flang: machreg.h File Reference
aarch64/machreg.h File Reference
#include "gbldefs.h"
Classes
struct MACH_REG
struct REG
struct RGSET
struct RGSETB
Macros
#define IR_FIRST_CALLEE_SAVE IR_ESI
#define IR_LAST_CALLEE_SAVE IR_EBP
#define GP_REG_NAMES
#define WORD_REG_NAMES
#define HALF_REG_NAMES
#define BYTE_REG_NAMES
#define IR_RAX IR_EAX
#define IR_RCX IR_ECX
#define IR_RDX IR_EDX
#define IR_RSI IR_ESI
#define IR_RDI IR_EDI
#define IR_RBX IR_EBX
#define IR_FRAMEP IR_EBP
#define IR_STACKP IR_ESP
#define N_GP_REGS 8
#define IR_FIRST 1
#define IR_LAST 8
#define XR_FIRST_CALLEE_SAVE 9 /* no callee-saved xmm regs */
#define XR_LAST_CALLEE_SAVE 8
#define XMM_REG_NAMES
#define YMM_REG_NAMES
#define ZMM_REG_NAMES
#define MAX_N_XMM_REGS 8
#define XR_FIRST 1
#define XR_LAST 8
#define XR_NUM_REGS 8 /* only used in {hammer,llvm}/src/llvect.c */
#define MAX_N_REGS (N_GP_REGS + MAX_N_XMM_REGS)
#define IR_NUM_NAMES N_GP_REGS + 1 /* only used in dwarf2.c! */
#define RAX gp_reg[IR_EAX]
#define RBX gp_reg[IR_EBX]
#define RCX gp_reg[IR_ECX]
#define RDX gp_reg[IR_EDX]
#define RDI gp_reg[IR_EDI]
#define RSI gp_reg[IR_ESI]
#define RBP gp_reg[IR_EBP]
#define RSP gp_reg[IR_ESP]
#define EAX word_reg[IR_EAX]
#define EBX word_reg[IR_EBX]
#define ECX word_reg[IR_ECX]
#define EDX word_reg[IR_EDX]
#define EDI word_reg[IR_EDI]
#define ESI word_reg[IR_ESI]
#define EBP word_reg[IR_EBP]
#define ESP word_reg[IR_ESP]
#define FR_RETVAL XR_XMM0
#define SP_RETVAL XR_XMM0
#define DP_RETVAL XR_XMM0
#define QP_RETVAL XR_XMM0
#define CS_RETVAL XR_XMM0
#define CD_RETVAL XR_XMM0
#define IR_RETVAL IR_RAX
#define AR_RETVAL IR_RAX
#define MEMARG_OFFSET 8
#define MR_MAX_IREG_ARGS 0
#define MR_MAX_XREG_ARGS 8
#define MR_MAX_FREG_ARGS 0
#define MR_MAX_IREG_RES 2
#define MR_MAX_XREG_RES 2
#define ARG_IR(i) (scratch_regs[i]) /* initialized in machreg.c */
#define ARG_XR(i) (mr_arg_xr[i])
#define RES_IR(i) (mr_res_ir[i])
#define RES_XR(i) (mr_res_xr[i])
#define AR(i) IR_RETVAL /* used only for pgftn/386 */
#define IR(i) ARG_IR(i)
#define SP(i) ARG_XR(i)
#define DP(i) ARG_XR(i)
#define QP(i) ARG_XR(i)
#define ISP(i) (i + 100) /* not used? */
#define IDP(i) (i + 100)
#define IR_ARET IR_RETVAL
#define KR_LSH(i) (((i) >> 8) & 0xff)
#define KR_MSH(i) ((i)&0xff)
#define KR_PACK(ms, ls) (((ls) << 8) | (ms))
#define KR_RETVAL KR_PACK(IR_EDX, IR_EAX)
#define MR_UNIQ 3
#define GR_THRESHOLD 2
#define MR_L1 1
#define MR_U1 3
#define MR_MAX1 (MR_U1 - MR_L1 + 1)
#define MR_L2 2
#define MR_U2 4
#define MR_MAX2 (MR_U2 - MR_L2 + 1)
#define MR_L3 2
#define MR_U3 4
#define MR_MAX3 (MR_U3 - MR_L3 + 1)
#define MR_NUMGLB (MR_MAX1 + MR_MAX2 + MR_MAX3)
#define MR_IR_AVAIL(c) 0
#define MR_GI_IR_LOW 0
#define MR_GI_IR_HIGH (MR_U1 - MR_L1)
#define MR_GI_IS_SCR_IR(i) ((i) > (MR_U1 - MR_L1))
#define RGSETG(i) rgsetb.stg_base[i]
#define RGSET_XR(i) rgsetb.stg_base[i].xr
#define SET_RGSET_XR(i, reg)
#define TST_RGSET_XR(i, reg) ((RGSET_XR(i) >> (reg)) & 1)
Enumerations
enum IR_REGS {
NO_REG = -1 , IR_EAX = 1 , IR_ECX , IR_EDX ,
IR_ESI , IR_EDI , IR_EBX , IR_EBP ,
IR_ESP , NO_REG = -1 , IR_EAX = 1 , IR_ECX ,
IR_EDX , IR_ESI , IR_EDI , IR_EBX ,
IR_EBP , IR_ESP , NO_REG = -1 , IR_RAX = 1 ,
IR_RCX , IR_RDX , IR_RSI , IR_RDI ,
IR_R8 , IR_R9 , IR_R10 , IR_R11 ,
IR_RBX , IR_RBP , IR_R12 , IR_R13 ,
IR_R14 , IR_R15 , IR_RSP
}
enum XR_REGS {
XR_XMM0 = 1 , XR_XMM1 , XR_XMM2 , XR_XMM3 ,
XR_XMM4 , XR_XMM5 , XR_XMM6 , XR_XMM7 ,
XR_XMM0 = 1 , XR_XMM1 , XR_XMM2 , XR_XMM3 ,
XR_XMM4 , XR_XMM5 , XR_XMM6 , XR_XMM7 ,
XR_XMM0 = 1 , XR_XMM1 , XR_XMM2 , XR_XMM3 ,
XR_XMM4 , XR_XMM5 , XR_XMM6 , XR_XMM7 ,
XR_XMM8 , XR_XMM9 , XR_XMM10 , XR_XMM11 ,
XR_XMM12 , XR_XMM13 , XR_XMM14 , XR_XMM15 ,
XR_XMM16 , XR_XMM17 , XR_XMM18 , XR_XMM19 ,
XR_XMM20 , XR_XMM21 , XR_XMM22 , XR_XMM23 ,
XR_XMM24 , XR_XMM25 , XR_XMM26 , XR_XMM27 ,
XR_XMM28 , XR_XMM29 , XR_XMM30 , XR_XMM31
}
Functions
int mr_getnext (int rtype)
int mr_getreg (int rtype)
get a global register for a given register type (RATA_IR, etc.). NOTE that the global registers are allocated in increasing order. next_global locates the next available global register. The range of global register values is from first_global to last_global, inclusive.
int mr_get_rgset ()
allocate and initialize a RGSET entry.
int mr_gindex (int rtype, int regno)
map a register type and global register number to an index value in the range 0 .. MR_NUMGLB-1, taking into consideration that certain register types map to the same machine register set.
void mr_end ()
communicate to the scheduler the first global register not assigned for each register class
void mr_init ()
Initialize mach_reg structs and reg array. This is done for each function (subprogram)
void mr_reset_frglobals ()
void mr_reset (int rtype)
Initialize for scanning the entire machine register set used for rtype.
void mr_reset_numglobals (int)
Variables
const int scratch_regs []
char * gp_reg [N_GP_REGS+1]
char * word_reg [N_GP_REGS+1]
char * half_reg [N_GP_REGS+1]
char * byte_reg [N_GP_REGS+1]
char * xm_reg [MAX_N_XMM_REGS+1]
char * ym_reg [MAX_N_XMM_REGS+1]
char * zm_reg [MAX_N_XMM_REGS+1]
int mr_arg_ir [MR_MAX_IREG_ARGS+1]
int mr_arg_xr [MR_MAX_XREG_ARGS+1]
int mr_res_ir [MR_MAX_IREG_RES+1]
int mr_res_xr [MR_MAX_XREG_RES+1]
REG reg []
RGSETB rgsetb
Macro Definition Documentation
AR
#define AR (i) IR_RETVAL /* used only for pgftn/386 */
Definition at line 197 of file aarch64/machreg.h.
AR_RETVAL
#define AR_RETVAL IR_RAX
Definition at line 174 of file aarch64/machreg.h.
ARG_IR
#define ARG_IR (i) (scratch_regs[i]) /* initialized in machreg.c */
Definition at line 192 of file aarch64/machreg.h.
ARG_XR
#define ARG_XR (i) (mr_arg_xr[i])
Definition at line 193 of file aarch64/machreg.h.
BYTE_REG_NAMES
#define BYTE_REG_NAMES
Value:
  {                                                                 \
    "%badreg3", "%al", "%cl", "%dl", "%badreg4", "%badreg5", "%bl", \
        "%badreg6", "%badreg7"                                      \
  }
Definition at line 63 of file aarch64/machreg.h.
CD_RETVAL
#define CD_RETVAL XR_XMM0
Definition at line 171 of file aarch64/machreg.h.
CS_RETVAL
#define CS_RETVAL XR_XMM0
Definition at line 170 of file aarch64/machreg.h.
DP
#define DP (i) ARG_XR(i)
Definition at line 200 of file aarch64/machreg.h.
DP_RETVAL
#define DP_RETVAL XR_XMM0
Definition at line 168 of file aarch64/machreg.h.
EAX
#define EAX word_reg[IR_EAX]
Definition at line 155 of file aarch64/machreg.h.
EBP
#define EBP word_reg[IR_EBP]
Definition at line 161 of file aarch64/machreg.h.
EBX
#define EBX word_reg[IR_EBX]
Definition at line 156 of file aarch64/machreg.h.
ECX
#define ECX word_reg[IR_ECX]
Definition at line 157 of file aarch64/machreg.h.
EDI
#define EDI word_reg[IR_EDI]
Definition at line 159 of file aarch64/machreg.h.
EDX
#define EDX word_reg[IR_EDX]
Definition at line 158 of file aarch64/machreg.h.
ESI
#define ESI word_reg[IR_ESI]
Definition at line 160 of file aarch64/machreg.h.
ESP
#define ESP word_reg[IR_ESP]
Definition at line 162 of file aarch64/machreg.h.
FR_RETVAL
#define FR_RETVAL XR_XMM0
Definition at line 166 of file aarch64/machreg.h.
GP_REG_NAMES
#define GP_REG_NAMES
Value:
  {                                                                            \
    "%badreg0", "%eax", "%ecx", "%edx", "%esi", "%edi", "%ebx", "%ebp", "%esp" \
  }
Definition at line 48 of file aarch64/machreg.h.
GR_THRESHOLD
#define GR_THRESHOLD 2
Definition at line 224 of file aarch64/machreg.h.
HALF_REG_NAMES
#define HALF_REG_NAMES
Value:
  {                                                                    \
    "%badreg2", "%ax", "%cx", "%dx", "%si", "%di", "%bx", "%bp", "%sp" \
  }
Definition at line 58 of file aarch64/machreg.h.
IDP
#define IDP (i) (i + 100)
Definition at line 203 of file aarch64/machreg.h.
IR
#define IR (i) ARG_IR(i)
Definition at line 198 of file aarch64/machreg.h.
IR_ARET
#define IR_ARET IR_RETVAL
Definition at line 207 of file aarch64/machreg.h.
IR_FIRST
#define IR_FIRST 1
Definition at line 81 of file aarch64/machreg.h.
IR_FIRST_CALLEE_SAVE
#define IR_FIRST_CALLEE_SAVE IR_ESI
Definition at line 45 of file aarch64/machreg.h.
IR_FRAMEP
#define IR_FRAMEP IR_EBP
Definition at line 77 of file aarch64/machreg.h.
IR_LAST
#define IR_LAST 8
Definition at line 82 of file aarch64/machreg.h.
IR_LAST_CALLEE_SAVE
#define IR_LAST_CALLEE_SAVE IR_EBP
Definition at line 46 of file aarch64/machreg.h.
IR_NUM_NAMES
#define IR_NUM_NAMES N_GP_REGS + 1 /* only used in dwarf2.c! */
Definition at line 136 of file aarch64/machreg.h.
IR_RAX
#define IR_RAX IR_EAX
Definition at line 71 of file aarch64/machreg.h.
IR_RBX
#define IR_RBX IR_EBX
Definition at line 76 of file aarch64/machreg.h.
IR_RCX
#define IR_RCX IR_ECX
Definition at line 72 of file aarch64/machreg.h.
IR_RDI
#define IR_RDI IR_EDI
Definition at line 75 of file aarch64/machreg.h.
IR_RDX
#define IR_RDX IR_EDX
Definition at line 73 of file aarch64/machreg.h.
IR_RETVAL
#define IR_RETVAL IR_RAX
Definition at line 173 of file aarch64/machreg.h.
IR_RSI
#define IR_RSI IR_ESI
Definition at line 74 of file aarch64/machreg.h.
IR_STACKP
#define IR_STACKP IR_ESP
Definition at line 78 of file aarch64/machreg.h.
ISP
#define ISP (i) (i + 100) /* not used? */
Definition at line 202 of file aarch64/machreg.h.
KR_LSH
#define KR_LSH (i) (((i) >> 8) & 0xff)
Definition at line 211 of file aarch64/machreg.h.
KR_MSH
#define KR_MSH (i) ((i)&0xff)
Definition at line 212 of file aarch64/machreg.h.
KR_PACK
#define KR_PACK (ms, ls) (((ls) << 8) | (ms))
Definition at line 213 of file aarch64/machreg.h.
KR_RETVAL
#define KR_RETVAL KR_PACK(IR_EDX, IR_EAX)
Definition at line 218 of file aarch64/machreg.h.
MAX_N_REGS
#define MAX_N_REGS (N_GP_REGS + MAX_N_XMM_REGS)
Definition at line 128 of file aarch64/machreg.h.
MAX_N_XMM_REGS
#define MAX_N_XMM_REGS 8
Definition at line 123 of file aarch64/machreg.h.
MEMARG_OFFSET
#define MEMARG_OFFSET 8
Definition at line 175 of file aarch64/machreg.h.
MR_GI_IR_HIGH
#define MR_GI_IR_HIGH (MR_U1 - MR_L1)
Definition at line 259 of file aarch64/machreg.h.
MR_GI_IR_LOW
#define MR_GI_IR_LOW 0
Definition at line 258 of file aarch64/machreg.h.
MR_GI_IS_SCR_IR
#define MR_GI_IS_SCR_IR (i) ((i) > (MR_U1 - MR_L1))
Definition at line 260 of file aarch64/machreg.h.
MR_IR_AVAIL
#define MR_IR_AVAIL (c) 0
Definition at line 253 of file aarch64/machreg.h.
MR_L1
#define MR_L1 1
Definition at line 231 of file aarch64/machreg.h.
MR_L2
#define MR_L2 2
Definition at line 236 of file aarch64/machreg.h.
MR_L3
#define MR_L3 2
Definition at line 241 of file aarch64/machreg.h.
MR_MAX1
#define MR_MAX1 (MR_U1 - MR_L1 + 1)
Definition at line 233 of file aarch64/machreg.h.
MR_MAX2
#define MR_MAX2 (MR_U2 - MR_L2 + 1)
Definition at line 238 of file aarch64/machreg.h.
MR_MAX3
#define MR_MAX3 (MR_U3 - MR_L3 + 1)
Definition at line 243 of file aarch64/machreg.h.
MR_MAX_FREG_ARGS
#define MR_MAX_FREG_ARGS 0
Definition at line 180 of file aarch64/machreg.h.
MR_MAX_IREG_ARGS
#define MR_MAX_IREG_ARGS 0
Definition at line 177 of file aarch64/machreg.h.
MR_MAX_IREG_RES
#define MR_MAX_IREG_RES 2
Definition at line 182 of file aarch64/machreg.h.
MR_MAX_XREG_ARGS
#define MR_MAX_XREG_ARGS 8
Definition at line 178 of file aarch64/machreg.h.
MR_MAX_XREG_RES
#define MR_MAX_XREG_RES 2
Definition at line 183 of file aarch64/machreg.h.
MR_NUMGLB
#define MR_NUMGLB (MR_MAX1 + MR_MAX2 + MR_MAX3)
Definition at line 248 of file aarch64/machreg.h.
MR_U1
#define MR_U1 3
Definition at line 232 of file aarch64/machreg.h.
MR_U2
#define MR_U2 4
Definition at line 237 of file aarch64/machreg.h.
MR_U3
#define MR_U3 4
Definition at line 242 of file aarch64/machreg.h.
MR_UNIQ
#define MR_UNIQ 3
Definition at line 222 of file aarch64/machreg.h.
N_GP_REGS
#define N_GP_REGS 8
Definition at line 80 of file aarch64/machreg.h.
QP
#define QP (i) ARG_XR(i)
Definition at line 201 of file aarch64/machreg.h.
QP_RETVAL
#define QP_RETVAL XR_XMM0
Definition at line 169 of file aarch64/machreg.h.
RAX
#define RAX gp_reg[IR_EAX]
Definition at line 146 of file aarch64/machreg.h.
RBP
#define RBP gp_reg[IR_EBP]
Definition at line 152 of file aarch64/machreg.h.
RBX
#define RBX gp_reg[IR_EBX]
Definition at line 147 of file aarch64/machreg.h.
RCX
#define RCX gp_reg[IR_ECX]
Definition at line 148 of file aarch64/machreg.h.
RDI
#define RDI gp_reg[IR_EDI]
Definition at line 150 of file aarch64/machreg.h.
RDX
#define RDX gp_reg[IR_EDX]
Definition at line 149 of file aarch64/machreg.h.
RES_IR
#define RES_IR (i) (mr_res_ir[i])
Definition at line 194 of file aarch64/machreg.h.
RES_XR
#define RES_XR (i) (mr_res_xr[i])
Definition at line 195 of file aarch64/machreg.h.
RGSET_XR
#define RGSET_XR (i) rgsetb.stg_base[i].xr
Definition at line 328 of file aarch64/machreg.h.
RGSETG
#define RGSETG (i) rgsetb.stg_base[i]
Definition at line 326 of file aarch64/machreg.h.
RSI
#define RSI gp_reg[IR_ESI]
Definition at line 151 of file aarch64/machreg.h.
RSP
#define RSP gp_reg[IR_ESP]
Definition at line 153 of file aarch64/machreg.h.
SET_RGSET_XR
#define SET_RGSET_XR (i, reg)
Value:
  {                              \
    RGSET_XR(i) |= (1 << (reg)); \
  }
Definition at line 330 of file aarch64/machreg.h.
SP
#define SP (i) ARG_XR(i)
Definition at line 199 of file aarch64/machreg.h.
SP_RETVAL
#define SP_RETVAL XR_XMM0
Definition at line 167 of file aarch64/machreg.h.
TST_RGSET_XR
#define TST_RGSET_XR (i, reg) ((RGSET_XR(i) >> (reg)) & 1)
Definition at line 335 of file aarch64/machreg.h.
WORD_REG_NAMES
#define WORD_REG_NAMES
Value:
  {                                                                            \
    "%badreg1", "%eax", "%ecx", "%edx", "%esi", "%edi", "%ebx", "%ebp", "%esp" \
  }
Definition at line 53 of file aarch64/machreg.h.
XMM_REG_NAMES
#define XMM_REG_NAMES
Value:
  {                                                                           \
    "%badxmm", "%xmm0", "%xmm1", "%xmm2", "%xmm3", "%xmm4", "%xmm5", "%xmm6", \
        "%xmm7"                                                               \
  }
Definition at line 105 of file aarch64/machreg.h.
XR_FIRST
#define XR_FIRST 1
Definition at line 124 of file aarch64/machreg.h.
XR_FIRST_CALLEE_SAVE
#define XR_FIRST_CALLEE_SAVE 9 /* no callee-saved xmm regs */
Definition at line 102 of file aarch64/machreg.h.
XR_LAST
#define XR_LAST 8
Definition at line 125 of file aarch64/machreg.h.
XR_LAST_CALLEE_SAVE
#define XR_LAST_CALLEE_SAVE 8
Definition at line 103 of file aarch64/machreg.h.
XR_NUM_REGS
#define XR_NUM_REGS 8 /* only used in {hammer,llvm}/src/llvect.c */
Definition at line 126 of file aarch64/machreg.h.
YMM_REG_NAMES
#define YMM_REG_NAMES
Value:
  {                                                                           \
    "%badymm", "%ymm0", "%ymm1", "%ymm2", "%ymm3", "%ymm4", "%ymm5", "%ymm6", \
        "%ymm7"                                                               \
  }
Definition at line 111 of file aarch64/machreg.h.
ZMM_REG_NAMES
#define ZMM_REG_NAMES
Value:
  {                                                                           \
    "%badzmm", "%zmm0", "%zmm1", "%zmm2", "%zmm3", "%zmm4", "%zmm5", "%zmm6", \
        "%zmm7"                                                               \
  }
Definition at line 117 of file aarch64/machreg.h.
Enumeration Type Documentation
IR_REGS
enum IR_REGS
Enumerator
NO_REG
IR_EAX
IR_ECX
IR_EDX
IR_ESI
IR_EDI
IR_EBX
IR_EBP
IR_ESP
NO_REG
IR_EAX
IR_ECX
IR_EDX
IR_ESI
IR_EDI
IR_EBX
IR_EBP
IR_ESP
NO_REG
IR_RAX
IR_RCX
IR_RDX
IR_RSI
IR_RDI
IR_R8
IR_R9
IR_R10
IR_R11
IR_RBX
IR_RBP
IR_R12
IR_R13
IR_R14
IR_R15
IR_RSP
Definition at line 33 of file aarch64/machreg.h.
XR_REGS
enum XR_REGS
Enumerator
XR_XMM0
XR_XMM1
XR_XMM2
XR_XMM3
XR_XMM4
XR_XMM5
XR_XMM6
XR_XMM7
XR_XMM0
XR_XMM1
XR_XMM2
XR_XMM3
XR_XMM4
XR_XMM5
XR_XMM6
XR_XMM7
XR_XMM0
XR_XMM1
XR_XMM2
XR_XMM3
XR_XMM4
XR_XMM5
XR_XMM6
XR_XMM7
XR_XMM8
XR_XMM9
XR_XMM10
XR_XMM11
XR_XMM12
XR_XMM13
XR_XMM14
XR_XMM15
XR_XMM16
XR_XMM17
XR_XMM18
XR_XMM19
XR_XMM20
XR_XMM21
XR_XMM22
XR_XMM23
XR_XMM24
XR_XMM25
XR_XMM26
XR_XMM27
XR_XMM28
XR_XMM29
XR_XMM30
XR_XMM31
Definition at line 88 of file aarch64/machreg.h.
Function Documentation
mr_end()
void mr_end (void)
communicate to the scheduler the first global register not assigned for each register class
Note that this will be the physical register number; it reflects the number of registers assigned from the physical set mapped from the generic register set. Because two or more generic register sets can map to a single register set, this information can only be computed after all of the assignments are done.
Definition at line 250 of file machreg.cpp.
References aux, AUX::curr_entry, ENTRY::first_ar, ENTRY::first_dp, ENTRY::first_dr, ENTRY::first_sp, REG::mach_reg, MACH_REG::nused, RATA_AR, RATA_DP, RATA_IR, RATA_SP, and reg.
Referenced by reg_assign1().
mr_get_rgset()
int mr_get_rgset ()
allocate and initialize a RGSET entry.
Definition at line 375 of file machreg.cpp.
References CNULL, ERR_Fatal, error(), MAXRAT, NEED, NULL, RGSET_XR, rgsetb, RGSETB::stg_avail, RGSETB::stg_base, and RGSETB::stg_size.
Referenced by merge_rgset().
mr_getnext()
int mr_getnext (int rtype)
\func Attempt to retrieve the next available register from the set used for rtype.
If one is found, it may be necessary to update the mach_reg info since we're scanning the entire set. mr_getreg uses a portion of the set (as defined by the reg structure); things could get out of sync when registers of different rtypes share the same register set.
Definition at line 302 of file machreg.cpp.
References _mr_getnext().
mr_getreg()
int mr_getreg (int rtype)
get a global register for a given register type (RATA_IR, etc.). NOTE that the global registers are allocated in increasing order. next_global locates the next available global register. The range of global register values is from first_global to last_global, inclusive.
Definition at line 175 of file machreg.cpp.
References _mr_getreg().
Referenced by assign1().
mr_gindex()
int mr_gindex (int rtype, int regno)
map a register type and global register number to an index value in the range 0 .. MR_NUMGLB-1, taking into consideration that certain register types map to the same machine register set.
This is used by * the optimizer to index into its register history table.
Definition at line 233 of file machreg.cpp.
References MACH_REG::first_global, REG::mach_reg, MACH_REG::mapbase, and reg.
mr_init()
void mr_init ()
Initialize mach_reg structs and reg array. This is done for each function (subprogram)
Definition at line 109 of file machreg.cpp.
References aux, AUX::curr_entry, ENTRY::first_ar, ENTRY::first_dp, ENTRY::first_dr, MACH_REG::first_global, ENTRY::first_sp, i, REG::mach_reg, mach_reg, MR_UNIQ, MACH_REG::next_global, MACH_REG::nused, REG::nused, RATA_AR, RATA_DP, RATA_IR, RATA_RTYPES_ACTIVE, RATA_SP, REG::rcand, reg, and XBIT.
Referenced by reg_init().
mr_reset()
void mr_reset (int rtype)
Initialize for scanning the entire machine register set used for rtype.
This mechanism for retrieving registers is done when we can no longer retrieve registers from mr_getreg (we're out of rtype registers). Ensuing calls to mr_getnext will attempt to retrieve a register from the set. The assumption is that the caller (optimizer) will first call mr_reset, and then call mr_getnext one or more times.
Definition at line 279 of file machreg.cpp.
References MACH_REG::first_global, getnext_reg, REG::mach_reg, RATA_AR, RATA_IR, RATA_KR, reg, and XBIT.
mr_reset_frglobals()
void mr_reset_frglobals ()
Definition at line 161 of file machreg.cpp.
References MACH_REG::first_global, MACH_REG::last_global, and mach_reg.
Referenced by exp_end().
mr_reset_numglobals()
void mr_reset_numglobals (int reduce_by)
Definition at line 155 of file machreg.cpp.
References MACH_REG::end_global, MACH_REG::last_global, and mach_reg.
Referenced by exp_end().
Variable Documentation
byte_reg
char* byte_reg[N_GP_REGS+1] extern
gp_reg
char* gp_reg[N_GP_REGS+1] extern
half_reg
char* half_reg[N_GP_REGS+1] extern
mr_arg_ir
int mr_arg_ir[MR_MAX_IREG_ARGS+1] extern
Definition at line 91 of file machreg.cpp.
mr_arg_xr
int mr_arg_xr[MR_MAX_XREG_ARGS+1] extern
Definition at line 94 of file machreg.cpp.
mr_res_ir
int mr_res_ir[MR_MAX_IREG_RES+1] extern
Definition at line 99 of file machreg.cpp.
mr_res_xr
int mr_res_xr[MR_MAX_XREG_RES+1] extern
Definition at line 101 of file machreg.cpp.
reg
REG reg[] extern
Definition at line 37 of file machreg.cpp.
Referenced by _assn_rtemp(), ad_func(), addrcand(), assign1(), cpuSupportsAVX2(), cpuSupportsAVX512F(), cpuSupportsFMA(), dmprcand(), and endrcand().
rgsetb
RGSETB rgsetb extern
Definition at line 55 of file machreg.cpp.
Referenced by ds_init(), and exp_cleanup().
scratch_regs
const int scratch_regs[] extern
Definition at line 57 of file machreg.cpp.
word_reg
char* word_reg[N_GP_REGS+1] extern
xm_reg
char* xm_reg[MAX_N_XMM_REGS+1] extern
ym_reg
char* ym_reg[MAX_N_XMM_REGS+1] extern
zm_reg
char* zm_reg[MAX_N_XMM_REGS+1] extern