flang: ll_abi.cpp File Reference
aarch64/ll_abi.cpp File Reference
#include "gbldefs.h"
#include "global.h"
#include "symtab.h"
#include "llutil.h"
#include "ll_structure.h"
#include "dtypeutl.h"
Classes
struct arm_homogeneous_aggr
struct ARM_ABI_ArgInfo_
Macros
#define DT_VOIDNONE DT_NONE
#define DT_BASETYPE(dt) (dt)
Typedefs
typedef struct ARM_ABI_ArgInfo_ ARM_ABI_ArgInfo
Functions
void ll_abi_compute_call_conv (LL_ABI_Info *abi, int func_sptr, int jsra_flags)
...
static void update_arg_info (LL_ABI_ArgInfo *arg, ARM_ABI_ArgInfo *arm_arg)
static int update_homogeneous (void *context, DTYPE dtype, unsigned address, int member_sptr)
static LL_Type * check_vfp (LL_Module *module, DTYPE dtype, struct arm_homogeneous_aggr *aggr)
static enum LL_ABI_ArgKind classify_int (DTYPE dtype)
static int ll_abi_num_regs (int num_bytes)
static bool classify_common (LL_Module *module, LL_ABI_Info *abi, ARM_ABI_ArgInfo *arg, DTYPE dtype)
void ll_abi_classify_return_dtype (LL_ABI_Info *abi, DTYPE dtype)
...
void ll_abi_classify_arg_dtype (LL_ABI_Info *abi, LL_ABI_ArgInfo *arg, DTYPE dtype)
...
unsigned ll_abi_classify_va_arg_dtype (LL_Module *module, DTYPE dtype, unsigned *num_gp, unsigned *num_fp)
...
Macro Definition Documentation
DT_BASETYPE
#define DT_BASETYPE (dt) (dt)
Definition at line 23 of file aarch64/ll_abi.cpp.
DT_VOIDNONE
#define DT_VOIDNONE DT_NONE
Definition at line 21 of file aarch64/ll_abi.cpp.
Typedef Documentation
ARM_ABI_ArgInfo
typedef struct ARM_ABI_ArgInfo_ ARM_ABI_ArgInfo
Function Documentation
check_vfp()
static LL_Type * check_vfp (LL_Module * module, DTYPE dtype, struct arm_homogeneous_aggr * aggr) static
Definition at line 110 of file aarch64/ll_abi.cpp.
References arm_homogeneous_aggr::base_bytes, arm_homogeneous_aggr::base_type, LL_Type_::data_type, ISZ_T, LL_DOUBLE, LL_FLOAT, ll_get_array_type(), LL_VECTOR, NULL, size, size_of(), update_homogeneous(), and visit_flattened_dtype().
Referenced by classify_common(), and ll_abi_classify_va_arg_dtype().
classify_common()
static bool classify_common (LL_Module * module, LL_ABI_Info * abi, ARM_ABI_ArgInfo * arg, DTYPE dtype) static
Definition at line 166 of file aarch64/ll_abi.cpp.
References arg, check_vfp(), classify_int(), DT_ISINT, DT_ISSCALAR, DT_VOIDNONE, DTY, ISZ_T, ll_abi_num_regs(), LL_ARG_COERCE, LL_ARG_DIRECT, LL_ARG_INDIRECT, LL_ARG_INDIRECT_BUFFERED, ll_coercion_type(), ll_create_basic_type(), ll_get_array_type(), LL_I64, arm_homogeneous_aggr::module, LL_ABI_Info_::module, NULL, size, and size_of().
Referenced by ll_abi_classify_arg_dtype(), and ll_abi_classify_return_dtype().
classify_int()
static enum LL_ABI_ArgKind classify_int (DTYPE dtype) static
Definition at line 149 of file aarch64/ll_abi.cpp.
References DT_ISUNSIGNED, LL_ARG_DIRECT, LL_ARG_SIGNEXT, LL_ARG_ZEROEXT, and size_of().
Referenced by classify_common().
ll_abi_classify_arg_dtype()
void ll_abi_classify_arg_dtype (LL_ABI_Info * abi, LL_ABI_ArgInfo * arg, DTYPE dtype)
...
Definition at line 278 of file aarch64/ll_abi.cpp.
References alignment(), arg, classify_common(), DT_BASETYPE, ISZ_T, LL_ARG_COERCE, LL_ARG_UNKNOWN, ll_create_basic_type(), ll_get_array_type(), LL_I32, LL_I64, LL_ABI_Info_::module, NULL, size, size_of(), and update_arg_info().
Referenced by gen_arg_operand(), ll_process_routine_parameters(), and process_ll_abi_func_ftn_mod().
ll_abi_classify_return_dtype()
void ll_abi_classify_return_dtype (LL_ABI_Info * abi, DTYPE dtype)
...
Definition at line 238 of file aarch64/ll_abi.cpp.
References LL_ABI_Info_::arg, classify_common(), DT_BASETYPE, LL_ABI_ArgInfo_::kind, LL_ARG_COERCE, LL_ARG_INDIRECT, LL_ARG_UNKNOWN, ll_create_basic_type(), LL_I16, LL_I32, LL_I64, LL_I8, LL_NOTYPE, LL_ABI_Info_::module, NULL, size_of(), LL_ABI_ArgInfo_::type, and update_arg_info().
Referenced by ll_abi_for_missing_prototype(), ll_check_struct_return(), and process_ll_abi_func_ftn_mod().
ll_abi_classify_va_arg_dtype()
unsigned ll_abi_classify_va_arg_dtype (LL_Module * module, DTYPE dtype, unsigned * num_gp, unsigned * num_fp)
...
Definition at line 307 of file aarch64/ll_abi.cpp.
References arm_homogeneous_aggr::base_bytes, check_vfp(), DT_ISINT, DTY, ISZ_T, ll_abi_num_regs(), arm_homogeneous_aggr::module, NULL, size, and size_of().
ll_abi_compute_call_conv()
void ll_abi_compute_call_conv (LL_ABI_Info * abi, int func_sptr, int jsra_flags)
...
Definition at line 26 of file aarch64/ll_abi.cpp.
References LL_ABI_Info_::call_conv, and LL_CallConv_C.
Referenced by ll_abi_for_missing_prototype(), and process_ll_abi_func_ftn_mod().
ll_abi_num_regs()
static int ll_abi_num_regs (int num_bytes) inline static
Definition at line 159 of file aarch64/ll_abi.cpp.
Referenced by classify_common(), and ll_abi_classify_va_arg_dtype().
update_arg_info()
static void update_arg_info (LL_ABI_ArgInfo * arg, ARM_ABI_ArgInfo * arm_arg) inline static
Definition at line 47 of file aarch64/ll_abi.cpp.
References arg, ARM_ABI_ArgInfo_::kind, and ARM_ABI_ArgInfo_::type.
Referenced by ll_abi_classify_arg_dtype(), and ll_abi_classify_return_dtype().
update_homogeneous()
static int update_homogeneous (void * context, DTYPE dtype, unsigned address, int member_sptr) static
Definition at line 58 of file aarch64/ll_abi.cpp.
References arm_homogeneous_aggr::base_bytes, arm_homogeneous_aggr::base_type, LL_Type_::data_type, DT_BASETYPE, DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_FLOAT, DTY, ll_convert_dtype(), LL_VECTOR, arm_homogeneous_aggr::module, size, and size_of().
Referenced by check_vfp().