flang: accpp.c File Reference
accpp.c File Reference
accpp.c - PGC ansi source preprocessor module.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "machar.h"
#include "version.h"
Classes
struct IFREC
struct PPSYM
struct INCLSTACK
struct PTOK
struct macstk_type
Macros
#define ACC_DBG
#define _CS 1 /* c symbol */
#define _DI 2 /* digit */
#define _BL 4 /* blank */
#define _HD 8 /* hex digit */
#define _WS 16 /* white space (' ' or '\t') */
#define MASK(c) ((int)c & 0xFF)
#define iscsym(c) (ctable[MASK(c)] & _CS)
#define iswhite(c) (ctable[MASK(c)] & _WS)
#define isblank(c) (ctable[MASK(c)] & _BL)
#define ishex(c) (ctable[MASK(c)] & (_HD | _DI))
#define isident(c) (ctable[MASK(c)] & (_CS | _DI))
#define isdig(c) (ctable[MASK(c)] & _DI)
#define ERR_OFFSET 700
#define pperror(n, x, sev)
#define pperr(n, sev) pperror(n, CNULL, sev)
#define LINELEN 12000
#define HASHSIZ 1031
#define TOKMAX 8192
#define IFMAX 20
#define MACMAX 6000
#define FORMALMAX 127 /* FS#14308 - set max formals to 127 */
#define ARGMAX 16384
#define TARGMAX 32768
#define MAX_PATHNAME_LEN 1024
#define MAXINC 20
#define MACSTK_MAX 100
#define ARGST 0xFE
#define SENTINEL 0xFD
#define NOSUBST 0xFC
#define NOFUNC 0xFB
#define STRINGIZE 0xFA
#define CONCAT 0xF9
#define ENDTOKEN 0xF8
#define CONCAT1 0xF7
#define WHITESPACE 0xF6
#define PRAGMAOP 0xF5
#define VA_ARGS 0xF4
#define VA_REST 0xF3
#define T_IDENT 'a'
#define T_NSIDENT 'b'
#define T_NOFIDENT 'f'
#define T_PPNUM 'p'
#define T_POUND (-2)
#define T_STRING 's'
#define T_WSTRING 'w'
#define T_CHAR 'c'
#define T_WCHAR 'z'
#define T_OP 'o'
#define T_CONCAT (-5)
#define T_SENTINEL (-3)
#define D_IF 1
#define D_ELIF 2
#define D_ELSE 3
#define D_ENDIF 4
#define D_IFDEF 5
#define D_IFNDEF 6
#define D_INCLUDE 7
#define D_DEFINE 8
#define D_UNDEF 9
#define D_LINE 10
#define D_PRAGMA 11
#define D_ERROR 12
#define D_MODULE 13
#define D_LIST 14
#define D_NOLIST 15
#define D_IDENT 16
#define D_INCLUDE_NEXT 17
#define D_WARNING 18
#define F_PREDEF 1
#define F_FUNCLIKE 2
#define F_CHAR 4
#define F_VA_ARGS 8
#define F_VA_REST 16
#define PPNUM_IS_32
#define PTOK_V(t) (t).val
#define PTOK_VUNS(a) (UINT *) PTOK_V(a)
#define PTOK_ISUNS(t) (t).isuns
#define FIXUL(a)
#define MKXUL(a)
#define PTOK_MUL(a, b) mul64(PTOK_V(a), PTOK_V(b), PTOK_V(a)) MKXUL(a)
#define PTOK_DIV(a, b) div64(PTOK_V(a), PTOK_V(b), PTOK_V(a))
#define PTOK_UDIV(a, b)
#define PTOK_MOD(a, b) mod64(PTOK_V(a), PTOK_V(b), PTOK_V(a))
#define PTOK_UMOD(a, b) umod64(PTOK_VUNS(a), PTOK_VUNS(b), PTOK_VUNS(a)) MKXUL(a)
#define PTOK_ADD(a, b) add64(PTOK_V(a), PTOK_V(b), PTOK_V(a)) MKXUL(a)
#define PTOK_SUB(a, b) sub64(PTOK_V(a), PTOK_V(b), PTOK_V(a)) MKXUL(a)
#define PTOK_NEG(a, b) neg64(PTOK_V(b), PTOK_V(a)) MKXUL(a)
#define PTOK_AND(a, b) and64(PTOK_V(a), PTOK_V(b), PTOK_V(a)) MKXUL(a)
#define PTOK_OR(a, b) or64(PTOK_V(a), PTOK_V(b), PTOK_V(a)) MKXUL(a)
#define PTOK_XOR(a, b) xor64(PTOK_V(a), PTOK_V(b), PTOK_V(a)) MKXUL(a)
#define PTOK_BNOT(a, b) not64(PTOK_V(b), PTOK_V(a)) MKXUL(a)
#define PTOK_LNOT(a, b) PTOK_ASSN32(a, cmp64(PTOK_V(b), zero64) == 0)
#define PTOK_ANDAND(a, b) PTOK_ASSN32(a, cmp64(PTOK_V(a), zero64) && cmp64(PTOK_V(b), zero64))
#define PTOK_OROR(a, b) PTOK_ASSN32(a, cmp64(PTOK_V(a), zero64) || cmp64(PTOK_V(b), zero64))
#define PTOK_LSHIFT(a, b) shf64(PTOK_V(a), PTOK_V(b)[1], PTOK_V(a)) MKXUL(a)
#define PTOK_URSHIFT(a, b) ushf64(PTOK_VUNS(a), -PTOK_V(b)[1], PTOK_VUNS(a)) MKXUL(a)
#define PTOK_CRSHIFT(a, b) shf64(PTOK_V(a), -PTOK_V(b)[1], PTOK_V(a)) MKXUL(a)
#define PTOK_CMP(a, b) cmp64(PTOK_V(a), PTOK_V(b))
#define PTOK_LOGEQ(a, b) PTOK_ASSN32(a, PTOK_CMP(a, b) == 0)
#define PTOK_LOGNE(a, b) PTOK_ASSN32(a, PTOK_CMP(a, b) != 0)
#define PTOK_LOGLT(a, b) PTOK_ASSN32(a, PTOK_CMP(a, b) < 0)
#define PTOK_LOGLE(a, b) PTOK_ASSN32(a, PTOK_CMP(a, b) <= 0)
#define PTOK_LOGGT(a, b) PTOK_ASSN32(a, PTOK_CMP(a, b) > 0)
#define PTOK_LOGGE(a, b) PTOK_ASSN32(a, PTOK_CMP(a, b) >= 0)
#define PTOK_UCMP(a, b) ucmp64(PTOK_VUNS(a), PTOK_VUNS(b))
#define PTOK_LOGULT(a, b) PTOK_ASSN32(a, PTOK_UCMP(a, b) < 0)
#define PTOK_LOGULE(a, b) PTOK_ASSN32(a, PTOK_UCMP(a, b) <= 0)
#define PTOK_LOGUGT(a, b) PTOK_ASSN32(a, PTOK_UCMP(a, b) > 0)
#define PTOK_LOGUGE(a, b) PTOK_ASSN32(a, PTOK_UCMP(a, b) >= 0)
#define PTOK_ISNEG(a) (cmp64(PTOK_V(a), zero64) < 0)
#define PTOK_ISNZ(a) (cmp64(PTOK_V(a), zero64) != 0)
#define PTOK_ASSN(a, b) (void)(PTOK_V(a)[0] = PTOK_V(b)[0], PTOK_V(a)[1] = PTOK_V(b)[1])
#define PTOK_ASSN32(a, i) (void)(PTOK_V(a)[1] = (i), PTOK_V(a)[0] = 0)
#define PTOK_LSHIFT32(a, i) PTOK_V(a)[1] <<= (i)
#define PTOK_OR32(a, i) PTOK_V(a)[1] |= (i)
#define PTOK_BTEST32(a, i) (PTOK_V(a)[1] & (i))
#define PTOK_SEXTEND32(a)
#define ifstack(name) _ifs[iftop].name
#define INCLPATH(i) (idir.b + idir.path[i])
#define GROW_ARGBUF(argbuf, argp, fstart, argbufsize, newsize)
#define chkdef(name, val)
#define PP_MAJOR "__FLANG_MAJOR__"
#define PP_MINOR "__FLANG_MINOR__"
#define PP_PATCHLEVEL "__FLANG_PATCHLEVEL__"
#define GROW_MACBUF(amt, p)
#define Number 1
#define Lparen 2
#define Rparen 3
#define Eoln 4
#define Defined 5
#define Mult 6
#define Divide 7
#define Mod 8
#define Plus 9
#define Minus 10
#define Lshift 11
#define Rshift 12
#define Lt 13
#define Gt 14
#define Le 15
#define Ge 16
#define Eq 17
#define Ne 18
#define And 19
#define Xor 20
#define Or 21
#define Andand 22
#define Oror 23
#define Question 24
#define Colon 25
#define Comma 26
#define Minusx 27 /* unary minus operation */
#define Not 28
#define Compl 29 /* ~ */
#define Predicate 30
#define Plusx 31 /* unary plus */
#define CHECK(t)
#define UCONV
#define inchar() (lineptr < lineend ? *lineptr++ : _nextline())
#define NPRED 20
Typedefs
typedef char INCLENTRY[MAX_PATHNAME_LEN]
Functions
static void mod64 (DBLINT64, DBLINT64, DBLINT64)
static void umod64 (DBLUINT64, DBLUINT64, DBLUINT64)
void accpp (void)
void setasmmode (void)
static void delete (const char *)
static void pbchar (int)
static void pbstr (const char *)
static void clreol (int)
static int dlookup (char *)
static void dodef (int cmdline)
Default behavior: Add whitespace at the beginning and end of the macro body, and between tokens in the macro body.
static void doincl (LOGICAL)
static void _doincl (char *, int, LOGICAL)
static void domodule (void)
static INT doparse (void)
static void doundef (int)
static int gtok (char *tokval, int expflag)
static void ifpush (void)
static PPSYM * lookup (const char *, int)
static void ptok (const char *)
static int subst (PPSYM *)
static INT strstore (const char *)
static INT tobinary (char *, int *, INT *)
static INT tobinary64 (char *, int *, DBLINT64)
static int gettoken (void)
static void parse (int rbp, PTOK *tk)
parse "current" expression and return value computed by constant folding it.
static void pr_line (const char *name, int line, LOGICAL from_stdinc)
Format of pr_line output: # line "file_full_path" "from_stdinc".
static void doline (int, char *)
static int dopragma (void)
static void doerror (void)
static void dowarning (void)
static void doident (void)
static int findtok (char *, int)
static int macro_recur_check (PPSYM *)
static int predarg (char *)
static void predicate (char *)
static ptrdiff_t realloc_linebuf (ptrdiff_t)
static int nextok (char *, int)
static int _nextline (void)
static int mac_push (PPSYM *, char *)
static void popstack (void)
static void stash_paths (const char *)
static void dumpval (char *, FILE *)
static void dumpmac (PPSYM *sp)
static void putmac (PPSYM *)
static void putunmac (char *mac)
output undefine macro
static void update_actuals (char **, int, char *, char *)
static int skipbl (char *tokval, int flag)
void print_and_check (FILE *ff, char *str, char end_c)
Replaces fprintf (ff, format, str) ,.
static void acc_display_macros ()
static int inlist (int *list, int nl, char *value, char *macbuf)
static void add_to_incllist (char *fullname)
Add fullname to the list of include files in incllist.
void setsuffix (char *newsuffix)
Variables
static char ctable [256]
static FILE * ifp
static int iftop
static int ifsize
static IFREC * _ifs
static INT hashtab [HASHSIZ]
static PPSYM * hashrec
static INT nhash
static INT next_hash
static char * deftab
static INT ndef
static INT next_def
static const char * suffix = ".o"
static const char * prevfile = NULL
static int prevline = -1
static LOGICAL in_dodef
static LOGICAL in_ftn_comment
static DBLINT64 zero64 = {0, 0}
static int token
static PTOK tokenval
static int syntaxerr
static INCLSTACK * inclstack
static INT incsize
static INT inclev = 0
static INCLENTRY * incllist
static int incfiles = 0
static int inclsize
static char * lineptr
static char * lineend
static char * savlptr
static int linelen
static INT linesize
static char * linebuf
static int lineloc
static int fileloc
static char cur_fname [MAX_PATHNAME_LEN]
static int cur_line
static LOGICAL cur_from_stdinc
static char filename [MAX_PATHNAME_LEN] = {'\0'}
static char dirwork [MAX_PATHNAME_LEN]
static int startline
static int pflag
static int list_flag
static struct macstk_type macstk [MACSTK_MAX]
static int macstk_top = -1
static int toktyp
static int nifile
struct {
int * path
int cnt
int sz
char * b
int b_avl
int b_sz
int last
} idir
static LOGICAL cpp_comments
static LOGICAL asm_mode = FALSE
struct {
INT8 led
INT8 nud
short lbp
INT8 rbp
} PT []
define parse table, PT, which has an entry for each of the tokens just defined:
static char * predtab [NPRED]
static int prednum = 1
static int pred = 0
Detailed Description
accpp.c - PGC ansi source preprocessor module.
Definition in file accpp.c.
Macro Definition Documentation
_BL
#define _BL 4 /* blank */
Definition at line 28 of file accpp.c.
_CS
#define _CS 1 /* c symbol */
Definition at line 26 of file accpp.c.
_DI
#define _DI 2 /* digit */
Definition at line 27 of file accpp.c.
_HD
#define _HD 8 /* hex digit */
Definition at line 29 of file accpp.c.
_WS
#define _WS 16 /* white space (' ' or '\t') */
Definition at line 30 of file accpp.c.
ACC_DBG
#define ACC_DBG
Value:
  fprintf(stderr, "%d: toktyp=%c(%d);  tokval=%s; line=%d\n", __LINE__, \
          toktyp, toktyp, tokval, cur_line);
Definition at line 18 of file accpp.c.
And
#define And 19
Definition at line 3301 of file accpp.c.
Andand
#define Andand 22
Definition at line 3304 of file accpp.c.
ARGMAX
#define ARGMAX 16384
Definition at line 200 of file accpp.c.
ARGST
#define ARGST 0xFE
Definition at line 207 of file accpp.c.
CHECK
#define CHECK (t)
Value:
  {                      \
    if (token != t)      \
      goto syntax_error; \
    token = gettoken();  \
  }
Definition at line 3360 of file accpp.c.
chkdef
#define chkdef (name, val)
Value:
  do {                           \
    sp = lookup(name, 1);        \
    sp->flags |= F_PREDEF;       \
    sp->nformals = 0;            \
    if (sp->value != 0)          \
      pperror(245, name, 1);     \
    else {                       \
      sp->value = strstore(val); \
      if (XBIT(122, 0x40000))    \
        putmac(sp);              \
    }                            \
  } while(0)
Colon
#define Colon 25
Definition at line 3307 of file accpp.c.
Comma
#define Comma 26
Definition at line 3308 of file accpp.c.
Compl
#define Compl 29 /* ~ */
Definition at line 3311 of file accpp.c.
CONCAT
#define CONCAT 0xF9
Definition at line 212 of file accpp.c.
CONCAT1
#define CONCAT1 0xF7
Definition at line 214 of file accpp.c.
D_DEFINE
#define D_DEFINE 8
Definition at line 241 of file accpp.c.
D_ELIF
#define D_ELIF 2
Definition at line 235 of file accpp.c.
D_ELSE
#define D_ELSE 3
Definition at line 236 of file accpp.c.
D_ENDIF
#define D_ENDIF 4
Definition at line 237 of file accpp.c.
D_ERROR
#define D_ERROR 12
Definition at line 245 of file accpp.c.
D_IDENT
#define D_IDENT 16
Definition at line 250 of file accpp.c.
D_IF
#define D_IF 1
Definition at line 234 of file accpp.c.
D_IFDEF
#define D_IFDEF 5
Definition at line 238 of file accpp.c.
D_IFNDEF
#define D_IFNDEF 6
Definition at line 239 of file accpp.c.
D_INCLUDE
#define D_INCLUDE 7
Definition at line 240 of file accpp.c.
D_INCLUDE_NEXT
#define D_INCLUDE_NEXT 17
Definition at line 251 of file accpp.c.
D_LINE
#define D_LINE 10
Definition at line 243 of file accpp.c.
D_LIST
#define D_LIST 14
Definition at line 248 of file accpp.c.
D_MODULE
#define D_MODULE 13
Definition at line 247 of file accpp.c.
D_NOLIST
#define D_NOLIST 15
Definition at line 249 of file accpp.c.
D_PRAGMA
#define D_PRAGMA 11
Definition at line 244 of file accpp.c.
D_UNDEF
#define D_UNDEF 9
Definition at line 242 of file accpp.c.
D_WARNING
#define D_WARNING 18
Definition at line 252 of file accpp.c.
Defined
#define Defined 5
Definition at line 3287 of file accpp.c.
Divide
#define Divide 7
Definition at line 3289 of file accpp.c.
ENDTOKEN
#define ENDTOKEN 0xF8
Definition at line 213 of file accpp.c.
Eoln
#define Eoln 4
Definition at line 3286 of file accpp.c.
Eq
#define Eq 17
Definition at line 3299 of file accpp.c.
ERR_OFFSET
#define ERR_OFFSET 700
Definition at line 176 of file accpp.c.
F_CHAR
#define F_CHAR 4
Definition at line 288 of file accpp.c.
F_FUNCLIKE
#define F_FUNCLIKE 2
Definition at line 287 of file accpp.c.
F_PREDEF
#define F_PREDEF 1
Definition at line 286 of file accpp.c.
F_VA_ARGS
#define F_VA_ARGS 8
Definition at line 289 of file accpp.c.
F_VA_REST
#define F_VA_REST 16
Definition at line 290 of file accpp.c.
FIXUL
#define FIXUL (a)
Definition at line 446 of file accpp.c.
FORMALMAX
#define FORMALMAX 127 /* FS#14308 - set max formals to 127 */
Definition at line 199 of file accpp.c.
Ge
#define Ge 16
Definition at line 3298 of file accpp.c.
GROW_ARGBUF
#define GROW_ARGBUF (argbuf, argp, fstart, argbufsize, newsize)
Value:
  {                                                            \
    int poffset = argp - argbuf;                               \
    int foffset = fstart - argbuf;                             \
    NEED(argbufsize + 1, argbuf, char, argbufsize, newsize);   \
    argp = argbuf + poffset;                                   \
    fstart = argbuf + foffset;                                 \
  }
Definition at line 596 of file accpp.c.
GROW_MACBUF
#define GROW_MACBUF (amt, p)
Value:
  if (1) {                                         \
    int _n, _i, _offs;                             \
    _n = amt;                                      \
    if (_n < MACMAX)                               \
      _n = MACMAX;                                 \
    _offs = p - macbuf;                            \
    _i = _offs + amt;                              \
    NEED(_i, macbuf, char, macsize, macsize + _n); \
    p = macbuf + _offs;                            \
  } else
Gt
#define Gt 14
Definition at line 3296 of file accpp.c.
HASHSIZ
#define HASHSIZ 1031
Definition at line 195 of file accpp.c.
IFMAX
#define IFMAX 20
Definition at line 197 of file accpp.c.
ifstack
#define ifstack (name) _ifs[iftop].name
Definition at line 550 of file accpp.c.
inchar
#define inchar () (lineptr < lineend ? *lineptr++ : _nextline())
Definition at line 4106 of file accpp.c.
INCLPATH
#define INCLPATH (i) (idir.b + idir.path[i])
Definition at line 591 of file accpp.c.
isblank
#define isblank (c) (ctable[MASK(c)] & _BL)
Definition at line 37 of file accpp.c.
iscsym
#define iscsym (c) (ctable[MASK(c)] & _CS)
Definition at line 34 of file accpp.c.
isdig
#define isdig (c) (ctable[MASK(c)] & _DI)
Definition at line 40 of file accpp.c.
ishex
#define ishex (c) (ctable[MASK(c)] & (_HD | _DI))
Definition at line 38 of file accpp.c.
isident
#define isident (c) (ctable[MASK(c)] & (_CS | _DI))
Definition at line 39 of file accpp.c.
iswhite
#define iswhite (c) (ctable[MASK(c)] & _WS)
Definition at line 35 of file accpp.c.
Le
#define Le 15
Definition at line 3297 of file accpp.c.
LINELEN
#define LINELEN 12000
Definition at line 194 of file accpp.c.
Lparen
#define Lparen 2
Definition at line 3284 of file accpp.c.
Lshift
#define Lshift 11
Definition at line 3293 of file accpp.c.
Lt
#define Lt 13
Definition at line 3295 of file accpp.c.
MACMAX
#define MACMAX 6000
Definition at line 198 of file accpp.c.
MACSTK_MAX
#define MACSTK_MAX 100
Definition at line 204 of file accpp.c.
MASK
#define MASK (c) ((int)c & 0xFF)
Definition at line 32 of file accpp.c.
MAX_PATHNAME_LEN
#define MAX_PATHNAME_LEN 1024
Definition at line 202 of file accpp.c.
MAXINC
#define MAXINC 20
Definition at line 203 of file accpp.c.
Minus
#define Minus 10
Definition at line 3292 of file accpp.c.
Minusx
#define Minusx 27 /* unary minus operation */
Definition at line 3309 of file accpp.c.
MKXUL
#define MKXUL (a)
Definition at line 447 of file accpp.c.
Mod
#define Mod 8
Definition at line 3290 of file accpp.c.
Mult
#define Mult 6
Definition at line 3288 of file accpp.c.
Ne
#define Ne 18
Definition at line 3300 of file accpp.c.
NOFUNC
#define NOFUNC 0xFB
Definition at line 210 of file accpp.c.
NOSUBST
#define NOSUBST 0xFC
Definition at line 209 of file accpp.c.
Not
#define Not 28
Definition at line 3310 of file accpp.c.
NPRED
#define NPRED 20
Definition at line 4931 of file accpp.c.
Number
#define Number 1
Definition at line 3283 of file accpp.c.
Or
#define Or 21
Definition at line 3303 of file accpp.c.
Oror
#define Oror 23
Definition at line 3305 of file accpp.c.
Plus
#define Plus 9
Definition at line 3291 of file accpp.c.
Plusx
#define Plusx 31 /* unary plus */
Definition at line 3313 of file accpp.c.
PP_MAJOR
#define PP_MAJOR "__FLANG_MAJOR__"
PP_MINOR
#define PP_MINOR "__FLANG_MINOR__"
PP_PATCHLEVEL
#define PP_PATCHLEVEL "__FLANG_PATCHLEVEL__"
pperr
#define pperr (n, sev) pperror(n, CNULL, sev)
Definition at line 192 of file accpp.c.
pperror
#define pperror (n, x, sev)
Value:
  do {                                                   \
    if (ERR_OFFSET && (n) == 23)                         \
      error(236, sev, startline, x, CNULL);              \
    else if ((n) < 200)                                  \
      error((n), sev, startline, x, CNULL);              \
    else                                                 \
      error((n) + ERR_OFFSET, sev, startline, x, CNULL); \
  } while (0)
Definition at line 182 of file accpp.c.
PPNUM_IS_32
#define PPNUM_IS_32
Definition at line 340 of file accpp.c.
PRAGMAOP
#define PRAGMAOP 0xF5
Definition at line 216 of file accpp.c.
Predicate
#define Predicate 30
Definition at line 3312 of file accpp.c.
PTOK_ADD
#define PTOK_ADD (a, b) add64(PTOK_V(a), PTOK_V(b), PTOK_V(a)) MKXUL(a)
Definition at line 468 of file accpp.c.
PTOK_AND
#define PTOK_AND (a, b) and64(PTOK_V(a), PTOK_V(b), PTOK_V(a)) MKXUL(a)
Definition at line 472 of file accpp.c.
PTOK_ANDAND
#define PTOK_ANDAND (a, b) PTOK_ASSN32(a, cmp64(PTOK_V(a), zero64) && cmp64(PTOK_V(b), zero64))
Definition at line 477 of file accpp.c.
PTOK_ASSN
#define PTOK_ASSN (a, b) (void)(PTOK_V(a)[0] = PTOK_V(b)[0], PTOK_V(a)[1] = PTOK_V(b)[1])
Definition at line 503 of file accpp.c.
PTOK_ASSN32
#define PTOK_ASSN32 (a, i) (void)(PTOK_V(a)[1] = (i), PTOK_V(a)[0] = 0)
Definition at line 513 of file accpp.c.
PTOK_BNOT
#define PTOK_BNOT (a, b) not64(PTOK_V(b), PTOK_V(a)) MKXUL(a)
Definition at line 475 of file accpp.c.
PTOK_BTEST32
#define PTOK_BTEST32 (a, i) (PTOK_V(a)[1] & (i))
Definition at line 516 of file accpp.c.
PTOK_CMP
#define PTOK_CMP (a, b) cmp64(PTOK_V(a), PTOK_V(b))
Definition at line 487 of file accpp.c.
PTOK_CRSHIFT
#define PTOK_CRSHIFT (a, b) shf64(PTOK_V(a), -PTOK_V(b)[1], PTOK_V(a)) MKXUL(a)
Definition at line 485 of file accpp.c.
PTOK_DIV
#define PTOK_DIV (a, b) div64(PTOK_V(a), PTOK_V(b), PTOK_V(a))
Definition at line 454 of file accpp.c.
PTOK_ISNEG
#define PTOK_ISNEG (a) (cmp64(PTOK_V(a), zero64) < 0)
Definition at line 501 of file accpp.c.
PTOK_ISNZ
#define PTOK_ISNZ (a) (cmp64(PTOK_V(a), zero64) != 0)
Definition at line 502 of file accpp.c.
PTOK_ISUNS
#define PTOK_ISUNS (t) (t).isuns
Definition at line 369 of file accpp.c.
PTOK_LNOT
#define PTOK_LNOT (a, b) PTOK_ASSN32(a, cmp64(PTOK_V(b), zero64) == 0)
Definition at line 476 of file accpp.c.
PTOK_LOGEQ
#define PTOK_LOGEQ (a, b) PTOK_ASSN32(a, PTOK_CMP(a, b) == 0)
Definition at line 488 of file accpp.c.
PTOK_LOGGE
#define PTOK_LOGGE (a, b) PTOK_ASSN32(a, PTOK_CMP(a, b) >= 0)
Definition at line 493 of file accpp.c.
PTOK_LOGGT
#define PTOK_LOGGT (a, b) PTOK_ASSN32(a, PTOK_CMP(a, b) > 0)
Definition at line 492 of file accpp.c.
PTOK_LOGLE
#define PTOK_LOGLE (a, b) PTOK_ASSN32(a, PTOK_CMP(a, b) <= 0)
Definition at line 491 of file accpp.c.
PTOK_LOGLT
#define PTOK_LOGLT (a, b) PTOK_ASSN32(a, PTOK_CMP(a, b) < 0)
Definition at line 490 of file accpp.c.
PTOK_LOGNE
#define PTOK_LOGNE (a, b) PTOK_ASSN32(a, PTOK_CMP(a, b) != 0)
Definition at line 489 of file accpp.c.
PTOK_LOGUGE
#define PTOK_LOGUGE (a, b) PTOK_ASSN32(a, PTOK_UCMP(a, b) >= 0)
Definition at line 499 of file accpp.c.
PTOK_LOGUGT
#define PTOK_LOGUGT (a, b) PTOK_ASSN32(a, PTOK_UCMP(a, b) > 0)
Definition at line 498 of file accpp.c.
PTOK_LOGULE
#define PTOK_LOGULE (a, b) PTOK_ASSN32(a, PTOK_UCMP(a, b) <= 0)
Definition at line 497 of file accpp.c.
PTOK_LOGULT
#define PTOK_LOGULT (a, b) PTOK_ASSN32(a, PTOK_UCMP(a, b) < 0)
Definition at line 496 of file accpp.c.
PTOK_LSHIFT
#define PTOK_LSHIFT (a, b) shf64(PTOK_V(a), PTOK_V(b)[1], PTOK_V(a)) MKXUL(a)
Definition at line 482 of file accpp.c.
PTOK_LSHIFT32
#define PTOK_LSHIFT32 (a, i) PTOK_V(a)[1] <<= (i)
Definition at line 514 of file accpp.c.
PTOK_MOD
#define PTOK_MOD (a, b) mod64(PTOK_V(a), PTOK_V(b), PTOK_V(a))
Definition at line 464 of file accpp.c.
PTOK_MUL
#define PTOK_MUL (a, b) mul64(PTOK_V(a), PTOK_V(b), PTOK_V(a)) MKXUL(a)
Definition at line 453 of file accpp.c.
PTOK_NEG
#define PTOK_NEG (a, b) neg64(PTOK_V(b), PTOK_V(a)) MKXUL(a)
Definition at line 470 of file accpp.c.
PTOK_OR
#define PTOK_OR (a, b) or64(PTOK_V(a), PTOK_V(b), PTOK_V(a)) MKXUL(a)
Definition at line 473 of file accpp.c.
PTOK_OR32
#define PTOK_OR32 (a, i) PTOK_V(a)[1] |= (i)
Definition at line 515 of file accpp.c.
PTOK_OROR
#define PTOK_OROR (a, b) PTOK_ASSN32(a, cmp64(PTOK_V(a), zero64) || cmp64(PTOK_V(b), zero64))
Definition at line 479 of file accpp.c.
PTOK_SEXTEND32
#define PTOK_SEXTEND32 (a)
Value:
  {                                \
    if (PTOK_V(a)[1] & 0x80000000) \
      PTOK_V(a)[0] = 0xffffffff;   \
    else                           \
      PTOK_V(a)[0] = 0;            \
  }
Definition at line 517 of file accpp.c.
PTOK_SUB
#define PTOK_SUB (a, b) sub64(PTOK_V(a), PTOK_V(b), PTOK_V(a)) MKXUL(a)
Definition at line 469 of file accpp.c.
PTOK_UCMP
#define PTOK_UCMP (a, b) ucmp64(PTOK_VUNS(a), PTOK_VUNS(b))
Definition at line 495 of file accpp.c.
PTOK_UDIV
#define PTOK_UDIV (a, b)
Value:
  {                                         \
    DBLUINT64 ui;                              \
    udiv64(PTOK_VUNS(a), PTOK_VUNS(b), ui); \
    PTOK_V(a)[0] = ui[0];                   \
    PTOK_V(a)[1] = ui[1];                   \
    FIXUL(a);                               \
  }
Definition at line 455 of file accpp.c.
PTOK_UMOD
#define PTOK_UMOD (a, b) umod64(PTOK_VUNS(a), PTOK_VUNS(b), PTOK_VUNS(a)) MKXUL(a)
Definition at line 465 of file accpp.c.
PTOK_URSHIFT
#define PTOK_URSHIFT (a, b) ushf64(PTOK_VUNS(a), -PTOK_V(b)[1], PTOK_VUNS(a)) MKXUL(a)
Definition at line 483 of file accpp.c.
PTOK_V
#define PTOK_V (t) (t).val
Definition at line 367 of file accpp.c.
PTOK_VUNS
#define PTOK_VUNS (a) (UINT *) PTOK_V(a)
Definition at line 368 of file accpp.c.
PTOK_XOR
#define PTOK_XOR (a, b) xor64(PTOK_V(a), PTOK_V(b), PTOK_V(a)) MKXUL(a)
Definition at line 474 of file accpp.c.
Question
#define Question 24
Definition at line 3306 of file accpp.c.
Rparen
#define Rparen 3
Definition at line 3285 of file accpp.c.
Rshift
#define Rshift 12
Definition at line 3294 of file accpp.c.
SENTINEL
#define SENTINEL 0xFD
Definition at line 208 of file accpp.c.
STRINGIZE
#define STRINGIZE 0xFA
Definition at line 211 of file accpp.c.
T_CHAR
#define T_CHAR 'c'
Definition at line 228 of file accpp.c.
T_CONCAT
#define T_CONCAT (-5)
Definition at line 231 of file accpp.c.
T_IDENT
#define T_IDENT 'a'
Definition at line 221 of file accpp.c.
T_NOFIDENT
#define T_NOFIDENT 'f'
Definition at line 223 of file accpp.c.
T_NSIDENT
#define T_NSIDENT 'b'
Definition at line 222 of file accpp.c.
T_OP
#define T_OP 'o'
Definition at line 230 of file accpp.c.
T_POUND
#define T_POUND (-2)
Definition at line 225 of file accpp.c.
T_PPNUM
#define T_PPNUM 'p'
Definition at line 224 of file accpp.c.
T_SENTINEL
#define T_SENTINEL (-3)
Definition at line 232 of file accpp.c.
T_STRING
#define T_STRING 's'
Definition at line 226 of file accpp.c.
T_WCHAR
#define T_WCHAR 'z'
Definition at line 229 of file accpp.c.
T_WSTRING
#define T_WSTRING 'w'
Definition at line 227 of file accpp.c.
TARGMAX
#define TARGMAX 32768
Definition at line 201 of file accpp.c.
TOKMAX
#define TOKMAX 8192
Definition at line 196 of file accpp.c.
UCONV
#define UCONV
Value:
  if (PTOK_ISUNS(left) || PTOK_ISUNS(right)) \
    PTOK_ISUNS(left) = 1;                    \
  else                                       \
  PTOK_ISUNS(left) = 0
Definition at line 3389 of file accpp.c.
VA_ARGS
#define VA_ARGS 0xF4
Definition at line 217 of file accpp.c.
VA_REST
#define VA_REST 0xF3
Definition at line 218 of file accpp.c.
WHITESPACE
#define WHITESPACE 0xF6
Definition at line 215 of file accpp.c.
Xor
#define Xor 20
Definition at line 3302 of file accpp.c.
Typedef Documentation
INCLENTRY
typedef char INCLENTRY[MAX_PATHNAME_LEN]
Definition at line 536 of file accpp.c.
Function Documentation
_doincl()
static void _doincl (char * name, int type, LOGICAL include_next) static
Parameters
type
-0  --  "file_name"
-1  --  <file_name>
Definition at line 2104 of file accpp.c.
References add_to_incllist(), CNULL, INCLSTACK::count, count, dirnam(), dirname, dirwork, error(), FALSE, fname, INCLSTACK::fname, fndpath(), INCLSTACK::from_stdinc, gbl, i, idir, ifp, inclev, INCLPATH, inclstack, incsize, INCLSTACK::lineno, MAX_PATHNAME_LEN, MAXINC, name, NEED, NULL, INCLSTACK::path_idx, pperror, pr_line(), prevfile, prevline, startline, strlen(), type, and XBIT.
Referenced by doincl().
_nextline()
static int _nextline (void) static
Definition at line 4721 of file accpp.c.
References c, INCLSTACK::count, cur_fname, cur_from_stdinc, fclose(), FILE, flg, fn, fname, INCLSTACK::fname, fp, INCLSTACK::from_stdinc, gbl, i, idir, ifp, INCLSTACK::ifp, inclev, inclstack, FLG::include, j, linebuf, lineend, linelen, INCLSTACK::lineno, lineno, lineptr, linesize, list_flag, list_line(), p, INCLSTACK::path_idx, pr_line(), realloc_linebuf(), start, and startline.
Referenced by nextok().
acc_display_macros()
static void acc_display_macros () static
Definition at line 700 of file accpp.c.
References deftab, gbl, hashrec, i, PPSYM::name, name, next_hash, PPSYM::value, and value().
Referenced by accpp().
accpp()
void accpp (void)
Definition at line 715 of file accpp.c.
References _ifs, acc_display_macros(), atoxi(), c, chkdef, clreol(), INCLSTACK::count, count, cp, cpp_comments, ctable, cur_fname, cur_from_stdinc, cur_line, D_DEFINE, D_ELIF, D_ELSE, D_ENDIF, D_ERROR, D_IDENT, D_IF, D_IFDEF, D_IFNDEF, D_INCLUDE, D_INCLUDE_NEXT, D_LINE, D_LIST, D_MODULE, D_NOLIST, D_PRAGMA, D_UNDEF, D_WARNING, FLG::def, deftab, dirnam(), dirname, DIRSINCS, dlookup(), dodef(), doerror(), doident(), doincl(), doline(), domodule(), doparse(), dopragma(), doundef(), dowarning(), errfatal(), FLG::es, F_PREDEF, FALSE, fileloc, findtok(), finish(), PPSYM::flags, flg, fname, FREE, INCLSTACK::from_stdinc, gbl, getenv(), gtok(), hashrec, i, idir, FLG::idir, IFMAX, ifp, INCLSTACK::ifp, ifpush(), ifsize, ifstack, iftop, in_ftn_comment, incfiles, incllist, inclstack, incsize, isdig, iswhite, linebuf, lineend, LINELEN, linelen, lineloc, INCLSTACK::lineno, lineptr, linesize, FLG::list, list_flag, FLG::list_macros, lookup(), macro_recur_check(), MAXINC, NEW, PPSYM::nformals, nifile, NULL, p, FLG::p, INCLSTACK::path_idx, pbchar(), pbstr(), pflag, PP_MAJOR, PP_MINOR, PP_PATCHLEVEL, pperr, pperror, pr_line(), ptok(), skipbl(), FLG::smp, startline, stash_paths(), FLG::stdinc, strlen(), subst(), T_IDENT, T_NSIDENT, T_PPNUM, T_SENTINEL, tmpfile(), TOKMAX, toktyp, tokval, TRUE, FLG::undef, version, void(), and XBIT.
Referenced by fpp().
add_to_incllist()
static void add_to_incllist (char * fullname) static
Add fullname to the list of include files in incllist.
This list is used to generate build system dependencies with the -M, -MM, -MD, and -MMD options.
The fullname buffer will be modified by this function.
The file should be added to inclstack with a correct sys bit before calling this function. The inclstack is inspected to implement -MM and -MMD correctly.
Definition at line 2059 of file accpp.c.
References i, incfiles, inclev, incllist, inclsize, inclstack, NEED, NEW, and XBIT.
Referenced by _doincl().
clreol()
static void clreol (int erf) static
Parameters
erf
*- 0: do NOT print msg 251;
   -1/1: print msg 251(extraneous tokens ignored)
Definition at line 1432 of file accpp.c.
References col, erf(), FALSE, first, flg, FLG::freeform, gtok(), in_ftn_comment, iswhite, linebuf, LINELEN, lineptr, pperr, ptok(), TOKMAX, toktyp, tokval, and XBIT.
Referenced by accpp(), dodef(), doident(), doincl(), doline(), domodule(), doparse(), and doundef().
delete()
static void delete (const char * name) static
Definition at line 3169 of file accpp.c.
References cp, deftab, F_PREDEF, flags, hashrec, HASHSIZ, hashtab, i, INT, j, m, MAXIDLEN, name, PPSYM::next, p, pperror, and q.
dlookup()
static int dlookup (char * name) static
Definition at line 1466 of file accpp.c.
References D_DEFINE, D_ELIF, D_ELSE, D_ENDIF, D_ERROR, D_IDENT, D_IF, D_IFDEF, D_IFNDEF, D_INCLUDE, D_INCLUDE_NEXT, D_LINE, D_LIST, D_MODULE, D_NOLIST, D_PRAGMA, D_UNDEF, D_WARNING, i, name, and val.
Referenced by accpp().
dodef()
static void dodef (int cmdline) static
Default behavior: Add whitespace at the beginning and end of the macro body, and between tokens in the macro body.
Behavior Modified by:
-Mx,123,x20: Do NOT add whitespace at the beginning, between and end of the macro body.
-Mx,123,x200: Add whitespace at beginning, end and between tokens in the macro body. Do NOT add whitespace between tokens when OUTSIDE of a macro body.
-Mx,123,x800: Do NOT collapse consecutive whitespace ('cpp' mode).
Definition at line 1546 of file accpp.c.
References argbuf, ARGST, clreol(), CNULL, CONCAT, CONCAT1, DBGBIT, deftab, delim, dumpmac(), ENDTOKEN, error(), F_CHAR, F_FUNCLIKE, F_VA_ARGS, F_VA_REST, FALSE, PPSYM::flags, FORMALMAX, PPSYM::formals, FREE, GROW_MACBUF, gtok(), i, in_dodef, inlist(), iswhite, lookup(), MACMAX, MASK, n, PPSYM::name, NEW, PPSYM::nformals, p, pperr, pperror, putmac(), q, r, s, skipbl(), startline, STRINGIZE, strlen(), strstore(), T_CHAR, T_CONCAT, T_IDENT, T_OP, T_STRING, TOKMAX, toktyp, tokval, TRUE, VA_ARGS, VA_REST, PPSYM::value, WHITESPACE, and XBIT.
Referenced by accpp().
doerror()
static void doerror (void) static
Definition at line 1396 of file accpp.c.
References gtok(), pperror, TOKMAX, toktyp, and tokval.
Referenced by accpp().
doident()
static void doident (void) static
Definition at line 1377 of file accpp.c.
References clreol(), pperr, skipbl(), strlen(), T_STRING, TOKMAX, toktyp, and tokval.
Referenced by accpp().
doincl()
static void doincl (LOGICAL include_next) static
Definition at line 1949 of file accpp.c.
References _doincl(), buff, clreol(), delim, gtok(), MAX_PATHNAME_LEN, NULL, p, pperr, skipbl(), T_STRING, TOKMAX, toktyp, tokval, and type.
Referenced by accpp().
doline()
static void doline (int inflg, char * tokv) static
Definition at line 1290 of file accpp.c.
References clreol(), filename, fname, gbl, inclev, inclstack, line, INCLSTACK::lineno, pperr, skipbl(), strlen(), T_IDENT, T_PPNUM, T_STRING, tobinary(), TOKMAX, toktyp, tokval, and XBIT.
Referenced by accpp().
domodule()
static void domodule (void) static
Definition at line 2256 of file accpp.c.
References clreol(), cp, gbl, i, MAXIDLEN, NEW, pperr, skipbl(), T_IDENT, TOKMAX, toktyp, and tokval.
Referenced by accpp().
doparse()
static INT doparse (void) static
Definition at line 3368 of file accpp.c.
References clreol(), Eoln, gettoken(), i, parse(), pperr, ptok(), PTOK_ISNZ, syntaxerr, tmp, and token.
Referenced by accpp().
dopragma()
static int dopragma (void) static
Definition at line 1338 of file accpp.c.
References gtok(), iswhite, ptok(), T_IDENT, TOKMAX, toktyp, tokval, and XBIT.
Referenced by accpp().
doundef()
static void doundef (int cmdline) static
Definition at line 2282 of file accpp.c.
References clreol(), pperr, putunmac(), skipbl(), T_IDENT, TOKMAX, toktyp, tokval, and XBIT.
Referenced by accpp().
dowarning()
static void dowarning (void) static
Definition at line 1411 of file accpp.c.
References gtok(), pperror, TOKMAX, toktyp, and tokval.
Referenced by accpp().
dumpmac()
static void dumpmac (PPSYM * sp) static
Definition at line 2975 of file accpp.c.
References deftab, dumpval(), PPSYM::flags, PPSYM::name, PPSYM::next, PPSYM::nformals, and PPSYM::value.
Referenced by dodef().
dumpval()
static void dumpval (char * p, FILE * ff) static
Definition at line 2921 of file accpp.c.
References ARGST, CONCAT, CONCAT1, ENDTOKEN, f, FILE, MASK, NOFUNC, NOSUBST, p, PRAGMAOP, SENTINEL, STRINGIZE, VA_ARGS, VA_REST, and WHITESPACE.
Referenced by dumpmac().
findtok()
static int findtok (char * tokval, int truth) static
Definition at line 4052 of file accpp.c.
References FALSE, i, in_ftn_comment, isblank, lookup(), macro_recur_check(), nextok(), ptok(), subst(), T_IDENT, T_NOFIDENT, T_NSIDENT, T_POUND, T_SENTINEL, toktyp, and tokval.
Referenced by accpp().
gettoken()
static int gettoken (void) static
Definition at line 3595 of file accpp.c.
References And, Andand, c, Colon, Comma, Compl, Defined, Divide, Eoln, Eq, Ge, Gt, i, ishex, Le, lookup(), Lparen, Lshift, Lt, Minus, Mod, Mult, Ne, Not, Number, Or, Oror, Plus, pperr, predarg(), Predicate, predicate(), PTOK_ASSN32, PTOK_BTEST32, PTOK_ISUNS, PTOK_LSHIFT32, PTOK_OR32, PTOK_SEXTEND32, PTOK_V, Question, Rparen, Rshift, s, skipbl(), t, T_CHAR, T_IDENT, T_OP, T_PPNUM, T_STRING, T_WCHAR, T_WSTRING, tobinary(), tobinary64(), tokenval, TOKMAX, toktyp, tokval, PPSYM::value, and Xor.
Referenced by doparse(), and parse().
gtok()
static int gtok (char * tokval, int expflag) static
Definition at line 4018 of file accpp.c.
References FLG::es, FALSE, flg, i, lookup(), macro_recur_check(), nextok(), subst(), T_IDENT, T_NOFIDENT, T_NSIDENT, T_SENTINEL, toktyp, tokval, TRUE, and XBIT.
Referenced by accpp(), clreol(), dodef(), doerror(), doincl(), dopragma(), dowarning(), skipbl(), and subst().
ifpush()
static void ifpush (void) static
Definition at line 2885 of file accpp.c.
References _ifs, IFMAX, ifsize, ifstack, iftop, NEED, and IFREC::truth.
Referenced by accpp().
inlist()
static int inlist (int * list, int nl, char * value, char * macbuf) static
Definition at line 1517 of file accpp.c.
References i, list, and value().
Referenced by dodef().
lookup()
static PPSYM * lookup (const char * name, int insflg) static
Definition at line 3095 of file accpp.c.
References buff, cp, deftab, F_PREDEF, flags, PPSYM::flags, hashrec, HASHSIZ, hashtab, i, INT, m, MASK, MAXIDLEN, PPSYM::name, name, NEED, NEW, PPSYM::next, next_hash, PPSYM::nformals, nhash, NULL, p, pperror, q, strstore(), and PPSYM::value.
Referenced by accpp(), dodef(), findtok(), gettoken(), and gtok().
mac_push()
static int mac_push (PPSYM * sp, char * lptr) static
Definition at line 4893 of file accpp.c.
References hashrec, interr(), macstk, MACSTK_MAX, macstk_top, macstk_type::msptr, macstk_type::sav_lptr, and startline.
Referenced by subst().
macro_recur_check()
static int macro_recur_check (PPSYM * sp) static
Definition at line 4915 of file accpp.c.
References hashrec, i, macstk, and macstk_top.
Referenced by accpp(), findtok(), and gtok().
mod64()
static void mod64 (DBLINT64 x, DBLINT64 y, DBLINT64 res) static
Definition at line 5037 of file accpp.c.
References div64(), mul64(), res, sub64(), x, and y.
nextok()
static int nextok (char * tokval, int truth) static
Definition at line 4109 of file accpp.c.
References _nextline(), asm_mode, c, cpp_comments, delim, ENDTOKEN, FLG::es, FALSE, FLANG_FALLTHROUGH, flg, FLG::freeform, i, ifstack, in_dodef, in_ftn_comment, inchar, isdig, isident, linebuf, lineend, LINELEN, lineptr, MASK, NOFUNC, NOSUBST, p, popstack(), pperr, ptok(), SENTINEL, T_CONCAT, T_IDENT, T_NOFIDENT, T_NSIDENT, T_OP, T_PPNUM, T_SENTINEL, T_STRING, T_WCHAR, T_WSTRING, tmp, TOKMAX, toktyp, tokval, TRUE, WHITESPACE, and XBIT.
Referenced by findtok(), and gtok().
parse()
static void parse (int rbp, PTOK * tk) static
parse "current" expression and return value computed by constant folding it.
Definition at line 3400 of file accpp.c.
References And, Andand, CHECK, Colon, Comma, Compl, Defined, Divide, Eoln, Eq, FALSE, Ge, gettoken(), Gt, lbp, Le, led, Lparen, Lshift, Lt, Minus, Minusx, Mod, Mult, Ne, Not, Number, Or, Oror, parse(), Plus, Plusx, pperr, Predicate, PT, PTOK_ADD, PTOK_AND, PTOK_ANDAND, PTOK_ASSN, PTOK_ASSN32, PTOK_BNOT, PTOK_CRSHIFT, PTOK_DIV, PTOK_ISNEG, PTOK_ISNZ, PTOK_ISUNS, PTOK_LNOT, PTOK_LOGEQ, PTOK_LOGGE, PTOK_LOGGT, PTOK_LOGLE, PTOK_LOGLT, PTOK_LOGNE, PTOK_LOGUGE, PTOK_LOGUGT, PTOK_LOGULE, PTOK_LOGULT, PTOK_LSHIFT, PTOK_MOD, PTOK_MUL, PTOK_NEG, PTOK_OR, PTOK_OROR, PTOK_SUB, PTOK_UDIV, PTOK_UMOD, PTOK_URSHIFT, PTOK_XOR, Question, rbp, Rparen, Rshift, syntaxerr, t, T_IDENT, tmp, token, tokenval, toktyp, TRUE, UCONV, and Xor.
Referenced by doparse(), and parse().
pbchar()
static void pbchar (int c) static
Definition at line 4869 of file accpp.c.
References c, linebuf, lineptr, and realloc_linebuf().
Referenced by accpp(), and subst().
pbstr()
static void pbstr (const char * s) static
Definition at line 4879 of file accpp.c.
References linebuf, lineptr, p, realloc_linebuf(), s, and strlen().
Referenced by accpp(), and subst().
popstack()
static void popstack (void) static
Definition at line 4907 of file accpp.c.
References lineptr, macstk, and macstk_top.
Referenced by nextok().
pr_line()
static void pr_line (const char * name, int line, LOGICAL from_stdinc) static
Format of pr_line output: # line "file_full_path" "from_stdinc".
NB: -"form_stdinc" field is omitted in Fortran -If you modify "System_Header", make sure you modify get_line() in scan.c (both the string and its length)
Definition at line 1270 of file accpp.c.
References INCLSTACK::fname, gbl, inclev, inclstack, line, INCLSTACK::lineno, name, pflag, and XBIT.
Referenced by _doincl(), _nextline(), accpp(), and ptok().
predarg()
static int predarg (char * tokval) static
Definition at line 4984 of file accpp.c.
References j, p, pred, predtab, strlen(), tokval, and val.
Referenced by gettoken().
predicate()
static void predicate (char * tokval) static
Definition at line 4970 of file accpp.c.
References i, j, pred, prednum, predtab, strlen(), and tokval.
Referenced by emit_scatterx_gatherx(), gettoken(), no_data_components_recursive(), search_type_members(), search_type_members_wrapped(), test_sym_and_components(), and test_sym_components_only().
print_and_check()
void print_and_check (FILE * ff, char * str, char end_c)
Replaces fprintf (ff, format, str) ,.
checks for spaces in the string,
and windows ':'
and adds backspaces so that the output can be included in makefiles
Definition at line 677 of file accpp.c.
References cp, and str.
ptok()
static void ptok (const char * tok) static
Definition at line 3215 of file accpp.c.
References cur_fname, cur_from_stdinc, cur_line, FILE, fname, fp, FREE, INCLSTACK::from_stdinc, gbl, inclev, inclstack, iswhite, MASK, pr_line(), startline, tok, void(), WHITESPACE, and XBIT.
Referenced by accpp(), clreol(), doparse(), dopragma(), findtok(), nextok(), and subst().
putmac()
static void putmac (PPSYM * sp) static
Definition at line 2998 of file accpp.c.
References ARGST, CONCAT, CONCAT1, deftab, ENDTOKEN, f, FILE, PPSYM::formals, gbl, i, MASK, PPSYM::name, PPSYM::nformals, NOFUNC, NOSUBST, p, PRAGMAOP, prevfile, prevline, SENTINEL, startline, STRINGIZE, VA_ARGS, VA_REST, PPSYM::value, WHITESPACE, and XBIT.
Referenced by dodef().
putunmac()
static void putunmac (char * mac) static
output undefine macro
Definition at line 3073 of file accpp.c.
References f, FILE, gbl, prevfile, prevline, and startline.
Referenced by doundef().
realloc_linebuf()
static ptrdiff_t realloc_linebuf (ptrdiff_t extra) static
Definition at line 4831 of file accpp.c.
References FREE, i, linebuf, lineend, LINELEN, linelen, lineptr, linesize, macstk, macstk_top, NEW, and savlptr.
Referenced by _nextline(), pbchar(), and pbstr().
setasmmode()
void setasmmode (void)
Definition at line 5057 of file accpp.c.
References _CS, asm_mode, ctable, and TRUE.
setsuffix()
void setsuffix (char * newsuffix)
Definition at line 5067 of file accpp.c.
References suffix.
skipbl()
static int skipbl (char * tokval, int flag) static
Definition at line 659 of file accpp.c.
References gtok(), iswhite, toktyp, and tokval.
Referenced by accpp(), dodef(), doident(), doincl(), doline(), domodule(), doundef(), and gettoken().
stash_paths()
static void stash_paths (const char * dirs) static
Definition at line 5005 of file accpp.c.
References DIRSEP, idir, n, NEED, NULL, path, and TRUE.
Referenced by accpp().
strstore()
static INT strstore (const char * name) static
Definition at line 2897 of file accpp.c.
References deftab, i, j, name, ndef, NEED, NEW, next_def, and strlen().
Referenced by dodef(), and lookup().
subst()
static int subst (PPSYM * sp) static
Definition at line 2301 of file accpp.c.
References argbuf, ARGMAX, ARGST, CONCAT, CONCAT1, cur_line, deftab, ENDTOKEN, F_CHAR, F_FUNCLIKE, F_VA_ARGS, F_VA_REST, fileloc, PPSYM::flags, FLANG_FALLTHROUGH, fname, FORMALMAX, FREE, GROW_ARGBUF, gtok(), hashrec, i, inclev, inclstack, interr(), isblank, iswhite, len, linebuf, LINELEN, lineloc, lineno, lineptr, mac_push(), MASK, PPSYM::name, NEW, PPSYM::nformals, NOFUNC, NOSUBST, p, pbchar(), pbstr(), pperr, pperror, PRAGMAOP, ptok(), q, qq, r, savlptr, SENTINEL, startline, STRINGIZE, strlen(), T_NSIDENT, T_SENTINEL, T_STRING, TARGMAX, tmp, TOKMAX, toktyp, tokval, update_actuals(), VA_ARGS, VA_REST, PPSYM::value, WHITESPACE, and XBIT.
Referenced by accpp(), findtok(), and gtok().
tobinary()
static INT tobinary (char * st, int * isuns, INT * value) static
Definition at line 3822 of file accpp.c.
References atoxi(), c, cp, ishex, pperror, r, st, strlen(), and value().
Referenced by doline(), and gettoken().
tobinary64()
static INT tobinary64 (char * st, int * isuns, DBLINT64 value) static
Definition at line 3901 of file accpp.c.
References atoxi64(), c, cp, ishex, pperror, r, st, strlen(), and value().
Referenced by gettoken().
umod64()
static void umod64 (DBLUINT64 x, DBLUINT64 y, DBLUINT64 res) static
Definition at line 5047 of file accpp.c.
References res, udiv64(), umul64(), usub64(), x, and y.
update_actuals()
static void update_actuals (char ** actuals, int nactuals, char * oldargbuf, char * newargbuf) static
Definition at line 5075 of file accpp.c.
References i, and offset.
Referenced by subst().
Variable Documentation
_ifs
IFREC* _ifs static
Definition at line 295 of file accpp.c.
Referenced by accpp(), and ifpush().
asm_mode
LOGICAL asm_mode = FALSE static
Definition at line 594 of file accpp.c.
Referenced by nextok(), and setasmmode().
b
char* b
Definition at line 585 of file accpp.c.
b_avl
int b_avl
Definition at line 586 of file accpp.c.
b_sz
int b_sz
Definition at line 587 of file accpp.c.
cnt
int cnt
Definition at line 582 of file accpp.c.
Referenced by __c_mcopy1(), __c_mcopy16(), __c_mcopy2(), __c_mcopy4(), __c_mcopy8(), __c_mset1(), __c_mset16(), __c_mset2(), __c_mset4(), __c_mset8(), __c_mzero1(), __c_mzero16(), __c_mzero2(), __c_mzero4(), __c_mzero8(), __fort_bcopysl(), __fort_crecv(), __fort_csend(), __fort_global_reduce(), __fort_par_read(), __fort_par_write(), __fort_print_vector(), __fort_rbcst(), __fort_rbcstl(), __fort_recvl(), __fort_reduce_section(), __fort_replicate_result(), __fort_rrecv(), __fort_rrecvl(), __fort_rsend(), __fort_rsendl(), __fort_sendl(), __fortio_swap_bytes(), __INT_T(), _constructf90(), _fixup_llvm_uplevel_symbol(), _is_atomic_update_binop(), add_uplevel_to_host(), annomod_initx(), assumshp_args(), ast_intr(), ast_trav_recurse(), bld_ud(), broadcast(), check_subprogram(), chk_adjarr(), chk_struct_constructor(), collapse_index(), compute_invariant(), const_xtoi(), conv_forall(), copy_loop(), copy_xfer_loop(), dmp_all_anno(), do_nml(), dump_memrefs(), dump_vinduc(), e74_cnt(), ef_putvlist(), emitComplexDIExpression(), ENTFTN(), evl_kwd_args(), exp_mp_atomic_capture(), export_one_ast(), export_some_args(), export_some_procedure(), ff_get_label(), find_idx(), flowgraph(), forall_make_same_idx(), ftn_i_shift64(), Ftn_str_copy(), Ftn_str_copy_klen(), fw_slashes(), get_exttype_list(), get_keyword_args(), get_keyword_components(), get_kwd_args(), init_fold_const(), insert_forall_comm(), is_atomic_update_intr(), is_avail_expr_with_list(), is_fusable(), is_tail_aexe(), kwd_match(), lldbg_create_global_variable_mdnode(), lldbg_emit_expression_mdnode(), lower_data_stmts(), lower_intrinsic(), lower_no_subscr_chk(), make_keyword_str(), mk_argt(), mkarglist(), mkatomictemp(), new_argt(), new_asd(), new_shape(), nml_emit_desc(), olap_recv(), olap_send(), par_body(), partition_blocks(), print_ast(), print_row(), put_buf(), put_call(), put_prefix(), replace_formal_triples(), rqueue_ast(), search_pure_function(), storedums(), sum_scatter_args(), unmk_argt(), and upper_save_syminfo().
cpp_comments
LOGICAL cpp_comments static
Definition at line 593 of file accpp.c.
Referenced by accpp(), and nextok().
ctable
char ctable[256] static
Definition at line 42 of file accpp.c.
Referenced by accpp(), scan_init(), and setasmmode().
cur_fname
char cur_fname[MAX_PATHNAME_LEN] static
Definition at line 553 of file accpp.c.
Referenced by _nextline(), accpp(), and ptok().
cur_from_stdinc
LOGICAL cur_from_stdinc static
Definition at line 555 of file accpp.c.
Referenced by _nextline(), accpp(), and ptok().
cur_line
int cur_line static
Definition at line 554 of file accpp.c.
Referenced by accpp(), ptok(), and subst().
deftab
char* deftab static
Definition at line 303 of file accpp.c.
Referenced by acc_display_macros(), accpp(), delete(), dodef(), dumpmac(), lookup(), putmac(), strstore(), and subst().
dirwork
char dirwork[MAX_PATHNAME_LEN] static
Definition at line 560 of file accpp.c.
Referenced by _doincl().
fileloc
int fileloc static
Definition at line 548 of file accpp.c.
Referenced by accpp(), and subst().
filename
char filename[MAX_PATHNAME_LEN] = {'\0'} static
Definition at line 556 of file accpp.c.
Referenced by __fortio_open(), __fortio_scratch_name(), addfile(), addinlfile(), addmodfile(), doline(), formatFilename(), gentmp(), get_filename(), getline(), lldbg_create_compile_unit_mdnode(), lldbg_create_file_mdnode(), lower_add_func_call(), lower_fileinfo(), lower_fileinfo_llvm(), lowerFilename(), open_input_file(), pg_makenewdir(), pg_makenewfile(), pg_newfile(), read_fileentries(), stb_upper_init(), and upper_init().
hashrec
PPSYM* hashrec static
Definition at line 299 of file accpp.c.
Referenced by acc_display_macros(), accpp(), delete(), lookup(), mac_push(), macro_recur_check(), and subst().
hashtab
INT hashtab[HASHSIZ] static
Definition at line 298 of file accpp.c.
Referenced by delete(), and lookup().
struct { ... } idir
Referenced by _doincl(), _nextline(), accpp(), and stash_paths().
ifp
FILE* ifp static
Definition at line 254 of file accpp.c.
Referenced by _doincl(), _nextline(), and accpp().
ifsize
int ifsize static
Definition at line 294 of file accpp.c.
Referenced by accpp(), and ifpush().
iftop
int iftop static
Definition at line 293 of file accpp.c.
Referenced by accpp(), and ifpush().
in_dodef
LOGICAL in_dodef static
Definition at line 317 of file accpp.c.
Referenced by dodef(), and nextok().
in_ftn_comment
LOGICAL in_ftn_comment static
Definition at line 320 of file accpp.c.
Referenced by accpp(), clreol(), findtok(), and nextok().
incfiles
int incfiles = 0 static
Definition at line 538 of file accpp.c.
Referenced by accpp(), and add_to_incllist().
inclev
INT inclev = 0 static
Definition at line 533 of file accpp.c.
Referenced by _doincl(), _nextline(), add_to_incllist(), doline(), pr_line(), ptok(), and subst().
incllist
INCLENTRY* incllist static
Definition at line 537 of file accpp.c.
Referenced by accpp(), and add_to_incllist().
inclsize
int inclsize static
Definition at line 539 of file accpp.c.
Referenced by add_to_incllist().
inclstack
INCLSTACK* inclstack static
Definition at line 531 of file accpp.c.
Referenced by _doincl(), _nextline(), accpp(), add_to_incllist(), doline(), pr_line(), ptok(), and subst().
incsize
INT incsize static
Definition at line 532 of file accpp.c.
Referenced by _doincl(), and accpp().
last
int last
Definition at line 589 of file accpp.c.
Referenced by _dinit_acl(), add_isoc_intrinsics(), add_tmp_buf_list_item(), additl(), binop_init_list(), change_predefineds(), chncsl(), copyl(), delcs(), end_param(), exp_smp(), export_iso_c_libraries(), fastset_internal_drop_at(), fastset_remove(), fill_links_symbol(), flushsym(), get_rutime(), insertsrt(), link_iollist(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), maybe_generate_fma(), mk_lastprivate_list(), mk_reduction_list(), mk_shared_list(), open_module(), overwrite_fma_add(), plist(), save_firstprivate_list(), save_private_list(), save_shared_list(), tablea(), unop_init_list(), and write_typedescs().
lbp
short lbp
Definition at line 3324 of file accpp.c.
Referenced by parse().
led
INT8 led
Definition at line 3319 of file accpp.c.
Referenced by parse().
linebuf
char* linebuf static
Definition at line 545 of file accpp.c.
Referenced by _nextline(), accpp(), clreol(), nextok(), pbchar(), pbstr(), realloc_linebuf(), and subst().
lineend
char * lineend static
Definition at line 542 of file accpp.c.
Referenced by _nextline(), accpp(), nextok(), and realloc_linebuf().
linelen
int linelen static
Definition at line 543 of file accpp.c.
Referenced by _nextline(), accpp(), and realloc_linebuf().
lineloc
int lineloc static
Definition at line 548 of file accpp.c.
Referenced by accpp(), and subst().
lineptr
char* lineptr static
Definition at line 542 of file accpp.c.
Referenced by _nextline(), accpp(), clreol(), nextok(), pbchar(), pbstr(), popstack(), realloc_linebuf(), and subst().
linesize
INT linesize static
Definition at line 544 of file accpp.c.
Referenced by _nextline(), accpp(), and realloc_linebuf().
list_flag
int list_flag static
Definition at line 566 of file accpp.c.
Referenced by _nextline(), and accpp().
macstk
struct macstk_type macstk[MACSTK_MAX] static
Definition at line 573 of file accpp.c.
Referenced by mac_push(), macro_recur_check(), popstack(), and realloc_linebuf().
macstk_top
int macstk_top = -1 static
Definition at line 574 of file accpp.c.
Referenced by mac_push(), macro_recur_check(), popstack(), and realloc_linebuf().
ndef
INT ndef static
Definition at line 304 of file accpp.c.
Referenced by strstore().
next_def
INT next_def static
Definition at line 304 of file accpp.c.
Referenced by _avail(), and strstore().
next_hash
INT next_hash static
Definition at line 300 of file accpp.c.
Referenced by acc_display_macros(), and lookup().
nhash
INT nhash static
Definition at line 300 of file accpp.c.
Referenced by lookup().
nifile
int nifile static
Definition at line 577 of file accpp.c.
Referenced by accpp().
nud
INT8 nud
Definition at line 3321 of file accpp.c.
path
int* path
Definition at line 581 of file accpp.c.
Referenced by __abort_init(), __fort_getdir(), __fort_zopen(), ENT3F(), fndpath(), and stash_paths().
pflag
int pflag static
Definition at line 565 of file accpp.c.
Referenced by _contains_any_call(), _contains_ast(), _contains_sptr(), _is_another_shift(), accpp(), emit_scatterx_gatherx(), emit_sum_scatterx(), generate_gather(), and pr_line().
pred
int pred = 0 static
Definition at line 4935 of file accpp.c.
Referenced by __rss_log_fma3(), call_in_path(), cp_loop(), def_in_out(), dumpfnode(), find_bivs(), have_preheader(), in_path(), pred_of_loop(), predarg(), predicate(), and sched_block_breadth_first().
prednum
int prednum = 1 static
Definition at line 4934 of file accpp.c.
Referenced by predicate().
predtab
char* predtab[NPRED] static
Definition at line 4933 of file accpp.c.
Referenced by predarg(), and predicate().
prevfile
const char* prevfile = NULL static
Definition at line 313 of file accpp.c.
Referenced by _doincl(), putmac(), and putunmac().
prevline
int prevline = -1 static
Definition at line 314 of file accpp.c.
Referenced by _doincl(), putmac(), and putunmac().
struct { ... } PT[]
define parse table, PT, which has an entry for each of the tokens just defined:
Referenced by parse().
rbp
INT8 rbp
Definition at line 3325 of file accpp.c.
Referenced by parse().
savlptr
char * savlptr static
Definition at line 542 of file accpp.c.
Referenced by realloc_linebuf(), and subst().
startline
int startline static
Definition at line 563 of file accpp.c.
Referenced by _doincl(), _nextline(), accpp(), dodef(), lldbg_assign_lexical_block(), lldbg_emit_lexical_block(), lldbg_emit_line(), lldbg_limit_lexical_blocks(), lldbg_reserve_lexical_block(), mac_push(), ptok(), putmac(), putunmac(), read_symbol(), and subst().
suffix
const char* suffix = ".o" static
Definition at line 310 of file accpp.c.
Referenced by get_implementation(), getccssym(), getccsym(), getccsym_sc(), intrin_name(), ll_get_array_type(), process_formal_arguments(), put_ll_table_addr(), setsuffix(), and write_typedescs().
syntaxerr
int syntaxerr static
Definition at line 528 of file accpp.c.
Referenced by doparse(), and parse().
sz
int sz
Definition at line 583 of file accpp.c.
token
int token static
Definition at line 526 of file accpp.c.
Referenced by doparse(), and parse().
tokenval
PTOK tokenval static
Definition at line 527 of file accpp.c.
Referenced by gettoken(), and parse().
toktyp
int toktyp static
Definition at line 576 of file accpp.c.
Referenced by accpp(), clreol(), dodef(), doerror(), doident(), doincl(), doline(), domodule(), dopragma(), doundef(), dowarning(), findtok(), fpp(), gettoken(), gtok(), nextok(), parse(), skipbl(), and subst().
zero64
DBLINT64 zero64 = {0, 0} static
Definition at line 449 of file accpp.c.