flang: aligned.c File Reference
aligned.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "fort_vars.h"
Functions
int I8() __fort_conform (F90_Desc *s, __INT_T *smap, F90_Desc *t, __INT_T *tmap)
Compare rank and shape of objects s and t. Return true if s and t are conformable under the axis mappings smap and tmap. Scalars are conformable with arrays. conform(A,B) implies conform(B,A).
int I8() __fort_covers_procs (F90_Desc *s, F90_Desc *t)
int I8() __fort_aligned (F90_Desc *t, __INT_T *tmap, F90_Desc *u, __INT_T *umap)
Leftover from HPF Fortran.
int I8() __fort_aligned_axes (F90_Desc *t, int tx, F90_Desc *u, int ux)
Leftover from HPF Fortran.
Detailed Description
Routines to test array conformance
Definition in file aligned.c.
Function Documentation
__fort_aligned()
int I8() __fort_aligned (F90_Desc * t, __INT_T * tmap, F90_Desc * u, __INT_T * umap)
Leftover from HPF Fortran.
Definition at line 55 of file aligned.c.
Referenced by __fort_gathscat().
__fort_aligned_axes()
int I8() __fort_aligned_axes (F90_Desc * t, int tx, F90_Desc * u, int ux)
Leftover from HPF Fortran.
Definition at line 69 of file aligned.c.
Referenced by __fort_gathscat().
__fort_conform()
int I8() __fort_conform (F90_Desc * s, __INT_T * smap, F90_Desc * t, __INT_T * tmap)
Compare rank and shape of objects s and t. Return true if s and t are conformable under the axis mappings smap and tmap. Scalars are conformable with arrays. conform(A,B) implies conform(B,A).
Definition at line 21 of file aligned.c.
References __DESC, DECL_DIM_PTRS, dim, F90_DPTR_EXTENT_G, F90_GSIZE_G, F90_RANK_G, F90_TAG_G, NULL, s, SET_DIM_PTRS, t, and td.
Referenced by __fort_gathscat().
__fort_covers_procs()
int I8() __fort_covers_procs (F90_Desc * s, F90_Desc * t)
Definition at line 44 of file aligned.c.
Referenced by __fort_gathscat().