flang: allo.c File Reference
allo.c File Reference
#include <string.h>
#include <stdlib.h>
#include "stdioInterf.h"
#include "fioMacros.h"
#include "type.h"
#include "llcrit.h"
#include "f90alloc.h"
#include "fort_vars.h"
Classes
struct ALLO_HDR
struct SAL
Macros
#define DEBUG 1
#define ASZ 16
#define AUTOASZ 16
#define USE_MEMALIGN
#define MASKP(len) ((len)-1)
#define ALIGNP(p, len) ((char *)(((__POINT_T)(((char *)p) + (len)-1)) & ~MASKP(len)))
#define SEL_HDR(area) ((((__POINT_T)area >> 7)) & (num_hdrs - 1))
#define NUM_HDRS 1024 * 64
#define XYZZY(a) ((void **)a)[-1]
#define XYZZYP(a, p) XYZZY(a) = p
#define __man_malloc malloc
#define __man_callocx calloc
#define __man_free free
#define __pin_malloc malloc
#define __pin_callocx calloc
#define __pin_free free
#define ALLHDR()
#define ALN_LARGE
#define ALN_THRESH (ALN_MAXADJ / ALN_UNIT)
#define ALN_LARGE
#define ALN_THRESH (ALN_MAXADJ / ALN_UNIT)
#define TLS_DECL
#define MP_P_ALLO _mp_p(&sem_allo)
#define MP_V_ALLO _mp_v(&sem_allo)
#define AUTO_ALN_THRESH (AUTO_ALN_MAXADJ / AUTO_ALN_UNIT)
Typedefs
typedef struct ALLO_HDR ALLO_HDR
Functions
MP_SEMAPHORE (static, sem)
int I8() __fort_ptr_aligned (char *p1, dtype kind, int len, char *p2)
Return nonzero if addresses p1 and p2 are aligned with respect to a multiple of the length of the data type.
char *I8() __fort_ptr_offset (char **pointer, __POINT_T *offset, char *base, dtype kind, __CLEN_T len, char *area)
Compute pointer-sized index offset to replace Cray pointer, return aligned address. offset assumes 1-based arrays.
void ENTFTN (PTR_OFFSET, ptr_offset)
Compute pointer-sized index offset to replace Cray pointer. offset assumes 1-based arrays. DOES NOT WORK FOR CHARACTER DATA TYPE.
char *I8() __fort_alloc (__INT_T nelem, dtype kind, size_t len, __STAT_T *stat, char **pointer, __POINT_T *offset, char *base, int check, void *(*mallocfn)(size_t))
allocate space using given 'malloc' function. if present, set pointer and pointer-sized integer offset from base address. offset is in units of the data type length.
static char *I8() __alloc04 (__NELEM_T nelem, dtype kind, size_t len, __STAT_T *stat, char **pointer, __POINT_T *offset, char *base, int check, void *(*mallocfn)(size_t), size_t align, char *errmsg, int errlen)
allocate space using given 'malloc' function. if present, set pointer and pointer-sized integer offset from base address. offset is in units of the data type length.
char *I8() __fort_kalloc (__INT8_T nelem, dtype kind, size_t len, __STAT_T *stat, char **pointer, __POINT_T *offset, char *base, int check, void *(*mallocfn)(size_t))
allocate space using given 'malloc' function. if present, set pointer and pointer-sized integer offset from base address. offset is in units of the data type length.
int I8() __fort_allocated (char *area)
Is array allocated?
__LOG_T I8() ftn_allocated (char *area)
__LOG_T ENTF90 (ALLOCATED, allocated)
__LOG_T ENTF90 (ALLOCATED2, allocated2)
__LOG_T ENTF90 (ALLOCATED_LHS, allocated_lhs)
__LOG_T ENTF90 (ALLOCATED_LHS2, allocated_lhs2)
__LOG8_T ENTF90 (KALLOCATED, kallocated)
__LOG8_T ENTF90 (KALLOCATED2, kallocated2)
__LOG8_T ENTF90 (KALLOCATED_LHS, kallocated_lhs)
__LOG8_T ENTF90 (KALLOCATED_LHS2, kallocated_lhs2)
char *I8() ftn_allocate (int size, __STAT_T *stat)
F77 allocate statement – don't check allocated status.
char *I8() ftn_alloc (int size, __STAT_T *stat, char *area)
F77 allocate statement – check allocated status.
MP_SEMAPHORE (static, sem_allo)
void __f90_allo_term (void)
F90 allocate statement – check allocated status.
static void save_alloc (__POINT_T nelem, __INT_T len, char **pointer)
static void * use_alloc (__POINT_T nelem, __INT_T len)
static void * reuse_alloc (__STAT_T *stat, char *area)
void ENTF90 (ALLOCA, alloca)
void ENTF90 (ALLOC, alloc)
void ENTF90 (ALLOC03A, alloc03a)
void ENTF90 (ALLOC03, alloc03)
void ENTF90 (ALLOC03_CHKA, alloc03_chka)
void ENTF90 (ALLOC03_CHK, alloc03_chk)
void ENTF90 (REALLOC_ARR_IN_IMPLIED_DO, realloc_arr_in_impiled_do)
void ENTF90 (ALLOC04A, alloc04a)
void ENTF90 (ALLOC04, alloc04)
void ENTF90 (ALLOC04_CHKA, alloc04_chka)
void ENTF90 (ALLOC04_CHK, alloc04_chk)
void ENTF90 (KALLOC, kalloc)
void ENTF90 (CALLOC, calloc)
void ENTF90 (CALLOC03A, calloc03a)
void ENTF90 (CALLOC03, calloc03)
void ENTF90 (CALLOC04A, calloc04a)
void ENTF90 (CALLOC04, calloc04)
void ENTF90 (KCALLOC, kcalloc)
void ENTF90 (PTR_ALLOCA, ptr_alloca)
F90 allocate statement – don't check allocated status.
void ENTF90 (PTR_ALLOC, ptr_alloc)
void ENTF90 (PTR_ALLOC03A, ptr_alloc03a)
F90 allocate statement – don't check allocated status.
void ENTF90 (PTR_ALLOC03, ptr_alloc03)
void ENTF90 (PTR_ALLOC04A, ptr_alloc04a)
void ENTF90 (PTR_ALLOC04, ptr_alloc04)
void ENTF90 (PTR_SRC_ALLOC03A, ptr_src_alloc03a)
Same as ptr_alloc03 above, except it's used with sourced allocation where the destination or source argument is polymorphic. So, we neeed to get the size from the source descriptor and allocate the source size if it's greater than the destination size passed in *len.
void ENTF90 (PTR_SRC_ALLOC03, ptr_src_alloc03)
void ENTF90 (PTR_SRC_CALLOC03A, ptr_src_calloc03a)
void ENTF90 (PTR_SRC_CALLOC03, ptr_src_calloc03)
void ENTF90 (PTR_SRC_ALLOC04A, ptr_src_alloc04a)
void ENTF90 (PTR_SRC_ALLOC04, ptr_src_alloc04)
void (F90_Desc *sd, __NELEM_T *nelem, __INT_T *kind, __INT_T *len, __STAT_T *stat, char **pointer, __POINT_T *offset, __INT_T *firsttime, __NELEM_T *align, DCHAR(errmsg) DCLEN64(errmsg))
void (F90_Desc *sd, __NELEM_T *nelem, __INT_T *kind, __INT_T *len, __STAT_T *stat, char **pointer, __POINT_T *offset, __INT_T *firsttime, __NELEM_T *align, DCHAR(errmsg) DCLEN(errmsg))
void ENTF90 (PTR_KALLOC, ptr_kalloc)
64 bit F90 allocate statement – don't check allocated status
void ENTF90 (PTR_CALLOC, ptr_calloc)
void (__INT_T *nelem, __INT_T *kind, __INT_T *len, __STAT_T *stat, char **pointer, __POINT_T *offset, __INT_T *firsttime, DCHAR(errmsg) DCLEN64(errmsg))
void (__INT_T *nelem, __INT_T *kind, __INT_T *len, __STAT_T *stat, char **pointer, __POINT_T *offset, __INT_T *firsttime, DCHAR(errmsg) DCLEN(errmsg))
void ENTF90 (PTR_CALLOC04A, ptr_calloc04a)
void ENTF90 (PTR_CALLOC04, ptr_calloc04)
void ENTF90 (PTR_KCALLOC, ptr_kcalloc)
char *I8() __fort_allocate (int nelem, dtype kind, size_t len, char *base, char **pointer, __POINT_T *offset)
Allocate global array (must be same size on all processors), return pointer and pointer-sized integer offset from base address. offset is in units of the data type length. don't check allocated status.
char *I8() __fort_local_allocate (int nelem, dtype kind, size_t len, char *base, char **pointer, __POINT_T *offset)
Allocate local array (may be different size on each processor), return pointer and pointer-sized integer offset from base address. offset is in units of the data type length. don't check allocated status.
char *I8() __fort_kallocate (long nelem, dtype kind, size_t len, char *base, char **pointer, __POINT_T *offset)
Allocate global array (must be same size on all processors), return pointer and pointer-sized integer offset from base address. offset is in units of the data type length. don't check allocated status.
char *I8() __fort_local_kallocate (long nelem, dtype kind, size_t len, char *base, char **pointer, __POINT_T *offset)
Allocate local array (may be different size on each processor), return pointer and pointer-sized integer offset from base address. offset is in units of the data type length. don't check allocated status.
char *I8() __fort_dealloc (char *area, __STAT_T *stat, void(*freefn)(void *))
Deallocate array using given 'free' function.
static char *I8() __fort_dealloc03 (char *area, __STAT_T *stat, void(*freefn)(void *), char *errmsg, int errlen)
void I8() ftn_deallocate (char *area, __STAT_T *stat)
F77 deallocate statement.
char *I8() ftn_dealloc (char *area, __STAT_T *stat)
void ENTF90 (DEALLOCA, dealloca)
f90 deallocate statement
void ENTF90 (DEALLOC, dealloc)
void ENTF90 (DEALLOC03A, dealloc03a)
void ENTF90 (DEALLOC03, dealloc03)
void ENTF90 (DEALLOC_MBR, dealloc_mbr)
void ENTF90 (DEALLOC_MBR03A, dealloc_mbr03a)
void ENTF90 (DEALLOC_MBR03, dealloc_mbr03)
void ENTF90 (DEALLOCX, deallocx)
void I8() __fort_deallocate (char *area)
deallocate global array
void I8() __fort_local_deallocate (char *area)
deallocate local array
static void *I8() __auto_alloc (__NELEM_T nelem, __INT_T sz, void *(*mallocroutine)(size_t))
void * ENTF90 (AUTO_ALLOCV, auto_allocv)
void * ENTF90 (AUTO_ALLOC, auto_alloc)
void * ENTF90 (AUTO_ALLOC04, auto_alloc04)
void * ENTF90 (AUTO_CALLOC, auto_calloc)
void * ENTF90 (AUTO_CALLOC04, auto_calloc04)
void ENTF90 (AUTO_DEALLOC, auto_dealloc)
void ENTRY (__FTN_ALLOC_DUMP, __ftn_alloc_dump)()
Variables
static ALLO_HDR * allo_list
static long num_hdrs = NUM_HDRS
static SAL savedalloc = {0, -99, (char *)0}
static size_t AUTO_ALN_MINSZ = 128000
static size_t AUTO_ALN_UNIT = 64
static size_t AUTO_ALN_MAXADJ = 4096
Detailed Description
Runtime memory allocation routines
Definition in file allo.c.
Macro Definition Documentation
__man_callocx
#define __man_callocx calloc
Definition at line 94 of file allo.c.
__man_free
#define __man_free free
Definition at line 95 of file allo.c.
__man_malloc
#define __man_malloc malloc
Definition at line 93 of file allo.c.
__pin_callocx
#define __pin_callocx calloc
Definition at line 97 of file allo.c.
__pin_free
#define __pin_free free
Definition at line 98 of file allo.c.
__pin_malloc
#define __pin_malloc malloc
Definition at line 96 of file allo.c.
ALIGNP
#define ALIGNP (p, len) ((char *)(((__POINT_T)(((char *)p) + (len)-1)) & ~MASKP(len)))
Definition at line 43 of file allo.c.
ALLHDR
#define ALLHDR ()
Definition at line 102 of file allo.c.
ALN_LARGE [1/2]
#define ALN_LARGE
ALN_LARGE [2/2]
#define ALN_LARGE
ALN_THRESH [1/2]
#define ALN_THRESH (ALN_MAXADJ / ALN_UNIT)
ALN_THRESH [2/2]
#define ALN_THRESH (ALN_MAXADJ / ALN_UNIT)
ASZ
#define ASZ 16
Definition at line 29 of file allo.c.
AUTO_ALN_THRESH
#define AUTO_ALN_THRESH (AUTO_ALN_MAXADJ / AUTO_ALN_UNIT)
AUTOASZ
#define AUTOASZ 16
Definition at line 31 of file allo.c.
DEBUG
#define DEBUG 1
Definition at line 19 of file allo.c.
MASKP
#define MASKP (len) ((len)-1)
Definition at line 41 of file allo.c.
MP_P_ALLO
#define MP_P_ALLO _mp_p(&sem_allo)
Definition at line 715 of file allo.c.
MP_V_ALLO
#define MP_V_ALLO _mp_v(&sem_allo)
Definition at line 716 of file allo.c.
NUM_HDRS
#define NUM_HDRS 1024 * 64
Definition at line 84 of file allo.c.
SEL_HDR
#define SEL_HDR (area) ((((__POINT_T)area >> 7)) & (num_hdrs - 1))
Definition at line 83 of file allo.c.
TLS_DECL
#define TLS_DECL
Definition at line 713 of file allo.c.
USE_MEMALIGN
#define USE_MEMALIGN
Definition at line 34 of file allo.c.
XYZZY
#define XYZZY (a) ((void **)a)[-1]
Definition at line 86 of file allo.c.
XYZZYP
#define XYZZYP (a, p) XYZZY(a) = p
Definition at line 87 of file allo.c.
Typedef Documentation
ALLO_HDR
typedef struct ALLO_HDR ALLO_HDR
Definition at line 69 of file allo.c.
Function Documentation
__alloc04()
static char *I8() __alloc04 (__NELEM_T nelem, dtype kind, size_t len, __STAT_T * stat, char ** pointer, __POINT_T * offset, char * base, int check, void *(*)(size_t) mallocfn, size_t align, char * errmsg, int errlen) static
allocate space using given 'malloc' function. if present, set pointer and pointer-sized integer offset from base address. offset is in units of the data type length.
Definition at line 369 of file allo.c.
References __DERIVED, __fort_abort(), __fort_allocated(), __fort_test, __STR, ALIGNP, ALLHDR, ALN_MAXADJ, ALN_MINSZ, ALN_THRESH, ALN_UNIT, area, ASZ, AUTOASZ, base, DEBUG_ALLO, GET_DIST_LCPU, GET_DIST_SHIFTS, getenv(), i, I8, ISPRESENT, kind, len, MP_P_STDIO, MP_V_STDIO, msg(), nelem, NULL, off, offset, p, pointer, size, stat, and XYZZYP.
Referenced by ENTF90(), and void().
__auto_alloc()
static void *I8() __auto_alloc (__NELEM_T nelem, __INT_T sz, void *(*)(size_t) mallocroutine) static
Definition at line 1739 of file allo.c.
References __fort_abort(), area, ASZ, AUTO_ALN_MINSZ, AUTO_ALN_THRESH, AUTO_ALN_UNIT, AUTOASZ, MP_P_STDIO, MP_V_STDIO, msg(), nelem, NULL, p, size, sz, and XYZZYP.
Referenced by ENTF90().
__f90_allo_term()
void __f90_allo_term (void)
F90 allocate statement – check allocated status.
Definition at line 735 of file allo.c.
References __fort_free(), area, SAL::len, MP_P_ALLO, MP_V_ALLO, NULL, SAL::pointer, savedalloc, SAL::valid, and XYZZY.
Referenced by term().
__fort_alloc()
char *I8() __fort_alloc (__INT_T nelem, dtype kind, size_t len, __STAT_T * stat, char ** pointer, __POINT_T * offset, char * base, int check, void *(*)(size_t) mallocfn)
allocate space using given 'malloc' function. if present, set pointer and pointer-sized integer offset from base address. offset is in units of the data type length.
Definition at line 230 of file allo.c.
References __DERIVED, __fort_abort(), __fort_test, __STR, ALIGNP, ALLHDR, ALN_MAXADJ, ALN_MINSZ, ALN_THRESH, ALN_UNIT, area, ASZ, AUTOASZ, base, DEBUG_ALLO, GET_DIST_LCPU, GET_DIST_SHIFTS, getenv(), ISPRESENT, kind, len, MP_P, MP_P_STDIO, MP_V, MP_V_STDIO, msg(), nelem, NULL, off, offset, p, pointer, sem, size, stat, and XYZZYP.
Referenced by __fort_allocate(), __fort_local_allocate(), ENTF90(), ftn_alloc(), ftn_allocate(), and void().
__fort_allocate()
char *I8() __fort_allocate (int nelem, dtype kind, size_t len, char * base, char ** pointer, __POINT_T * offset)
Allocate global array (must be same size on all processors), return pointer and pointer-sized integer offset from base address. offset is in units of the data type length. don't check allocated status.
Definition at line 1492 of file allo.c.
References __fort_alloc(), __fort_gmalloc_without_abort(), base, I8, kind, len, nelem, NULL, offset, and pointer.
Referenced by ENTF90(), and recopy().
__fort_allocated()
int I8() __fort_allocated (char * area)
Is array allocated?
Definition at line 611 of file allo.c.
References ALLHDR, and area.
Referenced by __alloc04(), ENTF90(), ftn_allocated(), process_final_procedures(), and sourced_alloc_and_assign().
__fort_dealloc()
char *I8() __fort_dealloc (char * area, __STAT_T * stat, void(*)(void *) freefn)
Deallocate array using given 'free' function.
Definition at line 1545 of file allo.c.
References __fort_abort(), __fort_test, ALLHDR, area, DEBUG_ALLO, GET_DIST_LCPU, ISPRESENT, MP_P_STDIO, MP_V_STDIO, msg(), NULL, p, stat, and XYZZY.
Referenced by __fort_deallocate(), __fort_local_deallocate(), ENTF90(), ftn_dealloc(), ftn_deallocate(), use_alloc(), and void().
__fort_dealloc03()
static char *I8() __fort_dealloc03 (char * area, __STAT_T * stat, void(*)(void *) freefn, char * errmsg, int errlen) static
Definition at line 1578 of file allo.c.
References __fort_abort(), __fort_test, ALLHDR, area, DEBUG_ALLO, GET_DIST_LCPU, i, ISPRESENT, MP_P_STDIO, MP_V_STDIO, msg(), NULL, p, stat, and XYZZY.
Referenced by ENTF90().
__fort_deallocate()
void I8() __fort_deallocate (char * area)
deallocate global array
Definition at line 1719 of file allo.c.
References __fort_dealloc(), __fort_gfree(), area, I8, NULL, and void().
Referenced by ENTF90(), and recopy().
__fort_kalloc()
char *I8() __fort_kalloc (__INT8_T nelem, dtype kind, size_t len, __STAT_T * stat, char ** pointer, __POINT_T * offset, char * base, int check, void *(*)(size_t) mallocfn)
allocate space using given 'malloc' function. if present, set pointer and pointer-sized integer offset from base address. offset is in units of the data type length.
Definition at line 529 of file allo.c.
References __DERIVED, __fort_abort(), __fort_test, __STR, ALIGNP, ALLHDR, area, ASZ, AUTOASZ, base, DEBUG_ALLO, GET_DIST_LCPU, GET_DIST_SHIFTS, ISPRESENT, kind, len, MP_P, MP_P_STDIO, MP_V, MP_V_STDIO, msg(), nelem, NULL, off, offset, p, pointer, sem, size, and stat.
Referenced by __fort_kallocate(), __fort_local_kallocate(), and ENTF90().
__fort_kallocate()
char *I8() __fort_kallocate (long nelem, dtype kind, size_t len, char * base, char ** pointer, __POINT_T * offset)
Allocate global array (must be same size on all processors), return pointer and pointer-sized integer offset from base address. offset is in units of the data type length. don't check allocated status.
Definition at line 1519 of file allo.c.
References __fort_gmalloc_without_abort(), __fort_kalloc(), base, I8, kind, len, nelem, NULL, offset, and pointer.
__fort_local_allocate()
char *I8() __fort_local_allocate (int nelem, dtype kind, size_t len, char * base, char ** pointer, __POINT_T * offset)
Allocate local array (may be different size on each processor), return pointer and pointer-sized integer offset from base address. offset is in units of the data type length. don't check allocated status.
Definition at line 1506 of file allo.c.
References __fort_alloc(), __fort_malloc_without_abort(), base, I8, kind, len, nelem, NULL, offset, and pointer.
Referenced by ENTFTN().
__fort_local_deallocate()
void I8() __fort_local_deallocate (char * area)
deallocate local array
Definition at line 1729 of file allo.c.
References __fort_dealloc(), __fort_free(), area, I8, NULL, and void().
Referenced by __fort_copy_out().
__fort_local_kallocate()
char *I8() __fort_local_kallocate (long nelem, dtype kind, size_t len, char * base, char ** pointer, __POINT_T * offset)
Allocate local array (may be different size on each processor), return pointer and pointer-sized integer offset from base address. offset is in units of the data type length. don't check allocated status.
Definition at line 1534 of file allo.c.
References __fort_kalloc(), __fort_malloc_without_abort(), base, I8, kind, len, nelem, NULL, offset, and pointer.
__fort_ptr_aligned()
int I8() __fort_ptr_aligned (char * p1, dtype kind, int len, char * p2)
Return nonzero if addresses p1 and p2 are aligned with respect to a multiple of the length of the data type.
Definition at line 148 of file allo.c.
References __DERIVED, __STR, GET_DIST_SHIFTS, kind, len, and off.
Referenced by ENTFTN().
__fort_ptr_offset()
char *I8() __fort_ptr_offset (char ** pointer, __POINT_T * offset, char * base, dtype kind, __CLEN_T len, char * area)
Compute pointer-sized index offset to replace Cray pointer, return aligned address. offset assumes 1-based arrays.
Definition at line 165 of file allo.c.
References __DERIVED, __fort_test, __STR, area, base, DEBUG_ALLO, GET_DIST_LCPU, GET_DIST_SHIFTS, ISPRESENT, kind, len, off, offset, and pointer.
Referenced by ENTFTN(), nullify(), ptr_asgn(), and ptr_in().
ENTF90() [1/57]
void ENTF90 (ALLOC , alloc)
Definition at line 862 of file allo.c.
References __CLEN_T, ALLOCA, base, CADR, CLEN, ENTF90(), kind, len, nelem, offset, pointer, and stat.
ENTF90() [2/57]
void ENTF90 (ALLOC03 , alloc03)
Definition at line 899 of file allo.c.
References __CLEN_T, CADR, CLEN, ENTF90(), firsttime, kind, len, nelem, offset, pointer, and stat.
ENTF90() [3/57]
void ENTF90 (ALLOC03_CHK , alloc03_chk)
Definition at line 928 of file allo.c.
References __CLEN_T, CADR, CLEN, ENTF90(), firsttime, kind, len, nelem, offset, pointer, and stat.
ENTF90() [4/57]
void ENTF90 (ALLOC03_CHKA , alloc03_chka)
Definition at line 908 of file allo.c.
References __fort_abort(), __fort_allocated(), CADR, CLEN, ENTF90(), firsttime, I8, ISPRESENT, kind, len, nelem, offset, pointer, and stat.
ENTF90() [5/57]
void ENTF90 (ALLOC03A , alloc03a)
Definition at line 871 of file allo.c.
References __alloc04(), __fort_gmalloc_without_abort(), __fort_malloc_without_abort(), ALLHDR, CADR, CLEN, firsttime, I8, ISPRESENT, kind, len, LOCAL_MODE, nelem, offset, pointer, save_alloc(), stat, use_alloc(), and void().
ENTF90() [6/57]
void ENTF90 (ALLOC04 , alloc04)
Definition at line 998 of file allo.c.
References __CLEN_T, CADR, CLEN, ENTF90(), firsttime, kind, len, nelem, offset, pointer, and stat.
ENTF90() [7/57]
void ENTF90 (ALLOC04_CHK , alloc04_chk)
Definition at line 1030 of file allo.c.
References __CLEN_T, CADR, CLEN, ENTF90(), firsttime, kind, len, nelem, offset, pointer, and stat.
ENTF90() [8/57]
void ENTF90 (ALLOC04_CHKA , alloc04_chka)
Definition at line 1008 of file allo.c.
References __fort_abort(), __fort_allocated(), CADR, CLEN, ENTF90(), firsttime, I8, ISPRESENT, kind, len, nelem, offset, pointer, and stat.
ENTF90() [9/57]
void ENTF90 (ALLOC04A , alloc04a)
Definition at line 969 of file allo.c.
References __alloc04(), __fort_gmalloc_without_abort(), __fort_malloc_without_abort(), ALLHDR, CADR, CLEN, firsttime, I8, ISPRESENT, kind, len, LOCAL_MODE, nelem, offset, pointer, save_alloc(), stat, use_alloc(), and void().
ENTF90() [10/57]
void ENTF90 (ALLOCA , alloca)
Definition at line 837 of file allo.c.
References __fort_alloc(), __fort_gmalloc_without_abort(), __fort_malloc_without_abort(), ALLHDR, base, CADR, I8, ISPRESENT, kind, len, LOCAL_MODE, nelem, offset, pointer, save_alloc(), stat, use_alloc(), and void().
ENTF90() [11/57]
__LOG_T ENTF90 (ALLOCATED , allocated)
Definition at line 628 of file allo.c.
References __fort_allocated(), area, GET_DIST_TRUE_LOG, and I8.
Referenced by ENTF90(), and void().
ENTF90() [12/57]
__LOG_T ENTF90 (ALLOCATED2 , allocated2)
Definition at line 634 of file allo.c.
References __fort_allocated(), area, GET_DIST_TRUE_LOG, and I8.
ENTF90() [13/57]
__LOG_T ENTF90 (ALLOCATED_LHS , allocated_lhs)
Definition at line 640 of file allo.c.
References __fort_allocated(), area, GET_DIST_TRUE_LOG, and I8.
ENTF90() [14/57]
__LOG_T ENTF90 (ALLOCATED_LHS2 , allocated_lhs2)
Definition at line 646 of file allo.c.
References __fort_allocated(), area, GET_DIST_TRUE_LOG, and I8.
ENTF90() [15/57]
void * ENTF90 (AUTO_ALLOC , auto_alloc)
Definition at line 1798 of file allo.c.
References __auto_alloc(), I8, malloc(), nelem, p, and sz.
ENTF90() [16/57]
void * ENTF90 (AUTO_ALLOC04 , auto_alloc04)
Definition at line 1807 of file allo.c.
References __auto_alloc(), I8, malloc(), nelem, p, and sz.
ENTF90() [17/57]
void * ENTF90 (AUTO_ALLOCV , auto_allocv)
Definition at line 1789 of file allo.c.
References __auto_alloc(), I8, malloc(), nelem, p, and sz.
ENTF90() [18/57]
void * ENTF90 (AUTO_CALLOC , auto_calloc)
Definition at line 1816 of file allo.c.
References __auto_alloc(), I8, malloc(), nelem, p, size, and sz.
ENTF90() [19/57]
void * ENTF90 (AUTO_CALLOC04 , auto_calloc04)
Definition at line 1831 of file allo.c.
References __auto_alloc(), I8, malloc(), nelem, p, size, and sz.
ENTF90() [20/57]
void ENTF90 (AUTO_DEALLOC , auto_dealloc)
Definition at line 1846 of file allo.c.
References area, and XYZZY.
ENTF90() [21/57]
void ENTF90 (CALLOC , calloc)
Definition at line 1062 of file allo.c.
References __fort_alloc(), __fort_calloc_without_abort(), __fort_gcalloc_without_abort(), base, CADR, I8, kind, len, LOCAL_MODE, nelem, offset, pointer, stat, and void().
ENTF90() [22/57]
void ENTF90 (CALLOC03 , calloc03)
Definition at line 1088 of file allo.c.
References __CLEN_T, CADR, CLEN, ENTF90(), firsttime, kind, len, nelem, offset, pointer, and stat.
ENTF90() [23/57]
void ENTF90 (CALLOC03A , calloc03a)
Definition at line 1072 of file allo.c.
References __alloc04(), __fort_calloc_without_abort(), __fort_gcalloc_without_abort(), CADR, CLEN, firsttime, I8, ISPRESENT, kind, len, LOCAL_MODE, nelem, offset, pointer, stat, and void().
ENTF90() [24/57]
void ENTF90 (CALLOC04 , calloc04)
Definition at line 1116 of file allo.c.
References __CLEN_T, CADR, CLEN, ENTF90(), firsttime, kind, len, nelem, offset, pointer, and stat.
ENTF90() [25/57]
void ENTF90 (CALLOC04A , calloc04a)
Definition at line 1100 of file allo.c.
References __alloc04(), __fort_calloc_without_abort(), __fort_gcalloc_without_abort(), CADR, CLEN, firsttime, I8, ISPRESENT, kind, len, LOCAL_MODE, nelem, offset, pointer, stat, and void().
ENTF90() [26/57]
void ENTF90 (DEALLOC , dealloc)
Definition at line 1650 of file allo.c.
References __CLEN_T, area, CADR, CLEN, ENTF90(), and stat.
ENTF90() [27/57]
void ENTF90 (DEALLOC03 , dealloc03)
Definition at line 1670 of file allo.c.
References __CLEN_T, area, CADR, CLEN, ENTF90(), firsttime, and stat.
ENTF90() [28/57]
void ENTF90 (DEALLOC03A , dealloc03a)
Definition at line 1656 of file allo.c.
References __fort_dealloc03(), __fort_free(), __fort_gfree(), area, CADR, CLEN, firsttime, I8, ISPRESENT, LOCAL_MODE, reuse_alloc(), stat, and void().
ENTF90() [29/57]
void ENTF90 (DEALLOC_MBR , dealloc_mbr)
Definition at line 1680 of file allo.c.
References __fort_allocated(), area, CADR, CLEN, ENTF90(), I8, and stat.
ENTF90() [30/57]
void ENTF90 (DEALLOC_MBR03 , dealloc_mbr03)
Definition at line 1701 of file allo.c.
References __CLEN_T, area, CADR, CLEN, ENTF90(), firsttime, and stat.
ENTF90() [31/57]
void ENTF90 (DEALLOC_MBR03A , dealloc_mbr03a)
Definition at line 1689 of file allo.c.
References __fort_allocated(), area, CADR, CLEN, ENTF90(), firsttime, I8, and stat.
ENTF90() [32/57]
void ENTF90 (DEALLOCA , dealloca)
f90 deallocate statement
Definition at line 1640 of file allo.c.
References __fort_dealloc(), __fort_free(), __fort_gfree(), area, CADR, I8, LOCAL_MODE, reuse_alloc(), stat, and void().
ENTF90() [33/57]
void ENTF90 (DEALLOCX , deallocx)
Definition at line 1710 of file allo.c.
References __fort_dealloc(), __fort_free(), __fort_gfree(), area, I8, LOCAL_MODE, stat, and void().
ENTF90() [34/57]
void ENTF90 (KALLOC , kalloc)
Definition at line 1041 of file allo.c.
References __fort_gmalloc_without_abort(), __fort_kalloc(), __fort_malloc_without_abort(), base, CADR, I8, ISPRESENT, kind, len, LOCAL_MODE, nelem, offset, pointer, save_alloc(), stat, use_alloc(), and void().
ENTF90() [35/57]
__LOG8_T ENTF90 (KALLOCATED , kallocated)
Definition at line 653 of file allo.c.
References __fort_allocated(), area, GET_DIST_TRUE_LOG, and I8.
ENTF90() [36/57]
__LOG8_T ENTF90 (KALLOCATED2 , kallocated2)
Definition at line 660 of file allo.c.
References __fort_allocated(), area, GET_DIST_TRUE_LOG, and I8.
ENTF90() [37/57]
__LOG8_T ENTF90 (KALLOCATED_LHS , kallocated_lhs)
Definition at line 667 of file allo.c.
References __fort_allocated(), area, GET_DIST_TRUE_LOG, and I8.
ENTF90() [38/57]
__LOG8_T ENTF90 (KALLOCATED_LHS2 , kallocated_lhs2)
Definition at line 674 of file allo.c.
References __fort_allocated(), area, GET_DIST_TRUE_LOG, and I8.
ENTF90() [39/57]
void ENTF90 (KCALLOC , kcalloc)
Definition at line 1128 of file allo.c.
References __fort_calloc_without_abort(), __fort_gcalloc_without_abort(), __fort_kalloc(), base, CADR, I8, kind, len, LOCAL_MODE, nelem, offset, pointer, stat, and void().
ENTF90() [40/57]
void ENTF90 (PTR_ALLOC , ptr_alloc)
Definition at line 1152 of file allo.c.
References __CLEN_T, base, CADR, CLEN, ENTF90(), kind, len, nelem, offset, pointer, and stat.
ENTF90() [41/57]
void ENTF90 (PTR_ALLOC03 , ptr_alloc03)
Definition at line 1179 of file allo.c.
References __CLEN_T, CADR, CLEN, ENTF90(), firsttime, kind, len, nelem, offset, pointer, and stat.
ENTF90() [42/57]
void ENTF90 (PTR_ALLOC03A , ptr_alloc03a)
F90 allocate statement – don't check allocated status.
Definition at line 1165 of file allo.c.
References __alloc04(), __fort_gmalloc_without_abort(), __fort_malloc_without_abort(), CADR, CLEN, firsttime, I8, ISPRESENT, kind, len, LOCAL_MODE, nelem, offset, pointer, stat, and void().
ENTF90() [43/57]
void ENTF90 (PTR_ALLOC04 , ptr_alloc04)
Definition at line 1205 of file allo.c.
References __CLEN_T, CADR, CLEN, ENTF90(), firsttime, kind, len, nelem, offset, pointer, and stat.
ENTF90() [44/57]
void ENTF90 (PTR_ALLOC04A , ptr_alloc04a)
Definition at line 1189 of file allo.c.
References __alloc04(), __fort_gmalloc_without_abort(), __fort_malloc_without_abort(), CADR, CLEN, firsttime, I8, ISPRESENT, kind, len, LOCAL_MODE, nelem, offset, pointer, stat, and void().
ENTF90() [45/57]
void ENTF90 (PTR_ALLOCA , ptr_alloca)
F90 allocate statement – don't check allocated status.
Definition at line 1141 of file allo.c.
References __fort_alloc(), __fort_gmalloc_without_abort(), __fort_malloc_without_abort(), base, CADR, I8, kind, len, LOCAL_MODE, nelem, offset, pointer, stat, and void().
ENTF90() [46/57]
void ENTF90 (PTR_CALLOC , ptr_calloc)
Definition at line 1408 of file allo.c.
References __fort_alloc(), __fort_calloc_without_abort(), __fort_gcalloc_without_abort(), base, CADR, I8, kind, len, LOCAL_MODE, nelem, offset, pointer, stat, and void().
ENTF90() [47/57]
void ENTF90 (PTR_CALLOC04 , ptr_calloc04)
Definition at line 1462 of file allo.c.
References __CLEN_T, CADR, CLEN, ENTF90(), firsttime, kind, len, nelem, offset, pointer, and stat.
ENTF90() [48/57]
void ENTF90 (PTR_CALLOC04A , ptr_calloc04a)
Definition at line 1445 of file allo.c.
References __alloc04(), __fort_calloc_without_abort(), __fort_gcalloc_without_abort(), CADR, CLEN, firsttime, I8, ISPRESENT, kind, len, LOCAL_MODE, nelem, offset, pointer, stat, and void().
ENTF90() [49/57]
void ENTF90 (PTR_KALLOC , ptr_kalloc)
64 bit F90 allocate statement – don't check allocated status
Definition at line 1397 of file allo.c.
References __fort_gmalloc_without_abort(), __fort_kalloc(), __fort_malloc_without_abort(), base, CADR, I8, kind, len, LOCAL_MODE, nelem, offset, pointer, stat, and void().
ENTF90() [50/57]
void ENTF90 (PTR_KCALLOC , ptr_kcalloc)
Definition at line 1476 of file allo.c.
References __fort_calloc_without_abort(), __fort_gcalloc_without_abort(), __fort_kalloc(), base, CADR, I8, kind, len, LOCAL_MODE, nelem, offset, pointer, stat, and void().
ENTF90() [51/57]
void ENTF90 (PTR_SRC_ALLOC03 , ptr_src_alloc03)
Definition at line 1253 of file allo.c.
References __CLEN_T, CADR, CLEN, ENTF90(), firsttime, kind, len, nelem, offset, pointer, and stat.
ENTF90() [52/57]
void ENTF90 (PTR_SRC_ALLOC03A , ptr_src_alloc03a)
Same as ptr_alloc03 above, except it's used with sourced allocation where the destination or source argument is polymorphic. So, we neeed to get the size from the source descriptor and allocate the source size if it's greater than the destination size passed in *len.
Definition at line 1225 of file allo.c.
References __alloc04(), __DESC, __fort_gmalloc_without_abort(), __fort_malloc_without_abort(), CADR, CLEN, ENTF90(), firsttime, I8, ISPRESENT, kind, len, LOCAL_MODE, F90_Desc::lsize, nelem, offset, pointer, stat, F90_Desc::tag, and void().
ENTF90() [53/57]
void ENTF90 (PTR_SRC_ALLOC04 , ptr_src_alloc04)
Definition at line 1333 of file allo.c.
References __CLEN_T, CADR, CLEN, ENTF90(), firsttime, kind, len, nelem, offset, pointer, and stat.
ENTF90() [54/57]
void ENTF90 (PTR_SRC_ALLOC04A , ptr_src_alloc04a)
Definition at line 1304 of file allo.c.
References __alloc04(), __DESC, __fort_gmalloc_without_abort(), __fort_malloc_without_abort(), CADR, CLEN, ENTF90(), firsttime, I8, ISPRESENT, kind, len, LOCAL_MODE, F90_Desc::lsize, nelem, offset, pointer, stat, F90_Desc::tag, and void().
ENTF90() [55/57]
void ENTF90 (PTR_SRC_CALLOC03 , ptr_src_calloc03)
Definition at line 1292 of file allo.c.
References __CLEN_T, CADR, CLEN, ENTF90(), firsttime, kind, len, nelem, offset, pointer, and stat.
ENTF90() [56/57]
void ENTF90 (PTR_SRC_CALLOC03A , ptr_src_calloc03a)
Definition at line 1265 of file allo.c.
References __alloc04(), __DESC, __fort_calloc_without_abort(), __fort_gcalloc_without_abort(), CADR, CLEN, ENTF90(), firsttime, I8, ISPRESENT, kind, len, LOCAL_MODE, F90_Desc::lsize, nelem, offset, pointer, stat, F90_Desc::tag, and void().
ENTF90() [57/57]
void ENTF90 (REALLOC_ARR_IN_IMPLIED_DO , realloc_arr_in_impiled_do)
Definition at line 938 of file allo.c.
References __fort_allocate(), __fort_bcopy(), __fort_deallocate(), __NELEM_T, F90_DIM_EXTENT_G, F90_GSIZE_G, F90_KIND_G, F90_LEN_G, F90_LSIZE_G, F90_RANK_G, i, I8, NULL, tmp, and void().
ENTFTN()
void ENTFTN (PTR_OFFSET , ptr_offset)
Compute pointer-sized index offset to replace Cray pointer. offset assumes 1-based arrays. DOES NOT WORK FOR CHARACTER DATA TYPE.
Definition at line 211 of file allo.c.
References __DERIVED, __fort_abort(), __STR, ABSENT, area, base, GET_DIST_SHIFTS, ISPRESENT, kind, and offset.
ENTRY()
void ENTRY (__FTN_ALLOC_DUMP , __ftn_alloc_dump)
Definition at line 1850 of file allo.c.
References ALLHDR, allo_list, GET_DIST_LCPU, n, next, NULL, num_hdrs, and p.
ftn_alloc()
char *I8() ftn_alloc (int size, __STAT_T * stat, char * area)
F77 allocate statement – check allocated status.
Definition at line 694 of file allo.c.
References __CHAR, __fort_alloc(), __fort_gmalloc_without_abort(), __fort_malloc_without_abort(), area, I8, LOCAL_MODE, NULL, size, and stat.
ftn_allocate()
char *I8() ftn_allocate (int size, __STAT_T * stat)
F77 allocate statement – don't check allocated status.
Definition at line 683 of file allo.c.
References __CHAR, __fort_alloc(), __fort_gmalloc_without_abort(), __fort_malloc_without_abort(), I8, LOCAL_MODE, NULL, size, and stat.
ftn_allocated()
__LOG_T I8() ftn_allocated (char * area)
Definition at line 622 of file allo.c.
References __fort_allocated(), area, GET_DIST_TRUE_LOG, and I8.
ftn_dealloc()
char *I8() ftn_dealloc (char * area, __STAT_T * stat)
Definition at line 1631 of file allo.c.
References __fort_dealloc(), __fort_free(), __fort_gfree(), area, I8, LOCAL_MODE, and stat.
ftn_deallocate()
void I8() ftn_deallocate (char * area, __STAT_T * stat)
F77 deallocate statement.
Definition at line 1625 of file allo.c.
References __fort_dealloc(), __fort_free(), __fort_gfree(), area, I8, LOCAL_MODE, stat, and void().
MP_SEMAPHORE() [1/2]
MP_SEMAPHORE (static , sem)
MP_SEMAPHORE() [2/2]
MP_SEMAPHORE (static , sem_allo)
reuse_alloc()
static void * reuse_alloc (__STAT_T * stat, char * area) static
Definition at line 814 of file allo.c.
References area, ISPRESENT, SAL::len, MP_P_ALLO, MP_V_ALLO, NULL, SAL::pointer, savedalloc, stat, and SAL::valid.
Referenced by ENTF90().
save_alloc()
static void save_alloc (__POINT_T nelem, __INT_T len, char ** pointer) static
Definition at line 756 of file allo.c.
References SAL::len, len, MP_P_ALLO, MP_V_ALLO, nelem, SAL::pointer, pointer, savedalloc, and SAL::valid.
Referenced by ENTF90().
use_alloc()
static void * use_alloc (__POINT_T nelem, __INT_T len) static
Definition at line 775 of file allo.c.
References __fort_dealloc(), __fort_free(), ENTCOMN, I8, SAL::len, len, MP_P_ALLO, MP_V_ALLO, nelem, NULL, SAL::pointer, pp, savedalloc, SAL::valid, and void().
Referenced by ENTF90().
void() [1/4]
void (__INT_T * nelem, __INT_T * kind, __INT_T * len, __STAT_T * stat, char ** pointer, __POINT_T * offset, __INT_T * firsttime, DCHAR(errmsg) DCLEN(errmsg))
Definition at line 1433 of file allo.c.
References __CLEN_T, CADR, CLEN, ENTF90(), firsttime, kind, len, nelem, offset, pointer, and stat.
void() [2/4]
void (__INT_T * nelem, __INT_T * kind, __INT_T * len, __STAT_T * stat, char ** pointer, __POINT_T * offset, __INT_T * firsttime, DCHAR(errmsg) DCLEN64(errmsg))
Definition at line 1417 of file allo.c.
References __alloc04(), __fort_calloc_without_abort(), __fort_gcalloc_without_abort(), CADR, CLEN, firsttime, I8, ISPRESENT, kind, len, LOCAL_MODE, nelem, offset, pointer, stat, and void().
void() [3/4]
void (F90_Desc * sd, __NELEM_T * nelem, __INT_T * kind, __INT_T * len, __STAT_T * stat, char ** pointer, __POINT_T * offset, __INT_T * firsttime, __NELEM_T * align, DCHAR(errmsg) DCLEN(errmsg))
Definition at line 1380 of file allo.c.
References __CLEN_T, CADR, CLEN, ENTF90(), firsttime, kind, len, nelem, offset, pointer, and stat.
void() [4/4]
void (F90_Desc * sd, __NELEM_T * nelem, __INT_T * kind, __INT_T * len, __STAT_T * stat, char ** pointer, __POINT_T * offset, __INT_T * firsttime, __NELEM_T * align, DCHAR(errmsg) DCLEN64(errmsg))
Definition at line 1346 of file allo.c.
References __alloc04(), __DESC, __fort_calloc_without_abort(), __fort_gcalloc_without_abort(), __NTYPES, CADR, CLEN, ENTF90(), firsttime, F90_Desc::gsize, I8, ISPRESENT, kind, F90_Desc::kind, len, F90_Desc::len, LOCAL_MODE, F90_Desc::lsize, nelem, offset, pointer, F90_Desc::rank, stat, F90_Desc::tag, and void().
Referenced by __abort_sig_hand(), __abort_sig_init(), __dump_loop(), __f90io_unf_read(), __f90io_unf_write(), __f90io_usw_read(), __f90io_usw_write(), __fort_deallocate(), __fort_heapinit(), __fort_local_deallocate(), __fortio_assign(), __fortio_default_convert(), __fortio_rwinit(), __INT_T(), __io_binary_mode(), __math_dispatch_error(), __math_dispatch_init(), __mth_i_anint(), __mth_i_dnint(), _constructf90(), _f90io_encode_fmt(), _f90io_ldw_intern_init(), _read_token(), a1tos1(), a4tos1(), accpp(), add_action(), add_assign_firstprivate(), add_assignment(), add_assignment_before(), add_loop_preheader(), add_pragma(), add_private_allocatable(), add_ptr_assignment(), add_taskloopreg(), addarth(), addlabel(), alloc_rbuf(), args_match(), asn_sfuse(), ast_clear_repl(), ast_intr(), bblock(), begin_parallel_clause(), bld_ud(), call_dtsfmt(), cast_to_typeless(), ch_substring(), check_etmp(), chk_arguments(), chk_block(), chk_expr(), chk_fmtid(), chk_unitid(), chk_var(), chkarg(), chkopnds(), cngshape(), cngtyp2(), collapse_add(), collapse_begin(), collapse_expr(), collapse_index(), copy_action(), dfs(), dinit_data(), dinit_subs(), dinit_varref(), dmp_rat(), do_copyin(), do_copyprivate(), do_dist_schedule(), do_distbegin(), do_end(), do_lastval(), do_map(), do_nml(), do_openmp_atomics(), do_private(), do_reduction(), do_schedule(), dtio_read_scalar(), dtio_write_scalar(), e113toe(), eadd1(), ediv(), emit_bcs_ecs(), emit_bpar(), emit_btarget(), emit_epar(), emit_etarget(), emul(), end_lastprivate(), end_parallel_clause(), end_reduction(), end_target(), end_teams(), ENT3F(), ENTF90(), ENTFTN(), etoasc(), eval_reshape(), evl_kwd_args(), exp_ac(), exp_alloca(), expand(), fill_ast(), find_base(), find_best_generic(), find_outer_sym(), fio_end_err(), flowgraph(), fpp(), fr_Breadnum(), fr_get_fmtcode(), fr_OZreadnum(), fr_read(), fr_readnum(), free_iterator(), ftn_deallocate(), Ftn_time(), func_call2(), fw_check_size(), fw_get_fmtcode(), fw_write(), fw_write_record(), gen_and_assoc_tmp_ptr(), gen_conditional_dealloc_for_sym(), gen_deallocate_arrays(), gen_derived_io(), gen_dtio_args(), gen_early_array_bnds(), gen_early_str_len(), gen_init_intrin_call(), gen_lastval(), gen_logical_if_expr(), gen_reduction(), gen_return_operand(), gen_spec_item_tmp(), get_junk(), get_kind_id(), get_num(), get_qstr(), get_sym_from_sst_if_available(), handle_dependence_ido(), i32tos(), induction(), init_sptr_w_acl(), inquire(), invar_mark(), iomsg_check(), kanji_prefix(), ll_reset_parfile(), ll_reset_parfile_(), llmp_concur_add_shared_var(), lv_print(), make_temp_descriptor(), misc_checks(), misc_io_checks(), mk_firstprivate(), mkarg(), mkexpr1(), mmul(), mod_init(), mp_create_bscope(), mp_create_escope(), new_asts(), precompute_arg_intrin(), precompute_args(), presence_test(), prng_loop_d_lf(), prng_loop_d_npb(), prng_loop_r_lf(), prng_loop_r_npb(), proc_sym(), process_forall(), process_input(), ptok(), ptrfunc_call(), ptrsubr_call(), put_buf(), rdline(), read_record(), ref_intrin(), ref_intrin_subr(), ref_pd(), ref_pd_subr(), ref_stfunc(), rw_array(), rw_dinit_state(), s1toa4(), save_clauses(), scan_def(), schedule(), semant1(), semant2(), semant3(), semant_reinit(), semantio(), semfin(), semsmp(), storedums(), subr_call2(), sum_scatter_args(), sym_get_sdescr(), tempify(), tempify_ast(), ufptod(), use_alloc(), void(), wrap_symbol(), write_item(), wtline(), and wtpage().
Variable Documentation
allo_list
ALLO_HDR* allo_list static
Definition at line 89 of file allo.c.
Referenced by ENTRY().
AUTO_ALN_MAXADJ
size_t AUTO_ALN_MAXADJ = 4096 static
Definition at line 1736 of file allo.c.
AUTO_ALN_MINSZ
size_t AUTO_ALN_MINSZ = 128000 static
Definition at line 1734 of file allo.c.
Referenced by __auto_alloc().
AUTO_ALN_UNIT
size_t AUTO_ALN_UNIT = 64 static
Definition at line 1735 of file allo.c.
Referenced by __auto_alloc().
num_hdrs
long num_hdrs = NUM_HDRS static
Definition at line 90 of file allo.c.
Referenced by ENTRY().
savedalloc
SAL savedalloc = {0, -99, (char *)0} static
Definition at line 728 of file allo.c.
Referenced by __f90_allo_term(), reuse_alloc(), save_alloc(), and use_alloc().