flang: arch.c File Reference
arch.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Macros
#define CPUIDX8664(a) __cpuid_##a
Functions
static int CPUIDX8664() is_avx512 ()
static int CPUIDX8664() is_avx512vl ()
static int CPUIDX8664() is_avx512f ()
static int CPUIDX8664() is_avx2 ()
static int CPUIDX8664() is_avx ()
static int CPUIDX8664() is_intel ()
static int CPUIDX8664() is_amd ()
static int CPUIDX8664() is_fma4 ()
static int CPUIDX8664() is_sse4a ()
static int CPUIDX8664() is_sse41 ()
const char * get_arch ()
Macro Definition Documentation
CPUIDX8664
#define CPUIDX8664 (a) __cpuid_##a
Definition at line 20 of file arch.c.
Function Documentation
get_arch()
const char * get_arch ()
Definition at line 36 of file arch.c.
References CPUIDX8664, is_amd(), is_avx(), is_avx2(), is_avx512f(), is_avx512vl(), is_fma4(), is_intel(), is_sse41(), is_sse4a(), and malloc().
is_amd()
static int CPUIDX8664() is_amd () static
Definition at line 234 of file x86id.c.
References DEBUG_PRINTF, h, CPU0::i, idcache(), signature_AMD_ebx, signature_AMD_ecx, signature_AMD_edx, and X86IDFN().
Referenced by get_arch(), get_cachesize(), is_aes(), is_amd_family(), is_athlon(), is_avx(), is_avx2(), is_bulldozer(), is_f16c(), is_fma(), is_fma4(), is_gh(), is_hammer(), is_k7(), is_sse(), is_sse2(), is_sse3(), is_sse42(), is_sse4a(), and is_ssse3().
is_avx()
static int CPUIDX8664() is_avx () static
Definition at line 410 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_amd(), is_intel(), is_xcr_set(), ICPU1::u, X86IDFN(), and xcr0_mask_YMM.
Referenced by get_arch(), init_hw_features(), is_avx2(), is_avx512(), and is_f16c().
is_avx2()
static int CPUIDX8664() is_avx2 () static
Definition at line 434 of file x86id.c.
References __pgi_cpuid_ecx(), DEBUG_PRINTF, ICPU7::ebx, ICPU7::i, is_amd(), is_avx(), is_intel(), ICPU7::u, and X86IDFN().
Referenced by get_arch(), and init_hw_features().
is_avx512()
static int CPUIDX8664() is_avx512 () static
Definition at line 458 of file x86id.c.
References is_avx(), is_intel(), is_xcr_set(), X86IDFN(), and xcr0_mask_ZMM.
Referenced by init_hw_features(), and is_avx512f().
is_avx512f()
static int CPUIDX8664() is_avx512f () static
Definition at line 473 of file x86id.c.
References __pgi_cpuid_ecx(), DEBUG_PRINTF, ICPU7::ebx, ICPU7::i, is_avx512(), ICPU7::u, and X86IDFN().
Referenced by get_arch(), init_hw_features(), and is_avx512vl().
is_avx512vl()
static int CPUIDX8664() is_avx512vl () static
Definition at line 490 of file x86id.c.
References __pgi_cpuid_ecx(), DEBUG_PRINTF, ICPU7::ebx, ICPU7::i, is_avx512f(), ICPU7::u, and X86IDFN().
Referenced by get_arch(), and init_hw_features().
is_fma4()
static int CPUIDX8664() is_fma4 () static
Definition at line 546 of file x86id.c.
References CPU80::b, ACPU81::ecx, CPU80::i, ACPU81::i, idcache(), is_amd(), CPU80::largest, ACPU81::u, and X86IDFN().
Referenced by get_arch(), and init_hw_features().
is_intel()
static int CPUIDX8664() is_intel () static
Definition at line 214 of file x86id.c.
References DEBUG_PRINTF, h, CPU0::i, idcache(), signature_INTEL_ebx, signature_INTEL_ecx, signature_INTEL_edx, and X86IDFN().
Referenced by get_arch(), get_cachesize(), is_aes(), is_avx(), is_avx2(), is_avx512(), is_f16c(), is_fma(), is_ht(), is_ia32e(), is_knl(), is_p4(), is_sse(), is_sse2(), is_sse3(), is_sse41(), is_sse42(), and is_ssse3().
is_sse41()
static int CPUIDX8664() is_sse41 () static
Definition at line 362 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_intel(), ICPU1::u, and X86IDFN().
Referenced by get_arch().
is_sse4a()
static int CPUIDX8664() is_sse4a () static
Definition at line 342 of file x86id.c.
References CPU80::b, ACPU81::ecx, CPU80::i, ACPU81::i, idcache(), is_amd(), CPU80::largest, ACPU81::u, and X86IDFN().
Referenced by get_arch().