flang: arg_parser.c File Reference
arg_parser.c File Reference
Argument parser implementation.
#include "flang/ADT/hash.h"
#include "flang/ArgParser/arg_parser.h"
#include "flang/ArgParser/xflag.h"
#include "flang/Error/pgerror.h"
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
Classes
struct arg_parser_
Internal representation of argument parser.
struct bool_string_
Link a bool * and a char ** value together.
struct action_map_bundle_
Combine input and output for action map arguments.
struct value_
Argument type and location.
Typedefs
typedef struct bool_string_ bool_string_t
Link a bool * and a char ** value together.
typedef struct action_map_bundle_ action_map_bundle_t
Combine input and output for action map arguments.
typedef enum value_type_ value_type_t
Argument value type.
typedef struct value_ value_t
Argument type and location.
Enumerations
enum value_type_ {
ARG_ActionMap , ARG_Boolean , ARG_CombinedBoolean , ARG_InformLevel ,
ARG_Integer , ARG_ReverseBoolean , ARG_String , ARG_StringList ,
ARG_QFlag , ARG_XFlag , ARG_YFlag
}
Argument value type.
Functions
static void add_generic_argument (arg_parser_t *parser, const char *arg_name, value_type_t value_type, void *value_ptr)
Add a generic argument, specifying argument type.
static void deallocate_arg_value (hash_key_t ignore, hash_data_t value_ptr, void *ignore_context)
static void compose_and_throw (const char *first_part, const char *second_part)
Compose and throw internal compiler error.
static char * next_value (char **argv, int *arg_index)
Point to next argument value.
static inform_level_t strtoinform (const char *string)
Convert a inform level string to corresponding constant.
void create_arg_parser (arg_parser_t **parser, bool fail_on_unknown_args)
Allocate and initialize argument parser data structure.
void destroy_arg_parser (arg_parser_t **parser)
Deallocate argument parser data structure.
void register_string_arg (arg_parser_t *parser, const char *arg_name, const char **target, const char *default_value)
Register a string argument.
void register_string_list_arg (arg_parser_t *parser, const char *arg_name, char **target)
Register a string list argument.
void register_integer_arg (arg_parser_t *parser, const char *arg_name, int *target, const int default_value)
Register an integer argument.
void register_boolean_arg (arg_parser_t *parser, const char *arg_name, bool *target, const bool default_value)
Register a boolean argument.
void register_combined_bool_string_arg (arg_parser_t *parser, const char *arg_name, bool *bool_target, const char **string_target)
Register a combines bool and string argument.
void register_qflag_arg (arg_parser_t *parser, const char *arg_name, int *qflags, const int qflags_size)
Register a "q flag" argument.
void register_xflag_arg (arg_parser_t *parser, const char *arg_name, int *xflags)
Register X version of "x flag" argument.
void register_yflag_arg (arg_parser_t *parser, const char *arg_name, int *xflags)
Register Y version of "x flag" argument.
void register_inform_level_arg (arg_parser_t *parser, const char *arg_name, inform_level_t *target, const inform_level_t default_value)
Register "inform level" argument that determines how verbose compiler output is.
void register_action_map_arg (arg_parser_t *parser, const char *arg_name, action_map_t *target, const action_map_t *input)
Regiser "action list" argument.
void register_filename_arg (arg_parser_t *parser, const char **target)
Register input file.
void parse_arguments (const arg_parser_t *parser, int argc, char **argv)
Parse arguments.
bool was_value_set (const arg_parser_t *parser, const void *location)
Check if a value was set during parse.
Detailed Description
Argument parser implementation.
Definition in file arg_parser.c.
Typedef Documentation
action_map_bundle_t
typedef struct action_map_bundle_ action_map_bundle_t
Combine input and output for action map arguments.
bool_string_t
typedef struct bool_string_ bool_string_t
Link a bool * and a char ** value together.
value_t
typedef struct value_ value_t
Argument type and location.
value_type_t
typedef enum value_type_ value_type_t
Argument value type.
Enumeration Type Documentation
value_type_
enum value_type_
Argument value type.
Enumerator
ARG_ActionMap
ARG_Boolean
ARG_CombinedBoolean
ARG_InformLevel
ARG_Integer
ARG_ReverseBoolean
ARG_String
ARG_StringList
ARG_QFlag
ARG_XFlag
ARG_YFlag
Definition at line 48 of file arg_parser.c.
Function Documentation
add_generic_argument()
static void add_generic_argument (arg_parser_t * parser, const char * arg_name, value_type_t value_type, void * value_ptr) static
Add a generic argument, specifying argument type.
Parameters
arg_parser Parser data structure
arg_name Argument name (key to flags table)
value_type Type of the value to store
value_ptr Location to store value to
Definition at line 272 of file arg_parser.c.
References ARG_ActionMap, compose_and_throw(), hashmap_insert(), hashmap_lookup(), hashset_replace(), malloc(), NULL, parser(), and value().
Referenced by register_action_map_arg(), register_boolean_arg(), register_combined_bool_string_arg(), register_inform_level_arg(), register_integer_arg(), register_qflag_arg(), register_string_arg(), register_string_list_arg(), register_xflag_arg(), and register_yflag_arg().
compose_and_throw()
static void compose_and_throw (const char * first_part, const char * second_part) static
Compose and throw internal compiler error.
Produces internal compiler error with the message composed by concatenating the two operands
Definition at line 490 of file arg_parser.c.
References ERR_Fatal, interr(), malloc(), msg(), and strlen().
Referenced by add_generic_argument(), parse_arguments(), strtoinform(), and was_value_set().
create_arg_parser()
void create_arg_parser (arg_parser_t ** parser, bool fail_on_unknown_args)
Allocate and initialize argument parser data structure.
Allocate argument parser hash map
Definition at line 80 of file arg_parser.c.
References hash_functions_direct, hash_functions_strings, hashmap_alloc(), hashset_alloc(), malloc(), NULL, and parser().
Referenced by init().
deallocate_arg_value()
static void deallocate_arg_value (hash_key_t key, hash_data_t value_ptr, void * key_context) static
Deallocate hashtable entry
Definition at line 107 of file arg_parser.c.
References ARG_ActionMap, ARG_CombinedBoolean, ARG_ReverseBoolean, k, and p.
Referenced by destroy_arg_parser().
destroy_arg_parser()
void destroy_arg_parser (arg_parser_t ** parser)
Deallocate argument parser data structure.
Deallocate argument parser hash map
Definition at line 92 of file arg_parser.c.
References deallocate_arg_value(), hashmap_free(), hashmap_iterate(), NULL, and parser().
Referenced by init().
next_value()
static char * next_value (char ** argv, int * arg_index) static
Point to next argument value.
If next argument in argument list does not start with a '-' return it and advance argument counter, otherwise return NULL and keep counter the same
Returns
pointer to the next non-switch command line argument
Parameters
argv command line argument array
arg_index current index into the argument array
Definition at line 508 of file arg_parser.c.
References NULL.
Referenced by parse_arguments().
parse_arguments()
void parse_arguments (const arg_parser_t * parser, int argc, char ** argv)
Parse arguments.
Parse all arguments
Definition at line 304 of file arg_parser.c.
References arg, ARG_ActionMap, ARG_Boolean, ARG_CombinedBoolean, ARG_InformLevel, ARG_Integer, ARG_QFlag, ARG_ReverseBoolean, ARG_String, ARG_StringList, ARG_XFlag, ARG_YFlag, compose_and_throw(), copy_action(), ERR_Fatal, hashmap_lookup(), hashset_clear(), hashset_replace(), interr(), next_value(), NULL, parser(), set_xflag_value(), strtoinform(), unset_xflag_value(), and value().
Referenced by init().
register_action_map_arg()
void register_action_map_arg (arg_parser_t * parser, const char * arg_name, action_map_t * target, const action_map_t * input)
Regiser "action list" argument.
Register "action list" argument
Definition at line 246 of file arg_parser.c.
References add_generic_argument(), ARG_ActionMap, malloc(), parser(), and value().
Referenced by init().
register_boolean_arg()
void register_boolean_arg (arg_parser_t * parser, const char * arg_name, bool * target, const bool default_value)
Register a boolean argument.
Register a boolean argument
Definition at line 168 of file arg_parser.c.
References add_generic_argument(), ARG_Boolean, ARG_ReverseBoolean, malloc(), parser(), and strlen().
Referenced by init().
register_combined_bool_string_arg()
void register_combined_bool_string_arg (arg_parser_t * parser, const char * arg_name, bool * bool_target, const char ** string_target)
Register a combines bool and string argument.
Register a combines bool and string argument
Definition at line 191 of file arg_parser.c.
References add_generic_argument(), ARG_CombinedBoolean, bool_string_::bool_ptr, malloc(), NULL, parser(), and bool_string_::string_ptr.
Referenced by init().
register_filename_arg()
void register_filename_arg (arg_parser_t * parser, const char ** target)
Register input file.
Register input file name
Definition at line 259 of file arg_parser.c.
References parser().
Referenced by init().
register_inform_level_arg()
void register_inform_level_arg (arg_parser_t * parser, const char * arg_name, inform_level_t * target, const inform_level_t default_value)
Register "inform level" argument that determines how verbose compiler output is.
Register verbosity argument
Definition at line 234 of file arg_parser.c.
References add_generic_argument(), ARG_InformLevel, and parser().
Referenced by init().
register_integer_arg()
void register_integer_arg (arg_parser_t * parser, const char * arg_name, int * target, const int default_value)
Register an integer argument.
Register an integer argument
Definition at line 157 of file arg_parser.c.
References add_generic_argument(), ARG_Integer, and parser().
Referenced by init().
register_qflag_arg()
void register_qflag_arg (arg_parser_t * parser, const char * arg_name, int * qflags, const int qflags_size)
Register a "q flag" argument.
Register "x" flag argument
Definition at line 209 of file arg_parser.c.
References add_generic_argument(), ARG_QFlag, and parser().
Referenced by init().
register_string_arg()
void register_string_arg (arg_parser_t * parser, const char * arg_name, const char ** target, const char * default_value)
Register a string argument.
Register a string argument
Definition at line 132 of file arg_parser.c.
References add_generic_argument(), ARG_String, and parser().
Referenced by init().
register_string_list_arg()
void register_string_list_arg (arg_parser_t * parser, const char * arg_name, char ** target)
Register a string list argument.
Register a string list argument
Definition at line 146 of file arg_parser.c.
References add_generic_argument(), ARG_StringList, NULL, and parser().
Referenced by init().
register_xflag_arg()
void register_xflag_arg (arg_parser_t * parser, const char * arg_name, int * xflags)
Register X version of "x flag" argument.
Register "x" flag argument
Definition at line 220 of file arg_parser.c.
References add_generic_argument(), ARG_XFlag, and parser().
Referenced by init().
register_yflag_arg()
void register_yflag_arg (arg_parser_t * parser, const char * arg_name, int * xflags)
Register Y version of "x flag" argument.
Register "y" flag argument
Definition at line 227 of file arg_parser.c.
References add_generic_argument(), ARG_YFlag, and parser().
Referenced by init().
strtoinform()
static inform_level_t strtoinform (const char * string) static
Convert a inform level string to corresponding constant.
Definition at line 520 of file arg_parser.c.
References compose_and_throw(), LV_Fatal, LV_Inform, LV_Severe, and LV_Warn.
Referenced by parse_arguments().
was_value_set()
bool was_value_set (const arg_parser_t * parser, const void * location)
Check if a value was set during parse.
Check if argument was found during parse
Definition at line 539 of file arg_parser.c.
References compose_and_throw(), hashset_lookup(), and parser().
Referenced by init().