flang: arg_parser.h File Reference
arg_parser.h File Reference
C header file for the argument parser.
#include "flang/ArgParser/debug_action.h"
#include <stdbool.h>
Typedefs
typedef enum inform_level_ inform_level_t
Inform (verbosity) level.
typedef struct arg_parser_ arg_parser_t
argument parser data structure
Enumerations
enum inform_level_ { LV_Inform = 1 , LV_Warn , LV_Severe , LV_Fatal }
Inform (verbosity) level.
Functions
void create_arg_parser (arg_parser_t **parser, bool fail_on_unknown_args)
Allocate and initialize argument parser data structure.
void destroy_arg_parser (arg_parser_t **parser)
Deallocate argument parser data structure.
void register_string_arg (arg_parser_t *parser, const char *arg_name, const char **target, const char *default_value)
Register a string argument.
void register_string_list_arg (arg_parser_t *parser, const char *arg_name, char **target)
Register a string list argument.
void register_combined_bool_string_arg (arg_parser_t *parser, const char *arg_name, bool *bool_target, const char **string_target)
Register a combines bool and string argument.
void register_integer_arg (arg_parser_t *parser, const char *arg_name, int *target, const int default_value)
Register an integer argument.
void register_boolean_arg (arg_parser_t *parser, const char *arg_name, bool *target, const bool default_value)
Register a boolean argument.
void register_qflag_arg (arg_parser_t *parser, const char *arg_name, int *qflags, const int qflags_size)
Register a "q flag" argument.
void register_xflag_arg (arg_parser_t *parser, const char *arg_name, int *xflags)
Register X version of "x flag" argument.
void register_yflag_arg (arg_parser_t *parser, const char *arg_name, int *xflags)
Register Y version of "x flag" argument.
void register_inform_level_arg (arg_parser_t *parser, const char *arg_name, inform_level_t *target, const inform_level_t default_value)
Register "inform level" argument that determines how verbose compiler output is.
void register_action_map_arg (arg_parser_t *parser, const char *arg_name, action_map_t *target, const action_map_t *input)
Regiser "action list" argument.
void register_filename_arg (arg_parser_t *parser, const char **target)
Register input file.
void parse_arguments (const arg_parser_t *parser, int argc, char **argv)
Parse arguments.
bool was_value_set (const arg_parser_t *parser, const void *location)
Check if a value was set during parse.
Detailed Description
C header file for the argument parser.
Rules of the game:
Argument parser exepects usual argc, argv pair; tries to handle all arguments
Swithches start with a '-'
First or last argument without a leading dash is considered the input file name (only one), everything else is treated as a switch followed by zero or more values
Definition in file arg_parser.h.
Typedef Documentation
arg_parser_t
typedef struct arg_parser_ arg_parser_t
argument parser data structure
Forward declared to limit access outside of this module
Definition at line 36 of file arg_parser.h.
inform_level_t
typedef enum inform_level_ inform_level_t
Inform (verbosity) level.
Enumeration Type Documentation
inform_level_
enum inform_level_
Inform (verbosity) level.
Enumerator
LV_Inform
LV_Warn
LV_Severe
LV_Fatal
Definition at line 25 of file arg_parser.h.
Function Documentation
create_arg_parser()
void create_arg_parser (arg_parser_t ** parser, bool fail_on_unknown_args)
Allocate and initialize argument parser data structure.
Parameters
parser Argument parser structure to initialize
fail_on_unknown_args Set to true to throw an error on unknown arguments, to false to silently continue parsing
Allocate argument parser hash map
Definition at line 80 of file arg_parser.c.
References hash_functions_direct, hash_functions_strings, hashmap_alloc(), hashset_alloc(), malloc(), NULL, and parser().
Referenced by init().
destroy_arg_parser()
void destroy_arg_parser (arg_parser_t ** parser)
Deallocate argument parser data structure.
Deallocate argument parser hash map
Definition at line 92 of file arg_parser.c.
References deallocate_arg_value(), hashmap_free(), hashmap_iterate(), NULL, and parser().
Referenced by init().
parse_arguments()
void parse_arguments (const arg_parser_t * parser, int argc, char ** argv)
Parse arguments.
Set values to the variable(s) that were registered with this parser
Parameters
parser The parser data structure
argc Standard argc parameter
argv Standard argv parameter
Parse all arguments
Definition at line 304 of file arg_parser.c.
References arg, ARG_ActionMap, ARG_Boolean, ARG_CombinedBoolean, ARG_InformLevel, ARG_Integer, ARG_QFlag, ARG_ReverseBoolean, ARG_String, ARG_StringList, ARG_XFlag, ARG_YFlag, compose_and_throw(), copy_action(), ERR_Fatal, hashmap_lookup(), hashset_clear(), hashset_replace(), interr(), next_value(), NULL, parser(), set_xflag_value(), strtoinform(), unset_xflag_value(), and value().
Referenced by init().
register_action_map_arg()
void register_action_map_arg (arg_parser_t * parser, const char * arg_name, action_map_t * target, const action_map_t * input)
Regiser "action list" argument.
Argument would take input action list and pull relevant parts of it into the target value as they are passed in as arguments. This argument type expects two values: '+' separated list of new action names followed by '+' separated list of original action names. The target list would contain the same actions but under the new keywords (if original keywords are found in the input action list).
Parameters
parser argument parser data structure
arg_name name of the argument (minus the '-')
target pointer to location to write argument value to
default_value value to intialize the target
Register "action list" argument
Definition at line 246 of file arg_parser.c.
References add_generic_argument(), ARG_ActionMap, malloc(), parser(), and value().
Referenced by init().
register_boolean_arg()
void register_boolean_arg (arg_parser_t * parser, const char * arg_name, bool * target, const bool default_value)
Register a boolean argument.
Boolean argument is actually two argument: <arg> and no<arg>. First one sets its target to true if it is present on command line, and the second one – to false.
Parameters
parser argument parser data structure
arg_name name of the argument (minus the '-')
target pointer to location to write argument value to
default_value value to intialize the target
Register a boolean argument
Definition at line 168 of file arg_parser.c.
References add_generic_argument(), ARG_Boolean, ARG_ReverseBoolean, malloc(), parser(), and strlen().
Referenced by init().
register_combined_bool_string_arg()
void register_combined_bool_string_arg (arg_parser_t * parser, const char * arg_name, bool * bool_target, const char ** string_target)
Register a combines bool and string argument.
The argument will set bool value to true if it is present and would also set the string target to the value that follows it. Boolean target is initialized to false and string target to NULL
Parameters
parser argument parser data structure
arg_name name of the argument (minus the '-')
bool_target pointer to write boolean value to
string_target pointer to string buffer to write string value to
Register a combines bool and string argument
Definition at line 191 of file arg_parser.c.
References add_generic_argument(), ARG_CombinedBoolean, bool_string_::bool_ptr, malloc(), NULL, parser(), and bool_string_::string_ptr.
Referenced by init().
register_filename_arg()
void register_filename_arg (arg_parser_t * parser, const char ** target)
Register input file.
This argument does not have a default value, parser would live target unchanged if it does not detect input file name.
Parameters
parser argument parser data structure
target location to set the result (pointer to the string)
Register input file name
Definition at line 259 of file arg_parser.c.
References parser().
Referenced by init().
register_inform_level_arg()
void register_inform_level_arg (arg_parser_t * parser, const char * arg_name, inform_level_t * target, const inform_level_t default_value)
Register "inform level" argument that determines how verbose compiler output is.
Parameter would mactch sting input to information level and store it as an integer constant. Recognized values and their integer codes are (minus quotes):
"inform" 1 (LV_Inform)
"warn" 2 (LV_Warn)
"severe" 3 (LV_Severe)
"fatal" 4 (LV_Fatal)
Parameters
parser argument parser data structure
arg_name name of the argument (minus the '-')
target pointer to location to write argument value to
default_value value to intialize the target
Register verbosity argument
Definition at line 234 of file arg_parser.c.
References add_generic_argument(), ARG_InformLevel, and parser().
Referenced by init().
register_integer_arg()
void register_integer_arg (arg_parser_t * parser, const char * arg_name, int * target, const int default_value)
Register an integer argument.
Prepare to set an integer value for an arugument. Value will be written to a location pointed by "target" argument.
Parameters
parser argument parser data structure
arg_name name of the argument (minus the '-')
target pointer to location to write argument value to
default_value value to intialize the target
Register an integer argument
Definition at line 157 of file arg_parser.c.
References add_generic_argument(), ARG_Integer, and parser().
Referenced by init().
register_qflag_arg()
void register_qflag_arg (arg_parser_t * parser, const char * arg_name, int * qflags, const int qflags_size)
Register a "q flag" argument.
"q" command line switch sets a mask in debug features array that is consumed by other parts of compiler. This function also fills the array with zeros.
Parameters
parser argument parser data structure
arg_name name of the argument (minus the '-')
qflags pointer to the beginning of q flags array
qflags_size number of elelemts in qflags array
Register "x" flag argument
Definition at line 209 of file arg_parser.c.
References add_generic_argument(), ARG_QFlag, and parser().
Referenced by init().
register_string_arg()
void register_string_arg (arg_parser_t * parser, const char * arg_name, const char ** target, const char * default_value)
Register a string argument.
Prepare to set a string value for an arugument. Do not perform any allocation, value from argv array will just be pointed to.
Parameters
parser argument parser data structure
arg_name name of the argument (minus the '-')
target pointer to string buffer to write argument value to
default_value value to intialize the target
Register a string argument
Definition at line 132 of file arg_parser.c.
References add_generic_argument(), ARG_String, and parser().
Referenced by init().
register_string_list_arg()
void register_string_list_arg (arg_parser_t * parser, const char * arg_name, char ** target)
Register a string list argument.
Add a "string list argument", that would produce a null terminated list of string pointers. Values are taken from argument pointers, but space for them needs to be allocated and freed by the consumer (argc can be a fair guess of the number of array elements to allocate).
XXX If there would be many arguments of this type, then we would need to dynamically allocate the array (otherwise it would be too vasteful for the consumer to do that).
Parameters
parser argument parser data structure
arg_name name of the argument (minus the '-')
target pointer to start of the string buffer array
Register a string list argument
Definition at line 146 of file arg_parser.c.
References add_generic_argument(), ARG_StringList, NULL, and parser().
Referenced by init().
register_xflag_arg()
void register_xflag_arg (arg_parser_t * parser, const char * arg_name, int * xflags)
Register X version of "x flag" argument.
"x" command line switch sets a mask in x flags (features) array that is consumed by other parts of compiler.
Parameters
parser argument parser data structure
arg_name name of the argument (minus the '-')
xflags pointer to x flags
Register "x" flag argument
Definition at line 220 of file arg_parser.c.
References add_generic_argument(), ARG_XFlag, and parser().
Referenced by init().
register_yflag_arg()
void register_yflag_arg (arg_parser_t * parser, const char * arg_name, int * xflags)
Register Y version of "x flag" argument.
"y" command line switch clears a mask in features array, complementing what "x" flag does.
Parameters
parser argument parser data structure
arg_name name of the argument (minus the '-')
xflags pointer to x flags
xflags_size number of elelemts in xflags array
Register "y" flag argument
Definition at line 227 of file arg_parser.c.
References add_generic_argument(), ARG_YFlag, and parser().
Referenced by init().
was_value_set()
bool was_value_set (const arg_parser_t * parser, const void * location)
Check if a value was set during parse.
Parameters
parser argument parser data structure
location pointer to argument's value (needs to match "register" call)
Returns
true if value was set, false otherwise
Check if argument was found during parse
Definition at line 539 of file arg_parser.c.
References compose_and_throw(), hashset_lookup(), and parser().
Referenced by init().