flang: around.c File Reference
around.c File Reference
#include "mthdecls.h"
Functions
float roundf (float)
float __mth_i_around (float x)
Function Documentation
__mth_i_around()
float __mth_i_around (float x)
Definition at line 13 of file around.c.
References roundf(), and x.
Referenced by __nearbyintf().
roundf()
float roundf (float)
Referenced by __mth_i_around().