flang: asm_anno.h File Reference
asm_anno.h File Reference
Interface to annotation module.
Functions
void anno_blkcnt (int blkno)
...
void annomod_asm (int blkno)
should be called before emitting assembly code for each basic block
void annomod_end (void)
should be called after all code is emitted for the current user function, but before assem_end_func() is called.
void annomod_init (void)
should be called at the beginning of processing for each user function (but not before merge_blocks() is called).
Detailed Description
Interface to annotation module.
Define interface to Annotation module: which supports assembly file annotation (-Manno switch).
Annotation is supported by the following functions - generally called from the Scheduler/Code Generator module, iff "flg.anno" is true.
Definition in file asm_anno.h.
Function Documentation
anno_blkcnt()
void anno_blkcnt (int blkno)
...
Definition at line 343 of file asm_anno.cpp.
References BIH_BLKCNT, comment_char, and gbl.
annomod_asm()
void annomod_asm (int blkno)
should be called before emitting assembly code for each basic block
should be called before emitting assembly code for each basic block
Just seek to file position indicated and output from there to next file position or eof.
Definition at line 357 of file asm_anno.cpp.
References amod, FLG::anno, BIH_LINENO, ANNO_S::bihd, emit_str(), ERR_Informational, ERR_Warning, fanno, ANNO_S::fileloc, flg, get_anno_line(), interr(), lanno, lineno, ANNO_S::lineno, modcnt, ANNO_S::next, NULL, p, and put_anno_line().
annomod_end()
void annomod_end (void)
should be called after all code is emitted for the current user function, but before assem_end_func() is called.
should be called after all code is emitted for the current user function, but before assem_end_func() is called.
Just seek to the current file position.
Definition at line 427 of file asm_anno.cpp.
References amod, assert, ERR_Warning, fanno, lanno, modcnt, and NULL.
annomod_init()
void annomod_init (void)
should be called at the beginning of processing for each user function (but not before merge_blocks() is called).
Definition at line 65 of file asm_anno.cpp.
References ahead, amod, annomod_initx(), modcnt, and NULL.