flang: asm_anno.cpp File Reference
asm_anno.cpp File Reference
Module to support assembly file annotation (-Manno switch).
#include "gbldefs.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "ili.h"
#include "asm_anno.h"
#include "fih.h"
Classes
struct ANNO_S
Assembly block annotation.
Macros
#define ALEN 256
#define SOURCE_FILE gbl.file_name
#define BLEN 80
Typedefs
typedef struct ANNO_S ANNO
Assembly block annotation.
Functions
void annomod_init (void)
should be called at the beginning of processing for each user function (but not before merge_blocks() is called).
static ANNO * annomod_initx (ANNO *ahead)
Initiate annotation of the assembly file.
static int qs_anno (const void *p1, const void *p2)
Quicksort comparison routine for annotations.
void annomod_asm (int blkno)
Annotate assembly file.
void anno_blkcnt (int blkno)
...
void annomod_end (void)
Finish annotate assembly file for this module.
static char * get_anno_line (FILE *fptr)
Get a line from the file.
static void put_anno_line (char *p)
Output an annotated line.
static int find_idx (ANNO *, int, int, int)
static void emit_str (const char *p, int lptr)
Emit the string to the output file.
static void dmp_all_anno (ANNO *, FILE *, int)
static void dmp_anno (ANNO *, FILE *)
Variables
char * comment_char
struct {
FILE * fp
FILE * fname
int curlin
INT curpos
char buf [ALEN+4]
} lanno
static FILE * fanno = NULL
static ANNO * amod = NULL
static ANNO * ahead = NULL
static int modcnt = -1
Detailed Description
Module to support assembly file annotation (-Manno switch).
Definition in file asm_anno.cpp.
Macro Definition Documentation
ALEN
#define ALEN 256
Definition at line 47 of file asm_anno.cpp.
BLEN
#define BLEN 80
SOURCE_FILE
#define SOURCE_FILE gbl.file_name
Definition at line 62 of file asm_anno.cpp.
Typedef Documentation
ANNO
typedef struct ANNO_S ANNO
Assembly block annotation.
Function Documentation
anno_blkcnt()
void anno_blkcnt (int blkno)
...
Definition at line 343 of file asm_anno.cpp.
References BIH_BLKCNT, comment_char, and gbl.
annomod_asm()
void annomod_asm (int blkno)
Annotate assembly file.
should be called before emitting assembly code for each basic block
Just seek to file position indicated and output from there to next file position or eof.
Definition at line 357 of file asm_anno.cpp.
References amod, FLG::anno, BIH_LINENO, ANNO_S::bihd, emit_str(), ERR_Informational, ERR_Warning, fanno, ANNO_S::fileloc, flg, get_anno_line(), interr(), lanno, lineno, ANNO_S::lineno, modcnt, ANNO_S::next, NULL, p, and put_anno_line().
annomod_end()
void annomod_end (void)
Finish annotate assembly file for this module.
should be called after all code is emitted for the current user function, but before assem_end_func() is called.
Just seek to the current file position.
Definition at line 427 of file asm_anno.cpp.
References amod, assert, ERR_Warning, fanno, lanno, modcnt, and NULL.
annomod_init()
void annomod_init (void)
should be called at the beginning of processing for each user function (but not before merge_blocks() is called).
Definition at line 65 of file asm_anno.cpp.
References ahead, amod, annomod_initx(), modcnt, and NULL.
annomod_initx()
static ANNO * annomod_initx (ANNO * ahead) static
Initiate annotation of the assembly file.
This is called before code is generated. Augment the current annotation chain with a sorted list of the new linenumber records (ANNO) for this module.
Parameters
ahead head of annotation list
Returns
new head of annotation list
Definition at line 83 of file asm_anno.cpp.
References ahead, FLG::anno, assert, BIH_FINDEX, BIH_LINENO, BIH_NEXT, ANNO_S::bihd, BZERO, cnt, CNULL, DBGBIT, dmp_all_anno(), ERR_Informational, ERR_Severe, ERR_Warning, error(), fanno, ANNO_S::fd, FIH_INC, FIH_INL, FIH_LINENO, FIH_PARENT, file_pos, ANNO_S::fileloc, ANNO_S::filename, find_idx(), flg, FREE, gbl, get_anno_line(), i, idx, interr(), j, lanno, ANNO_S::lineno, modcnt, ANNO_S::module, NEW, ANNO_S::next, NULL, p, qs_anno(), SOURCE_FILE, and ANNO_S::tmp.
Referenced by annomod_init().
dmp_all_anno()
static void dmp_all_anno (ANNO * panno, FILE * fp, int flag) static
Definition at line 539 of file asm_anno.cpp.
References cnt, dmp_anno(), fflush(), fp, msg(), and p.
Referenced by annomod_initx().
dmp_anno()
static void dmp_anno (ANNO * panno, FILE * fp) static
Definition at line 569 of file asm_anno.cpp.
References ANNO_S::bihd, fflush(), ANNO_S::fileloc, fp, ANNO_S::lineno, ANNO_S::module, ANNO_S::next, and ANNO_S::tmp.
Referenced by dmp_all_anno().
emit_str()
static void emit_str (const char * p, int lptr) static
Emit the string to the output file.
Parameters
p is the string to output
lptr is the label sptr used for delay br filling.
Definition at line 521 of file asm_anno.cpp.
References assert, ERR_Informational, gbl, NULL, p, and XBIT.
Referenced by annomod_asm(), and put_anno_line().
find_idx()
static int find_idx (ANNO * p, int cnt, int idx, int last_idx) static
Definition at line 494 of file asm_anno.cpp.
References cnt, i, idx, p, and tmp.
Referenced by annomod_initx().
get_anno_line()
static char * get_anno_line (FILE * fptr) static
Get a line from the file.
Parameters
fptr file pointer
Returns
ptr to static file buffer if enough room or return NULL if problem encountered.
Definition at line 449 of file asm_anno.cpp.
References ALEN, BLEN, lanno, p, and strlen().
Referenced by annomod_asm(), and annomod_initx().
put_anno_line()
static void put_anno_line (char * p) static
Output an annotated line.
Parameters
p assembly buffer to print
Definition at line 484 of file asm_anno.cpp.
References comment_char, emit_str(), and p.
Referenced by annomod_asm().
qs_anno()
static int qs_anno (const void * p1, const void * p2) static
Quicksort comparison routine for annotations.
Compares source file line numbers that the blocks correspond to.
Parameters
p1 first block
p2 second block
Note: parameters are void* because that is required by qsort.
Definition at line 326 of file asm_anno.cpp.
References lineno.
Referenced by annomod_initx().
Variable Documentation
ahead
ANNO* ahead = NULL static
Definition at line 58 of file asm_anno.cpp.
Referenced by annomod_init(), and annomod_initx().
amod
ANNO* amod = NULL static
Definition at line 57 of file asm_anno.cpp.
Referenced by annomod_asm(), annomod_end(), and annomod_init().
buf
char buf[ALEN+4]
Definition at line 53 of file asm_anno.cpp.
comment_char
char * comment_char extern
Definition at line 145 of file assem.h.
Referenced by anno_blkcnt(), and put_anno_line().
curlin
int curlin
Definition at line 51 of file asm_anno.cpp.
curpos
INT curpos
Definition at line 52 of file asm_anno.cpp.
Referenced by pp_entries(), and pp_entries_mixedstrlen().
fanno
FILE* fanno = NULL static
Definition at line 56 of file asm_anno.cpp.
Referenced by annomod_asm(), annomod_end(), and annomod_initx().
fname
FILE* fname
Definition at line 50 of file asm_anno.cpp.
fp
FILE* fp
Definition at line 49 of file asm_anno.cpp.
Referenced by __fortio_zeropad(), __io_binary_mode(), __io_getfd(), __io_setmode_binary(), _f90io_backspace(), _nextline(), dmp_all_anno(), dmp_anno(), dump_loop_args(), dump_parsyms(), dumpUplevel(), ENT3F(), ENTF90(), finish(), Fio_asy_open(), fr_get_val(), fr_read_record(), fw_get_val(), gen_bindC_retval(), gen_funcret(), import_module_print(), ioerrinfo(), ll_set_outlined_currsub(), llmp_task_add_private(), print_back_trace_line(), ptok(), rdline(), wtline(), and wtpage().
struct { ... } lanno
Referenced by annomod_asm(), annomod_end(), annomod_initx(), and get_anno_line().
modcnt
int modcnt = -1 static
Definition at line 59 of file asm_anno.cpp.
Referenced by annomod_asm(), annomod_end(), annomod_init(), and annomod_initx().