flang: assem.h File Reference
assem.h File Reference
Assembler module.
Macros
#define STR_SEC 0
#define RO_SEC 1
#define DATA_SEC 2
#define TEXT_SEC 3
#define INIT_SEC 4
#define DRECTVE_SEC 5
#define PDATA_SEC 6
#define XDATA_SEC 7
#define TRACE_SEC 8
#define BSS_SEC 9
#define GXX_EH_SEC 10
#define LNK_T_SEC 11
#define LNK_D_SEC 12
#define LNK_R_SEC 13
#define RO_DATA_WEAK_SEC 14
#define DATA_WEAK_SEC 15
#define BSS_WEAK_SEC 16
#define RO_DATA_SEC 17
#define NVIDIA_FATBIN_SEC 18
#define NVIDIA_MODULEID_SEC 19
#define NVIDIA_RELFATBIN_SEC 20
#define NVIDIA_OLDFATBIN_SEC 21
#define GNU_NAMED_SEC 22
#define OMP_OFFLOAD_SEC 23
#define HAS_TLS_SECTIONS 1
#define TDATA_SEC 23
#define TBSS_SEC 24
#define TDATA_WEAK_SEC 25
#define TBSS_WEAK_SEC 26
#define DATA_SECG(sptr) (IS_TLS(sptr) ? TDATA_SEC : DATA_SEC)
#define BSS_SECG(sptr) (IS_TLS(sptr) ? TBSS_SEC : BSS_SEC)
#define ULABPFX ".L"
#define EMIT_INSTR_EXT(op, ext, op1, op2) emit_instr(#op #ext, op1, op2)
#define EMIT_VZEROUPPER
#define ASM_VZEROUPPER
Functions
char * getsname (SPTR)
char * getsname2 (int)
void sym_is_refd (SPTR)
void assem_init (void)
Initialize assem for a function.
void assem_begin_func (int func_sptr)
void assem_pc (int func_sptr, int arg1_offset, int base_reg)
void assem_mxcsr (int func_sptr)
void assem_user_entry (int label_sptr, int lineno, int firstline)
void assem_emit_line (int findex, int lineno)
void assem_emit_file_line (int findex, int lineno)
void assem_end_func (int func_sptr)
void assem_data (void)
void assem_end (void)
void prof_rouent (int func_sptr)
void prof_linent (int lineno, int loop_flag, int blocknum)
void prof_rouret (void)
int get_private_size (void)
void add_init_routine (char *initroutine)
Add initilizer routine 'initroutine' to the llvm global ctor array.
void create_static_base (int name)
void emit_instr (const char *, const char *, const char *)
void emit_label (char *)
char * hex (int num, int pad)
char * imm (int num)
char * imm_isz (ISZ_T)
char * imm_hex (int num, int pad)
char * mem (char *r)
char * sib (char *base, char *idx, int ss)
void create_static_name (char *name, int usestatic, int num)
Variables
char * comment_char
char * immed_char
char * labpfx
Detailed Description
Assembler module.
Define those functions and data items which are defined in the assembler module, assem.c, and exported to other modules of the compiler. (X86 and Hammer targets)
Definition in file assem.h.
Macro Definition Documentation
ASM_VZEROUPPER
#define ASM_VZEROUPPER
Value:
  {                                                                 \
    if (!XBIT(164, 0x100000) &&                                     \
        (XBIT(164, 0x2000000) || !TEST_FEATURE(FEATURE_SIMD128)) && \
        mach.feature[FEATURE_AVX])                                  \
      fprintf(ASMFIL, "\tvzeroupper\n");                            \
  }
Definition at line 192 of file assem.h.
BSS_SEC
#define BSS_SEC 9
Definition at line 96 of file assem.h.
BSS_SECG
#define BSS_SECG (sptr) (IS_TLS(sptr) ? TBSS_SEC : BSS_SEC)
Definition at line 129 of file assem.h.
BSS_WEAK_SEC
#define BSS_WEAK_SEC 16
Definition at line 111 of file assem.h.
DATA_SEC
#define DATA_SEC 2
Definition at line 89 of file assem.h.
DATA_SECG
#define DATA_SECG (sptr) (IS_TLS(sptr) ? TDATA_SEC : DATA_SEC)
Definition at line 128 of file assem.h.
DATA_WEAK_SEC
#define DATA_WEAK_SEC 15
Definition at line 110 of file assem.h.
DRECTVE_SEC
#define DRECTVE_SEC 5
Definition at line 92 of file assem.h.
EMIT_INSTR_EXT
#define EMIT_INSTR_EXT (op, ext, op1, op2) emit_instr(#op #ext, op1, op2)
Definition at line 149 of file assem.h.
EMIT_VZEROUPPER
#define EMIT_VZEROUPPER
Value:
  {                                                                 \
    if (!XBIT(164, 0x100000) &&                                     \
        (XBIT(164, 0x2000000) || !TEST_FEATURE(FEATURE_SIMD128)) && \
        mach.feature[FEATURE_AVX])                                  \
      emit_instr("vzeroupper", NULL, NULL);                         \
  }
Definition at line 184 of file assem.h.
GNU_NAMED_SEC
#define GNU_NAMED_SEC 22
Definition at line 117 of file assem.h.
GXX_EH_SEC
#define GXX_EH_SEC 10
Definition at line 97 of file assem.h.
HAS_TLS_SECTIONS
#define HAS_TLS_SECTIONS 1
Definition at line 120 of file assem.h.
INIT_SEC
#define INIT_SEC 4
Definition at line 91 of file assem.h.
LNK_D_SEC
#define LNK_D_SEC 12
Definition at line 103 of file assem.h.
LNK_R_SEC
#define LNK_R_SEC 13
Definition at line 105 of file assem.h.
LNK_T_SEC
#define LNK_T_SEC 11
Definition at line 101 of file assem.h.
NVIDIA_FATBIN_SEC
#define NVIDIA_FATBIN_SEC 18
Definition at line 113 of file assem.h.
NVIDIA_MODULEID_SEC
#define NVIDIA_MODULEID_SEC 19
Definition at line 114 of file assem.h.
NVIDIA_OLDFATBIN_SEC
#define NVIDIA_OLDFATBIN_SEC 21
Definition at line 116 of file assem.h.
NVIDIA_RELFATBIN_SEC
#define NVIDIA_RELFATBIN_SEC 20
Definition at line 115 of file assem.h.
OMP_OFFLOAD_SEC
#define OMP_OFFLOAD_SEC 23
Definition at line 118 of file assem.h.
PDATA_SEC
#define PDATA_SEC 6
Definition at line 93 of file assem.h.
RO_DATA_SEC
#define RO_DATA_SEC 17
Definition at line 112 of file assem.h.
RO_DATA_WEAK_SEC
#define RO_DATA_WEAK_SEC 14
Definition at line 108 of file assem.h.
RO_SEC
#define RO_SEC 1
Definition at line 88 of file assem.h.
STR_SEC
#define STR_SEC 0
Definition at line 87 of file assem.h.
TBSS_SEC
#define TBSS_SEC 24
Definition at line 125 of file assem.h.
TBSS_WEAK_SEC
#define TBSS_WEAK_SEC 26
Definition at line 127 of file assem.h.
TDATA_SEC
#define TDATA_SEC 23
Definition at line 124 of file assem.h.
TDATA_WEAK_SEC
#define TDATA_WEAK_SEC 25
Definition at line 126 of file assem.h.
TEXT_SEC
#define TEXT_SEC 3
Definition at line 90 of file assem.h.
TRACE_SEC
#define TRACE_SEC 8
Definition at line 95 of file assem.h.
ULABPFX
#define ULABPFX ".L"
Definition at line 140 of file assem.h.
XDATA_SEC
#define XDATA_SEC 7
Definition at line 94 of file assem.h.
Function Documentation
add_init_routine()
void add_init_routine (char * initroutine)
Add initilizer routine 'initroutine' to the llvm global ctor array.
Definition at line 1081 of file llassem_common.cpp.
References llvm_ctor_add().
assem_begin_func()
void assem_begin_func (int func_sptr)
assem_data()
void assem_data (void)
Definition at line 972 of file llassem.cpp.
References assem_init(), dinits(), write_bss(), write_comm(), write_consts(), write_extern_inits(), write_externs(), write_statics(), and write_typedescs().
Referenced by schedule().
assem_emit_file_line()
void assem_emit_file_line (int findex, int lineno)
Definition at line 4440 of file llassem.cpp.
assem_emit_line()
void assem_emit_line (int findex, int lineno)
Definition at line 4435 of file llassem.cpp.
assem_end()
void assem_end (void)
Definition at line 1002 of file llassem.cpp.
References ag_local, agb_local, bss_aln_n, bss_base, bss_name_global, bss_name_initialized, dinit_end(), fptr_local, FREE, freearea(), has_init, AGB_t::n_avl, fptr_local_t::n_avl, AGB_t::n_base, fptr_local_t::n_base, AGB_t::n_size, fptr_local_t::n_size, NULL, ptr_local, reset_equiv_var(), reset_master_sptr(), AGB_t::s_avl, fptr_local_t::s_avl, AGB_t::s_base, fptr_local_t::s_base, AGB_t::s_size, fptr_local_t::s_size, SPTR_NULL, static_base, static_name_global, static_name_initialized, and stk_aln_n.
Referenced by cg_llvm_fnend(), and schedule().
assem_end_func()
void assem_end_func (int func_sptr)
assem_init()
void assem_init (void)
Initialize assem for a function.
Called once per function. This init is called immediately before any processing is performed for a function.
Definition at line 858 of file llassem.cpp.
References add_ag_name(), AG_HASHSZ, ag_local, AG_SIZE, AG_TYPENMPTR, agb_local, bss_base, bss_name, bss_name_global, bss_name_initialized, BZERO, contained_bss_name, contained_static_name, DSRTG, fptr_local, gbl, generate_struct_dtype(), get_llvm_name(), get_struct_from_dsrt(), has_init, AGB_t::hashtb, fptr_local_t::hashtb, AGB_t::n_avl, fptr_local_t::n_avl, AGB_t::n_base, fptr_local_t::n_base, AGB_t::n_size, fptr_local_t::n_size, NEW, NOSYM, NULL, outer_bss_name, outer_static_name, ptr_local, AGB_t::s_avl, fptr_local_t::s_avl, AGB_t::s_base, fptr_local_t::s_base, AGB_t::s_size, fptr_local_t::s_size, sptr, SPTR_NULL, static_base, static_name, static_name_global, and static_name_initialized.
Referenced by cg_llvm_init().
assem_mxcsr()
void assem_mxcsr (int func_sptr)
assem_pc()
void assem_pc (int func_sptr, int arg1_offset, int base_reg)
assem_user_entry()
void assem_user_entry (int label_sptr, int lineno, int firstline)
create_static_base()
void create_static_base (int name)
Definition at line 1563 of file lowersym.c.
create_static_name()
void create_static_name (char * name, int usestatic, int num)
Definition at line 4678 of file llassem.cpp.
References name, and num.
emit_instr()
void emit_instr (const char * , const char * , const char *)
emit_label()
void emit_label (char *)
get_private_size()
int get_private_size (void)
Definition at line 4553 of file llassem.cpp.
References gbl, getsymbol(), and name.
getsname()
char * getsname (SPTR sptr)
Definition at line 3589 of file llassem.cpp.
References AG_NAME, bss_base, bss_name, bss_name_global, CUDAG, FLG::dollar, DTY, ERR_Severe, extent_of(), FLANG_FALLTHROUGH, flg, gbl, get_altname(), getfuncname(), getsname(), global_sptr, interr(), m, MXIDLN, name, outer_bss_name, outer_static_name, p, q, RU_PROG, FLG::smp, sptr, static_base, static_name, static_name_global, SYMNAME, ULABPFX, upcase_name(), and XBIT.
getsname2()
char * getsname2 (int)
hex()
char * hex (int num, int pad)
Referenced by puthex().
imm()
char * imm (int num)
Referenced by vfixup_vd_vd_vd_vi2_i(), and vfixup_vf_vf_vf_vi2_i().
imm_hex()
char * imm_hex (int num, int pad)
imm_isz()
char * imm_isz (ISZ_T)
mem()
char * mem (char * r)
Referenced by _do_iface(), add_dt_subscr(), add_member_for_llvm(), add_to_common(), addToDtype(), all_default_init(), all_len_parms_assumed(), allocate_aligned(), ast_rewrite(), build_final_table(), check_defined_io2(), check_derived_type_array_section(), check_kind_type_param(), chk_arguments(), chk_asz_deferlen(), chk_initialization_with_kind_parm(), chk_new_param_dt(), completeTbp(), create_parameterized_dt(), defer_iface(), export_dtypes(), fill_links_symbol(), find_best_generic(), find_member_base(), find_operator(), find_parent_member(), fix_iface(), fix_iface0(), fix_mem_bounds(), fix_mem_bounds2(), fix_type_param_members(), func_call2(), gen_allocate(), gen_deallocate(), gen_kind_parm_assignments(), generic_tbp_has_pass_and_nopass(), get_all_descriptors(), get_defined_io_call(), get_generic_member(), get_generic_member2(), get_generic_tbp_pass_or_nopass(), get_highest_param_offset(), get_implementation(), get_kind_parm(), get_kind_parm_by_name(), get_kind_parm_strict(), get_kind_set_parm(), get_len_parm(), get_len_parm_by_number(), get_len_set_parm(), get_len_set_parm_by_name(), get_mem_sptr_by_name(), get_parameterized_dt(), get_parm_ast(), get_parm_by_name(), get_parm_by_number(), get_specific_member(), get_tbp_argno(), get_unl_poly_sym(), handle_allocatable_members(), has_final_procedures(), has_length_type_parameter_use(), has_pending_final_procedures(), has_poly_mbr(), hash_mem(), initFinalSub(), is_empty_typedef(), is_intrinsic_opr(), ll_get_uplevel_offset(), ll_make_kmpc_struct_type(), ll_manage_mem(), load_uplevel_addresses(), lower_symbol(), lower_symbols(), make_secd_for_members(), match_memname(), mk_charlen_address(), mk_mem_ptr_shape(), mk_member(), new_member_expr(), no_data_components_recursive(), pad_cmn_mem(), proc_arginfo(), propagatemodified(), put_default_kind_type_param(), put_kind_type_param(), put_length_type_param(), queue_type_param(), resolveGeneric(), semant2(), semant3(), semCheckTbp(), smallest_dtype(), subr_call2(), sym_get_sdescr(), trav_struct(), and wrap_symbol().
prof_linent()
void prof_linent (int lineno, int loop_flag, int blocknum)
prof_rouent()
void prof_rouent (int func_sptr)
prof_rouret()
void prof_rouret (void)
sib()
char * sib (char * base, char * idx, int ss)
sym_is_refd()
void sym_is_refd (SPTR sptr)
Definition at line 3925 of file llassem.cpp.
Variable Documentation
comment_char
char* comment_char extern
Definition at line 145 of file assem.h.
immed_char
char* immed_char extern
labpfx
char* labpfx extern