flang: assem.c File Reference
assem.c File Reference
PGFTN/N10 "assembler" module.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "dtypeutl.h"
#include "machar.h"
#include "version.h"
#include "fih.h"
Macros
#define DT_QUADALIGN 15
#define ALN_MINSZ 128000
#define ALN_UNIT 64
#define ALN_MAXADJ 4096
#define ALN_THRESH (ALN_MAXADJ / ALN_UNIT)
Functions
void assemble (void)
...
void assemble_init (void)
void assemble_end (void)
...
void sym_is_refd (int sptr)
void fix_equiv_locals (int loc_list, ISZ_T loc_addr)
The equivalence processor assigns positive offsets to the local variables which appear in equivalence statements. Target addresses must be assigned using the offsets provided by the equivalence processor.
void fix_equiv_statics (int loc_list, ISZ_T loc_addr, LOGICAL dinitflg)
Similiar to fix_equiv_locals except that these local variables were saved and/or dinit'd. for these variables, switch the storage class to SC_STATIC.
ISZ_T get_bss_addr (void)
...
ISZ_T set_bss_addr (ISZ_T addr)
ISZ_T pad_cmn_mem (int mem, ISZ_T msz, int *p_aln_n)
Variables
static ISZ_T bss_addr
Detailed Description
PGFTN/N10 "assembler" module.
Definition in file assem.c.
Macro Definition Documentation
ALN_MAXADJ
#define ALN_MAXADJ 4096
Definition at line 318 of file assem.c.
ALN_MINSZ
#define ALN_MINSZ 128000
Definition at line 316 of file assem.c.
ALN_THRESH
#define ALN_THRESH (ALN_MAXADJ / ALN_UNIT)
Definition at line 319 of file assem.c.
ALN_UNIT
#define ALN_UNIT 64
Definition at line 317 of file assem.c.
DT_QUADALIGN
#define DT_QUADALIGN 15
Definition at line 24 of file assem.c.
Function Documentation
assemble()
void assemble (void)
...
Definition at line 27 of file assem.c.
Referenced by process_input().
assemble_end()
void assemble_end (void)
...
Definition at line 37 of file assem.c.
Referenced by fini(), and finish().
assemble_init()
void assemble_init (void)
Definition at line 32 of file assem.c.
Referenced by init().
fix_equiv_locals()
void fix_equiv_locals (int loc_list, ISZ_T loc_addr)
The equivalence processor assigns positive offsets to the local variables which appear in equivalence statements. Target addresses must be assigned using the offsets provided by the equivalence processor.
Parameters
loc_list list of local symbols linked by SYMLK
loc_addr total size of the equivalenced locals
Definition at line 213 of file assem.c.
References ALIGN, alignment(), DT_DBLE, DT_QUADALIGN, flg, gbl, NOSYM, and FLG::quad.
Referenced by do_equiv().
fix_equiv_statics()
void fix_equiv_statics (int loc_list, ISZ_T loc_addr, LOGICAL dinitflg)
Similiar to fix_equiv_locals except that these local variables were saved and/or dinit'd. for these variables, switch the storage class to SC_STATIC.
Parameters
loc_list list of local symbols linked by SYMLK
loc_addr total size of the equivalenced locals
dinitflg variables were dinit'd
The equivalence processor assigns positive offsets to the local variables which appear in equivalence statements. Target addresses must be assigned using the offsets provided by the equivalence processor.
Definition at line 255 of file assem.c.
References addr, ALIGN, alignment(), assert, bss_addr, DT_DBLE, DT_QUADALIGN, flg, gbl, ISZ_T, NOSYM, and FLG::quad.
Referenced by do_equiv().
get_bss_addr()
ISZ_T get_bss_addr (void)
...
Definition at line 304 of file assem.c.
References bss_addr.
Referenced by lower_sym_header(), parser(), and stb_lower_sym_header().
pad_cmn_mem()
ISZ_T pad_cmn_mem (int mem, ISZ_T msz, int * p_aln_n)
Definition at line 322 of file assem.c.
References ALN_MINSZ, ALN_THRESH, ALN_UNIT, mem(), msz, PDALN_IS_DEFAULT, and XBIT.
Referenced by add_to_common(), do_common_blocks(), and set_common_size().
set_bss_addr()
ISZ_T set_bss_addr (ISZ_T addr)
Definition at line 310 of file assem.c.
References addr, and bss_addr.
Referenced by datastructure_reinit(), and parser().
sym_is_refd()
void sym_is_refd (int sptr)
Definition at line 42 of file assem.c.
References a, addr, ALIGN, ALIGN_AUTO, alignment(), assert, bss_addr, DBGBIT, DT_PTR, DT_QUADALIGN, flg, gbl, getprint(), interr(), ISZ_PF, ISZ_T, no_data_components(), FLG::quad, FLG::recursive, size, size_of(), sptr, and sym_is_refd().
Referenced by AssignAddresses(), ch_substring(), cp_byval_mem_arg(), create_llvm_display_temp(), create_ref(), dinit_constructor(), dinit_name(), do_nml(), do_save(), exp_header(), fix_symbol(), gen_acon_expr(), genload(), get_entries_argnum(), get_param_alias_var(), get_static_type_descriptor(), ll_get_gtid_addr_ili(), ll_get_gtid_val_ili(), ll_load_outlined_args(), llCollectSymbolInfo(), llvmAddConcurEntryBlk(), loadUplevelArgsForRegion(), lower_init_sym(), make_new_funcsptr(), mk_kmpc_api_call(), mkfunc(), nml_sym_is_refd(), process_extern_function_sptr(), process_label_sptr(), process_local_sptr(), process_private_sptr(), process_sptr_offset(), process_static_sptr(), put_data(), put_name(), read_init(), reloc_byvalue_parameters(), semant1(), semant3(), semantio(), and sym_is_refd().
Variable Documentation
bss_addr
ISZ_T bss_addr static
Definition at line 22 of file assem.c.
Referenced by fix_equiv_statics(), get_bss_addr(), lower_sym_header(), set_bss_addr(), stb_lower_sym_header(), and sym_is_refd().