flang: assign.c File Reference
assign.c File Reference
#include "global.h"
#include <string.h>
Macros
#define PP_INT1(i) (*(__INT1_T *)(i))
#define PP_INT2(i) (*(__INT2_T *)(i))
#define PP_INT4(i) (*(__INT4_T *)(i))
#define PP_INT8(i) (*(__INT8_T *)(i))
#define PP_LOG1(i) (*(__LOG1_T *)(i))
#define PP_LOG2(i) (*(__LOG2_T *)(i))
#define PP_LOG4(i) (*(__LOG4_T *)(i))
#define PP_LOG8(i) (*(__LOG8_T *)(i))
#define PP_REAL4(i) (*(__REAL4_T *)(i))
#define PP_REAL8(i) (*(__REAL8_T *)(i))
#define PP_REAL16(i) (*(__REAL16_T *)(i))
Functions
static __BIGINT_T to_bigint (AVAL *)
static __BIGREAL_T to_bigreal (AVAL *)
static __INT8_T to_int8 (AVAL *)
static __LOG8_T to_log8 (AVAL *)
int __fortio_assign (char *item, int type, __CLEN_T item_length, AVAL *valp)
__fortio_assign - store a value found during list-directed or namelist read. return 0 if successful, otherwise an error code (typically, a conversion error).
Detailed Description
RunTime routines to handle namelist and list directed reads
Definition in file assign.c.
Macro Definition Documentation
PP_INT1
#define PP_INT1 (i) (*(__INT1_T *)(i))
Definition at line 15 of file assign.c.
PP_INT2
#define PP_INT2 (i) (*(__INT2_T *)(i))
Definition at line 16 of file assign.c.
PP_INT4
#define PP_INT4 (i) (*(__INT4_T *)(i))
Definition at line 17 of file assign.c.
PP_INT8
#define PP_INT8 (i) (*(__INT8_T *)(i))
Definition at line 18 of file assign.c.
PP_LOG1
#define PP_LOG1 (i) (*(__LOG1_T *)(i))
Definition at line 19 of file assign.c.
PP_LOG2
#define PP_LOG2 (i) (*(__LOG2_T *)(i))
Definition at line 20 of file assign.c.
PP_LOG4
#define PP_LOG4 (i) (*(__LOG4_T *)(i))
Definition at line 21 of file assign.c.
PP_LOG8
#define PP_LOG8 (i) (*(__LOG8_T *)(i))
Definition at line 22 of file assign.c.
PP_REAL16
#define PP_REAL16 (i) (*(__REAL16_T *)(i))
Definition at line 25 of file assign.c.
PP_REAL4
#define PP_REAL4 (i) (*(__REAL4_T *)(i))
Definition at line 23 of file assign.c.
PP_REAL8
#define PP_REAL8 (i) (*(__REAL8_T *)(i))
Definition at line 24 of file assign.c.
Function Documentation
__fortio_assign()
int __fortio_assign (char * item, int type, __CLEN_T item_length, AVAL * valp)
__fortio_assign - store a value found during list-directed or namelist read. return 0 if successful, otherwise an error code (typically, a conversion error).
Definition at line 39 of file assign.c.
References __BIGCPLX, __BIGINT, __BIGLOG, __BIGREAL, __CLEN_T, __CPLX16, __CPLX32, __CPLX8, __ftn_32in64_, __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __NCHAR, __REAL16, __REAL4, __REAL8, __STR, __WORD16, assert, atag::c, atag::cmplx, atag::dtype, FIO_EERR_DATA_CONVERSION, FIO_EQUAD, FLANG_FALLTHROUGH, atag::i, I64_LSH, I64_MSH, atag::i8, len, atag::len, lp, PP_INT1, PP_INT2, PP_INT4, PP_INT8, PP_LOG1, PP_LOG2, PP_LOG4, PP_LOG8, PP_REAL16, PP_REAL4, PP_REAL8, atag::str, to_bigint(), to_bigreal(), to_int8(), to_log8(), type, atag::val, and void().
Referenced by __f90io_ldr(), and assign().
to_bigint()
static __BIGINT_T to_bigint (AVAL * valp) static
Definition at line 268 of file assign.c.
References __BIGINT, __BIGLOG, __BIGREAL, assert, atag::d, atag::dtype, atag::i, and atag::val.
Referenced by __fortio_assign().
to_bigreal()
static __BIGREAL_T to_bigreal (AVAL * valp) static
Definition at line 277 of file assign.c.
References __BIGINT, __BIGLOG, __BIGREAL, __INT8, __LOG8, assert, atag::d, atag::dtype, atag::i, atag::i8v, and atag::val.
Referenced by __fortio_assign().
to_int8()
static __INT8_T to_int8 (AVAL * valp) static
Definition at line 289 of file assign.c.
References __BIGREAL, __INT4, __LOG4, atag::d, atag::dtype, atag::i, I64_LSH, I64_MSH, atag::i8, atag::i8v, and atag::val.
Referenced by __fortio_assign().
to_log8()
static __LOG8_T to_log8 (AVAL * valp) static
Definition at line 304 of file assign.c.
References __INT4, __LOG4, atag::dtype, atag::i, I64_LSH, I64_MSH, atag::ui8, atag::ui8v, and atag::val.
Referenced by __fortio_assign().