flang: ast.c File Reference
ast.c File Reference
Abstract syntax tree access module.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "scan.h"
#include "machar.h"
#include "state.h"
#include "ast.h"
#include "pragma.h"
#include "rte.h"
#include "extern.h"
#include "rtlRtns.h"
#include "semant.h"
#include <stdarg.h>
Macros
#define HUGE_NUM2 0xffffffff
#define HUGE_NUM3 0xffffffff
#define BYTE_NUMBER16 16
#define MIN_INT64(n) (((n[0] & 0xffffffff) == 0x80000000) && ((n[1] & 0xffffffff) == 0))
#define MKU(a, s, d)
#define ADD_NODE(nd, a, hashval)
#define HSH_2(a, o1, o2) hash_val(a, o1, o2, -1, -1)
#define HSH_3(a, o1, o2, o3) hash_val(a, o1, o2, o3, -1)
#define HSH_4(a, o1, o2, o3, o4) hash_val(a, o1, o2, o3, o4)
#define _PFG(cond, str)
#define C90_HUGE "0.136343516952426e+2466" /* 0577757777777777777776 */
#define KANJI_BLANK 0xA1A1
#define MASKH32(sptr) (CONVAL1G(sptr) & 0xFFFFFFFF)
Functions
static int reduce_iadd (int, INT)
static int reduce_i8add (int, int)
static int convert_cnst (int, int)
static SPTR sym_of_ast2 (int)
static LOGICAL bounds_match (int, int, int)
static INT _fdiv (INT, INT)
static void _ddiv (INT *, INT *, INT *)
static int hex2char (INT *hexval)
Convert doubleword hex/octal value to a character.
static int hex2nchar (INT *)
static void truncation_warning (int)
static void conversion_warning (void)
void ast_init (void)
Initialize AST table for new user program unit.
void ast_fini (void)
int new_node (int type)
static INT hash_val (int a, int hw3, int hw4, int hw5, int hw6)
static int hash_sym (int a, DTYPE dtype, int sptr)
static int hash_unop (int a, DTYPE dtype, int lop, int optype)
static int hash_binop (int a, DTYPE dtype, int lop, int optype, int rop)
static int hash_paren (int a, DTYPE dtype, int lop)
static int hash_conv (int a, DTYPE dtype, int lop, int shd)
static int hash_subscr (int a, DTYPE dtype, int lop, int asd)
static int hash_mem (int a, DTYPE dtype, int parent, int mem)
static int hash_cmplxc (int a, DTYPE dtype, int lop, int rop)
static int hash_triple (int a, int lb, int ub, int stride)
static int hash_substr (int a, DTYPE dtype, int lop, int left, int right)
int mk_id (int id)
int mk_id_noshape (int id)
int mk_init (int left, DTYPE dtype)
int mk_atomic (int stmt_type, int left, int right, DTYPE dtype)
int mk_cnst (int cnst)
Make a constant AST given a constant symbol table pointer.
int mk_cval (INT v, DTYPE dtype)
int mk_isz_cval (ISZ_T v, DTYPE dtype)
int mk_fake_iostat ()
int mk_cval1 (INT v, DTYPE dtype)
Make a constant AST given the actual (single word) value or a constant symbol table pointer; determined by data type.
void mk_alias (int ast, int a_cnst)
Create an alias of ast if it isn't a constant AST. Its alias field will be set to the ast 'a_cnst'.
int mk_label (int lab)
int mk_binop (int optype, int lop, int rop, DTYPE dtype)
int mk_unop (int optype, int lop, DTYPE dtype)
...
int mk_cmplxc (int lop, int rop, DTYPE dtype)
int mk_paren (int lop, DTYPE dtype)
int mk_convert (int lop, DTYPE dtype)
int convert_int (int ast, DTYPE dtype)
int mk_promote_scalar (int lop, DTYPE dtype, int shd)
int mk_subscr (int arr, int *subs, int numdim, DTYPE dtype)
int mk_subscr_copy (int arr, int asd, DTYPE dtype)
int mk_asd (int *subs, int numdim)
int mk_triple (int lb, int ub, int stride)
int mk_substr (int chr, int left, int right, DTYPE dtype)
int complex_alias (int ast)
For an AST tree with members and subscripts, if the base variable has the PARAMG bit set and all the subscripts are known constants, we can perhaps find the value the AST and set the A_ALIAS flag.
int mk_member (int parent, int mem, DTYPE dtype)
int mkshape (DTYPE dtype)
Make shape ilm(s) from an array descriptor. Return the pointer to the the shape descriptor (SHD).
int mk_mem_ptr_shape (int parent, int mem, DTYPE dtype)
Make shape ast(s) for an array reference off of a pointer in a derived type. Return the shape descriptor (SHD). Main difference is that the descriptor references need to be derived type components.
int mk_shape (void)
int mk_offset (int astx, int resdtype)
Make an ast tree that computes the offset of the derived type or array element reference 'ast' from the start of the variable being referenced.
int reduc_shape (int o_shape, int astdim, int after)
Duplicate a shape descriptor excluding a given dimension.
int increase_shape (int o_shape, int astdim, int ub, int after)
Duplicate a shape descriptor increasing its rank at the given dimension.
void add_shape_rank (int ndim)
void add_shape_spec (int lwb, int upb, int stride)
LOGICAL conform_shape (int shape1, int shape2)
Check conformance of shape descriptors.
int extent_of_shape (int shape, int dim)
Create an ast representing the extent of a dimension.
int lbound_of_shape (int shape, int dim)
Get the lower bound of a shape descriptor.
int ubound_of_shape (int shape, int dim)
Get the upper bound of a shape descriptor.
int rank_of_ast (int ast)
int mk_zbase_expr (ADSC *ad)
Return the ast which computes the zero-base offset for an array.
int mk_mlpyr_expr (int lb, int ub, int mlpyr)
Return an ast that computes the multiplier from the multiplier, lower bound, and upper bound of the previous dimension.
int mk_extent_expr (int lb, int ub)
Return an ast that computes the extent (from the lb and ub).
int mk_extent (int lb, int ub, int dim)
Return an ast to reference the extent.
int mk_shared_extent (int lb, int ub, int dim)
LOGICAL ast_is_sym (int ast)
int sym_of_ast (int ast)
Like memsym_of_ast(), but for a member, returns the sptr of its parent, not the member.
int pass_sym_of_ast (int ast)
Like sym_of_ast(), except for members it will return second to last parent member.
int memsym_of_ast (int ast)
Like sym_of_ast(), but for a member, returns the sptr of the member itself, not its parent.
void put_memsym_of_ast (int ast, int sptr)
Replace sptr of ast, if member, replace the sptr of the member.
int replace_memsym_of_ast (int ast, SPTR sptr)
Generate a replacement AST with a new sptr for certain AST types.
int procsym_of_ast (int ast)
Like memsym_of_ast(), but for looking for the sptr of a procedure reference.
LOGICAL pure_func_call (int func_ast)
LOGICAL elemental_func_call (int func_ast)
int sptr_of_subscript (int ast)
Return sptr of an A_SUBSCR.
int left_array_symbol (int ast)
Return the leftmost array symbol.
int left_subscript_ast (int ast)
Return the AST of the leftmost A_SUBSCR:
int left_nonscalar_subscript_ast (int ast)
This routine is similar to left_subscript_ast except it returns the leftmost non-scalar subscript.
int dist_ast (int ast)
Return the AST of the leftmost A_SUBSCR or A_ID that is distributed or aligned.
static LOGICAL stride1_triple (int triple)
static LOGICAL contiguous_array_section (int subscr_ast)
LOGICAL is_whole_dim (int arr_ast, int i)
Determine if array arr_ast covers all extent at dim i.
LOGICAL is_whole_array (int arr_ast)
LOGICAL simply_contiguous (int arr_ast)
LOGICAL bnds_remap_list (int subscr_ast)
int replace_ast_subtree (int original, int subtree, int replacement)
In original replace subtree with replacement.
int elem_size_of_ast (int ast)
Given an ast, return an ast with the element size.
int size_of_ast (int ast)
int mk_bnd_ast (void)
int mk_shared_bnd_ast (int ast)
Create a shared bounds temporary.
int mk_stmt (int stmt_type, DTYPE dtype)
int mk_std (int ast)
int add_stmt (int ast)
static void set_par (int std)
int add_stmt_after (int ast, int stmt)
int add_stmt_before (int ast, int stmt)
void insert_stmt_after (int std, int stdafter)
void insert_stmt_before (int std, int stdbefore)
void remove_stmt (int std)
void move_range_before (int sstd, int estd, int stdbefore)
void move_range_after (int sstd, int estd, int stdafter)
void move_stmts_before (int std, int stdbefore)
void move_stmts_after (int std, int stdafter)
void ast_to_comment (int ast)
int mk_comstr (char *str)
int mk_argt (int cnt)
Create an ARGT.
void unmk_argt (int cnt)
void start_astli (void)
Initialize for a new ast list.
int add_astli (void)
Create and return an AST list item, adding it to the end of the current list.
static void reset_astli (void)
void ast_implicit (int firstc, int lastc, DTYPE dtype)
int begin_call (int ast_type, int func, int count)
void add_arg (int arg)
Add an argument.
void finish_args (DTYPE dtype, LOGICAL promote)
For an elemental intrinsic or function AST created by begin_call() and one or more calls to add_arg, fill in the result dtype and shape of the AST.
int mk_func_node (int ast_type, int func_ast, int paramct, int argt)
int mk_assn_stmt (int dest, int source, DTYPE dtype)
static LOGICAL _contains_ast (int astTarg, LOGICAL *pflag)
LOGICAL contains_ast (int astTarg, int astSrc)
Return TRUE if astSrc occurs somewhere within astTarg.
void ast_visit (int old, int new)
Add an AST to the visit list.
void ast_replace (int old, int new)
The old AST is to be replaced by the new AST.
void ast_unvisit (void)
Traverse the visit list to clean up the nodes in the list.
void ast_unvisit_norepl (void)
void ast_revisit (ast_visit_fn proc, int *extra_arg)
Visit the nodes on the 'visit_list' again, call proc on each one.
int ast_rewrite (int ast)
void ast_clear_repl (int ast)
Only called by the semantic analyzer; if it needs to be used by all phases, many ASTs need to be added as cases.
static void _ast_trav (int ast, int *extra_arg)
void ast_traverse (int ast, ast_preorder_fn preorder, ast_visit_fn postorder, int *extra_arg)
General ast traversal function: uses a list to keep track of the ast nodes which have been visited; if a node is visited, the node's REPL field is non-zero.
void ast_traverse_all (int ast, ast_preorder_fn preorder, ast_visit_fn postorder, int *extra_arg)
Recursively visit the ast operands of ast; useful if the caller needs check the 'result' (via extra_arg) of the visit function.
void ast_traverse_more (int ast, int *extra_arg)
While in an ast_traverse recursion, continue on another subtree.
void ast_trav_recurse (int ast, int *extra_arg)
void _dump_shape (int shd, FILE *file)
void dump_shape (int shd)
void _dump_one_ast (int i, FILE *file)
void dump_one_ast (int i)
void dump_ast_tree (int i)
void dump_ast (void)
void dump_astli (int astli)
void _dump_std (int std, FILE *fil)
void dump_std (void)
void dump_stg_stat (const char *where)
static int _huge (DTYPE)
int ast_intr (int i_intr, DTYPE dtype, int cnt,...)
static int mk_int (int expr, DTYPE dt_needed)
int mk_default_int (int expr)
Utility function to ensure that an expression has type DT_INT (default integer).
int mk_bnd_int (int expr)
Utility function to ensure that an expression has a type suitable for array bounds, DT_INT8 for -Mlarge_arrays, DT_INT otherwise.
int mk_smallest_val (DTYPE dtype)
...
int mk_largest_val (DTYPE dtype)
...
int mk_merge (int tsource, int fsource, int mask, DTYPE resdt)
void rw_ast_state (RW_ROUTINE, RW_FILE)
void delete_stmt (int std)
int add_nullify_ast (int sptrast)
int has_assumshp_expr (int ast)
Looks for an assumed shape expression in an AST.
int has_adjustable_expr (int ast)
Looks for an adjustable array expression in an AST.
int has_pointer_expr (int ast)
Looks for a pointer expression in an AST.
int has_allocatable_expr (int ast)
Looks for an allocatable expression in an AST.
int is_iso_cloc (int ast)
Check if the derived type tag is the iso_c_binding: c_ptr or c_funptr. These types are compatible with pointers.
int is_iso_c_loc (int ast)
Check if this AST is an intrinsic call to c_loc.
int is_iso_c_funloc (int ast)
Check if this AST is an intrinsic call to c_funloc.
int find_pointer_variable (int ast)
Find the symbol table entry of pointer variable from an ast representing a pointer object.
void find_pointer_target (int ast, int *pbase, int *psym)
Find the symbol table entry of the target from an ast representing the target in a pointer assignment.
void holtonum (char *cp, INT *num, int bc)
Convert a hollerith constant to a numeric value.
INT negate_const (INT conval, DTYPE dtype)
INT const_fold (int opr, INT conval1, INT conval2, DTYPE dtype)
INT cngcon (INT oldval, int oldtyp, int newtyp)
Convert constant from oldtyp to newtyp.
int resolve_ast_alias (int ast)
LOGICAL is_array_ast (int ast)
LOGICAL has_vector_subscript_ast (int ast)
LOGICAL is_data_ast (int ast)
LOGICAL is_variable_ast (int ast)
int get_ast_asd (int ast)
DTYPE get_ast_dtype (int ast)
int get_ast_rank (int ast)
int get_ast_sptr (int ast)
int rewrite_ast_with_new_dtype (int ast, DTYPE dtype)
int mk_duplicate_ast (int ast)
int get_ast_extents (int extent_asts[], int from_ast, DTYPE arr_dtype)
int get_ast_bounds (int lower_bound_asts[], int upper_bound_asts[], int from_ast, DTYPE arr_dtype)
int add_extent_subscripts (int to_ast, int rank, const int extent_asts[], DTYPE elt_dtype)
int add_bounds_subscripts (int to_ast, int rank, const int lower_bound_asts[], const int upper_bound_asts[], DTYPE elt_dtype)
int add_shapely_subscripts (int to_ast, int from_ast, DTYPE arr_dtype, DTYPE elt_dtype)
Variables
static int atemps
struct {
short ndim
short next
struct {
int lwb
int upb
int stride
} spec [MAXRANK]
} _shd
static int tail_astli
struct {
int argt
int ast
int arg_num
int ast_type
int arg_count
} curr_call = {0, 0, 0, 0, 0}
static int astMatch
static int visit_list = 0
static ast_visit_fn _visited
int rewrite_opfields = 0
static LOGICAL ast_visit_state = FALSE
static LOGICAL ast_check_visited = TRUE
static ast_preorder_fn _preorder
static ast_visit_fn _postorder
static int indent = 0
Detailed Description
Abstract syntax tree access module.
This module contains the routines used to initialize, update, access, and dump the abstract syntax tree.
q flags:
    -q  4  256   dump asts
    -q  4  512   include hash table of asts
Definition in file ast.c.
Macro Definition Documentation
_PFG
#define _PFG (cond, str)
Value:
  if (cond)             \
  fprintf(fil, " %s", str)
ADD_NODE
#define ADD_NODE (nd, a, hashval)
Value:
  (nd) = new_node(a);                  \
  A_HSHLKP((nd), astb.hshtb[hashval]); \
  astb.hshtb[hashval] = (nd)
Definition at line 281 of file ast.c.
BYTE_NUMBER16
#define BYTE_NUMBER16 16
Definition at line 39 of file ast.c.
C90_HUGE
#define C90_HUGE "0.136343516952426e+2466" /* 0577757777777777777776 */
HSH_2
#define HSH_2 (a, o1, o2) hash_val(a, o1, o2, -1, -1)
Definition at line 290 of file ast.c.
HSH_3
#define HSH_3 (a, o1, o2, o3) hash_val(a, o1, o2, o3, -1)
Definition at line 291 of file ast.c.
HSH_4
#define HSH_4 (a, o1, o2, o3, o4) hash_val(a, o1, o2, o3, o4)
Definition at line 292 of file ast.c.
HUGE_NUM2
#define HUGE_NUM2 0xffffffff
Definition at line 37 of file ast.c.
HUGE_NUM3
#define HUGE_NUM3 0xffffffff
Definition at line 38 of file ast.c.
KANJI_BLANK
#define KANJI_BLANK 0xA1A1
MASKH32
#define MASKH32 (sptr) (CONVAL1G(sptr) & 0xFFFFFFFF)
MIN_INT64
#define MIN_INT64 (n) (((n[0] & 0xffffffff) == 0x80000000) && ((n[1] & 0xffffffff) == 0))
Definition at line 54 of file ast.c.
MKU
#define MKU (a, s, d)
Value:
  {                            \
    i = new_node(A_ID);        \
    A_SPTRP(i, s);             \
    A_DTYPEP(i, d);            \
    a = mk_unop(OP_VAL, i, d); \
  }
Function Documentation
_ast_trav()
static void _ast_trav (int ast, int * extra_arg) static
Definition at line 5614 of file ast.c.
References _postorder, _preorder, _visited, ast, ast_check_visited, ast_trav_recurse(), ast_visit(), and NULL.
Referenced by ast_trav_recurse(), ast_traverse(), ast_traverse_all(), and ast_traverse_more().
_contains_ast()
static LOGICAL _contains_ast (int astTarg, LOGICAL * pflag) static
Definition at line 4321 of file ast.c.
References astMatch, FALSE, pflag, and TRUE.
Referenced by contains_ast().
_ddiv()
static void _ddiv (INT * dividend, INT * divisor, INT * quotient) static
Definition at line 9610 of file ast.c.
References flg, FLG::ieee, xddiv(), xdmul(), and xdrcp().
Referenced by const_fold().
_dump_one_ast()
void _dump_one_ast (int i, FILE * file)
Definition at line 6267 of file ast.c.
References A_ARGCNTG, A_CANCELKINDG, A_ISEXPR, A_OPTYPEG, A_ORDEREDG, A_SCHED_TYPEG, A_TKNG, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, astb, ASTB::atypes, COMSTR, dump_astli(), dump_shape(), getdtype(), getprint(), i, indent, j, k, NULL, PR_ACCTILE, ASTB::ptr0, ASTB::ptr0c, ASTB::ptr1, and SYMNAME.
Referenced by dump_ast(), and dump_one_ast().
_dump_shape()
void _dump_shape (int shd, FILE * file)
Definition at line 6240 of file ast.c.
References indent, NULL, SHD_LWB, SHD_NDIM, SHD_STRIDE, and SHD_UPB.
Referenced by dump_shape().
_dump_std()
void _dump_std (int std, FILE * fil)
Definition at line 7203 of file ast.c.
References _PFG, ast, dbg_print_ast(), NULL, std, STD_AST, STD_BR, STD_CS, STD_DELETE, STD_EX, STD_IGNORE, STD_LABEL, STD_LINENO, STD_LOCAL, STD_MINFO, STD_PAR, STD_PARSECT, STD_PURE, STD_SPLIT, STD_ST, STD_TASK, and SYMNAME.
Referenced by dump_std().
_fdiv()
static INT _fdiv (INT dividend, INT divisor) static
Definition at line 9592 of file ast.c.
References flg, FLG::ieee, xfdiv(), xfmul(), and xfrcp().
Referenced by const_fold().
_huge()
static int _huge (DTYPE dtype) static
Definition at line 7369 of file ast.c.
References ast, atoxd(), C90_HUGE, DTYG, getcon(), HUGE_NUM2, HUGE_NUM3, mk_cnst(), mk_cval1(), putsname(), sptr, strlen(), tmp, TY_BINT, TY_DBLE, TY_INT, TY_INT8, TY_QUAD, TY_REAL, TY_SINT, val, and XBIT.
Referenced by ast_intr(), and mk_smallest_val().
add_arg()
void add_arg (int arg)
Add an argument.
Parameters
arg AST of argument to add.
Definition at line 4252 of file ast.c.
References arg, ARGT_ARG, curr_call, ERR_Severe, and interr().
Referenced by add_io_arg(), add_nullify_ast(), add_ptr_assign(), add_reduce_descriptor(), add_spread_descriptor(), ast_intr(), call_dtsfmt(), collapse_assignment(), conv_allocate(), conv_forall(), elem_size_of_ast(), emit_alnd_secd(), get_defined_io_call(), ref_pd(), ref_pd_subr(), rewrite_allocatable_assignment(), semant3(), semantio(), and size_of_dtype().
add_astli()
int add_astli (void)
Create and return an AST list item, adding it to the end of the current list.
Definition at line 4163 of file ast.c.
References astb, ASTLI_FLAGS, ASTLI_NEXT, errfatal(), MAX_NMPTR, NEED, NULL, and tail_astli.
Referenced by assign_array_w_forall(), ast_rewrite(), change_forall_triple(), import(), inline_spread_shifts(), make_forall(), normalize_forall_triplet(), pointer_squeezer(), semant3(), and semantio().
add_bounds_subscripts()
int add_bounds_subscripts (int to_ast, int rank, const int lower_bound_asts[], const int upper_bound_asts[], DTYPE elt_dtype)
Definition at line 10161 of file ast.c.
References j, MAXRANK, mk_subscr(), mk_triple(), and rank.
Referenced by semant3().
add_extent_subscripts()
int add_extent_subscripts (int to_ast, int rank, const int extent_asts[], DTYPE elt_dtype)
Definition at line 10147 of file ast.c.
References astb, ASTB::bnd, j, MAXRANK, mk_subscr(), mk_triple(), ASTB::one, and rank.
Referenced by add_shapely_subscripts().
add_nullify_ast()
int add_nullify_ast (int sptrast)
Definition at line 7651 of file ast.c.
References A_OPTYPEP, add_arg(), ast, begin_call(), intast_sym, and sptr.
Referenced by _constructf90(), add_private_allocatable(), gen_alloc_mem_initialize_for_sym2(), gen_dtio_args(), gen_dtsfmt_args(), handle_allocatable_members(), misc_checks(), nullify_member(), nullify_member_after(), and semant3().
add_shape_rank()
void add_shape_rank (int ndim)
Definition at line 2616 of file ast.c.
References _shd, and ndim.
Referenced by _constructf90(), increase_shape(), mk_bounds_shape(), mk_mem_ptr_shape(), mk_subscr_copy(), mkshape(), new_shape(), reduc_shape(), and ref_pd().
add_shape_spec()
void add_shape_spec (int lwb, int upb, int stride)
Definition at line 2623 of file ast.c.
References _shd, assert, i, lwb, stride, and upb.
Referenced by _constructf90(), increase_shape(), mk_bounds_shape(), mk_mem_ptr_shape(), mk_subscr_copy(), mkshape(), new_shape(), reduc_shape(), and ref_pd().
add_shapely_subscripts()
int add_shapely_subscripts (int to_ast, int from_ast, DTYPE arr_dtype, DTYPE elt_dtype)
Definition at line 10178 of file ast.c.
References add_extent_subscripts(), get_ast_extents(), MAXRANK, and rank.
Referenced by allocate_lhs_if_needed(), construct_association(), and rewrite_allocatable_assignment().
add_stmt()
int add_stmt (int ast)
Definition at line 3888 of file ast.c.
References ast, SCN::currlab, gbl, insert_stmt_before(), mk_std(), scn, std, STD_FINDEX, STD_LABEL, STD_LINENO, and STD_ORIG.
Referenced by _constructf90(), add_assignment(), add_pragma(), add_private_allocatable(), add_ptr_assign(), add_ptr_assignment(), add_taskloopreg(), asn_sfuse(), begin_parallel_clause(), call_dtsfmt(), check_etmp(), collapse_add(), collapse_begin(), collapse_expr(), collapse_index(), compute_size_ido(), construct_association(), convert_to_block_forall(), copy_replic_sect_to_tmp(), do_bdistribute(), do_bteams(), do_copyin(), do_copyprivate(), do_dist_schedule(), do_distbegin(), do_end(), do_firstprivate(), do_lastval(), do_map(), do_openmp_atomics(), do_reduction(), do_schedule(), emit_bcs_ecs(), emit_bpar(), emit_btarget(), emit_epar(), emit_etarget(), end_association(), end_lastprivate(), end_parallel_clause(), end_reduction(), end_teams(), func_call2(), gen_alloc_dealloc(), gen_and_assoc_tmp_ptr(), gen_contig_check(), gen_defer_shape(), gen_derived_type_alloc_init(), gen_dtio_args(), gen_dtsfmt_args(), gen_finalized_result(), gen_init_unl_poly_desc(), gen_lastval(), gen_reduction(), gen_type_initialize_for_sym(), get_subscripting_tmp(), handle_dependence_ido(), incr_tmp(), inline_contig_check(), mkexpr_assign_temp(), mp_create_bscope(), mp_create_escope(), new_stds(), precompute_arg_intrin(), precompute_args(), ptrfunc_call(), ref_array(), ref_intrin(), ref_pd(), ref_stfunc(), save_clauses(), semant1(), semant3(), semantio(), semsmp(), subr_call2(), tempify(), and tempify_ast().
add_stmt_after()
int add_stmt_after (int ast, int stmt)
Definition at line 3927 of file ast.c.
References assert, ast, flg, insert_stmt_after(), mk_std(), set_par(), FLG::smp, std, and stmt.
Referenced by __gen_conditional_dealloc(), add_assign_firstprivate(), add_bound_assignments(), add_cgoto(), add_firstprivate_assn(), add_loop_hd(), add_private_allocatable(), add_ptr_assign(), add_single_loop_exit(), alloc_char_temp(), allocate_array(), bblock(), check_pointer_type(), close_entry_guard(), conv_allocate(), conv_forall(), convert_omp_workshare(), copy_arg_to_seq_tmp(), copy_back_to_replic_sect(), copy_inargs(), do_end(), emit_fl(), emit_kopy_in(), emit_scalar_kopy_in(), end_io_call(), end_or_err(), enter_lexical_block(), exit_lexical_block(), fio_end_err(), forall_dependency(), forall_dependency_scalarize(), gen_alloc_dealloc(), gen_alloc_mem_initialize_for_sym2(), gen_automatic_reallocation(), gen_conditional_alloc(), gen_conditional_dealloc_for_sym(), gen_contig_check(), gen_dealloc_for_sym(), gen_early_array_bnds(), gen_early_bnd_dependencies(), gen_early_str_len(), gen_endsingle(), gen_finalization_for_sym(), gen_init_unl_poly_desc(), gen_kind_parm_assignments(), gen_poly_element_arg(), gen_set_type(), generate_copy(), generate_gather(), generate_get_scalar(), genPolyAsn(), handle_allocatable_members(), init_derived_type(), init_intrin_type_desc(), init_sdsc(), init_sdsc_bounds(), inline_contig_check(), inline_RTE_set_type(), insert_assign(), insert_endmask(), insert_mask(), iomsg_check(), lower_data_stmts(), misc_checks(), mk_dealloc_stub(), mk_deallocate_scalar(), mk_firstprivate(), mk_loop_hdtl(), mk_ptr_subscr(), move_invar_std(), nml_emit_desc(), nullify_member_after(), open_entry_guard(), presence_test(), rewrite_allocatable_assignment(), rewrite_block_where(), rewrite_calls(), rewrite_into_forall(), rewrite_sub_args(), semant3(), semantio(), set_assumed_bounds(), set_assumsz_bound(), and unlnkilt().
add_stmt_before()
int add_stmt_before (int ast, int stmt)
Definition at line 3943 of file ast.c.
References assert, ast, flg, insert_stmt_before(), mk_std(), set_par(), FLG::smp, std, and stmt.
Referenced by _constructf90(), _ptrassign(), _ptrassign_copy(), _ptrassign_set(), _ptrassign_set_ast(), _reshape(), _rewrite_scalar_fuctions(), _RTE_ba(), _sect(), _template(), add_assignment_before(), add_auto_bounds(), add_bound_assignments(), add_end_presence(), add_presence(), add_ptr_assign(), add_reduce_descriptor(), add_spread_descriptor(), addssassignments(), alloc_char_temp(), allocate_lhs_if_needed(), assign_bounds(), assign_scalar(), bblock(), check_alloc_ptr_type(), check_pointer_type(), component_init_allocd_auto(), conv_deallocate(), conv_forall(), conv_fused_forall(), convert_omp_workshare(), convert_template_instance(), copy_arg_to_seq_tmp(), copy_desc_to_bnds_vars(), copy_inargs(), copy_scalar_intent_in(), copy_surrogate_to_bnds_vars(), copy_to_scalar(), emit_alnd(), emit_copy_section(), emit_gatherx(), emit_get_scalar(), emit_get_scalar_sub(), emit_kopy_in(), emit_overlap(), emit_permute_section(), emit_redim(), emit_scalar_kopy_in(), emit_scatterx_gatherx(), emit_secd(), emit_sum_scatterx(), enter_local_mode(), exit_local_mode(), forall_dependency(), forall_dependency_scalarize(), forall_lhs_indirection(), forall_with_mask(), func_call2(), gen_alloc_dealloc(), gen_alloc_mbr(), gen_allocated_check(), gen_automatic_reallocation(), gen_bounds_assignments(), gen_contig_check(), gen_dealloc_if_allocated(), gen_dealloc_mbr(), gen_derived_arr_init(), gen_do_ends(), gen_dos_over_shape(), gen_early_array_bnds(), gen_early_str_len(), gen_endsingle(), gen_kind_parm_assignments(), gen_poly_element_arg(), gen_ptr_in(), gen_set_type(), generate_copy(), generate_gather(), generate_get_scalar(), generate_hcycliclp(), generate_hlocalizebnds(), get_invoking_proc_desc(), handle_allocatable_members(), handle_shift(), init_sdsc(), init_sdsc_bounds(), init_sptr_w_acl(), inline_contig_check(), inline_hlocalizebnds(), inline_reduction_f90(), inline_RTE_set_type(), inline_shifts(), inline_small_matmul(), insert_assign(), make_sec_ast(), make_sec_from_ast_chk(), make_simple_template_from_ast(), make_temp_descriptor(), matmul(), mk_allocate_scalar(), mk_ptr_subscr(), mk_ztrips(), mmul(), move_labels(), normalize_forall_triplet(), nullify_member(), partition_blocks(), put_calls(), recurse_eoshift(), recurse_shift(), redimension(), reshape(), rewrite_allocatable_assignment(), rewrite_block_forall(), rewrite_block_where(), rewrite_calls(), rewrite_deallocate(), rewrite_func_ast(), rewrite_intr_allocatable(), rewrite_sub_args(), rewrite_where_expr(), semant3(), sequentialize(), sequentialize_call(), set_descr_tag(), set_type_in_descriptor(), symvalue(), temp_type_descriptor(), tmp_assign(), trans_mkproc(), transform_all_call(), transform_c_f_pointer(), transform_c_f_procpointer(), transform_call(), transform_elemental(), transform_merge(), transform_move_alloc(), and transform_mvbits().
ast_clear_repl()
void ast_clear_repl (int ast)
Only called by the semantic analyzer; if it needs to be used by all phases, many ASTs need to be added as cases.
Definition at line 5456 of file ast.c.
References A_ARGCNTG, arg, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, ast_clear_repl(), i, interr(), and void().
Referenced by asn_sfuse(), and ast_clear_repl().
ast_fini()
void ast_fini (void)
Definition at line 239 of file ast.c.
References ASTB::asd, astb, FREE, ASTB::shd, and STG_DELETE.
Referenced by finish().
ast_implicit()
void ast_implicit (int firstc, int lastc, DTYPE dtype)
Parameters
firstc first character in range
lastc last character in range
dtype implicit dtype pointer: 0 => NONE
Definition at line 4195 of file ast.c.
References astb, DTY, i, IMPL_INDEX, ASTB::implicit, and j.
Referenced by mod_add_subprogram(), and semant1().
ast_init()
void ast_init (void)
Initialize AST table for new user program unit.
Definition at line 60 of file ast.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_UPAST, ADD_UPBD, ASTB::asd, assert, astb, atemps, aux, ASTB::bnd, BZERO, AUX::dt_iarray, AUX::dt_iarray_int, STB::dt_int, DT_INT, DTY, ASTB::dtype, ASTB::firstuast, get_array_dtype(), get_aux_arrdsc(), ASTB::hash, HSHSZ, ASTB::hshtb, i, ASTB::i0, ASTB::i1, ASTB::implicit, ASTB::k0, ASTB::k1, mk_cval(), MKU, NEW, ASTB::one, ASTB::ptr0, ASTB::ptr0c, ASTB::ptr1, ASTB::shd, stb, STD_FINDEX, STD_FLAGS, STD_LINENO, STD_NEXT, STD_PREV, STG_ALLOC, STG_NEXT, STG_RESET, STB::user, XBIT, and ASTB::zero.
Referenced by semant_init().
ast_intr()
int ast_intr (int i_intr, DTYPE dtype, int cnt, ...)
Definition at line 7271 of file ast.c.
References _huge(), A_OPTYPEP, add_arg(), assert, ast, begin_call(), cnt, DT_DBLE, DT_INT, DTY, DTYG, ERR_Fatal, FALSE, FLANG_FALLTHROUGH, GREALG, intast_sym, mk_cval(), mkRteRtnNm(), RTE_dble, RTE_int, RTE_real, sptr, sym_mkfunc_nodesc(), TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_REAL, TY_SINT, TY_SLOG, ty_to_lib, TY_WORD, and void().
Referenced by __gen_conditional_dealloc(), _reshape(), add_private_allocatable(), chksubstr(), construct_intrinsic_acl(), conv_to_int(), copy_arg_to_seq_tmp(), cp_loop(), emit_kopy_in(), emit_redim(), emit_scalar_kopy_in(), find_presence(), fix_dtype(), gen_char_result(), gen_early_bnd_dependencies(), gen_early_str_len(), gen_lastval(), gen_minmax(), gen_ptr_in(), inline_contig_check(), inline_shifts(), mk_int(), mk_largest_val(), presence_test(), ref_pd(), rewrite_allocatable_assignment(), rewrite_calls(), set_assumed_bounds(), set_assumsz_bound(), size_ast(), size_ast_of(), size_of_allocatable(), string_expr_length(), and transform_c_f_pointer().
ast_is_sym()
LOGICAL ast_is_sym (int ast)
Definition at line 2922 of file ast.c.
References ast, and sym_of_ast2().
Referenced by _constructf90(), add_ptr_assign(), allocate_lhs_if_needed(), check_doconcurrent_ast(), gen_contig_check(), get_descr_or_placeholder_arg(), inline_reduction_f90(), is_deferlenchar_ast(), lower_stmt(), ref_pd(), rewrite_all_shape(), rewrite_allocatable_assignment(), semant2(), set_descr_tag(), tkr_match(), and transform_call().
ast_replace()
void ast_replace (int old, int new)
The old AST is to be replaced by the new AST.
Set its REPL field and add to the visit list. The caller of ast_rewrite() will have called ast_replace() one or more times to 'initialize' the rewriting process.
Definition at line 4397 of file ast.c.
References ast_visit(), ast_visit_state, FALSE, and interr().
Referenced by _constructf90(), _linearize(), _rewrite_scalar_fuctions(), _simple_replacements(), addssassignments(), asn_sfuse(), ast_rewrite(), ast_rewrite_indices(), canonical_conversion(), collapse_loops(), compute_size_ido(), copy_const(), cp_loop(), define_stfunc(), fill_argt_with_alnd(), forall_make_same_idx(), gen_array_result(), get_all_descriptors(), handle_dependence_ido(), merge(), opt_allocate(), reassociate(), ref_stfunc(), remove_from_scalar_subscript(), remove_function_common_from_scalar_subscript(), rename_forall_list(), replace_arguments(), replace_label(), replace_parms(), rewrite_subscr(), rewrite_triples(), same_forall_bnds(), and scan_ind_uses().
ast_revisit()
void ast_revisit (ast_visit_fn proc, int * extra_arg)
Visit the nodes on the 'visit_list' again, call proc on each one.
Definition at line 4457 of file ast.c.
References visit_list.
Referenced by lower_end_stmt(), and lower_reinit().
ast_rewrite()
int ast_rewrite (int ast)
Definition at line 4469 of file ast.c.
References A_ARGCNTG, A_ARGCNTP, A_CANCELKINDG, A_CANCELKINDP, A_MEM_ORDERG, A_MEM_ORDERP, A_OPTYPEG, A_OPTYPEP, A_ORDEREDG, A_ORDEREDP, A_SCHED_TYPEG, A_SCHED_TYPEP, A_TKNG, A_TKNP, add_astli(), argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, ast_replace(), ast_rewrite(), astb, ASTLI_AST, ASTLI_HEAD, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, ASTB::bnd, chunk, CONVAL2G, DDTG, dest, dim, DT_INT, ASTB::dtype, FALSE, get_array_dtype(), i, interr(), lbound_of_shape(), lwb, m2, m4, MAXRANK, mem(), mk_argt(), mk_assn_stmt(), mk_binop(), mk_convert(), mk_func_node(), mk_id(), mk_init(), mk_member(), mk_paren(), mk_stmt(), mk_subscr(), mk_substr(), mk_triple(), mk_unop(), new_node(), ASTB::one, OP_ADD, OP_DIV, OP_SUB, parent, rank, reset_astli(), rewrite_opfields, s, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, src, start, start_astli(), stride, sub, TRUE, ubound_of_shape(), unmk_argt(), and upb.
Referenced by _constructf90(), _linearize(), acl_rewrite_asts(), addssassignments(), asn_sfuse(), ast_rewrite(), ast_rewrite_indices(), canonical_conversion(), collapse_loops(), compute_size_ido(), convert_simple(), copy_const(), cp_loop(), define_stfunc(), fill_argt_with_alnd(), fix_character_length(), forall_make_same_idx(), gen_array_result(), gen_char_result(), get_all_descriptors(), handle_dependence_ido(), linearize_arrays(), reassociate(), ref_stfunc(), remove_from_scalar_subscript(), remove_function_common_from_scalar_subscript(), rename_forall_list(), replace_label(), replace_parms(), rewrite_all_asts(), rewrite_all_shape(), rewrite_inlined_args(), rewrite_scalar_functions(), rewritefg(), same_forall_bnds(), and scan_ind_uses().
ast_to_comment()
void ast_to_comment (int ast)
Definition at line 4077 of file ast.c.
References A_STDG, A_STDP, ast, mk_stmt(), par, std, STD_ACCEL, STD_AST, STD_FLAGS, and STD_PAR.
Referenced by _RTE_ba(), assign(), conv_forall(), convert_omp_workshare(), forall_dependency_analyze(), get_temp_forall2(), nop_dealloc(), rewrite_allocatable_assignment(), rewrite_block_forall(), rewrite_block_where(), rewrite_calls(), rewrite_into_forall(), sectinline(), semant1(), and sequentialize().
ast_trav_recurse()
void ast_trav_recurse (int ast, int * extra_arg)
Definition at line 5637 of file ast.c.
References _ast_trav(), A_ARGCNTG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, ASTLI_AST, ASTLI_NEXT, ASTLI_TRIPLE, cnt, i, and interr().
Referenced by _ast_trav(), and _fam().
ast_traverse()
void ast_traverse (int ast, ast_preorder_fn preorder, ast_visit_fn postorder, int * extra_arg)
General ast traversal function: uses a list to keep track of the ast nodes which have been visited; if a node is visited, the node's REPL field is non-zero.
Parameters
ast the ast to traverse
preorder called before visiting children; return TRUE to prevent visiting ast's operands
postorder called after visiting children
extra_arg passed to preorder and postorder
preorder and postorder can be NULL. If they are not, they are called with two arguments, an ast and a pointer. The pointer argument 'extra_arg' (possibly NULL) may be used by the caller to pass value(s) to visit routines, used by the visit routines to return values, or both.
Visited asts are linked together using 'visit_list'; the caller must call ast_unvisit() to cleanup up the VISIT and REPL fields of the asts. To begin the traverse, ast #1 must be marked visited by the caller; e.g.,
  ast_visit(1, 1);
Definition at line 5565 of file ast.c.
References _ast_trav(), _postorder, _preorder, ast, ast_check_visited, and TRUE.
Referenced by _check_clean(), _findrefs(), _linearize_all(), any_functions(), avail_expr(), bld_lhs(), bld_ud(), bld_use(), bnd_contains_auto(), build_do_init(), build_ud(), charintr_arg_forall_depnd(), check_doconcurrent(), chk_kind_parm(), contains_any_call(), contains_ast(), contains_forall_index(), contains_sptr(), convert_simple(), convert_template_instance(), copy_to_loop(), create_nmes(), define_stfunc(), eliminate_unused_variables(), export_ict_asts(), export_ivl_asts(), export_ivl_ict_asts(), find_assumshp_dep(), find_descrs(), find_lhs_on_rhs_conflict(), find_pointer_assignments_f90(), find_rhs_conflict(), findssexprsfg(), init_exprs_idx_dependent(), invar_src(), is_another_shift(), is_atomic_update_binop(), linearize_arrays(), lower_check_ast(), lower_expression(), lower_no_subscr_chk(), mark_ast(), mark_dtype_ast_idstr(), markmodifiedexprsfg(), mask_on_lhs(), nice_where_mask(), printstdref(), pstride_analysis(), queue_ast(), ref_stfunc(), replace_parms(), rewrite_inlined_args(), rewrite_scalar_functions(), save_contained(), and sfloat().
ast_traverse_all()
void ast_traverse_all (int ast, ast_preorder_fn preorder, ast_visit_fn postorder, int * extra_arg)
Recursively visit the ast operands of ast; useful if the caller needs check the 'result' (via extra_arg) of the visit function.
See ast_traverse() for details about params.
For the case where it's necessary to perform certain actions/checks when an ast has already been visited, ast_estab_visited(visit) may be called prior to ast_traverse() to establish such a function. ast_unvisit() removes this function.
Definition at line 5591 of file ast.c.
References _ast_trav(), _postorder, _preorder, ast, ast_check_visited, and FALSE.
Referenced by _fam(), and find_fam().
ast_traverse_more()
void ast_traverse_more (int ast, int * extra_arg)
While in an ast_traverse recursion, continue on another subtree.
Definition at line 5608 of file ast.c.
References _ast_trav(), and ast.
Referenced by markid().
ast_unvisit()
void ast_unvisit (void)
Traverse the visit list to clean up the nodes in the list.
The caller must call ast_unvisit(). ast_unvisit() also clears the REPL field.
Definition at line 4416 of file ast.c.
References _visited, ast_check_visited, ast_visit_state, FALSE, interr(), next, NULL, rewrite_opfields, and visit_list.
Referenced by _constructf90(), any_functions(), assumshp_args(), ast_rewrite_indices(), avail_expr(), basic_block_redundant(), bblock(), bnd_contains_auto(), build_do_init(), build_ud(), canonical_conversion(), charintr_arg_forall_depnd(), check_doconcurrent(), chk_kind_parm(), collapse_loops(), compute_size_ido(), contains_any_call(), contains_ast(), contains_forall_index(), contains_sptr(), convert_simple(), convert_template_instance(), copy_const(), copy_to_loop(), cp_loop(), create_nmes(), define_stfunc(), eliminate_unused_variables(), emit_alnd_secd(), export(), export_host_subprogram(), export_module_subprogram(), find_descrs(), find_lhs_on_rhs_conflict(), find_pointer_assignments_f90(), find_rhs_conflict(), findssexprs(), fix_character_length(), fixup_host_symbol_dtype(), forall_make_same_idx(), gen_array_result(), gen_char_result(), get_all_descriptors(), handle_dependence_ido(), init_exprs_idx_dependent(), invar_src(), is_another_shift(), is_atomic_update_binop(), linearize_arrays(), mask_on_lhs(), merge(), nice_where_mask(), opt_allocate(), printstdref(), pstride_analysis(), reassociate(), ref_stfunc(), remove_from_scalar_subscript(), remove_function_common_from_scalar_subscript(), rename_forall_list(), replace_label(), rewrite_inlined_args(), rewrite_scalar_functions(), same_forall_bnds(), scan_ind_uses(), sfloat(), and transform_wrapup().
ast_unvisit_norepl()
void ast_unvisit_norepl (void)
Definition at line 4436 of file ast.c.
References _visited, ast_visit_state, FALSE, interr(), next, NULL, rewrite_opfields, and visit_list.
Referenced by lower_data_stmts(), lower_end_stmt(), lower_reinit(), markmodifiedexprs(), and save_contained().
ast_visit()
void ast_visit (int old, int new)
Add an AST to the visit list.
An ast is added to the visit list during ast_rewrite() and ast_traverse().
Definition at line 4370 of file ast.c.
References ast_check_visited, ast_visit_state, FALSE, interr(), and TRUE.
Referenced by _ast_trav(), _constructf90(), add_auto_bounds(), add_bound_assignments(), any_functions(), assumshp_args(), ast_replace(), ast_rewrite_indices(), avail_expr(), basic_block_redundant(), bblock(), bnd_contains_auto(), build_do_init(), build_ud(), canonical_conversion(), charintr_arg_forall_depnd(), check_doconcurrent(), chk_kind_parm(), collapse_loops(), compute_size_ido(), contains_any_call(), contains_ast(), contains_forall_index(), contains_sptr(), convert_simple(), convert_template_instance(), copy_const(), copy_to_loop(), cp_loop(), create_nmes(), define_stfunc(), eliminate_unused_variables(), emit_alnd_secd(), export(), export_host_subprogram(), export_module_subprogram(), find_descrs(), find_lhs_on_rhs_conflict(), find_pointer_assignments_f90(), find_rhs_conflict(), findssexprs(), fix_character_length(), fixup_host_symbol_dtype(), forall_make_same_idx(), gen_array_result(), gen_char_result(), get_all_descriptors(), handle_dependence_ido(), init_exprs_idx_dependent(), interface_for_entry(), invar_src(), is_another_shift(), is_atomic_update_binop(), linearize_arrays(), lower_reinit(), lower_start_stmt(), markmodifiedexprs(), mask_on_lhs(), merge(), nice_where_mask(), opt_allocate(), printstdref(), pstride_analysis(), reassociate(), ref_stfunc(), remove_from_scalar_subscript(), remove_function_common_from_scalar_subscript(), rename_forall_list(), replace_formal_triples(), replace_label(), rewrite_inlined_args(), rewrite_scalar_functions(), same_forall_bnds(), save_contained(), scan_ind_uses(), search_for_auto(), and sfloat().
begin_call()
int begin_call (int ast_type, int func, int count)
Parameters
ast_type A_FUNC, A_CALL, or A_INTR
func sptr of function to invoke
count number of arguments
Definition at line 4225 of file ast.c.
References A_ARGCNTP, ast_type, count, curr_call, func, interr(), mk_argt(), mk_id(), and new_node().
Referenced by add_nullify_ast(), add_ptr_assign(), add_reduce_descriptor(), add_spread_descriptor(), ast_intr(), begin_io_call(), call_dtsfmt(), collapse_assignment(), conv_allocate(), conv_forall(), elem_size_of_ast(), emit_alnd_secd(), get_defined_io_call(), ref_pd(), ref_pd_subr(), rewrite_allocatable_assignment(), semant3(), semantio(), and size_of_dtype().
bnds_remap_list()
LOGICAL bnds_remap_list (int subscr_ast)
Definition at line 3681 of file ast.c.
References ASD_NDIM, ASD_SUBS, ast, dim, FALSE, ndims, and TRUE.
Referenced by lower_stmt(), transform_ptr(), and valid_assign_pointer_types().
bounds_match()
static LOGICAL bounds_match (int lwdtype, int lwshape, int parent) static
Definition at line 3617 of file ast.c.
References ASD_NDIM, ASD_SUBS, FALSE, parent, and TRUE.
Referenced by is_whole_array().
cngcon()
INT cngcon (INT oldval, int oldtyp, int newtyp)
Convert constant from oldtyp to newtyp.
Returns
constant value for 32-bit constants, or symbol table pointer
Issue error messages only for impossible conversions.
Can only be used for scalar constants.
Remember: Non-decimal constants are octal, hexadecimal, or hollerith constants which are represented by DT_WORD, DT_DWORD and DT_HOLL. Non-decimal constants 'assume' data types rather than go thru a conversion. Hollerith constants have a data type of DT_HOLL in the semantic stack; the CONVAL1 field locates a constant of data type DT_CHAR and the CONVAL2 field indicates the kind of Hollerith ('h', 'l', or 'r').
Hollerith constants are always treated as scalars while octal or hexadecimal constants can be promoted to vectors.
Definition at line 8769 of file ast.c.
References BCOPY, BYTE_NUMBER16, CNULL, CONVAL2G, conversion_warning(), cp, STB::dbl0, DTY, FLG::endian, errinfo(), error(), errsev(), errwarn(), F77OUTPUT, FLANG_FALLTHROUGH, flg, gbl, get_type(), getcon(), getitem(), getstring(), hex2char(), hex2nchar(), holtonum(), is_empty_typedef(), kanji_len(), kanji_prefix(), local_sname(), MASKH32, mk_cval(), STB::n_base, num, STB::quad0, result, sign_extend(), FLG::standard, stb, string_length(), truncation_warning(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_ISINT, TY_ISLOG, TY_ISNUMERIC, TY_ISSCALAR, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, xdble(), xdfix(), xdfix64(), xdfloat(), xdflt64(), xdtoq(), xffloat(), xfix(), xfix64(), xflt64(), xftoq(), xqfix(), xqfix64(), xqfloat(), xqflt64(), xqtod(), xqtof(), and xsngl().
Referenced by _put(), _xtok(), binop(), check_ccon(), chkcon(), chksubstr(), cngtyp2(), const_eval(), const_fold(), conv_bint_ilm(), conv_blog_ilm(), conv_cmplx_ilm(), conv_dble_ilm(), conv_dcmplx_ilm(), conv_dword_ilm(), conv_int8_ilm(), conv_int_ilm(), conv_log8_ilm(), conv_log_ilm(), conv_real_ilm(), conv_sint_ilm(), conv_slog_ilm(), conv_word_ilm(), convert_acl_dtype(), dinit_getval(), dinit_getval1(), dinit_val(), eval_abs(), eval_ceiling(), eval_char(), eval_floor(), eval_fltconvert(), eval_ichar(), eval_init_op(), eval_int(), eval_mod(), eval_nint(), eval_sqrt(), get_kind_value(), get_param_alias_const(), init_fold_const(), lower_ast(), read_init(), ref_array(), ref_intrin(), ref_pd(), semant1(), and set_kind_result().
complex_alias()
int complex_alias (int ast)
For an AST tree with members and subscripts, if the base variable has the PARAMG bit set and all the subscripts are known constants, we can perhaps find the value the AST and set the A_ALIAS flag.
Definition at line 2139 of file ast.c.
References a, ADD_LWAST, ADD_MLPYR, ASD_NDIM, ASD_SUBS, ast, complex_alias(), CONVAL2G, DTY, i, j, mplyr, ndim, PARAMVALG, sptr, and ss.
Referenced by complex_alias(), eval_con_expr(), eval_KIND_expr(), mk_member(), and mk_subscr_copy().
conform_shape()
LOGICAL conform_shape (int shape1, int shape2)
Check conformance of shape descriptors.
Returns
true if the data types for two shapes are conformable (have the same shape). Shape is defined to be the rank and the extents of each dimension.
Definition at line 2643 of file ast.c.
References FALSE, get_isz_cval(), i, ISZ_T, ndim, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, and TRUE.
Referenced by chkshape(), cngshape(), extract_shape_from_args(), ref_pd(), ref_pd_subr(), rewrite_block_where(), rewrite_into_forall(), and set_shape_result().
const_fold()
INT const_fold (int opr, INT conval1, INT conval2, DTYPE dtype)
Definition at line 8095 of file ast.c.
References _ddiv(), _fdiv(), add64(), cmp64(), cngcon(), CNULL, CONVAL2G, STB::dbl0, STB::dbl1, div64(), DTY, error(), errsev(), STB::flt0, STB::flt1, gbl, getcon(), interr(), KANJI_BLANK, kanji_char(), mul64(), STB::n_base, OP_ADD, OP_CMP, OP_DIV, OP_MUL, OP_SUB, OP_XTOI, OP_XTOX, p, q, STB::quad0, STB::quad1, result, stb, string_length(), sub64(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, UINT, xcdpow(), xcfpow(), xcqpow(), xdadd(), xdcmp(), xdmul(), xdpow(), xdsub(), xfadd(), xfcmp(), xfmul(), xfpow(), xfsub(), xqadd(), xqcmp(), xqdiv(), xqmul(), xqpow(), xqsub(), and xucmp().
Referenced by _xtok(), binop(), chk_kind_parm_set_expr(), const_eval(), eval_con_expr(), eval_init_op(), eval_KIND_expr(), mk_binop(), mk_cmp(), negate_const(), reduce_i8add(), ref_intrin(), and ref_pd().
contains_ast()
LOGICAL contains_ast (int astTarg, int astSrc)
Return TRUE if astSrc occurs somewhere within astTarg.
WARNING: This routine may not produce correct results for non-leaf AST's – correctness depends on hashing capabilities.
Definition at line 4336 of file ast.c.
References _contains_ast(), ast_traverse(), ast_unvisit(), ast_visit(), astMatch, FALSE, NULL, and result.
Referenced by aliased_args(), bounds_depends(), check_dependence_ido(), compute_size_ido(), is_contains_ast_between(), is_fusable(), is_valid_atomic_capture(), not_in_arrfn(), position_finder(), and put_forall_pcalls().
contiguous_array_section()
static LOGICAL contiguous_array_section (int subscr_ast) static
Definition at line 3431 of file ast.c.
References ASD_NDIM, ASD_SUBS, ast, dim, FALSE, FLANG_FALLTHROUGH, interr(), is_whole_dim(), ndims, stride1_triple(), and TRUE.
Referenced by simply_contiguous().
conversion_warning()
static void conversion_warning (void) static
Definition at line 9585 of file ast.c.
References ERR_Warning, error(), and gbl.
Referenced by cngcon().
convert_cnst()
static int convert_cnst (int cnst, int newtyp) static
Definition at line 1387 of file ast.c.
References CONVAL2G, STB::dbl0, DTY, FLANG_FALLTHROUGH, getcon(), mk_cval1(), num, STB::quad0, result, sign_extend(), size_of(), sptr, stb, TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_ISINT, TY_ISSCALAR, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, XBIT, xdble(), xdfix(), xdfix64(), xdfloat(), xdflt64(), xdtoq(), xffloat(), xfix(), xfix64(), xflt64(), xftoq(), xqfix(), xqfix64(), xqfloat(), xqflt64(), xqtod(), xqtof(), and xsngl().
Referenced by mk_convert(), and mk_int().
convert_int()
int convert_int (int ast, DTYPE dtype)
Definition at line 1379 of file ast.c.
References ast, and mk_convert().
Referenced by add_reduce_descriptor(), add_spread_descriptor(), collapse_assignment(), mk_binop(), mk_unop(), ref_pd(), and rewrite_func_ast().
delete_stmt()
void delete_stmt (int std)
Definition at line 7627 of file ast.c.
References gbl, mk_stmt(), NOSYM, remove_stmt(), std, STD_AST, STD_DELETE, STD_FINDEX, and STD_LINENO.
Referenced by alloc2ast(), assign(), collapse_allocates(), conv_allocate(), conv_deallocate(), conv_forall(), conv_fused_forall(), convert_template_instance(), convert_to_block_forall(), eliminate_barrier(), gen_derived_arr_init(), generate_copy(), generate_gather(), generate_get_scalar(), generate_hallobnds(), generate_hcycliclp(), generate_hlocalizebnds(), generate_sect(), inline_stds(), no_effect_forall(), put_calls(), remove_block(), rewrite_asn(), sequentialize(), sequentialize_call(), transform_c_f_pointer(), transform_c_f_procpointer(), transform_elemental(), transform_merge(), transform_move_alloc(), and transform_mvbits().
dist_ast()
int dist_ast (int ast)
Return the AST of the leftmost A_SUBSCR or A_ID that is distributed or aligned.
For a%b(i)%c%d(j)%e, it will return the AST of %e, d(j), %c, b(i), or a, depending on which is distributed.
Definition at line 3359 of file ast.c.
References ALIGNG, ast, DISTG, interr(), and sptr.
Referenced by emit_get_scalar(), and no_comm_class().
dump_ast()
void dump_ast (void)
Definition at line 7170 of file ast.c.
References _dump_one_ast(), astb, DBGBIT, gbl, HSHSZ, ASTB::hshtb, and i.
Referenced by dbg_dump(), import_inline(), and init().
dump_ast_tree()
void dump_ast_tree (int i)
Definition at line 6787 of file ast.c.
References a, A_ARGCNTG, ARGT_ARG, ASD_NDIM, ASD_SUBS, astb, dump_ast_tree(), dump_one_ast(), gbl, i, indent, j, k, and PR_ACCTILE.
Referenced by asn_sfuse(), dump_ast_tree(), dump_stfunc(), dumpsst(), and ref_stfunc().
dump_astli()
void dump_astli (int astli)
Definition at line 7191 of file ast.c.
References ASTLI_FLAGS, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, and gbl.
Referenced by _dump_one_ast().
dump_one_ast()
void dump_one_ast (int i)
Definition at line 6780 of file ast.c.
References _dump_one_ast(), gbl, and i.
Referenced by ast_error(), dump_ast_tree(), and dump_stfunc().
dump_shape()
void dump_shape (int shd)
Definition at line 6260 of file ast.c.
References _dump_shape(), and gbl.
Referenced by _dump_one_ast().
dump_std()
void dump_std (void)
Definition at line 7238 of file ast.c.
References _dump_std(), gbl, std, and STD_NEXT.
Referenced by bblock(), collapse_arrays(), comm_invar(), inliner(), lower(), and optimize().
dump_stg_stat()
void dump_stg_stat (const char * where)
Definition at line 7248 of file ast.c.
References ASTB::asd, astb, STB::dt, FILE, gbl, NULL, ASTB::shd, and stb.
Referenced by display_error(), and dump_stg_stats().
elem_size_of_ast()
int elem_size_of_ast (int ast)
Given an ast, return an ast with the element size.
Definition at line 3757 of file ast.c.
References add_arg(), ast, astb, begin_call(), ASTB::bnd, DTY, ASTB::dtype, i, mk_isz_cval(), mkRteRtnNm(), RTE_lena, RTE_nlena, size_of(), sym_mkfunc_nodesc(), sym_mkfunc_nodesc_expst(), TY_CHAR, and TY_NCHAR.
Referenced by ref_pd().
elemental_func_call()
LOGICAL elemental_func_call (int func_ast)
Definition at line 3141 of file ast.c.
References FALSE, NULL, proc_arginfo(), procsym_of_ast(), and TRUE.
Referenced by _contains_any_call(), build_array_ref(), normalize_forall(), pure_procedure(), rewrite_calls(), rewrite_func_ast(), rewrite_sub_ast(), search_conform_array(), and transform_elemental().
extent_of_shape()
int extent_of_shape (int shape, int dim)
Create an ast representing the extent of a dimension.
Parameters
shape shape descriptor
dim which dimension (0 based)
Definition at line 2696 of file ast.c.
References a, astb, ASTB::bnd, cmp64(), CONVAL2G, dim, DT_INT, DTY, ASTB::dtype, ASTB::i0, lb, mk_binop(), mk_merge(), OP_ADD, OP_DIV, OP_GE, OP_SUB, SHD_LWB, SHD_STRIDE, SHD_UPB, stride, TY_INT8, ub, XBIT, and ASTB::zero.
Referenced by _constructf90(), _reshape(), gen_bounds_assignments(), get_ast_extents(), mk_bounds_shape(), mk_shape_intrin(), mk_size_intrin(), mk_ulbound_intrin(), and ref_pd().
find_pointer_target()
void find_pointer_target (int ast, int * pbase, int * psym)
Find the symbol table entry of the target from an ast representing the target in a pointer assignment.
Definition at line 7920 of file ast.c.
References ast, base, and psym.
Referenced by chk_pointer_target(), and ref_pd().
find_pointer_variable()
int find_pointer_variable (int ast)
Find the symbol table entry of pointer variable from an ast representing a pointer object.
Definition at line 7900 of file ast.c.
References ast, and FLANG_FALLTHROUGH.
Referenced by add_nullify(), chk_arguments(), find_pointer_variable_assign(), gen_allocate(), lower_stmt(), mkarg(), print_ast(), ref_intrin_subr(), ref_pd(), semant3(), and transform_ptr().
finish_args()
void finish_args (DTYPE dtype, LOGICAL promote)
For an elemental intrinsic or function AST created by begin_call() and one or more calls to add_arg, fill in the result dtype and shape of the AST.
Parameters
dtype scalar dtype of the function/intrinsic
promote if TRUE, promote the dtype to an array & create a shape descriptor
Definition at line 4272 of file ast.c.
References ARGT_ARG, curr_call, and get_array_dtype().
get_ast_asd()
int get_ast_asd (int ast)
Definition at line 9873 of file ast.c.
References ast, and resolve_ast_alias().
get_ast_bounds()
int get_ast_bounds (int lower_bound_asts[], int upper_bound_asts[], int from_ast, DTYPE arr_dtype)
Definition at line 10085 of file ast.c.
References ADD_LWAST, ADD_UPAST, ASD_SUBS, astb, ASTB::bnd, dim, get_ast_extents(), get_ast_rank(), is_array_dtype(), lb, ASTB::one, rank, SHD_LWB, SHD_STRIDE, SHD_UPB, stride, and ub.
Referenced by semant3().
get_ast_dtype()
DTYPE get_ast_dtype (int ast)
Definition at line 9881 of file ast.c.
References ast, and resolve_ast_alias().
Referenced by get_ast_rank(), and is_array_ast().
get_ast_extents()
int get_ast_extents (int extent_asts[], int from_ast, DTYPE arr_dtype)
Definition at line 10027 of file ast.c.
References ADD_LWAST, ADD_UPAST, ASD_SUBS, astb, ASTB::bnd, dim, ASTB::dtype, extent(), extent_of_shape(), get_ast_rank(), is_array_dtype(), lb, mk_binop(), ASTB::one, OP_ADD, OP_DIV, OP_SUB, rank, SHD_LWB, SHD_STRIDE, SHD_UPB, stride, and ub.
Referenced by add_shapely_subscripts(), and get_ast_bounds().
get_ast_rank()
int get_ast_rank (int ast)
Definition at line 9911 of file ast.c.
References ADD_NUMDIM, ast, get_ast_dtype(), is_array_dtype(), resolve_ast_alias(), and SHD_NDIM.
Referenced by construct_association(), get_ast_bounds(), get_ast_extents(), rewrite_ast_with_new_dtype(), and rewrite_func_ast().
get_ast_sptr()
int get_ast_sptr (int ast)
Definition at line 9936 of file ast.c.
References ast, get_ast_sptr(), NOSYM, resolve_ast_alias(), and sptr.
Referenced by construct_association(), get_ast_sptr(), and valid_assign_pointer_types().
has_adjustable_expr()
int has_adjustable_expr (int ast)
Looks for an adjustable array expression in an AST.
Parameters
ast is the AST expression that we're examining.
Definition at line 7720 of file ast.c.
References A_OPTYPEG, ARGT_ARG, ast, DTY, has_adjustable_expr(), i, interr(), and sptr.
Referenced by has_adjustable_expr().
has_allocatable_expr()
int has_allocatable_expr (int ast)
Looks for an allocatable expression in an AST.
Parameters
ast is the AST expression that we're examining.
Definition at line 7824 of file ast.c.
References A_OPTYPEG, ARGT_ARG, ast, has_allocatable_expr(), i, interr(), and sptr.
Referenced by has_allocatable_expr().
has_assumshp_expr()
int has_assumshp_expr (int ast)
Looks for an assumed shape expression in an AST.
Parameters
ast is the AST expression that we're examining.
Definition at line 7667 of file ast.c.
References A_OPTYPEG, ARGT_ARG, ast, DTY, has_assumshp_expr(), i, interr(), and sptr.
Referenced by has_assumshp_expr().
has_pointer_expr()
int has_pointer_expr (int ast)
Looks for a pointer expression in an AST.
Parameters
ast is the AST expression that we're examining.
Definition at line 7773 of file ast.c.
References A_OPTYPEG, ARGT_ARG, ast, has_pointer_expr(), i, interr(), and sptr.
Referenced by has_pointer_expr().
has_vector_subscript_ast()
LOGICAL has_vector_subscript_ast (int ast)
Definition at line 9798 of file ast.c.
References ASD_NDIM, ASD_SUBS, ast, FALSE, has_vector_subscript_ast(), is_array_ast(), j, resolve_ast_alias(), and TRUE.
Referenced by has_vector_subscript_ast(), is_associatable_variable_ast(), and rewrite_allocatable_assignment().
hash_binop()
static int hash_binop (int a, DTYPE dtype, int lop, int optype, int rop) static
Definition at line 354 of file ast.c.
References a, A_OPTYPEG, A_OPTYPEP, ADD_NODE, astb, HSH_4, ASTB::hshtb, and optype().
Referenced by mk_binop(), reduce_i8add(), and reduce_iadd().
hash_cmplxc()
static int hash_cmplxc (int a, DTYPE dtype, int lop, int rop) static
Definition at line 452 of file ast.c.
References a, ADD_NODE, astb, HSH_3, and ASTB::hshtb.
Referenced by mk_cmplxc().
hash_conv()
static int hash_conv (int a, DTYPE dtype, int lop, int shd) static
Definition at line 393 of file ast.c.
References a, ADD_NODE, astb, HSH_3, and ASTB::hshtb.
Referenced by mk_convert(), and mk_promote_scalar().
hash_mem()
static int hash_mem (int a, DTYPE dtype, int parent, int mem) static
Definition at line 432 of file ast.c.
References a, ADD_NODE, astb, HSH_3, ASTB::hshtb, mem(), and parent.
Referenced by mk_member().
hash_paren()
static int hash_paren (int a, DTYPE dtype, int lop) static
Definition at line 375 of file ast.c.
References a, ADD_NODE, astb, HSH_2, and ASTB::hshtb.
Referenced by mk_paren().
hash_subscr()
static int hash_subscr (int a, DTYPE dtype, int lop, int asd) static
Definition at line 412 of file ast.c.
References a, ADD_NODE, astb, HSH_3, and ASTB::hshtb.
Referenced by mk_subscr_copy().
hash_substr()
static int hash_substr (int a, DTYPE dtype, int lop, int left, int right) static
Definition at line 492 of file ast.c.
References a, ADD_NODE, astb, HSH_4, and ASTB::hshtb.
Referenced by mk_substr().
hash_sym()
static int hash_sym (int a, DTYPE dtype, int sptr) static
Definition at line 315 of file ast.c.
References a, ADD_NODE, astb, HSH_2, ASTB::hshtb, and sptr.
Referenced by mk_cnst(), mk_cval1(), mk_id_noshape(), and mk_label().
hash_triple()
static int hash_triple (int a, int lb, int ub, int stride) static
Definition at line 472 of file ast.c.
References a, ADD_NODE, astb, HSH_3, ASTB::hshtb, lb, stride, and ub.
Referenced by mk_triple().
hash_unop()
static int hash_unop (int a, DTYPE dtype, int lop, int optype) static
Definition at line 334 of file ast.c.
References a, A_OPTYPEG, A_OPTYPEP, ADD_NODE, astb, HSH_3, ASTB::hshtb, and optype().
Referenced by mk_unop().
hash_val()
static INT hash_val (int a, int hw3, int hw4, int hw5, int hw6) static
Definition at line 295 of file ast.c.
References a, and HSHSZ.
hex2char()
static int hex2char (INT * hexval) static
Convert doubleword hex/octal value to a character.
Parameters
hexval two-element array of [0] msw, [1] lsw
Returns
the symbol table entry of the character constant
The conversion is performed by copying an 8-bit value (2 hex digits) to a character position which is endian-dependent. The endian-dependency is handled as if the hex value is "equivalenced" with a character value of the same length. The length of the character constant returned is determined by the magnitude of the hex values (leading 0's are not converted). Note that this conversion returns the same character value in context of an assignment or data initialization.
We may be incompatible with other implementations with respect to data initialization:
if the value is smaller than the char item being initialized, the conversion process results in appending blanks; other systems may pad with 'nulls'
if the value is larger, truncation of the least significant characters ("rightmost") occurs; other systems truncate the most significant characters ("leftmost").
Definition at line 9648 of file ast.c.
References buf, FLG::endian, flg, getstring(), i, len, p, and val.
Referenced by cngcon().
hex2nchar()
static int hex2nchar (INT * hexval) static
Definition at line 9713 of file ast.c.
References buf, FLG::endian, flg, getstring(), i, len, p, and val.
Referenced by cngcon().
holtonum()
void holtonum (char * cp, INT * num, int bc)
Convert a hollerith constant to a numeric value.
Parameters
cp character pointer to hollerith character string
num result of conversion of hollerith to numeric
bc byte count of destination area i.e. *1, *2, *4, *8 or *16
Definition at line 7958 of file ast.c.
References buf, cp, FLG::endian, errwarn(), flg, i, num, and p.
Referenced by cngcon(), conv_bint_ilm(), conv_int8_ilm(), conv_int_ilm(), and conv_sint_ilm().
increase_shape()
int increase_shape (int o_shape, int astdim, int ub, int after)
Duplicate a shape descriptor increasing its rank at the given dimension.
Parameters
o_shape old shape
astdim ast of dimension to add
ub ast of upper bound of dim at astdim
after std after which code is produced to create the bounds descriptor (if dim is not a constant)
Definition at line 2562 of file ast.c.
References a, add_shape_rank(), add_shape_spec(), astb, ASTB::bnd, dim, ASTB::dtype, error(), gbl, get_int_cval(), getccsym(), i, mk_id(), mk_shape(), ndim, NULL, ASTB::one, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, sptr, and ub.
Referenced by ref_pd().
insert_stmt_after()
void insert_stmt_after (int std, int stdafter)
Definition at line 3962 of file ast.c.
References std, STD_FINDEX, STD_LINENO, STD_NEXT, and STD_PREV.
Referenced by add_stmt_after(), move_range_after(), and move_stmts_after().
insert_stmt_before()
void insert_stmt_before (int std, int stdbefore)
Definition at line 3976 of file ast.c.
References std, STD_FINDEX, STD_LINENO, STD_NEXT, and STD_PREV.
Referenced by add_stmt(), add_stmt_before(), move_range_before(), and move_stmts_before().
is_array_ast()
LOGICAL is_array_ast (int ast)
Definition at line 9768 of file ast.c.
References ASD_NDIM, ASD_SUBS, ast, FALSE, get_ast_dtype(), is_array_ast(), is_array_dtype(), is_array_sptr(), j, resolve_ast_alias(), and TRUE.
Referenced by has_vector_subscript_ast(), and is_array_ast().
is_data_ast()
LOGICAL is_data_ast (int ast)
Definition at line 9825 of file ast.c.
References ast, DTY, FALSE, is_data_ast(), is_procedure_ptr(), resolve_ast_alias(), and TRUE.
Referenced by is_associatable_variable_ast(), and is_data_ast().
is_iso_c_funloc()
int is_iso_c_funloc (int ast)
Check if this AST is an intrinsic call to c_funloc.
Definition at line 7891 of file ast.c.
References A_OPTYPEG, and ast.
Referenced by is_iso_cloc(), and ref_intrin_subr().
is_iso_c_loc()
int is_iso_c_loc (int ast)
Check if this AST is an intrinsic call to c_loc.
Definition at line 7884 of file ast.c.
References A_OPTYPEG, and ast.
Referenced by cngshape(), is_iso_cloc(), and ref_intrin_subr().
is_iso_cloc()
int is_iso_cloc (int ast)
Check if the derived type tag is the iso_c_binding: c_ptr or c_funptr. These types are compatible with pointers.
Returns
true if this AST is an intrinsic call to c_loc or c_funcloc
Definition at line 7877 of file ast.c.
References ast, is_iso_c_funloc(), and is_iso_c_loc().
Referenced by chk_arguments(), func_call2(), handle_arguments(), lower_function(), lower_intrinsic(), ptrfunc_call(), ptrsubr_call(), rewrite_sub_args(), semant3(), and subr_call2().
is_variable_ast()
LOGICAL is_variable_ast (int ast)
Definition at line 9856 of file ast.c.
References ast, FALSE, is_procedure_ptr(), is_variable_ast(), and resolve_ast_alias().
Referenced by is_associatable_variable_ast(), and is_variable_ast().
is_whole_array()
LOGICAL is_whole_array (int arr_ast)
Definition at line 3561 of file ast.c.
References ADD_LWAST, ADD_LWBD, ADD_UPBD, assert, astb, bounds_match(), FALSE, i, ASTB::i1, interr(), ndim, rank_of_sym(), SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, sptr, stride, and TRUE.
Referenced by eliminate_sect(), make_sec_ast(), make_sec_from_ast_chk(), make_simple_template_from_ast(), and transform_section_arg().
is_whole_dim()
LOGICAL is_whole_dim (int arr_ast, int i)
Determine if array arr_ast covers all extent at dim i.
For example, on a(1,:) return true for second dim.
Definition at line 3498 of file ast.c.
References AD_DPTR, AD_LWAST, AD_UPAST, ASD_SUBS, assert, astb, ASTB::bnd, check_member(), FALSE, i, ASTB::i1, lb, memsym_of_ast(), ASTB::one, sptr, st, sub, and TRUE.
Referenced by contiguous_array_section(), contiguous_section(), contiguous_section_array(), and continuous_section().
lbound_of_shape()
int lbound_of_shape (int shape, int dim)
Get the lower bound of a shape descriptor.
Parameters
shape shape descriptor
dim which dimension (0 based)
Returns
an ast if the lower bound is a constant; otherwise, return 0.
Definition at line 2743 of file ast.c.
References astb, ASTB::bnd, dim, get_isz_cval(), lb, SHD_LWB, SHD_UPB, ub, and ASTB::zero.
Referenced by ast_rewrite(), mk_shape_intrin(), mk_ulbound_intrin(), and ref_pd().
left_array_symbol()
int left_array_symbol (int ast)
Return the leftmost array symbol.
for a%b(i)%c%d(j)%e, it will return b
for a(i)%d(j), it will return a
for a(i)%d, it will return a
for a%b%c%d(i), it will return d
for scalar a%b, it will return a
Definition at line 3184 of file ast.c.
References a, ast, DTY, FLANG_FALLTHROUGH, interr(), and sptr.
Referenced by canonical_conversion(), eliminate_copy(), eliminate_gather(), eliminate_shift(), eliminate_start(), forall_lhs_indirection(), forall_with_mask(), is_same_descr_for_bnds(), and same_forall_bnds().
left_nonscalar_subscript_ast()
int left_nonscalar_subscript_ast (int ast)
This routine is similar to left_subscript_ast except it returns the leftmost non-scalar subscript.
For a(1)%b(i) return b(i)
Definition at line 3292 of file ast.c.
References ASD_NDIM, ASD_SUBS, ast, DTY, FLANG_FALLTHROUGH, i, interr(), ndim, sptr, and sub.
Referenced by process_lhs_sub().
left_subscript_ast()
int left_subscript_ast (int ast)
Return the AST of the leftmost A_SUBSCR:
For a%b(i)%c%d(j)%e, it will return the AST of a%b(i)
For a(i)%d(j), it will return the AST of a(i)
For a(i)%d, it will return the AST of a(i)
For a%b%c%d(i), it will return a%b%c%d(i)
For scalar a%b, it will return a
Definition at line 3239 of file ast.c.
References ast, DTY, FLANG_FALLTHROUGH, interr(), and sptr.
Referenced by canonical_conversion(), conv_forall(), eliminate_gather(), eliminate_shift(), eliminate_start(), fix_guard_forall(), forall_lhs_indirection(), lhs_dim(), process_lhs_sub(), and same_forall_bnds().
memsym_of_ast()
int memsym_of_ast (int ast)
Like sym_of_ast(), but for a member, returns the sptr of the member itself, not its parent.
Definition at line 3011 of file ast.c.
References a, ast, STB::i0, interr(), and stb.
Referenced by _constructf90(), _is_another_shift(), _pgi_element_size(), _pgi_kind(), add_ptr_assign(), assign_bounds(), ast_has_allocatable_member(), bld_lhs(), bld_use(), build_allocation_item(), build_conformable_func_node(), build_poly_func_node(), build_sdsc_node(), check_derived_type_array_section(), check_doconcurrent_ast(), check_pointer_type(), check_subprogram(), chk_arguments(), collapse_arrays(), component_init_allocd_auto(), contiguous_section(), conv_forall(), convert_template_instance(), eliminate_redundant(), emit_gatherx(), emit_get_scalar(), emit_overlap(), emit_scatterx_gatherx(), emit_sum_scatterx(), fix_proc_pointer_call(), func_call(), func_call2(), gen_alloc_mbr(), gen_alloc_mem_initialize_for_sym2(), gen_automatic_reallocation(), gen_bnd_assn(), gen_bounds_assignments(), gen_contig_check(), gen_dealloc_mbr(), gen_set_type(), generate_gather(), generate_get_scalar(), generate_hcycliclp(), generate_hlocalizebnds(), get_defined_io_call(), get_descr_or_placeholder_arg(), handle_allocatable_members(), handle_arguments(), init_sptr_w_acl(), inline_reduction_f90(), inline_shifts(), is_deferlenchar_ast(), is_deferlenchar_dtype(), is_descr_expression(), is_ptr_arg(), is_ptrast_arg(), is_same_mask(), is_shift_conflict(), is_use_lhs_final(), is_whole_dim(), lower_check_ast(), lower_function(), lower_put_datatype(), lower_stmt(), markmodified(), mk_extent(), mk_mem_ptr_shape(), mk_offset(), mk_shared_extent(), mklvalue(), mkvarref(), print_ast(), printastref(), promote_assumsz_arg(), ptrfunc_call(), ref_pd(), ref_pd_subr(), remove_parent_from_ast(), replace_arg(), rewrite_allocatable_assignment(), rewrite_block_where(), rewrite_calls(), rewrite_deallocate(), rewrite_func_ast(), rewrite_inlined_args(), rewrite_sub_args(), semant2(), semant3(), set_descr_tag(), simply_contiguous(), sptr_of_subscript(), stride_1_dummy(), stride_1_section(), subr_call2(), subst_lhs_arrfn(), subst_lhs_pointer(), tkr_match(), transform_associated(), transform_call(), valid_kind_parm_expr(), and validate_atomic_expr().
mk_alias()
void mk_alias (int ast, int a_cnst)
Create an alias of ast if it isn't a constant AST. Its alias field will be set to the ast 'a_cnst'.
Definition at line 676 of file ast.c.
References ast.
Referenced by cngtyp2(), semant1(), and semant2().
mk_argt()
int mk_argt (int cnt)
Create an ARGT.
Parameters
cnt number of arguments in the ARGT
Definition at line 4114 of file ast.c.
References argt, ARGT_CNT, astb, cnt, errfatal(), MAX_NMPTR, NEED, and NULL.
Referenced by __gen_conditional_dealloc(), _constructf90(), _linearize(), _sect(), add_ptr_assign(), ast_rewrite(), begin_call(), build_conformable_func_node(), build_poly_func_node(), check_pointer_type(), conv_deallocate(), conv_forall(), convert_subscript_in_expr(), copy_arg_to_seq_tmp(), copy_inargs(), emit_alnd(), emit_fl(), emit_get_scalar_sub(), emit_kopy_in(), emit_permute_section(), emit_scatterx_gatherx(), emit_secd(), emit_sum_scatterx(), extent(), fill_cyclic_k(), func_call2(), gen_allocated_check(), gen_automatic_reallocation(), gen_call_class_obj_size(), gen_conditional_alloc(), gen_contig_check(), gen_copy_out(), gen_finalization_for_sym(), gen_init_intrin_call(), gen_init_unl_poly_desc(), gen_islocal_index(), gen_localize_index(), gen_poly_element_arg(), gen_ptr_in(), gen_ptr_out(), generate_copy(), generate_gather(), generate_get_scalar(), generate_hcycliclp(), generate_hlocalizebnds(), genPolyAsn(), get_invoking_proc_desc(), handle_shift(), import(), init_derived_type(), init_sdsc(), init_sdsc_bounds(), inline_ast(), inline_reduction_f90(), inline_small_matmul(), make_sec_from_ast_chk(), make_simple_template_from_ast(), make_temp_descriptor(), matmul(), mk_merge(), mk_set_type_call(), mmul(), pointer_squeezer(), ptrfunc_call(), ptrsubr_call(), ref_intrin(), ref_intrin_subr(), ref_pd(), ref_pd_subr(), remove_parent_from_ast(), replace_vector_subscript(), reshape(), rewrite_allocatable_assignment(), rewrite_func_ast(), rewrite_sub_args(), semant3(), set_type_in_descriptor(), size_of_allocatable(), subr_call2(), trans_mkproc(), transform_associated(), transform_c_f_pointer(), transform_c_f_procpointer(), transform_call(), transform_elemental(), transform_merge(), transform_move_alloc(), transform_mvbits(), and transform_ptr().
mk_asd()
int mk_asd (int * subs, int numdim)
Definition at line 2068 of file ast.c.
References ASTB::asd, ASD_NDIM, ASD_NEXT, ASD_SUBS, assert, astb, ERR_Fatal, ERR_Severe, ASTB::hash, i, MAXSUBS, NEED, and sub.
Referenced by gen_dos_over_shape(), mk_subscr(), normalize_subscripts(), and subscript_allocmem().
mk_assn_stmt()
int mk_assn_stmt (int dest, int source, DTYPE dtype)
Definition at line 4308 of file ast.c.
References ast, dest, and mk_stmt().
Referenced by _constructf90(), _reshape(), _rewrite_scalar_fuctions(), add_auto_bounds(), add_bound_assignments(), add_private_allocatable(), add_ptr_assign(), alloc_char_temp(), allocate_array(), asn_sfuse(), assign(), assign_array_w_forall(), assign_bounds(), ast_rewrite(), bblock(), call_dtsfmt(), check_alloc_ptr_type(), chk_SIZE_var(), collapse_add(), collapse_begin(), collapse_expr(), collapse_index(), component_init_allocd_auto(), compute_size_ido(), construct_association(), conv_forall(), copy_arg_to_seq_tmp(), copy_back_to_replic_sect(), copy_desc_to_bnds_vars(), copy_inargs(), copy_replic_sect_to_tmp(), copy_scalar_intent_in(), copy_surrogate_to_bnds_vars(), do_dist_schedule(), do_distbegin(), do_lastval(), do_schedule(), emit_redim(), end_io_call(), fill_ast(), func_call2(), gen_alloc_dealloc(), gen_automatic_reallocation(), gen_bounds_assignments(), gen_defer_shape(), gen_derived_type_alloc_init(), gen_dtio_args(), gen_early_array_bnds(), gen_early_bnd_dependencies(), gen_early_str_len(), gen_kind_parm_assignments(), gen_lastval(), gen_ptr_in(), gen_set_len_ast(), generate_hcycliclp(), generate_hlocalizebnds(), get_subscripting_tmp(), handle_allocatable_members(), handle_dependence_ido(), handle_shift(), incr_tmp(), init_derived_type(), init_sptr_w_acl(), inline_ast(), inline_reduction_f90(), inline_RTE_set_type(), inline_shifts(), inline_small_matmul(), insert_assign(), lower_data_stmts(), mk_ptr_subscr(), mkexpr_assign_temp(), nml_emit_desc(), pointer_squeezer(), precompute_arg_intrin(), recurse_eoshift(), recurse_shift(), ref_pd(), ref_stfunc(), rewrite_allocatable_assignment(), rewrite_block_where(), rewrite_func_ast(), rewrite_intr_allocatable(), rewrite_sub_args(), save_clauses(), semant3(), semantio(), set_assumed_bounds(), set_descr_tag(), temp_type_descriptor(), tempify_ast(), transform_c_f_pointer(), and transform_call().
mk_atomic()
int mk_atomic (int stmt_type, int left, int right, DTYPE dtype)
Definition at line 540 of file ast.c.
References ast, and new_node().
Referenced by mk_atomic_read(), and rewrite_sub_ast().
mk_binop()
int mk_binop (int optype, int lop, int rop, DTYPE dtype)
Definition at line 689 of file ast.c.
References A_OPTYPEG, ast, astb, cmp64(), const_fold(), CONVAL2G, convert_int(), DT_INT, DT_ISINT, DTY, FALSE, FLANG_FALLTHROUGH, hash_binop(), ASTB::i0, ASTB::i1, interr(), STB::k0, STB::k1, MIN_INT64, mk_cnst(), mk_cval(), mk_unop(), negate_const(), OP_ADD, OP_DIV, OP_LAND, OP_LEQV, OP_LNEQV, OP_LOR, OP_MUL, OP_SUB, OP_XTOI, optype(), reduce_i8add(), reduce_iadd(), stb, tmp, TRUE, TY_INT8, and TY_LOG8.
Referenced by _constructf90(), _fam(), _linearize(), _PDsize(), _pghpf_bound(), _pghpf_size(), _ptrassign(), _reshape(), _RTE_ba(), _RTE_size(), _RTE_xb(), _sect(), _template(), _transform_func(), ad2ili(), add_auto_bounds(), add_bound_assignments(), add_iolptrs(), add_lbnd(), addcomponents(), assign_bounds(), ast_rewrite(), binop(), binop_init_list(), bld_ud(), build_array_ref(), build_array_reference(), check_pointer_type(), chk_constructor(), chksubstr(), collapse_add(), collapse_assignment(), collapse_begin(), collapse_index(), combine_fdiv(), common_rel(), compute_size_expr(), compute_size_ido(), conv_forall(), convert_subscript_in_expr(), copy_arg_to_seq_tmp(), copy_desc_to_bnds_vars(), copy_inargs(), copy_surrogate_to_bnds_vars(), cyclic_section(), dd_array_conflict(), diff_lbnd(), do_branch(), do_lastval(), emit_scatterx_gatherx(), end_lastprivate(), end_or_err(), extent_of_shape(), fill_argt_with_alnd(), fill_ast(), fill_cyclic_1(), fill_cyclic_k(), fill_pointer_array_dtype(), find_presence(), fixup_KIND_expr(), gen_allocate(), gen_automatic_reallocation(), gen_islocal_index(), gen_lastval(), gen_reduction(), get_all_descriptors(), get_ast_extents(), get_dobegin(), get_forall_subscr(), get_scalar_in_expr(), handle_dependence_ido(), handle_shift(), incr_tmp(), inline_ast(), inline_contig_check(), inline_hlocalizebnds(), inline_reduction_f90(), inline_shifts(), inline_small_matmul(), inline_spread_shifts(), insert_comm_before(), insert_forall_comm(), make_simple_template_from_ast(), mk_conformable_test(), mk_count_test(), mk_extent_expr(), mk_forall_sptr(), mk_mem_ptr_shape(), mk_mlpyr_expr(), mk_offset(), mk_poly_test(), mk_zbase_expr(), mkSub(), mmul_arg(), mulcomponents(), negatecomponent(), new_seq_temp_array(), normalize_forall(), normalize_subscript(), open_entry_guard(), opt_binop(), pointer_squeezer(), print_ast(), put_length_type_param(), reassoc_add(), ref_pd(), reference_for_temp(), remove_cond(), remove_parent_from_ast(), replace_arg(), replace_expr(), replace_sdsc_in_ast(), replace_vector_subscript(), rewrite_allocatable_assignment(), rewrite_block_forall(), rewrite_block_where(), rewrite_func_ast(), rewrite_sub_ast(), same_forall_size(), scalar_communication(), semant2(), semant3(), semantio(), set_assumed_bounds(), shape_comm_in_expr(), size_ast(), size_ast_of(), size_of_allocatable(), size_of_ast(), size_of_shape_dim(), size_shape(), string_expr_length(), sub_lbnd(), transform_all_call(), and transform_pure_function().
mk_bnd_ast()
int mk_bnd_ast (void)
Definition at line 3829 of file ast.c.
References atemps, getcctmp(), mk_id(), and XBIT.
Referenced by _mk_arrdsc(), _reshape(), deferred_to_pointer(), dtype_with_shape(), mk_defer_shape(), mk_extent(), and mk_shared_extent().
mk_bnd_int()
int mk_bnd_int (int expr)
Utility function to ensure that an expression has a type suitable for array bounds, DT_INT8 for -Mlarge_arrays, DT_INT otherwise.
Definition at line 7499 of file ast.c.
References astb, ASTB::bnd, ASTB::dtype, and mk_int().
Referenced by _mk_arrdsc(), fill_argt_with_alnd(), fixup_param_vars(), gen_localize_index(), generate_hcycliclp(), generate_hlocalizebnds(), init_sdsc_bounds(), lower_stmt(), make_sec_from_ast_chk(), make_simple_template_from_ast(), put_length_type_param(), ref_pd(), semant1(), set_assumed_bounds(), and size_of_dtype().
mk_cmplxc()
int mk_cmplxc (int lop, int rop, DTYPE dtype)
Definition at line 1328 of file ast.c.
References ast, DTY, hash_cmplxc(), and mkshape().
Referenced by fill_ast().
mk_cnst()
int mk_cnst (int cnst)
Make a constant AST given a constant symbol table pointer.
Definition at line 553 of file ast.c.
References ast, DTY, hash_sym(), and mkshape().
Referenced by _huge(), ast_cnst(), bld_ud(), ch_substring(), dinit_val(), eval_do_idx(), eval_init_op(), fill_adjustable_array_dtype(), fill_ast(), fill_fixed_array_dtype(), fixup_KIND_expr(), form_cmplx_const(), gen_dtio_arglist(), gen_dtio_args(), get_len_parm_by_number(), get_mp_bind_type(), lower_do_stmt(), lower_namelist_plists(), mk_binop(), mk_unop(), mkexpr1(), mkvarref(), mmul(), reduce_i8add(), ref_pd(), replace_parms(), semant1(), semant3(), semantio(), transform_call(), and transform_ptr().
mk_comstr()
int mk_comstr (char * str)
Definition at line 4093 of file ast.c.
References astb, COMSTR, mk_stmt(), NEED, str, and strlen().
Referenced by semant1().
mk_convert()
int mk_convert (int lop, DTYPE dtype)
Definition at line 1350 of file ast.c.
References ast, convert_cnst(), DT_ISINT, DTY, hash_conv(), and mkshape().
Referenced by _reshape(), _RTE_xb(), _simple_replacements(), _transform_func(), ad1ili(), ad2ili(), ast_rewrite(), build_array_ref(), cast_to_typeless(), chk_arguments(), chk_SIZE_var(), chksubstr(), cngtyp2(), convert_int(), convert_subscript_in_expr(), emit_scatterx_gatherx(), end_io_call(), fill_ast(), fixup_KIND_expr(), func_call2(), gen_dtio_arglist(), gen_dtio_args(), gen_early_bnd_dependencies(), gen_early_str_len(), gen_lastval(), gen_ptr_in(), get_scalar_in_expr(), inline_ast(), inline_reduction_f90(), insert_comm_before(), insert_forall_comm(), lower_numelm(), MakeReplacement(), mk_size_intrin(), mk_ulbound_intrin(), mkSub(), mmul_arg(), normalize_forall(), pointer_squeezer(), put_adjarr_bounds(), ref_pd(), ref_pd_subr(), remove_parent_from_ast(), replace_arg(), replace_expr(), replace_vector_subscript(), rewrite_sub_ast(), scalar_communication(), search_idx(), semant2(), semantio(), shape_comm_in_expr(), size_ast(), size_ast_of(), size_shape(), transform_all_call(), and transform_pure_function().
mk_cval()
int mk_cval (INT v, DTYPE dtype)
Definition at line 565 of file ast.c.
References DTY, getcon(), mk_cval1(), TY_INT8, and TY_LOG8.
Referenced by _makezero(), _PDsize(), _pghpf_bound(), _pghpf_size(), _pgi_element_size(), _pgi_kind(), _repeat(), _reshape(), _RTE_ba(), add_cgoto(), add_equivalence(), add_padding(), add_ptr_assign(), add_reduce_descriptor(), ast_init(), ast_intr(), bblock(), binop(), build_allocation_item(), build_array_reference(), build_conformable_func_node(), ch_substring(), chk_unitid(), chksubstr(), cngcon(), compute_size_ido(), construct_acl_from_ast(), conv_deallocate(), copy_arg_to_seq_tmp(), dinit_data(), dinit_getval(), dinit_getval1(), emit_fl(), emit_kopy_in(), emit_sum_scatterx(), eval_init_op(), fill_cyclic_k(), fill_links_symbol(), fix_dtype(), gen_bounds_assignments(), gen_copy_out(), gen_derived_io(), gen_early_bnd_dependencies(), gen_early_str_len(), gen_islocal_index(), gen_ptr_in(), generate_gather(), getstring(), handle_shift(), hlv_getvsym(), init_derived_type(), init_intrin_type_desc(), inline_reduction_f90(), inline_shifts(), inline_small_matmul(), inline_spread_shifts(), lower_data_stmts(), make_alnd(), make_equiv_ss(), mk_binop(), mk_ceil_div(), mk_isz_cval(), mk_size(), mk_size_intrin(), mk_transfer_intrin(), mk_ulbound_intrin(), mk_unop(), mod_type(), nml_emit_desc(), open_entry_guard(), reduce_iadd(), ref_intrin(), ref_pd(), rewrite_allocatable_assignment(), rewrite_func_ast(), rw_array(), semant1(), semant2(), semant3(), semantio(), semsmp(), size_ast(), size_ast_of(), string_expr_length(), trans_mkproc(), and transform_c_f_pointer().
mk_cval1()
int mk_cval1 (INT v, DTYPE dtype)
Make a constant AST given the actual (single word) value or a constant symbol table pointer; determined by data type.
Definition at line 615 of file ast.c.
References ast, DTY, getcon(), hash_sym(), interr(), mkshape(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, and val.
Referenced by _constructf90(), _huge(), _makezero(), assign_cval(), ast_conval(), build_poly_func_node(), check_alloc_ptr_type(), check_pointer_type(), chk_kind_parm_set_expr(), chkopnds(), cngtyp2(), common_rel(), construct_association(), convert_cnst(), dinit_getval(), dinit_getval1(), do_reduction(), end_lastprivate(), eval_do(), eval_do_idx(), fill_links_symbol(), gen_contig_check(), gen_init_unl_poly_desc(), gen_kind_parm_assignments(), gen_poly_element_arg(), gen_reduction(), genPolyAsn(), get_keyword_components(), get_param_alias_const(), log_negation(), mk_cval(), mk_isz_cval(), mk_smallest_val(), mmul(), ref_array(), ref_intrin(), ref_pd(), rewrite_allocatable_assignment(), semant1(), semant2(), semant3(), set_descr_tag(), set_type_in_descriptor(), and temp_type_descriptor().
mk_default_int()
int mk_default_int (int expr)
Utility function to ensure that an expression has type DT_INT (default integer).
Definition at line 7490 of file ast.c.
References DT_INT, and mk_int().
Referenced by emit_get_scalar_sub(), fill_cyclic_k(), gen_islocal_index(), generate_get_scalar(), generate_hcycliclp(), and inline_hlocalizebnds().
mk_duplicate_ast()
int mk_duplicate_ast (int ast)
Definition at line 10003 of file ast.c.
References ast, astb, and mk_stmt().
mk_extent()
int mk_extent (int lb, int ub, int dim)
Return an ast to reference the extent.
Definition at line 2854 of file ast.c.
References ad_val_of(), astb, ASTB::bnd, dim, ASTB::dtype, extent(), get_extent(), lb, memsym_of_ast(), mk_bnd_ast(), mk_isz_cval(), ASTB::one, sptr, and ub.
Referenced by allocate_array(), dtype_with_shape(), fix_dtype(), gen_bnd_assn(), inline_reduction_f90(), mk_forall_sptr(), mkarg(), mkexpr1(), new_seq_temp_array(), ref_pd(), and rewrite_func_ast().
mk_extent_expr()
int mk_extent_expr (int lb, int ub)
Return an ast that computes the extent (from the lb and ub).
Definition at line 2832 of file ast.c.
References ad_val_of(), astb, ASTB::bnd, ASTB::dtype, lb, mk_binop(), mk_isz_cval(), ASTB::one, OP_ADD, OP_SUB, and ub.
Referenced by add_auto_bounds(), add_bound_assignments(), build_conformable_func_node(), copy_desc_to_bnds_vars(), copy_surrogate_to_bnds_vars(), gen_allocate(), gen_defer_shape(), mk_shared_extent(), and mmul_arg().
mk_fake_iostat()
int mk_fake_iostat (void)
Definition at line 606 of file ast.c.
References astb, ASTB::bnd, ASTB::dtype, get_temp(), and mk_id().
Referenced by semantio().
mk_func_node()
int mk_func_node (int ast_type, int func_ast, int paramct, int argt)
Definition at line 4286 of file ast.c.
References A_ARGCNTP, argt, ARGT_ARG, ast, ast_type, i, and new_node().
Referenced by __gen_conditional_dealloc(), _constructf90(), _linearize(), _sect(), add_ptr_assign(), ast_rewrite(), build_conformable_func_node(), build_poly_func_node(), check_pointer_type(), conv_deallocate(), conv_forall(), convert_subscript_in_expr(), copy_arg_to_seq_tmp(), copy_inargs(), emit_alnd(), emit_fl(), emit_kopy_in(), emit_secd(), extent(), func_call2(), gen_allocated_check(), gen_automatic_reallocation(), gen_call_class_obj_size(), gen_conditional_alloc(), gen_contig_check(), gen_finalization_for_sym(), gen_init_intrin_call(), gen_init_unl_poly_desc(), gen_islocal_index(), gen_localize_index(), gen_null_intrin(), gen_poly_element_arg(), gen_ptr_in(), gen_ptr_out(), generate_copy(), generate_gather(), genPolyAsn(), get_invoking_proc_desc(), handle_shift(), init_derived_type(), init_sdsc(), init_sdsc_bounds(), inline_ast(), inline_reduction_f90(), inline_small_matmul(), inline_spread_shifts(), make_sec_from_ast_chk(), make_simple_template_from_ast(), make_temp_descriptor(), matmul(), mk_merge(), mk_set_type_call(), mmul(), pointer_squeezer(), ptrfunc_call(), ptrsubr_call(), ref_intrin(), ref_pd(), replace_memsym_of_ast(), replace_vector_subscript(), reshape(), rewrite_allocatable_assignment(), rewrite_func_ast(), semant3(), semantio(), set_type_in_descriptor(), size_of_allocatable(), subr_call2(), trans_mkproc(), transform_associated(), transform_c_f_pointer(), transform_c_f_procpointer(), transform_call(), transform_elemental(), transform_merge(), transform_move_alloc(), transform_mvbits(), and transform_pure_function().
mk_id()
int mk_id (int id)
Definition at line 512 of file ast.c.
References ast, mk_id_noshape(), and mkshape().
Referenced by __gen_conditional_dealloc(), _constructf90(), _cr_nme(), _linearize(), _linearize_func(), _makezero(), _PDsize(), _ptrassign(), _reshape(), _rewrite_scalar_fuctions(), _sect(), add_assign_firstprivate(), add_firstprivate_assn(), add_iolptrs(), add_p_dealloc_item(), add_private_allocatable(), add_ptr_assign(), add_ptr_assignment(), add_reduce_descriptor(), add_spread_descriptor(), addssassignments(), alloc_char_temp(), allocate_aligned(), allocate_array(), allocate_one_auto(), asn_sfuse(), assign_array_w_forall(), assign_pointer(), assign_scalar(), ast_ioret(), ast_rewrite(), at_local_mode(), bblock(), begin_call(), bld_lhs(), bld_ud(), bld_use(), bounds_depends(), build_conformable_func_node(), build_do_init(), build_poly_func_node(), build_sdsc_node(), call_dtsfmt(), canonical_conversion(), ch_substring(), check_alloc_ptr_type(), check_dependence_ido(), check_pointer_type(), chk_fmtid(), chk_struct_constructor(), collapse_add(), collapse_arrays(), collapse_begin(), collapse_expr(), collapse_index(), component_init_allocd_auto(), compute_size_ido(), construct_association(), constructf90(), conv_allocate(), conv_deallocate(), conv_forall(), convert_subscript(), convert_template_instance(), convert_to_block_forall(), copy_arg_to_seq_tmp(), copy_inargs(), copy_replic_sect_to_tmp(), copy_scalar_intent_in(), copy_section_temp_before(), copy_to_scalar(), dealloc_tmp(), deallocate_privates(), decl_private_sym(), defined_operator(), dinit_constructor(), do_begin(), do_change_mk_id(), do_dist_schedule(), do_distbegin(), do_lastval(), do_parbegin(), do_schedule(), do_simdbegin(), eliminate_extra_idx(), emit_alnd(), emit_copy_section(), emit_fl(), emit_get_scalar(), emit_get_scalar_sub(), emit_kopy_in(), emit_overlap(), emit_permute_section(), emit_redim(), emit_scalar_kopy_in(), emit_scatterx_gatherx(), emit_secd(), emit_sum_scatterx(), end_association(), end_lastprivate(), enter_local_mode(), evl_kwd_args(), exit_local_mode(), extent(), fill_adjustable_array_dtype(), fill_argt_with_alnd(), fill_ast(), fill_cyclic_k(), fill_links_symbol(), find_descrs(), find_presence(), fix_dtype(), fix_proc_pointer_call(), fix_type_param_members(), fixup_KIND_expr(), forall_make_same_idx(), func_call2(), gatherx_temp_before(), gen_alloc_dealloc(), gen_alloc_mem_initialize_for_sym2(), gen_allocatable_result(), gen_allocated_check(), gen_and_assoc_tmp_ptr(), gen_array_result(), gen_automatic_reallocation(), gen_call_class_obj_size(), gen_char_result(), gen_conditional_alloc(), gen_conditional_dealloc_for_sym(), gen_contig_check(), gen_copy_out(), gen_dealloc_etmps(), gen_dealloc_for_sym(), gen_defer_shape(), gen_derived_arr_init(), gen_derived_io(), gen_derived_type_alloc_init(), gen_dinit(), gen_dos_over_shape(), gen_dtio_arglist(), gen_dtio_args(), gen_dtsfmt_args(), gen_early_bnd_dependencies(), gen_early_str_len(), gen_finalization_for_sym(), gen_init_intrin_call(), gen_init_unl_poly_desc(), gen_islocal_index(), gen_kind_parm_assignments(), gen_lastval(), gen_localize_index(), gen_null_intrin(), gen_pointer_result(), gen_poly_element_arg(), gen_ptr_in(), gen_ptr_out(), gen_set_len_ast(), gen_set_type(), gen_vlist(), generate_copy(), generate_gather(), generate_get_scalar(), generate_hcycliclp(), generate_hlocalizebnds(), generate_sect(), generic_func(), genPolyAsn(), get_charintrin_temp(), get_defined_io_call(), get_descr_arg(), get_header_member(), get_header_member_with_parent(), get_invoking_proc_desc(), get_len_of_deferchar_ast(), get_len_parm_by_number(), get_param_alias_const(), get_parm_ast(), get_per_dim_member(), get_sdsc_ast(), get_subscripting_tmp(), get_temp_forall2(), handle_allocatable_members(), handle_dependence_ido(), handle_seq_section(), handle_shift(), increase_shape(), init_derived_type(), init_intrin_type_desc(), init_sdsc(), init_sdsc_bounds(), init_sdsc_from_dtype(), init_sptr_w_acl(), inline_ast(), inline_reduction_f90(), inline_RTE_set_type(), inline_shifts(), inline_small_matmul(), is_fusable(), is_idx(), is_intrinsic_opr(), is_invariant_base(), is_same_secd(), lower_data_stmts(), lower_sptr(), lower_stmt(), make_sec_ast(), make_sec_from_ast_chk(), make_simple_template_from_ast(), make_temp_descriptor(), makezero(), markmodified(), matmul(), merge(), misc_checks(), mk_allocate_scalar(), mk_bnd_ast(), mk_component_ast(), mk_deallocate_scalar(), mk_descr_from_section(), mk_descr_id(), mk_fake_iostat(), mk_firstprivate(), mk_mem_ptr_shape(), mk_merge(), mk_ptr_subscr(), mk_result_sptr(), mk_set_type_call(), mk_shared_bnd_ast(), mkarg(), mkexpr1(), mkexpr2(), mkexpr_assign_temp(), mklabelvar(), mklvalue(), mkmember(), mkvarref(), mmul(), move_alloc_arg(), mp_create_bscope(), newargs_for_entry(), nml_emit_desc(), normalize_forall_array(), normalize_forall_triplet(), nullify_member(), nullify_member_after(), open_entry_guard(), opt_allocate(), outvalue_hcycliclp(), outvalue_hlocalizebnds(), pghpf_type(), pointer_squeezer(), position_finder(), precompute_arg_intrin(), presence_test(), print_ast(), print_refsym(), propagatemodified(), ptrfunc_call(), ptrsubr_call(), put_data(), put_forall_pcalls(), put_length_type_param(), redimension(), reduc_shape(), ref_array(), ref_intrin(), ref_intrin_subr(), ref_pd(), ref_pd_subr(), ref_stfunc(), reference_for_temp(), remove_from_scalar_subscript(), remove_function_common_from_scalar_subscript(), remove_parent_from_ast(), rename_forall_list(), replace_arguments(), replace_memsym_of_ast(), replace_parms(), replace_sdsc_in_ast(), replace_sptr_in_ast(), reshape(), restore_clauses(), rewrite_acl(), rewrite_allocatable_assignment(), rewrite_ast_with_new_dtype(), rewrite_block_where(), rewrite_cptr_references(), rewrite_deallocate(), rewrite_func_ast(), rewrite_inlined_args(), rewrite_intr_allocatable(), rewrite_sub_args(), same_forall_bnds(), save_clauses(), semant1(), semant2(), semant3(), semantio(), semsmp(), sequentialize(), set_assumed_bounds(), set_assumsz_bound(), set_mp_loop_var(), set_type_in_descriptor(), simple_reference_for_temp(), size_ast(), size_ast_of(), size_of_allocatable(), size_of_dtype(), string_expr_length(), subr_call2(), symvalue(), temp_copy_section(), temp_gatherx(), temp_type_descriptor(), tempify_ast(), tmp_assign(), trans_mkproc(), transform_all_call(), transform_associated(), transform_c_f_pointer(), transform_c_f_procpointer(), transform_call(), transform_elemental(), transform_merge(), transform_move_alloc(), transform_mvbits(), transform_ptr(), transform_section_arg(), transform_wrapup(), update_arrdsc(), and wrap_symbol().
mk_id_noshape()
int mk_id_noshape (int id)
Definition at line 521 of file ast.c.
References ERR_Severe, hash_sym(), interr(), and stb.
Referenced by mk_id().
mk_init()
int mk_init (int left, DTYPE dtype)
Definition at line 530 of file ast.c.
References ast, and new_node().
Referenced by _makezero(), add_init(), ast_rewrite(), binop_init_list(), fill_ast(), and unop_init_list().
mk_int()
static int mk_int (int expr, DTYPE dt_needed) static
Definition at line 7465 of file ast.c.
References ast_intr(), convert_cnst(), DDTG, and dt.
Referenced by mk_bnd_int(), and mk_default_int().
mk_isz_cval()
int mk_isz_cval (ISZ_T v, DTYPE dtype)
Definition at line 594 of file ast.c.
References getcon(), ISZ_2_INT64, mk_cval(), mk_cval1(), and num.
Referenced by _constructf90(), _mk_arrdsc(), _ptrassign_set(), _sd_member(), _sect(), _template(), add_class_arg_descr_arg(), check_alloc_ptr_type(), chk_constructor(), compute_size_ido(), copy_desc_to_bnds_vars(), declare_type(), dtype_with_shape(), elem_size_of_ast(), emit_alnd(), emit_alnd_secd(), emit_kopy_in(), emit_overlap(), emit_permute_section(), emit_scatterx_gatherx(), emit_secd(), emit_sum_scatterx(), extent(), fill_argt_with_alnd(), first_element_from_section(), fixup_param_vars(), gen_localize_index(), gen_ptr_in(), generate_hcycliclp(), generate_hlocalizebnds(), get_all_descriptors(), get_csect_sym(), get_header_member(), get_header_member_with_parent(), get_len_of_deferchar_ast(), get_per_dim_member(), init_sdsc(), init_sdsc_bounds(), inline_contig_check(), make_sec_from_ast_chk(), make_simple_template_from_ast(), mk_extent(), mk_extent_expr(), mk_mem_ptr_shape(), mk_offset(), mk_shared_extent(), normalize_subscript(), permute_axis(), pghpf_type(), put_data(), put_length_type_param(), ref_pd(), search_idx(), semant1(), semantio(), set_assumed_bounds(), size_ast(), size_ast_of(), size_of_dtype(), stride_one(), sym_get_arg_sec(), sym_get_formal(), sym_get_sdescr(), sym_get_sec(), transform_associated(), and transform_ptr().
mk_label()
int mk_label (int lab)
Definition at line 683 of file ast.c.
References hash_sym().
Referenced by add_single_loop_exit(), bblock(), do_end(), end_or_err(), fill_ast(), fio_end_err(), remove_returns(), replace_label(), semant3(), and semsmp().
mk_largest_val()
int mk_largest_val (DTYPE dtype)
...
Definition at line 7558 of file ast.c.
References ast_intr().
Referenced by inline_reduction_f90().
mk_mem_ptr_shape()
int mk_mem_ptr_shape (int parent, int mem, DTYPE dtype)
Make shape ast(s) for an array reference off of a pointer in a derived type. Return the shape descriptor (SHD). Main difference is that the descriptor references need to be derived type components.
Definition at line 2304 of file ast.c.
References ADD_EXTNTAST, ADD_NUMDIM, add_shape_rank(), add_shape_spec(), ADD_UPAST, ASD_NDIM, ASD_SUBS, assert, astb, ASTB::bnd, DTY, ASTB::dtype, i, interr(), lbound_of(), lwb, MAXRANK, mem(), memsym_of_ast(), mk_binop(), mk_id(), mk_isz_cval(), mk_member(), mk_shape(), mk_subscr(), ASTB::one, OP_ADD, OP_SUB, parent, stride, and upb.
Referenced by gen_bounds_assignments(), handle_allocatable_members(), mk_member(), and rewrite_allocatable_assignment().
mk_member()
int mk_member (int parent, int mem, DTYPE dtype)
Definition at line 2220 of file ast.c.
References ast, complex_alias(), DDTG, DT_ISSCALAR, DTY, dtype_with_shape(), hash_mem(), mem(), mk_mem_ptr_shape(), mkshape(), and parent.
Referenced by _constructf90(), _linearize(), _ptrassign(), _transform_func(), add_dt_subscr(), allocate_aligned(), ast_rewrite(), build_allocation_item(), build_array_ref(), build_sdsc_node(), check_pointer_type(), conv_allocate(), convert_subscript(), fill_ast(), first_element_from_section(), fixup_KIND_expr(), func_call2(), gen_alloc_mem_initialize_for_sym2(), gen_bounds_assignments(), gen_kind_parm_assignments(), get_defined_io_call(), get_len_of_deferchar_ast(), get_parm_ast(), get_scalar_in_expr(), handle_allocatable_members(), init_sdsc(), init_sdsc_bounds(), insert_comm_before(), insert_forall_comm(), lower_stmt(), mk_mem_ptr_shape(), mkmember(), new_member_expr(), normalize_forall(), normalize_forall_array(), nullify_member(), nullify_member_after(), pointer_squeezer(), ptrfunc_call(), ref_pd(), remove_section(), remove_subscript_expressions(), replace_ast_subtree(), replace_memsym_of_ast(), replace_parms(), replace_vector_subscript(), rewrite_allocatable_assignment(), rewrite_ast_with_new_dtype(), rewrite_cptr_references(), rewrite_deallocate(), rewrite_sub_ast(), scalar_communication(), semant2(), shape_comm_in_expr(), subscript_allocmem(), transform_all_call(), transform_pure_function(), and wrap_symbol().
mk_merge()
int mk_merge (int tsource, int fsource, int mask, DTYPE resdt)
Definition at line 7564 of file ast.c.
References A_OPTYPEP, ARGT_ARG, DT_INT, func, mk_argt(), mk_func_node(), mk_id(), mkRteRtnNm(), RTE_mergei, RTE_mergei8, and sym_mkfunc_nodesc().
Referenced by _RTE_xb(), extent_of_shape(), and size_shape().
mk_mlpyr_expr()
int mk_mlpyr_expr (int lb, int ub, int mlpyr)
Return an ast that computes the multiplier from the multiplier, lower bound, and upper bound of the previous dimension.
Definition at line 2815 of file ast.c.
References ast, astb, ASTB::bnd, ASTB::dtype, lb, mk_binop(), ASTB::one, OP_ADD, OP_MUL, OP_SUB, and ub.
Referenced by _mk_arrdsc(), _reshape(), add_bound_assignments(), and set_assumed_bounds().
mk_offset()
int mk_offset (int astx, int resdtype)
Make an ast tree that computes the offset of the derived type or array element reference 'ast' from the start of the variable being referenced.
Definition at line 2449 of file ast.c.
References ADD_LWAST, ADD_MLPYR, ADD_NUMDIM, ASD_NDIM, ASD_SUBS, DTY, i, STB::i1, interr(), memsym_of_ast(), mk_binop(), mk_isz_cval(), mk_offset(), OP_ADD, OP_MUL, OP_SUB, size_ast(), sptr, ss, stb, and sub.
Referenced by mk_offset().
mk_paren()
int mk_paren (int lop, DTYPE dtype)
Definition at line 1339 of file ast.c.
References ast, and hash_paren().
Referenced by _transform_func(), ast_rewrite(), build_array_ref(), chkarg(), convert_subscript_in_expr(), fill_ast(), get_scalar_in_expr(), inline_ast(), insert_comm_before(), insert_forall_comm(), normalize_forall(), pointer_squeezer(), replace_expr(), replace_vector_subscript(), rewrite_sub_ast(), scalar_communication(), semant2(), shape_comm_in_expr(), transform_all_call(), and transform_pure_function().
mk_promote_scalar()
int mk_promote_scalar (int lop, DTYPE dtype, int shd)
Definition at line 1965 of file ast.c.
References ast, and hash_conv().
Referenced by chkshape(), cngshape(), convert_subscript_in_expr(), and rewrite_sub_ast().
mk_shape()
int mk_shape (void)
Definition at line 2399 of file ast.c.
References _shd, assert, astb, ASTB::hash, i, ndim, NEED, ASTB::shd, SHD_FILL, SHD_LWB, SHD_NDIM, SHD_NEXT, SHD_STRIDE, and SHD_UPB.
Referenced by _constructf90(), increase_shape(), mk_bounds_shape(), mk_mem_ptr_shape(), mk_subscr_copy(), mkshape(), new_shape(), reduc_shape(), and ref_pd().
mk_shared_bnd_ast()
int mk_shared_bnd_ast (int ast)
Create a shared bounds temporary.
Parameters
ast the AST of the bounds expression which will be stored in the temp
The same temp will be used for multiple uses of an expression.
Definition at line 3848 of file ast.c.
References ast, getcctmp(), mk_id(), and XBIT.
Referenced by _mk_arrdsc(), fix_array_fields(), and mk_shared_extent().
mk_shared_extent()
int mk_shared_extent (int lb, int ub, int dim)
Definition at line 2882 of file ast.c.
References ad_val_of(), astb, ASTB::bnd, dim, ASTB::dtype, extent(), get_extent(), lb, memsym_of_ast(), mk_bnd_ast(), mk_extent_expr(), mk_isz_cval(), mk_shared_bnd_ast(), ASTB::one, sptr, and ub.
Referenced by _mk_arrdsc(), and fixup_param_vars().
mk_smallest_val()
int mk_smallest_val (DTYPE dtype)
...
Definition at line 7505 of file ast.c.
References _huge(), DTYG, getcon(), mk_cval1(), mk_unop(), OP_SUB, tmp, TY_BINT, TY_DBLE, TY_INT, TY_INT8, TY_QUAD, TY_REAL, TY_SINT, val, and XBIT.
Referenced by inline_reduction_f90().
mk_std()
int mk_std (int ast)
Definition at line 3875 of file ast.c.
References A_STDP, ast, astb, errfatal(), MAXAST, NULL, std, STD_AST, and STG_NEXT.
Referenced by add_stmt(), add_stmt_after(), and add_stmt_before().
mk_stmt()
int mk_stmt (int stmt_type, DTYPE dtype)
Definition at line 3864 of file ast.c.
References ast, and new_node().
Referenced by __gen_conditional_dealloc(), _constructf90(), _RTE_ba(), _sect(), _template(), add_assign_firstprivate(), add_end_presence(), add_firstprivate_assn(), add_loop_hd(), add_pragma(), add_presence(), add_ptr_assign(), add_single_loop_exit(), add_taskloopreg(), addssassignments(), alloc_char_temp(), allocate_array(), allocate_lhs_if_needed(), assign_array_w_forall(), assign_scalar(), ast_rewrite(), ast_to_comment(), bblock(), begin_parallel_clause(), check_pointer_type(), close_entry_guard(), component_init_allocd_auto(), construct_association(), conv_forall(), convert_omp_workshare(), convert_template_instance(), convert_to_block_forall(), copy_arg_to_seq_tmp(), copy_forall(), copy_inargs(), copy_to_scalar(), delete_stmt(), do_bdistribute(), do_begin(), do_bteams(), do_copyin(), do_copyprivate(), do_distbegin(), do_end(), do_firstprivate(), do_map(), do_parbegin(), do_simdbegin(), emit_bcs_ecs(), emit_bpar(), emit_btarget(), emit_copy_section(), emit_epar(), emit_etarget(), emit_get_scalar_sub(), emit_kopy_in(), emit_overlap(), emit_permute_section(), emit_redim(), emit_scalar_kopy_in(), emit_scatterx_gatherx(), emit_sum_scatterx(), end_association(), end_lastprivate(), end_or_err(), end_parallel_clause(), end_reduction(), end_teams(), enter_lexical_block(), enter_local_mode(), exit_lexical_block(), exit_local_mode(), fill_ast(), fill_cyclic_1(), fill_cyclic_k(), fio_end_err(), forall_dependency(), forall_dependency_scalarize(), forall_lhs_indirection(), forall_with_mask(), func_call2(), gen_alloc_dealloc(), gen_allocated_check(), gen_automatic_reallocation(), gen_conditional_alloc(), gen_conditional_dealloc_for_sym(), gen_contig_check(), gen_copy_out(), gen_dealloc_for_sym(), gen_dealloc_if_allocated(), gen_do_ends(), gen_dos_over_shape(), gen_endsingle(), gen_finalization_for_sym(), gen_finalized_result(), gen_kind_parm_assignments(), gen_pdo(), gen_reduction(), gen_type_initialize_for_sym(), generate_copy(), generate_gather(), generate_get_scalar(), generate_hcycliclp(), generate_hlocalizebnds(), genPolyAsn(), handle_dependence_ido(), handle_shift(), init_derived_type(), inline_ast(), inline_contig_check(), inline_hlocalizebnds(), inline_reduction_f90(), inline_shifts(), inline_spread_shifts(), insert_endmask(), insert_mask(), make_forall(), make_sec_ast(), mk_allocate(), mk_allocate_scalar(), mk_assn_stmt(), mk_atomic_capture(), mk_atomic_update_binop(), mk_atomic_update_intr(), mk_atomic_write(), mk_comstr(), mk_conformable_test(), mk_dealloc_stub(), mk_deallocate(), mk_deallocate_scalar(), mk_duplicate_ast(), mk_firstprivate(), mk_loop_hdtl(), mk_poly_test(), mk_ptr_subscr(), mk_ztrips(), move_invar_std(), move_labels(), mp_create_bscope(), mp_create_escope(), normalize_forall(), normalize_forall_triplet(), open_entry_guard(), partition_blocks(), pointer_squeezer(), presence_test(), put_length_type_param(), redimension(), ref_array(), ref_intrin_subr(), ref_pd(), ref_pd_subr(), remove_parent_from_ast(), remove_returns(), rewrite_allocatable_assignment(), rewrite_block_forall(), rewrite_block_where(), rewrite_calls(), rewrite_deallocate(), rewrite_func_ast(), rewrite_where_expr(), rewritefg(), semant1(), semant3(), semantio(), semsmp(), sequentialize(), set_assumed_bounds(), set_assumsz_bound(), symvalue(), tmp_assign(), transform_all_call(), transform_elemental(), transform_merge(), transform_mvbits(), and unlnkilt().
mk_subscr()
int mk_subscr (int arr, int * subs, int numdim, DTYPE dtype)
Definition at line 1974 of file ast.c.
References mk_asd(), and mk_subscr_copy().
Referenced by _linearize(), _linearize_func(), _PDsize(), _pghpf_bound(), _pghpf_size(), _reshape(), _RTE_ba(), _sd_member(), _transform_func(), add_bounds_subscripts(), add_dt_subscr(), add_extent_subscripts(), add_iolptrs(), add_private_allocatable(), add_subscript(), allocate_array(), apply_shape_subscripts(), assign_array_w_forall(), ast_rewrite(), build_allocation_item(), build_array_reference(), canonical_conversion(), component_init_allocd_auto(), convert_subscript(), copy_arg_to_seq_tmp(), copy_inargs(), copy_section_temp_before(), eliminate_extra_idx(), eliminate_shift(), emit_overlap(), emit_scatterx_gatherx(), emit_sum_scatterx(), extent(), fill_ast(), first_element_from_section(), fixup_KIND_expr(), forall_2_sec(), gatherx_temp_before(), gen_bounds_assignments(), gen_defer_shape(), gen_derived_arr_init(), generate_sect(), get_allobnds(), get_header_member(), get_header_member_with_parent(), get_len_of_deferchar_ast(), get_per_dim_member(), handle_shift(), inline_ast(), inline_reduction_f90(), inline_spread_shifts(), insert_comm_before(), insert_forall_comm(), lower_data_stmts(), make_sec_from_ast_chk(), MakeReplacement(), mk_component_ast(), mk_mem_ptr_shape(), mklvalue(), mmul_arg(), nml_emit_desc(), normalize_forall(), normalize_forall_array(), opt_allocate(), permute_axis(), pghpf_type(), pointer_squeezer(), promote_assumsz_arg(), recurse_eoshift(), recurse_shift(), ref_array(), ref_pd(), reference_for_temp(), remove_subscript_expressions(), replace_arg(), replace_ast_subtree(), replace_expr(), replace_parms(), replace_vector_subscript(), rewrite_allocatable_assignment(), rewrite_ast_with_new_dtype(), rewrite_func_ast(), rewrite_sub_ast(), rewrite_subscr(), scalar_communication(), semantio(), simple_reference_for_temp(), subscript_allocmem(), subscript_lhs(), temp_copy_section(), temp_gatherx(), and transform_all_call().
mk_subscr_copy()
int mk_subscr_copy (int arr, int asd, DTYPE dtype)
Definition at line 1981 of file ast.c.
References add_shape_rank(), add_shape_spec(), ASTB::asd, ASD_NDIM, ASD_SUBS, assert, ast, astb, ASTB::bnd, complex_alias(), DDTG, STB::dt, DT_ISSCALAR, dtype_with_shape(), ERR_Fatal, hash_subscr(), i, lwb, mk_shape(), ASTB::one, SHD_LWB, SHD_STRIDE, SHD_UPB, stb, stride, sub, and upb.
Referenced by build_array_ref(), mk_subscr(), remove_parent_from_ast(), remove_section(), replace_sdsc_in_ast(), rewrite_deallocate(), rewrite_func_ast(), and subscript_allocmem().
mk_substr()
int mk_substr (int chr, int left, int right, DTYPE dtype)
Parameters
chr ast of character item being substring'd
left position of leftmost character
right position of rightmost character
dtype dtype
Definition at line 2122 of file ast.c.
References ast, and hash_substr().
Referenced by _transform_func(), ast_rewrite(), build_array_ref(), ch_substring(), chksubstr(), convert_subscript_in_expr(), fill_ast(), get_scalar_in_expr(), inline_ast(), insert_comm_before(), normalize_forall(), pointer_squeezer(), ref_pd(), remove_section(), replace_ast_subtree(), replace_vector_subscript(), rewrite_func_ast(), rewrite_sub_ast(), semantio(), and transform_all_call().
mk_triple()
int mk_triple (int lb, int ub, int stride)
Parameters
lb ast of lower bound
ub ast of upper bound
stride ast of stride Any of these asts can be 0
Definition at line 2106 of file ast.c.
References ast, hash_triple(), lb, stride, and ub.
Referenced by _transform_func(), add_bounds_subscripts(), add_extent_subscripts(), add_private_allocatable(), allocate_array(), allocate_one_auto(), apply_shape_subscripts(), ast_rewrite(), build_allocation_item(), canonical_conversion(), change_forall_triple(), convert_subscript(), copy_arg_to_seq_tmp(), copy_inargs(), eliminate_shift(), emit_overlap(), emit_scatterx_gatherx(), emit_sum_scatterx(), fill_ast(), fill_cyclic_k(), forall_2_sec(), forall_list_call(), gen_defer_shape(), get_allobnds(), get_forall_subscr(), get_scalar_in_expr(), get_subscr(), handle_shift(), inline_ast(), inline_reduction_f90(), inline_spread_shifts(), insert_comm_before(), make_forall(), mk_component_ast(), mk_forall_sptr(), mk_result_sptr(), normalize_forall_triplet(), opt_allocate(), outvalue_hcycliclp(), outvalue_hlocalizebnds(), pointer_squeezer(), promote_assumsz_arg(), ref_array(), reference_for_temp(), remove_subscript_expressions(), replace_arg(), rewrite_allocatable_assignment(), rewrite_sub_ast(), rewrite_triples(), scalar_communication(), semant3(), semantio(), transform_all_call(), and wrap_symbol().
mk_unop()
int mk_unop (int optype, int lop, DTYPE dtype)
...
Definition at line 1234 of file ast.c.
References ast, astb, CONVAL2G, convert_int(), DT_INT, DTY, hash_unop(), ASTB::i0, interr(), mk_cnst(), mk_cval(), negate_const(), OP_ADD, OP_LNOT, OP_LOC, OP_SUB, optype(), TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, and TY_SLOG.
Referenced by _constructf90(), _ptrassign(), _sect(), _transform_func(), ad1ili(), add_byval(), addcomponents(), ast_rewrite(), build_array_ref(), build_conformable_func_node(), build_poly_func_node(), byvalue_ref_arg(), check_alloc_ptr_type(), check_pointer_type(), collapse_assignment(), construct_intrinsic_acl(), convert_subscript_in_expr(), convert_template_instance(), copy_arg_to_seq_tmp(), emit_scatterx_gatherx(), end_or_err(), fill_ast(), fixup_KIND_expr(), gen_allocated_check(), gen_contig_check(), gen_init_unl_poly_desc(), gen_poly_element_arg(), gen_RTE_loc(), genPolyAsn(), get_scalar_in_expr(), init_derived_type(), init_intrin_type_desc(), inline_ast(), inline_reduction_f90(), inline_RTE_set_type(), insert_comm_before(), insert_forall_comm(), log_negation(), lower_data_stmts(), make_sec_from_ast_chk(), mk_binop(), mk_smallest_val(), mkSub(), move_alloc_arg(), mulcomponents(), negatecomponent(), nml_emit_desc(), normalize_forall(), opt_unop(), pointer_squeezer(), reduce_i8add(), reduce_iadd(), ref_pd(), remove_parent_from_ast(), replace_expr(), replace_vector_subscript(), rewrite_allocatable_assignment(), rewrite_block_where(), rewrite_sub_ast(), scalar_communication(), semant1(), semant2(), semant3(), semantio(), set_type_in_descriptor(), shape_comm_in_expr(), transform_all_call(), transform_c_f_pointer(), transform_pure_function(), and unop_init_list().
mk_zbase_expr()
int mk_zbase_expr (ADSC * ad)
Return the ast which computes the zero-base offset for an array.
Definition at line 2793 of file ast.c.
References a, AD_LWAST, AD_MLPYR, AD_NUMDIM, astb, ASTB::bnd, ASTB::dtype, i, mk_binop(), OP_ADD, and OP_MUL.
Referenced by _mk_arrdsc(), and _reshape().
mkshape()
int mkshape (DTYPE dtype)
Make shape ilm(s) from an array descriptor. Return the pointer to the the shape descriptor (SHD).
Definition at line 2272 of file ast.c.
References ADD_NUMDIM, add_shape_rank(), add_shape_spec(), ADD_UPAST, astb, ASTB::bnd, DTY, i, interr(), lbound_of(), lwb, mk_shape(), ASTB::one, stride, and upb.
Referenced by func_call2(), mk_cmplxc(), mk_cnst(), mk_convert(), mk_cval1(), mk_id(), mk_member(), mklvalue(), ptrfunc_call(), and ref_pd().
move_range_after()
void move_range_after (int sstd, int estd, int stdafter)
Definition at line 4028 of file ast.c.
References insert_stmt_after(), STD_NEXT, and STD_PREV.
Referenced by _constructf90(), and handle_dependence_ido().
move_range_before()
void move_range_before (int sstd, int estd, int stdbefore)
Definition at line 4008 of file ast.c.
References insert_stmt_before(), STD_NEXT, and STD_PREV.
Referenced by compute_size().
move_stmts_after()
void move_stmts_after (int std, int stdafter)
Definition at line 4063 of file ast.c.
References flg, insert_stmt_after(), remove_stmt(), set_par(), FLG::smp, std, and STD_NEXT.
Referenced by rewrite_allocatable_assignment().
move_stmts_before()
void move_stmts_before (int std, int stdbefore)
Definition at line 4048 of file ast.c.
References flg, insert_stmt_before(), remove_stmt(), set_par(), FLG::smp, std, and STD_NEXT.
Referenced by rewrite_allocatable_assignment().
negate_const()
INT negate_const (INT conval, DTYPE dtype)
Definition at line 8011 of file ast.c.
References const_fold(), CONVAL2G, DTY, getcon(), interr(), STB::k0, num, OP_SUB, result, stb, TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, xdneg(), xfneg(), and xqneg().
Referenced by const_eval(), eval_con_expr(), eval_init_op(), eval_KIND_expr(), mk_binop(), mk_unop(), reduce_i8add(), semant1(), and semant2().
new_node()
int new_node (int type)
Definition at line 270 of file ast.c.
References astb, errfatal(), MAXAST, NULL, STG_NEXT, and type.
Referenced by alloc2ast(), ast_rewrite(), begin_call(), define_stfunc(), emit_copy_section(), emit_get_scalar(), emit_overlap(), emit_scatterx_gatherx(), fill_ast(), lldbg_add_pending_import_entity(), lldbg_add_pending_import_entity_to_child(), make_sec_ast(), mk_atomic(), mk_func_node(), mk_init(), mk_stmt(), mod_init(), ref_stfunc(), semsmp(), temp_copy_section(), and temp_gatherx().
pass_sym_of_ast()
int pass_sym_of_ast (int ast)
Like sym_of_ast(), except for members it will return second to last parent member.
For example, pds%data%foo() returns data, pds%data returns pds.
This is used in computing the pass argument for a type-bound procedure expression.
Definition at line 2976 of file ast.c.
References a, ast, STB::i0, interr(), and stb.
Referenced by fix_proc_pointer_call(), func_call2(), handle_arguments(), inline_reduction_f90(), is_ptrast_arg(), lower_function(), semant2(), semant3(), subr_call2(), and transform_call().
procsym_of_ast()
int procsym_of_ast (int ast)
Like memsym_of_ast(), but for looking for the sptr of a procedure reference.
Definition at line 3109 of file ast.c.
References ast, STB::i0, interr(), and stb.
Referenced by _contains_any_call(), _rewrite_scalar_fuctions(), bld_ud(), elemental_func_call(), extract_shape_from_args(), gen_automatic_reallocation(), is_ptrast_arg(), lower_function(), lower_stmt(), pure_func_call(), put_call(), rewrite_func_ast(), rewrite_sub_args(), string_expr_length(), and transform_call().
pure_func_call()
LOGICAL pure_func_call (int func_ast)
Definition at line 3129 of file ast.c.
References FALSE, NULL, proc_arginfo(), procsym_of_ast(), and TRUE.
Referenced by pure_procedure().
put_memsym_of_ast()
void put_memsym_of_ast (int ast, int sptr)
Replace sptr of ast, if member, replace the sptr of the member.
Definition at line 3044 of file ast.c.
References a, ast, interr(), and sptr.
rank_of_ast()
int rank_of_ast (int ast)
Definition at line 2780 of file ast.c.
References ast, and SHD_NDIM.
Referenced by chksubscr(), ref_intrin(), ref_pd(), ref_pd_subr(), sum_scatter_args(), and valid_assign_pointer_types().
reduc_shape()
int reduc_shape (int o_shape, int astdim, int after)
Duplicate a shape descriptor excluding a given dimension.
Parameters
o_shape old shape
astdim ast of dimension to be excluded
after std after which code is produced to create the bounds descriptor (if dim is not a constant)
Definition at line 2505 of file ast.c.
References a, add_shape_rank(), add_shape_spec(), astb, ASTB::bnd, dim, ASTB::dtype, error(), gbl, get_int_cval(), getccsym(), i, mk_id(), mk_shape(), ndim, NULL, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, and sptr.
Referenced by inline_reduction_f90(), and ref_pd().
reduce_i8add()
static int reduce_i8add (int opnd, int con_st) static
Definition at line 1116 of file ast.c.
References A_OPTYPEG, assert, cmp64(), const_fold(), CONVAL2G, hash_binop(), STB::k0, MIN_INT64, mk_cnst(), mk_unop(), negate_const(), OP_ADD, OP_SUB, reduce_i8add(), stb, and tmp.
Referenced by mk_binop(), and reduce_i8add().
reduce_iadd()
static int reduce_iadd (int opnd, INT con) static
Definition at line 1010 of file ast.c.
References A_OPTYPEG, assert, astb, CONVAL2G, DT_INT, hash_binop(), ASTB::i0, mk_cval(), mk_unop(), OP_ADD, OP_SUB, reduce_iadd(), and tmp.
Referenced by mk_binop(), and reduce_iadd().
remove_stmt()
void remove_stmt (int std)
Definition at line 3988 of file ast.c.
References ERR_Severe, interr(), next, prev, std, STD_NEXT, and STD_PREV.
Referenced by delete_stmt(), move_stmts_after(), and move_stmts_before().
replace_ast_subtree()
int replace_ast_subtree (int original, int subtree, int replacement)
In original replace subtree with replacement.
Parameters
original a%b(i)%c%d(j)%e
subtree a%b(i)
replacement a%b(1:2)
Returns
New ast: a%b(1:2)%c%d(j)%e
Definition at line 3711 of file ast.c.
References ASD_NDIM, ASD_SUBS, ast, DDTG, FLANG_FALLTHROUGH, i, interr(), MAXRANK, mk_member(), mk_subscr(), mk_substr(), nsubs, p, and replace_ast_subtree().
Referenced by add_iolptrs(), canonical_conversion(), eliminate_shift(), emit_get_scalar(), handle_seq_section(), insert_comm_before(), replace_ast_subtree(), subscript_lhs(), and transform_section_arg().
replace_memsym_of_ast()
int replace_memsym_of_ast (int ast, SPTR sptr)
Generate a replacement AST with a new sptr for certain AST types.
This routine duplicates an AST and replaces its symbol table pointer with the caller specified symbol table pointer. This routine is typically used for replacing a generic type bound procedure with its resolved specific type bound procedure. This routine currently works for A_ID and A_MEM AST types.
Parameters
ast is the original AST that we want to duplicate.
sptr is the new symbol table pointer for the new AST.
Returns
the (new) replacement AST.
Definition at line 3087 of file ast.c.
References A_ARGCNTG, ast, FLANG_FALLTHROUGH, interr(), mk_func_node(), mk_id(), mk_member(), and sptr.
Referenced by func_call2(), gen_unique_func_ast(), and subr_call2().
reset_astli()
static void reset_astli (void) static
Definition at line 4181 of file ast.c.
References astb, and ASTLI_HEAD.
Referenced by ast_rewrite().
resolve_ast_alias()
int resolve_ast_alias (int ast)
Definition at line 9757 of file ast.c.
References ast.
Referenced by get_ast_asd(), get_ast_dtype(), get_ast_rank(), get_ast_sptr(), has_vector_subscript_ast(), is_array_ast(), is_data_ast(), and is_variable_ast().
rewrite_ast_with_new_dtype()
int rewrite_ast_with_new_dtype (int ast, DTYPE dtype)
Definition at line 9964 of file ast.c.
References ASD_SUBS, ast, get_ast_rank(), interr(), j, MAXRANK, mk_id(), mk_member(), mk_subscr(), rank, and sptr.
Referenced by semant3().
rw_ast_state()
void rw_ast_state (RW_ROUTINE , RW_FILE)
Definition at line 7583 of file ast.c.
References ASTB::asd, astb, ASTB::hash, ASTB::hshtb, RW_FD, RW_SCALAR, and ASTB::shd.
Referenced by rw_host_state().
set_par()
static void set_par (int std) static
Definition at line 3913 of file ast.c.
References std, STD_NEXT, STD_PAR, STD_PREV, and STD_TASK.
Referenced by add_stmt_after(), add_stmt_before(), move_stmts_after(), and move_stmts_before().
simply_contiguous()
LOGICAL simply_contiguous (int arr_ast)
Definition at line 3646 of file ast.c.
References contiguous_array_section(), DT_ISCMPLX, FALSE, memsym_of_ast(), sptr, sym_of_ast(), and TRUE.
Referenced by chk_arguments(), mmul_arg(), transform_ptr(), and valid_assign_pointer_types().
size_of_ast()
int size_of_ast (int ast)
Definition at line 3803 of file ast.c.
References ast, astb, ASTB::bnd, check_member(), ASTB::dtype, i, mk_binop(), ndim, ASTB::one, OP_ADD, OP_DIV, OP_MUL, OP_SUB, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, sz, t, and tmp.
Referenced by compute_size_expr(), mk_size_intrin(), ref_pd(), rw_array(), and semantio().
sptr_of_subscript()
int sptr_of_subscript (int ast)
Return sptr of an A_SUBSCR.
Definition at line 3154 of file ast.c.
References assert, ast, memsym_of_ast(), sptr, and sptr_of_subscript().
Referenced by conv_allocate(), convert_subscript(), copy_back_to_replic_sect(), copy_replic_sect_to_tmp(), count_nest(), eliminate_extra_idx(), emit_copy_section(), emit_get_scalar_sub(), emit_permute_section(), emit_sum_scatterx(), first_element_from_section(), forall_2_sec(), handle_seq_section(), inline_reduction_f90(), insert_forall_comm(), is_legal_lhs(), is_structured(), make_sec_ast(), make_sec_from_ast_chk(), make_simple_template_from_ast(), MakeReplacement(), markss(), no_comm_class(), overlap_class(), pointer_squeezer(), process_lhs_sub(), process_rhs_sub(), replace_expr(), rewrite_func_ast(), sptr_of_subscript(), tag_comms(), tag_forall_comm(), transform_call(), and transform_section_arg().
start_astli()
void start_astli (void)
Initialize for a new ast list.
The head of the list is stored in ast.astli.base[0].next and is accessed via the macro ASTLI_HEAD.
Call add_astli() to add items to the end of the list.
Definition at line 4153 of file ast.c.
References ASTLI_HEAD, and tail_astli.
Referenced by assign_array_w_forall(), ast_rewrite(), change_forall_triple(), import(), inline_spread_shifts(), make_forall(), normalize_forall_triplet(), pointer_squeezer(), semant3(), and semantio().
stride1_triple()
static LOGICAL stride1_triple (int triple) static
Definition at line 3410 of file ast.c.
References assert, astb, ASTB::bnd, FALSE, ASTB::i1, ASTB::one, and TRUE.
Referenced by contiguous_array_section().
sym_of_ast()
int sym_of_ast (int ast)
Like memsym_of_ast(), but for a member, returns the sptr of its parent, not the member.
Definition at line 2931 of file ast.c.
References ast, STB::i0, interr(), sptr, stb, and sym_of_ast2().
Referenced by add_iolptrs(), add_parent_to_bounds(), allocate_lhs_if_needed(), assign_intrinsic_to_pointer(), assign_pointer(), build_sdsc_node(), check_and_add_auto_dealloc_from_ast(), check_doconcurrent_ast(), chk_arguments(), chk_evar(), chk_unitid(), compute_size_expr(), Conflict_(), construct_association(), continuous_section(), conv_forall(), convert_omp_workshare(), convert_template_instance(), convert_to_block_forall(), dinit_data(), eval_const_array_section(), eval_sub_index(), export_ivl_ict(), extent_of(), find_base(), fixup_param_vars(), forall_dependency(), func_call2(), gen_alloc_dealloc(), gen_and_assoc_tmp_ptr(), gen_defer_shape(), gen_unique_func_ast(), genPolyAsn(), getast(), handle_arguments(), inline_reduction_f90(), is_allocatable_assign(), is_fusable(), is_same_mask(), lower_function(), lower_stmt(), lower_symbols(), make_forall(), mark_ivl_dinit(), mark_static(), markmodified(), mk_reshape_intrin(), mklvalue(), nml_emit_desc(), print_ast(), propagate_bound(), put_data_statement(), put_forall_pcalls(), put_kind_type_param(), record_barrier(), ref_pd(), ref_pd_subr(), replace_parms(), rewrite_all_shape(), rewrite_allocatable_assignment(), rewrite_calls(), rewrite_func_ast(), semant1(), semant2(), semant3(), semantio(), simply_contiguous(), size_ast(), size_ast_of(), size_of(), size_of_array(), subr_call2(), subst_lhs_arrfn(), transform_call(), and transform_section_arg().
sym_of_ast2()
static SPTR sym_of_ast2 (int ast) static
Definition at line 2943 of file ast.c.
References ast, and sym_of_ast2().
Referenced by ast_is_sym(), sym_of_ast(), and sym_of_ast2().
truncation_warning()
static void truncation_warning (int c) static
Definition at line 9576 of file ast.c.
References buf, ERR_Warning, error(), and gbl.
Referenced by cngcon().
ubound_of_shape()
int ubound_of_shape (int shape, int dim)
Get the upper bound of a shape descriptor.
Parameters
shape shape descriptor
dim which dimension (0 based)
Returns
an ast if the upper bound is a constant; otherwise, return 0.
Definition at line 2764 of file ast.c.
References astb, ASTB::bnd, dim, get_isz_cval(), lb, SHD_LWB, SHD_UPB, ub, and ASTB::zero.
Referenced by ast_rewrite(), mk_shape_intrin(), mk_ulbound_intrin(), and ref_pd().
unmk_argt()
void unmk_argt (int cnt)
Parameters
cnt Number of arguments in the ARGT
Definition at line 4134 of file ast.c.
References astb, and cnt.
Referenced by _linearize(), ast_rewrite(), inline_ast(), pointer_squeezer(), and replace_vector_subscript().
Variable Documentation
_postorder
ast_visit_fn _postorder static
Definition at line 5540 of file ast.c.
Referenced by _ast_trav(), ast_traverse(), and ast_traverse_all().
_preorder
ast_preorder_fn _preorder static
Definition at line 5539 of file ast.c.
Referenced by _ast_trav(), ast_traverse(), and ast_traverse_all().
struct { ... } _shd
Referenced by add_shape_rank(), add_shape_spec(), and mk_shape().
_visited
ast_visit_fn _visited static
Definition at line 4356 of file ast.c.
Referenced by _ast_trav(), ast_unvisit(), and ast_unvisit_norepl().
arg_count
int arg_count
Definition at line 4216 of file ast.c.
Referenced by mk_reshape_intrin(), mk_size_intrin(), and mk_ulbound_intrin().
arg_num
int arg_num
Definition at line 4214 of file ast.c.
Referenced by addag_llvm_argdtlist(), and get_argdt().
argt
int argt
Definition at line 4212 of file ast.c.
Referenced by __gen_conditional_dealloc(), _available(), _available_size(), _constructf90(), _linearize(), _olap_conflict(), _PDbound(), _PDsize(), _pghpf_bound(), _pghpf_size(), _pgi_element_size(), _pgi_kind(), _ptrassign(), _RTE_ba(), _RTE_bound(), _RTE_size(), _RTE_xb(), _sect(), _template(), _transform_func(), aliased_args(), assign(), assign_pointer(), ast_clear_repl(), ast_isparam(), ast_rewrite(), ast_trav_recurse(), bld_ud(), build_array_ref(), build_conformable_func_node(), build_poly_func_node(), check_doconcurrent_ast(), check_pointer_type(), check_subprogram(), compute_invariant(), Conflict_(), construct_arg_list(), construct_intrinsic_acl(), conv_deallocate(), conv_forall(), convert_subscript_in_expr(), decompose_expression(), early_specification_stmt_needed(), emit_alnd(), emit_fl(), emit_get_scalar_sub(), emit_kopy_in(), emit_permute_section(), emit_scatterx_gatherx(), emit_secd(), emit_sum_scatterx(), expr_dependent_check(), extent(), extract_shape_from_args(), fill_argt_with_alnd(), fill_ast(), fill_cyclic_k(), find_presence(), fixup_KIND_expr(), flowgraph(), func_call2(), gen_allocated_check(), gen_automatic_reallocation(), gen_call_class_obj_size(), gen_conditional_alloc(), gen_copy_out(), gen_early_bnd_dependencies(), gen_finalization_for_sym(), gen_init_intrin_call(), gen_init_unl_poly_desc(), gen_islocal_index(), gen_localize_index(), generate_copy(), generate_gather(), generate_get_scalar(), generate_hcycliclp(), generate_hlocalizebnds(), genPolyAsn(), get_scalar_in_expr(), init_derived_type(), init_sdsc(), init_sdsc_bounds(), inline_ast(), inline_spread_shifts(), insert_comm_before(), insert_forall_comm(), is_array_in_expr(), is_atomic_update_intr(), is_call_dependent(), is_dist_array_in_expr(), is_lonely_idx(), is_name_in_expr(), is_nonscalar_array_in_expr(), is_ptrast_arg(), is_same_mask(), lower_check_ast(), lower_no_subscr_chk(), make_sec_from_ast_chk(), make_simple_template_from_ast(), make_temp_descriptor(), markmodified(), missing_optionals(), mk_argt(), mk_func_node(), mk_reshape_intrin(), mk_shape_intrin(), mk_size_intrin(), mk_transfer_intrin(), mk_transpose_intrin(), mk_ulbound_intrin(), new_argt(), normalize_forall(), not_in_arrfn(), partition_blocks(), pointer_squeezer(), print_ast(), ptrfunc_call(), ptrsubr_call(), put_call(), put_call_comm(), put_forall_pcalls(), ref_intrin(), ref_intrin_subr(), ref_pd(), ref_pd_subr(), remove_alias(), remove_from_scalar_subscript(), remove_function_common_from_scalar_subscript(), replace_expr(), replace_formal_triples(), replace_parms(), replace_vector_subscript(), rewrite_allocatable_assignment(), rewrite_sub_args(), scalar_communication(), search_conform_array(), search_for_auto(), semant3(), set_type_in_descriptor(), shape_comm(), shape_comm_in_expr(), size_of_allocatable(), subr_call2(), subscr_dependent_check(), tag_forall_comm(), trans_mkproc(), transform_all_call(), transform_associated(), transform_call(), transform_ptr(), and transform_pure_function().
ast
int ast
Definition at line 4213 of file ast.c.
Referenced by __gen_conditional_dealloc(), _arg_forall_depnd(), _ast_trav(), _available(), _available_size(), _can_fold(), _check_clean(), _constructf90(), _contains_forall_index(), _cr_nme(), _dinit_acl(), _dump_std(), _dumpacl(), _find_assumshp_dep(), _find_lhs_on_rhs_conflict(), _find_rhs_def_conflict(), _huge(), _linearize(), _linearize_all(), _linearize_func(), _linearize_sub(), _makezero(), _mark_descr(), _mk_arrdsc(), _non_private(), _PDbound(), _PDsize(), _pghpf_bound(), _pghpf_size(), _pgi_element_size(), _pgi_kind(), _reshape(), _rewrite_scalar_fuctions(), _RTE_ba(), _RTE_bound(), _RTE_size(), _RTE_xb(), _sect(), _simple_replacements(), _template(), _transform_func(), acl_rewrite_asts(), add_assign_firstprivate(), add_auto_bounds(), add_bound_assignments(), add_byval(), add_dt_subscr(), add_firstprivate_assn(), add_init(), add_lbnd(), add_lnop(), add_loop_hd(), add_nullify(), add_nullify_ast(), add_parent_to_bounds(), add_pragma(), add_presence(), add_private_allocatable(), add_ptr_assign(), add_single_loop_exit(), add_stmt(), add_stmt_after(), add_stmt_before(), add_subscript_list(), add_taskloopreg(), add_to_early_bnd_list(), addcomponents(), addssassignments(), adjust_ch_length(), alldefs_allocsafe(), alloc2ast(), allocate_array(), allocate_one_auto(), any_functions(), any_pointer_source(), apply_shape_subscripts(), asn_sfuse(), assign(), assign_array_w_forall(), assign_bounds(), assign_cval(), assign_pointer(), assign_scalar(), ast_clear_repl(), ast_cval(), ast_error(), ast_has_allocatable_member(), ast_intr(), ast_is_sym(), ast_isparam(), ast_rewrite(), ast_rewrite_indices(), ast_to_comment(), ast_trav_recurse(), ast_traverse(), ast_traverse_all(), ast_traverse_more(), at_local_mode(), bblock(), begin_combine_constructs(), begin_parallel_clause(), bld_lhs(), bld_ud(), bld_use(), bnd_contains_auto(), bnds_remap_list(), build_array_list(), build_array_reference(), build_conformable_func_node(), build_do_init(), build_poly_func_node(), build_sdsc_node(), build_subscript_list(), call_analyze(), call_comm(), canonical_conversion(), ch_substring(), check_and_add_auto_dealloc_from_ast(), check_derived_type_array_section(), check_do_term(), check_doconcurrent_ast(), check_etmp(), check_pointer_type(), check_pure_interface(), check_region(), check_subprogram(), check_subscript(), check_used_in_data(), check_value(), chk_and_rewrite_cmplxpart_assn(), chk_asz_deferlen(), chk_doindex(), chk_kind_parm(), chk_kind_parm_expr(), chk_kind_parm_set_expr(), chk_len_parm_expr(), chk_struct_constructor(), chkarg(), chkshape(), chksubstr(), cngshape(), cngtyp2(), collapse_add(), collapse_arrays(), collapse_assignment(), collapse_begin(), collapse_expr(), collapse_loops(), comm_analyze(), comm_generator(), common_rel(), compatible_characteristics(), complex_alias(), component_init_allocd_auto(), compute_invariant(), compute_size_expr(), compute_size_ido(), const_eval(), constant_lvalue(), construct_acl_from_ast(), construct_arg_list(), construct_intrinsic_acl(), contains_alloc(), contains_forall_index(), contiguous_array_section(), conv_bint(), conv_bint_ilm(), conv_blog(), conv_blog_ilm(), conv_cmplx(), conv_cmplx_ilm(), conv_dble(), conv_dble_ilm(), conv_dcmplx(), conv_dcmplx_ilm(), conv_deallocate(), conv_dword(), conv_dword_ilm(), conv_forall(), conv_fused_forall(), conv_int(), conv_int8(), conv_int8_ilm(), conv_int_ilm(), conv_log(), conv_log8(), conv_log8_ilm(), conv_log_ilm(), conv_real(), conv_real_ilm(), conv_sint(), conv_sint_ilm(), conv_slog(), conv_slog_ilm(), conv_word(), conv_word_ilm(), convert_forall(), convert_int(), convert_omp_workshare(), convert_simple(), convert_statements(), convert_template_instance(), convert_to_block_forall(), copy_arg_to_seq_tmp(), copy_inargs(), copy_to_scalar(), count_allocatable_members(), count_nest(), cyclic_section(), dbg_print_ast(), dbg_print_stmts(), dealloc_dt_auto(), dealloc_tmp(), defer_put_kind_type_param(), define_stfunc(), diff_lbnd(), dinit_acl_val2(), dinit_constructor(), dinit_data(), dinit_eval(), dinit_getval(), dinit_getval1(), dist_ast(), distribute(), do_bdistribute(), do_begin(), do_bteams(), do_change_mk_id(), do_copyin(), do_copyprivate(), do_dist_schedule(), do_end(), do_firstprivate(), do_lastval(), do_map(), do_openmp_atomics(), do_parbegin(), do_reduction(), do_schedule(), do_simdbegin(), dumparref(), dumpSSlist(), dumpsst(), early_specification_stmt_needed(), elem_size_of_ast(), eliminate_barrier(), eliminate_redundant(), eliminate_start(), eliminate_unused_variables(), emit_alnd_secd(), emit_bcs_ecs(), emit_bpar(), emit_btarget(), emit_copy_section(), emit_epar(), emit_etarget(), emit_fl(), emit_get_scalar(), emit_kopy_in(), emit_overlap(), emit_scatterx_gatherx(), end_association(), end_parallel_clause(), end_target(), end_teams(), end_workshare(), enter_lexical_block(), enter_local_mode(), eval_con_expr(), eval_do_idx(), eval_KIND_expr(), exit_lexical_block(), exit_local_mode(), export(), export_data_const_asts(), export_data_consts(), export_data_varlist(), export_one_ast(), export_some_fini(), extent(), f90_value_function_I2(), fill_argt_with_alnd(), fill_ast(), fill_cyclic_1(), fill_cyclic_k(), fill_links_symbol(), fill_name(), fill_recurse(), find_allocatable_assignment(), find_base(), find_calls_pos(), find_cc_symbols(), find_collapse_allocs(), find_descrs(), find_get_scalar(), find_max_of_mask_calls_pos(), find_pointer_target(), find_pointer_variable(), find_pointer_variable_assign(), find_presence(), find_section_subscript(), findcomponents(), findmulcomponents(), findss(), findssexprsfg(), fix_guard_forall(), fix_mem_ast(), fix_proc_pointer_call(), fix_type_param_members(), fixup_KIND_expr(), flowgraph(), forall_dependency_analyze(), forall_dependency_scalarize(), forall_init(), forall_opt1(), form_cmplx_const(), func_call(), func_call2(), gen_alloc_dealloc(), gen_alloc_mbr(), gen_alloc_mem_initialize_for_sym2(), gen_allocate(), gen_allocated_check(), gen_and_assoc_tmp_ptr(), gen_automatic_reallocation(), gen_bounds_assignments(), gen_call_class_obj_size(), gen_conditional_alloc(), gen_conditional_dealloc_for_sym(), gen_dealloc_for_sym(), gen_dealloc_if_allocated(), gen_dealloc_mbr(), gen_defer_shape(), gen_derived_type_alloc_init(), gen_early_bnd_dependencies(), gen_finalization_for_sym(), gen_init_intrin_call(), gen_init_unl_poly_desc(), gen_islocal_index(), gen_kind_parm_assignments(), gen_logical_if_expr(), gen_null_intrin(), gen_nullify(), gen_pdo(), gen_poly_element_arg(), gen_reduction(), gen_set_len_ast(), gen_type_initialize_for_sym(), gen_unique_func_ast(), gen_varref_var(), generate_copy(), generate_gather(), generate_get_scalar(), generate_hallobnds(), generate_hcycliclp(), generate_hlocalizebnds(), generate_sect(), genPolyAsn(), get_ac_intrinsic(), get_ac_op(), get_all_descriptors(), get_allobnds(), get_ast_asd(), get_ast_dtype(), get_ast_rank(), get_ast_sptr(), get_charintrin_temp(), get_component_init(), get_const_from_ast(), get_descr_or_placeholder_arg(), get_exttype_struct_constructor(), get_forall_subscr(), get_header_member(), get_header_member_with_parent(), get_invoking_proc_desc(), get_len_of_deferchar_ast(), get_param_alias_const(), get_parm_ast(), get_per_dim_member(), get_sst_cval(), get_sst_named_whole_variable(), get_subscr(), get_subscripting_tmp(), getast(), getbase(), getict(), getivl(), handle_arguments(), handle_dependence_ido(), handle_shift(), has_adjustable_expr(), has_allocatable_expr(), has_assumshp_expr(), has_def_inlp(), has_invar_subs(), has_kind_parm_expr(), has_pointer_expr(), has_vector_subscript_ast(), hoist_std(), id_dep_in_forall_idxlist(), incr_tmp(), init_exprs_idx_dependent(), init_intrin_type_desc(), init_sdsc(), init_sdsc_bounds(), init_sptr_w_acl(), InitAST(), inline_ast(), inline_func(), inline_reduction_f90(), inline_shifts(), inline_small_matmul(), inline_stds(), insert_comm(), insert_comm_before(), insert_endmask(), insert_forall_comm(), insert_mask(), internref_bnd(), intrin_name(), intrin_name_bsik(), intrinsic_arg_dtype(), invar_motion(), invar_src(), is_alloc_ast(), is_alloc_std(), is_allocatable_assign(), is_array_ast(), is_array_element_in_forall(), is_array_in_expr(), is_associatable_variable_ast(), is_branch_between(), is_call_dependent(), is_contains_ast_between(), is_data_ast(), is_dealloc_ast(), is_dealloc_std(), is_deferlenchar_ast(), is_descr_expression(), is_dist_array_in_expr(), is_duplicate(), is_function_common(), is_hoistable(), is_illegal_expr_in_init(), is_intrinsic_opr(), is_iso_c_funloc(), is_iso_c_loc(), is_iso_cloc(), is_legal_lhs_for_mask(), is_linear(), is_mask_for_rhs(), is_nonscalar_array_in_expr(), is_pcalls(), is_pointer(), is_ptr_arg(), is_ptrast_arg(), is_ptrdef_in_path(), is_reshape(), is_safe_copy(), is_same_def(), is_same_mask(), is_same_mask_in_fused(), is_std_hoistable(), is_variable_ast(), lbound_of(), leading_section(), leave_arg(), left_array_symbol(), left_nonscalar_subscript_ast(), left_subscript_ast(), leftparens(), linearize_arrays(), llvm_omp_sched(), log_negation(), look_for_descriptor(), lower_address(), lower_ast(), lower_base(), lower_base_address(), lower_bin_arith(), lower_bin_comparison(), lower_bin_logical(), lower_check_ast(), lower_check_pointer(), lower_check_subscript(), lower_clear_opt(), lower_conv(), lower_conv_ilm(), lower_data_stmts(), lower_do_stmt(), lower_end_stmt(), lower_expression(), lower_function(), lower_ilm(), lower_intrinsic(), lower_logical(), lower_logical_expr(), lower_ndtypeg(), lower_no_subscr_chk(), lower_numelm(), lower_omp_atomic_capture(), lower_omp_atomic_update(), lower_omp_atomic_write(), lower_omp_target_tripcount(), lower_parenthesize_expression(), lower_replacement(), lower_start_stmt(), lower_stmt(), lower_target(), lower_un_arith(), lower_un_logical(), make_forall(), make_sec_ast(), make_sec_from_ast(), make_sec_from_ast_chk(), make_simple_template_from_ast(), make_temp_descriptor(), MakeReplacement(), mark(), mark_ast(), mark_idstr(), mark_used_variable(), markmodified(), markss(), matmul(), memsym_of_ast(), merge_blocks(), misc_checks(), mixedsum(), mk_alias(), mk_allocate(), mk_allocate_scalar(), mk_assn_stmt(), mk_atomic(), mk_atomic_capture(), mk_atomic_read(), mk_atomic_update_binop(), mk_atomic_update_intr(), mk_atomic_write(), mk_binop(), mk_cmplxc(), mk_cnst(), mk_convert(), mk_count_test(), mk_cval1(), mk_dealloc_stub(), mk_deallocate(), mk_deallocate_scalar(), mk_duplicate_ast(), mk_elem_init_intrinsic(), mk_firstprivate(), mk_forall_sptr(), mk_func_node(), mk_id(), mk_init(), mk_loop_hdtl(), mk_member(), mk_mlpyr_expr(), mk_nonelem_init_intrinsic(), mk_paren(), mk_promote_scalar(), mk_ptr_subscr(), mk_reshape_intrin(), mk_shape_intrin(), mk_shared_bnd_ast(), mk_size_intrin(), mk_std(), mk_stmt(), mk_subscr_copy(), mk_substr(), mk_transfer_intrin(), mk_transpose_intrin(), mk_triple(), mk_ulbound_intrin(), mk_unop(), mk_ztrips(), mkarg(), mkexpr_assign_temp(), mklabelvar(), mklvalue(), mkmember(), mkSub(), mkunion(), mkvarref(), mmul(), modified(), modify_inlined_stds(), move_labels(), mp_create_bscope(), mp_create_escope(), msg(), mulcomponents(), negatecomponent(), negative_constant(), new_argt(), new_asd(), new_astli(), new_intrin_sym(), new_member_expr(), new_shape(), new_stds(), newargs_for_entry(), nice_mask(), nice_where_mask(), nme_of_ast(), nml_emit_desc(), nop_dealloc(), normalize_forall(), normalize_forall_array(), normalize_forall_triplet(), normalize_subscript(), nullify_member(), nullify_member_after(), open_entry_guard(), opt_allocate(), opt_binop(), optimize(), outvalue_hcycliclp(), outvalue_hlocalizebnds(), parref_bnd(), partition_blocks(), pass_sym_of_ast(), pghpf_type(), pointer_changer(), pointer_squeezer(), position_finder(), precedence(), print_ast(), print_ast_replaced(), print_loc(), print_naked_id(), print_refsym(), print_uncoerced_const(), printast(), printastref(), printstdref(), printstdref_subscript(), process_lhs_sub(), process_real_kind(), procsym_of_ast(), promote_assumsz_arg(), propagate_bound(), propagatemodified(), ptrfunc_call(), ptrsubr_call(), pure_procedure(), put_a_init_tree(), put_call(), put_call_comm(), put_calls(), put_kind_type_param(), put_length_type_param(), put_mem_string(), put_memsym_of_ast(), putzero(), queue_ast(), rank_of_ast(), reassoc_add(), reassociate(), recurse_eoshift(), recurse_shift(), ref_array(), ref_intrin(), ref_intrin_subr(), ref_pd(), ref_pd_subr(), ref_stfunc(), reference_for_temp(), remove_alias(), remove_from_scalar_subscript(), remove_parent_from_ast(), remove_returns(), remove_section(), remove_subscript_expressions(), replace_arg(), replace_ast_subtree(), replace_formal_triples(), replace_label(), replace_memsym_of_ast(), replace_parms(), replace_sdsc_in_ast(), replace_sdsc_in_bounds(), replace_sptr_in_ast(), reshape(), resolve_ast_alias(), rewrite_acl(), rewrite_allocatable_assignment(), rewrite_asn(), rewrite_ast_with_new_dtype(), rewrite_block_forall(), rewrite_block_where(), rewrite_calls(), rewrite_cmplxpart_rval(), rewrite_cptr_references(), rewrite_deallocate(), rewrite_forall(), rewrite_func_ast(), rewrite_inlined_args(), rewrite_into_forall(), rewrite_scalar_functions(), rewrite_sub_args(), rewrite_sub_ast(), rewrite_subscr(), rewrite_where_expr(), rewritefg(), rhs_expr_idx_dependent(), rightparens(), rqueue_ast(), rt_outvalue(), runtime_array(), save_clauses(), scalar_communication(), search_arr(), search_basearr(), search_conform_array(), search_for_auto(), search_idx(), search_kind(), search_pure_function(), sectinline(), selection_sort(), self_use(), semant1(), semant2(), semant3(), semsmp(), sequentialize_call(), set_assumed_bounds(), set_internref_stfunc(), set_kind_result(), set_parref_flag2(), set_private_bnd_encl(), sfloat(), shape_comm(), simple_reference(), simple_reference_for_temp(), size_ast_of(), size_of_allocatable(), size_of_ast(), smp_conflict(), sptr_of_subscript(), srch_sym(), string_expr_length(), sub_lbnd(), subr_call2(), subscript_allocmem(), subscript_lhs(), sym_of_ast(), sym_of_ast2(), symvalue(), tag_forall_comm(), temp_copy_section(), temp_gatherx(), temp_type_descriptor(), tempify_ast(), tmp_assign(), transform_all_call(), transform_associated(), transform_ast(), transform_call(), transform_elemental(), transform_forall(), transform_merge(), transform_mvbits(), transform_ptr(), ubound_of(), unique_allo(), update_shape_info(), update_shape_info_expr(), valid_kind_parm_expr(), value(), and wrap_symbol().
ast_check_visited
LOGICAL ast_check_visited = TRUE static
Definition at line 4363 of file ast.c.
Referenced by _ast_trav(), ast_traverse(), ast_traverse_all(), ast_unvisit(), and ast_visit().
ast_type
int ast_type
Definition at line 4215 of file ast.c.
Referenced by begin_call(), gen_dtio_arglist(), and mk_func_node().
ast_visit_state
LOGICAL ast_visit_state = FALSE static
Definition at line 4361 of file ast.c.
Referenced by ast_replace(), ast_unvisit(), ast_unvisit_norepl(), and ast_visit().
astMatch
int astMatch static
Definition at line 4317 of file ast.c.
Referenced by _contains_ast(), and contains_ast().
atemps
int atemps static
Definition at line 52 of file ast.c.
Referenced by ast_init(), and mk_bnd_ast().
struct { ... } curr_call
Referenced by add_arg(), begin_call(), and finish_args().
indent
int indent = 0 static
Definition at line 6236 of file ast.c.
Referenced by _dmp_acl(), _dump_one_ast(), _dump_shape(), _dumpilmtree(), cg_llvm_init(), dmp_acl(), dmp_const(), dmp_var(), dump_ast_tree(), dump_list_node(), and prntstl().
lwb
int lwb
Definition at line 2392 of file ast.c.
Referenced by add_shape_spec(), ast_rewrite(), collapse_assignment(), const_eval(), ENTF90(), eval_reshape(), find_const_bound_rhs(), make_forall(), mk_mem_ptr_shape(), mk_subscr_copy(), mkshape(), and normalize_forall_array().
ndim
short ndim
Definition at line 2389 of file ast.c.
Referenced by __fort_describe_replication(), _available(), _available_size(), _can_fold(), _constructf90(), _findrefs(), _linearize(), _printnme(), _transform_func(), add_dt_subscr(), add_shape_rank(), add_subscript_list(), apply_shape_subscripts(), assign_array_w_forall(), ast_isparam(), bounds_contain_automatics(), build_allocation_item(), build_array_list(), build_conformable_func_node(), build_subscript_list(), canonical_conversion(), check_derived_type_array_section(), check_dim_error(), chk_assumed_subscr(), cmpat_arr_arg(), collapse_assignment(), complex_alias(), component_init_allocd_auto(), compute_invariant(), compute_permute(), conform_shape(), conformable(), construct_acl_from_ast(), convert_idx_scalar(), convert_subscript(), copy_arg_to_seq_tmp(), copy_desc_to_bnds_vars(), copy_section_temp_before(), copy_surrogate_to_bnds_vars(), dastreex(), decl_private_sym(), decompose_expression(), dtype_with_shape(), dumparref(), dumpsubinfo(), eliminate_extra_idx(), eliminate_gather(), eliminate_shift(), emit_alnd(), emit_get_scalar(), emit_get_scalar_sub(), emit_kopy_in(), emit_overlap(), emit_permute_section(), emit_secd(), ENTF90(), fill_adjustable_array_dtype(), fill_argt_with_alnd(), fill_fixed_array_dtype(), fill_pointer_array_dtype(), fill_subscripts(), find_assumshp_dep(), find_base(), find_presence(), first_element_from_section(), fix_datatype(), fix_dtype(), fix_guard_forall(), fixup_KIND_expr(), fixup_param_vars(), forall_2_sec(), forall_semantic(), gatherx_temp_before(), gen_allocate(), gen_bnd_assn(), gen_bounds_assignments(), gen_derived_arr_init(), gen_dos_over_shape(), gen_ptr_in(), generate_get_scalar(), generate_hallobnds(), generate_sect(), get_all_descriptors(), get_allobnds(), get_temp_forall2(), getast(), handle_allocatable_members(), has_def_inlp(), hoist_std(), increase_shape(), init_sptr_w_acl(), inline_reduction_f90(), inline_spread_shifts(), insert_comm_before(), insert_forall_comm(), is_array_element_in_forall(), is_duplicate(), is_hoistable(), is_indirection_in_it(), is_legal_lhs(), is_legal_lhs_for_mask(), is_nonscalar_array_in_expr(), is_nonscalar_indirection_in_it(), is_one_idx_for_dim(), is_ordered(), is_permuted(), is_same_alnd(), is_same_array_bounds(), is_same_array_shape(), is_same_mask(), is_same_number_of_idx(), is_same_secd(), is_structured(), is_vector_indirection_in_it(), is_vector_subscript(), is_whole_array(), left_nonscalar_subscript_ast(), lhs_dim(), lower_ast(), lower_check_ast(), lower_check_subscript(), lower_put_datatype(), lower_stmt(), lower_use_datatype(), make_alnd(), make_sec_from_ast_chk(), make_secd(), make_seq_temp_array(), mark_dtype_ast_idstr(), matched_dim(), mk_bounds_shape(), mk_component_ast(), mk_shape(), mkvarref(), new_seq_temp_array(), no_comm_class(), normalize_subscripts(), opt_allocate(), opt_overlap(), overlap_class(), permute_axis(), process_rhs_sub(), put_adjarr_bounds(), queue_dtype(), read_datatype(), reduc_shape(), reference_for_temp(), remove_from_scalar_subscript(), remove_function_common_from_scalar_subscript(), remove_subscript_expressions(), replace_expr(), rewrite_all_shape(), rewrite_allocatable_assignment(), rewrite_triples(), scalar_communication(), semant1(), semantio(), set_internref_flag(), set_parref_flag(), set_private_encl(), simple_reference_for_temp(), size_of_ast(), small_shape(), sym_get_array(), tag_comms(), tag_forall_comm(), to_assumed_shape(), trans_mkproc(), transform_all_call(), and wrap_symbol().
next
short next
Definition at line 2390 of file ast.c.
Referenced by __fort_gathscat(), __fortio_alloc_fcb(), access_swtab_base_label(), access_swtab_case_label(), acl_rewrite_asts(), add_autobj(), addnewbih(), addpte(), ast_unvisit(), ast_unvisit_norepl(), bih_init(), defer_arg_chk(), defer_pt_decl(), defer_put_kind_type_param(), delbih(), delilt(), do_equiv(), dup_acl(), ENTFTN(), ENTRY(), eval_reshape(), export(), export_data_asts(), export_data_stmt(), export_equivs(), export_ivl_ict(), export_ivl_ict_asts(), fix_module_common(), Ftn_str_free(), gen_alloc_mem_initialize_for_sym2(), gen_dinit(), gen_llvm_atomic_intrinsic_for_builtin(), genswitch(), get_all_descriptors(), has_final_members(), has_type_parameter2(), ilt_init(), insertsrt(), is_same_def(), ll_destroy_basic_block(), ll_destroy_function(), ll_destroy_module(), lower_end_stmt(), mkvarref(), print_par_xref(), put_default_kind_type_param(), put_length_type_param(), queue_type_param(), read_fileentries(), remove_flow_list(), remove_instr(), remove_loop(), remove_stmt(), restore_hoist_stmt(), sdrop_stmt(), semant1(), semantio(), semsmp(), set_outliner_state(), sfloat_stmt(), sfloat_stmt2(), sptrListFree(), top_sort(), and x86_promote_to_vector().
rewrite_opfields
int rewrite_opfields = 0
Definition at line 4358 of file ast.c.
Referenced by ast_rewrite(), ast_unvisit(), ast_unvisit_norepl(), and comm_optimize_post().
struct { ... } spec[MAXRANK]
Referenced by __fvs_log_fma3(), __fvs_log_fma3_256(), __rvs_log_fma3(), __rvs_log_fma3_256(), check_alloc_clauses(), check_dealloc_clauses(), fix_symbol(), gen_alloc_dealloc(), and select_gsame().
stride
int stride
Definition at line 2394 of file ast.c.
Referenced by add_shape_spec(), ast_rewrite(), extent_of_shape(), get_ast_bounds(), get_ast_extents(), hash_triple(), is_whole_array(), mk_mem_ptr_shape(), mk_subscr_copy(), mk_triple(), and mkshape().
tail_astli
int tail_astli static
Definition at line 4143 of file ast.c.
Referenced by add_astli(), and start_astli().
upb
int upb
Definition at line 2393 of file ast.c.
Referenced by add_shape_spec(), arrayref_size(), ast_rewrite(), collapse_assignment(), ENTF90(), find_const_bound_rhs(), make_forall(), mk_mem_ptr_shape(), mk_subscr_copy(), and mkshape().
visit_list
int visit_list = 0 static
Definition at line 4355 of file ast.c.
Referenced by ast_revisit(), ast_unvisit(), ast_unvisit_norepl(), gen_alloc_mem_initialize_for_sym2(), has_final_members(), and has_type_parameter2().