flang: astout.c File Reference
astout.c File Reference
Abstract syntax tree output module.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "soc.h"
#include "semant.h"
#include "ast.h"
#include "pragma.h"
#include "gramtk.h"
#include "tokdf.h"
#include "dinit.h"
#include "rte.h"
#include "rtlRtns.h"
Classes
struct _A_Q
struct _qsym
Macros
#define NO_PTR XBIT(49, 0x8000)
#define NO_CHARPTR XBIT(58, 0x1)
#define NO_DERIVEDPTR XBIT(58, 0x40000)
#define CARDB_SIZE 2100 /* make it large enough */
#define MAX_FNAME_LEN 2050
#define INDENT_MAX 4
#define INDENT_STR " "
#define PREC_TERM 20
#define PREC_POW 18
#define PREC_MULT 16
#define PREC_ADD 14
#define PREC_NEG 12
#define PREC_REL 10
#define PREC_NOT 8
#define PREC_AND 6
#define PREC_OR 4
#define PREC_EQV 2
Typedefs
typedef struct _qsym QSYM
Functions
static void print_ast (int ast)
static void print_ast_replaced (int, int, int)
static void init_line (void)
static void push_indent (void)
static void pop_indent (void)
static void print_uncoerced_const (int)
static void print_loc (int)
static void print_loc_of_sym (int)
static void print_refsym (int, int)
static void print_sname (int)
static void print_naked_id (int)
void deferred_to_pointer (void)
Since the output is 'standard' f77, all allocatable (deferred-shape) arrays must be converted to pointer-based arrays. The symbol table is scanned to find allocatable arrays which do not have bound temporaries or associated pointer variables.
static int pr_chk_arr (int)
static void gen_bnd_assn (int)
static void gen_allocate (int, int)
static void gen_deallocate (int, int, int, int)
static void gen_nullify (int, int, int)
static void put_mem_string (int, const char *)
static void put_string (const char *)
static void put_fstring (const char *)
static void put_char (char)
static void put_const (int)
static void put_int (INT)
static void put_intkind (INT, int)
static void put_int8 (int)
static void put_logical (LOGICAL, int)
static void put_float (INT)
static void put_double (int)
static void char_to_text (int)
static void put_u_to_l (const char *)
static void put_l_to_u (const char *)
static void check_len (int)
static char * label_name (int)
static void print_header (int)
static void pghpf_entry (int)
static void put_call (int ast, int call, const char *name, int check_ptrarg)
void astout_init (void)
static int precedence (int ast)
static LOGICAL negative_constant (int ast)
static int left_precedence (int lop, int prec_op)
static int right_precedence (int rop, int prec_op)
static void cuf_pragma (int ast)
static void acc_pragma (int ast)
static void acc_dtype (int ast)
static void pr_arr_name (int arr)
static int find_member_base (int dtype)
static void write_next_line (void)
void add_param (int sptr)
Add parameters in the order in which they were declared.
void end_param (void)
Since a separate list is created for each parameter combination of ansi-/vax- style and constant/non-constant ast, it is necessary to mark where in the list the contributions from a each parameter statement ends.
void dbg_print_ast (int ast, FILE *fil)
void dbg_print_stmts (FILE *f)
void printast (int ast)
Variables
static FILE * outfile
static int col = 0
static int max_col = 72
static int continuations = 0
static int indent
static char lbuff [CARDB_SIZE]
static LOGICAL ast_is_comment = FALSE
static LOGICAL op_space = TRUE
static LOGICAL altret_spec = FALSE
struct {
_A_Q q
_A_Q q_e
} params
struct {
_A_Q q
_A_Q q_e
} vx_params = {0}
static int just_did_sharpline = 0
Detailed Description
Abstract syntax tree output module.
Definition in file astout.c.
Macro Definition Documentation
CARDB_SIZE
#define CARDB_SIZE 2100 /* make it large enough */
Definition at line 42 of file astout.c.
INDENT_MAX
#define INDENT_MAX 4
Definition at line 128 of file astout.c.
INDENT_STR
#define INDENT_STR " "
Definition at line 129 of file astout.c.
MAX_FNAME_LEN
#define MAX_FNAME_LEN 2050
Definition at line 45 of file astout.c.
NO_CHARPTR
#define NO_CHARPTR XBIT(58, 0x1)
Definition at line 30 of file astout.c.
NO_DERIVEDPTR
#define NO_DERIVEDPTR XBIT(58, 0x40000)
Definition at line 31 of file astout.c.
NO_PTR
#define NO_PTR XBIT(49, 0x8000)
Definition at line 29 of file astout.c.
PREC_ADD
#define PREC_ADD 14
PREC_AND
#define PREC_AND 6
PREC_EQV
#define PREC_EQV 2
PREC_MULT
#define PREC_MULT 16
PREC_NEG
#define PREC_NEG 12
PREC_NOT
#define PREC_NOT 8
PREC_OR
#define PREC_OR 4
PREC_POW
#define PREC_POW 18
PREC_REL
#define PREC_REL 10
PREC_TERM
#define PREC_TERM 20
Typedef Documentation
QSYM
typedef struct _qsym QSYM
Function Documentation
acc_dtype()
static void acc_dtype (int ast) static
Definition at line 355 of file astout.c.
Referenced by print_ast().
acc_pragma()
static void acc_pragma (int ast) static
Definition at line 343 of file astout.c.
References lbuff.
Referenced by print_ast().
add_param()
void add_param (int sptr)
Add parameters in the order in which they were declared.
Definition at line 4413 of file astout.c.
References CONVAL2G, _A_Q::first, _A_Q::last, params, q, sem, sptr, vx_params, and SEM::which_pass.
Referenced by fill_links_symbol(), get_param_alias_const(), and semant1().
astout_init()
void astout_init (void)
Definition at line 113 of file astout.c.
References BZERO, max_col, params, vx_params, and XBIT.
Referenced by datastructure_reinit().
char_to_text()
static void char_to_text (int ch) static
Definition at line 4251 of file astout.c.
References b, c, put_char(), put_string(), and XBIT.
Referenced by put_const().
check_len()
static void check_len (int len) static
Definition at line 4335 of file astout.c.
References col, continuations, len, max_col, and write_next_line().
Referenced by put_char(), put_string(), and put_u_to_l().
cuf_pragma()
static void cuf_pragma (int ast) static
Definition at line 332 of file astout.c.
References lbuff.
Referenced by print_ast().
dbg_print_ast()
void dbg_print_ast (int ast, FILE * fil)
Definition at line 4482 of file astout.c.
References ast, ast_is_comment, col, FALSE, indent, init_line(), max_col, NULL, outfile, print_ast(), TRUE, and write_next_line().
Referenced by _dump_node(), _dump_std(), asn_sfuse(), ast_error(), copy_to_loop(), dbg_print_stmts(), dsstd(), dstd(), induction(), and ref_stfunc().
dbg_print_stmts()
void dbg_print_stmts (FILE * f)
Definition at line 4503 of file astout.c.
References ast, dbg_print_ast(), f, NULL, std, STD_AST, and STD_NEXT.
Referenced by transform().
deferred_to_pointer()
void deferred_to_pointer (void)
Since the output is 'standard' f77, all allocatable (deferred-shape) arrays must be converted to pointer-based arrays. The symbol table is scanned to find allocatable arrays which do not have bound temporaries or associated pointer variables.
Definition at line 3334 of file astout.c.
References AD_DEFER, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_NOBOUNDS, AD_NUMDIM, AD_UPAST, ALIGNG, STB::firstusym, i, mk_bnd_ast(), NO_PTR, s, sptr, stb, sym_get_ptr(), and XBIT.
Referenced by linearize_arrays().
end_param()
void end_param (void)
Since a separate list is created for each parameter combination of ansi-/vax- style and constant/non-constant ast, it is necessary to mark where in the list the contributions from a each parameter statement ends.
Definition at line 4446 of file astout.c.
References first, i, last, params, q, and vx_params.
Referenced by fill_links_symbol(), and semant1().
find_member_base()
static int find_member_base (int dtype) static
Definition at line 3524 of file astout.c.
References DDTG, lookupsymbol(), mem(), mkRteRtnNm(), NOSYM, and RTE_member_base.
Referenced by gen_allocate(), and gen_deallocate().
gen_allocate()
static void gen_allocate (int object, int stat) static
Definition at line 3553 of file astout.c.
References AD_DPTR, AD_NUMELM, ADD_EXTNTAST, ADD_LWAST, ADD_UPAST, ALIGNG, ASD_NDIM, ASD_SUBS, ast, astb, DDTG, dsym(), DT_INT, DTY, DTYG, FALSE, find_member_base(), find_pointer_variable(), gen_bnd_assn(), i, ASTB::i1, lb, mem(), mk_binop(), mk_extent_expr(), mkRteRtnNm(), ndim, nelem, NO_CHARPTR, NO_DERIVEDPTR, NO_PTR, NOSYM, OP_ADD, OP_MUL, op_space, OP_SUB, print_ast(), print_ast_replaced(), ASTB::ptr0, put_char(), put_int(), put_l_to_u(), put_mem_string(), put_string(), RTE_alloca, RTE_ptr_alloca, size_ast(), stat, SYMNAME, t, TY_CHAR, ty_to_lib, ub, and XBIT.
Referenced by print_ast().
gen_bnd_assn()
static void gen_bnd_assn (int sub) static
Definition at line 3490 of file astout.c.
References AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_NUMDIM, AD_UPAST, ASD_NDIM, ASD_SUBS, assert, DDTG, dsym(), get_array_dtype(), i, memsym_of_ast(), mk_extent(), ndim, and sub.
Referenced by gen_allocate(), and print_ast().
gen_deallocate()
static void gen_deallocate (int object, int stat, int asym, int passptr) static
Definition at line 3706 of file astout.c.
References assert, astb, DTYG, find_member_base(), gen_nullify(), mem(), mkRteRtnNm(), NO_CHARPTR, NO_DERIVEDPTR, NO_PTR, NOSYM, print_ast(), print_ast_replaced(), ASTB::ptr0, put_char(), put_l_to_u(), put_mem_string(), put_string(), RTE_dealloca, RTE_deallocx, stat, SYMNAME, TY_CHAR, and XBIT.
Referenced by print_ast().
gen_nullify()
static void gen_nullify (int ast, int sym, int passptr) static
Definition at line 3764 of file astout.c.
References ast, DTYG, mkRteRtnNm(), print_ast_replaced(), put_char(), put_l_to_u(), put_mem_string(), put_string(), RTE_nullify, RTE_nullify_chara, RTE_nullifyx, SYMNAME, TY_CHAR, and XBIT.
Referenced by gen_deallocate(), and print_ast().
init_line()
static void init_line (void) static
Definition at line 122 of file astout.c.
References col, and put_string().
Referenced by dbg_print_ast().
label_name()
static char * label_name (int lab) static
Definition at line 4344 of file astout.c.
References getsym(), lb, lbuff, lookupsym(), SYMNAME, and TRUE.
Referenced by print_ast().
left_precedence()
static int left_precedence (int lop, int prec_op) static
Definition at line 281 of file astout.c.
References negative_constant(), PREC_ADD, PREC_POW, and precedence().
Referenced by print_ast().
negative_constant()
static LOGICAL negative_constant (int ast) static
Definition at line 240 of file astout.c.
References ast, cmp64(), CONVAL2G, STB::dbl0, DTY, FALSE, STB::flt0, sptr, stb, TRUE, TY_DBLE, TY_INT, TY_INT8, TY_REAL, xdcmp(), and xfcmp().
Referenced by left_precedence(), print_ast(), and right_precedence().
pghpf_entry()
static void pghpf_entry (int func) static
Definition at line 4458 of file astout.c.
References ENDLINEG, fl, func, FUNCLINEG, gbl, mkRteRtnNm(), put_char(), put_fstring(), put_int(), put_l_to_u(), put_string(), RTE_function_entrya, SYMNAME, and XBIT.
Referenced by print_ast().
pop_indent()
static void pop_indent (void) static
Definition at line 142 of file astout.c.
References ast_is_comment, col, ERR_Warning, indent, INDENT_MAX, INDENT_STR, interr(), and strlen().
Referenced by print_ast().
pr_arr_name()
static void pr_arr_name (int arr) static
Definition at line 3413 of file astout.c.
References DTYG, print_ast(), print_sname(), put_char(), and sptr.
Referenced by pr_chk_arr().
pr_chk_arr()
static int pr_chk_arr (int arr) static
Definition at line 3440 of file astout.c.
References DTYG, F77OUTPUT, NO_CHARPTR, NO_DERIVEDPTR, NO_PTR, pr_arr_name(), print_ast(), sptr, and TY_CHAR.
Referenced by print_ast().
precedence()
static int precedence (int ast) static
Definition at line 156 of file astout.c.
References A_OPTYPEG, ast, OP_ADD, OP_BYVAL, OP_CAT, OP_DIV, OP_EQ, OP_GE, OP_GT, OP_LAND, OP_LE, OP_LEQV, OP_LNEQV, OP_LNOT, OP_LOC, OP_LOR, OP_LT, OP_MUL, OP_NE, OP_REF, OP_SCAND, OP_SUB, OP_VAL, OP_XTOI, OP_XTOX, PREC_ADD, PREC_AND, PREC_EQV, PREC_MULT, PREC_NOT, PREC_OR, PREC_POW, PREC_REL, PREC_TERM, and precedence().
Referenced by left_precedence(), precedence(), print_ast(), and right_precedence().
print_ast()
static void print_ast (int ast) static
Definition at line 360 of file astout.c.
References A_ARGCNTG, A_MEM_ORDERG, A_OPTYPEG, A_ORDEREDG, A_SCHED_TYPEG, A_TKNG, acc_dtype(), acc_pragma(), AD_DPTR, AD_LWAST, AD_UPAST, ADD_LWAST, altret_spec, arg, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, ast_is_comment, astb, ASTLI_AST, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, ASTB::atypes, ASTB::bnd, check_member(), cnt, col, COMSTR, cuf_pragma(), DDTG, dsym(), DT_PTR, DTY, DTYG, ASTB::dtype, ERR_Fatal, F77OUTPUT, FALSE, find_pointer_variable(), gbl, gen_allocate(), gen_bnd_assn(), gen_deallocate(), gen_nullify(), get_local_multiplier(), get_section_offset(), get_xbase(), i, ASTB::i1, intast_sym, label_name(), lbuff, left_precedence(), memsym_of_ast(), mk_binop(), mk_id(), mkRteRtnNm(), STB::n_base, negative_constant(), NO_CHARPTR, NO_DERIVEDPTR, NO_PTR, NOSYM, NULL, off, offset, ASTB::one, OP_ADD, OP_BYVAL, OP_CAT, OP_DIV, OP_EQ, OP_GE, OP_GT, OP_LAND, OP_LE, OP_LEQV, OP_LNEQV, OP_LNOT, OP_LOC, OP_LOR, OP_LT, OP_MUL, OP_NE, OP_REF, OP_SCAND, op_space, OP_SUB, OP_VAL, OP_XTOI, OP_XTOX, optype(), pghpf_entry(), pop_indent(), PR_ACCASYNC, PR_ACCATTACH, PR_ACCAUTO, PR_ACCBEGINDIR, PR_ACCCACHEARG, PR_ACCCACHEDIR, PR_ACCCACHEREADONLY, PR_ACCCOLLAPSE, PR_ACCCOMPARE, PR_ACCCOPY, PR_ACCCOPYIN, PR_ACCCOPYOUT, PR_ACCCREATE, PR_ACCDATAREG, PR_ACCDEFNONE, PR_ACCDEFPRESENT, PR_ACCDELETE, PR_ACCDETACH, PR_ACCDEVICEID, PR_ACCDEVICEPTR, PR_ACCDEVICERES, PR_ACCEL, PR_ACCELLP, PR_ACCENDDATAREG, PR_ACCENDHOSTDATA, PR_ACCENDIMPDATAREG, PR_ACCENDKERNELS, PR_ACCENDPARCONSTRUCT, PR_ACCENDSCALARREG, PR_ACCENDSERIAL, PR_ACCENTERDATA, PR_ACCEXITDATA, PR_ACCFINALEXITDATA, PR_ACCFIRSTPRIVATE, PR_ACCFORCECOLLAPSE, PR_ACCGANG, PR_ACCGANGCHUNK, PR_ACCGANGDIM, PR_ACCHOST, PR_ACCHOSTDATA, PR_ACCIF, PR_ACCIMPDATAREG, PR_ACCIMPDATAREGX, PR_ACCINDEPENDENT, PR_ACCKERNELS, PR_ACCKLOOP, PR_ACCLINK, PR_ACCLOCAL, PR_ACCLOOPPRIVATE, PR_ACCMIRROR, PR_ACCNO_CREATE, PR_ACCNOWAIT, PR_ACCNUMGANGS, PR_ACCNUMGANGS2, PR_ACCNUMGANGS3, PR_ACCNUMWORKERS, PR_ACCPARALLEL, PR_ACCPARCONSTRUCT, PR_ACCPARUNROLL, PR_ACCPCOPY, PR_ACCPCOPYIN, PR_ACCPCOPYOUT, PR_ACCPCREATE, PR_ACCPDELETE, PR_ACCPLOOP, PR_ACCPRESENT, PR_ACCPRIVATE, PR_ACCREDUCT_OP_ADD, PR_ACCREDUCT_OP_BITAND, PR_ACCREDUCT_OP_BITEOR, PR_ACCREDUCT_OP_BITIOR, PR_ACCREDUCT_OP_EQV, PR_ACCREDUCT_OP_LOGAND, PR_ACCREDUCT_OP_LOGOR, PR_ACCREDUCT_OP_MAX, PR_ACCREDUCT_OP_MIN, PR_ACCREDUCT_OP_MUL, PR_ACCREDUCT_OP_NEQV, PR_ACCREDUCTION, PR_ACCREDUCTOP, PR_ACCREFLECT, PR_ACCSCALARREG, PR_ACCSEQ, PR_ACCSEQUNROLL, PR_ACCSERIAL, PR_ACCSLOOP, PR_ACCTILE, PR_ACCTKLOOP, PR_ACCTPLOOP, PR_ACCTSLOOP, PR_ACCUNROLL, PR_ACCUPDATE, PR_ACCUPDATEDEVICE, PR_ACCUPDATEDEVICEIFP, PR_ACCUPDATEHOST, PR_ACCUPDATEHOSTIFP, PR_ACCUPDATESELF, PR_ACCUPDATESELFIFP, PR_ACCUSEDEVICE, PR_ACCUSEDEVICEIFP, PR_ACCVECTOR, PR_ACCVECUNROLL, PR_ACCVLENGTH, PR_ACCWAIT, PR_ACCWAITARG, PR_ACCWAITDIR, PR_ACCWORKER, PR_ALWAYSINLINE, pr_chk_arr(), PR_CUFLOOPPRIVATE, PR_ENDACCEL, PR_ENDKERNEL, PR_GLOBAL, PR_INLINEALIGN, PR_INLINEAS, PR_INLINEONLY, PR_INLINETYPE, PR_INLININGOFF, PR_INLININGON, PR_KERNEL, PR_KERNEL_BLOCK, PR_KERNEL_DEVICE, PR_KERNEL_GRID, PR_KERNEL_NEST, PR_KERNEL_STREAM, PR_KERNELBEGIN, PR_KERNELTILE, PR_LINE, PR_LOOP, PR_NEVERINLINE, PR_NONE, PR_NOSCOPE, PR_PCASTCOMPARE, PR_PGICOMPARE, PR_ROUTINE, PREC_MULT, PREC_TERM, precedence(), print_ast(), print_ast_replaced(), print_header(), print_loc(), print_loc_of_sym(), print_naked_id(), print_refsym(), print_sname(), print_uncoerced_const(), ASTB::ptr0, ASTB::ptr0c, push_indent(), put_call(), put_char(), put_const(), put_int(), put_intkind(), put_l_to_u(), put_mem_string(), put_string(), put_u_to_l(), right_precedence(), RTE_achara, RTE_allocated, RTE_barrier, RTE_copy_out, RTE_exit, RTE_expon, RTE_expond, RTE_exponq, RTE_frac, RTE_fracd, RTE_fracq, RTE_function_exit, RTE_iachara, RTE_ilen, RTE_indexa, RTE_lb, RTE_leadz, RTE_lentrima, RTE_mvbits, RTE_nearest, RTE_nearestd, RTE_nearestq, RTE_nlentrim, RTE_nscan, RTE_nverify, RTE_popcnt, RTE_poppar, RTE_ptr_assign, RTE_ptr_assign_chara, RTE_ptr_assign_charxa, RTE_ptr_assignx, RTE_ptr_in_chara, RTE_ptr_ina, RTE_ptr_offset, RTE_ptr_out, RTE_ptr_out_chara, RTE_qopy_in, RTE_reshape, RTE_rrspacing, RTE_rrspacingd, RTE_rrspacingq, RTE_scale, RTE_scaled, RTE_scaleq, RTE_scana, RTE_setexp, RTE_setexpd, RTE_setexpq, RTE_size, RTE_spacing, RTE_spacingd, RTE_spacingq, RTE_trailz, RTE_ub, RTE_verifya, RU_BDATA, RU_FUNC, RU_PROG, RU_SUBR, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, size_of(), sptr, stb, str, stride, strlen(), sym_of_ast(), SYMNAME, tmp, TRUE, TY_CHAR, TY_QUAD, TY_REAL, ty_to_lib, XBIT, and ASTB::zero.
Referenced by dbg_print_ast(), gen_allocate(), gen_deallocate(), pr_arr_name(), pr_chk_arr(), print_ast(), print_ast_replaced(), print_loc(), print_naked_id(), print_refsym(), print_uncoerced_const(), printast(), put_call(), and put_mem_string().
print_ast_replaced()
static void print_ast_replaced (int ast, int sym, int replacesym) static
Definition at line 3143 of file astout.c.
References ast, print_ast(), put_string(), and SYMNAME.
Referenced by gen_allocate(), gen_deallocate(), gen_nullify(), and print_ast().
print_header()
static void print_header (int subp) static
Definition at line 4385 of file astout.c.
References arg, aux, AUX::dpdsc_base, i, print_sname(), put_char(), put_string(), SYMNAME, and TRUE.
Referenced by print_ast().
print_loc()
static void print_loc (int ast) static
Definition at line 3207 of file astout.c.
References ast, ast_is_comment, mkRteRtnNm(), print_ast(), print_loc_of_sym(), put_char(), put_string(), and RTE_loc.
Referenced by print_ast().
print_loc_of_sym()
static void print_loc_of_sym (int sym) static
Definition at line 3224 of file astout.c.
References ast_is_comment, F77OUTPUT, mkRteRtnNm(), NO_PTR, print_refsym(), put_char(), put_string(), RTE_loc, and SYMNAME.
Referenced by print_ast(), and print_loc().
print_naked_id()
static void print_naked_id (int ast) static
Definition at line 3318 of file astout.c.
References ast, print_ast(), put_string(), and SYMNAME.
Referenced by print_ast(), and put_call().
print_refsym()
static void print_refsym (int sym, int ast) static
Definition at line 3242 of file astout.c.
References ALIGNG, ast, ast_is_comment, b, check_member(), DBGBIT, DTYG, F77OUTPUT, mk_id(), NO_CHARPTR, NO_DERIVEDPTR, NO_PTR, offset, print_ast(), print_sname(), put_char(), put_string(), SYMNAME, and TY_CHAR.
Referenced by print_ast(), and print_loc_of_sym().
print_sname()
static void print_sname (int sym) static
Definition at line 3278 of file astout.c.
References FLANG_FALLTHROUGH, put_string(), and SYMNAME.
Referenced by pr_arr_name(), print_ast(), print_header(), and print_refsym().
print_uncoerced_const()
static void print_uncoerced_const (int ast) static
Definition at line 3188 of file astout.c.
References ast, print_ast(), and put_const().
Referenced by print_ast().
printast()
void printast (int ast)
Definition at line 4517 of file astout.c.
References ast, ast_is_comment, col, FALSE, gbl, indent, lbuff, NULL, outfile, print_ast(), and TRUE.
Referenced by _dumpacl(), _printnme(), addSS(), addssassignments(), analyze(), dmp_var(), dump_ind(), dump_one_memref(), dump_vinduc(), dumparref(), dumpSSlist(), dumpsubinfo(), make_assignment(), mark(), past(), printastref(), printstdref(), putast(), and reassociate().
push_indent()
static void push_indent (void) static
Definition at line 132 of file astout.c.
References ast_is_comment, indent, INDENT_MAX, INDENT_STR, and put_string().
Referenced by print_ast().
put_call()
static void put_call (int ast, int call, const char * name, int check_ptrarg) static
Definition at line 3047 of file astout.c.
References A_ARGCNTG, altret_spec, arg, argt, ARGT_ARG, ast, ast_is_comment, astb, aux, cnt, AUX::dpdsc_base, DTY, F77OUTPUT, FALSE, i, name, NO_PTR, print_ast(), print_naked_id(), proc_arginfo(), procsym_of_ast(), ASTB::ptr0, ASTB::ptr0c, put_char(), put_l_to_u(), put_string(), sptr, SYMNAME, and TRUE.
Referenced by print_ast().
put_char()
static void put_char (char ch) static
Definition at line 3866 of file astout.c.
References check_len(), col, and lbuff.
Referenced by char_to_text(), gen_allocate(), gen_deallocate(), gen_nullify(), pghpf_entry(), pr_arr_name(), print_ast(), print_header(), print_loc(), print_loc_of_sym(), print_refsym(), put_call(), put_const(), put_double(), put_float(), and put_fstring().
put_const()
static void put_const (int sptr) static
Definition at line 3874 of file astout.c.
References b, c, char_to_text(), CONVAL2G, DTY, FLANG_FALLTHROUGH, len, STB::n_base, put_char(), put_const(), put_double(), put_float(), put_int8(), put_intkind(), put_l_to_u(), put_logical(), put_string(), sptr, stb, string_length(), SYMNAME, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by print_ast(), print_uncoerced_const(), and put_const().
put_double()
static void put_double (int sptr) static
Definition at line 4174 of file astout.c.
References b, CONVAL2G, cprintf(), DT_REAL, DTY, end, exp, i, num, put_char(), put_string(), sptr, start, strlen(), TY_DBLE, and XBIT.
Referenced by put_const().
put_float()
static void put_float (INT val) static
Definition at line 4110 of file astout.c.
References b, cprintf(), DT_REAL, DTY, end, exp, i, put_char(), put_string(), start, strlen(), target_kind(), TY_REAL, and val.
Referenced by put_const().
put_fstring()
static void put_fstring (const char * str) static
Definition at line 3850 of file astout.c.
References len, put_char(), str, and strlen().
Referenced by pghpf_entry().
put_int()
static void put_int (INT val) static
Definition at line 3989 of file astout.c.
References b, put_string(), and val.
Referenced by gen_allocate(), pghpf_entry(), and print_ast().
put_int8()
static void put_int8 (int sptr) static
Definition at line 4050 of file astout.c.
References b, CONVAL2G, DT_INT, DTY, end, FALSE, num, put_string(), sptr, strlen(), target_kind(), TRUE, TY_INT8, ui64toax(), and XBIT.
Referenced by put_const().
put_intkind()
static void put_intkind (INT val, int dtype) static
Definition at line 3997 of file astout.c.
References b, DT_INT, DTY, end, FALSE, put_string(), strlen(), target_kind(), TRUE, TY_BINT, TY_INT, TY_INT8, TY_SINT, val, and XBIT.
Referenced by print_ast(), and put_const().
put_l_to_u()
static void put_l_to_u (const char * name) static
Definition at line 4318 of file astout.c.
References name, and put_string().
Referenced by gen_allocate(), gen_deallocate(), gen_nullify(), pghpf_entry(), print_ast(), put_call(), and put_const().
put_logical()
static void put_logical (LOGICAL val, int dtype) static
Definition at line 4093 of file astout.c.
References b, DT_LOG, DTY, put_string(), target_kind(), and val.
Referenced by put_const().
put_mem_string()
static void put_mem_string (int ast, const char * str) static
Definition at line 3840 of file astout.c.
References ast, print_ast(), put_string(), and str.
Referenced by gen_allocate(), gen_deallocate(), gen_nullify(), and print_ast().
put_string()
static void put_string (const char * str) static
Definition at line 3829 of file astout.c.
References check_len(), col, lbuff, len, str, and strlen().
Referenced by char_to_text(), gen_allocate(), gen_deallocate(), gen_nullify(), init_line(), pghpf_entry(), print_ast(), print_ast_replaced(), print_header(), print_loc(), print_loc_of_sym(), print_naked_id(), print_refsym(), print_sname(), push_indent(), put_call(), put_const(), put_double(), put_float(), put_int(), put_int8(), put_intkind(), put_l_to_u(), put_logical(), put_mem_string(), and put_u_to_l().
put_u_to_l()
static void put_u_to_l (const char * name) static
Definition at line 4296 of file astout.c.
References check_len(), col, flg, lbuff, name, put_string(), strlen(), and FLG::ucase.
Referenced by print_ast().
right_precedence()
static int right_precedence (int rop, int prec_op) static
Definition at line 306 of file astout.c.
References negative_constant(), PREC_ADD, PREC_POW, and precedence().
Referenced by print_ast().
write_next_line()
static void write_next_line (void) static
Definition at line 4326 of file astout.c.
References col, just_did_sharpline, lbuff, and outfile.
Referenced by check_len(), and dbg_print_ast().
Variable Documentation
altret_spec
LOGICAL altret_spec = FALSE static
Definition at line 49 of file astout.c.
Referenced by print_ast(), and put_call().
ast_is_comment
LOGICAL ast_is_comment = FALSE static
Definition at line 46 of file astout.c.
Referenced by dbg_print_ast(), pop_indent(), print_ast(), print_loc(), print_loc_of_sym(), print_refsym(), printast(), push_indent(), and put_call().
col
int col = 0 static
Definition at line 35 of file astout.c.
Referenced by check_len(), clreol(), dbg_print_ast(), display_error(), get_src_line(), init_line(), lower_to_upper(), pop_indent(), print_ast(), printast(), prmat(), put_char(), put_string(), put_u_to_l(), upper_to_lower(), and write_next_line().
continuations
int continuations = 0 static
Definition at line 38 of file astout.c.
Referenced by check_len().
indent
int indent static
Definition at line 40 of file astout.c.
Referenced by dbg_print_ast(), pop_indent(), printast(), and push_indent().
just_did_sharpline
int just_did_sharpline = 0 static
Definition at line 4323 of file astout.c.
Referenced by write_next_line().
lbuff
char lbuff[CARDB_SIZE] static
Definition at line 43 of file astout.c.
Referenced by acc_pragma(), cuf_pragma(), get_stmt(), label_name(), print_ast(), printast(), put_char(), put_string(), put_u_to_l(), and write_next_line().
max_col
int max_col = 72 static
Definition at line 36 of file astout.c.
Referenced by astout_init(), check_len(), and dbg_print_ast().
op_space
LOGICAL op_space = TRUE static
Definition at line 47 of file astout.c.
Referenced by gen_allocate(), and print_ast().
outfile
FILE* outfile static
Definition at line 34 of file astout.c.
Referenced by _dmp_dent(), dbg_print_ast(), dmp_dent(), dumparref(), dumpsubinfo(), printast(), printastref(), printstdref(), and write_next_line().
struct { ... } params
Referenced by _stb_fixup_ifacearg(), add_param(), astout_init(), end_param(), gen_call_llvm_fm_intrinsic(), gen_call_llvm_intrinsic(), gen_call_llvm_intrinsic_impl(), gen_call_llvm_non_fm_math_intrinsic(), gen_call_pgocl_intrinsic(), gen_call_to_builtin(), handle_arguments(), ll_process_routine_parameters(), lldbg_create_subroutine_type_mdnode(), llMakeFtnOutlinedSignature(), lower_function(), lower_mark_entries(), lower_put_datatype(), lower_symbol(), lower_use_datatype(), lower_visit_symbol(), and replace_fval_in_params().
q
_A_Q q
Definition at line 65 of file astout.c.
Referenced by add_param(), and end_param().
q_e
_A_Q q_e
Definition at line 66 of file astout.c.
struct { ... } vx_params
Referenced by add_param(), astout_init(), and end_param().