flang: astutil.c File Reference
astutil.c File Reference
astutil.c - AST utility program
#include "gbldefs.h"
#include "utils.h"
#include <unistd.h>
Classes
struct symfld
struct symsym
Macros
#define ASTTMPFILE "ASTTMPFILE"
#define LT_SF 1
#define LT_ST 2
#define LT_SM 3
#define LT_SE 4
#define LT_SI 5
#define LT_FL 6
#define LT_TA 7
#define MAXFIELDS 110
#define MAXATTRIB 20
#define MAXATYPES 200
#define MAXFPERS 30
#define SYMLEN 19
Functions
static int addattr ()
static void copy_file (FILE *, FILE *)
static void proc_sym ()
static void flushsym (int *, int, FILE *)
static void addfieldtosym (int *, int, int)
static void write_ast ()
static int qscmp (const void *, const void *)
int main (int aargc, char *aargv[])
...
static int findsym ()
static int addfield (int sharedflag, int flagflag)
static int chk_overlap (int f1, int f2, int flag)
Variables
static LT elt []
static int lt
static char tok [132]
static struct symfld fields [MAXFIELDS]
static int fieldnum
static char attrnames [MAXATTRIB][32]
static int attrnum = 0
static struct symsym symbols [MAXATYPES]
static int symnum
static int checkmode = 0
Detailed Description
astutil.c - AST utility program
Definition in file astutil.c.
Macro Definition Documentation
ASTTMPFILE
#define ASTTMPFILE "ASTTMPFILE"
Definition at line 20 of file astutil.c.
LT_FL
#define LT_FL 6
Definition at line 28 of file astutil.c.
LT_SE
#define LT_SE 4
Definition at line 26 of file astutil.c.
LT_SF
#define LT_SF 1
Definition at line 23 of file astutil.c.
LT_SI
#define LT_SI 5
Definition at line 27 of file astutil.c.
LT_SM
#define LT_SM 3
Definition at line 25 of file astutil.c.
LT_ST
#define LT_ST 2
Definition at line 24 of file astutil.c.
LT_TA
#define LT_TA 7
Definition at line 30 of file astutil.c.
MAXATTRIB
#define MAXATTRIB 20
Definition at line 49 of file astutil.c.
MAXATYPES
#define MAXATYPES 200
Definition at line 55 of file astutil.c.
MAXFIELDS
#define MAXFIELDS 110
Definition at line 45 of file astutil.c.
MAXFPERS
#define MAXFPERS 30
Definition at line 56 of file astutil.c.
SYMLEN
#define SYMLEN 19
Definition at line 67 of file astutil.c.
Function Documentation
addattr()
static int addattr () static
Definition at line 680 of file astutil.c.
References attrnames, attrnum, i, MAXATTRIB, put_error(), and tok.
Referenced by proc_sym().
addfield()
static int addfield (int sharedflag, int flagflag) static
Definition at line 586 of file astutil.c.
References FALSE, fieldnum, fields, symfld::flag, get_token(), i, len, MAXFIELDS, name, symfld::name, symfld::offs, put_error(), symfld::shared, size, symfld::size, SYMLEN, and tok.
Referenced by proc_sym().
addfieldtosym()
static void addfieldtosym (int * cursyms, int cursym, int field) static
Definition at line 529 of file astutil.c.
References chk_overlap(), fields, symsym::fields, i, j, k, symsym::nfields, put_err(), symbols, and TRUE.
Referenced by proc_sym().
chk_overlap()
static int chk_overlap (int f1, int f2, int flag) static
Definition at line 549 of file astutil.c.
References f2, FALSE, fields, put_err(), size, and TRUE.
Referenced by addfieldtosym(), and flushsym().
copy_file()
static void copy_file (FILE * from, FILE * to) static
Definition at line 697 of file astutil.c.
References c.
Referenced by main(), and write_ast().
findsym()
static int findsym () static
Definition at line 569 of file astutil.c.
References i, MAXATYPES, put_error(), symsym::stype, symbols, symnum, and tok.
Referenced by proc_sym().
flushsym()
static void flushsym (int * cursyms, int cursym, FILE * tempf) static
Definition at line 395 of file astutil.c.
References chk_overlap(), FALSE, fclose(), fieldnum, fields, symsym::fields, i, j, k, last, name, symsym::nfields, NULL, OUT1, output(), p, put_err(), qscmp(), size, symfld::size, symbols, SYMLEN, and TRUE.
Referenced by proc_sym().
main()
int main (int aargc, char * aargv[])
...
...
Parameters
argc number of command-line arguments \pram argv array of command-line argument strings
Definition at line 80 of file astutil.c.
References ASTTMPFILE, checkmode, copy_file(), IN3, open_files(), OUT2, proc_sym(), and write_ast().
proc_sym()
static void proc_sym () static
Definition at line 105 of file astutil.c.
References addattr(), addfield(), addfieldtosym(), ASTTMPFILE, symsym::attr, elt, FALSE, fieldnum, FILE, findsym(), flush_line(), flushsym(), get_line1(), get_token(), i, IN1, len, LOOP, lt, LT_EOF, LT_FL, LT_SE, LT_SF, LT_SI, LT_SM, LT_ST, symsym::nattr, NULL, OUT1, put_err(), put_error(), symsym::sname, symbols, symnum, tok, TRUE, and void().
Referenced by main().
qscmp()
static int qscmp (const void * a1, const void * a2) static
Definition at line 370 of file astutil.c.
References f2, fields, name, symfld::offs, and r.
Referenced by flushsym(), and write_ast().
write_ast()
static void write_ast () static
Definition at line 202 of file astutil.c.
References attrnames, attrnum, buff, checkmode, copy_file(), elt, fieldnum, fields, get_line1(), i, IN2, IN4, j, k, LOOP, lt, LT_EOF, LT_SE, LT_ST, LT_TA, MAXFIELDS, name, symsym::nattr, symsym::nfields, OUT2, OUT3, put_err(), put_error(), qscmp(), s, size, strlen(), symbols, symnum, and x.
Referenced by main().
Variable Documentation
attrnames
char attrnames[MAXATTRIB][32] static
Definition at line 50 of file astutil.c.
Referenced by addattr(), and write_ast().
attrnum
int attrnum = 0 static
Definition at line 51 of file astutil.c.
Referenced by addattr(), and write_ast().
checkmode
int checkmode = 0 static
Definition at line 75 of file astutil.c.
Referenced by main(), and write_ast().
elt
LT elt[] static
Initial value:
= {{".SF", LT_SF}, {".ST", LT_ST}, {".SM", LT_SM},
                   {".SE", LT_SE}, {".SI", LT_SI}, {".FL", LT_FL},
                   {".TA", LT_TA}, {"", LT_EOF}}
Definition at line 32 of file astutil.c.
Referenced by proc_sym(), and write_ast().
fieldnum
int fieldnum static
Definition at line 47 of file astutil.c.
Referenced by addfield(), flushsym(), proc_sym(), and write_ast().
fields
struct symfld fields[MAXFIELDS] static
Definition at line 46 of file astutil.c.
Referenced by addfield(), addfieldtosym(), chk_overlap(), flushsym(), qscmp(), and write_ast().
lt
int lt static
Definition at line 35 of file astutil.c.
Referenced by proc_sym(), and write_ast().
symbols
struct symsym symbols[MAXATYPES] static
Referenced by addfieldtosym(), findsym(), flushsym(), proc_sym(), and write_ast().
symnum
int symnum static
Definition at line 65 of file astutil.c.
Referenced by findsym(), proc_sym(), and write_ast().
tok
char tok[132] static
Definition at line 36 of file astutil.c.
Referenced by addattr(), addfield(), collectIncludePaths(), findsym(), main(), proc_sym(), ptok(), and ILMTPApp::run().