flang: async.c File Reference
async.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <aio.h>
#include <signal.h>
#include "stdioInterf.h"
#include "async.h"
Classes
struct asy_transaction_data
struct asy
Macros
#define FIO_MAX_ASYNC_TRANSACTIONS 16
#define ASY_FDACT 0x01 /* fd is active, not fp */
#define ASY_IOACT 0x02 /* asynch i/o is active */
Functions
static int asy_wait (struct asy *asy)
int Fio_asy_fseek (struct asy *asy, long offset, int whence)
Asynchronous fseek.
int Fio_asy_enable (struct asy *asy)
Enable asynchronous IO, disable stdio.
int Fio_asy_disable (struct asy *asy)
Disable asynchronous IO, enable stdio.
int Fio_asy_open (FILE *fp, struct asy **pasy)
Initialize a file for asynchronous IO, called from open.
int Fio_asy_read (struct asy *asy, void *adr, long len)
Start an asynch read.
int Fio_asy_write (struct asy *asy, void *adr, long len)
Start an asynch write.
int Fio_asy_start (struct asy *asy)
int Fio_asy_close (struct asy *asy)
close asynch i/o called from close
Variables
static int slime
Macro Definition Documentation
ASY_FDACT
#define ASY_FDACT 0x01 /* fd is active, not fp */
Definition at line 78 of file async.c.
ASY_IOACT
#define ASY_IOACT 0x02 /* asynch i/o is active */
Definition at line 79 of file async.c.
FIO_MAX_ASYNC_TRANSACTIONS
#define FIO_MAX_ASYNC_TRANSACTIONS 16
Definition at line 36 of file async.c.
Function Documentation
asy_wait()
static int asy_wait (struct asy * asy) static
Definition at line 120 of file async.c.
References __io_errno(), __io_set_errno(), asy::aiocb, ASY_IOACT, asy::atd, asy::fd, FIO_EEOF, asy::flags, asy_transaction_data::len, len, asy_transaction_data::off, asy::outstanding_transactions, p, s, and slime.
Referenced by Fio_asy_close(), Fio_asy_disable(), Fio_asy_enable(), Fio_asy_read(), and Fio_asy_write().
Fio_asy_close()
int Fio_asy_close (struct asy * asy)
close asynch i/o called from close
Definition at line 387 of file async.c.
References ASY_IOACT, asy_wait(), asy::fd, asy::flags, n, and slime.
Fio_asy_disable()
int Fio_asy_disable (struct asy * asy)
Disable asynchronous IO, enable stdio.
Definition at line 211 of file async.c.
References __io_fseekx, ASY_FDACT, ASY_IOACT, asy_wait(), asy::atd, asy::fd, asy::flags, asy::fp, n, asy_transaction_data::off, offset, asy::outstanding_transactions, and slime.
Referenced by __f90io_unf_write(), __f90io_usw_read(), __fortio_rwinit(), __getfile3f(), __unf_init(), _f90io_backspace(), _f90io_rewind(), ENTF90IO(), and inquire().
Fio_asy_enable()
int Fio_asy_enable (struct asy * asy)
Enable asynchronous IO, disable stdio.
Definition at line 180 of file async.c.
References __io_fflush, __io_ftellx, ASY_FDACT, ASY_IOACT, asy_wait(), asy::atd, asy::fd, asy::flags, asy::fp, n, asy_transaction_data::off, asy::outstanding_transactions, and slime.
Referenced by __unf_init().
Fio_asy_fseek()
int Fio_asy_fseek (struct asy * asy, long offset, int whence)
Asynchronous fseek.
Definition at line 164 of file async.c.
References asy::atd, asy::fd, asy_transaction_data::off, offset, asy::outstanding_transactions, and slime.
Referenced by adjust_fpos().
Fio_asy_open()
int Fio_asy_open (FILE * fp, struct asy ** pasy)
Initialize a file for asynchronous IO, called from open.
Definition at line 239 of file async.c.
References __io_getfd(), __io_set_errno(), asy::fd, asy::fp, fp, and slime.
Referenced by ENTF90IO().
Fio_asy_read()
int Fio_asy_read (struct asy * asy, void * adr, long len)
Start an asynch read.
Definition at line 271 of file async.c.
References asy::aiocb, ASY_IOACT, asy_wait(), asy::atd, FALSE, asy::fd, asy::flags, asy_transaction_data::len, len, n, NULL, asy_transaction_data::off, asy::outstanding_transactions, and slime.
Referenced by __f90io_unf_read().
Fio_asy_start()
int Fio_asy_start (struct asy * asy)
\brief For vectored i/o, start reads or writes
Definition at line 377 of file async.c.
References asy::fd, and slime.
Fio_asy_write()
int Fio_asy_write (struct asy * asy, void * adr, long len)
Start an asynch write.
Definition at line 325 of file async.c.
References asy::aiocb, ASY_IOACT, asy_wait(), asy::atd, FALSE, asy::fd, asy::flags, asy_transaction_data::len, len, n, NULL, asy_transaction_data::off, asy::outstanding_transactions, and slime.
Referenced by unf_fwrite().
Variable Documentation
slime
int slime static
Definition at line 81 of file async.c.
Referenced by asy_wait(), Fio_asy_close(), Fio_asy_disable(), Fio_asy_enable(), Fio_asy_fseek(), Fio_asy_open(), Fio_asy_read(), Fio_asy_start(), and Fio_asy_write().