flang: async.h File Reference
async.h File Reference
Macros
#define FIO_EEOF 217
Functions
int Fio_asy_fseek (struct asy *asy, long offset, int whence)
Asynchronous fseek.
int Fio_asy_enable (struct asy *asy)
Enable asynchronous IO, disable stdio.
int Fio_asy_disable (struct asy *asy)
Disable asynchronous IO, enable stdio.
int Fio_asy_open (FILE *fp, struct asy **pasy)
Initialize a file for asynchronous IO, called from open.
int Fio_asy_read (struct asy *asy, void *adr, long len)
Start an asynch read.
int Fio_asy_write (struct asy *asy, void *adr, long len)
Start an asynch write.
int Fio_asy_start (struct asy *asy)
int Fio_asy_close (struct asy *asy)
close asynch i/o called from close
Detailed Description
Externally visiable Fortran asynchronous IO routines (from async.c)
Definition in file async.h.
Macro Definition Documentation
FIO_EEOF
#define FIO_EEOF 217
Definition at line 17 of file async.h.
Function Documentation
Fio_asy_close()
int Fio_asy_close (struct asy * asy)
close asynch i/o called from close
Definition at line 387 of file async.c.
References ASY_IOACT, asy_wait(), asy::fd, asy::flags, n, and slime.
Fio_asy_disable()
int Fio_asy_disable (struct asy * asy)
Disable asynchronous IO, enable stdio.
Definition at line 211 of file async.c.
References __io_fseekx, ASY_FDACT, ASY_IOACT, asy_wait(), asy::atd, asy::fd, asy::flags, asy::fp, n, asy_transaction_data::off, offset, asy::outstanding_transactions, and slime.
Referenced by __f90io_unf_write(), __f90io_usw_read(), __fortio_rwinit(), __getfile3f(), __unf_init(), _f90io_backspace(), _f90io_rewind(), ENTF90IO(), and inquire().
Fio_asy_enable()
int Fio_asy_enable (struct asy * asy)
Enable asynchronous IO, disable stdio.
Definition at line 180 of file async.c.
References __io_fflush, __io_ftellx, ASY_FDACT, ASY_IOACT, asy_wait(), asy::atd, asy::fd, asy::flags, asy::fp, n, asy_transaction_data::off, asy::outstanding_transactions, and slime.
Referenced by __unf_init().
Fio_asy_fseek()
int Fio_asy_fseek (struct asy * asy, long offset, int whence)
Asynchronous fseek.
Definition at line 164 of file async.c.
References asy::atd, asy::fd, asy_transaction_data::off, offset, asy::outstanding_transactions, and slime.
Referenced by adjust_fpos().
Fio_asy_open()
int Fio_asy_open (FILE * fp, struct asy ** pasy)
Initialize a file for asynchronous IO, called from open.
Definition at line 239 of file async.c.
References __io_getfd(), __io_set_errno(), asy::fd, asy::fp, fp, and slime.
Referenced by ENTF90IO().
Fio_asy_read()
int Fio_asy_read (struct asy * asy, void * adr, long len)
Start an asynch read.
Definition at line 271 of file async.c.
References asy::aiocb, ASY_IOACT, asy_wait(), asy::atd, FALSE, asy::fd, asy::flags, asy_transaction_data::len, len, n, NULL, asy_transaction_data::off, asy::outstanding_transactions, and slime.
Referenced by __f90io_unf_read().
Fio_asy_start()
int Fio_asy_start (struct asy * asy)
\brief For vectored i/o, start reads or writes
Definition at line 377 of file async.c.
References asy::fd, and slime.
Fio_asy_write()
int Fio_asy_write (struct asy * asy, void * adr, long len)
Start an asynch write.
Definition at line 325 of file async.c.
References asy::aiocb, ASY_IOACT, asy_wait(), asy::atd, FALSE, asy::fd, asy::flags, asy_transaction_data::len, len, n, NULL, asy_transaction_data::off, asy::outstanding_transactions, and slime.
Referenced by unf_fwrite().