flang: atan_vec.h File Reference
atan_vec.h File Reference
#include <common.h>
Functions
vfloat __attribute__ ((noinline)) atan_vec(vfloat const x)
Function Documentation
__attribute__()
vfloat __attribute__ ((noinline)) const
Definition at line 11 of file atan_vec.h.
References AbsMask, AbsMask_as_float, C1, C2, C3, C4, C5, C6, C7, C8, D1, D2, D3, D4, D5, D6, D7, D8, L1, L2, L3, L4, M1, M2, PI_2, poly, result, signedPi_2, vand_vm_vm_vm(), vcast_vf_f(), vfma_vf_vf_vf_vf(), vgt_vo_vf_vf(), vor_vm_vm_vm(), vreinterpret_vf_vm(), vreinterpret_vm_vf(), vsel_vf_vo_vf_vf(), vxor_vm_vm_vm(), x, x2, x4, x8, xAbs, and xReduced.