flang: atan2_vec.h File Reference
atan2_vec.h File Reference
#include <common.h>
Functions
vfloat __attribute__ ((noinline)) atan2_vec(vfloat const y
Variables
vfloat vfloat const x
const vfloat pi_over_4 = vcast_vf_f(PI_OVER_4)
const vfloat pi_2 = vcast_vf_f(PI_OVER_2)
const vfloat pi = vcast_vf_f(PI)
unsigned long long int AbsMask = 0x7FFFFFFF
float AbsMask_as_float = *(float *)&AbsMask
vfloat yAbs
vfloat xAbs
vopmask yBigger = vgt_vo_vf_vf(yAbs, xAbs)
vfloat xReduced
vfloat x2 = xReduced * xReduced
vfloat x4 = x2 * x2
vfloat x8 = x4 * x4
vfloat x16 = x8 * x8
const vfloat D1 = vcast_vf_f(C1)
const vfloat D2 = vcast_vf_f(C2)
const vfloat D3 = vcast_vf_f(C3)
const vfloat D4 = vcast_vf_f(C4)
const vfloat D5 = vcast_vf_f(C5)
const vfloat D6 = vcast_vf_f(C6)
const vfloat D7 = vcast_vf_f(C7)
const vfloat D8 = vcast_vf_f(C8)
vfloat L1 = vfma_vf_vf_vf_vf(x2, D2, D1)
vfloat L2 = vfma_vf_vf_vf_vf(x2, D4, D3)
vfloat L3 = vfma_vf_vf_vf_vf(x2, D6, D5)
vfloat L4 = vfma_vf_vf_vf_vf(x2, D8, D7)
vfloat M1 = vfma_vf_vf_vf_vf(x4, L2, L1)
vfloat M2 = vfma_vf_vf_vf_vf(x4, L4, L3)
vfloat poly = vfma_vf_vf_vf_vf(x8, M2, M1)
vfloat result_f = poly
unsigned long long int SignBit = 0x80000000
float SignBit_as_float = *(float *)&SignBit
vfloat SignBit_as_floatV = vcast_vf_f(SignBit_as_float)
vfloat signedPi_2
vfloat pi_factor = vsel_vf_vo_vf_vf(yBigger, signedPi_2, vcast_vf_f(0.0f))
const vfloat signedPi
vint2 pi_factor_as_vmask
vfloat special_return_value
vint2 special_yx_zero_zero_as_int
vfloat special_yx_zero_zero
Function Documentation
__attribute__()
vfloat __attribute__ ((noinline)) const
References PI_3_OVER_4, and vcast_vf_f().
Variable Documentation
AbsMask
unsigned long long int AbsMask = 0x7FFFFFFF
Definition at line 19 of file atan2_vec.h.
AbsMask_as_float
float AbsMask_as_float = *(float *)&AbsMask
Definition at line 20 of file atan2_vec.h.
Referenced by __attribute__().
D1
const vfloat D1 = vcast_vf_f(C1)
Definition at line 51 of file atan2_vec.h.
Referenced by __attribute__(), __fvd_acos_fma3(), __fvd_acos_fma3_256(), __fvd_asin_fma3(), __fvd_asin_fma3_256(), __fvs_acos_fma3(), __fvs_acos_fma3_256(), __fvs_asin_fma3(), __fvs_asin_fma3_256(), __rvs_log_fma3(), and __rvs_log_fma3_256().
D2
const vfloat D2 = vcast_vf_f(C2)
Definition at line 52 of file atan2_vec.h.
D3
const vfloat D3 = vcast_vf_f(C3)
Definition at line 53 of file atan2_vec.h.
D4
const vfloat D4 = vcast_vf_f(C4)
Definition at line 54 of file atan2_vec.h.
D5
const vfloat D5 = vcast_vf_f(C5)
Definition at line 55 of file atan2_vec.h.
D6
const vfloat D6 = vcast_vf_f(C6)
Definition at line 56 of file atan2_vec.h.
D7
const vfloat D7 = vcast_vf_f(C7)
Definition at line 57 of file atan2_vec.h.
D8
const vfloat D8 = vcast_vf_f(C8)
Definition at line 58 of file atan2_vec.h.
L1
vfloat L1 = vfma_vf_vf_vf_vf(x2, D2, D1)
Definition at line 61 of file atan2_vec.h.
L2
vfloat L2 = vfma_vf_vf_vf_vf(x2, D4, D3)
Definition at line 62 of file atan2_vec.h.
L3
vfloat L3 = vfma_vf_vf_vf_vf(x2, D6, D5)
Definition at line 63 of file atan2_vec.h.
L4
vfloat L4 = vfma_vf_vf_vf_vf(x2, D8, D7)
Definition at line 64 of file atan2_vec.h.
M1
vfloat M1 = vfma_vf_vf_vf_vf(x4, L2, L1)
Definition at line 67 of file atan2_vec.h.
M2
vfloat M2 = vfma_vf_vf_vf_vf(x4, L4, L3)
Definition at line 68 of file atan2_vec.h.
pi
const vfloat pi = vcast_vf_f(PI)
Definition at line 17 of file atan2_vec.h.
pi_2
const vfloat pi_2 = vcast_vf_f(PI_OVER_2)
Definition at line 16 of file atan2_vec.h.
pi_factor
pi_factor = vsel_vf_vo_vf_vf(yBigger, signedPi_2, vcast_vf_f(0.0f))
Definition at line 84 of file atan2_vec.h.
pi_factor_as_vmask
vint2 pi_factor_as_vmask
Initial value:
=
        (~vgt_vi2_vi2_vi2(vreinterpret_vi2_vf(x), vcast_vi2_i(-1))) &
        vreinterpret_vi2_vf(signedPi)
Definition at line 97 of file atan2_vec.h.
pi_over_4
const vfloat pi_over_4 = vcast_vf_f(PI_OVER_4)
Definition at line 15 of file atan2_vec.h.
poly
vfloat poly = vfma_vf_vf_vf_vf(x8, M2, M1)
Definition at line 70 of file atan2_vec.h.
result_f
return result_f = poly
Definition at line 72 of file atan2_vec.h.
Referenced by atan2_scalar().
SignBit
unsigned long long int SignBit = 0x80000000
Definition at line 75 of file atan2_vec.h.
SignBit_as_float
float SignBit_as_float = *(float *)&SignBit
Definition at line 76 of file atan2_vec.h.
SignBit_as_floatV
vfloat SignBit_as_floatV = vcast_vf_f(SignBit_as_float)
Definition at line 77 of file atan2_vec.h.
signedPi
const vfloat signedPi
Initial value:
= vreinterpret_vf_vm(
        vreinterpret_vm_vf(pi) |
        (vreinterpret_vm_vf(y) & vreinterpret_vm_vf(SignBit_as_floatV)))
Definition at line 91 of file atan2_vec.h.
signedPi_2
vfloat signedPi_2
Initial value:
= vreinterpret_vf_vm(
        vreinterpret_vm_vf(pi_2) |
        (vreinterpret_vm_vf(xReduced) & vreinterpret_vm_vf(SignBit_as_floatV)))
Definition at line 80 of file atan2_vec.h.
special_return_value
special_return_value
Initial value:
= vsel_vf_vo_vf_vf(
        vlt_vo_vf_vf(x, vcast_vf_f(0.0f)), pi_3_over_4, pi_over_4)
Definition at line 108 of file atan2_vec.h.
special_yx_zero_zero
vfloat special_yx_zero_zero
Initial value:
=
        vreinterpret_vf_vi2(special_yx_zero_zero_as_int)
Definition at line 116 of file atan2_vec.h.
special_yx_zero_zero_as_int
vint2 special_yx_zero_zero_as_int
Initial value:
=
        ~vgt_vi2_vi2_vi2(vreinterpret_vi2_vf(x), vcast_vi2_i(-1)) &
        vreinterpret_vi2_vf(pi)
Definition at line 112 of file atan2_vec.h.
x
vfloat vfloat const x
Initial value:
{
    const vfloat pi_3_over_4 = vcast_vf_f(PI_3_OVER_4)
Definition at line 11 of file atan2_vec.h.
x16
vfloat x16 = x8 * x8
Definition at line 48 of file atan2_vec.h.
x2
vfloat x2 = xReduced * xReduced
Definition at line 45 of file atan2_vec.h.
x4
vfloat x4 = x2 * x2
Definition at line 46 of file atan2_vec.h.
x8
vfloat x8 = x4 * x4
Definition at line 47 of file atan2_vec.h.
xAbs
vfloat xAbs
Initial value:
= vreinterpret_vf_vm(
        vand_vm_vm_vm(vreinterpret_vm_vf(x),
                      vreinterpret_vm_vf(vcast_vf_f(AbsMask_as_float))))
Definition at line 26 of file atan2_vec.h.
xReduced
xReduced
Initial value:
=
        vsel_vf_vo_vf_vf(yBigger, x, y) / vsel_vf_vo_vf_vf(yBigger, y, x)
Definition at line 40 of file atan2_vec.h.
yAbs
vfloat yAbs
Initial value:
= vreinterpret_vf_vm(
        vand_vm_vm_vm(vreinterpret_vm_vf(y),
                      vreinterpret_vm_vf(vcast_vf_f(AbsMask_as_float))))
Definition at line 22 of file atan2_vec.h.
yBigger
vopmask yBigger = vgt_vo_vf_vf(yAbs, xAbs)
Definition at line 30 of file atan2_vec.h.