flang: atan_d_vec.h File Reference
atan_d_vec.h File Reference
#include <common.h>
Functions
vdouble __attribute__ ((noinline)) atan_d_vec(vdouble const x)
Function Documentation
__attribute__()
vdouble __attribute__ ((noinline)) const
Definition at line 11 of file atan_d_vec.h.
References AbsMask, AbsMask_as_double, C10, C11, C12, C13, C14, C15, C16, C17, C18, C19, C2, C20, C3, C4, C5, C6, C7, C8, C9, D10, D11, D12, D13, D14, D15, D16, D17, D18, D19, D2, D20, D3, D4, D5, D6, D7, D8, D9, L1, L2, L3, L4, L5, L6, L7, L8, M1, M2, M3, M4, N1, N2, PI_2, poly, result, signedPi_2, vand_vm_vm_vm(), vcast_vd_d(), vfma_vd_vd_vd_vd(), vgt_vo_vd_vd(), vor_vm_vm_vm(), vreinterpret_vd_vm(), vreinterpret_vm_vd(), vsel_vd_vo_vd_vd(), vxor_vm_vm_vm(), x, x16, x2, x4, x8, and xReduced.