flang: atol.c File Reference
atol.c File Reference
#include <stdlib.h>
#include "global.h"
Functions
int __fort_atol (char *p)
long __fort_strtol (const char *str, char **ptr, int base)
Function Documentation
__fort_atol()
int __fort_atol (char * p)
Definition at line 12 of file atol.c.
References n, p, and q.
__fort_strtol()
long __fort_strtol (const char * str, char ** ptr, int base)
Definition at line 39 of file atol.c.
References base, end, FLANG_FALLTHROUGH, NULL, str, and val.
Referenced by __fort_getoptn(), __fort_initcom(), __fort_sethand(), and __fort_trac_init().