flang: backspace.c File Reference
backspace.c File Reference
Implements Fortran BACKSPACE statement.
#include "global.h"
#include "async.h"
#include "stdioInterf.h"
Macros
#define RCWSZ sizeof(int)
this must match RCWSZ defined in unf.c - is the number of bytes used to represent the length that is stored with an unformatted record
Functions
static int _f90io_backspace (__INT_T *unit, __INT_T *bitv, __INT_T *iostat, int swap_bytes)
__INT_T ENTF90IO (BACKSPACE, backspace)
__INT_T ENTCRF90IO (BACKSPACE, backspace)
__INT_T ENTF90IO (SWBACKSPACE, swbackspace)
__INT_T ENTCRF90IO (SWBACKSPACE, swbackspace)
Detailed Description
Implements Fortran BACKSPACE statement.
Definition in file backspace.c.
Macro Definition Documentation
RCWSZ
#define RCWSZ sizeof(int)
this must match RCWSZ defined in unf.c - is the number of bytes used to represent the length that is stored with an unformatted record
Definition at line 19 of file backspace.c.
Function Documentation
_f90io_backspace()
static int _f90io_backspace (__INT_T * unit, __INT_T * bitv, __INT_T * iostat, int swap_bytes) static
Definition at line 22 of file backspace.c.
References __fortio_errinit03(), __fortio_error(), __fortio_find_unit(), __fortio_swap_bytes(), __INT, __io_binary_mode(), __io_errno(), __io_ferror(), __io_fgetc, __io_fputc(), __io_fread, __io_fseek, __io_ftell, fcb::acc, assert, fcb::asy_rw, fcb::asyptr, fcb::binary, bitv, fcb::byte_swap, fcb::coherent, fcb::eof_flag, f, FALSE, FILE, Fio_asy_disable(), FIO_DIRECT, FIO_EDIRECT, FIO_EUNIT, FIO_FORMATTED, FIO_UNFORMATTED, fcb::form, fcb::fp, fp, ILLEGAL_UNIT, fcb::native, fcb::nextrec, fcb::nonadvance, NULL, pos, RCWSZ, TRUE, and fcb::truncflag.
Referenced by ENTCRF90IO(), and ENTF90IO().
ENTCRF90IO() [1/2]
__INT_T ENTCRF90IO (BACKSPACE , backspace)
Definition at line 142 of file backspace.c.
References __fortio_errend03(), _f90io_backspace(), bitv, and s.
ENTCRF90IO() [2/2]
__INT_T ENTCRF90IO (SWBACKSPACE , swbackspace)
Definition at line 163 of file backspace.c.
References __fortio_errend03(), _f90io_backspace(), bitv, and s.
ENTF90IO() [1/2]
__INT_T ENTF90IO (BACKSPACE , backspace)
Definition at line 130 of file backspace.c.
References __fort_status_init(), __fortio_errend03(), _f90io_backspace(), bitv, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, and s.
ENTF90IO() [2/2]
__INT_T ENTF90IO (SWBACKSPACE , swbackspace)
Definition at line 151 of file backspace.c.
References __fort_status_init(), __fortio_errend03(), _f90io_backspace(), bitv, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, and s.