flang: bblock.c File Reference
bblock.c File Reference
Fortran front-end basic block module.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "ast.h"
#include "semant.h"
#include "soc.h"
#include "transfrm.h"
#include "extern.h"
#include "dinit.h"
#include "fdirect.h"
#include "pd.h"
#include "rtlRtns.h"
Functions
static void init_newargs (int)
static void assumshp_args (int)
static void adj_based_arrays (void)
static void gen_early_bnd_dependencies (int)
static void add_bound_assignments (int)
static void set_std_parflags (int)
static void gen_early_array_bnds (int sptr)
static void gen_early_str_len ()
void bblock_init ()
Called from semant_init().
int bblock ()
Return nonzero if there are any CUDA Fortran kernels.
static void find_assumshp_dep (int)
static LOGICAL _find_assumshp_dep (int, LOGICAL *)
static void add_assumshp (int)
static int early_specification_stmt_needed (int ast)
static void add_to_early_bnd_list (int ast)
static void merge (int, int)
void merge_commons ()
Merge common blocks.
static LOGICAL same_datatype (int s1, int s2)
static void rewrite_all_asts ()
static int make_equiv_ss (ISZ_T pos, int dtype)
static int smallest_dtype (int cmn)
static void add_equivalence (int cmn1, int cmn2, int mem1, int mem2)
static void add_soc (int mem1, int mem2)
void renumber_lines ()
static void mark_symbol (int sptr, int limit)
static void mark (int sptr, int limit)
static void mark_used_variable (int ast, int *plimit)
static void mark_ast (int ast, int limit)
static void mark_dtype (int dtype, int limit)
static void mark_used_in_independent (INDEP_INFO *indep)
static void check_used_in_data ()
static LOGICAL must_mark (int sptr)
void eliminate_unused_variables (int which)
For XBIT(57,0x2000), eliminate declarations of any unused variables, unless they are in COMMON.
Variables
static int entry_point
static int par
static int cs
static int parsect
static int task
static int atomic
static int kernel
struct {
int * base
int sz
int avl
} erly_bnds_depd = {NULL, 0, 0}
struct {
int * abase
int acnt
int sacnt
} assumshp
static int donetwice1
static int donetwice2
static int merge_common_symbol
static int merge_member
static int renumber = 0
static int eliminate_save_alignments
static int eliminate_save_distributed
Detailed Description
Fortran front-end basic block module.
Definition in file bblock.c.
Function Documentation
_find_assumshp_dep()
static LOGICAL _find_assumshp_dep (int ast, LOGICAL * rr) static
Definition at line 564 of file bblock.c.
References ast, DTY, FALSE, and find_assumshp_dep().
Referenced by find_assumshp_dep().
add_assumshp()
static void add_assumshp (int arg) static
Definition at line 585 of file bblock.c.
References arg, assumshp, and i.
Referenced by assumshp_args(), and find_assumshp_dep().
add_bound_assignments()
static void add_bound_assignments (int sym) static
Definition at line 862 of file bblock.c.
References a, AD_DPTR, AD_LWAST, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_UPAST, AD_UPBD, AD_ZBASE, add_stmt_after(), ast, ast_visit(), astb, BLOCK_ENDPROLOG_STD, ASTB::bnd, ASTB::dtype, entry_point, i, mk_assn_stmt(), mk_binop(), mk_mlpyr_expr(), ASTB::one, OP_ADD, OP_MUL, STD_PREV, and tmp.
Referenced by adj_based_arrays().
add_equivalence()
static void add_equivalence (int cmn1, int cmn2, int mem1, int mem2) static
Definition at line 1170 of file bblock.c.
References add_equivalence(), ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_NUMELM, ADD_UPAST, ADD_UPBD, ADD_ZBASE, astb, STB::curr_scope, DBGBIT, DT_INT, DTY, EQV, SEM::eqv_avail, SEM::eqv_base, SEM::eqv_size, SEM::eqvlist, gbl, get_array_dtype(), get_next_sym(), ASTB::i1, ISZ_T, m2, make_equiv_ss(), merge_common_symbol, merge_member, mk_cval(), NEED, off, s, sem, size, size_of(), smallest_dtype(), ss, stb, and SYMNAME.
Referenced by add_equivalence(), and merge().
add_soc()
static void add_soc (int mem1, int mem2) static
Definition at line 1327 of file bblock.c.
References SOC::avail, SOC::base, NEED, NEW, SOC_ITEM::next, SOC::size, soc, SOC_NEXT, SOC_SPTR, and SOC_ITEM::sptr.
Referenced by merge().
add_to_early_bnd_list()
static void add_to_early_bnd_list (int ast) static
Definition at line 643 of file bblock.c.
References ast, erly_bnds_depd, and NEED.
Referenced by gen_early_array_bnds(), gen_early_bnd_dependencies(), and gen_early_str_len().
adj_based_arrays()
static void adj_based_arrays (void) static
Definition at line 843 of file bblock.c.
References add_bound_assignments(), gbl, gen_early_array_bnds(), NOSYM, and sptr.
Referenced by bblock().
assumshp_args()
static void assumshp_args (int ent) static
Definition at line 471 of file bblock.c.
References add_assumshp(), arg, assumshp, ast_unvisit(), ast_visit(), aux, cnt, AUX::dpdsc_base, DTY, entry_point, find_assumshp_dep(), FREE, i, NEW, set_assumed_bounds(), and TRUE.
Referenced by bblock().
bblock()
int bblock (void)
Return nonzero if there are any CUDA Fortran kernels.
Definition at line 61 of file bblock.c.
References add_stmt_after(), add_stmt_before(), adj_based_arrays(), SEM::alloc_mem_initialize, assumshp_args(), ast, ast_unvisit(), ast_visit(), astb, atomic, SEM::auto_dealloc, SEM::auto_finalize, BLOCK_ENTRY_STD, BLOCK_EXIT_STD, cs, DBGBIT, DT_INT, dump_std(), entry_point, erly_bnds_depd, FREE, gbl, gen_alloc_mem_initialize_for_sym(), gen_conditional_dealloc_for_sym(), gen_early_str_len(), gen_finalization_for_sym(), gen_type_initialize_for_sym(), getlab(), getsymbol(), ASTB::i0, init_newargs(), itemp, kernel, label, last_std, mk_assn_stmt(), mk_cval(), mk_id(), mk_label(), mk_stmt(), NEW, new_ast(), new_std(), NOSYM, NULL, par, parsect, RFCNTI, RU_PROG, s, sem, set_std_parflags(), sptr, std, STD_AST, STD_ATOMIC, STD_CS, STD_LABEL, STD_LAST, STD_LINENO, STD_NEXT, STD_PAR, STD_PARSECT, STD_PREV, STD_TASK, stdx, task, SEM::temps_reset, tmp, TRUE, SEM::type_initialize, and void().
bblock_init()
void bblock_init (void)
Called from semant_init().
Definition at line 54 of file bblock.c.
Referenced by semant_init().
check_used_in_data()
static void check_used_in_data () static
Definition at line 1592 of file bblock.c.
References ast, astb, ASTB::df, Doend, Dostart, VAR::dostart, flg, VAR::id, VAR::indvar, FLG::ipa, lineno, mark_ast(), VAR::next, NULL, VAR::ptr, VAR::u, Varref, and VAR::varref.
Referenced by eliminate_unused_variables().
early_specification_stmt_needed()
static int early_specification_stmt_needed (int ast) static
Definition at line 598 of file bblock.c.
References argt, ARGT_ARG, ARGT_CNT, ast, early_specification_stmt_needed(), FALSE, i, sptr, and TRUE.
Referenced by early_specification_stmt_needed(), gen_early_array_bnds(), and gen_early_str_len().
eliminate_unused_variables()
void eliminate_unused_variables (int which)
For XBIT(57,0x2000), eliminate declarations of any unused variables, unless they are in COMMON.
Definition at line 1666 of file bblock.c.
References assert, ast, ast_traverse(), ast_unvisit(), ast_visit(), aux, DIRECT::avail, check_used_in_data(), direct, eliminate_save_alignments, eliminate_save_distributed, STB::firstusym, FLANG_FALLTHROUGH, gbl, AUX::list, DIRECT::lpg, mark(), mark_symbol(), mark_used_in_independent(), mark_used_variable(), must_mark(), NOSYM, NULL, RU_BDATA, sptr, stb, std, STD_AST, STD_NEXT, and DIRECT::stgb.
find_assumshp_dep()
static void find_assumshp_dep (int arg) static
Definition at line 541 of file bblock.c.
References _find_assumshp_dep(), AD_DPTR, AD_LWBD, AD_NUMDIM, add_assumshp(), arg, ast_traverse(), d, lb, ndim, and NULL.
Referenced by _find_assumshp_dep(), and assumshp_args().
gen_early_array_bnds()
static void gen_early_array_bnds (int sptr) static
Definition at line 785 of file bblock.c.
References AD_DPTR, AD_LWAST, AD_LWBD, AD_NUMDIM, AD_UPAST, AD_UPBD, add_stmt_after(), add_stmt_before(), add_to_early_bnd_list(), astb, BLOCK_ENDPROLOG_STD, ASTB::bnd, ASTB::dtype, early_specification_stmt_needed(), entry_point, erly_bnds_depd, FALSE, gen_early_bnd_dependencies(), i, mk_assn_stmt(), ndims, sptr, TRUE, and void().
Referenced by adj_based_arrays().
gen_early_bnd_dependencies()
static void gen_early_bnd_dependencies (int ast) static
Definition at line 651 of file bblock.c.
References AD_DPTR, AD_LWAST, AD_LWBD, AD_NUMDIM, AD_UPAST, AD_UPBD, add_stmt_after(), add_to_early_bnd_list(), argt, ARGT_ARG, ARGT_CNT, ast, ast_intr(), astb, BLOCK_ENTRY_STD, ASTB::bnd, DDTG, DT_INT, DTY, ASTB::dtype, FALSE, gbl, gen_early_bnd_dependencies(), i, mk_assn_stmt(), mk_convert(), mk_cval(), mk_id(), ndims, sptr, std, sym_get_scalar(), SYMNAME, and TRUE.
Referenced by gen_early_array_bnds(), gen_early_bnd_dependencies(), and gen_early_str_len().
gen_early_str_len()
static void gen_early_str_len () static
Definition at line 743 of file bblock.c.
References add_stmt_after(), add_stmt_before(), add_to_early_bnd_list(), ast_intr(), BLOCK_ENDPROLOG_STD, DDTG, DT_INT, DTY, early_specification_stmt_needed(), entry_point, erly_bnds_depd, gbl, gen_early_bnd_dependencies(), i, mk_assn_stmt(), mk_convert(), mk_cval(), mk_id(), NOSYM, sptr, sym_get_scalar(), SYMNAME, and void().
Referenced by bblock().
init_newargs()
static void init_newargs (int ent) static
Definition at line 406 of file bblock.c.
References arg, aux, CNULL, DDTG, AUX::dpdsc_base, DTY, error(), gbl, i, is_bad_dtype(), NEWDSCG, NEWDSCP, sym_get_arg_sec(), sym_get_formal(), SYMNAME, and XBIT.
Referenced by bblock().
make_equiv_ss()
static int make_equiv_ss (ISZ_T pos, int dtype) static
Definition at line 1095 of file bblock.c.
References ADD_LWBD, ADD_NUMDIM, ADD_UPBD, astb, CONVAL2G, DT_INT, EQV_NUMSS, EQV_SS, SEM::eqv_ss_avail, SEM::eqv_ss_base, SEM::eqv_ss_size, i, ASTB::i1, interr(), lb, mk_cval(), NEED, p, pos, sem, SIZE, ss, and ub.
Referenced by add_equivalence().
mark()
static void mark (int sptr, int limit) static
Definition at line 1454 of file bblock.c.
References mark_symbol(), sptr, and stb.
Referenced by add_store(), complt(), eliminate_unused_variables(), invariant_mark(), mark_symbol(), and mark_used_variable().
mark_ast()
static void mark_ast (int ast, int limit) static
Definition at line 1487 of file bblock.c.
References ast, ast_traverse(), astb, mark_used_variable(), and NULL.
Referenced by check_used_in_data(), mark_dtype(), mark_symbol(), and mark_used_in_independent().
mark_dtype()
static void mark_dtype (int dtype, int limit) static
Definition at line 1497 of file bblock.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_NUMDIM, ADD_NUMELM, ADD_UPAST, ADD_UPBD, ADD_ZBASE, DTY, i, mark_ast(), mark_dtype(), n, and NOSYM.
Referenced by mark_dtype(), and mark_symbol().
mark_symbol()
static void mark_symbol (int sptr, int limit) static
Definition at line 1528 of file bblock.c.
References mark(), mark_ast(), mark_dtype(), PARAMVALG, and sptr.
Referenced by eliminate_unused_variables(), mark(), and mark_used_in_independent().
mark_used_in_independent()
static void mark_used_in_independent (INDEP_INFO * indep) static
Definition at line 1562 of file bblock.c.
References list, mark_ast(), and mark_symbol().
Referenced by eliminate_unused_variables().
mark_used_variable()
static void mark_used_variable (int ast, int * plimit) static
Definition at line 1468 of file bblock.c.
References ast, mark(), and sptr.
Referenced by eliminate_unused_variables(), and mark_ast().
merge()
static void merge (int cmn1, int cmn2) static
Definition at line 1349 of file bblock.c.
References add_equivalence(), add_soc(), ast_replace(), ast_unvisit(), ast_visit(), CMEMLG, CMEMLP, DBGBIT, gbl, ISZ_T, merge_common_symbol, merge_member, mk_id(), NOSYM, rewrite_all_asts(), same_datatype(), size_of(), and SYMNAME.
Referenced by merge_commons(), and trnred().
merge_commons()
void merge_commons (void)
Merge common blocks.
If two modules declare the same common block, both sets of symbols appear in the program. If either uses the same variable names, by Fortran 90 rules, the names may not be used, though they could be hidden by USE, ONLY clauses. To generate correct output, we must merge the two definitions. This routine checks that the distributed variables in the duplicate commons have the same type, distribution, offsets, and sizes. It replaces all references to one of the commons by references to the other. For nondistributed data, this routine generates EQUIVALENCE data.
Definition at line 973 of file bblock.c.
References donetwice1, donetwice2, gbl, merge(), and NOSYM.
must_mark()
static LOGICAL must_mark (int sptr) static
Definition at line 1634 of file bblock.c.
References ALIGNG, DISTG, eliminate_save_distributed, FALSE, sptr, and TRUE.
Referenced by eliminate_unused_variables().
renumber_lines()
void renumber_lines (void)
Definition at line 1441 of file bblock.c.
References renumber, std, STD_LINENO, and STD_NEXT.
rewrite_all_asts()
static void rewrite_all_asts () static
Definition at line 1051 of file bblock.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_NUMDIM, ADD_NUMELM, ADD_UPAST, ADD_UPBD, ADD_ZBASE, ast_rewrite(), dim, dlen(), STB::dt, DTY, ss, stb, std, STD_AST, and STD_NEXT.
Referenced by merge().
same_datatype()
static LOGICAL same_datatype (int s1, int s2) static
Definition at line 1041 of file bblock.c.
References eq_dtype(), FALSE, and TRUE.
Referenced by merge().
set_std_parflags()
static void set_std_parflags (int std) static
Definition at line 943 of file bblock.c.
References cs, kernel, par, parsect, std, STD_CS, STD_KERNEL, STD_PAR, STD_PARSECT, STD_TASK, and task.
Referenced by bblock().
smallest_dtype()
static int smallest_dtype (int cmn) static
Definition at line 1140 of file bblock.c.
References DT_INT, DTY, mem(), NOSYM, size, size_of(), and TY_CHAR.
Referenced by add_equivalence().
Variable Documentation
abase
int* abase
Definition at line 457 of file bblock.c.
acnt
int acnt
Definition at line 458 of file bblock.c.
Referenced by copy_initconst_to_array(), and ftn_i_shift64().
struct { ... } assumshp
Referenced by add_assumshp(), assumshp_args(), and ref_pd().
atomic
int atomic static
Definition at line 33 of file bblock.c.
Referenced by bblock().
avl
int avl
Definition at line 48 of file bblock.c.
base
int* base
Definition at line 46 of file bblock.c.
cs
int cs static
Definition at line 30 of file bblock.c.
Referenced by __fort_cyclic_loop(), bblock(), copy_loop(), cyclic_setup(), ENTFTN(), export_one_std(), export_symbol(), fill_cyclic_k(), gen_contig_check(), mmul_mxm(), mmul_mxv(), mmul_vxm(), new_stds(), outvalue_hcycliclp(), and set_std_parflags().
donetwice1
int donetwice1 static
Definition at line 958 of file bblock.c.
Referenced by merge_commons().
donetwice2
int donetwice2 static
Definition at line 958 of file bblock.c.
Referenced by merge_commons().
eliminate_save_alignments
int eliminate_save_alignments static
Definition at line 1450 of file bblock.c.
Referenced by eliminate_unused_variables().
eliminate_save_distributed
int eliminate_save_distributed static
Definition at line 1451 of file bblock.c.
Referenced by eliminate_unused_variables(), and must_mark().
entry_point
int entry_point static
Definition at line 28 of file bblock.c.
Referenced by add_bound_assignments(), assumshp_args(), bblock(), gen_early_array_bnds(), and gen_early_str_len().
struct { ... } erly_bnds_depd
Referenced by add_to_early_bnd_list(), bblock(), gen_early_array_bnds(), and gen_early_str_len().
kernel
int kernel static
Definition at line 34 of file bblock.c.
Referenced by bblock(), and set_std_parflags().
merge_common_symbol
int merge_common_symbol static
Definition at line 1091 of file bblock.c.
Referenced by add_equivalence(), and merge().
merge_member
int merge_member static
Definition at line 1092 of file bblock.c.
Referenced by add_equivalence(), and merge().
par
int par static
Definition at line 29 of file bblock.c.
Referenced by __fort_par_open(), addssassignments(), ast_to_comment(), bblock(), export_one_std(), forall_dependency(), get_temp_forall2(), hoist_comms(), new_stds(), and set_std_parflags().
parsect
int parsect static
Definition at line 31 of file bblock.c.
Referenced by bblock(), export_one_std(), new_stds(), and set_std_parflags().
renumber
int renumber = 0 static
Definition at line 1439 of file bblock.c.
Referenced by renumber_lines().
sacnt
int sacnt
Definition at line 459 of file bblock.c.
sz
int sz
Definition at line 47 of file bblock.c.
task
int task static
Definition at line 32 of file bblock.c.
Referenced by addDeferredTbp(), addExplicitIface(), addFinalSubroutine(), addNonOverridableTbp(), addNoPassArg(), addPassArg(), addPrivateAttribute(), addPublicAttribute(), addssassignments(), addTbpInterface(), addToDtype(), bblock(), clearStaleRecs(), dtypeHasTbp(), enqueueTbp(), exp_smp(), forall_dependency(), inheritTbps(), initFinalSub(), initTbp(), ll_make_kmpc_task_arg(), llGetTask(), llmp_create_task(), llmp_get_task(), llmp_reset_uplevel(), llmp_task_add(), llmp_task_add_loopvar(), llmp_task_add_private(), llmp_task_get_by_fnsptr(), llmp_task_get_private(), llmp_task_get_privoff(), llmp_task_get_size(), llmp_task_set_fnsptr(), queue_tbp(), read_symbol(), requiresOverloading(), resolveBind(), resolveGeneric(), resolveImp(), resolvePass(), resolveTbps(), semCheckTbp(), and set_std_parflags().