flang: bcopy.c File Reference
bcopy.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
Functions
void __fort_bcopy (char *to, char *fr, size_t n)
Function Documentation
__fort_bcopy()
void __fort_bcopy (char * to, char * fr, size_t n)
Definition at line 12 of file bcopy.c.
References n.
Referenced by __fort_bcopysl(), __fort_copy_descriptor(), __fort_map(), __fort_zwrite(), ENTF90(), ENTFTN(), if(), merge_ent(), process_final_procedures(), ptr_assign(), ptr_assn(), and sourced_alloc_and_assign().