flang: bcopys.c File Reference
bcopys.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
Macros
#define ALIGNMASK(typ) (sizeof(typ) - 1)
Functions
void __fort_bcopysl (char *to, char *fr, size_t cnt, size_t tostr, size_t frstr, size_t len)
Macro Definition Documentation
ALIGNMASK
#define ALIGNMASK (typ) (sizeof(typ) - 1)
Definition at line 20 of file bcopys.c.
Function Documentation
__fort_bcopysl()
void __fort_bcopysl (char * to, char * fr, size_t cnt, size_t tostr, size_t frstr, size_t len)
Definition at line 23 of file bcopys.c.
References __fort_bcopy(), ALIGNMASK, cnt, i, j, k, len, and n.
Referenced by __fort_ebcopys(), fills_loop(), and local_copy().