flang: bessel_tyn.c File Reference
bessel_tyn.c File Reference
Functions
float __mth_i_bessel_y0 (float arg)
float __mth_i_bessel_y1 (float arg)
float __mth_i_bessel_yn (int n, float arg)
void f90_bessel_yn (float *rslts, int *n1, int *n2, float *x)
Function Documentation
__mth_i_bessel_y0()
float __mth_i_bessel_y0 (float arg)
Definition at line 14 of file bessel_y0.c.
References arg, BESSEL_Y0F, and f.
Referenced by f90_bessel_yn().
__mth_i_bessel_y1()
float __mth_i_bessel_y1 (float arg)
Definition at line 14 of file bessel_y1.c.
References arg, BESSEL_Y1F, and f.
Referenced by f90_bessel_yn().
__mth_i_bessel_yn()
float __mth_i_bessel_yn (int n, float arg)
Definition at line 14 of file bessel_yn.c.
References arg, BESSEL_YNF, f, and n.
Referenced by f90_bessel_yn().
f90_bessel_yn()
void f90_bessel_yn (float * rslts, int * n1, int * n2, float * x)
Definition at line 15 of file bessel_tyn.c.
References __mth_i_bessel_y0(), __mth_i_bessel_y1(), __mth_i_bessel_yn(), i, n1, n2, and x.