flang: bessel_tjn.c File Reference
bessel_tjn.c File Reference
Functions
float __mth_i_bessel_j0 (float arg)
float __mth_i_bessel_j1 (float arg)
float __mth_i_bessel_jn (int n, float arg)
void f90_bessel_jn (float *rslts, int *n1, int *n2, float *x)
Function Documentation
__mth_i_bessel_j0()
float __mth_i_bessel_j0 (float arg)
Definition at line 14 of file bessel_j0.c.
References arg, BESSEL_J0F, and f.
Referenced by f90_bessel_jn().
__mth_i_bessel_j1()
float __mth_i_bessel_j1 (float arg)
Definition at line 14 of file bessel_j1.c.
References arg, BESSEL_J1F, and f.
Referenced by f90_bessel_jn().
__mth_i_bessel_jn()
float __mth_i_bessel_jn (int n, float arg)
Definition at line 14 of file bessel_jn.c.
References arg, BESSEL_JNF, f, and n.
Referenced by f90_bessel_jn().
f90_bessel_jn()
void f90_bessel_jn (float * rslts, int * n1, int * n2, float * x)
Definition at line 15 of file bessel_tjn.c.
References __mth_i_bessel_j0(), __mth_i_bessel_j1(), __mth_i_bessel_jn(), i, n1, n2, and x.