flang: bihutil.cpp File Reference
bihutil.cpp File Reference
C and Fortran BIH utility module.
#include "bihutil.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "ilm.h"
#include "fih.h"
#include "ili.h"
#include "expand.h"
#include "regutil.h"
#include "machreg.h"
Macros
#define MAXBIH 67108864
Functions
int getcon ()
int mkfunc ()
void rdilts ()
void wrilts ()
void bih_init (void)
Initialize BIH area.
void bih_cleanup ()
...
int exp_addbih (int after)
Add a new block during the expand phase.
int addnewbih (int after, int flags, int fih)
Universal function to create new BIH entry.
int addbih (int after)
Create a new BIH entry and add it after the one specified by the formal argument.
void delbih (int bihx)
Delete a bih entry from the BIH list.
void merge_bih_flags (int to_bih, int fm_bih)
...
int merge_bih (int curbih)
Merge a block with its successor.
bool contains_par_blocks (void)
...
void merge_blks (int b1, int b2)
Merge block b2 into b1.
void merge_rgset (int tobih, int frombih, bool reuse_to)
...
void unsplit (void)
...
void split_extended ()
...
void dump_blocks (FILE *ff, int bih, const char *fmt, int fihflag)
...
void dump_one_block (FILE *ff, int bih, const char *fmt)
...
Variables
int * badpointer1 = (int *)0
long * badpointer2 = (long *)1
long badnumerator = 99
long baddenominator = 0
Detailed Description
C and Fortran BIH utility module.
Definition in file bihutil.cpp.
Macro Definition Documentation
MAXBIH
#define MAXBIH 67108864
Definition at line 29 of file bihutil.cpp.
Function Documentation
addbih()
int addbih (int after)
Create a new BIH entry and add it after the one specified by the formal argument.
...
Parameters
after BIH entry to add after
Returns
new BIH entry
Definition at line 173 of file bihutil.cpp.
References addnewbih(), and after.
Referenced by split_extended().
addnewbih()
int addnewbih (int after, int flags, int fih)
Universal function to create new BIH entry.
...
Parameters
after BIH anery to the new one after
flags BIH entry to take flags from
fih BIH entry to take FIH information from
Returns
new BIH entry
Definition at line 120 of file bihutil.cpp.
References after, BIH_AVLPCNT, BIH_BLKCNT, BIH_FINDEX, BIH_FTAG, BIH_LINENO, BIH_NEXT, BIH_PAR, BIH_PARSECT, BIH_PREV, BIH_TASK, bihb, flags, i, next, p, SPTR_NULL, BIHB::stg_max, and STG_NEXT_FREELIST.
Referenced by addbih(), llvmAddConcurEntryBlk(), and llvmAddConcurExitBlk().
bih_cleanup()
void bih_cleanup (void)
...
Definition at line 61 of file bihutil.cpp.
References bihb, and STG_DELETE.
bih_init()
void bih_init (void)
Initialize BIH area.
...
Definition at line 34 of file bihutil.cpp.
References assert, BIH_ASM, BIH_AVLPCNT, BIH_BLKCNT, BIH_FINDEX, BIH_FLAGS, BIH_FTAG, BIH_GUARDEE, BIH_GUARDER, BIH_LINENO, BIH_LPCNTFROM, BIH_NEXT, BIH_PREV, bihb, ERR_Fatal, next, STG_ALLOC, BIHB::stg_max, and STG_SET_FREELINK.
Referenced by ds_init().
contains_par_blocks()
bool contains_par_blocks (void)
...
Definition at line 354 of file bihutil.cpp.
References BIH_NEXT, BIH_PAR, and gbl.
delbih()
void delbih (int bihx)
Delete a bih entry from the BIH list.
...
Parameters
bihx BIH entry to delete
Definition at line 185 of file bihutil.cpp.
References BIH_NEXT, BIH_PREV, bihb, next, BIH::next, prev, and STG_ADD_FREELIST.
Referenced by merge_bih().
dump_blocks()
void dump_blocks (FILE * ff, int bih, const char * fmt, int fihflag)
...
Definition at line 508 of file bihutil.cpp.
References BIH_LAST, BIH_NEXT, dump_ilt(), dump_one_block(), FIH_FULLNAME, fihb, NULL, FIHB::stg_avail, and FIHB::stg_base.
Referenced by expand(), and processOutlinedByConcur().
dump_one_block()
void dump_one_block (FILE * ff, int bih, const char * fmt)
...
Definition at line 530 of file bihutil.cpp.
References BIH_LABEL, dump_ilt(), getprint(), and NULL.
Referenced by dump_blocks(), and exp_remove_gsmove().
exp_addbih()
int exp_addbih (int after)
Add a new block during the expand phase.
...
Create a new bih entry and add it after the one specified by the formal argument set the FINDEX/FTAG from fihb structure; used during expand
Parameters
after BIH entry to add after
Returns
new BIH entry
Definition at line 77 of file bihutil.cpp.
References after, BIH_NEXT, BIH_PREV, bihb, fihb, i, FIHB::nextfindex, FIHB::nextftag, p, SPTR_NULL, BIHB::stg_max, STG_NEXT_FREELIST, and UNKNOWN_EXEC_CNT.
Referenced by cr_block(), and reg_assign1().
getcon()
int getcon ()
merge_bih()
int merge_bih (int curbih)
Merge a block with its successor.
...
Parameters
curbih BIH block to merge with its successor
Returns
BIH of the merged block if merging occurred; otherwise, return 0.
Definition at line 244 of file bihutil.cpp.
References assert, BIH_ASSN, BIH_COMBST, BIH_CS, BIH_EN, BIH_ENLAB, BIH_ILTFIRST, BIH_ILTLAST, BIH_LABEL, BIH_LINENO, BIH_NEXT, BIH_NOMERGE, BIH_PAR, BIH_PARSECT, BIH_PL, BIH_TASK, BIH_XT, delbih(), ERR_Severe, EXPDBG, gbl, IL_TYPE, ILI_OPC, ILT_DBGLINE, ILT_DELEBB, ILT_DELETE, ILT_ILIP, ILT_NEXT, ILT_PREV, ILTY_BRANCH, label, merge_bih_flags(), merge_rgset(), rdilts(), SPTR_NULL, wrilts(), and XBIT.
Referenced by unsplit().
merge_bih_flags()
void merge_bih_flags (int to_bih, int fm_bih)
...
Definition at line 205 of file bihutil.cpp.
References BIH_ASM, BIH_COMBST, BIH_EX, BIH_FT, BIH_INVIF, BIH_LAST, BIH_LDVOL, BIH_MIDIOM, BIH_NOBLA, BIH_NODEPCHK, BIH_NOINVIF, BIH_NOSIMD, BIH_NOUNROLL, BIH_QJSR, BIH_RESID, BIH_SIMD, BIH_SMOVE, BIH_STVOL, BIH_TAIL, BIH_UNROLL, BIH_UNROLL_COUNT, BIH_VCAND, and BIH_ZTRP.
Referenced by merge_bih().
merge_blks()
void merge_blks (int b1, int b2)
Merge block b2 into b1.
...
Definition at line 368 of file bihutil.cpp.
References BIH_EX, BIH_FT, BIH_ILTFIRST, BIH_ILTLAST, BIH_QJSR, i, ILT_NEXT, ILT_PREV, j, rdilts(), and wrilts().
merge_rgset()
void merge_rgset (int tobih, int frombih, bool reuse_to)
...
Definition at line 399 of file bihutil.cpp.
References BIH_RGSET, mr_get_rgset(), and RGSET_XR.
Referenced by merge_bih().
mkfunc()
int mkfunc ()
rdilts()
void rdilts ()
Referenced by merge_bih(), and merge_blks().
split_extended()
void split_extended (void)
...
Definition at line 471 of file bihutil.cpp.
References addbih(), BIH_EX, BIH_FT, BIH_ILTFIRST, BIH_ILTLAST, BIH_LAST, BIH_LDVOL, BIH_NEXT, BIH_NOMERGE, BIH_PAR, BIH_QJSR, BIH_SMOVE, BIH_STVOL, gbl, IL_TYPE, ILI_OPC, ILT_ILIP, ILT_NEXT, ILT_PREV, and ILTY_BRANCH.
unsplit()
void unsplit (void)
...
Definition at line 425 of file bihutil.cpp.
References b, baddenominator, badnumerator, badpointer1, BIH_FT, BIH_ILTLAST, BIH_LAST, BIH_NEXT, gbl, ILT_BR_OR_CAN_THROW, merge_bih(), and XBIT.
Referenced by process_input().
wrilts()
void wrilts ()
Referenced by merge_bih(), and merge_blks().
Variable Documentation
baddenominator
long baddenominator = 0
Definition at line 413 of file bihutil.cpp.
Referenced by unsplit().
badnumerator
long badnumerator = 99
Definition at line 412 of file bihutil.cpp.
Referenced by unsplit().
badpointer1
int* badpointer1 = (int *)0
Definition at line 410 of file bihutil.cpp.
Referenced by unsplit().
badpointer2
long* badpointer2 = (long *)1
Definition at line 411 of file bihutil.cpp.