flang: builtin.c File Reference
builtin.c File Reference
Functions
int __builtin_abs (int a)
float __builtin_fabsf (float a)
double __builtin_fabs (double a)
float __builtin_sqrtf (float a)
double __builtin_sqrt (double a)
double __builtin_tan (double a)
float __builtin_floorf (float a)
double __builtin_floor (double a)
float __builtin_ceilf (float a)
double __builtin_ceil (double a)
float __builtin_truncf (float a)
double __builtin_trunc (double a)
float __builtin_sinf (float a)
double __builtin_sin (double a)
float __builtin_cosf (float a)
double __builtin_cos (double a)
float __builtin_tanf (float a)
float __builtin_acosf (float a)
double __builtin_acos (double a)
float __builtin_asinf (float a)
double __builtin_asin (double a)
float __builtin_atan2f (float a, float b)
double __builtin_atan2 (double a, double b)
float __builtin_atanf (float a)
double __builtin_atan (double a)
float __builtin_sinhf (float a)
double __builtin_sinh (double a)
float __builtin_coshf (float a)
double __builtin_cosh (double a)
float __builtin_tanhf (float a)
double __builtin_tanh (double a)
float __builtin_expf (float a)
double __builtin_exp (double a)
float __builtin_logf (float a)
double __builtin_log (double a)
float __builtin_log10f (float a)
double __builtin_log10 (double a)
double __builtin_pow (double a, double b)
float __builtin_crealf (float _Complex a)
float __builtin_cimagf (float _Complex a)
float _Complex __builtin_conjf (float _Complex a)
double __builtin_creal (double _Complex a)
double __builtin_cimag (double _Complex a)
double _Complex __builtin_conj (double _Complex a)
Function Documentation
__builtin_abs()
int __builtin_abs (int a)
Definition at line 19 of file builtin.c.
References __builtin_abs(), and a.
Referenced by __builtin_abs(), and __mth_i_abs().
__builtin_acos()
double __builtin_acos (double a)
Definition at line 145 of file builtin.c.
References __builtin_acos(), a, and d.
Referenced by __builtin_acos().
__builtin_acosf()
float __builtin_acosf (float a)
Definition at line 138 of file builtin.c.
References __builtin_acosf(), a, and f.
Referenced by __builtin_acosf().
__builtin_asin()
double __builtin_asin (double a)
Definition at line 159 of file builtin.c.
References __builtin_asin(), a, and d.
Referenced by __builtin_asin().
__builtin_asinf()
float __builtin_asinf (float a)
Definition at line 152 of file builtin.c.
References __builtin_asinf(), a, and f.
Referenced by __builtin_asinf().
__builtin_atan()
double __builtin_atan (double a)
Definition at line 187 of file builtin.c.
References __builtin_atan(), a, and d.
Referenced by __builtin_atan().
__builtin_atan2()
double __builtin_atan2 (double a, double b)
Definition at line 173 of file builtin.c.
References __builtin_atan2(), a, b, and d.
Referenced by __builtin_atan2().
__builtin_atan2f()
float __builtin_atan2f (float a, float b)
Definition at line 166 of file builtin.c.
References __builtin_atan2f(), a, b, and f.
Referenced by __builtin_atan2f().
__builtin_atanf()
float __builtin_atanf (float a)
Definition at line 180 of file builtin.c.
References __builtin_atanf(), a, and f.
Referenced by __builtin_atanf().
__builtin_ceil()
double __builtin_ceil (double a)
Definition at line 81 of file builtin.c.
References __builtin_ceil(), a, and d.
Referenced by __builtin_ceil().
__builtin_ceilf()
float __builtin_ceilf (float a)
Definition at line 74 of file builtin.c.
References __builtin_ceilf(), a, and f.
Referenced by __builtin_ceilf().
__builtin_cimag()
double __builtin_cimag (double _Complex a)
Definition at line 312 of file builtin.c.
References __builtin_cimag(), a, and d.
Referenced by __builtin_cimag().
__builtin_cimagf()
float __builtin_cimagf (float _Complex a)
Definition at line 292 of file builtin.c.
References __builtin_cimagf(), a, and d.
Referenced by __builtin_cimagf().
__builtin_conj()
double _Complex __builtin_conj (double _Complex a)
Definition at line 318 of file builtin.c.
References __builtin_conj(), a, and d.
Referenced by __builtin_conj().
__builtin_conjf()
float _Complex __builtin_conjf (float _Complex a)
Definition at line 298 of file builtin.c.
References __builtin_conjf(), a, and d.
Referenced by __builtin_conjf().
__builtin_cos()
double __builtin_cos (double a)
Definition at line 123 of file builtin.c.
References __builtin_cos(), a, and d.
Referenced by __builtin_cos().
__builtin_cosf()
float __builtin_cosf (float a)
Definition at line 116 of file builtin.c.
References __builtin_cosf(), a, and f.
Referenced by __builtin_cosf().
__builtin_cosh()
double __builtin_cosh (double a)
Definition at line 215 of file builtin.c.
References __builtin_cosh(), a, and d.
Referenced by __builtin_cosh().
__builtin_coshf()
float __builtin_coshf (float a)
Definition at line 208 of file builtin.c.
References __builtin_coshf(), a, and f.
Referenced by __builtin_coshf().
__builtin_creal()
double __builtin_creal (double _Complex a)
Definition at line 305 of file builtin.c.
References __builtin_creal(), a, and d.
Referenced by __builtin_creal().
__builtin_crealf()
float __builtin_crealf (float _Complex a)
Definition at line 285 of file builtin.c.
References __builtin_crealf(), a, and d.
Referenced by __builtin_crealf().
__builtin_exp()
double __builtin_exp (double a)
Definition at line 243 of file builtin.c.
References __builtin_exp(), a, and d.
Referenced by __builtin_exp().
__builtin_expf()
float __builtin_expf (float a)
Definition at line 236 of file builtin.c.
References __builtin_expf(), a, and f.
Referenced by __builtin_expf().
__builtin_fabs()
double __builtin_fabs (double a)
Definition at line 32 of file builtin.c.
References __builtin_fabs(), a, and d.
Referenced by __builtin_fabs(), and __mth_i_fabs().
__builtin_fabsf()
float __builtin_fabsf (float a)
Definition at line 25 of file builtin.c.
References __builtin_fabsf(), a, and d.
Referenced by __builtin_fabsf().
__builtin_floor()
double __builtin_floor (double a)
Definition at line 67 of file builtin.c.
References __builtin_floor(), a, and d.
Referenced by __builtin_floor().
__builtin_floorf()
float __builtin_floorf (float a)
Definition at line 60 of file builtin.c.
References __builtin_floorf(), a, and f.
Referenced by __builtin_floorf().
__builtin_log()
double __builtin_log (double a)
Definition at line 257 of file builtin.c.
References __builtin_log(), a, and d.
Referenced by __builtin_log().
__builtin_log10()
double __builtin_log10 (double a)
Definition at line 271 of file builtin.c.
References __builtin_log10(), a, and d.
Referenced by __builtin_log10().
__builtin_log10f()
float __builtin_log10f (float a)
Definition at line 264 of file builtin.c.
References __builtin_log10f(), a, and f.
Referenced by __builtin_log10f().
__builtin_logf()
float __builtin_logf (float a)
Definition at line 250 of file builtin.c.
References __builtin_logf(), a, and f.
Referenced by __builtin_logf().
__builtin_pow()
double __builtin_pow (double a, double b)
Definition at line 278 of file builtin.c.
References __builtin_pow(), a, b, and d.
Referenced by __builtin_pow().
__builtin_sin()
double __builtin_sin (double a)
Definition at line 109 of file builtin.c.
References __builtin_sin(), a, and d.
Referenced by __builtin_sin().
__builtin_sinf()
float __builtin_sinf (float a)
Definition at line 102 of file builtin.c.
References __builtin_sinf(), a, and f.
Referenced by __builtin_sinf().
__builtin_sinh()
double __builtin_sinh (double a)
Definition at line 201 of file builtin.c.
References __builtin_sinh(), a, and d.
Referenced by __builtin_sinh().
__builtin_sinhf()
float __builtin_sinhf (float a)
Definition at line 194 of file builtin.c.
References __builtin_sinhf(), a, and f.
Referenced by __builtin_sinhf().
__builtin_sqrt()
double __builtin_sqrt (double a)
Definition at line 46 of file builtin.c.
References __builtin_sqrt(), a, and d.
Referenced by __builtin_sqrt(), and __mth_i_dsqrt().
__builtin_sqrtf()
float __builtin_sqrtf (float a)
Definition at line 39 of file builtin.c.
References __builtin_sqrtf(), a, and f.
Referenced by __builtin_sqrtf(), and __mth_i_sqrt().
__builtin_tan()
double __builtin_tan (double a)
Definition at line 53 of file builtin.c.
References __builtin_tan(), a, and d.
Referenced by __builtin_tan().
__builtin_tanf()
float __builtin_tanf (float a)
Definition at line 130 of file builtin.c.
References __builtin_tanf(), a, and f.
Referenced by __builtin_tanf().
__builtin_tanh()
double __builtin_tanh (double a)
Definition at line 229 of file builtin.c.
References __builtin_tanh(), a, and d.
Referenced by __builtin_tanh().
__builtin_tanhf()
float __builtin_tanhf (float a)
Definition at line 222 of file builtin.c.
References __builtin_tanhf(), a, and f.
Referenced by __builtin_tanhf().
__builtin_trunc()
double __builtin_trunc (double a)
Definition at line 95 of file builtin.c.
References __builtin_trunc(), a, and d.
Referenced by __builtin_trunc().
__builtin_truncf()
float __builtin_truncf (float a)
Definition at line 88 of file builtin.c.
References __builtin_truncf(), a, and f.
Referenced by __builtin_truncf().