flang: ccffinfo.c File Reference
ccffinfo.c File Reference
common compiler feedback format module
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include "symtab.h"
#include "ilm.h"
#include "fih.h"
#include "version.h"
#include "ccffinfo.h"
#include "lz.h"
#include "cgraph.h"
Macros
#define BUILD_VENDOR "flang-compiler"
#define CCFFAREA 24
#define ICCFFAREA 27
#define COPYSTRING(string) strcpy(GETITEMS(CCFFAREA, char, strlen(string) + 1), string)
#define ICOPYSTRING(string) strcpy(GETITEMS(ICCFFAREA, char, strlen(string) + 1), string)
#define COPYNSTRING(string, len) strncpy(GETITEMS(CCFFAREA, char, (len) + 1), string, len)
#define ICOPYNSTRING(string, len) strncpy(GETITEMS(ICCFFAREA, char, (len) + 1), string, len)
#define INDENT 5
#define CINDENT 2
Functions
int bu_auto_inline (void)
static bool need_cdata (const char *string)
static void xmlout (const char *string)
static void xmlout2 (const char *string1, const char *string2)
static void xmlintout (int value)
static void xmlintout2 (int value1, int value2)
static void xmlopen (const char *entity, const char *shortentity)
static void xmlopenn (const char *entity, const char *shortentity)
static void xmlopenattri (const char *entity, const char *shortentity, const char *attr, int attrval)
static void xmlopenattrs2 (const char *entity, const char *shortentity, const char *attr1, const char *attr1val, const char *attr2, const char *attr2val)
static void xmlclose (const char *entity, const char *shortentity)
static void xmlentity (const char *entity, const char *shortentity, const char *string)
static void xmlentity2 (const char *entity, const char *shortentity, const char *string1, const char *string2)
static void xmlintentity (const char *entity, const char *shortentity, int value)
static void xmlintentity2 (const char *entity, const char *shortentity, int value1, int value2)
void ccff_open (const char *ccff_filename, const char *srcfile)
Open ccff_file, write initial tags.
void ccff_close ()
Close the ccff tag, close ccff_file.
void ccff_build (const char *options, const char *language)
Write build information, including command line options.
char * getexnamestring (char *, int, int, int, int)
...
void ccff_open_unit ()
Write initial unit information.
void ccff_open_unit_deferred (void)
...
void dumpmessagelist (int nmessages)
...
static void _childsort (int l, int h)
static void _ichildsort (int l, int h)
static void fih_sort_children (int fihx)
static void ifih_sort_children (int ifihx)
static bool _numeric (const char *s, int *v)
static int _messagecmp (MESSAGE *m1, MESSAGE *m2, int sortorder)
static void _messagesort (int l, int h, int sortorder)
static MESSAGE * sort_message_list (MESSAGE *msglist)
static void fih_sort_messages (int fihx)
static void ifih_sort_messages (int ifihx)
static bool combine_message (MESSAGE *mptr1, MESSAGE *mptr2)
static void __fih_message (FILE *ofile, MESSAGE *mptr, bool dolist)
static void _fih_message (FILE *ofile, MESSAGE *mptr, bool do_cdata)
static void fih_message (MESSAGE *mptr)
static void print_func (FILE *ofile)
static void fih_message_ofile (FILE *ofile, int nest, int lineno, int childnest, MESSAGE *mptr)
static void fih_messages (int fihx, FILE *ofile, int nest)
static void fih_rminc_children (int fihx)
static void ifih_rminc_children (int ifihx)
static bool save_any_messages (int fihx)
static void ccff_set_children ()
static void ccff_set_children_deferred ()
static void ccff_cleanup_children ()
void ccff_cleanup_children_deferred ()
...
void ccff_close_unit ()
...
void ccff_close_unit_deferred ()
...
static void fillformat (const char *format, int len)
static char * newbuff (const char *oldstring, int len, int *pl)
static char * newprintfl (const char *oldstring, const char *format, int len, long data)
static char * newprintfi (const char *oldstring, const char *format, int len, int data)
static char * newprintfd (const char *oldstring, const char *format, int len, double data)
static char * newprintfs (const char *oldstring, const char *format, int len, char *data)
static char * newprintfx (const char *oldstring, const char *format, int len)
void * _ccff_info (int msgtype, const char *msgid, int fihx, int lineno, const char *varname, const char *funcname, void *xparent, const char *message, va_list argptr)
...
void * ccff_info (int msgtype, const char *msgid, int fihx, int lineno, const char *message,...)
...
void * subccff_info (void *xparent, int msgtype, const char *msgid, int fihx, int lineno, const char *message,...)
...
void * ccff_var_info (int msgtype, const char *msgid, const char *varname, const char *message,...)
...
void * ccff_func_info (int msgtype, const char *msgid, const char *funcname, const char *message,...)
...
void ccff_seq (int seq)
...
int addfile (const char *filename, const char *funcname, int tag, int flags, int lineno, int srcline, int level)
int addinlfile (const char *filename, const char *funcname, int tag, int flags, int lineno, int srcline, int level, int parent)
...
int subfih (int fihindex, int tag, int flags, int lineno)
...
void setfile (int f, const char *funcname, int tag)
...
void save_ccff_mark ()
...
void restore_ccff_mark ()
...
void set_allfiles (int save)
...
void fih_fini ()
...
void print_fih ()
...
void print_ifih ()
...
Variables
int auto_reinlinedepth
bool in_auto_reinline
static int anyunits = 0
static int prevnest = -1
static int prevchildnest = -1
static int prevlineno = 0
static bool anymessages
FIHB fihb = {(FIH *)0, 0, 0, 0, 0, 0, 0, 0}
FIHB ifihb = {(FIH *)0, 0, 0, 0, 0, 0, 0, 0}
static char * formatbuffer = NULL
static int formatbuffersize = 0
static int unitstatus = -1
static MESSAGE * prevmessage = NULL
static int globalorder = 0
static FILE * ccff_file = NULL
static int * childlist
static int childlistsize
static MESSAGE ** messagelist
static int messagelistsize
static int strngsize = 0
static char * strng = NULL
static const char * nullname = ""
Detailed Description
common compiler feedback format module
Definition in file ccffinfo.c.
Macro Definition Documentation
BUILD_VENDOR
#define BUILD_VENDOR "flang-compiler"
Definition at line 53 of file ccffinfo.c.
CCFFAREA
#define CCFFAREA 24
Definition at line 58 of file ccffinfo.c.
CINDENT
#define CINDENT 2
Definition at line 1192 of file ccffinfo.c.
COPYNSTRING
#define COPYNSTRING (string, len) strncpy(GETITEMS(CCFFAREA, char, (len) + 1), string, len)
Definition at line 64 of file ccffinfo.c.
COPYSTRING
#define COPYSTRING (string) strcpy(GETITEMS(CCFFAREA, char, strlen(string) + 1), string)
Definition at line 60 of file ccffinfo.c.
ICCFFAREA
#define ICCFFAREA 27
Definition at line 59 of file ccffinfo.c.
ICOPYNSTRING
#define ICOPYNSTRING (string, len) strncpy(GETITEMS(ICCFFAREA, char, (len) + 1), string, len)
Definition at line 66 of file ccffinfo.c.
ICOPYSTRING
#define ICOPYSTRING (string) strcpy(GETITEMS(ICCFFAREA, char, strlen(string) + 1), string)
Definition at line 62 of file ccffinfo.c.
INDENT
#define INDENT 5
Definition at line 1191 of file ccffinfo.c.
Function Documentation
__fih_message()
static void __fih_message (FILE * ofile, MESSAGE * mptr, bool dolist) static
Definition at line 1038 of file ccffinfo.c.
References ccff_message::args, ccff_argument::argstring, ccff_argument::argvalue, CCFFAREA, ccff_message::combine, first, getitem(), ccff_message::message, ccff_message::next, ccff_argument::next, strng, strngsize, and XBIT.
Referenced by _fih_message().
_ccff_info()
void * _ccff_info (int msgtype, const char * msgid, int fihx, int lineno, const char * varname, const char * funcname, void * xparent, const char * message, va_list argptr)
...
Definition at line 2215 of file ccffinfo.c.
References ccff_message::args, ccff_argument::argstring, ccff_argument::argvalue, BZERO, CCFFAREA, ccff_message::combine, COPYNSTRING, COPYSTRING, d, DBGBIT, ERR_Severe, f, FIH_CCFF, FIH_CCFFINFO, FIH_SETFLAG, ccff_message::fihx, ccff_message::funcname, gbl, GETITEM, globalorder, i, interr(), lineno, ccff_message::lineno, ccff_message::message, ccff_message::msgid, ccff_message::msgtype, newprintfd(), newprintfi(), newprintfl(), newprintfs(), newprintfx(), ccff_message::next, ccff_argument::next, NULL, ccff_message::order, parent, prevmessage, s, ccff_message::seq, unitstatus, and ccff_message::varname.
Referenced by ccff_func_info(), ccff_ilt_info(), ccff_info(), ccff_var_info(), subccff_ilt_info(), and subccff_info().
_childsort()
static void _childsort (int l, int h) static
Definition at line 577 of file ccffinfo.c.
References c, childlist, FIH_LINENO, h, and m2.
Referenced by fih_sort_children().
_fih_message()
static void _fih_message (FILE * ofile, MESSAGE * mptr, bool do_cdata) static
Definition at line 1114 of file ccffinfo.c.
References __fih_message(), ccff_message::args, ccff_argument::argvalue, ccff_file, ccff_message::message, need_cdata(), and ccff_argument::next.
Referenced by fih_message(), and fih_message_ofile().
_ichildsort()
static void _ichildsort (int l, int h) static
Definition at line 612 of file ccffinfo.c.
References c, childlist, h, IFIH_LINENO, and m2.
Referenced by ifih_sort_children().
_messagecmp()
static int _messagecmp (MESSAGE * m1, MESSAGE * m2, int sortorder) static
Definition at line 760 of file ccffinfo.c.
References _numeric(), ccff_message::args, ccff_argument::argstring, ccff_argument::argvalue, ccff_message::funcname, ccff_message::lineno, m2, ccff_message::msgid, ccff_message::msgtype, ccff_argument::next, ccff_message::order, r, ccff_message::suborder, and ccff_message::varname.
Referenced by _messagesort(), and sort_message_list().
_messagesort()
static void _messagesort (int l, int h, int sortorder) static
Definition at line 842 of file ccffinfo.c.
References _messagecmp(), c, h, m2, messagelist, and r.
Referenced by sort_message_list().
_numeric()
static bool _numeric (const char * s, int * v) static
Definition at line 729 of file ccffinfo.c.
References r, and s.
Referenced by _messagecmp().
addfile()
int addfile (const char * filename, const char * funcname, int tag, int flags, int lineno, int srcline, int level)
Definition at line 2504 of file ccffinfo.c.
References BZERO, cp, FIHB::currfindex, FIHB::currftag, DBGBIT, f, FIH_DIRNAME, FIH_FILENAME, FIH_FLAGS, FIH_FULLNAME, FIH_FUNCNAME, FIH_FUNCTAG, FIH_INC, FIH_LEVEL, FIH_LINENO, FIH_PARENT, FIH_SRCLINE, fihb, filename, flags, gbl, getitem(), len, level(), lineno, NEED, NEW, FIHB::nextfindex, FIHB::nextftag, NULL, nullname, s, FIHB::stg_avail, FIHB::stg_base, FIHB::stg_size, and strlen().
Referenced by add_headerfile(), main(), and read_fileentries().
addinlfile()
int addinlfile (const char * filename, const char * funcname, int tag, int flags, int lineno, int srcline, int level, int parent)
...
Definition at line 2606 of file ccffinfo.c.
References BZERO, cp, FIHB::currfindex, FIHB::currftag, DBGBIT, f, FIH_CCFFINFO, FIH_DIRNAME, FIH_FILENAME, FIH_FLAGS, FIH_FULLNAME, FIH_FUNCNAME, FIH_FUNCTAG, FIH_LEVEL, FIH_LINENO, FIH_PARENT, FIH_SRCLINE, fihb, filename, flags, gbl, getitem(), len, level(), lineno, NEED, NEW, FIHB::nextfindex, FIHB::nextftag, NULL, nullname, parent, s, FIHB::stg_avail, FIHB::stg_base, FIHB::stg_size, and strlen().
bu_auto_inline()
int bu_auto_inline (void)
ccff_build()
void ccff_build (const char * options, const char * language)
Write build information, including command line options.
...
Definition at line 384 of file ccffinfo.c.
References BUILD_VENDOR, ccff_file, localtime(), time(), version, xmlclose(), xmlentity(), xmlentity2(), and xmlopen().
Referenced by init().
ccff_cleanup_children()
static void ccff_cleanup_children () static
Definition at line 1988 of file ccffinfo.c.
References CCFFAREA, childlist, childlistsize, FIH_CCFF, FIH_CCFFINFO, FIH_CLEARFLAG, fihb, formatbuffer, formatbuffersize, freearea(), messagelist, messagelistsize, NULL, FIHB::stg_avail, strng, and strngsize.
Referenced by ccff_close_unit().
ccff_cleanup_children_deferred()
void ccff_cleanup_children_deferred (void)
...
Definition at line 2008 of file ccffinfo.c.
References childlist, childlistsize, FIH_CCFF, formatbuffer, formatbuffersize, freearea(), ICCFFAREA, IFIH_CCFFINFO, IFIH_FLAGS, ifihb, messagelist, messagelistsize, NULL, FIHB::stg_avail, strng, and strngsize.
ccff_close()
void ccff_close (void)
Close the ccff tag, close ccff_file.
...
Definition at line 368 of file ccffinfo.c.
References anyunits, ccff_file, fclose(), NULL, unitstatus, and xmlclose().
Referenced by finish().
ccff_close_unit()
void ccff_close_unit (void)
...
Definition at line 2032 of file ccffinfo.c.
References anymessages, ccff_cleanup_children(), ccff_file, ccff_set_children(), fih_messages(), FILE, NULL, prevmessage, unitstatus, XBIT, and xmlclose().
Referenced by process_input().
ccff_close_unit_deferred()
void ccff_close_unit_deferred (void)
...
Definition at line 2055 of file ccffinfo.c.
References anymessages, ccff_set_children_deferred(), FILE, globalorder, NULL, prevmessage, unitstatus, and XBIT.
ccff_func_info()
void * ccff_func_info (int msgtype, const char * msgid, const char * funcname, const char * message, ...)
...
Definition at line 2481 of file ccffinfo.c.
References _ccff_info(), and NULL.
ccff_info()
void * ccff_info (int msgtype, const char * msgid, int fihx, int lineno, const char * message, ...)
...
Definition at line 2443 of file ccffinfo.c.
References _ccff_info(), lineno, and NULL.
Referenced by collapse_assignment(), conv_fused_forall(), copy_arg_to_seq_tmp(), exp_smp(), extractor_possible(), hoist_comms(), inline_func(), inline_reduction_f90(), maybe_generate_fma(), mmul(), name_dependent_check(), report_collapse(), report_comm(), and rewrite_inlined_args().
ccff_open()
void ccff_open (const char * ccff_filename, const char * srcfile)
Open ccff_file, write initial tags.
...
called from main()
Definition at line 320 of file ccffinfo.c.
References ccff_file, ccff_filename, CCFFVERSION, i, malloc(), NULL, strlen(), unitstatus, xmlclose(), xmlentity(), xmlopen(), and xmlopenattrs2().
Referenced by init().
ccff_open_unit()
void ccff_open_unit (void)
Write initial unit information.
...
Definition at line 414 of file ccffinfo.c.
References anyunits, ccff_file, ENDLINEG, flg, formatbuffer, formatbuffersize, FUNCLINEG, gbl, GBL_CURRFUNC, getexnamestring(), NULL, RU_BDATA, RU_FUNC, RU_PROG, RU_SUBR, SYMNAME, unitstatus, FLG::x, xmlclose(), xmlentity(), xmlintentity(), xmlintentity2(), and xmlopen().
Referenced by begin_entry(), and setfile().
ccff_open_unit_deferred()
void ccff_open_unit_deferred (void)
...
Definition at line 467 of file ccffinfo.c.
References ccff_file, flg, formatbuffer, formatbuffersize, NULL, unitstatus, and FLG::x.
ccff_seq()
void ccff_seq (int seq)
...
Definition at line 2494 of file ccffinfo.c.
References prevmessage, and ccff_message::seq.
ccff_set_children()
static void ccff_set_children () static
Definition at line 1905 of file ccffinfo.c.
References CCFFAREA, childlist, childlistsize, FIH_CCFF, FIH_CHECKFLAG, FIH_CHILD, FIH_DO_CCFF, FIH_NEXT, FIH_PARENT, fih_rminc_children(), FIH_SETFLAG, fih_sort_children(), fih_sort_messages(), fihb, getitem(), GETITEMS, messagelist, messagelistsize, save_any_messages(), FIHB::stg_avail, strng, and strngsize.
Referenced by ccff_close_unit().
ccff_set_children_deferred()
static void ccff_set_children_deferred () static
Definition at line 1947 of file ccffinfo.c.
References childlist, childlistsize, FIH_CCFF, getitem(), GETITEMS, ICCFFAREA, IFIH_CHILD, IFIH_FLAGS, IFIH_NEXT, IFIH_PARENT, ifih_rminc_children(), ifih_sort_children(), ifih_sort_messages(), ifihb, messagelist, messagelistsize, FIHB::stg_avail, strng, and strngsize.
Referenced by ccff_close_unit_deferred().
ccff_var_info()
void * ccff_var_info (int msgtype, const char * msgid, const char * varname, const char * message, ...)
...
Definition at line 2469 of file ccffinfo.c.
References _ccff_info(), and NULL.
combine_message()
static bool combine_message (MESSAGE * mptr1, MESSAGE * mptr2) static
Definition at line 990 of file ccffinfo.c.
References ccff_message::args, ccff_argument::argstring, ccff_argument::argvalue, ccff_message::combine, ccff_message::fihx, ccff_message::lineno, ccff_message::msgid, ccff_message::msgtype, ccff_argument::next, and XBIT.
Referenced by fih_message(), fih_message_ofile(), and fih_messages().
dumpmessagelist()
void dumpmessagelist (int nmessages)
...
Definition at line 566 of file ccffinfo.c.
References messagelist, and n.
fih_fini()
void fih_fini (void)
...
Definition at line 2974 of file ccffinfo.c.
References fihb, FREE, NULL, FIHB::stg_avail, FIHB::stg_base, and FIHB::stg_size.
Referenced by finish().
fih_message()
static void fih_message (MESSAGE * mptr) static
Definition at line 1146 of file ccffinfo.c.
References _fih_message(), ccff_message::args, ccff_argument::argstring, ccff_argument::argvalue, ccff_file, combine_message(), fih_message(), ccff_message::funcname, ccff_message::lineno, ccff_message::msgchild, ccff_message::msgid, ccff_message::next, ccff_argument::next, NULL, ccff_message::seq, ccff_message::varname, xmlclose(), xmlentity(), xmlintentity(), xmlopen(), xmlopenattri(), xmlopenn(), and xmlout().
Referenced by fih_message(), and fih_messages().
fih_message_ofile()
static void fih_message_ofile (FILE * ofile, int nest, int lineno, int childnest, MESSAGE * mptr) static
Definition at line 1211 of file ccffinfo.c.
References _fih_message(), CINDENT, combine_message(), fih_message_ofile(), flg, INDENT, lineno, ccff_message::lineno, MSGACCEL, ccff_message::msgchild, MSGCVECT, MSGFTN, MSGFUSE, MSGHPF, MSGINLINER, MSGINTENSITY, MSGIPA, MSGLOOP, MSGLRE, MSGNEGACCEL, MSGNEGCVECT, MSGNEGFUSE, MSGNEGINLINER, MSGNEGIPA, MSGNEGLOOP, MSGNEGLRE, MSGNEGOPT, MSGNEGPAR, MSGNEGPFO, MSGNEGVECT, MSGOPENMP, MSGOPT, MSGPAR, MSGPCAST, MSGPFO, MSGPREFETCH, ccff_message::msgtype, MSGUNIFIED, MSGVECT, ccff_message::next, prevchildnest, prevlineno, prevnest, print_func(), FLG::x, and XBIT.
Referenced by fih_message_ofile(), and fih_messages().
fih_messages()
static void fih_messages (int fihx, FILE * ofile, int nest) static
Definition at line 1500 of file ccffinfo.c.
References ccff_file, combine_message(), FIH_CCFFINFO, FIH_CHECKFLAG, FIH_CHILD, FIH_CLEARDONE, FIH_CLEARINCDONE, FIH_DO_CCFF, FIH_DONE, FIH_FILENAME, FIH_FULLNAME, FIH_FUNCNAME, FIH_INCLUDED, FIH_INLINED, FIH_LEVEL, FIH_LINENO, fih_message(), fih_message_ofile(), fih_messages(), FIH_NEXT, FIH_SETDONE, FIH_SRCLINE, INDENT, lineno, ccff_message::lineno, ccff_message::next, prevchildnest, prevlineno, prevnest, print_func(), ccff_message::seq, xmlclose(), xmlentity(), xmlintentity(), xmlopen(), and xmlopenattri().
Referenced by ccff_close_unit(), and fih_messages().
fih_rminc_children()
static void fih_rminc_children (int fihx) static
Definition at line 1727 of file ccffinfo.c.
References FIH_CCFFINFO, FIH_CHECKFLAG, FIH_CHILD, FIH_INCLUDED, FIH_NEXT, FIH_PARENT, and fih_rminc_children().
Referenced by ccff_set_children(), and fih_rminc_children().
fih_sort_children()
static void fih_sort_children (int fihx) static
Definition at line 648 of file ccffinfo.c.
References _childsort(), c, CCFFAREA, childlist, childlistsize, FIH_CHILD, FIH_NEXT, GETITEMS, and n.
Referenced by ccff_set_children().
fih_sort_messages()
static void fih_sort_messages (int fihx) static
Definition at line 956 of file ccffinfo.c.
References FIH_CCFFINFO, ccff_message::msgchild, ccff_message::next, and sort_message_list().
Referenced by ccff_set_children().
fillformat()
static void fillformat (const char * format, int len) static
Definition at line 2085 of file ccffinfo.c.
References CCFFAREA, formatbuffer, formatbuffersize, GETITEMS, and len.
Referenced by newprintfd(), newprintfi(), newprintfl(), newprintfs(), and newprintfx().
getexnamestring()
char * getexnamestring (char * string, int sptr, int stype, int scg, int extraunderscore)
...
Definition at line 5458 of file upper.cpp.
References FLG::dollar, flg, gbl, m, NEED, NEW, NULL, s, sptr, ss, strlen(), SYMNAME, upcase_name(), and XBIT.
Referenced by ccff_open_unit().
ifih_rminc_children()
static void ifih_rminc_children (int ifihx) static
Definition at line 1758 of file ccffinfo.c.
References FIH_INCLUDED, IFIH_CCFFINFO, IFIH_CHILD, IFIH_FLAGS, IFIH_NEXT, IFIH_PARENT, and ifih_rminc_children().
Referenced by ccff_set_children_deferred(), and ifih_rminc_children().
ifih_sort_children()
static void ifih_sort_children (int ifihx) static
Definition at line 688 of file ccffinfo.c.
References _ichildsort(), c, childlist, childlistsize, GETITEMS, ICCFFAREA, IFIH_CHILD, IFIH_NEXT, and n.
Referenced by ccff_set_children_deferred().
ifih_sort_messages()
static void ifih_sort_messages (int ifihx) static
Definition at line 970 of file ccffinfo.c.
References IFIH_CCFFINFO, ccff_message::msgchild, ccff_message::next, and sort_message_list().
Referenced by ccff_set_children_deferred().
need_cdata()
static bool need_cdata (const char * string) static
Definition at line 81 of file ccffinfo.c.
References p.
Referenced by _fih_message(), xmlout(), and xmlout2().
newbuff()
static char * newbuff (const char * oldstring, int len, int * pl) static
Definition at line 2103 of file ccffinfo.c.
References buff, CCFFAREA, GETITEMS, len, and strlen().
Referenced by newprintfd(), newprintfi(), newprintfl(), newprintfs(), and newprintfx().
newprintfd()
static char * newprintfd (const char * oldstring, const char * format, int len, double data) static
Definition at line 2148 of file ccffinfo.c.
References buff, fillformat(), formatbuffer, len, n, newbuff(), and NULL.
Referenced by _ccff_info().
newprintfi()
static char * newprintfi (const char * oldstring, const char * format, int len, int data) static
Definition at line 2133 of file ccffinfo.c.
References buff, fillformat(), formatbuffer, len, n, newbuff(), and NULL.
Referenced by _ccff_info().
newprintfl()
static char * newprintfl (const char * oldstring, const char * format, int len, long data) static
Definition at line 2118 of file ccffinfo.c.
References buff, fillformat(), formatbuffer, len, n, newbuff(), and NULL.
Referenced by _ccff_info().
newprintfs()
static char * newprintfs (const char * oldstring, const char * format, int len, char * data) static
Definition at line 2163 of file ccffinfo.c.
References buff, fillformat(), formatbuffer, len, malloc(), n, newbuff(), NULL, and strlen().
Referenced by _ccff_info().
newprintfx()
static char * newprintfx (const char * oldstring, const char * format, int len) static
Definition at line 2193 of file ccffinfo.c.
References buff, fillformat(), formatbuffer, len, n, newbuff(), and NULL.
Referenced by _ccff_info().
print_fih()
void print_fih (void)
...
Definition at line 2985 of file ccffinfo.c.
References FIH_CCFFINFO, FIH_CHILD, FIH_FILENAME, FIH_FLAGS, FIH_FUNCNAME, FIH_LEVEL, FIH_NEXT, FIH_PARENT, fihb, i, ccff_message::message, and FIHB::stg_avail.
print_func()
static void print_func (FILE * ofile) static
Definition at line 1196 of file ccffinfo.c.
References anymessages, and FIH_FUNCNAME.
Referenced by fih_message_ofile(), and fih_messages().
print_ifih()
void print_ifih (void)
...
Definition at line 3003 of file ccffinfo.c.
References i, IFIH_CCFFINFO, IFIH_CHILD, IFIH_FILENAME, IFIH_FLAGS, IFIH_FUNCNAME, IFIH_LEVEL, IFIH_LINENO, IFIH_NEXT, IFIH_PARENT, ifihb, ccff_message::message, and FIHB::stg_avail.
restore_ccff_mark()
void restore_ccff_mark (void)
...
Definition at line 2778 of file ccffinfo.c.
References FIH_PARENT, fihb, FIHB::saved_avail, and FIHB::stg_avail.
save_any_messages()
static bool save_any_messages (int fihx) static
Definition at line 1787 of file ccffinfo.c.
References FIH_CCFFINFO, MSGACCEL, MSGCVECT, MSGFTN, MSGFUSE, MSGHPF, MSGINLINER, MSGINTENSITY, MSGIPA, MSGLOOP, MSGLRE, MSGNEGACCEL, MSGNEGCVECT, MSGNEGFUSE, MSGNEGINLINER, MSGNEGIPA, MSGNEGLOOP, MSGNEGLRE, MSGNEGOPT, MSGNEGPAR, MSGNEGPFO, MSGNEGVECT, MSGOPENMP, MSGOPT, MSGPAR, MSGPFO, MSGPREFETCH, ccff_message::msgtype, MSGUNIFIED, MSGVECT, ccff_message::next, and XBIT.
Referenced by ccff_set_children().
save_ccff_mark()
void save_ccff_mark (void)
...
Definition at line 2772 of file ccffinfo.c.
References fihb, FIHB::saved_avail, and FIHB::stg_avail.
set_allfiles()
void set_allfiles (int save)
...
Definition at line 2801 of file ccffinfo.c.
References FIHB::currfindex, fihb, gbl, and FIHB::nextfindex.
Referenced by expand(), and parser().
setfile()
void setfile (int f, const char * funcname, int tag)
...
Definition at line 2724 of file ccffinfo.c.
References ccff_open_unit(), f, FIH_CCFFINFO, FIH_FLAGS, FIH_FUNCNAME, FIH_FUNCTAG, FIH_LINENO, firsttime, gbl, GBL_CURRFUNC, getitem(), ILMB::globalilmstart, ilmb, NULL, nullname, and strlen().
Referenced by push_scope_level(), and semant1().
sort_message_list()
static MESSAGE * sort_message_list (MESSAGE * msglist) static
Definition at line 879 of file ccffinfo.c.
References _messagecmp(), _messagesort(), CCFFAREA, GETITEMS, messagelist, messagelistsize, ccff_message::msgid, n, ccff_message::next, NULL, ccff_message::order, and ccff_message::suborder.
Referenced by fih_sort_messages(), and ifih_sort_messages().
subccff_info()
void * subccff_info (void * xparent, int msgtype, const char * msgid, int fihx, int lineno, const char * message, ...)
...
Definition at line 2456 of file ccffinfo.c.
References _ccff_info(), lineno, and NULL.
subfih()
int subfih (int fihindex, int tag, int flags, int lineno)
...
Definition at line 2699 of file ccffinfo.c.
References BZERO, f, FIH_DIRNAME, FIH_FILENAME, FIH_FLAGS, FIH_FULLNAME, FIH_FUNCNAME, FIH_FUNCTAG, FIH_LEVEL, FIH_LINENO, FIH_PARENT, fihb, flags, lineno, NEED, NULL, FIHB::stg_avail, FIHB::stg_base, and FIHB::stg_size.
xmlclose()
static void xmlclose (const char * entity, const char * shortentity) static
Definition at line 227 of file ccffinfo.c.
References ccff_file, and XBIT.
Referenced by ccff_build(), ccff_close(), ccff_close_unit(), ccff_open(), ccff_open_unit(), fih_message(), and fih_messages().
xmlentity()
static void xmlentity (const char * entity, const char * shortentity, const char * string) static
Definition at line 241 of file ccffinfo.c.
References ccff_file, XBIT, and xmlout().
Referenced by ccff_build(), ccff_open(), ccff_open_unit(), fih_message(), and fih_messages().
xmlentity2()
static void xmlentity2 (const char * entity, const char * shortentity, const char * string1, const char * string2) static
Definition at line 260 of file ccffinfo.c.
References ccff_file, XBIT, and xmlout2().
Referenced by ccff_build().
xmlintentity()
static void xmlintentity (const char * entity, const char * shortentity, int value) static
Definition at line 280 of file ccffinfo.c.
References ccff_file, value(), XBIT, and xmlintout().
Referenced by ccff_open_unit(), fih_message(), and fih_messages().
xmlintentity2()
static void xmlintentity2 (const char * entity, const char * shortentity, int value1, int value2) static
Definition at line 299 of file ccffinfo.c.
References ccff_file, XBIT, and xmlintout2().
Referenced by ccff_open_unit().
xmlintout()
static void xmlintout (int value) static
Definition at line 128 of file ccffinfo.c.
References ccff_file, and value().
Referenced by xmlintentity().
xmlintout2()
static void xmlintout2 (int value1, int value2) static
Definition at line 139 of file ccffinfo.c.
References ccff_file.
Referenced by xmlintentity2().
xmlopen()
static void xmlopen (const char * entity, const char * shortentity) static
Definition at line 150 of file ccffinfo.c.
References ccff_file, and XBIT.
Referenced by ccff_build(), ccff_open(), ccff_open_unit(), fih_message(), and fih_messages().
xmlopenattri()
static void xmlopenattri (const char * entity, const char * shortentity, const char * attr, int attrval) static
Definition at line 178 of file ccffinfo.c.
References ccff_file, and XBIT.
Referenced by fih_message(), and fih_messages().
xmlopenattrs2()
static void xmlopenattrs2 (const char * entity, const char * shortentity, const char * attr1, const char * attr1val, const char * attr2, const char * attr2val) static
Definition at line 210 of file ccffinfo.c.
References ccff_file, and XBIT.
Referenced by ccff_open().
xmlopenn()
static void xmlopenn (const char * entity, const char * shortentity) static
Definition at line 164 of file ccffinfo.c.
References ccff_file, and XBIT.
Referenced by fih_message().
xmlout()
static void xmlout (const char * string) static
Definition at line 97 of file ccffinfo.c.
References ccff_file, and need_cdata().
Referenced by fih_message(), and xmlentity().
xmlout2()
static void xmlout2 (const char * string1, const char * string2) static
Definition at line 113 of file ccffinfo.c.
References ccff_file, and need_cdata().
Referenced by xmlentity2().
Variable Documentation
anymessages
bool anymessages static
Definition at line 50 of file ccffinfo.c.
Referenced by ccff_close_unit(), ccff_close_unit_deferred(), and print_func().
anyunits
int anyunits = 0 static
Definition at line 44 of file ccffinfo.c.
Referenced by ccff_close(), and ccff_open_unit().
auto_reinlinedepth
int auto_reinlinedepth extern
ccff_file
FILE* ccff_file = NULL static
Definition at line 78 of file ccffinfo.c.
Referenced by _fih_message(), ccff_build(), ccff_close(), ccff_close_unit(), ccff_open(), ccff_open_unit(), ccff_open_unit_deferred(), fih_message(), fih_messages(), xmlclose(), xmlentity(), xmlentity2(), xmlintentity(), xmlintentity2(), xmlintout(), xmlintout2(), xmlopen(), xmlopenattri(), xmlopenattrs2(), xmlopenn(), xmlout(), and xmlout2().
childlist
int* childlist static
Definition at line 523 of file ccffinfo.c.
Referenced by _childsort(), _ichildsort(), ccff_cleanup_children(), ccff_cleanup_children_deferred(), ccff_set_children(), ccff_set_children_deferred(), fih_sort_children(), and ifih_sort_children().
childlistsize
int childlistsize static
Definition at line 524 of file ccffinfo.c.
Referenced by ccff_cleanup_children(), ccff_cleanup_children_deferred(), ccff_set_children(), ccff_set_children_deferred(), fih_sort_children(), and ifih_sort_children().
fihb
FIHB fihb = {(FIH *)0, 0, 0, 0, 0, 0, 0, 0}
Definition at line 55 of file ccffinfo.c.
Referenced by add_headerfile(), addfile(), addilt(), addinlfile(), ccff_cleanup_children(), ccff_set_children(), check_ilm(), db(), dump_blocks(), exp_addbih(), exp_label(), exp_misc(), expand(), ff_get_stmt(), fih_fini(), get_stmt(), init_ilm(), lldbg_create_file_mdnode(), lldbg_init(), lower_fileinfo(), lower_fileinfo_llvm(), parse_im_file(), print_fih(), rdilms(), rdilts(), restore_ccff_mark(), rewindilms(), save_ccff_mark(), set_allfiles(), subfih(), and wrilts().
formatbuffer
char* formatbuffer = NULL static
Definition at line 69 of file ccffinfo.c.
Referenced by ccff_cleanup_children(), ccff_cleanup_children_deferred(), ccff_open_unit(), ccff_open_unit_deferred(), fillformat(), newprintfd(), newprintfi(), newprintfl(), newprintfs(), and newprintfx().
formatbuffersize
int formatbuffersize = 0 static
Definition at line 70 of file ccffinfo.c.
Referenced by ccff_cleanup_children(), ccff_cleanup_children_deferred(), ccff_open_unit(), ccff_open_unit_deferred(), and fillformat().
globalorder
int globalorder = 0 static
Definition at line 75 of file ccffinfo.c.
Referenced by _ccff_info(), and ccff_close_unit_deferred().
ifihb
FIHB ifihb = {(FIH *)0, 0, 0, 0, 0, 0, 0, 0}
Definition at line 56 of file ccffinfo.c.
Referenced by ccff_cleanup_children_deferred(), ccff_set_children_deferred(), parse_im_file(), and print_ifih().
in_auto_reinline
bool in_auto_reinline extern
messagelist
MESSAGE** messagelist static
Definition at line 525 of file ccffinfo.c.
Referenced by _messagesort(), ccff_cleanup_children(), ccff_cleanup_children_deferred(), ccff_set_children(), ccff_set_children_deferred(), dumpmessagelist(), and sort_message_list().
messagelistsize
int messagelistsize static
Definition at line 526 of file ccffinfo.c.
Referenced by ccff_cleanup_children(), ccff_cleanup_children_deferred(), ccff_set_children(), ccff_set_children_deferred(), and sort_message_list().
nullname
const char* nullname = "" static
Definition at line 2501 of file ccffinfo.c.
Referenced by addfile(), addinlfile(), and setfile().
prevchildnest
int prevchildnest = -1 static
Definition at line 47 of file ccffinfo.c.
Referenced by fih_message_ofile(), and fih_messages().
prevlineno
int prevlineno = 0 static
Definition at line 49 of file ccffinfo.c.
Referenced by fih_message_ofile(), and fih_messages().
prevmessage
MESSAGE* prevmessage = NULL static
Definition at line 74 of file ccffinfo.c.
Referenced by _ccff_info(), ccff_close_unit(), ccff_close_unit_deferred(), and ccff_seq().
prevnest
int prevnest = -1 static
Definition at line 46 of file ccffinfo.c.
Referenced by fih_message_ofile(), and fih_messages().
strng
char* strng = NULL static
Definition at line 529 of file ccffinfo.c.
Referenced by __fih_message(), ccff_cleanup_children(), ccff_cleanup_children_deferred(), ccff_set_children(), and ccff_set_children_deferred().
strngsize
int strngsize = 0 static
Definition at line 528 of file ccffinfo.c.
Referenced by __fih_message(), ccff_cleanup_children(), ccff_cleanup_children_deferred(), ccff_set_children(), and ccff_set_children_deferred().
unitstatus
int unitstatus = -1 static
Definition at line 72 of file ccffinfo.c.
Referenced by _ccff_info(), ccff_close(), ccff_close_unit(), ccff_close_unit_deferred(), ccff_open(), ccff_open_unit(), and ccff_open_unit_deferred().