flang: ccffinfo.h File Reference
ccffinfo.h File Reference
function prototypes and macros for ccffinfo. Function prototypes and macros for common compiler feedback format module
#include <stdarg.h>
Macros
#define CCFFVERSION "0.9"
#define MSGINLINER 0x02
#define MSGNEGINLINER 0x03
#define MSGLOOP 0x04
#define MSGNEGLOOP 0x05
#define MSGLRE 0x06
#define MSGNEGLRE 0x07
#define MSGINTENSITY 0x08
#define MSGIPA 0x0a
#define MSGNEGIPA 0x0b
#define MSGFUSE 0x0c
#define MSGNEGFUSE 0x0d
#define MSGVECT 0x0e
#define MSGNEGVECT 0x0f
#define MSGOPENMP 0x10
#define MSGOPT 0x12
#define MSGNEGOPT 0x13
#define MSGPREFETCH 0x14
#define MSGFTN 0x16
#define MSGPAR 0x18
#define MSGNEGPAR 0x19
#define MSGHPF 0x1a
#define MSGPFO 0x1c
#define MSGNEGPFO 0x1d
#define MSGACCEL 0x1e
#define MSGNEGACCEL 0x1f
#define MSGUNIFIED 0x20
#define MSGCVECT 0x22
#define MSGNEGCVECT 0x23
#define MSGOMPACCEL 0x24
#define MSGPCAST 0x25
Functions
void * ccff_bih_info (int msgtype, const char *msgid, int bihx, const char *message,...)
void * subccff_bih_info (void *xparent, int msgtype, const char *msgid, int bihx, const char *message,...)
void * subccff_ilt_info (void *xparent, int msgtype, const char *msgid, int iltx, int bihx, const char *message,...)
...
void * ccff_ilt_info (int msgtype, const char *msgid, int iltx, int bihx, const char *message,...)
...
void ccff_init_f90 (void)
void ipa_report (void)
int addfile (const char *filename, const char *funcname, int tag, int flags, int lineno, int srcline, int level)
int addinlfile (const char *filename, const char *funcname, int tag, int flags, int lineno, int srcline, int level, int parent)
...
int subfih (int fihindex, int tag, int flags, int lineno)
...
void ccff_build (const char *options, const char *language)
...
void ccff_cleanup_children_deferred (void)
...
void ccff_close_unit_deferred (void)
...
void ccff_close_unit_f90 (void)
...
void ccff_close_unit (void)
...
void ccff_close (void)
...
void * ccff_func_info (int msgtype, const char *msgid, const char *funcname, const char *message,...)
...
void * ccff_info (int msgtype, const char *msgid, int fihx, int lineno, const char *message,...)
...
void * _ccff_info (int msgtype, const char *msgid, int fihx, int lineno, const char *varname, const char *funcname, void *xparent, const char *message, va_list argptr)
...
void ccff_open (const char *ccff_filename, const char *srcfile)
...
void ccff_open_unit_deferred (void)
...
void ccff_open_unit_f90 (void)
...
void ccff_open_unit (void)
...
void ccff_seq (int seq)
...
void * ccff_var_info (int msgtype, const char *msgid, const char *varname, const char *message,...)
...
void dumpmessagelist (int nmessages)
...
void fih_fini (void)
...
void print_fih (void)
...
void print_ifih (void)
...
void restore_ccff_mark (void)
...
void save_ccff_arg (const char *argname, const char *argvalue)
...
void save_ccff_mark (void)
...
void save_ccff_msg (int msgtype, const char *msgid, int fihx, int lineno, const char *varname, const char *funcname)
...
void save_ccff_text (const char *message)
...
void set_allfiles (int save)
...
void setfile (int f, const char *funcname, int tag)
...
void * subccff_info (void *xparent, int msgtype, const char *msgid, int fihx, int lineno, const char *message,...)
...
Detailed Description
function prototypes and macros for ccffinfo. Function prototypes and macros for common compiler feedback format module
Definition in file ccffinfo.h.
Macro Definition Documentation
CCFFVERSION
#define CCFFVERSION "0.9"
Definition at line 17 of file ccffinfo.h.
MSGACCEL
#define MSGACCEL 0x1e
Definition at line 63 of file ccffinfo.h.
MSGCVECT
#define MSGCVECT 0x22
Definition at line 66 of file ccffinfo.h.
MSGFTN
#define MSGFTN 0x16
Definition at line 57 of file ccffinfo.h.
MSGFUSE
#define MSGFUSE 0x0c
Definition at line 49 of file ccffinfo.h.
MSGHPF
#define MSGHPF 0x1a
Definition at line 60 of file ccffinfo.h.
MSGINLINER
#define MSGINLINER 0x02
Definition at line 40 of file ccffinfo.h.
MSGINTENSITY
#define MSGINTENSITY 0x08
Definition at line 46 of file ccffinfo.h.
MSGIPA
#define MSGIPA 0x0a
Definition at line 47 of file ccffinfo.h.
MSGLOOP
#define MSGLOOP 0x04
Definition at line 42 of file ccffinfo.h.
MSGLRE
#define MSGLRE 0x06
Definition at line 44 of file ccffinfo.h.
MSGNEGACCEL
#define MSGNEGACCEL 0x1f
Definition at line 64 of file ccffinfo.h.
MSGNEGCVECT
#define MSGNEGCVECT 0x23
Definition at line 67 of file ccffinfo.h.
MSGNEGFUSE
#define MSGNEGFUSE 0x0d
Definition at line 50 of file ccffinfo.h.
MSGNEGINLINER
#define MSGNEGINLINER 0x03
Definition at line 41 of file ccffinfo.h.
MSGNEGIPA
#define MSGNEGIPA 0x0b
Definition at line 48 of file ccffinfo.h.
MSGNEGLOOP
#define MSGNEGLOOP 0x05
Definition at line 43 of file ccffinfo.h.
MSGNEGLRE
#define MSGNEGLRE 0x07
Definition at line 45 of file ccffinfo.h.
MSGNEGOPT
#define MSGNEGOPT 0x13
Definition at line 55 of file ccffinfo.h.
MSGNEGPAR
#define MSGNEGPAR 0x19
Definition at line 59 of file ccffinfo.h.
MSGNEGPFO
#define MSGNEGPFO 0x1d
Definition at line 62 of file ccffinfo.h.
MSGNEGVECT
#define MSGNEGVECT 0x0f
Definition at line 52 of file ccffinfo.h.
MSGOMPACCEL
#define MSGOMPACCEL 0x24
Definition at line 68 of file ccffinfo.h.
MSGOPENMP
#define MSGOPENMP 0x10
Definition at line 53 of file ccffinfo.h.
MSGOPT
#define MSGOPT 0x12
Definition at line 54 of file ccffinfo.h.
MSGPAR
#define MSGPAR 0x18
Definition at line 58 of file ccffinfo.h.
MSGPCAST
#define MSGPCAST 0x25
Definition at line 69 of file ccffinfo.h.
MSGPFO
#define MSGPFO 0x1c
Definition at line 61 of file ccffinfo.h.
MSGPREFETCH
#define MSGPREFETCH 0x14
Definition at line 56 of file ccffinfo.h.
MSGUNIFIED
#define MSGUNIFIED 0x20
Definition at line 65 of file ccffinfo.h.
MSGVECT
#define MSGVECT 0x0e
Definition at line 51 of file ccffinfo.h.
Function Documentation
_ccff_info()
void * _ccff_info (int msgtype, const char * msgid, int fihx, int lineno, const char * varname, const char * funcname, void * xparent, const char * message, va_list argptr)
...
Definition at line 2215 of file ccffinfo.c.
References ccff_message::args, ccff_argument::argstring, ccff_argument::argvalue, BZERO, CCFFAREA, ccff_message::combine, COPYNSTRING, COPYSTRING, d, DBGBIT, ERR_Severe, f, FIH_CCFF, FIH_CCFFINFO, FIH_SETFLAG, ccff_message::fihx, ccff_message::funcname, gbl, GETITEM, globalorder, i, interr(), lineno, ccff_message::lineno, ccff_message::message, ccff_message::msgid, ccff_message::msgtype, newprintfd(), newprintfi(), newprintfl(), newprintfs(), newprintfx(), ccff_message::next, ccff_argument::next, NULL, ccff_message::order, parent, prevmessage, s, ccff_message::seq, unitstatus, and ccff_message::varname.
Referenced by ccff_func_info(), ccff_ilt_info(), ccff_info(), ccff_var_info(), subccff_ilt_info(), and subccff_info().
addfile()
int addfile (const char * filename, const char * funcname, int tag, int flags, int lineno, int srcline, int level)
Definition at line 2504 of file ccffinfo.c.
References BZERO, cp, FIHB::currfindex, FIHB::currftag, DBGBIT, f, FIH_DIRNAME, FIH_FILENAME, FIH_FLAGS, FIH_FULLNAME, FIH_FUNCNAME, FIH_FUNCTAG, FIH_INC, FIH_LEVEL, FIH_LINENO, FIH_PARENT, FIH_SRCLINE, fihb, filename, flags, gbl, getitem(), len, level(), lineno, NEED, NEW, FIHB::nextfindex, FIHB::nextftag, NULL, nullname, s, FIHB::stg_avail, FIHB::stg_base, FIHB::stg_size, and strlen().
Referenced by add_headerfile(), main(), and read_fileentries().
addinlfile()
int addinlfile (const char * filename, const char * funcname, int tag, int flags, int lineno, int srcline, int level, int parent)
...
Definition at line 2606 of file ccffinfo.c.
References BZERO, cp, FIHB::currfindex, FIHB::currftag, DBGBIT, f, FIH_CCFFINFO, FIH_DIRNAME, FIH_FILENAME, FIH_FLAGS, FIH_FULLNAME, FIH_FUNCNAME, FIH_FUNCTAG, FIH_LEVEL, FIH_LINENO, FIH_PARENT, FIH_SRCLINE, fihb, filename, flags, gbl, getitem(), len, level(), lineno, NEED, NEW, FIHB::nextfindex, FIHB::nextftag, NULL, nullname, parent, s, FIHB::stg_avail, FIHB::stg_base, FIHB::stg_size, and strlen().
ccff_bih_info()
void * ccff_bih_info (int msgtype, const char * msgid, int bihx, const char * message, ...)
ccff_build()
void ccff_build (const char * options, const char * language)
...
...
Definition at line 384 of file ccffinfo.c.
References BUILD_VENDOR, ccff_file, localtime(), time(), version, xmlclose(), xmlentity(), xmlentity2(), and xmlopen().
Referenced by init().
ccff_cleanup_children_deferred()
void ccff_cleanup_children_deferred (void)
...
Definition at line 2008 of file ccffinfo.c.
References childlist, childlistsize, FIH_CCFF, formatbuffer, formatbuffersize, freearea(), ICCFFAREA, IFIH_CCFFINFO, IFIH_FLAGS, ifihb, messagelist, messagelistsize, NULL, FIHB::stg_avail, strng, and strngsize.
ccff_close()
void ccff_close (void)
...
...
Definition at line 368 of file ccffinfo.c.
References anyunits, ccff_file, fclose(), NULL, unitstatus, and xmlclose().
Referenced by finish().
ccff_close_unit()
void ccff_close_unit (void)
...
Definition at line 2032 of file ccffinfo.c.
References anymessages, ccff_cleanup_children(), ccff_file, ccff_set_children(), fih_messages(), FILE, NULL, prevmessage, unitstatus, XBIT, and xmlclose().
Referenced by process_input().
ccff_close_unit_deferred()
void ccff_close_unit_deferred (void)
...
Definition at line 2055 of file ccffinfo.c.
References anymessages, ccff_set_children_deferred(), FILE, globalorder, NULL, prevmessage, unitstatus, and XBIT.
ccff_close_unit_f90()
void ccff_close_unit_f90 (void)
...
ccff_func_info()
void * ccff_func_info (int msgtype, const char * msgid, const char * funcname, const char * message, ...)
...
Definition at line 2481 of file ccffinfo.c.
References _ccff_info(), and NULL.
ccff_ilt_info()
void * ccff_ilt_info (int msgtype, const char * msgid, int iltx, int bihx, const char * message, ...)
...
Definition at line 514 of file iltutil.cpp.
References _ccff_info(), BIH_FINDEX, BIH_LINENO, ILT_FINDEX, ILT_LINENO, lineno, and NULL.
ccff_info()
void * ccff_info (int msgtype, const char * msgid, int fihx, int lineno, const char * message, ...)
...
Definition at line 2443 of file ccffinfo.c.
References _ccff_info(), lineno, and NULL.
Referenced by collapse_assignment(), conv_fused_forall(), copy_arg_to_seq_tmp(), exp_smp(), extractor_possible(), hoist_comms(), inline_func(), inline_reduction_f90(), maybe_generate_fma(), mmul(), name_dependent_check(), report_collapse(), report_comm(), and rewrite_inlined_args().
ccff_init_f90()
void ccff_init_f90 (void)
ccff_open()
void ccff_open (const char * ccff_filename, const char * srcfile)
...
...
called from main()
Definition at line 320 of file ccffinfo.c.
References ccff_file, ccff_filename, CCFFVERSION, i, malloc(), NULL, strlen(), unitstatus, xmlclose(), xmlentity(), xmlopen(), and xmlopenattrs2().
Referenced by init().
ccff_open_unit()
void ccff_open_unit (void)
...
...
Definition at line 414 of file ccffinfo.c.
References anyunits, ccff_file, ENDLINEG, flg, formatbuffer, formatbuffersize, FUNCLINEG, gbl, GBL_CURRFUNC, getexnamestring(), NULL, RU_BDATA, RU_FUNC, RU_PROG, RU_SUBR, SYMNAME, unitstatus, FLG::x, xmlclose(), xmlentity(), xmlintentity(), xmlintentity2(), and xmlopen().
Referenced by begin_entry(), and setfile().
ccff_open_unit_deferred()
void ccff_open_unit_deferred (void)
...
Definition at line 467 of file ccffinfo.c.
References ccff_file, flg, formatbuffer, formatbuffersize, NULL, unitstatus, and FLG::x.
ccff_open_unit_f90()
void ccff_open_unit_f90 (void)
...
ccff_seq()
void ccff_seq (int seq)
...
Definition at line 2494 of file ccffinfo.c.
References prevmessage, and ccff_message::seq.
ccff_var_info()
void * ccff_var_info (int msgtype, const char * msgid, const char * varname, const char * message, ...)
...
Definition at line 2469 of file ccffinfo.c.
References _ccff_info(), and NULL.
dumpmessagelist()
void dumpmessagelist (int nmessages)
...
Definition at line 566 of file ccffinfo.c.
References messagelist, and n.
fih_fini()
void fih_fini (void)
...
Definition at line 2974 of file ccffinfo.c.
References fihb, FREE, NULL, FIHB::stg_avail, FIHB::stg_base, and FIHB::stg_size.
Referenced by finish().
ipa_report()
void ipa_report (void)
Definition at line 1503 of file main.c.
print_fih()
void print_fih (void)
...
Definition at line 2985 of file ccffinfo.c.
References FIH_CCFFINFO, FIH_CHILD, FIH_FILENAME, FIH_FLAGS, FIH_FUNCNAME, FIH_LEVEL, FIH_NEXT, FIH_PARENT, fihb, i, ccff_message::message, and FIHB::stg_avail.
print_ifih()
void print_ifih (void)
...
Definition at line 3003 of file ccffinfo.c.
References i, IFIH_CCFFINFO, IFIH_CHILD, IFIH_FILENAME, IFIH_FLAGS, IFIH_FUNCNAME, IFIH_LEVEL, IFIH_LINENO, IFIH_NEXT, IFIH_PARENT, ifihb, ccff_message::message, and FIHB::stg_avail.
restore_ccff_mark()
void restore_ccff_mark (void)
...
Definition at line 2778 of file ccffinfo.c.
References FIH_PARENT, fihb, FIHB::saved_avail, and FIHB::stg_avail.
save_ccff_arg()
void save_ccff_arg (const char * argname, const char * argvalue)
...
Referenced by read_CCFF().
save_ccff_mark()
void save_ccff_mark (void)
...
Definition at line 2772 of file ccffinfo.c.
References fihb, FIHB::saved_avail, and FIHB::stg_avail.
save_ccff_msg()
void save_ccff_msg (int msgtype, const char * msgid, int fihx, int lineno, const char * varname, const char * funcname)
...
Referenced by read_CCFF().
save_ccff_text()
void save_ccff_text (const char * message)
...
Referenced by read_CCFF().
set_allfiles()
void set_allfiles (int save)
...
Definition at line 2801 of file ccffinfo.c.
References FIHB::currfindex, fihb, gbl, and FIHB::nextfindex.
Referenced by expand(), and parser().
setfile()
void setfile (int f, const char * funcname, int tag)
...
Definition at line 2724 of file ccffinfo.c.
References ccff_open_unit(), f, FIH_CCFFINFO, FIH_FLAGS, FIH_FUNCNAME, FIH_FUNCTAG, FIH_LINENO, firsttime, gbl, GBL_CURRFUNC, getitem(), ILMB::globalilmstart, ilmb, NULL, nullname, and strlen().
Referenced by push_scope_level(), and semant1().
subccff_bih_info()
void * subccff_bih_info (void * xparent, int msgtype, const char * msgid, int bihx, const char * message, ...)
subccff_ilt_info()
void * subccff_ilt_info (void * xparent, int msgtype, const char * msgid, int iltx, int bihx, const char * message, ...)
...
Definition at line 542 of file iltutil.cpp.
References _ccff_info(), BIH_FINDEX, BIH_LINENO, ILT_FINDEX, ILT_LINENO, lineno, and NULL.
subccff_info()
void * subccff_info (void * xparent, int msgtype, const char * msgid, int fihx, int lineno, const char * message, ...)
...
Definition at line 2456 of file ccffinfo.c.
References _ccff_info(), lineno, and NULL.
subfih()
int subfih (int fihindex, int tag, int flags, int lineno)
...
Definition at line 2699 of file ccffinfo.c.
References BZERO, f, FIH_DIRNAME, FIH_FILENAME, FIH_FLAGS, FIH_FULLNAME, FIH_FUNCNAME, FIH_FUNCTAG, FIH_LEVEL, FIH_LINENO, FIH_PARENT, fihb, flags, lineno, NEED, NULL, FIHB::stg_avail, FIHB::stg_base, and FIHB::stg_size.