flang: cexpf.c File Reference
cexpf.c File Reference
#include <math.h>
#include <complex.h>
#include "names.h"
#include "math_common.h"
#include "sleef_common.h"
#include "exp_common.h"
#include "cis_common.h"
#include "ldexp_common.h"
Functions
F_VISIBILITY_VEC vfloat cexpf_vec (vfloat x)
Function Documentation
cexpf_vec()
F_VISIBILITY_VEC vfloat cexpf_vec (vfloat x)
Definition at line 22 of file cexpf.c.
References __vcis_kernel(), __vexp_kernel(), __vldexpf_kernel(), FL_NINF, FL_PINF, FL_SIGN_BIT, poly, PRINT, reset, scale, vand_vi2_vi2_vi2(), vandnot_vi2_vi2_vi2(), veq_vo_vf_vf(), vF2I, vI2F, vmovehdup_vf_vf(), vmoveldup_vf_vf(), vmul_vf_vf_vf(), vor_vi2_vi2_vi2(), vsel_vf_vo_vf_vf(), vSETi, vSETLLi, and x.