flang: cexp.c File Reference
cexp/cexp.c File Reference
#include "names.h"
#include "math_common.h"
#include "sleef_common.h"
#include "ldexp_d_common.h"
#include "exp_d_common.h"
#include "cis_d_common.h"
Functions
F_VISIBILITY_VEC vdouble cexp_vec (vdouble x)
F_VISIBILITY_SCALAR double _Complex cexp_scalar_default_abi (double _Complex a)
Function Documentation
cexp_scalar_default_abi()
F_VISIBILITY_SCALAR double _Complex cexp_scalar_default_abi (double _Complex a)
Definition at line 74 of file cexp/cexp.c.
References __exp_d_scalar_kernel(), __ldexp_d_scalar_kernel(), a, assert, cexp_vec(), cimag, copysign(), creal, DB_NINF, DB_PINF, ia, L2D(), poly, PRINT, ra, res, scale, set_cmplxd(), and va.
cexp_vec()
F_VISIBILITY_VEC vdouble cexp_vec (vdouble x)
Definition at line 18 of file cexp/cexp.c.
References __vcis_d_kernel(), __vexp_d_kernel(), __vldexp_kernel(), DB_NINF, DB_PINF, DB_SIGN_BIT, poly, PRINT, reset, scale, vand_vi2_vi2_vi2(), vandnot_vi2_vi2_vi2(), vD2L, veq_vo_vd_vd(), vL2D, vmovehdup_vd_vd(), vmoveldup_vd_vd(), vmul_vd_vd_vd(), vor_vi2_vi2_vi2(), vsel_vd_vo_vd_vd(), vSETll, vSETLLL, and x.
Referenced by cexp_scalar_default_abi().