flang: cgllvm.h File Reference
cgllvm.h File Reference
Include file for ILI to LLVM translation.
#include "llutil.h"
#include "ll_ftn.h"
Classes
struct SPTRINFO_T
Macros
#define SNAME(sptr) (sptrinfo.array.stg_base[sptr])
#define LLTYPE(sptr) (sptrinfo.type_array.stg_base[sptr])
#define LLTYPE_kind(sptr) (sptrinfo.type_array.stg_base[sptr]->kind)
#define LLTYPE_size(sptr) (sptrinfo.type_array.stg_base[sptr]->size)
#define AGGREGATE_STYPE(s) ((s) == ST_STRUCT || (s) == ST_UNION || (s) == ST_ARRAY)
#define AGGREGATE_DTYPE(d) ((DTY(d)) == TY_STRUCT || (DTY(d)) == TY_UNION || (DTY(d)) == TY_ARRAY)
#define COMPLEX_DTYPE(d) ((DTY(d)) == TY_CMPLX || (DTY(d)) == TY_DCMPLX)
#define VECTOR_DTYPE(d) ((DTY(d)) == TY_VECT)
#define LLCCF_NEG
#define BITOP(i) ((i) >= I_SHL && (i) <= I_XOR)
#define BINOP(i) ((i) >= I_ADD && (i) <= I_FREM)
#define CONVERT(i) ((i) >= I_TRUNC && (i) <= I_BITCAST)
#define PICALL(i) ((i) == I_PICALL)
#define CMP_FLT 0
#define CMP_INT 1
#define CMP_USG 2
#define CARRAY_TMP 1
#define EXF_INTRINSIC 1
#define EXF_STRUCT_RETURN 2
#define EXF_VARARG 4
#define EXF_PURE 8
#define IS_OLD_STYLE_CAND(s) (DEFDG(sptr) || CCSYMG(sptr))
Typedefs
typedef enum STMT_Type STMT_Type
Enumerations
enum STMT_Type {
STMT_NONE = 0 , STMT_RET = 1 , STMT_EXPR = 2 , STMT_LABEL = 3 ,
STMT_BR = 4 , STMT_ST = 5 , STMT_CALL = 6 , STMT_SMOVE = 7 ,
STMT_SZERO = 8 , STMT_DECL = 9 , STMT_LAST = 10
}
enum MATCH_Kind { MATCH_NO = -1 , MATCH_OK = 0 , MATCH_MEM = 1 , MATCH_LAST = 2 }
Functions
void cprintf (char *s, const char *format, INT *val)
void schedule (void)
Perform code translation from ILI to LLVM for one routine.
void process_global_lifetime_debug (void)
Process symbols with global lifetime and cons their metadata.
OPERAND * gen_llvm_expr (int ilix, LL_Type *expected_type)
void clear_deletable_flags (int ilix)
Clear DELETABLE flag from previous instructions.
INSTR_LIST * llvm_info_last_instr (void)
OPERAND * gen_address_operand (int, int, bool, LL_Type *, MSZ)
Generate an address expression as an operand.
DTYPE msz_dtype (MSZ msz)
void update_external_function_declarations (const char *, char *, unsigned)
void cg_fetch_clen_parampos (SPTR *len, int *param, SPTR sptr)
void cg_llvm_init (void)
void cg_llvm_end (void)
Process the end of the file (Fortran)
void cg_llvm_fnend (void)
Process the end of the SUBROUTINE (Fortran)
void llvm_ctor_add (const char *)
void llvm_ctor_add_with_priority (const char *name, int priority)
void llvm_dtor_add (const char *)
void llvm_dtor_add_with_priority (const char *name, int priority)
void llvm_write_ctors (void)
void build_routine_and_parameter_entries (SPTR func_sptr, LL_ABI_Info *abi, LL_Module *module)
write out the header of the function definition
bool strict_match (LL_Type *, LL_Type *)
bool is_cg_llvm_init (void)
void process_formal_arguments (LL_ABI_Info *)
Process the formal arguments to the current function.
void write_external_function_declarations (int)
OPERAND * mk_alloca_instr (LL_Type *ptrTy)
INSTR_LIST * mk_store_instr (OPERAND *val, OPERAND *addr)
Variables
LL_Module * cpu_llvm_module
SPTRINFO_T sptrinfo
FILE * par_file1
FILE * par_file2
Detailed Description
Include file for ILI to LLVM translation.
Definition in file cgllvm.h.
Macro Definition Documentation
AGGREGATE_DTYPE
#define AGGREGATE_DTYPE (d) ((DTY(d)) == TY_STRUCT || (DTY(d)) == TY_UNION || (DTY(d)) == TY_ARRAY)
Definition at line 26 of file cgllvm.h.
AGGREGATE_STYPE
#define AGGREGATE_STYPE (s) ((s) == ST_STRUCT || (s) == ST_UNION || (s) == ST_ARRAY)
Definition at line 24 of file cgllvm.h.
BINOP
#define BINOP (i) ((i) >= I_ADD && (i) <= I_FREM)
Definition at line 72 of file cgllvm.h.
BITOP
#define BITOP (i) ((i) >= I_SHL && (i) <= I_XOR)
Definition at line 71 of file cgllvm.h.
CARRAY_TMP
#define CARRAY_TMP 1
Definition at line 88 of file cgllvm.h.
CMP_FLT
#define CMP_FLT 0
Definition at line 76 of file cgllvm.h.
CMP_INT
#define CMP_INT 1
Definition at line 77 of file cgllvm.h.
CMP_USG
#define CMP_USG 2
Definition at line 78 of file cgllvm.h.
COMPLEX_DTYPE
#define COMPLEX_DTYPE (d) ((DTY(d)) == TY_CMPLX || (DTY(d)) == TY_DCMPLX)
Definition at line 28 of file cgllvm.h.
CONVERT
#define CONVERT (i) ((i) >= I_TRUNC && (i) <= I_BITCAST)
Definition at line 73 of file cgllvm.h.
EXF_INTRINSIC
#define EXF_INTRINSIC 1
Definition at line 91 of file cgllvm.h.
EXF_PURE
#define EXF_PURE 8
Definition at line 94 of file cgllvm.h.
EXF_STRUCT_RETURN
#define EXF_STRUCT_RETURN 2
Definition at line 92 of file cgllvm.h.
EXF_VARARG
#define EXF_VARARG 4
Definition at line 93 of file cgllvm.h.
IS_OLD_STYLE_CAND
#define IS_OLD_STYLE_CAND (s) (DEFDG(sptr) || CCSYMG(sptr))
Definition at line 96 of file cgllvm.h.
LLCCF_NEG
#define LLCCF_NEG
Value:
  {                                                                       \
    LLCCF_NONE, LLCCF_TRUE, LLCCF_UNE, LLCCF_ULE, LLCCF_ULT, LLCCF_UGE,   \
        LLCCF_UGT, LLCCF_UNE, LLCCF_UNO, LLCCF_ONE, LLCCF_OLE, LLCCF_OLT, \
        LLCCF_OGE, LLCCF_OGT, LLCCF_OEQ, LLCCF_ORD, LLCCF_FALSE           \
  }
Definition at line 31 of file cgllvm.h.
LLTYPE
#define LLTYPE (sptr) (sptrinfo.type_array.stg_base[sptr])
Definition at line 20 of file cgllvm.h.
LLTYPE_kind
#define LLTYPE_kind (sptr) (sptrinfo.type_array.stg_base[sptr]->kind)
Definition at line 21 of file cgllvm.h.
LLTYPE_size
#define LLTYPE_size (sptr) (sptrinfo.type_array.stg_base[sptr]->size)
Definition at line 22 of file cgllvm.h.
PICALL
#define PICALL (i) ((i) == I_PICALL)
Definition at line 74 of file cgllvm.h.
SNAME
#define SNAME (sptr) (sptrinfo.array.stg_base[sptr])
Definition at line 19 of file cgllvm.h.
VECTOR_DTYPE
#define VECTOR_DTYPE (d) ((DTY(d)) == TY_VECT)
Definition at line 29 of file cgllvm.h.
Typedef Documentation
STMT_Type
typedef enum STMT_Type STMT_Type
Enumeration Type Documentation
MATCH_Kind
enum MATCH_Kind
Enumerator
MATCH_NO
MATCH_OK
MATCH_MEM
MATCH_LAST
Definition at line 80 of file cgllvm.h.
STMT_Type
enum STMT_Type
Enumerator
STMT_NONE
STMT_RET
STMT_EXPR
STMT_LABEL
STMT_BR
STMT_ST
STMT_CALL
STMT_SMOVE
STMT_SZERO
STMT_DECL
STMT_LAST
Definition at line 57 of file cgllvm.h.
Function Documentation
build_routine_and_parameter_entries()
void build_routine_and_parameter_entries (SPTR func_sptr, LL_ABI_Info * abi, LL_Module * module)
write out the header of the function definition
Writes text from define to the label of the entry block.
Definition at line 13873 of file cgmain.cpp.
References add_property_struct(), BITS_IN_BYTE, LL_Module::debug_info, get_llvm_name(), get_llvm_sname(), i, LL_Module::ir, ll_feature_debug_info_ver38, LL_MDREF_IS_NULL, ll_proto_key(), ll_proto_set_defined_body(), ll_proto_set_weak(), lldbg_subprogram(), llvm_ctor_add_with_priority(), llvm_dtor_add_with_priority(), llvm_set_unique_sym(), _OMPACCEL_TARGET::n_reduction_symbols, NULL, ompaccel_tinfo_get(), print_dbg_line_no_comma(), print_function_signature(), print_line(), print_token(), _OMPACCEL_TARGET::reduction_symbols, OMPACCEL_RED_SYM::shared_sym, size_of(), and SYMNAME.
Referenced by print_entry_subroutine(), and write_master_entry_routine().
cg_fetch_clen_parampos()
void cg_fetch_clen_parampos (SPTR * len, int * param, SPTR sptr)
Definition at line 14407 of file cgmain.cpp.
References llvm_tag::abi_info, LL_ABI_Info_::arg, i, len, llvm_info, LL_ABI_Info_::nargs, sptr, and LL_ABI_ArgInfo_::sptr.
Referenced by lldbg_create_assumed_len_string_type_mdnode().
cg_llvm_end()
void cg_llvm_end (void)
Process the end of the file (Fortran)
Dumps the metadata for the Module.
Definition at line 14122 of file cgmain.cpp.
References cpu_llvm_module, flg, gbl, gpu_llvm_module, ll_build_metadata_device(), ll_write_metadata(), llvm_file(), FLG::omptarget, and write_function_attributes().
Referenced by main().
cg_llvm_fnend()
void cg_llvm_fnend (void)
Process the end of the SUBROUTINE (Fortran)
In Fortran, we carry over data from the LONGTERM_AREA to the next subroutine to be processed.
Definition at line 14142 of file cgmain.cpp.
References assem_end(), cg_llvm_init(), CG_MEDTERM_AREA, cpu_llvm_module, freearea(), gbl, Globals, ll_reset_module_types(), llutil_struct_def_reset(), NOSYM, NULL, recorded_Globals, write_ftn_typedefs(), and write_global_and_static_defines().
Referenced by process_input(), and process_stb_file().
cg_llvm_init()
void cg_llvm_init (void)
Definition at line 14023 of file cgmain.cpp.
References assem_init(), BIH_FINDEX, CHECK, cpu_llvm_module, DBGBIT, FLG::debug, llvm_tag::declared_intrinsics, STB::dt, DT_CPTR, entry_bih, FIH_FILENAME, flg, FTN_HAS_INIT, gbl, get_llvm_version(), Globals, gpu_llvm_module, hash_functions_direct, hash_functions_strings, hashmap_alloc(), llvm_tag::homed_args, i, indent, init_gpu_output_file(), init_output_file(), llvm_tag::last_dtype_avail, llvm_tag::last_sym_avail, ll_create_module(), ll_dfile, ll_proto_init(), lldbg_init(), llvm_info, FLG::llvm_target_triple, MEM_EXTRA, NOSYM, NULL, ompaccel_get_targetriple(), FLG::omptarget, recorded_Globals, routine_count, size_of(), sptrinfo, stb, STG_ALLOC_SIDECAR, STG_CLEAR_ALL, TARGET_PTRSIZE, update_llvm_sym_arrays(), write_ftn_typedefs(), and XBIT.
Referenced by assemble(), and process_stb_file().
clear_deletable_flags()
void clear_deletable_flags (int ilix)
Clear DELETABLE flag from previous instructions.
Parameters
ilix The ILI of a LOAD instruction
Definition at line 6798 of file cgmain.cpp.
References DEBUG_ASSERT, INSTR_TAG::flags, INSTR_TAG::i_name, I_STORE, IL_TYPE, ILI_OPC, ILI_OPND, INSTR_TAG::ilix, ILTY_LOAD, llvm_tag::last_instr, llvm_info, and INSTR_TAG::prev.
cprintf()
void cprintf (char * s, const char * format, INT * val)
Definition at line 2388 of file legacy-folding-api.c.
gen_address_operand()
OPERAND * gen_address_operand (int addr_op, int nme, bool lda, LL_Type * llt_expected, MSZ msz)
Generate an address expression as an operand.
Parameters
addr_op ILI of address expression
nme NME value
lda is this an IL_LDA?
llt_expected expected LL_Type
msz memory access size
Definition at line 12473 of file cgmain.cpp.
References addressElementSize, assert, basesym_of(), LL_Type_::data_type, DBGDUMPLLTYPE, DBGTRACE4, DBGTRACEIN2, DBGTRACEOUT, DT_CPTR, ERR_Fatal, flg, gbl, GBL_CURRFUNC, gen_base_addr_operand(), get_csed_operand(), getprint(), IL_AADD, IL_ASUB, IL_NAME, ILI_COUNT, ILI_OPC, ILI_OPND, lda, LL_AddrSp_Default, LL_AddrSp_NVVM_Generic, LL_AddrSp_NVVM_Shared, ll_get_shared_arg(), LL_PTR, LL_STRUCT, ll_type_bytes_unchecked(), LLTYPE, make_lltype_from_dtype(), make_lltype_from_sptr(), make_ptr_lltype(), make_type_from_msz_with_addrspace(), msz, NME_SYM, NULL, operand, SC_AUTO, set_csed_operand(), FLG::smp, sptr, LL_Type_::sub_types, and XBIT.
gen_llvm_expr()
OPERAND * gen_llvm_expr (int ilix, LL_Type * expected_type)
Definition at line 8285 of file cgmain.cpp.
References ad1ili(), ad_csed_instr(), ad_icon, ad_instr(), ad_kconi(), add_to_cselist(), arg, args, asrt, assert, basesym_of(), bits, BITS_IN_BYTE, OPERAND::cc, CC_NE, CMP_FLT, CMP_INT, CMP_USG, complex_result_type(), convert_int_size(), convert_mismatched_types(), convert_ptr_to_int(), convert_to_llvm_fltcc(), convert_to_llvm_intcc(), convert_to_llvm_uintcc(), cpu_llvm_module, llvm_tag::curr_ret_dtype, d, LL_Type_::data_type, DBGDUMPLLTYPE, DBGTRACE1, DBGTRACE2, DBGTRACE3, DBGTRACEIN2, DBGTRACEOUT2, dt, DT_CMPLX, DT_CPTR, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, DT_ISINT, DT_ISUNSIGNED, DT_REAL, DTY, dtype_from_return_type(), DTySeqTyElement, DTyVecLength, ERR_Fatal, ERR_Severe, et, f, flags, OPERAND::flags, FLANG_FALLTHROUGH, gen_abs_expr(), gen_address_operand(), gen_base_addr_operand(), gen_binary_expr(), gen_binary_vexpr(), gen_bitcast_vector(), gen_call_as_llvm_instr(), gen_call_expr(), gen_call_llvm_intrinsic(), gen_call_pgocl_intrinsic(), gen_call_vminmax_intrinsic(), gen_call_vminmax_neon_intrinsic(), gen_call_vminmax_power_intrinsic(), gen_cmplx_math(), gen_cmplx_mul(), gen_comp_operand(), gen_const_expr(), gen_convert_vector(), gen_copy_op(), gen_copy_operand(), gen_eval_cmplx_value(), gen_extract_value(), gen_extract_value_ll(), gen_extract_vector(), gen_insert_value(), gen_instr(), gen_llvm_atomicrmw_expr(), gen_llvm_cmpxchg(), gen_llvm_cmpxchg_component(), gen_llvm_expr(), gen_llvm_select_sin_or_cos(), gen_llvm_select_vsincos(), gen_llvm_sincos_builtin(), gen_llvm_vsincos_builtin(), gen_minmax_expr(), gen_mulh_expr(), gen_optext_comp_operand(), gen_resized_vect(), gen_return_operand(), gen_scalar_to_vector(), gen_scalar_to_vector_no_shuffle(), gen_select_expr(), gen_unary_expr(), gen_va_arg(), gen_vect_compare_operand(), gen_vsincos_return_type(), get_csed_operand(), get_vcon_scalar(), get_vector_dtype(), getcon(), i, I_ADD, I_ALLOCA, I_AND, I_ASHR, I_BITCAST, I_CALL, I_FADD, I_FCMP, I_FDIV, I_FMUL, I_FPEXT, I_FPTOSI, I_FPTOUI, I_FPTRUNC, I_FREM, I_FSUB, I_ICMP, I_LSHR, I_MUL, I_OR, I_PICALL, I_SDIV, I_SELECT, I_SEXT, I_SHL, I_SHUFFVEC, I_SITOFP, I_SREM, I_SUB, I_UDIV, I_UITOFP, I_UREM, I_XOR, IEEE_CMP, IL_AADD, IL_ASUB, IL_HAS_FENCE, IL_IADD, IL_IDIV, IL_IMUL, IL_INEG, IL_ISUB, IL_MOD, IL_NAME, IL_TYPE, ILI_ALT, ILI_ccOPND(), ILI_COUNT, ILI_DTyOPND, ili_get_vect_dtype(), ILI_MSZ_OF_LD, ILI_OPC, ILI_OPND, ILI_SymOPND, ILTY_CONS, ILTY_PROC, InstrListFlagsNull, interr(), is_complex_result(), ldst_instr_flags_from_dtype(), ldst_instr_flags_from_dtype_nme(), LL_ARRAY, ll_create_int_type(), LL_DOUBLE, LL_FLOAT, ll_get_vector_type(), ll_instr_flags_for_memory_order_and_scope(), LL_PTR, OPERAND::ll_type, ll_type_bytes(), ll_type_int_bits(), ll_type_is_fp(), ll_type_is_mem_seq(), LL_VECTOR, LLCCF_OEQ, llvm_info, make_bitcast(), make_constval_op(), make_constval_opL(), make_int_lltype(), make_lltype_from_dtype(), make_load(), make_operand(), make_ptr_lltype(), make_tmp_op(), make_tmps(), make_type_from_opc(), make_undef_op(), make_var_op(), make_void_lltype(), make_vtype(), MATCH_MEM, MATCH_NO, MATCH_OK, match_types(), mftof, msz, msz_dtype(), MSZ_I8, MSZ_ILI_OPND, MSZ_WORD, name, OPERAND::next, NULL, operand, OPF_CONTAINS_UNDEF, OPF_SEXT, OPF_ZEXT, OT_CC, OPERAND::ot_type, q, QTMP_SIZE, res, set_csed_operand(), setTempMap(), sign_extend_int(), sincos_clear_all_args(), sincos_seen(), size_of(), sptr, OPERAND::sptr, SPTR_NULL, OPERAND::sptr_undef, strict_match(), LL_Type_::sub_elements, LL_Type_::sub_types, SYMNAME, t, TARGET_PTRSIZE, tmp, OPERAND::tmps, TY_FLOAT, TY_ISVECT, OPERAND::undef_mask, update_return_type_for_ccfunc(), val, OPERAND::val, VCON_CONVAL, vect_llvm_intrinsic_name(), xmdtod(), xmqtoq(), zero_extend_int(), and zsize_of().
is_cg_llvm_init()
bool is_cg_llvm_init (void)
Definition at line 14164 of file cgmain.cpp.
llvm_ctor_add()
void llvm_ctor_add (const char * name)
Definition at line 14329 of file cgmain.cpp.
References llvm_add_to_init_list(), llvm_ctor_list, and name.
Referenced by add_ctor(), and add_init_routine().
llvm_ctor_add_with_priority()
void llvm_ctor_add_with_priority (const char * name, int priority)
Definition at line 14335 of file cgmain.cpp.
References llvm_add_to_init_list(), llvm_ctor_list, name, and priority().
llvm_dtor_add()
void llvm_dtor_add (const char * name)
Definition at line 14341 of file cgmain.cpp.
References llvm_add_to_init_list(), llvm_dtor_list, and name.
llvm_dtor_add_with_priority()
void llvm_dtor_add_with_priority (const char * name, int priority)
Definition at line 14347 of file cgmain.cpp.
References llvm_add_to_init_list(), llvm_dtor_list, name, and priority().
llvm_info_last_instr()
INSTR_LIST * llvm_info_last_instr (void)
Definition at line 520 of file cgmain.cpp.
References llvm_tag::last_instr, and llvm_info.
llvm_write_ctors()
void llvm_write_ctors (void)
Definition at line 14400 of file cgmain.cpp.
References llvm_ctor_list, llvm_dtor_list, and llvm_write_ctor_dtor_list().
Referenced by assemble_end().
mk_alloca_instr()
OPERAND * mk_alloca_instr (LL_Type * ptrTy)
Definition at line 3565 of file cgmain.cpp.
References ad_instr(), gen_instr(), I_ALLOCA, make_tmp_op(), make_tmps(), NULL, and OPERAND::tmps.
mk_store_instr()
INSTR_LIST * mk_store_instr (OPERAND * val, OPERAND * addr)
Definition at line 3574 of file cgmain.cpp.
References ad_instr(), addr, cons_vec_always_metadata(), INSTR_TAG::flags, gen_instr(), I_STORE, LDST_HAS_ACCESSGRP_METADATA, INSTR_TAG::misc_metadata, NULL, and val.
msz_dtype()
DTYPE msz_dtype (MSZ msz)
Definition at line 2377 of file cgmain.cpp.
References assert, DT_CPTR, DT_DBLE, DT_FLOAT, DT_INT, ERR_Fatal, msz, MSZ_BYTE, MSZ_DFLWORD, MSZ_F16, MSZ_F32, MSZ_FWORD, MSZ_I8, MSZ_PTR, MSZ_SBYTE, MSZ_SHWORD, MSZ_SLWORD, MSZ_SWORD, MSZ_UHWORD, MSZ_ULWORD, and MSZ_UWORD.
process_formal_arguments()
void process_formal_arguments (LL_ABI_Info * abi)
Process the formal arguments to the current function.
Generate the required prolog code to home all arguments that need it.
llvm_info.abi_info must be initialized before calling this function.
Populates llvm_info.homed_args, which must be allocated and empty before the call.
Definition at line 13477 of file cgmain.cpp.
References LL_Object::address, arg, LL_ABI_Info_::arg, assert, clen_parent_is_param(), compilingGlobalOrDevice(), convert_operand(), cpu_llvm_module, llvm_tag::curr_func, LL_Value::data, LL_Type_::data_type, ERR_Fatal, LL_Function_::first_local, flags, FLANG_FALLTHROUGH, formalsAddDebug(), formalsGetDtype(), formalsMidnumNotDummy(), get_llvm_name(), hashmap_insert(), llvm_tag::homed_args, i, I_FPTRUNC, I_TRUNC, INT2HKEY, LL_Module::ir, LL_ABI_Info_::is_fortran, LL_ABI_Info_::is_iso_c, LL_Object::kind, LL_Function_::last_local, ldst_instr_flags_from_dtype(), LL_ARG_BYVAL, LL_ARG_COERCE, LL_ARG_DIRECT, LL_ARG_INDIRECT, LL_ARG_INDIRECT_BUFFERED, ll_create_local_name(), ll_create_local_object(), ll_feature_debug_info_ver90, ll_get_pointer_type(), LL_PTR, OPERAND::ll_type, ll_type_bytes(), ll_type_int_bits(), ll_type_is_fp(), llis_dummied_arg(), LLObj_LocalBuffered, LLTYPE, llvm_info, make_bitcast(), make_generic_dummy_lltype(), make_lltype_from_abi_arg(), make_load(), make_operand(), make_store(), make_var_op(), mem_size(), LL_ABI_Info_::nargs, LL_Object::next, NULL, OPERAND::ot_type, OT_VAR, process_sptr(), SNAME, LL_Object::sptr, OPERAND::sptr, OPERAND::string, LL_Type_::sub_types, suffix, SYMNAME, TY_INT, and OPERAND::val.
process_global_lifetime_debug()
void process_global_lifetime_debug (void)
Process symbols with global lifetime and cons their metadata.
Definition at line 14504 of file cgmain.cpp.
References add_debug_cmnblk_variables(), cpu_llvm_module, CUDA_HOST, CUDAG, db(), LL_Module::debug_info, gbl, LL_Module::global_debug_map, hashmap_clear(), lldbg_emit_common_block_mdnode(), lldbg_emit_module_mdnode(), lldbg_reset_module(), NOSYM, RU_BDATA, scope, sptr, and update_llvm_sym_arrays().
Referenced by process_input().
schedule()
void schedule (void)
Perform code translation from ILI to LLVM for one routine.
Definition at line 17 of file dummy.c.
strict_match()
bool strict_match (LL_Type * ty1, LL_Type * ty2)
Definition at line 12011 of file cgmain.cpp.
update_external_function_declarations()
void update_external_function_declarations (const char * name, char * decl, unsigned flags)
Definition at line 10852 of file cgmain.cpp.
References add_external_function_declaration(), flags, EXFUNC_LIST::flags, EXFUNC_LIST::func_def, getitem(), LLVM_LONGTERM_AREA, name, and strlen().
write_external_function_declarations()
void write_external_function_declarations (int first_time)
Definition at line 13303 of file cgmain.cpp.
References DBGTRACEIN, DBGTRACEOUT, ll_proto_iterate(), print_nl(), and write_extern_fndecl().
Referenced by assemble_end().
Variable Documentation
cpu_llvm_module
LL_Module* cpu_llvm_module extern
Definition at line 170 of file cgmain.cpp.
Referenced by add_ctor(), add_debug_cmnblk_variables(), add_external_function_declaration(), add_global_define(), addDebugForGlobalVar(), addDebugForLocalVar(), assemble_end(), cg_llvm_end(), cg_llvm_fnend(), cg_llvm_init(), cons_expression_metadata_operand(), cons_loop_id_md(), cons_loop_parallel_accesses_metadata(), cons_nounroll_metadata(), cons_novectorize_metadata(), cons_unroll_count_metadata(), cons_unroll_metadata(), cons_vec_always_metadata(), cons_vectorize_metadata(), cons_vectorlength_scalable_metadata(), consLoadDebug(), construct_vectorlength_metadata(), finish_routine(), formalsAddDebug(), gen_call_expr(), gen_llvm_cmpxchg(), gen_llvm_expr(), gen_ptr_offset_val(), gen_vsincos_return_type(), generating_debug_info(), insert_llvm_dbg_declare(), insert_llvm_dbg_value(), ll_check_struct_return(), ll_convert_struct_dtype(), ll_process_routine_parameters(), lldbg_create_cmblk_mem_mdnode_list(), lldbg_create_global_variable_mdnode(), lldbg_create_module_mdnode(), lldbg_emit_global_variable(), lldbg_emit_type(), llvm_get_current_module(), make_function_type_from_args(), make_instr(), process_cmnblk_data(), process_formal_arguments(), process_global_lifetime_debug(), process_params(), put_addr(), schedule(), update_llvm_sym_arrays(), write_bss(), write_I_CALL(), write_statics(), and write_typedescs().
par_file1
FILE* par_file1 extern
Definition at line 55 of file outliner.cpp.
par_file2
FILE* par_file2 extern
Definition at line 56 of file outliner.cpp.
sptrinfo
SPTRINFO_T sptrinfo extern
Definition at line 165 of file cgmain.cpp.
Referenced by cg_llvm_init().