flang: cgmain.cpp File Reference
cgmain.cpp File Reference
Main source module to translate into LLVM.
#include "cgmain.h"
#include "dtypeutl.h"
#include "ll_ftn.h"
#include "exp_rte.h"
#include "error.h"
#include "machreg.h"
#include "dinit.h"
#include "cg.h"
#include "mach.h"
#include "fih.h"
#include "pd.h"
#include "llutil.h"
#include "lldebug.h"
Classes
struct ret_tag
struct llvm_tag
struct TmpsMap
struct ComplexResultList_t
list for tracking calls with complex result types
struct init_node
struct init_list_t
Typedefs
typedef enum SincosOptimizationFlags SincosOptimizationFlags
typedef struct TmpsMap TmpsMap
typedef struct ComplexResultList_t ComplexResultList_t
list for tracking calls with complex result types
typedef struct init_node init_node
typedef struct init_list_t init_list_t
Enumerations
enum SincosOptimizationFlags { SINCOS_SIN = 1 , SINCOS_COS = 2 , SINCOS_EXTRACT = 4 , SINCOS_MASK = SINCOS_SIN | SINCOS_COS }
enum calling_conventions { CALLCONV }
Functions
static void insert_entry_label (int)
static void insert_jump_entry_instr (int ilt)
Insert the jump entry instruction.
static void store_return_value_for_entry (OPERAND *, int)
static void fma_rewrite (INSTR_LIST *isns)
Find and rewrite any multiply-add opportunities.
static void undo_recip_div (INSTR_LIST *isns)
Undoes the multiply-by-reciprocal transformation.
static const char * set_local_sname (int sptr, const char *name)
static const char * get_llvm_sname (SPTR sptr)
static int is_special_return_symbol (int sptr)
static bool cgmain_init_call (int)
static OPERAND * gen_call_llvm_intrinsic (const char *, OPERAND *, LL_Type *, INSTR_LIST *, LL_InstrName)
static OPERAND * gen_call_llvm_fm_intrinsic (const char *, OPERAND *, LL_Type *, INSTR_LIST *, LL_InstrName)
static OPERAND * gen_llvm_atomicrmw_instruction (int, int, OPERAND *, DTYPE)
static void gen_llvm_fence_instruction (int ilix)
static const char * get_atomicrmw_opname (LL_InstrListFlags)
static const char * get_atomic_memory_order_name (int)
static void insert_llvm_memcpy (int, int, OPERAND *, OPERAND *, int, int, int)
static void insert_llvm_memset (int, int, OPERAND *, int, int, int, int)
static void insert_llvm_prefetch (int ilix, OPERAND *dest_op)
static SPTR get_call_sptr (int)
static LL_Type * make_function_type_from_args (LL_Type *return_type, OPERAND *first_arg_op, bool is_varargs)
Create a function type from a return type and an argument list.
static MATCH_Kind match_types (LL_Type *ty1, LL_Type *ty2)
Does ty2 "match" ty1 or can ty2 be converted to ty1?
static int decimal_value_from_oct (int, int, int)
static char * vect_llvm_intrinsic_name (int)
static void build_unused_global_define_from_params (void)
static void print_function_signature (int func_sptr, const char *fn_name, LL_ABI_Info *abi, bool print_arg_names)
Print the signature of func_sptr, omitting the leading define/declare, ending after the function attributes.
static void write_global_and_static_defines (void)
static char * gen_constant (SPTR, DTYPE, INT, INT, int)
static char * process_string (char *name, int pad, int string_length)
Format a string for LLVM output.
static void make_stmt (STMT_Type, int, bool, SPTR next_bih_label, int ilt)
static INSTR_LIST * make_instr (LL_InstrName instr_name)
Construct an INSTR_LIST object.
static INSTR_LIST * gen_instr (LL_InstrName instr_name, TMPS *tmps, LL_Type *ll_type, OPERAND *operands)
Like make_instr, but also sets tmps, ll_type, and operands.
static OPERAND * ad_csed_instr (LL_InstrName, int, LL_Type *, OPERAND *, LL_InstrListFlags, bool)
static void ad_instr (int, INSTR_LIST *)
static OPERAND * gen_call_expr (int ilix, DTYPE ret_dtype, INSTR_LIST *call_instr, int call_sptr)
Generate LLVM instructions for a call.
static INSTR_LIST * gen_switch (int ilix)
static OPERAND * gen_unary_expr (int, LL_InstrName)
static OPERAND * gen_binary_vexpr (int, int, int, int)
static OPERAND * gen_binary_expr (int, int)
static OPERAND * gen_va_arg (int ilix)
Expand an IL_VA_ARG instruction.
static OPERAND * gen_va_start (int)
static OPERAND * gen_va_end (int)
static OPERAND * gen_gep_index (OPERAND *, LL_Type *, int)
static OPERAND * gen_insert_value (OPERAND *aggr, OPERAND *elem, unsigned index)
Generate an insertvalue instruction.
static char * gen_vconstant (const char *, int, DTYPE, int)
static LL_Type * make_vtype (DTYPE, int)
static LL_Type * make_type_from_msz (MSZ)
static LL_Type * make_type_from_msz_with_addrspace (MSZ, int)
static LL_Type * make_type_from_opc (ILI_OP)
static bool add_to_cselist (int ilix)
Add ilix to the CSE list.
static void clear_csed_list (void)
static void remove_from_csed_list (int)
static void set_csed_operand (OPERAND **, OPERAND *)
static OPERAND ** get_csed_operand (int ilix)
static void build_csed_list (int)
static OPERAND * gen_base_addr_operand (int, LL_Type *)
static OPERAND * gen_optext_comp_operand (OPERAND *operand, ILI_OP opc, int lhs_ili, int rhs_ili, int cc_ili, int cc_type, LL_InstrName itype, int optext, int ilix)
Generate comparison operand. Optionally extending the result.
static OPERAND * gen_sptr (SPTR sptr)
static OPERAND * gen_load (OPERAND *addr, LL_Type *type, LL_InstrListFlags flags)
Insert an LLVM load instruction and return the loaded value.
static void make_store (OPERAND *, OPERAND *, LL_InstrListFlags)
static OPERAND * make_load (int ilix, OPERAND *load_op, LL_Type *rslt_type, MSZ msz, unsigned flags)
return new operand of type OT_TMP as result of loading load_op
static OPERAND * convert_operand (OPERAND *convert_op, LL_Type *rslt_type, LL_InstrName convert_instruction)
static OPERAND * convert_float_size (OPERAND *, LL_Type *)
static int follow_sptr_hashlk (SPTR sptr)
static DTYPE follow_ptr_dtype (DTYPE)
static bool same_op (OPERAND *, OPERAND *)
static void write_instructions (LL_Module *module)
Write the instruction list to the LLVM IR output file.
static LLIntegerConditionCodes convert_to_llvm_intcc (CC_RELATION cc)
static LLIntegerConditionCodes convert_to_llvm_uintcc (CC_RELATION cc)
static LLFloatingPointConditionCodes convert_to_llvm_fltcc (CC_RELATION cc)
static int convert_to_llvm_cc (CC_RELATION cc, int cc_type)
static OPERAND * get_intrinsic (const char *name, LL_Type *func_type, unsigned flags)
Get an intrinsic function with name and func_type.
static OPERAND * get_intrinsic_call_ops (const char *name, LL_Type *return_type, OPERAND *args, unsigned flags)
Prepend the callee to a list of operands for an intrinsic call.
static OPERAND * sign_extend_int (OPERAND *op, unsigned result_bits)
static OPERAND * zero_extend_int (OPERAND *op, unsigned result_bits)
static bool repeats_in_binary (union xx_u)
static bool zerojump (ILI_OP)
static bool exprjump (ILI_OP)
static OPERAND * gen_resized_vect (OPERAND *vop, int new_size, int start)
Create a new vector.
static bool is_blockaddr_store (int, int, int)
static SPTR process_blockaddr_sptr (int sptr, int label)
Process block address symbol.
static bool is_256_or_512_bit_math_intrinsic (int)
static bool have_masked_intrinsic (int)
static OPERAND * make_bitcast (OPERAND *, LL_Type *)
static void update_llvm_sym_arrays (void)
Update the shadow symbol arrays.
static bool need_debug_info (SPTR sptr)
Determine if debug information is needed for a particular symbol.
static OPERAND * convert_int_size (int, OPERAND *, LL_Type *)
static OPERAND * convert_int_to_ptr (OPERAND *, LL_Type *)
static OPERAND * gen_call_vminmax_intrinsic (int ilix, OPERAND *op1, OPERAND *op2)
static OPERAND * gen_extract_value_ll (OPERAND *, LL_Type *, LL_Type *, int)
static OPERAND * gen_extract_value (OPERAND *, DTYPE, DTYPE, int)
static OPERAND * gen_vect_compare_operand (int)
static OPERAND * gen_call_vminmax_power_intrinsic (int ilix, OPERAND *op1, OPERAND *op2)
static OPERAND * gen_call_vminmax_neon_intrinsic (int ilix, OPERAND *op1, OPERAND *op2)
static INSTR_LIST * remove_instr (INSTR_LIST *instr, bool update_usect_only)
static CC_RELATION ILI_ccOPND (int i, int j)
static void consTempMap (unsigned size)
static void gcTempMap (void)
static TMPS * getTempMap (unsigned ilix)
static void setTempMap (unsigned ilix, OPERAND *op)
static const char * map_to_llvm_name (const char *function_name)
void set_llvm_sptr_name (OPERAND *operand)
...
const char * get_label_name (int sptr)
...
DTYPE cg_get_type (int n, TY_KIND v1, int v2)
...
INSTR_LIST * llvm_info_last_instr (void)
...
bool ll_check_struct_return (DTYPE dtype)
Check if the TY_STRUCT fits in registers per the ABI.
static void analyze_ret_info (SPTR func_sptr)
static INLINE OPERAND * gen_return_operand (int ilix)
Generate a return operand when ILI didn't provide a return value.
static INLINE bool on_prescan_complex_list (int ilix)
static void add_prescan_complex_list (int ilix)
static INLINE void clear_prescan_complex_list (void)
static INLINE void fix_nodepchk_flag (int bih)
static INLINE void clear_cached_loop_id_md ()
static INLINE LL_MDRef cons_loop_id_md ()
static INLINE void mark_rw_access_grp (int bih)
static INLINE void clear_rw_access_grp (void)
void print_personality (void)
...
void llvmResetSname (int sptr)
Clear SNAME for sptr.
bool currsub_is_sret (void)
...
static INLINE INSTR_LIST * find_last_executable (INSTR_LIST *i)
static int processOutlinedByConcur (int bih)
static void assign_fortran_storage_classes (void)
static INLINE LL_MDRef cons_loop_parallel_accesses_metadata (void)
static INLINE LL_MDRef cons_novectorize_metadata (void)
Construct exactly one cached instance of !{!"llvm.loop.vectorize.enable", 0}.
static INLINE LL_MDRef cons_nounroll_metadata (void)
Construct exactly one cached instance of !{!"llvm.loop.unroll.disable"}.
static INLINE LL_MDRef cons_vectorize_metadata (void)
Construct exactly one cached instance of !{!"llvm.loop.vectorize.enable", 1}.
static INLINE void remove_dead_sincos_calls (INSTR_LIST *isns)
Second pass to clean up all the dead sincos callsites.
static INLINE bool sincos_seen (void)
static INLINE void sincos_clear_all_args (void)
static INLINE void cleanup_unneeded_sincos_calls (INSTR_LIST *isns)
First pass to rewrite degenerate sincos to sin (or cos) as needed.
static INLINE bool store_for_homing (int rIli, int nme)
Is the store ILT really a homing store?
static void add_external_function_declaration (const char *key, EXFUNC_LIST *exfunc)
static void add_profile_decl (const char *key, char *gname)
static INLINE void write_profile_call (const char *profFn)
Shared code to emit a call to a profile function.
static INLINE void write_profile_enter (SPTR sptr, LL_Type *currFnTy)
Write a call to the profile entry routine.
static INLINE void write_profile_exit (void)
Write a call to the profile exit routine.
static INLINE void write_routine_definition (SPTR func_sptr, LL_ABI_Info *abi, LL_Module *module, LL_Type *funcTy)
Write out the start of an LLVM function definition.
static INLINE void finish_routine (void)
static LL_MDRef cons_vec_always_metadata (void)
Return current loop ID and mark it as vectorizable.
static LL_MDRef cons_unroll_metadata (void)
Construct exactly one cached instance of !{!"llvm.loop.unroll.enable"}.
static LL_MDRef cons_unroll_count_metadata (int unroll_factor)
Construct instance of !{!"llvm.loop.unroll.count", <unroll_factor>}.
static INLINE LL_MDRef cons_vectorlength_scalable_metadata (int arg)
Construct exactly one instance of !{!"llvm.loop.vectorize.scalable.enable", <arg>}.
static INLINE bool ignore_simd_block (int bih)
static INLINE void remove_dead_instrs (void)
Remove all deletable instructions from the instruction list.
static bool check_for_loop_directive (int branch_line_number, int xbit, int xflag)
static void process_params (void)
process debug info of constants with parameter attribute.
static void construct_vectorlength_metadata (LL_MDRef *loop_md, int vectorlength_factor, int scalable)
Constructs needed vectorlength nodes.
void schedule (void)
Perform code translation from ILI to LLVM for one routine.
static INLINE bool call_sym_is (SPTR sptr, const char *sym_name)
static OPERAND * gen_llvm_instr (int ilix, ILI_OP opc, LL_Type *return_type, LL_Type *param_lltype, LL_InstrName itype)
static OPERAND * gen_llvm_atomic_intrinsic_for_builtin (int pdnum, int sptr, int ilix, INSTR_LIST *Call_Instr)
static OPERAND * gen_alloca_call_if_necessary (SPTR sptr, int ilix)
static OPERAND * gen_unreachable_if_necessary (SPTR sptr, int ilix)
OPERAND * gen_call_as_llvm_instr (SPTR sptr, int ilix)
DTYPE msz_dtype (MSZ msz)
...
static void emit_dbg_from_module (LL_Module *module)
Create and append a !dbg info metadata from module.
static LL_Type * fixup_x86_abi_return (LL_Type *sig)
LL_Type * maybe_fixup_x86_abi_return (LL_Type *sig)
...
static int write_I_CALL (INSTR_LIST *curr_instr, bool emit_func_signature_for_call)
write I_CALL instruction
static LL_MDRef get_omnipotent_pointer (LL_Module *module)
Create the root and omnipotent pointer nodes of the TBAA tree.
static bool assumeWillAlias (int nme)
static LL_MDRef locset_to_tbaa_info (LL_Module *module, LL_MDRef omniPtr, int ilix)
Fortran location set to "TBAA" translation.
static LL_MDRef get_tbaa_metadata (LL_Module *module, int ilix, OPERAND *opnd, bool isVol)
Write TBAA metadata for the address opnd.
static INLINE bool tbaa_disabled (void)
Is TBAA disabled?
static void write_tbaa_metadata (LL_Module *mod, int ilix, OPERAND *opnd, int flags)
Write out the TBAA metadata, if needed.
static INLINE int dont_force_a_dummy_label (INSTR_LIST *insn)
Test for improperly constructed instruction streams.
static void write_memory_order (INSTR_LIST *instrs)
For the given instruction, write [singlethread] <memory ordering> to the LLVM IR output file.
static void write_memory_order_and_alignment (INSTR_LIST *instrs)
For the given instruction, write [singlethread] <memory ordering>, <alignment> to the LLVM IR output file.
static INLINE void write_llaccgroup_metadata (LL_Module *module, INSTR_LIST *insn, LL_InstrListFlags flag_check, unsigned int val)
static void write_verbose_type (LL_Type *ll_type)
static bool should_suppress_debug_loc (INSTR_LIST *instrs)
OPERAND * mk_alloca_instr (LL_Type *ptrTy)
...
INSTR_LIST * mk_store_instr (OPERAND *val, OPERAND *addr)
...
void dump_type_for_debug (LL_Type *ll_type)
...
TMPS * gen_extract_insert (LL_InstrName i_name, LL_Type *struct_type, TMPS *tmp, LL_Type *tmp_type, TMPS *tmp2, LL_Type *tmp2_type, int index)
...
static INLINE OPERAND * convert_sint_to_float (OPERAND *convert_op, LL_Type *rslt_type)
static INLINE OPERAND * convert_float_to_sint (OPERAND *convert_op, LL_Type *rslt_type)
static INLINE OPERAND * convert_uint_to_float (OPERAND *convert_op, LL_Type *rslt_type)
static INLINE OPERAND * convert_float_to_uint (OPERAND *convert_op, LL_Type *rslt_type)
static INLINE OPERAND * convert_ptr_to_int (OPERAND *convert_op, LL_Type *rslt_type)
static OPERAND * convert_mismatched_types (OPERAND *operand, LL_Type *expected_type, int ilix)
static bool cancel_store (int ilix, int op_ili, int addr_ili)
static LL_InstrListFlags ll_instr_flags_from_memory_order (MEMORY_ORDER mo)
static LL_InstrListFlags ll_instr_flags_for_memory_order_and_scope (int ilix)
From an ILI atomic instruction with a fence, get instruction flags for [singlethread] <memory order>.
static bool sincos_input_uses (int ilix, int nme)
Invalidate cached sincos intrinsics on write to input expression.
static void sincos_clear_arg_helper (hash_key_t key, hash_data_t data, void *context)
Remove all loads that correspond to a given NME.
static INLINE void sincos_clear_specific_arg (int lhs_ili, int nme)
static INLINE OPERAND * gen_sret_expr (int ilix, LL_Type *expected_type)
static SPTR make_arg_tmp (int ilix, DTYPE dtype)
Create a variable of type dtype.
OPERAND * gen_call_to_builtin (int ilix, char *fname, OPERAND *params, LL_Type *return_ll_type, INSTR_LIST *Call_Instr, LL_InstrName i_name, LL_InstrListFlags MathFlag, unsigned flags)
...
static OPERAND * gen_call_llvm_intrinsic_impl (const char *fname, OPERAND *params, LL_Type *return_ll_type, INSTR_LIST *Call_Instr, LL_InstrName i_name, LL_InstrListFlags MathFlag)
static OPERAND * gen_call_llvm_non_fm_math_intrinsic (const char *fname, OPERAND *params, LL_Type *return_ll_type, INSTR_LIST *Call_Instr, LL_InstrName i_name)
static OPERAND * gen_call_pgocl_intrinsic (const char *fname, OPERAND *params, LL_Type *return_ll_type, INSTR_LIST *Call_Instr, LL_InstrName i_name)
void insert_llvm_dbg_declare (LL_MDRef mdnode, SPTR sptr, LL_Type *llTy, OPERAND *exprMDOp, OperandFlag_t opflag)
Insert @llvm.dbg.declare call for debug.
const char * match_names (MATCH_Kind match_val)
...
static OPERAND * gen_const_expr (int ilix, LL_Type *expected_type)
static OPERAND * gen_abs_expr (int ilix)
static OPERAND * gen_minmax_expr (int ilix, OPERAND *op1, OPERAND *op2)
static OPERAND * gen_select_expr (int ilix)
static int get_vconi (DTYPE dtype, INT value)
static SPTR get_vcon0_n (DTYPE dtype, int start, int N)
static OPERAND * gen_imask (SPTR sptr)
static OPERAND * gen_insert_vector (OPERAND *vop, OPERAND *sop, int idx)
static OPERAND * gen_extract_vector (OPERAND *vop, int idx)
static OPERAND * gen_scalar_to_vector_helper (int ilix, int from_ili, LL_Type *ll_vecttype)
static INLINE OPERAND * gen_scalar_to_vector (int ilix, LL_Type *ll_vecttype)
static OPERAND * gen_scalar_to_vector_no_shuffle (int ilix, LL_Type *ll_vecttype)
static INLINE OPERAND * gen_temp_to_vector (int from_ili, LL_Type *ll_vecttype)
static OPERAND * gen_gep_op (int ilix, OPERAND *base_op, LL_Type *llt, OPERAND *index_op)
void insert_llvm_dbg_value (OPERAND *load, LL_MDRef mdnode, SPTR sptr, LL_Type *type)
Insert @llvm.dbg.value call for debug.
static void consLoadDebug (OPERAND *ld, OPERAND *addr, LL_Type *type)
Construct llvm.dbg.value calls on the load sites.
static OPERAND * gen_convert_vector (int ilix)
static OPERAND * gen_bitcast_vector (int ilix)
static int fused_multiply_add_candidate (int ilix)
Is ilix a candidate for translation to FMA?
static const char * get_mac_name (int *swap, int *fneg, int ilix, int matches, int l, int r)
Get the x86 intrinsic name of the MAC instruction.
static void fused_multiply_add_canonical_form (INSTR_LIST *addInsn, int matches, ILI_OP opc, OPERAND **l, OPERAND **r, int *lhs_ili, int *rhs_ili)
Put the candidate in proper canonical form.
static INLINE bool fma_mult_has_mult_uses (OPERAND *multop)
Does this multiply op have more than one use?
static void overwrite_fma_add (INSTR_LIST *oldAdd, INSTR_LIST *newFma, INSTR_LIST *last)
static OPERAND * x86_promote_to_vector (LL_Type *eTy, LL_Type *vTy, OPERAND *op)
static void maybe_generate_fma (int ilix, INSTR_LIST *insn)
Replace add instruction with an FMA when all conditions are met.
static OPERAND * gen_mulh_expr (int ilix)
static bool can_move_load_up_over_fence (INSTR_LIST *instr)
void clear_deletable_flags (int ilix)
Clear DELETABLE flag from previous instructions.
static INLINE OPERAND * find_load_cse (int ilix, OPERAND *load_op, LL_Type *llt)
SPTR find_pointer_to_function (int ilix)
Find the (virtual) function pointer in a JSRA call.
static void update_return_type_for_ccfunc (int ilix, ILI_OP opc)
static OPERAND * gen_arg_operand (LL_ABI_Info *abi, unsigned abi_arg, int arg_ili)
static int get_next_arg (int arg_ili)
static OPERAND * gen_arg_operand_list (LL_ABI_Info *abi, int arg_ili)
static OPERAND * gen_eval_cmplx_value (int ilix, DTYPE dtype)
static OPERAND * gen_copy_operand (OPERAND *opnd)
static OPERAND * gen_cmplx_math (int ilix, DTYPE dtype, LL_InstrName itype)
static OPERAND * gen_cmplx_mul (int ilix, DTYPE dtype)
static OPERAND * gen_llvm_atomicrmw_expr (int ilix)
static INLINE OPERAND * gen_llvm_cmpxchg (int ilix)
static OPERAND * gen_llvm_cmpxchg_component (int ilix, int idx)
static void add_sincos_map (INSTR_LIST *insn, unsigned flag)
static INLINE OPERAND * gen_llvm_select_sin_or_cos (OPERAND *op, LL_Type *argTy, LL_Type *retTy, int component)
Generate the extractvalue for the sin or cos part.
static INLINE OPERAND * gen_llvm_select_vsincos (OPERAND *op, LL_Type *argTy, LL_Type *retTy, int component)
static void add_sincos_imap_loads (int ilix)
static INLINE void add_sincos_imap (int ilix, hash_data_t data)
static INLINE OPERAND * gen_llvm_sincos_call (int ilix)
Generate a CALL to sincos, the scalar version.
static INLINE LL_Type * gen_vsincos_return_type (LL_Type *vecTy)
static INLINE OPERAND * gen_llvm_vsincos_call (int ilix)
static bool sincos_argument_valid (int ilix)
static INLINE OPERAND * get_last_sincos (int ilix)
static INLINE OPERAND * gen_llvm_sincos_builtin (int ilix)
static INLINE OPERAND * gen_llvm_vsincos_builtin (int ilix)
static INLINE bool is_complex_result (int ilix)
static INLINE LL_Type * complex_result_type (ILI_OP opc)
static INLINE OPERAND * gen_comp_operand (OPERAND *operand, ILI_OP opc, int lhs_ili, int rhs_ili, int cc_ili, int cc_type, LL_InstrName itype)
OPERAND * gen_llvm_expr (int ilix, LL_Type *expected_type)
...
static INLINE bool check_global_define (GBL_LIST *cgl)
static void add_global_define (GBL_LIST *gitem)
void update_external_function_declarations (const char *name, char *decl, unsigned flags)
...
const char * dtype_struct_name (DTYPE dtype)
Get string name for a struct type.
static const char * set_global_sname (int sptr, const char *name)
static const char * set_numbered_global_sname (int sptr, const char *name)
static void create_global_initializer (GBL_LIST *gitem, const char *flag_str, const char *type_str)
bool pointer_scalar_need_debug_info (SPTR sptr)
Check if sptr is the midnum of a scalar and scalar has POINTER/ALLOCATABLE attribute.
bool ftn_array_need_debug_info (SPTR sptr)
Check if sptr is the midnum of an array and the array has descriptor.
static INLINE bool needDebugInfoFilt (SPTR sptr)
Separate symbols that should NOT have debug information.
static INLINE bool is_ompaccel (SPTR sptr)
static INLINE bool generating_debug_info (void)
static INLINE LL_Type * mergeDebugTypesForGlobal (const char **glob, LL_Type *symTy, LL_Type *declTy)
Fixup debug info types.
static void addDebugForGlobalVar (SPTR sptr, ISZ_T off)
static void process_cmnblk_data (SPTR sptr, ISZ_T off)
static void process_static_sptr (SPTR sptr, ISZ_T off)
process SC_STATIC sptr representing a file-local variable
static void process_extern_function_sptr (SPTR sptr)
Process sptr and initialize SNAME(sptr)
static INLINE bool externVarHasDefinition (SPTR sptr)
static INLINE bool externVarMustInitialize (SPTR sptr)
static void process_extern_variable_sptr (SPTR sptr, ISZ_T off)
Process extern variable sptr and initialize SNAME(sptr)
static INLINE void addDebugForLocalVar (SPTR sptr, LL_Type *type)
add debug information for variable sptr
static void process_local_sptr (SPTR sptr)
process an SC_LOCAL sptr and initialize SNAME(sptr)
static void gen_name_private_sptr (SPTR sptr)
static void process_private_sptr (SPTR sptr)
static INLINE int compilingGlobalOrDevice ()
static INLINE bool processAutoSptr_skip (SPTR sptr)
Does this arg's pointer type really need to be dereferenced?
static INLINE LL_Type * fixup_argument_type (SPTR sptr, LL_Type *type)
static void process_auto_sptr (SPTR sptr)
Process an SC_AUTO or SC_REGISTER sptr.
static void process_label_sptr_c (SPTR sptr)
static void process_label_sptr (SPTR sptr)
Process an SC_NONE sptr.
static void process_sptr_offset (SPTR sptr, ISZ_T off)
static ISZ_T variable_offset_in_aggregate (SPTR sptr, ISZ_T idx)
Computes byte offset into aggregate structure of sptr.
void process_sptr (SPTR sptr)
...
bool strict_match (LL_Type *ty1, LL_Type *ty2)
...
int match_llvm_types (LL_Type *ty1, LL_Type *ty2)
...
int need_ptr (int sptr, int sc, DTYPE sdtype)
...
OPERAND * gen_address_operand (int addr_op, int nme, bool lda, LL_Type *llt_expected, MSZ msz)
Generate an address expression as an operand.
static OPERAND * gen_acon_expr (int ilix, LL_Type *expected_type)
Generate an OPERAND representing the value of the ACON ilix.
static OPERAND * attempt_gep_folding (int addr, BIGINT64 size)
Pattern match the ILI tree and fold when there is a match.
static OPERAND * maybe_do_gep_folding (int aadd, int idxOp, LL_Type *ty)
Attempt to convert explicit pointer scaling into GEP.
void print_tmp_name (TMPS *t)
...
char * gen_llvm_vconstant (const char *ctype, int sptr, DTYPE tdtype, int flags)
...
static char * add_tmp_buf_list_item (TEMP_BUF_LIST **tempbuflist_ptr, int sz)
static INLINE bool isNVVM (char *fn_name)
static void write_extern_fndecl (struct LL_FnProto_ *proto)
void write_external_function_declarations (int first_time)
...
static INLINE void write_target_features (void)
static INLINE void write_vscale_range (void)
static INLINE void write_function_attributes (void)
Emit function attributes in debugging mode output.
static INLINE bool formalsMidnumNotDummy (SPTR sptr)
Helper function: In Fortran, test if MIDNUM is not SC_DUMMY.
static INLINE DTYPE formalsGetDtype (SPTR s)
Helper function: Get DTYPE of s.
static INLINE OPERAND * cons_expression_metadata_operand (LL_Type *llTy)
static INLINE bool formalsNeedDebugInfo (SPTR sptr)
static INLINE void formalsAddDebug (SPTR sptr, unsigned i, LL_Type *llType, bool mayHide)
Helper function: add debug information for formal argument.
void process_formal_arguments (LL_ABI_Info *abi)
Process the formal arguments to the current function.
static void print_arg_attributes (LL_ABI_ArgInfo *arg)
Write out attributes for a function argument or return value.
INLINE static void add_property_struct (char *func_name, int nreductions, int reductionsize)
void build_routine_and_parameter_entries (SPTR func_sptr, LL_ABI_Info *abi, LL_Module *module)
write out the header of the function definition
const char * char_type (DTYPE dtype, SPTR sptr)
Get the string representation of the type of sptr or dtype.
void cg_llvm_init (void)
...
void cg_llvm_end (void)
Process the end of the file (Fortran)
void cg_llvm_fnend (void)
Process the end of the SUBROUTINE (Fortran)
bool is_cg_llvm_init (void)
...
void reset_expr_id (void)
...
static void llvm_add_to_init_list (const char *name, int priority, init_list_t *list)
void llvm_ctor_add (const char *name)
...
void llvm_ctor_add_with_priority (const char *name, int priority)
...
void llvm_dtor_add (const char *name)
...
void llvm_dtor_add_with_priority (const char *name, int priority)
...
static void llvm_write_ctor_dtor_list (init_list_t *list, const char *global_name)
void llvm_write_ctors ()
...
void cg_fetch_clen_parampos (SPTR *len, int *param, SPTR sptr)
...
bool clen_parent_is_param (SPTR length)
Helper function: test if the param length exists as compiler created symbol which represents length of any assumed length string argument in the arg list.
void add_debug_cmnblk_variables (LL_DebugInfo *db, SPTR sptr)
Process common block symbols, adding debug info for it's variables.
void process_global_lifetime_debug (void)
Process symbols with global lifetime and cons their metadata.
bool is_vector_x86_mmx (LL_Type *type)
int get_parnum (SPTR sptr)
Variables
static const char *const llvm_instr_names [I_LAST]
static const char *const stmt_names [STMT_LAST]
const int MEM_EXTRA = 500
static unsigned addressElementSize
SPTRINFO_T sptrinfo
LL_Module * current_module = NULL
LL_Module * cpu_llvm_module = NULL
LL_Module * gpu_llvm_module = NULL
struct {
unsigned _new_ebb: 1
unsigned _killCSE: 1
unsigned _init_once: 1
unsigned _cpp_init_once: 1
unsigned _ftn_init_once: 1
unsigned _float_jmp: 1
unsigned _fcmp_negate: 1
unsigned _last_stmt_is_branch: 1
unsigned _rw_acc_grp_check: 1
} CGMain
static int funcId
static int fnegcc [17] = LLCCF_NEG
static int expr_id
static int entry_bih = 0
static int routine_count
static STMT_Type curr_stmt_type
static hashmap_t sincos_map
static hashmap_t sincos_imap
static LL_MDRef cached_loop_id_md = ll_get_md_null()
static bool cached_loop_id_md_has_vectorize = false
static LL_MDRef cached_vectorize_enable_metadata = ll_get_md_null()
static LL_MDRef cached_vectorize_disable_metadata = ll_get_md_null()
static LL_MDRef cached_unroll_enable_metadata = ll_get_md_null()
static LL_MDRef cached_unroll_disable_metadata = ll_get_md_null()
static LL_MDRef cached_access_group_metadata = ll_get_md_null()
static bool CG_cpu_compile = false
static struct ret_tag ret_info
static struct llvm_tag llvm_info
static GBL_LIST * Globals
static GBL_LIST * recorded_Globals
static INSTR_LIST * Instructions
static CSED_ITEM * csedList
static TmpsMap tempsMap
static ComplexResultList_t complexResultList
const char * cc_as_str [] = {CALLCONV}
static init_list_t llvm_ctor_list
static init_list_t llvm_dtor_list
Detailed Description
Main source module to translate into LLVM.
Definition in file cgmain.cpp.
Typedef Documentation
ComplexResultList_t
typedef struct ComplexResultList_t ComplexResultList_t
list for tracking calls with complex result types
init_list_t
typedef struct init_list_t init_list_t
init_node
typedef struct init_node init_node
SincosOptimizationFlags
typedef enum SincosOptimizationFlags SincosOptimizationFlags
TmpsMap
typedef struct TmpsMap TmpsMap
Enumeration Type Documentation
calling_conventions
enum calling_conventions
Enumerator
CALLCONV
Definition at line 2427 of file cgmain.cpp.
SincosOptimizationFlags
enum SincosOptimizationFlags
Enumerator
SINCOS_SIN
SINCOS_COS
SINCOS_EXTRACT
SINCOS_MASK
Definition at line 57 of file cgmain.cpp.
Function Documentation
ad_csed_instr()
static OPERAND * ad_csed_instr (LL_InstrName instr_name, int ilix, LL_Type * ll_type, OPERAND * operands, LL_InstrListFlags flags, bool do_cse) static
Definition at line 3780 of file cgmain.cpp.
References ad_instr(), cons_vec_always_metadata(), convert_mismatched_types(), flags, INSTR_TAG::flags, FLANG_FALLTHROUGH, gen_instr(), I_BR, I_CALL, I_INDBR, I_INVOKE, I_LOAD, INSTR_TAG::i_name, I_NONE, I_SW, llvm_tag::last_instr, LDST_HAS_ACCESSGRP_METADATA, INSTR_TAG::ll_type, llvm_info, make_tmp_op(), make_tmps(), INSTR_TAG::misc_metadata, OPERAND::next, NULL, operand, INSTR_TAG::operands, INSTR_TAG::prev, same_op(), STARTEBB, and INSTR_TAG::tmps.
Referenced by convert_int_size(), gen_binary_expr(), gen_cmplx_math(), gen_cmplx_mul(), gen_gep_op(), gen_insert_value(), gen_llvm_atomicrmw_expr(), gen_llvm_cmpxchg(), gen_llvm_expr(), gen_load(), gen_mulh_expr(), gen_unary_expr(), gen_va_arg(), and gen_vect_compare_operand().
ad_instr()
static void ad_instr (int ilix, INSTR_LIST * instr) static
Definition at line 3837 of file cgmain.cpp.
References assert, DEBUG_ASSERT, ERR_Fatal, INSTR_TAG::flags, INSTR_TAG::ilix, Instructions, llvm_tag::last_instr, llvm_info, INSTR_TAG::next, NULL, operand, INSTR_TAG::operands, OT_TMP, INSTR_TAG::prev, and STARTEBB.
Referenced by ad_csed_instr(), convert_float_size(), convert_operand(), fused_multiply_add_canonical_form(), gen_abs_expr(), gen_call_expr(), gen_call_to_builtin(), gen_extract_insert(), gen_extract_value_ll(), gen_extract_vector(), gen_insert_vector(), gen_llvm_expr(), gen_llvm_fence_instruction(), gen_llvm_instr(), gen_minmax_expr(), gen_optext_comp_operand(), gen_resized_vect(), gen_scalar_to_vector_helper(), gen_select_expr(), gen_switch(), gen_unreachable_if_necessary(), insert_entry_label(), insert_jump_entry_instr(), insert_llvm_dbg_declare(), insert_llvm_dbg_value(), insert_llvm_memcpy(), insert_llvm_memset(), insert_llvm_prefetch(), make_bitcast(), make_load(), make_stmt(), mk_alloca_instr(), mk_store_instr(), and schedule().
add_debug_cmnblk_variables()
void add_debug_cmnblk_variables (LL_DebugInfo * db, SPTR sptr)
Process common block symbols, adding debug info for it's variables.
Parameters
sptr A symbol
Definition at line 14441 of file cgmain.cpp.
References addDebugForGlobalVar(), cpu_llvm_module, db(), gbl, hash_functions_strings, hashset_alloc(), hashset_insert(), hashset_lookup(), LL_Module::ir, ll_feature_debug_info_ver11, lldbg_add_pending_import_entity(), lldbg_add_pending_import_entity_to_child(), lookup_modvar_alias(), new_debug_name(), NOSYM, NULL, RU_BDATA, scope, SNAME, sptr, SYMNAME, and variable_offset_in_aggregate().
Referenced by lldbg_emit_common_block_mdnode(), and process_global_lifetime_debug().
add_external_function_declaration()
static void add_external_function_declaration (const char * key, EXFUNC_LIST * exfunc) static
Definition at line 1129 of file cgmain.cpp.
References LL_ABI_Info_::arg, assert, cpu_llvm_module, LL_Type_::data_type, DEBUG_ASSERT, ERR_Fatal, EXF_INTRINSIC, EXF_PURE, EXFUNC_LIST::flags, EXFUNC_LIST::func_def, i, LL_ABI_Info_::is_pure, is_vector_x86_mmx(), ll_abi_alloc(), ll_abi_for_func_sptr(), ll_convert_dtype(), ll_create_basic_type(), ll_get_pointer_type(), ll_proto_add(), ll_proto_add_sptr(), ll_proto_key(), ll_proto_set_intrinsic(), ll_proto_set_weak(), LL_PTR, LL_X86_MMX, LL_Type_::module, LL_ABI_Info_::nargs, NULL, sptr, EXFUNC_LIST::sptr, and LL_ABI_ArgInfo_::type.
Referenced by add_profile_decl(), gen_va_end(), gen_va_start(), insert_llvm_dbg_declare(), insert_llvm_dbg_value(), insert_llvm_memcpy(), insert_llvm_memset(), insert_llvm_prefetch(), process_extern_function_sptr(), and update_external_function_declarations().
add_global_define()
static void add_global_define (GBL_LIST * gitem) static
Definition at line 10822 of file cgmain.cpp.
References check_global_define(), cpu_llvm_module, DBGTRACEIN2, DBGTRACEOUT, FLG::debug, LL_Module::debug_info, flg, GBL_TAG::global_def, Globals, llvm_tag::last_global, ll_create_value_from_type(), lldbg_emit_global_variable(), llvm_info, make_lltype_from_sptr(), GBL_TAG::next, SNAME, GBL_TAG::sptr, ST_ISVAR, type, and value().
Referenced by process_blockaddr_sptr(), and process_local_sptr().
add_prescan_complex_list()
static void add_prescan_complex_list (int ilix) static
Definition at line 721 of file cgmain.cpp.
References complexResultList, ComplexResultList_t::entries, ComplexResultList_t::list, on_prescan_complex_list(), size, and ComplexResultList_t::size.
Referenced by build_csed_list().
add_profile_decl()
static void add_profile_decl (const char * key, char * gname) static
Definition at line 1186 of file cgmain.cpp.
References add_external_function_declaration(), EXF_INTRINSIC, EXFUNC_LIST::flags, EXFUNC_LIST::func_def, getitem(), and LLVM_LONGTERM_AREA.
Referenced by write_profile_enter().
add_property_struct()
INLINE static void add_property_struct (char * func_name, int nreductions, int reductionsize) static
Definition at line 13858 of file cgmain.cpp.
References print_token().
Referenced by build_routine_and_parameter_entries().
add_sincos_imap()
static INLINE void add_sincos_imap (int ilix, hash_data_t data) static
Definition at line 8128 of file cgmain.cpp.
References hashmap_replace(), INT2HKEY, and sincos_imap.
Referenced by gen_llvm_sincos_call(), and gen_llvm_vsincos_call().
add_sincos_imap_loads()
static void add_sincos_imap_loads (int ilix) static
Definition at line 8111 of file cgmain.cpp.
References add_sincos_imap_loads(), hashmap_replace(), i, IL_ISLINK, IL_TYPE, ILI_OPC, ILI_OPND, ilis, ILTY_LOAD, INT2HKEY, NULL, ILIINFO::oprs, and sincos_imap.
Referenced by add_sincos_imap_loads(), gen_llvm_sincos_call(), and gen_llvm_vsincos_call().
add_sincos_map()
static void add_sincos_map (INSTR_LIST * insn, unsigned flag) static
Definition at line 8074 of file cgmain.cpp.
References hash_functions_direct, hashmap_alloc(), hashmap_lookup(), hashmap_replace(), HKEY2INT, INT2HKEY, NULL, and sincos_map.
Referenced by gen_llvm_select_sin_or_cos(), and gen_llvm_select_vsincos().
add_tmp_buf_list_item()
static char * add_tmp_buf_list_item (TEMP_BUF_LIST ** tempbuflist_ptr, int sz) static
Definition at line 13224 of file cgmain.cpp.
References CG_MEDTERM_AREA, getitem(), i, last, NULL, and sz.
add_to_cselist()
static bool add_to_cselist (int ilix) static
Add ilix to the CSE list.
Parameters
ilix The ILI index to be added
Returns
true iff ilix already appears in the CSE list
Definition at line 10646 of file cgmain.cpp.
References build_csed_list(), csedList, DBGTRACE1, DBGTRACE2, getitem(), ILI_ALT, ILI_COUNT, CSED_TAG::ilix, LLVM_LONGTERM_AREA, and CSED_TAG::next.
Referenced by build_csed_list(), and gen_llvm_expr().
addDebugForGlobalVar()
static void addDebugForGlobalVar (SPTR sptr, ISZ_T off) static
Definition at line 11300 of file cgmain.cpp.
References cpu_llvm_module, LL_Module::debug_info, ll_create_value_from_type(), ll_get_pointer_type(), lldbg_emit_global_variable(), LLTYPE, make_lltype_from_dtype(), make_lltype_from_sptr(), mergeDebugTypesForGlobal(), need_debug_info(), off, SNAME, sptr, and val.
Referenced by add_debug_cmnblk_variables(), process_extern_variable_sptr(), and process_static_sptr().
addDebugForLocalVar()
static INLINE void addDebugForLocalVar (SPTR sptr, LL_Type * type) static
add debug information for variable sptr
Parameters
sptr the symbol to be added
type the type to be used for sptr
Definition at line 11601 of file cgmain.cpp.
References BIH_FINDEX, cpu_llvm_module, LL_Type_::data_type, LL_Module::debug_info, ftn_array_need_debug_info(), gbl, insert_llvm_dbg_declare(), LL_Module::ir, ll_feature_debug_info_ver90, LL_PTR, lldbg_emit_local_variable(), LLTYPE, need_debug_info(), NULL, OPF_NONE, pointer_scalar_need_debug_info(), sptr, LL_Type_::sub_types, and type.
Referenced by gen_name_private_sptr(), process_auto_sptr(), and process_local_sptr().
analyze_ret_info()
static void analyze_ret_info (SPTR func_sptr) static
Definition at line 594 of file cgmain.cpp.
References llvm_tag::abi_info, LL_ABI_Info_::arg, assert, aux, CMPLXFUNC_C, DBGTRACE2, DT_INT, DT_ISCMPLX, ret_tag::emit_sret, AUX::entry_base, ERR_Fatal, gbl, get_return_type(), has_multiple_entries(), LL_ABI_HAS_SRET, llvm_info, make_lltype_from_abi_arg(), make_lltype_from_dtype(), make_void_lltype(), process_sptr(), ret_info, ENTRY::ret_var, llvm_tag::return_ll_type, ret_tag::sret_sptr, and LL_ABI_ArgInfo_::type.
Referenced by schedule().
assign_fortran_storage_classes()
static void assign_fortran_storage_classes (void) static
Definition at line 913 of file cgmain.cpp.
References STB::firstusym, flg, gbl, FLG::recursive, FLG::smp, sptr, stb, and XBIT.
Referenced by schedule().
assumeWillAlias()
static bool assumeWillAlias (int nme) static
Definition at line 2661 of file cgmain.cpp.
References DTY, NME_NM, NME_SYM, NME_TYPE, NT_ARR, NT_IND, NT_MEM, and NT_SAFE.
Referenced by locset_to_tbaa_info().
attempt_gep_folding()
static OPERAND * attempt_gep_folding (int addr, BIGINT64 size) static
Pattern match the ILI tree and fold when there is a match.
Parameters
addr The ILI to pattern match
size The expected type size
Definition at line 12669 of file cgmain.cpp.
References addr, CONVAL2G, gen_llvm_expr(), ILI_OPC, ILI_OPND, make_int_lltype(), NULL, size, and val.
Referenced by maybe_do_gep_folding().
build_csed_list()
static void build_csed_list (int ilix) static
Definition at line 10754 of file cgmain.cpp.
References add_prescan_complex_list(), add_to_cselist(), build_csed_list(), i, IL_ISLINK, ILI_ALT, ILI_OPC, ILI_OPND, ilis, is_cseili_opcode(), and ILIINFO::oprs.
Referenced by add_to_cselist(), build_csed_list(), and schedule().
build_routine_and_parameter_entries()
void build_routine_and_parameter_entries (SPTR func_sptr, LL_ABI_Info * abi, LL_Module * module)
write out the header of the function definition
...
Writes text from define to the label of the entry block.
Definition at line 13873 of file cgmain.cpp.
References add_property_struct(), BITS_IN_BYTE, LL_Module::debug_info, get_llvm_name(), get_llvm_sname(), i, LL_Module::ir, ll_feature_debug_info_ver38, LL_MDREF_IS_NULL, ll_proto_key(), ll_proto_set_defined_body(), ll_proto_set_weak(), lldbg_subprogram(), llvm_ctor_add_with_priority(), llvm_dtor_add_with_priority(), llvm_set_unique_sym(), _OMPACCEL_TARGET::n_reduction_symbols, NULL, ompaccel_tinfo_get(), print_dbg_line_no_comma(), print_function_signature(), print_line(), print_token(), _OMPACCEL_TARGET::reduction_symbols, OMPACCEL_RED_SYM::shared_sym, size_of(), and SYMNAME.
Referenced by print_entry_subroutine(), write_master_entry_routine(), and write_routine_definition().
build_unused_global_define_from_params()
static void build_unused_global_define_from_params (void) static
Definition at line 13375 of file cgmain.cpp.
Referenced by schedule().
call_sym_is()
static INLINE bool call_sym_is (SPTR sptr, const char * sym_name) static
Definition at line 2096 of file cgmain.cpp.
References sptr, strlen(), and SYMNAME.
Referenced by gen_alloca_call_if_necessary(), and gen_unreachable_if_necessary().
can_move_load_up_over_fence()
static bool can_move_load_up_over_fence (INSTR_LIST * instr) static
Return true if a load can be moved upwards (backwards in time) over fencing specified by the given instruction.
Definition at line 6781 of file cgmain.cpp.
References ATOMIC_ACQ_REL_FLAG, ATOMIC_ACQUIRE_FLAG, ATOMIC_MEM_ORD_FLAGS, ATOMIC_SEQ_CST_FLAG, and INSTR_TAG::flags.
Referenced by find_load_cse().
cancel_store()
static bool cancel_store (int ilix, int op_ili, int addr_ili) static
Definition at line 3872 of file cgmain.cpp.
References DBGTRACE1, IL_TYPE, ILI_OPC, ILI_OPND, ILTY_LOAD, and is_cseili_opcode().
Referenced by make_stmt().
cg_fetch_clen_parampos()
void cg_fetch_clen_parampos (SPTR * len, int * param, SPTR sptr)
...
Definition at line 14407 of file cgmain.cpp.
References llvm_tag::abi_info, LL_ABI_Info_::arg, i, len, llvm_info, LL_ABI_Info_::nargs, sptr, and LL_ABI_ArgInfo_::sptr.
Referenced by lldbg_create_assumed_len_string_type_mdnode().
cg_get_type()
DTYPE cg_get_type (int n, TY_KIND v1, int v2)
...
Definition at line 512 of file cgmain.cpp.
References get_type(), n, and update_llvm_sym_arrays().
Referenced by gen_llvm_atomic_intrinsic_for_builtin(), ll_make_kmpc_struct_type(), mk_struct_for_llvm_init(), and update_return_type_for_ccfunc().
cg_llvm_end()
void cg_llvm_end (void)
Process the end of the file (Fortran)
...
Dumps the metadata for the Module.
Definition at line 14122 of file cgmain.cpp.
References cpu_llvm_module, flg, gbl, gpu_llvm_module, ll_build_metadata_device(), ll_write_metadata(), llvm_file(), FLG::omptarget, and write_function_attributes().
Referenced by main().
cg_llvm_fnend()
void cg_llvm_fnend (void)
Process the end of the SUBROUTINE (Fortran)
...
In Fortran, we carry over data from the LONGTERM_AREA to the next subroutine to be processed.
Definition at line 14142 of file cgmain.cpp.
References assem_end(), cg_llvm_init(), CG_MEDTERM_AREA, cpu_llvm_module, freearea(), gbl, Globals, ll_reset_module_types(), llutil_struct_def_reset(), NOSYM, NULL, recorded_Globals, write_ftn_typedefs(), and write_global_and_static_defines().
Referenced by process_input(), and process_stb_file().
cg_llvm_init()
void cg_llvm_init (void)
...
Definition at line 14023 of file cgmain.cpp.
References assem_init(), BIH_FINDEX, CHECK, cpu_llvm_module, DBGBIT, FLG::debug, llvm_tag::declared_intrinsics, STB::dt, DT_CPTR, entry_bih, FIH_FILENAME, flg, FTN_HAS_INIT, gbl, get_llvm_version(), Globals, gpu_llvm_module, hash_functions_direct, hash_functions_strings, hashmap_alloc(), llvm_tag::homed_args, i, indent, init_gpu_output_file(), init_output_file(), llvm_tag::last_dtype_avail, llvm_tag::last_sym_avail, ll_create_module(), ll_dfile, ll_proto_init(), lldbg_init(), llvm_info, FLG::llvm_target_triple, MEM_EXTRA, NOSYM, NULL, ompaccel_get_targetriple(), FLG::omptarget, recorded_Globals, routine_count, size_of(), sptrinfo, stb, STG_ALLOC_SIDECAR, STG_CLEAR_ALL, TARGET_PTRSIZE, update_llvm_sym_arrays(), write_ftn_typedefs(), and XBIT.
Referenced by assemble(), cg_llvm_fnend(), process_stb_file(), and schedule().
cgmain_init_call()
static bool cgmain_init_call (int sptr) static
Definition at line 2371 of file cgmain.cpp.
References sptr, and SYMNAME.
Referenced by process_extern_function_sptr(), and schedule().
char_type()
const char * char_type (DTYPE dtype, SPTR sptr)
Get the string representation of the type of sptr or dtype.
...
Parameters
sptr symbol to use for type consing or 0
dtype used when sptr not provided
Definition at line 13993 of file cgmain.cpp.
References make_lltype_from_dtype(), make_lltype_from_sptr(), need_ptr(), sptr, LL_Type_::str, and LL_Type_::sub_types.
Referenced by gen_constant(), ll_process_routine_parameters(), process_blockaddr_sptr(), process_extern_function_sptr(), process_extern_variable_sptr(), process_local_sptr(), put_fstr(), put_kstr(), write_comm(), write_consts(), and write_externs().
check_for_loop_directive()
static bool check_for_loop_directive (int branch_line_number, int xbit, int xflag) static
Definition at line 1390 of file cgmain.cpp.
References DIRECT::avail, direct, lpprg_::dirset, lpprg_::end_line, DIRECT::lpg, DIRECT::stgb, and DIRSET::x.
Referenced by schedule().
check_global_define()
static INLINE bool check_global_define (GBL_LIST * cgl) static
Definition at line 10802 of file cgmain.cpp.
References DBGTRACE1, getitem(), GBL_TAG::global_def, LLVM_LONGTERM_AREA, GBL_TAG::next, recorded_Globals, and GBL_TAG::sptr.
Referenced by add_global_define().
cleanup_unneeded_sincos_calls()
static INLINE void cleanup_unneeded_sincos_calls (INSTR_LIST * isns) static
First pass to rewrite degenerate sincos to sin (or cos) as needed.
Parameters
isns The list of instructions
Definition at line 1053 of file cgmain.cpp.
References LL_Type_::data_type, DEBUG_ASSERT, DT_DBLE, DT_FLOAT, EXF_PURE, gen_call_to_builtin(), hashmap_lookup(), HKEY2INT, I_CALL, I_EXTRACTVAL, TMP_TAG::idef, ili_get_vect_arg_count(), ILI_OPC, ILI_OPND, INSTR_TAG::ilix, TMP_TAG::info, InstrListFlagsNull, LL_VECTOR, llmk_math_name(), make_lltype_from_dtype(), MTH_cos, MTH_sin, name, OPERAND::next, NULL, INSTR_TAG::operands, p, SINCOS_COS, sincos_map, SINCOS_MASK, sincos_seen(), LL_Type_::sub_elements, LL_Type_::sub_types, t, and OPERAND::tmps.
Referenced by schedule().
clear_cached_loop_id_md()
static INLINE void clear_cached_loop_id_md () static
Definition at line 764 of file cgmain.cpp.
References cached_loop_id_md, cached_loop_id_md_has_vectorize, and ll_get_md_null.
Referenced by clear_rw_access_grp(), and mark_rw_access_grp().
clear_csed_list()
static void clear_csed_list (void) static
Definition at line 10690 of file cgmain.cpp.
References csedList, ILI_COUNT, CSED_TAG::ilix, CSED_TAG::next, NULL, and CSED_TAG::operand.
Referenced by maybe_generate_fma(), and schedule().
clear_deletable_flags()
void clear_deletable_flags (int ilix)
Clear DELETABLE flag from previous instructions.
...
Parameters
ilix The ILI of a LOAD instruction
Definition at line 6798 of file cgmain.cpp.
References DEBUG_ASSERT, INSTR_TAG::flags, INSTR_TAG::i_name, I_STORE, IL_TYPE, ILI_OPC, ILI_OPND, INSTR_TAG::ilix, ILTY_LOAD, llvm_tag::last_instr, llvm_info, and INSTR_TAG::prev.
clear_prescan_complex_list()
static INLINE void clear_prescan_complex_list (void) static
Definition at line 739 of file cgmain.cpp.
References complexResultList, ComplexResultList_t::entries, ComplexResultList_t::list, NULL, and ComplexResultList_t::size.
Referenced by schedule().
clear_rw_access_grp()
static INLINE void clear_rw_access_grp (void) static
Definition at line 791 of file cgmain.cpp.
References clear_cached_loop_id_md().
Referenced by schedule().
clen_parent_is_param()
bool clen_parent_is_param (SPTR length)
Helper function: test if the param length exists as compiler created symbol which represents length of any assumed length string argument in the arg list.
...
Parameters
length is the compiler created symbol which represents length of assumed length string argument
Definition at line 14428 of file cgmain.cpp.
References llvm_tag::abi_info, LL_ABI_Info_::arg, DTY, i, length(), llvm_info, LL_ABI_Info_::nargs, parent, LL_ABI_ArgInfo_::sptr, and TY_CHAR.
Referenced by process_formal_arguments().
compilingGlobalOrDevice()
static INLINE int compilingGlobalOrDevice () static
Definition at line 11735 of file cgmain.cpp.
References CG_cpu_compile, CUDA_DEVICE, CUDA_GLOBAL, CUDAG, and gbl.
Referenced by gen_acon_expr(), process_formal_arguments(), process_sptr_offset(), and processAutoSptr_skip().
complex_result_type()
static INLINE LL_Type * complex_result_type (ILI_OP opc) static
Definition at line 8264 of file cgmain.cpp.
References make_lltype_from_dtype(), and NULL.
Referenced by gen_llvm_expr().
cons_expression_metadata_operand()
static INLINE OPERAND * cons_expression_metadata_operand (LL_Type * llTy) static
Definition at line 13402 of file cgmain.cpp.
References cpu_llvm_module, LL_Type_::data_type, LL_Module::debug_info, LL_DW_OP_deref, LL_PTR, lldbg_emit_expression_mdnode(), lldbg_encode_expression_arg(), make_mdref_op(), and NULL.
Referenced by formalsAddDebug().
cons_loop_id_md()
static INLINE LL_MDRef cons_loop_id_md () static
Definition at line 773 of file cgmain.cpp.
References cached_loop_id_md, cpu_llvm_module, ll_create_flexible_md_node(), ll_extend_md_node(), and LL_MDREF_IS_NULL.
Referenced by cons_vec_always_metadata(), and schedule().
cons_loop_parallel_accesses_metadata()
static INLINE LL_MDRef cons_loop_parallel_accesses_metadata (void) static
Definition at line 952 of file cgmain.cpp.
References cached_access_group_metadata, cpu_llvm_module, ll_get_md_node(), ll_get_md_string(), and LL_PlainMDNode.
Referenced by cons_vec_always_metadata().
cons_nounroll_metadata()
static INLINE LL_MDRef cons_nounroll_metadata (void) static
Construct exactly one cached instance of !{!"llvm.loop.unroll.disable"}.
Definition at line 981 of file cgmain.cpp.
References cached_unroll_disable_metadata, cpu_llvm_module, ll_get_md_node(), ll_get_md_string(), LL_MDREF_IS_NULL, and LL_PlainMDNode.
Referenced by schedule().
cons_novectorize_metadata()
static INLINE LL_MDRef cons_novectorize_metadata (void) static
Construct exactly one cached instance of !{!"llvm.loop.vectorize.enable", 0}.
Definition at line 965 of file cgmain.cpp.
References cached_vectorize_disable_metadata, cpu_llvm_module, ll_get_md_i1(), ll_get_md_node(), ll_get_md_string(), LL_MDREF_IS_NULL, and LL_PlainMDNode.
Referenced by schedule().
cons_unroll_count_metadata()
static LL_MDRef cons_unroll_count_metadata (int unroll_factor) static
Construct instance of !{!"llvm.loop.unroll.count", <unroll_factor>}.
Definition at line 1338 of file cgmain.cpp.
References cpu_llvm_module, ll_get_md_i32(), ll_get_md_node(), ll_get_md_string(), LL_PlainMDNode, and unroll().
Referenced by schedule().
cons_unroll_metadata()
static LL_MDRef cons_unroll_metadata (void) static
Construct exactly one cached instance of !{!"llvm.loop.unroll.enable"}.
Definition at line 1323 of file cgmain.cpp.
References cached_unroll_enable_metadata, cpu_llvm_module, ll_get_md_node(), ll_get_md_string(), LL_MDREF_IS_NULL, and LL_PlainMDNode.
Referenced by schedule().
cons_vec_always_metadata()
static LL_MDRef cons_vec_always_metadata (void) static
Return current loop ID and mark it as vectorizable.
"NODEPCHK" and "VECTOR ALWAYS" currently both mean to mark a loop ID with !"llvm.loop.vectorize.enable", and to mark memory instructions with !llvm.access.group referring to the cached access group. This function returns the current loop ID metadata via cons_loop_id_md() and marks the loop as vectorizable.
Definition at line 1306 of file cgmain.cpp.
References cached_loop_id_md_has_vectorize, cons_loop_id_md(), cons_loop_parallel_accesses_metadata(), cons_vectorize_metadata(), cpu_llvm_module, ll_extend_md_node(), and vectorize().
Referenced by ad_csed_instr(), make_load(), mk_store_instr(), and schedule().
cons_vectorize_metadata()
static INLINE LL_MDRef cons_vectorize_metadata (void) static
Construct exactly one cached instance of !{!"llvm.loop.vectorize.enable", 1}.
Definition at line 996 of file cgmain.cpp.
References cached_vectorize_enable_metadata, cpu_llvm_module, ll_get_md_i1(), ll_get_md_node(), ll_get_md_string(), LL_MDREF_IS_NULL, and LL_PlainMDNode.
Referenced by cons_vec_always_metadata(), and construct_vectorlength_metadata().
cons_vectorlength_scalable_metadata()
static INLINE LL_MDRef cons_vectorlength_scalable_metadata (int arg) static
Construct exactly one instance of !{!"llvm.loop.vectorize.scalable.enable", <arg>}.
Definition at line 1352 of file cgmain.cpp.
References arg, cpu_llvm_module, ll_get_md_i1(), ll_get_md_node(), ll_get_md_string(), and LL_PlainMDNode.
Referenced by construct_vectorlength_metadata().
consLoadDebug()
static void consLoadDebug (OPERAND * ld, OPERAND * addr, LL_Type * type) static
Construct llvm.dbg.value calls on the load sites.
Parameters
ld The load
addr The address being loaded
type The type of the object being loaded
Definition at line 5678 of file cgmain.cpp.
References addr, BIH_FINDEX, cpu_llvm_module, LL_Module::debug_info, gbl, insert_llvm_dbg_value(), ld, lldbg_emit_local_variable(), need_debug_info(), sptr, and type.
Referenced by gen_load(), and make_load().
consTempMap()
static void consTempMap (unsigned size) static
Definition at line 421 of file cgmain.cpp.
References TmpsMap::map, size, TmpsMap::size, and tempsMap.
Referenced by schedule().
construct_vectorlength_metadata()
static void construct_vectorlength_metadata (LL_MDRef * loop_md, int vectorlength_factor, int scalable) static
Constructs needed vectorlength nodes.
Definition at line 1452 of file cgmain.cpp.
References cons_vectorize_metadata(), cons_vectorlength_scalable_metadata(), cpu_llvm_module, ll_extend_md_node(), ll_get_md_i32(), ll_get_md_node(), ll_get_md_string(), and LL_PlainMDNode.
Referenced by schedule().
convert_float_size()
static OPERAND * convert_float_size (OPERAND * convert_op, LL_Type * rslt_type) static
Definition at line 6572 of file cgmain.cpp.
References ad_instr(), LL_Type_::data_type, DBGDUMPLLTYPE, DBGTRACEIN1, DBGTRACEOUT1, gen_instr(), I_FPEXT, I_FPTRUNC, OPERAND::ll_type, LL_VECTOR, make_tmp_op(), make_tmps(), OPERAND::next, NULL, and LL_Type_::sub_types.
Referenced by convert_mismatched_types(), and gen_convert_vector().
convert_float_to_sint()
static INLINE OPERAND * convert_float_to_sint (OPERAND * convert_op, LL_Type * rslt_type) static
Definition at line 3718 of file cgmain.cpp.
References convert_operand(), and I_FPTOSI.
Referenced by convert_mismatched_types(), and gen_convert_vector().
convert_float_to_uint()
static INLINE OPERAND * convert_float_to_uint (OPERAND * convert_op, LL_Type * rslt_type) static
Definition at line 3730 of file cgmain.cpp.
References convert_operand(), and I_FPTOUI.
Referenced by gen_convert_vector().
convert_int_size()
static OPERAND * convert_int_size (int ilix, OPERAND * convert_op, LL_Type * rslt_type) static
return new operand of type OT_TMP as result of converting convert_op, which is an int but needs coercion to the int size within rslt_type. If the passed operand convert_op has a next pointer, make sure it is handled BEFORE this call!
Definition at line 6610 of file cgmain.cpp.
References ad_csed_instr(), assert, BITS_IN_BYTE, LL_Type_::data_type, DBGDUMPLLTYPE, DBGTRACE, DBGTRACE2, DBGTRACEIN1, DBGTRACEOUT1, ERR_Fatal, OPERAND::flags, I_SEXT, I_TRUNC, I_ZEXT, InstrListFlagsNull, OPERAND::ll_type, ll_type_bytes(), ll_type_int_bits(), LL_VECTOR, llvm_instr_names, make_tmps(), OPF_ZEXT, and LL_Type_::sub_types.
Referenced by convert_mismatched_types(), gen_base_addr_operand(), gen_binary_expr(), gen_convert_vector(), gen_llvm_expr(), make_load(), and make_stmt().
convert_int_to_ptr()
static OPERAND * convert_int_to_ptr (OPERAND * convert_op, LL_Type * rslt_type) static
Definition at line 6704 of file cgmain.cpp.
References assert, BITS_IN_BYTE, convert_operand(), DT_CPTR, ERR_Fatal, I_INTTOPTR, OPERAND::ll_type, ll_type_int_bits(), and size_of().
Referenced by convert_mismatched_types(), gen_base_addr_operand(), and gen_va_arg().
convert_mismatched_types()
static OPERAND * convert_mismatched_types (OPERAND * operand, LL_Type * expected_type, int ilix) static
Definition at line 3742 of file cgmain.cpp.
References assert, convert_float_size(), convert_float_to_sint(), convert_int_size(), convert_int_to_ptr(), convert_ptr_to_int(), convert_sint_to_float(), LL_Type_::data_type, DBGDUMPLLTYPE, ERR_Fatal, LL_PTR, ll_type_bytes(), ll_type_int_bits(), ll_type_is_fp(), LL_X86_FP80, make_bitcast(), and operand.
Referenced by ad_csed_instr(), and gen_llvm_expr().
convert_operand()
static OPERAND * convert_operand (OPERAND * convert_op, LL_Type * rslt_type, LL_InstrName convert_instruction) static
Definition at line 6680 of file cgmain.cpp.
References ad_instr(), BITS_IN_BYTE, DBGDUMPLLTYPE, DBGTRACEIN1, DBGTRACEOUT1, gen_instr(), OPERAND::ll_type, ll_type_bytes(), make_tmp_op(), make_tmps(), and size.
Referenced by convert_float_to_sint(), convert_float_to_uint(), convert_int_to_ptr(), convert_ptr_to_int(), convert_sint_to_float(), convert_uint_to_float(), gen_bitcast_vector(), process_formal_arguments(), sign_extend_int(), and zero_extend_int().
convert_ptr_to_int()
static INLINE OPERAND * convert_ptr_to_int (OPERAND * convert_op, LL_Type * rslt_type) static
Definition at line 3736 of file cgmain.cpp.
References convert_operand(), and I_PTRTOINT.
Referenced by convert_mismatched_types(), gen_base_addr_operand(), and gen_llvm_expr().
convert_sint_to_float()
static INLINE OPERAND * convert_sint_to_float (OPERAND * convert_op, LL_Type * rslt_type) static
Definition at line 3712 of file cgmain.cpp.
References convert_operand(), and I_SITOFP.
Referenced by convert_mismatched_types(), and gen_convert_vector().
convert_to_llvm_cc()
static int convert_to_llvm_cc (CC_RELATION cc, int cc_type) static
Definition at line 10785 of file cgmain.cpp.
References CMP_INT, CMP_USG, convert_to_llvm_fltcc(), convert_to_llvm_intcc(), convert_to_llvm_uintcc(), fnegcc, and IEEE_CMP.
Referenced by gen_optext_comp_operand(), and gen_vect_compare_operand().
convert_to_llvm_fltcc()
static LLFloatingPointConditionCodes convert_to_llvm_fltcc (CC_RELATION cc) static
Definition at line 10383 of file cgmain.cpp.
References assert, CC_EQ, CC_GE, CC_GT, CC_LE, CC_LT, CC_NE, CC_NOTEQ, CC_NOTGE, CC_NOTGT, CC_NOTLE, CC_NOTLT, CC_NOTNE, ERR_Fatal, LLCCF_NONE, LLCCF_OEQ, LLCCF_OGE, LLCCF_OGT, LLCCF_OLE, LLCCF_OLT, LLCCF_UGE, LLCCF_UGT, LLCCF_ULE, LLCCF_ULT, and LLCCF_UNE.
Referenced by convert_to_llvm_cc(), gen_abs_expr(), gen_llvm_expr(), and gen_minmax_expr().
convert_to_llvm_intcc()
static LLIntegerConditionCodes convert_to_llvm_intcc (CC_RELATION cc) static
Definition at line 10339 of file cgmain.cpp.
References assert, CC_EQ, CC_GE, CC_GT, CC_LE, CC_LT, CC_NE, CC_NOTEQ, CC_NOTGE, CC_NOTGT, CC_NOTLE, CC_NOTLT, CC_NOTNE, ERR_Fatal, LLCC_EQ, LLCC_NE, LLCC_NONE, LLCC_SGE, LLCC_SGT, LLCC_SLE, and LLCC_SLT.
Referenced by convert_to_llvm_cc(), gen_abs_expr(), gen_llvm_expr(), gen_minmax_expr(), and insert_jump_entry_instr().
convert_to_llvm_uintcc()
static LLIntegerConditionCodes convert_to_llvm_uintcc (CC_RELATION cc) static
Definition at line 10361 of file cgmain.cpp.
References assert, CC_EQ, CC_GE, CC_GT, CC_LE, CC_LT, CC_NE, CC_NOTEQ, CC_NOTGE, CC_NOTGT, CC_NOTLE, CC_NOTLT, CC_NOTNE, ERR_Fatal, LLCC_EQ, LLCC_NE, LLCC_NONE, LLCC_UGE, LLCC_UGT, LLCC_ULE, and LLCC_ULT.
Referenced by convert_to_llvm_cc(), gen_llvm_expr(), and gen_minmax_expr().
convert_uint_to_float()
static INLINE OPERAND * convert_uint_to_float (OPERAND * convert_op, LL_Type * rslt_type) static
Definition at line 3724 of file cgmain.cpp.
References convert_operand(), and I_UITOFP.
Referenced by gen_convert_vector().
create_global_initializer()
static void create_global_initializer (GBL_LIST * gitem, const char * flag_str, const char * type_str) static
Definition at line 11165 of file cgmain.cpp.
References AGGREGATE_STYPE, assert, COMPLEX_DTYPE, DTY, ERR_Fatal, getitem(), GBL_TAG::global_def, LLVM_LONGTERM_AREA, NULL, SNAME, sptr, GBL_TAG::sptr, strlen(), TY_ISREAL, and VECTOR_DTYPE.
Referenced by process_extern_variable_sptr(), and process_local_sptr().
currsub_is_sret()
bool currsub_is_sret (void)
...
Definition at line 817 of file cgmain.cpp.
References llvm_tag::abi_info, LL_ABI_HAS_SRET, and llvm_info.
Referenced by get_ftn_dummy_lltype(), and make_stmt().
decimal_value_from_oct()
static int decimal_value_from_oct (int c, int b, int a) static
Definition at line 10936 of file cgmain.cpp.
References a, b, va, and val.
Referenced by process_string().
dont_force_a_dummy_label()
static INLINE int dont_force_a_dummy_label (INSTR_LIST * insn) static
Test for improperly constructed instruction streams.
Parameters
insn The instruction under the cursor
Returns
true iff we don't need to emit a dummy label
Definition at line 2853 of file cgmain.cpp.
References I_BR, INSTR_TAG::i_name, I_NONE, and INSTR_TAG::next.
Referenced by write_instructions().
dtype_struct_name()
const char * dtype_struct_name (DTYPE dtype)
Get string name for a struct type.
...
Parameters
dtype dtype index
Returns
string containing dtype name
Definition at line 11105 of file cgmain.cpp.
References process_dtype_struct().
dump_type_for_debug()
void dump_type_for_debug (LL_Type * ll_type)
...
Definition at line 3589 of file cgmain.cpp.
References ll_dfile, NULL, and LL_Type_::str.
emit_dbg_from_module()
static void emit_dbg_from_module (LL_Module * module) static
Create and append a !dbg info metadata from module.
Parameters
module The module from which to get debug_info
Definition at line 2442 of file cgmain.cpp.
References LL_Module::debug_info, LL_MDREF_IS_NULL, lldbg_cons_line(), and print_dbg_line().
Referenced by write_I_CALL().
exprjump()
static bool exprjump (ILI_OP opc) static
Definition at line 13948 of file cgmain.cpp.
Referenced by make_stmt().
externVarHasDefinition()
static INLINE bool externVarHasDefinition (SPTR sptr) static
Definition at line 11544 of file cgmain.cpp.
References sptr.
Referenced by process_extern_variable_sptr().
externVarMustInitialize()
static INLINE bool externVarMustInitialize (SPTR sptr) static
Definition at line 11550 of file cgmain.cpp.
Referenced by process_extern_variable_sptr().
find_last_executable()
static INLINE INSTR_LIST * find_last_executable (INSTR_LIST * i) static
Definition at line 823 of file cgmain.cpp.
References i, I_NONE, and NULL.
Referenced by schedule().
find_load_cse()
static INLINE OPERAND * find_load_cse (int ilix, OPERAND * load_op, LL_Type * llt) static
Definition at line 6820 of file cgmain.cpp.
References c, can_move_load_up_over_fence(), DEBUG_ASSERT, FLG::depchk, enhanced_conflict(), FAST_CALL, INSTR_TAG::flags, flg, gen_copy_op(), I_ATOMICRMW, I_BR, I_CALL, I_CMPXCHG, I_FENCE, I_INDBR, I_INVOKE, I_LOAD, INSTR_TAG::i_name, I_NONE, I_STORE, IL_TYPE, ILI_OPC, ILI_OPND, ili_opnd(), INSTR_TAG::ilix, ILTY_LOAD, ILTY_STORE, llvm_tag::last_instr, last_instr, OPERAND::ll_type, INSTR_TAG::ll_type, llvm_info, make_tmp_op(), MATCH_OK, match_types(), OPERAND::next, NME_VOL, NOCONFLICT, NULL, INSTR_TAG::operands, INSTR_TAG::prev, SAME, same_op(), STARTEBB, and INSTR_TAG::tmps.
Referenced by make_load().
find_pointer_to_function()
SPTR find_pointer_to_function (int ilix)
Find the (virtual) function pointer in a JSRA call.
Parameters
ilix the first argument of the IL_JSRA
Definition at line 7024 of file cgmain.cpp.
References addr, IL_AADD, ILI_OPC, ILI_OPND, ILI_SymOPND, sptr, SPTR_NULL, and SymConval1.
Referenced by get_call_sptr().
finish_routine()
static INLINE void finish_routine (void) static
Definition at line 1285 of file cgmain.cpp.
References cpu_llvm_module, LL_Module::debug_info, flg, GBL_CURRFUNC, ll_reset_outlined_func(), llassem_end_func, print_line(), and FLG::smp.
Referenced by schedule().
fix_nodepchk_flag()
static INLINE void fix_nodepchk_flag (int bih) static
Definition at line 749 of file cgmain.cpp.
References BIH_NEXT, BIH_NODEPCHK, BIH_NODEPCHK2, and block_branches_to().
Referenced by schedule().
fixup_argument_type()
static INLINE LL_Type * fixup_argument_type (SPTR sptr, LL_Type * type) static
Definition at line 11759 of file cgmain.cpp.
References processAutoSptr_skip(), sptr, and type.
Referenced by formalsAddDebug(), and process_auto_sptr().
fixup_x86_abi_return()
static LL_Type * fixup_x86_abi_return (LL_Type * sig) static
Definition at line 2451 of file cgmain.cpp.
References args, DT_INT, LL_Type_::flags, ll_create_function_type(), LL_TYPE_IS_VARARGS_FUNC, make_lltype_from_dtype(), malloc(), LL_Type_::module, LL_Type_::sub_elements, and LL_Type_::sub_types.
Referenced by maybe_fixup_x86_abi_return(), and write_I_CALL().
fma_mult_has_mult_uses()
static INLINE bool fma_mult_has_mult_uses (OPERAND * multop) static
Does this multiply op have more than one use?
Parameters
multop A multiply operation (unchecked)
Definition at line 6057 of file cgmain.cpp.
References OPERAND::tmps, and TMP_TAG::use_count.
Referenced by maybe_generate_fma().
fma_rewrite()
static void fma_rewrite (INSTR_LIST * isns) static
Find and rewrite any multiply-add opportunities.
Parameters
isns The list of instructions
Definition at line 6211 of file cgmain.cpp.
References maybe_generate_fma(), and p.
Referenced by schedule().
follow_ptr_dtype()
static DTYPE follow_ptr_dtype (DTYPE dtype) static
Definition at line 12001 of file cgmain.cpp.
References DTY, and DTySeqTyElement.
follow_sptr_hashlk()
static int follow_sptr_hashlk (SPTR sptr) static
Definition at line 11985 of file cgmain.cpp.
References get_llvm_name(), name, and sptr.
formalsAddDebug()
static INLINE void formalsAddDebug (SPTR sptr, unsigned i, LL_Type * llType, bool mayHide) static
Helper function: add debug information for formal argument.
Parameters
sptr a symbol
i parameter position
Definition at line 13429 of file cgmain.cpp.
References BIH_FINDEX, cons_expression_metadata_operand(), cpu_llvm_module, current_module, db(), LL_Module::debug_info, fixup_argument_type(), formalsNeedDebugInfo(), gbl, get_param_mdnode(), i, insert_llvm_dbg_declare(), LL_Module::ir, ll_feature_debug_info_ver90, LL_MDREF_IS_NULL, lldbg_emit_param_variable(), NULL, OPF_HIDDEN, OPF_NONE, and sptr.
Referenced by process_formal_arguments().
formalsGetDtype()
static INLINE DTYPE formalsGetDtype (SPTR s) static
Helper function: Get DTYPE of s.
Parameters
s a symbol Fortran requires special handling for ST_PROC.
Definition at line 13396 of file cgmain.cpp.
References s.
Referenced by process_formal_arguments().
formalsMidnumNotDummy()
static INLINE bool formalsMidnumNotDummy (SPTR sptr) static
Helper function: In Fortran, test if MIDNUM is not SC_DUMMY.
Parameters
sptr a symbol
Definition at line 13385 of file cgmain.cpp.
References sptr.
Referenced by process_formal_arguments().
formalsNeedDebugInfo()
static INLINE bool formalsNeedDebugInfo (SPTR sptr) static
Definition at line 13415 of file cgmain.cpp.
References generating_debug_info(), is_ompaccel(), and sptr.
Referenced by formalsAddDebug().
ftn_array_need_debug_info()
bool ftn_array_need_debug_info (SPTR sptr)
Check if sptr is the midnum of an array and the array has descriptor.
Check if sptr is the mindum of an array and the array has descriptor.
Parameters
sptr A symbol
Definition at line 11223 of file cgmain.cpp.
References NOSYM, and sptr.
Referenced by addDebugForLocalVar(), insert_llvm_dbg_declare(), lldbg_create_global_variable_mdnode(), lldbg_emit_global_variable(), lldbg_emit_local_variable(), lldbg_emit_type(), and needDebugInfoFilt().
fused_multiply_add_candidate()
static int fused_multiply_add_candidate (int ilix) static
Is ilix a candidate for translation to FMA?
Parameters
ilix The index of the ILI
Returns
ILI of the multiply operand or 0 if not a candidate
This inspects the operation at ilix to determine if it matches any of the suitable forms for a fused multiply add instruction.
([-] (([-] A) * ([-] B))) + [-] C
where [-] is an optional negation/subraction.
Definition at line 5877 of file cgmain.cpp.
References ILI_OPC, ILI_OPND, and r.
Referenced by maybe_generate_fma().
fused_multiply_add_canonical_form()
static void fused_multiply_add_canonical_form (INSTR_LIST * addInsn, int matches, ILI_OP opc, OPERAND ** l, OPERAND ** r, int * lhs_ili, int * rhs_ili) static
Put the candidate in proper canonical form.
The canonical form is lhs = (a * b), rhs = c, lhs + rhs.
Definition at line 5974 of file cgmain.cpp.
References ad1ili(), ad_instr(), assert, ERR_Fatal, gen_instr(), gen_llvm_expr(), I_FMUL, TMP_TAG::idef, ILI_OPC, ILI_OPND, TMP_TAG::info, OPERAND::ll_type, make_tmp_op(), make_tmps(), n, neg(), OPERAND::next, NULL, INSTR_TAG::operands, r, t, tmp, and OPERAND::tmps.
Referenced by maybe_generate_fma().
gcTempMap()
static void gcTempMap (void) static
Definition at line 431 of file cgmain.cpp.
References TmpsMap::map, NULL, TmpsMap::size, and tempsMap.
Referenced by schedule().
gen_abs_expr()
static OPERAND * gen_abs_expr (int ilix) static
Definition at line 5161 of file cgmain.cpp.
References ad1ili(), ad_icon, ad_instr(), ad_kconi(), assert, OPERAND::cc, CC_LT, convert_to_llvm_fltcc(), convert_to_llvm_intcc(), d, DBGTRACEIN2, DBGTRACEOUT1, DT_DBLE, DT_FLOAT, ERR_Fatal, f, gen_copy_op(), gen_instr(), gen_llvm_expr(), getcon(), I_FCMP, I_ICMP, I_SELECT, IL_INEG, IL_NAME, ILI_OPC, ILI_OPND, interr(), OPERAND::ll_type, make_int_lltype(), make_operand(), make_tmp_op(), make_tmps(), make_type_from_opc(), mftof, OPERAND::next, NULL, operand, INSTR_TAG::operands, OT_CC, OPERAND::ot_type, stb, tmp, OPERAND::tmps, OPERAND::val, and xmdtod().
Referenced by gen_llvm_expr().
gen_acon_expr()
static OPERAND * gen_acon_expr (int ilix, LL_Type * expected_type) static
Generate an OPERAND representing the value of the ACON ilix.
Parameters
ilix An IL_ACON ilix
expected_type The expected type of the result
Returns
an OPERAND
Definition at line 12583 of file cgmain.cpp.
References ACONOFFG, assert, BITS_IN_BYTE, compilingGlobalOrDevice(), CONVAL2G, DT_CPTR, DT_INT, DT_ISINT, DTY, ERR_Fatal, gen_gep_op(), gen_sptr(), hi, idx, ILI_OPC, ILI_SymOPND, ISZ_2_INT64, ISZ_T, lo, make_bitcast(), make_constval_op(), make_int_lltype(), make_lltype_from_dtype(), make_ptr_lltype(), NULL, num, operand, OPF_VOLATILE, process_sptr_offset(), size_of(), sptr, sym_is_refd(), SymConval1, val, and variable_offset_in_aggregate().
Referenced by gen_base_addr_operand().
gen_address_operand()
OPERAND * gen_address_operand (int addr_op, int nme, bool lda, LL_Type * llt_expected, MSZ msz)
Generate an address expression as an operand.
...
Parameters
addr_op ILI of address expression
nme NME value
lda is this an IL_LDA?
llt_expected expected LL_Type
msz memory access size
Definition at line 12473 of file cgmain.cpp.
References addressElementSize, assert, basesym_of(), LL_Type_::data_type, DBGDUMPLLTYPE, DBGTRACE4, DBGTRACEIN2, DBGTRACEOUT, DT_CPTR, ERR_Fatal, flg, gbl, GBL_CURRFUNC, gen_base_addr_operand(), get_csed_operand(), getprint(), IL_AADD, IL_ASUB, IL_NAME, ILI_COUNT, ILI_OPC, ILI_OPND, lda, LL_AddrSp_Default, LL_AddrSp_NVVM_Generic, LL_AddrSp_NVVM_Shared, ll_get_shared_arg(), LL_PTR, LL_STRUCT, ll_type_bytes_unchecked(), LLTYPE, make_lltype_from_dtype(), make_lltype_from_sptr(), make_ptr_lltype(), make_type_from_msz_with_addrspace(), msz, NME_SYM, NULL, operand, SC_AUTO, set_csed_operand(), FLG::smp, sptr, LL_Type_::sub_types, and XBIT.
Referenced by gen_llvm_expr(), and make_stmt().
gen_alloca_call_if_necessary()
static OPERAND * gen_alloca_call_if_necessary (SPTR sptr, int ilix) static
Definition at line 2337 of file cgmain.cpp.
References call_sym_is(), DT_CPTR, DT_INT, gen_llvm_instr(), I_ALLOCA, make_lltype_from_dtype(), NULL, size_of(), and sptr.
Referenced by gen_call_as_llvm_instr(), and make_stmt().
gen_arg_operand()
static OPERAND * gen_arg_operand (LL_ABI_Info * abi, unsigned abi_arg, int arg_ili) static
Definition at line 7196 of file cgmain.cpp.
References align_of(), arg, LL_ABI_Info_::arg, arg_ili, assert, BITS_IN_BYTE, DT_CPTR, DTY, ERR_Fatal, flags, gen_llvm_expr(), gen_load(), get_dtype_from_arg_opc(), IL_RES, ILI_DTyOPND, ILI_OPC, ILI_OPND, ILIA_ISAR, insert_llvm_memcpy(), interr(), LL_ABI_Info_::is_fortran, LL_ABI_Info_::is_iso_c, ldst_instr_flags_from_dtype(), ll_abi_classify_arg_dtype(), ll_abi_complete_arg_info(), LL_ARG_BYVAL, LL_ARG_COERCE, LL_ARG_DIRECT, LL_ARG_INDIRECT, LL_ARG_INDIRECT_BUFFERED, LL_ARG_SIGNEXT, LL_ARG_ZEROEXT, make_arg_tmp(), make_bitcast(), make_lltype_from_abi_arg(), make_lltype_from_dtype(), make_ptr_lltype(), make_var_op(), nargs, operand, OPF_SRARG_TYPE, OPF_SRET_TYPE, size_of(), tmp, and ts.
Referenced by gen_arg_operand_list().
gen_arg_operand_list()
static OPERAND * gen_arg_operand_list (LL_ABI_Info * abi, int arg_ili) static
Definition at line 7405 of file cgmain.cpp.
References arg_ili, gen_arg_operand(), get_next_arg(), ILI_OPC, LL_ABI_Info_::is_varargs, LL_ABI_HAS_SRET, LL_ABI_Info_::missing_prototype, LL_ABI_Info_::nargs, OPERAND::next, and NULL.
Referenced by gen_call_expr().
gen_base_addr_operand()
static OPERAND * gen_base_addr_operand (int ilix, LL_Type * expected_type) static
Definition at line 12742 of file cgmain.cpp.
References ad1ili(), ad2ili(), ad_icon, ad_kconi(), assert, BITS_IN_BYTE, convert_int_size(), convert_int_to_ptr(), convert_ptr_to_int(), LL_Type_::data_type, DBGDUMPLLTYPE, DBGTRACE, DBGTRACEIN2, DBGTRACEOUT4, DT_CPTR, ERR_Fatal, flags, FLANG_FALLTHROUGH, gen_acon_expr(), gen_base_addr_operand(), gen_gep_op(), gen_llvm_expr(), get_csed_operand(), IL_AADD, IL_ASUB, IL_ISUB, IL_NAME, ILI_COUNT, ILI_OPC, ILI_OPND, LL_ARRAY, LL_FLOAT, LL_NOTYPE, LL_PTR, LL_STRUCT, ll_type_bytes(), ll_type_int_bits(), LL_VECTOR, LL_VOID, make_bitcast(), make_constval_op(), make_int_lltype(), make_lltype_from_dtype(), make_ptr_lltype(), maybe_do_gep_folding(), NULL, operand, OPF_NULL_TYPE, OPF_SEXT, OPF_VOLATILE, OPF_ZEXT, OT_CONSTVAL, OT_VAR, set_csed_operand(), setTempMap(), size_of(), strict_match(), LL_Type_::sub_types, and XBIT.
Referenced by gen_address_operand(), gen_base_addr_operand(), gen_llvm_expr(), gen_optext_comp_operand(), make_stmt(), and maybe_do_gep_folding().
gen_binary_expr()
static OPERAND * gen_binary_expr (int ilix, int itype) static
Definition at line 6238 of file cgmain.cpp.
References ad1ili(), ad_csed_instr(), ad_icon, ad_kconi(), assert, convert_int_size(), DBGTRACE1, DBGTRACE2, DBGTRACEIN2, DBGTRACEOUT1, STB::dblm0, DT_DBLE, DT_FLOAT, DT_INT, DTY, DTySeqTyElement, DTyVecLength, ERR_Fatal, flags, STB::fltm0, gen_llvm_expr(), gen_temp_to_vector(), get_vcon_scalar(), get_vconi(), get_vconm0(), get_vector_dtype(), getcon(), IL_IADD, IL_IMUL, IL_INEG, IL_ISLINK, IL_ISUB, IL_NAME, ILI_DTyOPND, ili_get_vect_dtype(), ILI_OPC, ILI_OPND, InstrListFlagsNull, ISZ_2_INT64, ll_get_vector_type(), OPERAND::ll_type, make_int_lltype(), make_lltype_from_dtype(), make_type_from_opc(), make_vtype(), OPERAND::next, NOSIGNEDWRAP, NULL, num, operand, STB::quad0, SPTR_NULL, stb, TY_DBLE, TY_INT8, TY_REAL, and val.
Referenced by gen_binary_vexpr(), and gen_llvm_expr().
gen_binary_vexpr()
static OPERAND * gen_binary_vexpr (int ilix, int itype_int, int itype_uint, int itype_float) static
Definition at line 5837 of file cgmain.cpp.
References assert, DTY, DTySeqTyElement, ERR_Fatal, gen_binary_expr(), ili_get_vect_dtype(), NULL, TY_BINT, TY_DBLE, TY_INT, TY_INT8, TY_LOG, TY_REAL, and TY_SINT.
Referenced by gen_llvm_expr().
gen_bitcast_vector()
static OPERAND * gen_bitcast_vector (int ilix) static
Definition at line 5819 of file cgmain.cpp.
References assert, convert_operand(), LL_Type_::data_type, ERR_Fatal, gen_llvm_expr(), I_BITCAST, ILI_OPND, LL_VECTOR, make_lltype_from_dtype(), and operand.
Referenced by gen_llvm_expr().
gen_call_as_llvm_instr()
OPERAND * gen_call_as_llvm_instr (SPTR sptr, int ilix)
Definition at line 2360 of file cgmain.cpp.
References gen_alloca_call_if_necessary(), gen_unreachable_if_necessary(), NULL, and sptr.
Referenced by gen_llvm_expr().
gen_call_expr()
static OPERAND * gen_call_expr (int ilix, DTYPE ret_dtype, INSTR_LIST * call_instr, int call_sptr) static
Generate LLVM instructions for a call.
Parameters
ilix is the IL_JSR or IL_JSRA instruction representing the call
ret_dtype is the dtype for the return value, or 0 if return unused
call_instr is either a newly allocated I_CALL or NULL; if NULL, a new instruction will be allocated
call_sptr is the sptr of the called function or function pointer, if known
Returns
an OPERAND representing the value returned by the call
Definition at line 7454 of file cgmain.cpp.
References ad_instr(), addr, LL_ABI_Info_::arg, assert, LL_ABI_Info_::call_as_varargs, LL_ABI_Info_::call_conv, CALL_FUNC_PTR_FLAG, CALLCONV_SHIFT, OPERAND::cc, cpu_llvm_module, LL_Type_::data_type, dsize, DTY, ERR_Fatal, LL_ABI_Info_::fast_math, FAST_MATH_FLAG, OPERAND::flags, INSTR_TAG::flags, gen_arg_operand_list(), gen_copy_op(), gen_llvm_expr(), getlab(), I_CALL, I_INVOKE, IL_RES, ILI_ALT, ILI_DTyOPND, ILI_OPC, ILI_OPND, ILI_SymOPND, ili_throw_label(), ILIA_ISAR, interr(), is_256_or_512_bit_math_intrinsic(), LL_ABI_Info_::is_varargs, ldst_instr_flags_from_dtype(), ll_abi_from_call_site(), ll_abi_function_type(), LL_ABI_HAS_SRET, ll_abi_return_type(), OPERAND::ll_type, INSTR_TAG::ll_type, LL_VOID, make_bitcast(), make_function_type_from_args(), make_instr(), make_label_op(), make_lltype_from_abi_arg(), make_operand(), make_ptr_lltype(), make_store(), make_tmp_op(), make_tmps(), make_var_op(), make_void_lltype(), LL_ABI_Info_::missing_prototype, OPERAND::next, NOUNWIND_CALL_FLAG, NULL, INSTR_TAG::operands, OT_LABEL, OPERAND::ot_type, OPERAND::string, LL_Type_::sub_types, INSTR_TAG::tmps, OPERAND::val, XBIT, and zsize_of().
Referenced by gen_llvm_expr(), and make_stmt().
gen_call_llvm_fm_intrinsic()
static OPERAND * gen_call_llvm_fm_intrinsic (const char * fname, OPERAND * params, LL_Type * return_ll_type, INSTR_LIST * Call_Instr, LL_InstrName i_name) static
Definition at line 4730 of file cgmain.cpp.
References FAST_MATH_FLAG, fname, gen_call_llvm_intrinsic_impl(), and params.
Referenced by maybe_generate_fma().
gen_call_llvm_intrinsic()
static OPERAND * gen_call_llvm_intrinsic (const char * fname, OPERAND * params, LL_Type * return_ll_type, INSTR_LIST * Call_Instr, LL_InstrName i_name) static
Definition at line 4721 of file cgmain.cpp.
References fname, gen_call_llvm_intrinsic_impl(), InstrListFlagsNull, and params.
Referenced by gen_llvm_expr().
gen_call_llvm_intrinsic_impl()
static OPERAND * gen_call_llvm_intrinsic_impl (const char * fname, OPERAND * params, LL_Type * return_ll_type, INSTR_LIST * Call_Instr, LL_InstrName i_name, LL_InstrListFlags MathFlag) static
Definition at line 4709 of file cgmain.cpp.
References buf, fname, gen_call_to_builtin(), MAXIDLEN, and params.
Referenced by gen_call_llvm_fm_intrinsic(), gen_call_llvm_intrinsic(), and gen_call_llvm_non_fm_math_intrinsic().
gen_call_llvm_non_fm_math_intrinsic()
static OPERAND * gen_call_llvm_non_fm_math_intrinsic (const char * fname, OPERAND * params, LL_Type * return_ll_type, INSTR_LIST * Call_Instr, LL_InstrName i_name) static
Definition at line 4739 of file cgmain.cpp.
References fname, gen_call_llvm_intrinsic_impl(), InstrListFlagsNull, NSZ_MATH_FLAG, params, REASSOC_MATH_FLAG, and XBIT.
Referenced by maybe_generate_fma().
gen_call_pgocl_intrinsic()
static OPERAND * gen_call_pgocl_intrinsic (const char * fname, OPERAND * params, LL_Type * return_ll_type, INSTR_LIST * Call_Instr, LL_InstrName i_name) static
Definition at line 4753 of file cgmain.cpp.
References buf, fname, gen_call_to_builtin(), InstrListFlagsNull, MAXIDLEN, and params.
Referenced by gen_llvm_expr().
gen_call_to_builtin()
OPERAND * gen_call_to_builtin (int ilix, char * fname, OPERAND * params, LL_Type * return_ll_type, INSTR_LIST * Call_Instr, LL_InstrName i_name, LL_InstrListFlags MathFlag, unsigned flags)
...
Definition at line 4614 of file cgmain.cpp.
References ad_instr(), CALL_INTRINSIC_FLAG, DBGTRACEIN1, DBGTRACEOUT, flags, INSTR_TAG::flags, fname, get_intrinsic_call_ops(), getitem(), TMP_TAG::idef, TMP_TAG::info, INSTR_TAG::ll_type, LLVM_LONGTERM_AREA, make_instr(), make_tmp_op(), make_tmps(), NULL, operand, INSTR_TAG::operands, params, strlen(), and INSTR_TAG::tmps.
Referenced by cleanup_unneeded_sincos_calls(), gen_call_llvm_intrinsic_impl(), gen_call_pgocl_intrinsic(), gen_call_vminmax_intrinsic(), gen_call_vminmax_neon_intrinsic(), gen_call_vminmax_power_intrinsic(), gen_llvm_sincos_call(), and gen_llvm_vsincos_call().
gen_call_vminmax_intrinsic()
static OPERAND * gen_call_vminmax_intrinsic (int ilix, OPERAND * op1, OPERAND * op2) static
Definition at line 2200 of file cgmain.cpp.
References assert, BITS_IN_BYTE, buf, DTY, DTySeqTyElement, DTyVecLength, ERR_Fatal, FLANG_FALLTHROUGH, gen_call_to_builtin(), I_PICALL, ILI_DTyOPND, ILI_OPC, InstrListFlagsNull, make_lltype_from_dtype(), MAXIDLEN, OPERAND::next, NULL, sign, TY_BINT, TY_DBLE, TY_FLOAT, TY_INT, TY_SINT, type, and zsize_of().
Referenced by gen_llvm_expr().
gen_call_vminmax_neon_intrinsic()
static OPERAND * gen_call_vminmax_neon_intrinsic (int ilix, OPERAND * op1, OPERAND * op2) static
Definition at line 2289 of file cgmain.cpp.
References BITS_IN_BYTE, buf, DTY, DTySeqTyElement, DTyVecLength, gen_call_to_builtin(), I_PICALL, ILI_OPC, ILI_OPND, InstrListFlagsNull, make_lltype_from_dtype(), MAXIDLEN, OPERAND::next, NULL, sign, TY_BINT, TY_FLOAT, TY_INT, TY_SINT, type, and zsize_of().
Referenced by gen_llvm_expr().
gen_call_vminmax_power_intrinsic()
static OPERAND * gen_call_vminmax_power_intrinsic (int ilix, OPERAND * op1, OPERAND * op2) static
Definition at line 2253 of file cgmain.cpp.
References BITS_IN_BYTE, buf, DTY, DTySeqTyElement, DTyVecLength, gen_call_to_builtin(), I_PICALL, ILI_DTyOPND, ILI_OPC, InstrListFlagsNull, make_lltype_from_dtype(), MAXIDLEN, OPERAND::next, NULL, TY_DBLE, TY_FLOAT, type, and zsize_of().
Referenced by gen_llvm_expr().
gen_cmplx_math()
static OPERAND * gen_cmplx_math (int ilix, DTYPE dtype, LL_InstrName itype) static
Definition at line 7891 of file cgmain.cpp.
References ad_csed_instr(), assert, DT_CMPLX, DT_DBLE, DT_FLOAT, DT_ISCMPLX, ERR_Fatal, gen_copy_operand(), gen_eval_cmplx_value(), gen_extract_value(), gen_insert_value(), ILI_OPND, InstrListFlagsNull, make_lltype_from_dtype(), make_undef_op(), OPERAND::next, and res.
Referenced by gen_llvm_expr().
gen_cmplx_mul()
static OPERAND * gen_cmplx_mul (int ilix, DTYPE dtype) static
Definition at line 7936 of file cgmain.cpp.
References a, ad_csed_instr(), c, DT_CMPLX, DT_DBLE, DT_FLOAT, gen_copy_operand(), gen_eval_cmplx_value(), gen_extract_value(), gen_insert_value(), I_FADD, I_FMUL, I_FSUB, ILI_OPND, InstrListFlagsNull, make_lltype_from_dtype(), make_undef_op(), OPERAND::next, r4, and res.
Referenced by gen_llvm_expr().
gen_comp_operand()
static INLINE OPERAND * gen_comp_operand (OPERAND * operand, ILI_OP opc, int lhs_ili, int rhs_ili, int cc_ili, int cc_type, LL_InstrName itype) static
Definition at line 8277 of file cgmain.cpp.
References gen_optext_comp_operand(), and operand.
Referenced by gen_llvm_expr().
gen_const_expr()
static OPERAND * gen_const_expr (int ilix, LL_Type * expected_type) static
Definition at line 4991 of file cgmain.cpp.
References assert, CONVAL2G, LL_Type_::data_type, DT_DBLE, DT_FLOAT, DT_INT, ERR_Fatal, ILI_OPC, ILI_SymOPND, interr(), LL_PTR, ll_type_int_bits(), make_lltype_from_dtype(), make_lltype_from_sptr(), make_null_op(), make_operand(), operand, OT_CONSTSPTR, OT_CONSTVAL, and sptr.
Referenced by gen_llvm_expr().
gen_constant()
static char * gen_constant (SPTR sptr, DTYPE tdtype, INT conval0, INT conval1, int flags) static
Definition at line 13015 of file cgmain.cpp.
References assert, b, char_type(), CONVAL2G, cprintf(), d, DBGTRACE1, DBGTRACE2, DBGTRACE3, DBGTRACEIN3, DBGTRACEOUT1, DT_DBLE, DT_INT, DT_LOG, DT_REAL, DTY, ERR_Fatal, flags, FLG_OMIT_OP_TYPE, gen_vconstant(), getitem(), llvm_fc_type(), llvm_info, LLVM_LONGTERM_AREA, MAXIDLEN, NEW, llvm_tag::no_debug_info, NULL, num, repeats_in_binary(), size, sptr, stb, strlen(), tmp, STB::tynames, ui64toax(), xx_u::ww, xdble(), and xdtomd().
Referenced by gen_vconstant().
gen_convert_vector()
static OPERAND * gen_convert_vector (int ilix) static
Definition at line 5713 of file cgmain.cpp.
References assert, convert_float_size(), convert_float_to_sint(), convert_float_to_uint(), convert_int_size(), convert_sint_to_float(), convert_uint_to_float(), LL_Type_::data_type, DT_ISUNSIGNED, ERR_Fatal, gen_llvm_expr(), ILI_DTyOPND, ILI_OPND, LL_DOUBLE, LL_FLOAT, LL_I1, LL_I128, LL_I16, LL_I24, LL_I256, LL_I32, LL_I40, LL_I48, LL_I56, LL_I64, LL_I8, LL_VECTOR, make_lltype_from_dtype(), NULL, operand, OPF_ZEXT, and LL_Type_::sub_types.
Referenced by gen_llvm_expr().
gen_copy_operand()
static OPERAND * gen_copy_operand (OPERAND * opnd) static
Definition at line 7869 of file cgmain.cpp.
References gen_copy_op(), and OPERAND::next.
Referenced by gen_cmplx_math(), gen_cmplx_mul(), and gen_llvm_expr().
gen_eval_cmplx_value()
static OPERAND * gen_eval_cmplx_value (int ilix, DTYPE dtype) static
Definition at line 7856 of file cgmain.cpp.
References gen_llvm_expr(), and make_lltype_from_dtype().
Referenced by gen_cmplx_math(), gen_cmplx_mul(), and gen_llvm_expr().
gen_extract_insert()
TMPS * gen_extract_insert (LL_InstrName i_name, LL_Type * struct_type, TMPS * tmp, LL_Type * tmp_type, TMPS * tmp2, LL_Type * tmp2_type, int index)
...
Definition at line 3605 of file cgmain.cpp.
References ad_instr(), DT_INT, gen_instr(), getcon(), STB::i0, STB::i1, index, OPERAND::ll_type, make_lltype_from_dtype(), make_operand(), make_tmp_op(), make_tmps(), make_undef_op(), OPERAND::next, num, OT_CONSTSPTR, OPERAND::ot_type, OPERAND::sptr, stb, tmp, and OPERAND::val.
gen_extract_value()
static OPERAND * gen_extract_value (OPERAND * aggr, DTYPE aggr_dtype, DTYPE elt_dtype, int idx) static
Definition at line 7848 of file cgmain.cpp.
References gen_extract_value_ll(), idx, and make_lltype_from_dtype().
Referenced by gen_cmplx_math(), gen_cmplx_mul(), and gen_llvm_expr().
gen_extract_value_ll()
static OPERAND * gen_extract_value_ll (OPERAND * aggr, LL_Type * aggr_ty, LL_Type * elt_ty, int idx) static
Definition at line 7837 of file cgmain.cpp.
References ad_instr(), gen_instr(), I_EXTRACTVAL, idx, make_constval32_op(), make_tmp_op(), make_tmps(), OPERAND::next, and res.
Referenced by gen_extract_value(), gen_llvm_cmpxchg_component(), gen_llvm_expr(), gen_llvm_select_sin_or_cos(), and gen_llvm_select_vsincos().
gen_extract_vector()
static OPERAND * gen_extract_vector (OPERAND * vop, int idx) static
Definition at line 5482 of file cgmain.cpp.
References ad_instr(), assert, LL_Type_::data_type, ERR_Fatal, gen_instr(), I_EXTELE, idx, OPERAND::ll_type, LL_VECTOR, make_constval32_op(), make_tmp_op(), make_tmps(), OPERAND::next, operand, and LL_Type_::sub_types.
Referenced by gen_llvm_expr(), and maybe_generate_fma().
gen_gep_index()
static INLINE OPERAND * gen_gep_index (OPERAND * base_op, LL_Type * llt, int index) static
Definition at line 5621 of file cgmain.cpp.
References gen_gep_op(), index, and make_constval32_op().
Referenced by gen_va_arg().
gen_gep_op()
static OPERAND * gen_gep_op (int ilix, OPERAND * base_op, LL_Type * llt, OPERAND * index_op) static
Definition at line 5613 of file cgmain.cpp.
References ad_csed_instr(), I_GEP, InstrListFlagsNull, and OPERAND::next.
Referenced by gen_acon_expr(), gen_base_addr_operand(), gen_gep_index(), and maybe_do_gep_folding().
gen_imask()
static OPERAND * gen_imask (SPTR sptr) static
Definition at line 5438 of file cgmain.cpp.
References DT_INT, DTyVecLength, make_operand(), make_vtype(), operand, OT_CONSTSPTR, and sptr.
Referenced by gen_resized_vect(), and gen_scalar_to_vector_helper().
gen_insert_value()
static OPERAND * gen_insert_value (OPERAND * aggr, OPERAND * elem, unsigned index) static
Generate an insertvalue instruction.
Parameters
aggr an aggregate (destination object)
elem an element (item to be inserted)
index index to insert element
Definition at line 3656 of file cgmain.cpp.
References ad_csed_instr(), I_INSERTVAL, index, InstrListFlagsNull, OPERAND::ll_type, make_constval32_op(), and OPERAND::next.
Referenced by gen_cmplx_math(), gen_cmplx_mul(), and gen_llvm_expr().
gen_insert_vector()
static OPERAND * gen_insert_vector (OPERAND * vop, OPERAND * sop, int idx) static
Definition at line 5459 of file cgmain.cpp.
References ad_instr(), gen_instr(), I_INSELE, idx, OPERAND::ll_type, make_constval32_op(), make_tmp_op(), make_tmps(), OPERAND::next, and operand.
Referenced by gen_scalar_to_vector_helper(), gen_scalar_to_vector_no_shuffle(), and x86_promote_to_vector().
gen_instr()
static INSTR_LIST * gen_instr (LL_InstrName instr_name, TMPS * tmps, LL_Type * ll_type, OPERAND * operands) static
Like make_instr, but also sets tmps, ll_type, and operands.
Definition at line 3697 of file cgmain.cpp.
References TMP_TAG::idef, TMP_TAG::info, INSTR_TAG::ll_type, make_instr(), NULL, INSTR_TAG::operands, and INSTR_TAG::tmps.
Referenced by ad_csed_instr(), convert_float_size(), convert_operand(), fused_multiply_add_canonical_form(), gen_abs_expr(), gen_extract_insert(), gen_extract_value_ll(), gen_extract_vector(), gen_insert_vector(), gen_llvm_expr(), gen_llvm_fence_instruction(), gen_llvm_instr(), gen_minmax_expr(), gen_optext_comp_operand(), gen_resized_vect(), gen_scalar_to_vector_helper(), gen_select_expr(), gen_unreachable_if_necessary(), insert_entry_label(), insert_jump_entry_instr(), make_bitcast(), make_load(), make_stmt(), mk_alloca_instr(), mk_store_instr(), and schedule().
gen_llvm_atomic_intrinsic_for_builtin()
static OPERAND * gen_llvm_atomic_intrinsic_for_builtin (int pdnum, int sptr, int ilix, INSTR_LIST * Call_Instr) static
Definition at line 2133 of file cgmain.cpp.
References ad_icon, arg_ili, assert, cg_get_type(), DTY, DTyReturnType, ERR_Fatal, gen_llvm_atomicrmw_instruction(), gen_llvm_expr(), ILI_OPC, ILI_OPND, make_lltype_from_dtype(), MAXIDLEN, next, NULL, operand, sptr, TY_BINT, TY_INT, TY_INT8, TY_REAL, and TY_SINT.
gen_llvm_atomicrmw_expr()
static OPERAND * gen_llvm_atomicrmw_expr (int ilix) static
Definition at line 7991 of file cgmain.cpp.
References ad_csed_instr(), atomic_info(), flags, gen_llvm_expr(), I_ATOMICRMW, ILI_OPND, info, ll_instr_flags_for_memory_order_and_scope(), ll_instr_flags_from_aop(), make_ptr_lltype(), make_type_from_msz(), OPERAND::next, NME_VOL, result, and VOLATILE_FLAG.
Referenced by gen_llvm_expr().
gen_llvm_atomicrmw_instruction()
static OPERAND * gen_llvm_atomicrmw_instruction (int ilix, int pdnum, OPERAND * params, DTYPE return_dtype) static
Definition at line 4701 of file cgmain.cpp.
References NULL.
Referenced by gen_llvm_atomic_intrinsic_for_builtin().
gen_llvm_cmpxchg()
static INLINE OPERAND * gen_llvm_cmpxchg (int ilix) static
Definition at line 8021 of file cgmain.cpp.
References ad_csed_instr(), atomic_info(), cmpxchg_is_weak(), cmpxchg_loc(), cmpxchg_memory_order(), CMPXCHG_WEAK_FLAG, cpu_llvm_module, flags, gen_llvm_expr(), I_CMPXCHG, ILI_OPND, LL_AddrSp_Default, ll_create_anon_struct_type(), ll_create_basic_type(), LL_I1, ll_instr_flags_for_memory_order_and_scope(), ll_instr_flags_from_memory_order(), make_ptr_lltype(), make_type_from_msz(), msz, ATOMIC_INFO::msz, OPERAND::next, NME_VOL, order, TO_CMPXCHG_MEMORDER_FAIL, and VOLATILE_FLAG.
Referenced by gen_llvm_expr().
gen_llvm_cmpxchg_component()
static OPERAND * gen_llvm_cmpxchg_component (int ilix, int idx) static
Definition at line 8059 of file cgmain.cpp.
References DEBUG_ASSERT, gen_extract_value_ll(), gen_llvm_expr(), idx, ILI_OPND, OPERAND::ll_type, make_constval32_op(), OPERAND::next, NULL, result, and LL_Type_::sub_types.
Referenced by gen_llvm_expr().
gen_llvm_expr()
OPERAND * gen_llvm_expr (int ilix, LL_Type * expected_type)
...
Definition at line 8285 of file cgmain.cpp.
References ad1ili(), ad_csed_instr(), ad_icon, ad_instr(), ad_kconi(), add_to_cselist(), arg, args, asrt, assert, basesym_of(), bits, BITS_IN_BYTE, OPERAND::cc, CC_NE, CMP_FLT, CMP_INT, CMP_USG, complex_result_type(), convert_int_size(), convert_mismatched_types(), convert_ptr_to_int(), convert_to_llvm_fltcc(), convert_to_llvm_intcc(), convert_to_llvm_uintcc(), cpu_llvm_module, llvm_tag::curr_ret_dtype, d, LL_Type_::data_type, DBGDUMPLLTYPE, DBGTRACE1, DBGTRACE2, DBGTRACE3, DBGTRACEIN2, DBGTRACEOUT2, dt, DT_CMPLX, DT_CPTR, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, DT_ISINT, DT_ISUNSIGNED, DT_REAL, DTY, dtype_from_return_type(), DTySeqTyElement, DTyVecLength, ERR_Fatal, ERR_Severe, et, f, flags, OPERAND::flags, FLANG_FALLTHROUGH, gen_abs_expr(), gen_address_operand(), gen_base_addr_operand(), gen_binary_expr(), gen_binary_vexpr(), gen_bitcast_vector(), gen_call_as_llvm_instr(), gen_call_expr(), gen_call_llvm_intrinsic(), gen_call_pgocl_intrinsic(), gen_call_vminmax_intrinsic(), gen_call_vminmax_neon_intrinsic(), gen_call_vminmax_power_intrinsic(), gen_cmplx_math(), gen_cmplx_mul(), gen_comp_operand(), gen_const_expr(), gen_convert_vector(), gen_copy_op(), gen_copy_operand(), gen_eval_cmplx_value(), gen_extract_value(), gen_extract_value_ll(), gen_extract_vector(), gen_insert_value(), gen_instr(), gen_llvm_atomicrmw_expr(), gen_llvm_cmpxchg(), gen_llvm_cmpxchg_component(), gen_llvm_expr(), gen_llvm_select_sin_or_cos(), gen_llvm_select_vsincos(), gen_llvm_sincos_builtin(), gen_llvm_vsincos_builtin(), gen_minmax_expr(), gen_mulh_expr(), gen_optext_comp_operand(), gen_resized_vect(), gen_return_operand(), gen_scalar_to_vector(), gen_scalar_to_vector_no_shuffle(), gen_select_expr(), gen_unary_expr(), gen_va_arg(), gen_vect_compare_operand(), gen_vsincos_return_type(), get_csed_operand(), get_vcon_scalar(), get_vector_dtype(), getcon(), i, I_ADD, I_ALLOCA, I_AND, I_ASHR, I_BITCAST, I_CALL, I_FADD, I_FCMP, I_FDIV, I_FMUL, I_FPEXT, I_FPTOSI, I_FPTOUI, I_FPTRUNC, I_FREM, I_FSUB, I_ICMP, I_LSHR, I_MUL, I_OR, I_PICALL, I_SDIV, I_SELECT, I_SEXT, I_SHL, I_SHUFFVEC, I_SITOFP, I_SREM, I_SUB, I_UDIV, I_UITOFP, I_UREM, I_XOR, IEEE_CMP, IL_AADD, IL_ASUB, IL_HAS_FENCE, IL_IADD, IL_IDIV, IL_IMUL, IL_INEG, IL_ISUB, IL_MOD, IL_NAME, IL_TYPE, ILI_ALT, ILI_ccOPND(), ILI_COUNT, ILI_DTyOPND, ili_get_vect_dtype(), ILI_MSZ_OF_LD, ILI_OPC, ILI_OPND, ILI_SymOPND, ILTY_CONS, ILTY_PROC, InstrListFlagsNull, interr(), is_complex_result(), ldst_instr_flags_from_dtype(), ldst_instr_flags_from_dtype_nme(), LL_ARRAY, ll_create_int_type(), LL_DOUBLE, LL_FLOAT, ll_get_vector_type(), ll_instr_flags_for_memory_order_and_scope(), LL_PTR, OPERAND::ll_type, ll_type_bytes(), ll_type_int_bits(), ll_type_is_fp(), ll_type_is_mem_seq(), LL_VECTOR, LLCCF_OEQ, llvm_info, make_bitcast(), make_constval_op(), make_constval_opL(), make_int_lltype(), make_lltype_from_dtype(), make_load(), make_operand(), make_ptr_lltype(), make_tmp_op(), make_tmps(), make_type_from_opc(), make_undef_op(), make_var_op(), make_void_lltype(), make_vtype(), MATCH_MEM, MATCH_NO, MATCH_OK, match_types(), mftof, msz, msz_dtype(), MSZ_I8, MSZ_ILI_OPND, MSZ_WORD, name, OPERAND::next, NULL, operand, OPF_CONTAINS_UNDEF, OPF_SEXT, OPF_ZEXT, OT_CC, OPERAND::ot_type, q, QTMP_SIZE, res, set_csed_operand(), setTempMap(), sign_extend_int(), sincos_clear_all_args(), sincos_seen(), size_of(), sptr, OPERAND::sptr, SPTR_NULL, OPERAND::sptr_undef, strict_match(), LL_Type_::sub_elements, LL_Type_::sub_types, SYMNAME, t, TARGET_PTRSIZE, tmp, OPERAND::tmps, TY_FLOAT, TY_ISVECT, OPERAND::undef_mask, update_return_type_for_ccfunc(), val, OPERAND::val, VCON_CONVAL, vect_llvm_intrinsic_name(), xmdtod(), xmqtoq(), zero_extend_int(), and zsize_of().
Referenced by attempt_gep_folding(), fused_multiply_add_canonical_form(), gen_abs_expr(), gen_arg_operand(), gen_base_addr_operand(), gen_binary_expr(), gen_bitcast_vector(), gen_call_expr(), gen_convert_vector(), gen_eval_cmplx_value(), gen_llvm_atomic_intrinsic_for_builtin(), gen_llvm_atomicrmw_expr(), gen_llvm_cmpxchg(), gen_llvm_cmpxchg_component(), gen_llvm_expr(), gen_llvm_instr(), gen_llvm_sincos_call(), gen_llvm_vsincos_call(), gen_mulh_expr(), gen_optext_comp_operand(), gen_scalar_to_vector_helper(), gen_scalar_to_vector_no_shuffle(), gen_select_expr(), gen_sret_expr(), gen_switch(), gen_unary_expr(), gen_va_arg(), gen_va_end(), gen_va_start(), gen_vect_compare_operand(), insert_jump_entry_instr(), make_stmt(), and schedule().
gen_llvm_fence_instruction()
static void gen_llvm_fence_instruction (int ilix) static
Definition at line 8012 of file cgmain.cpp.
References ad_instr(), flags, INSTR_TAG::flags, gen_instr(), I_FENCE, ll_instr_flags_for_memory_order_and_scope(), and NULL.
Referenced by schedule().
gen_llvm_instr()
static OPERAND * gen_llvm_instr (int ilix, ILI_OP opc, LL_Type * return_type, LL_Type * param_lltype, LL_InstrName itype) static
Definition at line 2102 of file cgmain.cpp.
References ad_instr(), arg_ili, assert, ERR_Fatal, gen_instr(), gen_llvm_expr(), ILI_OPC, ILI_OPND, make_tmp_op(), make_tmps(), OPERAND::next, NULL, operand, and INSTR_TAG::operands.
Referenced by gen_alloca_call_if_necessary().
gen_llvm_select_sin_or_cos()
static INLINE OPERAND * gen_llvm_select_sin_or_cos (OPERAND * op, LL_Type * argTy, LL_Type * retTy, int component) static
Generate the extractvalue for the sin or cos part.
Definition at line 8089 of file cgmain.cpp.
References add_sincos_map(), gen_extract_value_ll(), TMP_TAG::idef, TMP_TAG::info, SINCOS_COS, SINCOS_EXTRACT, SINCOS_SIN, and OPERAND::tmps.
Referenced by gen_llvm_expr().
gen_llvm_select_vsincos()
static INLINE OPERAND * gen_llvm_select_vsincos (OPERAND * op, LL_Type * argTy, LL_Type * retTy, int component) static
Definition at line 8100 of file cgmain.cpp.
References add_sincos_map(), gen_extract_value_ll(), TMP_TAG::idef, TMP_TAG::info, SINCOS_COS, SINCOS_EXTRACT, SINCOS_SIN, and OPERAND::tmps.
Referenced by gen_llvm_expr().
gen_llvm_sincos_builtin()
static INLINE OPERAND * gen_llvm_sincos_builtin (int ilix) static
Definition at line 8233 of file cgmain.cpp.
References gen_llvm_sincos_call(), get_last_sincos(), and sincos().
Referenced by gen_llvm_expr().
gen_llvm_sincos_call()
static INLINE OPERAND * gen_llvm_sincos_call (int ilix) static
Generate a CALL to sincos, the scalar version.
Definition at line 8137 of file cgmain.cpp.
References add_sincos_imap(), add_sincos_imap_loads(), arg, DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_FLOAT, EXF_PURE, gen_call_to_builtin(), gen_llvm_expr(), hash_functions_direct, hashmap_alloc(), I_CALL, ILI_OPC, ILI_OPND, InstrListFlagsNull, llmk_math_name(), make_lltype_from_dtype(), MTH_sincos, NULL, and sincos_imap.
Referenced by gen_llvm_sincos_builtin().
gen_llvm_vconstant()
char * gen_llvm_vconstant (const char * ctype, int sptr, DTYPE tdtype, int flags)
...
Definition at line 13009 of file cgmain.cpp.
References flags, gen_vconstant(), and sptr.
gen_llvm_vsincos_builtin()
static INLINE OPERAND * gen_llvm_vsincos_builtin (int ilix) static
Definition at line 8240 of file cgmain.cpp.
References gen_llvm_vsincos_call(), and get_last_sincos().
Referenced by gen_llvm_expr().
gen_llvm_vsincos_call()
static INLINE OPERAND * gen_llvm_vsincos_call (int ilix) static
Definition at line 8165 of file cgmain.cpp.
References add_sincos_imap(), add_sincos_imap_loads(), DT_DBLE, DT_FLOAT, DT_INT, EXF_PURE, gen_call_to_builtin(), gen_llvm_expr(), gen_vsincos_return_type(), get_vector_dtype(), hash_functions_direct, hashmap_alloc(), I_CALL, ili_get_vect_arg_count(), ili_get_vect_dtype(), ILI_OPC, ILI_OPND, InstrListFlagsNull, llmk_math_name(), make_lltype_from_dtype(), MTH_sincos, OPERAND::next, NULL, sincos_imap, LL_Type_::sub_elements, and LL_Type_::sub_types.
Referenced by gen_llvm_vsincos_builtin().
gen_load()
static OPERAND * gen_load (OPERAND * addr, LL_Type * type, LL_InstrListFlags flags) static
Insert an LLVM load instruction and return the loaded value.
The address operand must be a pointer type that points to the load type.
The flags provide the alignment and volatility, see ldst_instr_flags_from_dtype().
Definition at line 5698 of file cgmain.cpp.
References ad_csed_instr(), addr, consLoadDebug(), flags, I_LOAD, ld, and type.
Referenced by gen_arg_operand(), gen_return_operand(), gen_va_arg(), insert_jump_entry_instr(), and make_stmt().
gen_minmax_expr()
static OPERAND * gen_minmax_expr (int ilix, OPERAND * op1, OPERAND * op2) static
Definition at line 5257 of file cgmain.cpp.
References ad_instr(), OPERAND::cc, CC_GT, CC_LT, CC_NOTGE, CC_NOTLE, convert_to_llvm_fltcc(), convert_to_llvm_intcc(), convert_to_llvm_uintcc(), DBGTRACEIN2, DBGTRACEOUT1, DT_ISUNSIGNED, DTY, DTySeqTyElement, ERR_Fatal, gen_copy_op(), gen_instr(), I_FCMP, I_ICMP, I_SELECT, IL_NAME, ili_get_vect_dtype(), ILI_OPC, interr(), OPERAND::ll_type, make_int_lltype(), make_lltype_from_dtype(), make_operand(), make_tmp_op(), make_tmps(), make_type_from_opc(), OPERAND::next, NULL, operand, INSTR_TAG::operands, OT_CC, OPERAND::ot_type, LL_Type_::sub_types, OPERAND::tmps, TY_DBLE, TY_FLOAT, and OPERAND::val.
Referenced by gen_llvm_expr().
gen_mulh_expr()
static OPERAND * gen_mulh_expr (int ilix) static
Definition at line 6447 of file cgmain.cpp.
References ad_csed_instr(), bits, ERR_Fatal, gen_llvm_expr(), I_ASHR, I_LSHR, I_MUL, I_SEXT, I_TRUNC, I_ZEXT, ILI_OPC, ILI_OPND, InstrListFlagsNull, interr(), lhs, make_constval_op(), make_int_lltype(), NOSIGNEDWRAP, NOUNSIGNEDWRAP, NULL, and result.
Referenced by gen_llvm_expr().
gen_name_private_sptr()
static void gen_name_private_sptr (SPTR sptr) static
Definition at line 11688 of file cgmain.cpp.
References addDebugForLocalVar(), LL_Object::address, align_of_var(), CHECK, llvm_tag::curr_func, LL_Value::data, get_llvm_name(), ll_create_local_object(), LL_PTR, LLTYPE, llvm_info, SNAME, sptr, and type.
Referenced by process_private_sptr(), and process_sptr_offset().
gen_optext_comp_operand()
static OPERAND * gen_optext_comp_operand (OPERAND * operand, ILI_OP opc, int lhs_ili, int rhs_ili, int cc_ili, int cc_type, LL_InstrName itype, int optext, int ilix) static
Generate comparison operand. Optionally extending the result.
Parameters
optext if this is false, do not extend the result to 32 bits.
Definition at line 10520 of file cgmain.cpp.
References ad_instr(), assert, OPERAND::cc, convert_to_llvm_cc(), DTyVecLength, ERR_Fatal, OPERAND::flags, gen_base_addr_operand(), gen_instr(), gen_llvm_expr(), ILI_DTyOPND, OPERAND::ll_type, make_int_lltype(), make_lltype_from_dtype(), make_operand(), make_tmps(), make_type_from_opc(), make_vector_lltype(), OPERAND::next, operand, INSTR_TAG::operands, OPF_NULL_TYPE, OT_CC, OT_TMP, OPERAND::ot_type, sign_extend_int(), OPERAND::val, XBIT, and zero_extend_int().
Referenced by gen_comp_operand(), and gen_llvm_expr().
gen_resized_vect()
static OPERAND * gen_resized_vect (OPERAND * vop, int new_size, int start) static
Create a new vector.
The new vactor will have the same type as vop with size new_size and filed with values from vop. This is useful for converting 3 element vectors to 4 element vectors and vice-versa.
Let's assume vop is a vector of 4 floats and new_size is 3. This will be expanded into following LLVM instruction:
%0 = shufflevector <4 x float> vop, <4 x float> undef,
          <3 x i32> <i32 0, i32 1, i32 2>
This will build a vector of 3 floats with 3 first elements from vop.
Definition at line 5518 of file cgmain.cpp.
References ad_instr(), assert, BITS_IN_BYTE, LL_Type_::data_type, DT_INT, ERR_Fatal, gen_imask(), gen_instr(), get_vcon(), get_vcon0_n(), get_vector_dtype(), i, I_SHUFFVEC, ll_get_vector_type(), OPERAND::ll_type, ll_type_bytes(), LL_VECTOR, make_operand(), make_tmp_op(), make_tmps(), OPERAND::next, operand, OPERAND::ot_type, OT_UNDEF, start, LL_Type_::sub_types, and TY_VECT_MAXLEN.
Referenced by gen_llvm_expr().
gen_return_operand()
static INLINE OPERAND * gen_return_operand (int ilix) static
Generate a return operand when ILI didn't provide a return value.
LLVM requires a return instruction, even if it is only a "return undef". Also handle the case where we have a special return value symbol but want to return a value in registers.
Definition at line 652 of file cgmain.cpp.
References bindC_function_return_struct_in_registers(), LL_Type_::data_type, DTY, gbl, gen_load(), gen_sptr(), has_multiple_entries(), ILI_OPND, ldst_instr_flags_from_dtype(), OPERAND::ll_type, LL_VOID, llvm_info, make_bitcast(), make_lltype_from_dtype(), make_operand(), make_ptr_lltype(), make_undef_op(), ret_info, llvm_tag::return_ll_type, ret_tag::sret_sptr, TY_CHAR, TY_CMPLX, TY_DCMPLX, TY_NCHAR, and void().
Referenced by gen_llvm_expr().
gen_scalar_to_vector()
static INLINE OPERAND * gen_scalar_to_vector (int ilix, LL_Type * ll_vecttype) static
Definition at line 5587 of file cgmain.cpp.
References gen_scalar_to_vector_helper(), and ILI_OPND.
Referenced by gen_llvm_expr().
gen_scalar_to_vector_helper()
static OPERAND * gen_scalar_to_vector_helper (int ilix, int from_ili, LL_Type * ll_vecttype) static
Definition at line 5555 of file cgmain.cpp.
References ad_instr(), arg, DT_INT, gen_imask(), gen_insert_vector(), gen_instr(), gen_llvm_expr(), get_vcon0(), get_vector_dtype(), I_SHUFFVEC, make_tmp_op(), make_tmps(), make_undef_op(), OPERAND::next, NULL, operand, INSTR_TAG::operands, LL_Type_::sub_elements, and LL_Type_::sub_types.
Referenced by gen_scalar_to_vector(), and gen_temp_to_vector().
gen_scalar_to_vector_no_shuffle()
static OPERAND * gen_scalar_to_vector_no_shuffle (int ilix, LL_Type * ll_vecttype) static
Definition at line 5595 of file cgmain.cpp.
References arg, gen_insert_vector(), gen_llvm_expr(), ILI_OPND, make_undef_op(), operand, and LL_Type_::sub_types.
Referenced by gen_llvm_expr().
gen_select_expr()
static OPERAND * gen_select_expr (int ilix) static
Definition at line 5368 of file cgmain.cpp.
References ad_instr(), assert, DBGTRACE2, DBGTRACEIN2, DBGTRACEOUT1, ERR_Fatal, gen_instr(), gen_llvm_expr(), I_SELECT, IEEE_CMP, IL_NAME, ILI_OPC, ILI_OPND, make_int_lltype(), make_tmp_op(), make_tmps(), make_type_from_opc(), OPERAND::next, NULL, operand, and INSTR_TAG::operands.
Referenced by gen_llvm_expr().
gen_sptr()
static OPERAND * gen_sptr (SPTR sptr) static
Definition at line 12417 of file cgmain.cpp.
References assert, DBGTRACE2, DBGTRACEIN2, DBGTRACEOUT1, ERR_Fatal, FLANG_FALLTHROUGH, OPERAND::ll_type, LLTYPE, make_operand(), OPERAND::ot_type, OT_VAR, process_sptr(), SC_AUTO, SNAME, sptr, OPERAND::sptr, OPERAND::string, SYMNAME, and OPERAND::val.
Referenced by gen_acon_expr(), and gen_return_operand().
gen_sret_expr()
static INLINE OPERAND * gen_sret_expr (int ilix, LL_Type * expected_type) static
Definition at line 3982 of file cgmain.cpp.
References gen_llvm_expr(), ILI_OPND, make_lltype_from_dtype(), make_operand(), NME_SYM, process_sptr(), ret_info, ret_tag::sret_sptr, and value().
Referenced by make_stmt().
gen_switch()
static INSTR_LIST * gen_switch (int ilix) static
Definition at line 10580 of file cgmain.cpp.
References ad_instr(), DEFLABG, ERR_Fatal, gen_llvm_expr(), I_SW, ILI_OPC, ILI_OPND, interr(), label, make_constsptr_op(), make_constval32_op(), make_instr(), make_int_lltype(), make_target_op(), SWEL::next, OPERAND::next, INSTR_TAG::operands, switch_base, val, and value().
Referenced by make_stmt().
gen_temp_to_vector()
static INLINE OPERAND * gen_temp_to_vector (int from_ili, LL_Type * ll_vecttype) static
Definition at line 5606 of file cgmain.cpp.
References gen_scalar_to_vector_helper().
Referenced by gen_binary_expr().
gen_unary_expr()
static OPERAND * gen_unary_expr (int ilix, LL_InstrName itype) static
Definition at line 5066 of file cgmain.cpp.
References ad_csed_instr(), assert, DBGTRACE2, DBGTRACEIN2, DBGTRACEOUT1, DT_DBLE, DT_FLOAT, DT_INT, ERR_Fatal, gen_llvm_expr(), IL_NAME, ILI_OPC, ILI_OPND, InstrListFlagsNull, make_lltype_from_dtype(), make_type_from_opc(), NULL, and operand.
Referenced by gen_llvm_expr().
gen_unreachable_if_necessary()
static OPERAND * gen_unreachable_if_necessary (SPTR sptr, int ilix) static
Definition at line 2350 of file cgmain.cpp.
References ad_instr(), call_sym_is(), gen_instr(), I_UNREACH, make_undef_op(), make_void_lltype(), NULL, and sptr.
Referenced by gen_call_as_llvm_instr(), and make_stmt().
gen_va_arg()
static OPERAND * gen_va_arg (int ilix) static
Expand an IL_VA_ARG instruction.
VA_ARG arlnk dtype The first argument is a pointer to the va_list, the second is the dtype of the argument to be extracted. Produce a pointer where the argument can be loaded.
There are two versions of this function (one for x86-64 and one for non-x86-64).
Definition at line 4447 of file cgmain.cpp.
References ad_csed_instr(), alignment(), convert_int_to_ptr(), DT_CMPLX, DT_CPTR, DT_FLOAT, DTY, flags, gen_copy_op(), gen_gep_index(), gen_llvm_expr(), gen_load(), I_ADD, I_AND, ILI_DTyOPND, ILI_OPND, InstrListFlagsNull, ldst_instr_flags_from_dtype(), make_arg_tmp(), make_bitcast(), make_constval_op(), make_int_lltype(), make_lltype_from_dtype(), make_ptr_lltype(), make_store(), make_var_op(), OPERAND::next, NOUNSIGNEDWRAP, size_of(), and tmp.
Referenced by gen_llvm_expr().
gen_va_end()
static OPERAND * gen_va_end (int ilix) static
Definition at line 4572 of file cgmain.cpp.
References add_external_function_declaration(), arg, assert, DBGTRACEIN1, DBGTRACEOUT1, DT_CPTR, ERR_Fatal, EXF_INTRINSIC, EXFUNC_LIST::flags, EXFUNC_LIST::func_def, gen_llvm_expr(), getitem(), ILI_OPC, ILI_OPND, is_argili_opcode(), OPERAND::ll_type, LLVM_LONGTERM_AREA, make_lltype_from_dtype(), make_operand(), make_void_lltype(), OPERAND::next, OT_CALL, OPERAND::ot_type, OPERAND::string, and strlen().
gen_va_start()
static OPERAND * gen_va_start (int ilix) static
Definition at line 4357 of file cgmain.cpp.
References add_external_function_declaration(), arg, assert, DBGTRACEIN1, DBGTRACEOUT1, DT_CPTR, ERR_Fatal, EXF_INTRINSIC, EXFUNC_LIST::flags, EXFUNC_LIST::func_def, gen_llvm_expr(), getitem(), ILI_OPC, ILI_OPND, is_argili_opcode(), OPERAND::ll_type, LLVM_LONGTERM_AREA, make_lltype_from_dtype(), make_operand(), make_void_lltype(), OPERAND::next, OT_CALL, OPERAND::ot_type, OPERAND::string, and strlen().
gen_vconstant()
static char * gen_vconstant (const char * ctype, int sptr, DTYPE tdtype, int flags) static
Definition at line 12962 of file cgmain.cpp.
References DTY, DTySeqTyElement, DTyVecLength, flags, FLG_OMIT_OP_TYPE, gen_constant(), getitem(), i, LLVM_LONGTERM_AREA, sptr, SPTR_NULL, strlen(), TY_DBLE, TY_INT8, TY_REAL, and VCON_CONVAL.
Referenced by gen_constant(), and gen_llvm_vconstant().
gen_vect_compare_operand()
static OPERAND * gen_vect_compare_operand (int mask_ili) static
Definition at line 10405 of file cgmain.cpp.
References ad_csed_instr(), assert, OPERAND::cc, CMP_FLT, CMP_INT, CMP_USG, convert_to_llvm_cc(), DT_ISINT, DT_ISREAL, DT_ISUNSIGNED, DTySeqTyElement, DTyVecLength, ERR_Fatal, gen_llvm_expr(), I_FCMP, I_ICMP, I_NONE, ILI_ccOPND(), ili_get_vect_dtype(), ILI_OPC, ILI_OPND, InstrListFlagsNull, ll_get_vector_type(), OPERAND::ll_type, make_int_lltype(), make_lltype_from_dtype(), make_operand(), make_tmps(), OPERAND::next, operand, OT_CC, OPERAND::ot_type, OPERAND::tmps, and OPERAND::val.
Referenced by gen_llvm_expr().
gen_vsincos_return_type()
static INLINE LL_Type * gen_vsincos_return_type (LL_Type * vecTy) static
Definition at line 8158 of file cgmain.cpp.
References cpu_llvm_module, LL_AddrSp_Default, and ll_create_anon_struct_type().
Referenced by gen_llvm_expr(), and gen_llvm_vsincos_call().
generating_debug_info()
static INLINE bool generating_debug_info (void) static
Definition at line 11257 of file cgmain.cpp.
References cpu_llvm_module, FLG::debug, LL_Module::debug_info, and flg.
Referenced by formalsNeedDebugInfo(), and need_debug_info().
get_atomic_memory_order_name()
static const char * get_atomic_memory_order_name (int instr_flags) static
Definition at line 4679 of file cgmain.cpp.
References ATOMIC_ACQ_REL_FLAG, ATOMIC_ACQUIRE_FLAG, ATOMIC_MEM_ORD_FLAGS, ATOMIC_MONOTONIC_FLAG, ATOMIC_RELEASE_FLAG, ATOMIC_SEQ_CST_FLAG, ERR_Severe, and interr().
Referenced by write_instructions(), and write_memory_order().
get_atomicrmw_opname()
static const char * get_atomicrmw_opname (LL_InstrListFlags instr_flags) static
Definition at line 4648 of file cgmain.cpp.
References ATOMIC_ADD_FLAG, ATOMIC_AND_FLAG, ATOMIC_MAX_FLAG, ATOMIC_MIN_FLAG, ATOMIC_OR_FLAG, ATOMIC_RMW_OP_FLAGS, ATOMIC_SUB_FLAG, ATOMIC_UMAX_FLAG, ATOMIC_UMIN_FLAG, ATOMIC_XCHG_FLAG, ATOMIC_XOR_FLAG, ERR_Severe, and interr().
Referenced by write_instructions().
get_call_sptr()
static SPTR get_call_sptr (int ilix) static
Definition at line 7051 of file cgmain.cpp.
References addr, assert, DBGTRACE2, DBGTRACEIN2, DBGTRACEOUT1, ERR_Fatal, find_pointer_to_function(), get_call_sptr(), IL_NAME, ILI_OPC, ILI_OPND, ILI_SymOPND, sptr, SPTR_NULL, and SymConval1.
Referenced by get_call_sptr(), and make_stmt().
get_csed_operand()
static OPERAND ** get_csed_operand (int ilix) static
Definition at line 10726 of file cgmain.cpp.
References csedList, DBGDUMPLLTYPE, DBGTRACE1, DBGTRACE3, ILI_ALT, CSED_TAG::ilix, CSED_TAG::next, NULL, CSED_TAG::operand, OTNAMEG, and p.
Referenced by gen_address_operand(), gen_base_addr_operand(), and gen_llvm_expr().
get_intrinsic()
static OPERAND * get_intrinsic (const char * name, LL_Type * func_type, unsigned flags) static
Get an intrinsic function with name and func_type.
Parameters
name The name of the function
func_type The signature of the function
Create an external function declaration if necessary, or verify that the requested function type matches previous uses.
Use this to generate calls to LLVM intrinsics or runtime library functions.
The function name must include the leading '@'. The name string will not be copied.
Definition at line 10881 of file cgmain.cpp.
References assert, llvm_tag::declared_intrinsics, ERR_Fatal, EXF_INTRINSIC, flags, getitem(), hashmap_insert(), hashmap_lookup(), i, OPERAND::ll_type, llvm_info, LLVM_LONGTERM_AREA, make_operand(), make_ptr_lltype(), name, NULL, OT_CALL, OPERAND::ot_type, LL_Type_::str, OPERAND::string, strlen(), LL_Type_::sub_elements, LL_Type_::sub_types, and update_external_function_declarations().
Referenced by get_intrinsic_call_ops().
get_intrinsic_call_ops()
static OPERAND * get_intrinsic_call_ops (const char * name, LL_Type * return_type, OPERAND * args, unsigned flags) static
Prepend the callee to a list of operands for an intrinsic call.
When preparing a call to float @llvm.foo(i32 a, i32 b), pass the a, b operands to get_intrinsic_call_ops("@llvm.foo", float, a_b_ops);
Definition at line 10923 of file cgmain.cpp.
References args, flags, get_intrinsic(), make_function_type_from_args(), name, and OPERAND::next.
Referenced by gen_call_to_builtin().
get_label_name()
const char * get_label_name (int sptr)
...
Definition at line 481 of file cgmain.cpp.
References SNAME, and sptr.
Referenced by make_label_op(), make_target_op(), and process_blockaddr_sptr().
get_last_sincos()
static INLINE OPERAND * get_last_sincos (int ilix) static
Definition at line 8222 of file cgmain.cpp.
References hashmap_lookup(), ILI_OPND, INT2HKEY, NULL, sincos_argument_valid(), and sincos_imap.
Referenced by gen_llvm_sincos_builtin(), and gen_llvm_vsincos_builtin().
get_llvm_sname()
const char * get_llvm_sname (SPTR sptr) static
Definition at line 490 of file cgmain.cpp.
References buf, getitem(), LLVM_LONGTERM_AREA, map_to_llvm_name(), NULL, p, process_sptr(), SNAME, sptr, strlen(), and SYMNAME.
Referenced by build_routine_and_parameter_entries().
get_mac_name()
static const char * get_mac_name (int * swap, int * fneg, int ilix, int matches, int l, int r) static
Get the x86 intrinsic name of the MAC instruction.
Parameters
swap [output] true if caller must swap arguments
fneg [output] true if multiply result is negated
ilix The root of the MAC (must be an ADD or SUB)
l The (original) lhs ili
r The (original) rhs ili
Returns
the name of the intrinsic (sans "llvm." prefix)
Definition at line 5937 of file cgmain.cpp.
References assert, ERR_Fatal, ILI_OPC, and r.
Referenced by maybe_generate_fma().
get_next_arg()
static int get_next_arg (int arg_ili) static
Definition at line 7364 of file cgmain.cpp.
References arg_ili, ERR_Fatal, ILI_OPC, ILI_OPND, and interr().
Referenced by gen_arg_operand_list().
get_omnipotent_pointer()
static LL_MDRef get_omnipotent_pointer (LL_Module * module) static
Create the root and omnipotent pointer nodes of the TBAA tree.
These metadata nodes are unique per LLVM module and should be cached there.
Definition at line 2633 of file cgmain.cpp.
References a, funcId, ll_get_md_i64(), ll_get_md_node(), ll_get_md_string(), LL_MDREF_IS_NULL, LL_PlainMDNode, LL_Module::omnipotentPtr, and LL_Module::unrefPtr.
Referenced by get_tbaa_metadata().
get_parnum()
int get_parnum (SPTR sptr)
Definition at line 14561 of file cgmain.cpp.
References llvm_tag::abi_info, LL_ABI_Info_::arg, llvm_info, LL_ABI_Info_::nargs, sptr, and LL_ABI_ArgInfo_::sptr.
Referenced by lldbg_emit_param_variable(), and lldbg_emit_type().
get_tbaa_metadata()
static LL_MDRef get_tbaa_metadata (LL_Module * module, int ilix, OPERAND * opnd, bool isVol) static
Write TBAA metadata for the address opnd.
Parameters
module The module
opnd a pointer to a typed location
isVol Is this a volatile access?
To do this correctly for C, we have use the effective type.
Definition at line 2790 of file cgmain.cpp.
References a, assert, LL_Type_::data_type, ERR_Fatal, get_omnipotent_pointer(), ll_get_md_i64(), ll_get_md_node(), LL_NOTYPE, LL_PlainMDNode, LL_PTR, OPERAND::ll_type, locset_to_tbaa_info(), and LL_Type_::sub_types.
Referenced by write_tbaa_metadata().
get_vcon0_n()
static SPTR get_vcon0_n (DTYPE dtype, int start, int N) static
Definition at line 5426 of file cgmain.cpp.
References get_vcon(), i, start, and TY_VECT_MAXLEN.
Referenced by gen_resized_vect().
get_vconi()
static int get_vconi (DTYPE dtype, INT value) static
Definition at line 5414 of file cgmain.cpp.
References DTyVecLength, get_vcon(), i, TY_VECT_MAXLEN, and value().
Referenced by gen_binary_expr().
getTempMap()
static TMPS * getTempMap (unsigned ilix) static
Definition at line 439 of file cgmain.cpp.
References TmpsMap::map, NULL, TmpsMap::size, and tempsMap.
Referenced by make_stmt().
have_masked_intrinsic()
static bool have_masked_intrinsic (int ilix) static
Definition at line 7775 of file cgmain.cpp.
References IL_OPRS, ili_get_vect_dtype(), ILI_OPC, and ILI_OPND.
ignore_simd_block()
static INLINE bool ignore_simd_block (int bih) static
Definition at line 1362 of file cgmain.cpp.
References BIH_NOSIMD, and XBIT.
Referenced by schedule().
ILI_ccOPND()
static CC_RELATION ILI_ccOPND (int i, int j) inline static
Definition at line 410 of file cgmain.cpp.
References assert, CC_NOTGT, ERR_Fatal, i, ILI_OPND, j, and result.
Referenced by gen_llvm_expr(), and gen_vect_compare_operand().
insert_entry_label()
static void insert_entry_label (int ilt) static
Definition at line 14225 of file cgmain.cpp.
References ad_instr(), DT_INT, gbl, gen_instr(), get_return_type(), I_NONE, ILI_SymOPND, ilt, ILT_ILIP, llvm_info, make_label_op(), make_lltype_from_dtype(), NULL, llvm_tag::return_ll_type, and sptr.
Referenced by schedule().
insert_jump_entry_instr()
static void insert_jump_entry_instr (int ilt) static
Insert the jump entry instruction.
Insert compare and jump instruction to correct "entry" based on the first argument of the routine.
Definition at line 14176 of file cgmain.cpp.
References ad_icon, ad_instr(), assert, aux, OPERAND::cc, CC_EQ, convert_to_llvm_intcc(), AUX::dpdsc_base, DT_INT, ERR_Fatal, gbl, gen_instr(), gen_llvm_expr(), gen_load(), getlab(), has_multiple_entries(), hashmap_lookup(), llvm_tag::homed_args, I_BR, I_ICMP, I_NONE, INT2HKEY, ldst_instr_flags_from_dtype(), OPERAND::ll_type, llvm_info, make_instr(), make_int_lltype(), make_label_op(), make_lltype_from_dtype(), make_operand(), make_target_op(), make_tmp_op(), make_tmps(), make_type_from_opc(), make_var_op(), master_sptr, OPERAND::next, NOSYM, NULL, operand, INSTR_TAG::operands, OT_CC, OPERAND::ot_type, sptr, val, and OPERAND::val.
Referenced by schedule().
insert_llvm_dbg_declare()
void insert_llvm_dbg_declare (LL_MDRef mdnode, SPTR sptr, LL_Type * llTy, OPERAND * exprMDOp, OperandFlag_t opflag)
Insert @llvm.dbg.declare call for debug.
Parameters
mdnode metadata node
sptr symbol
llTy preferred type of sptr or NULL
Definition at line 4907 of file cgmain.cpp.
References ad_instr(), add_external_function_declaration(), CALL_INTRINSIC_FLAG, cpu_llvm_module, INSTR_TAG::dbg_line_op, LL_Module::debug_info, deref, EXF_INTRINSIC, EXFUNC_LIST::flags, OPERAND::flags, INSTR_TAG::flags, ftn_array_need_debug_info(), EXFUNC_LIST::func_def, getitem(), I_CALL, LL_Module::ir, LL_DW_OP_deref, ll_feature_dbg_declare_needs_expression_md, ll_feature_debug_info_ver90, OPERAND::ll_type, INSTR_TAG::ll_type, lldbg_emit_empty_expression_mdnode(), lldbg_emit_expression_mdnode(), lldbg_encode_expression_arg(), lldbg_get_var_line(), LLVM_LONGTERM_AREA, make_instr(), make_mdref_op(), make_metadata_wrapper_op(), make_operand(), make_void_lltype(), OPERAND::next, INSTR_TAG::operands, OT_CALL, OPERAND::ot_type, sptr, and OPERAND::string.
Referenced by addDebugForLocalVar(), formalsAddDebug(), lldbg_create_deferred_len_string_type_mdnode(), and lldbg_emit_type().
insert_llvm_dbg_value()
void insert_llvm_dbg_value (OPERAND * load, LL_MDRef mdnode, SPTR sptr, LL_Type * type)
Insert @llvm.dbg.value call for debug.
Parameters
OPERAND operand
sptr symbol
llTy preferred type of sptr or NULL
Definition at line 5628 of file cgmain.cpp.
References ad_instr(), add_external_function_declaration(), CALL_INTRINSIC_FLAG, cpu_llvm_module, INSTR_TAG::dbg_line_op, LL_Module::debug_info, EXF_INTRINSIC, EXFUNC_LIST::flags, OPERAND::flags, INSTR_TAG::flags, EXFUNC_LIST::func_def, getitem(), I_CALL, ll_create_int_type(), OPERAND::ll_type, INSTR_TAG::ll_type, lldbg_emit_empty_expression_mdnode(), lldbg_get_var_line(), LLVM_LONGTERM_AREA, load, make_constval_op(), make_instr(), make_mdref_op(), make_operand(), make_void_lltype(), OPERAND::next, INSTR_TAG::operands, OPF_WRAPPED_MD, OT_CALL, OT_MDNODE, OPERAND::ot_type, sptr, OPERAND::string, OPERAND::tmps, type, and OPERAND::val.
Referenced by consLoadDebug(), lldbg_emit_type(), and process_params().
insert_llvm_memcpy()
static void insert_llvm_memcpy (int ilix, int size, OPERAND * dest_op, OPERAND * src_op, int len, int align, int is_volatile) static
Definition at line 4856 of file cgmain.cpp.
References ad_instr(), add_external_function_declaration(), CALL_INTRINSIC_FLAG, DBGTRACEIN, DBGTRACEOUT, EXF_INTRINSIC, EXFUNC_LIST::flags, INSTR_TAG::flags, EXFUNC_LIST::func_def, getitem(), I_CALL, len, OPERAND::ll_type, INSTR_TAG::ll_type, LLVM_LONGTERM_AREA, make_constval32_op(), make_constval_op(), make_instr(), make_int_lltype(), make_operand(), make_void_lltype(), OPERAND::next, INSTR_TAG::operands, OT_CALL, OPERAND::ot_type, size, OPERAND::string, and strlen().
Referenced by gen_arg_operand(), and make_stmt().
insert_llvm_memset()
static void insert_llvm_memset (int ilix, int size, OPERAND * dest_op, int len, int value, int align, int is_volatile) static
Definition at line 4811 of file cgmain.cpp.
References ad_instr(), add_external_function_declaration(), CALL_INTRINSIC_FLAG, DBGTRACEIN, DBGTRACEOUT, EXF_INTRINSIC, EXFUNC_LIST::flags, INSTR_TAG::flags, EXFUNC_LIST::func_def, getitem(), I_CALL, len, OPERAND::ll_type, INSTR_TAG::ll_type, LLVM_LONGTERM_AREA, make_constval32_op(), make_constval_op(), make_instr(), make_int_lltype(), make_operand(), make_void_lltype(), OPERAND::next, INSTR_TAG::operands, OT_CALL, OPERAND::ot_type, size, OPERAND::string, strlen(), and value().
Referenced by make_stmt().
insert_llvm_prefetch()
static void insert_llvm_prefetch (int ilix, OPERAND * dest_op) static
Definition at line 4765 of file cgmain.cpp.
References ad_instr(), add_external_function_declaration(), CALL_INTRINSIC_FLAG, DBGTRACEIN, DBGTRACEOUT, EXF_INTRINSIC, EXFUNC_LIST::flags, INSTR_TAG::flags, fname, EXFUNC_LIST::func_def, getitem(), I_CALL, OPERAND::ll_type, INSTR_TAG::ll_type, LLVM_LONGTERM_AREA, make_constval_op(), make_instr(), make_int_lltype(), make_operand(), make_void_lltype(), OPERAND::next, INSTR_TAG::operands, OT_CALL, OPERAND::ot_type, OPERAND::string, and strlen().
Referenced by schedule().
is_256_or_512_bit_math_intrinsic()
static bool is_256_or_512_bit_math_intrinsic (int sptr) static
Definition at line 7644 of file cgmain.cpp.
References NULL, sptr, and SYMNAME.
Referenced by gen_call_expr().
is_blockaddr_store()
static bool is_blockaddr_store (int ilix, int rhs, int lhs) static
Definition at line 11358 of file cgmain.cpp.
References ad3ili(), ad4ili(), ad_acon(), addnme(), basesym_of(), ili, ILI_OPC, ILI_OPND, ILI_SymOPND, label, lhs, make_stmt(), MSZ_WORD, NT_VAR, process_blockaddr_sptr(), process_sptr(), sptr, SPTR_NULL, STMT_ST, and SymConval1.
Referenced by make_stmt().
is_cg_llvm_init()
bool is_cg_llvm_init (void)
...
Definition at line 14164 of file cgmain.cpp.
is_complex_result()
static INLINE bool is_complex_result (int ilix) static
Definition at line 8247 of file cgmain.cpp.
References ILI_OPC, ILI_OPND, and on_prescan_complex_list().
Referenced by gen_llvm_expr().
is_ompaccel()
static INLINE bool is_ompaccel (SPTR sptr) static
Definition at line 11251 of file cgmain.cpp.
References sptr.
Referenced by formalsNeedDebugInfo(), and need_debug_info().
is_special_return_symbol()
static int is_special_return_symbol (int sptr) static
Definition at line 12370 of file cgmain.cpp.
References ret_info, sptr, and ret_tag::sret_sptr.
Referenced by need_ptr(), and process_auto_sptr().
is_vector_x86_mmx()
bool is_vector_x86_mmx (LL_Type * type)
Definition at line 14542 of file cgmain.cpp.
References LL_PTR, LL_VECTOR, t, and type.
Referenced by add_external_function_declaration().
isNVVM()
static INLINE bool isNVVM (char * fn_name) static
Definition at line 13250 of file cgmain.cpp.
References flg, and FLG::omptarget.
Referenced by write_extern_fndecl().
ll_check_struct_return()
bool ll_check_struct_return (DTYPE dtype)
Check if the TY_STRUCT fits in registers per the ABI.
...
This is a backdoor for the expander to access the LLVM bridge.
Definition at line 531 of file cgmain.cpp.
References cpu_llvm_module, DEBUG_ASSERT, DT_ISCMPLX, DTY, gbl, ll_abi_classify_return_dtype(), ll_abi_for_func_sptr(), and LL_ABI_HAS_SRET.
Referenced by check_struct().
ll_instr_flags_for_memory_order_and_scope()
static LL_InstrListFlags ll_instr_flags_for_memory_order_and_scope (int ilix) static
From an ILI atomic instruction with a fence, get instruction flags for [singlethread] <memory order>.
Definition at line 3924 of file cgmain.cpp.
References atomic_info(), ATOMIC_SINGLETHREAD_FLAG, flags, info, ll_instr_flags_from_memory_order(), memory_order(), and SS_SINGLETHREAD.
Referenced by gen_llvm_atomicrmw_expr(), gen_llvm_cmpxchg(), gen_llvm_expr(), gen_llvm_fence_instruction(), and make_stmt().
ll_instr_flags_from_memory_order()
static LL_InstrListFlags ll_instr_flags_from_memory_order (MEMORY_ORDER mo) static
Definition at line 3895 of file cgmain.cpp.
References assert, ATOMIC_ACQ_REL_FLAG, ATOMIC_ACQUIRE_FLAG, ATOMIC_MONOTONIC_FLAG, ATOMIC_RELEASE_FLAG, ATOMIC_SEQ_CST_FLAG, ERR_Fatal, MO_ACQ_REL, MO_ACQUIRE, MO_CONSUME, MO_RELAXED, MO_RELEASE, and MO_SEQ_CST.
Referenced by gen_llvm_cmpxchg(), and ll_instr_flags_for_memory_order_and_scope().
llvm_add_to_init_list()
static void llvm_add_to_init_list (const char * name, int priority, init_list_t * list) static
Definition at line 14308 of file cgmain.cpp.
References list, llutil_strdup(), malloc(), name, init_node::name, init_node::next, NULL, priority(), and init_node::priority.
Referenced by llvm_ctor_add(), llvm_ctor_add_with_priority(), llvm_dtor_add(), and llvm_dtor_add_with_priority().
llvm_ctor_add()
void llvm_ctor_add (const char * name)
...
Definition at line 14329 of file cgmain.cpp.
References llvm_add_to_init_list(), llvm_ctor_list, and name.
Referenced by add_ctor(), and add_init_routine().
llvm_ctor_add_with_priority()
void llvm_ctor_add_with_priority (const char * name, int priority)
...
Definition at line 14335 of file cgmain.cpp.
References llvm_add_to_init_list(), llvm_ctor_list, name, and priority().
Referenced by build_routine_and_parameter_entries().
llvm_dtor_add()
void llvm_dtor_add (const char * name)
...
Definition at line 14341 of file cgmain.cpp.
References llvm_add_to_init_list(), llvm_dtor_list, and name.
llvm_dtor_add_with_priority()
void llvm_dtor_add_with_priority (const char * name, int priority)
...
Definition at line 14347 of file cgmain.cpp.
References llvm_add_to_init_list(), llvm_dtor_list, name, and priority().
Referenced by build_routine_and_parameter_entries().
llvm_info_last_instr()
INSTR_LIST * llvm_info_last_instr (void)
...
Definition at line 520 of file cgmain.cpp.
References llvm_tag::last_instr, and llvm_info.
llvm_write_ctor_dtor_list()
static void llvm_write_ctor_dtor_list (init_list_t * list, const char * global_name) static
Definition at line 14353 of file cgmain.cpp.
References current_module, LL_Module::ir, list, ll_feature_three_argument_ctor_and_dtor, init_node::name, init_node::next, NULL, print_nl(), print_token(), and init_node::priority.
Referenced by llvm_write_ctors().
llvm_write_ctors()
void llvm_write_ctors (void)
...
Definition at line 14400 of file cgmain.cpp.
References llvm_ctor_list, llvm_dtor_list, and llvm_write_ctor_dtor_list().
Referenced by assemble_end().
llvmResetSname()
void llvmResetSname (int sptr)
Clear SNAME for sptr.
...
Parameters
sptr the symbol Used by auto parallel in C when the optimizer uses the same compiler generated variable across loops
Definition at line 811 of file cgmain.cpp.
References NULL, SNAME, and sptr.
Referenced by processOutlinedByConcur().
locset_to_tbaa_info()
static LL_MDRef locset_to_tbaa_info (LL_Module * module, LL_MDRef omniPtr, int ilix) static
Fortran location set to "TBAA" translation.
In Fortran, there isn't any TBAA. But we use the LLVM mechanism to hint to the backend what may alias.
Definition at line 2706 of file cgmain.cpp.
References a, assumeWillAlias(), base, basenme_of(), DEBUG_ASSERT, DTY, funcId, IL_TYPE, ILI_OPC, ILI_OPND, ILTY_LOAD, ll_get_md_i64(), ll_get_md_node(), ll_get_md_string(), LL_MDREF_ctor, LL_PlainMDNode, name, NME_SYM, SOC_NEXT, SYMNAME, and LL_Module::unrefPtr.
Referenced by get_tbaa_metadata().
make_arg_tmp()
static SPTR make_arg_tmp (int ilix, DTYPE dtype) static
Create a variable of type dtype.
Parameters
ilix
dtype
Returns
an sptr to the newly created instance.
Definition at line 4406 of file cgmain.cpp.
References align_bytes2power(), align_of(), DTY, NEWSYM, PDALNP, putsname(), SC_AUTO, strlen(), and tmp.
Referenced by gen_arg_operand(), and gen_va_arg().
make_bitcast()
static OPERAND * make_bitcast (OPERAND * cast_op, LL_Type * rslt_type) static
return new operand of type OT_TMP as result of converting cast_op. If cast_op has a next, make sure the next pointer is dealt with properly BEFORE the call to make_bitcast().
Definition at line 6498 of file cgmain.cpp.
References ad_instr(), assert, LL_Type_::data_type, DBGDUMPLLTYPE, DBGTRACEIN1, DBGTRACEOUT1, ERR_Fatal, INSTR_TAG::flags, FLANG_FALLTHROUGH, gen_copy_op(), gen_instr(), I_BITCAST, I_BR, I_INDBR, INSTR_TAG::i_name, I_NONE, TMP_TAG::idef, TMP_TAG::info, llvm_tag::last_instr, LL_PTR, OPERAND::ll_type, INSTR_TAG::ll_type, ll_type_bytes(), llvm_info, make_tmp_op(), make_tmps(), OPERAND::next, NULL, operand, INSTR_TAG::operands, OT_TMP, OPERAND::ot_type, INSTR_TAG::prev, same_op(), STARTEBB, strict_match(), OPERAND::tmps, and INSTR_TAG::tmps.
Referenced by convert_mismatched_types(), gen_acon_expr(), gen_arg_operand(), gen_base_addr_operand(), gen_call_expr(), gen_llvm_expr(), gen_return_operand(), gen_va_arg(), make_stmt(), and process_formal_arguments().
make_function_type_from_args()
static LL_Type * make_function_type_from_args (LL_Type * return_type, OPERAND * first_arg_op, bool is_varargs) static
Create a function type from a return type and an argument list.
Definition at line 7162 of file cgmain.cpp.
References cpu_llvm_module, i, ll_create_function_type(), OPERAND::ll_type, nargs, and OPERAND::next.
Referenced by gen_call_expr(), and get_intrinsic_call_ops().
make_instr()
static INSTR_LIST * make_instr (LL_InstrName instr_name) static
Construct an INSTR_LIST object.
Initializes fields i_name (and dbg_line_op if appropriate). Zeros the other fields.
Definition at line 3671 of file cgmain.cpp.
References cpu_llvm_module, INSTR_TAG::dbg_line_op, FLG::debug, LL_Module::debug_info, flg, getitem(), I_CATCH, I_CLEANUP, I_DECL, INSTR_TAG::i_name, I_NONE, lldbg_get_line(), LLVM_LONGTERM_AREA, and XBIT.
Referenced by gen_call_expr(), gen_call_to_builtin(), gen_instr(), gen_switch(), insert_jump_entry_instr(), insert_llvm_dbg_declare(), insert_llvm_dbg_value(), insert_llvm_memcpy(), insert_llvm_memset(), insert_llvm_prefetch(), and make_stmt().
make_load()
static OPERAND * make_load (int ilix, OPERAND * load_op, LL_Type * rslt_type, MSZ msz, unsigned flags) static
return new operand of type OT_TMP as result of loading load_op
If load_op has a next, make sure the next pointer is dealt with properly BEFORE the call to make_load().
flags is the instruction flags to set. Should usually be ldst_instr_flags_from_dtype() for natural alignment.
Definition at line 6932 of file cgmain.cpp.
References ad_instr(), assert, bits, cons_vec_always_metadata(), consLoadDebug(), convert_int_size(), LL_Type_::data_type, DBGDUMPLLTYPE, DBGTRACEIN2, DBGTRACEOUT1, ERR_Fatal, find_load_cse(), flags, INSTR_TAG::flags, FLANG_FALLTHROUGH, gen_instr(), I_LOAD, is_omp_atomic_ld(), LDST_HAS_ACCESSGRP_METADATA, LL_PTR, OPERAND::ll_type, ll_type_int_bits(), make_lltype_from_dtype(), make_tmp_op(), make_tmps(), MATCH_OK, match_types(), INSTR_TAG::misc_metadata, msz, MSZ_BYTE, MSZ_SBYTE, MSZ_SHWORD, MSZ_UBYTE, MSZ_UHWORD, OPERAND::next, NULL, operand, OPF_SEXT, OPF_ZEXT, and LL_Type_::sub_types.
Referenced by gen_llvm_expr(), and process_formal_arguments().
make_stmt()
static void make_stmt (STMT_Type stmt_type, int ilix, bool deletable, SPTR next_bih_label, int ilt) static
Definition at line 3993 of file cgmain.cpp.
References llvm_tag::abi_info, ad_instr(), align_of(), alignment(), LL_ABI_Info_::arg, assert, BITS_IN_BYTE, cancel_store(), CONVAL2G, convert_int_size(), llvm_tag::curr_ret_dtype, curr_stmt_type, currsub_is_sret(), LL_Type_::data_type, DBGTRACE1, DBGTRACE2, DBGTRACEIN2, DBGTRACEOUT, DELETABLE, DT_CMPLX, DT_CPTR, DT_DCMPLX, DT_INT, dt_nme(), DTyVecLength, ERR_Fatal, exprjump(), LL_ABI_Info_::extend_abi_return, INSTR_TAG::flags, gbl, gen_address_operand(), gen_alloca_call_if_necessary(), gen_base_addr_operand(), gen_call_expr(), gen_instr(), gen_llvm_expr(), gen_load(), gen_sret_expr(), gen_switch(), gen_unreachable_if_necessary(), get_call_sptr(), getlab(), getTempMap(), has_multiple_entries(), I_BR, I_DECL, I_FCMP, I_ICMP, I_INDBR, I_NONE, I_RET, IL_AADD, IL_ASUB, IL_HAS_FENCE, ili_get_vect_dtype(), ILI_MSZ_OF_ST, ILI_OPC, ILI_OPND, ILI_SymOPND, INSTR_TAG::ilix, ilt, insert_llvm_memcpy(), insert_llvm_memset(), InstrListFlagsNull, Instructions, is_blockaddr_store(), LL_ABI_Info_::is_iso_c, ldst_instr_flags_from_dtype(), LDST_LOGALIGN_MASK, ll_instr_flags_for_memory_order_and_scope(), LL_PTR, LL_STRUCT, OPERAND::ll_type, ll_type_bytes(), ll_type_int_bits(), llvm_info, make_bitcast(), make_instr(), make_int_lltype(), make_label_op(), make_lltype_from_dtype(), make_lltype_sz4v3_from_dtype(), make_ptr_lltype(), make_stmt(), make_target_op(), make_tmp_op(), make_tmps(), make_type_from_msz(), mk_store_instr(), msz, msz_dtype(), OPERAND::next, NME_VOL, NULL, INSTR_TAG::operands, INSTR_TAG::prev, process_sptr(), llvm_tag::return_ll_type, sincos_clear_specific_arg(), sincos_seen(), size_of(), sptr, SPTR_NULL, STMT_BR, STMT_CALL, STMT_DECL, STMT_LABEL, stmt_names, STMT_RET, STMT_SMOVE, STMT_ST, STMT_SZERO, LL_Type_::sub_types, ts, LL_ABI_ArgInfo_::type, update_llvm_sym_arrays(), VOLATILE_FLAG, zerojump(), and zsize_of().
Referenced by is_blockaddr_store(), make_stmt(), and schedule().
make_store()
static INLINE void make_store (OPERAND * sop, OPERAND * address_op, LL_InstrListFlags flags) static
Definition at line 5706 of file cgmain.cpp.
References flags, INSTR_TAG::flags, and mk_store_instr().
Referenced by gen_call_expr(), gen_va_arg(), and process_formal_arguments().
make_type_from_msz()
static LL_Type * make_type_from_msz (MSZ msz) static
Definition at line 12356 of file cgmain.cpp.
References LL_AddrSp_Default, make_type_from_msz_with_addrspace(), and msz.
Referenced by gen_llvm_atomicrmw_expr(), gen_llvm_cmpxchg(), and make_stmt().
make_type_from_msz_with_addrspace()
static LL_Type * make_type_from_msz_with_addrspace (MSZ msz, int addrspace) static
Definition at line 12350 of file cgmain.cpp.
References make_lltype_from_dtype_with_addrspace(), msz, and msz_dtype().
Referenced by gen_address_operand(), and make_type_from_msz().
make_type_from_opc()
static LL_Type * make_type_from_opc (ILI_OP opc) static
Definition at line 12119 of file cgmain.cpp.
References assert, DBGTRACE2, DBGTRACEIN1, DBGTRACEOUT1, DT_CMPLX, DT_CPTR, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, ERR_Fatal, IL_IADD, IL_IDIV, IL_IMUL, IL_INEG, IL_ISUB, IL_MOD, IL_NAME, make_lltype_from_dtype(), and NULL.
Referenced by gen_abs_expr(), gen_binary_expr(), gen_llvm_expr(), gen_minmax_expr(), gen_optext_comp_operand(), gen_select_expr(), gen_unary_expr(), and insert_jump_entry_instr().
make_vtype()
static LL_Type * make_vtype (DTYPE dtype, int sz) static
Definition at line 12362 of file cgmain.cpp.
References get_vector_dtype(), make_lltype_from_dtype(), and sz.
Referenced by gen_binary_expr(), gen_imask(), and gen_llvm_expr().
map_to_llvm_name()
static const char * map_to_llvm_name (const char * function_name) static
Definition at line 459 of file cgmain.cpp.
References NULL.
Referenced by get_llvm_sname(), print_function_signature(), and set_global_sname().
mark_rw_access_grp()
static INLINE void mark_rw_access_grp (int bih) static
Definition at line 783 of file cgmain.cpp.
References BIH_NODEPCHK2, and clear_cached_loop_id_md().
Referenced by schedule().
match_llvm_types()
int match_llvm_types (LL_Type * ty1, LL_Type * ty2)
...
Definition at line 12113 of file cgmain.cpp.
References match_types().
match_names()
const char * match_names (MATCH_Kind match_val)
...
Definition at line 4971 of file cgmain.cpp.
References asrt, getitem(), LLVM_LONGTERM_AREA, MATCH_MEM, MATCH_NO, and MATCH_OK.
Referenced by match_types().
match_types()
static MATCH_Kind match_types (LL_Type * ty1, LL_Type * ty2) static
Does ty2 "match" ty1 or can ty2 be converted to ty1?
Parameters
ty1 the result type
ty2 a type
If ty1 is a ptr and ty2 is not, we have an error. In general, if the nesting level of ty1 is greater than that of ty2, then we have an error.
NB: The original algorithm did NOT enforce the latter condition above. The old algorithm would peel off all outer levels of array types blindly and until a non-array element type is found. This implied that this function would return MATCH_OK when the input types are i32 and [A x [B x [C x [D x i32]]]].
Definition at line 12032 of file cgmain.cpp.
References asrt, assert, BITS_IN_BYTE, LL_Type_::data_type, DBGTRACEIN2, DBGTRACEOUT3, DBGTRACEOUT4, ERR_Fatal, LL_ARRAY, LL_FUNCTION, LL_PTR, LL_STRUCT, ll_type_array_elety(), ll_type_bytes(), ll_type_int_bits(), LL_VOID, MATCH_MEM, match_names(), MATCH_NO, MATCH_OK, match_types(), LL_Type_::str, and LL_Type_::sub_types.
Referenced by find_load_cse(), gen_llvm_expr(), make_load(), match_llvm_types(), match_types(), and write_instructions().
maybe_do_gep_folding()
static OPERAND * maybe_do_gep_folding (int aadd, int idxOp, LL_Type * ty) static
Attempt to convert explicit pointer scaling into GEP.
Parameters
aadd An IL_AADD
idxOp The index expression to be checked
Do not assume idxOp is the same as ILI_OPND(aadd, 2).
Definition at line 12700 of file cgmain.cpp.
References addressElementSize, attempt_gep_folding(), base, DT_CPTR, gen_base_addr_operand(), gen_gep_op(), ILI_OPND, index, ll_get_pointer_type(), make_lltype_from_dtype(), NULL, and TARGET_PTRSIZE.
Referenced by gen_base_addr_operand().
maybe_fixup_x86_abi_return()
LL_Type * maybe_fixup_x86_abi_return (LL_Type * sig)
...
Definition at line 2466 of file cgmain.cpp.
References LL_Type_::data_type, fixup_x86_abi_return(), LL_FUNCTION, ll_get_pointer_type(), LL_I16, LL_PTR, pt, LL_Type_::sub_types, and XBIT.
Referenced by write_instructions(), and write_operand().
maybe_generate_fma()
static void maybe_generate_fma (int ilix, INSTR_LIST * insn) static
Replace add instruction with an FMA when all conditions are met.
Definition at line 6111 of file cgmain.cpp.
References ccff_info(), clear_csed_list(), DBGBIT, DT_DBLE, DT_FLOAT, flg, fma(), fma_mult_has_mult_uses(), fused_multiply_add_candidate(), fused_multiply_add_canonical_form(), gbl, gen_call_llvm_fm_intrinsic(), gen_call_llvm_non_fm_math_intrinsic(), gen_extract_vector(), get_mac_name(), I_PICALL, TMP_TAG::idef, FLG::ieee, if(), ILI_OPC, ILI_OPND, TMP_TAG::info, last, llvm_tag::last_instr, ll_get_vector_type(), llvm_info, make_lltype_from_dtype(), MSGOPT, OPERAND::next, NULL, INSTR_TAG::operands, overwrite_fma_add(), r, t, OPERAND::tmps, TMP_TAG::use_count, x86_promote_to_vector(), and XBIT.
Referenced by fma_rewrite().
mergeDebugTypesForGlobal()
static INLINE LL_Type * mergeDebugTypesForGlobal (const char ** glob, LL_Type * symTy, LL_Type * declTy) static
Fixup debug info types.
The declared type and the type of the symbol may have diverged. We want to use the declared type for debug info so the user sees the expected representation.
Definition at line 11286 of file cgmain.cpp.
References buff, getitem(), LLVM_LONGTERM_AREA, LL_Type_::str, and strlen().
Referenced by addDebugForGlobalVar().
mk_alloca_instr()
OPERAND * mk_alloca_instr (LL_Type * ptrTy)
...
Definition at line 3565 of file cgmain.cpp.
References ad_instr(), gen_instr(), I_ALLOCA, make_tmp_op(), make_tmps(), NULL, and OPERAND::tmps.
mk_store_instr()
INSTR_LIST * mk_store_instr (OPERAND * val, OPERAND * addr)
...
Definition at line 3574 of file cgmain.cpp.
References ad_instr(), addr, cons_vec_always_metadata(), INSTR_TAG::flags, gen_instr(), I_STORE, LDST_HAS_ACCESSGRP_METADATA, INSTR_TAG::misc_metadata, NULL, and val.
Referenced by make_stmt(), and make_store().
msz_dtype()
DTYPE msz_dtype (MSZ msz)
...
Definition at line 2377 of file cgmain.cpp.
References assert, DT_CPTR, DT_DBLE, DT_FLOAT, DT_INT, ERR_Fatal, msz, MSZ_BYTE, MSZ_DFLWORD, MSZ_F16, MSZ_F32, MSZ_FWORD, MSZ_I8, MSZ_PTR, MSZ_SBYTE, MSZ_SHWORD, MSZ_SLWORD, MSZ_SWORD, MSZ_UHWORD, MSZ_ULWORD, and MSZ_UWORD.
Referenced by gen_llvm_expr(), make_stmt(), and make_type_from_msz_with_addrspace().
need_debug_info()
static INLINE bool need_debug_info (SPTR sptr) static
Determine if debug information is needed for a particular symbol.
Parameters
sptr The symbol
Checks debug flags and symbol properties.
Definition at line 11269 of file cgmain.cpp.
References generating_debug_info(), is_ompaccel(), needDebugInfoFilt(), and sptr.
Referenced by addDebugForGlobalVar(), addDebugForLocalVar(), consLoadDebug(), print_function_signature(), and write_function_attributes().
need_ptr()
int need_ptr (int sptr, int sc, DTYPE sdtype)
...
Definition at line 12376 of file cgmain.cpp.
References DTY, is_special_return_symbol(), and sptr.
Referenced by char_type(), make_lltype_from_sptr(), and put_addr().
needDebugInfoFilt()
static INLINE bool needDebugInfoFilt (SPTR sptr) static
Separate symbols that should NOT have debug information.
Parameters
sptr a symbol
Returns
false iff sptr ought NOT to have debug info
Definition at line 11239 of file cgmain.cpp.
References ftn_array_need_debug_info(), is_procedure_ptr(), and sptr.
Referenced by need_debug_info().
on_prescan_complex_list()
static INLINE bool on_prescan_complex_list (int ilix) static
Definition at line 711 of file cgmain.cpp.
References complexResultList, ComplexResultList_t::entries, i, and ComplexResultList_t::list.
Referenced by add_prescan_complex_list(), and is_complex_result().
overwrite_fma_add()
static void overwrite_fma_add (INSTR_LIST * oldAdd, INSTR_LIST * newFma, INSTR_LIST * last) static
Definition at line 6063 of file cgmain.cpp.
References INSTR_TAG::flags, INSTR_TAG::i_name, INSTR_TAG::ilix, last, INSTR_TAG::ll_type, OPERAND::next, INSTR_TAG::next, NULL, INSTR_TAG::operands, prev, INSTR_TAG::prev, INSTR_TAG::rank, start, OPERAND::tmps, and TMP_TAG::use_count.
Referenced by maybe_generate_fma().
pointer_scalar_need_debug_info()
bool pointer_scalar_need_debug_info (SPTR sptr)
Check if sptr is the midnum of a scalar and scalar has POINTER/ALLOCATABLE attribute.
Parameters
sptr A symbol
Definition at line 11207 of file cgmain.cpp.
References NOSYM, and sptr.
Referenced by addDebugForLocalVar(), lldbg_emit_global_variable(), and lldbg_emit_local_variable().
print_arg_attributes()
static void print_arg_attributes (LL_ABI_ArgInfo * arg) static
Write out attributes for a function argument or return value.
Parameters
arg an argument's info record
Definition at line 13689 of file cgmain.cpp.
References arg, ERR_Fatal, interr(), LL_ARG_BYVAL, LL_ARG_COERCE, LL_ARG_DIRECT, LL_ARG_INDIRECT, LL_ARG_INDIRECT_BUFFERED, LL_ARG_SIGNEXT, LL_ARG_ZEROEXT, and print_token().
Referenced by print_function_signature().
print_function_signature()
static void print_function_signature (int func_sptr, const char * fn_name, LL_ABI_Info * abi, bool print_arg_names) static
Print the signature of func_sptr, omitting the leading define/declare, ending after the function attributes.
When print_arg_names is set, also print the names of arguments. (From abi->arg[n].sptr).
fn_name is passed separately from the sptr, since Fortran also calls this routine. In the Fortran case, the sptr will not always be valid, but the LL_FnProto contains a valid fn_name string.
Definition at line 13725 of file cgmain.cpp.
References arg, LL_ABI_Info_::arg, assert, LL_ABI_Info_::call_as_varargs, LL_ABI_Info_::call_conv, DT_INT, ERR_Fatal, LL_ABI_Info_::extend_abi_return, hashmap_lookup(), llvm_tag::homed_args, i, INT2HKEY, LL_ABI_HAS_SRET, ll_abi_use_llvm_varargs(), LL_CallConv_Fast, ll_get_calling_conv_str(), llvm_info, make_lltype_from_dtype(), map_to_llvm_name(), LL_ABI_Info_::nargs, need_comma, need_debug_info(), NOSYM, NULL, print_arg_attributes(), print_space(), print_token(), ret_info, SNAME, SPTR_NULL, ret_tag::sret_sptr, str, LL_Type_::str, OPERAND::string, SYMNAME, LL_ABI_ArgInfo_::type, write_target_features(), write_vscale_range(), and XBIT.
Referenced by build_routine_and_parameter_entries(), and write_extern_fndecl().
print_personality()
void print_personality (void)
...
Definition at line 798 of file cgmain.cpp.
References print_token().
Referenced by write_instructions().
print_tmp_name()
void print_tmp_name (TMPS * t)
...
Definition at line 12926 of file cgmain.cpp.
References expr_id, idx, print_token(), t, and tmp.
Referenced by print_entry_subroutine(), store_return_value_for_entry(), write_I_CALL(), write_instructions(), and write_operand().
process_auto_sptr()
static void process_auto_sptr (SPTR sptr) static
Process an SC_AUTO or SC_REGISTER sptr.
Parameters
sptr A symbol Also initialize SNAME(sptr).
Definition at line 11773 of file cgmain.cpp.
References addDebugForLocalVar(), LL_Object::address, align_of_var(), assert, CHECK, llvm_tag::curr_func, LL_Value::data, ret_tag::emit_sret, ERR_Fatal, fixup_argument_type(), hashmap_lookup(), llvm_tag::homed_args, INT2HKEY, is_special_return_symbol(), ll_create_local_name(), ll_create_local_object(), LL_PTR, LLTYPE, llvm_info, NULL, ret_info, SNAME, sptr, SYMNAME, and type.
Referenced by process_sptr_offset().
process_blockaddr_sptr()
static SPTR process_blockaddr_sptr (int sptr, int label) static
Process block address symbol.
We want to generate something similar to:
  @MAIN_iab = internal global  i8*  blockaddress(@MAIN_, %L.LB1_351)
MAIN_:
   %0 = load i8** @iab2
   store i8* %0, i8** %iab
   ; next instruction is use when branching
   ; indirectbr i8** %iab, [label %the_label]
Definition at line 11401 of file cgmain.cpp.
References add_global_define(), char_type(), DEBUG_ASSERT, DT_CPTR, gbl, get_label_name(), getitem(), getsname(), getsymbol(), GBL_TAG::global_def, label, LLTYPE, LLVM_LONGTERM_AREA, make_lltype_sz4v3_from_sptr(), MXIDLN, NULL, size, SNAME, sptr, GBL_TAG::sptr, strlen(), and SYMNAME.
Referenced by is_blockaddr_store().
process_cmnblk_data()
static void process_cmnblk_data (SPTR sptr, ISZ_T off) static
Definition at line 11321 of file cgmain.cpp.
References LL_Module::common_debug_map, cpu_llvm_module, FLG::debug, LL_Module::debug_info, flg, ll_get_module_debug(), lldbg_emit_common_block_mdnode(), name, new_debug_name(), NULL, scope, sptr, and SYMNAME.
Referenced by process_sptr_offset().
process_extern_function_sptr()
static void process_extern_function_sptr (SPTR sptr) static
Process sptr and initialize SNAME(sptr)
Parameters
sptr an external function
Definition at line 11451 of file cgmain.cpp.
References add_external_function_declaration(), assert, cgmain_init_call(), char_type(), DDTG, DT_INT, DTY, ERR_Fatal, EXF_INTRINSIC, EXF_STRUCT_RETURN, EXF_VARARG, EXFUNC_LIST::flags, FLANG_FALLTHROUGH, EXFUNC_LIST::func_def, FUNCLINEG, gbl, get_llvm_name(), get_return_dtype(), getitem(), LLTYPE, LLVM_LONGTERM_AREA, make_lltype_from_dtype(), make_ptr_lltype(), name, NOSYM, NULL, set_global_sname(), size, SNAME, sptr, EXFUNC_LIST::sptr, SPTR_NULL, strlen(), sym_is_refd(), TY_BINT, TY_CHAR, TY_SINT, and EXFUNC_LIST::use_dtype.
Referenced by process_sptr_offset().
process_extern_variable_sptr()
static void process_extern_variable_sptr (SPTR sptr, ISZ_T off) static
Process extern variable sptr and initialize SNAME(sptr)
Parameters
sptr a symbol
off
Definition at line 11561 of file cgmain.cpp.
References addDebugForGlobalVar(), align_of_var(), GBL_TAG::alignment, char_type(), create_global_initializer(), DEBUG_ASSERT, externVarHasDefinition(), externVarMustInitialize(), get_llvm_name(), getitem(), IS_TLS, LLVM_LONGTERM_AREA, name, off, set_global_sname(), SNAME, sptr, and GBL_TAG::sptr.
Referenced by process_sptr_offset().
process_formal_arguments()
void process_formal_arguments (LL_ABI_Info * abi)
Process the formal arguments to the current function.
...
Generate the required prolog code to home all arguments that need it.
llvm_info.abi_info must be initialized before calling this function.
Populates llvm_info.homed_args, which must be allocated and empty before the call.
Definition at line 13477 of file cgmain.cpp.
References LL_Object::address, arg, LL_ABI_Info_::arg, assert, clen_parent_is_param(), compilingGlobalOrDevice(), convert_operand(), cpu_llvm_module, llvm_tag::curr_func, LL_Value::data, LL_Type_::data_type, ERR_Fatal, LL_Function_::first_local, flags, FLANG_FALLTHROUGH, formalsAddDebug(), formalsGetDtype(), formalsMidnumNotDummy(), get_llvm_name(), hashmap_insert(), llvm_tag::homed_args, i, I_FPTRUNC, I_TRUNC, INT2HKEY, LL_Module::ir, LL_ABI_Info_::is_fortran, LL_ABI_Info_::is_iso_c, LL_Object::kind, LL_Function_::last_local, ldst_instr_flags_from_dtype(), LL_ARG_BYVAL, LL_ARG_COERCE, LL_ARG_DIRECT, LL_ARG_INDIRECT, LL_ARG_INDIRECT_BUFFERED, ll_create_local_name(), ll_create_local_object(), ll_feature_debug_info_ver90, ll_get_pointer_type(), LL_PTR, OPERAND::ll_type, ll_type_bytes(), ll_type_int_bits(), ll_type_is_fp(), llis_dummied_arg(), LLObj_LocalBuffered, LLTYPE, llvm_info, make_bitcast(), make_generic_dummy_lltype(), make_lltype_from_abi_arg(), make_load(), make_operand(), make_store(), make_var_op(), mem_size(), LL_ABI_Info_::nargs, LL_Object::next, NULL, OPERAND::ot_type, OT_VAR, process_sptr(), SNAME, LL_Object::sptr, OPERAND::sptr, OPERAND::string, LL_Type_::sub_types, suffix, SYMNAME, TY_INT, and OPERAND::val.
Referenced by schedule().
process_global_lifetime_debug()
void process_global_lifetime_debug (void)
Process symbols with global lifetime and cons their metadata.
...
Definition at line 14504 of file cgmain.cpp.
References add_debug_cmnblk_variables(), cpu_llvm_module, CUDA_HOST, CUDAG, db(), LL_Module::debug_info, gbl, LL_Module::global_debug_map, hashmap_clear(), lldbg_emit_common_block_mdnode(), lldbg_emit_module_mdnode(), lldbg_reset_module(), NOSYM, RU_BDATA, scope, sptr, and update_llvm_sym_arrays().
Referenced by process_input().
process_label_sptr()
static void process_label_sptr (SPTR sptr) static
Process an SC_NONE sptr.
Parameters
sptr represents a label Also initialize SNAME(sptr).
Definition at line 11825 of file cgmain.cpp.
References assert, ERR_Fatal, NULL, process_label_sptr_c(), SNAME, sptr, and sym_is_refd().
Referenced by process_sptr_offset().
process_label_sptr_c()
static void process_label_sptr_c (SPTR sptr) static
Definition at line 11811 of file cgmain.cpp.
References buf, get_llvm_name(), getitem(), LLVM_LONGTERM_AREA, name, SNAME, sptr, and strlen().
Referenced by process_label_sptr().
process_local_sptr()
static void process_local_sptr (SPTR sptr) static
process an SC_LOCAL sptr and initialize SNAME(sptr)
Parameters
sptr a symbol
Definition at line 11630 of file cgmain.cpp.
References add_global_define(), addDebugForLocalVar(), LL_Object::address, align_of_var(), assert, char_type(), CHECK, create_global_initializer(), llvm_tag::curr_func, LL_Value::data, DBGTRACE2, ERR_Fatal, get_llvm_name(), get_local_overlap_var(), getitem(), ll_create_local_object(), LL_PTR, LLTYPE, llvm_info, LLVM_LONGTERM_AREA, name, NULL, set_global_sname(), set_numbered_global_sname(), SNAME, sptr, GBL_TAG::sptr, sym_is_refd(), SYMNAME, and type.
Referenced by process_sptr_offset().
process_params()
static void process_params (void) static
process debug info of constants with parameter attribute.
Definition at line 1420 of file cgmain.cpp.
References BIH_FINDEX, cpu_llvm_module, LL_Module::debug_info, DTY, gbl, get_symbol_start(), insert_llvm_dbg_value(), ld, lldbg_emit_local_variable(), make_lltype_from_dtype(), make_operand(), OT_MDNODE, should_preserve_param(), smax, sptr, stb, and type.
Referenced by schedule().
process_private_sptr()
static void process_private_sptr (SPTR sptr) static
Definition at line 11711 of file cgmain.cpp.
References assert, ERR_Fatal, gbl, GBL_CURRFUNC, gen_name_private_sptr(), NULL, SNAME, sptr, and sym_is_refd().
Referenced by process_sptr_offset().
process_sptr()
void process_sptr (SPTR sptr)
...
Definition at line 11970 of file cgmain.cpp.
References process_sptr_offset(), sptr, and variable_offset_in_aggregate().
Referenced by analyze_ret_info(), gen_sptr(), gen_sret_expr(), get_ftn_lltype(), get_llvm_sname(), is_blockaddr_store(), make_arg_op(), make_label_op(), make_metadata_wrapper_op(), make_stmt(), make_target_op(), make_var_op(), print_entry_subroutine(), process_formal_arguments(), put_addr(), schedule(), write_comm(), write_layout_desc_entry(), and write_typedescs().
process_sptr_offset()
static void process_sptr_offset (SPTR sptr, ISZ_T off) static
Definition at line 11844 of file cgmain.cpp.
References compilingGlobalOrDevice(), DBGTRACE1, DBGTRACEIN7, DBGTRACEOUT, flg, gbl, GBL_CURRFUNC, gen_name_private_sptr(), get_llvm_name(), getprint(), hashmap_lookup(), llvm_tag::homed_args, INT2HKEY, ll_get_shared_arg(), LLTYPE, llvm_info, make_lltype_from_dtype(), make_lltype_sz4v3_from_sptr(), make_ptr_lltype(), NULL, off, process_auto_sptr(), process_cmnblk_data(), process_extern_function_sptr(), process_extern_variable_sptr(), process_label_sptr(), process_local_sptr(), process_private_sptr(), process_static_sptr(), STB::scnames, set_global_sname(), set_local_sname(), FLG::smp, SNAME, sptr, stb, sym_is_refd(), update_llvm_sym_arrays(), and XBIT.
Referenced by gen_acon_expr(), and process_sptr().
process_static_sptr()
static void process_static_sptr (SPTR sptr, ISZ_T off) static
process SC_STATIC sptr representing a file-local variable
Parameters
sptr A symbol
off offset into a structure (should be >= 0)
Definition at line 11339 of file cgmain.cpp.
References addDebugForGlobalVar(), DEBUG_ASSERT, get_llvm_name(), off, set_global_sname(), SNAME, sptr, and sym_is_refd().
Referenced by process_sptr_offset().
process_string()
static char * process_string (char * name, int pad, int string_length) static
Format a string for LLVM output.
LLVM uses hex ASCII characters in strings in place of escape sequences. So process the string here making all needed replacements.
Definition at line 10954 of file cgmain.cpp.
References count, DBGTRACEIN4, DBGTRACEOUT1, decimal_value_from_oct(), getitem(), i, len, LLVM_LONGTERM_AREA, name, string_length(), strlen(), and value().
processAutoSptr_skip()
static INLINE bool processAutoSptr_skip (SPTR sptr) static
Does this arg's pointer type really need to be dereferenced?
Parameters
sptr The argument
Returns
true iff this argument should NOT use the pointer's base type
Definition at line 11749 of file cgmain.cpp.
References compilingGlobalOrDevice(), and sptr.
Referenced by fixup_argument_type().
processOutlinedByConcur()
static int processOutlinedByConcur (int bih) static
Definition at line 838 of file cgmain.cpp.
References BIH_ILTFIRST, BIH_NEXT, DBGBIT, dump_blocks(), gbl, GBL_CURRFUNC, gtid, ILI_OPC, ILI_SymOPND, ILT_ILIP, ILT_NEXT, ll_get_gtid(), ll_save_gtid_val(), llvmAddConcurEntryBlk(), llvmAddConcurExitBlk(), llvmResetSname(), and SPTR_NULL.
Referenced by schedule().
remove_dead_instrs()
static INLINE void remove_dead_instrs (void) static
Remove all deletable instructions from the instruction list.
Definition at line 1371 of file cgmain.cpp.
References DELETABLE, INSTR_TAG::flags, I_ATOMICRMW, I_CALL, I_INVOKE, INSTR_TAG::i_name, I_STORE, llvm_tag::last_instr, llvm_info, NULL, INSTR_TAG::prev, remove_instr(), INSTR_TAG::tmps, and TMP_TAG::use_count.
Referenced by schedule().
remove_dead_sincos_calls()
static INLINE void remove_dead_sincos_calls (INSTR_LIST * isns) static
Second pass to clean up all the dead sincos callsites.
Parameters
isns The list of instructions
Definition at line 1013 of file cgmain.cpp.
References hashmap_free(), hashmap_lookup(), HKEY2INT, I_CALL, NULL, p, remove_instr(), SINCOS_EXTRACT, sincos_imap, sincos_map, and SINCOS_MASK.
Referenced by schedule().
remove_from_csed_list()
static void remove_from_csed_list (int ili) static
Definition at line 10701 of file cgmain.cpp.
References csedList, DBGTRACE1, i, IL_ISLINK, ili, ILI_COUNT, ILI_OPC, ILI_OPND, ilis, CSED_TAG::ilix, is_cseili_opcode(), CSED_TAG::next, NULL, CSED_TAG::operand, ILIINFO::oprs, and remove_from_csed_list().
Referenced by remove_from_csed_list(), and schedule().
remove_instr()
static INSTR_LIST * remove_instr (INSTR_LIST * instr, bool update_usect_only) static
Definition at line 6732 of file cgmain.cpp.
References assert, ERR_Fatal, Instructions, llvm_tag::last_instr, llvm_info, next, INSTR_TAG::next, operand, INSTR_TAG::operands, OT_TMP, prev, and INSTR_TAG::prev.
Referenced by remove_dead_instrs(), and remove_dead_sincos_calls().
repeats_in_binary()
static bool repeats_in_binary (union xx_u xx) static
Definition at line 12945 of file cgmain.cpp.
References DBGTRACEIN1, DBGTRACEOUT1, xx_u::ff, if(), llvm_info, and llvm_tag::no_debug_info.
Referenced by gen_constant().
reset_expr_id()
void reset_expr_id (void)
...
Definition at line 14236 of file cgmain.cpp.
References expr_id.
Referenced by print_entry_subroutine().
same_op()
static bool same_op (OPERAND * op1, OPERAND * op2) static
Definition at line 6761 of file cgmain.cpp.
References OPERAND::conval, OT_CONSTVAL, OT_TMP, OPERAND::ot_type, OT_VAR, OPERAND::sptr, OPERAND::tmps, and OPERAND::val.
Referenced by ad_csed_instr(), find_load_cse(), and make_bitcast().
schedule()
void schedule (void)
Perform code translation from ILI to LLVM for one routine.
...
Definition at line 1472 of file cgmain.cpp.
References llvm_tag::abi_info, ad_instr(), analyze_ret_info(), assem_data(), assem_end(), assert, assign_fortran_storage_classes(), FLG::autoinline, BIH_CS, BIH_EN, BIH_FINDEX, BIH_HEAD, BIH_ILTFIRST, BIH_ILTLAST, BIH_LABEL, BIH_LAST, BIH_LINENO, BIH_NEXT, BIH_NODEPCHK, BIH_NODEPCHK2, BIH_NOMERGE, BIH_NOSIMD, BIH_NOUNROLL, BIH_PAR, BIH_SIMD, BIH_TAIL, BIH_TASK, BIH_UNROLL, BIH_UNROLL_COUNT, BIH_VECTORLENGTH_ENABLED, BIH_VECTORLENGTH_SCALABLE, build_csed_list(), build_unused_global_define_from_params(), cached_access_group_metadata, CG_cpu_compile, cg_llvm_init(), CG_MEDTERM_AREA, cgmain_init_call(), check_for_loop_directive(), cleanup_unneeded_sincos_calls(), clear_csed_list(), clear_prescan_complex_list(), clear_rw_access_grp(), close_pragma(), cons_loop_id_md(), cons_nounroll_metadata(), cons_novectorize_metadata(), cons_unroll_count_metadata(), cons_unroll_metadata(), cons_vec_always_metadata(), consTempMap(), construct_vectorlength_metadata(), cpu_llvm_module, csedList, llvm_tag::curr_func, llvm_tag::curr_instr, current_module, DBGBIT, DBGTRACE1, FLG::debug, LL_Module::debug_info, FLG::depchk, dmpili(), dmpilt(), DT_CPTR, dumpblocks(), entry_bih, ERR_Fatal, expr_id, find_last_executable(), finish_routine(), first, fix_nodepchk_flag(), FLANG_FALLTHROUGH, flg, fma_rewrite(), freearea(), FTN_HOST_REG, funcHasNoDepChk(), funcId, gbl, GBL_CURRFUNC, gcTempMap(), gen_instr(), gen_llvm_expr(), gen_llvm_fence_instruction(), get_entries_argnum(), get_llvm_version(), get_local_overlap_size(), get_master_sptr(), get_return_type(), gpu_llvm_module, has_multiple_entries(), hashmap_clear(), llvm_tag::homed_args, i, I_NONE, FLG::ieee, ignore_simd_block(), IL_NAME, IL_RES, IL_TYPE, ILI_OPC, ILI_OPND, ILIA_DP, ILIA_SP, ilib, ilis, ilt, ILT_BR, ILT_DELETE, ILT_EX, ILT_ILIP, ILT_LINENO, ILT_NEXT, ILT_ST, ILTY_ARTH, ILTY_CONS, ILTY_DEFINE, ILTY_LOAD, ILTY_MOVE, ILTY_OTHER, ILTY_STORE, FLG::inliner, insert_entry_label(), insert_jump_entry_instr(), insert_llvm_prefetch(), Instructions, is_freeili_opcode(), is_mvili_opcode(), is_rgdfili_opcode(), llvm_tag::last_instr, ll_abi_for_func_sptr(), ll_abi_function_type(), LL_ABI_HAS_SRET, ll_create_device_function_from_type(), ll_create_distinct_md_node(), ll_create_function_from_type(), ll_create_pointer_value_from_type(), ll_destroy_function(), ll_dfile, ll_extend_md_node(), ll_get_md_null, LL_INTERNAL_LINKAGE, LL_MDREF_IS_NULL, LL_NO_LINKAGE, LL_PlainMDNode, ll_proto_add_sptr(), ll_reset_gtid(), LL_Version_3_7, ll_write_local_objects(), lldbg_cleanup_missing_bounds(), lldbg_emit_line(), lldbg_emit_lv_list(), lldbg_emit_subprogram(), lldbg_get_di_routine_idx(), lldbg_get_line(), lldbg_reset_dtype_array(), lldbg_set_func_ptr(), llvm_file(), llvm_info, LOOP_BACKEDGE_FLAG, make_label_op(), make_lltype_from_dtype(), make_stmt(), mark_rw_access_grp(), NULL, LL_Module::omnipotentPtr, FLG::omptarget, open_pragma(), ILIINFO::oprs, FLG::opt, optimize_block(), optype(), INSTR_TAG::prev, print_entry_subroutine(), process_formal_arguments(), process_ll_abi_func_ftn_mod(), process_params(), process_sptr(), processOutlinedByConcur(), redundantLdLdElim(), remove_dead_instrs(), remove_dead_sincos_calls(), remove_from_csed_list(), ret_info, routine_count, sched_instructions(), sincos_clear_all_args(), sincos_seen(), FLG::smp, SNAME, sptr, SPTR_NULL, ret_tag::sret_sptr, stb_process_routine_parameters(), STMT_BR, STMT_CALL, STMT_DECL, STMT_LABEL, STMT_RET, STMT_SMOVE, STMT_ST, STMT_SZERO, store_for_homing(), store_llvm_localfptr(), SYMNAME, undo_recip_div(), void(), widenAddressArith(), write_ftn_typedefs(), write_global_and_static_defines(), write_instructions(), write_libomtparget(), write_local_overlap(), write_routine_definition(), FLG::x, XBIT, XBIT_GENERATE_SCALAR_FMA, and XBIT_NOUNIFORM.
set_csed_operand()
static void set_csed_operand (OPERAND ** csed_operand, OPERAND * operand) static
Definition at line 10671 of file cgmain.cpp.
References DBGTRACE, make_tmp_op(), operand, and OPERAND::tmps.
Referenced by gen_address_operand(), gen_base_addr_operand(), and gen_llvm_expr().
set_global_sname()
static const char * set_global_sname (int sptr, const char * name) static
Definition at line 11117 of file cgmain.cpp.
References buf, getitem(), LLVM_LONGTERM_AREA, map_to_llvm_name(), name, SNAME, sptr, and strlen().
Referenced by process_extern_function_sptr(), process_extern_variable_sptr(), process_local_sptr(), process_sptr_offset(), and process_static_sptr().
set_llvm_sptr_name()
void set_llvm_sptr_name (OPERAND * operand)
...
Definition at line 474 of file cgmain.cpp.
References operand, SNAME, and sptr.
Referenced by make_var_op().
set_local_sname()
static const char * set_local_sname (int sptr, const char * name) static
Definition at line 11145 of file cgmain.cpp.
References buf, getitem(), LLVM_LONGTERM_AREA, name, SNAME, sptr, and strlen().
Referenced by process_sptr_offset().
set_numbered_global_sname()
static const char * set_numbered_global_sname (int sptr, const char * name) static
Definition at line 11132 of file cgmain.cpp.
References buf, getitem(), LLVM_LONGTERM_AREA, name, SNAME, sptr, and strlen().
Referenced by process_local_sptr().
setTempMap()
static void setTempMap (unsigned ilix, OPERAND * op) static
Definition at line 445 of file cgmain.cpp.
References TmpsMap::map, TmpsMap::size, tempsMap, and OPERAND::tmps.
Referenced by gen_base_addr_operand(), and gen_llvm_expr().
should_suppress_debug_loc()
static bool should_suppress_debug_loc (INSTR_LIST * instrs) static
Definition at line 2939 of file cgmain.cpp.
References I_CALL, I_INVOKE, INSTR_TAG::i_name, INSTR_TAG::operands, OT_TMP, OPERAND::ot_type, OT_VAR, INSTR_TAG::prev, OPERAND::string, strlen(), OPERAND::tmps, and INSTR_TAG::tmps.
Referenced by write_instructions().
sign_extend_int()
static OPERAND * sign_extend_int (OPERAND * op, unsigned result_bits) static
Definition at line 6714 of file cgmain.cpp.
References assert, convert_operand(), ERR_Fatal, I_SEXT, OPERAND::ll_type, ll_type_int_bits(), and make_int_lltype().
Referenced by gen_llvm_expr(), and gen_optext_comp_operand().
sincos_argument_valid()
static bool sincos_argument_valid (int ilix) static
Definition at line 8202 of file cgmain.cpp.
References hashmap_lookup(), i, IL_ISLINK, IL_TYPE, ILI_OPC, ILI_OPND, ilis, ILTY_LOAD, INT2HKEY, NULL, ILIINFO::oprs, sincos_argument_valid(), and sincos_imap.
Referenced by get_last_sincos(), and sincos_argument_valid().
sincos_clear_all_args()
static INLINE void sincos_clear_all_args (void) static
Definition at line 1043 of file cgmain.cpp.
References hashmap_clear(), and sincos_imap.
Referenced by gen_llvm_expr(), and schedule().
sincos_clear_arg_helper()
static void sincos_clear_arg_helper (hash_key_t key, hash_data_t data, void * context) static
Remove all loads that correspond to a given NME.
Parameters
key an ILI value
data is NULL for a load
context the NME we want to remove
Definition at line 3963 of file cgmain.cpp.
References hashmap_erase(), HKEY2INT, ILI_OPND, NULL, sincos_imap, and sincos_input_uses().
Referenced by sincos_clear_specific_arg().
sincos_clear_specific_arg()
static INLINE void sincos_clear_specific_arg (int lhs_ili, int nme) static
Definition at line 3975 of file cgmain.cpp.
References hashmap_iterate(), sincos_clear_arg_helper(), and sincos_imap.
Referenced by make_stmt().
sincos_input_uses()
static bool sincos_input_uses (int ilix, int nme) static
Invalidate cached sincos intrinsics on write to input expression.
Definition at line 3938 of file cgmain.cpp.
References i, IL_ISLINK, IL_TYPE, ILI_OPC, ILI_OPND, ilis, ILTY_LOAD, ILIINFO::oprs, and sincos_input_uses().
Referenced by sincos_clear_arg_helper(), and sincos_input_uses().
sincos_seen()
static INLINE bool sincos_seen (void) static
Definition at line 1037 of file cgmain.cpp.
References NULL, and sincos_imap.
Referenced by cleanup_unneeded_sincos_calls(), gen_llvm_expr(), make_stmt(), and schedule().
store_for_homing()
static INLINE bool store_for_homing (int rIli, int nme) static
Is the store ILT really a homing store?
Parameters
rIli The value to be stored
nme The NME argument of the store
Definition at line 1112 of file cgmain.cpp.
References bindC_function_return_struct_in_registers(), DTY, gbl, ILI_OPC, ILI_OPND, and NME_SYM.
Referenced by schedule().
store_return_value_for_entry()
static void store_return_value_for_entry (OPERAND * p, int i_name) static
Definition at line 14242 of file cgmain.cpp.
References assert, LL_Type_::data_type, ERR_Fatal, FLG_OMIT_OP_TYPE, get_entret_arg_name(), LL_PTR, llvm_instr_names, make_ptr_lltype(), make_tmps(), p, print_space(), print_tmp_name(), print_token(), write_operand(), and write_type().
Referenced by write_instructions().
strict_match()
bool strict_match (LL_Type * ty1, LL_Type * ty2)
...
Definition at line 12011 of file cgmain.cpp.
Referenced by gen_base_addr_operand(), gen_llvm_expr(), and make_bitcast().
tbaa_disabled()
static INLINE bool tbaa_disabled (void) static
Is TBAA disabled?
Definition at line 2821 of file cgmain.cpp.
References flg, FLG::opt, and XBIT.
Referenced by write_tbaa_metadata().
undo_recip_div()
static void undo_recip_div (INSTR_LIST * isns) static
Undoes the multiply-by-reciprocal transformation.
Parameters
isns The list of instructions
Definition at line 6227 of file cgmain.cpp.
References I_FMUL, maybe_undo_recip_div(), and p.
Referenced by schedule().
update_external_function_declarations()
void update_external_function_declarations (const char * name, char * decl, unsigned flags)
...
Definition at line 10852 of file cgmain.cpp.
References add_external_function_declaration(), flags, EXFUNC_LIST::flags, EXFUNC_LIST::func_def, getitem(), LLVM_LONGTERM_AREA, name, and strlen().
Referenced by get_intrinsic().
update_llvm_sym_arrays()
static void update_llvm_sym_arrays (void) static
Update the shadow symbol arrays.
When adding new symbols or starting a new routine, make sure the shadow symbol arrays and dtype debug array are updated.
Definition at line 14014 of file cgmain.cpp.
References cpu_llvm_module, FLG::debug, LL_Module::debug_info, STB::dt, flg, llvm_tag::last_dtype_avail, lldbg_update_arrays(), llvm_info, MEM_EXTRA, stb, and XBIT.
Referenced by cg_get_type(), cg_llvm_init(), make_stmt(), process_global_lifetime_debug(), and process_sptr_offset().
update_return_type_for_ccfunc()
static void update_return_type_for_ccfunc (int ilix, ILI_OP opc) static
Definition at line 7108 of file cgmain.cpp.
References assert, cg_get_type(), DT_CMPLX, DT_CPTR, DT_DBLE, DT_FLOAT, DT_INT, DTY, DTyParamList, DTySetParamList, ERR_Fatal, ILI_OPND, new_dtype(), and sptr.
Referenced by gen_llvm_expr().
variable_offset_in_aggregate()
static ISZ_T variable_offset_in_aggregate (SPTR sptr, ISZ_T idx) static
Computes byte offset into aggregate structure of sptr.
Parameters
sptr the symbol
idx additional addend to offset
Returns
an offset into a memory object or 0
NB: sym_is_refd() must be called prior to this function in order to return the correct result.
Definition at line 11950 of file cgmain.cpp.
References get_socptr_offset(), idx, and sptr.
Referenced by add_debug_cmnblk_variables(), gen_acon_expr(), and process_sptr().
vect_llvm_intrinsic_name()
static char * vect_llvm_intrinsic_name (int ilix) static
Definition at line 10458 of file cgmain.cpp.
References assert, DT_DBLE, DT_FLOAT, DTY, DTySeqTyElement, DTyVecLength, ERR_Fatal, getitem(), IL_VECT, ili_get_vect_dtype(), ILI_OPC, LLVM_LONGTERM_AREA, n, NULL, and type.
Referenced by gen_llvm_expr().
write_extern_fndecl()
static void write_extern_fndecl (struct LL_FnProto_ * proto) static
Definition at line 13262 of file cgmain.cpp.
References LL_FnProto_::abi, LL_ABI_Info_::fast_math, flg, LL_FnProto_::fn_name, LL_FnProto_::has_defined_body, FLG::ieee, LL_FnProto_::intrinsic_decl_str, LL_ABI_Info_::is_pure, LL_FnProto_::is_weak, isNVVM(), print_function_signature(), print_nl(), print_token(), and XBIT.
Referenced by write_external_function_declarations().
write_external_function_declarations()
void write_external_function_declarations (int first_time)
...
Definition at line 13303 of file cgmain.cpp.
References DBGTRACEIN, DBGTRACEOUT, ll_proto_iterate(), print_nl(), and write_extern_fndecl().
Referenced by assemble_end().
write_function_attributes()
static INLINE void write_function_attributes (void) static
Emit function attributes in debugging mode output.
The "no-frame-pointer-elim-non-leaf" flag is included to generate better coverage of the function in the .eh_frame section. This is done primarily to help the profiler unwind the stack.
Definition at line 13343 of file cgmain.cpp.
References need_debug_info(), print_token(), SPTR_NULL, write_target_features(), write_vscale_range(), and XBIT.
Referenced by cg_llvm_end().
write_global_and_static_defines()
static void write_global_and_static_defines (void) static
Definition at line 13360 of file cgmain.cpp.
References GBL_TAG::global_def, Globals, GBL_TAG::next, NULL, print_line(), and GBL_TAG::sptr.
Referenced by cg_llvm_fnend(), and schedule().
write_I_CALL()
static int write_I_CALL (INSTR_LIST * curr_instr, bool emit_func_signature_for_call) static
write I_CALL instruction
Parameters
curr_instr pointer to current instruction instance
emit_func_signature_for_call
Returns
1 if debug op was written, 0 otherwise
Definition at line 2487 of file cgmain.cpp.
References assert, CALLCONV_MASK, CALLCONV_SHIFT, cpu_llvm_module, LL_Type_::data_type, INSTR_TAG::dbg_line_op, LL_Module::debug_info, DT_INT, emit_dbg_from_module(), ERR_Fatal, expr_id, FAST_CALL, FAST_MATH_FLAG, fixup_x86_abi_return(), LL_Type_::flags, INSTR_TAG::flags, flg, FLG_OMIT_OP_TYPE, INSTR_TAG::i_name, FLG::ieee, LL_Module::ir, ll_feature_subprogram_not_in_cu, ll_get_calling_conv_str(), LL_I16, LL_MDREF_IS_NULL, OPERAND::ll_type, INSTR_TAG::ll_type, ll_type_is_pointer_to_function(), LL_TYPE_IS_VARARGS_FUNC, LL_VOID, llvm_instr_names, make_lltype_from_dtype(), OPERAND::next, NSZ_MATH_FLAG, INSTR_TAG::operands, print_dbg_line(), print_space(), print_tmp_name(), print_token(), REASSOC_MATH_FLAG, sptr, OPERAND::sptr, LL_Type_::sub_types, INSTR_TAG::tmps, OPERAND::val, write_operand(), write_operands(), write_type(), and XBIT.
Referenced by write_instructions().
write_instructions()
static void write_instructions (LL_Module * module) static
Write the instruction list to the LLVM IR output file.
Definition at line 2976 of file cgmain.cpp.
References llvm_tag::abi_info, asrt, assert, ATOMIC_MEM_ORD_FLAGS, BINOP, BITOP, buf, buff, cached_access_group_metadata, CANCEL_CALL_DBG_VALUE, CONVERT, count, llvm_tag::curr_instr, LL_Type_::data_type, INSTR_TAG::dbg_line_op, DBGTRACE, DBGTRACE1, DBGTRACE3, DBGTRACEIN, DBGTRACEOUT, LL_Module::debug_info, DELETABLE, dont_force_a_dummy_label(), DT_INT, ERR_Fatal, LL_ABI_Info_::extend_abi_return, INSTR_TAG::flags, flg, FLG_AS_UNSIGNED, FLG_FIXUP_RETURN_TYPE, FLG_OMIT_OP_TYPE, FROM_CMPXCHG_MEMORDER_FAIL, gbl, get_atomic_memory_order_name(), get_atomicrmw_opname(), get_llvm_name(), has_multiple_entries(), I_ALLOCA, I_ATOMICRMW, I_BARRIER, I_BR, I_CALL, I_CATCH, I_CLEANUP, I_CMPXCHG, I_DECL, I_EXTELE, I_EXTRACTVAL, I_FADD, I_FCMP, I_FDIV, I_FENCE, I_FILTER, I_FMUL, I_FREM, I_FSUB, I_GEP, I_ICMP, I_INDBR, I_INSELE, I_INSERTVAL, I_INVOKE, I_LANDINGPAD, I_LAST, I_LOAD, INSTR_TAG::i_name, I_NONE, I_PICALL, I_RESUME, I_RET, I_SELECT, I_SHUFFVEC, I_STORE, I_SW, I_UNREACH, I_VA_ARG, FLG::ieee, INSTR_TAG::ilix, INSTR_IS_TERMINAL, INSTR_PREV, Instructions, LL_Module::ir, LDST_HAS_ACCESSGRP_METADATA, LL_DOUBLE, ll_feature_eh_personality_on_landingpad, ll_feature_emit_func_signature_for_call, ll_feature_explicit_gep_load_type, LL_FLOAT, LL_FP128, LL_I1, LL_I128, LL_I16, LL_I24, LL_I256, LL_I32, LL_I40, LL_I48, LL_I56, LL_I64, LL_I8, LL_MDREF_IS_NULL, LL_MDREF_value, LL_PPC_FP128, LL_PTR, OPERAND::ll_type, INSTR_TAG::ll_type, LL_VOID, LL_X86_FP80, lldbg_get_subprogram_line(), llvm_info, llvm_instr_names, LOOP_BACKEDGE_FLAG, make_lltype_from_dtype(), MATCH_OK, match_types(), maybe_fixup_x86_abi_return(), INSTR_TAG::misc_metadata, OPERAND::next, INSTR_TAG::next, NOSYM, NULL, INSTR_TAG::operands, OT_NONE, p, INSTR_TAG::prev, print_dbg_line(), print_nl(), print_personality(), print_space(), print_tmp_name(), print_token(), INSTR_TAG::rank, llvm_tag::return_ll_type, ROOTDG, should_suppress_debug_loc(), sptr, OPERAND::sptr, STARTEBB, store_return_value_for_entry(), LL_Type_::sub_types, t, INSTR_TAG::tmps, INSTR_TAG::traceComment, TMP_TAG::use_count, OPERAND::val, VOLATILE_FLAG, write_I_CALL(), write_llaccgroup_metadata(), write_memory_order(), write_memory_order_and_alignment(), write_operand(), write_operands(), write_profile_exit(), write_tbaa_metadata(), write_type(), write_verbose_type(), and XBIT.
Referenced by schedule().
write_llaccgroup_metadata()
static INLINE void write_llaccgroup_metadata (LL_Module * module, INSTR_LIST * insn, LL_InstrListFlags flag_check, unsigned int val) static
Definition at line 2916 of file cgmain.cpp.
References buf, DEBUG_ASSERT, INSTR_TAG::flags, LL_MDREF_value, INSTR_TAG::misc_metadata, n, print_token(), and val.
Referenced by write_instructions().
write_memory_order()
static void write_memory_order (INSTR_LIST * instrs) static
For the given instruction, write [singlethread] <memory ordering> to the LLVM IR output file.
Definition at line 2874 of file cgmain.cpp.
References ATOMIC_SINGLETHREAD_FLAG, INSTR_TAG::flags, get_atomic_memory_order_name(), print_space(), and print_token().
Referenced by write_instructions(), and write_memory_order_and_alignment().
write_memory_order_and_alignment()
static void write_memory_order_and_alignment (INSTR_LIST * instrs) static
For the given instruction, write [singlethread] <memory ordering>, <alignment> to the LLVM IR output file.
Definition at line 2888 of file cgmain.cpp.
References ATOMIC_MEM_ORD_FLAGS, ATOMIC_SINGLETHREAD_FLAG, DEBUG_ASSERT, INSTR_TAG::flags, I_LOAD, INSTR_TAG::i_name, I_STORE, LDST_BYTEALIGN, print_token(), and write_memory_order().
Referenced by write_instructions().
write_profile_call()
static INLINE void write_profile_call (const char * profFn) static
Shared code to emit a call to a profile function.
Definition at line 1200 of file cgmain.cpp.
References ASMFIL.
Referenced by write_profile_enter(), and write_profile_exit().
write_profile_enter()
static INLINE void write_profile_enter (SPTR sptr, LL_Type * currFnTy) static
Write a call to the profile entry routine.
Parameters
sptr The symbol of the function we are generating
currFnTy The type of the function, sptr
-finstrument-functions adds an entry and exit profile call to each function
Definition at line 1222 of file cgmain.cpp.
References add_profile_decl(), ASMFIL, get_llvm_name(), getitem(), LLVM_LONGTERM_AREA, sptr, and write_profile_call().
Referenced by write_routine_definition().
write_profile_exit()
static INLINE void write_profile_exit (void) static
Write a call to the profile exit routine.
This should be done before each ret in the function.
Definition at line 1257 of file cgmain.cpp.
References write_profile_call().
Referenced by write_instructions().
write_routine_definition()
static INLINE void write_routine_definition (SPTR func_sptr, LL_ABI_Info * abi, LL_Module * module, LL_Type * funcTy) static
Write out the start of an LLVM function definition.
Definition at line 1270 of file cgmain.cpp.
References build_routine_and_parameter_entries(), has_multiple_entries(), write_master_entry_routine(), write_profile_enter(), and XBIT.
Referenced by schedule().
write_target_features()
static INLINE void write_target_features (void) static
Definition at line 13314 of file cgmain.cpp.
References flg, print_token(), and FLG::target_features.
Referenced by print_function_signature(), and write_function_attributes().
write_tbaa_metadata()
static void write_tbaa_metadata (LL_Module * mod, int ilix, OPERAND * opnd, int flags) static
Write out the TBAA metadata, if needed.
Definition at line 2835 of file cgmain.cpp.
References flags, gbl, get_tbaa_metadata(), LL_MDREF_IS_NULL, print_token(), tbaa_disabled(), VOLATILE_FLAG, and write_mdref().
Referenced by write_instructions().
write_verbose_type()
static void write_verbose_type (LL_Type * ll_type) static
Definition at line 2932 of file cgmain.cpp.
References print_token(), and LL_Type_::str.
Referenced by write_instructions().
write_vscale_range()
static INLINE void write_vscale_range (void) static
Definition at line 13324 of file cgmain.cpp.
References flg, print_token(), FLG::vscale_range_max, and FLG::vscale_range_min.
Referenced by print_function_signature(), and write_function_attributes().
x86_promote_to_vector()
static OPERAND * x86_promote_to_vector (LL_Type * eTy, LL_Type * vTy, OPERAND * op) static
Definition at line 6092 of file cgmain.cpp.
References gen_copy_op(), gen_insert_vector(), make_undef_op(), next, OPERAND::next, NULL, and x86_promote_to_vector().
Referenced by maybe_generate_fma(), and x86_promote_to_vector().
zero_extend_int()
static OPERAND * zero_extend_int (OPERAND * op, unsigned result_bits) static
Definition at line 6723 of file cgmain.cpp.
References assert, convert_operand(), ERR_Fatal, I_ZEXT, OPERAND::ll_type, ll_type_int_bits(), and make_int_lltype().
Referenced by gen_llvm_expr(), and gen_optext_comp_operand().
zerojump()
static bool zerojump (ILI_OP opc) static
Definition at line 13968 of file cgmain.cpp.
Referenced by make_stmt().
Variable Documentation
_cpp_init_once
unsigned _cpp_init_once
Definition at line 182 of file cgmain.cpp.
_fcmp_negate
unsigned _fcmp_negate
Definition at line 185 of file cgmain.cpp.
_float_jmp
unsigned _float_jmp
Definition at line 184 of file cgmain.cpp.
_ftn_init_once
unsigned _ftn_init_once
Definition at line 183 of file cgmain.cpp.
_init_once
unsigned _init_once
Definition at line 181 of file cgmain.cpp.
_killCSE
unsigned _killCSE
Definition at line 180 of file cgmain.cpp.
_last_stmt_is_branch
unsigned _last_stmt_is_branch
Definition at line 186 of file cgmain.cpp.
_new_ebb
unsigned _new_ebb
Definition at line 179 of file cgmain.cpp.
_rw_acc_grp_check
unsigned _rw_acc_grp_check
Definition at line 187 of file cgmain.cpp.
addressElementSize
unsigned addressElementSize static
Definition at line 98 of file cgmain.cpp.
Referenced by gen_address_operand(), and maybe_do_gep_folding().
cached_access_group_metadata
LL_MDRef cached_access_group_metadata = ll_get_md_null() static
Definition at line 214 of file cgmain.cpp.
Referenced by cons_loop_parallel_accesses_metadata(), schedule(), and write_instructions().
cached_loop_id_md
LL_MDRef cached_loop_id_md = ll_get_md_null() static
Definition at line 208 of file cgmain.cpp.
Referenced by clear_cached_loop_id_md(), and cons_loop_id_md().
cached_loop_id_md_has_vectorize
bool cached_loop_id_md_has_vectorize = false static
Definition at line 209 of file cgmain.cpp.
Referenced by clear_cached_loop_id_md(), and cons_vec_always_metadata().
cached_unroll_disable_metadata
LL_MDRef cached_unroll_disable_metadata = ll_get_md_null() static
Definition at line 213 of file cgmain.cpp.
Referenced by cons_nounroll_metadata().
cached_unroll_enable_metadata
LL_MDRef cached_unroll_enable_metadata = ll_get_md_null() static
Definition at line 212 of file cgmain.cpp.
Referenced by cons_unroll_metadata().
cached_vectorize_disable_metadata
LL_MDRef cached_vectorize_disable_metadata = ll_get_md_null() static
Definition at line 211 of file cgmain.cpp.
Referenced by cons_novectorize_metadata().
cached_vectorize_enable_metadata
LL_MDRef cached_vectorize_enable_metadata = ll_get_md_null() static
Definition at line 210 of file cgmain.cpp.
Referenced by cons_vectorize_metadata().
cc_as_str
const char* cc_as_str[] = {CALLCONV}
Definition at line 2431 of file cgmain.cpp.
CG_cpu_compile
bool CG_cpu_compile = false static
Definition at line 216 of file cgmain.cpp.
Referenced by compilingGlobalOrDevice(), and schedule().
struct { ... } CGMain
complexResultList
ComplexResultList_t complexResultList static
Definition at line 277 of file cgmain.cpp.
Referenced by add_prescan_complex_list(), clear_prescan_complex_list(), and on_prescan_complex_list().
cpu_llvm_module
LL_Module* cpu_llvm_module = NULL
Definition at line 170 of file cgmain.cpp.
Referenced by add_ctor(), add_debug_cmnblk_variables(), add_external_function_declaration(), add_global_define(), addDebugForGlobalVar(), addDebugForLocalVar(), assemble_end(), cg_llvm_end(), cg_llvm_fnend(), cg_llvm_init(), cons_expression_metadata_operand(), cons_loop_id_md(), cons_loop_parallel_accesses_metadata(), cons_nounroll_metadata(), cons_novectorize_metadata(), cons_unroll_count_metadata(), cons_unroll_metadata(), cons_vec_always_metadata(), cons_vectorize_metadata(), cons_vectorlength_scalable_metadata(), consLoadDebug(), construct_vectorlength_metadata(), finish_routine(), formalsAddDebug(), gen_call_expr(), gen_llvm_cmpxchg(), gen_llvm_expr(), gen_ptr_offset_val(), gen_vsincos_return_type(), generating_debug_info(), insert_llvm_dbg_declare(), insert_llvm_dbg_value(), ll_check_struct_return(), ll_convert_struct_dtype(), ll_process_routine_parameters(), lldbg_create_cmblk_mem_mdnode_list(), lldbg_create_global_variable_mdnode(), lldbg_create_module_mdnode(), lldbg_emit_global_variable(), lldbg_emit_type(), llvm_get_current_module(), make_function_type_from_args(), make_instr(), process_cmnblk_data(), process_formal_arguments(), process_global_lifetime_debug(), process_params(), put_addr(), schedule(), update_llvm_sym_arrays(), write_bss(), write_I_CALL(), write_statics(), and write_typedescs().
csedList
CSED_ITEM* csedList static
Definition at line 263 of file cgmain.cpp.
Referenced by add_to_cselist(), clear_csed_list(), get_csed_operand(), remove_from_csed_list(), and schedule().
curr_stmt_type
STMT_Type curr_stmt_type static
Definition at line 205 of file cgmain.cpp.
Referenced by make_stmt().
current_module
LL_Module* current_module = NULL
Definition at line 169 of file cgmain.cpp.
Referenced by formalsAddDebug(), llvm_write_ctor_dtor_list(), and schedule().
entry_bih
int entry_bih = 0 static
Definition at line 203 of file cgmain.cpp.
Referenced by cg_llvm_init(), and schedule().
expr_id
int expr_id static
Definition at line 202 of file cgmain.cpp.
Referenced by print_tmp_name(), reset_expr_id(), schedule(), and write_I_CALL().
fnegcc
int fnegcc[17] = LLCCF_NEG static
Definition at line 201 of file cgmain.cpp.
Referenced by convert_to_llvm_cc().
funcId
int funcId static
Definition at line 200 of file cgmain.cpp.
Referenced by get_omnipotent_pointer(), locset_to_tbaa_info(), and schedule().
Globals
GBL_LIST* Globals static
Definition at line 260 of file cgmain.cpp.
Referenced by add_global_define(), cg_llvm_fnend(), cg_llvm_init(), and write_global_and_static_defines().
gpu_llvm_module
LL_Module* gpu_llvm_module = NULL
Definition at line 172 of file cgmain.cpp.
Referenced by cg_llvm_end(), cg_llvm_init(), init_gpu_output_file(), and schedule().
Instructions
INSTR_LIST* Instructions static
Definition at line 262 of file cgmain.cpp.
Referenced by ad_instr(), make_stmt(), remove_instr(), schedule(), and write_instructions().
llvm_ctor_list
init_list_t llvm_ctor_list static
Definition at line 14304 of file cgmain.cpp.
Referenced by llvm_ctor_add(), llvm_ctor_add_with_priority(), and llvm_write_ctors().
llvm_dtor_list
init_list_t llvm_dtor_list static
Definition at line 14305 of file cgmain.cpp.
Referenced by llvm_dtor_add(), llvm_dtor_add_with_priority(), and llvm_write_ctors().
llvm_info
struct llvm_tag llvm_info static
Referenced by ad_csed_instr(), ad_instr(), add_global_define(), analyze_ret_info(), cg_fetch_clen_parampos(), cg_llvm_init(), clear_deletable_flags(), clen_parent_is_param(), currsub_is_sret(), find_load_cse(), gen_constant(), gen_llvm_expr(), gen_name_private_sptr(), gen_return_operand(), get_intrinsic(), get_parnum(), insert_entry_label(), insert_jump_entry_instr(), llvm_info_last_instr(), make_bitcast(), make_stmt(), maybe_generate_fma(), print_function_signature(), process_auto_sptr(), process_formal_arguments(), process_local_sptr(), process_sptr_offset(), remove_dead_instrs(), remove_instr(), repeats_in_binary(), schedule(), update_llvm_sym_arrays(), and write_instructions().
llvm_instr_names
const char* const llvm_instr_names[I_LAST] static
Initial value:
= {
  "none", "ret", "br", "switch", "invoke", "unwind", "unreachable",
  "add nsw",
  "fadd",
  "sub nsw",
  "fsub",
  "mul nsw",
  "fmul", "udiv", "sdiv", "fdiv", "urem", "srem", "frem",
  "shl nsw",
  "lshr", "ashr", "and", "or", "xor", "extractelement", "insertelement",
  "shufflevector", "extractvalue", "insertvalue", "malloc", "free", "alloca",
  "load", "store", "getelementptr", "trunc", "zext", "sext", "fptrunc",
  "fpext", "fptoui", "fptosi", "uitofp", "sitofp", "ptrtoint", "inttoptr",
  "bitcast", "icmp", "fcmp", "vicmp", "vfcmp", "phi", "select", "call",
  "va_arg", "=", "landingpad", "resume", "cleanup", "catch", "fence",
  "atomicrmw", "cmpxchg", "fence", "call", "indirectbr", "filter"
}
Definition at line 67 of file cgmain.cpp.
Referenced by convert_int_size(), store_return_value_for_entry(), write_I_CALL(), and write_instructions().
MEM_EXTRA
const int MEM_EXTRA = 500
Definition at line 92 of file cgmain.cpp.
Referenced by cg_llvm_init(), and update_llvm_sym_arrays().
recorded_Globals
GBL_LIST* recorded_Globals static
Definition at line 261 of file cgmain.cpp.
Referenced by cg_llvm_fnend(), cg_llvm_init(), and check_global_define().
ret_info
struct ret_tag ret_info static
Referenced by analyze_ret_info(), gen_return_operand(), gen_sret_expr(), is_special_return_symbol(), print_function_signature(), process_auto_sptr(), and schedule().
routine_count
int routine_count static
Definition at line 204 of file cgmain.cpp.
Referenced by cg_llvm_init(), and schedule().
sincos_imap
hashmap_t sincos_imap static
Definition at line 207 of file cgmain.cpp.
Referenced by add_sincos_imap(), add_sincos_imap_loads(), gen_llvm_sincos_call(), gen_llvm_vsincos_call(), get_last_sincos(), remove_dead_sincos_calls(), sincos_argument_valid(), sincos_clear_all_args(), sincos_clear_arg_helper(), sincos_clear_specific_arg(), and sincos_seen().
sincos_map
hashmap_t sincos_map static
Definition at line 206 of file cgmain.cpp.
Referenced by add_sincos_map(), cleanup_unneeded_sincos_calls(), and remove_dead_sincos_calls().
sptrinfo
SPTRINFO_T sptrinfo
Definition at line 165 of file cgmain.cpp.
Referenced by cg_llvm_init().
stmt_names
const char* const stmt_names[STMT_LAST] static
Initial value:
= {
    "STMT_NONE", "STMT_RET",  "STMT_EXPR",  "STMT_LABEL", "STMT_BR",
    "STMT_ST",   "STMT_CALL", "STMT_SMOVE", "STMT_SZERO", "STMT_DECL"
}
Definition at line 85 of file cgmain.cpp.
Referenced by make_stmt().
tempsMap
TmpsMap tempsMap static
Definition at line 269 of file cgmain.cpp.
Referenced by consTempMap(), gcTempMap(), getTempMap(), and setTempMap().