flang: cgmain.h File Reference
cgmain.h File Reference
#include "gbldefs.h"
#include "global.h"
#include "symtab.h"
#include "ili.h"
#include "cgllvm.h"
#include "ll_structure.h"
#include "llutil.h"
Macros
#define FFAST_MATH_IS_PRESENT() XBIT(216, 1)
#define QTMP_SIZE 4 /* tmp[] of union qtmp has 4 elements and 128 bits */
Functions
bool currsub_is_sret (void)
...
bool is_cg_llvm_init (void)
...
bool ll_check_struct_return (DTYPE dtype)
...
bool strict_match (LL_Type *ty1, LL_Type *ty2)
...
const char * dtype_struct_name (DTYPE dtype)
...
char * gen_llvm_vconstant (const char *ctype, int sptr, DTYPE tdtype, int flags)
...
const char * get_label_name (int sptr)
...
const char * match_names (MATCH_Kind match_val)
...
const char * char_type (DTYPE dtype, SPTR sptr)
...
DTYPE msz_dtype (MSZ msz)
...
INSTR_LIST * llvm_info_last_instr (void)
...
INSTR_LIST * mk_store_instr (OPERAND *val, OPERAND *addr)
...
DTYPE cg_get_type (int n, TY_KIND v1, int v2)
...
SPTR find_pointer_to_function (int ilix)
Find the (virtual) function pointer in a JSRA call.
int match_llvm_types (LL_Type *ty1, LL_Type *ty2)
...
int need_ptr (int sptr, int sc, DTYPE sdtype)
...
LL_Type * maybe_fixup_x86_abi_return (LL_Type *sig)
...
OPERAND * gen_address_operand (int addr_op, int nme, bool lda, LL_Type *llt_expected, MSZ msz)
...
OPERAND * gen_call_as_llvm_instr (int sptr, int ilix)
...
OPERAND * gen_call_to_builtin (int ilix, char *fname, OPERAND *params, LL_Type *return_ll_type, INSTR_LIST *Call_Instr, LL_InstrName i_name, LL_InstrListFlags MathFlag, unsigned flags)
...
OPERAND * gen_llvm_expr (int ilix, LL_Type *expected_type)
...
OPERAND * mk_alloca_instr (LL_Type *ptrTy)
...
TMPS * gen_extract_insert (LL_InstrName i_name, LL_Type *struct_type, TMPS *tmp, LL_Type *tmp_type, TMPS *tmp2, LL_Type *tmp2_type, int index)
...
void build_routine_and_parameter_entries (SPTR func_sptr, LL_ABI_Info *abi, LL_Module *module)
...
void cg_fetch_clen_parampos (SPTR *len, int *param, SPTR sptr)
...
bool clen_parent_is_param (SPTR length)
...
void cg_llvm_end (void)
...
void cg_llvm_fnend (void)
...
void cg_llvm_init (void)
...
void clear_deletable_flags (int ilix)
...
void dump_type_for_debug (LL_Type *ll_type)
...
void llvm_ctor_add (const char *name)
...
void llvm_ctor_add_with_priority (const char *name, int priority)
...
void llvm_dtor_add (const char *name)
...
void llvm_dtor_add_with_priority (const char *name, int priority)
...
void llvmResetSname (int sptr)
...
void llvm_write_ctors (void)
...
void print_personality (void)
...
void print_tmp_name (TMPS *t)
...
void process_formal_arguments (LL_ABI_Info *abi)
...
void process_global_lifetime_debug (void)
...
void process_sptr (SPTR sptr)
...
void reset_expr_id (void)
...
void schedule (void)
...
void set_llvm_sptr_name (OPERAND *operand)
...
void update_external_function_declarations (const char *name, char *decl, unsigned flags)
...
void write_external_function_declarations (int first_time)
...
bool is_vector_x86_mmx (LL_Type *)
void add_debug_cmnblk_variables (LL_DebugInfo *db, SPTR sptr)
Process common block symbols, adding debug info for it's variables.
bool ftn_array_need_debug_info (SPTR sptr)
Check if sptr is the mindum of an array and the array has descriptor.
void insert_llvm_dbg_declare (LL_MDRef mdnode, SPTR sptr, LL_Type *llTy, OPERAND *exprMDOp, OperandFlag_t opflag)
Insert @llvm.dbg.declare call for debug.
void insert_llvm_dbg_value (OPERAND *load, LL_MDRef mdnode, SPTR sptr, LL_Type *type)
Insert @llvm.dbg.value call for debug.
bool pointer_scalar_need_debug_info (SPTR sptr)
Check if sptr is the midnum of a scalar and scalar has POINTER/ALLOCATABLE attribute.
int get_parnum (SPTR sptr)
Macro Definition Documentation
FFAST_MATH_IS_PRESENT
#define FFAST_MATH_IS_PRESENT () XBIT(216, 1)
Definition at line 19 of file cgmain.h.
QTMP_SIZE
#define QTMP_SIZE 4 /* tmp[] of union qtmp has 4 elements and 128 bits */
Definition at line 20 of file cgmain.h.
Function Documentation
add_debug_cmnblk_variables()
void add_debug_cmnblk_variables (LL_DebugInfo * db, SPTR sptr)
Process common block symbols, adding debug info for it's variables.
Parameters
sptr A symbol
Definition at line 14441 of file cgmain.cpp.
References addDebugForGlobalVar(), cpu_llvm_module, db(), gbl, hash_functions_strings, hashset_alloc(), hashset_insert(), hashset_lookup(), LL_Module::ir, ll_feature_debug_info_ver11, lldbg_add_pending_import_entity(), lldbg_add_pending_import_entity_to_child(), lookup_modvar_alias(), new_debug_name(), NOSYM, NULL, RU_BDATA, scope, SNAME, sptr, SYMNAME, and variable_offset_in_aggregate().
Referenced by lldbg_emit_common_block_mdnode(), and process_global_lifetime_debug().
build_routine_and_parameter_entries()
void build_routine_and_parameter_entries (SPTR func_sptr, LL_ABI_Info * abi, LL_Module * module)
...
...
Writes text from define to the label of the entry block.
Definition at line 13873 of file cgmain.cpp.
Referenced by write_routine_definition().
cg_fetch_clen_parampos()
void cg_fetch_clen_parampos (SPTR * len, int * param, SPTR sptr)
...
Definition at line 14407 of file cgmain.cpp.
cg_get_type()
DTYPE cg_get_type (int n, TY_KIND v1, int v2)
...
Definition at line 512 of file cgmain.cpp.
References get_type(), n, and update_llvm_sym_arrays().
Referenced by gen_llvm_atomic_intrinsic_for_builtin(), ll_make_kmpc_struct_type(), mk_struct_for_llvm_init(), and update_return_type_for_ccfunc().
cg_llvm_end()
void cg_llvm_end (void)
...
...
Dumps the metadata for the Module.
Definition at line 14122 of file cgmain.cpp.
cg_llvm_fnend()
void cg_llvm_fnend (void)
...
...
In Fortran, we carry over data from the LONGTERM_AREA to the next subroutine to be processed.
Definition at line 14142 of file cgmain.cpp.
cg_llvm_init()
void cg_llvm_init (void)
...
Definition at line 14023 of file cgmain.cpp.
Referenced by cg_llvm_fnend(), and schedule().
char_type()
const char * char_type (DTYPE dtype, SPTR sptr)
...
...
Parameters
sptr symbol to use for type consing or 0
dtype used when sptr not provided
Definition at line 13993 of file cgmain.cpp.
References make_lltype_from_dtype(), make_lltype_from_sptr(), need_ptr(), sptr, LL_Type_::str, and LL_Type_::sub_types.
Referenced by gen_constant(), ll_process_routine_parameters(), process_blockaddr_sptr(), process_extern_function_sptr(), process_extern_variable_sptr(), process_local_sptr(), put_fstr(), put_kstr(), write_comm(), write_consts(), and write_externs().
clear_deletable_flags()
void clear_deletable_flags (int ilix)
...
...
Parameters
ilix The ILI of a LOAD instruction
Definition at line 6798 of file cgmain.cpp.
clen_parent_is_param()
bool clen_parent_is_param (SPTR length)
...
...
Parameters
length is the compiler created symbol which represents length of assumed length string argument
Definition at line 14428 of file cgmain.cpp.
References llvm_tag::abi_info, LL_ABI_Info_::arg, DTY, i, length(), llvm_info, LL_ABI_Info_::nargs, parent, LL_ABI_ArgInfo_::sptr, and TY_CHAR.
Referenced by process_formal_arguments().
currsub_is_sret()
bool currsub_is_sret (void)
...
Definition at line 817 of file cgmain.cpp.
dtype_struct_name()
const char * dtype_struct_name (DTYPE dtype)
...
...
Parameters
dtype dtype index
Returns
string containing dtype name
Definition at line 11105 of file cgmain.cpp.
References process_dtype_struct().
dump_type_for_debug()
void dump_type_for_debug (LL_Type * ll_type)
...
Definition at line 3589 of file cgmain.cpp.
References ll_dfile, NULL, and LL_Type_::str.
find_pointer_to_function()
SPTR find_pointer_to_function (int ilix)
Find the (virtual) function pointer in a JSRA call.
Parameters
ilix the first argument of the IL_JSRA
Definition at line 7024 of file cgmain.cpp.
References addr, IL_AADD, ILI_OPC, ILI_OPND, ILI_SymOPND, sptr, SPTR_NULL, and SymConval1.
Referenced by get_call_sptr().
ftn_array_need_debug_info()
bool ftn_array_need_debug_info (SPTR sptr)
Check if sptr is the mindum of an array and the array has descriptor.
Parameters
sptr A symbol
Check if sptr is the mindum of an array and the array has descriptor.
Parameters
sptr A symbol
Definition at line 11223 of file cgmain.cpp.
References NOSYM, and sptr.
Referenced by addDebugForLocalVar(), insert_llvm_dbg_declare(), lldbg_create_global_variable_mdnode(), lldbg_emit_global_variable(), lldbg_emit_local_variable(), lldbg_emit_type(), and needDebugInfoFilt().
gen_address_operand()
OPERAND * gen_address_operand (int addr_op, int nme, bool lda, LL_Type * llt_expected, MSZ msz)
...
...
Parameters
addr_op ILI of address expression
nme NME value
lda is this an IL_LDA?
llt_expected expected LL_Type
msz memory access size
Definition at line 12473 of file cgmain.cpp.
Referenced by gen_llvm_expr(), and make_stmt().
gen_call_as_llvm_instr()
OPERAND * gen_call_as_llvm_instr (int sptr, int ilix)
...
gen_call_to_builtin()
OPERAND * gen_call_to_builtin (int ilix, char * fname, OPERAND * params, LL_Type * return_ll_type, INSTR_LIST * Call_Instr, LL_InstrName i_name, LL_InstrListFlags MathFlag, unsigned flags)
...
Definition at line 4614 of file cgmain.cpp.
References ad_instr(), CALL_INTRINSIC_FLAG, DBGTRACEIN1, DBGTRACEOUT, flags, INSTR_TAG::flags, fname, get_intrinsic_call_ops(), getitem(), TMP_TAG::idef, TMP_TAG::info, INSTR_TAG::ll_type, LLVM_LONGTERM_AREA, make_instr(), make_tmp_op(), make_tmps(), NULL, operand, INSTR_TAG::operands, params, strlen(), and INSTR_TAG::tmps.
Referenced by cleanup_unneeded_sincos_calls(), gen_call_llvm_intrinsic_impl(), gen_call_pgocl_intrinsic(), gen_call_vminmax_intrinsic(), gen_call_vminmax_neon_intrinsic(), gen_call_vminmax_power_intrinsic(), gen_llvm_sincos_call(), and gen_llvm_vsincos_call().
gen_extract_insert()
TMPS * gen_extract_insert (LL_InstrName i_name, LL_Type * struct_type, TMPS * tmp, LL_Type * tmp_type, TMPS * tmp2, LL_Type * tmp2_type, int index)
...
Definition at line 3605 of file cgmain.cpp.
References ad_instr(), DT_INT, gen_instr(), getcon(), STB::i0, STB::i1, index, OPERAND::ll_type, make_lltype_from_dtype(), make_operand(), make_tmp_op(), make_tmps(), make_undef_op(), OPERAND::next, num, OT_CONSTSPTR, OPERAND::ot_type, OPERAND::sptr, stb, tmp, and OPERAND::val.
gen_llvm_expr()
OPERAND * gen_llvm_expr (int ilix, LL_Type * expected_type)
...
Definition at line 8285 of file cgmain.cpp.
Referenced by attempt_gep_folding(), fused_multiply_add_canonical_form(), gen_abs_expr(), gen_arg_operand(), gen_base_addr_operand(), gen_binary_expr(), gen_bitcast_vector(), gen_call_expr(), gen_convert_vector(), gen_eval_cmplx_value(), gen_llvm_atomic_intrinsic_for_builtin(), gen_llvm_atomicrmw_expr(), gen_llvm_cmpxchg(), gen_llvm_cmpxchg_component(), gen_llvm_expr(), gen_llvm_instr(), gen_llvm_sincos_call(), gen_llvm_vsincos_call(), gen_mulh_expr(), gen_optext_comp_operand(), gen_scalar_to_vector_helper(), gen_scalar_to_vector_no_shuffle(), gen_select_expr(), gen_sret_expr(), gen_switch(), gen_unary_expr(), gen_va_arg(), gen_va_end(), gen_va_start(), gen_vect_compare_operand(), insert_jump_entry_instr(), make_stmt(), and schedule().
gen_llvm_vconstant()
char * gen_llvm_vconstant (const char * ctype, int sptr, DTYPE tdtype, int flags)
...
Definition at line 13009 of file cgmain.cpp.
References flags, gen_vconstant(), and sptr.
get_label_name()
const char * get_label_name (int sptr)
...
Definition at line 481 of file cgmain.cpp.
References SNAME, and sptr.
Referenced by make_label_op(), make_target_op(), and process_blockaddr_sptr().
get_parnum()
int get_parnum (SPTR sptr)
Definition at line 14561 of file cgmain.cpp.
References llvm_tag::abi_info, LL_ABI_Info_::arg, llvm_info, LL_ABI_Info_::nargs, sptr, and LL_ABI_ArgInfo_::sptr.
Referenced by lldbg_emit_param_variable(), and lldbg_emit_type().
insert_llvm_dbg_declare()
void insert_llvm_dbg_declare (LL_MDRef mdnode, SPTR sptr, LL_Type * llTy, OPERAND * exprMDOp, OperandFlag_t opflag)
Insert @llvm.dbg.declare call for debug.
Parameters
mdnode metadata node
sptr symbol
llTy preferred type of sptr or NULL
Definition at line 4907 of file cgmain.cpp.
References ad_instr(), add_external_function_declaration(), CALL_INTRINSIC_FLAG, cpu_llvm_module, INSTR_TAG::dbg_line_op, LL_Module::debug_info, deref, EXF_INTRINSIC, EXFUNC_LIST::flags, OPERAND::flags, INSTR_TAG::flags, ftn_array_need_debug_info(), EXFUNC_LIST::func_def, getitem(), I_CALL, LL_Module::ir, LL_DW_OP_deref, ll_feature_dbg_declare_needs_expression_md, ll_feature_debug_info_ver90, OPERAND::ll_type, INSTR_TAG::ll_type, lldbg_emit_empty_expression_mdnode(), lldbg_emit_expression_mdnode(), lldbg_encode_expression_arg(), lldbg_get_var_line(), LLVM_LONGTERM_AREA, make_instr(), make_mdref_op(), make_metadata_wrapper_op(), make_operand(), make_void_lltype(), OPERAND::next, INSTR_TAG::operands, OT_CALL, OPERAND::ot_type, sptr, and OPERAND::string.
Referenced by addDebugForLocalVar(), formalsAddDebug(), lldbg_create_deferred_len_string_type_mdnode(), and lldbg_emit_type().
insert_llvm_dbg_value()
void insert_llvm_dbg_value (OPERAND * load, LL_MDRef mdnode, SPTR sptr, LL_Type * type)
Insert @llvm.dbg.value call for debug.
Parameters
OPERAND operand
sptr symbol
llTy preferred type of sptr or NULL
Definition at line 5628 of file cgmain.cpp.
References ad_instr(), add_external_function_declaration(), CALL_INTRINSIC_FLAG, cpu_llvm_module, INSTR_TAG::dbg_line_op, LL_Module::debug_info, EXF_INTRINSIC, EXFUNC_LIST::flags, OPERAND::flags, INSTR_TAG::flags, EXFUNC_LIST::func_def, getitem(), I_CALL, ll_create_int_type(), OPERAND::ll_type, INSTR_TAG::ll_type, lldbg_emit_empty_expression_mdnode(), lldbg_get_var_line(), LLVM_LONGTERM_AREA, load, make_constval_op(), make_instr(), make_mdref_op(), make_operand(), make_void_lltype(), OPERAND::next, INSTR_TAG::operands, OPF_WRAPPED_MD, OT_CALL, OT_MDNODE, OPERAND::ot_type, sptr, OPERAND::string, OPERAND::tmps, type, and OPERAND::val.
Referenced by consLoadDebug(), lldbg_emit_type(), and process_params().
is_cg_llvm_init()
bool is_cg_llvm_init (void)
...
Definition at line 14164 of file cgmain.cpp.
is_vector_x86_mmx()
bool is_vector_x86_mmx (LL_Type * type)
Definition at line 14542 of file cgmain.cpp.
References LL_PTR, LL_VECTOR, t, and type.
Referenced by add_external_function_declaration().
ll_check_struct_return()
bool ll_check_struct_return (DTYPE dtype)
...
...
This is a backdoor for the expander to access the LLVM bridge.
Definition at line 531 of file cgmain.cpp.
References cpu_llvm_module, DEBUG_ASSERT, DT_ISCMPLX, DTY, gbl, ll_abi_classify_return_dtype(), ll_abi_for_func_sptr(), and LL_ABI_HAS_SRET.
Referenced by check_struct().
llvm_ctor_add()
void llvm_ctor_add (const char * name)
...
Definition at line 14329 of file cgmain.cpp.
llvm_ctor_add_with_priority()
void llvm_ctor_add_with_priority (const char * name, int priority)
...
Definition at line 14335 of file cgmain.cpp.
Referenced by build_routine_and_parameter_entries().
llvm_dtor_add()
void llvm_dtor_add (const char * name)
...
Definition at line 14341 of file cgmain.cpp.
llvm_dtor_add_with_priority()
void llvm_dtor_add_with_priority (const char * name, int priority)
...
Definition at line 14347 of file cgmain.cpp.
Referenced by build_routine_and_parameter_entries().
llvm_info_last_instr()
INSTR_LIST * llvm_info_last_instr (void)
...
Definition at line 520 of file cgmain.cpp.
llvm_write_ctors()
void llvm_write_ctors (void)
...
Definition at line 14400 of file cgmain.cpp.
llvmResetSname()
void llvmResetSname (int sptr)
...
...
Parameters
sptr the symbol Used by auto parallel in C when the optimizer uses the same compiler generated variable across loops
Definition at line 811 of file cgmain.cpp.
References NULL, SNAME, and sptr.
Referenced by processOutlinedByConcur().
match_llvm_types()
int match_llvm_types (LL_Type * ty1, LL_Type * ty2)
...
Definition at line 12113 of file cgmain.cpp.
References match_types().
match_names()
const char * match_names (MATCH_Kind match_val)
...
Definition at line 4971 of file cgmain.cpp.
References asrt, getitem(), LLVM_LONGTERM_AREA, MATCH_MEM, MATCH_NO, and MATCH_OK.
Referenced by match_types().
maybe_fixup_x86_abi_return()
LL_Type * maybe_fixup_x86_abi_return (LL_Type * sig)
...
Definition at line 2466 of file cgmain.cpp.
References LL_Type_::data_type, fixup_x86_abi_return(), LL_FUNCTION, ll_get_pointer_type(), LL_I16, LL_PTR, pt, LL_Type_::sub_types, and XBIT.
Referenced by write_instructions(), and write_operand().
mk_alloca_instr()
OPERAND * mk_alloca_instr (LL_Type * ptrTy)
...
Definition at line 3565 of file cgmain.cpp.
mk_store_instr()
INSTR_LIST * mk_store_instr (OPERAND * val, OPERAND * addr)
...
Definition at line 3574 of file cgmain.cpp.
Referenced by make_stmt(), and make_store().
msz_dtype()
DTYPE msz_dtype (MSZ msz)
...
Definition at line 2377 of file cgmain.cpp.
Referenced by gen_llvm_expr(), make_stmt(), and make_type_from_msz_with_addrspace().
need_ptr()
int need_ptr (int sptr, int sc, DTYPE sdtype)
...
Definition at line 12376 of file cgmain.cpp.
References DTY, is_special_return_symbol(), and sptr.
Referenced by char_type(), make_lltype_from_sptr(), and put_addr().
pointer_scalar_need_debug_info()
bool pointer_scalar_need_debug_info (SPTR sptr)
Check if sptr is the midnum of a scalar and scalar has POINTER/ALLOCATABLE attribute.
Parameters
sptr A symbol
Definition at line 11207 of file cgmain.cpp.
References NOSYM, and sptr.
Referenced by addDebugForLocalVar(), lldbg_emit_global_variable(), and lldbg_emit_local_variable().
print_personality()
void print_personality (void)
...
Definition at line 798 of file cgmain.cpp.
References print_token().
Referenced by write_instructions().
print_tmp_name()
void print_tmp_name (TMPS * t)
...
Definition at line 12926 of file cgmain.cpp.
References expr_id, idx, print_token(), t, and tmp.
Referenced by print_entry_subroutine(), store_return_value_for_entry(), write_I_CALL(), write_instructions(), and write_operand().
process_formal_arguments()
void process_formal_arguments (LL_ABI_Info * abi)
...
...
Generate the required prolog code to home all arguments that need it.
llvm_info.abi_info must be initialized before calling this function.
Populates llvm_info.homed_args, which must be allocated and empty before the call.
Definition at line 13477 of file cgmain.cpp.
Referenced by schedule().
process_global_lifetime_debug()
void process_global_lifetime_debug (void)
...
...
Definition at line 14504 of file cgmain.cpp.
process_sptr()
void process_sptr (SPTR sptr)
...
Definition at line 11970 of file cgmain.cpp.
References process_sptr_offset(), sptr, and variable_offset_in_aggregate().
Referenced by analyze_ret_info(), gen_sptr(), gen_sret_expr(), get_ftn_lltype(), get_llvm_sname(), is_blockaddr_store(), make_arg_op(), make_label_op(), make_metadata_wrapper_op(), make_stmt(), make_target_op(), make_var_op(), print_entry_subroutine(), process_formal_arguments(), put_addr(), schedule(), write_comm(), write_layout_desc_entry(), and write_typedescs().
reset_expr_id()
void reset_expr_id (void)
...
Definition at line 14236 of file cgmain.cpp.
schedule()
void schedule (void)
...
...
Definition at line 17 of file dummy.c.
set_llvm_sptr_name()
void set_llvm_sptr_name (OPERAND * operand)
...
Definition at line 474 of file cgmain.cpp.
References operand, SNAME, and sptr.
Referenced by make_var_op().
strict_match()
bool strict_match (LL_Type * ty1, LL_Type * ty2)
...
Definition at line 12011 of file cgmain.cpp.
Referenced by gen_base_addr_operand(), gen_llvm_expr(), and make_bitcast().
update_external_function_declarations()
void update_external_function_declarations (const char * name, char * decl, unsigned flags)
...
Definition at line 10852 of file cgmain.cpp.
Referenced by get_intrinsic().
write_external_function_declarations()
void write_external_function_declarations (int first_time)
...
Definition at line 13303 of file cgmain.cpp.