flang: chn1tn.c File Reference
chn1tn.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "genlist.h"
#include "xfer.h"
Functions
struct chdr * __fort_chn_1toN (struct chdr *cp, int dnd, int dlow, int *dcnts, int *dstrs, int snd, int slow, int *scnts, int *sstrs)
Function Documentation
__fort_chn_1toN()
struct chdr * __fort_chn_1toN (struct chdr * cp, int dnd, int dlow, int * dcnts, int * dstrs, int snd, int slow, int * scnts, int * sstrs)
Definition at line 15 of file chn1tn.c.
References __fort_allchn(), __fort_bcstchn(), __fort_free(), __fort_genlist(), __fort_malloc(), __fort_myprocnum(), c, copy(), cp, CPU_COPY, CPU_RECV, CPU_SEND, cgrp::cpus, i, MAXDIMS, n, cgrp::ncpus, and sg.
Referenced by copy_xfer().