flang: chn1t1.c File Reference
chn1t1.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "genlist.h"
#include "xfer.h"
Functions
struct chdr * __fort_chn_1to1 (struct chdr *cp, int dnd, int dlow, int *dcnts, int *dstrs, int snd, int slow, int *scnts, int *sstrs)
Function Documentation
__fort_chn_1to1()
struct chdr * __fort_chn_1to1 (struct chdr * cp, int dnd, int dlow, int * dcnts, int * dstrs, int snd, int slow, int * scnts, int * sstrs)
Definition at line 15 of file chn1t1.c.
References __fort_allchn(), __fort_free(), __fort_genlist(), __fort_initndx(), c, cp, cpu(), CPU_COPY, CPU_RECV, CPU_SEND, cgrp::cpus, GET_DIST_LCPU, GET_DIST_TCPUS, MAXDIMS, cgrp::ncpus, r, and sg.
Referenced by __fort_copy(), __fort_exchange_counts(), mget_recv(), mget_send(), and olap_shift().