flang: chnbcst_loop.c File Reference
chnbcst_loop.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
Functions
struct cgrp * __fort_genlist ()
struct chdr * __fort_allchn ()
void __fort_bcstchn (struct chdr *c, int scpu, int ncpus, int *cpus)
Function Documentation
__fort_allchn()
struct chdr * __fort_allchn ()
Referenced by __fort_chn_1to1(), __fort_chn_1toN(), and __fort_comm_merge().
__fort_bcstchn()
void __fort_bcstchn (struct chdr * c, int scpu, int ncpus, int * cpus)
Definition at line 16 of file chnbcst_loop.c.
References __fort_myprocnum(), CPU_RECV, CPU_SEND, and n.
Referenced by __fort_chn_1toN().
__fort_genlist()
struct cgrp * __fort_genlist ()
Referenced by __fort_chn_1to1(), and __fort_chn_1toN().