flang: chnmerge.c File Reference
chnmerge.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "xfer.h"
Functions
static void merge_ent (struct ents *a, struct ents *b, struct ents *c)
chdr * __fort_comm_merge (chdr *b, chdr *c)
Function Documentation
__fort_comm_merge()
chdr * __fort_comm_merge (chdr * b, chdr * c)
Definition at line 31 of file chnmerge.c.
References __fort_abort(), __fort_allchn(), __fort_free(), a, b, CHDR_BASE, cpu(), CPU_COPY, CPU_RECV, CPU_SEND, F90_Desc::flags, GET_DIST_LCPU, GET_DIST_TCPUS, merge_ent(), and r.
merge_ent()
static void merge_ent (struct ents * a, struct ents * b, struct ents * c) static
Definition at line 15 of file chnmerge.c.
References __fort_bcopy(), __fort_free(), __fort_realloc(), a, and b.
Referenced by __fort_comm_merge().