flang: cis_common.h File Reference
cis_common.h File Reference
#include "common.h"
#include "math_common.h"
#include "sleef_common.h"
Macros
#define THRESHOLD_F 0x1.7c3e58p17
#define DELTA 0.005
#define _1_OVER_PI_F I2F(0x3ea2f983)
#define PI_HI_F I2F(0x40490fdc)
#define PI_MI_F I2F(0xb4aeef48)
#define PI_LO_F I2F(0xa9e7b967)
#define S1 I2F(0x3f800000)
#define S3 I2F(0xbe2aaaa9)
#define S5 I2F(0x3c0885e1)
#define S7 I2F(0xb94d4ec3)
#define C0 I2F(0x3f800000)
#define C2 I2F(0xbf000000)
#define C4 I2F(0x3d2aaaa7)
#define C6 I2F(0xbab60727)
#define C8 I2F(0x37cd39b8)
Functions
static float __attribute__ ((noinline)) __reduction_slowpath_pio2(float const a
if ((unsigned) float_as_int(a) >=0x7f800000) return a *0.0f
for (q=0;q< 6;q++)
if (p &0x2000000000000000ULL)
static float _Complex __attribute__ ((always_inline)) inline __cis_scalar_kernel(float x)
static vfloat INLINE __vcis_kernel (vfloat va)
Variables
static float int32_t * h = q
static float int32_t float * w
uint32_t ia = float_as_int(a)
uint32_t result [7] = hi
uint32_t hi = 0
uint32_t lo
uint32_t e = ((ia >> 23) & 0xff) - 127
int32_t idx = 4 - ((e >> 5) & 3)
int32_t q = (p >> 32) & 0xE0000000
uint64_t p = (uint64_t)result[idx + 2] << 32
double d = (double)(int64_t)p
d *float r = (float)d
static vfloat vopmask m
vfloat res = vSETf(0.0f)
int i
const int vlen = sizeof(vfloat) / sizeof(float _Complex)
Macro Definition Documentation
_1_OVER_PI_F
#define _1_OVER_PI_F I2F(0x3ea2f983)
C0
#define C0 I2F(0x3f800000)
C2
#define C2 I2F(0xbf000000)
C4
#define C4 I2F(0x3d2aaaa7)
C6
#define C6 I2F(0xbab60727)
C8
#define C8 I2F(0x37cd39b8)
DELTA
#define DELTA 0.005
PI_HI_F
#define PI_HI_F I2F(0x40490fdc)
PI_LO_F
#define PI_LO_F I2F(0xa9e7b967)
PI_MI_F
#define PI_MI_F I2F(0xb4aeef48)
S1
#define S1 I2F(0x3f800000)
S3
#define S3 I2F(0xbe2aaaa9)
S5
#define S5 I2F(0x3c0885e1)
S7
#define S7 I2F(0xb94d4ec3)
THRESHOLD_F
#define THRESHOLD_F 0x1.7c3e58p17
Function Documentation
__attribute__() [1/2]
static float _Complex __attribute__ ((always_inline)) static
Definition at line 79 of file cis_common.h.
References _1_OVER_PI_F, __reduction_slowpath_pio2(), assert, C0, C2, C4, C6, C8, DELTA, F2I(), fast2mul(), fast2sum(), FL_ABS_MASK, FL_SIGN_BIT, float_as_int(), fmaf(), h, I2F(), k, p, pc, PI_HI_F, PI_LO_F, PI_MI_F, PRINT, r, s, S3, S5, S7, set_cmplx(), sign, t, t1, t2, THRESHOLD_F, w, x, x2, and x3.
__attribute__() [2/2]
static float __attribute__ ((noinline)) const static
__vcis_kernel()
static vfloat INLINE __vcis_kernel (vfloat va) static
Definition at line 260 of file cis_common.h.
References _1_OVER_PI_F, C2, C4, C6, C8, F2I(), FL_ABS_MASK, FL_ONE, FL_SIGN_BIT, k, m, p, PI_HI_F, PI_LO_F, PI_MI_F, PRINT, S3, S5, S7, t1, t2, THRESHOLD_F, va, vadd_vf_vf_vf(), vadd_vi2_vi2_vi2(), vand_vi2_vi2_vi2(), veq_vo_vi2_vi2(), vF2I, vfast2mul(), vfast2sum(), vfma_vf_vf_vf_vf(), vgt_vo_vf_vf(), vI2F, vmul_vf_vf_vf(), vor_vi2_vi2_vi2(), vrev21_vf_vf(), vsel_vf_vo_vf_vf(), vSETf, vSETi, vSETLLi, vsll_vi2_vi2_i(), vsub_vf_vf_vf(), vtestz_i_vo(), vxor_vi2_vi2_vi2(), w, and x2.
Referenced by cexpf_vec().
for()
for ()
Definition at line 37 of file cis_common.h.
References hi, i1opi_f, ia, lo, m, q, result, and umad32wide().
if() [1/2]
if ((unsigned) float_as_int(a) >= 0x7f800000)
if() [2/2]
if (p & 0x2000000000000000ULL)
Definition at line 61 of file cis_common.h.
References p.
Variable Documentation
d
double d = (double)(int64_t)p
Definition at line 69 of file cis_common.h.
Referenced by __attribute__(), __builtin_acos(), __builtin_asin(), __builtin_atan(), __builtin_atan2(), __builtin_ceil(), __builtin_cimag(), __builtin_cimagf(), __builtin_conj(), __builtin_conjf(), __builtin_cos(), __builtin_cosh(), __builtin_creal(), __builtin_crealf(), __builtin_exp(), __builtin_fabs(), __builtin_fabsf(), __builtin_floor(), __builtin_log(), __builtin_log10(), __builtin_pow(), __builtin_sin(), __builtin_sinh(), __builtin_sqrt(), __builtin_tan(), __builtin_tanh(), __builtin_trunc(), __fort_block_bounds(), __fort_block_loop(), __fort_copy_descriptor(), __fort_cycle_bounds(), __fort_cyclic_loop(), __fort_describe(), __fort_describe_replication(), __fort_dump_type(), __fort_fetch_int(), __fort_fetch_int_element(), __fort_fetch_int_vector(), __fort_fetch_log(), __fort_finish_descriptor(), __fort_finish_section(), __fort_frechn(), __fort_gen_block_bounds(), __fort_inherit_template(), __fort_islocal(), __fort_local_address(), __fort_local_offset(), __fort_localize(), __fort_print_local(), __fort_second(), __fort_set_alignment(), __fort_set_second(), __fort_set_section(), __fort_set_sectionx(), __fort_set_single(), __fort_show_section(), __fort_store_int(), __fort_store_int_element(), __fort_store_int_vector(), __fort_store_log(), __fort_use_allocation(), __fortio_chk_f(), __fortio_fmt_d(), __fortio_fmt_e(), __fortio_fmt_f(), __fortio_fmt_g(), __fortio_getnum(), __fortio_strtod(), __INT8_T(), __INT_T(), __LOG_T(), __mth_i_aqanint(), __mth_i_dacos(), __mth_i_dacosd(), __mth_i_dasin(), __mth_i_dasind(), __mth_i_datan(), __mth_i_datand(), __mth_i_datanh(), __mth_i_dcos(), __mth_i_dcosd(), __mth_i_dcosh(), __mth_i_dexp(), __mth_i_dlog(), __mth_i_dlog10(), __mth_i_dqanint(), __mth_i_dsin(), __mth_i_dsind(), __mth_i_dsinh(), __mth_i_dsqrt(), __mth_i_dtan(), __mth_i_dtand(), __mth_i_dtanh(), __mth_i_fabs(), __mth_i_idnint(), __mth_i_iqnint(), __mth_i_kidnnt(), __mth_i_kiqnint(), __mth_i_knint(), __mth_i_nint(), __mth_i_qacosd(), __mth_i_qanint(), __mth_i_qasin(), __mth_i_qasind(), __mth_i_qatan(), __mth_i_qatand(), __mth_i_qatanh(), __mth_i_qcos(), __mth_i_qcosd(), __mth_i_qlog10(), __mth_i_qsin(), __mth_i_qsind(), __mth_i_qtan(), __mth_i_qtand(), __mth_i_qtanh(), __reduction_slowpath(), __rss_log_fma3(), __utl_i_dfix64(), __utl_i_dflt64(), _avail(), _ccff_info(), _check_clean(), _fam(), _printnme(), _sect(), _size_of(), _transform_func(), addn(), advance(), advance_permuted(), appendbigint(), appendhex1(), appendint1(), assign_cval(), atoxd(), block_setup(), build_array_list(), build_dlist(), check_new_bound(), chkstruct(), choose_multiplier(), choose_multiplier_64(), CMPLXFUNC_C_C(), CONCAT(), conv_e(), conv_en(), conv_es(), conv_f(), convert_subscript_in_expr(), cprintf(), cpu(), cyclic_setup(), do_subscript(), dtoufp(), dumpdeflist(), dumpdvl(), dumpdvls(), dumpnme(), ENTF90(), ENTF90COMN(), ENTFTN(), eval_dtio_sb(), eval_sb(), extent_of(), find_assumshp_dep(), finddthash(), fix_datatype(), fr_getreal(), fr_readnum(), fw_writenum(), gen_abs_expr(), gen_constant(), gen_llvm_expr(), get_ftn_cbind_lltype(), get_number(), get_offset_without_dim(), get_scalar_in_expr(), get_token(), hxatoxd(), incr_index(), init_unassociated_pointer_desc(), insert_comm_before(), insert_forall_comm(), insertdthash(), ipa_restore_dtb(), lg(), lg64(), lower_set_symbols(), LZMPLXFUNC_LZ_LZ(), make_lltype_from_sptr(), msg(), name_dependent_check(), parse_d(), plower(), print_loop(), put_int(), putbigint(), putddtype(), putdouble(), putdtype(), putint(), putINT(), putint1(), putint1star(), putnzbigint(), putnzbits(), putnzhex(), putnzint(), putnzINT(), putnzisz(), putpint(), reciprocal_mod(), reciprocal_mod_64(), reduction_slowpath(), remove_from_scalar_subscript(), remove_function_common_from_scalar_subscript(), scalar_communication(), scale_bytes(), scale_kbytes(), scale_of(), Scale_Of(), sectfloat(), semant1(), semant2(), semant3(), semsmp(), set_final_descriptor(), set_preserve_descriptor(), sfloat(), shape_comm_in_expr(), size_ast(), size_ast_of(), size_of(), size_of_array(), subst(), transform_all_call(), transform_ptr(), transform_pure_function(), trav_struct(), unwrap_d(), use_atomic_for_reduction(), use_opt_atomic(), vabs_vd_vd(), vcast_vd_d(), vgetexp_vd_vd(), vgetexp_vf_vf(), vgetmant_vd_vd(), vgetmant_vf_vf(), vilogb2k_vi_vd(), vilogbk_vi2_vf(), vilogbk_vi_vd(), visinf_vo_vd(), visinf_vo_vf(), visminf_vo_vd(), visminf_vo_vf(), visnan_vo_vd(), visnan_vo_vf(), vispinf_vo_vd(), vispinf_vo_vf(), vneg_vd_vd(), vneg_vf_vf(), vnegpos_vd_vd(), vnegpos_vf_vf(), vposneg_vd_vd(), vposneg_vf_vf(), wrap_d(), write_constant_value(), xdabsv(), xdacos(), xdasin(), xdatan(), xdcos(), xdexp(), xdfix(), xdfix64(), xdfixu(), xdfixu64(), xdfloat(), xdfloatu(), xdflt64(), xdfltu64(), xdisint(), xdlog(), xdlog10(), xdneg(), xdrcp(), xdsin(), xdsqrt(), xdtan(), xdtomd(), xdtoq(), xmdtod(), xqtod(), xsngl(), xudiv(), xumod(), ZMPLXFUNC_Z(), ZMPLXFUNC_Z_D(), ZMPLXFUNC_Z_Z(), and zsize_of().
e
e = ((ia >> 23) & 0xff) - 127
Definition at line 23 of file cis_common.h.
Referenced by __attribute__(), __fort_getenv(), __fort_rbcstl(), __fort_rrecvl(), __fort_rsendl(), __fortio_fmt_e(), __fortio_fmt_g(), __fortio_lldecvt(), __fsd_pow_fma3(), __fss_log_fma3(), __fss_pow_fma3(), __fvd_pow_fma3(), __fvd_pow_fma3_256(), __fvs_log_fma3(), __fvs_log_fma3_256(), __fvs_pow_fma3(), __INT8_T(), __INT_T(), __internal_ddadd_yisdouble(), __internal_ddfma(), __reduction_slowpath(), __reduction_slowpath_pio2(), __rss_log_fma3(), __rvs_log_fma3(), __rvs_log_fma3_256(), _is_nand(), _isinfd(), _isinff(), _isnand(), _isnanf(), apply_use(), conv_e(), conv_en(), conv_es(), copy_type_to_entry(), cpu(), dirv_permute(), dovec(), efloor(), ENTF90(), eval_array_constructor(), eval_init_expr(), eval_scale(), fr_readnum(), fw_writenum(), llmd_reverse(), name_dependent_check(), reduction_slowpath(), ref_pd(), rewrite_cmplxpart_rval(), stb_process_iface_chlen(), upper(), vneg_vi2_vi2(), and vneg_vi_vi().
h
p &* h = q
Definition at line 17 of file cis_common.h.
Referenced by __attribute__(), __reduction_slowpath(), __reduction_slowpath_pio2(), __tan_f_vec(), __tan_kernel(), _childsort(), _ichildsort(), _messagesort(), alloc_tables(), find_apte(), finddthash(), findhash(), findindex(), ftn_i_kidim(), get_apte(), getF90TmplSectRtn(), hashmap_alloc(), hashmap_clear(), hashmap_erase(), hashmap_free(), hashmap_insert(), hashmap_iterate(), hashmap_lookup(), hashmap_replace(), hashmap_size(), hashmap_sort(), hashset_alloc(), hashset_clear(), hashset_erase(), hashset_free(), hashset_insert(), hashset_iterate(), hashset_lookup(), hashset_replace(), hashset_size(), have_preheader(), insertdthash(), inserthash(), insertion_point(), is_amd(), is_intel(), newindex(), reduction_slowpath(), rehash(), and search().
hi
hi = 0
Definition at line 22 of file cis_common.h.
Referenced by __reduction_slowpath(), atoui64(), fast2sum(), fast2sum_dp(), for(), gen_acon_expr(), getoperation(), II2L(), manadd(), prng_loop_d_lf(), prng_loop_d_npb(), prng_loop_r_lf(), prng_loop_r_npb(), reduction_slowpath(), ui64toa(), vfast2sum(), vfast2sum_dp(), and vset_vd_d_d().
i
int i
Definition at line 244 of file cis_common.h.
ia
ia = float_as_int(a)
Definition at line 20 of file cis_common.h.
Referenced by __reduction_slowpath(), __reduction_slowpath_pio2(), cexp_scalar_default_abi(), for(), and reduction_slowpath().
idx
idx = 4 - ((e >> 5) & 3)
Definition at line 24 of file cis_common.h.
Referenced by __attribute__(), __fort_fetch_int_element(), __fort_get_scalar(), __fort_global_reduce(), __fort_i64toax(), __fort_local_address(), __fort_local_offset(), __fort_set_single(), __fort_store_int_element(), __fortio_ecvt(), __fortio_fcvt(), __get_size_of(), __INT_T(), __LOG_T(), __reduction_slowpath(), __reduction_slowpath_pio2(), __rss_log_fma3(), annomod_initx(), apply_gep_index(), change_forall_triple(), check_ccon(), check_sc(), direct_import(), dumpsubinfo(), ENTFTN(), fastset_add(), fastset_contains(), fastset_get(), fastset_internal_drop_at(), fastset_intersection(), fastset_member_index(), fastset_remove(), find_idx(), forall_make_same_idx(), fr_OZreadnum(), fr_read(), fr_read_record(), fr_readnum(), gen_acon_expr(), gen_extract_value(), gen_extract_value_ll(), gen_extract_vector(), gen_insert_vector(), gen_llvm_cmpxchg_component(), generate_hcycliclp(), generate_hlocalizebnds(), get_lexical_block_info(), i32tos(), is_avail_expr_with_list(), is_fusable(), is_same_idx(), ll_get_atomic_memorder(), ll_get_atomic_opr(), ll_get_const_gep(), lldbg_assign_lexical_block(), lldbg_assign_lexical_blocks(), lldbg_emit_lexical_blocks(), lldbg_emit_line(), lldbg_get_var_line(), lldbg_reserve_lexical_blocks(), llmp_add_shared_var(), llmp_add_shared_var_charlen(), llmp_task_add_private(), make_constval32_op(), make_module_common(), make_rte_descriptor(), print_tmp_name(), rd_dir(), reduction_slowpath(), semant1(), and variable_offset_in_aggregate().
lo
uint32_t lo
Definition at line 22 of file cis_common.h.
Referenced by __reduction_slowpath(), atoui64(), fast2sum(), fast2sum_dp(), for(), gen_acon_expr(), getoperation(), II2L(), manadd(), prng_loop_d_lf(), prng_loop_d_npb(), prng_loop_r_lf(), prng_loop_r_npb(), reduction_slowpath(), ui64toa(), vfast2sum(), vfast2sum_dp(), and vset_vd_d_d().
m
vfloat vopmask m
Initial value:
{
    vfloat in = x
Definition at line 240 of file cis_common.h.
Referenced by __vcis_kernel(), and for().
p
p = (uint64_t)result[idx + 2] << 32
Definition at line 50 of file cis_common.h.
Referenced by __abort(), __abort_init(), __abort_sig_hand(), __aligned_free(), __alloc04(), __attribute__(), __auto_alloc(), __dump_loop(), __f90io_ldw(), __fcvt(), __fort_adjbase(), __fort_alloc(), __fort_atol(), __fort_calloc(), __fort_calloc_without_abort(), __fort_coord_to_procnum(), __fort_dealloc(), __fort_dealloc03(), __fort_defaultproc(), __fort_describe_replication(), __fort_ebcopys(), __fort_getdir(), __fort_gethostname(), __fort_getopt(), __fort_getoptb(), __fort_getoptn(), __fort_initcom(), __fort_initopt(), __fort_istat(), __fort_kalloc(), __fort_kred_scalarlk(), __fort_lcm(), __fort_localize(), __fort_malloc(), __fort_malloc_without_abort(), __fort_par_open(), __fort_passarg(), __fort_realloc(), __fort_red_scalar(), __fort_red_scalarlk(), __fort_sethand(), __fort_trac_init(), __fort_traceback(), __fort_tracecall(), __fortio_alloc_fcb(), __fortio_cleanup_fcb(), __fortio_default_convert(), __fortio_find_unit(), __fortio_fmt_f(), __fortio_fmt_g(), __fortio_fmt_i(), __fortio_fmt_i8(), __fortio_free_fcb(), __fortio_strtod(), __fortio_swap_bytes(), __fortio_trunc(), __fss_acos_fma3(), __fss_asin_fma3(), __getfile3f(), __INT8_T(), __INT_T(), __io_clearerr(), __io_feof(), __io_ferror(), __io_getc(), __io_putc(), __io_tempnam(), __isatty3f(), __math_dispatch(), __reduction_slowpath(), __reduction_slowpath_pio2(), __tan_f_vec(), __vcis_d_kernel(), __vcis_kernel(), _adjustl(), _adjustr(), _dump_node(), _f90io_encode_fmt(), _get_token(), _len_trim(), _mp_calloc(), _mp_free(), _mp_malloc(), _mp_realloc(), _nextline(), _rd_tkline(), _rd_token(), _rdfo(), _readln(), _repeat(), _selected_char_kind(), _trim(), _write_token(), accpp(), ad2ilm(), ad3ilm(), ad4ilm(), ad5ilm(), add(), add_biv_def(), add_dep(), add_empty_succ(), add_ilms(), add_loop_preheader(), add_lpexit(), add_pred(), add_succ(), add_to_common(), add_to_malf(), add_to_private_mod_list(), add_to_region(), addilt(), addn(), addnewbih(), addpte(), adNilm(), all_zeroes(), annomod_asm(), annomod_initx(), append_succ(), assign(), asy_wait(), atoxufp(), ch_substring(), check_alias(), check_bounds(), check_ccon(), check_outer_parens(), check_sc(), chk_expr(), chk_var(), chkref(), cleanup_unneeded_sincos_calls(), cntl_name(), compare_one_bound(), Conflict_(), const_eval(), const_fold(), constants_hash(), conv_e(), conv_en(), conv_es(), conv_int(), conv_int8(), convert_2dollar_signs_to_hyphen(), copy_xfer(), cprintf(), crunch(), ctime_c(), cvt(), dd_edge(), dd_succ(), deallocate_arg_value(), delete(), dfs(), dinit(), dinit_data(), dinit_eval(), dinits(), dirv_print(), dlist(), dmp_all_anno(), dmp_socs(), dodef(), doincl(), dominators(), dump_dd(), dump_dinit_chain(), dump_dinit_structure(), dump_global(), dump_ilt(), dump_ind(), dump_mth_rt_vi_ptrs(), dump_one_bound(), dump_two_bound(), dumploop(), dumpval(), e113toe(), e74_arg(), ecmp(), edivm(), ef_getnum(), ef_nextchar(), ef_putiotype(), ef_putstring(), ef_putvlist(), efloor(), efunc(), emit_str(), emovi(), emovo(), emulm(), enan(), enormlz(), ENT3F(), ENTF90(), ENTF90IO(), ENTFTN(), ENTRY(), errfill(), error(), eshdn6(), eshift(), eshup6(), etoasc(), eval(), eval_adjustl(), eval_adjustr(), eval_do_idx(), eval_len_trim(), eval_null(), eval_repeat(), eval_trim(), exp_addbih(), exp_mac(), export_all(), export_append_host_sym(), export_append_sym(), export_fix_host_append_list(), export_header(), export_host_subprogram(), export_module_subprogram(), export_public_module(), export_symbol(), ff_get_noncomment(), ff_get_stmt(), ff_prescan(), ff_read_card(), fillin_succ(), find_bivs(), find_idx(), findloop(), fix_module_common(), flushsym(), fma_rewrite(), fndpath(), fpp(), fr_Breadnum(), fr_getreal(), fr_intern_init(), fr_read_record(), freearea(), frte_func(), Ftn_str_free(), Ftn_str_malloc(), Ftn_str_malloc_klen(), fw_Bwritenum(), fw_OZwritenum(), fw_write_item(), fw_writenum(), gen_deallocate_arrays(), gen_dtio_arglist(), gen_dtio_args(), gen_spec_item_tmp(), gentmp(), get_anno_line(), get_component_init(), get_csed_operand(), get_cstring(), get_defined_io_call(), get_fmt_array(), get_fmtstr(), get_fn(), get_highest_param_offset(), get_id_name(), get_ili(), get_literal(), get_llvm_name(), get_llvm_sname(), get_msize(), get_next_sym(), get_next_sym_dt(), get_num(), get_number(), get_stmt(), get_struct_from_dsrt2(), get_template_expansion(), getbit(), getbits(), getcharconst(), getdddir(), getdtype(), getextfuncname(), getict(), getitem(), getivl(), getoperation(), getopt_abort(), getsname(), getstring(), hex2char(), hex2nchar(), hlv_getsym(), holtonum(), if(), ili_init(), import(), import_header_only(), import_skip_use_stmts(), import_use_stmts(), init(), init_fold_const(), inlist(), insertion_point(), intermediate_members(), is_biv(), is_biv_store(), is_equivalence(), is_lineblank(), is_repeat_count(), is_tail_aexe(), kanji_char(), kanji_len(), kanji_prefix(), keyword(), line_directive(), list_init(), live_var(), live_var_end(), ll_get_const_gep(), ll_get_md_rawstring(), LLABI_find_array_type_def(), LLABI_find_su_type_def(), lldbg_alloc(), llObjtodbgPush(), llutil_alloc(), llutil_strdup(), localflow(), lookup(), lower_add_func_call(), lower_set_symbols(), lower_sym_header(), m16m(), make_equiv_ss(), manmul(), mergesrt(), mkfname(), mkfunc_sflags(), mod_fini(), mth_i_dtanh(), mth_i_tanh(), need_cdata(), new_du_ud(), nextok(), nml_equiv(), nullify(), open_files(), pbstr(), pgio_ecvt(), postdominators(), predarg(), print_int(), prntstl(), proc_setup(), process_dsrt(), prsym(), pruneAcon(), ptr_asgn(), push_include(), put_anno_line(), put_getitem_p(), put_kstr(), put_ncharstring_n(), put_string_n(), putmac(), queue_symbol(), rb_free(), rdfs(), rdilts(), reaching_defs(), read_card(), read_record(), reduction_slowpath(), reloc_ilms(), remove_dead_sincos_calls(), replace_ast_subtree(), reserve_buffer(), rm_edge(), save_ilms(), save_ilms0(), scan_include(), scan_ind_uses(), scan_options(), sccalloc(), search(), semant1(), stb_lower_sym_header(), store_return_value_for_entry(), string_hash(), subst(), sym_get_arg_sec(), sym_get_sec(), sym_strsave(), symdentry(), top_sort(), trace(), trans_clridx(), trans_mkdescr(), trimContIdx(), undo_recip_div(), upcase_name(), use_before_def(), util_error(), visit_list_free(), vloadu_vi2_p(), vloadu_vi_p(), vol_equiv(), vstoreu_v_p_vi(), vstoreu_v_p_vi2(), wrilms(), wrilts(), write_constant_value(), write_instructions(), write_item(), write_nml_val(), write_operand(), write_operands(), and xargvar().
q
q = (p >> 32) & 0xE0000000
Definition at line 25 of file cis_common.h.
Referenced by __aligned_malloc(), __dump_loop(), __fort_atol(), __fort_ebcopys(), __fort_fixmnt(), __fort_getopt(), __fort_getoptn(), __fort_initcom(), __fort_initopt(), __fort_kred_scalarlk(), __fort_par_open(), __fort_red_scalar(), __fort_red_scalarlk(), __fort_sethand(), __fort_trac_init(), __fortio_free_fcb(), __fortio_open(), __fortio_strtod(), __fsd_pow_fma3(), __fvd_pow_fma3(), __fvd_pow_fma3_256(), __mth_i_qacos(), __mth_i_qacosd(), __mth_i_qasind(), __mth_i_qatan2d(), __mth_i_qatand(), __mth_i_qcosd(), __mth_i_qexp(), __mth_i_qgamma(), __mth_i_qlog(), __mth_i_qlog_gamma(), __mth_i_qsind(), __mth_i_qsqrt(), __mth_i_qtand(), __reduction_slowpath(), __reduction_slowpath_pio2(), _mp_realloc(), _rd_token(), _readln(), add(), add_loop_preheader(), append_succ(), atoxq(), bld_lhs(), ceilg(), check_bounds(), check_outer_parens(), collapse_index(), CONCAT(), const_fold(), const_prop(), convert_2dollar_signs_to_hyphen(), copy_const(), delete(), dmp_socs(), do_subscript(), dodef(), dump_ilt(), dump_two_bound(), dumploop(), e74_arg(), ecmp(), ef_putdt(), ef_putiotype(), ef_putstring(), emovi(), emovo(), emulm(), ENT3F(), ENTF90(), findloop(), floorg(), flowgraph(), for(), freearea(), Ftn_str_malloc(), Ftn_str_malloc_klen(), fw_write_item(), gen_llvm_expr(), gentmp(), get_fmtstr(), get_llvm_name(), get_temp_forall2(), getextfuncname(), getitem(), getopt_abort(), getsname(), hxatoxq(), init(), init_fold_const(), insertsrt(), is_repeat_count(), is_sym_invariant_safe(), is_sym_live_safe(), is_sym_optsafe(), live_var(), lookup(), make_seq_temp_array(), merge(), mergesrt(), mod_fini(), mth_i_alog(), mth_i_atan(), mth_i_atan2(), mth_i_datan(), mth_i_dlog(), mth_i_log(), parse_q(), partition_blocks(), rb_free(), reciprocal_division(), reciprocal_division_64(), reduction_slowpath(), save_ilms(), save_ilms0(), scan_include(), sccalloc(), sccrelal(), skipws(), subst(), symbolic_divide(), uninit_var(), unwrap_q(), wrap_q(), xdtoq(), xftoq(), xqabsv(), xqacos(), xqasin(), xqatan(), xqcos(), xqexp(), xqfix(), xqfix64(), xqfixu(), xqfixu64(), xqfloat(), xqfloatu(), xqflt64(), xqfltu64(), xqlog(), xqlog10(), xqneg(), xqsin(), xqsqrt(), xqtan(), xqtod(), and xqtof().
r
return r = (float)d
Definition at line 72 of file cis_common.h.
Referenced by __attribute__(), __erf(), __erfc(), __fort_chn_1to1(), __fort_comm_merge(), __fort_describe_replication(), __fort_next_owner(), __fort_print_scalar(), __fort_recvl(), __INT8_T(), __INT_T(), __mth_i_dsign(), __mth_i_dsincos(), __mth_i_kdiv(), __mth_i_sign(), __mth_i_sincos(), __mth_i_ukdiv(), __pg_delete_lock_file(), __pg_get_lock(), __pg_make_lock_file(), __pg_release_lock(), __pgcpuid(), __pgi_cpuid(), __pgi_cpuid_ecx(), __pgi_getbv(), __reduction_slowpath(), __reduction_slowpath_pio2(), __tan_f_vec(), __tan_kernel(), __utl_i_mul64(), __ZGVxM2v__mth_i_vr8(), __ZGVxM2v__mth_i_vr8si4(), __ZGVxM2v__mth_i_vr8si8(), __ZGVxM2vv__mth_i_vr8vi4(), __ZGVxM2vv__mth_i_vr8vi8(), __ZGVxM2vv__mth_i_vr8vr8(), __ZGVxM4v__mth_i_vr4(), __ZGVxM4v__mth_i_vr4si4(), __ZGVxM4v__mth_i_vr4si8(), __ZGVxM4vv__mth_i_vr4vi4(), __ZGVxM4vv__mth_i_vr4vi8(), __ZGVxM4vv__mth_i_vr4vr4(), __ZGVxN2v__mth_i_vr8(), __ZGVxN2v__mth_i_vr8si4(), __ZGVxN2v__mth_i_vr8si8(), __ZGVxN2vv__mth_i_vr8vi4(), __ZGVxN2vv__mth_i_vr8vi8(), __ZGVxN2vv__mth_i_vr8vr8(), __ZGVxN4v__mth_i_vr4(), __ZGVxN4v__mth_i_vr4si4(), __ZGVxN4v__mth_i_vr4si8(), __ZGVxN4vv__mth_i_vr4vi4(), __ZGVxN4vv__mth_i_vr4vi8(), __ZGVxN4vv__mth_i_vr4vr4(), __ZGVyM4v__mth_i_vr8(), __ZGVyM4v__mth_i_vr8si4(), __ZGVyM4v__mth_i_vr8si8(), __ZGVyM4vv__mth_i_vr8vi4(), __ZGVyM4vv__mth_i_vr8vi8(), __ZGVyM4vv__mth_i_vr8vr8(), __ZGVyM8v__mth_i_vr4(), __ZGVyM8v__mth_i_vr4si4(), __ZGVyM8v__mth_i_vr4si8(), __ZGVyM8vv__mth_i_vr4vi4(), __ZGVyM8vv__mth_i_vr4vi8(), __ZGVyM8vv__mth_i_vr4vr4(), __ZGVyN4v__mth_i_vr8(), __ZGVyN4v__mth_i_vr8si4(), __ZGVyN4v__mth_i_vr8si8(), __ZGVyN4vv__mth_i_vr8vi4(), __ZGVyN4vv__mth_i_vr8vi8(), __ZGVyN4vv__mth_i_vr8vr8(), __ZGVyN8v__mth_i_vr4(), __ZGVyN8v__mth_i_vr4si4(), __ZGVyN8v__mth_i_vr4si8(), __ZGVyN8vv__mth_i_vr4vi4(), __ZGVyN8vv__mth_i_vr4vi8(), __ZGVyN8vv__mth_i_vr4vr4(), __ZGVzM16v__mth_i_vr4(), __ZGVzM16v__mth_i_vr4si4(), __ZGVzM16v__mth_i_vr4si8(), __ZGVzM16vv__mth_i_vr4vi4(), __ZGVzM16vv__mth_i_vr4vi8(), __ZGVzM16vv__mth_i_vr4vr4(), __ZGVzM8v__mth_i_vr8(), __ZGVzM8v__mth_i_vr8si4(), __ZGVzM8v__mth_i_vr8si8(), __ZGVzM8vv__mth_i_vr8vi4(), __ZGVzM8vv__mth_i_vr8vi8(), __ZGVzM8vv__mth_i_vr8vr8(), __ZGVzN16v__mth_i_vr4(), __ZGVzN16v__mth_i_vr4si4(), __ZGVzN16v__mth_i_vr4si8(), __ZGVzN16vv__mth_i_vr4vi4(), __ZGVzN16vv__mth_i_vr4vi8(), __ZGVzN16vv__mth_i_vr4vr4(), __ZGVzN8v__mth_i_vr8(), __ZGVzN8v__mth_i_vr8si4(), __ZGVzN8v__mth_i_vr8si8(), __ZGVzN8vv__mth_i_vr8vi4(), __ZGVzN8vv__mth_i_vr8vi8(), __ZGVzN8vv__mth_i_vr8vr8(), _messagecmp(), _messagesort(), _numeric(), _olap_conflict(), _rb_walk(), _sect(), _template(), _transform_func(), ad_free(), advance(), advance_permuted(), allocate_one_auto(), appendbigint(), appendint1(), appendstring1(), appendsym1(), bv_mem(), bv_off(), bv_set(), CMPLXFUNC_C_C(), CMPLXFUNC_C_F(), collapse_index(), combine_fdiv(), Conflict_(), convert_subscript_in_expr(), cos_piby4(), cpu(), dodef(), e113toe(), emdnorm(), ENTF90(), ENTFTN(), etoasc(), eval_merge(), eval_selected_char_kind(), eval_selected_int_kind(), eval_selected_real_kind(), exp_ac(), fix_array_fields(), form_cmplx_const(), freefield(), fused_multiply_add_candidate(), fused_multiply_add_canonical_form(), gathscat_maxval_int1(), gathscat_maxval_int2(), gathscat_maxval_int4(), gathscat_maxval_int8(), gathscat_maxval_real16(), gathscat_maxval_real4(), gathscat_maxval_real8(), gathscat_minval_int1(), gathscat_minval_int2(), gathscat_minval_int4(), gathscat_minval_int8(), gathscat_minval_real16(), gathscat_minval_real4(), gathscat_minval_real8(), gcd(), get_default_int_val(), get_mac_name(), get_scalar_in_expr(), getF90TmplSectRtn(), ia_cachesize(), ia_cores(), ia_unifiedcache(), iadd_ovf(), ICON(), idcache(), insert_comm_before(), insert_forall_comm(), insertsrt(), is_hoistable(), is_known_bug(), is_mask_for_rhs(), is_ordered(), is_same_mask(), is_std_hoistable(), isub_ovf(), ll_get_outlined_funcname(), lower_put_datatype(), LZMPLXFUNC_LZ_LZ(), maybe_generate_fma(), merge(), mergesrt(), mk_shape_intrin(), mk_ulbound_intrin(), mth_dsincos(), mth_i_alog(), mth_i_atan2(), mth_i_cos(), mth_i_datan2(), mth_i_dcos(), mth_i_dlog(), mth_i_dsin(), mth_i_dtan(), mth_i_log(), mth_i_sin(), mth_i_tan(), mth_sincos(), pg_makenewdir(), pg_makenewfile(), pg_newfile(), pointer_squeezer(), points_to(), print_row(), put_getitem_p(), putdty(), putdtypex(), qscmp(), rb_find(), rb_walk(), reduction_slowpath(), remove_flow_list(), rewrite_func_ast(), rewrite_sub_ast(), scalar_communication(), scatter_maxval_int1(), scatter_maxval_int2(), scatter_maxval_int4(), scatter_maxval_int8(), scatter_maxval_real16(), scatter_maxval_real4(), scatter_maxval_real8(), scatter_minval_int1(), scatter_minval_int2(), scatter_minval_int4(), scatter_minval_int8(), scatter_minval_real16(), scatter_minval_real4(), scatter_minval_real8(), set_assumed_bounds(), set_descriptor_rank(), set_ilmpos(), shape_comm_in_expr(), sin_piby4(), stg_add_freelist(), stg_clear(), stg_clear_force(), stg_next(), stg_next_freelist(), stg_return(), subst(), tag_forall_comm(), tan_piby4(), tanf_piby4(), tobinary(), tobinary64(), top_sort(), transform_all_call(), transform_pure_function(), ufptod(), ufptof(), verify_compatible(), widenPushdown(), xdabsv(), xdacos(), xdadd(), xdasin(), xdatan(), xdatan2(), xdble(), xdcos(), xddiv(), xdexp(), xdlog(), xdlog10(), xdmul(), xdneg(), xdpow(), xdrcp(), xdsin(), xdsqrt(), xdsub(), xdtan(), xfabsv(), xfacos(), xfadd(), xfasin(), xfatan(), xfatan2(), xfcos(), xfdiv(), xfexp(), xflog(), xflog10(), xfmul(), xfneg(), xfpow(), xfrcp(), xfsin(), xfsqrt(), xfsub(), xftan(), xqabsv(), xqacos(), xqadd(), xqasin(), xqatan(), xqatan2(), xqcos(), xqdiv(), xqexp(), xqlog(), xqlog10(), xqmul(), xqneg(), xqpow(), xqsin(), xqsqrt(), xqsub(), xqtan(), xqtof(), xsngl(), xudiv(), xumod(), and ZMPLXFUNC_Z_Z().
res
return res = vSETf(0.0f)
Definition at line 243 of file cis_common.h.
result
result[q] = hi
Definition at line 21 of file cis_common.h.
Referenced by __attribute__(), __ldexp_d_scalar_kernel(), __ldexpf_scalar_kernel(), __mth_i_derfc_scaled(), __mth_i_erfc_scaled(), __mth_i_kdiv(), __mth_i_kicshft(), __mth_i_kishft(), __mth_i_ukdiv(), __mth_i_ukicshft(), __reduction_slowpath_pio2(), __utl_i_add64(), __utl_i_div64(), __utl_i_mul64(), __utl_i_sub64(), __utl_i_udiv64(), __vldexp_manual(), __vldexpf_manual(), _adjustl(), _adjustr(), _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_mp_atomic_write(), _len_trim(), _repeat(), _trim(), add128(), add64(), and64(), call_format_double(), cngcon(), collectIncludePaths(), CONCAT(), Conflict_(), const_fold(), contains_ast(), contains_forall_index(), contains_sptr(), convert_cnst(), create_atomic_capture_seq(), div128(), div64(), do_eval_minval_or_maxval(), emit_scatterx(), emit_scatterx_gatherx(), emit_sum_scatterx(), ENTF90(), ENTFTN(), eval_fltconvert(), eval_int(), eval_len_trim(), eval_merge(), eval_repeat(), exp64(), exp_mp_atomic_capture(), exp_mp_atomic_update(), find_lhs_on_rhs_conflict(), find_rhs_conflict(), for(), ftn_i_bktest(), ftn_i_kibclr(), ftn_i_kibits(), ftn_i_kibset(), Ftn_izext(), Ftn_jzext(), fw_writenum(), gen_llvm_atomicrmw_expr(), gen_llvm_cmpxchg_component(), gen_mulh_expr(), get_derived_iolptrs(), get_offset_without_dim(), ILI_ccOPND(), init_fold_const(), init_negate_const(), inline_shifts(), int128_and(), int128_from_int64(), int128_from_uint64(), int128_ones_complement(), int128_or(), int128_shift_left(), int128_shift_right_logical(), int128_signed_add(), int128_signed_subtract(), int128_to_int64(), int128_to_uint64(), int128_twos_complement(), int128_unsigned_add(), int128_xor(), is_another_shift(), is_array_type(), is_same_array_shape(), lhs_needtmp(), ll_make_atomic_compare_xchg(), ll_make_atomic_load(), ll_make_atomic_store(), mul128l(), mul64(), mul64_10(), neg64(), negate_const(), negate_const_be(), no_data_components(), NORM2_REAL4(), NORM2_REAL8(), not64(), or64(), permute_axis(), reduction_slowpath(), search_type_members(), search_type_members_wrapped(), set_cmplx(), set_cmplxd(), set_dcmplx(), shf128(), shf128by1(), shf64(), stride_1_norm2_real4(), stride_1_norm2_real8(), sub128(), sub64(), test_sym_and_components(), uadd64(), udiv64(), umul64(), umul64_10(), uneg64(), unwrap_i128(), ushf64(), usub64(), visit_ili_operands(), and xor64().
vlen
const int vlen = sizeof(vfloat) / sizeof(float _Complex)
Definition at line 245 of file cis_common.h.
w
* w
Initial value:
{
    uint2 m
Definition at line 17 of file cis_common.h.
Referenced by __attribute__(), __fortio_fmt_d(), __fortio_fmt_e(), __fortio_fmt_f(), __fortio_fmt_g(), __vcis_d_kernel(), __vcis_kernel(), _rdfo(), bv_count(), bv_mem(), bv_off(), bv_print(), bv_set(), CMPLXFUNC_C_C(), conv_f(), dfs(), dominators(), ENTF90(), etoasc(), fr_Breadnum(), fr_getreal(), fr_intern_init(), fr_OZconv_init(), fr_OZreadnum(), fr_read(), fr_readnum(), fw_Bwritenum(), fw_OZwritenum(), fw_writenum(), int128_count_leading_zeros(), ipa_restore_dtb(), is_dominator(), is_post_dominator(), lv_print(), LZMPLXFUNC_LZ_LZ(), postdominators(), rdfs(), sign_extend(), and ZMPLXFUNC_Z_Z().