flang: close.c File Reference
close.c File Reference
Implements Fortran CLOSE statement.
#include <errno.h>
#include "global.h"
#include <unistd.h>
#include "stdioInterf.h"
Functions
int __fortio_close (FIO_FCB *f, int flag)
static int _f90io_close (__INT_T *unit, __INT_T *bitv, __INT_T *iostat, char *status, __CLEN_T status_siz)
__INT_T (__INT_T *unit, __INT_T *bitv, __INT_T *iostat, DCHAR(status) DCLEN64(status))
__INT_T (__INT_T *unit, __INT_T *bitv, __INT_T *iostat, DCHAR(status) DCLEN(status))
void __fortio_cleanup (void)
IO cleanup routine.
Detailed Description
Implements Fortran CLOSE statement.
Definition in file close.c.
Function Documentation
__fortio_cleanup()
void __fortio_cleanup (void)
IO cleanup routine.
Runtime library IO cleanup routine; do whatever in neccessary to clean up open files.
Definition at line 180 of file close.c.
References __fort_access, __fort_barrier(), __fort_unlink, __fortio_cleanup_fcb(), __fortio_close(), __io_fflush, fcb::dispose, f, FIO_TBL::fcbs, FIO_DELETE, FIO_SCRATCH, fioFcbTbls, fcb::fp, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, fcb::name, fcb::next, NULL, fcb::status, and fcb::stdunit.
Referenced by term().
__fortio_close()
int __fortio_close (FIO_FCB * f, int flag)
brief Fortran file close
Parameters
f 0 (use default stream)
flag FIO_KEEP, FIO_DELETE
Definition at line 35 of file close.c.
References __fort_access, __fort_unlink, __fortio_error(), __fortio_free_fcb(), __io_binary_mode(), __io_errno(), __io_fclose, __io_ferror(), __io_fflush, __io_fputc(), fcb::dispose, f, FALSE, FIO_DELETE, FIO_EREADONLY, FIO_SCRATCH, fcb::fp, fcb::name, fcb::nonadvance, fcb::status, fcb::stdunit, and fcb::unit.
Referenced by __fortio_cleanup(), __fortio_open(), and _f90io_close().
__INT_T() [1/2]
__INT_T (__INT_T * unit, __INT_T * bitv, __INT_T * iostat, DCHAR(status) DCLEN(status))
Definition at line 142 of file close.c.
References __CLEN_T, bitv, CADR, CLEN, and ENTF90IO.
__INT_T() [2/2]
__INT_T (__INT_T * unit, __INT_T * bitv, __INT_T * iostat, DCHAR(status) DCLEN64(status))
Definition at line 119 of file close.c.
References __CLEN_T, __fort_status_init(), __fortio_errend03(), _f90io_close(), bitv, CADR, CLEN, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, ISPRESENTC, LOCAL_MODE, n, NULL, p, and s.
_f90io_close()
static int _f90io_close (__INT_T * unit, __INT_T * bitv, __INT_T * iostat, char * status, __CLEN_T status_siz) static
Definition at line 83 of file close.c.
References __fortio_close(), __fortio_eq_str(), __fortio_errinit03(), __fortio_error(), __fortio_find_unit(), fcb::acc, bitv, f, FIO_DELETE, FIO_ECOMPAT, FIO_EREADONLY, FIO_ESPEC, FIO_EUNIT, FIO_KEEP, FIO_READ, FIO_SCRATCH, ILLEGAL_UNIT, NULL, and fcb::status.
Referenced by __INT_T().