flang: cnfg.h File Reference
cnfg.h File Reference
cnfg.h - declare external variables/arrays used by Fortran I/O
Classes
struct FIO_CNFG
Macros
#define GET_FIO_CNFG_DEFAULT_NAME __fortio_cnfg_.default_name
#define GET_FIO_CNFG_TRUE_MASK __fortio_cnfg_.true_mask
#define GET_FIO_CNFG_TRUE_MASK_ADDR &__fortio_cnfg_.true_mask
#define GET_FIO_CNFG_FTN_TRUE __fortio_cnfg_.ftn_true
#define GET_FIO_CNFG_FTN_TRUE_ADDR &__fortio_cnfg_.ftn_true
Functions
void __fortio_scratch_name (char *, int)
Variables
FIO_CNFG __fortio_cnfg_
Detailed Description
cnfg.h - declare external variables/arrays used by Fortran I/O
Definition in file cnfg.h.
Macro Definition Documentation
GET_FIO_CNFG_DEFAULT_NAME
#define GET_FIO_CNFG_DEFAULT_NAME __fortio_cnfg_.default_name
Definition at line 39 of file cnfg.h.
GET_FIO_CNFG_FTN_TRUE
#define GET_FIO_CNFG_FTN_TRUE __fortio_cnfg_.ftn_true
Definition at line 42 of file cnfg.h.
GET_FIO_CNFG_FTN_TRUE_ADDR
#define GET_FIO_CNFG_FTN_TRUE_ADDR &__fortio_cnfg_.ftn_true
Definition at line 43 of file cnfg.h.
GET_FIO_CNFG_TRUE_MASK
#define GET_FIO_CNFG_TRUE_MASK __fortio_cnfg_.true_mask
Definition at line 40 of file cnfg.h.
GET_FIO_CNFG_TRUE_MASK_ADDR
#define GET_FIO_CNFG_TRUE_MASK_ADDR &__fortio_cnfg_.true_mask
Definition at line 41 of file cnfg.h.
Function Documentation
__fortio_scratch_name()
void __fortio_scratch_name (char * filename, int unit)
Definition at line 71 of file cnfg.c.
References __io_tempnam(), filename, and getenv().
Referenced by __fortio_open().
Variable Documentation
__fortio_cnfg_
FIO_CNFG __fortio_cnfg_ extern
Definition at line 31 of file cnfg.c.
Referenced by __get_fio_cnfg_default_name(), __get_fio_cnfg_ftn_true(), __get_fio_cnfg_ftn_true_addr(), __get_fio_cnfg_true_mask(), and __get_fio_cnfg_true_mask_addr().