flang: cnfg.c File Reference
cnfg.c File Reference
#include "cnfg.h"
#include <string.h>
#include <stdlib.h>
#include "stdioInterf.h"
Functions
const char * __get_fio_cnfg_default_name (void)
int __get_fio_cnfg_true_mask (void)
int * __get_fio_cnfg_true_mask_addr (void)
int __get_fio_cnfg_ftn_true (void)
int * __get_fio_cnfg_ftn_true_addr (void)
void __fortio_scratch_name (char *filename, int unit)
Variables
FIO_CNFG __fortio_cnfg_
Function Documentation
__fortio_scratch_name()
void __fortio_scratch_name (char * filename, int unit)
Definition at line 71 of file cnfg.c.
References __io_tempnam(), filename, and getenv().
Referenced by __fortio_open().
__get_fio_cnfg_default_name()
const char * __get_fio_cnfg_default_name (void)
Definition at line 41 of file cnfg.c.
References __fortio_cnfg_, and FIO_CNFG::default_name.
__get_fio_cnfg_ftn_true()
int __get_fio_cnfg_ftn_true (void)
Definition at line 59 of file cnfg.c.
References __fortio_cnfg_, and FIO_CNFG::ftn_true.
__get_fio_cnfg_ftn_true_addr()
int * __get_fio_cnfg_ftn_true_addr (void)
Definition at line 65 of file cnfg.c.
References __fortio_cnfg_, and FIO_CNFG::ftn_true.
__get_fio_cnfg_true_mask()
int __get_fio_cnfg_true_mask (void)
Definition at line 47 of file cnfg.c.
References __fortio_cnfg_, and FIO_CNFG::true_mask.
__get_fio_cnfg_true_mask_addr()
int * __get_fio_cnfg_true_mask_addr (void)
Definition at line 53 of file cnfg.c.
References __fortio_cnfg_, and FIO_CNFG::true_mask.
Variable Documentation
__fortio_cnfg_
FIO_CNFG __fortio_cnfg_
Initial value:
= {
    "fort.%d",
    1,
    -1,
}
Definition at line 31 of file cnfg.c.
Referenced by __get_fio_cnfg_default_name(), __get_fio_cnfg_ftn_true(), __get_fio_cnfg_ftn_true_addr(), __get_fio_cnfg_true_mask(), and __get_fio_cnfg_true_mask_addr().