flang: commopt.h File Reference
commopt.h File Reference
macros, definitions, and prototypes for communications module
Classes
struct CTYPE
union FTABLE
struct FT
struct FTB
struct OPTSUM
Macros
#define MAXFUSE 10
#define MAXOMEM 40
#define FT_STD(i) ftb.base[i].std
#define FT_FORALL(i) ftb.base[i].fall
#define FT_GETSCLR_SAME(i) ftb.base[i].f.getsclr.same
#define FT_GETSCLR_REUSE(i) ftb.base[i].f.getsclr.reuse
#define FT_GETSCLR_NOMEM(i) ftb.base[i].f.getsclr.nomem
#define FT_GETSCLR_OMEM(i, j) ftb.base[i].f.getsclr.omem[j]
#define FT_GETSCLR_OMEMED(i) ftb.base[i].f.getsclr.omemed
#define FT_BND_LHS(i) ftb.base[i].f.bnd.lhs
#define FT_BND_IDX(i) ftb.base[i].f.bnd.idx
#define FT_BND_SAME(i) ftb.base[i].f.bnd.same
#define FT_BND_CALL(i) ftb.base[i].f.bnd.call
#define FT_ALLOC_SPTR(i) ftb.base[i].f.alloc.sptr
#define FT_ALLOC_FREE(i) ftb.base[i].f.alloc.free
#define FT_ALLOC_SAME(i) ftb.base[i].f.alloc.same
#define FT_ALLOC_OUT(i) ftb.base[i].f.alloc.out
#define FT_ALLOC_REUSE(i) ftb.base[i].f.alloc.reuse
#define FT_ALLOC_USED(i) ftb.base[i].f.alloc.used
#define FT_ALLOC_PTASGN(i) ftb.base[i].f.alloc.ptasgn
#define FT_SECT_ARR(i) ftb.base[i].f.sect.arr
#define FT_SECT_SPTR(i) ftb.base[i].f.sect.sptr
#define FT_SECT_ALLOC(i) ftb.base[i].f.sect.alloc
#define FT_SECT_FREE(i) ftb.base[i].f.sect.free
#define FT_SECT_FLAG(i) ftb.base[i].f.sect.flag
#define FT_SECT_SAME(i) ftb.base[i].f.sect.same
#define FT_SECT_OUT(i) ftb.base[i].f.sect.out
#define FT_SECT_REUSE(i) ftb.base[i].f.sect.reuse
#define FT_CCOPY_ALLOC(i) ftb.base[i].f.ccopy.alloc
#define FT_CCOPY_LHS(i) ftb.base[i].f.ccopy.lhs
#define FT_CCOPY_RHS(i) ftb.base[i].f.ccopy.rhs
#define FT_CCOPY_TSPTR(i) ftb.base[i].f.ccopy.sptr
#define FT_CCOPY_SECTL(i) ftb.base[i].f.ccopy.sectl
#define FT_CCOPY_SECTR(i) ftb.base[i].f.ccopy.sectr
#define FT_CCOPY_USELHS(i) ftb.base[i].f.ccopy.uselhs
#define FT_CCOPY_FREE(i) ftb.base[i].f.ccopy.free
#define FT_CCOPY_SAME(i) ftb.base[i].f.ccopy.same
#define FT_CCOPY_OUT(i) ftb.base[i].f.ccopy.out
#define FT_CCOPY_REUSE(i) ftb.base[i].f.ccopy.reuse
#define FT_CCOPY_LHSSEC(i) ftb.base[i].f.ccopy.lhssec
#define FT_CCOPY_NOTLHS(i) ftb.base[i].f.ccopy.notlhs
#define FT_CGATHER_ALLOC(i) ftb.base[i].f.cgather.alloc
#define FT_CGATHER_LHS(i) ftb.base[i].f.cgather.lhs
#define FT_CGATHER_RHS(i) ftb.base[i].f.cgather.rhs
#define FT_CGATHER_VSUB(i) ftb.base[i].f.cgather.vsub
#define FT_CGATHER_NVSUB(i) ftb.base[i].f.cgather.nvsub
#define FT_CGATHER_MASK(i) ftb.base[i].f.cgather.mask
#define FT_CGATHER_SECTVSUB(i) ftb.base[i].f.cgather.sectvsub
#define FT_CGATHER_SECTNVSUB(i) ftb.base[i].f.cgather.sectnvsub
#define FT_CGATHER_SECTM(i) ftb.base[i].f.cgather.sectm
#define FT_CGATHER_SECTV(i, j) ftb.base[i].f.cgather.sectv[j]
#define FT_CGATHER_V(i, j) ftb.base[i].f.cgather.v[j]
#define FT_CGATHER_PERMUTE(i, j) ftb.base[i].f.cgather.permute[j]
#define FT_CGATHER_VFLAG(i) ftb.base[i].f.cgather.vflag
#define FT_CGATHER_PFLAG(i) ftb.base[i].f.cgather.pflag
#define FT_CGATHER_VDIM(i) ftb.base[i].f.cgather.vdim
#define FT_CGATHER_PDIM(i) ftb.base[i].f.cgather.pdim
#define FT_CGATHER_NVEC(i) ftb.base[i].f.cgather.nvec
#define FT_CGATHER_NPER(i) ftb.base[i].f.cgather.nper
#define FT_CGATHER_TYPE(i) ftb.base[i].f.cgather.type
#define FT_CGATHER_USELHS(i) ftb.base[i].f.cgather.uselhs
#define FT_CGATHER_FREE(i) ftb.base[i].f.cgather.free
#define FT_CGATHER_SAME(i) ftb.base[i].f.cgather.same
#define FT_CGATHER_OUT(i) ftb.base[i].f.cgather.out
#define FT_CGATHER_REUSE(i) ftb.base[i].f.cgather.reuse
#define FT_CGATHER_INDEXREUSE(i) ftb.base[i].f.cgather.indexreuse
#define FT_CGATHER_LHSSEC(i) ftb.base[i].f.cgather.lhssec
#define FT_CGATHER_NOTLHS(i) ftb.base[i].f.cgather.notlhs
#define FT_SHIFT_RHS(i) ftb.base[i].f.shift.rhs
#define FT_SHIFT_FREE(i) ftb.base[i].f.shift.free
#define FT_SHIFT_SAME(i) ftb.base[i].f.shift.same
#define FT_SHIFT_OUT(i) ftb.base[i].f.shift.out
#define FT_SHIFT_REUSE(i) ftb.base[i].f.shift.reuse
#define FT_SHIFT_TYPE(i) ftb.base[i].f.shift.type
#define FT_SHIFT_BOUNDARY(i) ftb.base[i].f.shift.boundary
#define FT_CSTART_COMM(i) ftb.base[i].f.cstart.comm
#define FT_CSTART_LHS(i) ftb.base[i].f.cstart.lhs
#define FT_CSTART_RHS(i) ftb.base[i].f.cstart.rhs
#define FT_CSTART_SECTL(i) ftb.base[i].f.cstart.sectl
#define FT_CSTART_SECTR(i) ftb.base[i].f.cstart.sectr
#define FT_CSTART_FREE(i) ftb.base[i].f.cstart.free
#define FT_CSTART_SAME(i) ftb.base[i].f.cstart.same
#define FT_CSTART_OUT(i) ftb.base[i].f.cstart.out
#define FT_CSTART_ALLOC(i) ftb.base[i].f.cstart.alloc
#define FT_CSTART_REF(i) ftb.base[i].f.cstart.ref
#define FT_CSTART_REUSE(i) ftb.base[i].f.cstart.reuse
#define FT_CSTART_INVMVD(i) ftb.base[i].f.cstart.invmvd
#define FT_CSTART_TYPE(i) ftb.base[i].f.cstart.type
#define FT_CSTART_USELHS(i) ftb.base[i].f.cstart.uselhs
#define FT_CSTART_USEDSTD(i) ftb.base[i].f.cstart.usedstd
#define FT_CALL_SPTR(i) ftb.base[i].f.call.sptr
#define FT_CALL_NCALL(i) ftb.base[i].f.call.ncall
#define FT_CALL_CALL(i) ftb.base[i].f.call.call
#define FT_CALL_POS(i) ftb.base[i].f.call.pos
#define FT_NRT(i) ftb.base[i].f.forall.nrt
#define FT_RTL(i) ftb.base[i].f.forall.rtl
#define FT_NMCALL(i) ftb.base[i].f.forall.nmcall
#define FT_MCALL(i) ftb.base[i].f.forall.mcall
#define FT_NSCALL(i) ftb.base[i].f.forall.nscall
#define FT_SCALL(i) ftb.base[i].f.forall.scall
#define FT_NPCALL(i) ftb.base[i].f.forall.npcall
#define FT_PCALL(i) ftb.base[i].f.forall.pcall
#define FT_NMGET(i) ftb.base[i].f.forall.nmget
#define FT_MGET(i) ftb.base[i].f.forall.mget
#define FT_NSGET(i) ftb.base[i].f.forall.nsget
#define FT_SGET(i) ftb.base[i].f.forall.sget
#define FT_IGNORE(i) ftb.base[i].f.forall.ignore
#define FT_CYCLIC(i) ftb.base[i].f.forall.cyclic
#define FT_SECTL(i) ftb.base[i].f.forall.sectl
#define FT_NFUSE(i, j) ftb.base[i].f.forall.nfuse[j]
#define FT_FUSELP(i, j, k) ftb.base[i].f.forall.fuselp[(j)][(k)]
#define FT_FUSEDSTD(i, j, k) ftb.base[i].f.forall.fusedstd[(j)][(k)]
#define FT_FUSED(i) ftb.base[i].f.forall.fused
#define FT_HEADER(i) ftb.base[i].f.forall.header
#define FT_BARR1(i) ftb.base[i].f.forall.barr1
#define FT_BARR2(i) ftb.base[i].f.forall.barr2
#define FT_FG(i) ftb.base[i].f.forall.fg
#define BOGUSFLAG 0x100
#define NOTSECTFLAG 0 /* remove this flag, 0x200 */
#define NOREINDEX 0x2000000
Functions
void add_loop_hd (int)
If necessary create new preheader and trailer nodes for loop #lp, and set fgPre & fgPost to these nodes.
LOGICAL same_forall_size (int, int, int)
void comm_analyze (void)
Communication analyzer entry point.
void comm_optimize_post (void)
void comm_invar (void)
Hoist invariant communication expressions out of loops.
void comm_generator (void)
void comm_optimize_pre (void)
Variables
FTB ftb
OPTSUM optsum
Detailed Description
macros, definitions, and prototypes for communications module
Definition in file commopt.h.
Macro Definition Documentation
BOGUSFLAG
#define BOGUSFLAG 0x100
Definition at line 324 of file commopt.h.
FT_ALLOC_FREE
#define FT_ALLOC_FREE (i) ftb.base[i].f.alloc.free
Definition at line 199 of file commopt.h.
FT_ALLOC_OUT
#define FT_ALLOC_OUT (i) ftb.base[i].f.alloc.out
Definition at line 201 of file commopt.h.
FT_ALLOC_PTASGN
#define FT_ALLOC_PTASGN (i) ftb.base[i].f.alloc.ptasgn
Definition at line 204 of file commopt.h.
FT_ALLOC_REUSE
#define FT_ALLOC_REUSE (i) ftb.base[i].f.alloc.reuse
Definition at line 202 of file commopt.h.
FT_ALLOC_SAME
#define FT_ALLOC_SAME (i) ftb.base[i].f.alloc.same
Definition at line 200 of file commopt.h.
FT_ALLOC_SPTR
#define FT_ALLOC_SPTR (i) ftb.base[i].f.alloc.sptr
Definition at line 198 of file commopt.h.
FT_ALLOC_USED
#define FT_ALLOC_USED (i) ftb.base[i].f.alloc.used
Definition at line 203 of file commopt.h.
FT_BARR1
#define FT_BARR1 (i) ftb.base[i].f.forall.barr1
Definition at line 306 of file commopt.h.
FT_BARR2
#define FT_BARR2 (i) ftb.base[i].f.forall.barr2
Definition at line 307 of file commopt.h.
FT_BND_CALL
#define FT_BND_CALL (i) ftb.base[i].f.bnd.call
Definition at line 196 of file commopt.h.
FT_BND_IDX
#define FT_BND_IDX (i) ftb.base[i].f.bnd.idx
Definition at line 194 of file commopt.h.
FT_BND_LHS
#define FT_BND_LHS (i) ftb.base[i].f.bnd.lhs
Definition at line 193 of file commopt.h.
FT_BND_SAME
#define FT_BND_SAME (i) ftb.base[i].f.bnd.same
Definition at line 195 of file commopt.h.
FT_CALL_CALL
#define FT_CALL_CALL (i) ftb.base[i].f.call.call
Definition at line 283 of file commopt.h.
FT_CALL_NCALL
#define FT_CALL_NCALL (i) ftb.base[i].f.call.ncall
Definition at line 282 of file commopt.h.
FT_CALL_POS
#define FT_CALL_POS (i) ftb.base[i].f.call.pos
Definition at line 284 of file commopt.h.
FT_CALL_SPTR
#define FT_CALL_SPTR (i) ftb.base[i].f.call.sptr
Definition at line 281 of file commopt.h.
FT_CCOPY_ALLOC
#define FT_CCOPY_ALLOC (i) ftb.base[i].f.ccopy.alloc
Definition at line 215 of file commopt.h.
FT_CCOPY_FREE
#define FT_CCOPY_FREE (i) ftb.base[i].f.ccopy.free
Definition at line 222 of file commopt.h.
FT_CCOPY_LHS
#define FT_CCOPY_LHS (i) ftb.base[i].f.ccopy.lhs
Definition at line 216 of file commopt.h.
FT_CCOPY_LHSSEC
#define FT_CCOPY_LHSSEC (i) ftb.base[i].f.ccopy.lhssec
Definition at line 226 of file commopt.h.
FT_CCOPY_NOTLHS
#define FT_CCOPY_NOTLHS (i) ftb.base[i].f.ccopy.notlhs
Definition at line 227 of file commopt.h.
FT_CCOPY_OUT
#define FT_CCOPY_OUT (i) ftb.base[i].f.ccopy.out
Definition at line 224 of file commopt.h.
FT_CCOPY_REUSE
#define FT_CCOPY_REUSE (i) ftb.base[i].f.ccopy.reuse
Definition at line 225 of file commopt.h.
FT_CCOPY_RHS
#define FT_CCOPY_RHS (i) ftb.base[i].f.ccopy.rhs
Definition at line 217 of file commopt.h.
FT_CCOPY_SAME
#define FT_CCOPY_SAME (i) ftb.base[i].f.ccopy.same
Definition at line 223 of file commopt.h.
FT_CCOPY_SECTL
#define FT_CCOPY_SECTL (i) ftb.base[i].f.ccopy.sectl
Definition at line 219 of file commopt.h.
FT_CCOPY_SECTR
#define FT_CCOPY_SECTR (i) ftb.base[i].f.ccopy.sectr
Definition at line 220 of file commopt.h.
FT_CCOPY_TSPTR
#define FT_CCOPY_TSPTR (i) ftb.base[i].f.ccopy.sptr
Definition at line 218 of file commopt.h.
FT_CCOPY_USELHS
#define FT_CCOPY_USELHS (i) ftb.base[i].f.ccopy.uselhs
Definition at line 221 of file commopt.h.
FT_CGATHER_ALLOC
#define FT_CGATHER_ALLOC (i) ftb.base[i].f.cgather.alloc
Definition at line 229 of file commopt.h.
FT_CGATHER_FREE
#define FT_CGATHER_FREE (i) ftb.base[i].f.cgather.free
Definition at line 249 of file commopt.h.
FT_CGATHER_INDEXREUSE
#define FT_CGATHER_INDEXREUSE (i) ftb.base[i].f.cgather.indexreuse
Definition at line 253 of file commopt.h.
FT_CGATHER_LHS
#define FT_CGATHER_LHS (i) ftb.base[i].f.cgather.lhs
Definition at line 230 of file commopt.h.
FT_CGATHER_LHSSEC
#define FT_CGATHER_LHSSEC (i) ftb.base[i].f.cgather.lhssec
Definition at line 254 of file commopt.h.
FT_CGATHER_MASK
#define FT_CGATHER_MASK (i) ftb.base[i].f.cgather.mask
Definition at line 234 of file commopt.h.
FT_CGATHER_NOTLHS
#define FT_CGATHER_NOTLHS (i) ftb.base[i].f.cgather.notlhs
Definition at line 255 of file commopt.h.
FT_CGATHER_NPER
#define FT_CGATHER_NPER (i) ftb.base[i].f.cgather.nper
Definition at line 246 of file commopt.h.
FT_CGATHER_NVEC
#define FT_CGATHER_NVEC (i) ftb.base[i].f.cgather.nvec
Definition at line 245 of file commopt.h.
FT_CGATHER_NVSUB
#define FT_CGATHER_NVSUB (i) ftb.base[i].f.cgather.nvsub
Definition at line 233 of file commopt.h.
FT_CGATHER_OUT
#define FT_CGATHER_OUT (i) ftb.base[i].f.cgather.out
Definition at line 251 of file commopt.h.
FT_CGATHER_PDIM
#define FT_CGATHER_PDIM (i) ftb.base[i].f.cgather.pdim
Definition at line 244 of file commopt.h.
FT_CGATHER_PERMUTE
#define FT_CGATHER_PERMUTE (i, j) ftb.base[i].f.cgather.permute[j]
Definition at line 240 of file commopt.h.
FT_CGATHER_PFLAG
#define FT_CGATHER_PFLAG (i) ftb.base[i].f.cgather.pflag
Definition at line 242 of file commopt.h.
FT_CGATHER_REUSE
#define FT_CGATHER_REUSE (i) ftb.base[i].f.cgather.reuse
Definition at line 252 of file commopt.h.
FT_CGATHER_RHS
#define FT_CGATHER_RHS (i) ftb.base[i].f.cgather.rhs
Definition at line 231 of file commopt.h.
FT_CGATHER_SAME
#define FT_CGATHER_SAME (i) ftb.base[i].f.cgather.same
Definition at line 250 of file commopt.h.
FT_CGATHER_SECTM
#define FT_CGATHER_SECTM (i) ftb.base[i].f.cgather.sectm
Definition at line 237 of file commopt.h.
FT_CGATHER_SECTNVSUB
#define FT_CGATHER_SECTNVSUB (i) ftb.base[i].f.cgather.sectnvsub
Definition at line 236 of file commopt.h.
FT_CGATHER_SECTV
#define FT_CGATHER_SECTV (i, j) ftb.base[i].f.cgather.sectv[j]
Definition at line 238 of file commopt.h.
FT_CGATHER_SECTVSUB
#define FT_CGATHER_SECTVSUB (i) ftb.base[i].f.cgather.sectvsub
Definition at line 235 of file commopt.h.
FT_CGATHER_TYPE
#define FT_CGATHER_TYPE (i) ftb.base[i].f.cgather.type
Definition at line 247 of file commopt.h.
FT_CGATHER_USELHS
#define FT_CGATHER_USELHS (i) ftb.base[i].f.cgather.uselhs
Definition at line 248 of file commopt.h.
FT_CGATHER_V
#define FT_CGATHER_V (i, j) ftb.base[i].f.cgather.v[j]
Definition at line 239 of file commopt.h.
FT_CGATHER_VDIM
#define FT_CGATHER_VDIM (i) ftb.base[i].f.cgather.vdim
Definition at line 243 of file commopt.h.
FT_CGATHER_VFLAG
#define FT_CGATHER_VFLAG (i) ftb.base[i].f.cgather.vflag
Definition at line 241 of file commopt.h.
FT_CGATHER_VSUB
#define FT_CGATHER_VSUB (i) ftb.base[i].f.cgather.vsub
Definition at line 232 of file commopt.h.
FT_CSTART_ALLOC
#define FT_CSTART_ALLOC (i) ftb.base[i].f.cstart.alloc
Definition at line 273 of file commopt.h.
FT_CSTART_COMM
#define FT_CSTART_COMM (i) ftb.base[i].f.cstart.comm
Definition at line 265 of file commopt.h.
FT_CSTART_FREE
#define FT_CSTART_FREE (i) ftb.base[i].f.cstart.free
Definition at line 270 of file commopt.h.
FT_CSTART_INVMVD
#define FT_CSTART_INVMVD (i) ftb.base[i].f.cstart.invmvd
Definition at line 276 of file commopt.h.
FT_CSTART_LHS
#define FT_CSTART_LHS (i) ftb.base[i].f.cstart.lhs
Definition at line 266 of file commopt.h.
FT_CSTART_OUT
#define FT_CSTART_OUT (i) ftb.base[i].f.cstart.out
Definition at line 272 of file commopt.h.
FT_CSTART_REF
#define FT_CSTART_REF (i) ftb.base[i].f.cstart.ref
Definition at line 274 of file commopt.h.
FT_CSTART_REUSE
#define FT_CSTART_REUSE (i) ftb.base[i].f.cstart.reuse
Definition at line 275 of file commopt.h.
FT_CSTART_RHS
#define FT_CSTART_RHS (i) ftb.base[i].f.cstart.rhs
Definition at line 267 of file commopt.h.
FT_CSTART_SAME
#define FT_CSTART_SAME (i) ftb.base[i].f.cstart.same
Definition at line 271 of file commopt.h.
FT_CSTART_SECTL
#define FT_CSTART_SECTL (i) ftb.base[i].f.cstart.sectl
Definition at line 268 of file commopt.h.
FT_CSTART_SECTR
#define FT_CSTART_SECTR (i) ftb.base[i].f.cstart.sectr
Definition at line 269 of file commopt.h.
FT_CSTART_TYPE
#define FT_CSTART_TYPE (i) ftb.base[i].f.cstart.type
Definition at line 277 of file commopt.h.
FT_CSTART_USEDSTD
#define FT_CSTART_USEDSTD (i) ftb.base[i].f.cstart.usedstd
Definition at line 279 of file commopt.h.
FT_CSTART_USELHS
#define FT_CSTART_USELHS (i) ftb.base[i].f.cstart.uselhs
Definition at line 278 of file commopt.h.
FT_CYCLIC
#define FT_CYCLIC (i) ftb.base[i].f.forall.cyclic
Definition at line 299 of file commopt.h.
FT_FG
#define FT_FG (i) ftb.base[i].f.forall.fg
Definition at line 308 of file commopt.h.
FT_FORALL
#define FT_FORALL (i) ftb.base[i].fall
Definition at line 185 of file commopt.h.
FT_FUSED
#define FT_FUSED (i) ftb.base[i].f.forall.fused
Definition at line 304 of file commopt.h.
FT_FUSEDSTD
#define FT_FUSEDSTD (i, j, k) ftb.base[i].f.forall.fusedstd[(j)][(k)]
Definition at line 303 of file commopt.h.
FT_FUSELP
#define FT_FUSELP (i, j, k) ftb.base[i].f.forall.fuselp[(j)][(k)]
Definition at line 302 of file commopt.h.
FT_GETSCLR_NOMEM
#define FT_GETSCLR_NOMEM (i) ftb.base[i].f.getsclr.nomem
Definition at line 189 of file commopt.h.
FT_GETSCLR_OMEM
#define FT_GETSCLR_OMEM (i, j) ftb.base[i].f.getsclr.omem[j]
Definition at line 190 of file commopt.h.
FT_GETSCLR_OMEMED
#define FT_GETSCLR_OMEMED (i) ftb.base[i].f.getsclr.omemed
Definition at line 191 of file commopt.h.
FT_GETSCLR_REUSE
#define FT_GETSCLR_REUSE (i) ftb.base[i].f.getsclr.reuse
Definition at line 188 of file commopt.h.
FT_GETSCLR_SAME
#define FT_GETSCLR_SAME (i) ftb.base[i].f.getsclr.same
Definition at line 187 of file commopt.h.
FT_HEADER
#define FT_HEADER (i) ftb.base[i].f.forall.header
Definition at line 305 of file commopt.h.
FT_IGNORE
#define FT_IGNORE (i) ftb.base[i].f.forall.ignore
Definition at line 298 of file commopt.h.
FT_MCALL
#define FT_MCALL (i) ftb.base[i].f.forall.mcall
Definition at line 289 of file commopt.h.
FT_MGET
#define FT_MGET (i) ftb.base[i].f.forall.mget
Definition at line 295 of file commopt.h.
FT_NFUSE
#define FT_NFUSE (i, j) ftb.base[i].f.forall.nfuse[j]
Definition at line 301 of file commopt.h.
FT_NMCALL
#define FT_NMCALL (i) ftb.base[i].f.forall.nmcall
Definition at line 288 of file commopt.h.
FT_NMGET
#define FT_NMGET (i) ftb.base[i].f.forall.nmget
Definition at line 294 of file commopt.h.
FT_NPCALL
#define FT_NPCALL (i) ftb.base[i].f.forall.npcall
Definition at line 292 of file commopt.h.
FT_NRT
#define FT_NRT (i) ftb.base[i].f.forall.nrt
Definition at line 286 of file commopt.h.
FT_NSCALL
#define FT_NSCALL (i) ftb.base[i].f.forall.nscall
Definition at line 290 of file commopt.h.
FT_NSGET
#define FT_NSGET (i) ftb.base[i].f.forall.nsget
Definition at line 296 of file commopt.h.
FT_PCALL
#define FT_PCALL (i) ftb.base[i].f.forall.pcall
Definition at line 293 of file commopt.h.
FT_RTL
#define FT_RTL (i) ftb.base[i].f.forall.rtl
Definition at line 287 of file commopt.h.
FT_SCALL
#define FT_SCALL (i) ftb.base[i].f.forall.scall
Definition at line 291 of file commopt.h.
FT_SECT_ALLOC
#define FT_SECT_ALLOC (i) ftb.base[i].f.sect.alloc
Definition at line 208 of file commopt.h.
FT_SECT_ARR
#define FT_SECT_ARR (i) ftb.base[i].f.sect.arr
Definition at line 206 of file commopt.h.
FT_SECT_FLAG
#define FT_SECT_FLAG (i) ftb.base[i].f.sect.flag
Definition at line 210 of file commopt.h.
FT_SECT_FREE
#define FT_SECT_FREE (i) ftb.base[i].f.sect.free
Definition at line 209 of file commopt.h.
FT_SECT_OUT
#define FT_SECT_OUT (i) ftb.base[i].f.sect.out
Definition at line 212 of file commopt.h.
FT_SECT_REUSE
#define FT_SECT_REUSE (i) ftb.base[i].f.sect.reuse
Definition at line 213 of file commopt.h.
FT_SECT_SAME
#define FT_SECT_SAME (i) ftb.base[i].f.sect.same
Definition at line 211 of file commopt.h.
FT_SECT_SPTR
#define FT_SECT_SPTR (i) ftb.base[i].f.sect.sptr
Definition at line 207 of file commopt.h.
FT_SECTL
#define FT_SECTL (i) ftb.base[i].f.forall.sectl
Definition at line 300 of file commopt.h.
FT_SGET
#define FT_SGET (i) ftb.base[i].f.forall.sget
Definition at line 297 of file commopt.h.
FT_SHIFT_BOUNDARY
#define FT_SHIFT_BOUNDARY (i) ftb.base[i].f.shift.boundary
Definition at line 263 of file commopt.h.
FT_SHIFT_FREE
#define FT_SHIFT_FREE (i) ftb.base[i].f.shift.free
Definition at line 258 of file commopt.h.
FT_SHIFT_OUT
#define FT_SHIFT_OUT (i) ftb.base[i].f.shift.out
Definition at line 260 of file commopt.h.
FT_SHIFT_REUSE
#define FT_SHIFT_REUSE (i) ftb.base[i].f.shift.reuse
Definition at line 261 of file commopt.h.
FT_SHIFT_RHS
#define FT_SHIFT_RHS (i) ftb.base[i].f.shift.rhs
Definition at line 257 of file commopt.h.
FT_SHIFT_SAME
#define FT_SHIFT_SAME (i) ftb.base[i].f.shift.same
Definition at line 259 of file commopt.h.
FT_SHIFT_TYPE
#define FT_SHIFT_TYPE (i) ftb.base[i].f.shift.type
Definition at line 262 of file commopt.h.
FT_STD
#define FT_STD (i) ftb.base[i].std
Definition at line 184 of file commopt.h.
MAXFUSE
#define MAXFUSE 10
Definition at line 12 of file commopt.h.
MAXOMEM
#define MAXOMEM 40
Definition at line 13 of file commopt.h.
NOREINDEX
#define NOREINDEX 0x2000000
Definition at line 326 of file commopt.h.
NOTSECTFLAG
#define NOTSECTFLAG 0 /* remove this flag, 0x200 */
Definition at line 325 of file commopt.h.
Function Documentation
add_loop_hd()
void add_loop_hd (int lp)
If necessary create new preheader and trailer nodes for loop #lp, and set fgPre & fgPost to these nodes.
Definition at line 683 of file comminvar.c.
References add_fg(), add_loop_preheader(), add_stmt_after(), ast, FG_FT, FG_LPREV, FG_STDFIRST, fgPre, lp, LP_HEAD, mk_stmt(), opt, OPT::pre_fg, rdilts(), std, TRUE, and wrilts().
Referenced by get_temp_forall2().
comm_analyze()
void comm_analyze (void)
Communication analyzer entry point.
Definition at line 118 of file tools/flang1/flang1exe/comm.c.
References A_OPTYPEG, ast, check_region(), comm_init(), pure_gbl::end_master_region, gbl, init_region(), pure_gbl::local_mode, set_descriptor_sc(), std, STD_AST, STD_LINENO, STD_LOCAL, STD_NEXT, STD_PURE, transform_ast(), transform_forall(), transform_ptr(), and type.
comm_generator()
void comm_generator (void)
Definition at line 62 of file commgen.c.
References ast, eliminate_redundant(), gbl, generate_copy(), generate_gather(), generate_get_scalar(), generate_hallobnds(), generate_sect(), pointer_changer(), rt_outvalue(), std, STD_AST, STD_LINENO, STD_NEXT, type, and XBIT.
comm_invar()
void comm_invar (void)
Hoist invariant communication expressions out of loops.
Definition at line 99 of file comminvar.c.
References clean_flags(), DBGBIT, dump_std(), FREE, gbl, get_loopcounts(), hlopt_end(), HLOPT_INDUC, hlopt_init(), hoist_loop(), lp, LP_CHILD, LP_SIBLING, mk_ztrips(), NULL, and pastCounts.
comm_optimize_post()
void comm_optimize_post (void)
Definition at line 123 of file commopt.c.
References alloc2ast(), comm_optimize_end(), comm_optimize_init(), commopt(), DBGBIT, dump_flowgraph(), dump_loops(), findloop(), flow(), flowgraph(), HLOPT_ALL, optsummary(), and rewrite_opfields.
comm_optimize_pre()
void comm_optimize_pre (void)
Definition at line 156 of file commopt.c.
References comm_optimize_end(), comm_optimize_init(), DBGBIT, dump_flowgraph(), dump_loops(), findloop(), flow(), flowgraph(), fuse_forall(), HLOPT_ALL, and selection_sort().
same_forall_size()
LOGICAL same_forall_size (int lp1, int lp2, int nested)
Definition at line 437 of file commopt.c.
References astb, ASTLI_NEXT, ASTLI_TRIPLE, ASTB::bnd, ASTB::dtype, FALSE, FG_STDFIRST, i, ASTB::i1, is_avail_expr(), is_dominator(), LP_FG, LP_HEAD, mk_binop(), OP_SUB, STD_AST, and TRUE.
Referenced by get_temp_forall2().
Variable Documentation
ftb
FTB ftb extern
Definition at line 87 of file commopt.c.
Referenced by alloc2ast(), convert_output(), init_ftb(), mk_ftb(), move_mask_calls(), remove_mask_calls(), and remove_stmt_calls().
optsum
OPTSUM optsum extern
Definition at line 88 of file commopt.c.
Referenced by eliminate_alloc(), eliminate_bnds(), eliminate_copy(), eliminate_gather(), eliminate_sect(), eliminate_shift(), eliminate_start(), fuse_forall(), init_optsum(), and optsummary().