flang: commgen.c File Reference
commgen.c File Reference
Fortran communications optimizer module.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "comm.h"
#include "dtypeutl.h"
#include "symutl.h"
#include "soc.h"
#include "semant.h"
#include "ast.h"
#include "transfrm.h"
#include "extern.h"
#include "commopt.h"
#include "rte.h"
#include "fdirect.h"
#include "rtlRtns.h"
#include "ilidir.h"
Functions
static void change_forall_triple (int, int, int, LOGICAL)
static int fill_cyclic_k (int)
static void fill_cyclic_1 (int)
static void generate_hallobnds (int)
static void generate_sect (int)
static void generate_copy (int)
static void generate_gather (int)
static void generate_get_scalar (void)
static void eliminate_redundant (void)
static void pointer_changer (void)
static int pointer_squeezer (int)
static int cyclic_section (int, int, int, int, int)
static int gen_minmax (int, int, int)
void comm_generator (void)
void rt_outvalue (void)
LOGICAL is_use_lhs_final (int a, int forall, LOGICAL same_nidx, LOGICAL independent, int std)
void outvalue_hlocalizebnds (int ast)
void outvalue_hcycliclp (int ast)
void generate_hlocalizebnds (int ast)
void generate_hcycliclp (int ast)
int gen_localize_index (int sptr, int dim, int subAst, int astmem)
int inline_hlocalizebnds (int i1, int i2, int lb, int ub, int sptr_lhs, int descr, int dim, int std, int astmem)
Detailed Description
Fortran communications optimizer module.
Definition in file commgen.c.
Function Documentation
change_forall_triple()
static void change_forall_triple (int forall, int idx, int otriple, LOGICAL is_cyclic) static
Definition at line 1197 of file commgen.c.
References add_astli(), ASTLI_HEAD, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, idx, lb, list, mk_triple(), st, start_astli(), and ub.
Referenced by generate_hcycliclp(), and generate_hlocalizebnds().
comm_generator()
void comm_generator (void)
Definition at line 62 of file commgen.c.
References ast, eliminate_redundant(), gbl, generate_copy(), generate_gather(), generate_get_scalar(), generate_hallobnds(), generate_sect(), pointer_changer(), rt_outvalue(), std, STD_AST, STD_LINENO, STD_NEXT, type, and XBIT.
cyclic_section()
static int cyclic_section (int sptr, int idxAst, int clofAst, int i, int memberast) static
Definition at line 1535 of file commgen.c.
References assert, ast, astb, ASTB::bnd, check_member(), ASTB::dtype, get_section_offset(), get_section_stride(), i, mk_binop(), OP_ADD, OP_MUL, OP_SUB, and sptr.
Referenced by pointer_squeezer().
eliminate_redundant()
static void eliminate_redundant (void) static
Definition at line 722 of file commgen.c.
References ast, close_pragma(), FALSE, flg, FT_ALLOC_REUSE, FT_ALLOC_SPTR, FT_CCOPY_ALLOC, FT_CCOPY_LHS, FT_CCOPY_NOTLHS, FT_CCOPY_RHS, FT_CCOPY_SECTL, FT_CCOPY_USELHS, FT_CGATHER_ALLOC, FT_CGATHER_LHS, FT_CGATHER_NOTLHS, FT_CGATHER_RHS, FT_CGATHER_SECTNVSUB, FT_CGATHER_USELHS, FT_CSTART_COMM, FT_CSTART_INVMVD, FT_CSTART_REUSE, FT_CSTART_SECTL, FT_CSTART_SECTR, FT_CSTART_TYPE, FT_CSTART_USELHS, FT_NRT, FT_RTL, FT_SECT_REUSE, FT_SECTL, gbl, glist(), is_use_lhs_final(), k, lhs, memsym_of_ast(), open_pragma(), rank_of_sym(), start, arg_gbl::std, std, STD_AST, STD_DELETE, STD_LINENO, STD_NEXT, TRUE, type, and FLG::x.
Referenced by comm_generator().
fill_cyclic_1()
static void fill_cyclic_1 (int ast) static
Definition at line 1245 of file commgen.c.
References assert, ast, CTYPE::c_inc, CTYPE::c_init, CTYPE::c_lof, cdim, dim, DT_INT, FT_CYCLIC, FT_STD, get_int_cval(), mk_binop(), mk_stmt(), OP_ADD, and STD_AST.
Referenced by generate_hcycliclp().
fill_cyclic_k()
static int fill_cyclic_k (int ast) static
Definition at line 1302 of file commgen.c.
References A_ARGCNTP, argt, ARGT_ARG, assert, ast, CTYPE::c_lof, CTYPE::cb_block, CTYPE::cb_do, CTYPE::cb_enddo, CTYPE::cb_inc, CTYPE::cb_init, cdim, cl, cs, dim, DT_INT, FT_CYCLIC, FT_STD, get_int_cval(), lb, mk_argt(), mk_binop(), mk_cval(), mk_default_int(), mk_id(), mk_stmt(), mk_triple(), mkRteRtnNm(), nargs, OP_ADD, RTE_block_loop, s, src, STD_AST, sym_mkfunc(), trans_getbound(), and ub.
Referenced by generate_hcycliclp().
gen_localize_index()
int gen_localize_index (int sptr, int dim, int subAst, int astmem)
Definition at line 1497 of file commgen.c.
References add_lbnd(), argt, ARGT_ARG, astb, ASTB::bnd, check_member(), dim, DT_INT, ASTB::dtype, mk_argt(), mk_bnd_int(), mk_func_node(), mk_id(), mk_isz_cval(), mkRteRtnNm(), nargs, normalize_bounds(), RTE_localize_index, sptr, sub_lbnd(), and sym_mkfunc().
gen_minmax()
static int gen_minmax (int astl, int astr, int type) static
Definition at line 1708 of file commgen.c.
References ast_intr(), DT_ISINT, DTY, and type.
Referenced by inline_hlocalizebnds().
generate_copy()
static void generate_copy (int ast) static
Definition at line 269 of file commgen.c.
References A_ARGCNTP, A_STDG, add_stmt_after(), add_stmt_before(), argt, ARGT_ARG, assert, ast, astb, check_member(), copy(), cp, delete_stmt(), dest, DT_INT, FT_ALLOC_OUT, FT_CCOPY_ALLOC, FT_CCOPY_FREE, FT_CCOPY_LHS, FT_CCOPY_OUT, FT_CCOPY_SAME, FT_CCOPY_SECTL, FT_CCOPY_SECTR, FT_CCOPY_USELHS, FT_SECT_ARR, FT_SECT_OUT, ASTB::i1, mk_argt(), mk_func_node(), mk_id(), mk_stmt(), mkRteRtnNm(), nargs, RTE_comm_copy, RTE_comm_free, sptr, src, std, STD_AST, STD_DELETE, and sym_mkfunc().
Referenced by comm_generator().
generate_gather()
static void generate_gather (int ast) static
Definition at line 366 of file commgen.c.
References A_ARGCNTP, A_STDG, add_stmt_after(), add_stmt_before(), argt, ARGT_ARG, ASD_NDIM, assert, ast, astb, check_member(), cp, delete_stmt(), dest, DT_INT, DT_LOG, dtype_to_arg(), FT_ALLOC_OUT, FT_CGATHER_ALLOC, FT_CGATHER_FREE, FT_CGATHER_INDEXREUSE, FT_CGATHER_LHS, FT_CGATHER_NPER, FT_CGATHER_NVEC, FT_CGATHER_NVSUB, FT_CGATHER_OUT, FT_CGATHER_PDIM, FT_CGATHER_PERMUTE, FT_CGATHER_PFLAG, FT_CGATHER_SAME, FT_CGATHER_SECTM, FT_CGATHER_SECTNVSUB, FT_CGATHER_SECTV, FT_CGATHER_SECTVSUB, FT_CGATHER_TYPE, FT_CGATHER_USELHS, FT_CGATHER_V, FT_CGATHER_VDIM, FT_CGATHER_VFLAG, FT_CGATHER_VSUB, FT_SECT_OUT, func, getbit(), i, ASTB::i1, j, memsym_of_ast(), mk_argt(), mk_cval(), mk_func_node(), mk_id(), mk_stmt(), mkRteRtnNm(), nargs, pflag, RTE_comm_free, RTE_comm_gatherx, RTE_comm_scatterx, sptr, std, STD_AST, STD_DELETE, sym_mkfunc(), and vec.
Referenced by comm_generator().
generate_get_scalar()
static void generate_get_scalar (void) static
Definition at line 102 of file commgen.c.
References a, A_ARGCNTP, add_stmt_after(), add_stmt_before(), argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, tbl::avl, tbl::base, check_member(), delete_stmt(), dest, TABLE::f1, find_get_scalar(), free_gstbl(), FT_GETSCLR_SAME, FT_STD, GETSCALAR_CAUSE, gstbl, i, init_gstbl(), j, memsym_of_ast(), mk_argt(), mk_default_int(), mk_id(), mk_stmt(), mkRteRtnNm(), nargs, ndim, normalize_bounds(), report_comm(), RTE_get_scalar, src, std, STD_AST, STD_DELETE, sub_lbnd(), and sym_mkfunc().
Referenced by comm_generator().
generate_hallobnds()
static void generate_hallobnds (int ast) static
Definition at line 182 of file commgen.c.
References A_STDG, ASD_NDIM, ASD_SUBS, assert, ast, delete_stmt(), FT_ALLOC_FREE, FT_ALLOC_SAME, i, mk_mem_allocate(), mk_mem_deallocate(), ndim, std, STD_DELETE, and STD_RESCOPE.
Referenced by comm_generator().
generate_hcycliclp()
void generate_hcycliclp (int ast)
Definition at line 1085 of file commgen.c.
References A_ARGCNTP, A_STDG, add_lbnd(), add_stmt_before(), argt, ARGT_ARG, assert, ast, astb, ASTB::bnd, change_forall_triple(), check_member(), delete_stmt(), dim, ASTB::dtype, FALSE, fill_cyclic_1(), fill_cyclic_k(), FT_BND_CALL, FT_BND_IDX, FT_BND_LHS, FT_BND_SAME, FT_STD, get_int_cval(), idx, lhs, memsym_of_ast(), mk_argt(), mk_assn_stmt(), mk_bnd_int(), mk_default_int(), mk_id(), mk_isz_cval(), mk_stmt(), mkRteRtnNm(), nargs, normalize_bounds(), RTE_cyclic_loop, st, std, STD_AST, STD_DELETE, sub_lbnd(), sym_mkfunc(), and TRUE.
generate_hlocalizebnds()
void generate_hlocalizebnds (int ast)
Definition at line 974 of file commgen.c.
References A_ARGCNTP, A_STDG, add_lbnd(), add_stmt_before(), argt, ARGT_ARG, assert, ast, astb, ASTB::bnd, change_forall_triple(), check_member(), delete_stmt(), dim, ASTB::dtype, FALSE, FT_BND_CALL, FT_BND_IDX, FT_BND_LHS, FT_BND_SAME, FT_STD, get_int_cval(), idx, inline_hlocalizebnds(), lb, lhs, memsym_of_ast(), mk_argt(), mk_assn_stmt(), mk_bnd_int(), mk_id(), mk_isz_cval(), mk_stmt(), mkRteRtnNm(), nargs, normalize_bounds(), ASTB::one, RTE_localize_bounds, st, std, STD_AST, STD_DELETE, sub_lbnd(), sym_mkfunc(), ub, and XBIT.
generate_sect()
static void generate_sect (int ast) static
Definition at line 221 of file commgen.c.
References A_STDG, ASD_NDIM, ASD_SUBS, assert, ast, delete_stmt(), FT_ALLOC_OUT, FT_SECT_ALLOC, FT_SECT_FLAG, FT_SECT_FREE, FT_SECT_OUT, FT_SECT_SAME, i, make_sec_from_ast(), mk_id(), mk_subscr(), ndim, sectflag, sptr, std, STD_AST, and STD_DELETE.
Referenced by comm_generator().
inline_hlocalizebnds()
int inline_hlocalizebnds (int i1, int i2, int lb, int ub, int sptr_lhs, int descr, int dim, int std, int astmem)
Definition at line 1644 of file commgen.c.
References AD_DPTR, AD_LWAST, AD_UPAST, add_stmt_before(), assert, astb, ASTB::bnd, check_member(), dim, ASTB::dtype, gen_minmax(), get_owner_lower(), get_owner_upper(), is_array_type(), lb, max, min, mk_binop(), mk_default_int(), mk_stmt(), normalize_bounds(), ASTB::one, OP_ADD, OP_SUB, std, STD_LINENO, STD_LOCAL, STD_NEXT, and ub.
Referenced by generate_hlocalizebnds().
is_use_lhs_final()
LOGICAL is_use_lhs_final (int a, int forall, LOGICAL same_nidx, LOGICAL independent, int std)
Definition at line 871 of file commgen.c.
References a, expr_dependent(), FALSE, FT_FUSEDSTD, FT_HEADER, FT_NFUSE, header(), i, is_same_number_of_idx(), lhs, list, memsym_of_ast(), sptr, src, std, STD_AST, and TRUE.
Referenced by eliminate_redundant(), and emit_permute_section().
outvalue_hcycliclp()
void outvalue_hcycliclp (int ast)
Definition at line 942 of file commgen.c.
References assert, ast, cl, cs, mk_id(), mk_triple(), and trans_getbound().
Referenced by rt_outvalue().
outvalue_hlocalizebnds()
void outvalue_hlocalizebnds (int ast)
Definition at line 925 of file commgen.c.
References assert, ast, lb, mk_id(), mk_triple(), trans_getbound(), and ub.
Referenced by rt_outvalue().
pointer_changer()
static void pointer_changer (void) static
Definition at line 1728 of file commgen.c.
References A_STDP, ast, gbl, pointer_squeezer(), arg_gbl::std, std, STD_AST, STD_DELETE, STD_LINENO, and STD_NEXT.
Referenced by comm_generator().
pointer_squeezer()
static int pointer_squeezer (int ast) static
Definition at line 1747 of file commgen.c.
References A_ARGCNTG, A_OPTYPEG, A_OPTYPEP, add_astli(), ALIGNG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, ASTLI_HEAD, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, cyclic_section(), i, interr(), m2, m4, mk_argt(), mk_assn_stmt(), mk_binop(), mk_convert(), mk_func_node(), mk_id(), mk_member(), mk_paren(), mk_stmt(), mk_subscr(), mk_substr(), mk_triple(), mk_unop(), pointer_squeezer(), r, sptr, sptr_of_subscript(), start_astli(), and unmk_argt().
Referenced by pointer_changer(), and pointer_squeezer().
rt_outvalue()
void rt_outvalue (void)
Definition at line 695 of file commgen.c.
References ast, gbl, outvalue_hcycliclp(), outvalue_hlocalizebnds(), arg_gbl::std, std, STD_AST, STD_DELETE, STD_LINENO, and STD_NEXT.
Referenced by comm_generator().