flang: comminvar.c File Reference
comminvar.c File Reference
Invariant communication optimization.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "ast.h"
#include "nme.h"
#include "machar.h"
#include "gramtk.h"
#include "optimize.h"
#include "induc.h"
#include "extern.h"
#include "commopt.h"
#include "ccffinfo.h"
#include "fdirect.h"
#include "ilidir.h"
Macros
#define A_CONDG(a) A_OPT2G(a)
#define A_CONDP(a, v) A_OPT2P(a, v)
#define TRACE0(s)
#define TRACE1(s, a1)
#define TRACE2(s, a1, a2)
#define TRACE3(s, a1, a2, a3)
#define TRACE4(s, a1, a2, a3, a4)
#define TRACE5(s, a1, a2, a3, a4, a5)
Functions
static LOGICAL hoist_loop (int lp)
static void clean_flags (void)
static void get_loopcounts (void)
static LOGICAL contains_alloc (int lp)
static LOGICAL unique_allo (int allo_std, int allo_ft, int lp)
static void hoist_comms (int lp)
static void hoist_std (int, int, int)
static LOGICAL check_outer_defs (int std, int lp, int nme)
static LOGICAL check_inner_uses (int std, int lp, int nme)
static LOGICAL is_invariant_base (int nme)
static LOGICAL is_parent_loop (int lpParent, int lpChild)
static LOGICAL has_invar_subs (int ast)
static LOGICAL is_invariant_list (int n, int vast[])
static LOGICAL check_moved_list (int n, int vstd[])
static LOGICAL check_moved (int std)
static void move_invar_std (int std, int fg)
static void mk_loop_hdtl (int lp)
static int mk_count_test (int astCond, int astCount)
static int mk_dealloc_stub (int astCond)
static void mk_ztrips (int lp)
static int remove_cond (int astTarg, int astSrc)
void comm_invar (void)
Hoist invariant communication expressions out of loops.
void add_loop_hd (int lp)
If necessary create new preheader and trailer nodes for loop #lp, and set fgPre & fgPost to these nodes.
Variables
static int fgPre
static int fgPost
static LOGICAL bMovedComm
static LOGICAL bMovedAssn
static int * pastCounts = NULL
Detailed Description
Invariant communication optimization.
Definition in file comminvar.c.
Macro Definition Documentation
A_CONDG
#define A_CONDG (a) A_OPT2G(a)
Definition at line 36 of file comminvar.c.
A_CONDP
#define A_CONDP (a, v) A_OPT2P(a, v)
Definition at line 37 of file comminvar.c.
TRACE0
#define TRACE0 (s)
Value:
  if (DBGBIT(43, 2)) \
  fprintf(gbl.dbgfil, s)
Definition at line 40 of file comminvar.c.
TRACE1
#define TRACE1 (s, a1)
Value:
  if (DBGBIT(43, 2))  \
  fprintf(gbl.dbgfil, s, a1)
Definition at line 43 of file comminvar.c.
TRACE2
#define TRACE2 (s, a1, a2)
Value:
  if (DBGBIT(43, 2))      \
  fprintf(gbl.dbgfil, s, a1, a2)
Definition at line 46 of file comminvar.c.
TRACE3
#define TRACE3 (s, a1, a2, a3)
Value:
  if (DBGBIT(43, 2))          \
  fprintf(gbl.dbgfil, s, a1, a2, a3)
Definition at line 49 of file comminvar.c.
TRACE4
#define TRACE4 (s, a1, a2, a3, a4)
Value:
  if (DBGBIT(43, 2))              \
  fprintf(gbl.dbgfil, s, a1, a2, a3, a4)
Definition at line 52 of file comminvar.c.
TRACE5
#define TRACE5 (s, a1, a2, a3, a4, a5)
Value:
  if (DBGBIT(43, 2))                  \
  fprintf(gbl.dbgfil, s, a1, a2, a3, a4, a5)
Definition at line 55 of file comminvar.c.
Function Documentation
add_loop_hd()
void add_loop_hd (int lp)
If necessary create new preheader and trailer nodes for loop #lp, and set fgPre & fgPost to these nodes.
Definition at line 683 of file comminvar.c.
References add_fg(), add_loop_preheader(), add_stmt_after(), ast, FG_FT, FG_LPREV, FG_STDFIRST, fgPre, lp, LP_HEAD, mk_stmt(), opt, OPT::pre_fg, rdilts(), std, TRUE, and wrilts().
Referenced by get_temp_forall2().
check_inner_uses()
static LOGICAL check_inner_uses (int std, int lp, int nme) static
Definition at line 490 of file comminvar.c.
References def, DEF_DU, DEF_NEXT, DEF_STD, FALSE, FG_LOOP, is_parent_loop(), lp, DU_TAG::next, NME_DEF, std, TRUE, use, DU_TAG::use, and USE_FG.
Referenced by hoist_std().
check_moved()
static LOGICAL check_moved (int std) static
Definition at line 597 of file comminvar.c.
References FALSE, std, STD_DELETE, STD_MOVED, and TRUE.
Referenced by check_moved_list(), and hoist_std().
check_moved_list()
static LOGICAL check_moved_list (int n, int vstd[]) static
Definition at line 585 of file comminvar.c.
References check_moved(), FALSE, i, n, and TRUE.
Referenced by hoist_std().
check_outer_defs()
static LOGICAL check_outer_defs (int std, int lp, int nme) static
Definition at line 474 of file comminvar.c.
References def, DEF_FG, DEF_NEXT, DEF_STD, FALSE, FG_LOOP, is_parent_loop(), lp, NME_DEF, std, and TRUE.
Referenced by hoist_std().
clean_flags()
static void clean_flags (void) static
Definition at line 136 of file comminvar.c.
References A_CONDP, FALSE, std, STD_AST, STD_FIRST, STD_MOVED, and STD_NEXT.
Referenced by comm_invar().
comm_invar()
void comm_invar (void)
Hoist invariant communication expressions out of loops.
Definition at line 99 of file comminvar.c.
References clean_flags(), DBGBIT, dump_std(), FREE, gbl, get_loopcounts(), hlopt_end(), HLOPT_INDUC, hlopt_init(), hoist_loop(), lp, LP_CHILD, LP_SIBLING, mk_ztrips(), NULL, and pastCounts.
contains_alloc()
static LOGICAL contains_alloc (int lp) static
Definition at line 210 of file comminvar.c.
References ast, FALSE, fg, FG_NEXT, FG_STDFIRST, FG_STDLAST, interr(), lp, LP_FG, sptr, std, STD_AST, STD_NEXT, and TRUE.
Referenced by hoist_loop().
get_loopcounts()
static void get_loopcounts (void) static
Definition at line 148 of file comminvar.c.
References end_loop_count(), get_loop_count(), invariant_nomotion(), invariant_unmarkv(), lp, NEW, OPT::nloops, opt, and pastCounts.
Referenced by comm_invar().
has_invar_subs()
static LOGICAL has_invar_subs (int ast) static
Definition at line 538 of file comminvar.c.
References ASD_NDIM, ASD_SUBS, assert, ast, FALSE, interr(), is_invariant(), ndims, sub, and TRUE.
Referenced by hoist_std().
hoist_comms()
static void hoist_comms (int lp) static
Definition at line 248 of file comminvar.c.
References bMovedAssn, bMovedComm, ccff_info(), FALSE, fg, FG_LINENO, FG_LNEXT, FG_LOOP, FG_STDFIRST, FG_STDLAST, fgPre, flg, hoist_std(), FLG::hpf, is_dominator(), lp, LP_HEAD, LP_TAIL, MSGFTN, NULL, par, std, STD_DELETE, STD_MOVED, STD_NEXT, and STD_PAR.
Referenced by hoist_loop().
hoist_loop()
static LOGICAL hoist_loop (int lp) static
Definition at line 166 of file comminvar.c.
References close_pragma(), contains_alloc(), FALSE, FG_LINENO, fgPost, fgPre, hoist_comms(), hoist_loop(), invariant_nomotion(), invariant_unmarkv(), lp, LP_CHILD, LP_HEAD, LP_MEXITS, LP_SIBLING, open_pragma(), pastCounts, TRUE, and XBIT.
Referenced by comm_invar(), and hoist_loop().
hoist_std()
static void hoist_std (int fg, int std, int lp) static
Definition at line 331 of file comminvar.c.
References A_CONDG, ASD_NDIM, ASD_SUBS, assert, ast, bMovedAssn, bMovedComm, check_inner_uses(), check_moved(), check_moved_list(), check_outer_defs(), CONVAL2G, dim, fg, FG_LOOP, FT_ALLOC_FREE, FT_CCOPY_ALLOC, FT_CCOPY_FREE, FT_CCOPY_SECTL, FT_CCOPY_SECTR, FT_CGATHER_FREE, FT_CGATHER_MASK, FT_CGATHER_NVSUB, FT_CGATHER_SECTM, FT_CGATHER_SECTNVSUB, FT_CGATHER_SECTV, FT_CGATHER_SECTVSUB, FT_CGATHER_V, FT_CGATHER_VSUB, FT_CSTART_COMM, FT_CSTART_FREE, FT_CSTART_INVMVD, FT_CSTART_SECTL, FT_CSTART_SECTR, FT_SECT_ALLOC, FT_SECT_FREE, FT_SHIFT_BOUNDARY, FT_SHIFT_FREE, has_invar_subs(), INV, invariant_mark(), is_invariant(), is_invariant_base(), is_invariant_list(), is_sym_invariant_safe(), lp, mk_dealloc_stub(), move_invar_std(), ndim, NME_STL, std, STD_AST, TRUE, and unique_allo().
Referenced by hoist_comms().
is_invariant_base()
static LOGICAL is_invariant_base (int nme) static
Definition at line 513 of file comminvar.c.
References FALSE, is_invariant(), mk_id(), NME_SYM, NOSYM, and TRUE.
Referenced by hoist_std().
is_invariant_list()
static LOGICAL is_invariant_list (int n, int vast[]) static
Definition at line 573 of file comminvar.c.
References FALSE, i, is_invariant(), n, and TRUE.
Referenced by hoist_std().
is_parent_loop()
static LOGICAL is_parent_loop (int lpParent, int lpChild) static
Definition at line 526 of file comminvar.c.
References FALSE, LP_PARENT, and TRUE.
Referenced by check_inner_uses(), and check_outer_defs().
mk_count_test()
static int mk_count_test (int astCond, int astCount) static
Definition at line 706 of file comminvar.c.
References assert, ast, astb, DT_LOG, ASTB::i0, mk_binop(), OP_GT, and OP_LAND.
Referenced by move_invar_std().
mk_dealloc_stub()
static int mk_dealloc_stub (int astCond) static
Definition at line 724 of file comminvar.c.
References A_CONDP, add_stmt_after(), ast, FG_LINENO, fgPost, mk_stmt(), rdilts(), std, STD_LINENO, and wrilts().
Referenced by hoist_std().
mk_loop_hdtl()
static void mk_loop_hdtl (int lp) static
Definition at line 654 of file comminvar.c.
References add_fg(), add_loop_preheader(), add_single_loop_exit(), add_stmt_after(), ast, FG_FT, FG_LINENO, FG_LNEXT, FG_LPREV, FG_STDFIRST, fgPost, fgPre, lp, LP_HEAD, LP_TAIL, mk_stmt(), opt, OPT::pre_fg, rdilts(), std, STD_LINENO, TRUE, and wrilts().
Referenced by move_invar_std().
mk_ztrips()
static void mk_ztrips (int lp) static
Definition at line 742 of file comminvar.c.
References A_CONDG, add_stmt_before(), assert, ast, fg, FG_NEXT, FG_STDFIRST, FG_STDLAST, FREE, lp, LP_CHILD, LP_FG, LP_SIBLING, mk_stmt(), mk_ztrips(), NEW, OPT::nloops, NULL, opt, remove_cond(), std, STD_AST, and STD_NEXT.
Referenced by comm_invar(), and mk_ztrips().
move_invar_std()
static void move_invar_std (int std, int fg) static
Definition at line 609 of file comminvar.c.
References A_CONDG, A_CONDP, add_stmt_after(), fg, FG_LOOP, fgPre, mk_count_test(), mk_loop_hdtl(), mk_stmt(), pastCounts, rdilts(), std, STD_AST, STD_LABEL, STD_LAST, STD_LINENO, STD_MOVED, STD_NEXT, STD_PREV, TRUE, and wrilts().
Referenced by hoist_std().
remove_cond()
static int remove_cond (int astTarg, int astSrc) static
Definition at line 843 of file comminvar.c.
References A_OPTYPEG, DT_LOG, mk_binop(), OP_LAND, and remove_cond().
Referenced by mk_ztrips(), and remove_cond().
unique_allo()
static LOGICAL unique_allo (int allo_std, int allo_ft, int lp) static
Definition at line 300 of file comminvar.c.
References ast, FALSE, fg, FG_NEXT, FG_STDFIRST, FG_STDLAST, FT_ALLOC_SPTR, lp, LP_FG, std, STD_AST, STD_NEXT, and TRUE.
Referenced by hoist_std().
Variable Documentation
bMovedAssn
LOGICAL bMovedAssn static
Definition at line 94 of file comminvar.c.
Referenced by hoist_comms(), and hoist_std().
bMovedComm
LOGICAL bMovedComm static
Definition at line 93 of file comminvar.c.
Referenced by hoist_comms(), and hoist_std().
fgPost
int fgPost static
Definition at line 92 of file comminvar.c.
Referenced by hoist_loop(), mk_dealloc_stub(), and mk_loop_hdtl().
fgPre
int fgPre static
Definition at line 91 of file comminvar.c.
Referenced by add_loop_hd(), hoist_comms(), hoist_loop(), mk_loop_hdtl(), and move_invar_std().
pastCounts
int* pastCounts = NULL static
Definition at line 95 of file comminvar.c.
Referenced by comm_invar(), get_loopcounts(), hoist_loop(), and move_invar_std().