flang: commopt.c File Reference
commopt.c File Reference
Fortran communications optimizer module.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "comm.h"
#include "symtab.h"
#include "dtypeutl.h"
#include "soc.h"
#include "semant.h"
#include "ast.h"
#include "gramtk.h"
#include "transfrm.h"
#include "extern.h"
#include "commopt.h"
#include "ccffinfo.h"
#include "optimize.h"
#include "nme.h"
#include "rte.h"
#include "hlvect.h"
#include "symutl.h"
Functions
static void commopt (void)
static void comm_optimize_init (void)
static LOGICAL same_forall_bnds (int, int, int)
static LOGICAL is_fusable (int lp, int lp1, int nested)
...
static LOGICAL smp_conflict (int, int)
static LOGICAL is_in_block (int, int)
static LOGICAL Conflict (int, int, int, LOGICAL, int, int)
static LOGICAL is_branch_between (int, int)
static LOGICAL is_contains_ast_between (int, int, int)
static LOGICAL is_same_align_shape (int, int, int, int)
static void comm_optimize_end (void)
static void eliminate_rt (int)
static void eliminate_bnds (int, int, int, int)
static void eliminate_alloc (int, int, int, int)
static void eliminate_sect (int, int, int, int)
static void eliminate_copy (int, int, int, int)
static void eliminate_gather (int, int, int, int)
static void eliminate_shift (int, int, int, int)
static void eliminate_start (int, int, int, int)
static void eliminate_get_scalar (void)
static void fuse_forall (int)
static LOGICAL is_same_descr_for_bnds (int, int)
static LOGICAL Conflict_ (int)
static LOGICAL is_same_idx (int, int)
static LOGICAL is_dominator_fg (int, int)
static LOGICAL must_follow (int, int, int, int)
int find_lp (int)
static void init_optsum (void)
static void optsummary (void)
static void alloc2ast (void)
static void opt_allocate (void)
LOGICAL is_same_def (int, int)
static LOGICAL is_safe_copy (int)
static LOGICAL is_allocatable_assign (int ast)
static int propagate_bound (LITEMF *defs_to_propagate, int bound)
static void rewrite_all_shape (LITEMF *)
static void decompose_expression (int, int[], int, int *, int *)
static LOGICAL is_avail_expr_with_list (int, int, int, int, int, int[], int)
static void put_forall_fg (void)
static LOGICAL independent_commtype (int, int)
static LOGICAL is_olap_conflict (int, int)
static LOGICAL is_pcalls (int, int)
static void forall_make_same_idx (int)
static void selection_sort (void)
void comm_optimize_post (void)
void comm_optimize_pre (void)
void forall_init (void)
LOGICAL same_forall_size (int lp1, int lp2, int nested)
static LOGICAL _olap_conflict (int expr, int expr1)
static LOGICAL is_same_array_bounds (int sub, int sub1, int std, int std1, int fg, int fg1)
static LOGICAL is_same_array_bounds_for_schedule (int sub, int sub1, int std, int std1, int fg, int fg1)
LOGICAL is_same_array_alignment (int sptr, int sptr1)
static LOGICAL is_same_array_alignment_for_schedule (int sptr, int sptr1)
LOGICAL is_same_array_shape (int sptr, int sptr1)
void init_gstbl (void)
void free_gstbl (void)
int get_gstbl (void)
void init_brtbl (void)
void free_brtbl (void)
int get_brtbl (void)
void init_ftb (void)
int mk_ftb (void)
LITEMF * clist (void)
void plist (LITEMF *list, int item)
int glist (LITEMF *list, int n)
LOGICAL inlist (LITEMF *list, int item)
void dlist (LITEMF *list)
void optimize_alloc (void)
Try to optimize allocate statements.
void put_forall_pcalls (int fstd)
Put forall calls into forall tables.
void find_get_scalar (void)
Put all get_scalar into table to easily process.
Variables
int rewrite_opfields
INT * lpsort
FTB ftb
OPTSUM optsum
struct {
int otherlhs
int src
int sink
int list
int after
int order
int forcomm
} conf
Detailed Description
Fortran communications optimizer module.
Definition in file commopt.c.
Function Documentation
_olap_conflict()
static LOGICAL _olap_conflict (int expr, int expr1) static
Definition at line 790 of file commopt.c.
References _olap_conflict(), A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, FALSE, i, interr(), is_shift_conflict(), nargs, r, and TRUE.
Referenced by _olap_conflict(), and is_olap_conflict().
alloc2ast()
static void alloc2ast (void) static
Definition at line 2794 of file commopt.c.
References A_STDP, A_TKNG, assert, ast, FTB::avl, delete_stmt(), FALSE, FT_ALLOC_FREE, FT_ALLOC_OUT, FT_ALLOC_PTASGN, FT_ALLOC_REUSE, FT_ALLOC_SAME, FT_ALLOC_SPTR, FT_ALLOC_USED, FT_FORALL, FT_STD, ftb, i, mk_ftb(), new_node(), sptr, start, std, STD_AST, STD_IGNORE, STD_NEXT, STD_PREV, and TRUE.
Referenced by comm_optimize_post().
clist()
LITEMF * clist (void)
Definition at line 2656 of file commopt.c.
References FORALL_AREA, getitem(), and list.
Referenced by conv_allocate(), forall_opt1(), getcyclic(), opt_allocate(), put_forall_pcalls(), record_barrier(), remove_mask_calls(), and remove_stmt_calls().
comm_optimize_end()
static void comm_optimize_end (void) static
Definition at line 2626 of file commopt.c.
References induction_end(), optshrd_end(), and optshrd_fend().
Referenced by comm_optimize_post(), comm_optimize_pre(), and optimize_alloc().
comm_optimize_init()
static void comm_optimize_init (void) static
Definition at line 2618 of file commopt.c.
References induction_init(), optshrd_finit(), and optshrd_init().
Referenced by comm_optimize_post(), comm_optimize_pre(), and optimize_alloc().
comm_optimize_post()
void comm_optimize_post (void)
Definition at line 123 of file commopt.c.
References alloc2ast(), comm_optimize_end(), comm_optimize_init(), commopt(), DBGBIT, dump_flowgraph(), dump_loops(), findloop(), flow(), flowgraph(), HLOPT_ALL, optsummary(), and rewrite_opfields.
comm_optimize_pre()
void comm_optimize_pre (void)
Definition at line 156 of file commopt.c.
References comm_optimize_end(), comm_optimize_init(), DBGBIT, dump_flowgraph(), dump_loops(), findloop(), flow(), flowgraph(), fuse_forall(), HLOPT_ALL, and selection_sort().
commopt()
static void commopt (void) static
Definition at line 312 of file commopt.c.
References eliminate_get_scalar(), eliminate_rt(), put_forall_fg(), selection_sort(), and XBIT.
Referenced by comm_optimize_post().
Conflict()
static LOGICAL Conflict (int list, int src, int sink, LOGICAL after, int order, int forcomm) static
Definition at line 664 of file commopt.c.
References after, conf, Conflict_(), forcomm, list, order, sink, and src.
Referenced by is_fusable().
Conflict_()
static LOGICAL Conflict_ (int sink) static
Definition at line 679 of file commopt.c.
References a, A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, conf, Conflict_(), dd_array_conflict(), DDTG, FALSE, i, interr(), nargs, p, r, result, sink, sptr, src, sym_of_ast(), and TRUE.
Referenced by Conflict(), and Conflict_().
decompose_expression()
static void decompose_expression (int expr, int a[], int size, int * nvar, int * onlyvar) static
Definition at line 3311 of file commopt.c.
References a, A_ARGCNTG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, decompose_expression(), i, interr(), n, ndim, and size.
Referenced by decompose_expression(), is_avail_expr_with_list(), and is_safe_copy().
dlist()
void dlist (LITEMF * list)
Definition at line 2718 of file commopt.c.
References dfile, FILE, gbl, list, and p.
eliminate_alloc()
static void eliminate_alloc (int lp, int lp1, int rt_std, int rt1_std) static
Definition at line 1745 of file commopt.c.
References OPTSUM::alloc, assert, DTY, fg, FG_STDFIRST, FT_ALLOC_FREE, FT_ALLOC_OUT, FT_ALLOC_REUSE, FT_ALLOC_SAME, FT_ALLOC_SPTR, FT_ALLOC_USED, is_dominator_fg(), is_same_array_alignment(), is_same_array_bounds(), lp, LP_FG, LP_FORALL, LP_HEAD, LP_PARENT, optsum, sptr, std, STD_AST, STD_DELETE, and sub.
Referenced by eliminate_rt().
eliminate_bnds()
static void eliminate_bnds (int lp, int lp1, int rt_std, int rt1_std) static
Definition at line 1562 of file commopt.c.
References assert, astb, OPTSUM::bnd, fg, FG_STDFIRST, FT_BND_SAME, ASTB::i1, is_avail_expr(), is_same_descr_for_bnds(), lb, lp, LP_FG, LP_FORALL, LP_HEAD, optsum, st, std, STD_AST, STD_DELETE, and ub.
Referenced by eliminate_rt().
eliminate_copy()
static void eliminate_copy (int lp, int lp1, int rt_std, int rt1_std) static
Definition at line 2010 of file commopt.c.
References assert, BOGUSFLAG, copy(), OPTSUM::copysection, fg, FG_STDFIRST, FT_CCOPY_FREE, FT_CCOPY_LHS, FT_CCOPY_LHSSEC, FT_CCOPY_NOTLHS, FT_CCOPY_OUT, FT_CCOPY_REUSE, FT_CCOPY_RHS, FT_CCOPY_SAME, FT_CCOPY_SECTL, FT_CCOPY_SECTR, FT_CCOPY_TSPTR, FT_SECT_FLAG, is_dominator_fg(), is_same_array_alignment_for_schedule(), is_same_array_bounds_for_schedule(), left_array_symbol(), lhs, lp, LP_FG, LP_FORALL, LP_HEAD, LP_PARENT, optsum, sptr, std, STD_AST, STD_DELETE, sub, and XBIT.
Referenced by eliminate_rt().
eliminate_gather()
static void eliminate_gather (int lp, int lp1, int rt_std, int rt1_std) static
Definition at line 2127 of file commopt.c.
References ASD_NDIM, assert, fg, FG_STDFIRST, FT_CGATHER_FREE, FT_CGATHER_LHSSEC, FT_CGATHER_MASK, FT_CGATHER_NOTLHS, FT_CGATHER_NVSUB, FT_CGATHER_OUT, FT_CGATHER_PERMUTE, FT_CGATHER_PFLAG, FT_CGATHER_REUSE, FT_CGATHER_SAME, FT_CGATHER_TYPE, FT_CGATHER_V, FT_CGATHER_VFLAG, FT_CGATHER_VSUB, OPTSUM::gatherx, i, is_avail_expr(), is_same_array_alignment_for_schedule(), is_same_array_bounds_for_schedule(), left_array_symbol(), left_subscript_ast(), lp, LP_FG, LP_FORALL, LP_HEAD, LP_PARENT, ndim, optsum, OPTSUM::scatterx, sptr, std, STD_AST, STD_DELETE, sub, and XBIT.
Referenced by eliminate_rt().
eliminate_get_scalar()
static void eliminate_get_scalar (void) static
Definition at line 2518 of file commopt.c.
References assert, tbl::avl, tbl::base, TABLE::f1, fg, find_get_scalar(), free_gstbl(), FT_GETSCLR_REUSE, FT_GETSCLR_SAME, gstbl, i, init_gstbl(), is_avail_expr(), is_dominator(), j, src, STD_AST, STD_DELETE, and STD_FG.
Referenced by commopt().
eliminate_rt()
static void eliminate_rt (int type0) static
Definition at line 1356 of file commopt.c.
References assert, eliminate_alloc(), eliminate_bnds(), eliminate_copy(), eliminate_gather(), eliminate_sect(), eliminate_shift(), eliminate_start(), FG_STDFIRST, FT_FG, FT_HEADER, FT_NRT, FT_RTL, header(), i, independent_commtype(), is_branch_between(), is_dominator(), itemlist::item, j, k, LP_FORALL, LP_HEAD, lpsort, itemlist::next, OPT::nloops, opt, std, STD_AST, STD_DELETE, and type.
Referenced by commopt().
eliminate_sect()
static void eliminate_sect (int lp, int lp1, int rt_std, int rt1_std) static
Definition at line 1863 of file commopt.c.
References assert, DTY, fg, FG_STDFIRST, FT_ALLOC_OUT, FT_SECT_ALLOC, FT_SECT_FLAG, FT_SECT_FREE, FT_SECT_OUT, FT_SECT_REUSE, FT_SECT_SAME, FT_SECT_SPTR, getbit(), is_dominator_fg(), is_same_array_alignment(), is_same_array_bounds(), is_same_array_shape(), is_whole_array(), lp, LP_FG, LP_FORALL, LP_HEAD, LP_PARENT, optsum, OPTSUM::sect, sectflag, sptr, std, STD_AST, STD_DELETE, and sub.
Referenced by eliminate_rt().
eliminate_shift()
static void eliminate_shift (int lp, int lp1, int rt_std, int rt1_std) static
Definition at line 2259 of file commopt.c.
References ASD_NDIM, ASD_SUBS, assert, DTY, fg, FG_STDFIRST, FT_SHIFT_BOUNDARY, FT_SHIFT_FREE, FT_SHIFT_OUT, FT_SHIFT_REUSE, FT_SHIFT_SAME, FT_SHIFT_TYPE, get_int_cval(), i, is_avail_expr(), is_dominator_fg(), is_same_array_alignment(), is_same_array_shape(), left_array_symbol(), left_subscript_ast(), lp, LP_FG, LP_FORALL, LP_HEAD, LP_PARENT, mk_subscr(), mk_triple(), ndim, optsum, replace_ast_subtree(), OPTSUM::shift, shift, sptr, src, std, STD_AST, STD_DELETE, sub, and XBIT.
Referenced by eliminate_rt().
eliminate_start()
static void eliminate_start (int lp, int lp1, int rt_std, int rt1_std) static
Definition at line 2372 of file commopt.c.
References assert, ast, cp, dest, fg, FG_STDFIRST, FT_ALLOC_FREE, FT_ALLOC_USED, FT_CCOPY_OUT, FT_CGATHER_OUT, FT_CSTART_ALLOC, FT_CSTART_COMM, FT_CSTART_FREE, FT_CSTART_OUT, FT_CSTART_REUSE, FT_CSTART_RHS, FT_CSTART_SAME, FT_CSTART_TYPE, FT_SHIFT_OUT, is_avail_expr(), is_dominator_fg(), is_same_array_alignment(), is_same_array_bounds(), left_array_symbol(), left_subscript_ast(), lp, LP_FG, LP_FORALL, LP_HEAD, optsum, sptr, src, start, OPTSUM::start, std, STD_AST, STD_DELETE, and sub.
Referenced by eliminate_rt().
find_get_scalar()
void find_get_scalar (void)
Put all get_scalar into table to easily process.
Definition at line 3624 of file commopt.c.
References ast, tbl::base, TABLE::f1, FT_GETSCLR_NOMEM, FT_GETSCLR_OMEMED, FT_GETSCLR_REUSE, FT_GETSCLR_SAME, FT_STD, get_gstbl(), gstbl, i, mk_ftb(), std, STD_AST, STD_NEXT, and type.
Referenced by eliminate_get_scalar(), and generate_get_scalar().
find_lp()
int find_lp (int std)
Definition at line 1727 of file commopt.c.
References assert, FG_STDFIRST, i, LP_HEAD, OPT::nloops, opt, and std.
forall_init()
void forall_init (void)
Definition at line 182 of file commopt.c.
References ast, forall_make_same_idx(), forall_opt1(), init_bnd(), init_dtb(), init_ftb(), init_optsum(), put_forall_pcalls(), set_descriptor_sc(), std, STD_AST, STD_BLKSYM, STD_LABEL, and STD_NEXT.
forall_make_same_idx()
static void forall_make_same_idx (int std) static
Definition at line 3533 of file commopt.c.
References A_NCOUNTG, A_NCOUNTP, A_STDP, assert, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), ASTLI_NEXT, ASTLI_SPTR, cnt, FT_NPCALL, FT_PCALL, get_init_idx(), i, idx, list, mk_id(), nc, past(), plist(), st, std, STD_AST, and STD_TASK.
Referenced by forall_init().
free_brtbl()
void free_brtbl (void)
Definition at line 2600 of file commopt.c.
References tbl::base, brtbl, and FREE.
Referenced by convert_output().
free_gstbl()
void free_gstbl (void)
Definition at line 2573 of file commopt.c.
References tbl::base, FREE, and gstbl.
Referenced by eliminate_get_scalar(), and generate_get_scalar().
fuse_forall()
static void fuse_forall (int nested) static
Definition at line 330 of file commopt.c.
References fg, FG_STDFIRST, FT_FUSED, FT_FUSEDSTD, FT_FUSELP, FT_HEADER, FT_NFUSE, OPTSUM::fuse, i, is_dominator(), is_fusable(), is_same_idx(), j, LP_FG, LP_FORALL, LP_HEAD, LP_PARENT, lpsort, MAXFUSE, OPT::nloops, opt, optsum, same_forall_bnds(), std, STD_ACCEL, STD_AST, and STD_BLKSYM.
Referenced by comm_optimize_pre().
get_brtbl()
int get_brtbl (void)
Definition at line 2606 of file commopt.c.
References tbl::avl, tbl::base, brtbl, errfatal(), NEED, NULL, tbl::size, and SPTR_MAX.
Referenced by record_barrier().
get_gstbl()
int get_gstbl (void)
Definition at line 2580 of file commopt.c.
References tbl::avl, tbl::base, errfatal(), gstbl, NEED, NULL, tbl::size, and SPTR_MAX.
Referenced by find_get_scalar().
glist()
int glist (LITEMF * list, int n)
Definition at line 2687 of file commopt.c.
References assert, i, itemlist::item, list, n, and itemlist::next.
Referenced by add_mask_calls(), add_stmt_calls(), call_comm(), conv_deallocate(), conv_forall(), eliminate_redundant(), find_calls_pos(), find_mask_calls_pos(), find_max_of_mask_calls_pos(), find_stmt_calls_pos(), insert_call_comm(), insert_forall_comm(), is_call_dependent(), is_mask_call_dependent(), is_same_mask_in_fused(), is_stmt_call_dependent(), opt_allocate(), put_call_comm(), put_calls(), put_forall_pcalls(), sequentialize_call(), sequentialize_mask_call(), sequentialize_stmt_call(), shape_comm(), shape_communication(), and tag_call_comm().
independent_commtype()
static LOGICAL independent_commtype (int type, int type0) static
Definition at line 1502 of file commopt.c.
References assert, FALSE, TRUE, and type.
Referenced by eliminate_rt().
init_brtbl()
void init_brtbl (void)
Definition at line 2592 of file commopt.c.
References tbl::avl, tbl::base, brtbl, NEW, and tbl::size.
Referenced by comm_init().
init_ftb()
void init_ftb (void)
Definition at line 2636 of file commopt.c.
References FTB::avl, FTB::base, ftb, NEW, and FTB::size.
Referenced by forall_init().
init_gstbl()
void init_gstbl (void)
Definition at line 2565 of file commopt.c.
References tbl::avl, tbl::base, gstbl, NEW, and tbl::size.
Referenced by eliminate_get_scalar(), and generate_get_scalar().
init_optsum()
static void init_optsum (void) static
Definition at line 265 of file commopt.c.
References OPTSUM::alloc, OPTSUM::bnd, OPTSUM::copysection, OPTSUM::fuse, OPTSUM::gatherx, optsum, OPTSUM::scatterx, OPTSUM::sect, OPTSUM::shift, and OPTSUM::start.
Referenced by forall_init().
inlist()
LOGICAL inlist (LITEMF * list, int item)
Definition at line 2704 of file commopt.c.
References FALSE, list, p, and TRUE.
Referenced by inline_spread_shifts(), normalize_forall(), normalize_forall_array(), normalize_id(), and rewrite_all_shape().
is_allocatable_assign()
static LOGICAL is_allocatable_assign (int ast) static
Definition at line 3013 of file commopt.c.
References ast, dest, FALSE, src, sym_of_ast(), TRUE, and XBIT.
Referenced by opt_allocate().
is_avail_expr_with_list()
static LOGICAL is_avail_expr_with_list (int expr, int std, int fg, int std1, int fg1, int idx[], int cnt) static
Definition at line 1290 of file commopt.c.
References cnt, decompose_expression(), FALSE, fg, i, idx, is_avail_expr(), j, NULL, size, std, and TRUE.
Referenced by is_fusable().
is_branch_between()
static LOGICAL is_branch_between (int lp, int lp1) static
Definition at line 1221 of file commopt.c.
References ast, FALSE, fg, FG_LNEXT, FG_STDFIRST, lp, LP_FG, LP_HEAD, rdilts(), std, STD_AST, STD_BR, STD_NEXT, TRUE, type, and wrilts().
Referenced by eliminate_rt(), and is_fusable().
is_contains_ast_between()
static LOGICAL is_contains_ast_between (int lp, int lp1, int a) static
Definition at line 1256 of file commopt.c.
References a, ast, contains_ast(), FALSE, fg, FG_LNEXT, FG_STDFIRST, lp, LP_FG, LP_HEAD, rdilts(), std, STD_AST, STD_NEXT, TRUE, and wrilts().
Referenced by is_fusable().
is_dominator_fg()
static LOGICAL is_dominator_fg (int std, int std1) static
Definition at line 1965 of file commopt.c.
References FALSE, is_dominator(), std, STD_FG, and TRUE.
Referenced by eliminate_alloc(), eliminate_copy(), eliminate_sect(), eliminate_shift(), and eliminate_start().
is_fusable()
static LOGICAL is_fusable (int lp, int lp1, int nested) static
...
  S1: A(i) = ...
  S2: ...  = ... A(f(i)) ...
The loops cannot be fused if either of the following calls to dd_array_conflict() return TRUE:
  dd_array_conflict(tripletList, A(f(i)), A(i), FALSE)
  dd_array_conflict(tripletList, A(i), A(f(i)), TRUE)
Alternatively, the statements within the original loops may be of the following form:
  S1: ...  = ... A(f(i))
  S2: A(i) = ...
The loops cannot be fused if the following call to dd_array_conflict() returns TRUE.
  dd_array_conflict(tripletList, A(i), A(f(i)), FALSE)
The back end recognizes loops with 0 RHS and transforms these into calls to _mzero, so don't fuse assignments with just 0 on the RHS.
Definition at line 912 of file commopt.c.
References ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, cnt, conf, Conflict(), contains_ast(), FALSE, fg, FG_STDFIRST, flg, FT_FUSELP, FT_NFUSE, idx, is_avail_expr_with_list(), is_branch_between(), is_contains_ast_between(), is_dominator(), is_fusable(), is_in_block(), is_olap_conflict(), k, lhs, list, lp, LP_FG, LP_HEAD, LP_PARENT, mk_id(), FLG::opt, smp_conflict(), std, STD_AST, subscr_dependent(), sym_of_ast(), TRUE, and XBIT.
Referenced by fuse_forall(), and is_fusable().
is_in_block()
static LOGICAL is_in_block (int std, int std1) static
Definition at line 1189 of file commopt.c.
References assert, FALSE, FT_FUSEDSTD, FT_HEADER, FT_NFUSE, header(), k, std, STD_AST, and STD_NEXT.
Referenced by is_fusable().
is_olap_conflict()
static LOGICAL is_olap_conflict (int forall, int forall1) static
Definition at line 849 of file commopt.c.
References _olap_conflict(), FALSE, and TRUE.
Referenced by is_fusable().
is_pcalls()
static LOGICAL is_pcalls (int std, int fstd) static
Definition at line 3514 of file commopt.c.
References ast, error(), FALSE, is_impure(), sptr, std, STD_AST, STD_LINENO, SYMNAME, and TRUE.
Referenced by put_forall_pcalls().
is_safe_copy()
static LOGICAL is_safe_copy (int deflist) static
Definition at line 3070 of file commopt.c.
References a, addnme(), ast, decompose_expression(), def, DEF_FG, DEF_NEXT, DEF_STD, dest, FALSE, fg, i, must_follow(), NME_DEF, NT_VAR, src, std, STD_AST, and TRUE.
Referenced by propagate_bound().
is_same_align_shape()
static LOGICAL is_same_align_shape (int sptr, int dim, int sptr1, int dim1) static
Definition at line 1556 of file commopt.c.
References TRUE.
Referenced by is_same_descr_for_bnds(), and same_forall_bnds().
is_same_array_alignment()
LOGICAL is_same_array_alignment (int sptr, int sptr1)
Definition at line 1708 of file commopt.c.
References TRUE.
Referenced by eliminate_alloc(), eliminate_sect(), eliminate_shift(), eliminate_start(), and is_same_mask().
is_same_array_alignment_for_schedule()
static LOGICAL is_same_array_alignment_for_schedule (int sptr, int sptr1) static
Definition at line 1720 of file commopt.c.
References TRUE.
Referenced by eliminate_copy(), and eliminate_gather().
is_same_array_bounds()
static LOGICAL is_same_array_bounds (int sub, int sub1, int std, int std1, int fg, int fg1) static
Definition at line 1615 of file commopt.c.
References ASD_NDIM, ASD_SUBS, astb, count, FALSE, fg, i, ASTB::i1, interr(), is_avail_expr(), lb, ndim, st, std, sub, TRUE, and ub.
Referenced by eliminate_alloc(), eliminate_sect(), and eliminate_start().
is_same_array_bounds_for_schedule()
static LOGICAL is_same_array_bounds_for_schedule (int sub, int sub1, int std, int std1, int fg, int fg1) static
Definition at line 1701 of file commopt.c.
References TRUE.
Referenced by eliminate_copy(), and eliminate_gather().
is_same_array_shape()
LOGICAL is_same_array_shape (int sptr, int sptr1)
Definition at line 1824 of file commopt.c.
References AD_DPTR, AD_LWAST, AD_UPAST, FALSE, i, lb, ndim, rank_of_sym(), result, sptr, TRUE, and ub.
Referenced by eliminate_sect(), and eliminate_shift().
is_same_def()
LOGICAL is_same_def (int def, int def1)
Definition at line 3155 of file commopt.c.
References ast, def, DEF_FG, DEF_NEXT, DEF_STD, FALSE, fg, is_avail_expr(), is_dominator(), next, std, STD_AST, and TRUE.
is_same_descr_for_bnds()
static LOGICAL is_same_descr_for_bnds (int rt, int rt1) static
Definition at line 1531 of file commopt.c.
References dim, FALSE, FT_BND_LHS, get_int_cval(), is_same_align_shape(), left_array_symbol(), lhs, and sptr.
Referenced by eliminate_bnds().
is_same_idx()
static LOGICAL is_same_idx (int std, int std1) static
Definition at line 399 of file commopt.c.
References ASTLI_NEXT, ASTLI_SPTR, FALSE, i, idx, list, std, STD_AST, and TRUE.
Referenced by fuse_forall().
mk_ftb()
int mk_ftb (void)
Definition at line 2644 of file commopt.c.
References FTB::avl, FTB::base, errfatal(), ftb, NEED, NULL, and FTB::size.
Referenced by alloc2ast(), emit_copy_section(), emit_overlap(), emit_scatterx_gatherx(), find_get_scalar(), forall_opt1(), make_sec_ast(), move_mask_calls(), put_forall_pcalls(), remove_mask_calls(), remove_stmt_calls(), temp_copy_section(), and temp_gatherx().
must_follow()
static LOGICAL must_follow (int fg1, int std1, int fg2, int std2) static
Definition at line 1983 of file commopt.c.
References FALSE, fg, FG_PDOM, FG_STDFIRST, is_dominator(), rdilts(), std, STD_NEXT, TRUE, and wrilts().
Referenced by is_safe_copy().
opt_allocate()
static void opt_allocate (void) static
Definition at line 2902 of file commopt.c.
References A_TKNG, AD_DPTR, ASD_SUBS, assert, ast, ast_replace(), ast_unvisit(), ast_visit(), astb, clist(), def, DEF_STD, dest, DTY, ERR_Fatal, FALSE, FORALL_AREA, freearea(), glist(), i, ASTB::i1, is_allocatable_assign(), MAXSUBS, mk_id(), mk_subscr(), mk_triple(), ndim, itemlist::nitem, plist(), propagate_bound(), rank_of_sym(), rewrite_all_shape(), sptr, src, ss, std, STD_AST, STD_NEXT, STD_PAR, sub, and TRUE.
Referenced by optimize_alloc().
optimize_alloc()
void optimize_alloc (void)
Try to optimize allocate statements.
If they have same bounds, give them the same bound variable. This will help the compiler to reduce # of communication for allocatable variables.
Definition at line 2877 of file commopt.c.
References comm_optimize_end(), comm_optimize_init(), DBGBIT, dump_flowgraph(), dump_loops(), findloop(), flow(), flowgraph(), HLOPT_ALL, opt_allocate(), and postdominators().
optsummary()
static void optsummary (void) static
Definition at line 280 of file commopt.c.
References OPTSUM::alloc, OPTSUM::bnd, OPTSUM::copysection, FILE, OPTSUM::fuse, OPTSUM::gatherx, gbl, NULL, optsum, OPTSUM::scatterx, OPTSUM::sect, OPTSUM::shift, OPTSUM::start, and SYMNAME.
Referenced by comm_optimize_post().
plist()
void plist (LITEMF * list, int item)
Definition at line 2667 of file commopt.c.
References assert, FORALL_AREA, getitem(), itemlist::item, last, list, and itemlist::next.
Referenced by canonical_conversion(), conv_allocate(), do_nml(), emit_copy_section(), emit_gatherx(), emit_overlap(), emit_scatterx_gatherx(), fix_symbol(), forall_make_same_idx(), lower_namelist_plists(), make_sec_ast(), opt_allocate(), propagate_bound(), put_forall_pcalls(), and read_symbol().
propagate_bound()
static int propagate_bound (LITEMF * defs_to_propagate, int bound) static
Definition at line 3041 of file commopt.c.
References addnme(), assert, ast, bound, def, DEF_STD, ERR_Fatal, is_safe_copy(), NME_DEF, NT_VAR, plist(), sptr, std, STD_AST, and sym_of_ast().
Referenced by opt_allocate().
put_forall_fg()
static void put_forall_fg (void) static
Definition at line 1337 of file commopt.c.
References FG_STDFIRST, FT_FG, i, LP_FORALL, LP_HEAD, lpsort, OPT::nloops, opt, std, and STD_AST.
Referenced by commopt().
put_forall_pcalls()
void put_forall_pcalls (int fstd)
Put forall calls into forall tables.
FT_MCALL will have calls used in the mask.
FT_SCALL will have calls used in the statement.
These later will be used to parallel calls.
Definition at line 3401 of file commopt.c.
References A_ARGCNTG, arg, argt, ARGT_ARG, assert, clist(), contains_ast(), expr_dependent(), FT_CALL_CALL, FT_CALL_NCALL, FT_CALL_POS, FT_CALL_SPTR, FT_MCALL, FT_NMCALL, FT_NPCALL, FT_NSCALL, FT_PCALL, FT_SCALL, glist(), i, is_pcalls(), j, mk_ftb(), mk_id(), nargs, past(), plist(), STD_AST, STD_NEXT, STD_PURE, sym_of_ast(), and TRUE.
Referenced by forall_init().
rewrite_all_shape()
static void rewrite_all_shape (LITEMF * exceptions) static
Definition at line 3244 of file commopt.c.
References ast_is_sym(), ast_rewrite(), astb, flg, ASTB::hash, i, inlist(), MAXDIMS, ndim, set_parref_flag2(), ASTB::shd, SHD_LWB, SHD_NEXT, SHD_STRIDE, SHD_UPB, FLG::smp, and sym_of_ast().
Referenced by opt_allocate().
same_forall_bnds()
static LOGICAL same_forall_bnds (int lp1, int lp2, int nested) static
Definition at line 518 of file commopt.c.
References ASD_NDIM, ASD_SUBS, assert, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), astb, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, FALSE, FG_STDFIRST, i, ASTB::i1, is_avail_expr(), is_dominator(), is_duplicate(), is_name_in_expr(), is_ordered(), is_same_align_shape(), k, left_array_symbol(), left_subscript_ast(), LP_FG, LP_HEAD, MAXDIMS, mk_id(), no, STD_AST, and TRUE.
Referenced by fuse_forall().
same_forall_size()
LOGICAL same_forall_size (int lp1, int lp2, int nested)
Definition at line 437 of file commopt.c.
References astb, ASTLI_NEXT, ASTLI_TRIPLE, ASTB::bnd, ASTB::dtype, FALSE, FG_STDFIRST, i, ASTB::i1, is_avail_expr(), is_dominator(), LP_FG, LP_HEAD, mk_binop(), OP_SUB, STD_AST, and TRUE.
Referenced by get_temp_forall2().
selection_sort()
static void selection_sort (void) static
Definition at line 91 of file commopt.c.
References ast, dom, FG_STDFIRST, FORALL_AREA, getitem(), i, INT, is_dominator(), j, LP_HEAD, lpsort, OPT::nloops, opt, std, STD_AST, and t.
Referenced by comm_optimize_pre(), and commopt().
smp_conflict()
static LOGICAL smp_conflict (int fg1, int fg2) static
Definition at line 1108 of file commopt.c.
References ast, FALSE, fg, FG_CS, FG_LNEXT, FG_PAR, FG_PARSECT, FG_STDFIRST, flg, rdilts(), FLG::smp, std, STD_AST, STD_NEXT, TRUE, and wrilts().
Referenced by is_fusable().
Variable Documentation
after
int after
Definition at line 655 of file commopt.c.
Referenced by __gen_conditional_dealloc(), add_fg(), addbih(), addilt(), addnewbih(), check_alloc_ptr_type(), Conflict(), dealloc_dt_auto(), exp_addbih(), gen_conditional_alloc(), gen_conditional_dealloc(), inline_RTE_set_type(), and mk_deallocate_scalar().
struct { ... } conf
Referenced by Conflict(), Conflict_(), and is_fusable().
forcomm
int forcomm
Definition at line 657 of file commopt.c.
Referenced by Conflict().
ftb
FTB ftb
Definition at line 87 of file commopt.c.
Referenced by alloc2ast(), convert_output(), init_ftb(), mk_ftb(), move_mask_calls(), remove_mask_calls(), and remove_stmt_calls().
list
int list
Definition at line 654 of file commopt.c.
Referenced by __fort_chain_em_up(), _contains_forall_index(), add_init(), add_subscript_list(), add_to_list(), addCopyinInplace(), args_match(), assign_array_w_forall(), binop_init_list(), build_array_list(), build_name_buffer(), build_subscript_list(), canonical_conversion(), change_forall_triple(), check_alloc_clauses(), check_arguments(), check_dealloc_clauses(), chk_arguments(), clear_list_nodes_visited(), clist(), compute_permute(), Conflict(), conv_allocate(), conv_deallocate(), copy_section_temp_before(), count_actuals(), defer_arg_chk(), defined_operator(), dlist(), eliminate_extra_idx(), emit_copy_section(), emit_gatherx(), emit_permute_section(), emit_scatterx_gatherx(), emit_sum_scatterx(), ENTFTN(), evl_kwd_args(), find_best_generic(), find_modname_in_list(), find_next_modname_in_list(), fix_proc_pointer_call(), forall_2_sec(), forall_lhs_indirection(), forall_list_call(), forall_make_same_idx(), forall_semantic(), forall_with_mask(), func_call(), func_call2(), gatherx_temp_before(), generic_call(), generic_func(), generic_tbp_call(), generic_tbp_func(), get_keyword_args(), get_kwd_args(), glist(), in_wheresymlist(), inline_reduction_f90(), inline_spread_shifts(), inlist(), is_array_element_in_forall(), is_duplicate(), is_fusable(), is_idx(), is_intrinsic_opr(), is_legal_lhs(), is_legal_lhs_for_mask(), is_multiple_idx_in_list(), is_one_idx_for_dim(), is_ordered(), is_same_idx(), is_same_number_of_idx(), is_scalar(), is_sptr_in_shared_list(), is_triplet(), is_use_lhs(), is_use_lhs_final(), is_vector_indirection_in_it(), is_vector_subscript(), kwd_match(), llvm_add_to_init_list(), llvm_write_ctor_dtor_list(), make_forall(), make_list(), makeCopyprivArray(), makeCopyprivArray_tls(), mark_used_in_independent(), mkvarref(), normalize_forall_array(), normalize_forall_triplet(), par_body(), permute_axis(), plist(), process_lhs_sub(), process_sub(), ptrfunc_call(), ptrsubr_call(), putslnk1(), putsymlk(), ref_array(), ref_intrin(), ref_intrin_subr(), ref_pd(), ref_pd_subr(), reference_for_temp(), remove_list(), rename_forall_list(), resolve_defined_io(), resolve_generic(), rewrite_block_forall(), rewrite_cmplxpart_rval(), search_idx(), semantio(), simple_reference_for_temp(), sptrListAdd(), sptrListFree(), subr_call(), subr_call2(), sum_scatter_args(), sym_in_sym_list(), sym_visible_in_scope(), unop_init_list(), unvisit(), update_list_exceptions(), visit_list_free(), visit_list_push(), and visit_list_scan().
lpsort
INT* lpsort
Definition at line 86 of file commopt.c.
Referenced by eliminate_rt(), fuse_forall(), put_forall_fg(), and selection_sort().
optsum
OPTSUM optsum
Definition at line 88 of file commopt.c.
Referenced by eliminate_alloc(), eliminate_bnds(), eliminate_copy(), eliminate_gather(), eliminate_sect(), eliminate_shift(), eliminate_start(), fuse_forall(), init_optsum(), and optsummary().
order
int order
Definition at line 656 of file commopt.c.
Referenced by advance_permuted(), compute_permute(), Conflict(), ENTFTN(), eval_reshape(), gen_llvm_cmpxchg(), and is_ordered().
otherlhs
int otherlhs
Definition at line 651 of file commopt.c.
rewrite_opfields
int rewrite_opfields extern
Definition at line 4358 of file ast.c.
Referenced by comm_optimize_post().
sink
int sink
Definition at line 653 of file commopt.c.
Referenced by Conflict(), Conflict_(), and dd_edge().
src
int src
Definition at line 652 of file commopt.c.
Referenced by __c_mcopy1(), __c_mcopy16(), __c_mcopy2(), __c_mcopy4(), __c_mcopy8(), __fort_adjust_index_array(), __fort_ftnstrcpy(), __fort_get_scalar(), __fort_rbcst(), __fort_rbcstl(), _constructf90(), _mp_copypriv_kmpc(), add_ptr_assign(), append_init_list(), ast_rewrite(), at_local_mode(), broadcast(), build_poly_func_node(), collapse_assignment(), Conflict(), Conflict_(), conv_allocate(), copy_specifics(), copy_sym_flags(), copystr(), dd_edge(), dup_acl(), eliminate_get_scalar(), eliminate_shift(), eliminate_start(), emit_kopy_in(), emit_permute_section(), emit_scalar_kopy_in(), end_or_err(), ENT3F(), enter_local_mode(), ENTF90(), ENTFTN(), eval_transfer(), exit_local_mode(), fill_cyclic_k(), find_descrs(), forall_lhs_indirection(), forall_with_mask(), Ftn_imvbits(), Ftn_jmvbits(), Ftn_kmvbits(), ftnstrcpy(), gen_contig_check(), gen_defer_shape(), generate_copy(), generate_get_scalar(), genPolyAsn(), get_source_and_dest_sizes(), inline_contig_check(), insert_forall_comm(), is_allocatable_assign(), is_safe_copy(), is_same_mask_in_fused(), is_same_number_of_idx(), is_use_lhs(), is_use_lhs_final(), local_gather_CPLX16(), local_gather_CPLX32(), local_gather_CPLX8(), local_gather_INT1(), local_gather_INT2(), local_gather_INT4(), local_gather_INT8(), local_gather_LOG1(), local_gather_LOG2(), local_gather_LOG4(), local_gather_LOG8(), local_gather_REAL16(), local_gather_REAL4(), local_gather_REAL8(), local_gather_WRAPPER(), local_gathscat_CPLX16(), local_gathscat_CPLX32(), local_gathscat_CPLX8(), local_gathscat_INT1(), local_gathscat_INT2(), local_gathscat_INT4(), local_gathscat_INT8(), local_gathscat_LOG1(), local_gathscat_LOG2(), local_gathscat_LOG4(), local_gathscat_LOG8(), local_gathscat_REAL16(), local_gathscat_REAL4(), local_gathscat_REAL8(), local_gathscat_WRAPPER(), local_scatter_CPLX16(), local_scatter_CPLX32(), local_scatter_CPLX8(), local_scatter_INT1(), local_scatter_INT2(), local_scatter_INT4(), local_scatter_INT8(), local_scatter_LOG1(), local_scatter_LOG2(), local_scatter_LOG4(), local_scatter_LOG8(), local_scatter_REAL16(), local_scatter_REAL4(), local_scatter_REAL8(), local_scatter_WRAPPER(), lower_data_stmts(), lower_numelm(), lower_stmt(), mk_atomic_read(), mk_conformable_test(), mk_poly_test(), NORM2_REAL4(), NORM2_REAL8(), olap_send(), opt_allocate(), process_final_procedures(), ref_pd(), semant3(), tag_forall_comm(), tempify_ast(), transfer_load(), transform_forall(), and transform_ptr().