flang: comm.h File Reference
comm.h File Reference
#include "gbldefs.h"
#include "transfrm.h"
#include <stdio.h>
Classes
struct SUBINFO
struct SCATTER_TYPE
struct comminfo
struct ARREF
struct TDESC
struct TRANSFORM
Macros
#define COMMT_NOTAG -1 /* no tag attached yet */
#define COMMT_NONE 0 /* no communication */
#define COMMT_MULTI 1 /* multicast */
#define COMMT_SHIFTC 2 /* constant shift */
#define COMMT_SHIFTV 3 /* variable shift */
#define COMMT_TRANSFER 4 /* transfer */
#define COMMT_REPLICATE 5 /* replication */
#define COMMT_CONST 6 /* index */
#define COMMT_UNSTRUCT 7 /* unstructured communication */
#define SUBI_IDX(i) trans.subb.stg_base[i].idx
#define SUBI_STRIDE(i) trans.subb.stg_base[i].stride
#define SUBI_BASE(i) trans.subb.stg_base[i].base
#define SUBI_SUB(i) trans.subb.stg_base[i].sub
#define SUBI_DSTT(i) trans.subb.stg_base[i].dst_type
#define SUBI_LDIM(i) trans.subb.stg_base[i].lhs_dim
#define SUBI_NEWL(i) trans.subb.stg_base[i].newl
#define SUBI_NEWU(i) trans.subb.stg_base[i].newu
#define SUBI_NEWS(i) trans.subb.stg_base[i].news
#define SUBI_DSTT(i) trans.subb.stg_base[i].dst_type
#define SUBI_COMMT(i) trans.subb.stg_base[i].comm_type
#define SUBI_COMMV(i) trans.subb.stg_base[i].comm_value
#define SUBI_CNST(i) trans.subb.stg_base[i].cnst
#define SUBI_DIFF(i) trans.subb.stg_base[i].diff
#define SUBI_LOF(i) trans.subb.stg_base[i].lof
#define SUBI_DUPL(i) trans.subb.stg_base[i].dupl
#define SUBI_NOP(i) trans.subb.stg_base[i].nop
#define SUBI_POP(i) trans.subb.stg_base[i].pop
#define NO_CLASS 0
#define NO_COMM 1
#define OVERLAP 2
#define COLLECTIVE 3
#define COPY_SECTION 4
#define GATHER 5
#define SCATTER 6
#define IRREGULAR 7
#define ARREF_CLASS(i) trans.arrb.stg_base[i].class
#define ARREF_FLAG(i) trans.arrb.stg_base[i].flag
#define ARREF_TEMP(i) trans.arrb.stg_base[i].temp
#define ARREF_ARRSYM(i) trans.arrb.stg_base[i].arrsym
#define ARREF_ARR(i) trans.arrb.stg_base[i].arr
#define ARREF_SUB(i) trans.arrb.stg_base[i].sub
#define ARREF_NDIM(i) trans.arrb.stg_base[i].ndim
#define ARREF_NEXT(i) trans.arrb.stg_base[i].next
#define TD_LHS(i) trans.tdescb.stg_base[i].lhs
#define TD_RHS(i) trans.tdescb.stg_base[i].rhs
#define FORALL_PFX "i_"
#define TMPL_PFX "tmpl_"
#define PROC_PFX "proc_"
#define INIT_PFX "init_"
#define COMMON_PFX "cmn_"
#define TRANS_ALLOC(stgb, dt, sz)
#define TRANS_MORE(stb, dt, nsz)
#define TRANS_NEED(stb, dt, nsz)
#define TRANS_FREE(stb) FREE(stb.stg_base)
Functions
LOGICAL is_same_number_of_idx (int dest, int src, int list)
LOGICAL normalize_bounds (int sptr)
Return TRUE if the bounds of array sptr should be 1-based with respect to the runtime.
int add_lbnd (int dtyp, int dim, int ast, int astmember)
Construct an AST to add the lower bound of dimension dim for array datatype dtyp to ast, and return the new AST.
int insert_endmask (int ast, int stdstart)
Create ENDIF statements corresponding to conditional statements emitted for mask expression ast. Insert the ENDIFs after stdstart. Return the STD of the last statement added.
int insert_mask (int ast, int stdstart)
Create mask statements for conditional expression ast and insert them after stdstart. Return the STD of the last statement added.
int record_barrier (LOGICAL, int, int)
This routine a barrier statement in the barrier table.
int sub_lbnd (int dtyp, int dim, int ast, int astmember)
Construct an AST to subtract the lower bound of dimension dim for array datatype dtyp to ast, and return the new AST.
void check_region (int std)
Check a region is valid.
void comm_analyze (void)
Communication analyzer entry point.
void comm_fini (void)
Finalize the phase and free allocated memory.
void init_region (void)
Keep track of STD of endcritical or endmaster statement.
void report_comm (int std, int cause)
Dump compiler internal information for the communication analyzer.
int reference_for_temp (int sptr, int a, int forall)
This routine finds the dimension of sptr.
int emit_get_scalar (int a, int std)
This routine is to read distributed array element at forall by using get scalar primitive.
void forall_opt1 (int ast)
void transform_forall (int std, int ast)
void scalarize (int std, int forall, LOGICAL after_transformer)
The forall should be treated like a serial statement.
void un_fuse (int forall)
This is necessary, if forall sequentialized.
void sequentialize (int std, int forall, LOGICAL after_transformer)
Variables
struct comminfo comminfo
TRANSFORM trans
Macro Definition Documentation
ARREF_ARR
#define ARREF_ARR (i) trans.arrb.stg_base[i].arr
Definition at line 118 of file comm.h.
ARREF_ARRSYM
#define ARREF_ARRSYM (i) trans.arrb.stg_base[i].arrsym
Definition at line 117 of file comm.h.
ARREF_CLASS
#define ARREF_CLASS (i) trans.arrb.stg_base[i].class
Definition at line 114 of file comm.h.
ARREF_FLAG
#define ARREF_FLAG (i) trans.arrb.stg_base[i].flag
Definition at line 115 of file comm.h.
ARREF_NDIM
#define ARREF_NDIM (i) trans.arrb.stg_base[i].ndim
Definition at line 120 of file comm.h.
ARREF_NEXT
#define ARREF_NEXT (i) trans.arrb.stg_base[i].next
Definition at line 121 of file comm.h.
ARREF_SUB
#define ARREF_SUB (i) trans.arrb.stg_base[i].sub
Definition at line 119 of file comm.h.
ARREF_TEMP
#define ARREF_TEMP (i) trans.arrb.stg_base[i].temp
Definition at line 116 of file comm.h.
COLLECTIVE
#define COLLECTIVE 3
Definition at line 97 of file comm.h.
COMMON_PFX
#define COMMON_PFX "cmn_"
Definition at line 165 of file comm.h.
COMMT_CONST
#define COMMT_CONST 6 /* index */
Definition at line 46 of file comm.h.
COMMT_MULTI
#define COMMT_MULTI 1 /* multicast */
Definition at line 41 of file comm.h.
COMMT_NONE
#define COMMT_NONE 0 /* no communication */
Definition at line 40 of file comm.h.
COMMT_NOTAG
#define COMMT_NOTAG -1 /* no tag attached yet */
Definition at line 39 of file comm.h.
COMMT_REPLICATE
#define COMMT_REPLICATE 5 /* replication */
Definition at line 45 of file comm.h.
COMMT_SHIFTC
#define COMMT_SHIFTC 2 /* constant shift */
Definition at line 42 of file comm.h.
COMMT_SHIFTV
#define COMMT_SHIFTV 3 /* variable shift */
Definition at line 43 of file comm.h.
COMMT_TRANSFER
#define COMMT_TRANSFER 4 /* transfer */
Definition at line 44 of file comm.h.
COMMT_UNSTRUCT
#define COMMT_UNSTRUCT 7 /* unstructured communication */
Definition at line 47 of file comm.h.
COPY_SECTION
#define COPY_SECTION 4
Definition at line 98 of file comm.h.
FORALL_PFX
#define FORALL_PFX "i_"
Definition at line 161 of file comm.h.
GATHER
#define GATHER 5
Definition at line 99 of file comm.h.
INIT_PFX
#define INIT_PFX "init_"
Definition at line 164 of file comm.h.
IRREGULAR
#define IRREGULAR 7
Definition at line 101 of file comm.h.
NO_CLASS
#define NO_CLASS 0
Definition at line 94 of file comm.h.
NO_COMM
#define NO_COMM 1
Definition at line 95 of file comm.h.
OVERLAP
#define OVERLAP 2
Definition at line 96 of file comm.h.
PROC_PFX
#define PROC_PFX "proc_"
Definition at line 163 of file comm.h.
SCATTER
#define SCATTER 6
Definition at line 100 of file comm.h.
SUBI_BASE
#define SUBI_BASE (i) trans.subb.stg_base[i].base
Definition at line 51 of file comm.h.
SUBI_CNST
#define SUBI_CNST (i) trans.subb.stg_base[i].cnst
Definition at line 61 of file comm.h.
SUBI_COMMT
#define SUBI_COMMT (i) trans.subb.stg_base[i].comm_type
Definition at line 59 of file comm.h.
SUBI_COMMV
#define SUBI_COMMV (i) trans.subb.stg_base[i].comm_value
Definition at line 60 of file comm.h.
SUBI_DIFF
#define SUBI_DIFF (i) trans.subb.stg_base[i].diff
Definition at line 62 of file comm.h.
SUBI_DSTT [1/2]
#define SUBI_DSTT (i) trans.subb.stg_base[i].dst_type
Definition at line 58 of file comm.h.
SUBI_DSTT [2/2]
#define SUBI_DSTT (i) trans.subb.stg_base[i].dst_type
Definition at line 58 of file comm.h.
SUBI_DUPL
#define SUBI_DUPL (i) trans.subb.stg_base[i].dupl
Definition at line 64 of file comm.h.
SUBI_IDX
#define SUBI_IDX (i) trans.subb.stg_base[i].idx
Definition at line 49 of file comm.h.
SUBI_LDIM
#define SUBI_LDIM (i) trans.subb.stg_base[i].lhs_dim
Definition at line 54 of file comm.h.
SUBI_LOF
#define SUBI_LOF (i) trans.subb.stg_base[i].lof
Definition at line 63 of file comm.h.
SUBI_NEWL
#define SUBI_NEWL (i) trans.subb.stg_base[i].newl
Definition at line 55 of file comm.h.
SUBI_NEWS
#define SUBI_NEWS (i) trans.subb.stg_base[i].news
Definition at line 57 of file comm.h.
SUBI_NEWU
#define SUBI_NEWU (i) trans.subb.stg_base[i].newu
Definition at line 56 of file comm.h.
SUBI_NOP
#define SUBI_NOP (i) trans.subb.stg_base[i].nop
Definition at line 65 of file comm.h.
SUBI_POP
#define SUBI_POP (i) trans.subb.stg_base[i].pop
Definition at line 66 of file comm.h.
SUBI_STRIDE
#define SUBI_STRIDE (i) trans.subb.stg_base[i].stride
Definition at line 50 of file comm.h.
SUBI_SUB
#define SUBI_SUB (i) trans.subb.stg_base[i].sub
Definition at line 52 of file comm.h.
TD_LHS
#define TD_LHS (i) trans.tdescb.stg_base[i].lhs
Definition at line 128 of file comm.h.
TD_RHS
#define TD_RHS (i) trans.tdescb.stg_base[i].rhs
Definition at line 129 of file comm.h.
TMPL_PFX
#define TMPL_PFX "tmpl_"
Definition at line 162 of file comm.h.
TRANS_ALLOC
#define TRANS_ALLOC (stgb, dt, sz)
Value:
  {                               \
    NEW(stgb.stg_base, dt, sz);   \
    stgb.stg_size = sz;           \
    stgb.stg_avail = 1;           \
  }
Definition at line 169 of file comm.h.
TRANS_FREE
#define TRANS_FREE (stb) FREE(stb.stg_base)
Definition at line 189 of file comm.h.
TRANS_MORE
#define TRANS_MORE (stb, dt, nsz)
Value:
  {                                                                         \
    stb.stg_base =                                                          \
        (dt *)sccrelal((char *)stb.stg_base, ((BIGUINT64)((nsz) * sizeof(dt)))); \
    stb.stg_size = nsz;                                                     \
    if (stb.stg_base == NULL)                                               \
      error(7, 4, 0, CNULL, CNULL);                                         \
  }
Definition at line 176 of file comm.h.
TRANS_NEED
#define TRANS_NEED (stb, dt, nsz)
Value:
  if (stb.stg_avail > stb.stg_size) \
    TRANS_MORE(stb, dt, nsz);
Definition at line 185 of file comm.h.
Function Documentation
add_lbnd()
int add_lbnd (int dtyp, int dim, int ast, int astmember)
Construct an AST to add the lower bound of dimension dim for array datatype dtyp to ast, and return the new AST.
Definition at line 332 of file tools/flang1/flang1exe/comm.c.
References ADD_LWAST, ast, astb, ASTB::bnd, check_member(), dim, ASTB::dtype, mk_binop(), ASTB::one, OP_ADD, and OP_SUB.
Referenced by conv_forall(), gen_islocal_index(), gen_localize_index(), generate_hcycliclp(), generate_hlocalizebnds(), and get_allobnds().
check_region()
void check_region (int std)
Check a region is valid.
Definition at line 197 of file tools/flang1/flang1exe/comm.c.
References A_STDG, ast, pure_gbl::end_critical_region, pure_gbl::end_master_region, std, and STD_AST.
Referenced by call_analyze(), comm_analyze(), and convert_forall().
comm_analyze()
void comm_analyze (void)
Communication analyzer entry point.
Definition at line 118 of file tools/flang1/flang1exe/comm.c.
comm_fini()
void comm_fini (void)
Finalize the phase and free allocated memory.
Definition at line 101 of file tools/flang1/flang1exe/comm.c.
References TRANSFORM::arrb, FINFO_TBL::base, finfot, FREE, free_pertbl(), NULL, TRANSFORM::stg_base, TRANSFORM::subb, TRANSFORM::tdescb, trans, and TRANS_FREE.
Referenced by convert_output().
emit_get_scalar()
int emit_get_scalar (int a, int std)
This routine is to read distributed array element at forall by using get scalar primitive.
Definition at line 614 of file tools/flang1/flang1exe/comm.c.
References a, A_STDP, add_stmt_before(), ALIGNG, ASD_NDIM, ast, check_member(), dist_ast(), DISTG, DTY, ld, memsym_of_ast(), mk_id(), ndim, new_node(), replace_ast_subtree(), std, STD_LOCAL, sym_get_scalar(), and SYMNAME.
Referenced by get_scalar_in_expr().
forall_opt1()
void forall_opt1 (int ast)
Algorithm:
  gather information about lhs array.
  tag communications for rhs array.
  optimize overlap_shift if there is same array shift.
  optimize copy_section
  convert to forall into block forall since owner computes rule distribution
  for cyclic require complicated statement insertion.
  forall_gbl.s0....
  forall_gbl.s1 forall(i=.
  forall_gbl.s2   A(i)=
  forall_gbl.s3 endforall
  forall_gbl.s4, forall_gbl.s5 ...
These variables are globals.
  forall_gbl.s1 moves up.
  forall_gbl.s4 moves down.
Definition at line 671 of file tools/flang1/flang1exe/comm.c.
References A_STDG, ast, clist(), FT_BARR1, FT_BARR2, FT_CYCLIC, FT_FG, FT_FUSED, FT_FUSELP, FT_HEADER, FT_IGNORE, FT_MCALL, FT_MGET, FT_NFUSE, FT_NMCALL, FT_NMGET, FT_NPCALL, FT_NRT, FT_NSCALL, FT_NSGET, FT_PCALL, FT_RTL, FT_SCALL, FT_SECTL, FT_SGET, getcyclic(), i, j, MAXFUSE, mk_ftb(), and std.
Referenced by copy_arg_to_seq_tmp(), forall_init(), and transform_forall().
init_region()
void init_region (void)
Keep track of STD of endcritical or endmaster statement.
Definition at line 187 of file tools/flang1/flang1exe/comm.c.
References pure_gbl::end_critical_region, and pure_gbl::end_master_region.
Referenced by call_analyze(), comm_analyze(), convert_forall(), and transform_init().
insert_endmask()
int insert_endmask (int ast, int stdstart)
Create ENDIF statements corresponding to conditional statements emitted for mask expression ast. Insert the ENDIFs after stdstart. Return the STD of the last statement added.
Definition at line 248 of file tools/flang1/flang1exe/comm.c.
References A_OPTYPEG, add_stmt_after(), ast, insert_endmask(), mk_stmt(), OP_SCAND, and std.
Referenced by conv_forall(), conv_fused_forall(), insert_endmask(), and sequentialize().
insert_mask()
int insert_mask (int ast, int stdstart)
Create mask statements for conditional expression ast and insert them after stdstart. Return the STD of the last statement added.
Definition at line 225 of file tools/flang1/flang1exe/comm.c.
References A_OPTYPEG, add_stmt_after(), ast, insert_mask(), mk_stmt(), OP_SCAND, and std.
Referenced by conv_forall(), conv_fused_forall(), insert_mask(), and sequentialize().
is_same_number_of_idx()
LOGICAL is_same_number_of_idx (int dest, int src, int list)
Definition at line 376 of file tools/flang1/flang1exe/comm.c.
References ASD_NDIM, ASD_SUBS, count, dest, FALSE, j, list, ndim, search_forall_var(), src, and TRUE.
Referenced by is_use_lhs(), and is_use_lhs_final().
normalize_bounds()
LOGICAL normalize_bounds (int sptr)
Return TRUE if the bounds of array sptr should be 1-based with respect to the runtime.
Definition at line 368 of file tools/flang1/flang1exe/comm.c.
References FALSE, sptr, and XBIT.
Referenced by conv_forall(), emit_alnd(), emit_get_scalar_sub(), emit_kopy_in(), emit_secd(), fill_argt_with_alnd(), gen_islocal_index(), gen_localize_index(), generate_get_scalar(), generate_hcycliclp(), generate_hlocalizebnds(), get_allobnds(), inline_hlocalizebnds(), interface_for_entry(), interface_for_llvmiface(), lower_ast(), newargs_for_entry(), and rewrite_func_ast().
record_barrier()
int record_barrier (LOGICAL bBefore, int astStmt, int std)
This routine a barrier statement in the barrier table.
Definition at line 582 of file tools/flang1/flang1exe/comm.c.
References tbl::base, brtbl, clist(), TABLE::f1, TABLE::f2, TABLE::f3, get_brtbl(), i, itemlist::item, sptr, std, and sym_of_ast().
reference_for_temp()
int reference_for_temp (int sptr, int a, int forall)
This routine finds the dimension of sptr.
It takes subscript a(f(i),5,f(j)). It eliminates scalar dimension. It makes an ast for reference sptr: a(f(i),5,f(j)) --> sptr(f(i),f(j))
NOTE: This is always called after get_temp_forall(), which calls mk_forall_sptr(). The subscripts are not always as simple as sptr(f(i),f(j)), especially if the stride is not known. if the stride is not +1 or -1, the subscript will be normalized.
Definition at line 457 of file tools/flang1/flang1exe/comm.c.
References a, ASD_NDIM, ASD_SUBS, assert, ast, astb, ASTLI_SPTR, ASTLI_TRIPLE, c, check_member(), constant_stride(), STB::dt_int, DTY, flg, i, ASTB::i1, interr(), k, list, mk_binop(), mk_id(), mk_subscr(), mk_triple(), ndim, OP_ADD, OP_DIV, OP_SUB, FLG::opt, other_forall_var(), rank_of_sym(), search_forall_var(), sptr, stb, stride, STB::user, value(), and XBIT.
Referenced by forall_dependency(), and forall_dependency_scalarize().
report_comm()
void report_comm (int std, int cause)
Dump compiler internal information for the communication analyzer.
Definition at line 267 of file tools/flang1/flang1exe/comm.c.
References assert, CANONICAL_CAUSE, ccff_info(), COPYSCALAR_CAUSE, COPYSECTION_CAUSE, DEPENDENCY_CAUSE, GETSCALAR_CAUSE, INTRINSIC_CAUSE, MANYRUNTIME_CAUSE, MSGFTN, NULL, PURECOMM_CAUSE, std, STD_AST, STD_LINENO, STD_MINFO, UGLYCOMM_CAUSE, UGLYMASK_CAUSE, UGLYPURE_CAUSE, and XBIT.
Referenced by emit_get_scalar_sub(), forall_dependency(), generate_get_scalar(), and transform_forall().
scalarize()
void scalarize (int std, int forall, LOGICAL after_transformer)
The forall should be treated like a serial statement.
Turn it into a block-forall so the IF stuff works OK.
Definition at line 810 of file tools/flang1/flang1exe/comm.c.
References forall_dependency_scalarize(), sequentialize(), std, STD_AST, and transform_forall().
Referenced by copy_arg_to_seq_tmp(), forall_semantic(), and transform_forall().
sequentialize()
void sequentialize (int std, int forall, LOGICAL after_transformer)
Definition at line 860 of file tools/flang1/flang1exe/comm.c.
References A_STDG, add_stmt_before(), ast_to_comment(), ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, delete_stmt(), i, index_var, insert_endmask(), insert_mask(), lineno, mk_id(), mk_stmt(), n, sequentialize_mask_call(), sequentialize_stmt_call(), std, STD_AST, STD_LINENO, STD_NEXT, STD_PREV, transform_ast(), and un_fuse().
Referenced by process_forall(), and scalarize().
sub_lbnd()
int sub_lbnd (int dtyp, int dim, int ast, int astmember)
Construct an AST to subtract the lower bound of dimension dim for array datatype dtyp to ast, and return the new AST.
Definition at line 350 of file tools/flang1/flang1exe/comm.c.
References ADD_LWAST, ast, astb, ASTB::bnd, check_member(), dim, ASTB::dtype, mk_binop(), ASTB::one, OP_ADD, and OP_SUB.
Referenced by conv_forall(), emit_get_scalar_sub(), gen_islocal_index(), gen_localize_index(), generate_get_scalar(), generate_hcycliclp(), and generate_hlocalizebnds().
transform_forall()
void transform_forall (int std, int ast)
Definition at line 710 of file tools/flang1/flang1exe/comm.c.
References ast, CANONICAL_CAUSE, canonical_conversion(), dest, pure_gbl::end_critical_region, fix_guard_forall(), comminfo::forall, forall_opt1(), FT_NRT, init_opt_tables(), insert_call_comm(), insert_forall_comm(), is_scatter(), MANYRUNTIME_CAUSE, comminfo::mask_phase, normalize_forall_triplet(), opt_overlap(), process_lhs_sub(), report_comm(), TRANSFORM::rhsbase, scalar_communication(), scalarize(), shape_communication(), src, comminfo::std, std, STD_AST, tag_call_comm(), tag_forall_comm(), trans, TRUE, comminfo::ugly_mask, UGLYCOMM_CAUSE, UGLYMASK_CAUSE, comminfo::unstruct, and comminfo::usedstd.
Referenced by comm_analyze(), copy_arg_to_seq_tmp(), emit_sum_scatterx(), and scalarize().
un_fuse()
void un_fuse (int forall)
This is necessary, if forall sequentialized.
Definition at line 837 of file tools/flang1/flang1exe/comm.c.
References A_STDG, assert, FT_FUSEDSTD, FT_HEADER, FT_NFUSE, i, and STD_AST.
Referenced by forall_dependency(), and sequentialize().
Variable Documentation
comminfo
struct comminfo comminfo extern
Definition at line 39 of file commdf.c.
Referenced by emit_sum_scatterx().
trans
TRANSFORM trans extern
Definition at line 23 of file commdf.c.
Referenced by comm_fini(), comm_init(), dumparref(), opt_overlap(), process_lhs_sub(), process_rhs_sub(), and transform_forall().