flang: copy.c File Reference
copy.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "fort_vars.h"
Classes
struct copy_sect
struct copy_parm
Functions
static void I8() copy_xfer_loop (copy_parm *z, copy_sect *ly, __INT_T offset, __INT_T dim)
static void I8() copy_xfer (copy_parm *z, copy_sect *ly, copy_sect *ry, __INT_T offset, __INT_T cnt)
static void I8() copy_loop (copy_parm *z, copy_sect *ly, copy_sect *ry, __INT_T offset, __INT_T cnt, int dim)
void I8() copy_setup (copy_sect *y, char *b, F90_Desc *c, int *axis_map)
chdr *I8() __fort_copy (void *db, void *sb, F90_Desc *dc, F90_Desc *sc, int *src_axis_map)
void ENTFTN (PERMUTE_SECTION, permute_section)
void ENTFTN (COPY_SECTION, copy_section)
sked * ENTFTN (COMM_COPY, comm_copy)
void ENTFTN (TRANSPOSE, transpose)
void ENTFTN (COPY_SCALAR, copy_scalar)
Variables
static int identity_map [MAXDIMS] = {1, 2, 3, 4, 5, 6, 7}
static int _1 = 1
Function Documentation
__fort_copy()
chdr *I8() __fort_copy (void * db, void * sb, F90_Desc * dc, F90_Desc * sc, int * src_axis_map)
Definition at line 670 of file copy.c.
References _1, __BOGUSBOUNDS, __DESC, __fort_abort(), __fort_calloc(), __fort_chain_em_up(), __fort_chn_1to1(), __fort_chn_prune(), __fort_describe_replication(), __fort_finish_section(), __fort_free(), __fort_recvl(), __fort_sendl(), __fort_set_section(), __fort_show_index(), __fort_show_section(), __fort_test, copy_loop(), copy_setup(), copy_xfer(), db(), dc, DEBUG_COPY, DECL_DIM_PTRS, DIST_ACTUAL_ARG_G, DIST_ACTUAL_ARG_P, DIST_DPTR_TAXIS_G, DIST_DPTR_TLB_G, DIST_DPTR_TUB_G, DIST_REPLICATED_G, DIST_SCOFF_G, DPTR_UBOUND_G, ds(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_FLAGS_P, F90_GSIZE_G, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_LCPU, GET_DIST_TCPUS_ADDR, i, I8, identity_map, j, LOCAL_MODE, Max, Min, n, NULL, offset, sb, SET_DIM_PTRS, sg, chdr::sn, ss, and z.
Referenced by cshift_loop(), ENTFTN(), eoshift_scalar(), and recopy().
copy_loop()
static void I8() copy_loop (copy_parm * z, copy_sect * ly, copy_sect * ry, __INT_T offset, __INT_T cnt, int dim) static
Definition at line 295 of file copy.c.
References __fort_abort(), __fort_block_bounds(), __fort_free(), __fort_new_gen_block(), __fort_test, cl, chdr::cn, cnt, copy_loop(), copy_xfer(), cs, DEBUG_COPY, DECL_DIM_PTRS, DECL_HDR_PTRS, DFMT, DFMT_GEN_BLOCK, dim, DIST_DPTR_BLOCK_G, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CNO_G, DIST_DPTR_CS_G, DIST_DPTR_GEN_BLOCK_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_TLB_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, DIST_DPTR_TUB_G, DIST_MAPPED_G, DPTR_UBOUND_G, error(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, GET_DIST_LCPU, i, I8, j, Min, n, off, offset, rc, chdr::rn, SET_DIM_PTRS, and z.
Referenced by __fort_copy(), and copy_loop().
copy_setup()
void I8() copy_setup (copy_sect * y, char * b, F90_Desc * c, int * axis_map)
Definition at line 643 of file copy.c.
References __fort_cycle_bounds(), __OFF_TEMPLATE, b, c, DECL_DIM_PTRS, DIST_DPTR_CN_G, DPTR_UBOUND_G, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_LSIZE_G, F90_RANK_G, i, I8, SET_DIM_PTRS, and y.
Referenced by __fort_copy().
copy_xfer()
static void I8() copy_xfer (copy_parm * z, copy_sect * ly, copy_sect * ry, __INT_T offset, __INT_T cnt) static
Definition at line 146 of file copy.c.
References __fort_abort(), __fort_chn_1toN(), __fort_sendl(), __fort_test, copy_xfer_loop(), DEBUG_COPY, DECL_DIM_PTRS, DECL_HDR_PTRS, DFMT__MASK, DFMT__WIDTH, DFMT_COLLAPSED, DIST_DFMT_G, DIST_DIST_TARGET_G, DIST_DPTR_PSTRIDE_G, DIST_PBASE_G, DIST_REPLICATED_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, F90_RANK_G, GET_DIST_LCPU, i, I8, if(), LOCAL_MODE, m, MAXDIMS, NULL, offset, p, pc, pd, rc, SET_DIM_PTRS, and z.
Referenced by __fort_copy(), and copy_loop().
copy_xfer_loop()
static void I8() copy_xfer_loop (copy_parm * z, copy_sect * ly, __INT_T offset, __INT_T dim) static
Definition at line 106 of file copy.c.
References __fort_show_scalar(), __fort_test, cnt, copy_xfer_loop(), DEBUG_COPY, DECL_DIM_PTRS, DECL_HDR_PTRS, dim, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, F90_KIND_G, F90_LEN_G, GET_DIST_LCPU, I8, offset, SET_DIM_PTRS, str, and z.
Referenced by copy_xfer(), and copy_xfer_loop().
ENTFTN() [1/5]
sked * ENTFTN (COMM_COPY , comm_copy)
Definition at line 1009 of file copy.c.
References __DESC, __fort_abort(), __fort_comm_sked(), __fort_copy(), DIST_SCOFF_G, F90_KIND_G, F90_LEN_G, F90_TAG_G, I8, ISPRESENT, NULL, rb, chdr::rp, sb, chdr::sp, and ss.
ENTFTN() [2/5]
void ENTFTN (COPY_SCALAR , copy_scalar)
Definition at line 1062 of file copy.c.
References __DESC, __DIST_INIT_SECTION, __fort_abort(), __fort_copy(), __fort_doit(), __fort_finish_section(), __fort_frechn(), __fort_set_single(), __SCALAR, __SINGLE, DECL_HDR_PTRS, DECL_HDR_VARS, dim, DIST_SCOFF_G, DIST_SCOFF_P, F90_KIND_G, F90_KIND_P(), F90_LBASE_P, F90_LEN_G, F90_LEN_P, F90_RANK_G, F90_TAG_G, I8, index, ISPRESENT, NULL, sb, chdr::sp, ss, and va.
ENTFTN() [3/5]
void ENTFTN (COPY_SECTION , copy_section)
Definition at line 984 of file copy.c.
References __DESC, __fort_abort(), __fort_copy(), __fort_doit(), __fort_frechn(), DIST_SCOFF_G, F90_LEN_G, F90_TAG_G, I8, ISPRESENT, NULL, rb, chdr::rp, sb, chdr::sp, and ss.
ENTFTN() [4/5]
void ENTFTN (PERMUTE_SECTION , permute_section)
Definition at line 953 of file copy.c.
References __DESC, __fort_abort(), __fort_copy(), __fort_doit(), __fort_frechn(), DIST_SCOFF_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, i, I8, ISPRESENT, MAXDIMS, NULL, rb, chdr::rp, sb, chdr::sp, ss, and va.
ENTFTN() [5/5]
void ENTFTN (TRANSPOSE , transpose)
Definition at line 1033 of file copy.c.
References __DESC, __fort_abort(), __fort_copy(), __fort_doit(), __fort_frechn(), DIST_SCOFF_G, F90_LEN_G, F90_TAG_G, I8, ISPRESENT, MAXDIMS, NULL, rb, chdr::rp, sb, chdr::sp, and ss.
Variable Documentation
_1
int _1 = 1 static
Definition at line 56 of file copy.c.
Referenced by __fort_copy(), __fort_kred_arraylk(), __fort_red_array(), and __fort_red_arraylk().
identity_map
int identity_map[MAXDIMS] = {1, 2, 3, 4, 5, 6, 7} static
Definition at line 23 of file copy.c.
Referenced by __fort_copy(), and ENTFTN().