flang: cos.c File Reference
cos.c File Reference
#include "mthdecls.h"
Functions
float __mth_i_cos (float f)
Function Documentation
__mth_i_cos()
float __mth_i_cos (float f)
Definition at line 11 of file cos.c.
References cosf(), and f.
Referenced by __gs_cos_4(), and __gs_cos_4m().