flang: cprof2.c File Reference
cprof2.c File Reference
Functions
void __fort_prof_arecv (int cpu, long len, int reqn)
void __fort_prof_arecv_done (int cpu)
void __fort_prof_asend (int cpu, long len, int reqn)
void __fort_prof_asend_done (int cpu)
void __fort_prof_await (int reqn)
void __fort_prof_await_done (int reqn)
Function Documentation
__fort_prof_arecv()
void __fort_prof_arecv (int cpu, long len, int reqn)
Definition at line 11 of file cprof2.c.
Referenced by __fort_entry_arecv().
__fort_prof_arecv_done()
void __fort_prof_arecv_done (int cpu)
Definition at line 18 of file cprof2.c.
Referenced by __fort_entry_arecv_done().
__fort_prof_asend()
void __fort_prof_asend (int cpu, long len, int reqn)
Definition at line 25 of file cprof2.c.
Referenced by __fort_entry_asend().
__fort_prof_asend_done()
void __fort_prof_asend_done (int cpu)
Definition at line 32 of file cprof2.c.
Referenced by __fort_entry_asend_done().
__fort_prof_await()
void __fort_prof_await (int reqn)
Definition at line 39 of file cprof2.c.
Referenced by __fort_entry_await().
__fort_prof_await_done()
void __fort_prof_await_done (int reqn)
Definition at line 46 of file cprof2.c.
Referenced by __fort_entry_await_done().