flang: cprof.c File Reference
cprof.c File Reference
Functions
int __fort_prof_init (void)
Profile initialization.
void __fort_prof_function_entry (int line, int lines, int cline, char *func, char *file, int funcl, int filel)
Function entry
void __fort_prof_line_entry (int line)
Line entry
void __fort_prof_recv (int cpu, long len)
Update start receive message stats.
void __fort_prof_recv_done (int cpu)
Update done receive message stats.
void __fort_prof_send (int cpu, long len)
Update start send message stats.
void __fort_prof_send_done (int cpu)
Update done send message stats.
void __fort_prof_copy (long len)
Update start bcopy message stats.
void __fort_prof_copy_done (void)
Update done bcopy message stats.
void __fort_prof_function_exit (void)
Function exit
void __fort_prof_term (void)
Profile termination.
Function Documentation
__fort_prof_copy()
void __fort_prof_copy (long len)
Update start bcopy message stats.
Parameters
len total length in bytes
Definition at line 62 of file cprof.c.
Referenced by __fort_entry_copy().
__fort_prof_copy_done()
void __fort_prof_copy_done (void)
Update done bcopy message stats.
Definition at line 68 of file cprof.c.
Referenced by __fort_entry_copy_done().
__fort_prof_function_entry()
void __fort_prof_function_entry (int line, int lines, int cline, char * func, char * file, int funcl, int filel)
Function entry
Definition at line 17 of file cprof.c.
Referenced by ENTFTN().
__fort_prof_function_exit()
void __fort_prof_function_exit (void)
Function exit
Definition at line 74 of file cprof.c.
Referenced by ENTFTN().
__fort_prof_init()
int __fort_prof_init (void)
Profile initialization.
Definition at line 10 of file cprof.c.
Referenced by __fort_entry_init().
__fort_prof_line_entry()
void __fort_prof_line_entry (int line)
Line entry
Definition at line 24 of file cprof.c.
Referenced by ENTFTN().
__fort_prof_recv()
void __fort_prof_recv (int cpu, long len)
Update start receive message stats.
Parameters
cpu sending cpu
len total length in bytes
Definition at line 33 of file cprof.c.
Referenced by __fort_entry_recv().
__fort_prof_recv_done()
void __fort_prof_recv_done (int cpu)
Update done receive message stats.
Definition at line 39 of file cprof.c.
Referenced by __fort_entry_recv_done().
__fort_prof_send()
void __fort_prof_send (int cpu, long len)
Update start send message stats.
Parameters
cpu receiving cpu
len total length in bytes
Definition at line 48 of file cprof.c.
Referenced by __fort_entry_send().
__fort_prof_send_done()
void __fort_prof_send_done (int cpu)
Update done send message stats.
Definition at line 54 of file cprof.c.
Referenced by __fort_entry_send_done().
__fort_prof_term()
void __fort_prof_term (void)
Profile termination.
Definition at line 80 of file cprof.c.
Referenced by __fort_entry_term().