flang: cpu-stopwatch.c File Reference
cpu-stopwatch.c File Reference
Millisecond CPU stopwatch for internal timing.
#include <sys/times.h>
#include <unistd.h>
#include "scutil.h"
Functions
unsigned long get_rutime (void)
Detailed Description
Millisecond CPU stopwatch for internal timing.
Return the elapsed user+system CPU time in milliseconds since the most recent call. Very much not thread-safe.
Definition in file cpu-stopwatch.c.
Function Documentation
get_rutime()
unsigned long get_rutime (void)
Definition at line 21 of file cpu-stopwatch.c.
References last, times(), tms::tms_stime, and tms::tms_utime.
Referenced by main(), and process_input().