flang: cpuid8664.h File Reference
cpuid8664.h File Reference
#include <stdio.h>
#include <stdint.h>
#include <cpuid.h>
Macros
#define xcr0_bit_XMM 0x00000002U
#define xcr0_bit_YMM 0x00000004U
#define xcr0_bit_ZMMK 0x00000020U
#define xcr0_bit_ZMMLO 0x00000040U
#define xcr0_bit_ZMMHI 0x00000080U
#define xcr0_mask_YMM (xcr0_bit_XMM | xcr0_bit_YMM)
#define xcr0_mask_ZMM (xcr0_bit_ZMMK | xcr0_bit_ZMMLO | xcr0_bit_ZMMHI)
#define CPUIDX8664(a) __cpuid_##a
Functions
static int CPUIDX8664() is_avx512 ()
static int CPUIDX8664() is_avx512vl ()
static int CPUIDX8664() is_avx512f ()
static int CPUIDX8664() is_avx2 ()
static int CPUIDX8664() is_avx ()
static int CPUIDX8664() is_intel ()
static int CPUIDX8664() is_amd ()
static int CPUIDX8664() is_fma4 ()
static int CPUIDX8664() is_sse4a ()
static int CPUIDX8664() is_sse41 ()
static int CPUIDX8664() is_f16c ()
Macro Definition Documentation
CPUIDX8664
#define CPUIDX8664 (a) __cpuid_##a
Definition at line 40 of file cpuid8664.h.
xcr0_bit_XMM
#define xcr0_bit_XMM 0x00000002U
Definition at line 25 of file cpuid8664.h.
xcr0_bit_YMM
#define xcr0_bit_YMM 0x00000004U
Definition at line 26 of file cpuid8664.h.
xcr0_bit_ZMMHI
#define xcr0_bit_ZMMHI 0x00000080U
Definition at line 29 of file cpuid8664.h.
xcr0_bit_ZMMK
#define xcr0_bit_ZMMK 0x00000020U
Definition at line 27 of file cpuid8664.h.
xcr0_bit_ZMMLO
#define xcr0_bit_ZMMLO 0x00000040U
Definition at line 28 of file cpuid8664.h.
xcr0_mask_YMM
#define xcr0_mask_YMM (xcr0_bit_XMM | xcr0_bit_YMM)
Definition at line 31 of file cpuid8664.h.
xcr0_mask_ZMM
#define xcr0_mask_ZMM (xcr0_bit_ZMMK | xcr0_bit_ZMMLO | xcr0_bit_ZMMHI)
Definition at line 32 of file cpuid8664.h.
Function Documentation
is_amd()
static int CPUIDX8664() is_amd (void) static
Definition at line 72 of file cpuid8664.h.
References eax, ecx, signature_AMD_ebx, signature_AMD_ecx, and signature_AMD_edx.
Referenced by __math_dispatch(), is_avx(), is_avx2(), is_f16c(), is_fma4(), and is_sse4a().
is_avx()
static int CPUIDX8664() is_avx (void) static
Definition at line 161 of file cpuid8664.h.
References CPUIDX8664, eax, ecx, is_amd(), is_intel(), and xcr0_mask_YMM.
Referenced by __math_dispatch(), is_avx2(), is_avx512(), and is_f16c().
is_avx2()
static int CPUIDX8664() is_avx2 (void) static
Definition at line 196 of file cpuid8664.h.
References CPUIDX8664, eax, ecx, is_amd(), is_avx(), and is_intel().
Referenced by __math_dispatch().
is_avx512()
static int CPUIDX8664() is_avx512 (void) static
Definition at line 223 of file cpuid8664.h.
References CPUIDX8664, eax, ecx, is_avx(), is_intel(), and xcr0_mask_ZMM.
Referenced by is_avx512f().
is_avx512f()
static int CPUIDX8664() is_avx512f (void) static
Definition at line 255 of file cpuid8664.h.
References CPUIDX8664, eax, ecx, and is_avx512().
Referenced by __math_dispatch(), and is_avx512vl().
is_avx512vl()
static int CPUIDX8664() is_avx512vl (void) static
Definition at line 275 of file cpuid8664.h.
References CPUIDX8664, eax, ecx, and is_avx512f().
Referenced by __math_dispatch().
is_f16c()
static int CPUIDX8664() is_f16c (void) static
Definition at line 295 of file cpuid8664.h.
References CPUIDX8664, eax, ecx, is_amd(), is_avx(), and is_intel().
is_fma4()
static int CPUIDX8664() is_fma4 (void) static
Definition at line 84 of file cpuid8664.h.
References CPUIDX8664, eax, ecx, and is_amd().
Referenced by __math_dispatch().
is_intel()
static int CPUIDX8664() is_intel (void) static
Definition at line 60 of file cpuid8664.h.
References eax, ecx, signature_INTEL_ebx, signature_INTEL_ecx, and signature_INTEL_edx.
Referenced by __math_dispatch(), is_avx(), is_avx2(), is_avx512(), is_f16c(), and is_sse41().
is_sse41()
static int CPUIDX8664() is_sse41 (void) static
Definition at line 141 of file cpuid8664.h.
References CPUIDX8664, eax, ecx, and is_intel().
Referenced by __math_dispatch().
is_sse4a()
static int CPUIDX8664() is_sse4a (void) static
Definition at line 112 of file cpuid8664.h.
References CPUIDX8664, eax, ecx, and is_amd().
Referenced by __math_dispatch().