flang: cshift.c File Reference
cshift.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "fort_vars.h"
Functions
void ENTFTN (CSHIFTS, cshifts)
void ENTFTN (CSHIFTSCA, cshiftsca)
void ENTFTN (CSHIFTSC, cshiftsc)
void I8() cshift_loop (void *rb, void *ab, __INT_T *sb, __INT_T shift_dim, F90_Desc *rs, F90_Desc *as, F90_Desc *ss, F90_Desc *rc, F90_Desc *ac, __INT_T soff, __INT_T loop_dim)
void ENTFTN (CSHIFT, cshift)
void ENTFTN (CSHIFTCA, cshiftca)
void ENTFTN (CSHIFTC, cshiftc)
Function Documentation
cshift_loop()
void I8() cshift_loop (void * rb, void * ab, __INT_T * sb, __INT_T shift_dim, F90_Desc * rs, F90_Desc * as, F90_Desc * ss, F90_Desc * rc, F90_Desc * ac, __INT_T soff, __INT_T loop_dim)
Definition at line 203 of file cshift.c.
References __fort_chain_em_up(), __fort_copy(), __fort_doit(), __fort_finish_section(), __fort_frechn(), __fort_set_section(), __fort_set_single(), __SCALAR, cshift_loop(), DECL_DIM_PTRS, DIM_UBOUND_G, DIST_CACHED_P, DIST_DIM_OLB_G, DIST_DIM_OLB_P, DIST_DIM_OUB_G, DIST_DIM_OUB_P, DIST_PBASE_G, DIST_PBASE_P, DIST_REPLICATED_G, DIST_REPLICATED_P, DIST_SCOFF_G, DIST_SCOFF_P, DPTR_UBOUND_G, extent(), F90_DIM_LBOUND_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_FLAGS_P, F90_LBASE_G, F90_LBASE_P, F90_LEN_G, F90_RANK_G, i, I8, MAXDIMS, NULL, rb, rc, sb, SET_DIM_PTRS, shift, and ss.
Referenced by cshift_loop(), and ENTFTN().
ENTFTN() [1/6]
void ENTFTN (CSHIFT , cshift)
Definition at line 410 of file cshift.c.
References __DIST_INIT_SECTION, __fort_show_section(), __fort_test, cshift_loop(), db(), DEBUG_CSHF, DECL_HDR_VARS, dim, F90_LBASE_G, F90_RANK_G, GET_DIST_LCPU, I8, rb, rc, sb, and ss.
ENTFTN() [2/6]
void ENTFTN (CSHIFTC , cshiftc)
Definition at line 462 of file cshift.c.
References __CLEN_T, CADR, CLEN, db(), ds(), ENTFTN(), rb, sb, and ss.
ENTFTN() [3/6]
void ENTFTN (CSHIFTCA , cshiftca)
Definition at line 448 of file cshift.c.
References CADR, db(), ds(), ENTFTN(), rb, sb, and ss.
ENTFTN() [4/6]
void ENTFTN (CSHIFTS , cshifts)
Definition at line 17 of file cshift.c.
References __DIST_INIT_SECTION, __fort_chain_em_up(), __fort_copy(), __fort_doit(), __fort_finish_section(), __fort_frechn(), __fort_set_section(), __fort_show_section(), __fort_test, db(), DEBUG_CSHF, DECL_DIM_PTRS, DECL_HDR_VARS, dim, DIST_CACHED_P, DIST_DIM_OLB_G, DIST_DIM_OLB_P, DIST_DIM_OUB_G, DIST_DIM_OUB_P, DIST_PBASE_G, DIST_PBASE_P, DIST_REPLICATED_G, DIST_REPLICATED_P, DIST_SCOFF_G, DIST_SCOFF_P, DPTR_UBOUND_G, extent(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_FLAGS_G, F90_FLAGS_P, F90_LBASE_G, F90_LBASE_P, F90_LEN_G, F90_RANK_G, GET_DIST_LCPU, i, I8, MAXDIMS, NULL, rb, rc, sb, SET_DIM_PTRS, and shift.
Referenced by ENTFTN().
ENTFTN() [5/6]
void ENTFTN (CSHIFTSC , cshiftsc)
Definition at line 184 of file cshift.c.
References __CLEN_T, CADR, CLEN, db(), ds(), ENTFTN(), rb, sb, and ss.
ENTFTN() [6/6]
void ENTFTN (CSHIFTSCA , cshiftsca)
Definition at line 169 of file cshift.c.
References CADR, db(), ds(), ENTFTN(), rb, sb, and ss.