flang: ctime3f.c File Reference
ctime3f.c File Reference
#include "ent3f.h"
#include "utils3f.h"
Functions
char * ctime (long *)
static void ctime_c (char *tm, int tml, long stime)
void ENT3F (CTIME, ctime)
void ENT3F (CTIME8, ctime8)
Function Documentation
ctime()
char * ctime (long *)
Referenced by ctime_c().
ctime_c()
static void ctime_c (char * tm, int tml, long stime) static
Definition at line 20 of file ctime3f.c.
References __fcp_cstr(), ctime(), i, and p.
Referenced by ENT3F().
ENT3F() [1/2]
void ENT3F (CTIME , ctime)
Definition at line 36 of file ctime3f.c.
References CADR, CLEN, and ctime_c().
ENT3F() [2/2]
void ENT3F (CTIME8 , ctime8)
Definition at line 41 of file ctime3f.c.
References CADR, CLEN, and ctime_c().