flang: curdir.c File Reference
curdir.c File Reference
#include <sys/types.h>
#include <sys/param.h>
#include <sys/utsname.h>
#include <stdlib.h>
#include "stdioInterf.h"
#include "fioMacros.h"
Macros
#define MAXPATHLEN 1024
Functions
WIN_MSVCRT_IMP char *WIN_CDECL getenv (const char *)
void __fort_fixmnt (char *new, char *old)
void __fort_getdir (char *curdir)
void __fort_gethostname (char *host)
Macro Definition Documentation
MAXPATHLEN
#define MAXPATHLEN 1024
Definition at line 18 of file curdir.c.
Function Documentation
__fort_fixmnt()
void __fort_fixmnt (char * new, char * old)
Definition at line 29 of file curdir.c.
References __fort_getopt(), MAXPATHLEN, n, NULL, q, s, and strlen().
Referenced by __fort_getdir().
__fort_getdir()
void __fort_getdir (char * curdir)
Definition at line 69 of file curdir.c.
References __fort_abort(), __fort_fixmnt(), getenv(), MAXPATHLEN, NULL, p, and path.
__fort_gethostname()
void __fort_gethostname (char * host)
Definition at line 87 of file curdir.c.
References __fort_abortp(), __fort_getopt(), host, NULL, p, s, and uname.
getenv()
WIN_MSVCRT_IMP char *WIN_CDECL getenv (const char *)
Referenced by __abort(), __abort_init(), __alloc04(), __fort_alloc(), __fort_getdir(), __fortio_errmsg(), __fortio_scratch_name(), __math_dispatch(), accpp(), ENT3F(), ENTF90(), gentmp(), and mth_i_override().