flang: cvt.c File Reference
cvt.c File Reference
#include <stdlib.h>
#include <string.h>
#include <math.h>
Classes
union IEEE_DBL
Macros
#define IEEE 1
#define NDIG 512
Functions
static int __isspecial (double f, char *bp)
static char * cvt (double arg, int ndigits, int *decpt, int *sign, int eflag)
char * ecvt (double arg, int ndigits, int *decpt, int *sign)
char * fcvt (double arg, int ndigits, int *decpt, int *sign)
Macro Definition Documentation
IEEE
#define IEEE 1
Definition at line 12 of file cvt.c.
NDIG
#define NDIG 512
Definition at line 59 of file cvt.c.
Function Documentation
__isspecial()
static int __isspecial (double f, char * bp) static
Definition at line 44 of file cvt.c.
References IEEE_DBL::e, f, IEEE_DBL::f, IEEE_DBL::mh, IEEE_DBL::ml, and IEEE_DBL::s.
Referenced by cvt().
cvt()
static char * cvt (double arg, int ndigits, int * decpt, int * sign, int eflag) static
Definition at line 65 of file cvt.c.
References __isspecial(), arg, buf, modf(), NDIG, ndigits, p, and sign.
Referenced by ecvt(), and fcvt().
ecvt()
char * ecvt (double arg, int ndigits, int * decpt, int * sign)
Definition at line 144 of file cvt.c.
References arg, cvt(), ndigits, and sign.
Referenced by __ecvt().
fcvt()
char * fcvt (double arg, int ndigits, int * decpt, int * sign)
Definition at line 150 of file cvt.c.
References arg, cvt(), ndigits, and sign.