flang: datadep.c File Reference
datadep.c File Reference
Data dependence framework.
#include "gbldefs.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "ast.h"
#include "nme.h"
#include "optimize.h"
#include "hlvect.h"
#include "induc.h"
#include "soc.h"
#include "fdirect.h"
#include "extern.h"
#include "ilidir.h"
Classes
struct DV
struct bound
struct arith_term
Macros
#define TRACE0(s)
#define TRACE1(s, a1)
#define TRACE2(s, a1, a2)
#define TRACE3(s, a1, a2, a3)
#define TRACE4(s, a1, a2, a3, a4)
#define TRACE5(s, a1, a2, a3, a4, a5)
#define STRACE0(s)
#define STRACE1(s, a1)
#define STRACE2(s, a1, a2)
#define STRACE3(s, a1, a2, a3)
#define STRACE4(s, a1, a2, a3, a4)
#define STRACE5(s, a1, a2, a3, a4, a5)
#define DTRACE0(s)
#define DTRACE1(s, a1)
#define DTRACE2(s, a1, a2)
#define DTRACE3(s, a1, a2, a3)
#define DTRACE4(s, a1, a2, a3, a4)
#define DTRACE5(s, a1, a2, a3, a4, a5)
#define BTRACE0(s)
#define BTRACE1(s, a1)
#define BTRACE2(s, a1, a2)
#define BTRACE3(s, a1, a2, a3)
#define BTRACE4(s, a1, a2, a3, a4)
#define BTRACE5(s, a1, a2, a3, a4, a5)
#define ad_icon(i) (mk_isz_cval(i, astb.bnd.dtype))
#define prilitree(a) (printast(a))
#define ILT_NEXT(s) (STD_NEXT(s))
#define IS_CNST(a) (A_TYPEG(a) == A_CNST)
#define CNSTG(a) (get_isz_cval(A_SPTRG(a)))
#define ZZZCNSTG(a) (DBGcnst(A_SPTRG(a)))
#define RESG(a) (A_DTYPEG(a))
#define IS_IRES(a) (DT_ISINT(RESG(a)))
#define IS_ARES(a) (RESG(a) == DT_ADDR)
#define ILI_VISIT(a) (A_VISITG(a))
#define ILI_REPL(a) (A_REPLG(a))
#define IL_INEG 1
#define IL_IADD 2
#define IL_ISUB 3
#define IL_IMUL 4
#define IL_IDIV 5
#define IL_MOD 6
#define IL_AADD 7
#define IL_ASUB 8
#define MAX_DD (2 * MAX_LOOPS)
#define MAX_N MAX_DD
#define MAXNMESIZ 30
#define MAX_S MAXNMESIZ
#define UD xUD
#define BOUND_LEN (2 * (MAX_N + 1))
#define BOUND_ADD(t, l, i)
Typedefs
typedef struct DV DV
typedef struct bound BOUND
typedef BV * BVP
typedef struct arith_term ARITH_TERM
typedef struct arith_term * ARITH_LIST
Functions
ISZ_T DBGcnst (int s)
static void build_loop_dd (int loop)
static void dd_compute (void)
void dd_edge (int src, int sink, DIRVEC vec)
static void dd_succ (int loop)
static void resolve_vv (void)
static void resolve_pv (void)
static void resolve_pp (void)
static void resolve_uv (void)
static void do_subscript (int nsubs)
static void add_dep (DIRVEC vec)
static void hierarchy (DIRVEC dir, int lev, DIRVEC veco)
static void unpack_loops (void)
static void chkref (int i, int j)
LOGICAL dd_array_conflict (int astliTriples, int astArrSrc, int astArrSink, int bSinkAfterSrc)
Return TRUE if there is a forward dependence from astArrSrc (the source) to astArrSink (the sink) within an iteration space described by a triplet list beginning at astliTriples.
static int symbolic_mul (int a, int b)
static LOGICAL symbolic_divide (int num, int den, int *quot)
static void cln_visit (void)
static int ili_symbolic (int ili)
int dd_symbolic (int il)
Perform symbolic algebraic simplification of term il.
static void dump_one_bound (BOUND *p, int k, LOGICAL btype)
static void dump_two_bound (BOUND *p, BOUND *q, int k, LOGICAL btype)
static int ad1ili (int opc, int ast1)
static int ad2ili (int opc, int ast1, int ast2)
static int ILI_OPC (int astx)
static int ILI_OPND (int astx, int opnd)
void build_dd (int loop)
Build the data dependency graph.
static void build_nat_loop (int loop)
static LOGICAL mr_precedes (int mr1, int mr2)
static void edge_func (DIRVEC vec)
static void prmat (int col, int row)
static INT gcd (INT a, INT b)
static int ceilg (int t, int g)
static int floorg (int t, int g)
static LOGICAL compare_one_bound (BOUND *low, BOUND *up, int var)
static int bound_add (int *ibound, LOGICAL upflag, int var)
static LOGICAL check_bounds (void)
static LOGICAL bnd_le (int k, LOGICAL eqflag)
static LOGICAL bnd_ge (int k, LOGICAL eqflag)
static LOGICAL check_new_bound (DIRVEC dir, int lev)
DIRVEC dirv_inverse (DIRVEC vec)
Invert a direction vector.
DIRVEC dirv_fulldep (int level)
Generate full dependence at a given level.
DIRVEC dirv_exo (int level, int flag)
Generate legal execution order direction vectors.
static DIRVEC dirv_permute (DIRVEC dir, int *m, int nest)
static void dovec (DIRVEC dir, DIRVEC dir1, int pos, int ig, void(*f)(DIRVEC), int alleq, int seenlt)
void dirv_gen (DIRVEC dir, int *map, int nest, int ig, void(*f)(DIRVEC))
static LOGICAL is_linear (int)
static LOGICAL mkSub (int astliTriples, int sub, int astmpyr, int ast)
static void fwd_func (DIRVEC dv)
static int fill_subscripts (int astRef, int mr, int subStart, int ntriples, int astliTriples)
static ARITH_LIST apnd (ARITH_LIST l1, ARITH_LIST l2)
static void refactor (ARITH_LIST atp)
static void refactor_list (ARITH_LIST lst)
static int sum (ARITH_LIST lst)
static ARITH_LIST distrib (int ili, int mpyr)
static LOGICAL contains_common_factor (ARITH_LIST lst, int trm)
static long combine_terms (ARITH_LIST lst, int trm)
static ARITH_LIST remove_terms (ARITH_LIST lst, int trm)
static ARITH_LIST elim (ARITH_LIST lst)
int dirv_chkzero (DIRVEC dir, int n)
char * dirv_print (DIRVEC dir)
void dump_dd (DDEDGE *p)
void dump_termlist (ARITH_LIST lst)
Variables
struct {
int mr1
int mr2
int subs1
int subs2
int basenm1
int basenm2
int outer_loop
DIRVEC vec
DV * dvlist
int unknown
int n1
int n2
int n
int common
short lps [MAX_DD]
VPRAGMAS pragmas
} ddinfo
static BVP * fgsucc
static BV * fgbase
static int nvars
static int neqns
static int nfree
static int UD [MAX_N][MAX_S+MAX_N]
static int T [MAX_N]
static int C [MAX_S]
static int Dist [MAX_LOOPS]
static int TU [MAX_S][MAX_N]
static BOUND * Bound [MAX_N+1][2]
static BOUND * SaveBound [MAX_N+1][2]
struct {
int nloops
LOGICAL bFwd
} fwd
static LOGICAL rdc
static int visit_chain = 0
static LOGICAL use_visit = TRUE
Detailed Description
Data dependence framework.
Definition in file datadep.c.
Macro Definition Documentation
ad_icon
#define ad_icon (i) (mk_isz_cval(i, astb.bnd.dtype))
Definition at line 144 of file datadep.c.
BOUND_ADD
#define BOUND_ADD (t, l, i)
Value:
  if (bound_add(t, l, i))  \
    goto no_dep;           \
  else
BOUND_LEN
#define BOUND_LEN (2 * (MAX_N + 1))
Definition at line 929 of file datadep.c.
BTRACE0
#define BTRACE0 (s)
Value:
  if (DBGBIT(36, 64)) \
  fprintf(gbl.dbgfil, s)
Definition at line 87 of file datadep.c.
BTRACE1
#define BTRACE1 (s, a1)
Value:
  if (DBGBIT(36, 64))  \
  fprintf(gbl.dbgfil, s, a1)
Definition at line 90 of file datadep.c.
BTRACE2
#define BTRACE2 (s, a1, a2)
Value:
  if (DBGBIT(36, 64))      \
  fprintf(gbl.dbgfil, s, a1, a2)
Definition at line 93 of file datadep.c.
BTRACE3
#define BTRACE3 (s, a1, a2, a3)
Value:
  if (DBGBIT(36, 64))          \
  fprintf(gbl.dbgfil, s, a1, a2, a3)
Definition at line 96 of file datadep.c.
BTRACE4
#define BTRACE4 (s, a1, a2, a3, a4)
Value:
  if (DBGBIT(36, 64))              \
  fprintf(gbl.dbgfil, s, a1, a2, a3, a4)
Definition at line 99 of file datadep.c.
BTRACE5
#define BTRACE5 (s, a1, a2, a3, a4, a5)
Value:
  if (DBGBIT(36, 64))                  \
  fprintf(gbl.dbgfil, s, a1, a2, a3, a4, a5)
Definition at line 102 of file datadep.c.
CNSTG
#define CNSTG (a) (get_isz_cval(A_SPTRG(a)))
Definition at line 148 of file datadep.c.
DTRACE0
#define DTRACE0 (s)
Value:
  if (DBGBIT(36, 16)) \
  fprintf(gbl.dbgfil, s)
Definition at line 68 of file datadep.c.
DTRACE1
#define DTRACE1 (s, a1)
Value:
  if (DBGBIT(36, 16))  \
  fprintf(gbl.dbgfil, s, a1)
Definition at line 71 of file datadep.c.
DTRACE2
#define DTRACE2 (s, a1, a2)
Value:
  if (DBGBIT(36, 16))      \
  fprintf(gbl.dbgfil, s, a1, a2)
Definition at line 74 of file datadep.c.
DTRACE3
#define DTRACE3 (s, a1, a2, a3)
Value:
  if (DBGBIT(36, 16))          \
  fprintf(gbl.dbgfil, s, a1, a2, a3)
Definition at line 77 of file datadep.c.
DTRACE4
#define DTRACE4 (s, a1, a2, a3, a4)
Value:
  if (DBGBIT(36, 16))              \
  fprintf(gbl.dbgfil, s, a1, a2, a3, a4)
Definition at line 80 of file datadep.c.
DTRACE5
#define DTRACE5 (s, a1, a2, a3, a4, a5)
Value:
  if (DBGBIT(36, 16))                  \
  fprintf(gbl.dbgfil, s, a1, a2, a3, a4, a5)
Definition at line 83 of file datadep.c.
IL_AADD
#define IL_AADD 7
Definition at line 162 of file datadep.c.
IL_ASUB
#define IL_ASUB 8
Definition at line 163 of file datadep.c.
IL_IADD
#define IL_IADD 2
Definition at line 157 of file datadep.c.
IL_IDIV
#define IL_IDIV 5
Definition at line 160 of file datadep.c.
IL_IMUL
#define IL_IMUL 4
Definition at line 159 of file datadep.c.
IL_INEG
#define IL_INEG 1
Definition at line 156 of file datadep.c.
IL_ISUB
#define IL_ISUB 3
Definition at line 158 of file datadep.c.
IL_MOD
#define IL_MOD 6
Definition at line 161 of file datadep.c.
ILI_REPL
#define ILI_REPL (a) (A_REPLG(a))
Definition at line 154 of file datadep.c.
ILI_VISIT
#define ILI_VISIT (a) (A_VISITG(a))
Definition at line 153 of file datadep.c.
ILT_NEXT
#define ILT_NEXT (s) (STD_NEXT(s))
Definition at line 146 of file datadep.c.
IS_ARES
#define IS_ARES (a) (RESG(a) == DT_ADDR)
Definition at line 152 of file datadep.c.
IS_CNST
#define IS_CNST (a) (A_TYPEG(a) == A_CNST)
Definition at line 147 of file datadep.c.
IS_IRES
#define IS_IRES (a) (DT_ISINT(RESG(a)))
Definition at line 151 of file datadep.c.
MAX_DD
#define MAX_DD (2 * MAX_LOOPS)
Definition at line 170 of file datadep.c.
MAX_N
#define MAX_N MAX_DD
Definition at line 171 of file datadep.c.
MAX_S
#define MAX_S MAXNMESIZ
Definition at line 173 of file datadep.c.
MAXNMESIZ
#define MAXNMESIZ 30
Definition at line 172 of file datadep.c.
prilitree
#define prilitree (a) (printast(a))
Definition at line 145 of file datadep.c.
RESG
#define RESG (a) (A_DTYPEG(a))
Definition at line 150 of file datadep.c.
STRACE0
#define STRACE0 (s)
Value:
  if (DBGBIT(36, 4)) \
  fprintf(gbl.dbgfil, s)
Definition at line 49 of file datadep.c.
STRACE1
#define STRACE1 (s, a1)
Value:
  if (DBGBIT(36, 4))   \
  fprintf(gbl.dbgfil, s, a1)
Definition at line 52 of file datadep.c.
STRACE2
#define STRACE2 (s, a1, a2)
Value:
  if (DBGBIT(36, 4))       \
  fprintf(gbl.dbgfil, s, a1, a2)
Definition at line 55 of file datadep.c.
STRACE3
#define STRACE3 (s, a1, a2, a3)
Value:
  if (DBGBIT(36, 4))           \
  fprintf(gbl.dbgfil, s, a1, a2, a3)
Definition at line 58 of file datadep.c.
STRACE4
#define STRACE4 (s, a1, a2, a3, a4)
Value:
  if (DBGBIT(36, 4))               \
  fprintf(gbl.dbgfil, s, a1, a2, a3, a4)
Definition at line 61 of file datadep.c.
STRACE5
#define STRACE5 (s, a1, a2, a3, a4, a5)
Value:
  if (DBGBIT(36, 4))                   \
  fprintf(gbl.dbgfil, s, a1, a2, a3, a4, a5)
Definition at line 64 of file datadep.c.
TRACE0
#define TRACE0 (s)
Value:
  if (DBGBIT(36, 2)) \
  fprintf(gbl.dbgfil, s)
Definition at line 30 of file datadep.c.
TRACE1
#define TRACE1 (s, a1)
Value:
  if (DBGBIT(36, 2))  \
  fprintf(gbl.dbgfil, s, a1)
Definition at line 33 of file datadep.c.
TRACE2
#define TRACE2 (s, a1, a2)
Value:
  if (DBGBIT(36, 2))      \
  fprintf(gbl.dbgfil, s, a1, a2)
Definition at line 36 of file datadep.c.
TRACE3
#define TRACE3 (s, a1, a2, a3)
Value:
  if (DBGBIT(36, 2))          \
  fprintf(gbl.dbgfil, s, a1, a2, a3)
Definition at line 39 of file datadep.c.
TRACE4
#define TRACE4 (s, a1, a2, a3, a4)
Value:
  if (DBGBIT(36, 2))              \
  fprintf(gbl.dbgfil, s, a1, a2, a3, a4)
Definition at line 42 of file datadep.c.
TRACE5
#define TRACE5 (s, a1, a2, a3, a4, a5)
Value:
  if (DBGBIT(36, 2))                  \
  fprintf(gbl.dbgfil, s, a1, a2, a3, a4, a5)
Definition at line 45 of file datadep.c.
UD
#define UD xUD
Definition at line 922 of file datadep.c.
ZZZCNSTG
#define ZZZCNSTG (a) (DBGcnst(A_SPTRG(a)))
Definition at line 149 of file datadep.c.
Typedef Documentation
ARITH_LIST
typedef struct arith_term * ARITH_LIST
ARITH_TERM
typedef struct arith_term ARITH_TERM
BOUND
typedef struct bound BOUND
BVP
typedef BV* BVP
Definition at line 262 of file datadep.c.
DV
typedef struct DV DV
Function Documentation
ad1ili()
static int ad1ili (int opc, int ast1) static
Definition at line 3032 of file datadep.c.
References astb, ASTB::bnd, ASTB::dtype, IL_INEG, interr(), mk_convert(), mk_unop(), and OP_SUB.
Referenced by _exp_mp_atomic_update(), _exp_smove(), _make_mp_get_threadprivate(), add_arglnk_closure(), add_gargl_closure(), add_ptr_subscript(), add_reg_arg_ili(), addCopyinInplace(), assign1(), begin_entry(), chk_block(), compare_one_bound(), compute_sdsc_subscr(), cr_block(), create_array_ref(), create_array_subscr(), create_atomic_capture_seq(), create_atomic_read_seq(), create_atomic_seq(), create_atomic_write_seq(), create_sdsc_subscr(), distrib(), do_subscript(), exp_ac(), exp_alloca(), exp_bran(), exp_call(), exp_cgoto(), exp_end(), exp_estmt(), exp_fstring(), exp_get_sdsc_len(), exp_header(), exp_load(), exp_misc(), exp_qjsr(), exp_restore_mxcsr(), exp_scope_label(), exp_smp(), exp_store(), exp_strx(), exp_szero(), exp_type_bound_proc_call(), exp_zqjsr(), finish_array(), fused_multiply_add_canonical_form(), gen_abs_expr(), gen_base_addr_operand(), gen_binary_expr(), gen_llvm_expr(), gen_null_arg(), genload(), genNullArg(), genSizeAcon(), genswitch(), getstraddr(), getstrlen64(), init_ainfo(), jsrAddArg(), ll_ad_outlined_func2(), ll_make_atomic_compare_xchg(), ll_make_atomic_load(), ll_make_atomic_store(), ll_make_kmpc_fork_call(), ll_make_kmpc_fork_teams(), ll_make_kmpc_threadprivate_cached(), ll_make_outlined_garg(), llvmAddConcurEntryBlk(), llvmAddConcurExitBlk(), makeCall(), makeCopyprivArray_tls(), pass_char_arg(), redundantLdLdElim(), rm_smove(), srcfunc(), symbolic_divide(), symbolic_mul(), visit_ilis(), widenApplyCse(), widenApplyStore(), widenProcessDirectLoad(), widenProcessIndirectLoad(), and widenPushdown().
ad2ili()
static int ad2ili (int opc, int ast1, int ast2) static
Definition at line 3046 of file datadep.c.
References astb, ASTB::bnd, ASTB::dtype, IL_AADD, IL_ASUB, IL_IADD, IL_IDIV, IL_IMUL, IL_ISUB, interr(), mk_binop(), mk_convert(), OP_ADD, OP_DIV, OP_MUL, OP_SUB, and optype().
Referenced by add_ptr_subscript(), addCopyinInplace(), allochartmp(), arg_dp(), arg_ir(), arg_kr(), arg_sp(), assign1(), begin_entry(), bnd_ge(), bnd_le(), bound_add(), charaddr(), cloneUplevel(), compare_one_bound(), compute_sdsc_subscr(), cr_block(), create_array_ref(), create_array_subscr(), create_atomic_capture_seq(), create_atomic_read_seq(), create_atomic_seq(), create_atomic_write_seq(), create_ref(), create_sdsc_subscr(), distrib(), do_subscript(), exp_ac(), exp_alloca(), exp_bran(), exp_call(), exp_end(), exp_fstring(), exp_header(), exp_load(), exp_misc(), exp_pure(), exp_qjsr(), exp_restore_mxcsr(), exp_smp(), exp_store(), exp_strcpy(), exp_strx(), exp_szero(), exp_type_bound_proc_call(), exp_zqjsr(), finish_array(), gen_base_addr_operand(), gen_bindC_retval(), gen_funcret(), get_chain_pointer_closure(), get_sdsc_element(), inlarr(), jsr2qjsr(), jsrAddArg(), kanji_bytes(), kanji_divide(), ll_ad_outlined_func2(), ll_load_outlined_args(), ll_make_atomic_compare_xchg(), ll_make_atomic_load(), ll_make_atomic_store(), ll_make_kmpc_task(), ll_make_kmpc_task_begin_if0(), ll_make_kmpc_task_complete_if0(), ll_make_outlined_task_call(), llGetThreadprivateAddr(), llLoadGtid(), llvmAddConcurEntryBlk(), loadUplevelArgsForRegion(), makeCall(), makeCopyprivArray_tls(), mk_charlen_address(), ref_threadprivate(), ref_threadprivate_var(), refactor(), setTaskloopVars(), storechartmp(), sum(), symbolic_mul(), toUplevelAddr(), and widenPushdown().
add_dep()
static void add_dep (DIRVEC vec) static
Definition at line 626 of file datadep.c.
References ddinfo, getitem(), HLV_AREA1, p, and vec.
Referenced by dd_compute(), do_subscript(), hierarchy(), resolve_pp(), resolve_pv(), resolve_uv(), and resolve_vv().
apnd()
static ARITH_LIST apnd (ARITH_LIST l1, ARITH_LIST l2) static
Definition at line 2671 of file datadep.c.
References arith_term::next, and NULL.
Referenced by distrib().
bnd_ge()
static LOGICAL bnd_ge (int k, LOGICAL eqflag) static
Definition at line 1223 of file datadep.c.
References ad2ili(), ad_icon, compare_one_bound(), for(), i, if(), IL_IADD, ili_symbolic(), k, nfree, and TU.
Referenced by check_new_bound().
bnd_le()
static LOGICAL bnd_le (int k, LOGICAL eqflag) static
Definition at line 1206 of file datadep.c.
References ad2ili(), ad_icon, compare_one_bound(), i, if(), IL_IADD, ili_symbolic(), k, nfree, and TU.
Referenced by check_new_bound().
bound_add()
static int bound_add (int * ibound, LOGICAL upflag, int var) static
Definition at line 1153 of file datadep.c.
References ad2ili(), ad_icon, BTRACE4, compare_one_bound(), if(), IL_IADD, IL_IMUL, ili_symbolic(), j, k, nfree, nvars, and TU.
build_dd()
void build_dd (int loop)
Build the data dependency graph.
Definition at line 268 of file datadep.c.
References build_loop_dd(), cln_visit(), DBGBIT, ddinfo, dump_one_vloop(), dump_vloops(), gbl, i, VL_CHILD, and VL_SIBLING.
build_loop_dd()
static void build_loop_dd (int loop) static
Definition at line 397 of file datadep.c.
References build_loop_dd(), chkref(), DBGBIT, dd_succ(), ddinfo, dump_memrefs(), end, fgbase, fgsucc, FREE, gbl, i, j, TRACE2, VL_CHILD, VL_MRCNT, VL_MRECNT, VL_MRSTART, VL_PRAGMAS, and VL_SIBLING.
Referenced by build_dd(), and build_loop_dd().
build_nat_loop()
static void build_nat_loop (int loop) static
Definition at line 290 of file datadep.c.
References build_nat_loop(), FG_NATNXT, FG_NEXT, HLVECT::fgn, hlv, i, LP_FG, HLVECT::natural_loop, VL_CHILD, and VL_SIBLING.
Referenced by build_nat_loop(), and dd_succ().
ceilg()
static int ceilg (int t, int g) static
Definition at line 967 of file datadep.c.
References a, ddinfo, q, and t.
Referenced by compare_one_bound().
check_bounds()
static LOGICAL check_bounds (void) static
Definition at line 1188 of file datadep.c.
References Bound, compare_one_bound(), FALSE, k, nfree, p, q, and TRUE.
Referenced by check_new_bound(), and hierarchy().
check_new_bound()
static LOGICAL check_new_bound (DIRVEC dir, int lev) static
Definition at line 1241 of file datadep.c.
References BCOPY, bnd_ge(), bnd_le(), Bound, BOUND_LEN, check_bounds(), d, DIRV_ENTRYG, DIRV_EQ, DIRV_GT, DIRV_LT, DIRV_STAR, FALSE, k, SaveBound, and TRUE.
Referenced by hierarchy().
chkref()
static void chkref (int i, int j) static
compute execution orders from j to i
compute execution orders from i to j
Definition at line 480 of file datadep.c.
References bv_mem(), dd_compute(), dd_edge(), ddinfo, dirv_chkzero(), dirv_exo(), dirv_inverse(), FALSE, fgsucc, freearea(), HLV_AREA1, i, j, MR_FG, mr_precedes(), MR_TYPE, NULL, p, STRACE2, TRUE, and vec.
Referenced by build_loop_dd().
cln_visit()
static void cln_visit (void) static
Definition at line 2657 of file datadep.c.
References ILI_REPL, ILI_VISIT, and visit_chain.
Referenced by build_dd(), and dd_array_conflict().
combine_terms()
static long combine_terms (ARITH_LIST lst, int trm) static
Definition at line 2879 of file datadep.c.
References arith_term::confact, arith_term::next, sum(), and arith_term::varfact.
Referenced by elim().
compare_one_bound()
static LOGICAL compare_one_bound (BOUND * low, BOUND * up, int var) static
Definition at line 1013 of file datadep.c.
References ad1ili(), ad2ili(), ad_icon, b, Bound, ceilg(), CNSTG, DBGBIT, ddinfo, DEBUG, DTRACE0, DTRACE1, dump_one_bound(), dump_two_bound(), FALSE, floorg(), gbl, gcd(), getitem(), HLV_AREA1, i, if(), IL_IMUL, IL_INEG, IL_ISUB, ili_symbolic(), IS_CNST, j, MAX_N, p, prilitree, t, t1, tmp, and TRUE.
Referenced by bnd_ge(), bnd_le(), bound_add(), and check_bounds().
contains_common_factor()
static LOGICAL contains_common_factor (ARITH_LIST lst, int trm) static
Definition at line 2860 of file datadep.c.
References assert, FALSE, arith_term::next, TRUE, and arith_term::varfact.
Referenced by elim().
DBGcnst()
ISZ_T DBGcnst (int s)
Definition at line 136 of file datadep.c.
References get_isz_cval(), ISZ_T, and s.
dd_array_conflict()
LOGICAL dd_array_conflict (int astliTriples, int astArrSrc, int astArrSink, int bSinkAfterSrc)
Return TRUE if there is a forward dependence from astArrSrc (the source) to astArrSink (the sink) within an iteration space described by a triplet list beginning at astliTriples.
bSinkAfterSrc should be:
1 if the sink is lexically after the source.
0 if the sink is lexically before the source.
-1 if this is a FORALL test
Definition at line 2342 of file datadep.c.
References ASD_NDIM, assert, astb, ASTLI_NEXT, ASTLI_TRIPLE, ASTB::bnd, BZERO, cln_visit(), CNSTG, dd_edge(), DD_NEXT, ddinfo, dirv_chkzero(), DIRV_ENTRYG, dirv_exo(), dirv_gen(), DIRV_GT, DIRV_LT, DDEDGE::dirvec, do_subscript(), ASTB::dtype, FALSE, fill_subscripts(), FREE, freearea(), fwd, fwd_func(), hlv, HLV_AREA1, i, interr(), IS_CNST, ISZ_T, lp, HLVECT::lpavail, HLVECT::lpbase, HLVECT::lpsize, MAX_LOOPS, mk_binop(), MR_ILI, MR_SUBCNT, MR_SUBST, MR_SUCC, MR_TYPE, HLVECT::mravail, HLVECT::mrbase, HLVECT::mrsize, NEED, NEW, DV::next, nsubs, NULL, OP_SUB, SB_BASE, SB_BASES, SB_STRIDE, sub, HLVECT::subavail, HLVECT::subbase, HLVECT::subsize, t, TRUE, val, DV::vec, VL_LBND, VL_UBND, VP_DEPCHK, and ASTB::zero.
Referenced by Conflict_(), and name_dependent_check().
dd_compute()
static void dd_compute (void) static
Definition at line 637 of file datadep.c.
References add_dep(), assert, basesym_of(), ddinfo, dirv_fulldep(), expr_dependent(), FALSE, FG_TO_BIH, i, MR_FG, MR_ILI, MR_ILT, MR_INIT, MR_IV, MR_IVUSE, MR_LOOP, MR_NEXT, MR_NME, NME_NM, NME_TYPE, NT_ARR, NT_IND, NT_MEM, NT_UNK, NT_VAR, resolve_pp(), resolve_pv(), resolve_uv(), resolve_vv(), SOC_NEXT, SOC_SPTR, STRACE4, TRUE, VL_IVLIST, VL_PREBIH, VP_DEPCHK, and VP_EQVCHK.
Referenced by chkref().
dd_edge()
void dd_edge (int src, int sink, DIRVEC vec)
Definition at line 557 of file datadep.c.
References DD_DIRVEC, DD_NEXT, DD_SINK, DD_TYPE, ddinfo, def, DEF_FG, DEF_NEXT, DIRV_BIGPOS, DIRV_FANTI, DIRV_FFLOW, DIRV_FOUT, dirv_gen(), dirv_print(), edge_func(), FG_LOOP, getitem(), HLV_AREA, inloop(), interr(), lp, LP_PARENT, MR_ILT, MR_INVAL, MR_NME, MR_SUCC, MR_TYPE, NME_DEF, p, sink, skip, src, TRACE0, TRACE3, type, and vec.
Referenced by chkref(), and dd_array_conflict().
dd_succ()
static void dd_succ (int loop) static
Definition at line 305 of file datadep.c.
References assert, build_nat_loop(), BV_BITS, bv_copy(), bv_notequal(), bv_print(), bv_set(), bv_union(), BZERO, DBGBIT, FG_NATNXT, FG_SUCC, fgbase, HLVECT::fgn, fgsucc, gbl, hlv, i, LP_TAIL, HLVECT::natural_loop, NEW, OPT::num_nodes, opt, p, PSI_NEXT, PSI_NODE, and TRUE.
Referenced by build_loop_dd().
dd_symbolic()
int dd_symbolic (int il)
Perform symbolic algebraic simplification of term il.
NOTE: Call freearea(HLV_AREA1) after calling this function.
Definition at line 3009 of file datadep.c.
References FALSE, ili_symbolic(), TRUE, and use_visit.
Referenced by opt_binop().
dirv_chkzero()
int dirv_chkzero (DIRVEC dir, int n)
Definition at line 3020 of file datadep.c.
References DIRV_ENTRYG, i, and n.
Referenced by chkref(), and dd_array_conflict().
dirv_exo()
DIRVEC dirv_exo (int level, int flag)
Generate legal execution order direction vectors.
Parameters
level loop nesting level
flag says whether all '=' allowed
Definition at line 2018 of file datadep.c.
References DIRV_ALLEQ, DIRV_ENTRYP, DIRV_EQ, DIRV_LT, DIRV_STAR, i, level(), and vec.
Referenced by chkref(), and dd_array_conflict().
dirv_fulldep()
DIRVEC dirv_fulldep (int level)
Generate full dependence at a given level.
Definition at line 1999 of file datadep.c.
References DIRV_ALLEQ, DIRV_ENTSIZ, DIRV_STAR, i, level(), and vec.
Referenced by dd_compute(), do_subscript(), resolve_pp(), resolve_pv(), resolve_uv(), and resolve_vv().
dirv_gen()
void dirv_gen (DIRVEC dir, int * map, int nest, int ig, void(*)(DIRVEC) f)
Definition at line 2125 of file datadep.c.
References DIRV_ENTRYG, dirv_permute(), dovec(), f, i, and MAX_LOOPS.
Referenced by dd_array_conflict(), and dd_edge().
dirv_inverse()
DIRVEC dirv_inverse (DIRVEC vec)
Invert a direction vector.
Definition at line 1967 of file datadep.c.
References DIRV_ENTRYG, DIRV_ENTRYP, DIRV_INFOPART, i, MAX_LOOPS, t, and vec.
Referenced by chkref().
dirv_permute()
static DIRVEC dirv_permute (DIRVEC dir, int * m, int nest) static
Definition at line 2046 of file datadep.c.
References assert, base, DIRV_ALLEQ, DIRV_ENTRYG, DIRV_ENTSIZ, DIRV_EQ, DIRV_INFOPART, DIRV_LT, e, i, j, k, m, MAX_LOOPS, and skip.
Referenced by dirv_gen().
dirv_print()
char * dirv_print (DIRVEC dir)
Definition at line 3148 of file datadep.c.
References DIRV_ALLEQ, DIRV_ENTRYG, DIRV_EQ, DIRV_GT, DIRV_LT, DIRV_RD, i, MAX_LOOPS, p, and t.
Referenced by dd_edge(), dump_dd(), and hierarchy().
distrib()
static ARITH_LIST distrib (int ili, int mpyr) static
Definition at line 2777 of file datadep.c.
References ad1ili(), ad2ili(), apnd(), assert, arith_term::confact, distrib(), FLANG_FALLTHROUGH, getitem(), HLV_AREA1, IL_IADD, IL_IDIV, IL_IMUL, IL_INEG, IL_ISUB, IL_MOD, ili, ILI_OPC(), ILI_OPND(), ili_symbolic(), IS_IRES, arith_term::next, NULL, and arith_term::varfact.
Referenced by distrib(), and ili_symbolic().
do_subscript()
static void do_subscript (int nsubs) static
Definition at line 1277 of file datadep.c.
References ad1ili(), ad2ili(), ad_icon, add_dep(), assert, astb, Bound, BOUND_ADD, BTRACE1, C, CNSTG, d, DBGBIT, ddinfo, DIRV_ENTRYP, dirv_fulldep(), DIRV_STAR, Dist, DTRACE0, DTRACE2, FALSE, gbl, hierarchy(), i, IL_ASUB, IL_IADD, IL_IMUL, IL_INEG, IL_ISUB, ili, ili_symbolic(), interr(), IS_ARES, IS_CNST, IS_IRES, j, k, lp, MAX_N, n1, neqns, nfree, nsubs, nvars, prilitree, prmat(), q, RESG, SB_BASES, SB_STRIDE, skip, sub, symbolic_divide(), symbolic_mul(), t, T, tmp, TRUE, TU, vec, VL_LBND, VL_UBND, VP_DEPCHK, and XBIT.
Referenced by dd_array_conflict(), resolve_pp(), and resolve_vv().
dovec()
static void dovec (DIRVEC dir, DIRVEC dir1, int pos, int ig, void(*)(DIRVEC) f, int alleq, int seenlt) static
Definition at line 2090 of file datadep.c.
References DIRV_ALLEQ, DIRV_ENTRYG, DIRV_ENTSIZ, DIRV_EQ, DIRV_GT, DIRV_LT, DIRV_RD, dovec(), e, f, and pos.
Referenced by dirv_gen(), and dovec().
dump_dd()
void dump_dd (DDEDGE * p)
Definition at line 3185 of file datadep.c.
References DD_DIRVEC, DD_NEXT, DD_SINK, DD_TYPE, dirv_print(), gbl, and p.
Referenced by dump_one_memref().
dump_one_bound()
static void dump_one_bound (BOUND * p, int k, LOGICAL btype) static
Definition at line 3196 of file datadep.c.
References b, CNSTG, gbl, IS_CNST, j, k, p, and prilitree.
Referenced by compare_one_bound().
dump_termlist()
void dump_termlist (ARITH_LIST lst)
Definition at line 3290 of file datadep.c.
References arith_term::confact, gbl, arith_term::next, NULL, prilitree, and arith_term::varfact.
dump_two_bound()
static void dump_two_bound (BOUND * p, BOUND * q, int k, LOGICAL btype) static
Definition at line 3231 of file datadep.c.
References CNSTG, gbl, IS_CNST, j, k, p, prilitree, and q.
Referenced by compare_one_bound().
edge_func()
static void edge_func (DIRVEC vec) static
Definition at line 551 of file datadep.c.
References ddinfo, and vec.
Referenced by dd_edge().
elim()
static ARITH_LIST elim (ARITH_LIST lst) static
Definition at line 2929 of file datadep.c.
References combine_terms(), arith_term::confact, contains_common_factor(), arith_term::next, NULL, rdc, remove_terms(), sum(), TRUE, and arith_term::varfact.
Referenced by ili_symbolic().
fill_subscripts()
static int fill_subscripts (int astRef, int mr, int subStart, int ntriples, int astliTriples) static
Definition at line 2285 of file datadep.c.
References ASD_NDIM, ASD_SUBS, astb, ASTB::bnd, BZERO, fill_subscripts(), hlv, i, ili_symbolic(), interr(), mkSub(), MR_SUBCNT, n, ndim, NEED, ASTB::one, SB_BASE, SB_BASES, SB_STRIDE, sub, HLVECT::subavail, HLVECT::subbase, HLVECT::subsize, and ASTB::zero.
Referenced by dd_array_conflict(), and fill_subscripts().
floorg()
static int floorg (int t, int g) static
Definition at line 990 of file datadep.c.
References a, ddinfo, q, and t.
Referenced by compare_one_bound().
fwd_func()
static void fwd_func (DIRVEC dv) static
Definition at line 2272 of file datadep.c.
References DIRV_ENTRYG, DIRV_LT, fwd, and i.
Referenced by dd_array_conflict().
gcd()
static INT gcd (INT a, INT b) static
Definition at line 951 of file datadep.c.
References a, b, and r.
Referenced by compare_one_bound().
hierarchy()
static void hierarchy (DIRVEC dir, int lev, DIRVEC veco) static
Definition at line 1893 of file datadep.c.
References add_dep(), BCOPY, bottom, Bound, BOUND_LEN, check_bounds(), check_new_bound(), ddinfo, DIRV_ALLEQ, DIRV_ENTRYC, DIRV_ENTRYG, DIRV_ENTRYP, DIRV_EQ, DIRV_GT, DIRV_LT, dirv_print(), DIRV_STAR, DTRACE2, FALSE, hierarchy(), i, SaveBound, top, TRUE, and VP_DEPCHK.
Referenced by do_subscript(), and hierarchy().
ILI_OPC()
static int ILI_OPC (int astx) static
Definition at line 3088 of file datadep.c.
References A_OPTYPEG, DT_ISBASIC, IL_AADD, IL_ASUB, IL_IADD, IL_IDIV, IL_IMUL, IL_INEG, IL_ISUB, interr(), OP_ADD, OP_DIV, OP_MUL, and OP_SUB.
Referenced by distrib(), ili_symbolic(), refactor(), symbolic_divide(), and symbolic_mul().
ILI_OPND()
static int ILI_OPND (int astx, int opnd) static
Definition at line 3126 of file datadep.c.
References interr().
Referenced by distrib(), refactor(), symbolic_divide(), and symbolic_mul().
ili_symbolic()
static int ili_symbolic (int ili) static
Definition at line 2957 of file datadep.c.
References ad_icon, DBGBIT, distrib(), elim(), FALSE, gbl, ili, ILI_OPC(), ILI_REPL, ILI_VISIT, IS_CNST, IS_IRES, prilitree, rdc, refactor_list(), sum(), use_visit, and visit_chain.
Referenced by bnd_ge(), bnd_le(), bound_add(), compare_one_bound(), dd_symbolic(), distrib(), do_subscript(), and fill_subscripts().
is_linear()
static LOGICAL is_linear (int ast) static
Definition at line 2235 of file datadep.c.
References A_OPTYPEG, ast, FALSE, IS_IRES, is_linear(), OP_ADD, OP_MUL, OP_SUB, and TRUE.
Referenced by is_linear(), and mkSub().
mkSub()
static LOGICAL mkSub (int astliTriples, int sub, int astmpyr, int ast) static
Definition at line 2148 of file datadep.c.
References A_OPTYPEG, ast, astb, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, ASTB::bnd, ASTB::dtype, FALSE, FLANG_FALLTHROUGH, i, is_linear(), mk_binop(), mk_convert(), mk_unop(), mkSub(), ASTB::one, OP_ADD, OP_MUL, OP_SUB, SB_BASE, SB_STRIDE, sub, and TRUE.
Referenced by fill_subscripts(), and mkSub().
mr_precedes()
static LOGICAL mr_precedes (int mr1, int mr2) static
Definition at line 454 of file datadep.c.
References assert, FALSE, ILT_NEXT, mr1, mr2, MR_ILT, MR_TYPE, and TRUE.
Referenced by chkref().
prmat()
static void prmat (int col, int row) static
Definition at line 935 of file datadep.c.
References col, gbl, i, j, neqns, nvars, and prilitree.
Referenced by do_subscript().
refactor()
static void refactor (ARITH_LIST atp) static
Definition at line 2697 of file datadep.c.
References ad2ili(), ad_icon, CNSTG, arith_term::confact, IL_IMUL, IL_INEG, ILI_OPC(), ILI_OPND(), IS_CNST, arith_term::next, NULL, refactor(), and arith_term::varfact.
Referenced by refactor(), and refactor_list().
refactor_list()
static void refactor_list (ARITH_LIST lst) static
Definition at line 2741 of file datadep.c.
References arith_term::next, and refactor().
Referenced by ili_symbolic().
remove_terms()
static ARITH_LIST remove_terms (ARITH_LIST lst, int trm) static
Definition at line 2898 of file datadep.c.
References assert, arith_term::next, NULL, and arith_term::varfact.
Referenced by elim().
resolve_pp()
static void resolve_pp (void) static
Definition at line 733 of file datadep.c.
References add_dep(), BIH_LINENO, close_pragma(), ddinfo, dirv_fulldep(), do_subscript(), FG_TO_BIH, is_ptr_safe(), LP_HEAD, MR_SUBST, open_pragma(), unpack_loops(), and VP_DEPCHK.
Referenced by dd_compute().
resolve_pv()
static void resolve_pv (void) static
Definition at line 754 of file datadep.c.
References add_dep(), assert, BIH_LINENO, close_pragma(), ddinfo, dirv_fulldep(), FG_TO_BIH, is_ptr_safe(), is_sym_optsafe(), LP_HEAD, NME_TYPE, NT_IND, NT_VAR, and open_pragma().
Referenced by dd_compute().
resolve_uv()
static void resolve_uv (void) static
Definition at line 778 of file datadep.c.
References add_dep(), ddinfo, and dirv_fulldep().
Referenced by dd_compute().
resolve_vv()
static void resolve_vv (void) static
Definition at line 815 of file datadep.c.
References add_dep(), ASD_NDIM, assert, ddinfo, DIRV_ALLEQ, DIRV_ENTRYP, DIRV_EQ, dirv_fulldep(), DIRV_STAR, do_subscript(), i, j, MAXNMESIZ, MR_NME, MR_SCALR, NME_NM, NME_SUB, NME_SYM, NME_TYPE, NT_ARR, NT_MEM, NT_VAR, NULL, SCLR_NEXT, SCLR_NME, unpack_loops(), and VL_SCLIST.
Referenced by dd_compute().
sum()
static int sum (ARITH_LIST lst) static
Definition at line 2751 of file datadep.c.
References ad2ili(), ad_icon, arith_term::confact, IL_IADD, IL_IMUL, arith_term::next, and arith_term::varfact.
Referenced by combine_terms(), compute_size_ido(), compute_width_dtype(), distribute(), elim(), ili_symbolic(), LLTypeGetBytesUnchecked(), NORM2_REAL4(), and NORM2_REAL8().
symbolic_divide()
static LOGICAL symbolic_divide (int num, int den, int * quot) static
Definition at line 2590 of file datadep.c.
References ad1ili(), ad_icon, FALSE, IL_IMUL, IL_INEG, ILI_OPC(), ILI_OPND(), num, q, sign, and TRUE.
Referenced by do_subscript().
symbolic_mul()
static int symbolic_mul (int a, int b) static
Definition at line 2567 of file datadep.c.
References a, ad1ili(), ad2ili(), b, c, IL_IMUL, IL_INEG, ILI_OPC(), and ILI_OPND().
Referenced by do_subscript().
unpack_loops()
static void unpack_loops (void) static
Definition at line 784 of file datadep.c.
References assert, ddinfo, DTRACE2, i, j, LP_PARENT, MAX_DD, MR_LOOP, MR_SUBCNT, and MR_SUBST.
Referenced by resolve_pp(), and resolve_vv().
Variable Documentation
basenm1
int basenm1
Definition at line 216 of file datadep.c.
basenm2
int basenm2
Definition at line 216 of file datadep.c.
bFwd
LOGICAL bFwd
Definition at line 2268 of file datadep.c.
Bound
BOUND* Bound[MAX_N+1][2] static
Definition at line 930 of file datadep.c.
Referenced by check_bounds(), check_new_bound(), compare_one_bound(), do_subscript(), and hierarchy().
C
int C[MAX_S] static
Definition at line 925 of file datadep.c.
Referenced by __attribute__(), __fss_acos_fma3(), __fss_asin_fma3(), __reduction_slowpath(), __rvs_log_fma3(), __rvs_log_fma3_256(), do_subscript(), and reduction_slowpath().
common
int common
Definition at line 223 of file datadep.c.
Referenced by check_derived_type_in_comm(), fix_symbol(), lower_visit_symbol(), read_symbol(), and set_common_size().
struct { ... } ddinfo
Referenced by add_dep(), build_dd(), build_loop_dd(), ceilg(), chkref(), compare_one_bound(), dd_array_conflict(), dd_compute(), dd_edge(), do_subscript(), edge_func(), floorg(), hierarchy(), resolve_pp(), resolve_pv(), resolve_uv(), resolve_vv(), and unpack_loops().
Dist
int Dist[MAX_LOOPS] static
Definition at line 926 of file datadep.c.
Referenced by do_subscript().
dvlist
DV* dvlist
Definition at line 219 of file datadep.c.
fgbase
BV* fgbase static
Definition at line 264 of file datadep.c.
Referenced by build_loop_dd(), and dd_succ().
fgsucc
BVP* fgsucc static
Definition at line 263 of file datadep.c.
Referenced by build_loop_dd(), chkref(), and dd_succ().
struct { ... } fwd
Referenced by dd_array_conflict(), fwd_func(), ll_finish_variable(), lldbg_create_aggregate_members_type(), lldbg_create_global_variable_mdnode(), lldbg_create_local_variable_mdnode(), lldbg_create_member_mdnode(), lldbg_emit_global_variable(), and lldbg_emit_local_variable().
lps
short lps[MAX_DD]
Definition at line 224 of file datadep.c.
mr1
int mr1
Definition at line 214 of file datadep.c.
Referenced by mr_precedes().
mr2
int mr2
Definition at line 214 of file datadep.c.
Referenced by mr_precedes().
n
int n
Definition at line 222 of file datadep.c.
Referenced by __abort(), __abort_init(), __abort_sig_hand(), __abort_sig_init(), __ecvt(), __fcvt(), __fort_adjbase(), __fort_atol(), __fort_atoxi32(), __fort_atoxi64(), __fort_bcopy(), __fort_bcopysl(), __fort_bcstchn(), __fort_calloc(), __fort_calloc_without_abort(), __fort_chn_1toN(), __fort_chn_prune(), __fort_copy(), __fort_doit(), __fort_exchange_counts(), __fort_findndx(), __fort_fixmnt(), __fort_frechn(), __fort_gathscat(), __fort_gcalloc(), __fort_gcalloc_without_abort(), __fort_gcd(), __fort_genlist(), __fort_getenv(), __fort_getmap(), __fort_getopt(), __fort_getoptb(), __fort_getoptn(), __fort_gmalloc(), __fort_gmalloc_without_abort(), __fort_grealloc(), __fort_initcom(), __fort_initndx(), __fort_malloc(), __fort_malloc_without_abort(), __fort_passargs(), __fort_psignal(), __fort_realloc(), __fort_recvl(), __fort_reduce_section(), __fort_rstchn(), __fort_sendl(), __fort_sethand(), __fort_trac_init(), __fort_zclose(), __fort_zopen(), __fortio_fmt_g(), __fortio_loop(), __INT8_T(), __INT_T(), __mth_i_bessel_jn(), __mth_i_bessel_yn(), __mth_i_dbessel_jn(), __mth_i_dbessel_yn(), _dumpnme(), _exp_smove(), _f90io_encode_fmt(), _f90io_nml_write(), _index(), _mp_calloc(), _mp_malloc(), _mp_realloc(), _printili(), _printnme(), _put(), _xtoi(), a1tos1(), a4tos1(), add(), add_fpsrc(), add_fpte(), add_triple(), addbran(), addn(), adNilm(), advance(), advance_permuted(), advance_seed_lf(), advance_seed_npb(), all_zeroes(), alloc_fpbuf(), analyz(), assem_emit_align(), atosi32(), atosi64(), atoui64(), atoxd(), atoxf(), atoxi(), atoxi64(), atoxq(), block_setup(), cg_get_type(), check_moved_list(), checkfltol(), cmpat_dtype_with_size(), CONCAT(), condec(), conv_bint_ilm(), conv_forall(), conv_int(), conv_int8_ilm(), conv_int_ilm(), conv_sint_ilm(), copy(), copy_bytes(), copy_loop(), cpu(), createUplevelSptr(), cvtp_cp(), cvtp_set(), cyclic_setup(), decompose_expression(), dinit_fseek(), dinit_fseek_end(), dinit_fskip(), dinit_put(), dinit_put_string(), dinit_read(), dinit_read_string(), dirv_chkzero(), div_shift(), dodef(), dump_list_node(), dumphashlk(), dumpmessagelist(), dumpnme(), dumpnmes(), dumpnnme(), ef_putiotype(), enan(), ENT3F(), ENTF90(), ENTF90IO(), ENTFTN(), ENTRY(), errnum(), eval_index(), exp_agoto(), exp_cgoto(), exp_pure(), exp_strcpy(), export_one_ast(), expr_dependent_check(), fastset_resize(), fih_sort_children(), fill(), fill_subscripts(), find_const_bound_rhs(), Fio_asy_close(), Fio_asy_disable(), Fio_asy_enable(), Fio_asy_read(), Fio_asy_write(), Ftn_nstr_copy(), Ftn_nstr_copy_klen(), Ftn_str_copy(), Ftn_str_copy_klen(), fused_multiply_add_canonical_form(), g_count(), gathscat_loop(), gathscat_mask_loop(), gathscat_maxval_int1(), gathscat_maxval_int2(), gathscat_maxval_int4(), gathscat_maxval_int8(), gathscat_maxval_real16(), gathscat_maxval_real4(), gathscat_maxval_real8(), gathscat_minval_int1(), gathscat_minval_int2(), gathscat_minval_int4(), gathscat_minval_int8(), gathscat_minval_real16(), gathscat_minval_real4(), gathscat_minval_real8(), generic_atoxi(), gentmp(), get_cstring(), get_forall_subscr(), get_int_literal(), get_literal(), get_shape_arraydtype(), get_type(), get_vcon(), get_vcon0(), get_vcon1(), get_vcon_scalar(), get_vconm0(), get_vector_dtype(), getarg(), getbits(), getccssym(), getccssym_sc(), getccsym(), getccsym_sc(), getcctmp(), getcctmp_sc(), getnewccsym(), glist(), hashmap_iterate(), hashmap_sort(), hashset_iterate(), have_preheader(), hxatoxd(), hxatoxf(), hxatoxq(), ia_cachesize(), ia_cores(), ia_unifiedcache(), ic_strncmp(), ifih_sort_children(), ili_opnd(), import_use_stmts(), init_arg_ili(), inline_add_func(), IPA_allcall_safe(), IPA_call_safe(), IPA_func_almostpure(), IPA_func_pure(), IPA_noaddr(), IPA_pointer_safe(), IPA_pstride(), IPA_range(), IPA_safe(), IPA_sstride(), is_array_in_expr(), is_dist_array_in_expr(), is_invariant_list(), is_lonely_idx(), is_name_in_expr(), is_nonscalar_array_in_expr(), is_std_hoistable(), llObjtodbgFree(), local_copy(), local_gather_CPLX16(), local_gather_CPLX32(), local_gather_CPLX8(), local_gather_INT1(), local_gather_INT2(), local_gather_INT4(), local_gather_INT8(), local_gather_LOG1(), local_gather_LOG2(), local_gather_LOG4(), local_gather_LOG8(), local_gather_REAL16(), local_gather_REAL4(), local_gather_REAL8(), local_gather_WRAPPER(), local_gathscat_CPLX16(), local_gathscat_CPLX32(), local_gathscat_CPLX8(), local_gathscat_INT1(), local_gathscat_INT2(), local_gathscat_INT4(), local_gathscat_INT8(), local_gathscat_LOG1(), local_gathscat_LOG2(), local_gathscat_LOG4(), local_gathscat_LOG8(), local_gathscat_REAL16(), local_gathscat_REAL4(), local_gathscat_REAL8(), local_gathscat_WRAPPER(), local_scatter_CPLX16(), local_scatter_CPLX32(), local_scatter_CPLX8(), local_scatter_INT1(), local_scatter_INT2(), local_scatter_INT4(), local_scatter_INT8(), local_scatter_LOG1(), local_scatter_LOG2(), local_scatter_LOG4(), local_scatter_LOG8(), local_scatter_REAL16(), local_scatter_REAL4(), local_scatter_REAL8(), local_scatter_WRAPPER(), lower_put_datatype(), lower_symbols(), manshftl(), manshftr(), mark_dtype(), mask_for_entries(), mk_forall_sptr(), mk_swlist(), mk_swtab(), mk_swtab_ll(), newprintfd(), newprintfi(), newprintfl(), newprintfs(), newprintfx(), normalize_forall(), olap_copy(), olap_recv(), olap_send(), parse_d(), parse_f(), parse_q(), pntset(), position_finder(), pp_params(), pprintnme(), print_loop(), printnme(), prng_loop_d_lf(), prng_loop_d_npb(), prng_loop_r_lf(), prng_loop_r_npb(), put_ncharstring_n(), put_string_n(), putnme(), putsname(), putvline(), rdilts(), read_overlap(), reciprocal_division(), reciprocal_division_64(), reciprocal_mod(), reciprocal_mod_64(), rehash(), remove_from_use_tree(), reorder_dfn_loops(), reorderloops(), rm_smove(), ILMTPApp::run(), s1toa4(), same_dtype(), SCALAR_SIZE(), scatter_maxval_int1(), scatter_maxval_int2(), scatter_maxval_int4(), scatter_maxval_int8(), scatter_maxval_real16(), scatter_maxval_real4(), scatter_maxval_real8(), scatter_minval_int1(), scatter_minval_int2(), scatter_minval_int4(), scatter_minval_int8(), scatter_minval_real16(), scatter_minval_real4(), scatter_minval_real8(), semantio(), sequentialize(), set_tp(), sort_message_list(), sptrListFree(), stash_paths(), stg_clear(), stg_clear_force(), stg_next(), subscr_dependent_check(), subscript_allocmem(), sym_visible_in_scope(), symdentry(), symini_errfatal(), symini_error(), tobinary(), top_sort(), types_equal(), ui64toa(), vect_llvm_intrinsic_name(), vector_member(), wrilts(), write_llaccgroup_metadata(), write_record(), wtline(), xref(), xudiv(), and xumod().
n1
int n1
Definition at line 221 of file datadep.c.
Referenced by CONCAT(), conflict(), do_subscript(), ENT3F(), f90_bessel_jn(), f90_bessel_yn(), f90_dbessel_jn(), f90_dbessel_yn(), F90_nme_conflict(), IPA_nme_conflict(), manmul(), normalize_forall_array(), and sortgm().
n2
int n2
Definition at line 221 of file datadep.c.
Referenced by CONCAT(), conflict(), ENT3F(), f90_bessel_jn(), f90_bessel_yn(), f90_dbessel_jn(), f90_dbessel_yn(), F90_nme_conflict(), IPA_nme_conflict(), manmul(), and sortgm().
neqns
int neqns static
Definition at line 919 of file datadep.c.
Referenced by do_subscript(), and prmat().
nfree
int nfree static
Definition at line 920 of file datadep.c.
Referenced by bnd_ge(), bnd_le(), bound_add(), check_bounds(), and do_subscript().
nloops
int nloops
Definition at line 2267 of file datadep.c.
nvars
int nvars static
Definition at line 918 of file datadep.c.
Referenced by bound_add(), do_subscript(), and prmat().
outer_loop
int outer_loop
Definition at line 217 of file datadep.c.
pragmas
VPRAGMAS pragmas
Definition at line 225 of file datadep.c.
rdc
LOGICAL rdc static
Definition at line 2644 of file datadep.c.
Referenced by elim(), and ili_symbolic().
SaveBound
BOUND* SaveBound[MAX_N+1][2] static
Definition at line 931 of file datadep.c.
Referenced by check_new_bound(), and hierarchy().
subs1
int subs1
Definition at line 215 of file datadep.c.
Referenced by normalize_forall_array().
subs2
int subs2
Definition at line 215 of file datadep.c.
T
int T[MAX_N] static
Definition at line 924 of file datadep.c.
Referenced by _rbtree_insert(), do_subscript(), rb_find(), rb_free(), rb_insert(), rb_left_rotate(), rb_new(), rb_right_rotate(), and rb_walk().
TU
int TU[MAX_S][MAX_N] static
Definition at line 927 of file datadep.c.
Referenced by bnd_ge(), bnd_le(), bound_add(), and do_subscript().
UD
int UD[MAX_N][MAX_S+MAX_N] static
Definition at line 923 of file datadep.c.
unknown
int unknown
Definition at line 220 of file datadep.c.
Referenced by dumparref(), dumpsubinfo(), and write_layout_desc().
use_visit
LOGICAL use_visit = TRUE static
Definition at line 2646 of file datadep.c.
Referenced by dd_symbolic(), and ili_symbolic().
vec
DIRVEC vec
Definition at line 218 of file datadep.c.
Referenced by __fort_fetch_int_vector(), __fort_store_int_vector(), add_dep(), chkref(), dd_edge(), dirv_exo(), dirv_fulldep(), dirv_inverse(), do_subscript(), edge_func(), and generate_gather().
visit_chain
int visit_chain = 0 static
Definition at line 2645 of file datadep.c.
Referenced by cln_visit(), and ili_symbolic().