flang: dbug.c File Reference
dbug.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "type.h"
#include "fort_vars.h"
Functions
void ENTFTN (SET_TEST, set_test)
void ENTFTN (ABORTA, aborta)
void ENTFTN (ABORT, abort)
void __fort_print_scalar (void *adr, dtype kind)
void __fort_show_scalar (void *adr, dtype kind)
void I8() __fort_show_index (__INT_T rank, __INT_T *index)
void I8() __fort_show_section (F90_Desc *d)
void __fort_show_flags (__INT_T flags)
void ENTFTN (SHOW, show)
void ENTF90COMN (SHOW_, show_)
void I8() __fort_describe (char *b, F90_Desc *d)
void ENTFTN (DESCRIBE, describe)
static void I8() print_row (void *ab, __INT_T str, __INT_T cnt, dtype kind)
static void I8() print_loop (char *b, F90_Desc *d, __INT_T rowdim, __INT_T dim, __INT_T off)
void I8() __fort_print_local (void *b, F90_Desc *d)
void I8() __fort_print_vector (char *msg, void *adr, __INT_T str, __INT_T cnt, dtype kind)
Variables
static const char * intentnames [4] = {"INOUT", "IN", "OUT", "??"}
static const char * specnames [4]
static const char * dfmtabbrev []
Function Documentation
__fort_describe()
void I8() __fort_describe (char * b, F90_Desc * d)
Definition at line 408 of file dbug.c.
References __DESC, __fort_print_scalar(), __fort_show_flags(), __io_stderr(), __TEMPLATE, b, d, DIM_UBOUND_G, DIST_DIM_LAB_G, DIST_DIM_LOFFSET_G, DIST_DIM_NO_G, DIST_DIM_PO_G, DIST_DIM_UAB_G, DIST_SCOFF_G, F90_DIM_LBOUND_G, F90_DIM_LSTRIDE_G, F90_FLAGS_G, F90_KIND_G, F90_LBASE_G, F90_LSIZE_G, F90_RANK_G, F90_TAG_G, GET_DIST_TYPENAMES, ISSCALAR, ISSEQUENCE, and TYPEKIND.
Referenced by __fort_gathscat(), ENTFTN(), and mmul_mxv().
__fort_print_local()
void I8() __fort_print_local (void * b, F90_Desc * d)
Definition at line 666 of file dbug.c.
References __fort_cycle_bounds(), __fort_test, __io_stderr(), __OFF_TEMPLATE, b, d, F90_FLAGS_G, F90_LBASE_G, F90_RANK_G, I8, Min, and print_loop().
Referenced by mmul_mxm().
__fort_print_scalar()
void __fort_print_scalar (void * adr, dtype kind)
Definition at line 40 of file dbug.c.
References __CINT, __CPLX16, __CPLX32, __CPLX8, __DOUBLE, __FLOAT, __INT1, __INT2, __INT4, __INT8, __io_stderr(), __LOG1, __LOG2, __LOG4, __LOG8, __REAL16, __REAL4, __REAL8, __SHORT, __STR, ABSENTC, GET_DIST_MASK_LOG1, GET_DIST_MASK_LOG2, GET_DIST_MASK_LOG4, GET_DIST_MASK_LOG8, i, ISPRESENT, kind, NULL, and r.
Referenced by __fort_describe(), __fort_show_scalar(), ENTFTN(), eoshift_scalar(), gathscat_element(), kred_array_loop(), and red_array_loop().
__fort_print_vector()
void I8() __fort_print_vector (char * msg, void * adr, __INT_T str, __INT_T cnt, dtype kind)
Definition at line 683 of file dbug.c.
References __io_stderr(), cnt, GET_DIST_LCPU, I8, kind, msg(), print_row(), and str.
__fort_show_flags()
void __fort_show_flags (__INT_T flags)
Definition at line 183 of file dbug.c.
References __ALIGN_TARGET_MASK, __ALIGN_TARGET_SHIFT, __ASSUMED_OVERLAPS, __ASSUMED_SHAPE, __ASSUMED_SIZE, __BOGUSBOUNDS, __DIST_FORMAT_MASK, __DIST_FORMAT_SHIFT, __DIST_TARGET_AXIS, __DIST_TARGET_MASK, __DIST_TARGET_SHIFT, __DYNAMIC, __IDENTITY_MAP, __INHERIT, __INTENT_MASK, __INTENT_SHIFT, __io_stderr(), __LOCAL, __NO_OVERLAPS, __NOT_COPIED, __OFF_TEMPLATE, __SAVE, __SECTZBASE, __SEQUENCE, __SEQUENTIAL_SECTION, __TEMPLATE, flags, intent, intentnames, and specnames.
Referenced by __fort_describe(), ENTF90(), ENTF90COMN(), ENTFTN(), and void().
__fort_show_index()
void I8() __fort_show_index (__INT_T rank, __INT_T * index)
Definition at line 128 of file dbug.c.
References __io_stderr(), i, index, NULL, and rank.
Referenced by __fort_copy(), __fort_global_reduce(), __fort_reduce_section(), __fort_replicate_result(), __io_read(), __io_write(), ENTFTN(), and gathscat_element().
__fort_show_scalar()
void __fort_show_scalar (void * adr, dtype kind)
Definition at line 121 of file dbug.c.
References __fort_print_scalar(), __io_stderr(), GET_DIST_TYPENAMES, and kind.
Referenced by __fort_get_scalar(), copy_xfer_loop(), ENTFTN(), olap_copy(), olap_recv(), and olap_send().
__fort_show_section()
void I8() __fort_show_section (F90_Desc * d)
Definition at line 144 of file dbug.c.
References __DESC, __io_stderr(), d, DECL_DIM_PTRS, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_GSIZE_G, F90_RANK_G, F90_TAG_G, ISSCALAR, ISSEQUENCE, and SET_DIM_PTRS.
Referenced by __fort_copy(), __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), ENTF90COMN(), and ENTFTN().
ENTF90COMN()
void ENTF90COMN (SHOW_ , show_)
Definition at line 360 of file dbug.c.
References __DESC, __fort_dump_type(), __fort_show_flags(), __fort_show_section(), __io_stderr(), __POLY, b, d, DECL_DIM_PTRS, dest, DIST_PBASE_G, DIST_SCOFF_G, DPTR_UBOUND_G, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_LSIZE_G, F90_RANK_G, F90_TAG_G, GET_DIST_TYPENAMES, I8, and SET_DIM_PTRS.
ENTFTN() [1/5]
void ENTFTN (ABORT , abort)
Definition at line 33 of file dbug.c.
References __CLEN_T, CADR, CLEN, ENTFTN(), and msg().
ENTFTN() [2/5]
void ENTFTN (ABORTA , aborta)
Definition at line 23 of file dbug.c.
References __fort_abort(), CADR, CLEN, and msg().
ENTFTN() [3/5]
void ENTFTN (DESCRIBE , describe)
Definition at line 478 of file dbug.c.
References __fort_describe(), b, d, and I8.
ENTFTN() [4/5]
void ENTFTN (SET_TEST , set_test)
Definition at line 20 of file dbug.c.
References __fort_test, and t.
Referenced by ENTFTN().
ENTFTN() [5/5]
void ENTFTN (SHOW , show)
Definition at line 245 of file dbug.c.
References __fort_show_flags(), __fort_show_section(), __io_stderr(), b, d, DECL_DIM_PTRS, DECL_HDR_PTRS, DFMT, dfmtabbrev, DIST_ALIGN_TARGET_G, DIST_CACHED_G, DIST_DIST_TARGET_G, DIST_DPTR_AOFFSET_G, DIST_DPTR_ASTRIDE_G, DIST_DPTR_BLOCK_G, DIST_DPTR_CL_G, DIST_DPTR_CLB_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CNO_G, DIST_DPTR_COFSTR_G, DIST_DPTR_CS_G, DIST_DPTR_CYCLE_G, DIST_DPTR_LAB_G, DIST_DPTR_LOFFSET_G, DIST_DPTR_NO_G, DIST_DPTR_OLB_G, DIST_DPTR_OUB_G, DIST_DPTR_PAXIS_G, DIST_DPTR_PCOORD_G, DIST_DPTR_PO_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_PSTRIDE_G, DIST_DPTR_TAXIS_G, DIST_DPTR_TLB_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, DIST_DPTR_TUB_G, DIST_DPTR_UAB_G, DIST_INFO_G, DIST_MAPPED_G, DIST_NONSEQUENCE_G, DIST_PBASE_G, DIST_REPLICATED_G, DIST_SCOFF_G, DIST_SINGLE_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_LSIZE_G, F90_RANK_G, GET_DIST_TYPENAMES, I8, NONSEQ_OVERLAP, NONSEQ_SECTION, p, pd, SET_DIM_PTRS, t, and td.
print_loop()
static void I8() print_loop (char * b, F90_Desc * d, __INT_T rowdim, __INT_T dim, __INT_T off) static
Definition at line 629 of file dbug.c.
References __fort_block_bounds(), __io_stderr(), b, cl, d, DECL_DIM_PTRS, dim, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_KIND_G, F90_LEN_G, I8, k, n, off, print_loop(), print_row(), and SET_DIM_PTRS.
Referenced by __fort_print_local(), and print_loop().
print_row()
static void I8() print_row (void * ab, __INT_T str, __INT_T cnt, dtype kind) static
Definition at line 485 of file dbug.c.
References __CINT, __CPLX16, __CPLX32, __CPLX8, __fort_abort(), __INT1, __INT2, __INT4, __INT8, __io_stderr(), __LOG1, __LOG2, __LOG4, __LOG8, __REAL16, __REAL4, __REAL8, cnt, GET_DIST_MASK_LOG1, GET_DIST_MASK_LOG2, GET_DIST_MASK_LOG4, GET_DIST_MASK_LOG8, i, i4, i8, kind, r, r4, r8, and str.
Referenced by __fort_print_vector(), and print_loop().
Variable Documentation
dfmtabbrev
const char* dfmtabbrev[] static
Initial value:
= {"*", "BLK", "BLKK", "CYC", "CYCK", "GENB",
                                   "IND"}
Definition at line 178 of file dbug.c.
Referenced by ENTFTN().
intentnames
const char* intentnames[4] = {"INOUT", "IN", "OUT", "??"} static
Definition at line 173 of file dbug.c.
Referenced by __fort_show_flags().
specnames
const char* specnames[4] static
Initial value:
= {"OMITTED", "PRESCRIPTIVE", "DESCRIPTIVE",
                                   "TRANSCRIPTIVE"}
Definition at line 175 of file dbug.c.
Referenced by __fort_show_flags().