flang: debug_action.c File Reference
debug_action.c File Reference
#include "flang/ADT/hash.h"
#include "flang/ArgParser/debug_action.h"
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
Classes
struct action_map_
Internal representation of the action map.
struct action_list_
Action list.
Typedefs
typedef void(* action_t) (void)
An action is just a void function.
typedef struct action_list_ action_list_t
Action list.
Functions
void create_action_map (action_map_t **map)
Allocate and initialize action map data structure.
void destroy_action_map (action_map_t **map)
Deallocate action map data structure.
void add_action (action_map_t *map, const char *keyword, void(*action)(void))
Add action to action map.
void execute_actions_for_keyword (action_map_t *map, const char *keyword)
Execute action(s) for a given keyword.
void copy_action (const action_map_t *from, const char *keyword_from, action_map_t *to, const char *keyword_to)
Copy an action from one map to another.
Typedef Documentation
action_list_t
typedef struct action_list_ action_list_t
Action list.
action_t
typedef void(* action_t) (void)
An action is just a void function.
Definition at line 21 of file debug_action.c.
Function Documentation
add_action()
void add_action (action_map_t * map, const char * keyword, void(*)(void) action)
Add action to action map.
Add action to action map
Definition at line 53 of file debug_action.c.
References action_map_::actions, action_list_::actions, action_list_::count, hashmap_insert(), hashmap_lookup(), keyword(), malloc(), NULL, and void().
Referenced by init().
copy_action()
void copy_action (const action_map_t * from, const char * keyword_from, action_map_t * to, const char * keyword_to)
Copy an action from one map to another.
Copy an action from one map to another
Definition at line 99 of file debug_action.c.
References action_map_::actions, action_list_::actions, action_list_::count, count, hashmap_insert(), hashmap_lookup(), malloc(), NULL, and void().
Referenced by parse_arguments().
create_action_map()
void create_action_map (action_map_t ** map)
Allocate and initialize action map data structure.
Allocate and initialize action map data structure
Definition at line 33 of file debug_action.c.
References hash_functions_strings, hashmap_alloc(), and malloc().
Referenced by init().
destroy_action_map()
void destroy_action_map (action_map_t ** map)
Deallocate action map data structure.
Deallocate action map data structure
Definition at line 41 of file debug_action.c.
References hashmap_free(), and NULL.
Referenced by finish(), and init().
execute_actions_for_keyword()
void execute_actions_for_keyword (action_map_t * map, const char * keyword)
Execute action(s) for a given keyword.
Execute action(s) for a given keyword
Definition at line 80 of file debug_action.c.
References action_map_::actions, action_list_::actions, action_list_::count, hashmap_lookup(), index, keyword(), and NULL.
Referenced by do_debug().