flang: debug_action.h File Reference
debug_action.h File Reference
Debug action header file.
Typedefs
typedef struct action_map_ action_map_t
Forward-declared action map type.
Functions
void create_action_map (action_map_t **map)
Allocate and initialize action map data structure.
void destroy_action_map (action_map_t **map)
Deallocate action map data structure.
void add_action (action_map_t *map, const char *keyword, void(*action)(void))
Add action to action map.
void copy_action (const action_map_t *from, const char *keyword_from, action_map_t *to, const char *keyword_to)
Copy an action from one map to another.
void execute_actions_for_keyword (action_map_t *map, const char *keyword)
Execute action(s) for a given keyword.
Detailed Description
Debug action header file.
Definition in file debug_action.h.
Typedef Documentation
action_map_t
typedef struct action_map_ action_map_t
Forward-declared action map type.
Definition at line 17 of file debug_action.h.
Function Documentation
add_action()
void add_action (action_map_t * map, const char * keyword, void(*)(void) action)
Add action to action map.
Multiple invocations of this function can add set multiple actions to the same keyword as well as add the same action to multiple keyword.
Parameters
map action map
keyword string to associate the action with
action function pointer to invoke when argument is provided
Add action to action map
Definition at line 53 of file debug_action.c.
References action_map_::actions, action_list_::actions, action_list_::count, hashmap_insert(), hashmap_lookup(), keyword(), malloc(), NULL, and void().
Referenced by init().
copy_action()
void copy_action (const action_map_t * from, const char * keyword_from, action_map_t * to, const char * keyword_to)
Copy an action from one map to another.
Take whatever is associated with a given keyword in one map and copy it to another map.
Parameters
from action map to copy from
keyword_from keyword in original action map
to destination action map
keyword_to new keyword for the destination
Copy an action from one map to another
Definition at line 99 of file debug_action.c.
References action_map_::actions, action_list_::actions, action_list_::count, count, hashmap_insert(), hashmap_lookup(), malloc(), NULL, and void().
Referenced by parse_arguments().
create_action_map()
void create_action_map (action_map_t ** map)
Allocate and initialize action map data structure.
Parameters
map Action map structure to initialize
Allocate and initialize action map data structure
Definition at line 33 of file debug_action.c.
References hash_functions_strings, hashmap_alloc(), and malloc().
Referenced by init().
destroy_action_map()
void destroy_action_map (action_map_t ** map)
Deallocate action map data structure.
Deallocate action map data structure
Definition at line 41 of file debug_action.c.
References hashmap_free(), and NULL.
Referenced by finish(), and init().
execute_actions_for_keyword()
void execute_actions_for_keyword (action_map_t * map, const char * keyword)
Execute action(s) for a given keyword.
Order of execution is not guaranteed when multiple actions were added for the same keyword. An action that was added multiple times executes multiple times.
Parameters
map action map
keyword the keyword to look up actions
Execute action(s) for a given keyword
Definition at line 80 of file debug_action.c.
References action_map_::actions, action_list_::actions, action_list_::count, hashmap_lookup(), index, keyword(), and NULL.
Referenced by do_debug().