flang: desc.c File Reference
desc.c File Reference
#include "global.h"
#include "descRW.h"
#include "feddesc.h"
#include "format.h"
#include "unf.h"
#include "list_io.h"
Macros
#define TEMPLATE(dd, i, lb, ub, lbase, gsize)
Functions
__INT_T (char *ab, F90_Desc *ac)
void I8() get_vlist_desc (F90_Desc *sd, __INT_T ubnd)
Macro Definition Documentation
TEMPLATE
#define TEMPLATE (dd, i, lb, ub, lbase, gsize)
Value:
  {                                                                            \
    __INT_T __extent, u, l;                                                    \
    DECL_DIM_PTRS(_dd);                                                        \
    SET_DIM_PTRS(_dd, dd, i - 1);                                              \
    l = lb;                                                                    \
    u = ub;                                                                    \
    __extent = u - l + 1;                                                      \
    if (__extent < 0) {                                                        \
      __extent = 0;                                                            \
      u = l - 1;                                                               \
    }                                                                          \
    F90_DPTR_LBOUND_P(_dd, l);                                                 \
    DPTR_UBOUND_P(_dd, u);                                                     \
    F90_DPTR_SSTRIDE_P(_dd, 1);                                                \
    F90_DPTR_SOFFSET_P(_dd, 0);                                                \
    lbase -= gsize * l;                                                        \
    F90_DPTR_LSTRIDE_P(_dd, gsize);                                            \
    gsize *= __extent;                                                         \
  }
Definition at line 83 of file desc.c.
Function Documentation
__INT_T()
__INT_T (char * ab, F90_Desc * ac)
Definition at line 19 of file desc.c.
References __f90io_fmt_read(), __fortio_main(), and I8.
get_vlist_desc()
void I8() get_vlist_desc (F90_Desc * sd, __INT_T ubnd)
Definition at line 105 of file desc.c.
References __DIST_INIT_DESCRIPTOR, __INT4, __INT8, __NONE, F90_GSIZE_P, F90_KIND_P(), F90_LBASE_P, F90_LEN_P, F90_LSIZE_P, flags, lbase, NULL, rank, TEMPLATE, and type.
Referenced by ENTF90IO().