flang: descRW.h File Reference
descRW.h File Reference
Classes
struct fio_parm
Typedefs
typedef int(* f90io_rw_fn) (int, long, int, char *, __CLEN_T)
typedef struct fio_parm fio_parm
Functions
int I8() __fortio_main (char *ab, F90_Desc *ac, int rw, f90io_rw_fn f90io_rw)
void I8() __fortio_loop (fio_parm *z, int dim)
Typedef Documentation
f90io_rw_fn
typedef int(* f90io_rw_fn) (int, long, int, char *, __CLEN_T)
Definition at line 8 of file descRW.h.
fio_parm
typedef struct fio_parm fio_parm
Definition at line 10 of file descRW.h.
Function Documentation
__fortio_loop()
void I8() __fortio_loop (fio_parm * z, int dim)
Definition at line 17 of file descFioUtil.c.
References __fortio_loop(), DECL_DIM_PTRS, DECL_HDR_PTRS, dim, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, I8, n, SET_DIM_PTRS, and z.
Referenced by __fortio_loop(), and __fortio_main().
__fortio_main()
int I8() __fortio_main (char * ab, F90_Desc * ac, int rw, f90io_rw_fn f90io_rw)
Definition at line 91 of file descRW.c.
References __DERIVED, __DESC, __fort_abort(), __fort_describe_replication(), __fort_rbcstl(), __fortio_loop(), __fortio_stat_bcst, __io_read(), __io_write(), __STR, DIST_SCOFF_G, F90_GSIZE_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_IOPROC, GET_DIST_LCPU, GET_DIST_SIZE_OF, I8, kind, LOCAL_MODE, rw, TYPEKIND, and z.
Referenced by __INT_T().