flang: descRW.c File Reference
descRW.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "descRW.h"
#include "fort_vars.h"
Macros
#define __fort_owner(a, b) 0
#define __fort_next_owner(a, b, c, d) -1
#define __fortio_stat_bcst(a) (*(a))
Functions
char * __fort_getgbuf (long len)
static void I8() __io_read (fio_parm *z)
static void I8() __io_write (fio_parm *z)
int I8() __fortio_main (char *ab, F90_Desc *ac, int rw, f90io_rw_fn f90io_rw)
Macro Definition Documentation
__fort_next_owner
#define __fort_next_owner (a, b, c, d) -1
Definition at line 22 of file descRW.c.
__fort_owner
#define __fort_owner (a, b) 0
Definition at line 21 of file descRW.c.
__fortio_stat_bcst
#define __fortio_stat_bcst (a) (*(a))
Definition at line 24 of file descRW.c.
Function Documentation
__fort_getgbuf()
char * __fort_getgbuf (long len)
Definition at line 345 of file xfer.c.
References __fort_gfree(), __fort_gmalloc(), gbuf, GBUFA, gbufz, and len.
Referenced by __io_read().
__fortio_main()
int I8() __fortio_main (char * ab, F90_Desc * ac, int rw, f90io_rw_fn f90io_rw)
Definition at line 91 of file descRW.c.
References __DERIVED, __DESC, __fort_abort(), __fort_describe_replication(), __fort_rbcstl(), __fortio_loop(), __fortio_stat_bcst, __io_read(), __io_write(), __STR, DIST_SCOFF_G, F90_GSIZE_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_IOPROC, GET_DIST_LCPU, GET_DIST_SIZE_OF, I8, kind, LOCAL_MODE, rw, TYPEKIND, and z.
Referenced by __INT_T().
__io_read()
static void I8() __io_read (fio_parm * z) static
Definition at line 26 of file descRW.c.
References __fort_getgbuf(), __fort_local_address(), __fort_next_owner, __fort_owner, __fort_rrecvl(), __fort_rsendl(), __fort_show_index(), __fort_test, buf, DEBUG_HFIO, DECL_HDR_PTRS, F90_KIND_G, F90_LEN_G, F90_RANK_G, GET_DIST_IOPROC, GET_DIST_LCPU, i, I8, LOCAL_MODE, MAXDIMS, NULL, pc, str, and z.
Referenced by __fortio_main().
__io_write()
static void I8() __io_write (fio_parm * z) static
Definition at line 70 of file descRW.c.
References __fort_local_address(), __fort_show_index(), __fort_test, DEBUG_HFIO, DECL_HDR_PTRS, F90_KIND_G, F90_LEN_G, F90_RANK_G, GET_DIST_LCPU, I8, str, and z.
Referenced by __fortio_main().