flang: descIntrins.c File Reference
descIntrins.c File Reference
#include <string.h>
#include "fioMacros.h"
Functions
__INT_T (DCHAR(string) DCLEN64(string))
__INT_T (DCHAR(string) DCLEN(string))
__INT_T ENTFTN (LENXA, lenxa)
__INT_T ENTFTN (LENX, lenx)
__INT8_T (DCHAR(string) DCLEN64(string))
__INT8_T (DCHAR(string) DCLEN(string))
__INT8_T ENTFTN (KLENXA, klenxa)
__INT8_T ENTFTN (KLENX, klenx)
__INT_T (DCHAR(string), DCHAR(substring) DCLEN64(string) DCLEN64(substring))
version of index that takes no descriptor
__INT_T (DCHAR(string), DCHAR(substring) DCLEN(string) DCLEN(substring))
__INT8_T (DCHAR(string), DCHAR(substring) DCLEN64(string) DCLEN64(substring))
version of index that takes no descriptor
__INT8_T (DCHAR(string), DCHAR(substring) DCLEN(string) DCLEN(substring))
Detailed Description
These routines are substituted for intrinsic procedures which are passed as actual arguments. The intrinsics don't expect descriptors – these routines do.
Definition in file descIntrins.c.
Function Documentation
__INT8_T() [1/4]
__INT8_T (DCHAR(string) DCLEN(string))
Definition at line 60 of file descIntrins.c.
References __CLEN_T, CADR, CLEN, and ENTFTN().
__INT8_T() [2/4]
__INT8_T (DCHAR(string) DCLEN64(string))
Definition at line 53 of file descIntrins.c.
References CLEN.
Referenced by __INT8_T().
__INT8_T() [3/4]
__INT8_T (DCHAR(string) , DCHAR(substring) DCLEN(string) DCLEN(substring))
Definition at line 147 of file descIntrins.c.
References __CLEN_T, CADR, CLEN, ENTFTN(), and substring.
__INT8_T() [4/4]
__INT8_T (DCHAR(string) , DCHAR(substring) DCLEN64(string) DCLEN64(substring))
version of index that takes no descriptor
Definition at line 127 of file descIntrins.c.
References __INT8_T(), CADR, CLEN, i, n, and substring.
__INT_T() [1/4]
__INT_T (DCHAR(string) DCLEN(string))
Definition at line 38 of file descIntrins.c.
References __CLEN_T, CADR, CLEN, and ENTFTN().
__INT_T() [2/4]
__INT_T (DCHAR(string) DCLEN64(string))
Definition at line 30 of file descIntrins.c.
References CLEN.
Referenced by __INT_T().
__INT_T() [3/4]
__INT_T (DCHAR(string) , DCHAR(substring) DCLEN(string) DCLEN(substring))
Definition at line 102 of file descIntrins.c.
References __CLEN_T, CADR, CLEN, ENTFTN(), and substring.
__INT_T() [4/4]
__INT_T (DCHAR(string) , DCHAR(substring) DCLEN64(string) DCLEN64(substring))
version of index that takes no descriptor
Definition at line 82 of file descIntrins.c.
References __INT_T(), CADR, CLEN, i, n, and substring.
ENTFTN() [1/4]
__INT8_T ENTFTN (KLENX , klenx)
Definition at line 73 of file descIntrins.c.
References CLEN.
ENTFTN() [2/4]
__INT8_T ENTFTN (KLENXA , klenxa)
Definition at line 70 of file descIntrins.c.
References CLEN.
ENTFTN() [3/4]
__INT_T ENTFTN (LENX , lenx)
Definition at line 51 of file descIntrins.c.
References CLEN.
ENTFTN() [4/4]
__INT_T ENTFTN (LENXA , lenxa)
Definition at line 48 of file descIntrins.c.
References CLEN.
Referenced by __INT8_T(), and __INT_T().