flang: descFioUtil.c File Reference
descFioUtil.c File Reference
#include "fioMacros.h"
#include "descRW.h"
#include "global.h"
Functions
void I8() __fortio_loop (fio_parm *z, int dim)
void __fort_status_init (__INT_T *bitv, __INT_T *iostat)
__INT_T __fort_status_bcst (__INT_T s)
void __fortio_stat_init (__INT_T *bitv, __INT_T *iostat)
int __fortio_stat_bcst (int *stat)
Variables
static __INT_T fio_bitv
static __INT_T * fio_iostat
Function Documentation
__fort_status_bcst()
__INT_T __fort_status_bcst (__INT_T s)
Definition at line 69 of file descFioUtil.c.
References __fort_rbcst(), __INT, fio_bitv, FIO_BITV_EOF, FIO_BITV_EOR, FIO_BITV_ERR, FIO_BITV_IOSTAT, fio_iostat, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, msg(), and s.
__fort_status_init()
void __fort_status_init (__INT_T * bitv, __INT_T * iostat)
Definition at line 59 of file descFioUtil.c.
References bitv, fio_bitv, and fio_iostat.
Referenced by __INT_T(), and ENTF90IO().
__fortio_loop()
void I8() __fortio_loop (fio_parm * z, int dim)
Definition at line 17 of file descFioUtil.c.
References __fortio_loop(), DECL_DIM_PTRS, DECL_HDR_PTRS, dim, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, I8, n, SET_DIM_PTRS, and z.
Referenced by __fortio_loop(), and __fortio_main().
__fortio_stat_bcst()
int __fortio_stat_bcst (int * stat)
Definition at line 110 of file descFioUtil.c.
References __fort_rbcstl(), __INT, fio_bitv, FIO_BITV_EOF, FIO_BITV_EOR, FIO_BITV_ERR, FIO_BITV_IOSTAT, fio_iostat, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, msg(), and stat.
__fortio_stat_init()
void __fortio_stat_init (__INT_T * bitv, __INT_T * iostat)
Definition at line 101 of file descFioUtil.c.
References bitv, fio_bitv, and fio_iostat.
Variable Documentation
fio_bitv
__INT_T fio_bitv static
Definition at line 54 of file descFioUtil.c.
Referenced by __fort_status_bcst(), __fort_status_init(), __fortio_stat_bcst(), and __fortio_stat_init().
fio_iostat
__INT_T* fio_iostat static
Definition at line 55 of file descFioUtil.c.
Referenced by __fort_status_bcst(), __fort_status_init(), __fortio_stat_bcst(), and __fortio_stat_init().