flang: detect.c File Reference
detect.c File Reference
Detect communications for the communications module.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "soc.h"
#include "semant.h"
#include "ast.h"
#include "gramtk.h"
#include "comm.h"
#include "extern.h"
#include "hpfutl.h"
#include "commopt.h"
#include "symutl.h"
Functions
static void process_sub (int, int)
static void tag_comms (int)
static void matched_dim (int)
static void no_comm_class (int)
static void overlap_class (int)
static void convert_idx_scalar (int)
static int is_structured (int)
static LOGICAL is_array_in_expr (int ast)
static LOGICAL is_nonscalar_array_in_expr (int ast)
int tag_forall_comm (int ast)
Go through and tag the communications for this statement.
void process_rhs_sub (int a)
void dumpsubinfo (int subinfo, int ndim)
void dumparref (int arref)
void printastref (int ast)
static void printstdref_subscript (int ast, LOGICAL *junk)
void printstdref (int std)
LOGICAL scatter_class (int std)
LOGICAL is_indirection_in_it (int a)
Inquire whether array has indirection in its subscripts.
LOGICAL is_nonscalar_indirection_in_it (int a)
Inquire whether an array reference has indirection in its subscripts and the indirection has nonscalar subscripts.
LOGICAL is_vector_indirection_in_it (int a, int list)
Inquire whether array has indirection in its subscripts.
LOGICAL is_dist_array_in_expr (int ast)
Inquire whether expression has distributed array.
void search_idx (int ast, int list, int *astli, int *base, int *stride)
int process_lhs_sub (int std, int ast)
Detailed Description
Detect communications for the communications module.
Definition in file detect.c.
Function Documentation
convert_idx_scalar()
static void convert_idx_scalar (int arref) static
Definition at line 1606 of file detect.c.
References ARREF_NDIM, ARREF_SUB, astb, ASTB::bnd, i, j, ndim, SUBI_BASE, SUBI_DUPL, SUBI_IDX, SUBI_STRIDE, SUBI_SUB, zero, and ASTB::zero.
Referenced by process_lhs_sub().
dumparref()
void dumparref (int arref)
Definition at line 382 of file detect.c.
References ARREF_ARR, ARREF_ARRSYM, ARREF_CLASS, ARREF_FLAG, ARREF_NDIM, ARREF_NEXT, ARREF_SUB, ARREF_TEMP, ast, astb, COLLECTIVE, COMMT_CONST, COMMT_MULTI, COMMT_NONE, COMMT_NOTAG, COMMT_REPLICATE, COMMT_SHIFTC, COMMT_SHIFTV, COMMT_TRANSFER, COMMT_UNSTRUCT, COPY_SECTION, dumpsubinfo(), FILE, gbl, i, IRREGULAR, ndim, NO_CLASS, NO_COMM, NULL, outfile, OVERLAP, printast(), sptr, stb, TRANSFORM::stg_avail, TRANSFORM::stg_base, TRANSFORM::subb, SUBI_COMMT, SYMNAME, trans, and unknown.
Referenced by printastref().
dumpsubinfo()
void dumpsubinfo (int subinfo, int ndim)
Definition at line 253 of file detect.c.
References astb, ASTLI_SPTR, base, COMMT_CONST, COMMT_MULTI, COMMT_NONE, COMMT_NOTAG, COMMT_REPLICATE, COMMT_SHIFTC, COMMT_SHIFTV, COMMT_TRANSFER, COMMT_UNSTRUCT, FILE, gbl, i, idx, ndim, NULL, outfile, pop(), printast(), s, sptr, stb, stride, sub, SUBI_BASE, SUBI_CNST, SUBI_COMMT, SUBI_COMMV, SUBI_DIFF, SUBI_DSTT, SUBI_DUPL, SUBI_IDX, SUBI_LDIM, SUBI_NOP, SUBI_POP, SUBI_STRIDE, SUBI_SUB, SYMNAME, and unknown.
Referenced by dumparref().
is_array_in_expr()
static LOGICAL is_array_in_expr (int ast) static
Definition at line 1106 of file detect.c.
References A_ARGCNTG, argt, ARGT_ARG, ast, DTY, FALSE, i, interr(), is_array_in_expr(), n, sptr, and TRUE.
Referenced by is_array_in_expr(), is_indirection_in_it(), and is_vector_indirection_in_it().
is_dist_array_in_expr()
LOGICAL is_dist_array_in_expr (int ast)
Inquire whether expression has distributed array.
Definition at line 1255 of file detect.c.
References A_ARGCNTG, ALIGNG, argt, ARGT_ARG, ast, DTY, FALSE, i, interr(), is_dist_array_in_expr(), n, sptr, and TRUE.
Referenced by canonical_conversion(), and is_dist_array_in_expr().
is_indirection_in_it()
LOGICAL is_indirection_in_it (int a)
Inquire whether array has indirection in its subscripts.
Definition at line 1029 of file detect.c.
References a, ASD_NDIM, ASD_SUBS, FALSE, i, interr(), is_array_in_expr(), ndim, and TRUE.
Referenced by forall_with_mask(), and is_mask_for_rhs().
is_nonscalar_array_in_expr()
static LOGICAL is_nonscalar_array_in_expr (int ast) static
Definition at line 1180 of file detect.c.
References A_ARGCNTG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, ast, DTY, FALSE, i, interr(), is_nonscalar_array_in_expr(), n, ndim, sptr, sub, and TRUE.
Referenced by is_nonscalar_array_in_expr(), and is_nonscalar_indirection_in_it().
is_nonscalar_indirection_in_it()
LOGICAL is_nonscalar_indirection_in_it (int a)
Inquire whether an array reference has indirection in its subscripts and the indirection has nonscalar subscripts.
Definition at line 1055 of file detect.c.
References a, ASD_NDIM, ASD_SUBS, FALSE, i, interr(), is_nonscalar_array_in_expr(), ndim, and TRUE.
is_structured()
static int is_structured (int a) static
Definition at line 555 of file detect.c.
References a, ARREF_SUB, ASD_NDIM, ASTLI_SPTR, i, j, ndim, sptr, sptr_of_subscript(), SUBI_BASE, SUBI_IDX, SUBI_LDIM, and comminfo::subinfo.
Referenced by tag_comms().
is_vector_indirection_in_it()
LOGICAL is_vector_indirection_in_it (int a, int list)
Inquire whether array has indirection in its subscripts.
Definition at line 1078 of file detect.c.
References a, ASD_NDIM, ASD_SUBS, FALSE, i, interr(), is_array_in_expr(), is_vector_subscript(), list, ndim, sub, and TRUE.
Referenced by forall_lhs_indirection().
matched_dim()
static void matched_dim (int a) static
Definition at line 1328 of file detect.c.
References a, ARREF_SUB, ASD_NDIM, i, ndim, and SUBI_LDIM.
Referenced by process_rhs_sub().
no_comm_class()
static void no_comm_class (int a) static
Definition at line 651 of file detect.c.
References a, ALIGNG, ARREF_CLASS, ARREF_SUB, ASD_NDIM, astb, ASTB::bnd, COMMT_CONST, COMMT_NONE, dist_ast(), FALSE, comminfo::forall, i, lhs, ndim, NO_COMM, sptr, sptr_of_subscript(), SUBI_COMMT, SUBI_STRIDE, zero, and ASTB::zero.
Referenced by tag_comms().
overlap_class()
static void overlap_class (int a) static
Definition at line 593 of file detect.c.
References a, ARREF_CLASS, ARREF_SUB, ASD_NDIM, COMMT_CONST, COMMT_NONE, COMMT_SHIFTC, count, i, j, ndim, OVERLAP, sptr, sptr_of_subscript(), comminfo::sub, SUBI_CNST, SUBI_COMMT, SUBI_COMMV, SUBI_DIFF, and SUBI_LDIM.
Referenced by tag_comms().
printastref()
void printastref (int ast)
Definition at line 487 of file detect.c.
References ast, dumparref(), FILE, gbl, memsym_of_ast(), NULL, outfile, printast(), sptr, and SYMNAME.
Referenced by printstdref_subscript().
printstdref()
void printstdref (int std)
Definition at line 517 of file detect.c.
References ast, ast_traverse(), ast_unvisit(), ast_visit(), astb, FILE, gbl, NULL, outfile, printast(), printstdref_subscript(), std, and STD_AST.
printstdref_subscript()
static void printstdref_subscript (int ast, LOGICAL * junk) static
Definition at line 509 of file detect.c.
References ast, and printastref().
Referenced by printstdref().
process_lhs_sub()
int process_lhs_sub (int std, int ast)
Definition at line 1522 of file detect.c.
References ALIGNG, TRANSFORM::arrb, ARREF_ARR, ARREF_ARRSYM, ARREF_CLASS, ARREF_NDIM, ARREF_NEXT, ARREF_SUB, ARREF_TEMP, ASD_NDIM, ASD_SUBS, assert, ast, convert_idx_scalar(), comminfo::forall, FT_CYCLIC, i, CTYPE::idx, left_nonscalar_subscript_ast(), left_subscript_ast(), comminfo::lhs, TRANSFORM::lhs, CTYPE::lhs, lhs, list, comminfo::mask_phase, NO_CLASS, process_sub(), sptr, sptr_of_subscript(), comminfo::std, std, TRANSFORM::stg_avail, TRANSFORM::stg_size, comminfo::sub, TRANSFORM::subb, SUBI_BASE, SUBI_DSTT, SUBI_DUPL, SUBI_IDX, SUBI_NOP, SUBI_POP, SUBI_SUB, comminfo::subinfo, trans, TRANS_NEED, comminfo::ugly_mask, and comminfo::unstruct.
Referenced by transform_forall().
process_rhs_sub()
void process_rhs_sub (int a)
Definition at line 164 of file detect.c.
References a, ALIGNG, TRANSFORM::arrb, ARREF_ARR, ARREF_ARRSYM, ARREF_CLASS, ARREF_NDIM, ARREF_NEXT, ARREF_SUB, ARREF_TEMP, ASD_NDIM, ASD_SUBS, assert, COMMT_NOTAG, comminfo::forall, i, matched_dim(), ndim, NO_CLASS, process_sub(), TRANSFORM::rhsbase, sptr, sptr_of_subscript(), TRANSFORM::stg_avail, TRANSFORM::stg_size, comminfo::sub, TRANSFORM::subb, SUBI_COMMT, SUBI_DSTT, SUBI_DUPL, SUBI_NOP, SUBI_POP, SUBI_SUB, trans, and TRANS_NEED.
Referenced by emit_permute_section(), and tag_comms().
process_sub()
static void process_sub (int sub, int list) static
Definition at line 1494 of file detect.c.
References base, list, search_idx(), stride, sub, SUBI_BASE, SUBI_IDX, SUBI_STRIDE, and SUBI_SUB.
Referenced by process_lhs_sub(), and process_rhs_sub().
scatter_class()
LOGICAL scatter_class (int std)
Definition at line 921 of file detect.c.
References FALSE.
Referenced by forall_lhs_indirection(), and is_scatter().
search_idx()
void search_idx (int ast, int list, int * astli, int * base, int * stride)
Definition at line 1345 of file detect.c.
References A_OPTYPEG, ast, astb, ASTLI_NEXT, ASTLI_SPTR, base, ASTB::bnd, ASTB::dtype, i, list, mk_convert(), mk_isz_cval(), OP_ADD, OP_MUL, OP_SUB, opt_binop(), opt_unop(), search_forall_idx(), search_idx(), stride, zero, and ASTB::zero.
Referenced by canonical_conversion(), forall_2_sec(), is_triplet(), process_sub(), and search_idx().
tag_comms()
static void tag_comms (int a) static
Definition at line 216 of file detect.c.
References a, ALIGNG, ARREF_CLASS, ASD_NDIM, assert, comminfo::forall, is_structured(), lhs, ndim, NO_CLASS, NO_COMM, no_comm_class(), overlap_class(), process_rhs_sub(), sptr, sptr_of_subscript(), and comminfo::sub.
Referenced by tag_forall_comm().
tag_forall_comm()
int tag_forall_comm (int ast)
Go through and tag the communications for this statement.
Returns
0 if any unstructured communication
Definition at line 52 of file detect.c.
References a, A_ARGCNTG, A_OPTYPEG, ALIGNG, argt, ARGT_ARG, ARREF_CLASS, ASD_NDIM, ASD_SUBS, assert, ast, i, interr(), nargs, ndim, OVERLAP, r, sptr, sptr_of_subscript(), src, comminfo::std, std, tag_comms(), and tag_forall_comm().
Referenced by call_comm(), tag_forall_comm(), and transform_forall().