flang: dexp2.c File Reference
dexp2.c File Reference
#include "libm_amd.h"
#include "libm_util_amd.h"
#include "libm_inlines_amd.h"
#include "libm_errno_amd.h"
Macros
#define USE_SPLITEXP
#define USE_SCALEDOUBLE_1
#define USE_SCALEDOUBLE_2
#define USE_ZERO_WITH_FLAGS
#define USE_INFINITY_WITH_FLAGS
#define USE_HANDLE_ERROR
Functions
static double retval_errno_erange_overflow (double x __attribute__((unused)))
static double retval_errno_erange_underflow (double x __attribute__((unused)))
double FN_PROTOTYPE() mth_i_dexp2 (double x)
Macro Definition Documentation
USE_HANDLE_ERROR
#define USE_HANDLE_ERROR
Definition at line 50 of file dexp2.c.
USE_INFINITY_WITH_FLAGS
#define USE_INFINITY_WITH_FLAGS
Definition at line 49 of file dexp2.c.
USE_SCALEDOUBLE_1
#define USE_SCALEDOUBLE_1
Definition at line 46 of file dexp2.c.
USE_SCALEDOUBLE_2
#define USE_SCALEDOUBLE_2
Definition at line 47 of file dexp2.c.
USE_SPLITEXP
#define USE_SPLITEXP
Definition at line 45 of file dexp2.c.
USE_ZERO_WITH_FLAGS
#define USE_ZERO_WITH_FLAGS
Definition at line 48 of file dexp2.c.
Function Documentation
mth_i_dexp2()
double FN_PROTOTYPE() mth_i_dexp2 (double x)
Definition at line 74 of file dexp2.c.
References EMAX_DP64, EMIN_DP64, GET_BITS_DP64, m, MANTBITS_DP64, PUT_BITS_DP64, retval_errno_erange_overflow(), retval_errno_erange_underflow(), SIGNBIT_DP64, x, y, y1(), and z.
Referenced by mth_i_rpowr().
retval_errno_erange_overflow()
static double retval_errno_erange_overflow (double x __attribute__(unused)) inline static
Definition at line 63 of file dexp2.c.
References AMD_F_INEXACT, and AMD_F_OVERFLOW.
Referenced by mth_i_dexp2().
retval_errno_erange_underflow()
static double retval_errno_erange_underflow (double x __attribute__(unused)) inline static
Definition at line 69 of file dexp2.c.
References AMD_F_INEXACT, and AMD_F_UNDERFLOW.
Referenced by mth_i_dexp2().