flang: dinitutl.cpp File Reference
dinitutl.cpp File Reference
SCFTN data initialization file utilities.
#include "dinitutl.h"
#include "error.h"
#include "global.h"
#include "dinit.h"
#include "ilm.h"
#include "dtypeutl.h"
Functions
static void dump_buff (char)
void dinit_init (void)
...
void dinit_put (DTYPE dtype, ISZ_T conval)
...
void dinit_put_string (ISZ_T len, char *str)
...
DREC * dinit_read (void)
...
void dinit_read_string (ISZ_T len, char *str)
...
long dinit_ftell (void)
...
void dinit_fskip (long off)
...
void dinit_fseek (long off)
...
void dinit_end (void)
...
void dinit_save (void)
Save and restore position and mode of the dinit file.
void dinit_restore (void)
...
bool df_is_open (void)
...
Variables
static char mode = ' '
static FILE * df = NULL
static DREC t
static char savemode
static long savepos
Detailed Description
SCFTN data initialization file utilities.
Definition in file dinitutl.cpp.
Function Documentation
df_is_open()
bool df_is_open (void)
...
Definition at line 255 of file dinitutl.cpp.
References df, and NULL.
dinit_end()
void dinit_end (void)
...
Definition at line 213 of file dinitutl.cpp.
References DBGBIT, df, fclose(), FREE, gbl, ILMB::ilm_base, ilmb, mode, NULL, and RU_BDATA.
Referenced by assem_end(), cleanup(), datastructure_reinit(), and fe_restart().
dinit_fseek()
void dinit_fseek (long off)
...
Definition at line 201 of file dinitutl.cpp.
References assert, DBGBIT, df, ERR_Fatal, gbl, mode, n, and off.
Referenced by get_struct_from_dsrt2(), lower_data_stmts(), and process_dsrt().
dinit_fskip()
void dinit_fskip (long off)
...
Definition at line 191 of file dinitutl.cpp.
References assert, df, ERR_Fatal, mode, n, and off.
Referenced by dinits(), and get_struct_from_dsrt2().
dinit_ftell()
long dinit_ftell (void)
...
Definition at line 183 of file dinitutl.cpp.
References df, and NULL.
Referenced by dinits(), and end_module().
dinit_init()
void dinit_init (void)
...
Definition at line 33 of file dinitutl.cpp.
References df, and mode.
Referenced by datastructure_reinit(), and reinit().
dinit_put()
void dinit_put (DTYPE dtype, ISZ_T conval)
...
Definition at line 45 of file dinitutl.cpp.
References CNULL, DREC::conval, DBGBIT, df, DREC::dtype, dump_buff(), ERR_Fatal, errfatal(), error(), mode, n, NULL, t, and tmpfile().
dinit_put_string()
void dinit_put_string (ISZ_T len, char * str)
...
Definition at line 75 of file dinitutl.cpp.
References CNULL, DBGBIT, df, ERR_Fatal, error(), gbl, len, mode, n, NULL, and str.
dinit_read()
DREC * dinit_read (void)
...
Definition at line 91 of file dinitutl.cpp.
References assert, DREC::conval, DBGBIT, df, DINIT_ENDFILE, DREC::dtype, dump_buff(), ERR_Fatal, gbl, mode, n, NULL, and t.
Referenced by dinits(), get_struct_from_dsrt2(), lower_data_stmts(), and process_dsrt().
dinit_read_string()
void dinit_read_string (ISZ_T len, char * str)
...
Definition at line 122 of file dinitutl.cpp.
References df, len, mode, n, and str.
Referenced by emit_init().
dinit_restore()
void dinit_restore (void)
...
Definition at line 246 of file dinitutl.cpp.
References df, mode, savemode, and savepos.
dinit_save()
void dinit_save (void)
Save and restore position and mode of the dinit file.
...
Definition at line 236 of file dinitutl.cpp.
References df, mode, savemode, and savepos.
dump_buff()
static void dump_buff (char mode) static
Definition at line 134 of file dinitutl.cpp.
References buf, DREC::conval, DINIT_DATASECT, DINIT_FUNCCOUNT, DINIT_LABEL, DINIT_LOC, DINIT_OFFSET, DINIT_REPEAT, DINIT_SECT, DINIT_SLOC, DINIT_STRING, DINIT_ZEROES, STB::dt, DREC::dtype, gbl, getdtype(), getprint(), ISZ_PF, mode, stb, and t.
Referenced by dinit_put(), and dinit_read().
Variable Documentation
df
FILE* df = NULL static
Definition at line 26 of file dinitutl.cpp.
Referenced by df_is_open(), dinit_end(), dinit_fseek(), dinit_fskip(), dinit_ftell(), dinit_init(), dinit_put(), dinit_put_string(), dinit_read(), dinit_read_string(), dinit_restore(), and dinit_save().
mode
char mode = ' ' static
Definition at line 25 of file dinitutl.cpp.
Referenced by dinit_end(), dinit_fseek(), dinit_fskip(), dinit_init(), dinit_put(), dinit_put_string(), dinit_read(), dinit_read_string(), dinit_restore(), dinit_save(), and dump_buff().
savemode
char savemode static
Definition at line 229 of file dinitutl.cpp.
Referenced by dinit_restore(), and dinit_save().
savepos
long savepos static
Definition at line 230 of file dinitutl.cpp.
Referenced by dinit_restore(), and dinit_save().
t
DREC t static
Definition at line 28 of file dinitutl.cpp.
Referenced by dinit_put(), dinit_read(), and dump_buff().