flang: dinit.c File Reference
dinit.c File Reference
Process data initialization statements. Called by semant.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "semant.h"
#include "semstk.h"
#include "dinit.h"
#include "ast.h"
#include "state.h"
#include "pd.h"
Macros
#define ERR170(s1, s2) error(170, 2, gbl.lineno, s1, s2)
Functions
static int chk_doindex (int)
void dmp_ivl (VAR *ivl, FILE *f)
Dump an initializer variable list to a file (or stderr if no file provided).
void dmp_ict (ACL *ict, FILE *dfil)
Dump an initializer constant tree to a file (dfil==0 --> stderr).
static char * acl_idname (int)
static char * ac_opname (int)
static void dinit_data (VAR *, ACL *, int)
static ISZ_T arrayref_size (ACL *)
static void mark_dinit (VAR *, ACL *)
static void dinit_acl_val (int, int, ACL *)
static void dinit_intr_call (int, int, ACL *)
static void dinit_subs (ACL *)
static int dinit_val (int, int, int, int, int)
static int dinit_hollerith (int, int, int)
static void find_base (int, int *, int *)
static void sym_is_dinitd (int)
void dinit (VAR *ivl, ACL *ict)
void do_dinit (void)
Read in the information a "record" (1 word, 2 pointers) at a time saved by dinit(), and write dinit records for each record.
void dinit_no_dinitp (VAR *ivl, ACL *ict)
void df_dinit_end ()
void df_dinit (VAR *ivl, ACL *ict)
static void setConval (int sptr, int conval, int op)
static void process_real_kind (int sptr, ACL *ict, int op)
static void dinit_acl_val2 (int sptr, int dtype, ACL *ict, int op)
INT dinit_eval (int ast)
static void mark_ivl_dinit (VAR *ivl)
LOGICAL dinit_ok (int sptr)
...
void rw_dinit_state (RW_ROUTINE, RW_FILE)
Variables
static LOGICAL no_dinitp = FALSE
Detailed Description
Process data initialization statements. Called by semant.
Definition in file dinit.c.
Macro Definition Documentation
ERR170
#define ERR170 (s1, s2) error(170, 2, gbl.lineno, s1, s2)
Definition at line 44 of file dinit.c.
Function Documentation
ac_opname()
static char * ac_opname (int id) static
Definition at line 1274 of file dinit.c.
References AC_ADD, AC_ARRAYREF, AC_CAT, AC_CONV, AC_DIV, AC_EQ, AC_EXP, AC_EXPK, AC_EXPX, AC_GE, AC_GT, AC_INTR_CALL, AC_LAND, AC_LE, AC_LEQV, AC_LNEQV, AC_LNOT, AC_LOR, AC_LT, AC_MEMBR_SEL, AC_MUL, AC_NE, AC_NEG, AC_SUB, and AC_TRIPLE.
Referenced by dmp_ict().
acl_idname()
static char * acl_idname (int id) static
Definition at line 1214 of file dinit.c.
References AC_ACONST, AC_AST, AC_CONST, AC_CONVAL, AC_EXPR, AC_ICONST, AC_IDENT, AC_IDO, AC_IEXPR, AC_LIST, AC_REPEAT, AC_SCONST, AC_TRIPLE, AC_TYPEINIT, AC_VMSSTRUCT, and AC_VMSUNION.
Referenced by dmp_ict().
arrayref_size()
static ISZ_T arrayref_size (ACL * sect) static
Definition at line 489 of file dinit.c.
References c, get_isz_cval(), interr(), ISZ_T, lowb, nelem, size, stride, t, and upb.
Referenced by dinit_data().
chk_doindex()
static int chk_doindex (int ast) static
Definition at line 1444 of file dinit.c.
References ast, SEM::dinit_error, DT_ISINT, errsev(), sem, and TRUE.
Referenced by dinit_data().
df_dinit()
void df_dinit (VAR * ivl, ACL * ict)
Parameters
ivl pointer to initializer variable list
ict pointer to initializer constant tree
Definition at line 184 of file dinit.c.
References DBGBIT, dinit_data(), dinit_subs(), dmp_ict(), dmp_ivl(), SEM::dostack, gbl, sem, _acl::sptr, sym_is_dinitd(), and SEM::top.
Referenced by do_dinit(), init_allocatable_typedef_components(), and save_typedef_init().
df_dinit_end()
void df_dinit_end (void)
Definition at line 172 of file dinit.c.
References astb, ASTB::df, fclose(), and NULL.
Referenced by cleanup(), and semfin().
dinit()
void dinit (VAR * ivl, ACL * ict)
Instead of creating dinit records during the processing of data initializations, we need to save information so the records are written at the end of semantic analysis (during semfin). This is necessary for at least a couple of reasons: 1). a record dcl with inits in its STRUCTURE could occur before resolution of its storage class (problematic is SC_CMBLK) 2). with VMS ftn, an array may be initialized (not by implied DO) before resolution of its stype (i.e., its DIMENSION).
The information we need to save is the pointers to the var list and constant tree. This also implies that the getitem areas (4, 5) need to stay around until dinit output.
Definition at line 60 of file dinit.c.
References astb, CNULL, ASTB::df, SEM::dinit_nbr_inits, errfatal(), error(), gbl, VAR::id, mark_dinit(), NULL, VAR::ptr, S_IDENT, sem, tmpfile(), VAR::u, and VAR::varref.
Referenced by dinit_constructor(), dinit_no_dinitp(), gen_dinit(), get_dtype_init_template(), init_sptr_w_acl(), mkvarref(), semant1(), and Writedata().
dinit_acl_val()
static void dinit_acl_val (int sptr, int dtype, ACL * ict) static
Definition at line 865 of file dinit.c.
References dinit_acl_val2(), and sptr.
Referenced by dinit_data(), and dinit_subs().
dinit_acl_val2()
static void dinit_acl_val2 (int sptr, int dtype, ACL * ict, int op) static
Definition at line 712 of file dinit.c.
References _selected_char_kind(), AC_ACONST, AC_ADD, AC_ARRAYREF, AC_AST, AC_CONST, AC_CONV, AC_DIV, AC_EQ, AC_EXP, AC_EXPK, AC_EXPX, AC_GE, AC_GT, AC_I_selected_char_kind, AC_I_selected_int_kind, AC_I_selected_real_kind, AC_IDENT, AC_IDO, AC_IEXPR, AC_INTR_CALL, AC_LAND, AC_LE, AC_LEQV, AC_LNEQV, AC_LNOT, AC_LOR, AC_LT, AC_MEMBR_SEL, AC_MUL, AC_NE, AC_NEG, AC_SUB, ast, _acl::ast, aux, cmpat_dtype_array_cast(), cmpat_dtype_with_size(), CONVAL2G, DDTG, dinit_acl_val2(), dinit_intr_call(), dinit_val(), DTY, _acl::dtype, AUX::dvl_avl, AUX::dvl_base, DVL_CONVAL, AUX::dvl_size, DVL_SPTR, errsev(), _acl::expr, flg, _acl::id, interr(), AEXPR::lop, NEED, AEXPR::op, FLG::opt, process_real_kind(), AEXPR::rop, setConval(), sptr, string_length(), _acl::subc, TY_CHAR, TY_NCHAR, _acl::u1, CONST::u1, val, and XBIT.
Referenced by dinit_acl_val(), and dinit_acl_val2().
dinit_data()
static void dinit_data (VAR * ivl, ACL * ict, int dtype) static
Definition at line 215 of file dinit.c.
References AC_ACONST, AC_ARRAYREF, AC_IDO, AC_IEXPR, AD_NUMELM, AD_PTR, ADD_NUMELM, arrayref_size(), assert, ast, _acl::ast, chk_doindex(), DOSTACK::currval, DDTG, dinit_acl_val(), dinit_data(), SEM::dinit_error, dinit_eval(), dinit_hollerith(), dinit_val(), Doend, VAR::doend, SEM::dostack, Dostart, VAR::dostart, DTY, _acl::dtype, VAR::dtype, ERR170, errsev(), _acl::expr, FALSE, find_base(), flg, get_int_cval(), get_isz_cval(), get_seen_contains(), get_type(), _acl::id, VAR::id, VAR::indvar, is_empty_typedef(), is_tbp_or_final(), is_zero_size_typedef(), ISZ_T, len, VAR::lowbd, MAX_DOSTACK, mk_cval(), _acl::next, VAR::next, NOSYM, NULL, AEXPR::op, VAR::ptr, _acl::repeatc, AEXPR::rop, s, sem, VAR::shape, size_of_array(), sptr, DOSTACK::sptr, FLG::standard, DOSTACK::step, VAR::step, string_length(), _acl::subc, sym_is_dinitd(), sym_of_ast(), SYMNAME, SEM::top, TRUE, VAR::u, _acl::u1, uf, DOSTACK::upbd, VAR::upbd, Varref, VAR::varref, void(), and XBIT.
Referenced by df_dinit(), and dinit_data().
dinit_eval()
INT dinit_eval (int ast)
Definition at line 1463 of file dinit.c.
References A_OPTYPEG, ast, CNULL, SEM::dinit_error, dinit_eval(), SEM::dostack, DT_ISINT, error(), errsev(), FLANG_FALLTHROUGH, gbl, get_int_cval(), OP_ADD, OP_DIV, OP_MUL, OP_SUB, p, sem, sptr, SYMNAME, SEM::top, and TRUE.
Referenced by _dinit_acl(), compute_size_ido(), dinit_data(), dinit_eval(), dinit_getval(), dinit_subs(), eval_do(), and find_base().
dinit_hollerith()
static int dinit_hollerith (int sptr, int dtype, int holl_const) static
Definition at line 1090 of file dinit.c.
References val.
Referenced by dinit_data().
dinit_intr_call()
static void dinit_intr_call (int sptr, int dtype, ACL * ict) static
Definition at line 874 of file dinit.c.
References AC_AST, AC_I_null, AC_ICONST, ADD_NUMELM, assert, _acl::ast, astb, DDTG, DT_PTR, DTY, _acl::dtype, errsev(), _acl::expr, GET_ACL, get_type(), ASTB::i0, _acl::id, CONST::id, _acl::is_const, ASTB::k0, AEXPR::lop, _acl::next, _acl::ptrdtype, _acl::repeatc, sptr, _acl::sptr, _acl::u1, and CONST::u1.
Referenced by dinit_acl_val2().
dinit_no_dinitp()
void dinit_no_dinitp (VAR * ivl, ACL * ict)
Definition at line 163 of file dinit.c.
References dinit(), FALSE, no_dinitp, _acl::no_dinitp, and TRUE.
Referenced by build_typedef_init_tree().
dinit_ok()
LOGICAL dinit_ok (int sptr)
...
Definition at line 1602 of file dinit.c.
References CNULL, SEM::dinit_error, error(), FALSE, gbl, sem, sptr, SYMNAME, and TRUE.
Referenced by find_base(), and gen_dinit().
dinit_subs()
static void dinit_subs (ACL * ict) static
Definition at line 542 of file dinit.c.
References AC_ACONST, AC_AST, AC_CONST, AC_EXPR, AC_IDENT, AC_IDO, AC_IEXPR, AC_REPEAT, AC_SCONST, AC_TYPEINIT, _acl::ast, DDTG, dinit_acl_val(), dinit_eval(), dinit_subs(), dinit_val(), _acl::dtype, i, _acl::id, _acl::next, _acl::repeatc, sptr, _acl::sptr, _acl::subc, _acl::u1, and void().
Referenced by df_dinit(), and dinit_subs().
dinit_val()
static int dinit_val (int sptr, int dtype, int dtypev, int astval, int op) static
Definition at line 942 of file dinit.c.
References astb, buf, cngcon(), CNULL, CONVAL2G, DT_ISINT, DT_ISLOG, DTY, DTYG, eq_dtype(), error(), errsev(), flg, gbl, getcon(), getstring(), ASTB::i1, is_procedure_ptr(), mk_cnst(), FLG::opt, sptr, FLG::standard, SYMNAME, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, TY_SLOG, TY_WORD, val, and XBIT.
Referenced by dinit_acl_val2(), dinit_data(), and dinit_subs().
dmp_ict()
void dmp_ict (ACL * ict, FILE * dfil)
Dump an initializer constant tree to a file (dfil==0 --> stderr).
Definition at line 1152 of file dinit.c.
References AC_AST, AC_CONST, AC_EXPR, AC_ICONST, AC_IDENT, AC_IDO, AC_IEXPR, ac_opname(), AC_REPEAT, acl_idname(), dmp_ict(), i, level(), _acl::next, and SYMNAME.
Referenced by df_dinit(), and dmp_ict().
dmp_ivl()
void dmp_ivl (VAR * ivl, FILE * f)
Dump an initializer variable list to a file (or stderr if no file provided).
...
Definition at line 1108 of file dinit.c.
References assert, dmp_ivl(), Doend, VAR::doend, Dostart, VAR::dostart, f, FILE, VAR::id, VAR::next, VAR::ptr, S_IDENT, VAR::shape, SYMNAME, VAR::u, Varref, and VAR::varref.
Referenced by df_dinit(), and dmp_ivl().
do_dinit()
void do_dinit (void)
Read in the information a "record" (1 word, 2 pointers) at a time saved by dinit(), and write dinit records for each record.
...
Definition at line 97 of file dinit.c.
References assert, astb, DBGBIT, ASTB::df, df_dinit(), FALSE, fclose(), gbl, no_dinitp, _acl::no_dinitp, NULL, and TRUE.
Referenced by semfin(), and upper().
find_base()
static void find_base (int ast, int * psptr, int * pmemptr) static
Definition at line 1366 of file dinit.c.
References a, AD_LWAST, AD_PTR, AD_UPAST, ASD_NDIM, ASD_SUBS, ast, CNULL, SEM::dinit_error, dinit_eval(), dinit_ok(), error(), find_base(), gbl, get_int_cval(), i, ndim, offset, sem, sptr, sym_of_ast(), SYMNAME, TRUE, and void().
Referenced by dinit_data(), and find_base().
mark_dinit()
static void mark_dinit (VAR * ivl, ACL * ict) static
Definition at line 1589 of file dinit.c.
References mark_ivl_dinit(), NULL, _acl::sptr, and sym_is_dinitd().
Referenced by dinit().
mark_ivl_dinit()
static void mark_ivl_dinit (VAR * ivl) static
Definition at line 1574 of file dinit.c.
References VAR::id, mark_ivl_dinit(), VAR::next, NULL, VAR::ptr, sptr, sym_is_dinitd(), sym_of_ast(), VAR::u, Varref, and VAR::varref.
Referenced by mark_dinit(), and mark_ivl_dinit().
process_real_kind()
static void process_real_kind (int sptr, ACL * ict, int op) static
Definition at line 647 of file dinit.c.
References ast, _acl::ast, CONVAL2G, _acl::next, setConval(), sptr, _acl::u1, and XBIT.
Referenced by dinit_acl_val2().
rw_dinit_state()
void rw_dinit_state (RW_ROUTINE , RW_FILE)
Definition at line 1647 of file dinit.c.
References assert, astb, ASTB::df, SEM::dinit_nbr_inits, errfatal(), fd, FILE, file_pos, i, VAR::id, interr(), ISREAD, lineno, NULL, VAR::ptr, RW_SCALAR, S_IDENT, sem, tmpfile(), VAR::u, VAR::varref, and void().
Referenced by rw_host_state().
setConval()
static void setConval (int sptr, int conval, int op) static
Definition at line 586 of file dinit.c.
References AC_ADD, AC_DIV, AC_EQ, AC_GE, AC_GT, AC_LAND, AC_LE, AC_LNOT, AC_LOR, AC_LT, AC_MUL, AC_NE, AC_NEG, AC_SUB, error(), gbl, NULL, sptr, and val.
Referenced by dinit_acl_val2(), and process_real_kind().
sym_is_dinitd()
static void sym_is_dinitd (int sptr) static
Definition at line 1540 of file dinit.c.
References is_procedure_ptr(), no_dinitp, off, sptr, and ST_ISVAR.
Referenced by df_dinit(), dinit_data(), mark_dinit(), and mark_ivl_dinit().
Variable Documentation
no_dinitp
LOGICAL no_dinitp = FALSE static
Definition at line 42 of file dinit.c.
Referenced by dinit_no_dinitp(), do_dinit(), and sym_is_dinitd().