flang: dinitutl.c File Reference
dinitutl.c File Reference
Utilities for processing the data init file.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "dtypeutl.h"
#include "semant.h"
#include "dinit.h"
Functions
static void dump_buff (const char *)
void dinit_init (void)
...
void dinit_put (int dtype, INT conval)
DREC * dinit_read (void)
...
long dinit_ftell (void)
...
void dinit_fseek (long off)
...
void dinit_fseek_end (void)
void dinit_end (void)
...
void dinit_newfile (FILE *newdf)
void dinit_save (void)
Save and restore position and mode of the dinit file.
void dinit_restore (void)
...
Variables
static char mode
static FILE * df = NULL
static DREC t
static char savemode
static long savepos
Detailed Description
Utilities for processing the data init file.
Definition in file dinitutl.c.
Function Documentation
dinit_end()
void dinit_end (void)
...
Definition at line 185 of file dinitutl.c.
Referenced by dinit_newfile().
dinit_fseek()
void dinit_fseek (long off)
...
Definition at line 150 of file dinitutl.c.
dinit_fseek_end()
void dinit_fseek_end (void)
Definition at line 168 of file dinitutl.c.
References assert, DBGBIT, df, gbl, mode, and n.
Referenced by lower_data_stmts().
dinit_ftell()
long dinit_ftell (void)
...
Definition at line 142 of file dinitutl.c.
dinit_init()
void dinit_init (void)
...
Definition at line 28 of file dinitutl.c.
dinit_newfile()
void dinit_newfile (FILE * newdf)
Definition at line 199 of file dinitutl.c.
References df, dinit_end(), and mode.
dinit_put()
void dinit_put (int dtype, INT conval)
Definition at line 34 of file dinitutl.c.
References CNULL, DREC::conval, DBGBIT, df, DREC::dtype, dump_buff(), errfatal(), error(), gbl, mode, n, NULL, t, and tmpfile().
Referenced by _dinit_acl(), _put(), ch_substring(), dinit_name(), dinit_subs(), dinit_val(), dinit_varref(), do_nml(), makezero(), mk_swlist(), mk_swtab_ll(), put_a_init_tree(), put_data(), put_dinit_record(), put_funccount(), put_name(), putzero(), read_init(), and semantio().
dinit_read()
DREC * dinit_read (void)
...
Definition at line 61 of file dinitutl.c.
dinit_restore()
void dinit_restore (void)
...
Definition at line 222 of file dinitutl.c.
dinit_save()
void dinit_save (void)
Save and restore position and mode of the dinit file.
...
Definition at line 212 of file dinitutl.c.
dump_buff()
static void dump_buff (const char * str) static
Definition at line 94 of file dinitutl.c.
References buf, DREC::conval, DINIT_END, DINIT_FMT, DINIT_LABEL, DINIT_LOC, DINIT_NML, DINIT_OFFSET, DINIT_REPEAT, DINIT_STR, DINIT_ZEROES, DREC::dtype, gbl, getdtype(), getprint(), str, and t.
Referenced by dinit_put(), and dinit_read().
Variable Documentation
df
FILE* df = NULL static
Definition at line 21 of file dinitutl.c.
Referenced by _dmp_doif(), add_def(), bld_lhs(), bld_ud(), build_do_init(), const_prop(), copy_const(), dinit_end(), dinit_fseek(), dinit_fseek_end(), dinit_ftell(), dinit_newfile(), dinit_put(), dinit_read(), dinit_restore(), dinit_save(), dmp_doif(), ENTFTN(), in_kernel_region(), recopy(), sem_err104(), sem_err105(), and use_before_def().
mode
char mode static
Definition at line 20 of file dinitutl.c.
Referenced by __fort_par_open(), __io_binary_mode(), __io_setmode_binary(), access_swtab_base_label(), dinit_end(), dinit_fseek(), dinit_fseek_end(), dinit_init(), dinit_newfile(), dinit_put(), dinit_read(), dinit_restore(), dinit_save(), ENT3F(), installsym_ex(), is_omp_mode_target(), open_files(), rdgilms(), set_gilmb_mode(), and should_round_up().
savemode
char savemode static
Definition at line 206 of file dinitutl.c.
Referenced by dinit_restore(), and dinit_save().
savepos
long savepos static
Definition at line 207 of file dinitutl.c.
Referenced by dinit_restore(), and dinit_save().
t
DREC t static
Definition at line 25 of file dinitutl.c.
Referenced by dinit_put(), dinit_read(), and dump_buff().