flang: dinitutl.h File Reference
dinitutl.h File Reference
#include "gbldefs.h"
#include "symtab.h"
Functions
bool df_is_open (void)
...
struct DREC * dinit_read (void)
...
long dinit_ftell (void)
...
void dinit_end (void)
...
void dinit_fseek (long off)
...
void dinit_fskip (long off)
...
void dinit_init (void)
...
void dinit_put (DTYPE dtype, ISZ_T conval)
...
void dinit_put_string (ISZ_T len, char *str)
...
void dinit_read_string (ISZ_T len, char *str)
...
void dinit_restore (void)
...
void dinit_save (void)
...
Function Documentation
df_is_open()
bool df_is_open (void)
...
Definition at line 255 of file dinitutl.cpp.
References df, and NULL.
dinit_end()
void dinit_end (void)
...
Definition at line 185 of file dinitutl.c.
References df, fclose(), FREE, gbl, ILMB::ilm_base, ilmb, mode, NULL, and RU_BDATA.
Referenced by dinit_newfile().
dinit_fseek()
void dinit_fseek (long off)
...
Definition at line 150 of file dinitutl.c.
References assert, df, ERR_Fatal, mode, n, and off.
dinit_fskip()
void dinit_fskip (long off)
...
Definition at line 191 of file dinitutl.cpp.
References assert, df, ERR_Fatal, mode, n, and off.
Referenced by dinits(), and get_struct_from_dsrt2().
dinit_ftell()
long dinit_ftell (void)
...
Definition at line 142 of file dinitutl.c.
References df.
dinit_init()
void dinit_init (void)
...
Definition at line 28 of file dinitutl.c.
References df, and mode.
dinit_put()
void dinit_put (DTYPE dtype, ISZ_T conval)
...
Definition at line 45 of file dinitutl.cpp.
References CNULL, DREC::conval, DBGBIT, df, DREC::dtype, dump_buff(), ERR_Fatal, errfatal(), error(), mode, n, NULL, t, and tmpfile().
dinit_put_string()
void dinit_put_string (ISZ_T len, char * str)
...
Definition at line 75 of file dinitutl.cpp.
References CNULL, DBGBIT, df, ERR_Fatal, error(), gbl, len, mode, n, NULL, and str.
dinit_read()
struct DREC * dinit_read (void)
...
Definition at line 61 of file dinitutl.c.
References assert, DREC::conval, DBGBIT, df, DINIT_ENDFILE, DREC::dtype, dump_buff(), ERR_Fatal, mode, n, NULL, and t.
dinit_read_string()
void dinit_read_string (ISZ_T len, char * str)
...
Definition at line 122 of file dinitutl.cpp.
References df, len, mode, n, and str.
Referenced by emit_init().
dinit_restore()
void dinit_restore (void)
...
Definition at line 222 of file dinitutl.c.
References df, mode, savemode, and savepos.
dinit_save()
void dinit_save (void)
...
...
Definition at line 212 of file dinitutl.c.
References df, mode, savemode, and savepos.