flang: dinit.cpp File Reference
dinit.cpp File Reference
SCFTN routine to process data initialization statements; called by semant.
#include "dinit.h"
#include "dinitutl.h"
#include "dtypeutl.h"
#include "semant.h"
#include "ilm.h"
#include "ilmtp.h"
#include "machardf.h"
#include "semutil0.h"
#include "symfun.h"
Classes
struct EFFADR
Effective address of a reference being initialized.
struct DOSTACK
struct INDEX
Macros
#define CONST_ERR(dt) (const_err.dtype = dt, clone_init_const(&const_err, true))
#define MAXDIMS 7
#define MAXDEPTH 8
#define THRESHOLD 6
#define MAX_EXP_QVALUE 4931 /* max value exponent */
#define MAX_EXP_OF_QMANTISSA 33 /* 2^112 : 5.19e+33 */
#define REAL_16 16
#define REAL_0 0
#define RADIX2 2 /* Binary */
#define NOT_GET_VAL 0 /* 0 is default, This should be ruled out */
#define NO_REAL -5 /* if the processor supports no real type with radix RADIX */
#define KANJI_BLANK 0xA1A1
#define TRACE_EVAL_SB 0
#define ABS(x) (((x) > 0) ? (x) : (-(x)))
#define INTINTRIN2(iname, ent, op)
#define GET_DBLE(x, y)
#define GET_QUAD(x, y)
#define GETVALI64(x, b)
#define C90_HUGE "0.136343516952426e+2466" /* 0577757777777777777776 */
#define FPINTRIN1(iname, ent, fscutil, dscutil, qscutil)
#define FPINTRIN2(iname, ent, fscutil, dscutil, qscutil)
Functions
static EFFADR * mkeffadr (int ilmptr)
derefence an ilm pointer to determine the effective address of a reference (i.e. base sptr + byte offset).
static ISZ_T eval (int)
static char * acl_idname (int)
static void dinit_subs (CONST *ict, SPTR base, ISZ_T boffset, SPTR mbr_sptr)
FIXME.
static void dinit_val (SPTR sptr, DTYPE dtypev, INT val)
static ISZ_T get_ival (DTYPE, INT)
static INT _fdiv (INT dividend, INT divisor)
static void _ddiv (INT *dividend, INT *divisor, INT *quotient)
static CONST * eval_init_expr_item (CONST *cur_e)
static CONST * eval_array_constructor (CONST *e)
static CONST * eval_init_expr (CONST *e)
static CONST * eval_do (CONST *ido)
static CONST * clone_init_const (CONST *original, int temp)
static CONST * clone_init_const_list (CONST *original, int temp)
static void add_to_list (CONST *val, CONST **root, CONST **tail)
static void save_init (CONST *ict, SPTR sptr)
static void df_dinit (VAR *, CONST *)
static CONST * dinit_varref (VAR *ivl, SPTR member, CONST *ict, DTYPE dtype, int *struct_bytes_initd, ISZ_T *repeat, ISZ_T base_off)
void dinit (VAR *ivl, CONST *ict)
...
static void sym_is_dinitd (SPTR sptr)
a symbol is being initialized update certain attributes of the symbol including its dinit flag
void do_dinit (void)
Read in the information a "record" (1 word, 2 pointers) at a time saved by dinit(), and write dinit records for each record.
static int chk_doindex (int ilmptr)
Find the sptr for the implied do index variable The ilm in this context represents the ilms generated to load the index variable and perhaps "type" convert (if it's integer*2, etc.).
static void dinit_data (VAR *ivl, CONST *ict, DTYPE dtype, ISZ_T base_off)
Initialize a data object.
static bool is_zero (DTYPE dtype, INT conval)
Return true if the constant of the given dtype represents zero.
void dmp_ivl (VAR *ivl, FILE *f)
...
void dmp_ict (CONST *ict, FILE *f)
...
bool dinit_ok (int sptr)
determine if the symbol can be legally data initialized
static int get_ast_op (int op)
static INT init_fold_const (int opr, INT conval1, INT conval2, DTYPE dtype)
static INT init_negate_const (INT conval, DTYPE dtype)
static ISZ_T eval_sub_index (int dim)
static int eval_sb (int d)
static CONST * eval_const_array_triple_section (CONST *curr_e)
static CONST * eval_const_array_section (CONST *lop, DTYPE ldtype, DTYPE dtype)
static INLINE CONST * eval_ishft (CONST *arg, DTYPE dtype)
Evaluate compile-time constant produced by ISFHT intrinsic.
static CONST * eval_ichar (CONST *arg, DTYPE dtype)
static CONST * eval_char (CONST *arg, DTYPE dtype)
static INLINE CONST * eval_int (CONST *arg, DTYPE dtype)
static CONST * eval_null (CONST *arg, DTYPE dtype)
static CONST * eval_fltconvert (CONST *arg, DTYPE dtype)
static CONST * eval_abs (CONST *arg, DTYPE dtype)
static CONST * eval_min (CONST *arg, DTYPE dtype)
static CONST * eval_max (CONST *arg, DTYPE dtype)
static bool cmp_acl (DTYPE dtype, CONST *x, CONST *y, bool want_max, bool back)
static bool incr_index (INDEX *index)
static unsigned get_offset_without_dim (INDEX *index, unsigned dim)
static int _huge (DTYPE dtype)
static INT negate_const_be (INT conval, DTYPE dtype)
int mk_unop (int optype, int lop, DTYPE dtype)
...
int mk_smallest_val (DTYPE dtype)
...
int mk_largest_val (DTYPE dtype)
...
static CONST * get_minmax_val (DTYPE dtype, bool want_max)
static CONST * convert_acl_dtype (CONST *head, DTYPE oldtype, DTYPE newtype)
static CONST * do_eval_minval_or_maxval (INDEX *index, DTYPE elem_dt, DTYPE loc_dt, CONST *elems, unsigned dim, CONST *mask, bool back, int intrin)
static CONST * eval_scale (CONST *arg, int type)
static CONST * eval_minval_or_maxval (CONST *arg, DTYPE dtype, int intrin)
static CONST * eval_nint (CONST *arg, DTYPE dtype)
static INLINE CONST * eval_floor (CONST *arg, DTYPE dtype)
static INLINE CONST * eval_ceiling (CONST *arg, DTYPE dtype)
static CONST * eval_mod (CONST *arg, DTYPE dtype)
static CONST * eval_repeat (CONST *arg, DTYPE dtype)
static CONST * eval_len_trim (CONST *arg, DTYPE dtype)
static CONST * eval_selected_real_kind (CONST *arg, DTYPE dtype)
static CONST * eval_selected_int_kind (CONST *arg, DTYPE dtype)
static CONST * eval_selected_char_kind (CONST *arg, DTYPE dtype)
static CONST * eval_scan (CONST *arg, DTYPE dtype)
static CONST * eval_verify (CONST *arg, DTYPE dtype)
static CONST * eval_index (CONST *arg, DTYPE dtype)
static CONST * eval_trim (CONST *arg, DTYPE dtype)
static INLINE CONST * eval_adjustl (CONST *arg, DTYPE dtype)
static CONST * eval_adjustr (CONST *arg, DTYPE dtype)
static CONST * eval_shape (CONST *arg, DTYPE dtype)
static CONST * eval_size (CONST *arg, DTYPE dtype)
static CONST * eval_ul_bound (int ul_selector, CONST *arg, DTYPE dtype)
static int copy_initconst_to_array (CONST **arr, CONST *c, int count)
static CONST * eval_reshape (CONST *arg, DTYPE dtype, LOGICAL transpose)
static void transfer_store (INT conval, DTYPE dtype, char *destination)
static INT transfer_load (DTYPE dtype, char *source)
static INLINE CONST * eval_transfer (CONST *arg, DTYPE dtype)
static INLINE CONST * eval_sqrt (CONST *arg, DTYPE dtype)
static INLINE CONST * eval_merge (CONST *arg, DTYPE dtype)
static void mk_cmp (CONST *c, int op, INT l_conval, INT r_conval, DTYPE rdtype, DTYPE dt)
static CONST * eval_init_op (int op, CONST *lop, DTYPE ldtype, CONST *rop, DTYPE rdtype, SPTR sptr, DTYPE dtype)
Variables
static CONST ** init_const
static int cur_init = 0
int init_list_count = 0
static CONST const_err
static int substr_len
static DOSTACK dostack [MAXDEPTH]
static DOSTACK * top
static DOSTACK * bottom
static FILE * df
struct {
CONST * root
CONST * roottail
CONST * arrbase
int ndims
struct {
DTYPE dtype
ISZ_T idx
CONST * subscr_base
ISZ_T lowb
ISZ_T upb
ISZ_T stride
} sub [7]
struct {
ISZ_T lowb
ISZ_T upb
ISZ_T mplyr
} dim [7]
} sb
Detailed Description
SCFTN routine to process data initialization statements; called by semant.
Definition in file dinit.cpp.
Macro Definition Documentation
ABS
#define ABS (x) (((x) > 0) ? (x) : (-(x)))
Definition at line 2356 of file dinit.cpp.
C90_HUGE
#define C90_HUGE "0.136343516952426e+2466" /* 0577757777777777777776 */
CONST_ERR
#define CONST_ERR (dt) (const_err.dtype = dt, clone_init_const(&const_err, true))
Definition at line 65 of file dinit.cpp.
FPINTRIN1
#define FPINTRIN1 (iname, ent, fscutil, dscutil, qscutil)
Definition at line 4919 of file dinit.cpp.
FPINTRIN2
#define FPINTRIN2 (iname, ent, fscutil, dscutil, qscutil)
Definition at line 5043 of file dinit.cpp.
GET_DBLE
#define GET_DBLE (x, y)
Value:
  x[0] = CONVAL1G(y);  \
  x[1] = CONVAL2G(y)
Definition at line 2568 of file dinit.cpp.
GET_QUAD
#define GET_QUAD (x, y)
Value:
  x[0] = CONVAL1G(y);  \
  x[1] = CONVAL2G(y);  \
  x[2] = CONVAL3G(y);  \
  x[3] = CONVAL4G(y);
Definition at line 2571 of file dinit.cpp.
GETVALI64
#define GETVALI64 (x, b)
Value:
  x[0] = CONVAL1G(b);   \
  x[1] = CONVAL2G(b);
Definition at line 2576 of file dinit.cpp.
INTINTRIN2
#define INTINTRIN2 (iname, ent, op)
Definition at line 2435 of file dinit.cpp.
KANJI_BLANK
#define KANJI_BLANK 0xA1A1
MAX_EXP_OF_QMANTISSA
#define MAX_EXP_OF_QMANTISSA 33 /* 2^112 : 5.19e+33 */
Definition at line 80 of file dinit.cpp.
MAX_EXP_QVALUE
#define MAX_EXP_QVALUE 4931 /* max value exponent */
Definition at line 79 of file dinit.cpp.
MAXDEPTH
#define MAXDEPTH 8
Definition at line 70 of file dinit.cpp.
MAXDIMS
#define MAXDIMS 7
Definition at line 69 of file dinit.cpp.
NO_REAL
#define NO_REAL -5 /* if the processor supports no real type with radix RADIX */
Definition at line 85 of file dinit.cpp.
NOT_GET_VAL
#define NOT_GET_VAL 0 /* 0 is default, This should be ruled out */
Definition at line 84 of file dinit.cpp.
RADIX2
#define RADIX2 2 /* Binary */
Definition at line 83 of file dinit.cpp.
REAL_0
#define REAL_0 0
Definition at line 82 of file dinit.cpp.
REAL_16
#define REAL_16 16
Definition at line 81 of file dinit.cpp.
THRESHOLD
#define THRESHOLD 6
Definition at line 78 of file dinit.cpp.
TRACE_EVAL_SB
#define TRACE_EVAL_SB 0
Function Documentation
_ddiv()
static void _ddiv (INT * dividend, INT * divisor, INT * quotient) static
Definition at line 1282 of file dinit.cpp.
References flg, FLG::ieee, xddiv(), xdmul(), and xdrcp().
Referenced by init_fold_const().
_fdiv()
static INT _fdiv (INT dividend, INT divisor) static
Definition at line 1263 of file dinit.cpp.
References flg, FLG::ieee, xfdiv(), xfmul(), and xfrcp().
Referenced by init_fold_const().
_huge()
static int _huge (DTYPE dtype) static
Definition at line 3010 of file dinit.cpp.
References atoxd(), C90_HUGE, DT_DBLE, DTYG, getcon(), strlen(), tmp, TY_BINT, TY_DBLE, TY_INT, TY_INT8, TY_QUAD, TY_REAL, TY_SINT, val, and XBIT.
Referenced by mk_largest_val(), and mk_smallest_val().
acl_idname()
static char * acl_idname (int id) static
Definition at line 989 of file dinit.cpp.
References AC_ACONST, AC_AST, AC_CONST, AC_CONVAL, AC_EXPR, AC_ICONST, AC_IDENT, AC_IDO, AC_IEXPR, AC_LIST, AC_REPEAT, AC_SCONST, AC_TRIPLE, AC_TYPEINIT, AC_VMSSTRUCT, and AC_VMSUNION.
Referenced by dmp_ict().
add_to_list()
static void add_to_list (CONST * val, CONST ** root, CONST ** tail) static
Definition at line 5963 of file dinit.cpp.
References CONST::next, root, roottail, and val.
Referenced by clone_init_const_list(), do_eval_minval_or_maxval(), eval_array_constructor(), eval_do(), eval_index(), eval_init_expr(), eval_init_expr_item(), eval_init_op(), eval_max(), eval_min(), eval_sb(), eval_scan(), and eval_verify().
chk_doindex()
static int chk_doindex (int ilmptr) static
Find the sptr for the implied do index variable The ilm in this context represents the ilms generated to load the index variable and perhaps "type" convert (if it's integer*2, etc.).
Definition at line 247 of file dinit.cpp.
References SEM::dinit_error, errsev(), ILMA, sem, and sptr.
Referenced by dinit_data().
clone_init_const()
static CONST * clone_init_const (CONST * original, int temp) static
Definition at line 5926 of file dinit.cpp.
References AC_IEXPR, clone_init_const_list(), CONST::expr, getitem(), CONST::id, AEXPR::lop, CONST::next, NULL, AEXPR::rop, CONST::subc, and CONST::u1.
Referenced by clone_init_const_list(), copy_initconst_to_array(), eval_init_expr(), eval_init_expr_item(), eval_init_op(), eval_null(), eval_reshape(), eval_sb(), eval_shape(), eval_size(), eval_ul_bound(), and get_minmax_val().
clone_init_const_list()
static CONST * clone_init_const_list (CONST * original, int temp) static
Definition at line 5950 of file dinit.cpp.
References add_to_list(), clone_init_const(), CONST::next, and NULL.
Referenced by clone_init_const(), dinit_varref(), eval_init_expr_item(), eval_merge(), and eval_mod().
cmp_acl()
static bool cmp_acl (DTYPE dtype, CONST * x, CONST * y, bool want_max, bool back) static
Definition at line 2926 of file dinit.cpp.
References cmp(), DTY, ERR_Severe, init_fold_const(), interr(), STB::n_base, OP_CMP, stb, TY_BINT, TY_CHAR, TY_DBLE, TY_INT, TY_INT8, TY_QUAD, TY_REAL, TY_SINT, x, xfcmp(), and y.
Referenced by do_eval_minval_or_maxval().
convert_acl_dtype()
static CONST * convert_acl_dtype (CONST * head, DTYPE oldtype, DTYPE newtype) static
Definition at line 3269 of file dinit.cpp.
References AC_CONST, cngcon(), CONST::conval, DDTG, DTY, dtype, CONST::dtype, CONST::id, CONST::next, TY_CHAR, TY_NCHAR, and CONST::u1.
Referenced by do_eval_minval_or_maxval(), eval_init_expr(), and eval_init_expr_item().
copy_initconst_to_array()
static int copy_initconst_to_array (CONST ** arr, CONST * c, int count) static
Definition at line 4348 of file dinit.cpp.
References AC_ACONST, AC_CONST, acnt, clone_init_const(), copy_initconst_to_array(), count, ERR_Severe, i, interr(), NULL, and CONST::repeatc.
Referenced by copy_initconst_to_array(), and eval_reshape().
df_dinit()
static void df_dinit (VAR * ivl, CONST * ict) static
Parameters
ivl pointer to initializer variable list
ict pointer to initializer constant tree
Definition at line 390 of file dinit.cpp.
References bottom, DBGBIT, dinit_data(), dinit_subs(), dmp_ict(), dmp_ivl(), dostack, eval_init_expr(), gbl, CONST::sptr, SPTR_NULL, substr_len, sym_is_dinitd(), and top.
Referenced by do_dinit().
dinit()
void dinit (VAR * ivl, CONST * ict)
...
Definition at line 104 of file dinit.cpp.
References CNULL, DBGBIT, df, dumpilms(), ERR_Fatal, errfatal(), error(), gbl, ILMB::ilm_base, ILMB::ilmavl, ilmb, NULL, p, and tmpfile().
dinit_data()
static void dinit_data (VAR * ivl, CONST * ict, DTYPE dtype, ISZ_T base_off) static
Initialize a data object.
Parameters
ivl pointer to initializer variable list
ict pointer to initializer constant tree
dtype data type of structure type, if a struct init
Definition at line 278 of file dinit.cpp.
References assert, BOS_SIZE, chk_doindex(), DOSTACK::currval, DBGBIT, DDTG, SEM::dinit_error, dinit_varref(), dmpilms(), Doend, VAR::doend, dostack, Dostart, VAR::dostart, DTyAlgTyMember, ERR_Severe, errsev(), eval(), gbl, VAR::id, ILMB::ilm_base, ILMB::ilmavl, ilmb, VAR::indvar, is_empty_typedef(), ISZ_T, VAR::lowbd, MAXDEPTH, VAR::next, NOSYM, NULL, p, sem, size_of(), DOSTACK::sptr, SPTR_NULL, DOSTACK::step, VAR::step, top, VAR::u, DOSTACK::upbd, VAR::upbd, and Varref.
Referenced by df_dinit(), and dinit_varref().
dinit_ok()
bool dinit_ok (int sptr)
determine if the symbol can be legally data initialized
...
Definition at line 1219 of file dinit.cpp.
References CNULL, SEM::dinit_error, ERR_Severe, error(), gbl, sem, sptr, and SYMNAME.
Referenced by dinit_varref(), and mkeffadr().
dinit_subs()
static void dinit_subs (CONST * ict, SPTR base, ISZ_T boffset, SPTR mbr_sptr) static
FIXME.
Parameters
ict pointer to initializer constant tree
base sym pointer to base address
boffset current offset from base
mbr_sptr sptr of member if processing typedef
Definition at line 704 of file dinit.cpp.
References AC_ACONST, AC_SCONST, AD_DPTR, AD_NUMELM, AD_PTR, ad_val_of(), base, CONST::conval, DDTG, DINIT_LOC, DINIT_OFFSET, dinit_put(), DINIT_REPEAT, dinit_subs(), dinit_val(), DTY, DTyAlgTyMember, DTyAlgTySize, dtype, CONST::dtype, ERR_Severe, i, CONST::id, interr(), ISZ_T, CONST::next, NOSYM, CONST::repeatc, size_of(), sptr, CONST::sptr, SPTR_NULL, CONST::subc, and CONST::u1.
Referenced by df_dinit(), and dinit_subs().
dinit_val()
static void dinit_val (SPTR sptr, DTYPE dtypev, INT val) static
Definition at line 848 of file dinit.cpp.
References assert, aux, buf, cngcon(), CNULL, DDTG, DINIT_PROC, dinit_put(), DT_INT, DT_ISINT, DT_ISLOG, DTY, DTyCharLength, DTYG, dtype, AUX::dvl_avl, AUX::dvl_base, DVL_CONVAL, AUX::dvl_size, DVL_SPTR, ERR_Severe, ERR_Warning, error(), flg, gbl, get_type(), getstring(), NEED, no_data_components(), FLG::opt, sptr, FLG::standard, substr_len, SYMNAME, TY_CHAR, TY_HOLL, TY_NCHAR, and val.
Referenced by dinit_subs(), and dinit_varref().
dinit_varref()
static CONST * dinit_varref (VAR * ivl, SPTR member, CONST * ict, DTYPE dtype, int * struct_bytes_initd, ISZ_T * repeat, ISZ_T base_off) static
Definition at line 490 of file dinit.cpp.
References AC_ACONST, AD_NUMELM, AD_PTR, ad_val_of(), assert, clone_init_const_list(), CONST::conval, DDTG, dinit_data(), SEM::dinit_error, DINIT_LOC, DINIT_OFFSET, dinit_ok(), dinit_put(), DINIT_REPEAT, dinit_val(), dinit_varref(), DINIT_ZEROES, DTY, VAR::dtype, CONST::dtype, ERR_Severe, ERR_Warning, errsev(), extent_of(), i, VAR::id, CONST::id, CONST::ido, ILMA, IDOINFO::index_var, interr(), is_zero(), is_zero_size_typedef(), ISZ_T, EFFADR::mem, mkeffadr(), CONST::next, no_data_components(), NULL, offset, EFFADR::offset, VAR::ptr, CONST::repeatc, S_IDENT, save_init(), sem, VAR::shape, size_of(), sptr, EFFADR::sptr, CONST::subc, sym_is_dinitd(), THRESHOLD, VAR::u, CONST::u1, uf, VAR::varref, void(), and zero.
Referenced by dinit_data(), and dinit_varref().
dmp_ict()
void dmp_ict (CONST * ict, FILE * f)
...
Definition at line 947 of file dinit.cpp.
References acl_idname(), dmp_ict(), DTyAlgTyTag, f, FILE, ISZ_PF, and SYMNAME.
Referenced by df_dinit(), and dmp_ict().
dmp_ivl()
void dmp_ivl (VAR * ivl, FILE * f)
...
Dump an initializer variable list to a file (or stderr if no file provided).
...
Definition at line 913 of file dinit.cpp.
References assert, Doend, VAR::doend, Dostart, VAR::dostart, ERR_Severe, f, FILE, VAR::id, ILMA, VAR::next, VAR::ptr, S_IDENT, VAR::shape, SYMNAME, VAR::u, Varref, and VAR::varref.
Referenced by df_dinit().
do_dinit()
void do_dinit (void)
Read in the information a "record" (1 word, 2 pointers) at a time saved by dinit(), and write dinit records for each record.
...
Definition at line 168 of file dinit.cpp.
References assert, BOS_SIZE, BZERO, DBGBIT, df, df_dinit(), ERR_Fatal, ERR_Severe, fclose(), freearea(), gbl, getitem(), ILMB::ilm_base, ILMB::ilmavl, ilmb, init_const, init_list_count, CONST::no_dinitp, NULL, and CONST::sptr.
do_eval_minval_or_maxval()
static CONST * do_eval_minval_or_maxval (INDEX * index, DTYPE elem_dt, DTYPE loc_dt, CONST * elems, unsigned dim, CONST * mask, bool back, int intrin) static
Definition at line 3297 of file dinit.cpp.
References AC_ACONST, AC_CONST, AC_I_maxloc, AC_I_maxval, AC_I_minval, add_to_list(), BCOPY, BZERO, cmp_acl(), CONST::conval, convert_acl_dtype(), dim, CONST::dtype, eval_init_expr_item(), get_minmax_val(), get_offset_without_dim(), getitem(), i, CONST::id, incr_index(), index, ndims, NEW, CONST::next, NULL, offset, CONST::repeatc, result, roottail, CONST::u1, and val.
Referenced by eval_minval_or_maxval().
eval()
static ISZ_T eval (int ilmptr) static
Definition at line 1145 of file dinit.cpp.
References bottom, CNULL, CONVAL2G, SEM::dinit_error, ERR_Severe, error(), errsev(), eval(), gbl, get_isz_cval(), ILMA, p, sem, SYMNAME, and top.
Referenced by dinit_data(), eval(), and mkeffadr().
eval_abs()
static CONST * eval_abs (CONST * arg, DTYPE dtype) static
Definition at line 2581 of file dinit.cpp.
References AC_ACONST, arg, cmp64(), cngcon(), CONST::conval, CONVAL2G, DT_DBLE, DT_REAL, DTY, dtype, CONST::dtype, eval_init_expr_item(), GET_DBLE, GET_QUAD, getcon(), GETVALI64, CONST::id, STB::k0, neg64(), CONST::next, res, stb, CONST::subc, TY_BINT, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_QUAD, TY_REAL, TY_SINT, CONST::u1, xdabsv(), xfabsv(), xfadd(), xfmul(), xfsqrt(), and xqabsv().
Referenced by eval_init_op().
eval_adjustl()
static INLINE CONST * eval_adjustl (CONST * arg, DTYPE dtype) static
Definition at line 4207 of file dinit.cpp.
References AC_ACONST, AC_CONST, arg, assert, CONST::conval, cp, CONST::dtype, ERR_Fatal, eval_init_expr(), getitem(), getstring(), i, CONST::id, STB::n_base, CONST::next, p, size_of(), stb, str, CONST::subc, and CONST::u1.
Referenced by eval_init_op().
eval_adjustr()
static CONST * eval_adjustr (CONST * arg, DTYPE dtype) static
Definition at line 4245 of file dinit.cpp.
References AC_ACONST, AC_CONST, arg, assert, CONST::conval, cp, CONST::dtype, ERR_Fatal, eval_init_expr(), getitem(), getstring(), i, CONST::id, STB::n_base, CONST::next, p, size_of(), stb, str, CONST::subc, and CONST::u1.
Referenced by eval_init_op().
eval_array_constructor()
static CONST * eval_array_constructor (CONST * e) static
Definition at line 5704 of file dinit.cpp.
References AC_ACONST, add_to_list(), e, eval_array_constructor(), eval_init_expr_item(), CONST::id, CONST::next, NULL, root, and roottail.
Referenced by eval_array_constructor(), eval_const_array_section(), eval_init_expr(), and eval_init_expr_item().
eval_ceiling()
static INLINE CONST * eval_ceiling (CONST * arg, DTYPE dtype) static
Definition at line 3649 of file dinit.cpp.
References AC_ACONST, AC_CONST, arg, cngcon(), CONST::conval, CONVAL2G, STB::dbl0, DT_DBLE, DT_ISWORD, DT_REAL, DTY, dtype, CONST::dtype, eval_init_expr_item(), STB::flt0, getcon(), CONST::id, init_fold_const(), CONST::next, OP_ADD, OP_CMP, STB::quad0, CONST::repeatc, stb, CONST::subc, TY_DBLE, TY_QUAD, TY_REAL, CONST::u1, and xfcmp().
Referenced by eval_init_op().
eval_char()
static CONST * eval_char (CONST * arg, DTYPE dtype) static
Definition at line 2502 of file dinit.cpp.
References AC_ACONST, arg, cngcon(), CONST::conval, DDTG, DT_ISWORD, dtype, CONST::dtype, eval_init_expr_item(), CONST::id, CONST::next, CONST::subc, and CONST::u1.
Referenced by eval_init_op().
eval_const_array_section()
static CONST * eval_const_array_section (CONST * lop, DTYPE ldtype, DTYPE dtype) static
Definition at line 2324 of file dinit.cpp.
References AC_ACONST, AD_DPTR, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_UPBD, ad_val_of(), CONST_ERR, ERR_Severe, eval_array_constructor(), eval_sb(), i, CONST::id, interr(), ndims, NULL, and sb.
Referenced by eval_init_op().
eval_const_array_triple_section()
static CONST * eval_const_array_triple_section (CONST * curr_e) static
Definition at line 2245 of file dinit.cpp.
References AC_ACONST, AC_CONST, c, CONST_ERR, CONST::conval, dtype, CONST::dtype, ERR_Severe, eval_init_expr(), get_ival(), CONST::id, interr(), ndims, CONST::next, NULL, sb, t, and CONST::u1.
Referenced by eval_init_expr_item().
eval_do()
static CONST * eval_do (CONST * ido) static
Definition at line 5852 of file dinit.cpp.
References AC_CONST, add_to_list(), BZERO, CONST::conval, DTY, CONST::dtype, eval_init_expr(), eval_init_expr_item(), get_ival(), getcon(), getitem(), i, CONST::id, CONST::ido, IDOINFO::index_var, init_const, IDOINFO::initval, ISZ_2_INT64, ISZ_T, IDOINFO::limitval, NULL, num, PARAMVALG, CONST::repeatc, root, roottail, save_init(), IDOINFO::stepval, CONST::subc, TY_INT8, TY_LOG8, and CONST::u1.
Referenced by eval_init_expr_item().
eval_floor()
static INLINE CONST * eval_floor (CONST * arg, DTYPE dtype) static
Definition at line 3585 of file dinit.cpp.
References AC_ACONST, AC_CONST, arg, cngcon(), CONST::conval, CONVAL2G, STB::dbl0, DT_DBLE, DT_ISWORD, DT_REAL, DTY, dtype, CONST::dtype, eval_init_expr_item(), STB::flt0, getcon(), CONST::id, init_fold_const(), CONST::next, OP_CMP, OP_SUB, STB::quad0, CONST::repeatc, stb, CONST::subc, TY_DBLE, TY_QUAD, TY_REAL, CONST::u1, and xfcmp().
Referenced by eval_init_op().
eval_fltconvert()
static CONST * eval_fltconvert (CONST * arg, DTYPE dtype) static
Definition at line 2551 of file dinit.cpp.
References AC_ACONST, AC_CONST, arg, cngcon(), CONST::conval, DDTG, CONST::dtype, eval_init_expr_item(), CONST::id, CONST::next, CONST::repeatc, result, CONST::subc, and CONST::u1.
Referenced by eval_init_op().
eval_ichar()
static CONST * eval_ichar (CONST * arg, DTYPE dtype) static
Definition at line 2473 of file dinit.cpp.
References AC_ACONST, arg, c, cngcon(), CONST::conval, DDTG, DTY, dtype, CONST::dtype, eval_init_expr(), CONST::id, kanji_char(), STB::n_base, CONST::next, size_of(), stb, CONST::subc, TY_NCHAR, and CONST::u1.
Referenced by eval_init_op().
eval_index()
static CONST * eval_index (CONST * arg, DTYPE dtype) static
Definition at line 4108 of file dinit.cpp.
References AC_ACONST, AC_CONST, add_to_list(), arg, assert, BZERO, c, CONST::conval, DT_INT, CONST::dtype, ERR_Fatal, eval_init_expr_item(), get_ival(), getitem(), i, CONST::id, ISZ_T, n, STB::n_base, CONST::next, NULL, size_of(), stb, and CONST::u1.
Referenced by eval_init_op().
eval_init_expr()
static CONST * eval_init_expr (CONST * e) static
Definition at line 5808 of file dinit.cpp.
References AC_ACONST, AC_IDENT, AC_SCONST, add_to_list(), clone_init_const(), convert_acl_dtype(), DDTG, DTY, CONST::dtype, e, eval_array_constructor(), eval_init_expr(), eval_init_expr_item(), FLANG_FALLTHROUGH, CONST::id, CONST::next, NULL, root, roottail, CONST::sptr, SPTR_NULL, and CONST::subc.
Referenced by df_dinit(), eval_adjustl(), eval_adjustr(), eval_const_array_triple_section(), eval_do(), eval_ichar(), eval_init_expr(), eval_init_expr_item(), eval_init_op(), eval_max(), eval_min(), eval_scale(), eval_selected_char_kind(), eval_transfer(), and eval_trim().
eval_init_expr_item()
static CONST * eval_init_expr_item (CONST * cur_e) static
Definition at line 5727 of file dinit.cpp.
References AC_ACONST, AC_ARRAYREF, AC_CONST, AC_IDENT, AC_IDO, AC_IEXPR, AC_INTR_CALL, AC_SCONST, AC_TRIPLE, add_to_list(), clone_init_const(), clone_init_const_list(), CONST::conval, convert_acl_dtype(), DDTG, DINIT_PROC, CONST::dtype, eval_array_constructor(), eval_const_array_triple_section(), eval_do(), eval_init_expr(), eval_init_op(), CONST::expr, CONST::id, init_const, AEXPR::lop, CONST::mbr, NULL, AEXPR::op, PARAMVALG, CONST::repeatc, AEXPR::rop, CONST::sptr, CONST::subc, and CONST::u1.
Referenced by do_eval_minval_or_maxval(), eval_abs(), eval_array_constructor(), eval_ceiling(), eval_char(), eval_do(), eval_floor(), eval_fltconvert(), eval_index(), eval_init_expr(), eval_int(), eval_ishft(), eval_len_trim(), eval_merge(), eval_minval_or_maxval(), eval_mod(), eval_nint(), eval_repeat(), eval_reshape(), eval_sb(), eval_scan(), eval_selected_int_kind(), eval_selected_real_kind(), eval_size(), eval_sqrt(), eval_ul_bound(), eval_verify(), and get_minmax_val().
eval_init_op()
static CONST * eval_init_op (int op, CONST * lop, DTYPE ldtype, CONST * rop, DTYPE rdtype, SPTR sptr, DTYPE dtype) static
Definition at line 5185 of file dinit.cpp.
References AC_ACONST, AC_ARRAYREF, AC_CAT, AC_CONST, AC_CONV, AC_I_abs, AC_I_acos, AC_I_adjustl, AC_I_adjustr, AC_I_asin, AC_I_atan, AC_I_atan2, AC_I_ceiling, AC_I_char, AC_I_cos, AC_I_exp, AC_I_floor, AC_I_fltconvert, AC_I_iand, AC_I_ichar, AC_I_ieor, AC_I_index, AC_I_int, AC_I_ior, AC_I_ishft, AC_I_lbound, AC_I_len_trim, AC_I_log, AC_I_log10, AC_I_max, AC_I_maxloc, AC_I_maxval, AC_I_merge, AC_I_min, AC_I_minloc, AC_I_minval, AC_I_mod, AC_I_nint, AC_I_null, AC_I_repeat, AC_I_reshape, AC_I_scale, AC_I_scan, AC_I_selected_char_kind, AC_I_selected_int_kind, AC_I_selected_real_kind, AC_I_shape, AC_I_sin, AC_I_size, AC_I_sqrt, AC_I_tan, AC_I_transfer, AC_I_transpose, AC_I_trim, AC_I_ubound, AC_I_verify, AC_INTR_CALL, AC_LNOT, AC_MEMBR_SEL, AC_NEG, add_to_list(), BCOPY, BZERO, c, clone_init_const(), cngcon(), CONST_ERR, CONST::conval, DDTG, dt, DT_LOG, DTY, CONST::dtype, ERR_Severe, eval_abs(), eval_adjustl(), eval_adjustr(), eval_ceiling(), eval_char(), eval_const_array_section(), eval_floor(), eval_fltconvert(), eval_ichar(), eval_index(), eval_init_expr(), eval_int(), eval_ishft(), eval_len_trim(), eval_max(), eval_merge(), eval_min(), eval_minval_or_maxval(), eval_mod(), eval_nint(), eval_null(), eval_repeat(), eval_reshape(), eval_scale(), eval_scan(), eval_selected_char_kind(), eval_selected_int_kind(), eval_selected_real_kind(), eval_shape(), eval_size(), eval_sqrt(), eval_transfer(), eval_trim(), eval_ul_bound(), eval_verify(), FALSE, get_ast_op(), get_type(), getitem(), getstring(), i, CONST::id, init_fold_const(), init_negate_const(), interr(), ISZ_T, mk_cmp(), STB::n_base, CONST::next, NULL, OP_CAT, OP_CMP, OP_EQ, OP_GE, OP_GT, OP_LAND, OP_LE, OP_LEQV, OP_LNEQV, OP_LOR, OP_LT, OP_NE, OP_XTOI, OP_XTOK, OP_XTOX, CONST::repeatc, root, roottail, s, SCFTN_FALSE, SCFTN_TRUE, size_of(), stb, CONST::subc, TRUE, TY_CHAR, and CONST::u1.
Referenced by eval_init_expr_item().
eval_int()
static INLINE CONST * eval_int (CONST * arg, DTYPE dtype) static
Definition at line 2521 of file dinit.cpp.
References AC_ACONST, AC_CONST, arg, cngcon(), CONST::conval, DDTG, CONST::dtype, eval_init_expr_item(), CONST::id, CONST::next, CONST::repeatc, result, CONST::subc, and CONST::u1.
Referenced by eval_init_op().
eval_ishft()
static INLINE CONST * eval_ishft (CONST * arg, DTYPE dtype) static
Evaluate compile-time constant produced by ISFHT intrinsic.
ISHFT(I, SHIFT) shifts value in I by SHIFT bits to the left (if SHIFT is negative, it shifts by -SHIFT to the right).
For 64-bit values we need to extract the arguments from the symbol table and write the result back to it.
Parameters
arg initilization expression
dtype expected result type
Definition at line 2369 of file dinit.cpp.
References ABS, AC_ACONST, arg, CONST_ERR, CONST::conval, CONVAL2G, CONST::dtype, ERR_Severe, error(), eval_init_expr_item(), gbl, getcon(), CONST::id, INT64_2_ISZ, ISZ_2_INT64, ISZ_T, CONST::next, NULL, size_of(), CONST::subc, CONST::u1, and val.
Referenced by eval_init_op().
eval_len_trim()
static CONST * eval_len_trim (CONST * arg, DTYPE dtype) static
Definition at line 3843 of file dinit.cpp.
References AC_ACONST, AC_CONST, arg, CONST::conval, DT_INT, CONST::dtype, eval_init_expr_item(), CONST::id, STB::n_base, CONST::next, p, CONST::repeatc, result, size_of(), stb, CONST::subc, and CONST::u1.
Referenced by eval_init_op().
eval_max()
static CONST * eval_max (CONST * arg, DTYPE dtype) static
Definition at line 2791 of file dinit.cpp.
References AC_ACONST, AC_CONST, AD_DPTR, AD_NUMELM, ad_val_of(), add_to_list(), arg, BZERO, c, CONST::conval, DTY, CONST::dtype, eval_init_expr(), FREE, getitem(), i, CONST::id, init_fold_const(), j, STB::n_base, nargs, NEW, CONST::next, NULL, num, OP_CMP, CONST::repeatc, root, roottail, stb, CONST::subc, TY_CHAR, TY_DBLE, TY_INT, TY_INT8, TY_QUAD, TY_REAL, CONST::u1, and xfcmp().
Referenced by eval_init_op().
eval_merge()
static INLINE CONST * eval_merge (CONST * arg, DTYPE dtype) static
Definition at line 5096 of file dinit.cpp.
References AC_ACONST, arg, clone_init_const_list(), CONST::conval, CONVAL2G, DT_ISWORD, dtype, CONST::dtype, eval_init_expr_item(), CONST::id, CONST::next, r, result, CONST::subc, and CONST::u1.
Referenced by eval_init_op().
eval_min()
static CONST * eval_min (CONST * arg, DTYPE dtype) static
Definition at line 2657 of file dinit.cpp.
References AC_ACONST, AC_CONST, AD_DPTR, AD_NUMELM, ad_val_of(), add_to_list(), arg, BZERO, c, CONST::conval, DTY, CONST::dtype, eval_init_expr(), FREE, getitem(), i, CONST::id, init_fold_const(), j, STB::n_base, nargs, NEW, CONST::next, NULL, num, OP_CMP, CONST::repeatc, root, roottail, stb, CONST::subc, TY_CHAR, TY_DBLE, TY_INT, TY_INT8, TY_QUAD, TY_REAL, CONST::u1, and xfcmp().
Referenced by eval_init_op().
eval_minval_or_maxval()
static CONST * eval_minval_or_maxval (CONST * arg, DTYPE dtype, int intrin) static
Definition at line 3475 of file dinit.cpp.
References AC_ACONST, AC_CONST, AD_DPTR, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_UPBD, ad_val_of(), arg, array_element_dtype(), BZERO, CONST::conval, dim, do_eval_minval_or_maxval(), DT_INT, DT_ISINT, DT_ISLOG, DT_LOG, CONST::dtype, eval_init_expr_item(), extent(), FALSE, getitem(), i, CONST::id, index, NULL, sb, CONST::subc, and CONST::u1.
Referenced by eval_init_op().
eval_mod()
static CONST * eval_mod (CONST * arg, DTYPE dtype) static
Definition at line 3713 of file dinit.cpp.
References AC_ACONST, AC_CONST, arg, clone_init_const_list(), cngcon(), CONST::conval, CONVAL2G, DT_DBLE, DT_REAL, DTY, dtype, CONST::dtype, ERR_Severe, error(), eval_init_expr_item(), gbl, getcon(), CONST::id, CONST::next, CONST::repeatc, CONST::subc, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_QUAD, TY_REAL, CONST::u1, xddiv(), xdmul(), xdsub(), xfdiv(), xfmul(), xfsub(), xqdiv(), xqmul(), and xqsub().
Referenced by eval_init_op().
eval_nint()
static CONST * eval_nint (CONST * arg, DTYPE dtype) static
Definition at line 3533 of file dinit.cpp.
References AC_ACONST, AC_CONST, arg, cngcon(), CONST::conval, CONVAL2G, STB::dbl0, STB::dblhalf, DT_DBLE, DT_INT, DT_REAL, DTY, CONST::dtype, eval_init_expr_item(), STB::flt0, STB::flthalf, CONST::id, init_fold_const(), CONST::next, OP_ADD, OP_CMP, OP_SUB, STB::quad0, STB::quadhalf, CONST::repeatc, res, stb, CONST::subc, TY_DBLE, TY_QUAD, TY_REAL, CONST::u1, xfadd(), xfcmp(), and xfsub().
Referenced by eval_init_op().
eval_null()
static CONST * eval_null (CONST * arg, DTYPE dtype) static
Definition at line 2539 of file dinit.cpp.
References AC_CONST, clone_init_const(), DDTG, NULL, p, and SPTR_NULL.
Referenced by eval_init_op().
eval_repeat()
static CONST * eval_repeat (CONST * arg, DTYPE dtype) static
Definition at line 3809 of file dinit.cpp.
References AC_CONST, arg, BZERO, CONST::conval, cp, dtype, CONST::dtype, eval_init_expr_item(), getitem(), getstring(), i, CONST::id, j, STB::n_base, NULL, p, CONST::repeatc, result, size_of(), stb, str, and CONST::u1.
Referenced by eval_init_op().
eval_reshape()
static CONST * eval_reshape (CONST * arg, DTYPE dtype, LOGICAL transpose) static
Definition at line 4385 of file dinit.cpp.
References AC_ACONST, AC_CONST, AC_CONVAL, AD_DPTR, AD_NUMDIM, AD_NUMELM, AD_UPBD, ad_val_of(), arg, BZERO, clone_init_const(), CONST_ERR, copy_initconst_to_array(), count, DT_ISWORD, end, eval_init_expr_item(), FREE, i, CONST::id, idx, index, j, lwb, NEW, next, CONST::next, NULL, order, rank, CONST::repeatc, start, CONST::subc, sz, upb, and void().
Referenced by eval_init_op().
eval_sb()
static int eval_sb (int d) static
Definition at line 2153 of file dinit.cpp.
References add_to_list(), c, clone_init_const(), d, ERR_Severe, eval_init_expr_item(), eval_sb(), eval_sub_index(), i, interr(), ISZ_T, CONST::next, NULL, CONST::repeatc, sb, tmp, and TRACE_EVAL_SB.
Referenced by eval_const_array_section(), and eval_sb().
eval_scale()
static CONST * eval_scale (CONST * arg, int type) static
Definition at line 3386 of file dinit.cpp.
References AC_CONST, arg, BZERO, CONST::conval, CONVAL2G, DT_DBLE, CONST::dtype, e, ERR_Warning, error(), eval_init_expr(), gbl, getcon(), getitem(), i, CONST::id, CONST::repeatc, size_of(), SYMNAME, CONST::u1, xdmul(), xfmul(), and xqmul().
Referenced by eval_init_op().
eval_scan()
static CONST * eval_scan (CONST * arg, DTYPE dtype) static
Definition at line 3985 of file dinit.cpp.
References AC_ACONST, AC_CONST, add_to_list(), arg, assert, BZERO, c, CONST::conval, DT_INT, CONST::dtype, ERR_Fatal, eval_init_expr_item(), get_ival(), getitem(), i, CONST::id, ISZ_T, j, STB::n_base, CONST::next, NULL, size_of(), stb, and CONST::u1.
Referenced by eval_init_op().
eval_selected_char_kind()
static CONST * eval_selected_char_kind (CONST * arg, DTYPE dtype) static
Definition at line 3962 of file dinit.cpp.
References AC_CONST, arg, BZERO, CONST::conval, DT_INT, CONST::dtype, eval_init_expr(), getitem(), CONST::id, r, CONST::repeatc, sem_eq_str(), and CONST::u1.
Referenced by eval_init_op().
eval_selected_int_kind()
static CONST * eval_selected_int_kind (CONST * arg, DTYPE dtype) static
Definition at line 3937 of file dinit.cpp.
References arg, CONST::conval, eval_init_expr_item(), r, CONST::u1, and XBIT.
Referenced by eval_init_op().
eval_selected_real_kind()
static CONST * eval_selected_real_kind (CONST * arg, DTYPE dtype) static
Definition at line 3871 of file dinit.cpp.
References AC_CONST, arg, BZERO, CONST::conval, DT_INT, CONST::dtype, eval_init_expr_item(), getitem(), CONST::id, MAX_EXP_OF_QMANTISSA, MAX_EXP_QVALUE, NO_REAL, NOT_GET_VAL, r, RADIX2, REAL_0, REAL_16, CONST::repeatc, CONST::sptr, and CONST::u1.
Referenced by eval_init_op().
eval_shape()
static CONST * eval_shape (CONST * arg, DTYPE dtype) static
Definition at line 4284 of file dinit.cpp.
References arg, and clone_init_const().
Referenced by eval_init_op().
eval_size()
static CONST * eval_size (CONST * arg, DTYPE dtype) static
Definition at line 4293 of file dinit.cpp.
References arg, clone_init_const(), CONST::conval, dim, eval_init_expr_item(), i, CONST::next, CONST::subc, and CONST::u1.
Referenced by eval_init_op().
eval_sqrt()
static INLINE CONST * eval_sqrt (CONST * arg, DTYPE dtype) static
Definition at line 4792 of file dinit.cpp.
References AC_ACONST, AC_CONST, arg, cngcon(), CONST::conval, CONVAL2G, DT_DBLE, DTY, dtype, CONST::dtype, ERR_Severe, error(), eval_init_expr_item(), gbl, getcon(), CONST::id, CONST::next, CONST::repeatc, res, CONST::subc, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_QUAD, TY_REAL, CONST::u1, xdsqrt(), xfsqrt(), and xqsqrt().
Referenced by eval_init_op().
eval_sub_index()
static ISZ_T eval_sub_index (int dim) static
Definition at line 2127 of file dinit.cpp.
References AD_DPTR, AD_LWBD, ad_val_of(), CONST::conval, dim, CONST::dtype, get_ival(), ISZ_T, CONST::next, CONST::repeatc, sb, subscr_base, and CONST::u1.
Referenced by eval_sb().
eval_transfer()
static INLINE CONST * eval_transfer (CONST * arg, DTYPE dtype) static
Definition at line 4689 of file dinit.cpp.
References AC_ACONST, AC_CONST, AD_DPTR, AD_NUMELM, ad_val_of(), arg, assert, avail, BZERO, CONST_ERR, CONST::conval, current, DDTG, DTY, dtype, CONST::dtype, ERR_Severe, eval_init_expr(), FREE, getitem(), i, CONST::id, ISZ_T, j, nelem, NEW, CONST::next, NULL, CONST::repeatc, root, size_of(), src, CONST::subc, transfer_load(), transfer_store(), TY_CHAR, CONST::u1, and value().
Referenced by eval_init_op().
eval_trim()
static CONST * eval_trim (CONST * arg, DTYPE dtype) static
Definition at line 4169 of file dinit.cpp.
References arg, CONST::conval, cp, DTY, CONST::dtype, eval_init_expr(), get_type(), getitem(), getstring(), i, STB::n_base, p, size_of(), stb, str, strlen(), and CONST::u1.
Referenced by eval_init_op().
eval_ul_bound()
static CONST * eval_ul_bound (int ul_selector, CONST * arg, DTYPE dtype) static
Definition at line 4318 of file dinit.cpp.
References AD_DPTR, AD_UPBD, arg, clone_init_const(), CNULL, CONST_ERR, CONST::conval, CONST::dtype, ERR_Severe, error(), eval_init_expr_item(), gbl, i, CONST::next, rank, CONST::subc, and CONST::u1.
Referenced by eval_init_op().
eval_verify()
static CONST * eval_verify (CONST * arg, DTYPE dtype) static
Definition at line 4044 of file dinit.cpp.
References AC_ACONST, AC_CONST, add_to_list(), arg, assert, BZERO, c, CONST::conval, DT_INT, CONST::dtype, ERR_Fatal, eval_init_expr_item(), get_ival(), getitem(), i, CONST::id, ISZ_T, j, STB::n_base, CONST::next, NULL, size_of(), stb, and CONST::u1.
Referenced by eval_init_op().
get_ast_op()
static int get_ast_op (int op) static
Definition at line 1299 of file dinit.cpp.
References AC_ADD, AC_CAT, AC_DIV, AC_EQ, AC_EXP, AC_EXPK, AC_EXPX, AC_GE, AC_GT, AC_LAND, AC_LE, AC_LEQV, AC_LNEQV, AC_LNOT, AC_LOR, AC_LT, AC_MUL, AC_NE, AC_NEG, AC_SUB, ERR_Severe, interr(), OP_ADD, OP_CAT, OP_DIV, OP_EQ, OP_GE, OP_GT, OP_LAND, OP_LE, OP_LEQV, OP_LNEQV, OP_LNOT, OP_LOR, OP_LT, OP_MUL, OP_NE, OP_NEG, OP_SUB, OP_XTOI, OP_XTOK, and OP_XTOX.
Referenced by eval_init_op(), and mk_cmp().
get_ival()
static ISZ_T get_ival (DTYPE dtype, INT conval) static
Definition at line 1201 of file dinit.cpp.
References DTY, get_isz_cval(), TY_INT8, and TY_LOG8.
Referenced by eval_const_array_triple_section(), eval_do(), eval_index(), eval_scan(), eval_sub_index(), and eval_verify().
get_minmax_val()
static CONST * get_minmax_val (DTYPE dtype, bool want_max) static
Definition at line 3255 of file dinit.cpp.
References AC_CONST, BZERO, clone_init_const(), CONST::conval, dtype, CONST::dtype, eval_init_expr_item(), getitem(), CONST::id, mk_largest_val(), mk_smallest_val(), CONST::next, CONST::repeatc, and CONST::u1.
Referenced by do_eval_minval_or_maxval().
get_offset_without_dim()
static unsigned get_offset_without_dim (INDEX * index, unsigned dim) static
Definition at line 2992 of file dinit.cpp.
References d, dim, index, and result.
Referenced by do_eval_minval_or_maxval().
incr_index()
static bool incr_index (INDEX * index) static
Definition at line 2978 of file dinit.cpp.
References d, and index.
Referenced by do_eval_minval_or_maxval().
init_fold_const()
static INT init_fold_const (int opr, INT conval1, INT conval2, DTYPE dtype) static
Definition at line 1372 of file dinit.cpp.
References _ddiv(), _fdiv(), add64(), cmp64(), cngcon(), cnt, CONVAL2G, STB::dbl0, STB::dbl1, div64(), DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_INT, DTY, DTyCharLength, ERR_Severe, errsev(), STB::flt0, STB::flt1, get_isz_cval(), getcon(), init_fold_const(), interr(), ISZ_T, STB::k1, KANJI_BLANK, kanji_char(), mul64(), STB::n_base, OP_ADD, OP_CMP, OP_DIV, OP_MUL, OP_SUB, OP_XTOI, OP_XTOK, OP_XTOX, p, q, STB::quad0, STB::quad1, result, sign, stb, sub64(), term(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, val, xcdpow(), xcfpow(), xcqpow(), xdadd(), xdcmp(), xdmul(), xdpow(), xdsub(), xfadd(), xfcmp(), xfmul(), xfpow(), xfsub(), xqadd(), xqcmp(), xqdiv(), xqmul(), xqpow(), and xqsub().
Referenced by cmp_acl(), eval_ceiling(), eval_floor(), eval_init_op(), eval_max(), eval_min(), eval_nint(), init_fold_const(), init_negate_const(), mk_cmp(), and negate_const_be().
init_negate_const()
static INT init_negate_const (INT conval, DTYPE dtype) static
Definition at line 2025 of file dinit.cpp.
References CONVAL2G, DT_CMPLX, DT_DBLE, DT_DCMPLX, DTY, ERR_Severe, getcon(), init_fold_const(), interr(), STB::k0, num, OP_SUB, result, stb, TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, xdneg(), xfneg(), and xqneg().
Referenced by eval_init_op().
is_zero()
static bool is_zero (DTYPE dtype, INT conval) static
Return true if the constant of the given dtype represents zero.
Definition at line 441 of file dinit.cpp.
References CONVAL2G, STB::dbl0, DTY, STB::quad0, stb, TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_SINT, TY_SLOG, and XBIT.
Referenced by collapse_assignment(), and dinit_varref().
mk_cmp()
static void mk_cmp (CONST * c, int op, INT l_conval, INT r_conval, DTYPE rdtype, DTYPE dt) static
Definition at line 5126 of file dinit.cpp.
References dt, get_ast_op(), init_fold_const(), OP_CMP, OP_EQ, OP_GE, OP_GT, OP_LAND, OP_LE, OP_LEQV, OP_LNEQV, OP_LOR, OP_LT, OP_NE, OP_XTOI, OP_XTOK, SCFTN_FALSE, and SCFTN_TRUE.
Referenced by eval_init_op().
mk_largest_val()
int mk_largest_val (DTYPE dtype)
...
Definition at line 3248 of file dinit.cpp.
References _huge().
Referenced by get_minmax_val().
mk_smallest_val()
int mk_smallest_val (DTYPE dtype)
...
Definition at line 3196 of file dinit.cpp.
References _huge(), DTYG, getcon(), mk_unop(), OP_SUB, tmp, TY_BINT, TY_DBLE, TY_INT, TY_INT8, TY_QUAD, TY_REAL, TY_SINT, val, and XBIT.
Referenced by get_minmax_val().
mk_unop()
int mk_unop (int optype, int lop, DTYPE dtype)
...
Definition at line 3157 of file dinit.cpp.
References DTY, ERR_Severe, interr(), negate_const_be(), OP_ADD, OP_SUB, optype(), TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, and TY_SLOG.
Referenced by mk_smallest_val().
mkeffadr()
static EFFADR * mkeffadr (int ilmptr) static
derefence an ilm pointer to determine the effective address of a reference (i.e. base sptr + byte offset).
Definition at line 1054 of file dinit.cpp.
References AD_LWBD, AD_MLPYR, AD_PTR, AD_UPBD, ad_val_of(), buf, CNULL, DDTG, SEM::dinit_error, dinit_ok(), ERR_Severe, error(), eval(), gbl, i, ILMA, ISZ_T, EFFADR::mem, mkeffadr(), offset, EFFADR::offset, sem, size_of(), EFFADR::sptr, SPTR_NULL, substr_len, and SYMNAME.
Referenced by dinit_varref(), and mkeffadr().
negate_const_be()
static INT negate_const_be (INT conval, DTYPE dtype) static
Definition at line 3073 of file dinit.cpp.
References CONVAL2G, DT_CMPLX, DT_DBLE, DT_DCMPLX, DTY, ERR_Severe, getcon(), init_fold_const(), interr(), STB::k0, num, OP_SUB, result, stb, TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, xdneg(), xfneg(), and xqneg().
Referenced by mk_unop().
save_init()
static void save_init (CONST * ict, SPTR sptr) static
Definition at line 5983 of file dinit.cpp.
References cur_init, ERR_Severe, init_const, init_list_count, interr(), PARAMVALG, PARAMVALP, and sptr.
Referenced by dinit_varref(), and eval_do().
sym_is_dinitd()
static void sym_is_dinitd (SPTR sptr) static
a symbol is being initialized update certain attributes of the symbol including its dinit flag
Definition at line 150 of file dinit.cpp.
References sptr.
Referenced by df_dinit(), and dinit_varref().
transfer_load()
static INT transfer_load (DTYPE dtype, char * source) static
Definition at line 4638 of file dinit.cpp.
References DT_DBLE, DT_ISWORD, DTY, ERR_Severe, getcon(), getstring(), interr(), num, size_of(), src, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT8, TY_LOG8, and TY_QUAD.
Referenced by eval_transfer().
transfer_store()
static void transfer_store (INT conval, DTYPE dtype, char * destination) static
Definition at line 4585 of file dinit.cpp.
References CONVAL2G, dest, DT_ISWORD, DTY, ERR_Severe, interr(), STB::n_base, size_of(), stb, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT8, TY_LOG8, and TY_QUAD.
Referenced by eval_transfer().
Variable Documentation
arrbase
CONST* arrbase
Definition at line 2109 of file dinit.cpp.
bottom
DOSTACK* bottom static
Definition at line 73 of file dinit.cpp.
Referenced by df_dinit(), eval(), and hierarchy().
const_err
CONST const_err static
Definition at line 63 of file dinit.cpp.
cur_init
int cur_init = 0 static
Definition at line 61 of file dinit.cpp.
Referenced by save_init().
df
FILE* df static
Definition at line 74 of file dinit.cpp.
Referenced by dinit(), and do_dinit().
struct { ... } dim[7]
Referenced by do_eval_minval_or_maxval(), eval_minval_or_maxval(), eval_size(), eval_sub_index(), and get_offset_without_dim().
dostack
DOSTACK dostack[MAXDEPTH] static
Definition at line 71 of file dinit.cpp.
Referenced by df_dinit(), and dinit_data().
dtype
DTYPE dtype
Definition at line 2112 of file dinit.cpp.
Referenced by convert_acl_dtype(), dinit_subs(), dinit_val(), eval_abs(), eval_ceiling(), eval_char(), eval_const_array_triple_section(), eval_floor(), eval_ichar(), eval_merge(), eval_mod(), eval_repeat(), eval_sqrt(), eval_transfer(), and get_minmax_val().
idx
ISZ_T idx
Definition at line 2113 of file dinit.cpp.
Referenced by eval_reshape().
init_const
CONST** init_const static
Definition at line 60 of file dinit.cpp.
Referenced by do_dinit(), eval_do(), eval_init_expr_item(), and save_init().
init_list_count
int init_list_count = 0
Definition at line 62 of file dinit.cpp.
Referenced by dataConstant(), do_dinit(), read_symbol(), and save_init().
lowb
ISZ_T lowb
Definition at line 2115 of file dinit.cpp.
mplyr
ISZ_T mplyr
Definition at line 2122 of file dinit.cpp.
ndims
int ndims
Definition at line 2110 of file dinit.cpp.
Referenced by do_eval_minval_or_maxval(), eval_const_array_section(), and eval_const_array_triple_section().
root
CONST* root
Definition at line 2107 of file dinit.cpp.
Referenced by add_to_list(), eval_array_constructor(), eval_do(), eval_init_expr(), eval_init_op(), eval_max(), eval_min(), and eval_transfer().
roottail
CONST* roottail
Definition at line 2108 of file dinit.cpp.
Referenced by add_to_list(), do_eval_minval_or_maxval(), eval_array_constructor(), eval_do(), eval_init_expr(), eval_init_op(), eval_max(), and eval_min().
struct { ... } sb
Referenced by eval_const_array_section(), eval_const_array_triple_section(), eval_minval_or_maxval(), eval_sb(), and eval_sub_index().
stride
ISZ_T stride
Definition at line 2117 of file dinit.cpp.
struct { ... } sub[7]
subscr_base
CONST* subscr_base
Definition at line 2114 of file dinit.cpp.
Referenced by eval_sub_index().
substr_len
int substr_len static
Definition at line 67 of file dinit.cpp.
Referenced by df_dinit(), dinit_val(), and mkeffadr().
top
DOSTACK* top static
Definition at line 72 of file dinit.cpp.
Referenced by bld_ud(), df_dinit(), dinit_data(), eval(), find_bivs(), flowgraph(), hierarchy(), init_where(), int128_unsigned_divide(), pop_forall(), pop_scope_level(), pop_where(), push_elsewhere(), push_forall(), push_where(), reaching_defs(), rewrite_block_forall(), semant1(), semant2(), semsmp(), string_with_kind(), and top_sort().
upb
ISZ_T upb
Definition at line 2116 of file dinit.cpp.
Referenced by eval_reshape().