flang: direct.c File Reference
direct.c File Reference
Directive/pragma support modules.
#include "fdirect.h"
#include "pragma.h"
#include "ilidir.h"
#include "miscutil.h"
#include "mach.h"
Classes
struct xf_tag
Macros
#define TR0(s)
#define TR1(s, a)
#define TR2(s, a, b)
#define TR3(s, a, b, c)
#define MAXLINELEN 4096
#define ST_VAL(m)
#define ST_BV(m)
#define UADDR(x) (unsigned int *) & x
Typedefs
typedef struct xf_tag XF
Functions
void direct_init (void)
Initialize directive structure.
void direct_fini ()
...
void direct_rou_end (void)
Re-initialize the routine structure.
void direct_loop_enter (void)
...
void direct_loop_end (int beg_line, int end_line)
Re-initialize the loop structure.
void direct_xf (char *fn, int x, int v)
...
void direct_yf (char *fn, int x, int v)
...
void direct_rou_load (int func)
Load direct.rou for the current function.
void direct_rou_setopt (int func, int opt)
...
void load_dirset (DIRSET *currdir)
...
void store_dirset (DIRSET *currdir)
...
void dirset_options (bool restore)
OPTIONS statement processed (by scan via semant)
static int read_line (void)
static int rd_dir (DIRSET *)
int direct_import (FILE *ff)
...
Variables
DIRECT direct
static XF * xf_p = NULL
static XF * yf_p = NULL
static FILE * dirfil
static int ilmlinenum = 0
static char line [MAXLINELEN]
Detailed Description
Directive/pragma support modules.
Definition in file direct.c.
Macro Definition Documentation
MAXLINELEN
#define MAXLINELEN 4096
Definition at line 646 of file direct.c.
ST_BV
#define ST_BV (m)
Value:
  if (change)    \
  dd->m = (v & change) | (dd->m & ~change)
ST_VAL
#define ST_VAL (m)
Value:
  if (change)     \
  dd->m = v
TR0
#define TR0 (s)
Definition at line 34 of file direct.c.
TR1
#define TR1 (s, a)
Definition at line 35 of file direct.c.
TR2
#define TR2 (s, a, b)
Definition at line 36 of file direct.c.
TR3
#define TR3 (s, a, b, c)
Definition at line 37 of file direct.c.
UADDR
#define UADDR (x) (unsigned int *) & x
Typedef Documentation
XF
typedef struct xf_tag XF
Function Documentation
direct_fini()
void direct_fini (void)
...
Definition at line 145 of file direct.c.
References DIRECT::avail, direct, FREE, DIRECT::lpg, DIRECT::lpg_stk, DIRECT::size, DIRECT::stgb, and DIRECT::top.
Referenced by finish().
direct_import()
int direct_import (FILE * ff)
...
Definition at line 652 of file direct.c.
References DIRECT::avail, lpprg_::beg_line, DBGBIT, direct, dirfil, lpprg_::dirset, lpprg_::end_line, DIRECT::gbl, i, idx, ilmlinenum, line, DIRECT::lpg, NEEDB, rd_dir(), read_line(), DIRECT::rou_begin, DIRECT::size, and DIRECT::stgb.
Referenced by upper().
direct_init()
void direct_init (void)
Initialize directive structure.
...
Initialize directive structure which is global for the source file and the structure which is used per routine. must be called just once for the compilation and after all of the command line options have been processed.
The initial values of the global structure are extracted from the command line options. The routine structure is initialized with values from the global structure.
Definition at line 99 of file direct.c.
References DIRECT::avail, BZERO, DIRECT::carry_fwd, direct, flg, DIRECT::gbl, FLG::genilm, DIRECT::in_loop, DIRECT::loop, DIRECT::loop_flag, DIRECT::lpg, DIRECT::lpg_stk, NEW, NULL, DIRECT::rou, DIRECT::rou_begin, DIRECT::size, DIRECT::stgb, store_dirset(), DIRECT::top, and FLG::x.
Referenced by init().
direct_loop_end()
void direct_loop_end (int beg_line, int end_line)
Re-initialize the loop structure.
...
Must be called after the end of a loop is processed by semant for which loop-scoped pragmas/directives apply.
Definition at line 227 of file direct.c.
References lpprg_::beg_line, DBGBIT, DIRSET::depchk, direct, lpprg_::end_line, flg, FLG::genilm, i, DIRECT::in_loop, DIRECT::loop, DIRECT::loop_flag, DIRECT::lpg, DIRECT::lpg_stk, DIRECT::rou, DIRECT::stgb, DIRECT::top, TR1, TR2, and XBIT.
Referenced by assign(), semant1(), and semant3().
direct_loop_enter()
void direct_loop_enter (void)
...
Definition at line 205 of file direct.c.
References DIRECT::avail, DIRECT::carry_fwd, direct, flg, gbl, FLG::genilm, DIRECT::in_loop, DIRECT::loop, DIRECT::loop_flag, DIRECT::lpg, NEEDB, push_lpprg(), and DIRECT::stgb.
Referenced by assign(), do_distbegin(), and semant3().
direct_rou_end()
void direct_rou_end (void)
Re-initialize the routine structure.
...
Must be called after the end of a function is processed by semant and before the next function is parsed. For C, this is when the END ilm is written for a function. For Fortran, this is after a subprogram has been processed by all phases of the compiler.
For C, process any symbol-/variable- related pragmas which may have occurred. Also, save the index into the lpprg table which is the beginning of the function's lpprg segment; mark the end of the segment with an entry whose beg_line is -1.
Definition at line 184 of file direct.c.
References DIRECT::avail, DIRECT::carry_fwd, direct, flg, DIRECT::gbl, FLG::genilm, DIRECT::loop, DIRECT::lpg, DIRECT::rou, and DIRECT::rou_begin.
Referenced by cleanup(), and process_input().
direct_rou_load()
void direct_rou_load (int func)
Load direct.rou for the current function.
...
Called after the parse phase is complete; called once per function. For C this means the call occurs during expand when it sees the ENTRY ilm; for Fortran, this is at the beginning of expand (in main).
DIRSET direct.rou_begin represents the state of the directives/pragmas at the beginning of the function.
Parameters
func - symbol of current function
Definition at line 343 of file direct.c.
References currdir, DBGBIT, direct, ERR_Informational, error(), flg, xf_tag::fn, func, gbl, load_dirset(), mach, xf_tag::next, NULL, FLG::opt, DIRSET::opt, DIRECT::rou_begin, set_mach(), set_xflag(), set_yflag(), SYMNAME, DIRSET::tpvalue, xf_tag::v, FLG::vect, DIRSET::vect, FLG::x, xf_tag::x, DIRSET::x, xf_p, and yf_p.
Referenced by process_input().
direct_rou_setopt()
void direct_rou_setopt (int func, int opt)
...
Definition at line 409 of file direct.c.
References currdir, direct, flg, FLG::opt, opt, DIRSET::opt, and DIRECT::rou_begin.
direct_xf()
void direct_xf (char * fn, int x, int v)
...
Definition at line 306 of file direct.c.
References fn, xf_tag::fn, getitem(), xf_tag::next, xf_tag::v, x, xf_tag::x, and xf_p.
direct_yf()
void direct_yf (char * fn, int x, int v)
...
Definition at line 319 of file direct.c.
References fn, xf_tag::fn, getitem(), xf_tag::next, xf_tag::v, x, xf_tag::x, and yf_p.
dirset_options()
void dirset_options (bool restore)
OPTIONS statement processed (by scan via semant)
...
These only affect what happens in semant for the 'next' routine. alter any dirset values which can be altered by OPTIONS.
Parameters
restore true if called when restoring effects of OPTIONS
Definition at line 452 of file direct.c.
References direct, flg, DIRECT::gbl, DIRECT::rou_begin, FLG::x, and DIRSET::x.
load_dirset()
void load_dirset (DIRSET * currdir)
...
Definition at line 418 of file direct.c.
References BCOPY, currdir, DBGBIT, FLG::depchk, DIRSET::depchk, flg, FLG::opt, DIRSET::opt, TPNVERSION, FLG::tpvalue, DIRSET::tpvalue, FLG::vect, DIRSET::vect, FLG::x, and DIRSET::x.
Referenced by close_pragma(), direct_rou_load(), open_pragma(), pop_pragma(), and push_pragma().
rd_dir()
static int rd_dir (DIRSET * dd) static
Definition at line 725 of file direct.c.
References direct, idx, is_xflag_bit(), line, opt, read_line(), DIRECT::rou_begin, ST_BV, ST_VAL, UADDR, xf_tag::v, and x.
Referenced by direct_import().
read_line()
static int read_line (void) static
Definition at line 714 of file direct.c.
References dirfil, ilmlinenum, line, MAXLINELEN, and NULL.
Referenced by direct_import(), and rd_dir().
store_dirset()
void store_dirset (DIRSET * currdir)
...
Definition at line 433 of file direct.c.
References BCOPY, currdir, FLG::depchk, DIRSET::depchk, flg, FLG::opt, DIRSET::opt, TPNVERSION, FLG::tpvalue, DIRSET::tpvalue, FLG::vect, DIRSET::vect, FLG::x, and DIRSET::x.
Referenced by direct_init().
Variable Documentation
direct
DIRECT direct
Definition at line 42 of file direct.c.
Referenced by __INT_T(), __mth_i_kicshft(), __mth_i_ukicshft(), check_for_loop_directive(), close_pragma(), direct_fini(), direct_import(), direct_init(), direct_loop_end(), direct_loop_enter(), direct_rou_end(), direct_rou_load(), direct_rou_setopt(), dirset_options(), eliminate_unused_variables(), emit_scatterx_gatherx(), ENTCRF90IO(), ENTF90IO(), find_lpprg(), ili_lpprg_init(), import_use_stmts(), open_pragma(), pop_pragma(), push_pragma(), and rd_dir().
dirfil
FILE* dirfil static
Definition at line 644 of file direct.c.
Referenced by direct_import(), and read_line().
ilmlinenum
int ilmlinenum = 0 static
Definition at line 645 of file direct.c.
Referenced by direct_import(), and read_line().
line
char line[MAXLINELEN] static
Definition at line 647 of file direct.c.
Referenced by direct_import(), rd_dir(), and read_line().
xf_p
XF* xf_p = NULL static
Definition at line 302 of file direct.c.
Referenced by direct_rou_load(), and direct_xf().
yf_p
XF* yf_p = NULL static
Definition at line 303 of file direct.c.
Referenced by direct_rou_load(), and direct_yf().