flang: dispatch.c File Reference
dispatch.c File Reference
#include <stdbool.h>
#include <string.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <time.h>
#include <inttypes.h>
#include <sched.h>
#include "mth_tbldefs.h"
#include "math_tables/mth_acosdefs.h"
#include "math_tables/mth_asindefs.h"
#include "math_tables/mth_atandefs.h"
#include "math_tables/mth_atan2defs.h"
#include "math_tables/mth_cosdefs.h"
#include "math_tables/mth_sindefs.h"
#include "math_tables/mth_tandefs.h"
#include "math_tables/mth_coshdefs.h"
#include "math_tables/mth_sinhdefs.h"
#include "math_tables/mth_tanhdefs.h"
#include "math_tables/mth_expdefs.h"
#include "math_tables/mth_logdefs.h"
#include "math_tables/mth_log10defs.h"
#include "math_tables/mth_powdefs.h"
#include "math_tables/mth_powidefs.h"
#include "math_tables/mth_sincosdefs.h"
#include "math_tables/mth_divdefs.h"
#include "math_tables/mth_sqrtdefs.h"
#include "math_tables/mth_moddefs.h"
#include "math_tables/mth_aintdefs.h"
#include "math_tables/mth_ceildefs.h"
#include "math_tables/mth_floordefs.h"
#include "tmp-mth_statsdefs.h"
#include "tmp-mth_alldefs.h"
Classes
struct text2archtype_t
struct sv2attributes_t
struct frp_env_t
struct fptr2name_t
Macros
#define _STRINGIFY(s) #s
#define STRINGIFY(s) _STRINGIFY(s)
#define ARCH_DEFAULT arch_generic
#define STR_ARCH_DEFAULT "generic"
#define DO_MTH_DISPATCH_FUNC(name_, func_, sv_, frp_) extern void name_##_init(void);
#define DO_MTH_DISPATCH_FUNC(name_, func_, sv_, frp_) extern void name_##_prof(void);
#define MTHINTRIN(_func, _sv, _a, _f, _r, _p, _s)
#define DO_MTH_DISPATCH_FUNC(name_, func_, sv_, frp_) [func_][sv_][frp_] = name_##_prof,
#define DO_MTH_DISPATCH_FUNC(name_, func_, sv_, frp_) [func_][sv_][frp_] = name_##_init,
#define CONSTRUCTOR __attribute__((constructor(101)))
#define DESTRUCTOR __attribute__((destructor))
#define MTHTMPDEF(_f)
Typedefs
typedef p2f __mth_rt_vi_ptrs_t[func_size][sv_size][frp_size]
Enumerations
enum stats_e {
stats_none = 0x0 , stats_summary = 1<<0 , stats_by_type = 1<<1 , stats_by_func = 1<<2 ,
stats_disp_err = 1<<3 , stats_all = stats_summary | stats_by_type | stats_by_func
}
Functions
void __math_dispatch_error (void)
static char * fptr2char (void *)
static void __pgmath_abort (int, char *)
static int get_string_index (char *s, char *tbl[], int len)
static bool is_frp_char_valid (char c)
static frp_e frp2index (char frp)
static void mth_i_override_usage ()
static void mth_i_override ()
static void dump_mth_rt_vi_ptrs ()
static void __math_epilog_do_stats ()
void DESTRUCTOR __math_epilog_ ()
void CONSTRUCTOR __math_dispatch ()
void __math_dispatch_init ()
Variables
static char * carch []
static char * csv []
static char * cfunc []
static mth_intrins_defs_t mth_intrins_defs []
static __mth_rt_vi_ptrs_t __mth_rt_vi_ptrs_statdefs
__mth_rt_vi_ptrs_t __mth_rt_vi_ptrs
__mth_rt_vi_ptrs_t __mth_rt_vi_ptrs_stat
uint64_t __mth_rt_stats [frp_size][func_size][sv_size]
static __mth_rt_vi_ptrs_t __mth_rt_vi_ptrs_new
static volatile bool __math_dispatch_is_init = false
static bool __math_dispatch_in_prog = false
static arch_e __math_target = arch_size
static text2archtype_t text2archtype []
static sv2attributes_t sv2attributes []
static char * elmtsz2text []
static frp_e __mth_fast = frp_f
static frp_e __mth_relaxed = frp_r
static frp_e __mth_precise = frp_p
static frp_e __mth_sleef = frp_s
static char * frp2text []
static frp_env_t frp_env []
static uint64_t __mth_i_debug = 0
static stats_e __mth_i_stats = stats_none
static fptr2name_t fptr2name []
Macro Definition Documentation
_STRINGIFY
#define _STRINGIFY (s) #s
Definition at line 132 of file dispatch.c.
ARCH_DEFAULT
#define ARCH_DEFAULT arch_generic
CONSTRUCTOR
#define CONSTRUCTOR __attribute__((constructor(101)))
Definition at line 333 of file dispatch.c.
DESTRUCTOR
#define DESTRUCTOR __attribute__((destructor))
Definition at line 334 of file dispatch.c.
DO_MTH_DISPATCH_FUNC [1/4]
#define DO_MTH_DISPATCH_FUNC (name_, func_, sv_, frp_) extern void name_##_init(void);
Definition at line 321 of file dispatch.c.
DO_MTH_DISPATCH_FUNC [2/4]
#define DO_MTH_DISPATCH_FUNC (name_, func_, sv_, frp_) extern void name_##_prof(void);
Definition at line 321 of file dispatch.c.
DO_MTH_DISPATCH_FUNC [3/4]
#define DO_MTH_DISPATCH_FUNC (name_, func_, sv_, frp_) [func_][sv_][frp_] = name_##_prof,
Definition at line 321 of file dispatch.c.
DO_MTH_DISPATCH_FUNC [4/4]
#define DO_MTH_DISPATCH_FUNC (name_, func_, sv_, frp_) [func_][sv_][frp_] = name_##_init,
Definition at line 321 of file dispatch.c.
MTHINTRIN
#define MTHINTRIN (_func, _sv, _a, _f, _r, _p, _s)
Value:
  {                                                                    \
    .arch = arch_##_a, .func = func_##_func, .sv = sv_##_sv, .pf = _f, \
    .pr = _r, .pp = _p, .ps=_s,                                        \
  }                                                                    \
  ,
Definition at line 271 of file dispatch.c.
MTHTMPDEF
#define MTHTMPDEF (_f)
Value:
  {                           \
    .pfunc = _f, .cname = #_f \
  }                           \
  ,
Definition at line 505 of file dispatch.c.
STR_ARCH_DEFAULT
#define STR_ARCH_DEFAULT "generic"
STRINGIFY
#define STRINGIFY (s) _STRINGIFY(s)
Definition at line 133 of file dispatch.c.
Typedef Documentation
__mth_rt_vi_ptrs_t
typedef p2f __mth_rt_vi_ptrs_t[func_size][sv_size][frp_size]
Definition at line 142 of file dispatch.c.
Enumeration Type Documentation
stats_e
enum stats_e
Enumerator
stats_none
stats_summary
stats_by_type
stats_by_func
stats_disp_err
stats_all
Definition at line 485 of file dispatch.c.
Function Documentation
__math_dispatch()
void CONSTRUCTOR __math_dispatch ()
Definition at line 988 of file dispatch.c.
References __math_dispatch_error(), __math_target, __mth_fast, __mth_i_debug, __mth_i_stats, __mth_precise, __mth_relaxed, __mth_rt_stats, __mth_rt_vi_ptrs, __mth_rt_vi_ptrs_new, __mth_rt_vi_ptrs_stat, __mth_rt_vi_ptrs_statdefs, __mth_sleef, __pgmath_abort(), arch_any, ARCH_DEFAULT, arch_size, carch, frp_env_t::defval, dump_mth_rt_vi_ptrs(), f, frp2text, frp_env, frp_f, frp_p, frp_r, frp_size, func_size, getenv(), i, is_amd(), is_avx(), is_avx2(), is_avx512f(), is_avx512vl(), is_fma4(), is_intel(), is_sse41(), is_sse4a(), j, mth_i_override(), mth_intrins_defs, NULL, p, text2archtype_t::parch, s, stats_all, stats_summary, STR_ARCH_DEFAULT, STRINGIFY, sv_size, text2archtype, frp_env_t::val, val, and X86IDFN.
Referenced by __math_dispatch_init().
__math_dispatch_error()
void __math_dispatch_error (void)
Definition at line 1350 of file dispatch.c.
References __math_epilog_do_stats(), __mth_i_stats, __pgmath_abort(), fflush(), NULL, stats_disp_err, and void().
Referenced by __math_dispatch(), and __math_epilog_do_stats().
__math_dispatch_init()
void __math_dispatch_init ()
Definition at line 1318 of file dispatch.c.
References __math_dispatch(), __math_dispatch_in_prog, __math_dispatch_is_init, __mth_i_debug, NULL, and void().
__math_epilog_()
void DESTRUCTOR __math_epilog_ ()
Definition at line 975 of file dispatch.c.
References __math_epilog_do_stats(), and __mth_i_stats.
__math_epilog_do_stats()
static void __math_epilog_do_stats () static
Definition at line 812 of file dispatch.c.
References __math_dispatch_error(), __math_target, __mth_i_stats, __mth_rt_stats, __mth_rt_vi_ptrs_stat, carch, cfunc, csv, sv2attributes_t::elmtsz, elmtsz2text, elmtsz_size, f, fflush(), fptr2char(), frp2text, frp_f, frp_p, frp_r, frp_size, func_size, sv2attributes_t::nelmt, pi, s, stats_by_func, stats_by_type, stats_disp_err, stats_summary, sv2attributes, t, and t1.
Referenced by __math_dispatch_error(), and __math_epilog_().
__pgmath_abort()
static void __pgmath_abort (int ierr, char * s) static
Definition at line 1450 of file dispatch.c.
References s.
Referenced by __math_dispatch(), and __math_dispatch_error().
dump_mth_rt_vi_ptrs()
static void dump_mth_rt_vi_ptrs () static
Definition at line 788 of file dispatch.c.
References __mth_i_stats, __mth_rt_vi_ptrs, __mth_rt_vi_ptrs_stat, cfunc, csv, f, fptr2char(), frp_f, frp_p, frp_r, frp_s, func_size, p, and s.
Referenced by __math_dispatch().
fptr2char()
static char * fptr2char (void * fptr) static
Definition at line 775 of file dispatch.c.
References fptr2name, and i.
Referenced by __math_epilog_do_stats(), dump_mth_rt_vi_ptrs(), and mth_i_override().
frp2index()
static frp_e frp2index (char frp) static
Definition at line 545 of file dispatch.c.
References frp_f, frp_p, frp_r, and frp_s.
Referenced by mth_i_override().
get_string_index()
static int get_string_index (char * s, char * tbl[], int len) static
Definition at line 517 of file dispatch.c.
References i, len, and s.
Referenced by mth_i_override().
is_frp_char_valid()
static bool is_frp_char_valid (char c) static
Definition at line 531 of file dispatch.c.
Referenced by mth_i_override().
mth_i_override()
static void mth_i_override () static
Definition at line 585 of file dispatch.c.
References __mth_i_debug, __mth_rt_vi_ptrs_new, cfunc, csv, f, fptr2char(), frp2index(), get_string_index(), getenv(), i, is_frp_char_valid(), j, malloc(), mth_i_override_usage(), name, NULL, s, and strlen().
Referenced by __math_dispatch().
mth_i_override_usage()
static void mth_i_override_usage () static
Definition at line 561 of file dispatch.c.
References cfunc, csv, and i.
Referenced by mth_i_override().
Variable Documentation
__math_dispatch_in_prog
bool __math_dispatch_in_prog = false static
Definition at line 341 of file dispatch.c.
Referenced by __math_dispatch_init().
__math_dispatch_is_init
volatile bool __math_dispatch_is_init = false static
Definition at line 340 of file dispatch.c.
Referenced by __math_dispatch_init().
__math_target
arch_e __math_target = arch_size static
Definition at line 343 of file dispatch.c.
Referenced by __math_dispatch(), and __math_epilog_do_stats().
__mth_fast
frp_e __mth_fast = frp_f static
Definition at line 443 of file dispatch.c.
Referenced by __math_dispatch().
__mth_i_debug
uint64_t __mth_i_debug = 0 static
Definition at line 483 of file dispatch.c.
Referenced by __math_dispatch(), __math_dispatch_init(), and mth_i_override().
__mth_i_stats
stats_e __mth_i_stats = stats_none static
Definition at line 493 of file dispatch.c.
Referenced by __math_dispatch(), __math_dispatch_error(), __math_epilog_(), __math_epilog_do_stats(), and dump_mth_rt_vi_ptrs().
__mth_precise
frp_e __mth_precise = frp_p static
Definition at line 445 of file dispatch.c.
Referenced by __math_dispatch().
__mth_relaxed
frp_e __mth_relaxed = frp_r static
Definition at line 444 of file dispatch.c.
Referenced by __math_dispatch().
__mth_rt_stats
uint64_t __mth_rt_stats[frp_size][func_size][sv_size]
Definition at line 329 of file dispatch.c.
Referenced by __math_dispatch(), and __math_epilog_do_stats().
__mth_rt_vi_ptrs
__mth_rt_vi_ptrs_t __mth_rt_vi_ptrs
Initial value:
= {
}
Definition at line 324 of file dispatch.c.
Referenced by __math_dispatch(), and dump_mth_rt_vi_ptrs().
__mth_rt_vi_ptrs_new
__mth_rt_vi_ptrs_t __mth_rt_vi_ptrs_new static
Definition at line 330 of file dispatch.c.
Referenced by __math_dispatch(), and mth_i_override().
__mth_rt_vi_ptrs_stat
__mth_rt_vi_ptrs_t __mth_rt_vi_ptrs_stat
Definition at line 328 of file dispatch.c.
Referenced by __math_dispatch(), __math_epilog_do_stats(), and dump_mth_rt_vi_ptrs().
__mth_rt_vi_ptrs_statdefs
__mth_rt_vi_ptrs_t __mth_rt_vi_ptrs_statdefs static
Initial value:
= {
}
Definition at line 311 of file dispatch.c.
Referenced by __math_dispatch().
__mth_sleef
frp_e __mth_sleef = frp_s static
Definition at line 446 of file dispatch.c.
Referenced by __math_dispatch().
carch
char* carch[] static
Initial value:
= {
#define ARCH_DEFAULT
#define STR_ARCH_DEFAULT
        [arch_generic]  = "generic",
}
Definition at line 144 of file dispatch.c.
Referenced by __math_dispatch(), and __math_epilog_do_stats().
cfunc
char* cfunc[] static
Initial value:
= {
        [func_acos]     = "acos",
        [func_asin]     = "asin",
        [func_atan]     = "atan",
        [func_atan2]    = "atan2",
        [func_cos]      = "cos",
        [func_sin]      = "sin",
        [func_tan]      = "tan",
        [func_cosh]     = "cosh",
        [func_sinh]     = "sinh",
        [func_tanh]     = "tanh",
        [func_exp]      = "exp",
        [func_log]      = "log",
        [func_log10]    = "log10",
        [func_pow]      = "pow",
        [func_powi1]    = "powi1",
        [func_powi]     = "powi",
        [func_powk1]    = "powk1",
        [func_powk]     = "powk",
        [func_sincos]   = "sincos",
        [func_div]      = "div",
        [func_sqrt]     = "sqrt",
        [func_mod]      = "mod",
        [func_aint]     = "aint",
        [func_ceil]     = "ceil",
        [func_floor]    = "floor",
}
Definition at line 208 of file dispatch.c.
Referenced by __math_epilog_do_stats(), dump_mth_rt_vi_ptrs(), exp_call(), mth_i_override(), and mth_i_override_usage().
csv
char* csv[] static
Definition at line 174 of file dispatch.c.
Referenced by __math_epilog_do_stats(), dump_mth_rt_vi_ptrs(), mth_i_override(), and mth_i_override_usage().
elmtsz2text
char* elmtsz2text[] static
Initial value:
= {
        [elmtsz_32]     = "32",
        [elmtsz_64]     = "64",
        [elmtsz_128]    = "128",
        [elmtsz_256]    = "256",
        [elmtsz_512]    = "512",
}
Definition at line 435 of file dispatch.c.
Referenced by __math_epilog_do_stats().
fptr2name
fptr2name_t fptr2name[] static
Initial value:
= {
    {.pfunc = __math_dispatch_error, .cname = "__math_dispatch_error"},
}
Definition at line 511 of file dispatch.c.
Referenced by fptr2char().
frp2text
char* frp2text[] static
Initial value:
= {
        [frp_f] = "fast",
        [frp_r] = "relaxed",
        [frp_p] = "precise",
        [frp_s] = "sleef",
}
Definition at line 448 of file dispatch.c.
Referenced by __math_dispatch(), and __math_epilog_do_stats().
frp_env
frp_env_t frp_env[] static
Initial value:
= {
    {.var = "MTH_I_FAST",    .val = &__mth_fast, .defval = frp_f},
    {.var = "MTH_I_RELAXED", .val = &__mth_relaxed, .defval = frp_r},
    {.var = "MTH_I_PRECISE", .val = &__mth_precise, .defval = frp_p},
    {.var = "MTH_I_SLEEF",   .val = &__mth_precise, .defval = frp_s},
}
Definition at line 466 of file dispatch.c.
Referenced by __math_dispatch().
mth_intrins_defs
mth_intrins_defs_t mth_intrins_defs[] static
Initial value:
= {
}
Definition at line 278 of file dispatch.c.
Referenced by __math_dispatch().
sv2attributes
sv2attributes_t sv2attributes[] static
Definition at line 397 of file dispatch.c.
Referenced by __math_epilog_do_stats().
text2archtype
text2archtype_t text2archtype[] static
Definition at line 350 of file dispatch.c.
Referenced by __math_dispatch().