flang: dpm_out.h File Reference
dpm_out.h File Reference
#include "lz.h"
Classes
union DTABLE
struct DTB
struct FL
Macros
#define TMPL_DESCR(i) dtb.base[i].template.descr
#define TMPL_RANK(i) dtb.base[i].template.rank
#define TMPL_FLAG(i) dtb.base[i].template.flag
#define TMPL_DIST_TARGET(i) dtb.base[i].template.dist_target
#define TMPL_DIST_TARGET_DESCR(i) dtb.base[i].template.dist_target_descr
#define TMPL_ISSTAR(i) dtb.base[i].template.isstar
#define TMPL_ALIGN_TARGET(i) dtb.base[i].template.align_target
#define TMPL_TARGET_DESCR(i) dtb.base[i].template.target_descr
#define TMPL_CONFORM(i) dtb.base[i].template.conform
#define TMPL_COLLAPSE(i) dtb.base[i].template.collapse
#define TMPL_LB(i, j) dtb.base[i].template.lb[j]
#define TMPL_UB(i, j) dtb.base[i].template.ub[j]
#define TMPL_TYPE(i) dtb.base[i].template.type
#define TMPL_ALIGNEE_SC(i) dtb.base[i].template.alignee_sc
#define TMPL_TARGET_SC(i) dtb.base[i].template.target_sc
#define INS_DESCR(i) dtb.base[i].instance.descr
#define INS_RANK(i) dtb.base[i].instance.rank
#define INS_TEMPLATE(i) dtb.base[i].instance.template
#define INS_DTYPE(i) dtb.base[i].instance.dtype
#define INS_KIND(i) dtb.base[i].instance.kind
#define INS_SIZE(i) dtb.base[i].instance.size
#define __ASSUMED_SIZE 0x0001
#define __SEQUENTIAL 0x0002
#define __ASSUMED_SHAPE 0x0004
#define __SAVE 0x0008
#define __INHERIT 0x0010
#define __NO_OVERLAPS 0x00020
#define __INTENT_INOUT 0
#define __INTENT_IN 0x0040
#define __INTENT_OUT 0x0080
#define __OMITTED_DIST_TARGET 0
#define __PRESCRIPTIVE_DIST_TARGET 0x0100
#define __DESCRIPTIVE_DIST_TARGET 0x0200
#define __TRANSCRIPTIVE_DIST_TARGET 0x0300
#define __OMITTED_DIST_FORMAT 0
#define __PRESCRIPTIVE_DIST_FORMAT 0x0400
#define __DESCRIPTIVE_DIST_FORMAT 0x0800
#define __TRANSCRIPTIVE_DIST_FORMAT 0x0c00
#define __PRESCRIPTIVE_ALIGN_TARGET 0x1000
#define __DESCRIPTIVE_ALIGN_TARGET 0x2000
#define __IDENTITY_MAP 0x4000
#define __DYNAMIC 0x8000
#define __POINTER 0x10000
#define __LOCAL 0x20000
#define __F77_LOCAL_DUMMY 0x40000
#define __OFF_TEMPLATE 0x80000
#define REPLICATED 0
#define DISTRIBUTED 1
#define ALIGNED 2
#define INHERITED 3
#define DIST_TARGET_SHIFT 8
#define DIST_FORMAT_SHIFT 10
#define ALIGN_TARGET_SHIFT 12
#define OMIT 0
#define PRESCRIP 1
#define DESCRIP 2
#define TRANSCRIP 3
#define NONE_SC 0
#define ALLOC_SC 1
#define DUMMY_SC 2
#define STATIC_SC 3
#define COMMON_SC 4
Functions
void set_typed_alloc (DTYPE)
void set_type_in_descriptor (int descriptor_ast, int sptr, DTYPE dtype, int parent_ast, int before_std)
int make_simple_template_from_ast (int ast, int std, LOGICAL need_type_in_descr)
Create a RTE_template call for an effective argument a(1:n,3:m)
int newargs_for_llvmiface (int sptr)
void interface_for_llvmiface (int this_entry, int new_dscptr)
void undouble_callee_args_llvmf90 (int iface)
Variables
DTB dtb
FL fl
Macro Definition Documentation
__ASSUMED_SHAPE
#define __ASSUMED_SHAPE 0x0004
Definition at line 72 of file dpm_out.h.
__ASSUMED_SIZE
#define __ASSUMED_SIZE 0x0001
Definition at line 70 of file dpm_out.h.
__DESCRIPTIVE_ALIGN_TARGET
#define __DESCRIPTIVE_ALIGN_TARGET 0x2000
Definition at line 93 of file dpm_out.h.
__DESCRIPTIVE_DIST_FORMAT
#define __DESCRIPTIVE_DIST_FORMAT 0x0800
Definition at line 89 of file dpm_out.h.
__DESCRIPTIVE_DIST_TARGET
#define __DESCRIPTIVE_DIST_TARGET 0x0200
Definition at line 84 of file dpm_out.h.
__DYNAMIC
#define __DYNAMIC 0x8000
Definition at line 96 of file dpm_out.h.
__F77_LOCAL_DUMMY
#define __F77_LOCAL_DUMMY 0x40000
Definition at line 99 of file dpm_out.h.
__IDENTITY_MAP
#define __IDENTITY_MAP 0x4000
Definition at line 94 of file dpm_out.h.
__INHERIT
#define __INHERIT 0x0010
Definition at line 75 of file dpm_out.h.
__INTENT_IN
#define __INTENT_IN 0x0040
Definition at line 79 of file dpm_out.h.
__INTENT_INOUT
#define __INTENT_INOUT 0
Definition at line 78 of file dpm_out.h.
__INTENT_OUT
#define __INTENT_OUT 0x0080
Definition at line 80 of file dpm_out.h.
__LOCAL
#define __LOCAL 0x20000
Definition at line 98 of file dpm_out.h.
__NO_OVERLAPS
#define __NO_OVERLAPS 0x00020
Definition at line 76 of file dpm_out.h.
__OFF_TEMPLATE
#define __OFF_TEMPLATE 0x80000
Definition at line 100 of file dpm_out.h.
__OMITTED_DIST_FORMAT
#define __OMITTED_DIST_FORMAT 0
Definition at line 87 of file dpm_out.h.
__OMITTED_DIST_TARGET
#define __OMITTED_DIST_TARGET 0
Definition at line 82 of file dpm_out.h.
__POINTER
#define __POINTER 0x10000
Definition at line 97 of file dpm_out.h.
__PRESCRIPTIVE_ALIGN_TARGET
#define __PRESCRIPTIVE_ALIGN_TARGET 0x1000
Definition at line 92 of file dpm_out.h.
__PRESCRIPTIVE_DIST_FORMAT
#define __PRESCRIPTIVE_DIST_FORMAT 0x0400
Definition at line 88 of file dpm_out.h.
__PRESCRIPTIVE_DIST_TARGET
#define __PRESCRIPTIVE_DIST_TARGET 0x0100
Definition at line 83 of file dpm_out.h.
__SAVE
#define __SAVE 0x0008
Definition at line 73 of file dpm_out.h.
__SEQUENTIAL
#define __SEQUENTIAL 0x0002
Definition at line 71 of file dpm_out.h.
__TRANSCRIPTIVE_DIST_FORMAT
#define __TRANSCRIPTIVE_DIST_FORMAT 0x0c00
Definition at line 90 of file dpm_out.h.
__TRANSCRIPTIVE_DIST_TARGET
#define __TRANSCRIPTIVE_DIST_TARGET 0x0300
Definition at line 85 of file dpm_out.h.
ALIGN_TARGET_SHIFT
#define ALIGN_TARGET_SHIFT 12
Definition at line 109 of file dpm_out.h.
ALIGNED
#define ALIGNED 2
Definition at line 104 of file dpm_out.h.
ALLOC_SC
#define ALLOC_SC 1
Definition at line 117 of file dpm_out.h.
COMMON_SC
#define COMMON_SC 4
Definition at line 120 of file dpm_out.h.
DESCRIP
#define DESCRIP 2
Definition at line 113 of file dpm_out.h.
DIST_FORMAT_SHIFT
#define DIST_FORMAT_SHIFT 10
Definition at line 108 of file dpm_out.h.
DIST_TARGET_SHIFT
#define DIST_TARGET_SHIFT 8
Definition at line 107 of file dpm_out.h.
DISTRIBUTED
#define DISTRIBUTED 1
Definition at line 103 of file dpm_out.h.
DUMMY_SC
#define DUMMY_SC 2
Definition at line 118 of file dpm_out.h.
INHERITED
#define INHERITED 3
Definition at line 105 of file dpm_out.h.
INS_DESCR
#define INS_DESCR (i) dtb.base[i].instance.descr
Definition at line 63 of file dpm_out.h.
INS_DTYPE
#define INS_DTYPE (i) dtb.base[i].instance.dtype
Definition at line 66 of file dpm_out.h.
INS_KIND
#define INS_KIND (i) dtb.base[i].instance.kind
Definition at line 67 of file dpm_out.h.
INS_RANK
#define INS_RANK (i) dtb.base[i].instance.rank
Definition at line 64 of file dpm_out.h.
INS_SIZE
#define INS_SIZE (i) dtb.base[i].instance.size
Definition at line 68 of file dpm_out.h.
INS_TEMPLATE
#define INS_TEMPLATE (i) dtb.base[i].instance.template
Definition at line 65 of file dpm_out.h.
NONE_SC
#define NONE_SC 0
Definition at line 116 of file dpm_out.h.
OMIT
#define OMIT 0
Definition at line 111 of file dpm_out.h.
PRESCRIP
#define PRESCRIP 1
Definition at line 112 of file dpm_out.h.
REPLICATED
#define REPLICATED 0
Definition at line 102 of file dpm_out.h.
STATIC_SC
#define STATIC_SC 3
Definition at line 119 of file dpm_out.h.
TMPL_ALIGN_TARGET
#define TMPL_ALIGN_TARGET (i) dtb.base[i].template.align_target
Definition at line 53 of file dpm_out.h.
TMPL_ALIGNEE_SC
#define TMPL_ALIGNEE_SC (i) dtb.base[i].template.alignee_sc
Definition at line 60 of file dpm_out.h.
TMPL_COLLAPSE
#define TMPL_COLLAPSE (i) dtb.base[i].template.collapse
Definition at line 56 of file dpm_out.h.
TMPL_CONFORM
#define TMPL_CONFORM (i) dtb.base[i].template.conform
Definition at line 55 of file dpm_out.h.
TMPL_DESCR
#define TMPL_DESCR (i) dtb.base[i].template.descr
Definition at line 47 of file dpm_out.h.
TMPL_DIST_TARGET
#define TMPL_DIST_TARGET (i) dtb.base[i].template.dist_target
Definition at line 50 of file dpm_out.h.
TMPL_DIST_TARGET_DESCR
#define TMPL_DIST_TARGET_DESCR (i) dtb.base[i].template.dist_target_descr
Definition at line 51 of file dpm_out.h.
TMPL_FLAG
#define TMPL_FLAG (i) dtb.base[i].template.flag
Definition at line 49 of file dpm_out.h.
TMPL_ISSTAR
#define TMPL_ISSTAR (i) dtb.base[i].template.isstar
Definition at line 52 of file dpm_out.h.
TMPL_LB
#define TMPL_LB (i, j) dtb.base[i].template.lb[j]
Definition at line 57 of file dpm_out.h.
TMPL_RANK
#define TMPL_RANK (i) dtb.base[i].template.rank
Definition at line 48 of file dpm_out.h.
TMPL_TARGET_DESCR
#define TMPL_TARGET_DESCR (i) dtb.base[i].template.target_descr
Definition at line 54 of file dpm_out.h.
TMPL_TARGET_SC
#define TMPL_TARGET_SC (i) dtb.base[i].template.target_sc
Definition at line 61 of file dpm_out.h.
TMPL_TYPE
#define TMPL_TYPE (i) dtb.base[i].template.type
Definition at line 59 of file dpm_out.h.
TMPL_UB
#define TMPL_UB (i, j) dtb.base[i].template.ub[j]
Definition at line 58 of file dpm_out.h.
TRANSCRIP
#define TRANSCRIP 3
Definition at line 114 of file dpm_out.h.
Function Documentation
interface_for_llvmiface()
void interface_for_llvmiface (int this_entry, int new_dscptr)
Definition at line 5310 of file dpm_out.c.
References add_auto_len(), arg, aux, AUX::dpdsc_base, emit_kopy_in(), emit_redim(), EntryStd, FREE, i, needs_redim(), NEW, normalize_bounds(), orderargs, reorder_args(), and this_entry_fval.
Referenced by _stb_fixup_ifacearg().
make_simple_template_from_ast()
int make_simple_template_from_ast (int ast, int std, LOGICAL need_type_in_descr)
Create a RTE_template call for an effective argument a(1:n,3:m)
Create a template that looks like (1:n,1:m-2). Return sptr of the template we create. ast must be an A_SUBSCR that has a section subscript RTE_template (template, rank, flags, type, kind, [lb, ub,]...)
Definition at line 3858 of file dpm_out.c.
References add_stmt_before(), argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, astb, ASTB::bnd, diff_lbnd(), DTY, ASTB::dtype, dtype_to_arg(), flg, i, is_whole_array(), j, mk_argt(), mk_binop(), mk_bnd_int(), mk_func_node(), mk_id(), mk_isz_cval(), mkRteRtnNm(), nargs, ASTB::one, OP_ADD, OP_SUB, rank_of(), RTE_template, set_parref_flag2(), set_type_in_descriptor(), SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, size_of_dtype(), FLG::smp, sptr, sptr_of_subscript(), ss, std, sym_get_sdescr(), sym_mkfunc(), and XBIT.
Referenced by transform_section_arg().
newargs_for_llvmiface()
int newargs_for_llvmiface (int sptr)
Definition at line 5304 of file dpm_out.c.
References newargs_for_entry(), and sptr.
Referenced by _stb_fixup_ifacearg().
set_type_in_descriptor()
void set_type_in_descriptor (int descriptor_ast, int sptr, DTYPE dtype, int parent_ast, int before_std)
Definition at line 2178 of file dpm_out.c.
References add_stmt_before(), argt, ARGT_ARG, array_element_dtype(), DT_INT, dtype_to_arg(), find_descriptor_ast(), func, gbl, get_static_type_descriptor(), get_struct_tag_sptr(), get_type_descr_arg(), is_array_dtype(), is_unl_poly(), mk_argt(), mk_cval1(), mk_func_node(), mk_id(), mk_unop(), mkRteRtnNm(), NOSYM, OP_VAL, RTE_no_rtn, RTE_set_intrin_type, RTE_set_type, sptr, and sym_mkfunc_nodesc().
Referenced by emit_alnd(), emit_secd(), init_sdsc_from_dtype(), make_simple_template_from_ast(), and transform_call().
set_typed_alloc()
void set_typed_alloc (DTYPE t)
Definition at line 2163 of file dpm_out.c.
References t, and typed_alloc.
Referenced by conv_allocate().
undouble_callee_args_llvmf90()
void undouble_callee_args_llvmf90 (int iface)
Definition at line 5348 of file dpm_out.c.
References arg, arg_has_descriptor(), aux, AUX::dpdsc_base, get_arg_table(), i, pass_reflected_arg_by_value(), put_arg_table(), and XBIT.
Referenced by _stb_fixup_ifacearg().
Variable Documentation
dtb
DTB dtb extern
Definition at line 130 of file dpm_out.c.
Referenced by dalnd(), dsecd(), free_dtb(), init_dtb(), ipa_restore_dtb(), make_alnd(), make_secd(), mk_dtb(), and rw_dpmout_state().
fl
FL fl extern
Definition at line 131 of file dpm_out.c.
Referenced by conv_allocate(), emit_fl(), finish_fl(), init_fl(), and pghpf_entry().