flang: dpm_out.c File Reference
dpm_out.c File Reference
Fortran data partitioning module, output.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "comm.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "soc.h"
#include "semant.h"
#include "ast.h"
#include "gramtk.h"
#include "extern.h"
#include "dpm_out.h"
#include "rte.h"
#include "hpfutl.h"
#include "state.h"
#include "pragma.h"
#include "lz.h"
#include "optimize.h"
#include "rtlRtns.h"
Classes
struct DYNSH
struct gbientry
Macros
#define RTE_C
#define NO_PTR XBIT(49, 0x8000)
#define NO_CHARPTR XBIT(58, 0x1)
#define NO_DERIVEDPTR XBIT(58, 0x40000)
#define DYNSH_SPTR(i) (dynsh.stg_base[i].sptr)
#define DYNSH_ELSZ(i) (dynsh.stg_base[i].elsz)
Typedefs
typedef struct gbientry gbientry
Functions
static bool allocate_one_auto (int sptr)
Insert memory allocation code for a symbol.
static void component_init_allocd_auto (int, int)
static void add_auto_bounds (int, int)
static void mk_allocate_scalar (int memberast, int sptr, int before)
static void mk_deallocate_scalar (int memberast, int sptr, int after)
static void dealloc_dt_auto (int, int, int)
static void open_entry_guard (int)
static void close_entry_guard (void)
static void interface_for_entry (int, int)
static void reorder_args (int sptrEntry)
static void add_adjarr_bounds (int)
static void add_bound_assignments (int)
static void redimension (int, int)
static void declare_dummy_array (int)
static void declare_array_dummys (int)
static int get_array_pointer (int)
static int newargs_for_entry (int)
static void init_change_mk_id (void)
static void change_mk_id (int sptr, int sptr1)
static void do_change_mk_id (void)
static void finish_fl (void)
static bool emit_alnd (int sptr, int memberast, LOGICAL free_flag, LOGICAL for_allocate, int allocbounds)
static void emit_secd (int sptr, int memberast, LOGICAL free_flag, LOGICAL for_allocate)
static void fix_sdsc_sc (int, int, int)
static void emit_redim (int arg)
static void emit_kopy_in (int, int, int)
static void emit_scalar_kopy_in (int, int)
static int gen_ptr_in (int, int)
static int gen_ptr_out (int, int)
static int gen_copy_out (int, int, int, int)
static int gen_RTE_loc (int)
static LOGICAL is_set (int, int)
static int fill_argt_with_alnd (int sptr, int memberast, int argt, int alnd, int j, int redist, int allocbounds)
static int getbits (int, int, int)
static void prepare_for_astout (void)
static void undouble_callee_args_f90 (void)
static int get_scalar_in_expr (int expr, int std, LOGICAL astversion)
static int emit_get_scalar_sub (int, int)
static int get_arg_table (void)
static void put_arg_table (int)
LOGICAL has_overlap (int sptr)
int find_cc_symbols (int ast)
Scan an expression for compiler-created symbols.
void init_dtb (void)
void free_dtb (void)
static int mk_dtb (int which)
void init_fl (void)
void dpm_out_init (void)
Stub.
static void trans_mkproc (int sptr)
static int extent (int array, int descriptor, int dimension)
Return a 'extent(array,dim)' call.
static void allocate_aligned (int sptr, int memberast, int basesptr)
static void allocate_for_aligned_array (void)
static void check_flag (int flag)
check that distribution and alignment are mutually exclusive
static int construct_flag (int sptr)
static int make_alnd (int sptr)
static void share_alnd (int type)
LOGICAL is_same_alnd (int sptr, int sptr1)
LOGICAL is_same_secd (int sptr, int sptr1)
static int make_secd (int sptr)
static void make_secd_for_members (int dtype)
LOGICAL want_descriptor_anyway (int sptr)
Return TRUE if we need to initialize the descriptor for this symbol because perhaps this is a host subroutine, and the internal subprograms will need the descriptor, or perhaps -g is set.
static void share_secd (void)
static void desc_need_arrays (void)
static void use_dummy_desc (void)
LOGICAL is_kopy_in_needed (int arg)
void unvisit_every_sptr (void)
static void wrap_symbol (int sptr, int memberast, int basesptr)
void transform_wrapup (void)
static LOGICAL arg_has_descriptor (int)
static LOGICAL pass_reflected_arg_by_value (int arg)
void emit_fl (void)
void emit_alnd_secd (int sptr, int memberast, LOGICAL free_flag, int std, int allocbounds)
static int size_of_dtype (int dtype, int sptr, int memberast)
static void emit_target_alnd (int alnd, int memberast, LOGICAL free_flag)
void set_typed_alloc (DTYPE t)
void set_type_in_descriptor (int descriptor_ast, int sptr, DTYPE dtype0, int parent_ast, int before_std)
void make_temp_descriptor (int ast_ele, SPTR sptr_orig, SPTR sptr_tmp, int before_std)
void init_sdsc_from_dtype (int sptr, DTYPE dtype, int before_std)
static LOGICAL bounds_depends (int sptrA, int sptrB)
static LOGICAL arg_depends (int isptr, int jsptr)
LOGICAL needs_redim (int arg)
Return TRUE if the array with symbol table pointer arg requires a redimension statement.
LOGICAL getbit (int x, int p)
static int diff_lbnd (int dtyp, int dim, int ast, int descr)
int make_sec_from_ast (int ast, int std, int stdafter, int sec_ast, int sectflag)
Create section descriptor and initialize prior to call.
int make_sec_from_ast_chk (int ast, int std, int stdafter, int sec_ast, int sectflag, int ignore_c)
int make_simple_template_from_ast (int ast, int std, LOGICAL need_type_in_descr)
Create a RTE_template call for an effective argument a(1:n,3:m)
void set_assumsz_bound (int arg, int entry)
static bool update_shape_info_expr (int arg, int ast)
static void update_shape_info (int arg)
void set_assumed_bounds (int arg, int entry, int actual)
int get_allobnds (int sptr, int ast)
static void find_presence (int ast, int *piftest)
static int add_presence (int ast, int std)
static void add_end_presence (int astpresent, int std)
void rw_dpmout_state (RW_ROUTINE, RW_FILE)
static int get_num (void)
void ipa_restore_dtb (char *line)
int newargs_for_llvmiface (int sptr)
void interface_for_llvmiface (int this_entry, int new_dscptr)
void undouble_callee_args_llvmf90 (int iface)
Variables
static int EntryStd = 0
static int ExitStd = 0
static int f77_local = 0
static int redistribute = 0
static int realign = 0
static int allocatable_freeing = 0
static int this_entry_g
static int new_dscptr_g
static int this_entry_fval = 0
static char * currp
static int * make_secd_flag
static DTYPE typed_alloc = DT_NONE
DTB dtb
FL fl
struct {
DYNSH * stg_base
int stg_size
int stg_avail
} dynsh
struct {
gbientry * base
int avl
int size
int index
int unconditional
} gbitable = {NULL, 0, 0, 0, 1}
static int change_mk_id_list
static int * orderargs
Detailed Description
Fortran data partitioning module, output.
Definition in file dpm_out.c.
Macro Definition Documentation
DYNSH_ELSZ
#define DYNSH_ELSZ (i) (dynsh.stg_base[i].elsz)
Definition at line 145 of file dpm_out.c.
DYNSH_SPTR
#define DYNSH_SPTR (i) (dynsh.stg_base[i].sptr)
Definition at line 144 of file dpm_out.c.
NO_CHARPTR
#define NO_CHARPTR XBIT(58, 0x1)
Definition at line 37 of file dpm_out.c.
NO_DERIVEDPTR
#define NO_DERIVEDPTR XBIT(58, 0x40000)
Definition at line 38 of file dpm_out.c.
NO_PTR
#define NO_PTR XBIT(49, 0x8000)
Definition at line 36 of file dpm_out.c.
RTE_C
#define RTE_C
Definition at line 29 of file dpm_out.c.
Typedef Documentation
gbientry
typedef struct gbientry gbientry
Function Documentation
add_adjarr_bounds()
static void add_adjarr_bounds (int sptr) static
Definition at line 4988 of file dpm_out.c.
References add_bound_assignments(), DTY, and sptr.
Referenced by interface_for_entry().
add_auto_bounds()
static void add_auto_bounds (int sym, int entryStd) static
Definition at line 4690 of file dpm_out.c.
References AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_UPAST, AD_UPBD, AD_ZBASE, add_stmt_before(), ast, ast_visit(), astb, ASTB::bnd, DT_INT, ASTB::dtype, EntryStd, FALSE, get_scalar_in_expr(), i, mk_assn_stmt(), mk_binop(), mk_extent_expr(), ASTB::one, OP_ADD, OP_MUL, and tmp.
Referenced by allocate_one_auto(), and wrap_symbol().
add_bound_assignments()
static void add_bound_assignments (int sym) static
Definition at line 5099 of file dpm_out.c.
References a, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_UPAST, AD_UPBD, AD_ZBASE, add_end_presence(), add_presence(), add_stmt_before(), ast, ast_visit(), astb, ASTB::bnd, ASTB::dtype, EntryStd, FALSE, get_scalar_in_expr(), i, mk_assn_stmt(), mk_binop(), mk_extent_expr(), mk_mlpyr_expr(), ASTB::one, OP_ADD, OP_MUL, std, this_entry_fval, and tmp.
Referenced by add_adjarr_bounds().
add_end_presence()
static void add_end_presence (int astpresent, int std) static
Definition at line 5089 of file dpm_out.c.
References add_stmt_before(), mk_stmt(), and std.
Referenced by add_bound_assignments().
add_presence()
static int add_presence (int ast, int std) static
Definition at line 5075 of file dpm_out.c.
References add_stmt_before(), ast, find_presence(), mk_stmt(), and std.
Referenced by add_bound_assignments().
allocate_aligned()
static void allocate_aligned (int sptr, int memberast, int basesptr) static
Definition at line 314 of file dpm_out.c.
References allocate_aligned(), DTY, gbl, is_tbp_or_final(), mem(), mk_id(), mk_member(), NOSYM, and sptr.
Referenced by allocate_aligned(), and allocate_for_aligned_array().
allocate_for_aligned_array()
static void allocate_for_aligned_array (void) static
Algorithm: This routine puts allocate statement for each aligned arrays except allocatable aligned arrays. allocate(a(a$sd(33):a$sd(34))) This routine is called after all pghpf_template and pghpf_instance which set array descr fully. At the end, it fixes declaration part of arrays by making the deferred array real a(:,:)
Definition at line 361 of file dpm_out.c.
References AD_DEFER, AD_DPTR, ALIGNG, allocate_aligned(), STB::firstusym, sptr, and stb.
Referenced by transform_wrapup().
allocate_one_auto()
static bool allocate_one_auto (int sptr) static
Insert memory allocation code for a symbol.
Parameters
sptr symbol table index for the symbol
Returns
true if \sptr is an array of derived type, and the caller must initialize its components (by calling component_init_allocd_auto after calling wrap_symbol for sptr)
Definition at line 4358 of file dpm_out.c.
References AD_DPTR, AD_LWAST, AD_NUMDIM, AD_UPAST, add_auto_bounds(), add_auto_len(), ALIGNG, ast, dealloc_dt_auto(), DTY, DTYG, EntryStd, ExitStd, i, mk_allocate_scalar(), mk_deallocate_scalar(), mk_id(), mk_mem_allocate(), mk_mem_deallocate(), mk_triple(), r, RUNTIMEG, sptr, and subscr.
Referenced by transform_wrapup().
arg_depends()
static LOGICAL arg_depends (int isptr, int jsptr) static
Definition at line 2829 of file dpm_out.c.
References bounds_depends(), FALSE, and TRUE.
Referenced by reorder_args().
arg_has_descriptor()
static LOGICAL arg_has_descriptor (int oldarg) static
Definition at line 1713 of file dpm_out.c.
References is_kopy_in_needed(), and NOSYM.
Referenced by undouble_callee_args_f90(), and undouble_callee_args_llvmf90().
bounds_depends()
static LOGICAL bounds_depends (int sptrA, int sptrB) static
Definition at line 2764 of file dpm_out.c.
References AD_DPTR, AD_LWAST, AD_LWBD, AD_NUMDIM, AD_UPAST, AD_UPBD, bounds_depends(), contains_ast(), DTY, FALSE, mk_id(), and TRUE.
Referenced by arg_depends(), and bounds_depends().
change_mk_id()
static void change_mk_id (int sptr, int sptr1) static
Definition at line 1112 of file dpm_out.c.
References assert, change_mk_id_list, flg, set_parref_flag2(), FLG::smp, and sptr.
Referenced by emit_alnd_secd(), emit_kopy_in(), make_secd_for_members(), prepare_for_astout(), share_secd(), and wrap_symbol().
check_flag()
static void check_flag (int flag) static
check that distribution and alignment are mutually exclusive
Definition at line 408 of file dpm_out.c.
References __DESCRIPTIVE_ALIGN_TARGET, __DESCRIPTIVE_DIST_FORMAT, __DESCRIPTIVE_DIST_TARGET, __IDENTITY_MAP, __OMITTED_DIST_FORMAT, __OMITTED_DIST_TARGET, __PRESCRIPTIVE_ALIGN_TARGET, __PRESCRIPTIVE_DIST_FORMAT, __PRESCRIPTIVE_DIST_TARGET, __TRANSCRIPTIVE_DIST_FORMAT, __TRANSCRIPTIVE_DIST_TARGET, and assert.
Referenced by construct_flag().
close_entry_guard()
static void close_entry_guard (void) static
Definition at line 3605 of file dpm_out.c.
References add_stmt_after(), ExitStd, gbl, and mk_stmt().
Referenced by transform_wrapup().
component_init_allocd_auto()
static void component_init_allocd_auto (int ast, int std) static
Definition at line 4314 of file dpm_out.c.
References add_stmt_before(), ast, astb, basedtype(), ASTB::bnd, DDTG, dest, DTY, ASTB::dtype, get_dtype_init_template(), get_struct_initialization_tree(), get_temp(), ASTB::i1, j, MAXDIMS, memsym_of_ast(), mk_assn_stmt(), mk_id(), mk_stmt(), mk_subscr(), ndim, NOSYM, SHD_LWB, SHD_NDIM, SHD_UPB, sptr, and std.
Referenced by transform_wrapup().
construct_flag()
static int construct_flag (int sptr) static
Definition at line 423 of file dpm_out.c.
References __ASSUMED_SHAPE, __ASSUMED_SIZE, __INTENT_IN, __INTENT_INOUT, __INTENT_OUT, __POINTER, __SAVE, __SEQUENTIAL, check_flag(), INTENT_DFLT, INTENT_IN, INTENT_INOUT, INTENT_OUT, INTENTG, sptr, and XBIT.
Referenced by make_alnd().
dealloc_dt_auto()
static void dealloc_dt_auto (int ast, int sptr, int after) static
Definition at line 4843 of file dpm_out.c.
References after, ast, has_allocattr(), mk_mem_deallocate(), and sptr.
Referenced by allocate_one_auto().
declare_array_dummys()
static void declare_array_dummys (int this_entry) static
Definition at line 4436 of file dpm_out.c.
References arg, aux, declare_dummy_array(), AUX::dpdsc_base, i, is_array_type(), is_bad_dtype(), and XBIT.
Referenced by transform_wrapup().
declare_dummy_array()
static void declare_dummy_array (int arg) static
Definition at line 4412 of file dpm_out.c.
References AD_DEFER, AD_DPTR, arg, assert, and DTY.
Referenced by declare_array_dummys().
desc_need_arrays()
static void desc_need_arrays (void) static
Definition at line 1144 of file dpm_out.c.
References ALIGNG, aux, STB::firstosym, is_array_type(), AUX::list, RUNTIMEG, sptr, stb, and want_descriptor_anyway().
Referenced by transform_wrapup().
diff_lbnd()
static int diff_lbnd (int dtyp, int dim, int ast, int descr) static
Definition at line 3633 of file dpm_out.c.
References ADD_LWAST, ast, astb, ASTB::bnd, dim, ASTB::dtype, get_global_lower(), mk_binop(), OP_ADD, and OP_SUB.
Referenced by make_sec_from_ast_chk(), and make_simple_template_from_ast().
do_change_mk_id()
static void do_change_mk_id (void) static
Definition at line 1130 of file dpm_out.c.
References ast, change_mk_id_list, mk_id(), NOSYM, and sptr.
Referenced by emit_alnd_secd(), and transform_wrapup().
dpm_out_init()
void dpm_out_init (void)
Stub.
Definition at line 243 of file dpm_out.c.
Referenced by reinit().
emit_alnd()
static bool emit_alnd (int sptr, int memberast, LOGICAL free_flag, LOGICAL for_allocate, int allocbounds) static
Definition at line 2242 of file dpm_out.c.
References add_stmt_before(), argt, ARGT_ARG, assert, astb, ASTB::bnd, check_member(), ASTB::dtype, emit_target_alnd(), EntryStd, fill_argt_with_alnd(), func, gbl, is_bad_dtype(), mk_argt(), mk_func_node(), mk_id(), mk_isz_cval(), mkRteRtnNm(), nargs, ndim, normalize_bounds(), realign, redistribute, RTE_realign, RTE_redistribute, RTE_template, RTE_templateDsc, set_type_in_descriptor(), sptr, sym_mkfunc(), TMPL_ALIGN_TARGET, TMPL_DESCR, TMPL_DIST_TARGET, TMPL_DIST_TARGET_DESCR, TMPL_FLAG, TMPL_RANK, TMPL_TARGET_DESCR, trans_mkproc(), typed_alloc, and XBIT.
Referenced by emit_alnd_secd(), emit_target_alnd(), and wrap_symbol().
emit_alnd_secd()
void emit_alnd_secd (int sptr, int memberast, LOGICAL free_flag, int std, int allocbounds)
Definition at line 1748 of file dpm_out.c.
References A_OPTYPEG, add_arg(), allocatable_freeing, ARGT_ARG, assert, ast, ast_unvisit(), ast_visit(), astb, begin_call(), ASTB::bnd, change_mk_id(), do_change_mk_id(), DTY, DTYG, ASTB::dtype, emit_alnd(), emit_secd(), EntryStd, ERR_Fatal, ExitStd, init_change_mk_id(), INS_DESCR, make_alnd(), make_secd(), mk_isz_cval(), mkRteRtnNm(), NO_CHARPTR, NO_DERIVEDPTR, NO_PTR, RTE_lena, sptr, std, STD_AST, STD_PREV, string_length(), sym_get_sdescr(), sym_mkfunc_nodesc(), TMPL_DESCR, TRUE, TY_CHAR, and XBIT.
Referenced by conv_allocate(), mk_descr_from_section(), and transform_ptr().
emit_fl()
void emit_fl (void)
Definition at line 1721 of file dpm_out.c.
References add_stmt_after(), argt, ARGT_ARG, ast, FL::avl, FL::base, DT_INT, fl, gbl, i, mk_argt(), mk_cval(), mk_func_node(), mk_id(), mkRteRtnNm(), nargs, RTE_freen, and sym_mkfunc().
Referenced by transform_wrapup().
emit_get_scalar_sub()
static int emit_get_scalar_sub (int a, int std) static
Definition at line 4935 of file dpm_out.c.
References a, A_ARGCNTP, add_stmt_before(), ALIGNG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, DISTG, DTY, GETSCALAR_CAUSE, i, INS_DESCR, mk_argt(), mk_default_int(), mk_id(), mk_stmt(), mkRteRtnNm(), nargs, ndim, normalize_bounds(), report_comm(), RTE_get_scalar, sptr, sptr_of_subscript(), std, sub_lbnd(), sym_get_scalar(), sym_mkfunc(), and SYMNAME.
Referenced by get_scalar_in_expr().
emit_kopy_in()
static void emit_kopy_in (int arg, int this_entry, int actual) static
Definition at line 2995 of file dpm_out.c.
References __NO_OVERLAPS, A_OPTYPEP, add_stmt_after(), add_stmt_before(), arg, argt, ARGT_ARG, assert, ast, ast_intr(), astb, ASTB::bnd, change_mk_id(), check_member(), collapse, DDTG, dest, DT_INT, STB::dt_log, DTY, DTYG, ASTB::dtype, dtype_to_arg(), emit_scalar_kopy_in(), emit_target_alnd(), EntryStd, ExitStd, f77_local, fill_argt_with_alnd(), gbitable, gen_copy_out(), gen_ptr_in(), gen_ptr_out(), gen_RTE_loc(), get_array_pointer(), ASTB::i0, ASTB::i1, INS_DESCR, INS_DTYPE, intast_sym, is_array_type(), is_bad_dtype(), is_kopy_in_needed(), is_set(), mk_argt(), mk_cval(), mk_func_node(), mk_id(), mk_isz_cval(), mk_stmt(), mkRteRtnNm(), nargs, ndim, NEWDSCG, NO_CHARPTR, NO_DERIVEDPTR, NO_PTR, normalize_bounds(), present, ASTB::ptr0, ASTB::ptr0c, redimension(), REPLICATED, RTE_present, size_of_dtype(), src, stb, sym_mkfunc_nodesc(), TMPL_ALIGN_TARGET, TMPL_COLLAPSE, TMPL_DESCR, TMPL_DIST_TARGET, TMPL_DIST_TARGET_DESCR, TMPL_FLAG, TMPL_ISSTAR, TMPL_RANK, TMPL_TARGET_DESCR, TMPL_TYPE, trans_mkproc(), TRUE, TY_CHAR, STB::user, and XBIT.
Referenced by emit_target_alnd(), interface_for_entry(), and interface_for_llvmiface().
emit_redim()
static void emit_redim (int arg) static
Definition at line 2899 of file dpm_out.c.
References add_stmt_before(), arg, assert, ast_intr(), DT_INT, STB::dt_log, EntryStd, gbitable, get_array_pointer(), mk_assn_stmt(), mk_id(), mk_stmt(), mkRteRtnNm(), present, redimension(), RTE_present, stb, sym_mkfunc_nodesc(), and STB::user.
Referenced by interface_for_entry(), and interface_for_llvmiface().
emit_scalar_kopy_in()
static void emit_scalar_kopy_in (int arg, int this_entry) static
Definition at line 3517 of file dpm_out.c.
References add_stmt_after(), add_stmt_before(), arg, assert, ast_intr(), astb, DDTG, dest, DT_INT, STB::dt_log, DTY, EntryStd, ExitStd, f77_local, gbitable, gen_ptr_in(), gen_ptr_out(), gen_RTE_loc(), mk_id(), mk_stmt(), mkRteRtnNm(), present, ASTB::ptr0, ASTB::ptr0c, RTE_present, src, stb, sym_mkfunc_nodesc(), TY_CHAR, and STB::user.
Referenced by emit_kopy_in().
emit_secd()
static void emit_secd (int sptr, int memberast, LOGICAL free_flag, LOGICAL for_allocate) static
Definition at line 1899 of file dpm_out.c.
References add_stmt_before(), argt, ARGT_ARG, assert, astb, ASTB::bnd, check_member(), collapse, DTY, ASTB::dtype, dtype_to_arg(), EntryStd, func, gbl, info, INS_DESCR, INS_DTYPE, INS_RANK, INS_TEMPLATE, is_bad_dtype(), j, mk_argt(), mk_func_node(), mk_id(), mk_isz_cval(), mkRteRtnNm(), nargs, ndim, normalize_bounds(), NOSYM, realign, redistribute, RTE_instance, set_type_in_descriptor(), size_of_dtype(), sptr, sym_mkfunc(), TMPL_COLLAPSE, TMPL_ISSTAR, typed_alloc, and XBIT.
Referenced by emit_alnd_secd(), and wrap_symbol().
emit_target_alnd()
static void emit_target_alnd (int alnd, int memberast, LOGICAL free_flag) static
Definition at line 2000 of file dpm_out.c.
References ALLOC_SC, assert, COMMON_SC, DUMMY_SC, emit_alnd(), emit_kopy_in(), FALSE, INHERITED, STATIC_SC, this_entry_g, TMPL_ALIGN_TARGET, TMPL_ALIGNEE_SC, TMPL_DESCR, TMPL_TARGET_DESCR, TMPL_TARGET_SC, and TMPL_TYPE.
Referenced by emit_alnd(), and emit_kopy_in().
extent()
static int extent (int array, int descriptor, int dimension) static
Return a 'extent(array,dim)' call.
Definition at line 290 of file dpm_out.c.
References argt, ARGT_ARG, ast, astb, ASTB::bnd, dimension, DTYG, ASTB::dtype, func, get_global_extent_index(), mk_argt(), mk_func_node(), mk_id(), mk_isz_cval(), mk_subscr(), mkRteRtnNm(), nargs, RTE_extent, sym_mkfunc_nodesc(), and TY_CHAR.
Referenced by __fort_set_alignment(), __fort_set_sectionx(), _makezero(), _sect(), _template(), copy_surrogate_to_bnds_vars(), cshift_loop(), ENTF90(), ENTFTN(), eoshift_scalar(), eval_minval_or_maxval(), gen_defer_shape(), get_ast_extents(), mk_extent(), mk_shared_extent(), red_scalar_loop(), set_assumed_bounds(), set_assumsz_bound(), sourced_alloc_and_assign_array(), sourced_alloc_and_assign_array_from_scalar(), and void().
fill_argt_with_alnd()
static int fill_argt_with_alnd (int sptr, int memberast, int argt, int alnd, int j, int redist, int allocbounds) static
Definition at line 2389 of file dpm_out.c.
References __IDENTITY_MAP, a, ad_val_of(), ALIGNED, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, ast_replace(), ast_rewrite(), astb, ASTB::bnd, check_member(), DESCRIP, DIST_FORMAT_SHIFT, DISTRIBUTED, dt, DTY, ASTB::dtype, getbits(), i, is_set(), j, lb, m, mk_binop(), mk_bnd_int(), mk_id(), mk_isz_cval(), ndim, normalize_bounds(), NOSYM, ASTB::one, OP_ADD, OP_SUB, PRESCRIP, s, sptr, stride, TMPL_ALIGN_TARGET, TMPL_COLLAPSE, TMPL_CONFORM, TMPL_DIST_TARGET_DESCR, TMPL_FLAG, TMPL_ISSTAR, TMPL_LB, TMPL_RANK, TMPL_TARGET_DESCR, TMPL_TYPE, TMPL_UB, and ub.
Referenced by emit_alnd(), and emit_kopy_in().
find_cc_symbols()
int find_cc_symbols (int ast)
Scan an expression for compiler-created symbols.
Returns
0 if the expression contains a compiler-created symbol
1 if all variables are user declared
-1 if all symbols are constants (or something other than above)
We use this routine when examining the distribution block factor expression.
Definition at line 2122 of file dpm_out.c.
References ast, find_cc_symbols(), j, and k.
Referenced by find_cc_symbols().
find_presence()
static void find_presence (int ast, int * piftest) static
Definition at line 5003 of file dpm_out.c.
References A_ARGCNTG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, ast, ast_intr(), STB::dt_log, find_presence(), i, interr(), mk_binop(), mk_id(), nargs, ndim, OP_LAND, sptr, stb, and STB::user.
Referenced by add_presence(), and find_presence().
finish_fl()
static void finish_fl (void) static
Definition at line 199 of file dpm_out.c.
References FL::base, fl, and FREE.
Referenced by transform_wrapup().
fix_sdsc_sc()
static void fix_sdsc_sc (int sptr, int sdsc, int arrdsc) static
If the symbol is pointer-based, need to make sure that the storage class of its descriptor is consistent with its pointer; specifically (f15624), if the pointer is SC_PRIVATE, the descriptor must be SC_PRIVATE. Generally speaking, privatizing temps occurs at the time the temps are created. Context is set wrt being in a parallel region. Unfortunately, the parallel vs serial context is not available at transform_wrapup-time where the only information available is what's in the symbol table. The routine used to create descriptors is via symutl.c:trans_mkdescr(). This routine is called from various points in the compiler and creates ST_ARRDSC entries which eventually become ...$sd temp arrays. The bug of f15624 has to do with the descriptors of the temps created for copy-in/copy-out calls at certain call sites. REVISION - the private storage class cannot simply be copied to the descriptor; a private allocatable array will have a shared descriptor.
Definition at line 5220 of file dpm_out.c.
References sptr.
Referenced by share_secd().
free_dtb()
void free_dtb (void)
Definition at line 170 of file dpm_out.c.
References DTB::avl, DTB::base, dtb, FREE, and DTB::size.
Referenced by transform_wrapup().
gen_copy_out()
static int gen_copy_out (int newarg, int arg, int newdsc, int dummy_sec) static
Definition at line 3332 of file dpm_out.c.
References a, A_ARGCNTP, A_OPTYPEP, arg, argt, ARGT_ARG, DT_INT, intast_sym, INTENTG, mk_argt(), mk_cval(), mk_id(), mk_stmt(), and nargs.
Referenced by emit_kopy_in().
gen_ptr_in()
static int gen_ptr_in (int arg, int this_entry) static
Definition at line 3374 of file dpm_out.c.
References A_OPTYPEP, add_stmt_before(), arg, ARGT_ARG, assert, ast_intr(), astb, base, ASTB::bnd, DDTG, ASTB::dtype, dtype_to_arg(), EntryStd, intast_sym, is_bad_dtype(), kind, len, mk_argt(), mk_assn_stmt(), mk_convert(), mk_cval(), mk_func_node(), mk_id(), mk_isz_cval(), nargs, ndim, NEWDSCG, rank_of_sym(), size_ast_of(), sym_get_scalar(), and SYMNAME.
Referenced by emit_kopy_in(), and emit_scalar_kopy_in().
gen_ptr_out()
static int gen_ptr_out (int arg, int this_entry) static
Definition at line 3467 of file dpm_out.c.
References A_OPTYPEP, arg, ARGT_ARG, assert, base, intast_sym, is_bad_dtype(), mk_argt(), mk_func_node(), mk_id(), nargs, and NEWDSCG.
Referenced by emit_kopy_in(), and emit_scalar_kopy_in().
gen_RTE_loc()
static int gen_RTE_loc (int arg_ast) static
Definition at line 4855 of file dpm_out.c.
References DT_PTR, mk_unop(), and OP_LOC.
Referenced by emit_kopy_in(), and emit_scalar_kopy_in().
get_allobnds()
int get_allobnds (int sptr, int ast)
Definition at line 4464 of file dpm_out.c.
References add_lbnd(), assert, ast, check_member(), DTY, get_local_lower(), get_local_upper(), i, INS_DESCR, lb, mk_subscr(), mk_triple(), ndim, normalize_bounds(), rank_of_sym(), sptr, and ub.
Referenced by redimension().
get_arg_table()
static int get_arg_table (void) static
Definition at line 2533 of file dpm_out.c.
References aux, and AUX::dpdsc_avl.
Referenced by newargs_for_entry(), undouble_callee_args_f90(), and undouble_callee_args_llvmf90().
get_array_pointer()
static int get_array_pointer (int arg) static
Definition at line 4397 of file dpm_out.c.
References arg, assert, and sym_get_ptr().
Referenced by emit_kopy_in(), and emit_redim().
get_num()
static int get_num (void) static
Definition at line 5241 of file dpm_out.c.
References atoxi(), currp, p, val, and void().
Referenced by ipa_restore_dtb().
get_scalar_in_expr()
static int get_scalar_in_expr (int expr, int std, LOGICAL astversion) static
Definition at line 4861 of file dpm_out.c.
References A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, d, emit_get_scalar(), emit_get_scalar_sub(), get_scalar_in_expr(), i, interr(), mk_binop(), mk_convert(), mk_member(), mk_paren(), mk_substr(), mk_triple(), mk_unop(), nargs, r, and std.
Referenced by add_auto_bounds(), add_bound_assignments(), get_scalar_in_expr(), and make_sec_from_ast_chk().
getbit()
LOGICAL getbit (int x, int p)
Definition at line 3616 of file dpm_out.c.
References p, and x.
Referenced by eliminate_sect(), emit_scatterx_gatherx(), emit_sum_scatterx(), generate_gather(), make_sec_ast(), and make_sec_from_ast_chk().
getbits()
static int getbits (int x, int p, int n) static
Definition at line 3622 of file dpm_out.c.
References n, p, and x.
Referenced by fill_argt_with_alnd().
has_overlap()
LOGICAL has_overlap (int sptr)
init_change_mk_id()
static void init_change_mk_id (void) static
Definition at line 1106 of file dpm_out.c.
References change_mk_id_list, and NOSYM.
Referenced by emit_alnd_secd(), and transform_wrapup().
init_dtb()
void init_dtb (void)
Definition at line 159 of file dpm_out.c.
References DTB::avl, DTB::base, BZERO, dtb, NEW, NULL, and DTB::size.
Referenced by forall_init(), and ipa_restore_dtb().
init_fl()
void init_fl (void)
Definition at line 191 of file dpm_out.c.
References FL::avl, FL::base, fl, NEW, and FL::size.
Referenced by conv_allocate(), and transform_wrapup().
init_sdsc_from_dtype()
void init_sdsc_from_dtype (int sptr, DTYPE dtype, int before_std)
Definition at line 2382 of file dpm_out.c.
References init_sdsc(), mk_id(), set_type_in_descriptor(), and sptr.
Referenced by transform_call().
interface_for_entry()
static void interface_for_entry (int this_entry, int new_dscptr) static
Definition at line 2719 of file dpm_out.c.
References add_adjarr_bounds(), add_auto_len(), arg, ast_visit(), aux, AUX::dpdsc_base, DTY, emit_kopy_in(), emit_redim(), EntryStd, f77_local, FREE, i, needs_redim(), NEW, normalize_bounds(), orderargs, reorder_args(), and this_entry_fval.
Referenced by transform_wrapup().
interface_for_llvmiface()
void interface_for_llvmiface (int this_entry, int new_dscptr)
Definition at line 5310 of file dpm_out.c.
References add_auto_len(), arg, aux, AUX::dpdsc_base, emit_kopy_in(), emit_redim(), EntryStd, FREE, i, needs_redim(), NEW, normalize_bounds(), orderargs, reorder_args(), and this_entry_fval.
Referenced by _stb_fixup_ifacearg().
ipa_restore_dtb()
void ipa_restore_dtb (char * line)
Definition at line 5256 of file dpm_out.c.
References DTB::avl, DTB::base, currp, d, dtb, get_num(), i, init_dtb(), INS_DESCR, INS_DTYPE, INS_KIND, INS_RANK, INS_SIZE, INS_TEMPLATE, line, NEED, NULL, DTB::size, TMPL_ALIGN_TARGET, TMPL_ALIGNEE_SC, TMPL_COLLAPSE, TMPL_CONFORM, TMPL_DESCR, TMPL_DIST_TARGET, TMPL_DIST_TARGET_DESCR, TMPL_FLAG, TMPL_ISSTAR, TMPL_LB, TMPL_RANK, TMPL_TARGET_DESCR, TMPL_TARGET_SC, TMPL_TYPE, TMPL_UB, and w.
is_kopy_in_needed()
LOGICAL is_kopy_in_needed (int arg)
Definition at line 1199 of file dpm_out.c.
References ADD_ASSUMSHP, arg, DTY, FALSE, and TRUE.
Referenced by arg_has_descriptor(), emit_kopy_in(), is_desc_needed(), use_dummy_desc(), and wrap_symbol().
is_same_alnd()
LOGICAL is_same_alnd (int sptr, int sptr1)
Definition at line 751 of file dpm_out.c.
References FALSE, i, ndim, sptr, TMPL_ALIGN_TARGET, TMPL_COLLAPSE, TMPL_CONFORM, TMPL_DIST_TARGET_DESCR, TMPL_FLAG, TMPL_ISSTAR, TMPL_LB, TMPL_RANK, TMPL_TARGET_DESCR, TMPL_UB, and TRUE.
Referenced by share_alnd().
is_same_secd()
LOGICAL is_same_secd (int sptr, int sptr1)
Definition at line 803 of file dpm_out.c.
References DTY, dtype_to_arg(), FALSE, INS_RANK, INS_TEMPLATE, mk_id(), ndim, size_ast_of(), sptr, and TRUE.
Referenced by share_secd().
is_set()
static LOGICAL is_set (int flag, int value) static
Definition at line 632 of file dpm_out.c.
References FALSE, TRUE, and value().
Referenced by emit_kopy_in(), fill_argt_with_alnd(), and make_alnd().
make_alnd()
static int make_alnd (int sptr) static
Definition at line 456 of file dpm_out.c.
References __ASSUMED_SHAPE, __ASSUMED_SIZE, AD_DPTR, AD_LWAST, AD_LWBD, AD_UPAST, AD_UPBD, assert, DTB::base, BZERO, construct_flag(), DT_INT, dtb, i, is_bad_dtype(), is_set(), mk_cval(), mk_dtb(), ndim, rank_of_sym(), REPLICATED, sptr, TMPL_FLAG, TMPL_LB, TMPL_RANK, TMPL_TYPE, TMPL_UB, and trans_mkdescr().
Referenced by emit_alnd_secd(), make_secd_for_members(), and share_alnd().
make_sec_from_ast()
int make_sec_from_ast (int ast, int std, int stdafter, int sec_ast, int sectflag)
Create section descriptor and initialize prior to call.
It initialize before std. And section information comes from AST arr. ast is A_SUBSCR with non-null shape. To find section boundary, it looks for AST. If AST is not enough (e.g, A(:,1)), it uses the shape. Check for A(:)%B(5) also.
Definition at line 3659 of file dpm_out.c.
References ast, make_sec_from_ast_chk(), sectflag, and std.
Referenced by copy_arg_to_seq_tmp(), emit_permute_section(), emit_sum_scatterx(), generate_sect(), handle_seq_section(), transform_associated(), transform_ptr(), and transform_section_arg().
make_sec_from_ast_chk()
int make_sec_from_ast_chk (int ast, int std, int stdafter, int sec_ast, int sectflag, int ignore_c)
Definition at line 3668 of file dpm_out.c.
References a, add_stmt_before(), argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, astb, ASTB::bnd, check_member(), diff_lbnd(), DT_INT, DT_PTR, ASTB::dtype, FALSE, get_scalar_in_expr(), getbit(), i, interr(), is_whole_array(), j, pure_gbl::local_mode, mk_argt(), mk_bnd_int(), mk_func_node(), mk_id(), mk_isz_cval(), mk_subscr(), mk_unop(), mkRteRtnNm(), nargs, ndim, NOSYM, ASTB::one, OP_VAL, parent, rank_of(), RTE_sect, RTE_sect1, RTE_sect1v, RTE_sect2, RTE_sect2v, RTE_sect3, RTE_sect3v, sectflag, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, size_of(), sptr, sptr_of_subscript(), std, sym_get_sdescr(), sym_mkfunc(), TRUE, and XBIT.
Referenced by handle_seq_section(), and make_sec_from_ast().
make_secd()
static int make_secd (int sptr) static
Definition at line 839 of file dpm_out.c.
References AD_DPTR, ALIGNG, assert, DTB::base, BZERO, dtb, i, INS_DESCR, INS_DTYPE, INS_RANK, INS_TEMPLATE, is_bad_dtype(), mk_dtb(), ndim, rank_of_sym(), sptr, and TMPL_DESCR.
Referenced by emit_alnd_secd(), make_secd_for_members(), and share_secd().
make_secd_for_members()
static void make_secd_for_members (int dtype) static
Definition at line 869 of file dpm_out.c.
References change_mk_id(), DTY, INS_DESCR, INS_TEMPLATE, make_alnd(), make_secd(), make_secd_flag, make_secd_for_members(), mem(), NOSYM, sym_get_sdescr(), TMPL_DESCR, and XBIT.
Referenced by make_secd_for_members(), and share_secd().
make_simple_template_from_ast()
int make_simple_template_from_ast (int ast, int std, LOGICAL need_type_in_descr)
Create a RTE_template call for an effective argument a(1:n,3:m)
Create a template that looks like (1:n,1:m-2). Return sptr of the template we create. ast must be an A_SUBSCR that has a section subscript RTE_template (template, rank, flags, type, kind, [lb, ub,]...)
Definition at line 3858 of file dpm_out.c.
References add_stmt_before(), argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, astb, ASTB::bnd, diff_lbnd(), DTY, ASTB::dtype, dtype_to_arg(), flg, i, is_whole_array(), j, mk_argt(), mk_binop(), mk_bnd_int(), mk_func_node(), mk_id(), mk_isz_cval(), mkRteRtnNm(), nargs, ASTB::one, OP_ADD, OP_SUB, rank_of(), RTE_template, set_parref_flag2(), set_type_in_descriptor(), SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, size_of_dtype(), FLG::smp, sptr, sptr_of_subscript(), ss, std, sym_get_sdescr(), sym_mkfunc(), and XBIT.
Referenced by transform_section_arg().
make_temp_descriptor()
void make_temp_descriptor (int ast_ele, SPTR sptr_orig, SPTR sptr_tmp, int before_std)
Definition at line 2360 of file dpm_out.c.
References add_stmt_before(), argt, ARGT_ARG, assert, ast, check_member(), ERR_Fatal, mk_argt(), mk_func_node(), mk_id(), mkRteRtnNm(), nargs, RTE_tmp_desc, sym_mkfunc(), and void().
Referenced by transform_call().
mk_allocate_scalar()
static void mk_allocate_scalar (int memberast, int sptr, int before) static
Definition at line 4817 of file dpm_out.c.
References a, A_TKNP, add_stmt_before(), ast, check_member(), mk_id(), mk_stmt(), and sptr.
Referenced by allocate_one_auto(), and wrap_symbol().
mk_deallocate_scalar()
static void mk_deallocate_scalar (int memberast, int sptr, int after) static
Definition at line 4830 of file dpm_out.c.
References a, A_TKNP, add_stmt_after(), after, ast, check_member(), mk_id(), mk_stmt(), and sptr.
Referenced by allocate_one_auto(), and wrap_symbol().
mk_dtb()
static int mk_dtb (int which) static
Definition at line 178 of file dpm_out.c.
References DTB::avl, DTB::base, dtb, errfatal(), NEED, NULL, DTB::size, SPTR_MAX, and DTABLE::which.
Referenced by make_alnd(), and make_secd().
needs_redim()
LOGICAL needs_redim (int arg)
Return TRUE if the array with symbol table pointer arg requires a redimension statement.
Definition at line 2941 of file dpm_out.c.
References arg, DDTG, DTYG, f77_local, FALSE, is_array_type(), is_bad_dtype(), NO_CHARPTR, NO_DERIVEDPTR, NO_PTR, TRUE, and TY_CHAR.
Referenced by interface_for_entry(), interface_for_llvmiface(), newargs_for_entry(), and rewrite_func_ast().
newargs_for_entry()
static int newargs_for_entry (int this_entry) static
Definition at line 2557 of file dpm_out.c.
References arg, ast, aux, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, EntryStd, FUNCLINEG, gbl, gen_contig_check(), get_arg_table(), i, is_array_type(), is_bad_dtype(), is_procedure_ptr(), mk_id(), NEED, needs_redim(), NEWDSCG, NEWDSCP, normalize_bounds(), put_arg_table(), sem, set_preserve_descriptor(), sym_get_arg_sec(), sym_get_formal(), sym_get_sec(), SEM::which_pass, and XBIT.
Referenced by newargs_for_llvmiface(), and transform_wrapup().
newargs_for_llvmiface()
int newargs_for_llvmiface (int sptr)
Definition at line 5304 of file dpm_out.c.
References newargs_for_entry(), and sptr.
Referenced by _stb_fixup_ifacearg().
open_entry_guard()
static void open_entry_guard (int entry) static
Definition at line 3589 of file dpm_out.c.
References add_stmt_after(), ast, DT_INT, DT_LOG, ExitStd, gbl, mk_binop(), mk_cval(), mk_id(), mk_stmt(), and OP_EQ.
Referenced by transform_wrapup().
pass_reflected_arg_by_value()
static LOGICAL pass_reflected_arg_by_value (int arg) static
Definition at line 1635 of file dpm_out.c.
References FALSE.
Referenced by undouble_callee_args_f90(), and undouble_callee_args_llvmf90().
prepare_for_astout()
static void prepare_for_astout (void) static
Definition at line 1565 of file dpm_out.c.
References change_mk_id(), DTY, STB::firstusym, flg, INS_DESCR, set_parref_flag2(), FLG::smp, sptr, stb, sym_get_sdescr(), undouble_callee_args_f90(), and want_descriptor_anyway().
Referenced by transform_wrapup().
put_arg_table()
static void put_arg_table (int arg) static
Definition at line 2539 of file dpm_out.c.
References arg, aux, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, and NEED.
Referenced by newargs_for_entry(), undouble_callee_args_f90(), and undouble_callee_args_llvmf90().
redimension()
static void redimension (int sptr, int memberast) static
Definition at line 4500 of file dpm_out.c.
References add_stmt_before(), check_member(), EntryStd, get_allobnds(), interr(), mk_id(), mk_stmt(), and sptr.
Referenced by emit_kopy_in(), and emit_redim().
reorder_args()
static void reorder_args (int sptrEntry) static
Definition at line 2845 of file dpm_out.c.
References arg_depends(), aux, CNULL, AUX::dpdsc_base, error(), gbl, nargs, orderargs, and SYMNAME.
Referenced by interface_for_entry(), and interface_for_llvmiface().
rw_dpmout_state()
void rw_dpmout_state (RW_ROUTINE , RW_FILE)
Definition at line 5230 of file dpm_out.c.
References DTB::avl, DTB::base, dtb, and RW_FD.
Referenced by rw_host_state().
set_assumed_bounds()
void set_assumed_bounds (int arg, int entry, int actual)
Definition at line 4064 of file dpm_out.c.
References a, AD_DEFER, AD_DPTR, AD_LWAST, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_UPAST, AD_ZBASE, ADD_LWAST, ADD_LWBD, add_stmt_after(), arg, assert, ast, ast_intr(), astb, ASTB::bnd, check_member(), STB::dt_log, ASTB::dtype, extent(), f77_local, get_global_lower(), get_isz_cval(), get_local_multiplier(), get_section_offset(), get_section_stride(), get_xbase(), i, is_array_type(), ISZ_T, lb, mk_assn_stmt(), mk_binop(), mk_bnd_int(), mk_id(), mk_isz_cval(), mk_mlpyr_expr(), mk_stmt(), mkRteRtnNm(), NEWDSCG, ASTB::one, OP_ADD, OP_LT, OP_MUL, OP_SUB, present, r, RTE_present, stb, std, sym_mkfunc_nodesc(), tmp, update_shape_info(), STB::user, and XBIT.
Referenced by assumshp_args().
set_assumsz_bound()
void set_assumsz_bound (int arg, int entry)
Definition at line 3945 of file dpm_out.c.
References AD_DPTR, AD_EXTNTAST, AD_NUMDIM, add_stmt_after(), arg, assert, ast_intr(), STB::dt_log, extent(), f77_local, i, mk_id(), mk_stmt(), mkRteRtnNm(), NEWDSCG, present, RTE_present, stb, std, sym_mkfunc_nodesc(), and STB::user.
set_type_in_descriptor()
void set_type_in_descriptor (int descriptor_ast, int sptr, DTYPE dtype0, int parent_ast, int before_std)
Definition at line 2178 of file dpm_out.c.
References add_stmt_before(), argt, ARGT_ARG, array_element_dtype(), DT_INT, dtype_to_arg(), find_descriptor_ast(), func, gbl, get_static_type_descriptor(), get_struct_tag_sptr(), get_type_descr_arg(), is_array_dtype(), is_unl_poly(), mk_argt(), mk_cval1(), mk_func_node(), mk_id(), mk_unop(), mkRteRtnNm(), NOSYM, OP_VAL, RTE_no_rtn, RTE_set_intrin_type, RTE_set_type, sptr, and sym_mkfunc_nodesc().
Referenced by emit_alnd(), emit_secd(), init_sdsc_from_dtype(), make_simple_template_from_ast(), and transform_call().
set_typed_alloc()
void set_typed_alloc (DTYPE t)
Definition at line 2163 of file dpm_out.c.
References t, and typed_alloc.
Referenced by conv_allocate().
share_alnd()
static void share_alnd (int type) static
Definition at line 643 of file dpm_out.c.
References ALIGNG, assert, aux, DDTG, DISTG, gbl, is_bad_dtype(), is_same_alnd(), AUX::list, make_alnd(), NOSYM, sptr, sym_get_sdescr(), TMPL_DESCR, type, and XBIT.
Referenced by transform_wrapup().
share_secd()
static void share_secd (void) static
Definition at line 964 of file dpm_out.c.
References assert, aux, BZERO, change_mk_id(), FLG::debug, dlen(), STB::dt, DTY, STB::firstosym, fix_sdsc_sc(), flg, FREE, gbl, INS_DESCR, is_bad_dtype(), is_same_secd(), AUX::list, make_secd(), make_secd_flag, make_secd_for_members(), NEW, NOSYM, sptr, stb, sym_get_sdescr(), and XBIT.
Referenced by transform_wrapup().
size_of_dtype()
static int size_of_dtype (int dtype, int sptr, int memberast) static
Definition at line 1871 of file dpm_out.c.
References add_arg(), astb, begin_call(), ASTB::bnd, check_member(), DTY, ASTB::dtype, mk_bnd_int(), mk_id(), mk_isz_cval(), mkRteRtnNm(), NOSYM, RTE_lena, size_of(), sptr, sym_mkfunc_nodesc(), and TY_CHAR.
Referenced by emit_kopy_in(), emit_secd(), and make_simple_template_from_ast().
trans_mkproc()
static void trans_mkproc (int sptr) static
Definition at line 249 of file dpm_out.c.
References AD_DPTR, AD_LWBD, AD_UPBD, add_stmt_before(), argt, ARGT_ARG, DT_INT, DTY, EntryStd, i, mk_argt(), mk_cval(), mk_func_node(), mk_id(), mk_size(), mkRteRtnNm(), nargs, ndim, rank_of(), RTE_processors, sptr, and sym_mkfunc().
Referenced by emit_alnd(), and emit_kopy_in().
transform_wrapup()
void transform_wrapup (void)
Definition at line 1410 of file dpm_out.c.
References add_auto_len(), allocate_for_aligned_array(), allocate_one_auto(), ast_unvisit(), BLOCK_ENDPROLOG_STD, BLOCK_EXIT_STD, close_entry_guard(), component_init_allocd_auto(), declare_array_dummys(), desc_need_arrays(), do_change_mk_id(), DTYG, emit_fl(), EntryStd, ExitStd, f77_local, finish_fl(), STB::firstosym, flg, FREE, free_dtb(), gbl, i, init_change_mk_id(), init_fl(), interface_for_entry(), j, mk_id(), NEW, new_dscptr_g, newargs_for_entry(), NOSYM, open_entry_guard(), prepare_for_astout(), s, set_parref_flag2(), share_alnd(), share_secd(), FLG::smp, sptr, stb, STD_FIRST, STD_LINENO, STD_NEXT, STD_PREV, sym_get_ptr(), this_entry_g, TY_CHAR, TY_NCHAR, unvisit_every_sptr(), use_dummy_desc(), and wrap_symbol().
Referenced by convert_output().
undouble_callee_args_f90()
static void undouble_callee_args_f90 (void) static
Definition at line 1641 of file dpm_out.c.
References arg, arg_has_descriptor(), aux, AUX::dpdsc_base, gbl, get_arg_table(), i, NOSYM, pass_reflected_arg_by_value(), put_arg_table(), and XBIT.
Referenced by prepare_for_astout().
undouble_callee_args_llvmf90()
void undouble_callee_args_llvmf90 (int iface)
Definition at line 5348 of file dpm_out.c.
References arg, arg_has_descriptor(), aux, AUX::dpdsc_base, get_arg_table(), i, pass_reflected_arg_by_value(), put_arg_table(), and XBIT.
Referenced by _stb_fixup_ifacearg().
unvisit_every_sptr()
void unvisit_every_sptr (void)
Definition at line 1232 of file dpm_out.c.
References STB::firstosym, sptr, and stb.
Referenced by convert_statements(), and transform_wrapup().
update_shape_info()
static void update_shape_info (int arg) static
Definition at line 4034 of file dpm_out.c.
References A_ISEXPR, arg, ast, astb, ASTB::bnd, i, ASTB::one, SHD_LWB, SHD_NDIM, sptr, std, STD_AST, STD_NEXT, and update_shape_info_expr().
Referenced by set_assumed_bounds().
update_shape_info_expr()
static bool update_shape_info_expr (int arg, int ast) static
Definition at line 3996 of file dpm_out.c.
References arg, ast, astb, ASTB::bnd, i, ASTB::one, SHD_LWB, SHD_NDIM, sptr, and update_shape_info_expr().
Referenced by update_shape_info(), and update_shape_info_expr().
use_dummy_desc()
static void use_dummy_desc (void) static
Definition at line 1178 of file dpm_out.c.
References arg, aux, AUX::dpdsc_base, gbl, i, is_kopy_in_needed(), and NOSYM.
Referenced by transform_wrapup().
want_descriptor_anyway()
LOGICAL want_descriptor_anyway (int sptr)
Return TRUE if we need to initialize the descriptor for this symbol because perhaps this is a host subroutine, and the internal subprograms will need the descriptor, or perhaps -g is set.
Definition at line 932 of file dpm_out.c.
References ADD_ASSUMSHP, ADD_DEFER, ALIGNG, FLG::debug, DISTG, DTY, FALSE, flg, gbl, sptr, TRUE, and XBIT.
Referenced by conv_allocate(), desc_need_arrays(), prepare_for_astout(), and wrap_symbol().
wrap_symbol()
static void wrap_symbol (int sptr, int memberast, int basesptr) static
Definition at line 1244 of file dpm_out.c.
References add_auto_bounds(), add_auto_len(), ADD_LWAST, ADD_NUMDIM, ADD_UPAST, ALIGNG, ast, change_mk_id(), check_member(), DTY, emit_alnd(), emit_secd(), EntryStd, ExitStd, FALSE, gbl, i, is_kopy_in_needed(), is_tbp_or_final(), mem(), mk_allocate_scalar(), mk_deallocate_scalar(), mk_id(), mk_mem_allocate(), mk_mem_deallocate(), mk_member(), mk_triple(), ndim, NOSYM, RUNTIMEG, sptr, STD_NEXT, subscr, TRUE, void(), want_descriptor_anyway(), and wrap_symbol().
Referenced by transform_wrapup(), and wrap_symbol().
Variable Documentation
allocatable_freeing
int allocatable_freeing = 0 static
Definition at line 123 of file dpm_out.c.
Referenced by emit_alnd_secd().
avl
int avl
Definition at line 153 of file dpm_out.c.
base
gbientry* base
Definition at line 152 of file dpm_out.c.
Referenced by gen_ptr_in(), and gen_ptr_out().
change_mk_id_list
int change_mk_id_list static
Definition at line 1103 of file dpm_out.c.
Referenced by change_mk_id(), do_change_mk_id(), and init_change_mk_id().
currp
char* currp static
Definition at line 126 of file dpm_out.c.
Referenced by get_num(), and ipa_restore_dtb().
dtb
DTB dtb
Definition at line 130 of file dpm_out.c.
Referenced by dalnd(), dsecd(), free_dtb(), init_dtb(), ipa_restore_dtb(), make_alnd(), make_secd(), mk_dtb(), and rw_dpmout_state().
struct { ... } dynsh
EntryStd
int EntryStd = 0 static
Definition at line 119 of file dpm_out.c.
Referenced by add_auto_bounds(), add_bound_assignments(), allocate_one_auto(), emit_alnd(), emit_alnd_secd(), emit_kopy_in(), emit_redim(), emit_scalar_kopy_in(), emit_secd(), gen_ptr_in(), interface_for_entry(), interface_for_llvmiface(), newargs_for_entry(), redimension(), trans_mkproc(), transform_wrapup(), and wrap_symbol().
ExitStd
int ExitStd = 0 static
Definition at line 119 of file dpm_out.c.
Referenced by allocate_one_auto(), close_entry_guard(), emit_alnd_secd(), emit_kopy_in(), emit_scalar_kopy_in(), open_entry_guard(), transform_wrapup(), and wrap_symbol().
f77_local
int f77_local = 0 static
Definition at line 120 of file dpm_out.c.
Referenced by emit_kopy_in(), emit_scalar_kopy_in(), interface_for_entry(), needs_redim(), set_assumed_bounds(), set_assumsz_bound(), and transform_wrapup().
fl
FL fl
Definition at line 131 of file dpm_out.c.
Referenced by conv_allocate(), emit_fl(), finish_fl(), init_fl(), and pghpf_entry().
struct { ... } gbitable
Referenced by emit_kopy_in(), emit_redim(), and emit_scalar_kopy_in().
index
int index
Definition at line 153 of file dpm_out.c.
Referenced by __fort_show_index(), add_to_list(), advance(), advance_permuted(), do_eval_minval_or_maxval(), ENTF90(), ENTFTN(), eval_minval_or_maxval(), eval_reshape(), execute_actions_for_keyword(), exp_mac(), gen_extract_insert(), gen_gep_index(), gen_insert_value(), get_file_mdnode(), get_filedesc_mdnode(), get_offset_without_dim(), incr_index(), is_xflag_bitvector(), ll_create_sym(), ll_set_function_argument(), lldbg_create_file_mdnode(), maybe_do_gep_folding(), mkrtemp_arg1_sc(), mkrtemp_cpx_sc(), mkrtemp_sc(), mth_i_alog(), mth_i_atan2(), mth_i_datan2(), mth_i_dlog(), mth_i_log(), newbas(), next_index(), par_xref(), set_xflag_value(), store_element(), unset_xflag_value(), and xref().
make_secd_flag
int* make_secd_flag static
Definition at line 127 of file dpm_out.c.
Referenced by make_secd_for_members(), and share_secd().
new_dscptr_g
int new_dscptr_g static
Definition at line 124 of file dpm_out.c.
Referenced by transform_wrapup().
orderargs
int* orderargs static
Definition at line 2692 of file dpm_out.c.
Referenced by interface_for_entry(), interface_for_llvmiface(), and reorder_args().
realign
int realign = 0 static
Definition at line 122 of file dpm_out.c.
Referenced by emit_alnd(), emit_secd(), and ENTFTN().
redistribute
int redistribute = 0 static
Definition at line 121 of file dpm_out.c.
Referenced by emit_alnd(), emit_secd(), and ENTFTN().
size
int size
Definition at line 153 of file dpm_out.c.
stg_avail
int stg_avail
Definition at line 141 of file dpm_out.c.
Referenced by flowgraph().
stg_base
DYNSH* stg_base
Definition at line 140 of file dpm_out.c.
Referenced by flowgraph().
stg_size
int stg_size
Definition at line 141 of file dpm_out.c.
Referenced by flowgraph().
this_entry_fval
int this_entry_fval = 0 static
Definition at line 125 of file dpm_out.c.
Referenced by add_bound_assignments(), interface_for_entry(), and interface_for_llvmiface().
this_entry_g
int this_entry_g static
Definition at line 124 of file dpm_out.c.
Referenced by emit_target_alnd(), and transform_wrapup().
typed_alloc
DTYPE typed_alloc = DT_NONE static
Definition at line 128 of file dpm_out.c.
Referenced by emit_alnd(), emit_secd(), and set_typed_alloc().
unconditional
int unconditional
Definition at line 153 of file dpm_out.c.