flang: dround.c File Reference
dround.c File Reference
#include "mthdecls.h"
Functions
double round (double)
double __mth_i_dround (double x)
Function Documentation
__mth_i_dround()
double __mth_i_dround (double x)
Definition at line 13 of file dround.c.
References round(), and x.
Referenced by __nearbyint().
round()
double round (double)
Referenced by __fortio_default_convert(), __fortio_ecvt(), __fortio_fcvt(), __fortio_fmt_d(), __fortio_fmt_e(), __fortio_fmt_f(), __fortio_fmt_g(), __INT_T(), __mth_i_dround(), ENTF90IO(), and manrnd().