flang: dsincosp.c File Reference
dsincosp.c File Reference
#include "libm_amd.h"
#include "libm_util_amd.h"
#include "libm_inlines_amd.h"
Macros
#define USE_REMAINDER_PIBY2_INLINE
#define USE_NAN_WITH_FLAGS
#define USE_VAL_WITH_FLAGS
#define USE_HANDLE_ERROR
Functions
static double sin_piby4 (double x, double xx)
static double cos_piby4 (double x, double xx)
void FN_PROTOTYPE() mth_dsincos (double x, double *s, double *c)
double FN_PROTOTYPE() mth_i_dsin (double x)
double FN_PROTOTYPE() mth_i_dcos (double x)
Macro Definition Documentation
USE_HANDLE_ERROR
#define USE_HANDLE_ERROR
Definition at line 49 of file dsincosp.c.
USE_NAN_WITH_FLAGS
#define USE_NAN_WITH_FLAGS
Definition at line 47 of file dsincosp.c.
USE_REMAINDER_PIBY2_INLINE
#define USE_REMAINDER_PIBY2_INLINE
Definition at line 46 of file dsincosp.c.
USE_VAL_WITH_FLAGS
#define USE_VAL_WITH_FLAGS
Definition at line 48 of file dsincosp.c.
Function Documentation
cos_piby4()
static double cos_piby4 (double x, double xx) inline static
Definition at line 89 of file dsincosp.c.
References r, t, x, and x2.
Referenced by mth_dsincos(), mth_i_dcos(), and mth_i_dsin().
mth_dsincos()
void FN_PROTOTYPE() mth_dsincos (double x, double * s, double * c)
Definition at line 118 of file dsincosp.c.
References AMD_F_INEXACT, AMD_F_INVALID, cos_piby4(), EXPBITS_DP64, EXPSHIFTBITS_DP64, GET_BITS_DP64, MANTBITS_DP64, r, s, sin_piby4(), t, x, and xneg.
mth_i_dcos()
double FN_PROTOTYPE() mth_i_dcos (double x)
Definition at line 391 of file dsincosp.c.
References AMD_F_INEXACT, AMD_F_INVALID, cos_piby4(), EXPBITS_DP64, EXPSHIFTBITS_DP64, GET_BITS_DP64, MANTBITS_DP64, r, sin_piby4(), t, x, and xneg.
mth_i_dsin()
double FN_PROTOTYPE() mth_i_dsin (double x)
Definition at line 268 of file dsincosp.c.
References AMD_F_INEXACT, AMD_F_INVALID, cos_piby4(), EXPBITS_DP64, EXPSHIFTBITS_DP64, GET_BITS_DP64, MANTBITS_DP64, r, sin_piby4(), t, x, and xneg.
sin_piby4()
static double sin_piby4 (double x, double xx) inline static
Definition at line 58 of file dsincosp.c.
References r, x, x2, and x3.
Referenced by mth_dsincos(), mth_i_dcos(), and mth_i_dsin().