flang: dtypeutl.cpp File Reference
dtypeutl.cpp File Reference
data type utility functions.
#include "dtypeutl.h"
#include "machar.h"
#include "machardf.h"
#include "symfun.h"
Classes
struct visit_list
struct chartab
Macros
#define CHARTABSIZE 40
#define _VP 3
#define _FP ((4 * sizeof(int) + sizeof(char *)) / sizeof(int))
#define ALIGNSIZE ((sizeof(struct getpointeralign) - sizeof(char *) - 1) / sizeof(int))
#define DEFAULT_DIM_SIZE 127
#define SS2 0x8e
#define SS3 0x8f
#define IS_COMMON_VAR(sptr)
Typedefs
typedef bool(* stm_predicate_t) (int member_sptr, struct visit_list **visited)
typedef struct chartab CHARTAB
Functions
static struct visit_list * visit_list_scan (struct visit_list *list, DTYPE dtype)
static void visit_list_push (struct visit_list **list, DTYPE dtype)
static void visit_list_free (struct visit_list **list)
static bool is_recursive (int sptr, struct visit_list **visited)
static TY_KIND get_ty_kind (DTYPE dtype)
bool is_array_dtype (DTYPE dtype)
...
DTYPE array_element_dtype (DTYPE dtype)
if array datatype, returns the element dtype, else returns dtype
static bool is_container_dtype (DTYPE dtype)
static bool search_type_members (DTYPE dtype, stm_predicate_t predicate, struct visit_list **visited)
bool is_empty_typedef (DTYPE dtype)
Check for special case of empty typedef which has a size of 0 but one member of type DT_NONE to indicate that the type is empty and not incomplete, a forward reference, etc.
bool is_zero_size_typedef (DTYPE dtype)
Check for special case of zero-size typedef which may nest have zero-size typedef compnents or zero-size array compnents.
static bool no_data_components_recursive (DTYPE dtype, struct visit_list **visited)
bool no_data_components (DTYPE dtype)
...
static ISZ_T _size_of (DTYPE dtype)
ISZ_T size_of (DTYPE dtype)
...
ISZ_T zsize_of (DTYPE dtype)
...
ISZ_T size_of_sym (SPTR sym)
...
int dlen (TY_KIND dty)
Return the length, in stb.dt.stg_base words, of each type of datatype entry.
int align_bytes2mask (int bytes)
int align_bytes2power (int bytes)
int align_mask2bytes (int mask)
int align_mask2power (int mask)
int align_power2bytes (int power)
int align_power2mask (int power)
int alignment (DTYPE dtype)
...
int align_unconstrained (DTYPE dtype)
...
int alignment_sym (SPTR sym)
...
int align_of (DTYPE dtype)
Support the alignof operator.
void init_chartab (void)
...
void Save_Chartab (FILE *fil)
...
void Restore_Chartab (FILE *fil)
...
DTYPE get_type (int n, TY_KIND v1, int v2)
...
static void get_aux_arrdsc (DTYPE dtype, int numdim)
Create a dtype record for an array of rank numdim including its array descriptor.
DTYPE get_array_dtype (int numdim, DTYPE eltype)
Create a dtype record for an array of rank numdim including its array descriptor.
DTYPE get_vector_dtype (DTYPE dtype, int n)
...
bool cmpat_func (DTYPE d1, DTYPE d2)
Return true if the data types for two functions are compatible.
void getdtype (DTYPE dtype, char *ptr)
Put into the character array pointed to by ptr, the print representation of dtype.
ISZ_T extent_of (DTYPE dtype)
...
ISZ_T ad_val_of (int sym)
...
int get_bnd_con (ISZ_T v)
Create a constant sym entry which reflects the type of an array bound/extent.
ISZ_T get_bnd_cval (int con)
Given a constant symbol, return its numerical value.
static int _dmp_dent (DTYPE dtypeind, FILE *outfile)
int dmp_dent (DTYPE dtypeind)
...
void dmp_dtype (void)
...
int Scale_Of (DTYPE dtype, ISZ_T *size)
Compute the size of a data type.
int scale_of (DTYPE dtype, INT *size)
Compute the size of a data type.
int fval_of (DTYPE dtype)
Return 0 if reg, 1 if mem.
int kanji_len (unsigned char *p, int len)
Return number of kanji characters.
int kanji_char (unsigned char *p, int len, int *bytes)
Extract necessary bytes from character string in order to return integer (16-bit) representation of one kanji char.
int kanji_prefix (unsigned char *p, int newlen, int len)
Return number of bytes required for newlen chars.
bool is_overlap_cmblk_var (int sptr1, int sptr2)
Variables
static int size_sym = 0
static int nosize_ok = 0
static bool constrained = true
static int chartab [CHARTABSIZE]
static int chartabavail
static int chartabsize
static CHARTAB * chartabbase
Detailed Description
data type utility functions.
Definition in file dtypeutl.cpp.
Macro Definition Documentation
_FP
#define _FP ((4 * sizeof(int) + sizeof(char *)) / sizeof(int))
Definition at line 697 of file dtypeutl.cpp.
_VP
#define _VP 3
Definition at line 696 of file dtypeutl.cpp.
ALIGNSIZE
#define ALIGNSIZE ((sizeof(struct getpointeralign) - sizeof(char *) - 1) / sizeof(int))
CHARTABSIZE
#define CHARTABSIZE 40
Definition at line 571 of file dtypeutl.cpp.
DEFAULT_DIM_SIZE
#define DEFAULT_DIM_SIZE 127
IS_COMMON_VAR
#define IS_COMMON_VAR (sptr)
Value:
                            (SCG(sptr) == SC_CMBLK &&\
                            MODCMNG(MIDNUMG(sptr)) == 0)
Definition at line 1289 of file dtypeutl.cpp.
SS2
#define SS2 0x8e
Definition at line 1231 of file dtypeutl.cpp.
SS3
#define SS3 0x8f
Definition at line 1232 of file dtypeutl.cpp.
Typedef Documentation
CHARTAB
typedef struct chartab CHARTAB
Data structure to hold TY_CHAR entries: linked list off of array chartab; entries that are equal module CHARTABSIZE are linked. Relative pointers (integers) are used.
stm_predicate_t
typedef bool(* stm_predicate_t) (int member_sptr, struct visit_list **visited)
Definition at line 58 of file dtypeutl.cpp.
Function Documentation
_dmp_dent()
static int _dmp_dent (DTYPE dtypeind, FILE * outfile) static
Definition at line 953 of file dtypeutl.cpp.
References AD_DPTR, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_SCHECK, AD_SDSC, AD_UPBD, AD_ZBASE, aux, buf, AUX::dpdsc_base, STB::dt, DTY, DTyAlgTyAlign, DTyAlgTyInitCon, DTyAlgTyMember, DTyAlgTySize, DTyAlgTyTag, DTyArgNext, DTyArgSym, DTyArgType, DTyArrayDesc, DTyFuncVal, DTyInterface, DTyParamCount, DTyParamDesc, DTyParamList, DTyReturnType, DTySeqTyElement, DTyVecLength, ERR_Informational, ERR_Severe, get_getitem_p(), getdtype(), i, interr(), ISZ_PF, outfile, stb, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, and STB::tynames.
Referenced by dmp_dent().
_size_of()
static ISZ_T _size_of (DTYPE dtype) static
Definition at line 216 of file dtypeutl.cpp.
References AD_DPTR, AD_NUMELM, ad_val_of(), assert, d, DTY, DTyAlgTySize, DTyArrayDesc, DTyCharLength, DTySeqTyElement, DTyValidRange, DTyVecLength, ERR_Severe, errsev(), STB::i1, interr(), ISZ_T, STB::k1, nosize_ok, size_of(), size_sym, stb, sz, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, TY_SLOG, TY_WORD, val, and XBIT.
Referenced by size_of(), and zsize_of().
ad_val_of()
ISZ_T ad_val_of (int sym)
...
Definition at line 913 of file dtypeutl.cpp.
References CONVAL2G, get_isz_cval(), and XBIT.
Referenced by _size_of(), and extent_of().
align_bytes2mask()
int align_bytes2mask (int bytes)
Definition at line 431 of file dtypeutl.cpp.
align_bytes2power()
int align_bytes2power (int bytes)
Definition at line 437 of file dtypeutl.cpp.
Referenced by align_mask2power(), and make_arg_tmp().
align_mask2bytes()
int align_mask2bytes (int mask)
Definition at line 449 of file dtypeutl.cpp.
align_mask2power()
int align_mask2power (int mask)
Definition at line 455 of file dtypeutl.cpp.
References align_bytes2power().
align_of()
int align_of (DTYPE dtype)
Support the alignof operator.
Parameters
dtype
Definition at line 566 of file dtypeutl.cpp.
References alignment().
Referenced by align_of_var(), gen_arg_operand(), make_arg_tmp(), and make_stmt().
align_power2bytes()
int align_power2bytes (int power)
Definition at line 461 of file dtypeutl.cpp.
align_power2mask()
int align_power2mask (int power)
Definition at line 467 of file dtypeutl.cpp.
align_unconstrained()
int align_unconstrained (DTYPE dtype)
...
Align on the most strict boundary for a data type – used whenever we want to align unconstrained (top-level) objects such as simple local, static, and external variables. The alignment of struct of union variables is just the most strict alignment determined by alignment() of its members. The alignment of arrays is just the aligmnent of required for its element type.
Definition at line 547 of file dtypeutl.cpp.
References a, alignment(), and constrained.
Referenced by assn_static_off(), assn_stkoff(), max_align(), and sym_is_refd().
alignment()
int alignment (DTYPE dtype)
...
Definition at line 475 of file dtypeutl.cpp.
References alignment(), constrained, FLG::dalign, DTY, DTyAlgTyAlign, DTySeqTyElement, ERR_Severe, flg, interr(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, and XBIT.
Referenced by align_of(), align_unconstrained(), alignment(), and alignment_sym().
alignment_sym()
int alignment_sym (SPTR sym)
...
Definition at line 558 of file dtypeutl.cpp.
References alignment(), and TY_DBLE.
array_element_dtype()
DTYPE array_element_dtype (DTYPE dtype)
if array datatype, returns the element dtype, else returns dtype
Definition at line 76 of file dtypeutl.cpp.
References DTySeqTyElement, and is_array_dtype().
Referenced by is_container_dtype(), and search_type_members().
cmpat_func()
bool cmpat_func (DTYPE d1, DTYPE d2)
Return true if the data types for two functions are compatible.
Two functions are compatible if a single local variable can be used to hold their return values and therefore implying that the same return mechanism can be used for the functions.
Definition at line 768 of file dtypeutl.cpp.
References assert, DTY, and ERR_Severe.
dlen()
int dlen (TY_KIND dty)
Return the length, in stb.dt.stg_base words, of each type of datatype entry.
Return the length.
Definition at line 368 of file dtypeutl.cpp.
References TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
dmp_dent()
int dmp_dent (DTYPE dtypeind)
...
Definition at line 1089 of file dtypeutl.cpp.
References _dmp_dent(), and gbl.
Referenced by dmp_dtype().
dmp_dtype()
void dmp_dtype (void)
...
Definition at line 1095 of file dtypeutl.cpp.
References dmp_dent(), STB::dt, gbl, i, and stb.
extent_of()
ISZ_T extent_of (DTYPE dtype)
...
Compute total number of elements in this array - if a dimension is not known, estimate. We assume that we already know that dtype is an array reference (either an array or a pointer to an array)
Definition at line 865 of file dtypeutl.cpp.
References AD_DPTR, AD_LWBD, AD_NUMDIM, AD_UPBD, ad_val_of(), DEFAULT_DIM_SIZE, STB::dt, DTY, DTyArrayDesc, DTySeqTyElement, ERR_Informational, ERR_Severe, i, interr(), ISZ_T, size, and stb.
fval_of()
int fval_of (DTYPE dtype)
Return 0 if reg, 1 if mem.
Get FVAL field of a data type.
Definition at line 1220 of file dtypeutl.cpp.
References assert, DTY, DTyValidRange, and ERR_Severe.
get_array_dtype()
DTYPE get_array_dtype (int numdim, DTYPE eltype)
Create a dtype record for an array of rank numdim including its array descriptor.
...
Parameters
numdim number of dimensions
eltype data type of the array element
The layout of an array descriptor is:
    int    numdim;  --+
    int    zbase;     |
    UINT16 *ilmp;     |
    char   defer;     +-- 4 ints (fixed part)
    char   adjarr;    |
    char   assumsz;   |
    char   pad;     --+
    struct {
        int mlpyr;  --+
        int lwbd;     |
        int upbd;     +-- 6 ints (variable part)
        int lwast;    |
        int upast;    |
        int exntnast;-+
    } b[numdim];
    int    numelm;  --+-- 1 int
Any change in the size of the structure requires a change to one or both of the macros _FP and _VP. Also the size assertion in symtab.c needs to be changed.
Definition at line 748 of file dtypeutl.cpp.
References get_aux_arrdsc(), and get_type().
get_aux_arrdsc()
static void get_aux_arrdsc (DTYPE dtype, int numdim) static
Create a dtype record for an array of rank numdim including its array descriptor.
The layout of an array descriptor is:
   int    numdim;  --+
   int    scheck;    |
   int    zbase;  +-- 5 ints (fixed part)
   int    sdsc; |
   ILM_T  *ilmp;   --+   watch out if  pointers are 8 bytes.
   struct {
       int mlpyr;  --+
       int lwbd;  +-- 3 ints (variable part)
       int upbd;   --+
   } b[numdim];
   int    numlem;  --+-- 1 int after variable part.
Any change in the size of the structure requires a change to one or both of the macros _FP and _VP. Also the size assertion in symtab.c needs to be changed.
Definition at line 722 of file dtypeutl.cpp.
References _FP, _VP, AD_DPTR, AD_NUMDIM, ALIGN, ALIGNSIZE, AUX::arrdsc_avl, AUX::arrdsc_base, AUX::arrdsc_size, aux, BZERO, c, DTySetArrayDesc, and NEED.
Referenced by get_array_dtype().
get_bnd_con()
int get_bnd_con (ISZ_T v)
Create a constant sym entry which reflects the type of an array bound/extent.
Definition at line 921 of file dtypeutl.cpp.
References DT_INT, getcon(), ISZ_2_INT64, num, and XBIT.
get_bnd_cval()
ISZ_T get_bnd_cval (int con)
Given a constant symbol, return its numerical value.
Definition at line 935 of file dtypeutl.cpp.
References assert, CONVAL2G, DT_ISINT, ERR_unused, INT64_2_ISZ, and ISZ_T.
Referenced by ll_convert_array_dtype().
get_ty_kind()
static TY_KIND get_ty_kind (DTYPE dtype) static
Definition at line 61 of file dtypeutl.cpp.
References assert, DTY, DTyValidRange, and ERR_Severe.
Referenced by is_array_dtype().
get_type()
DTYPE get_type (int n, TY_KIND v1, int v2)
...
Find or allocate a slot in dtype array for the new datatype. For strings, check if the data type is already present.
Parameters
n number of datatype entries we want to occupy
v1 data type
v2 second value, meaning depends on data type, for strings it is the length, for pointers - target type, etc
Definition at line 660 of file dtypeutl.cpp.
References chartabavail, chartabbase, CHARTABSIZE, chartabsize, STB::dt, DTY, DTyCharLength, chartab::dtype, DTySet, DTySetFst, i, if(), j, k, n, NEED, chartab::next, stb, STG_NEXT_SIZE, TY_CHAR, and TY_NCHAR.
Referenced by get_array_dtype(), and get_vector_dtype().
get_vector_dtype()
DTYPE get_vector_dtype (DTYPE dtype, int n)
...
Definition at line 756 of file dtypeutl.cpp.
References aux, DTY, DTySetVecLength, get_type(), n, and AUX::vtypes.
Referenced by gen_binary_expr(), gen_llvm_expr(), gen_llvm_vsincos_call(), gen_resized_vect(), gen_scalar_to_vector_helper(), make_vtype(), and vect_math().
getdtype()
void getdtype (DTYPE dtype, char * ptr)
Put into the character array pointed to by ptr, the print representation of dtype.
Definition at line 782 of file dtypeutl.cpp.
References AD_DPTR, AD_LWBD, AD_NUMDIM, AD_UPBD, assert, STB::dt, DTY, DTyAlgTyTag, DTyArrayDesc, DTyCharLength, DTySeqTyElement, DTyVecLength, ERR_Informational, ERR_Severe, getprint(), i, interr(), NOSYM, p, stb, strlen(), SYMNAME, TY_CHAR, TY_NCHAR, and STB::tynames.
Referenced by _dmp_dent().
init_chartab()
void init_chartab (void)
...
Definition at line 588 of file dtypeutl.cpp.
References chartabavail, chartabbase, CHARTABSIZE, chartabsize, chartab::dtype, i, NEW, and chartab::next.
is_array_dtype()
bool is_array_dtype (DTYPE dtype)
...
Definition at line 70 of file dtypeutl.cpp.
References get_ty_kind().
Referenced by array_element_dtype(), is_container_dtype(), is_zero_size_typedef(), and search_type_members().
is_container_dtype()
static bool is_container_dtype (DTYPE dtype) static
Definition at line 82 of file dtypeutl.cpp.
References array_element_dtype(), DTYG, and is_array_dtype().
Referenced by search_type_members().
is_empty_typedef()
bool is_empty_typedef (DTYPE dtype)
Check for special case of empty typedef which has a size of 0 but one member of type DT_NONE to indicate that the type is empty and not incomplete, a forward reference, etc.
Check for special case of empty typedef which has a size of 0 but one member of type DT_NONE to indicate that the type is empty and not incomplete, a forward reference, etc.
Definition at line 131 of file dtypeutl.cpp.
References DTY, DTyAlgTyMember, mem(), and NOSYM.
Referenced by no_data_components_recursive().
is_overlap_cmblk_var()
bool is_overlap_cmblk_var (int sptr1, int sptr2)
Definition at line 1294 of file dtypeutl.cpp.
References getsymbol(), IS_COMMON_VAR, size_of_sym(), and SYMNAME.
Referenced by conflict().
is_recursive()
static bool is_recursive (int sptr, struct visit_list ** visited) static
Definition at line 155 of file dtypeutl.cpp.
References is_recursive(), NOSYM, search_type_members(), and sptr.
Referenced by is_recursive(), and search_type_members().
is_zero_size_typedef()
bool is_zero_size_typedef (DTYPE dtype)
Check for special case of zero-size typedef which may nest have zero-size typedef compnents or zero-size array compnents.
Definition at line 142 of file dtypeutl.cpp.
References DTY, DTyAlgTySize, DTySeqTyElement, and is_array_dtype().
kanji_char()
int kanji_char (unsigned char * p, int len, int * bytes)
Extract necessary bytes from character string in order to return integer (16-bit) representation of one kanji char.
Parameters
p ptr to EUC string
len number of bytes in p
bytes return number of EUC bytes used up
Definition at line 1257 of file dtypeutl.cpp.
References len, p, SS2, SS3, and val.
Referenced by kanji_prefix().
kanji_len()
int kanji_len (unsigned char * p, int len)
Return number of kanji characters.
Get number of kanji characters.
Parameters
p character string
len length in bytes of p
Definition at line 1235 of file dtypeutl.cpp.
References count, len, p, SS2, SS3, and val.
kanji_prefix()
int kanji_prefix (unsigned char * p, int newlen, int len)
Return number of bytes required for newlen chars.
Get number of bytes needed for kanji characters in string prefix.
Parameters
p ptr to EUC string
newlen number of kanji chars required from string prefix
len total number of bytes in string
Definition at line 1274 of file dtypeutl.cpp.
References kanji_char(), len, p, and void().
no_data_components()
bool no_data_components (DTYPE dtype)
...
Definition at line 205 of file dtypeutl.cpp.
References no_data_components_recursive(), NULL, result, and visit_list_free().
no_data_components_recursive()
static bool no_data_components_recursive (DTYPE dtype, struct visit_list ** visited) static
For the derived type in dtype: Returns true if dtype is empty or if it does not contain any data components (i.e., a derived type with type bound procedures returns false). Otherwise, returns false.
Definition at line 166 of file dtypeutl.cpp.
References DTY, DTyAlgTyMember, DTySeqTyElement, visit_list::is_active, is_empty_typedef(), mem(), no_data_components_recursive(), NOSYM, visit_list_push(), and visit_list_scan().
Referenced by no_data_components(), and no_data_components_recursive().
Restore_Chartab()
void Restore_Chartab (FILE * fil)
...
Definition at line 637 of file dtypeutl.cpp.
References chartabavail, chartabbase, CHARTABSIZE, chartabsize, ERR_Fatal, error(), and NEED.
Save_Chartab()
void Save_Chartab (FILE * fil)
...
Definition at line 616 of file dtypeutl.cpp.
References chartabavail, chartabbase, CHARTABSIZE, ERR_Fatal, and error().
scale_of()
int scale_of (DTYPE dtype, INT * size)
Compute the size of a data type.
...
This machine dependent routine computes the size of a data type in terms of two quantities:
size - number of elements in the data type (returned thru size).
scale - number of bytes in each element, expressed as a power of two (the return value of scale_of).
This routine will be used to take advantage of the machines that have the ability to add a scaled expression (multiplied by a power of two) to an address. This is particularly useful for incrementing a pointer variable and array subscripting.
Note that for those machines that do not have this feature, scale_of returns a scale of 0 and size_of for size.
Definition at line 1209 of file dtypeutl.cpp.
References ISZ_T, scale, Scale_Of(), and size.
Scale_Of()
int Scale_Of (DTYPE dtype, ISZ_T * size)
Compute the size of a data type.
Parameters
dtype
size number of elements in the data type [output]
Returns
number of bytes in each element, expressed as a power of two (scale)
This machine dependent routine computes the size of a data type in terms of two quantities: the size and the scale
This routine will be used to take advantage of the machines that have the ability to add a scaled expression (multiplied by a power of two) to an address. This is particularly useful for incrementing a pointer variable and array subscripting.
Note that for those machines that do not have this feature, scale_of returns a scale of 0 and size_of for size.
Definition at line 1111 of file dtypeutl.cpp.
References assert, d, DTY, DTyAlgTySize, DTyArrayDesc, DTyCharLength, DTySeqTyElement, DTySetArrayDesc, DTyValidRange, DTyVecLength, ERR_Severe, interr(), ISZ_T, scale, Scale_Of(), size, tmp, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by compute_sdsc_subscr(), inlarr(), scale_of(), and Scale_Of().
search_type_members()
static bool search_type_members (DTYPE dtype, stm_predicate_t predicate, struct visit_list ** visited) static
Definition at line 99 of file dtypeutl.cpp.
References array_element_dtype(), DTyAlgTyMember, visit_list::is_active, is_array_dtype(), is_container_dtype(), is_recursive(), NOSYM, predicate(), result, visit_list_push(), and visit_list_scan().
Referenced by is_recursive().
size_of()
ISZ_T size_of (DTYPE dtype)
...
Definition at line 334 of file dtypeutl.cpp.
References _size_of().
Referenced by _size_of(), and size_of_sym().
size_of_sym()
ISZ_T size_of_sym (SPTR sym)
...
Definition at line 350 of file dtypeutl.cpp.
References ERR_Severe, error(), gbl, ISZ_T, NULL, size_of(), size_sym, SYMNAME, and sz.
Referenced by get_ag(), is_overlap_cmblk_var(), llmp_task_add_private(), and max_align().
visit_list_free()
static void visit_list_free (struct visit_list ** list) static
Definition at line 48 of file dtypeutl.cpp.
References FREE, list, and p.
Referenced by no_data_components().
visit_list_push()
static void visit_list_push (struct visit_list ** list, DTYPE dtype) static
Definition at line 37 of file dtypeutl.cpp.
References visit_list::dtype, visit_list::is_active, list, NEW, and visit_list::next.
Referenced by no_data_components_recursive(), and search_type_members().
visit_list_scan()
static struct visit_list * visit_list_scan (struct visit_list * list, DTYPE dtype) static
Definition at line 27 of file dtypeutl.cpp.
References list.
Referenced by no_data_components_recursive(), and search_type_members().
zsize_of()
ISZ_T zsize_of (DTYPE dtype)
...
Definition at line 340 of file dtypeutl.cpp.
References _size_of(), d, ISZ_T, and nosize_ok.
Referenced by _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_mp_atomic_write(), align_of_var(), amd64_classify(), amd64_coerce(), amd64_update_class(), can_use_rmw(), check_vector_registers(), classify_int(), exp_smp(), gen_call_expr(), gen_call_vminmax_intrinsic(), gen_call_vminmax_neon_intrinsic(), gen_call_vminmax_power_intrinsic(), gen_llvm_expr(), ll_abi_classify_arg_dtype(), ll_abi_classify_return_dtype(), lldbg_emit_type(), lldbg_get_bounds_for_assumed_rank_sdsc(), lldbg_get_bounds_for_sdsc(), lldbg_get_sizeof(), llmp_task_add_loopvar(), llmp_task_add_private(), make_stmt(), msz_from_atomic_dtype(), setTaskloopVars(), and update_homogeneous().
Variable Documentation
chartab
int chartab[CHARTABSIZE] static
Definition at line 572 of file dtypeutl.cpp.
chartabavail
int chartabavail static
Definition at line 583 of file dtypeutl.cpp.
Referenced by get_type(), init_chartab(), Restore_Chartab(), and Save_Chartab().
chartabbase
CHARTAB* chartabbase static
Definition at line 585 of file dtypeutl.cpp.
Referenced by get_type(), init_chartab(), Restore_Chartab(), and Save_Chartab().
chartabsize
int chartabsize static
Definition at line 584 of file dtypeutl.cpp.
Referenced by get_type(), init_chartab(), and Restore_Chartab().
constrained
bool constrained = true static
Definition at line 472 of file dtypeutl.cpp.
Referenced by align_unconstrained(), and alignment().
nosize_ok
int nosize_ok = 0 static
Definition at line 213 of file dtypeutl.cpp.
Referenced by _size_of(), and zsize_of().
size_sym
int size_sym = 0 static
Definition at line 17 of file dtypeutl.cpp.
Referenced by _size_of(), and size_of_sym().