flang: dtypeutl.c File Reference
dtypeutl.c File Reference
Fortran data type utility functions.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "dtypeutl.h"
#include "machar.h"
#include "machardf.h"
#include "ast.h"
#include "rte.h"
#include "symutl.h"
Classes
struct visit_list
struct chartab
Macros
#define CHARTABSIZE 40
#define SS2 0x8e
#define SS3 0x8f
#define _FP 4
#define _VP 6
#define RW_FD(b, s, n)
Typedefs
typedef LOGICAL(* stm_predicate_t) (int member_sptr, struct visit_list **visited)
Enumerations
enum _pghpf_type {
__NONE = 0 , __SHORT = 1 , __USHORT = 2 , __INT = 3 ,
__UINT = 4 , __LONG = 5 , __ULONG = 6 , __FLOAT = 7 ,
__DOUBLE = 8 , __CPLX = 9 , __DCPLX = 10 , __CHAR = 11 ,
__UCHAR = 12 , __LONGDOUBLE = 13 , __STR = 14 , __LONGLONG = 15 ,
__ULONGLONG = 16 , __BLOG = 17 , __SLOG = 18 , __LOG = 19 ,
__LOG8 = 20 , __WORD = 21 , __DWORD = 22 , __NCHAR = 23 ,
__INT2 = 24 , __INT4 = 25 , __INT8 = 26 , __REAL2 = 45 ,
__REAL4 = 27 , __REAL8 = 28 , __REAL16 = 29 , __CPLX32 = 30 ,
__WORD16 = 31 , __INT1 = 32 , __DERIVED = 33 , __PROC = 34 ,
__DESC = 35 , __SKED = 36 , __M128 = 37 , __M256 = 38 ,
__INT16 = 39 , __LOG16 = 40 , __QREAL16 = 41 , __QCPLX32 = 42 ,
__POLY = 43 , __PROCPTR = 44 , __NTYPES = 46
}
Functions
static TY_KIND get_ty_kind (DTYPE)
static LOGICAL get_kind_set_parm (int, DTYPE, int *)
static int get_len_set_parm (int, DTYPE, int *)
static DTYPE get_iso_derivedtype (DTYPE)
static DTYPE get_cuf_derivedtype (DTYPE)
static int ic_strcmp (const char *str, const char *pattern)
Compare str and pattern like strcmp() but ignoring the case of str. pattern is all lower case.
const char * target_name (DTYPE dtype)
int target_kind (DTYPE dtype)
ISZ_T size_of (DTYPE dtype)
...
int string_length (DTYPE dtype)
Return length of constant char string data type.
static struct visit_list * visit_list_scan (struct visit_list *list, DTYPE dtype)
static void visit_list_push (struct visit_list **list, DTYPE dtype)
static void visit_list_free (struct visit_list **list)
static LOGICAL is_container_dtype (DTYPE dtype)
static LOGICAL is_recursive (int sptr, struct visit_list **visited)
static LOGICAL search_type_members (DTYPE dtype, stm_predicate_t predicate, struct visit_list **visited)
static LOGICAL search_type_members_wrapped (DTYPE dtype, stm_predicate_t predicate)
static LOGICAL test_sym_and_components (int sptr, stm_predicate_t predicate)
static LOGICAL test_sym_components_only (int sptr, stm_predicate_t predicate)
LOGICAL is_empty_typedef (DTYPE dtype)
Check for special case of empty typedef which has a size of 0 but one member of type DT_NONE to indicate that the type is empty and not incomplete, a forward reference, etc.
LOGICAL is_zero_size_typedef (DTYPE dtype)
Check for special case of zero-size typedef which may nest have zero-size typedef compnents or zero-size array compnents.
static LOGICAL is_recursive_dtype (int sptr, struct visit_list **visited)
static bool no_data_components_recursive (DTYPE dtype, stm_predicate_t predicate, struct visit_list **visited)
LOGICAL no_data_components (DTYPE dtype)
...
ISZ_T size_of_var (int sptr)
Return the size of this variable, taking into account such things like whether the variable is a pointer.
INT size_ast (int sptr, DTYPE dtype)
INT size_ast_of (int ast, DTYPE dtype)
Like size_ast(), but pass an AST, allowing for member references.
INT string_expr_length (int ast)
DTYPE adjust_ch_length (DTYPE dtype, int ast)
Change dtype from assumed-length to length of ast.
DTYPE fix_dtype (int sptr, DTYPE dtype)
Fix array and char dtypes.
ISZ_T extent_of (DTYPE dtype)
...
DTYPE dtype_with_shape (DTYPE dtype, int shape)
ISZ_T ad_val_of (int sym)
...
int get_bnd_con (ISZ_T v)
Create a constant sym entry which reflects the type of an array bound/extent.
int alignment (DTYPE dtype)
...
int alignment_of_var (int sptr)
Like alignment(), but takes into account whether the var is a pointer.
int bits_in (DTYPE dtype)
void init_chartab (void)
...
void fini_chartab ()
DTYPE get_type (int n, TY_KIND v1, int v2)
...
LOGICAL cmpat_func (DTYPE d1, DTYPE d2)
Return true if the data types for two functions are compatible.
LOGICAL tk_match_arg (int formal_dt, int actual_dt, LOGICAL flag)
Return TRUE if the scalar data types of an actual argument matches the formal with respect to the type & kind rules.
LOGICAL eq_dtype2 (DTYPE d1, DTYPE d2, LOGICAL flag)
In the presence of modules and interface blocks, it's possible that two identical derived types are not represented by the same data type record. If this occurs, eq_dtype() will check the types of the members.
LOGICAL eq_dtype (DTYPE d1, DTYPE d2)
LOGICAL same_ancestor (DTYPE dtype1, DTYPE dtype2)
Check to see if two types are extensions from the same ancestor.
LOGICAL has_recursive_component (int sptr)
static LOGICAL is_finalized (int sptr, struct visit_list **visited)
LOGICAL has_finalized_component (SPTR sptr)
static LOGICAL is_impure_finalizer (int sptr, struct visit_list **visited)
LOGICAL has_impure_finalizer (SPTR sptr)
static LOGICAL is_layout_desc (SPTR sptr, struct visit_list **visited)
LOGICAL has_layout_desc (SPTR sptr)
static LOGICAL is_poly (SPTR sptr, struct visit_list **visited)
LOGICAL is_or_has_poly (SPTR sptr)
static LOGICAL is_derived_type_allo (SPTR sptr, struct visit_list **visited)
LOGICAL is_or_has_derived_allo (SPTR sptr)
LOGICAL cmpat_dtype (DTYPE d1, DTYPE d2)
Similar to eq_dtype(), except all scalar integer types are compatible with each other, all scalar logical types are compatible with each other, all character types are compatible with each other.
LOGICAL cmpat_dtype_with_size (DTYPE d1, DTYPE d2)
Similar to compat_dtype(), except all scalar integer types are compatible with each other, all scalar logical types are compatible with each other, all character types are compatible with each other. Also, array extents are checked.
LOGICAL same_dtype (DTYPE d1, DTYPE d2)
Similar to eq_dtype(), except types must match exactly, and derived types must be SEQUENCE and match in name also. Also, array extents are checked.
LOGICAL cmpat_dtype_array_cast (DTYPE d1, DTYPE d2)
Similar to eq_dtype(), except all scalar integer types are compatible with each other, all scalar logical types are compatible with each other, all character types are compatible with each other and we allow casting arrays when types fit into each other.
static int priority (int op)
static int leftparens (int ast, int astleft)
static int rightparens (int ast, int astright)
static void getop (int op, char *string)
void getast (int ast, char *string)
Given an AST and a string pointer, append a printable representation of the AST expression onto the string.
bool is_deferlenchar_ast (int ast)
Check if ast is deferred-length character
bool is_deferlenchar_dtype (DTYPE dtype)
Check if dtype is deferred-length character.
void getdtype (DTYPE dtype, char *ptr)
Put into the character array pointed to by ptr, the print representation of dtype.
void dmp_dtype (void)
...
int dlen (int ty)
int _dmp_dent (DTYPE dtypeind, FILE *outfile)
int dmp_dent (DTYPE dtypeind)
...
void pr_dent (DTYPE dt, FILE *f)
void dumpdtype (DTYPE dtype)
...
int scale_of (DTYPE dtype, INT *size)
Compute the size of a data type.
int fval_of (DTYPE dtype)
Return 0 if reg, 1 if mem.
int kanji_len (unsigned char *p, int len)
Return number of kanji characters.
int kanji_char (unsigned char *p, int len, int *bytes)
Extract necessary bytes from character string in order to return integer (16-bit) representation of one kanji char.
int kanji_prefix (unsigned char *p, int newlen, int len)
Return number of bytes required for newlen chars.
DTYPE get_array_dtype (int numdim, DTYPE eltype)
Create a dtype record for an array of rank numdim including its array descriptor.
void get_aux_arrdsc (DTYPE dtype, int numdim)
DTYPE dup_array_dtype (DTYPE o_dt)
Duplicate a dtype array record and its array descriptor.
DTYPE reduc_rank_dtype (DTYPE o_dt, DTYPE elem_dt, int astdim, int after)
Duplicate a dtype array record and its array descriptor, excluding a dimension.
int rank_of (DTYPE dtype)
Return number of dimensions of array dtype.
int rank_of_sym (int sptr)
Return number of dimensions of symbol sptr.
int lbound_of (DTYPE dtype, int dim)
Return AST representing the lower bound of array dtype for dimension dim (dim is relative to 0).
int lbound_of_sym (int sptr, int dim)
Return AST representing the lower bound of array symbol for dimension dim (dim is relative to 0).
int ubound_of (DTYPE dtype, int dim)
Return AST representing the upper bound of array dtype for dimension dim (dim is relative to 0).
int ubound_of_sym (int sptr, int dim)
Return AST representing the upper bound of array symbol for dimension dim (dim is relative to 0).
LOGICAL conformable (DTYPE d1, DTYPE d2)
Return true if the data types for two arrays are conformable (have the same shape). Shape is defined to be the rank and the extents of each dimension.
int dtype_to_arg (DTYPE dtype)
Map compiler's DT_ values to the values expected by the run-time.
int kind_of (DTYPE d1)
For intrinsic types, return same value as the KIND intrinsic.
LOGICAL same_type_different_kind (DTYPE d1, DTYPE d2)
LOGICAL different_type_same_kind (DTYPE d1, DTYPE d2)
void rw_dtype_state (int(*p_rw)(void *, size_t, size_t, FILE *), FILE *fd)
static LOGICAL is_tbp_component (int sptr, struct visit_list **visited)
LOGICAL has_tbp (DTYPE dtype)
static LOGICAL is_tbp_or_final_component (int sptr, struct visit_list **visited)
LOGICAL has_tbp_or_final (DTYPE dtype)
int chk_kind_parm_set_expr (int ast, DTYPE dtype)
void chkstruct (DTYPE dtype)
Compute size and alignment of struct and union types and their members.
DTYPE is_iso_cptr (DTYPE d_dtype)
...
LOGICAL is_iso_c_ptr (DTYPE d_dtype)
LOGICAL is_iso_c_funptr (DTYPE d_dtype)
LOGICAL is_cuf_c_devptr (DTYPE d_dtype)
DTYPE get_iso_ptrtype (const char *name)
DTYPE get_iso_c_ptr (void)
LOGICAL is_array_dtype (DTYPE dtype)
...
DTYPE array_element_dtype (DTYPE dtype)
if array datatype, returns the element dtype, else returns dtype
LOGICAL is_dtype_runtime_length_char (DTYPE dtype)
LOGICAL is_dtype_unlimited_polymorphic (DTYPE dtype)
LOGICAL is_procedure_ptr_dtype (DTYPE dtype)
Test if a data type index corresponds with a procedure pointer.
DTYPE proc_ptr_result_dtype (DTYPE dtype)
Get return type from a procedure pointer dtype.
void set_proc_ptr_result_dtype (DTYPE ptr_dtype, DTYPE result_dtype)
Set return type for a procedure pointer.
void set_proc_ptr_param_count_dtype (DTYPE ptr_dtype, int param_count)
Set paramter count for a procedure pointer type.
LOGICAL is_procedure_dtype (DTYPE dtype)
Test if a data type index corresponds with a procedure.
void set_proc_result_dtype (DTYPE proc_dtype, DTYPE result_dtype)
Set return type for a procedure type.
void set_proc_param_count_dtype (DTYPE proc_dtype, int param_count)
Set paramter count for a procedure type.
static int get_struct_dtype_field (DTYPE dtype, int offset, int default_result)
SPTR get_struct_tag_sptr (DTYPE dtype)
SPTR get_struct_members (DTYPE dtype)
int get_struct_initialization_tree (DTYPE dtype)
LOGICAL is_unresolved_parameterized_dtype (DTYPE dtype)
DTYPE change_assumed_char_to_deferred (DTYPE dtype)
Variables
static int size_sym = 0
static int chartab [CHARTABSIZE]
static int chartabavail
static int chartabsize
static struct chartab * chartabbase = 0
int ty_to_lib []
static int ty_to_base_ty []
Detailed Description
Fortran data type utility functions.
Definition in file dtypeutl.c.
Macro Definition Documentation
_FP
#define _FP 4
Definition at line 3128 of file dtypeutl.c.
_VP
#define _VP 6
Definition at line 3129 of file dtypeutl.c.
CHARTABSIZE
#define CHARTABSIZE 40
Definition at line 1335 of file dtypeutl.c.
RW_FD
#define RW_FD (b, s, n)
Value:
  {                                            \
    nw = (*p_rw)((char *)b, sizeof(s), n, fd); \
    if (nw != (n))                             \
      error(10, 40, 0, "(state file)", CNULL); \
  }
Definition at line 3667 of file dtypeutl.c.
SS2
#define SS2 0x8e
Definition at line 3055 of file dtypeutl.c.
SS3
#define SS3 0x8f
Definition at line 3056 of file dtypeutl.c.
Typedef Documentation
stm_predicate_t
typedef LOGICAL(* stm_predicate_t) (int member_sptr, struct visit_list **visited)
Definition at line 318 of file dtypeutl.c.
Enumeration Type Documentation
_pghpf_type
enum _pghpf_type
Enumerator
__NONE
__SHORT
__USHORT
__INT
__UINT
__LONG
__ULONG
__FLOAT
__DOUBLE
__CPLX
__DCPLX
__CHAR
__UCHAR
__LONGDOUBLE
__STR
__LONGLONG
__ULONGLONG
__BLOG
__SLOG
__LOG
__LOG8
__WORD
__DWORD
__NCHAR
__INT2
__INT4
__INT8
__REAL2
__REAL4
__REAL8
__REAL16
__CPLX32
__WORD16
__INT1
__DERIVED
__PROC
__DESC
__SKED
__M128
__M256
__INT16
__LOG16
__QREAL16
__QCPLX32
__POLY
__PROCPTR
__NTYPES
Definition at line 3451 of file dtypeutl.c.
Function Documentation
_dmp_dent()
int _dmp_dent (DTYPE dtypeind, FILE * outfile)
Definition at line 2779 of file dtypeutl.c.
References AD_ADJARR, AD_ASSUMRANK, AD_ASSUMSHP, AD_ASSUMSZ, AD_DEFER, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_MLPYR, AD_NOBOUNDS, AD_NUMDIM, AD_NUMELM, AD_UPAST, AD_UPBD, AD_ZBASE, aux, BIGIPFSZ, buf, AUX::dpdsc_base, STB::dt, DTY, get_getitem_p(), getdtype(), i, ISZ_PF, NULL, outfile, stb, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, and STB::tynames.
Referenced by dmp_dent(), and pr_dent().
ad_val_of()
ISZ_T ad_val_of (int sym)
...
Definition at line 1182 of file dtypeutl.c.
References CONVAL2G, INT64_2_ISZ, ISZ_T, num, and XBIT.
Referenced by compute_size_expr(), create_array_ref(), create_array_subscr(), dinit_subs(), dinit_varref(), dtype_with_shape(), eval_const_array_section(), eval_max(), eval_min(), eval_minval_or_maxval(), eval_reshape(), eval_sub_index(), eval_transfer(), fill_adjustable_array_dtype(), fill_argt_with_alnd(), fill_fixed_array_dtype(), finish_array(), fixup_param_vars(), get_dim_size(), get_ftn_cbind_lltype(), get_shape_arraydtype(), init_sdsc_bounds(), init_subrange_bound(), init_subrange_bound_pre11(), inlarr(), lldbg_emit_type(), make_lltype_from_sptr(), mk_extent(), mk_extent_expr(), mk_shared_extent(), mkarglist(), mkeffadr(), put_adjarr_bounds(), semant1(), should_preserve_param(), size_ast(), size_ast_of(), size_of_array(), small_shape(), stride_one(), and trav_struct().
adjust_ch_length()
DTYPE adjust_ch_length (DTYPE dtype, int ast)
Change dtype from assumed-length to length of ast.
Definition at line 927 of file dtypeutl.c.
References ast, DDTG, DTY, get_type(), len, and string_expr_length().
Referenced by compute_size_expr(), and get_charintrin_temp().
alignment()
int alignment (DTYPE dtype)
...
Definition at line 1213 of file dtypeutl.c.
References alignment(), FLG::dalign, DTY, FLANG_FALLTHROUGH, flg, get_ty_kind(), interr(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, and XBIT.
Referenced by align_struct_tmp(), alignment(), alignment_of_var(), amd64_update_class(), do_equiv(), emit_init(), fix_equiv_locals(), fix_equiv_statics(), gen_va_arg(), get_hollerith_size(), get_struct_from_dsrt2(), handle_bindC_func_ret(), layout_struct_body(), ldst_instr_flags_from_dtype(), ll_abi_classify_arg_dtype(), lldbg_create_aggregate_members_type(), lldbg_create_aggregate_type_mdnode(), lldbg_create_array_type_mdnode(), lldbg_create_assumed_len_string_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_ftn_array_type_mdnode(), lldbg_create_member_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_create_string_type_mdnode(), lldbg_create_structure_type_mdnode(), lldbg_create_union_type_mdnode(), lldbg_create_vector_type_mdnode(), lldbg_emit_local_variable(), lldbg_emit_ptr_param_variable(), lldbg_emit_type(), llmp_task_add_loopvar(), llmp_task_add_private(), make_stmt(), make_uplevel_arg_struct(), read_init(), ref_pd(), and sym_is_refd().
alignment_of_var()
int alignment_of_var (int sptr)
Like alignment(), but takes into account whether the var is a pointer.
Definition at line 1265 of file dtypeutl.c.
References alignment(), PDALN_IS_DEFAULT, PDALNG, sptr, and TY_QUAD.
Referenced by add_to_common(), chkstruct(), do_common_blocks(), and set_common_size().
array_element_dtype()
DTYPE array_element_dtype (DTYPE dtype)
if array datatype, returns the element dtype, else returns dtype
Definition at line 4108 of file dtypeutl.c.
References DTY, and is_array_dtype().
Referenced by allocate_lhs_if_needed(), build_array_ref(), check_alloc_ptr_type(), construct_association(), eval_minval_or_maxval(), gen_type_initialize_for_sym(), get_dtype_init_template(), get_struct_dtype_field(), init_allocatable_typedef_components(), init_derived_type(), initFinalSub(), inline_RTE_set_type(), instantiate_interface(), is_container_dtype(), is_dtype_runtime_length_char(), is_dtype_unlimited_polymorphic(), is_empty_typedef(), is_unresolved_parameterized_dtype(), lower_put_datatype(), lower_use_datatype(), needs_type_in_descr(), no_data_components_recursive(), search_type_members(), set_type_in_descriptor(), transform_call(), and valid_assign_pointer_types().
bits_in()
int bits_in (DTYPE dtype)
Definition at line 1295 of file dtypeutl.c.
References get_ty_kind(), interr(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by ref_intrin(), and ref_pd().
change_assumed_char_to_deferred()
DTYPE change_assumed_char_to_deferred (DTYPE dtype)
Definition at line 4274 of file dtypeutl.c.
Referenced by construct_association().
chk_kind_parm_set_expr()
int chk_kind_parm_set_expr (int ast, DTYPE dtype)
Definition at line 3721 of file dtypeutl.c.
References A_OPTYPEG, ARGT_ARG, ast, chk_kind_parm_set_expr(), const_fold(), CONVAL2G, DT_INT, get_kind_set_parm(), get_len_set_parm(), i, mk_cval1(), sptr, and val.
Referenced by chk_kind_parm_set_expr(), gen_kind_parm_assignments(), put_kind_type_param(), and put_length_type_param().
chkstruct()
void chkstruct (DTYPE dtype)
Compute size and alignment of struct and union types and their members.
Definition at line 3842 of file dtypeutl.c.
References a, ALIGN, ALIGNG, alignment_of_var(), assert, d, DISTG, DTY, extent_of(), is_tbp_or_final(), ISZ_T, m, NOSYM, offset, RUNTIMEG, s, size, and size_of_var().
Referenced by get_parameterized_dt(), lower_init_sym(), put_default_kind_type_param(), put_length_type_param(), semant1(), semant3(), and sym_init().
cmpat_dtype()
LOGICAL cmpat_dtype (DTYPE d1, DTYPE d2)
Similar to eq_dtype(), except all scalar integer types are compatible with each other, all scalar logical types are compatible with each other, all character types are compatible with each other.
Definition at line 1896 of file dtypeutl.c.
References DT_ISINT, DT_ISLOG, DTY, eq_dtype(), FALSE, TRUE, TY_CHAR, and TY_NCHAR.
Referenced by cmpat_dtype_array_cast(), and semant3().
cmpat_dtype_array_cast()
LOGICAL cmpat_dtype_array_cast (DTYPE d1, DTYPE d2)
Similar to eq_dtype(), except all scalar integer types are compatible with each other, all scalar logical types are compatible with each other, all character types are compatible with each other and we allow casting arrays when types fit into each other.
Definition at line 2145 of file dtypeutl.c.
References cmpat_dtype(), DDTG, DT_ISINT, DT_ISLOG, DT_ISREAL, DTY, eq_dtype(), FALSE, TRUE, TY_CHAR, and TY_NCHAR.
Referenced by dinit_acl_val2().
cmpat_dtype_with_size()
LOGICAL cmpat_dtype_with_size (DTYPE d1, DTYPE d2)
Similar to compat_dtype(), except all scalar integer types are compatible with each other, all scalar logical types are compatible with each other, all character types are compatible with each other. Also, array extents are checked.
Definition at line 1921 of file dtypeutl.c.
References ADD_LWBD, ADD_NUMDIM, ADD_UPBD, cmpat_dtype_with_size(), DT_ISLOG, DT_ISNUMERIC, DTY, FALSE, get_int_cval(), i, is_iso_cptr(), n, NOSYM, TRUE, TY_CHAR, and TY_NCHAR.
Referenced by chk_struct_constructor(), cmpat_dtype_with_size(), compat_arg_lists(), dinit_acl_val2(), get_exttype_struct_constructor(), get_keyword_components(), and init_types_compatable().
cmpat_func()
LOGICAL cmpat_func (DTYPE d1, DTYPE d2)
Return true if the data types for two functions are compatible.
Two functions are compatible if a single local variable can be used to hold their return values and therefore implying that the same return mechanism can be used for the functions.
Definition at line 1442 of file dtypeutl.c.
References assert, DTY, and TRUE.
conformable()
LOGICAL conformable (DTYPE d1, DTYPE d2)
Return true if the data types for two arrays are conformable (have the same shape). Shape is defined to be the rank and the extents of each dimension.
Definition at line 3384 of file dtypeutl.c.
References AD_DPTR, AD_LWAST, AD_NUMDIM, AD_UPAST, FALSE, get_int_cval(), i, ndim, and TRUE.
Referenced by ENTF90(), and semfin().
different_type_same_kind()
LOGICAL different_type_same_kind (DTYPE d1, DTYPE d2)
Definition at line 3649 of file dtypeutl.c.
References DTY, FALSE, kind_of(), and TRUE.
Referenced by chk_arguments(), and tkr_match().
dlen()
int dlen (int ty)
Definition at line 2725 of file dtypeutl.c.
References TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by dtype_skip(), dumpdts(), dumpdtypes(), dumpnewdtypes(), local_copy(), lower_data_types(), lower_init_sym(), rewrite_all_asts(), share_secd(), and simpledtype().
dmp_dent()
int dmp_dent (DTYPE dtypeind)
...
Definition at line 2903 of file dtypeutl.c.
References _dmp_dent(), FILE, gbl, NULL, and outfile.
Referenced by dmp_dtype(), and dumpdtype().
dmp_dtype()
void dmp_dtype (void)
...
Definition at line 2709 of file dtypeutl.c.
References dmp_dent(), STB::dt, gbl, i, and stb.
Referenced by dbg_dump(), import_inline(), init(), lower(), process_input(), and upper().
dtype_to_arg()
int dtype_to_arg (DTYPE dtype)
Map compiler's DT_ values to the values expected by the run-time.
Definition at line 3599 of file dtypeutl.c.
References DTY, and ty_to_lib.
Referenced by _pgi_kind(), add_reduce_descriptor(), check_alloc_ptr_type(), check_pointer_type(), construct_association(), emit_kopy_in(), emit_secd(), emit_sum_scatterx(), gen_poly_element_arg(), gen_ptr_in(), generate_gather(), get_descr_or_placeholder_arg(), init_intrin_type_desc(), init_sdsc(), init_sdsc_bounds(), is_same_secd(), lower_stmt(), make_simple_template_from_ast(), nml_emit_desc(), rewrite_allocatable_assignment(), rw_array(), semant3(), semantio(), set_type_in_descriptor(), transform_associated(), transform_c_f_pointer(), transform_call(), and transform_ptr().
dtype_with_shape()
DTYPE dtype_with_shape (DTYPE dtype, int shape)
Definition at line 1098 of file dtypeutl.c.
References ad_val_of(), ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_NUMDIM, ADD_NUMELM, ADD_UPAST, ADD_UPBD, ADD_ZBASE, astb, ASTB::bnd, DTY, ASTB::dtype, get_array_dtype(), i, ISZ_T, lb, mk_bnd_ast(), mk_extent(), mk_isz_cval(), ndim, ASTB::one, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, and ub.
Referenced by func_call2(), mk_member(), mk_subscr_copy(), ptrfunc_call(), ref_pd(), and rewrite_allocatable_assignment().
dumpdtype()
void dumpdtype (DTYPE dtype)
...
Definition at line 2943 of file dtypeutl.c.
References dmp_dent().
Referenced by inlarr().
dup_array_dtype()
DTYPE dup_array_dtype (DTYPE o_dt)
Duplicate a dtype array record and its array descriptor.
Definition at line 3186 of file dtypeutl.c.
References _FP, _VP, AD_DPTR, AD_NUMDIM, AUX::arrdsc_avl, AUX::arrdsc_base, AUX::arrdsc_size, aux, BCOPY, DTY, get_type(), and NEED.
Referenced by add_ptr_assign(), chkshape(), cngshape(), decl_private_sym(), fix_mem_bounds2(), gen_allocatable_result(), gen_and_assoc_tmp_ptr(), gen_char_result(), gen_pointer_result(), get_parameterized_dt(), put_length_type_param(), ref_intrin(), ref_pd(), rewrite_allocatable_assignment(), and semant3().
eq_dtype()
LOGICAL eq_dtype (DTYPE d1, DTYPE d2)
Definition at line 1748 of file dtypeutl.c.
References eq_dtype2(), and FALSE.
Referenced by chk_arguments(), cmpat_dtype(), cmpat_dtype_array_cast(), compute_size_expr(), dinit_val(), get_dtype_init_template(), lower_ast(), lower_conv(), ref_pd(), resolvePass(), same_datatype(), and semant3().
eq_dtype2()
LOGICAL eq_dtype2 (DTYPE d1, DTYPE d2, LOGICAL flag)
In the presence of modules and interface blocks, it's possible that two identical derived types are not represented by the same data type record. If this occurs, eq_dtype() will check the types of the members.
Definition at line 1656 of file dtypeutl.c.
References ADD_NUMDIM, cmp_interfaces(), DTY, eq_dtype2(), extends_type(), FALSE, NOSYM, SYMNAME, TRUE, TY_CHAR, and TY_NCHAR.
Referenced by check_defined_io2(), chk_arguments(), cmp_interfaces(), cngtyp2(), compatible_characteristics(), eq_dtype(), eq_dtype2(), find_by_name_stype_arg(), get_generic_member2(), ref_pd(), ref_pd_subr(), resolveBind(), same_ancestor(), semant1(), semant3(), semCheckTbp(), subr_call2(), tk_match_arg(), and valid_assign_pointer_types().
extent_of()
ISZ_T extent_of (DTYPE dtype)
...
Definition at line 1071 of file dtypeutl.c.
References AD_DPTR, AD_NUMELM, assert, CONVAL2G, d, DTY, STB::i0, interr(), ISZ_T, stb, and sym_of_ast().
Referenced by chkstruct(), dinit_varref(), dinits(), exp_smp(), get_llvm_name(), getsname(), layout_struct_body(), llassem_get_objtodbg_list(), and tk_match_arg().
fini_chartab()
void fini_chartab (void)
Definition at line 1369 of file dtypeutl.c.
References chartabavail, chartabbase, chartabsize, and FREE.
Referenced by symtab_fini().
fix_dtype()
DTYPE fix_dtype (int sptr, DTYPE dtype)
Fix array and char dtypes.
Given datatype dtype and symbol sptr, return a datatype equivalent to the given datatype, but with any array bounds filled in from the symbol's array bounds, and char length filled in from the symbol's char length, using calls to LBOUND, UBOUND, or LEN, as necessary.
Definition at line 954 of file dtypeutl.c.
References ADD_ASSUMSHP, ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_NUMDIM, ADD_NUMELM, ADD_UPAST, ADD_UPBD, ADD_ZBASE, ast_intr(), astb, ASTB::bnd, dt, DT_INT, DTY, ASTB::dtype, fix_dtype(), get_array_dtype(), get_ty_kind(), get_type(), i, interr(), mk_cval(), mk_extent(), mk_id(), ndim, NOSYM, sptr, sym_get_scalar(), SYMNAME, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by compute_size_ast(), compute_size_expr(), fix_dtype(), and rewrite_sub_args().
fval_of()
int fval_of (DTYPE dtype)
Return 0 if reg, 1 if mem.
Get FVAL field of a data type.
Definition at line 3040 of file dtypeutl.c.
References assert, and get_ty_kind().
get_array_dtype()
DTYPE get_array_dtype (int numdim, DTYPE eltype)
Create a dtype record for an array of rank numdim including its array descriptor.
...
Parameters
numdim number of dimensions
eltype data type of the array element
The layout of an array descriptor is:
    int    numdim;  --+
    int    zbase;     |
    UINT16 *ilmp;     |
    char   defer;     +-- 4 ints (fixed part)
    char   adjarr;    |
    char   assumsz;   |
    char   pad;     --+
    struct {
        int mlpyr;  --+
        int lwbd;     |
        int upbd;     +-- 6 ints (variable part)
        int lwast;    |
        int upast;    |
        int exntnast;-+
    } b[numdim];
    int    numelm;  --+-- 1 int
Any change in the size of the structure requires a change to one or both of the macros _FP and _VP. Also the size assertion in symtab.c needs to be changed.
Definition at line 3159 of file dtypeutl.c.
References get_aux_arrdsc(), and get_type().
Referenced by _mk_arrdsc(), add_class_arg_descr_arg(), add_equivalence(), add_padding(), ast_init(), ast_rewrite(), binop(), construct_association(), create_threadprivate_dtype(), declare_type(), dtype_with_shape(), finish_args(), fix_dtype(), gen_bnd_assn(), gen_dtio_args(), gen_dtsfmt_args(), gen_vlist(), get_csect_sym(), get_semaphore(), hlv_getvsym(), import(), inline_small_matmul(), lower_do_stmt(), lower_linearized(), lower_namelist_plists(), lower_prepare_symbols(), makeCopyprivArray(), mkarglist(), promote_assumsz_arg(), read_datatype(), read_symbol(), ref_pd(), replace_arg(), rewrite_func_ast(), sym_get_array(), sym_get_formal(), and sym_get_sdescr().
get_aux_arrdsc()
void get_aux_arrdsc (DTYPE dtype, int numdim)
Definition at line 3170 of file dtypeutl.c.
References _FP, _VP, AD_DPTR, AD_NUMDIM, AUX::arrdsc_avl, AUX::arrdsc_base, AUX::arrdsc_size, aux, BZERO, DTY, and NEED.
Referenced by ast_init(), fix_mem_bounds2(), and get_array_dtype().
get_bnd_con()
int get_bnd_con (ISZ_T v)
Create a constant sym entry which reflects the type of an array bound/extent.
Definition at line 1199 of file dtypeutl.c.
References DT_INT, getcon(), ISZ_2_INT64, num, and XBIT.
Referenced by mk_swlist().
get_cuf_derivedtype()
static DTYPE get_cuf_derivedtype (DTYPE d_dtype) static
Definition at line 4016 of file dtypeutl.c.
References DTY, and lookupsymbol().
Referenced by is_cuf_c_devptr().
get_iso_c_ptr()
DTYPE get_iso_c_ptr (void)
Definition at line 4070 of file dtypeutl.c.
References get_iso_ptrtype().
Referenced by transform_c_f_pointer().
get_iso_derivedtype()
static DTYPE get_iso_derivedtype (DTYPE d_dtype) static
Definition at line 3966 of file dtypeutl.c.
References DTY, gbl, lookupsymbol(), and SYMNAME.
Referenced by is_iso_c_funptr(), is_iso_c_ptr(), and is_iso_cptr().
get_iso_ptrtype()
DTYPE get_iso_ptrtype (const char * name)
Definition at line 4043 of file dtypeutl.c.
References DTY, first_hash(), getsymbol(), lookupsymbol(), name, s, and sptr.
Referenced by get_iso_c_ptr(), and ref_intrin().
get_kind_set_parm()
static LOGICAL get_kind_set_parm (int sptr, DTYPE dtype, int * val) static
Definition at line 3791 of file dtypeutl.c.
References DTY, FALSE, get_kind_set_parm(), mem(), NOSYM, sptr, SYMNAME, TRUE, and val.
Referenced by chk_kind_parm_set_expr(), and get_kind_set_parm().
get_len_set_parm()
static int get_len_set_parm (int sptr, DTYPE dtype, int * val) static
Definition at line 3815 of file dtypeutl.c.
References DTY, get_len_set_parm(), mem(), NOSYM, sptr, SYMNAME, and val.
Referenced by chk_kind_parm_set_expr(), and get_len_set_parm().
get_struct_dtype_field()
static int get_struct_dtype_field (DTYPE dtype, int offset, int default_result) static
Definition at line 4214 of file dtypeutl.c.
References array_element_dtype(), DTY, get_ty_kind(), is_array_dtype(), and offset.
Referenced by get_struct_initialization_tree(), get_struct_members(), and get_struct_tag_sptr().
get_struct_initialization_tree()
int get_struct_initialization_tree (DTYPE dtype)
Definition at line 4244 of file dtypeutl.c.
References get_struct_dtype_field().
Referenced by component_init_allocd_auto(), gen_derived_type_alloc_init(), get_dtype_init_template(), get_static_type_descriptor(), init_allocatable_typedef_components(), misc_checks(), and sym_get_sdescr().
get_struct_members()
SPTR get_struct_members (DTYPE dtype)
Definition at line 4238 of file dtypeutl.c.
References get_struct_dtype_field().
Referenced by get_static_type_descriptor(), get_vtoff(), is_unresolved_parameterized_dtype(), and semant1().
get_struct_tag_sptr()
SPTR get_struct_tag_sptr (DTYPE dtype)
Definition at line 4232 of file dtypeutl.c.
References get_struct_dtype_field().
Referenced by addFinalSubroutine(), check_derived_type_in_comm(), completeTbp(), get_dtype_init_template(), get_static_type_descriptor(), get_vtoff(), inheritTbps(), init_derived_type(), initFinalSub(), is_unresolved_parameterized_dtype(), resolveGeneric(), resolvePass(), resolveTbps(), semCheckTbp(), and set_type_in_descriptor().
get_ty_kind()
static TY_KIND get_ty_kind (DTYPE dtype) static
Definition at line 3049 of file dtypeutl.c.
References assert, STB::dt, DTY, ERR_Severe, and stb.
Referenced by alignment(), bits_in(), fix_dtype(), fval_of(), get_struct_dtype_field(), is_array_dtype(), is_procedure_dtype(), is_procedure_ptr_dtype(), scale_of(), size_ast(), size_ast_of(), size_of(), target_kind(), and target_name().
get_type()
DTYPE get_type (int n, TY_KIND v1, int v2)
...
Find or allocate a slot in dtype array for the new datatype. For strings, check if the data type is already present.
Parameters
n number of datatype entries we want to occupy
v1 data type
v2 second value, meaning depends on data type, for strings it is the length, for pointers - target type, etc
Definition at line 1385 of file dtypeutl.c.
References astb, chartabavail, chartabbase, CHARTABSIZE, chartabsize, STB::dt, DTY, chartab::dtype, FALSE, i, ASTB::i1, interr(), j, k, n, NEED, chartab::next, stb, STG_NEXT_SIZE, TY_CHAR, and TY_NCHAR.
Referenced by _repeat(), _trim(), add_padding(), adjust_ch_length(), alloc_char_temp(), binop(), casttyp(), cg_get_type(), ch_substring(), chk_constructor(), chksubstr(), cngcon(), cngtyp2(), dinit_data(), dinit_intr_call(), dinit_val(), dup_array_dtype(), eval_init_op(), eval_trim(), fill_links_symbol(), fill_midnum(), fix_character_length(), fix_dtype(), gen_char_result(), get_array_dtype(), get_ftn_hollerith_type(), get_parameterized_dt(), get_unl_poly_sym(), getchartmp(), getstring(), import(), lower_add_pghpf_commons(), lower_linearized(), lower_set_craypointer(), mk_swlist(), mod_type(), put_kind_type_param(), read_datatype(), reduc_rank_dtype(), ref_pd(), rewrite_allocatable_assignment(), rewrite_sub_args(), semant1(), semant2(), set_string_type_from_init(), setup_procedure_sym(), widenProcessDirectLoad(), and widenProcessIndirectLoad().
getast()
void getast (int ast, char * string)
Given an AST and a string pointer, append a printable representation of the AST expression onto the string.
Definition at line 2389 of file dtypeutl.c.
References A_OPTYPEG, ASD_NDIM, ASD_SUBS, ast, b, DBGBIT, getast(), getop(), getprint(), i, leftparens(), lp, ndim, rightparens(), and sym_of_ast().
Referenced by getast(), getdtype(), and symdentry().
getdtype()
void getdtype (DTYPE dtype, char * ptr)
Put into the character array pointed to by ptr, the print representation of dtype.
Definition at line 2559 of file dtypeutl.c.
References AD_ADJARR, AD_ASSUMRANK, AD_ASSUMSHP, AD_ASSUMSZ, AD_DEFER, AD_DPTR, AD_LWAST, AD_LWBD, AD_NOBOUNDS, AD_NUMDIM, AD_UPAST, AD_UPBD, STB::dt, DTY, getast(), i, p, stb, strlen(), SYMNAME, TY_CHAR, TY_NCHAR, and STB::tynames.
Referenced by _dmp_dent(), _dump_one_ast(), dmp_var(), dsym(), dump_buff(), putdtype(), putentry(), and symdentry().
getop()
static void getop (int op, char * string) static
Definition at line 2282 of file dtypeutl.c.
References OP_ADD, OP_AIF, OP_BYVAL, OP_CAT, OP_CMP, OP_CON, OP_DIV, OP_EQ, OP_FUNC, OP_GE, OP_GT, OP_LAND, OP_LD, OP_LE, OP_LEQV, OP_LNEQV, OP_LNOT, OP_LOC, OP_LOG, OP_LOR, OP_LT, OP_MUL, OP_NE, OP_NEG, OP_REF, OP_SCAND, OP_ST, OP_SUB, OP_VAL, OP_XTOI, OP_XTOX, and s.
Referenced by getast().
has_finalized_component()
LOGICAL has_finalized_component (SPTR sptr)
Definition at line 1821 of file dtypeutl.c.
References is_finalized(), sptr, and test_sym_components_only().
Referenced by gen_finalization_for_sym(), gen_finalized_result(), is_layout_desc(), lower_stmt(), misc_checks(), rewrite_allocatable_assignment(), semant1(), and semant3().
has_impure_finalizer()
LOGICAL has_impure_finalizer (SPTR sptr)
Definition at line 1836 of file dtypeutl.c.
References is_impure_finalizer(), sptr, and test_sym_and_components().
Referenced by check_doconcurrent_ast().
has_layout_desc()
LOGICAL has_layout_desc (SPTR sptr)
Definition at line 1858 of file dtypeutl.c.
References is_layout_desc(), sptr, and test_sym_components_only().
Referenced by _constructf90(), lower_stmt(), and write_typedescs().
has_recursive_component()
LOGICAL has_recursive_component (int sptr)
Definition at line 1806 of file dtypeutl.c.
References is_recursive(), sptr, and test_sym_and_components().
Referenced by is_layout_desc().
has_tbp()
LOGICAL has_tbp (DTYPE dtype)
Definition at line 3698 of file dtypeutl.c.
References is_tbp_component(), and search_type_members_wrapped().
Referenced by construct_association().
has_tbp_or_final()
LOGICAL has_tbp_or_final (DTYPE dtype)
Definition at line 3715 of file dtypeutl.c.
References is_tbp_or_final_component(), and search_type_members_wrapped().
Referenced by lower_symbols(), rewrite_calls(), semant1(), and size_ast().
ic_strcmp()
static int ic_strcmp (const char * str, const char * pattern) static
Compare str and pattern like strcmp() but ignoring the case of str. pattern is all lower case.
Definition at line 4081 of file dtypeutl.c.
References str.
Referenced by is_cuf_c_devptr(), is_iso_c_funptr(), and is_iso_c_ptr().
init_chartab()
void init_chartab (void)
...
Definition at line 1345 of file dtypeutl.c.
References chartabavail, chartabbase, CHARTABSIZE, chartabsize, chartab::dtype, flg, i, NEW, chartab::next, TY_CMPLX, TY_DBLE, FLG::x, and XBIT.
Referenced by sym_init().
is_array_dtype()
LOGICAL is_array_dtype (DTYPE dtype)
...
Definition at line 4102 of file dtypeutl.c.
References get_ty_kind().
Referenced by array_element_dtype(), build_array_ref(), check_alloc_ptr_type(), construct_association(), gen_bounds_assignments(), gen_type_initialize_for_sym(), get_ast_bounds(), get_ast_extents(), get_ast_rank(), get_dtype_init_template(), get_struct_dtype_field(), init_allocatable_typedef_components(), init_derived_type(), initFinalSub(), inline_RTE_set_type(), is_array_ast(), is_container_dtype(), is_dtype_runtime_length_char(), is_dtype_unlimited_polymorphic(), is_empty_typedef(), is_unresolved_parameterized_dtype(), is_zero_size_typedef(), lower_put_datatype(), lower_stmt(), lower_use_datatype(), needs_type_in_descr(), no_data_components_recursive(), ptrfunc_call(), search_type_members(), semant3(), set_type_in_descriptor(), and transform_call().
is_container_dtype()
static LOGICAL is_container_dtype (DTYPE dtype) static
Definition at line 298 of file dtypeutl.c.
References array_element_dtype(), DTYG, FALSE, is_array_dtype(), and TRUE.
Referenced by is_derived_type_allo(), no_data_components_recursive(), and search_type_members().
is_cuf_c_devptr()
LOGICAL is_cuf_c_devptr (DTYPE d_dtype)
Definition at line 4009 of file dtypeutl.c.
References DTY, get_cuf_derivedtype(), ic_strcmp(), and SYMNAME.
Referenced by transform_c_f_pointer().
is_deferlenchar_ast()
bool is_deferlenchar_ast (int ast)
Check if ast is deferred-length character
Definition at line 2476 of file dtypeutl.c.
References ADD_DEFER, ast, ast_is_sym(), DDTG, dt, DTY, memsym_of_ast(), NOSYM, TY_CHAR, and TY_NCHAR.
Referenced by gen_alloc_dealloc(), gen_bounds_assignments(), is_deferlenchar_dtype(), mkexpr_assign_temp(), and rewrite_allocatable_assignment().
is_deferlenchar_dtype()
bool is_deferlenchar_dtype (DTYPE dtype)
Check if dtype is deferred-length character.
Definition at line 2514 of file dtypeutl.c.
References ADD_DEFER, ARGT_ARG, DDTG, dt, DTY, is_deferlenchar_ast(), memsym_of_ast(), TY_CHAR, and TY_NCHAR.
Referenced by chk_constructor(), gen_allocate_array(), get_shape_arraydtype(), and lower_put_datatype().
is_derived_type_allo()
static LOGICAL is_derived_type_allo (SPTR sptr, struct visit_list ** visited) static
Definition at line 1877 of file dtypeutl.c.
References is_container_dtype(), is_derived_type_allo(), NOSYM, search_type_members(), and sptr.
Referenced by is_derived_type_allo(), and is_or_has_derived_allo().
is_dtype_runtime_length_char()
LOGICAL is_dtype_runtime_length_char (DTYPE dtype)
Definition at line 4114 of file dtypeutl.c.
References array_element_dtype(), DT_ISCHAR, is_array_dtype(), and string_length().
Referenced by compute_size_expr(), and construct_association().
is_dtype_unlimited_polymorphic()
LOGICAL is_dtype_unlimited_polymorphic (DTYPE dtype)
Definition at line 4124 of file dtypeutl.c.
References array_element_dtype(), DTY, and is_array_dtype().
Referenced by add_ptr_assign(), and cngtyp2().
is_empty_typedef()
LOGICAL is_empty_typedef (DTYPE dtype)
Check for special case of empty typedef which has a size of 0 but one member of type DT_NONE to indicate that the type is empty and not incomplete, a forward reference, etc.
Check for special case of empty typedef which has a size of 0 but one member of type DT_NONE to indicate that the type is empty and not incomplete, a forward reference, etc.
Definition at line 401 of file dtypeutl.c.
References array_element_dtype(), DTY, FALSE, is_array_dtype(), NOSYM, sptr, and TRUE.
Referenced by cngcon(), dinit_data(), emit_init(), no_data_components_recursive(), process_dtype_struct(), semant1(), and semant2().
is_finalized()
static LOGICAL is_finalized (int sptr, struct visit_list ** visited) static
Definition at line 1812 of file dtypeutl.c.
References is_finalized(), NOSYM, search_type_members(), and sptr.
Referenced by has_finalized_component(), and is_finalized().
is_impure_finalizer()
static LOGICAL is_impure_finalizer (int sptr, struct visit_list ** visited) static
Definition at line 1827 of file dtypeutl.c.
References is_impure(), is_impure_finalizer(), NOSYM, search_type_members(), and sptr.
Referenced by has_impure_finalizer(), and is_impure_finalizer().
is_iso_c_funptr()
LOGICAL is_iso_c_funptr (DTYPE d_dtype)
Definition at line 3959 of file dtypeutl.c.
References DTY, get_iso_derivedtype(), ic_strcmp(), and SYMNAME.
Referenced by cngtyp2(), ref_intrin_subr(), and ref_pd().
is_iso_c_ptr()
LOGICAL is_iso_c_ptr (DTYPE d_dtype)
Definition at line 3952 of file dtypeutl.c.
References DTY, get_iso_derivedtype(), ic_strcmp(), and SYMNAME.
Referenced by cngtyp2(), ref_intrin_subr(), and transform_c_f_pointer().
is_iso_cptr()
DTYPE is_iso_cptr (DTYPE d_dtype)
...
Definition at line 3946 of file dtypeutl.c.
References get_iso_derivedtype().
Referenced by _constructf90(), assign(), byvalue_ref_arg(), cmpat_dtype_with_size(), cngtyp2(), find_byval_ref(), func_call2(), has_private(), llvm_check_retval_inargs(), lower_ast(), lower_visit_symbol(), normalize_forall(), process_ll_abi_func_ftn_mod(), ptrfunc_call(), ptrsubr_call(), ref_pd(), rewrite_cptr_references(), semant3(), semantio(), and subr_call2().
is_layout_desc()
static LOGICAL is_layout_desc (SPTR sptr, struct visit_list ** visited) static
Definition at line 1842 of file dtypeutl.c.
References DTYG, has_finalized_component(), has_recursive_component(), is_layout_desc(), is_or_has_derived_allo(), NOSYM, search_type_members(), and sptr.
Referenced by has_layout_desc(), and is_layout_desc().
is_or_has_derived_allo()
LOGICAL is_or_has_derived_allo (SPTR sptr)
Definition at line 1885 of file dtypeutl.c.
References is_derived_type_allo(), sptr, and test_sym_and_components().
Referenced by is_layout_desc(), and lower_stmt().
is_or_has_poly()
LOGICAL is_or_has_poly (SPTR sptr)
Definition at line 1871 of file dtypeutl.c.
References is_poly(), sptr, and test_sym_and_components().
Referenced by lower_stmt(), and rewrite_calls().
is_poly()
static LOGICAL is_poly (SPTR sptr, struct visit_list ** visited) static
Definition at line 1864 of file dtypeutl.c.
References is_poly(), is_tbp_or_final(), NOSYM, search_type_members(), and sptr.
Referenced by is_or_has_poly(), and is_poly().
is_procedure_dtype()
LOGICAL is_procedure_dtype (DTYPE dtype)
Test if a data type index corresponds with a procedure.
Parameters
dtype data type index to check
Definition at line 4182 of file dtypeutl.c.
References get_ty_kind().
Referenced by is_procedure_ptr_dtype(), semant1(), set_proc_param_count_dtype(), and set_proc_result_dtype().
is_procedure_ptr_dtype()
LOGICAL is_procedure_ptr_dtype (DTYPE dtype)
Test if a data type index corresponds with a procedure pointer.
Parameters
dtype data type index to check
Definition at line 4137 of file dtypeutl.c.
References DTY, get_ty_kind(), and is_procedure_dtype().
Referenced by is_procedure_ptr(), proc_ptr_result_dtype(), semant1(), set_proc_ptr_param_count_dtype(), set_proc_ptr_result_dtype(), and valid_assign_pointer_types().
is_recursive()
static LOGICAL is_recursive (int sptr, struct visit_list ** visited) static
Definition at line 1799 of file dtypeutl.c.
References is_recursive(), NOSYM, search_type_members(), and sptr.
Referenced by has_recursive_component(), is_recursive(), and search_type_members().
is_recursive_dtype()
static LOGICAL is_recursive_dtype (int sptr, struct visit_list ** visited) static
Definition at line 447 of file dtypeutl.c.
References is_recursive_dtype(), NOSYM, search_type_members(), and sptr.
Referenced by is_recursive_dtype(), no_data_components(), and no_data_components_recursive().
is_tbp_component()
static LOGICAL is_tbp_component (int sptr, struct visit_list ** visited) static
Definition at line 3689 of file dtypeutl.c.
References is_tbp(), is_tbp_component(), NOSYM, search_type_members(), and sptr.
Referenced by has_tbp(), and is_tbp_component().
is_tbp_or_final_component()
static LOGICAL is_tbp_or_final_component (int sptr, struct visit_list ** visited) static
Definition at line 3705 of file dtypeutl.c.
References is_tbp_or_final(), is_tbp_or_final_component(), NOSYM, search_type_members(), and sptr.
Referenced by has_tbp_or_final(), and is_tbp_or_final_component().
is_unresolved_parameterized_dtype()
LOGICAL is_unresolved_parameterized_dtype (DTYPE dtype)
Definition at line 4250 of file dtypeutl.c.
References array_element_dtype(), FALSE, get_struct_members(), get_struct_tag_sptr(), is_array_dtype(), NOSYM, and TRUE.
Referenced by get_dtype_init_template().
is_zero_size_typedef()
LOGICAL is_zero_size_typedef (DTYPE dtype)
Check for special case of zero-size typedef which may nest have zero-size typedef compnents or zero-size array compnents.
Definition at line 429 of file dtypeutl.c.
References DTY, FALSE, and is_array_dtype().
Referenced by dinit_data(), dinit_varref(), dinits(), get_struct_from_dsrt2(), process_dsrt(), and rewrite_acl().
kanji_char()
int kanji_char (unsigned char * p, int len, int * bytes)
Extract necessary bytes from character string in order to return integer (16-bit) representation of one kanji char.
Parameters
p ptr to EUC string
len number of bytes in p
bytes return number of EUC bytes used up
Definition at line 3091 of file dtypeutl.c.
References len, p, SS2, SS3, and val.
Referenced by const_eval(), const_fold(), eval_ichar(), init_fold_const(), kanji_prefix(), put_kstr(), put_ncharstring_n(), and ref_intrin().
kanji_len()
int kanji_len (unsigned char * p, int len)
Return number of kanji characters.
Get number of kanji characters.
Parameters
p character string
len length in bytes of p
Definition at line 3063 of file dtypeutl.c.
References count, len, p, SS2, SS3, and val.
Referenced by _trim(), binop(), ch_substring(), cngcon(), get_stmt(), and semant2().
kanji_prefix()
int kanji_prefix (unsigned char * p, int newlen, int len)
Return number of bytes required for newlen chars.
Get number of bytes needed for kanji characters in string prefix.
Parameters
p ptr to EUC string
newlen number of kanji chars required from string prefix
len total number of bytes in string
Definition at line 3113 of file dtypeutl.c.
References kanji_char(), len, p, and void().
Referenced by cngcon(), crunch(), and ff_prescan().
kind_of()
int kind_of (DTYPE d1)
For intrinsic types, return same value as the KIND intrinsic.
Definition at line 3606 of file dtypeutl.c.
References DTY, k, size_of(), TY_CHAR, TY_CMPLX, TY_DCMPLX, TY_ISBASIC, and TY_NCHAR.
Referenced by different_type_same_kind(), and ref_pd().
lbound_of()
int lbound_of (DTYPE dtype, int dim)
Return AST representing the lower bound of array dtype for dimension dim (dim is relative to 0).
Definition at line 3300 of file dtypeutl.c.
References AD_ASSUMSHP, AD_DPTR, AD_LWAST, AD_LWBD, assert, ast, astb, ASTB::bnd, dim, DTY, ASTB::one, rank, and rank_of().
Referenced by init_sptr_w_acl(), lbound_of_sym(), mk_mem_ptr_shape(), mkshape(), and ref_array().
lbound_of_sym()
int lbound_of_sym (int sptr, int dim)
Return AST representing the lower bound of array symbol for dimension dim (dim is relative to 0).
Definition at line 3335 of file dtypeutl.c.
References dim, lbound_of(), and sptr.
leftparens()
static int leftparens (int ast, int astleft) static
Definition at line 2238 of file dtypeutl.c.
References A_OPTYPEG, ast, FALSE, priority(), and TRUE.
Referenced by getast().
no_data_components()
LOGICAL no_data_components (DTYPE dtype)
...
Definition at line 500 of file dtypeutl.c.
References is_recursive_dtype(), no_data_components_recursive(), NULL, result, and visit_list_free().
Referenced by _constructf90(), chk_struct_constructor(), construct_acl_for_sst(), dinit_val(), dinit_varref(), get_exttype_default(), get_exttype_struct_constructor(), get_keyword_components(), rewrite_acl(), semant2(), semantio(), and sym_is_refd().
no_data_components_recursive()
static bool no_data_components_recursive (DTYPE dtype, stm_predicate_t predicate, struct visit_list ** visited) static
Definition at line 457 of file dtypeutl.c.
References array_element_dtype(), DTY, DTYG, FALSE, visit_list::is_active, is_array_dtype(), is_container_dtype(), is_empty_typedef(), is_recursive_dtype(), no_data_components_recursive(), NOSYM, predicate(), TRUE, visit_list_push(), and visit_list_scan().
Referenced by no_data_components(), and no_data_components_recursive().
pr_dent()
void pr_dent (DTYPE dt, FILE * f)
Definition at line 2916 of file dtypeutl.c.
References _dmp_dent(), STB::dt, dt, DTY, f, FLANG_FALLTHROUGH, NOSYM, NULL, pr_dent(), ss, stb, and SYMNAME.
Referenced by pr_dent().
priority()
static int priority (int op) static
Definition at line 2184 of file dtypeutl.c.
References interr(), OP_ADD, OP_AIF, OP_BYVAL, OP_CAT, OP_CMP, OP_CON, OP_DIV, OP_EQ, OP_FUNC, OP_GE, OP_GT, OP_LAND, OP_LD, OP_LE, OP_LEQV, OP_LNEQV, OP_LNOT, OP_LOC, OP_LOG, OP_LOR, OP_LT, OP_MUL, OP_NE, OP_NEG, OP_REF, OP_SCAND, OP_ST, OP_SUB, OP_VAL, OP_XTOI, and OP_XTOX.
Referenced by leftparens(), llvm_add_to_init_list(), llvm_ctor_add_with_priority(), llvm_dtor_add_with_priority(), and rightparens().
proc_ptr_result_dtype()
DTYPE proc_ptr_result_dtype (DTYPE dtype)
Get return type from a procedure pointer dtype.
Parameters
dtype data type index for procedure pointer
Definition at line 4147 of file dtypeutl.c.
References DTY, and is_procedure_ptr_dtype().
Referenced by valid_assign_pointer_types().
rank_of()
int rank_of (DTYPE dtype)
Return number of dimensions of array dtype.
Definition at line 3272 of file dtypeutl.c.
References AD_DPTR, AD_NUMDIM, assert, DTY, and interr().
Referenced by chk_struct_constructor(), first_element_from_section(), lbound_of(), make_sec_from_ast_chk(), make_simple_template_from_ast(), rank_of_sym(), ref_pd_subr(), tkr_match_arg(), trans_mkproc(), and ubound_of().
rank_of_sym()
int rank_of_sym (int sptr)
Return number of dimensions of symbol sptr.
Definition at line 3291 of file dtypeutl.c.
References rank_of(), and sptr.
Referenced by _reshape(), assign_bounds(), check_defined_io2(), copy_section_temp_before(), eliminate_redundant(), gatherx_temp_before(), gen_ptr_in(), get_all_descriptors(), get_allobnds(), init_derived_type(), initFinalSub(), is_same_array_shape(), is_whole_array(), lower_prepare_symbols(), lower_stmt(), make_alnd(), make_secd(), opt_allocate(), reference_for_temp(), replace_arg(), rewrite_func_ast(), semant3(), simple_reference_for_temp(), temp_copy_section(), and temp_gatherx().
reduc_rank_dtype()
DTYPE reduc_rank_dtype (DTYPE o_dt, DTYPE elem_dt, int astdim, int after)
Duplicate a dtype array record and its array descriptor, excluding a dimension.
Parameters
o_dt old array dtype
elem_dt element dtype
astdim ast of dimension to be excluded
after std after which code is produced to create the bounds descriptor (if dim is not a constant)
Definition at line 3216 of file dtypeutl.c.
References _FP, _VP, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_NUMDIM, AD_UPAST, AD_UPBD, AUX::arrdsc_avl, AUX::arrdsc_base, AUX::arrdsc_size, aux, BZERO, CONVAL2G, dim, DTY, error(), gbl, get_type(), i, j, NEED, and NULL.
rightparens()
static int rightparens (int ast, int astright) static
Definition at line 2260 of file dtypeutl.c.
References A_OPTYPEG, ast, FALSE, priority(), and TRUE.
Referenced by getast().
rw_dtype_state()
void rw_dtype_state (int(*)(void *, size_t, size_t, FILE *) p_rw, FILE * fd)
Definition at line 3675 of file dtypeutl.c.
References chartabavail, chartabbase, STB::dt, ISZ_T, RW_FD, and stb.
Referenced by rw_host_state().
same_ancestor()
LOGICAL same_ancestor (DTYPE dtype1, DTYPE dtype2)
Check to see if two types are extensions from the same ancestor.
Definition at line 1755 of file dtypeutl.c.
References DTY, eq_dtype2(), FALSE, same_ancestor(), and TRUE.
Referenced by resolveBind(), and same_ancestor().
same_dtype()
LOGICAL same_dtype (DTYPE d1, DTYPE d2)
Similar to eq_dtype(), except types must match exactly, and derived types must be SEQUENCE and match in name also. Also, array extents are checked.
Definition at line 2030 of file dtypeutl.c.
References ADD_LWBD, ADD_NUMDIM, ADD_UPBD, DTY, FALSE, get_int_cval(), i, n, NOSYM, same_dtype(), TRUE, TY_CHAR, and TY_NCHAR.
Referenced by cngtyp2(), lower_init_sym(), and same_dtype().
same_type_different_kind()
LOGICAL same_type_different_kind (DTYPE d1, DTYPE d2)
Definition at line 3636 of file dtypeutl.c.
References DTY, FALSE, TRUE, and ty_to_base_ty.
Referenced by chk_arguments(), and tkr_match().
scale_of()
int scale_of (DTYPE dtype, INT * size)
Compute the size of a data type.
...
This machine dependent routine computes the size of a data type in terms of two quantities:
size - number of elements in the data type (returned thru size).
scale - number of bytes in each element, expressed as a power of two (the return value of scale_of).
This routine will be used to take advantage of the machines that have the ability to add a scaled expression (multiplied by a power of two) to an address. This is particularly useful for incrementing a pointer variable and array subscripting.
Note that for those machines that do not have this feature, scale_of returns a scale of 0 and size_of for size.
Definition at line 2966 of file dtypeutl.c.
References d, DTY, get_ty_kind(), interr(), scale, scale_of(), size, string_length(), tmp, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by compute_sdsc_subscr(), create_array_subscr(), create_sdsc_subscr(), exp_mac(), get_sdsc_element(), and scale_of().
search_type_members()
static LOGICAL search_type_members (DTYPE dtype, stm_predicate_t predicate, struct visit_list ** visited) static
Definition at line 329 of file dtypeutl.c.
References array_element_dtype(), DTY, FALSE, visit_list::is_active, is_array_dtype(), is_container_dtype(), is_recursive(), NOSYM, predicate(), result, visit_list_push(), and visit_list_scan().
Referenced by is_derived_type_allo(), is_finalized(), is_impure_finalizer(), is_layout_desc(), is_poly(), is_recursive(), is_recursive_dtype(), is_tbp_component(), is_tbp_or_final_component(), and search_type_members_wrapped().
search_type_members_wrapped()
static LOGICAL search_type_members_wrapped (DTYPE dtype, stm_predicate_t predicate) static
Definition at line 368 of file dtypeutl.c.
References NULL, predicate(), result, search_type_members(), and visit_list_free().
Referenced by has_tbp(), has_tbp_or_final(), and test_sym_components_only().
set_proc_param_count_dtype()
void set_proc_param_count_dtype (DTYPE proc_dtype, int param_count)
Set paramter count for a procedure type.
Parameters
proc_dtype data type index for the procedure type
param_count paramter count to set
Definition at line 4205 of file dtypeutl.c.
References assert, DTY, and is_procedure_dtype().
Referenced by set_proc_ptr_param_count_dtype().
set_proc_ptr_param_count_dtype()
void set_proc_ptr_param_count_dtype (DTYPE ptr_dtype, int param_count)
Set paramter count for a procedure pointer type.
Parameters
ptr_dtype data type index for the procedure pointer
param_count paramter count to set
Definition at line 4170 of file dtypeutl.c.
References assert, DTY, is_procedure_ptr_dtype(), and set_proc_param_count_dtype().
Referenced by semant1().
set_proc_ptr_result_dtype()
void set_proc_ptr_result_dtype (DTYPE ptr_dtype, DTYPE result_dtype)
Set return type for a procedure pointer.
Parameters
ptr_dtype data type index for the procedure pointer
result_dtype data type index for the return type
Definition at line 4157 of file dtypeutl.c.
References assert, DTY, is_procedure_ptr_dtype(), and set_proc_result_dtype().
Referenced by semant1().
set_proc_result_dtype()
void set_proc_result_dtype (DTYPE proc_dtype, DTYPE result_dtype)
Set return type for a procedure type.
Parameters
proc_dtype data type index for the procedure type
result_dtype data type index for the return type
Definition at line 4192 of file dtypeutl.c.
References assert, DTY, and is_procedure_dtype().
Referenced by semant1(), and set_proc_ptr_result_dtype().
size_ast()
INT size_ast (int sptr, DTYPE dtype)
Definition at line 551 of file dtypeutl.c.
References ad_val_of(), ADD_DEFER, ADD_NUMELM, ast_intr(), astb, ASTB::bnd, CONVAL2G, d, DT_INT, DT_PTR, DTY, ASTB::dtype, FLANG_FALLTHROUGH, get_ty_kind(), has_tbp_or_final(), STB::i0, STB::i1, interr(), ISZ_T, len, mk_binop(), mk_convert(), mk_cval(), mk_id(), mk_isz_cval(), ASTB::one, OP_MUL, size, size_ast(), sptr, stb, sym_get_scalar(), sym_of_ast(), SYMNAME, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by add_reduce_descriptor(), chksubstr(), copy_arg_to_seq_tmp(), gen_allocate(), inline_contig_check(), lower_stmt(), mk_offset(), mkarg(), mkexpr1(), mkexpr2(), mklvalue(), ref_pd(), rewrite_func_ast(), and size_ast().
size_ast_of()
INT size_ast_of (int ast, DTYPE dtype)
Like size_ast(), but pass an AST, allowing for member references.
Definition at line 679 of file dtypeutl.c.
References A_OPTYPEG, ad_val_of(), ADD_DEFER, ADD_NUMELM, ast, ast_intr(), astb, ASTB::bnd, CONVAL2G, d, DT_INT, DT_PTR, DTY, ASTB::dtype, errsev(), FLANG_FALLTHROUGH, get_ty_kind(), STB::i0, STB::i1, interr(), ISZ_T, len, mk_binop(), mk_convert(), mk_cval(), mk_id(), mk_isz_cval(), ASTB::one, OP_ADD, OP_CAT, OP_MUL, size, size_ast_of(), sptr, stb, sym_get_scalar(), sym_of_ast(), SYMNAME, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, TY_SLOG, TY_WORD, and val.
Referenced by gen_automatic_reallocation(), gen_ptr_in(), is_same_secd(), ref_pd(), rewrite_allocatable_assignment(), rewrite_func_ast(), semant3(), size_ast_of(), size_of_allocatable(), and string_expr_length().
size_of()
ISZ_T size_of (DTYPE dtype)
...
Definition at line 96 of file dtypeutl.c.
References A_OPTYPEG, AD_DEFER, AD_DPTR, AD_NUMELM, astb, CONVAL2G, d, DT_INT, DT_PTR, DTY, errsev(), get_ty_kind(), STB::i0, STB::i1, ASTB::i1, INT64_2_ISZ, interr(), ISZ_T, STB::k0, STB::k1, ASTB::k1, num, size_of(), size_sym, stb, string_length(), sym_of_ast(), sz, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, TY_SLOG, TY_WORD, and XBIT.
Referenced by _exp_smove(), _pgi_element_size(), _put(), add_equivalence(), add_socs(), allocThreadprivate(), arg_is_refd(), build_routine_and_parameter_entries(), casttyp(), cg_llvm_init(), check_cstruct_return(), check_sc(), check_struct(), check_vfp(), chk_evar(), chkcon_to_isz(), classify_common(), classify_int(), cmplx_to_mem(), collapse_assignment(), compute_sdsc_subscr(), const_eval(), convert_cnst(), convert_dtype(), convert_int_to_ptr(), convert_template_instance(), cp_byval_mem_arg(), create_array_subscr(), create_sdsc_subscr(), dinit_data(), dinit_subs(), dinit_varref(), dinits(), do_equiv(), do_reduction(), elem_size_of_ast(), emit_init(), eval_adjustl(), eval_adjustr(), eval_ichar(), eval_index(), eval_init_op(), eval_ishft(), eval_len_trim(), eval_repeat(), eval_scale(), eval_scan(), eval_transfer(), eval_trim(), eval_verify(), exp_ac(), exp_add_copy(), exp_call(), exp_load(), exp_mac(), exp_smp(), exp_store(), gen_acon_expr(), gen_alloca_call_if_necessary(), gen_arg_operand(), gen_base_addr_operand(), gen_derived_io(), gen_llvm_expr(), gen_va_arg(), get_ag(), get_dtype_for_vect_type_nme(), get_isz_cval(), get_string_constant(), get_struct_from_dsrt2(), get_threadprivate_origsize(), getTaskSharedSize(), hostsym_is_refd(), inlarr(), kind_of(), ld_sptr(), ll_abi_classify_arg_dtype(), ll_abi_classify_return_dtype(), ll_abi_classify_va_arg_dtype(), ll_make_kmpc_atomic_read(), ll_make_kmpc_atomic_write(), ll_make_kmpc_dispatch_fini(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), ll_make_kmpc_for_static_init_args(), ll_make_kmpc_struct_type(), ll_make_kmpc_task_arg(), ll_make_uplevel_type(), llvm_fc_type(), loadUplevelArgsForRegion(), lower_add_pghpf_commons(), lower_data_stmts(), lower_do_stmt(), lower_init_sym(), lower_numelm(), lower_omp_target_tripcount(), lower_stmt(), make_sec_from_ast_chk(), make_stmt(), make_uplevel_arg_struct(), merge(), mkeffadr(), pp_entries(), pp_entries_mixedstrlen(), pp_params(), pp_params_mixedstrlen(), print_ast(), put_adjarr_bounds(), read_init(), ref_intrin(), ref_pd(), ref_threadprivate_var(), rewrite_func_ast(), SCALAR_SIZE(), sem_eq_str(), semant1(), semantio(), semsmp(), set_common_size(), set_initial_s1(), size_of(), size_of_allocatable(), size_of_dtype(), size_of_var(), smallest_dtype(), stackcheck(), sym_is_refd(), transfer_load(), transfer_store(), transform_c_f_pointer(), transform_ptr(), trav_struct(), update_homogeneous(), write_comm(), write_layout_desc(), and write_typedescs().
size_of_var()
ISZ_T size_of_var (int sptr)
Return the size of this variable, taking into account such things like whether the variable is a pointer.
Definition at line 511 of file dtypeutl.c.
References ADD_NUMDIM, STB::dt_int, DTY, error(), gbl, get_descriptor_len(), is_tbp_or_final(), ISZ_T, NULL, rank, size_of(), size_sym, sptr, stb, SYMNAME, and sz.
Referenced by add_to_common(), chkstruct(), do_common_blocks(), llmp_task_add_private(), and set_common_size().
string_expr_length()
INT string_expr_length (int ast)
Definition at line 835 of file dtypeutl.c.
References A_OPTYPEG, ARGT_ARG, ast, ast_intr(), astb, ASTB::bnd, DDTG, DT_INT, ASTB::dtype, get_int_cval(), ASTB::i0, ASTB::i1, interr(), len, mk_binop(), mk_cval(), mk_id(), NULL, OP_ADD, OP_CAT, OP_SUB, proc_arginfo(), procsym_of_ast(), size_ast_of(), and string_expr_length().
Referenced by add_ptr_assign(), adjust_ch_length(), gen_automatic_reallocation(), gen_bounds_assignments(), lower_stmt(), rewrite_allocatable_assignment(), rewrite_func_ast(), rewrite_sub_args(), semant3(), semantio(), and string_expr_length().
string_length()
int string_length (DTYPE dtype)
Return length of constant char string data type.
Definition at line 229 of file dtypeutl.c.
References CONVAL2G, DTY, interr(), TY_CHAR, and TY_NCHAR.
Referenced by _adjustl(), _adjustr(), _index(), _len_trim(), _repeat(), _scan(), _trim(), _verify(), _write_token(), binop(), ch_substring(), chksubstr(), cngcon(), const_fold(), dinit_acl_val2(), dinit_data(), emit_alnd_secd(), eval_init_op(), export_symbol(), get_fmtstr(), getprint(), is_dtype_runtime_length_char(), lower_data_stmts(), lower_symbol(), nml_emit_desc(), process_string(), put_const(), ref_intrin(), ref_pd(), scale_of(), semant1(), semant2(), semant3(), semantio(), size_of(), and temp_type_descriptor().
target_kind()
int target_kind (DTYPE dtype)
Definition at line 67 of file dtypeutl.c.
References get_ty_kind(), interr(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, and TY_SLOG.
Referenced by put_float(), put_int8(), put_intkind(), put_logical(), and ref_pd().
target_name()
const char * target_name (DTYPE dtype)
Definition at line 34 of file dtypeutl.c.
References FLANG_FALLTHROUGH, get_ty_kind(), interr(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, TY_SLOG, and XBIT.
Referenced by semant3().
test_sym_and_components()
static LOGICAL test_sym_and_components (int sptr, stm_predicate_t predicate) static
Definition at line 382 of file dtypeutl.c.
References NULL, predicate(), result, sptr, and visit_list_free().
Referenced by has_impure_finalizer(), has_recursive_component(), is_or_has_derived_allo(), and is_or_has_poly().
test_sym_components_only()
static LOGICAL test_sym_components_only (int sptr, stm_predicate_t predicate) static
Definition at line 391 of file dtypeutl.c.
References NOSYM, predicate(), search_type_members_wrapped(), and sptr.
Referenced by has_finalized_component(), and has_layout_desc().
tk_match_arg()
LOGICAL tk_match_arg (int formal_dt, int actual_dt, LOGICAL flag)
Return TRUE if the scalar data types of an actual argument matches the formal with respect to the type & kind rules.
Definition at line 1459 of file dtypeutl.c.
References cmp_interfaces(), CONVAL2G, DDTG, DTY, eq_dtype2(), extent_of(), FALSE, TRUE, TY_CHAR, and TY_NCHAR.
Referenced by chk_arguments(), subr_call2(), tkr_match(), and tkr_match_arg().
ubound_of()
int ubound_of (DTYPE dtype, int dim)
Return AST representing the upper bound of array dtype for dimension dim (dim is relative to 0).
Definition at line 3344 of file dtypeutl.c.
References AD_DPTR, AD_UPAST, assert, ast, astb, ASTB::bnd, dim, DTY, interr(), ASTB::one, rank, and rank_of().
Referenced by ubound_of_sym().
ubound_of_sym()
int ubound_of_sym (int sptr, int dim)
Return AST representing the upper bound of array symbol for dimension dim (dim is relative to 0).
Definition at line 3374 of file dtypeutl.c.
References dim, sptr, and ubound_of().
visit_list_free()
static void visit_list_free (struct visit_list ** list) static
Definition at line 288 of file dtypeutl.c.
References FREE, list, and p.
Referenced by no_data_components(), search_type_members_wrapped(), and test_sym_and_components().
visit_list_push()
static void visit_list_push (struct visit_list ** list, DTYPE dtype) static
Definition at line 277 of file dtypeutl.c.
References visit_list::dtype, visit_list::is_active, list, NEW, visit_list::next, and TRUE.
Referenced by no_data_components_recursive(), and search_type_members().
visit_list_scan()
static struct visit_list * visit_list_scan (struct visit_list * list, DTYPE dtype) static
Definition at line 267 of file dtypeutl.c.
References list.
Referenced by no_data_components_recursive(), and search_type_members().
Variable Documentation
chartab
int chartab[CHARTABSIZE] static
Definition at line 1336 of file dtypeutl.c.
chartabavail
int chartabavail static
Definition at line 1341 of file dtypeutl.c.
Referenced by fini_chartab(), get_type(), init_chartab(), and rw_dtype_state().
chartabbase
struct chartab* chartabbase = 0 static
Definition at line 1342 of file dtypeutl.c.
Referenced by fini_chartab(), get_type(), init_chartab(), and rw_dtype_state().
chartabsize
int chartabsize static
Definition at line 1341 of file dtypeutl.c.
Referenced by fini_chartab(), get_type(), and init_chartab().
size_sym
int size_sym = 0 static
Definition at line 31 of file dtypeutl.c.
Referenced by size_of(), and size_of_var().
ty_to_base_ty
int ty_to_base_ty[] static
Definition at line 3552 of file dtypeutl.c.
Referenced by same_type_different_kind().
ty_to_lib
int ty_to_lib[]
Definition at line 3512 of file dtypeutl.c.
Referenced by ast_intr(), dtype_to_arg(), gen_allocate(), lower_intrinsic(), print_ast(), semant3(), semantio(), and transform_ptr().