flang: dummy.c File Reference
dummy.c File Reference
Functions
void expand ()
...
void unroll_n ()
void schedule ()
...
void unroll ()
void cg_add_func ()
void garbage_collect ()
Function Documentation
cg_add_func()
void cg_add_func ()
Definition at line 25 of file dummy.c.
expand()
void expand (void)
...
Definition at line 9 of file dummy.c.
Referenced by process_input().
garbage_collect()
void garbage_collect ()
Definition at line 29 of file dummy.c.
schedule()
void schedule (void)
...
Definition at line 17 of file dummy.c.
Referenced by process_input().
unroll()
void unroll ()
Definition at line 21 of file dummy.c.
Referenced by cons_unroll_count_metadata().
unroll_n()
void unroll_n ()
Definition at line 13 of file dummy.c.