flang: dump.c File Reference
dump.c File Reference
dump routines for compiler's internal data structures. This file contains dump routines for the compiler's various internal data structures (e.g., symbol tables, dtype records, etc.).
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "dtypeutl.h"
#include "ast.h"
#include "nme.h"
#include "optimize.h"
#include "dpm_out.h"
#include "hlvect.h"
#include "soc.h"
#include "fih.h"
#include "symutl.h"
Macros
#define SIZEOF(array) (sizeof(array) / sizeof(char *))
Functions
static void putit ()
static void appendit ()
static void putline ()
static void putint (const char *s, int d)
static void put2int (const char *s, int d1, int d2)
static void putint1 (int d)
static void appendint1 (int d)
static void put2int1 (int d1, int d2)
static void putint1star (int d, int star, const char *starstring)
static void putnzint (const char *s, int d)
static void putnzhex (const char *s, int d)
static void putnzbits (const char *s, int d)
static void putcharacter (const char *s, char c)
static void putedge (int d1, int d2)
static void putsym (const char *s, int sptr)
static void putsym1 (int sptr)
static void putsymilist (int symi)
void dumpsymi (int symi)
static void putnsym (const char *s, int sptr)
static void putstring (const char *s, const char *t)
static void putstring1 (const char *t)
static void appendstring1 (const char *t)
static void putsc (const char *s, int sc)
static void putstype (const char *s, int stype)
static void putstype1 (int stype)
static void putintent (const char *s, int intent)
static void putinkind (const char *s, int k)
static void put_inkwd (const char *s, int k)
static void putnname (const char *s, int off)
static void putdtype (const char *s, int d)
static void putdty (const char *s, int dty)
static void putparam (int dpdsc, int paramct)
void putsymlk (const char *name, int list)
void putslnk1 (int list)
void dumplists ()
static void putbit (const char *s, int b)
static void check (const char *s, int v)
void putasttype (const char *s, int opc)
static void putast (const char *s, int a)
static void putval (const char *s, int val, const char *values[], int sizeofvalues)
static void putoptype (const char *s, int optype)
void dastli (int astli)
void dast (int astx)
void dumpasts ()
void dumpshape (int shd)
void dumpshapes ()
static void dastreex (int astx, int l, int notlast)
void dastree (int astx)
void past (int astx)
static void putflags (const char *s, int flags)
void dumpfnode (int v)
...
void dumpfg (int v)
void dfg (int v)
void dumpfgraph ()
...
void putnme (int n)
void putnmetype (const char *s, int t)
char * printname (int sptr)
...
static void _printnme (int n)
void printnme (int n)
...
void dumpnme (int n)
...
void dumpnmes ()
...
void dumploop (int l)
...
void dumploops ()
...
void dstd (int stdx)
void dsstd (int stdx)
void dstdp (int stdx)
void dstdtree (int stdx)
void dstds (int std1, int std2)
void dstdps (int std1, int std2)
void dsstds (int std1, int std2)
void dstdr (int stdx, int count)
void dstda ()
void dstdpa ()
void dumpstdtrees ()
void dsocptr (int sochead)
void puttmpltype (const char *s, int t)
void puttmplsc (const char *s, int t)
void puttmplflag (char *s, int f)
void dalnd (int alnd)
void dsecd (int secd)
void dsym (int sptr)
...
void dsyms (int l, int u)
...
void ds (int sptr)
...
void dsa ()
...
void dss (int l, int u)
...
void dumphashlk (int sptr)
void dcommon (int c)
void dcommons ()
void dumpdt (int dt)
void dumpdts ()
void ddt (int dt)
void dumpdtypes ()
...
char * getdddir (DDEDGE *dd)
void putdd (DDEDGE *dd)
void putddlist (const char *s, DDEDGE *ddlist)
void dumpvind (int i)
...
void dumpvinds (int start, int end)
void dumpmr (int mr)
...
void dumpmemref (int mr)
...
void dumpmemrefs (int m1, int m2)
void putmrlist (const char *s, int ivlist)
void putsclist (const char *s, int sclist)
...
void dumpvloop (int l)
...
void dumpvnest (int l)
void dumpvloops ()
...
void dumpvnest2 (int l)
void dumpvloops2 ()
void dumpdef (int def)
...
void dumpdefs (void)
...
void dumpdeflist (int d)
...
void dumpuse (int use)
...
void dumpuses (void)
...
Variables
static FILE * dfile
static int linelen = 0
static char BUF [900]
static int longlines = 1
static char prefix [500]
Detailed Description
dump routines for compiler's internal data structures. This file contains dump routines for the compiler's various internal data structures (e.g., symbol tables, dtype records, etc.).
Definition in file dump.c.
Macro Definition Documentation
SIZEOF
#define SIZEOF (array) (sizeof(array) / sizeof(char *))
Definition at line 687 of file dump.c.
Function Documentation
_printnme()
static void _printnme (int n) static
Definition at line 1989 of file dump.c.
References _printnme(), appendint1(), appendstring1(), ASD_NDIM, ASD_SUBS, d, dfile, gbl, i, n, ndim, NME_CNST, NME_NM, NME_NULL, NME_SUB, NME_SYM, NME_TYPE, nmeb, NT_ARR, NT_IND, NT_MEM, NT_UNK, NT_VAR, printast(), printname(), and putint().
Referenced by _printnme(), and printnme().
appendint1()
static void appendint1 (int d) static
Definition at line 103 of file dump.c.
References appendit(), BUF, and d.
Referenced by _printnme().
appendit()
static void appendit (void) static
Definition at line 53 of file dump.c.
References BUF, dfile, linelen, and strlen().
Referenced by appendint1(), appendstring1(), and putstype1().
appendstring1()
static void appendstring1 (const char * t) static
Definition at line 283 of file dump.c.
References appendit(), BUF, and t.
Referenced by _printnme(), dumplists(), and putnme().
check()
static void check (const char * s, int v) static
Definition at line 607 of file dump.c.
References dfile, and s.
Referenced by dsym().
dalnd()
void dalnd (int alnd)
Definition at line 2564 of file dump.c.
References __ASSUMED_SHAPE, __ASSUMED_SIZE, __DESCRIPTIVE_ALIGN_TARGET, __DESCRIPTIVE_DIST_FORMAT, __DESCRIPTIVE_DIST_TARGET, __DYNAMIC, __IDENTITY_MAP, __INHERIT, __INTENT_IN, __INTENT_OUT, __LOCAL, __NO_OVERLAPS, __OFF_TEMPLATE, __POINTER, __PRESCRIPTIVE_ALIGN_TARGET, __PRESCRIPTIVE_DIST_FORMAT, __PRESCRIPTIVE_DIST_TARGET, __SAVE, __SEQUENTIAL, __TRANSCRIPTIVE_DIST_FORMAT, __TRANSCRIPTIVE_DIST_TARGET, DTB::avl, DTB::base, dfile, dtb, f, gbl, i, NULL, putast(), putbit(), putint(), putline(), putnsym(), putnzbits(), putnzhex(), putstring(), puttmplsc(), puttmpltype(), TMPL_ALIGN_TARGET, TMPL_ALIGNEE_SC, TMPL_COLLAPSE, TMPL_DESCR, TMPL_DIST_TARGET, TMPL_DIST_TARGET_DESCR, TMPL_FLAG, TMPL_ISSTAR, TMPL_LB, TMPL_RANK, TMPL_TARGET_DESCR, TMPL_TARGET_SC, TMPL_TYPE, and TMPL_UB.
dast()
void dast (int astx)
Definition at line 717 of file dump.c.
References A_ARGCNTG, A_ARGCNTP, A_MEM_ORDERG, A_MEM_ORDERP, A_OPTYPEG, A_OPTYPEP, A_ORDEREDG, A_ORDEREDP, A_SCHED_TYPEG, A_SCHED_TYPEP, A_TKNG, A_TKNP, args, ARGT_ARG, ASD_NDIM, ASD_SUBS, astb, BCOPY, COMSTR, dastli(), dfile, gbl, j, ASTB::ptr0, ASTB::ptr0c, ASTB::ptr1, put2int1(), putasttype(), putbit(), putdtype(), putint(), putline(), putnzint(), putoptype(), putstring1(), and putsym().
Referenced by dastreex(), do_distbegin(), dumpasts(), semant3(), set_descr_tag(), and temp_type_descriptor().
dastli()
void dastli (int astli)
Definition at line 702 of file dump.c.
References a, astb, ASTLI_FLAGS, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, BUF, and putit().
Referenced by dast().
dastree()
void dastree (int astx)
Definition at line 1706 of file dump.c.
References dastreex(), dfile, gbl, longlines, and prefix.
Referenced by dstdtree().
dastreex()
static void dastreex (int astx, int l, int notlast) static
Definition at line 1413 of file dump.c.
References A_ARGCNTG, args, ARGT_ARG, ASD_NDIM, ASD_SUBS, astb, dast(), dastreex(), dfile, FLANG_FALLTHROUGH, gbl, j, ndim, and prefix.
Referenced by dastree(), and dastreex().
dcommon()
void dcommon (int c)
Definition at line 4238 of file dump.c.
References dfile, gbl, m, NOSYM, stb, and SYMNAME.
Referenced by dcommons().
dcommons()
void dcommons (void)
Definition at line 4256 of file dump.c.
References c, dcommon(), dfile, gbl, NOSYM, and stb.
Referenced by init().
ddt()
void ddt (int dt)
Definition at line 4370 of file dump.c.
References dt, and dumpdt().
Referenced by gen_pointer_result(), and ref_intrin().
dfg()
void dfg (int v)
Definition at line 1814 of file dump.c.
References dumpfnode().
ds()
void ds (int sptr)
...
Definition at line 4204 of file dump.c.
References dsym(), and sptr.
Referenced by __fort_copy(), __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), ENTFTN(), export_symbol(), kmaxloc_common(), kminloc_common(), maxloc_common(), minloc_common(), msg(), queue_symbol(), scale_bytes(), and scale_kbytes().
dsa()
void dsa (void)
...
Definition at line 4210 of file dump.c.
References dsyms().
dsecd()
void dsecd (int secd)
Definition at line 2661 of file dump.c.
References DTB::avl, DTB::base, dfile, dtb, gbl, INS_DESCR, INS_DTYPE, INS_RANK, INS_TEMPLATE, NULL, putdtype(), putint(), putline(), and putnsym().
Referenced by dsym().
dsocptr()
void dsocptr (int sochead)
Definition at line 2446 of file dump.c.
References SOC::avail, dfile, putline(), putstring1(), putsym1(), soc, SOC_NEXT, and SOC_SPTR.
Referenced by dsym().
dss()
void dss (int l, int u)
...
Definition at line 4216 of file dump.c.
References dsyms().
dsstd()
void dsstd (int stdx)
Definition at line 2303 of file dump.c.
References astb, dbg_print_ast(), dfile, gbl, STD_AST, STD_LINENO, and stdx.
Referenced by dsstds().
dsstds()
void dsstds (int std1, int std2)
Definition at line 2379 of file dump.c.
References astb, dfile, dsstd(), gbl, STD_NEXT, STD_PREV, stdx, and SYMNAME.
Referenced by dump_sstds().
dstd()
void dstd (int stdx)
Definition at line 2248 of file dump.c.
References astb, ASTB::atypes, dbg_print_ast(), dfile, gbl, putbit(), putflags(), putint(), putline(), putnsym(), putnzint(), putstring(), SPTR_NULL, STD_ACCEL, STD_AST, STD_ATOMIC, STD_BLKSYM, STD_BR, STD_CS, STD_DELETE, STD_EX, STD_FG, STD_FLAGS, STD_IGNORE, STD_INDIVISIBLE, STD_KERNEL, STD_LABEL, STD_LINENO, STD_LOCAL, STD_MARK, STD_MINFO, STD_NEXT, STD_ORIG, STD_PAR, STD_PARSECT, STD_PREV, STD_PURE, STD_RESCOPE, STD_SPLIT, STD_ST, STD_TASK, stdx, and SYMNAME.
Referenced by dstdp(), dstds(), dstdtree(), and get_temp_forall2().
dstda()
void dstda (void)
Definition at line 2417 of file dump.c.
References dstds().
Referenced by reassociate(), and transform().
dstdp()
void dstdp (int stdx)
Definition at line 2318 of file dump.c.
References dstd(), putstdassigns(), putstdpta(), and stdx.
Referenced by dstdps(), and points_to().
dstdpa()
void dstdpa (void)
Definition at line 2423 of file dump.c.
References dstdps(), putstdassigns(), and putstdpta().
Referenced by pstride_analysis(), and transform().
dstdps()
void dstdps (int std1, int std2)
Definition at line 2359 of file dump.c.
References astb, dfile, dstdp(), gbl, STD_NEXT, STD_PREV, stdx, and SYMNAME.
Referenced by dstdpa(), dump_stdps(), and points_to().
dstdr()
void dstdr (int stdx, int count)
Definition at line 2397 of file dump.c.
References astb, c, count, dfile, dstds(), gbl, STD_NEXT, STD_PREV, and stdx.
dstds()
void dstds (int std1, int std2)
Definition at line 2342 of file dump.c.
References astb, dfile, dstd(), gbl, STD_NEXT, STD_PREV, stdx, and SYMNAME.
Referenced by dstda(), dstdr(), and dump_stds().
dstdtree()
void dstdtree (int stdx)
Definition at line 2328 of file dump.c.
References astb, dastree(), dfile, dstd(), gbl, STD_AST, and stdx.
Referenced by dumpstdtrees().
dsym()
void dsym (int sptr)
...
Definition at line 2684 of file dump.c.
References BCOPY, check(), CMEMLG, CMEMLP, CONVAL2G, CONVAL2P, CUDAG, CUDAP, DEFLABG, DEFLABP, dfile, dsecd(), dsocptr(), ENDLINEG, ENDLINEP, FORALLNDXG, FORALLNDXP, FUNCLINEG, FUNCLINEP, gbl, getdtype(), getprint(), GREALG, GREALP, GSAMEG, GSAMEP, i, ILMG, ILMP, INHERITG, INTENTG, INTENTP, linelen, STB::n_base, NEWDSCG, NEWDSCP, NML_NEXT, NML_SPTR, PARAMVALG, PARAMVALP, PDALNG, PDALNP, put_inkwd(), putbit(), putcuda(), putdtype(), putinkind(), putint(), putintent(), putline(), putnname(), putnsym(), putnzint(), putparam(), putsc(), putstring(), putstype(), putsym(), putsym1(), putsymilist(), putsymlk(), RUNTIMEG, scope, SFDSCG, SFDSCP, sptr, and stb.
Referenced by _linearize(), ds(), dsyms(), gen_allocate(), gen_bnd_assn(), print_ast(), and pstride_analysis().
dsyms()
void dsyms (int l, int u)
...
Definition at line 4189 of file dump.c.
References dsym(), STB::firstusym, i, and stb.
Referenced by dsa(), dss(), dump_all_symbols(), dump_current_symbols(), and dump_symbols().
dumpasts()
void dumpasts (void)
Definition at line 1367 of file dump.c.
References astb, and dast().
Referenced by init().
dumpdef()
void dumpdef (int def)
...
Definition at line 4723 of file dump.c.
References def, DEF_ADDR, DEF_ARG, DEF_CONFL, DEF_CONST, DEF_CSEL, DEF_DELETE, DEF_DOEND, DEF_DOINIT, DEF_DU, DEF_FG, DEF_GEN, DEF_LHS, DEF_LNEXT, DEF_LOOPENTRY, DEF_NEXT, DEF_NM, DEF_OTHER, DEF_PRECISE, DEF_RHS, DEF_SELF, DEF_STD, dfile, gbl, OPT::ndefs, DU_TAG::next, NULL, opt, printnme(), putbit(), putint(), putint1(), putline(), putnzint(), putstring1(), and DU_TAG::use.
Referenced by dumpdeflist(), and dumpdefs().
dumpdeflist()
void dumpdeflist (int d)
...
Definition at line 4787 of file dump.c.
References d, def, DEF_NEXT, dfile, dumpdef(), gbl, OPT::ndefs, and opt.
dumpdefs()
void dumpdefs (void)
...
Definition at line 4774 of file dump.c.
References def, dfile, dumpdef(), FIRST_DEF, gbl, OPT::ndefs, and opt.
Referenced by sectfloat().
dumpdt()
void dumpdt (int dt)
Definition at line 4288 of file dump.c.
References ADD_ADJARR, ADD_ASSUMRANK, ADD_ASSUMSHP, ADD_ASSUMSZ, ADD_DEFER, ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_NOBOUNDS, ADD_NUMDIM, ADD_NUMELM, ADD_UPAST, ADD_UPBD, ADD_ZBASE, dfile, STB::dt, dt, DTY, gbl, i, putast(), putbit(), putdty(), putdtype(), putint(), putline(), putsym(), putsymlk(), stb, TY_CHAR, and TY_NCHAR.
Referenced by ddt(), and dumpdts().
dumpdts()
void dumpdts (void)
Definition at line 4356 of file dump.c.
References dfile, dlen(), STB::dt, dt, DTY, dumpdt(), gbl, and stb.
Referenced by dumpdtypes(), and init().
dumpdtypes()
void dumpdtypes (void)
...
Definition at line 4376 of file dump.c.
References dumpdts().
Referenced by init().
dumpfg()
void dumpfg (int v)
Definition at line 1808 of file dump.c.
References dumpfnode().
dumpfgraph()
void dumpfgraph (void)
...
Definition at line 1820 of file dump.c.
References dfile, OPT::dfn, dumpfnode(), EDGE_PRED, EDGE_SUCC, gbl, NULL, OPT::num_nodes, opt, putedge(), putint1(), putline(), and VTX_NODE.
Referenced by redundss(), and sectfloat().
dumpfnode()
void dumpfnode (int v)
...
Definition at line 1740 of file dump.c.
References dfile, FG_ATOMIC, FG_CS, FG_CTLEQUIV, FG_DFN, FG_DOM, FG_EN, FG_EX, FG_FT, FG_HEAD, FG_INNERMOST, FG_JMP_TBL, FG_LABEL, FG_LINENO, FG_LNEXT, FG_LOOP, FG_LPREV, FG_MASTER, FG_MEXITS, FG_NATNXT, FG_NEXT, FG_PAR, FG_PARLOOP, FG_PARSECT, FG_PDOM, FG_PRED, FG_PTR_STORE, FG_STDFIRST, FG_STDLAST, FG_SUCC, FG_TAIL, FG_TASK, FG_XT, FG_ZTRP, gbl, NULL, OPT::num_nodes, opt, pred, PSI_FT, PSI_NEXT, PSI_NODE, PSI_P_NULL, putbit(), putint(), putint1star(), putline(), putnsym(), putnzint(), putstring(), and putstring1().
Referenced by dfg(), dumpfg(), and dumpfgraph().
dumphashlk()
void dumphashlk (int sptr)
Definition at line 4222 of file dump.c.
References dfile, first_hash(), gbl, n, putline(), putsym1(), s, sptr, and SYMNAME.
dumplists()
void dumplists (void)
Definition at line 491 of file dump.c.
References appendstring1(), aux, dfile, gbl, AUX::list, NOSYM, putline(), putslnk1(), putstring1(), and putstype1().
Referenced by init().
dumploop()
void dumploop (int l)
...
Definition at line 2140 of file dump.c.
References BIH_LINENO, dfile, FG_NEXT, FG_TO_BIH, gbl, LP_CALLFG, LP_CALLINTERNAL, LP_CHILD, LP_CNCALL, LP_CS, LP_CSECT, LP_EXITS, LP_EXT_STORE, LP_FG, LP_FORALL, LP_HEAD, LP_INNERMOST, LP_INVARIF, LP_JMP_TBL, LP_LEVEL, LP_MARK, LP_MASTER, LP_MEXITS, LP_NOBLA, LP_PARENT, LP_PARLOOP, LP_PARREGN, LP_PARSECT, LP_PTR_LOAD, LP_PTR_STORE, LP_QJSR, LP_SIBLING, LP_STL_PAR, LP_TAIL, LP_XTNDRNG, LP_ZEROTRIP, OPT::nloops, NULL, opt, p, PSI_NEXT, PSI_NODE, PSI_P_NULL, put2int(), putbit(), putint(), putint1(), putline(), putnme(), putnzint(), putstring(), putstring1(), and q.
Referenced by dumploops(), and dumpvnest2().
dumploops()
void dumploops (void)
...
Definition at line 2231 of file dump.c.
References dfile, dumploop(), gbl, LP_LOOP, OPT::nloops, NULL, and opt.
Referenced by redundss(), and sectfloat().
dumpmemref()
void dumpmemref (int mr)
...
Definition at line 4557 of file dump.c.
References dumpmr().
dumpmemrefs()
void dumpmemrefs (int m1, int m2)
Definition at line 4563 of file dump.c.
References dumpmr(), and m2.
Referenced by dumpvloop().
dumpmr()
void dumpmr (int mr)
...
Definition at line 4503 of file dump.c.
References dfile, gbl, hlv, MR_ARRAY, MR_BASED, MR_CSEILI, MR_EXP, MR_EXPARR, MR_FG, MR_FSUBS, MR_ILI, MR_ILT, MR_INDIR, MR_INDUC, MR_INIT, MR_INVAL, MR_INVAR, MR_INVEC, MR_IV, MR_IVUSE, MR_LOOP, MR_NEST, MR_NEXT, MR_NME, MR_PREV, MR_REWR, MR_RG, MR_SCALR, MR_SCLR, MR_STMT, MR_SUBCNT, MR_SUBST, MR_SUCC, MR_TYPE, HLVECT::mravail, HLVECT::mrbase, NULL, putast(), putbit(), putcharacter(), putddlist(), putint(), putline(), putnme(), and putnzint().
Referenced by dumpmemref(), and dumpmemrefs().
dumpnme()
void dumpnme (int n)
...
Definition at line 2090 of file dump.c.
References d, DEF_NEXT, dfile, gbl, n, NME_CNST, NME_CNT, NME_DEF, NME_HSHLNK, NME_INLARR, NME_NM, NME_RFPTR, NME_STL, NME_SUB, NME_SYM, NME_TYPE, nmeb, NULL, putint(), putint1(), putline(), putnmetype(), putnsym(), putnzint(), and putstring1().
Referenced by dumpnmes().
dumpnmes()
void dumpnmes (void)
...
Definition at line 2124 of file dump.c.
References dfile, dumpnme(), gbl, n, nmeb, and NULL.
Referenced by init(), and sectfloat().
dumpshape()
void dumpshape (int shd)
Definition at line 1376 of file dump.c.
References astb, dfile, gbl, putast(), putint(), putline(), ASTB::shd, SHD_LWB, SHD_NDIM, SHD_STRIDE, and SHD_UPB.
Referenced by dumpshapes().
dumpshapes()
void dumpshapes (void)
Definition at line 1398 of file dump.c.
References astb, dfile, dumpshape(), ASTB::shd, and SHD_NDIM.
Referenced by init().
dumpstdtrees()
void dumpstdtrees (void)
Definition at line 2433 of file dump.c.
References dfile, dstdtree(), STD_NEXT, STD_PREV, and stdx.
Referenced by init().
dumpsymi()
void dumpsymi (int symi)
Definition at line 233 of file dump.c.
References aux, dfile, gbl, putint(), putline(), putsymilist(), and AUX::symi_avl.
dumpuse()
void dumpuse (int use)
...
Definition at line 4799 of file dump.c.
References UD_TAG::def, dfile, gbl, UD_TAG::next, NULL, opt, printnme(), putbit(), putint(), putint1(), putline(), putnzint(), putstring1(), use, USE_ADDR, USE_ARG, USE_AST, USE_CSE, USE_DOINIT, USE_EXPOSED, USE_FG, USE_LOOPENTRY, USE_MARK1, USE_MARK2, USE_NM, USE_PRECISE, USE_STD, and USE_UD.
Referenced by dumpuses().
dumpuses()
void dumpuses (void)
...
Definition at line 4840 of file dump.c.
References dfile, dumpuse(), gbl, opt, and use.
Referenced by sectfloat().
dumpvind()
void dumpvind (int i)
...
Definition at line 4454 of file dump.c.
References dfile, gbl, hlv, i, HLVECT::indavail, HLVECT::indbase, NULL, putast(), putasttype(), putbit(), putint(), putline(), putnme(), VIND_ALAST, VIND_ALIAS, VIND_DELETE, VIND_INIT, VIND_LOAD, VIND_MIDF, VIND_NIU, VIND_NM, VIND_NOINV, VIND_OMIT, VIND_OPC, VIND_ORIGINIT, VIND_PTR, VIND_SAVE, VIND_SKIP, VIND_TOTSKIP, and VIND_VISIT.
Referenced by dumpvinds().
dumpvinds()
void dumpvinds (int start, int end)
Definition at line 4489 of file dump.c.
References dfile, dumpvind(), end, gbl, hlv, i, HLVECT::indbase, NULL, and start.
Referenced by dumpvloop().
dumpvloop()
void dumpvloop (int l)
...
Definition at line 4603 of file dump.c.
References dfile, dumpmemrefs(), dumpvinds(), gbl, hlv, HLVECT::lpavail, HLVECT::lpbase, NULL, putast(), putbit(), putint(), putline(), putmrlist(), putnzint(), putsclist(), VL_ALBND, VL_AUBND, VL_CAND, VL_DEL, VL_EALIST, VL_ICNT, VL_ILBND, VL_ISTART, VL_IUBND, VL_IVLIST, VL_LBND, VL_LPCNT, VL_MRCNT, VL_MRECNT, VL_MRSTART, VL_NEST, VL_PERF, VL_PREBIH, VL_SCLIST, VL_SIBLING, VL_UBND, VL_ZTRIP, VLP_ASSOC, VLP_DEPCHK, VLP_EQVCHK, VLP_LDSTSPLIT, VLP_LSTVAL, VLP_MINCNT, VLP_OPSPLIT, VLP_RECOG, VLP_SAFECALL, VLP_SHORTLP, and VLP_TRANS.
Referenced by dumpvnest(), and dumpvnest2().
dumpvloops()
void dumpvloops (void)
...
Definition at line 4672 of file dump.c.
References dfile, dumpvnest(), hlv, HLVECT::looplist, HLVECT::lpbase, NULL, and VL_SIBLING.
dumpvloops2()
void dumpvloops2 ()
Definition at line 4706 of file dump.c.
References dfile, dumpvnest2(), hlv, HLVECT::looplist, HLVECT::lpbase, NULL, opt, and VL_SIBLING.
dumpvnest()
void dumpvnest (int l)
Definition at line 4656 of file dump.c.
References dfile, dumpvloop(), dumpvnest(), gbl, hlv, HLVECT::lpbase, NULL, VL_CHILD, and VL_SIBLING.
Referenced by dumpvloops(), and dumpvnest().
dumpvnest2()
void dumpvnest2 (int l)
Definition at line 4685 of file dump.c.
References dfile, dumploop(), dumpvloop(), dumpvnest2(), gbl, hlv, HLVECT::lpbase, NULL, opt, VL_CHILD, and VL_SIBLING.
Referenced by dumpvloops2(), and dumpvnest2().
getdddir()
char * getdddir (DDEDGE * dd)
Definition at line 4383 of file dump.c.
References buf, DD_DIRVEC, DIRV_ALLEQ, DIRV_ENTRYG, DIRV_EQ, DIRV_GT, DIRV_LT, DIRV_RD, i, MAX_LOOPS, p, and t.
Referenced by putdd().
past()
void past (int astx)
Definition at line 1723 of file dump.c.
References dfile, gbl, and printast().
Referenced by build_array_list(), canonical_conversion(), check_alloc_ptr_type(), check_pointer_type(), do_distbegin(), forall_make_same_idx(), and put_forall_pcalls().
printname()
char * printname (int sptr)
...
Definition at line 1910 of file dump.c.
References b, CONVAL2G, cprintf(), DTY, ISZ_PF, STB::n_base, num, sptr, stb, SYMNAME, TY_CHAR, TY_DBLE, TY_FLOAT, TY_INT, TY_INT8, TY_QUAD, TY_WORD, and ui64toax().
Referenced by _printnme().
printnme()
void printnme (int n)
...
Definition at line 2082 of file dump.c.
References _printnme(), dfile, gbl, n, and putstring1().
Referenced by dumpdef(), and dumpuse().
put2int()
static void put2int (const char * s, int d1, int d2) static
Definition at line 89 of file dump.c.
References BUF, putit(), and s.
Referenced by dumploop(), and putnme().
put2int1()
static void put2int1 (int d1, int d2) static
Definition at line 110 of file dump.c.
References BUF, and putit().
Referenced by dast().
put_inkwd()
static void put_inkwd (const char * s, int k) static
Definition at line 412 of file dump.c.
References intrinsic_kwd, k, putstring(), and s.
Referenced by dsym().
putast()
static void putast (const char * s, int a) static
Definition at line 649 of file dump.c.
References a, astb, BUF, dfile, linelen, longlines, printast(), putit(), and s.
Referenced by dalnd(), dumpdt(), dumpmr(), dumpshape(), dumpvind(), and dumpvloop().
putasttype()
void putasttype (const char * s, int opc)
Definition at line 637 of file dump.c.
References astb, ASTB::atypes, BUF, dfile, gbl, putit(), and s.
Referenced by dast(), and dumpvind().
putbit()
static void putbit (const char * s, int b) static
Definition at line 588 of file dump.c.
References b, dfile, linelen, longlines, s, and strlen().
Referenced by dalnd(), dast(), dstd(), dsym(), dumpdef(), dumpdt(), dumpfnode(), dumploop(), dumpmr(), dumpuse(), dumpvind(), dumpvloop(), and putsclist().
putcharacter()
static void putcharacter (const char * s, char c) static
Definition at line 170 of file dump.c.
References BUF, putit(), and s.
Referenced by dumpmr().
putdd()
void putdd (DDEDGE * dd)
Definition at line 4426 of file dump.c.
References BUF, DD_SINK, DD_TYPE, dfile, gbl, getdddir(), NULL, and putit().
Referenced by putddlist().
putddlist()
void putddlist (const char * s, DDEDGE * ddlist)
Definition at line 4441 of file dump.c.
References DD_NEXT, NULL, putdd(), putline(), putstring1(), and s.
Referenced by dumpmr().
putdty()
static void putdty (const char * s, int dty) static
Definition at line 439 of file dump.c.
References BUF, NULL, putit(), s, stb, and STB::tynames.
Referenced by dumpdt().
putdtype()
static void putdtype (const char * s, int d) static
Definition at line 428 of file dump.c.
References BUF, d, getdtype(), putit(), and s.
Referenced by dast(), dsecd(), dsym(), and dumpdt().
putedge()
static void putedge (int d1, int d2) static
Definition at line 177 of file dump.c.
References BUF, and putit().
Referenced by dumpfgraph().
putflags()
static void putflags (const char * s, int flags) static
Definition at line 1731 of file dump.c.
References BUF, flags, putit(), and s.
Referenced by dstd().
putinkind()
static void putinkind (const char * s, int k) static
Definition at line 390 of file dump.c.
References k, putint(), putstring(), and s.
Referenced by dsym().
putint()
static void putint (const char * s, int d) static
Definition at line 69 of file dump.c.
References BUF, d, putit(), and s.
Referenced by _printnme(), dalnd(), dast(), dsecd(), dstd(), dsym(), dumpdef(), dumpdt(), dumpfnode(), dumploop(), dumpmr(), dumpnme(), dumpshape(), dumpsymi(), dumpuse(), dumpvind(), dumpvloop(), putinkind(), putnme(), putnmetype(), and putsclist().
putint1()
static void putint1 (int d) static
Definition at line 96 of file dump.c.
References BUF, d, and putit().
Referenced by dumpdef(), dumpfgraph(), dumploop(), dumpnme(), dumpuse(), and putmrlist().
putint1star()
static void putint1star (int d, int star, const char * starstring) static
Definition at line 117 of file dump.c.
References BUF, d, and putit().
Referenced by dumpfnode().
putintent()
static void putintent (const char * s, int intent) static
Definition at line 365 of file dump.c.
References BUF, intent, putit(), and s.
Referenced by dsym().
putit()
static void putit (void) static
Definition at line 37 of file dump.c.
References BUF, dfile, linelen, longlines, and strlen().
Referenced by dastli(), put2int(), put2int1(), putast(), putasttype(), putcharacter(), putdd(), putdty(), putdtype(), putedge(), putflags(), putint(), putint1(), putint1star(), putintent(), putnsym(), putnzbits(), putnzhex(), putnzint(), putsc(), putstring(), putstring1(), putstype(), putsym(), putsym1(), puttmplsc(), puttmpltype(), and putval().
putline()
static void putline (void) static
Definition at line 61 of file dump.c.
References dfile, and linelen.
Referenced by dalnd(), dast(), dsecd(), dsocptr(), dstd(), dsym(), dumpdef(), dumpdt(), dumpfgraph(), dumpfnode(), dumphashlk(), dumplists(), dumploop(), dumpmr(), dumpnme(), dumpshape(), dumpsymi(), dumpuse(), dumpvind(), dumpvloop(), putddlist(), putmrlist(), putparam(), putsclist(), and putsymlk().
putmrlist()
void putmrlist (const char * s, int ivlist)
Definition at line 4572 of file dump.c.
References i, MR_NEXT, putint1(), putline(), putstring1(), and s.
Referenced by dumpvloop().
putnme()
void putnme (int n)
Definition at line 1848 of file dump.c.
References appendstring1(), dfile, gbl, getprint(), n, NME_NM, NME_SYM, NME_TYPE, nmeb, NT_MEM, NT_VAR, put2int(), putint(), putnme(), and putstring1().
Referenced by dumploop(), dumpmr(), dumpvind(), putnme(), and putsclist().
putnmetype()
void putnmetype (const char * s, int t)
Definition at line 1879 of file dump.c.
References NT_ADD, NT_ARR, NT_IND, NT_MEM, NT_SAFE, NT_UNK, NT_VAR, putint(), putstring(), s, and t.
Referenced by dumpnme().
putnname()
static void putnname (const char * s, int off) static
Definition at line 420 of file dump.c.
References STB::n_base, off, putstring(), s, and stb.
Referenced by dsym().
putnsym()
static void putnsym (const char * s, int sptr) static
Definition at line 246 of file dump.c.
References BUF, DTY, STB::n_base, NOSYM, putit(), s, sptr, stb, SYMNAME, and TY_CHAR.
Referenced by dalnd(), dsecd(), dstd(), dsym(), dumpfnode(), dumpnme(), and putsclist().
putnzbits()
static void putnzbits (const char * s, int d) static
Definition at line 146 of file dump.c.
References b, BUF, d, putit(), s, and strlen().
Referenced by dalnd().
putnzhex()
static void putnzhex (const char * s, int d) static
Definition at line 137 of file dump.c.
References BUF, d, putit(), and s.
Referenced by dalnd().
putnzint()
static void putnzint (const char * s, int d) static
Definition at line 128 of file dump.c.
References BUF, d, putit(), and s.
Referenced by dast(), dstd(), dsym(), dumpdef(), dumpfnode(), dumploop(), dumpmr(), dumpnme(), dumpuse(), and dumpvloop().
putoptype()
static void putoptype (const char * s, int optype) static
Definition at line 690 of file dump.c.
References opt, optype(), putval(), s, and SIZEOF.
Referenced by dast().
putparam()
static void putparam (int dpdsc, int paramct) static
Definition at line 450 of file dump.c.
References aux, AUX::dpdsc_base, putline(), putstring1(), putsym1(), and sptr.
Referenced by dsym().
putsc()
static void putsc (const char * s, int sc) static
Definition at line 290 of file dump.c.
References BUF, putit(), s, STB::scnames, and stb.
Referenced by dsym().
putsclist()
void putsclist (const char * s, int sclist)
...
Definition at line 4585 of file dump.c.
References putbit(), putint(), putline(), putnme(), putnsym(), putstring1(), s, SCLR_ARRSYM, SCLR_FLAG, SCLR_MASKSYM, SCLR_NEXT, SCLR_NME, and SCLR_SPAN.
Referenced by dumpvloop().
putslnk1()
void putslnk1 (int list)
Definition at line 480 of file dump.c.
References dfile, gbl, list, NOSYM, and putsym1().
Referenced by dumplists().
putstring()
static void putstring (const char * s, const char * t) static
Definition at line 269 of file dump.c.
References BUF, putit(), s, and t.
Referenced by dalnd(), dstd(), dsym(), dumpfnode(), dumploop(), put_inkwd(), putinkind(), putnmetype(), putnname(), and putval().
putstring1()
static void putstring1 (const char * t) static
Definition at line 276 of file dump.c.
References BUF, putit(), and t.
Referenced by dast(), dsocptr(), dumpdef(), dumpfnode(), dumplists(), dumploop(), dumpnme(), dumpuse(), printnme(), putddlist(), putmrlist(), putnme(), putparam(), putsclist(), and putsymlk().
putstype()
static void putstype (const char * s, int stype) static
Definition at line 301 of file dump.c.
References BUF, putit(), s, stb, and STB::stypes.
Referenced by dsym().
putstype1()
static void putstype1 (int stype) static
Definition at line 312 of file dump.c.
References appendit(), BUF, stb, and STB::stypes.
Referenced by dumplists().
putsym()
static void putsym (const char * s, int sptr) static
Definition at line 184 of file dump.c.
References BUF, NOSYM, putit(), s, sptr, stb, and SYMNAME.
Referenced by dast(), dsym(), and dumpdt().
putsym1()
static void putsym1 (int sptr) static
Definition at line 197 of file dump.c.
References BUF, NOSYM, putit(), sptr, stb, and SYMNAME.
Referenced by dsocptr(), dsym(), dumphashlk(), putparam(), putslnk1(), putsymilist(), and putsymlk().
putsymilist()
static void putsymilist (int symi) static
Definition at line 225 of file dump.c.
References putsym1(), SYMI_NEXT, and SYMI_SPTR.
Referenced by dsym(), and dumpsymi().
putsymlk()
void putsymlk (const char * name, int list)
Definition at line 467 of file dump.c.
References dfile, gbl, list, name, NOSYM, putline(), putstring1(), and putsym1().
Referenced by dsym(), and dumpdt().
puttmplflag()
void puttmplflag (char * s, int f)
Definition at line 2515 of file dump.c.
References dfile, f, linelen, s, and strlen().
puttmplsc()
void puttmplsc (const char * s, int t)
Definition at line 2488 of file dump.c.
References ALLOC_SC, BUF, COMMON_SC, dfile, DUMMY_SC, gbl, NONE_SC, putit(), s, STATIC_SC, and t.
Referenced by dalnd().
puttmpltype()
void puttmpltype (const char * s, int t)
Definition at line 2464 of file dump.c.
References ALIGNED, BUF, dfile, DISTRIBUTED, gbl, INHERITED, putit(), REPLICATED, s, and t.
Referenced by dalnd().
putval()
static void putval (const char * s, int val, const char * values[], int sizeofvalues) static
Definition at line 677 of file dump.c.
References BUF, putit(), putstring(), s, and val.
Referenced by emit_init(), put_dcmplx_n(), and putoptype().
Variable Documentation
BUF
char BUF[900] static
Definition at line 32 of file dump.c.
Referenced by appendint1(), appendit(), appendstring1(), dastli(), put2int(), put2int1(), putast(), putasttype(), putcharacter(), putdd(), putdty(), putdtype(), putedge(), putflags(), putint(), putint1(), putint1star(), putintent(), putit(), putnsym(), putnzbits(), putnzhex(), putnzint(), putsc(), putstring(), putstring1(), putstype(), putstype1(), putsym(), putsym1(), puttmplsc(), puttmpltype(), and putval().
dfile
FILE* dfile static
Definition at line 30 of file dump.c.
Referenced by _printnme(), appendit(), check(), dalnd(), dast(), dastree(), dastreex(), dcommon(), dcommons(), dlist(), dmp_const(), dsecd(), dsocptr(), dsstd(), dsstds(), dstd(), dstdps(), dstdr(), dstds(), dstdtree(), dsym(), dump_ilmfile_state(), dump_outliner(), dumpdef(), dumpdeflist(), dumpdefs(), dumpdt(), dumpdts(), dumpfgraph(), dumpfnode(), dumphashlk(), dumplists(), dumploop(), dumploops(), dumpmr(), dumpnme(), dumpnmes(), dumpshape(), dumpshapes(), dumpstdtrees(), dumpsymi(), dumpuse(), dumpuses(), dumpvind(), dumpvinds(), dumpvloop(), dumpvloops(), dumpvloops2(), dumpvnest(), dumpvnest2(), past(), printnme(), put_prefix(), putast(), putasttype(), putbit(), putdd(), putit(), putline(), putnme(), putslnk1(), putsymlk(), puttmplflag(), puttmplsc(), puttmpltype(), and use_hash_dump_one().
linelen
int linelen = 0 static
Definition at line 31 of file dump.c.
Referenced by appendit(), dsym(), putast(), putbit(), putit(), putline(), and puttmplflag().
longlines
int longlines = 1 static
Definition at line 34 of file dump.c.
Referenced by dastree(), putast(), putbit(), and putit().
prefix
char prefix[500] static
Definition at line 1410 of file dump.c.
Referenced by dastree(), and dastreex().