flang: dwarf2.h File Reference
dwarf2.h File Reference
Manifest constants, etc. used in for DWARF2/DWARF3 emission. DWARF versions 2 and 3.
Macros
#define DWARF_VERSION 2
#define DWARF_VERSION3 3
#define DWARF_VERSION4 4
#define DW_TAG_padding 0x00
#define DW_TAG_array_type 0x01
#define DW_TAG_class_type 0x02
#define DW_TAG_entry_point 0x03
#define DW_TAG_enumeration_type 0x04
#define DW_TAG_formal_parameter 0x05
#define DW_TAG_imported_declaration 0x08
#define DW_TAG_label 0x0a
#define DW_TAG_lexical_block 0x0b
#define DW_TAG_member 0x0d
#define DW_TAG_pointer_type 0x0f
#define DW_TAG_reference_type 0x10
#define DW_TAG_compile_unit 0x11
#define DW_TAG_string_type 0x12
#define DW_TAG_structure_type 0x13
#define DW_TAG_subroutine_type 0x15
#define DW_TAG_typedef 0x16
#define DW_TAG_union_type 0x17
#define DW_TAG_unspecified_parameters 0x18
#define DW_TAG_variant 0x19
#define DW_TAG_common_block 0x1a
#define DW_TAG_common_inclusion 0x1b
#define DW_TAG_inheritance 0x1c
#define DW_TAG_inlined_subroutine 0x1d
#define DW_TAG_module 0x1e
#define DW_TAG_ptr_to_member_type 0x1f
#define DW_TAG_set_type 0x20
#define DW_TAG_subrange_type 0x21
#define DW_TAG_with_stmt 0x22
#define DW_TAG_access_declaration 0x23
#define DW_TAG_base_type 0x24
#define DW_TAG_catch_block 0x25
#define DW_TAG_const_type 0x26
#define DW_TAG_constant 0x27
#define DW_TAG_enumerator 0x28
#define DW_TAG_file_type 0x29
#define DW_TAG_friend 0x2a
#define DW_TAG_namelist 0x2b
#define DW_TAG_namelist_item 0x2c
#define DW_TAG_packed_type 0x2d
#define DW_TAG_subprogram 0x2e
#define DW_TAG_template_type_param 0x2f
#define DW_TAG_template_value_param 0x30
#define DW_TAG_thrown_type 0x31
#define DW_TAG_try_block 0x32
#define DW_TAG_variant_part 0x33
#define DW_TAG_variable 0x34
#define DW_TAG_volatile_type 0x35
#define DW_TAG_dwarf_procedure 0x36
#define DW_TAG_restrict_type 0x37
#define DW_TAG_interface_type 0x38
#define DW_TAG_namespace 0x39
#define DW_TAG_imported_module 0x3a
#define DW_TAG_unspecified_type 0x3b
#define DW_TAG_partial_unit 0x3c
#define DW_TAG_imported_unit 0x3d
#define DW_TAG_condition 0x3f
#define DW_TAG_shared_type 0x40
#define DW_TAG_auto_variable 0x100
#define DW_TAG_arg_variable 0x101
#define DW_TAG_MIPS_loop 0x4081
#define DW_TAG_HP_array_descriptor 0x4090
#define DW_TAG_format_label 0x4101
#define DW_TAG_function_template 0x4102
#define DW_TAG_class_template 0x4103
#define DW_TAG_GNU_BINCL 0x4104
#define DW_TAG_GNU_EINCL 0x4105
#define DW_TAG_upc_shared_type 0x8765
#define DW_TAG_upc_strict_type 0x8766
#define DW_TAG_upc_relaxed_type 0x8767
#define DW_TAG_kanji_type 0xA000
#define DW_TAG_interface_block 0xA020
#define DW_TAG_lo_user 0x4080
#define DW_TAG_hi_user 0xffff
#define DW_children_no 0
#define DW_children_yes 1
#define DW_FORM_addr 0x01
#define DW_FORM_block2 0x03
#define DW_FORM_block4 0x04
#define DW_FORM_data2 0x05
#define DW_FORM_data4 0x06
#define DW_FORM_data8 0x07
#define DW_FORM_string 0x08
#define DW_FORM_block 0x09
#define DW_FORM_block1 0x0a
#define DW_FORM_data1 0x0b
#define DW_FORM_flag 0x0c
#define DW_FORM_sdata 0x0d
#define DW_FORM_strp 0x0e
#define DW_FORM_udata 0x0f
#define DW_FORM_ref_addr 0x10
#define DW_FORM_ref1 0x11
#define DW_FORM_ref2 0x12
#define DW_FORM_ref4 0x13
#define DW_FORM_ref8 0x14
#define DW_FORM_ref_udata 0x15
#define DW_FORM_indirect 0x16
#define DW_FORM_sec_offset 0x17 /* v. 4 */
#define DW_FORM_exprloc 0x18 /* v. 4 */
#define DW_FORM_flag_present 0x19 /* v. 4 */
#define DW_FORM_ref_sig8 0x20 /* v. 4 */
#define DW_AT_sibling 0x01
#define DW_AT_location 0x02
#define DW_AT_name 0x03
#define DW_AT_ordering 0x09
#define DW_AT_subscr_data 0x0a
#define DW_AT_byte_size 0x0b
#define DW_AT_bit_offset 0x0c
#define DW_AT_bit_size 0x0d
#define DW_AT_element_list 0x0f
#define DW_AT_stmt_list 0x10
#define DW_AT_low_pc 0x11
#define DW_AT_high_pc 0x12
#define DW_AT_language 0x13
#define DW_AT_member 0x14
#define DW_AT_discr 0x15
#define DW_AT_discr_value 0x16
#define DW_AT_visibility 0x17
#define DW_AT_import 0x18
#define DW_AT_string_length 0x19
#define DW_AT_common_reference 0x1a
#define DW_AT_comp_dir 0x1b
#define DW_AT_const_value 0x1c
#define DW_AT_containing_type 0x1d
#define DW_AT_default_value 0x1e
#define DW_AT_inline 0x20
#define DW_AT_is_optional 0x21
#define DW_AT_lower_bound 0x22
#define DW_AT_producer 0x25
#define DW_AT_prototyped 0x27
#define DW_AT_return_addr 0x2a
#define DW_AT_start_scope 0x2c
#define DW_AT_stride_size 0x2e
#define DW_AT_upper_bound 0x2f
#define DW_AT_abstract_origin 0x31
#define DW_AT_accessibility 0x32
#define DW_AT_address_class 0x33
#define DW_AT_artificial 0x34
#define DW_AT_base_types 0x35
#define DW_AT_calling_convention 0x36
#define DW_AT_count 0x37
#define DW_AT_data_member_location 0x38
#define DW_AT_decl_column 0x39
#define DW_AT_decl_file 0x3a
#define DW_AT_decl_line 0x3b
#define DW_AT_declaration 0x3c
#define DW_AT_discr_list 0x3d
#define DW_AT_encoding 0x3e
#define DW_AT_external 0x3f
#define DW_AT_frame_base 0x40
#define DW_AT_friend 0x41
#define DW_AT_identifier_case 0x42
#define DW_AT_macro_info 0x43
#define DW_AT_namelist_item 0x44
#define DW_AT_priority 0x45
#define DW_AT_segment 0x46
#define DW_AT_specification 0x47
#define DW_AT_static_link 0x48
#define DW_AT_type 0x49
#define DW_AT_use_location 0x4a
#define DW_AT_variable_parameter 0x4b
#define DW_AT_virtuality 0x4c
#define DW_AT_vtable_elem_location 0x4d
#define DW_AT_bit_stride 0x2e /* official name */
#define DW_AT_allocated 0x4e
#define DW_AT_associated 0x4f
#define DW_AT_data_location 0x50
#define DW_AT_stride 0x51
#define DW_AT_byte_stride 0x51 /* official name */
#define DW_AT_entry_pc 0x52
#define DW_AT_use_UTF8 0x53
#define DW_AT_extension 0x54
#define DW_AT_ranges 0x55
#define DW_AT_trampoline 0x56
#define DW_AT_call_column 0x57
#define DW_AT_call_file 0x58
#define DW_AT_call_line 0x59
#define DW_AT_description 0x5a
#define DW_AT_binary_scale 0x5b
#define DW_AT_decimal_scale 0x5c
#define DW_AT_small 0x5d
#define DW_AT_decimal_sign 0x5e
#define DW_AT_digit_count 0x5f
#define DW_AT_picture_string 0x60
#define DW_AT_mutable 0x61
#define DW_AT_threads_scaled 0x62
#define DW_AT_explicit 0x63
#define DW_AT_object_pointer 0x64
#define DW_AT_endianity 0x65
#define DW_AT_elemental 0x66
#define DW_AT_pure 0x67
#define DW_AT_recursive 0x68
#define DW_AT_MIPS_fde 0x2001
#define DW_AT_MIPS_loop_begin 0x2002
#define DW_AT_MIPS_tail_loop_begin 0x2003
#define DW_AT_MIPS_epilog_begin 0x2004
#define DW_AT_MIPS_loop_unroll_factor 0x2005
#define DW_AT_MIPS_software_pipeline_depth 0x2006
#define DW_AT_MIPS_linkage_name 0x2007 /* supported by PGI */
#define DW_AT_MIPS_stride 0x2008
#define DW_AT_MIPS_abstract_name 0x2009
#define DW_AT_MIPS_clone_origin 0x200a
#define DW_AT_MIPS_has_inlines 0x200b
#define DW_AT_HP_block_index 0x2000
#define DW_AT_HP_unmodifiable 0x2001
#define DW_AT_HP_actuals_stmt_list 0x2010
#define DW_AT_HP_proc_per_section 0x2011
#define DW_AT_HP_raw_data_ptr 0x2012
#define DW_AT_HP_pass_by_reference 0x2013
#define DW_AT_HP_opt_level 0x2014
#define DW_AT_HP_prof_version_id 0x2015
#define DW_AT_HP_opt_flags 0x2016
#define DW_AT_HP_cold_region_low_pc 0x2017
#define DW_AT_HP_cold_region_high_pc 0x2018
#define DW_AT_HP_all_variables_modifiable 0x2019
#define DW_AT_HP_linkage_name 0x201a
#define DW_AT_HP_prof_flags 0x201b
#define DW_AT_sf_names 0x2101
#define DW_AT_src_info 0x2102
#define DW_AT_mac_info 0x2103
#define DW_AT_src_coords 0x2104
#define DW_AT_body_begin 0x2105
#define DW_AT_body_end 0x2106
#define DW_AT_GNU_vector 0x2107
#define DW_AT_VMS_rtnbeg_pd_address 0x2201
#define DW_AT_upc_threads_scaled 0x3210
#define DW_AT_lbase 0x3a00
#define DW_AT_soffset 0x3a01
#define DW_AT_lstride 0x3a02
#define DW_AT_APPLE_optimized 0x3fe1
#define DW_AT_APPLE_flags 0x3fe2
#define DW_AT_APPLE_isa 0x3fe3
#define DW_AT_APPLE_block 0x3fe4
#define DW_AT_APPLE_major_runtime_vers 0x3fe5
#define DW_AT_APPLE_runtime_class 0x3fe6
#define DW_AT_APPLE_omit_frame_ptr 0x3fe7
#define DW_AT_APPLE_property_name 0x3fe8
#define DW_AT_APPLE_property_getter 0x3fe9
#define DW_AT_APPLE_property_setter 0x3fea
#define DW_AT_APPLE_property_attribute 0x3feb
#define DW_AT_APPLE_objc_complete_type 0x3fec
#define DW_AT_APPLE_property 0x3fed
#define DW_AT_lo_user 0x2000
#define DW_AT_hi_user 0x3fff
#define DW_OP_addr 0x03
#define DW_OP_deref 0x06
#define DW_OP_const1u 0x08
#define DW_OP_const1s 0x09
#define DW_OP_const2u 0x0a
#define DW_OP_const2s 0x0b
#define DW_OP_const4u 0x0c
#define DW_OP_const4s 0x0d
#define DW_OP_const8u 0x0e
#define DW_OP_const8s 0x0f
#define DW_OP_constu 0x10
#define DW_OP_consts 0x11
#define DW_OP_dup 0x12
#define DW_OP_drop 0x13
#define DW_OP_over 0x14
#define DW_OP_pick 0x15
#define DW_OP_swap 0x16
#define DW_OP_rot 0x17
#define DW_OP_xderef 0x18
#define DW_OP_abs 0x19
#define DW_OP_and 0x1a
#define DW_OP_div 0x1b
#define DW_OP_minus 0x1c
#define DW_OP_mod 0x1d
#define DW_OP_mul 0x1e
#define DW_OP_neg 0x1f
#define DW_OP_not 0x20
#define DW_OP_or 0x21
#define DW_OP_plus 0x22
#define DW_OP_plus_uconst 0x23
#define DW_OP_shl 0x24
#define DW_OP_shr 0x25
#define DW_OP_shra 0x26
#define DW_OP_xor 0x27
#define DW_OP_bra 0x28
#define DW_OP_eq 0x29
#define DW_OP_ge 0x2a
#define DW_OP_gt 0x2b
#define DW_OP_le 0x2c
#define DW_OP_lt 0x2d
#define DW_OP_ne 0x2e
#define DW_OP_skip 0x2f
#define DW_OP_lit0 0x30
#define DW_OP_lit1 0x31
#define DW_OP_lit2 0x32
#define DW_OP_lit3 0x33
#define DW_OP_lit4 0x34
#define DW_OP_lit5 0x35
#define DW_OP_lit6 0x36
#define DW_OP_lit7 0x37
#define DW_OP_lit8 0x38
#define DW_OP_lit9 0x39
#define DW_OP_lit10 0x3a
#define DW_OP_lit11 0x3b
#define DW_OP_lit12 0x3c
#define DW_OP_lit13 0x3d
#define DW_OP_lit14 0x3e
#define DW_OP_lit15 0x3f
#define DW_OP_lit16 0x40
#define DW_OP_lit17 0x41
#define DW_OP_lit18 0x42
#define DW_OP_lit19 0x43
#define DW_OP_lit20 0x44
#define DW_OP_lit21 0x45
#define DW_OP_lit22 0x46
#define DW_OP_lit23 0x47
#define DW_OP_lit24 0x48
#define DW_OP_lit25 0x49
#define DW_OP_lit26 0x4a
#define DW_OP_lit27 0x4b
#define DW_OP_lit28 0x4c
#define DW_OP_lit29 0x4d
#define DW_OP_lit30 0x4e
#define DW_OP_lit31 0x4f
#define DW_OP_reg0 0x50
#define DW_OP_reg1 0x51
#define DW_OP_reg2 0x52
#define DW_OP_reg3 0x53
#define DW_OP_reg4 0x54
#define DW_OP_reg5 0x55
#define DW_OP_reg6 0x56
#define DW_OP_reg7 0x57
#define DW_OP_reg8 0x58
#define DW_OP_reg9 0x59
#define DW_OP_reg10 0x5a
#define DW_OP_reg11 0x5b
#define DW_OP_reg12 0x5c
#define DW_OP_reg13 0x5d
#define DW_OP_reg14 0x5e
#define DW_OP_reg15 0x5f
#define DW_OP_reg16 0x60
#define DW_OP_reg17 0x61
#define DW_OP_reg18 0x62
#define DW_OP_reg19 0x63
#define DW_OP_reg20 0x64
#define DW_OP_reg21 0x65
#define DW_OP_reg22 0x66
#define DW_OP_reg23 0x67
#define DW_OP_reg24 0x68
#define DW_OP_reg25 0x69
#define DW_OP_reg26 0x6a
#define DW_OP_reg27 0x6b
#define DW_OP_reg28 0x6c
#define DW_OP_reg29 0x6d
#define DW_OP_reg30 0x6e
#define DW_OP_reg31 0x6f
#define DW_OP_breg0 0x70
#define DW_OP_breg1 0x71
#define DW_OP_breg2 0x72
#define DW_OP_breg3 0x73
#define DW_OP_breg4 0x74
#define DW_OP_breg5 0x75
#define DW_OP_breg6 0x76
#define DW_OP_breg7 0x77
#define DW_OP_breg8 0x78
#define DW_OP_breg9 0x79
#define DW_OP_breg10 0x7a
#define DW_OP_breg11 0x7b
#define DW_OP_breg12 0x7c
#define DW_OP_breg13 0x7d
#define DW_OP_breg14 0x7e
#define DW_OP_breg15 0x7f
#define DW_OP_breg16 0x80
#define DW_OP_breg17 0x81
#define DW_OP_breg18 0x82
#define DW_OP_breg19 0x83
#define DW_OP_breg20 0x84
#define DW_OP_breg21 0x85
#define DW_OP_breg22 0x86
#define DW_OP_breg23 0x87
#define DW_OP_breg24 0x88
#define DW_OP_breg25 0x89
#define DW_OP_breg26 0x8a
#define DW_OP_breg27 0x8b
#define DW_OP_breg28 0x8c
#define DW_OP_breg29 0x8d
#define DW_OP_breg30 0x8e
#define DW_OP_breg31 0x8f
#define DW_OP_regx 0x90
#define DW_OP_fbreg 0x91
#define DW_OP_bregx 0x92
#define DW_OP_piece 0x93
#define DW_OP_deref_size 0x94
#define DW_OP_xderef_size 0x95
#define DW_OP_nop 0x96
#define DW_OP_push_object_address 0x97
#define DW_OP_call2 0x98
#define DW_OP_call4 0x99
#define DW_OP_call_ref 0x9a
#define DW_OP_form_tls_address 0x9b
#define DW_OP_call_frame_cfa 0x9c
#define DW_OP_bit_piece 0x9d
#define DW_OP_implicit_value 0x9e
#define DW_OP_stack_value 0x9f
#define DW_OP_GNU_push_tls_address 0xe0
#define DW_OP_GNU_uninit 0xf0
#define DW_OP_HP_unknown 0xe0
#define DW_OP_HP_is_value 0xe1
#define DW_OP_HP_fltconst4 0xe2
#define DW_OP_HP_fltconst8 0xe3
#define DW_OP_HP_mod_range 0xe4
#define DW_OP_HP_unmod_range 0xe5
#define DW_OP_HP_tls 0xe6
#define DW_OP_PGI_omp_thread_num 0xf8
#define DW_OP_lo_user 0xe0
#define DW_OP_hi_user 0xff
#define DW_ATE_address 0x1
#define DW_ATE_boolean 0x2
#define DW_ATE_complex_float 0x3
#define DW_ATE_float 0x4
#define DW_ATE_signed 0x5
#define DW_ATE_signed_char 0x6
#define DW_ATE_unsigned 0x7
#define DW_ATE_unsigned_char 0x8
#define DW_ATE_imaginary_float 0x09
#define DW_ATE_packed_decimal 0x0a
#define DW_ATE_numeric_string 0x0b
#define DW_ATE_edited 0x0c
#define DW_ATE_signed_fixed 0x0d
#define DW_ATE_unsigned_fixed 0x0e
#define DW_ATE_decimal_float 0x0f
#define DW_ATE_HP_float80 0x80
#define DW_ATE_HP_complex_float80 0x81
#define DW_ATE_HP_float128 0x82
#define DW_ATE_HP_complex_float128 0x83
#define DW_ATE_HP_floathpintel 0x84
#define DW_ATE_HP_imaginary_float80 0x85
#define DW_ATE_HP_imaginary_float128 0x86
#define DW_ATE_lo_user 0x80
#define DW_ATE_hi_user 0xff
#define DW_ACCESS_public 1
#define DW_ACCESS_protected 2
#define DW_ACCESS_private 3
#define DW_VIS_local 1
#define DW_VIS_exported 2
#define DW_VIS_qualified 3
#define DW_VIRTUALITY_none 0
#define DW_VIRTUALITY_virtual 1
#define DW_VIRTUALITY_pure_virtual 2
#define DW_LANG_C89 0x0001
#define DW_LANG_C 0x0002
#define DW_LANG_Ada83 0x0003
#define DW_LANG_C_plus_plus 0x0004
#define DW_LANG_Cobol74 0x0005
#define DW_LANG_Cobol85 0x0006
#define DW_LANG_Fortran77 0x0007
#define DW_LANG_Fortran90 0x0008
#define DW_LANG_Pascal83 0x0009
#define DW_LANG_Modula2 0x000a
#define DW_LANG_Java 0x000b
#define DW_LANG_C99 0x000c
#define DW_LANG_Ada95 0x000d
#define DW_LANG_Fortran95 0x000e
#define DW_LANG_PLI 0x000f
#define DW_LANG_ObjC 0x0010
#define DW_LANG_ObjC_plus_plus 0x0011
#define DW_LANG_UPC 0x0012
#define DW_LANG_D 0x0013
#define DW_LANG_Mips_Assembler 0x8001
#define DW_LANG_Upc 0x8765
#define DW_LANG_lo_user 0x8000
#define DW_LANG_hi_user 0xffff
#define DW_ID_case_sensitive 0
#define DW_ID_up_case 1
#define DW_ID_down_case 2
#define DW_ID_case_insensitive 3
#define DW_CC_normal 0x1
#define DW_CC_program 0x2
#define DW_CC_nocall 0x3
#define DW_CC_GNU_renesas_sh 0x40
#define DW_CC_lo_user 0x40
#define DW_CC_hi_user 0xff
#define DW_INL_not_inlined 0
#define DW_INL_inlined 1
#define DW_INL_declared_not_inlined 2
#define DW_INL_declared_inlined 3
#define DW_ORD_row_major 0
#define DW_ORD_col_major 1
#define DW_DSC_label 0
#define DW_DSC_range 1
#define DW_LNS_copy 0x01
#define DW_LNS_advance_pc 0x02
#define DW_LNS_advance_line 0x03
#define DW_LNS_set_file 0x04
#define DW_LNS_set_column 0x05
#define DW_LNS_negate_stmt 0x06
#define DW_LNS_set_basic_block 0x07
#define DW_LNS_const_add_pc 0x08
#define DW_LNS_fixed_advance_pc 0x09
#define DW_LNS_set_prologue_end 0x0a
#define DW_LNS_set_epilogue_begin 0x0b
#define DW_LNS_set_isa 0x0c
#define DW_LNE_end_sequence 1
#define DW_LNE_set_address 2
#define DW_LNE_define_file 3
#define DW_LNE_set_discriminator 4
#define DW_LNE_HP_negate_is_UV_update 0x11
#define DW_LNE_HP_push_context 0x12
#define DW_LNE_HP_pop_context 0x13
#define DW_LNE_HP_set_file_line_column 0x14
#define DW_LNE_HP_set_routine_name 0x15
#define DW_LNE_HP_set_sequence 0x16
#define DW_LNE_HP_negate_post_semantics 0x17
#define DW_LNE_HP_negate_function_exit 0x18
#define DW_LNE_HP_negate_front_end_logical 0x19
#define DW_LNE_HP_define_proc 0x20
#define DW_LNE_lo_user 0x80
#define DW_LNE_hi_user 0xff
#define DW_MACINFO_define 1
#define DW_MACINFO_undef 2
#define DW_MACINFO_start_file 3
#define DW_MACINFO_end_file 4
#define DW_MACINFO_vendor_ext 255
#define DW_CFA_advance_loc 0x40
#define DW_CFA_offset 0x80
#define DW_CFA_restore 0xc0
#define DW_CFA_extended 0
#define DW_CFA_nop 0x00
#define DW_CFA_set_loc 0x01
#define DW_CFA_advance_loc1 0x02
#define DW_CFA_advance_loc2 0x03
#define DW_CFA_advance_loc4 0x04
#define DW_CFA_offset_extended 0x05
#define DW_CFA_restore_extended 0x06
#define DW_CFA_undefined 0x07
#define DW_CFA_same_value 0x08
#define DW_CFA_register 0x09
#define DW_CFA_remember_state 0x0a
#define DW_CFA_restore_state 0x0b
#define DW_CFA_def_cfa 0x0c
#define DW_CFA_def_cfa_register 0x0d
#define DW_CFA_def_cfa_offset 0x0e
#define DW_CFA_def_cfa_expression 0x0f
#define DW_CFA_expression 0x10
#define DW_CFA_offset_extended_sf 0x11
#define DW_CFA_def_cfa_sf 0x12
#define DW_CFA_def_cfa_offset_sf 0x13
#define DW_CFA_val_offset 0x14
#define DW_CFA_val_offset_sf 0x15
#define DW_CFA_val_expression 0x16
#define DW_CFA_MIPS_advance_loc8 0x1d
#define DW_CFA_GNU_window_save 0x2d
#define DW_CFA_GNU_args_size 0x2e
#define DW_CFA_GNU_negative_offset_extended 0x2f
#define DW_CFA_low_user 0x1c
#define DW_CFA_high_user 0x3f
#define DW_CHILDREN_no 0x00
#define DW_CHILDREN_yes 0x01
#define DW_ADDR_none 0
#define DW_TAG_nameless_struct (0x0050)
#define DW_TAG_nameless_union (0x0051)
#define DW_TAG_nameless_class (0x0052)
#define DW_TAG_nameless_enumeration (0x0053)
#define DW_TAG_include_table (0x0054)
#define DW_TAG_void_type (0x0055)
Functions
const char * dwarf_tag_name (unsigned)
Convert a DW_TAG_* constant to the corresponding string.
const char * dwarf_attr_name (unsigned)
const char * dwarf_form_name (unsigned)
const char * dwarf_stack_op_name (unsigned)
const char * dwarf_virtuality_name (unsigned)
const char * dwarf_lang_name (unsigned)
const char * dwarf_encoding_name (unsigned)
void emit_dwf2_ftn_func_begin (int sptr)
void input_dwarf_info (char *filename)
void dwarf_get_fn (char *filename)
Detailed Description
Manifest constants, etc. used in for DWARF2/DWARF3 emission. DWARF versions 2 and 3.
Definition in file dwarf2.h.
Macro Definition Documentation
DW_ACCESS_private
#define DW_ACCESS_private 3
Definition at line 500 of file dwarf2.h.
DW_ACCESS_protected
#define DW_ACCESS_protected 2
Definition at line 499 of file dwarf2.h.
DW_ACCESS_public
#define DW_ACCESS_public 1
Definition at line 498 of file dwarf2.h.
DW_ADDR_none
#define DW_ADDR_none 0
Definition at line 650 of file dwarf2.h.
DW_AT_abstract_origin
#define DW_AT_abstract_origin 0x31
Definition at line 177 of file dwarf2.h.
DW_AT_accessibility
#define DW_AT_accessibility 0x32
Definition at line 178 of file dwarf2.h.
DW_AT_address_class
#define DW_AT_address_class 0x33
Definition at line 179 of file dwarf2.h.
DW_AT_allocated
#define DW_AT_allocated 0x4e
Definition at line 208 of file dwarf2.h.
DW_AT_APPLE_block
#define DW_AT_APPLE_block 0x3fe4
Definition at line 283 of file dwarf2.h.
DW_AT_APPLE_flags
#define DW_AT_APPLE_flags 0x3fe2
Definition at line 281 of file dwarf2.h.
DW_AT_APPLE_isa
#define DW_AT_APPLE_isa 0x3fe3
Definition at line 282 of file dwarf2.h.
DW_AT_APPLE_major_runtime_vers
#define DW_AT_APPLE_major_runtime_vers 0x3fe5
Definition at line 284 of file dwarf2.h.
DW_AT_APPLE_objc_complete_type
#define DW_AT_APPLE_objc_complete_type 0x3fec
Definition at line 291 of file dwarf2.h.
DW_AT_APPLE_omit_frame_ptr
#define DW_AT_APPLE_omit_frame_ptr 0x3fe7
Definition at line 286 of file dwarf2.h.
DW_AT_APPLE_optimized
#define DW_AT_APPLE_optimized 0x3fe1
Definition at line 280 of file dwarf2.h.
DW_AT_APPLE_property
#define DW_AT_APPLE_property 0x3fed
Definition at line 292 of file dwarf2.h.
DW_AT_APPLE_property_attribute
#define DW_AT_APPLE_property_attribute 0x3feb
Definition at line 290 of file dwarf2.h.
DW_AT_APPLE_property_getter
#define DW_AT_APPLE_property_getter 0x3fe9
Definition at line 288 of file dwarf2.h.
DW_AT_APPLE_property_name
#define DW_AT_APPLE_property_name 0x3fe8
Definition at line 287 of file dwarf2.h.
DW_AT_APPLE_property_setter
#define DW_AT_APPLE_property_setter 0x3fea
Definition at line 289 of file dwarf2.h.
DW_AT_APPLE_runtime_class
#define DW_AT_APPLE_runtime_class 0x3fe6
Definition at line 285 of file dwarf2.h.
DW_AT_artificial
#define DW_AT_artificial 0x34
Definition at line 180 of file dwarf2.h.
DW_AT_associated
#define DW_AT_associated 0x4f
Definition at line 209 of file dwarf2.h.
DW_AT_base_types
#define DW_AT_base_types 0x35
Definition at line 181 of file dwarf2.h.
DW_AT_binary_scale
#define DW_AT_binary_scale 0x5b
Definition at line 222 of file dwarf2.h.
DW_AT_bit_offset
#define DW_AT_bit_offset 0x0c
Definition at line 150 of file dwarf2.h.
DW_AT_bit_size
#define DW_AT_bit_size 0x0d
Definition at line 151 of file dwarf2.h.
DW_AT_bit_stride
#define DW_AT_bit_stride 0x2e /* official name */
Definition at line 207 of file dwarf2.h.
DW_AT_body_begin
#define DW_AT_body_begin 0x2105
Definition at line 268 of file dwarf2.h.
DW_AT_body_end
#define DW_AT_body_end 0x2106
Definition at line 269 of file dwarf2.h.
DW_AT_byte_size
#define DW_AT_byte_size 0x0b
Definition at line 149 of file dwarf2.h.
DW_AT_byte_stride
#define DW_AT_byte_stride 0x51 /* official name */
Definition at line 212 of file dwarf2.h.
DW_AT_call_column
#define DW_AT_call_column 0x57
Definition at line 218 of file dwarf2.h.
DW_AT_call_file
#define DW_AT_call_file 0x58
Definition at line 219 of file dwarf2.h.
DW_AT_call_line
#define DW_AT_call_line 0x59
Definition at line 220 of file dwarf2.h.
DW_AT_calling_convention
#define DW_AT_calling_convention 0x36
Definition at line 182 of file dwarf2.h.
DW_AT_common_reference
#define DW_AT_common_reference 0x1a
Definition at line 163 of file dwarf2.h.
DW_AT_comp_dir
#define DW_AT_comp_dir 0x1b
Definition at line 164 of file dwarf2.h.
DW_AT_const_value
#define DW_AT_const_value 0x1c
Definition at line 165 of file dwarf2.h.
DW_AT_containing_type
#define DW_AT_containing_type 0x1d
Definition at line 166 of file dwarf2.h.
DW_AT_count
#define DW_AT_count 0x37
Definition at line 183 of file dwarf2.h.
DW_AT_data_location
#define DW_AT_data_location 0x50
Definition at line 210 of file dwarf2.h.
DW_AT_data_member_location
#define DW_AT_data_member_location 0x38
Definition at line 184 of file dwarf2.h.
DW_AT_decimal_scale
#define DW_AT_decimal_scale 0x5c
Definition at line 223 of file dwarf2.h.
DW_AT_decimal_sign
#define DW_AT_decimal_sign 0x5e
Definition at line 225 of file dwarf2.h.
DW_AT_decl_column
#define DW_AT_decl_column 0x39
Definition at line 185 of file dwarf2.h.
DW_AT_decl_file
#define DW_AT_decl_file 0x3a
Definition at line 186 of file dwarf2.h.
DW_AT_decl_line
#define DW_AT_decl_line 0x3b
Definition at line 187 of file dwarf2.h.
DW_AT_declaration
#define DW_AT_declaration 0x3c
Definition at line 188 of file dwarf2.h.
DW_AT_default_value
#define DW_AT_default_value 0x1e
Definition at line 167 of file dwarf2.h.
DW_AT_description
#define DW_AT_description 0x5a
Definition at line 221 of file dwarf2.h.
DW_AT_digit_count
#define DW_AT_digit_count 0x5f
Definition at line 226 of file dwarf2.h.
DW_AT_discr
#define DW_AT_discr 0x15
Definition at line 158 of file dwarf2.h.
DW_AT_discr_list
#define DW_AT_discr_list 0x3d
Definition at line 189 of file dwarf2.h.
DW_AT_discr_value
#define DW_AT_discr_value 0x16
Definition at line 159 of file dwarf2.h.
DW_AT_element_list
#define DW_AT_element_list 0x0f
Definition at line 152 of file dwarf2.h.
DW_AT_elemental
#define DW_AT_elemental 0x66
Definition at line 233 of file dwarf2.h.
DW_AT_encoding
#define DW_AT_encoding 0x3e
Definition at line 190 of file dwarf2.h.
DW_AT_endianity
#define DW_AT_endianity 0x65
Definition at line 232 of file dwarf2.h.
DW_AT_entry_pc
#define DW_AT_entry_pc 0x52
Definition at line 213 of file dwarf2.h.
DW_AT_explicit
#define DW_AT_explicit 0x63
Definition at line 230 of file dwarf2.h.
DW_AT_extension
#define DW_AT_extension 0x54
Definition at line 215 of file dwarf2.h.
DW_AT_external
#define DW_AT_external 0x3f
Definition at line 191 of file dwarf2.h.
DW_AT_frame_base
#define DW_AT_frame_base 0x40
Definition at line 192 of file dwarf2.h.
DW_AT_friend
#define DW_AT_friend 0x41
Definition at line 193 of file dwarf2.h.
DW_AT_GNU_vector
#define DW_AT_GNU_vector 0x2107
Definition at line 270 of file dwarf2.h.
DW_AT_hi_user
#define DW_AT_hi_user 0x3fff
Definition at line 295 of file dwarf2.h.
DW_AT_high_pc
#define DW_AT_high_pc 0x12
Definition at line 155 of file dwarf2.h.
DW_AT_HP_actuals_stmt_list
#define DW_AT_HP_actuals_stmt_list 0x2010
Definition at line 251 of file dwarf2.h.
DW_AT_HP_all_variables_modifiable
#define DW_AT_HP_all_variables_modifiable 0x2019
Definition at line 260 of file dwarf2.h.
DW_AT_HP_block_index
#define DW_AT_HP_block_index 0x2000
Definition at line 249 of file dwarf2.h.
DW_AT_HP_cold_region_high_pc
#define DW_AT_HP_cold_region_high_pc 0x2018
Definition at line 259 of file dwarf2.h.
DW_AT_HP_cold_region_low_pc
#define DW_AT_HP_cold_region_low_pc 0x2017
Definition at line 258 of file dwarf2.h.
DW_AT_HP_linkage_name
#define DW_AT_HP_linkage_name 0x201a
Definition at line 261 of file dwarf2.h.
DW_AT_HP_opt_flags
#define DW_AT_HP_opt_flags 0x2016
Definition at line 257 of file dwarf2.h.
DW_AT_HP_opt_level
#define DW_AT_HP_opt_level 0x2014
Definition at line 255 of file dwarf2.h.
DW_AT_HP_pass_by_reference
#define DW_AT_HP_pass_by_reference 0x2013
Definition at line 254 of file dwarf2.h.
DW_AT_HP_proc_per_section
#define DW_AT_HP_proc_per_section 0x2011
Definition at line 252 of file dwarf2.h.
DW_AT_HP_prof_flags
#define DW_AT_HP_prof_flags 0x201b
Definition at line 262 of file dwarf2.h.
DW_AT_HP_prof_version_id
#define DW_AT_HP_prof_version_id 0x2015
Definition at line 256 of file dwarf2.h.
DW_AT_HP_raw_data_ptr
#define DW_AT_HP_raw_data_ptr 0x2012
Definition at line 253 of file dwarf2.h.
DW_AT_HP_unmodifiable
#define DW_AT_HP_unmodifiable 0x2001
Definition at line 250 of file dwarf2.h.
DW_AT_identifier_case
#define DW_AT_identifier_case 0x42
Definition at line 194 of file dwarf2.h.
DW_AT_import
#define DW_AT_import 0x18
Definition at line 161 of file dwarf2.h.
DW_AT_inline
#define DW_AT_inline 0x20
Definition at line 168 of file dwarf2.h.
DW_AT_is_optional
#define DW_AT_is_optional 0x21
Definition at line 169 of file dwarf2.h.
DW_AT_language
#define DW_AT_language 0x13
Definition at line 156 of file dwarf2.h.
DW_AT_lbase
#define DW_AT_lbase 0x3a00
Definition at line 276 of file dwarf2.h.
DW_AT_lo_user
#define DW_AT_lo_user 0x2000
Definition at line 294 of file dwarf2.h.
DW_AT_location
#define DW_AT_location 0x02
Definition at line 145 of file dwarf2.h.
DW_AT_low_pc
#define DW_AT_low_pc 0x11
Definition at line 154 of file dwarf2.h.
DW_AT_lower_bound
#define DW_AT_lower_bound 0x22
Definition at line 170 of file dwarf2.h.
DW_AT_lstride
#define DW_AT_lstride 0x3a02
Definition at line 278 of file dwarf2.h.
DW_AT_mac_info
#define DW_AT_mac_info 0x2103
Definition at line 266 of file dwarf2.h.
DW_AT_macro_info
#define DW_AT_macro_info 0x43
Definition at line 195 of file dwarf2.h.
DW_AT_member
#define DW_AT_member 0x14
Definition at line 157 of file dwarf2.h.
DW_AT_MIPS_abstract_name
#define DW_AT_MIPS_abstract_name 0x2009
Definition at line 245 of file dwarf2.h.
DW_AT_MIPS_clone_origin
#define DW_AT_MIPS_clone_origin 0x200a
Definition at line 246 of file dwarf2.h.
DW_AT_MIPS_epilog_begin
#define DW_AT_MIPS_epilog_begin 0x2004
Definition at line 240 of file dwarf2.h.
DW_AT_MIPS_fde
#define DW_AT_MIPS_fde 0x2001
Definition at line 237 of file dwarf2.h.
DW_AT_MIPS_has_inlines
#define DW_AT_MIPS_has_inlines 0x200b
Definition at line 247 of file dwarf2.h.
DW_AT_MIPS_linkage_name
#define DW_AT_MIPS_linkage_name 0x2007 /* supported by PGI */
Definition at line 243 of file dwarf2.h.
DW_AT_MIPS_loop_begin
#define DW_AT_MIPS_loop_begin 0x2002
Definition at line 238 of file dwarf2.h.
DW_AT_MIPS_loop_unroll_factor
#define DW_AT_MIPS_loop_unroll_factor 0x2005
Definition at line 241 of file dwarf2.h.
DW_AT_MIPS_software_pipeline_depth
#define DW_AT_MIPS_software_pipeline_depth 0x2006
Definition at line 242 of file dwarf2.h.
DW_AT_MIPS_stride
#define DW_AT_MIPS_stride 0x2008
Definition at line 244 of file dwarf2.h.
DW_AT_MIPS_tail_loop_begin
#define DW_AT_MIPS_tail_loop_begin 0x2003
Definition at line 239 of file dwarf2.h.
DW_AT_mutable
#define DW_AT_mutable 0x61
Definition at line 228 of file dwarf2.h.
DW_AT_name
#define DW_AT_name 0x03
Definition at line 146 of file dwarf2.h.
DW_AT_namelist_item
#define DW_AT_namelist_item 0x44
Definition at line 196 of file dwarf2.h.
DW_AT_object_pointer
#define DW_AT_object_pointer 0x64
Definition at line 231 of file dwarf2.h.
DW_AT_ordering
#define DW_AT_ordering 0x09
Definition at line 147 of file dwarf2.h.
DW_AT_picture_string
#define DW_AT_picture_string 0x60
Definition at line 227 of file dwarf2.h.
DW_AT_priority
#define DW_AT_priority 0x45
Definition at line 197 of file dwarf2.h.
DW_AT_producer
#define DW_AT_producer 0x25
Definition at line 171 of file dwarf2.h.
DW_AT_prototyped
#define DW_AT_prototyped 0x27
Definition at line 172 of file dwarf2.h.
DW_AT_pure
#define DW_AT_pure 0x67
Definition at line 234 of file dwarf2.h.
DW_AT_ranges
#define DW_AT_ranges 0x55
Definition at line 216 of file dwarf2.h.
DW_AT_recursive
#define DW_AT_recursive 0x68
Definition at line 235 of file dwarf2.h.
DW_AT_return_addr
#define DW_AT_return_addr 0x2a
Definition at line 173 of file dwarf2.h.
DW_AT_segment
#define DW_AT_segment 0x46
Definition at line 198 of file dwarf2.h.
DW_AT_sf_names
#define DW_AT_sf_names 0x2101
Definition at line 264 of file dwarf2.h.
DW_AT_sibling
#define DW_AT_sibling 0x01
Definition at line 144 of file dwarf2.h.
DW_AT_small
#define DW_AT_small 0x5d
Definition at line 224 of file dwarf2.h.
DW_AT_soffset
#define DW_AT_soffset 0x3a01
Definition at line 277 of file dwarf2.h.
DW_AT_specification
#define DW_AT_specification 0x47
Definition at line 199 of file dwarf2.h.
DW_AT_src_coords
#define DW_AT_src_coords 0x2104
Definition at line 267 of file dwarf2.h.
DW_AT_src_info
#define DW_AT_src_info 0x2102
Definition at line 265 of file dwarf2.h.
DW_AT_start_scope
#define DW_AT_start_scope 0x2c
Definition at line 174 of file dwarf2.h.
DW_AT_static_link
#define DW_AT_static_link 0x48
Definition at line 200 of file dwarf2.h.
DW_AT_stmt_list
#define DW_AT_stmt_list 0x10
Definition at line 153 of file dwarf2.h.
DW_AT_stride
#define DW_AT_stride 0x51
Definition at line 211 of file dwarf2.h.
DW_AT_stride_size
#define DW_AT_stride_size 0x2e
Definition at line 175 of file dwarf2.h.
DW_AT_string_length
#define DW_AT_string_length 0x19
Definition at line 162 of file dwarf2.h.
DW_AT_subscr_data
#define DW_AT_subscr_data 0x0a
Definition at line 148 of file dwarf2.h.
DW_AT_threads_scaled
#define DW_AT_threads_scaled 0x62
Definition at line 229 of file dwarf2.h.
DW_AT_trampoline
#define DW_AT_trampoline 0x56
Definition at line 217 of file dwarf2.h.
DW_AT_type
#define DW_AT_type 0x49
Definition at line 201 of file dwarf2.h.
DW_AT_upc_threads_scaled
#define DW_AT_upc_threads_scaled 0x3210
Definition at line 274 of file dwarf2.h.
DW_AT_upper_bound
#define DW_AT_upper_bound 0x2f
Definition at line 176 of file dwarf2.h.
DW_AT_use_location
#define DW_AT_use_location 0x4a
Definition at line 202 of file dwarf2.h.
DW_AT_use_UTF8
#define DW_AT_use_UTF8 0x53
Definition at line 214 of file dwarf2.h.
DW_AT_variable_parameter
#define DW_AT_variable_parameter 0x4b
Definition at line 203 of file dwarf2.h.
DW_AT_virtuality
#define DW_AT_virtuality 0x4c
Definition at line 204 of file dwarf2.h.
DW_AT_visibility
#define DW_AT_visibility 0x17
Definition at line 160 of file dwarf2.h.
DW_AT_VMS_rtnbeg_pd_address
#define DW_AT_VMS_rtnbeg_pd_address 0x2201
Definition at line 272 of file dwarf2.h.
DW_AT_vtable_elem_location
#define DW_AT_vtable_elem_location 0x4d
Definition at line 205 of file dwarf2.h.
DW_ATE_address
#define DW_ATE_address 0x1
Definition at line 470 of file dwarf2.h.
DW_ATE_boolean
#define DW_ATE_boolean 0x2
Definition at line 471 of file dwarf2.h.
DW_ATE_complex_float
#define DW_ATE_complex_float 0x3
Definition at line 472 of file dwarf2.h.
DW_ATE_decimal_float
#define DW_ATE_decimal_float 0x0f
Definition at line 485 of file dwarf2.h.
DW_ATE_edited
#define DW_ATE_edited 0x0c
Definition at line 482 of file dwarf2.h.
DW_ATE_float
#define DW_ATE_float 0x4
Definition at line 473 of file dwarf2.h.
DW_ATE_hi_user
#define DW_ATE_hi_user 0xff
Definition at line 496 of file dwarf2.h.
DW_ATE_HP_complex_float128
#define DW_ATE_HP_complex_float128 0x83
Definition at line 490 of file dwarf2.h.
DW_ATE_HP_complex_float80
#define DW_ATE_HP_complex_float80 0x81
Definition at line 488 of file dwarf2.h.
DW_ATE_HP_float128
#define DW_ATE_HP_float128 0x82
Definition at line 489 of file dwarf2.h.
DW_ATE_HP_float80
#define DW_ATE_HP_float80 0x80
Definition at line 487 of file dwarf2.h.
DW_ATE_HP_floathpintel
#define DW_ATE_HP_floathpintel 0x84
Definition at line 491 of file dwarf2.h.
DW_ATE_HP_imaginary_float128
#define DW_ATE_HP_imaginary_float128 0x86
Definition at line 493 of file dwarf2.h.
DW_ATE_HP_imaginary_float80
#define DW_ATE_HP_imaginary_float80 0x85
Definition at line 492 of file dwarf2.h.
DW_ATE_imaginary_float
#define DW_ATE_imaginary_float 0x09
Definition at line 479 of file dwarf2.h.
DW_ATE_lo_user
#define DW_ATE_lo_user 0x80
Definition at line 495 of file dwarf2.h.
DW_ATE_numeric_string
#define DW_ATE_numeric_string 0x0b
Definition at line 481 of file dwarf2.h.
DW_ATE_packed_decimal
#define DW_ATE_packed_decimal 0x0a
Definition at line 480 of file dwarf2.h.
DW_ATE_signed
#define DW_ATE_signed 0x5
Definition at line 474 of file dwarf2.h.
DW_ATE_signed_char
#define DW_ATE_signed_char 0x6
Definition at line 475 of file dwarf2.h.
DW_ATE_signed_fixed
#define DW_ATE_signed_fixed 0x0d
Definition at line 483 of file dwarf2.h.
DW_ATE_unsigned
#define DW_ATE_unsigned 0x7
Definition at line 476 of file dwarf2.h.
DW_ATE_unsigned_char
#define DW_ATE_unsigned_char 0x8
Definition at line 477 of file dwarf2.h.
DW_ATE_unsigned_fixed
#define DW_ATE_unsigned_fixed 0x0e
Definition at line 484 of file dwarf2.h.
DW_CC_GNU_renesas_sh
#define DW_CC_GNU_renesas_sh 0x40
Definition at line 547 of file dwarf2.h.
DW_CC_hi_user
#define DW_CC_hi_user 0xff
Definition at line 550 of file dwarf2.h.
DW_CC_lo_user
#define DW_CC_lo_user 0x40
Definition at line 549 of file dwarf2.h.
DW_CC_nocall
#define DW_CC_nocall 0x3
Definition at line 545 of file dwarf2.h.
DW_CC_normal
#define DW_CC_normal 0x1
Definition at line 543 of file dwarf2.h.
DW_CC_program
#define DW_CC_program 0x2
Definition at line 544 of file dwarf2.h.
DW_CFA_advance_loc
#define DW_CFA_advance_loc 0x40
Definition at line 604 of file dwarf2.h.
DW_CFA_advance_loc1
#define DW_CFA_advance_loc1 0x02
Definition at line 611 of file dwarf2.h.
DW_CFA_advance_loc2
#define DW_CFA_advance_loc2 0x03
Definition at line 612 of file dwarf2.h.
DW_CFA_advance_loc4
#define DW_CFA_advance_loc4 0x04
Definition at line 613 of file dwarf2.h.
DW_CFA_def_cfa
#define DW_CFA_def_cfa 0x0c
Definition at line 621 of file dwarf2.h.
DW_CFA_def_cfa_expression
#define DW_CFA_def_cfa_expression 0x0f
Definition at line 625 of file dwarf2.h.
DW_CFA_def_cfa_offset
#define DW_CFA_def_cfa_offset 0x0e
Definition at line 623 of file dwarf2.h.
DW_CFA_def_cfa_offset_sf
#define DW_CFA_def_cfa_offset_sf 0x13
Definition at line 629 of file dwarf2.h.
DW_CFA_def_cfa_register
#define DW_CFA_def_cfa_register 0x0d
Definition at line 622 of file dwarf2.h.
DW_CFA_def_cfa_sf
#define DW_CFA_def_cfa_sf 0x12
Definition at line 628 of file dwarf2.h.
DW_CFA_expression
#define DW_CFA_expression 0x10
Definition at line 626 of file dwarf2.h.
DW_CFA_extended
#define DW_CFA_extended 0
Definition at line 607 of file dwarf2.h.
DW_CFA_GNU_args_size
#define DW_CFA_GNU_args_size 0x2e
Definition at line 637 of file dwarf2.h.
DW_CFA_GNU_negative_offset_extended
#define DW_CFA_GNU_negative_offset_extended 0x2f
Definition at line 638 of file dwarf2.h.
DW_CFA_GNU_window_save
#define DW_CFA_GNU_window_save 0x2d
Definition at line 636 of file dwarf2.h.
DW_CFA_high_user
#define DW_CFA_high_user 0x3f
Definition at line 641 of file dwarf2.h.
DW_CFA_low_user
#define DW_CFA_low_user 0x1c
Definition at line 640 of file dwarf2.h.
DW_CFA_MIPS_advance_loc8
#define DW_CFA_MIPS_advance_loc8 0x1d
Definition at line 634 of file dwarf2.h.
DW_CFA_nop
#define DW_CFA_nop 0x00
Definition at line 609 of file dwarf2.h.
DW_CFA_offset
#define DW_CFA_offset 0x80
Definition at line 605 of file dwarf2.h.
DW_CFA_offset_extended
#define DW_CFA_offset_extended 0x05
Definition at line 614 of file dwarf2.h.
DW_CFA_offset_extended_sf
#define DW_CFA_offset_extended_sf 0x11
Definition at line 627 of file dwarf2.h.
DW_CFA_register
#define DW_CFA_register 0x09
Definition at line 618 of file dwarf2.h.
DW_CFA_remember_state
#define DW_CFA_remember_state 0x0a
Definition at line 619 of file dwarf2.h.
DW_CFA_restore
#define DW_CFA_restore 0xc0
Definition at line 606 of file dwarf2.h.
DW_CFA_restore_extended
#define DW_CFA_restore_extended 0x06
Definition at line 615 of file dwarf2.h.
DW_CFA_restore_state
#define DW_CFA_restore_state 0x0b
Definition at line 620 of file dwarf2.h.
DW_CFA_same_value
#define DW_CFA_same_value 0x08
Definition at line 617 of file dwarf2.h.
DW_CFA_set_loc
#define DW_CFA_set_loc 0x01
Definition at line 610 of file dwarf2.h.
DW_CFA_undefined
#define DW_CFA_undefined 0x07
Definition at line 616 of file dwarf2.h.
DW_CFA_val_expression
#define DW_CFA_val_expression 0x16
Definition at line 632 of file dwarf2.h.
DW_CFA_val_offset
#define DW_CFA_val_offset 0x14
Definition at line 630 of file dwarf2.h.
DW_CFA_val_offset_sf
#define DW_CFA_val_offset_sf 0x15
Definition at line 631 of file dwarf2.h.
DW_children_no
#define DW_children_no 0
Definition at line 115 of file dwarf2.h.
DW_CHILDREN_no
#define DW_CHILDREN_no 0x00
Definition at line 647 of file dwarf2.h.
DW_children_yes
#define DW_children_yes 1
Definition at line 116 of file dwarf2.h.
DW_CHILDREN_yes
#define DW_CHILDREN_yes 0x01
Definition at line 648 of file dwarf2.h.
DW_DSC_label
#define DW_DSC_label 0
Definition at line 560 of file dwarf2.h.
DW_DSC_range
#define DW_DSC_range 1
Definition at line 561 of file dwarf2.h.
DW_FORM_addr
#define DW_FORM_addr 0x01
Definition at line 118 of file dwarf2.h.
DW_FORM_block
#define DW_FORM_block 0x09
Definition at line 125 of file dwarf2.h.
DW_FORM_block1
#define DW_FORM_block1 0x0a
Definition at line 126 of file dwarf2.h.
DW_FORM_block2
#define DW_FORM_block2 0x03
Definition at line 119 of file dwarf2.h.
DW_FORM_block4
#define DW_FORM_block4 0x04
Definition at line 120 of file dwarf2.h.
DW_FORM_data1
#define DW_FORM_data1 0x0b
Definition at line 127 of file dwarf2.h.
DW_FORM_data2
#define DW_FORM_data2 0x05
Definition at line 121 of file dwarf2.h.
DW_FORM_data4
#define DW_FORM_data4 0x06
Definition at line 122 of file dwarf2.h.
DW_FORM_data8
#define DW_FORM_data8 0x07
Definition at line 123 of file dwarf2.h.
DW_FORM_exprloc
#define DW_FORM_exprloc 0x18 /* v. 4 */
Definition at line 140 of file dwarf2.h.
DW_FORM_flag
#define DW_FORM_flag 0x0c
Definition at line 128 of file dwarf2.h.
DW_FORM_flag_present
#define DW_FORM_flag_present 0x19 /* v. 4 */
Definition at line 141 of file dwarf2.h.
DW_FORM_indirect
#define DW_FORM_indirect 0x16
Definition at line 138 of file dwarf2.h.
DW_FORM_ref1
#define DW_FORM_ref1 0x11
Definition at line 133 of file dwarf2.h.
DW_FORM_ref2
#define DW_FORM_ref2 0x12
Definition at line 134 of file dwarf2.h.
DW_FORM_ref4
#define DW_FORM_ref4 0x13
Definition at line 135 of file dwarf2.h.
DW_FORM_ref8
#define DW_FORM_ref8 0x14
Definition at line 136 of file dwarf2.h.
DW_FORM_ref_addr
#define DW_FORM_ref_addr 0x10
Definition at line 132 of file dwarf2.h.
DW_FORM_ref_sig8
#define DW_FORM_ref_sig8 0x20 /* v. 4 */
Definition at line 142 of file dwarf2.h.
DW_FORM_ref_udata
#define DW_FORM_ref_udata 0x15
Definition at line 137 of file dwarf2.h.
DW_FORM_sdata
#define DW_FORM_sdata 0x0d
Definition at line 129 of file dwarf2.h.
DW_FORM_sec_offset
#define DW_FORM_sec_offset 0x17 /* v. 4 */
Definition at line 139 of file dwarf2.h.
DW_FORM_string
#define DW_FORM_string 0x08
Definition at line 124 of file dwarf2.h.
DW_FORM_strp
#define DW_FORM_strp 0x0e
Definition at line 130 of file dwarf2.h.
DW_FORM_udata
#define DW_FORM_udata 0x0f
Definition at line 131 of file dwarf2.h.
DW_ID_case_insensitive
#define DW_ID_case_insensitive 3
Definition at line 541 of file dwarf2.h.
DW_ID_case_sensitive
#define DW_ID_case_sensitive 0
Definition at line 538 of file dwarf2.h.
DW_ID_down_case
#define DW_ID_down_case 2
Definition at line 540 of file dwarf2.h.
DW_ID_up_case
#define DW_ID_up_case 1
Definition at line 539 of file dwarf2.h.
DW_INL_declared_inlined
#define DW_INL_declared_inlined 3
Definition at line 555 of file dwarf2.h.
DW_INL_declared_not_inlined
#define DW_INL_declared_not_inlined 2
Definition at line 554 of file dwarf2.h.
DW_INL_inlined
#define DW_INL_inlined 1
Definition at line 553 of file dwarf2.h.
DW_INL_not_inlined
#define DW_INL_not_inlined 0
Definition at line 552 of file dwarf2.h.
DW_LANG_Ada83
#define DW_LANG_Ada83 0x0003
Definition at line 512 of file dwarf2.h.
DW_LANG_Ada95
#define DW_LANG_Ada95 0x000d
Definition at line 523 of file dwarf2.h.
DW_LANG_C
#define DW_LANG_C 0x0002
Definition at line 511 of file dwarf2.h.
DW_LANG_C89
#define DW_LANG_C89 0x0001
Definition at line 510 of file dwarf2.h.
DW_LANG_C99
#define DW_LANG_C99 0x000c
Definition at line 522 of file dwarf2.h.
DW_LANG_C_plus_plus
#define DW_LANG_C_plus_plus 0x0004
Definition at line 513 of file dwarf2.h.
DW_LANG_Cobol74
#define DW_LANG_Cobol74 0x0005
Definition at line 514 of file dwarf2.h.
DW_LANG_Cobol85
#define DW_LANG_Cobol85 0x0006
Definition at line 515 of file dwarf2.h.
DW_LANG_D
#define DW_LANG_D 0x0013
Definition at line 529 of file dwarf2.h.
DW_LANG_Fortran77
#define DW_LANG_Fortran77 0x0007
Definition at line 516 of file dwarf2.h.
DW_LANG_Fortran90
#define DW_LANG_Fortran90 0x0008
Definition at line 517 of file dwarf2.h.
DW_LANG_Fortran95
#define DW_LANG_Fortran95 0x000e
Definition at line 524 of file dwarf2.h.
DW_LANG_hi_user
#define DW_LANG_hi_user 0xffff
Definition at line 536 of file dwarf2.h.
DW_LANG_Java
#define DW_LANG_Java 0x000b
Definition at line 521 of file dwarf2.h.
DW_LANG_lo_user
#define DW_LANG_lo_user 0x8000
Definition at line 535 of file dwarf2.h.
DW_LANG_Mips_Assembler
#define DW_LANG_Mips_Assembler 0x8001
Definition at line 531 of file dwarf2.h.
DW_LANG_Modula2
#define DW_LANG_Modula2 0x000a
Definition at line 519 of file dwarf2.h.
DW_LANG_ObjC
#define DW_LANG_ObjC 0x0010
Definition at line 526 of file dwarf2.h.
DW_LANG_ObjC_plus_plus
#define DW_LANG_ObjC_plus_plus 0x0011
Definition at line 527 of file dwarf2.h.
DW_LANG_Pascal83
#define DW_LANG_Pascal83 0x0009
Definition at line 518 of file dwarf2.h.
DW_LANG_PLI
#define DW_LANG_PLI 0x000f
Definition at line 525 of file dwarf2.h.
DW_LANG_UPC
#define DW_LANG_UPC 0x0012
Definition at line 528 of file dwarf2.h.
DW_LANG_Upc
#define DW_LANG_Upc 0x8765
Definition at line 533 of file dwarf2.h.
DW_LNE_define_file
#define DW_LNE_define_file 3
Definition at line 579 of file dwarf2.h.
DW_LNE_end_sequence
#define DW_LNE_end_sequence 1
Definition at line 577 of file dwarf2.h.
DW_LNE_hi_user
#define DW_LNE_hi_user 0xff
Definition at line 596 of file dwarf2.h.
DW_LNE_HP_define_proc
#define DW_LNE_HP_define_proc 0x20
Definition at line 593 of file dwarf2.h.
DW_LNE_HP_negate_front_end_logical
#define DW_LNE_HP_negate_front_end_logical 0x19
Definition at line 592 of file dwarf2.h.
DW_LNE_HP_negate_function_exit
#define DW_LNE_HP_negate_function_exit 0x18
Definition at line 591 of file dwarf2.h.
DW_LNE_HP_negate_is_UV_update
#define DW_LNE_HP_negate_is_UV_update 0x11
Definition at line 584 of file dwarf2.h.
DW_LNE_HP_negate_post_semantics
#define DW_LNE_HP_negate_post_semantics 0x17
Definition at line 590 of file dwarf2.h.
DW_LNE_HP_pop_context
#define DW_LNE_HP_pop_context 0x13
Definition at line 586 of file dwarf2.h.
DW_LNE_HP_push_context
#define DW_LNE_HP_push_context 0x12
Definition at line 585 of file dwarf2.h.
DW_LNE_HP_set_file_line_column
#define DW_LNE_HP_set_file_line_column 0x14
Definition at line 587 of file dwarf2.h.
DW_LNE_HP_set_routine_name
#define DW_LNE_HP_set_routine_name 0x15
Definition at line 588 of file dwarf2.h.
DW_LNE_HP_set_sequence
#define DW_LNE_HP_set_sequence 0x16
Definition at line 589 of file dwarf2.h.
DW_LNE_lo_user
#define DW_LNE_lo_user 0x80
Definition at line 595 of file dwarf2.h.
DW_LNE_set_address
#define DW_LNE_set_address 2
Definition at line 578 of file dwarf2.h.
DW_LNE_set_discriminator
#define DW_LNE_set_discriminator 4
Definition at line 581 of file dwarf2.h.
DW_LNS_advance_line
#define DW_LNS_advance_line 0x03
Definition at line 565 of file dwarf2.h.
DW_LNS_advance_pc
#define DW_LNS_advance_pc 0x02
Definition at line 564 of file dwarf2.h.
DW_LNS_const_add_pc
#define DW_LNS_const_add_pc 0x08
Definition at line 570 of file dwarf2.h.
DW_LNS_copy
#define DW_LNS_copy 0x01
Definition at line 563 of file dwarf2.h.
DW_LNS_fixed_advance_pc
#define DW_LNS_fixed_advance_pc 0x09
Definition at line 571 of file dwarf2.h.
DW_LNS_negate_stmt
#define DW_LNS_negate_stmt 0x06
Definition at line 568 of file dwarf2.h.
DW_LNS_set_basic_block
#define DW_LNS_set_basic_block 0x07
Definition at line 569 of file dwarf2.h.
DW_LNS_set_column
#define DW_LNS_set_column 0x05
Definition at line 567 of file dwarf2.h.
DW_LNS_set_epilogue_begin
#define DW_LNS_set_epilogue_begin 0x0b
Definition at line 574 of file dwarf2.h.
DW_LNS_set_file
#define DW_LNS_set_file 0x04
Definition at line 566 of file dwarf2.h.
DW_LNS_set_isa
#define DW_LNS_set_isa 0x0c
Definition at line 575 of file dwarf2.h.
DW_LNS_set_prologue_end
#define DW_LNS_set_prologue_end 0x0a
Definition at line 573 of file dwarf2.h.
DW_MACINFO_define
#define DW_MACINFO_define 1
Definition at line 598 of file dwarf2.h.
DW_MACINFO_end_file
#define DW_MACINFO_end_file 4
Definition at line 601 of file dwarf2.h.
DW_MACINFO_start_file
#define DW_MACINFO_start_file 3
Definition at line 600 of file dwarf2.h.
DW_MACINFO_undef
#define DW_MACINFO_undef 2
Definition at line 599 of file dwarf2.h.
DW_MACINFO_vendor_ext
#define DW_MACINFO_vendor_ext 255
Definition at line 602 of file dwarf2.h.
DW_OP_abs
#define DW_OP_abs 0x19
Definition at line 316 of file dwarf2.h.
DW_OP_addr
#define DW_OP_addr 0x03
Definition at line 297 of file dwarf2.h.
DW_OP_and
#define DW_OP_and 0x1a
Definition at line 317 of file dwarf2.h.
DW_OP_bit_piece
#define DW_OP_bit_piece 0x9d
Definition at line 449 of file dwarf2.h.
DW_OP_bra
#define DW_OP_bra 0x28
Definition at line 331 of file dwarf2.h.
DW_OP_breg0
#define DW_OP_breg0 0x70
Definition at line 403 of file dwarf2.h.
DW_OP_breg1
#define DW_OP_breg1 0x71
Definition at line 404 of file dwarf2.h.
DW_OP_breg10
#define DW_OP_breg10 0x7a
Definition at line 413 of file dwarf2.h.
DW_OP_breg11
#define DW_OP_breg11 0x7b
Definition at line 414 of file dwarf2.h.
DW_OP_breg12
#define DW_OP_breg12 0x7c
Definition at line 415 of file dwarf2.h.
DW_OP_breg13
#define DW_OP_breg13 0x7d
Definition at line 416 of file dwarf2.h.
DW_OP_breg14
#define DW_OP_breg14 0x7e
Definition at line 417 of file dwarf2.h.
DW_OP_breg15
#define DW_OP_breg15 0x7f
Definition at line 418 of file dwarf2.h.
DW_OP_breg16
#define DW_OP_breg16 0x80
Definition at line 419 of file dwarf2.h.
DW_OP_breg17
#define DW_OP_breg17 0x81
Definition at line 420 of file dwarf2.h.
DW_OP_breg18
#define DW_OP_breg18 0x82
Definition at line 421 of file dwarf2.h.
DW_OP_breg19
#define DW_OP_breg19 0x83
Definition at line 422 of file dwarf2.h.
DW_OP_breg2
#define DW_OP_breg2 0x72
Definition at line 405 of file dwarf2.h.
DW_OP_breg20
#define DW_OP_breg20 0x84
Definition at line 423 of file dwarf2.h.
DW_OP_breg21
#define DW_OP_breg21 0x85
Definition at line 424 of file dwarf2.h.
DW_OP_breg22
#define DW_OP_breg22 0x86
Definition at line 425 of file dwarf2.h.
DW_OP_breg23
#define DW_OP_breg23 0x87
Definition at line 426 of file dwarf2.h.
DW_OP_breg24
#define DW_OP_breg24 0x88
Definition at line 427 of file dwarf2.h.
DW_OP_breg25
#define DW_OP_breg25 0x89
Definition at line 428 of file dwarf2.h.
DW_OP_breg26
#define DW_OP_breg26 0x8a
Definition at line 429 of file dwarf2.h.
DW_OP_breg27
#define DW_OP_breg27 0x8b
Definition at line 430 of file dwarf2.h.
DW_OP_breg28
#define DW_OP_breg28 0x8c
Definition at line 431 of file dwarf2.h.
DW_OP_breg29
#define DW_OP_breg29 0x8d
Definition at line 432 of file dwarf2.h.
DW_OP_breg3
#define DW_OP_breg3 0x73
Definition at line 406 of file dwarf2.h.
DW_OP_breg30
#define DW_OP_breg30 0x8e
Definition at line 433 of file dwarf2.h.
DW_OP_breg31
#define DW_OP_breg31 0x8f
Definition at line 434 of file dwarf2.h.
DW_OP_breg4
#define DW_OP_breg4 0x74
Definition at line 407 of file dwarf2.h.
DW_OP_breg5
#define DW_OP_breg5 0x75
Definition at line 408 of file dwarf2.h.
DW_OP_breg6
#define DW_OP_breg6 0x76
Definition at line 409 of file dwarf2.h.
DW_OP_breg7
#define DW_OP_breg7 0x77
Definition at line 410 of file dwarf2.h.
DW_OP_breg8
#define DW_OP_breg8 0x78
Definition at line 411 of file dwarf2.h.
DW_OP_breg9
#define DW_OP_breg9 0x79
Definition at line 412 of file dwarf2.h.
DW_OP_bregx
#define DW_OP_bregx 0x92
Definition at line 437 of file dwarf2.h.
DW_OP_call2
#define DW_OP_call2 0x98
Definition at line 444 of file dwarf2.h.
DW_OP_call4
#define DW_OP_call4 0x99
Definition at line 445 of file dwarf2.h.
DW_OP_call_frame_cfa
#define DW_OP_call_frame_cfa 0x9c
Definition at line 448 of file dwarf2.h.
DW_OP_call_ref
#define DW_OP_call_ref 0x9a
Definition at line 446 of file dwarf2.h.
DW_OP_const1s
#define DW_OP_const1s 0x09
Definition at line 300 of file dwarf2.h.
DW_OP_const1u
#define DW_OP_const1u 0x08
Definition at line 299 of file dwarf2.h.
DW_OP_const2s
#define DW_OP_const2s 0x0b
Definition at line 302 of file dwarf2.h.
DW_OP_const2u
#define DW_OP_const2u 0x0a
Definition at line 301 of file dwarf2.h.
DW_OP_const4s
#define DW_OP_const4s 0x0d
Definition at line 304 of file dwarf2.h.
DW_OP_const4u
#define DW_OP_const4u 0x0c
Definition at line 303 of file dwarf2.h.
DW_OP_const8s
#define DW_OP_const8s 0x0f
Definition at line 306 of file dwarf2.h.
DW_OP_const8u
#define DW_OP_const8u 0x0e
Definition at line 305 of file dwarf2.h.
DW_OP_consts
#define DW_OP_consts 0x11
Definition at line 308 of file dwarf2.h.
DW_OP_constu
#define DW_OP_constu 0x10
Definition at line 307 of file dwarf2.h.
DW_OP_deref
#define DW_OP_deref 0x06
Definition at line 298 of file dwarf2.h.
DW_OP_deref_size
#define DW_OP_deref_size 0x94
Definition at line 439 of file dwarf2.h.
DW_OP_div
#define DW_OP_div 0x1b
Definition at line 318 of file dwarf2.h.
DW_OP_drop
#define DW_OP_drop 0x13
Definition at line 310 of file dwarf2.h.
DW_OP_dup
#define DW_OP_dup 0x12
Definition at line 309 of file dwarf2.h.
DW_OP_eq
#define DW_OP_eq 0x29
Definition at line 332 of file dwarf2.h.
DW_OP_fbreg
#define DW_OP_fbreg 0x91
Definition at line 436 of file dwarf2.h.
DW_OP_form_tls_address
#define DW_OP_form_tls_address 0x9b
Definition at line 447 of file dwarf2.h.
DW_OP_ge
#define DW_OP_ge 0x2a
Definition at line 333 of file dwarf2.h.
DW_OP_GNU_push_tls_address
#define DW_OP_GNU_push_tls_address 0xe0
Definition at line 454 of file dwarf2.h.
DW_OP_GNU_uninit
#define DW_OP_GNU_uninit 0xf0
Definition at line 455 of file dwarf2.h.
DW_OP_gt
#define DW_OP_gt 0x2b
Definition at line 334 of file dwarf2.h.
DW_OP_hi_user
#define DW_OP_hi_user 0xff
Definition at line 468 of file dwarf2.h.
DW_OP_HP_fltconst4
#define DW_OP_HP_fltconst4 0xe2
Definition at line 459 of file dwarf2.h.
DW_OP_HP_fltconst8
#define DW_OP_HP_fltconst8 0xe3
Definition at line 460 of file dwarf2.h.
DW_OP_HP_is_value
#define DW_OP_HP_is_value 0xe1
Definition at line 458 of file dwarf2.h.
DW_OP_HP_mod_range
#define DW_OP_HP_mod_range 0xe4
Definition at line 461 of file dwarf2.h.
DW_OP_HP_tls
#define DW_OP_HP_tls 0xe6
Definition at line 463 of file dwarf2.h.
DW_OP_HP_unknown
#define DW_OP_HP_unknown 0xe0
Definition at line 457 of file dwarf2.h.
DW_OP_HP_unmod_range
#define DW_OP_HP_unmod_range 0xe5
Definition at line 462 of file dwarf2.h.
DW_OP_implicit_value
#define DW_OP_implicit_value 0x9e
Definition at line 451 of file dwarf2.h.
DW_OP_le
#define DW_OP_le 0x2c
Definition at line 335 of file dwarf2.h.
DW_OP_lit0
#define DW_OP_lit0 0x30
Definition at line 339 of file dwarf2.h.
DW_OP_lit1
#define DW_OP_lit1 0x31
Definition at line 340 of file dwarf2.h.
DW_OP_lit10
#define DW_OP_lit10 0x3a
Definition at line 349 of file dwarf2.h.
DW_OP_lit11
#define DW_OP_lit11 0x3b
Definition at line 350 of file dwarf2.h.
DW_OP_lit12
#define DW_OP_lit12 0x3c
Definition at line 351 of file dwarf2.h.
DW_OP_lit13
#define DW_OP_lit13 0x3d
Definition at line 352 of file dwarf2.h.
DW_OP_lit14
#define DW_OP_lit14 0x3e
Definition at line 353 of file dwarf2.h.
DW_OP_lit15
#define DW_OP_lit15 0x3f
Definition at line 354 of file dwarf2.h.
DW_OP_lit16
#define DW_OP_lit16 0x40
Definition at line 355 of file dwarf2.h.
DW_OP_lit17
#define DW_OP_lit17 0x41
Definition at line 356 of file dwarf2.h.
DW_OP_lit18
#define DW_OP_lit18 0x42
Definition at line 357 of file dwarf2.h.
DW_OP_lit19
#define DW_OP_lit19 0x43
Definition at line 358 of file dwarf2.h.
DW_OP_lit2
#define DW_OP_lit2 0x32
Definition at line 341 of file dwarf2.h.
DW_OP_lit20
#define DW_OP_lit20 0x44
Definition at line 359 of file dwarf2.h.
DW_OP_lit21
#define DW_OP_lit21 0x45
Definition at line 360 of file dwarf2.h.
DW_OP_lit22
#define DW_OP_lit22 0x46
Definition at line 361 of file dwarf2.h.
DW_OP_lit23
#define DW_OP_lit23 0x47
Definition at line 362 of file dwarf2.h.
DW_OP_lit24
#define DW_OP_lit24 0x48
Definition at line 363 of file dwarf2.h.
DW_OP_lit25
#define DW_OP_lit25 0x49
Definition at line 364 of file dwarf2.h.
DW_OP_lit26
#define DW_OP_lit26 0x4a
Definition at line 365 of file dwarf2.h.
DW_OP_lit27
#define DW_OP_lit27 0x4b
Definition at line 366 of file dwarf2.h.
DW_OP_lit28
#define DW_OP_lit28 0x4c
Definition at line 367 of file dwarf2.h.
DW_OP_lit29
#define DW_OP_lit29 0x4d
Definition at line 368 of file dwarf2.h.
DW_OP_lit3
#define DW_OP_lit3 0x33
Definition at line 342 of file dwarf2.h.
DW_OP_lit30
#define DW_OP_lit30 0x4e
Definition at line 369 of file dwarf2.h.
DW_OP_lit31
#define DW_OP_lit31 0x4f
Definition at line 370 of file dwarf2.h.
DW_OP_lit4
#define DW_OP_lit4 0x34
Definition at line 343 of file dwarf2.h.
DW_OP_lit5
#define DW_OP_lit5 0x35
Definition at line 344 of file dwarf2.h.
DW_OP_lit6
#define DW_OP_lit6 0x36
Definition at line 345 of file dwarf2.h.
DW_OP_lit7
#define DW_OP_lit7 0x37
Definition at line 346 of file dwarf2.h.
DW_OP_lit8
#define DW_OP_lit8 0x38
Definition at line 347 of file dwarf2.h.
DW_OP_lit9
#define DW_OP_lit9 0x39
Definition at line 348 of file dwarf2.h.
DW_OP_lo_user
#define DW_OP_lo_user 0xe0
Definition at line 467 of file dwarf2.h.
DW_OP_lt
#define DW_OP_lt 0x2d
Definition at line 336 of file dwarf2.h.
DW_OP_minus
#define DW_OP_minus 0x1c
Definition at line 319 of file dwarf2.h.
DW_OP_mod
#define DW_OP_mod 0x1d
Definition at line 320 of file dwarf2.h.
DW_OP_mul
#define DW_OP_mul 0x1e
Definition at line 321 of file dwarf2.h.
DW_OP_ne
#define DW_OP_ne 0x2e
Definition at line 337 of file dwarf2.h.
DW_OP_neg
#define DW_OP_neg 0x1f
Definition at line 322 of file dwarf2.h.
DW_OP_nop
#define DW_OP_nop 0x96
Definition at line 441 of file dwarf2.h.
DW_OP_not
#define DW_OP_not 0x20
Definition at line 323 of file dwarf2.h.
DW_OP_or
#define DW_OP_or 0x21
Definition at line 324 of file dwarf2.h.
DW_OP_over
#define DW_OP_over 0x14
Definition at line 311 of file dwarf2.h.
DW_OP_PGI_omp_thread_num
#define DW_OP_PGI_omp_thread_num 0xf8
Definition at line 465 of file dwarf2.h.
DW_OP_pick
#define DW_OP_pick 0x15
Definition at line 312 of file dwarf2.h.
DW_OP_piece
#define DW_OP_piece 0x93
Definition at line 438 of file dwarf2.h.
DW_OP_plus
#define DW_OP_plus 0x22
Definition at line 325 of file dwarf2.h.
DW_OP_plus_uconst
#define DW_OP_plus_uconst 0x23
Definition at line 326 of file dwarf2.h.
DW_OP_push_object_address
#define DW_OP_push_object_address 0x97
Definition at line 443 of file dwarf2.h.
DW_OP_reg0
#define DW_OP_reg0 0x50
Definition at line 371 of file dwarf2.h.
DW_OP_reg1
#define DW_OP_reg1 0x51
Definition at line 372 of file dwarf2.h.
DW_OP_reg10
#define DW_OP_reg10 0x5a
Definition at line 381 of file dwarf2.h.
DW_OP_reg11
#define DW_OP_reg11 0x5b
Definition at line 382 of file dwarf2.h.
DW_OP_reg12
#define DW_OP_reg12 0x5c
Definition at line 383 of file dwarf2.h.
DW_OP_reg13
#define DW_OP_reg13 0x5d
Definition at line 384 of file dwarf2.h.
DW_OP_reg14
#define DW_OP_reg14 0x5e
Definition at line 385 of file dwarf2.h.
DW_OP_reg15
#define DW_OP_reg15 0x5f
Definition at line 386 of file dwarf2.h.
DW_OP_reg16
#define DW_OP_reg16 0x60
Definition at line 387 of file dwarf2.h.
DW_OP_reg17
#define DW_OP_reg17 0x61
Definition at line 388 of file dwarf2.h.
DW_OP_reg18
#define DW_OP_reg18 0x62
Definition at line 389 of file dwarf2.h.
DW_OP_reg19
#define DW_OP_reg19 0x63
Definition at line 390 of file dwarf2.h.
DW_OP_reg2
#define DW_OP_reg2 0x52
Definition at line 373 of file dwarf2.h.
DW_OP_reg20
#define DW_OP_reg20 0x64
Definition at line 391 of file dwarf2.h.
DW_OP_reg21
#define DW_OP_reg21 0x65
Definition at line 392 of file dwarf2.h.
DW_OP_reg22
#define DW_OP_reg22 0x66
Definition at line 393 of file dwarf2.h.
DW_OP_reg23
#define DW_OP_reg23 0x67
Definition at line 394 of file dwarf2.h.
DW_OP_reg24
#define DW_OP_reg24 0x68
Definition at line 395 of file dwarf2.h.
DW_OP_reg25
#define DW_OP_reg25 0x69
Definition at line 396 of file dwarf2.h.
DW_OP_reg26
#define DW_OP_reg26 0x6a
Definition at line 397 of file dwarf2.h.
DW_OP_reg27
#define DW_OP_reg27 0x6b
Definition at line 398 of file dwarf2.h.
DW_OP_reg28
#define DW_OP_reg28 0x6c
Definition at line 399 of file dwarf2.h.
DW_OP_reg29
#define DW_OP_reg29 0x6d
Definition at line 400 of file dwarf2.h.
DW_OP_reg3
#define DW_OP_reg3 0x53
Definition at line 374 of file dwarf2.h.
DW_OP_reg30
#define DW_OP_reg30 0x6e
Definition at line 401 of file dwarf2.h.
DW_OP_reg31
#define DW_OP_reg31 0x6f
Definition at line 402 of file dwarf2.h.
DW_OP_reg4
#define DW_OP_reg4 0x54
Definition at line 375 of file dwarf2.h.
DW_OP_reg5
#define DW_OP_reg5 0x55
Definition at line 376 of file dwarf2.h.
DW_OP_reg6
#define DW_OP_reg6 0x56
Definition at line 377 of file dwarf2.h.
DW_OP_reg7
#define DW_OP_reg7 0x57
Definition at line 378 of file dwarf2.h.
DW_OP_reg8
#define DW_OP_reg8 0x58
Definition at line 379 of file dwarf2.h.
DW_OP_reg9
#define DW_OP_reg9 0x59
Definition at line 380 of file dwarf2.h.
DW_OP_regx
#define DW_OP_regx 0x90
Definition at line 435 of file dwarf2.h.
DW_OP_rot
#define DW_OP_rot 0x17
Definition at line 314 of file dwarf2.h.
DW_OP_shl
#define DW_OP_shl 0x24
Definition at line 327 of file dwarf2.h.
DW_OP_shr
#define DW_OP_shr 0x25
Definition at line 328 of file dwarf2.h.
DW_OP_shra
#define DW_OP_shra 0x26
Definition at line 329 of file dwarf2.h.
DW_OP_skip
#define DW_OP_skip 0x2f
Definition at line 338 of file dwarf2.h.
DW_OP_stack_value
#define DW_OP_stack_value 0x9f
Definition at line 452 of file dwarf2.h.
DW_OP_swap
#define DW_OP_swap 0x16
Definition at line 313 of file dwarf2.h.
DW_OP_xderef
#define DW_OP_xderef 0x18
Definition at line 315 of file dwarf2.h.
DW_OP_xderef_size
#define DW_OP_xderef_size 0x95
Definition at line 440 of file dwarf2.h.
DW_OP_xor
#define DW_OP_xor 0x27
Definition at line 330 of file dwarf2.h.
DW_ORD_col_major
#define DW_ORD_col_major 1
Definition at line 558 of file dwarf2.h.
DW_ORD_row_major
#define DW_ORD_row_major 0
Definition at line 557 of file dwarf2.h.
DW_TAG_access_declaration
#define DW_TAG_access_declaration 0x23
Definition at line 59 of file dwarf2.h.
DW_TAG_arg_variable
#define DW_TAG_arg_variable 0x101
Definition at line 92 of file dwarf2.h.
DW_TAG_array_type
#define DW_TAG_array_type 0x01
Definition at line 31 of file dwarf2.h.
DW_TAG_auto_variable
#define DW_TAG_auto_variable 0x100
Definition at line 91 of file dwarf2.h.
DW_TAG_base_type
#define DW_TAG_base_type 0x24
Definition at line 60 of file dwarf2.h.
DW_TAG_catch_block
#define DW_TAG_catch_block 0x25
Definition at line 61 of file dwarf2.h.
DW_TAG_class_template
#define DW_TAG_class_template 0x4103
Definition at line 101 of file dwarf2.h.
DW_TAG_class_type
#define DW_TAG_class_type 0x02
Definition at line 32 of file dwarf2.h.
DW_TAG_common_block
#define DW_TAG_common_block 0x1a
Definition at line 50 of file dwarf2.h.
DW_TAG_common_inclusion
#define DW_TAG_common_inclusion 0x1b
Definition at line 51 of file dwarf2.h.
DW_TAG_compile_unit
#define DW_TAG_compile_unit 0x11
Definition at line 42 of file dwarf2.h.
DW_TAG_condition
#define DW_TAG_condition 0x3f
Definition at line 87 of file dwarf2.h.
DW_TAG_const_type
#define DW_TAG_const_type 0x26
Definition at line 62 of file dwarf2.h.
DW_TAG_constant
#define DW_TAG_constant 0x27
Definition at line 63 of file dwarf2.h.
DW_TAG_dwarf_procedure
#define DW_TAG_dwarf_procedure 0x36
Definition at line 79 of file dwarf2.h.
DW_TAG_entry_point
#define DW_TAG_entry_point 0x03
Definition at line 33 of file dwarf2.h.
DW_TAG_enumeration_type
#define DW_TAG_enumeration_type 0x04
Definition at line 34 of file dwarf2.h.
DW_TAG_enumerator
#define DW_TAG_enumerator 0x28
Definition at line 64 of file dwarf2.h.
DW_TAG_file_type
#define DW_TAG_file_type 0x29
Definition at line 65 of file dwarf2.h.
DW_TAG_formal_parameter
#define DW_TAG_formal_parameter 0x05
Definition at line 35 of file dwarf2.h.
DW_TAG_format_label
#define DW_TAG_format_label 0x4101
Definition at line 99 of file dwarf2.h.
DW_TAG_friend
#define DW_TAG_friend 0x2a
Definition at line 66 of file dwarf2.h.
DW_TAG_function_template
#define DW_TAG_function_template 0x4102
Definition at line 100 of file dwarf2.h.
DW_TAG_GNU_BINCL
#define DW_TAG_GNU_BINCL 0x4104
Definition at line 102 of file dwarf2.h.
DW_TAG_GNU_EINCL
#define DW_TAG_GNU_EINCL 0x4105
Definition at line 103 of file dwarf2.h.
DW_TAG_hi_user
#define DW_TAG_hi_user 0xffff
Definition at line 113 of file dwarf2.h.
DW_TAG_HP_array_descriptor
#define DW_TAG_HP_array_descriptor 0x4090
Definition at line 97 of file dwarf2.h.
DW_TAG_imported_declaration
#define DW_TAG_imported_declaration 0x08
Definition at line 36 of file dwarf2.h.
DW_TAG_imported_module
#define DW_TAG_imported_module 0x3a
Definition at line 83 of file dwarf2.h.
DW_TAG_imported_unit
#define DW_TAG_imported_unit 0x3d
Definition at line 86 of file dwarf2.h.
DW_TAG_include_table
#define DW_TAG_include_table (0x0054)
Definition at line 658 of file dwarf2.h.
DW_TAG_inheritance
#define DW_TAG_inheritance 0x1c
Definition at line 52 of file dwarf2.h.
DW_TAG_inlined_subroutine
#define DW_TAG_inlined_subroutine 0x1d
Definition at line 53 of file dwarf2.h.
DW_TAG_interface_block
#define DW_TAG_interface_block 0xA020
Definition at line 110 of file dwarf2.h.
DW_TAG_interface_type
#define DW_TAG_interface_type 0x38
Definition at line 81 of file dwarf2.h.
DW_TAG_kanji_type
#define DW_TAG_kanji_type 0xA000
Definition at line 109 of file dwarf2.h.
DW_TAG_label
#define DW_TAG_label 0x0a
Definition at line 37 of file dwarf2.h.
DW_TAG_lexical_block
#define DW_TAG_lexical_block 0x0b
Definition at line 38 of file dwarf2.h.
DW_TAG_lo_user
#define DW_TAG_lo_user 0x4080
Definition at line 112 of file dwarf2.h.
DW_TAG_member
#define DW_TAG_member 0x0d
Definition at line 39 of file dwarf2.h.
DW_TAG_MIPS_loop
#define DW_TAG_MIPS_loop 0x4081
Definition at line 95 of file dwarf2.h.
DW_TAG_module
#define DW_TAG_module 0x1e
Definition at line 54 of file dwarf2.h.
DW_TAG_nameless_class
#define DW_TAG_nameless_class (0x0052)
Definition at line 656 of file dwarf2.h.
DW_TAG_nameless_enumeration
#define DW_TAG_nameless_enumeration (0x0053)
Definition at line 657 of file dwarf2.h.
DW_TAG_nameless_struct
#define DW_TAG_nameless_struct (0x0050)
Definition at line 654 of file dwarf2.h.
DW_TAG_nameless_union
#define DW_TAG_nameless_union (0x0051)
Definition at line 655 of file dwarf2.h.
DW_TAG_namelist
#define DW_TAG_namelist 0x2b
Definition at line 67 of file dwarf2.h.
DW_TAG_namelist_item
#define DW_TAG_namelist_item 0x2c
Definition at line 68 of file dwarf2.h.
DW_TAG_namespace
#define DW_TAG_namespace 0x39
Definition at line 82 of file dwarf2.h.
DW_TAG_packed_type
#define DW_TAG_packed_type 0x2d
Definition at line 69 of file dwarf2.h.
DW_TAG_padding
#define DW_TAG_padding 0x00
Definition at line 30 of file dwarf2.h.
DW_TAG_partial_unit
#define DW_TAG_partial_unit 0x3c
Definition at line 85 of file dwarf2.h.
DW_TAG_pointer_type
#define DW_TAG_pointer_type 0x0f
Definition at line 40 of file dwarf2.h.
DW_TAG_ptr_to_member_type
#define DW_TAG_ptr_to_member_type 0x1f
Definition at line 55 of file dwarf2.h.
DW_TAG_reference_type
#define DW_TAG_reference_type 0x10
Definition at line 41 of file dwarf2.h.
DW_TAG_restrict_type
#define DW_TAG_restrict_type 0x37
Definition at line 80 of file dwarf2.h.
DW_TAG_set_type
#define DW_TAG_set_type 0x20
Definition at line 56 of file dwarf2.h.
DW_TAG_shared_type
#define DW_TAG_shared_type 0x40
Definition at line 88 of file dwarf2.h.
DW_TAG_string_type
#define DW_TAG_string_type 0x12
Definition at line 43 of file dwarf2.h.
DW_TAG_structure_type
#define DW_TAG_structure_type 0x13
Definition at line 44 of file dwarf2.h.
DW_TAG_subprogram
#define DW_TAG_subprogram 0x2e
Definition at line 70 of file dwarf2.h.
DW_TAG_subrange_type
#define DW_TAG_subrange_type 0x21
Definition at line 57 of file dwarf2.h.
DW_TAG_subroutine_type
#define DW_TAG_subroutine_type 0x15
Definition at line 45 of file dwarf2.h.
DW_TAG_template_type_param
#define DW_TAG_template_type_param 0x2f
Definition at line 71 of file dwarf2.h.
DW_TAG_template_value_param
#define DW_TAG_template_value_param 0x30
Definition at line 72 of file dwarf2.h.
DW_TAG_thrown_type
#define DW_TAG_thrown_type 0x31
Definition at line 73 of file dwarf2.h.
DW_TAG_try_block
#define DW_TAG_try_block 0x32
Definition at line 74 of file dwarf2.h.
DW_TAG_typedef
#define DW_TAG_typedef 0x16
Definition at line 46 of file dwarf2.h.
DW_TAG_union_type
#define DW_TAG_union_type 0x17
Definition at line 47 of file dwarf2.h.
DW_TAG_unspecified_parameters
#define DW_TAG_unspecified_parameters 0x18
Definition at line 48 of file dwarf2.h.
DW_TAG_unspecified_type
#define DW_TAG_unspecified_type 0x3b
Definition at line 84 of file dwarf2.h.
DW_TAG_upc_relaxed_type
#define DW_TAG_upc_relaxed_type 0x8767
Definition at line 107 of file dwarf2.h.
DW_TAG_upc_shared_type
#define DW_TAG_upc_shared_type 0x8765
Definition at line 105 of file dwarf2.h.
DW_TAG_upc_strict_type
#define DW_TAG_upc_strict_type 0x8766
Definition at line 106 of file dwarf2.h.
DW_TAG_variable
#define DW_TAG_variable 0x34
Definition at line 76 of file dwarf2.h.
DW_TAG_variant
#define DW_TAG_variant 0x19
Definition at line 49 of file dwarf2.h.
DW_TAG_variant_part
#define DW_TAG_variant_part 0x33
Definition at line 75 of file dwarf2.h.
DW_TAG_void_type
#define DW_TAG_void_type (0x0055)
Definition at line 660 of file dwarf2.h.
DW_TAG_volatile_type
#define DW_TAG_volatile_type 0x35
Definition at line 77 of file dwarf2.h.
DW_TAG_with_stmt
#define DW_TAG_with_stmt 0x22
Definition at line 58 of file dwarf2.h.
DW_VIRTUALITY_none
#define DW_VIRTUALITY_none 0
Definition at line 506 of file dwarf2.h.
DW_VIRTUALITY_pure_virtual
#define DW_VIRTUALITY_pure_virtual 2
Definition at line 508 of file dwarf2.h.
DW_VIRTUALITY_virtual
#define DW_VIRTUALITY_virtual 1
Definition at line 507 of file dwarf2.h.
DW_VIS_exported
#define DW_VIS_exported 2
Definition at line 503 of file dwarf2.h.
DW_VIS_local
#define DW_VIS_local 1
Definition at line 502 of file dwarf2.h.
DW_VIS_qualified
#define DW_VIS_qualified 3
Definition at line 504 of file dwarf2.h.
DWARF_VERSION
#define DWARF_VERSION 2
Definition at line 13 of file dwarf2.h.
DWARF_VERSION3
#define DWARF_VERSION3 3
Definition at line 14 of file dwarf2.h.
DWARF_VERSION4
#define DWARF_VERSION4 4
Definition at line 15 of file dwarf2.h.
Function Documentation
dwarf_attr_name()
const char * dwarf_attr_name (unsigned value)
Definition at line 114 of file dwarf_names.cpp.
References CASERET, DW_AT_abstract_origin, DW_AT_accessibility, DW_AT_address_class, DW_AT_allocated, DW_AT_APPLE_block, DW_AT_APPLE_flags, DW_AT_APPLE_isa, DW_AT_APPLE_major_runtime_vers, DW_AT_APPLE_objc_complete_type, DW_AT_APPLE_omit_frame_ptr, DW_AT_APPLE_optimized, DW_AT_APPLE_property, DW_AT_APPLE_property_attribute, DW_AT_APPLE_property_getter, DW_AT_APPLE_property_name, DW_AT_APPLE_property_setter, DW_AT_APPLE_runtime_class, DW_AT_artificial, DW_AT_associated, DW_AT_base_types, DW_AT_binary_scale, DW_AT_bit_offset, DW_AT_bit_size, DW_AT_body_begin, DW_AT_body_end, DW_AT_byte_size, DW_AT_call_column, DW_AT_call_file, DW_AT_call_line, DW_AT_calling_convention, DW_AT_common_reference, DW_AT_comp_dir, DW_AT_const_value, DW_AT_containing_type, DW_AT_count, DW_AT_data_location, DW_AT_data_member_location, DW_AT_decimal_scale, DW_AT_decimal_sign, DW_AT_decl_column, DW_AT_decl_file, DW_AT_decl_line, DW_AT_declaration, DW_AT_default_value, DW_AT_description, DW_AT_digit_count, DW_AT_discr, DW_AT_discr_list, DW_AT_discr_value, DW_AT_element_list, DW_AT_elemental, DW_AT_encoding, DW_AT_endianity, DW_AT_entry_pc, DW_AT_explicit, DW_AT_extension, DW_AT_external, DW_AT_frame_base, DW_AT_friend, DW_AT_GNU_vector, DW_AT_hi_user, DW_AT_high_pc, DW_AT_identifier_case, DW_AT_import, DW_AT_inline, DW_AT_is_optional, DW_AT_language, DW_AT_lbase, DW_AT_lo_user, DW_AT_location, DW_AT_low_pc, DW_AT_lower_bound, DW_AT_lstride, DW_AT_mac_info, DW_AT_macro_info, DW_AT_member, DW_AT_MIPS_linkage_name, DW_AT_mutable, DW_AT_name, DW_AT_namelist_item, DW_AT_object_pointer, DW_AT_ordering, DW_AT_picture_string, DW_AT_priority, DW_AT_producer, DW_AT_prototyped, DW_AT_pure, DW_AT_ranges, DW_AT_recursive, DW_AT_return_addr, DW_AT_segment, DW_AT_sf_names, DW_AT_sibling, DW_AT_small, DW_AT_soffset, DW_AT_specification, DW_AT_src_coords, DW_AT_src_info, DW_AT_start_scope, DW_AT_static_link, DW_AT_stmt_list, DW_AT_stride, DW_AT_stride_size, DW_AT_string_length, DW_AT_subscr_data, DW_AT_threads_scaled, DW_AT_trampoline, DW_AT_type, DW_AT_upc_threads_scaled, DW_AT_upper_bound, DW_AT_use_location, DW_AT_use_UTF8, DW_AT_variable_parameter, DW_AT_virtuality, DW_AT_visibility, DW_AT_VMS_rtnbeg_pd_address, DW_AT_vtable_elem_location, and value().
dwarf_encoding_name()
const char * dwarf_encoding_name (unsigned value)
Definition at line 482 of file dwarf_names.cpp.
References CASERET, DW_ATE_address, DW_ATE_boolean, DW_ATE_complex_float, DW_ATE_decimal_float, DW_ATE_edited, DW_ATE_float, DW_ATE_imaginary_float, DW_ATE_numeric_string, DW_ATE_packed_decimal, DW_ATE_signed, DW_ATE_signed_char, DW_ATE_signed_fixed, DW_ATE_unsigned, DW_ATE_unsigned_char, DW_ATE_unsigned_fixed, and value().
Referenced by write_mdfield().
dwarf_form_name()
const char * dwarf_form_name (unsigned value)
Definition at line 244 of file dwarf_names.cpp.
References CASERET, DW_FORM_addr, DW_FORM_block, DW_FORM_block1, DW_FORM_block2, DW_FORM_block4, DW_FORM_data1, DW_FORM_data2, DW_FORM_data4, DW_FORM_data8, DW_FORM_exprloc, DW_FORM_flag, DW_FORM_flag_present, DW_FORM_indirect, DW_FORM_ref1, DW_FORM_ref2, DW_FORM_ref4, DW_FORM_ref8, DW_FORM_ref_addr, DW_FORM_ref_sig8, DW_FORM_ref_udata, DW_FORM_sdata, DW_FORM_sec_offset, DW_FORM_string, DW_FORM_strp, DW_FORM_udata, and value().
dwarf_get_fn()
void dwarf_get_fn (char * filename)
dwarf_lang_name()
const char * dwarf_lang_name (unsigned value)
Definition at line 453 of file dwarf_names.cpp.
References CASERET, DW_LANG_Ada83, DW_LANG_Ada95, DW_LANG_C, DW_LANG_C89, DW_LANG_C99, DW_LANG_C_plus_plus, DW_LANG_Cobol74, DW_LANG_Cobol85, DW_LANG_D, DW_LANG_Fortran77, DW_LANG_Fortran90, DW_LANG_Fortran95, DW_LANG_Java, DW_LANG_Mips_Assembler, DW_LANG_Modula2, DW_LANG_ObjC, DW_LANG_ObjC_plus_plus, DW_LANG_Pascal83, DW_LANG_PLI, DW_LANG_UPC, DW_LANG_Upc, and value().
Referenced by write_mdfield().
dwarf_stack_op_name()
const char * dwarf_stack_op_name (unsigned value)
Definition at line 277 of file dwarf_names.cpp.
References CASERET, DW_OP_abs, DW_OP_addr, DW_OP_and, DW_OP_bit_piece, DW_OP_bra, DW_OP_breg0, DW_OP_breg1, DW_OP_breg10, DW_OP_breg11, DW_OP_breg12, DW_OP_breg13, DW_OP_breg14, DW_OP_breg15, DW_OP_breg16, DW_OP_breg17, DW_OP_breg18, DW_OP_breg19, DW_OP_breg2, DW_OP_breg20, DW_OP_breg21, DW_OP_breg22, DW_OP_breg23, DW_OP_breg24, DW_OP_breg25, DW_OP_breg26, DW_OP_breg27, DW_OP_breg28, DW_OP_breg29, DW_OP_breg3, DW_OP_breg30, DW_OP_breg31, DW_OP_breg4, DW_OP_breg5, DW_OP_breg6, DW_OP_breg7, DW_OP_breg8, DW_OP_breg9, DW_OP_bregx, DW_OP_call2, DW_OP_call4, DW_OP_call_frame_cfa, DW_OP_call_ref, DW_OP_const1s, DW_OP_const1u, DW_OP_const2s, DW_OP_const2u, DW_OP_const4s, DW_OP_const4u, DW_OP_const8s, DW_OP_const8u, DW_OP_consts, DW_OP_constu, DW_OP_deref, DW_OP_deref_size, DW_OP_div, DW_OP_drop, DW_OP_dup, DW_OP_eq, DW_OP_fbreg, DW_OP_form_tls_address, DW_OP_ge, DW_OP_GNU_push_tls_address, DW_OP_GNU_uninit, DW_OP_gt, DW_OP_implicit_value, DW_OP_le, DW_OP_lit0, DW_OP_lit1, DW_OP_lit10, DW_OP_lit11, DW_OP_lit12, DW_OP_lit13, DW_OP_lit14, DW_OP_lit15, DW_OP_lit16, DW_OP_lit17, DW_OP_lit18, DW_OP_lit19, DW_OP_lit2, DW_OP_lit20, DW_OP_lit21, DW_OP_lit22, DW_OP_lit23, DW_OP_lit24, DW_OP_lit25, DW_OP_lit26, DW_OP_lit27, DW_OP_lit28, DW_OP_lit29, DW_OP_lit3, DW_OP_lit30, DW_OP_lit31, DW_OP_lit4, DW_OP_lit5, DW_OP_lit6, DW_OP_lit7, DW_OP_lit8, DW_OP_lit9, DW_OP_lt, DW_OP_minus, DW_OP_mod, DW_OP_mul, DW_OP_ne, DW_OP_neg, DW_OP_nop, DW_OP_not, DW_OP_or, DW_OP_over, DW_OP_PGI_omp_thread_num, DW_OP_pick, DW_OP_piece, DW_OP_plus, DW_OP_plus_uconst, DW_OP_push_object_address, DW_OP_reg0, DW_OP_reg1, DW_OP_reg10, DW_OP_reg11, DW_OP_reg12, DW_OP_reg13, DW_OP_reg14, DW_OP_reg15, DW_OP_reg16, DW_OP_reg17, DW_OP_reg18, DW_OP_reg19, DW_OP_reg2, DW_OP_reg20, DW_OP_reg21, DW_OP_reg22, DW_OP_reg23, DW_OP_reg24, DW_OP_reg25, DW_OP_reg26, DW_OP_reg27, DW_OP_reg28, DW_OP_reg29, DW_OP_reg3, DW_OP_reg30, DW_OP_reg31, DW_OP_reg4, DW_OP_reg5, DW_OP_reg6, DW_OP_reg7, DW_OP_reg8, DW_OP_reg9, DW_OP_regx, DW_OP_rot, DW_OP_shl, DW_OP_shr, DW_OP_shra, DW_OP_skip, DW_OP_stack_value, DW_OP_swap, DW_OP_xderef, DW_OP_xderef_size, DW_OP_xor, and value().
dwarf_tag_name()
const char * dwarf_tag_name (unsigned value)
Convert a DW_TAG_* constant to the corresponding string.
The contents of this function was generated by the following vim command:
:read !awk '/define DW_TAG_/ { printf " CASERET(\%s);\n", $2 }' dwarf2.h
Definition at line 27 of file dwarf_names.cpp.
References CASERET, DW_TAG_access_declaration, DW_TAG_arg_variable, DW_TAG_array_type, DW_TAG_auto_variable, DW_TAG_base_type, DW_TAG_catch_block, DW_TAG_class_template, DW_TAG_class_type, DW_TAG_common_block, DW_TAG_common_inclusion, DW_TAG_compile_unit, DW_TAG_condition, DW_TAG_const_type, DW_TAG_constant, DW_TAG_dwarf_procedure, DW_TAG_entry_point, DW_TAG_enumeration_type, DW_TAG_enumerator, DW_TAG_file_type, DW_TAG_formal_parameter, DW_TAG_format_label, DW_TAG_friend, DW_TAG_function_template, DW_TAG_GNU_BINCL, DW_TAG_GNU_EINCL, DW_TAG_hi_user, DW_TAG_HP_array_descriptor, DW_TAG_imported_declaration, DW_TAG_imported_module, DW_TAG_imported_unit, DW_TAG_inheritance, DW_TAG_inlined_subroutine, DW_TAG_interface_block, DW_TAG_interface_type, DW_TAG_kanji_type, DW_TAG_label, DW_TAG_lexical_block, DW_TAG_lo_user, DW_TAG_member, DW_TAG_MIPS_loop, DW_TAG_module, DW_TAG_namelist, DW_TAG_namelist_item, DW_TAG_namespace, DW_TAG_packed_type, DW_TAG_padding, DW_TAG_partial_unit, DW_TAG_pointer_type, DW_TAG_ptr_to_member_type, DW_TAG_reference_type, DW_TAG_restrict_type, DW_TAG_set_type, DW_TAG_shared_type, DW_TAG_string_type, DW_TAG_structure_type, DW_TAG_subprogram, DW_TAG_subrange_type, DW_TAG_subroutine_type, DW_TAG_template_type_param, DW_TAG_template_value_param, DW_TAG_thrown_type, DW_TAG_try_block, DW_TAG_typedef, DW_TAG_union_type, DW_TAG_unspecified_parameters, DW_TAG_unspecified_type, DW_TAG_upc_relaxed_type, DW_TAG_upc_shared_type, DW_TAG_upc_strict_type, DW_TAG_variable, DW_TAG_variant, DW_TAG_variant_part, DW_TAG_volatile_type, DW_TAG_with_stmt, and value().
Referenced by write_mdfield().
dwarf_virtuality_name()
const char * dwarf_virtuality_name (unsigned value)
Definition at line 442 of file dwarf_names.cpp.
References CASERET, DW_VIRTUALITY_none, DW_VIRTUALITY_pure_virtual, DW_VIRTUALITY_virtual, and value().
Referenced by write_mdfield().
emit_dwf2_ftn_func_begin()
void emit_dwf2_ftn_func_begin (int sptr)
input_dwarf_info()
void input_dwarf_info (char * filename)