flang: dwarf_names.cpp File Reference
dwarf_names.cpp File Reference
Converting DWARF symbolic identifiers to textual form.
#include "gbldefs.h"
#include "dwarf2.h"
Macros
#define CASERET(X)
Functions
const char * dwarf_tag_name (unsigned value)
Convert a DW_TAG_* constant to the corresponding string.
const char * dwarf_attr_name (unsigned value)
const char * dwarf_form_name (unsigned value)
const char * dwarf_stack_op_name (unsigned value)
const char * dwarf_virtuality_name (unsigned value)
const char * dwarf_lang_name (unsigned value)
const char * dwarf_encoding_name (unsigned value)
Detailed Description
Converting DWARF symbolic identifiers to textual form.
Definition in file dwarf_names.cpp.
Macro Definition Documentation
CASERET
#define CASERET (X)
Value:
  case X:          \
    return #X
Definition at line 15 of file dwarf_names.cpp.
Function Documentation
dwarf_attr_name()
const char * dwarf_attr_name (unsigned value)
Definition at line 114 of file dwarf_names.cpp.
References CASERET, DW_AT_abstract_origin, DW_AT_accessibility, DW_AT_address_class, DW_AT_allocated, DW_AT_APPLE_block, DW_AT_APPLE_flags, DW_AT_APPLE_isa, DW_AT_APPLE_major_runtime_vers, DW_AT_APPLE_objc_complete_type, DW_AT_APPLE_omit_frame_ptr, DW_AT_APPLE_optimized, DW_AT_APPLE_property, DW_AT_APPLE_property_attribute, DW_AT_APPLE_property_getter, DW_AT_APPLE_property_name, DW_AT_APPLE_property_setter, DW_AT_APPLE_runtime_class, DW_AT_artificial, DW_AT_associated, DW_AT_base_types, DW_AT_binary_scale, DW_AT_bit_offset, DW_AT_bit_size, DW_AT_body_begin, DW_AT_body_end, DW_AT_byte_size, DW_AT_call_column, DW_AT_call_file, DW_AT_call_line, DW_AT_calling_convention, DW_AT_common_reference, DW_AT_comp_dir, DW_AT_const_value, DW_AT_containing_type, DW_AT_count, DW_AT_data_location, DW_AT_data_member_location, DW_AT_decimal_scale, DW_AT_decimal_sign, DW_AT_decl_column, DW_AT_decl_file, DW_AT_decl_line, DW_AT_declaration, DW_AT_default_value, DW_AT_description, DW_AT_digit_count, DW_AT_discr, DW_AT_discr_list, DW_AT_discr_value, DW_AT_element_list, DW_AT_elemental, DW_AT_encoding, DW_AT_endianity, DW_AT_entry_pc, DW_AT_explicit, DW_AT_extension, DW_AT_external, DW_AT_frame_base, DW_AT_friend, DW_AT_GNU_vector, DW_AT_hi_user, DW_AT_high_pc, DW_AT_identifier_case, DW_AT_import, DW_AT_inline, DW_AT_is_optional, DW_AT_language, DW_AT_lbase, DW_AT_lo_user, DW_AT_location, DW_AT_low_pc, DW_AT_lower_bound, DW_AT_lstride, DW_AT_mac_info, DW_AT_macro_info, DW_AT_member, DW_AT_MIPS_linkage_name, DW_AT_mutable, DW_AT_name, DW_AT_namelist_item, DW_AT_object_pointer, DW_AT_ordering, DW_AT_picture_string, DW_AT_priority, DW_AT_producer, DW_AT_prototyped, DW_AT_pure, DW_AT_ranges, DW_AT_recursive, DW_AT_return_addr, DW_AT_segment, DW_AT_sf_names, DW_AT_sibling, DW_AT_small, DW_AT_soffset, DW_AT_specification, DW_AT_src_coords, DW_AT_src_info, DW_AT_start_scope, DW_AT_static_link, DW_AT_stmt_list, DW_AT_stride, DW_AT_stride_size, DW_AT_string_length, DW_AT_subscr_data, DW_AT_threads_scaled, DW_AT_trampoline, DW_AT_type, DW_AT_upc_threads_scaled, DW_AT_upper_bound, DW_AT_use_location, DW_AT_use_UTF8, DW_AT_variable_parameter, DW_AT_virtuality, DW_AT_visibility, DW_AT_VMS_rtnbeg_pd_address, DW_AT_vtable_elem_location, and value().
dwarf_encoding_name()
const char * dwarf_encoding_name (unsigned value)
Definition at line 482 of file dwarf_names.cpp.
References CASERET, DW_ATE_address, DW_ATE_boolean, DW_ATE_complex_float, DW_ATE_decimal_float, DW_ATE_edited, DW_ATE_float, DW_ATE_imaginary_float, DW_ATE_numeric_string, DW_ATE_packed_decimal, DW_ATE_signed, DW_ATE_signed_char, DW_ATE_signed_fixed, DW_ATE_unsigned, DW_ATE_unsigned_char, DW_ATE_unsigned_fixed, and value().
Referenced by write_mdfield().
dwarf_form_name()
const char * dwarf_form_name (unsigned value)
Definition at line 244 of file dwarf_names.cpp.
References CASERET, DW_FORM_addr, DW_FORM_block, DW_FORM_block1, DW_FORM_block2, DW_FORM_block4, DW_FORM_data1, DW_FORM_data2, DW_FORM_data4, DW_FORM_data8, DW_FORM_exprloc, DW_FORM_flag, DW_FORM_flag_present, DW_FORM_indirect, DW_FORM_ref1, DW_FORM_ref2, DW_FORM_ref4, DW_FORM_ref8, DW_FORM_ref_addr, DW_FORM_ref_sig8, DW_FORM_ref_udata, DW_FORM_sdata, DW_FORM_sec_offset, DW_FORM_string, DW_FORM_strp, DW_FORM_udata, and value().
dwarf_lang_name()
const char * dwarf_lang_name (unsigned value)
Definition at line 453 of file dwarf_names.cpp.
References CASERET, DW_LANG_Ada83, DW_LANG_Ada95, DW_LANG_C, DW_LANG_C89, DW_LANG_C99, DW_LANG_C_plus_plus, DW_LANG_Cobol74, DW_LANG_Cobol85, DW_LANG_D, DW_LANG_Fortran77, DW_LANG_Fortran90, DW_LANG_Fortran95, DW_LANG_Java, DW_LANG_Mips_Assembler, DW_LANG_Modula2, DW_LANG_ObjC, DW_LANG_ObjC_plus_plus, DW_LANG_Pascal83, DW_LANG_PLI, DW_LANG_UPC, DW_LANG_Upc, and value().
Referenced by write_mdfield().
dwarf_stack_op_name()
const char * dwarf_stack_op_name (unsigned value)
Definition at line 277 of file dwarf_names.cpp.
References CASERET, DW_OP_abs, DW_OP_addr, DW_OP_and, DW_OP_bit_piece, DW_OP_bra, DW_OP_breg0, DW_OP_breg1, DW_OP_breg10, DW_OP_breg11, DW_OP_breg12, DW_OP_breg13, DW_OP_breg14, DW_OP_breg15, DW_OP_breg16, DW_OP_breg17, DW_OP_breg18, DW_OP_breg19, DW_OP_breg2, DW_OP_breg20, DW_OP_breg21, DW_OP_breg22, DW_OP_breg23, DW_OP_breg24, DW_OP_breg25, DW_OP_breg26, DW_OP_breg27, DW_OP_breg28, DW_OP_breg29, DW_OP_breg3, DW_OP_breg30, DW_OP_breg31, DW_OP_breg4, DW_OP_breg5, DW_OP_breg6, DW_OP_breg7, DW_OP_breg8, DW_OP_breg9, DW_OP_bregx, DW_OP_call2, DW_OP_call4, DW_OP_call_frame_cfa, DW_OP_call_ref, DW_OP_const1s, DW_OP_const1u, DW_OP_const2s, DW_OP_const2u, DW_OP_const4s, DW_OP_const4u, DW_OP_const8s, DW_OP_const8u, DW_OP_consts, DW_OP_constu, DW_OP_deref, DW_OP_deref_size, DW_OP_div, DW_OP_drop, DW_OP_dup, DW_OP_eq, DW_OP_fbreg, DW_OP_form_tls_address, DW_OP_ge, DW_OP_GNU_push_tls_address, DW_OP_GNU_uninit, DW_OP_gt, DW_OP_implicit_value, DW_OP_le, DW_OP_lit0, DW_OP_lit1, DW_OP_lit10, DW_OP_lit11, DW_OP_lit12, DW_OP_lit13, DW_OP_lit14, DW_OP_lit15, DW_OP_lit16, DW_OP_lit17, DW_OP_lit18, DW_OP_lit19, DW_OP_lit2, DW_OP_lit20, DW_OP_lit21, DW_OP_lit22, DW_OP_lit23, DW_OP_lit24, DW_OP_lit25, DW_OP_lit26, DW_OP_lit27, DW_OP_lit28, DW_OP_lit29, DW_OP_lit3, DW_OP_lit30, DW_OP_lit31, DW_OP_lit4, DW_OP_lit5, DW_OP_lit6, DW_OP_lit7, DW_OP_lit8, DW_OP_lit9, DW_OP_lt, DW_OP_minus, DW_OP_mod, DW_OP_mul, DW_OP_ne, DW_OP_neg, DW_OP_nop, DW_OP_not, DW_OP_or, DW_OP_over, DW_OP_PGI_omp_thread_num, DW_OP_pick, DW_OP_piece, DW_OP_plus, DW_OP_plus_uconst, DW_OP_push_object_address, DW_OP_reg0, DW_OP_reg1, DW_OP_reg10, DW_OP_reg11, DW_OP_reg12, DW_OP_reg13, DW_OP_reg14, DW_OP_reg15, DW_OP_reg16, DW_OP_reg17, DW_OP_reg18, DW_OP_reg19, DW_OP_reg2, DW_OP_reg20, DW_OP_reg21, DW_OP_reg22, DW_OP_reg23, DW_OP_reg24, DW_OP_reg25, DW_OP_reg26, DW_OP_reg27, DW_OP_reg28, DW_OP_reg29, DW_OP_reg3, DW_OP_reg30, DW_OP_reg31, DW_OP_reg4, DW_OP_reg5, DW_OP_reg6, DW_OP_reg7, DW_OP_reg8, DW_OP_reg9, DW_OP_regx, DW_OP_rot, DW_OP_shl, DW_OP_shr, DW_OP_shra, DW_OP_skip, DW_OP_stack_value, DW_OP_swap, DW_OP_xderef, DW_OP_xderef_size, DW_OP_xor, and value().
dwarf_tag_name()
const char * dwarf_tag_name (unsigned value)
Convert a DW_TAG_* constant to the corresponding string.
The contents of this function was generated by the following vim command:
:read !awk '/define DW_TAG_/ { printf " CASERET(\%s);\n", $2 }' dwarf2.h
Definition at line 27 of file dwarf_names.cpp.
References CASERET, DW_TAG_access_declaration, DW_TAG_arg_variable, DW_TAG_array_type, DW_TAG_auto_variable, DW_TAG_base_type, DW_TAG_catch_block, DW_TAG_class_template, DW_TAG_class_type, DW_TAG_common_block, DW_TAG_common_inclusion, DW_TAG_compile_unit, DW_TAG_condition, DW_TAG_const_type, DW_TAG_constant, DW_TAG_dwarf_procedure, DW_TAG_entry_point, DW_TAG_enumeration_type, DW_TAG_enumerator, DW_TAG_file_type, DW_TAG_formal_parameter, DW_TAG_format_label, DW_TAG_friend, DW_TAG_function_template, DW_TAG_GNU_BINCL, DW_TAG_GNU_EINCL, DW_TAG_hi_user, DW_TAG_HP_array_descriptor, DW_TAG_imported_declaration, DW_TAG_imported_module, DW_TAG_imported_unit, DW_TAG_inheritance, DW_TAG_inlined_subroutine, DW_TAG_interface_block, DW_TAG_interface_type, DW_TAG_kanji_type, DW_TAG_label, DW_TAG_lexical_block, DW_TAG_lo_user, DW_TAG_member, DW_TAG_MIPS_loop, DW_TAG_module, DW_TAG_namelist, DW_TAG_namelist_item, DW_TAG_namespace, DW_TAG_packed_type, DW_TAG_padding, DW_TAG_partial_unit, DW_TAG_pointer_type, DW_TAG_ptr_to_member_type, DW_TAG_reference_type, DW_TAG_restrict_type, DW_TAG_set_type, DW_TAG_shared_type, DW_TAG_string_type, DW_TAG_structure_type, DW_TAG_subprogram, DW_TAG_subrange_type, DW_TAG_subroutine_type, DW_TAG_template_type_param, DW_TAG_template_value_param, DW_TAG_thrown_type, DW_TAG_try_block, DW_TAG_typedef, DW_TAG_union_type, DW_TAG_unspecified_parameters, DW_TAG_unspecified_type, DW_TAG_upc_relaxed_type, DW_TAG_upc_shared_type, DW_TAG_upc_strict_type, DW_TAG_variable, DW_TAG_variant, DW_TAG_variant_part, DW_TAG_volatile_type, DW_TAG_with_stmt, and value().
Referenced by write_mdfield().
dwarf_virtuality_name()
const char * dwarf_virtuality_name (unsigned value)
Definition at line 442 of file dwarf_names.cpp.
References CASERET, DW_VIRTUALITY_none, DW_VIRTUALITY_pure_virtual, DW_VIRTUALITY_virtual, and value().
Referenced by write_mdfield().