flang: dynam.c File Reference
dynam.c File Reference
Dynamic, realign, redistribute arrays.
#include "stdioInterf.h"
#include "fioMacros.h"
#include "fort_vars.h"
Functions
static void I8() recopy (F90_Desc *ad, F90_Desc *dd, F90_Desc *pd)
void ENTFTN (REALIGN, realign)
void ENTFTN (REDISTRIBUTE, redistribute)
redistribute the distributee and all objects that are currently ultimately-aligned with it (within the scope of the calling subprogram). redistribution does not change alignment relationships.
Detailed Description
Dynamic, realign, redistribute arrays.
Definition in file dynam.c.
Function Documentation
ENTFTN() [1/2]
void ENTFTN (REALIGN , realign)
Definition at line 78 of file dynam.c.
References __DESC, __DIST_FORMAT_MASK, __DIST_FORMAT_SHIFT, __DIST_INIT_DESCRIPTOR, __DIST_SET_ALLOCATION, __DIST_TARGET_MASK, __DIST_TARGET_SHIFT, __DYNAMIC, __fort_abort(), __fort_copy_descriptor(), __fort_finish_descriptor(), __fort_set_alignment(), __fort_set_single(), __fort_show_flags(), __fort_test, __IDENTITY_MAP, __INHERIT, __SEQUENCE, __SINGLE, __TEMPLATE, add(), proc::base, collapse, DEBUG_RDST, DECL_DIM_PTRS, DECL_HDR_PTRS, DECL_HDR_VARS, DIST_ALIGN_TARGET_G, DIST_ALIGN_TARGET_P, DIST_DIST_TARGET_G, DIST_DIST_TARGET_P, DIST_DPTR_BLOCK_G, DIST_DPTR_GEN_BLOCK_G, DIST_DPTR_NO_G, DIST_DPTR_PAXIS_G, DIST_DPTR_PO_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_PSTRIDE_G, DIST_DPTR_TAXIS_G, DIST_DPTR_TLB_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, DIST_INFO_G, DIST_NEXT_ALIGNEE_G, DIST_NEXT_ALIGNEE_P, DIST_SINGLE_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_FLAGS_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, flags, GET_DIST_LCPU, i, I8, m, MAXDIMS, next, NULL, p_flags, p_rank, prev, rank, realign, recopy(), SET_DIM_PTRS, proc::size, td, tstride, and va.
ENTFTN() [2/2]
void ENTFTN (REDISTRIBUTE , redistribute)
redistribute the distributee and all objects that are currently ultimately-aligned with it (within the scope of the calling subprogram). redistribution does not change alignment relationships.
  varargs are:
  [ proc *dist_target, ]
  __INT_T *isstar,
  { [__INT_T paxis,](__INT_T *dstfmt, |
    (__INT_T * gen_block_array, __INT_T extent) ) }*
*
Definition at line 350 of file dynam.c.
References __ALIGN_TARGET_MASK, __ALIGN_TARGET_SHIFT, __DESC, __DESCRIPTIVE, __DIST_FORMAT_MASK, __DIST_FORMAT_SHIFT, __DIST_INIT_DESCRIPTOR, __DIST_SET_ALLOCATION, __DIST_SET_DISTRIBUTION, __DIST_TARGET_AXIS, __DIST_TARGET_MASK, __DIST_TARGET_SHIFT, __DYNAMIC, __fort_abort(), __fort_copy_descriptor(), __fort_defaultproc(), __fort_finish_descriptor(), __fort_set_alignment(), __fort_show_flags(), __fort_test, __OMITTED, __PRESCRIPTIVE, __PROC, __SEQUENCE, __TEMPLATE, __TRANSCRIPTIVE, proc::base, DEBUG_RDST, DECL_DIM_PTRS, DECL_HDR_PTRS, DECL_HDR_VARS, DFMT, DFMT__MASK, DFMT__WIDTH, DFMT_BLOCK, DFMT_BLOCK_K, DFMT_COLLAPSED, DFMT_CYCLIC, DFMT_CYCLIC_K, DFMT_GEN_BLOCK, proc::dim, DIST_ALIGN_TARGET_G, DIST_ALIGN_TARGET_P, DIST_DFMT_G, DIST_DFMT_P, DIST_DIM_GEN_BLOCK_G, DIST_DIM_GEN_BLOCK_P, DIST_DIM_TAXIS_G, DIST_DIST_TARGET_G, DIST_DPTR_BLOCK_G, DIST_DPTR_NO_G, DIST_DPTR_PAXIS_G, DIST_DPTR_PO_G, DIST_DPTR_TAXIS_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, DIST_NEXT_ALIGNEE_G, DIST_NEXT_ALIGNEE_P, DPTR_UBOUND_G, EXTENSION_BLOCK_MASK, F90_DPTR_LBOUND_G, F90_FLAGS_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, flags, GET_DIST_LCPU, i, I8, j, MAXDIMS, next, NULL, p_flags, p_rank, proc::rank, rank, recopy(), redistribute, SET_DIM_PTRS, procdim::shape, proc::size, proc::tag, td, and va.
recopy()
static void I8() recopy (F90_Desc * ad, F90_Desc * dd, F90_Desc * pd) static
Definition at line 23 of file dynam.c.
References __fort_allocate(), __fort_copy(), __fort_deallocate(), __fort_doit(), __fort_frechn(), __fort_test, __NOT_COPIED, __TEMPLATE, base, db(), DEBUG_RDST, df, DIST_SCOFF_G, F90_FLAGS_G, F90_FLAGS_P, F90_KIND_G, F90_LEN_G, F90_LSIZE_G, GET_DIST_LCPU, I8, ISPRESENT, NULL, off, and pd.
Referenced by ENTFTN().