flang: encodefmt.c File Reference
encodefmt.c File Reference
#include "global.h"
#include "feddesc.h"
Macros
#define STACK_SIZE 20 /* max nesting depth of parens */
#define is_digit(c) ((c) >= '0' && (c) <= '9')
#define DT_LEN 2
Typedefs
typedef int ERRCODE
Functions
static ERRCODE check_outer_parens (char *, __CLEN_T)
static bool ef_getnum (char *, int *)
static int ef_nextchar (char *, int *)
static void ef_put (INT)
static void ef_putnum (INT)
static ERRCODE ef_putstring (char *, INT, int)
static void ef_alloc (int)
static INT ef_error (ERRCODE)
static void ef_putvlist (char *, int *)
static void ef_putdt ()
static void ef_putiotype (char *, int *)
static __INT_T _f90io_encode_fmt (char *str, __INT_T *nelem, __CLEN_T str_siz)
__INT_T (__INT_T *kind, __INT_T *nelem, DCHAR(str) DCLEN64(str))
__INT_T (__INT_T *kind, __INT_T *nelem, DCHAR(str) DCLEN(str))
__INT_T (char **str)
Variables
static long numval
static char * firstchar
static char * lastchar
static int curpos
static int paren_stack [STACK_SIZE]
static bool enclosing_parens
static INT * buff = NULL
static int buffsize = 0
static char quote
Macro Definition Documentation
DT_LEN
#define DT_LEN 2
Definition at line 849 of file encodefmt.c.
is_digit
#define is_digit (c) ((c) >= '0' && (c) <= '9')
Definition at line 16 of file encodefmt.c.
STACK_SIZE
#define STACK_SIZE 20 /* max nesting depth of parens */
Definition at line 15 of file encodefmt.c.
Typedef Documentation
ERRCODE
typedef int ERRCODE
Definition at line 18 of file encodefmt.c.
Function Documentation
__INT_T() [1/3]
__INT_T (__INT_T * kind, __INT_T * nelem, DCHAR(str) DCLEN(str))
Definition at line 968 of file encodefmt.c.
References __CLEN_T, CADR, CLEN, ENTF90IO, kind, nelem, and str.
__INT_T() [2/3]
__INT_T (__INT_T * kind, __INT_T * nelem, DCHAR(str) DCLEN64(str))
Definition at line 943 of file encodefmt.c.
References __CLEN_T, __fortio_errend03(), __STR, _f90io_encode_fmt(), buff, buffsize, CADR, CLEN, GET_DIST_IOPROC, GET_DIST_LCPU, GET_DIST_SIZE_OF, kind, len, LOCAL_MODE, nelem, NULL, s, str, and void().
__INT_T() [3/3]
__INT_T (char ** str)
Definition at line 1009 of file encodefmt.c.
References __fortio_errend03(), _f90io_encode_fmt(), buff, buffsize, GET_DIST_IOPROC, GET_DIST_LCPU, len, LOCAL_MODE, nelem, NULL, s, str, and void().
_f90io_encode_fmt()
static __INT_T _f90io_encode_fmt (char * str, __INT_T * nelem, __CLEN_T str_siz) static
Definition at line 44 of file encodefmt.c.
References __fortio_errinit03(), __fortio_fmtinit(), assert, c, check_outer_parens(), curpos, ef_error(), ef_getnum(), ef_nextchar(), ef_put(), ef_putdt(), ef_putiotype(), ef_putnum(), ef_putstring(), ef_putvlist(), enclosing_parens, envar_fortranopt, FALSE, FED_A, FED_Aw, FED_BN, FED_Bw_m, FED_BZ, FED_COLON, FED_D, FED_DC, FED_DOLLAR, FED_DP, FED_DT, FED_Dw_d, FED_E, FED_Ee, FED_END, FED_ENw_d, FED_ESw_d, FED_Ew_d, FED_F, FED_Fw_d, FED_G, FED_G0, FED_G0_d, FED_Gw_d, FED_I, FED_Iw_m, FED_L, FED_LPAREN, FED_Lw, FED_O, FED_Ow_m, FED_P, FED_Q, FED_RC, FED_RD, FED_RN, FED_RP, FED_RPAREN, FED_RU, FED_RZ, FED_S, FED_SLASH, FED_SP, FED_SS, FED_T, FED_TL, FED_TR, FED_X, FED_Z, FED_Zw_m, FIO_ECHAR, FIO_EDOT, FIO_EENDFMT, FIO_EFGD, FIO_EFSYNTAX, FIO_ELETTER, FIO_EPAREN, FIO_EPT, FIO_ESTRING, firstchar, i, j, k, lastchar, n, nelem, NULL, numval, p, paren_stack, quote, STACK_SIZE, str, TRUE, and void().
Referenced by __INT_T().
check_outer_parens()
static ERRCODE check_outer_parens (char * p, __CLEN_T len) static
Definition at line 621 of file encodefmt.c.
References enclosing_parens, envar_fortranopt, FALSE, FIO_ELPAREN, firstchar, lastchar, len, NULL, p, q, and TRUE.
Referenced by _f90io_encode_fmt().
ef_alloc()
static void ef_alloc (int len) static
Definition at line 918 of file encodefmt.c.
References assert, buff, buffsize, FIO_TBL::enctab, fioFcbTbls, len, malloc(), and NULL.
Referenced by ef_put(), ef_putdt(), ef_putiotype(), ef_putnum(), ef_putstring(), and ef_putvlist().
ef_error()
static INT ef_error (ERRCODE code) static
Definition at line 932 of file encodefmt.c.
References curpos, ef_put(), and FED_ERROR.
Referenced by _f90io_encode_fmt().
ef_getnum()
static bool ef_getnum (char * p, int * len) static
Definition at line 657 of file encodefmt.c.
References c, ef_nextchar(), FALSE, is_digit, lastchar, len, numval, p, and TRUE.
Referenced by _f90io_encode_fmt(), and ef_putvlist().
ef_nextchar()
static int ef_nextchar (char * p, int * len) static
Definition at line 689 of file encodefmt.c.
References c, lastchar, len, and p.
Referenced by _f90io_encode_fmt(), and ef_getnum().
ef_put()
static void ef_put (INT val) static
Definition at line 729 of file encodefmt.c.
References buff, buffsize, curpos, ef_alloc(), and val.
Referenced by _f90io_encode_fmt(), ef_error(), and ef_putstring().
ef_putdt()
static void ef_putdt () static
Definition at line 851 of file encodefmt.c.
References buff, buffsize, curpos, DT_LEN, ef_alloc(), ef_putnum(), and q.
Referenced by _f90io_encode_fmt().
ef_putiotype()
static void ef_putiotype (char * p, int * numlen) static
Definition at line 866 of file encodefmt.c.
References buff, buffsize, curpos, DT_LEN, ef_alloc(), ef_putnum(), ef_putvlist(), lastchar, len, n, p, and q.
Referenced by _f90io_encode_fmt().
ef_putnum()
static void ef_putnum (INT val) static
Definition at line 740 of file encodefmt.c.
References buff, buffsize, curpos, ef_alloc(), and val.
Referenced by _f90io_encode_fmt(), ef_putdt(), ef_putiotype(), and ef_putvlist().
ef_putstring()
static ERRCODE ef_putstring (char * p, INT len, int quote_count) static
Definition at line 821 of file encodefmt.c.
References buff, buffsize, curpos, ef_alloc(), ef_put(), FED_STR, FIO_ESTRING, lastchar, len, p, q, and quote.
Referenced by _f90io_encode_fmt().
ef_putvlist()
static void ef_putvlist (char * p, int * len) static
Definition at line 750 of file encodefmt.c.
References buff, buffsize, cnt, curpos, ef_alloc(), ef_getnum(), ef_putnum(), i, j, lastchar, len, numval, and p.
Referenced by _f90io_encode_fmt(), and ef_putiotype().
Variable Documentation
buff
INT* buff = NULL static
Definition at line 25 of file encodefmt.c.
Referenced by __INT_T(), add_ctor(), decimal_increment(), decode_expression_op(), display_error(), doincl(), ef_alloc(), ef_put(), ef_putdt(), ef_putiotype(), ef_putnum(), ef_putstring(), ef_putvlist(), emitComplexDIExpression(), ENT3F(), enter(), format_fraction(), format_int_part(), fr_getreal(), fraction_digits(), lldbg_function_end(), lookup(), mergeDebugTypesForGlobal(), newbuff(), newprintfd(), newprintfi(), newprintfl(), newprintfs(), newprintfx(), sem_err104(), symdentry(), symini_interr(), ui64toa(), write_ast(), and write_instructions().
buffsize
int buffsize = 0 static
Definition at line 26 of file encodefmt.c.
Referenced by __INT_T(), ef_alloc(), ef_put(), ef_putdt(), ef_putiotype(), ef_putnum(), ef_putstring(), and ef_putvlist().
curpos
int curpos static
Definition at line 22 of file encodefmt.c.
Referenced by _f90io_encode_fmt(), ef_error(), ef_put(), ef_putdt(), ef_putiotype(), ef_putnum(), ef_putstring(), and ef_putvlist().
enclosing_parens
bool enclosing_parens static
Definition at line 24 of file encodefmt.c.
Referenced by _f90io_encode_fmt(), and check_outer_parens().
firstchar
char* firstchar static
Definition at line 21 of file encodefmt.c.
Referenced by _f90io_encode_fmt(), and check_outer_parens().
lastchar
char * lastchar static
Definition at line 21 of file encodefmt.c.
Referenced by _f90io_encode_fmt(), check_outer_parens(), ef_getnum(), ef_nextchar(), ef_putiotype(), ef_putstring(), and ef_putvlist().
numval
long numval static
Definition at line 20 of file encodefmt.c.
Referenced by _f90io_encode_fmt(), ef_getnum(), and ef_putvlist().
paren_stack
int paren_stack[STACK_SIZE] static
Definition at line 23 of file encodefmt.c.
Referenced by _f90io_encode_fmt().
quote
char quote static
Definition at line 27 of file encodefmt.c.
Referenced by _f90io_encode_fmt(), ef_putstring(), ff_prescan(), and get_qstr().