flang: endfile.c File Reference
endfile.c File Reference
Implement Fortran ENDFILE statement.
#include "global.h"
Functions
static int _f90io_endfile (__INT_T *unit, __INT_T *bitv, __INT_T *iostat)
__INT_T ENTF90IO (ENDFILE, endfile)
__INT_T ENTCRF90IO (ENDFILE, endfile)
Detailed Description
Implement Fortran ENDFILE statement.
Definition in file endfile.c.
Function Documentation
_f90io_endfile()
static int _f90io_endfile (__INT_T * unit, __INT_T * bitv, __INT_T * iostat) static
Definition at line 18 of file endfile.c.
References __fortio_errinit03(), __fortio_error(), __fortio_rwinit(), bitv, fcb::eof_flag, ERR_FLAG, f, FIO_EUNIT, FIO_UNFORMATTED, ILLEGAL_UNIT, NULL, and TRUE.
Referenced by ENTCRF90IO(), and ENTF90IO().
ENTCRF90IO()
__INT_T ENTCRF90IO (ENDFILE , endfile)
Definition at line 50 of file endfile.c.
References __fortio_errend03(), _f90io_endfile(), bitv, and s.
ENTF90IO()
__INT_T ENTF90IO (ENDFILE , endfile)
Definition at line 38 of file endfile.c.
References __fort_status_init(), __fortio_errend03(), _f90io_endfile(), bitv, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, and s.