flang: entry.c File Reference
entry.c File Reference
FIXME.
#include "stdioInterf.h"
#include "fioMacros.h"
Classes
struct pent
Macros
#define PENTS 256 /* initial number of stack entries */
#define UNKNOWN "<unknown>" /* function/file name of dummy entry */
Functions
void __fort_entry_init (void)
Initialization.
void ENTFTN (FUNCTION_ENTRYA, function_entrya)
void ENTFTN (FUNCTION_ENTRY, function_entry)
void ENTFTN (FUNCTION_EXIT, function_exit)()
void ENTFTN (LINE_ENTRY, line_entry)()
void __fort_traceback ()
void ENTFTN (TRACEBACK, traceback)()
void __fort_tracecall (const char *msg)
void ENTFTN (TRACECALLA, tracecalla)
void ENTFTN (TRACECALL, tracecall)
void __fort_entry_recv (int cpu, long len)
void __fort_entry_recv_done (int cpu)
void __fort_entry_send (int cpu, long len)
void __fort_entry_send_done (int cpu)
void __fort_entry_copy (long len)
void __fort_entry_copy_done (void)
void __fort_entry_arecv (int cpu, long len, int reqn)
void __fort_entry_arecv_done (int cpu)
void __fort_entry_asend (int cpu, long len, int reqn)
void __fort_entry_asend_done (int cpu)
void __fort_entry_await (int reqn)
void __fort_entry_await_done (int reqn)
void __fort_entry_term (void)
Termination.
Variables
WIN_API __INT_T LINENO []
static struct pent * pentb
static struct pent * pentc
static struct pent * pente
static int __fort_stat_mflag
static int __fort_trac_mflag
static int __fort_prof_mflag
int __fort_entry_mflag
Detailed Description
FIXME.
Definition in file entry.c.
Macro Definition Documentation
PENTS
#define PENTS 256 /* initial number of stack entries */
Definition at line 36 of file entry.c.
UNKNOWN
#define UNKNOWN "<unknown>" /* function/file name of dummy entry */
Definition at line 37 of file entry.c.
Function Documentation
__fort_entry_arecv()
void __fort_entry_arecv (int cpu, long len, int reqn)
Definition at line 342 of file entry.c.
References __fort_prof_arecv(), __fort_prof_mflag, __fort_stat_arecv(), __fort_stat_mflag, __fort_trac_arecv(), __fort_trac_mflag, cpu(), and len.
__fort_entry_arecv_done()
void __fort_entry_arecv_done (int cpu)
Definition at line 358 of file entry.c.
References __fort_prof_arecv_done(), __fort_prof_mflag, __fort_stat_arecv_done(), __fort_stat_mflag, __fort_trac_mflag, __fort_trac_recv_done(), and cpu().
__fort_entry_asend()
void __fort_entry_asend (int cpu, long len, int reqn)
Definition at line 374 of file entry.c.
References __fort_prof_asend(), __fort_prof_mflag, __fort_stat_asend(), __fort_stat_mflag, __fort_trac_asend(), __fort_trac_mflag, cpu(), and len.
__fort_entry_asend_done()
void __fort_entry_asend_done (int cpu)
Definition at line 390 of file entry.c.
References __fort_prof_asend_done(), __fort_prof_mflag, __fort_stat_asend_done(), __fort_stat_mflag, __fort_trac_asend_done(), __fort_trac_mflag, and cpu().
__fort_entry_await()
void __fort_entry_await (int reqn)
Definition at line 406 of file entry.c.
References __fort_prof_await(), __fort_prof_mflag, __fort_stat_await(), __fort_stat_mflag, __fort_trac_await(), and __fort_trac_mflag.
__fort_entry_await_done()
void __fort_entry_await_done (int reqn)
Definition at line 422 of file entry.c.
References __fort_prof_await_done(), __fort_prof_mflag, __fort_stat_await_done(), __fort_stat_mflag, __fort_trac_await_done(), and __fort_trac_mflag.
__fort_entry_copy()
void __fort_entry_copy (long len)
Definition at line 310 of file entry.c.
References __fort_prof_copy(), __fort_prof_mflag, __fort_stat_copy(), __fort_stat_mflag, __fort_trac_copy(), __fort_trac_mflag, and len.
__fort_entry_copy_done()
void __fort_entry_copy_done (void)
Definition at line 326 of file entry.c.
References __fort_prof_copy_done(), __fort_prof_mflag, __fort_stat_copy_done(), __fort_stat_mflag, __fort_trac_copy_done(), and __fort_trac_mflag.
__fort_entry_init()
void __fort_entry_init (void)
Initialization.
Definition at line 60 of file entry.c.
References __fort_entry_mflag, __fort_malloc(), __fort_prof_init(), __fort_prof_mflag, __fort_stat_init(), __fort_stat_mflag, __fort_trac_init(), __fort_trac_mflag, pent::file, pent::filel, pent::func, pent::funcl, pentb, pentc, pente, PENTS, and UNKNOWN.
Referenced by ENTFTN().
__fort_entry_recv()
void __fort_entry_recv (int cpu, long len)
Definition at line 246 of file entry.c.
References __fort_prof_mflag, __fort_prof_recv(), __fort_stat_mflag, __fort_stat_recv(), __fort_trac_mflag, __fort_trac_recv(), cpu(), and len.
__fort_entry_recv_done()
void __fort_entry_recv_done (int cpu)
Definition at line 262 of file entry.c.
References __fort_prof_mflag, __fort_prof_recv_done(), __fort_stat_mflag, __fort_stat_recv_done(), __fort_trac_mflag, __fort_trac_recv_done(), and cpu().
__fort_entry_send()
void __fort_entry_send (int cpu, long len)
Definition at line 278 of file entry.c.
References __fort_prof_mflag, __fort_prof_send(), __fort_stat_mflag, __fort_stat_send(), __fort_trac_mflag, __fort_trac_send(), cpu(), and len.
__fort_entry_send_done()
void __fort_entry_send_done (int cpu)
Definition at line 294 of file entry.c.
References __fort_prof_mflag, __fort_prof_send_done(), __fort_stat_mflag, __fort_stat_send_done(), __fort_trac_mflag, __fort_trac_send_done(), and cpu().
__fort_entry_term()
void __fort_entry_term (void)
Termination.
Definition at line 437 of file entry.c.
References __fort_entry_mflag, __fort_prof_term(), __fort_stat_term(), and __fort_trac_term().
Referenced by term().
__fort_traceback()
void __fort_traceback (void)
Definition at line 144 of file entry.c.
References buf, pent::cline, pent::file, pent::filel, pent::func, pent::funcl, GET_DIST_LCPU, LINENO, p, pentb, pentc, strlen(), and write.
Referenced by __fort_abortx(), and ENTFTN().
__fort_tracecall()
void __fort_tracecall (const char * msg)
Definition at line 183 of file entry.c.
References buf, pent::cline, pent::file, pent::filel, pent::func, pent::funcl, GET_DIST_LCPU, LINENO, msg(), p, pentb, pentc, strlen(), and write.
Referenced by ENTFTN().
ENTFTN() [1/7]
void ENTFTN (FUNCTION_ENTRY , function_entry)
Definition at line 111 of file entry.c.
References __CLEN_T, CADR, CLEN, ENTFTN(), pent::file, func, line, and pent::lines.
ENTFTN() [2/7]
void ENTFTN (FUNCTION_ENTRYA , function_entrya)
Definition at line 78 of file entry.c.
References __fort_prof_function_entry(), __fort_realloc(), __fort_stat_function_entry(), __fort_trac_function_entry(), CADR, CLEN, pent::cline, pent::file, pent::filel, pent::func, func, pent::funcl, pent::line, line, LINENO, pent::lines, n, pentb, pentc, pente, and PENTS.
Referenced by ENTFTN().
ENTFTN() [3/7]
void ENTFTN (FUNCTION_EXIT , function_exit)
Definition at line 122 of file entry.c.
References __fort_prof_function_exit(), __fort_stat_function_exit(), __fort_trac_function_exit(), pent::cline, LINENO, and pentc.
ENTFTN() [4/7]
void ENTFTN (LINE_ENTRY , line_entry)
Definition at line 134 of file entry.c.
References __fort_prof_line_entry(), __fort_stat_line_entry(), __fort_trac_line_entry(), and LINENO.
ENTFTN() [5/7]
void ENTFTN (TRACEBACK , traceback)
Definition at line 178 of file entry.c.
References __fort_traceback().
ENTFTN() [6/7]
void ENTFTN (TRACECALL , tracecall)
Definition at line 238 of file entry.c.
References __CLEN_T, CADR, CLEN, ENTFTN(), and msg().
ENTFTN() [7/7]
void ENTFTN (TRACECALLA , tracecalla)
Definition at line 223 of file entry.c.
References __CLEN_T, __fort_tracecall(), buf, CADR, CLEN, i, len, msg(), and p.
Variable Documentation
__fort_entry_mflag
int __fort_entry_mflag
Definition at line 46 of file entry.c.
Referenced by __fort_entry_init(), and __fort_entry_term().
__fort_prof_mflag
int __fort_prof_mflag static
Definition at line 45 of file entry.c.
Referenced by __fort_entry_arecv(), __fort_entry_arecv_done(), __fort_entry_asend(), __fort_entry_asend_done(), __fort_entry_await(), __fort_entry_await_done(), __fort_entry_copy(), __fort_entry_copy_done(), __fort_entry_init(), __fort_entry_recv(), __fort_entry_recv_done(), __fort_entry_send(), and __fort_entry_send_done().
__fort_stat_mflag
int __fort_stat_mflag static
Definition at line 43 of file entry.c.
Referenced by __fort_entry_arecv(), __fort_entry_arecv_done(), __fort_entry_asend(), __fort_entry_asend_done(), __fort_entry_await(), __fort_entry_await_done(), __fort_entry_copy(), __fort_entry_copy_done(), __fort_entry_init(), __fort_entry_recv(), __fort_entry_recv_done(), __fort_entry_send(), and __fort_entry_send_done().
__fort_trac_mflag
int __fort_trac_mflag static
Definition at line 44 of file entry.c.
Referenced by __fort_entry_arecv(), __fort_entry_arecv_done(), __fort_entry_asend(), __fort_entry_asend_done(), __fort_entry_await(), __fort_entry_await_done(), __fort_entry_copy(), __fort_entry_copy_done(), __fort_entry_init(), __fort_entry_recv(), __fort_entry_recv_done(), __fort_entry_send(), and __fort_entry_send_done().
LINENO
WIN_API __INT_T LINENO[]
Definition at line 17 of file entry.c.
Referenced by __fort_traceback(), __fort_tracecall(), and ENTFTN().
pentb
struct pent* pentb static
Definition at line 39 of file entry.c.
Referenced by __fort_entry_init(), __fort_traceback(), __fort_tracecall(), and ENTFTN().
pentc
struct pent* pentc static
Definition at line 40 of file entry.c.
Referenced by __fort_entry_init(), __fort_traceback(), __fort_tracecall(), and ENTFTN().
pente
struct pent* pente static
Definition at line 41 of file entry.c.
Referenced by __fort_entry_init(), and ENTFTN().