flang: eoshift.c File Reference
eoshift.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "fort_vars.h"
Functions
static void I8() eoshift_scalar (char *rb, char *ab, __INT_T shift_amt, char *bb, __INT_T shift_dim, F90_Desc *rs, F90_Desc *as, F90_Desc *rc, F90_Desc *ac, __INT_T sub_dim)
static void I8() eoshift_loop (char *rb, char *ab, __INT_T *sb, char *bb, __INT_T shift_dim, F90_Desc *rs, F90_Desc *as, F90_Desc *ss, F90_Desc *bs, F90_Desc *rc, F90_Desc *ac, __INT_T soff, __INT_T boff, __INT_T loop_dim)
void ENTFTN (EOSHIFTSZ, eoshiftsz)
void ENTFTN (EOSHIFTSZCA, eoshiftszca)
void ENTFTN (EOSHIFTSZC, eoshiftszc)
void ENTFTN (EOSHIFTSS, eoshiftss)
void ENTFTN (EOSHIFTSSCA, eoshiftssca)
void ENTFTN (EOSHIFTSSC, eoshiftssc)
void ENTFTN (EOSHIFTSA, eoshiftsa)
void ENTFTN (EOSHIFTSACA, eoshiftsaca)
void ENTFTN (EOSHIFTSAC, eoshiftsac)
void ENTFTN (EOSHIFTZ, eoshiftz)
void ENTFTN (EOSHIFTZCA, eoshiftzca)
void ENTFTN (EOSHIFTZC, eoshiftzc)
void ENTFTN (EOSHIFTS, eoshifts)
void ENTFTN (EOSHIFTSCA, eoshiftsca)
void ENTFTN (EOSHIFTSC, eoshiftsc)
void ENTFTN (EOSHIFT, eoshift)
void ENTFTN (EOSHIFTCA, eoshiftca)
void ENTFTN (EOSHIFTC, eoshiftc)
Function Documentation
ENTFTN() [1/18]
void ENTFTN (EOSHIFT , eoshift)
Definition at line 745 of file eoshift.c.
References __DIST_INIT_SECTION, __fort_show_section(), __fort_test, db(), DEBUG_EOSH, DECL_HDR_VARS, dim, eoshift_loop(), F90_LBASE_G, F90_RANK_G, GET_DIST_LCPU, I8, rb, rc, sb, and ss.
ENTFTN() [2/18]
void ENTFTN (EOSHIFTC , eoshiftc)
Definition at line 807 of file eoshift.c.
References __CLEN_T, CADR, CLEN, db(), ds(), ENTFTN(), rb, sb, and ss.
ENTFTN() [3/18]
void ENTFTN (EOSHIFTCA , eoshiftca)
Definition at line 788 of file eoshift.c.
References CADR, db(), ds(), ENTFTN(), rb, sb, and ss.
ENTFTN() [4/18]
void ENTFTN (EOSHIFTS , eoshifts)
Definition at line 663 of file eoshift.c.
References __DIST_INIT_SECTION, __fort_print_scalar(), __fort_show_section(), __fort_test, db(), DEBUG_EOSH, DECL_HDR_VARS, dim, eoshift_loop(), F90_LBASE_G, F90_RANK_G, F90_TAG_G, GET_DIST_LCPU, I8, rb, rc, sb, and ss.
ENTFTN() [5/18]
void ENTFTN (EOSHIFTSA , eoshiftsa)
Definition at line 509 of file eoshift.c.
References __DIST_INIT_SECTION, __fort_show_section(), __fort_test, db(), DEBUG_EOSH, DECL_HDR_VARS, dim, eoshift_loop(), F90_LBASE_G, F90_RANK_G, GET_DIST_LCPU, I8, rb, rc, sb, shift, and ss.
ENTFTN() [6/18]
void ENTFTN (EOSHIFTSAC , eoshiftsac)
Definition at line 567 of file eoshift.c.
References __CLEN_T, CADR, CLEN, db(), ds(), ENTFTN(), rb, sb, and ss.
ENTFTN() [7/18]
void ENTFTN (EOSHIFTSACA , eoshiftsaca)
Definition at line 548 of file eoshift.c.
References CADR, db(), ds(), ENTFTN(), rb, sb, and ss.
ENTFTN() [8/18]
void ENTFTN (EOSHIFTSC , eoshiftsc)
Definition at line 724 of file eoshift.c.
References __CLEN_T, CADR, CLEN, db(), ds(), ENTFTN(), rb, sb, and ss.
ENTFTN() [9/18]
void ENTFTN (EOSHIFTSCA , eoshiftsca)
Definition at line 705 of file eoshift.c.
References CADR, db(), ds(), ENTFTN(), rb, sb, and ss.
ENTFTN() [10/18]
void ENTFTN (EOSHIFTSS , eoshiftss)
Definition at line 418 of file eoshift.c.
References __DIST_INIT_SECTION, __fort_print_scalar(), __fort_set_section(), __fort_show_section(), __fort_test, db(), DEBUG_EOSH, DECL_DIM_PTRS, DECL_HDR_VARS, dim, DPTR_UBOUND_G, eoshift_scalar(), F90_DPTR_LBOUND_G, F90_RANK_G, F90_TAG_G, GET_DIST_LCPU, i, I8, rb, rc, sb, SET_DIM_PTRS, and shift.
ENTFTN() [11/18]
void ENTFTN (EOSHIFTSSC , eoshiftssc)
Definition at line 488 of file eoshift.c.
References __CLEN_T, CADR, CLEN, db(), ds(), ENTFTN(), rb, sb, and ss.
ENTFTN() [12/18]
void ENTFTN (EOSHIFTSSCA , eoshiftssca)
Definition at line 469 of file eoshift.c.
References CADR, db(), ds(), ENTFTN(), rb, sb, and ss.
ENTFTN() [13/18]
void ENTFTN (EOSHIFTSZ , eoshiftsz)
Definition at line 336 of file eoshift.c.
References __DIST_INIT_SECTION, __fort_set_section(), __fort_show_section(), __fort_test, __STR, db(), DEBUG_EOSH, DECL_DIM_PTRS, DECL_HDR_VARS, dim, DPTR_UBOUND_G, eoshift_scalar(), F90_DPTR_LBOUND_G, F90_KIND_G, F90_RANK_G, GET_DIST_LCPU, GET_DIST_ZED, i, I8, rb, rc, sb, SET_DIM_PTRS, and shift.
Referenced by ENTFTN().
ENTFTN() [14/18]
void ENTFTN (EOSHIFTSZC , eoshiftszc)
Definition at line 401 of file eoshift.c.
References __CLEN_T, CADR, CLEN, db(), ds(), ENTFTN(), rb, sb, and ss.
ENTFTN() [15/18]
void ENTFTN (EOSHIFTSZCA , eoshiftszca)
Definition at line 386 of file eoshift.c.
References CADR, db(), ds(), ENTFTN(), rb, sb, and ss.
ENTFTN() [16/18]
void ENTFTN (EOSHIFTZ , eoshiftz)
Definition at line 588 of file eoshift.c.
References __DIST_INIT_SECTION, __fort_show_section(), __fort_test, __STR, db(), DEBUG_EOSH, DECL_HDR_PTRS, DECL_HDR_VARS, dim, eoshift_loop(), F90_KIND_G, F90_LBASE_G, F90_RANK_G, GET_DIST_LCPU, GET_DIST_ZED, I8, rb, rc, sb, and ss.
ENTFTN() [17/18]
void ENTFTN (EOSHIFTZC , eoshiftzc)
Definition at line 646 of file eoshift.c.
References __CLEN_T, CADR, CLEN, db(), ds(), ENTFTN(), rb, sb, and ss.
ENTFTN() [18/18]
void ENTFTN (EOSHIFTZCA , eoshiftzca)
Definition at line 631 of file eoshift.c.
References CADR, db(), ds(), ENTFTN(), rb, sb, and ss.
eoshift_loop()
static void I8() eoshift_loop (char * rb, char * ab, __INT_T * sb, char * bb, __INT_T shift_dim, F90_Desc * rs, F90_Desc * as, F90_Desc * ss, F90_Desc * bs, F90_Desc * rc, F90_Desc * ac, __INT_T soff, __INT_T boff, __INT_T loop_dim) static
Definition at line 237 of file eoshift.c.
References __DESC, __fort_set_single(), __SCALAR, DECL_DIM_PTRS, DIST_CACHED_P, DIST_PBASE_G, DIST_PBASE_P, DIST_REPLICATED_G, DIST_REPLICATED_P, DIST_SCOFF_G, DIST_SCOFF_P, DPTR_UBOUND_G, eoshift_loop(), eoshift_scalar(), F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_FLAGS_P, F90_LBASE_G, F90_LBASE_P, F90_LEN_G, F90_TAG_G, I8, rb, rc, sb, SET_DIM_PTRS, and ss.
Referenced by ENTFTN(), and eoshift_loop().
eoshift_scalar()
static void I8() eoshift_scalar (char * rb, char * ab, __INT_T shift_amt, char * bb, __INT_T shift_dim, F90_Desc * rs, F90_Desc * as, F90_Desc * rc, F90_Desc * ac, __INT_T sub_dim) static
Definition at line 15 of file eoshift.c.
References __fort_copy(), __fort_doit(), __fort_fills(), __fort_finish_section(), __fort_frechn(), __fort_print_scalar(), __fort_set_section(), __fort_test, Abs, c, DEBUG_EOSH, DECL_DIM_PTRS, DIST_CACHED_P, DIST_DIM_OLB_G, DIST_DIM_OLB_P, DIST_DIM_OUB_G, DIST_DIM_OUB_P, DIST_PBASE_G, DIST_PBASE_P, DIST_REPLICATED_G, DIST_REPLICATED_P, DIST_SCOFF_G, DIST_SCOFF_P, DPTR_UBOUND_G, extent(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_FLAGS_G, F90_FLAGS_P, F90_KIND_G, F90_LBASE_G, F90_LBASE_P, F90_LEN_G, F90_RANK_G, GET_DIST_LCPU, i, I8, MAXDIMS, NULL, rb, rc, and SET_DIM_PTRS.
Referenced by ENTFTN(), and eoshift_loop().