flang: exch.c File Reference
exch.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "fort_vars.h"
Functions
int __fort_exchange_counts (int *counts)
Variables
static int _1 = 1
static chdr * exch [16] = {NULL}
static int * rbuf
static int * sbuf
static int * vcounts
static int * vrbuf
static int * vsbuf
static int rmax
static int smax
static int vrmax
Function Documentation
__fort_exchange_counts()
int __fort_exchange_counts (int * counts)
Definition at line 28 of file exch.c.
References _1, __CINT, __fort_chn_1to1(), __fort_chn_prune(), __fort_doit(), __fort_gmalloc(), __fort_np2, __fort_recvl(), __fort_sendl(), __fort_test, c, cpu(), DEBUG_EXCH, exch, GET_DIST_LCPU, GET_DIST_TCPUS, GET_DIST_TCPUS_ADDR, i, j, k, m, n, NULL, rbuf, rmax, sbuf, smax, vcounts, vrbuf, vrmax, and vsbuf.
Variable Documentation
_1
int _1 = 1 static
Definition at line 15 of file exch.c.
Referenced by __fort_exchange_counts().
exch
chdr* exch[16] = {NULL} static
Definition at line 16 of file exch.c.
Referenced by __fort_exchange_counts().
rbuf
int* rbuf static
Definition at line 17 of file exch.c.
Referenced by __fort_exchange_counts().
rmax
int rmax static
Definition at line 18 of file exch.c.
Referenced by __fort_exchange_counts().
sbuf
int * sbuf static
Definition at line 17 of file exch.c.
Referenced by __fort_exchange_counts().
smax
int smax static
Definition at line 18 of file exch.c.
Referenced by __fort_exchange_counts(), fix_symbol(), and process_params().
vcounts
int * vcounts static
Definition at line 17 of file exch.c.
Referenced by __fort_exchange_counts().
vrbuf
int * vrbuf static
Definition at line 17 of file exch.c.
Referenced by __fort_exchange_counts().
vrmax
int vrmax static
Definition at line 18 of file exch.c.
Referenced by __fort_exchange_counts().
vsbuf
int * vsbuf static
Definition at line 17 of file exch.c.
Referenced by __fort_exchange_counts().