flang: exit3f.c File Reference
exit3f.c File Reference
#include "ent3f.h"
#include "enames.h"
Functions
void __fort_exit (int)
void ENT3F (EXIT, exit)
Function Documentation
__fort_exit()
void __fort_exit (int s)
Definition at line 344 of file initpar.c.
References s.
Referenced by _f90io_stop(), ENTCRF90(), and ENTF90().
ENT3F()
void ENT3F (EXIT , exit)
Definition at line 16 of file exit3f.c.
References Ftn_exit, and s.