flang: exp_rte.cpp File Reference
exp_rte.cpp File Reference
Fortran expander routines.
#include "exp_rte.h"
#include "error.h"
#include "llassem.h"
#include "ll_ftn.h"
#include "outliner.h"
#include "cgmain.h"
#include "expatomics.h"
#include "exputil.h"
#include "regutil.h"
#include "machreg.h"
#include "exp_ftn.h"
#include "expsmp.h"
#include "expreg.h"
#include "semutil0.h"
#include "ilm.h"
#include "ilmtp.h"
#include "ili.h"
#include "expand.h"
#include "machar.h"
#include "mach.h"
#include "rtlRtns.h"
#include "dtypeutl.h"
#include "upper.h"
#include "symfun.h"
Classes
struct finfo_t
struct arg_info
struct garg_info
struct ainfo_t
Macros
#define EXPANDER_DECLARE_INTERNAL
#define CLASS_NONE 0
#define CLASS_INT4 4
#define CLASS_INT8 8
#define CLASS_MEM 13
#define MAX_PASS_STRUCT_SIZE 16
#define mk_prototype mk_prototype_llvm
#define IS_INTERNAL_PROC_CALL(opc)
#define convertSPTR(X) X
#define sptr_mk_address mk_address
#define NME_STR1 NME_VOL
#define IILM_OPC(i) ilmb.ilm_base[i]
#define IILM_OPND(i, j) ilmb.ilm_base[i + j]
#define FUNCPTR_BINDC 0x1
#define IILM_DTyOPND IILM_OPND
#define SMOVE_CHUNK 8
#define TEST_BOUND 96
#define START_AT 0 /* loop for skip size == 8, 4, 2, 1 */
#define STR_MOVE_THRESH 16
#define ILM_OPC(i) ilmb.ilm_base[i]
#define ILM_OPND(i, n) ilmb.ilm_base[i + n]
#define ILM_SymOPND ILM_OPND
Functions
static int exp_strx (int, STRDESC *, STRDESC *)
static int exp_strcpy (STRDESC *, STRDESC *)
static bool strovlp (STRDESC *lhs, STRDESC *rhs)
Determine if it's possible that the lhs & rhs of a string/character assignment can overlap.
static STRDESC * getstr (int)
static STRDESC * getstrconst (const char *, int)
static STRDESC * storechartmp (STRDESC *str, int mxlenili, int clenili)
static char * getcharconst (STRDESC *)
static int ftn_strcmp (char *, char *, int, int)
static int getstrlen64 (STRDESC *)
static void pp_entries (void)
static void pp_entries_mixedstrlen (void)
static void pp_params (SPTR func)
static void pp_params_mixedstrlen (int)
static void cp_memarg (int sym, INT off, int dtype)
Copy an argument from the memory area to the local area; this routine is only called from pp_params (the arg needs to be copied).
static void cp_byval_mem_arg (SPTR argsptr)
static SPTR allochartmp (int lenili)
static int block_str_move (STRDESC *, STRDESC *)
static int getchartmp (int ili)
static void _exp_smove (int, int, int, int, DTYPE)
static int check_desc (int, int)
static void check_desc_args (int)
static int exp_type_bound_proc_call (int arg, SPTR descno, int vtoff, int arglnk)
static bool is_asn_closure_call (int sptr)
static bool is_proc_desc_arg (int ili)
static bool process_end_of_list (SPTR func, SPTR osym, int *nlens, DTYPE argdtype)
static int get_chain_pointer_closure (SPTR sdsc)
get the chain pointer argument from a descriptor.
static int add_last_arg (int arglnk, int displnk)
static int add_arglnk_closure (SPTR sdsc)
static int add_gargl_closure (SPTR sdsc)
static bool strislen1 (STRDESC *str)
static bool strislen0 (STRDESC *str)
static int getstraddr (STRDESC *str)
static int getstrlen (STRDESC *str)
static void gsmove_chk_block (int ili)
Create & add an ILT for an ILI when transforming GSMOVE ILI.
int is_passbyval_dummy (int sptr)
...
int needlen (int sym, int func)
...
static void create_llvm_display_temp (void)
void exp_header (SPTR sym)
...
SPTR getdumlen (void)
...
SPTR gethost_dumlen (int arg, ISZ_T address)
bool func_has_char_args (SPTR func)
Checks to see if a procedure has character dummy arguments.
static INLINE int check_struct (DTYPE dtype)
static int check_return (DTYPE retdtype)
static INLINE void align_struct_tmp (int sptr)
bool bindC_function_return_struct_in_registers (int func_sym)
Does the bind(c) function return the struct in register(s)?
static void handle_bindC_func_ret (int func, finfo_t *pf)
static void ldst_size (DTYPE dtype, ILI_OP *ldo, ILI_OP *sto, int *siz)
int exp_alloca (ILM *ilmp)
...
static void gen_funcret (finfo_t *)
void exp_end (ILM *ilmp, int curilm, bool is_func)
...
static void gen_bindC_retval (finfo_t *fp)
static void genswitch (INT, INT)
void exp_cgoto (ILM *ilmp, int curilm)
expand a computed go to
void exp_build_agoto (int *tab, int mx)
...
void exp_agoto (ILM *ilmp, int curilm)
Expand a goto.
static void from_addr_and_length (STRDESC *s, ainfo_t *ainfo_ptr)
static void arg_ir (int, ainfo_t *)
static void arg_kr (int, ainfo_t *)
static void arg_ar (int, ainfo_t *, int)
static void arg_sp (int, ainfo_t *)
static void arg_dp (int, ainfo_t *)
static void arg_charlen (int, ainfo_t *)
static void arg_length (STRDESC *, ainfo_t *)
static void init_ainfo (ainfo_t *ap)
static void end_ainfo (ainfo_t *ap)
void init_arg_ili (int n)
...
void end_arg_ili (void)
...
static void add_to_args (int type, int argili)
static void add_struct_byval_to_args (int type, int argili, int dtype)
void add_arg_ili (int ilix, int nme, int dtype)
...
static void put_arg_ili (int i, ainfo_t *ainfo)
static void process_desc_args (ainfo_t *ainfo)
int gen_arg_ili (void)
...
static void pass_char_arg (int type, int argili, int lenili)
static int struct_ret_tmp (int ilmx)
static int check_cstruct_return (DTYPE retdtype)
static void cmplx_to_mem (int real, int imag, DTYPE dtype, int *addr, int *nme)
void exp_call (ILM_OP opc, ILM *ilmp, int curilm)
...
void exp_qjsr (const char *ext, DTYPE res_dtype, ILM *ilmp, int curilm)
...
void exp_zqjsr (char *ext, DTYPE res_dtype, ILM *ilmp, int curilm)
void expand_smove (int destilm, int srcilm, DTYPE dtype)
...
void exp_remove_gsmove (void)
Transform the GSMOVE ILI created by expand_smove()
void exp_szero (ILM *ilmp, int curilm, int to, int from, int dtype)
...
void exp_fstring (ILM_OP opc, ILM *ilmp, int curilm)
...
static int _fstrcmp (char *a1, char *a2, int len)
int charlen (SPTR sym)
return ili for character length of passed length dummy.
int charaddr (SPTR sym)
Return ili for character addr of passed length dummy.
void chk_terminal_func (int entbih, int exitbih)
...
void exp_reset_argregs (int ir, int fr)
...
void AssignAddresses (void)
Process referenced symbols, assigning them locations.
Variables
static SPTR exp_call_sym
static SPTR fptr_iface
static SPTR allocharhdr
static int * parg
static finfo_t * pfinfo
static int nentries
static int smove_flag
static int mscall_flag
static int alloca_flag
static int retgrp_cnt
static SPTR retgrp_var
static SPTR memarg_var
static void(* p_chk_block)(int) = chk_block
static int gsmove_ilt
static SWEL * sw_array
static int sw_temp
static int sw_val
static int agotostart
static arg_info * arg_ili
static int arg_entry
static int charargs
static int * len_ili
static garg_info * garg_ili
Detailed Description
Fortran expander routines.
For processing ILMs dealing with the run-time environment, e.g., expanding calls, expanding entries, and handling structure assignments.
Definition in file exp_rte.cpp.
Macro Definition Documentation
CLASS_INT4
#define CLASS_INT4 4
Definition at line 81 of file exp_rte.cpp.
CLASS_INT8
#define CLASS_INT8 8
Definition at line 82 of file exp_rte.cpp.
CLASS_MEM
#define CLASS_MEM 13
Definition at line 83 of file exp_rte.cpp.
CLASS_NONE
#define CLASS_NONE 0
Definition at line 80 of file exp_rte.cpp.
convertSPTR
#define convertSPTR (X) X
Definition at line 151 of file exp_rte.cpp.
EXPANDER_DECLARE_INTERNAL
#define EXPANDER_DECLARE_INTERNAL
Definition at line 34 of file exp_rte.cpp.
FUNCPTR_BINDC
#define FUNCPTR_BINDC 0x1
Definition at line 3008 of file exp_rte.cpp.
IILM_DTyOPND
#define IILM_DTyOPND IILM_OPND
Definition at line 3014 of file exp_rte.cpp.
IILM_OPC
#define IILM_OPC (i) ilmb.ilm_base[i]
Definition at line 3006 of file exp_rte.cpp.
IILM_OPND
#define IILM_OPND (i, j) ilmb.ilm_base[i + j]
Definition at line 3007 of file exp_rte.cpp.
ILM_OPC
#define ILM_OPC (i) ilmb.ilm_base[i]
Definition at line 6068 of file exp_rte.cpp.
ILM_OPND
#define ILM_OPND (i, n) ilmb.ilm_base[i + n]
Definition at line 6069 of file exp_rte.cpp.
ILM_SymOPND
#define ILM_SymOPND ILM_OPND
Definition at line 6075 of file exp_rte.cpp.
IS_INTERNAL_PROC_CALL
#define IS_INTERNAL_PROC_CALL (opc)
Value:
  (opc == IM_PCALLA || opc == IM_PCHFUNCA || opc == IM_PNCHFUNCA || \
   opc == IM_PKFUNCA || opc == IM_PLFUNCA || opc == IM_PIFUNCA ||   \
   opc == IM_PRFUNCA || opc == IM_PDFUNCA || opc == IM_PCFUNCA ||   \
   opc == IM_PCDFUNCA || opc == IM_PPFUNCA)
Definition at line 97 of file exp_rte.cpp.
MAX_PASS_STRUCT_SIZE
#define MAX_PASS_STRUCT_SIZE 16
Definition at line 85 of file exp_rte.cpp.
mk_prototype
#define mk_prototype mk_prototype_llvm
Definition at line 87 of file exp_rte.cpp.
NME_STR1
#define NME_STR1 NME_VOL
Definition at line 1974 of file exp_rte.cpp.
SMOVE_CHUNK
#define SMOVE_CHUNK 8
sptr_mk_address
#define sptr_mk_address mk_address
Definition at line 152 of file exp_rte.cpp.
START_AT
#define START_AT 0 /* loop for skip size == 8, 4, 2, 1 */
STR_MOVE_THRESH
#define STR_MOVE_THRESH 16
TEST_BOUND
#define TEST_BOUND 96
Function Documentation
_exp_smove()
static void _exp_smove (int dest_nme, int src_nme, int dest_addr, int src_addr, DTYPE dtype) static
Definition at line 4953 of file exp_rte.cpp.
References ad1ili(), ad3ili(), ad4ili(), ad5ili(), ad_aconi(), chk_block(), i, IL_AADD, info, ISZ_T, MSZ_I8, MSZ_UBYTE, MSZ_UHWORD, MSZ_WORD, n, offset, p_chk_block, size_of(), skip, SMOVE_CHUNK, smove_flag, START_AT, TEST_BOUND, and XBIT.
Referenced by exp_call(), exp_remove_gsmove(), and expand_smove().
_fstrcmp()
static int _fstrcmp (char * a1, char * a2, int len) static
Definition at line 5680 of file exp_rte.cpp.
References len.
Referenced by ftn_strcmp().
add_arg_ili()
void add_arg_ili (int ilix, int nme, int dtype)
...
Definition at line 2874 of file exp_rte.cpp.
References add_to_args(), ERR_Severe, IL_RES, ILI_OPC, ILIA_AR, ILIA_CD, ILIA_CS, ILIA_DP, ILIA_IR, ILIA_KR, ILIA_QP, ILIA_SP, and interr().
Referenced by exp_call().
add_arglnk_closure()
static int add_arglnk_closure (SPTR sdsc) static
Definition at line 3212 of file exp_rte.cpp.
References ad1ili(), ad3ili(), get_chain_pointer_closure(), and i.
Referenced by exp_call().
add_gargl_closure()
static int add_gargl_closure (SPTR sdsc) static
Definition at line 3222 of file exp_rte.cpp.
References ad1ili(), ad4ili(), get_chain_pointer_closure(), i, and NME_VOL.
Referenced by exp_call().
add_last_arg()
static int add_last_arg (int arglnk, int displnk) static
Definition at line 3195 of file exp_rte.cpp.
References i, ILI_OPC, and ILI_OPND.
Referenced by exp_call().
add_struct_byval_to_args()
static void add_struct_byval_to_args (int type, int argili, int dtype) static
Definition at line 2866 of file exp_rte.cpp.
References add_to_args(), arg_entry, arg_ili, arg_info::dtype, and type.
Referenced by exp_call().
add_to_args()
static void add_to_args (int type, int argili) static
Definition at line 2858 of file exp_rte.cpp.
References arg_entry, arg_ili, arg_info::ili_arg, arg_info::ili_type, and type.
Referenced by add_arg_ili(), add_struct_byval_to_args(), exp_call(), and pass_char_arg().
align_struct_tmp()
static INLINE void align_struct_tmp (int sptr) static
Definition at line 1363 of file exp_rte.cpp.
References alignment(), DTY, ERR_Severe, interr(), PDALNG, PDALNP, and sptr.
Referenced by handle_bindC_func_ret().
allochartmp()
static SPTR allochartmp (int lenili) static
Parameters
lenili length ili
Definition at line 5772 of file exp_rte.cpp.
References ad2ili(), ad3ili(), ad_acon(), addnme(), allocharhdr, arg_ar(), arg_ir(), ILTB::callfg, CHARLEN_64BIT, EXP::chartmps, chk_block(), end_ainfo(), expb, frte_func(), getccsym(), ili, iltb, init_ainfo(), ainfo_t::lnk, mkfunc(), mkRteRtnNm(), NT_VAR, RTE_str_malloc, and RTE_str_malloc_klen.
Referenced by getchartmp(), and storechartmp().
arg_ar()
static void arg_ar (int ilix, ainfo_t * ap, int dtype) static
Definition at line 4840 of file exp_rte.cpp.
References ad3ili(), and ainfo_t::lnk.
Referenced by allochartmp(), exp_qjsr(), exp_strcpy(), exp_zqjsr(), from_addr_and_length(), and put_arg_ili().
arg_charlen()
static void arg_charlen (int ilix, ainfo_t * ap) static
Definition at line 4865 of file exp_rte.cpp.
References arg_ir(), arg_kr(), IL_RES, ILI_OPC, and ILIA_KR.
Referenced by gen_arg_ili().
arg_dp()
static void arg_dp (int ilix, ainfo_t * ap) static
Definition at line 4852 of file exp_rte.cpp.
References ad2ili(), and ainfo_t::lnk.
Referenced by exp_qjsr(), exp_zqjsr(), and put_arg_ili().
arg_ir()
static void arg_ir (int ilix, ainfo_t * ap) static
Definition at line 4826 of file exp_rte.cpp.
References ad2ili(), ainfo_t::lnk, and sel_iconv().
Referenced by allochartmp(), arg_charlen(), arg_length(), exp_qjsr(), exp_strcpy(), exp_zqjsr(), and put_arg_ili().
arg_kr()
static void arg_kr (int ilix, ainfo_t * ap) static
Definition at line 4833 of file exp_rte.cpp.
References ad2ili(), ainfo_t::lnk, and sel_iconv().
Referenced by arg_charlen(), arg_length(), exp_qjsr(), exp_zqjsr(), and put_arg_ili().
arg_length()
static void arg_length (STRDESC * str, ainfo_t * ap) static
Definition at line 4874 of file exp_rte.cpp.
References arg_ir(), arg_kr(), getstrlen(), getstrlen64(), str, and XBIT.
Referenced by exp_strcpy(), and from_addr_and_length().
arg_sp()
static void arg_sp (int ilix, ainfo_t * ap) static
Definition at line 4846 of file exp_rte.cpp.
References ad2ili(), and ainfo_t::lnk.
Referenced by exp_qjsr(), exp_zqjsr(), and put_arg_ili().
AssignAddresses()
void AssignAddresses (void)
Process referenced symbols, assigning them locations.
Definition at line 6079 of file exp_rte.cpp.
References ILM_OPC, ILM_OPND, ILM_SymOPND, ilms, IM_OPRFLAG, IM_VAR, len, OPR_SYM, ILMINFO::oprs, rdilms(), reset_global_ilm_position(), SC_AUTO, sptr, SPTR_NULL, stb, and sym_is_refd().
Referenced by process_input().
bindC_function_return_struct_in_registers()
bool bindC_function_return_struct_in_registers (int func_sym)
Does the bind(c) function return the struct in register(s)?
...
Parameters
func_sym the function's symbol
Definition at line 1400 of file exp_rte.cpp.
References check_return(), CLASS_MEM, and DEBUG_ASSERT.
Referenced by gen_return_operand(), and store_for_homing().
block_str_move()
static int block_str_move (STRDESC * str1, STRDESC * str2) static
Definition at line 5521 of file exp_rte.cpp.
References ad3ili(), ad4ili(), ad_aconi(), ad_icon, ad_kcon(), chk_block(), getstraddr(), IL_AADD, ISZ_T, len, _str::lval, MSZ_BYTE, MSZ_I8, MSZ_UHWORD, MSZ_WORD, NME_STR1, and off.
Referenced by exp_strcpy().
charaddr()
int charaddr (SPTR sym)
Return ili for character addr of passed length dummy.
...
Definition at line 5976 of file exp_rte.cpp.
References ad2ili(), addnme(), addr, assert, ERR_Severe, gbl, mk_address(), mk_argasym(), and NT_VAR.
Referenced by create_ref().
charlen()
int charlen (SPTR sym)
return ili for character length of passed length dummy.
...
Definition at line 5952 of file exp_rte.cpp.
References ad3ili(), addnme(), addr, gbl, mk_address(), mk_charlen_address(), mk_charlen_parref_sptr(), MSZ_I8, MSZ_WORD, and NT_VAR.
Referenced by compute_sdsc_subscr(), create_array_subscr(), create_ref(), create_sdsc_subscr(), exp_smp(), inlarr(), and lower_data_stmts().
check_cstruct_return()
static int check_cstruct_return (DTYPE retdtype) static
Definition at line 3037 of file exp_rte.cpp.
References DTY, MAX_PASS_STRUCT_SIZE, size, and size_of().
Referenced by exp_call().
check_desc()
static int check_desc (int func, int sptr) static
Definition at line 1219 of file exp_rte.cpp.
References assert, aux, AUX::dpdsc_base, ERR_Fatal, FREE, func, i, j, nargs, NEW, pos, and sptr.
Referenced by check_desc_args().
check_desc_args()
static void check_desc_args (int func) static
Definition at line 1294 of file exp_rte.cpp.
References aux, check_desc(), AUX::dpdsc_base, func, i, and nargs.
Referenced by pp_params(), and pp_params_mixedstrlen().
check_return()
static int check_return (DTYPE retdtype) static
Definition at line 1352 of file exp_rte.cpp.
References check_struct(), CLASS_INT4, CLASS_INT8, DT_ISCMPLX, and DTY.
Referenced by bindC_function_return_struct_in_registers(), and handle_bindC_func_ret().
check_struct()
static INLINE int check_struct (DTYPE dtype) static
Definition at line 1344 of file exp_rte.cpp.
References CLASS_INT4, CLASS_MEM, and ll_check_struct_return().
Referenced by check_return().
chk_terminal_func()
void chk_terminal_func (int entbih, int exitbih)
...
Parameters
entbih bih of the entry block
exitbih bih of the exit block
Check if this function is a terminal routine (one that does not call any other routines). If so, the necessary changes will be made to the entry and exit blocks. This optimization depends on the target machine and its execution environment. It is appropriate when the target does not have instructions to manipulate the stack; multiple instructions have to be generated to allocate stack space, manipulate the frame and stack pointers, and to check for overflow and underflow.
When the terminal function optimization is appropriate, the following applies:
exceptions and global registers are not used: a. if the routine is terminal, static space is used in lieu of the stack. ILIs QENTRY and QEXIT are used. b. otherwise, faster entry and exit routines, c_i_qentry and c_i_qexit, are used. The ENTRY ili is modified to locate c_i_qentry, and a new EXIT ili locating c_i_qexit is generated.
otherwise, the ENTRY and EXIT ILIs are left as is.
When the terminal function optimization is not appropriate, the following applies:
if exceptions and global registers are not used, the faster entry and exit routines, c_i_qentry and c_i_qexit, are used. The ILIs QENTRY and QEXIT are used.
otherwise, the ENTRY and EXIT ILIs are left as is.
The -q 0 256 switch forces full entry and exit to be used. The -q 0 4096 switch forces QENTRY and QEXIT to be used for all routines.
Definition at line 6031 of file exp_rte.cpp.
References ENTRY::auto_array, aux, and AUX::curr_entry.
Referenced by exp_end().
cmplx_to_mem()
static void cmplx_to_mem (int real, int imag, DTYPE dtype, int * addr, int * nme) static
Definition at line 3050 of file exp_rte.cpp.
References ACONOFFG, ad3ili(), ad4ili(), ad_acon(), ad_aconi(), addnme(), addr, assert, chk_block(), DT_CMPLX, DT_ISCMPLX, DTY, ERR_Severe, expb, IL_AADD, ILI_OPC, ILI_OPND, load, loc_of(), mkrtemp_cpx_sc(), msz, MSZ_F16, MSZ_F4, MSZ_F8, NME_NM, NOSYM, NT_MEM, NT_VAR, EXP::sc, size, size_of(), SPTR_NULL, tmp, TY_CMPLX, and XBIT.
Referenced by exp_call().
cp_byval_mem_arg()
static void cp_byval_mem_arg (SPTR argsptr) static
Definition at line 1981 of file exp_rte.cpp.
References ad3ili(), ad4ili(), ad_acon(), addnme(), addr, chk_block(), DT_CMPLX, DT_DCMPLX, DTY, gbl, get_byval_local(), ldst_size(), NME_STR1, NOSYM, NT_MEM, NT_VAR, size_of(), SPTR_NULL, sym_is_refd(), sz, and val.
Referenced by pp_params(), and pp_params_mixedstrlen().
cp_memarg()
static void cp_memarg (int sym, INT off, int dtype) static
Copy an argument from the memory area to the local area; this routine is only called from pp_params (the arg needs to be copied).
Definition at line 2041 of file exp_rte.cpp.
References arg_is_refd(), DT_INT, ERR_Severe, EXPDBG, gbl, interr(), mk_argasym(), off, and SYMNAME.
Referenced by pp_params(), and pp_params_mixedstrlen().
create_llvm_display_temp()
static void create_llvm_display_temp (void) static
Definition at line 277 of file exp_rte.cpp.
References aux, AUX::curr_entry, ENTRY::display, DTY, expb, gbl, EXP::gentmps, getccsym(), load_uplevel_addresses(), make_uplevel_arg_struct(), mk_argasym(), and sym_is_refd().
Referenced by exp_header().
end_ainfo()
static void end_ainfo (ainfo_t * ap) static
Definition at line 2822 of file exp_rte.cpp.
Referenced by allochartmp(), exp_qjsr(), exp_strcpy(), exp_zqjsr(), and gen_arg_ili().
end_arg_ili()
void end_arg_ili (void)
...
Definition at line 2848 of file exp_rte.cpp.
References arg_ili, FREE, garg_ili, len_ili, and XBIT.
Referenced by exp_call().
exp_agoto()
void exp_agoto (ILM * ilmp, int curilm)
Expand a goto.
...
for TARGET_LLVM, we are not performing an indirect branch, so expand an assigned goto into a computed goto – the labels appearing in the ASSIGN statements and their respective computed goto index values have already been collected into a switch_base table whose starting index is agotostart.
Definition at line 2738 of file exp_rte.cpp.
References agotostart, assert, SWEL::clabel, FLG::dbg, ERR_Severe, exp_label(), flg, gbl, genswitch(), getlab(), i, ILI_OF, ILM_OPND, kimove(), n, RFCNTI, sw_array, sw_temp, sw_val, switch_base, and SWEL::val.
Referenced by exp_bran().
exp_alloca()
int exp_alloca (ILM * ilmp)
...
sptr = ILM_OPND(ilmp, 3); sym and currently ignored
tmp = ILM_OPND(ilmp, 4); stc and currently ignored
runtime adjusts the size
Definition at line 2074 of file exp_rte.cpp.
References ad1ili(), ad2ili(), ad_kcon(), ad_kconi(), alloca_flag, AR_RETVAL, ikmove(), ILI_OF, ILM_OPND, mk_prototype, mkfunc(), void(), and XBIT.
Referenced by exp_ac().
exp_build_agoto()
void exp_build_agoto (int * tab, int mx)
...
Definition at line 2701 of file exp_rte.cpp.
References agotostart, SWEL::clabel, convertSPTR, getswel(), i, SWEL::next, RFCNTI, switch_base, and SWEL::val.
Referenced by build_agoto().
exp_call()
void exp_call (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 3264 of file exp_rte.cpp.
References _exp_smove(), ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_acon(), ad_aconi(), ad_icon, add_arg_ili(), add_arglnk_closure(), add_gargl_closure(), add_last_arg(), add_struct_byval_to_args(), add_to_args(), addnme(), addr, AR_RETVAL, aux, basenm, ILTB::callfg, cfunc, charargs, CHARLEN_64BIT, check_cstruct_return(), chk_block(), cmplx_to_mem(), CMPLXFUNC_C, AUX::curr_entry, ENTRY::display, dt, DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, DT_ISBASIC, DT_REAL, DTY, DTyInterface, garg_info::dtype, DTySeqTyElement, end_arg_ili(), ERR_Severe, ERR_unused, exp_call_sym, exp_type_bound_proc_call(), expb, FLANG_FALLTHROUGH, fptr_iface, FR_RETVAL, FUNCPTR_BINDC, garg_ili, gbl, gen_arg_ili(), getstr(), getstraddr(), getstrlen(), i, IILM_DTyOPND, IILM_OPC, IILM_OPND, IL_AADD, IL_RES, ili, ILI_ALT, ILI_DTyOPND, ILI_OF, ILI_OPC, ILI_OPND, ili_opnd(), ILIA_AR, ILIA_CD, ILIA_CQ, ILIA_CS, ILIA_DP, ILIA_IR, ILIA_ISAR, ILIA_KR, ILIA_QP, ILIA_SP, garg_info::ilix, ILMB::ilm_base, ILM_CLEN, ILM_DTyOPND, ILM_IRESULT, ILM_ISCHAR, ILM_ISCMPLX, ILM_ISDCMPLX, ILM_ISQCMPLX, ILM_MXLEN, ILM_NME, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_RRESULT, ILM_SymOPND, ilmb, iltb, IM_TYPE, IMTY_CONS, IMTY_REF, init_arg_ili(), interr(), IR_RETVAL, is_asn_closure_call(), IS_INTERNAL_PROC_CALL, is_proc_desc_arg(), KR_RETVAL, len_ili, loc_of(), mk_address(), mk_argasym(), mkrtemp_cpx_sc(), mkrtemp_sc(), mkRteRtnNm(), msz, MSZ_BYTE, MSZ_F16, MSZ_F32, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_UHWORD, MSZ_WORD, nargs, _str::next, garg_info::nme, NME_OF, NME_STR1, NME_UNK, NME_VOL, NOSYM, NT_MEM, NT_VAR, optional_missing(), optional_present(), pass_char_arg(), replace_by_one(), replace_by_zero(), res, RTE_present, EXP::sc, sel_iconv(), size_of(), skip, sptr_mk_address, SPTR_NULL, storechartmp(), struct_ret_tmp(), SYMNAME, TY_CHAR, TY_NCHAR, garg_info::val_flag, and XBIT.
Referenced by eval_ilm().
exp_cgoto()
void exp_cgoto (ILM * ilmp, int curilm)
expand a computed go to
...
this processing is similiar to the processing of a switch by pgc. The exception is that the switch list is already ordered as a table in increasing order. pgc must first create a table of the switch values.
Definition at line 2505 of file exp_rte.cpp.
References ad1ili(), assert, chk_block(), SWEL::clabel, CONVAL2G, FLG::dbg, ERR_Severe, flg, gbl, genswitch(), i, ILI_OF, ILI_OPC, ILI_OPND, ILM_OPND, n, RFCNTD, sw_array, sw_temp, sw_val, switch_base, val, and SWEL::val.
Referenced by exp_bran().
exp_end()
void exp_end (ILM * ilmp, int curilm, bool is_func)
...
Definition at line 2110 of file exp_rte.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_acon(), ad_icon, addilt(), addnme(), addr, alloca_flag, allocharhdr, EXP::aret_tmp, EXP::arglist, aux, BIH_EX, BIH_LAST, BIH_NEXT, BIH_SMOVE, BIH_XT, EXP::bits, ILTB::callfg, EXP::callfg, chk_block(), chk_terminal_func(), CONVAL2G, cr_block(), EXP::curbih, EXP::curilt, AUX::curr_entry, FLG::debug, DOREG1, ENTRY::ent_save, exp_label(), exp_mp_func_prologue(), exp_restore_mxcsr(), expb, EXPDBG, ENTRY::flags, EXP::flags, flg, flsh_block(), freearea(), frte_func(), func, gbl, gen_funcret(), getlab(), FLG::ieee, ILI_OPND, ILT_PREV, iltb, IR_ARET, ld, mkfunc(), mkrtemp_end(), mkRteRtnNm(), mr_reset_frglobals(), mr_reset_numglobals(), mscall_flag, MSZ_WORD, NOSYM, NT_VAR, FLG::opt, pfinfo, FLG::profile, rdilts(), reg_assign1(), finfo_t::retgrp, retgrp_cnt, retgrp_var, EXP::retlbl, RFCNTI, RTE_str_free, RU_PROG, smove_flag, FLG::smp, SPTR_NULL, st, SYMNAME, tmp, wr_block(), wrilts(), and XBIT.
Referenced by exp_misc().
exp_fstring()
void exp_fstring (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 5057 of file exp_rte.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_icon, ad_kconi(), addr, assert, ILTB::callfg, CC_EQ, CHARLEN_64BIT, chk_block(), _str::cnt, CONVAL2G, DTY, ERR_Severe, exp_strcpy(), exp_strx(), FLANG_FALLTHROUGH, ftn_strcmp(), get_isz_cval(), getcharconst(), getchartmp(), getcon(), getstr(), getstraddr(), getstrconst(), IL_AADD, IL_IADD, IL_IMUL, IL_ISUB, IL_RES, IL_TYPE, ILI_OF, ILI_OPC, ILI_OPND, ILIA_KR, ILM_CLEN, ILM_ISCHAR, ILM_MXLEN, ILM_OPND, ILM_RESTYPE, ILM_RESULT, iltb, ILTY_CONS, interr(), _str::liscon, _str::lval, MSZ_BYTE, MSZ_UHWORD, STB::n_base, _str::next, NME_STR1, NULL, sel_iconv(), stb, storechartmp(), strislen0(), strislen1(), tmp, TY_CHAR, and val.
Referenced by eval_ilm().
exp_header()
void exp_header (SPTR sym)
...
Expand entry, main, sub, or func. For an unnamed program, PROGRAM, SUBROUTINE, or FUNCTION, sym is 0; otherwise, sym is the ENTRY name.
Definition at line 327 of file exp_rte.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad_acon(), addilt(), addnme(), alloca_flag, allocharhdr, EXP::arglcnt, aux, BIH_EN, BIH_LABEL, BIH_LINENO, bihb, chk_block(), cr_block(), create_llvm_display_temp(), EXP::curbih, EXP::curilt, AUX::curr_entry, FLG::debug, ENTRY::display, ENTRY::ent_save, expb, flg, flsh_block(), gbl, GBL_CURRFUNC, EXP::gentmps, getccsym(), ili, ll_get_hostprog_arg(), ll_get_shared_arg(), EXP::max, memarg_var, mk_address(), mk_argasym(), mkrtemp_init(), mscall_flag, EXP::next, NT_IND, NT_VAR, BIHB::parfg, pp_entries(), pp_entries_mixedstrlen(), pp_params(), pp_params_mixedstrlen(), FLG::recursive, reg_init(), RU_PROG, smove_flag, FLG::smp, SPTR_NULL, EXP::start, sym_is_refd(), BIHB::taskfg, ENTRY::uplevel, WINNT_CALL, wr_block(), and XBIT.
Referenced by begin_entry().
exp_qjsr()
void exp_qjsr (const char * ext, DTYPE res_dtype, ILM * ilmp, int curilm)
...
Parameters
ext name of routine to call
res_dtype function return type
Generate a sequence of ili for the current ilm which is an "arithmetic". This sequence essentially looks like a normal call, except where we can, arguments are passed by value.
The requirements are:
The ilm looks like an "arithmetic" ILM where there's a fixed number of operands (determined by the ilms info).
The result is returned in a temporary.
The address of the result is the first argument in the call.
The operands are fully evaluated (no reference ilms).
Character arguments are not seen.
For now this only works for complex/double complex ILMs which are QJSRs in the "standard" fortran.
Definition at line 4561 of file exp_rte.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad_acon(), ad_aconi(), addnme(), arg_ar(), arg_dp(), arg_ir(), arg_kr(), arg_sp(), ILTB::callfg, chk_block(), DT_CMPLX, DT_ISCMPLX, end_ainfo(), ERR_Severe, expb, i, IL_AADD, IL_RES, ILI_OPC, ILIA_AR, ILIA_CD, ILIA_CQ, ILIA_CS, ILIA_DP, ILIA_IR, ILIA_KR, ILIA_SP, ILMB::ilm_base, ILM_IRESULT, ILM_ISCHAR, ILM_ISCMPLX, ILM_ISDCMPLX, ILM_ISQCMPLX, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_RRESULT, ilmb, ilms, iltb, init_ainfo(), interr(), ainfo_t::lnk, mkfunc(), mkrtemp_arg1_sc(), MSZ_F16, MSZ_F32, MSZ_F4, MSZ_F8, nargs, NOSYM, NT_MEM, NT_VAR, ILMINFO::oprs, res, EXP::sc, SPTR_NULL, and XBIT.
Referenced by exp_ac().
exp_remove_gsmove()
void exp_remove_gsmove (void)
Transform the GSMOVE ILI created by expand_smove()
...
Definition at line 4917 of file exp_rte.cpp.
References _exp_smove(), BIH_NEXT, chk_block(), DBGBIT, delilt(), dump_one_block(), gbl, gsmove_chk_block(), gsmove_ilt, ILI_DTyOPND, ILI_OPC, ILI_OPND, ILT_ILIP, ILT_NEXT, ILT_PREV, NULL, p_chk_block, rdilts(), and wrilts().
Referenced by rm_smove().
exp_reset_argregs()
void exp_reset_argregs (int ir, int fr)
...
Parameters
ir number of integer regs used as arguments
fr number of floating point regs used as arguments
Perform the necessary adjustments regarding the number of argument registers used by a jsr/qsr added after the expand phase and before the optimizer (i.e., by the vectorizer). An argument to the current function must be stored in memory if it has been marked by expand as a register argument and if its register is used by the jsr/qjr. Also, the available set of arg/scratch registers that can be used as globals by the optimizer must be updated.
Definition at line 6051 of file exp_rte.cpp.
exp_strcpy()
static int exp_strcpy (STRDESC * str1, STRDESC * str2) static
Definition at line 5412 of file exp_rte.cpp.
References ad2ili(), ad_icon, arg_ar(), arg_ir(), arg_length(), b, block_str_move(), CHARLEN_64BIT, _str::cnt, _str::dtype, end_ainfo(), from_addr_and_length(), frte_func(), getcharconst(), getstraddr(), getstrconst(), init_ainfo(), ISZ_T, len, _str::liscon, ainfo_t::lnk, _str::lval, mkfunc(), mkfunc_cncall(), mkRteRtnNm(), n, RTE_nstr_copy, RTE_nstr_copy_klen, RTE_str_copy, RTE_str_copy_klen, RTE_str_cpy1, str, STR_MOVE_THRESH, strovlp(), TY_CHAR, TY_NCHAR, and XBIT.
Referenced by exp_fstring(), and storechartmp().
exp_strx()
static int exp_strx (int opc, STRDESC * str1, STRDESC * str2) static
Definition at line 5351 of file exp_rte.cpp.
References ad1ili(), ad2ili(), ad3ili(), CHARLEN_64BIT, _str::dtype, frte_func(), getstraddr(), getstrlen(), getstrlen64(), IR_RETVAL, KR_RETVAL, mkfunc(), mkRteRtnNm(), RTE_nstr_index, RTE_nstr_index_klen, RTE_nstrcmp, RTE_nstrcmp_klen, RTE_str_index, RTE_str_index_klen, RTE_strcmp, RTE_strcmp_klen, TY_NCHAR, and XBIT.
Referenced by exp_fstring().
exp_szero()
void exp_szero (ILM * ilmp, int curilm, int to, int from, int dtype)
...
Parameters
to ilm of receiving struct/union
from ilm of sending struct/union
dtype data type of struct/union
Definition at line 5037 of file exp_rte.cpp.
References ad1ili(), ad2ili(), ad3ili(), addr, chk_block(), ILI_OF, loc_of(), mkfunc(), NME_OF, and tmp.
Referenced by exp_store().
exp_type_bound_proc_call()
static int exp_type_bound_proc_call (int arg, SPTR descno, int vtoff, int arglnk) static
Definition at line 1130 of file exp_rte.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_aconi(), addnme(), addr, arg, chk_block(), expb, fptr_iface, gbl, EXP::gentmps, get_acon(), getccsym_sc(), IL_AADD, ili, mk_address(), mk_argasym(), MSZ_I8, NME_UNK, NT_VAR, sz, tmp, and XBIT.
Referenced by exp_call().
exp_zqjsr()
void exp_zqjsr (char * ext, DTYPE res_dtype, ILM * ilmp, int curilm)
Parameters
ext name of routine to call
res_dtype function return type
Same as exp_qjsr() except that if the result is complex, its pointer argument is passed as the last argument instead of the first argument. This is necessary to keep double arguments properly aligned on the stack.
For now this only works for complex/double complex ILMs which are QJSRs in the "standard" fortran.
Definition at line 4710 of file exp_rte.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad_acon(), ad_aconi(), addnme(), arg_ar(), arg_dp(), arg_ir(), arg_kr(), arg_sp(), ILTB::callfg, chk_block(), DT_CMPLX, DT_ISCMPLX, end_ainfo(), ERR_Severe, expb, i, IL_AADD, IL_RES, ILI_OPC, ILIA_AR, ILIA_CD, ILIA_CS, ILIA_DP, ILIA_IR, ILIA_KR, ILIA_SP, ILMB::ilm_base, ILM_IRESULT, ILM_ISCHAR, ILM_ISCMPLX, ILM_ISDCMPLX, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_RRESULT, ilmb, ilms, iltb, init_ainfo(), interr(), ainfo_t::lnk, mkfunc(), mkrtemp_cpx_sc(), MSZ_F16, MSZ_F4, MSZ_F8, nargs, NOSYM, NT_MEM, NT_VAR, ILMINFO::oprs, res, EXP::sc, SPTR_NULL, and XBIT.
expand_smove()
void expand_smove (int destilm, int srcilm, DTYPE dtype)
...
Expand an smove ILM.
Parameters
destilm ilm of receiving struct/union
srcilm ilm of sending struct/union
dtype data type of struct/union
Definition at line 4890 of file exp_rte.cpp.
References _exp_smove(), ad5ili(), chk_block(), flg, ILI_OF, loc_of(), NME_OF, FLG::opt, and USE_GSMOVE.
Referenced by exp_store().
from_addr_and_length()
static void from_addr_and_length (STRDESC * s, ainfo_t * ainfo_ptr) static
Definition at line 5403 of file exp_rte.cpp.
References arg_ar(), arg_length(), from_addr_and_length(), getstraddr(), and s.
Referenced by exp_strcpy(), and from_addr_and_length().
ftn_strcmp()
static int ftn_strcmp (char * a1, char * a2, int a1_len, int a2_len) static
Definition at line 5696 of file exp_rte.cpp.
References _fstrcmp().
Referenced by exp_fstring().
func_has_char_args()
bool func_has_char_args (SPTR func)
Checks to see if a procedure has character dummy arguments.
Parameters
func is the procedure we are checking.
Returns
true if the procedure has character dummy arguments, else false.
Definition at line 1325 of file exp_rte.cpp.
References aux, convertSPTR, AUX::dpdsc_base, DTYG, func, i, nargs, TY_CHAR, and TY_NCHAR.
Referenced by ll_process_routine_parameters(), print_entry_subroutine(), and process_end_of_list().
gen_arg_ili()
int gen_arg_ili (void)
...
Definition at line 2953 of file exp_rte.cpp.
References arg_charlen(), arg_entry, arg_ili, charargs, end_ainfo(), exp_call_sym, i, ili, arg_info::ili_arg, init_ainfo(), is_proc_desc_arg(), len_ili, ainfo_t::lnk, process_desc_args(), and put_arg_ili().
Referenced by exp_call().
gen_bindC_retval()
static void gen_bindC_retval (finfo_t * fp) static
Definition at line 2342 of file exp_rte.cpp.
References ad2ili(), ad3ili(), ad4ili(), ad_acon(), addnme(), chk_block(), ERR_Severe, EXPDBG, fp, gbl, IL_RES, ILI_OPC, ILIA_AR, ILIA_DP, ILIA_IR, ILIA_KR, ILIA_SP, interr(), MSZ_F4, MSZ_F8, NT_VAR, RES_IR, and RES_XR.
Referenced by gen_funcret().
gen_funcret()
static void gen_funcret (finfo_t * fp) static
Definition at line 2407 of file exp_rte.cpp.
References ad2ili(), ad3ili(), ad_acon(), addnme(), addr, chk_block(), CMPLXFUNC_C, DTY, ERR_Severe, fp, FR_RETVAL, gbl, gen_bindC_retval(), ILI_ALT, interr(), IR_RETVAL, KR_RETVAL, MSZ_F16, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_SBYTE, MSZ_SHWORD, MSZ_WORD, NT_VAR, RES_IR, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_ISCMPLX, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and XBIT.
Referenced by exp_end().
genswitch()
static void genswitch (INT lb, INT ub) static
Parameters
lb lower bound of switch array
ub upper bound of switch array
Definition at line 2553 of file exp_rte.cpp.
References ad1ili(), ad3ili(), ad4ili(), ad_acon(), ad_icon, addnme(), chk_block(), EXP::curilt, FLG::dbg, exp_label(), expb, first, flg, gbl, genswitch(), getlab(), i, ILT_ILIP, label, lb, m, mk_swtab(), mkrtemp_sc(), MSZ_WORD, next, SWEL::next, NT_VAR, FLG::opt, RFCNTD, RFCNTI, EXP::sc, sw_array, sw_temp, sw_val, ub, val, SWEL::val, and wr_block().
Referenced by exp_agoto(), exp_cgoto(), and genswitch().
get_chain_pointer_closure()
static int get_chain_pointer_closure (SPTR sdsc) static
get the chain pointer argument from a descriptor.
Parameters
arglnk is a chain of argument ILI for a call-site.
sdsc is the descriptor that has the chain pointer.
Returns
an IL_LDA ili chain that contains the ILI that loads the chain pointer from the descriptor.
In LLVM, pointer descriptor is not visible in the outlined func. Use mk_address() which fetches the uplevel ref
Definition at line 3159 of file exp_rte.cpp.
References ad2ili(), ad3ili(), ad_acon(), ad_aconi(), addnme(), addr, cp, IL_AADD, ili, mk_address(), mk_argasym(), NT_VAR, and XBIT.
Referenced by add_arglnk_closure(), and add_gargl_closure().
getcharconst()
static char * getcharconst (STRDESC * str) static
Definition at line 5655 of file exp_rte.cpp.
References CONVAL2G, STB::n_base, NULL, p, stb, and str.
Referenced by exp_fstring(), and exp_strcpy().
getchartmp()
static int getchartmp (int ili) static
Parameters
ili max size ili
Definition at line 5754 of file exp_rte.cpp.
References allochartmp(), EXP::chartmps, CONVAL2G, expb, get_type(), getccsym(), IL_TYPE, ili, ILI_OPC, ILI_OPND, ILTY_CONS, EXP::sc, and TY_CHAR.
Referenced by exp_fstring(), and storechartmp().
getdumlen()
SPTR getdumlen (void)
...
Definition at line 1097 of file exp_rte.cpp.
References EXP::chardtmps, CHARLEN_64BIT, DT_INT, expb, and getccsym().
Referenced by _fixup_llvm_uplevel_symbol(), ll_process_routine_parameters(), pp_entries(), pp_entries_mixedstrlen(), print_entry_subroutine(), stb_process_iface_chlen(), and upper().
gethost_dumlen()
SPTR gethost_dumlen (int arg, ISZ_T address)
Create a symbol representing the length of a passed-length character argument in the host subprogram.
Definition at line 1112 of file exp_rte.cpp.
References arg, CHARLEN_64BIT, DT_INT, getccsym(), and pop_sym().
Referenced by _fixup_llvm_uplevel_symbol(), and restore_saved_syminfo().
getstr()
static STRDESC * getstr (int ilm) static
Definition at line 5819 of file exp_rte.cpp.
References _str::aisvar, _str::aval, _str::cnt, CONVAL2G, DTY, _str::dtype, DTySeqTyElement, getitem(), getrval(), getstr(), IL_TYPE, ILI_OPC, ILI_OPND, ILMB::ilm_base, ILM_CLEN, ILM_OPC, ILM_OPND, ILM_RESULT, ilmb, ILTY_CONS, _str::liscon, _str::lval, _str::next, STR_AREA, TY_CHAR, and TY_NCHAR.
Referenced by exp_call(), exp_fstring(), and getstr().
getstraddr()
static int getstraddr (STRDESC * str) static
Definition at line 168 of file exp_rte.cpp.
References ad1ili(), and str.
Referenced by block_str_move(), exp_call(), exp_fstring(), exp_strcpy(), exp_strx(), from_addr_and_length(), and storechartmp().
getstrconst()
static STRDESC * getstrconst (const char * str, int len) static
Definition at line 5876 of file exp_rte.cpp.
References _str::aisvar, _str::aval, _str::cnt, _str::dtype, get_acon(), getitem(), getstring(), len, _str::liscon, _str::lval, _str::next, str, STR_AREA, and TY_CHAR.
Referenced by exp_fstring(), and exp_strcpy().
getstrlen()
static int getstrlen (STRDESC * str) static
Definition at line 176 of file exp_rte.cpp.
References ad_icon, and str.
Referenced by arg_length(), exp_call(), exp_strx(), and getstrlen64().
getstrlen64()
static int getstrlen64 (STRDESC * str) static
Definition at line 184 of file exp_rte.cpp.
References ad1ili(), getstrlen(), IL_RES, ILI_OPC, ILIA_KR, and str.
Referenced by arg_length(), and exp_strx().
gsmove_chk_block()
static void gsmove_chk_block (int ili) static
Create & add an ILT for an ILI when transforming GSMOVE ILI.
Definition at line 6059 of file exp_rte.cpp.
References addilt(), gsmove_ilt, and ili.
Referenced by exp_remove_gsmove().
handle_bindC_func_ret()
static void handle_bindC_func_ret (int func, finfo_t * pf) static
Definition at line 1407 of file exp_rte.cpp.
References align_struct_tmp(), alignment(), check_return(), CLASS_MEM, finfo_t::fval, finfo_t::ret_align, and finfo_t::ret_sm_struct.
Referenced by pp_params().
init_ainfo()
static void init_ainfo (ainfo_t * ap) static
Definition at line 2816 of file exp_rte.cpp.
References ad1ili(), and ainfo_t::lnk.
Referenced by allochartmp(), exp_qjsr(), exp_strcpy(), exp_zqjsr(), and gen_arg_ili().
init_arg_ili()
void init_arg_ili (int n)
...
Definition at line 2828 of file exp_rte.cpp.
References arg_entry, arg_ili, BZERO, charargs, garg_ili, len_ili, n, NEW, and XBIT.
Referenced by exp_call().
is_asn_closure_call()
static bool is_asn_closure_call (int sptr) static
Definition at line 3232 of file exp_rte.cpp.
References mkRteRtnNm(), NOSYM, RTE_asn_closure, sptr, and SYMNAME.
Referenced by exp_call().
is_passbyval_dummy()
int is_passbyval_dummy (int sptr)
...
Definition at line 226 of file exp_rte.cpp.
References BYVALDEFAULT, GBL_CURRFUNC, and sptr.
Referenced by sym_is_refd().
is_proc_desc_arg()
static bool is_proc_desc_arg (int ili) static
Definition at line 3242 of file exp_rte.cpp.
References IL_TYPE, ili, ILI_OPC, ILI_OPND, ILI_SymOPND, ILTY_LOAD, NME_SYM, NOSYM, SPTR_NULL, and SymConval1.
Referenced by exp_call(), gen_arg_ili(), and process_desc_args().
ldst_size()
static void ldst_size (DTYPE dtype, ILI_OP * ldo, ILI_OP * sto, int * siz) static
Definition at line 1877 of file exp_rte.cpp.
References DTY, DTyAlgTySize, MSZ_BYTE, MSZ_DFLWORD, MSZ_F16, MSZ_F4, MSZ_F8, MSZ_FWORD, MSZ_I8, MSZ_SBYTE, MSZ_SHWORD, MSZ_WORD, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_FLOAT, TY_INT, TY_INT8, TY_NCHAR, TY_QUAD, TY_SINT, and TY_SLOG.
Referenced by cp_byval_mem_arg().
needlen()
int needlen (int sym, int func)
...
Definition at line 241 of file exp_rte.cpp.
References func.
Referenced by pp_entries(), pp_entries_mixedstrlen(), pp_params_mixedstrlen(), and process_end_of_list().
pass_char_arg()
static void pass_char_arg (int type, int argili, int lenili) static
Definition at line 2985 of file exp_rte.cpp.
References ad1ili(), add_to_args(), charargs, exp_call_sym, IL_RES, ILI_OPC, ILIA_KR, len_ili, type, and XBIT.
Referenced by exp_call().
pp_entries()
static void pp_entries (void) static
Definition at line 530 of file exp_rte.cpp.
References assert, aux, BYVALDEFAULT, BZERO, CMPLXFUNC_C, curpos, DDTG, AUX::dpdsc_base, dt, DT_INT, DTY, DTYG, ERR_Severe, EXPDBG, func, finfo_t::fval, gbl, getccsym(), getdumlen(), getitem(), i, nargs, needlen(), nentries, NOSYM, parg, pfinfo, pos, finfo_t::retgrp, retgrp_cnt, retgrp_var, RU_FUNC, size_of(), SYMNAME, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT8, TY_LOG8, TY_NCHAR, TY_QUAD, and XBIT.
Referenced by exp_header().
pp_entries_mixedstrlen()
static void pp_entries_mixedstrlen (void) static
Definition at line 827 of file exp_rte.cpp.
References assert, aux, BYVALDEFAULT, BZERO, convertSPTR, curpos, AUX::curr_entry, DDTG, AUX::dpdsc_base, dt, DT_INT, DTY, ENTRY::ent_save, ERR_Severe, expb, EXPDBG, func, finfo_t::fval, gbl, EXP::gentmps, getccsym(), getdumlen(), getitem(), i, nargs, needlen(), nentries, NOSYM, parg, pfinfo, pos, finfo_t::retgrp, retgrp_cnt, retgrp_var, RU_FUNC, size_of(), SYMNAME, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT8, TY_LOG8, TY_NCHAR, TY_QUAD, WINNT_CALL, and XBIT.
Referenced by exp_header().
pp_params()
static void pp_params (SPTR func) static
Definition at line 1445 of file exp_rte.cpp.
References ad5ili(), ad_acon(), addnme(), aux, BYVALDEFAULT, EXP::charlen_dtype, check_desc_args(), chk_block(), CMPLXFUNC_C, convertSPTR, cp_byval_mem_arg(), cp_memarg(), AUX::dpdsc_base, DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_ISCMPLX, DTY, expb, EXPDBG, func, gbl, GBL_CURRFUNC, get_byval_local(), handle_bindC_func_ret(), finfo_t::mem_off, mk_argasym(), n, nargs, NME_VOL, NT_VAR, parg, pfinfo, process_end_of_list(), finfo_t::retgrp, RU_FUNC, size_of(), SYMNAME, TY_CHAR, TY_CMPLX, TY_DCMPLX, TY_NCHAR, and XBIT.
Referenced by exp_header().
pp_params_mixedstrlen()
static void pp_params_mixedstrlen (int func) static
Definition at line 1668 of file exp_rte.cpp.
References aux, BYVALDEFAULT, EXP::charlen_dtype, check_desc_args(), convertSPTR, cp_byval_mem_arg(), cp_memarg(), AUX::dpdsc_base, DT_CMPLX, DT_DBLE, DT_DCMPLX, DTY, DTYG, expb, EXPDBG, func, gbl, finfo_t::mem_off, mk_argasym(), nargs, needlen(), pfinfo, RU_FUNC, size_of(), SYMNAME, TY_CHAR, TY_CMPLX, TY_DCMPLX, TY_NCHAR, and XBIT.
Referenced by exp_header().
process_desc_args()
static void process_desc_args (ainfo_t * ainfo) static
Definition at line 2941 of file exp_rte.cpp.
References arg_entry, arg_ili, i, ili, arg_info::ili_arg, is_proc_desc_arg(), and put_arg_ili().
Referenced by gen_arg_ili().
process_end_of_list()
static bool process_end_of_list (SPTR func, SPTR osym, int * nlens, DTYPE argdtype) static
Definition at line 1426 of file exp_rte.cpp.
References DTYG, func, func_has_char_args(), needlen(), parg, TY_CHAR, and TY_NCHAR.
Referenced by pp_params().
put_arg_ili()
static void put_arg_ili (int i, ainfo_t * ainfo) static
Definition at line 2910 of file exp_rte.cpp.
References arg_ar(), arg_dp(), arg_ili, arg_ir(), arg_kr(), arg_sp(), ERR_Severe, i, and interr().
Referenced by gen_arg_ili(), and process_desc_args().
storechartmp()
static STRDESC * storechartmp (STRDESC * str, int mxlenili, int clenili) static
Definition at line 5894 of file exp_rte.cpp.
References ad2ili(), ad3ili(), ad4ili(), ad_acon(), ad_icon, addnme(), _str::aisvar, allochartmp(), _str::aval, ILTB::callfg, chk_block(), _str::cnt, CONVAL2G, _str::dtype, exp_strcpy(), getchartmp(), getcon(), getitem(), getstraddr(), IL_IMUL, IL_TYPE, ILI_OPC, ILI_OPND, iltb, ILTY_CONS, _str::liscon, _str::lval, msz, MSZ_BYTE, MSZ_UHWORD, _str::next, NME_STR1, NT_VAR, str, STR_AREA, strislen1(), TY_NCHAR, and val.
Referenced by exp_call(), and exp_fstring().
strislen0()
static bool strislen0 (STRDESC * str) static
Definition at line 162 of file exp_rte.cpp.
References str.
Referenced by exp_fstring().
strislen1()
static bool strislen1 (STRDESC * str) static
Definition at line 156 of file exp_rte.cpp.
References str.
Referenced by exp_fstring(), and storechartmp().
strovlp()
static bool strovlp (STRDESC * lhs, STRDESC * rhs) static
Determine if it's possible that the lhs & rhs of a string/character assignment can overlap.
Note that for now, an assumed-size char lhs is not a candidate since its STRDESC is not marked 'asivar'.
Definition at line 5629 of file exp_rte.cpp.
References _str::aisvar, _str::aval, lhs, _str::next, and NULL.
Referenced by exp_strcpy().
struct_ret_tmp()
static int struct_ret_tmp (int ilmx) static
Definition at line 3019 of file exp_rte.cpp.
References assert, ERR_Severe, ILMB::ilm_base, ILM_OPC, ILM_OPND, and ilmb.
Referenced by exp_call().
Variable Documentation
agotostart
int agotostart static
Definition at line 2698 of file exp_rte.cpp.
Referenced by exp_agoto(), and exp_build_agoto().
alloca_flag
int alloca_flag static
Definition at line 126 of file exp_rte.cpp.
Referenced by exp_alloca(), exp_end(), and exp_header().
allocharhdr
SPTR allocharhdr static
Definition at line 106 of file exp_rte.cpp.
Referenced by allochartmp(), exp_end(), and exp_header().
arg_entry
int arg_entry static
Definition at line 2785 of file exp_rte.cpp.
Referenced by add_struct_byval_to_args(), add_to_args(), gen_arg_ili(), init_arg_ili(), and process_desc_args().
arg_ili
arg_info* arg_ili static
Definition at line 2784 of file exp_rte.cpp.
Referenced by add_struct_byval_to_args(), add_to_args(), end_arg_ili(), gen_arg_ili(), gen_arg_operand(), gen_arg_operand_list(), gen_llvm_atomic_intrinsic_for_builtin(), gen_llvm_instr(), get_next_arg(), init_arg_ili(), process_desc_args(), and put_arg_ili().
charargs
int charargs static
Definition at line 2786 of file exp_rte.cpp.
Referenced by exp_call(), gen_arg_ili(), init_arg_ili(), and pass_char_arg().
exp_call_sym
SPTR exp_call_sym static
sptr subprogram being called
Definition at line 104 of file exp_rte.cpp.
Referenced by exp_call(), gen_arg_ili(), and pass_char_arg().
fptr_iface
SPTR fptr_iface static
sptr of function pointer's interface
Definition at line 105 of file exp_rte.cpp.
Referenced by exp_call(), and exp_type_bound_proc_call().
garg_ili
garg_info* garg_ili static
Definition at line 2788 of file exp_rte.cpp.
Referenced by end_arg_ili(), exp_call(), and init_arg_ili().
gsmove_ilt
int gsmove_ilt static
Definition at line 206 of file exp_rte.cpp.
Referenced by exp_remove_gsmove(), and gsmove_chk_block().
len_ili
int* len_ili static
Definition at line 2787 of file exp_rte.cpp.
Referenced by end_arg_ili(), exp_call(), gen_arg_ili(), init_arg_ili(), and pass_char_arg().
memarg_var
SPTR memarg_var static
variable used to locate the beginning of the memory argument area
Definition at line 131 of file exp_rte.cpp.
Referenced by exp_header().
mscall_flag
int mscall_flag static
Definition at line 125 of file exp_rte.cpp.
Referenced by exp_end(), and exp_header().
nentries
int nentries static
number of entries for the subprogram
Definition at line 123 of file exp_rte.cpp.
Referenced by pp_entries(), and pp_entries_mixedstrlen().
p_chk_block
void(* p_chk_block) (int) (int) = chk_block static
Definition at line 204 of file exp_rte.cpp.
Referenced by _exp_smove(), and exp_remove_gsmove().
parg
int* parg static
pointer to area for dummy arg processing
Definition at line 107 of file exp_rte.cpp.
Referenced by leave_arg(), pp_entries(), pp_entries_mixedstrlen(), pp_params(), and process_end_of_list().
pfinfo
finfo_t* pfinfo static
table of finfo for the entries
Definition at line 122 of file exp_rte.cpp.
Referenced by exp_end(), pp_entries(), pp_entries_mixedstrlen(), pp_params(), and pp_params_mixedstrlen().
retgrp_cnt
int retgrp_cnt static
number of return counts
Definition at line 127 of file exp_rte.cpp.
Referenced by exp_end(), pp_entries(), and pp_entries_mixedstrlen().
retgrp_var
SPTR retgrp_var static
local variable holding return group value
Definition at line 128 of file exp_rte.cpp.
Referenced by exp_end(), pp_entries(), and pp_entries_mixedstrlen().
smove_flag
int smove_flag static
Definition at line 124 of file exp_rte.cpp.
Referenced by _exp_smove(), exp_end(), and exp_header().
sw_array
SWEL* sw_array static
linear form of the switch list, incl default
Definition at line 2491 of file exp_rte.cpp.
Referenced by exp_agoto(), exp_cgoto(), and genswitch().
sw_temp
int sw_temp static
acon ili of temp holding value of switch val
Definition at line 2492 of file exp_rte.cpp.
Referenced by exp_agoto(), exp_cgoto(), and genswitch().
sw_val
int sw_val static
ili of the original switch value; becomes a load of a temp if it's necessary to temp store value
Definition at line 2493 of file exp_rte.cpp.
Referenced by exp_agoto(), exp_cgoto(), and genswitch().