flang: exp_ftn.cpp File Reference
exp_ftn.cpp File Reference
Fortran-specific expander routines.
#include "exp_ftn.h"
#include "exputil.h"
#include "exp_rte.h"
#include "expreg.h"
#include "expatomics.h"
#include "dtypeutl.h"
#include "regutil.h"
#include "machreg.h"
#include "ilm.h"
#include "fih.h"
#include "ilmtp.h"
#include "ili.h"
#include "expand.h"
#include "machar.h"
#include "llassem.h"
#include "rte.h"
#include "mach.h"
#include "pragma.h"
#include "rtlRtns.h"
#include "upper.h"
#include "mth.h"
#include "mwd.h"
#include "ccffinfo.h"
#include "symfun.h"
Macros
#define EXPANDER_DECLARE_INTERNAL
#define RTE_C
#define SINGLE_COMPLEX_OP XBIT(70, 0x40000000)
#define Get_expb_logcjmp() expb.logcjmp
#define mk_prototype mk_prototype_llvm
#define BR_TRUE(t, i, c, s) ad3ili(Get_expb_logcjmp(), ad2ili(aif[t].cmpop, i, c), CC_NE, s)
Functions
static void begin_entry (SPTR esym)
Shared function for calling target specific exp_header.
static void store_aret (int)
static void create_array_subscr (int nmex, SPTR sym, DTYPE dtype, int nsubs, int *subs, int ilix)
create an array reference given the array and subscripts
static int add_ptr_subscript (int, int, int, int, int, int, ADSC *, int, int)
static int forceK (int ili)
static bool is_ishft (int curilm)
check special case for ISHFT(int8)
void exp_ac (ILM_OP opc, ILM *ilmp, int curilm)
...
static int genload (SPTR sym, bool bigobj)
static void compute_subscr (ILM *ilmp, bool bigobj)
static int kanji_bytes (int ilix)
: return double character length, since kanji char is 2 bytes long
static int kanji_divide (int ilix)
: return kanji char string length from byte count, divide by 2
static int compute_nme (SPTR sptr, int constant, int basenm)
static void compute_sdsc_subscr (ILM *ilmp, bool bigobj)
static bool is_currsub_dummy (int sdsc)
int get_sdsc_element (SPTR sdsc, int indx, int membase, int membase_nme)
...
static void create_sdsc_subscr (int nmex, SPTR sptr, int nsubs, int *subs, DTYPE dtype, int ilix, int sdscilix)
static void inlarr (int curilm, DTYPE odtype, bool bigobj)
static int finish_array (bool bigobj, bool inl_flg)
void exp_array (ILM_OP opc, ILM *ilmp, int curilm)
...
int create_array_ref (int nmex, SPTR sptr, DTYPE dtype, int nsubs, int *subs, int ilix, int sdscilix, int inline_flag, int *pnme)
...
static bool simple_ili (int ilix)
void exp_bran (ILM_OP opc, ILM *ilmp, int curilm)
...
void exp_misc (ILM_OP opc, ILM *ilmp, int curilm)
...
void exp_restore_mxcsr (void)
...
int exp_get_sdsc_len (int s, int base, int basenm)
...
SPTR frte_func (SPTR(*pf)(const char *), const char *root)
...
Variables
static int vf_addr
static int entry_sptr
static int accreduct_op
bool ishft = false
struct {
int base
int basenm
int zbase
int offset
int scale
int elmscz
int elmsz
DTYPE eldt
int nsubs
int sub [7]
int osub [7]
int finalnme
} subscr
Detailed Description
Fortran-specific expander routines.
Definition in file exp_ftn.cpp.
Macro Definition Documentation
BR_TRUE
#define BR_TRUE (t, i, c, s) ad3ili(Get_expb_logcjmp(), ad2ili(aif[t].cmpop, i, c), CC_NE, s)
EXPANDER_DECLARE_INTERNAL
#define EXPANDER_DECLARE_INTERNAL
Definition at line 24 of file exp_ftn.cpp.
Get_expb_logcjmp
#define Get_expb_logcjmp () expb.logcjmp
Definition at line 56 of file exp_ftn.cpp.
mk_prototype
#define mk_prototype mk_prototype_llvm
Definition at line 75 of file exp_ftn.cpp.
RTE_C
#define RTE_C
Definition at line 28 of file exp_ftn.cpp.
SINGLE_COMPLEX_OP
#define SINGLE_COMPLEX_OP XBIT(70, 0x40000000)
Definition at line 42 of file exp_ftn.cpp.
Function Documentation
add_ptr_subscript()
static int add_ptr_subscript (int i, int sub, int ili1, int base, int basesym, int basenm, ADSC * adp, int ptrexpand, int any_kr) static
Definition at line 2067 of file exp_ftn.cpp.
References ad1ili(), ad2ili(), ad3ili(), AD_MLPYR, AD_SDSC, addnme(), base, basenm, DT_INT, DTYG, get_sdsc_element(), i, IL_IADD, IL_IMUL, m, mk_address(), MSZ_I8, MSZ_WORD, NT_VAR, sub, val, and XBIT.
Referenced by compute_sdsc_subscr().
begin_entry()
static void begin_entry (SPTR esym) static
Shared function for calling target specific exp_header.
Definition at line 4483 of file exp_ftn.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad_acon(), ad_icon, addr, EXP::aret_tmp, arg, ARG_IR, ILTB::callfg, ccff_open_unit(), chk_block(), DT_DCMPLX, DT_INT, entry_sptr, exp_header(), expb, gbl, GBL_CURRFUNC, EXP::gentmps, getccsym(), iltb, mk_address(), mkfunc(), EXP::mxcsr_tmp, SC_AUTO, tmp, and vf_addr.
Referenced by exp_misc().
compute_nme()
static int compute_nme (SPTR sptr, int constant, int basenm) static
Definition at line 1628 of file exp_ftn.cpp.
References ad_icon, add_arrnme(), addnme(), basenm, NT_ARR, NT_MEM, NT_VAR, sptr, SPTR_NULL, and sub.
Referenced by get_sdsc_element().
compute_sdsc_subscr()
static void compute_sdsc_subscr (ILM * ilmp, bool bigobj) static
Definition at line 1656 of file exp_ftn.cpp.
References ad1ili(), ad2ili(), ad3ili(), AD_DPTR, ad_icon, ad_kconi(), AD_SDSC, AD_ZBASE, add_ptr_subscript(), addnme(), assert, base, basenm, charlen(), CONVAL2G, DTySeqTyElement, ERR_Severe, exp_get_sdsc_len(), gbl, GBL_CURRFUNC, get_isz_cval(), get_sdsc_element(), i, ikmove(), IL_AADD, IL_IADD, IL_IMUL, IL_ISUB, IL_RES, IL_TYPE, ILI_OF, ILI_OPC, ILI_OPND, ILIA_KR, ILMB::ilm_base, ILM_DTyOPND, ILM_OPC, ILM_OPND, ILM_SymOPND, ilmb, ILTY_CONS, is_llvm_local_private(), ISZ_T, STB::k0, kanji_bytes(), kimove(), mk_address(), MSZ_I8, MSZ_WORD, NME_NM, NME_OF, NME_SYM, NME_TYPE, NT_IND, NT_VAR, offset, ORIGDUMMYG, scale_of(), Scale_Of(), size_of(), SPTR_NULL, stb, sub, subscr, val, XBIT, and zbase.
Referenced by exp_array(), and inlarr().
compute_subscr()
static void compute_subscr (ILM * ilmp, bool bigobj) static
Definition at line 1566 of file exp_ftn.cpp.
References assert, create_array_subscr(), ERR_Severe, i, ILI_OF, ILMB::ilm_base, ILM_DTyOPND, ILM_OPC, ILM_OPND, ILM_SymOPND, ilmb, NME_OF, ORIGDUMMYG, and subscr.
Referenced by exp_array(), and inlarr().
create_array_ref()
int create_array_ref (int nmex, SPTR sptr, DTYPE dtype, int nsubs, int * subs, int ilix, int sdscilix, int inline_flag, int * pnme)
...
Definition at line 3420 of file exp_ftn.cpp.
References ad1ili(), ad2ili(), ad3ili(), AD_DPTR, AD_SDSC, ad_val_of(), add_arrnme(), base, create_array_subscr(), create_sdsc_subscr(), i, ikmove(), IL_AADD, IL_ASUB, IL_IMUL, IL_ISUB, IL_RES, IL_TYPE, ILI_OPC, ILI_OPND, ILIA_KR, ILTY_CONS, kimove(), NME_NULL, nsubs, NT_ARR, sptr, SPTR_NULL, sub, subscr, and XBIT.
Referenced by exp_array().
create_array_subscr()
static void create_array_subscr (int nmex, SPTR sym, DTYPE dtype, int nsubs, int * subs, int ilix) static
create an array reference given the array and subscripts
Definition at line 3170 of file exp_ftn.cpp.
References ad1ili(), ad2ili(), AD_DPTR, ad_icon, ad_kconi(), AD_MLPYR, ad_val_of(), AD_ZBASE, assert, charlen(), CONVAL2G, DTySeqTyElement, ERR_Severe, exp_get_sdsc_len(), genload(), get_isz_cval(), i, ikmove(), IL_IADD, IL_IMUL, IL_ISUB, IL_RES, IL_TYPE, ILI_OPC, ILI_OPND, ILIA_KR, ILTY_CONS, ISZ_T, kanji_bytes(), mplyr, NME_OF, nsubs, offset, scale_of(), sel_icnst(), size_of(), sub, subscr, val, XBIT, and zbase.
Referenced by compute_subscr(), and create_array_ref().
create_sdsc_subscr()
static void create_sdsc_subscr (int nmex, SPTR sptr, int nsubs, int * subs, DTYPE dtype, int ilix, int sdscilix) static
Definition at line 2259 of file exp_ftn.cpp.
References ad1ili(), ad2ili(), ad3ili(), AD_DPTR, ad_icon, ad_kconi(), AD_MLPYR, AD_SDSC, AD_ZBASE, addnme(), assert, base, basenm, charlen(), DTySeqTyElement, ERR_Severe, exp_get_sdsc_len(), gbl, GBL_CURRFUNC, get_sdsc_element(), i, ikmove(), IL_IADD, IL_IMUL, IL_RES, ILI_OPC, ILIA_KR, is_llvm_local_private(), j, STB::k0, kanji_bytes(), m, mk_address(), MSZ_I8, MSZ_WORD, NME_NM, NME_SYM, NME_TYPE, nsubs, NT_IND, NT_MEM, NT_VAR, ORIGDUMMYG, scale_of(), size_of(), sptr, SPTR_NULL, stb, sub, subscr, val, XBIT, and zbase.
Referenced by create_array_ref().
exp_ac()
void exp_ac (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 118 of file exp_ftn.cpp.
References ad1ili(), ad2func_kint(), ad2ili(), ad3ili(), ad_aconi(), ad_icon, AR_RETVAL, arg, assert, basesym_of(), bihb, CC_EQ, CONVAL2G, STB::dbl0, DP, DP_RETVAL, DT_CMPLX, DT_CPTR, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, DT_LOG, DT_REAL, ERR_Severe, exp_alloca(), exp_mac(), exp_qjsr(), flg, STB::flt0, forceK(), gbl, get_acon(), getcon(), FLG::ieee, IL_IADD, IL_IDIV, IL_IMUL, IL_INEG, IL_ISUB, IL_RES, ILI_OF, ILI_OPC, ILI_OPND, ILI_SymOPND, ILIA_AR, ILIA_IR, ILIA_KR, ILMB::ilm_base, ILM_IRESULT, ILM_ISCHAR, ILM_ISCMPLX, ILM_ISDCMPLX, ILM_ISQCMPLX, ILM_NME, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_RRESULT, ILM_SymOPND, ilmb, interr(), is_creal_flt0(), is_dbl0(), is_flt0(), is_ishft(), ishft, kimove(), RCANDB::kr, KR_RETVAL, loc_of(), mk_prototype, mkfunc(), mkRteRtnNm(), MTH_I_DFLOATK, MTH_I_FIXK, MTH_I_FLOATK, MTH_I_KBCLR, MTH_I_KBITS, MTH_I_KBSET, MTH_I_KBTEST, NME_OF, NME_UNK, BIHB::parfg, STB::quad0, r, rcandb, relaxed_math(), RTE_auto_allocv, s, SetILM_OPC, SINGLE_COMPLEX_OP, size_of(), SP, sptr, SPTR_NULL, stb, SymConval1, BIHB::taskfg, tmp, val, void(), XBIT, and XBIT_NEW_MATH_NAMES_CMPLX.
exp_array()
void exp_array (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 3061 of file exp_ftn.cpp.
References AD_DPTR, AD_SDSC, assert, compute_sdsc_subscr(), compute_subscr(), create_array_ref(), DTY, DTySeqTyElement, ERR_Severe, finish_array(), i, ILI_OF, ILMB::ilm_base, ILM_CLEN, ILM_DTyOPND, ILM_ISCHAR, ILM_MXLEN, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_SymOPND, ilmb, inlarr(), kanji_divide(), kimove(), NME_OF, ORIGDUMMYG, subscr, TY_CHAR, TY_NCHAR, and XBIT.
Referenced by exp_ref().
exp_bran()
void exp_bran (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 3528 of file exp_ftn.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_acon(), addnme(), BR_TRUE, CC_EQ, CC_GE, CC_LE, CC_LT, CC_NE, chk_block(), DT_DBLE, DT_INT, DT_REAL, exp_agoto(), exp_cgoto(), exp_mac(), expb, flg, Get_expb_logcjmp, i, IL_ISUB, IL_RES, ILI_OPC, ILI_OPND, ILIA_KR, ILMB::ilm_base, ILM_OPC, ILM_OPND, ILM_RESULT, ILM_SymOPND, ilmb, ilms, load, mkrtemp_sc(), msz, MSZ_F16, MSZ_F2, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_WORD, NT_VAR, FLG::opt, RFCNTD, EXP::sc, simple_ili(), type, and XBIT.
Referenced by eval_ilm().
exp_get_sdsc_len()
int exp_get_sdsc_len (int s, int base, int basenm)
...
Definition at line 4595 of file exp_ftn.cpp.
References ad1ili(), assert, base, basenm, DDTG, ERR_Severe, get_sdsc_element(), IL_RES, ILI_OPC, ILIA_KR, kimove(), len, s, and XBIT.
Referenced by compute_sdsc_subscr(), create_array_subscr(), create_ref(), create_sdsc_subscr(), exp_load(), and inlarr().
exp_misc()
void exp_misc (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 3771 of file exp_ftn.cpp.
References ACC_DATAMOVEMENT_DISABLED, accreduct_op, ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_icon, ad_kconi(), addnme(), ADDRCAND, arg, ARG_IR, EXP::arglcnt, assert, begin_entry(), BIH_DOCONC, BIH_ENLAB, BIH_GUARDEE, BIH_GUARDER, BIH_HEAD, BIH_LABEL, BIH_LINENO, BIH_NOMERGE, BIH_ZTRP, bihb, EXP::bits, BOS_SIZE, CC_GT, CC_LE, CC_NE, chk_block(), CNULL, cr_block(), EXP::curbih, EXP::curilt, EXP::curlin, FIHB::currfindex, FIHB::currftag, entry_sptr, ERR_Severe, error(), exp_end(), exp_estmt(), exp_label(), expb, fihb, EXP::flags, FLANG_FALLTHROUGH, flg, flsh_block(), gbl, get_atomic_capture_created(), get_atomic_store_created(), get_capture_read_ili(), get_capture_update_ili(), get_is_in_atomic_capture(), getccsym(), getsym(), STB::i1, IL_ISUB, IL_TYPE, ILI_OF, ILI_OPC, ILMB::ilm_base, ILM_CLEN, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_SymOPND, EXP::ilm_thresh, EXP::ilm_words, ilmb, ILT_NEXT, ILTY_CONS, IM_TYPE, IMTY_CONS, interr(), EXP::isguarded, STB::k1, mk_address(), mkrtemp_init(), MSZ_I8, MSZ_WORD, EXP::next, FIHB::nextfindex, FIHB::nextftag, EXP::nilms, NME_OF, EXP::noblock, EXP::noheader, NT_VAR, FLG::onetrip, FLG::opt, BIHB::parfg, PR_ACCASYNC, PR_ACCAUTO, PR_ACCBEGINDIR, PR_ACCCACHEDIR, PR_ACCCACHEREADONLY, PR_ACCCOLLAPSE, PR_ACCDATAREG, PR_ACCDEFNONE, PR_ACCDEFPRESENT, PR_ACCDEVICEID, PR_ACCEL, PR_ACCELLP, PR_ACCENDDATAREG, PR_ACCENDHOSTDATA, PR_ACCENDIMPDATAREG, PR_ACCENDKERNELS, PR_ACCENDPARCONSTRUCT, PR_ACCENDSCALARREG, PR_ACCENDSERIAL, PR_ACCENTERDATA, PR_ACCEXITDATA, PR_ACCFINALEXITDATA, PR_ACCFORCECOLLAPSE, PR_ACCGANG, PR_ACCGANGCHUNK, PR_ACCGANGDIM, PR_ACCHOST, PR_ACCHOSTDATA, PR_ACCIF, PR_ACCIMPDATAREG, PR_ACCIMPDATAREGX, PR_ACCINDEPENDENT, PR_ACCKERNEL, PR_ACCKERNELS, PR_ACCKLOOP, PR_ACCNOWAIT, PR_ACCNUMGANGS, PR_ACCNUMGANGS2, PR_ACCNUMGANGS3, PR_ACCNUMWORKERS, PR_ACCPARALLEL, PR_ACCPARCONSTRUCT, PR_ACCPARUNROLL, PR_ACCPLOOP, PR_ACCREDUCTOP, PR_ACCSCALARREG, PR_ACCSEQ, PR_ACCSEQUNROLL, PR_ACCSERIAL, PR_ACCSHORTLOOP, PR_ACCSLOOP, PR_ACCTKLOOP, PR_ACCTPLOOP, PR_ACCTSLOOP, PR_ACCUNROLL, PR_ACCUPDATE, PR_ACCVECTOR, PR_ACCVECUNROLL, PR_ACCVLENGTH, PR_ACCWAIT, PR_ACCWAITARG, PR_ACCWAITDIR, PR_ACCWORKER, PR_ENDACCEL, PR_ENDKERNEL, PR_KERNEL, PR_KERNEL_BLOCK, PR_KERNEL_DEVICE, PR_KERNEL_GRID, PR_KERNEL_NEST, PR_KERNEL_STREAM, PR_KERNELBEGIN, PR_PCASTCOMPARE, EXP::retcnt, EXP::retlbl, RFCNTD, RFCNTI, s, set_atomic_capture_created(), set_atomic_store_created(), set_capture_read_ili(), set_capture_update_ili(), set_is_in_atomic(), set_is_in_atomic_capture(), set_is_in_atomic_read(), set_is_in_atomic_write(), SPTR_NULL, EXP::start, stb, store_aret(), strlen(), SYMNAME, BIHB::taskfg, tmp, vf_addr, EXP::waitlbl, wr_block(), and XBIT.
Referenced by eval_ilm().
exp_restore_mxcsr()
void exp_restore_mxcsr (void)
...
Definition at line 4553 of file exp_ftn.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad_acon(), addnme(), addr, arg, ILTB::callfg, chk_block(), expb, gbl, iltb, mkfunc(), MSZ_WORD, EXP::mxcsr_tmp, NT_VAR, and tmp.
Referenced by exp_end().
finish_array()
static int finish_array (bool bigobj, bool inl_flg) static
Definition at line 2937 of file exp_ftn.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad_val_of(), add_arrnme(), base, i, ikmove(), IL_AADD, IL_ASUB, IL_IADD, IL_IMUL, IL_ISUB, IL_RES, IL_TYPE, ILI_OPC, ILI_OPND, ILIA_KR, ILTY_CONS, kimove(), NME_NULL, NME_OVS, NME_TYPE, NT_ARR, SPTR_NULL, sub, subscr, and XBIT.
Referenced by exp_array().
forceK()
static int forceK (int ili) static
Definition at line 80 of file exp_ftn.cpp.
References ikmove(), ili, and XBIT.
Referenced by exp_ac().
frte_func()
SPTR frte_func (SPTR(*)(const char *) pf, const char * root)
...
Definition at line 4622 of file exp_ftn.cpp.
References assert, ERR_Severe, p, root, and strlen().
Referenced by allochartmp(), exp_end(), exp_strcpy(), and exp_strx().
genload()
static int genload (SPTR sym, bool bigobj) static
Definition at line 1525 of file exp_ftn.cpp.
References ad1ili(), ad3ili(), addnme(), compute_address(), flg, MSZ_I8, MSZ_WORD, NT_VAR, FLG::smp, sym_is_refd(), and XBIT.
Referenced by create_array_subscr(), and inlarr().
get_sdsc_element()
int get_sdsc_element (SPTR sdsc, int indx, int membase, int membase_nme)
...
Definition at line 2184 of file exp_ftn.cpp.
References ad2ili(), ad3ili(), ad_aconi(), addnme(), ADDRCAND, compute_nme(), DTYG, elmsz, ERR_Fatal, STB::i1, IL_AADD, ili, interr(), is_currsub_dummy(), IS_THREAD_TP, STB::k1, mk_address(), mk_argasym(), MSZ_I8, MSZ_WORD, NT_VAR, ref_threadprivate(), ref_threadprivate_var(), scale, scale_of(), stb, and XBIT.
Referenced by add_ptr_subscript(), compute_sdsc_subscr(), create_sdsc_subscr(), exp_get_sdsc_len(), and inlarr().
inlarr()
static void inlarr (int curilm, DTYPE odtype, bool bigobj) static
the current ilm is an INLELEM which is generated for the subscripted references of the dummy arrays of a subprogram which has been inlined. This ilm is used for cases where the name of the actual array cannot be substituted (e.g., the dimensions change). The goal of this ilm is to generate a subscript expression where the subscripts used for the dummy array are folded into the first subscript of the actual array; doing this allows the name's entry of the actual to be used. Note that it's assumed that the data types of the actual & dummy arrays match.
This routine is recursive, where the subscripts are evaluated beginning with the base reference (ELEMENT, BASE, or MEMBER ilms). Because of multi-level inlining, it's possible to have a "list" of INLELEM ilms which ultimately locates the base.
Definition at line 2599 of file exp_ftn.cpp.
References ad2ili(), AD_DPTR, ad_icon, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_SDSC, ad_val_of(), AD_ZBASE, assert, base, basenm, charlen(), compute_sdsc_subscr(), compute_subscr(), CONVAL2G, DBGBIT, dilitre(), DTY, DTySeqTyElement, dumpdtype(), ERR_Severe, exp_get_sdsc_len(), FILE, gbl, genload(), get_isz_cval(), get_sdsc_element(), i, ikmove(), IL_IADD, IL_IMUL, IL_ISUB, IL_RES, IL_TYPE, ILI_OF, ILI_OPC, ILI_OPND, ILIA_KR, ILMB::ilm_base, ILM_DTyOPND, ILM_OPC, ILM_OPND, ILM_SymOPND, ilmb, ILTY_CONS, inlarr(), interr(), ISZ_T, kanji_bytes(), mplyr, NME_OF, nsubs, offset, Scale_Of(), sel_icnst(), sel_iconv(), size_of(), sub, subscr, tmp, val, XBIT, and zbase.
Referenced by add_arrnme(), build_sym_nme(), exp_array(), inlarr(), and lookupnme().
is_currsub_dummy()
static bool is_currsub_dummy (int sdsc) static
Definition at line 2152 of file exp_ftn.cpp.
References flg, gbl, and FLG::smp.
Referenced by get_sdsc_element().
is_ishft()
static bool is_ishft (int curilm) static
check special case for ISHFT(int8)
Definition at line 95 of file exp_ftn.cpp.
References BOS_SIZE, ILMB::ilm_base, ILM_OPC, ILM_OPND, ilmb, ilms, IM_VAR, len, and ILMINFO::oprs.
Referenced by exp_ac().
kanji_bytes()
static int kanji_bytes (int ilix) static
: return double character length, since kanji char is 2 bytes long
Definition at line 1603 of file exp_ftn.cpp.
References ad2ili(), ad_icon, ad_kcon(), IL_IMUL, IL_RES, ILI_OPC, and ILIA_KR.
Referenced by compute_sdsc_subscr(), create_array_subscr(), create_sdsc_subscr(), and inlarr().
kanji_divide()
static int kanji_divide (int ilix) static
: return kanji char string length from byte count, divide by 2
Definition at line 1617 of file exp_ftn.cpp.
References ad2ili(), ad_icon, ad_kcon(), IL_IDIV, IL_RES, ILI_OPC, and ILIA_KR.
Referenced by exp_array().
simple_ili()
static bool simple_ili (int ilix) static
Definition at line 3515 of file exp_ftn.cpp.
References func_in(), IL_TYPE, ILI_OPC, ILTY_CONS, and ILTY_LOAD.
Referenced by exp_bran().
store_aret()
static void store_aret (int val) static
Definition at line 4581 of file exp_ftn.cpp.
References ad4ili(), ad_acon(), addnme(), addr, ADDRCAND, EXP::aret_tmp, chk_block(), expb, MSZ_WORD, NT_VAR, tmp, and val.
Referenced by exp_misc().
Variable Documentation
accreduct_op
int accreduct_op static
Definition at line 73 of file exp_ftn.cpp.
Referenced by exp_misc().
base
int base
Definition at line 1551 of file exp_ftn.cpp.
Referenced by add_ptr_subscript(), compute_sdsc_subscr(), create_array_ref(), create_sdsc_subscr(), exp_get_sdsc_len(), finish_array(), and inlarr().
basenm
int basenm
Definition at line 1552 of file exp_ftn.cpp.
Referenced by add_ptr_subscript(), compute_nme(), compute_sdsc_subscr(), create_ref(), create_sdsc_subscr(), exp_call(), exp_get_sdsc_len(), exp_ref(), inlarr(), llGetThreadprivateAddr(), load_uplevel_addresses(), ref_threadprivate(), ref_threadprivate_var(), and setTaskloopVars().
eldt
DTYPE eldt
Definition at line 1558 of file exp_ftn.cpp.
Referenced by subst_lhs_arrfn().
elmscz
int elmscz
Definition at line 1556 of file exp_ftn.cpp.
elmsz
int elmsz
Definition at line 1557 of file exp_ftn.cpp.
Referenced by get_sdsc_element().
entry_sptr
int entry_sptr static
Definition at line 69 of file exp_ftn.cpp.
Referenced by begin_entry(), and exp_misc().
finalnme
int finalnme
Definition at line 1562 of file exp_ftn.cpp.
ishft
bool ishft = false
Definition at line 77 of file exp_ftn.cpp.
Referenced by addarth(), and exp_ac().
nsubs
int nsubs
Definition at line 1559 of file exp_ftn.cpp.
Referenced by create_array_ref(), create_array_subscr(), create_sdsc_subscr(), dd_array_conflict(), do_subscript(), inlarr(), inline_ast(), mk_component_ast(), promote_assumsz_arg(), ref_pd(), replace_ast_subtree(), and replace_vector_subscript().
offset
int offset
Definition at line 1554 of file exp_ftn.cpp.
Referenced by compute_sdsc_subscr(), create_array_subscr(), and inlarr().
osub
int osub[7]
Definition at line 1561 of file exp_ftn.cpp.
scale
int scale
Definition at line 1555 of file exp_ftn.cpp.
Referenced by __exp_d_scalar_kernel(), __exp_scalar_kernel(), __ldexp_d_scalar_kernel(), __ldexpf_scalar_kernel(), cexp_scalar_default_abi(), cexp_vec(), cexpf_vec(), get_sdsc_element(), red_aadd(), red_damv(), scale_of(), and Scale_Of().
sub
int sub[7]
Definition at line 1560 of file exp_ftn.cpp.
Referenced by add_ptr_subscript(), compute_nme(), compute_sdsc_subscr(), create_array_ref(), create_array_subscr(), create_sdsc_subscr(), finish_array(), and inlarr().
struct { ... } subscr
Referenced by _linearize(), _linearize_func(), _reshape(), _sd_member(), allocate_one_auto(), build_allocation_item(), check_derived_type_array_section(), compute_sdsc_subscr(), compute_subscr(), copy_arg_to_seq_tmp(), copy_replic_sect_to_tmp(), create_array_ref(), create_array_subscr(), create_sdsc_subscr(), exp_array(), finish_array(), gen_bounds_assignments(), gen_derived_arr_init(), get_charintrin_temp(), get_forall_subscr(), get_temp_forall2(), init_sdsc_bounds(), inlarr(), inline_reduction_f90(), MakeReplacement(), matmul(), mk_descr_from_section(), mk_forall_sptr(), mk_ptr_subscr(), mk_result_sptr(), mmul(), mmul_arg(), reshape(), rewrite_block_where(), rewrite_func_ast(), rewrite_intr_allocatable(), rewrite_sub_args(), rewrite_subscr(), semant3(), temp_copy_section(), temp_gatherx(), and wrap_symbol().
vf_addr
int vf_addr static
Definition at line 68 of file exp_ftn.cpp.
Referenced by begin_entry(), and exp_misc().
zbase
int zbase
Definition at line 1553 of file exp_ftn.cpp.
Referenced by _mk_arrdsc(), _reshape(), compute_sdsc_subscr(), copy_surrogate_to_bnds_vars(), create_array_subscr(), create_sdsc_subscr(), fill_adjustable_array_dtype(), fill_fixed_array_dtype(), fix_datatype(), fix_mem_bounds(), fix_mem_bounds2(), fixup_param_vars(), inlarr(), lower_put_datatype(), lower_use_datatype(), and put_adjarr_bounds().