flang: exp_rte.h File Reference
exp_rte.h File Reference
#include "gbldefs.h"
#include "global.h"
#include "symtab.h"
#include "expand.h"
Functions
bool bindC_function_return_struct_in_registers (int func_sym)
...
int charaddr (SPTR sym)
...
int charlen (SPTR sym)
...
int exp_alloca (ILM *ilmp)
...
int gen_arg_ili (void)
...
SPTR getdumlen (void)
...
SPTR gethost_dumlen (int arg, ISZ_T address)
int is_passbyval_dummy (int sptr)
...
int needlen (int sym, int func)
...
void add_arg_ili (int ilix, int nme, int dtype)
...
void chk_terminal_func (int entbih, int exitbih)
...
void end_arg_ili (void)
...
void exp_agoto (ILM *ilmp, int curilm)
...
void expand_smove (int destilm, int srcilm, DTYPE dtype)
...
void exp_build_agoto (int *tab, int mx)
...
void exp_call (ILM_OP opc, ILM *ilmp, int curilm)
...
void exp_cgoto (ILM *ilmp, int curilm)
...
void exp_end (ILM *ilmp, int curilm, bool is_func)
...
void exp_fstring (ILM_OP opc, ILM *ilmp, int curilm)
...
void exp_header (SPTR sym)
...
void exp_qjsr (const char *ext, DTYPE res_dtype, ILM *ilmp, int curilm)
...
void exp_remove_gsmove (void)
...
void exp_reset_argregs (int ir, int fr)
...
void exp_szero (ILM *ilmp, int curilm, int to, int from, int dtype)
...
void exp_zqjsr (char *ext, int res_dtype, ILM *ilmp, int curilm)
...
void init_arg_ili (int n)
...
bool func_has_char_args (SPTR func)
Checks to see if a procedure has character dummy arguments.
void AssignAddresses (void)
Process referenced symbols, assigning them locations.
Function Documentation
add_arg_ili()
void add_arg_ili (int ilix, int nme, int dtype)
...
Definition at line 2874 of file exp_rte.cpp.
References add_to_args(), ERR_Severe, IL_RES, ILI_OPC, ILIA_AR, ILIA_CD, ILIA_CS, ILIA_DP, ILIA_IR, ILIA_KR, ILIA_QP, ILIA_SP, and interr().
Referenced by exp_call().
AssignAddresses()
void AssignAddresses (void)
Process referenced symbols, assigning them locations.
Definition at line 6079 of file exp_rte.cpp.
References ILM_OPC, ILM_OPND, ILM_SymOPND, ilms, IM_OPRFLAG, IM_VAR, len, OPR_SYM, ILMINFO::oprs, rdilms(), reset_global_ilm_position(), SC_AUTO, sptr, SPTR_NULL, stb, and sym_is_refd().
Referenced by process_input().
bindC_function_return_struct_in_registers()
bool bindC_function_return_struct_in_registers (int func_sym)
...
...
Parameters
func_sym the function's symbol
Definition at line 1400 of file exp_rte.cpp.
References check_return(), CLASS_MEM, and DEBUG_ASSERT.
Referenced by gen_return_operand(), and store_for_homing().
charaddr()
int charaddr (SPTR sym)
...
...
Definition at line 5976 of file exp_rte.cpp.
References ad2ili(), addnme(), addr, assert, ERR_Severe, gbl, mk_address(), mk_argasym(), and NT_VAR.
Referenced by create_ref().
charlen()
int charlen (SPTR sym)
...
...
Definition at line 5952 of file exp_rte.cpp.
References ad3ili(), addnme(), addr, gbl, mk_address(), mk_charlen_address(), mk_charlen_parref_sptr(), MSZ_I8, MSZ_WORD, and NT_VAR.
Referenced by compute_sdsc_subscr(), create_array_subscr(), create_ref(), create_sdsc_subscr(), exp_smp(), inlarr(), and lower_data_stmts().
chk_terminal_func()
void chk_terminal_func (int entbih, int exitbih)
...
Parameters
entbih bih of the entry block
exitbih bih of the exit block
Check if this function is a terminal routine (one that does not call any other routines). If so, the necessary changes will be made to the entry and exit blocks. This optimization depends on the target machine and its execution environment. It is appropriate when the target does not have instructions to manipulate the stack; multiple instructions have to be generated to allocate stack space, manipulate the frame and stack pointers, and to check for overflow and underflow.
When the terminal function optimization is appropriate, the following applies:
exceptions and global registers are not used: a. if the routine is terminal, static space is used in lieu of the stack. ILIs QENTRY and QEXIT are used. b. otherwise, faster entry and exit routines, c_i_qentry and c_i_qexit, are used. The ENTRY ili is modified to locate c_i_qentry, and a new EXIT ili locating c_i_qexit is generated.
otherwise, the ENTRY and EXIT ILIs are left as is.
When the terminal function optimization is not appropriate, the following applies:
if exceptions and global registers are not used, the faster entry and exit routines, c_i_qentry and c_i_qexit, are used. The ILIs QENTRY and QEXIT are used.
otherwise, the ENTRY and EXIT ILIs are left as is.
The -q 0 256 switch forces full entry and exit to be used. The -q 0 4096 switch forces QENTRY and QEXIT to be used for all routines.
Definition at line 6031 of file exp_rte.cpp.
References ENTRY::auto_array, aux, and AUX::curr_entry.
Referenced by exp_end().
end_arg_ili()
void end_arg_ili (void)
...
Definition at line 2848 of file exp_rte.cpp.
References arg_ili, FREE, garg_ili, len_ili, and XBIT.
Referenced by exp_call().
exp_agoto()
void exp_agoto (ILM * ilmp, int curilm)
...
...
for TARGET_LLVM, we are not performing an indirect branch, so expand an assigned goto into a computed goto – the labels appearing in the ASSIGN statements and their respective computed goto index values have already been collected into a switch_base table whose starting index is agotostart.
Definition at line 2738 of file exp_rte.cpp.
References agotostart, assert, SWEL::clabel, FLG::dbg, ERR_Severe, exp_label(), flg, gbl, genswitch(), getlab(), i, ILI_OF, ILM_OPND, kimove(), n, RFCNTI, sw_array, sw_temp, sw_val, switch_base, and SWEL::val.
Referenced by exp_bran().
exp_alloca()
int exp_alloca (ILM * ilmp)
...
sptr = ILM_OPND(ilmp, 3); sym and currently ignored
tmp = ILM_OPND(ilmp, 4); stc and currently ignored
runtime adjusts the size
Definition at line 2074 of file exp_rte.cpp.
References ad1ili(), ad2ili(), ad_kcon(), ad_kconi(), alloca_flag, AR_RETVAL, ikmove(), ILI_OF, ILM_OPND, mk_prototype, mkfunc(), void(), and XBIT.
Referenced by exp_ac().
exp_build_agoto()
void exp_build_agoto (int * tab, int mx)
...
Definition at line 2701 of file exp_rte.cpp.
References agotostart, SWEL::clabel, convertSPTR, getswel(), i, SWEL::next, RFCNTI, switch_base, and SWEL::val.
Referenced by build_agoto().
exp_call()
void exp_call (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 3264 of file exp_rte.cpp.
References _exp_smove(), ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_acon(), ad_aconi(), ad_icon, add_arg_ili(), add_arglnk_closure(), add_gargl_closure(), add_last_arg(), add_struct_byval_to_args(), add_to_args(), addnme(), addr, AR_RETVAL, aux, basenm, ILTB::callfg, cfunc, charargs, CHARLEN_64BIT, check_cstruct_return(), chk_block(), cmplx_to_mem(), CMPLXFUNC_C, AUX::curr_entry, ENTRY::display, dt, DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, DT_ISBASIC, DT_REAL, DTY, DTyInterface, garg_info::dtype, DTySeqTyElement, end_arg_ili(), ERR_Severe, ERR_unused, exp_call_sym, exp_type_bound_proc_call(), expb, FLANG_FALLTHROUGH, fptr_iface, FR_RETVAL, FUNCPTR_BINDC, garg_ili, gbl, gen_arg_ili(), getstr(), getstraddr(), getstrlen(), i, IILM_DTyOPND, IILM_OPC, IILM_OPND, IL_AADD, IL_RES, ili, ILI_ALT, ILI_DTyOPND, ILI_OF, ILI_OPC, ILI_OPND, ili_opnd(), ILIA_AR, ILIA_CD, ILIA_CQ, ILIA_CS, ILIA_DP, ILIA_IR, ILIA_ISAR, ILIA_KR, ILIA_QP, ILIA_SP, garg_info::ilix, ILMB::ilm_base, ILM_CLEN, ILM_DTyOPND, ILM_IRESULT, ILM_ISCHAR, ILM_ISCMPLX, ILM_ISDCMPLX, ILM_ISQCMPLX, ILM_MXLEN, ILM_NME, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_RRESULT, ILM_SymOPND, ilmb, iltb, IM_TYPE, IMTY_CONS, IMTY_REF, init_arg_ili(), interr(), IR_RETVAL, is_asn_closure_call(), IS_INTERNAL_PROC_CALL, is_proc_desc_arg(), KR_RETVAL, len_ili, loc_of(), mk_address(), mk_argasym(), mkrtemp_cpx_sc(), mkrtemp_sc(), mkRteRtnNm(), msz, MSZ_BYTE, MSZ_F16, MSZ_F32, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_UHWORD, MSZ_WORD, nargs, _str::next, garg_info::nme, NME_OF, NME_STR1, NME_UNK, NME_VOL, NOSYM, NT_MEM, NT_VAR, optional_missing(), optional_present(), pass_char_arg(), replace_by_one(), replace_by_zero(), res, RTE_present, EXP::sc, sel_iconv(), size_of(), skip, sptr_mk_address, SPTR_NULL, storechartmp(), struct_ret_tmp(), SYMNAME, TY_CHAR, TY_NCHAR, garg_info::val_flag, and XBIT.
Referenced by eval_ilm().
exp_cgoto()
void exp_cgoto (ILM * ilmp, int curilm)
...
...
this processing is similiar to the processing of a switch by pgc. The exception is that the switch list is already ordered as a table in increasing order. pgc must first create a table of the switch values.
Definition at line 2505 of file exp_rte.cpp.
References ad1ili(), assert, chk_block(), SWEL::clabel, CONVAL2G, FLG::dbg, ERR_Severe, flg, gbl, genswitch(), i, ILI_OF, ILI_OPC, ILI_OPND, ILM_OPND, n, RFCNTD, sw_array, sw_temp, sw_val, switch_base, val, and SWEL::val.
Referenced by exp_bran().
exp_end()
void exp_end (ILM * ilmp, int curilm, bool is_func)
...
Definition at line 2110 of file exp_rte.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_acon(), ad_icon, addilt(), addnme(), addr, alloca_flag, allocharhdr, EXP::aret_tmp, EXP::arglist, aux, BIH_EX, BIH_LAST, BIH_NEXT, BIH_SMOVE, BIH_XT, EXP::bits, ILTB::callfg, EXP::callfg, chk_block(), chk_terminal_func(), CONVAL2G, cr_block(), EXP::curbih, EXP::curilt, AUX::curr_entry, FLG::debug, DOREG1, ENTRY::ent_save, exp_label(), exp_mp_func_prologue(), exp_restore_mxcsr(), expb, EXPDBG, ENTRY::flags, EXP::flags, flg, flsh_block(), freearea(), frte_func(), func, gbl, gen_funcret(), getlab(), FLG::ieee, ILI_OPND, ILT_PREV, iltb, IR_ARET, ld, mkfunc(), mkrtemp_end(), mkRteRtnNm(), mr_reset_frglobals(), mr_reset_numglobals(), mscall_flag, MSZ_WORD, NOSYM, NT_VAR, FLG::opt, pfinfo, FLG::profile, rdilts(), reg_assign1(), finfo_t::retgrp, retgrp_cnt, retgrp_var, EXP::retlbl, RFCNTI, RTE_str_free, RU_PROG, smove_flag, FLG::smp, SPTR_NULL, st, SYMNAME, tmp, wr_block(), wrilts(), and XBIT.
Referenced by exp_misc().
exp_fstring()
void exp_fstring (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 5057 of file exp_rte.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_icon, ad_kconi(), addr, assert, ILTB::callfg, CC_EQ, CHARLEN_64BIT, chk_block(), _str::cnt, CONVAL2G, DTY, ERR_Severe, exp_strcpy(), exp_strx(), FLANG_FALLTHROUGH, ftn_strcmp(), get_isz_cval(), getcharconst(), getchartmp(), getcon(), getstr(), getstraddr(), getstrconst(), IL_AADD, IL_IADD, IL_IMUL, IL_ISUB, IL_RES, IL_TYPE, ILI_OF, ILI_OPC, ILI_OPND, ILIA_KR, ILM_CLEN, ILM_ISCHAR, ILM_MXLEN, ILM_OPND, ILM_RESTYPE, ILM_RESULT, iltb, ILTY_CONS, interr(), _str::liscon, _str::lval, MSZ_BYTE, MSZ_UHWORD, STB::n_base, _str::next, NME_STR1, NULL, sel_iconv(), stb, storechartmp(), strislen0(), strislen1(), tmp, TY_CHAR, and val.
Referenced by eval_ilm().
exp_header()
void exp_header (SPTR sym)
...
Expand entry, main, sub, or func. For an unnamed program, PROGRAM, SUBROUTINE, or FUNCTION, sym is 0; otherwise, sym is the ENTRY name.
Definition at line 327 of file exp_rte.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad_acon(), addilt(), addnme(), alloca_flag, allocharhdr, EXP::arglcnt, aux, BIH_EN, BIH_LABEL, BIH_LINENO, bihb, chk_block(), cr_block(), create_llvm_display_temp(), EXP::curbih, EXP::curilt, AUX::curr_entry, FLG::debug, ENTRY::display, ENTRY::ent_save, expb, flg, flsh_block(), gbl, GBL_CURRFUNC, EXP::gentmps, getccsym(), ili, ll_get_hostprog_arg(), ll_get_shared_arg(), EXP::max, memarg_var, mk_address(), mk_argasym(), mkrtemp_init(), mscall_flag, EXP::next, NT_IND, NT_VAR, BIHB::parfg, pp_entries(), pp_entries_mixedstrlen(), pp_params(), pp_params_mixedstrlen(), FLG::recursive, reg_init(), RU_PROG, smove_flag, FLG::smp, SPTR_NULL, EXP::start, sym_is_refd(), BIHB::taskfg, ENTRY::uplevel, WINNT_CALL, wr_block(), and XBIT.
Referenced by begin_entry().
exp_qjsr()
void exp_qjsr (const char * ext, DTYPE res_dtype, ILM * ilmp, int curilm)
...
Parameters
ext name of routine to call
res_dtype function return type
Generate a sequence of ili for the current ilm which is an "arithmetic". This sequence essentially looks like a normal call, except where we can, arguments are passed by value.
The requirements are:
The ilm looks like an "arithmetic" ILM where there's a fixed number of operands (determined by the ilms info).
The result is returned in a temporary.
The address of the result is the first argument in the call.
The operands are fully evaluated (no reference ilms).
Character arguments are not seen.
For now this only works for complex/double complex ILMs which are QJSRs in the "standard" fortran.
Definition at line 4561 of file exp_rte.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad_acon(), ad_aconi(), addnme(), arg_ar(), arg_dp(), arg_ir(), arg_kr(), arg_sp(), ILTB::callfg, chk_block(), DT_CMPLX, DT_ISCMPLX, end_ainfo(), ERR_Severe, expb, i, IL_AADD, IL_RES, ILI_OPC, ILIA_AR, ILIA_CD, ILIA_CQ, ILIA_CS, ILIA_DP, ILIA_IR, ILIA_KR, ILIA_SP, ILMB::ilm_base, ILM_IRESULT, ILM_ISCHAR, ILM_ISCMPLX, ILM_ISDCMPLX, ILM_ISQCMPLX, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_RRESULT, ilmb, ilms, iltb, init_ainfo(), interr(), ainfo_t::lnk, mkfunc(), mkrtemp_arg1_sc(), MSZ_F16, MSZ_F32, MSZ_F4, MSZ_F8, nargs, NOSYM, NT_MEM, NT_VAR, ILMINFO::oprs, res, EXP::sc, SPTR_NULL, and XBIT.
Referenced by exp_ac().
exp_remove_gsmove()
void exp_remove_gsmove (void)
...
...
Definition at line 4917 of file exp_rte.cpp.
exp_reset_argregs()
void exp_reset_argregs (int ir, int fr)
...
Parameters
ir number of integer regs used as arguments
fr number of floating point regs used as arguments
Perform the necessary adjustments regarding the number of argument registers used by a jsr/qsr added after the expand phase and before the optimizer (i.e., by the vectorizer). An argument to the current function must be stored in memory if it has been marked by expand as a register argument and if its register is used by the jsr/qjr. Also, the available set of arg/scratch registers that can be used as globals by the optimizer must be updated.
Definition at line 6051 of file exp_rte.cpp.
exp_szero()
void exp_szero (ILM * ilmp, int curilm, int to, int from, int dtype)
...
Parameters
to ilm of receiving struct/union
from ilm of sending struct/union
dtype data type of struct/union
Definition at line 5037 of file exp_rte.cpp.
References ad1ili(), ad2ili(), ad3ili(), addr, chk_block(), ILI_OF, loc_of(), mkfunc(), NME_OF, and tmp.
Referenced by exp_store().
exp_zqjsr()
void exp_zqjsr (char * ext, int res_dtype, ILM * ilmp, int curilm)
...
expand_smove()
void expand_smove (int destilm, int srcilm, DTYPE dtype)
...
Expand an smove ILM.
Parameters
destilm ilm of receiving struct/union
srcilm ilm of sending struct/union
dtype data type of struct/union
Definition at line 4890 of file exp_rte.cpp.
References _exp_smove(), ad5ili(), chk_block(), flg, ILI_OF, loc_of(), NME_OF, FLG::opt, and USE_GSMOVE.
Referenced by exp_store().
func_has_char_args()
bool func_has_char_args (SPTR func)
Checks to see if a procedure has character dummy arguments.
Parameters
func is the procedure we are checking.
Returns
true if the procedure has character dummy arguments, else false.
Definition at line 1325 of file exp_rte.cpp.
References aux, convertSPTR, AUX::dpdsc_base, DTYG, func, i, nargs, TY_CHAR, and TY_NCHAR.
Referenced by ll_process_routine_parameters(), print_entry_subroutine(), and process_end_of_list().
gen_arg_ili()
int gen_arg_ili (void)
...
Definition at line 2953 of file exp_rte.cpp.
References arg_charlen(), arg_entry, arg_ili, charargs, end_ainfo(), exp_call_sym, i, ili, arg_info::ili_arg, init_ainfo(), is_proc_desc_arg(), len_ili, ainfo_t::lnk, process_desc_args(), and put_arg_ili().
Referenced by exp_call().
getdumlen()
SPTR getdumlen (void)
...
Definition at line 1097 of file exp_rte.cpp.
References EXP::chardtmps, CHARLEN_64BIT, DT_INT, expb, and getccsym().
Referenced by _fixup_llvm_uplevel_symbol(), ll_process_routine_parameters(), pp_entries(), pp_entries_mixedstrlen(), print_entry_subroutine(), stb_process_iface_chlen(), and upper().
gethost_dumlen()
SPTR gethost_dumlen (int arg, ISZ_T address)
Create a symbol representing the length of a passed-length character argument in the host subprogram.
Definition at line 1112 of file exp_rte.cpp.
References arg, CHARLEN_64BIT, DT_INT, getccsym(), and pop_sym().
Referenced by _fixup_llvm_uplevel_symbol(), and restore_saved_syminfo().
init_arg_ili()
void init_arg_ili (int n)
...
Definition at line 2828 of file exp_rte.cpp.
References arg_entry, arg_ili, BZERO, charargs, garg_ili, len_ili, n, NEW, and XBIT.
Referenced by exp_call().
is_passbyval_dummy()
int is_passbyval_dummy (int sptr)
...
Definition at line 226 of file exp_rte.cpp.
References BYVALDEFAULT, GBL_CURRFUNC, and sptr.
Referenced by sym_is_refd().
needlen()
int needlen (int sym, int func)
...
Definition at line 241 of file exp_rte.cpp.
References func.
Referenced by pp_entries(), pp_entries_mixedstrlen(), pp_params_mixedstrlen(), and process_end_of_list().