flang: exp_common.h File Reference
exp_common.h File Reference
#include "math_common.h"
#include "sleef_common.h"
Macros
#define L2E 1.4426950408889634e+0f
#define LN2_0 0x1.62E43p-01
#define LN2_1 -0x1.05C61p-29
#define EXP_C0 I2F(0x3f800000)
#define EXP_C1 I2F(0x3f800000)
#define EXP_C2 I2F(0x3effffff)
#define EXP_C3 I2F(0x3e2aaa57)
#define EXP_C4 I2F(0x3d2aab8d)
#define EXP_C5 I2F(0x3c091474)
#define EXP_C6 I2F(0x3ab5b798)
#define EXP_HI (128.0f * logf(2.0f))
Functions
static INLINE float __exp_poly (float z)
static INLINE void __exp_scalar_kernel (float a, float *poly, int *scale)
static vfloat INLINE __vexp_poly (vfloat z)
static void INLINE __vexp_kernel (vfloat vx, vfloat *vpoly, vfloat *vscale)
Macro Definition Documentation
EXP_C0
#define EXP_C0 I2F(0x3f800000)
Definition at line 17 of file exp_common.h.
EXP_C1
#define EXP_C1 I2F(0x3f800000)
Definition at line 18 of file exp_common.h.
EXP_C2
#define EXP_C2 I2F(0x3effffff)
Definition at line 19 of file exp_common.h.
EXP_C3
#define EXP_C3 I2F(0x3e2aaa57)
Definition at line 20 of file exp_common.h.
EXP_C4
#define EXP_C4 I2F(0x3d2aab8d)
Definition at line 21 of file exp_common.h.
EXP_C5
#define EXP_C5 I2F(0x3c091474)
Definition at line 22 of file exp_common.h.
EXP_C6
#define EXP_C6 I2F(0x3ab5b798)
Definition at line 23 of file exp_common.h.
EXP_HI
#define EXP_HI (128.0f * logf(2.0f))
L2E
#define L2E 1.4426950408889634e+0f
Definition at line 12 of file exp_common.h.
LN2_0
#define LN2_0 0x1.62E43p-01
Definition at line 13 of file exp_common.h.
LN2_1
#define LN2_1 -0x1.05C61p-29
Definition at line 14 of file exp_common.h.
Function Documentation
__exp_poly()
static INLINE float __exp_poly (float z) static
Definition at line 26 of file exp_common.h.
References EXP_C0, EXP_C1, EXP_C2, EXP_C3, EXP_C4, EXP_C5, EXP_C6, EXP_C7, fmaf(), and z.
Referenced by __exp_scalar_kernel().
__exp_scalar_kernel()
static INLINE void __exp_scalar_kernel (float a, float * poly, int * scale) static
Definition at line 51 of file exp_common.h.
References __exp_poly(), a, exp, EXP_HI, F2I(), fmaf(), I2F(), L2E, LN2_0, LN2_1, poly, scale, t, and z.
__vexp_kernel()
static void INLINE __vexp_kernel (vfloat vx, vfloat * vpoly, vfloat * vscale) static
Definition at line 117 of file exp_common.h.
References __vexp_poly(), EXP_HI, L2E, LN2_0, LN2_1, PRINT, t, vF2I, vfma_vf_vf_vf_vf(), vgt_vo_vf_vf(), vI2F, vle_vo_vf_vf(), vmul_vf_vf_vf(), vsel_vf_vo_vf_vf(), vSETf, vSETi, vsll_vi2_vi2_i(), vsra_vi2_vi2_i(), vsub_vf_vf_vf(), vsub_vi2_vi2_vi2(), and z.
Referenced by cexpf_vec().
__vexp_poly()
static vfloat INLINE __vexp_poly (vfloat z) static
Definition at line 104 of file exp_common.h.
References EXP_C0, EXP_C1, EXP_C2, EXP_C3, EXP_C4, EXP_C5, EXP_C6, vfma_vf_vf_vf_vf(), vSETf, and z.
Referenced by __vexp_kernel().