flang: exp_ftn.h File Reference
exp_ftn.h File Reference
#include "gbldefs.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "expand.h"
Functions
int create_array_ref (int nmex, SPTR sptr, DTYPE dtype, int nsubs, int *subs, int ilix, int sdscilix, int inline_flag, int *pnme)
...
int exp_get_sdsc_len (int s, int base, int basenm)
...
int get_sdsc_element (SPTR sdsc, int indx, int membase, int membase_nme)
...
SPTR frte_func (SPTR(*pf)(const char *), const char *root)
...
void exp_ac (ILM_OP opc, ILM *ilmp, int curilm)
...
void exp_array (ILM_OP opc, ILM *ilmp, int curilm)
...
void exp_bran (ILM_OP opc, ILM *ilmp, int curilm)
...
void exp_misc (ILM_OP opc, ILM *ilmp, int curilm)
...
void exp_restore_mxcsr (void)
...
Function Documentation
create_array_ref()
int create_array_ref (int nmex, SPTR sptr, DTYPE dtype, int nsubs, int * subs, int ilix, int sdscilix, int inline_flag, int * pnme)
...
Definition at line 3420 of file exp_ftn.cpp.
References ad1ili(), ad2ili(), ad3ili(), AD_DPTR, AD_SDSC, ad_val_of(), add_arrnme(), base, create_array_subscr(), create_sdsc_subscr(), i, ikmove(), IL_AADD, IL_ASUB, IL_IMUL, IL_ISUB, IL_RES, IL_TYPE, ILI_OPC, ILI_OPND, ILIA_KR, ILTY_CONS, kimove(), NME_NULL, nsubs, NT_ARR, sptr, SPTR_NULL, sub, subscr, and XBIT.
Referenced by exp_array().
exp_ac()
void exp_ac (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 118 of file exp_ftn.cpp.
References ad1ili(), ad2func_kint(), ad2ili(), ad3ili(), ad_aconi(), ad_icon, AR_RETVAL, arg, assert, basesym_of(), bihb, CC_EQ, CONVAL2G, STB::dbl0, DP, DP_RETVAL, DT_CMPLX, DT_CPTR, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, DT_LOG, DT_REAL, ERR_Severe, exp_alloca(), exp_mac(), exp_qjsr(), flg, STB::flt0, forceK(), gbl, get_acon(), getcon(), FLG::ieee, IL_IADD, IL_IDIV, IL_IMUL, IL_INEG, IL_ISUB, IL_RES, ILI_OF, ILI_OPC, ILI_OPND, ILI_SymOPND, ILIA_AR, ILIA_IR, ILIA_KR, ILMB::ilm_base, ILM_IRESULT, ILM_ISCHAR, ILM_ISCMPLX, ILM_ISDCMPLX, ILM_ISQCMPLX, ILM_NME, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_RRESULT, ILM_SymOPND, ilmb, interr(), is_creal_flt0(), is_dbl0(), is_flt0(), is_ishft(), ishft, kimove(), RCANDB::kr, KR_RETVAL, loc_of(), mk_prototype, mkfunc(), mkRteRtnNm(), MTH_I_DFLOATK, MTH_I_FIXK, MTH_I_FLOATK, MTH_I_KBCLR, MTH_I_KBITS, MTH_I_KBSET, MTH_I_KBTEST, NME_OF, NME_UNK, BIHB::parfg, STB::quad0, r, rcandb, relaxed_math(), RTE_auto_allocv, s, SetILM_OPC, SINGLE_COMPLEX_OP, size_of(), SP, sptr, SPTR_NULL, stb, SymConval1, BIHB::taskfg, tmp, val, void(), XBIT, and XBIT_NEW_MATH_NAMES_CMPLX.
exp_array()
void exp_array (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 3061 of file exp_ftn.cpp.
References AD_DPTR, AD_SDSC, assert, compute_sdsc_subscr(), compute_subscr(), create_array_ref(), DTY, DTySeqTyElement, ERR_Severe, finish_array(), i, ILI_OF, ILMB::ilm_base, ILM_CLEN, ILM_DTyOPND, ILM_ISCHAR, ILM_MXLEN, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_SymOPND, ilmb, inlarr(), kanji_divide(), kimove(), NME_OF, ORIGDUMMYG, subscr, TY_CHAR, TY_NCHAR, and XBIT.
Referenced by exp_ref().
exp_bran()
void exp_bran (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 3528 of file exp_ftn.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_acon(), addnme(), BR_TRUE, CC_EQ, CC_GE, CC_LE, CC_LT, CC_NE, chk_block(), DT_DBLE, DT_INT, DT_REAL, exp_agoto(), exp_cgoto(), exp_mac(), expb, flg, Get_expb_logcjmp, i, IL_ISUB, IL_RES, ILI_OPC, ILI_OPND, ILIA_KR, ILMB::ilm_base, ILM_OPC, ILM_OPND, ILM_RESULT, ILM_SymOPND, ilmb, ilms, load, mkrtemp_sc(), msz, MSZ_F16, MSZ_F2, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_WORD, NT_VAR, FLG::opt, RFCNTD, EXP::sc, simple_ili(), type, and XBIT.
Referenced by eval_ilm().
exp_get_sdsc_len()
int exp_get_sdsc_len (int s, int base, int basenm)
...
Definition at line 4595 of file exp_ftn.cpp.
References ad1ili(), assert, base, basenm, DDTG, ERR_Severe, get_sdsc_element(), IL_RES, ILI_OPC, ILIA_KR, kimove(), len, s, and XBIT.
Referenced by compute_sdsc_subscr(), create_array_subscr(), create_ref(), create_sdsc_subscr(), exp_load(), and inlarr().
exp_misc()
void exp_misc (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 3771 of file exp_ftn.cpp.
References ACC_DATAMOVEMENT_DISABLED, accreduct_op, ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_icon, ad_kconi(), addnme(), ADDRCAND, arg, ARG_IR, EXP::arglcnt, assert, begin_entry(), BIH_DOCONC, BIH_ENLAB, BIH_GUARDEE, BIH_GUARDER, BIH_HEAD, BIH_LABEL, BIH_LINENO, BIH_NOMERGE, BIH_ZTRP, bihb, EXP::bits, BOS_SIZE, CC_GT, CC_LE, CC_NE, chk_block(), CNULL, cr_block(), EXP::curbih, EXP::curilt, EXP::curlin, FIHB::currfindex, FIHB::currftag, entry_sptr, ERR_Severe, error(), exp_end(), exp_estmt(), exp_label(), expb, fihb, EXP::flags, FLANG_FALLTHROUGH, flg, flsh_block(), gbl, get_atomic_capture_created(), get_atomic_store_created(), get_capture_read_ili(), get_capture_update_ili(), get_is_in_atomic_capture(), getccsym(), getsym(), STB::i1, IL_ISUB, IL_TYPE, ILI_OF, ILI_OPC, ILMB::ilm_base, ILM_CLEN, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_SymOPND, EXP::ilm_thresh, EXP::ilm_words, ilmb, ILT_NEXT, ILTY_CONS, IM_TYPE, IMTY_CONS, interr(), EXP::isguarded, STB::k1, mk_address(), mkrtemp_init(), MSZ_I8, MSZ_WORD, EXP::next, FIHB::nextfindex, FIHB::nextftag, EXP::nilms, NME_OF, EXP::noblock, EXP::noheader, NT_VAR, FLG::onetrip, FLG::opt, BIHB::parfg, PR_ACCASYNC, PR_ACCAUTO, PR_ACCBEGINDIR, PR_ACCCACHEDIR, PR_ACCCACHEREADONLY, PR_ACCCOLLAPSE, PR_ACCDATAREG, PR_ACCDEFNONE, PR_ACCDEFPRESENT, PR_ACCDEVICEID, PR_ACCEL, PR_ACCELLP, PR_ACCENDDATAREG, PR_ACCENDHOSTDATA, PR_ACCENDIMPDATAREG, PR_ACCENDKERNELS, PR_ACCENDPARCONSTRUCT, PR_ACCENDSCALARREG, PR_ACCENDSERIAL, PR_ACCENTERDATA, PR_ACCEXITDATA, PR_ACCFINALEXITDATA, PR_ACCFORCECOLLAPSE, PR_ACCGANG, PR_ACCGANGCHUNK, PR_ACCGANGDIM, PR_ACCHOST, PR_ACCHOSTDATA, PR_ACCIF, PR_ACCIMPDATAREG, PR_ACCIMPDATAREGX, PR_ACCINDEPENDENT, PR_ACCKERNEL, PR_ACCKERNELS, PR_ACCKLOOP, PR_ACCNOWAIT, PR_ACCNUMGANGS, PR_ACCNUMGANGS2, PR_ACCNUMGANGS3, PR_ACCNUMWORKERS, PR_ACCPARALLEL, PR_ACCPARCONSTRUCT, PR_ACCPARUNROLL, PR_ACCPLOOP, PR_ACCREDUCTOP, PR_ACCSCALARREG, PR_ACCSEQ, PR_ACCSEQUNROLL, PR_ACCSERIAL, PR_ACCSHORTLOOP, PR_ACCSLOOP, PR_ACCTKLOOP, PR_ACCTPLOOP, PR_ACCTSLOOP, PR_ACCUNROLL, PR_ACCUPDATE, PR_ACCVECTOR, PR_ACCVECUNROLL, PR_ACCVLENGTH, PR_ACCWAIT, PR_ACCWAITARG, PR_ACCWAITDIR, PR_ACCWORKER, PR_ENDACCEL, PR_ENDKERNEL, PR_KERNEL, PR_KERNEL_BLOCK, PR_KERNEL_DEVICE, PR_KERNEL_GRID, PR_KERNEL_NEST, PR_KERNEL_STREAM, PR_KERNELBEGIN, PR_PCASTCOMPARE, EXP::retcnt, EXP::retlbl, RFCNTD, RFCNTI, s, set_atomic_capture_created(), set_atomic_store_created(), set_capture_read_ili(), set_capture_update_ili(), set_is_in_atomic(), set_is_in_atomic_capture(), set_is_in_atomic_read(), set_is_in_atomic_write(), SPTR_NULL, EXP::start, stb, store_aret(), strlen(), SYMNAME, BIHB::taskfg, tmp, vf_addr, EXP::waitlbl, wr_block(), and XBIT.
Referenced by eval_ilm().
exp_restore_mxcsr()
void exp_restore_mxcsr (void)
...
Definition at line 4553 of file exp_ftn.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad_acon(), addnme(), addr, arg, ILTB::callfg, chk_block(), expb, gbl, iltb, mkfunc(), MSZ_WORD, EXP::mxcsr_tmp, NT_VAR, and tmp.
Referenced by exp_end().
frte_func()
SPTR frte_func (SPTR(*)(const char *) pf, const char * root)
...
Definition at line 4622 of file exp_ftn.cpp.
References assert, ERR_Severe, p, root, and strlen().
Referenced by allochartmp(), exp_end(), exp_strcpy(), and exp_strx().
get_sdsc_element()
int get_sdsc_element (SPTR sdsc, int indx, int membase, int membase_nme)
...
Definition at line 2184 of file exp_ftn.cpp.
References ad2ili(), ad3ili(), ad_aconi(), addnme(), ADDRCAND, compute_nme(), DTYG, elmsz, ERR_Fatal, STB::i1, IL_AADD, ili, interr(), is_currsub_dummy(), IS_THREAD_TP, STB::k1, mk_address(), mk_argasym(), MSZ_I8, MSZ_WORD, NT_VAR, ref_threadprivate(), ref_threadprivate_var(), scale, scale_of(), stb, and XBIT.
Referenced by add_ptr_subscript(), compute_sdsc_subscr(), create_sdsc_subscr(), exp_get_sdsc_len(), and inlarr().