flang: expand.cpp File Reference
expand.cpp File Reference
Common expander routines.
#include "expand.h"
#include "exputil.h"
#include "exp_ftn.h"
#include "expatomics.h"
#include "expreg.h"
#include "expsmp.h"
#include "error.h"
#include "regutil.h"
#include "machreg.h"
#include "fih.h"
#include "ilmtp.h"
#include "ilm.h"
#include "ili.h"
#include "machar.h"
#include "scope.h"
#include "llassem.h"
#include "outliner.h"
#include "verify.h"
#include "ccffinfo.h"
#include "ilidir.h"
#include "exp_rte.h"
#include "dtypeutl.h"
#include "symfun.h"
Macros
#define EXPANDER_DECLARE_INTERNAL
#define DO_PFO ((XBIT(148, 0x1000) && !XBIT(148, 0x4000)) || XBIT(148, 1))
#define CHECK_NME(nme, cond)
#define SET_ASSN(n) set_assn(n)
#define EXP_ISFUNC(s) (STYPEG(s) == ST_PROC)
#define EXP_ISINDIR(s) (SCG(s) == SC_DUMMY)
#define MAX_PUREARGS 2
Functions
static int efunc (const char *)
static int create_ref (SPTR sym, int *pnmex, int basenm, int baseilix, int *pclen, int *pmxlen, int *prestype)
static int jsr2qjsr (int)
void ds_init (void)
...
void exp_init (void)
...
void exp_cleanup (void)
...
static void parse_im_file (const ILM *ilmp, int *lineno_out, int *findex_out, int *ftag_out)
int expand (void)
Expand ILMs to ILIs.
static void eval_ilm_argument1 (int opr, ILM *ilmpx, int ilmx)
void eval_ilm (int ilmx)
...
void exp_estmt (int ilix)
...
static void exp_scope_label (int lbl)
void exp_label (SPTR lbl)
...
static int SCALAR_SIZE (DTYPE dtype, int n)
int optional_missing (int nme)
...
int optional_missing_ilm (ILM *ilmpin)
...
void replace_by_zero (ILM_OP opc, ILM *ilmp, int curilm)
...
int optional_present (int nme)
...
void replace_by_one (ILM_OP opc, ILM *ilmp, int curilm)
...
void exp_load (ILM_OP opc, ILM *ilmp, int curilm)
...
void set_assn (int nme)
...
void exp_store (ILM_OP opc, ILM *ilmp, int curilm)
...
int exp_mac (ILM_OP opc, ILM *ilmp, int curilm)
...
void exp_ref (ILM_OP opc, ILM *ilmp, int curilm)
...
static int update_local_nme (int nme, int sptr)
void ll_set_new_threadprivate (int oldsptr)
...
int llGetThreadprivateAddr (int sptr)
...
int getThreadPrivateTp (int sptr)
...
void ref_threadprivate (int cmsym, int *addr, int *nm)
Have a reference to a member of a threadprivate common.
void ref_threadprivate_var (int cmsym, int *addr, int *nm, int mark)
Have a reference to a Fortran or C threadprivate variable.
void exp_pure (SPTR extsym, int nargs, ILM *ilmp, int curilm)
...
Variables
int in_extract_inline
Detailed Description
Common expander routines.
Definition in file expand.cpp.
Macro Definition Documentation
CHECK_NME
#define CHECK_NME (nme, cond)
Value:
  {                                                                  \
    NT_KIND i = NME_TYPE(nme);                                       \
    if (NME_SYM(nme) == 0 && (i == NT_ARR || i == NT_IND) && (cond)) \
      nme = add_arrnme(i, NME_NULL, NME_NM(nme), 0, NME_SUB(nme),    \
                       NME_INLARR(nme));                             \
  }
Definition at line 888 of file expand.cpp.
DO_PFO
#define DO_PFO ((XBIT(148, 0x1000) && !XBIT(148, 0x4000)) || XBIT(148, 1))
Definition at line 50 of file expand.cpp.
EXP_ISFUNC
#define EXP_ISFUNC (s) (STYPEG(s) == ST_PROC)
Definition at line 2392 of file expand.cpp.
EXP_ISINDIR
#define EXP_ISINDIR (s) (SCG(s) == SC_DUMMY)
Definition at line 2393 of file expand.cpp.
EXPANDER_DECLARE_INTERNAL
#define EXPANDER_DECLARE_INTERNAL
Definition at line 12 of file expand.cpp.
MAX_PUREARGS
#define MAX_PUREARGS 2
SET_ASSN
#define SET_ASSN (n) set_assn(n)
Definition at line 1407 of file expand.cpp.
Function Documentation
create_ref()
static int create_ref (SPTR sym, int * pnmex, int basenm, int baseilix, int * pclen, int * pmxlen, int * prestype) static
Definition at line 2466 of file expand.cpp.
References ad2ili(), ad3ili(), ad_acon(), ad_aconi(), ad_icon, addnme(), ADDRCAND, assert, basenm, charaddr(), charlen(), DTY, DTyCharLength, DTySeqTyElement, ERR_Severe, exp_get_sdsc_len(), EXP_ISFUNC, EXP_ISINDIR, flg, gbl, GBL_CURRFUNC, getccsym(), IL_AADD, ILI_OPND, ILM_ISCHAR, IS_LCL, IS_STATIC, IS_THREAD_TP, ISZ_T, mk_address(), mk_argasym(), NME_UNK, NME_VOL, NT_IND, NT_MEM, NT_VAR, rcandb, FLG::recursive, ref_threadprivate(), ref_threadprivate_var(), s, FLG::smp, SPTR_NULL, RCANDB::static_cnt, sym_is_refd(), TY_CHAR, TY_NCHAR, update_local_nme(), val, and XBIT.
Referenced by exp_ref().
ds_init()
void ds_init (void)
...
Definition at line 58 of file expand.cpp.
References bih_init(), BZERO, EXP_ALLOC, i, ili_init(), ilt_init(), RCANDB::kr, nme_init(), ratb, rcandb, rgsetb, RGSETB::stg_avail, RATB::stg_avail, RCANDB::stg_avail, RGSETB::stg_base, RCANDB::stg_base, and RCANDB::weight.
Referenced by exp_init().
efunc()
static int efunc (const char * nm) static
Definition at line 2329 of file expand.cpp.
References DT_DBLE, DT_FLOAT, DT_INT, ERR_Severe, func, interr(), mkfunc(), and p.
Referenced by exp_mac().
eval_ilm()
void eval_ilm (int ilmx)
...
< ILM opcode of the ILM
Definition at line 437 of file expand.cpp.
References ILTB::callfg, check_ilm(), chk_block(), ERR_Severe, eval_ilm_argument1(), exp_ac, exp_bran(), exp_call(), exp_fstring(), exp_load(), exp_mac(), exp_misc(), exp_ompaccel_reduction(), exp_ref(), exp_smp(), exp_store(), EXPDBG, flg, gbl, ILI_OF, ILMB::ilm_base, ILM_EXPANDED_FOR, ILM_IRESULT, ILM_ISCMPLX, ILM_ISDCMPLX, ILM_ISFLOAT128CMPLX, ILM_ISI8, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_RRESULT, ilmb, ilms, iltb, IM_I8, IM_OPRFLAG, IM_SPEC, IM_TYPE, IM_VAR, IMTY_ARTH, IMTY_BRANCH, IMTY_CONS, IMTY_FSTR, IMTY_INTR, IMTY_LOAD, IMTY_MISC, IMTY_PROC, IMTY_REF, IMTY_SMP, IMTY_STORE, interr(), ll_ilm_is_rewriting(), ll_make_tgt_register_lib2(), ll_rewrite_ilms(), ILMINFO::name, ompaccel_is_tgt_registered(), ompaccel_nvvm_get(), ompaccel_register_tgt(), FLG::omptarget, OPR_LNK, ILMINFO::oprs, FLG::smp, threadIdX, tmp, and XBIT.
Referenced by eval_fvec(), eval_ilm_argument1(), expand(), replace_by_one(), and replace_by_zero().
eval_ilm_argument1()
static void eval_ilm_argument1 (int opr, ILM * ilmpx, int ilmx) static
Definition at line 419 of file expand.cpp.
References eval_ilm(), ILI_OF, ILI_OPC, ILM_EXPANDED_FOR, ILM_OPND, and is_cseili_opcode().
Referenced by eval_ilm().
exp_cleanup()
void exp_cleanup (void)
...
Definition at line 145 of file expand.cpp.
References EXP_FREE, NULL, ratb, rcandb, rgsetb, RGSETB::stg_base, RATB::stg_base, and RCANDB::stg_base.
exp_estmt()
void exp_estmt (int ilix)
...
Definition at line 664 of file expand.cpp.
References ad1ili(), ad_free(), ILTB::callfg, chk_block(), exp_estmt(), i, IL_HAS_FENCE, IL_ISLINK, IL_TYPE, ILI_OPC, ILI_OPND, ilis, iltb, ILTY_PROC, and ILIINFO::oprs.
Referenced by exp_estmt(), and exp_misc().
exp_init()
void exp_init (void)
...
Definition at line 84 of file expand.cpp.
References aux, EXP::bits, CHARLEN_64BIT, EXP::charlen_dtype, EXP::clobber_ir, EXP::clobber_pr, EXP::curbih, EXP::curilt, AUX::curr_entry, ENTRY::display, ds_init(), DT_INT, EXP::excstat, EXP_ALLOC, exp_smp_init(), expb, EXP::flags, flg, EXP::gentmps, EXP::ilm_thresh, EXP::ilmb, EXP::isguarded, EXP::logcjmp, NEW, EXP::noblock, EXP::noheader, FLG::opt, rewindilms(), EXP::sc, SC_AUTO, SPTR_NULL, EXP::str_avail, EXP::str_base, EXP::str_size, FLG::vect, EXP::wd, FLG::x, XBIT, FLG::xoff, and FLG::xon.
Referenced by expand().
exp_label()
void exp_label (SPTR lbl)
...
Definition at line 761 of file expand.cpp.
References addilt(), BIH_LABEL, EXP::bits, CNULL, compl_br(), cr_block(), EXP::curbih, EXP::curilt, FIHB::currfindex, FIHB::currftag, DBGBIT, ERR_Informational, errlabel(), exp_scope_label(), expb, EXPDBG, fihb, EXP::flags, flg, gbl, ILI_OPC, ILI_OPND, ilis, ILT_BR, ILT_DBGLINE, ILT_ILIP, ILT_NEXT, ILT_PREV, iltb, is_scope_label(), FIHB::nextfindex, FIHB::nextftag, FLG::opt, reduce_ilt(), RFCNTD, EXP::saveili, STG_ADD_FREELIST, SYMNAME, EXP::waitlbl, wr_block(), and XBIT.
Referenced by exp_agoto(), exp_end(), exp_misc(), exp_smp(), genswitch(), and section_create_endblock().
exp_load()
void exp_load (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 1092 of file expand.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad_aconi(), ad_icon, ad_kconi(), add_arrnme(), addnme(), addr, ADDRCAND, assert, base, CHARLEN_64BIT, CHECK_NME, DDTG, dt, DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, DT_ISBASIC, DT_ISSCALAR, dt_nme(), DTY, DTyCharLength, DTySeqTyElement, FLG::endian, ERR_Severe, exp_get_sdsc_len(), flg, IL_AADD, ili, ILI_OF, ILMB::ilm_base, ILM_CLEN, ILM_IRESULT, ILM_ISCHAR, ILM_ISCMPLX, ILM_ISDCMPLX, ILM_ISFLOAT128CMPLX, ILM_ISQCMPLX, ILM_MXLEN, ILM_NME, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_RRESULT, ILM_SymOPND, ilmb, interr(), RCANDB::kr, load, mk_address(), MSZ_F16, MSZ_F32, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_SBYTE, MSZ_SHWORD, MSZ_WORD, NME_INLARR, NME_OF, NME_SYM, NME_TYPE, NOSYM, NT_ARR, NT_IND, NT_MEM, NT_VAR, optional_missing_ilm(), rcandb, replace_by_zero(), SCALAR_SIZE(), size_of(), SPTR_NULL, tmp, TY_CHAR, TY_NCHAR, TY_QUAD, and XBIT.
Referenced by eval_ilm().
exp_mac()
int exp_mac (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 2015 of file expand.cpp.
References addili(), AR_RETVAL, atoxd(), atoxf(), atoxi(), atoxi64(), ILMOPND::aux, DP, DP_RETVAL, DT_DBLE, DT_FLOAT, DT_INT, efunc(), ERR_Severe, for(), getcon(), i, IDP, ILMINFO::ilict, ilis, ILM_DTyOPND, ILM_IRESULT, ILM_ISCMPLX, ILM_ISDCMPLX, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_RRESULT, ILM_TEMP, ilmaux, ILMO__ESYM, ILMO_AR, ILMO_ARPOS, ILMO_ARRET, ILMO_DP, ILMO_DPPOS, ILMO_DPRET, ILMO_DR, ILMO_DRPOS, ILMO_DRRET, ILMO_DSYM, ILMO_ESYM, ILMO_IDP, ILMO_IP, ILMO_IR, ILMO_ISP, ILMO_ISYM, ILMO_IV, ILMO_KR, ILMO_KRRET, ILMO_LLSYM, ILMO_NULL, ILMO_P, ILMO_QPRET, ILMO_R, ILMO_RP, ILMO_RR, ILMO_RSYM, ILMO_SCF, ILMO_SCZ, ILMO_SP, ILMO_SPPOS, ILMO_SPRET, ILMO_SZ, ILMO_T, ILMO_V, ILMO_XDSYM, ILMO_XRSYM, ilmopnd, ilms, ilmtp, IM_DCPLX, index, interr(), IR, IR_RETVAL, ISP, KR_RETVAL, len, num, ILI::opc, ILMMAC::opc, ILMMAC::opnd, ILI::opnd, ILIINFO::oprs, p, ILMINFO::pattern, QP_RETVAL, ILMMAC::result, scale_of(), size_of(), SP, SP_RETVAL, strlen(), and ILMOPND::type.
Referenced by eval_ilm(), exp_ac(), and exp_bran().
exp_pure()
void exp_pure (SPTR extsym, int nargs, ILM * ilmp, int curilm)
...
Definition at line 2910 of file expand.cpp.
References ad2ili(), ad3ili(), ad_acon(), args, i, IL_RES, ILI_OF, ILI_OPC, ILIA_AR, ILIA_IR, ILMB::ilm_base, ilm_callee_index(), ILM_OPC, ILM_OPND, ILM_RESULT, ilmb, jsr2qjsr(), MAX_PUREARGS, n, and nargs.
exp_ref()
void exp_ref (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 2398 of file expand.cpp.
References base, basenm, create_ref(), exp_array(), ILI_OF, ILM_CLEN, ILM_MXLEN, ILM_NME, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_SymOPND, and NME_OF.
Referenced by eval_ilm().
exp_scope_label()
static void exp_scope_label (int lbl) static
Definition at line 711 of file expand.cpp.
References ad1ili(), addilt(), assert, EXP::curbih, EXP::curilt, ERR_Severe, expb, GBL_CURRFUNC, ILI_OPC, ilt, ILT_ILIP, ILT_NEXT, and ILT_PREV.
Referenced by exp_label().
exp_store()
void exp_store (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 1410 of file expand.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_aconi(), ad_cse(), ad_icon, add_arrnme(), addnme(), addr, ADDRCAND, CHECK_NME, chk_block(), EXP::curbih, EXP::curilt, dt, DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, DT_ISSCALAR, dt_nme(), DTY, FLG::endian, ERR_Severe, exp_end_atomic(), exp_szero(), expand_smove(), expb, EXPDBG, FLANG_FALLTHROUGH, flg, gbl, IL_AADD, IL_RES, ILI_ALT, ili_get_vect_dtype(), ILI_OF, ILI_OPC, ILI_OPND, ILIA_AR, ILIA_CD, ILIA_CS, ILIA_DP, ILIA_FLOAT128, ILIA_IR, ILIA_KR, ILIA_LNK, ILIA_SP, ILMB::ilm_base, ILM_BLOCK, ILM_DTyOPND, ILM_IRESULT, ILM_ISCMPLX, ILM_ISDCMPLX, ILM_ISFLOAT128CMPLX, ILM_ISQCMPLX, ILM_NME, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ilm_return_slot_index(), ILM_RRESULT, ilmb, ILT_CPLX, interr(), RCANDB::kr, loc_of(), MSZ_F16, MSZ_F32, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_SBYTE, MSZ_SHWORD, MSZ_WORD, NME_INLARR, NME_OF, NME_SYM, NME_TYPE, NME_UNK, NOSYM, NT_ARR, NT_IND, NT_MEM, NT_VAR, optional_missing_ilm(), rcandb, SCALAR_SIZE(), SET_ASSN, size_of(), SPTR_NULL, tmp, TY_QUAD, and XBIT.
Referenced by eval_ilm().
expand()
int expand (void)
Expand ILMs to ILIs.
...
Definition at line 206 of file expand.cpp.
References BIH_EN, BIH_FTAG, BIH_NEXT, bihb, conflict(), EXP::curbih, FIHB::currfindex, FIHB::currftag, DBGBIT, DEBUG_ASSERT, dmpili(), dmpnme(), dump_blocks(), dumpilms(), eval_ilm(), EXP_FREE, exp_init(), EXP_MORE, exp_smp_fini(), expb, fihb, flg, FREE, freearea(), gbl, i, ili_lpprg_init(), ilib, ILMB::ilm_base, ILM_EXPANDED_FOR, ILM_NME, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ilmb, EXP::ilmb, ilms, iltb, IM_TRM, IM_VAR, is_scope_label(), j, len, ll_rewrite_ilms(), new_callee_scope, FIHB::nextfindex, FIHB::nextftag, EXP::nilms, nmeb, NULL, ILMINFO::oprs, FLG::opt, parse_im_file(), rcandb, rdilms(), set_allfiles(), share_proc_ili, FLG::smp, RCANDB::stg_base, EXP::stg_size, STR_AREA, verify_function_ili(), VERIFY_ILI_DEEP, void(), and XBIT.
getThreadPrivateTp()
int getThreadPrivateTp (int sptr)
...
Definition at line 2801 of file expand.cpp.
References sptr.
Referenced by handle_nested_threadprivate(), and loadUplevelArgsForRegion().
jsr2qjsr()
static int jsr2qjsr (int dfili) static
Definition at line 2996 of file expand.cpp.
References ad2ili(), assert, cl, ERR_unused, ILI_OPC, and ILI_OPND.
Referenced by exp_pure().
ll_set_new_threadprivate()
void ll_set_new_threadprivate (int oldsptr)
...
Definition at line 2763 of file expand.cpp.
References DT_CPTR, gbl, GBL_CURRFUNC, getnewccsym(), SC_AUTO, and stb.
Referenced by allocThreadprivate(), and llGetThreadprivateAddr().
llGetThreadprivateAddr()
int llGetThreadprivateAddr (int sptr)
...
Definition at line 2785 of file expand.cpp.
References ad2ili(), ad_acon(), addnme(), addr, basenm, ll_set_new_threadprivate(), NT_VAR, and sptr.
Referenced by addCopyinInplace(), handle_nested_threadprivate(), loadUplevelArgsForRegion(), ref_threadprivate(), and ref_threadprivate_var().
optional_missing()
int optional_missing (int nme)
...
Definition at line 914 of file expand.cpp.
References NME_SYM, sptr, and SYMNAME.
Referenced by exp_call().
optional_missing_ilm()
int optional_missing_ilm (ILM * ilmpin)
...
Definition at line 931 of file expand.cpp.
References ILMB::ilm_base, ILM_OPC, ILM_OPND, ilmb, sptr, and SYMNAME.
Referenced by exp_load(), and exp_store().
optional_present()
int optional_present (int nme)
...
Definition at line 1041 of file expand.cpp.
References NME_SYM, sptr, and SYMNAME.
Referenced by exp_call().
parse_im_file()
static void parse_im_file (const ILM * ilmp, int * lineno_out, int * findex_out, int * ftag_out) static
Definition at line 169 of file expand.cpp.
References assert, ERR_Fatal, ERR_Warning, fihb, IFIH_FINDEX, ifihb, ILM_OPC, ILM_OPND, lineno, and FIHB::stg_avail.
Referenced by expand().
ref_threadprivate()
void ref_threadprivate (int cmsym, int * addr, int * nm)
Have a reference to a member of a threadprivate common.
...
Generate an indirection using the threadprivate common's vector and then add the offset of this member. The actual address computation is: vector[_mp_lcpu3()] + offset(member)
Definition at line 2829 of file expand.cpp.
References ad2ili(), ad3ili(), ad_acon(), ad_aconi(), addnme(), addr, basenm, IL_AADD, llGetThreadprivateAddr(), NT_VAR, and XBIT.
Referenced by create_ref(), get_sdsc_element(), and makeCopyprivArray().
ref_threadprivate_var()
void ref_threadprivate_var (int cmsym, int * addr, int * nm, int mark)
Have a reference to a Fortran or C threadprivate variable.
...
Generate an indirection using the threadprivate's vector. The actual address computations is: vector[_mp_lcpu3()] mark : 1 - mark TPLNKP , and add it go gbl.threadprivate : this is normal processing. When calling this function later on, during exception fixup, call with mark = 0
Definition at line 2873 of file expand.cpp.
References ad2ili(), ad3ili(), ad_acon(), addnme(), addr, basenm, IL_AADD, llGetThreadprivateAddr(), NT_VAR, size_of(), SPTR_NULL, and XBIT.
Referenced by create_ref(), get_sdsc_element(), and makeCopyprivArray().
replace_by_one()
void replace_by_one (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 1066 of file expand.cpp.
References ERR_Severe, eval_ilm(), STB::i1, ILM_OPND, interr(), one, SetILM_OPC, and stb.
Referenced by exp_call().
replace_by_zero()
void replace_by_zero (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 965 of file expand.cpp.
References STB::dbl0, DT_CMPLX, DT_DCMPLX, ERR_Severe, eval_ilm(), STB::flt0, getcon(), STB::i0, ILM_OPND, interr(), STB::k0, num, SetILM_OPC, stb, and zero.
Referenced by exp_call(), and exp_load().
SCALAR_SIZE()
static int SCALAR_SIZE (DTYPE dtype, int n) static
Definition at line 897 of file expand.cpp.
References n, and size_of().
Referenced by exp_load(), and exp_store().
set_assn()
void set_assn (int nme)
...
Definition at line 1401 of file expand.cpp.
References basesym_of(), err_protected(), gbl, is_protected(), is_used_by_submod(), s, and sptr.
Referenced by exp_mp_atomic_capture(), exp_mp_atomic_update(), semant3(), and semantio().
update_local_nme()
static int update_local_nme (int nme, int sptr) static
Definition at line 2438 of file expand.cpp.
References addnme(), gbl, GBL_CURRFUNC, is_llvm_local_private(), NME_TYPE, NT_IND, sptr, and SPTR_NULL.
Referenced by create_ref().
Variable Documentation
in_extract_inline
int in_extract_inline extern