flang: expatomics.h File Reference
expatomics.h File Reference
#include "gbldefs.h"
#include "symtab.h"
#include "expand.h"
#include "ili.h"
Functions
bool exp_end_atomic (int store, int curilm)
...
ILI_OP get_atomic_update_opcode (int current_ili)
...
int create_atomic_capture_seq (int update_ili, int read_ili, int capture_first)
...
int create_atomic_read_seq (int store_ili)
...
int create_atomic_seq (int store_ili)
...
int create_atomic_write_seq (int store_ili)
...
int exp_mp_atomic_read (ILM *ilmp)
...
int get_atomic_capture_created (void)
...
int get_atomic_function_ex (ILI_OP opcode)
...
int get_atomic_function (ILI_OP opcode)
...
int get_atomic_read_opcode (int current_ili)
...
int get_atomic_store_created (void)
...
int get_atomic_write_opcode (int current_ili)
...
int get_capture_read_ili (void)
...
int get_capture_update_ili (void)
...
int get_is_in_atomic_capture (void)
...
int get_is_in_atomic_read (void)
...
int get_is_in_atomic (void)
...
int get_is_in_atomic_write (void)
...
void exp_mp_atomic_capture (ILM *ilmp)
...
void exp_mp_atomic_update (ILM *ilmp)
...
void exp_mp_atomic_write (ILM *ilmp)
...
void set_atomic_capture_created (int x)
...
void set_atomic_store_created (int x)
...
void set_capture_read_ili (int x)
...
void set_capture_update_ili (int x)
...
void set_is_in_atomic_capture (int x)
...
void set_is_in_atomic (int x)
...
void set_is_in_atomic_read (int x)
...
void set_is_in_atomic_write (int x)
...
Function Documentation
create_atomic_capture_seq()
int create_atomic_capture_seq (int update_ili, int read_ili, int capture_first)
...
Definition at line 619 of file expatomics.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), arg, ARG_IR, ARG_XR, DT_CPTR, DT_DBLE, DT_FLOAT, DT_INT, ERR_Severe, ERR_unused, FR_RETVAL, get_atomic_function(), ILI_ALT, ILI_OPC, ILI_OPND, interr(), IR_RETVAL, KR_RETVAL, result, and set_store_pt_addrtkn_flg().
Referenced by exp_end_atomic().
create_atomic_read_seq()
int create_atomic_read_seq (int store_ili)
...
Definition at line 934 of file expatomics.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), arg, ARG_IR, AtomicOp, DT_CPTR, get_atomic_function(), ILI_ALT, ILI_OPC, ILI_OPND, and set_store_pt_addrtkn_flg().
Referenced by exp_end_atomic().
create_atomic_seq()
int create_atomic_seq (int store_ili)
...
Definition at line 1300 of file expatomics.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), addcallarg(), arg, atomic_typecast_operand, AtomicOp, DT_CPTR, DT_DBLE, DT_FLOAT, DT_INT, ERR_Severe, gencallargs(), get_atomic_function(), get_atomic_function_ex(), IL_AADD, IL_ASUB, ili, ILI_ALT, ILI_OPC, ILI_OPND, initcallargs(), interr(), and is_atomic_typcast_h2l().
Referenced by exp_end_atomic().
create_atomic_write_seq()
int create_atomic_write_seq (int store_ili)
...
Definition at line 812 of file expatomics.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), arg, ARG_IR, ARG_XR, AtomicOp, DT_CPTR, DT_DBLE, DT_FLOAT, DT_INT, ERR_Severe, get_atomic_function(), ILI_ALT, ILI_OPC, ILI_OPND, interr(), and set_store_pt_addrtkn_flg().
Referenced by exp_end_atomic().
exp_end_atomic()
bool exp_end_atomic (int store, int curilm)
...
Definition at line 1480 of file expatomics.cpp.
References capture_read_ili, capture_update_ili, chk_block(), CNULL, create_atomic_capture_seq(), create_atomic_read_seq(), create_atomic_seq(), create_atomic_write_seq(), EXP::curbih, ERR_Severe, error(), expb, gbl, get_atomic_read_opcode(), get_atomic_store_created(), get_atomic_update_opcode(), get_atomic_write_opcode(), ILM_BLOCK, ILM_RESULT, is_in_atomic, is_in_atomic_capture, is_in_atomic_read, is_in_atomic_write, reset_atomic_typecast_h2l(), set_atomic_capture_created(), and set_atomic_store_created().
Referenced by exp_store().
exp_mp_atomic_capture()
void exp_mp_atomic_capture (ILM * ilmp)
...
Definition at line 3054 of file expatomics.cpp.
References _exp_mp_atomic_update(), ad3ili(), ad4ili(), ad5ili(), ad_icon, addnme(), AORG_OPENMP, atomic_encode_rmw(), OPCODES::atomicrmw, can_use_rmw(), chk_block(), cnt, CNULL, dt_nme(), DTY, ERR_Severe, error(), find_ili(), gbl, get_complex_update_operand(), get_dtype_from_ilm(), get_ops(), get_simple_update_operand(), GetAtomicOp, GetSPTRVal, ILI_OF, ILI_OPND, ILM_OPND, is_cse(), ld, ldst_msz(), lhs, LHS_IDX, load, load_op_match_lhs(), loc_of(), MAX_ATOMIC_ARGS, mem_size(), mk_address(), mkatomictemp(), MO_IDX, MO_SEQ_CST, msz, NME_OF, NOSYM, NT_VAR, result, rewr_cln_ili(), rewr_ili(), RHS_IDX, set_assn(), SS_PROCESS, st, and TMP_SPTR_IDX.
Referenced by exp_smp().
exp_mp_atomic_read()
int exp_mp_atomic_read (ILM * ilmp)
...
Definition at line 2505 of file expatomics.cpp.
References _exp_mp_atomic_read(), ad_icon, AORG_OPENMP, atomic_encode(), dt_nme(), get_dtype_from_ilm(), ILI_OF, ILM_OPND, ld, ldst_msz(), LHS_IDX, MAX_ATOMIC_ARGS, MO_IDX, MO_SEQ_CST, msz, NME_OF, SS_PROCESS, st, and TMP_SPTR_IDX.
Referenced by exp_smp().
exp_mp_atomic_update()
void exp_mp_atomic_update (ILM * ilmp)
...
Definition at line 2982 of file expatomics.cpp.
References _exp_mp_atomic_update(), ad4ili(), ad5ili(), ad_icon, addnme(), AORG_OPENMP, atomic_encode_rmw(), OPCODES::atomicrmw, can_use_rmw(), chk_block(), CNULL, cr_block(), dt_nme(), DTY, ERR_Severe, error(), gbl, get_complex_update_operand(), get_dtype_from_ilm(), get_ops(), get_simple_update_operand(), GetAtomicOp, GetSPTRVal, ILI_OF, ILI_OPND, ILM_OPND, is_cse(), ld, ldst_msz(), LHS_IDX, loc_of(), MAX_ATOMIC_ARGS, mem_size(), mk_address(), mkatomictemp(), MO_IDX, MO_SEQ_CST, msz, NME_OF, NT_VAR, result, RHS_IDX, set_assn(), SPTR_NULL, SS_PROCESS, st, TMP_SPTR_IDX, and wr_block().
Referenced by exp_smp().
exp_mp_atomic_write()
void exp_mp_atomic_write (ILM * ilmp)
...
Definition at line 2584 of file expatomics.cpp.
References _exp_mp_atomic_write(), ad_icon, AORG_OPENMP, atomic_encode(), dt_nme(), DTY, get_dtype_from_ilm(), ILI_OF, ILM_OPND, LHS_IDX, MAX_ATOMIC_ARGS, mem_size(), MO_IDX, MO_SEQ_CST, NME_OF, RHS_IDX, and SS_PROCESS.
Referenced by exp_smp().
get_atomic_capture_created()
int get_atomic_capture_created (void)
...
Definition at line 533 of file expatomics.cpp.
References atomic_capture_created.
Referenced by exp_misc().
get_atomic_function()
int get_atomic_function (ILI_OP opcode)
...
Definition at line 331 of file expatomics.cpp.
References DT_CPTR, DT_DBLE, DT_FLOAT, DT_INT, DT_VOID_NONE, ERR_Severe, IL_IADD, IL_IDIV, IL_IMUL, IL_INEG, IL_ISUB, interr(), and mk_prototype.
Referenced by create_atomic_capture_seq(), create_atomic_read_seq(), create_atomic_seq(), and create_atomic_write_seq().
get_atomic_function_ex()
int get_atomic_function_ex (ILI_OP opcode)
...
Definition at line 113 of file expatomics.cpp.
References atomic_typecast_operand, CNULL, DT_CPTR, DT_DBLE, DT_FLOAT, DT_INT, ERR_Severe, error(), gbl, is_atomic_operand1, and mk_prototype.
Referenced by create_atomic_seq().
get_atomic_read_opcode()
int get_atomic_read_opcode (int current_ili)
...
Definition at line 898 of file expatomics.cpp.
References AtomicOp, ili, ILI_OPC, and ILI_OPND.
Referenced by exp_end_atomic().
get_atomic_store_created()
int get_atomic_store_created (void)
...
Definition at line 545 of file expatomics.cpp.
References atomic_store_created.
Referenced by exp_end_atomic(), and exp_misc().
get_atomic_update_opcode()
ILI_OP get_atomic_update_opcode (int current_ili)
...
Definition at line 989 of file expatomics.cpp.
References assert, atomic_typecast_operand, AtomicOp, cmplx_atomic_opcodes, CNULL, double_atomic_opcodes, ERR_Fatal, ERR_Severe, error(), float_atomic_opcodes, gbl, ili, ILI_OPC, ILI_OPND, int_atomic_opcodes, interr(), is_atomic_operand1, long_atomic_opcodes, num_cmplx_opcodes, num_double_opcodes, num_float_opcodes, num_int_opcodes, num_long_opcodes, set_atomic_typecast_h2l(), and SYMNAME.
Referenced by exp_end_atomic().
get_atomic_write_opcode()
int get_atomic_write_opcode (int current_ili)
...
Definition at line 557 of file expatomics.cpp.
References AtomicOp, ili, ILI_OPC, and ILI_OPND.
Referenced by exp_end_atomic().
get_capture_read_ili()
int get_capture_read_ili (void)
...
Definition at line 461 of file expatomics.cpp.
References capture_read_ili.
Referenced by exp_misc().
get_capture_update_ili()
int get_capture_update_ili (void)
...
Definition at line 473 of file expatomics.cpp.
References capture_update_ili.
Referenced by exp_misc().
get_is_in_atomic()
int get_is_in_atomic (void)
...
Definition at line 485 of file expatomics.cpp.
References is_in_atomic.
get_is_in_atomic_capture()
int get_is_in_atomic_capture (void)
...
Definition at line 521 of file expatomics.cpp.
References is_in_atomic_capture.
Referenced by exp_misc().
get_is_in_atomic_read()
int get_is_in_atomic_read (void)
...
Definition at line 497 of file expatomics.cpp.
References is_in_atomic_read.
get_is_in_atomic_write()
int get_is_in_atomic_write (void)
...
Definition at line 509 of file expatomics.cpp.
References is_in_atomic_write.
set_atomic_capture_created()
void set_atomic_capture_created (int x)
...
Definition at line 539 of file expatomics.cpp.
References atomic_capture_created, and x.
Referenced by exp_end_atomic(), and exp_misc().
set_atomic_store_created()
void set_atomic_store_created (int x)
...
Definition at line 551 of file expatomics.cpp.
References atomic_store_created, and x.
Referenced by exp_end_atomic(), and exp_misc().
set_capture_read_ili()
void set_capture_read_ili (int x)
...
Definition at line 467 of file expatomics.cpp.
References capture_read_ili, and x.
Referenced by exp_misc().
set_capture_update_ili()
void set_capture_update_ili (int x)
...
Definition at line 479 of file expatomics.cpp.
References capture_update_ili, and x.
Referenced by exp_misc().
set_is_in_atomic()
void set_is_in_atomic (int x)
...
Definition at line 491 of file expatomics.cpp.
References is_in_atomic, and x.
Referenced by exp_misc().
set_is_in_atomic_capture()
void set_is_in_atomic_capture (int x)
...
Definition at line 527 of file expatomics.cpp.
References is_in_atomic_capture, and x.
Referenced by exp_misc().
set_is_in_atomic_read()
void set_is_in_atomic_read (int x)
...
Definition at line 503 of file expatomics.cpp.
References is_in_atomic_read, and x.
Referenced by exp_misc().
set_is_in_atomic_write()
void set_is_in_atomic_write (int x)
...
Definition at line 515 of file expatomics.cpp.
References is_in_atomic_write, and x.
Referenced by exp_misc().