flang: expatomics.cpp File Reference
expatomics.cpp File Reference
OpenMP/OpenACC/C++11 atomics expander routines; all targets including LLVM.
#include "expatomics.h"
#include "exputil.h"
#include "error.h"
#include "dtypeutl.h"
#include "regutil.h"
#include "machreg.h"
#include "ilmtp.h"
#include "ilm.h"
#include "ili.h"
#include "expand.h"
#include "machar.h"
#include "ccffinfo.h"
#include "pd.h"
#include "symfun.h"
Classes
struct OPCODES
struct auto_temp
Macros
#define EXPANDER_DECLARE_INTERNAL
#define GetAtomicOp(A) (A[AOP_IDX])
#define GetSPTRVal(A) (A[TMP_SPTR_IDX])
#define DT_VOID_NONE DT_NONE
#define TARGET_GNU_ATOMICS 1
#define EACH_SUBOP(s, t)
#define MAX_ATOMIC_ARGS 6
#define COMPARAND_INDEX 1
Typedefs
typedef enum MP_ATOMIC_IDX MP_ATOMIC_IDX
typedef enum ATOMIC_OP_CATEGORY ATOMIC_OP_CATEGORY
typedef struct OPCODES OPCODES
typedef struct auto_temp auto_temp
Enumerations
enum MP_ATOMIC_IDX {
LHS_IDX = 0 , RHS_IDX , MO_IDX , AOP_IDX ,
UNUSED1 , TMP_SPTR_IDX
}
enum ATOMIC_OP_CATEGORY {
AOC_LOAD , AOC_STORE , AOC_EXCHANGE , AOC_COMPARE_EXCHANGE ,
AOC_FETCH_OP , AOC_OP_FETCH , AOC_TEST_AND_SET , AOC_CLEAR ,
AOC_FENCE
}
Functions
int get_atomic_function_ex (ILI_OP opcode)
...
int get_atomic_function (ILI_OP opcode)
...
int get_capture_read_ili (void)
...
void set_capture_read_ili (int x)
...
int get_capture_update_ili (void)
...
void set_capture_update_ili (int x)
...
int get_is_in_atomic (void)
...
void set_is_in_atomic (int x)
...
int get_is_in_atomic_read (void)
...
void set_is_in_atomic_read (int x)
...
int get_is_in_atomic_write (void)
...
void set_is_in_atomic_write (int x)
...
int get_is_in_atomic_capture (void)
...
void set_is_in_atomic_capture (int x)
...
int get_atomic_capture_created (void)
...
void set_atomic_capture_created (int x)
...
int get_atomic_store_created (void)
...
void set_atomic_store_created (int x)
...
int get_atomic_write_opcode (int current_ili)
...
static void set_store_pt_addrtkn_flg (int store_pt)
int create_atomic_capture_seq (int update_ili, int read_ili, int capture_first)
...
int create_atomic_write_seq (int store_ili)
...
int get_atomic_read_opcode (int current_ili)
...
int create_atomic_read_seq (int store_ili)
...
static void set_atomic_typecast_h2l (int tcast_ili)
static void reset_atomic_typecast_h2l ()
static int is_atomic_typcast_h2l ()
ILI_OP get_atomic_update_opcode (int current_ili)
...
int create_atomic_seq (int store_ili)
...
bool exp_end_atomic (int store, int curilm)
...
static MSZ msz_from_atomic_dtype (DTYPE dtype)
static const OPCODES * get_ops (MSZ msz, int is_openmp)
static SPTR mkatomictemp (DTYPE dtype)
static int ll_make_atomic_load (int size_ili, int lhs, int rhs, int mem_order)
static int ll_make_atomic_store (int size_ili, int lhs, int rhs, int mem_order)
static int ll_make_atomic_compare_xchg (int size_ili, int lhs, int expected, int desired, int success, int failure)
static int _exp_mp_atomic_read (int stc, DTYPE dtype, int *opnd, int *nme)
static DTYPE get_dtype_from_ilm (ILM *ilmp)
int exp_mp_atomic_read (ILM *ilmp)
...
static void _exp_mp_atomic_write (int stc, DTYPE dtype, int *opnd, int *nme)
void exp_mp_atomic_write (ILM *ilmp)
...
static bool can_use_rmw (DTYPE dtype, ATOMIC_RMW_OP aop)
static bool is_cse (int ilix)
static int get_simple_update_operand (int *opnd, ILM *ilmp)
static bool lhs_match_rhs (int lop, int rop)
static void _ilis_are_matched (int rhs, int lhs, int *res, int *load)
static int load_op_match_lhs (int lhs, int rhs)
static int get_complex_update_operand (int *opnd, ILM *ilmp, int *nme, DTYPE dtype)
static void _exp_mp_atomic_update (DTYPE dtype, int *opnd, int *nme)
void exp_mp_atomic_update (ILM *ilmp)
...
void exp_mp_atomic_capture (ILM *ilmp)
...
Variables
static int atomic_capture_created
static int atomic_store_created
static int is_in_atomic
static int is_in_atomic_read
static int is_in_atomic_write
static int is_in_atomic_capture
static int capture_read_ili
static int capture_update_ili
static int atomic_typecast_operand
static int is_atomic_operand1 = 0
static int cmplx_atomic_opcodes [] = {IL_SCMPLXADD, IL_SCMPLXSUB}
static int num_cmplx_opcodes = sizeof(cmplx_atomic_opcodes) / sizeof(int)
static int float_atomic_opcodes []
static int num_float_opcodes = sizeof(float_atomic_opcodes) / sizeof(int)
static int double_atomic_opcodes []
static int num_double_opcodes = sizeof(double_atomic_opcodes) / sizeof(int)
static int int_atomic_opcodes []
static int num_int_opcodes = sizeof(int_atomic_opcodes) / sizeof(int)
static int long_atomic_opcodes []
static int num_long_opcodes = sizeof(long_atomic_opcodes) / sizeof(int)
struct {
int atomic_operand
int ldst_point
int ldst_nme
int ili_operand
} AtomicOp
Detailed Description
OpenMP/OpenACC/C++11 atomics expander routines; all targets including LLVM.
Definition in file expatomics.cpp.
Macro Definition Documentation
COMPARAND_INDEX
#define COMPARAND_INDEX 1
Definition at line 2088 of file expatomics.cpp.
DT_VOID_NONE
#define DT_VOID_NONE DT_NONE
EACH_SUBOP
#define EACH_SUBOP (s, t)
Value:
       s##_add_##t: \
  case s##_sub_##t: \
  case s##_and_##t: \
  case s##_or_##t: \
  case s##_xor_##t
Definition at line 1628 of file expatomics.cpp.
EXPANDER_DECLARE_INTERNAL
#define EXPANDER_DECLARE_INTERNAL
Definition at line 22 of file expatomics.cpp.
GetAtomicOp
#define GetAtomicOp (A) (A[AOP_IDX])
Definition at line 107 of file expatomics.cpp.
GetSPTRVal
#define GetSPTRVal (A) (A[TMP_SPTR_IDX])
Definition at line 108 of file expatomics.cpp.
MAX_ATOMIC_ARGS
#define MAX_ATOMIC_ARGS 6
Definition at line 2087 of file expatomics.cpp.
TARGET_GNU_ATOMICS
#define TARGET_GNU_ATOMICS 1
Definition at line 1607 of file expatomics.cpp.
Typedef Documentation
ATOMIC_OP_CATEGORY
typedef enum ATOMIC_OP_CATEGORY ATOMIC_OP_CATEGORY
Categorization of atomic intrinsics that abstracts out details. Each class corresponds to a general code-generation schema.
auto_temp
typedef struct auto_temp auto_temp
Object that assists generation of temporaries. See functions auto_stash and auto_retrieve for how it is used.
MP_ATOMIC_IDX
typedef enum MP_ATOMIC_IDX MP_ATOMIC_IDX
OPCODES
typedef struct OPCODES OPCODES
ILI operations of a given "link" kind.
Enumeration Type Documentation
ATOMIC_OP_CATEGORY
enum ATOMIC_OP_CATEGORY
Categorization of atomic intrinsics that abstracts out details. Each class corresponds to a general code-generation schema.
Enumerator
AOC_LOAD
AOC_STORE
AOC_EXCHANGE
AOC_COMPARE_EXCHANGE
AOC_FETCH_OP
AOC_OP_FETCH
AOC_TEST_AND_SET
AOC_CLEAR
AOC_FENCE
Definition at line 1612 of file expatomics.cpp.
MP_ATOMIC_IDX
enum MP_ATOMIC_IDX
Enumerator
LHS_IDX
RHS_IDX
MO_IDX
AOP_IDX
UNUSED1
TMP_SPTR_IDX
Definition at line 77 of file expatomics.cpp.
Function Documentation
_exp_mp_atomic_read()
static int _exp_mp_atomic_read (int stc, DTYPE dtype, int * opnd, int * nme) static
Definition at line 2423 of file expatomics.cpp.
References ad3ili(), ad4ili(), ad_icon, addnme(), OPCODES::atomicld, ILTB::callfg, chk_block(), DT_CMPLX, DT_DCMPLX, get_ops(), GetSPTRVal, iltb, ISZ_T, ld, ldst_msz(), LHS_IDX, ll_make_atomic_load(), ll_make_kmpc_atomic_read(), loc_of(), mk_address(), mkatomictemp(), MO_IDX, msz, NOSYM, NT_VAR, result, size, st, TMP_SPTR_IDX, and zsize_of().
Referenced by exp_mp_atomic_read(), and get_complex_update_operand().
_exp_mp_atomic_update()
static void _exp_mp_atomic_update (DTYPE dtype, int * opnd, int * nme) static
Definition at line 2898 of file expatomics.cpp.
References ad1ili(), ad3ili(), ad4ili(), ad_cmpxchg(), ad_cse(), ad_icon, addnme(), AORG_OPENMP, atomic_encode(), BIH_LABEL, ILTB::callfg, CC_EQ, chk_block(), OPCODES::cmpxchg, OPCODES::cmpxchg_old, EXP::curbih, DT_CMPLX, DT_DCMPLX, expb, get_ops(), getlab(), GetSPTRVal, iltb, ISZ_T, label, OPCODES::ld, ld, ldst_msz(), LHS_IDX, ll_make_atomic_compare_xchg(), loc_of(), mk_address(), mkatomictemp(), MO_IDX, msz, msz_from_atomic_dtype(), NT_VAR, result, RFCNTI, RHS_IDX, size, SS_PROCESS, OPCODES::st, st, and zsize_of().
Referenced by exp_mp_atomic_capture(), and exp_mp_atomic_update().
_exp_mp_atomic_write()
static void _exp_mp_atomic_write (int stc, DTYPE dtype, int * opnd, int * nme) static
Definition at line 2533 of file expatomics.cpp.
References ad4ili(), ad5ili(), ad_icon, addnme(), OPCODES::atomicst, ILTB::callfg, chk_block(), DT_CMPLX, DT_DCMPLX, DT_VOID_NONE, get_ops(), iltb, ISZ_T, ld, ldst_msz(), LHS_IDX, ll_make_atomic_store(), ll_make_kmpc_atomic_write(), loc_of(), mk_address(), mkatomictemp(), MO_IDX, msz, NOSYM, NT_VAR, result, RHS_IDX, size, st, TMP_SPTR_IDX, and zsize_of().
Referenced by exp_mp_atomic_write().
_ilis_are_matched()
static void _ilis_are_matched (int rhs, int lhs, int * res, int * load) static
Definition at line 2778 of file expatomics.cpp.
References _ilis_are_matched(), CNULL, ERR_Severe, error(), gbl, IL_ISLINK, IL_OPRS, IL_TYPE, ILI_OPC, ILI_OPND, ILTY_LOAD, j, lhs, lhs_match_rhs(), load, and res.
Referenced by _ilis_are_matched(), and load_op_match_lhs().
can_use_rmw()
static bool can_use_rmw (DTYPE dtype, ATOMIC_RMW_OP aop) static
Definition at line 2612 of file expatomics.cpp.
References AOP_MAX_DEF, DT_CPTR, DT_INT, DT_LOG, and zsize_of().
Referenced by exp_mp_atomic_capture(), and exp_mp_atomic_update().
create_atomic_capture_seq()
int create_atomic_capture_seq (int update_ili, int read_ili, int capture_first)
...
Definition at line 619 of file expatomics.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), arg, ARG_IR, ARG_XR, DT_CPTR, DT_DBLE, DT_FLOAT, DT_INT, ERR_Severe, ERR_unused, FR_RETVAL, get_atomic_function(), ILI_ALT, ILI_OPC, ILI_OPND, interr(), IR_RETVAL, KR_RETVAL, result, and set_store_pt_addrtkn_flg().
Referenced by exp_end_atomic().
create_atomic_read_seq()
int create_atomic_read_seq (int store_ili)
...
Definition at line 934 of file expatomics.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), arg, ARG_IR, AtomicOp, DT_CPTR, get_atomic_function(), ILI_ALT, ILI_OPC, ILI_OPND, and set_store_pt_addrtkn_flg().
Referenced by exp_end_atomic().
create_atomic_seq()
int create_atomic_seq (int store_ili)
...
Definition at line 1300 of file expatomics.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), addcallarg(), arg, atomic_typecast_operand, AtomicOp, DT_CPTR, DT_DBLE, DT_FLOAT, DT_INT, ERR_Severe, gencallargs(), get_atomic_function(), get_atomic_function_ex(), IL_AADD, IL_ASUB, ili, ILI_ALT, ILI_OPC, ILI_OPND, initcallargs(), interr(), and is_atomic_typcast_h2l().
Referenced by exp_end_atomic().
create_atomic_write_seq()
int create_atomic_write_seq (int store_ili)
...
Definition at line 812 of file expatomics.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), arg, ARG_IR, ARG_XR, AtomicOp, DT_CPTR, DT_DBLE, DT_FLOAT, DT_INT, ERR_Severe, get_atomic_function(), ILI_ALT, ILI_OPC, ILI_OPND, interr(), and set_store_pt_addrtkn_flg().
Referenced by exp_end_atomic().
exp_end_atomic()
bool exp_end_atomic (int store, int curilm)
...
Definition at line 1480 of file expatomics.cpp.
References capture_read_ili, capture_update_ili, chk_block(), CNULL, create_atomic_capture_seq(), create_atomic_read_seq(), create_atomic_seq(), create_atomic_write_seq(), EXP::curbih, ERR_Severe, error(), expb, gbl, get_atomic_read_opcode(), get_atomic_store_created(), get_atomic_update_opcode(), get_atomic_write_opcode(), ILM_BLOCK, ILM_RESULT, is_in_atomic, is_in_atomic_capture, is_in_atomic_read, is_in_atomic_write, reset_atomic_typecast_h2l(), set_atomic_capture_created(), and set_atomic_store_created().
Referenced by exp_store().
exp_mp_atomic_capture()
void exp_mp_atomic_capture (ILM * ilmp)
...
Definition at line 3054 of file expatomics.cpp.
References _exp_mp_atomic_update(), ad3ili(), ad4ili(), ad5ili(), ad_icon, addnme(), AORG_OPENMP, atomic_encode_rmw(), OPCODES::atomicrmw, can_use_rmw(), chk_block(), cnt, CNULL, dt_nme(), DTY, ERR_Severe, error(), find_ili(), gbl, get_complex_update_operand(), get_dtype_from_ilm(), get_ops(), get_simple_update_operand(), GetAtomicOp, GetSPTRVal, ILI_OF, ILI_OPND, ILM_OPND, is_cse(), ld, ldst_msz(), lhs, LHS_IDX, load, load_op_match_lhs(), loc_of(), MAX_ATOMIC_ARGS, mem_size(), mk_address(), mkatomictemp(), MO_IDX, MO_SEQ_CST, msz, NME_OF, NOSYM, NT_VAR, result, rewr_cln_ili(), rewr_ili(), RHS_IDX, set_assn(), SS_PROCESS, st, and TMP_SPTR_IDX.
Referenced by exp_smp().
exp_mp_atomic_read()
int exp_mp_atomic_read (ILM * ilmp)
...
Definition at line 2505 of file expatomics.cpp.
References _exp_mp_atomic_read(), ad_icon, AORG_OPENMP, atomic_encode(), dt_nme(), get_dtype_from_ilm(), ILI_OF, ILM_OPND, ld, ldst_msz(), LHS_IDX, MAX_ATOMIC_ARGS, MO_IDX, MO_SEQ_CST, msz, NME_OF, SS_PROCESS, st, and TMP_SPTR_IDX.
Referenced by exp_smp().
exp_mp_atomic_update()
void exp_mp_atomic_update (ILM * ilmp)
...
Definition at line 2982 of file expatomics.cpp.
References _exp_mp_atomic_update(), ad4ili(), ad5ili(), ad_icon, addnme(), AORG_OPENMP, atomic_encode_rmw(), OPCODES::atomicrmw, can_use_rmw(), chk_block(), CNULL, cr_block(), dt_nme(), DTY, ERR_Severe, error(), gbl, get_complex_update_operand(), get_dtype_from_ilm(), get_ops(), get_simple_update_operand(), GetAtomicOp, GetSPTRVal, ILI_OF, ILI_OPND, ILM_OPND, is_cse(), ld, ldst_msz(), LHS_IDX, loc_of(), MAX_ATOMIC_ARGS, mem_size(), mk_address(), mkatomictemp(), MO_IDX, MO_SEQ_CST, msz, NME_OF, NT_VAR, result, RHS_IDX, set_assn(), SPTR_NULL, SS_PROCESS, st, TMP_SPTR_IDX, and wr_block().
Referenced by exp_smp().
exp_mp_atomic_write()
void exp_mp_atomic_write (ILM * ilmp)
...
Definition at line 2584 of file expatomics.cpp.
References _exp_mp_atomic_write(), ad_icon, AORG_OPENMP, atomic_encode(), dt_nme(), DTY, get_dtype_from_ilm(), ILI_OF, ILM_OPND, LHS_IDX, MAX_ATOMIC_ARGS, mem_size(), MO_IDX, MO_SEQ_CST, NME_OF, RHS_IDX, and SS_PROCESS.
Referenced by exp_smp().
get_atomic_capture_created()
int get_atomic_capture_created (void)
...
Definition at line 533 of file expatomics.cpp.
References atomic_capture_created.
Referenced by exp_misc().
get_atomic_function()
int get_atomic_function (ILI_OP opcode)
...
Definition at line 331 of file expatomics.cpp.
References DT_CPTR, DT_DBLE, DT_FLOAT, DT_INT, DT_VOID_NONE, ERR_Severe, IL_IADD, IL_IDIV, IL_IMUL, IL_INEG, IL_ISUB, interr(), and mk_prototype.
Referenced by create_atomic_capture_seq(), create_atomic_read_seq(), create_atomic_seq(), and create_atomic_write_seq().
get_atomic_function_ex()
int get_atomic_function_ex (ILI_OP opcode)
...
Definition at line 113 of file expatomics.cpp.
References atomic_typecast_operand, CNULL, DT_CPTR, DT_DBLE, DT_FLOAT, DT_INT, ERR_Severe, error(), gbl, is_atomic_operand1, and mk_prototype.
Referenced by create_atomic_seq().
get_atomic_read_opcode()
int get_atomic_read_opcode (int current_ili)
...
Definition at line 898 of file expatomics.cpp.
References AtomicOp, ili, ILI_OPC, and ILI_OPND.
Referenced by exp_end_atomic().
get_atomic_store_created()
int get_atomic_store_created (void)
...
Definition at line 545 of file expatomics.cpp.
References atomic_store_created.
Referenced by exp_end_atomic(), and exp_misc().
get_atomic_update_opcode()
ILI_OP get_atomic_update_opcode (int current_ili)
...
Definition at line 989 of file expatomics.cpp.
References assert, atomic_typecast_operand, AtomicOp, cmplx_atomic_opcodes, CNULL, double_atomic_opcodes, ERR_Fatal, ERR_Severe, error(), float_atomic_opcodes, gbl, ili, ILI_OPC, ILI_OPND, int_atomic_opcodes, interr(), is_atomic_operand1, long_atomic_opcodes, num_cmplx_opcodes, num_double_opcodes, num_float_opcodes, num_int_opcodes, num_long_opcodes, set_atomic_typecast_h2l(), and SYMNAME.
Referenced by exp_end_atomic().
get_atomic_write_opcode()
int get_atomic_write_opcode (int current_ili)
...
Definition at line 557 of file expatomics.cpp.
References AtomicOp, ili, ILI_OPC, and ILI_OPND.
Referenced by exp_end_atomic().
get_capture_read_ili()
int get_capture_read_ili (void)
...
Definition at line 461 of file expatomics.cpp.
References capture_read_ili.
Referenced by exp_misc().
get_capture_update_ili()
int get_capture_update_ili (void)
...
Definition at line 473 of file expatomics.cpp.
References capture_update_ili.
Referenced by exp_misc().
get_complex_update_operand()
static int get_complex_update_operand (int * opnd, ILM * ilmp, int * nme, DTYPE dtype) static
Definition at line 2852 of file expatomics.cpp.
References _exp_mp_atomic_read(), ad3ili(), ad4ili(), addnme(), AORG_OPENMP, atomic_encode(), chk_block(), find_ili(), GetSPTRVal, ili, ili_unvisit(), ld, ldst_msz(), lhs, LHS_IDX, load, load_op_match_lhs(), mk_address(), mkatomictemp(), msz, NT_VAR, rewr_cln_ili(), rewr_ili(), RHS_IDX, SS_PROCESS, st, and TMP_SPTR_IDX.
Referenced by exp_mp_atomic_capture(), and exp_mp_atomic_update().
get_dtype_from_ilm()
static DTYPE get_dtype_from_ilm (ILM * ilmp) static
Definition at line 2476 of file expatomics.cpp.
References ERR_Severe, ILMB::ilm_base, ILM_DTyOPND, ILM_OPC, ILM_OPND, ILM_SymOPND, ilmb, and interr().
Referenced by exp_mp_atomic_capture(), exp_mp_atomic_read(), exp_mp_atomic_update(), and exp_mp_atomic_write().
get_is_in_atomic()
int get_is_in_atomic (void)
...
Definition at line 485 of file expatomics.cpp.
References is_in_atomic.
get_is_in_atomic_capture()
int get_is_in_atomic_capture (void)
...
Definition at line 521 of file expatomics.cpp.
References is_in_atomic_capture.
Referenced by exp_misc().
get_is_in_atomic_read()
int get_is_in_atomic_read (void)
...
Definition at line 497 of file expatomics.cpp.
References is_in_atomic_read.
get_is_in_atomic_write()
int get_is_in_atomic_write (void)
...
Definition at line 509 of file expatomics.cpp.
References is_in_atomic_write.
get_ops()
static const OPCODES * get_ops (MSZ msz, int is_openmp) static
Get operations suitable for a given MSZ. The MSZ must correspond to an integer type.
Definition at line 1739 of file expatomics.cpp.
References FLANG_FALLTHROUGH, msz, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_PTR, MSZ_SLWORD, and MSZ_ULWORD.
Referenced by _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_mp_atomic_write(), exp_mp_atomic_capture(), and exp_mp_atomic_update().
get_simple_update_operand()
static int get_simple_update_operand (int * opnd, ILM * ilmp) static
Definition at line 2660 of file expatomics.cpp.
References AOP_ADD, AOP_AND, AOP_IDX, AOP_MAX, AOP_MIN, AOP_OR, AOP_SUB, AOP_XOR, find_ili(), IL_IADD, IL_ISUB, IL_TYPE, ILI_OPC, ILI_OPND, ILTY_LOAD, is_cse(), lhs, LHS_IDX, and RHS_IDX.
Referenced by exp_mp_atomic_capture(), and exp_mp_atomic_update().
is_atomic_typcast_h2l()
static int is_atomic_typcast_h2l () static
Definition at line 983 of file expatomics.cpp.
References atomic_typecast_operand.
Referenced by create_atomic_seq().
is_cse()
static bool is_cse (int ilix) static
Definition at line 2637 of file expatomics.cpp.
References ILI_OPC.
Referenced by exp_mp_atomic_capture(), exp_mp_atomic_update(), and get_simple_update_operand().
lhs_match_rhs()
static bool lhs_match_rhs (int lop, int rop) static
Definition at line 2750 of file expatomics.cpp.
References IL_ISLINK, IL_OPRS, ILI_OPC, ILI_OPND, j, and lhs_match_rhs().
Referenced by _ilis_are_matched(), and lhs_match_rhs().
ll_make_atomic_compare_xchg()
static int ll_make_atomic_compare_xchg (int size_ili, int lhs, int expected, int desired, int success, int failure) static
Definition at line 2376 of file expatomics.cpp.
References ad1ili(), ad2ili(), arg, func, ikmove(), IR_RETVAL, lhs, mkfunc(), and result.
Referenced by _exp_mp_atomic_update().
ll_make_atomic_load()
static int ll_make_atomic_load (int size_ili, int lhs, int rhs, int mem_order) static
Definition at line 2337 of file expatomics.cpp.
References ad1ili(), ad2ili(), arg, func, ikmove(), lhs, mkfunc(), and result.
Referenced by _exp_mp_atomic_read().
ll_make_atomic_store()
static int ll_make_atomic_store (int size_ili, int lhs, int rhs, int mem_order) static
Definition at line 2357 of file expatomics.cpp.
References ad1ili(), ad2ili(), arg, func, ikmove(), lhs, mkfunc(), and result.
Referenced by _exp_mp_atomic_write().
load_op_match_lhs()
static int load_op_match_lhs (int lhs, int rhs) static
Definition at line 2822 of file expatomics.cpp.
References _ilis_are_matched(), find_ili(), IL_AADD, IL_ASUB, ILI_OPC, ILI_OPND, ili_unvisit(), lhs, load, and res.
Referenced by exp_mp_atomic_capture(), and get_complex_update_operand().
mkatomictemp()
static SPTR mkatomictemp (DTYPE dtype) static
Definition at line 2326 of file expatomics.cpp.
References cnt, gbl, GBL_CURRFUNC, getnewccsym(), and SC_AUTO.
Referenced by _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_mp_atomic_write(), exp_mp_atomic_capture(), exp_mp_atomic_update(), and get_complex_update_operand().
msz_from_atomic_dtype()
static MSZ msz_from_atomic_dtype (DTYPE dtype) static
Definition at line 1715 of file expatomics.cpp.
References MSZ_BYTE, MSZ_I8, MSZ_SHWORD, MSZ_SWORD, MSZ_UNDEF, and zsize_of().
Referenced by _exp_mp_atomic_update().
reset_atomic_typecast_h2l()
static void reset_atomic_typecast_h2l () static
Definition at line 976 of file expatomics.cpp.
References atomic_typecast_operand, and is_atomic_operand1.
Referenced by exp_end_atomic().
set_atomic_capture_created()
void set_atomic_capture_created (int x)
...
Definition at line 539 of file expatomics.cpp.
References atomic_capture_created, and x.
Referenced by exp_end_atomic(), and exp_misc().
set_atomic_store_created()
void set_atomic_store_created (int x)
...
Definition at line 551 of file expatomics.cpp.
References atomic_store_created, and x.
Referenced by exp_end_atomic(), and exp_misc().
set_atomic_typecast_h2l()
static void set_atomic_typecast_h2l (int tcast_ili) static
Definition at line 970 of file expatomics.cpp.
References atomic_typecast_operand.
Referenced by get_atomic_update_opcode().
set_capture_read_ili()
void set_capture_read_ili (int x)
...
Definition at line 467 of file expatomics.cpp.
References capture_read_ili, and x.
Referenced by exp_misc().
set_capture_update_ili()
void set_capture_update_ili (int x)
...
Definition at line 479 of file expatomics.cpp.
References capture_update_ili, and x.
Referenced by exp_misc().
set_is_in_atomic()
void set_is_in_atomic (int x)
...
Definition at line 491 of file expatomics.cpp.
References is_in_atomic, and x.
Referenced by exp_misc().
set_is_in_atomic_capture()
void set_is_in_atomic_capture (int x)
...
Definition at line 527 of file expatomics.cpp.
References is_in_atomic_capture, and x.
Referenced by exp_misc().
set_is_in_atomic_read()
void set_is_in_atomic_read (int x)
...
Definition at line 503 of file expatomics.cpp.
References is_in_atomic_read, and x.
Referenced by exp_misc().
set_is_in_atomic_write()
void set_is_in_atomic_write (int x)
...
Definition at line 515 of file expatomics.cpp.
References is_in_atomic_write, and x.
Referenced by exp_misc().
set_store_pt_addrtkn_flg()
static void set_store_pt_addrtkn_flg (int store_pt) static
Definition at line 588 of file expatomics.cpp.
References IL_AADD, IL_ASUB, ILI_OPC, and ILI_OPND.
Referenced by create_atomic_capture_seq(), create_atomic_read_seq(), and create_atomic_write_seq().
Variable Documentation
atomic_capture_created
int atomic_capture_created static
Definition at line 29 of file expatomics.cpp.
Referenced by get_atomic_capture_created(), and set_atomic_capture_created().
atomic_operand
int atomic_operand
Definition at line 89 of file expatomics.cpp.
atomic_store_created
int atomic_store_created static
Definition at line 30 of file expatomics.cpp.
Referenced by get_atomic_store_created(), and set_atomic_store_created().
atomic_typecast_operand
int atomic_typecast_operand static
Definition at line 38 of file expatomics.cpp.
Referenced by create_atomic_seq(), get_atomic_function_ex(), get_atomic_update_opcode(), is_atomic_typcast_h2l(), reset_atomic_typecast_h2l(), and set_atomic_typecast_h2l().
struct { ... } AtomicOp
Referenced by create_atomic_read_seq(), create_atomic_seq(), create_atomic_write_seq(), get_atomic_read_opcode(), get_atomic_update_opcode(), and get_atomic_write_opcode().
capture_read_ili
int capture_read_ili static
Definition at line 36 of file expatomics.cpp.
Referenced by exp_end_atomic(), get_capture_read_ili(), and set_capture_read_ili().
capture_update_ili
int capture_update_ili static
Definition at line 37 of file expatomics.cpp.
Referenced by exp_end_atomic(), get_capture_update_ili(), and set_capture_update_ili().
cmplx_atomic_opcodes
int cmplx_atomic_opcodes[] = {IL_SCMPLXADD, IL_SCMPLXSUB} static
Definition at line 44 of file expatomics.cpp.
Referenced by get_atomic_update_opcode().
double_atomic_opcodes
int double_atomic_opcodes[] static
Initial value:
= {IL_DADD, IL_DSUB, IL_DDIV,
                                      IL_DMUL, IL_DMAX, IL_DMIN}
Definition at line 51 of file expatomics.cpp.
Referenced by get_atomic_update_opcode().
float_atomic_opcodes
int float_atomic_opcodes[] static
Initial value:
= {IL_FADD, IL_FSUB, IL_FDIV,
                                     IL_FMUL, IL_FMAX, IL_FMIN}
Definition at line 47 of file expatomics.cpp.
Referenced by get_atomic_update_opcode().
ili_operand
int ili_operand
Definition at line 92 of file expatomics.cpp.
int_atomic_opcodes
int int_atomic_opcodes[] static
Initial value:
= {
    IL_IADD,    IL_ISUB,   IL_LEQV,   IL_XOR,   IL_IMUL,  IL_UIMUL,
    IL_AND,     IL_OR,     IL_UIADD,  IL_UISUB, IL_UIMUL, IL_ULSHIFT,
    IL_URSHIFT, IL_LSHIFT, IL_RSHIFT, IL_IDIV,  IL_UIDIV, IL_IMAX,
    IL_IMIN,    IL_NOT,    IL_INEG,   IL_LD}
Definition at line 59 of file expatomics.cpp.
Referenced by get_atomic_update_opcode().
is_atomic_operand1
int is_atomic_operand1 = 0 static
Definition at line 42 of file expatomics.cpp.
Referenced by get_atomic_function_ex(), get_atomic_update_opcode(), and reset_atomic_typecast_h2l().
is_in_atomic
int is_in_atomic static
Definition at line 31 of file expatomics.cpp.
Referenced by exp_end_atomic(), get_is_in_atomic(), and set_is_in_atomic().
is_in_atomic_capture
int is_in_atomic_capture static
Definition at line 34 of file expatomics.cpp.
Referenced by exp_end_atomic(), get_is_in_atomic_capture(), and set_is_in_atomic_capture().
is_in_atomic_read
int is_in_atomic_read static
Definition at line 32 of file expatomics.cpp.
Referenced by exp_end_atomic(), get_is_in_atomic_read(), and set_is_in_atomic_read().
is_in_atomic_write
int is_in_atomic_write static
Definition at line 33 of file expatomics.cpp.
Referenced by exp_end_atomic(), get_is_in_atomic_write(), and set_is_in_atomic_write().
ldst_nme
int ldst_nme
Definition at line 91 of file expatomics.cpp.
ldst_point
int ldst_point
Definition at line 90 of file expatomics.cpp.
long_atomic_opcodes
int long_atomic_opcodes[] static
Initial value:
= {IL_KADD, IL_KSUB, IL_KXOR, IL_KMUL,
                                    IL_UKMUL, IL_KAND, IL_KOR, IL_UKADD,
                                    IL_UKSUB, IL_KDIV, IL_UKDIV
                                    ,
                                    IL_KMAX, IL_KMIN
}
Definition at line 70 of file expatomics.cpp.
Referenced by get_atomic_update_opcode().
num_cmplx_opcodes
int num_cmplx_opcodes = sizeof(cmplx_atomic_opcodes) / sizeof(int) static
Definition at line 45 of file expatomics.cpp.
Referenced by get_atomic_update_opcode().
num_double_opcodes
int num_double_opcodes = sizeof(double_atomic_opcodes) / sizeof(int) static
Definition at line 53 of file expatomics.cpp.
Referenced by get_atomic_update_opcode().
num_float_opcodes
int num_float_opcodes = sizeof(float_atomic_opcodes) / sizeof(int) static
Definition at line 49 of file expatomics.cpp.
Referenced by get_atomic_update_opcode().
num_int_opcodes
int num_int_opcodes = sizeof(int_atomic_opcodes) / sizeof(int) static
Definition at line 64 of file expatomics.cpp.
Referenced by get_atomic_update_opcode().
num_long_opcodes
int num_long_opcodes = sizeof(long_atomic_opcodes) / sizeof(int) static
Definition at line 86 of file expatomics.cpp.
Referenced by get_atomic_update_opcode().