flang: expand.h File Reference
expand.h File Reference
various definitions for the expand module
#include "gbldefs.h"
#include "global.h"
#include "symtab.h"
#include "ilmtp.h"
#include <stdint.h>
Classes
struct ILM
struct ILM_AUX
struct _str
string descriptor
struct EXP
Macros
#define EXPDBG(x, y) (DEBUG && DBGBIT(x, y))
#define EXP_ALLOC(stgb, dt, sz)
#define EXP_MORE(stb, dt, nsz)
#define EXP_NEED(stb, dt, nsz)
#define EXP_FREE(stb) FREE(stb.stg_base)
#define ILM_OPND(i, opn) ((i)->opnd[opn - 1])
#define ILM_OPC(i) ((i)->opc)
#define SetILM_OPC(i, j) ((i)->opc = (j))
#define ILM_SymOPND ILM_OPND
#define ILM_DTyOPND ILM_OPND
#define ILM_TEMP(i) (expb.temps[i])
#define ILI_OF(i) (expb.ilmb.stg_base[i].w1)
#define NME_OF(i) (expb.ilmb.stg_base[i].w2)
#define SCALE_OF(i) (expb.ilmb.stg_base[i].w4)
#define ILM_RESULT(i) (expb.ilmb.stg_base[i].w1)
#define ILM_NME(i) (expb.ilmb.stg_base[i].w2)
#define ILM_BLOCK(i) (expb.ilmb.stg_base[i].w3)
#define ILM_SCALE(i) (expb.ilmb.stg_base[i].w4)
#define ILM_RRESULT(i) ILM_RESULT(i)
#define ILM_IRESULT(i) (expb.ilmb.stg_base[i].w7)
#define ILM_RESTYPE(i) (expb.ilmb.stg_base[i].w6)
#define ILM_ISCMPLX 1
#define ILM_ISDCMPLX 2
#define ILM_ISCHAR 3
#define ILM_ISI8 4
#define ILM_ISX87CMPLX 5
#define ILM_ISDOUBLEDOUBLECMPLX 6
#define ILM_ISFLOAT128CMPLX 7
#define ILM_ISQCMPLX 8
#define ILM_MXLEN(i) (expb.ilmb.stg_base[i].w5)
#define ILM_CLEN(i) (expb.ilmb.stg_base[i].w7)
#define ILM_EXPANDED_FOR(i) (expb.ilmb.stg_base[i].w8)
#define DOREG1 (flg.opt == 1 && !XBIT(8, 0x8))
#define ADDRCAND(a, b) if (DOREG1) { exp_rcand((a), (b)); }
#define STR_AREA 6
#define CHARLEN_64BIT (XBIT(68,1) || XBIT(68,0x20))
Typedefs
typedef struct ILM ILM
typedef struct _str STRDESC
string descriptor
Functions
int expand (void)
...
int exp_mac (ILM_OP opc, ILM *ilmp, int curilm)
...
int getThreadPrivateTp (int sptr)
...
int llGetThreadprivateAddr (int sptr)
...
int optional_missing_ilm (ILM *ilmpin)
...
int optional_missing (int nme)
...
int optional_present (int nme)
...
void ds_init (void)
...
void eval_ilm (int ilmx)
...
void exp_cleanup (void)
...
void exp_estmt (int ilix)
...
void exp_init (void)
...
void exp_label (SPTR lbl)
...
void exp_load (ILM_OP opc, ILM *ilmp, int curilm)
...
void exp_pure (SPTR extsym, int nargs, ILM *ilmp, int curilm)
...
void exp_ref (ILM_OP opc, ILM *ilmp, int curilm)
...
void exp_store (ILM_OP opc, ILM *ilmp, int curilm)
...
void ll_set_new_threadprivate (int oldsptr)
...
void ref_threadprivate (int cmsym, int *addr, int *nm)
...
void ref_threadprivate_var (int cmsym, int *addr, int *nm, int mark)
...
void replace_by_one (ILM_OP opc, ILM *ilmp, int curilm)
...
void replace_by_zero (ILM_OP opc, ILM *ilmp, int curilm)
...
void set_assn (int nme)
...
Variables
EXP expb
Detailed Description
various definitions for the expand module
Definition in file expand.h.
Macro Definition Documentation
ADDRCAND
#define ADDRCAND (a, b) if (DOREG1) { exp_rcand((a), (b)); }
Definition at line 134 of file expand.h.
CHARLEN_64BIT
#define CHARLEN_64BIT (XBIT(68,1) || XBIT(68,0x20))
Definition at line 225 of file expand.h.
DOREG1
#define DOREG1 (flg.opt == 1 && !XBIT(8, 0x8))
Definition at line 133 of file expand.h.
EXP_ALLOC
#define EXP_ALLOC (stgb, dt, sz)
Value:
  {                             \
    NEW(stgb.stg_base, dt, sz); \
    stgb.stg_size = sz;         \
  }
Definition at line 27 of file expand.h.
EXP_FREE
#define EXP_FREE (stb) FREE(stb.stg_base)
Definition at line 44 of file expand.h.
EXP_MORE
#define EXP_MORE (stb, dt, nsz)
Value:
  {                                                                         \
    stb.stg_base =                                                          \
        (dt *)sccrelal((char *)stb.stg_base, ((BIGUINT64)((nsz) * sizeof(dt)))); \
    stb.stg_size = nsz;                                                     \
  }
Definition at line 33 of file expand.h.
EXP_NEED
#define EXP_NEED (stb, dt, nsz)
Value:
  if (stb.stg_avail > stb.stg_size) \
    EXP_MORE(stb, dt, nsz);
Definition at line 40 of file expand.h.
EXPDBG
#define EXPDBG (x, y) (DEBUG && DBGBIT(x, y))
Definition at line 23 of file expand.h.
ILI_OF
#define ILI_OF (i) (expb.ilmb.stg_base[i].w1)
Definition at line 102 of file expand.h.
ILM_BLOCK
#define ILM_BLOCK (i) (expb.ilmb.stg_base[i].w3)
Definition at line 108 of file expand.h.
ILM_CLEN
#define ILM_CLEN (i) (expb.ilmb.stg_base[i].w7)
Definition at line 127 of file expand.h.
ILM_DTyOPND
#define ILM_DTyOPND ILM_OPND
Definition at line 79 of file expand.h.
ILM_EXPANDED_FOR
#define ILM_EXPANDED_FOR (i) (expb.ilmb.stg_base[i].w8)
Definition at line 131 of file expand.h.
ILM_IRESULT
#define ILM_IRESULT (i) (expb.ilmb.stg_base[i].w7)
Definition at line 112 of file expand.h.
ILM_ISCHAR
#define ILM_ISCHAR 3
Definition at line 118 of file expand.h.
ILM_ISCMPLX
#define ILM_ISCMPLX 1
Definition at line 116 of file expand.h.
ILM_ISDCMPLX
#define ILM_ISDCMPLX 2
Definition at line 117 of file expand.h.
ILM_ISDOUBLEDOUBLECMPLX
#define ILM_ISDOUBLEDOUBLECMPLX 6
Definition at line 121 of file expand.h.
ILM_ISFLOAT128CMPLX
#define ILM_ISFLOAT128CMPLX 7
Definition at line 122 of file expand.h.
ILM_ISI8
#define ILM_ISI8 4
Definition at line 119 of file expand.h.
ILM_ISQCMPLX
#define ILM_ISQCMPLX 8
Definition at line 123 of file expand.h.
ILM_ISX87CMPLX
#define ILM_ISX87CMPLX 5
Definition at line 120 of file expand.h.
ILM_MXLEN
#define ILM_MXLEN (i) (expb.ilmb.stg_base[i].w5)
Definition at line 126 of file expand.h.
ILM_NME
#define ILM_NME (i) (expb.ilmb.stg_base[i].w2)
Definition at line 107 of file expand.h.
ILM_OPC
#define ILM_OPC (i) ((i)->opc)
Definition at line 76 of file expand.h.
ILM_OPND
#define ILM_OPND (i, opn) ((i)->opnd[opn - 1])
Definition at line 55 of file expand.h.
ILM_RESTYPE
#define ILM_RESTYPE (i) (expb.ilmb.stg_base[i].w6)
Definition at line 115 of file expand.h.
ILM_RESULT
#define ILM_RESULT (i) (expb.ilmb.stg_base[i].w1)
Definition at line 106 of file expand.h.
ILM_RRESULT
#define ILM_RRESULT (i) ILM_RESULT(i)
Definition at line 111 of file expand.h.
ILM_SCALE
#define ILM_SCALE (i) (expb.ilmb.stg_base[i].w4)
Definition at line 109 of file expand.h.
ILM_SymOPND
#define ILM_SymOPND ILM_OPND
Definition at line 78 of file expand.h.
ILM_TEMP
#define ILM_TEMP (i) (expb.temps[i])
Definition at line 100 of file expand.h.
NME_OF
#define NME_OF (i) (expb.ilmb.stg_base[i].w2)
Definition at line 103 of file expand.h.
SCALE_OF
#define SCALE_OF (i) (expb.ilmb.stg_base[i].w4)
Definition at line 104 of file expand.h.
SetILM_OPC
#define SetILM_OPC (i, j) ((i)->opc = (j))
Definition at line 77 of file expand.h.
STR_AREA
#define STR_AREA 6
Definition at line 138 of file expand.h.
Typedef Documentation
ILM
typedef struct ILM ILM
STRDESC
typedef struct _str STRDESC
string descriptor
Function Documentation
ds_init()
void ds_init (void)
...
Definition at line 58 of file expand.cpp.
References bih_init(), BZERO, EXP_ALLOC, i, ili_init(), ilt_init(), RCANDB::kr, nme_init(), ratb, rcandb, rgsetb, RGSETB::stg_avail, RATB::stg_avail, RCANDB::stg_avail, RGSETB::stg_base, RCANDB::stg_base, and RCANDB::weight.
Referenced by exp_init().
eval_ilm()
void eval_ilm (int ilmx)
...
< ILM opcode of the ILM
Definition at line 437 of file expand.cpp.
References ILTB::callfg, check_ilm(), chk_block(), ERR_Severe, eval_ilm_argument1(), exp_ac, exp_bran(), exp_call(), exp_fstring(), exp_load(), exp_mac(), exp_misc(), exp_ompaccel_reduction(), exp_ref(), exp_smp(), exp_store(), EXPDBG, flg, gbl, ILI_OF, ILMB::ilm_base, ILM_EXPANDED_FOR, ILM_IRESULT, ILM_ISCMPLX, ILM_ISDCMPLX, ILM_ISFLOAT128CMPLX, ILM_ISI8, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_RRESULT, ilmb, ilms, iltb, IM_I8, IM_OPRFLAG, IM_SPEC, IM_TYPE, IM_VAR, IMTY_ARTH, IMTY_BRANCH, IMTY_CONS, IMTY_FSTR, IMTY_INTR, IMTY_LOAD, IMTY_MISC, IMTY_PROC, IMTY_REF, IMTY_SMP, IMTY_STORE, interr(), ll_ilm_is_rewriting(), ll_make_tgt_register_lib2(), ll_rewrite_ilms(), ILMINFO::name, ompaccel_is_tgt_registered(), ompaccel_nvvm_get(), ompaccel_register_tgt(), FLG::omptarget, OPR_LNK, ILMINFO::oprs, FLG::smp, threadIdX, tmp, and XBIT.
Referenced by eval_fvec(), eval_ilm_argument1(), expand(), replace_by_one(), and replace_by_zero().
exp_cleanup()
void exp_cleanup (void)
...
Definition at line 145 of file expand.cpp.
References EXP_FREE, NULL, ratb, rcandb, rgsetb, RGSETB::stg_base, RATB::stg_base, and RCANDB::stg_base.
exp_estmt()
void exp_estmt (int ilix)
...
Definition at line 664 of file expand.cpp.
References ad1ili(), ad_free(), ILTB::callfg, chk_block(), exp_estmt(), i, IL_HAS_FENCE, IL_ISLINK, IL_TYPE, ILI_OPC, ILI_OPND, ilis, iltb, ILTY_PROC, and ILIINFO::oprs.
Referenced by exp_estmt(), and exp_misc().
exp_init()
void exp_init (void)
...
Definition at line 84 of file expand.cpp.
References aux, EXP::bits, CHARLEN_64BIT, EXP::charlen_dtype, EXP::clobber_ir, EXP::clobber_pr, EXP::curbih, EXP::curilt, AUX::curr_entry, ENTRY::display, ds_init(), DT_INT, EXP::excstat, EXP_ALLOC, exp_smp_init(), expb, EXP::flags, flg, EXP::gentmps, EXP::ilm_thresh, EXP::ilmb, EXP::isguarded, EXP::logcjmp, NEW, EXP::noblock, EXP::noheader, FLG::opt, rewindilms(), EXP::sc, SC_AUTO, SPTR_NULL, EXP::str_avail, EXP::str_base, EXP::str_size, FLG::vect, EXP::wd, FLG::x, XBIT, FLG::xoff, and FLG::xon.
Referenced by expand().
exp_label()
void exp_label (SPTR lbl)
...
Definition at line 761 of file expand.cpp.
References addilt(), BIH_LABEL, EXP::bits, CNULL, compl_br(), cr_block(), EXP::curbih, EXP::curilt, FIHB::currfindex, FIHB::currftag, DBGBIT, ERR_Informational, errlabel(), exp_scope_label(), expb, EXPDBG, fihb, EXP::flags, flg, gbl, ILI_OPC, ILI_OPND, ilis, ILT_BR, ILT_DBGLINE, ILT_ILIP, ILT_NEXT, ILT_PREV, iltb, is_scope_label(), FIHB::nextfindex, FIHB::nextftag, FLG::opt, reduce_ilt(), RFCNTD, EXP::saveili, STG_ADD_FREELIST, SYMNAME, EXP::waitlbl, wr_block(), and XBIT.
Referenced by exp_agoto(), exp_end(), exp_misc(), exp_smp(), genswitch(), and section_create_endblock().
exp_load()
void exp_load (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 1092 of file expand.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad_aconi(), ad_icon, ad_kconi(), add_arrnme(), addnme(), addr, ADDRCAND, assert, base, CHARLEN_64BIT, CHECK_NME, DDTG, dt, DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, DT_ISBASIC, DT_ISSCALAR, dt_nme(), DTY, DTyCharLength, DTySeqTyElement, FLG::endian, ERR_Severe, exp_get_sdsc_len(), flg, IL_AADD, ili, ILI_OF, ILMB::ilm_base, ILM_CLEN, ILM_IRESULT, ILM_ISCHAR, ILM_ISCMPLX, ILM_ISDCMPLX, ILM_ISFLOAT128CMPLX, ILM_ISQCMPLX, ILM_MXLEN, ILM_NME, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_RRESULT, ILM_SymOPND, ilmb, interr(), RCANDB::kr, load, mk_address(), MSZ_F16, MSZ_F32, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_SBYTE, MSZ_SHWORD, MSZ_WORD, NME_INLARR, NME_OF, NME_SYM, NME_TYPE, NOSYM, NT_ARR, NT_IND, NT_MEM, NT_VAR, optional_missing_ilm(), rcandb, replace_by_zero(), SCALAR_SIZE(), size_of(), SPTR_NULL, tmp, TY_CHAR, TY_NCHAR, TY_QUAD, and XBIT.
Referenced by eval_ilm().
exp_mac()
int exp_mac (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 2015 of file expand.cpp.
References addili(), AR_RETVAL, atoxd(), atoxf(), atoxi(), atoxi64(), ILMOPND::aux, DP, DP_RETVAL, DT_DBLE, DT_FLOAT, DT_INT, efunc(), ERR_Severe, for(), getcon(), i, IDP, ILMINFO::ilict, ilis, ILM_DTyOPND, ILM_IRESULT, ILM_ISCMPLX, ILM_ISDCMPLX, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_RRESULT, ILM_TEMP, ilmaux, ILMO__ESYM, ILMO_AR, ILMO_ARPOS, ILMO_ARRET, ILMO_DP, ILMO_DPPOS, ILMO_DPRET, ILMO_DR, ILMO_DRPOS, ILMO_DRRET, ILMO_DSYM, ILMO_ESYM, ILMO_IDP, ILMO_IP, ILMO_IR, ILMO_ISP, ILMO_ISYM, ILMO_IV, ILMO_KR, ILMO_KRRET, ILMO_LLSYM, ILMO_NULL, ILMO_P, ILMO_QPRET, ILMO_R, ILMO_RP, ILMO_RR, ILMO_RSYM, ILMO_SCF, ILMO_SCZ, ILMO_SP, ILMO_SPPOS, ILMO_SPRET, ILMO_SZ, ILMO_T, ILMO_V, ILMO_XDSYM, ILMO_XRSYM, ilmopnd, ilms, ilmtp, IM_DCPLX, index, interr(), IR, IR_RETVAL, ISP, KR_RETVAL, len, num, ILI::opc, ILMMAC::opc, ILMMAC::opnd, ILI::opnd, ILIINFO::oprs, p, ILMINFO::pattern, QP_RETVAL, ILMMAC::result, scale_of(), size_of(), SP, SP_RETVAL, strlen(), and ILMOPND::type.
Referenced by eval_ilm(), exp_ac(), and exp_bran().
exp_pure()
void exp_pure (SPTR extsym, int nargs, ILM * ilmp, int curilm)
...
Definition at line 2910 of file expand.cpp.
References ad2ili(), ad3ili(), ad_acon(), args, i, IL_RES, ILI_OF, ILI_OPC, ILIA_AR, ILIA_IR, ILMB::ilm_base, ilm_callee_index(), ILM_OPC, ILM_OPND, ILM_RESULT, ilmb, jsr2qjsr(), MAX_PUREARGS, n, and nargs.
exp_ref()
void exp_ref (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 2398 of file expand.cpp.
References base, basenm, create_ref(), exp_array(), ILI_OF, ILM_CLEN, ILM_MXLEN, ILM_NME, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ILM_SymOPND, and NME_OF.
Referenced by eval_ilm().
exp_store()
void exp_store (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 1410 of file expand.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_aconi(), ad_cse(), ad_icon, add_arrnme(), addnme(), addr, ADDRCAND, CHECK_NME, chk_block(), EXP::curbih, EXP::curilt, dt, DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, DT_ISSCALAR, dt_nme(), DTY, FLG::endian, ERR_Severe, exp_end_atomic(), exp_szero(), expand_smove(), expb, EXPDBG, FLANG_FALLTHROUGH, flg, gbl, IL_AADD, IL_RES, ILI_ALT, ili_get_vect_dtype(), ILI_OF, ILI_OPC, ILI_OPND, ILIA_AR, ILIA_CD, ILIA_CS, ILIA_DP, ILIA_FLOAT128, ILIA_IR, ILIA_KR, ILIA_LNK, ILIA_SP, ILMB::ilm_base, ILM_BLOCK, ILM_DTyOPND, ILM_IRESULT, ILM_ISCMPLX, ILM_ISDCMPLX, ILM_ISFLOAT128CMPLX, ILM_ISQCMPLX, ILM_NME, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ilm_return_slot_index(), ILM_RRESULT, ilmb, ILT_CPLX, interr(), RCANDB::kr, loc_of(), MSZ_F16, MSZ_F32, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_SBYTE, MSZ_SHWORD, MSZ_WORD, NME_INLARR, NME_OF, NME_SYM, NME_TYPE, NME_UNK, NOSYM, NT_ARR, NT_IND, NT_MEM, NT_VAR, optional_missing_ilm(), rcandb, SCALAR_SIZE(), SET_ASSN, size_of(), SPTR_NULL, tmp, TY_QUAD, and XBIT.
Referenced by eval_ilm().
expand()
int expand (void)
...
...
Definition at line 9 of file dummy.c.
References BIH_EN, BIH_FTAG, BIH_NEXT, bihb, conflict(), EXP::curbih, FIHB::currfindex, FIHB::currftag, DBGBIT, DEBUG_ASSERT, dmpili(), dmpnme(), dump_blocks(), dumpilms(), eval_ilm(), EXP_FREE, exp_init(), EXP_MORE, exp_smp_fini(), expb, fihb, flg, FREE, freearea(), gbl, i, ili_lpprg_init(), ilib, ILMB::ilm_base, ILM_EXPANDED_FOR, ILM_NME, ILM_OPC, ILM_OPND, ILM_RESTYPE, ILM_RESULT, ilmb, EXP::ilmb, ilms, iltb, IM_TRM, IM_VAR, is_scope_label(), j, len, ll_rewrite_ilms(), new_callee_scope, FIHB::nextfindex, FIHB::nextftag, EXP::nilms, nmeb, NULL, ILMINFO::oprs, FLG::opt, parse_im_file(), rcandb, rdilms(), set_allfiles(), share_proc_ili, FLG::smp, RCANDB::stg_base, EXP::stg_size, STR_AREA, verify_function_ili(), VERIFY_ILI_DEEP, void(), and XBIT.
Referenced by process_input().
getThreadPrivateTp()
int getThreadPrivateTp (int sptr)
...
Definition at line 2801 of file expand.cpp.
References sptr.
Referenced by handle_nested_threadprivate(), and loadUplevelArgsForRegion().
ll_set_new_threadprivate()
void ll_set_new_threadprivate (int oldsptr)
...
Definition at line 2763 of file expand.cpp.
References DT_CPTR, gbl, GBL_CURRFUNC, getnewccsym(), SC_AUTO, and stb.
Referenced by allocThreadprivate(), and llGetThreadprivateAddr().
llGetThreadprivateAddr()
int llGetThreadprivateAddr (int sptr)
...
Definition at line 2785 of file expand.cpp.
References ad2ili(), ad_acon(), addnme(), addr, basenm, ll_set_new_threadprivate(), NT_VAR, and sptr.
Referenced by addCopyinInplace(), handle_nested_threadprivate(), loadUplevelArgsForRegion(), ref_threadprivate(), and ref_threadprivate_var().
optional_missing()
int optional_missing (int nme)
...
Definition at line 914 of file expand.cpp.
References NME_SYM, sptr, and SYMNAME.
Referenced by exp_call().
optional_missing_ilm()
int optional_missing_ilm (ILM * ilmpin)
...
Definition at line 931 of file expand.cpp.
References ILMB::ilm_base, ILM_OPC, ILM_OPND, ilmb, sptr, and SYMNAME.
Referenced by exp_load(), and exp_store().
optional_present()
int optional_present (int nme)
...
Definition at line 1041 of file expand.cpp.
References NME_SYM, sptr, and SYMNAME.
Referenced by exp_call().
ref_threadprivate()
void ref_threadprivate (int cmsym, int * addr, int * nm)
...
...
Generate an indirection using the threadprivate common's vector and then add the offset of this member. The actual address computation is: vector[_mp_lcpu3()] + offset(member)
Definition at line 2829 of file expand.cpp.
References ad2ili(), ad3ili(), ad_acon(), ad_aconi(), addnme(), addr, basenm, IL_AADD, llGetThreadprivateAddr(), NT_VAR, and XBIT.
Referenced by create_ref(), get_sdsc_element(), and makeCopyprivArray().
ref_threadprivate_var()
void ref_threadprivate_var (int cmsym, int * addr, int * nm, int mark)
...
...
Generate an indirection using the threadprivate's vector. The actual address computations is: vector[_mp_lcpu3()] mark : 1 - mark TPLNKP , and add it go gbl.threadprivate : this is normal processing. When calling this function later on, during exception fixup, call with mark = 0
Definition at line 2873 of file expand.cpp.
References ad2ili(), ad3ili(), ad_acon(), addnme(), addr, basenm, IL_AADD, llGetThreadprivateAddr(), NT_VAR, size_of(), SPTR_NULL, and XBIT.
Referenced by create_ref(), get_sdsc_element(), and makeCopyprivArray().
replace_by_one()
void replace_by_one (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 1066 of file expand.cpp.
References ERR_Severe, eval_ilm(), STB::i1, ILM_OPND, interr(), one, SetILM_OPC, and stb.
Referenced by exp_call().
replace_by_zero()
void replace_by_zero (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 965 of file expand.cpp.
References STB::dbl0, DT_CMPLX, DT_DCMPLX, ERR_Severe, eval_ilm(), STB::flt0, getcon(), STB::i0, ILM_OPND, interr(), STB::k0, num, SetILM_OPC, stb, and zero.
Referenced by exp_call(), and exp_load().
set_assn()
void set_assn (int nme)
...
Definition at line 4707 of file semutil.c.
References basesym_of(), and s.
Referenced by assign_intrinsic_to_pointer(), assign_pointer(), and mklvalue().
Variable Documentation
expb
EXP expb extern
Definition at line 27 of file expdf.cpp.