flang: expreg.cpp File Reference
expreg.cpp File Reference
Register allocation performed by the expander at opt level 1.
#include "expreg.h"
#include "gbldefs.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "ili.h"
#include "expand.h"
#include "regutil.h"
#include "machreg.h"
#include "machar.h"
Functions
static void assign1 (int rtype)
Assign registers for opt level 1.
void exp_rcand (int ilix, int nmex)
Add register candidate.
void reg_assign1 (void)
Control the assignment of the registers at opt level 1.
Variables
static int ilt
static LST * list
Detailed Description
Register allocation performed by the expander at opt level 1.
Definition in file expreg.cpp.
Function Documentation
assign1()
static void assign1 (int rtype) static
Assign registers for opt level 1.
The possible set of registers to use satisfies the relation first_global <= reg <= last_global, where the bounds are found in the mach_reg structure of the reg structure for the given register type. The registers are assigned beginning at last_global and continues down to first_global. The value returned by the function is the number of registers assigned.
Parameters
rtype type of registers
Definition at line 208 of file expreg.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad_aconi(), addilt(), ADDNODE, addr, aux, AUX::curr_entry, ENTRY::display, FLG::endian, flg, gbl, GET_RAT, getrcand(), IL_AADD, ILI_OPC, ILI_OPND, ilt, IS_DUM, IS_REGARG, list, mr_getreg(), MV_RTYPE, NME_SYM, NO_REG, NOSYM, RAT_ADDR, RAT_ATYPE, RAT_CONFL, RAT_MSIZE, RAT_REG, RAT_RTYPE, RAT_STORE, RAT_VAL, RATA_NME, REG::rcand, RCAND_IGNORE, RCAND_ISILI, RCAND_MSIZE, RCAND_STORE, RCAND_VAL, reg, RTYPE_DF, RU_PROG, and XBIT.
Referenced by reg_assign1().
exp_rcand()
void exp_rcand (int ilix, int nmex)
Add register candidate.
...
routine to add candidates to the register candidate lists of the register module. This routine is valid for opt 1 only. This routine is called only for load and store ILI and will eliminate a candidate which depend on their types, storage class, etc.
Definition at line 38 of file expreg.cpp.
References addrcand(), bihb, BIHB::csfg, DTY, IS_LCL_OR_DUM, NME_RAT, NME_SYM, NME_TYPE, NT_VAR, BIHB::parfg, BIHB::parsectfg, RCAND_IGNORE, BIHB::taskfg, and TY_ISSCALAR.
reg_assign1()
void reg_assign1 (void)
Control the assignment of the registers at opt level 1.
...
Definition at line 66 of file expreg.cpp.
References addilt(), assign1(), aux, BIH_ASSN, BIH_LABEL, BIH_NEXT, EXP::curbih, AUX::curr_entry, dmprat(), dmprcand(), endrcand(), exp_addbih(), expb, EXPDBG, ENTRY::first_ar, ENTRY::first_dp, ENTRY::first_dr, ENTRY::first_sp, freearea(), gbl, GET_RAT, getprint(), ilt, ILT_PREV, LST_TAG::item, list, LST_AREA, mr_end(), LST_TAG::next, NOSYM, RAT_VAL, RATA_AR, RATA_DP, RATA_IR, RATA_KR, RATA_SP, ratb, rdilts(), RATB::stg_avail, storedums(), and wrilts().
Referenced by exp_end().
Variable Documentation
ilt
int ilt static
Definition at line 23 of file expreg.cpp.
Referenced by assign1(), block_branches_to(), check_lineno(), collect_root_ilis(), dilt(), dumpblock(), dumpilt(), exp_scope_label(), hasExactlyOneStore(), insert_entry_label(), make_stmt(), printblock(), printblockline(), redundantLdLdElim(), reg_assign1(), schedule(), verify_beginscopes(), verify_endscopes(), widenAddressArith(), and widenInsertWideStore().
list
LST* list static
Definition at line 25 of file expreg.cpp.
Referenced by assign1(), and reg_assign1().