flang: expreg.h File Reference
expreg.h File Reference
Functions
void exp_rcand (int ilix, int nmex)
...
void reg_assign1 (void)
...
Function Documentation
exp_rcand()
void exp_rcand (int ilix, int nmex)
...
...
routine to add candidates to the register candidate lists of the register module. This routine is valid for opt 1 only. This routine is called only for load and store ILI and will eliminate a candidate which depend on their types, storage class, etc.
Definition at line 38 of file expreg.cpp.
References addrcand(), bihb, BIHB::csfg, DTY, IS_LCL_OR_DUM, NME_RAT, NME_SYM, NME_TYPE, NT_VAR, BIHB::parfg, BIHB::parsectfg, RCAND_IGNORE, BIHB::taskfg, and TY_ISSCALAR.
reg_assign1()
void reg_assign1 (void)
...
...
Definition at line 66 of file expreg.cpp.
References addilt(), assign1(), aux, BIH_ASSN, BIH_LABEL, BIH_NEXT, EXP::curbih, AUX::curr_entry, dmprat(), dmprcand(), endrcand(), exp_addbih(), expb, EXPDBG, ENTRY::first_ar, ENTRY::first_dp, ENTRY::first_dr, ENTRY::first_sp, freearea(), gbl, GET_RAT, getprint(), ilt, ILT_PREV, LST_TAG::item, list, LST_AREA, mr_end(), LST_TAG::next, NOSYM, RAT_VAL, RATA_AR, RATA_DP, RATA_IR, RATA_KR, RATA_SP, ratb, rdilts(), RATB::stg_avail, storedums(), and wrilts().
Referenced by exp_end().