flang: expsmp.cpp File Reference
expsmp.cpp File Reference
SMP expander routines.
#include "expsmp.h"
#include "exputil.h"
#include "exp_rte.h"
#include "dtypeutl.h"
#include "expatomics.h"
#include "regutil.h"
#include "machreg.h"
#include "ilm.h"
#include "ilmtp.h"
#include "ili.h"
#include "expand.h"
#include "machar.h"
#include "ccffinfo.h"
#include "kmpcutil.h"
#include "outliner.h"
#include "mp.h"
#include "mach.h"
#include "assem.h"
#include "llutil.h"
#include "llassem.h"
#include "ll_ftn.h"
#include "llmputil.h"
#include "symfun.h"
Classes
struct SectionsWrk_t
struct sptrListT
For use with generating an array filed with copyprivate addresses.
Macros
#define EXPANDER_DECLARE_INTERNAL
#define mk_prototype mk_prototype_llvm
#define TASK_LB taskLpInfo.lb_ili
#define TASK_LPVAR_OFFSET taskLpInfo.offset
#define TASK_UB taskLpInfo.ub_ili
#define TASK_ST taskLpInfo.st_ili
#define TASK_LASTITR taskLpInfo.lastitr
#define TASKLPARGS taskLpInfo.tasklpargs
#define TASKLP_TASK taskLpInfo.tasklpargs[TASKLPARG_TASK]
#define TASKLP_IF taskLpInfo.tasklpargs[TASKLPARG_IF_VAL]
#define TASKLP_LB taskLpInfo.tasklpargs[TASKLPARG_LB]
#define TASKLP_UB taskLpInfo.tasklpargs[TASKLPARG_UB]
#define TASKLP_ST taskLpInfo.tasklpargs[TASKLPARG_ST]
#define TASKLP_NOGROUP taskLpInfo.tasklpargs[TASKLPARG_NOGROUP]
#define TASKLP_SCHED taskLpInfo.tasklpargs[TASKLPARG_SCHED]
#define TASKLP_GRAINSIZE taskLpInfo.tasklpargs[TASKLPARG_GRAINSIZE]
#define TASKLP_TASKDUP taskLpInfo.tasklpargs[TASKLPARG_TASKDUP]
#define SECT_UB sectionsWrk.lb
#define SECT_LB sectionsWrk.ub
#define SECT_ST sectionsWrk.st
#define SECT_LAST sectionsWrk.last
#define SECT_CNT sectionsWrk.cnt
#define SECT_BBIH sectionsWrk.bbih
#define MP_NOT_IMPLEMENTED(_str) error(375, ERR_Fatal, 0, _str, NULL)
#define SET_MPPBIH 1
#define RESTORE_MPPBIH 0
#define IS_PREVMPPG 1
#define IS_NOTPREVMPPG 0
#define USE_NEXTBIH 1
#define NOTUSE_NEXTBIH 0
Typedefs
typedef struct SectionsWrk_t SectionsWrk_t
typedef struct sptrListT sptrListT
For use with generating an array filed with copyprivate addresses.
Enumerations
enum taskloooparg {
TASKLPARG_TASK = 0 , TASKLPARG_IF_VAL , TASKLPARG_LB , TASKLPARG_UB ,
TASKLPARG_ST , TASKLPARG_NOGROUP , TASKLPARG_SCHED , TASKLPARG_GRAINSIZE ,
TASKLPARG_TASKDUP , TASKLPARG_MAX
}
Functions
static int incrOutlinedCnt (void)
static int decrOutlinedCnt (void)
static int isUnnamedCs (int)
static int addMpUnp (void)
static int addMpUnv (void)
static int addMpBcsNest (void)
static int addMpEcsNest (void)
static int allocThreadprivate (SPTR sym, int *tmpthr)
C and Fortran threadprivate : for simple POD.
void exp_smp_init (void)
...
void exp_smp_fini (void)
...
static SPTR getPrivateTemp (DTYPE dtype)
static void expSmpSectionInit (void)
static void expSmpSectionEnd (void)
static int sectionCreateBlock (int nextLabel, SPTR lb, SPTR ub, int myVal)
void section_create_endblock (SPTR endLabel)
...
static void resetMppBih (int set, int eampp)
static void resetTaskBih (int set)
static void sptrListAdd (sptrListT **list, SPTR sptr, int size_ili, bool is_cmblk, int cplus_assign_rou, int vec_size_ili, SPTR o_sptr)
static void sptrListFree (sptrListT **list)
static int genSizeAcon (int size_ili)
static SPTR makeCopyprivArray (const sptrListT *list, bool pass_size_addresses)
static int mkMemcpy (void)
static int jsrAddArg (int arglist, ILI_OP opc, int argili)
...
static int makeCall (const char *fname, ILI_OP opc, int argili)
Return the ili of a call to a function with name fname, and argument list argili. If argili = 0, argument list is empty.
static void addCopyinInplace (const sptrListT *list)
static void makeCopyprivArray_tls (const sptrListT *list)
static int findEnlabBih (int func)
static void setTaskloopVars (SPTR lb, SPTR ub, SPTR stride, SPTR lastitr)
static int getElemSize (DTYPE dtype)
static void clearTaskloopInfo (void)
static int genIntStore (SPTR sym, int rhs)
static int genIntLoad (SPTR sym)
void exp_smp (ILM_OP opc, ILM *ilmp, int curilm)
...
SPTR lcpu_temp (SC_KIND sc)
...
SPTR ncpus_temp (SC_KIND sc)
...
int add_mp_p (SPTR semaphore)
Insert semaphore wait (enter critical section)
int add_mp_v (SPTR semaphore)
Insert semaphore signal (end critical section)
int add_mp_penter (int ispar)
...
int add_mp_pexit (void)
...
int add_mp_ncpus (void)
...
int add_mp_ncpus3 (void)
...
int add_mp_lcpu (void)
...
int add_mp_barrier2 (void)
...
void clear_tplnk (void)
...
void exp_mp_func_prologue (bool process_tp)
Generate any mp-specific prologue for a function.
int _make_mp_get_threadprivate (int data_ili, int size_ili, int cache_ili)
...
int get_threadprivate_origsize (int sym)
...
SPTR llTaskAllocSptr (void)
...
LLTask * llGetTask (int scope)
...
Variables
static int availIreg
static int availFreg
static int maxIreg
static int maxFreg
static int outlinedCnt
static int parCnt
static int parsectCnt
static int critCnt
static int taskbih
static int taskCnt
static int taskLoopCnt
static int taskBv
static int taskdup
static int taskIfv
static SPTR taskFlags
value of final clause for BTASK & TASKREG
static SPTR taskFnsptr
store task func sptr
static SPTR taskAllocSptr
store the return value from kmpc_alloc
static int maxOutlinedCnt
static int sumOutlinedCnt
static SPTR scopeSptr
static int * mppgbih
static int mppgcnt
static int mppgBihSiz
struct {
int lb_ili
int ub_ili
int st_ili
int lastitr
int flags
INT offset
int tasklpargs [10]
} taskLpInfo
static SectionsWrk_t sectionsWrk
Detailed Description
SMP expander routines.
Definition in file expsmp.cpp.
Macro Definition Documentation
EXPANDER_DECLARE_INTERNAL
#define EXPANDER_DECLARE_INTERNAL
Definition at line 22 of file expsmp.cpp.
IS_NOTPREVMPPG
#define IS_NOTPREVMPPG 0
Definition at line 304 of file expsmp.cpp.
IS_PREVMPPG
#define IS_PREVMPPG 1
Definition at line 303 of file expsmp.cpp.
mk_prototype
#define mk_prototype mk_prototype_llvm
Definition at line 61 of file expsmp.cpp.
MP_NOT_IMPLEMENTED
#define MP_NOT_IMPLEMENTED (_str) error(375, ERR_Fatal, 0, _str, NULL)
Definition at line 164 of file expsmp.cpp.
NOTUSE_NEXTBIH
#define NOTUSE_NEXTBIH 0
Definition at line 306 of file expsmp.cpp.
RESTORE_MPPBIH
#define RESTORE_MPPBIH 0
Definition at line 302 of file expsmp.cpp.
SECT_BBIH
#define SECT_BBIH sectionsWrk.bbih
Definition at line 162 of file expsmp.cpp.
SECT_CNT
#define SECT_CNT sectionsWrk.cnt
Definition at line 161 of file expsmp.cpp.
SECT_LAST
#define SECT_LAST sectionsWrk.last
Definition at line 160 of file expsmp.cpp.
SECT_LB
#define SECT_LB sectionsWrk.ub
Definition at line 158 of file expsmp.cpp.
SECT_ST
#define SECT_ST sectionsWrk.st
Definition at line 159 of file expsmp.cpp.
SECT_UB
#define SECT_UB sectionsWrk.lb
Definition at line 157 of file expsmp.cpp.
SET_MPPBIH
#define SET_MPPBIH 1
Definition at line 301 of file expsmp.cpp.
TASK_LASTITR
#define TASK_LASTITR taskLpInfo.lastitr
Definition at line 132 of file expsmp.cpp.
TASK_LB
#define TASK_LB taskLpInfo.lb_ili
Definition at line 128 of file expsmp.cpp.
TASK_LPVAR_OFFSET
#define TASK_LPVAR_OFFSET taskLpInfo.offset
Definition at line 129 of file expsmp.cpp.
TASK_ST
#define TASK_ST taskLpInfo.st_ili
Definition at line 131 of file expsmp.cpp.
TASK_UB
#define TASK_UB taskLpInfo.ub_ili
Definition at line 130 of file expsmp.cpp.
TASKLP_GRAINSIZE
#define TASKLP_GRAINSIZE taskLpInfo.tasklpargs[TASKLPARG_GRAINSIZE]
Definition at line 143 of file expsmp.cpp.
TASKLP_IF
#define TASKLP_IF taskLpInfo.tasklpargs[TASKLPARG_IF_VAL]
Definition at line 137 of file expsmp.cpp.
TASKLP_LB
#define TASKLP_LB taskLpInfo.tasklpargs[TASKLPARG_LB]
Definition at line 138 of file expsmp.cpp.
TASKLP_NOGROUP
#define TASKLP_NOGROUP taskLpInfo.tasklpargs[TASKLPARG_NOGROUP]
Definition at line 141 of file expsmp.cpp.
TASKLP_SCHED
#define TASKLP_SCHED taskLpInfo.tasklpargs[TASKLPARG_SCHED]
Definition at line 142 of file expsmp.cpp.
TASKLP_ST
#define TASKLP_ST taskLpInfo.tasklpargs[TASKLPARG_ST]
Definition at line 140 of file expsmp.cpp.
TASKLP_TASK
#define TASKLP_TASK taskLpInfo.tasklpargs[TASKLPARG_TASK]
Definition at line 136 of file expsmp.cpp.
TASKLP_TASKDUP
#define TASKLP_TASKDUP taskLpInfo.tasklpargs[TASKLPARG_TASKDUP]
Definition at line 144 of file expsmp.cpp.
TASKLP_UB
#define TASKLP_UB taskLpInfo.tasklpargs[TASKLPARG_UB]
Definition at line 139 of file expsmp.cpp.
TASKLPARGS
#define TASKLPARGS taskLpInfo.tasklpargs
Definition at line 135 of file expsmp.cpp.
USE_NEXTBIH
#define USE_NEXTBIH 1
Definition at line 305 of file expsmp.cpp.
Typedef Documentation
SectionsWrk_t
typedef struct SectionsWrk_t SectionsWrk_t
sptrListT
typedef struct sptrListT sptrListT
For use with generating an array filed with copyprivate addresses.
Enumeration Type Documentation
taskloooparg
enum taskloooparg
Enumerator
TASKLPARG_TASK
TASKLPARG_IF_VAL
TASKLPARG_LB
TASKLPARG_UB
TASKLPARG_ST
TASKLPARG_NOGROUP
TASKLPARG_SCHED
TASKLPARG_GRAINSIZE
TASKLPARG_TASKDUP
TASKLPARG_MAX
Definition at line 115 of file expsmp.cpp.
Function Documentation
_make_mp_get_threadprivate()
int _make_mp_get_threadprivate (int data_ili, int size_ili, int cache_ili)
...
Definition at line 3089 of file expsmp.cpp.
References ad1ili(), DT_CPTR, DT_INT, genretvalue(), getcon(), ili, jsrAddArg(), ll_get_gtid_val_ili(), makeCall(), mk_prototype, NULL, sel_iconv(), sptrListT::size_ili, and tmp.
Referenced by allocThreadprivate().
add_mp_barrier2()
int add_mp_barrier2 (void)
...
Definition at line 2951 of file expsmp.cpp.
add_mp_lcpu()
int add_mp_lcpu (void)
...
Definition at line 2945 of file expsmp.cpp.
add_mp_ncpus()
int add_mp_ncpus (void)
...
Definition at line 2933 of file expsmp.cpp.
add_mp_ncpus3()
int add_mp_ncpus3 (void)
...
Definition at line 2939 of file expsmp.cpp.
add_mp_p()
int add_mp_p (SPTR semaphore)
Insert semaphore wait (enter critical section)
Definition at line 2905 of file expsmp.cpp.
References ili, and ll_make_kmpc_critical().
Referenced by exp_smp().
add_mp_penter()
int add_mp_penter (int ispar)
...
Definition at line 2921 of file expsmp.cpp.
add_mp_pexit()
int add_mp_pexit (void)
...
Definition at line 2927 of file expsmp.cpp.
add_mp_v()
int add_mp_v (SPTR semaphore)
Insert semaphore signal (end critical section)
Definition at line 2913 of file expsmp.cpp.
References ili, and ll_make_kmpc_end_critical().
Referenced by exp_smp().
addCopyinInplace()
static void addCopyinInplace (const sptrListT * list) static
Definition at line 633 of file expsmp.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), addnme(), BIH_LABEL, ILTB::callfg, CC_EQ, chk_block(), cr_block(), EXP::curbih, DT_CPTR, expb, func, getlab(), i, ili, ILI_ALT, ILI_OPND, iltb, jsrAddArg(), list, ll_make_kmpc_barrier(), llGetThreadprivateAddr(), makeCall(), mk_address(), mkMemcpy(), sptrListT::next, NT_VAR, sptrListT::o_sptr, RFCNTI, sel_iconv(), sptrListT::size_ili, sptr, sptrListT::sptr, and wr_block().
Referenced by exp_smp().
addMpBcsNest()
static int addMpBcsNest (void) static
Definition at line 2889 of file expsmp.cpp.
References ili, and makeCall().
Referenced by exp_smp().
addMpEcsNest()
static int addMpEcsNest (void) static
Definition at line 2897 of file expsmp.cpp.
References ili, and makeCall().
Referenced by exp_smp().
addMpUnp()
static int addMpUnp (void) static
Definition at line 3073 of file expsmp.cpp.
References ili, ll_make_kmpc_critical(), and SPTR_NULL.
Referenced by exp_smp().
addMpUnv()
static int addMpUnv (void) static
Definition at line 3081 of file expsmp.cpp.
References ili, ll_make_kmpc_end_critical(), and SPTR_NULL.
Referenced by exp_smp().
allocThreadprivate()
static int allocThreadprivate (SPTR sym, int * tmpthr) static
C and Fortran threadprivate : for simple POD.
Definition at line 3114 of file expsmp.cpp.
References _make_mp_get_threadprivate(), ad3ili(), ad_acon(), ad_icon, addnme(), DTY, ll_make_kmpc_threadprivate_cached(), ll_set_new_threadprivate(), NOSYM, NT_VAR, size, size_of(), and XBIT.
Referenced by exp_mp_func_prologue().
clear_tplnk()
void clear_tplnk (void)
...
Definition at line 2960 of file expsmp.cpp.
References gbl, and NOSYM.
clearTaskloopInfo()
static void clearTaskloopInfo (void) static
Definition at line 881 of file expsmp.cpp.
References BZERO, offset, TASK_LPVAR_OFFSET, and taskLpInfo.
Referenced by exp_smp().
decrOutlinedCnt()
static int decrOutlinedCnt (void) static
Definition at line 3029 of file expsmp.cpp.
References ll_write_ilm_end(), outlinedCnt, and unsetRewritingILM().
Referenced by exp_smp().
exp_mp_func_prologue()
void exp_mp_func_prologue (bool process_tp)
Generate any mp-specific prologue for a function.
...
Definition at line 2973 of file expsmp.cpp.
References allocThreadprivate(), ILTB::callfg, chk_block(), CUDA_DEVICE, CUDA_GLOBAL, CUDAG, EXP::curbih, EXP::curilt, expb, EXPDBG, findEnlabBih(), func, gbl, GBL_CURRFUNC, has_multiple_entries(), iltb, ll_save_gtid_val(), NOSYM, rdilts(), SYMNAME, and wrilts().
Referenced by exp_end().
exp_smp()
void exp_smp (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 913 of file expsmp.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_acon(), ad_aconi(), ad_icon, ad_kconi(), add_mp_p(), add_mp_v(), addCopyinInplace(), addilt(), addMpBcsNest(), addMpEcsNest(), addMpUnp(), addMpUnv(), addnme(), addr, args, assert, BIH_CS, BIH_FT, BIH_LABEL, BIH_NOMERGE, BIH_PARLOOP, BIH_PARSECT, BIH_QJSR, bihb, ILTB::callfg, CC_EQ, CC_NE, ccff_info(), charlen(), chk_block(), _loop_args_t::chunk, clearTaskloopInfo(), cr_block(), critCnt, BIHB::csfg, EXP::curbih, EXP::curilt, DDTG, decrOutlinedCnt(), DT_CPTR, DT_INT, DTY, _loop_args_t::dtype, ERR_Fatal, ERR_Severe, exp_add_copy(), exp_label(), exp_mp_atomic_capture(), exp_mp_atomic_read(), exp_mp_atomic_update(), exp_mp_atomic_write(), exp_ompaccel_bpar(), exp_ompaccel_btarget(), exp_ompaccel_bteams(), exp_ompaccel_emap(), exp_ompaccel_epar(), exp_ompaccel_etarget(), exp_ompaccel_eteams(), exp_ompaccel_looptripcount(), exp_ompaccel_map(), exp_ompaccel_mploop(), exp_ompaccel_mploopfini(), exp_ompaccel_reductionitem(), exp_ompaccel_targetdata(), expb, expSmpSectionEnd(), expSmpSectionInit(), extent_of(), finish_taskdup_routine(), FLANG_FALLTHROUGH, flg, gbl, GBL_CURRFUNC, genIntLoad(), genIntStore(), get_isz_cval(), getccsym_copy(), getElemSize(), getlab(), getnewccsym(), getPrivateTemp(), STB::i0, IL_AADD, ili, ILI_OF, ILMB::ilm_base, ILM_DTyOPND, ILM_OPND, ilm_outlined_pad_ilm(), ILM_RESULT, ILM_SymOPND, ilmb, ILT_PREV, iltb, incrOutlinedCnt(), interr(), IS_OMP_DEVICE_CG, IS_PREVMPPG, isUnnamedCs(), ISZ_T, KMP_DISTRIBUTE_STATIC, KMP_DISTRIBUTE_STATIC_CHUNKED, KMP_DISTRIBUTE_STATIC_CHUNKED_CHUNKONE, KMP_ORD_DYNAMIC_CHUNKED, KMP_ORD_STATIC, KMP_SCH_STATIC, KMP_SCH_STATIC_CHUNKED, label, last, _loop_args_t::last, lastitr, lb, ld, ldst_msz(), ll_get_gtid_val_ili(), ll_get_hostprog_arg(), ll_ilm_is_rewriting(), ll_load_outlined_args(), ll_make_kmpc_barrier(), ll_make_kmpc_cancel(), ll_make_kmpc_cancellationpoint(), ll_make_kmpc_copyprivate(), ll_make_kmpc_dispatch_fini(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_end_master(), ll_make_kmpc_end_ordered(), ll_make_kmpc_end_serialized_parallel(), ll_make_kmpc_end_single(), ll_make_kmpc_end_taskgroup(), ll_make_kmpc_flush(), ll_make_kmpc_for_static_fini(), ll_make_kmpc_for_static_init(), ll_make_kmpc_for_static_init_args(), ll_make_kmpc_fork_call(), ll_make_kmpc_fork_teams(), ll_make_kmpc_master(), ll_make_kmpc_ordered(), ll_make_kmpc_push_num_teams(), ll_make_kmpc_push_num_threads(), ll_make_kmpc_push_proc_bind(), ll_make_kmpc_serialized_parallel(), ll_make_kmpc_single(), ll_make_kmpc_task(), ll_make_kmpc_task_arg(), ll_make_kmpc_task_begin_if0(), ll_make_kmpc_task_complete_if0(), ll_make_kmpc_task_wait(), ll_make_kmpc_task_yield(), ll_make_kmpc_taskgroup(), ll_make_kmpc_taskloop(), ll_make_outlined_call2(), ll_make_outlined_func(), ll_make_outlined_func_wopc(), ll_make_outlined_task(), ll_make_outlined_task_call(), ll_make_sections_args(), ll_make_tgt_target_data_end(), ll_process_routine_parameters(), ll_rewrite_ilms(), ll_write_ilm_header(), llGetTask(), llmp_task_add_loopvar(), llmp_task_add_private(), llmp_task_set_fnsptr(), llWriteNopILM(), load, lower(), _loop_args_t::lower, makeCopyprivArray(), makeCopyprivArray_tls(), mk_address(), mkfunc(), MP_SCH_BLK_ALN, MP_SCH_BLK_CYC, MP_SCH_CHUNK_1, mp_sched_to_kmpc_sched(), MP_TASK_FINAL, MP_TASK_GRAINSIZE, MP_TASK_IF, MP_TASK_NOGROUP, MP_TASK_NUM_TASKS, MP_TASK_UNTIED, mp_to_kmpc_tasking_flags(), mppgbih, mppgBihSiz, mppgcnt, MSGOPENMP, msz, MSZ_WORD, NEED, NT_IND, NT_VAR, NULL, off, offset, OMPACCEL_DEFAULT_DEVICEID, ompaccel_tinfo_current_get_targetdata(), ompaccel_tinfo_set_mode_next_target(), FLG::omptarget, OPENMP, FLG::opt, outlinedCnt, parsectCnt, BIHB::parsectfg, rdilts(), resetMppBih(), resetTaskBih(), restartRewritingILM(), RESTORE_MPPBIH, RFCNTI, EXP::sc, SC_AUTO, _loop_args_t::sched, scopeSptr, SECT_BBIH, SECT_CNT, SECT_LAST, SECT_LB, SECT_ST, SECT_UB, sectionCreateBlock(), sel_iconv(), SET_MPPBIH, setTaskloopVars(), size, size_of(), sptr, SPTR_NULL, sptrListAdd(), sptrListFree(), st, start_taskdup(), stb, stop_taskdup(), stride, _loop_args_t::stride, SYMNAME, sz, task, TASK_LASTITR, TASK_LB, TASK_LPVAR_OFFSET, TASK_ST, TASK_UB, taskAllocSptr, taskbih, taskBv, taskCnt, taskdup, taskFlags, taskFnsptr, taskIfv, taskLoopCnt, TASKLP_GRAINSIZE, TASKLP_IF, TASKLP_LB, TASKLP_NOGROUP, TASKLP_SCHED, TASKLP_ST, TASKLP_TASK, TASKLP_TASKDUP, TASKLP_UB, TASKLPARGS, ub, unsetRewritingILM(), _loop_args_t::upper, upper(), _loop_args_t::upperd, wr_block(), wrilts(), FLG::x, XBIT, and zsize_of().
Referenced by eval_ilm().
exp_smp_fini()
void exp_smp_fini (void)
...
Definition at line 199 of file expsmp.cpp.
References FREE, maxOutlinedCnt, mppgbih, and sumOutlinedCnt.
Referenced by expand().
exp_smp_init()
void exp_smp_init (void)
...
Definition at line 181 of file expsmp.cpp.
References critCnt, expb, EXP::lcpu2, EXP::lcpu3, maxOutlinedCnt, mppgbih, mppgBihSiz, mppgcnt, EXP::ncpus2, NEW, outlinedCnt, parCnt, parsectCnt, taskCnt, and taskLoopCnt.
Referenced by exp_init().
expSmpSectionEnd()
static void expSmpSectionEnd (void) static
Definition at line 234 of file expsmp.cpp.
References getPrivateTemp(), SECT_BBIH, SECT_CNT, SECT_LAST, SECT_LB, SECT_ST, and SECT_UB.
Referenced by exp_smp().
expSmpSectionInit()
static void expSmpSectionInit (void) static
Definition at line 217 of file expsmp.cpp.
References EXP::curbih, expb, gbl, getPrivateTemp(), SC_AUTO, SECT_BBIH, SECT_CNT, SECT_LAST, SECT_LB, SECT_ST, and SECT_UB.
Referenced by exp_smp().
findEnlabBih()
static int findEnlabBih (int func) static
Definition at line 786 of file expsmp.cpp.
References BIH_NEXT, and func.
Referenced by exp_mp_func_prologue().
genIntLoad()
static int genIntLoad (SPTR sym) static
Definition at line 901 of file expsmp.cpp.
References ad3ili(), ad_acon(), addnme(), ili, MSZ_WORD, and NT_VAR.
Referenced by exp_smp().
genIntStore()
static int genIntStore (SPTR sym, int rhs) static
Definition at line 889 of file expsmp.cpp.
References ad4ili(), ad_acon(), addnme(), ili, MSZ_WORD, and NT_VAR.
Referenced by exp_smp().
genSizeAcon()
static int genSizeAcon (int size_ili) static
Definition at line 398 of file expsmp.cpp.
References ad1ili(), ad4ili(), ad_acon(), addnme(), chk_block(), DT_INT, getPrivateTemp(), ili, MSZ_I8, MSZ_WORD, NT_VAR, SC_AUTO, sptrListT::size_ili, TARGET_PTRSIZE, and tmp.
Referenced by makeCopyprivArray().
get_threadprivate_origsize()
int get_threadprivate_origsize (int sym)
...
Definition at line 3207 of file expsmp.cpp.
References ad_icon, DTY, NOSYM, size, and size_of().
getElemSize()
static int getElemSize (DTYPE dtype) static
Definition at line 867 of file expsmp.cpp.
References DTY, DTyAlgTySize, and DTySeqTyElement.
Referenced by exp_smp().
getPrivateTemp()
static SPTR getPrivateTemp (DTYPE dtype) static
Definition at line 206 of file expsmp.cpp.
References count, GBL_CURRFUNC, getnewccsym(), and sptr.
Referenced by exp_smp(), expSmpSectionEnd(), expSmpSectionInit(), and genSizeAcon().
incrOutlinedCnt()
static int incrOutlinedCnt (void) static
Definition at line 3040 of file expsmp.cpp.
References maxOutlinedCnt, outlinedCnt, and parCnt.
Referenced by exp_smp().
isUnnamedCs()
static int isUnnamedCs (int sem) static
Definition at line 3064 of file expsmp.cpp.
References sem, and SYMNAME.
Referenced by exp_smp().
jsrAddArg()
static int jsrAddArg (int arglist, ILI_OP opc, int argili) static
...
Parameters
arglist
opc IL_DAIR/IL_DAAR/IL_DADP/IL_DASP/IL_ARGxx (x86)
argili
Add argument expression argili to existing argument list arglist using opcode opc. If arglist = 0, begin a new list.
Definition at line 546 of file expsmp.cpp.
References ad1ili(), ad2ili(), ad3ili(), assert, availFreg, availIreg, ERR_Fatal, ili, IR, is_daili_opcode(), and SP.
Referenced by _make_mp_get_threadprivate(), addCopyinInplace(), and makeCopyprivArray_tls().
lcpu_temp()
SPTR lcpu_temp (SC_KIND sc)
...
Definition at line 2857 of file expsmp.cpp.
References DT_INT, getcctemp_sc(), and name.
llGetTask()
LLTask * llGetTask (int scope)
...
Definition at line 3257 of file expsmp.cpp.
References assert, ERR_Fatal, llmp_create_task(), llmp_get_task(), scope, scopeSptr, sptr, and task.
Referenced by exp_smp().
llTaskAllocSptr()
SPTR llTaskAllocSptr (void)
...
Definition at line 3251 of file expsmp.cpp.
References taskAllocSptr.
Referenced by cloneUplevel(), and ll_load_outlined_args().
makeCall()
static int makeCall (const char * fname, ILI_OP opc, int argili) static
Return the ili of a call to a function with name fname, and argument list argili. If argili = 0, argument list is empty.
Parameters
fname function name
opc IL_QJSR/IL_JSR
argili argument list
Definition at line 603 of file expsmp.cpp.
References ad1ili(), ad2ili(), availFreg, availIreg, fname, ili, maxFreg, maxIreg, mkfunc(), share_proc_ili, and share_qjsr_ili.
Referenced by _make_mp_get_threadprivate(), addCopyinInplace(), addMpBcsNest(), addMpEcsNest(), and makeCopyprivArray_tls().
makeCopyprivArray()
static SPTR makeCopyprivArray (const sptrListT * list, bool pass_size_addresses) static
Definition at line 440 of file expsmp.cpp.
References ad3ili(), ad4ili(), ad_acon(), ad_aconi(), AD_DPTR, ad_icon, AD_LWBD, AD_NUMELM, AD_UPBD, add_arrnme(), addnme(), chk_block(), DT_CPTR, DT_INT, genSizeAcon(), get_array_dtype(), getcon(), getnewccsym(), i, STB::i1, ili, sptrListT::is_common_block, list, mk_address(), MSZ_I8, MSZ_WORD, sptrListT::next, NT_ARR, NT_VAR, ref_threadprivate(), ref_threadprivate_var(), SC_AUTO, sptrListT::size_ili, sptrListT::sptr, stb, and TARGET_PTRSIZE.
Referenced by exp_smp().
makeCopyprivArray_tls()
static void makeCopyprivArray_tls (const sptrListT * list) static
Definition at line 716 of file expsmp.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_acon(), addnme(), BIH_LABEL, ILTB::callfg, CC_EQ, chk_block(), cr_block(), EXP::curbih, DT_CPTR, expb, func, getlab(), i, ili, ILI_ALT, iltb, jsrAddArg(), list, ll_make_kmpc_barrier(), makeCall(), mk_address(), mkMemcpy(), sptrListT::next, NT_VAR, sptrListT::o_sptr, RFCNTI, sel_iconv(), sptrListT::size_ili, sptr, sptrListT::sptr, and wr_block().
Referenced by exp_smp().
mkMemcpy()
static int mkMemcpy (void) static
Definition at line 527 of file expsmp.cpp.
References DT_CPTR, func, mk_prototype, mkfunc(), and NULL.
Referenced by addCopyinInplace(), and makeCopyprivArray_tls().
ncpus_temp()
SPTR ncpus_temp (SC_KIND sc)
...
Definition at line 2873 of file expsmp.cpp.
References DT_INT, getcctemp_sc(), and name.
resetMppBih()
static void resetMppBih (int set, int eampp) static
Definition at line 309 of file expsmp.cpp.
References EXP::curbih, EXP::curilt, expb, flg, ILT_PREV, mppgbih, mppgcnt, rdilts(), set, wr_block(), wrilts(), and FLG::x.
Referenced by exp_smp().
resetTaskBih()
static void resetTaskBih (int set) static
Definition at line 340 of file expsmp.cpp.
References EXP::curbih, EXP::curilt, expb, flg, ILT_PREV, rdilts(), set, taskbih, wr_block(), wrilts(), and FLG::x.
Referenced by exp_smp().
section_create_endblock()
void section_create_endblock (SPTR endLabel)
...
Definition at line 280 of file expsmp.cpp.
References BIH_LABEL, ILTB::callfg, chk_block(), cr_block(), EXP::curbih, exp_label(), expb, ili, iltb, ll_make_kmpc_barrier(), ll_make_kmpc_for_static_fini(), and wr_block().
sectionCreateBlock()
static int sectionCreateBlock (int nextLabel, SPTR lb, SPTR ub, int myVal) static
Definition at line 245 of file expsmp.cpp.
References ad3ili(), ad4ili(), ad_acon(), ad_icon, addnme(), CC_GT, CC_LT, chk_block(), ili, lb, MSZ_WORD, NT_VAR, RFCNTI, and ub.
Referenced by exp_smp().
setTaskloopVars()
static void setTaskloopVars (SPTR lb, SPTR ub, SPTR stride, SPTR lastitr) static
Definition at line 794 of file expsmp.cpp.
References ad2ili(), ad3ili(), ad4ili(), ad_acon(), ad_aconi(), addnme(), arg, basenm, chk_block(), cr_block(), EXP::curbih, DT_INT, expb, GBL_CURRFUNC, IL_AADD, ili, kimove(), lastitr, lb, ld, ldst_msz(), ll_get_hostprog_arg(), mk_address(), mk_argasym(), msz, MSZ_I8, NT_IND, NT_VAR, st, stride, TASK_LPVAR_OFFSET, ub, wr_block(), and zsize_of().
Referenced by exp_smp().
sptrListAdd()
static void sptrListAdd (sptrListT ** list, SPTR sptr, int size_ili, bool is_cmblk, int cplus_assign_rou, int vec_size_ili, SPTR o_sptr) static
Definition at line 365 of file expsmp.cpp.
References sptrListT::cplus_assign_rou, sptrListT::is_common_block, list, malloc(), sptrListT::next, sptrListT::o_sptr, sptrListT::size_ili, sptr, sptrListT::sptr, and sptrListT::vec_size_ili.
Referenced by exp_smp().
sptrListFree()
static void sptrListFree (sptrListT ** list) static
Definition at line 381 of file expsmp.cpp.
References list, n, next, and NULL.
Referenced by exp_smp().
Variable Documentation
availFreg
int availFreg static
Definition at line 64 of file expsmp.cpp.
Referenced by jsrAddArg(), and makeCall().
availIreg
int availIreg static
Definition at line 63 of file expsmp.cpp.
Referenced by jsrAddArg(), and makeCall().
critCnt
int critCnt static
Definition at line 71 of file expsmp.cpp.
Referenced by exp_smp(), and exp_smp_init().
flags
int flags
Definition at line 110 of file expsmp.cpp.
lastitr
int lastitr
Definition at line 109 of file expsmp.cpp.
Referenced by exp_smp(), and setTaskloopVars().
lb_ili
int lb_ili
Definition at line 106 of file expsmp.cpp.
maxFreg
int maxFreg static
Definition at line 66 of file expsmp.cpp.
Referenced by makeCall().
maxIreg
int maxIreg static
Definition at line 65 of file expsmp.cpp.
Referenced by makeCall().
maxOutlinedCnt
int maxOutlinedCnt static
Definition at line 90 of file expsmp.cpp.
Referenced by exp_smp_fini(), exp_smp_init(), and incrOutlinedCnt().
mppgbih
int* mppgbih static
Definition at line 101 of file expsmp.cpp.
Referenced by exp_smp(), exp_smp_fini(), exp_smp_init(), and resetMppBih().
mppgBihSiz
int mppgBihSiz static
Definition at line 103 of file expsmp.cpp.
Referenced by exp_smp(), and exp_smp_init().
mppgcnt
int mppgcnt static
Definition at line 102 of file expsmp.cpp.
Referenced by exp_smp(), exp_smp_init(), and resetMppBih().
offset
INT offset
Definition at line 111 of file expsmp.cpp.
Referenced by clearTaskloopInfo(), and exp_smp().
outlinedCnt
int outlinedCnt static
Definition at line 68 of file expsmp.cpp.
Referenced by decrOutlinedCnt(), exp_smp(), exp_smp_init(), and incrOutlinedCnt().
parCnt
int parCnt static
Definition at line 69 of file expsmp.cpp.
Referenced by exp_smp_init(), and incrOutlinedCnt().
parsectCnt
int parsectCnt static
Definition at line 70 of file expsmp.cpp.
Referenced by exp_smp(), and exp_smp_init().
scopeSptr
SPTR scopeSptr static
Definition at line 100 of file expsmp.cpp.
Referenced by exp_smp(), and llGetTask().
sectionsWrk
SectionsWrk_t sectionsWrk static
Definition at line 155 of file expsmp.cpp.
st_ili
int st_ili
Definition at line 108 of file expsmp.cpp.
sumOutlinedCnt
int sumOutlinedCnt static
Definition at line 91 of file expsmp.cpp.
Referenced by exp_smp_fini().
taskAllocSptr
SPTR taskAllocSptr static
store the return value from kmpc_alloc
Definition at line 89 of file expsmp.cpp.
Referenced by cloneUplevel(), exp_smp(), handle_nested_threadprivate(), ll_load_outlined_args(), llTaskAllocSptr(), loadUplevelArgsForRegion(), and toUplevelAddr().
taskbih
int taskbih static
Definition at line 72 of file expsmp.cpp.
Referenced by exp_smp(), and resetTaskBih().
taskBv
int taskBv static
Definition at line 75 of file expsmp.cpp.
Referenced by exp_smp().
taskCnt
int taskCnt static
Definition at line 73 of file expsmp.cpp.
Referenced by exp_smp(), and exp_smp_init().
taskdup
int taskdup static
Definition at line 85 of file expsmp.cpp.
Referenced by exp_smp().
taskFlags
SPTR taskFlags static
value of final clause for BTASK & TASKREG
Definition at line 87 of file expsmp.cpp.
Referenced by exp_smp().
taskFnsptr
SPTR taskFnsptr static
store task func sptr
Definition at line 88 of file expsmp.cpp.
Referenced by exp_smp().
taskIfv
int taskIfv static
Definition at line 86 of file expsmp.cpp.
Referenced by exp_smp().
taskLoopCnt
int taskLoopCnt static
Definition at line 74 of file expsmp.cpp.
Referenced by exp_smp(), and exp_smp_init().
tasklpargs
int tasklpargs[10]
Definition at line 112 of file expsmp.cpp.
struct { ... } taskLpInfo
Referenced by clearTaskloopInfo().
ub_ili
int ub_ili
Definition at line 107 of file expsmp.cpp.