flang: expsmp.h File Reference
expsmp.h File Reference
#include "gbldefs.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "expand.h"
#include "llmputil.h"
Functions
int add_mp_barrier2 (void)
...
int add_mp_lcpu (void)
...
int add_mp_ncpus3 (void)
...
int add_mp_ncpus (void)
...
int add_mp_penter (int ispar)
...
int add_mp_pexit (void)
...
int add_mp_p (SPTR semaphore)
Insert semaphore wait (enter critical section)
int add_mp_v (SPTR semaphore)
Insert semaphore signal (end critical section)
int get_threadprivate_origsize (int sym)
...
SPTR lcpu_temp (SC_KIND sc)
...
SPTR llTaskAllocSptr (void)
...
int _make_mp_get_threadprivate (int data_ili, int size_ili, int cache_ili)
...
SPTR ncpus_temp (SC_KIND sc)
...
LLTask * llGetTask (int scope)
...
void clear_tplnk (void)
...
void exp_mp_func_prologue (bool)
...
void exp_smp_fini (void)
...
void exp_smp (ILM_OP opc, ILM *ilmp, int curilm)
...
void exp_smp_init (void)
...
void section_create_endblock (SPTR endLabel)
...
Function Documentation
_make_mp_get_threadprivate()
int _make_mp_get_threadprivate (int data_ili, int size_ili, int cache_ili)
...
Definition at line 3089 of file expsmp.cpp.
References ad1ili(), DT_CPTR, DT_INT, genretvalue(), getcon(), ili, jsrAddArg(), ll_get_gtid_val_ili(), makeCall(), mk_prototype, NULL, sel_iconv(), sptrListT::size_ili, and tmp.
Referenced by allocThreadprivate().
add_mp_barrier2()
int add_mp_barrier2 (void)
...
Definition at line 2951 of file expsmp.cpp.
add_mp_lcpu()
int add_mp_lcpu (void)
...
Definition at line 2945 of file expsmp.cpp.
add_mp_ncpus()
int add_mp_ncpus (void)
...
Definition at line 2933 of file expsmp.cpp.
add_mp_ncpus3()
int add_mp_ncpus3 (void)
...
Definition at line 2939 of file expsmp.cpp.
add_mp_p()
int add_mp_p (SPTR semaphore)
Insert semaphore wait (enter critical section)
Definition at line 2905 of file expsmp.cpp.
References ili, and ll_make_kmpc_critical().
Referenced by exp_smp().
add_mp_penter()
int add_mp_penter (int ispar)
...
Definition at line 2921 of file expsmp.cpp.
add_mp_pexit()
int add_mp_pexit (void)
...
Definition at line 2927 of file expsmp.cpp.
add_mp_v()
int add_mp_v (SPTR semaphore)
Insert semaphore signal (end critical section)
Definition at line 2913 of file expsmp.cpp.
References ili, and ll_make_kmpc_end_critical().
Referenced by exp_smp().
clear_tplnk()
void clear_tplnk (void)
...
Definition at line 2960 of file expsmp.cpp.
References gbl, and NOSYM.
exp_mp_func_prologue()
void exp_mp_func_prologue (bool process_tp)
...
...
Definition at line 2973 of file expsmp.cpp.
References allocThreadprivate(), ILTB::callfg, chk_block(), CUDA_DEVICE, CUDA_GLOBAL, CUDAG, EXP::curbih, EXP::curilt, expb, EXPDBG, findEnlabBih(), func, gbl, GBL_CURRFUNC, has_multiple_entries(), iltb, ll_save_gtid_val(), NOSYM, rdilts(), SYMNAME, and wrilts().
Referenced by exp_end().
exp_smp()
void exp_smp (ILM_OP opc, ILM * ilmp, int curilm)
...
Definition at line 913 of file expsmp.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_acon(), ad_aconi(), ad_icon, ad_kconi(), add_mp_p(), add_mp_v(), addCopyinInplace(), addilt(), addMpBcsNest(), addMpEcsNest(), addMpUnp(), addMpUnv(), addnme(), addr, args, assert, BIH_CS, BIH_FT, BIH_LABEL, BIH_NOMERGE, BIH_PARLOOP, BIH_PARSECT, BIH_QJSR, bihb, ILTB::callfg, CC_EQ, CC_NE, ccff_info(), charlen(), chk_block(), _loop_args_t::chunk, clearTaskloopInfo(), cr_block(), critCnt, BIHB::csfg, EXP::curbih, EXP::curilt, DDTG, decrOutlinedCnt(), DT_CPTR, DT_INT, DTY, _loop_args_t::dtype, ERR_Fatal, ERR_Severe, exp_add_copy(), exp_label(), exp_mp_atomic_capture(), exp_mp_atomic_read(), exp_mp_atomic_update(), exp_mp_atomic_write(), exp_ompaccel_bpar(), exp_ompaccel_btarget(), exp_ompaccel_bteams(), exp_ompaccel_emap(), exp_ompaccel_epar(), exp_ompaccel_etarget(), exp_ompaccel_eteams(), exp_ompaccel_looptripcount(), exp_ompaccel_map(), exp_ompaccel_mploop(), exp_ompaccel_mploopfini(), exp_ompaccel_reductionitem(), exp_ompaccel_targetdata(), expb, expSmpSectionEnd(), expSmpSectionInit(), extent_of(), finish_taskdup_routine(), FLANG_FALLTHROUGH, flg, gbl, GBL_CURRFUNC, genIntLoad(), genIntStore(), get_isz_cval(), getccsym_copy(), getElemSize(), getlab(), getnewccsym(), getPrivateTemp(), STB::i0, IL_AADD, ili, ILI_OF, ILMB::ilm_base, ILM_DTyOPND, ILM_OPND, ilm_outlined_pad_ilm(), ILM_RESULT, ILM_SymOPND, ilmb, ILT_PREV, iltb, incrOutlinedCnt(), interr(), IS_OMP_DEVICE_CG, IS_PREVMPPG, isUnnamedCs(), ISZ_T, KMP_DISTRIBUTE_STATIC, KMP_DISTRIBUTE_STATIC_CHUNKED, KMP_DISTRIBUTE_STATIC_CHUNKED_CHUNKONE, KMP_ORD_DYNAMIC_CHUNKED, KMP_ORD_STATIC, KMP_SCH_STATIC, KMP_SCH_STATIC_CHUNKED, label, last, _loop_args_t::last, lastitr, lb, ld, ldst_msz(), ll_get_gtid_val_ili(), ll_get_hostprog_arg(), ll_ilm_is_rewriting(), ll_load_outlined_args(), ll_make_kmpc_barrier(), ll_make_kmpc_cancel(), ll_make_kmpc_cancellationpoint(), ll_make_kmpc_copyprivate(), ll_make_kmpc_dispatch_fini(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_end_master(), ll_make_kmpc_end_ordered(), ll_make_kmpc_end_serialized_parallel(), ll_make_kmpc_end_single(), ll_make_kmpc_end_taskgroup(), ll_make_kmpc_flush(), ll_make_kmpc_for_static_fini(), ll_make_kmpc_for_static_init(), ll_make_kmpc_for_static_init_args(), ll_make_kmpc_fork_call(), ll_make_kmpc_fork_teams(), ll_make_kmpc_master(), ll_make_kmpc_ordered(), ll_make_kmpc_push_num_teams(), ll_make_kmpc_push_num_threads(), ll_make_kmpc_push_proc_bind(), ll_make_kmpc_serialized_parallel(), ll_make_kmpc_single(), ll_make_kmpc_task(), ll_make_kmpc_task_arg(), ll_make_kmpc_task_begin_if0(), ll_make_kmpc_task_complete_if0(), ll_make_kmpc_task_wait(), ll_make_kmpc_task_yield(), ll_make_kmpc_taskgroup(), ll_make_kmpc_taskloop(), ll_make_outlined_call2(), ll_make_outlined_func(), ll_make_outlined_func_wopc(), ll_make_outlined_task(), ll_make_outlined_task_call(), ll_make_sections_args(), ll_make_tgt_target_data_end(), ll_process_routine_parameters(), ll_rewrite_ilms(), ll_write_ilm_header(), llGetTask(), llmp_task_add_loopvar(), llmp_task_add_private(), llmp_task_set_fnsptr(), llWriteNopILM(), load, lower(), _loop_args_t::lower, makeCopyprivArray(), makeCopyprivArray_tls(), mk_address(), mkfunc(), MP_SCH_BLK_ALN, MP_SCH_BLK_CYC, MP_SCH_CHUNK_1, mp_sched_to_kmpc_sched(), MP_TASK_FINAL, MP_TASK_GRAINSIZE, MP_TASK_IF, MP_TASK_NOGROUP, MP_TASK_NUM_TASKS, MP_TASK_UNTIED, mp_to_kmpc_tasking_flags(), mppgbih, mppgBihSiz, mppgcnt, MSGOPENMP, msz, MSZ_WORD, NEED, NT_IND, NT_VAR, NULL, off, offset, OMPACCEL_DEFAULT_DEVICEID, ompaccel_tinfo_current_get_targetdata(), ompaccel_tinfo_set_mode_next_target(), FLG::omptarget, OPENMP, FLG::opt, outlinedCnt, parsectCnt, BIHB::parsectfg, rdilts(), resetMppBih(), resetTaskBih(), restartRewritingILM(), RESTORE_MPPBIH, RFCNTI, EXP::sc, SC_AUTO, _loop_args_t::sched, scopeSptr, SECT_BBIH, SECT_CNT, SECT_LAST, SECT_LB, SECT_ST, SECT_UB, sectionCreateBlock(), sel_iconv(), SET_MPPBIH, setTaskloopVars(), size, size_of(), sptr, SPTR_NULL, sptrListAdd(), sptrListFree(), st, start_taskdup(), stb, stop_taskdup(), stride, _loop_args_t::stride, SYMNAME, sz, task, TASK_LASTITR, TASK_LB, TASK_LPVAR_OFFSET, TASK_ST, TASK_UB, taskAllocSptr, taskbih, taskBv, taskCnt, taskdup, taskFlags, taskFnsptr, taskIfv, taskLoopCnt, TASKLP_GRAINSIZE, TASKLP_IF, TASKLP_LB, TASKLP_NOGROUP, TASKLP_SCHED, TASKLP_ST, TASKLP_TASK, TASKLP_TASKDUP, TASKLP_UB, TASKLPARGS, ub, unsetRewritingILM(), _loop_args_t::upper, upper(), _loop_args_t::upperd, wr_block(), wrilts(), FLG::x, XBIT, and zsize_of().
Referenced by eval_ilm().
exp_smp_fini()
void exp_smp_fini (void)
...
Definition at line 199 of file expsmp.cpp.
References FREE, maxOutlinedCnt, mppgbih, and sumOutlinedCnt.
Referenced by expand().
exp_smp_init()
void exp_smp_init (void)
...
Definition at line 181 of file expsmp.cpp.
References critCnt, expb, EXP::lcpu2, EXP::lcpu3, maxOutlinedCnt, mppgbih, mppgBihSiz, mppgcnt, EXP::ncpus2, NEW, outlinedCnt, parCnt, parsectCnt, taskCnt, and taskLoopCnt.
Referenced by exp_init().
get_threadprivate_origsize()
int get_threadprivate_origsize (int sym)
...
Definition at line 3207 of file expsmp.cpp.
References ad_icon, DTY, NOSYM, size, and size_of().
lcpu_temp()
SPTR lcpu_temp (SC_KIND sc)
...
Definition at line 2857 of file expsmp.cpp.
References DT_INT, getcctemp_sc(), and name.
llGetTask()
LLTask * llGetTask (int scope)
...
Definition at line 3257 of file expsmp.cpp.
References assert, ERR_Fatal, llmp_create_task(), llmp_get_task(), scope, scopeSptr, sptr, and task.
Referenced by exp_smp().
llTaskAllocSptr()
SPTR llTaskAllocSptr (void)
...
Definition at line 3251 of file expsmp.cpp.
References taskAllocSptr.
Referenced by cloneUplevel(), and ll_load_outlined_args().
ncpus_temp()
SPTR ncpus_temp (SC_KIND sc)
...
Definition at line 2873 of file expsmp.cpp.
References DT_INT, getcctemp_sc(), and name.
section_create_endblock()
void section_create_endblock (SPTR endLabel)
...
Definition at line 280 of file expsmp.cpp.
References BIH_LABEL, ILTB::callfg, chk_block(), cr_block(), EXP::curbih, exp_label(), expb, ili, iltb, ll_make_kmpc_barrier(), ll_make_kmpc_for_static_fini(), and wr_block().