flang: exputil.cpp File Reference
exputil.cpp File Reference
Expander utility routines.
#include "exputil.h"
#include "expreg.h"
#include "dinit.h"
#include "dinitutl.h"
#include "dtypeutl.h"
#include "llassem.h"
#include "ilm.h"
#include "ilmtp.h"
#include "fih.h"
#include "ili.h"
#include "iliutil.h"
#include "expand.h"
#include "machar.h"
#include "regutil.h"
#include "machreg.h"
#include "symfun.h"
Macros
#define EXPANDER_DECLARE_INTERNAL
#define DO_PFO (XBIT(148, 0x1000) && !XBIT(148, 0x4000))
#define getSptr_bnd_con get_bnd_con
#define DINITSWTAB_put(c, s)
#define DINITSWTAB_put2(c, s, t)
Functions
static void propagate_bihflags (void)
static void flsh_saveili (void)
Put out expb.saveili if necesssary.
void mkarglist (int cnt, DTYPE dt)
Make an argument list.
void cr_block (void)
Create a block during expand.
void wr_block (void)
Write a block during expand.
void flsh_block (void)
Close current block and write out.
void chk_block (int newili)
Check for end of ILT block.
void chk_block_suppress_throw (int newili)
Like chk_block, but suppress CAN_THROW flag.
int check_ilm (int ilmx, int ilix)
Check an ILM which has been evaluated.
void put_funccount (void)
...
int mk_swlist (INT n, SWEL *swhdr, int doinit)
Make a switch list for the intrinsic.
int access_swtab_base_label (int base_label, int sptr, int flag)
...
int access_swtab_case_label (int case_label, int *case_val, int sptr, int flag)
...
int mk_swtab (INT n, SWEL *swhdr, int deflab, int doinit)
Make a switch address table.
int mk_swtab_ll (INT n, SWEL *swhdr, int deflab, int doinit)
...
SPTR mk_argasym (int sptr)
Make a sym for an arg's address.
SPTR find_argasym (int sptr)
...
int mk_impsym (SPTR sptr)
...
SPTR mkfunc_cncall (const char *nmptr)
...
static const char * skipws (const char *q)
SPTR mkfunc_sflags (const char *nmptr, const char *flags)
...
void exp_add_copy (SPTR lhssptr, SPTR rhssptr)
add IL_LD of the rhs, IL_ST to the lhs, for two integer-type symbols
SPTR get_byval_local (int argsptr)
...
int add_reg_arg_ili (int arglist, int argili, int nmex, DTYPE dtype)
Add a register argument.
void expdumpilms ()
...
Detailed Description
Expander utility routines.
Definition in file exputil.cpp.
Macro Definition Documentation
DINITSWTAB_put
#define DINITSWTAB_put (c, s)
Definition at line 891 of file exputil.cpp.
DINITSWTAB_put2
#define DINITSWTAB_put2 (c, s, t)
Definition at line 892 of file exputil.cpp.
DO_PFO
#define DO_PFO (XBIT(148, 0x1000) && !XBIT(148, 0x4000))
Definition at line 33 of file exputil.cpp.
EXPANDER_DECLARE_INTERNAL
#define EXPANDER_DECLARE_INTERNAL
Definition at line 23 of file exputil.cpp.
getSptr_bnd_con
#define getSptr_bnd_con get_bnd_con
Definition at line 40 of file exputil.cpp.
Function Documentation
access_swtab_base_label()
int access_swtab_base_label (int base_label, int sptr, int flag)
...
Definition at line 766 of file exputil.cpp.
References FREE, gbl, mode, NEW, next, prev, and sptr.
access_swtab_case_label()
int access_swtab_case_label (int case_label, int * case_val, int sptr, int flag)
...
Definition at line 835 of file exputil.cpp.
References FREE, NEW, next, prev, and sptr.
add_reg_arg_ili()
int add_reg_arg_ili (int arglist, int argili, int nmex, DTYPE dtype)
Add a register argument.
...
Add argument expression argili to existing argument list, arglist, using registers. If arglist = 0, begin a new list.
Definition at line 1241 of file exputil.cpp.
References ad1ili(), ad3ili(), DT_ISINT, DTY, IL_RES, ILI_OPC, ILIA_KR, IR, SP, and TY_DBLE.
check_ilm()
int check_ilm (int ilmx, int ilix)
Check an ILM which has been evaluated.
...
This routine checks an ILM which has already been evaluated (i.e., the ILM is referenced again). Depending on the type of the ili which defines this ILM, certain actions may occur to "redefine" the ILM (i.e., create a new ILI for the ILM).
Parameters
ilmx – ILM index of the ILM evaluated
ilix – ILI index of the ILI for the ILM
Definition at line 418 of file exputil.cpp.
References ad3ili(), ad4ili(), ad_acon(), ad_cse(), ad_load(), addilt(), addnme(), ADDRCAND, base, BIH_FINDEX, BIH_FTAG, bihb, BIHB::callfg, ILTB::callfg, cse, EXP::curbih, FIHB::currfindex, FIHB::currftag, ERR_Severe, expb, EXPDBG, fihb, gbl, i, IL_TYPE, ILI_OPC, ILI_OPND, ILMB::ilm_base, ILM_BLOCK, ILM_NME, ILM_OPC, ILM_OPND, ilmb, ilms, ILT_ILIP, ILT_PREV, iltb, ILTY_ARTH, ILTY_CONS, ILTY_DEFINE, ILTY_LOAD, ILTY_MOVE, ILTY_OTHER, ILTY_PLOAD, ILTY_PSTORE, ILTY_STORE, IM_OPRFLAG, IM_TYPE, IM_VAR, IMTY_ARTH, interr(), is_freeili_opcode(), BIHB::ldvol, ILTB::ldvol, len, mkrtemp_sc(), MSZ_F16, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_WORD, ILMINFO::name, EXP::nilms, NT_IND, NT_VAR, OPR_LNK, ILMINFO::oprs, propagate_bihflags(), qjsr_in(), BIHB::qjsrfg, ILTB::qjsrfg, rdilts(), EXP::sc, SPTR_NULL, BIHB::stvol, ILTB::stvol, use, and wrilts().
Referenced by eval_ilm().
chk_block()
void chk_block (int newili)
Check for end of ILT block.
...
Check if the current block is at its end. newili locates an ili tree which represents an ili statement.
Definition at line 242 of file exputil.cpp.
References ad1ili(), addilt(), BIH_ILTLAST, EXP::bits, ILTB::callfg, compl_br(), cr_block(), EXP::curbih, EXP::curilt, expb, EXPDBG, EXP::flags, flg, flsh_saveili(), gbl, IL_OPRFLAG, IL_TYPE, ili, ILI_OPC, ILI_OPND, ILIO_SYM, ilis, ILT_BR, ILT_CAN_THROW, ILT_ILIP, ILT_PREV, iltb, ILTY_BRANCH, ILIINFO::oprs, FLG::opt, reduce_ilt(), RFCNTD, EXP::saveili, void(), EXP::waitlbl, wr_block(), and XBIT.
Referenced by chk_block_suppress_throw(), and exp_add_copy().
chk_block_suppress_throw()
void chk_block_suppress_throw (int newili)
Like chk_block, but suppress CAN_THROW flag.
...
When a call can throw and defines two result registers, we have an ad-hoc rule that only the second store is marked as "can throw". This utility is useful for ensuring that the first store is not marked "can throw".
Definition at line 401 of file exputil.cpp.
References chk_block(), EXP::curilt, expb, and ILT_SET_CAN_THROW.
cr_block()
void cr_block (void)
Create a block during expand.
...
Definition at line 89 of file exputil.cpp.
References ad1ili(), ad2ili(), addilt(), BIH_GUARDEE, BIH_LINENO, EXP::bits, EXP::curbih, EXP::curilt, EXP::curlin, EXP::dbgline, exp_addbih(), expb, EXPDBG, EXP::flags, gbl, ILT_DBGLINE, ILT_NEXT, ILT_PREV, EXP::isguarded, mkfunc(), and EXP::noblock.
Referenced by chk_block(), and flsh_saveili().
exp_add_copy()
void exp_add_copy (SPTR lhssptr, SPTR rhssptr)
add IL_LD of the rhs, IL_ST to the lhs, for two integer-type symbols
Definition at line 1175 of file exputil.cpp.
References ad3ili(), ad4ili(), ad_acon(), addnme(), chk_block(), ERR_Severe, interr(), msz, MSZ_BYTE, MSZ_I8, MSZ_SHWORD, MSZ_WORD, NT_VAR, size_of(), and sz.
Referenced by exp_smp().
expdumpilms()
void expdumpilms (void)
...
Definition at line 1278 of file exputil.cpp.
References _dumponeilm(), BOS_SIZE, check(), gbl, ILMB::globalilmcount, ILMB::globalilmstart, i, ILMB::ilm_base, ILM_BLOCK, ILM_EXPANDED_FOR, ILM_IRESULT, ILM_MXLEN, ILM_NME, ILM_RESTYPE, ILM_RESULT, ILM_SCALE, ILMB::ilmavl, ilmb, j, and NULL.
find_argasym()
SPTR find_argasym (int sptr)
...
Definition at line 1081 of file exputil.cpp.
References DT_CPTR, lookupsym(), name, sptr, SPTR_NULL, and strlen().
flsh_block()
void flsh_block (void)
Close current block and write out.
...
Definition at line 168 of file exputil.cpp.
References flsh_saveili(), and wr_block().
Referenced by exp_end(), exp_header(), and exp_misc().
flsh_saveili()
static void flsh_saveili (void) static
Put out expb.saveili if necesssary.
May be an unadded ili if expb.flags.bits.waitlbl is set
Definition at line 179 of file exputil.cpp.
References addilt(), EXP::bits, ILTB::callfg, cr_block(), EXP::curilt, expb, EXPDBG, EXP::flags, flg, gbl, iltb, ILTB::ldvol, FLG::opt, ILTB::qjsrfg, EXP::saveili, ILTB::stvol, EXP::waitlbl, and wr_block().
Referenced by chk_block(), and flsh_block().
get_byval_local()
SPTR get_byval_local (int argsptr)
...
Definition at line 1209 of file exputil.cpp.
References getsymbol(), SPTR_NULL, strlen(), and SYMNAME.
Referenced by cp_byval_mem_arg(), and pp_params().
mk_argasym()
SPTR mk_argasym (int sptr)
Make a sym for an arg's address.
...
Definition at line 1041 of file exputil.cpp.
References DT_CPTR, gbl, getccsym(), and sptr.
Referenced by charaddr(), cloneUplevel(), cp_memarg(), create_llvm_display_temp(), create_ref(), exp_call(), exp_header(), exp_type_bound_proc_call(), get_chain_pointer_closure(), get_sdsc_element(), llLoadGtid(), llvmAddConcurEntryBlk(), loadUplevelArgsForRegion(), pp_params(), pp_params_mixedstrlen(), and setTaskloopVars().
mk_impsym()
int mk_impsym (SPTR sptr)
...
Definition at line 1095 of file exputil.cpp.
References FLANG_FALLTHROUGH, getsname(), getsymbol(), MAXIDLEN, sptr, and SYMNAME.
mk_swlist()
int mk_swlist (INT n, SWEL * swhdr, int doinit)
Make a switch list for the intrinsic.
...
The switch list consists of the number of cases which occurred, the default label, and followed by the pairs (in sorted order based on case values) of case values and their respective case labels.
Definition at line 729 of file exputil.cpp.
References ad_acon(), SWEL::clabel, DINIT_LABEL, DINIT_LOC, dinit_put(), DT_INT, DTySetArrayDesc, expb, get_bnd_con(), get_type(), getccsym(), i, n, SWEL::next, put_funccount(), switch_base, EXP::swtcnt, and SWEL::val.
mk_swtab()
int mk_swtab (INT n, SWEL * swhdr, int deflab, int doinit)
Make a switch address table.
...
Definition at line 897 of file exputil.cpp.
References SWEL::clabel, DEFLABP, DINIT_LABEL, DINIT_LOC, DINITSWTAB_put, DT_CPTR, ERR_Warning, expb, getccsym(), i, interr(), n, SWEL::next, RFCNTI, switch_base, EXP::swtcnt, and SWEL::val.
Referenced by genswitch().
mk_swtab_ll()
int mk_swtab_ll (INT n, SWEL * swhdr, int deflab, int doinit)
...
Definition at line 962 of file exputil.cpp.
References add64(), SWEL::clabel, cmp64(), CONVAL2G, DEFLABP, DINIT_LABEL, DINIT_LOC, dinit_put(), ERR_Warning, expb, getccsym(), i, interr(), n, SWEL::next, one, RFCNTI, sub64(), switch_base, EXP::swtcnt, SWEL::val, and zero.
mkarglist()
void mkarglist (int cnt, DTYPE dt)
Make an argument list.
...
Create a compiler generated array temporary for an argument list. its size is cnt and its dtype is dt. NOTE that the caller may modify the size of this array (a target may require alignment other than int). mkarglist guarantees reuse as long as expb.arglcnt.next is reset to expb.arglcnt.start.
Definition at line 52 of file exputil.cpp.
References AD_DPTR, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_SCHECK, AD_UPBD, ad_val_of(), AD_ZBASE, EXP::arglcnt, EXP::arglist, cnt, dt, expb, get_array_dtype(), getccsym(), getSptr_bnd_con, STB::i1, EXP::max, EXP::next, SC_AUTO, and stb.
mkfunc_cncall()
SPTR mkfunc_cncall (const char * nmptr)
...
Definition at line 1127 of file exputil.cpp.
References mkfunc(), and sptr.
Referenced by exp_strcpy().
mkfunc_sflags()
SPTR mkfunc_sflags (const char * nmptr, const char * flags)
...
Definition at line 1146 of file exputil.cpp.
References ERR_Severe, flags, interr(), mkfunc(), p, skipws(), sptr, and XBIT.
propagate_bihflags()
static void propagate_bihflags (void) static
Definition at line 142 of file exputil.cpp.
References BIH_ASM, BIH_CS, BIH_EX, BIH_LDVOL, BIH_PAR, BIH_PARSECT, BIH_QJSR, BIH_STVOL, BIH_TASK, bihb, BIHB::callfg, BIHB::csfg, EXP::curbih, expb, BIHB::gasm, BIHB::ldvol, BIHB::parfg, BIHB::parsectfg, BIHB::qjsrfg, BIHB::stvol, and BIHB::taskfg.
Referenced by check_ilm(), and wr_block().
put_funccount()
void put_funccount (void)
...
Definition at line 716 of file exputil.cpp.
References DINIT_FUNCCOUNT, dinit_put(), and gbl.
Referenced by mk_swlist().
skipws()
static const char * skipws (const char * q) static
Definition at line 1138 of file exputil.cpp.
References q.
Referenced by mkfunc_sflags().
wr_block()
void wr_block (void)
Write a block during expand.
...
Definition at line 112 of file exputil.cpp.
References BIH_FT, bihb, EXP::bits, BIHB::callfg, EXP::callfg, EXP::curbih, expb, EXPDBG, EXP::flags, BIHB::gasm, gbl, ILI_OPC, EXP::ilm_words, ILT_BR, ILT_ILIP, ILT_PREV, EXP::noblock, propagate_bihflags(), and wrilts().
Referenced by chk_block(), flsh_block(), and flsh_saveili().