flang: exterf.c File Reference
exterf.c File Reference
Routines for exporting symbols to .mod files and to IPA.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "dtypeutl.h"
#include "machar.h"
#include "semant.h"
#include "ast.h"
#include "dinit.h"
#include "soc.h"
#include "lz.h"
#include "trace.h"
#include "interf.h"
#include "fih.h"
#include "dpm_out.h"
Classes
struct itemx
struct xitemx
Macros
#define TRACEFLAG 48
#define TRACEBIT 4
#define TRACESTRING "export"
#define INSIDE_INTERF
#define COMPILER_OWNED_MODULE XBIT(58, 0x100000)
#define MOD_AREA 18
#define APPEND_AREA 19
#define MAX_FNAME_LEN 2050
#define PUTFIELD(f) lzprintf(outlz, " %d", stb.stg_base[sptr].f)
#define PUTISZ_FIELD(f) lzprintf(outlz, " %" ISZ_PF "d", stb.stg_base[sptr].f)
#define ADDBIT(f)
#define ADDBIT(fl)
#define ADDBIT(f)
Typedefs
typedef struct itemx ITEMX
typedef struct xitemx XITEMX
Functions
static void queue_symbol (int)
static void rqueue_ast (int ast, int *unused)
static void queue_ast (int ast)
static void queue_dtype (int dtype)
static void export_dtypes (int, int)
static void export_outer_derived_dtypes (int limit)
static void export_dt (int)
static void export_symbol (int)
static void export_one_ast (int)
static void export_iso_c_libraries (void)
static void export_iso_fortran_env_libraries (void)
static void export_ieee_arith_libraries (void)
static void export_one_std (int)
static void queue_one_std (int std)
static void all_stds (void(*)(int))
static void export_data_file (int)
static void export_component_init (int)
static void export_data_file_asts (ast_visit_fn, int, int, int)
static void export_component_init_asts (ast_visit_fn, int, int)
static void export_equivs (void)
static int dtype_skip (int dtype)
void export_public_module (int module, int exceptlist)
static lzhandle * export_header (FILE *fd, const char *export_name, int compress)
static void export (FILE *export_fd, char *export_name, int cleanup)
void export_inline (FILE *export_fd, char *export_name, char *file_name)
void export_module (FILE *module_file, char *export_name, int modulesym, int cleanup)
Save the module file for use when exporting contained subprograms.
void export_append_sym (int sym)
static void mark_idstr (int ast, int *unused)
void mark_dtype_ast_idstr (int dtype)
void export_append_host_sym (int sym)
void export_fix_host_append_list (int(*newsym)(int))
static void export_some_init ()
static void export_some_procedure (int sptr)
static void export_some_args (int sptr, int limitsptr)
static void export_some_fini (int limitsptr, int limitast)
static void fixup_host_symbol_dtype (int sptr)
void export_host_subprogram (FILE *host_file, int host_sym, int limitsptr, int limitast, int limitdtype)
void export_module_subprogram (FILE *subprog_file, int subprog_sym, int limitsptr, int limitast, int limitdtype)
void exterf_init ()
void exterf_init_host ()
static VAR * export_ivl_asts (VAR *ivl, ast_visit_fn astproc)
static void export_ict_asts (ACL *ict, ast_visit_fn astproc, int queuesym, int queuedtype, int domarkdtype)
static void export_ivl_ict_asts (VAR *ivl, ACL *ict, ast_visit_fn astproc, int queuesym, int queuedtype, int domarkdtype)
static VAR * export_ivl (VAR *ivl)
static void export_ict (ACL *ict)
static void export_ivl_ict (int lineno, VAR *ivl, ACL *ict, int dostructures)
static void add_to_private_mod_list (int sptr)
static void export_derived_dt (int dtype)
static void export_equiv_item (int evp)
void set_tag ()
Variables
static char * symbol_flag
static int symbol_flag_size
static int symbol_flag_lowest_const = 0
static char * dtype_flag
static int dtype_flag_size
static char * ast_flag
static int ast_flag_size
static int ast_flag_lowest_const = 0
static char * eqv_flag
static XITEMX * public_module_list = NULL
static ITEMX * private_module_list = NULL
static ITEMX * append_list
static LOGICAL for_module = FALSE
static LOGICAL for_inliner = FALSE
static int sym_module = 0
static LOGICAL for_contained = FALSE
static LOGICAL exporting_module = FALSE
static lzhandle * outlz
static int exportmode = 0
static int out_platform = MOD_ANY
EXPORTB exportb
static ITEMX * host_append_list
static int max_tag = 0
Detailed Description
Routines for exporting symbols to .mod files and to IPA.
Definition in file exterf.c.
Macro Definition Documentation
ADDBIT [1/3]
#define ADDBIT (f)
Value:
  if (stb.stg_base[sptr].f)                                                    \
    flags |= bit;                                                              \
  bit <<= 1;
ADDBIT [2/3]
#define ADDBIT (f)
Value:
  if (astb.std.stg_base[std].flags.bits.f)                                     \
    flags |= bit;                                                              \
  bit <<= 1;
ADDBIT [3/3]
#define ADDBIT (fl)
Value:
  if (astb.stg_base[ast].fl)                                                   \
    flags |= bit;                                                              \
  bit <<= 1;
APPEND_AREA
#define APPEND_AREA 19
Definition at line 57 of file exterf.c.
COMPILER_OWNED_MODULE
#define COMPILER_OWNED_MODULE XBIT(58, 0x100000)
Definition at line 34 of file exterf.c.
INSIDE_INTERF
#define INSIDE_INTERF
Definition at line 28 of file exterf.c.
MAX_FNAME_LEN
#define MAX_FNAME_LEN 2050
Definition at line 92 of file exterf.c.
MOD_AREA
#define MOD_AREA 18
Definition at line 52 of file exterf.c.
PUTFIELD
#define PUTFIELD (f) lzprintf(outlz, " %d", stb.stg_base[sptr].f)
PUTISZ_FIELD
#define PUTISZ_FIELD (f) lzprintf(outlz, " %" ISZ_PF "d", stb.stg_base[sptr].f)
TRACEBIT
#define TRACEBIT 4
Definition at line 24 of file exterf.c.
TRACEFLAG
#define TRACEFLAG 48
Definition at line 23 of file exterf.c.
TRACESTRING
#define TRACESTRING "export"
Definition at line 25 of file exterf.c.
Typedef Documentation
ITEMX
typedef struct itemx ITEMX
XITEMX
typedef struct xitemx XITEMX
Function Documentation
add_to_private_mod_list()
static void add_to_private_mod_list (int sptr) static
Definition at line 1630 of file exterf.c.
References getitem(), MOD_AREA, p, private_module_list, and sptr.
Referenced by queue_symbol().
all_stds()
static void all_stds (void(*)(int) callproc) static
Definition at line 2871 of file exterf.c.
References std, and STD_NEXT.
Referenced by export().
dtype_skip()
static int dtype_skip (int dtype) static
Definition at line 2047 of file exterf.c.
References dlen(), and DTY.
Referenced by export_component_init(), export_component_init_asts(), export_dtypes(), and export_outer_derived_dtypes().
export()
static void export (FILE * export_fd, char * export_name, int cleanup) static
Definition at line 235 of file exterf.c.
References all_stds(), append_list, ast, EXPORTB::ast, ast_flag, ast_flag_lowest_const, ast_flag_size, ast_unvisit(), ast_visit(), astb, BZERO, cleanup(), DBGBIT, DLL_EXPORT, DLLP, EXPORTB::dt, STB::dt, dtype_flag, dtype_flag_size, EQV, SEM::eqv_avail, eqv_flag, EQV_NUMSS, EQV_SS, SEM::eqvlist, export_component_init(), export_component_init_asts(), export_data_file(), export_data_file_asts(), export_dtypes(), export_equivs(), export_header(), export_ieee_arith_libraries(), export_iso_c_libraries(), export_iso_fortran_env_libraries(), export_one_ast(), export_one_std(), export_symbol(), exportb, exporting_module, FALSE, fflush(), STB::firstosym, ASTB::firstuast, STB::firstusym, for_inliner, for_module, FREE, freearea(), gbl, EXPORTB::hmark, j, lzfinifile(), lzprintf(), EXPORTB::maxast, EXPORTB::maxsptr, MOD_AREA, SEM::mod_dllexport, NEW, next, xitemx::next, NULL, outlz, private_module_list, public_module_list, queue_ast(), queue_one_std(), queue_symbol(), rqueue_ast(), sem, sptr, ss, stb, substring, sym_module, symbol_flag, symbol_flag_lowest_const, symbol_flag_size, symdmp(), Trace, TRUE, and xitemx::val.
Referenced by export_inline(), and export_module().
export_append_host_sym()
void export_append_host_sym (int sym)
Definition at line 621 of file exterf.c.
References APPEND_AREA, getitem(), host_append_list, p, SYMNAME, and Trace.
Referenced by restore_host_state().
export_append_sym()
void export_append_sym (int sym)
Definition at line 575 of file exterf.c.
References APPEND_AREA, append_list, getitem(), p, SYMNAME, and Trace.
Referenced by declsym(), and mod_add_subprogram().
export_component_init()
static void export_component_init (int cleanup) static
Definition at line 1306 of file exterf.c.
References _acl::ci_exprt, cleanup(), STB::dt, DTY, dtype_skip(), export_ict(), get_getitem_p(), and stb.
Referenced by export().
export_component_init_asts()
static void export_component_init_asts (ast_visit_fn astproc, int queuesym, int queuedtype) static
Definition at line 1139 of file exterf.c.
References STB::dt, DTY, dtype_skip(), export_ict_asts(), get_getitem_p(), and stb.
Referenced by export().
export_data_file()
static void export_data_file (int dostructures) static
Definition at line 1326 of file exterf.c.
References astb, ASTB::df, export_ivl_ict(), lineno, and NULL.
Referenced by export().
export_data_file_asts()
static void export_data_file_asts (ast_visit_fn astproc, int queuesym, int queuedtype, int domarkdtype) static
Definition at line 1099 of file exterf.c.
References assert, astb, ASTB::df, export_ivl_ict_asts(), lineno, and NULL.
Referenced by export().
export_derived_dt()
static void export_derived_dt (int dtype) static
Definition at line 2176 of file exterf.c.
References base, DTY, lzprintf(), outlz, scope, sptr, and SYMNAME.
Referenced by export_outer_derived_dtypes().
export_dt()
static void export_dt (int dtype) static
Definition at line 2056 of file exterf.c.
References AD_ADJARR, AD_ASSUMSHP, AD_ASSUMSZ, AD_DEFER, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_MLPYR, AD_NOBOUNDS, AD_NUMDIM, AD_NUMELM, AD_UPAST, AD_UPBD, AD_ZBASE, aux, AUX::dpdsc_base, DTY, i, interr(), lzprintf(), ndims, outlz, TY_CHAR, and TY_NCHAR.
Referenced by export_dtypes().
export_dtypes()
static void export_dtypes (int start, int ignore) static
Definition at line 2140 of file exterf.c.
References STB::dt, DTY, dtype_flag, dtype_flag_size, dtype_skip(), export_dt(), mem(), NOSYM, start, stb, and TY_CHAR.
Referenced by export(), export_host_subprogram(), and export_module_subprogram().
export_equiv_item()
static void export_equiv_item (int evp) static
Definition at line 3053 of file exterf.c.
References EQV, EQV_NUMSS, EQV_SS, j, lineno, lzprintf(), outlz, sptr, ss, and substring.
Referenced by export_equivs().
export_equivs()
static void export_equivs (void) static
Definition at line 3090 of file exterf.c.
References EQV, eqv_flag, SEM::eqvlist, export_equiv_item(), next, and sem.
Referenced by export(), and export_some_fini().
export_fix_host_append_list()
void export_fix_host_append_list (int(*)(int) newsym)
Definition at line 633 of file exterf.c.
References host_append_list, newsym(), NULL, p, and Trace.
Referenced by import_host_subprogram().
export_header()
static lzhandle * export_header (FILE * fd, const char * export_name, int compress) static
Definition at line 183 of file exterf.c.
References base, COMPILER_OWNED_MODULE, compress(), count, xitemx::exceptlist, fd, STB::firstosym, for_contained, for_inliner, for_module, gbl, i, imported_directly(), lz(), lzinitfile(), lzprintf(), xitemx::next, out_platform, p, private_module_list, public_module_list, stb, strlen(), SYMI_NEXT, SYMI_SPTR, SYMNAME, xitemx::val, and XBIT.
Referenced by export(), export_host_subprogram(), and export_module_subprogram().
export_host_subprogram()
void export_host_subprogram (FILE * host_file, int host_sym, int limitsptr, int limitast, int limitdtype)
Definition at line 790 of file exterf.c.
References ADD_DEFER, ast_unvisit(), ast_visit(), DTY, export_dtypes(), export_header(), export_outer_derived_dtypes(), export_some_args(), export_some_fini(), export_some_init(), export_some_procedure(), export_symbol(), FALSE, fflush(), fixup_host_symbol_dtype(), for_contained, gbl, host_append_list, interr(), limitsptr, lzfinifile(), mark_dtype_ast_idstr(), SEM::mod_cnt, SEM::mod_sym, NULL, outlz, p, queue_symbol(), sem, sym_module, SYMNAME, Trace, and TRUE.
Referenced by restore_host_state().
export_ict()
static void export_ict (ACL * ict) static
Definition at line 1174 of file exterf.c.
References AC_ACONST, AC_AST, AC_CONST, AC_ICONST, AC_IDENT, AC_IDO, AC_IEXPR, AC_REPEAT, AC_SCONST, AC_TYPEINIT, AC_VMSSTRUCT, AC_VMSUNION, _acl::ast, BINOP, _acl::doinfo, _acl::dtype, export_ict(), _acl::expr, _acl::i, _acl::id, DOINFO::index_var, DOINFO::init_expr, interr(), _acl::is_const, DOINFO::limit_expr, AEXPR::lop, lzprintf(), _acl::next, NULL, AEXPR::op, outlz, _acl::ptrdtype, _acl::repeatc, AEXPR::rop, _acl::sptr, DOINFO::step_expr, _acl::subc, and _acl::u1.
Referenced by export_component_init(), export_ict(), and export_ivl_ict().
export_ict_asts()
static void export_ict_asts (ACL * ict, ast_visit_fn astproc, int queuesym, int queuedtype, int domarkdtype) static
Definition at line 998 of file exterf.c.
References AC_IDO, AC_IEXPR, _acl::ast, ast_traverse(), astb, BINOP, DOINFO::count, _acl::doinfo, DTY, _acl::dtype, export_ict_asts(), _acl::expr, _acl::id, DOINFO::index_var, DOINFO::init_expr, DOINFO::limit_expr, AEXPR::lop, _acl::next, NULL, _acl::ptrdtype, queue_dtype(), queue_symbol(), _acl::repeatc, AEXPR::rop, _acl::sptr, DOINFO::step_expr, _acl::subc, and _acl::u1.
Referenced by export_component_init_asts(), export_ict_asts(), and export_ivl_ict_asts().
export_ieee_arith_libraries()
void export_ieee_arith_libraries (void) static
Definition at line 531 of file exterf.c.
References exportb, get_ieee_arith_intrin(), EXPORTB::ieee_arith_library, lzprintf(), outlz, sptr, SYMNAME, and Trace.
Referenced by export().
export_inline()
void export_inline (FILE * export_fd, char * export_name, char * file_name)
Definition at line 543 of file exterf.c.
References export(), FALSE, fclose(), for_inliner, gbl, sym_module, and TRUE.
Referenced by extractor().
export_iso_c_libraries()
void export_iso_c_libraries (void) static
Definition at line 500 of file exterf.c.
References exportb, first, iso_c_lib_stat(), EXPORTB::iso_c_library, last, lookupsymbol(), lzprintf(), outlz, sptr, SYMNAME, and Trace.
Referenced by export().
export_iso_fortran_env_libraries()
void export_iso_fortran_env_libraries (void) static
Definition at line 518 of file exterf.c.
References exportb, EXPORTB::iso_fortran_env_library, lookupsymbol(), lzprintf(), outlz, sptr, and SYMNAME.
Referenced by export().
export_ivl()
static VAR * export_ivl (VAR * ivl) static
Definition at line 1155 of file exterf.c.
References VAR::dtype, export_ivl(), VAR::id, lzprintf(), VAR::next, NULL, outlz, VAR::ptr, VAR::u, Varref, and VAR::varref.
Referenced by export_ivl(), and export_ivl_ict().
export_ivl_asts()
static VAR * export_ivl_asts (VAR * ivl, ast_visit_fn astproc) static
Definition at line 984 of file exterf.c.
References ast_traverse(), export_ivl_asts(), VAR::id, VAR::next, NULL, VAR::ptr, VAR::u, Varref, and VAR::varref.
Referenced by export_ivl_asts(), and export_ivl_ict_asts().
export_ivl_ict()
static void export_ivl_ict (int lineno, VAR * ivl, ACL * ict, int dostructures) static
Definition at line 1256 of file exterf.c.
References Doend, Dostart, VAR::dostart, export_ict(), export_ivl(), for_module, VAR::id, VAR::indvar, lineno, VAR::lowbd, lzprintf(), next, VAR::next, NULL, outlz, VAR::ptr, sptr, VAR::step, _acl::subc, sym_of_ast(), VAR::u, VAR::upbd, Varref, and VAR::varref.
Referenced by export_data_file().
export_ivl_ict_asts()
static void export_ivl_ict_asts (VAR * ivl, ACL * ict, ast_visit_fn astproc, int queuesym, int queuedtype, int domarkdtype) static
Definition at line 1063 of file exterf.c.
References ast_traverse(), Doend, Dostart, VAR::dostart, export_ict_asts(), export_ivl_asts(), exportmode, VAR::id, VAR::indvar, VAR::lowbd, next, VAR::next, NULL, queue_symbol(), _acl::sptr, VAR::step, _acl::subc, VAR::u, VAR::upbd, and Varref.
Referenced by export_data_file_asts().
export_module()
void export_module (FILE * module_file, char * export_name, int modulesym, int cleanup)
Save the module file for use when exporting contained subprograms.
Definition at line 562 of file exterf.c.
References cleanup(), export(), exporting_module, FALSE, for_module, sym_module, Trace, and TRUE.
Referenced by export_all().
export_module_subprogram()
void export_module_subprogram (FILE * subprog_file, int subprog_sym, int limitsptr, int limitast, int limitdtype)
Definition at line 845 of file exterf.c.
References append_list, ast_unvisit(), ast_visit(), DLL_EXPORT, DLLP, export_dtypes(), export_header(), export_some_args(), export_some_fini(), export_some_init(), export_some_procedure(), export_symbol(), FALSE, fflush(), FLANG_FALLTHROUGH, for_contained, gbl, interr(), limitsptr, lzfinifile(), SEM::mod_dllexport, SEM::mod_sym, NOSYM, NULL, outlz, p, queue_symbol(), sem, sptr, stb, sym_module, symbol_flag, SYMNAME, Trace, and TRUE.
Referenced by reset_module_state().
export_one_ast()
static void export_one_ast (int ast) static
Definition at line 2735 of file exterf.c.
References a, A_ARGCNTG, ADDBIT, ARGT_ARG, ASD_NDIM, ASD_SUBS, ast, astb, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, cnt, exportmode, f2, flags, FLANG_FALLTHROUGH, gbl, i, lzprintf(), n, outlz, s, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, SYMNAME, and XBIT.
Referenced by export(), and export_some_fini().
export_one_std()
static void export_one_std (int std) static
Definition at line 2839 of file exterf.c.
References ADDBIT, cs, exportmode, flags, lzprintf(), outlz, par, parsect, st, std, STD_AST, STD_LABEL, and STD_LINENO.
Referenced by export().
export_outer_derived_dtypes()
static void export_outer_derived_dtypes (int limit) static
Definition at line 2203 of file exterf.c.
References dtype_flag, dtype_flag_size, dtype_skip(), and export_derived_dt().
Referenced by export_host_subprogram().
export_public_module()
void export_public_module (int module, int exceptlist)
Definition at line 162 of file exterf.c.
References xitemx::exceptlist, getitem(), MOD_AREA, p, public_module_list, and same_sym_list().
Referenced by export_public_used_modules().
export_some_args()
static void export_some_args (int sptr, int limitsptr) static
Definition at line 691 of file exterf.c.
References arg, aux, cnt, AUX::dpdsc_base, export_symbol(), limitsptr, and sptr.
Referenced by export_host_subprogram(), and export_module_subprogram().
export_some_fini()
static void export_some_fini (int limitsptr, int limitast) static
Definition at line 709 of file exterf.c.
References ast, ast_flag, ast_flag_lowest_const, ast_flag_size, astb, dtype_flag, dtype_flag_size, eqv_flag, export_equivs(), export_one_ast(), export_symbol(), FREE, freearea(), limitsptr, lzprintf(), MOD_AREA, NULL, outlz, private_module_list, public_module_list, sptr, stb, symbol_flag, and symbol_flag_lowest_const.
Referenced by export_host_subprogram(), and export_module_subprogram().
export_some_init()
static void export_some_init () static
Definition at line 645 of file exterf.c.
References ast_flag, ast_flag_lowest_const, ast_flag_size, astb, BZERO, STB::dt, dtype_flag, dtype_flag_size, SEM::eqv_avail, eqv_flag, NEW, sem, stb, symbol_flag, symbol_flag_lowest_const, and symbol_flag_size.
Referenced by export_host_subprogram(), and export_module_subprogram().
export_some_procedure()
static void export_some_procedure (int sptr) static
Definition at line 667 of file exterf.c.
References arg, aux, cnt, AUX::dpdsc_base, and sptr.
Referenced by export_host_subprogram(), and export_module_subprogram().
export_symbol()
static void export_symbol (int sptr) static
Definition at line 2221 of file exterf.c.
References ADDBIT, aux, base, cs, STB::curr_scope, AUX::dpdsc_base, ds(), DTY, exportmode, f2, STB::firstosym, flags, for_contained, for_inliner, for_module, gbl, i, interr(), lineno, lzprintf(), STB::n_base, nml, NML_LINENO, NML_NEXT, NML_SPTR, offset, outlz, p, PUTFIELD, PUTISZ_FIELD, scope, SOC_NEXT, SOC_SPTR, sptr, stb, string_length(), sym_module, SYMI_NEXT, SYMI_SPTR, SYMNAME, TRUE, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, uname, and XBIT.
Referenced by export(), export_host_subprogram(), export_module_subprogram(), export_some_args(), and export_some_fini().
exterf_init()
void exterf_init (void)
Definition at line 970 of file exterf.c.
References APPEND_AREA, append_list, freearea(), host_append_list, and NULL.
Referenced by import_init().
exterf_init_host()
void exterf_init_host (void)
Definition at line 978 of file exterf.c.
References host_append_list, and NULL.
Referenced by restore_internal_subprograms().
fixup_host_symbol_dtype()
static void fixup_host_symbol_dtype (int sptr) static
Definition at line 753 of file exterf.c.
References ast_unvisit(), ast_visit(), CONVAL2G, DTY, mark_dtype_ast_idstr(), sptr, TY_CHAR, and TY_NCHAR.
Referenced by export_host_subprogram().
mark_dtype_ast_idstr()
void mark_dtype_ast_idstr (int dtype)
Definition at line 598 of file exterf.c.
References ADD_LWBD, ADD_NUMDIM, ADD_UPBD, ast_traverse(), DTY, i, mark_idstr(), ndim, NULL, and TY_CHAR.
Referenced by export_host_subprogram(), and fixup_host_symbol_dtype().
mark_idstr()
static void mark_idstr (int ast, int * unused) static
Definition at line 590 of file exterf.c.
References ast.
Referenced by mark_dtype_ast_idstr().
queue_ast()
static void queue_ast (int ast) static
Definition at line 1541 of file exterf.c.
References ast, ast_traverse(), NULL, and rqueue_ast().
Referenced by export(), queue_dtype(), queue_one_std(), queue_symbol(), and rqueue_ast().
queue_dtype()
static void queue_dtype (int dtype) static
Definition at line 1548 of file exterf.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_NUMDIM, ADD_NUMELM, ADD_UPAST, ADD_UPBD, ADD_ZBASE, aux, AUX::dpdsc_base, DTY, dtype_flag, dtype_flag_size, i, ndim, NOSYM, parent, queue_ast(), queue_dtype(), queue_symbol(), sptr, symbol_flag_size, TY_CHAR, and TY_NCHAR.
Referenced by export_ict_asts(), queue_dtype(), queue_symbol(), and rqueue_ast().
queue_one_std()
static void queue_one_std (int std) static
Definition at line 2830 of file exterf.c.
References queue_ast(), queue_symbol(), std, STD_AST, and STD_LABEL.
Referenced by export().
queue_symbol()
static void queue_symbol (int sptr) static
Definition at line 1649 of file exterf.c.
References add_to_private_mod_list(), arg, assert, aux, CONVAL2G, STB::curr_scope, AUX::dpdsc_base, ds(), DTY, exportmode, FALSE, STB::firstosym, FLANG_FALLTHROUGH, for_contained, for_inliner, for_module, gbl, GSAMEG, i, interr(), NML_NEXT, NML_SPTR, NOSYM, p, PARAMVALG, queue_ast(), queue_dtype(), queue_symbol(), scope, SOC_NEXT, SOC_SPTR, sptr, stb, sym_module, symbol_flag, symbol_flag_lowest_const, symbol_flag_size, SYMI_NEXT, SYMI_SPTR, SYMNAME, Trace, TRUE, TY_DCMPLX, TY_HOLL, TY_ISWORD, TY_NCHAR, and XBIT.
Referenced by export(), export_host_subprogram(), export_ict_asts(), export_ivl_ict_asts(), export_module_subprogram(), queue_dtype(), queue_one_std(), queue_symbol(), and rqueue_ast().
rqueue_ast()
static void rqueue_ast (int ast, int * unused) static
Definition at line 1351 of file exterf.c.
References ast, ast_flag, ast_flag_lowest_const, ast_flag_size, bound, cnt, FLANG_FALLTHROUGH, i, queue_ast(), queue_dtype(), queue_symbol(), s, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, and symbol_flag_size.
Referenced by export(), and queue_ast().
set_tag()
void set_tag (void)
Definition at line 3106 of file exterf.c.
References max_tag, std, and STD_NEXT.
Variable Documentation
append_list
ITEMX* append_list static
Definition at line 82 of file exterf.c.
Referenced by export(), export_append_sym(), export_module_subprogram(), and exterf_init().
ast_flag
char* ast_flag static
Definition at line 75 of file exterf.c.
Referenced by export(), export_some_fini(), export_some_init(), and rqueue_ast().
ast_flag_lowest_const
int ast_flag_lowest_const = 0 static
Definition at line 77 of file exterf.c.
Referenced by export(), export_some_fini(), export_some_init(), and rqueue_ast().
ast_flag_size
int ast_flag_size static
Definition at line 76 of file exterf.c.
Referenced by export(), export_some_fini(), export_some_init(), and rqueue_ast().
dtype_flag
char* dtype_flag static
Definition at line 73 of file exterf.c.
Referenced by export(), export_dtypes(), export_outer_derived_dtypes(), export_some_fini(), export_some_init(), and queue_dtype().
dtype_flag_size
int dtype_flag_size static
Definition at line 74 of file exterf.c.
Referenced by export(), export_dtypes(), export_outer_derived_dtypes(), export_some_fini(), export_some_init(), and queue_dtype().
eqv_flag
char* eqv_flag static
Definition at line 78 of file exterf.c.
Referenced by export(), export_equivs(), export_some_fini(), and export_some_init().
exportb
EXPORTB exportb
Definition at line 96 of file exterf.c.
Referenced by apply_use_stmts(), end_module(), export(), export_ieee_arith_libraries(), export_iso_c_libraries(), export_iso_fortran_env_libraries(), import(), mod_init(), and new_dtypes().
exporting_module
LOGICAL exporting_module = FALSE static
Definition at line 89 of file exterf.c.
Referenced by export(), and export_module().
exportmode
int exportmode = 0 static
Definition at line 91 of file exterf.c.
Referenced by export_ivl_ict_asts(), export_one_ast(), export_one_std(), export_symbol(), and queue_symbol().
for_contained
LOGICAL for_contained = FALSE static
Definition at line 88 of file exterf.c.
Referenced by export_header(), export_host_subprogram(), export_module_subprogram(), export_symbol(), and queue_symbol().
for_inliner
LOGICAL for_inliner = FALSE static
Definition at line 85 of file exterf.c.
Referenced by export(), export_header(), export_inline(), export_symbol(), and queue_symbol().
for_module
LOGICAL for_module = FALSE static
Definition at line 84 of file exterf.c.
Referenced by export(), export_header(), export_ivl_ict(), export_module(), export_symbol(), and queue_symbol().
host_append_list
ITEMX* host_append_list static
Definition at line 587 of file exterf.c.
Referenced by export_append_host_sym(), export_fix_host_append_list(), export_host_subprogram(), exterf_init(), and exterf_init_host().
max_tag
int max_tag = 0 static
Definition at line 3104 of file exterf.c.
Referenced by set_tag().
out_platform
int out_platform = MOD_ANY static
Definition at line 94 of file exterf.c.
Referenced by export_header().
outlz
lzhandle* outlz static
Definition at line 90 of file exterf.c.
Referenced by export(), export_derived_dt(), export_dt(), export_equiv_item(), export_host_subprogram(), export_ict(), export_ieee_arith_libraries(), export_iso_c_libraries(), export_iso_fortran_env_libraries(), export_ivl(), export_ivl_ict(), export_module_subprogram(), export_one_ast(), export_one_std(), export_some_fini(), and export_symbol().
private_module_list
ITEMX* private_module_list = NULL static
Definition at line 80 of file exterf.c.
Referenced by add_to_private_mod_list(), export(), export_header(), and export_some_fini().
public_module_list
XITEMX* public_module_list = NULL static
Definition at line 79 of file exterf.c.
Referenced by export(), export_header(), export_public_module(), and export_some_fini().
sym_module
int sym_module = 0 static
Definition at line 86 of file exterf.c.
Referenced by export(), export_host_subprogram(), export_inline(), export_module(), export_module_subprogram(), export_symbol(), and queue_symbol().
symbol_flag
char* symbol_flag static
Definition at line 70 of file exterf.c.
Referenced by export(), export_module_subprogram(), export_some_fini(), export_some_init(), and queue_symbol().
symbol_flag_lowest_const
int symbol_flag_lowest_const = 0 static
Definition at line 72 of file exterf.c.
Referenced by export(), export_some_fini(), export_some_init(), and queue_symbol().
symbol_flag_size
int symbol_flag_size static
Definition at line 71 of file exterf.c.
Referenced by export(), export_some_init(), queue_dtype(), queue_symbol(), and rqueue_ast().