flang: extern.h File Reference
extern.h File Reference
FIXME.
Classes
struct arg_gbl
struct forall_gbl
struct pre_loop
struct FINFO
struct FINFO_TBL
struct itemlist
struct TABLE
struct tbl
struct pure_gbl
Macros
#define FORALL_AREA 10
#define FINFO_AST(i) finfot.base[i].ast
#define FINFO_TYPE(i) finfot.base[i].type
#define FINFO_SHAPE(i) finfot.base[i].shape
#define CANONICAL_CAUSE 1
#define INTRINSIC_CAUSE 2
#define UGLYCOMM_CAUSE 3
#define DEPENDENCY_CAUSE 4
#define GETSCALAR_CAUSE 5
#define COPYSCALAR_CAUSE 6
#define COPYSECTION_CAUSE 7
#define MANYRUNTIME_CAUSE 8
#define PURECOMM_CAUSE 9
#define UGLYPURE_CAUSE 10
#define UGLYMASK_CAUSE 11
#define NOPARALLELISM_CAUSE 13
Typedefs
typedef struct itemlist LITEMF
Functions
void enter_local_mode (int std)
void exit_local_mode (int std)
void convert_forall (void)
int conv_forall (int std)
void forall_dependency_analyze (void)
int gen_islocal_index (int, int, int, int)
int gen_localize_index (int, int, int, int)
int inline_hlocalizebnds (int, int, int, int, int, int, int, int, int)
void generate_hlocalizebnds (int)
void outvalue_hlocalizebnds (int)
void generate_hcycliclp (int)
void outvalue_hcycliclp (int)
void put_forall_pcalls (int fstd)
Put forall calls into forall tables.
int convert_subscript (int)
LOGICAL is_shift_conflict (int, int, int)
void check_pointer_type (int past, int tast, int stmt, LOGICAL is_sourced_allocation)
int search_conform_array (int ast, int flag)
LOGICAL contains_ast (int, int)
Return TRUE if astSrc occurs somewhere within astTarg.
LOGICAL contains_call (int)
int rename_forall_list (int)
int concatenate_list (int, int)
LOGICAL is_multiple_idx_in_list (int)
void unvisit_every_sptr (void)
int sptr_of_subscript (int)
Return sptr of an A_SUBSCR.
int sym_of_ast (int ast)
Like memsym_of_ast(), but for a member, returns the sptr of its parent, not the member.
void init_gstbl (void)
int get_gstbl (void)
void free_gstbl (void)
void init_brtbl (void)
int get_brtbl (void)
void free_brtbl (void)
void init_rmtbl (void)
int get_rmtbl (void)
void free_rmtbl (void)
void reset_init_idx (void)
LOGICAL getbit (int, int)
LOGICAL is_vector_subscript (int, int)
int process_forall (int)
LOGICAL is_no_comm (int, int)
LOGICAL is_no_comm_expr (int, int)
LOGICAL is_no_rcomm_expr (int, int)
int insert_comm_before (int, int, LOGICAL *, LOGICAL)
int localize_for_cyclic_expr_sub (int, int)
void copy_surrogate_to_bnds_vars (DTYPE, int, DTYPE, int, int)
void copy_desc_to_bnds_vars (int sptrdest, int desc, int memdesc, int std)
void emit_fl (void)
void init_sdsc_from_dtype (int sptr, DTYPE, int before_std)
void make_temp_descriptor (int, SPTR, SPTR, int)
int init_sdsc (int sptr, DTYPE dtype, int before_std, int parent_sptr)
void ipa_restore_dtb (char *line)
void transform_call (int, int)
The following code takes a function or subroutine call and adds section descriptors for the array arguments at the end of the argument list, if the callee has an explicit interface.
LOGICAL is_scalar (int a, int)
LOGICAL is_idx (int a, int)
void forall_init (void)
LOGICAL is_same_alnd (int, int)
LOGICAL is_same_secd (int, int)
int dist_symbol (int)
LOGICAL is_array_type (int)
void rt_outvalue (void)
int mk_ftb (void)
void init_ftb (void)
void init_bnd (void)
LOGICAL is_ordered (int, int, int, int[MAXDIMS], int *)
LOGICAL is_duplicate (int, int)
int delete_astli (int list, int)
void forall_lhs_indirection (int)
void forall_rhs_indirection (int)
LOGICAL scatter_class (int)
LOGICAL is_legal_rhs (int, int, int)
LOGICAL is_legal_lhs (int, int)
int is_scatter_subscript (int, int, int)
void search_forall_idx (int, int, int *, int *)
void process_rhs_sub (int)
void globalize_subscripts (int, int)
void globalize_expr (int)
void transform_wrapup (void)
void transform_ast (int, int)
int get_dist_type (int, int)
int dist_get (int)
int same_template (int, int)
int same_template_without_single (int, int)
LOGICAL is_replicated (int)
LOGICAL is_same_alignment (int, int, int, int)
LOGICAL is_same_single_alignment (int, int)
LOGICAL is_cyclic_dist (int sptr)
LOGICAL is_same_array_alignment (int, int)
LOGICAL is_same_dist_proc (int, int)
LOGICAL is_same_array_shape (int, int)
LOGICAL is_single_alignment (int align)
int gen_single (int sptr, int memberast)
int is_array_element_in_forall (int, int)
LOGICAL is_name_in_expr (int, int)
LOGICAL is_lonely_idx (int, int)
LOGICAL expr_dependent (int, int, int, int)
LOGICAL subscr_dependent (int, int, int, int)
LOGICAL is_equivalence (int, int)
LOGICAL is_dist_all_star (int)
int process_lhs_sub (int std, int ast)
int tag_forall_comm (int)
Go through and tag the communications for this statement.
void owner_computes_rule (int)
int replace_expr (int, int, int, int)
void replace_common_proc_template (void)
void guard_forall (int)
void delete_stmt (int)
void search_idx (int ast, int list, int *astli, int *base, int *stride)
void rewrite_calls (void)
int trans_getbound (int, int)
void rewrite_forall (void)
This routine rewrites foralls.
void rewrite_forall_pure (void)
LOGICAL is_dependent (int lhs, int rhs, int forall, int, int)
LOGICAL is_pointer_dependent (int sptr, int sptr1)
void emit_alnd_secd (int, int, LOGICAL, int, int)
int get_allobnds (int, int)
LOGICAL is_indirection_in_it (int)
Inquire whether array has indirection in its subscripts.
LOGICAL is_nonscalar_indirection_in_it (int)
Inquire whether an array reference has indirection in its subscripts and the indirection has nonscalar subscripts.
LOGICAL is_dist_array_in_expr (int ast)
Inquire whether expression has distributed array.
LOGICAL is_vector_indirection_in_it (int, int)
Inquire whether array has indirection in its subscripts.
int insert_maskend (int, int)
void original_align_or_dist (int, int *, int *)
LOGICAL is_kopy_in_needed (int)
void find_get_scalar (void)
Put all get_scalar into table to easily process.
LOGICAL is_use_lhs_final (int, int, LOGICAL, LOGICAL, int)
int make_sec_from_ast (int, int, int, int, int)
Create section descriptor and initialize prior to call.
int make_sec_from_ast_chk (int, int, int, int, int, int)
int rewrite_interface_args (int func, int arg, int pos)
void get_dist_intr (int intr, int arg_list, int old_arg_list, int nargs)
void get_dist_func (int arg_list, int old_arg_list, int nargs)
LOGICAL needs_redim (int arg)
Return TRUE if the array with symbol table pointer arg requires a redimension statement.
void init_dtb (void)
void free_dtb (void)
void init_fl (void)
void dpm_out_init (void)
Stub.
void dpm_out_fe_gend (void)
void set_assumsz_bound (int arg, int entry)
void set_assumed_bounds (int arg, int entry, int actual)
int my_pe (void)
void extr_f77_local (int std, int ast)
LOGICAL pta_conflict (int ptrstdx, int ptrsptr, int targetstdx, int targetsptr, int targetpointer, int targettarget)
int pta_target (int ptrstdx, int ptrsptr, int *ptag, int *pid)
LOGICAL pta_aligned (int ptrstdx, int ptrsptr)
bool pta_stride1 (int ptrstdx, int ptrsptr)
void plist (LITEMF *, int)
int glist (LITEMF *, int)
LITEMF * clist (void)
Variables
struct arg_gbl arg_gbl
struct forall_gbl forall_gbl
struct pre_loop pre_loop
int scope
FINFO_TBL finfot
struct tbl tbl
struct tbl pertbl
struct tbl gstbl
struct tbl brtbl
struct tbl rmtbl
struct pure_gbl pure_gbl
Detailed Description
FIXME.
Definition in file extern.h.
Macro Definition Documentation
CANONICAL_CAUSE
#define CANONICAL_CAUSE 1
Definition at line 206 of file extern.h.
COPYSCALAR_CAUSE
#define COPYSCALAR_CAUSE 6
Definition at line 211 of file extern.h.
COPYSECTION_CAUSE
#define COPYSECTION_CAUSE 7
Definition at line 212 of file extern.h.
DEPENDENCY_CAUSE
#define DEPENDENCY_CAUSE 4
Definition at line 209 of file extern.h.
FINFO_AST
#define FINFO_AST (i) finfot.base[i].ast
Definition at line 202 of file extern.h.
FINFO_SHAPE
#define FINFO_SHAPE (i) finfot.base[i].shape
Definition at line 204 of file extern.h.
FINFO_TYPE
#define FINFO_TYPE (i) finfot.base[i].type
Definition at line 203 of file extern.h.
FORALL_AREA
#define FORALL_AREA 10
Definition at line 170 of file extern.h.
GETSCALAR_CAUSE
#define GETSCALAR_CAUSE 5
Definition at line 210 of file extern.h.
INTRINSIC_CAUSE
#define INTRINSIC_CAUSE 2
Definition at line 207 of file extern.h.
MANYRUNTIME_CAUSE
#define MANYRUNTIME_CAUSE 8
Definition at line 213 of file extern.h.
NOPARALLELISM_CAUSE
#define NOPARALLELISM_CAUSE 13
Definition at line 217 of file extern.h.
PURECOMM_CAUSE
#define PURECOMM_CAUSE 9
Definition at line 214 of file extern.h.
UGLYCOMM_CAUSE
#define UGLYCOMM_CAUSE 3
Definition at line 208 of file extern.h.
UGLYMASK_CAUSE
#define UGLYMASK_CAUSE 11
Definition at line 216 of file extern.h.
UGLYPURE_CAUSE
#define UGLYPURE_CAUSE 10
Definition at line 215 of file extern.h.
Typedef Documentation
LITEMF
typedef struct itemlist LITEMF
Function Documentation
check_pointer_type()
void check_pointer_type (int past, int tast, int stmt, LOGICAL is_sourced_allocation)
Definition at line 1299 of file func.c.
References A_OPTYPEG, add_stmt_after(), add_stmt_before(), argt, ARGT_ARG, assert, ast, astb, check_member(), DT_INT, DT_LOG, DT_PTR, DTY, dtype_to_arg(), FALSE, FLANG_FALLTHROUGH, gbl, gen_set_type(), get_member_descriptor(), get_static_type_descriptor(), get_type_descr_arg(), getccsym(), ASTB::i0, inline_RTE_set_type(), ASTB::k0, memsym_of_ast(), mk_argt(), mk_binop(), mk_cval1(), mk_func_node(), mk_id(), mk_member(), mk_set_type_call(), mk_stmt(), mk_unop(), mkRteRtnNm(), NOSYM, OP_LOC, OP_NE, OP_VAL, past(), RTE_init_unl_poly_desc, stmt, sym_mkfunc_nodesc(), tmp, TRUE, val, and XBIT.
Referenced by rewrite_allocatable_assignment(), rewrite_calls(), and rewrite_func_ast().
clist()
LITEMF * clist (void)
Definition at line 2656 of file commopt.c.
References FORALL_AREA, getitem(), and list.
Referenced by conv_allocate(), forall_opt1(), getcyclic(), opt_allocate(), put_forall_pcalls(), record_barrier(), remove_mask_calls(), and remove_stmt_calls().
concatenate_list()
int concatenate_list (int list1, int list2)
Definition at line 1125 of file vsub.c.
Referenced by rewrite_block_forall().
contains_ast()
LOGICAL contains_ast (int astTarg, int astSrc)
Return TRUE if astSrc occurs somewhere within astTarg.
WARNING: This routine may not produce correct results for non-leaf AST's – correctness depends on hashing capabilities.
Definition at line 4336 of file ast.c.
contains_call()
LOGICAL contains_call (int astx)
Definition at line 1419 of file vsub.c.
Referenced by forall_list_call(), and rewrite_calls().
conv_forall()
int conv_forall (int std)
Definition at line 3428 of file outconv.c.
References A_ARGCNTG, A_OPTYPEG, add_arg(), add_lbnd(), add_mask_calls(), add_stmt_after(), add_stmt_before(), add_stmt_calls(), argt, ARGT_ARG, assert, ast, ast_to_comment(), astb, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, begin_call(), ASTB::bnd, CTYPE::c_inc, CTYPE::c_init, CTYPE::cb_block, CTYPE::cb_do, CTYPE::cb_enddo, CTYPE::cb_inc, CTYPE::cb_init, cnt, conv_forall(), conv_fused_forall(), delete_stmt(), dim, dt, DT_INT, DT_LOG, DTY, CTYPE::endifast, FALSE, find_mask_calls_pos(), find_stmt_calls_pos(), FT_CYCLIC, get_int_cval(), get_temp(), glist(), i, ASTB::i0, ASTB::i1, CTYPE::ifast, index_var, CTYPE::inner_cyclic, insert_endmask(), insert_mask(), is_same_mask_in_fused(), left_subscript_ast(), CTYPE::lhs, lhs, lhs_dim(), pure_gbl::local_mode, MAXSUBS, memsym_of_ast(), mk_argt(), mk_assn_stmt(), mk_binop(), mk_func_node(), mk_id(), mk_stmt(), n, itemlist::nitem, no_effect_forall(), normalize_bounds(), OP_ADD, OP_DIV, OP_LE, OP_LOR, OP_SUB, pos, rewrite_asn(), search_pure_function(), arg_gbl::std, std, STD_ACCEL, STD_AST, STD_KERNEL, STD_LINENO, STD_NEXT, STD_PAR, STD_PREV, STD_TASK, STD_ZTRIP, stmt, stride, sub_lbnd(), sym_of_ast(), TRUE, TY_INT8, XBIT, zero, and ASTB::zero.
Referenced by conv_forall(), and convert_forall().
convert_forall()
void convert_forall (void)
Definition at line 200 of file outconv.c.
References ast, check_region(), conv_forall(), convert_omp_workshare(), early_flow_fini(), early_flow_init(), f90_fini_pointsto(), FALSE, flg, forall_dependency_analyze(), arg_gbl::inforall, init_region(), FLG::opt, points_to(), FLG::smp, std, STD_AST, STD_NEXT, TRUE, and XBIT.
convert_subscript()
int convert_subscript (int a)
Definition at line 985 of file func.c.
References a, AD_DPTR, AD_LWAST, AD_NUMDIM, AD_UPAST, ASD_NDIM, ASD_SUBS, assert, astb, ASTB::bnd, check_member(), convert_subscript(), i, is_array_type(), lb, MAXSUBS, mk_id(), mk_member(), mk_subscr(), mk_triple(), ndim, ASTB::one, parent, sptr, sptr_of_subscript(), st, stride_one(), and ub.
Referenced by convert_subscript(), convert_subscript_in_expr(), handle_seq_section(), inline_reduction_f90(), inline_shifts(), shape_comm(), shape_comm_in_expr(), and transform_section_arg().
copy_desc_to_bnds_vars()
void copy_desc_to_bnds_vars (int sptrdest, int desc, int memdesc, int std)
Definition at line 978 of file rest.c.
References a, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_NUMDIM, AD_UPAST, add_stmt_before(), astb, ASTB::bnd, check_member(), dt, DTY, ASTB::dtype, get_extent(), get_global_lower(), i, mk_assn_stmt(), mk_binop(), mk_extent_expr(), mk_isz_cval(), ndim, ASTB::one, OP_ADD, OP_SUB, and std.
Referenced by transform_call().
copy_surrogate_to_bnds_vars()
void copy_surrogate_to_bnds_vars (DTYPE dt_dest, int parent_dest, DTYPE dt_src, int parent_src, int std)
Definition at line 927 of file rest.c.
References AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_MLPYR, AD_NUMDIM, AD_UPAST, AD_ZBASE, add_parent_to_bounds(), add_stmt_before(), astb, ASTB::bnd, DTY, ASTB::dtype, extent(), i, mk_assn_stmt(), mk_binop(), mk_extent_expr(), ndim, ASTB::one, OP_ADD, OP_MUL, OP_SUB, std, and zbase.
Referenced by transform_call(), and transform_move_alloc().
delete_astli()
int delete_astli (int list, int astli)
Definition at line 1049 of file vsub.c.
Referenced by inline_spread_shifts().
delete_stmt()
void delete_stmt (int std)
Definition at line 7627 of file ast.c.
dist_get()
int dist_get (int)
dist_symbol()
int dist_symbol (int)
dpm_out_fe_gend()
void dpm_out_fe_gend (void)
dpm_out_init()
void dpm_out_init (void)
Stub.
Definition at line 243 of file dpm_out.c.
Referenced by reinit().
emit_alnd_secd()
void emit_alnd_secd (int sptr, int memberast, LOGICAL free_flag, int std, int allocbounds)
Definition at line 1748 of file dpm_out.c.
References A_OPTYPEG, add_arg(), allocatable_freeing, ARGT_ARG, assert, ast, ast_unvisit(), ast_visit(), astb, begin_call(), ASTB::bnd, change_mk_id(), do_change_mk_id(), DTY, DTYG, ASTB::dtype, emit_alnd(), emit_secd(), EntryStd, ERR_Fatal, ExitStd, init_change_mk_id(), INS_DESCR, make_alnd(), make_secd(), mk_isz_cval(), mkRteRtnNm(), NO_CHARPTR, NO_DERIVEDPTR, NO_PTR, RTE_lena, sptr, std, STD_AST, STD_PREV, string_length(), sym_get_sdescr(), sym_mkfunc_nodesc(), TMPL_DESCR, TRUE, TY_CHAR, and XBIT.
Referenced by conv_allocate(), mk_descr_from_section(), and transform_ptr().
emit_fl()
void emit_fl (void)
Definition at line 1721 of file dpm_out.c.
References add_stmt_after(), argt, ARGT_ARG, ast, FL::avl, FL::base, DT_INT, fl, gbl, i, mk_argt(), mk_cval(), mk_func_node(), mk_id(), mkRteRtnNm(), nargs, RTE_freen, and sym_mkfunc().
Referenced by transform_wrapup().
enter_local_mode()
void enter_local_mode (int std)
Definition at line 4888 of file outconv.c.
References add_stmt_before(), ast, astb, dest, DT_INT, getsymbol(), ASTB::i1, mk_id(), mk_stmt(), sptr, src, and std.
exit_local_mode()
void exit_local_mode (int std)
Definition at line 4916 of file outconv.c.
References add_stmt_before(), ast, dest, DT_INT, getsymbol(), mk_id(), mk_stmt(), sptr, src, and std.
expr_dependent()
LOGICAL expr_dependent (int expr, int depends, int lstdx, int rstdx)
Definition at line 631 of file iterat.c.
References build_dlist(), and expr_dependent_check().
Referenced by dd_compute(), is_use_lhs(), is_use_lhs_final(), put_forall_pcalls(), remove_from_scalar_subscript(), and rewrite_calls().
extr_f77_local()
void extr_f77_local (int std, int ast)
find_get_scalar()
void find_get_scalar (void)
Put all get_scalar into table to easily process.
Definition at line 3624 of file commopt.c.
References ast, tbl::base, TABLE::f1, FT_GETSCLR_NOMEM, FT_GETSCLR_OMEMED, FT_GETSCLR_REUSE, FT_GETSCLR_SAME, FT_STD, get_gstbl(), gstbl, i, mk_ftb(), std, STD_AST, STD_NEXT, and type.
Referenced by eliminate_get_scalar(), and generate_get_scalar().
forall_dependency_analyze()
void forall_dependency_analyze (void)
Definition at line 149 of file outconv.c.
References ast, ast_to_comment(), forall_dependency(), freearea(), NULL, set_descriptor_sc(), std, STD_AST, STD_DELETE, STD_NEXT, TEMP_AREA, and templist.
Referenced by convert_forall().
forall_init()
void forall_init (void)
Definition at line 182 of file commopt.c.
References ast, forall_make_same_idx(), forall_opt1(), init_bnd(), init_dtb(), init_ftb(), init_optsum(), put_forall_pcalls(), set_descriptor_sc(), std, STD_AST, STD_BLKSYM, STD_LABEL, and STD_NEXT.
forall_lhs_indirection()
void forall_lhs_indirection (int std)
Definition at line 403 of file vsub.c.
References add_stmt_before(), ALIGNG, find_scatter_rhs(), get_temp_forall(), is_duplicate(), is_legal_lhs(), is_multiple_idx_in_list(), is_one_idx_for_dim(), is_vector_indirection_in_it(), left_array_symbol(), left_subscript_ast(), lhs, list, mk_stmt(), optype(), process_forall(), reference_for_temp_lhs_indirection(), scalar_lhs_dependency(), scatter_class(), scatter_dependency(), sptr, src, std, and STD_AST.
Referenced by process_forall().
forall_rhs_indirection()
void forall_rhs_indirection (int)
free_brtbl()
void free_brtbl (void)
Definition at line 2600 of file commopt.c.
References tbl::base, brtbl, and FREE.
Referenced by convert_output().
free_dtb()
void free_dtb (void)
Definition at line 170 of file dpm_out.c.
References DTB::avl, DTB::base, dtb, FREE, and DTB::size.
Referenced by transform_wrapup().
free_gstbl()
void free_gstbl (void)
Definition at line 2573 of file commopt.c.
References tbl::base, FREE, and gstbl.
Referenced by eliminate_get_scalar(), and generate_get_scalar().
free_rmtbl()
void free_rmtbl (void)
gen_islocal_index()
int gen_islocal_index (int ast, int sptr, int dim, int subAst)
Definition at line 68 of file func.c.
References add_lbnd(), ALIGNG, argt, ARGT_ARG, ast, astb, ASTB::bnd, check_member(), dim, DT_LOG, ASTB::dtype, get_owner_lower(), get_owner_upper(), mk_argt(), mk_binop(), mk_cval(), mk_default_int(), mk_func_node(), mk_id(), mkRteRtnNm(), nargs, normalize_bounds(), OP_GE, OP_LAND, OP_LE, RTE_islocal_idx, sptr, sub_lbnd(), sym_mkfunc(), TRUE, and XBIT.
gen_localize_index()
int gen_localize_index (int sptr, int dim, int subAst, int astmem)
Definition at line 1497 of file commgen.c.
References add_lbnd(), argt, ARGT_ARG, astb, ASTB::bnd, check_member(), dim, DT_INT, ASTB::dtype, mk_argt(), mk_bnd_int(), mk_func_node(), mk_id(), mk_isz_cval(), mkRteRtnNm(), nargs, normalize_bounds(), RTE_localize_index, sptr, sub_lbnd(), and sym_mkfunc().
gen_single()
int gen_single (int sptr, int memberast)
generate_hcycliclp()
void generate_hcycliclp (int ast)
Definition at line 1085 of file commgen.c.
References A_ARGCNTP, A_STDG, add_lbnd(), add_stmt_before(), argt, ARGT_ARG, assert, ast, astb, ASTB::bnd, change_forall_triple(), check_member(), delete_stmt(), dim, ASTB::dtype, FALSE, fill_cyclic_1(), fill_cyclic_k(), FT_BND_CALL, FT_BND_IDX, FT_BND_LHS, FT_BND_SAME, FT_STD, get_int_cval(), idx, lhs, memsym_of_ast(), mk_argt(), mk_assn_stmt(), mk_bnd_int(), mk_default_int(), mk_id(), mk_isz_cval(), mk_stmt(), mkRteRtnNm(), nargs, normalize_bounds(), RTE_cyclic_loop, st, std, STD_AST, STD_DELETE, sub_lbnd(), sym_mkfunc(), and TRUE.
generate_hlocalizebnds()
void generate_hlocalizebnds (int ast)
Definition at line 974 of file commgen.c.
References A_ARGCNTP, A_STDG, add_lbnd(), add_stmt_before(), argt, ARGT_ARG, assert, ast, astb, ASTB::bnd, change_forall_triple(), check_member(), delete_stmt(), dim, ASTB::dtype, FALSE, FT_BND_CALL, FT_BND_IDX, FT_BND_LHS, FT_BND_SAME, FT_STD, get_int_cval(), idx, inline_hlocalizebnds(), lb, lhs, memsym_of_ast(), mk_argt(), mk_assn_stmt(), mk_bnd_int(), mk_id(), mk_isz_cval(), mk_stmt(), mkRteRtnNm(), nargs, normalize_bounds(), ASTB::one, RTE_localize_bounds, st, std, STD_AST, STD_DELETE, sub_lbnd(), sym_mkfunc(), ub, and XBIT.
get_allobnds()
int get_allobnds (int sptr, int ast)
Definition at line 4464 of file dpm_out.c.
References add_lbnd(), assert, ast, check_member(), DTY, get_local_lower(), get_local_upper(), i, INS_DESCR, lb, mk_subscr(), mk_triple(), ndim, normalize_bounds(), rank_of_sym(), sptr, and ub.
Referenced by redimension().
get_brtbl()
int get_brtbl (void)
Definition at line 2606 of file commopt.c.
References tbl::avl, tbl::base, brtbl, errfatal(), NEED, NULL, tbl::size, and SPTR_MAX.
Referenced by record_barrier().
get_dist_func()
void get_dist_func (int arg_list, int old_arg_list, int nargs)
get_dist_intr()
void get_dist_intr (int intr, int arg_list, int old_arg_list, int nargs)
get_dist_type()
int get_dist_type (int , int)
get_gstbl()
int get_gstbl (void)
Definition at line 2580 of file commopt.c.
References tbl::avl, tbl::base, errfatal(), gstbl, NEED, NULL, tbl::size, and SPTR_MAX.
Referenced by find_get_scalar().
get_rmtbl()
int get_rmtbl (void)
getbit()
LOGICAL getbit (int x, int p)
Definition at line 3616 of file dpm_out.c.
References p, and x.
Referenced by eliminate_sect(), emit_scatterx_gatherx(), emit_sum_scatterx(), generate_gather(), make_sec_ast(), and make_sec_from_ast_chk().
glist()
int glist (LITEMF * list, int n)
Definition at line 2687 of file commopt.c.
References assert, i, itemlist::item, list, n, and itemlist::next.
Referenced by add_mask_calls(), add_stmt_calls(), call_comm(), conv_deallocate(), conv_forall(), eliminate_redundant(), find_calls_pos(), find_mask_calls_pos(), find_max_of_mask_calls_pos(), find_stmt_calls_pos(), insert_call_comm(), insert_forall_comm(), is_call_dependent(), is_mask_call_dependent(), is_same_mask_in_fused(), is_stmt_call_dependent(), opt_allocate(), put_call_comm(), put_calls(), put_forall_pcalls(), sequentialize_call(), sequentialize_mask_call(), sequentialize_stmt_call(), shape_comm(), shape_communication(), and tag_call_comm().
globalize_expr()
void globalize_expr (int)
globalize_subscripts()
void globalize_subscripts (int , int)
guard_forall()
void guard_forall (int)
init_bnd()
void init_bnd (void)
Definition at line 3281 of file symutl.c.
Referenced by forall_init().
init_brtbl()
void init_brtbl (void)
Definition at line 2592 of file commopt.c.
References tbl::avl, tbl::base, brtbl, NEW, and tbl::size.
Referenced by comm_init().
init_dtb()
void init_dtb (void)
Definition at line 159 of file dpm_out.c.
References DTB::avl, DTB::base, BZERO, dtb, NEW, NULL, and DTB::size.
Referenced by forall_init(), and ipa_restore_dtb().
init_fl()
void init_fl (void)
Definition at line 191 of file dpm_out.c.
References FL::avl, FL::base, fl, NEW, and FL::size.
Referenced by conv_allocate(), and transform_wrapup().
init_ftb()
void init_ftb (void)
Definition at line 2636 of file commopt.c.
References FTB::avl, FTB::base, ftb, NEW, and FTB::size.
Referenced by forall_init().
init_gstbl()
void init_gstbl (void)
Definition at line 2565 of file commopt.c.
References tbl::avl, tbl::base, gstbl, NEW, and tbl::size.
Referenced by eliminate_get_scalar(), and generate_get_scalar().
init_rmtbl()
void init_rmtbl (void)
init_sdsc()
int init_sdsc (int sptr, DTYPE dtype, int before_std, int parent_sptr)
Definition at line 12741 of file semutil2.c.
References AD_DPTR, AD_LWAST, AD_NUMDIM, AD_UPAST, add_stmt_after(), add_stmt_before(), argt, ARGT_ARG, assert, ast, astb, ASTB::bnd, DDTG, DT_INT, ASTB::dtype, dtype_to_arg(), ERR_Fatal, i, mk_argt(), mk_func_node(), mk_id(), mk_isz_cval(), mk_member(), mkRteRtnNm(), nargs, ndims, NOSYM, RTE_instance, RTE_template, size_of_dtype(), sptr, std, sym_mkfunc(), and TRUE.
Referenced by init_sdsc_from_dtype().
init_sdsc_from_dtype()
void init_sdsc_from_dtype (int sptr, DTYPE dtype, int before_std)
Definition at line 2382 of file dpm_out.c.
References init_sdsc(), mk_id(), set_type_in_descriptor(), and sptr.
Referenced by transform_call().
inline_hlocalizebnds()
int inline_hlocalizebnds (int i1, int i2, int lb, int ub, int sptr_lhs, int descr, int dim, int std, int astmem)
Definition at line 1644 of file commgen.c.
References AD_DPTR, AD_LWAST, AD_UPAST, add_stmt_before(), assert, astb, ASTB::bnd, check_member(), dim, ASTB::dtype, gen_minmax(), get_owner_lower(), get_owner_upper(), is_array_type(), lb, max, min, mk_binop(), mk_default_int(), mk_stmt(), normalize_bounds(), ASTB::one, OP_ADD, OP_SUB, std, STD_LINENO, STD_LOCAL, STD_NEXT, and ub.
Referenced by generate_hlocalizebnds().
insert_comm_before()
int insert_comm_before (int std, int ast, LOGICAL * rhs_is_dist, LOGICAL is_subscript)
Definition at line 65 of file rest.c.
References a, A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, astb, d, dest, ASTB::firstuast, i, insert_comm_before(), interr(), MAXDIMS, mk_binop(), mk_convert(), mk_member(), mk_paren(), mk_subscr(), mk_substr(), mk_triple(), mk_unop(), nargs, ndim, r, replace_ast_subtree(), std, and TRUE.
Referenced by copy_to_scalar(), insert_comm(), insert_comm_before(), insert_forall_comm(), normalize_forall_triplet(), scalar_communication(), and tmp_assign().
insert_maskend()
int insert_maskend (int , int)
ipa_restore_dtb()
void ipa_restore_dtb (char * line)
Definition at line 5256 of file dpm_out.c.
References DTB::avl, DTB::base, currp, d, dtb, get_num(), i, init_dtb(), INS_DESCR, INS_DTYPE, INS_KIND, INS_RANK, INS_SIZE, INS_TEMPLATE, line, NEED, NULL, DTB::size, TMPL_ALIGN_TARGET, TMPL_ALIGNEE_SC, TMPL_COLLAPSE, TMPL_CONFORM, TMPL_DESCR, TMPL_DIST_TARGET, TMPL_DIST_TARGET_DESCR, TMPL_FLAG, TMPL_ISSTAR, TMPL_LB, TMPL_RANK, TMPL_TARGET_DESCR, TMPL_TARGET_SC, TMPL_TYPE, TMPL_UB, and w.
is_array_element_in_forall()
int is_array_element_in_forall (int subs, int std)
Definition at line 29 of file iterat.c.
References ASD_NDIM, ASD_SUBS, ast, ASTLI_NEXT, ASTLI_SPTR, i, is_name_in_expr(), j, list, ndim, std, and STD_AST.
Referenced by insert_forall_comm(), and scalar_communication().
is_array_type()
LOGICAL is_array_type (int sptr)
Definition at line 2595 of file transfrm.c.
References DTY, FALSE, result, sptr, and TRUE.
Referenced by convert_subscript(), declare_array_dummys(), desc_need_arrays(), emit_kopy_in(), first_element_from_section(), handle_seq_section(), inline_hlocalizebnds(), is_legal_lhs(), needs_redim(), newargs_for_entry(), and set_assumed_bounds().
is_cyclic_dist()
LOGICAL is_cyclic_dist (int sptr)
is_dependent()
LOGICAL is_dependent (int lhs, int rhs, int forall, int lstdx, int rstdx)
Definition at line 638 of file iterat.c.
References build_dlist(), expr_dependent_check(), FALSE, and lhs.
Referenced by forall_dependency(), forall_dependency_scalarize(), and is_call_dependent().
is_dist_all_star()
LOGICAL is_dist_all_star (int)
is_dist_array_in_expr()
LOGICAL is_dist_array_in_expr (int ast)
Inquire whether expression has distributed array.
Definition at line 1255 of file detect.c.
References A_ARGCNTG, ALIGNG, argt, ARGT_ARG, ast, DTY, FALSE, i, interr(), is_dist_array_in_expr(), n, sptr, and TRUE.
Referenced by canonical_conversion(), and is_dist_array_in_expr().
is_duplicate()
LOGICAL is_duplicate (int a, int list)
Definition at line 609 of file vsub.c.
References a, ASD_NDIM, ASD_SUBS, ast, ASTLI_NEXT, ASTLI_SPTR, FALSE, i, interr(), is_name_in_expr(), list, ndim, sptr, and TRUE.
Referenced by compute_permute(), forall_lhs_indirection(), is_legal_lhs_for_mask(), and same_forall_bnds().
is_equivalence()
LOGICAL is_equivalence (int sptr1, int sptr2)
Definition at line 725 of file iterat.c.
References FALSE, p, SOC_NEXT, SOC_SPTR, and TRUE.
Referenced by is_name_in_expr(), and name_dependent_check().
is_idx()
LOGICAL is_idx (int a, int list)
Definition at line 657 of file vsub.c.
References a, ASTLI_SPTR, FALSE, list, mk_id(), search_forall_idx(), and TRUE.
Referenced by is_legal_lhs(), is_legal_lhs_for_mask(), and is_vector_subscript().
is_indirection_in_it()
LOGICAL is_indirection_in_it (int a)
Inquire whether array has indirection in its subscripts.
Definition at line 1029 of file detect.c.
References a, ASD_NDIM, ASD_SUBS, FALSE, i, interr(), is_array_in_expr(), ndim, and TRUE.
Referenced by forall_with_mask(), and is_mask_for_rhs().
is_kopy_in_needed()
LOGICAL is_kopy_in_needed (int arg)
Definition at line 1199 of file dpm_out.c.
References ADD_ASSUMSHP, arg, DTY, FALSE, and TRUE.
Referenced by arg_has_descriptor(), emit_kopy_in(), is_desc_needed(), use_dummy_desc(), and wrap_symbol().
is_legal_lhs()
LOGICAL is_legal_lhs (int a, int forall)
Definition at line 481 of file vsub.c.
References a, AD_DPTR, AD_LWBD, ASD_NDIM, ASD_SUBS, assert, astb, FALSE, i, ASTB::i1, interr(), is_array_type(), is_idx(), is_scalar(), is_vector_subscript(), lb, list, ndim, sptr, sptr_of_subscript(), and TRUE.
Referenced by forall_lhs_indirection().
is_legal_rhs()
LOGICAL is_legal_rhs (int lhs, int rhs, int forall)
Definition at line 938 of file vsub.c.
Referenced by is_mask_for_rhs().
is_lonely_idx()
LOGICAL is_lonely_idx (int expr, int isptr)
Definition at line 143 of file iterat.c.
References A_ARGCNTG, argt, ARGT_ARG, FALSE, i, interr(), is_lonely_idx(), n, and TRUE.
Referenced by is_lonely_idx().
is_multiple_idx_in_list()
LOGICAL is_multiple_idx_in_list (int list)
Definition at line 556 of file vsub.c.
References ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, FALSE, is_name_in_expr(), list, and TRUE.
Referenced by forall_lhs_indirection(), forall_with_mask(), and normalize_forall_triplet().
is_name_in_expr()
LOGICAL is_name_in_expr (int expr, int isptr)
Definition at line 57 of file iterat.c.
References A_ARGCNTG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, FALSE, i, interr(), is_equivalence(), is_name_in_expr(), n, sptr, and TRUE.
Referenced by canonical_conversion(), eliminate_extra_idx(), forall_semantic(), inline_reduction_f90(), is_array_element_in_forall(), is_duplicate(), is_multiple_idx_in_list(), is_name_in_expr(), and same_forall_bnds().
is_no_comm()
LOGICAL is_no_comm (int , int)
is_no_comm_expr()
LOGICAL is_no_comm_expr (int , int)
is_no_rcomm_expr()
LOGICAL is_no_rcomm_expr (int , int)
is_nonscalar_indirection_in_it()
LOGICAL is_nonscalar_indirection_in_it (int a)
Inquire whether an array reference has indirection in its subscripts and the indirection has nonscalar subscripts.
Definition at line 1055 of file detect.c.
References a, ASD_NDIM, ASD_SUBS, FALSE, i, interr(), is_nonscalar_array_in_expr(), ndim, and TRUE.
is_ordered()
LOGICAL is_ordered (int lhs, int rhs, int list, int order2[MAXDIMS], int * no)
Definition at line 712 of file vsub.c.
References ASD_NDIM, ASD_SUBS, assert, count, i, is_ordered(), j, LHS, list, MAXDIMS, ndim, order, r, and search_forall_idx().
Referenced by emit_copy_section(), emit_permute_section(), is_ordered(), and same_forall_bnds().
is_pointer_dependent()
LOGICAL is_pointer_dependent (int sptr, int sptr1)
Definition at line 4237 of file outconv.c.
References DTY, FALSE, sptr, and TRUE.
is_replicated()
LOGICAL is_replicated (int)
is_same_alignment()
LOGICAL is_same_alignment (int , int , int , int)
is_same_alnd()
LOGICAL is_same_alnd (int sptr, int sptr1)
Definition at line 751 of file dpm_out.c.
References FALSE, i, ndim, sptr, TMPL_ALIGN_TARGET, TMPL_COLLAPSE, TMPL_CONFORM, TMPL_DIST_TARGET_DESCR, TMPL_FLAG, TMPL_ISSTAR, TMPL_LB, TMPL_RANK, TMPL_TARGET_DESCR, TMPL_UB, and TRUE.
Referenced by share_alnd().
is_same_array_alignment()
LOGICAL is_same_array_alignment (int sptr, int sptr1)
Definition at line 1708 of file commopt.c.
References TRUE.
Referenced by eliminate_alloc(), eliminate_sect(), eliminate_shift(), eliminate_start(), and is_same_mask().
is_same_array_shape()
LOGICAL is_same_array_shape (int sptr, int sptr1)
Definition at line 1824 of file commopt.c.
References AD_DPTR, AD_LWAST, AD_UPAST, FALSE, i, lb, ndim, rank_of_sym(), result, sptr, TRUE, and ub.
Referenced by eliminate_sect(), and eliminate_shift().
is_same_dist_proc()
LOGICAL is_same_dist_proc (int , int)
is_same_secd()
LOGICAL is_same_secd (int sptr, int sptr1)
Definition at line 803 of file dpm_out.c.
References DTY, dtype_to_arg(), FALSE, INS_RANK, INS_TEMPLATE, mk_id(), ndim, size_ast_of(), sptr, and TRUE.
Referenced by share_secd().
is_same_single_alignment()
LOGICAL is_same_single_alignment (int , int)
is_scalar()
LOGICAL is_scalar (int a, int list)
Definition at line 643 of file vsub.c.
References a, FALSE, list, search_forall_idx(), and TRUE.
Referenced by emit_scatterx_gatherx(), emit_sum_scatterx(), is_legal_lhs(), is_legal_lhs_for_mask(), and is_vector_subscript().
is_scatter_subscript()
int is_scatter_subscript (int , int , int)
is_shift_conflict()
LOGICAL is_shift_conflict (int func_ast, int func_args, int expr)
Definition at line 894 of file func.c.
References A_OPTYPEG, ARGT_ARG, boundary, FALSE, is_another_shift(), memsym_of_ast(), sptr, and TRUE.
Referenced by _olap_conflict().
is_single_alignment()
LOGICAL is_single_alignment (int align)
is_use_lhs_final()
LOGICAL is_use_lhs_final (int a, int forall, LOGICAL same_nidx, LOGICAL independent, int std)
Definition at line 871 of file commgen.c.
References a, expr_dependent(), FALSE, FT_FUSEDSTD, FT_HEADER, FT_NFUSE, header(), i, is_same_number_of_idx(), lhs, list, memsym_of_ast(), sptr, src, std, STD_AST, and TRUE.
Referenced by eliminate_redundant(), and emit_permute_section().
is_vector_indirection_in_it()
LOGICAL is_vector_indirection_in_it (int a, int list)
Inquire whether array has indirection in its subscripts.
Definition at line 1078 of file detect.c.
References a, ASD_NDIM, ASD_SUBS, FALSE, i, interr(), is_array_in_expr(), is_vector_subscript(), list, ndim, sub, and TRUE.
Referenced by forall_lhs_indirection().
is_vector_subscript()
LOGICAL is_vector_subscript (int a, int list)
Definition at line 687 of file vsub.c.
References a, ASD_NDIM, ASD_SUBS, count, FALSE, i, is_idx(), is_scalar(), list, ndim, and TRUE.
Referenced by emit_scatterx_gatherx(), emit_sum_scatterx(), is_legal_lhs(), is_legal_lhs_for_mask(), is_vector_indirection_in_it(), and permute_axis().
localize_for_cyclic_expr_sub()
int localize_for_cyclic_expr_sub (int , int)
make_sec_from_ast()
int make_sec_from_ast (int ast, int std, int stdafter, int sec_ast, int sectflag)
Create section descriptor and initialize prior to call.
It initialize before std. And section information comes from AST arr. ast is A_SUBSCR with non-null shape. To find section boundary, it looks for AST. If AST is not enough (e.g, A(:,1)), it uses the shape. Check for A(:)%B(5) also.
Definition at line 3659 of file dpm_out.c.
References ast, make_sec_from_ast_chk(), sectflag, and std.
Referenced by copy_arg_to_seq_tmp(), emit_permute_section(), emit_sum_scatterx(), generate_sect(), handle_seq_section(), transform_associated(), transform_ptr(), and transform_section_arg().
make_sec_from_ast_chk()
int make_sec_from_ast_chk (int ast, int std, int stdafter, int sec_ast, int sectflag, int ignore_c)
Definition at line 3668 of file dpm_out.c.
References a, add_stmt_before(), argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, astb, ASTB::bnd, check_member(), diff_lbnd(), DT_INT, DT_PTR, ASTB::dtype, FALSE, get_scalar_in_expr(), getbit(), i, interr(), is_whole_array(), j, pure_gbl::local_mode, mk_argt(), mk_bnd_int(), mk_func_node(), mk_id(), mk_isz_cval(), mk_subscr(), mk_unop(), mkRteRtnNm(), nargs, ndim, NOSYM, ASTB::one, OP_VAL, parent, rank_of(), RTE_sect, RTE_sect1, RTE_sect1v, RTE_sect2, RTE_sect2v, RTE_sect3, RTE_sect3v, sectflag, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, size_of(), sptr, sptr_of_subscript(), std, sym_get_sdescr(), sym_mkfunc(), TRUE, and XBIT.
Referenced by handle_seq_section(), and make_sec_from_ast().
make_temp_descriptor()
void make_temp_descriptor (int ast_ele, SPTR sptr_orig, SPTR sptr_tmp, int before_std)
Definition at line 2360 of file dpm_out.c.
References add_stmt_before(), argt, ARGT_ARG, assert, ast, check_member(), ERR_Fatal, mk_argt(), mk_func_node(), mk_id(), mkRteRtnNm(), nargs, RTE_tmp_desc, sym_mkfunc(), and void().
Referenced by transform_call().
mk_ftb()
int mk_ftb (void)
Definition at line 2644 of file commopt.c.
References FTB::avl, FTB::base, errfatal(), ftb, NEED, NULL, and FTB::size.
Referenced by alloc2ast(), emit_copy_section(), emit_overlap(), emit_scatterx_gatherx(), find_get_scalar(), forall_opt1(), make_sec_ast(), move_mask_calls(), put_forall_pcalls(), remove_mask_calls(), remove_stmt_calls(), temp_copy_section(), and temp_gatherx().
my_pe()
int my_pe (void)
needs_redim()
LOGICAL needs_redim (int arg)
Return TRUE if the array with symbol table pointer arg requires a redimension statement.
Definition at line 2941 of file dpm_out.c.
References arg, DDTG, DTYG, f77_local, FALSE, is_array_type(), is_bad_dtype(), NO_CHARPTR, NO_DERIVEDPTR, NO_PTR, TRUE, and TY_CHAR.
Referenced by interface_for_entry(), interface_for_llvmiface(), newargs_for_entry(), and rewrite_func_ast().
original_align_or_dist()
void original_align_or_dist (int , int * , int *)
outvalue_hcycliclp()
void outvalue_hcycliclp (int ast)
Definition at line 942 of file commgen.c.
References assert, ast, cl, cs, mk_id(), mk_triple(), and trans_getbound().
Referenced by rt_outvalue().
outvalue_hlocalizebnds()
void outvalue_hlocalizebnds (int ast)
Definition at line 925 of file commgen.c.
References assert, ast, lb, mk_id(), mk_triple(), trans_getbound(), and ub.
Referenced by rt_outvalue().
owner_computes_rule()
void owner_computes_rule (int)
plist()
void plist (LITEMF * list, int item)
Definition at line 2667 of file commopt.c.
References assert, FORALL_AREA, getitem(), itemlist::item, last, list, and itemlist::next.
Referenced by canonical_conversion(), conv_allocate(), do_nml(), emit_copy_section(), emit_gatherx(), emit_overlap(), emit_scatterx_gatherx(), fix_symbol(), forall_make_same_idx(), lower_namelist_plists(), make_sec_ast(), opt_allocate(), propagate_bound(), put_forall_pcalls(), and read_symbol().
process_forall()
int process_forall (int std)
Definition at line 119 of file vsub.c.
References assert, FALSE, forall_bound_dependence(), forall_bound_dependence_fix(), forall_lhs_indirection(), forall_loop_interchange(), forall_semantic(), forall_with_mask(), forall_with_shape(), lhs, process_forall_recursion, sequentialize(), std, STD_AST, STD_NEXT, STD_PREV, and void().
Referenced by copy_arg_to_seq_tmp(), emit_sum_scatterx(), forall_lhs_indirection(), forall_with_mask(), and rewrite_forall().
process_lhs_sub()
int process_lhs_sub (int std, int ast)
Definition at line 1522 of file detect.c.
References ALIGNG, TRANSFORM::arrb, ARREF_ARR, ARREF_ARRSYM, ARREF_CLASS, ARREF_NDIM, ARREF_NEXT, ARREF_SUB, ARREF_TEMP, ASD_NDIM, ASD_SUBS, assert, ast, convert_idx_scalar(), comminfo::forall, FT_CYCLIC, i, CTYPE::idx, left_nonscalar_subscript_ast(), left_subscript_ast(), comminfo::lhs, TRANSFORM::lhs, CTYPE::lhs, lhs, list, comminfo::mask_phase, NO_CLASS, process_sub(), sptr, sptr_of_subscript(), comminfo::std, std, TRANSFORM::stg_avail, TRANSFORM::stg_size, comminfo::sub, TRANSFORM::subb, SUBI_BASE, SUBI_DSTT, SUBI_DUPL, SUBI_IDX, SUBI_NOP, SUBI_POP, SUBI_SUB, comminfo::subinfo, trans, TRANS_NEED, comminfo::ugly_mask, and comminfo::unstruct.
Referenced by transform_forall().
process_rhs_sub()
void process_rhs_sub (int a)
Definition at line 164 of file detect.c.
References a, ALIGNG, TRANSFORM::arrb, ARREF_ARR, ARREF_ARRSYM, ARREF_CLASS, ARREF_NDIM, ARREF_NEXT, ARREF_SUB, ARREF_TEMP, ASD_NDIM, ASD_SUBS, assert, COMMT_NOTAG, comminfo::forall, i, matched_dim(), ndim, NO_CLASS, process_sub(), TRANSFORM::rhsbase, sptr, sptr_of_subscript(), TRANSFORM::stg_avail, TRANSFORM::stg_size, comminfo::sub, TRANSFORM::subb, SUBI_COMMT, SUBI_DSTT, SUBI_DUPL, SUBI_NOP, SUBI_POP, SUBI_SUB, trans, and TRANS_NEED.
Referenced by emit_permute_section(), and tag_comms().
pta_aligned()
LOGICAL pta_aligned (int ptrstdx, int ptrsptr)
Definition at line 3781 of file pointsto.c.
References FALSE, FPSRC_NEXT, FPSRC_PTELIST, FPSRC_SPTR, FPTE_NEXT, FPTE_SPTR, FPTE_STRIDE, FPTE_TYPE, NULL, sptr, TRUE, TT_ANON, TT_CON, TT_GDYN, TT_GLOB, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_MEM, TT_NLOC, TT_PSYM, TT_UNINIT, and TT_UNK.
Referenced by analyze().
pta_conflict()
LOGICAL pta_conflict (int ptrstdx, int ptrsptr, int targetstdx, int targetsptr, int targetpointer, int targettarget)
Definition at line 3318 of file pointsto.c.
References DBGBIT, FALSE, FPSRC_NEXT, FPSRC_PTELIST, FPSRC_SPTR, FPTE_NEXT, FPTE_SPTR, FPTE_TYPE, FPTE_VAL, gbl, NULL, SYMNAME, TRACEBIT, TRACEFLAG, TRUE, TT_ANON, TT_CON, TT_GDYN, TT_GLOB, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_MEM, TT_NLOC, TT_PSYM, TT_UNINIT, and TT_UNK.
Referenced by name_dependent_check().
pta_stride1()
bool pta_stride1 (int ptrstdx, int ptrsptr)
Definition at line 3847 of file pointsto.c.
References FALSE, FPSRC_NEXT, FPSRC_PTELIST, FPSRC_SPTR, FPTE_NEXT, FPTE_STRIDE, FPTE_TYPE, NULL, TRUE, TT_ANON, TT_CON, TT_GDYN, TT_GLOB, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_MEM, TT_NLOC, TT_PSYM, TT_UNINIT, and TT_UNK.
Referenced by analyze(), and stride_1_section().
pta_target()
int pta_target (int ptrstdx, int ptrsptr, int * ptag, int * pid)
Definition at line 3916 of file pointsto.c.
References FPSRC_NEXT, FPSRC_PTELIST, FPSRC_SPTR, FPTE_NEXT, FPTE_SPTR, FPTE_TYPE, FPTE_VAL, gbl, NULL, pid, TT_ANON, TT_CON, TT_GDYN, TT_GLOB, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_MEM, TT_NLOC, TT_PSYM, TT_UNINIT, and TT_UNK.
Referenced by do_targets().
put_forall_pcalls()
void put_forall_pcalls (int fstd)
Put forall calls into forall tables.
FT_MCALL will have calls used in the mask.
FT_SCALL will have calls used in the statement.
These later will be used to parallel calls.
Definition at line 3401 of file commopt.c.
References A_ARGCNTG, arg, argt, ARGT_ARG, assert, clist(), contains_ast(), expr_dependent(), FT_CALL_CALL, FT_CALL_NCALL, FT_CALL_POS, FT_CALL_SPTR, FT_MCALL, FT_NMCALL, FT_NPCALL, FT_NSCALL, FT_PCALL, FT_SCALL, glist(), i, is_pcalls(), j, mk_ftb(), mk_id(), nargs, past(), plist(), STD_AST, STD_NEXT, STD_PURE, sym_of_ast(), and TRUE.
Referenced by forall_init().
rename_forall_list()
int rename_forall_list (int forall)
Definition at line 3406 of file rest.c.
References A_NCOUNTG, A_NCOUNTP, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), astb, ASTLI_NEXT, ASTLI_SPTR, ASTB::bnd, ASTB::dtype, list, mk_id(), sym_get_scalar(), and SYMNAME.
Referenced by copy_arg_to_seq_tmp().
replace_common_proc_template()
void replace_common_proc_template (void)
replace_expr()
int replace_expr (int sub_expr, int isptr, int expr, int indirection)
Definition at line 658 of file iterat.c.
References A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, i, mk_binop(), mk_convert(), mk_paren(), mk_subscr(), mk_unop(), nargs, ndim, replace_expr(), sptr, and sptr_of_subscript().
Referenced by forall_2_sec(), and replace_expr().
reset_init_idx()
void reset_init_idx (void)
Definition at line 185 of file transfrm.c.
References i, init_idx, and MAXSUBS.
Referenced by inline_reduction_f90().
rewrite_calls()
void rewrite_calls (void)
Definition at line 3833 of file func.c.
References a, A_TKNG, add_stmt_after(), add_stmt_before(), alloc_source, allocatable_member(), args, assert, assign_scalar(), ast, ast_intr(), ast_to_comment(), astb, ASTB::bnd, check_alloc_ptr_type(), check_pointer_type(), close_pragma(), contains_call(), DDTG, difficult, DTY, ASTB::dtype, elemental_func_call(), expr_dependent(), FALSE, FLANG_FALLTHROUGH, gbl, gen_set_len_ast(), has_length_type_parameter_use(), has_poly_mbr(), has_tbp_or_final(), arg_gbl::inforall, interr(), is_or_has_poly(), len, arg_gbl::lhs, lhs, memsym_of_ast(), mk_stmt(), nop_dealloc(), NOSYM, open_pragma(), rewrite_asn(), rewrite_deallocate(), rewrite_sub_args(), rewrite_sub_ast(), set_descriptor_sc(), src, arg_gbl::std, std, STD_AST, STD_LINENO, STD_NEXT, STD_PREV, sym_of_ast(), TRUE, TY_CHAR, TY_NCHAR, type, and arg_gbl::used.
Referenced by transform().
rewrite_forall()
void rewrite_forall (void)
This routine rewrites foralls.
forall with shape sec as A(i,:)
forall with dependency,
forall with distributed indirection array at rhs.
Definition at line 65 of file vsub.c.
References ast, FALSE, gbl, arg_gbl::inforall, arg_gbl::lhs, process_forall(), set_descriptor_sc(), arg_gbl::std, std, STD_AST, STD_LINENO, STD_NEXT, and arg_gbl::used.
Referenced by transform().
rewrite_forall_pure()
void rewrite_forall_pure (void)
Definition at line 1159 of file vsub.c.
Referenced by transform().
rewrite_interface_args()
int rewrite_interface_args (int func, int arg, int pos)
rt_outvalue()
void rt_outvalue (void)
Definition at line 695 of file commgen.c.
References ast, gbl, outvalue_hcycliclp(), outvalue_hlocalizebnds(), arg_gbl::std, std, STD_AST, STD_DELETE, STD_LINENO, and STD_NEXT.
Referenced by comm_generator().
same_template()
int same_template (int , int)
same_template_without_single()
int same_template_without_single (int , int)
scatter_class()
LOGICAL scatter_class (int std)
Definition at line 921 of file detect.c.
References FALSE.
Referenced by forall_lhs_indirection(), and is_scatter().
search_conform_array()
int search_conform_array (int ast, int flag)
Definition at line 4509 of file func.c.
References A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, ast, elemental_func_call(), FLANG_FALLTHROUGH, i, j, nargs, and search_conform_array().
Referenced by inline_reduction_f90(), rewrite_block_where(), rewrite_sub_args(), and search_conform_array().
search_forall_idx()
void search_forall_idx (int ast, int list, int * astli, int * nidx)
Definition at line 872 of file vsub.c.
Referenced by compute_permute(), copy_section_temp_before(), eliminate_extra_idx(), forall_2_sec(), gatherx_temp_before(), inline_spread_shifts(), is_idx(), is_one_idx_for_dim(), is_ordered(), is_scalar(), and search_idx().
search_idx()
void search_idx (int ast, int list, int * astli, int * base, int * stride)
Definition at line 1345 of file detect.c.
References A_OPTYPEG, ast, astb, ASTLI_NEXT, ASTLI_SPTR, base, ASTB::bnd, ASTB::dtype, i, list, mk_convert(), mk_isz_cval(), OP_ADD, OP_MUL, OP_SUB, opt_binop(), opt_unop(), search_forall_idx(), search_idx(), stride, zero, and ASTB::zero.
Referenced by canonical_conversion(), forall_2_sec(), is_triplet(), process_sub(), and search_idx().
set_assumed_bounds()
void set_assumed_bounds (int arg, int entry, int actual)
Definition at line 4064 of file dpm_out.c.
References a, AD_DEFER, AD_DPTR, AD_LWAST, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_UPAST, AD_ZBASE, ADD_LWAST, ADD_LWBD, add_stmt_after(), arg, assert, ast, ast_intr(), astb, ASTB::bnd, check_member(), STB::dt_log, ASTB::dtype, extent(), f77_local, get_global_lower(), get_isz_cval(), get_local_multiplier(), get_section_offset(), get_section_stride(), get_xbase(), i, is_array_type(), ISZ_T, lb, mk_assn_stmt(), mk_binop(), mk_bnd_int(), mk_id(), mk_isz_cval(), mk_mlpyr_expr(), mk_stmt(), mkRteRtnNm(), NEWDSCG, ASTB::one, OP_ADD, OP_LT, OP_MUL, OP_SUB, present, r, RTE_present, stb, std, sym_mkfunc_nodesc(), tmp, update_shape_info(), STB::user, and XBIT.
Referenced by assumshp_args().
set_assumsz_bound()
void set_assumsz_bound (int arg, int entry)
Definition at line 3945 of file dpm_out.c.
References AD_DPTR, AD_EXTNTAST, AD_NUMDIM, add_stmt_after(), arg, assert, ast_intr(), STB::dt_log, extent(), f77_local, i, mk_id(), mk_stmt(), mkRteRtnNm(), NEWDSCG, present, RTE_present, stb, std, sym_mkfunc_nodesc(), and STB::user.
sptr_of_subscript()
int sptr_of_subscript (int ast)
Return sptr of an A_SUBSCR.
Definition at line 3154 of file ast.c.
subscr_dependent()
LOGICAL subscr_dependent (int expr, int depends, int lstdx, int rstdx)
Definition at line 647 of file iterat.c.
References build_dlist(), and subscr_dependent_check().
Referenced by is_fusable().
sym_of_ast()
int sym_of_ast (int ast)
Like memsym_of_ast(), but for a member, returns the sptr of its parent, not the member.
Definition at line 2931 of file ast.c.
tag_forall_comm()
int tag_forall_comm (int ast)
Go through and tag the communications for this statement.
Returns
0 if any unstructured communication
Definition at line 52 of file detect.c.
References a, A_ARGCNTG, A_OPTYPEG, ALIGNG, argt, ARGT_ARG, ARREF_CLASS, ASD_NDIM, ASD_SUBS, assert, ast, i, interr(), nargs, ndim, OVERLAP, r, sptr, sptr_of_subscript(), src, comminfo::std, std, tag_comms(), and tag_forall_comm().
Referenced by call_comm(), tag_forall_comm(), and transform_forall().
trans_getbound()
int trans_getbound (int sym, int type)
Definition at line 3333 of file symutl.c.
Referenced by fill_cyclic_k(), outvalue_hcycliclp(), outvalue_hlocalizebnds(), sym_get_cp(), and sym_get_xfer().
transform_ast()
void transform_ast (int std, int ast)
Definition at line 464 of file rest.c.
References ast, FALSE, insert_comm(), and std.
Referenced by comm_analyze(), sequentialize(), and sequentialize_call().
transform_call()
void transform_call (int std, int ast)
The following code takes a function or subroutine call and adds section descriptors for the array arguments at the end of the argument list, if the callee has an explicit interface.
For example, call foo(a1,a2,a3) will be transformed call foo(a1,a2,a3, sec_a1, sec_a2, sec_a3).
It does not accept array expressions as argument nor array funcs. For accelerator routines, it also adds arguments to match the device-reflected copies
Rule:
 Argument Type           Address         Descriptor
 ___________________     ___________     ___________________
 scalar                  &scalar         --
 array elem              &array_elem     --
 array expression        &temp           section descriptor (if
assumed-shape)
 array expression        &temp           -- (else)
 array section           &array          section descriptor (if assumed-shape
                                         and stride-1)
 array section           &temp           section descriptor (if assumed-shape
                                         and not-stride-1)
 array section           &array          -- (else if contiguous)
 array section           &temp           -- (else)
 ptr array section       &ptr            static descriptor (if pointer dummy)
 ptr array section       &temp           section descriptor (if
assumed-shape,
                                         call added)
 ptr array section       &temp           -- (else, call added)
 func/subroutine dummy   &function       --
If there is an explicit interface, and the dummy argument has the REFLECTED attribute, then the actual argument must have a device resident copy, either from a region, data region, implicit data region, or must be itself reflected. In that case, the address of the reflected copy is passed just after the dummy, and if there is a section descriptor, the address of the section descriptor for the reflected copy is passed just after the section descriptor.
Definition at line 1111 of file rest.c.
References A_ARGCNTG, A_ARGCNTP, A_OPTYPEG, add_ptr_assign(), add_stmt_before(), arg, argt, ARGT_ARG, array_element_dtype(), assert, ast, ast_is_sym(), astb, aux, ASTB::bnd, check_alloc_ptr_type(), check_member(), check_pure_interface(), cmp_interfaces_strict(), copy_desc_to_bnds_vars(), copy_surrogate_to_bnds_vars(), DDTG, DEBUG, FLG::debug, AUX::dpdsc_base, DT_ISBASIC, SEM::dtemps, DTY, ASTB::dtype, dtype_to_arg(), ERR_Fatal, ERR_Severe, error(), FALSE, find_dummy_position(), fix_class_args(), FLANG_FALLTHROUGH, flg, func, gbl, gen_contig_check(), gen_poly_element_arg(), gen_set_type(), get_all_descriptors(), get_descr_or_placeholder_arg(), get_invoking_proc_desc(), get_member_descriptor(), get_proc_ptr(), get_static_descriptor(), get_static_type_descriptor(), get_tmp_descr(), get_type_descr_arg(), get_type_descr_arg2(), get_value_length_ast(), getccsym_sc(), getcctmp_sc(), handle_seq_section(), i, IGNORE_ARG_NAMES, init_sdsc_from_dtype(), inline_RTE_set_type(), INTENT_OUT, INTENTG, interr(), is_array_dtype(), is_bad_dtype(), is_optional_char_dummy(), IS_PROC, is_procedure_ptr(), is_seq_dummy(), is_unl_poly(), STB::k0, make_temp_descriptor(), max_binding_invobj(), memsym_of_ast(), mk_argt(), mk_assn_stmt(), mk_cnst(), mk_func_node(), mk_id(), mkRteRtnNm(), nargs, needs_descriptor(), NOSYM, NULL, OP_LOC, OP_REF, OP_VAL, pass_sym_of_ast(), pghpf_type(), proc_arginfo(), procsym_of_ast(), ASTB::ptr0, ASTB::ptr0c, RELAX_INTENT_CHK, RELAX_PURE_CHK_1, RELAX_STYPE_CHK, remove_subscript_expressions(), RTE_show, RTE_test_and_set_type, s, SEM::sc, scope, sem, set_parref_flag2(), set_type_in_descriptor(), SHD_NDIM, FLG::smp, sptr, sptr_of_subscript(), stb, std, STD_NEXT, stride_1_dummy(), stride_1_section(), sym_get_array(), sym_mkfunc_nodesc(), sym_of_ast(), symbol_descriptor_length_ast(), SYMNAME, temp_type_descriptor(), tmp, transform_section_arg(), TRUE, TY_HOLL, SEM::which_pass, and XBIT.
Referenced by _transform_func(), put_calls(), transform_all_call(), and transform_pure_function().
transform_wrapup()
void transform_wrapup (void)
Definition at line 1410 of file dpm_out.c.
References add_auto_len(), allocate_for_aligned_array(), allocate_one_auto(), ast_unvisit(), BLOCK_ENDPROLOG_STD, BLOCK_EXIT_STD, close_entry_guard(), component_init_allocd_auto(), declare_array_dummys(), desc_need_arrays(), do_change_mk_id(), DTYG, emit_fl(), EntryStd, ExitStd, f77_local, finish_fl(), STB::firstosym, flg, FREE, free_dtb(), gbl, i, init_change_mk_id(), init_fl(), interface_for_entry(), j, mk_id(), NEW, new_dscptr_g, newargs_for_entry(), NOSYM, open_entry_guard(), prepare_for_astout(), s, set_parref_flag2(), share_alnd(), share_secd(), FLG::smp, sptr, stb, STD_FIRST, STD_LINENO, STD_NEXT, STD_PREV, sym_get_ptr(), this_entry_g, TY_CHAR, TY_NCHAR, unvisit_every_sptr(), use_dummy_desc(), and wrap_symbol().
Referenced by convert_output().
unvisit_every_sptr()
void unvisit_every_sptr (void)
Definition at line 1232 of file dpm_out.c.
References STB::firstosym, sptr, and stb.
Referenced by convert_statements(), and transform_wrapup().
Variable Documentation
arg_gbl
struct arg_gbl arg_gbl extern
Definition at line 36 of file commdf.c.
brtbl
struct tbl brtbl extern
Definition at line 43 of file commdf.c.
Referenced by free_brtbl(), get_brtbl(), init_brtbl(), and record_barrier().
finfot
FINFO_TBL finfot extern
Definition at line 70 of file transfrm.c.
Referenced by comm_fini(), init_finfo(), and mk_finfo().
forall_gbl
struct forall_gbl forall_gbl extern
Definition at line 37 of file commdf.c.
gstbl
struct tbl gstbl extern
Definition at line 42 of file commdf.c.
Referenced by eliminate_get_scalar(), find_get_scalar(), free_gstbl(), generate_get_scalar(), get_gstbl(), and init_gstbl().
pertbl
struct tbl pertbl extern
Definition at line 41 of file commdf.c.
Referenced by free_pertbl(), get_pertbl(), init_pertbl(), and put_data().
pre_loop
struct pre_loop pre_loop extern
Definition at line 38 of file commdf.c.
pure_gbl
struct pure_gbl pure_gbl extern
Definition at line 73 of file transfrm.c.
rmtbl
struct tbl rmtbl extern
scope
int scope extern
Referenced by _do_iface(), add_debug_cmnblk_variables(), add_only(), apply_use(), cmp_interfaces(), copy_sym_flags(), do_lastprivate(), dsym(), dump_one_scope(), dup_sym(), export_derived_dt(), export_public_used_modules(), export_symbol(), fill_sym(), find_by_name_stype_arg(), find_def_in_most_recent_scope(), find_in_host(), find_member_name(), fix_symbol(), gen_conditional_dealloc_for_sym(), gen_reduction(), get_implementation(), get_scope_level(), get_stblk_uplevel_sptr(), have_use_scope(), import_use_stmts(), is_except_in_scope(), is_in_currsub(), is_private_in_scope(), isLocalPrivate(), lldbg_create_common_block_mdnode(), lldbg_create_location_mdnode(), lldbg_create_module_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_emit_common_block_mdnode(), lldbg_emit_subprogram(), llGetTask(), lower_symbols(), next_scope(), next_scope_kind(), next_scope_kind_sptr(), next_scope_kind_symname(), next_scope_sptr(), par_push_scope(), pop_scope_level(), pop_subprogram(), process_cmnblk_data(), process_global_lifetime_debug(), push_scope_level(), queue_symbol(), reinit_sym(), resolveImp(), scopestack_init(), sem_import_sym(), set_private_bnd_encl(), set_private_encl(), sym_get_arg_sec(), sym_in_scope(), sym_visible_in_scope(), test_private_dtype(), test_scope(), and transform_call().
tbl
struct tbl tbl extern
Definition at line 40 of file commdf.c.