flang: fastset.cpp File Reference
fastset.cpp File Reference
Implementation of fast set representation for small integers.
#include "gbldefs.h"
#include "error.h"
#include <stdlib.h>
#include <string.h>
#include "fastset.h"
#include "go.h"
Macros
#define FASTSET_GRANULARITY 64
Allocations are rounded up to amortize the allocation time.
Functions
void fastset_check (const fastset *set)
Verifies that each member of the set corresponds to a valid index entry.
static void * print_int (void *p, int x)
Callback for fastset_map() as a means for printing sets.
void fastset_dbgprintf (const fastset *set)
Debug printing of a set.
void fastset_free (fastset *set)
Releases storage occupied by a set.
void fastset_reinit (fastset *set)
FIXME.
void fastset_resize (fastset *set, unsigned limit)
FIXME.
void fastset_union (fastset *xs, const fastset *ys)
Set union, destructive.
static INLINE void fastset_internal_drop_at (fastset *set, unsigned idx)
void fastset_difference (fastset *xs, const fastset *ys)
Set difference, destructive.
void fastset_intersection (fastset *xs, const fastset *ys)
Set intersection, destructive.
void * fastset_map (const fastset *xs, void *f(void *, int), void *pointer)
Apply a function to each member of a set.
void fastset_unit_tests (void)
FIXME.
Detailed Description
Implementation of fast set representation for small integers.
The fast set operations with O(1) time are implemented with small inline functions in fastset.h. This file contains those that need not be fast or that have linear time complexity, at worst.
Definition in file fastset.cpp.
Macro Definition Documentation
FASTSET_GRANULARITY
#define FASTSET_GRANULARITY 64
Allocations are rounded up to amortize the allocation time.
Definition at line 28 of file fastset.cpp.
Function Documentation
fastset_check()
void fastset_check (const fastset * set)
Verifies that each member of the set corresponds to a valid index entry.
Validation (asserts if set is bad)
Definition at line 33 of file fastset.cpp.
References CHECK, j, and set.
Referenced by fastset_unit_tests().
fastset_dbgprintf()
void fastset_dbgprintf (const fastset * set)
Debug printing of a set.
Debug printing.
Definition at line 54 of file fastset.cpp.
References fastset_map(), NULL, print_int(), and set.
fastset_difference()
void fastset_difference (fastset * xs, const fastset * ys)
Set difference, destructive.
FIXME.
Algorithm depends on the number of members in the two sets.
Definition at line 148 of file fastset.cpp.
References fastset_contains(), fastset_internal_drop_at(), fastset_remove(), fastset_vacate(), j, fastset::member, and fastset::members.
Referenced by fastset_unit_tests().
fastset_free()
void fastset_free (fastset * set)
Releases storage occupied by a set.
FIXME.
Definition at line 61 of file fastset.cpp.
References set.
Referenced by fastset_reinit(), and fastset_unit_tests().
fastset_internal_drop_at()
static INLINE void fastset_internal_drop_at (fastset * set, unsigned idx) static
Internal utility: keep a set's member list contiguous by moving its last member into a vacated position.
Definition at line 137 of file fastset.cpp.
References idx, last, and set.
Referenced by fastset_difference(), and fastset_intersection().
fastset_intersection()
void fastset_intersection (fastset * xs, const fastset * ys)
Set intersection, destructive.
FIXME.
Algorithm depends on the number of members in the two sets.
Definition at line 173 of file fastset.cpp.
References fastset_contains(), fastset_internal_drop_at(), idx, fastset::index, j, fastset::member, fastset::members, tmp, and y.
Referenced by fastset_unit_tests().
fastset_map()
void * fastset_map (const fastset * xs, void * fvoid *, int, void * pointer)
Apply a function to each member of a set.
Apply 'f' to the supplied pointer and each member of 'xs'. The pointer result from each invocation is passed as the pointer argument to the next.
Definition at line 208 of file fastset.cpp.
References count, f, j, fastset::member, fastset::members, and pointer.
Referenced by fastset_dbgprintf().
fastset_reinit()
void fastset_reinit (fastset * set)
FIXME.
Definition at line 71 of file fastset.cpp.
References fastset_free(), fastset_init(), and set.
fastset_resize()
void fastset_resize (fastset * set, unsigned limit)
FIXME.
Definition at line 78 of file fastset.cpp.
References assert, ERR_Fatal, FASTSET_GRANULARITY, i, malloc(), n, and set.
Referenced by fastset_add().
fastset_union()
void fastset_union (fastset * xs, const fastset * ys)
Set union, destructive.
FIXME.
Just call fastset_add() for every member of the second set argument.
Definition at line 126 of file fastset.cpp.
References fastset_add(), j, fastset::member, and fastset::members.
Referenced by fastset_unit_tests().
fastset_unit_tests()
void fastset_unit_tests (void)
FIXME.
Definition at line 219 of file fastset.cpp.
References a, b, c, CHECK, fastset_add(), fastset_check(), fastset_contains(), fastset_difference(), fastset_free(), fastset_init(), fastset_intersection(), fastset_is_empty(), fastset_members(), fastset_pop(), fastset_remove(), fastset_union(), fastset_vacate(), j, and k.
print_int()
static void * print_int (void * p, int x) static
Callback for fastset_map() as a means for printing sets.
Definition at line 46 of file fastset.cpp.
References dbgprintf, p, and x.
Referenced by fastset_dbgprintf().