flang: fastset.h File Reference
fastset.h File Reference
Fast sets of small nonnegative integers.
#include "universal.h"
#include <stdlib.h>
Classes
struct fastset
Implementation.
Typedefs
typedef struct fastset fastset
The representation of a fastset should be considered private.
Functions
void fastset_check (const fastset *set)
Validation (asserts if set is bad)
void fastset_dbgprintf (const fastset *set)
Debug printing.
void fastset_free (fastset *set)
FIXME.
void fastset_reinit (fastset *set)
FIXME.
void fastset_resize (fastset *set, unsigned limit_hint)
FIXME.
void fastset_union (fastset *xs, const fastset *ys)
FIXME.
void fastset_difference (fastset *xs, const fastset *ys)
FIXME.
void fastset_intersection (fastset *xs, const fastset *ys)
FIXME.
void * fastset_map (const fastset *xs, void *f(void *, int), void *pointer)
Apply a function to each member of a set.
void fastset_unit_tests (void)
FIXME.
static INLINE void fastset_init (fastset *set)
FIXME.
static INLINE void fastset_vacate (fastset *set)
FIXME.
static INLINE int fastset_members (const fastset *set)
FIXME.
static INLINE int fastset_limit (const fastset *set)
FIXME.
static INLINE int fastset_is_empty (const fastset *set)
FIXME.
static INLINE int fastset_get (const fastset *set, int idx)
FIXME.
static INLINE int fastset_pop (fastset *set)
FIXME.
static INLINE int fastset_contains (const fastset *set, int x)
static INLINE int fastset_member_index (const fastset *set, int x)
FIXME.
static INLINE void fastset_add (fastset *set, unsigned x)
static INLINE void fastset_remove (fastset *set, int x)
Detailed Description
Fast sets of small nonnegative integers.
Element membership testing and removal are constant-time operations, as is emptying a set. Adding a member to a set is constant-time unless memory allocation is required. Element traversal has time complexity linear in the number elements. Set union is O(elements of second set); set difference and set intersection are O(elements of smallest set).
Always use fastset_init() after declaring or allocating a new set, and always use fastset_free() when the set is destroyed.
The data structure is an example of a space/time trade-off being made entirely in favor of time. These sets should not be used for values larger than a few thousand. (For sets with really small maximum values, consider using bitsets; for sets with larger maximum values, try a 3-2 tree.)
The idea for this fast set data structure is attributed by Preston Briggs in his register assignment thesis to himself and Linda Torczon.
Definition in file fastset.h.
Typedef Documentation
fastset
typedef struct fastset fastset
The representation of a fastset should be considered private.
Definition at line 36 of file fastset.h.
Function Documentation
fastset_add()
static INLINE void fastset_add (fastset * set, unsigned x) static
Adds a value to a set, if it is distinct from current members.
Definition at line 182 of file fastset.h.
References fastset_resize(), idx, set, and x.
Referenced by collect_root_ilis(), collect_tree_ilis(), fastset_union(), fastset_unit_tests(), and noop_visitor().
fastset_check()
void fastset_check (const fastset * set)
Validation (asserts if set is bad)
Validation (asserts if set is bad)
Definition at line 33 of file fastset.cpp.
References CHECK, j, and set.
Referenced by fastset_unit_tests().
fastset_contains()
static INLINE int fastset_contains (const fastset * set, int x) static
Predicate: is a particular value a current member of a set? Any integer value "x" may be tested.
Definition at line 162 of file fastset.h.
References idx, set, and x.
Referenced by collect_tree_ilis(), fastset_difference(), fastset_intersection(), and fastset_unit_tests().
fastset_dbgprintf()
void fastset_dbgprintf (const fastset * set)
Debug printing.
Debug printing.
Definition at line 54 of file fastset.cpp.
References fastset_map(), NULL, print_int(), and set.
fastset_difference()
void fastset_difference (fastset * xs, const fastset * ys)
FIXME.
FIXME.
Algorithm depends on the number of members in the two sets.
Definition at line 148 of file fastset.cpp.
References fastset_contains(), fastset_internal_drop_at(), fastset_remove(), fastset_vacate(), j, fastset::member, and fastset::members.
Referenced by fastset_unit_tests().
fastset_free()
void fastset_free (fastset * set)
FIXME.
FIXME.
Definition at line 61 of file fastset.cpp.
References set.
Referenced by fastset_reinit(), and fastset_unit_tests().
fastset_get()
static INLINE int fastset_get (const fastset * set, int idx) static
FIXME.
Definition at line 146 of file fastset.h.
References idx, and set.
fastset_init()
static INLINE void fastset_init (fastset * set) static
FIXME.
Definition at line 110 of file fastset.h.
References NULL, and set.
Referenced by fastset_reinit(), and fastset_unit_tests().
fastset_intersection()
void fastset_intersection (fastset * xs, const fastset * ys)
FIXME.
FIXME.
Algorithm depends on the number of members in the two sets.
Definition at line 173 of file fastset.cpp.
References fastset_contains(), fastset_internal_drop_at(), idx, fastset::index, j, fastset::member, fastset::members, tmp, and y.
Referenced by fastset_unit_tests().
fastset_is_empty()
static INLINE int fastset_is_empty (const fastset * set) static
FIXME.
Definition at line 139 of file fastset.h.
References set.
Referenced by fastset_unit_tests().
fastset_limit()
static INLINE int fastset_limit (const fastset * set) static
FIXME.
Definition at line 132 of file fastset.h.
References set.
fastset_map()
void * fastset_map (const fastset * xs, void * fvoid *, int, void * pointer)
Apply a function to each member of a set.
Apply 'f' to the supplied pointer and each member of 'xs'. The pointer result from each invocation is passed as the pointer argument to the next.
Definition at line 208 of file fastset.cpp.
References count, f, j, fastset::member, fastset::members, and pointer.
Referenced by fastset_dbgprintf().
fastset_member_index()
static INLINE int fastset_member_index (const fastset * set, int x) static
FIXME.
Definition at line 171 of file fastset.h.
References idx, set, and x.
fastset_members()
static INLINE int fastset_members (const fastset * set) static
FIXME.
Definition at line 125 of file fastset.h.
References set.
Referenced by fastset_unit_tests().
fastset_pop()
static INLINE int fastset_pop (fastset * set) static
FIXME.
Definition at line 153 of file fastset.h.
References set.
Referenced by fastset_unit_tests().
fastset_reinit()
void fastset_reinit (fastset * set)
FIXME.
Definition at line 71 of file fastset.cpp.
References fastset_free(), fastset_init(), and set.
fastset_remove()
static INLINE void fastset_remove (fastset * set, int x) static
Removes a value from a set, if present. "x" can be any integer, since out-of-range values can't be in the set anyway.
Definition at line 198 of file fastset.h.
References idx, last, set, and x.
Referenced by fastset_difference(), and fastset_unit_tests().
fastset_resize()
void fastset_resize (fastset * set, unsigned limit_hint)
FIXME.
Definition at line 78 of file fastset.cpp.
References assert, ERR_Fatal, FASTSET_GRANULARITY, i, malloc(), n, and set.
Referenced by fastset_add().
fastset_union()
void fastset_union (fastset * xs, const fastset * ys)
FIXME.
FIXME.
Just call fastset_add() for every member of the second set argument.
Definition at line 126 of file fastset.cpp.
References fastset_add(), j, fastset::member, and fastset::members.
Referenced by fastset_unit_tests().
fastset_unit_tests()
void fastset_unit_tests (void)
FIXME.
Definition at line 219 of file fastset.cpp.
References a, b, c, CHECK, fastset_add(), fastset_check(), fastset_contains(), fastset_difference(), fastset_free(), fastset_init(), fastset_intersection(), fastset_is_empty(), fastset_members(), fastset_pop(), fastset_remove(), fastset_union(), fastset_vacate(), j, and k.
fastset_vacate()
static INLINE void fastset_vacate (fastset * set) static
FIXME.
Definition at line 118 of file fastset.h.
References set.
Referenced by collect_live_ilis(), collect_root_ilis(), fastset_difference(), and fastset_unit_tests().