flang: fd_sincos_scalar.cpp File Reference
fd_sincos_scalar.cpp File Reference
#include <assert.h>
#include <stdio.h>
#include <math.h>
#include "sincos.h"
Macros
#define SINCOS_COMMA
#define _CONCAT(l, r) l##r
#define CONCAT(l, r) _CONCAT(l,r)
#define FCN_NAME CONCAT(CONCAT(__fd_,FNAME),_1_avx2)
Functions
double FCN_NAME (double const x)
double __attribute__ ((noinline)) FCN_NAME(double const x)
Macro Definition Documentation
_CONCAT
#define _CONCAT (l, r) l##r
Definition at line 38 of file fd_sincos_scalar.cpp.
CONCAT
#define CONCAT (l, r) _CONCAT(l,r)
Definition at line 39 of file fd_sincos_scalar.cpp.
FCN_NAME
#define FCN_NAME CONCAT(CONCAT(__fd_,FNAME),_1_avx2)
Definition at line 41 of file fd_sincos_scalar.cpp.
SINCOS_COMMA
#define SINCOS_COMMA
Definition at line 18 of file fd_sincos_scalar.cpp.
Function Documentation
__attribute__()
double __attribute__ ((noinline)) const
Definition at line 55 of file fd_sincos_scalar.cpp.
References _1_OVER_PI, A_D, B_D, c, C, C_D, d, D_D, double_as_ll(), E_D, F_D, FMA, G_D, H_D, hc, kc, ll_as_double(), p, PI_HI, PI_LO, PI_MI, rc, reduction_slowpath(), S(), SINCOS(), SINCOS_COMMA, ss, t, THRESHOLD, ts, va, and x.
FCN_NAME()
double FCN_NAME (double const x)