flang: fd_sincos_vector.cpp File Reference
fd_sincos_vector.cpp File Reference
#include <stdio.h>
#include <stdbool.h>
#include <math.h>
#include "sincos.h"
Macros
#define CONFIG 1
#define SINCOS_COMMA
#define _CONCAT(l, r) l##r
#define CONCAT(l, r) _CONCAT(l,r)
#define _CONCAT4(ll, l, r, rr) ll##l##r##rr
#define CONCAT4(ll, l, r, rr) _CONCAT4(ll,l,r,rr)
#define FCN_NAME CONCAT(CONCAT4(__fd_,FNAME,_,VL),_avx2)
Functions
vdouble FCN_NAME (const vdouble x)
static void INLINE __reduction_slowpath (vdouble const a, S(vdouble *vrs, vmask *vhs) SINCOS_COMMA C(vdouble *vrc, vmask *vhc))
vdouble __attribute__ ((noinline)) FCN_NAME(const vdouble x)
Macro Definition Documentation
_CONCAT
#define _CONCAT (l, r) l##r
Definition at line 49 of file fd_sincos_vector.cpp.
_CONCAT4
#define _CONCAT4 (ll, l, r, rr) ll##l##r##rr
Definition at line 51 of file fd_sincos_vector.cpp.
CONCAT
#define CONCAT (l, r) _CONCAT(l,r)
Definition at line 50 of file fd_sincos_vector.cpp.
CONCAT4
#define CONCAT4 (ll, l, r, rr) _CONCAT4(ll,l,r,rr)
Definition at line 52 of file fd_sincos_vector.cpp.
CONFIG
#define CONFIG 1
Definition at line 18 of file fd_sincos_vector.cpp.
FCN_NAME
#define FCN_NAME CONCAT(CONCAT4(__fd_,FNAME,_,VL),_avx2)
Definition at line 56 of file fd_sincos_vector.cpp.
SINCOS_COMMA
#define SINCOS_COMMA
Definition at line 29 of file fd_sincos_vector.cpp.
Function Documentation
__attribute__()
vdouble __attribute__ ((noinline)) const
Definition at line 92 of file fd_sincos_vector.cpp.
References _1_OVER_PI, __mth_return2vectors(), __reduction_slowpath(), A_D, B_D, C, C_D, D_D, E_D, F_D, G_D, H_D, hc, kc, p, PI_HI, PI_LO, PI_MI, rc, S(), SINCOS(), SINCOS_COMMA, ss, THRESHOLD, ts, vadd_vd_vd_vd(), vand_vi2_vi2_vi2(), vcast_vd_d(), vcast_vm_i_i(), vfma_vd_vd_vd_vd(), vfmapn_vd_vd_vd_vd(), vgt64_vo_vi2_vi2(), vmul_vd_vd_vd(), vsel_vd_vo_vd_vd(), vsel_vi2_vo_vi2_vi2(), vsll64_vi2_vi2_i(), vsub_vd_vd_vd(), vtestz_i_vo(), vxor_vi2_vi2_vi2(), and x.
__reduction_slowpath()
static void INLINE __reduction_slowpath (vdouble const a, S(vdouble *vrs, vmask *vhs) SINCOS_COMMA C(vdouble *vrc, vmask *vhc)) static
Definition at line 70 of file fd_sincos_vector.cpp.
References a, C, hc, i, rc, reduction_slowpath(), S(), and SINCOS_COMMA.
Referenced by __attribute__().
FCN_NAME()
vdouble FCN_NAME (const vdouble x)