flang: fdate3f.c File Reference
fdate3f.c File Reference
#include "ent3f.h"
#include <time.h>
#include "utils3f.h"
Functions
WIN_MSVCRT_IMP char *WIN_CDECL ctime (const time_t *)
void ENT3F (FDATE, fdate)
Function Documentation
ctime()
WIN_MSVCRT_IMP char *WIN_CDECL ctime (const time_t *)
Referenced by ENT3F().
ENT3F()
void ENT3F (FDATE , fdate)
Definition at line 21 of file fdate3f.c.
References __fcp_cstr(), CADR, CLEN, ctime(), i, len, p, str, t, and time().