flang: fdlog4.cpp File Reference
fdlog4.cpp File Reference
#include <immintrin.h>
#include "fdlog_defs.h"
Functions
__m256d __fvd_log_fma3_256 (__m256d)
__m256d __internal_fast_int2dbl (__m256i a)
__m256d __attribute__ ((noinline)) __pgm_log_d_vec256_special_cases(__m256d const a
Variables
__m256d __m256d z
__m256i const ALL_ONES_EXPONENT = _mm256_set1_epi64x(ALL_ONES_EXPONENT_D)
__m256d const NAN_VAL = (__m256d)_mm256_set1_epi64x(NAN_VAL_D)
__m256d const NEG_INF = (__m256d)_mm256_set1_epi64x(NEG_INF_D)
__m256i detect_inf_nan = (__m256i)_mm256_sub_pd(a, a)
__m256d inf_nan_mask = (__m256d)_mm256_cmpeq_epi64(_mm256_and_si256(detect_inf_nan, ALL_ONES_EXPONENT), ALL_ONES_EXPONENT)
__m256i inf_nan = (__m256i)_mm256_add_pd(a, a)
__m256d non_positive_mask = _mm256_cmp_pd(a, ZERO, _CMP_LT_OQ)
__m256d zero_mask = _mm256_cmp_pd(a, ZERO, _CMP_EQ_OQ)
Function Documentation
__attribute__()
__m256d __attribute__ ((noinline)) const
References ZERO, and ZERO_D.
__fvd_log_fma3_256()
__m256d __fvd_log_fma3_256 (__m256d a)
Definition at line 59 of file fdlog4.cpp.
References __internal_fast_int2dbl(), a, ALL_ONES_EXPONENT, ALL_ONES_EXPONENT_D, D52_D, detect_inf_nan, f, HALFIFIER_D, HI_CONST_1_D, HI_CONST_2_D, HI_MASK_D, HI_THRESH_D, inf_nan_mask, LN2_HI, LN2_HI_D, LN2_LO, LN2_LO_D, LOG_C10_VEC_D, LOG_C11_VEC_D, LOG_C12_VEC_D, LOG_C13_VEC_D, LOG_C14_VEC_D, LOG_C15_VEC_D, LOG_C16_VEC_D, LOG_C17_VEC_D, LOG_C18_VEC_D, LOG_C19_VEC_D, LOG_C1_VEC_D, LOG_C20_VEC_D, LOG_C21_VEC_D, LOG_C22_VEC_D, LOG_C23_VEC_D, LOG_C24_VEC_D, LOG_C2_VEC_D, LOG_C3_VEC_D, LOG_C4_VEC_D, LOG_C5_VEC_D, LOG_C6_VEC_D, LOG_C7_VEC_D, LOG_C8_VEC_D, LOG_C9_VEC_D, m, m2, m4, m8, ONE, ONE_D, ONE_F, ONE_F_D, TEN_23, TEN_23_D, z, ZERO, and ZERO_D.
__internal_fast_int2dbl()
__m256d __internal_fast_int2dbl (__m256i a) inline
Definition at line 21 of file fdlog4.cpp.
References a, INT2DBL_D, INT2DBL_HI_D, INT2DBL_LO_D, and t.
Referenced by __fvd_log_fma3_256().
Variable Documentation
ALL_ONES_EXPONENT
__m256i const ALL_ONES_EXPONENT = _mm256_set1_epi64x(ALL_ONES_EXPONENT_D)
Definition at line 36 of file fdlog4.cpp.
Referenced by __fvd_log_fma3_256().
detect_inf_nan
__m256i detect_inf_nan = (__m256i)_mm256_sub_pd(a, a)
Definition at line 41 of file fdlog4.cpp.
Referenced by __fvd_log_fma3_256().
inf_nan
__m256i inf_nan = (__m256i)_mm256_add_pd(a, a)
Definition at line 45 of file fdlog4.cpp.
inf_nan_mask
__m256d inf_nan_mask = (__m256d)_mm256_cmpeq_epi64(_mm256_and_si256(detect_inf_nan, ALL_ONES_EXPONENT), ALL_ONES_EXPONENT)
Definition at line 42 of file fdlog4.cpp.
Referenced by __fvd_log_fma3_256().
NAN_VAL
__m256d const NAN_VAL = (__m256d)_mm256_set1_epi64x(NAN_VAL_D)
Definition at line 37 of file fdlog4.cpp.
NEG_INF
__m256d const NEG_INF = (__m256d)_mm256_set1_epi64x(NEG_INF_D)
Definition at line 38 of file fdlog4.cpp.
non_positive_mask
__m256d non_positive_mask = _mm256_cmp_pd(a, ZERO, _CMP_LT_OQ)
Definition at line 48 of file fdlog4.cpp.
z
return z
Initial value:
{
    __m256d const ZERO         = _mm256_set1_pd(ZERO_D)
Definition at line 33 of file fdlog4.cpp.
Referenced by __fvd_log_fma3_256().
zero_mask
__m256d zero_mask = _mm256_cmp_pd(a, ZERO, _CMP_EQ_OQ)
Definition at line 53 of file fdlog4.cpp.