flang: fdlog8.cpp File Reference
fdlog8.cpp File Reference
#include <immintrin.h>
#include "mth_avx512helper.h"
#include "fdlog_defs.h"
#include <stdio.h>
Functions
__m512d FCN_AVX512() __fvd_log_fma3 (__m512d)
__m512d __internal_fast_int2dbl (__m512i a)
static __m512d __attribute__ ((noinline)) __pgm_log_d_vec512_special_cases(__m512d const a
Variables
static __m512d __m512d z
__m512i const ALL_ONES_EXPONENT = _mm512_set1_epi64(ALL_ONES_EXPONENT_D)
__m512d const NAN_VAL = (__m512d)_mm512_set1_epi64(NAN_VAL_D)
__m512d const NEG_INF = (__m512d)_mm512_set1_epi64(NEG_INF_D)
__m512i detect_inf_nan = (__m512i)_mm512_sub_pd(a, a)
__m512d inf_nan_mask = (__m512d)_MM512_CMPEQ_EPI64(_mm512_and_si512(detect_inf_nan, ALL_ONES_EXPONENT), ALL_ONES_EXPONENT)
__m512i inf_nan = (__m512i)_mm512_add_pd(a, a)
__m512d non_positive_mask = _MM512_CMP_PD(a, ZERO, _CMP_LT_OQ)
__m512d zero_mask = _MM512_CMP_PD(a, ZERO, _CMP_EQ_OQ)
Function Documentation
__attribute__()
static __m512d __attribute__ ((noinline)) const static
References ZERO, and ZERO_D.
__fvd_log_fma3()
__m512d FCN_AVX512() __fvd_log_fma3 (__m512d a)
Definition at line 61 of file fdlog8.cpp.
References __internal_fast_int2dbl(), _MM512_AND_PD, _MM512_BLENDV_PD, _MM512_CMP_PD, _MM512_CMPEQ_EPI64, _MM512_MOVEMASK_PD, _MM512_OR_PD, a, ALL_ONES_EXPONENT, ALL_ONES_EXPONENT_D, D52_D, detect_inf_nan, f, HALFIFIER_D, HI_CONST_1_D, HI_CONST_2_D, HI_MASK_D, HI_THRESH_D, inf_nan_mask, LN2_HI, LN2_HI_D, LN2_LO, LN2_LO_D, LOG_C10_VEC_D, LOG_C11_VEC_D, LOG_C12_VEC_D, LOG_C13_VEC_D, LOG_C14_VEC_D, LOG_C15_VEC_D, LOG_C16_VEC_D, LOG_C17_VEC_D, LOG_C18_VEC_D, LOG_C19_VEC_D, LOG_C1_VEC_D, LOG_C20_VEC_D, LOG_C21_VEC_D, LOG_C22_VEC_D, LOG_C23_VEC_D, LOG_C24_VEC_D, LOG_C2_VEC_D, LOG_C3_VEC_D, LOG_C4_VEC_D, LOG_C5_VEC_D, LOG_C6_VEC_D, LOG_C7_VEC_D, LOG_C8_VEC_D, LOG_C9_VEC_D, m, m2, m4, m8, ONE, ONE_D, ONE_F, ONE_F_D, TEN_23, TEN_23_D, z, ZERO, and ZERO_D.
__internal_fast_int2dbl()
__m512d __internal_fast_int2dbl (__m512i a) inline
Definition at line 23 of file fdlog8.cpp.
References a, INT2DBL_D, INT2DBL_HI_D, INT2DBL_LO_D, and t.
Referenced by __fvd_log_fma3().
Variable Documentation
ALL_ONES_EXPONENT
__m512i const ALL_ONES_EXPONENT = _mm512_set1_epi64(ALL_ONES_EXPONENT_D)
Definition at line 38 of file fdlog8.cpp.
Referenced by __fvd_log_fma3().
detect_inf_nan
__m512i detect_inf_nan = (__m512i)_mm512_sub_pd(a, a)
Definition at line 43 of file fdlog8.cpp.
Referenced by __fvd_log_fma3().
inf_nan
__m512i inf_nan = (__m512i)_mm512_add_pd(a, a)
Definition at line 47 of file fdlog8.cpp.
inf_nan_mask
__m512d inf_nan_mask = (__m512d)_MM512_CMPEQ_EPI64(_mm512_and_si512(detect_inf_nan, ALL_ONES_EXPONENT), ALL_ONES_EXPONENT)
Definition at line 44 of file fdlog8.cpp.
Referenced by __fvd_log_fma3().
NAN_VAL
__m512d const NAN_VAL = (__m512d)_mm512_set1_epi64(NAN_VAL_D)
Definition at line 39 of file fdlog8.cpp.
NEG_INF
__m512d const NEG_INF = (__m512d)_mm512_set1_epi64(NEG_INF_D)
Definition at line 40 of file fdlog8.cpp.
non_positive_mask
__m512d non_positive_mask = _MM512_CMP_PD(a, ZERO, _CMP_LT_OQ)
Definition at line 50 of file fdlog8.cpp.
z
return z
Initial value:
{
    __m512d const ZERO         = _mm512_set1_pd(ZERO_D)
Definition at line 35 of file fdlog8.cpp.
Referenced by __fvd_log_fma3().
zero_mask
__m512d zero_mask = _MM512_CMP_PD(a, ZERO, _CMP_EQ_OQ)
Definition at line 55 of file fdlog8.cpp.