flang: fgetc3f.c File Reference
fgetc3f.c File Reference
#include "io3f.h"
#include "ent3f.h"
#include "utils3f.h"
Functions
int ENT3F (FGETC, fgetc)
Detailed Description
Implements LIB3F fgetc function.
Definition in file fgetc3f.c.
Function Documentation
ENT3F()
int ENT3F (FGETC , fgetc)
Definition at line 18 of file fgetc3f.c.
References __getfile3f(), __io_errno(), __io_feof(), c, CADR, f, and FILE.