flang: fgraph.c File Reference
fgraph.c File Reference
optimizer submodule responsible for building the the flowgraph
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "ast.h"
#include "nme.h"
#include "optimize.h"
Classes
struct EXP
Macros
#define dom_link(v, w) ANCESTOR(w) = v
#define PARENT(i) dom.parent[i]
#define ANCESTOR(i) dom.ancestor[i]
#define LABEL(i) dom.label[i]
#define SEMI(i) dom.semi[i]
#define BUCKET(i) dom.bucket[i]
#define BUCKET_NODE(i) PSI_NODE(i)
#define BUCKET_NEXT(i) PSI_NEXT(i)
#define GET_BUCKET(i) i = (PSI *)getitem(BUCKET_AREA, sizeof(PSI))
#define FREE_BUCKET_AREA freearea(BUCKET_AREA)
#define CNTL_TOPFG(i) cntl.stg_base[i].topfg
#define CNTL_ENDL(i) cntl.stg_base[i].endl
#define CNTL_AST(i) cntl.stg_base[i].ast
#define PUSH_CNTL(f)
#define POP_CNTL
#define DOM_NEW(x, y)
#define _PFG(cond, str)
Functions
static void set_std_fg (void)
static void partition_blocks (void)
static void dominators (void)
static int eval (int)
static void dfs (int)
static void rdfs (int)
static void compress (int)
static PSI_P append_succ (int, int)
static PSI_P add_empty_succ (int)
static void fillin_succ (int, int)
void flowgraph (void)
static void cr_block (int std)
static void wr_block (void)
static void chk_block (int std)
void postdominators (void)
int add_fg (int after)
Create an FG and insert it after FG after.
void delete_fg (int fgx)
PSI_P add_succ (int fgx, int i)
PSI_P add_pred (int fgx, int i)
void rm_edge (int fg1, int fg2)
Remove the edge fg1 -> fg2 from the flowgraph.
int add_to_parent (int newfg, int lp)
void _dump_node (int v, FILE *ff)
void dump_node (int v)
void rdilts (int fgx)
'read' a flowgraph node.
void wrilts (int fgx)
'write' the flowgraph node.
void unlnkilt (int stdx, int fgx, LOGICAL reuse)
void delilt (int stdx)
...
void dmpilt (int fgx)
...
void dump_flowgraph (void)
Variables
static Q_ITEM * assigned_labels
struct {
int * parent
int * ancestor
int * label
int * semi
PSI_P * bucket
} dom
static EXP expb
static int rdfn
struct {
struct {
int next
int prev
} std0
int std_before
int std_after
} rw_state
Detailed Description
optimizer submodule responsible for building the the flowgraph
Definition in file fgraph.c.
Macro Definition Documentation
_PFG
#define _PFG (cond, str)
Value:
  if (cond)             \
  fprintf(ff, " %s", str)
ANCESTOR
#define ANCESTOR (i) dom.ancestor[i]
Definition at line 52 of file fgraph.c.
BUCKET
#define BUCKET (i) dom.bucket[i]
Definition at line 55 of file fgraph.c.
BUCKET_NEXT
#define BUCKET_NEXT (i) PSI_NEXT(i)
Definition at line 57 of file fgraph.c.
BUCKET_NODE
#define BUCKET_NODE (i) PSI_NODE(i)
Definition at line 56 of file fgraph.c.
CNTL_AST
#define CNTL_AST (i) cntl.stg_base[i].ast
CNTL_ENDL
#define CNTL_ENDL (i) cntl.stg_base[i].endl
CNTL_TOPFG
#define CNTL_TOPFG (i) cntl.stg_base[i].topfg
dom_link
#define dom_link (v, w) ANCESTOR(w) = v
Definition at line 35 of file fgraph.c.
DOM_NEW
#define DOM_NEW (x, y)
Value:
  {                                          \
    NEW(x, y, opt.num_nodes + 1);            \
    if (x == NULL)                           \
      error(7, 4, gbl.lineno, CNULL, CNULL); \
  }
FREE_BUCKET_AREA
#define FREE_BUCKET_AREA freearea(BUCKET_AREA)
Definition at line 59 of file fgraph.c.
GET_BUCKET
#define GET_BUCKET (i) i = (PSI *)getitem(BUCKET_AREA, sizeof(PSI))
Definition at line 58 of file fgraph.c.
LABEL
#define LABEL (i) dom.label[i]
Definition at line 53 of file fgraph.c.
PARENT
#define PARENT (i) dom.parent[i]
Definition at line 51 of file fgraph.c.
POP_CNTL
#define POP_CNTL
Value:
  {                                \
    cntl.stg_avail--;              \
    cntl.top = cntl.stg_avail - 1; \
  }
PUSH_CNTL
#define PUSH_CNTL (f)
Value:
  {                              \
    cntl.top = cntl.stg_avail++; \
    OPT_NEED(cntl, CNTL, 16);    \
    CNTL_TOPFG(cntl.top) = f;    \
    CNTL_ENDL(cntl.top) = NULL;  \
  }
SEMI
#define SEMI (i) dom.semi[i]
Definition at line 54 of file fgraph.c.
Function Documentation
_dump_node()
void _dump_node (int v, FILE * ff)
Definition at line 1515 of file fgraph.c.
References _PFG, dbg_print_ast(), FG_ATOMIC, FG_CS, FG_DFN, FG_DOM, FG_EN, FG_EX, FG_FT, FG_HEAD, FG_INNERMOST, FG_JMP_TBL, FG_LABEL, FG_LINENO, FG_LNEXT, FG_LOOP, FG_LPREV, FG_MASTER, FG_MEXITS, FG_NATNXT, FG_NEXT, FG_PAR, FG_PARLOOP, FG_PARSECT, FG_PRED, FG_PTR_STORE, FG_STDFIRST, FG_STDLAST, FG_SUCC, FG_TAIL, FG_TASK, FG_XT, FG_ZTRP, i, NULL, OPTDBG, p, PSI_FT, PSI_NEXT, PSI_NODE, PSI_P_NULL, s, STD_AST, STD_BR, STD_EX, STD_LABEL, STD_NEXT, SYMNAME, and TRUE.
Referenced by dump_node().
add_empty_succ()
static PSI_P add_empty_succ (int fgx) static
Definition at line 1355 of file fgraph.c.
References fg, fgx, GET_PSI, opt, p, PSI_ALL, PSI_NEXT, and PSI_NODE.
Referenced by add_succ(), append_succ(), and flowgraph().
add_fg()
int add_fg (int after)
Create an FG and insert it after FG after.
Definition at line 1276 of file fgraph.c.
References a, after, BZERO, fg, FG_LNEXT, FG_LPREV, i, OPT::num_nodes, opt, and OPT_NEED.
Referenced by add_loop_hd(), add_single_loop_exit(), cr_block(), forall_dependency(), mk_loop_hdtl(), partition_blocks(), and reassociate().
add_pred()
PSI_P add_pred (int fgx, int i)
Definition at line 1387 of file fgraph.c.
References assert, fg, fgx, GET_PSI, i, opt, p, PSI_ALL, PSI_NEXT, PSI_NODE, and PSI_P_NULL.
Referenced by add_loop_preheader(), add_single_loop_exit(), and dfs().
add_succ()
PSI_P add_succ (int fgx, int i)
Definition at line 1312 of file fgraph.c.
References add_empty_succ(), assert, fg, fgx, i, opt, p, PSI_NEXT, PSI_NODE, and PSI_P_NULL.
Referenced by add_loop_preheader(), add_single_loop_exit(), and flowgraph().
add_to_parent()
int add_to_parent (int newfg, int lp)
Parameters
newfg block to be added
lp descendant of the loop to which block is added
Definition at line 1495 of file fgraph.c.
References assert, FG_DOM, FG_LOOP, FG_NEXT, lp, LP_FG, LP_HEAD, LP_PARENT, and parent.
Referenced by add_single_loop_exit().
append_succ()
static PSI_P append_succ (int fgx, int i) static
Definition at line 1330 of file fgraph.c.
References add_empty_succ(), assert, fg, fgx, i, opt, p, PSI_NEXT, PSI_NODE, PSI_P_NULL, and q.
Referenced by flowgraph().
chk_block()
static void chk_block (int std) static
Definition at line 981 of file fgraph.c.
References cr_block(), EXP::curfg, EXP::curstd, expb, FG_LINENO, FG_STDFIRST, EXP::noblock, std, and STD_LINENO.
Referenced by _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_mp_atomic_write(), _exp_smove(), addCopyinInplace(), allochartmp(), begin_entry(), block_str_move(), cloneUplevel(), cmplx_to_mem(), cp_byval_mem_arg(), eval_ilm(), exp_bran(), exp_call(), exp_cgoto(), exp_end(), exp_end_atomic(), exp_estmt(), exp_fstring(), exp_header(), exp_misc(), exp_mp_atomic_capture(), exp_mp_atomic_update(), exp_mp_func_prologue(), exp_qjsr(), exp_remove_gsmove(), exp_restore_mxcsr(), exp_smp(), exp_store(), exp_szero(), exp_type_bound_proc_call(), exp_zqjsr(), expand_smove(), gen_bindC_retval(), gen_funcret(), genSizeAcon(), genswitch(), get_complex_update_operand(), handle_nested_threadprivate(), ll_make_kmpc_task_arg(), ll_save_gtid_val(), load_uplevel_addresses(), loadUplevelArgsForRegion(), makeCopyprivArray(), makeCopyprivArray_tls(), partition_blocks(), pp_params(), section_create_endblock(), sectionCreateBlock(), setTaskloopVars(), store_aret(), and storechartmp().
compress()
static void compress (int v) static
Definition at line 1241 of file fgraph.c.
References ANCESTOR, compress(), LABEL, and SEMI.
Referenced by compress(), eval(), export_header(), and import_header_only().
cr_block()
static void cr_block (int std) static
Definition at line 943 of file fgraph.c.
References add_fg(), EXP::atomic, EXP::cs, EXP::curfg, EXP::curstd, expb, FG_ATOMIC, FG_CS, FG_FT, FG_LINENO, FG_MASTER, FG_PAR, FG_PARSECT, FG_STDFIRST, FG_STDLAST, FG_TASK, EXP::master, EXP::noblock, EXP::par_cnt, EXP::parsect, std, STD_LINENO, EXP::task, and wr_block().
Referenced by addCopyinInplace(), chk_block(), exp_end(), exp_header(), exp_label(), exp_misc(), exp_mp_atomic_update(), exp_smp(), makeCopyprivArray_tls(), partition_blocks(), section_create_endblock(), and setTaskloopVars().
delete_fg()
void delete_fg (int fgx)
Definition at line 1301 of file fgraph.c.
References FG_LNEXT, FG_LPREV, and fgx.
delilt()
void delilt (int stdx)
...
Definition at line 1769 of file fgraph.c.
References stdx, TRUE, and unlnkilt().
Referenced by exp_remove_gsmove(), and remove_scope_labels().
dfs()
static void dfs (int v) static
Definition at line 1179 of file fgraph.c.
References add_pred(), ANCESTOR, OPT::dfn, dfs(), EDGE_NEXT, EDGE_PRED, EDGE_SUCC, FG_DFN, FG_SUCC, LABEL, opt, OPT_NEED, p, PARENT, PSI_NEXT, PSI_NODE, PSI_P_NULL, SEMI, void(), VTX_NODE, and w.
Referenced by dfs(), and dominators().
dmpilt()
void dmpilt (int fgx)
...
Definition at line 1775 of file fgraph.c.
References dump_node(), and fgx.
Referenced by flow(), and schedule().
dominators()
static void dominators (void) static
Definition at line 1002 of file fgraph.c.
References BUCKET, OPT::dfn, dfs(), dom, dom_link, DOM_NEW, eval(), FG_DOM, FG_PRED, FREE, FREE_BUCKET_AREA, GET_BUCKET, i, OPT::num_nodes, opt, p, PARENT, PSI_NEXT, PSI_NODE, PSI_P_NULL, SEMI, VTX_NODE, and w.
Referenced by flowgraph().
dump_flowgraph()
void dump_flowgraph (void)
Definition at line 1781 of file fgraph.c.
References OPT::dfn, dump_node(), EDGE_PRED, EDGE_SUCC, FG_DFN, FG_STDFIRST, gbl, getprint(), i, OPT::num_nodes, opt, STD_LABEL, and VTX_NODE.
Referenced by collapse_arrays(), comm_optimize_post(), comm_optimize_pre(), flow(), hlopt_init(), optimize(), and optimize_alloc().
dump_node()
void dump_node (int v)
Definition at line 1604 of file fgraph.c.
References _dump_node(), and gbl.
Referenced by add_loop_preheader(), dmpilt(), dump_flowgraph(), and rm_edge().
eval()
static int eval (int v) static
Definition at line 1254 of file fgraph.c.
References ANCESTOR, compress(), and LABEL.
Referenced by dominators(), and postdominators().
fillin_succ()
static void fillin_succ (int fgx, int succ) static
Definition at line 1370 of file fgraph.c.
References fg, fgx, interr(), opt, p, PSI_NEXT, PSI_NODE, and PSI_P_NULL.
Referenced by flowgraph().
flowgraph()
void flowgraph (void)
Definition at line 62 of file fgraph.c.
References A_ARGCNTG, add_empty_succ(), add_succ(), append_succ(), argt, ARGT_ARG, assert, assigned_labels, ast, ASTLI_AST, ASTLI_NEXT, cmp64(), cnt, CNTL_AST, CNTL_ENDL, CNTL_TOPFG, CONVAL2G, dominators(), DTY, FALSE, FG_EN, FG_FT, FG_LABEL, FG_LINENO, FG_LNEXT, FG_LPREV, FG_STDFIRST, FG_STDLAST, FG_XT, fgx, fillin_succ(), FLANG_FALLTHROUGH, freearea(), gbl, getitem(), getprint(), i, Q_TAG::info, m2, Q_TAG::next, NOSYM, NULL, OPT::num_nodes, opt, OPT_ALLOC, OPT_FREE, OPTDBG, partition_blocks(), POP_CNTL, PSI_FT, PSI_ZTRP, PUSH_CNTL, q, Q_AREA, set_std_fg(), STD_AST, STD_BR, STD_LABEL, stdx, stg_avail, stg_base, stg_size, top, TRUE, TY_BINT, TY_BLOG, TY_DBLE, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_REAL, TY_SINT, TY_SLOG, and void().
Referenced by comm_optimize_post(), comm_optimize_pre(), early_flow_init(), flow(), hlopt_init(), init_points_to_prop(), optimize(), optimize_alloc(), redundss(), and sectfloat().
partition_blocks()
static void partition_blocks (void) static
Definition at line 608 of file fgraph.c.
References A_ARGCNTG, add_fg(), add_stmt_before(), argt, ARGT_ARG, assigned_labels, ast, EXP::atomic, BZERO, chk_block(), cnt, cr_block(), EXP::cs, EXP::curfg, EXP::curstd, OPT::exitfg, expb, FG_FT, FG_LINENO, FG_LPREV, FG_PARLOOP, FG_STDFIRST, FG_STDLAST, FG_XT, FLANG_FALLTHROUGH, FUNCLINEG, gbl, getitem(), i, label, EXP::master, mk_stmt(), EXP::noblock, NULL, opt, EXP::par_cnt, EXP::parsect, q, Q_AREA, s, std, STD_ACCEL, STD_AST, STD_BR, STD_KERNEL, STD_LABEL, STD_LINENO, STD_NEXT, STD_PREV, EXP::task, and wr_block().
Referenced by flowgraph().
postdominators()
void postdominators (void)
Definition at line 1082 of file fgraph.c.
References BUCKET, dom, dom_link, DOM_NEW, eval(), FG_DFN, FG_PDOM, FG_SUCC, FG_XT, FREE, FREE_BUCKET_AREA, GET_BUCKET, i, OPT::num_nodes, opt, p, PARENT, PSI_NEXT, PSI_NODE, PSI_P_NULL, rdfn, rdfs(), RVTX_NODE, SEMI, and w.
Referenced by optimize_alloc(), and sectfloat().
rdfs()
static void rdfs (int v) static
Definition at line 1215 of file fgraph.c.
References ANCESTOR, FG_DFN, FG_PRED, FG_RDFN, LABEL, p, PARENT, PSI_NEXT, PSI_NODE, PSI_P_NULL, rdfn, rdfs(), RVTX_NODE, SEMI, and w.
Referenced by postdominators(), and rdfs().
rdilts()
void rdilts (int fgx)
'read' a flowgraph node.
...
This defines the 0th STD entry to locate the beginning and end STDs of the node. The STD state (values of the STDs in the 0th entry and the beginning and last STDs of the flowgraph node) is saved. After a node has been read, its STD list has the following properties:
the list is terminated by 0.
STD_NEXT(0) locates the first STD in the list.
STD_PREV(0) locates the last STD in the list.
Definition at line 1636 of file fgraph.c.
References f, FG_LNEXT, FG_LPREV, FG_STDFIRST, FG_STDLAST, fgx, n, p, rw_state, STD_NEXT, and STD_PREV.
Referenced by _avail(), add_loop_hd(), add_single_loop_exit(), check_ilm(), collect_root_ilis(), exp_end(), exp_mp_func_prologue(), exp_remove_gsmove(), exp_smp(), get_temp_forall2(), is_branch_between(), is_contains_ast_between(), lflow_of_block(), ll_save_gtid_val(), llvmAddConcurEntryBlk(), llvmAddConcurExitBlk(), mk_dealloc_stub(), mk_loop_hdtl(), move_invar_std(), must_follow(), reassociate(), reg_assign1(), remove_scope_labels(), resetMppBih(), resetTaskBih(), rm_smove(), smp_conflict(), storedums(), and visit_ilis().
rm_edge()
void rm_edge (int fg1, int fg2)
Remove the edge fg1 -> fg2 from the flowgraph.
remove fg2 from succ(fg1)
remove fg1 from pred(fg2)
Definition at line 1413 of file fgraph.c.
References assert, dump_node(), FG_LNEXT, FG_LOOP, FG_LPREV, FG_NEXT, FG_PRED, FG_SUCC, FG_XT, gbl, i, j, lp, LP_FG, OPTDBG, p, prev, PSI_NEXT, PSI_NODE, PSI_P_NULL, and rm_edge().
Referenced by add_single_loop_exit(), and rm_edge().
set_std_fg()
static void set_std_fg (void) static
Definition at line 556 of file fgraph.c.
References fg, FG_DFN, FG_STDFIRST, FG_STDLAST, OPT::num_nodes, opt, STD_FG, STD_NEXT, and stdx.
Referenced by flowgraph().
unlnkilt()
void unlnkilt (int stdx, int fgx, LOGICAL reuse)
Parameters
stdx std to be deleted
fgx fg of block from which std is deleted (0 => read)
reuse TRUE if ilt is to be reused
Definition at line 1731 of file fgraph.c.
References add_stmt_after(), assert, FG_STDFIRST, FG_STDLAST, fgx, i, j, mk_stmt(), STD_DELETE, STD_LABEL, STD_NEXT, STD_PREV, stdx, and TRUE.
Referenced by delete_stores(), delilt(), flow(), merge_blocks(), and rm_def_rloop().
wr_block()
static void wr_block (void) static
Definition at line 969 of file fgraph.c.
References EXP::curfg, EXP::curstd, expb, FG_STDLAST, and EXP::noblock.
Referenced by addCopyinInplace(), cr_block(), exp_end(), exp_header(), exp_label(), exp_misc(), exp_mp_atomic_update(), exp_smp(), genswitch(), makeCopyprivArray_tls(), partition_blocks(), resetMppBih(), resetTaskBih(), section_create_endblock(), and setTaskloopVars().
wrilts()
void wrilts (int fgx)
'write' the flowgraph node.
...
This restores the STD list to be a single list of all of the STDs in the function. The STD state is restored.
Definition at line 1679 of file fgraph.c.
References assert, f, FG_STDFIRST, FG_STDLAST, fgx, n, p, rw_state, STD_NEXT, and STD_PREV.
Referenced by _avail(), add_loop_hd(), add_single_loop_exit(), check_ilm(), collect_root_ilis(), exp_end(), exp_mp_func_prologue(), exp_remove_gsmove(), exp_smp(), get_temp_forall2(), is_branch_between(), is_contains_ast_between(), lflow_of_block(), ll_save_gtid_val(), llvmAddConcurEntryBlk(), llvmAddConcurExitBlk(), mk_dealloc_stub(), mk_loop_hdtl(), move_invar_std(), must_follow(), reassociate(), reg_assign1(), remove_scope_labels(), resetMppBih(), resetTaskBih(), rm_smove(), smp_conflict(), storedums(), visit_ilis(), and wr_block().
Variable Documentation
ancestor
int* ancestor
Definition at line 45 of file fgraph.c.
assigned_labels
Q_ITEM* assigned_labels static
Definition at line 23 of file fgraph.c.
Referenced by flowgraph(), and partition_blocks().
bucket
PSI_P* bucket
Definition at line 48 of file fgraph.c.
struct { ... } dom
Referenced by dominators(), postdominators(), sectfloat(), and selection_sort().
expb
EXP expb static
Definition at line 601 of file fgraph.c.
Referenced by _exp_mp_atomic_update(), addarth(), addCopyinInplace(), addili(), allochartmp(), begin_entry(), check_ilm(), chk_block(), chk_block_suppress_throw(), cmplx_to_mem(), cr_block(), create_llvm_display_temp(), exp_bran(), exp_call(), exp_end(), exp_end_atomic(), exp_header(), exp_init(), exp_label(), exp_misc(), exp_mp_func_prologue(), exp_qjsr(), exp_restore_mxcsr(), exp_scope_label(), exp_smp(), exp_smp_init(), exp_store(), exp_type_bound_proc_call(), exp_zqjsr(), expand(), expSmpSectionInit(), flsh_saveili(), genswitch(), getchartmp(), getdumlen(), ll_save_gtid_val(), llvmAddConcurEntryBlk(), llvmAddConcurExitBlk(), llvmGetExpbCurIlt(), llvmSetExpbCurIlt(), makeCopyprivArray_tls(), mk_swlist(), mk_swtab(), mk_swtab_ll(), mkarglist(), partition_blocks(), pp_entries_mixedstrlen(), pp_params(), pp_params_mixedstrlen(), propagate_bihflags(), reg_assign1(), resetMppBih(), resetTaskBih(), section_create_endblock(), setTaskloopVars(), store_aret(), and wr_block().
label
int* label
Definition at line 46 of file fgraph.c.
Referenced by _exp_mp_atomic_update(), _printili(), add_loop_preheader(), bblock(), begin_inlined_scope(), check_loop_bound(), end_inlined_scope(), exp_smp(), find_scope_labels(), gen_switch(), genswitch(), is_blockaddr_store(), llvm_lower_enddo_stmt(), lower_do_stmt(), lower_enddo_stmt(), lower_start_stmt(), lower_stmt(), merge_bih(), partition_blocks(), plabel(), process_blockaddr_sptr(), read_label(), replace_label(), semant3(), and track_scope_label().
next
int next
Definition at line 1617 of file fgraph.c.
parent
int* parent
Definition at line 44 of file fgraph.c.
Referenced by __fort_dump_type(), _ccff_info(), _linearize(), add_dt_subscr(), add_parent_to_bounds(), add_psd(), add_to_parent(), addinlfile(), ast_rewrite(), begin_submodule(), bounds_match(), build_vft(), check_derived_type_array_section(), clen_parent_is_param(), convert_subscript(), count_parent_pointers(), ENTF90(), find_psd(), find_section_subscript(), first_element_from_section(), fix_mem_bounds(), fix_mem_bounds2(), get_ancestor_module(), get_header_member_with_parent(), get_parent_pointer(), get_parm_ast(), handle_nested_threadprivate(), hash_mem(), inheritTbps(), insert_forall_comm(), intermediate_members(), localflow(), make_sec_from_ast_chk(), mk_component_ast(), mk_mem_ptr_shape(), mk_member(), nml_traverse(), pop_scope_level(), process_final_procedures(), queue_dtype(), queue_type_param(), read_fileentries(), read_symbol(), remove_loop(), remove_subscript_expressions(), semant1(), semant3(), semCheckTbp(), set_internref_flag(), transform_move_alloc(), and write_parent_pointers().
prev
int prev
Definition at line 1618 of file fgraph.c.
Referenced by __reduction_slowpath(), access_swtab_base_label(), access_swtab_case_label(), add_loop_preheader(), add_member_for_llvm(), add_to_list(), check_barrier(), check_cancel(), check_crit(), clearStaleRecs(), construct_acl_from_ast(), defer_arg_chk(), defer_pt_decl(), defer_put_kind_type_param(), delbih(), delilt(), dinits(), do_distbegin(), enqueueTbp(), enter_dir(), ENTFTN(), gen_alloc_mem_initialize_for_sym2(), get_exttype_list(), getict(), getivl(), has_final_members(), has_type_parameter2(), leave_dir(), lower_start_stmt(), lower_stmt(), mk_ido_std_range(), overwrite_fma_add(), push_lower_refd_list(), put_default_kind_type_param(), put_length_type_param(), queue_type_param(), remove_from_use_tree(), remove_instr(), remove_list(), remove_loop(), remove_stmt(), restore_hoist_stmt(), rm_edge(), sdrop_stmt(), semant2(), semant3(), set_iftype(), set_ilmfile(), sfloat_stmt(), sfloat_stmt2(), and toi64().
rdfn
int rdfn static
Definition at line 1080 of file fgraph.c.
Referenced by postdominators(), and rdfs().
struct { ... } rw_state
Referenced by rdilts(), and wrilts().
semi
int* semi
Definition at line 47 of file fgraph.c.
struct { ... } std0
std_after
int std_after
Definition at line 1621 of file fgraph.c.
std_before
int std_before
Definition at line 1620 of file fgraph.c.