flang: fill.c File Reference
fill.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "fort_vars.h"
Functions
static void I8() fills_loop (char *ab, F90_Desc *as, void *fb, __INT_T off0, __INT_T dim)
void I8() __fort_fills (char *ab, F90_Desc *as, void *fb)
Variables
void(* __fort_scalar_copy [__NTYPES])(void *rp, void *sp, int size)
Function Documentation
__fort_fills()
void I8() __fort_fills (char * ab, F90_Desc * as, void * fb)
Definition at line 48 of file fill.c.
References __fort_cycle_bounds(), __fort_scalar_copy, __OFF_TEMPLATE, DIST_SCOFF_G, F90_FLAGS_G, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, fills_loop(), and I8.
Referenced by eoshift_scalar(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
fills_loop()
static void I8() fills_loop (char * ab, F90_Desc * as, void * fb, __INT_T off0, __INT_T dim) static
Definition at line 14 of file fill.c.
References __fort_bcopysl(), __fort_block_bounds(), cl, DECL_DIM_PTRS, dim, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_LEN_G, fills_loop(), I8, off, and SET_DIM_PTRS.
Referenced by __fort_fills(), and fills_loop().
Variable Documentation
__fort_scalar_copy
void(* __fort_scalar_copy[__NTYPES])(void *rp, void *sp, int size) (void * rp, void * sp, int size) extern
Referenced by __fort_fills().