flang: findloop.h File Reference
findloop.h File Reference
#include "universal.h"
#include <stdio.h>
Functions
bool contains_loop (int lp1, int lp2)
...
bool is_childloop (int lp1, int lp2)
...
bool is_dominator (int v, int w)
...
bool is_post_dominator (int v, int w)
...
bool is_tail_aexe (int lp)
...
bool overlapping_loops (int lp1, int lp2)
...
void __dump_loop (FILE *ff, int lp)
...
void dump_loops (void)
...
void __dump_region (FILE *ff, int lp)
...
void dump_region (int lp)
...
void findloop (int hlopt_bv)
...
void findlooptopsort (void)
...
void reorderloops (void)
...
void sortloops (void)
...
Function Documentation
__dump_loop()
void __dump_loop (FILE * ff, int lp)
...
Definition at line 1373 of file findloop.c.
References __dump_region(), __print_nme(), BIH_LINENO, FG_TO_BIH, i, lp, LP_CALLFG, LP_CHILD, LP_CNCALL, LP_COUNT, LP_CS, LP_CSECT, LP_EXITS, LP_FG, LP_FORALL, LP_HEAD, LP_INNERMOST, LP_JMP_TBL, LP_LEVEL, LP_MASTER, LP_MEXITS, LP_NOBLA, LP_PARENT, LP_PARLOOP, LP_PARREGN, LP_PARSECT, LP_QJSR, LP_SIBLING, LP_STL_PAR, LP_TAIL, LP_TAIL_AEXE, LP_TASK, LP_VOLLAB, LP_XTNDRNG, LP_ZEROTRIP, NULL, p, PSI_NEXT, PSI_NODE, PSI_P_NULL, q, and void().
Referenced by dump_loops().
__dump_region()
void __dump_region (FILE * ff, int lp)
...
Definition at line 1345 of file findloop.c.
References FG_NEXT, j, lp, and LP_FG.
Referenced by __dump_loop(), and dump_region().
contains_loop()
bool contains_loop (int lp1, int lp2)
...
Definition at line 1315 of file findloop.c.
References LP_LEVEL, and LP_PARENT.
Referenced by overlapping_loops().
dump_loops()
void dump_loops (void)
...
...
Definition at line 1451 of file findloop.c.
References __dump_loop(), BIH_LABEL, gbl, getprint(), i, j, LP_INNERMOST, LP_LOOP, OPT::nloops, and opt.
Referenced by collapse_arrays(), comm_optimize_post(), comm_optimize_pre(), flow(), hlopt_init(), optimize(), and optimize_alloc().
dump_region()
void dump_region (int lp)
...
...
Definition at line 1365 of file findloop.c.
References __dump_region(), gbl, and lp.
Referenced by add_loop_preheader().
findloop()
void findloop (int hlopt_bv)
...
...
Definition at line 52 of file findloop.c.
References add_lpexit(), assert, BIH_EX, BIH_LABEL, BIH_TO_FG, build_loop(), BZERO, convert_loop(), OPT::dfn, EDGE_NEXT, EDGE_PRED, EDGE_SUCC, ERR_Informational, OPT::exitfg, FG_DFN, FG_LOOP, FG_NEXT, FG_SUCC, FG_TO_BIH, gbl, getitem(), getprint(), HLOPT_ENDTEST, i, is_dominator(), is_tail_aexe(), lp, LP_CHILD, LP_CNCALL, LP_COUNT, LP_FG, LP_HEAD, LP_INNERMOST, LP_LEVEL, LP_LOOP, LP_PARENT, LP_RGSET, LP_SIBLING, LP_TAIL, LP_TAIL_AEXE, lp_topsort, LP_XTNDRNG, malformed(), MR_NUMGLB, naturalloop, OPT::nloops, NUM_RTE, opt, OPTDBG, p, PSI_EXIT, PSI_NEXT, PSI_NODE, PSI_P_NULL, pt, q, RTEMPS, STG_CLEAR, STG_NEXT, top_sort(), unvisit(), VTX_NODE, XBIT, and z.
Referenced by comm_optimize_post(), comm_optimize_pre(), early_flow_init(), findlooptopsort(), flow(), hlopt_init(), optimize(), optimize_alloc(), and redundss().
findlooptopsort()
void findlooptopsort (void)
...
...
Definition at line 428 of file findloop.c.
is_childloop()
bool is_childloop (int lp1, int lp2)
...
Definition at line 1298 of file findloop.c.
References is_childloop(), LP_CHILD, and LP_SIBLING.
Referenced by is_childloop().
is_dominator()
bool is_dominator (int v, int w)
...
...
Parameters
v first node
w second node
Returns
true if 'v' dominates 'w'
Walk up dominator tree from 'w', stop at 'v' (return true) or when we reach a node above 'v' in the spanning tree.
Definition at line 553 of file findloop.c.
References FG_DFN, FG_DOM, and w.
Referenced by _avail(), def_ok(), eliminate_get_scalar(), eliminate_rt(), findloop(), fuse_forall(), hoist_comms(), invar_mark(), is_dominator_fg(), is_fusable(), is_same_def(), iscall_in_path(), must_follow(), same_forall_bnds(), same_forall_size(), sectfloat(), and selection_sort().
is_post_dominator()
bool is_post_dominator (int v, int w)
...
Definition at line 579 of file findloop.c.
References FG_PDOM, and w.
Referenced by sectfloat().
is_tail_aexe()
bool is_tail_aexe (int lp)
...
Definition at line 596 of file findloop.c.
References BIH_FT, cnt, fg, FG_LOOP, FG_PRED, FG_TO_BIH, lp, LP_HEAD, LP_MEXITS, LP_TAIL, p, PSI_NEXT, PSI_NODE, and PSI_P_NULL.
Referenced by findloop().
overlapping_loops()
bool overlapping_loops (int lp1, int lp2)
...
Definition at line 1333 of file findloop.c.
References contains_loop(), and LP_LEVEL.
reorderloops()
void reorderloops (void)
...
Definition at line 1227 of file findloop.c.
sortloops()
void sortloops (void)
...
Definition at line 1248 of file findloop.c.
References BIH_NEXT, BIH_TO_FG, FG_LOOP, FG_NEXT, fgx, gbl, LP_CHILD, LP_FG, LP_HEAD, LP_PARENT, LP_SIBLING, lpx, OPT::nloops, OPT::num_nodes, and opt.