flang: findloop.c File Reference
findloop.c File Reference
optimizer submodule to find loops in a flow graph. Used by the optimizer and vectorizer.
#include "findloop.h"
#include "gbldefs.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "ast.h"
#include "nme.h"
#include "optimize.h"
Macros
#define TOP(i) topb[i].top
#define COUNT(i) topb[i].count
#define QLINK(i) topb[i].count
#define SUCC(p) p->succ
#define NEXT(p) p->next
Functions
static void top_sort (void)
Topological sort.
static void build_loop (int loop)
Build the natural loop and loop region given the head and tail flow graph nodes.
static void add_to_region (int v)
Add a node to the loop region.
static void add_lpexit (int, int)
static void unvisit (int list, int clearfgloop)
Unvisit blocks in the natural loop created by build_loop; also optionally unvisit blocks in the loop region.
static void malformed (int, int)
static void add_to_malf (int)
static void convert_loop (int loop)
Routine to find loops whose control flow follows the pattern of a "while" loop.
void findloop (int hlopt_bv)
A routine to find the loops in a flow graph.
void findlooptopsort (void)
findlooptopsort builds loops and adds the FG nodes to the loop in topological order, top-down.
bool is_dominator (int v, int w)
Determine if a node dominates another.
bool is_post_dominator (int v, int w)
...
bool is_tail_aexe (int lp)
...
static void addloop (int l, int *pn)
void reorderloops ()
...
void sortloops ()
...
bool is_childloop (int lp1, int lp2)
...
bool contains_loop (int lp1, int lp2)
...
bool overlapping_loops (int lp1, int lp2)
...
void __dump_region (FILE *ff, int lp)
...
void dump_region (int lp)
Dump a loop region.
void __dump_loop (FILE *ff, int lp)
...
void dump_loops (void)
Dump the loop table.
Variables
static int current_lp
static int current_lp_tail
static int lp_topsort
static int naturalloop
static int malformed_loop
Detailed Description
optimizer submodule to find loops in a flow graph. Used by the optimizer and vectorizer.
Definition in file findloop.c.
Macro Definition Documentation
COUNT
#define COUNT (i) topb[i].count
NEXT
#define NEXT (p) p->next
QLINK
#define QLINK (i) topb[i].count
SUCC
#define SUCC (p) p->succ
TOP
#define TOP (i) topb[i].top
Function Documentation
__dump_loop()
void __dump_loop (FILE * ff, int lp)
...
Definition at line 1373 of file findloop.c.
References __dump_region(), __print_nme(), BIH_LINENO, FG_TO_BIH, i, lp, LP_CALLFG, LP_CHILD, LP_CNCALL, LP_COUNT, LP_CS, LP_CSECT, LP_EXITS, LP_FG, LP_FORALL, LP_HEAD, LP_INNERMOST, LP_JMP_TBL, LP_LEVEL, LP_MASTER, LP_MEXITS, LP_NOBLA, LP_PARENT, LP_PARLOOP, LP_PARREGN, LP_PARSECT, LP_QJSR, LP_SIBLING, LP_STL_PAR, LP_TAIL, LP_TAIL_AEXE, LP_TASK, LP_VOLLAB, LP_XTNDRNG, LP_ZEROTRIP, NULL, p, PSI_NEXT, PSI_NODE, PSI_P_NULL, q, and void().
Referenced by dump_loops().
__dump_region()
void __dump_region (FILE * ff, int lp)
...
Definition at line 1345 of file findloop.c.
References FG_NEXT, j, lp, and LP_FG.
Referenced by __dump_loop(), and dump_region().
add_lpexit()
static void add_lpexit (int lpx, int exit) static
Definition at line 762 of file findloop.c.
References gbl, GET_PSI, LP_EXITS, LP_MEXITS, lpx, OPTDBG, p, PSI_ALL, PSI_NEXT, PSI_NODE, and PSI_P_NULL.
Referenced by findloop().
add_to_malf()
static void add_to_malf (int v) static
Definition at line 844 of file findloop.c.
References add_to_malf(), FG_NATNXT, FG_PRED, FG_VISITED, malformed_loop, p, PSI_NEXT, PSI_NODE, and PSI_P_NULL.
Referenced by add_to_malf(), and malformed().
add_to_region()
static void add_to_region (int v) static
Add a node to the loop region.
Definition at line 700 of file findloop.c.
References add_to_region(), BIH_EX, BIH_NOBLA, current_lp, current_lp_tail, FG_JMP_TBL, FG_LOOP, FG_NATNXT, FG_NEXT, FG_PRED, FG_TO_BIH, FG_VISITED, LP_CALLFG, LP_FG, LP_JMP_TBL, LP_NOBLA, lp_topsort, naturalloop, p, PSI_FT, PSI_NEXT, PSI_NODE, and PSI_P_NULL.
Referenced by add_to_region(), and build_loop().
addloop()
static void addloop (int l, int * pn) static
Definition at line 1216 of file findloop.c.
References addloop(), LP_CHILD, LP_LOOP, and LP_SIBLING.
Referenced by addloop(), and reorderloops().
build_loop()
static void build_loop (int loop) static
Build the natural loop and loop region given the head and tail flow graph nodes.
The natural loop is represented by a linked list headed by the variable naturalloop. As nodes are visited, they are added to this list. The natural loop is built by first adding the loop head to the list and then visiting the tail of the loop and recursively visiting its predecessors. The natural loop contains the nodes of any nested loops. Note that if there are other retreating edges whose head values are identical to the head of the loop, these extra edges are taken into consideration so that the loops defined by retreating edges with identical head values are combined into a single loop.
The loop region is defined to be the set of nodes in the natural loop which do not belong to any nested loops. The loop region is represented as a linked list headed by the field LP_FG of the current loop. The nodes which belong to the current loop region are linked together using the FG_NEXT fields. The field FG_LOOP records the loop to which it belongs. Also, the loop's LP_CALLFG and LP_NOBLA fields are set if the respective criteria are met.
NOTE that build_loop is used for two purposes:
to aid in determining the level and parent values of the loops so that the loops can be sorted,
to build the regions of the loops after the loops have been sorted. For the first case, the natural loop list and loop region list are identical.
Definition at line 651 of file findloop.c.
References add_to_region(), BIH_EX, BIH_NOBLA, BIH_PARALN, BIH_PARLOOP, current_lp, current_lp_tail, EDGE_NEXT, EDGE_PRED, FG_JMP_TBL, FG_LOOP, FG_NATNXT, FG_NEXT, FG_PAR, FG_TO_BIH, FG_VISITED, LP_CALLFG, LP_EDGE, LP_FG, LP_HEAD, LP_JMP_TBL, LP_NOBLA, LP_PARLOOP, LP_TAIL, and naturalloop.
Referenced by findloop().
contains_loop()
bool contains_loop (int lp1, int lp2)
...
Definition at line 1315 of file findloop.c.
References LP_LEVEL, and LP_PARENT.
Referenced by overlapping_loops().
convert_loop()
static void convert_loop (int loop) static
Routine to find loops whose control flow follows the pattern of a "while" loop.
A "while <cond>" loop is changed to "if <cond> do ... while !<cond>". A "for" loop is a form of a "while" loop.
Definition at line 1202 of file findloop.c.
Referenced by findloop().
dump_loops()
void dump_loops (void)
Dump the loop table.
...
Definition at line 1451 of file findloop.c.
References __dump_loop(), BIH_LABEL, gbl, getprint(), i, j, LP_INNERMOST, LP_LOOP, OPT::nloops, and opt.
Referenced by collapse_arrays(), comm_optimize_post(), comm_optimize_pre(), flow(), hlopt_init(), optimize(), and optimize_alloc().
dump_region()
void dump_region (int lp)
Dump a loop region.
...
Definition at line 1365 of file findloop.c.
References __dump_region(), gbl, and lp.
Referenced by add_loop_preheader().
findloop()
void findloop (int hlopt_bv)
A routine to find the loops in a flow graph.
...
Definition at line 52 of file findloop.c.
References add_lpexit(), assert, BIH_EX, BIH_LABEL, BIH_TO_FG, build_loop(), BZERO, convert_loop(), OPT::dfn, EDGE_NEXT, EDGE_PRED, EDGE_SUCC, ERR_Informational, OPT::exitfg, FG_DFN, FG_LOOP, FG_NEXT, FG_SUCC, FG_TO_BIH, gbl, getitem(), getprint(), HLOPT_ENDTEST, i, is_dominator(), is_tail_aexe(), lp, LP_CHILD, LP_CNCALL, LP_COUNT, LP_FG, LP_HEAD, LP_INNERMOST, LP_LEVEL, LP_LOOP, LP_PARENT, LP_RGSET, LP_SIBLING, LP_TAIL, LP_TAIL_AEXE, lp_topsort, LP_XTNDRNG, malformed(), MR_NUMGLB, naturalloop, OPT::nloops, NUM_RTE, opt, OPTDBG, p, PSI_EXIT, PSI_NEXT, PSI_NODE, PSI_P_NULL, pt, q, RTEMPS, STG_CLEAR, STG_NEXT, top_sort(), unvisit(), VTX_NODE, XBIT, and z.
Referenced by comm_optimize_post(), comm_optimize_pre(), early_flow_init(), findlooptopsort(), flow(), hlopt_init(), optimize(), optimize_alloc(), and redundss().
findlooptopsort()
void findlooptopsort (void)
findlooptopsort builds loops and adds the FG nodes to the loop in topological order, top-down.
...
Definition at line 428 of file findloop.c.
References findloop(), HLOPT_ALL, and lp_topsort.
Referenced by sectfloat().
is_childloop()
bool is_childloop (int lp1, int lp2)
...
Definition at line 1298 of file findloop.c.
References is_childloop(), LP_CHILD, and LP_SIBLING.
Referenced by is_childloop().
is_dominator()
bool is_dominator (int v, int w)
Determine if a node dominates another.
...
Parameters
v first node
w second node
Returns
true if 'v' dominates 'w'
Walk up dominator tree from 'w', stop at 'v' (return true) or when we reach a node above 'v' in the spanning tree.
Definition at line 553 of file findloop.c.
References FG_DFN, FG_DOM, and w.
Referenced by _avail(), def_ok(), eliminate_get_scalar(), eliminate_rt(), findloop(), fuse_forall(), hoist_comms(), invar_mark(), is_dominator_fg(), is_fusable(), is_same_def(), iscall_in_path(), must_follow(), same_forall_bnds(), same_forall_size(), sectfloat(), and selection_sort().
is_post_dominator()
bool is_post_dominator (int v, int w)
...
Definition at line 579 of file findloop.c.
References FG_PDOM, and w.
Referenced by sectfloat().
is_tail_aexe()
bool is_tail_aexe (int lp)
...
Definition at line 596 of file findloop.c.
References BIH_FT, cnt, fg, FG_LOOP, FG_PRED, FG_TO_BIH, lp, LP_HEAD, LP_MEXITS, LP_TAIL, p, PSI_NEXT, PSI_NODE, and PSI_P_NULL.
Referenced by findloop().
malformed()
static void malformed (int head, int tail) static
Build the natural loop and loop region given the head and tail flow graph nodes and mark the nodes in the loop as 'malformed' (FG_MALF_LP). Make sure the nodes of any enclosed loop are no set.
Definition at line 808 of file findloop.c.
References add_to_malf(), BIH_LABEL, BIH_LINENO, FG_LOOP, FG_MALF_LP, FG_NATNXT, FG_TO_BIH, FG_VISITED, gbl, getprint(), i, malformed_loop, and OPTDBG.
Referenced by findloop().
overlapping_loops()
bool overlapping_loops (int lp1, int lp2)
...
Definition at line 1333 of file findloop.c.
References contains_loop(), and LP_LEVEL.
reorderloops()
void reorderloops (void)
...
Definition at line 1227 of file findloop.c.
References addloop(), ERR_Severe, interr(), LP_CHILD, LP_SIBLING, n, OPT::nloops, and opt.
Referenced by sectfloat().
sortloops()
void sortloops (void)
...
Definition at line 1248 of file findloop.c.
References BIH_NEXT, BIH_TO_FG, FG_LOOP, FG_NEXT, fgx, gbl, LP_CHILD, LP_FG, LP_HEAD, LP_PARENT, LP_SIBLING, lpx, OPT::nloops, OPT::num_nodes, and opt.
top_sort()
static void top_sort (void) static
Topological sort.
This routine is used to sort the loops found in the flowgraph such that a loop X is processed for optimizations before any of the loops containing X. The algorithm used is the topological sort as defined in Knuth (p. 262), The Art of Computer Programming, Volume 1/Fundamental Algorithms.
Definition at line 447 of file findloop.c.
References assert, COUNT, count, ERR_Severe, FREE, freearea(), gbl, getitem(), k, lp, LP_LOOP, LP_PARENT, n, NEW, next, NEXT, OPT::nloops, NULL, opt, OPTDBG, p, QLINK, r, SUCC, TOP, top, and TOPI_AREA.
Referenced by findloop().
unvisit()
static void unvisit (int list, int clearfgloop) static
Unvisit blocks in the natural loop created by build_loop; also optionally unvisit blocks in the loop region.
Definition at line 790 of file findloop.c.
References FG_LOOP, FG_NATNXT, FG_VISITED, i, and list.
Referenced by findloop().
Variable Documentation
current_lp
int current_lp static
Definition at line 42 of file findloop.c.
Referenced by add_to_region(), and build_loop().
current_lp_tail
int current_lp_tail static
Definition at line 43 of file findloop.c.
Referenced by add_to_region(), and build_loop().
lp_topsort
int lp_topsort static
Definition at line 44 of file findloop.c.
Referenced by add_to_region(), findloop(), and findlooptopsort().
malformed_loop
int malformed_loop static
Definition at line 801 of file findloop.c.
Referenced by add_to_malf(), and malformed().
naturalloop
int naturalloop static
Definition at line 45 of file findloop.c.
Referenced by add_to_region(), build_loop(), and findloop().