flang: fioMacros.h File Reference
fioMacros.h File Reference
descriptor and other definitions
#include <stdlib.h>
#include <stdarg.h>
#include "fortDt.h"
#include "fioStructs.h"
#include "FuncArgMacros.h"
#include "fort_vars.h"
Classes
struct procdim
struct proc
struct F90_DescDim
Fortran descriptor dimension info.
struct F90_Desc
Fortran descriptor header.
struct DIST_DescDim
struct DIST_Desc
struct repl_t
struct sked
struct cgrp
Macros
#define ABSENT (ENTCOMN(0, 0) + 2)
#define ABSENTC ENTCOMN(0C, 0c)
#define ISPRESENT(p)
#define ISPRESENTC(p) ((CADR(p)) && (CADR(p) != ABSENTC))
#define ISSEQUENCE(p) (F90_TAG_G(p) < 0 && F90_TAG_G(p) != -__DESC)
#define ISSCALAR(p) (F90_TAG_G(p) > 0 && F90_TAG_G(p) != __DESC)
#define TYPEKIND(p)
#define EXTENSION_BLOCK_MASK 0xFFFFF80
#define ALIGNZ 16
#define ALIGNR(x) (((x) + ALIGNZ - 1) & ~(ALIGNZ - 1))
#define __DIST_ENTRY_RECV(cpu, len)
#define __DIST_ENTRY_RECV_DONE(cpu)
#define __DIST_ENTRY_SEND(cpu, len)
#define __DIST_ENTRY_SEND_DONE(cpu)
#define __DIST_ENTRY_COPY(len)
#define __DIST_ENTRY_COPY_DONE()
#define __DIST_ENTRY_ARECV(cpu, len, reqn)
#define __DIST_ENTRY_ARECV_DONE(cpu)
#define __DIST_ENTRY_ASEND(cpu, len, reqn)
#define __DIST_ENTRY_ASEND_DONE(cpu)
#define __DIST_ENTRY_AWAIT(reqn)
#define __DIST_ENTRY_AWAIT_DONE(reqn)
#define GET_DIST_MASK_LOG __fort_mask_log
#define GET_DIST_MASK_LOG1 __fort_mask_log1
#define GET_DIST_MASK_LOG2 __fort_mask_log2
#define GET_DIST_MASK_LOG4 __fort_mask_log4
#define GET_DIST_MASK_LOG8 __fort_mask_log8
#define GET_DIST_MASK_INT1 __fort_mask_int1
#define GET_DIST_MASK_INT2 __fort_mask_int2
#define GET_DIST_MASK_INT4 __fort_mask_int4
#define GET_DIST_MASK_INT8 __fort_mask_int8
#define GET_DIST_TRUE_LOG __fort_true_log
#define GET_DIST_TRUE_LOG_ADDR &__fort_true_log
#define GET_DIST_TRUE_LOG1 __fort_true_log1
#define GET_DIST_TRUE_LOG2 __fort_true_log2
#define GET_DIST_TRUE_LOG4 __fort_true_log4
#define GET_DIST_TRUE_LOG8 __fort_true_log8
#define SET_DIST_MASK_LOG(n) __fort_mask_log = n
#define SET_DIST_MASK_LOG1(n) __fort_mask_log1 = n
#define SET_DIST_MASK_LOG2(n) __fort_mask_log2 = n
#define SET_DIST_MASK_LOG4(n) __fort_mask_log4 = n
#define SET_DIST_MASK_LOG8(n) __fort_mask_log8 = n
#define SET_DIST_MASK_INT1(n) __fort_mask_int1 = n
#define SET_DIST_MASK_INT2(n) __fort_mask_int2 = n
#define SET_DIST_MASK_INT4(n) __fort_mask_int4 = n
#define SET_DIST_MASK_INT8(n) __fort_mask_int8 = n
#define SET_DIST_TRUE_LOG(n) __fort_true_log = n
#define SET_DIST_TRUE_LOG1(n) __fort_true_log1 = n
#define SET_DIST_TRUE_LOG2(n) __fort_true_log2 = n
#define SET_DIST_TRUE_LOG4(n) __fort_true_log4 = n
#define SET_DIST_TRUE_LOG8(n) __fort_true_log8 = n
#define GET_DIST_MAXS(idx) __fort_maxs[idx]
#define GET_DIST_MINS(idx) __fort_mins[idx]
#define GET_DIST_SHIFTS(idx) __fort_shifts[idx]
#define GET_DIST_SIZE_OF(idx) __fort_size_of[idx]
#define GET_DIST_TRUES(idx) __fort_trues[idx]
#define GET_DIST_TYPENAMES(idx) __fort_typenames[idx]
#define GET_DIST_UNITS(idx) __fort_units[idx]
#define SET_DIST_MAXS(idx, val) __fort_maxs[idx] = val
#define SET_DIST_MINS(idx, val) __fort_mins[idx] = val
#define SET_DIST_SHIFTS(idx, val) __fort_shifts[idx] = val
#define SET_DIST_SIZE_OF(idx, val) __fort_size_of[idx] = val
#define SET_DIST_TRUES(idx, val) __fort_trues[idx] = val
#define SET_DIST_TYPENAMES(idx, val) __fort_typenames[idx] = val
#define SET_DIST_UNITS(idx, val) __fort_units[idx] = val
#define GET_DIST_ONE __fort_one
#define GET_DIST_ZED __fort_zed
#define GET_DIST_HEAPZ 0
#define GET_DIST_IOPROC 0
#define GET_DIST_LCPU 0
#define GET_DIST_TCPUS 1
#define GET_DIST_TRANSNAM "rpm1"
#define GET_DIST_DEBUG __fort_debug
#define GET_DIST_DEBUGN __fort_debugn
#define GET_DIST_LCPU_ADDR &__fort_lcpu
#define GET_DIST_PARIO __fort_pario
#define GET_DIST_QUIET __fort_quiet
#define GET_DIST_TCPUS_ADDR &__fort_tcpus
#define GET_DIST_TIDS __fort_tids
#define GET_DIST_TIDS_ELEM(idx) __fort_tids[idx]
#define SET_DIST_DEBUG(n) __fort_debug = n
#define SET_DIST_DEBUGN(n) __fort_debugn = n
#define SET_DIST_HEAPZ(n) __fort_heapz = n
#define SET_DIST_IOPROC(n) __fort_ioproc = n
#define SET_DIST_LCPU(n) __fort_lcpu = n
#define SET_DIST_PARIO(n) __fort_pario = n
#define SET_DIST_QUIET(n) __fort_quiet = n
#define SET_DIST_TCPUS(n) __fort_tcpus = n
#define SET_DIST_TIDS(n) __fort_tids = n
#define SET_DIST_TIDS_ELEM(idx, val) __fort_tids[idx] = val
#define Q_CPU 0x01 /* cpu */
#define Q_CPUS 0x02 /* cpus */
#define Q_MSG 0x04 /* message */
#define Q_MSGS 0x08 /* messages */
#define Q_MEM 0x10 /* memory */
#define Q_MEMS 0x20 /* memories */
#define Q_PROF 0x40 /* profile output (not used) */
#define Q_TRAC 0x80 /* trace output (not used) */
#define Q_PROF_AVG 0x00400000 /* output min/avg/max for profile */
#define Q_PROF_NONE 0x00800000 /* disable profiling */
#define MAXDIMS 7
#define ALLDIMS (~(-1 << MAXDIMS))
#define DEBUG_COPYIN_GLOBAL 0x00001
#define DEBUG_COPYIN_LOCAL 0x00002
#define DEBUG_EXCH 0x00004
#define DEBUG_GRAD 0x00008
#define DEBUG_MMUL 0x00010
#define DEBUG_OLAP 0x00020
#define DEBUG_RDST 0x00040
#define DEBUG_REDU 0x00080
#define DEBUG_SCAL 0x00100
#define DEBUG_SCAN 0x00200
#define DEBUG_SCAT 0x00400
#define DEBUG_LVAL 0x00800
#define DEBUG_HFIO 0x01000
#define DEBUG_ALLO 0x02000
#define DEBUG_TIME 0x04000
#define DEBUG_CSHF 0x08000
#define DEBUG_EOSH 0x10000
#define DEBUG_CHAN 0x20000
#define DEBUG_COPY 0x40000
#define DEBUG_DIST 0x80000
#define DEBUG_CHECK 0x100000
#define __CORMEM_M0 666
#define __CORMEM_M1 0x58ad5e3
#define __CORMEM_M2 0x61f072b
#define NPLIMIT 0
#define __CORMEM_SCAN()
#define Sign(y) ((y) < 0 ? -1 : 1)
#define Abs(y) ((y) < 0 ? -(y) : (y))
#define Ceil(x, y) (((x) ^ (y)) > 0 ? (Abs(x) + Abs(y) - 1) / Abs(y) : (x) / (y))
#define Floor(x, y) (((x) ^ (y)) < 0 ? -(Abs(x) + Abs(y) - 1) / Abs(y) : (x) / (y))
#define Min(x, y) ((x) < (y) ? (x) : (y))
#define Max(x, y) ((x) > (y) ? (x) : (y))
#define RECIP_FRACBITS 32
#define RECIP(y) (1UL + ((unsigned long)0xFFFFFFFF) / ((unsigned long)(y)))
#define RECIP_DIV(q, x, y)
#define RECIP_MOD(r, x, y)
#define RECIP_DIVMOD(q, r, x, y)
#define __ASSUMED_SIZE 0x00000001
This descriptor flag is used to indicate that the array is declared assumed size.
#define __SEQUENCE 0x00000002
#define __ASSUMED_SHAPE 0x00000004
This descriptor flag is used to indicate that the array is declared assumed shape.
#define __SAVE 0x00000008
descriptor flag (reserved)
#define __INHERIT 0x00000010
descriptor flag (reserved)
#define __NO_OVERLAPS 0x00000020
descriptor flag (reserved)
#define __INTENT_MASK 0x3
#define __INTENT_SHIFT 6
#define __INTENT_INOUT (__INOUT << __INTENT_SHIFT)
#define __INTENT_IN (__IN << __INTENT_SHIFT)
#define __INTENT_OUT (__OUT << __INTENT_SHIFT)
#define __DIST_TARGET_MASK 0x3
#define __DIST_TARGET_SHIFT 8
#define __PRESCRIPTIVE_DIST_TARGET (__PRESCRIPTIVE << __DIST_TARGET_SHIFT)
#define __DESCRIPTIVE_DIST_TARGET (__DESCRIPTIVE << __DIST_TARGET_SHIFT)
#define __TRANSCRIPTIVE_DIST_TARGET (__TRANSCRIPTIVE << __DIST_TARGET_SHIFT)
#define __DIST_FORMAT_MASK 0x3
#define __DIST_FORMAT_SHIFT 10
#define __PRESCRIPTIVE_DIST_FORMAT (__PRESCRIPTIVE << __DIST_FORMAT_SHIFT)
#define __DESCRIPTIVE_DIST_FORMAT (__DESCRIPTIVE << __DIST_FORMAT_SHIFT)
#define __TRANSCRIPTIVE_DIST_FORMAT (__TRANSCRIPTIVE << __DIST_FORMAT_SHIFT)
#define __ALIGN_TARGET_MASK 0x3
#define __ALIGN_TARGET_SHIFT 12
#define __PRESCRIPTIVE_ALIGN_TARGET (__PRESCRIPTIVE << __ALIGN_TARGET_SHIFT)
#define __DESCRIPTIVE_ALIGN_TARGET (__DESCRIPTIVE << __ALIGN_TARGET_SHIFT)
#define __IDENTITY_MAP 0x00004000
descriptor flag (reserved)
#define __DYNAMIC 0x00008000
descriptor flag (reserved)
#define __TEMPLATE 0x00010000
descriptor flag (reserved)
#define __LOCAL 0x00020000
descriptor flag (reserved)
#define __F77_LOCAL_DUMMY 0x00040000
descriptor flag (reserved)
#define __OFF_TEMPLATE 0x00080000
descriptor flag (reserved)
#define __DIST_TARGET_AXIS 0x00100000
descriptor flag (reserved)
#define __ASSUMED_OVERLAPS 0x00200000
descriptor flag (reserved)
#define __SECTZBASE 0x00400000
When creating a section of an array, set up each dimension and compute GSIZE (see ENTF90(SECT, sect) in dist.c).
#define __BOGUSBOUNDS 0x00800000
When creating an array section, defer set up of the bounds in the descriptor after a copy.
#define __NOT_COPIED 0x01000000
descriptor flag (reserved)
#define __NOREINDEX 0x02000000
When creating an array section, use the existing bounds. Do not reset the lower bound to 1 and the upper bound to the extent.
#define __ASSUMED_GB_EXTENT 0x08000000
descriptor flag (reserved)
#define __DUMMY_COLLAPSE_PAXIS 0x10000000
descriptor flag (reserved)
#define __SEQUENTIAL_SECTION 0x20000000
#define PROC_HDR_INT_LEN 5
#define PROC_DIM_INT_LEN 5
#define F90_DESC_HDR_INT_LEN 8
#define F90_DESC_HDR_PTR_LEN 2
#define F90_DESC_DIM_INT_LEN 6
#define F90_DESC_DIM_PTR_LEN 0
#define DIST_DESC_HDR_INT_LEN 16
#define DIST_DESC_HDR_PTR_LEN 4
#define DIST_DESC_DIM_INT_LEN 34
#define DIST_DESC_DIM_PTR_LEN 1
#define F90_DPTR_LBOUND_G(p) (p##_f90_dim->lbound)
#define F90_DPTR_EXTENT_G(p) (p##_f90_dim->extent)
#define F90_DPTR_SSTRIDE_G(p) 1
#define F90_DPTR_SOFFSET_G(p) 0
#define F90_DPTR_LSTRIDE_G(p) (p##_f90_dim->lstride)
#define F90_DPTR_UBOUND_G(p) (p##_f90_dim->extent + p##_f90_dim->lbound - 1)
#define F90_DPTR_LBOUND_P(p, v) (p##_f90_dim->lbound = v)
#define F90_DPTR_EXTENT_P(p, v) (p##_f90_dim->extent = v)
#define F90_DPTR_SSTRIDE_P(p, v) (p##_f90_dim->sstride = v)
#define F90_DPTR_SOFFSET_P(p, v) (p##_f90_dim->soffset = v)
#define F90_DPTR_LSTRIDE_P(p, v) (p##_f90_dim->lstride = v)
#define F90_DIM_LBOUND_G(p, i) (p->dim[i].lbound)
#define F90_DIM_EXTENT_G(p, i) (p->dim[i].extent)
#define F90_DIM_SSTRIDE_G(p, i) 1
#define F90_DIM_SOFFSET_G(p, i) 0
#define F90_DIM_LSTRIDE_G(p, i) (p->dim[i].lstride)
#define F90_DIM_UBOUND_G(p, i) (p->dim[i].extent + p->dim[i].lbound - 1)
#define F90_DIM_LBOUND_P(p, i, v) (p->dim[i].lbound = v)
#define F90_DIM_EXTENT_P(p, i, v) (p->dim[i].extent = v)
#define F90_DIM_SSTRIDE_P(p, i, v) (p->dim[i].sstride = v)
#define F90_DIM_SOFFSET_P(p, i, v) (p->dim[i].soffset = v)
#define F90_DIM_LSTRIDE_P(p, i, v) (p->dim[i].lstride = v)
#define DPTR_UBOUND_G(p) (p##_f90_dim->extent + p##_f90_dim->lbound - 1)
#define DPTR_UBOUND_P(p, v)
#define DIM_UBOUND_G(p, i) (p->dim[i].extent + p->dim[i].lbound - 1)
#define DIM_UBOUND_P(p, i, v) (p->dim[i].extent = (v)-p->dim[i].lbound + 1; p->dim[i].ubound = v;)
#define F90_TAG_G(p) (*(int *)&(p->tag))
#define F90_RANK_G(p) ((p)->rank)
#define F90_KIND_G(p) ((p)->kind)
#define F90_LEN_G(p) ((p)->len)
#define F90_FLAGS_G(p) ((p)->flags)
#define F90_LSIZE_G(p) ((p)->lsize)
#define F90_GSIZE_G(p) ((p)->gsize)
#define F90_LBASE_G(p) ((p)->lbase)
#define F90_GBASE_G(p) ((p)->gbase)
#define F90_DIST_DESC_G(p) ((p)->dist_desc)
#define F90_TAG_P(p, v) ((p)->tag = (v))
#define F90_RANK_P(p, v) ((p)->rank = (v))
#define F90_KIND_P(p, v) ((p)->kind = (v))
#define F90_LEN_P(p, v) ((p)->len = ((__INT_T)v))
#define F90_FLAGS_P(p, v) ((p)->flags = (v))
#define F90_LSIZE_P(p, v) ((p)->lsize = (v))
#define F90_GSIZE_P(p, v) ((p)->gsize = (v))
#define F90_LBASE_P(p, v) ((p)->lbase = (v))
#define F90_GBASE_P(p, v) ((p)->gbase = (v))
#define F90_DIST_DESC_P(p, v) ((p)->dist_desc = (v))
#define SET_F90_VAR_DIST_DESC_PTR(f, h) /*(f.dist_desc = NULL)*/
#define SET_F90_DIST_DESC_PTR(p, r) /*(p->dist_desc = NULL)*/
#define SIZE_OF_RANK_n_ARRAY_DESC(n) (sizeof(F90_Desc) - (MAXDIMS - n) * sizeof(F90_DescDim))
#define DIST_DPTR_LAB_G(p) F90_DPTR_LBOUND_G(p)
#define DIST_DPTR_UAB_G(p) F90_DPTR_UBOUND_G(p)
#define DIST_DPTR_LOFFSET_G(p) (-(F90_DPTR_LSTRIDE_G(p) * DIST_DPTR_LAB_G(p)))
#define DIST_DPTR_COFSTR_G(p) 0
#define DIST_DPTR_NO_G(p) 0
#define DIST_DPTR_PO_G(p) 0
#define DIST_DPTR_OLB_G(p) F90_DPTR_LBOUND_G(p)
#define DIST_DPTR_OUB_G(p) F90_DPTR_UBOUND_G(p)
#define DIST_DPTR_CLB_G(p) F90_DPTR_LBOUND_G(p)
#define DIST_DPTR_CNO_G(p) 1
#define DIST_DPTR_TAXIS_G(p) 0
#define DIST_DPTR_TSTRIDE_G(p) F90_DPTR_SSTRIDE_G(p)
#define DIST_DPTR_TOFFSET_G(p) F90_DPTR_SOFFSET_G(p)
#define DIST_DPTR_TLB_G(p) F90_DPTR_LBOUND_G(p)
#define DIST_DPTR_TUB_G(p) F90_DPTR_UBOUND_G(p)
#define DIST_DPTR_PAXIS_G(p) 0
#define DIST_DPTR_BLOCK_G(p) 1
#define DIST_DPTR_BLOCK_SHIFT_G(p) 0
#define DIST_DPTR_BLOCK_RECIP_G(p) 0
#define DIST_DPTR_CYCLE_G(p) 1
#define DIST_DPTR_CYCLE_SHIFT_G(p) 0
#define DIST_DPTR_CYCLE_RECIP_G(p) 0
#define DIST_DPTR_PSHAPE_G(p) 1
#define DIST_DPTR_PSHAPE_SHIFT_G(p) 0
#define DIST_DPTR_PSHAPE_RECIP_G(p) 0
#define DIST_DPTR_PCOORD_G(p) 0
#define DIST_DPTR_PSTRIDE_G(p) F90_DPTR_SSTRIDE_G(p)
#define DIST_DPTR_ASTRIDE_G(p) F90_DPTR_SSTRIDE_G(p)
#define DIST_DPTR_AOFFSET_G(p) 0
#define DIST_DPTR_CL_G(p) 0
#define DIST_DPTR_CN_G(p) 1
#define DIST_DPTR_CS_G(p) 0
#define DIST_DPTR_CLOF_G(p) 0
#define DIST_DPTR_CLOS_G(p) 0
#define DIST_DPTR_GEN_BLOCK_G(p) (f90DummyGenBlockPtr)
#define DIST_DPTR_LAB_P(p, v)
#define DIST_DPTR_UAB_P(p, v)
#define DIST_DPTR_LOFFSET_P(p, v)
#define DIST_DPTR_COFSTR_P(p, v)
#define DIST_DPTR_NO_P(p, v)
#define DIST_DPTR_PO_P(p, v)
#define DIST_DPTR_OLB_P(p, v)
#define DIST_DPTR_OUB_P(p, v)
#define DIST_DPTR_CLB_P(p, v)
#define DIST_DPTR_CNO_P(p, v)
#define DIST_DPTR_TAXIS_P(p, v)
#define DIST_DPTR_TSTRIDE_P(p, v)
#define DIST_DPTR_TOFFSET_P(p, v)
#define DIST_DPTR_TLB_P(p, v)
#define DIST_DPTR_TUB_P(p, v)
#define DIST_DPTR_PAXIS_P(p, v)
#define DIST_DPTR_BLOCK_P(p, v)
#define DIST_DPTR_BLOCK_SHIFT_P(p, v)
#define DIST_DPTR_BLOCK_RECIP_P(p, v)
#define DIST_DPTR_CYCLE_P(p, v)
#define DIST_DPTR_CYCLE_SHIFT_P(p, v)
#define DIST_DPTR_CYCLE_RECIP_P(p, v)
#define DIST_DPTR_PSHAPE_P(p, v)
#define DIST_DPTR_PSHAPE_SHIFT_P(p, v)
#define DIST_DPTR_PSHAPE_RECIP_P(p, v)
#define DIST_DPTR_PCOORD_P(p, v)
#define DIST_DPTR_PSTRIDE_P(p, v)
#define DIST_DPTR_ASTRIDE_P(p, v)
#define DIST_DPTR_AOFFSET_P(p, v)
#define DIST_DPTR_CL_P(p, v)
#define DIST_DPTR_CN_P(p, v)
#define DIST_DPTR_CS_P(p, v)
#define DIST_DPTR_CLOF_P(p, v)
#define DIST_DPTR_CLOS_P(p, v)
#define DIST_DPTR_GEN_BLOCK_P(p, v)
#define DIST_DIM_LAB_G(p, i) F90_DIM_LBOUND_G(p, i)
#define DIST_DIM_UAB_G(p, i) F90_DIM_UBOUND_G(p, i)
#define DIST_DIM_LOFFSET_G(p, i) (-(F90_DIM_LSTRIDE_G(p, i)))
#define DIST_DIM_COFSTR_G(p, i) 0
#define DIST_DIM_NO_G(p, i) 0
#define DIST_DIM_PO_G(p, i) 0
#define DIST_DIM_OLB_G(p, i) F90_DIM_LBOUND_G(p, i)
#define DIST_DIM_OUB_G(p, i) F90_DIM_UBOUND_G(p, i)
#define DIST_DIM_CLB_G(p, i) F90_DIM_LBOUND_G(p, i)
#define DIST_DIM_CNO_G(p, i) 1
#define DIST_DIM_TAXIS_G(p, i) 0
#define DIST_DIM_TSTRIDE_G(p, i) F90_DIM_LSTRIDE_G(p, i)
#define DIST_DIM_TOFFSET_G(p, i) F90_DIM_SOFFSET_G(p, i)
#define DIST_DIM_TLB_G(p, i) F90_DIM_LBOUND_G(p, i)
#define DIST_DIM_TUB_G(p, i) F90_DIM_UBOUND_G(p, i)
#define DIST_DIM_PAXIS_G(p, i) 0
#define DIST_DIM_BLOCK_G(p, i) 0
#define DIST_DIM_BLOCK_SHIFT_G(p, i) 0
#define DIST_DIM_BLOCK_RECIP_G(p, i) 0
#define DIST_DIM_CYCLE_G(p, i) 0
#define DIST_DIM_CYCLE_SHIFT_G(p, i) 0
#define DIST_DIM_CYCLE_RECIP_G(p, i) 0
#define DIST_DIM_PSHAPE_G(p, i) 1
#define DIST_DIM_PSHAPE_SHIFT_G(p, i) 0
#define DIST_DIM_PSHAPE_recip_G(p, i) 0
#define DIST_DIM_PCOORD_G(p, i) 0
#define DIST_DIM_PSTRIDE_G(p, i) F90_DIM_SSTRIDE_G(p, i)
#define DIST_DIM_ASTRIDE_G(p, i) F90_DIM_SSTRIDE_G(p, i)
#define DIST_DIM_AOFFSET_G(p, i) 0
#define DIST_DIM_CL_G(p, i) 0
#define DIST_DIM_CN_G(p, i) 1
#define DIST_DIM_CS_G(p, i) 0
#define DIST_DIM_CLOF_G(p, i) 0
#define DIST_DIM_CLOS_G(p, i) 0
#define DIST_DIM_GEN_BLOCK_G(p, i) (f90DummyGenBlockPtr)
#define DIST_DIM_LAB_P(p, i, v)
#define DIST_DIM_UAB_P(p, i, v)
#define DIST_DIM_LOFFSET_P(p, i)
#define DIST_DIM_COFSTR_P(p, i, v)
#define DIST_DIM_NO_P(p, i, v)
#define DIST_DIM_PO_P(p, i, v)
#define DIST_DIM_OLB_P(p, i, v)
#define DIST_DIM_OUB_P(p, i, v)
#define DIST_DIM_CLB_P(p, i, v)
#define DIST_DIM_CNO_P(p, i, v)
#define DIST_DIM_TAXIS_P(p, i, v)
#define DIST_DIM_TSTRIDE_P(p, i, v)
#define DIST_DIM_TOFFSET_P(p, i, v)
#define DIST_DIM_TLB_P(p, i, v)
#define DIST_DIM_TUB_P(p, i, v)
#define DIST_DIM_PAXIS_P(p, i, v)
#define DIST_DIM_BLOCK_P(p, i, v)
#define DIST_DIM_BLOCK_SHIFT_P(p, i, v)
#define DIST_DIM_BLOCK_RECIP_P(p, i, v)
#define DIST_DIM_CYCLE_P(p, i, v)
#define DIST_DIM_CYCLE_SHIFT_P(p, i, v)
#define DIST_DIM_CYCLE_RECIP_P(p, i, v)
#define DIST_DIM_PSHAPE_P(p, i, v)
#define DIST_DIM_PSHAPE_SHIFT_P(p, i, v)
#define DIST_DIM_PSHAPE_recip_P(p, i, v)
#define DIST_DIM_PCOORD_P(p, i, v)
#define DIST_DIM_PSTRIDE_P(p, i, v)
#define DIST_DIM_ASTRIDE_P(p, i, v)
#define DIST_DIM_AOFFSET_P(p, i, v)
#define DIST_DIM_CL_P(p, i, v)
#define DIST_DIM_CN_P(p, i, v)
#define DIST_DIM_CS_P(p, i, v)
#define DIST_DIM_CLOF_P(p, i, v)
#define DIST_DIM_CLOS_P(p, i, v)
#define DIST_DIM_GEN_BLOCK_P(p, i, v)
#define DIST_SCOFF_G(p) 0
#define DIST_HEAPB_G(p) 0
#define DIST_PBASE_G(p) 0
#define DIST_MAPPED_G(p) 0
#define DIST_DFMT_G(p) 0
#define DIST_CACHED_G(p) 0
#define DIST_SINGLE_G(p) 0
#define DIST_REPLICATED_G(p) 0
#define DIST_NONSEQUENCE_G(p) 0
#define DIST_DIST_TARGET_G(p) NULL
#define DIST_ALIGN_TARGET_G(p) (p)
#define DIST_NEXT_ALIGNEE_G(p) (p)
#define DIST_ACTUAL_ARG_G(p) NULL
#define DIST_INFO_G(p, i) 0
#define DIST_SCOFF_P(p, v)
#define DIST_HEAPB_P(p, v)
#define DIST_PBASE_P(p, v)
#define DIST_MAPPED_P(p, v)
#define DIST_DFMT_P(p, v)
#define DIST_CACHED_P(p, v)
#define DIST_SINGLE_P(p, v)
#define DIST_REPLICATED_P(p, v)
#define DIST_NONSEQUENCE_P(p, v)
#define DIST_DIST_TARGET_P(p, v)
#define DIST_ALIGN_TARGET_P(p, v)
#define DIST_NEXT_ALIGNEE_P(p, v)
#define DIST_ACTUAL_ARG_P(p, v)
#define DIST_INFO_P(p, i, v)
#define F90_DIM_NAME(p) p##_f90_dim
#define DIST_DIM_NAME(p) p##_fort_dim
#define DESC_VAR_NM(p) p##_desc_var_
#define DECL_HDR_PTRS(p) F90_Desc *p
#define DECL_HDR_VARS(v)
#define DECL_F90_DIM_PTR(p) F90_DescDim *p##_f90_dim
#define DECL_DIST_DIM_PTR(p) DIST_DescDim *p##_fort_dim
#define DECL_DIM_PTRS(p) DECL_F90_DIM_PTR(p)
#define SET_DIM_PTRS(n, p, i) n##_f90_dim = &((p)->dim[i]);
#define NONSEQ_OVERLAP (1 << MAXDIMS)
#define NONSEQ_SECTION (1)
#define DFMT_COLLAPSED 0
#define DFMT_BLOCK 1
#define DFMT_BLOCK_K 2
#define DFMT_CYCLIC 3
#define DFMT_CYCLIC_K 4
#define DFMT_GEN_BLOCK 5
#define DFMT_INDIRECT 6
#define DFMT__MASK 0xf
#define DFMT__WIDTH 4
#define DFMT(D, DIM) (DIST_DFMT_G(D) >> DFMT__WIDTH * ((DIM)-1) & DFMT__MASK)
#define __DIST_SET_ALLOCATION(d, dim, no, po) F90_FLAGS_P((d), F90_FLAGS_G((d)) & ~__TEMPLATE);
#define __DIST_SET_DISTRIBUTION(d, dim, lbound, ubound, paxis, block)
#define __DIST_INIT_SECTION(d, r, a)
#define __DIST_INIT_DESCRIPTOR(d, rank, kind, len, flags, target)
#define __DIST_SET_SECTIONXX(d, ddim, a, adim, l, u, s, noreindex, gsize)
This macro is used for creating an array section.
#define __DIST_SET_SECTIONX(d, ddim, a, adim, l, u, s, noreindex)
This macro is used for creating an array section.
Typedefs
typedef struct procdim procdim
typedef struct proc proc
typedef struct F90_Desc F90_Desc
typedef struct F90_DescDim F90_DescDim
typedef struct DIST_Desc DIST_Desc
typedef struct DIST_DescDim DIST_DescDim
typedef struct type_desc TYPE_DESC
typedef struct repl_t repl_t
typedef void(* sked_start_fn) (void *schedule, char *rb, char *sb, F90_Desc *rd, F90_Desc *sd)
typedef void(* sked_free_fn) (void *schedule)
typedef struct sked sked
typedef void(* local_reduc_fn) (void *, __INT_T, void *, __INT_T, __LOG_T *, __INT_T, __INT_T *, __INT_T, __INT_T, __INT_T)
typedef void(* local_reduc_back_fn) (void *, __INT_T, void *, __INT_T, __LOG_T *, __INT_T, __INT_T *, __INT_T, __INT_T, __INT_T, __LOG_T)
typedef void(* global_reduc_fn) (__INT_T, void *, void *, void *, void *, __INT_T)
Enumerations
enum _io_intent { __INOUT = 0 , __IN = 1 , __OUT = 2 }
enum _io_spec { __OMITTED = 0 , __PRESCRIPTIVE = 1 , __DESCRIPTIVE = 2 , __TRANSCRIPTIVE = 3 }
enum _set_single_enum { __SINGLE , __SCALAR }
Functions
__INT_T ENTCOMN (0, 0)[]
__STR_T ENTCOMN (0C, 0c)[]
__INT_T ENTCOMN (LOCAL_MODE, local_mode)[]
void __fort_chn_prune (struct chdr *c)
void __fort_entry_arecv (int, long, int)
void __fort_entry_arecv_done (int)
void __fort_entry_asend (int, long, int)
void __fort_entry_asend_done (int)
void __fort_entry_await (int)
void __fort_entry_await_done (int)
void __fort_entry_copy (long)
void __fort_entry_copy_done (void)
void __fort_entry_init (void)
Initialization.
void __fort_entry_recv (int, long)
void __fort_entry_recv_done (int)
void __fort_entry_send (int, long)
void __fort_entry_send_done (int)
void __fort_entry_term (void)
Termination.
void __fort_sethand (void)
int __fort_stat_init (void)
Begin stats.
void __fort_stat_arecv (int cpu, long len, int reqn)
Update start asynch receive message stats.
void __fort_stat_arecv_done (int cpu)
void __fort_stat_asend (int cpu, long len, int reqn)
void __fort_stat_asend_done (int cpu)
void __fort_stat_await (int reqn)
void __fort_stat_await_done (int reqn)
void __fort_stat_copy (long len)
Update start bcopy message stats.
void __fort_stat_copy_done (void)
Update done bcopy message stats.
void __fort_stat_function_entry (int line, int lines, int cline, char *func, char *file, int funcl, int filel)
Function entry
void __fort_stat_function_exit (void)
Function exit
void __fort_stat_line_entry (int line)
Line entry
void __fort_stat_recv (int cpu, long len)
void __fort_stat_recv_done (int cpu)
Update done receive message stats.
void __fort_stat_send (int cpu, long len)
Update start send message stats.
void __fort_stat_send_done (int cpu)
Update done send message stats.
void __fort_stat_term (void)
Print stats (called by all cpus)
int __fort_prof_init (void)
Profile initialization.
void __fort_prof_arecv (int cpu, long len, int reqn)
void __fort_prof_arecv_done (int cpu)
void __fort_prof_asend (int cpu, long len, int reqn)
void __fort_prof_asend_done (int cpu)
void __fort_prof_await (int reqn)
void __fort_prof_await_done (int reqn)
void __fort_prof_copy (long len)
Update start bcopy message stats.
void __fort_prof_copy_done (void)
Update done bcopy message stats.
void __fort_prof_function_entry (int line, int lines, int cline, char *func, char *file, int funcl, int filel)
Function entry
void __fort_prof_function_exit (void)
Function exit
void __fort_prof_line_entry (int line)
Line entry
void __fort_prof_recv (int cpu, long len)
Update start receive message stats.
void __fort_prof_recv_done (int cpu)
Update done receive message stats.
void __fort_prof_send (int cpu, long len)
Update start send message stats.
void __fort_prof_send_done (int cpu)
Update done send message stats.
void __fort_prof_term (void)
Profile termination.
void __fort_procargs (void)
int __fort_trac_init (void)
Initialization.
void __fort_trac_arecv (int cpu, long len, int reqn)
void __fort_trac_arecv_done (int cpu)
void __fort_trac_asend (int cpu, long len, int reqn)
void __fort_trac_asend_done (int cpu)
void __fort_trac_await (int reqn)
void __fort_trac_await_done (int reqn)
void __fort_trac_copy (long len)
Update start bcopy message stats.
void __fort_trac_copy_done (void)
Update done bcopy message stats.
void __fort_trac_function_entry (int line, int lines, int cline, DCHAR(func), DCHAR(file) DCLEN64(funcl) DCLEN64(filel))
void __fort_trac_function_exit (void)
Function exit
void __fort_trac_line_entry (int line)
line entry
void __fort_trac_recv (int cpu, long len)
Update start receive message stats.
void __fort_trac_recv_done (int cpu)
Update done receive message stats.
void __fort_trac_send (int cpu, long len)
Update start send message stats.
void __fort_trac_send_done (int cpu)
Update done send message stats.
void __fort_trac_term (void)
Termination.
void __fort_traceback (void)
void __fort_begpar (int ncpus)
Begin parallel program.
void __fort_endpar (void)
End of parallel program.
void __fort_abortx (void)
Abort the whole mess.
void __fort_setarg (void)
void __fort_set_second (double d)
__INT_T I8() is_nonsequential_section (F90_Desc *d, __INT_T dim)
check if a descriptor is associated with a non-contiguous section.
void *I8() __fort_create_conforming_mask_array (const char *what, char *ab, char *mb, F90_Desc *as, F90_Desc *ms, F90_Desc *new_ms)
void I8() __fort_reverse_array (char *db, char *ab, F90_Desc *dd, F90_Desc *ad)
__INT_T *I8() __fort_new_gen_block (F90_Desc *d, int dim)
void I8() __fort_gen_block_bounds (F90_Desc *d, int dim, __INT_T *the_olb, __INT_T *the_oub, __INT_T pcoord)
int __fort_gcd (int, int)
int __fort_lcm (int, int)
void I8() __fort_init_descriptor (F90_Desc *d, __INT_T rank, dtype kind, __INT_T len, __INT_T flags, void *target)
void I8() __fort_set_distribution (F90_Desc *d, __INT_T dim, __INT_T lbound, __INT_T ubound, __INT_T paxis, __INT_T *block)
void I8() __fort_set_alignment (F90_Desc *d, __INT_T dim, __INT_T lbound, __INT_T ubound, __INT_T taxis, __INT_T tstride, __INT_T toffset,...)
void I8() __fort_set_allocation (F90_Desc *d, __INT_T dim, __INT_T no, __INT_T po)
void I8() __fort_use_allocation (F90_Desc *d, __INT_T dim, __INT_T no, __INT_T po, F90_Desc *a)
void I8() __fort_set_single (F90_Desc *d, F90_Desc *a, __INT_T dim, __INT_T i, _set_single_enum what)
void I8() __fort_finish_descriptor (F90_Desc *d)
void I8() __fort_init_section (F90_Desc *d, __INT_T rank, F90_Desc *a)
void I8() __fort_set_section (F90_Desc *d, __INT_T ddim, F90_Desc *a, __INT_T adim, __INT_T l, __INT_T u, __INT_T s)
void I8() __fort_finish_section (F90_Desc *d)
int compute_lstride (F90_Desc *d, int dim)
void I8() __fort_copy_descriptor (F90_Desc *d, F90_Desc *d0)
F90_Desc *I8() __fort_inherit_template (F90_Desc *d, __INT_T rank, F90_Desc *target)
proc * __fort_defaultproc (int rank)
proc * __fort_localproc (void)
int __fort_myprocnum (void)
int __fort_is_ioproc (void)
int I8() __fort_owner (F90_Desc *d, __INT_T *gidx)
void I8() __fort_localize (F90_Desc *d, __INT_T *idxv, int *cpu, __INT_T *off)
void I8() __fort_describe_replication (F90_Desc *d, repl_t *r)
int I8() __fort_next_owner (F90_Desc *d, repl_t *r, int *pc, int owner)
int I8() __fort_islocal (F90_Desc *d, __INT_T *gidx)
__INT_T I8() __fort_local_offset (F90_Desc *d, __INT_T *gidx)
void *I8() __fort_local_address (void *base, F90_Desc *d, __INT_T *gidx)
void I8() __fort_cycle_bounds (F90_Desc *d)
__INT_T I8() __fort_block_bounds (F90_Desc *d, __INT_T dim, __INT_T ci, __INT_T *bl, __INT_T *bu)
__INT_T I8() __fort_cyclic_loop (F90_Desc *d, __INT_T dim, __INT_T l, __INT_T u, __INT_T s, __INT_T *cl, __INT_T *cu, __INT_T *cs, __INT_T *clof, __INT_T *clos)
int I8() __fort_block_loop (F90_Desc *d, int dim, __INT_T l, __INT_T u, int s, __INT_T ci, __INT_T *bl, __INT_T *bu)
int I8() __fort_stored_alike (F90_Desc *dd, F90_Desc *sd)
int I8() __fort_conform (F90_Desc *s, __INT_T *smap, F90_Desc *t, __INT_T *tmap)
Compare rank and shape of objects s and t. Return true if s and t are conformable under the axis mappings smap and tmap. Scalars are conformable with arrays. conform(A,B) implies conform(B,A).
int I8() __fort_covers_procs (F90_Desc *s, F90_Desc *t)
int I8() __fort_aligned (F90_Desc *t, __INT_T *tmap, F90_Desc *u, __INT_T *umap)
Leftover from HPF Fortran.
int I8() __fort_aligned_axes (F90_Desc *t, int tx, F90_Desc *u, int ux)
Leftover from HPF Fortran.
void __fort_abort (const char *msg)
void __fort_abortp (const char *s)
void __fort_bcopy (char *to, char *fr, size_t n)
void __fort_bcopysl (char *to, char *fr, size_t cnt, size_t tostr, size_t frstr, size_t size)
void I8() __fort_fills (char *ab, F90_Desc *ad, void *fill)
chdr *I8() __fort_copy (void *db, void *sb, F90_Desc *dd, F90_Desc *sd, int *smap)
void I8() __fort_copy_out (void *db, void *sb, F90_Desc *dd, F90_Desc *sd, __INT_T flags)
int __fort_exchange_counts (int *counts)
void I8() __fort_get_scalar (void *temp, void *b, F90_Desc *d, __INT_T *gidx)
void I8() __fort_reduce_section (void *vec1, dtype typ1, int siz1, void *vec2, dtype typ2, int siz2, int cnt, global_reduc_fn fn_g, int dim, F90_Desc *d)
void I8() __fort_replicate_result (void *vec1, dtype typ1, int siz1, void *vec2, dtype typ2, int siz2, int cnt, F90_Desc *d)
sked *I8() __fort_comm_sked (chdr *ch, char *rb, char *sb, dtype kind, int len)
int I8() __fort_ptr_aligned (char *p1, dtype kind, int len, char *p2)
Return nonzero if addresses p1 and p2 are aligned with respect to a multiple of the length of the data type.
char *I8() __fort_ptr_offset (char **pointer, __POINT_T *offset, char *base, dtype kind, __CLEN_T len, char *area)
Compute pointer-sized index offset to replace Cray pointer, return aligned address. offset assumes 1-based arrays.
char *I8() __fort_alloc (__INT_T nelem, dtype kind, size_t len, __STAT_T *stat, char **pointer, __POINT_T *offset, char *base, int check, void *(*mallocfn)(size_t))
allocate space using given 'malloc' function. if present, set pointer and pointer-sized integer offset from base address. offset is in units of the data type length.
char *I8() __fort_allocate (int nelem, dtype kind, size_t len, char *base, char **pointer, __POINT_T *offset)
Allocate global array (must be same size on all processors), return pointer and pointer-sized integer offset from base address. offset is in units of the data type length. don't check allocated status.
int I8() __fort_allocated (char *area)
Is array allocated?
char *I8() __fort_local_allocate (int nelem, dtype kind, size_t len, char *base, char **pointer, __POINT_T *offset)
Allocate local array (may be different size on each processor), return pointer and pointer-sized integer offset from base address. offset is in units of the data type length. don't check allocated status.
char *I8() __fort_dealloc (char *area, __STAT_T *stat, void(*freefn)(void *))
Deallocate array using given 'free' function.
void I8() __fort_deallocate (char *area)
deallocate global array
void I8() __fort_local_deallocate (char *area)
deallocate local array
void * __fort_malloc_without_abort (size_t n)
void * __fort_calloc_without_abort (size_t n)
void * __fort_malloc (size_t n)
void * __fort_realloc (void *ptr, size_t n)
void * __fort_calloc (size_t n, size_t s)
void __fort_free (void *ptr)
void * __fort_gmalloc_without_abort (size_t n)
void * __fort_gcalloc_without_abort (size_t n)
void * __fort_gmalloc (size_t n)
void * __fort_grealloc (void *ptr, size_t n)
void * __fort_gcalloc (size_t n, size_t s)
void __fort_gfree (void *ptr)
void * __fort_gsbrk (int n)
chdr * __fort_chn_1to1 (chdr *fir, int dnd, int dlow, int *dcnt, int *dstr, int snd, int slow, int *scnt, int *sstr)
chdr * __fort_chn_1toN (chdr *fir, int dnd, int dlow, int *dcnt, int *dstr, int snd, int slow, int *scnt, int *sstr)
void __fort_sendl (chdr *c, int indx, void *adr, long cnt, long str, int typ, long ilen)
void __fort_recvl (chdr *c, int indx, void *adr, long cnt, long str, int typ, long ilen)
chdr * __fort_chain_em_up (chdr *list, chdr *c)
void __fort_setbase (chdr *c, char *bases, char *baser, int typ, long ilen)
void __fort_adjbase (chdr *c, char *bases, char *baser, int typ, long ilen)
void __fort_doit (chdr *c)
void __fort_frechn (chdr *c)
void __fort_rsendl (int cpu, void *adr, long cnt, long str, int typ, long ilen)
void __fort_rrecvl (int cpu, void *adr, long cnt, long str, int typ, long ilen)
void __fort_rsend (int cpu, void *adr, long cnt, long str, int typ)
void __fort_rrecv (int cpu, void *adr, long cnt, long str, int typ)
void __fort_rbcstl (int src, void *adr, long cnt, long str, int typ, long ilen)
void __fort_rbcst (int src, void *adr, long cnt, long str, int typ)
void __fort_bcstchn (struct chdr *c, int scpu, int ncpus, int *cpus)
void __fort_exit (int s)
void __fort_tracecall (const char *msg)
int I8() __fort_varying_int (void *b, __INT_T *size)
int I8() __fort_varying_log (void *b, __INT_T *size)
int I8() __fort_fetch_int (void *b, F90_Desc *d)
void I8() __fort_store_int (void *b, F90_Desc *d, int val)
int I8() __fort_fetch_log (void *b, F90_Desc *d)
void I8() __fort_store_log (void *b, F90_Desc *d, int val)
int I8() __fort_fetch_int_element (void *b, F90_Desc *d, int i)
void I8() __fort_store_int_element (void *b, F90_Desc *d, int i, int val)
void I8() __fort_fetch_int_vector (void *b, F90_Desc *d, int *vec, int veclen)
void I8() __fort_store_int_vector (void *b, F90_Desc *d, int *vec, int veclen)
void __fort_ftnstrcpy (char *dst, int len, char *src)
const char * __fort_getopt (const char *opt)
long __fort_getoptn (const char *opt, long def)
int __fort_atol (char *p)
long __fort_strtol (const char *str, char **ptr, int base)
void __fort_initndx (int nd, int *cnts, int *ncnts, int *strs, int *nstrs, int *mults)
int __fort_findndx (int cpu, int nd, int low, int *nstrs, int *mults)
void __fort_barrier (void)
void __fort_par_unlink (char *fn)
void __fort_zopen (char *path)
void __fort_erecv (int cpu, struct ents *e)
void __fort_esend (int cpu, struct ents *e)
void __fort_rstchn (struct chdr *c)
void ENTFTN (INSTANCE, instance)(F90_Desc *dd
void F90_Desc __INT_T __INT_T __INT_T void ENTFTN (TEMPLATE, template)(F90_Desc *dd
void F90_Desc __INT_T __INT_T __INT_T void __INT_T __INT_T void ENTFTN (SECT, sect)(F90_Desc *d
void F90_Desc __INT_T __INT_T __INT_T void __INT_T __INT_T void F90_Desc __LOG_T ENTFTN (ASSOCIATED, associated)(char *pb
void ENTF90 (TEMPLATE, template)(F90_Desc *dd
void __INT_T __INT_T __INT_T __INT_T void ENTF90 (TEMPLATE1, template1)(F90_Desc *dd
void ENTF90 (TEMPLATE2, template2)(F90_Desc *dd
void ENTF90 (TEMPLATE3, template3)(F90_Desc *dd
Variables
__LOG_T __fort_mask_log
__LOG1_T __fort_mask_log1
__LOG2_T __fort_mask_log2
__LOG4_T __fort_mask_log4
__LOG8_T __fort_mask_log8
__INT1_T __fort_mask_int1
__INT2_T __fort_mask_int2
__INT4_T __fort_mask_int4
__INT8_T __fort_mask_int8
__LOG_T __fort_true_log
__LOG1_T __fort_true_log1
__LOG2_T __fort_true_log2
__LOG4_T __fort_true_log4
__LOG8_T __fort_true_log8
void * __fort_maxs [__NTYPES]
void * __fort_mins [__NTYPES]
int __fort_shifts [__NTYPES]
void * __fort_trues [__NTYPES]
const char * __fort_typenames [__NTYPES]
void * __fort_units [__NTYPES]
long long int __fort_one [4]
long long int __fort_zed [4]
const char * __fort_transnam
int __fort_size_of [__NTYPES]
int __fort_entry_mflag
__INT_T CORMEM []
__INT_T f90DummyGenBlock
__INT_T * f90DummyGenBlockPtr
void F90_Desc * td
void F90_Desc __INT_T * p_kind
void F90_Desc __INT_T __INT_T * p_len
void F90_Desc __INT_T __INT_T __INT_T * p_collapse
void F90_Desc __INT_T __INT_T __INT_T void __INT_T * p_rank
void F90_Desc __INT_T __INT_T __INT_T void __INT_T __INT_T * p_flags
void F90_Desc __INT_T __INT_T __INT_T void __INT_T __INT_T void F90_Desc * a
void F90_Desc __INT_T __INT_T __INT_T void __INT_T __INT_T void F90_Desc __LOG_T F90_Desc * pd
void F90_Desc __INT_T __INT_T __INT_T void __INT_T __INT_T void F90_Desc __LOG_T F90_Desc char * tb
void __INT_T __INT_T __INT_T __INT_T void __INT_T __INT_T __INT_T __INT_T * p_l1
void __INT_T __INT_T __INT_T __INT_T void __INT_T __INT_T __INT_T __INT_T __INT_T * p_u1
void __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T * p_l2
void __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T * p_u2
void __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T * p_l3
void __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T * p_u3
Detailed Description
descriptor and other definitions
Definition in file fioMacros.h.
Macro Definition Documentation
__ALIGN_TARGET_MASK
#define __ALIGN_TARGET_MASK 0x3
Definition at line 650 of file fioMacros.h.
__ALIGN_TARGET_SHIFT
#define __ALIGN_TARGET_SHIFT 12
Definition at line 651 of file fioMacros.h.
__ASSUMED_GB_EXTENT
#define __ASSUMED_GB_EXTENT 0x08000000
descriptor flag (reserved)
Definition at line 711 of file fioMacros.h.
__ASSUMED_OVERLAPS
#define __ASSUMED_OVERLAPS 0x00200000
descriptor flag (reserved)
Definition at line 687 of file fioMacros.h.
__ASSUMED_SHAPE
#define __ASSUMED_SHAPE 0x00000004
This descriptor flag is used to indicate that the array is declared assumed shape.
Definition at line 609 of file fioMacros.h.
__ASSUMED_SIZE
#define __ASSUMED_SIZE 0x00000001
This descriptor flag is used to indicate that the array is declared assumed size.
Definition at line 603 of file fioMacros.h.
__BOGUSBOUNDS
#define __BOGUSBOUNDS 0x00800000
When creating an array section, defer set up of the bounds in the descriptor after a copy.
Definition at line 697 of file fioMacros.h.
__CORMEM_M0
#define __CORMEM_M0 666
Definition at line 526 of file fioMacros.h.
__CORMEM_M1
#define __CORMEM_M1 0x58ad5e3
Definition at line 527 of file fioMacros.h.
__CORMEM_M2
#define __CORMEM_M2 0x61f072b
Definition at line 528 of file fioMacros.h.
__CORMEM_SCAN
#define __CORMEM_SCAN ()
Value:
  {                                                                            \
    __INT_T n;                                                                 \
    n = ((__CORMEM_M1 ^ CORMEM[2]) - CORMEM[0]) - __CORMEM_M0;                 \
    if (n != ((__CORMEM_M2 ^ CORMEM[7]) + CORMEM[1]) - __CORMEM_M0)            \
      __fort_abort("Memory corrupted, aborting\n");                             \
    if (NPLIMIT != 0 && (n == 0 || n > NPLIMIT))                               \
      n = NPLIMIT;                                                             \
    if (n != 0 && GET_DIST_TCPUS > n)                                         \
      __fort_abort("Number of processors exceeds license\n");                   \
  }
Definition at line 547 of file fioMacros.h.
__DESCRIPTIVE_ALIGN_TARGET
#define __DESCRIPTIVE_ALIGN_TARGET (__DESCRIPTIVE << __ALIGN_TARGET_SHIFT)
Definition at line 653 of file fioMacros.h.
__DESCRIPTIVE_DIST_FORMAT
#define __DESCRIPTIVE_DIST_FORMAT (__DESCRIPTIVE << __DIST_FORMAT_SHIFT)
Definition at line 647 of file fioMacros.h.
__DESCRIPTIVE_DIST_TARGET
#define __DESCRIPTIVE_DIST_TARGET (__DESCRIPTIVE << __DIST_TARGET_SHIFT)
Definition at line 641 of file fioMacros.h.
__DIST_ENTRY_ARECV
#define __DIST_ENTRY_ARECV (cpu, len, reqn)
Definition at line 204 of file fioMacros.h.
__DIST_ENTRY_ARECV_DONE
#define __DIST_ENTRY_ARECV_DONE (cpu)
Definition at line 205 of file fioMacros.h.
__DIST_ENTRY_ASEND
#define __DIST_ENTRY_ASEND (cpu, len, reqn)
Definition at line 206 of file fioMacros.h.
__DIST_ENTRY_ASEND_DONE
#define __DIST_ENTRY_ASEND_DONE (cpu)
Definition at line 207 of file fioMacros.h.
__DIST_ENTRY_AWAIT
#define __DIST_ENTRY_AWAIT (reqn)
Definition at line 208 of file fioMacros.h.
__DIST_ENTRY_AWAIT_DONE
#define __DIST_ENTRY_AWAIT_DONE (reqn)
Definition at line 209 of file fioMacros.h.
__DIST_ENTRY_COPY
#define __DIST_ENTRY_COPY (len)
Definition at line 201 of file fioMacros.h.
__DIST_ENTRY_COPY_DONE
#define __DIST_ENTRY_COPY_DONE ()
Definition at line 203 of file fioMacros.h.
__DIST_ENTRY_RECV
#define __DIST_ENTRY_RECV (cpu, len)
Definition at line 197 of file fioMacros.h.
__DIST_ENTRY_RECV_DONE
#define __DIST_ENTRY_RECV_DONE (cpu)
Definition at line 198 of file fioMacros.h.
__DIST_ENTRY_SEND
#define __DIST_ENTRY_SEND (cpu, len)
Definition at line 199 of file fioMacros.h.
__DIST_ENTRY_SEND_DONE
#define __DIST_ENTRY_SEND_DONE (cpu)
Definition at line 200 of file fioMacros.h.
__DIST_FORMAT_MASK
#define __DIST_FORMAT_MASK 0x3
Definition at line 644 of file fioMacros.h.
__DIST_FORMAT_SHIFT
#define __DIST_FORMAT_SHIFT 10
Definition at line 645 of file fioMacros.h.
__DIST_INIT_DESCRIPTOR
#define __DIST_INIT_DESCRIPTOR (d, rank, kind, len, flags, target)
Value:
  F90_TAG_P((d), __DESC);                                                      \
  F90_RANK_P((d), rank);                                                       \
  F90_KIND_P((d), kind);                                                       \
  F90_LEN_P((d), len);                                                         \
  F90_FLAGS_P((d), ((flags) | __TEMPLATE |                                     \
                    __SEQUENTIAL_SECTION & ~(__NOT_COPIED | __OFF_TEMPLATE))); \
  F90_GSIZE_P((d), 0);                                                         \
  F90_LSIZE_P((d), 0);                                                         \
  F90_GBASE_P((d), 0);                                                         \
  F90_DIST_DESC_P((d), 0);                                                      \
  F90_LBASE_P((d), 1);
Definition at line 1348 of file fioMacros.h.
__DIST_INIT_SECTION
#define __DIST_INIT_SECTION (d, r, a)
Value:
  F90_TAG_P((d), __DESC);                                                      \
  F90_RANK_P((d), r);                                                          \
  F90_KIND_P((d), F90_KIND_G(a));                                              \
  F90_LEN_P((d), F90_LEN_G(a));                                                \
  F90_FLAGS_P((d), F90_FLAGS_G(a));                                            \
  F90_GSIZE_P((d), F90_GSIZE_G(a));                                            \
  F90_LSIZE_P((d), F90_LSIZE_G(a));                                            \
  F90_GBASE_P((d), F90_GBASE_G(a));                                            \
  F90_LBASE_P((d), F90_LBASE_G(a));                                            \
  F90_DIST_DESC_P((d), F90_DIST_DESC_G(a)); /* TYPE_DESC pointer */
Definition at line 1336 of file fioMacros.h.
__DIST_SET_ALLOCATION
#define __DIST_SET_ALLOCATION (d, dim, no, po) F90_FLAGS_P((d), F90_FLAGS_G((d)) & ~__TEMPLATE);
Definition at line 1322 of file fioMacros.h.
__DIST_SET_DISTRIBUTION
#define __DIST_SET_DISTRIBUTION (d, dim, lbound, ubound, paxis, block)
Value:
  {                                                                            \
    DECL_DIM_PTRS(_dd);                                                        \
    SET_DIM_PTRS(_dd, (d), (dim)-1);                                           \
    F90_DPTR_LBOUND_P(_dd, lbound);                                            \
    DPTR_UBOUND_P(_dd, ubound);                                                \
    F90_DPTR_SSTRIDE_P(_dd, 1);                                                \
    F90_DPTR_SOFFSET_P(_dd, 0);                                                \
    F90_DPTR_LSTRIDE_P(_dd, 0);                                                \
  }
Definition at line 1325 of file fioMacros.h.
__DIST_SET_SECTIONX
#define __DIST_SET_SECTIONX (d, ddim, a, adim, l, u, s, noreindex)
Value:
  {                                                                            \
    DECL_DIM_PTRS(__dd);                                                       \
    DECL_DIM_PTRS(__ad);                                                       \
    __INT_T __extent, __myoffset;                                              \
    SET_DIM_PTRS(__ad, a, adim - 1);                                           \
    SET_DIM_PTRS(__dd, d, ddim - 1);                                           \
    __extent = u - l + s; /* section extent */                                 \
    if (s != 1) {                                                              \
      if (s == -1)                                                             \
        __extent = -__extent;                                                  \
      else                                                                     \
        __extent /= s;                                                         \
    }                                                                          \
    if (__extent < 0)                                                          \
      __extent = 0;                                                            \
    if (noreindex && s == 1) {                                                 \
      F90_DPTR_LBOUND_P(__dd, l);                     /* lower bound */        \
      DPTR_UBOUND_P(__dd, __extent == 0 ? l - 1 : u); /* upper bound */        \
      __myoffset = 0;                                                          \
    } else {                                                                   \
      F90_DPTR_LBOUND_P(__dd, 1);    /* lower bound */                         \
      DPTR_UBOUND_P(__dd, __extent); /* upper bound */                         \
      __myoffset = l - s;                                                      \
    }                                                                          \
    F90_DPTR_SSTRIDE_P(__dd, 1);                                               \
    F90_DPTR_SOFFSET_P(__dd, 0);                                               \
    F90_DPTR_LSTRIDE_P(__dd, F90_DPTR_LSTRIDE_G(__ad) * s);                    \
    F90_LBASE_P(d, F90_LBASE_G(d) + __myoffset * F90_DPTR_LSTRIDE_G(__ad));    \
  }
This macro is used for creating an array section.
This macro is the same as __DIST_SET_SECTIONXX but without the gsize argument.
Definition at line 1409 of file fioMacros.h.
__DIST_SET_SECTIONXX
#define __DIST_SET_SECTIONXX (d, ddim, a, adim, l, u, s, noreindex, gsize)
This macro is used for creating an array section.
Note: We no longer need section stride/section offset.
This macro is the same as __DIST_SET_SECTIONX, except it collects the strides into the LSTRIDE; SSTRIDE and SOFFSET are just copied (left at one, zero)
Definition at line 1370 of file fioMacros.h.
__DIST_TARGET_AXIS
#define __DIST_TARGET_AXIS 0x00100000
descriptor flag (reserved)
Definition at line 683 of file fioMacros.h.
__DIST_TARGET_MASK
#define __DIST_TARGET_MASK 0x3
Definition at line 638 of file fioMacros.h.
__DIST_TARGET_SHIFT
#define __DIST_TARGET_SHIFT 8
Definition at line 639 of file fioMacros.h.
__DUMMY_COLLAPSE_PAXIS
#define __DUMMY_COLLAPSE_PAXIS 0x10000000
descriptor flag (reserved)
Definition at line 715 of file fioMacros.h.
__DYNAMIC
#define __DYNAMIC 0x00008000
descriptor flag (reserved)
Definition at line 662 of file fioMacros.h.
__F77_LOCAL_DUMMY
#define __F77_LOCAL_DUMMY 0x00040000
descriptor flag (reserved)
Definition at line 674 of file fioMacros.h.
__IDENTITY_MAP
#define __IDENTITY_MAP 0x00004000
descriptor flag (reserved)
Definition at line 658 of file fioMacros.h.
__INHERIT
#define __INHERIT 0x00000010
descriptor flag (reserved)
Definition at line 617 of file fioMacros.h.
__INTENT_IN
#define __INTENT_IN (__IN << __INTENT_SHIFT)
Definition at line 628 of file fioMacros.h.
__INTENT_INOUT
#define __INTENT_INOUT (__INOUT << __INTENT_SHIFT)
Definition at line 627 of file fioMacros.h.
__INTENT_MASK
#define __INTENT_MASK 0x3
Definition at line 625 of file fioMacros.h.
__INTENT_OUT
#define __INTENT_OUT (__OUT << __INTENT_SHIFT)
Definition at line 629 of file fioMacros.h.
__INTENT_SHIFT
#define __INTENT_SHIFT 6
Definition at line 626 of file fioMacros.h.
__LOCAL
#define __LOCAL 0x00020000
descriptor flag (reserved)
Definition at line 670 of file fioMacros.h.
__NO_OVERLAPS
#define __NO_OVERLAPS 0x00000020
descriptor flag (reserved)
Definition at line 621 of file fioMacros.h.
__NOREINDEX
#define __NOREINDEX 0x02000000
When creating an array section, use the existing bounds. Do not reset the lower bound to 1 and the upper bound to the extent.
Definition at line 707 of file fioMacros.h.
__NOT_COPIED
#define __NOT_COPIED 0x01000000
descriptor flag (reserved)
Definition at line 701 of file fioMacros.h.
__OFF_TEMPLATE
#define __OFF_TEMPLATE 0x00080000
descriptor flag (reserved)
Definition at line 679 of file fioMacros.h.
__PRESCRIPTIVE_ALIGN_TARGET
#define __PRESCRIPTIVE_ALIGN_TARGET (__PRESCRIPTIVE << __ALIGN_TARGET_SHIFT)
Definition at line 652 of file fioMacros.h.
__PRESCRIPTIVE_DIST_FORMAT
#define __PRESCRIPTIVE_DIST_FORMAT (__PRESCRIPTIVE << __DIST_FORMAT_SHIFT)
Definition at line 646 of file fioMacros.h.
__PRESCRIPTIVE_DIST_TARGET
#define __PRESCRIPTIVE_DIST_TARGET (__PRESCRIPTIVE << __DIST_TARGET_SHIFT)
Definition at line 640 of file fioMacros.h.
__SAVE
#define __SAVE 0x00000008
descriptor flag (reserved)
Definition at line 613 of file fioMacros.h.
__SECTZBASE
#define __SECTZBASE 0x00400000
When creating a section of an array, set up each dimension and compute GSIZE (see ENTF90(SECT, sect) in dist.c).
Definition at line 692 of file fioMacros.h.
__SEQUENCE
#define __SEQUENCE 0x00000002
Definition at line 604 of file fioMacros.h.
__SEQUENTIAL_SECTION
#define __SEQUENTIAL_SECTION 0x20000000
Used to determine if an array section passed as a parameter to an F77 subroutine needs to be copied or whether it can be passed as is. Set in ptr_assign and tested by the inline code.
Definition at line 723 of file fioMacros.h.
__TEMPLATE
#define __TEMPLATE 0x00010000
descriptor flag (reserved)
Definition at line 666 of file fioMacros.h.
__TRANSCRIPTIVE_DIST_FORMAT
#define __TRANSCRIPTIVE_DIST_FORMAT (__TRANSCRIPTIVE << __DIST_FORMAT_SHIFT)
Definition at line 648 of file fioMacros.h.
__TRANSCRIPTIVE_DIST_TARGET
#define __TRANSCRIPTIVE_DIST_TARGET (__TRANSCRIPTIVE << __DIST_TARGET_SHIFT)
Definition at line 642 of file fioMacros.h.
Abs
#define Abs (y) ((y) < 0 ? -(y) : (y))
Definition at line 563 of file fioMacros.h.
ABSENT
#define ABSENT (ENTCOMN(0, 0) + 2)
Definition at line 40 of file fioMacros.h.
ABSENTC
#define ABSENTC ENTCOMN(0C, 0c)
Definition at line 41 of file fioMacros.h.
ALIGNR
#define ALIGNR (x) (((x) + ALIGNZ - 1) & ~(ALIGNZ - 1))
Definition at line 103 of file fioMacros.h.
ALIGNZ
#define ALIGNZ 16
Definition at line 102 of file fioMacros.h.
ALLDIMS
#define ALLDIMS (~(-1 << MAXDIMS))
Definition at line 500 of file fioMacros.h.
Ceil
#define Ceil (x, y) (((x) ^ (y)) > 0 ? (Abs(x) + Abs(y) - 1) / Abs(y) : (x) / (y))
Definition at line 564 of file fioMacros.h.
DEBUG_ALLO
#define DEBUG_ALLO 0x02000
Definition at line 517 of file fioMacros.h.
DEBUG_CHAN
#define DEBUG_CHAN 0x20000
Definition at line 521 of file fioMacros.h.
DEBUG_CHECK
#define DEBUG_CHECK 0x100000
Definition at line 524 of file fioMacros.h.
DEBUG_COPY
#define DEBUG_COPY 0x40000
Definition at line 522 of file fioMacros.h.
DEBUG_COPYIN_GLOBAL
#define DEBUG_COPYIN_GLOBAL 0x00001
Definition at line 504 of file fioMacros.h.
DEBUG_COPYIN_LOCAL
#define DEBUG_COPYIN_LOCAL 0x00002
Definition at line 505 of file fioMacros.h.
DEBUG_CSHF
#define DEBUG_CSHF 0x08000
Definition at line 519 of file fioMacros.h.
DEBUG_DIST
#define DEBUG_DIST 0x80000
Definition at line 523 of file fioMacros.h.
DEBUG_EOSH
#define DEBUG_EOSH 0x10000
Definition at line 520 of file fioMacros.h.
DEBUG_EXCH
#define DEBUG_EXCH 0x00004
Definition at line 506 of file fioMacros.h.
DEBUG_GRAD
#define DEBUG_GRAD 0x00008
Definition at line 507 of file fioMacros.h.
DEBUG_HFIO
#define DEBUG_HFIO 0x01000
Definition at line 516 of file fioMacros.h.
DEBUG_LVAL
#define DEBUG_LVAL 0x00800
Definition at line 515 of file fioMacros.h.
DEBUG_MMUL
#define DEBUG_MMUL 0x00010
Definition at line 508 of file fioMacros.h.
DEBUG_OLAP
#define DEBUG_OLAP 0x00020
Definition at line 509 of file fioMacros.h.
DEBUG_RDST
#define DEBUG_RDST 0x00040
Definition at line 510 of file fioMacros.h.
DEBUG_REDU
#define DEBUG_REDU 0x00080
Definition at line 511 of file fioMacros.h.
DEBUG_SCAL
#define DEBUG_SCAL 0x00100
Definition at line 512 of file fioMacros.h.
DEBUG_SCAN
#define DEBUG_SCAN 0x00200
Definition at line 513 of file fioMacros.h.
DEBUG_SCAT
#define DEBUG_SCAT 0x00400
Definition at line 514 of file fioMacros.h.
DEBUG_TIME
#define DEBUG_TIME 0x04000
Definition at line 518 of file fioMacros.h.
DECL_DIM_PTRS
#define DECL_DIM_PTRS (p) DECL_F90_DIM_PTR(p)
Definition at line 1240 of file fioMacros.h.
DECL_DIST_DIM_PTR
#define DECL_DIST_DIM_PTR (p) DIST_DescDim *p##_fort_dim
Definition at line 1239 of file fioMacros.h.
DECL_F90_DIM_PTR
#define DECL_F90_DIM_PTR (p) F90_DescDim *p##_f90_dim
Definition at line 1238 of file fioMacros.h.
DECL_HDR_PTRS
#define DECL_HDR_PTRS (p) F90_Desc *p
Definition at line 1234 of file fioMacros.h.
DECL_HDR_VARS
#define DECL_HDR_VARS (v)
Value:
  F90_Desc DESC_VAR_NM(v);                                                     \
  F90_Desc *v = &DESC_VAR_NM(v)
Definition at line 1235 of file fioMacros.h.
DESC_VAR_NM
#define DESC_VAR_NM (p) p##_desc_var_
Definition at line 1233 of file fioMacros.h.
DFMT
#define DFMT (D, DIM) (DIST_DFMT_G(D) >> DFMT__WIDTH * ((DIM)-1) & DFMT__MASK)
Definition at line 1259 of file fioMacros.h.
DFMT__MASK
#define DFMT__MASK 0xf
Definition at line 1257 of file fioMacros.h.
DFMT__WIDTH
#define DFMT__WIDTH 4
Definition at line 1258 of file fioMacros.h.
DFMT_BLOCK
#define DFMT_BLOCK 1
Definition at line 1251 of file fioMacros.h.
DFMT_BLOCK_K
#define DFMT_BLOCK_K 2
Definition at line 1252 of file fioMacros.h.
DFMT_COLLAPSED
#define DFMT_COLLAPSED 0
Definition at line 1250 of file fioMacros.h.
DFMT_CYCLIC
#define DFMT_CYCLIC 3
Definition at line 1253 of file fioMacros.h.
DFMT_CYCLIC_K
#define DFMT_CYCLIC_K 4
Definition at line 1254 of file fioMacros.h.
DFMT_GEN_BLOCK
#define DFMT_GEN_BLOCK 5
Definition at line 1255 of file fioMacros.h.
DFMT_INDIRECT
#define DFMT_INDIRECT 6
Definition at line 1256 of file fioMacros.h.
DIM_UBOUND_G
#define DIM_UBOUND_G (p, i) (p->dim[i].extent + p->dim[i].lbound - 1)
Definition at line 1012 of file fioMacros.h.
DIM_UBOUND_P
#define DIM_UBOUND_P (p, i, v) (p->dim[i].extent = (v)-p->dim[i].lbound + 1; p->dim[i].ubound = v;)
Definition at line 1013 of file fioMacros.h.
DIST_ACTUAL_ARG_G
#define DIST_ACTUAL_ARG_G (p) NULL
Definition at line 1213 of file fioMacros.h.
DIST_ACTUAL_ARG_P
#define DIST_ACTUAL_ARG_P (p, v)
Definition at line 1228 of file fioMacros.h.
DIST_ALIGN_TARGET_G
#define DIST_ALIGN_TARGET_G (p) (p)
Definition at line 1211 of file fioMacros.h.
DIST_ALIGN_TARGET_P
#define DIST_ALIGN_TARGET_P (p, v)
Definition at line 1226 of file fioMacros.h.
DIST_CACHED_G
#define DIST_CACHED_G (p) 0
Definition at line 1206 of file fioMacros.h.
DIST_CACHED_P
#define DIST_CACHED_P (p, v)
Definition at line 1221 of file fioMacros.h.
DIST_DESC_DIM_INT_LEN
#define DIST_DESC_DIM_INT_LEN 34
Definition at line 770 of file fioMacros.h.
DIST_DESC_DIM_PTR_LEN
#define DIST_DESC_DIM_PTR_LEN 1
Definition at line 771 of file fioMacros.h.
DIST_DESC_HDR_INT_LEN
#define DIST_DESC_HDR_INT_LEN 16
Definition at line 768 of file fioMacros.h.
DIST_DESC_HDR_PTR_LEN
#define DIST_DESC_HDR_PTR_LEN 4
Definition at line 769 of file fioMacros.h.
DIST_DFMT_G
#define DIST_DFMT_G (p) 0
Definition at line 1205 of file fioMacros.h.
DIST_DFMT_P
#define DIST_DFMT_P (p, v)
Definition at line 1220 of file fioMacros.h.
DIST_DIM_AOFFSET_G
#define DIST_DIM_AOFFSET_G (p, i) 0
Definition at line 1157 of file fioMacros.h.
DIST_DIM_AOFFSET_P
#define DIST_DIM_AOFFSET_P (p, i, v)
Definition at line 1193 of file fioMacros.h.
DIST_DIM_ASTRIDE_G
#define DIST_DIM_ASTRIDE_G (p, i) F90_DIM_SSTRIDE_G(p, i)
Definition at line 1156 of file fioMacros.h.
DIST_DIM_ASTRIDE_P
#define DIST_DIM_ASTRIDE_P (p, i, v)
Definition at line 1192 of file fioMacros.h.
DIST_DIM_BLOCK_G
#define DIST_DIM_BLOCK_G (p, i) 0
Definition at line 1145 of file fioMacros.h.
DIST_DIM_BLOCK_P
#define DIST_DIM_BLOCK_P (p, i, v)
Definition at line 1181 of file fioMacros.h.
DIST_DIM_BLOCK_RECIP_G
#define DIST_DIM_BLOCK_RECIP_G (p, i) 0
Definition at line 1147 of file fioMacros.h.
DIST_DIM_BLOCK_RECIP_P
#define DIST_DIM_BLOCK_RECIP_P (p, i, v)
Definition at line 1183 of file fioMacros.h.
DIST_DIM_BLOCK_SHIFT_G
#define DIST_DIM_BLOCK_SHIFT_G (p, i) 0
Definition at line 1146 of file fioMacros.h.
DIST_DIM_BLOCK_SHIFT_P
#define DIST_DIM_BLOCK_SHIFT_P (p, i, v)
Definition at line 1182 of file fioMacros.h.
DIST_DIM_CL_G
#define DIST_DIM_CL_G (p, i) 0
Definition at line 1158 of file fioMacros.h.
DIST_DIM_CL_P
#define DIST_DIM_CL_P (p, i, v)
Definition at line 1194 of file fioMacros.h.
DIST_DIM_CLB_G
#define DIST_DIM_CLB_G (p, i) F90_DIM_LBOUND_G(p, i)
Definition at line 1137 of file fioMacros.h.
DIST_DIM_CLB_P
#define DIST_DIM_CLB_P (p, i, v)
Definition at line 1173 of file fioMacros.h.
DIST_DIM_CLOF_G
#define DIST_DIM_CLOF_G (p, i) 0
Definition at line 1161 of file fioMacros.h.
DIST_DIM_CLOF_P
#define DIST_DIM_CLOF_P (p, i, v)
Definition at line 1197 of file fioMacros.h.
DIST_DIM_CLOS_G
#define DIST_DIM_CLOS_G (p, i) 0
Definition at line 1162 of file fioMacros.h.
DIST_DIM_CLOS_P
#define DIST_DIM_CLOS_P (p, i, v)
Definition at line 1198 of file fioMacros.h.
DIST_DIM_CN_G
#define DIST_DIM_CN_G (p, i) 1
Definition at line 1159 of file fioMacros.h.
DIST_DIM_CN_P
#define DIST_DIM_CN_P (p, i, v)
Definition at line 1195 of file fioMacros.h.
DIST_DIM_CNO_G
#define DIST_DIM_CNO_G (p, i) 1
Definition at line 1138 of file fioMacros.h.
DIST_DIM_CNO_P
#define DIST_DIM_CNO_P (p, i, v)
Definition at line 1174 of file fioMacros.h.
DIST_DIM_COFSTR_G
#define DIST_DIM_COFSTR_G (p, i) 0
Definition at line 1132 of file fioMacros.h.
DIST_DIM_COFSTR_P
#define DIST_DIM_COFSTR_P (p, i, v)
Definition at line 1168 of file fioMacros.h.
DIST_DIM_CS_G
#define DIST_DIM_CS_G (p, i) 0
Definition at line 1160 of file fioMacros.h.
DIST_DIM_CS_P
#define DIST_DIM_CS_P (p, i, v)
Definition at line 1196 of file fioMacros.h.
DIST_DIM_CYCLE_G
#define DIST_DIM_CYCLE_G (p, i) 0
Definition at line 1148 of file fioMacros.h.
DIST_DIM_CYCLE_P
#define DIST_DIM_CYCLE_P (p, i, v)
Definition at line 1184 of file fioMacros.h.
DIST_DIM_CYCLE_RECIP_G
#define DIST_DIM_CYCLE_RECIP_G (p, i) 0
Definition at line 1150 of file fioMacros.h.
DIST_DIM_CYCLE_RECIP_P
#define DIST_DIM_CYCLE_RECIP_P (p, i, v)
Definition at line 1186 of file fioMacros.h.
DIST_DIM_CYCLE_SHIFT_G
#define DIST_DIM_CYCLE_SHIFT_G (p, i) 0
Definition at line 1149 of file fioMacros.h.
DIST_DIM_CYCLE_SHIFT_P
#define DIST_DIM_CYCLE_SHIFT_P (p, i, v)
Definition at line 1185 of file fioMacros.h.
DIST_DIM_GEN_BLOCK_G
#define DIST_DIM_GEN_BLOCK_G (p, i) (f90DummyGenBlockPtr)
Definition at line 1163 of file fioMacros.h.
DIST_DIM_GEN_BLOCK_P
#define DIST_DIM_GEN_BLOCK_P (p, i, v)
Definition at line 1199 of file fioMacros.h.
DIST_DIM_LAB_G
#define DIST_DIM_LAB_G (p, i) F90_DIM_LBOUND_G(p, i)
Definition at line 1129 of file fioMacros.h.
DIST_DIM_LAB_P
#define DIST_DIM_LAB_P (p, i, v)
Definition at line 1165 of file fioMacros.h.
DIST_DIM_LOFFSET_G
#define DIST_DIM_LOFFSET_G (p, i) (-(F90_DIM_LSTRIDE_G(p, i)))
Definition at line 1131 of file fioMacros.h.
DIST_DIM_LOFFSET_P
#define DIST_DIM_LOFFSET_P (p, i)
Definition at line 1167 of file fioMacros.h.
DIST_DIM_NAME
#define DIST_DIM_NAME (p) p##_fort_dim
Definition at line 1232 of file fioMacros.h.
DIST_DIM_NO_G
#define DIST_DIM_NO_G (p, i) 0
Definition at line 1133 of file fioMacros.h.
DIST_DIM_NO_P
#define DIST_DIM_NO_P (p, i, v)
Definition at line 1169 of file fioMacros.h.
DIST_DIM_OLB_G
#define DIST_DIM_OLB_G (p, i) F90_DIM_LBOUND_G(p, i)
Definition at line 1135 of file fioMacros.h.
DIST_DIM_OLB_P
#define DIST_DIM_OLB_P (p, i, v)
Definition at line 1171 of file fioMacros.h.
DIST_DIM_OUB_G
#define DIST_DIM_OUB_G (p, i) F90_DIM_UBOUND_G(p, i)
Definition at line 1136 of file fioMacros.h.
DIST_DIM_OUB_P
#define DIST_DIM_OUB_P (p, i, v)
Definition at line 1172 of file fioMacros.h.
DIST_DIM_PAXIS_G
#define DIST_DIM_PAXIS_G (p, i) 0
Definition at line 1144 of file fioMacros.h.
DIST_DIM_PAXIS_P
#define DIST_DIM_PAXIS_P (p, i, v)
Definition at line 1180 of file fioMacros.h.
DIST_DIM_PCOORD_G
#define DIST_DIM_PCOORD_G (p, i) 0
Definition at line 1154 of file fioMacros.h.
DIST_DIM_PCOORD_P
#define DIST_DIM_PCOORD_P (p, i, v)
Definition at line 1190 of file fioMacros.h.
DIST_DIM_PO_G
#define DIST_DIM_PO_G (p, i) 0
Definition at line 1134 of file fioMacros.h.
DIST_DIM_PO_P
#define DIST_DIM_PO_P (p, i, v)
Definition at line 1170 of file fioMacros.h.
DIST_DIM_PSHAPE_G
#define DIST_DIM_PSHAPE_G (p, i) 1
Definition at line 1151 of file fioMacros.h.
DIST_DIM_PSHAPE_P
#define DIST_DIM_PSHAPE_P (p, i, v)
Definition at line 1187 of file fioMacros.h.
DIST_DIM_PSHAPE_recip_G
#define DIST_DIM_PSHAPE_recip_G (p, i) 0
Definition at line 1153 of file fioMacros.h.
DIST_DIM_PSHAPE_recip_P
#define DIST_DIM_PSHAPE_recip_P (p, i, v)
Definition at line 1189 of file fioMacros.h.
DIST_DIM_PSHAPE_SHIFT_G
#define DIST_DIM_PSHAPE_SHIFT_G (p, i) 0
Definition at line 1152 of file fioMacros.h.
DIST_DIM_PSHAPE_SHIFT_P
#define DIST_DIM_PSHAPE_SHIFT_P (p, i, v)
Definition at line 1188 of file fioMacros.h.
DIST_DIM_PSTRIDE_G
#define DIST_DIM_PSTRIDE_G (p, i) F90_DIM_SSTRIDE_G(p, i)
Definition at line 1155 of file fioMacros.h.
DIST_DIM_PSTRIDE_P
#define DIST_DIM_PSTRIDE_P (p, i, v)
Definition at line 1191 of file fioMacros.h.
DIST_DIM_TAXIS_G
#define DIST_DIM_TAXIS_G (p, i) 0
Definition at line 1139 of file fioMacros.h.
DIST_DIM_TAXIS_P
#define DIST_DIM_TAXIS_P (p, i, v)
Definition at line 1175 of file fioMacros.h.
DIST_DIM_TLB_G
#define DIST_DIM_TLB_G (p, i) F90_DIM_LBOUND_G(p, i)
Definition at line 1142 of file fioMacros.h.
DIST_DIM_TLB_P
#define DIST_DIM_TLB_P (p, i, v)
Definition at line 1178 of file fioMacros.h.
DIST_DIM_TOFFSET_G
#define DIST_DIM_TOFFSET_G (p, i) F90_DIM_SOFFSET_G(p, i)
Definition at line 1141 of file fioMacros.h.
DIST_DIM_TOFFSET_P
#define DIST_DIM_TOFFSET_P (p, i, v)
Definition at line 1177 of file fioMacros.h.
DIST_DIM_TSTRIDE_G
#define DIST_DIM_TSTRIDE_G (p, i) F90_DIM_LSTRIDE_G(p, i)
Definition at line 1140 of file fioMacros.h.
DIST_DIM_TSTRIDE_P
#define DIST_DIM_TSTRIDE_P (p, i, v)
Definition at line 1176 of file fioMacros.h.
DIST_DIM_TUB_G
#define DIST_DIM_TUB_G (p, i) F90_DIM_UBOUND_G(p, i)
Definition at line 1143 of file fioMacros.h.
DIST_DIM_TUB_P
#define DIST_DIM_TUB_P (p, i, v)
Definition at line 1179 of file fioMacros.h.
DIST_DIM_UAB_G
#define DIST_DIM_UAB_G (p, i) F90_DIM_UBOUND_G(p, i)
Definition at line 1130 of file fioMacros.h.
DIST_DIM_UAB_P
#define DIST_DIM_UAB_P (p, i, v)
Definition at line 1166 of file fioMacros.h.
DIST_DIST_TARGET_G
#define DIST_DIST_TARGET_G (p) NULL
Definition at line 1210 of file fioMacros.h.
DIST_DIST_TARGET_P
#define DIST_DIST_TARGET_P (p, v)
Definition at line 1225 of file fioMacros.h.
DIST_DPTR_AOFFSET_G
#define DIST_DPTR_AOFFSET_G (p) 0
Definition at line 1085 of file fioMacros.h.
DIST_DPTR_AOFFSET_P
#define DIST_DPTR_AOFFSET_P (p, v)
Definition at line 1121 of file fioMacros.h.
DIST_DPTR_ASTRIDE_G
#define DIST_DPTR_ASTRIDE_G (p) F90_DPTR_SSTRIDE_G(p)
Definition at line 1084 of file fioMacros.h.
DIST_DPTR_ASTRIDE_P
#define DIST_DPTR_ASTRIDE_P (p, v)
Definition at line 1120 of file fioMacros.h.
DIST_DPTR_BLOCK_G
#define DIST_DPTR_BLOCK_G (p) 1
Definition at line 1073 of file fioMacros.h.
DIST_DPTR_BLOCK_P
#define DIST_DPTR_BLOCK_P (p, v)
Definition at line 1109 of file fioMacros.h.
DIST_DPTR_BLOCK_RECIP_G
#define DIST_DPTR_BLOCK_RECIP_G (p) 0
Definition at line 1075 of file fioMacros.h.
DIST_DPTR_BLOCK_RECIP_P
#define DIST_DPTR_BLOCK_RECIP_P (p, v)
Definition at line 1111 of file fioMacros.h.
DIST_DPTR_BLOCK_SHIFT_G
#define DIST_DPTR_BLOCK_SHIFT_G (p) 0
Definition at line 1074 of file fioMacros.h.
DIST_DPTR_BLOCK_SHIFT_P
#define DIST_DPTR_BLOCK_SHIFT_P (p, v)
Definition at line 1110 of file fioMacros.h.
DIST_DPTR_CL_G
#define DIST_DPTR_CL_G (p) 0
Definition at line 1086 of file fioMacros.h.
DIST_DPTR_CL_P
#define DIST_DPTR_CL_P (p, v)
Definition at line 1122 of file fioMacros.h.
DIST_DPTR_CLB_G
#define DIST_DPTR_CLB_G (p) F90_DPTR_LBOUND_G(p)
Definition at line 1065 of file fioMacros.h.
DIST_DPTR_CLB_P
#define DIST_DPTR_CLB_P (p, v)
Definition at line 1101 of file fioMacros.h.
DIST_DPTR_CLOF_G
#define DIST_DPTR_CLOF_G (p) 0
Definition at line 1089 of file fioMacros.h.
DIST_DPTR_CLOF_P
#define DIST_DPTR_CLOF_P (p, v)
Definition at line 1125 of file fioMacros.h.
DIST_DPTR_CLOS_G
#define DIST_DPTR_CLOS_G (p) 0
Definition at line 1090 of file fioMacros.h.
DIST_DPTR_CLOS_P
#define DIST_DPTR_CLOS_P (p, v)
Definition at line 1126 of file fioMacros.h.
DIST_DPTR_CN_G
#define DIST_DPTR_CN_G (p) 1
Definition at line 1087 of file fioMacros.h.
DIST_DPTR_CN_P
#define DIST_DPTR_CN_P (p, v)
Definition at line 1123 of file fioMacros.h.
DIST_DPTR_CNO_G
#define DIST_DPTR_CNO_G (p) 1
Definition at line 1066 of file fioMacros.h.
DIST_DPTR_CNO_P
#define DIST_DPTR_CNO_P (p, v)
Definition at line 1102 of file fioMacros.h.
DIST_DPTR_COFSTR_G
#define DIST_DPTR_COFSTR_G (p) 0
Definition at line 1060 of file fioMacros.h.
DIST_DPTR_COFSTR_P
#define DIST_DPTR_COFSTR_P (p, v)
Definition at line 1096 of file fioMacros.h.
DIST_DPTR_CS_G
#define DIST_DPTR_CS_G (p) 0
Definition at line 1088 of file fioMacros.h.
DIST_DPTR_CS_P
#define DIST_DPTR_CS_P (p, v)
Definition at line 1124 of file fioMacros.h.
DIST_DPTR_CYCLE_G
#define DIST_DPTR_CYCLE_G (p) 1
Definition at line 1076 of file fioMacros.h.
DIST_DPTR_CYCLE_P
#define DIST_DPTR_CYCLE_P (p, v)
Definition at line 1112 of file fioMacros.h.
DIST_DPTR_CYCLE_RECIP_G
#define DIST_DPTR_CYCLE_RECIP_G (p) 0
Definition at line 1078 of file fioMacros.h.
DIST_DPTR_CYCLE_RECIP_P
#define DIST_DPTR_CYCLE_RECIP_P (p, v)
Definition at line 1114 of file fioMacros.h.
DIST_DPTR_CYCLE_SHIFT_G
#define DIST_DPTR_CYCLE_SHIFT_G (p) 0
Definition at line 1077 of file fioMacros.h.
DIST_DPTR_CYCLE_SHIFT_P
#define DIST_DPTR_CYCLE_SHIFT_P (p, v)
Definition at line 1113 of file fioMacros.h.
DIST_DPTR_GEN_BLOCK_G
#define DIST_DPTR_GEN_BLOCK_G (p) (f90DummyGenBlockPtr)
Definition at line 1091 of file fioMacros.h.
DIST_DPTR_GEN_BLOCK_P
#define DIST_DPTR_GEN_BLOCK_P (p, v)
Definition at line 1127 of file fioMacros.h.
DIST_DPTR_LAB_G
#define DIST_DPTR_LAB_G (p) F90_DPTR_LBOUND_G(p)
Definition at line 1057 of file fioMacros.h.
DIST_DPTR_LAB_P
#define DIST_DPTR_LAB_P (p, v)
Definition at line 1093 of file fioMacros.h.
DIST_DPTR_LOFFSET_G
#define DIST_DPTR_LOFFSET_G (p) (-(F90_DPTR_LSTRIDE_G(p) * DIST_DPTR_LAB_G(p)))
Definition at line 1059 of file fioMacros.h.
DIST_DPTR_LOFFSET_P
#define DIST_DPTR_LOFFSET_P (p, v)
Definition at line 1095 of file fioMacros.h.
DIST_DPTR_NO_G
#define DIST_DPTR_NO_G (p) 0
Definition at line 1061 of file fioMacros.h.
DIST_DPTR_NO_P
#define DIST_DPTR_NO_P (p, v)
Definition at line 1097 of file fioMacros.h.
DIST_DPTR_OLB_G
#define DIST_DPTR_OLB_G (p) F90_DPTR_LBOUND_G(p)
Definition at line 1063 of file fioMacros.h.
DIST_DPTR_OLB_P
#define DIST_DPTR_OLB_P (p, v)
Definition at line 1099 of file fioMacros.h.
DIST_DPTR_OUB_G
#define DIST_DPTR_OUB_G (p) F90_DPTR_UBOUND_G(p)
Definition at line 1064 of file fioMacros.h.
DIST_DPTR_OUB_P
#define DIST_DPTR_OUB_P (p, v)
Definition at line 1100 of file fioMacros.h.
DIST_DPTR_PAXIS_G
#define DIST_DPTR_PAXIS_G (p) 0
Definition at line 1072 of file fioMacros.h.
DIST_DPTR_PAXIS_P
#define DIST_DPTR_PAXIS_P (p, v)
Definition at line 1108 of file fioMacros.h.
DIST_DPTR_PCOORD_G
#define DIST_DPTR_PCOORD_G (p) 0
Definition at line 1082 of file fioMacros.h.
DIST_DPTR_PCOORD_P
#define DIST_DPTR_PCOORD_P (p, v)
Definition at line 1118 of file fioMacros.h.
DIST_DPTR_PO_G
#define DIST_DPTR_PO_G (p) 0
Definition at line 1062 of file fioMacros.h.
DIST_DPTR_PO_P
#define DIST_DPTR_PO_P (p, v)
Definition at line 1098 of file fioMacros.h.
DIST_DPTR_PSHAPE_G
#define DIST_DPTR_PSHAPE_G (p) 1
Definition at line 1079 of file fioMacros.h.
DIST_DPTR_PSHAPE_P
#define DIST_DPTR_PSHAPE_P (p, v)
Definition at line 1115 of file fioMacros.h.
DIST_DPTR_PSHAPE_RECIP_G
#define DIST_DPTR_PSHAPE_RECIP_G (p) 0
Definition at line 1081 of file fioMacros.h.
DIST_DPTR_PSHAPE_RECIP_P
#define DIST_DPTR_PSHAPE_RECIP_P (p, v)
Definition at line 1117 of file fioMacros.h.
DIST_DPTR_PSHAPE_SHIFT_G
#define DIST_DPTR_PSHAPE_SHIFT_G (p) 0
Definition at line 1080 of file fioMacros.h.
DIST_DPTR_PSHAPE_SHIFT_P
#define DIST_DPTR_PSHAPE_SHIFT_P (p, v)
Definition at line 1116 of file fioMacros.h.
DIST_DPTR_PSTRIDE_G
#define DIST_DPTR_PSTRIDE_G (p) F90_DPTR_SSTRIDE_G(p)
Definition at line 1083 of file fioMacros.h.
DIST_DPTR_PSTRIDE_P
#define DIST_DPTR_PSTRIDE_P (p, v)
Definition at line 1119 of file fioMacros.h.
DIST_DPTR_TAXIS_G
#define DIST_DPTR_TAXIS_G (p) 0
Definition at line 1067 of file fioMacros.h.
DIST_DPTR_TAXIS_P
#define DIST_DPTR_TAXIS_P (p, v)
Definition at line 1103 of file fioMacros.h.
DIST_DPTR_TLB_G
#define DIST_DPTR_TLB_G (p) F90_DPTR_LBOUND_G(p)
Definition at line 1070 of file fioMacros.h.
DIST_DPTR_TLB_P
#define DIST_DPTR_TLB_P (p, v)
Definition at line 1106 of file fioMacros.h.
DIST_DPTR_TOFFSET_G
#define DIST_DPTR_TOFFSET_G (p) F90_DPTR_SOFFSET_G(p)
Definition at line 1069 of file fioMacros.h.
DIST_DPTR_TOFFSET_P
#define DIST_DPTR_TOFFSET_P (p, v)
Definition at line 1105 of file fioMacros.h.
DIST_DPTR_TSTRIDE_G
#define DIST_DPTR_TSTRIDE_G (p) F90_DPTR_SSTRIDE_G(p)
Definition at line 1068 of file fioMacros.h.
DIST_DPTR_TSTRIDE_P
#define DIST_DPTR_TSTRIDE_P (p, v)
Definition at line 1104 of file fioMacros.h.
DIST_DPTR_TUB_G
#define DIST_DPTR_TUB_G (p) F90_DPTR_UBOUND_G(p)
Definition at line 1071 of file fioMacros.h.
DIST_DPTR_TUB_P
#define DIST_DPTR_TUB_P (p, v)
Definition at line 1107 of file fioMacros.h.
DIST_DPTR_UAB_G
#define DIST_DPTR_UAB_G (p) F90_DPTR_UBOUND_G(p)
Definition at line 1058 of file fioMacros.h.
DIST_DPTR_UAB_P
#define DIST_DPTR_UAB_P (p, v)
Definition at line 1094 of file fioMacros.h.
DIST_HEAPB_G
#define DIST_HEAPB_G (p) 0
Definition at line 1202 of file fioMacros.h.
DIST_HEAPB_P
#define DIST_HEAPB_P (p, v)
Definition at line 1217 of file fioMacros.h.
DIST_INFO_G
#define DIST_INFO_G (p, i) 0
Definition at line 1214 of file fioMacros.h.
DIST_INFO_P
#define DIST_INFO_P (p, i, v)
Definition at line 1229 of file fioMacros.h.
DIST_MAPPED_G
#define DIST_MAPPED_G (p) 0
Definition at line 1204 of file fioMacros.h.
DIST_MAPPED_P
#define DIST_MAPPED_P (p, v)
Definition at line 1219 of file fioMacros.h.
DIST_NEXT_ALIGNEE_G
#define DIST_NEXT_ALIGNEE_G (p) (p)
Definition at line 1212 of file fioMacros.h.
DIST_NEXT_ALIGNEE_P
#define DIST_NEXT_ALIGNEE_P (p, v)
Definition at line 1227 of file fioMacros.h.
DIST_NONSEQUENCE_G
#define DIST_NONSEQUENCE_G (p) 0
Definition at line 1209 of file fioMacros.h.
DIST_NONSEQUENCE_P
#define DIST_NONSEQUENCE_P (p, v)
Definition at line 1224 of file fioMacros.h.
DIST_PBASE_G
#define DIST_PBASE_G (p) 0
Definition at line 1203 of file fioMacros.h.
DIST_PBASE_P
#define DIST_PBASE_P (p, v)
Definition at line 1218 of file fioMacros.h.
DIST_REPLICATED_G
#define DIST_REPLICATED_G (p) 0
Definition at line 1208 of file fioMacros.h.
DIST_REPLICATED_P
#define DIST_REPLICATED_P (p, v)
Definition at line 1223 of file fioMacros.h.
DIST_SCOFF_G
#define DIST_SCOFF_G (p) 0
Definition at line 1201 of file fioMacros.h.
DIST_SCOFF_P
#define DIST_SCOFF_P (p, v)
Definition at line 1216 of file fioMacros.h.
DIST_SINGLE_G
#define DIST_SINGLE_G (p) 0
Definition at line 1207 of file fioMacros.h.
DIST_SINGLE_P
#define DIST_SINGLE_P (p, v)
Definition at line 1222 of file fioMacros.h.
DPTR_UBOUND_G
#define DPTR_UBOUND_G (p) (p##_f90_dim->extent + p##_f90_dim->lbound - 1)
Definition at line 1007 of file fioMacros.h.
DPTR_UBOUND_P
#define DPTR_UBOUND_P (p, v)
Value:
  (p##_f90_dim->extent = (v)-p##_f90_dim->lbound + 1);                         \
  (p##_f90_dim->ubound = v)
Definition at line 1008 of file fioMacros.h.
EXTENSION_BLOCK_MASK
#define EXTENSION_BLOCK_MASK 0xFFFFF80
Definition at line 98 of file fioMacros.h.
F90_DESC_DIM_INT_LEN
#define F90_DESC_DIM_INT_LEN 6
Definition at line 765 of file fioMacros.h.
F90_DESC_DIM_PTR_LEN
#define F90_DESC_DIM_PTR_LEN 0
Definition at line 766 of file fioMacros.h.
F90_DESC_HDR_INT_LEN
#define F90_DESC_HDR_INT_LEN 8
Definition at line 763 of file fioMacros.h.
F90_DESC_HDR_PTR_LEN
#define F90_DESC_HDR_PTR_LEN 2
Definition at line 764 of file fioMacros.h.
F90_DIM_EXTENT_G
#define F90_DIM_EXTENT_G (p, i) (p->dim[i].extent)
Definition at line 994 of file fioMacros.h.
F90_DIM_EXTENT_P
#define F90_DIM_EXTENT_P (p, i, v) (p->dim[i].extent = v)
Definition at line 1002 of file fioMacros.h.
F90_DIM_LBOUND_G
#define F90_DIM_LBOUND_G (p, i) (p->dim[i].lbound)
Definition at line 993 of file fioMacros.h.
F90_DIM_LBOUND_P
#define F90_DIM_LBOUND_P (p, i, v) (p->dim[i].lbound = v)
Definition at line 1001 of file fioMacros.h.
F90_DIM_LSTRIDE_G
#define F90_DIM_LSTRIDE_G (p, i) (p->dim[i].lstride)
Definition at line 998 of file fioMacros.h.
F90_DIM_LSTRIDE_P
#define F90_DIM_LSTRIDE_P (p, i, v) (p->dim[i].lstride = v)
Definition at line 1005 of file fioMacros.h.
F90_DIM_NAME
#define F90_DIM_NAME (p) p##_f90_dim
Definition at line 1231 of file fioMacros.h.
F90_DIM_SOFFSET_G
#define F90_DIM_SOFFSET_G (p, i) 0
Definition at line 997 of file fioMacros.h.
F90_DIM_SOFFSET_P
#define F90_DIM_SOFFSET_P (p, i, v) (p->dim[i].soffset = v)
Definition at line 1004 of file fioMacros.h.
F90_DIM_SSTRIDE_G
#define F90_DIM_SSTRIDE_G (p, i) 1
Definition at line 996 of file fioMacros.h.
F90_DIM_SSTRIDE_P
#define F90_DIM_SSTRIDE_P (p, i, v) (p->dim[i].sstride = v)
Definition at line 1003 of file fioMacros.h.
F90_DIM_UBOUND_G
#define F90_DIM_UBOUND_G (p, i) (p->dim[i].extent + p->dim[i].lbound - 1)
Definition at line 999 of file fioMacros.h.
F90_DIST_DESC_G
#define F90_DIST_DESC_G (p) ((p)->dist_desc)
Definition at line 1025 of file fioMacros.h.
F90_DIST_DESC_P
#define F90_DIST_DESC_P (p, v) ((p)->dist_desc = (v))
Definition at line 1041 of file fioMacros.h.
F90_DPTR_EXTENT_G
#define F90_DPTR_EXTENT_G (p) (p##_f90_dim->extent)
Definition at line 980 of file fioMacros.h.
F90_DPTR_EXTENT_P
#define F90_DPTR_EXTENT_P (p, v) (p##_f90_dim->extent = v)
Definition at line 988 of file fioMacros.h.
F90_DPTR_LBOUND_G
#define F90_DPTR_LBOUND_G (p) (p##_f90_dim->lbound)
Definition at line 979 of file fioMacros.h.
F90_DPTR_LBOUND_P
#define F90_DPTR_LBOUND_P (p, v) (p##_f90_dim->lbound = v)
Definition at line 987 of file fioMacros.h.
F90_DPTR_LSTRIDE_G
#define F90_DPTR_LSTRIDE_G (p) (p##_f90_dim->lstride)
Definition at line 984 of file fioMacros.h.
F90_DPTR_LSTRIDE_P
#define F90_DPTR_LSTRIDE_P (p, v) (p##_f90_dim->lstride = v)
Definition at line 991 of file fioMacros.h.
F90_DPTR_SOFFSET_G
#define F90_DPTR_SOFFSET_G (p) 0
Definition at line 983 of file fioMacros.h.
F90_DPTR_SOFFSET_P
#define F90_DPTR_SOFFSET_P (p, v) (p##_f90_dim->soffset = v)
Definition at line 990 of file fioMacros.h.
F90_DPTR_SSTRIDE_G
#define F90_DPTR_SSTRIDE_G (p) 1
Definition at line 982 of file fioMacros.h.
F90_DPTR_SSTRIDE_P
#define F90_DPTR_SSTRIDE_P (p, v) (p##_f90_dim->sstride = v)
Definition at line 989 of file fioMacros.h.
F90_DPTR_UBOUND_G
#define F90_DPTR_UBOUND_G (p) (p##_f90_dim->extent + p##_f90_dim->lbound - 1)
Definition at line 985 of file fioMacros.h.
F90_FLAGS_G
#define F90_FLAGS_G (p) ((p)->flags)
Definition at line 1020 of file fioMacros.h.
F90_FLAGS_P
#define F90_FLAGS_P (p, v) ((p)->flags = (v))
Definition at line 1036 of file fioMacros.h.
F90_GBASE_G
#define F90_GBASE_G (p) ((p)->gbase)
Definition at line 1024 of file fioMacros.h.
F90_GBASE_P
#define F90_GBASE_P (p, v) ((p)->gbase = (v))
Definition at line 1040 of file fioMacros.h.
F90_GSIZE_G
#define F90_GSIZE_G (p) ((p)->gsize)
Definition at line 1022 of file fioMacros.h.
F90_GSIZE_P
#define F90_GSIZE_P (p, v) ((p)->gsize = (v))
Definition at line 1038 of file fioMacros.h.
F90_KIND_G
#define F90_KIND_G (p) ((p)->kind)
Definition at line 1018 of file fioMacros.h.
F90_KIND_P
#define F90_KIND_P (p, v) ((p)->kind = (v))
Definition at line 1029 of file fioMacros.h.
F90_LBASE_G
#define F90_LBASE_G (p) ((p)->lbase)
Definition at line 1023 of file fioMacros.h.
F90_LBASE_P
#define F90_LBASE_P (p, v) ((p)->lbase = (v))
Definition at line 1039 of file fioMacros.h.
F90_LEN_G
#define F90_LEN_G (p) ((p)->len)
Definition at line 1019 of file fioMacros.h.
F90_LEN_P
#define F90_LEN_P (p, v) ((p)->len = ((__INT_T)v))
Definition at line 1035 of file fioMacros.h.
F90_LSIZE_G
#define F90_LSIZE_G (p) ((p)->lsize)
Definition at line 1021 of file fioMacros.h.
F90_LSIZE_P
#define F90_LSIZE_P (p, v) ((p)->lsize = (v))
Definition at line 1037 of file fioMacros.h.
F90_RANK_G
#define F90_RANK_G (p) ((p)->rank)
Definition at line 1017 of file fioMacros.h.
F90_RANK_P
#define F90_RANK_P (p, v) ((p)->rank = (v))
Definition at line 1028 of file fioMacros.h.
F90_TAG_G
#define F90_TAG_G (p) (*(int *)&(p->tag))
Definition at line 1016 of file fioMacros.h.
F90_TAG_P
#define F90_TAG_P (p, v) ((p)->tag = (v))
Definition at line 1027 of file fioMacros.h.
Floor
#define Floor (x, y) (((x) ^ (y)) < 0 ? -(Abs(x) + Abs(y) - 1) / Abs(y) : (x) / (y))
Definition at line 566 of file fioMacros.h.
GET_DIST_DEBUG
#define GET_DIST_DEBUG __fort_debug
Definition at line 454 of file fioMacros.h.
GET_DIST_DEBUGN
#define GET_DIST_DEBUGN __fort_debugn
Definition at line 455 of file fioMacros.h.
GET_DIST_HEAPZ
#define GET_DIST_HEAPZ 0
Definition at line 449 of file fioMacros.h.
GET_DIST_IOPROC
#define GET_DIST_IOPROC 0
Definition at line 450 of file fioMacros.h.
GET_DIST_LCPU
#define GET_DIST_LCPU 0
Definition at line 451 of file fioMacros.h.
GET_DIST_LCPU_ADDR
#define GET_DIST_LCPU_ADDR &__fort_lcpu
Definition at line 456 of file fioMacros.h.
GET_DIST_MASK_INT1
#define GET_DIST_MASK_INT1 __fort_mask_int1
Definition at line 391 of file fioMacros.h.
GET_DIST_MASK_INT2
#define GET_DIST_MASK_INT2 __fort_mask_int2
Definition at line 392 of file fioMacros.h.
GET_DIST_MASK_INT4
#define GET_DIST_MASK_INT4 __fort_mask_int4
Definition at line 393 of file fioMacros.h.
GET_DIST_MASK_INT8
#define GET_DIST_MASK_INT8 __fort_mask_int8
Definition at line 394 of file fioMacros.h.
GET_DIST_MASK_LOG
#define GET_DIST_MASK_LOG __fort_mask_log
Definition at line 386 of file fioMacros.h.
GET_DIST_MASK_LOG1
#define GET_DIST_MASK_LOG1 __fort_mask_log1
Definition at line 387 of file fioMacros.h.
GET_DIST_MASK_LOG2
#define GET_DIST_MASK_LOG2 __fort_mask_log2
Definition at line 388 of file fioMacros.h.
GET_DIST_MASK_LOG4
#define GET_DIST_MASK_LOG4 __fort_mask_log4
Definition at line 389 of file fioMacros.h.
GET_DIST_MASK_LOG8
#define GET_DIST_MASK_LOG8 __fort_mask_log8
Definition at line 390 of file fioMacros.h.
GET_DIST_MAXS
#define GET_DIST_MAXS (idx) __fort_maxs[idx]
Definition at line 424 of file fioMacros.h.
GET_DIST_MINS
#define GET_DIST_MINS (idx) __fort_mins[idx]
Definition at line 425 of file fioMacros.h.
GET_DIST_ONE
#define GET_DIST_ONE __fort_one
Definition at line 443 of file fioMacros.h.
GET_DIST_PARIO
#define GET_DIST_PARIO __fort_pario
Definition at line 457 of file fioMacros.h.
GET_DIST_QUIET
#define GET_DIST_QUIET __fort_quiet
Definition at line 458 of file fioMacros.h.
GET_DIST_SHIFTS
#define GET_DIST_SHIFTS (idx) __fort_shifts[idx]
Definition at line 426 of file fioMacros.h.
GET_DIST_SIZE_OF
#define GET_DIST_SIZE_OF (idx) __fort_size_of[idx]
Definition at line 427 of file fioMacros.h.
GET_DIST_TCPUS
#define GET_DIST_TCPUS 1
Definition at line 452 of file fioMacros.h.
GET_DIST_TCPUS_ADDR
#define GET_DIST_TCPUS_ADDR &__fort_tcpus
Definition at line 459 of file fioMacros.h.
GET_DIST_TIDS
#define GET_DIST_TIDS __fort_tids
Definition at line 460 of file fioMacros.h.
GET_DIST_TIDS_ELEM
#define GET_DIST_TIDS_ELEM (idx) __fort_tids[idx]
Definition at line 461 of file fioMacros.h.
GET_DIST_TRANSNAM
#define GET_DIST_TRANSNAM "rpm1"
Definition at line 453 of file fioMacros.h.
GET_DIST_TRUE_LOG
#define GET_DIST_TRUE_LOG __fort_true_log
Definition at line 395 of file fioMacros.h.
GET_DIST_TRUE_LOG1
#define GET_DIST_TRUE_LOG1 __fort_true_log1
Definition at line 397 of file fioMacros.h.
GET_DIST_TRUE_LOG2
#define GET_DIST_TRUE_LOG2 __fort_true_log2
Definition at line 398 of file fioMacros.h.
GET_DIST_TRUE_LOG4
#define GET_DIST_TRUE_LOG4 __fort_true_log4
Definition at line 399 of file fioMacros.h.
GET_DIST_TRUE_LOG8
#define GET_DIST_TRUE_LOG8 __fort_true_log8
Definition at line 400 of file fioMacros.h.
GET_DIST_TRUE_LOG_ADDR
#define GET_DIST_TRUE_LOG_ADDR &__fort_true_log
Definition at line 396 of file fioMacros.h.
GET_DIST_TRUES
#define GET_DIST_TRUES (idx) __fort_trues[idx]
Definition at line 428 of file fioMacros.h.
GET_DIST_TYPENAMES
#define GET_DIST_TYPENAMES (idx) __fort_typenames[idx]
Definition at line 429 of file fioMacros.h.
GET_DIST_UNITS
#define GET_DIST_UNITS (idx) __fort_units[idx]
Definition at line 430 of file fioMacros.h.
GET_DIST_ZED
#define GET_DIST_ZED __fort_zed
Definition at line 444 of file fioMacros.h.
ISPRESENT
#define ISPRESENT (p)
Value:
  ((p) &&                                                                      \
   ((__INT_T *)(p) < ENTCOMN(0, 0) || (__INT_T *)(p) > (ENTCOMN(0, 0) + 3)))
Definition at line 50 of file fioMacros.h.
ISPRESENTC
#define ISPRESENTC (p) ((CADR(p)) && (CADR(p) != ABSENTC))
Definition at line 55 of file fioMacros.h.
ISSCALAR
#define ISSCALAR (p) (F90_TAG_G(p) > 0 && F90_TAG_G(p) != __DESC)
Definition at line 61 of file fioMacros.h.
ISSEQUENCE
#define ISSEQUENCE (p) (F90_TAG_G(p) < 0 && F90_TAG_G(p) != -__DESC)
Definition at line 59 of file fioMacros.h.
Max
#define Max (x, y) ((x) > (y) ? (x) : (y))
Definition at line 569 of file fioMacros.h.
MAXDIMS
#define MAXDIMS 7
Definition at line 496 of file fioMacros.h.
Min
#define Min (x, y) ((x) < (y) ? (x) : (y))
Definition at line 568 of file fioMacros.h.
NONSEQ_OVERLAP
#define NONSEQ_OVERLAP (1 << MAXDIMS)
Definition at line 1246 of file fioMacros.h.
NONSEQ_SECTION
#define NONSEQ_SECTION (1)
Definition at line 1247 of file fioMacros.h.
NPLIMIT
#define NPLIMIT 0
Definition at line 541 of file fioMacros.h.
PROC_DIM_INT_LEN
#define PROC_DIM_INT_LEN 5
Definition at line 731 of file fioMacros.h.
PROC_HDR_INT_LEN
#define PROC_HDR_INT_LEN 5
Definition at line 730 of file fioMacros.h.
Q_CPU
#define Q_CPU 0x01 /* cpu */
Definition at line 482 of file fioMacros.h.
Q_CPUS
#define Q_CPUS 0x02 /* cpus */
Definition at line 483 of file fioMacros.h.
Q_MEM
#define Q_MEM 0x10 /* memory */
Definition at line 486 of file fioMacros.h.
Q_MEMS
#define Q_MEMS 0x20 /* memories */
Definition at line 487 of file fioMacros.h.
Q_MSG
#define Q_MSG 0x04 /* message */
Definition at line 484 of file fioMacros.h.
Q_MSGS
#define Q_MSGS 0x08 /* messages */
Definition at line 485 of file fioMacros.h.
Q_PROF
#define Q_PROF 0x40 /* profile output (not used) */
Definition at line 488 of file fioMacros.h.
Q_PROF_AVG
#define Q_PROF_AVG 0x00400000 /* output min/avg/max for profile */
Definition at line 491 of file fioMacros.h.
Q_PROF_NONE
#define Q_PROF_NONE 0x00800000 /* disable profiling */
Definition at line 492 of file fioMacros.h.
Q_TRAC
#define Q_TRAC 0x80 /* trace output (not used) */
Definition at line 489 of file fioMacros.h.
RECIP
#define RECIP (y) (1UL + ((unsigned long)0xFFFFFFFF) / ((unsigned long)(y)))
Definition at line 576 of file fioMacros.h.
RECIP_DIV
#define RECIP_DIV (q, x, y)
Value:
  {                                                                            \
    *(q) = ((y) == 1 ? (x) : (x) / (y));                                       \
  }
Definition at line 578 of file fioMacros.h.
RECIP_DIVMOD
#define RECIP_DIVMOD (q, r, x, y)
Value:
  {                                                                            \
    if ((y) == 1)                                                              \
      *(q) = (x), *(r) = 0;                                                    \
    else {                                                                     \
      register long _p_ = (x) / (y);                                           \
      register long _m_ = (x)-_p_ * (y);                                       \
      *(q) = _p_, *(r) = _m_;                                                  \
    }                                                                          \
  }
Definition at line 586 of file fioMacros.h.
RECIP_FRACBITS
#define RECIP_FRACBITS 32
Definition at line 575 of file fioMacros.h.
RECIP_MOD
#define RECIP_MOD (r, x, y)
Value:
  {                                                                            \
    *(r) = ((y) == 1 ? 0 : (x) % (y));                                         \
  }
Definition at line 582 of file fioMacros.h.
SET_DIM_PTRS
#define SET_DIM_PTRS (n, p, i) n##_f90_dim = &((p)->dim[i]);
Definition at line 1243 of file fioMacros.h.
SET_DIST_DEBUG
#define SET_DIST_DEBUG (n) __fort_debug = n
Definition at line 463 of file fioMacros.h.
SET_DIST_DEBUGN
#define SET_DIST_DEBUGN (n) __fort_debugn = n
Definition at line 464 of file fioMacros.h.
SET_DIST_HEAPZ
#define SET_DIST_HEAPZ (n) __fort_heapz = n
Definition at line 465 of file fioMacros.h.
SET_DIST_IOPROC
#define SET_DIST_IOPROC (n) __fort_ioproc = n
Definition at line 466 of file fioMacros.h.
SET_DIST_LCPU
#define SET_DIST_LCPU (n) __fort_lcpu = n
Definition at line 467 of file fioMacros.h.
SET_DIST_MASK_INT1
#define SET_DIST_MASK_INT1 (n) __fort_mask_int1 = n
Definition at line 407 of file fioMacros.h.
SET_DIST_MASK_INT2
#define SET_DIST_MASK_INT2 (n) __fort_mask_int2 = n
Definition at line 408 of file fioMacros.h.
SET_DIST_MASK_INT4
#define SET_DIST_MASK_INT4 (n) __fort_mask_int4 = n
Definition at line 409 of file fioMacros.h.
SET_DIST_MASK_INT8
#define SET_DIST_MASK_INT8 (n) __fort_mask_int8 = n
Definition at line 410 of file fioMacros.h.
SET_DIST_MASK_LOG
#define SET_DIST_MASK_LOG (n) __fort_mask_log = n
Definition at line 402 of file fioMacros.h.
SET_DIST_MASK_LOG1
#define SET_DIST_MASK_LOG1 (n) __fort_mask_log1 = n
Definition at line 403 of file fioMacros.h.
SET_DIST_MASK_LOG2
#define SET_DIST_MASK_LOG2 (n) __fort_mask_log2 = n
Definition at line 404 of file fioMacros.h.
SET_DIST_MASK_LOG4
#define SET_DIST_MASK_LOG4 (n) __fort_mask_log4 = n
Definition at line 405 of file fioMacros.h.
SET_DIST_MASK_LOG8
#define SET_DIST_MASK_LOG8 (n) __fort_mask_log8 = n
Definition at line 406 of file fioMacros.h.
SET_DIST_MAXS
#define SET_DIST_MAXS (idx, val) __fort_maxs[idx] = val
Definition at line 432 of file fioMacros.h.
SET_DIST_MINS
#define SET_DIST_MINS (idx, val) __fort_mins[idx] = val
Definition at line 433 of file fioMacros.h.
SET_DIST_PARIO
#define SET_DIST_PARIO (n) __fort_pario = n
Definition at line 468 of file fioMacros.h.
SET_DIST_QUIET
#define SET_DIST_QUIET (n) __fort_quiet = n
Definition at line 469 of file fioMacros.h.
SET_DIST_SHIFTS
#define SET_DIST_SHIFTS (idx, val) __fort_shifts[idx] = val
Definition at line 434 of file fioMacros.h.
SET_DIST_SIZE_OF
#define SET_DIST_SIZE_OF (idx, val) __fort_size_of[idx] = val
Definition at line 435 of file fioMacros.h.
SET_DIST_TCPUS
#define SET_DIST_TCPUS (n) __fort_tcpus = n
Definition at line 470 of file fioMacros.h.
SET_DIST_TIDS
#define SET_DIST_TIDS (n) __fort_tids = n
Definition at line 471 of file fioMacros.h.
SET_DIST_TIDS_ELEM
#define SET_DIST_TIDS_ELEM (idx, val) __fort_tids[idx] = val
Definition at line 472 of file fioMacros.h.
SET_DIST_TRUE_LOG
#define SET_DIST_TRUE_LOG (n) __fort_true_log = n
Definition at line 411 of file fioMacros.h.
SET_DIST_TRUE_LOG1
#define SET_DIST_TRUE_LOG1 (n) __fort_true_log1 = n
Definition at line 412 of file fioMacros.h.
SET_DIST_TRUE_LOG2
#define SET_DIST_TRUE_LOG2 (n) __fort_true_log2 = n
Definition at line 413 of file fioMacros.h.
SET_DIST_TRUE_LOG4
#define SET_DIST_TRUE_LOG4 (n) __fort_true_log4 = n
Definition at line 414 of file fioMacros.h.
SET_DIST_TRUE_LOG8
#define SET_DIST_TRUE_LOG8 (n) __fort_true_log8 = n
Definition at line 415 of file fioMacros.h.
SET_DIST_TRUES
#define SET_DIST_TRUES (idx, val) __fort_trues[idx] = val
Definition at line 436 of file fioMacros.h.
SET_DIST_TYPENAMES
#define SET_DIST_TYPENAMES (idx, val) __fort_typenames[idx] = val
Definition at line 437 of file fioMacros.h.
SET_DIST_UNITS
#define SET_DIST_UNITS (idx, val) __fort_units[idx] = val
Definition at line 438 of file fioMacros.h.
SET_F90_DIST_DESC_PTR
#define SET_F90_DIST_DESC_PTR (p, r) /*(p->dist_desc = NULL)*/
Definition at line 1052 of file fioMacros.h.
SET_F90_VAR_DIST_DESC_PTR
#define SET_F90_VAR_DIST_DESC_PTR (f, h) /*(f.dist_desc = NULL)*/
Definition at line 1050 of file fioMacros.h.
Sign
#define Sign (y) ((y) < 0 ? -1 : 1)
Definition at line 562 of file fioMacros.h.
SIZE_OF_RANK_n_ARRAY_DESC
#define SIZE_OF_RANK_n_ARRAY_DESC (n) (sizeof(F90_Desc) - (MAXDIMS - n) * sizeof(F90_DescDim))
Definition at line 1054 of file fioMacros.h.
TYPEKIND
#define TYPEKIND (p)
Value:
  ((dtype)(F90_TAG_G(p) == __DESC                                              \
               ? (p)->kind                                                     \
               : (F90_TAG_G(p) < 0 ? -F90_TAG_G(p) : F90_TAG_G(p))))
Definition at line 63 of file fioMacros.h.
Typedef Documentation
DIST_Desc
typedef struct DIST_Desc DIST_Desc
Definition at line 775 of file fioMacros.h.
DIST_DescDim
typedef struct DIST_DescDim DIST_DescDim
Definition at line 776 of file fioMacros.h.
F90_Desc
typedef struct F90_Desc F90_Desc
Definition at line 773 of file fioMacros.h.
F90_DescDim
typedef struct F90_DescDim F90_DescDim
Definition at line 774 of file fioMacros.h.
global_reduc_fn
typedef void(* global_reduc_fn) (__INT_T, void *, void *, void *, void *, __INT_T)
Definition at line 1300 of file fioMacros.h.
local_reduc_back_fn
typedef void(* local_reduc_back_fn) (void *, __INT_T, void *, __INT_T, __LOG_T *, __INT_T, __INT_T *, __INT_T, __INT_T, __INT_T, __LOG_T)
Definition at line 1296 of file fioMacros.h.
local_reduc_fn
typedef void(* local_reduc_fn) (void *, __INT_T, void *, __INT_T, __LOG_T *, __INT_T, __INT_T *, __INT_T, __INT_T, __INT_T)
Definition at line 1293 of file fioMacros.h.
proc
typedef struct proc proc
Definition at line 728 of file fioMacros.h.
procdim
typedef struct procdim procdim
Definition at line 727 of file fioMacros.h.
repl_t
typedef struct repl_t repl_t
Definition at line 1263 of file fioMacros.h.
sked
typedef struct sked sked
Definition at line 1283 of file fioMacros.h.
sked_free_fn
typedef void(* sked_free_fn) (void *schedule)
Definition at line 1279 of file fioMacros.h.
sked_start_fn
typedef void(* sked_start_fn) (void *schedule, char *rb, char *sb, F90_Desc *rd, F90_Desc *sd)
Definition at line 1277 of file fioMacros.h.
TYPE_DESC
typedef struct type_desc TYPE_DESC
Definition at line 816 of file fioMacros.h.
Enumeration Type Documentation
_io_intent
enum _io_intent
Enumerator
__INOUT
__IN
__OUT
Definition at line 623 of file fioMacros.h.
_io_spec
enum _io_spec
Enumerator
__OMITTED
__PRESCRIPTIVE
__DESCRIPTIVE
__TRANSCRIPTIVE
Definition at line 631 of file fioMacros.h.
_set_single_enum
enum _set_single_enum
Enumerator
__SINGLE
__SCALAR
Definition at line 1483 of file fioMacros.h.
Function Documentation
__fort_abort()
void __fort_abort (const char * msg)
Definition at line 320 of file initpar.c.
References __fort_abortx(), __fort_lcpu, buf, NULL, s, strlen(), and write.
Referenced by __alloc04(), __auto_alloc(), __fort_abortp(), __fort_adjbase(), __fort_adjust_index_array(), __fort_alloc(), __fort_associated(), __fort_calloc(), __fort_comm_merge(), __fort_coord_to_procnum(), __fort_copy(), __fort_create_conforming_index_array(), __fort_create_conforming_mask_array(), __fort_crecv(), __fort_csend(), __fort_cyclic_loop(), __fort_dealloc(), __fort_dealloc03(), __fort_defaultproc(), __fort_doit(), __fort_ebcopys(), __fort_erecv(), __fort_esend(), __fort_fetch_int(), __fort_fetch_int_element(), __fort_fetch_int_vector(), __fort_fetch_log(), __fort_finish_descriptor(), __fort_gen_block_bounds(), __fort_get_scalar(), __fort_getarg(), __fort_getdir(), __fort_global_reduce(), __fort_inherit_template(), __fort_init_consts(), __fort_initopt(), __fort_kalloc(), __fort_local_address(), __fort_local_offset(), __fort_localize(), __fort_malloc(), __fort_par_read(), __fort_procnum_to_coord(), __fort_realloc(), __fort_recvl(), __fort_red_abort(), __fort_reverse_array(), __fort_sendl(), __fort_set_alignment(), __fort_set_sectionx(), __fort_set_single(), __fort_store_int(), __fort_store_int_element(), __fort_store_int_vector(), __fort_store_log(), __fort_trac_init(), __fort_use_allocation(), __fort_varying_int(), __fort_varying_log(), __fort_zwrite(), __fortio_eoferr(), __fortio_eorerr(), __fortio_error(), __fortio_main(), __INT_T(), __LOG_T(), advance(), advance_permuted(), block_setup(), comm_sked_start(), copy_in_abort(), copy_loop(), copy_none(), copy_xfer(), cyclic_setup(), DCLEN64(), ENTF90(), ENTFTN(), fetch_int(), fetch_vector(), gathscat_abort(), getopt_abort(), global_reduce_abort(), if(), mmul_mxm(), mmul_mxv(), mmul_vxm(), nullify(), olap_copy(), olap_recv(), olap_send(), olap_shift(), olap_start(), print_row(), proc_setup(), ptr_asgn(), ptr_out(), put_int(), sighand(), store_element(), store_int(), store_int_kind(), store_log(), store_vector(), store_vector_int(), and void().
__fort_abortp()
void __fort_abortp (const char * s)
Definition at line 334 of file initpar.c.
References __fort_abort(), __fort_lcpu, __io_stderr(), NULL, and s.
Referenced by __fort_gethostname(), __fort_par_close(), __fort_par_open(), __fort_par_read(), __fort_par_seek(), __fort_par_unlink(), __fort_par_write(), __fort_second(), __fort_zclose(), __fort_zopen(), and __fort_zwrite().
__fort_abortx()
void __fort_abortx (void)
Abort the whole mess.
Definition at line 35 of file init.c.
References __abort(), __fort_traceback(), and NULL.
Referenced by __fort_abort().
__fort_adjbase()
void __fort_adjbase (chdr * c, char * bases, char * baser, int typ, long ilen)
Definition at line 220 of file xfer.c.
References __fort_abort(), avl, CHDR_1DBL, CHDR_1INT, CHDR_BASE, ent::ilen, n, p, and ent::typ.
Referenced by comm_sked_start(), gathscat_start(), and olap_start().
__fort_aligned()
int I8() __fort_aligned (F90_Desc * t, __INT_T * tmap, F90_Desc * u, __INT_T * umap)
Leftover from HPF Fortran.
Definition at line 55 of file aligned.c.
Referenced by __fort_gathscat().
__fort_aligned_axes()
int I8() __fort_aligned_axes (F90_Desc * t, int tx, F90_Desc * u, int ux)
Leftover from HPF Fortran.
Definition at line 69 of file aligned.c.
Referenced by __fort_gathscat().
__fort_alloc()
char *I8() __fort_alloc (__INT_T nelem, dtype kind, size_t len, __STAT_T * stat, char ** pointer, __POINT_T * offset, char * base, int check, void *(*)(size_t) mallocfn)
allocate space using given 'malloc' function. if present, set pointer and pointer-sized integer offset from base address. offset is in units of the data type length.
Definition at line 230 of file allo.c.
References __DERIVED, __fort_abort(), __fort_test, __STR, ALIGNP, ALLHDR, ALN_MAXADJ, ALN_MINSZ, ALN_THRESH, ALN_UNIT, area, ASZ, AUTOASZ, base, DEBUG_ALLO, GET_DIST_LCPU, GET_DIST_SHIFTS, getenv(), ISPRESENT, kind, len, MP_P, MP_P_STDIO, MP_V, MP_V_STDIO, msg(), nelem, NULL, off, offset, p, pointer, sem, size, stat, and XYZZYP.
Referenced by __fort_allocate(), __fort_local_allocate(), ENTF90(), ftn_alloc(), ftn_allocate(), and void().
__fort_allocate()
char *I8() __fort_allocate (int nelem, dtype kind, size_t len, char * base, char ** pointer, __POINT_T * offset)
Allocate global array (must be same size on all processors), return pointer and pointer-sized integer offset from base address. offset is in units of the data type length. don't check allocated status.
Definition at line 1492 of file allo.c.
References __fort_alloc(), __fort_gmalloc_without_abort(), base, I8, kind, len, nelem, NULL, offset, and pointer.
Referenced by ENTF90(), and recopy().
__fort_allocated()
int I8() __fort_allocated (char * area)
Is array allocated?
Definition at line 611 of file allo.c.
References ALLHDR, and area.
Referenced by __alloc04(), ENTF90(), ftn_allocated(), process_final_procedures(), and sourced_alloc_and_assign().
__fort_atol()
int __fort_atol (char * p)
Definition at line 12 of file atol.c.
References n, p, and q.
__fort_barrier()
void __fort_barrier (void)
Definition at line 65 of file init.c.
Referenced by __fort_par_close(), __fort_par_open(), __fort_par_read(), __fort_par_unlink(), __fort_par_write(), __fortio_cleanup(), and ENTF90().
__fort_bcopy()
void __fort_bcopy (char * to, char * fr, size_t n)
Definition at line 12 of file bcopy.c.
References n.
Referenced by __fort_bcopysl(), __fort_copy_descriptor(), __fort_map(), __fort_zwrite(), ENTF90(), ENTFTN(), if(), merge_ent(), process_final_procedures(), ptr_assign(), ptr_assn(), and sourced_alloc_and_assign().
__fort_bcopysl()
void __fort_bcopysl (char * to, char * fr, size_t cnt, size_t tostr, size_t frstr, size_t size)
Definition at line 23 of file bcopys.c.
References __fort_bcopy(), ALIGNMASK, cnt, i, j, k, len, and n.
Referenced by __fort_ebcopys(), fills_loop(), and local_copy().
__fort_bcstchn()
void __fort_bcstchn (struct chdr * c, int scpu, int ncpus, int * cpus)
Definition at line 16 of file chnbcst_loop.c.
References __fort_myprocnum(), CPU_RECV, CPU_SEND, and n.
Referenced by __fort_chn_1toN().
__fort_begpar()
void __fort_begpar (int ncpus)
Begin parallel program.
Definition at line 49 of file init.c.
References __fort_procargs(), __fort_sethand(), __io_stderr(), GET_DIST_TCPUS, SET_DIST_LCPU, SET_DIST_TCPUS, SET_DIST_TIDS, and tid.
Referenced by ENTFTN().
__fort_block_bounds()
__INT_T I8() __fort_block_bounds (F90_Desc * d, __INT_T dim, __INT_T ci, __INT_T * bl, __INT_T * bu)
Definition at line 960 of file runtime/flang/dist.c.
References block_setup(), d, DECL_DIM_PTRS, dim, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, I8, and SET_DIM_PTRS.
Referenced by copy_loop(), ENTFTN(), fills_loop(), gathscat_loop(), gathscat_mask_loop(), kred_array_loop(), local_copy(), mmul_mxm(), mmul_mxv(), mmul_vxm(), olap_loop(), olap_recv(), olap_send(), print_loop(), prng_loop_d_lf(), prng_loop_d_npb(), prng_loop_r_lf(), prng_loop_r_npb(), red_array_loop(), and red_scalar_loop().
__fort_block_loop()
int I8() __fort_block_loop (F90_Desc * d, int dim, __INT_T l, __INT_T u, int s, __INT_T ci, __INT_T * bl, __INT_T * bu)
Definition at line 943 of file runtime/flang/dist.c.
References block_setup(), d, dim, I8, and s.
Referenced by gathscat_loop(), and gathscat_mask_loop().
__fort_calloc()
void * __fort_calloc (size_t n, size_t s)
Definition at line 89 of file malloc.c.
References __fort_abort(), n, p, s, and ZIP.
Referenced by __fort_allchn(), __fort_copy(), and __fort_gcalloc().
__fort_calloc_without_abort()
void * __fort_calloc_without_abort (size_t n)
Definition at line 76 of file malloc.c.
References malloc(), n, NULL, p, and ZIP.
Referenced by __fort_gcalloc_without_abort(), ENTF90(), and void().
__fort_chain_em_up()
chdr * __fort_chain_em_up (chdr * list, chdr * c)
Definition at line 202 of file xfer.c.
References c, list, and chdr::next.
Referenced by __fort_copy(), cshift_loop(), and ENTFTN().
__fort_chn_1to1()
chdr * __fort_chn_1to1 (chdr * fir, int dnd, int dlow, int * dcnt, int * dstr, int snd, int slow, int * scnt, int * sstr)
Definition at line 15 of file chn1t1.c.
References __fort_allchn(), __fort_free(), __fort_genlist(), __fort_initndx(), c, cp, cpu(), CPU_COPY, CPU_RECV, CPU_SEND, cgrp::cpus, GET_DIST_LCPU, GET_DIST_TCPUS, MAXDIMS, cgrp::ncpus, r, and sg.
Referenced by __fort_copy(), __fort_exchange_counts(), mget_recv(), mget_send(), and olap_shift().
__fort_chn_1toN()
chdr * __fort_chn_1toN (chdr * fir, int dnd, int dlow, int * dcnt, int * dstr, int snd, int slow, int * scnt, int * sstr)
Definition at line 15 of file chn1tn.c.
References __fort_allchn(), __fort_bcstchn(), __fort_free(), __fort_genlist(), __fort_malloc(), __fort_myprocnum(), c, copy(), cp, CPU_COPY, CPU_RECV, CPU_SEND, cgrp::cpus, i, MAXDIMS, n, cgrp::ncpus, and sg.
Referenced by copy_xfer().
__fort_chn_prune()
void __fort_chn_prune (struct chdr * c)
Definition at line 364 of file xfer.c.
References m, and n.
Referenced by __fort_copy(), __fort_exchange_counts(), ENTFTN(), and olap_shift().
__fort_comm_sked()
sked *I8() __fort_comm_sked (chdr * ch, char * rb, char * sb, dtype kind, int len)
Definition at line 50 of file runtime/flang/comm.c.
References __fort_malloc(), __fort_setbase(), __SKED, sked::arg, comm_sked::channel, comm_sked_free(), comm_sked_start(), sked::free, I8, kind, len, rb, sb, comm_sked::sked, sked::start, and sked::tag.
Referenced by ENTFTN().
__fort_conform()
int I8() __fort_conform (F90_Desc * s, __INT_T * smap, F90_Desc * t, __INT_T * tmap)
Compare rank and shape of objects s and t. Return true if s and t are conformable under the axis mappings smap and tmap. Scalars are conformable with arrays. conform(A,B) implies conform(B,A).
Definition at line 21 of file aligned.c.
References __DESC, DECL_DIM_PTRS, dim, F90_DPTR_EXTENT_G, F90_GSIZE_G, F90_RANK_G, F90_TAG_G, NULL, s, SET_DIM_PTRS, t, and td.
Referenced by __fort_gathscat().
__fort_copy()
chdr *I8() __fort_copy (void * db, void * sb, F90_Desc * dd, F90_Desc * sd, int * smap)
Definition at line 670 of file copy.c.
References _1, __BOGUSBOUNDS, __DESC, __fort_abort(), __fort_calloc(), __fort_chain_em_up(), __fort_chn_1to1(), __fort_chn_prune(), __fort_describe_replication(), __fort_finish_section(), __fort_free(), __fort_recvl(), __fort_sendl(), __fort_set_section(), __fort_show_index(), __fort_show_section(), __fort_test, copy_loop(), copy_setup(), copy_xfer(), db(), dc, DEBUG_COPY, DECL_DIM_PTRS, DIST_ACTUAL_ARG_G, DIST_ACTUAL_ARG_P, DIST_DPTR_TAXIS_G, DIST_DPTR_TLB_G, DIST_DPTR_TUB_G, DIST_REPLICATED_G, DIST_SCOFF_G, DPTR_UBOUND_G, ds(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_FLAGS_P, F90_GSIZE_G, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_LCPU, GET_DIST_TCPUS_ADDR, i, I8, identity_map, j, LOCAL_MODE, Max, Min, n, NULL, offset, sb, SET_DIM_PTRS, sg, chdr::sn, ss, and z.
Referenced by cshift_loop(), ENTFTN(), eoshift_scalar(), and recopy().
__fort_copy_descriptor()
void I8() __fort_copy_descriptor (F90_Desc * d, F90_Desc * d0)
Definition at line 2409 of file runtime/flang/dist.c.
References __DESC, __fort_bcopy(), d, F90_RANK_G, F90_TAG_G, F90_TAG_P, SET_F90_DIST_DESC_PTR, and SIZE_OF_RANK_n_ARRAY_DESC.
Referenced by __fort_inherit_template(), and ENTFTN().
__fort_copy_out()
void I8() __fort_copy_out (void * db, void * sb, F90_Desc * dd, F90_Desc * sd, __INT_T flags)
Parameters
db actual base address
sb dummy base address
dd actual descriptor
sd dummy descriptor
Definition at line 787 of file rdst.c.
References __COPY_OUT, __DESC, __DIST_INIT_DESCRIPTOR, __DIST_SET_DISTRIBUTION, __fort_cycle_bounds(), __fort_finish_descriptor(), __fort_local_deallocate(), __fort_test, __IN, __INTENT_MASK, __INTENT_SHIFT, __NO_OVERLAPS, __NOT_COPIED, __SEQUENCE, __TEMPLATE, c, db(), DEBUG_RDST, DECL_HDR_PTRS, DECL_HDR_VARS, DIST_ALIGN_TARGET_G, DIST_DIST_TARGET_G, F90_DIM_EXTENT_G, F90_FLAGS_G, F90_FLAGS_P, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, flags, GET_DIST_LCPU, i, I8, intent, ISPRESENT, local_copy(), MAXDIMS, and NULL.
Referenced by __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), ENTFTN(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
__fort_covers_procs()
int I8() __fort_covers_procs (F90_Desc * s, F90_Desc * t)
Definition at line 44 of file aligned.c.
Referenced by __fort_gathscat().
__fort_create_conforming_mask_array()
void *I8() __fort_create_conforming_mask_array (const char * what, char * ab, char * mb, F90_Desc * as, F90_Desc * ms, F90_Desc * new_ms)
Definition at line 1291 of file red.c.
References __fort_abort(), __fort_gmalloc(), __LOG1, __LOG2, __LOG4, __LOG8, ENTFTN(), F90_GSIZE_G, F90_LSIZE_G, F90_TAG_G, GET_DIST_LCPU, i, and ISSCALAR.
Referenced by ENTFTN(), kmaxloc_common(), kminloc_common(), maxloc_common(), and minloc_common().
__fort_cycle_bounds()
void I8() __fort_cycle_bounds (F90_Desc * d)
Definition at line 743 of file runtime/flang/dist.c.
References cyclic_setup(), d, DECL_DIM_PTRS, dim, DIST_CACHED_G, DIST_CACHED_P, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_P, DIST_DPTR_CS_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_RANK_G, I8, and SET_DIM_PTRS.
Referenced by __fort_copy_out(), __fort_fills(), __fort_gathscat(), __fort_kred_arraylk(), __fort_kred_scalarlk(), __fort_print_local(), __fort_red_array(), __fort_red_arraylk(), __fort_red_scalar(), __fort_red_scalarlk(), copy_setup(), ENTFTN(), mmul_mxm(), mmul_mxv(), mmul_vxm(), and olap_shift().
__fort_cyclic_loop()
__INT_T I8() __fort_cyclic_loop (F90_Desc * d, __INT_T dim, __INT_T l, __INT_T u, __INT_T s, __INT_T * cl, __INT_T * cu, __INT_T * cs, __INT_T * clof, __INT_T * clos)
Definition at line 768 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), cl, cs, cyclic_setup(), d, DECL_DIM_PTRS, dim, DIST_CACHED_G, DIST_CACHED_P, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CN_P, DIST_DPTR_CS_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_RANK_G, F90_TAG_G, I8, m, NULL, s, and SET_DIM_PTRS.
Referenced by ENTFTN(), gathscat_loop(), gathscat_mask_loop(), mmul_mxv(), and mmul_vxm().
__fort_dealloc()
char *I8() __fort_dealloc (char * area, __STAT_T * stat, void(*)(void *) freefn)
Deallocate array using given 'free' function.
Definition at line 1545 of file allo.c.
References __fort_abort(), __fort_test, ALLHDR, area, DEBUG_ALLO, GET_DIST_LCPU, ISPRESENT, MP_P_STDIO, MP_V_STDIO, msg(), NULL, p, stat, and XYZZY.
Referenced by __fort_deallocate(), __fort_local_deallocate(), ENTF90(), ftn_dealloc(), ftn_deallocate(), use_alloc(), and void().
__fort_deallocate()
void I8() __fort_deallocate (char * area)
deallocate global array
Definition at line 1719 of file allo.c.
References __fort_dealloc(), __fort_gfree(), area, I8, NULL, and void().
Referenced by ENTF90(), and recopy().
__fort_defaultproc()
proc * __fort_defaultproc (int rank)
Definition at line 1113 of file runtime/flang/dist.c.
References __fort_abort(), __fort_malloc(), __PROC, default_proc_list, GET_DIST_TCPUS, i, k, MAXDIMS, NPRIMES, NULL, p, prime, proc_setup(), rank, and t.
Referenced by ENTFTN().
__fort_describe_replication()
void I8() __fort_describe_replication (F90_Desc * d, repl_t * r)
Definition at line 280 of file runtime/flang/dist.c.
References d, DECL_DIM_PTRS, DIST_DIST_TARGET_G, DIST_DPTR_PCOORD_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_PSTRIDE_G, DIST_MAPPED_G, DIST_PBASE_G, DIST_REPLICATED_G, F90_RANK_G, m, ndim, p, pd, r, and SET_DIM_PTRS.
Referenced by __fort_copy(), __fort_gathscat(), __fortio_main(), and ENTFTN().
__fort_doit()
void __fort_doit (chdr * c)
Definition at line 57 of file xfer_rpm1.c.
References __fort_abort(), __fort_ebcopys(), cp, CPU_COPY, and n.
Referenced by __fort_exchange_counts(), comm_sked_start(), cshift_loop(), ENTFTN(), eoshift_scalar(), gathscat_start(), olap_start(), and recopy().
__fort_endpar()
void __fort_endpar (void)
End of parallel program.
Definition at line 43 of file init.c.
Referenced by term().
__fort_entry_arecv()
void __fort_entry_arecv (int cpu, long len, int reqn)
Definition at line 342 of file entry.c.
References __fort_prof_arecv(), __fort_prof_mflag, __fort_stat_arecv(), __fort_stat_mflag, __fort_trac_arecv(), __fort_trac_mflag, cpu(), and len.
__fort_entry_arecv_done()
void __fort_entry_arecv_done (int cpu)
Definition at line 358 of file entry.c.
References __fort_prof_arecv_done(), __fort_prof_mflag, __fort_stat_arecv_done(), __fort_stat_mflag, __fort_trac_mflag, __fort_trac_recv_done(), and cpu().
__fort_entry_asend()
void __fort_entry_asend (int cpu, long len, int reqn)
Definition at line 374 of file entry.c.
References __fort_prof_asend(), __fort_prof_mflag, __fort_stat_asend(), __fort_stat_mflag, __fort_trac_asend(), __fort_trac_mflag, cpu(), and len.
__fort_entry_asend_done()
void __fort_entry_asend_done (int cpu)
Definition at line 390 of file entry.c.
References __fort_prof_asend_done(), __fort_prof_mflag, __fort_stat_asend_done(), __fort_stat_mflag, __fort_trac_asend_done(), __fort_trac_mflag, and cpu().
__fort_entry_await()
void __fort_entry_await (int reqn)
Definition at line 406 of file entry.c.
References __fort_prof_await(), __fort_prof_mflag, __fort_stat_await(), __fort_stat_mflag, __fort_trac_await(), and __fort_trac_mflag.
__fort_entry_await_done()
void __fort_entry_await_done (int reqn)
Definition at line 422 of file entry.c.
References __fort_prof_await_done(), __fort_prof_mflag, __fort_stat_await_done(), __fort_stat_mflag, __fort_trac_await_done(), and __fort_trac_mflag.
__fort_entry_copy()
void __fort_entry_copy (long len)
Definition at line 310 of file entry.c.
References __fort_prof_copy(), __fort_prof_mflag, __fort_stat_copy(), __fort_stat_mflag, __fort_trac_copy(), __fort_trac_mflag, and len.
__fort_entry_copy_done()
void __fort_entry_copy_done (void)
Definition at line 326 of file entry.c.
References __fort_prof_copy_done(), __fort_prof_mflag, __fort_stat_copy_done(), __fort_stat_mflag, __fort_trac_copy_done(), and __fort_trac_mflag.
__fort_entry_init()
void __fort_entry_init (void)
Initialization.
Definition at line 60 of file entry.c.
References __fort_entry_mflag, __fort_malloc(), __fort_prof_init(), __fort_prof_mflag, __fort_stat_init(), __fort_stat_mflag, __fort_trac_init(), __fort_trac_mflag, pent::file, pent::filel, pent::func, pent::funcl, pentb, pentc, pente, PENTS, and UNKNOWN.
Referenced by ENTFTN().
__fort_entry_recv()
void __fort_entry_recv (int cpu, long len)
Definition at line 246 of file entry.c.
References __fort_prof_mflag, __fort_prof_recv(), __fort_stat_mflag, __fort_stat_recv(), __fort_trac_mflag, __fort_trac_recv(), cpu(), and len.
__fort_entry_recv_done()
void __fort_entry_recv_done (int cpu)
Definition at line 262 of file entry.c.
References __fort_prof_mflag, __fort_prof_recv_done(), __fort_stat_mflag, __fort_stat_recv_done(), __fort_trac_mflag, __fort_trac_recv_done(), and cpu().
__fort_entry_send()
void __fort_entry_send (int cpu, long len)
Definition at line 278 of file entry.c.
References __fort_prof_mflag, __fort_prof_send(), __fort_stat_mflag, __fort_stat_send(), __fort_trac_mflag, __fort_trac_send(), cpu(), and len.
__fort_entry_send_done()
void __fort_entry_send_done (int cpu)
Definition at line 294 of file entry.c.
References __fort_prof_mflag, __fort_prof_send_done(), __fort_stat_mflag, __fort_stat_send_done(), __fort_trac_mflag, __fort_trac_send_done(), and cpu().
__fort_entry_term()
void __fort_entry_term (void)
Termination.
Definition at line 437 of file entry.c.
References __fort_entry_mflag, __fort_prof_term(), __fort_stat_term(), and __fort_trac_term().
Referenced by term().
__fort_erecv()
void __fort_erecv (int cpu, struct ents * e)
Definition at line 15 of file xfer_rpm1.c.
References __fort_abort().
Referenced by __fort_rbcstl(), and __fort_rrecvl().
__fort_esend()
void __fort_esend (int cpu, struct ents * e)
Definition at line 22 of file xfer_rpm1.c.
References __fort_abort().
Referenced by __fort_rbcstl(), and __fort_rsendl().
__fort_exchange_counts()
int __fort_exchange_counts (int * counts)
Definition at line 28 of file exch.c.
References _1, __CINT, __fort_chn_1to1(), __fort_chn_prune(), __fort_doit(), __fort_gmalloc(), __fort_np2, __fort_recvl(), __fort_sendl(), __fort_test, c, cpu(), DEBUG_EXCH, exch, GET_DIST_LCPU, GET_DIST_TCPUS, GET_DIST_TCPUS_ADDR, i, j, k, m, n, NULL, rbuf, rmax, sbuf, smax, vcounts, vrbuf, vrmax, and vsbuf.
__fort_exit()
void __fort_exit (int s)
Definition at line 344 of file initpar.c.
__fort_fetch_int()
int I8() __fort_fetch_int (void * b, F90_Desc * d)
Definition at line 54 of file util.c.
References __DESC, __fort_abort(), __INT1, __INT2, __INT4, __INT8, __OFF_TEMPLATE, Abs, b, d, DIST_SCOFF_G, F90_FLAGS_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, and kind.
Referenced by __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), __INT8_T(), __INT_T(), and ENTFTN().
__fort_fetch_int_element()
int I8() __fort_fetch_int_element (void * b, F90_Desc * d, int i)
Definition at line 185 of file util.c.
References __fort_abort(), __fort_get_scalar(), __INT1, __INT2, __INT4, __INT8, b, d, F90_DIM_LBOUND_G, F90_KIND_G, F90_RANK_G, i, I8, idx, tmp, and val.
__fort_fetch_int_vector()
void I8() __fort_fetch_int_vector (void * b, F90_Desc * d, int * vec, int veclen)
Definition at line 249 of file util.c.
References __fort_abort(), __fort_get_scalar(), __INT1, __INT2, __INT4, __INT8, b, d, F90_DIM_LBOUND_G, F90_KIND_G, F90_RANK_G, i, I8, tmp, and vec.
Referenced by ENTFTN().
__fort_fetch_log()
int I8() __fort_fetch_log (void * b, F90_Desc * d)
Definition at line 120 of file util.c.
References __DESC, __fort_abort(), __LOG1, __LOG2, __LOG4, __LOG8, __OFF_TEMPLATE, Abs, b, d, DIST_SCOFF_G, F90_FLAGS_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_MASK_LOG1, GET_DIST_MASK_LOG2, GET_DIST_MASK_LOG4, GET_DIST_MASK_LOG8, and kind.
Referenced by __fort_gathscat(), __fort_kred_arraylk(), __fort_kred_scalarlk(), __fort_red_array(), __fort_red_arraylk(), __fort_red_scalar(), and __fort_red_scalarlk().
__fort_fills()
void I8() __fort_fills (char * ab, F90_Desc * ad, void * fill)
Definition at line 48 of file fill.c.
References __fort_cycle_bounds(), __fort_scalar_copy, __OFF_TEMPLATE, DIST_SCOFF_G, F90_FLAGS_G, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, fills_loop(), and I8.
Referenced by eoshift_scalar(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
__fort_findndx()
int __fort_findndx (int cpu, int nd, int low, int * nstrs, int * mults)
Definition at line 55 of file genlist.c.
References cpu(), i, and n.
__fort_finish_descriptor()
void I8() __fort_finish_descriptor (F90_Desc * d)
Definition at line 1367 of file runtime/flang/dist.c.
References __DERIVED, __fort_abort(), __fort_heap_block, __NONE, __STR, d, DECL_DIM_PTRS, DIST_DPTR_LAB_G, DIST_DPTR_LOFFSET_P, DIST_HEAPB_G, DIST_HEAPB_P, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_P, F90_GSIZE_P, F90_KIND_G, F90_LBASE_P, F90_LEN_G, F90_LSIZE_P, F90_RANK_G, GET_DIST_SHIFTS, i, lbase, rank, and SET_DIM_PTRS.
Referenced by __fort_copy_out(), ENTF90(), ENTFTN(), ptr_asgn(), and void().
__fort_finish_section()
void I8() __fort_finish_section (F90_Desc * d)
Definition at line 1485 of file runtime/flang/dist.c.
References __SEQUENCE, d, DIST_NONSEQUENCE_G, F90_DIM_EXTENT_G, F90_FLAGS_G, F90_FLAGS_P, F90_GSIZE_P, F90_RANK_G, i, and rank.
Referenced by __fort_copy(), cshift_loop(), ENTFTN(), and eoshift_scalar().
__fort_frechn()
void __fort_frechn (chdr * c)
Definition at line 53 of file xfer.c.
References __fort_free(), d, and n.
Referenced by comm_sked_free(), cshift_loop(), ENTFTN(), eoshift_scalar(), gathscat_free(), olap_free(), and recopy().
__fort_free()
void __fort_free (void * ptr)
Definition at line 105 of file malloc.c.
References ZIP.
Referenced by __f90_allo_term(), __fort_chn_1to1(), __fort_chn_1toN(), __fort_comm_merge(), __fort_copy(), __fort_frechn(), __fort_gen_block_bounds(), __fort_getmap(), __fort_gfree(), __fort_initopt(), __fort_local_deallocate(), __fort_map(), __INT_T(), comm_sked_free(), copy_loop(), ENTF90(), ENTF90IO(), ENTFTN(), ftn_dealloc(), ftn_deallocate(), gathscat_free(), if(), merge_ent(), olap_free(), olap_recv(), olap_send(), olap_shift(), and use_alloc().
__fort_ftnstrcpy()
void __fort_ftnstrcpy (char * dst, int len, char * src)
Definition at line 314 of file util.c.
References end, len, and src.
__fort_gcalloc()
void * __fort_gcalloc (size_t n, size_t s)
Definition at line 141 of file malloc.c.
References __fort_calloc(), n, and s.
__fort_gcalloc_without_abort()
void * __fort_gcalloc_without_abort (size_t n)
Definition at line 135 of file malloc.c.
References __fort_calloc_without_abort(), and n.
Referenced by ENTF90(), and void().
__fort_gcd()
int __fort_gcd (int u, int v)
Definition at line 165 of file runtime/flang/dist.c.
References k, m, n, and t.
Referenced by __fort_lcm().
__fort_gen_block_bounds()
void I8() __fort_gen_block_bounds (F90_Desc * d, int dim, __INT_T * the_olb, __INT_T * the_oub, __INT_T pcoord)
Definition at line 28 of file runtime/flang/dist.c.
References __fort_abort(), __fort_free(), __fort_new_gen_block(), d, DECL_DIM_PTRS, dim, DIST_DPTR_GEN_BLOCK_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_TLB_G, DIST_DPTR_TSTRIDE_G, DIST_DPTR_TUB_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, i, I8, and SET_DIM_PTRS.
__fort_get_scalar()
void I8() __fort_get_scalar (void * temp, void * b, F90_Desc * d, __INT_T * gidx)
Definition at line 20 of file scal.c.
References __fort_abort(), __fort_local_address(), __fort_owner, __fort_rbcstl(), __fort_scalar_copy, __fort_show_scalar(), __fort_test, __io_putchar(), __LOCAL, DEBUG_SCAL, DFMT, DFMT_GEN_BLOCK, DIM_UBOUND_G, DIST_ALIGN_TARGET_G, DIST_DIM_GEN_BLOCK_G, DIST_DIM_OLB_G, DIST_DIM_OUB_G, DIST_DIM_PSHAPE_G, DIST_DIM_TLB_G, DIST_DIM_TOFFSET_G, DIST_DIM_TSTRIDE_G, DIST_DIM_TUB_G, DIST_MAPPED_G, DIST_SCOFF_G, F90_DIM_LBOUND_G, F90_FLAGS_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, GET_DIST_LCPU, i, I8, idx, j, NULL, and src.
Referenced by __fort_fetch_int_element(), __fort_fetch_int_vector(), and ENTFTN().
__fort_getopt()
const char * __fort_getopt (const char * opt)
Definition at line 440 of file initpar.c.
References __fort_getenv(), arg, env, n, NULL, opt, p, and q.
Referenced by __fort_fixmnt(), __fort_gethostname(), __fort_getmap(), __fort_getoptb(), __fort_getoptn(), __fort_initcom(), __fort_istat(), __fort_sethand(), __fort_trac_init(), and ENTFTN().
__fort_getoptn()
long __fort_getoptn (const char * opt, long def)
Definition at line 508 of file initpar.c.
References __fort_getopt(), __fort_strtol(), def, getopt_abort(), n, NULL, opt, p, and q.
Referenced by ENTFTN().
__fort_gfree()
void __fort_gfree (void * ptr)
Definition at line 147 of file malloc.c.
References __fort_free().
Referenced by __fort_deallocate(), __fort_getgbuf(), __fort_global_reduce(), __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), __fort_reduce_section(), __fort_stat_term(), ENTF90(), ENTFTN(), ftn_dealloc(), ftn_deallocate(), gathscat_free(), gathscat_start(), kmaxloc_common(), kmaxlocs_common(), kminloc_common(), kminlocs_common(), maxloc_common(), maxlocs_common(), minloc_common(), minlocs_common(), and void().
__fort_gmalloc()
void * __fort_gmalloc (size_t n)
Definition at line 123 of file malloc.c.
References __fort_malloc(), and n.
Referenced by __chk_str_val(), __fort_adjust_index_array(), __fort_create_conforming_index_array(), __fort_create_conforming_mask_array(), __fort_exchange_counts(), __fort_getgbuf(), __fort_global_reduce(), __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), __fort_reduce_section(), __fort_stat_term(), __fort_zopen(), ENTFTN(), gathscat_start(), kmaxlocs_common(), kminlocs_common(), maxlocs_common(), and minlocs_common().
__fort_gmalloc_without_abort()
void * __fort_gmalloc_without_abort (size_t n)
Definition at line 117 of file malloc.c.
References __fort_malloc_without_abort(), and n.
Referenced by __fort_allocate(), __fort_kallocate(), ENTF90(), ftn_alloc(), and ftn_allocate().
__fort_grealloc()
void * __fort_grealloc (void * ptr, size_t n)
Definition at line 129 of file malloc.c.
References __fort_realloc(), and n.
__fort_gsbrk()
void * __fort_gsbrk (int n)
__fort_inherit_template()
F90_Desc *I8() __fort_inherit_template (F90_Desc * d, __INT_T rank, F90_Desc * target)
Definition at line 2423 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), __fort_copy_descriptor(), __NOT_COPIED, __TEMPLATE, ALIGNR, d, DECL_HDR_PTRS, DIST_ACTUAL_ARG_P, DIST_ALIGN_TARGET_P, DIST_NEXT_ALIGNEE_P, F90_FLAGS_G, F90_FLAGS_P, F90_LSIZE_P, F90_TAG_G, I8, MAXDIMS, NULL, rank, SIZE_OF_RANK_n_ARRAY_DESC, and t.
__fort_init_descriptor()
void I8() __fort_init_descriptor (F90_Desc * d, __INT_T rank, dtype kind, __INT_T len, __INT_T flags, void * target)
__fort_init_section()
void I8() __fort_init_section (F90_Desc * d, __INT_T rank, F90_Desc * a)
__fort_initndx()
void __fort_initndx (int nd, int * cnts, int * ncnts, int * strs, int * nstrs, int * mults)
Definition at line 12 of file genlist.c.
References i, and n.
Referenced by __fort_chn_1to1().
__fort_is_ioproc()
int __fort_is_ioproc (void)
Definition at line 312 of file initpar.c.
References __fort_ioproc, and __fort_lcpu.
Referenced by __fort_stat_term().
__fort_islocal()
int I8() __fort_islocal (F90_Desc * d, __INT_T * gidx)
Definition at line 372 of file runtime/flang/dist.c.
References __OFF_TEMPLATE, d, DECL_DIM_PTRS, DFMT__WIDTH, DIST_DFMT_G, F90_FLAGS_G, and SET_DIM_PTRS.
Referenced by __LOG_T(), and ENTFTN().
__fort_lcm()
int __fort_lcm (int u, int v)
Definition at line 218 of file runtime/flang/dist.c.
References __fort_gcd(), and p.
__fort_local_address()
void *I8() __fort_local_address (void * base, F90_Desc * d, __INT_T * gidx)
Definition at line 597 of file runtime/flang/dist.c.
References __fort_abort(), __OFF_TEMPLATE, __SEQUENCE, base, d, DECL_DIM_PTRS, DFMT__MASK, DFMT__WIDTH, DFMT_BLOCK, DFMT_BLOCK_K, DFMT_COLLAPSED, DFMT_GEN_BLOCK, DIST_DFMT_G, DIST_DPTR_OLB_G, DIST_DPTR_OUB_G, DIST_SCOFF_G, DPTR_UBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, idx, NULL, offset, and SET_DIM_PTRS.
Referenced by __fort_get_scalar(), __fort_store_int_element(), __fort_store_int_vector(), __io_read(), __io_write(), ENTFTN(), eval_dtio_sb(), eval_sb(), fetch_vector(), kred_array_loop(), red_array_loop(), red_scalar_loop(), store_element(), store_vector(), and store_vector_int().
__fort_local_allocate()
char *I8() __fort_local_allocate (int nelem, dtype kind, size_t len, char * base, char ** pointer, __POINT_T * offset)
Allocate local array (may be different size on each processor), return pointer and pointer-sized integer offset from base address. offset is in units of the data type length. don't check allocated status.
Definition at line 1506 of file allo.c.
References __fort_alloc(), __fort_malloc_without_abort(), base, I8, kind, len, nelem, NULL, offset, and pointer.
Referenced by ENTFTN().
__fort_local_deallocate()
void I8() __fort_local_deallocate (char * area)
deallocate local array
Definition at line 1729 of file allo.c.
References __fort_dealloc(), __fort_free(), area, I8, NULL, and void().
Referenced by __fort_copy_out().
__fort_local_offset()
__INT_T I8() __fort_local_offset (F90_Desc * d, __INT_T * gidx)
Definition at line 555 of file runtime/flang/dist.c.
References __fort_abort(), __fort_test, __OFF_TEMPLATE, __SEQUENCE, d, DEBUG_DIST, DECL_DIM_PTRS, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_LBASE_G, F90_RANK_G, GET_DIST_LCPU, idx, offset, and SET_DIM_PTRS.
Referenced by ENTFTN(), and gathscat_element().
__fort_localize()
void I8() __fort_localize (F90_Desc * d, __INT_T * idxv, int * cpu, __INT_T * off)
Definition at line 410 of file runtime/flang/dist.c.
References __fort_abort(), __fort_test, Ceil, cpu(), d, DEBUG_DIST, DECL_DIM_PTRS, DFMT__MASK, DFMT__WIDTH, DFMT_COLLAPSED, DIST_DFMT_G, DIST_DIST_TARGET_G, DIST_DPTR_AOFFSET_G, DIST_DPTR_ASTRIDE_G, DIST_DPTR_BLOCK_G, DIST_DPTR_CLB_G, DIST_DPTR_CYCLE_G, DIST_DPTR_GEN_BLOCK_G, DIST_DPTR_LAB_G, DIST_DPTR_NO_G, DIST_DPTR_PSTRIDE_G, DIST_PBASE_G, DIST_REPLICATED_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_RANK_G, GET_DIST_LCPU, off, offset, p, pd, and SET_DIM_PTRS.
Referenced by gathscat_element().
__fort_localproc()
proc * __fort_localproc (void)
Definition at line 1187 of file runtime/flang/dist.c.
References __fort_malloc(), __LOCAL, __PROC, proc::base, proc::flags, GET_DIST_LCPU, local_proc, MAXDIMS, NULL, proc_setup(), proc::rank, and proc::tag.
Referenced by void().
__fort_malloc()
void * __fort_malloc (size_t n)
Definition at line 37 of file malloc.c.
References __fort_abort(), __fort_malloc_without_abort(), n, and p.
Referenced by __fort_chn_1toN(), __fort_comm_sked(), __fort_defaultproc(), __fort_entry_init(), __fort_genlist(), __fort_getmap(), __fort_gmalloc(), __fort_initopt(), __fort_localproc(), __fort_map(), __fort_passarg(), __fort_passargs(), __fort_recvl(), __fort_sendl(), __INT_T(), ENTF90IO(), ENTFTN(), and if().
__fort_malloc_without_abort()
void * __fort_malloc_without_abort (size_t n)
Definition at line 24 of file malloc.c.
References __fort_zmem, malloc(), n, NULL, p, and ZIP.
Referenced by __fort_gmalloc_without_abort(), __fort_local_allocate(), __fort_local_kallocate(), __fort_malloc(), ENTF90(), ftn_alloc(), ftn_allocate(), and void().
__fort_myprocnum()
int __fort_myprocnum (void)
Definition at line 79 of file initpar.c.
References __fort_lcpu.
Referenced by __fort_bcstchn(), __fort_chn_1toN(), and sighand().
__fort_new_gen_block()
__INT_T *I8() __fort_new_gen_block (F90_Desc * d, int dim)
Referenced by __fort_gen_block_bounds(), copy_loop(), olap_recv(), olap_send(), and olap_shift().
__fort_next_owner()
int I8() __fort_next_owner (F90_Desc * d, repl_t * r, int * pc, int owner)
Definition at line 332 of file runtime/flang/dist.c.
References i, and r.
__fort_owner()
int I8() __fort_owner (F90_Desc * d, __INT_T * gidx)
Definition at line 227 of file runtime/flang/dist.c.
Referenced by __INT_T().
__fort_par_unlink()
void __fort_par_unlink (char * fn)
Definition at line 196 of file usrio_smp.c.
References __fort_abortp(), __fort_barrier(), fn, and GET_DIST_LCPU.
__fort_procargs()
void __fort_procargs (void)
Definition at line 656 of file initpar.c.
References __fort_initarg(), __fort_initcom(), __fort_initopt(), and arg.
Referenced by __fort_begpar().
__fort_prof_arecv()
void __fort_prof_arecv (int cpu, long len, int reqn)
Definition at line 11 of file cprof2.c.
Referenced by __fort_entry_arecv().
__fort_prof_arecv_done()
void __fort_prof_arecv_done (int cpu)
Definition at line 18 of file cprof2.c.
Referenced by __fort_entry_arecv_done().
__fort_prof_asend()
void __fort_prof_asend (int cpu, long len, int reqn)
Definition at line 25 of file cprof2.c.
Referenced by __fort_entry_asend().
__fort_prof_asend_done()
void __fort_prof_asend_done (int cpu)
Definition at line 32 of file cprof2.c.
Referenced by __fort_entry_asend_done().
__fort_prof_await()
void __fort_prof_await (int reqn)
Definition at line 39 of file cprof2.c.
Referenced by __fort_entry_await().
__fort_prof_await_done()
void __fort_prof_await_done (int reqn)
Definition at line 46 of file cprof2.c.
Referenced by __fort_entry_await_done().
__fort_prof_copy()
void __fort_prof_copy (long len)
Update start bcopy message stats.
Parameters
len total length in bytes
Definition at line 62 of file cprof.c.
Referenced by __fort_entry_copy().
__fort_prof_copy_done()
void __fort_prof_copy_done (void)
Update done bcopy message stats.
Definition at line 68 of file cprof.c.
Referenced by __fort_entry_copy_done().
__fort_prof_function_entry()
void __fort_prof_function_entry (int line, int lines, int cline, char * func, char * file, int funcl, int filel)
Function entry
Definition at line 17 of file cprof.c.
Referenced by ENTFTN().
__fort_prof_function_exit()
void __fort_prof_function_exit (void)
Function exit
Definition at line 74 of file cprof.c.
Referenced by ENTFTN().
__fort_prof_init()
int __fort_prof_init (void)
Profile initialization.
Definition at line 10 of file cprof.c.
Referenced by __fort_entry_init().
__fort_prof_line_entry()
void __fort_prof_line_entry (int line)
Line entry
Definition at line 24 of file cprof.c.
Referenced by ENTFTN().
__fort_prof_recv()
void __fort_prof_recv (int cpu, long len)
Update start receive message stats.
Parameters
cpu sending cpu
len total length in bytes
Definition at line 33 of file cprof.c.
Referenced by __fort_entry_recv().
__fort_prof_recv_done()
void __fort_prof_recv_done (int cpu)
Update done receive message stats.
Definition at line 39 of file cprof.c.
Referenced by __fort_entry_recv_done().
__fort_prof_send()
void __fort_prof_send (int cpu, long len)
Update start send message stats.
Parameters
cpu receiving cpu
len total length in bytes
Definition at line 48 of file cprof.c.
Referenced by __fort_entry_send().
__fort_prof_send_done()
void __fort_prof_send_done (int cpu)
Update done send message stats.
Definition at line 54 of file cprof.c.
Referenced by __fort_entry_send_done().
__fort_prof_term()
void __fort_prof_term (void)
Profile termination.
Definition at line 80 of file cprof.c.
Referenced by __fort_entry_term().
__fort_ptr_aligned()
int I8() __fort_ptr_aligned (char * p1, dtype kind, int len, char * p2)
Return nonzero if addresses p1 and p2 are aligned with respect to a multiple of the length of the data type.
Definition at line 148 of file allo.c.
References __DERIVED, __STR, GET_DIST_SHIFTS, kind, len, and off.
Referenced by ENTFTN().
__fort_ptr_offset()
char *I8() __fort_ptr_offset (char ** pointer, __POINT_T * offset, char * base, dtype kind, __CLEN_T len, char * area)
Compute pointer-sized index offset to replace Cray pointer, return aligned address. offset assumes 1-based arrays.
Definition at line 165 of file allo.c.
References __DERIVED, __fort_test, __STR, area, base, DEBUG_ALLO, GET_DIST_LCPU, GET_DIST_SHIFTS, ISPRESENT, kind, len, off, offset, and pointer.
Referenced by ENTFTN(), nullify(), ptr_asgn(), and ptr_in().
__fort_rbcst()
void __fort_rbcst (int src, void * adr, long cnt, long str, int typ)
Definition at line 130 of file rw.c.
References __fort_rbcstl(), ent::adr, cnt, GET_DIST_SIZE_OF, src, str, and ent::typ.
Referenced by __fort_status_bcst(), and __fort_time().
__fort_rbcstl()
void __fort_rbcstl (int src, void * adr, long cnt, long str, int typ, long ilen)
Definition at line 76 of file rw.c.
References __fort_erecv(), __fort_esend(), ent::adr, cnt, cp, e, GET_DIST_LCPU, GET_DIST_TCPUS, ent::ilen, s, src, str, and ent::typ.
Referenced by __fort_get_scalar(), __fort_rbcst(), __fortio_main(), __fortio_stat_bcst(), and ENTFTN().
__fort_realloc()
void * __fort_realloc (void * ptr, size_t n)
Definition at line 50 of file malloc.c.
References __fort_abort(), __fort_zmem, malloc(), n, NULL, p, and ZIP.
Referenced by __fort_grealloc(), __fort_recvl(), __fort_sendl(), ENTFTN(), and merge_ent().
__fort_recvl()
void __fort_recvl (chdr * c, int indx, void * adr, long cnt, long str, int typ, long ilen)
Definition at line 151 of file xfer.c.
References __fort_abort(), __fort_malloc(), __fort_realloc(), ent::adr, CHDR_1DBL, CHDR_1INT, cnt, DEFENTS, ent::ilen, n, r, str, and ent::typ.
Referenced by __fort_copy(), __fort_exchange_counts(), ENTFTN(), mget_recv(), olap_copy(), and olap_recv().
__fort_reduce_section()
void I8() __fort_reduce_section (void * vec1, dtype typ1, int siz1, void * vec2, dtype typ2, int siz2, int cnt, global_reduc_fn fn_g, int dim, F90_Desc * d)
Definition at line 340 of file reduct.c.
References __fort_gfree(), __fort_gmalloc(), __fort_rrecvl(), __fort_rsendl(), __fort_show_index(), __fort_test, a, cnt, cpu(), DEBUG_REDU, DECL_DIM_PTRS, dim, DIST_DPTR_PCOORD_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_PSTRIDE_G, DIST_MAPPED_G, F90_RANK_G, GET_DIST_LCPU, i, I8, LOCAL_MODE, map_to_processor(), MAXDIMS, n, NULL, pc, and SET_DIM_PTRS.
Referenced by __fort_kred_arraylk(), __fort_kred_scalarlk(), __fort_red_array(), __fort_red_arraylk(), __fort_red_scalar(), __fort_red_scalarlk(), ENTFTN(), mmul_mxv(), and mmul_vxm().
__fort_replicate_result()
void I8() __fort_replicate_result (void * vec1, dtype typ1, int siz1, void * vec2, dtype typ2, int siz2, int cnt, F90_Desc * d)
Definition at line 470 of file reduct.c.
References __fort_show_index(), __fort_test, a, broadcast(), cnt, DEBUG_REDU, DECL_DIM_PTRS, DECL_HDR_PTRS, DIST_ALIGN_TARGET_G, DIST_DPTR_BLOCK_G, DIST_DPTR_PCOORD_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_PSTRIDE_G, DIST_DPTR_TLB_G, DIST_INFO_G, DIST_MAPPED_G, DIST_SINGLE_G, F90_RANK_G, GET_DIST_LCPU, i, I8, LOCAL_MODE, MAXDIMS, NULL, pc, RECIP_DIV, RECIP_MOD, SET_DIM_PTRS, t, and td.
Referenced by __fort_kred_arraylk(), __fort_kred_scalarlk(), __fort_red_array(), __fort_red_arraylk(), __fort_red_scalar(), __fort_red_scalarlk(), ENTFTN(), mmul_mxv(), and mmul_vxm().
__fort_reverse_array()
void I8() __fort_reverse_array (char * db, char * ab, F90_Desc * dd, F90_Desc * ad)
Definition at line 2920 of file runtime/flang/dist.c.
References _0, __ASSUMED_GB_EXTENT, __DIST_TARGET_AXIS, __DUMMY_COLLAPSE_PAXIS, __fort_abort(), __PRESCRIPTIVE_DIST_FORMAT, __PRESCRIPTIVE_DIST_TARGET, add(), db(), DECL_DIM_PTRS, DECL_HDR_VARS, DFMT, DFMT_BLOCK, DFMT_BLOCK_K, DFMT_COLLAPSED, DFMT_CYCLIC, DFMT_CYCLIC_K, DFMT_GEN_BLOCK, DIST_DIST_TARGET_G, DIST_DPTR_BLOCK_G, DIST_DPTR_GEN_BLOCK_G, DIST_DPTR_NO_G, DIST_DPTR_PAXIS_G, DIST_DPTR_PO_G, DIST_DPTR_TLB_G, DIST_DPTR_TSTRIDE_G, DIST_DPTR_TUB_G, ENTFTN(), F90_KIND_G, F90_LEN_G, F90_RANK_G, flags, i, kind, len, MAXDIMS, no, rank, s, SET_DIM_PTRS, SET_F90_DIST_DESC_PTR, stride, t, TEMPLATE, and xfer().
__fort_rrecv()
void __fort_rrecv (int cpu, void * adr, long cnt, long str, int typ)
Definition at line 60 of file rw.c.
References __fort_rrecvl(), ent::adr, cnt, cpu(), GET_DIST_SIZE_OF, str, and ent::typ.
Referenced by __fort_crecv(), __fort_pull_them_in(), __fort_stat_term(), __fort_zclose(), __fort_zopen(), and ENTFTN().
__fort_rrecvl()
void __fort_rrecvl (int cpu, void * adr, long cnt, long str, int typ, long ilen)
Definition at line 14 of file rw.c.
References __fort_erecv(), ent::adr, cnt, cpu(), e, ent::ilen, s, str, and ent::typ.
Referenced by __fort_global_reduce(), __fort_passarg(), __fort_passargs(), __fort_reduce_section(), __fort_rrecv(), __io_read(), broadcast(), and gathscat_start().
__fort_rsend()
void __fort_rsend (int cpu, void * adr, long cnt, long str, int typ)
Definition at line 68 of file rw.c.
References __fort_rsendl(), ent::adr, cnt, cpu(), GET_DIST_SIZE_OF, str, and ent::typ.
Referenced by __fort_csend(), __fort_pull_them_in(), __fort_stat_term(), __fort_zclose(), __fort_zopen(), __fort_zwrite(), and ENTFTN().
__fort_rsendl()
void __fort_rsendl (int cpu, void * adr, long cnt, long str, int typ, long ilen)
Definition at line 37 of file rw.c.
References __fort_esend(), ent::adr, cnt, cpu(), e, ent::ilen, s, str, and ent::typ.
Referenced by __fort_global_reduce(), __fort_passarg(), __fort_passargs(), __fort_reduce_section(), __fort_rsend(), __io_read(), broadcast(), and gathscat_start().
__fort_rstchn()
void __fort_rstchn (struct chdr * c)
Definition at line 83 of file xfer.c.
References n.
__fort_sendl()
void __fort_sendl (chdr * c, int indx, void * adr, long cnt, long str, int typ, long ilen)
Definition at line 100 of file xfer.c.
References __fort_abort(), __fort_malloc(), __fort_realloc(), ent::adr, CHDR_1DBL, CHDR_1INT, cnt, DEFENTS, ent::ilen, n, s, str, and ent::typ.
Referenced by __fort_copy(), __fort_exchange_counts(), copy_xfer(), ENTFTN(), mget_send(), olap_copy(), olap_recv(), and olap_send().
__fort_set_alignment()
void I8() __fort_set_alignment (F90_Desc * d, __INT_T dim, __INT_T lbound, __INT_T ubound, __INT_T taxis, __INT_T tstride, __INT_T toffset, ...)
Definition at line 1202 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), __fort_test, d, DEBUG_DIST, DECL_DIM_PTRS, dim, DIST_DPTR_CLB_G, DIST_DPTR_CNO_G, DIST_DPTR_OLB_G, DIST_DPTR_OUB_G, DIST_DPTR_TAXIS_G, DIST_DPTR_TLB_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, DIST_DPTR_TUB_G, DPTR_UBOUND_G, DPTR_UBOUND_P, extent(), F90_DPTR_LBOUND_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_P, F90_DPTR_SOFFSET_P, F90_DPTR_SSTRIDE_P, F90_RANK_G, F90_TAG_G, GET_DIST_LCPU, NULL, and SET_DIM_PTRS.
Referenced by ENTFTN(), ptr_asgn(), and void().
__fort_set_allocation()
void I8() __fort_set_allocation (F90_Desc * d, __INT_T dim, __INT_T no, __INT_T po)
__fort_set_distribution()
void I8() __fort_set_distribution (F90_Desc * d, __INT_T dim, __INT_T lbound, __INT_T ubound, __INT_T paxis, __INT_T * block)
__fort_set_second()
void __fort_set_second (double d)
Definition at line 125 of file stat_linux.c.
References d, and first.
Referenced by ENTFTN().
__fort_set_section()
void I8() __fort_set_section (F90_Desc * d, __INT_T ddim, F90_Desc * a, __INT_T adim, __INT_T l, __INT_T u, __INT_T s)
Definition at line 1475 of file runtime/flang/dist.c.
References __DIST_SET_SECTIONX, a, d, and s.
Referenced by __fort_copy(), cshift_loop(), ENTFTN(), and eoshift_scalar().
__fort_set_single()
void I8() __fort_set_single (F90_Desc * d, F90_Desc * a, __INT_T dim, __INT_T i, _set_single_enum what)
Definition at line 1331 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), __fort_test, __OFF_TEMPLATE, __SINGLE, a, d, DEBUG_DIST, DECL_DIM_PTRS, dim, DIST_DPTR_LOFFSET_G, DIST_PBASE_G, DIST_SCOFF_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_LBASE_G, F90_LBASE_P, F90_RANK_G, F90_TAG_G, GET_DIST_LCPU, idx, k, NULL, and SET_DIM_PTRS.
Referenced by cshift_loop(), ENTF90(), ENTFTN(), and eoshift_loop().
__fort_setarg()
void __fort_setarg (void)
Definition at line 33 of file stat_linux.c.
Referenced by ENTFTN().
__fort_setbase()
void __fort_setbase (chdr * c, char * bases, char * baser, int typ, long ilen)
Definition at line 315 of file xfer.c.
References CHDR_BASE, ent::ilen, and ent::typ.
Referenced by __fort_comm_sked(), and olap_shift().
__fort_sethand()
void __fort_sethand (void)
Definition at line 96 of file hand.c.
References __fort_getopt(), __fort_strtol(), n, NULL, p, q, sigs::sig, and sighand().
Referenced by __fort_begpar().
__fort_stat_arecv()
void __fort_stat_arecv (int cpu, long len, int reqn)
Update start asynch receive message stats.
Definition at line 393 of file stat.c.
References tb::byter, tb::datar, len, and tb1.
Referenced by __fort_entry_arecv().
__fort_stat_arecv_done()
void __fort_stat_arecv_done (int cpu)
Definition at line 402 of file stat.c.
Referenced by __fort_entry_arecv_done().
__fort_stat_asend()
void __fort_stat_asend (int cpu, long len, int reqn)
Definition at line 409 of file stat.c.
References tb::bytes, tb::datas, len, and tb1.
Referenced by __fort_entry_asend().
__fort_stat_asend_done()
void __fort_stat_asend_done (int cpu)
Definition at line 418 of file stat.c.
Referenced by __fort_entry_asend_done().
__fort_stat_await()
void __fort_stat_await (int reqn)
Definition at line 425 of file stat.c.
Referenced by __fort_entry_await().
__fort_stat_await_done()
void __fort_stat_await_done (int reqn)
Definition at line 432 of file stat.c.
Referenced by __fort_entry_await_done().
__fort_stat_copy()
void __fort_stat_copy (long len)
Update start bcopy message stats.
Parameters
len total length in bytes
Definition at line 379 of file stat.c.
References tb::bytec, tb::datac, len, and tb1.
Referenced by __fort_entry_copy().
__fort_stat_copy_done()
void __fort_stat_copy_done (void)
Update done bcopy message stats.
Definition at line 387 of file stat.c.
Referenced by __fort_entry_copy_done().
__fort_stat_function_entry()
void __fort_stat_function_entry (int line, int lines, int cline, char * func, char * file, int funcl, int filel)
Function entry
Definition at line 449 of file stat.c.
Referenced by ENTFTN().
__fort_stat_function_exit()
void __fort_stat_function_exit (void)
Function exit
Definition at line 464 of file stat.c.
Referenced by ENTFTN().
__fort_stat_init()
int __fort_stat_init (void)
Begin stats.
Definition at line 54 of file stat.c.
References __fort_gettb(), and tb0.
Referenced by __fort_entry_init().
__fort_stat_line_entry()
void __fort_stat_line_entry (int line)
Line entry
Definition at line 457 of file stat.c.
Referenced by ENTFTN().
__fort_stat_recv()
void __fort_stat_recv (int cpu, long len)
Definition at line 342 of file stat.c.
References tb::byter, tb::datar, len, and tb1.
Referenced by __fort_entry_recv().
__fort_stat_recv_done()
void __fort_stat_recv_done (int cpu)
Update done receive message stats.
Definition at line 352 of file stat.c.
Referenced by __fort_entry_recv_done().
__fort_stat_send()
void __fort_stat_send (int cpu, long len)
Update start send message stats.
Parameters
cpu receiving cpu
len total length in bytes
Definition at line 361 of file stat.c.
References tb::bytes, tb::datas, len, and tb1.
Referenced by __fort_entry_send().
__fort_stat_send_done()
void __fort_stat_send_done (int cpu)
Update done send message stats.
Parameters
cpu - receiving cpu
Definition at line 371 of file stat.c.
Referenced by __fort_entry_send_done().
__fort_stat_term()
void __fort_stat_term (void)
Print stats (called by all cpus)
Definition at line 295 of file stat.c.
References __fort_gettb(), __fort_gfree(), __fort_gmalloc(), __fort_is_ioproc(), __fort_rrecv(), __fort_rsend(), __UCHAR, cpu(), GET_DIST_IOPROC, GET_DIST_QUIET, GET_DIST_TCPUS, tb::gsbrk, i, mem(), msg(), Q_CPU, Q_CPUS, Q_MEM, Q_MEMS, Q_MSG, Q_MSGS, tb::r, tb::s, tb::sbrk, tb0, tb1, and tb::u.
Referenced by __fort_entry_term().
__fort_store_int()
void I8() __fort_store_int (void * b, F90_Desc * d, int val)
Definition at line 85 of file util.c.
References __DESC, __fort_abort(), __INT1, __INT2, __INT4, __INT8, __OFF_TEMPLATE, Abs, b, d, DIST_SCOFF_G, F90_FLAGS_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, kind, and val.
__fort_store_int_element()
void I8() __fort_store_int_element (void * b, F90_Desc * d, int i, int val)
Definition at line 217 of file util.c.
References __fort_abort(), __fort_local_address(), __INT1, __INT2, __INT4, __INT8, b, d, F90_DIM_LBOUND_G, F90_KIND_G, F90_RANK_G, i, I8, idx, NULL, and val.
Referenced by ENTFTN().
__fort_store_int_vector()
void I8() __fort_store_int_vector (void * b, F90_Desc * d, int * vec, int veclen)
Definition at line 280 of file util.c.
References __fort_abort(), __fort_local_address(), __INT1, __INT2, __INT4, __INT8, b, d, F90_DIM_LBOUND_G, F90_KIND_G, F90_RANK_G, i, I8, NULL, and vec.
__fort_store_log()
void I8() __fort_store_log (void * b, F90_Desc * d, int val)
Definition at line 151 of file util.c.
References __DESC, __fort_abort(), __LOG1, __LOG2, __LOG4, __LOG8, __OFF_TEMPLATE, Abs, b, d, DIST_SCOFF_G, F90_FLAGS_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_TRUE_LOG1, GET_DIST_TRUE_LOG2, GET_DIST_TRUE_LOG4, GET_DIST_TRUE_LOG8, kind, and val.
__fort_stored_alike()
int I8() __fort_stored_alike (F90_Desc * dd, F90_Desc * sd)
Referenced by __fort_kred_arraylk(), __fort_kred_scalarlk(), __fort_red_array(), __fort_red_arraylk(), __fort_red_scalar(), __fort_red_scalarlk(), and ENTFTN().
__fort_strtol()
long __fort_strtol (const char * str, char ** ptr, int base)
Definition at line 39 of file atol.c.
References base, end, FLANG_FALLTHROUGH, NULL, str, and val.
Referenced by __fort_getoptn(), __fort_initcom(), __fort_sethand(), and __fort_trac_init().
__fort_trac_arecv()
void __fort_trac_arecv (int cpu, long len, int reqn)
Definition at line 11 of file trace2.c.
Referenced by __fort_entry_arecv().
__fort_trac_arecv_done()
void __fort_trac_arecv_done (int cpu)
Definition at line 18 of file trace2.c.
__fort_trac_asend()
void __fort_trac_asend (int cpu, long len, int reqn)
Definition at line 25 of file trace2.c.
Referenced by __fort_entry_asend().
__fort_trac_asend_done()
void __fort_trac_asend_done (int cpu)
Definition at line 32 of file trace2.c.
Referenced by __fort_entry_asend_done().
__fort_trac_await()
void __fort_trac_await (int reqn)
Definition at line 39 of file trace2.c.
Referenced by __fort_entry_await().
__fort_trac_await_done()
void __fort_trac_await_done (int reqn)
Definition at line 46 of file trace2.c.
Referenced by __fort_entry_await_done().
__fort_trac_copy()
void __fort_trac_copy (long len)
Update start bcopy message stats.
Parameters
len total length in bytes
Definition at line 98 of file flang/trace.c.
Referenced by __fort_entry_copy().
__fort_trac_copy_done()
void __fort_trac_copy_done (void)
Update done bcopy message stats.
Definition at line 104 of file flang/trace.c.
Referenced by __fort_entry_copy_done().
__fort_trac_function_entry()
void __fort_trac_function_entry (int line, int lines, int cline, DCHAR(func) , DCHAR(file) DCLEN64(funcl) DCLEN64(filel))
Referenced by ENTFTN().
__fort_trac_function_exit()
void __fort_trac_function_exit (void)
Function exit
Definition at line 111 of file flang/trace.c.
References call_level.
Referenced by ENTFTN().
__fort_trac_init()
int __fort_trac_init (void)
Initialization.
Definition at line 16 of file flang/trace.c.
References __fort_abort(), __fort_getopt(), __fort_strtol(), GET_DIST_LCPU, GET_DIST_TCPUS, n, p, q, and tracing.
Referenced by __fort_entry_init().
__fort_trac_line_entry()
void __fort_trac_line_entry (int line)
line entry
Parameters
line - current line number
Definition at line 56 of file flang/trace.c.
Referenced by ENTFTN().
__fort_trac_recv()
void __fort_trac_recv (int cpu, long len)
Update start receive message stats.
Parameters
cpu sending cpu
len total length in bytes
Definition at line 65 of file flang/trace.c.
Referenced by __fort_entry_recv().
__fort_trac_recv_done()
void __fort_trac_recv_done (int cpu)
Update done receive message stats.
Parameters
cpu - sending cpu
Definition at line 73 of file flang/trace.c.
Referenced by __fort_entry_arecv_done(), and __fort_entry_recv_done().
__fort_trac_send()
void __fort_trac_send (int cpu, long len)
Update start send message stats.
Parameters
cpu sending cpu
len total length in bytes
Definition at line 82 of file flang/trace.c.
Referenced by __fort_entry_send().
__fort_trac_send_done()
void __fort_trac_send_done (int cpu)
Update done send message stats.
Parameters
cpu - receiving cpu
Definition at line 90 of file flang/trace.c.
Referenced by __fort_entry_send_done().
__fort_trac_term()
void __fort_trac_term (void)
Termination.
Definition at line 118 of file flang/trace.c.
Referenced by __fort_entry_term().
__fort_traceback()
void __fort_traceback (void)
Definition at line 144 of file entry.c.
References buf, pent::cline, pent::file, pent::filel, pent::func, pent::funcl, GET_DIST_LCPU, LINENO, p, pentb, pentc, strlen(), and write.
Referenced by __fort_abortx(), and ENTFTN().
__fort_tracecall()
void __fort_tracecall (const char * msg)
Definition at line 183 of file entry.c.
References buf, pent::cline, pent::file, pent::filel, pent::func, pent::funcl, GET_DIST_LCPU, LINENO, msg(), p, pentb, pentc, strlen(), and write.
Referenced by ENTFTN().
__fort_use_allocation()
void I8() __fort_use_allocation (F90_Desc * d, __INT_T dim, __INT_T no, __INT_T po, F90_Desc * a)
Definition at line 1245 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), __fort_test, __LOCAL, __TEMPLATE, a, d, DEBUG_DIST, DECL_DIM_PTRS, dim, DIST_DPTR_COFSTR_G, DIST_DPTR_COFSTR_P, DIST_DPTR_LAB_G, DIST_DPTR_LAB_P, DIST_DPTR_NO_G, DIST_DPTR_NO_P, DIST_DPTR_OLB_G, DIST_DPTR_OUB_G, DIST_DPTR_PO_G, DIST_DPTR_PO_P, DIST_DPTR_UAB_G, DIST_DPTR_UAB_P, DIST_NONSEQUENCE_G, DIST_NONSEQUENCE_P, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_FLAGS_P, F90_RANK_G, F90_TAG_G, GET_DIST_LCPU, k, no, NULL, and SET_DIM_PTRS.
Referenced by ptr_asgn().
__fort_varying_int()
int I8() __fort_varying_int (void * b, __INT_T * size)
Definition at line 15 of file util.c.
References __fort_abort(), b, and size.
Referenced by __CLEN_T(), __INT8_T(), __INT_T(), ENTF90(), and ENTFTN().
__fort_varying_log()
int I8() __fort_varying_log (void * b, __INT_T * size)
Definition at line 34 of file util.c.
References __fort_abort(), b, GET_DIST_MASK_LOG1, GET_DIST_MASK_LOG2, GET_DIST_MASK_LOG4, GET_DIST_MASK_LOG8, and size.
Referenced by __INT1_T(), __INT2_T(), __INT4_T(), __INT8_T(), __INT_T(), __LOG1_T(), __LOG2_T(), __LOG4_T(), __LOG8_T(), __REAL16_T(), __REAL4_T(), __REAL8_T(), ENTF90(), and ENTFTN().
__fort_zopen()
void __fort_zopen (char * path)
Definition at line 49 of file buffer.c.
References __fort_abortp(), __fort_gmalloc(), __fort_rrecv(), __fort_rsend(), __UCHAR, buf, bufe, bufp, fd, GET_DIST_IOPROC, GET_DIST_LCPU, MAXBUF, n, off, path, s, and write.
Referenced by __fort_pull_them_in().
compute_lstride()
int compute_lstride (F90_Desc * d, int dim)
ENTCOMN() [1/3]
__INT_T ENTCOMN (0 , 0)
ENTCOMN() [2/3]
__STR_T ENTCOMN (0C , 0c)
ENTCOMN() [3/3]
__INT_T ENTCOMN (LOCAL_MODE , local_mode)
ENTF90() [1/4]
void ENTF90 (TEMPLATE , template)
ENTF90() [2/4]
void __INT_T __INT_T __INT_T __INT_T void ENTF90 (TEMPLATE1 , template1)
ENTF90() [3/4]
void ENTF90 (TEMPLATE2 , template2)
ENTF90() [4/4]
void ENTF90 (TEMPLATE3 , template3)
ENTFTN() [1/4]
void F90_Desc __INT_T __INT_T __INT_T void __INT_T __INT_T void F90_Desc __LOG_T ENTFTN (ASSOCIATED , associated)
ENTFTN() [2/4]
void ENTFTN (INSTANCE , instance)
ENTFTN() [3/4]
void F90_Desc __INT_T __INT_T __INT_T void __INT_T __INT_T void ENTFTN (SECT , sect)
ENTFTN() [4/4]
void F90_Desc __INT_T __INT_T __INT_T void ENTFTN (TEMPLATE , template)
is_nonsequential_section()
__INT_T I8() is_nonsequential_section (F90_Desc * a, __INT_T dim)
check if a descriptor is associated with a non-contiguous section.
Parameters
a is the descriptor we are checking.
dim is the rank of the array we are checking.
Returns
0 if contiguous, else the dimension that is non-contiguous.
Definition at line 231 of file rdst.c.
References a, DECL_DIM_PTRS, dim, F90_DPTR_EXTENT_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, i, and SET_DIM_PTRS.
Referenced by __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), ENTF90(), ENTFTN(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
Variable Documentation
__fort_entry_mflag
int __fort_entry_mflag extern
Definition at line 46 of file entry.c.
Referenced by __fort_entry_init(), and __fort_entry_term().
__fort_mask_int1
__INT1_T __fort_mask_int1 extern
Definition at line 374 of file const.c.
__fort_mask_int2
__INT2_T __fort_mask_int2 extern
Definition at line 375 of file const.c.
__fort_mask_int4
__INT4_T __fort_mask_int4 extern
Definition at line 376 of file const.c.
__fort_mask_int8
__INT8_T __fort_mask_int8 extern
Definition at line 377 of file const.c.
__fort_mask_log
__LOG_T __fort_mask_log extern
Definition at line 368 of file const.c.
Referenced by __fort_init_consts().
__fort_mask_log1
__LOG1_T __fort_mask_log1 extern
Definition at line 370 of file const.c.
__fort_mask_log2
__LOG2_T __fort_mask_log2 extern
Definition at line 371 of file const.c.
__fort_mask_log4
__LOG4_T __fort_mask_log4 extern
Definition at line 372 of file const.c.
__fort_mask_log8
__LOG8_T __fort_mask_log8 extern
Definition at line 373 of file const.c.
__fort_maxs
void* __fort_maxs[__NTYPES] extern
Definition at line 152 of file const.c.
__fort_mins
void* __fort_mins[__NTYPES] extern
Definition at line 215 of file const.c.
__fort_one
long long int __fort_one[4] extern
Definition at line 134 of file const.c.
__fort_shifts
int __fort_shifts[__NTYPES] extern
Definition at line 21 of file const.c.
Referenced by __fort_init_consts().
__fort_size_of
int __fort_size_of[__NTYPES] extern
Definition at line 25 of file const.c.
Referenced by __fort_init_consts(), __get_size_of(), and get_source_and_dest_sizes().
__fort_transnam
const char* __fort_transnam extern
Definition at line 19 of file init.c.
__fort_true_log
__LOG_T __fort_true_log extern
Definition at line 314 of file const.c.
Referenced by __fort_init_consts().
__fort_true_log1
__LOG1_T __fort_true_log1 extern
Definition at line 315 of file const.c.
__fort_true_log2
__LOG2_T __fort_true_log2 extern
Definition at line 316 of file const.c.
__fort_true_log4
__LOG4_T __fort_true_log4 extern
Definition at line 317 of file const.c.
__fort_true_log8
__LOG8_T __fort_true_log8 extern
Definition at line 318 of file const.c.
__fort_trues
void* __fort_trues[__NTYPES] extern
Definition at line 330 of file const.c.
Referenced by __fort_init_consts().
__fort_typenames
const char* __fort_typenames[__NTYPES] extern
Definition at line 73 of file const.c.
__fort_units
void* __fort_units[__NTYPES] extern
Definition at line 275 of file const.c.
__fort_zed
long long int __fort_zed[4] extern
Definition at line 135 of file const.c.
a
void F90_Desc __INT_T __INT_T __INT_T void __INT_T __INT_T void F90_Desc* a
Definition at line 1727 of file fioMacros.h.
Referenced by __attribute__(), __builtin_abs(), __builtin_acos(), __builtin_acosf(), __builtin_asin(), __builtin_asinf(), __builtin_atan(), __builtin_atan2(), __builtin_atan2f(), __builtin_atanf(), __builtin_ceil(), __builtin_ceilf(), __builtin_cimag(), __builtin_cimagf(), __builtin_conj(), __builtin_conjf(), __builtin_cos(), __builtin_cosf(), __builtin_cosh(), __builtin_coshf(), __builtin_creal(), __builtin_crealf(), __builtin_exp(), __builtin_expf(), __builtin_fabs(), __builtin_fabsf(), __builtin_floor(), __builtin_floorf(), __builtin_log(), __builtin_log10(), __builtin_log10f(), __builtin_logf(), __builtin_pow(), __builtin_sin(), __builtin_sinf(), __builtin_sinh(), __builtin_sinhf(), __builtin_sqrt(), __builtin_sqrtf(), __builtin_tan(), __builtin_tanf(), __builtin_tanh(), __builtin_tanhf(), __builtin_trunc(), __builtin_truncf(), __double_as_ll(), __exp_d_scalar_kernel(), __exp_scalar_kernel(), __float_as_int(), __fort_comm_merge(), __fort_reduce_section(), __fort_replicate_result(), __fort_set_section(), __fort_set_sectionx(), __fort_set_single(), __fort_use_allocation(), __fsd_acos_fma3(), __fsd_asin_fma3(), __fsd_exp_fma3(), __fsd_log_fma3(), __fsd_pow_fma3(), __fss_acos_fma3(), __fss_asin_fma3(), __fss_atan_fma3(), __fss_exp_fma3(), __fss_pow_fma3(), __fvd_acos_fma3(), __fvd_acos_fma3_256(), __fvd_asin_fma3(), __fvd_asin_fma3_256(), __fvd_exp_fma3(), __fvd_exp_fma3_256(), __fvd_log_fma3(), __fvd_log_fma3_256(), __fvd_pow_fma3(), __fvd_pow_fma3_256(), __fvs_acos_fma3(), __fvs_acos_fma3_256(), __fvs_asin_fma3(), __fvs_asin_fma3_256(), __fvs_atan_fma3(), __fvs_atan_fma3_256(), __fvs_exp_fma3(), __fvs_exp_fma3_256(), __fvs_log_fma3(), __fvs_log_fma3_256(), __int_as_float(), __INT_T(), __internal_fast_int2dbl(), __ldexp_d_scalar_kernel(), __ldexpf_scalar_kernel(), __ll_as_double(), __mth_i_dsign(), __mth_i_dsincos(), __mth_i_kdiv(), __mth_i_qsign(), __mth_i_sign(), __mth_i_sincos(), __mth_i_ukdiv(), __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), __pgm_exp_d_vec512_slowpath(), __pgm_exp_vec128_slowpath(), __pgm_exp_vec256_slowpath(), __pgm_exp_vec512_slowpath(), __reduction_slowpath(), __reduction_slowpath_pio2(), __rss_log_fma3(), __rvs_log_fma3(), __rvs_log_fma3_256(), __tan_f_vec(), __tan_kernel(), __unf_init(), _cr_nme(), _find_pointer_assignments_f90(), _findrefs(), _int_mult_upper(), _PDsize(), _pghpf_bound(), _ptrassign(), _RTE_size(), _transform_func(), add_bound_assignments(), add_fg(), add_subscript_list(), addclasses(), align_unconstrained(), assn_static_off(), assn_stkoff(), bld_lhs(), bld_use(), build_array_list(), build_array_reference(), bv_copy(), bv_intersect(), bv_intersect3(), bv_mem(), bv_notequal(), bv_off(), bv_set(), bv_sub(), bv_union(), bv_zero(), ceilg(), cexp_scalar_default_abi(), chk_assumed_subscr(), chkstruct(), CMPLXFUNC_C(), compar_tids(), complex_alias(), Conflict_(), constant_stride(), constants_equal(), convert_subscript(), convert_template_instance(), copy_desc_to_bnds_vars(), cpu(), dastli(), decimal_value_from_oct(), decompose_expression(), do_equiv(), dotp_cplx16(), dotp_cplx8(), dotp_int1(), dotp_int2(), dotp_int4(), dotp_int8(), dotp_log1(), dotp_log2(), dotp_log4(), dotp_log8(), dotp_real8(), double_as_ll(), dump_ast_tree(), eadd1(), eaddm(), ecmp(), ecmpm(), ediv(), eliminate_extra_idx(), emit_copy_section(), emit_gatherx(), emit_get_scalar(), emit_get_scalar_sub(), emit_overlap(), emit_permute_section(), emov(), emovi(), emovo(), emovz(), emul(), emulm(), ENT3F(), ENTF90(), ENTFTN(), esub(), esubm(), export_one_ast(), extent_of_shape(), fastset_unit_tests(), fill_argt_with_alnd(), fill_pointer_array_dtype(), find_base(), find_section_subscript(), float_as_int(), floorg(), for(), forall_2_sec(), fti(), ftn_i_ddim(), ftn_i_dim(), ftn_i_idim(), gathscat_maxval_int1(), gathscat_maxval_int2(), gathscat_maxval_int4(), gathscat_maxval_int8(), gathscat_maxval_real16(), gathscat_maxval_real4(), gathscat_maxval_real8(), gathscat_minval_int1(), gathscat_minval_int2(), gathscat_minval_int4(), gathscat_minval_int8(), gathscat_minval_real16(), gathscat_minval_real4(), gathscat_minval_real8(), gcd(), gen_cmplx_mul(), gen_copy_out(), generate_get_scalar(), get_acl(), get_all_descriptors(), get_finfo(), get_lhs_first_defs(), get_omnipotent_pointer(), get_tbaa_metadata(), handle_arguments(), hash_binop(), hash_cmplxc(), hash_conv(), hash_mem(), hash_paren(), hash_subscr(), hash_substr(), hash_sym(), hash_triple(), hash_unop(), hash_val(), if(), increase_shape(), init_points_to_anal(), insert_comm_before(), insert_forall_comm(), int_as_float(), intermediate_members(), ipa_ast(), is_contains_ast_between(), is_duplicate(), is_idx(), is_indirection_in_it(), is_legal_lhs(), is_legal_lhs_for_mask(), is_nonscalar_indirection_in_it(), is_nonsequential_section(), is_one_idx_for_dim(), is_safe_copy(), is_scalar(), is_std_hoistable(), is_structured(), is_triplet(), is_use_lhs(), is_use_lhs_final(), is_vector_indirection_in_it(), is_vector_subscript(), itf(), left_array_symbol(), ll_as_double(), locset_to_tbaa_info(), lower(), lower_function(), lower_parenthesize_expression(), lower_symbol(), m16m(), make_address_for_ast(), make_sec_from_ast_chk(), mark(), markmodified(), matched_dim(), mdnode_equal(), memsym_of_ast(), merge_ent(), mk_allocate_scalar(), mk_ceil_div(), mk_deallocate_scalar(), mk_elem_init_intrinsic(), mk_reshape_intrin(), mk_zbase_expr(), mkexpr_assign_temp(), mmul_cplx16(), mmul_cplx8(), my_fmaf(), neg(), no_comm_class(), opt_ast(), overlap_class(), pass_sym_of_ast(), points_to_anal(), process_rhs_sub(), put_memsym_of_ast(), put_ncharstring_n(), putast(), putstdassigns(), putzero(), read_init(), reduc_shape(), reduction_slowpath(), reference_for_temp(), rewrite_calls(), scalar_communication(), scatter_maxval_int1(), scatter_maxval_int2(), scatter_maxval_int4(), scatter_maxval_int8(), scatter_maxval_real16(), scatter_maxval_real4(), scatter_maxval_real8(), scatter_minval_int1(), scatter_minval_int2(), scatter_minval_int4(), scatter_minval_int8(), scatter_minval_real16(), scatter_minval_real4(), scatter_minval_real8(), semant2(), set_assumed_bounds(), simple_reference_for_temp(), size_shape(), string_cmp(), string_equals(), sym_is_refd(), symbolic_mul(), symvalue(), tag_comms(), tag_forall_comm(), transform_all_call(), types_equal(), umad32wide(), vfixup_vd_vd_vd_vi2_i(), vfixup_vf_vf_vf_vi2_i(), write_master_entry_routine(), xucmp(), and ZMPLXFUNC_Z().
CORMEM
__INT_T CORMEM[] extern
f90DummyGenBlock
__INT_T f90DummyGenBlock extern
Definition at line 18 of file defs.c.
Referenced by ENTFTN().
f90DummyGenBlockPtr
__INT_T* f90DummyGenBlockPtr extern
Definition at line 19 of file defs.c.
p_collapse
void F90_Desc __INT_T __INT_T __INT_T* p_collapse
Definition at line 1725 of file fioMacros.h.
p_flags
void __INT_T * p_flags
Definition at line 1726 of file fioMacros.h.
Referenced by ENTF90(), ENTFTN(), and void().
p_kind
void __INT_T __INT_T * p_kind
Definition at line 1725 of file fioMacros.h.
Referenced by ENTF90(), and ENTFTN().
p_l1
void __INT_T __INT_T __INT_T __INT_T * p_l1
Definition at line 1732 of file fioMacros.h.
Referenced by ENTF90().
p_l2
void __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T * p_l2
Definition at line 1733 of file fioMacros.h.
Referenced by ENTF90().
p_l3
void __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T* p_l3
Definition at line 1734 of file fioMacros.h.
Referenced by ENTF90().
p_len
void __INT_T __INT_T __INT_T * p_len
Definition at line 1725 of file fioMacros.h.
Referenced by ENTF90(), and ENTFTN().
p_rank
void __INT_T * p_rank
Definition at line 1726 of file fioMacros.h.
Referenced by ENTF90(), ENTFTN(), and void().
p_u1
void __INT_T __INT_T __INT_T __INT_T __INT_T * p_u1
Definition at line 1732 of file fioMacros.h.
Referenced by ENTF90().
p_u2
void __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T * p_u2
Definition at line 1733 of file fioMacros.h.
Referenced by ENTF90().
p_u3
void __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T __INT_T* p_u3
Definition at line 1734 of file fioMacros.h.
Referenced by ENTF90().
pd
void *char F90_Desc * pd
Definition at line 1728 of file fioMacros.h.
Referenced by __fort_describe_replication(), __fort_localize(), __INT8_T(), __INT_T(), can_find_dtype(), copy_xfer(), ENTF90(), ENTFTN(), finddthash(), import(), install_dtype(), new_dtype(), new_dtypes(), new_installed_dtype(), proc_setup(), and recopy().
tb
void *char F90_Desc char * tb
Definition at line 1728 of file fioMacros.h.
Referenced by handle_shift(), and mmul().
td
void *char F90_Desc char F90_Desc * td
Definition at line 1725 of file fioMacros.h.
Referenced by __fort_conform(), __fort_replicate_result(), ENTF90(), ENTFTN(), has_intrin_type(), make_keyword_str(), sourced_alloc_and_assign(), sourced_alloc_and_assign_array(), sourced_alloc_and_assign_array_from_scalar(), vcvtsi64_vd_vi2(), and void().