flang: semant.h File Reference
flang1/flang1exe/semant.h File Reference
Semantic analyzer data definitions.
Classes
struct type_list
struct FLITM
struct _std_range
struct _std_record
struct xyyz
struct DOINFO
struct reduc_sym
struct reduc_tag
struct noscope_sym
struct DOIF
struct var_init
struct _acl
struct _aexpr
struct STSK
struct equiv_var
struct _seql
struct _accl
struct INTERF
struct argpos_t
struct DOSTACK
struct scope_sym_tag
struct SCOPESTACK
struct SEM_DIM_SPECS
struct SEM_DIM_SPECS::_sem_bounds
struct SEM_DIM_SPECS::_sem_arrdim
struct IFACE
Deferred procedure interface.
struct ident_proc_list
struct ident_list
struct SEM
Macros
#define S_NULL 0 /* empty/invalid */
#define S_CONST 1 /* scalar constant */
#define S_EXPR 2 /* expression */
#define S_LVALUE 3 /* non-whole variable */
#define S_LOGEXPR 4 /* (obsolete; was logical expression) */
#define S_STAR 5 /* * */
#define S_VAL 6 /* %VAL(expr) argument (VMS) */
#define S_IDENT 7 /* identifier, possibly a whole variable */
#define S_LABEL 8 /* label */
#define S_STFUNC 9 /* statement function reference */
#define S_REF 10 /* %REF(expr) argument (VMS)*/
#define S_TRIPLE 11 /* j:k:m */
#define S_KEYWORD 12 /* keyword, not an identifier */
#define S_ACONST 13 /* array constant */
#define S_SCONST 14 /* structure constant */
#define S_DERIVED 15 /* derived type object */
#define POW1 1
#define POW2 2
#define RADIX2 2 /* Binary */
#define NOT_GET_VAL 0 /* 0 is default, This should be ruled out */
#define NO_REAL -5 /* if the processor supports no real type with radix RADIX */
#define KEYWD_ARGS2 2
#define DT_IO_UNKNOWN 0x0 /* Not yet known if derived type has defined I/O */
#define DT_IO_NONE 0x1 /* No defined I/O for derived type */
#define DT_IO_FREAD 0x2 /* Defined READ(FORMATTED) */
#define DT_IO_UREAD 0x4 /* Defined READ(UNFORMATTED) */
#define DT_IO_FWRITE 0x8 /* Defined WRITE(FORMATTED) */
#define DT_IO_UWRITE 0x10 /* Defined WRITE(UNFORMATTED) */
#define DT_HAS_IO_FREAD(dt) (((UFIOG(DTY(dt + 3)) & DT_IO_FREAD)))
#define DT_HAS_IO_UREAD(dt) (((UFIOG(DTY(dt + 3)) & DT_IO_UREAD)))
#define DT_HAS_IO_FWRITE(dt) (((UFIOG(DTY(dt + 3)) & DT_IO_FWRITE)))
#define DT_HAS_IO_UWRITE(dt) (((UFIOG(DTY(dt + 3)) & DT_IO_UWRITE)))
#define DT_HAS_IO(dt) ((UFIOG(DTY(dt + 3))))
#define NEW_INTRIN 65535 /* (newer) intrinsic with no predefined entry in the symtab */
#define DBG_LEXBLK flg.debug && !flg.vect && !XBIT(34, 0x200) && !XBIT(123, 0x400)
#define ITEM_END ((ITEM *)1)
#define DI_SCH_STATIC 0
#define DI_SCH_DYNAMIC 1
#define DI_SCH_GUIDED 2
#define DI_SCH_INTERLEAVE 3
#define DI_SCH_RUNTIME 4
#define DI_SCH_AUTO 5
#define DI_SCH_DIST_STATIC 6
#define DI_SCH_DIST_DYNAMIC 7
#define DI_ID(d) sem.doif_base[d].Id
#define DI_LINENO(d) sem.doif_base[d].lineno
#define DI_NEST(d) sem.doif_base[d].nest
#define DI_NAME(d) sem.doif_base[d].name
#define DI_EXIT_LABEL(d) sem.doif_base[d].exit_label
#define DI_DO_LABEL(d) sem.doif_base[d].u.u1.do_label
#define DI_CYCLE_LABEL(d) sem.doif_base[d].u.u1.cycle_label
#define DI_TOP_LABEL(d) sem.doif_base[d].u.u1.top_label
#define DI_DO_AST(d) sem.doif_base[d].u.u1.ast
#define DI_DOINFO(d) sem.doif_base[d].u.u1.doinfo
#define DI_DO_POPINDEX(d) sem.doif_base[d].u.u1.popindex
#define DI_CONC_SYMAVL(d) sem.doif_base[d].u.u1.symavl
#define DI_CONC_COUNT(d) sem.doif_base[d].u.u1.count
#define DI_CONC_KIND(d) sem.doif_base[d].u.u1.kind
#define DI_CONC_NO_DEFAULT(d) sem.doif_base[d].u.u1.no_default
#define DI_CONC_BLOCK_SYM(d) sem.doif_base[d].u.u1.block_sym
#define DI_CONC_SYMS(d) sem.doif_base[d].u.u1.syms
#define DI_CONC_LAST_SYM(d) sem.doif_base[d].u.u1.last_sym
#define DI_CONC_LABEL_SYMS(d) sem.doif_base[d].u.u1.label_syms
#define DI_CONC_ERROR_SYMS(d) sem.doif_base[d].u.u1.error_syms
#define DI_CONC_MASK_STD(d) sem.doif_base[d].u.u1.mask_std
#define DI_CONC_BODY_STD(d) sem.doif_base[d].u.u1.body_std
#define DI_SHAPEDIM(d) sem.doif_base[d].u.u2.shapedim
#define DI_MASKED(d) sem.doif_base[d].u.u2.masked
#define DI_CASE_EXPR(d) sem.doif_base[d].u.u3.case_expr
#define DI_DTYPE(d) sem.doif_base[d].u.u3.dtype
#define DI_BEG_DEFAULT(d) sem.doif_base[d].u.u3.beg_default
#define DI_END_DEFAULT(d) sem.doif_base[d].u.u3.end_default
#define DI_SWEL_HD(d) sem.doif_base[d].u.u3.swel_hd
#define DI_ALLO_CHTMP(d) sem.doif_base[d].u.u3.allo_chtmp
#define DI_DEFAULT_SEEN(d) sem.doif_base[d].u.u3.default_seen
#define DI_DEFAULT_COMPLETE(d) sem.doif_base[d].u.u3.default_complete
#define DI_PENDING(d) sem.doif_base[d].u.u3.pending
#define DI_BPAR(d) sem.doif_base[d].u.u4.bpar
#define DI_BTARGET(d) sem.doif_base[d].u.u4.target
#define DI_BTEAMS(d) sem.doif_base[d].u.u4.teams
#define DI_BDISTRIBUTE(d) sem.doif_base[d].u.u4.distribute
#define DI_CRITSYM(d) sem.doif_base[d].u.u4.bpar
#define DI_BEGINP(d) sem.doif_base[d].u.u4.beginp
#define DI_REDUC(d) sem.doif_base[d].u.u4.reduc
#define DI_LASTPRIVATE(d) sem.doif_base[d].u.u4.lastprivate
#define DI_ALLOCATED(d) sem.doif_base[d].u.u4.allocated
#define DI_REGIONVARS(d) sem.doif_base[d].u.u4.region_vars
#define DI_SCHED_TYPE(d) sem.doif_base[d].u.u4.v.v1.sched_type
#define DI_CHUNK(d) sem.doif_base[d].u.u4.v.v1.chunk
#define DI_DISTCHUNK(d) sem.doif_base[d].u.u4.v.v1.dist_chunk
#define DI_IS_ORDERED(d) sem.doif_base[d].u.u4.v.v1.is_ordered
#define DI_ISSIMD(d) sem.doif_base[d].u.u4.v.v1.is_simd
#define DI_SECT_CNT(d) sem.doif_base[d].u.u4.v.v2.sect_cnt
#define DI_SECT_VAR(d) sem.doif_base[d].u.u4.v.v2.sect_var
#define DI_NOSCOPE_BASE(d) sem.doif_base[d].no_scope_base
#define DI_NOSCOPE_SIZE(d) sem.doif_base[d].no_scope_size
#define DI_NOSCOPE_AVL(d) sem.doif_base[d].no_scope_avail
#define DI_NOSCOPE_FORALL(d) sem.doif_base[d].no_scope_forall
#define DI_SELECTOR(d) sem.doif_base[d].u.u5.selector
#define DI_IS_WHOLE(d) sem.doif_base[d].u.u5.is_whole
#define DI_ACTIVE_SPTR(d) sem.doif_base[d].u.u5.active_sptr
#define DI_END_SELECT_LABEL(d) sem.doif_base[d].u.u5.end_select_label
#define DI_TYPE_BEG(d) sem.doif_base[d].u.u5.beg_std
#define DI_CLASS_DEFAULT_LABEL(d) sem.doif_base[d].u.u5.class_default_label
#define DI_SELECT_TYPE_LIST(d) sem.doif_base[d].u.u5.types
#define DI_FORALL_LASTSTD(d) sem.doif_base[d].u.u6.laststd
#define DI_FORALL_SYMAVL(d) sem.doif_base[d].u.u6.symavl
#define DI_FORALL_DTYPE(d) sem.doif_base[d].u.u6.dtype
#define DI_IDXLIST(d) sem.doif_base[d].u.u6.idxlist
#define DI_FORALL_AST(d) sem.doif_base[d].u.u6.forall_ast
#define DI_ASSOCIATIONS(d) sem.doif_base[d].u.u7.sptrs
#define DI_ENCL_BLOCK_SCOPE(d) sem.doif_base[d].u.u8.encl_block_scope
#define onel 1ULL
#define DI_B(t) (onel << (t))
#define DI_IN_NEST(d, t) (d && d <= sem.doif_depth && (DI_NEST(d) & DI_B(t)))
#define NEED_DOIF(df, typ)
#define Dostart 0
#define Doend 1
#define Varref 2
#define AC_IDENT 1
#define AC_CONST 2
#define AC_EXPR 3 /* SST expr */
#define AC_IEXPR 4 /* AC expression */
#define AC_AST 5
#define AC_IDO 6
#define AC_REPEAT 7
#define AC_ACONST 8
#define AC_SCONST 9
#define AC_LIST 10 /* only used during DATA stmt processing */
#define AC_VMSSTRUCT 11
#define AC_VMSUNION 12
#define AC_TYPEINIT 13
#define AC_ICONST 14
#define AC_CONVAL 15
#define AC_ADD 1
#define AC_SUB 2
#define AC_MUL 3
#define AC_DIV 4
#define AC_EXP 5
#define AC_NEG 6
#define AC_INTR_CALL 7
#define AC_ARRAYREF 8
#define AC_MEMBR_SEL 9
#define AC_CONV 10
#define AC_CAT 11
#define AC_EXPK 12
#define AC_LEQV 13
#define AC_LNEQV 14
#define AC_LOR 15
#define AC_LAND 16
#define AC_EQ 17
#define AC_GE 18
#define AC_GT 19
#define AC_LE 20
#define AC_LT 21
#define AC_NE 22
#define AC_LNOT 23
#define AC_EXPX 24
#define AC_TRIPLE 25
#define BINOP(p) ((p)->op != AC_NEG && (p)->op != AC_CONV)
#define ACL_AREA 0
#define ACL_SAVE_AREA 3
#define GET_ACL(a) get_acl(a)
#define STSK_ENT(i) sem.stsk_base[sem.stsk_depth - (i)-1]
#define EQV(i) sem.eqv_base[i]
#define EQV_NUMSS(i) sem.eqv_ss_base[i] /* number of subscripts */
#define EQV_SS(i, j) sem.eqv_ss_base[i + j + 1] /* j from 0 to EQV_NUMSS(i) */
#define ARG_STK(i) sem.argpos[i].stkp
#define ARG_AST(i) sem.argpos[i].ast
#define XFR_ARGAST(i) ARG_AST(i) = SST_ASTG(ARG_STK(i))
#define MAX_DOSTACK 8
#define PAR_SCOPE_NONE 0
#define PAR_SCOPE_SHARED 1
#define PAR_SCOPE_PRIVATE 2
#define PAR_SCOPE_FIRSTPRIVATE 3
#define PAR_SCOPE_TASKNODEFAULT 4
#define BLK_SYM(i) sem.scope_stack[i].blk_sym
#define BLK_AUTOBJ(i) sem.scope_stack[i].autobj
#define BLK_UPLEVEL_SPTR(i) sem.scope_stack[i].uplevel_sptr
#define BLK_SCOPE_SPTR(i) sem.scope_stack[i].mpscope_sptr
#define _INF_CLEN 500
#define ATOMIC_UNDEF -1
#define ATOMIC_UPDATE 1
#define ATOMIC_READ 2
#define ATOMIC_WRITE 3
#define ATOMIC_CAPTURE 4
#define NTYPE 23
#define IS_INTRINSIC(st) (st == ST_INTRIN || st == ST_GENERIC || st == ST_PD)
#define INSIDE_STRUCT (sem.stsk_depth != 0)
#define DCLCHK(sptr)
#define DOCHK(sptr)
#define IN_MODULE (sem.mod_cnt && gbl.internal == 0)
#define IN_MODULE_SPEC (sem.mod_cnt && gbl.currsub == 0)
Typedefs
typedef struct type_list TYPE_LIST
typedef struct _std_range STD_RANGE
typedef struct _std_record STD_RECORD
typedef struct xyyz ITEM
typedef struct reduc_sym REDUC_SYM
typedef struct reduc_tag REDUC
typedef struct noscope_sym NOSCOPE_SYM
typedef struct var_init VAR
typedef struct _aexpr AEXPR
typedef struct _acl ACL
typedef struct equiv_var EQVV
typedef struct _seql SEQL
typedef struct _accl ACCL
typedef struct scope_sym_tag SCOPE_SYM
typedef enum SCOPEKIND SCOPEKIND
typedef struct ident_proc_list IDENT_PROC_LIST
typedef struct ident_list IDENT_LIST
typedef enum tbpTasks tbpTask
Constants representing tasks for type bound procedure (tbp) processing.
typedef enum dimMask dimMask
These are constants used by SST_DIMFLAG and A_MASK to represent empty subscripts (e.g., (:), (:,:), (:,:,:), etc.)
Enumerations
enum distlooptype {
LP_PDO = 1 , LP_PARDO , LP_DISTRIBUTE , LP_DIST_TEAMS ,
LP_DIST_TARGTEAMS , LP_DISTPARDO , LP_DISTPARDO_TEAMS , LP_DISTPARDO_TARGTEAMS ,
LP_PARDO_OTHER
}
enum DI_KIND {
DI_IF , DI_IFELSE , DI_DO , DI_DOCONCURRENT ,
DI_DOWHILE , DI_WHERE , DI_ELSEWHERE , DI_FORALL ,
DI_CASE , DI_SELECT_TYPE , DI_ASSOC , DI_BLOCK ,
DI_FIRST_DIRECTIVE , DI_PAR = DI_FIRST_DIRECTIVE , DI_PARDO , DI_PDO ,
DI_DOACROSS , DI_PARSECTS , DI_SECTS , DI_SINGLE ,
DI_CRITICAL , DI_MASTER , DI_ORDERED , DI_WORKSHARE ,
DI_PARWORKS , DI_TASK , DI_ATOMIC_CAPTURE , DI_SIMD ,
DI_TASKGROUP , DI_TASKLOOP , DI_TARGET , DI_TARGETENTERDATA ,
DI_TARGETEXITDATA , DI_TARGETDATA , DI_TARGETUPDATE , DI_DISTRIBUTE ,
DI_TEAMS , DI_DECLTARGET , DI_DISTPARDO , DI_TARGPARDO ,
DI_TARGETSIMD , DI_TARGTEAMSDIST , DI_TEAMSDIST , DI_TARGTEAMSDISTPARDO ,
DI_TEAMSDISTPARDO , DI_CUFKERNEL , DI_ACCREG , DI_ACCKERNELS ,
DI_ACCPARALLEL , DI_ACCDO , DI_ACCLOOP , DI_ACCREGDO ,
DI_ACCREGLOOP , DI_ACCKERNELSDO , DI_ACCKERNELSLOOP , DI_ACCPARALLELDO ,
DI_ACCPARALLELLOOP , DI_ACCKERNEL , DI_ACCDATAREG , DI_ACCHOSTDATA ,
DI_ACCSERIAL , DI_ACCSERIALLOOP , DI_MAXID
}
enum AC_INTRINSIC {
AC_I_NONE = 0 , AC_I_adjustl , AC_I_adjustr , AC_I_char ,
AC_I_ichar , AC_I_index , AC_I_int , AC_I_ishft ,
AC_I_ishftc , AC_I_kind , AC_I_lbound , AC_I_len ,
AC_I_len_trim , AC_I_nint , AC_I_null , AC_I_repeat ,
AC_I_reshape , AC_I_scan , AC_I_selected_int_kind , AC_I_selected_real_kind ,
AC_I_size , AC_I_transfer , AC_I_trim , AC_I_ubound ,
AC_I_verify , AC_I_shape , AC_I_min , AC_I_max ,
AC_I_fltconvert , AC_I_floor , AC_I_ceiling , AC_I_mod ,
AC_I_sqrt , AC_I_exp , AC_I_log , AC_I_log10 ,
AC_I_sin , AC_I_cos , AC_I_tan , AC_I_asin ,
AC_I_acos , AC_I_atan , AC_I_atan2 , AC_I_selected_char_kind ,
AC_I_abs , AC_I_iand , AC_I_ior , AC_I_ieor ,
AC_I_merge , AC_I_lshift , AC_I_rshift , AC_I_maxloc ,
AC_I_maxval , AC_I_minloc , AC_I_minval , AC_I_scale ,
AC_I_transpose
}
enum SCOPEKIND {
SCOPE_OUTER , SCOPE_NORMAL , SCOPE_MODULE , SCOPE_SUBPROGRAM ,
SCOPE_BLOCK , SCOPE_INTERFACE , SCOPE_USE , SCOPE_PAR
}
enum PHASE_TYPE {
PHASE_END_MODULE = -1 , PHASE_INIT = 0 , PHASE_HEADER = 1 , PHASE_USE = 2 ,
PHASE_IMPORT = 3 , PHASE_IMPLICIT = 4 , PHASE_SPEC = 5 , PHASE_EXEC = 6 ,
PHASE_CONTAIN = 7 , PHASE_INTERNAL = 8 , PHASE_END = 9
}
enum tbpTasks {
TBP_CLEAR_ERROR = -1 , TBP_CLEAR , TBP_CLEAR_STALE_RECORDS , TBP_ADD_SIMPLE ,
TBP_ADD_TO_DTYPE , TBP_COMPLETE_ENDMODULE , TBP_ADD_INTERFACE , TBP_ADD_IMPL ,
TBP_PASS , TBP_COMPLETE_FIN , TBP_INHERIT , TBP_NOPASS ,
TBP_NONOVERRIDABLE , TBP_PRIVATE , TBP_PUBLIC , TBP_STATUS ,
TBP_DEFERRED , TBP_IFACE , TBP_COMPLETE_END , TBP_COMPLETE_ENDTYPE ,
TBP_CHECK_CHILD , TBP_CHECK_PRIVATE , TBP_CHECK_PUBLIC , TBP_COMPLETE_GENERIC ,
TBP_ADD_FINAL , TBP_FORCE_RESOLVE
}
Constants representing tasks for type bound procedure (tbp) processing.
enum dimMask { lboundMask = 0x1 , uboundMask = 0x2 , strideMask = 0x4 }
These are constants used by SST_DIMFLAG and A_MASK to represent empty subscripts (e.g., (:), (:,:), (:,:,:), etc.)
Functions
void scopestack_init (void)
Initialize the scope stack.
SCOPESTACK * curr_scope (void)
Return the scope at the top of the scope stack.
SCOPESTACK * get_scope (int index)
Get an entry in the scope stack.
int get_scope_level (SCOPESTACK *scope)
Return the level of this entry in the scope stack or -1 if scope is null.
SCOPESTACK * next_scope (SCOPESTACK *scope)
Return the next entry below this one in the scope stack; 0 if none. If scope is 0, return the top of the stack.
SCOPESTACK * next_scope_sptr (SCOPESTACK *scope, int sptr)
Return the next entry below scope that has this sptr assocated with it. If scope is 0, search from the top of the stack.
SCOPESTACK * next_scope_kind (SCOPESTACK *scope, SCOPEKIND kind)
Return the next entry below scope that has this kind. If scope is 0, search from the top of the stack.
SCOPESTACK * next_scope_kind_sptr (SCOPESTACK *scope, SCOPEKIND kind, int sptr)
Return the next entry below scope that has this kind and sptr. If scope is 0, search from the top of the stack.
SCOPESTACK * next_scope_kind_symname (SCOPESTACK *scope, SCOPEKIND kind, const char *symname)
Return the next entry below scope that has this kind and symbol name. If scope is 0, search from the top of the stack.
int have_use_scope (int sptr)
Return the USE module scope for the module associated with this symbol, or -1 if none.
LOGICAL is_except_in_scope (SCOPESTACK *scope, int sptr)
Return TRUE if sptr is in the exception list for this scope at this level.
LOGICAL is_private_in_scope (SCOPESTACK *scope, int sptr)
Return TRUE if scope is private and has sptr in its 'only' list.
void push_scope_level (int sptr, SCOPEKIND kind)
Push a slot on the scope stack.
void pop_scope_level (SCOPEKIND kind)
void save_scope_level (void)
Pop the current scope into a save area; restore with restore_scope_level()
void restore_scope_level (void)
Restore the scope that was saved by save_scope_level()
void par_push_scope (LOGICAL bind_to_outer)
void par_pop_scope (void)
void allocate_refsymbol (int)
void set_modusename (int, int)
void use_init (void)
void init_use_stmts (void)
void add_use_stmt (void)
Process a "USE module" statement. The module is specified in module_id.
void add_submodule_use (void)
SPTR add_use_rename (SPTR, SPTR, LOGICAL)
Process a USE ONLY statement, optionally renaming 'global' as 'local'. The module is specified in 'module_id'.
void apply_use_stmts (void)
void add_isoc_intrinsics (void)
void open_module (SPTR)
Begin processing a USE statement. use - sym ptr of module identifer in use statement Find or create an entry in usedb for it and set 'module_id' to the index.
void close_module (void)
void mod_combined_name (const char *)
void mod_combined_index (const char *)
SPTR begin_module (SPTR)
SPTR begin_submodule (SPTR, SPTR, SPTR, SPTR *)
LOGICAL get_seen_contains (void)
void mod_implicit (int, int, int)
void begin_contains (void)
void end_module (void)
LOGICAL has_cuda_data (void)
void mod_fini (void)
void mod_init (void)
int mod_add_subprogram (int)
void mod_end_subprogram (void)
void mod_end_subprogram_two (void)
int get_nml_array (int)
Create the array (ST_PLIST) representing the namelist.
ISZ_T size_of_array (DTYPE)
Check if array has zero size.
DTYPE chk_constructor (ACL *, DTYPE)
Check the array constructor and decide the dtype.
void chk_struct_constructor (ACL *)
void gen_type_initialize_for_sym (SPTR, int, int, DTYPE)
void clean_struct_default_init (int)
void restore_host_state (int)
Called at the end of an internal subprogram.
void restore_internal_subprograms (void)
Called at the beginning of a subprogram in pass 2.
void dummy_program (void)
Check whether there is a subprogram statement; if not, create a dummy program symbol, and use that as the program.
int have_module_state (void)
void fix_type_param_members (SPTR, DTYPE)
void add_type_param_initialize (int)
void add_p_dealloc_item (int sptr)
int gen_finalization_for_sym (int sptr, int std, int memAst)
void gen_alloc_mem_initialize_for_sym (int sptr, int std)
int add_parent_to_bounds (int parent, int ast)
int fix_mem_bounds2 (int, int)
int fix_mem_bounds (int parent, int mem)
int init_sdsc (int, DTYPE, int, int)
int init_sdsc_bounds (SPTR, DTYPE, int, SPTR, int, int)
Similar to init_sdsc() above, but it's also used to initialize a descriptor's bounds from a subscript expression.
void save_module_state1 (void)
Called at a CONTAINS clause.
void save_module_state2 (void)
void restore_module_state (void)
Called at start of module-contained subprogram, restores state. If this is the first 'restore' since the last 'reset', the 'module append' file is full and needs to be imported.
void reset_module_state (void)
Called at the end of a module-contained subprogram; rearranges the data structures for the module.
LOGICAL is_alloc_ast (int)
LOGICAL is_alloc_std (int)
LOGICAL is_dealloc_ast (int)
LOGICAL is_dealloc_std (int)
SPTR get_dtype_init_template (DTYPE)
Process an AC_TYPEINIT.
void module_must_hide_this_symbol (int sptr)
void reset_internal_subprograms (void)
int mp_create_bscope (int reuse)
void save_struct_init (ACL *)
void chk_adjarr (void)
int mp_create_escope (void)
void dup_struct_init (int, int)
Duplicate a derived type component's default initializations.
void gen_derived_type_alloc_init (ITEM *)
void save_host_state (int)
Called from semant.c to save the semant, sym, dtype, ast, and other 'state' information from a host routine for internal subprograms, for 'pass 1'. Also, for 'pass 2', save_host_state is called to overwrite the semant state information.
void add_auto_finalize (int)
int runtime_array (int)
Return TRUE if the expression at 'ast' is composed of constants and the special symbol 'hpf_np$'. In this case, even though the bound is not a literal constant, it is a runtime constant.
DTYPE mk_arrdsc (void)
int gen_defer_shape (int, int, int)
Process an explicit shape list has been parsed and all bounds information has been deposited into a few semant global data structures.
ACL * eval_init_expr (ACL *e)
void gen_allocate_array (int)
Given an allocatable array and an explicit shape list which has been deposited in the semant 'bounds' structure, generate assignments to the arrays bounds temporaries, and allocate the array. Save the id ast of the array for an ensuing deallocate of the array.
void gen_deallocate_arrays (void)
Generate deallocates for the temporary arrays in the sem.p_delloc list.
void mk_defer_shape (SPTR)
void mk_assumed_shape (SPTR)
SPTR get_arr_const (DTYPE)
Get a compiler array temporary of type dtype which is used to represent array constants.
DTYPE select_kind (DTYPE, int, INT)
SPTR get_param_alias_var (SPTR, DTYPE)
void init_named_array_constant (int, int)
Initialize a named array constant (array PARAMETER), ensuring that it's only being done within the context of its host subprogram.
int init_sptr_w_acl (int, ACL *)
Assign aclp values to in_sptr.
int init_derived_w_acl (int, ACL *)
ACL * mk_init_intrinsic (AC_INTRINSIC)
ACL * get_acl (int)
ACL * save_acl (ACL *)
ACL * construct_acl_from_ast (int, DTYPE, int)
ACL * rewrite_acl (ACL *, DTYPE, int)
ACL * all_default_init (DTYPE)
Check whether derived type has components with default initializations.
void dmp_acl (ACL *, int)
void mk_struct_constr (int, int)
void process_struct_components (int, void(*)(int))
int get_struct_leafcnt (int)
int get_first_mangled (int)
void re_struct_constr (int, int)
void propagate_attr (int, int)
ACL * dinit_struct_vals (ACL *, DTYPE, SPTR)
In DATA statement, do the stuff in dinit_struct_const in two steps.
SPTR get_temp (DTYPE)
Get a compiler temporary of any scalar dtype.
DTYPE get_temp_dtype (DTYPE, int)
SPTR get_itemp (DTYPE)
SPTR get_arr_temp (DTYPE, LOGICAL, LOGICAL, LOGICAL)
Get a compiler array temporary of type dtype.
SPTR get_adjlr_arr_temp (DTYPE)
Get a compiler-created allocatable array temp to represent the result of run-time function computing the adjustl/adjustr intrinsic.
int get_shape_arr_temp (int)
Get a compiler array temporary of from a shape of an ast.
SPTR get_ch_temp (DTYPE)
Get a character compiler temporary of type dtype.
int need_alloc_ch_temp (DTYPE)
int sem_strcmp (const char *, const char *)
Compare str and pattern like strcmp() but ignoring the case of str. pattern is all lower case.
LOGICAL sem_eq_str (int, const char *)
Return TRUE if fortran character constant is equal to pattern (pattern is always uppercase).
void add_case_range (int, int, int)
Update the SWEL list for a SELECTCASE construct represented by the doif structure.
int _i4_cmp (int, int)
Compare functions whose arguments are pointers to ST_CONST symbol table entries.
int _i8_cmp (int, int)
int _char_cmp (int, int)
int _nchar_cmp (int, int)
int gen_alloc_dealloc (int, int, ITEM *)
void check_alloc_clauses (ITEM *, ITEM *, int *, int *)
void check_dealloc_clauses (ITEM *, ITEM *)
void gen_conditional_dealloc (int, int, int)
int gen_conditional_alloc (int, int, int)
void gen_conditional_dealloc_for_sym (int, int)
int gen_dealloc_for_sym (int, int)
void gen_automatic_reallocation (int, int, int)
Generate (re)allocation code for deferred length character objects and traditional character objects that are allocatable scalars.
void gen_dealloc_etmps (void)
void sem_set_storage_class (int)
void check_and_add_auto_dealloc_from_ast (int)
void check_and_add_auto_dealloc (int)
void add_auto_dealloc (int)
int enter_lexical_block (int)
void exit_lexical_block (int)
void dmp_doif (FILE *f)
LOGICAL not_in_forall (const char *)
Check if we are currently in a block FORALL scope; if so, issue an error message.
LOGICAL cuda_enabled (const char *)
If we are accepting cuda syntax return TRUE. Otherwise issue an error message and return FALSE.
LOGICAL in_device_code (int)
void sem_err104 (int, int, const char *)
void sem_err105 (int)
VAR * gen_varref_var (int, DTYPE)
void sem_fini (void)
Compilation is finished - deallocate storage, close files, etc.
int gen_set_type (int dest_ast, int src_ast, int std, LOGICAL insert_before, LOGICAL intrin_type)
Generates calls to RTE_set_type() or RTE_set_intrin_type() which set the type descriptor field of an object's descriptor.
int mk_set_type_call (int arg0, int arg1, LOGICAL intrin_type)
Creates an ast that represents a call to a set type runtime routine.
int has_init_value (SPTR)
void semant_init (int noparse)
Initialize semantic analyzer for new user subprogram unit.
int getMscall (void)
provide mscall variable state to other source files.
int getCref (void)
provide cref variable state to other source files.
void build_typedef_init_tree (int sptr, int dtype)
int internal_proc_has_ident (int ident, int proc)
void fixup_reqgs_ident (int sptr)
int queue_type_param (int sptr, int dtype, int offset, int flag)
Sets up type parameters used in parameterized derived types (PDTs)
int get_kind_parm_by_name (char *np, int dtype)
search a derived type for a kind type parameter with a specified name.
int get_parm_by_number (int offset, int dtype)
search derived type for a type parameter in the same position as specified by offset.
int get_parm_by_name (char *np, int dtype)
search a derived type for a kind or length type parameter with a specified name.
int chk_kind_parm_expr (int ast, int dtype, int flag, int strict_flag)
int chk_len_parm_expr (int ast, int dtype, int flag)
int get_len_set_parm_by_name (char *np, int dtype, int *val)
int cmp_len_parms (int ast1, int ast2)
int defer_pt_decl (int dtype, int flag)
Store dtypes of parameterized derived types in which a parameter was explicitly declared (as opposed to using just the default values).
void put_default_kind_type_param (int dtype, int flag, int flag2)
void put_length_type_param (DTYPE dtype, int flag)
int get_len_parm_by_number (int num, int dtype, int flag)
int all_len_parms_assumed (int dtype)
Return 0 if there's at least one length type parameter that is not assumed. Otherwise return 1.
LOGICAL put_kind_type_param (DTYPE dtype, int offset, int value, int expr, int flag)
void llvm_set_tbp_dtype (int dtype)
int get_unl_poly_sym (int mem_dtype)
int has_type_parameter (int dtype)
checks to see if derived type record, dtype, has any type parameters (kind or length type parameters).
int has_length_type_parameter_use (int dtype)
DTYPE create_parameterized_dt (DTYPE dtype, LOGICAL force)
Create a parameterized derived type based on dtype. If force is not set and dtype is already a PDT, return DT_NONE.
DTYPE get_parameterized_dt (DTYPE dtype)
Duplicate dtype by creating a new derived type with a $pt suffix. For use with processing parameterized derived type.
int is_parameter_context ()
allow other source files to check whether we're processing a parameter construct.
bool in_intrinsic_decl (void)
Return the predicate: current entity has the INTRINSIC attribute.
int get_entity_access ()
provide the current entity's access to other source files.
void CheckDecl (int)
Check that sptr is declared if IMPLICIT NONE is set.
void end_contained (void)
called at end of processing contains subprograms
LOGICAL use_opt_atomic (int)
Decide to use optimized atomic usage.
int emit_epar (void)
int emit_etarget (void)
void is_dovar_sptr (int)
void clear_no_scope_sptr (void)
void add_no_scope_sptr (int, int, int)
void pop_accel_vars (void)
void handle_accdecl (int keyword)
void check_no_scope_sptr (void)
void parstuff_init (void)
int emit_bcs_ecs (int)
void end_parallel_clause (int)
void end_teams ()
void end_target ()
void add_assign_firstprivate (int, int)
Add an assignment to the parallel prologue.
void accel_end_dir (int, LOGICAL)
void add_non_private (int)
void mk_cuda_builtins (int *, int *, int)
int mk_cuda_typedef (char *)
int mk_mbr_ref (int, char *)
void set_parref_flag (int, int, int)
void set_parref_flag2 (int, int, int)
set_parref_flag set PARREF flag after semant phase
int is_sptr_in_shared_list (SPTR)
void set_private_encl (int, int)
void set_private_taskflag (int)
int find_outer_sym (int)
void par_add_stblk_shvar (void)
int do_distbegin (DOINFO *, int, int)
void check_derived_type_array_section (int)
Give error message for reference like a(:)b(:)
int gen_poly_element_arg (int ast, SPTR sptr, int std)
Generates a call to a poly_element_addr runtime routine that computes the address of a polymorphic array element.
int add_ptr_assign (int, int, int)
void gen_contig_check (int dest, int src, SPTR sdsc, int lineno, bool cs, int std)
Generate a contiguous pointer check on a pointer assignment when applicable.
int collapse_begin (DOINFO *)
Begin processing loop collapse.
int collapse_add (DOINFO *)
Process an ensuing loop which is being collapsed.
void link_parents (STSK *, int)
Link parents for type extension by adding parent as a member to the type.
void link_members (STSK *, int)
Link together members of a structure.
int ref_object (int)
Access the address of the object (sym).
LOGICAL ast_isparam (int ast)
int mk_component_ast (int, int, int)
int chk_pointer_intent (int, int)
int any_pointer_source (int)
int chk_pointer_target (int, int)
int mod_type (int, int, int, int, int, int)
Return a new data type based on the rules of applying a length specifier to an existing base data type (i.e. LOGICAL*1) passed in as a TY_ value.
int getbase (int)
Dereference an ast to determine the base, i.e. its symbol pointer.
int do_index_addr (int)
Generate ILMs which computes the address of the index variable. Need to do it this way since the ILMs which were originally computed during the parse are not saved across the blocks.
int do_begin (DOINFO *)
Write out block DO AST from doinfo record. This function assumes that they init, limit, and step expressions have already been cast to the type of the do index variable.
void do_lastval (DOINFO *)
int do_parbegin (DOINFO *)
void do_end (DOINFO *)
int mkmember (int, int, int)
LOGICAL legal_labelvar (int)
void resolve_fwd_refs (void)
Resolve forward references: try to find the declaration symbol and replace the reference symbol with it.
bool in_save_scope (SPTR)
DOINFO * get_doinfo (int)
LOGICAL is_protected (int)
void err_protected (int, const char *)
void set_assn (int)
void semfin (void)
Finalize semantic processing.
void ipa_semfin (void)
void semfin_free_memory (void)
Deallocate data structures for semantic analysis.
void fix_class_args (int sptr)
Add type descriptor arguments to a specified function if they have not already been added.
void llvm_fix_args (int sptr)
void do_equiv (void)
void init_derived_type (SPTR, int, int)
int sym_in_scope (int, OVCLASS, int *, int *, int)
Look for a symbol with same name as first and in an active scope.
void sem_import_sym (int)
IMPORT symbol from host scope – not to be confused with interf import stuff.
int test_scope (int)
int declref (int, SYMTYPE, int)
Look up symbol having a specific symbol type.
void set_internref_stfunc (int)
int declsym (int, SYMTYPE, LOGICAL)
Declare a new symbol.
int refsym (int, OVCLASS)
Look up a symbol having the given overloading class.
int refsym_inscope (int, OVCLASS)
Similar to refsym() except that the current scope is taken into consideration.
void enforce_denorm (void)
int getocsym (int, OVCLASS, LOGICAL)
Look up symbol matching overloading class of given symbol type.
int declobject (int, SYMTYPE)
int newsym (int)
Reset fields of intrinsic or generic symbol, sptr, to zero in preparation for changing its symbol type by the Semantic Analyzer.
int ref_ident (int)
Reference a symbol when it's known the context requires an identifier.
int ref_ident_inscope (int)
int ref_storage (int)
Reference a symbol when it's known the context requires storage, e.g., a variable or the result of a function.
int ref_storage_inscope (int)
int ref_int_scalar (int)
Reference a symbol when it's known the context requires an integer scalar variable.
int ref_based_object (int)
Reference a based object.
int ref_based_object_sc (int, SC_KIND)
int refocsym (int, OVCLASS)
Reference the first symbol of the given overloading class in the current scope. If not found, zero is returned.
int sym_skip_construct (int)
SPTR block_local_sym (SPTR)
Return a symbol local to the current BLOCK if applicable.
int declsym_newscope (int, SYMTYPE, int)
Declare a symbol in the most current scope; if one already exists return it.
int decl_private_sym (int)
Declare a private symbol which may be based on the attributes of an existing symbol.
int sem_check_scope (int, int)
Check the current parallel scope of a variable.
int get_static_type_descriptor (int sptr)
Return the "static type descriptor" for object sptr. The static type descriptor holds the "declared type" of an object.
int get_type_descr_arg (int func_sptr, int arg)
Return the type descriptor associated with arg (and func_sptr when arg is a dummy argument of routine func_sptr).
int get_type_descr_arg2 (int func_sptr, int arg)
Same as get_type_descr_arg(), but do not perform error check.
int sc_local_passbyvalue (int sptr, int func_sptr)
Return true if sptr is an SC_LOCAL and a pass by value parameter of func_sptr.
LOGICAL allocatable_member (int sptr)
Return TRUE if sptr is a derived type with an allocatable member.
LOGICAL in_kernel_region (void)
int get_tbp_argno (int sptr, int dty2)
int get_generic_member (int dtype, int sptr)
int get_generic_member2 (int dtype, int sptr, int argcnt, int *argno)
int generic_tbp_has_pass_and_nopass (int dtype, int sptr)
int get_generic_tbp_pass_or_nopass (int dtype, int sptr, int flag)
int get_specific_member (int dtype, int sptr)
int get_implementation (int dtype, int sptr, int flag, int *memout)
For type bound procedures, find the implementation for the type bound procedure binding name in dtype.
int _selected_char_kind (int con)
Check charset.
void set_pass_objects (int, int)
Set position of type-bound procedure passed object location.
int intrinsic_as_arg (int)
int ref_entry (int)
int select_gsame (int)
Given a generic intrinsic, select the corresponding specific of the same name.
char * make_kwd_str (int)
Make a keyword string for a ST_PROC.
char * make_keyword_str (int, int)
Make a keyword string from the DPDSC auxiliary structure.
LOGICAL get_kwd_args (ITEM *, int, const char *)
Extract the arguments from the semantic list into sem.argpos[] in positional order.
LOGICAL evl_kwd_args (ITEM *, int, const char *)
Call get_kwd_args and evaluate each argument.
LOGICAL sum_scatter_args (ITEM *, int)
LOGICAL check_arguments (int, int, ITEM *, char *)
Check arguments passed to a user subprogram which has an interface block. Its keyword string is available and is located by kwd_str.
LOGICAL chk_arguments (int, int, ITEM *, char *, int, int, int, int *)
Check arguments passed to a user subprogram which has an interface block. Its keyword string is available and is located by kwd_str.
LOGICAL ignore_tkr (int, int)
LOGICAL ignore_tkr_all (int)
int iface_intrinsic (int)
void defer_arg_chk (SPTR formal, SPTR actual, SPTR subprog, cmp_interface_flags, int lineno, bool performChk)
Process information for deferred interface argument checking in in the compat_arg_lists() function below.
void check_generic (int)
void init_intrinsic_opr (void)
void bind_intrinsic_opr (int, int)
int get_intrinsic_oprsym (int, int)
int get_intrinsic_opr (int, int)
int dtype_has_defined_io (int)
Return a bit mask indicating which I/O routines are defined for a derived type.
void check_defined_io (void)
void add_overload (int, int)
void copy_specifics (int fromsptr, int tosptr)
int test_private_dtype (int dtype)
Check whether the dtype is inside a valid scope.
void set_construct_name (int name)
int get_construct_name (void)
void check_doconcurrent (int doif)
Check a DO CONCURRENT loop for constraint violations.
int has_poly_mbr (int sptr, int flag)
Return TRUE if derived type has a polymorphic member.
void push_tbp_arg (ITEM *item)
ITEM * pop_tbp_arg (void)
void err307 (const char *, int, int)
void gen_init_unl_poly_desc (int dest_sdsc_ast, int src_sdsc_ast, int std)
Generate a call to init_unl_poly_desc which initializes a descriptor for an unlimited polymorphic object with another descriptor.
void xrefinit (void)
void xrefput (int symptr, int usage)
Write one reference record to Reference File:
void xref (void)
int queue_tbp (int sptr, int bind, int offset, int dtype, tbpTask task)
Main function for processing type bound procedures (tbps), generic type bound procedures, derived type I/O generic type bound procedures, and final subroutines.
void ensure_no_stale_tbp_queue_entries (void)
Variables
SEM sem
INT cast_types [NTYPE][2][2]
We only allow casting to and from TY_WORD and TY_DWORD. Therefore, you index into the following table as follows cast_types[dtype][{DT_WORD or DT_DWORD} - 1][0 for from or 1 for to] Entries are:
Detailed Description
Semantic analyzer data definitions.
Definition in file flang1/flang1exe/semant.h.
Macro Definition Documentation
_INF_CLEN
#define _INF_CLEN 500
Definition at line 1078 of file flang1/flang1exe/semant.h.
AC_ACONST
#define AC_ACONST 8
Definition at line 534 of file flang1/flang1exe/semant.h.
AC_ADD
#define AC_ADD 1
Definition at line 552 of file flang1/flang1exe/semant.h.
AC_ARRAYREF
#define AC_ARRAYREF 8
Definition at line 559 of file flang1/flang1exe/semant.h.
AC_AST
#define AC_AST 5
Definition at line 531 of file flang1/flang1exe/semant.h.
AC_CAT
#define AC_CAT 11
Definition at line 562 of file flang1/flang1exe/semant.h.
AC_CONST
#define AC_CONST 2
Definition at line 528 of file flang1/flang1exe/semant.h.
AC_CONV
#define AC_CONV 10
Definition at line 561 of file flang1/flang1exe/semant.h.
AC_CONVAL
#define AC_CONVAL 15
Definition at line 544 of file flang1/flang1exe/semant.h.
AC_DIV
#define AC_DIV 4
Definition at line 555 of file flang1/flang1exe/semant.h.
AC_EQ
#define AC_EQ 17
Definition at line 568 of file flang1/flang1exe/semant.h.
AC_EXP
#define AC_EXP 5
Definition at line 556 of file flang1/flang1exe/semant.h.
AC_EXPK
#define AC_EXPK 12
Definition at line 563 of file flang1/flang1exe/semant.h.
AC_EXPR
#define AC_EXPR 3 /* SST expr */
Definition at line 529 of file flang1/flang1exe/semant.h.
AC_EXPX
#define AC_EXPX 24
Definition at line 575 of file flang1/flang1exe/semant.h.
AC_GE
#define AC_GE 18
Definition at line 569 of file flang1/flang1exe/semant.h.
AC_GT
#define AC_GT 19
Definition at line 570 of file flang1/flang1exe/semant.h.
AC_ICONST
#define AC_ICONST 14
Definition at line 540 of file flang1/flang1exe/semant.h.
AC_IDENT
#define AC_IDENT 1
Definition at line 527 of file flang1/flang1exe/semant.h.
AC_IDO
#define AC_IDO 6
Definition at line 532 of file flang1/flang1exe/semant.h.
AC_IEXPR
#define AC_IEXPR 4 /* AC expression */
Definition at line 530 of file flang1/flang1exe/semant.h.
AC_INTR_CALL
#define AC_INTR_CALL 7
Definition at line 558 of file flang1/flang1exe/semant.h.
AC_LAND
#define AC_LAND 16
Definition at line 567 of file flang1/flang1exe/semant.h.
AC_LE
#define AC_LE 20
Definition at line 571 of file flang1/flang1exe/semant.h.
AC_LEQV
#define AC_LEQV 13
Definition at line 564 of file flang1/flang1exe/semant.h.
AC_LIST
#define AC_LIST 10 /* only used during DATA stmt processing */
Definition at line 536 of file flang1/flang1exe/semant.h.
AC_LNEQV
#define AC_LNEQV 14
Definition at line 565 of file flang1/flang1exe/semant.h.
AC_LNOT
#define AC_LNOT 23
Definition at line 574 of file flang1/flang1exe/semant.h.
AC_LOR
#define AC_LOR 15
Definition at line 566 of file flang1/flang1exe/semant.h.
AC_LT
#define AC_LT 21
Definition at line 572 of file flang1/flang1exe/semant.h.
AC_MEMBR_SEL
#define AC_MEMBR_SEL 9
Definition at line 560 of file flang1/flang1exe/semant.h.
AC_MUL
#define AC_MUL 3
Definition at line 554 of file flang1/flang1exe/semant.h.
AC_NE
#define AC_NE 22
Definition at line 573 of file flang1/flang1exe/semant.h.
AC_NEG
#define AC_NEG 6
Definition at line 557 of file flang1/flang1exe/semant.h.
AC_REPEAT
#define AC_REPEAT 7
Definition at line 533 of file flang1/flang1exe/semant.h.
AC_SCONST
#define AC_SCONST 9
Definition at line 535 of file flang1/flang1exe/semant.h.
AC_SUB
#define AC_SUB 2
Definition at line 553 of file flang1/flang1exe/semant.h.
AC_TRIPLE
#define AC_TRIPLE 25
Definition at line 576 of file flang1/flang1exe/semant.h.
AC_TYPEINIT
#define AC_TYPEINIT 13
Definition at line 539 of file flang1/flang1exe/semant.h.
AC_VMSSTRUCT
#define AC_VMSSTRUCT 11
Definition at line 537 of file flang1/flang1exe/semant.h.
AC_VMSUNION
#define AC_VMSUNION 12
Definition at line 538 of file flang1/flang1exe/semant.h.
ACL_AREA
#define ACL_AREA 0
Definition at line 641 of file flang1/flang1exe/semant.h.
ACL_SAVE_AREA
#define ACL_SAVE_AREA 3
Definition at line 642 of file flang1/flang1exe/semant.h.
ARG_AST
#define ARG_AST (i) sem.argpos[i].ast
Definition at line 750 of file flang1/flang1exe/semant.h.
ARG_STK
#define ARG_STK (i) sem.argpos[i].stkp
Definition at line 749 of file flang1/flang1exe/semant.h.
ATOMIC_CAPTURE
#define ATOMIC_CAPTURE 4
Definition at line 1312 of file flang1/flang1exe/semant.h.
ATOMIC_READ
#define ATOMIC_READ 2
Definition at line 1310 of file flang1/flang1exe/semant.h.
ATOMIC_UNDEF
#define ATOMIC_UNDEF -1
Definition at line 1308 of file flang1/flang1exe/semant.h.
ATOMIC_UPDATE
#define ATOMIC_UPDATE 1
Definition at line 1309 of file flang1/flang1exe/semant.h.
ATOMIC_WRITE
#define ATOMIC_WRITE 3
Definition at line 1311 of file flang1/flang1exe/semant.h.
BINOP
#define BINOP (p) ((p)->op != AC_NEG && (p)->op != AC_CONV)
Definition at line 638 of file flang1/flang1exe/semant.h.
BLK_AUTOBJ
#define BLK_AUTOBJ (i) sem.scope_stack[i].autobj
Definition at line 830 of file flang1/flang1exe/semant.h.
BLK_SCOPE_SPTR
#define BLK_SCOPE_SPTR (i) sem.scope_stack[i].mpscope_sptr
Definition at line 832 of file flang1/flang1exe/semant.h.
BLK_SYM
#define BLK_SYM (i) sem.scope_stack[i].blk_sym
Definition at line 829 of file flang1/flang1exe/semant.h.
BLK_UPLEVEL_SPTR
#define BLK_UPLEVEL_SPTR (i) sem.scope_stack[i].uplevel_sptr
Definition at line 831 of file flang1/flang1exe/semant.h.
DBG_LEXBLK
#define DBG_LEXBLK flg.debug && !flg.vect && !XBIT(34, 0x200) && !XBIT(123, 0x400)
Definition at line 72 of file flang1/flang1exe/semant.h.
DCLCHK
#define DCLCHK (sptr)
Value:
  {                        \
    if (sem.none_implicit) \
      CheckDecl(sptr);     \
  }
Definition at line 1456 of file flang1/flang1exe/semant.h.
DI_ACTIVE_SPTR
#define DI_ACTIVE_SPTR (d) sem.doif_base[d].u.u5.active_sptr
Definition at line 419 of file flang1/flang1exe/semant.h.
DI_ALLO_CHTMP
#define DI_ALLO_CHTMP (d) sem.doif_base[d].u.u3.allo_chtmp
Definition at line 390 of file flang1/flang1exe/semant.h.
DI_ALLOCATED
#define DI_ALLOCATED (d) sem.doif_base[d].u.u4.allocated
Definition at line 403 of file flang1/flang1exe/semant.h.
DI_ASSOCIATIONS
#define DI_ASSOCIATIONS (d) sem.doif_base[d].u.u7.sptrs
Definition at line 431 of file flang1/flang1exe/semant.h.
DI_B
#define DI_B (t) (onel << (t))
Definition at line 436 of file flang1/flang1exe/semant.h.
DI_BDISTRIBUTE
#define DI_BDISTRIBUTE (d) sem.doif_base[d].u.u4.distribute
Definition at line 398 of file flang1/flang1exe/semant.h.
DI_BEG_DEFAULT
#define DI_BEG_DEFAULT (d) sem.doif_base[d].u.u3.beg_default
Definition at line 387 of file flang1/flang1exe/semant.h.
DI_BEGINP
#define DI_BEGINP (d) sem.doif_base[d].u.u4.beginp
Definition at line 400 of file flang1/flang1exe/semant.h.
DI_BPAR
#define DI_BPAR (d) sem.doif_base[d].u.u4.bpar
Definition at line 395 of file flang1/flang1exe/semant.h.
DI_BTARGET
#define DI_BTARGET (d) sem.doif_base[d].u.u4.target
Definition at line 396 of file flang1/flang1exe/semant.h.
DI_BTEAMS
#define DI_BTEAMS (d) sem.doif_base[d].u.u4.teams
Definition at line 397 of file flang1/flang1exe/semant.h.
DI_CASE_EXPR
#define DI_CASE_EXPR (d) sem.doif_base[d].u.u3.case_expr
Definition at line 385 of file flang1/flang1exe/semant.h.
DI_CHUNK
#define DI_CHUNK (d) sem.doif_base[d].u.u4.v.v1.chunk
Definition at line 406 of file flang1/flang1exe/semant.h.
DI_CLASS_DEFAULT_LABEL
#define DI_CLASS_DEFAULT_LABEL (d) sem.doif_base[d].u.u5.class_default_label
Definition at line 422 of file flang1/flang1exe/semant.h.
DI_CONC_BLOCK_SYM
#define DI_CONC_BLOCK_SYM (d) sem.doif_base[d].u.u1.block_sym
Definition at line 374 of file flang1/flang1exe/semant.h.
DI_CONC_BODY_STD
#define DI_CONC_BODY_STD (d) sem.doif_base[d].u.u1.body_std
Definition at line 380 of file flang1/flang1exe/semant.h.
DI_CONC_COUNT
#define DI_CONC_COUNT (d) sem.doif_base[d].u.u1.count
Definition at line 371 of file flang1/flang1exe/semant.h.
DI_CONC_ERROR_SYMS
#define DI_CONC_ERROR_SYMS (d) sem.doif_base[d].u.u1.error_syms
Definition at line 378 of file flang1/flang1exe/semant.h.
DI_CONC_KIND
#define DI_CONC_KIND (d) sem.doif_base[d].u.u1.kind
Definition at line 372 of file flang1/flang1exe/semant.h.
DI_CONC_LABEL_SYMS
#define DI_CONC_LABEL_SYMS (d) sem.doif_base[d].u.u1.label_syms
Definition at line 377 of file flang1/flang1exe/semant.h.
DI_CONC_LAST_SYM
#define DI_CONC_LAST_SYM (d) sem.doif_base[d].u.u1.last_sym
Definition at line 376 of file flang1/flang1exe/semant.h.
DI_CONC_MASK_STD
#define DI_CONC_MASK_STD (d) sem.doif_base[d].u.u1.mask_std
Definition at line 379 of file flang1/flang1exe/semant.h.
DI_CONC_NO_DEFAULT
#define DI_CONC_NO_DEFAULT (d) sem.doif_base[d].u.u1.no_default
Definition at line 373 of file flang1/flang1exe/semant.h.
DI_CONC_SYMAVL
#define DI_CONC_SYMAVL (d) sem.doif_base[d].u.u1.symavl
Definition at line 370 of file flang1/flang1exe/semant.h.
DI_CONC_SYMS
#define DI_CONC_SYMS (d) sem.doif_base[d].u.u1.syms
Definition at line 375 of file flang1/flang1exe/semant.h.
DI_CRITSYM
#define DI_CRITSYM (d) sem.doif_base[d].u.u4.bpar
Definition at line 399 of file flang1/flang1exe/semant.h.
DI_CYCLE_LABEL
#define DI_CYCLE_LABEL (d) sem.doif_base[d].u.u1.cycle_label
Definition at line 365 of file flang1/flang1exe/semant.h.
DI_DEFAULT_COMPLETE
#define DI_DEFAULT_COMPLETE (d) sem.doif_base[d].u.u3.default_complete
Definition at line 392 of file flang1/flang1exe/semant.h.
DI_DEFAULT_SEEN
#define DI_DEFAULT_SEEN (d) sem.doif_base[d].u.u3.default_seen
Definition at line 391 of file flang1/flang1exe/semant.h.
DI_DISTCHUNK
#define DI_DISTCHUNK (d) sem.doif_base[d].u.u4.v.v1.dist_chunk
Definition at line 407 of file flang1/flang1exe/semant.h.
DI_DO_AST
#define DI_DO_AST (d) sem.doif_base[d].u.u1.ast
Definition at line 367 of file flang1/flang1exe/semant.h.
DI_DO_LABEL
#define DI_DO_LABEL (d) sem.doif_base[d].u.u1.do_label
Definition at line 364 of file flang1/flang1exe/semant.h.
DI_DO_POPINDEX
#define DI_DO_POPINDEX (d) sem.doif_base[d].u.u1.popindex
Definition at line 369 of file flang1/flang1exe/semant.h.
DI_DOINFO
#define DI_DOINFO (d) sem.doif_base[d].u.u1.doinfo
Definition at line 368 of file flang1/flang1exe/semant.h.
DI_DTYPE
#define DI_DTYPE (d) sem.doif_base[d].u.u3.dtype
Definition at line 386 of file flang1/flang1exe/semant.h.
DI_ENCL_BLOCK_SCOPE
#define DI_ENCL_BLOCK_SCOPE (d) sem.doif_base[d].u.u8.encl_block_scope
Definition at line 433 of file flang1/flang1exe/semant.h.
DI_END_DEFAULT
#define DI_END_DEFAULT (d) sem.doif_base[d].u.u3.end_default
Definition at line 388 of file flang1/flang1exe/semant.h.
DI_END_SELECT_LABEL
#define DI_END_SELECT_LABEL (d) sem.doif_base[d].u.u5.end_select_label
Definition at line 420 of file flang1/flang1exe/semant.h.
DI_EXIT_LABEL
#define DI_EXIT_LABEL (d) sem.doif_base[d].exit_label
Definition at line 362 of file flang1/flang1exe/semant.h.
DI_FORALL_AST
#define DI_FORALL_AST (d) sem.doif_base[d].u.u6.forall_ast
Definition at line 429 of file flang1/flang1exe/semant.h.
DI_FORALL_DTYPE
#define DI_FORALL_DTYPE (d) sem.doif_base[d].u.u6.dtype
Definition at line 427 of file flang1/flang1exe/semant.h.
DI_FORALL_LASTSTD
#define DI_FORALL_LASTSTD (d) sem.doif_base[d].u.u6.laststd
Definition at line 425 of file flang1/flang1exe/semant.h.
DI_FORALL_SYMAVL
#define DI_FORALL_SYMAVL (d) sem.doif_base[d].u.u6.symavl
Definition at line 426 of file flang1/flang1exe/semant.h.
DI_ID
#define DI_ID (d) sem.doif_base[d].Id
Definition at line 358 of file flang1/flang1exe/semant.h.
DI_IDXLIST
#define DI_IDXLIST (d) sem.doif_base[d].u.u6.idxlist
Definition at line 428 of file flang1/flang1exe/semant.h.
DI_IN_NEST
#define DI_IN_NEST (d, t) (d && d <= sem.doif_depth && (DI_NEST(d) & DI_B(t)))
Definition at line 437 of file flang1/flang1exe/semant.h.
DI_IS_ORDERED
#define DI_IS_ORDERED (d) sem.doif_base[d].u.u4.v.v1.is_ordered
Definition at line 408 of file flang1/flang1exe/semant.h.
DI_IS_WHOLE
#define DI_IS_WHOLE (d) sem.doif_base[d].u.u5.is_whole
Definition at line 418 of file flang1/flang1exe/semant.h.
DI_ISSIMD
#define DI_ISSIMD (d) sem.doif_base[d].u.u4.v.v1.is_simd
Definition at line 409 of file flang1/flang1exe/semant.h.
DI_LASTPRIVATE
#define DI_LASTPRIVATE (d) sem.doif_base[d].u.u4.lastprivate
Definition at line 402 of file flang1/flang1exe/semant.h.
DI_LINENO
#define DI_LINENO (d) sem.doif_base[d].lineno
Definition at line 359 of file flang1/flang1exe/semant.h.
DI_MASKED
#define DI_MASKED (d) sem.doif_base[d].u.u2.masked
Definition at line 383 of file flang1/flang1exe/semant.h.
DI_NAME
#define DI_NAME (d) sem.doif_base[d].name
Definition at line 361 of file flang1/flang1exe/semant.h.
DI_NEST
#define DI_NEST (d) sem.doif_base[d].nest
Definition at line 360 of file flang1/flang1exe/semant.h.
DI_NOSCOPE_AVL
#define DI_NOSCOPE_AVL (d) sem.doif_base[d].no_scope_avail
Definition at line 414 of file flang1/flang1exe/semant.h.
DI_NOSCOPE_BASE
#define DI_NOSCOPE_BASE (d) sem.doif_base[d].no_scope_base
Definition at line 412 of file flang1/flang1exe/semant.h.
DI_NOSCOPE_FORALL
#define DI_NOSCOPE_FORALL (d) sem.doif_base[d].no_scope_forall
Definition at line 415 of file flang1/flang1exe/semant.h.
DI_NOSCOPE_SIZE
#define DI_NOSCOPE_SIZE (d) sem.doif_base[d].no_scope_size
Definition at line 413 of file flang1/flang1exe/semant.h.
DI_PENDING
#define DI_PENDING (d) sem.doif_base[d].u.u3.pending
Definition at line 393 of file flang1/flang1exe/semant.h.
DI_REDUC
#define DI_REDUC (d) sem.doif_base[d].u.u4.reduc
Definition at line 401 of file flang1/flang1exe/semant.h.
DI_REGIONVARS
#define DI_REGIONVARS (d) sem.doif_base[d].u.u4.region_vars
Definition at line 404 of file flang1/flang1exe/semant.h.
DI_SCH_AUTO
#define DI_SCH_AUTO 5
Definition at line 354 of file flang1/flang1exe/semant.h.
DI_SCH_DIST_DYNAMIC
#define DI_SCH_DIST_DYNAMIC 7
Definition at line 356 of file flang1/flang1exe/semant.h.
DI_SCH_DIST_STATIC
#define DI_SCH_DIST_STATIC 6
Definition at line 355 of file flang1/flang1exe/semant.h.
DI_SCH_DYNAMIC
#define DI_SCH_DYNAMIC 1
Definition at line 350 of file flang1/flang1exe/semant.h.
DI_SCH_GUIDED
#define DI_SCH_GUIDED 2
Definition at line 351 of file flang1/flang1exe/semant.h.
DI_SCH_INTERLEAVE
#define DI_SCH_INTERLEAVE 3
Definition at line 352 of file flang1/flang1exe/semant.h.
DI_SCH_RUNTIME
#define DI_SCH_RUNTIME 4
Definition at line 353 of file flang1/flang1exe/semant.h.
DI_SCH_STATIC
#define DI_SCH_STATIC 0
Definition at line 349 of file flang1/flang1exe/semant.h.
DI_SCHED_TYPE
#define DI_SCHED_TYPE (d) sem.doif_base[d].u.u4.v.v1.sched_type
Definition at line 405 of file flang1/flang1exe/semant.h.
DI_SECT_CNT
#define DI_SECT_CNT (d) sem.doif_base[d].u.u4.v.v2.sect_cnt
Definition at line 410 of file flang1/flang1exe/semant.h.
DI_SECT_VAR
#define DI_SECT_VAR (d) sem.doif_base[d].u.u4.v.v2.sect_var
Definition at line 411 of file flang1/flang1exe/semant.h.
DI_SELECT_TYPE_LIST
#define DI_SELECT_TYPE_LIST (d) sem.doif_base[d].u.u5.types
Definition at line 423 of file flang1/flang1exe/semant.h.
DI_SELECTOR
#define DI_SELECTOR (d) sem.doif_base[d].u.u5.selector
Definition at line 417 of file flang1/flang1exe/semant.h.
DI_SHAPEDIM
#define DI_SHAPEDIM (d) sem.doif_base[d].u.u2.shapedim
Definition at line 382 of file flang1/flang1exe/semant.h.
DI_SWEL_HD
#define DI_SWEL_HD (d) sem.doif_base[d].u.u3.swel_hd
Definition at line 389 of file flang1/flang1exe/semant.h.
DI_TOP_LABEL
#define DI_TOP_LABEL (d) sem.doif_base[d].u.u1.top_label
Definition at line 366 of file flang1/flang1exe/semant.h.
DI_TYPE_BEG
#define DI_TYPE_BEG (d) sem.doif_base[d].u.u5.beg_std
Definition at line 421 of file flang1/flang1exe/semant.h.
DOCHK
#define DOCHK (sptr)
Value:
  if (DOVARG(sptr)) { \
    if (sem.doconcurrent_symavl) \
      error(1053, ERR_Severe, gbl.lineno, "DO CONCURRENT", CNULL); \
    else \
      error(115, 2, gbl.lineno, SYMNAME(sptr), CNULL); \
  }
Definition at line 1462 of file flang1/flang1exe/semant.h.
Doend
#define Doend 1
Definition at line 453 of file flang1/flang1exe/semant.h.
Dostart
#define Dostart 0
Definition at line 452 of file flang1/flang1exe/semant.h.
DT_HAS_IO
#define DT_HAS_IO (dt) ((UFIOG(DTY(dt + 3))))
Definition at line 60 of file flang1/flang1exe/semant.h.
DT_HAS_IO_FREAD
#define DT_HAS_IO_FREAD (dt) (((UFIOG(DTY(dt + 3)) & DT_IO_FREAD)))
Definition at line 56 of file flang1/flang1exe/semant.h.
DT_HAS_IO_FWRITE
#define DT_HAS_IO_FWRITE (dt) (((UFIOG(DTY(dt + 3)) & DT_IO_FWRITE)))
Definition at line 58 of file flang1/flang1exe/semant.h.
DT_HAS_IO_UREAD
#define DT_HAS_IO_UREAD (dt) (((UFIOG(DTY(dt + 3)) & DT_IO_UREAD)))
Definition at line 57 of file flang1/flang1exe/semant.h.
DT_HAS_IO_UWRITE
#define DT_HAS_IO_UWRITE (dt) (((UFIOG(DTY(dt + 3)) & DT_IO_UWRITE)))
Definition at line 59 of file flang1/flang1exe/semant.h.
DT_IO_FREAD
#define DT_IO_FREAD 0x2 /* Defined READ(FORMATTED) */
Definition at line 51 of file flang1/flang1exe/semant.h.
DT_IO_FWRITE
#define DT_IO_FWRITE 0x8 /* Defined WRITE(FORMATTED) */
Definition at line 53 of file flang1/flang1exe/semant.h.
DT_IO_NONE
#define DT_IO_NONE 0x1 /* No defined I/O for derived type */
Definition at line 50 of file flang1/flang1exe/semant.h.
DT_IO_UNKNOWN
#define DT_IO_UNKNOWN 0x0 /* Not yet known if derived type has defined I/O */
Definition at line 49 of file flang1/flang1exe/semant.h.
DT_IO_UREAD
#define DT_IO_UREAD 0x4 /* Defined READ(UNFORMATTED) */
Definition at line 52 of file flang1/flang1exe/semant.h.
DT_IO_UWRITE
#define DT_IO_UWRITE 0x10 /* Defined WRITE(UNFORMATTED) */
Definition at line 54 of file flang1/flang1exe/semant.h.
EQV
#define EQV (i) sem.eqv_base[i]
Definition at line 670 of file flang1/flang1exe/semant.h.
EQV_NUMSS
#define EQV_NUMSS (i) sem.eqv_ss_base[i] /* number of subscripts */
Definition at line 671 of file flang1/flang1exe/semant.h.
EQV_SS
#define EQV_SS (i, j) sem.eqv_ss_base[i + j + 1] /* j from 0 to EQV_NUMSS(i) */
Definition at line 672 of file flang1/flang1exe/semant.h.
GET_ACL
#define GET_ACL (a) get_acl(a)
Definition at line 644 of file flang1/flang1exe/semant.h.
IN_MODULE
#define IN_MODULE (sem.mod_cnt && gbl.internal == 0)
Definition at line 1470 of file flang1/flang1exe/semant.h.
IN_MODULE_SPEC
#define IN_MODULE_SPEC (sem.mod_cnt && gbl.currsub == 0)
Definition at line 1471 of file flang1/flang1exe/semant.h.
INSIDE_STRUCT
#define INSIDE_STRUCT (sem.stsk_depth != 0)
Definition at line 1453 of file flang1/flang1exe/semant.h.
IS_INTRINSIC
#define IS_INTRINSIC (st) (st == ST_INTRIN || st == ST_GENERIC || st == ST_PD)
Definition at line 1451 of file flang1/flang1exe/semant.h.
ITEM_END
#define ITEM_END ((ITEM *)1)
Definition at line 112 of file flang1/flang1exe/semant.h.
KEYWD_ARGS2
#define KEYWD_ARGS2 2
Definition at line 38 of file flang1/flang1exe/semant.h.
MAX_DOSTACK
#define MAX_DOSTACK 8
Definition at line 763 of file flang1/flang1exe/semant.h.
NEED_DOIF
#define NEED_DOIF (df, typ)
Value:
  {                                                                      \
    df = ++sem.doif_depth;                                               \
    NEED(df + 1, sem.doif_base, DOIF, sem.doif_size, sem.doif_size + 8); \
    BZERO(sem.doif_base+df, DOIF, 1);                                    \
    DI_LINENO(df) = gbl.lineno;                                          \
    DI_ID(df) = typ;                                                     \
    DI_NEST(df) = DI_NEST(df - 1) | DI_B(typ);                           \
  }
Definition at line 439 of file flang1/flang1exe/semant.h.
NEW_INTRIN
#define NEW_INTRIN 65535 /* (newer) intrinsic with no predefined entry in the symtab */
Definition at line 62 of file flang1/flang1exe/semant.h.
NO_REAL
#define NO_REAL -5 /* if the processor supports no real type with radix RADIX */
Definition at line 37 of file flang1/flang1exe/semant.h.
NOT_GET_VAL
#define NOT_GET_VAL 0 /* 0 is default, This should be ruled out */
Definition at line 36 of file flang1/flang1exe/semant.h.
NTYPE
#define NTYPE 23
Definition at line 1447 of file flang1/flang1exe/semant.h.
onel
#define onel 1ULL
Definition at line 435 of file flang1/flang1exe/semant.h.
PAR_SCOPE_FIRSTPRIVATE
#define PAR_SCOPE_FIRSTPRIVATE 3
Definition at line 826 of file flang1/flang1exe/semant.h.
PAR_SCOPE_NONE
#define PAR_SCOPE_NONE 0
Definition at line 823 of file flang1/flang1exe/semant.h.
PAR_SCOPE_PRIVATE
#define PAR_SCOPE_PRIVATE 2
Definition at line 825 of file flang1/flang1exe/semant.h.
PAR_SCOPE_SHARED
#define PAR_SCOPE_SHARED 1
Definition at line 824 of file flang1/flang1exe/semant.h.
PAR_SCOPE_TASKNODEFAULT
#define PAR_SCOPE_TASKNODEFAULT 4
Definition at line 827 of file flang1/flang1exe/semant.h.
POW1
#define POW1 1
Definition at line 32 of file flang1/flang1exe/semant.h.
POW2
#define POW2 2
Definition at line 33 of file flang1/flang1exe/semant.h.
RADIX2
#define RADIX2 2 /* Binary */
Definition at line 35 of file flang1/flang1exe/semant.h.
S_ACONST
#define S_ACONST 13 /* array constant */
Definition at line 27 of file flang1/flang1exe/semant.h.
S_CONST
#define S_CONST 1 /* scalar constant */
Definition at line 15 of file flang1/flang1exe/semant.h.
S_DERIVED
#define S_DERIVED 15 /* derived type object */
Definition at line 29 of file flang1/flang1exe/semant.h.
S_EXPR
#define S_EXPR 2 /* expression */
Definition at line 16 of file flang1/flang1exe/semant.h.
S_IDENT
#define S_IDENT 7 /* identifier, possibly a whole variable */
Definition at line 21 of file flang1/flang1exe/semant.h.
S_KEYWORD
#define S_KEYWORD 12 /* keyword, not an identifier */
Definition at line 26 of file flang1/flang1exe/semant.h.
S_LABEL
#define S_LABEL 8 /* label */
Definition at line 22 of file flang1/flang1exe/semant.h.
S_LOGEXPR
#define S_LOGEXPR 4 /* (obsolete; was logical expression) */
Definition at line 18 of file flang1/flang1exe/semant.h.
S_LVALUE
#define S_LVALUE 3 /* non-whole variable */
Definition at line 17 of file flang1/flang1exe/semant.h.
S_NULL
#define S_NULL 0 /* empty/invalid */
Definition at line 14 of file flang1/flang1exe/semant.h.
S_REF
#define S_REF 10 /* %REF(expr) argument (VMS)*/
Definition at line 24 of file flang1/flang1exe/semant.h.
S_SCONST
#define S_SCONST 14 /* structure constant */
Definition at line 28 of file flang1/flang1exe/semant.h.
S_STAR
#define S_STAR 5 /* * */
Definition at line 19 of file flang1/flang1exe/semant.h.
S_STFUNC
#define S_STFUNC 9 /* statement function reference */
Definition at line 23 of file flang1/flang1exe/semant.h.
S_TRIPLE
#define S_TRIPLE 11 /* j:k:m */
Definition at line 25 of file flang1/flang1exe/semant.h.
S_VAL
#define S_VAL 6 /* %VAL(expr) argument (VMS) */
Definition at line 20 of file flang1/flang1exe/semant.h.
STSK_ENT
#define STSK_ENT (i) sem.stsk_base[sem.stsk_depth - (i)-1]
Definition at line 656 of file flang1/flang1exe/semant.h.
Varref
#define Varref 2
Definition at line 454 of file flang1/flang1exe/semant.h.
XFR_ARGAST
#define XFR_ARGAST (i) ARG_AST(i) = SST_ASTG(ARG_STK(i))
Definition at line 751 of file flang1/flang1exe/semant.h.
Typedef Documentation
ACCL
typedef struct _accl ACCL
ACL
typedef struct _acl ACL
AEXPR
typedef struct _aexpr AEXPR
Definition at line 486 of file flang1/flang1exe/semant.h.
dimMask
typedef enum dimMask dimMask
These are constants used by SST_DIMFLAG and A_MASK to represent empty subscripts (e.g., (:), (:,:), (:,:,:), etc.)
EQVV
typedef struct equiv_var EQVV
IDENT_LIST
typedef struct ident_list IDENT_LIST
IDENT_PROC_LIST
typedef struct ident_proc_list IDENT_PROC_LIST
ITEM
typedef struct xyyz ITEM
NOSCOPE_SYM
typedef struct noscope_sym NOSCOPE_SYM
REDUC
typedef struct reduc_tag REDUC
REDUC_SYM
typedef struct reduc_sym REDUC_SYM
SCOPE_SYM
typedef struct scope_sym_tag SCOPE_SYM
SCOPEKIND
typedef enum SCOPEKIND SCOPEKIND
SEQL
typedef struct _seql SEQL
STD_RANGE
typedef struct _std_range STD_RANGE
STD_RECORD
typedef struct _std_record STD_RECORD
tbpTask
typedef enum tbpTasks tbpTask
Constants representing tasks for type bound procedure (tbp) processing.
These are used with the task argument in the queue_tbp() function.
TYPE_LIST
typedef struct type_list TYPE_LIST
VAR
typedef struct var_init VAR
Enumeration Type Documentation
AC_INTRINSIC
enum AC_INTRINSIC
Enumerator
AC_I_NONE
AC_I_adjustl
AC_I_adjustr
AC_I_char
AC_I_ichar
AC_I_index
AC_I_int
AC_I_ishft
AC_I_ishftc
AC_I_kind
AC_I_lbound
AC_I_len
AC_I_len_trim
AC_I_nint
AC_I_null
AC_I_repeat
AC_I_reshape
AC_I_scan
AC_I_selected_int_kind
AC_I_selected_real_kind
AC_I_size
AC_I_transfer
AC_I_trim
AC_I_ubound
AC_I_verify
AC_I_shape
AC_I_min
AC_I_max
AC_I_fltconvert
AC_I_floor
AC_I_ceiling
AC_I_mod
AC_I_sqrt
AC_I_exp
AC_I_log
AC_I_log10
AC_I_sin
AC_I_cos
AC_I_tan
AC_I_asin
AC_I_acos
AC_I_atan
AC_I_atan2
AC_I_selected_char_kind
AC_I_abs
AC_I_iand
AC_I_ior
AC_I_ieor
AC_I_merge
AC_I_lshift
AC_I_rshift
AC_I_maxloc
AC_I_maxval
AC_I_minloc
AC_I_minval
AC_I_scale
AC_I_transpose
Definition at line 578 of file flang1/flang1exe/semant.h.
DI_KIND
enum DI_KIND
Enumerator
DI_IF
DI_IFELSE
DI_DO
DI_DOCONCURRENT
DI_DOWHILE
DI_WHERE
DI_ELSEWHERE
DI_FORALL
DI_CASE
DI_SELECT_TYPE
DI_ASSOC
DI_BLOCK
DI_FIRST_DIRECTIVE
DI_PAR
DI_PARDO
DI_PDO
DI_DOACROSS
DI_PARSECTS
DI_SECTS
DI_SINGLE
DI_CRITICAL
DI_MASTER
DI_ORDERED
DI_WORKSHARE
DI_PARWORKS
DI_TASK
DI_ATOMIC_CAPTURE
DI_SIMD
DI_TASKGROUP
DI_TASKLOOP
DI_TARGET
DI_TARGETENTERDATA
DI_TARGETEXITDATA
DI_TARGETDATA
DI_TARGETUPDATE
DI_DISTRIBUTE
DI_TEAMS
DI_DECLTARGET
DI_DISTPARDO
DI_TARGPARDO
DI_TARGETSIMD
DI_TARGTEAMSDIST
DI_TEAMSDIST
DI_TARGTEAMSDISTPARDO
DI_TEAMSDISTPARDO
DI_CUFKERNEL
DI_ACCREG
DI_ACCKERNELS
DI_ACCPARALLEL
DI_ACCDO
DI_ACCLOOP
DI_ACCREGDO
DI_ACCREGLOOP
DI_ACCKERNELSDO
DI_ACCKERNELSLOOP
DI_ACCPARALLELDO
DI_ACCPARALLELLOOP
DI_ACCKERNEL
DI_ACCDATAREG
DI_ACCHOSTDATA
DI_ACCSERIAL
DI_ACCSERIALLOOP
DI_MAXID
Definition at line 160 of file flang1/flang1exe/semant.h.
dimMask
enum dimMask
These are constants used by SST_DIMFLAG and A_MASK to represent empty subscripts (e.g., (:), (:,:), (:,:,:), etc.)
Enumerator
lboundMask
empty lower bound mask
uboundMask
empty upper bound mask
strideMask
empty stride mask
Definition at line 1695 of file flang1/flang1exe/semant.h.
distlooptype
enum distlooptype
Enumerator
LP_PDO
LP_PARDO
LP_DISTRIBUTE
LP_DIST_TEAMS
LP_DIST_TARGTEAMS
LP_DISTPARDO
LP_DISTPARDO_TEAMS
LP_DISTPARDO_TARGTEAMS
LP_PARDO_OTHER
Definition at line 114 of file flang1/flang1exe/semant.h.
PHASE_TYPE
enum PHASE_TYPE
Enumerator
PHASE_END_MODULE
PHASE_INIT
PHASE_HEADER
PHASE_USE
PHASE_IMPORT
PHASE_IMPLICIT
PHASE_SPEC
PHASE_EXEC
PHASE_CONTAIN
PHASE_INTERNAL
PHASE_END
Definition at line 1108 of file flang1/flang1exe/semant.h.
SCOPEKIND
enum SCOPEKIND
Enumerator
SCOPE_OUTER
SCOPE_NORMAL
SCOPE_MODULE
SCOPE_SUBPROGRAM
SCOPE_BLOCK
SCOPE_INTERFACE
SCOPE_USE
SCOPE_PAR
Definition at line 779 of file flang1/flang1exe/semant.h.
tbpTasks
enum tbpTasks
Constants representing tasks for type bound procedure (tbp) processing.
These are used with the task argument in the queue_tbp() function.
Enumerator
TBP_CLEAR_ERROR
Clear all entries in queue after an error
TBP_CLEAR
Clear all entries after normal processing
TBP_CLEAR_STALE_RECORDS
Clear tbp_queue entries with stale dtypes
TBP_ADD_SIMPLE
Add tbp after parsing simple tbp (e.g., procedure tbp;)
TBP_ADD_TO_DTYPE
Add tbps to derived type dtype records
TBP_COMPLETE_ENDMODULE
Complete tbp ST_MEMBERs in derived type after parsing ENDMODULE
TBP_ADD_INTERFACE
Add interface name to queue if user specified one
TBP_ADD_IMPL
Add binding name and implementation name to queue. Occurs when we parse something like procedure x => y (where x is the binding name and y is the implementation name).
TBP_PASS
Specify explicit pass argument for tbp
TBP_COMPLETE_FIN
Complete tbp ST_MEMBERS after processing module CONTAINS, etc. Called from semfin()
TBP_INHERIT
Copy inherited tbps from parent type to child type
TBP_NOPASS
Specify NOPASS attribute for tbp
TBP_NONOVERRIDABLE
Specify NON_OVERRIDABLE attribute for tbp
TBP_PRIVATE
Specify PRIVATE attribute for tbp
TBP_PUBLIC
Specify PUBLIC attribute for tbp
TBP_STATUS
Check to see if we have tbps to add to a derived type
TBP_DEFERRED
Specify DEFERRED attribute for tbp
TBP_IFACE
Specify an external routine via an explicit interface for the tbp's implementation
TBP_COMPLETE_END
Complete tbp ST_MEMBERs after parsing ENDFUNCTION, ENPROGRAM, ENSUBROUTINE outside the scope of a module.
TBP_COMPLETE_ENDTYPE
Complete tbp ST_MEMBERs after parsing ENDTYPE outside the scope of a module.
TBP_CHECK_CHILD
Check validity of child tbp with parent tbp
TBP_CHECK_PRIVATE
Check validity of private child tbp with parent tbp
TBP_CHECK_PUBLIC
Check validity of public child tbp with parent tbp
TBP_COMPLETE_GENERIC
Complete tbp ST_MEMBERs for generic tbps. This task is invoked in various places of generic and operator processing.
TBP_ADD_FINAL
Add final subroutine to queue
TBP_FORCE_RESOLVE
Force resolution of tbps in tbpQueue
Definition at line 1646 of file flang1/flang1exe/semant.h.
Function Documentation
_char_cmp()
int _char_cmp (int l, int r)
Definition at line 8401 of file semutil2.c.
Referenced by semant3().
_i4_cmp()
int _i4_cmp (int l, int r)
Compare functions whose arguments are pointers to ST_CONST symbol table entries.
Returns
a number less than, equal to, or greater than 0, depending on the comparison
Definition at line 8375 of file semutil2.c.
Referenced by llvm_omp_sched(), and semant3().
_i8_cmp()
int _i8_cmp (int l, int r)
Definition at line 8389 of file semutil2.c.
Referenced by llvm_omp_sched(), and semant3().
_nchar_cmp()
int _nchar_cmp (int l, int r)
Definition at line 8411 of file semutil2.c.
Referenced by semant3().
_selected_char_kind()
int _selected_char_kind (int con)
Check charset.
Make sure this routine is consistent with
f90: dinit.c:_selected_char_kind()
runtime/f90: miscsup_com.c:_selected_char_kind()
Definition at line 12538 of file semfunc.c.
References sem_eq_str().
Referenced by ref_pd().
accel_end_dir()
void accel_end_dir (int , LOGICAL)
add_assign_firstprivate()
void add_assign_firstprivate (int dstsym, int srcsym)
Add an assignment to the parallel prologue.
Parameters
dstsym The symbol assigned to.
srcsym The symbol assigned from.
Definition at line 8922 of file semsmp.c.
References add_stmt_after(), assign(), assign_pointer(), ast, BLK_UPLEVEL_SPTR, SCOPESTACK::end_prologue, interr(), mk_id(), mk_stmt(), mk_storage(), SEM::parallel, S_IDENT, SEM::scope_level, SEM::scope_stack, sem, set_parref_flag(), SST_ASTP, SST_DTYPEP, SST_IDP, SST_SYMG, SST_SYMP, SEM::target, SEM::task, and void().
Referenced by sem_check_scope().
add_auto_dealloc()
void add_auto_dealloc (int sptr)
Definition at line 12299 of file semutil2.c.
References SEM::auto_dealloc, getitem(), itemp, sem, and sptr.
Referenced by check_and_add_auto_dealloc(), func_call2(), misc_checks(), and sem_set_storage_class().
add_auto_finalize()
void add_auto_finalize (int sptr)
Definition at line 12354 of file semutil2.c.
References SEM::auto_finalize, getitem(), itemp, sem, and sptr.
Referenced by semant1().
add_case_range()
void add_case_range (int doif, int lc, int uc)
Update the SWEL list for a SELECTCASE construct represented by the doif structure.
A new SWEL item is created for a case value or a range of case values denoted by the arguments lc and uc. The order of the items in the list will correspond to the case values in ascending order.
Kind of case lc uc
case (:c) c -1
case (c) c 0 (c is a sym pointer)
case (c:) c 1
case (c:d) c d (c and d are sym pointers)
Definition at line 8279 of file semutil2.c.
Referenced by semant3().
add_isoc_intrinsics()
void add_isoc_intrinsics (void)
Definition at line 805 of file module.c.
References first, i, iso_c_lib_stat(), last, size, and sptr.
Referenced by add_to_be_used_list().
add_no_scope_sptr()
void add_no_scope_sptr (int oldsptr, int newsptr, int lineno)
Definition at line 9579 of file semsmp.c.
References BZERO, DI_NOSCOPE_AVL, DI_NOSCOPE_BASE, DI_NOSCOPE_SIZE, SEM::doif_depth, gbl, i, lineno, NEED, and sem.
Referenced by sem_check_scope(), and semant3().
add_non_private()
void add_non_private (int sptr)
Definition at line 9554 of file semsmp.c.
References i, NEED, SEM::non_private_avail, SEM::non_private_base, SEM::non_private_size, sem, and sptr.
Referenced by _non_private().
add_overload()
void add_overload (int gnr, int func)
Definition at line 1863 of file semgnr.c.
References add_symitem(), DBGBIT, SEM::defined_io_type, func, gbl, sem, and SYMNAME.
Referenced by copy_specifics(), resolveGeneric(), and semant1().
add_p_dealloc_item()
void add_p_dealloc_item (int sptr)
Definition at line 718 of file semutil2.c.
References add_etmp(), DI_FORALL, DI_ID, SEM::doif_depth, getitem(), itemp, mk_id(), SEM::p_dealloc, sem, sptr, and SEM::use_etmps.
Referenced by func_call2(), gen_allocate_array(), and ptrfunc_call().
add_parent_to_bounds()
int add_parent_to_bounds (int parent, int ast)
Definition at line 12507 of file semutil2.c.
References A_OPTYPEG, add_parent_to_bounds(), ARGT_ARG, ast, get_parm_ast(), i, interr(), parent, and sym_of_ast().
Referenced by add_parent_to_bounds(), copy_surrogate_to_bnds_vars(), fix_mem_bounds(), fix_mem_bounds2(), fix_type_param_members(), and gen_kind_parm_assignments().
add_ptr_assign()
int add_ptr_assign (int dest, int src, int std)
Definition at line 4144 of file semutil.c.
References A_OPTYPEG, A_OPTYPEP, add_arg(), add_stmt(), add_stmt_after(), add_stmt_before(), ARGT_ARG, ast, ast_is_sym(), astb, begin_call(), ASTB::bnd, check_member(), cmp_interfaces_strict(), CNULL, create_parameterized_dt(), dest, DTY, dtype, ASTB::dtype, dup_array_dtype(), ERR_Severe, error(), func, gbl, gen_contig_check(), get_len_of_deferchar_ast(), get_member_descriptor(), get_static_descriptor(), has_type_parameter(), IGNORE_ARG_NAMES, intast_sym, is_dtype_unlimited_polymorphic(), memsym_of_ast(), mk_argt(), mk_assn_stmt(), mk_cval(), mk_func_node(), mk_id(), mk_stmt(), mkRteRtnNm(), NOSYM, NULL, proc_arginfo(), RELAX_STYPE_CHK, RTE_asn_closure, src, std, string_expr_length(), sym_mkfunc_nodesc(), SYMNAME, TY_CHAR, and XBIT.
Referenced by _constructf90(), assign_intrinsic_to_pointer(), assign_pointer(), construct_association(), gen_and_assoc_tmp_ptr(), gen_poly_element_arg(), handle_allocatable_members(), rewrite_allocatable_assignment(), semant3(), and transform_call().
add_submodule_use()
void add_submodule_use (void)
Definition at line 243 of file module.c.
References assert, ERR_Fatal, module_id, NO_MODULE, TRUE, and usedb.
Referenced by semant1().
add_type_param_initialize()
void add_type_param_initialize (int sptr)
Definition at line 12334 of file semutil2.c.
References DTY, getitem(), has_type_parameter(), itemp, sem, sptr, and SEM::type_initialize.
Referenced by semant1().
add_use_rename()
SPTR add_use_rename (SPTR local, SPTR global, LOGICAL is_operator)
Process a USE ONLY statement, optionally renaming 'global' as 'local'. The module is specified in 'module_id'.
Returns
The updated global symbol.
The USE statement can be any of these forms: USE module, ONLY: global USE module, ONLY: local => global USE module, ONLY: OPERATOR(.xx.) USE module, ONLY: ASSIGNMENT(=) is_operator is set for the last two.
Definition at line 267 of file module.c.
References assert, _rename::complete, FLG::debug, ERR_Fatal, flg, gbl, getitem(), _rename::global, _rename::is_operator, _rename::lineno, _rename::local, module_id, _rename::next, NO_MODULE, NOSYM, set_modusename(), SPTR_NULL, SYMNAME, USE_AREA, and usedb.
Referenced by semant1().
add_use_stmt()
void add_use_stmt (void)
Process a "USE module" statement. The module is specified in module_id.
Definition at line 235 of file module.c.
References assert, ERR_Fatal, module_id, NO_MODULE, TRUE, and usedb.
Referenced by semant1().
all_default_init()
ACL * all_default_init (DTYPE dtype)
Check whether derived type has components with default initializations.
Parameters
dtype is the derived type we want to check.
Returns
pointer to first default initializer, else NULL.
Definition at line 5653 of file semutil2.c.
References all_default_init(), clone_init_const(), DTC_DEFAULT, DTC_DEFAULT_CNT, DTY, is_tbp_or_final(), mem(), NOSYM, and NULL.
Referenced by all_default_init(), lower_symbol(), and semant2().
all_len_parms_assumed()
int all_len_parms_assumed (int dtype)
Return 0 if there's at least one length type parameter that is not assumed. Otherwise return 1.
Definition at line 15883 of file semant.c.
References all_len_parms_assumed(), DTY, i, mem(), and NOSYM.
Referenced by all_len_parms_assumed(), and check_defined_io2().
allocatable_member()
LOGICAL allocatable_member (int sptr)
Return TRUE if sptr is a derived type with an allocatable member.
Definition at line 567 of file semfunc.c.
References allocatable_member(), DDTG, DTY, DTYG, FALSE, is_tbp_or_final(), NOSYM, sptr, and TRUE.
Referenced by add_alloc_mem_initialize(), allocatable_member(), ast_has_allocatable_member(), check_derived_type_in_comm(), decl_private_sym(), func_call2(), gen_alloc_mem_initialize_for_sym2(), gen_dealloc_mbr(), handle_allocatable_members(), init_derived_type(), need_tmp_retval(), nullify_member_after(), ptrfunc_call(), rewrite_allocatable_assignment(), rewrite_calls(), rewrite_deallocate(), and semfin().
allocate_refsymbol()
void allocate_refsymbol (int symavl)
Definition at line 110 of file module.c.
References ref_symbol::altname, BZERO, dbgref_symbol, malloc(), NULL, ref_symbol::size, and ref_symbol::symnum.
Referenced by plower(), and set_modusename().
any_pointer_source()
int any_pointer_source (int ast)
Definition at line 4624 of file semutil.c.
References ast.
Referenced by chk_pointer_target(), and ref_pd().
apply_use_stmts()
void apply_use_stmts (void)
Definition at line 352 of file module.c.
References add_predefined_ieeearith_module(), add_predefined_iso_fortran_env_module(), add_predefined_isoc_module(), apply_use(), CNULL, ERR_Severe, error(), exportb, FIRST_USER_MODULE, FREE, freearea(), gbl, EXPORTB::ieee_arith_library, IEEE_ARITH_MOD, SEM::ieee_features, IEEE_FEATURES_MOD, IN_MODULE, SEM::interface, EXPORTB::iso_c_library, ISO_C_MOD, ISO_FORTRAN_ENV, EXPORTB::iso_fortran_env_library, module_id, NEED, NEW, NO_MODULE, NOSYM, NULL, pd_mod_entries, remove_from_use_tree(), SEM::scope_level, sem, SYMNAME, TRUE, USE_AREA, usedb, and XBIT.
Referenced by semant1().
ast_isparam()
LOGICAL ast_isparam (int ast)
Definition at line 2614 of file semutil.c.
References A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, ast, ast_isparam(), FALSE, i, ndim, ss, TRUE, and val.
Referenced by ast_isparam(), ref_array(), and semant1().
begin_contains()
void begin_contains (void)
Definition at line 1174 of file module.c.
References errsev(), FALSE, fix_module_common(), handle_mod_syms_dllexport(), SEM::mod_cnt, save_implicit(), save_module_state1(), save_module_state2(), seen_contains, sem, and TRUE.
Referenced by semant1().
begin_module()
SPTR begin_module (SPTR id)
Definition at line 1056 of file module.c.
References declsym(), FALSE, FUNCLINEP, gbl, impl, init_use_tree(), SEM::mod_dllexport, mod_lineno, modu_name, modu_sym, NEW, NULL, outfile, seen_contains, sem, SYMNAME, and TRUE.
Referenced by begin_submodule(), and semant1().
begin_submodule()
SPTR begin_submodule (SPTR id, SPTR ancestor_mod, SPTR parent_submod, SPTR * parent)
Definition at line 1082 of file module.c.
References begin_module(), ERR_Severe, error(), STB::firstusym, gbl, get_submod_sym(), insert_sym(), NOSYM, parent, stb, and SYMNAME.
Referenced by semant1().
bind_intrinsic_opr()
void bind_intrinsic_opr (int val, int opr)
Definition at line 1033 of file semgnr.c.
References optabstruct::opr, optab, and val.
Referenced by fill_links_symbol(), and get_intrinsic_opr().
block_local_sym()
SPTR block_local_sym (SPTR sptr)
Return a symbol local to the current BLOCK if applicable.
Parameters
sptr symbol (index), possibly declared in an enclosing scope.
Returns
symbol in the current BLOCK if in a BLOCK (which may be the original \sptr); otherwise return original \sptr.
This function should be called when a symbol might be declared in an ancestor subprogram or block, but should be redeclared as a symbol in the current BLOCK.
Definition at line 1538 of file semsym.c.
References SEM::block_scope, SEM::construct_sptr, insert_sym(), INSIDE_STRUCT, SEM::scope_stack, sem, sptr, and SCOPESTACK::symavl.
Referenced by getcctmp(), semant1(), semant2(), and semant3().
build_typedef_init_tree()
void build_typedef_init_tree (int sptr, int dtype)
Definition at line 13468 of file semant.c.
References AD_NUMELM, AD_PTR, astb, DDTG, dinit_no_dinitp(), DTY, GET_ACL, get_getitem_p(), ASTB::i1, STSK::ict_beg, STSK::ict_end, INSIDE_STRUCT, _acl::next, NULL, _acl::repeatc, save_struct_init(), sptr, _acl::sptr, and stsk.
Referenced by misc_checks(), and semant1().
check_alloc_clauses()
void check_alloc_clauses (ITEM * list, ITEM * spec, int * srcast, int * mold_or_src)
Definition at line 12106 of file semutil2.c.
References CNULL, error(), firstalloc, gbl, ITEM_END, itemp, list, spec, and stat.
Referenced by semant3().
check_and_add_auto_dealloc()
void check_and_add_auto_dealloc (int sptr)
Definition at line 12274 of file semutil2.c.
References add_auto_dealloc(), gbl, RU_FUNC, RU_SUBR, SEM::savall, SEM::scope_level, SEM::scope_stack, sem, sptr, and SCOPESTACK::sptr.
Referenced by check_and_add_auto_dealloc_from_ast(), and semant2().
check_and_add_auto_dealloc_from_ast()
void check_and_add_auto_dealloc_from_ast (int ast)
Definition at line 12266 of file semutil2.c.
References ast, check_and_add_auto_dealloc(), sptr, and sym_of_ast().
Referenced by gen_automatic_reallocation(), mk_ptr_subscr(), and semant3().
check_arguments()
LOGICAL check_arguments (int ext, int count, ITEM * list, char * kwd_str)
Check arguments passed to a user subprogram which has an interface block. Its keyword string is available and is located by kwd_str.
Definition at line 2125 of file semfunc2.c.
References chk_arguments(), count, list, and NULL.
Referenced by func_call2(), and subr_call2().
check_dealloc_clauses()
void check_dealloc_clauses (ITEM * list, ITEM * spec)
Definition at line 12075 of file semutil2.c.
References CNULL, error(), firstalloc, gbl, ITEM_END, itemp, list, spec, and stat.
Referenced by semant3().
check_defined_io()
void check_defined_io (void)
Definition at line 1818 of file semgnr.c.
References check_defined_io2().
Referenced by do_end_subprogram(), and semant1().
check_derived_type_array_section()
void check_derived_type_array_section (int ast)
Give error message for reference like a(:)b(:)
Definition at line 3395 of file semutil.c.
References ASD_NDIM, ASD_SUBS, ast, DTY, error(), FLANG_FALLTHROUGH, gbl, i, mem(), memsym_of_ast(), ndim, parent, sptr, ss, subscr, and SYMNAME.
Referenced by assign(), and semant2().
check_doconcurrent()
void check_doconcurrent (int doif)
Check a DO CONCURRENT loop for constraint violations.
Parameters
doif DO CONCURRENT doif stack slot index
Definition at line 5993 of file semant3.c.
References add_symitem(), ast_traverse(), ast_unvisit(), ast_visit(), check_doconcurrent_ast(), SCN::currlab, DC_BODY, DC_HEADER, DC_MASK, DI_CONC_BODY_STD, DI_CONC_COUNT, DI_CONC_KIND, DI_CONC_LABEL_SYMS, DI_CONC_MASK_STD, DI_CYCLE_LABEL, DI_DOINFO, DI_LINENO, gbl, i, DOINFO::init_expr, DOINFO::limit_expr, NULL, scn, std, STD_AST, STD_LABEL, STD_LINENO, STD_NEXT, and DOINFO::step_expr.
Referenced by do_end().
check_generic()
void check_generic (int gnr)
Definition at line 142 of file semgnr.c.
References assert.
Referenced by semant1(), and subr_call2().
check_no_scope_sptr()
void check_no_scope_sptr (void)
Definition at line 9627 of file semsmp.c.
References clear_no_scope_sptr(), DI_NOSCOPE_AVL, DI_NOSCOPE_BASE, DI_NOSCOPE_FORALL, SEM::doif_depth, error(), gbl, i, sem, and SYMNAME.
Referenced by semant1(), and semant3().
CheckDecl()
void CheckDecl (int sptr)
Check that sptr is declared if IMPLICIT NONE is set.
Be careful about the situation where IMPLICIT NONE is in the host, but there are IMPLICIT statements in the contained subprogram.
Definition at line 3074 of file semfin.c.
References CNULL, error(), gbl, IN_MODULE, SEM::mod_cnt, SEM::none_implicit, sem, sptr, SYMNAME, was_implicit(), SEM::which_pass, and XBIT.
chk_adjarr()
void chk_adjarr (void)
Definition at line 88 of file semutil2.c.
References arg, aux, cnt, AUX::dpdsc_base, FALSE, gbl, NOSYM, RU_FUNC, RU_PROG, RU_SUBR, RUNTIMEG, to_assumed_shape(), and TRUE.
Referenced by semant1().
chk_arguments()
LOGICAL chk_arguments (int ext, int count, ITEM * list, char * kwd_str, int paramct, int dpdsc, int callee, int * p_pass_pos)
Check arguments passed to a user subprogram which has an interface block. Its keyword string is available and is located by kwd_str.
NOTE: if callee is non-zero, the call is via some procedure pointer, and callee is the ast of pointer and ext will be the sptr of the pointer variable or member. Otherwise, callee is 0 and ext is the sptr of the subroutine/function.
Definition at line 2142 of file semfunc2.c.
References A_ARGCNTG, A_ISLVAL, A_OPTYPEG, ADD_NUMDIM, arg, ARG_AST, ARG_STK, aux, buf, chk_pointer_intent(), chkarg(), cmpat_arr_arg(), cngtyp(), CNULL, compat_arg_lists(), count, DDTG, different_type_same_kind(), AUX::dpdsc_base, DT_ISDWORD, DT_ISNUMERIC, DT_ISWORD, DTY, DTYG, eq_dtype(), eq_dtype2(), err_protected(), error(), FALSE, find_pointer_variable(), FLANG_FALLTHROUGH, flg, gbl, get_generic_member(), get_keyword_args(), get_kwd_args(), i, IGNORE_K, IGNORE_R, IGNORE_T, ignore_tkr(), INTENT_IN, INTENT_INOUT, INTENT_OUT, INTENTG, IS_CHAR_TYPE, is_iso_cloc(), is_protected(), list, mem(), memsym_of_ast(), mk_convert(), NULL, proc_arginfo(), s, same_type_different_kind(), SHD_NDIM, SHD_UPB, simply_contiguous(), sptr, ss, FLG::standard, sym_of_ast(), SYMNAME, tk_match_arg(), tmp, TRUE, TY_CHAR, TY_DWORD, TY_NCHAR, TY_WORD, user_subr, void(), and XFR_ARGAST.
Referenced by check_arguments(), ptrfunc_call(), and ptrsubr_call().
chk_constructor()
DTYPE chk_constructor (ACL * aclp, DTYPE dtype)
Check the array constructor and decide the dtype.
It is called when we first recognize an array constructor.
Definition at line 1464 of file semutil2.c.
References AC_ACONST, acs, _ACS::aggr_cnt, SEM::arrdim, _ACS::arrtype, assert, astb, ASTB::bnd, SEM::bounds, BZERO, compute_size(), DBGBIT, SEM::dostack, DTY, _acl::dtype, dtype, ASTB::dtype, _ACS::eltype, FALSE, gbl, SEM::gcvlen, get_type(), ASTB::i1, _acl::id, _acl::is_const, _ACS::is_const, is_deferlenchar_dtype(), mk_arrdsc(), mk_binop(), mk_isz_cval(), OP_ADD, printacl(), restore_dim_specs(), S_CONST, S_EXPR, save_dim_specs(), _ACS::scalar_cnt, sem, _acl::size, _acl::subc, SEM::top, TRUE, TY_CHAR, TY_NCHAR, ASTB::zero, and _ACS::zln.
Referenced by semant2().
chk_kind_parm_expr()
int chk_kind_parm_expr (int ast, int dtype, int flag, int strict_flag)
Definition at line 15062 of file semant.c.
References A_OPTYPEG, ARGT_ARG, ast, chk_kind_parm_expr(), get_kind_parm(), get_kind_parm_strict(), i, offset, queue_type_param(), sptr, and TRUE.
Referenced by _mk_arrdsc(), chk_initialization_with_kind_parm(), chk_kind_parm_expr(), gen_kind_parm_assignments(), put_kind_type_param(), and semant1().
chk_len_parm_expr()
int chk_len_parm_expr (int ast, int dtype, int flag)
Definition at line 15235 of file semant.c.
References ast, chk_len_parm_expr(), get_len_parm(), offset, queue_type_param(), sptr, ST_ISVAR, and TRUE.
Referenced by _mk_arrdsc(), chk_len_parm_expr(), and semant1().
chk_pointer_intent()
int chk_pointer_intent (int pvar, int refast)
Definition at line 4602 of file semutil.c.
References error(), gbl, getbase(), INTENT_IN, INTENTG, ss, and SYMNAME.
Referenced by assign_pointer(), chk_arguments(), and semant3().
chk_pointer_target()
int chk_pointer_target (int pvar, int source)
Definition at line 4649 of file semutil.c.
References any_pointer_source(), CNULL, DDTG, DT_ISCMPLX, err_protected(), error(), F77OUTPUT, find_pointer_target(), gbl, is_procedure_ptr(), is_protected(), SYMNAME, and XBIT.
Referenced by _constructf90(), and assign_pointer().
chk_struct_constructor()
void chk_struct_constructor (ACL * in_aclp)
Definition at line 6226 of file semutil2.c.
References A_OPTYPEG, AC_ACONST, AC_AST, AC_EXPR, AC_SCONST, ACL_AREA, assert, ast, _acl::ast, check_member(), cmpat_dtype_with_size(), cnt, CNULL, DBGBIT, DDTG, DT_PTR, DTC_ACL, DTY, _acl::dtype, dtype, error(), FREE, gbl, GET_ACL, get_all_descriptors(), get_keyword_components(), get_static_descriptor(), get_struct_default_init(), getitem(), STB::i0, _acl::id, is_illegal_expr_in_init(), is_tbp_or_final(), keyword(), make_structkwd_str(), mk_id(), _acl::next, no_data_components(), NOSYM, NULL, printacl(), _acl::ptrdtype, rank_of(), _acl::repeatc, S_CONST, S_EXPR, S_IDENT, S_LVALUE, set_exttype_list(), SHD_NDIM, _acl::size, sptr, SST_ASTG, SST_ASTP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_LSYMG, SST_LSYMP, SST_SHAPEP, SST_SYMG, SST_SYMP, stb, _acl::stkp, _acl::subc, SYMNAME, and _acl::u1.
Referenced by resolve_generic(), semant1(), and semant2().
clean_struct_default_init()
void clean_struct_default_init (int sptr)
Definition at line 5520 of file semutil2.c.
References DTC_ACL_HEAD, DTC_DEFAULT, DTC_DEFAULT_CNT, DTC_DEFAULT_HEAD, DTC_DT_CNT, FREE, i, NULL, and sptr.
Referenced by semant_init().
clear_no_scope_sptr()
void clear_no_scope_sptr (void)
Definition at line 9610 of file semsmp.c.
References DI_NOSCOPE_AVL, DI_NOSCOPE_BASE, SEM::doif_depth, i, pop_sym(), and sem.
Referenced by check_no_scope_sptr(), and semant3().
close_module()
void close_module (void)
Definition at line 993 of file module.c.
Referenced by semant1().
cmp_len_parms()
int cmp_len_parms (int ast1, int ast2)
Definition at line 15335 of file semant.c.
References A_OPTYPEG, cmp_len_parms(), and CONVAL2G.
Referenced by cmp_len_parms(), and semant3().
collapse_add()
int collapse_add (DOINFO * doinfo)
Process an ensuing loop which is being collapsed.
Definition at line 6174 of file semutil.c.
References add_stmt(), ast, astb, BLK_SYM, chktyp(), coll_st, DOINFO::collapse, SEM::collapse, SEM::collapse_depth, collapse_expr(), collapse_index(), DOINFO::count, DI_CONC_BLOCK_SYM, DI_DOCONCURRENT, DI_DOINFO, DI_ID, DI_SIMD, do_lastval(), do_parbegin(), do_simdbegin(), SEM::doif_depth, DT_INT, DT_ISINT, dtype, FALSE, get_collapse_temp(), get_doinfo(), i, ASTB::i1, DOINFO::index_var, DOINFO::init_expr, ASTB::k1, DOINFO::limit_expr, mk_assn_stmt(), mk_binop(), mk_id(), mkexpr1(), OP_ADD, OP_DIV, OP_MUL, OP_SUB, DOINFO::prev_dovar, S_EXPR, S_IDENT, SEM::scope_level, sem, SST_ASTG, SST_ASTP, SST_DTYPEP, SST_IDP, SST_SYMP, std, STD_BLKSYM, DOINFO::step_expr, TRUE, and void().
Referenced by semant3().
collapse_begin()
int collapse_begin (DOINFO * doinfo)
Begin processing loop collapse.
Example: the use of the collapse is for 3 loops.
!$omp ... collapse(3)
    do i1 = in1, l1, s1
      do i2 = in2, l2, s2
        do i3 = in3, l3, s3
        ... SS ...
The 3 loops are collapsed into a single loop with a new index variable and loop count. The new loop defines the iteration space for which the other omp clauses are applied; the new loop will appear as:
    n1 = (l1 - in1 + s1)/s1
    n2 = (l2 - in2 + s2)/s2
    n3 = (l3 - in3 + s3)/s3
    nn = n1*n2*n3  !! the product of the loop counts
!$omp ...
    do ii = 1, nn
        t  = ii-1
        q  = t / n3
        r  = t - q*n3
        i3 = in3 + r*s3
        t  = q
        q  = t / n2
        r  = t - q*n2
        i2 = in2 + r*s2
        t  = q
        q  = t / n1
        r  = t - q*n1
        i2 = in1 + r*s1
        ... SS ...
Basically, the original index variables are no longer iterated; their values are computed as a function of the new index variable and the corresponding loops' init, stride, and loop count.
Prefix of temps created for each loop:
    .Xa - lower bound
    .Xb - stride
    .Xc - loop count
Collapsed loop:
    .Xd - loop count
    .id - index variable
    .Xe - quotient  of id/loopcnt
    .Xf - remainder of id/loopcnt
    .Xg = temp var
Definition at line 6093 of file semutil.c.
References add_stmt(), ast, BLK_SYM, chktyp(), coll_st, DOINFO::collapse, SEM::collapse, SEM::collapse_depth, collapse_expr(), DOINFO::count, DI_DOINFO, do_begin(), SEM::doif_depth, DT_INT, DT_ISINT, dtype, error(), FALSE, gbl, get_collapse_temp(), DOINFO::index_var, DOINFO::init_expr, DOINFO::limit_expr, mk_assn_stmt(), mk_binop(), mk_id(), mkexpr1(), OP_ADD, OP_DIV, OP_SUB, S_EXPR, S_IDENT, SEM::scope_level, sem, SST_ASTG, SST_ASTP, SST_DTYPEP, SST_IDP, SST_SYMP, DOINFO::step_expr, SYMNAME, and void().
Referenced by do_distbegin(), and semant3().
construct_acl_from_ast()
ACL * construct_acl_from_ast (int ast, DTYPE dtype, int parent_acltype)
Definition at line 4540 of file semutil2.c.
References _can_fold(), AC_ACONST, AC_ARRAYREF, AC_AST, AC_CONV, AC_IDENT, AC_IEXPR, AC_LNOT, AC_MEMBR_SEL, AC_NEG, AC_SCONST, AC_TRIPLE, ADD_NUMELM, ASD_NDIM, ASD_SUBS, ast, _acl::ast, astb, ASTB::bnd, construct_acl_from_ast(), construct_intrinsic_acl(), DDTG, SEM::dinit_error, DTY, _acl::dtype, dtype, ASTB::dtype, SEM::equal_initializer, errsev(), eval_do_idx(), _acl::expr, FLANG_FALLTHROUGH, get_ac_op(), GET_ACL, getitem(), i, _acl::id, interr(), _acl::is_const, AEXPR::lop, mk_cval(), ndim, _acl::next, NOSYM, NULL, ASTB::one, AEXPR::op, prev, _acl::repeatc, AEXPR::rop, s, sem, SHD_LWB, SHD_UPB, sptr, _acl::subc, TRUE, and _acl::u1.
Referenced by construct_acl_for_sst(), construct_acl_from_ast(), construct_arg_list(), export_data_consts(), fixup_param_vars(), get_param_alias_const(), mk_reshape_intrin(), mk_size_intrin(), mk_transfer_intrin(), mk_transpose_intrin(), mk_ulbound_intrin(), ref_array(), ref_pd(), rewrite_acl(), and semant1().
copy_specifics()
void copy_specifics (int fromsptr, int tosptr)
Definition at line 1880 of file semgnr.c.
References add_overload(), assert, src, sym_in_sym_list(), SYMI_NEXT, and SYMI_SPTR.
Referenced by apply_use(), merge_generics(), and semant1().
create_parameterized_dt()
DTYPE create_parameterized_dt (DTYPE dtype, LOGICAL force)
Create a parameterized derived type based on dtype. If force is not set and dtype is already a PDT, return DT_NONE.
Definition at line 16298 of file semant.c.
References create_parameterized_dt(), DTY, get_parameterized_dt(), has_type_parameter(), insert_dup_sym(), is_pdt_dtype(), mem(), new_dtype(), and NOSYM.
Referenced by add_ptr_assign(), create_parameterized_dt(), defer_put_kind_type_param(), put_length_type_param(), semant1(), and semant3().
cuda_enabled()
LOGICAL cuda_enabled (const char * at_or_near)
If we are accepting cuda syntax return TRUE. Otherwise issue an error message and return FALSE.
Definition at line 8465 of file semutil2.c.
Referenced by semant1(), and semant3().
curr_scope()
SCOPESTACK * curr_scope (void)
Return the scope at the top of the scope stack.
Definition at line 49 of file scopestack.c.
References get_scope().
Referenced by add_only(), apply_use(), do_lastprivate(), do_nested_uses(), find_def_in_most_recent_scope(), import(), next_scope(), par_pop_scope(), par_push_scope(), pop_scope_level(), push_scope(), restore_scope_level(), save_scope_level(), scope_in_scope_stack(), and scopestack_init().
decl_private_sym()
int decl_private_sym (int sptr)
Declare a private symbol which may be based on the attributes of an existing symbol.
If the symbol doesn't exist (its stype is ST_UNKNOWN), it's assumed that the private variable will be a scalar variable.
Definition at line 1608 of file semsym.c.
References AD_DPTR, AD_LWBD, AD_NUMDIM, AD_UPBD, add_private_allocatable(), allocatable_member(), SEM::arrdim, BLK_SCOPE_SPTR, BLK_SYM, SEM::bounds, checking_scope, decl_private_sym(), DI_ID, DI_PAR, DI_PARDO, DI_PARSECTS, DI_TASK, DI_TASKLOOP, SEM::doif_depth, dt, DT_INT, DTY, dup_array_dtype(), SCOPESTACK::end_prologue, error(), flg, gbl, get_all_descriptors(), get_isz_cval(), get_static_descriptor(), getsymbol(), i, insert_sym(), SCOPESTACK::kind, lb, mk_arrdsc(), mk_id(), name, ndim, nullify_member_after(), STB::ovclass, refsym(), SCOPESTACK::rgn_scope, RUNTIMEG, S_CONST, S_EXPR, SEM::sc, SEM::scope_level, SCOPE_PAR, SEM::scope_stack, sem, set_descriptor_sc(), set_private_encl(), set_private_taskflag(), FLG::smp, sptr, SCOPESTACK::sptr, stb, STD_PREV, sym_get_scalar(), SYMNAME, and SEM::task.
Referenced by do_distbegin(), do_lastprivate(), do_private(), do_reduction(), mk_firstprivate(), and mklvalue().
declobject()
int declobject (int sptr, SYMTYPE stype)
Definition at line 1159 of file semsym.c.
References AD_ASSUMSZ, AD_DEFER, AD_DPTR, CNULL, declsym(), error(), flg, gbl, refsym(), sptr, SYMNAME, TRUE, FLG::xref, and xrefput().
declref()
int declref (int first, SYMTYPE stype, int def)
Look up symbol having a specific symbol type.
If a symbol is found in the same overloading class and has the same symbol type, it is returned to the caller. If a symbol is found in the same overloading class, the action of declref depends on the stype of the existing symbol and value of the argument def:
if symbol is an unfrozen intrinsic and def is 'd' (define), its intrinsic property is removed and a new symbol is declared,
if def is 'd', a multiple declaration error occurs, or
if def is not 'd', an 'illegal use' error occurs
If an error occurs or a matching symbol is not found, one is created and its symbol type is initialized.
Definition at line 491 of file semsym.c.
References CNULL, STB::curr_scope, def, error(), first, flg, gbl, insert_sym(), SEM::interface, IS_INTRINSIC, newsym(), NULL, STB::ovclass, sem, sptr, st, stb, sym_in_scope(), SYMNAME, FLG::xref, and xrefput().
Referenced by _read_token(), chk_fmtid(), dummy_program(), ff_get_label(), get_stmt(), read_symbol(), semant1(), and semant3().
declsym()
int declsym (int first, SYMTYPE stype, LOGICAL errflg)
Declare a new symbol.
An error can occur if the symbol is already in the symbol table.
If the symbol types match: treat as in error if errflg is true; otherwise return the symbol.
If they don't match: if symbol is an intrinsic attempt to remove symbol's intrinsic property; otherwise it is an error.
Definition at line 644 of file semsym.c.
References CNULL, STB::curr_scope, error(), export_append_sym(), first, first_hash(), STB::firstusym, flg, gbl, get_scope(), get_scope_level(), GSAMEG, GSAMEP, IN_MODULE, IN_MODULE_SPEC, insert_sym(), SEM::interface, internal_proc_has_ident(), IS_INTRINSIC, kind, level(), SEM::mod_sym, newsym(), next_scope_kind(), NOSYM, STB::ovclass, pop_sym(), push_sym(), replace_variable(), SCOPE_MODULE, SCOPE_NORMAL, SCOPE_OUTER, SCOPE_USE, sem, set_internref_flag(), sptr, st, stb, sym_in_scope(), SYMI_NEXT, SYMI_SPTR, SYMNAME, SEM::which_pass, FLG::xref, and xrefput().
Referenced by add_predefined_ieeearith_module(), add_predefined_iso_fortran_env_module(), add_predefined_isoc_module(), begin_module(), create_func_entry(), create_func_entry_result(), decl_procedure_sym(), declobject(), fixup_param_vars(), gen_finalized_result(), get_intrinsic_opr(), get_parameterized_dt(), get_unl_poly_sym(), resolveBind(), resolveImp(), semant1(), semant2(), and semant3().
declsym_newscope()
int declsym_newscope (int sptr, SYMTYPE stype, int dtype)
Declare a symbol in the most current scope; if one already exists return it.
Definition at line 1557 of file semsym.c.
References STB::curr_scope, FALSE, gbl, getocsym(), insert_sym(), STB::ovclass, sptr, and stb.
Referenced by ast_ioret(), get_fmt_array(), merge_generics(), and resolveImp().
defer_arg_chk()
void defer_arg_chk (SPTR formal, SPTR actual, SPTR subprog, cmp_interface_flags flags, int lineno, bool performChk)
Process information for deferred interface argument checking in in the compat_arg_lists() function below.
If the performChk argument is false, then we save the information (defer the check). If performChk argument is true, then we perform the argument checking. Note: If performChk is true, then the other arguments are ignored.
Parameters
formal is the symbol table pointer of the dummy/formal argument.
actual is the symbol table pointer of the actual argument.
flags are comparison flags that enable/disable certain checks
lineno is the source line number for the deferred check
performChk is false to defer checks and true to perform the checks.
Definition at line 1991 of file semfunc2.c.
References compatible_characteristics(), error(), flags, FREE, gbl, getsym(), lineno, list, NEW, next, NULL, prev, sem, strlen(), SYMNAME, and SEM::which_pass.
Referenced by compat_arg_lists(), and semant1().
defer_pt_decl()
int defer_pt_decl (int dtype, int flag)
Store dtypes of parameterized derived types in which a parameter was explicitly declared (as opposed to using just the default values).
Definition at line 15377 of file semant.c.
References FREE, SEM::interface, NEW, next, NULL, prev, sem, and SEM::which_pass.
Referenced by do_end_subprogram(), semant1(), and semant2().
dinit_struct_vals()
ACL * dinit_struct_vals (ACL * sconst, DTYPE dtype, SPTR component_sptr)
In DATA statement, do the stuff in dinit_struct_const in two steps.
Definition at line 7606 of file semutil2.c.
Referenced by semant1().
dmp_acl()
void dmp_acl (ACL * acl, int indent)
Definition at line 14288 of file semutil2.c.
References _dmp_acl(), indent, and NULL.
dmp_doif()
void dmp_doif (FILE * f)
Definition at line 14649 of file semutil2.c.
References _dmp_doif(), df, SEM::doif_depth, f, NULL, and sem.
do_begin()
int do_begin (DOINFO * doinfo)
Write out block DO AST from doinfo record. This function assumes that they init, limit, and step expressions have already been cast to the type of the do index variable.
Definition at line 5781 of file semutil.c.
References ast, DOCHK, DOINFO::index_var, DOINFO::init_expr, DOINFO::limit_expr, mk_id(), mk_stmt(), DOINFO::prev_dovar, and DOINFO::step_expr.
Referenced by _constructf90(), collapse_begin(), compute_size_ido(), do_distbegin(), do_parbegin(), do_simdbegin(), semant3(), and semantio().
do_distbegin()
int do_distbegin (DOINFO * doinfo, int do_label, int construct_name)
Definition at line 6411 of file semsmp.c.
References A_ORDEREDP, A_SCHED_TYPEP, add_stmt(), begin_parallel_clause(), BLK_UPLEVEL_SPTR, CL_COLLAPSE, CL_PRESENT, CL_VAL, DOINFO::collapse, SEM::collapse, collapse_begin(), SEM::collapse_depth, construct_name, dast(), decl_private_sym(), DI_ALLOCATED, DI_BPAR, DI_DISTCHUNK, DI_DO, DI_DO_AST, DI_DO_LABEL, DI_DOINFO, DI_IS_ORDERED, DI_LASTPRIVATE, DI_NAME, DI_PARDO, DI_REDUC, DI_REGIONVARS, DI_SCHED_TYPE, DI_SECT_VAR, direct_loop_enter(), DOINFO::distloop, do_begin(), do_label, do_lastval(), do_parbegin(), do_schedule(), DOCHK, SEM::doif_depth, DT_ISINT, emit_bpar(), ERR_Severe, error(), SEM::expect_dist_do, SEM::expect_do, FALSE, gbl, get_doinfo(), getccssym_sc(), has_team, DOINFO::index_var, DOINFO::init_expr, SEM::itemps, DOINFO::lastval_var, DOINFO::limit_expr, LP_DISTPARDO, LP_PARDO_OTHER, mk_assn_stmt(), mk_id(), mk_lastprivate_list(), mk_reduction_list(), mk_shared_list(), mk_stmt(), mp_create_bscope(), NEED_DOIF, NULL, par_push_scope(), past(), prev, DOINFO::prev_dovar, ref_object(), restore_clauses(), SEM::scope_level, sem, set_parref_flag(), sptr, DOINFO::step_expr, SYMNAME, SEM::teams, TRUE, and void().
Referenced by semant3().
do_end()
void do_end (DOINFO * doinfo)
Definition at line 6385 of file semutil.c.
References add_stmt(), add_stmt_after(), ast, check_doconcurrent(), SEM::close_pdo, DOINFO::collapse, SEM::collapse, SEM::construct_sptr, SCN::currlab, DCLCHK, DI_ACCDO, DI_ACCKERNELSDO, DI_ACCKERNELSLOOP, DI_ACCLOOP, DI_ACCPARALLELDO, DI_ACCPARALLELLOOP, DI_ACCREGDO, DI_ACCREGLOOP, DI_ACCSERIALLOOP, DI_BDISTRIBUTE, DI_BEGINP, DI_BPAR, DI_BTARGET, DI_CONC_COUNT, DI_CONC_MASK_STD, DI_CONC_SYMS, DI_CUFKERNEL, DI_CYCLE_LABEL, DI_DISTPARDO, DI_DISTRIBUTE, DI_DO, DI_DO_POPINDEX, DI_DOACROSS, DI_DOCONCURRENT, DI_DOINFO, DI_DOWHILE, DI_EXIT_LABEL, DI_ID, DI_PARDO, DI_PDO, DI_SIMD, DI_TARGPARDO, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TASKLOOP, DI_TEAMSDIST, DI_TEAMSDISTPARDO, DI_TOP_LABEL, SEM::doif_depth, emit_epar(), emit_etarget(), end_parallel_clause(), ENDLINEP, flg, gbl, getlab(), i, DOINFO::index_var, mk_label(), mk_stmt(), mp_create_escope(), par_pop_scope(), SEM::parallel, pop_sym(), DOINFO::prev_dovar, RFCNTI, scn, sem, FLG::smp, sptr, SPTR_NULL, stb, std, STD_BLKSYM, STD_LABEL, STD_LAST, STD_LINENO, SCN::stmtyp, SYMI_NEXT, SYMI_SPTR, SEM::target, SEM::task, TRUE, and void().
Referenced by _constructf90(), compute_size_ido(), semant1(), semant3(), and semantio().
do_equiv()
void do_equiv (void)
Definition at line 1438 of file semfin.c.
References a, add_socs(), addr, ALIGN, alignment(), assert, SOC::base, chk_evar(), PSECT::cmblk, CMEMLG, CMEMLP, CNULL, DBGBIT, equivalence(), EQV, SEM::eqvlist, error(), FALSE, fix_equiv_locals(), fix_equiv_statics(), flg, FREE, gbl, in_module, ISZ_T, PSECT::memlist, NEW, next, nml_equiv(), NOSYM, psect_base, psect_num, psect_size, FLG::recursive, SEM::savall, sem, size, SOC::size, size_of(), soc, sptr, SYMNAME, and vol_equiv().
Referenced by semfin().
do_index_addr()
int do_index_addr (int sptr)
Generate ILMs which computes the address of the index variable. Need to do it this way since the ILMs which were originally computed during the parse are not saved across the blocks.
Definition at line 5771 of file semutil.c.
References ref_object(), and sptr.
do_lastval()
void do_lastval (DOINFO * doinfo)
Definition at line 5807 of file semutil.c.
References add_stmt(), ast, astb, DT_INT, dtype, SEM::expect_simd_do, get_itemp(), ASTB::i0, DOINFO::index_var, DOINFO::init_expr, DOINFO::lastval_var, DOINFO::limit_expr, mk_assn_stmt(), mk_binop(), mk_id(), OP_ADD, OP_DIV, OP_MUL, OP_SUB, sem, sptr, DOINFO::step_expr, tempify_ast(), and void().
Referenced by collapse_add(), do_distbegin(), and semant3().
do_parbegin()
int do_parbegin (DOINFO * doinfo)
Definition at line 5897 of file semutil.c.
References A_ORDEREDP, A_SCHED_TYPEP, add_taskloopreg(), ast, DI_BTARGET, DI_CHUNK, DI_DISTCHUNK, DI_ID, DI_IS_ORDERED, DI_PARDO, DI_SCHED_TYPE, DI_TARGET, DI_TASKLOOP, do_begin(), DOCHK, SEM::doif_depth, DT_ISINT, error(), gbl, DOINFO::index_var, DOINFO::init_expr, DOINFO::lastval_var, DOINFO::limit_expr, mk_id(), mk_stmt(), DOINFO::prev_dovar, sem, DOINFO::step_expr, and SYMNAME.
Referenced by collapse_add(), do_distbegin(), and semant3().
dtype_has_defined_io()
int dtype_has_defined_io (int dtype)
Return a bit mask indicating which I/O routines are defined for a derived type.
Definition at line 1799 of file semgnr.c.
References check_defined_io2(), and DTY.
Referenced by nml_check_item(), nml_emit_desc(), nml_traverse(), and semantio().
dummy_program()
void dummy_program (void)
Check whether there is a subprogram statement; if not, create a dummy program symbol, and use that as the program.
Definition at line 13548 of file semutil2.c.
References SCN::currlab, declref(), FUNCLINEP, gbl, getsymbol(), NOSYM, push_scope_level(), scn, SEM::scope_level, SCOPE_NORMAL, SCOPE_SUBPROGRAM, sem, sptr, and tname.
Referenced by do_end_subprogram(), restore_internal_subprograms(), and semant1().
dup_struct_init()
void dup_struct_init (int new_sptr, int old_sptr)
Duplicate a derived type component's default initializations.
Parameters
new_sptr is the component that receives the initialization copy.
old_sptr has the default initialization that we want to duplicate.
We need to duplicate the initialization of a derived type component when we create new instances of the derived type with different kind/len type parameters.
Definition at line 5578 of file semutil2.c.
References BZERO, DTC_DEFAULT, DTC_DEFAULT_CNT, DTC_DEFAULT_HEAD, has_init_value(), and NEED.
Referenced by semant2().
emit_bcs_ecs()
int emit_bcs_ecs (int opc)
Definition at line 6304 of file semsmp.c.
References add_stmt(), assert, ast, DI_CRITICAL, DI_IN_NEST, SEM::doif_depth, mk_stmt(), sem, and void().
Referenced by semant1().
emit_epar()
int emit_epar (void)
Definition at line 6284 of file semsmp.c.
References add_stmt(), ast, mk_stmt(), SEM::parallel, sem, and void().
Referenced by do_end().
emit_etarget()
int emit_etarget (void)
Definition at line 6236 of file semsmp.c.
References add_stmt(), ast, mk_stmt(), sem, SEM::target, and void().
Referenced by do_end(), end_target(), and semsmp().
end_contained()
void end_contained (void)
called at end of processing contains subprograms
Definition at line 1472 of file main.c.
end_module()
void end_module (void)
Definition at line 1192 of file module.c.
References SEM::accl, astb, ASTB::df, dinit_ftell(), errfatal(), error(), export_all(), export_public_used_modules(), exportb, FALSE, fclose(), STB::firstusym, fix_module_common(), FREE, gbl, handle_mod_syms_dllexport(), EXPORTB::hpf_library, EXPORTB::hpf_local_library, EXPORTB::ieee_arith_library, impl, init_use_tree(), EXPORTB::iso_c_library, EXPORTB::iso_fortran_env_library, SEM::mod_cnt, SEM::mod_public_flag, MOD_SUFFIX, modu_name, modu_sym, NULL, outfile, SEM::scope_level, seen_contains, sem, sptr, stb, SYMNAME, tmpfile(), _accl::type, SEM::which_pass, and XBIT.
Referenced by alpha(), parser(), and semant1().
end_parallel_clause()
void end_parallel_clause (int doif)
Definition at line 7912 of file semsmp.c.
References add_stmt(), ast, deallocate_privates(), DI_DISTPARDO, DI_DISTRIBUTE, DI_DOACROSS, DI_ID, DI_PAR, DI_PARDO, DI_PARSECTS, DI_PARWORKS, DI_PDO, DI_REDUC, DI_SECTS, DI_SIMD, DI_SINGLE, DI_TARGET, DI_TARGPARDO, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TASK, DI_TASKLOOP, DI_TEAMS, DI_TEAMSDIST, DI_TEAMSDISTPARDO, end_lastprivate(), end_reduction(), FLANG_FALLTHROUGH, mk_stmt(), and void().
Referenced by do_end().
end_target()
void end_target ()
Definition at line 8758 of file semsmp.c.
References ast, DI_BTARGET, DI_TARGET, SEM::doif_depth, emit_etarget(), end_parallel_clause(), leave_dir(), mp_create_escope(), par_pop_scope(), sem, SEM::target, TRUE, and void().
Referenced by end_targteams(), and semant1().
end_teams()
void end_teams ()
Definition at line 8741 of file semsmp.c.
References add_stmt(), ast, DI_BTEAMS, DI_TEAMS, SEM::doif_depth, end_parallel_clause(), leave_dir(), mk_stmt(), mp_create_escope(), par_pop_scope(), sem, SEM::teams, TRUE, and void().
Referenced by end_targteams(), semant1(), and semsmp().
enforce_denorm()
void enforce_denorm (void)
Definition at line 1100 of file semsym.c.
References first, gbl, SEM::ieee_features, lookupsymbol(), NULL, sem, sptr, sym_in_scope(), SYMNAME, and TRUE.
Referenced by check_end_subprogram(), and semant1().
ensure_no_stale_tbp_queue_entries()
void ensure_no_stale_tbp_queue_entries (void)
enter_lexical_block()
int enter_lexical_block (int gen_debug)
Definition at line 14474 of file semutil2.c.
References add_stmt_after(), ast, BLK_SCOPE_SPTR, BLK_SYM, SEM::blksymnum, gbl, getccssym(), getlab(), mk_stmt(), RFCNTI, SEM::scope_level, sem, sptr, std, STD_LABEL, and STD_PREV.
Referenced by par_push_scope().
err307()
void err307 (const char * msg, int diname, int namedc)
Definition at line 6162 of file semant3.c.
References error(), gbl, msg(), STB::n_base, and stb.
Referenced by semant1(), and semant3().
err_protected()
void err_protected (int sptr, const char * context)
Definition at line 4697 of file semutil.c.
References ERRMSG_BUFFSIZE, error(), gbl, sptr, and SYMNAME.
Referenced by assign_pointer(), chk_arguments(), chk_pointer_target(), semant3(), and set_assn().
eval_init_expr()
ACL * eval_init_expr (ACL * e)
Definition at line 11835 of file semutil2.c.
References AC_ACONST, AC_SCONST, add_to_list(), clone_init_const(), convert_acl_dtype(), DDTG, _acl::dtype, e, eval_array_constructor(), eval_init_expr(), eval_init_expr_item(), _acl::id, _acl::next, NULL, root, _acl::subc, and TRUE.
Referenced by eval_const_array_triple_section(), eval_do(), eval_init_expr(), eval_init_expr_item(), eval_init_op(), get_param_alias_const(), ref_array(), ref_pd(), and semant1().
exit_lexical_block()
void exit_lexical_block (int gen_debug)
Definition at line 14505 of file semutil2.c.
References add_stmt_after(), ast, BLK_SYM, ENDLINEP, gbl, getlab(), mk_stmt(), RFCNTI, SEM::scope_level, sem, std, STD_LABEL, and STD_PREV.
Referenced by par_pop_scope().
find_outer_sym()
int find_outer_sym (int sym)
This function includes the actions performed by the production <var ref> ::= <ident> in the context of starting a parallel region or in the context of a parallel region. In either case, the symbol returned is the 'outer' symbol upon which the private symbol is based. In addition:
if the symbol is a function entry, refer to its local variable,
if the symbol is based, its associated pointer variable is created.
if the symbol is not yet a variable, it will be classified as if it was declared in the outer/nonparallel region.
Definition at line 8805 of file semsmp.c.
References STB::curr_scope, DCLCHK, gbl, insert_sym(), IS_INTRINSIC, newsym(), ref_based_object(), ref_entry(), refsym(), RU_FUNC, sem_set_storage_class(), setimplicit(), sptr, stb, and void().
Referenced by semant2(), and semsmp().
fix_class_args()
void fix_class_args (int func_sptr)
Add type descriptor arguments to a specified function if they have not already been added.
Parameters
sptr is the symbol table pointer of the specified function.
Definition at line 1065 of file semfin.c.
References add_class_arg_descr_arg(), aux, AUX::dpdsc_base, have_class_args_been_fixed_already(), and j.
Referenced by _stb_fixup_ifacearg(), do_end_subprogram(), gen_poly_element_arg(), get_type_descr_dummy(), llvm_check_retval_inargs(), semant1(), semfin(), and transform_call().
fix_mem_bounds()
int fix_mem_bounds (int parent, int mem)
Definition at line 12566 of file semutil2.c.
References AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_NUMDIM, AD_UPAST, AD_ZBASE, add_parent_to_bounds(), i, mem(), parent, and zbase.
Referenced by fix_type_param_members().
fix_mem_bounds2()
int fix_mem_bounds2 (int parent, int mem)
Definition at line 12603 of file semutil2.c.
References AD_DEFER, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_UPAST, AD_UPBD, AD_ZBASE, ADD_EXTNTAST, ADD_LWAST, ADD_NUMDIM, add_parent_to_bounds(), ADD_UPAST, ADD_ZBASE, dup_array_dtype(), get_aux_arrdsc(), i, mem(), new_dtype(), parent, remove_parent_from_ast(), and zbase.
Referenced by gen_kind_parm_assignments().
fix_type_param_members()
void fix_type_param_members (SPTR sptr, DTYPE dtype)
Definition at line 13145 of file semutil2.c.
References add_parent_to_bounds(), ast, DTY, fix_mem_bounds(), i, mem(), mk_id(), NOSYM, sptr, and TY_CHAR.
Referenced by semant1().
fixup_reqgs_ident()
void fixup_reqgs_ident (int sptr)
Referenced by lower_prepare_symbols(), ref_based_object_sc(), and semfin().
gen_alloc_dealloc()
int gen_alloc_dealloc (int stmtyp, int object, ITEM * spec)
Definition at line 12148 of file semutil2.c.
References A_TKNP, add_stmt(), add_stmt_after(), add_stmt_before(), SEM::alloc_std, assert, ast, DT_INT, DTYG, dtype, error(), firstalloc, flg, gbl, SEM::gcvlen, get_len_of_deferchar_ast(), get_temp(), is_deferlenchar_ast(), ITEM_END, itemp, mk_assn_stmt(), mk_id(), mk_stmt(), sem, spec, sptr, FLG::standard, stmt, sym_of_ast(), SYMNAME, tmp, TY_INT8, and XBIT.
Referenced by _constructf90(), convert_to_block_forall(), dealloc_tmp(), gen_allocate_array(), gen_dealloc_etmps(), gen_deallocate_arrays(), mk_ptr_subscr(), and semant3().
gen_alloc_mem_initialize_for_sym()
void gen_alloc_mem_initialize_for_sym (int sptr, int std)
Definition at line 13235 of file semutil2.c.
References gen_alloc_mem_initialize_for_sym2(), sptr, and std.
Referenced by bblock().
gen_allocate_array()
void gen_allocate_array (int arr)
Given an allocatable array and an explicit shape list which has been deposited in the semant 'bounds' structure, generate assignments to the arrays bounds temporaries, and allocate the array. Save the id ast of the array for an ensuing deallocate of the array.
Definition at line 1046 of file semutil2.c.
References acs, add_p_dealloc_item(), _ACS::arrtype, gen_alloc_dealloc(), gen_defer_shape(), get_all_descriptors(), get_static_descriptor(), and is_deferlenchar_dtype().
Referenced by gen_array_result(), init_sptr_w_acl(), and mkexpr_assign_temp().
gen_automatic_reallocation()
void gen_automatic_reallocation (int lhs, int rhs, int std)
Generate (re)allocation code for deferred length character objects and traditional character objects that are allocatable scalars.
This is typically used in generating (re)allocation code in an assignment to an allocatable/deferred length character object.
Reallocation code is generated for deferred length character objects.
For traditional character allocatable scalars, we allocate the object if it has not already been allocated; we do not generate reallocation code since the amount of space allocated is fixed with traditional character allocatable objects.
We update the character length descriptor information for both deferred length and traditional character objects. This is needed for proper I/O such as namelist processing.
Parameters
lhs is the ast of the object getting (re)allocated.
rhs is the ast of the object that supplies the character length.
std is the statement descriptor where we insert the (re)allocation and/or length assignment code.
Definition at line 13439 of file semutil2.c.
References A_OPTYPEP, A_TKNP, add_stmt_after(), add_stmt_before(), argt, ARGT_ARG, ast, check_and_add_auto_dealloc_from_ast(), DDTG, DT_INT, STB::dt_log, DT_LOG, get_len_of_deferchar_ast(), getsymbol(), init_intrin_type_desc(), lhs, memsym_of_ast(), mk_argt(), mk_assn_stmt(), mk_binop(), mk_func_node(), mk_id(), mk_stmt(), NULL, OP_NE, proc_arginfo(), procsym_of_ast(), size_ast_of(), stb, std, string_expr_length(), and STB::user.
Referenced by rewrite_allocatable_assignment().
gen_conditional_alloc()
int gen_conditional_alloc (int cond, int alloc_item, int after)
Definition at line 13296 of file semutil2.c.
References A_OPTYPEP, A_TKNP, add_stmt_after(), after, argt, ARGT_ARG, ast, STB::dt_log, getsymbol(), mk_argt(), mk_func_node(), mk_id(), mk_stmt(), stb, and STB::user.
Referenced by add_private_allocatable().
gen_conditional_dealloc()
void gen_conditional_dealloc (int do_cond, int dealloc_item, int after)
Definition at line 13290 of file semutil2.c.
References __gen_conditional_dealloc(), and after.
Referenced by deallocate_privates().
gen_conditional_dealloc_for_sym()
void gen_conditional_dealloc_for_sym (int sptr, int std)
Definition at line 13334 of file semutil2.c.
References __gen_conditional_dealloc(), A_TKNP, add_stmt_after(), ast, flg, gbl, mk_id(), mk_stmt(), scope, FLG::smp, sptr, std, and void().
Referenced by bblock(), and fix_args().
gen_contig_check()
void gen_contig_check (int dest, int src, SPTR sdsc, int srcLine, bool cs, int std)
Generate a contiguous pointer check on a pointer assignment when applicable.
Parameters
dest is the destination pointer.
src is the pointer target.
sdsc is an optional descriptor argument to pass to the check function (0 to use src's descriptor).
srcLine is the line number associated with the check.
cs is true when we are generating the check at a call-site.
std is the optional statement descriptor for adding the check (0 if not applicable).
Definition at line 4372 of file semutil.c.
References add_stmt(), add_stmt_after(), add_stmt_before(), ARGT_ARG, ast_is_sym(), check_member(), cs, dest, DT_INT, func, gbl, get_member_descriptor(), get_static_descriptor(), getstring(), inline_contig_check(), interr(), lineno, memsym_of_ast(), mk_argt(), mk_cval1(), mk_func_node(), mk_id(), mk_stmt(), mk_unop(), mkRteRtnNm(), NOSYM, OP_VAL, RTE_contigchk, RTE_contigerror, src, std, strlen(), sym_mkfunc_nodesc(), SYMNAME, and XBIT.
Referenced by add_ptr_assign(), newargs_for_entry(), and transform_call().
gen_dealloc_etmps()
void gen_dealloc_etmps (void)
Definition at line 12251 of file semutil2.c.
References SEM::etmp_list, FALSE, gen_alloc_dealloc(), mk_id(), xyyz::next, sem, sptr, xyyz::sptr, xyyz::t, and SEM::use_etmps.
Referenced by check_etmp(), and semant3().
gen_dealloc_for_sym()
int gen_dealloc_for_sym (int sptr, int std)
Definition at line 13361 of file semutil2.c.
References A_TKNP, add_stmt_after(), ast, mk_id(), mk_stmt(), sptr, ss, and std.
Referenced by init_derived_type().
gen_deallocate_arrays()
void gen_deallocate_arrays (void)
Generate deallocates for the temporary arrays in the sem.p_delloc list.
Definition at line 752 of file semutil2.c.
References DI_FORALL, DI_ID, SEM::doif_depth, gen_alloc_dealloc(), NULL, p, SEM::p_dealloc, sem, t, and void().
Referenced by rewrite_allocatable_assignment(), semant1(), and semant3().
gen_defer_shape()
int gen_defer_shape (int sptr, int astparent, int savedelete)
Process an explicit shape list has been parsed and all bounds information has been deposited into a few semant global data structures.
Parameters
sptr sptr of the deferred array
astparent ast of the parent pointer
savedelete ?
From this collection of information:
Generate assignments which define the lower and upper bounds for the deferred array; where the bounds are stored (asts) are located in the array descriptor.
Create a subscript AST which is used to represent the explicit shape; the bounds for the explicit shape use the bounds asts which are the destinations of the generated assignments; note that each subscript is represented as a triple.
Definition at line 613 of file semutil2.c.
References ADD_DEFER, ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_NUMDIM, add_stmt(), ADD_UPAST, ADD_UPBD, SEM::arrdim, ast, astb, ASTB::bnd, SEM::bounds, check_member(), dt, ASTB::dtype, extent(), getitem(), i, itemp, lb, MAXDIMS, mk_assn_stmt(), mk_extent_expr(), mk_id(), mk_subscr(), mk_triple(), ASTB::one, SEM::p_dealloc_delete, sem, sptr, src, std, sym_of_ast(), and ub.
Referenced by gen_allocate_array(), and semant3().
gen_derived_type_alloc_init()
void gen_derived_type_alloc_init (ITEM * itemp)
Definition at line 12049 of file semutil2.c.
References add_stmt(), ast, _acl::dtype, get_dtype_init_template(), get_getitem_p(), get_struct_initialization_tree(), has_type_parameter(), itemp, mk_assn_stmt(), mk_id(), and NOSYM.
Referenced by semant3().
gen_finalization_for_sym()
int gen_finalization_for_sym (int sptr, int std, int memAst)
Definition at line 12369 of file semutil2.c.
References add_stmt_after(), argt, ARGT_ARG, ast, check_member(), DTY, dtype, FALSE, gbl, gen_set_type(), get_static_descriptor(), get_static_type_descriptor(), get_type_descr_arg(), has_finalized_component(), init_sdsc(), mk_argt(), mk_func_node(), mk_id(), mk_stmt(), mkRteRtnNm(), RTE_finalize, SEM::savall, sem, sptr, std, and sym_mkfunc_nodesc().
Referenced by bblock(), gen_finalized_result(), rewrite_allocatable_assignment(), and semant3().
gen_init_unl_poly_desc()
void gen_init_unl_poly_desc (int dest_sdsc_ast, int src_sdsc_ast, int std)
Generate a call to init_unl_poly_desc which initializes a descriptor for an unlimited polymorphic object with another descriptor.
Parameters
dest_sdsc_ast is the AST of the destination's descriptor.
src_sdsc_ast is the AST of the source descriptor.
std is the statement descriptor to insert the call, or 0 to use the default statement descriptor.
Definition at line 6478 of file semant3.c.
References add_stmt(), add_stmt_after(), argt, ARGT_ARG, ast, DT_INT, mk_argt(), mk_cval1(), mk_func_node(), mk_id(), mk_unop(), mkRteRtnNm(), OP_VAL, RTE_init_unl_poly_desc, std, sym_mkfunc_nodesc(), and val.
Referenced by construct_association(), rewrite_allocatable_assignment(), and semant3().
gen_poly_element_arg()
int gen_poly_element_arg (int ast, SPTR sptr, int std)
Generates a call to a poly_element_addr runtime routine that computes the address of a polymorphic array element.
This is required when our passed object argument of a type bound procedure call is an array element.
Parameters
ast is the ast of the passed object argument (an A_SUBSCR ast).
sptr is the symbol table pointer of the passed object argument.
std is the current statement descriptor.
Returns
an ast that represents the pointer that holds the address of the polymorphic array element.
Definition at line 4033 of file semutil.c.
References add_ptr_assign(), add_stmt_after(), add_stmt_before(), args, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, check_member(), DT_INT, SEM::dtemps, DTY, dtype, dtype_to_arg(), fix_class_args(), func, gbl, get_member_descriptor(), get_static_descriptor(), get_type_descr_arg(), getccsym_sc(), i, mk_argt(), mk_cval1(), mk_func_node(), mk_id(), mk_set_type_call(), mk_unop(), mkRteRtnNm(), needs_descriptor(), NOSYM, OP_VAL, RTE_poly_element_addr, RTE_poly_element_addr1, RTE_poly_element_addr2, RTE_poly_element_addr3, sem, set_descriptor_rank(), sptr, ss, std, sym_mkfunc_nodesc(), and tmp.
Referenced by ref_array(), transform_call(), and transform_section_arg().
gen_set_type()
int gen_set_type (int dest_ast, int src_ast, int std, LOGICAL insert_before, LOGICAL intrin_type)
Generates calls to RTE_set_type() or RTE_set_intrin_type() which set the type descriptor field of an object's descriptor.
Parameters
dest_ast is the descriptor expression that's getting its type descriptor set. Note: dest_ast may be a descriptor expression or an expression that has a descriptor.
src_ast is the expression that has the type descriptor that we are copying to dest_ast. Note: src_ast may be a descriptor expression or an expession that has a descriptor.
std is the std where we will insert the call.
insert_before is true when you want to insert the call before std, otherwise we insert it after std.
intrin_type is true when you want to use the RTE_set_intrin_type() routine instead of the RTE_set_type() routine.
Returns
the new std after inserting the call.
Definition at line 14753 of file semutil2.c.
References add_stmt_after(), add_stmt_before(), check_member(), get_member_descriptor(), is_tbp(), memsym_of_ast(), mk_id(), mk_set_type_call(), sptr, and std.
Referenced by check_alloc_ptr_type(), check_pointer_type(), gen_finalization_for_sym(), genPolyAsn(), ref_pd(), and transform_call().
gen_type_initialize_for_sym()
void gen_type_initialize_for_sym (SPTR sptr, int std, int flag, DTYPE dtype2)
Definition at line 13163 of file semutil2.c.
References add_stmt(), array_element_dtype(), ast, DTY, gen_kind_parm_assignments(), is_array_dtype(), mk_stmt(), sptr, and std.
Referenced by bblock(), and semant3().
gen_varref_var()
VAR * gen_varref_var (int ast, DTYPE dtype)
Definition at line 11978 of file semutil2.c.
References ast, dinit_varref(), S_IDENT, SST_ASTP, SST_DTYPEP, SST_IDP, and SST_SHAPEP.
generic_tbp_has_pass_and_nopass()
int generic_tbp_has_pass_and_nopass (int dtype, int sptr)
Definition at line 2963 of file semfunc.c.
References DTY, generic_tbp_has_pass_and_nopass(), mem(), NOSYM, sptr, and SYMNAME.
Referenced by check_defined_io2(), find_best_generic(), generic_tbp_has_pass_and_nopass(), get_generic_tbp_pass_or_nopass(), semant2(), and semant3().
get_acl()
ACL * get_acl (int area)
Definition at line 5136 of file semutil2.c.
References a, area, BZERO, and getitem().
get_adjlr_arr_temp()
SPTR get_adjlr_arr_temp (DTYPE dtype)
Get a compiler-created allocatable array temp to represent the result of run-time function computing the adjustl/adjustr intrinsic.
The result of the run-time is the length (which we don't actually use), but it's needed to effect array/forall processing in the compiler. Eventually, in outconv.c, the temp is discarded, as well as the return value of the runtime routine.
Definition at line 8030 of file semutil2.c.
Referenced by init_sptr_w_acl(), and rewrite_func_ast().
get_arr_const()
SPTR get_arr_const (DTYPE dtype)
Get a compiler array temporary of type dtype which is used to represent array constants.
Definition at line 864 of file semutil2.c.
References getcctmp(), and sptr.
Referenced by init_sptr_w_acl().
get_arr_temp()
SPTR get_arr_temp (DTYPE dtype, LOGICAL nodesc, LOGICAL alloc_deferred, LOGICAL constructor)
Get a compiler array temporary of type dtype.
Definition at line 7932 of file semutil2.c.
Referenced by func_call2(), gen_derived_arr_init(), init_sptr_w_acl(), inline_small_matmul(), mkexpr_assign_temp(), precompute_arg_intrin(), ptrfunc_call(), ref_intrin(), ref_pd(), and rewrite_allocatable_assignment().
get_ch_temp()
SPTR get_ch_temp (DTYPE dtype)
Get a character compiler temporary of type dtype.
Definition at line 8055 of file semutil2.c.
Referenced by gen_char_result(), ref_pd(), and rewrite_allocatable_assignment().
get_construct_name()
int get_construct_name (void)
Definition at line 5688 of file semant3.c.
References construct_name.
Referenced by semant1().
get_doinfo()
DOINFO * get_doinfo (int area)
Definition at line 6635 of file semutil.c.
References area, DOINFO::collapse, DOINFO::distloop, and getitem().
Referenced by acl_rewrite_asts(), do_distbegin(), get_dobegin(), rewrite_acl(), save_acl(), semant2(), semant3(), and semantio().
get_dtype_init_template()
SPTR get_dtype_init_template (DTYPE dtype)
Process an AC_TYPEINIT.
Look for an initialization template for this type. If one already exists then return it. Otherwise build one (and return it).
Definition at line 11998 of file semutil2.c.
References array_element_dtype(), assert, DDTG, dinit(), DTY, _acl::dtype, dtype, eq_dtype(), ERR_Fatal, GET_ACL, get_getitem_p(), get_struct_initialization_tree(), get_struct_tag_sptr(), getccssym_sc(), is_array_dtype(), is_unresolved_parameterized_dtype(), NOSYM, NULL, prefix, sptr, _acl::sptr, and TRUE.
Referenced by component_init_allocd_auto(), gen_derived_type_alloc_init(), get_static_type_descriptor(), init_derived_type(), and sym_get_sdescr().
get_entity_access()
int get_entity_access ()
provide the current entity's access to other source files.
Definition at line 16488 of file semant.c.
References entity_attr.
Referenced by link_members().
get_first_mangled()
int get_first_mangled (int)
get_generic_member()
int get_generic_member (int dtype, int sptr)
Definition at line 2857 of file semfunc.c.
References DTY, get_generic_member(), mem(), NOSYM, sptr, and SYMNAME.
Referenced by check_defined_io2(), chk_arguments(), find_best_generic(), find_operator(), and get_generic_member().
get_generic_member2()
int get_generic_member2 (int dtype, int sptr, int argcnt, int * argno)
Definition at line 2888 of file semfunc.c.
References aux, AUX::dpdsc_base, DTY, eq_dtype2(), func, get_generic_member2(), get_implementation(), i, mem(), NOSYM, NULL, pass_arg, proc_arginfo(), sptr, and SYMNAME.
Referenced by get_generic_member2(), semant2(), and semant3().
get_generic_tbp_pass_or_nopass()
int get_generic_tbp_pass_or_nopass (int dtype, int sptr, int flag)
Definition at line 2998 of file semfunc.c.
References DTY, generic_tbp_has_pass_and_nopass(), mem(), NOSYM, sptr, and SYMNAME.
Referenced by semant2(), and semant3().
get_implementation()
int get_implementation (int dtype, int orig_sptr, int flag, int * memout)
For type bound procedures, find the implementation for the type bound procedure binding name in dtype.
If flag is set, then we check to see if we're accessing a PRIVATE type bound procedure. If so, we issue an error message.
Parameters
dtype is the derived type record that we are searching.
orig_sptr is the symbol table pointer of the binding name of the type bound procedure to look up.
flag is set to check for accessing a PRIVATE type bound procedure.
memout if set, the function will store the type bound procedure symbol table pointer in this pointer argument.
Returns
a symbol table pointer to the type bound procedure implementation; otherwise 0 (if not found).
Definition at line 3106 of file semfunc.c.
References DTY, error(), find_by_name_stype_arg(), gbl, get_implementation(), get_tbp(), mem(), NOSYM, queue_tbp(), scope, sem, sptr, strlen(), suffix, SYMNAME, TBP_FORCE_RESOLVE, and SEM::which_pass.
Referenced by check_defined_io2(), completeTbp(), find_best_generic(), find_operator(), func_call2(), get_defined_io_call(), get_generic_member2(), get_implementation(), get_tbp_argno(), is_intrinsic_opr(), lower_function(), nml_emit_desc(), proc_arginfo(), resolveGeneric(), resolveImp(), semant2(), semant3(), semCheckTbp(), and subr_call2().
get_intrinsic_opr()
int get_intrinsic_opr (int val, int tkn_alias)
Definition at line 1076 of file semgnr.c.
References bind_intrinsic_opr(), declsym(), FALSE, get_intrinsic_oprsym(), and val.
Referenced by semant1().
get_intrinsic_oprsym()
int get_intrinsic_oprsym (int val, int tkn_alias)
Definition at line 1065 of file semgnr.c.
References getsymbol(), name, optab, tkn_alias_sym(), and val.
Referenced by get_intrinsic_opr(), and semant1().
get_itemp()
SPTR get_itemp (DTYPE dtype)
Definition at line 7886 of file semutil2.c.
Referenced by do_dist_schedule(), do_lastval(), do_schedule(), save_clauses(), and semsmp().
get_kind_parm_by_name()
int get_kind_parm_by_name (char * np, int dtype)
search a derived type for a kind type parameter with a specified name.
Parameters
np is the name we're search for
dtype is the derived type record that we are searching
Returns
integer > 0 for the parameter number, else 0 if not found.
Definition at line 14955 of file semant.c.
References DTY, get_kind_parm_by_name(), mem(), NOSYM, and SYMNAME.
Referenced by defer_put_kind_type_param(), get_keyword_components(), get_kind_parm_by_name(), and semant2().
get_len_parm_by_number()
int get_len_parm_by_number (int num, int dtype, int flag)
Definition at line 15851 of file semant.c.
References DT_INT, DTY, get_len_parm_by_number(), getcon(), i, mem(), mk_cnst(), mk_id(), NOSYM, num, and val.
Referenced by get_len_parm_by_number(), put_kind_type_param(), and ref_pd().
get_len_set_parm_by_name()
int get_len_set_parm_by_name (char * np, int dtype, int * val)
Definition at line 15311 of file semant.c.
References DTY, get_len_set_parm_by_name(), mem(), NOSYM, SYMNAME, and val.
Referenced by get_keyword_components(), and get_len_set_parm_by_name().
get_nml_array()
int get_nml_array (int nml)
Create the array (ST_PLIST) representing the namelist.
The name is derived from the namelist group name.
Definition at line 4990 of file semantio.c.
References DT_PTR, get_next_sym(), nml, sptr, and SYMNAME.
Referenced by semant1(), and semantio().
get_param_alias_var()
SPTR get_param_alias_var (SPTR param_sptr, DTYPE dtype)
Definition at line 1543 of file semutil2.c.
References STB::curr_scope, getsymbol(), mangle_name(), PARAMVALG, PARAMVALP, stb, sym_is_refd(), and SYMNAME.
Referenced by convert_ctmp_array_to_param(), and fixup_param_vars().
get_parameterized_dt()
DTYPE get_parameterized_dt (DTYPE dtype)
Duplicate dtype by creating a new derived type with a $pt suffix. For use with processing parameterized derived type.
Definition at line 16335 of file semant.c.
References assert, chkstruct(), declsym(), DTY, dup_acl(), dup_array_dtype(), ERR_Fatal, get_getitem_p(), get_member_descriptor(), get_next_sym(), get_type(), insert_dup_sym(), match_memname(), mem(), new_dtype(), NOSYM, put_getitem_p(), sptr, SYMNAME, and TRUE.
Referenced by create_parameterized_dt(), and semant2().
get_parm_by_name()
int get_parm_by_name (char * np, int dtype)
search a derived type for a kind or length type parameter with a specified name.
Parameters
np is the name we're search for
dtype is the derived type record that we are searching
Returns
integer > 0 for the parameter number, else 0 if not found.
Definition at line 15013 of file semant.c.
References DTY, get_parm_by_name(), mem(), NOSYM, and SYMNAME.
Referenced by get_parm_by_name(), and semant3().
get_parm_by_number()
int get_parm_by_number (int offset, int dtype)
search derived type for a type parameter in the same position as specified by offset.
Parameters
offset is the desired parameter position
dtype is the derived type record to search in
Returns
symbol table pointer of the parameter component in the derived type; else 0 if not found.
Definition at line 14985 of file semant.c.
References DTY, get_parm_by_number(), mem(), NOSYM, and offset.
Referenced by get_parm_by_number(), and semant3().
get_scope()
SCOPESTACK * get_scope (int level)
Get an entry in the scope stack.
Parameters
level Level of the entry to return: 0 means top and negative is relative to the top.
Definition at line 59 of file scopestack.c.
References dumpscope(), ERR_Fatal, gbl, interr(), level(), SEM::scope_level, SEM::scope_size, SEM::scope_stack, and sem.
Referenced by curr_scope(), declsym(), export_public_used_modules(), find_in_host(), par_push_scope(), pop_scope_level(), sym_visible_in_scope(), test_scope(), and update_list_exceptions().
get_scope_level()
int get_scope_level (SCOPESTACK * scope)
Return the level of this entry in the scope stack or -1 if scope is null.
Definition at line 77 of file scopestack.c.
References assert, ERR_Fatal, level(), scope, SEM::scope_level, SEM::scope_stack, and sem.
Referenced by add_only(), apply_use(), declsym(), find_def_in_most_recent_scope(), find_in_host(), have_use_scope(), import_use_stmts(), next_scope(), and sym_in_scope().
get_seen_contains()
LOGICAL get_seen_contains (void)
Definition at line 1114 of file module.c.
References seen_contains.
Referenced by dinit_data(), do_iface_module(), and semant1().
get_shape_arr_temp()
int get_shape_arr_temp (int arg)
Get a compiler array temporary of from a shape of an ast.
Definition at line 8042 of file semutil2.c.
Referenced by precompute_arg_intrin(), and ref_intrin().
get_specific_member()
int get_specific_member (int dtype, int sptr)
Definition at line 3033 of file semfunc.c.
References DTY, get_specific_member(), mem(), NOSYM, sptr, and SYMNAME.
Referenced by check_defined_io2(), find_best_generic(), find_operator(), func_call2(), get_specific_member(), lower_function(), lower_symbol(), proc_arginfo(), resolveGeneric(), semant2(), semant3(), and semCheckTbp().
get_static_type_descriptor()
int get_static_type_descriptor (int sptr)
Return the "static type descriptor" for object sptr. The static type descriptor holds the "declared type" of an object.
Definition at line 123 of file semfunc.c.
References dt, DTY, FALSE, FLANG_FALLTHROUGH, get_dtype_init_template(), get_static_descriptor(), get_struct_initialization_tree(), get_struct_members(), get_struct_tag_sptr(), NOSYM, set_descriptor_class(), sptr, sym_is_refd(), and TRUE.
Referenced by _constructf90(), check_alloc_ptr_type(), check_pointer_type(), gen_call_class_obj_size(), gen_finalization_for_sym(), genPolyAsn(), get_sdsc_ast(), get_type_descr_arg(), get_type_descr_arg2(), get_unl_poly_sym(), init_derived_type(), lower_function(), lower_stmt(), ref_pd(), resolveTbps(), semant1(), semant3(), set_type_in_descriptor(), and transform_call().
get_struct_leafcnt()
int get_struct_leafcnt (int)
get_tbp_argno()
int get_tbp_argno (int sptr, int dty2)
Definition at line 2801 of file semfunc.c.
References assert, error(), find_dummy_position(), first, gbl, get_implementation(), get_next_hash_link(), getitem(), len, mem(), name, NOSYM, proc_arginfo(), sptr, strlen(), SYMNAME, and test_scope().
Referenced by func_call2(), handle_arguments(), is_intrinsic_opr(), lower_function(), semant2(), semant3(), and subr_call2().
get_temp()
SPTR get_temp (DTYPE dtype)
Get a compiler temporary of any scalar dtype.
Definition at line 7845 of file semutil2.c.
Referenced by _constructf90(), asn_sfuse(), assign_array_w_forall(), component_init_allocd_auto(), compute_size_ido(), conv_forall(), gen_alloc_dealloc(), gen_dos_over_shape(), get_dobegin(), get_subscripting_tmp(), handle_dependence_ido(), mk_fake_iostat(), precompute_arg_intrin(), ref_intrin(), ref_pd(), ref_stfunc(), rewrite_func_ast(), semant2(), semantio(), tempify(), tempify_ast(), and transform_c_f_pointer().
get_temp_dtype()
DTYPE get_temp_dtype (DTYPE dtype, int expr)
Definition at line 7870 of file semutil2.c.
Referenced by precompute_arg_intrin(), and ref_intrin().
get_type_descr_arg()
int get_type_descr_arg (int func_sptr, int arg)
Return the type descriptor associated with arg (and func_sptr when arg is a dummy argument of routine func_sptr).
Definition at line 223 of file semfunc.c.
References arg, assert, DTY, gbl, get_static_descriptor(), get_static_type_descriptor(), get_type_descr_dummy(), needs_descriptor(), NOSYM, and sptr.
Referenced by check_pointer_type(), gen_call_class_obj_size(), gen_finalization_for_sym(), gen_poly_element_arg(), get_descr_arg(), get_sdsc_ast(), handle_arguments(), lower_data_stmts(), lower_function(), lower_stmt(), ref_pd(), semant3(), set_type_in_descriptor(), and transform_call().
get_type_descr_arg2()
int get_type_descr_arg2 (int func_sptr, int arg)
Same as get_type_descr_arg(), but do not perform error check.
Definition at line 262 of file semfunc.c.
References arg, get_descriptor_sc(), get_static_descriptor(), get_static_type_descriptor(), get_type_descr_dummy(), needs_descriptor(), set_descriptor_sc(), and sptr.
Referenced by semant3(), and transform_call().
get_unl_poly_sym()
int get_unl_poly_sym (int mem_dtype)
Definition at line 16118 of file semant.c.
References declsym(), SEM::dtemps, DTY, get_static_type_descriptor(), get_type(), getccsym_sc(), getsymf(), SEM::interface, mem(), NOSYM, sem, sptr, and TRUE.
Referenced by semant1(), and semant3().
getbase()
int getbase (int ast)
Dereference an ast to determine the base, i.e. its symbol pointer.
Definition at line 5740 of file semutil.c.
References ast, and getbase().
Referenced by chk_pointer_intent(), getbase(), mklvalue(), and mkvarref().
getCref()
int getCref (void)
provide cref variable state to other source files.
Definition at line 16502 of file semant.c.
References cref.
Referenced by fixupImp(), and resolveImp().
getMscall()
int getMscall (void)
provide mscall variable state to other source files.
Definition at line 16495 of file semant.c.
References mscall.
Referenced by fixupImp(), and resolveImp().
getocsym()
int getocsym (int first, OVCLASS oclass, LOGICAL alias)
Look up symbol matching overloading class of given symbol type.
Parameters
first the symbol to match by name
oclass the overloading class to match
alias if true and the symbol is an ST_ALIAS, return the dereferenced symbol
Returns
The symbol whose overloading class matches the overloading class of the symbol type given. If no symbol is found in the given overloading class one is created.
Definition at line 1127 of file semsym.c.
References first, flg, insert_sym(), SEM::interface, NULL, STB::ovclass, sem, sptr, st, stb, sym_in_scope(), FLG::xref, and xrefput().
Referenced by chk_intrinsic(), declsym_newscope(), import_symbol(), newsym(), and semant1().
handle_accdecl()
void handle_accdecl (int keyword)
has_cuda_data()
LOGICAL has_cuda_data (void)
Definition at line 1912 of file module.c.
References FALSE, FIRST_DEV_COMMON, gbl, LAST_DEV_COMMON, mod_cmn, NOSYM, and TRUE.
has_init_value()
int has_init_value (SPTR sptr)
Definition at line 5544 of file semutil2.c.
References DTC_DEFAULT, DTC_DEFAULT_CNT, and sptr.
Referenced by check_derived_type_in_comm(), and dup_struct_init().
has_length_type_parameter_use()
int has_length_type_parameter_use (int dtype)
Definition at line 16254 of file semant.c.
References DTY, has_length_type_parameter_use(), mem(), and NOSYM.
Referenced by has_length_type_parameter_use(), and rewrite_calls().
has_poly_mbr()
int has_poly_mbr (int sptr, int flag)
Return TRUE if derived type has a polymorphic member.
If flag is set, then it also returns TRUE if it has a pointer or allocatable derived type member with a type descriptor embedded in the type itself.
Definition at line 6087 of file semant3.c.
References DTY, has_poly_mbr(), is_tbp_or_final(), mem(), NOSYM, and sptr.
Referenced by has_poly_mbr(), rewrite_calls(), and semant3().
has_type_parameter()
int has_type_parameter (int dtype)
checks to see if derived type record, dtype, has any type parameters (kind or length type parameters).
Parameters
dtype is the derived type record we're searching
Returns
integer > 0 if dtype has type parameters; else 0.
Definition at line 16227 of file semant.c.
References has_type_parameter2().
Referenced by add_ptr_assign(), add_type_param_initialize(), construct_acl_for_sst(), create_parameterized_dt(), gen_derived_type_alloc_init(), gen_kind_parm_assignments(), put_default_kind_type_param(), put_length_type_param(), semant1(), semant2(), and semant3().
have_module_state()
int have_module_state (void)
Definition at line 14116 of file semutil2.c.
References modstate_file, and NULL.
Referenced by semant1().
have_use_scope()
int have_use_scope (int sptr)
Return the USE module scope for the module associated with this symbol, or -1 if none.
Definition at line 166 of file scopestack.c.
References get_scope_level(), next_scope(), NULL, scope, SEM::scope_stack, SCOPE_USE, sem, and sptr.
Referenced by do_nested_uses().
iface_intrinsic()
int iface_intrinsic (int sptr)
Definition at line 2708 of file semfunc2.c.
References arg, assert, aux, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, DT_CMPLX, DT_DBLE, DT_INT, DT_REAL, getsym(), getsymf(), iface_arg(), intast_sym, INTENT_IN, INTENTP, KWDARGSTR, NEED, sptr, ss, SYMNAME, and TRUE.
Referenced by _do_iface().
ignore_tkr()
LOGICAL ignore_tkr (int arg, int tkr)
Definition at line 2618 of file semfunc2.c.
References arg, FALSE, IGNORE_C, ignore_tkr_all(), and TRUE.
Referenced by chk_arguments(), copy_arg_to_seq_tmp(), handle_seq_section(), and tkr_match().
ignore_tkr_all()
LOGICAL ignore_tkr_all (int arg)
Definition at line 2638 of file semfunc2.c.
References arg, FALSE, IGNORE_TKR_ALL, IGNORE_TKR_ALL0, and TRUE.
Referenced by ignore_tkr(), and misc_checks().
in_device_code()
LOGICAL in_device_code (int sptr)
Definition at line 8472 of file semutil2.c.
Referenced by _simple_replacements().
in_intrinsic_decl()
bool in_intrinsic_decl (void)
Return the predicate: current entity has the INTRINSIC attribute.
Definition at line 16481 of file semant.c.
References entity_attr, ET_B, and ET_INTRINSIC.
in_kernel_region()
LOGICAL in_kernel_region (void)
Definition at line 594 of file semfunc.c.
References df, DI_ACCDO, DI_ACCKERNELSDO, DI_ACCKERNELSLOOP, DI_ACCLOOP, DI_ACCPARALLELDO, DI_ACCPARALLELLOOP, DI_ACCREGDO, DI_ACCREGLOOP, DI_ACCSERIALLOOP, DI_CUFKERNEL, DI_ID, SEM::doif_depth, FALSE, sem, and TRUE.
in_save_scope()
bool in_save_scope (SPTR sptr)
Definition at line 2480 of file semutil.c.
References SEM::savall, sem, and sptr.
Referenced by do_save(), misc_checks(), ref_based_object_sc(), and semant1().
init_derived_type()
void init_derived_type (SPTR sptr, int parent_ast, int wherestd)
Definition at line 3548 of file semfin.c.
References add_stmt_after(), allocatable_member(), argt, ARGT_ARG, array_element_dtype(), BLOCK_ENTRY_STD, FALSE, find_descriptor_ast(), gbl, gen_dealloc_for_sym(), get_dtype_init_template(), get_static_type_descriptor(), get_struct_tag_sptr(), is_array_dtype(), mk_argt(), mk_assn_stmt(), mk_cval(), mk_func_node(), mk_id(), mk_stmt(), mk_unop(), mkRteRtnNm(), new_ast(), NOSYM, OP_VAL, presence_test(), rank_of_sym(), RTE_init_from_desc, sptr, std, and sym_mkfunc_nodesc().
Referenced by func_call2(), gen_finalized_result(), misc_checks(), and ptrfunc_call().
init_derived_w_acl()
int init_derived_w_acl (int in_sptr, ACL * sconst)
Definition at line 6506 of file semutil2.c.
References add_alloc_mem_initialize(), constructf90(), DTY, _acl::dtype, dtype, get_next_sym(), SEM::sc, sem, sptr, and SYMNAME.
Referenced by _constructf90(), mkarg(), semant3(), and semantio().
init_intrinsic_opr()
void init_intrinsic_opr (void)
Definition at line 1024 of file semgnr.c.
References i, OP_VAL, and optab.
Referenced by semant_init().
init_named_array_constant()
void init_named_array_constant (int arr, int host)
Initialize a named array constant (array PARAMETER), ensuring that it's only being done within the context of its host subprogram.
Definition at line 1533 of file semutil2.c.
References CONVAL2G, get_getitem_p(), host, and init_sptr_w_acl().
Referenced by fix_module_common(), fixup_param_vars(), and semant2().
init_sdsc()
int init_sdsc (int sptr, DTYPE dtype, int before_std, int parent_sptr)
Definition at line 12741 of file semutil2.c.
Referenced by gen_finalization_for_sym(), gen_kind_parm_assignments(), genPolyAsn(), and init_sdsc_bounds().
init_sdsc_bounds()
int init_sdsc_bounds (SPTR sptr, DTYPE dtype, int before_std, SPTR parent_sptr, int subscr, int td_ast)
Similar to init_sdsc() above, but it's also used to initialize a descriptor's bounds from a subscript expression.
Parameters
sptr is the symbol table pointer of the symbol with the descriptor to initialize.
dtype is the dtype used for initializing the descriptor.
before_std is the statement descriptor where we want to insert the initialization code (inserted before this std).
parent_sptr is the symbol table pointer of the enclosing object if sptr is an ST_MEMBER. Otherwise, it can be 0.
subscr is an AST representing the subscript expression that contains the array bounds. If it's not an A_SUBSCR, then init_sdsc() is called instead.
td_ast is an AST representing the descriptor that we are creating an instance of.
Returns
a statement descriptor of the generated statements.
Definition at line 12813 of file semutil2.c.
References AD_DPTR, AD_NUMDIM, ad_val_of(), add_stmt_after(), add_stmt_before(), argt, ARGT_ARG, ASD_SUBS, assert, ast, astb, ASTB::bnd, DDTG, DT_INT, ASTB::dtype, dtype_to_arg(), ERR_Fatal, i, init_sdsc(), mk_argt(), mk_bnd_int(), mk_func_node(), mk_id(), mk_isz_cval(), mk_member(), mkRteRtnNm(), nargs, ndims, NOSYM, RTE_instance, RTE_template, size_of_dtype(), sptr, std, stride, subscr, sym_mkfunc(), and TRUE.
Referenced by rewrite_allocatable_assignment().
init_sptr_w_acl()
int init_sptr_w_acl (int in_sptr, ACL * aclp)
Assign aclp values to in_sptr.
If in_sptr is 0, it assigns values to temporaries. init_sptr_w_acl() is called at the point we are trying to use (a possibly array/struct nested) constructor; eg. in mkexpr1(). If acl is constant, dinit_constructor() uses data initialization to assign the values; otherwise, _construct is called to generate runtime code to assign values. (is_const means: is constant, we can do it, and we're in the right context to do it.)
Definition at line 1620 of file semutil2.c.
References AC_ACONST, AC_IDO, acs, AD_DEFER, AD_DPTR, ADD_DEFER, ADD_EXTNTAST, ADD_LWBD, ADD_NUMDIM, add_stmt_before(), ADD_UPBD, ALLOCATE_ARRAYS, SEM::arrdim, SEM::arrfn, _ACS::arrtype, assert, ast, astb, ASTB::bnd, SEM::bounds, BZERO, constructf90(), convert_ctmp_array_to_param(), DBGBIT, dinit(), dinit_constructor(), SEM::dinit_data, dinit_varref(), _acl::dtype, dtype, ASTB::dtype, ERR_Fatal, FALSE, _ACS::func_in_do, gbl, gen_allocate_array(), get_adjlr_arr_temp(), get_all_descriptors(), get_arr_const(), get_arr_temp(), get_static_descriptor(), i, _acl::id, interr(), _acl::is_const, _ACS::is_const, lb, lbound_of(), memsym_of_ast(), mk_assn_stmt(), mk_id(), ndim, NOSYM, ASTB::one, printacl(), restore_dim_specs(), SEM::return_value, rewrite_acl(), S_IDENT, save_dim_specs(), sem, _acl::size, sptr, SEM::sptr, SST_ASTP, SST_DTYPEP, SST_IDP, SST_SHAPEP, std, STD_NEXT, STD_PREV, _acl::subc, _ACS::tmp, ub, void(), and ASTB::zero.
Referenced by _constructf90(), init_named_array_constant(), mkarg(), mkexpr1(), and mkvarref().
init_use_stmts()
void init_use_stmts (void)
Definition at line 221 of file module.c.
References BZERO, FIRST_USER_MODULE, NEW, NULL, and usedb.
Referenced by semant1().
internal_proc_has_ident()
int internal_proc_has_ident (int ident, int proc)
Definition at line 14042 of file semant.c.
References dirty_ident_base, HASH_STR, ident_list::ident, ident_base, ident_proc_list::next, ident_list::next, ident_list::proc_list, ident_proc_list::proc_name, strlen(), SYMNAME, and ident_proc_list::usecnt.
Referenced by declsym(), and semant1().
intrinsic_as_arg()
int intrinsic_as_arg (int intr)
Definition at line 851 of file semfunc2.c.
References cp, dt, FLANG_FALLTHROUGH, intast_sym, mkRteRtnNm(), STB::n_base, RTE_indexDsc, RTE_indexx_cr_nma, RTE_indexx_cra, RTE_indexxa, RTE_lenDsc, RTE_lenx_cr_nma, RTE_lenx_cra, RTE_lenxa, select_gsame(), stb, sym_mkfunc(), SYMNAME, WINNT_CALL, WINNT_CREF, WINNT_NOMIXEDSTRLEN, and XBIT.
Referenced by assign_pointer(), and mkarg().
ipa_semfin()
void ipa_semfin (void)
is_alloc_ast()
LOGICAL is_alloc_ast (int ast)
Definition at line 14662 of file semutil2.c.
References A_TKNG, ast, and FALSE.
Referenced by compute_invariant(), invar_motion(), and is_std_hoistable().
is_alloc_std()
LOGICAL is_alloc_std (int std)
Definition at line 14680 of file semutil2.c.
References A_TKNG, ast, FALSE, std, and STD_AST.
Referenced by alldefs_allocsafe().
is_dealloc_ast()
LOGICAL is_dealloc_ast (int ast)
Definition at line 14671 of file semutil2.c.
References A_TKNG, ast, and FALSE.
Referenced by compute_invariant(), invar_motion(), and is_std_hoistable().
is_dealloc_std()
LOGICAL is_dealloc_std (int std)
Definition at line 14692 of file semutil2.c.
References A_TKNG, ast, FALSE, std, and STD_AST.
Referenced by hoist_stmt().
is_dovar_sptr()
void is_dovar_sptr (int sptr)
Definition at line 9652 of file semsmp.c.
References DI_NOSCOPE_AVL, DI_NOSCOPE_BASE, SEM::doif_depth, i, sem, and sptr.
Referenced by semant2(), semant3(), and semantio().
is_except_in_scope()
LOGICAL is_except_in_scope (SCOPESTACK * scope, int sptr)
Return TRUE if sptr is in the exception list for this scope at this level.
Definition at line 184 of file scopestack.c.
References scope, sptr, and sym_in_sym_list().
Referenced by add_only(), find_def_in_most_recent_scope(), find_in_host(), sym_in_scope(), sym_visible_in_scope(), and test_scope().
is_parameter_context()
int is_parameter_context ()
allow other source files to check whether we're processing a parameter construct.
Definition at line 16460 of file semant.c.
References entity_attr, ET_B, and ET_PARAMETER.
Referenced by _mk_arrdsc(), and semant2().
is_private_in_scope()
LOGICAL is_private_in_scope (SCOPESTACK * scope, int sptr)
Return TRUE if scope is private and has sptr in its 'only' list.
Definition at line 192 of file scopestack.c.
References scope, sptr, and sym_in_sym_list().
Referenced by find_def_in_most_recent_scope(), and sym_visible_in_scope().
is_protected()
LOGICAL is_protected (int sptr)
Definition at line 4689 of file semutil.c.
References FALSE, SEM::mod_sym, sem, sptr, and TRUE.
Referenced by assign_pointer(), chk_arguments(), chk_pointer_target(), semant3(), and set_assn().
is_sptr_in_shared_list()
int is_sptr_in_shared_list (SPTR)
Referenced by check_parref().
legal_labelvar()
LOGICAL legal_labelvar (int dtype)
Definition at line 6746 of file semutil.c.
References STB::dt_int, FALSE, stb, TRUE, and STB::user.
Referenced by chk_fmtid(), and semant3().
link_members()
void link_members (STSK * stsk, int sptr)
Link together members of a structure.
Parameters
stsk the structure stack item representing the structure to which members are added
sptr points to a list of new members linked via symlk
The new member list is added to the end of the existing member list watching out for duplicate member names.
Definition at line 1970 of file semutil.c.
References assert, check_parent(), CNULL, count, DTY, STSK::dtype, dtype, error(), gbl, get_entity_access(), STSK::last, STSK::mem_access, NOSYM, sptr, stsk, and SYMNAME.
Referenced by link_parents(), semant1(), and setup_procedure_sym().
link_parents()
void link_parents (STSK * stsk, int sptr)
Link parents for type extension by adding parent as a member to the type.
Definition at line 1913 of file semutil.c.
References DTY, insert_sym(), link_members(), sptr, STSK::sptr, and stsk.
Referenced by semant1().
llvm_fix_args()
void llvm_fix_args (int sptr)
Definition at line 1173 of file semfin.c.
References fix_args(), and sptr.
Referenced by llvm_check_retval_inargs().
llvm_set_tbp_dtype()
void llvm_set_tbp_dtype (int dtype)
make_keyword_str()
char * make_keyword_str (int paramct, int dpdsc)
Make a keyword string from the DPDSC auxiliary structure.
Definition at line 1476 of file semfunc2.c.
References arg, aux, avl, cnt, AUX::dpdsc_base, i, len, name, NEED, NEW, size, strlen(), SYMNAME, and td.
Referenced by make_kwd_str(), ptrfunc_call(), and ptrsubr_call().
make_kwd_str()
char * make_kwd_str (int ext)
Make a keyword string for a ST_PROC.
Definition at line 1467 of file semfunc2.c.
References make_keyword_str().
Referenced by args_match(), func_call2(), and subr_call2().
mk_arrdsc()
DTYPE mk_arrdsc (void)
Definition at line 573 of file semutil2.c.
References _mk_arrdsc().
Referenced by decl_private_sym(), gen_array_result(), instantiate_interface(), mk_array_type(), ref_pd(), and semant1().
mk_assumed_shape()
void mk_assumed_shape (SPTR sptr)
Definition at line 840 of file semutil2.c.
References AD_ASSUMRANK, AD_ASSUMSHP, AD_DPTR, AD_LWAST, AD_LWBD, AD_NUMDIM, SEM::arrdim, astb, ASTB::bnd, dt, i, ASTB::one, sem, sptr, tempvar(), and XBIT.
Referenced by semant1().
mk_component_ast()
int mk_component_ast (int leaf, int parent, int src_ast)
Definition at line 4469 of file semutil.c.
References AD_DPTR, AD_LWAST, AD_NUMDIM, AD_UPAST, add(), ASD_SUBS, DDTG, dt, DTY, i, interr(), MAXDIMS, mk_id(), mk_subscr(), mk_triple(), ndim, nsubs, and parent.
mk_cuda_builtins()
void mk_cuda_builtins (int * , int * , int)
mk_cuda_typedef()
int mk_cuda_typedef (char *)
mk_defer_shape()
void mk_defer_shape (SPTR sptr)
Definition at line 803 of file semutil2.c.
References AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_NUMDIM, AD_UPAST, dt, i, IN_MODULE_SPEC, mk_bnd_ast(), and sptr.
Referenced by semant1().
mk_init_intrinsic()
ACL * mk_init_intrinsic (AC_INTRINSIC init_intr)
Definition at line 3505 of file semutil2.c.
References AC_ICONST, AC_IEXPR, AC_INTR_CALL, BZERO, _acl::expr, GET_ACL, getitem(), _acl::id, CONST::id, AEXPR::lop, AEXPR::op, _acl::u1, and CONST::u1.
Referenced by init_allocatable_typedef_components(), mk_elem_init_intrinsic(), mk_nonelem_init_intrinsic(), mk_reshape_intrin(), mk_shape_intrin(), mk_size_intrin(), mk_transfer_intrin(), mk_transpose_intrin(), and mk_ulbound_intrin().
mk_mbr_ref()
int mk_mbr_ref (int , char *)
mk_set_type_call()
int mk_set_type_call (int arg0, int arg1, LOGICAL intrin_type)
Creates an ast that represents a call to a set type runtime routine.
Parameters
arg0 is the ast of the descriptor that receives the type from arg1.
arg1 is the ast of the source descriptor. The type of arg1 is copied into the arg0 descriptor.
intrin_type is true when you want to use the RTE_set_intrin_type() routine instead of the RTE_set_type() routine.
Returns
the call ast
Definition at line 14716 of file semutil2.c.
References ARGT_ARG, func, mk_argt(), mk_func_node(), mk_id(), mkRteRtnNm(), RTE_set_intrin_type, RTE_set_type, and sym_mkfunc_nodesc().
Referenced by check_pointer_type(), gen_poly_element_arg(), gen_set_type(), init_intrin_type_desc(), rewrite_allocatable_assignment(), semant1(), and semant3().
mk_struct_constr()
void mk_struct_constr (int , int)
mkmember()
int mkmember (int structd, int base, int nmx)
Parameters
structd dtype record of parent structure
base ast ptr of parent structure
nmx index into "names" area of member
Returns
ast or 0 if not found
Definition at line 6651 of file semutil.c.
References ast, base, DTY, dtype, flg, mk_id(), mk_member(), mkmember(), mkunion(), NOSYM, sptr, FLG::xref, and xrefput().
Referenced by _constructf90(), add_iolptrs(), is_intrinsic_opr(), mkmember(), mkunion(), semant2(), and semant3().
mod_add_subprogram()
int mod_add_subprogram (int subp)
Definition at line 2298 of file module.c.
References arg, ast_implicit(), aux, count, DLL_EXPORT, DLLP, AUX::dpdsc_base, IMPL::dtype, export_append_sym(), FALSE, IMPL::firstc, FUNCLINEP, gbl, getstring(), i, impl, insert_dup_sym(), IMPL::lastc, SEM::mod_dllexport, modu_name, RU_FUNC, s, sem, setimplicit(), strlen(), SYMNAME, TRUE, and XBIT.
Referenced by semant1().
mod_combined_index()
void mod_combined_index (const char * name)
Definition at line 1047 of file module.c.
References name, and single_outfile_index_name.
Referenced by init().
mod_combined_name()
void mod_combined_name (const char * name)
Definition at line 1038 of file module.c.
References name, and single_outfile_name.
Referenced by init().
mod_end_subprogram()
void mod_end_subprogram (void)
Definition at line 2404 of file module.c.
References export_public_used_modules(), SEM::mod_cnt, SEM::mod_public_level, and sem.
Referenced by do_end_subprogram(), and semant1().
mod_end_subprogram_two()
void mod_end_subprogram_two (void)
Definition at line 2425 of file module.c.
References SEM::accl, arg, aux, AUX::dpdsc_base, STB::firstusym, gbl, i, limitsptr, SEM::mod_cnt, SEM::mod_public_flag, _accl::next, NOSYM, NULL, reset_module_state(), RU_FUNC, sem, sptr, _accl::sptr, stb, and _accl::type.
Referenced by semant1().
mod_fini()
void mod_fini (void)
Definition at line 1994 of file module.c.
References error(), fclose(), gbl, GBL_SIZE_T_FORMAT, LLF, mod_index_list, NULL, p, q, single_outfile, single_outfile_index_name, single_outfile_name, and strlen().
Referenced by finish().
mod_implicit()
void mod_implicit (int firstc, int lastc, int dtype)
Definition at line 1123 of file module.c.
References i, impl, and NEED.
Referenced by semant1().
mod_init()
void mod_init (void)
Definition at line 2277 of file module.c.
References astb, dbg_dump(), exportb, EXPORTB::hmark, i, init_use_tree(), limitsptr, EXPORTB::maxast, SEM::mod_public_level, new_node(), restore_module_state(), SEM::scope_level, sem, stb, and void().
Referenced by semant_init().
mod_type()
int mod_type (int dtype, int ty, int kind, int len, int propagated, int sptr)
Return a new data type based on the rules of applying a length specifier to an existing base data type (i.e. LOGICAL*1) passed in as a TY_ value.
sptr points to the symbol table entry whose data type is being modified. This is for error messages. If no sptr then message is for type declaration verb.
Special case:
‍ When sptr is 0, the data type adjustment is occurring at the time when the length immediately follows a data type (i.e. when <data type> is being processed). When sptr is non-zero, this means that the length follows the name of the symbol (<data type> has already been processed) (i.e. CHARACTER FOO*1); and a length of -1 implies that no length was specified.
So, when sptr is nonzero and len is -1, we do not attempt to adjust the data type; if so, we will incorrectly adjust
      REAL*4  rv
when the "r8" option has been selected (-x 124 8).
Definition at line 5568 of file semutil.c.
References astb, CNULL, DT_INT, DT_LOG, DTY, dtype, error(), FLANG_FALLTHROUGH, flg, gbl, get_type(), ASTB::i0, ASTB::i1, FLG::i4, interr(), kind, len, mk_cval(), SEM::ogdtype, propagated, sem, sptr, SYMNAME, TY_BINT, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_REAL, and XBIT.
Referenced by get_retval_LEN_value(), and semant1().
module_must_hide_this_symbol()
void module_must_hide_this_symbol (int sptr)
Definition at line 14037 of file semutil2.c.
References module_must_hide_this_symbol_sptr, and sptr.
Referenced by replace_variable().
mp_create_bscope()
int mp_create_bscope (int reuse)
Definition at line 14408 of file semutil2.c.
References add_stmt(), ast, BLK_SCOPE_SPTR, BLK_UPLEVEL_SPTR, SEM::blksymnum, getccssym(), i, llmp_create_uplevel(), llmp_uplevel_set_parent(), mk_id(), mk_stmt(), SEM::scope_level, sem, and void().
Referenced by begin_combine_constructs(), do_btarget(), do_bteams(), do_distbegin(), and semsmp().
mp_create_escope()
int mp_create_escope (void)
Definition at line 14462 of file semutil2.c.
References add_stmt(), ast, BLK_UPLEVEL_SPTR, mk_stmt(), SEM::scope_level, sem, and void().
Referenced by do_end(), end_target(), end_teams(), and semsmp().
need_alloc_ch_temp()
int need_alloc_ch_temp (DTYPE dtype)
Definition at line 8164 of file semutil2.c.
Referenced by ref_pd().
newsym()
int newsym (int sptr)
Reset fields of intrinsic or generic symbol, sptr, to zero in preparation for changing its symbol type by the Semantic Analyzer.
If the symbol type of the symbol has been 'frozen', issue an error message and notify the caller by returning a zero symbol pointer.
Definition at line 1183 of file semsym.c.
References CNULL, error(), FALSE, gbl, getocsym(), getsym(), insert_sym(), LOCAL_SYMNAME, sptr, strlen(), and SYMNAME.
Referenced by chkarg(), convert_intrinsics_to_idents(), declref(), declsym(), export_fix_host_append_list(), find_outer_sym(), gen_dinit(), get_type_rank(), matmul(), mkarg(), mkexpr1(), mklvalue(), mkvarref(), mmul(), ref_ident(), ref_ident_inscope(), ref_int_scalar(), ref_intrin(), ref_intrin_subr(), ref_pd(), ref_pd_subr(), ref_storage_inscope(), reshape(), rewrite_func_ast(), semant1(), semant3(), and subr_call2().
next_scope()
SCOPESTACK * next_scope (SCOPESTACK * scope)
Return the next entry below this one in the scope stack; 0 if none. If scope is 0, return the top of the stack.
Definition at line 93 of file scopestack.c.
References curr_scope(), get_scope_level(), and scope.
Referenced by apply_use(), do_lastprivate(), export_public_used_modules(), find_in_host(), have_use_scope(), next_scope_kind(), next_scope_sptr(), par_push_scope(), and sym_in_scope().
next_scope_kind()
SCOPESTACK * next_scope_kind (SCOPESTACK * scope, SCOPEKIND kind)
Return the next entry below scope that has this kind. If scope is 0, search from the top of the stack.
Definition at line 124 of file scopestack.c.
References kind, next_scope(), and scope.
Referenced by declsym(), find_in_host(), next_scope_kind_sptr(), next_scope_kind_symname(), scope_in_scope_stack(), and sem_import_sym().
next_scope_kind_sptr()
SCOPESTACK * next_scope_kind_sptr (SCOPESTACK * scope, SCOPEKIND kind, int sptr)
Return the next entry below scope that has this kind and sptr. If scope is 0, search from the top of the stack.
Definition at line 138 of file scopestack.c.
References kind, next_scope_kind(), scope, and sptr.
Referenced by sym_in_scope().
next_scope_kind_symname()
SCOPESTACK * next_scope_kind_symname (SCOPESTACK * scope, SCOPEKIND kind, const char * symname)
Return the next entry below scope that has this kind and symbol name. If scope is 0, search from the top of the stack.
Definition at line 152 of file scopestack.c.
References kind, next_scope_kind(), scope, and SYMNAME.
Referenced by import_use_stmts().
next_scope_sptr()
SCOPESTACK * next_scope_sptr (SCOPESTACK * scope, int sptr)
Return the next entry below scope that has this sptr assocated with it. If scope is 0, search from the top of the stack.
Definition at line 110 of file scopestack.c.
References next_scope(), scope, and sptr.
Referenced by add_only(), apply_use(), find_def_in_most_recent_scope(), and scope_in_scope_stack().
not_in_forall()
LOGICAL not_in_forall (const char * stmttype)
Check if we are currently in a block FORALL scope; if so, issue an error message.
Definition at line 8452 of file semutil2.c.
Referenced by misc_io_checks(), and semant3().
open_module()
void open_module (SPTR use)
Begin processing a USE statement. use - sym ptr of module identifer in use statement Find or create an entry in usedb for it and set 'module_id' to the index.
Definition at line 863 of file module.c.
References convert_2dollar_signs_to_hyphen(), erremit(), error(), FALSE, first, FIRST_MODULE, STB::firstusym, gbl, get_module_file_name(), getitem(), i, IEEE_ARITH_MOD, IEEE_FEATURES_MOD, insert_sym(), iso_c_lib_stat(), ISO_C_MOD, ISO_FORTRAN_ENV, last, lookupsymbol(), MAX_FNAME_LEN, MOD_SUFFIX, module_id, name, NEED, NEW, NEWSYM, NOSYM, NULL, pd_mod_entries, SEM::scope_level, sem, set_exitcode(), sptr, stb, strlen(), SYMNAME, use, usedb, and XBIT.
Referenced by semant1().
par_add_stblk_shvar()
void par_add_stblk_shvar (void)
Definition at line 9666 of file semsmp.c.
par_pop_scope()
void par_pop_scope (void)
Definition at line 411 of file scopestack.c.
par_push_scope()
void par_push_scope (LOGICAL bind_to_outer)
Definition at line 379 of file scopestack.c.
References curr_scope(), FLG::debug, SEM::doif_depth, SCOPESTACK::end_prologue, enter_lexical_block(), flg, get_scope(), kind, SCOPESTACK::kind, next_scope(), SEM::next_unnamed_scope, NULL, SCOPESTACK::par_scope, PAR_SCOPE_SHARED, SEM::parallel, push_scope_level(), SCOPESTACK::rgn_scope, SEM::sc, scope, SEM::scope_level, SCOPE_PAR, sem, SEM::target, SEM::task, SEM::teams, and XBIT.
Referenced by begin_combine_constructs(), do_bdistribute(), do_btarget(), do_bteams(), do_distbegin(), and semsmp().
parstuff_init()
void parstuff_init (void)
Definition at line 5768 of file semsmp.c.
References any_pflsr_private, chunk, CL_FIRST, CL_LAST, CL_MAXV, CL_PRESENT, CL_VAL, distchunk, FALSE, i, IF_DEFAULT, mp_iftype, NULL, and recent_loop_clause.
Referenced by begin_combine_constructs(), semant1(), and semsmp().
pop_accel_vars()
void pop_accel_vars (void)
pop_scope_level()
void pop_scope_level (SCOPEKIND kind)
Definition at line 250 of file scopestack.c.
References curr_scope(), STB::curr_scope, DBGBIT, dumpscope(), ERR_Severe, gbl, get_scope(), SEM::interface, interr(), kind, SCOPESTACK::kind, kind_to_string(), NULL, parent, pop_scope(), pop_sym(), scope, SCOPE_BLOCK, SCOPE_INTERFACE, SEM::scope_level, SCOPE_PAR, SEM::scope_stack, sem, sptr, SCOPESTACK::sptr, ST_ISVAR, stb, top, and SEM::which_pass.
Referenced by do_end_subprogram(), do_nested_uses(), par_pop_scope(), semant1(), and semfin().
pop_tbp_arg()
ITEM * pop_tbp_arg (void)
Definition at line 6145 of file semant3.c.
References sem, SEM::tbp_arg, and SEM::tbp_arg_cnt.
Referenced by semant2(), and semant3().
process_struct_components()
void process_struct_components (int , void(*)(int))
propagate_attr()
void propagate_attr (int , int)
push_scope_level()
void push_scope_level (int sptr, SCOPEKIND kind)
Push a slot on the scope stack.
Parameters
sptr For most scopes, scope symbol. For interface and parallel scopes, a small (unnamed) numeric index.
kind Scope kind.
Definition at line 203 of file scopestack.c.
References STB::curr_scope, DBGBIT, dumpscope(), ERR_Warning, gbl, interr(), kind, kind_to_string(), NULL, push_scope(), scope, SCOPE_BLOCK, SCOPE_INTERFACE, SCOPE_MODULE, SCOPE_NORMAL, SCOPE_PAR, SEM::scope_stack, SCOPE_SUBPROGRAM, SCOPE_USE, sem, setfile(), sptr, stb, SYMNAME, TRUE, and SEM::which_pass.
Referenced by do_nested_uses(), dummy_program(), import_module(), par_push_scope(), semant1(), and semfin().
push_tbp_arg()
void push_tbp_arg (ITEM * item)
Definition at line 6131 of file semant3.c.
References getitem(), i, sem, SEM::tbp_arg, and SEM::tbp_arg_cnt.
Referenced by semant2(), and semant3().
put_default_kind_type_param()
void put_default_kind_type_param (int dtype, int flag, int flag2)
Definition at line 15492 of file semant.c.
References BZERO, chkstruct(), DTY, FREE, has_type_parameter(), mem(), NEW, next, NOSYM, NULL, offset, prev, put_default_kind_type_param(), put_kind_type_param(), and val.
Referenced by get_keyword_components(), put_default_kind_type_param(), and semant1().
put_kind_type_param()
LOGICAL put_kind_type_param (DTYPE dtype, int offset, int value, int expr, int flag)
Definition at line 15922 of file semant.c.
References ast, chk_kind_parm_expr(), chk_kind_parm_set_expr(), CONVAL2G, DT_ISCMPLX, DT_ISINT, DT_ISREAL, DTY, ERR_Severe, error(), FALSE, gbl, get_len_parm(), get_len_parm_by_number(), get_type(), is_pdt_dtype(), mem(), SEM::new_param_dt, NOSYM, offset, put_kind_type_param(), select_kind(), sem, sym_of_ast(), SYMNAME, TRUE, TY_CHAR, TY_CMPLX, TY_INT, TY_NCHAR, TY_REAL, SEM::type_mode, and value().
Referenced by defer_put_kind_type_param(), put_default_kind_type_param(), put_kind_type_param(), and semant2().
put_length_type_param()
void put_length_type_param (DTYPE dtype, int flag)
Definition at line 15536 of file semant.c.
References A_OPTYPEG, A_OPTYPEP, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_MLPYR, AD_NUMDIM, AD_UPAST, ADD_NUMELM, ast, astb, ASTB::bnd, BZERO, chk_asz_deferlen(), chk_kind_parm_set_expr(), chkstruct(), cl, CONVAL2G, create_parameterized_dt(), DT_INT, DTY, ASTB::dtype, dup_array_dtype(), FREE, get_all_descriptors(), get_extent(), get_local_multiplier(), get_static_descriptor(), has_type_parameter(), i, ASTB::i0, interr(), lb, mem(), mk_binop(), mk_bnd_int(), mk_id(), mk_isz_cval(), mk_stmt(), NEW, SEM::new_param_dt, next, NOSYM, NULL, OP_ADD, OP_MUL, OP_SUB, prev, put_length_type_param(), replace_sdsc_in_bounds(), sem, sym_get_scalar(), sym_get_sdescr(), SYMNAME, TRUE, TY_CHAR, TY_NCHAR, and ub.
Referenced by get_keyword_components(), put_length_type_param(), semant1(), and semant3().
queue_tbp()
int queue_tbp (int sptr, int bind, int offset, int dtype, tbpTask task)
Main function for processing type bound procedures (tbps), generic type bound procedures, derived type I/O generic type bound procedures, and final subroutines.
Parameters
sptr is the symbol table pointer of the implementation name of tbp
bind symbol table pointer to the binding name of tbp
offset is the integer offset of tbp in its "virtual function table"
dtype is the enclosing dtype of the type bound procedure
task is the type of processing to be performed (see tbpTask definition in semant.h)
Definition at line 173 of file semtbp.c.
References addDeferredTbp(), addExplicitIface(), addFinalSubroutine(), addNonOverridableTbp(), addNoPassArg(), addPassArg(), addPrivateAttribute(), addPublicAttribute(), addTbpInterface(), addToDtype(), clearStaleRecs(), dtypeHasTbp(), enqueueTbp(), inheritTbps(), initTbp(), IS_ADD_DEFERRED_TBP_TASK, IS_ADD_EXPLICIT_IFACE_TBP_TASK, IS_ADD_FINAL_SUB_TASK, IS_ADD_NON_OVERRIDABLE_TBP_TASK, IS_ADD_PRIVATE_TBP_TASK, IS_ADD_PUBLIC_TBP_TASK, IS_ADD_TBP_INTERFACE_TASK, IS_ADD_TBP_NOPASS_ARG_TASK, IS_ADD_TBP_PASS_ARG_TASK, IS_ADD_TBP_TASK, IS_ADD_TBP_TO_DTYPE_TASK, IS_CLEAR_STALE_RECORDS_TASK, IS_CLEAR_TBP_TASK, IS_INHERIT_TBP_TASK, IS_RESOLVE_TBP_TASK, IS_TBP_STATUS_TASK, offset, resolveTbps(), sptr, and task.
Referenced by check_defined_io2(), defined_operator(), do_end_subprogram(), find_best_generic(), generic_tbp_call(), generic_tbp_func(), get_implementation(), is_intrinsic_opr(), reinit(), resolveGeneric(), resolveTbps(), semant1(), and semfin().
queue_type_param()
int queue_type_param (int sptr, int dtype, int offset, int flag)
Sets up type parameters used in parameterized derived types (PDTs)
Definition at line 14647 of file semant.c.
References BZERO, c, DTY, error(), FREE, gbl, i, mem(), name, NEW, next, NOSYM, offset, parent, prev, queue_type_param(), sptr, strlen(), and SYMNAME.
Referenced by chk_kind_parm(), chk_kind_parm_expr(), chk_len_parm_expr(), has_kind_parm_expr(), queue_type_param(), search_kind(), semant1(), and semant2().
re_struct_constr()
void re_struct_constr (int , int)
ref_based_object()
int ref_based_object (int sptr)
Reference a based object.
Since it's possible to have more than one level of 'based' storage, need to scan through the MIDNUM fields until the "pointer" variable is found. Along the way, it may be necessary to fix the stypes of the based variables and to create xref 'r' records. Also, the storage class of the 'pointer' variable is fixed if necessary. The symbol table index of the 'pointer' variable is returned.
Definition at line 1390 of file semsym.c.
References ref_based_object_sc(), and sptr.
Referenced by find_outer_sym(), gen_pointer_result(), ref_object(), and semant3().
ref_based_object_sc()
int ref_based_object_sc (int sptr, SC_KIND sc)
Definition at line 1398 of file semsym.c.
References AD_EXTNTAST, AD_LWAST, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_PTR, AD_UPAST, AD_ZBASE, assert, check_parref(), DT_PTR, DTY, F77OUTPUT, fixup_reqgs_ident(), flg, gbl, get_all_descriptors(), get_static_descriptor(), getccsym(), i, in_save_scope(), mark_static(), NOSYM, set_internref_flag(), FLG::smp, sptr, sym_get_ptr(), TRUE, FLG::xref, and xrefput().
Referenced by gen_allocatable_result(), gen_array_result(), and ref_based_object().
ref_entry()
int ref_entry (int ent)
Definition at line 1306 of file semfunc2.c.
References DT_INT, DTY, gbl, get_all_descriptors(), get_fval_array(), get_static_descriptor(), getsymbol(), insert_sym(), INTENT_OUT, INTENTP, name, SEM::orph, SEM::parallel, pop_sym(), sem, sem_check_scope(), SYMNAME, SEM::target, SEM::task, and SEM::teams.
Referenced by chkarg(), chksubstr(), find_outer_sym(), func_call2(), mkarg(), mkexpr1(), mklvalue(), mkvarref(), ptrfunc_call(), ref_array(), ref_storage(), ref_storage_inscope(), refsym(), semant3(), and semfin().
ref_ident()
int ref_ident (int sptr)
Reference a symbol when it's known the context requires an identifier.
If an error occurs (e.g., symbol which is frozen as an intrinsic), a new symbol is created so that processing can continue. If the symbol found is ST_UNKNOWN, its stype is changed to ST_IDENT.
Definition at line 1235 of file semsym.c.
References insert_sym(), IS_INTRINSIC, newsym(), refsym(), and sptr.
Referenced by ref_storage(), semant1(), and semsmp().
ref_ident_inscope()
int ref_ident_inscope (int sptr)
Definition at line 1252 of file semsym.c.
References insert_sym(), IS_INTRINSIC, newsym(), refsym_inscope(), and sptr.
Referenced by semant1().
ref_int_scalar()
int ref_int_scalar (int sptr)
Reference a symbol when it's known the context requires an integer scalar variable.
If an error occurs (e.g., symbol which is frozen as an intrinsic), a new symbol is created so that processing can continue. If the symbol found is ST_UNKNOWN, its stype is changed to ST_IDENT.
Definition at line 1345 of file semsym.c.
References DT_ISINT, error(), gbl, insert_sym(), IS_INTRINSIC, newsym(), refsym(), sptr, and SYMNAME.
ref_object()
int ref_object (int sptr)
Access the address of the object (sym).
Definition at line 2600 of file semutil.c.
References SEM::orph, SEM::parallel, ref_based_object(), sem, sem_check_scope(), sptr, SEM::target, SEM::task, and SEM::teams.
Referenced by chksubstr(), do_distbegin(), do_index_addr(), mkarg(), mkexpr1(), mkexpr2(), mklvalue(), mkvarref(), and ref_array().
ref_storage()
int ref_storage (int sptr)
Reference a symbol when it's known the context requires storage, e.g., a variable or the result of a function.
If an error occurs (e.g., symbol which is frozen as an intrinsic), a new symbol is created so that processing can continue. If the symbol found is ST_UNKNOWN, its stype is changed to ST_IDENT.
Definition at line 1279 of file semsym.c.
References DTY, gbl, ref_entry(), ref_ident(), RU_FUNC, and sptr.
ref_storage_inscope()
int ref_storage_inscope (int sptr)
Definition at line 1304 of file semsym.c.
References DTY, gbl, insert_sym(), IS_INTRINSIC, newsym(), ref_entry(), refsym_inscope(), RU_FUNC, and sptr.
refocsym()
int refocsym (int first, OVCLASS oclass)
Reference the first symbol of the given overloading class in the current scope. If not found, zero is returned.
Definition at line 1495 of file semsym.c.
References first, NULL, STB::ovclass, sptr, st, stb, and sym_in_scope().
Referenced by do_dot(), and resolveImp().
refsym()
int refsym (int first, OVCLASS oclass)
Look up a symbol having the given overloading class.
If the symbol with the overloading class is found its sptr is returned. If no symbol with the given overloading class is found, a new sptr is returned.
Definition at line 946 of file semsym.c.
References BLK_UPLEVEL_SPTR, first, flg, gbl, insert_sym(), SEM::interface, NULL, STB::ovclass, SEM::parallel, ref_entry(), RU_FUNC, SEM::scope_level, sem, set_internref_flag(), set_parref_flag(), sptr, st, stb, sym_in_scope(), SEM::target, SEM::task, SEM::teams, FLG::xref, and xrefput().
Referenced by _do_iface(), chk_func_entry_result(), decl_private_sym(), declobject(), do_access(), do_copyin(), do_copyprivate(), find_outer_sym(), get_derived_type(), ref_ident(), ref_int_scalar(), ref_pd(), sem_check_scope(), semant1(), semant2(), semant3(), semantio(), and semsmp().
refsym_inscope()
int refsym_inscope (int first, OVCLASS oclass)
Similar to refsym() except that the current scope is taken into consideration.
If the symbol with the overloading class is found its sptr is returned. If no symbol with the given overloading class is found, a new sptr is returned.
Definition at line 1009 of file semsym.c.
References STB::curr_scope, error(), first, STB::firstusym, flg, gbl, insert_sym(), SEM::interface, IS_INTRINSIC, SCOPESTACK::kind, level(), SEM::mod_sym, NULL, STB::ovclass, SEM::scope_level, SCOPE_NORMAL, SEM::scope_stack, sem, set_internref_flag(), sptr, st, stb, sym_in_scope(), SYMNAME, FLG::xref, and xrefput().
Referenced by _do_iface(), create_var(), get_csect_sym(), ref_ident_inscope(), ref_storage_inscope(), semant1(), and semant2().
reset_internal_subprograms()
void reset_internal_subprograms (void)
Definition at line 13953 of file semutil2.c.
References FALSE, state_append_file_full, state_file_position, and state_still_pass_one.
Referenced by parser().
reset_module_state()
void reset_module_state (void)
Called at the end of a module-contained subprogram; rearranges the data structures for the module.
Definition at line 14093 of file semutil2.c.
References errfatal(), export_module_subprogram(), gbl, interr(), modsaved_astavl, modsaved_dtyavl, modsaved_symavl, modstate_append_file, modstate_append_file_full, modstate_file, NULL, rw_host_state(), sem, tmpfile(), and SEM::which_pass.
Referenced by mod_end_subprogram_two().
resolve_fwd_refs()
void resolve_fwd_refs (void)
Resolve forward references: try to find the declaration symbol and replace the reference symbol with it.
F95 allows forward references to pure functions from within specification expressions. A symbol will be created at the reference which must be fixed later after the function declaration has been seen. Possible forward references are marked FWDREF in mkvarref() above.
Definition at line 2447 of file semutil.c.
References first_hash(), STB::firstusym, and stb.
Referenced by parser().
restore_host_state()
void restore_host_state (int whichpass)
Called at the end of an internal subprogram.
In pass 1:
Save the internal subprogram information, kind of like interface blocks. If there is more than 1 internal subprogram, the information is exported collectively, that is, all subprograms are exported each time.
Save any labels for internal subprograms. These labels are restored by restore_internal_subprograms() below.
Restores the host information for the next subprogram.
Reimport any internal subprograms as contained subprograms. This information will be reimported in pass 2 by restore_internal_subprograms() below.
In pass 2:
Restore the host information for the next subprogram, as this will have been saved by the save_host_state call for the host subprogram and will include all the contained subprograms information as imported in restore_internal_subprograms() for the host routine.
Definition at line 13759 of file semutil2.c.
References errfatal(), export_append_host_sym(), export_host_subprogram(), fflush(), STB::firstusym, fix_symtab(), SEM::flabels, gbl, import_host_subprogram(), interr(), len, SEM::mod_sym, NEED, NEW, NOSYM, NULL, rw_host_state(), saved_astavl, saved_dtyavl, saved_labels, saved_labels_avail, saved_labels_pos, saved_labels_size, saved_symavl, SEM::scope_level, SEM::scope_stack, sem, SCOPESTACK::sptr, state_append_file, state_append_file_full, state_file, state_file_position, state_last_routine, state_still_pass_one, stb, strlen(), SYMNAME, tmpfile(), and TRUE.
Referenced by semant1(), and semant_init().
restore_internal_subprograms()
void restore_internal_subprograms (void)
Called at the beginning of a subprogram in pass 2.
Checks whether there is information available for subprograms contained in this one, as saved by restore_host_state().
If so, restores that more or less like an interface block.
If the current routine is an internal subprogram, its labels are restored. This is so FORMAT labels that appear in both the inner and outer subprogram are properly resolved.
Definition at line 13882 of file semutil2.c.
References cp, STB::curr_scope, dummy_program(), exterf_init_host(), gbl, getsymbol(), import_host(), insert_sym(), interr(), SEM::mod_sym, NOSYM, saved_astavl, saved_dtyavl, saved_labels, saved_labels_pos, saved_symavl, SEM::scope_level, SEM::scope_stack, sem, sptr, SCOPESTACK::sptr, state_append_file, state_append_file_full, state_file_position, state_still_pass_one, stb, strlen(), and SYMNAME.
Referenced by semant1().
restore_module_state()
void restore_module_state (void)
Called at start of module-contained subprogram, restores state. If this is the first 'restore' since the last 'reset', the 'module append' file is full and needs to be imported.
Definition at line 14047 of file semutil2.c.
References astb, STB::dt, errfatal(), gbl, SEM::ieee_features, import_host(), mod_clear_init, modsave_ieee_features, modsaved_astavl, modsaved_dtyavl, modsaved_symavl, modstate_append_file, modstate_append_file_full, modstate_file, module_must_hide_this_symbol_sptr, NOSYM, NULL, rw_host_state(), sem, sptr, and stb.
Referenced by mod_init().
restore_scope_level()
void restore_scope_level (void)
Restore the scope that was saved by save_scope_level()
Definition at line 361 of file scopestack.c.
References count_scope_saved, curr_scope(), STB::curr_scope, DBGBIT, dumpscope(), gbl, interr(), push_scope(), saved_scope_stack, sem, SCOPESTACK::sptr, stb, and SEM::which_pass.
Referenced by do_nested_uses(), and import_module().
rewrite_acl()
ACL * rewrite_acl (ACL * aclp, DTYPE dtype, int parent_acltype)
Definition at line 4880 of file semutil2.c.
References AC_ACONST, AC_AST, AC_EXPR, AC_IDO, AC_IEXPR, AC_REPEAT, AC_SCONST, AC_TYPEINIT, ADD_NUMELM, ast, _acl::ast, construct_acl_from_ast(), DDTG, SEM::dinit_error, _acl::doinfo, DTY, _acl::dtype, dtype, errsev(), GET_ACL, get_doinfo(), _acl::id, DOINFO::index_var, interr(), _acl::is_const, is_zero_size_typedef(), mk_id(), mkexpr(), _acl::next, next_member(), no_data_components(), NULL, _acl::repeatc, rewrite_acl(), S_ACONST, S_CONST, S_EXPR, S_IDENT, sem, sptr, _acl::sptr, SST_ACLG, SST_ASTG, SST_IDG, SST_SYMG, _acl::stkp, _acl::subc, TRUE, and _acl::u1.
Referenced by construct_acl_for_sst(), init_sptr_w_acl(), rewrite_acl(), and semant1().
runtime_array()
int runtime_array (int ast)
Return TRUE if the expression at 'ast' is composed of constants and the special symbol 'hpf_np$'. In this case, even though the bound is not a literal constant, it is a runtime constant.
Definition at line 171 of file semutil2.c.
References ast, DBGBIT, FALSE, gbl, runtime_array(), and TRUE.
Referenced by _mk_arrdsc(), and runtime_array().
save_acl()
ACL * save_acl (ACL * oldp)
Definition at line 5145 of file semutil2.c.
References AC_ACONST, AC_AST, AC_CONST, AC_EXPR, AC_ICONST, AC_IDO, AC_IEXPR, AC_REPEAT, AC_SCONST, ACL_SAVE_AREA, _acl::ast, _acl::doinfo, _acl::expr, GET_ACL, get_doinfo(), _acl::id, interr(), AEXPR::lop, _acl::next, NULL, _acl::repeatc, AEXPR::rop, S_ACONST, save_acl(), _acl::size, SST_ACLG, SST_ASTG, SST_IDG, _acl::stkp, _acl::subc, TRUE, and _acl::u1.
Referenced by save_acl(), and semant1().
save_host_state()
void save_host_state (int wherefrom)
Called from semant.c to save the semant, sym, dtype, ast, and other 'state' information from a host routine for internal subprograms, for 'pass 1'. Also, for 'pass 2', save_host_state is called to overwrite the semant state information.
Definition at line 13635 of file semutil2.c.
References astb, STB::dt, errfatal(), STB::firstusym, NULL, rw_host_state(), saved_astavl, saved_dtyavl, saved_symavl, sptr, state_file, stb, and tmpfile().
Referenced by semant1().
save_module_state1()
void save_module_state1 (void)
Called at a CONTAINS clause.
Writes the module information out quickly. It is split into two pieces: the first only writes out the semant information, before semfin() deallocates it, and the second appends everything else, including the module.c tables.
Definition at line 13975 of file semutil2.c.
References errfatal(), modstate_file, NULL, rw_host_state(), and tmpfile().
Referenced by begin_contains().
save_module_state2()
void save_module_state2 (void)
Definition at line 13988 of file semutil2.c.
References astb, STB::dt, SEM::ieee_features, mod_clear_init, modsave_ieee_features, modsaved_astavl, modsaved_dtyavl, modsaved_symavl, modstate_append_file_full, modstate_file, rw_host_state(), sem, and stb.
Referenced by begin_contains().
save_scope_level()
void save_scope_level (void)
Pop the current scope into a save area; restore with restore_scope_level()
Definition at line 341 of file scopestack.c.
References count_scope_saved, curr_scope(), STB::curr_scope, DBGBIT, dumpscope(), gbl, interr(), pop_scope(), saved_scope_stack, sem, SCOPESTACK::sptr, stb, and SEM::which_pass.
Referenced by do_nested_uses(), and import_module().
save_struct_init()
void save_struct_init (ACL * ict)
Definition at line 5597 of file semutil2.c.
References AC_TYPEINIT, BZERO, DTC_DEFAULT, DTC_DEFAULT_CNT, DTC_DEFAULT_HEAD, _acl::id, NEED, rewrite_typeinit_to_sconst(), sptr, and _acl::sptr.
Referenced by build_typedef_init_tree(), getict(), and semant1().
sc_local_passbyvalue()
int sc_local_passbyvalue (int sptr, int func_sptr)
Return true if sptr is an SC_LOCAL and a pass by value parameter of func_sptr.
Definition at line 303 of file semfunc.c.
References aux, AUX::dpdsc_base, i, sptr, and SYMNAME.
Referenced by ref_intrin(), and semant2().
scopestack_init()
void scopestack_init (void)
Initialize the scope stack.
It starts with one frame representing the outer scope, with no associated symbol.
Definition at line 31 of file scopestack.c.
References BZERO, curr_scope(), NEW, SEM::next_unnamed_scope, NULL, scope, SEM::scope_level, SCOPE_OUTER, SEM::scope_size, SEM::scope_stack, sem, and stb.
Referenced by semant_init().
select_gsame()
int select_gsame (int gnr)
Given a generic intrinsic, select the corresponding specific of the same name.
Normally, the selection is performed by just accessing the GSAME field of the generic. When an option to override the meaning of INTEGER (-noi4) is selected, some analysis must be done to select the specific intrinsic whose argument type matches the type implied by the option.
Definition at line 1386 of file semfunc2.c.
References DT_CMPLX, DT_INT, DT_REAL, flg, GSAMEG, FLG::i4, spec, and XBIT.
Referenced by assign_pointer(), and semant1().
select_kind()
DTYPE select_kind (DTYPE dtype, int ty, INT kind_val)
Definition at line 875 of file semutil2.c.
References CNULL, dtype, error(), gbl, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_REAL, and XBIT.
Referenced by do_dot(), get_number(), get_retval_KIND_value(), put_kind_type_param(), ref_pd(), semant1(), and set_kind_result().
sem_check_scope()
int sem_check_scope (int sym, int orig)
Check the current parallel scope of a variable.
Parameters
sym Represents the variable which actually references storage.
orig Identifier to which the sym refers; for entries, orig will be the ST_ENTRY and sym will be its FVAL.
If the current scope is default private, need to ensure that any variables which have not been declared in this scope are declared as private variables. If the current scope is 'none', then need to ensure that the variables were actually declared in this scope.
Note that at this time, ST_UNKNOWN and ST_IDENT symbols should be have been resolved.
Definition at line 2013 of file semsym.c.
References add_assign_firstprivate(), add_no_scope_sptr(), check_parref(), checking_scope, decl_private_sym(), FALSE, gbl, SEM::ignore_default_none, SEM::orph, SCOPESTACK::par_scope, PAR_SCOPE_FIRSTPRIVATE, PAR_SCOPE_NONE, PAR_SCOPE_SHARED, PAR_SCOPE_TASKNODEFAULT, SEM::parallel, refsym(), SCOPESTACK::rgn_scope, s, SEM::scope_level, SEM::scope_stack, sem, sem_check_scope(), SCOPESTACK::sptr, ss, SEM::target, SEM::task, SEM::teams, and TRUE.
Referenced by mklvalue(), ref_entry(), ref_object(), and semant3().
sem_eq_str()
LOGICAL sem_eq_str (int con, const char * pattern)
Return TRUE if fortran character constant is equal to pattern (pattern is always uppercase).
Returns
true if fortran character constant is equal to pattern (pattern is always uppercase)
Definition at line 8210 of file semutil2.c.
Referenced by _selected_char_kind(), and eval_selected_char_kind().
sem_err104()
void sem_err104 (int df, int lineno, const char * str)
Definition at line 14590 of file semutil2.c.
References buff, CNULL, df, DI_ID, di_name, error(), interr(), lineno, and str.
Referenced by end_subprogram_checks(), and sem_err105().
sem_err105()
void sem_err105 (int df)
Definition at line 14606 of file semutil2.c.
References df, DI_ID, di_name, errsev(), gbl, and sem_err104().
Referenced by semant3().
sem_fini()
void sem_fini (void)
Compilation is finished - deallocate storage, close files, etc.
Definition at line 14126 of file semutil2.c.
References SEM::eqv_base, SEM::eqv_ss_base, fclose(), FREE, import_fini(), SEM::non_private_base, NULL, saved_labels, saved_labels_avail, saved_labels_pos, saved_labels_size, sem, state_append_file, and state_file.
Referenced by finish().
sem_import_sym()
void sem_import_sym (int s)
IMPORT symbol from host scope – not to be confused with interf import stuff.
Definition at line 325 of file semsym.c.
References add_symitem(), error(), find_in_host(), gbl, next_scope_kind(), NOSYM, s, scope, SCOPE_NORMAL, sptr, and SYMNAME.
Referenced by semant1().
sem_set_storage_class()
void sem_set_storage_class (int sptr)
Definition at line 14157 of file semutil2.c.
References add_auto_array(), add_auto_char(), add_auto_dealloc(), CNULL, error(), gbl, has_allocattr(), IS_INTRINSIC, RUNTIMEG, sptr, and SYMNAME.
Referenced by chkarg(), find_outer_sym(), get_type_rank(), misc_checks(), mkarg(), mkexpr1(), mklvalue(), mkvarref(), semant2(), semant3(), and semantio().
sem_strcmp()
int sem_strcmp (const char * str, const char * pattern)
Compare str and pattern like strcmp() but ignoring the case of str. pattern is all lower case.
Definition at line 8186 of file semutil2.c.
Referenced by _do_iface(), cancel_type(), clear_iface(), sched_type(), semant1(), and semant2().
semant_init()
void semant_init (int noparse)
Initialize semantic analyzer for new user subprogram unit.
Definition at line 427 of file semant.c.
References SEM::ac_std_range, SEM::accassignc, SEM::accl, SEM::action_type, SEM::alloc_mem_initialize, SEM::alloc_std, SEM::allocs, AOP_UNDEF, SEM::apply, SEM::array_const_level, SEM::ast, ast_init(), SEM::atemps, SEM::atomic, ATOMIC_UNDEF, SEM::auto_dealloc, SEM::auto_finalize, SEM::autoloc, bblock_init(), SEM::blksymnum, SEM::block_scope, change_predefineds(), clean_struct_default_init(), clear_subp_prefix_settings(), SEM::close_pdo, SEM::cnt, SEM::collapse, SEM::collapse_depth, SEM::collapsed_acc_do, SEM::contiguous, craft_intrinsics, cref, SEM::critical, STB::curr_scope, FLG::dclchk, SEM::defined_io_seen, SEM::defined_io_type, DI_ID, DI_LINENO, DI_NEST, SEM::dinit_data, SEM::dinit_error, SEM::dinit_nbr_inits, SEM::doconcurrent_dtype, SEM::doconcurrent_symavl, SEM::doif_base, SEM::doif_depth, SEM::doif_size, SEM::dtemps, SEM::elp_stack, end_of_host, SEM::equal_initializer, SEM::eqv_avail, SEM::eqv_base, EQV_NUMSS, SEM::eqv_size, SEM::eqv_ss_avail, SEM::eqv_ss_base, SEM::eqv_ss_size, SEM::eqvlist, SEM::etmp_list, SEM::expect_acc_do, SEM::expect_cuf_do, SEM::expect_dist_do, SEM::expect_do, SEM::expect_simd_do, SEM::extends, FALSE, SEM::flabels, flg, gbl, SEM::gdtype, SEM::generic_tbp, host_present, FLG::hpf, SEM::hpfdcl, SEM::ieee_features, SEM::iface_avail, SEM::iface_base, SEM::iface_size, SEM::ignore_default_none, SEM::ignore_stmt, import_init(), SEM::in_enum, IN_MODULE, SEM::in_stfunc, SEM::in_struct_constr, init_intrinsic_opr(), SEM::intent_list, SEM::interf_base, SEM::interf_size, SEM::interface, SEM::is_acc, SEM::is_hpf, SEM::itemps, SEM::kind_candidate, SEM::kind_type_param, SEM::len_candidate, SEM::len_type_param, lenspec, SEM::master, SEM::mem_order, MO_UNDEF, mod_init(), SEM::modhost_entry, SEM::modhost_proc, SEM::mpaccatomic, mscall, NEW, SEM::new_param_dt, _seql::next, _accl::next, SEM::nml, SEM::nodes, nomixedstrlen, SEM::non_private_avail, SEM::non_private_base, SEM::non_private_size, SEM::none_implicit, SYMUTL::none_implicit, NOSYM, NULL, SEM::orph, SEM::p_dealloc, SEM::p_dealloc_delete, SEM::parallel, SEM::param_assume_sz, SEM::param_defer_len, SEM::param_offset, SEM::param_struct_constr, SEM::parsing_operator, SEM::pending, SEM::pgphase, PHASE_INIT, SEM::proc_initializer, SEM::psfunc, SEM::ptemps, restore_host_state(), restore_implicit(), SEM::rmw_op, SEM::savall, FLG::save, SEM::save_aconst, save_implicit(), SEM::savloc, SEM::sc, scopestack_init(), SEM::seen, SEM::seen_end_module, seen_implicit, SEM::seen_import, seen_options, seen_parameter, SEM::select_type_seen, sem, SEM::seq_acc_do, SEM::seql, FLG::sequence, SPTR_NULL, SEM::ssa_area, SEM::stats, stb, SEM::stsk_base, SEM::stsk_depth, SEM::stsk_size, subp_prefix, SEM::switch_avl, switch_base, SEM::switch_size, SEM::symmetric, symutl, SEM::target, SEM::task, SEM::tbp_access_stmt, SEM::tbp_arg, SEM::tbp_arg_cnt, SEM::teams, SEM::temps_reset, TRUE, _seql::type, _accl::type, SEM::type_initialize, SEM::type_mode, SEM::type_param_candidate, SEM::type_param_sptr, SEM::typroc_avail, SEM::typroc_base, SEM::typroc_size, SEM::use_etmps, use_init(), SEM::use_seen, SEM::which_pass, WINNT_CALL, WINNT_CREF, WINNT_NOMIXEDSTRLEN, and XBIT.
Referenced by reinit().
semfin()
void semfin (void)
Finalize semantic processing.
Definition at line 319 of file semfin.c.
References FLG::accmp, allocatable_member(), arg, assert, aux, CNULL, conformable(), DBGBIT, df_dinit_end(), do_access(), do_common_blocks(), do_dinit(), do_equiv(), do_nml(), do_save(), do_sequence(), AUX::dpdsc_avl, AUX::dpdsc_base, DTY, DTYG, ENDLINEP, SEM::eqvlist, errlabel(), error(), FALSE, STB::firstosym, fix_args(), fix_class_args(), fixup_reqgs_ident(), SEM::flabels, flg, FUNCLINEG, gbl, FLG::hpf, i, IN_MODULE, in_module, AUX::list, merge_generics(), misc_checks(), mkRteRtnNm(), NOSYM, pop_scope_level(), prepend_func_result_as_first_arg(), push_scope_level(), queue_tbp(), FLG::recursive, ref_entry(), RTE_loc, RU_BDATA, RU_FUNC, RU_PROG, RU_SUBR, SEM::savall, SEM::savloc, SCOPE_NORMAL, sem, FLG::sequence, FLG::smp, sptr, stb, sym_mkfunc_nodesc(), SYMNAME, TBP_COMPLETE_FIN, TRUE, TY_CHAR, TY_DCMPLX, TY_NCHAR, SEM::typroc_avail, SEM::typroc_base, void(), SEM::which_pass, and XBIT.
Referenced by fix_module_common(), and semant1().
semfin_free_memory()
void semfin_free_memory (void)
Deallocate data structures for semantic analysis.
Definition at line 1032 of file semfin.c.
References SEM::doif_base, FREE, freearea(), SEM::iface_base, SEM::interf_base, NULL, SEM::scope_stack, sem, SEM::stsk_base, switch_base, and SEM::typroc_base.
Referenced by semant1().
set_assn()
void set_assn (int sptr)
Definition at line 4707 of file semutil.c.
References err_protected(), gbl, is_protected(), is_used_by_submod(), and sptr.
Referenced by exp_mp_atomic_capture(), exp_mp_atomic_update(), semant3(), and semantio().
set_construct_name()
void set_construct_name (int name)
Definition at line 5682 of file semant3.c.
References construct_name, and name.
Referenced by semant1().
set_internref_stfunc()
void set_internref_stfunc (int ast)
Definition at line 625 of file semsym.c.
References ast, gbl, set_internref_flag(), and sptr.
Referenced by ref_stfunc().
set_modusename()
void set_modusename (int local, int global)
Definition at line 160 of file module.c.
References allocate_refsymbol(), ref_symbol::altname, dbgref_symbol, malloc(), module_altname::next, NULL, ref_symbol::size, module_altname::sptr, stb, SYMNAME, and ref_symbol::symnum.
Referenced by add_use_rename(), and import_symbol().
set_parref_flag()
void set_parref_flag (int sptr, int psptr, int stblk)
Definition at line 9776 of file semsmp.c.
References AD_ADJARR, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_UPAST, AD_ZBASE, DTY, flg, get_static_descriptor(), get_stblk_uplevel_sptr(), i, mp_add_shared_var(), ndim, FLG::omptarget, parref_bnd(), sptr, and ST_ISVAR.
Referenced by add_assign_firstprivate(), add_private_allocatable(), check_parref(), do_dist_schedule(), do_distbegin(), do_lastprivate(), do_reduction(), do_schedule(), get_fmt_array(), mk_firstprivate(), refsym(), restore_clauses(), and set_parref_flag2().
set_parref_flag2()
void set_parref_flag2 (int sptr, int psptr, int std)
set_parref_flag set PARREF flag after semant phase
Parameters
sptr shared symbol - set PARREF field and put in uplevel structure
psptr shared symbol - use it as key to search for uplevel
std statement where the reference of sptr occurs
Definition at line 9851 of file semsmp.c.
References ast, STB::firstusym, i, llmp_get_uplevel(), mp_add_shared_var(), set_parref_flag(), sptr, ST_ISVAR, stb, std, STD_AST, STD_PREV, LLUplevel::vals, and LLUplevel::vals_count.
Referenced by add_class_arg_descr_arg(), change_mk_id(), make_simple_template_from_ast(), prepare_for_astout(), rewrite_all_shape(), transform_call(), and transform_wrapup().
set_pass_objects()
void set_pass_objects (int pos, int pod)
Set position of type-bound procedure passed object location.
Definition at line 89 of file semfunc2.c.
References pass_object_dummy, pass_position, and pos.
Referenced by func_call2(), and subr_call2().
set_private_encl()
void set_private_encl (int old, int new)
Definition at line 9936 of file semsmp.c.
References AD_ADJARR, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_UPAST, AD_ZBASE, DTY, i, ndim, scope, and set_private_bnd_encl().
Referenced by decl_private_sym().
set_private_taskflag()
void set_private_taskflag (int sptr)
Definition at line 9982 of file semsmp.c.
References RUNTIMEG, sem, sptr, and SEM::task.
Referenced by decl_private_sym().
size_of_array()
ISZ_T size_of_array (DTYPE dtype)
Check if array has zero size.
It expects lowerbound and upper bound to be constant asts. Don't use NUM_ELEM because it could return 1 as number of element, If dtype is zero, it loosely check aggregate size which must be done after chk_constructor/(2).
Definition at line 1399 of file semutil2.c.
References acs, AD_DPTR, AD_LWAST, AD_NUMDIM, AD_UPAST, ad_val_of(), _ACS::aggr_cnt, assert, astb, ASTB::bnd, d, DEFAULT_DIM_SIZE, DTY, i, interr(), ISZ_T, _ACS::scalar_cnt, size, sym_of_ast(), and ASTB::zero.
Referenced by dinit_data(), and semant1().
sym_in_scope()
int sym_in_scope (int first, OVCLASS overloadclass, int * paliassym, int * plevel, int multiple_use_error)
Look for a symbol with same name as first and in an active scope.
Parameters
first the symbol to match by name
overloadclass 0 or the value of stb.ovclass to match
paliassym return the symbol the result is an alias of
plevel return the scope nest at which symbol was found
multiple_use_error if true, report error if name is USE-associated from two different modules
Returns
symbol (or alias) if found, else 0
Definition at line 96 of file semsym.c.
References SEM::doif_depth, error(), find_explicit_interface(), first, first_hash(), gbl, get_scope_level(), is_except_in_scope(), IS_TBP, is_used_by_submod(), isLocalPrivate(), isSameNameGenericOrProcOrModproc(), msg(), next_scope(), next_scope_kind_sptr(), NULL, STB::ovclass, scope, SCOPE_BLOCK, SCOPE_INTERFACE, SCOPE_NORMAL, SEM::scope_stack, SCOPE_USE, sem, sptr, stb, sym_in_sym_list(), SYMNAME, TRUE, and SEM::which_pass.
Referenced by declref(), declsym(), do_access(), enforce_denorm(), getocsym(), refocsym(), refsym(), refsym_inscope(), resolveBind(), and semant1().
sym_skip_construct()
int sym_skip_construct (int first)
Definition at line 1516 of file semsym.c.
References first, NOSYM, and sptr.
Referenced by mkvarref(), and semant2().
test_private_dtype()
int test_private_dtype (int dtype)
Check whether the dtype is inside a valid scope.
Definition at line 2783 of file semant2.c.
References STB::curr_scope, DTY, NOSYM, scope, and stb.
Referenced by add_iolptrs(), has_private(), semant2(), and semant3().
test_scope()
int test_scope (int sptr)
Definition at line 440 of file semsym.c.
References gbl, get_scope(), is_except_in_scope(), scope, SEM::scope_level, SCOPE_USE, sem, sptr, sym_in_sym_list(), SYMI_NEXT, and SYMI_SPTR.
Referenced by _do_iface(), check_defined_io2(), cmp_interfaces(), find_best_generic(), find_operator(), fix_proc_ptr_dummy_args(), get_sst_named_whole_variable(), get_tbp_argno(), merge_generics(), mkexpr1(), semant1(), and subr_call2().
use_init()
void use_init (void)
Definition at line 213 of file module.c.
References reinit_refsymbol(), stb, and usedb.
Referenced by semant_init().
use_opt_atomic()
LOGICAL use_opt_atomic (int d)
Decide to use optimized atomic usage.
Definition at line 10308 of file semsmp.c.
References d, and OPT_OMP_ATOMIC.
Referenced by semant1(), semant3(), and semsmp().
xref()
void xref (void)
Definition at line 279 of file xref.c.
References baseptr, fclose(), fd, i, index, interr(), memitem::link, mergesrt(), NEW, NULL, printxref(), sptr, stb, xrefcnt, XREFLKG, and XREFLKP.
Referenced by main(), and process_input().
xrefinit()
void xrefinit (void)
Definition at line 35 of file xref.c.
References baseptr, errfatal(), fd, NULL, tmpfile(), and xrefcnt.
Referenced by reinit().
xrefput()
void xrefput (int symptr, int usage)
Write one reference record to Reference File:
Definition at line 49 of file xref.c.
References fd, gbl, interr(), memitem::lineno, memitem::link, memitem::use, and xrefcnt.
Referenced by chk_fmtid(), declobject(), declref(), declsym(), fixup_param_vars(), gen_dinit(), getocsym(), mkmember(), ptrsubr_call(), ref_based_object_sc(), refsym(), refsym_inscope(), semant1(), semant3(), and subr_call2().
Variable Documentation
cast_types
INT cast_types[NTYPE][2][2] extern
We only allow casting to and from TY_WORD and TY_DWORD. Therefore, you index into the following table as follows cast_types[dtype][{DT_WORD or DT_DWORD} - 1][0 for from or 1 for to] Entries are:
0 - casting unnecessary
1 - casting necessary
-1 - casting not allowed
We only allow casting to and from TY_WORD and TY_DWORD. Therefore, you index into the following table as follows cast_types[dtype][{DT_WORD or DT_DWORD} - 1][0 for from or 1 for to]
Definition at line 44 of file fenddf.c.
sem
SEM sem extern
Definition at line 23 of file fenddf.c.