flang: dtypeutl.h File Reference
flang2/flang2exe/dtypeutl.h File Reference
#include "gbldefs.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include <stdio.h>
Functions
ISZ_T ad_val_of (int sym)
...
ISZ_T extent_of (DTYPE dtype)
...
ISZ_T get_bnd_cval (int con)
Given a constant symbol, return its numerical value.
ISZ_T size_of (DTYPE dtype)
...
ISZ_T size_of_sym (SPTR sym)
...
ISZ_T zsize_of (DTYPE dtype)
...
bool cmpat_func (DTYPE d1, DTYPE d2)
Return true if the data types for two functions are compatible.
bool is_array_dtype (DTYPE dtype)
...
bool is_empty_typedef (DTYPE dtype)
Check for special case of empty typedef which has a size of 0 but one member of type DT_NONE to indicate that the type is empty and not incomplete, a forward reference, etc.
bool is_zero_size_typedef (DTYPE dtype)
Check for special case of zero-size typedef which may nest have zero-size typedef compnents or zero-size array compnents.
bool no_data_components (DTYPE dtype)
...
bool is_overlap_cmblk_var (int sptr1, int sptr2)
DTYPE array_element_dtype (DTYPE dtype)
if array datatype, returns the element dtype, else returns dtype
DTYPE get_array_dtype (int numdim, DTYPE eltype)
...
DTYPE get_type (int n, TY_KIND v1, int v2)
...
DTYPE get_vector_dtype (DTYPE dtype, int n)
...
int alignment (DTYPE dtype)
...
int alignment_sym (SPTR sym)
...
int align_of (DTYPE dtype)
Support the alignof operator.
int align_unconstrained (DTYPE dtype)
...
int dlen (TY_KIND dty)
Return the length.
int dmp_dent (DTYPE dtypeind)
...
int fval_of (DTYPE dtype)
Get FVAL field of a data type.
int get_bnd_con (ISZ_T v)
Create a constant sym entry which reflects the type of an array bound/extent.
int kanji_char (unsigned char *p, int len, int *bytes)
Extract necessary bytes from character string in order to return integer (16-bit) representation of one kanji char.
int kanji_len (unsigned char *p, int len)
Get number of kanji characters.
int kanji_prefix (unsigned char *p, int newlen, int len)
Get number of bytes needed for kanji characters in string prefix.
int Scale_Of (DTYPE dtype, ISZ_T *size)
Compute the size of a data type.
int scale_of (DTYPE dtype, INT *size)
...
void dmp_dtype (void)
...
void getdtype (DTYPE dtype, char *ptr)
Put into the character array pointed to by ptr, the print representation of dtype.
void init_chartab (void)
...
void Restore_Chartab (FILE *fil)
...
void Save_Chartab (FILE *fil)
...
int align_bytes2mask (int bytes)
int align_bytes2power (int bytes)
int align_mask2bytes (int mask)
int align_mask2power (int mask)
int align_power2bytes (int power)
int align_power2mask (int power)
Function Documentation
ad_val_of()
ISZ_T ad_val_of (int sym)
...
Definition at line 1182 of file dtypeutl.c.
References CONVAL2G, get_isz_cval(), INT64_2_ISZ, ISZ_T, num, and XBIT.
Referenced by _size_of(), compute_size_expr(), create_array_ref(), create_array_subscr(), dinit_subs(), dinit_varref(), dtype_with_shape(), eval_const_array_section(), eval_max(), eval_min(), eval_minval_or_maxval(), eval_reshape(), eval_sub_index(), eval_transfer(), extent_of(), fill_adjustable_array_dtype(), fill_argt_with_alnd(), fill_fixed_array_dtype(), finish_array(), fixup_param_vars(), get_dim_size(), get_ftn_cbind_lltype(), get_shape_arraydtype(), init_sdsc_bounds(), init_subrange_bound(), init_subrange_bound_pre11(), inlarr(), lldbg_emit_type(), make_lltype_from_sptr(), mk_extent(), mk_extent_expr(), mk_shared_extent(), mkarglist(), mkeffadr(), put_adjarr_bounds(), semant1(), should_preserve_param(), size_ast(), size_ast_of(), size_of_array(), small_shape(), stride_one(), and trav_struct().
align_bytes2mask()
int align_bytes2mask (int bytes)
Definition at line 431 of file dtypeutl.cpp.
align_bytes2power()
int align_bytes2power (int bytes)
Definition at line 437 of file dtypeutl.cpp.
Referenced by align_mask2power(), and make_arg_tmp().
align_mask2bytes()
int align_mask2bytes (int mask)
Definition at line 449 of file dtypeutl.cpp.
align_mask2power()
int align_mask2power (int mask)
Definition at line 455 of file dtypeutl.cpp.
References align_bytes2power().
align_of()
int align_of (DTYPE dtype)
Support the alignof operator.
Parameters
dtype
Definition at line 566 of file dtypeutl.cpp.
References alignment().
Referenced by align_of_var(), gen_arg_operand(), make_arg_tmp(), and make_stmt().
align_power2bytes()
int align_power2bytes (int power)
Definition at line 461 of file dtypeutl.cpp.
align_power2mask()
int align_power2mask (int power)
Definition at line 467 of file dtypeutl.cpp.
align_unconstrained()
int align_unconstrained (DTYPE dtype)
...
Align on the most strict boundary for a data type – used whenever we want to align unconstrained (top-level) objects such as simple local, static, and external variables. The alignment of struct of union variables is just the most strict alignment determined by alignment() of its members. The alignment of arrays is just the aligmnent of required for its element type.
Definition at line 547 of file dtypeutl.cpp.
References a, alignment(), and constrained.
Referenced by assn_static_off(), assn_stkoff(), max_align(), and sym_is_refd().
alignment()
int alignment (DTYPE dtype)
...
Definition at line 1213 of file dtypeutl.c.
alignment_sym()
int alignment_sym (SPTR sym)
...
Definition at line 558 of file dtypeutl.cpp.
References alignment(), and TY_DBLE.
array_element_dtype()
DTYPE array_element_dtype (DTYPE dtype)
if array datatype, returns the element dtype, else returns dtype
Definition at line 4108 of file dtypeutl.c.
References DTY, DTySeqTyElement, and is_array_dtype().
Referenced by allocate_lhs_if_needed(), build_array_ref(), check_alloc_ptr_type(), construct_association(), eval_minval_or_maxval(), gen_type_initialize_for_sym(), get_dtype_init_template(), get_struct_dtype_field(), init_allocatable_typedef_components(), init_derived_type(), initFinalSub(), inline_RTE_set_type(), instantiate_interface(), is_container_dtype(), is_dtype_runtime_length_char(), is_dtype_unlimited_polymorphic(), is_empty_typedef(), is_unresolved_parameterized_dtype(), lower_put_datatype(), lower_use_datatype(), needs_type_in_descr(), no_data_components_recursive(), search_type_members(), set_type_in_descriptor(), transform_call(), and valid_assign_pointer_types().
cmpat_func()
bool cmpat_func (DTYPE d1, DTYPE d2)
Return true if the data types for two functions are compatible.
Two functions are compatible if a single local variable can be used to hold their return values and therefore implying that the same return mechanism can be used for the functions.
Definition at line 1442 of file dtypeutl.c.
References assert, DTY, ERR_Severe, and TRUE.
dlen()
int dlen (TY_KIND dty)
Return the length.
Parameters
dty Length, in stb.dt_base words, of each type of datatype entry
Return the length.
Definition at line 368 of file dtypeutl.cpp.
References TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
dmp_dent()
int dmp_dent (DTYPE dtypeind)
...
Definition at line 2903 of file dtypeutl.c.
References _dmp_dent(), FILE, gbl, NULL, and outfile.
Referenced by dmp_dtype(), and dumpdtype().
dmp_dtype()
void dmp_dtype (void)
...
Definition at line 2709 of file dtypeutl.c.
References dmp_dent(), STB::dt, gbl, i, and stb.
Referenced by dbg_dump(), import_inline(), init(), lower(), process_input(), and upper().
extent_of()
ISZ_T extent_of (DTYPE dtype)
...
Compute total number of elements in this array - if a dimension is not known, estimate. We assume that we already know that dtype is an array reference (either an array or a pointer to an array)
Definition at line 1071 of file dtypeutl.c.
References AD_DPTR, AD_LWBD, AD_NUMDIM, AD_NUMELM, AD_UPBD, ad_val_of(), assert, CONVAL2G, d, DEFAULT_DIM_SIZE, STB::dt, DTY, DTyArrayDesc, DTySeqTyElement, ERR_Informational, ERR_Severe, i, STB::i0, interr(), ISZ_T, size, stb, and sym_of_ast().
Referenced by chkstruct(), dinit_varref(), dinits(), exp_smp(), get_llvm_name(), getsname(), layout_struct_body(), llassem_get_objtodbg_list(), and tk_match_arg().
fval_of()
int fval_of (DTYPE dtype)
Get FVAL field of a data type.
Returns
0 if reg, 1 if mem.
Get FVAL field of a data type.
Definition at line 3040 of file dtypeutl.c.
References assert, DTY, DTyValidRange, ERR_Severe, and get_ty_kind().
get_array_dtype()
DTYPE get_array_dtype (int numdim, DTYPE eltype)
...
...
Parameters
numdim number of dimensions
eltype data type of the array element
The layout of an array descriptor is:
    int    numdim;  --+
    int    zbase;     |
    UINT16 *ilmp;     |
    char   defer;     +-- 4 ints (fixed part)
    char   adjarr;    |
    char   assumsz;   |
    char   pad;     --+
    struct {
        int mlpyr;  --+
        int lwbd;     |
        int upbd;     +-- 6 ints (variable part)
        int lwast;    |
        int upast;    |
        int exntnast;-+
    } b[numdim];
    int    numelm;  --+-- 1 int
Any change in the size of the structure requires a change to one or both of the macros _FP and _VP. Also the size assertion in symtab.c needs to be changed.
Definition at line 3159 of file dtypeutl.c.
References get_aux_arrdsc(), and get_type().
Referenced by _mk_arrdsc(), add_class_arg_descr_arg(), add_equivalence(), add_padding(), ast_init(), ast_rewrite(), binop(), construct_association(), create_threadprivate_dtype(), declare_type(), dtype_with_shape(), finish_args(), fix_dtype(), gen_bnd_assn(), gen_dtio_args(), gen_dtsfmt_args(), gen_vlist(), get_csect_sym(), get_semaphore(), hlv_getvsym(), import(), inline_small_matmul(), lower_do_stmt(), lower_linearized(), lower_namelist_plists(), lower_prepare_symbols(), makeCopyprivArray(), mkarglist(), promote_assumsz_arg(), read_datatype(), read_symbol(), ref_pd(), replace_arg(), rewrite_func_ast(), sym_get_array(), sym_get_formal(), and sym_get_sdescr().
get_bnd_con()
int get_bnd_con (ISZ_T v)
Create a constant sym entry which reflects the type of an array bound/extent.
Definition at line 1199 of file dtypeutl.c.
References DT_INT, getcon(), ISZ_2_INT64, num, and XBIT.
Referenced by mk_swlist().
get_bnd_cval()
ISZ_T get_bnd_cval (int con)
Given a constant symbol, return its numerical value.
Definition at line 935 of file dtypeutl.cpp.
References assert, CONVAL2G, DT_ISINT, ERR_unused, INT64_2_ISZ, and ISZ_T.
Referenced by ll_convert_array_dtype().
get_type()
DTYPE get_type (int n, TY_KIND v1, int v2)
...
Find or allocate a slot in dtype array for the new datatype. For strings, check if the data type is already present.
Parameters
n number of datatype entries we want to occupy
v1 data type
v2 second value, meaning depends on data type, for strings it is the length, for pointers - target type, etc
Definition at line 1385 of file dtypeutl.c.
References astb, chartabavail, chartabbase, CHARTABSIZE, chartabsize, STB::dt, DTY, DTyCharLength, chartab::dtype, DTySet, DTySetFst, FALSE, i, ASTB::i1, if(), interr(), j, k, n, NEED, chartab::next, stb, STG_NEXT_SIZE, TY_CHAR, and TY_NCHAR.
Referenced by _repeat(), _trim(), add_padding(), adjust_ch_length(), alloc_char_temp(), binop(), casttyp(), cg_get_type(), ch_substring(), chk_constructor(), chksubstr(), cngcon(), cngtyp2(), dinit_data(), dinit_intr_call(), dinit_val(), dup_array_dtype(), eval_init_op(), eval_trim(), fill_links_symbol(), fill_midnum(), fix_character_length(), fix_dtype(), gen_char_result(), get_array_dtype(), get_ftn_hollerith_type(), get_parameterized_dt(), get_unl_poly_sym(), get_vector_dtype(), getchartmp(), getstring(), import(), lower_add_pghpf_commons(), lower_linearized(), lower_set_craypointer(), mk_swlist(), mod_type(), put_kind_type_param(), read_datatype(), reduc_rank_dtype(), ref_pd(), rewrite_allocatable_assignment(), rewrite_sub_args(), semant1(), semant2(), set_string_type_from_init(), setup_procedure_sym(), widenProcessDirectLoad(), and widenProcessIndirectLoad().
get_vector_dtype()
DTYPE get_vector_dtype (DTYPE dtype, int n)
...
Definition at line 756 of file dtypeutl.cpp.
References aux, DTY, DTySetVecLength, get_type(), n, and AUX::vtypes.
Referenced by gen_binary_expr(), gen_llvm_expr(), gen_llvm_vsincos_call(), gen_resized_vect(), gen_scalar_to_vector_helper(), make_vtype(), and vect_math().
getdtype()
void getdtype (DTYPE dtype, char * ptr)
Put into the character array pointed to by ptr, the print representation of dtype.
Definition at line 2559 of file dtypeutl.c.
References AD_ADJARR, AD_ASSUMRANK, AD_ASSUMSHP, AD_ASSUMSZ, AD_DEFER, AD_DPTR, AD_LWAST, AD_LWBD, AD_NOBOUNDS, AD_NUMDIM, AD_UPAST, AD_UPBD, assert, STB::dt, DTY, DTyAlgTyTag, DTyArrayDesc, DTyCharLength, DTySeqTyElement, DTyVecLength, ERR_Informational, ERR_Severe, getast(), getprint(), i, interr(), NOSYM, p, stb, strlen(), SYMNAME, TY_CHAR, TY_NCHAR, and STB::tynames.
Referenced by _dmp_dent(), _dump_one_ast(), dmp_var(), dsym(), dump_buff(), putdtype(), putentry(), and symdentry().
init_chartab()
void init_chartab (void)
...
Definition at line 1345 of file dtypeutl.c.
References chartabavail, chartabbase, CHARTABSIZE, chartabsize, chartab::dtype, flg, i, NEW, chartab::next, TY_CMPLX, TY_DBLE, FLG::x, and XBIT.
Referenced by sym_init().
is_array_dtype()
bool is_array_dtype (DTYPE dtype)
...
Definition at line 4102 of file dtypeutl.c.
References get_ty_kind().
Referenced by array_element_dtype(), build_array_ref(), check_alloc_ptr_type(), construct_association(), gen_bounds_assignments(), gen_type_initialize_for_sym(), get_ast_bounds(), get_ast_extents(), get_ast_rank(), get_dtype_init_template(), get_struct_dtype_field(), init_allocatable_typedef_components(), init_derived_type(), initFinalSub(), inline_RTE_set_type(), is_array_ast(), is_container_dtype(), is_dtype_runtime_length_char(), is_dtype_unlimited_polymorphic(), is_empty_typedef(), is_unresolved_parameterized_dtype(), is_zero_size_typedef(), lower_put_datatype(), lower_stmt(), lower_use_datatype(), needs_type_in_descr(), no_data_components_recursive(), ptrfunc_call(), search_type_members(), semant3(), set_type_in_descriptor(), and transform_call().
is_empty_typedef()
bool is_empty_typedef (DTYPE dtype)
Check for special case of empty typedef which has a size of 0 but one member of type DT_NONE to indicate that the type is empty and not incomplete, a forward reference, etc.
Check for special case of empty typedef which has a size of 0 but one member of type DT_NONE to indicate that the type is empty and not incomplete, a forward reference, etc.
Definition at line 401 of file dtypeutl.c.
References array_element_dtype(), DTY, DTyAlgTyMember, FALSE, is_array_dtype(), mem(), NOSYM, sptr, and TRUE.
Referenced by cngcon(), dinit_data(), emit_init(), no_data_components_recursive(), process_dtype_struct(), semant1(), and semant2().
is_overlap_cmblk_var()
bool is_overlap_cmblk_var (int sptr1, int sptr2)
Definition at line 1294 of file dtypeutl.cpp.
References getsymbol(), IS_COMMON_VAR, size_of_sym(), and SYMNAME.
Referenced by conflict().
is_zero_size_typedef()
bool is_zero_size_typedef (DTYPE dtype)
Check for special case of zero-size typedef which may nest have zero-size typedef compnents or zero-size array compnents.
Definition at line 429 of file dtypeutl.c.
References DTY, DTyAlgTySize, DTySeqTyElement, FALSE, and is_array_dtype().
Referenced by dinit_data(), dinit_varref(), dinits(), get_struct_from_dsrt2(), process_dsrt(), and rewrite_acl().
kanji_char()
int kanji_char (unsigned char * p, int len, int * bytes)
Extract necessary bytes from character string in order to return integer (16-bit) representation of one kanji char.
Parameters
p the character string
len number of bytes in string p
Returns
number of EUC bytes used up
Parameters
p ptr to EUC string
len number of bytes in p
bytes return number of EUC bytes used up
Definition at line 3091 of file dtypeutl.c.
References len, p, SS2, SS3, and val.
Referenced by const_eval(), const_fold(), eval_ichar(), init_fold_const(), kanji_prefix(), put_kstr(), put_ncharstring_n(), and ref_intrin().
kanji_len()
int kanji_len (unsigned char * p, int len)
Get number of kanji characters.
Parameters
length Length in bytes of character string
Get number of kanji characters.
Parameters
p character string
len length in bytes of p
Definition at line 3063 of file dtypeutl.c.
References count, len, p, SS2, SS3, and val.
Referenced by _trim(), binop(), ch_substring(), cngcon(), get_stmt(), and semant2().
kanji_prefix()
int kanji_prefix (unsigned char * p, int newlen, int len)
Get number of bytes needed for kanji characters in string prefix.
Parameters
p ptr to EUC string
newlen number of kanji chars required from string prefix
len total number of bytes in string
Returns
number of bytes required for newlen chars
Get number of bytes needed for kanji characters in string prefix.
Parameters
p ptr to EUC string
newlen number of kanji chars required from string prefix
len total number of bytes in string
Definition at line 3113 of file dtypeutl.c.
References kanji_char(), len, p, and void().
Referenced by cngcon(), crunch(), and ff_prescan().
no_data_components()
bool no_data_components (DTYPE dtype)
...
Definition at line 500 of file dtypeutl.c.
References is_recursive_dtype(), no_data_components_recursive(), NULL, result, and visit_list_free().
Referenced by _constructf90(), chk_struct_constructor(), construct_acl_for_sst(), dinit_val(), dinit_varref(), get_exttype_default(), get_exttype_struct_constructor(), get_keyword_components(), rewrite_acl(), semant2(), semantio(), and sym_is_refd().
Restore_Chartab()
void Restore_Chartab (FILE * fil)
...
Definition at line 637 of file dtypeutl.cpp.
References chartabavail, chartabbase, CHARTABSIZE, chartabsize, ERR_Fatal, error(), and NEED.
Save_Chartab()
void Save_Chartab (FILE * fil)
...
Definition at line 616 of file dtypeutl.cpp.
References chartabavail, chartabbase, CHARTABSIZE, ERR_Fatal, and error().
scale_of()
int scale_of (DTYPE dtype, INT * size)
...
...
This machine dependent routine computes the size of a data type in terms of two quantities:
size - number of elements in the data type (returned thru size).
scale - number of bytes in each element, expressed as a power of two (the return value of scale_of).
This routine will be used to take advantage of the machines that have the ability to add a scaled expression (multiplied by a power of two) to an address. This is particularly useful for incrementing a pointer variable and array subscripting.
Note that for those machines that do not have this feature, scale_of returns a scale of 0 and size_of for size.
Definition at line 2966 of file dtypeutl.c.
References d, DTY, get_ty_kind(), interr(), ISZ_T, scale, scale_of(), Scale_Of(), size, string_length(), tmp, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by compute_sdsc_subscr(), create_array_subscr(), create_sdsc_subscr(), exp_mac(), get_sdsc_element(), and scale_of().
Scale_Of()
int Scale_Of (DTYPE dtype, ISZ_T * size)
Compute the size of a data type.
Parameters
dtype
size number of elements in the data type [output]
Returns
number of bytes in each element, expressed as a power of two (scale)
This machine dependent routine computes the size of a data type in terms of two quantities: the size and the scale
This routine will be used to take advantage of the machines that have the ability to add a scaled expression (multiplied by a power of two) to an address. This is particularly useful for incrementing a pointer variable and array subscripting.
Note that for those machines that do not have this feature, scale_of returns a scale of 0 and size_of for size.
Definition at line 1111 of file dtypeutl.cpp.
References assert, d, DTY, DTyAlgTySize, DTyArrayDesc, DTyCharLength, DTySeqTyElement, DTySetArrayDesc, DTyValidRange, DTyVecLength, ERR_Severe, interr(), ISZ_T, scale, Scale_Of(), size, tmp, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by compute_sdsc_subscr(), inlarr(), scale_of(), and Scale_Of().
size_of()
ISZ_T size_of (DTYPE dtype)
...
Definition at line 96 of file dtypeutl.c.
References _size_of(), A_OPTYPEG, AD_DEFER, AD_DPTR, AD_NUMELM, astb, CONVAL2G, d, DT_INT, DT_PTR, DTY, errsev(), get_ty_kind(), STB::i0, STB::i1, ASTB::i1, INT64_2_ISZ, interr(), ISZ_T, STB::k0, STB::k1, ASTB::k1, num, size_of(), size_sym, stb, string_length(), sym_of_ast(), sz, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, TY_SLOG, TY_WORD, and XBIT.
Referenced by _exp_smove(), _pgi_element_size(), _put(), _size_of(), add_equivalence(), add_socs(), allocThreadprivate(), arg_is_refd(), build_routine_and_parameter_entries(), casttyp(), cg_llvm_init(), check_cstruct_return(), check_sc(), check_struct(), check_vfp(), chk_evar(), chkcon_to_isz(), classify_common(), classify_int(), cmplx_to_mem(), collapse_assignment(), compute_sdsc_subscr(), const_eval(), convert_cnst(), convert_dtype(), convert_int_to_ptr(), convert_template_instance(), cp_byval_mem_arg(), create_array_subscr(), create_sdsc_subscr(), dinit_data(), dinit_subs(), dinit_varref(), dinits(), do_equiv(), do_reduction(), elem_size_of_ast(), emit_init(), eval_adjustl(), eval_adjustr(), eval_ichar(), eval_index(), eval_init_op(), eval_ishft(), eval_len_trim(), eval_repeat(), eval_scale(), eval_scan(), eval_transfer(), eval_trim(), eval_verify(), exp_ac(), exp_add_copy(), exp_call(), exp_load(), exp_mac(), exp_smp(), exp_store(), gen_acon_expr(), gen_alloca_call_if_necessary(), gen_arg_operand(), gen_base_addr_operand(), gen_derived_io(), gen_llvm_expr(), gen_va_arg(), get_ag(), get_dtype_for_vect_type_nme(), get_isz_cval(), get_string_constant(), get_struct_from_dsrt2(), get_threadprivate_origsize(), getTaskSharedSize(), hostsym_is_refd(), inlarr(), kind_of(), ld_sptr(), ll_abi_classify_arg_dtype(), ll_abi_classify_return_dtype(), ll_abi_classify_va_arg_dtype(), ll_make_kmpc_atomic_read(), ll_make_kmpc_atomic_write(), ll_make_kmpc_dispatch_fini(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), ll_make_kmpc_for_static_init_args(), ll_make_kmpc_struct_type(), ll_make_kmpc_task_arg(), ll_make_uplevel_type(), llvm_fc_type(), loadUplevelArgsForRegion(), lower_add_pghpf_commons(), lower_data_stmts(), lower_do_stmt(), lower_init_sym(), lower_numelm(), lower_omp_target_tripcount(), lower_stmt(), make_sec_from_ast_chk(), make_stmt(), make_uplevel_arg_struct(), merge(), mkeffadr(), pp_entries(), pp_entries_mixedstrlen(), pp_params(), pp_params_mixedstrlen(), print_ast(), put_adjarr_bounds(), read_init(), ref_intrin(), ref_pd(), ref_threadprivate_var(), rewrite_func_ast(), SCALAR_SIZE(), sem_eq_str(), semant1(), semantio(), semsmp(), set_common_size(), set_initial_s1(), size_of(), size_of_allocatable(), size_of_dtype(), size_of_sym(), size_of_var(), smallest_dtype(), stackcheck(), sym_is_refd(), transfer_load(), transfer_store(), transform_c_f_pointer(), transform_ptr(), trav_struct(), update_homogeneous(), write_comm(), write_layout_desc(), and write_typedescs().
size_of_sym()
ISZ_T size_of_sym (SPTR sym)
...
Definition at line 350 of file dtypeutl.cpp.
References ERR_Severe, error(), gbl, ISZ_T, NULL, size_of(), size_sym, SYMNAME, and sz.
Referenced by get_ag(), is_overlap_cmblk_var(), llmp_task_add_private(), and max_align().
zsize_of()
ISZ_T zsize_of (DTYPE dtype)
...
Definition at line 340 of file dtypeutl.cpp.
References _size_of(), d, ISZ_T, and nosize_ok.
Referenced by _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_mp_atomic_write(), align_of_var(), amd64_classify(), amd64_coerce(), amd64_update_class(), can_use_rmw(), check_vector_registers(), classify_int(), exp_smp(), gen_call_expr(), gen_call_vminmax_intrinsic(), gen_call_vminmax_neon_intrinsic(), gen_call_vminmax_power_intrinsic(), gen_llvm_expr(), ll_abi_classify_arg_dtype(), ll_abi_classify_return_dtype(), lldbg_emit_type(), lldbg_get_bounds_for_assumed_rank_sdsc(), lldbg_get_bounds_for_sdsc(), lldbg_get_sizeof(), llmp_task_add_loopvar(), llmp_task_add_private(), make_stmt(), msz_from_atomic_dtype(), setTaskloopVars(), and update_homogeneous().