flang: symtab.in.h File Reference
flang1/utils/symtab/symtab.in.h File Reference
symtab.h - symbol tab definitions for Fortran
#include <universal.h>
#include "symacc.h"
Classes
struct ADSC
struct ENTRY
struct NMLDSC
struct SYMI
struct DVL
struct AUX
struct SWEL
Macros
#define ST_ISVAR(s) (((s) >= ST_VAR && (s) <= ST_UNION))
#define IS_PROC(st) ((st) >= ST_ENTRY && (st) <= ST_PD)
#define DT_MAX_43 43
#define DT_INT stb.dt_int
#define DT_REAL stb.dt_real
#define DT_CMPLX stb.dt_cmplx
#define DT_LOG stb.dt_log
#define DT_DBLE stb.dt_dble
#define DT_DCMPLX stb.dt_dcmplx
#define DT_PTR stb.dt_ptr
#define DT_FLOAT DT_REAL4
#define TY_FLOAT TY_REAL
#define DT_CPTR DT_ADDR
#define DTY(d) (stb.dt.stg_base[d])
#define DDTG(dt) (DTY(dt) == TY_ARRAY ? DTY(dt+1) : dt)
#define DTYG(dt) (DTY(dt) == TY_ARRAY ? DTY(DTY(dt+1)) : DTY(dt))
#define DT_ISCHAR(dt) (dttypes[DTY(dt)]&(_TY_CHAR|_TY_NCHAR))
#define DT_ISINT(dt) (dttypes[DTY(dt)]&_TY_INT)
#define DT_ISREAL(dt) (dttypes[DTY(dt)]&_TY_REAL)
#define DT_ISCMPLX(dt) (dttypes[DTY(dt)]&_TY_CMPLX)
#define DT_ISNUMERIC(dt) (dttypes[DTY(dt)]&(_TY_INT|_TY_REAL|_TY_CMPLX))
#define DT_ISBASIC(dt) (dttypes[DTY(dt)]&_TY_BASIC)
#define DT_ISUNSIGNED(dt) (dttypes[DTY(dt)]&_TY_UNSIGNED)
#define DT_ISSCALAR(dt) (dttypes[DTY(dt)]&_TY_SCALAR)
#define DT_ISVEC(dt) (dttypes[DTY(dt)]&_TY_VEC)
#define DT_ISLOG(dt) (dttypes[DTY(dt)]&_TY_LOG)
#define DT_ISWORD(dt) (dttypes[DTY(dt)]&_TY_WORD)
#define DT_ISDWORD(dt) (dttypes[DTY(dt)]&_TY_DWORD)
#define DT_ISINT_ARR(dt) (DTY(dt)==TY_ARRAY && DT_ISINT(DTY(dt+1)))
#define DT_ISREAL_ARR(dt) (DTY(dt)==TY_ARRAY && DT_ISREAL(DTY(dt+1)))
#define DT_ISCMPLX_ARR(dt) (DTY(dt)==TY_ARRAY && DT_ISCMPLX(DTY(dt+1)))
#define DT_ISNUMERIC_ARR(dt) (DTY(dt)==TY_ARRAY && DT_ISNUMERIC(DTY(dt+1)))
#define DT_ISLOG_ARR(dt) (DTY(dt)==TY_ARRAY && DT_ISLOG(DTY(dt+1)))
#define TY_ISCHAR(t) (dttypes[t]&(_TY_CHAR|_TY_NCHAR))
#define TY_ISINT(t) (dttypes[t]&_TY_INT)
#define TY_ISREAL(t) (dttypes[t]&_TY_REAL)
#define TY_ISCMPLX(t) (dttypes[t]&_TY_CMPLX)
#define TY_ISNUMERIC(t) (dttypes[t]&(_TY_INT|_TY_REAL|_TY_CMPLX))
#define TY_ISBASIC(t) (dttypes[t]&_TY_BASIC)
#define TY_ISUNSIGNED(t) (dttypes[t]&_TY_UNSIGNED)
#define TY_ISSCALAR(t) (dttypes[t]&_TY_SCALAR)
#define TY_ISLOG(t) (dttypes[t]&_TY_LOG)
#define TY_ISVEC(t) (dttypes[t]&_TY_VEC)
#define TY_ISWORD(t) (dttypes[t]&_TY_WORD)
#define TY_ISDWORD(t) (dttypes[t]&_TY_DWORD)
#define IS_CHAR_TYPE(t) (TY_ISCHAR(t))
#define ALIGN(addr, a) ((addr + a) & ~(a))
#define ALIGN_AUTO(addr, a) ((addr) & ~(a))
#define SC_AUTO SC_LOCAL
#define SC_ISCMBLK(p) (p == SC_CMBLK)
#define CUDA_HOST 0x01
#define CUDA_DEVICE 0x02
#define CUDA_GLOBAL 0x04
#define CUDA_BUILTIN 0x08
#define CUDA_GRID 0x10
#define INTENT_IN 0x1
#define INTENT_OUT 0x2
#define INTENT_INOUT 0x3
#define INTENT_DFLT 0x0
#define IGNORE_T 0x1
#define IGNORE_K 0x2
#define IGNORE_R 0x4
#define IGNORE_D 0x8
#define IGNORE_M 0x20
#define IGNORE_C 0x40
#define IGNORE_TKR_ALL 0x3f
#define IGNORE_TKR_ALL0 0x1f /* old value of IGNORE_TKR_ALL */
#define DLL_NONE 0x0
#define DLL_EXPORT 0x1
#define DLL_IMPORT 0x2
#define PRESCRIPTIVE 0
#define DESCRIPTIVE 1
#define TRANSCRIPTIVE 2
#define check_SPTR(v) (v)
#define check_DTYPE(v) (v)
#define check_INT(v) (v)
#define IS_TBP(func) (VTOFFG(func) && TBPLNKG(func))
#define FORALLNDXG(s) DOVARG(s)
#define FORALLNDXP(s, v) DOVARP(s,v)
#define ACONOFFG(s) ((stb.stg_base)[s].w14)
#define ACONOFFP(s, v) ((stb.stg_base)[s].w14 = (v))
#define INTENTG(s) b3G(s)
#define INTENTP(s, v) b3P(s,v)
#define DLLG(s) b3G(s)
#define DLLP(s, v) b3P(s,v)
#define PDALN_EXPLICIT_0 0xf
#define PDALNG(s) (b4G(s) == PDALN_EXPLICIT_0 ? 0 : b4G(s))
#define PDALNP(s, v) b4P(s, (v) == 0 ? PDALN_EXPLICIT_0 : (v))
#define PDALN_IS_DEFAULT(s) (b4G(s) == 0)
#define CUDAG(s) b4G(s)
#define CUDAP(s, v) b4P(s,v)
#define NEWDSCG(s) ((stb.stg_base)[s].w10)
#define NEWDSCP(s, v) ((stb.stg_base)[s].w10 = (v))
#define ARGINFOG(s) ((stb.stg_base)[s].w16)
#define ARGINFOP(s, v) ((stb.stg_base)[s].w16 = (v))
#define XREFLKG(s) ((stb.stg_base)[s].w16)
#define XREFLKP(s, v) ((stb.stg_base)[s].w16 = (v))
#define SYMNAME(p) (stb.n_base + NMPTRG(p))
#define SYMNAMEG(p, buff, len) len = NMLENG(p); strncpy(buff,SYMNAME(p),len)
#define LOCAL_SYMNAME(p) local_sname(SYMNAME(p))
#define RFCNTI(s) (++RFCNTG(s))
#define RFCNTD(s) (--RFCNTG(s))
#define KWDARGSTR(p) intrinsic_kwd[KWDARGG(p)]
#define NOSYM 1
#define IS_TLS(s) (TLSG(s) || ETLSG(s))
#define IS_THREAD_TLS(s) (THREADG(s) && IS_TLS(s))
#define IS_THREAD_TP(s) (THREADG(s) && (!IS_TLS(s)))
#define CMPLXFUNC_C XBIT(49, 0x40000000)
#define AD_DPTR(dtype) ((ADSC *)(aux.arrdsc_base+DTY((dtype)+2)))
#define AD_PTR(sptr) ((ADSC *) (aux.arrdsc_base + DTY(DTYPEG(sptr)+2)))
#define AD_NUMDIM(p) ((p)->numdim)
#define AD_DEFER(p) ((p)->defer)
#define AD_ASSUMRANK(p) ((p)->assumrank)
#define AD_ASSUMSHP(p) ((p)->assumshp)
#define AD_ADJARR(p) ((p)->adjarr)
#define AD_ASSUMSZ(p) ((p)->assumsz)
#define AD_NOBOUNDS(p) ((p)->nobounds)
#define AD_ZBASE(p) ((p)->zbase)
#define AD_MLPYR(p, i) ((p)->b[i].mlpyr)
#define AD_LWBD(p, i) ((p)->b[i].lwbd)
#define AD_UPBD(p, i) ((p)->b[i].upbd)
#define AD_LWAST(p, i) ((p)->b[i].lwast)
#define AD_UPAST(p, i) ((p)->b[i].upast)
#define AD_EXTNTAST(p, i) ((p)->b[i].extntast)
#define AD_NUMELM(p) ((p)->b[AD_NUMDIM(p)].mlpyr)
#define ADD_NUMDIM(dtyp) AD_NUMDIM(AD_DPTR(dtyp))
#define ADD_DEFER(dtyp) AD_DEFER(AD_DPTR(dtyp))
#define ADD_ASSUMRANK(dtyp) AD_ASSUMRANK(AD_DPTR(dtyp))
#define ADD_ASSUMSHP(dtyp) AD_ASSUMSHP(AD_DPTR(dtyp))
#define ADD_ADJARR(dtyp) AD_ADJARR(AD_DPTR(dtyp))
#define ADD_ASSUMSZ(dtyp) AD_ASSUMSZ(AD_DPTR(dtyp))
#define ADD_NOBOUNDS(dtyp) AD_NOBOUNDS(AD_DPTR(dtyp))
#define ADD_ZBASE(dtyp) AD_ZBASE(AD_DPTR(dtyp))
#define ADD_MLPYR(dtyp, i) AD_MLPYR(AD_DPTR(dtyp), i)
#define ADD_LWBD(dtyp, i) AD_LWBD(AD_DPTR(dtyp), i)
#define ADD_UPBD(dtyp, i) AD_UPBD(AD_DPTR(dtyp), i)
#define ADD_LWAST(dtyp, i) AD_LWAST(AD_DPTR(dtyp), i)
#define ADD_UPAST(dtyp, i) AD_UPAST(AD_DPTR(dtyp), i)
#define ADD_EXTNTAST(dtyp, i) AD_EXTNTAST(AD_DPTR(dtyp), i)
#define ADD_NUMELM(dtyp) AD_NUMELM(AD_DPTR(dtyp))
#define NML_SPTR(i) aux.nml_base[i].sptr
#define NML_NEXT(i) aux.nml_base[i].next
#define NML_LINENO(i) aux.nml_base[i].lineno
#define SYMI_SPTR(i) aux.symi_base[i].sptr
#define SYMI_NEXT(i) aux.symi_base[i].next
#define IMPL_INDEX(uc)
#define DVL_SPTR(i) aux.dvl_base[i].sptr
#define DVL_CONVAL(i) aux.dvl_base[i].conval
#define ALIGNG(sptr) 0
#define DISTG(sptr) 0
#define RUNTIMEG(sptr) 0
#define INHERITG(sptr) 0
Typedefs
typedef enum CMP_INTERFACE_FLAGS cmp_interface_flags
flag defintions for cmp_interfaces_strict()
Enumerations
enum etls_levels {
ETLS_PROCESS , ETLS_TASK , ETLS_THREAD , ETLS_OMP ,
ETLS_PROCESS , ETLS_TASK , ETLS_THREAD , ETLS_OMP ,
ETLS_NUM_LEVELS
}
enum CMP_INTERFACE_FLAGS {
IGNORE_IFACE_NAMES = 0x0 , CMP_IFACE_NAMES = 0x1 , IGNORE_ARG_NAMES = 0x2 , RELAX_STYPE_CHK = 0x4 ,
CMP_OPTARG = 0x8 , RELAX_INTENT_CHK = 0x10 , RELAX_POINTER_CHK = 0x20 , RELAX_PURE_CHK_1 = 0x40 ,
RELAX_PURE_CHK_2 = 0x80 , CMP_SUBMOD_IFACE = 0x100 , DEFER_IFACE_CHK = 0x200
}
flag defintions for cmp_interfaces_strict()
Functions
void sym_init (void)
Initialize symbol table for new user program unit.
void init_implicit (void)
void implicit_int (int)
void save_implicit (LOGICAL)
void restore_implicit (void)
void hpf_library_stat (int *, int *, int)
SPTR getsym (const char *, int)
Enter symbol with indicated name into symbol table, initialize the new entry.
SPTR getsymbol (const char *)
Enter symbol with indicated name into symbol table, initialize the new entry, and return pointer to it. If there is already such a symbol, just return pointer to the existing symbol table entry.
SPTR getsymf (const char *,...)
SPTR getcon (INT *, DTYPE)
Enter constant of given dtype and value into the symbol table and return pointer to it.
SPTR get_acon (SPTR, ISZ_T)
SPTR get_acon3 (SPTR, ISZ_T, DTYPE)
INT get_int_cval (int)
ISZ_T get_isz_cval (int)
INT sign_extend (INT, int)
Sign extend an integer value of an indicated width (8, 16, 32); value returned is sign extended with respect to the host's int type.
int getstring (const char *, int)
Enter character constant into symbol table and return pointer to it.
int gethollerith (int, int)
void newimplicit (int, int, int)
Change the current settings for implicit variable types and character lengths.
void setimplicit (int)
Assign to the indicated symbol table entry, the current implicit dtype.
const char * parmprint (int)
Return ptr to printable representation of the indicated PARAMETER.
const char * getprint (int)
Return ptr to printable representation of the indicated symbol.
void symdentry (FILE *, int)
void symdmp (FILE *, LOGICAL)
void dmp_socs (int, FILE *)
int getccsym (int, int, SYMTYPE)
int getnewccsym (int, int, int)
int getnewccsymf (int stype, const char *,...)
int getccsym_sc (int, int, int, int)
int getccssym (const char *, int, int)
int getccssym_sc (const char *, int, int, int)
int getcctmp (int, int, int, int)
int getcctmp_sc (int, int, int, int, int)
int insert_sym (int)
int insert_sym_first (int)
int getlab (void)
void pop_sym (int)
remove a symbol from its hash list
SPTR mkfunc (const char *)
Create a function ST item given a name.
SPTR mkfunc_cncall (const char *)
char * mkfunc_name (int, char *)
char * mkfunc_ir8name (int, char *, int)
char * ir8name (char *, int)
const char * mk_coercion_func_name (int)
create a coercion function based on the data type.
int mk_coercion_func (int)
Create a coercion function based on the data type.
int mk_external_var (char *, int)
LOGICAL is_arg_in_entry (int, int)
determine if an argument is an argument to a given entry
int resolve_sym_aliases (int)
LOGICAL is_procedure_ptr (int)
void proc_arginfo (int, int *, int *, int *)
void copy_sym_flags (SPTR, SPTR)
Copy flags from one symbol to another symbol.
void dup_sym (int, struct SYM *)
int insert_dup_sym (int)
int get_align_desc (int, int)
void dump_align (FILE *, int)
int copy_align_desc (int)
int copy_dist_desc (int)
int get_dist_desc (int)
void dump_dist (FILE *, int)
int get_shadow_desc (int)
void dump_shadow (FILE *, int)
char * mangle_name (const char *, const char *)
char * sym_strsave (const char *)
void save_uname (int, INT)
int add_symitem (int, int)
void change_predefineds (int, LOGICAL)
SPTR find_explicit_interface (SPTR s)
SPTR instantiate_interface (SPTR iface)
Instantiate a copy of a separate module subprogram's declared interface as part of the MODULE PROCEDURE's definition (i.e., implement what would have taken place had the subprogram been defined with a MODULE SUBROUTINE or MODULE FUNCTION with a compatible interface).
void convert_2dollar_signs_to_hyphen (char *name)
Convert two dollar signs to a hyphen. Especially used for the submodule *.mod file renaming: ancestor$$submod.mod -> ancestor-submod.mod.
char * getsname (int)
void sym_is_refd (SPTR)
void iso_c_lib_stat (int *, int *, int)
int get_ieee_arith_intrin (const char *)
void symtab_standard (void)
void symtab_nostandard (void)
void newimplicitnone (void)
void reinit_sym (int)
void symtab_fini (void)
int get_len_of_deferchar_ast (int ast)
SPTR get_proc_ptr (SPTR sptr)
get a temporary procedure pointer to a specified procedure.
LOGICAL sym_in_sym_list (int sptr, int symi)
Return TRUE if sptr is in symi list represented by list.
LOGICAL same_sym_list (int list1, int list2)
Return TRUE if these two symi lists have the same sptrs in the same order.
void push_sym (int sptr)
push a symbol onto a hash list
bool cmp_interfaces (int sym1, int sym2, int flag)
Compares two symbols by returning true if they both have equivalent interfaces. Otherwise, return false.
bool compatible_characteristics (int psptr, int psptr2, cmp_interface_flags flag)
Tests the characteristics between two interfaces.
bool cmp_interfaces_strict (SPTR sym1, SPTR sym2, cmp_interface_flags flag)
Same as cmp_interfaces() except we also compare the characteristics as defined in "12.2 Characteristics of procedures" in F2003 Spec.
bool is_used_by_submod (SPTR sym1, SPTR sym2)
Used for check whether sym2 used inside the scope of sym1 is defined in parent modules (SCOPEG(sym2)) and used by inherited submodules ENCLFUNCG(sym1).
Variables
short dttypes [TY_MAX+1]
AUX aux
const char * intrinsic_kwd []
SWEL * switch_base
Detailed Description
symtab.h - symbol tab definitions for Fortran
Definition in file flang1/utils/symtab/symtab.in.h.
Macro Definition Documentation
ACONOFFG
#define ACONOFFG (s) ((stb.stg_base)[s].w14)
Definition at line 154 of file flang1/utils/symtab/symtab.in.h.
ACONOFFP
#define ACONOFFP (s, v) ((stb.stg_base)[s].w14 = (v))
Definition at line 155 of file flang1/utils/symtab/symtab.in.h.
AD_ADJARR
#define AD_ADJARR (p) ((p)->adjarr)
Definition at line 221 of file flang1/utils/symtab/symtab.in.h.
AD_ASSUMRANK
#define AD_ASSUMRANK (p) ((p)->assumrank)
Definition at line 219 of file flang1/utils/symtab/symtab.in.h.
AD_ASSUMSHP
#define AD_ASSUMSHP (p) ((p)->assumshp)
Definition at line 220 of file flang1/utils/symtab/symtab.in.h.
AD_ASSUMSZ
#define AD_ASSUMSZ (p) ((p)->assumsz)
Definition at line 222 of file flang1/utils/symtab/symtab.in.h.
AD_DEFER
#define AD_DEFER (p) ((p)->defer)
Definition at line 218 of file flang1/utils/symtab/symtab.in.h.
AD_DPTR
#define AD_DPTR (dtype) ((ADSC *)(aux.arrdsc_base+DTY((dtype)+2)))
Definition at line 215 of file flang1/utils/symtab/symtab.in.h.
AD_EXTNTAST
#define AD_EXTNTAST (p, i) ((p)->b[i].extntast)
Definition at line 230 of file flang1/utils/symtab/symtab.in.h.
AD_LWAST
#define AD_LWAST (p, i) ((p)->b[i].lwast)
Definition at line 228 of file flang1/utils/symtab/symtab.in.h.
AD_LWBD
#define AD_LWBD (p, i) ((p)->b[i].lwbd)
Definition at line 226 of file flang1/utils/symtab/symtab.in.h.
AD_MLPYR
#define AD_MLPYR (p, i) ((p)->b[i].mlpyr)
Definition at line 225 of file flang1/utils/symtab/symtab.in.h.
AD_NOBOUNDS
#define AD_NOBOUNDS (p) ((p)->nobounds)
Definition at line 223 of file flang1/utils/symtab/symtab.in.h.
AD_NUMDIM
#define AD_NUMDIM (p) ((p)->numdim)
Definition at line 217 of file flang1/utils/symtab/symtab.in.h.
AD_NUMELM
#define AD_NUMELM (p) ((p)->b[AD_NUMDIM(p)].mlpyr)
Definition at line 231 of file flang1/utils/symtab/symtab.in.h.
AD_PTR
#define AD_PTR (sptr) ((ADSC *) (aux.arrdsc_base + DTY(DTYPEG(sptr)+2)))
Definition at line 216 of file flang1/utils/symtab/symtab.in.h.
AD_UPAST
#define AD_UPAST (p, i) ((p)->b[i].upast)
Definition at line 229 of file flang1/utils/symtab/symtab.in.h.
AD_UPBD
#define AD_UPBD (p, i) ((p)->b[i].upbd)
Definition at line 227 of file flang1/utils/symtab/symtab.in.h.
AD_ZBASE
#define AD_ZBASE (p) ((p)->zbase)
Definition at line 224 of file flang1/utils/symtab/symtab.in.h.
ADD_ADJARR
#define ADD_ADJARR (dtyp) AD_ADJARR(AD_DPTR(dtyp))
Definition at line 240 of file flang1/utils/symtab/symtab.in.h.
ADD_ASSUMRANK
#define ADD_ASSUMRANK (dtyp) AD_ASSUMRANK(AD_DPTR(dtyp))
Definition at line 238 of file flang1/utils/symtab/symtab.in.h.
ADD_ASSUMSHP
#define ADD_ASSUMSHP (dtyp) AD_ASSUMSHP(AD_DPTR(dtyp))
Definition at line 239 of file flang1/utils/symtab/symtab.in.h.
ADD_ASSUMSZ
#define ADD_ASSUMSZ (dtyp) AD_ASSUMSZ(AD_DPTR(dtyp))
Definition at line 241 of file flang1/utils/symtab/symtab.in.h.
ADD_DEFER
#define ADD_DEFER (dtyp) AD_DEFER(AD_DPTR(dtyp))
Definition at line 237 of file flang1/utils/symtab/symtab.in.h.
ADD_EXTNTAST
#define ADD_EXTNTAST (dtyp, i) AD_EXTNTAST(AD_DPTR(dtyp), i)
Definition at line 249 of file flang1/utils/symtab/symtab.in.h.
ADD_LWAST
#define ADD_LWAST (dtyp, i) AD_LWAST(AD_DPTR(dtyp), i)
Definition at line 247 of file flang1/utils/symtab/symtab.in.h.
ADD_LWBD
#define ADD_LWBD (dtyp, i) AD_LWBD(AD_DPTR(dtyp), i)
Definition at line 245 of file flang1/utils/symtab/symtab.in.h.
ADD_MLPYR
#define ADD_MLPYR (dtyp, i) AD_MLPYR(AD_DPTR(dtyp), i)
Definition at line 244 of file flang1/utils/symtab/symtab.in.h.
ADD_NOBOUNDS
#define ADD_NOBOUNDS (dtyp) AD_NOBOUNDS(AD_DPTR(dtyp))
Definition at line 242 of file flang1/utils/symtab/symtab.in.h.
ADD_NUMDIM
#define ADD_NUMDIM (dtyp) AD_NUMDIM(AD_DPTR(dtyp))
Definition at line 236 of file flang1/utils/symtab/symtab.in.h.
ADD_NUMELM
#define ADD_NUMELM (dtyp) AD_NUMELM(AD_DPTR(dtyp))
Definition at line 250 of file flang1/utils/symtab/symtab.in.h.
ADD_UPAST
#define ADD_UPAST (dtyp, i) AD_UPAST(AD_DPTR(dtyp), i)
Definition at line 248 of file flang1/utils/symtab/symtab.in.h.
ADD_UPBD
#define ADD_UPBD (dtyp, i) AD_UPBD(AD_DPTR(dtyp), i)
Definition at line 246 of file flang1/utils/symtab/symtab.in.h.
ADD_ZBASE
#define ADD_ZBASE (dtyp) AD_ZBASE(AD_DPTR(dtyp))
Definition at line 243 of file flang1/utils/symtab/symtab.in.h.
ALIGN
#define ALIGN (addr, a) ((addr + a) & ~(a))
Definition at line 96 of file flang1/utils/symtab/symtab.in.h.
ALIGN_AUTO
#define ALIGN_AUTO (addr, a) ((addr) & ~(a))
Definition at line 97 of file flang1/utils/symtab/symtab.in.h.
ALIGNG
#define ALIGNG (sptr) 0
Definition at line 449 of file flang1/utils/symtab/symtab.in.h.
ARGINFOG
#define ARGINFOG (s) ((stb.stg_base)[s].w16)
Definition at line 168 of file flang1/utils/symtab/symtab.in.h.
ARGINFOP
#define ARGINFOP (s, v) ((stb.stg_base)[s].w16 = (v))
Definition at line 169 of file flang1/utils/symtab/symtab.in.h.
check_DTYPE
#define check_DTYPE (v) (v)
Definition at line 141 of file flang1/utils/symtab/symtab.in.h.
check_INT
#define check_INT (v) (v)
Definition at line 142 of file flang1/utils/symtab/symtab.in.h.
check_SPTR
#define check_SPTR (v) (v)
Definition at line 140 of file flang1/utils/symtab/symtab.in.h.
CMPLXFUNC_C
#define CMPLXFUNC_C XBIT(49, 0x40000000)
Definition at line 191 of file flang1/utils/symtab/symtab.in.h.
CUDA_BUILTIN
#define CUDA_BUILTIN 0x08
Definition at line 106 of file flang1/utils/symtab/symtab.in.h.
CUDA_DEVICE
#define CUDA_DEVICE 0x02
Definition at line 104 of file flang1/utils/symtab/symtab.in.h.
CUDA_GLOBAL
#define CUDA_GLOBAL 0x04
Definition at line 105 of file flang1/utils/symtab/symtab.in.h.
CUDA_GRID
#define CUDA_GRID 0x10
Definition at line 107 of file flang1/utils/symtab/symtab.in.h.
CUDA_HOST
#define CUDA_HOST 0x01
Definition at line 103 of file flang1/utils/symtab/symtab.in.h.
CUDAG
#define CUDAG (s) b4G(s)
Definition at line 164 of file flang1/utils/symtab/symtab.in.h.
CUDAP
#define CUDAP (s, v) b4P(s,v)
Definition at line 165 of file flang1/utils/symtab/symtab.in.h.
DDTG
#define DDTG (dt) (DTY(dt) == TY_ARRAY ? DTY(dt+1) : dt)
Definition at line 59 of file flang1/utils/symtab/symtab.in.h.
DESCRIPTIVE
#define DESCRIPTIVE 1
Definition at line 130 of file flang1/utils/symtab/symtab.in.h.
DISTG
#define DISTG (sptr) 0
Definition at line 450 of file flang1/utils/symtab/symtab.in.h.
DLL_EXPORT
#define DLL_EXPORT 0x1
Definition at line 126 of file flang1/utils/symtab/symtab.in.h.
DLL_IMPORT
#define DLL_IMPORT 0x2
Definition at line 127 of file flang1/utils/symtab/symtab.in.h.
DLL_NONE
#define DLL_NONE 0x0
Definition at line 125 of file flang1/utils/symtab/symtab.in.h.
DLLG
#define DLLG (s) b3G(s)
Definition at line 158 of file flang1/utils/symtab/symtab.in.h.
DLLP
#define DLLP (s, v) b3P(s,v)
Definition at line 159 of file flang1/utils/symtab/symtab.in.h.
DT_CMPLX
#define DT_CMPLX stb.dt_cmplx
Definition at line 42 of file flang1/utils/symtab/symtab.in.h.
DT_CPTR
#define DT_CPTR DT_ADDR
Definition at line 50 of file flang1/utils/symtab/symtab.in.h.
DT_DBLE
#define DT_DBLE stb.dt_dble
Definition at line 44 of file flang1/utils/symtab/symtab.in.h.
DT_DCMPLX
#define DT_DCMPLX stb.dt_dcmplx
Definition at line 45 of file flang1/utils/symtab/symtab.in.h.
DT_FLOAT
#define DT_FLOAT DT_REAL4
Definition at line 48 of file flang1/utils/symtab/symtab.in.h.
DT_INT
#define DT_INT stb.dt_int
Definition at line 40 of file flang1/utils/symtab/symtab.in.h.
DT_ISBASIC
#define DT_ISBASIC (dt) (dttypes[DTY(dt)]&_TY_BASIC)
Definition at line 67 of file flang1/utils/symtab/symtab.in.h.
DT_ISCHAR
#define DT_ISCHAR (dt) (dttypes[DTY(dt)]&(_TY_CHAR|_TY_NCHAR))
Definition at line 62 of file flang1/utils/symtab/symtab.in.h.
DT_ISCMPLX
#define DT_ISCMPLX (dt) (dttypes[DTY(dt)]&_TY_CMPLX)
Definition at line 65 of file flang1/utils/symtab/symtab.in.h.
DT_ISCMPLX_ARR
#define DT_ISCMPLX_ARR (dt) (DTY(dt)==TY_ARRAY && DT_ISCMPLX(DTY(dt+1)))
Definition at line 77 of file flang1/utils/symtab/symtab.in.h.
DT_ISDWORD
#define DT_ISDWORD (dt) (dttypes[DTY(dt)]&_TY_DWORD)
Definition at line 73 of file flang1/utils/symtab/symtab.in.h.
DT_ISINT
#define DT_ISINT (dt) (dttypes[DTY(dt)]&_TY_INT)
Definition at line 63 of file flang1/utils/symtab/symtab.in.h.
DT_ISINT_ARR
#define DT_ISINT_ARR (dt) (DTY(dt)==TY_ARRAY && DT_ISINT(DTY(dt+1)))
Definition at line 75 of file flang1/utils/symtab/symtab.in.h.
DT_ISLOG
#define DT_ISLOG (dt) (dttypes[DTY(dt)]&_TY_LOG)
Definition at line 71 of file flang1/utils/symtab/symtab.in.h.
DT_ISLOG_ARR
#define DT_ISLOG_ARR (dt) (DTY(dt)==TY_ARRAY && DT_ISLOG(DTY(dt+1)))
Definition at line 79 of file flang1/utils/symtab/symtab.in.h.
DT_ISNUMERIC
#define DT_ISNUMERIC (dt) (dttypes[DTY(dt)]&(_TY_INT|_TY_REAL|_TY_CMPLX))
Definition at line 66 of file flang1/utils/symtab/symtab.in.h.
DT_ISNUMERIC_ARR
#define DT_ISNUMERIC_ARR (dt) (DTY(dt)==TY_ARRAY && DT_ISNUMERIC(DTY(dt+1)))
Definition at line 78 of file flang1/utils/symtab/symtab.in.h.
DT_ISREAL
#define DT_ISREAL (dt) (dttypes[DTY(dt)]&_TY_REAL)
Definition at line 64 of file flang1/utils/symtab/symtab.in.h.
DT_ISREAL_ARR
#define DT_ISREAL_ARR (dt) (DTY(dt)==TY_ARRAY && DT_ISREAL(DTY(dt+1)))
Definition at line 76 of file flang1/utils/symtab/symtab.in.h.
DT_ISSCALAR
#define DT_ISSCALAR (dt) (dttypes[DTY(dt)]&_TY_SCALAR)
Definition at line 69 of file flang1/utils/symtab/symtab.in.h.
DT_ISUNSIGNED
#define DT_ISUNSIGNED (dt) (dttypes[DTY(dt)]&_TY_UNSIGNED)
Definition at line 68 of file flang1/utils/symtab/symtab.in.h.
DT_ISVEC
#define DT_ISVEC (dt) (dttypes[DTY(dt)]&_TY_VEC)
Definition at line 70 of file flang1/utils/symtab/symtab.in.h.
DT_ISWORD
#define DT_ISWORD (dt) (dttypes[DTY(dt)]&_TY_WORD)
Definition at line 72 of file flang1/utils/symtab/symtab.in.h.
DT_LOG
#define DT_LOG stb.dt_log
Definition at line 43 of file flang1/utils/symtab/symtab.in.h.
DT_MAX_43
#define DT_MAX_43 43
Definition at line 30 of file flang1/utils/symtab/symtab.in.h.
DT_PTR
#define DT_PTR stb.dt_ptr
Definition at line 46 of file flang1/utils/symtab/symtab.in.h.
DT_REAL
#define DT_REAL stb.dt_real
Definition at line 41 of file flang1/utils/symtab/symtab.in.h.
DTY
#define DTY (d) (stb.dt.stg_base[d])
Definition at line 53 of file flang1/utils/symtab/symtab.in.h.
DTYG
#define DTYG (dt) (DTY(dt) == TY_ARRAY ? DTY(DTY(dt+1)) : DTY(dt))
Definition at line 60 of file flang1/utils/symtab/symtab.in.h.
DVL_CONVAL
#define DVL_CONVAL (i) aux.dvl_base[i].conval
Definition at line 309 of file flang1/utils/symtab/symtab.in.h.
DVL_SPTR
#define DVL_SPTR (i) aux.dvl_base[i].sptr
Definition at line 308 of file flang1/utils/symtab/symtab.in.h.
FORALLNDXG
#define FORALLNDXG (s) DOVARG(s)
Definition at line 152 of file flang1/utils/symtab/symtab.in.h.
FORALLNDXP
#define FORALLNDXP (s, v) DOVARP(s,v)
Definition at line 153 of file flang1/utils/symtab/symtab.in.h.
IGNORE_C
#define IGNORE_C 0x40
Definition at line 120 of file flang1/utils/symtab/symtab.in.h.
IGNORE_D
#define IGNORE_D 0x8
Definition at line 117 of file flang1/utils/symtab/symtab.in.h.
IGNORE_K
#define IGNORE_K 0x2
Definition at line 115 of file flang1/utils/symtab/symtab.in.h.
IGNORE_M
#define IGNORE_M 0x20
Definition at line 119 of file flang1/utils/symtab/symtab.in.h.
IGNORE_R
#define IGNORE_R 0x4
Definition at line 116 of file flang1/utils/symtab/symtab.in.h.
IGNORE_T
#define IGNORE_T 0x1
Definition at line 114 of file flang1/utils/symtab/symtab.in.h.
IGNORE_TKR_ALL
#define IGNORE_TKR_ALL 0x3f
Definition at line 122 of file flang1/utils/symtab/symtab.in.h.
IGNORE_TKR_ALL0
#define IGNORE_TKR_ALL0 0x1f /* old value of IGNORE_TKR_ALL */
Definition at line 123 of file flang1/utils/symtab/symtab.in.h.
IMPL_INDEX
#define IMPL_INDEX (uc)
Value:
         (islower(uc) ? uc - 'a' :      \
         (isupper(uc) ? 26+(uc-'A') : \
            (uc == '$'  ? 52 :              \
         (uc == '_'  ?  53  : -1) )))
Definition at line 298 of file flang1/utils/symtab/symtab.in.h.
INHERITG
#define INHERITG (sptr) 0
Definition at line 452 of file flang1/utils/symtab/symtab.in.h.
INTENT_DFLT
#define INTENT_DFLT 0x0
Definition at line 112 of file flang1/utils/symtab/symtab.in.h.
INTENT_IN
#define INTENT_IN 0x1
Definition at line 109 of file flang1/utils/symtab/symtab.in.h.
INTENT_INOUT
#define INTENT_INOUT 0x3
Definition at line 111 of file flang1/utils/symtab/symtab.in.h.
INTENT_OUT
#define INTENT_OUT 0x2
Definition at line 110 of file flang1/utils/symtab/symtab.in.h.
INTENTG
#define INTENTG (s) b3G(s)
Definition at line 156 of file flang1/utils/symtab/symtab.in.h.
INTENTP
#define INTENTP (s, v) b3P(s,v)
Definition at line 157 of file flang1/utils/symtab/symtab.in.h.
IS_CHAR_TYPE
#define IS_CHAR_TYPE (t) (TY_ISCHAR(t))
Definition at line 94 of file flang1/utils/symtab/symtab.in.h.
IS_PROC
#define IS_PROC (st) ((st) >= ST_ENTRY && (st) <= ST_PD)
Definition at line 24 of file flang1/utils/symtab/symtab.in.h.
IS_TBP
#define IS_TBP (func) (VTOFFG(func) && TBPLNKG(func))
Definition at line 148 of file flang1/utils/symtab/symtab.in.h.
IS_THREAD_TLS
#define IS_THREAD_TLS (s) (THREADG(s) && IS_TLS(s))
Definition at line 188 of file flang1/utils/symtab/symtab.in.h.
IS_THREAD_TP
#define IS_THREAD_TP (s) (THREADG(s) && (!IS_TLS(s)))
Definition at line 189 of file flang1/utils/symtab/symtab.in.h.
IS_TLS
#define IS_TLS (s) (TLSG(s) || ETLSG(s))
Definition at line 187 of file flang1/utils/symtab/symtab.in.h.
KWDARGSTR
#define KWDARGSTR (p) intrinsic_kwd[KWDARGG(p)]
Definition at line 178 of file flang1/utils/symtab/symtab.in.h.
LOCAL_SYMNAME
#define LOCAL_SYMNAME (p) local_sname(SYMNAME(p))
Definition at line 175 of file flang1/utils/symtab/symtab.in.h.
NEWDSCG
#define NEWDSCG (s) ((stb.stg_base)[s].w10)
Definition at line 166 of file flang1/utils/symtab/symtab.in.h.
NEWDSCP
#define NEWDSCP (s, v) ((stb.stg_base)[s].w10 = (v))
Definition at line 167 of file flang1/utils/symtab/symtab.in.h.
NML_LINENO
#define NML_LINENO (i) aux.nml_base[i].lineno
Definition at line 282 of file flang1/utils/symtab/symtab.in.h.
NML_NEXT
#define NML_NEXT (i) aux.nml_base[i].next
Definition at line 281 of file flang1/utils/symtab/symtab.in.h.
NML_SPTR
#define NML_SPTR (i) aux.nml_base[i].sptr
Definition at line 280 of file flang1/utils/symtab/symtab.in.h.
NOSYM
#define NOSYM 1
Definition at line 179 of file flang1/utils/symtab/symtab.in.h.
PDALN_EXPLICIT_0
#define PDALN_EXPLICIT_0 0xf
Definition at line 160 of file flang1/utils/symtab/symtab.in.h.
PDALN_IS_DEFAULT
#define PDALN_IS_DEFAULT (s) (b4G(s) == 0)
Definition at line 163 of file flang1/utils/symtab/symtab.in.h.
PDALNG
#define PDALNG (s) (b4G(s) == PDALN_EXPLICIT_0 ? 0 : b4G(s))
Definition at line 161 of file flang1/utils/symtab/symtab.in.h.
PDALNP
#define PDALNP (s, v) b4P(s, (v) == 0 ? PDALN_EXPLICIT_0 : (v))
Definition at line 162 of file flang1/utils/symtab/symtab.in.h.
PRESCRIPTIVE
#define PRESCRIPTIVE 0
Definition at line 129 of file flang1/utils/symtab/symtab.in.h.
RFCNTD
#define RFCNTD (s) (--RFCNTG(s))
Definition at line 177 of file flang1/utils/symtab/symtab.in.h.
RFCNTI
#define RFCNTI (s) (++RFCNTG(s))
Definition at line 176 of file flang1/utils/symtab/symtab.in.h.
RUNTIMEG
#define RUNTIMEG (sptr) 0
Definition at line 451 of file flang1/utils/symtab/symtab.in.h.
SC_AUTO
#define SC_AUTO SC_LOCAL
Definition at line 101 of file flang1/utils/symtab/symtab.in.h.
SC_ISCMBLK
#define SC_ISCMBLK (p) (p == SC_CMBLK)
Definition at line 102 of file flang1/utils/symtab/symtab.in.h.
ST_ISVAR
#define ST_ISVAR (s) (((s) >= ST_VAR && (s) <= ST_UNION))
Definition at line 23 of file flang1/utils/symtab/symtab.in.h.
SYMI_NEXT
#define SYMI_NEXT (i) aux.symi_base[i].next
Definition at line 293 of file flang1/utils/symtab/symtab.in.h.
SYMI_SPTR
#define SYMI_SPTR (i) aux.symi_base[i].sptr
Definition at line 292 of file flang1/utils/symtab/symtab.in.h.
SYMNAME
#define SYMNAME (p) (stb.n_base + NMPTRG(p))
Definition at line 173 of file flang1/utils/symtab/symtab.in.h.
SYMNAMEG
#define SYMNAMEG (p, buff, len) len = NMLENG(p); strncpy(buff,SYMNAME(p),len)
Definition at line 174 of file flang1/utils/symtab/symtab.in.h.
TRANSCRIPTIVE
#define TRANSCRIPTIVE 2
Definition at line 131 of file flang1/utils/symtab/symtab.in.h.
TY_FLOAT
#define TY_FLOAT TY_REAL
Definition at line 49 of file flang1/utils/symtab/symtab.in.h.
TY_ISBASIC
#define TY_ISBASIC (t) (dttypes[t]&_TY_BASIC)
Definition at line 86 of file flang1/utils/symtab/symtab.in.h.
TY_ISCHAR
#define TY_ISCHAR (t) (dttypes[t]&(_TY_CHAR|_TY_NCHAR))
Definition at line 81 of file flang1/utils/symtab/symtab.in.h.
TY_ISCMPLX
#define TY_ISCMPLX (t) (dttypes[t]&_TY_CMPLX)
Definition at line 84 of file flang1/utils/symtab/symtab.in.h.
TY_ISDWORD
#define TY_ISDWORD (t) (dttypes[t]&_TY_DWORD)
Definition at line 92 of file flang1/utils/symtab/symtab.in.h.
TY_ISINT
#define TY_ISINT (t) (dttypes[t]&_TY_INT)
Definition at line 82 of file flang1/utils/symtab/symtab.in.h.
TY_ISLOG
#define TY_ISLOG (t) (dttypes[t]&_TY_LOG)
Definition at line 89 of file flang1/utils/symtab/symtab.in.h.
TY_ISNUMERIC
#define TY_ISNUMERIC (t) (dttypes[t]&(_TY_INT|_TY_REAL|_TY_CMPLX))
Definition at line 85 of file flang1/utils/symtab/symtab.in.h.
TY_ISREAL
#define TY_ISREAL (t) (dttypes[t]&_TY_REAL)
Definition at line 83 of file flang1/utils/symtab/symtab.in.h.
TY_ISSCALAR
#define TY_ISSCALAR (t) (dttypes[t]&_TY_SCALAR)
Definition at line 88 of file flang1/utils/symtab/symtab.in.h.
TY_ISUNSIGNED
#define TY_ISUNSIGNED (t) (dttypes[t]&_TY_UNSIGNED)
Definition at line 87 of file flang1/utils/symtab/symtab.in.h.
TY_ISVEC
#define TY_ISVEC (t) (dttypes[t]&_TY_VEC)
Definition at line 90 of file flang1/utils/symtab/symtab.in.h.
TY_ISWORD
#define TY_ISWORD (t) (dttypes[t]&_TY_WORD)
Definition at line 91 of file flang1/utils/symtab/symtab.in.h.
XREFLKG
#define XREFLKG (s) ((stb.stg_base)[s].w16)
Definition at line 170 of file flang1/utils/symtab/symtab.in.h.
XREFLKP
#define XREFLKP (s, v) ((stb.stg_base)[s].w16 = (v))
Definition at line 171 of file flang1/utils/symtab/symtab.in.h.
Typedef Documentation
cmp_interface_flags
typedef enum CMP_INTERFACE_FLAGS cmp_interface_flags
flag defintions for cmp_interfaces_strict()
Enumeration Type Documentation
CMP_INTERFACE_FLAGS
enum CMP_INTERFACE_FLAGS
flag defintions for cmp_interfaces_strict()
Enumerator
IGNORE_IFACE_NAMES
ignore the symbol names sym1 & sym2, but make sure arguments have same stypes and names.
CMP_IFACE_NAMES
make sure sym1 and sym2 have the same symbol name.
IGNORE_ARG_NAMES
ignore the argument names.
RELAX_STYPE_CHK
relax stype check on arguments.
CMP_OPTARG
make sure sym1 and sym2 OPTARG fields are identical.
RELAX_INTENT_CHK
relax intent check on arguments.
RELAX_POINTER_CHK
relax pointer check on arguments.
RELAX_PURE_CHK_1
relax pure check on argument #1 of cmp_interfaces_strict() function
RELAX_PURE_CHK_2
relax pure check on argument #2 of cmp_interfaces_strict() function
CMP_SUBMOD_IFACE
make sure submodule interface of a procedure defined by a separate module subprogram's definition matches the declaration
DEFER_IFACE_CHK
defer interface check for procedure dummy arguments.
Definition at line 457 of file flang1/utils/symtab/symtab.in.h.
etls_levels
enum etls_levels
Enumerator
ETLS_PROCESS
ETLS_TASK
ETLS_THREAD
ETLS_OMP
ETLS_PROCESS
ETLS_TASK
ETLS_THREAD
ETLS_OMP
ETLS_NUM_LEVELS
Definition at line 181 of file flang1/utils/symtab/symtab.in.h.
Function Documentation
add_symitem()
int add_symitem (int sptr, int nxt)
Definition at line 3181 of file symtab.c.
change_predefineds()
void change_predefineds (int stype, LOGICAL remove)
switch from ST_CRAFT/ST_CRAY to ST_PD or vice versa
Definition at line 3195 of file symtab.c.
References BCOPY, first, hpf_library_stat(), last, s, and stb.
Referenced by semant_init().
cmp_interfaces()
bool cmp_interfaces (int sym1, int sym2, int flag)
Compares two symbols by returning true if they both have equivalent interfaces. Otherwise, return false.
If flag is set, then we also make sure that sym1 and sym2 have the same symbol name.
Definition at line 2449 of file symtab.c.
References aux, cmp_interfaces(), AUX::dpdsc_base, eq_dtype2(), HASH_ID, STB::hashtb, i, len, NOSYM, proc_arginfo(), scope, stb, strlen(), SYMNAME, and test_scope().
Referenced by cmp_interfaces(), eq_dtype2(), fix_proc_ptr_dummy_args(), and tk_match_arg().
cmp_interfaces_strict()
bool cmp_interfaces_strict (SPTR sym1, SPTR sym2, cmp_interface_flags flag)
Same as cmp_interfaces() except we also compare the characteristics as defined in "12.2 Characteristics of procedures" in F2003 Spec.
Definition at line 2655 of file symtab.c.
References aux, CMP_IFACE_NAMES, CMP_SUBMOD_IFACE, compatible_characteristics(), AUX::dpdsc_base, ERR_Severe, error(), gbl, i, j, NULL, proc_arginfo(), RELAX_PURE_CHK_1, RELAX_PURE_CHK_2, and SYMNAME.
Referenced by add_ptr_assign(), compatible_characteristics(), semant1(), semCheckTbp(), and transform_call().
compatible_characteristics()
bool compatible_characteristics (int psptr, int psptr2, cmp_interface_flags flag)
Tests the characteristics between two interfaces.
Parameters
psptr is the first interface.
pstr2 is the second interface.
flag is a bit mask that enforces/relaxes certain checks (see cmp_interface_flags enum in symtab.c).
Returns
true if the two characteristics are compatible, else false.
Definition at line 2551 of file symtab.c.
References AD_DPTR, AD_EXTNTAST, AD_NUMDIM, ast, cmp_interfaces_strict(), CMP_OPTARG, CMP_SUBMOD_IFACE, CONVAL2G, DDTG, DEFER_IFACE_CHK, DTY, DTYG, eq_dtype2(), ERR_Severe, error(), FALSE, gbl, generate_type_mismatch_errors(), i, IGNORE_ARG_NAMES, INTENTG, RELAX_INTENT_CHK, RELAX_POINTER_CHK, RELAX_STYPE_CHK, SYMNAME, TY_CHAR, and TY_NCHAR.
Referenced by cmp_interfaces_strict(), compat_arg_lists(), and defer_arg_chk().
convert_2dollar_signs_to_hyphen()
void convert_2dollar_signs_to_hyphen (char * name)
Convert two dollar signs to a hyphen. Especially used for the submodule *.mod file renaming: ancestor$$submod.mod -> ancestor-submod.mod.
Definition at line 3461 of file symtab.c.
References name, p, and q.
Referenced by add_to_be_used_list(), export_all(), and open_module().
copy_align_desc()
int copy_align_desc (int)
copy_dist_desc()
int copy_dist_desc (int)
copy_sym_flags()
void copy_sym_flags (SPTR dest, SPTR src)
Copy flags from one symbol to another symbol.
This routine is the same as dup_sym() except it preserves the symbol's name, hash link, scope, and name pointer. In other words, it copies all but 4 flags from one symbol to another. The 4 flags that are not copied are the hashlk, symlk, scope, and nmptr.
Parameters
dest is the receiving symbol table pointer of the flags.
src is the source symbol table pointer of the flags.
Definition at line 2791 of file symtab.c.
References dest, SYM::hashlk, SYM::nmptr, scope, SYM::scope, src, stb, and SYM::symlk.
Referenced by semant1().
dmp_socs()
void dmp_socs (int sptr, FILE * file)
Definition at line 1695 of file symtab.c.
dump_align()
void dump_align (FILE * , int)
dump_dist()
void dump_dist (FILE * , int)
dump_shadow()
void dump_shadow (FILE * , int)
dup_sym()
void dup_sym (int new, SYM * content)
replace contents of a symbol with values defining every field while ensuring values necessary for the hashing function are saved and restored.
Definition at line 2820 of file symtab.c.
References scope, and stb.
Referenced by gen_allocatable_result(), gen_array_result(), gen_pointer_result(), insert_dup_sym(), instantiate_interface(), reloc_byvalue_parameters(), and resolveBind().
find_explicit_interface()
SPTR find_explicit_interface (SPTR s)
return the symbol of the explicit interface of the ST_PROC
Definition at line 2861 of file symtab.c.
References s, and sptr.
Referenced by instantiate_interface(), semant1(), and sym_in_scope().
get_acon()
SPTR get_acon (SPTR sym, ISZ_T off)
Definition at line 601 of file symtab.c.
get_acon3()
SPTR get_acon3 (SPTR sym, ISZ_T off, DTYPE dtype)
Definition at line 611 of file symtab.c.
get_align_desc()
int get_align_desc (int , int)
get_dist_desc()
int get_dist_desc (int)
get_ieee_arith_intrin()
int get_ieee_arith_intrin (const char * nm)
Definition at line 428 of file symtab.c.
References i, and SYMNAME.
Referenced by add_predefined_ieeearith_module(), and export_ieee_arith_libraries().
get_int_cval()
INT get_int_cval (int con)
Retrieve the value of an integer constant symbol table entry and return as an 'INT'. Coerce TY_INT8 values if necessary.
Definition at line 674 of file symtab.c.
References assert, CONVAL2G, DT_ISINT, DT_ISLOG, DTY, res, TY_INT8, and TY_LOG8.
Referenced by _index(), _PDbound(), _PDsize(), _pghpf_bound(), _pghpf_size(), _repeat(), _reshape(), _RTE_ba(), _RTE_bound(), _RTE_size(), _RTE_xb(), _scan(), _verify(), check_dim_error(), check_subscript(), check_value(), chk_evar(), cmpat_arr_arg(), cmpat_dtype_with_size(), conformable(), const_eval(), conv_forall(), convert_template_instance(), dinit_data(), dinit_eval(), dump_ind(), eliminate_shift(), eval_init_op(), eval_sb(), eval_sub_index(), fill_cyclic_1(), fill_cyclic_k(), find_base(), generate_hcycliclp(), generate_hlocalizebnds(), get_isz_cval(), import(), increase_shape(), inline_reduction_f90(), inline_shifts(), inline_spread_shifts(), is_same_descr_for_bnds(), is_same_mask(), leave_arg(), lower_stmt(), mk_array_type(), mk_reshape_intrin(), mk_size(), mk_ulbound_intrin(), nml_emit_desc(), reduc_shape(), ref_pd(), rewrite_func_ast(), same_dtype(), semant1(), semant2(), semant3(), set_kind_result(), and string_expr_length().
get_isz_cval()
ISZ_T get_isz_cval (int con)
Definition at line 650 of file symtab.c.
get_len_of_deferchar_ast()
int get_len_of_deferchar_ast (int ast)
Definition at line 78 of file symutl.c.
References assert, ast, astb, ASTB::bnd, ASTB::dtype, first, first_element(), get_byte_len(), get_byte_len_indx(), get_member_descriptor(), mk_id(), mk_isz_cval(), mk_member(), mk_subscr(), and sptr.
Referenced by add_ptr_assign(), func_call2(), gen_alloc_dealloc(), gen_automatic_reallocation(), gen_bounds_assignments(), rewrite_allocatable_assignment(), and rewrite_func_ast().
get_proc_ptr()
SPTR get_proc_ptr (SPTR sptr)
get a temporary procedure pointer to a specified procedure.
Parameters
sptr is the ST_PROC pointer target.
Returns
the procedure pointer.
Definition at line 3877 of file symutl.c.
Referenced by transform_call().
get_shadow_desc()
int get_shadow_desc (int)
getccssym()
int getccssym (const char * pfx, int n, int stype)
create (or possibly reuse) a compiler created symbol whose name is of the form . "pfx" dddd where dddd is the decimal representation of n and "pfx" is the prefix specified in the pfx argument.
Definition at line 1852 of file symtab.c.
References STB::curr_scope, getsymbol(), i, IPA_RECOMPILATION_SUFFIX, n, name, sptr, stb, strlen(), and suffix.
Referenced by createUplevelSptr(), enter_lexical_block(), getccssym_sc(), and mp_create_bscope().
getccssym_sc()
int getccssym_sc (const char * pfx, int n, int stype, int sc)
similar to getccssym, but storage class is an argument. Calls getccssym if the storage class is not private; if private, a 'p' is appended to the name.
Definition at line 1883 of file symtab.c.
References STB::curr_scope, getccssym(), getsymf(), i, IPA_RECOMPILATION_SUFFIX, n, sptr, and stb.
Referenced by collapse_expr(), do_distbegin(), dotemp(), get_collapse_temp(), get_dtype_init_template(), lower_do_stmt(), and mkrtemp_arg1_sc().
getccsym()
int getccsym (int letter, int n, SYMTYPE stype)
create (or possibly reuse) a compiler created symbol whose name is of the form . 'letter' dddd where dddd is the decimal representation of n and 'letter' is the character specified in the letter argument.
Definition at line 1726 of file symtab.c.
References STB::curr_scope, getsymbol(), i, IPA_RECOMPILATION_SUFFIX, n, name, sptr, stb, and suffix.
Referenced by _constructf90(), add_private_allocatable(), allochartmp(), begin_entry(), check_alloc_ptr_type(), check_pointer_type(), create_display_temp_arg(), create_llvm_display_temp(), create_ref(), exp_header(), exp_misc(), fill_midnum(), get_atmp(), get_stblk_uplevel_sptr(), getccsym_sc(), getchartmp(), getdumlen(), gethost_dumlen(), getNewWideSym(), increase_shape(), llvmAddConcurEntryBlk(), mk_argasym(), mk_swlist(), mk_swtab(), mk_swtab_ll(), mkarglist(), mklvalue(), pp_entries(), pp_entries_mixedstrlen(), reduc_shape(), ref_based_object_sc(), ref_pd(), semant1(), and semant3().
getccsym_sc()
int getccsym_sc (int letter, int n, int stype, int sc)
similar to getccsym, but storage class is an argument. Calls getccsym if the storage class is not private; if private, a 'p' is appended to the name.
Definition at line 1812 of file symtab.c.
References STB::curr_scope, getccsym(), getsymbol(), i, IPA_RECOMPILATION_SUFFIX, n, name, sptr, stb, and suffix.
Referenced by add_class_arg_descr_arg(), exp_type_bound_proc_call(), gen_kind_parm_assignments(), gen_poly_element_arg(), get_unl_poly_sym(), initFinalSub(), is_intrinsic_opr(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), lower_scalar_temp(), mkrtemp_cpx_sc(), mkrtemp_sc(), and transform_call().
getcctmp()
int getcctmp (int letter, int n, int stype, int dtype)
Create a local compiler-created symbol - calls getcctmp_sc with the storage class SC_LOCAL.
Definition at line 1964 of file symtab.c.
References block_local_sym(), SEM::block_scope, getcctmp_sc(), n, sem, and sptr.
Referenced by ch_substring(), dinit_name(), get_arr_const(), mk_bnd_ast(), mk_shared_bnd_ast(), and put_name().
getcctmp_sc()
int getcctmp_sc (int letter, int n, int stype, int dtype, int sc)
create (or possibly reuse) a compiler created symbol whose name is of the form z_'letter'_'d' where 'd' is the decimal representation of n. If the storage class is private, 'p' is appended to the name.
Definition at line 1917 of file symtab.c.
References assert, CUDA_DEVICE, CUDA_GLOBAL, CUDAG, STB::curr_scope, DTY, gbl, getsymf(), i, IPA_RECOMPILATION_SUFFIX, n, sptr, and stb.
Referenced by _constructf90(), addssassignments(), chk_var(), func_call2(), gen_and_assoc_tmp_ptr(), gen_dtio_arglist(), gen_dtio_args(), gen_dtsfmt_args(), gen_spec_item_tmp(), gen_vlist(), get_invoking_proc_desc(), getcctmp(), mkarg(), mklabelvar(), ref_pd(), rewrite_allocatable_assignment(), semant3(), semantio(), temp_type_descriptor(), and transform_call().
getcon()
SPTR getcon (INT * value, DTYPE dtype)
Enter constant of given dtype and value into the symbol table and return pointer to it.
If an entry for the constant already exists, return pointer to the existing entry instead.
Enter constant of given dtype and value into the symbol table and return pointer to it.
Parameters
value is the constant value (value[1] if 1 word).
dtype - tbw.
Definition at line 524 of file symtab.c.
gethollerith()
int gethollerith (int strcon, int kind)
Create a 'kinded' hollerith constant from a string constant and return the pointer to it. If the constant is already in the table, return pointer to the existing entry. Possible kind values are: 'h' - left justifed, blank filled. 'l' - left justfied, zero filled. 'r' - right justfied, zero filled.
Definition at line 789 of file symtab.c.
References getcon(), kind, sptr, and val.
Referenced by _rd_token(), and crunch().
getlab()
int getlab (void)
return a compiler-created label – user labels begin with '.', compiler- created labels begin with ''. Compiler-created labels will be mapped to fortran 77 labels by astout.
Definition at line 2048 of file symtab.c.
getnewccsym()
int getnewccsym (int letter, int n, int stype)
create (never reuse) a compiler created symbol whose name is of the form . 'letter' dddd where dddd is the decimal representation of n and 'letter' is the character specified in the letter argument.
Definition at line 1757 of file symtab.c.
References gbl, n, name, NEWSYM, putsname(), sptr, and strlen().
Referenced by _sect(), exp_smp(), getPrivateTemp(), ll_create_task_sptr(), ll_set_new_threadprivate(), makeCopyprivArray(), and mkatomictemp().
getnewccsymf()
int getnewccsymf (int stype, const char * fmt, ...)
Definition at line 1793 of file symtab.c.
References getnewccsym2(), and MAXIDLEN.
Referenced by _sect(), and symvalue().
getprint()
const char * getprint (int sptr)
Return ptr to printable representation of the indicated symbol.
Parameters
sptr symbol table pointer
For symbols which are not constants, the name of the symbol is used. Constants are converted into the appropriate character representation.
Parameters
sptr - symbol table pointer
Definition at line 944 of file symtab.c.
getsname()
char * getsname (int)
Referenced by get_ftn_static_lltype(), get_ftn_typedesc_lltype(), ll_get_gtid_addr_ili(), ll_get_gtid_val_ili(), ll_get_outlined_funcname(), mk_impsym(), process_blockaddr_sptr(), put_addr(), and write_proc_pointer().
getstring()
int getstring (const char * value, int length)
Enter character constant into symbol table and return pointer to it.
Parameters
value character string value
length length of character string
If the constant is already in the table, return pointer to the existing entry instead.
Definition at line 724 of file symtab.c.
getsym()
SPTR getsym (const char * name, int olength)
Enter symbol with indicated name into symbol table, initialize the new entry.
Parameters
name symbol name
olength number of characters in the symbol name
Returns
pointer to new symbol
If there is already such a symbol, just return pointer to the existing symbol table entry.
Enter symbol with indicated name into symbol table, initialize the new entry.
Parameters
name is the symbol name.
olength is the number of characters in the symbol name.
Definition at line 460 of file symtab.c.
getsymbol()
SPTR getsymbol (const char * name)
Enter symbol with indicated name into symbol table, initialize the new entry, and return pointer to it. If there is already such a symbol, just return pointer to the existing symbol table entry.
Parameters
name is the symbol name.
Definition at line 445 of file symtab.c.
getsymf()
SPTR getsymf (const char * fmt, ...)
Definition at line 500 of file symtab.c.
References getsymbol(), and MAXIDLEN.
Referenced by _read_token(), addToDtype(), chk_fmtid(), ff_get_label(), get_csect_sym(), get_stmt(), get_submod_sym(), get_tbp(), get_unl_poly_sym(), getccssym_sc(), getcctmp_sc(), getlab(), hlv_getvsym(), iface_intrinsic(), reloc_byvalue_parameters(), semant1(), semant3(), sym_get_sdescr(), and sym_init().
hpf_library_stat()
void hpf_library_stat (int * firstp, int * lastp, int stype)
Return the first & last sym pointers for the HPF_LIBRARY procedures. Initially, the stype of the HPF library procedures is ST_HL; when the USE statement is seen, the stype of these symbols is changed to ST_PD.
Definition at line 393 of file symtab.c.
References interr().
Referenced by change_predefineds().
implicit_int()
void implicit_int (int default_int)
simple routine to reset the default integer type for implicitly typing integer variables. Needed for compile-type processing of -i4/-noi4 options in OPTIONS statement.
Definition at line 347 of file symtab.c.
References dtimplicit, DTIMPL::dtype, FALSE, i, and DTIMPL::typ8.
Referenced by init_implicit(), and scan_options().
init_implicit()
void init_implicit (void)
Set up initial implicit types. All are real except for the letters i thru n:
Definition at line 321 of file symtab.c.
References DTIMPL::anyset, STB::dt_int, STB::dt_real, dtimplicit, DTIMPL::dtype, FALSE, flg, i, FLG::i4, implicit_int(), DTIMPL::set, stb, TRUE, DTIMPL::typ8, STB::user, and XBIT.
Referenced by semant1(), and sym_init().
insert_dup_sym()
int insert_dup_sym (int sptr)
\Brief Create a duplicate of this sym and return it
Definition at line 2835 of file symtab.c.
References dup_sym(), insert_sym(), sptr, and stb.
Referenced by create_parameterized_dt(), get_parameterized_dt(), instantiate_interface(), mod_add_subprogram(), and semant3().
insert_sym()
int insert_sym (int first)
create new symbol table entry and insert it in the hash list immediately in front of 'first':
Definition at line 1985 of file symtab.c.
References assert, STB::curr_scope, first, gbl, HASH_ID, STB::hashtb, i, j, NEWSYM, NOSYM, setimplicit(), sptr, stb, strlen(), and SYMNAME.
Referenced by apply_use(), begin_submodule(), block_local_sym(), chk_intrinsic(), create_func_entry(), create_var(), decl_private_sym(), decl_procedure_sym(), declare_type(), declref(), declsym(), declsym_newscope(), do_access(), find_outer_sym(), gen_accl_alias(), gen_finalized_result(), get_fmt_array(), get_fval_array(), getocsym(), getsym(), iface_arg(), import_mk_newsym(), import_symbol(), insert_dup_sym(), link_parents(), lower_prepare_symbols(), mklvalue(), newsym(), open_module(), record_func_result(), ref_entry(), ref_ident(), ref_ident_inscope(), ref_int_scalar(), ref_storage_inscope(), refsym(), refsym_inscope(), replace_variable(), resolveBind(), resolveImp(), restore_internal_subprograms(), semant1(), semant2(), and semant3().
insert_sym_first()
int insert_sym_first (int first)
create new symbol table entry and insert it in the hash list in front of the head of the list containing 'first':
Definition at line 2020 of file symtab.c.
References STB::curr_scope, first, gbl, HASH_ID, STB::hashtb, i, NEWSYM, NOSYM, setimplicit(), sptr, stb, strlen(), and SYMNAME.
Referenced by add_member_for_llvm(), construct_association(), and instantiate_interface().
instantiate_interface()
SPTR instantiate_interface (SPTR iface)
Instantiate a copy of a separate module subprogram's declared interface as part of the MODULE PROCEDURE's definition (i.e., implement what would have taken place had the subprogram been defined with a MODULE SUBROUTINE or MODULE FUNCTION with a compatible interface).
Definition at line 2884 of file symtab.c.
References AD_DPTR, arg, array_element_dtype(), aux, DEC_DEF_MAP::dec_sptr, DEC_DEF_MAP::def_sptr, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, DTY, dup_sym(), find_explicit_interface(), FREE, gbl, get_all_descriptors(), get_static_descriptor(), insert_dup_sym(), insert_sym_first(), j, mk_arrdsc(), NEED, NEW, NOSYM, stb, trans_mkdescr(), TRUE, and update_arrdsc().
Referenced by semant1().
ir8name()
char * ir8name (char * , int)
is_arg_in_entry()
LOGICAL is_arg_in_entry (int ent, int arg)
determine if an argument is an argument to a given entry
Parameters
ent entry sptr
arg argument sptr
Definition at line 2294 of file symtab.c.
References arg, assert, aux, AUX::dpdsc_base, FALSE, i, and TRUE.
Referenced by handle_arguments(), and lower_data_stmts().
is_procedure_ptr()
LOGICAL is_procedure_ptr (int sptr)
Definition at line 2350 of file symtab.c.
References FALSE, is_procedure_ptr_dtype(), NOSYM, resolve_sym_aliases(), and sptr.
Referenced by assign_pointer(), chk_pointer_target(), dinit_val(), do_access(), fix_proc_pointer_call(), fix_proc_ptr_dummy_args(), get_invoking_proc_desc(), get_static_descriptor(), handle_arguments(), handle_seq_section(), is_associatable_variable_sst(), is_data_ast(), is_desc_needed(), is_variable_ast(), lower_data_stmts(), lower_function(), lower_make_all_descriptors(), lower_stmt(), lower_symbols(), mkvarref(), needDebugInfoFilt(), newargs_for_entry(), proc_arginfo(), ptrfunc_call(), ptrsubr_call(), ref_intrin_subr(), ref_pd(), semant1(), semant2(), semant3(), sym_is_dinitd(), transform_call(), and update_proc_ptr_dtype_from_interface().
is_used_by_submod()
bool is_used_by_submod (SPTR sym1, SPTR sym2)
Used for check whether sym2 used inside the scope of sym1 is defined in parent modules (SCOPEG(sym2)) and used by inherited submodules ENCLFUNCG(sym1).
Definition at line 3479 of file symtab.c.
Referenced by set_assn(), and sym_in_scope().
iso_c_lib_stat()
void iso_c_lib_stat (int * firstp, int * lastp, int stype)
Return the first & last sym pointers for the ISO_C intrinsic procedures. Initially, the stype of the ISO_C library procedures is ST_ISOC when the USE statement is seen, the stype of these symbols is changed to ST_INTRIN
Definition at line 413 of file symtab.c.
References interr().
Referenced by add_isoc_intrinsics(), export_iso_c_libraries(), and open_module().
mangle_name()
char * mangle_name (const char * basename, const char * purpose)
create a distinct mangled name
Definition at line 3045 of file symtab.c.
References assert, STB::curr_scope, flg, HASH_ID, STB::hashtb, i, j, length(), manglecount, MAXIDLEN, name, sptr, FLG::standard, STANDARD_MAXIDLEN, stb, strlen(), and SYMNAME.
Referenced by get_next_sym(), and get_param_alias_var().
mk_coercion_func()
int mk_coercion_func (int dtype)
Create a coercion function based on the data type.
Definition at line 2231 of file symtab.c.
References mk_coercion_func_name(), sptr, and sym_mkfunc_nodesc().
Referenced by ref_pd().
mk_coercion_func_name()
const char * mk_coercion_func_name (int dtype)
create a coercion function based on the data type.
Definition at line 2173 of file symtab.c.
References DTY, interr(), mkRteRtnNm(), RTE_cmplx16, RTE_cmplx32, RTE_cmplx8, RTE_int1, RTE_int2, RTE_int4, RTE_int8, RTE_log1, RTE_log2, RTE_log4, RTE_log8, RTE_no_rtn, RTE_real16, RTE_real4, RTE_real8, TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, and TY_SLOG.
Referenced by lower_intrinsic(), and mk_coercion_func().
mk_external_var()
int mk_external_var (char * name, int dtype)
create an external variable given a name and its data type. A common block of the same name is created and its member is the variable. If the variable already exists, just return it.
Definition at line 2245 of file symtab.c.
References assert, CMEMLP, DTY, gbl, getsymbol(), name, NOSYM, pop_sym(), and sptr.
mkfunc()
SPTR mkfunc (const char * nmptr)
Create a function ST item given a name.
create a function ST item given a name
Definition at line 2157 of file symtab.c.
mkfunc_cncall()
SPTR mkfunc_cncall (const char * nmptr)
Definition at line 1127 of file exputil.cpp.
References mkfunc(), and sptr.
Referenced by exp_strcpy().
mkfunc_ir8name()
char * mkfunc_ir8name (int , char * , int)
mkfunc_name()
char * mkfunc_name (int , char *)
newimplicit()
void newimplicit (int firstc, int lastc, int dtype)
Change the current settings for implicit variable types and character lengths.
Parameters
firstc characters delimiting range
lastc new value assigned to range
dtype data type
Definition at line 810 of file symtab.c.
References DTIMPL::anyset, assert, CNULL, dtimplicit, DTIMPL::dtype, error(), FALSE, gbl, i, IMPL_INDEX, j, DTIMPL::set, set, TRUE, and DTIMPL::typ8.
Referenced by semant1().
newimplicitnone()
void newimplicitnone (void)
Definition at line 839 of file symtab.c.
References DTIMPL::anyset, dtimplicit, FALSE, and i.
Referenced by semant1().
parmprint()
const char * parmprint (int sptr)
Return ptr to printable representation of the indicated PARAMETER.
Parameters
sptr symbol table pointer
sptr - symbol table pointer
Definition at line 892 of file symtab.c.
pop_sym()
void pop_sym (int sptr)
remove a symbol from its hash list
remove a symbol from its hash list
Definition at line 2101 of file symtab.c.
proc_arginfo()
void proc_arginfo (int sptr, int * paramct, int * dpdsc, int * iface)
Definition at line 2367 of file symtab.c.
References assert, DTY, get_implementation(), get_specific_member(), is_procedure_ptr(), IS_TBP, mem(), and sptr.
Referenced by _rewrite_scalar_fuctions(), add_ptr_assign(), assign_pointer(), bld_ud(), check_defined_io2(), chk_arguments(), cmp_interfaces(), cmp_interfaces_strict(), elemental_func_call(), extract_shape_from_args(), find_byval_ref(), fix_proc_pointer_call(), fix_proc_ptr_dummy_args(), gen_automatic_reallocation(), get_generic_member2(), get_tbp_argno(), handle_seq_section(), initFinalSub(), is_desc_needed(), is_ptrast_arg(), is_seq_dummy(), needs_type_in_descr(), ptrfunc_call(), ptrsubr_call(), pure_func_call(), put_call(), resolveImp(), resolvePass(), rewrite_sub_args(), semant1(), semant2(), semant3(), semCheckTbp(), string_expr_length(), transform_call(), update_proc_ptr_dtype_from_interface(), and valid_assign_pointer_types().
push_sym()
void push_sym (int sptr)
push a symbol onto a hash list
Definition at line 2137 of file symtab.c.
References DBGBIT, gbl, HASH_ID, STB::hashtb, name, sptr, stb, strlen(), and SYMNAME.
Referenced by declsym(), and semant3().
reinit_sym()
void reinit_sym (int sptr)
reinitialize a symbol
Definition at line 3015 of file symtab.c.
References BZERO, scope, sptr, and stb.
Referenced by semant1().
resolve_sym_aliases()
int resolve_sym_aliases (int sptr)
Definition at line 2341 of file symtab.c.
References NOSYM, and sptr.
Referenced by compat_arg_lists(), is_procedure_ptr(), semant1(), and semant3().
restore_implicit()
void restore_implicit (void)
Definition at line 378 of file symtab.c.
References BCOPY, dtimplicit, dtimplicitstack, interr(), and save_dtimplicit.
Referenced by restore_host(), and semant_init().
same_sym_list()
LOGICAL same_sym_list (int list1, int list2)
Return TRUE if these two symi lists have the same sptrs in the same order.
Definition at line 2083 of file symtab.c.
References FALSE, SYMI_NEXT, and SYMI_SPTR.
Referenced by already_to_be_used(), export_public_module(), and find_use_node_in_list().
save_implicit()
void save_implicit (LOGICAL reset)
Definition at line 357 of file symtab.c.
References BCOPY, BZERO, dtimplicit, dtimplicitsize, dtimplicitstack, FALSE, i, NEED, NEW, NULL, reset, save_dtimplicit, and DTIMPL::set.
Referenced by begin_contains(), restore_host(), save_host(), and semant_init().
save_uname()
void save_uname (int newsptr, INT oldnmptr)
can be called after name mangling if the original name needs to be saved in the symbol table, (for instance, for debug symbols.)
Definition at line 3162 of file symtab.c.
References assert, interr(), STB::namavl, and stb.
setimplicit()
void setimplicit (int sptr)
Assign to the indicated symbol table entry, the current implicit dtype.
assign to the indicated symbol table entry, the current implicit dtype.
Definition at line 853 of file symtab.c.
sign_extend()
INT sign_extend (INT val, int width)
Sign extend an integer value of an indicated width (8, 16, 32); value returned is sign extended with respect to the host's int type.
Sign extend an integer value of an indicated width (8, 16, 32); value returned is sign extended with respect to the host's int type.
Definition at line 702 of file symtab.c.
sym_in_sym_list()
LOGICAL sym_in_sym_list (int sptr, int symi)
Return TRUE if sptr is in symi list represented by list.
Definition at line 2069 of file symtab.c.
References FALSE, list, sptr, SYMI_NEXT, SYMI_SPTR, and TRUE.
Referenced by check_doconcurrent_ast(), copy_specifics(), find_in_host(), is_except_in_scope(), is_private_in_scope(), rhs_expr_idx_dependent(), semant3(), sym_in_scope(), and test_scope().
sym_init()
void sym_init (void)
Initialize symbol table for new user program unit.
Initialize symbol table for new user program unit.
Definition at line 72 of file symtab.c.
sym_is_refd()
void sym_is_refd (SPTR sptr)
Definition at line 3925 of file llassem.cpp.
References align_unconstrained(), arg_is_refd(), assn_static_off(), assn_stkoff(), flg, gbl, is_passbyval_dummy(), ISZ_T, MIN_ALIGN_SIZE, FLG::quad, FLG::recursive, RU_PROG, set_ag_ref(), size, size_of(), FLG::smp, sptr, sym_is_refd(), SymConval1, and XBIT.
sym_strsave()
char * sym_strsave (const char * s)
Definition at line 3028 of file symtab.c.
References i, NEW, p, s, and strlen().
Referenced by sym_get_arg_sec(), sym_get_sec(), and trans_mkdescr().
symdentry()
void symdentry (FILE * file, int sptr)
Parameters
file the file
sptr symbol currently being dumped
file the file.
sptr symbol currently being dumped.
Definition at line 1093 of file symtab.c.
symdmp()
void symdmp (FILE * dfil, LOGICAL full)
dump symbol table for debugging purposes. If full == TRUE, dump entire symbol table, otherwise dump symtab beginning with user symbols.
Definition at line 1686 of file symtab.c.
References STB::firstusym, full, sptr, stb, and symdentry().
Referenced by dbg_dump(), dump_old_symbols(), export(), import(), import_inline(), lower(), process_input(), and upper().
symtab_fini()
void symtab_fini (void)
Compilation is finished - deallocate storage, close files, etc.
Definition at line 3271 of file symtab.c.
References AUX::arrdsc_avl, AUX::arrdsc_base, AUX::arrdsc_size, aux, SOC::avail, SOC::base, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, STB::dt, dtimplicitsize, dtimplicitstack, AUX::dvl_avl, AUX::dvl_base, AUX::dvl_size, fini_chartab(), FREE, STB::n_base, STB::n_size, AUX::nml_avl, AUX::nml_base, AUX::nml_size, save_dtimplicit, SOC::size, soc, stb, STG_DELETE, AUX::symi_avl, AUX::symi_base, AUX::symi_size, STB::w_base, and STB::w_size.
Referenced by finish().
symtab_nostandard()
void symtab_nostandard (void)
call this when -nostandard is set; undo what symtab_standard does
Definition at line 3328 of file symtab.c.
References dttypes, TY_BLOG, TY_LOG, TY_LOG8, and TY_SLOG.
Referenced by scan_options().
symtab_standard()
void symtab_standard (void)
call this when -standard is set
Definition at line 3315 of file symtab.c.
References dttypes, TY_BLOG, TY_LOG, TY_LOG8, and TY_SLOG.
Referenced by scan_options().
Variable Documentation
aux
AUX aux extern
Definition at line 33 of file fenddf.c.
dttypes
short dttypes[TY_MAX+1] extern
Referenced by symtab_nostandard(), symtab_standard(), and write_module_as_subroutine().
intrinsic_kwd
const char* intrinsic_kwd[] extern
Referenced by put_inkwd().
switch_base
SWEL* switch_base extern
Definition at line 31 of file fenddf.c.