flang: dinit.h File Reference
flang1/flang1exe/dinit.h File Reference
Fortran declarations needed to use dinitutil.c module.
Classes
struct DREC
Macros
#define DINIT_STARTARY -95
#define DINIT_ENDARY -94
#define DINIT_TYPEDEF -93
#define DINIT_ENDTYPE -92
#define DINIT_LOC -99
#define DINIT_REPEAT -88
#define DINIT_OFFSET -77
#define DINIT_LABEL -33
#define DINIT_STR -67
#define DINIT_ZEROES -66
#define DINIT_FMT -98
#define DINIT_NML -97
#define DINIT_END -96 /* end of a data statement */
Functions
void dinit_init (void)
void dinit_put (int, INT)
DREC * dinit_read (void)
void dinit_fseek (long)
void dinit_fseek_end (void)
long dinit_ftell (void)
void dinit_end (void)
void dinit_newfile (FILE *)
void dinit_save (void)
Save and restore position and mode of the dinit file.
void dinit_restore (void)
void df_dinit_end (void)
void dinit (VAR *, ACL *)
void dinit_no_dinitp (VAR *, ACL *)
void do_dinit (void)
Read in the information a "record" (1 word, 2 pointers) at a time saved by dinit(), and write dinit records for each record.
void df_dinit (VAR *, ACL *)
INT dinit_eval (int)
LOGICAL dinit_ok (int)
determine if the symbol can be legally data initialized
Detailed Description
Fortran declarations needed to use dinitutil.c module.
Definition in file flang1/flang1exe/dinit.h.
Macro Definition Documentation
DINIT_END
#define DINIT_END -96 /* end of a data statement */
Definition at line 30 of file flang1/flang1exe/dinit.h.
DINIT_ENDARY
#define DINIT_ENDARY -94
Definition at line 19 of file flang1/flang1exe/dinit.h.
DINIT_ENDTYPE
#define DINIT_ENDTYPE -92
Definition at line 21 of file flang1/flang1exe/dinit.h.
DINIT_FMT
#define DINIT_FMT -98
Definition at line 28 of file flang1/flang1exe/dinit.h.
DINIT_LABEL
#define DINIT_LABEL -33
Definition at line 25 of file flang1/flang1exe/dinit.h.
DINIT_LOC
#define DINIT_LOC -99
Definition at line 22 of file flang1/flang1exe/dinit.h.
DINIT_NML
#define DINIT_NML -97
Definition at line 29 of file flang1/flang1exe/dinit.h.
DINIT_OFFSET
#define DINIT_OFFSET -77
Definition at line 24 of file flang1/flang1exe/dinit.h.
DINIT_REPEAT
#define DINIT_REPEAT -88
Definition at line 23 of file flang1/flang1exe/dinit.h.
DINIT_STARTARY
#define DINIT_STARTARY -95
Definition at line 18 of file flang1/flang1exe/dinit.h.
DINIT_STR
#define DINIT_STR -67
Definition at line 26 of file flang1/flang1exe/dinit.h.
DINIT_TYPEDEF
#define DINIT_TYPEDEF -93
Definition at line 20 of file flang1/flang1exe/dinit.h.
DINIT_ZEROES
#define DINIT_ZEROES -66
Definition at line 27 of file flang1/flang1exe/dinit.h.
Function Documentation
df_dinit()
void df_dinit (VAR * ivl, ACL * ict)
Parameters
ivl pointer to initializer variable list
ict pointer to initializer constant tree
Definition at line 184 of file dinit.c.
References DBGBIT, dinit_data(), dinit_subs(), dmp_ict(), dmp_ivl(), SEM::dostack, gbl, sem, _acl::sptr, sym_is_dinitd(), and SEM::top.
Referenced by do_dinit(), init_allocatable_typedef_components(), and save_typedef_init().
df_dinit_end()
void df_dinit_end (void)
Definition at line 172 of file dinit.c.
References astb, ASTB::df, fclose(), and NULL.
Referenced by cleanup(), and semfin().
dinit()
void dinit (VAR * ivl, ACL * ict)
Instead of creating dinit records during the processing of data initializations, we need to save information so the records are written at the end of semantic analysis (during semfin). This is necessary for at least a couple of reasons: 1). a record dcl with inits in its STRUCTURE could occur before resolution of its storage class (problematic is SC_CMBLK) 2). with VMS ftn, an array may be initialized (not by implied DO) before resolution of its stype (i.e., its DIMENSION).
The information we need to save is the pointers to the var list and constant tree. This also implies that the getitem areas (4, 5) need to stay around until dinit output.
Definition at line 60 of file dinit.c.
References astb, CNULL, ASTB::df, SEM::dinit_nbr_inits, errfatal(), error(), gbl, VAR::id, mark_dinit(), NULL, VAR::ptr, S_IDENT, sem, tmpfile(), VAR::u, and VAR::varref.
Referenced by dinit_constructor(), dinit_no_dinitp(), gen_dinit(), get_dtype_init_template(), init_sptr_w_acl(), mkvarref(), semant1(), and Writedata().
dinit_end()
void dinit_end (void)
Definition at line 185 of file dinitutl.c.
References DBGBIT, df, fclose(), gbl, mode, and NULL.
Referenced by assem_end(), cleanup(), datastructure_reinit(), and fe_restart().
dinit_eval()
INT dinit_eval (int ast)
Definition at line 1463 of file dinit.c.
References A_OPTYPEG, ast, CNULL, SEM::dinit_error, dinit_eval(), SEM::dostack, DT_ISINT, error(), errsev(), FLANG_FALLTHROUGH, gbl, get_int_cval(), OP_ADD, OP_DIV, OP_MUL, OP_SUB, p, sem, sptr, SYMNAME, SEM::top, and TRUE.
Referenced by _dinit_acl(), compute_size_ido(), dinit_data(), dinit_eval(), dinit_getval(), dinit_subs(), eval_do(), and find_base().
dinit_fseek()
void dinit_fseek (long off)
Definition at line 150 of file dinitutl.c.
References assert, DBGBIT, df, gbl, mode, n, and off.
Referenced by get_struct_from_dsrt2(), lower_data_stmts(), and process_dsrt().
dinit_fseek_end()
void dinit_fseek_end (void)
Definition at line 168 of file dinitutl.c.
References assert, DBGBIT, df, gbl, mode, and n.
Referenced by lower_data_stmts().
dinit_ftell()
long dinit_ftell (void)
Definition at line 142 of file dinitutl.c.
References df, and NULL.
Referenced by dinits(), and end_module().
dinit_init()
void dinit_init (void)
Definition at line 28 of file dinitutl.c.
References mode.
Referenced by datastructure_reinit(), and reinit().
dinit_newfile()
void dinit_newfile (FILE * newdf)
Definition at line 199 of file dinitutl.c.
References df, dinit_end(), and mode.
dinit_no_dinitp()
void dinit_no_dinitp (VAR * ivl, ACL * ict)
Definition at line 163 of file dinit.c.
References dinit(), FALSE, no_dinitp, _acl::no_dinitp, and TRUE.
Referenced by build_typedef_init_tree().
dinit_ok()
LOGICAL dinit_ok (int sptr)
determine if the symbol can be legally data initialized
Definition at line 1602 of file dinit.c.
dinit_put()
void dinit_put (int dtype, INT conval)
Definition at line 34 of file dinitutl.c.
References CNULL, DREC::conval, DBGBIT, df, DREC::dtype, dump_buff(), errfatal(), error(), gbl, mode, n, NULL, t, and tmpfile().
Referenced by _dinit_acl(), _put(), ch_substring(), dinit_name(), dinit_subs(), dinit_val(), dinit_varref(), do_nml(), makezero(), mk_swlist(), mk_swtab_ll(), put_a_init_tree(), put_data(), put_dinit_record(), put_funccount(), put_name(), putzero(), read_init(), and semantio().
dinit_read()
DREC * dinit_read (void)
Definition at line 61 of file dinitutl.c.
References assert, DBGBIT, df, dump_buff(), gbl, mode, n, NULL, and t.
Referenced by dinits(), get_struct_from_dsrt2(), lower_data_stmts(), and process_dsrt().
dinit_restore()
void dinit_restore (void)
Definition at line 222 of file dinitutl.c.
References df, mode, savemode, and savepos.
dinit_save()
void dinit_save (void)
Save and restore position and mode of the dinit file.
Definition at line 212 of file dinitutl.c.
References df, mode, savemode, and savepos.
do_dinit()
void do_dinit (void)
Read in the information a "record" (1 word, 2 pointers) at a time saved by dinit(), and write dinit records for each record.
Definition at line 97 of file dinit.c.