flang: dinit.h File Reference
flang2/flang2exe/dinit.h File Reference
(Fortran) declarations needed to use dinitutil.c module.
#include "gbldefs.h"
#include "symtab.h"
#include <stdio.h>
Classes
struct DREC
Macros
#define DINIT_ENDFILE ((DTYPE)-96)
#define DINIT_STARTARY ((DTYPE)-95)
#define DINIT_ENDARY ((DTYPE)-94)
#define DINIT_TYPEDEF ((DTYPE)-93)
#define DINIT_ENDTYPE ((DTYPE)-92)
#define DINIT_LOC ((DTYPE)-99)
#define DINIT_SLOC ((DTYPE)-91)
#define DINIT_REPEAT ((DTYPE)-88)
#define DINIT_SECT ((DTYPE)-87) /* conval field is sptr to string with section name */
#define DINIT_DATASECT ((DTYPE)-86) /* return to data section */
#define DINIT_OFFSET ((DTYPE)-77)
#define DINIT_LABEL ((DTYPE)-33)
#define DINIT_ZEROES ((DTYPE)-66)
#define DINIT_VPUINSTR ((DTYPE)-55) /* sparc/VPU compiler only */
#define DINIT_COMMENT
#define DINIT_FILL ((DTYPE)-59)
#define DINIT_MASK ((DTYPE)-60)
#define DINIT_ZEROINIT ((DTYPE)-61) /* llvm : use zeroinitializer */
#define DINIT_FUNCCOUNT ((DTYPE)-31) /* gbl.func_count value */
#define DINIT_STRING ((DTYPE)-30)
#define DINIT_PROC ((DTYPE)-42) /* procedure symbol value */
Typedefs
typedef struct DREC DREC
Functions
bool dinit_ok (int sptr)
...
int mk_largest_val (DTYPE dtype)
...
int mk_smallest_val (DTYPE dtype)
...
int mk_unop (int optype, int lop, DTYPE dtype)
...
void dinit (struct VAR *ivl, struct CONST *ict)
...
void dmp_ict (struct CONST *ict, FILE *f)
...
void dmp_ivl (struct VAR *ivl, FILE *f)
...
void do_dinit (void)
...
Detailed Description
(Fortran) declarations needed to use dinitutil.c module.
Definition in file flang2/flang2exe/dinit.h.
Macro Definition Documentation
DINIT_COMMENT
#define DINIT_COMMENT
Value:
                                     ((DTYPE)-44) /* comment string for asm file - the
                                     * DREC.conval field is an int index into
                                     * the getitem_p table (salloc.c) which
                                     * contains the pointer to the string.
                                     */
Definition at line 41 of file flang2/flang2exe/dinit.h.
DINIT_DATASECT
#define DINIT_DATASECT ((DTYPE)-86) /* return to data section */
Definition at line 36 of file flang2/flang2exe/dinit.h.
DINIT_ENDARY
#define DINIT_ENDARY ((DTYPE)-94)
Definition at line 29 of file flang2/flang2exe/dinit.h.
DINIT_ENDFILE
#define DINIT_ENDFILE ((DTYPE)-96)
Definition at line 27 of file flang2/flang2exe/dinit.h.
DINIT_ENDTYPE
#define DINIT_ENDTYPE ((DTYPE)-92)
Definition at line 31 of file flang2/flang2exe/dinit.h.
DINIT_FILL
#define DINIT_FILL ((DTYPE)-59)
Definition at line 42 of file flang2/flang2exe/dinit.h.
DINIT_FUNCCOUNT
#define DINIT_FUNCCOUNT ((DTYPE)-31) /* gbl.func_count value */
Definition at line 46 of file flang2/flang2exe/dinit.h.
DINIT_LABEL
#define DINIT_LABEL ((DTYPE)-33)
Definition at line 38 of file flang2/flang2exe/dinit.h.
DINIT_LOC
#define DINIT_LOC ((DTYPE)-99)
Definition at line 32 of file flang2/flang2exe/dinit.h.
DINIT_MASK
#define DINIT_MASK ((DTYPE)-60)
Definition at line 43 of file flang2/flang2exe/dinit.h.
DINIT_OFFSET
#define DINIT_OFFSET ((DTYPE)-77)
Definition at line 37 of file flang2/flang2exe/dinit.h.
DINIT_PROC
#define DINIT_PROC ((DTYPE)-42) /* procedure symbol value */
Definition at line 48 of file flang2/flang2exe/dinit.h.
DINIT_REPEAT
#define DINIT_REPEAT ((DTYPE)-88)
Definition at line 34 of file flang2/flang2exe/dinit.h.
DINIT_SECT
#define DINIT_SECT ((DTYPE)-87) /* conval field is sptr to string with section name */
Definition at line 35 of file flang2/flang2exe/dinit.h.
DINIT_SLOC
#define DINIT_SLOC ((DTYPE)-91)
Definition at line 33 of file flang2/flang2exe/dinit.h.
DINIT_STARTARY
#define DINIT_STARTARY ((DTYPE)-95)
Definition at line 28 of file flang2/flang2exe/dinit.h.
DINIT_STRING
#define DINIT_STRING ((DTYPE)-30)
Definition at line 47 of file flang2/flang2exe/dinit.h.
DINIT_TYPEDEF
#define DINIT_TYPEDEF ((DTYPE)-93)
Definition at line 30 of file flang2/flang2exe/dinit.h.
DINIT_VPUINSTR
#define DINIT_VPUINSTR ((DTYPE)-55) /* sparc/VPU compiler only */
Definition at line 40 of file flang2/flang2exe/dinit.h.
DINIT_ZEROES
#define DINIT_ZEROES ((DTYPE)-66)
Definition at line 39 of file flang2/flang2exe/dinit.h.
DINIT_ZEROINIT
#define DINIT_ZEROINIT ((DTYPE)-61) /* llvm : use zeroinitializer */
Definition at line 44 of file flang2/flang2exe/dinit.h.
Typedef Documentation
DREC
typedef struct DREC DREC
Function Documentation
dinit()
void dinit (struct VAR * ivl, struct CONST * ict)
...
Definition at line 104 of file dinit.cpp.
dinit_ok()
bool dinit_ok (int sptr)
...
...
Definition at line 1602 of file dinit.c.
dmp_ict()
void dmp_ict (struct CONST * ict, FILE * f)
...
Definition at line 947 of file dinit.cpp.
dmp_ivl()
void dmp_ivl (VAR * ivl, FILE * f)
...
...
Definition at line 1108 of file dinit.c.
do_dinit()
void do_dinit (void)
...
...
Definition at line 97 of file dinit.c.
References assert, astb, BOS_SIZE, BZERO, DBGBIT, ASTB::df, df, df_dinit(), ERR_Fatal, ERR_Severe, FALSE, fclose(), freearea(), gbl, getitem(), ILMB::ilm_base, ILMB::ilmavl, ilmb, init_const, init_list_count, no_dinitp, _acl::no_dinitp, CONST::no_dinitp, NULL, CONST::sptr, and TRUE.
Referenced by semfin(), and upper().
mk_largest_val()
int mk_largest_val (DTYPE dtype)
...
Definition at line 7558 of file ast.c.
References _huge(), and ast_intr().
Referenced by get_minmax_val(), and inline_reduction_f90().
mk_smallest_val()
int mk_smallest_val (DTYPE dtype)
...
Definition at line 7505 of file ast.c.
References _huge(), DTYG, getcon(), mk_cval1(), mk_unop(), OP_SUB, tmp, TY_BINT, TY_DBLE, TY_INT, TY_INT8, TY_QUAD, TY_REAL, TY_SINT, val, and XBIT.
Referenced by get_minmax_val(), and inline_reduction_f90().
mk_unop()
int mk_unop (int optype, int lop, DTYPE dtype)
...
Definition at line 1234 of file ast.c.
References ast, astb, CONVAL2G, convert_int(), DT_INT, DTY, ERR_Severe, hash_unop(), ASTB::i0, interr(), mk_cnst(), mk_cval(), negate_const(), negate_const_be(), OP_ADD, OP_LNOT, OP_LOC, OP_SUB, optype(), TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, and TY_SLOG.
Referenced by _constructf90(), _ptrassign(), _sect(), _transform_func(), ad1ili(), add_byval(), addcomponents(), ast_rewrite(), build_array_ref(), build_conformable_func_node(), build_poly_func_node(), byvalue_ref_arg(), check_alloc_ptr_type(), check_pointer_type(), collapse_assignment(), construct_intrinsic_acl(), convert_subscript_in_expr(), convert_template_instance(), copy_arg_to_seq_tmp(), emit_scatterx_gatherx(), end_or_err(), fill_ast(), fixup_KIND_expr(), gen_allocated_check(), gen_contig_check(), gen_init_unl_poly_desc(), gen_poly_element_arg(), gen_RTE_loc(), genPolyAsn(), get_scalar_in_expr(), init_derived_type(), init_intrin_type_desc(), inline_ast(), inline_reduction_f90(), inline_RTE_set_type(), insert_comm_before(), insert_forall_comm(), log_negation(), lower_data_stmts(), make_sec_from_ast_chk(), mk_binop(), mk_smallest_val(), mkSub(), move_alloc_arg(), mulcomponents(), negatecomponent(), nml_emit_desc(), normalize_forall(), opt_unop(), pointer_squeezer(), reduce_i8add(), reduce_iadd(), ref_pd(), remove_parent_from_ast(), replace_expr(), replace_vector_subscript(), rewrite_allocatable_assignment(), rewrite_block_where(), rewrite_sub_ast(), scalar_communication(), semant1(), semant2(), semant3(), semantio(), set_type_in_descriptor(), shape_comm_in_expr(), transform_all_call(), transform_c_f_pointer(), transform_pure_function(), and unop_init_list().