flang: trace.c File Reference
flang/trace.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
Functions
int __fort_trac_init (void)
Initialization.
void __fort_trac_function_entry (int line, int lines, int cline, char *func, char *file, __CLEN_T funcl, __CLEN_T filel)
void __fort_trac_line_entry (int line)
line entry
void __fort_trac_recv (int cpu, long len)
Update start receive message stats.
void __fort_trac_recv_done (int cpu)
Update done receive message stats.
void __fort_trac_send (int cpu, long len)
Update start send message stats.
void __fort_trac_send_done (int cpu)
Update done send message stats.
void __fort_trac_copy (long len)
Update start bcopy message stats.
void __fort_trac_copy_done (void)
Update done bcopy message stats.
void __fort_trac_function_exit (void)
Function exit
void __fort_trac_term (void)
Termination.
Variables
static int tracing = 0
static int call_level = 0
static char dots [] = "...................."
Function Documentation
__fort_trac_copy()
void __fort_trac_copy (long len)
Update start bcopy message stats.
Parameters
len total length in bytes
Definition at line 98 of file flang/trace.c.
Referenced by __fort_entry_copy().
__fort_trac_copy_done()
void __fort_trac_copy_done (void)
Update done bcopy message stats.
Definition at line 104 of file flang/trace.c.
Referenced by __fort_entry_copy_done().
__fort_trac_function_entry()
void __fort_trac_function_entry (int line, int lines, int cline, char * func, char * file, __CLEN_T funcl, __CLEN_T filel)
Definition at line 41 of file flang/trace.c.
References call_level, dots, func, GET_DIST_LCPU, line, and tracing.
__fort_trac_function_exit()
void __fort_trac_function_exit (void)
Function exit
Definition at line 111 of file flang/trace.c.
References call_level.
Referenced by ENTFTN().
__fort_trac_init()
int __fort_trac_init (void)
Initialization.
Definition at line 16 of file flang/trace.c.
References __fort_abort(), __fort_getopt(), __fort_strtol(), GET_DIST_LCPU, GET_DIST_TCPUS, n, p, q, and tracing.
Referenced by __fort_entry_init().
__fort_trac_line_entry()
void __fort_trac_line_entry (int line)
line entry
Parameters
line - current line number
Definition at line 56 of file flang/trace.c.
Referenced by ENTFTN().
__fort_trac_recv()
void __fort_trac_recv (int cpu, long len)
Update start receive message stats.
Parameters
cpu sending cpu
len total length in bytes
Definition at line 65 of file flang/trace.c.
Referenced by __fort_entry_recv().
__fort_trac_recv_done()
void __fort_trac_recv_done (int cpu)
Update done receive message stats.
Parameters
cpu - sending cpu
Definition at line 73 of file flang/trace.c.
Referenced by __fort_entry_arecv_done(), and __fort_entry_recv_done().
__fort_trac_send()
void __fort_trac_send (int cpu, long len)
Update start send message stats.
Parameters
cpu sending cpu
len total length in bytes
Definition at line 82 of file flang/trace.c.
Referenced by __fort_entry_send().
__fort_trac_send_done()
void __fort_trac_send_done (int cpu)
Update done send message stats.
Parameters
cpu - receiving cpu
Definition at line 90 of file flang/trace.c.
Referenced by __fort_entry_send_done().
__fort_trac_term()
void __fort_trac_term (void)
Termination.
Definition at line 118 of file flang/trace.c.
Referenced by __fort_entry_term().
Variable Documentation
call_level
int call_level = 0 static
Definition at line 12 of file flang/trace.c.
Referenced by __fort_trac_function_entry(), and __fort_trac_function_exit().
dots
char dots[] = "...................." static
Definition at line 37 of file flang/trace.c.
Referenced by __fort_trac_function_entry().
tracing
int tracing = 0 static
Definition at line 11 of file flang/trace.c.
Referenced by __fort_trac_function_entry(), and __fort_trac_init().