flang: main.h File Reference
flang2/flang2exe/main.h File Reference
main exports
#include "gbldefs.h"
#include "error.h"
#include "lz.h"
Functions
void schedule (void)
...
void acc_add_global (void)
char * user_string (void)
...
int bu_auto_inline (void)
...
int export_cgraph_sub (lzhandle *fd)
...
int main (int argc, char *argv[])
...
void add_llvm_uplevel_symbol (int sptr)
FIXME Comments say this belongs in upper.c.
void finish (void)
...
void fixup_llvm_uplevel_symbol (void)
FIXME Comments say this belongs in upper.c.
Detailed Description
main exports
Definition in file flang2/flang2exe/main.h.
Function Documentation
acc_add_global()
void acc_add_global (void)
add_llvm_uplevel_symbol()
void add_llvm_uplevel_symbol (int sptr)
FIXME Comments say this belongs in upper.c.
Definition at line 1039 of file main.cpp.
References _add_llvm_uplevel_symbol(), and sptr.
Referenced by read_symbol().
bu_auto_inline()
int bu_auto_inline (void)
...
export_cgraph_sub()
int export_cgraph_sub (lzhandle * fd)
...
finish()
void finish ()
...
...
...
\Brief Write summary line to terminal, and exit.
Definition at line 1320 of file main.c.
References assemble_end(), s_1_s::basis, ccff_close(), ccff_filename, DBGBIT, destroy_action_map(), FLG::es, exitf(), fclose(), FILES_CLOSE, flg, free_getitem_p(), freearea(), g_1_s::frsprd, FTN_HAS_INIT, g_1, gbl, hashpt, s4_s::item, g_1_s::lftuse, ll_unlink_parfiles(), maxfilsev, s4_s::nextt, g_1_s::nprods, NULL, s_1_s::nullnt, FLG::object, objectfile, phase_dump_map, g_1_s::prdind, g_1_s::prodcn, s_1_s::red, reptime(), g_1_s::rgtuse, s1_1, s4, s_1, scrtch, FLG::smp, s1_1_s::sstore, s1_1_s::sthead, summary(), s_1_s::thedpt, s_1_s::tran, and g_1_s::vocab.
Referenced by error(), init(), and main().
fixup_llvm_uplevel_symbol()
void fixup_llvm_uplevel_symbol (void)
FIXME Comments say this belongs in upper.c.
Definition at line 1047 of file main.cpp.
References _fixup_llvm_uplevel_symbol().
Referenced by upper().
main()
int main (int argc, char * argv[])
...
...
Parameters
argc number of command-line arguments \pram argv array of command-line argument strings
...
Definition at line 28 of file fs_cos_16_b.c.
References addfile(), ASTTMPFILE, buff, cg_llvm_end(), checkmode, collectIncludePaths(), copy_file(), DBGBIT, debugfunconly, do_AT_line(), do_CG_line(), do_IL_line(), do_SI_line(), dodebug, error(), errwarn(), fclose(), FILE, finish(), flg, FTN_HAS_INIT, gbl, get_input_line(), get_rutime(), i, ilis, IN3, init(), init_global_ilm_mode(), init_test(), introduces_ILI(), IPA_COLLECTION_ENABLED, IPA_INHERIT_ENABLED, ipa_init(), j, linenum, ll_unlink_parfiles(), match(), max_ili_num, MAX_OPNDS, mytmpfile, name, NULL, numoperations, ompaccel_init(), FLG::omptarget, opcode_num, open_files(), open_input_file(), operation, FLG::opt, OUT2, outfile, parseargs(), proc_sym(), process_input(), process_stb_file(), processed, putdecls(), FLG::recursive, saveoptflag, saverecursive, savevectflag, savex8flag, schinfo, size, FLG::smp, STB_UPPER, stb_upper_init(), upper_init(), FLG::vect, write_ast(), FLG::x, XBIT, yyin, and yylex().
schedule()
void schedule (void)
...
...
Definition at line 17 of file dummy.c.
References llvm_tag::abi_info, ad_instr(), analyze_ret_info(), assem_data(), assem_end(), assert, assign_fortran_storage_classes(), FLG::autoinline, BIH_CS, BIH_EN, BIH_FINDEX, BIH_HEAD, BIH_ILTFIRST, BIH_ILTLAST, BIH_LABEL, BIH_LAST, BIH_LINENO, BIH_NEXT, BIH_NODEPCHK, BIH_NODEPCHK2, BIH_NOMERGE, BIH_NOSIMD, BIH_NOUNROLL, BIH_PAR, BIH_SIMD, BIH_TAIL, BIH_TASK, BIH_UNROLL, BIH_UNROLL_COUNT, BIH_VECTORLENGTH_ENABLED, BIH_VECTORLENGTH_SCALABLE, build_csed_list(), build_unused_global_define_from_params(), cached_access_group_metadata, CG_cpu_compile, cg_llvm_init(), CG_MEDTERM_AREA, cgmain_init_call(), check_for_loop_directive(), cleanup_unneeded_sincos_calls(), clear_csed_list(), clear_prescan_complex_list(), clear_rw_access_grp(), close_pragma(), cons_loop_id_md(), cons_nounroll_metadata(), cons_novectorize_metadata(), cons_unroll_count_metadata(), cons_unroll_metadata(), cons_vec_always_metadata(), consTempMap(), construct_vectorlength_metadata(), cpu_llvm_module, csedList, llvm_tag::curr_func, llvm_tag::curr_instr, current_module, DBGBIT, DBGTRACE1, FLG::debug, LL_Module::debug_info, FLG::depchk, dmpili(), dmpilt(), DT_CPTR, dumpblocks(), entry_bih, ERR_Fatal, expr_id, find_last_executable(), finish_routine(), first, fix_nodepchk_flag(), FLANG_FALLTHROUGH, flg, fma_rewrite(), freearea(), FTN_HOST_REG, funcHasNoDepChk(), funcId, gbl, GBL_CURRFUNC, gcTempMap(), gen_instr(), gen_llvm_expr(), gen_llvm_fence_instruction(), get_entries_argnum(), get_llvm_version(), get_local_overlap_size(), get_master_sptr(), get_return_type(), gpu_llvm_module, has_multiple_entries(), hashmap_clear(), llvm_tag::homed_args, i, I_NONE, FLG::ieee, ignore_simd_block(), IL_NAME, IL_RES, IL_TYPE, ILI_OPC, ILI_OPND, ILIA_DP, ILIA_SP, ilib, ilis, ilt, ILT_BR, ILT_DELETE, ILT_EX, ILT_ILIP, ILT_LINENO, ILT_NEXT, ILT_ST, ILTY_ARTH, ILTY_CONS, ILTY_DEFINE, ILTY_LOAD, ILTY_MOVE, ILTY_OTHER, ILTY_STORE, FLG::inliner, insert_entry_label(), insert_jump_entry_instr(), insert_llvm_prefetch(), Instructions, is_freeili_opcode(), is_mvili_opcode(), is_rgdfili_opcode(), llvm_tag::last_instr, ll_abi_for_func_sptr(), ll_abi_function_type(), LL_ABI_HAS_SRET, ll_create_device_function_from_type(), ll_create_distinct_md_node(), ll_create_function_from_type(), ll_create_pointer_value_from_type(), ll_destroy_function(), ll_dfile, ll_extend_md_node(), ll_get_md_null, LL_INTERNAL_LINKAGE, LL_MDREF_IS_NULL, LL_NO_LINKAGE, LL_PlainMDNode, ll_proto_add_sptr(), ll_reset_gtid(), LL_Version_3_7, ll_write_local_objects(), lldbg_cleanup_missing_bounds(), lldbg_emit_line(), lldbg_emit_lv_list(), lldbg_emit_subprogram(), lldbg_get_di_routine_idx(), lldbg_get_line(), lldbg_reset_dtype_array(), lldbg_set_func_ptr(), llvm_file(), llvm_info, LOOP_BACKEDGE_FLAG, make_label_op(), make_lltype_from_dtype(), make_stmt(), mark_rw_access_grp(), NULL, LL_Module::omnipotentPtr, FLG::omptarget, open_pragma(), ILIINFO::oprs, FLG::opt, optimize_block(), optype(), INSTR_TAG::prev, print_entry_subroutine(), process_formal_arguments(), process_ll_abi_func_ftn_mod(), process_params(), process_sptr(), processOutlinedByConcur(), redundantLdLdElim(), remove_dead_instrs(), remove_dead_sincos_calls(), remove_from_csed_list(), ret_info, routine_count, sched_instructions(), sincos_clear_all_args(), sincos_seen(), FLG::smp, SNAME, sptr, SPTR_NULL, ret_tag::sret_sptr, stb_process_routine_parameters(), STMT_BR, STMT_CALL, STMT_DECL, STMT_LABEL, STMT_RET, STMT_SMOVE, STMT_ST, STMT_SZERO, store_for_homing(), store_llvm_localfptr(), SYMNAME, undo_recip_div(), void(), widenAddressArith(), write_ftn_typedefs(), write_global_and_static_defines(), write_instructions(), write_libomtparget(), write_local_overlap(), write_routine_definition(), FLG::x, XBIT, XBIT_GENERATE_SCALAR_FMA, and XBIT_NOUNIFORM.
Referenced by process_input().
user_string()
char * user_string (void)
...