flang: trace.c File Reference
flangrti/trace.c File Reference
#include <signal.h>
#include <stdlib.h>
#include <string.h>
#include "llcrit.h"
#include "stdioInterf.h"
Classes
struct opts
Macros
#define T_DEBUG 1 /* enable just in time debugging */
#define T_TRACE 2 /* enable stack traceback */
#define T_SIGNAL 4 /* enable signal handlers */
#define T_ABORT 8 /* enable abort call */
#define T_TEST 16 /* enable test code */
Functions
void dbg_stop_before_exit (void)
void __abort (int sv, const char *msg)
void __abort_err (char *msg)
void __abort_init (char *path)
void __ctrl_init (void)
char * __abort_image (void)
Variables
static struct opts opts []
static int tracopt = 0
static char * fn
Macro Definition Documentation
T_ABORT
#define T_ABORT 8 /* enable abort call */
Definition at line 20 of file flangrti/trace.c.
T_DEBUG
#define T_DEBUG 1 /* enable just in time debugging */
Definition at line 17 of file flangrti/trace.c.
T_SIGNAL
#define T_SIGNAL 4 /* enable signal handlers */
Definition at line 19 of file flangrti/trace.c.
T_TEST
#define T_TEST 16 /* enable test code */
Definition at line 21 of file flangrti/trace.c.
T_TRACE
#define T_TRACE 2 /* enable stack traceback */
Definition at line 18 of file flangrti/trace.c.
Function Documentation
__abort()
void __abort (int sv, const char * msg)
Definition at line 66 of file flangrti/trace.c.
References __abort_trace(), __io_stderr(), dbg_stop_before_exit(), fflush(), getenv(), msg(), n, NULL, p, T_ABORT, T_DEBUG, T_TEST, T_TRACE, and tracopt.
Referenced by __abort_err(), __abort_sig_hand(), __fort_abortx(), __fort_check_map(), __fort_getmap(), and __getfile3f().
__abort_err()
void __abort_err (char * msg)
Definition at line 118 of file flangrti/trace.c.
References __abort(), __io_stderr(), msg(), and NULL.
__abort_image()
char * __abort_image (void)
Definition at line 194 of file flangrti/trace.c.
References fn.
__abort_init()
void __abort_init (char * path)
Definition at line 130 of file flangrti/trace.c.
References __abort_sig_init(), __io_stderr(), fn, getenv(), n, neg(), NULL, opts::opt, opts, p, path, strlen(), T_SIGNAL, tracopt, and opts::val.
__ctrl_init()
void __ctrl_init (void)
Definition at line 187 of file flangrti/trace.c.
dbg_stop_before_exit()
void dbg_stop_before_exit (void)
Definition at line 46 of file flangrti/trace.c.
Referenced by __abort().
Variable Documentation
fn
char* fn static
Definition at line 41 of file flangrti/trace.c.
Referenced by __abort_image(), __abort_init(), __fort_global_reduce(), __fort_par_open(), __fort_par_unlink(), _nextline(), ad1mathfunc_cmplx(), ad2mathfunc_cmplx(), add_ctor(), basenam(), direct_xf(), direct_yf(), ENT3F(), gen_sincos(), get_lexical_block_info(), getLexBlock_notCurrentFunc(), lldbg_get_var_line(), tr_conval2g(), tr_conval2p(), and vect_math().
opts
struct opts opts[] static
Initial value:
= {{"debug", T_DEBUG | T_SIGNAL},
                             {"trace", T_TRACE | T_SIGNAL},
                             {"signal", T_SIGNAL},
                             {"abort", T_ABORT},
                             {"test", T_TEST},
                             {NULL, 0}}
Definition at line 30 of file flangrti/trace.c.
Referenced by __abort_init().
tracopt
int tracopt = 0 static
Definition at line 39 of file flangrti/trace.c.
Referenced by __abort(), and __abort_init().