flang: flangmain.c File Reference
flangmain.c File Reference
#include "FuncArgMacros.h"
Functions
char ** __io_environ ()
void __io_set_argc (int)
void __io_set_argv (char **)
int main (int argc, char **argv)
Function Documentation
__io_environ()
char ** __io_environ ()
Definition at line 37 of file iostdinit.c.
References environ.
Referenced by __fort_initarg(), and main().
__io_set_argc()
void __io_set_argc (int v)
Definition at line 38 of file ioargs.c.
Referenced by main().
__io_set_argv()
void __io_set_argv (char ** v)
Definition at line 22 of file ioargs.c.
References __argv_save.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 20 of file flangmain.c.
References __io_environ(), __io_set_argc(), __io_set_argv(), ENTF90, and i.
Referenced by lldbg_create_compile_unit_mdnode().