flang: fpcvt.c File Reference
flang/fpcvt.c File Reference
#include <string.h>
#include <ctype.h>
#include <fenv.h>
#include "float128.h"
#include "fioMacros.h"
#include "stdioInterf.h"
#include "fio_fcb_flags.h"
#include <errno.h>
Classes
union ieee
struct UFP
struct etypdat_tag
Macros
#define IEEE64_SUBNORMAL(a) (a.v.e == 0 && (a.v.hm != 0L || a.v.lm != 0L))
#define FP_NOERR 0
#define FP_ILLEGAL_INPUT_OR_NAN -1
#define FP_OVERFLOW_ERROR -2
#define FP_UNDERFLOW_ERROR -3
#define FP_UNDEFINED_ERROR -4
#define EXPONENT_BIAS_D 0x3ff
#define EXPONENT_BIAS_Q 0x3fff
#define INFINITY_STR_LEN 8 /* len of strings "Infinity". */
#define SUBSCRIPT_2 2 /* subscript is 2 */
#define SUBSCRIPT_3 3 /* subscript is 3 */
#define BYTCOPY(p, q, n) memcpy((char *)(p), (char *)(q), n)
#define FPE_NOERR FP_NOERR /* Everything OK */
#define FPE_FPOVF FP_OVERFLOW_ERROR /* floating point overflow */
#define FPE_FPUNF FP_UNDERFLOW_ERROR /* floating point underflow */
#define FPE_IOVF FP_OVERFLOW_ERROR /* integer overflow (fix/dfix only) */
#define FPE_INVOP FP_ILLEGAL_INPUT_OR_NAN /* invalid operand */
#define FPE_DIVZ FP_OVERFLOW_ERROR /* reciprocal of zero */
#define NE 10
#define NI (NE + 3)
#define E 1
#define M 2
#define NBITS ((NI - 4) * 16)
#define NDEC (NBITS * 8 / 27)
#define EXONE (0x3fff)
#define NANS
#define SING FPE_DIVZ
#define DOMAIN FPE_INVOP
#define UNDERFLOW FPE_FPUNF
#define OVERFLOW FPE_FPOVF
#define NTEN 12
#define MAXP 4096
Typedefs
typedef long INT
typedef unsigned long UINT
typedef double IEEE64
typedef unsigned short int USHORT
typedef USHORT U[NE]
typedef int IEEE128[4]
Enumerations
enum VAL {
ZERO , NIL , NORMAL , BIG ,
INFIN , NAN , DIVZ , SUBNORMAL ,
ZERO , NIL , NORMAL , BIG ,
INFIN , NAN , DIVZ , SUBNORMAL ,
ZERO , NIL , NORMAL , BIG ,
INFIN , NAN , DIVZ
}
Functions
static int ufpdnorm (UFP *, int)
static void mtherr (const char *, int)
static void fperror (int x)
static void manshftr (INT *m, int n)
static void manshftl (INT *m, int n)
static void manadd (INT *m1, INT *m2)
static void manrnd (INT *m, int bits)
static void manmul (INT *m1, INT *m2)
static void ufpnorm (UFP *u)
static void ufprnd (UFP *u, int bits)
static void ufpxten (UFP *u, int exp)
static void ufptod (UFP *u, IEEE64 *r)
static int atoxi (char *s, INT *i, int n, int base)
static void atoui64 (char *s, INT *m, int n, INT *exp)
static void atoxufp (char *s, UFP *u, char **p)
double __fortio_strtod (char *s, char **p)
int __fenv_fegetround ()
static void writefmt (char *fmt, int prec, char c, int is_quad)
char * __fortio_ecvt (__BIGREAL_T lvalue, int width, int ndigit, int *decpt, int *sign, int round, int is_quad)
char * __fortio_fcvt (__BIGREAL_T lv, int width, int prec, int sf, int *decpt, int *sign, int round, int is_quad)
void etoasc (USHORT *x, char *string, int ndigs, char let)
void e113toe (IEEE128 pe, USHORT *y)
char * __fortio_lldecvt (int num[4], int ndigit, int *decpt, int *sign)
char * __fortio_lldfcvt (int num[4], int ndigit, int *decpt, int *sign)
int eisnan (USHORT x[])
void emov (USHORT *a, USHORT *b)
int ecmp (USHORT *a, USHORT *b)
void ediv (USHORT *a, USHORT *b, USHORT *c)
void efloor (USHORT *x, USHORT *y)
void emul (USHORT *a, USHORT *b, USHORT *c)
void emovi (USHORT *a, USHORT *b)
int emovo (USHORT *a, USHORT *b)
void emovz (USHORT *a, USHORT *b)
void eiremain (USHORT *den, USHORT *num)
void eaddm (USHORT *x, USHORT *y)
void eshdn1 (USHORT *x)
void eshup1 (USHORT *x)
void ecleaz (USHORT *xi)
int eshift (USHORT *x, int sc)
void eclear (USHORT *x)
void einfin (USHORT *x)
void eneg (USHORT *x)
void enan (void *out, int size)
int enormlz (USHORT *x)
int eisinf (USHORT *x)
int eisneg (USHORT *x)
int edivm (USHORT *den, USHORT *num)
void emdnorm (USHORT *s, int lost, int subflg, INT exp, int rcntrl)
void esub (USHORT *a, USHORT *b, USHORT *c)
int emulm (USHORT *a, USHORT *b)
int eiisnan (USHORT x[])
int ecmpm (USHORT *a, USHORT *b)
void esubm (USHORT *x, USHORT *y)
void eshup8 (USHORT *x)
void eshup6 (USHORT *x)
void eshdn8 (USHORT *x)
void eshdn6 (USHORT *x)
void m16m (USHORT a, USHORT *b, USHORT *c)
void ecleazs (USHORT *xi)
int eisnan (USHORT *x)
static void eadd1 (USHORT *a, USHORT *b, USHORT *c)
int eiisnan (USHORT *x)
Variables
static INT ftab1 [29][3]
static INT ftab2 [25][3]
struct etypdat_tag etypdat
static USHORT etens [NTEN+1][NE]
static USHORT emtens [NTEN+1][NE]
static USHORT bmask []
static IEEE128 nan113
static int nan53 [2] = {0x7fffffff, (int)0xffffffff}
static int nan24 = 0x7fffffff
static int rlast = -1
static int rw = 0
static USHORT rmsk = 0
static USHORT rmbit = 0
static USHORT rebit = 0
static int re = 0
static USHORT rbit [NI] = {0, 0, 0, 0, 0, 0, 0, 0}
static int subflg = 0
Macro Definition Documentation
BYTCOPY
#define BYTCOPY (p, q, n) memcpy((char *)(p), (char *)(q), n)
Definition at line 1756 of file flang/fpcvt.c.
DOMAIN
#define DOMAIN FPE_INVOP
Definition at line 1824 of file flang/fpcvt.c.
E
#define E 1
Definition at line 1775 of file flang/fpcvt.c.
EXONE
#define EXONE (0x3fff)
Definition at line 1789 of file flang/fpcvt.c.
EXPONENT_BIAS_D
#define EXPONENT_BIAS_D 0x3ff
Definition at line 789 of file flang/fpcvt.c.
EXPONENT_BIAS_Q
#define EXPONENT_BIAS_Q 0x3fff
Definition at line 790 of file flang/fpcvt.c.
FP_ILLEGAL_INPUT_OR_NAN
#define FP_ILLEGAL_INPUT_OR_NAN -1
Definition at line 70 of file flang/fpcvt.c.
FP_NOERR
#define FP_NOERR 0
Definition at line 69 of file flang/fpcvt.c.
FP_OVERFLOW_ERROR
#define FP_OVERFLOW_ERROR -2
Definition at line 71 of file flang/fpcvt.c.
FP_UNDEFINED_ERROR
#define FP_UNDEFINED_ERROR -4
Definition at line 73 of file flang/fpcvt.c.
FP_UNDERFLOW_ERROR
#define FP_UNDERFLOW_ERROR -3
Definition at line 72 of file flang/fpcvt.c.
FPE_DIVZ
#define FPE_DIVZ FP_OVERFLOW_ERROR /* reciprocal of zero */
Definition at line 1766 of file flang/fpcvt.c.
FPE_FPOVF
#define FPE_FPOVF FP_OVERFLOW_ERROR /* floating point overflow */
Definition at line 1762 of file flang/fpcvt.c.
FPE_FPUNF
#define FPE_FPUNF FP_UNDERFLOW_ERROR /* floating point underflow */
Definition at line 1763 of file flang/fpcvt.c.
FPE_INVOP
#define FPE_INVOP FP_ILLEGAL_INPUT_OR_NAN /* invalid operand */
Definition at line 1765 of file flang/fpcvt.c.
FPE_IOVF
#define FPE_IOVF FP_OVERFLOW_ERROR /* integer overflow (fix/dfix only) */
Definition at line 1764 of file flang/fpcvt.c.
FPE_NOERR
#define FPE_NOERR FP_NOERR /* Everything OK */
Definition at line 1761 of file flang/fpcvt.c.
IEEE64_SUBNORMAL
#define IEEE64_SUBNORMAL (a) (a.v.e == 0 && (a.v.hm != 0L || a.v.lm != 0L))
Definition at line 61 of file flang/fpcvt.c.
INFINITY_STR_LEN
#define INFINITY_STR_LEN 8 /* len of strings "Infinity". */
Definition at line 791 of file flang/fpcvt.c.
M
#define M 2
Definition at line 1778 of file flang/fpcvt.c.
MAXP
#define MAXP 4096
Definition at line 1979 of file flang/fpcvt.c.
NANS
#define NANS
Definition at line 1822 of file flang/fpcvt.c.
NBITS
#define NBITS ((NI - 4) * 16)
Definition at line 1781 of file flang/fpcvt.c.
NDEC
#define NDEC (NBITS * 8 / 27)
Definition at line 1786 of file flang/fpcvt.c.
NE
#define NE 10
Definition at line 1769 of file flang/fpcvt.c.
NI
#define NI (NE + 3)
Definition at line 1772 of file flang/fpcvt.c.
NTEN
#define NTEN 12
Definition at line 1978 of file flang/fpcvt.c.
OVERFLOW
#define OVERFLOW FPE_FPOVF
Definition at line 1826 of file flang/fpcvt.c.
SING
#define SING FPE_DIVZ
Definition at line 1823 of file flang/fpcvt.c.
SUBSCRIPT_2
#define SUBSCRIPT_2 2 /* subscript is 2 */
Definition at line 792 of file flang/fpcvt.c.
SUBSCRIPT_3
#define SUBSCRIPT_3 3 /* subscript is 3 */
Definition at line 793 of file flang/fpcvt.c.
UNDERFLOW
#define UNDERFLOW FPE_FPUNF
Definition at line 1825 of file flang/fpcvt.c.
Typedef Documentation
IEEE128
typedef int IEEE128[4]
Definition at line 1795 of file flang/fpcvt.c.
IEEE64
typedef double IEEE64
Definition at line 52 of file flang/fpcvt.c.
INT
typedef long INT
Definition at line 50 of file flang/fpcvt.c.
U
typedef USHORT U[NE]
Definition at line 1793 of file flang/fpcvt.c.
UINT
typedef unsigned long UINT
Definition at line 51 of file flang/fpcvt.c.
USHORT
typedef unsigned short int USHORT
Definition at line 1791 of file flang/fpcvt.c.
Enumeration Type Documentation
VAL
enum VAL
Enumerator
ZERO
NIL
NORMAL
BIG
INFIN
NAN
DIVZ
SUBNORMAL
ZERO
NIL
NORMAL
BIG
INFIN
NAN
DIVZ
SUBNORMAL
ZERO
NIL
NORMAL
BIG
INFIN
NAN
DIVZ
Definition at line 53 of file flang/fpcvt.c.
Function Documentation
__fenv_fegetround()
int __fenv_fegetround ()
Definition at line 470 of file fltfenv.c.
Referenced by __fortio_ecvt(), and __fortio_fcvt().
__fortio_ecvt()
char * __fortio_ecvt (__BIGREAL_T lvalue, int width, int ndigit, int * decpt, int * sign, int round, int is_quad)
Definition at line 796 of file flang/fpcvt.c.
References __fenv_fegetround(), ieee::d, ieee::e, EXPONENT_BIAS_D, EXPONENT_BIAS_Q, FIO_COMPATIBLE, FIO_DOWN, FIO_NEAREST, FIO_PROCESSOR_DEFINED, FIO_UP, FIO_ZERO, FP_UNDEFINED_ERROR, ieee::hm, i, idx, INFINITY_STR_LEN, j, ieee::lm, mtherr(), NULL, round(), ieee::s, sign, SUBSCRIPT_2, tmp, ieee::v, value(), and writefmt().
__fortio_fcvt()
char * __fortio_fcvt (__BIGREAL_T lv, int width, int prec, int sf, int * decpt, int * sign, int round, int is_quad)
Definition at line 1186 of file flang/fpcvt.c.
References __fenv_fegetround(), ieee::d, ieee::e, EXPONENT_BIAS_D, EXPONENT_BIAS_Q, FIO_COMPATIBLE, FIO_DOWN, FIO_NEAREST, FIO_PROCESSOR_DEFINED, FIO_UP, FIO_ZERO, ieee::hm, ieee::i, i, idx, INFINITY_STR_LEN, j, ieee::lm, lv, NULL, round(), ieee::s, sign, SUBSCRIPT_2, SUBSCRIPT_3, tmp, ieee::v, and writefmt().
__fortio_lldecvt()
char * __fortio_lldecvt (int num[4], int ndigit, int * decpt, int * sign)
Definition at line 1831 of file flang/fpcvt.c.
References c, e, e113toe(), etoasc(), i, j, num, and sign.
Referenced by __fortio_lldfcvt().
__fortio_lldfcvt()
char * __fortio_lldfcvt (int num[4], int ndigit, int * decpt, int * sign)
Definition at line 1894 of file flang/fpcvt.c.
References __fortio_lldecvt(), b, num, and sign.
__fortio_strtod()
double __fortio_strtod (char * s, char ** p)
Definition at line 725 of file flang/fpcvt.c.
References atoxufp(), d, exp, p, q, s, ufptod(), and ufpxten().
atoui64()
static void atoui64 (char * s, INT * m, int n, INT * exp) static
Definition at line 592 of file flang/fpcvt.c.
References end, exp, hi, lo, m, n, and s.
Referenced by atoxufp().
atoxi()
static int atoxi (char * s, INT * i, int n, int base) static
Definition at line 502 of file flang/fpcvt.c.
References base, end, i, n, s, sign, and value().
Referenced by atoxufp().
atoxufp()
static void atoxufp (char * s, UFP * u, char ** p) static
Definition at line 643 of file flang/fpcvt.c.
References atoui64(), atoxi(), BIG, exp, NORMAL, p, s, sign, start, and ZERO.
Referenced by __fortio_strtod().
e113toe()
void e113toe (IEEE128 pe, USHORT * y)
Definition at line 1947 of file flang/fpcvt.c.
References E, ecleaz(), emovo(), eshift(), M, NI, p, r, void(), and y.
Referenced by __fortio_lldecvt().
eadd1()
static void eadd1 (USHORT * a, USHORT * b, USHORT * c) static
Definition at line 3389 of file flang/fpcvt.c.
References a, b, E, eaddm(), eclear(), ecmpm(), emdnorm(), emovi(), emovo(), emovz(), eshift(), eshup1(), esubm(), i, j, k, lt, NBITS, NI, subflg, and void().
Referenced by esub().
eaddm()
void eaddm (USHORT * x, USHORT * y)
Definition at line 2770 of file flang/fpcvt.c.
References a, carry(), i, M, NI, x, and y.
Referenced by eadd1(), emdnorm(), emulm(), and etoasc().
eclear()
void eclear (USHORT * x)
Definition at line 2914 of file flang/fpcvt.c.
References i, NE, and x.
Referenced by eadd1(), ediv(), efloor(), and emul().
ecleaz()
void ecleaz (USHORT * xi)
Definition at line 2845 of file flang/fpcvt.c.
References i, NI, and xi.
Referenced by e113toe(), eiremain(), and emdnorm().
ecleazs()
void ecleazs (USHORT * xi)
Definition at line 3696 of file flang/fpcvt.c.
References i, NI, and xi.
Referenced by emdnorm().
ecmp()
int ecmp (USHORT * a, USHORT * b)
Definition at line 2463 of file flang/fpcvt.c.
References a, b, emovi(), i, NI, p, and q.
Referenced by etoasc().
ecmpm()
int ecmpm (USHORT * a, USHORT * b)
Definition at line 3524 of file flang/fpcvt.c.
References a, b, i, M, and NI.
Referenced by eadd1(), edivm(), and eiremain().
ediv()
void ediv (USHORT * a, USHORT * b, USHORT * c)
Definition at line 2516 of file flang/fpcvt.c.
References a, b, E, eclear(), edivm(), einfin(), emdnorm(), emovi(), emovo(), enormlz(), EXONE, i, lt, mtherr(), NE, NI, SING, and void().
Referenced by etoasc().
edivm()
int edivm (USHORT * den, USHORT * num)
Definition at line 3119 of file flang/fpcvt.c.
References ecmpm(), etypdat_tag::equot, eshdn1(), eshup6(), esubm(), etypdat, i, j, M, m16m(), NI, num, and p.
Referenced by ediv().
efloor()
void efloor (USHORT * x, USHORT * y)
Definition at line 2581 of file flang/fpcvt.c.
References bmask, e, eclear(), emov(), etypdat_tag::eone, esub(), etypdat, EXONE, f, i, NBITS, NE, p, x, and y.
Referenced by etoasc().
eiisnan() [1/2]
int eiisnan (USHORT * x)
Definition at line 3502 of file flang/fpcvt.c.
References E, i, M, NI, and x.
eiisnan() [2/2]
int eiisnan (USHORT x[])
einfin()
void einfin (USHORT * x)
Definition at line 2931 of file flang/fpcvt.c.
References etypdat, i, NBITS, NE, etypdat_tag::rndprc, and x.
Referenced by ediv().
eiremain()
void eiremain (USHORT * den, USHORT * num)
Definition at line 2740 of file flang/fpcvt.c.
References E, ecleaz(), ecmpm(), emdnorm(), enormlz(), etypdat_tag::equot, eshup1(), esubm(), etypdat, j, ld, NI, and num.
Referenced by etoasc().
eisinf()
int eisinf (USHORT * x)
Definition at line 3091 of file flang/fpcvt.c.
References NE, and x.
eisnan() [1/2]
int eisnan (USHORT * x)
Definition at line 2431 of file flang/fpcvt.c.
eisnan() [2/2]
int eisnan (USHORT x[])
eisneg()
int eisneg (USHORT * x)
Definition at line 3104 of file flang/fpcvt.c.
References NE, and x.
emdnorm()
void emdnorm (USHORT * s, int lost, int subflg, INT exp, int rcntrl)
Definition at line 3204 of file flang/fpcvt.c.
References eaddm(), ecleaz(), ecleazs(), enormlz(), eshdn1(), eshift(), eshup1(), etypdat, exp, i, j, M, NBITS, NI, r, rbit, re, rebit, rlast, rmbit, rmsk, etypdat_tag::rndprc, rw, s, and subflg.
Referenced by eadd1(), ediv(), eiremain(), and emul().
emov()
void emov (USHORT * a, USHORT * b)
Definition at line 2444 of file flang/fpcvt.c.
References a, b, i, and NE.
Referenced by efloor(), and etoasc().
emovi()
void emovi (USHORT * a, USHORT * b)
Definition at line 2676 of file flang/fpcvt.c.
References a, b, i, NE, p, and q.
Referenced by eadd1(), ecmp(), ediv(), emul(), and etoasc().
emovo()
int emovo (USHORT * a, USHORT * b)
Definition at line 2704 of file flang/fpcvt.c.
References a, b, i, NE, p, and q.
Referenced by e113toe(), eadd1(), ediv(), emul(), and etoasc().
emovz()
void emovz (USHORT * a, USHORT * b)
Definition at line 2729 of file flang/fpcvt.c.
References a, b, i, and NI.
Referenced by eadd1(), and etoasc().
emul()
void emul (USHORT * a, USHORT * b, USHORT * c)
Definition at line 2624 of file flang/fpcvt.c.
References a, b, E, eclear(), emdnorm(), emovi(), emovo(), emulm(), enormlz(), EXONE, i, j, lt, NI, and void().
Referenced by etoasc().
emulm()
int emulm (USHORT * a, USHORT * b)
Definition at line 3464 of file flang/fpcvt.c.
References a, b, eaddm(), etypdat_tag::equot, eshdn6(), etypdat, for(), i, j, M, m16m(), NI, p, and q.
Referenced by emul().
enan()
void enan (void * out, int size)
Definition at line 2976 of file flang/fpcvt.c.
References BYTCOPY, DOMAIN, i, mtherr(), n, nan, nan113, nan24, nan53, NBITS, NE, NI, p, and size.
eneg()
void eneg (USHORT * x)
Definition at line 2961 of file flang/fpcvt.c.
References NE, and x.
enormlz()
int enormlz (USHORT * x)
Definition at line 3026 of file flang/fpcvt.c.
References eshdn1(), eshdn8(), eshup1(), eshup6(), eshup8(), M, mtherr(), NBITS, OVERFLOW, p, UNDERFLOW, and x.
Referenced by ediv(), eiremain(), emdnorm(), and emul().
eshdn1()
void eshdn1 (USHORT * x)
Definition at line 2796 of file flang/fpcvt.c.
References bits, i, M, NI, and x.
Referenced by edivm(), emdnorm(), enormlz(), eshift(), and etoasc().
eshdn6()
void eshdn6 (USHORT * x)
Definition at line 3638 of file flang/fpcvt.c.
References i, M, NI, p, and x.
Referenced by emulm(), and eshift().
eshdn8()
void eshdn8 (USHORT * x)
Definition at line 3616 of file flang/fpcvt.c.
References i, M, NI, and x.
Referenced by enormlz(), and eshift().
eshift()
int eshift (USHORT * x, int sc)
Definition at line 2858 of file flang/fpcvt.c.
References eshdn1(), eshdn6(), eshdn8(), eshup1(), eshup6(), eshup8(), NI, p, and x.
Referenced by e113toe(), eadd1(), and emdnorm().
eshup1()
void eshup1 (USHORT * x)
Definition at line 2820 of file flang/fpcvt.c.
References bits, i, M, NI, and x.
Referenced by eadd1(), eiremain(), emdnorm(), enormlz(), eshift(), and etoasc().
eshup6()
void eshup6 (USHORT * x)
Definition at line 3597 of file flang/fpcvt.c.
References i, M, NI, p, and x.
Referenced by edivm(), enormlz(), and eshift().
eshup8()
void eshup8 (USHORT * x)
Definition at line 3574 of file flang/fpcvt.c.
References i, M, NI, and x.
Referenced by enormlz(), and eshift().
esub()
void esub (USHORT * a, USHORT * b, USHORT * c)
Definition at line 3381 of file flang/fpcvt.c.
References a, b, eadd1(), and subflg.
Referenced by efloor().
esubm()
void esubm (USHORT * x, USHORT * y)
Definition at line 3548 of file flang/fpcvt.c.
References a, carry(), i, M, NI, x, and y.
Referenced by eadd1(), edivm(), and eiremain().
etoasc()
void etoasc (USHORT * x, char * string, int ndigs, char let)
Definition at line 2092 of file flang/fpcvt.c.
References DOMAIN, eaddm(), ecmp(), ediv(), efloor(), eiremain(), emov(), emovi(), emovo(), emovz(), emtens, emul(), etypdat_tag::eone, etypdat_tag::equot, eshdn1(), eshup1(), etens, etypdat, EXONE, etypdat_tag::ezero, i, j, k, m, MAXP, mtherr(), NBITS, NDEC, NE, NI, NTEN, p, r, etypdat_tag::rndprc, s, sign, ss, t, void(), w, x, and y.
Referenced by __fortio_lldecvt().
fperror()
static void fperror (int x) static
Definition at line 2408 of file flang/fpcvt.c.
Referenced by mtherr().
m16m()
void m16m (USHORT a, USHORT * b, USHORT * c)
Definition at line 3658 of file flang/fpcvt.c.
References a, b, carry(), i, M, m, NI, p, and pp.
Referenced by edivm(), and emulm().
manadd()
static void manadd (INT * m1, INT * m2) static
Definition at line 157 of file flang/fpcvt.c.
References carry(), hi, i, lo, m2, t1, and t2.
Referenced by manrnd().
manmul()
static void manmul (INT * m1, INT * m2) static
Definition at line 210 of file flang/fpcvt.c.
References carry(), i, j, k, m2, n1, n2, and p.
Referenced by ufpxten().
manrnd()
static void manrnd (INT * m, int bits) static
Definition at line 180 of file flang/fpcvt.c.
References bits, m, manadd(), manshftl(), manshftr(), one, and round().
Referenced by ufpdnorm(), and ufprnd().
manshftl()
static void manshftl (INT * m, int n) static
Definition at line 135 of file flang/fpcvt.c.
References i, j, m, and n.
Referenced by manrnd(), ufpdnorm(), ufpnorm(), and ufpxten().
manshftr()
static void manshftr (INT * m, int n) static
Definition at line 112 of file flang/fpcvt.c.
References i, j, m, and n.
Referenced by manrnd(), ufpdnorm(), ufpnorm(), and ufpxten().
mtherr()
static void mtherr (const char * s, int c) static
Definition at line 2402 of file flang/fpcvt.c.
References fperror().
Referenced by __fortio_ecvt(), ediv(), enan(), enormlz(), and etoasc().
ufpdnorm()
static int ufpdnorm (UFP * u, int bias) static
Definition at line 480 of file flang/fpcvt.c.
References manrnd(), manshftl(), and manshftr().
Referenced by ufptod().
ufpnorm()
static void ufpnorm (UFP * u) static
Definition at line 242 of file flang/fpcvt.c.
References manshftl(), and manshftr().
Referenced by ufprnd(), and ufpxten().
ufprnd()
static void ufprnd (UFP * u, int bits) static
Definition at line 259 of file flang/fpcvt.c.
References bits, manrnd(), and ufpnorm().
Referenced by ufptod().
ufptod()
static void ufptod (UFP * u, IEEE64 * r) static
Definition at line 424 of file flang/fpcvt.c.
References __io_set_errno(), BIG, DIVZ, INFIN, NAN, NIL, NORMAL, r, SUBNORMAL, ufpdnorm(), ufprnd(), ieee::v, void(), and ZERO.
Referenced by __fortio_strtod().
ufpxten()
static void ufpxten (UFP * u, int exp) static
Definition at line 298 of file flang/fpcvt.c.
References BIG, exp, ftab1, ftab2, i, j, manmul(), manshftl(), manshftr(), NIL, and ufpnorm().
Referenced by __fortio_strtod().
writefmt()
static void writefmt (char * fmt, int prec, char c, int is_quad) static
Definition at line 757 of file flang/fpcvt.c.
References c, and i.
Referenced by __fortio_ecvt(), and __fortio_fcvt().
Variable Documentation
bmask
USHORT bmask[] static
Initial value:
= {
    0xffff, 0xfffe, 0xfffc, 0xfff8, 0xfff0, 0xffe0, 0xffc0, 0xff80, 0xff00,
    0xfe00, 0xfc00, 0xf800, 0xf000, 0xe000, 0xc000, 0x8000, 0x0000,
}
Definition at line 2575 of file flang/fpcvt.c.
Referenced by efloor().
emtens
USHORT emtens[NTEN+1][NE] static
Definition at line 2036 of file flang/fpcvt.c.
Referenced by etoasc().
etens
USHORT etens[NTEN+1][NE] static
Definition at line 1981 of file flang/fpcvt.c.
Referenced by etoasc().
etypdat
struct etypdat_tag etypdat
Definition at line 2340 of file flang/fpcvt.c.
Referenced by edivm(), efloor(), einfin(), eiremain(), emdnorm(), emulm(), and etoasc().
ftab1
INT ftab1[29][3] static
Initial value:
= {
    {0xA05C0DD7, 0x0F6E1619, -1162}, {0xA5CED43B, 0x7E3E9188, -1079},
    {0xAB70FE17, 0xC79AC6CA, -996},  {0xB1442798, 0xF49FFB4A, -913},
    {0xB749FAED, 0x14125D36, -830},  {0xBD8430BD, 0x08277231, -747},
    {0xC3F490AA, 0x77BD60FC, -664},  {0xCA9CF1D2, 0x06FDC03B, -581},
    {0xD17F3B51, 0xFCA3A7A0, -498},  {0xD89D64D5, 0x7A607744, -415},
    {0xDFF97724, 0x70297EBD, -332},  {0xE7958CB8, 0x7392C2C2, -249},
    {0xEF73D256, 0xA5C0F77C, -166},  {0xF79687AE, 0xD3EEC551, -83},
    {0x80000000, 0x00000000, 1},     {0x84595161, 0x401484A0, 84},
    {0x88D8762B, 0xF324CD0F, 167},   {0x8D7EB760, 0x70A08AEC, 250},
    {0x924D692C, 0xA61BE758, 333},   {0x9745EB4D, 0x50CE6332, 416},
    {0x9C69A972, 0x84B578D7, 499},   {0xA1BA1BA7, 0x9E1632DC, 582},
    {0xA738C6BE, 0xBB12D16C, 665},   {0xACE73CBF, 0xDC0BFB7B, 748},
    {0xB2C71D5B, 0xCA9023F8, 831},   {0xB8DA1662, 0xE7B00A17, 914},
    {0xBF21E440, 0x03ACDD2C, 997},   {0xC5A05277, 0x621BE293, 1080},
    {0xCC573C2A, 0x0ECCDAA6, 1163},
}
Definition at line 265 of file flang/fpcvt.c.
Referenced by ufpxten().
ftab2
INT ftab2[25][3] static
Initial value:
= {
    {0x80000000, 0x00000000, 1},  {0xA0000000, 0x00000000, 4},
    {0xC8000000, 0x00000000, 7},  {0xFA000000, 0x00000000, 10},
    {0x9C400000, 0x00000000, 14}, {0xC3500000, 0x00000000, 17},
    {0xF4240000, 0x00000000, 20}, {0x98968000, 0x00000000, 24},
    {0xBEBC2000, 0x00000000, 27}, {0xEE6B2800, 0x00000000, 30},
    {0x9502F900, 0x00000000, 34}, {0xBA43B740, 0x00000000, 37},
    {0xE8D4A510, 0x00000000, 40}, {0x9184E72A, 0x00000000, 44},
    {0xB5E620F4, 0x80000000, 47}, {0xE35FA931, 0xA0000000, 50},
    {0x8E1BC9BF, 0x04000000, 54}, {0xB1A2BC2E, 0xC5000000, 57},
    {0xDE0B6B3A, 0x76400000, 60}, {0x8AC72304, 0x89E80000, 64},
    {0xAD78EBC5, 0xAC620000, 67}, {0xD8D726B7, 0x177A8000, 70},
    {0x87867832, 0x6EAC9000, 74}, {0xA968163F, 0x0A57B400, 77},
    {0xD3C21BCE, 0xCCEDA100, 80},
}
Definition at line 282 of file flang/fpcvt.c.
Referenced by ufpxten().
nan113
IEEE128 nan113 static
Initial value:
= {0x7fffffff, (int)0xffffffff, (int)0xffffffff,
                         (int)0xffffffff}
Definition at line 2970 of file flang/fpcvt.c.
Referenced by enan().
nan24
int nan24 = 0x7fffffff static
Definition at line 2973 of file flang/fpcvt.c.
Referenced by enan().
nan53
int nan53[2] = {0x7fffffff, (int)0xffffffff} static
Definition at line 2972 of file flang/fpcvt.c.
Referenced by enan().
rbit
USHORT rbit[NI] = {0, 0, 0, 0, 0, 0, 0, 0} static
Definition at line 3201 of file flang/fpcvt.c.
Referenced by emdnorm().
re
int re = 0 static
Definition at line 3200 of file flang/fpcvt.c.
Referenced by binop_init_list(), and emdnorm().
rebit
USHORT rebit = 0 static
Definition at line 3199 of file flang/fpcvt.c.
Referenced by emdnorm().
rlast
int rlast = -1 static
Definition at line 3195 of file flang/fpcvt.c.
Referenced by emdnorm().
rmbit
USHORT rmbit = 0 static
Definition at line 3198 of file flang/fpcvt.c.
Referenced by emdnorm().
rmsk
USHORT rmsk = 0 static
Definition at line 3197 of file flang/fpcvt.c.
Referenced by emdnorm().
rw
int rw = 0 static
Definition at line 3196 of file flang/fpcvt.c.
Referenced by __fortio_main(), and emdnorm().
subflg
int subflg = 0 static
Definition at line 3378 of file flang/fpcvt.c.
Referenced by _fam(), eadd1(), emdnorm(), and esub().