flang: gbldefs.h File Reference
flang2/flang2exe/gbldefs.h File Reference
Host dependent, version dependent, and miscellaneous macros used throughout PGFTN.
#include <stdint.h>
#include "universal.h"
#include "platform.h"
#include "pgifeat.h"
#include <scutil.h>
#include "sharedefs.h"
Macros
#define NEW_ARG_PARSER
#define USEFNEG 1
#define PGFTN
#define SCFTN
#define SCC_SCFTN
#define PGC_PGFTN
#define PGF90
#define DEBUG 1
#define DBGBIT(n, m) (flg.dbg[n] & m)
#define XBIT(n, m) (flg.x[n] & m)
#define WINNT_CALL XBIT(121, 0x10000)
#define WINNT_CREF XBIT(121, 0x40000)
#define WINNT_NOMIXEDSTRLEN XBIT(121, 0x80000)
#define XBIT_USE_SCOPE_LABELS !XBIT(198, 0x40000)
#define CNULL ((char *)0)
#define uf(s) error(V_0000_Internal_compiler_error_OP1_OP2, ERR_Informational, gbl.lineno, "Unimplemented feature", s)
#define STANDARD_MAXIDLEN 63
#define MAXIDLEN 163
#define MAX_FILENAME_LEN 2048
#define MAX_FUNCTION_NAME_LEN (1024)
#define MAX_VARIABLE_NAME_LEN (1024)
#define ISZ_T BIGINT
#define UISZ_T BIGUINT
#define ISZ_PF BIGIPFSZ
#define ISZ_2_INT64(s, r) bgitoi64(s, r)
#define INT64_2_ISZ(s, r) r = i64tobgi(s)
#define ISZ_ABS labs
#define TRUE true
#define FALSE false
#define SCFTN_TRUE gbl.ftn_true
#define SCFTN_FALSE 0
#define SCFTN_NEGATE(n) ((~(n)) & SCFTN_TRUE)
#define BCOPY(p, q, dt, n) memcpy(p, q, (sizeof(dt) * (n)))
#define BZERO(p, dt, n) memset((p), 0, (sizeof(dt) * (n)))
#define FREE(p) sccfree((char *)p), p = NULL
#define NODWARF 1
#define NOELF64 1
#define NEW(p, dt, n)
#define NEED(n, p, dt, size, newsize)
#define NEEDB(n, p, dt, size, newsize)
#define CLRFPERR() (Fperr = FPE_NOERR)
#define CHKFPERR() (Fperr != FPE_NOERR ? fperror() : 0)
#define GETITEM(area, type) (type *) getitem(area, sizeof(type))
#define GETITEMS(area, type, n) (type *) getitem(area, (n) * sizeof(type))
#define ALLOCA(type, number) (type *) alloca(sizeof(type) * (number))
#define USE_LLVM_CMPLX 1
Typedefs
typedef int8_t INT8
typedef int16_t INT16
typedef uint16_t UINT16
typedef int ILM_T
typedef BIGINT BV
typedef bool LOGICAL
typedef enum RUTYPE RUTYPE
Enumerations
enum RUTYPE { RU_SUBR = 1 , RU_FUNC = 2 , RU_PROG = 3 , RU_BDATA = 4 }
Functions
void reportarea (int full)
void bjunk (void *p, BIGUINT64 n)
char * sccalloc (BIGUINT64)
void sccfree (char *)
char * sccrelal (char *, BIGUINT64)
char * getitem (int, int)
void freearea (int)
int put_getitem_p (void *)
stores the pointer in the pointer table and returns its index.
void * get_getitem_p (int)
returns the pointer stored at index i.
void free_getitem_p (void)
frees the table of pointers. NOTE: it's safer to just call this function at the end of compilation to allow a mix of pointers which are only live during a phase and those which are live during the entire compile such as the pointers locating items in area 8.
char * mkfname (const char *, const char *, const char *)
Allocate space for and make new filename using mkperm.
void set_xflag (int, INT)
Called only from main()
void set_yflag (int, INT)
Called only from main()
void bzero (void *, size_t)
void list_init (FILE *)
void list_line (const char *)
void list_page (void)
void fprintf_str_esc_backslash (FILE *f, char *str)
void extractor_end (void)
void extractor_single_index_file (char *indexname)
void extractor_single_file (char *singlename)
void ipasave_extractor_end (void)
void extractor (void)
void carry (void)
void xcarry (void)
Detailed Description
Host dependent, version dependent, and miscellaneous macros used throughout PGFTN.
Definition in file flang2/flang2exe/gbldefs.h.
Macro Definition Documentation
ALLOCA
#define ALLOCA (type, number) (type *) alloca(sizeof(type) * (number))
Definition at line 193 of file flang2/flang2exe/gbldefs.h.
BCOPY
#define BCOPY (p, q, dt, n) memcpy(p, q, (sizeof(dt) * (n)))
Definition at line 99 of file flang2/flang2exe/gbldefs.h.
BZERO
#define BZERO (p, dt, n) memset((p), 0, (sizeof(dt) * (n)))
Definition at line 100 of file flang2/flang2exe/gbldefs.h.
CHKFPERR
#define CHKFPERR () (Fperr != FPE_NOERR ? fperror() : 0)
Definition at line 156 of file flang2/flang2exe/gbldefs.h.
CLRFPERR
#define CLRFPERR () (Fperr = FPE_NOERR)
Definition at line 153 of file flang2/flang2exe/gbldefs.h.
CNULL
#define CNULL ((char *)0)
Definition at line 46 of file flang2/flang2exe/gbldefs.h.
DBGBIT
#define DBGBIT (n, m) (flg.dbg[n] & m)
Definition at line 36 of file flang2/flang2exe/gbldefs.h.
DEBUG
#define DEBUG 1
Definition at line 34 of file flang2/flang2exe/gbldefs.h.
FALSE
#define FALSE false
Definition at line 89 of file flang2/flang2exe/gbldefs.h.
FREE
#define FREE (p) sccfree((char *)p), p = NULL
Definition at line 102 of file flang2/flang2exe/gbldefs.h.
GETITEM
#define GETITEM (area, type) (type *) getitem(area, sizeof(type))
Definition at line 165 of file flang2/flang2exe/gbldefs.h.
GETITEMS
#define GETITEMS (area, type, n) (type *) getitem(area, (n) * sizeof(type))
Definition at line 166 of file flang2/flang2exe/gbldefs.h.
INT64_2_ISZ
#define INT64_2_ISZ (s, r) r = i64tobgi(s)
Definition at line 78 of file flang2/flang2exe/gbldefs.h.
ISZ_2_INT64
#define ISZ_2_INT64 (s, r) bgitoi64(s, r)
Definition at line 77 of file flang2/flang2exe/gbldefs.h.
ISZ_ABS
#define ISZ_ABS labs
Definition at line 79 of file flang2/flang2exe/gbldefs.h.
ISZ_PF
#define ISZ_PF BIGIPFSZ
Definition at line 76 of file flang2/flang2exe/gbldefs.h.
ISZ_T
#define ISZ_T BIGINT
Definition at line 74 of file flang2/flang2exe/gbldefs.h.
MAX_FILENAME_LEN
#define MAX_FILENAME_LEN 2048
Definition at line 56 of file flang2/flang2exe/gbldefs.h.
MAX_FUNCTION_NAME_LEN
#define MAX_FUNCTION_NAME_LEN (1024)
Definition at line 62 of file flang2/flang2exe/gbldefs.h.
MAX_VARIABLE_NAME_LEN
#define MAX_VARIABLE_NAME_LEN (1024)
Definition at line 63 of file flang2/flang2exe/gbldefs.h.
MAXIDLEN
#define MAXIDLEN 163
Definition at line 53 of file flang2/flang2exe/gbldefs.h.
NEED
#define NEED (n, p, dt, size, newsize)
Value:
  if (n > size) {                                                       \
    p = (dt *)sccrelal((char *)p, ((BIGUINT64)((newsize) * sizeof(dt))));    \
    if (DBGBIT(7, 2))                                                   \
      bjunk((char *)(p + size), (BIGUINT64)((newsize - size) * sizeof(dt))); \
    size = newsize;                                                     \
  } else
Definition at line 120 of file flang2/flang2exe/gbldefs.h.
NEEDB
#define NEEDB (n, p, dt, size, newsize)
Value:
  if (n > size) {                                                    \
    p = (dt *)sccrelal((char *)p, ((BIGUINT64)((newsize) * sizeof(dt)))); \
    BZERO(p + size, dt, newsize - size);                             \
    size = newsize;                                                  \
  } else
Definition at line 137 of file flang2/flang2exe/gbldefs.h.
NEW
#define NEW (p, dt, n)
Value:
  if (1) {                                          \
    p = (dt *)sccalloc((BIGUINT64)(sizeof(dt) * (n)));   \
    if (DBGBIT(7, 2))                               \
      bjunk((char *)(p), (BIGUINT64)(sizeof(dt) * (n))); \
  } else
Definition at line 114 of file flang2/flang2exe/gbldefs.h.
NEW_ARG_PARSER
#define NEW_ARG_PARSER
Definition at line 23 of file flang2/flang2exe/gbldefs.h.
NODWARF
#define NODWARF 1
Definition at line 107 of file flang2/flang2exe/gbldefs.h.
NOELF64
#define NOELF64 1
Definition at line 108 of file flang2/flang2exe/gbldefs.h.
PGC_PGFTN
#define PGC_PGFTN
Definition at line 31 of file flang2/flang2exe/gbldefs.h.
PGF90
#define PGF90
Definition at line 32 of file flang2/flang2exe/gbldefs.h.
PGFTN
#define PGFTN
Definition at line 28 of file flang2/flang2exe/gbldefs.h.
SCC_SCFTN
#define SCC_SCFTN
Definition at line 30 of file flang2/flang2exe/gbldefs.h.
SCFTN
#define SCFTN
Definition at line 29 of file flang2/flang2exe/gbldefs.h.
SCFTN_FALSE
#define SCFTN_FALSE 0
Definition at line 96 of file flang2/flang2exe/gbldefs.h.
SCFTN_NEGATE
#define SCFTN_NEGATE (n) ((~(n)) & SCFTN_TRUE)
Definition at line 97 of file flang2/flang2exe/gbldefs.h.
SCFTN_TRUE
#define SCFTN_TRUE gbl.ftn_true
Definition at line 95 of file flang2/flang2exe/gbldefs.h.
STANDARD_MAXIDLEN
#define STANDARD_MAXIDLEN 63
Definition at line 50 of file flang2/flang2exe/gbldefs.h.
TRUE
#define TRUE true
Definition at line 88 of file flang2/flang2exe/gbldefs.h.
uf
#define uf (s) error(V_0000_Internal_compiler_error_OP1_OP2, ERR_Informational, gbl.lineno, "Unimplemented feature", s)
Definition at line 47 of file flang2/flang2exe/gbldefs.h.
UISZ_T
#define UISZ_T BIGUINT
Definition at line 75 of file flang2/flang2exe/gbldefs.h.
USE_LLVM_CMPLX
#define USE_LLVM_CMPLX 1
Definition at line 198 of file flang2/flang2exe/gbldefs.h.
USEFNEG
#define USEFNEG 1
Definition at line 26 of file flang2/flang2exe/gbldefs.h.
WINNT_CALL
#define WINNT_CALL XBIT(121, 0x10000)
Definition at line 40 of file flang2/flang2exe/gbldefs.h.
WINNT_CREF
#define WINNT_CREF XBIT(121, 0x40000)
Definition at line 41 of file flang2/flang2exe/gbldefs.h.
WINNT_NOMIXEDSTRLEN
#define WINNT_NOMIXEDSTRLEN XBIT(121, 0x80000)
Definition at line 42 of file flang2/flang2exe/gbldefs.h.
XBIT
#define XBIT (n, m) (flg.x[n] & m)
Definition at line 38 of file flang2/flang2exe/gbldefs.h.
XBIT_USE_SCOPE_LABELS
#define XBIT_USE_SCOPE_LABELS !XBIT(198, 0x40000)
Definition at line 44 of file flang2/flang2exe/gbldefs.h.
Typedef Documentation
BV
typedef BIGINT BV
Definition at line 81 of file flang2/flang2exe/gbldefs.h.
ILM_T
typedef int ILM_T
Definition at line 69 of file flang2/flang2exe/gbldefs.h.
INT16
typedef int16_t INT16
Definition at line 66 of file flang2/flang2exe/gbldefs.h.
INT8
typedef int8_t INT8
Definition at line 65 of file flang2/flang2exe/gbldefs.h.
LOGICAL
typedef bool LOGICAL
Definition at line 87 of file flang2/flang2exe/gbldefs.h.
RUTYPE
typedef enum RUTYPE RUTYPE
UINT16
typedef uint16_t UINT16
Definition at line 67 of file flang2/flang2exe/gbldefs.h.
Enumeration Type Documentation
RUTYPE
enum RUTYPE
Enumerator
RU_SUBR
RU_FUNC
RU_PROG
RU_BDATA
Definition at line 146 of file flang2/flang2exe/gbldefs.h.
Function Documentation
bjunk()
void bjunk (void * p, BIGUINT64 n)
bzero()
void bzero (void * , size_t)
carry()
void carry (void)
Referenced by __ecvt(), __utl_i_add64(), eaddm(), esubm(), int128_unsigned_add(), m16m(), manadd(), manmul(), mult_delimited_fraction(), and mult_fraction().
extractor()
void extractor (void)
Definition at line 362 of file inliner.c.
References error(), ERROR, errsev(), export_inline(), extractor_possible(), fd, FILE, find_libentry(), gbl, getitem(), MAX_FNAME_LEN, MODNAME_FMT, NULL, PERM_AREA, libentry::pleNext, pleStart, sExtDir, libentry::sFunc, libentry::sHost, libentry::sMod, libentry::sModFile, STASH, SYMNAME, and TRACE0.
extractor_end()
void extractor_end (void)
Definition at line 429 of file inliner.c.
References error(), fclose(), fd, FILE, fndpath(), freearea(), gbl, INLINER_VERSION, MAX_FNAME_LEN, NULL, PERM_AREA, libentry::pleNext, pleStart, sExtDir, libentry::sFunc, libentry::sHost, libentry::sMod, libentry::sModFile, TOC_ENTRY_FMT, and TOC_HEADER_FMT.
extractor_single_file()
void extractor_single_file (char * singlename)
extractor_single_index_file()
void extractor_single_index_file (char * indexname)
fprintf_str_esc_backslash()
void fprintf_str_esc_backslash (FILE * f, char * str)
Definition at line 108 of file miscutil.c.
References f, and str.
free_getitem_p()
void free_getitem_p (void)
frees the table of pointers. NOTE: it's safer to just call this function at the end of compilation to allow a mix of pointers which are only live during a phase and those which are live during the entire compile such as the pointers locating items in area 8.
Definition at line 177 of file salloc.c.
freearea()
void freearea (int area)
Definition at line 83 of file salloc.c.
get_getitem_p()
void * get_getitem_p (int i)
returns the pointer stored at index i.
Definition at line 158 of file salloc.c.
getitem()
char * getitem (int area, int size)
Parameters
area is an area
size is the size in bytes of item to be allocated.
Definition at line 37 of file salloc.c.
ipasave_extractor_end()
void ipasave_extractor_end (void)
list_init()
void list_init (FILE * fd)
Definition at line 25 of file listing.c.
list_line()
void list_line (const char * txt)
Definition at line 97 of file listing.c.
list_page()
void list_page (void)
Definition at line 130 of file listing.c.
mkfname()
char * mkfname (const char * oldname, const char * oldsuf, const char * newsuf)
Allocate space for and make new filename using mkperm.
Definition at line 24 of file miscutil.c.
put_getitem_p()
int put_getitem_p (void * p)
stores the pointer in the pointer table and returns its index.
Definition at line 134 of file salloc.c.
reportarea()
void reportarea (int full)
sccalloc()
char * sccalloc (BIGUINT64 nbytes)
Definition at line 35 of file mall.c.
sccfree()
void sccfree (char * ap)
Definition at line 62 of file mall.c.
sccrelal()
char * sccrelal (char * pp, BIGUINT64 nbytes)
Definition at line 71 of file mall.c.
set_xflag()
void set_xflag (int indx, INT val)
Called only from main()
Definition at line 92 of file miscutil.c.
set_yflag()
void set_yflag (int indx, INT val)
Called only from main()
Definition at line 102 of file miscutil.c.
xcarry()
void xcarry (void)