flang: gbldefs.h File Reference
flang1/flang1exe/gbldefs.h File Reference
miscellaneous macros and prototypes used by Fortran front-end Function prototypes and host/version dependent miscellaneous macros used throughout the Fortran front-end.
#include <stdint.h>
#include "universal.h"
#include "platform.h"
#include "pgifeat.h"
#include <scutil.h>
#include "sharedefs.h"
Macros
#define NEW_ARG_PARSER
#define USEFNEG 1
#define FE90
#define PGFTN
#define PGHPF
#define SCFTN
#define SCC_SCFTN
#define PGC_PGFTN
#define DEBUG 1
#define DBGBIT(n, m) (flg.dbg[n] & m)
#define GBL_SIZE_T_FORMAT "zu"
#define XBIT(n, m) (flg.x[n] & m)
#define F77OUTPUT XBIT(49, 0x80)
#define XBIT_USE_SCOPE_LABELS !XBIT(198, 0x40000)
#define WINNT_CALL XBIT(121, 0x10000)
#define WINNT_CREF XBIT(121, 0x40000)
#define WINNT_NOMIXEDSTRLEN XBIT(121, 0x80000)
#define CNULL ((char *)0)
#define uf(s) error(0, 1, gbl.lineno, "Unimplemented feature", s)
#define STANDARD_MAXIDLEN 63
#define MAXIDLEN 163
#define MAX_FILENAME_LEN 2048
#define MAXSUBS 7
#define MAXDIMS 7
#define ISZ_T BIGINT
#define UISZ_T BIGUINT
#define ISZ_PF BIGIPFSZ
#define ISZ_2_INT64(s, r) bgitoi64(s, r)
#define INT64_2_ISZ(s, r) r = i64tobgi(s)
#define BITS_PER_BYTE 8
#define TRUE 1
#define FALSE 0
#define SCFTN_TRUE gbl.ftn_true
#define SCFTN_FALSE 0
#define SCFTN_NEGATE(n) ((~(n)) & SCFTN_TRUE)
#define BCOPY(p, q, dt, n) memcpy(p, q, ((UINT)sizeof(dt) * (n)))
#define BZERO(p, dt, n) memset((p), 0, ((UINT)sizeof(dt) * (n)))
#define FREE(p) sccfree((char *)p), p = NULL
#define NEW(p, dt, n)
#define NEED(n, p, dt, size, newsize)
#define NEEDB(n, p, dt, size, newsize)
#define CLRFPERR() (Fperr = FPE_NOERR)
#define CHKFPERR() (Fperr != FPE_NOERR ? fperror() : 0)
#define GETITEM(area, type) (type *) getitem(area, sizeof(type))
#define GETITEMS(area, type, n) (type *) getitem(area, (n) * sizeof(type))
Typedefs
typedef int8_t INT8
typedef int16_t INT16
typedef uint16_t UINT16
typedef int LOGICAL
Functions
void finish (void)
Write summary line to terminal, and exit compiler.
char * sccalloc (BIGUINT64)
void sccfree (char *)
char * sccrelal (char *, BIGUINT64)
void bjunk (void *p, BIGUINT64 n)
char * getitem (int, int)
void freearea (int)
int put_getitem_p (void *)
stores the pointer in the pointer table and returns its index.
void * get_getitem_p (int)
returns the pointer stored at index i.
void free_getitem_p (void)
frees the table of pointers. NOTE: it's safer to just call this function at the end of compilation to allow a mix of pointers which are only live during a phase and those which are live during the entire compile such as the pointers locating items in area 8.
char * mkfname (const char *, const char *, const char *)
Allocate space for and make new filename using mkperm.
bool is_xflag_bit (int)
void set_xflag (int, INT)
Called only from main()
void set_yflag (int, INT)
Called only from main()
void list_init (FILE *)
void list_line (const char *)
void list_page (void)
ISZ_T get_bss_addr (void)
void assemble (void)
void assemble_init (void)
void assemble_end (void)
Complete assem for the source file.
ISZ_T set_bss_addr (ISZ_T)
ISZ_T pad_cmn_mem (int, ISZ_T, int *)
void fix_equiv_locals (int loc_list, ISZ_T loc_addr)
The equivalence processor assigns positive offsets to the local variables which appear in equivalence statements. Target addresses must be assigned using the offsets provided by the equivalence processor.
void fix_equiv_statics (int loc_list, ISZ_T loc_addr, LOGICAL dinitflg)
Similiar to fix_equiv_locals except that these local variables were saved and/or dinit'd. for these variables, switch the storage class to SC_STATIC.
void dbg_print_ast (int, FILE *)
void deferred_to_pointer (void)
Since the output is 'standard' f77, all allocatable (deferred-shape) arrays must be converted to pointer-based arrays. The symbol table is scanned to find allocatable arrays which do not have bound temporaries or associated pointer variables.
void dumpfgraph ()
void dumploops ()
void dumpnmes ()
void dumpuses (void)
void dumpdefs (void)
void dcommons (void)
void dumpdts (void)
void dstds (int std1, int std2)
void dsyms (int l, int u)
void dstdps (int std1, int std2)
void dumpasts (void)
void dumpstdtrees (void)
void dumpshapes (void)
void dumplists (void)
void dsstds (int std1, int std2)
void dump_ast_tree (int i)
void dumpaccrout (void)
void reportarea (int full)
void lower_ipa_info (FILE *lowerfile)
void ipa_init (void)
void ipa_startfunc (int currfunc)
void ipa_header1 (int currfunc)
void ipa_header2 (int currfunc)
void ipa (void)
long IPA_sstride (int sptr)
long IPA_pstride (int sptr)
void ipasave_endfunc (void)
void fill_ipasym (void)
void ipa_import_highpoint (void)
void ipa_import (void)
void ipa_set_vestigial_host (void)
void import_module_print (void)
void import_host_subprogram (FILE *fd, const char *file_name, int oldsymavl, int oldastavl, int olddtyavl, int modbase, int moddiff)
This is called to restore symbol table, etc., data for contained subprograms.
void import_fini (void)
Wrap-up module symbol import phase.
void set_tag (void)
void ipa_export_endmodule (void)
void ipa_export_highpoint (void)
void ipa_export_endcontained (void)
void exterf_init (void)
void exterf_init_host (void)
void export_public_module (int module, int exceptlist)
void export_inline (FILE *export_fd, char *export_name, char *file_name)
LOGICAL is_initialized (int *bv, int nme)
int IPA_isnoconflict (int sptr)
void reinit (void)
Perform initializations for new user subprogram unit:
int can_map_initsym (int old_firstosym)
Adding intrinsics, predeclareds, etc. to symini_ftn has the effect of rendering existng .mod files incompatible because the values of stb.firstosym will be different.
int map_initsym (int oldsym, int old_firstosym)
Determine if oldsym, read from a .mod file, is a predefined (intrinsic, predeclared, constant, etc.).
int hashcon (INT *value, int dtype, int sptr)
void end_contained (void)
called at end of processing contains subprograms
void set_exitcode (int ec)
set exit code for compiler (see finish() function)
void eliminate_unused_variables (int which)
For XBIT(57,0x2000), eliminate declarations of any unused variables, unless they are in COMMON.
void bblock_init (void)
Called from semant_init().
int bblock (void)
Return nonzero if there are any CUDA Fortran kernels.
void merge_commons (void)
Merge common blocks.
void renumber_lines (void)
void lower_constructor (void)
Notify back end of the end of a module.
void lower_pstride_info (FILE *lowerfile)
void parse_init (void)
void fpp (void)
Detailed Description
miscellaneous macros and prototypes used by Fortran front-end Function prototypes and host/version dependent miscellaneous macros used throughout the Fortran front-end.
Definition in file flang1/flang1exe/gbldefs.h.
Macro Definition Documentation
BCOPY
#define BCOPY (p, q, dt, n) memcpy(p, q, ((UINT)sizeof(dt) * (n)))
Definition at line 100 of file flang1/flang1exe/gbldefs.h.
BITS_PER_BYTE
#define BITS_PER_BYTE 8
Definition at line 82 of file flang1/flang1exe/gbldefs.h.
BZERO
#define BZERO (p, dt, n) memset((p), 0, ((UINT)sizeof(dt) * (n)))
Definition at line 101 of file flang1/flang1exe/gbldefs.h.
CHKFPERR
#define CHKFPERR () (Fperr != FPE_NOERR ? fperror() : 0)
Definition at line 140 of file flang1/flang1exe/gbldefs.h.
CLRFPERR
#define CLRFPERR () (Fperr = FPE_NOERR)
Definition at line 137 of file flang1/flang1exe/gbldefs.h.
CNULL
#define CNULL ((char *)0)
Definition at line 54 of file flang1/flang1exe/gbldefs.h.
DBGBIT
#define DBGBIT (n, m) (flg.dbg[n] & m)
Definition at line 39 of file flang1/flang1exe/gbldefs.h.
DEBUG
#define DEBUG 1
Definition at line 37 of file flang1/flang1exe/gbldefs.h.
F77OUTPUT
#define F77OUTPUT XBIT(49, 0x80)
Definition at line 44 of file flang1/flang1exe/gbldefs.h.
FALSE
#define FALSE 0
Definition at line 90 of file flang1/flang1exe/gbldefs.h.
FE90
#define FE90
Definition at line 29 of file flang1/flang1exe/gbldefs.h.
FREE
#define FREE (p) sccfree((char *)p), p = NULL
Definition at line 102 of file flang1/flang1exe/gbldefs.h.
GBL_SIZE_T_FORMAT
#define GBL_SIZE_T_FORMAT "zu"
Definition at line 41 of file flang1/flang1exe/gbldefs.h.
GETITEM
#define GETITEM (area, type) (type *) getitem(area, sizeof(type))
Definition at line 155 of file flang1/flang1exe/gbldefs.h.
GETITEMS
#define GETITEMS (area, type, n) (type *) getitem(area, (n) * sizeof(type))
Definition at line 156 of file flang1/flang1exe/gbldefs.h.
INT64_2_ISZ
#define INT64_2_ISZ (s, r) r = i64tobgi(s)
Definition at line 80 of file flang1/flang1exe/gbldefs.h.
ISZ_2_INT64
#define ISZ_2_INT64 (s, r) bgitoi64(s, r)
Definition at line 79 of file flang1/flang1exe/gbldefs.h.
ISZ_PF
#define ISZ_PF BIGIPFSZ
Definition at line 78 of file flang1/flang1exe/gbldefs.h.
ISZ_T
#define ISZ_T BIGINT
Definition at line 76 of file flang1/flang1exe/gbldefs.h.
MAX_FILENAME_LEN
#define MAX_FILENAME_LEN 2048
Definition at line 65 of file flang1/flang1exe/gbldefs.h.
MAXDIMS
#define MAXDIMS 7
Definition at line 69 of file flang1/flang1exe/gbldefs.h.
MAXIDLEN
#define MAXIDLEN 163
Definition at line 62 of file flang1/flang1exe/gbldefs.h.
MAXSUBS
#define MAXSUBS 7
Definition at line 68 of file flang1/flang1exe/gbldefs.h.
NEED
#define NEED (n, p, dt, size, newsize)
Value:
  if (n > size) {                                                            \
    p = (dt *)sccrelal((char *)p, ((BIGUINT64)((newsize) * (INT)sizeof(dt))));    \
    if (DBGBIT(7, 2))                                                        \
      bjunk((char *)(p + size), (BIGUINT64)((newsize - size) * (INT)sizeof(dt))); \
    size = newsize;                                                          \
  } else
Definition at line 111 of file flang1/flang1exe/gbldefs.h.
NEEDB
#define NEEDB (n, p, dt, size, newsize)
Value:
  if (n > size) {                                                         \
    p = (dt *)sccrelal((char *)p, ((BIGUINT64)((newsize) * (INT)sizeof(dt)))); \
    BZERO(p + size, dt, newsize - size);                                  \
    size = newsize;                                                       \
  } else
Definition at line 128 of file flang1/flang1exe/gbldefs.h.
NEW
#define NEW (p, dt, n)
Value:
  if (1) {                                               \
    p = (dt *)sccalloc((BIGUINT64)((INT)sizeof(dt) * (n)));   \
    if (DBGBIT(7, 2))                                    \
      bjunk((char *)(p), (BIGUINT64)((INT)sizeof(dt) * (n))); \
  } else
Definition at line 105 of file flang1/flang1exe/gbldefs.h.
NEW_ARG_PARSER
#define NEW_ARG_PARSER
Definition at line 24 of file flang1/flang1exe/gbldefs.h.
PGC_PGFTN
#define PGC_PGFTN
Definition at line 34 of file flang1/flang1exe/gbldefs.h.
PGFTN
#define PGFTN
Definition at line 30 of file flang1/flang1exe/gbldefs.h.
PGHPF
#define PGHPF
Definition at line 31 of file flang1/flang1exe/gbldefs.h.
SCC_SCFTN
#define SCC_SCFTN
Definition at line 33 of file flang1/flang1exe/gbldefs.h.
SCFTN
#define SCFTN
Definition at line 32 of file flang1/flang1exe/gbldefs.h.
SCFTN_FALSE
#define SCFTN_FALSE 0
Definition at line 97 of file flang1/flang1exe/gbldefs.h.
SCFTN_NEGATE
#define SCFTN_NEGATE (n) ((~(n)) & SCFTN_TRUE)
Definition at line 98 of file flang1/flang1exe/gbldefs.h.
SCFTN_TRUE
#define SCFTN_TRUE gbl.ftn_true
Definition at line 96 of file flang1/flang1exe/gbldefs.h.
STANDARD_MAXIDLEN
#define STANDARD_MAXIDLEN 63
Definition at line 59 of file flang1/flang1exe/gbldefs.h.
TRUE
#define TRUE 1
Definition at line 88 of file flang1/flang1exe/gbldefs.h.
uf
#define uf (s) error(0, 1, gbl.lineno, "Unimplemented feature", s)
Definition at line 56 of file flang1/flang1exe/gbldefs.h.
UISZ_T
#define UISZ_T BIGUINT
Definition at line 77 of file flang1/flang1exe/gbldefs.h.
USEFNEG
#define USEFNEG 1
Definition at line 27 of file flang1/flang1exe/gbldefs.h.
WINNT_CALL
#define WINNT_CALL XBIT(121, 0x10000)
Definition at line 50 of file flang1/flang1exe/gbldefs.h.
WINNT_CREF
#define WINNT_CREF XBIT(121, 0x40000)
Definition at line 51 of file flang1/flang1exe/gbldefs.h.
WINNT_NOMIXEDSTRLEN
#define WINNT_NOMIXEDSTRLEN XBIT(121, 0x80000)
Definition at line 52 of file flang1/flang1exe/gbldefs.h.
XBIT
#define XBIT (n, m) (flg.x[n] & m)
Definition at line 43 of file flang1/flang1exe/gbldefs.h.
XBIT_USE_SCOPE_LABELS
#define XBIT_USE_SCOPE_LABELS !XBIT(198, 0x40000)
Definition at line 46 of file flang1/flang1exe/gbldefs.h.
Typedef Documentation
INT16
typedef int16_t INT16
Definition at line 72 of file flang1/flang1exe/gbldefs.h.
INT8
typedef int8_t INT8
Definition at line 71 of file flang1/flang1exe/gbldefs.h.
LOGICAL
typedef int LOGICAL
Definition at line 86 of file flang1/flang1exe/gbldefs.h.
UINT16
typedef uint16_t UINT16
Definition at line 73 of file flang1/flang1exe/gbldefs.h.
Function Documentation
assemble()
void assemble (void)
Definition at line 27 of file assem.c.
assemble_end()
void assemble_end (void)
Complete assem for the source file.
Guaranteed to be called only once per compilation
Definition at line 37 of file assem.c.
assemble_init()
void assemble_init (void)
Definition at line 32 of file assem.c.
Referenced by init().
bblock()
int bblock (void)
Return nonzero if there are any CUDA Fortran kernels.
Definition at line 61 of file bblock.c.
References add_stmt_after(), add_stmt_before(), adj_based_arrays(), SEM::alloc_mem_initialize, assumshp_args(), ast, ast_unvisit(), ast_visit(), astb, atomic, SEM::auto_dealloc, SEM::auto_finalize, BLOCK_ENTRY_STD, BLOCK_EXIT_STD, cs, DBGBIT, DT_INT, dump_std(), entry_point, erly_bnds_depd, FREE, gbl, gen_alloc_mem_initialize_for_sym(), gen_conditional_dealloc_for_sym(), gen_early_str_len(), gen_finalization_for_sym(), gen_type_initialize_for_sym(), getlab(), getsymbol(), ASTB::i0, init_newargs(), itemp, kernel, label, last_std, mk_assn_stmt(), mk_cval(), mk_id(), mk_label(), mk_stmt(), NEW, new_ast(), new_std(), NOSYM, NULL, par, parsect, RFCNTI, RU_PROG, s, sem, set_std_parflags(), sptr, std, STD_AST, STD_ATOMIC, STD_CS, STD_LABEL, STD_LAST, STD_LINENO, STD_NEXT, STD_PAR, STD_PARSECT, STD_PREV, STD_TASK, stdx, task, SEM::temps_reset, tmp, TRUE, SEM::type_initialize, and void().
bblock_init()
void bblock_init (void)
Called from semant_init().
Definition at line 54 of file bblock.c.
Referenced by semant_init().
bjunk()
void bjunk (void * p, BIGUINT64 n)
can_map_initsym()
int can_map_initsym (int old_firstosym)
Adding intrinsics, predeclareds, etc. to symini_ftn has the effect of rendering existng .mod files incompatible because the values of stb.firstosym will be different.
stb.firstosym is computed from:
the number of intrinsics, predeclareds defined by symini_ftn, and
the number of predeclared constants/symbols created in symtab.c:sym_init() (e.g., 1.0, 0, 2, etc.)
It should be possible to map the 'firstosym' symbols from the previous symini to the current symini by just subscripting a table using the old symbol as the index. The purpose of oldsyms0() is to generate the table, map_init0[], based on the old (6.1) version of symini and the current symini which defines the mapping. The 6.1 information, represented by init_sym0[] and init_names0[], are manually extracted from the 6.1-generated syminidf.h; these tables are just renamed versions of init_sym[] & init_names[]. oldsyms0() just scans these 'symbols' and looks for the symbols with the same names in the current symini. In addition to generating the table, map_init0[], the size of the table, init_syms0_size, is generated. If new intrinsics are added after today's symini is released, a new table & size, presumably named init_sym1 and init_syms1_size, will be generated from inputs init_sym1 & init_names1. This process should be able to be repreated to create map_init2, ...
Determine if a firstosym value read from a .mod file matches the current initial symtab or a previous initial symtab for which we have mapping information.
Definition at line 3368 of file symtab.c.
References STB::firstosym, NXTRA, and stb.
Referenced by import_header_only().
dbg_print_ast()
void dbg_print_ast (int ast, FILE * fil)
Definition at line 4482 of file astout.c.
dcommons()
void dcommons (void)
Definition at line 4256 of file dump.c.
References c, dcommon(), dfile, gbl, NOSYM, and stb.
Referenced by init().
deferred_to_pointer()
void deferred_to_pointer (void)
Since the output is 'standard' f77, all allocatable (deferred-shape) arrays must be converted to pointer-based arrays. The symbol table is scanned to find allocatable arrays which do not have bound temporaries or associated pointer variables.
Definition at line 3334 of file astout.c.
References AD_DEFER, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_NOBOUNDS, AD_NUMDIM, AD_UPAST, ALIGNG, STB::firstusym, i, mk_bnd_ast(), NO_PTR, s, sptr, stb, sym_get_ptr(), and XBIT.
Referenced by linearize_arrays().
dsstds()
void dsstds (int std1, int std2)
Definition at line 2379 of file dump.c.
References astb, dfile, dsstd(), gbl, STD_NEXT, STD_PREV, stdx, and SYMNAME.
Referenced by dump_sstds().
dstdps()
void dstdps (int std1, int std2)
Definition at line 2359 of file dump.c.
References astb, dfile, dstdp(), gbl, STD_NEXT, STD_PREV, stdx, and SYMNAME.
Referenced by dstdpa(), dump_stdps(), and points_to().
dstds()
void dstds (int std1, int std2)
Definition at line 2342 of file dump.c.
References astb, dfile, dstd(), gbl, STD_NEXT, STD_PREV, stdx, and SYMNAME.
Referenced by dstda(), dstdr(), and dump_stds().
dsyms()
void dsyms (int l, int u)
Definition at line 4189 of file dump.c.
dump_ast_tree()
void dump_ast_tree (int i)
Definition at line 6787 of file ast.c.
dumpaccrout()
void dumpaccrout (void)
dumpasts()
void dumpasts (void)
Definition at line 1367 of file dump.c.
References astb, and dast().
Referenced by init().
dumpdefs()
void dumpdefs (void)
Definition at line 4774 of file dump.c.
dumpdts()
void dumpdts (void)
Definition at line 4356 of file dump.c.
References dfile, dlen(), STB::dt, dt, DTY, dumpdt(), gbl, and stb.
Referenced by dumpdtypes(), and init().
dumpfgraph()
void dumpfgraph ()
Definition at line 1820 of file dump.c.
dumplists()
void dumplists (void)
Definition at line 491 of file dump.c.
References appendstring1(), aux, dfile, gbl, AUX::list, NOSYM, putline(), putslnk1(), putstring1(), and putstype1().
Referenced by init().
dumploops()
void dumploops ()
Definition at line 2231 of file dump.c.
dumpnmes()
void dumpnmes ()
Definition at line 2124 of file dump.c.
dumpshapes()
void dumpshapes (void)
Definition at line 1398 of file dump.c.
References astb, dfile, dumpshape(), ASTB::shd, and SHD_NDIM.
Referenced by init().
dumpstdtrees()
void dumpstdtrees (void)
Definition at line 2433 of file dump.c.
References dfile, dstdtree(), STD_NEXT, STD_PREV, and stdx.
Referenced by init().
dumpuses()
void dumpuses (void)
Definition at line 4840 of file dump.c.
eliminate_unused_variables()
void eliminate_unused_variables (int which)
For XBIT(57,0x2000), eliminate declarations of any unused variables, unless they are in COMMON.
Definition at line 1666 of file bblock.c.
References assert, ast, ast_traverse(), ast_unvisit(), ast_visit(), aux, DIRECT::avail, check_used_in_data(), direct, eliminate_save_alignments, eliminate_save_distributed, STB::firstusym, FLANG_FALLTHROUGH, gbl, AUX::list, DIRECT::lpg, mark(), mark_symbol(), mark_used_in_independent(), mark_used_variable(), must_mark(), NOSYM, NULL, RU_BDATA, sptr, stb, std, STD_AST, STD_NEXT, and DIRECT::stgb.
end_contained()
void end_contained (void)
called at end of processing contains subprograms
Definition at line 1472 of file main.c.
References ipa_export_endcontained(), ipa_export_file, ipa_import_mode, and lower_end_contains().
Referenced by check_end_subprogram().
export_inline()
void export_inline (FILE * export_fd, char * export_name, char * file_name)
Definition at line 543 of file exterf.c.
References export(), FALSE, fclose(), for_inliner, gbl, sym_module, and TRUE.
Referenced by extractor().
export_public_module()
void export_public_module (int module, int exceptlist)
Definition at line 162 of file exterf.c.
References xitemx::exceptlist, getitem(), MOD_AREA, p, public_module_list, and same_sym_list().
Referenced by export_public_used_modules().
exterf_init()
void exterf_init (void)
Definition at line 970 of file exterf.c.
References APPEND_AREA, append_list, freearea(), host_append_list, and NULL.
Referenced by import_init().
exterf_init_host()
void exterf_init_host (void)
Definition at line 978 of file exterf.c.
References host_append_list, and NULL.
Referenced by restore_internal_subprograms().
fill_ipasym()
void fill_ipasym (void)
Definition at line 1511 of file main.c.
finish()
INT finish (void)
Write summary line to terminal, and exit compiler.
\Brief Write summary line to terminal, and exit.
Definition at line 1320 of file main.c.
References ast_fini(), c, called, DBGBIT, destroy_action_map(), direct_fini(), DUMP, errfatal(), FLG::es, exitcode, FALSE, fclose(), fih_fini(), FILE, fini(), flg, fp, free_getitem_p(), freearea(), gbl, import_module_print(), ipa_closefile(), IPA_COLLECTION_ENABLED, IPA_ENABLED, ipa_export_close(), ipa_export_file, ipa_fini(), ipa_import_mode, IPA_INHERIT_ENABLED, ipasave_closefile(), ipasave_fini(), maxfilsev, mkfname(), mod_fini(), NULL, FLG::object, objectfile, OBJFILE, FLG::opt, phase_dump_map, reptime(), scan_fini(), sem_fini(), summary(), symtab_fini(), TRUE, and XBIT.
Referenced by accpp(), display_error(), ff_get_stmt(), fpp(), and get_stmt().
fix_equiv_locals()
void fix_equiv_locals (int loc_list, ISZ_T loc_addr)
The equivalence processor assigns positive offsets to the local variables which appear in equivalence statements. Target addresses must be assigned using the offsets provided by the equivalence processor.
Parameters
loc_list list of local symbols linked by SYMLK
loc_addr total size of the equivalenced locals
Definition at line 213 of file assem.c.
References ALIGN, alignment(), DT_DBLE, DT_QUADALIGN, flg, gbl, NOSYM, and FLG::quad.
Referenced by do_equiv().
fix_equiv_statics()
void fix_equiv_statics (int loc_list, ISZ_T loc_addr, LOGICAL dinitflg)
Similiar to fix_equiv_locals except that these local variables were saved and/or dinit'd. for these variables, switch the storage class to SC_STATIC.
Parameters
loc_list list of local symbols linked by SYMLK
loc_addr total size of the equivalenced locals
dinitflg variables were dinit'd
The equivalence processor assigns positive offsets to the local variables which appear in equivalence statements. Target addresses must be assigned using the offsets provided by the equivalence processor.
Definition at line 255 of file assem.c.
References addr, ALIGN, alignment(), assert, bss_addr, DT_DBLE, DT_QUADALIGN, flg, gbl, ISZ_T, NOSYM, and FLG::quad.
Referenced by do_equiv().
fpp()
void fpp (void)
Definition at line 390 of file fpp.c.
References _ifs, accpp(), argbuf, ARGMAX, atoxi(), chkdef, clreol(), CNULL, count, cp, cur_fname, cur_line, D_DEFINE, D_ELIF, D_ELSE, D_ENDIF, D_ERROR, D_IDENT, D_IF, D_IFDEF, D_IFNDEF, D_INCLUDE, D_INCLUDE_NEXT, D_LINE, D_LIST, D_MODULE, D_NOLIST, D_PRAGMA, D_UNDEF, D_WARNING, FLG::def, deftab, dirnam(), dirname, DIRSINCS, dlookup(), dodef(), doerror(), doident(), doincl(), doline(), domodule(), doparse(), dopragma(), doundef(), dowarning(), errfatal(), error(), FLG::es, FALSE, fileloc, findtok(), finish(), flg, fname, fpp_display_macros(), FREE, gbl, hashrec, i, idir, FLG::idir, ifp, ifpush(), ifstack, iftop, incfiles, incllist, inclstack, isdig, lineloc, FLG::list, list_flag, FLG::list_macros, lookup(), MAX_FNAME_LEN, NEW, NULL, p, PGIF, PGIF_MINOR, PGIF_PATCHLEVEL, pperr, pperror, pr_line(), sccalloc(), skipbl(), FLG::smp, stash_paths(), FLG::stdinc, strlen(), strstore(), T_IDENT, tmpfile(), TOKMAX, toktyp, tokval, TRUE, FLG::undef, PPSYM::value, version, void(), FLG::x, and XBIT.
Referenced by init().
free_getitem_p()
void free_getitem_p (void)
frees the table of pointers. NOTE: it's safer to just call this function at the end of compilation to allow a mix of pointers which are only live during a phase and those which are live during the entire compile such as the pointers locating items in area 8.
Definition at line 177 of file salloc.c.
References tbl::base, and tbl::size.
Referenced by finish().
freearea()
void freearea (int area)
Definition at line 83 of file salloc.c.
References ANUM, area, areap, assert, ERR_Fatal, FREE, NULL, p, and q.
Referenced by apply_use_stmts(), assem_end(), call_analyze(), ccff_cleanup_children(), ccff_cleanup_children_deferred(), cg_llvm_fnend(), chkref(), cleanup(), const_prop(), convert_output(), dd_array_conflict(), do_dinit(), Done(), end_loop_count(), exp_end(), expand(), export(), export_some_fini(), exterf_init(), extractor_end(), finish(), flow(), flowgraph(), forall_dependency_analyze(), import_done(), live_var(), ll_process_routine_parameters(), opt_allocate(), opt_binop(), optshrd_fend(), reaching_defs(), reg_assign1(), schedule(), semant1(), semfin_free_memory(), top_sort(), trans_freeidx(), uninit_var(), and upper().
get_bss_addr()
ISZ_T get_bss_addr (void)
Definition at line 304 of file assem.c.
get_getitem_p()
void * get_getitem_p (int i)
returns the pointer stored at index i.
Definition at line 158 of file salloc.c.
References assert, tbl::base, ERR_unused, i, NULL, and tbl::size.
Referenced by _dmp_dent(), build_typedef_init_tree(), construct_acl_for_sst(), dump_stfunc(), eval_init_expr_item(), eval_init_op(), export_component_init(), export_component_init_asts(), gen_derived_type_alloc_init(), get_dtype_init_template(), get_parameterized_dt(), init_allocatable_typedef_components(), init_named_array_constant(), ref_stfunc(), and semant1().
getitem()
char * getitem (int area, int size)
Parameters
area is an area
size is the size in bytes of item to be allocated.
Definition at line 37 of file salloc.c.
References ALIGN, ANUM, area, areap, assert, avail, DBGBIT, ERR_Fatal, interr(), NEW, NULL, p, PTRSZ, q, s, SIZE, size, and sz.
Referenced by __fih_message(), _adjustl(), _adjustr(), _repeat(), _trim(), add_alloc_mem_initialize(), add_auto_dealloc(), add_auto_finalize(), add_biv_def(), add_dep(), add_du_ud(), add_etmp(), add_imported(), add_iolptrs(), add_p_dealloc_item(), add_private_allocatable(), add_profile_decl(), add_tmp_buf_list_item(), add_to_be_used_list(), add_to_cselist(), add_to_private_mod_list(), add_to_use_tree(), add_type_param_initialize(), add_use_edge(), add_use_rename(), add_use_tree_uses(), add_wheresym(), addfile(), addinlfile(), binop(), bld_lhs(), ccff_set_children(), ccff_set_children_deferred(), ch_substring(), check_alias(), check_global_define(), check_sc(), chk_struct_constructor(), clist(), clone_init_const(), cngcon(), compare_one_bound(), compute_size(), construct_acl_from_ast(), convert_to_block_forall(), create_global_initializer(), dataConstant(), dataDo(), dataEnddo(), dataReference(), dataStructure(), dataVariable(), dd_edge(), define_stfunc(), defined_io_error(), dinit_constructor(), direct_xf(), direct_yf(), distrib(), do_default_clause(), do_dinit(), do_eval_minval_or_maxval(), do_nested_uses(), enqueueTbp(), eval_adjustl(), eval_adjustr(), eval_do(), eval_index(), eval_init_op(), eval_max(), eval_min(), eval_minval_or_maxval(), eval_repeat(), eval_scale(), eval_scan(), eval_selected_char_kind(), eval_selected_real_kind(), eval_transfer(), eval_trim(), eval_verify(), export_all(), export_append_host_sym(), export_append_sym(), export_public_module(), extractor(), find_best_generic(), findloop(), fix_proc_pointer_call(), flowgraph(), func_call2(), gen_call_to_builtin(), gen_cmplxpart_intr(), gen_constant(), gen_defer_shape(), gen_dtio_arglist(), gen_dtio_args(), gen_fcn_sst(), gen_kind_parm_assignments(), gen_reduction(), gen_va_end(), gen_va_start(), gen_vconstant(), get_acl(), get_dobegin(), get_doend(), get_doinfo(), get_fn(), get_intrinsic(), get_keyword_args(), get_keyword_components(), get_llvm_ifacenm(), get_llvm_sname(), get_local_overlap_size(), get_minmax_val(), get_string_constant(), get_tbp_argno(), getcyclic(), getict(), getivl(), getstr(), getstrconst(), import(), import_header_only(), inheritTbps(), init(), insert_llvm_dbg_declare(), insert_llvm_dbg_value(), insert_llvm_memcpy(), insert_llvm_memset(), insert_llvm_prefetch(), insert_node_into_use_tree(), kwd_match(), ll_process_routine_parameters(), lldbg_alloc(), lldbg_function_end(), llutil_alloc(), load_TOC(), localflow(), lower_add_func_call(), make_instr(), make_list(), mangleUnderscores(), match_names(), mergeDebugTypesForGlobal(), mk_ido_std_range(), mk_init_intrinsic(), mk_lastprivate_list(), mk_reduction_list(), mk_shared_list(), mkfname(), mkitem(), new_ivs(), open_module(), partition_blocks(), plist(), pp_entries(), pp_entries_mixedstrlen(), print_entry_subroutine(), process_blockaddr_sptr(), process_extern_function_sptr(), process_extern_variable_sptr(), process_label_sptr_c(), process_local_sptr(), process_string(), push_include(), push_tbp_arg(), ref_stfunc(), replace_variable(), resolve_generic(), resolveGeneric(), resolvePass(), resolveTbps(), rewrite_cmplxpart_rhs(), rewrite_cmplxpart_rval(), save_firstprivate_list(), save_ilms(), save_private_list(), save_shared_list(), scan_include(), selection_sort(), semant1(), semant2(), semant3(), semantio(), semCheckTbp(), semsmp(), set_global_sname(), set_local_sname(), set_numbered_global_sname(), setfile(), store_funcname(), storechartmp(), subr_call2(), sum_scatter_args(), sym_get_sdescr(), top_sort(), update_external_function_declarations(), var_ref_list(), vect_llvm_intrinsic_name(), and write_profile_enter().
hashcon()
int hashcon (INT * value, int dtype, int sptr)
Definition at line 573 of file symtab.c.
References HASH_CON, STB::hashtb, sptr, stb, and value().
import_fini()
void import_fini (void)
Wrap-up module symbol import phase.
Definition at line 361 of file interf.c.
References imported_modules_struct::avail, FREE, imported_modules, imported_modules_struct::list, and imported_modules_struct::size.
Referenced by sem_fini().
import_host_subprogram()
void import_host_subprogram (FILE * fd, const char * file_name, int oldsymavl, int oldastavl, int olddtyavl, int modbase, int moddiff)
This is called to restore symbol table, etc., data for contained subprograms.
Definition at line 3289 of file interf.c.
References ADJmod, BASEast, BASEdty, BASEmod, BASEsym, export_fix_host_append_list(), FALSE, fd, for_host, import_done(), import_header(), IMPORT_WHICH_HOST, INCLUDE_PRIVATES, new_symbol(), and TRUE.
Referenced by restore_host_state().
import_module_print()
void import_module_print (void)
Definition at line 3215 of file interf.c.
References basenam(), c, CNULL, error(), f, FILE, fname, fp, gbl, m, modinclist, modinclistavl, NULL, sccalloc(), strlen(), and XBIT.
Referenced by finish().
ipa()
void ipa (void)
Definition at line 1512 of file main.c.
Referenced by get_component_init(), getict(), getivl(), and put_data_statement().
ipa_export_endcontained()
void ipa_export_endcontained (void)
Definition at line 1493 of file main.c.
Referenced by end_contained().
ipa_export_endmodule()
void ipa_export_endmodule (void)
Definition at line 1494 of file main.c.
ipa_export_highpoint()
void ipa_export_highpoint (void)
Definition at line 1495 of file main.c.
ipa_header1()
void ipa_header1 (int currfunc)
Definition at line 1497 of file main.c.
ipa_header2()
void ipa_header2 (int currfunc)
Definition at line 1498 of file main.c.
ipa_import()
void ipa_import (void)
Definition at line 1501 of file main.c.
ipa_import_highpoint()
void ipa_import_highpoint (void)
Definition at line 1499 of file main.c.
ipa_init()
void ipa_init (void)
Definition at line 1502 of file main.c.
Referenced by main().
IPA_isnoconflict()
int IPA_isnoconflict (int sptr)
Definition at line 1514 of file main.c.
Referenced by lower_set_symbols().
IPA_pstride()
long IPA_pstride (int sptr)
Definition at line 6230 of file upper.cpp.
References findindex(), i, INFO_PSTRIDE, IPA_Pointer_Strides_Propagated, IPNDX_INFO, IPNFO_NEXT, IPNFO_PSTRIDE, IPNFO_TYPE, n, sptr, and XBIT.
ipa_set_vestigial_host()
void ipa_set_vestigial_host (void)
Definition at line 1513 of file main.c.
IPA_sstride()
long IPA_sstride (int sptr)
Definition at line 6251 of file upper.cpp.
References findindex(), i, INFO_SSTRIDE, IPA_Pointer_Strides_Propagated, IPNDX_INFO, IPNFO_NEXT, IPNFO_SSTRIDE, IPNFO_TYPE, n, sptr, and XBIT.
ipa_startfunc()
void ipa_startfunc (int currfunc)
Definition at line 1509 of file main.c.
ipasave_endfunc()
void ipasave_endfunc (void)
Definition at line 1506 of file main.c.
is_initialized()
LOGICAL is_initialized (int * bv, int nme)
Definition at line 2360 of file flow.c.
References bv_mem(), is_optsym(), lv, and TRUE.
Referenced by alldefs_allocsafe(), and ptrdefs_has_lhsconflict().
is_xflag_bit()
bool is_xflag_bit (int indx)
Definition at line 85 of file miscutil.c.
References is_xflag_bitvector().
Referenced by rd_dir().
list_init()
void list_init (FILE * fd)
Definition at line 25 of file listing.c.
References FLG::asmcode, buf, FLG::code, DBGBIT, FLG::dclchk, FLG::debug, FLG::depchk, FLG::depwarn, FLG::dlines, FLG::extend_source, fd, flg, gbl, FLG::idir, FLG::include, FLG::inform, lf, FLG::line, FLG::list, list_line(), list_ln(), FLG::object, FLG::onetrip, FLG::opt, p, pgno, FLG::profile, FLG::save, FLG::standard, FLG::symbol, FLG::ucase, and FLG::xref.
Referenced by init().
list_line()
void list_line (const char * txt)
Definition at line 97 of file listing.c.
References list_ln().
Referenced by _nextline(), display_error(), ff_get_noncomment(), ff_get_stmt(), get_stmt(), par_body(), print_par_xref(), printxref(), push_include(), putentry(), reptime(), and scan_include().
list_page()
void list_page (void)
Definition at line 130 of file listing.c.
References DBGBIT, lf, list_line(), and pgpos.
Referenced by ff_get_stmt(), get_stmt(), init(), print_par_xref(), and printxref().
lower_constructor()
void lower_constructor (void)
Notify back end of the end of a module.
Definition at line 643 of file lower.c.
References gbl.
lower_ipa_info()
void lower_ipa_info (FILE * lowerfile)
lower_pstride_info()
void lower_pstride_info (FILE * lowerfile)
Definition at line 455 of file pstride.c.
References f, fist, FIST_GDYN, FIST_ID, FIST_ISYM, FIST_LDYN, FIST_NEXT, FIST_NLOC, FIST_PSYM, FIST_TYPE, FIST_UNK, fistlist, FLIST_PTR, FLIST_SPTR, NULL, sptr, and t.
Referenced by lower_symbols().
map_initsym()
int map_initsym (int oldsym, int old_firstosym)
Determine if oldsym, read from a .mod file, is a predefined (intrinsic, predeclared, constant, etc.).
If it is, attempt to map the oldsym to the current set of predefineds; note that oldsym could also be from the current set. The value of old_firstosym indicates to which set, current or older, oldsym belongs.
Definition at line 3402 of file symtab.c.
References STB::firstosym, interr(), NXTRA, and stb.
Referenced by new_symbol(), new_symbol_and_link(), and new_symbol_if_module().
merge_commons()
void merge_commons (void)
Merge common blocks.
If two modules declare the same common block, both sets of symbols appear in the program. If either uses the same variable names, by Fortran 90 rules, the names may not be used, though they could be hidden by USE, ONLY clauses. To generate correct output, we must merge the two definitions. This routine checks that the distributed variables in the duplicate commons have the same type, distribution, offsets, and sizes. It replaces all references to one of the commons by references to the other. For nondistributed data, this routine generates EQUIVALENCE data.
Definition at line 973 of file bblock.c.
References donetwice1, donetwice2, gbl, merge(), and NOSYM.
mkfname()
char * mkfname (const char * oldname, const char * oldsuf, const char * newsuf)
Allocate space for and make new filename using mkperm.
Definition at line 24 of file miscutil.c.
References getitem(), mkperm(), p, and strlen().
Referenced by finish(), init(), and mkDwfInfoFilename().
pad_cmn_mem()
ISZ_T pad_cmn_mem (int mem, ISZ_T msz, int * p_aln_n)
Definition at line 322 of file assem.c.
References ALN_MINSZ, ALN_THRESH, ALN_UNIT, mem(), msz, PDALN_IS_DEFAULT, and XBIT.
Referenced by add_to_common(), do_common_blocks(), and set_common_size().
parse_init()
void parse_init (void)
Definition at line 411 of file parser.c.
References cstate, pstack, scan_reset(), and stktop.
put_getitem_p()
int put_getitem_p (void * p)
stores the pointer in the pointer table and returns its index.
Definition at line 134 of file salloc.c.
References tbl::base, NEED, NEW, NULL, p, r, and tbl::size.
Referenced by convert_ctmp_array_to_param(), define_stfunc(), get_component_init(), get_parameterized_dt(), init_allocatable_typedef_components(), put_data_statement(), save_typedef_init(), and semant1().
reinit()
static void reinit (void)
Perform initializations for new user subprogram unit:
Perform initializations for new user subprogram unit:
Definition at line 872 of file main.cpp.
References datastructure_reinit(), dinit_init(), dpm_out_init(), errini(), flg, gbl, ipa_export_file, ipa_import_mode, IS_PARFILE, NOSYM, FLG::opt, queue_tbp(), FLG::recursive, RU_PROG, saveoptflag, saverecursive, savevectflag, savex8flag, scan_opt_restore(), semant_init(), SPTR_NULL, sym_init(), TBP_CLEAR_STALE_RECORDS, FLG::vect, FLG::x, FLG::xref, and xrefinit().
Referenced by parser().
renumber_lines()
void renumber_lines (void)
Definition at line 1441 of file bblock.c.
References renumber, std, STD_LINENO, and STD_NEXT.
reportarea()
void reportarea (int full)
Referenced by report_area().
sccalloc()
char * sccalloc (BIGUINT64 nbytes)
Definition at line 35 of file mall.c.
References DBGBIT, errfatal(), malloc(), NULL, p, q, s, TOO_LARGE, and TRACE.
Referenced by addmodfile(), fpp(), import_module_print(), rb_new(), scan_init(), and stg_alloc_base().
sccfree()
void sccfree (char * ap)
Definition at line 62 of file mall.c.
References TRACE.
Referenced by rb_free(), and stg_delete().
sccrelal()
char * sccrelal (char * pp, BIGUINT64 nbytes)
Definition at line 71 of file mall.c.
References errfatal(), NULL, pp, q, TOO_LARGE, and TRACE.
Referenced by _parser(), _rd_tkline(), read_line(), realloc_stmtb(), stg_need(), and subst().
set_bss_addr()
ISZ_T set_bss_addr (ISZ_T addr)
Definition at line 310 of file assem.c.
References addr, and bss_addr.
Referenced by datastructure_reinit(), and parser().
set_exitcode()
void set_exitcode (int ec)
set exit code for compiler (see finish() function)
Parameters
ec - the exit code to set
Definition at line 1312 of file main.c.
References exitcode.
Referenced by apply_use(), and open_module().
set_tag()
void set_tag (void)
Definition at line 3106 of file exterf.c.
References max_tag, std, and STD_NEXT.
set_xflag()
void set_xflag (int indx, INT val)
Called only from main()
Definition at line 92 of file miscutil.c.
References flg, FLG::opt, set_xflag_value(), val, and FLG::x.
Referenced by direct_rou_load(), and init().
set_yflag()
void set_yflag (int indx, INT val)
Called only from main()
Definition at line 102 of file miscutil.c.
References flg, unset_xflag_value(), val, and FLG::x.
Referenced by direct_rou_load(), and init().