flang: symtab.in.h File Reference
flang2/utils/symtab/symtab.in.h File Reference
symbol table for Fortran backend
#include "global.h"
#include <stdarg.h>
#include "symacc.h"
Classes
struct ADSC
struct ENTRY
struct NMLDSC
struct SYMI
struct DVL
struct AUX
struct SWEL
Macros
#define ST_ISVAR(s) ((s) >= ST_VAR && (s) <= ST_UNION)
#define DT_FLOAT DT_REAL
#define TY_FLOAT TY_REAL
#define DT_CPTR DT_ADDR
#define DTY(d) (stb.dt.stg_base[d])
#define DDTG(dt) (DTY(dt) == TY_ARRAY ? DTY(dt+1) : dt)
#define DTYG(dt) (DTY(dt) == TY_ARRAY ? DTY(DTY(dt+1)) : DTY(dt))
#define DT_ISINT(dt) (dttypes[DTY(dt)]&_TY_INT)
#define DT_ISREAL(dt) (dttypes[DTY(dt)]&_TY_REAL)
#define DT_ISCMPLX(dt) (dttypes[DTY(dt)]&_TY_CMPLX)
#define DT_ISNUMERIC(dt) (dttypes[DTY(dt)]&(_TY_INT|_TY_REAL|_TY_CMPLX))
#define DT_ISBASIC(dt) (dttypes[DTY(dt)]&_TY_BASIC)
#define DT_ISUNSIGNED(dt) (dttypes[DTY(dt)]&_TY_UNSIGNED)
#define DT_ISSCALAR(dt) (dttypes[DTY(dt)]&_TY_SCALAR)
#define DT_ISVEC(dt) (dttypes[DTY(dt)]&_TY_VEC)
#define DT_ISLOG(dt) (dttypes[DTY(dt)]&_TY_LOG)
#define DT_ISWORD(dt) (dttypes[DTY(dt)]&_TY_WORD)
#define DT_ISDWORD(dt) (dttypes[DTY(dt)]&_TY_DWORD)
#define DT_ISVECT(dt) (dttypes[DTY(dt)]&_TY_VECT)
#define TY_ISINT(t) (dttypes[t]&_TY_INT)
#define TY_ISREAL(t) (dttypes[t]&_TY_REAL)
#define TY_ISCMPLX(t) (dttypes[t]&_TY_CMPLX)
#define TY_ISNUMERIC(t) (dttypes[t]&(_TY_INT|_TY_REAL|_TY_CMPLX))
#define TY_ISBASIC(t) (dttypes[t]&_TY_BASIC)
#define TY_ISUNSIGNED(t) (dttypes[t]&_TY_UNSIGNED)
#define TY_ISSCALAR(t) (dttypes[t]&_TY_SCALAR)
#define TY_ISLOG(t) (dttypes[t]&_TY_LOG)
#define TY_ISVEC(t) (dttypes[t]&_TY_VEC)
#define TY_ISWORD(t) (dttypes[t]&_TY_WORD)
#define TY_ISDWORD(t) (dttypes[t]&_TY_DWORD)
#define TY_ISVECT(t) (dttypes[t]&_TY_VECT)
#define TY_VECT_MAXLEN 16
#define ALIGN(addr, a) ((addr + a) & ~(a))
#define ALIGN_AUTO(addr, a) ((addr) & ~(a))
#define SC_AUTO SC_LOCAL
#define SC_ISCMBLK(p) (p == SC_CMBLK)
#define CONVAL2G(s) (INT)((stb.stg_base)[s].w14)
#define CONVAL2P(s, v) (INT)((stb.stg_base)[s].w14 = (v))
#define CMEMLG(s) (INT)((stb.stg_base)[s].w14)
#define CMEMLP(s, v) (INT)((stb.stg_base)[s].w14 = (v))
#define DEFLABG(s) (INT)((stb.stg_base)[s].w14)
#define DEFLABP(s, v) (INT)((stb.stg_base)[s].w14 = (v))
#define ENDLINEG(s) (INT)((stb.stg_base)[s].w14)
#define ENDLINEP(s, v) (INT)((stb.stg_base)[s].w14 = (v))
#define FUNCLINEG(s) (INT)((stb.stg_base)[s].w14)
#define FUNCLINEP(s, v) (INT)((stb.stg_base)[s].w14 = (v))
#define GSAMEG(s) (INT)((stb.stg_base)[s].w14)
#define GSAMEP(s, v) (INT)((stb.stg_base)[s].w14 = (v))
#define ILMG(s) (INT)((stb.stg_base)[s].w14)
#define ILMP(s, v) (INT)((stb.stg_base)[s].w14 = (v))
#define ORIGDUMMYG(s) (INT)((stb.stg_base)[s].w32)
#define ORIGDUMMYP(s, v) (INT)((stb.stg_base)[s].w32 = (v))
#define GREALG(s) (INT)((stb.stg_base)[s].w10)
#define GREALP(s, v) (INT)((stb.stg_base)[s].w10 = (v))
#define SFDSCG(s) (INT)((stb.stg_base)[s].w10)
#define SFDSCP(s, v) (INT)((stb.stg_base)[s].w10 = (v))
#define ACONOFFG(s) ((stb.stg_base)[s].w14)
#define ACONOFFP(s, v) ((stb.stg_base)[s].w14 = (v))
#define PARAMVALG(s) ((stb.stg_base)[s].w15)
#define PARAMVALP(s, v) ((stb.stg_base)[s].w15 = (v))
#define DLLG(s) b3G(s)
#define DLLP(s, v) b3P(s,v)
#define PDALN_EXPLICIT_0 0xf
#define PDALNG(s) ((b4G(s)&0x0f) == PDALN_EXPLICIT_0 ? 0 : (b4G(s)&0x0f))
#define PDALNP(s, v) b4P(s, (b4G(s)&0xf0) | ((v) == 0 ? PDALN_EXPLICIT_0 : (v)))
#define PDALN_IS_DEFAULT(s) ((b4G(s)&0x0f) == 0)
#define SYMNAME(p) (stb.n_base + NMPTRG(p))
#define SYMNAMEG(p, buff, len) len = NMLENG(p); strncpy(buff,SYMNAME(p),len)
#define LOCAL_SYMNAME(p) local_sname(SYMNAME(p))
#define RFCNTI(s) (++RFCNTG(s))
#define RFCNTD(s) (--RFCNTG(s))
#define RETADJG(s) ((stb.stg_base)[s].w10)
#define RETADJP(s, v) ((stb.stg_base)[s].w10 = (v))
#define XREFLKG(s) ((stb.stg_base)[s].w16)
#define XREFLKP(s, v) ((stb.stg_base)[s].w16 = (v))
#define NOSYM ((SPTR)1)
#define IS_TLS(s) (TLSG(s) || ETLSG(s))
#define IS_THREAD_TLS(s) (THREADG(s) && IS_TLS(s))
#define IS_THREAD_TP(s) (THREADG(s) && (!IS_TLS(s)))
#define IS_TLS_WRAPPER(sptr) (0)
#define IS_TLS_GETTER(sptr) IS_TLS(sptr)
#define CMPLXFUNC_C XBIT(49, 0x40000000)
#define DLL_NONE 0x0
#define DLL_EXPORT 0x1
#define DLL_IMPORT 0x2
#define AD_DPTR(dtype) ((ADSC *)(aux.arrdsc_base+DTY((dtype)+2)))
#define AD_PTR(sptr) ((ADSC *) (aux.arrdsc_base + DTY(DTYPEG(sptr)+2)))
#define AD_NUMDIM(p) ((p)->numdim)
#define AD_SCHECK(p) ((p)->scheck)
#define AD_ZBASE(p) ((p)->zbase)
#define AD_SDSC(p) ((p)->sdsc)
#define AD_ILMP(p) ((p)->ilmp)
#define AD_MLPYR(p, i) ((p)->b[i].mlpyr)
#define AD_LWBD(p, i) ((p)->b[i].lwbd)
#define AD_UPBD(p, i) ((p)->b[i].upbd)
#define AD_NUMELM(p) ((p)->b[AD_NUMDIM(p)].mlpyr)
#define NML_SPTR(i) aux.nml_base[i].sptr
#define NML_NEXT(i) aux.nml_base[i].next
#define NML_LINENO(i) aux.nml_base[i].lineno
#define SYMI_SPTR(i) aux.symi_base[i].sptr
#define SYMI_NEXT(i) aux.symi_base[i].next
#define DVL_SPTR(i) aux.dvl_base[i].sptr
#define DVL_CONVAL(i) aux.dvl_base[i].conval
#define VCON_CONVAL(i) aux.vcon_base[i]
#define __POINT_T DT_INT8
Typedefs
typedef enum etls_levels etls_levels
typedef struct ADSC ADSC
typedef struct ENTRY ENTRY
typedef struct NMLDSC NMLDSC
typedef struct SYMI SYMI
typedef struct DVL DVL
typedef struct AUX AUX
typedef struct SWEL SWEL
Enumerations
enum etls_levels {
ETLS_PROCESS , ETLS_TASK , ETLS_THREAD , ETLS_OMP ,
ETLS_PROCESS , ETLS_TASK , ETLS_THREAD , ETLS_OMP ,
ETLS_NUM_LEVELS
}
Functions
ISZ_T get_isz_cval (int con)
...
char * getprint (int sptr)
...
const char * parmprint (int sptr)
...
SPTR adddupsym (SPTR oldsptr)
Add a new symbol with same name as an existing symbol.
SPTR addnewsym (const char *name)
Add a new symbol with given name.
int add_symitem (int sptr, int nxt)
...
int dbg_symdentry (int sptr)
...
SPTR getccssym (const char *pfx, int n, SYMTYPE stype)
Create (or possibly reuse) a compiler created symbol whose name is of the form . <pfx> dddd where dddd is the decimal representation of n.
SPTR getccssym_sc (const char *pfx, int n, SYMTYPE stype, SC_KIND sc)
Similar to getccssym, but storage class is an argument. Calls getccssym if the storage class is not private; if private, a 'p' is appended to the name.
SPTR getccsym_copy (SPTR oldsptr)
...
SPTR getccsym (char letter, int n, SYMTYPE stype)
create (or possibly reuse) a compiler created symbol whose name is of the form . <letter> dddd where dddd is the decimal representation of n.
SPTR getccsym_sc (char letter, int n, SYMTYPE stype, SC_KIND sc)
Similar to getccsym, but storage class is an argument. Calls getccsym if the storage class is not private; if private, a 'p' is appended to the name.
SPTR getcctemp_sc (const char *name, SYMTYPE stype, SC_KIND sc)
Create (or possibly reuse) a compiler created temporary where the caller constructs the name and passes the storage class as an argument.
int get_entry_item (void)
...
SPTR getlab (void)
...
SPTR getnewccsym (char letter, int n, SYMTYPE stype)
Create (never reuse) a compiler created symbol whose name is of the form . <letter> dddd where dddd is the decimal representation of n.
SPTR get_semaphore (void)
...
SPTR getstring (const char *value, int length)
Enter character constant into symbol table.
SPTR getntstring (const char *value)
Similar to getstring except the character string is null terminated.
SPTR getstringaddr (SPTR sptr)
int get_vcon0 (DTYPE dtype)
...
int get_vcon1 (DTYPE dtype)
...
SPTR get_vcon (INT *value, DTYPE dtype)
...
int get_vconm0 (DTYPE dtype)
get a vector constant of a zero which suits the element type
SPTR get_vcon_scalar (INT sclr, DTYPE dtype)
...
SPTR insert_sym_first (SPTR first)
...
SPTR insert_sym (SPTR first)
...
SPTR mk_prototype (const char *name, const char *attr, DTYPE resdt, int nargs,...)
...
SPTR mk_prototype_llvm (const char *name, const char *attr, DTYPE resdt, int nargs,...)
...
INT sign_extend (INT val, int width)
...
int tr_conval2g (char *fn, int ln, int s)
...
int tr_conval2p (char *fn, int ln, int s, int v)
...
SPTR get_acon3 (SPTR sym, ISZ_T off, DTYPE dtype)
...
SPTR get_acon (SPTR sym, ISZ_T off)
...
SPTR getcon (INT *value, DTYPE dtype)
...
SPTR getsymbol (const char *name)
...
SPTR getsym (const char *name, int olength)
...
SPTR mkfunc (const char *nmptr)
...
void dmp_socs (int sptr, FILE *file)
...
void implicit_int (DTYPE default_int)
...
void newimplicit (int firstc, int lastc, DTYPE dtype)
Change settings for implicit variable types, character lengths.
void pop_scope (void)
...
void pop_sym (int sptr)
...
void reapply_implicit (void)
...
void setimplicit (int sptr)
...
void symdentry (FILE *file, int sptr)
...
void symdmp (FILE *dfil, bool full)
...
void sym_init (void)
...
Variables
short dttypes [TY_MAX+1]
AUX aux
SWEL * switch_base
Detailed Description
symbol table for Fortran backend
Definition in file flang2/utils/symtab/symtab.in.h.
Macro Definition Documentation
__POINT_T
#define __POINT_T DT_INT8
Definition at line 308 of file flang2/utils/symtab/symtab.in.h.
ACONOFFG
#define ACONOFFG (s) ((stb.stg_base)[s].w14)
Definition at line 128 of file flang2/utils/symtab/symtab.in.h.
ACONOFFP
#define ACONOFFP (s, v) ((stb.stg_base)[s].w14 = (v))
Definition at line 129 of file flang2/utils/symtab/symtab.in.h.
AD_DPTR
#define AD_DPTR (dtype) ((ADSC *)(aux.arrdsc_base+DTY((dtype)+2)))
Definition at line 196 of file flang2/utils/symtab/symtab.in.h.
AD_ILMP
#define AD_ILMP (p) ((p)->ilmp)
Definition at line 202 of file flang2/utils/symtab/symtab.in.h.
AD_LWBD
#define AD_LWBD (p, i) ((p)->b[i].lwbd)
Definition at line 204 of file flang2/utils/symtab/symtab.in.h.
AD_MLPYR
#define AD_MLPYR (p, i) ((p)->b[i].mlpyr)
Definition at line 203 of file flang2/utils/symtab/symtab.in.h.
AD_NUMDIM
#define AD_NUMDIM (p) ((p)->numdim)
Definition at line 198 of file flang2/utils/symtab/symtab.in.h.
AD_NUMELM
#define AD_NUMELM (p) ((p)->b[AD_NUMDIM(p)].mlpyr)
Definition at line 206 of file flang2/utils/symtab/symtab.in.h.
AD_PTR
#define AD_PTR (sptr) ((ADSC *) (aux.arrdsc_base + DTY(DTYPEG(sptr)+2)))
Definition at line 197 of file flang2/utils/symtab/symtab.in.h.
AD_SCHECK
#define AD_SCHECK (p) ((p)->scheck)
Definition at line 199 of file flang2/utils/symtab/symtab.in.h.
AD_SDSC
#define AD_SDSC (p) ((p)->sdsc)
Definition at line 201 of file flang2/utils/symtab/symtab.in.h.
AD_UPBD
#define AD_UPBD (p, i) ((p)->b[i].upbd)
Definition at line 205 of file flang2/utils/symtab/symtab.in.h.
AD_ZBASE
#define AD_ZBASE (p) ((p)->zbase)
Definition at line 200 of file flang2/utils/symtab/symtab.in.h.
ALIGN
#define ALIGN (addr, a) ((addr + a) & ~(a))
Definition at line 68 of file flang2/utils/symtab/symtab.in.h.
ALIGN_AUTO
#define ALIGN_AUTO (addr, a) ((addr) & ~(a))
Definition at line 69 of file flang2/utils/symtab/symtab.in.h.
CMEMLG
#define CMEMLG (s) (INT)((stb.stg_base)[s].w14)
Definition at line 99 of file flang2/utils/symtab/symtab.in.h.
CMEMLP
#define CMEMLP (s, v) (INT)((stb.stg_base)[s].w14 = (v))
Definition at line 100 of file flang2/utils/symtab/symtab.in.h.
CMPLXFUNC_C
#define CMPLXFUNC_C XBIT(49, 0x40000000)
Definition at line 177 of file flang2/utils/symtab/symtab.in.h.
CONVAL2G
#define CONVAL2G (s) (INT)((stb.stg_base)[s].w14)
Definition at line 97 of file flang2/utils/symtab/symtab.in.h.
CONVAL2P
#define CONVAL2P (s, v) (INT)((stb.stg_base)[s].w14 = (v))
Definition at line 98 of file flang2/utils/symtab/symtab.in.h.
DDTG
#define DDTG (dt) (DTY(dt) == TY_ARRAY ? DTY(dt+1) : dt)
Definition at line 37 of file flang2/utils/symtab/symtab.in.h.
DEFLABG
#define DEFLABG (s) (INT)((stb.stg_base)[s].w14)
Definition at line 101 of file flang2/utils/symtab/symtab.in.h.
DEFLABP
#define DEFLABP (s, v) (INT)((stb.stg_base)[s].w14 = (v))
Definition at line 102 of file flang2/utils/symtab/symtab.in.h.
DLL_EXPORT
#define DLL_EXPORT 0x1
Definition at line 180 of file flang2/utils/symtab/symtab.in.h.
DLL_IMPORT
#define DLL_IMPORT 0x2
Definition at line 181 of file flang2/utils/symtab/symtab.in.h.
DLL_NONE
#define DLL_NONE 0x0
Definition at line 179 of file flang2/utils/symtab/symtab.in.h.
DLLG
#define DLLG (s) b3G(s)
Definition at line 132 of file flang2/utils/symtab/symtab.in.h.
DLLP
#define DLLP (s, v) b3P(s,v)
Definition at line 133 of file flang2/utils/symtab/symtab.in.h.
DT_CPTR
#define DT_CPTR DT_ADDR
Definition at line 29 of file flang2/utils/symtab/symtab.in.h.
DT_FLOAT
#define DT_FLOAT DT_REAL
Definition at line 27 of file flang2/utils/symtab/symtab.in.h.
DT_ISBASIC
#define DT_ISBASIC (dt) (dttypes[DTY(dt)]&_TY_BASIC)
Definition at line 44 of file flang2/utils/symtab/symtab.in.h.
DT_ISCMPLX
#define DT_ISCMPLX (dt) (dttypes[DTY(dt)]&_TY_CMPLX)
Definition at line 42 of file flang2/utils/symtab/symtab.in.h.
DT_ISDWORD
#define DT_ISDWORD (dt) (dttypes[DTY(dt)]&_TY_DWORD)
Definition at line 50 of file flang2/utils/symtab/symtab.in.h.
DT_ISINT
#define DT_ISINT (dt) (dttypes[DTY(dt)]&_TY_INT)
Definition at line 40 of file flang2/utils/symtab/symtab.in.h.
DT_ISLOG
#define DT_ISLOG (dt) (dttypes[DTY(dt)]&_TY_LOG)
Definition at line 48 of file flang2/utils/symtab/symtab.in.h.
DT_ISNUMERIC
#define DT_ISNUMERIC (dt) (dttypes[DTY(dt)]&(_TY_INT|_TY_REAL|_TY_CMPLX))
Definition at line 43 of file flang2/utils/symtab/symtab.in.h.
DT_ISREAL
#define DT_ISREAL (dt) (dttypes[DTY(dt)]&_TY_REAL)
Definition at line 41 of file flang2/utils/symtab/symtab.in.h.
DT_ISSCALAR
#define DT_ISSCALAR (dt) (dttypes[DTY(dt)]&_TY_SCALAR)
Definition at line 46 of file flang2/utils/symtab/symtab.in.h.
DT_ISUNSIGNED
#define DT_ISUNSIGNED (dt) (dttypes[DTY(dt)]&_TY_UNSIGNED)
Definition at line 45 of file flang2/utils/symtab/symtab.in.h.
DT_ISVEC
#define DT_ISVEC (dt) (dttypes[DTY(dt)]&_TY_VEC)
Definition at line 47 of file flang2/utils/symtab/symtab.in.h.
DT_ISVECT
#define DT_ISVECT (dt) (dttypes[DTY(dt)]&_TY_VECT)
Definition at line 51 of file flang2/utils/symtab/symtab.in.h.
DT_ISWORD
#define DT_ISWORD (dt) (dttypes[DTY(dt)]&_TY_WORD)
Definition at line 49 of file flang2/utils/symtab/symtab.in.h.
DTY
#define DTY (d) (stb.dt.stg_base[d])
Definition at line 31 of file flang2/utils/symtab/symtab.in.h.
DTYG
#define DTYG (dt) (DTY(dt) == TY_ARRAY ? DTY(DTY(dt+1)) : DTY(dt))
Definition at line 38 of file flang2/utils/symtab/symtab.in.h.
DVL_CONVAL
#define DVL_CONVAL (i) aux.dvl_base[i].conval
Definition at line 265 of file flang2/utils/symtab/symtab.in.h.
DVL_SPTR
#define DVL_SPTR (i) aux.dvl_base[i].sptr
Definition at line 264 of file flang2/utils/symtab/symtab.in.h.
ENDLINEG
#define ENDLINEG (s) (INT)((stb.stg_base)[s].w14)
Definition at line 103 of file flang2/utils/symtab/symtab.in.h.
ENDLINEP
#define ENDLINEP (s, v) (INT)((stb.stg_base)[s].w14 = (v))
Definition at line 104 of file flang2/utils/symtab/symtab.in.h.
FUNCLINEG
#define FUNCLINEG (s) (INT)((stb.stg_base)[s].w14)
Definition at line 105 of file flang2/utils/symtab/symtab.in.h.
FUNCLINEP
#define FUNCLINEP (s, v) (INT)((stb.stg_base)[s].w14 = (v))
Definition at line 106 of file flang2/utils/symtab/symtab.in.h.
GREALG
#define GREALG (s) (INT)((stb.stg_base)[s].w10)
Definition at line 121 of file flang2/utils/symtab/symtab.in.h.
GREALP
#define GREALP (s, v) (INT)((stb.stg_base)[s].w10 = (v))
Definition at line 122 of file flang2/utils/symtab/symtab.in.h.
GSAMEG
#define GSAMEG (s) (INT)((stb.stg_base)[s].w14)
Definition at line 107 of file flang2/utils/symtab/symtab.in.h.
GSAMEP
#define GSAMEP (s, v) (INT)((stb.stg_base)[s].w14 = (v))
Definition at line 108 of file flang2/utils/symtab/symtab.in.h.
ILMG
#define ILMG (s) (INT)((stb.stg_base)[s].w14)
Definition at line 109 of file flang2/utils/symtab/symtab.in.h.
ILMP
#define ILMP (s, v) (INT)((stb.stg_base)[s].w14 = (v))
Definition at line 110 of file flang2/utils/symtab/symtab.in.h.
IS_THREAD_TLS
#define IS_THREAD_TLS (s) (THREADG(s) && IS_TLS(s))
Definition at line 172 of file flang2/utils/symtab/symtab.in.h.
IS_THREAD_TP
#define IS_THREAD_TP (s) (THREADG(s) && (!IS_TLS(s)))
Definition at line 173 of file flang2/utils/symtab/symtab.in.h.
IS_TLS
#define IS_TLS (s) (TLSG(s) || ETLSG(s))
Definition at line 171 of file flang2/utils/symtab/symtab.in.h.
IS_TLS_GETTER
#define IS_TLS_GETTER (sptr) IS_TLS(sptr)
Definition at line 175 of file flang2/utils/symtab/symtab.in.h.
IS_TLS_WRAPPER
#define IS_TLS_WRAPPER (sptr) (0)
Definition at line 174 of file flang2/utils/symtab/symtab.in.h.
LOCAL_SYMNAME
#define LOCAL_SYMNAME (p) local_sname(SYMNAME(p))
Definition at line 153 of file flang2/utils/symtab/symtab.in.h.
NML_LINENO
#define NML_LINENO (i) aux.nml_base[i].lineno
Definition at line 246 of file flang2/utils/symtab/symtab.in.h.
NML_NEXT
#define NML_NEXT (i) aux.nml_base[i].next
Definition at line 245 of file flang2/utils/symtab/symtab.in.h.
NML_SPTR
#define NML_SPTR (i) aux.nml_base[i].sptr
Definition at line 244 of file flang2/utils/symtab/symtab.in.h.
NOSYM
#define NOSYM ((SPTR)1)
Definition at line 160 of file flang2/utils/symtab/symtab.in.h.
ORIGDUMMYG
#define ORIGDUMMYG (s) (INT)((stb.stg_base)[s].w32)
Definition at line 114 of file flang2/utils/symtab/symtab.in.h.
ORIGDUMMYP
#define ORIGDUMMYP (s, v) (INT)((stb.stg_base)[s].w32 = (v))
Definition at line 115 of file flang2/utils/symtab/symtab.in.h.
PARAMVALG
#define PARAMVALG (s) ((stb.stg_base)[s].w15)
Definition at line 130 of file flang2/utils/symtab/symtab.in.h.
PARAMVALP
#define PARAMVALP (s, v) ((stb.stg_base)[s].w15 = (v))
Definition at line 131 of file flang2/utils/symtab/symtab.in.h.
PDALN_EXPLICIT_0
#define PDALN_EXPLICIT_0 0xf
Definition at line 134 of file flang2/utils/symtab/symtab.in.h.
PDALN_IS_DEFAULT
#define PDALN_IS_DEFAULT (s) ((b4G(s)&0x0f) == 0)
Definition at line 137 of file flang2/utils/symtab/symtab.in.h.
PDALNG
#define PDALNG (s) ((b4G(s)&0x0f) == PDALN_EXPLICIT_0 ? 0 : (b4G(s)&0x0f))
Definition at line 135 of file flang2/utils/symtab/symtab.in.h.
PDALNP
#define PDALNP (s, v) b4P(s, (b4G(s)&0xf0) | ((v) == 0 ? PDALN_EXPLICIT_0 : (v)))
Definition at line 136 of file flang2/utils/symtab/symtab.in.h.
RETADJG
#define RETADJG (s) ((stb.stg_base)[s].w10)
Definition at line 156 of file flang2/utils/symtab/symtab.in.h.
RETADJP
#define RETADJP (s, v) ((stb.stg_base)[s].w10 = (v))
Definition at line 157 of file flang2/utils/symtab/symtab.in.h.
RFCNTD
#define RFCNTD (s) (--RFCNTG(s))
Definition at line 155 of file flang2/utils/symtab/symtab.in.h.
RFCNTI
#define RFCNTI (s) (++RFCNTG(s))
Definition at line 154 of file flang2/utils/symtab/symtab.in.h.
SC_AUTO
#define SC_AUTO SC_LOCAL
Definition at line 73 of file flang2/utils/symtab/symtab.in.h.
SC_ISCMBLK
#define SC_ISCMBLK (p) (p == SC_CMBLK)
Definition at line 74 of file flang2/utils/symtab/symtab.in.h.
SFDSCG
#define SFDSCG (s) (INT)((stb.stg_base)[s].w10)
Definition at line 123 of file flang2/utils/symtab/symtab.in.h.
SFDSCP
#define SFDSCP (s, v) (INT)((stb.stg_base)[s].w10 = (v))
Definition at line 124 of file flang2/utils/symtab/symtab.in.h.
ST_ISVAR
#define ST_ISVAR (s) ((s) >= ST_VAR && (s) <= ST_UNION)
Definition at line 23 of file flang2/utils/symtab/symtab.in.h.
SYMI_NEXT
#define SYMI_NEXT (i) aux.symi_base[i].next
Definition at line 256 of file flang2/utils/symtab/symtab.in.h.
SYMI_SPTR
#define SYMI_SPTR (i) aux.symi_base[i].sptr
Definition at line 255 of file flang2/utils/symtab/symtab.in.h.
SYMNAME
#define SYMNAME (p) (stb.n_base + NMPTRG(p))
Definition at line 151 of file flang2/utils/symtab/symtab.in.h.
SYMNAMEG
#define SYMNAMEG (p, buff, len) len = NMLENG(p); strncpy(buff,SYMNAME(p),len)
Definition at line 152 of file flang2/utils/symtab/symtab.in.h.
TY_FLOAT
#define TY_FLOAT TY_REAL
Definition at line 28 of file flang2/utils/symtab/symtab.in.h.
TY_ISBASIC
#define TY_ISBASIC (t) (dttypes[t]&_TY_BASIC)
Definition at line 57 of file flang2/utils/symtab/symtab.in.h.
TY_ISCMPLX
#define TY_ISCMPLX (t) (dttypes[t]&_TY_CMPLX)
Definition at line 55 of file flang2/utils/symtab/symtab.in.h.
TY_ISDWORD
#define TY_ISDWORD (t) (dttypes[t]&_TY_DWORD)
Definition at line 63 of file flang2/utils/symtab/symtab.in.h.
TY_ISINT
#define TY_ISINT (t) (dttypes[t]&_TY_INT)
Definition at line 53 of file flang2/utils/symtab/symtab.in.h.
TY_ISLOG
#define TY_ISLOG (t) (dttypes[t]&_TY_LOG)
Definition at line 60 of file flang2/utils/symtab/symtab.in.h.
TY_ISNUMERIC
#define TY_ISNUMERIC (t) (dttypes[t]&(_TY_INT|_TY_REAL|_TY_CMPLX))
Definition at line 56 of file flang2/utils/symtab/symtab.in.h.
TY_ISREAL
#define TY_ISREAL (t) (dttypes[t]&_TY_REAL)
Definition at line 54 of file flang2/utils/symtab/symtab.in.h.
TY_ISSCALAR
#define TY_ISSCALAR (t) (dttypes[t]&_TY_SCALAR)
Definition at line 59 of file flang2/utils/symtab/symtab.in.h.
TY_ISUNSIGNED
#define TY_ISUNSIGNED (t) (dttypes[t]&_TY_UNSIGNED)
Definition at line 58 of file flang2/utils/symtab/symtab.in.h.
TY_ISVEC
#define TY_ISVEC (t) (dttypes[t]&_TY_VEC)
Definition at line 61 of file flang2/utils/symtab/symtab.in.h.
TY_ISVECT
#define TY_ISVECT (t) (dttypes[t]&_TY_VECT)
Definition at line 64 of file flang2/utils/symtab/symtab.in.h.
TY_ISWORD
#define TY_ISWORD (t) (dttypes[t]&_TY_WORD)
Definition at line 62 of file flang2/utils/symtab/symtab.in.h.
TY_VECT_MAXLEN
#define TY_VECT_MAXLEN 16
Definition at line 66 of file flang2/utils/symtab/symtab.in.h.
VCON_CONVAL
#define VCON_CONVAL (i) aux.vcon_base[i]
Definition at line 298 of file flang2/utils/symtab/symtab.in.h.
XREFLKG
#define XREFLKG (s) ((stb.stg_base)[s].w16)
Definition at line 158 of file flang2/utils/symtab/symtab.in.h.
XREFLKP
#define XREFLKP (s, v) ((stb.stg_base)[s].w16 = (v))
Definition at line 159 of file flang2/utils/symtab/symtab.in.h.
Typedef Documentation
ADSC
typedef struct ADSC ADSC
AUX
typedef struct AUX AUX
DVL
typedef struct DVL DVL
ENTRY
typedef struct ENTRY ENTRY
etls_levels
typedef enum etls_levels etls_levels
NMLDSC
typedef struct NMLDSC NMLDSC
SWEL
typedef struct SWEL SWEL
SYMI
typedef struct SYMI SYMI
Enumeration Type Documentation
etls_levels
enum etls_levels
Enumerator
ETLS_PROCESS
ETLS_TASK
ETLS_THREAD
ETLS_OMP
ETLS_PROCESS
ETLS_TASK
ETLS_THREAD
ETLS_OMP
ETLS_NUM_LEVELS
Definition at line 162 of file flang2/utils/symtab/symtab.in.h.
Function Documentation
add_symitem()
int add_symitem (int sptr, int nxt)
...
Definition at line 3181 of file symtab.c.
References aux, i, NEED, sptr, AUX::symi_avl, AUX::symi_base, SYMI_NEXT, AUX::symi_size, and SYMI_SPTR.
Referenced by add_only(), add_overload(), apply_use(), check_doconcurrent(), check_doconcurrent_ast(), import(), import_use_stmts(), sem_import_sym(), semant1(), and semant3().
adddupsym()
SPTR adddupsym (SPTR oldsptr)
Add a new symbol with same name as an existing symbol.
Parameters
oldsptr symbol to duplicate
Definition at line 2116 of file symtab.cpp.
References NEWSYM, and sptr.
addnewsym()
SPTR addnewsym (const char * name)
Add a new symbol with given name.
Parameters
name the symbol's name
Definition at line 2107 of file symtab.cpp.
References name, NEWSYM, putsname(), sptr, and strlen().
Referenced by create_static_base(), get_entries_argnum(), and ll_make_kmpc_struct_type().
dbg_symdentry()
int dbg_symdentry (int sptr)
...
Definition at line 3216 of file symtab.c.
References sptr, and symdentry().
dmp_socs()
void dmp_socs (int sptr, FILE * file)
...
Definition at line 1695 of file symtab.c.
References SOC::base, p, q, soc, SOC_NEXT, SOC_SPTR, sptr, and SYMNAME.
Referenced by symdentry().
get_acon()
SPTR get_acon (SPTR sym, ISZ_T off)
...
Definition at line 601 of file symtab.c.
References DT_CPTR, get_acon3(), and off.
Referenced by ad_acon(), ad_aconi(), ad_aconk(), addarth(), cngcon(), exp_ac(), exp_type_bound_proc_call(), getstrconst(), ll_make_kmpc_fork_call(), and ll_make_kmpc_fork_teams().
get_acon3()
SPTR get_acon3 (SPTR sym, ISZ_T off, DTYPE dtype)
...
Definition at line 611 of file symtab.c.
References ACONOFFG, ACONOFFP, ADDSYM, bgitoi64(), HASH_CON, STB::hashtb, off, sptr, stb, and value().
Referenced by get_acon(), redundantLdLdElim(), widenProcessDirectLoad(), and widenProcessIndirectLoad().
get_entry_item()
int get_entry_item (void)
...
Definition at line 1835 of file symtab.cpp.
References aux, AUX::entry_avail, AUX::entry_base, AUX::entry_size, NEED, and NEW.
get_isz_cval()
ISZ_T get_isz_cval (int con)
...
Definition at line 650 of file symtab.c.
References assert, CONVAL2G, DT_ISINT, DT_ISLOG, ERR_unused, get_int_cval(), INT64_2_ISZ, ISZ_T, num, size_of(), and XBIT.
Referenced by ad_val_of(), arrayref_size(), ast_cval(), compute_sdsc_subscr(), compute_size_ast(), compute_size_expr(), conform_shape(), create_array_subscr(), DBGcnst(), decl_private_sym(), dinit_data(), eval(), exp_fstring(), exp_smp(), get_ival(), init_fold_const(), inlarr(), lbound_of_shape(), ref_pd(), semant1(), set_assumed_bounds(), small_enough(), and ubound_of_shape().
get_semaphore()
SPTR get_semaphore (void)
...
Definition at line 2047 of file symtab.cpp.
References AD_DPTR, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_SCHECK, AD_UPBD, AD_ZBASE, dt, DT_INT, get_array_dtype(), getcon(), getsym(), STB::i1, name, and stb.
get_vcon()
SPTR get_vcon (INT * value, DTYPE dtype)
...
Definition at line 437 of file symtab.cpp.
References ADDSYM, aux, STB::dt, DTyVecLength, HASH_CON, STB::hashtb, i, n, NEED, sptr, stb, value(), AUX::vcon_avl, AUX::vcon_base, VCON_CONVAL, and AUX::vcon_size.
Referenced by gen_resized_vect(), get_vcon0(), get_vcon0_n(), get_vcon1(), get_vcon_scalar(), get_vconi(), and get_vconm0().
get_vcon0()
int get_vcon0 (DTYPE dtype)
...
...
Definition at line 507 of file symtab.cpp.
References assert, CONVAL2G, STB::dbl0, DTY, DTySeqTyElement, DTyVecLength, ERR_Severe, STB::flt0, get_vcon(), i, STB::k0, n, stb, TY_DBLE, TY_FLOAT, TY_INT8, TY_LOG8, TY_VECT_MAXLEN, vc0, and zero.
Referenced by gen_scalar_to_vector_helper(), and get_vconm0().
get_vcon1()
int get_vcon1 (DTYPE dtype)
...
Definition at line 546 of file symtab.cpp.
References assert, CONVAL2G, STB::dbl1, DTY, DTySeqTyElement, DTyVecLength, ERR_Severe, STB::flt1, get_vcon(), i, STB::k1, n, one, stb, TY_DBLE, TY_FLOAT, TY_INT8, TY_LOG8, TY_VECT_MAXLEN, and vc1.
get_vcon_scalar()
SPTR get_vcon_scalar (INT sclr, DTYPE dtype)
...
Definition at line 628 of file symtab.cpp.
References assert, DTyVecLength, ERR_Severe, get_vcon(), i, n, and TY_VECT_MAXLEN.
Referenced by addarth(), gen_binary_expr(), and gen_llvm_expr().
get_vconm0()
int get_vconm0 (DTYPE dtype)
get a vector constant of a zero which suits the element type
Definition at line 581 of file symtab.cpp.
References assert, CONVAL2G, STB::dbl0, dblm0, DT_DBLE, DT_FLOAT, DTY, DTySeqTyElement, DTyVecLength, ERR_Severe, STB::flt0, fltm0, get_vcon(), get_vcon0(), getcon(), i, n, stb, TY_DBLE, TY_FLOAT, TY_VECT_MAXLEN, val, vcm0, and zero.
Referenced by gen_binary_expr().
getccssym()
SPTR getccssym (const char * pfx, int n, SYMTYPE stype)
Create (or possibly reuse) a compiler created symbol whose name is of the form . <pfx> dddd where dddd is the decimal representation of n.
Definition at line 1659 of file symtab.cpp.
References STB::curr_scope, getsym(), i, n, name, sptr, stb, and strlen().
Referenced by getccssym_sc().
getccssym_sc()
SPTR getccssym_sc (const char * pfx, int n, SYMTYPE stype, SC_KIND sc)
Similar to getccssym, but storage class is an argument. Calls getccssym if the storage class is not private; if private, a 'p' is appended to the name.
Definition at line 1684 of file symtab.cpp.
References STB::curr_scope, getccssym(), getsym(), i, n, name, sptr, stb, and strlen().
getccsym()
SPTR getccsym (char letter, int n, SYMTYPE stype)
create (or possibly reuse) a compiler created symbol whose name is of the form . <letter> dddd where dddd is the decimal representation of n.
Definition at line 1604 of file symtab.cpp.
References getsym(), n, name, set_ccflags(), sptr, and strlen().
Referenced by getccsym_sc(), and getlab().
getccsym_copy()
SPTR getccsym_copy (SPTR oldsptr)
...
Definition at line 1722 of file symtab.cpp.
References STB::curr_scope, DT_ISINT, fname, getsym(), i, len, malloc(), name, sptr, stb, strlen(), and SYMNAME.
Referenced by exp_smp().
getccsym_sc()
SPTR getccsym_sc (char letter, int n, SYMTYPE stype, SC_KIND sc)
Similar to getccsym, but storage class is an argument. Calls getccsym if the storage class is not private; if private, a 'p' is appended to the name.
Definition at line 1629 of file symtab.cpp.
References getccsym(), getcctemp_sc(), n, name, and sptr.
getcctemp_sc()
SPTR getcctemp_sc (const char * name, SYMTYPE stype, SC_KIND sc)
Create (or possibly reuse) a compiler created temporary where the caller constructs the name and passes the storage class as an argument.
Definition at line 1648 of file symtab.cpp.
References getsym(), name, set_ccflags(), and strlen().
Referenced by getccsym_sc(), lcpu_temp(), and ncpus_temp().
getcon()
SPTR getcon (INT * value, DTYPE dtype)
...
...
If an entry for the constant already exists, return pointer to the existing entry instead.
...
Enter constant of given dtype and value into the symbol table and return pointer to it.
Parameters
value is the constant value (value[1] if 1 word).
dtype - tbw.
Definition at line 524 of file symtab.c.
References ADDSYM, CONVAL2G, CONVAL2P, DTY, HASH_CON, STB::hashtb, sptr, stb, TY_QUAD, and value().
Referenced by _adjustl(), _adjustr(), _dinit_acl(), _huge(), _make_mp_get_threadprivate(), _makezero(), _rd_token(), _repeat(), _trim(), _xtok(), ad_icon(), ad_kcon(), ad_kconi(), add_fp_constants(), addarth(), addili(), addother(), binop(), call_dtsfmt(), ch_substring(), check_ccon(), cngcon(), const_fold(), conv_int8_ilm(), convert_cnst(), copyLastItr(), create_threadprivate_dtype(), dinit_val(), do_dot(), do_reduction(), eval_abs(), eval_ceiling(), eval_do(), eval_floor(), eval_ishft(), eval_mod(), eval_scale(), eval_sqrt(), exp_ac(), exp_fstring(), exp_mac(), form_cmplx_const(), gen_abs_expr(), gen_binary_expr(), gen_dtio_args(), gen_extract_insert(), gen_llvm_expr(), gen_null_arg(), genNullArg(), get_bnd_con(), get_default_int_val(), get_kind_id(), get_len_parm_by_number(), get_mp_bind_type(), get_nondec(), get_number(), get_prefixed_int(), get_semaphore(), get_vconm0(), gethollerith(), ICON(), import_constant(), import_ptr_constant(), import_symbol(), init_fold_const(), init_negate_const(), log_negation(), lower_data_stmts(), lower_getintcon(), lower_getiszcon(), lower_getlogcon(), lower_getnull(), lower_getrealcon(), makeCopyprivArray(), mk_cval(), mk_cval1(), mk_isz_cval(), mk_smallest_val(), mkexpr1(), mkvarref(), mmul(), negate_const(), negate_const_be(), put_data(), read_symbol(), red_kadd(), ref_intrin(), ref_pd(), replace_by_zero(), replace_parms(), semant1(), semant2(), storechartmp(), sym_init(), transfer_load(), transform_ptr(), and write_operand().
getlab()
SPTR getlab (void)
...
return a compiler-created label – user labels begin with '.', compiler- created labels begin with ''. Compiler-created labels will be mapped to fortran 77 labels by astout.
Definition at line 2048 of file symtab.c.
References assert, getccsym(), getsymf(), STB::lbavail, stb, and TRUE.
Referenced by _exp_mp_atomic_update(), add_loop_preheader(), add_single_loop_exit(), addCopyinInplace(), bblock(), do_end(), end_or_err(), enter_lexical_block(), exit_lexical_block(), exp_agoto(), exp_end(), exp_smp(), gen_call_expr(), genswitch(), import_symbol(), insert_begin_scope_label(), insert_end_scope_label(), insert_jump_entry_instr(), lower_lab(), make_stmt(), makeCopyprivArray_tls(), mkbranch(), remove_returns(), semant1(), semant3(), and semsmp().
getnewccsym()
SPTR getnewccsym (char letter, int n, SYMTYPE stype)
Create (never reuse) a compiler created symbol whose name is of the form . <letter> dddd where dddd is the decimal representation of n.
Definition at line 1616 of file symtab.cpp.
References n, name, NEWSYM, putsname(), set_ccflags(), sptr, and strlen().
getntstring()
SPTR getntstring (const char * value)
Similar to getstring except the character string is null terminated.
Definition at line 729 of file symtab.cpp.
References getstring(), strlen(), and value().
getprint()
char * getprint (int sptr)
...
Parameters
sptr symbol table pointer
...
For symbols which are not constants, the name of the symbol is used. Constants are converted into the appropriate character representation.
Parameters
sptr - symbol table pointer
Definition at line 944 of file symtab.c.
References __log_print(), b, c, CONVAL2G, cprintf(), DTY, DTyCharLength, dtype, end, ERR_Informational, FLANG_FALLTHROUGH, interr(), len, STB::n_base, NEW, NULL, num, sptr, stb, string_length(), SYMNAME, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, and ui64toax().
Referenced by __print_nme(), _dump_one_ast(), _dumpilmtree(), _dumponeilm(), assn_static_off(), assn_stkoff(), bld_lhs(), bld_use(), can_copy_def(), const_prop(), def_ok(), delete_stores(), dsym(), dump_buff(), dump_cand(), dump_flowgraph(), dump_global(), dump_ind(), dump_loops(), dump_one_block(), dump_vinduc(), DumpnameHelper(), dumpsingleilm(), find_bivs(), findloop(), flow(), flowgraph(), function_init(), gen_address_operand(), get_loop_count(), getast(), getdtype(), ind_loop_init(), lower_end_contains(), lower_symbol(), lower_symbols(), malformed(), new_ivs(), only_one_ud(), parmprint(), plower(), prettytoken(), process_sptr_offset(), prsym(), prtsst(), putnme(), putpair(), putsym(), reg_assign1(), removest(), semantio(), single_ud(), sym_is_refd(), and symdentry().
getstring()
SPTR getstring (const char * value, int length)
Enter character constant into symbol table.
Parameters
value is the character string value
length is the length of character string
Returns
a pointer to the character constant in the symbol table.
If the constant was already in the table, returns a pointer to the existing entry instead.
Enter character constant into symbol table.
Parameters
value character string value
length length of character string
If the constant is already in the table, return pointer to the existing entry instead.
Definition at line 724 of file symtab.c.
References ADDSYM, CONVAL2G, DTY, DTyCharLength, get_type(), HASH_STR, STB::hashtb, i, length(), mk_cval(), STB::n_base, p, putsname(), sptr, SPTR_NULL, stb, TY_CHAR, and value().
Referenced by _adjustl(), _adjustr(), _get_token(), _makezero(), _rd_token(), _repeat(), _trim(), binop(), ch_substring(), chkcon(), cngcon(), crunch(), dinit_name(), dinit_val(), eval_adjustl(), eval_adjustr(), eval_init_op(), eval_repeat(), eval_trim(), fill_name(), gen_contig_check(), gen_dtio_arglist(), get_cstring(), get_fmtstr(), getntstring(), getstrconst(), hex2char(), hex2nchar(), import_constant(), lower_add_pghpf_commons(), lower_check_subscript(), mkvarref(), mod_add_subprogram(), process_bind(), put_name(), read_init(), read_symbol(), ref_intrin(), ref_pd(), semant1(), semant3(), semantio(), and transfer_load().
getstringaddr()
SPTR getstringaddr (SPTR sptr)
Definition at line 740 of file symtab.cpp.
References STB::firstusym, NEWSYM, sptr, and stb.
getsym()
SPTR getsym (const char * name, int olength)
...
...
Parameters
name symbol name
olength number of characters in the symbol name
Returns
pointer to new symbol
If there is already such a symbol, just return pointer to the existing symbol table entry.
...
Enter symbol with indicated name into symbol table, initialize the new entry.
Parameters
name is the symbol name.
olength is the number of characters in the symbol name.
Definition at line 460 of file symtab.c.
References STB::curr_scope, gbl, insert_sym(), installsym, name, setimplicit(), sptr, and stb.
Referenced by _rd_token(), cng_generic(), cng_inttyp(), cng_specific(), defer_arg_chk(), exp_misc(), get_kind_id(), get_semaphore(), getccssym(), getccssym_sc(), getccsym(), getccsym_copy(), getcctemp_sc(), getsymbol(), iface_intrinsic(), label_name(), make_new_funcsptr(), mkfunc(), newsym(), read_symbol(), semant1(), and vmk_prototype().
getsymbol()
SPTR getsymbol (const char * name)
...
...
Parameters
name is the symbol name.
Definition at line 445 of file symtab.c.
References getsym(), name, and strlen().
Referenced by __gen_conditional_dealloc(), _do_iface(), assn_sclrtemp(), ast_ioret(), at_local_mode(), bblock(), check_defined_io2(), decl_private_sym(), declare_type(), dummy_program(), enter_local_mode(), exit_local_mode(), fixup_nme(), gen_allocated_check(), gen_automatic_reallocation(), gen_conditional_alloc(), gen_fcn_sst(), gen_finalized_result(), gen_newer_intrin(), get_byval_local(), get_fmt_array(), get_intrinsic_oprsym(), get_iso_ptrtype(), get_next_sym(), get_next_sym_dt(), get_param_alias_var(), get_private_size(), get_stack_size(), getccssym(), getccsym(), getccsym_sc(), getsymf(), import(), import_mk_newsym(), import_symbol(), initFinalSub(), is_overlap_cmblk_var(), ll_make_ftn_outlined_params(), ll_make_kmpc_proto(), ll_make_kmpc_struct_type(), lldbg_create_deferred_len_string_type_mdnode(), llGetSym(), llMakeFtnOutlinedSignature(), makeOutlinedFunc(), mk_external_var(), mk_impsym(), mk_shared_list(), mk_struct_for_llvm_init(), mkfunc(), process_blockaddr_sptr(), ref_entry(), ref_pd(), resolve_defined_io(), resolveBind(), resolveImp(), restore_internal_subprograms(), rewrite_cmplxpart_rval(), semant1(), semant2(), semant3(), sym_init(), sym_mkfunc(), and tkn_alias_sym().
implicit_int()
void implicit_int (DTYPE default_int)
...
...
Definition at line 281 of file symtab.cpp.
References dtimplicit, and i.
Referenced by sym_init().
insert_sym()
SPTR insert_sym (SPTR first)
...
...
Definition at line 1776 of file symtab.cpp.
References assert, ERR_Fatal, first, HASH_ID, STB::hashtb, i, j, NEWSYM, NOSYM, setimplicit(), sptr, stb, strlen(), and SYMNAME.
insert_sym_first()
SPTR insert_sym_first (SPTR first)
...
...
Definition at line 1809 of file symtab.cpp.
References first, HASH_ID, STB::hashtb, i, NEWSYM, setimplicit(), sptr, stb, strlen(), and SYMNAME.
mk_prototype()
SPTR mk_prototype (const char * name, const char * attr, DTYPE resdt, int nargs, ...)
...
...
Use when not using the LLVM backend or when the signature given is known to cause regressions in testing.
Definition at line 2001 of file symtab.cpp.
References name, nargs, NO_LLVM_CALLBACK, and vmk_prototype().
mk_prototype_llvm()
SPTR mk_prototype_llvm (const char * name, const char * attr, DTYPE resdt, int nargs, ...)
...
...
Definition at line 2015 of file symtab.cpp.
References LLVM_CALLBACK, name, nargs, and vmk_prototype().
mkfunc()
SPTR mkfunc (const char * nmptr)
...
create a function ST item given a name
...
create a function ST item given a name
Definition at line 2157 of file symtab.c.
References DT_INT, gbl, getsym(), getsymbol(), sptr, strlen(), and sym_is_refd().
Referenced by allochartmp(), begin_entry(), cr_block(), efunc(), exp_ac(), exp_alloca(), exp_end(), exp_qjsr(), exp_restore_mxcsr(), exp_smp(), exp_strcpy(), exp_strx(), exp_szero(), exp_zqjsr(), ll_make_atomic_compare_xchg(), ll_make_atomic_load(), ll_make_atomic_store(), makeCall(), mkfunc_cncall(), mkfunc_sflags(), mkMemcpy(), and vmk_prototype().
newimplicit()
void newimplicit (int firstc, int lastc, DTYPE dtype)
Change settings for implicit variable types, character lengths.
Parameters
firstc characters delimiting range
lastc characters delimiting range
dtype new value assigned to range
Definition at line 760 of file symtab.cpp.
References assert, CNULL, dtimplicit, dtype, ERR_Fatal, ERR_Severe, ERR_Warning, error(), gbl, i, IMPL_INDEX, j, and set.
parmprint()
const char * parmprint (int sptr)
...
...
Parameters
sptr symbol table pointer
...
Parameters
sptr - symbol table pointer
Definition at line 892 of file symtab.c.
References buf, CONVAL2G, CONVAL2P, DT_INT, DT_LOG, DTY, dtype, getprint(), sptr, TY_BINT, TY_HOLL, TY_ISWORD, TY_SINT, and TY_WORD.
Referenced by putentry(), and symdentry().
pop_scope()
void pop_scope (void)
...
...
Definition at line 1853 of file symtab.cpp.
References STB::curr_scope, DBGBIT, gbl, HASHSIZE, STB::hashtb, i, j, sptr, stb, and SYMNAME.
pop_sym()
void pop_sym (int sptr)
...
...
...
remove a symbol from its hash list
Definition at line 2101 of file symtab.c.
References DBGBIT, gbl, HASH_ID, STB::hashtb, j, name, s, sptr, SPTR_NULL, stb, strlen(), and SYMNAME.
Referenced by add_predefined_ieeearith_module(), add_predefined_iso_fortran_env_module(), add_predefined_isoc_module(), clear_no_scope_sptr(), create_func_entry(), decl_procedure_sym(), declsym(), do_end(), end_association(), fill_links_symbol(), get_fval_array(), get_retval_derived_type(), gethost_dumlen(), iface_arg(), mk_external_var(), pop_scope_level(), pop_subprogram(), record_func_result(), ref_entry(), semant1(), and semant3().
reapply_implicit()
void reapply_implicit (void)
...
...
Definition at line 816 of file symtab.cpp.
References dtimplicit, DTySetFst, STB::firstusym, i, IMPL_INDEX, sptr, stb, and SYMNAME.
setimplicit()
void setimplicit (int sptr)
...
assign to the indicated symbol table entry, the current implicit dtype.
...
assign to the indicated symbol table entry, the current implicit dtype.
Definition at line 853 of file symtab.c.
References dtimplicit, i, IMPL_INDEX, sptr, and SYMNAME.
Referenced by find_outer_sym(), gen_fcn_sst(), getsym(), insert_sym(), insert_sym_first(), mklvalue(), mod_add_subprogram(), rewrite_cmplxpart_rval(), semant1(), semant2(), semant3(), and tkr_match().
sign_extend()
INT sign_extend (INT val, int width)
...
Sign extend an integer value of an indicated width (8, 16, 32); value returned is sign extended with respect to the host's int type.
...
Sign extend an integer value of an indicated width (8, 16, 32); value returned is sign extended with respect to the host's int type.
Definition at line 702 of file symtab.c.
References val, and w.
Referenced by cngcon(), and convert_cnst().
sym_init()
void sym_init (void)
...
Initialize symbol table for new user program unit.
...
Initialize symbol table for new user program unit.
Definition at line 72 of file symtab.c.
References add_fp_constants(), AUX::arrdsc_avl, AUX::arrdsc_base, AUX::arrdsc_size, assert, aux, SOC::avail, BCOPY, BZERO, chkstruct(), clear_vc(), cng_generic(), cng_inttyp(), cng_specific(), CONVAL2G, AUX::curr_entry, STB::dbl0, STB::dblm0, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, STB::dt, STB::dt_cmplx, DT_CMPLX, DT_DBLE, DT_DCMPLX, STB::dt_int, DT_INT, STB::dt_log, DT_LOG, DT_PTR, STB::dt_real, DT_REAL, dtimplicit, dtimplicitstack, DTY, DTySet, AUX::dvl_avl, AUX::dvl_base, AUX::dvl_size, STB::firstosym, STB::firstusym, flg, STB::flt0, STB::fltm0, gbl, getcon(), getsymbol(), getsymf(), HASHSIZE, STB::hashtb, i, STB::i0, STB::i1, FLG::i4, if(), implicit_int(), init_chartab(), init_implicit(), INT, intast_sym, FLG::ipa, STB::k0, STB::k1, STB::lbavail, NMLDSC::lineno, AUX::list, llmp_reset_uplevel(), STB::n_base, STB::n_size, STB::namavl, NEW, NMLDSC::next, SYMI::next, AUX::nml_avl, AUX::nml_base, AUX::nml_size, NOSYM, onlyentry, res, SYMUTL::sc, soc, sptr, NMLDSC::sptr, SYMI::sptr, stb, STG_NEXT_SIZE, STG_RESET, sym_init_first(), AUX::symi_avl, AUX::symi_base, AUX::symi_size, symutl, tmp, STB::user, AUX::vtypes, XBIT, xdneg(), and xfneg().
Referenced by datastructure_reinit(), init(), and reinit().
symdentry()
void symdentry (FILE * file, int sptr)
...
Parameters
file the file
sptr symbol currently being dumped
file the file.
sptr symbol currently being dumped.
Definition at line 1093 of file symtab.c.
References _PFG, AD_DPTR, AD_LWBD, AD_NUMDIM, AD_UPBD, aux, buff, CMEMLG, CONVAL2G, DBGBIT, DEFLABG, DLL_EXPORT, DLL_IMPORT, DLLG, dmp_socs(), AUX::dpdsc_base, STB::dt, DT_DBLE, DT_FLOAT, DTY, DTyCharLength, dtype, DTySeqTyElement, DTyVecLength, ENDLINEG, ERR_Informational, f2, FILE, STB::firstusym, FUNCLINEG, getast(), getdtype(), getprint(), GREALG, GSAMEG, i, IGNORE_C, IGNORE_D, IGNORE_K, IGNORE_M, IGNORE_R, IGNORE_T, ILMG, INTENT_IN, INTENT_OUT, INTENTG, interr(), ISZ_PF, line, n, STB::n_base, NML_NEXT, NML_SPTR, ORIGDUMMYG, p, PARAMVALG, parmprint(), PDALN_IS_DEFAULT, PDALNG, putaltname(), putcuda(), STB::scnames, SFDSCG, sptr, stb, strlen(), STB::stypes, SYMI_NEXT, SYMI_SPTR, SYMNAME, TY_ISWORD, VCON_CONVAL, and WINNT_CALL.
Referenced by dbg_symdentry(), lower_symbol(), putsclass(), putstype(), and symdmp().
symdmp()
void symdmp (FILE * dfil, bool full)
...
...
Definition at line 1559 of file symtab.cpp.
References STB::firstusym, full, sptr, stb, and symdentry().
tr_conval2g()
int tr_conval2g (char * fn, int ln, int s)
...
Definition at line 2087 of file symtab.cpp.
References DTY, fn, s, and stb.
tr_conval2p()
int tr_conval2p (char * fn, int ln, int s, int v)
...
Definition at line 2096 of file symtab.cpp.
References DTY, fn, s, and stb.
Variable Documentation
aux
AUX aux extern
Definition at line 33 of file fenddf.c.
Referenced by _dmp_dent(), _do_iface(), _find_pointer_assignments_f90(), _linearize_func(), _stb_fixup_ifacearg(), add_symitem(), analyze_ret_info(), args_match(), assign1(), assumshp_args(), ast_init(), bld_ud(), check_defined_io2(), check_desc(), check_desc_args(), chk_adjarr(), chk_arguments(), chk_terminal_func(), cmp_interfaces(), cmp_interfaces_strict(), compat_arg_lists(), conflict(), const_prop(), copy_inargs(), count_formal_args(), create_llvm_display_temp(), declare_array_dummys(), desc_need_arrays(), dinit_acl_val2(), dinit_val(), dumpdvl(), dumpdvls(), dumplists(), dumpsymi(), dup_array_dtype(), eliminate_unused_variables(), exp_call(), exp_end(), exp_header(), exp_init(), export_dt(), export_some_args(), export_some_procedure(), export_symbol(), extract_shape_from_args(), fill_ast(), fill_entry_bounds(), find_by_name_stype_arg(), find_operator(), fix_args(), fix_class_args(), fix_iface(), fix_iface0(), fix_proc_ptr_dummy_args(), fix_symbol(), fix_symtab(), func_call2(), func_has_char_args(), gen_array_result(), get_arg_table(), get_aux_arrdsc(), get_entret_arg_name(), get_entries_argnum(), get_entry_item(), get_generic_member2(), get_type_descr_dummy(), get_vcon(), get_vector_dtype(), handle_arguments(), has_opt_args(), have_class_args_been_fixed_already(), iface_intrinsic(), import(), inc_dummy_param(), incr_invobj_for_retval_add(), init_newargs(), initFinalSub(), inject_arg(), insert_jump_entry_instr(), install_dtype(), instantiate_interface(), interface_for_entry(), interface_for_llvmiface(), is_arg_in_entry(), is_argp_in_entry(), is_desc_needed(), is_ptrast_arg(), is_seq_dummy(), ll_get_hostprog_arg(), ll_get_shared_arg(), ll_load_outlined_args(), ll_make_ftn_outlined_params(), ll_make_uplevel_type(), ll_process_routine_parameters(), llMakeFtnOutlinedSignature(), llvm_check_retval_inargs(), llvmAddConcurEntryBlk(), loadUplevelArgsForRegion(), lower_function(), lower_mark_entries(), lower_put_datatype(), lower_symbol(), lower_use_datatype(), lower_visit_symbol(), make_arg_copy(), make_keyword_str(), markmodified(), missing_optionals(), mk_charlen_address(), mod_add_subprogram(), mod_end_subprogram_two(), mr_end(), mr_init(), mth_i_atan(), mth_i_atan2(), mth_i_cosh(), mth_i_datan(), mth_i_datan2(), mth_i_dcosh(), mth_i_dsinh(), mth_i_dtanh(), mth_i_sinh(), mth_i_tanh(), needs_type_in_descr(), newargs_for_entry(), pop_subprogram(), pp_entries(), pp_entries_mixedstrlen(), pp_params(), pp_params_mixedstrlen(), prepend_func_result_as_first_arg(), print_entry_subroutine(), print_header(), ptrsubr_call(), put_arg_table(), put_call(), putparam(), queue_dtype(), queue_symbol(), read_init(), read_symbol(), reduc_rank_dtype(), ref_pd(), reg_assign1(), reg_init(), reloc_byvalue_parameters(), reorder_args(), replace_arguments(), replace_fval_in_params(), resolveImp(), resolvePass(), rewrite_inlined_args(), rewrite_sub_args(), rewrite_subscr(), rewrite_triples(), rw_sym_state(), sc_local_passbyvalue(), semant1(), semCheckTbp(), semfin(), share_alnd(), share_secd(), stb_process_iface_chlen(), subr_call2(), sym_get_arg_sec(), sym_get_sec(), sym_init(), symdentry(), symtab_fini(), transform_call(), undouble_callee_args_f90(), undouble_callee_args_llvmf90(), upper(), use_dummy_desc(), and write_dummy_as_local_in_entry().
dttypes
short dttypes[TY_MAX+1] extern
switch_base
SWEL* switch_base extern
Definition at line 31 of file fenddf.c.
Referenced by addbran(), exp_agoto(), exp_build_agoto(), exp_cgoto(), gen_switch(), getswel(), mk_swlist(), mk_swtab(), mk_swtab_ll(), read_label(), semant3(), semant_init(), and semfin_free_memory().