flang: flow.c File Reference
flow.c File Reference
Optimizer submodule responsible for performing flow analysis Used by the optimizer and vectorizer.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "ast.h"
#include "nme.h"
#include "optimize.h"
#include "flow_util.h"
#include "pragma.h"
#include "symutl.h"
#include "fdirect.h"
#include "extern.h"
#include "rtlRtns.h"
#include "ilidir.h"
Classes
struct dilttg
struct LV_SETS
Macros
#define LIN(v) lv.sets[v].lin
#define LOUT(v) lv.sets[v].lout
#define LUSE(v) lv.sets[v].luse
#define LDEF(v) lv.sets[v].ldef
#define LUNV(v) lv.sets[v].lunv
Typedefs
typedef struct dilttg DILT
Functions
static int add_use (int, int, int, int)
static DEF * add_def (int, int, int, int, int)
static int new_storeitem (int nme)
static void localflow (void)
static void lflow_of_block (void)
static void clean_names (STL *stl)
static void build_ud (int tree)
static void build_do_init (int tree)
static void dump_global (LOGICAL inout)
static void reaching_defs (void)
static void du_ud (void)
static void add_du_ud (int def, int use)
static void chk_ptr_load (int nme)
static void add_store (int nme)
static LOGICAL const_prop (void)
static LOGICAL self_use (int use)
static LOGICAL can_prop_fg (int)
static LOGICAL can_prop_def (int)
static void live_var_init (void)
static void live_var_end (void)
static void live_var (void)
static void lv_print (BV *)
static void uninit_var_init (void)
static void uninit_var_end (void)
static void uninit_var (void)
static LOGICAL bld_ud (int, int *)
static int bld_use (int, LOGICAL)
static DEF * bld_lhs (int, int, LOGICAL, int)
static void _cr_nme (int ast, int *dummy)
static int copy_const (int)
static void new_ud (int astx)
static void new_du_ud (void)
static void flow_init (void)
static void create_nmes (void)
void flow (void)
void flow_end (void)
Cleanup up structures created by flow analysis and after a function has been optimized.
static void prntstl (STL *p)
int update_stl (int lpx, int nme)
Utility function to add a store item to a loop's store list.
LOGICAL is_live_in (int nme, int lp)
Utility functions to determine if a variable is live-in to a loop and live-out of a loop.
LOGICAL is_live_out (int nme, int lp)
LOGICAL is_initialized (int *bv, int nme)
static int bv_count (int *bv)
static void _rdfo (int v)
static void build_rdfo ()
void delete_stores (void)
Mark stores as deletable only if its uses follow the definition in the same block.
void use_before_def (void)
void add_new_uses (int loop, int where, int newilt, int expr)
Add use items for optimizable variables which occur in the ili expression which is a new expression being added to a flowgraph node (where) such as the preheader of the loop.
Variables
static int def_bv_len
static int cur_lp
static int cur_fg
static int cur_std
static STL * cur_stl
static int cur_callfg
static int cur_callinternal
static int first_use
static int num_uses
static int last_def
static LOGICAL local_again
static LOGICAL jumps_deleted
static LOGICAL do_lv
static LOGICAL do_unv
static int in_doinit = 0
struct {
int first
int last
} g_mark_use = {0, 0}
static DILT * dilt_l
struct {
int n
int bv_len
int bv_sz
BV * stg_base
LV_SETS * sets
BV * lp_stg_base
int lp_bv_sz
} lv
static int rdfon = 0
struct {
int val
Q_ITEM * f_q
Q_ITEM * l_q
} cp
Detailed Description
Optimizer submodule responsible for performing flow analysis Used by the optimizer and vectorizer.
NOTE: loops' store lists are "computed" during localflow (build_ud). To associate a names entry with a store item, the name's stl field is used (assumed to be initialized to zero). At the end of processing a loop, the names' stl fields are cleaned up.
Definition in file flow.c.
Macro Definition Documentation
LDEF
#define LDEF (v) lv.sets[v].ldef
Definition at line 106 of file flow.c.
LIN
#define LIN (v) lv.sets[v].lin
Definition at line 103 of file flow.c.
LOUT
#define LOUT (v) lv.sets[v].lout
Definition at line 104 of file flow.c.
LUNV
#define LUNV (v) lv.sets[v].lunv
Definition at line 107 of file flow.c.
LUSE
#define LUSE (v) lv.sets[v].luse
Definition at line 105 of file flow.c.
Typedef Documentation
DILT
typedef struct dilttg DILT
Function Documentation
_cr_nme()
static void _cr_nme (int ast, int * dummy) static
Definition at line 182 of file flow.c.
References _cr_nme(), a, add_arrnme(), ast, ASTLI_NEXT, ASTLI_SPTR, check_member(), dummy, FALSE, mk_id(), n, NME_UNK, NOSYM, NT_ARR, NT_MEM, NT_VAR, s, and ST_ISVAR.
Referenced by _cr_nme(), and create_nmes().
_rdfo()
static void _rdfo (int v) static
Definition at line 2414 of file flow.c.
References _rdfo(), FG_RDFO, FG_SUCC, interr(), p, PSI_NEXT, PSI_NODE, PSI_P_NULL, rdfon, RDFOVTX_NODE, and w.
Referenced by _rdfo(), and build_rdfo().
add_def()
static DEF * add_def (int nme, int lhs, int addr, int rhs, int precise) static
Definition at line 1598 of file flow.c.
References addr, bv_set(), cur_fg, cur_std, DEF_LNEXT, df, do_lv, do_unv, flg, i, last_def, LDEF, lhs, OPT::ndefs, NME_DEF, NULL, FLG::opt, opt, OPT_NEED, and XBIT.
Referenced by bld_lhs().
add_du_ud()
static void add_du_ud (int def, int use) static
Definition at line 2698 of file flow.c.
References def, UD_TAG::def, DEF_DU, DU_AREA, getitem(), UD_TAG::next, DU_TAG::next, use, DU_TAG::use, and USE_UD.
Referenced by add_use(), du_ud(), and new_du_ud().
add_new_uses()
void add_new_uses (int loop, int where, int newilt, int expr)
Add use items for optimizable variables which occur in the ili expression which is a new expression being added to a flowgraph node (where) such as the preheader of the loop.
This is necessary to track new uses of a variable added after the flow information has been created. For example, it's important that the induction process adds uses in the loop count value used by a bla instruction since this expression was not seen by the flow analysis; a later call to induction will not find all of an induction variable's uses if it was used in the bla count of a contained loop.
Along with creating new uses, the du's of the defs reaching the uses are updated.
WARNING: this will only work when the expression is stored into an optimizer created temporary; to be more general (i.e., when adding stores of user-variables), new def information will have to be added which is impossible since the size of each bit vector cannot be increased.
Definition at line 3452 of file flow.c.
References cur_fg, cur_lp, cur_std, first_use, gbl, new_du_ud(), new_ud(), num_uses, opt, OPTDBG, and use_hash_reset().
add_store()
static void add_store (int nme) static
Definition at line 1650 of file flow.c.
References cur_fg, cur_lp, FG_PTR_STORE, gbl, IS_EXTERN, is_ptr_safe(), ISSCALAR, LP_EXT_STORE, LP_PTR_STORE, mark(), new_storeitem(), NME_NM, NME_STL, NME_SYM, NME_TYPE, NT_ARR, NT_IND, NT_MEM, NT_UNK, NT_VAR, OPTDBG, STORE_TYPE, and XBIT.
Referenced by bld_lhs().
add_use()
static int add_use (int nme, int ilix, int addr, int precise) static
Definition at line 1487 of file flow.c.
References add_du_ud(), addr, bv_set(), BZERO, cur_fg, cur_std, def, DEF_ADDR, DEF_FG, DEF_GEN, DEF_LHS, DEF_NEXT, DEF_PRECISE, do_lv, do_unv, first_use, flg, gbl, in_doinit, LUSE, NME_DEF, NULL, num_uses, FLG::opt, opt, OPT_NEED, OPTDBG, TRUE, USE_ADDR, USE_AST, USE_DOINIT, USE_EXPOSED, USE_FG, use_hash_check(), use_hash_insert(), use_hash_lookup(), USE_NM, USE_PRECISE, USE_STD, USE_UD, and XBIT.
Referenced by bld_lhs(), and bld_use().
bld_lhs()
static DEF * bld_lhs (int lhs, int rhs, LOGICAL isarg, int precise) static
visit routine for the lhs of assignments
Definition at line 1221 of file flow.c.
References a, add_def(), add_store(), add_use(), ASD_NDIM, ASD_SUBS, ast, ast_traverse(), bld_ud(), check_member(), chk_ptr_load(), cur_fg, cur_lp, DEF_ADDR, DEF_FG, DEF_GEN, DEF_LHS, DEF_NEXT, df, FG_CS, FG_PAR, FG_PARSECT, FG_PTR_STORE, FLANG_FALLTHROUGH, g_mark_use, gbl, getitem(), getprint(), i, if(), interr(), IS_PRIVATE, is_ptr_safe(), lhs, loc_of(), LP_PARENT, LP_PTR_STORE, LP_STL_PAR, memsym_of_ast(), mk_id(), n, NME_SYM, NME_TYPE, NOSYM, NT_MEM, NULL, opt, OPTDBG, q, s, ST_ISVAR, STL_AREA, TRUE, USE_ARG, USE_NM, and XBIT.
Referenced by bld_ud(), and build_do_init().
bld_ud()
static LOGICAL bld_ud (int ast, int * dummy) static
pre-order visit routine called during traversal
Definition at line 657 of file flow.c.
References A_ARGCNTG, A_ISLVAL, A_OPTYPEG, arg, argt, ARGT_ARG, assert, ast, ast_traverse(), astb, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, aux, bld_lhs(), bld_ud(), bld_use(), check_member(), cnt, cur_callfg, cur_callinternal, cur_lp, STB::dbl1, df, AUX::dpdsc_base, DT_DBLE, DT_INT, FALSE, STB::flt1, getF90TmplSectRtn(), i, ASTB::i1, intent, INTENT_DFLT, INTENT_IN, INTENT_OUT, INTENTG, j, LP_FORALL, mk_binop(), mk_cnst(), mk_id(), n, needs_descriptor(), NULL, OP_ADD, PR_ACCASYNC, PR_ACCATTACH, PR_ACCBEGINDIR, PR_ACCCACHE, PR_ACCCACHEARG, PR_ACCCACHEDIR, PR_ACCCACHEREADONLY, PR_ACCCOLLAPSE, PR_ACCCOPY, PR_ACCCOPYIN, PR_ACCCOPYOUT, PR_ACCCREATE, PR_ACCCUDACALL, PR_ACCDATAREG, PR_ACCDETACH, PR_ACCDEVICEPTR, PR_ACCDEVICERES, PR_ACCDEVSYM, PR_ACCELLP, PR_ACCENDDATAREG, PR_ACCENDHOSTDATA, PR_ACCENDIMPDATAREG, PR_ACCENDKERNELS, PR_ACCENDPARCONSTRUCT, PR_ACCENDSCALARREG, PR_ACCENDSERIAL, PR_ACCFIRSTPRIVATE, PR_ACCFORCECOLLAPSE, PR_ACCGANG, PR_ACCGANGCHUNK, PR_ACCGANGDIM, PR_ACCHOST, PR_ACCHOSTDATA, PR_ACCIF, PR_ACCIMPDATAREG, PR_ACCIMPDATAREGX, PR_ACCINDEPENDENT, PR_ACCKERNEL, PR_ACCKERNELS, PR_ACCKLOOP, PR_ACCLOCAL, PR_ACCMIRROR, PR_ACCNOWAIT, PR_ACCNUMGANGS, PR_ACCNUMGANGS2, PR_ACCNUMGANGS3, PR_ACCNUMWORKERS, PR_ACCPARALLEL, PR_ACCPARCONSTRUCT, PR_ACCPARUNROLL, PR_ACCPCOPY, PR_ACCPCOPYIN, PR_ACCPCOPYOUT, PR_ACCPCREATE, PR_ACCPLOOP, PR_ACCPRESENT, PR_ACCPRIVATE, PR_ACCREDUCTION, PR_ACCREDUCTOP, PR_ACCREFLECT, PR_ACCSCALARREG, PR_ACCSEQ, PR_ACCSEQUNROLL, PR_ACCSERIAL, PR_ACCSHORTLOOP, PR_ACCSLOOP, PR_ACCTKLOOP, PR_ACCTPLOOP, PR_ACCTSLOOP, PR_ACCUNROLL, PR_ACCUPDATE, PR_ACCUPDATEDEVICE, PR_ACCUPDATEHOST, PR_ACCUSEDEVICE, PR_ACCUSEDEVICEIFP, PR_ACCVECTOR, PR_ACCVECUNROLL, PR_ACCVLENGTH, PR_ACCWAIT, PR_ACCWAITARG, PR_ACCWAITDIR, PR_ACCWORKER, PR_ENDKERNEL, PR_KERNEL, PR_KERNEL_BLOCK, PR_KERNEL_DEVICE, PR_KERNEL_GRID, PR_KERNEL_NEST, PR_KERNEL_STREAM, PR_KERNELBEGIN, PR_KERNELTILE, proc_arginfo(), procsym_of_ast(), stb, SYMNAME, top, TRUE, and void().
Referenced by bld_lhs(), bld_ud(), bld_use(), build_do_init(), and build_ud().
bld_use()
static int bld_use (int lval, LOGICAL isarg) static
visit routine for adding uses
Definition at line 1098 of file flow.c.
References a, add_use(), ASD_NDIM, ASD_SUBS, ast, ast_traverse(), bld_ud(), check_member(), chk_ptr_load(), FLANG_FALLTHROUGH, gbl, getprint(), i, interr(), loc_of(), memsym_of_ast(), mk_id(), n, NME_SYM, NME_TYPE, NOSYM, NT_MEM, NULL, OPTDBG, s, ST_ISVAR, TRUE, USE_ARG, and XBIT.
Referenced by bld_ud().
build_do_init()
static void build_do_init (int tree) static
Definition at line 1430 of file flow.c.
References ast, ast_traverse(), ast_unvisit(), ast_visit(), astb, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, bld_lhs(), bld_ud(), df, FALSE, g_mark_use, ASTB::i1, in_doinit, interr(), mk_id(), NULL, and opt.
Referenced by lflow_of_block().
build_rdfo()
static void build_rdfo () static
Definition at line 2433 of file flow.c.
References _rdfo(), OPT::dfn, FG_RDFO, interr(), OPT::num_nodes, opt, rdfon, and RDFOVTX_NODE.
Referenced by reaching_defs().
build_ud()
static void build_ud (int tree) static
Definition at line 641 of file flow.c.
References ast_traverse(), ast_unvisit(), ast_visit(), bld_ud(), cur_callfg, cur_callinternal, and NULL.
Referenced by lflow_of_block().
bv_count()
static int bv_count (int * bv) static
Definition at line 2369 of file flow.c.
References BV_BITS, count, i, OPT::ndefs, opt, and w.
Referenced by reaching_defs().
can_prop_def()
static LOGICAL can_prop_def (int def) static
Definition at line 3056 of file flow.c.
References basesym_of(), def, DEF_ADDR, DEF_NM, DEF_RHS, DTY, FALSE, sptr, TRUE, TY_CHAR, TY_NCHAR, and XBIT.
Referenced by const_prop(), and copy_const().
can_prop_fg()
static LOGICAL can_prop_fg (int fg) static
Definition at line 3047 of file flow.c.
References FALSE, fg, FG_CS, and TRUE.
Referenced by const_prop().
chk_ptr_load()
static void chk_ptr_load (int nme) static
Definition at line 1634 of file flow.c.
References cur_lp, is_ptr_safe(), and LP_PTR_LOAD.
Referenced by bld_lhs(), and bld_use().
clean_names()
static void clean_names (STL * stl) static
Definition at line 632 of file flow.c.
References NME_STL, STL_TAG::store, STORE_NEXT, and STORE_NM.
Referenced by lflow_of_block().
const_prop()
static LOGICAL const_prop (void) static
Definition at line 2727 of file flow.c.
References addnme(), aux, can_prop_def(), can_prop_fg(), copy_const(), cp, DEF_CONST, DEF_DU, DEF_FG, DEF_NM, DEF_PRECISE, DEF_RHS, DEF_STD, df, dump_global(), AUX::dvl_avl, DVL_CONVAL, DVL_SPTR, FALSE, FG_LABEL, FIRST_DEF, freearea(), gbl, GET_Q_ITEM, getprint(), is_sym_imp_live(), OPT::ndefs, DU_TAG::next, NME_SYM, NT_VAR, opt, OPTDBG, q, Q_AREA, Q_NULL, self_use(), single_ud(), TRUE, use, DU_TAG::use, USE_NM, USE_PRECISE, and XBIT.
Referenced by flow().
copy_const()
static int copy_const (int use) static
Definition at line 2875 of file flow.c.
References A_STDP, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), b, can_prop_def(), cp, CUDA_HOST, CUDAG, DEF_CONST, DEF_NEXT, DEF_SELF, DEF_STD, df, fgx, gbl, GET_Q_ITEM, is_optsym(), NME_DEF, OPTDBG, PR_ACCATTACH, PR_ACCCACHE, PR_ACCCACHEARG, PR_ACCCACHEDIR, PR_ACCCACHEREADONLY, PR_ACCCOPY, PR_ACCCOPYIN, PR_ACCCOPYOUT, PR_ACCCREATE, PR_ACCCUDACALL, PR_ACCDETACH, PR_ACCDEVICEPTR, PR_ACCDEVICERES, PR_ACCDEVSYM, PR_ACCENDHOSTDATA, PR_ACCFIRSTPRIVATE, PR_ACCHOSTDATA, PR_ACCLOCAL, PR_ACCMIRROR, PR_ACCPCOPY, PR_ACCPCOPYIN, PR_ACCPCOPYOUT, PR_ACCPCREATE, PR_ACCPRESENT, PR_ACCPRIVATE, PR_ACCREDUCTION, PR_ACCREFLECT, PR_ACCUPDATE, PR_ACCUPDATEDEVICE, PR_ACCUPDATEHOST, PR_ACCUSEDEVICE, PR_ACCUSEDEVICEIFP, q, sptr, STD_AST, tmp, use, USE_ADDR, USE_FG, and USE_STD.
Referenced by const_prop().
create_nmes()
static void create_nmes (void) static
Definition at line 163 of file flow.c.
References _cr_nme(), ast_traverse(), ast_unvisit(), ast_visit(), dmpnme(), NULL, OPTDBG, std, STD_AST, and STD_NEXT.
Referenced by flow().
delete_stores()
void delete_stores (void)
Mark stores as deletable only if its uses follow the definition in the same block.
In the future, we'll get rid of defs for which there are no uses – but before we do this, we need to determine the side effects of eliminating a def (and ilt) from a block.
Definition at line 3091 of file flow.c.
References def, DEF_DELETE, DEF_DU, DEF_FG, DEF_NM, DEF_STD, FALSE, FG_CS, FG_LABEL, FIRST_DEF, flg, gbl, getprint(), i, IS_PRIVATE, is_sym_imp_live(), OPT::ndefs, NME_SYM, NME_TYPE, NT_VAR, NULL, opt, OPTDBG, FLG::smp, STD_AST, STD_EX, STD_LINENO, unlnkilt(), and XBIT.
Referenced by optimize().
du_ud()
static void du_ud (void) static
Definition at line 2670 of file flow.c.
References add_du_ud(), bv_mem(), cur_fg, def, DEF_NEXT, FG_IN, gbl, i, NME_DEF, opt, OPTDBG, USE_EXPOSED, USE_FG, and USE_NM.
Referenced by flow().
dump_global()
static void dump_global (LOGICAL inout) static
Definition at line 3263 of file flow.c.
References assert, basesym_of(), bv_print(), UD_TAG::def, DEF_ADDR, DEF_ARG, DEF_CONFL, DEF_CONST, DEF_CSEL, DEF_DOEND, DEF_DOINIT, DEF_DU, DEF_FG, DEF_GEN, DEF_LHS, DEF_LNEXT, DEF_NEXT, DEF_NM, DEF_OTHER, DEF_PRECISE, DEF_RHS, DEF_SELF, DEF_STD, OPT::dfn, dumpname(), FG_FDEF, FG_IN, FG_LABEL, FG_OUT, FIRST_DEF, gbl, getprint(), i, j, LP_CALLFG, LP_CALLINTERNAL, LP_EXT_STORE, LP_JMP_TBL, LP_PTR_LOAD, LP_PTR_STORE, LP_QJSR, LP_STL, OPT::ndefs, UD_TAG::next, DU_TAG::next, OPT::nloops, NME_DEF, NME_SYM, NME_TYPE, nmeb, NT_VAR, NULL, opt, p, STORE_NEXT, STORE_NM, STORE_TYPE, SYMNAME, DU_TAG::use, USE_ADDR, USE_ARG, USE_AST, USE_CSE, USE_DOINIT, USE_EXPOSED, USE_FG, USE_NM, USE_PRECISE, USE_STD, USE_UD, and VTX_NODE.
Referenced by const_prop(), and flow().
flow()
void flow (void)
Definition at line 256 of file flow.c.
References dilttg::bih, const_prop(), create_nmes(), FLG::dbg, DBGBIT, dilt_l, DLT_AREA, dmpilt(), do_lv, do_unv, DU_AREA, du_ud(), dump_flowgraph(), dump_global(), dump_loops(), FALSE, FG_ALL, FG_FDEF, FG_IN, FG_LABEL, FG_LNEXT, FG_OUT, FG_XT, findloop(), flg, flow_end(), flow_init(), flowgraph(), freearea(), gbl, getprint(), HLOPT_ALL, i, dilttg::ilt, interr(), jumps_deleted, live_var(), live_var_end(), live_var_init(), local_again, localflow(), LP_CS, LP_CSECT, LP_EXT_STORE, LP_MASTER, LP_PARREGN, LP_PARSECT, LP_PTR_LOAD, LP_PTR_STORE, LP_QJSR, LP_STL, LP_STL_PAR, dilttg::next, OPT::nloops, NME_STL, nmeb, NULL, OPT::num_nodes, FLG::opt, opt, OPTDBG, PSI_AREA, reaching_defs(), STL_AREA, TRUE, uninit_var(), uninit_var_end(), uninit_var_init(), unlnkilt(), and XBIT.
Referenced by comm_optimize_post(), comm_optimize_pre(), early_flow_init(), hlopt_init(), optimize(), optimize_alloc(), and sectfloat().
flow_end()
void flow_end (void)
Cleanup up structures created by flow analysis and after a function has been optimized.
Definition at line 427 of file flow.c.
References DEF_NM, OPT::def_setb, do_lv, FIRST_DEF, FREE, interr(), lv, OPT::ndefs, SET_BASE::nme_base, NME_DEF, nmeb, opt, SET_BASE::stg_base, and use_hash_free().
Referenced by flow(), optimize(), and optshrd_fend().
flow_init()
static void flow_init (void) static
Definition at line 136 of file flow.c.
References BZERO, FLG::dbg, DEF_ALL, DEF_FG, FIRST_DEF, flg, gbl, interr(), OPT::ndefs, NME_STL, nmeb, OPT::nsyms, opt, and use_hash_alloc().
Referenced by flow().
is_initialized()
LOGICAL is_initialized (int * bv, int nme)
Definition at line 2360 of file flow.c.
References bv_mem(), is_optsym(), lv, and TRUE.
Referenced by alldefs_allocsafe(), and ptrdefs_has_lhsconflict().
is_live_in()
LOGICAL is_live_in (int nme, int lp)
Utility functions to determine if a variable is live-in to a loop and live-out of a loop.
NOTE: conservative estimates currently in place for a variable which is unsafe (e.g., addrtkn, equivalenced, etc.); for addrtkn, more precise information involves checking arguments in bld_ud() and analyzing right- hand sides of assignments for acons. Similarly, conservative estimates for a static or external variable with respect to calls in the function.
Definition at line 2152 of file flow.c.
References bv_mem(), is_optsym(), is_sym_live_safe(), lp, LP_LIN, lv, TRUE, and XBIT.
Referenced by sfloat().
is_live_out()
LOGICAL is_live_out (int nme, int lp)
Definition at line 2164 of file flow.c.
References bv_mem(), is_optsym(), is_sym_live_safe(), lp, LP_LOUT, lv, TRUE, and XBIT.
Referenced by optimize(), and sfloat().
lflow_of_block()
static void lflow_of_block (void) static
Definition at line 546 of file flow.c.
References build_do_init(), build_ud(), clean_names(), close_pragma(), cur_callfg, cur_callinternal, cur_fg, cur_lp, cur_std, cur_stl, DEF_LNEXT, FG_CS, FG_DFN, FG_EX, FG_FDEF, FG_LINENO, FG_LNEXT, FG_LOOP, FG_MASTER, FG_PAR, FG_PARSECT, FG_STDFIRST, FG_TASK, FG_XT, first_use, gbl, last_def, LP_CALLFG, LP_CALLINTERNAL, LP_CS, LP_CSECT, LP_HEAD, LP_MASTER, LP_PARREGN, LP_PARSECT, LP_STL, LP_TASK, num_uses, open_pragma(), opt, OPTDBG, rdilts(), STD_AST, STD_EX, STD_NEXT, use_hash_reset(), and wrilts().
Referenced by localflow().
live_var()
static void live_var (void) static
Definition at line 2010 of file flow.c.
References bv_copy(), bv_notequal(), bv_sub(), bv_union(), bv_zero(), OPT::dfn, f_q, FG_INQ, FG_PRED, FG_SUCC, freearea(), gbl, GET_Q_ITEM, i, Q_TAG::info, l_q, LDEF, LIN, LOUT, LUSE, lv, lv_print(), Q_TAG::next, opt, OPTDBG, p, PSI_NEXT, PSI_NODE, PSI_P_NULL, q, Q_AREA, Q_NULL, and VTX_NODE.
Referenced by flow().
live_var_end()
static void live_var_end (void) static
Definition at line 1893 of file flow.c.
References bv_copy(), bv_union(), bv_zero(), BZERO, CNULL, error(), OPT::exitfg, FG_LOOP, FG_PRED, flg, FREE, gbl, i, j, LIN, LOUT, LP_EXITS, LP_HEAD, LP_LIN, LP_LOUT, lv, lv_print(), NEW, OPT::nloops, NULL, OPT::num_nodes, FLG::opt, opt, OPTDBG, p, PSI_NEXT, PSI_NODE, PSI_P_NULL, and XBIT.
Referenced by flow().
live_var_init()
static void live_var_init (void) static
Definition at line 1827 of file flow.c.
References BV_BITS, bv_set(), bv_zero(), CNULL, error(), OPT::exitfg, gbl, i, is_optsym(), is_sym_entry_live(), is_sym_exit_live(), LDEF, LIN, LOUT, LUNV, LUSE, lv, NEW, nmeb, NULL, OPT::num_nodes, opt, and OPTDBG.
Referenced by flow().
localflow()
static void localflow (void) static
Definition at line 477 of file flow.c.
References astb, STL_TAG::childlst, cur_fg, cur_lp, cur_stl, FG_LNEXT, gbl, getitem(), i, interr(), lflow_of_block(), LP_CALLFG, LP_CALLINTERNAL, LP_CSECT, LP_EXT_STORE, LP_JMP_TBL, LP_LOOP, LP_NOBLA, LP_PARENT, LP_PARREGN, LP_PARSECT, LP_PTR_LOAD, LP_PTR_STORE, LP_QJSR, LP_STL, STL_TAG::nextsibl, OPT::nloops, opt, OPTDBG, p, parent, prntstl(), STL_AREA, STL_TAG::store, and tmp.
Referenced by flow().
lv_print()
static void lv_print (BV * bv) static
Definition at line 2116 of file flow.c.
References BV_BITS, gbl, i, j, lv, print_nme(), void(), and w.
Referenced by live_var(), live_var_end(), and uninit_var().
new_du_ud()
static void new_du_ud (void) static
Definition at line 3486 of file flow.c.
References add_du_ud(), assert, bv_mem(), bv_print(), bv_union(), bv_zero(), cur_lp, def, def_bv_len, DEF_NEXT, OPT::def_setb, DEF_STD, FG_LOOP, FG_OUT, FG_PRED, first_use, gbl, i, LP_HEAD, OPT::ndefs, NME_DEF, NULL, opt, OPTDBG, p, PSI_NEXT, PSI_NODE, PSI_P_NULL, STD_DELETE, SET_BASE::stg_base, USE_EXPOSED, and USE_NM.
Referenced by add_new_uses().
new_storeitem()
static int new_storeitem (int nme) static
Definition at line 1772 of file flow.c.
References CNULL, cur_stl, error(), NME_STL, opt, OPT_NEED, STL_TAG::store, STORE_NEXT, STORE_NM, and STORE_TYPE.
Referenced by add_store().
new_ud()
static void new_ud (int astx) static
Definition at line 3475 of file flow.c.
Referenced by add_new_uses().
prntstl()
static void prntstl (STL * p) static
Definition at line 451 of file flow.c.
References dumpname(), gbl, i, indent, NULL, p, prntstl(), STORE_NEXT, STORE_NM, and STORE_TYPE.
Referenced by localflow(), and prntstl().
reaching_defs()
static void reaching_defs (void) static
Definition at line 2478 of file flow.c.
References assert, build_rdfo(), BV_BITS, bv_copy(), bv_count(), bv_notequal(), bv_off(), bv_print(), bv_set(), bv_union(), bv_zero(), CALL_DEF, DBGBIT, def, DEF_ADDR, DEF_ARG, def_bv_len, DEF_FG, DEF_GEN, DEF_LNEXT, DEF_NEXT, DEF_NM, DEF_PRECISE, OPT::def_setb, OPT::dfn, FG_EN, FG_EX, FG_FDEF, FG_IN, FG_OUT, FG_PRED, FG_PTR_STORE, FG_QJSR, FG_RDFO, FG_SUCC, freearea(), gbl, i, OPT::ndefs, NEW, NME_DEF, opt, OPTDBG, p, PSI_NEXT, PSI_NODE, PSI_P_NULL, PTR_STORE_DEF, Q_AREA, QJSR_DEF, RDFOVTX_NODE, s, ss, SET_BASE::stg_avail, SET_BASE::stg_base, and top.
Referenced by flow().
self_use()
static LOGICAL self_use (int use) static
Definition at line 3031 of file flow.c.
References ast, def, DEF_NEXT, DEF_STD, FALSE, NME_DEF, std, STD_AST, TRUE, use, USE_NM, and USE_STD.
Referenced by const_prop().
uninit_var()
static void uninit_var (void) static
Definition at line 2246 of file flow.c.
References bv_copy(), bv_intersect(), bv_notequal(), bv_union(), bv_zero(), OPT::dfn, f_q, FG_DONE, FG_INQ, FG_SUCC, FG_UNINITED, Q_TAG::flag, freearea(), gbl, GET_Q_ITEM, i, Q_TAG::info, l_q, LDEF, LUNV, lv, lv_print(), Q_TAG::next, NULL, opt, OPTDBG, PSI_NEXT, PSI_NODE, PSI_P_NULL, q, Q_AREA, Q_NULL, and VTX_NODE.
Referenced by flow().
uninit_var_end()
static void uninit_var_end (void) static
Definition at line 2341 of file flow.c.
References BZERO, OPT::dfn, FG_DONE, FG_INQ, FREE, i, lv, OPT::num_nodes, opt, and VTX_NODE.
Referenced by flow().
uninit_var_init()
static void uninit_var_init (void) static
Definition at line 2177 of file flow.c.
References BV_BITS, bv_set(), bv_zero(), CNULL, OPT::def_setb, error(), OPT::exitfg, FG_UNINITED, i, is_optsym(), is_sym_entry_live(), is_sym_exit_live(), j, LDEF, LIN, LOUT, LUNV, LUSE, lv, NEW, SET_BASE::nme_avail, SET_BASE::nme_base, nmeb, NULL, OPT::num_nodes, and opt.
Referenced by flow().
update_stl()
int update_stl (int lpx, int nme)
Utility function to add a store item to a loop's store list.
The store is added after flow analysis has taken place; this is needed if we care about considering these stores for later analysis (e.g., the store could affect later invariancy tests). The store item is returned to the caller (could be an existing one). If one is created, its type is set to zero; the caller is responsible for setting it to 1 (variable address).
Definition at line 1799 of file flow.c.
References CNULL, error(), LP_STL, lpx, opt, OPT_NEED, STL_TAG::store, STORE_NEXT, STORE_NM, and STORE_TYPE.
use_before_def()
void use_before_def (void)
Definition at line 3170 of file flow.c.
References basesym_of(), bv_mem(), UD_TAG::def, DEF_ARG, DEF_FG, DEF_NEXT, DEF_OTHER, DEF_PRECISE, df, error(), FALSE, fg, FG_IN, FG_LABEL, FG_LINENO, FG_LOOP, FG_OUT, FG_PRED, gbl, INTENT_OUT, INTENTG, LP_HEAD, UD_TAG::next, NME_DEF, NULL, opt, p, PSI_NEXT, PSI_NODE, PSI_P_NULL, SYMNAME, TRUE, use, USE_ARG, USE_EXPOSED, USE_FG, USE_NM, and USE_UD.
Referenced by optimize().
Variable Documentation
bv_len
int bv_len
Definition at line 95 of file flow.c.
bv_sz
int bv_sz
Definition at line 96 of file flow.c.
struct { ... } cp
Referenced by __fort_allchn(), __fort_chn_1to1(), __fort_chn_1toN(), __fort_doit(), __fort_rbcstl(), __fortio_getnum(), __INT_T(), __reduction_slowpath(), _adjustl(), _adjustr(), _repeat(), _trim(), accpp(), addfile(), addinlfile(), alpha(), ch_substring(), classify_ac_type(), classify_dec(), classify_kernel_pragma(), classify_pgi_dir(), classify_pgi_pragma(), classify_pragma(), classify_smp(), cngcon(), collectIncludePaths(), const_prop(), conv_bint_ilm(), conv_int8_ilm(), conv_int_ilm(), conv_sint_ilm(), copy_const(), delete(), do_dot(), domodule(), eliminate_start(), emit_copy_section(), emit_overlap(), emit_scatterx_gatherx(), eval_adjustl(), eval_adjustr(), eval_repeat(), eval_trim(), fpp(), generate_copy(), generate_gather(), get_chain_pointer_closure(), get_nondec(), get_number(), get_prefixed_int(), holtonum(), inquire(), intrinsic_as_arg(), layout_struct_body(), lookup(), print_and_check(), restore_internal_subprograms(), tobinary(), and tobinary64().
cur_callfg
int cur_callfg static
Definition at line 61 of file flow.c.
Referenced by bld_ud(), build_ud(), and lflow_of_block().
cur_callinternal
int cur_callinternal static
Definition at line 61 of file flow.c.
Referenced by bld_ud(), build_ud(), and lflow_of_block().
cur_fg
int cur_fg static
Definition at line 59 of file flow.c.
Referenced by add_def(), add_new_uses(), add_store(), add_use(), bld_lhs(), du_ud(), lflow_of_block(), and localflow().
cur_lp
int cur_lp static
Definition at line 59 of file flow.c.
Referenced by add_new_uses(), add_store(), bld_lhs(), bld_ud(), chk_ptr_load(), lflow_of_block(), localflow(), and new_du_ud().
cur_std
int cur_std static
Definition at line 59 of file flow.c.
Referenced by add_def(), add_new_uses(), add_use(), and lflow_of_block().
cur_stl
STL* cur_stl static
Definition at line 60 of file flow.c.
Referenced by lflow_of_block(), localflow(), and new_storeitem().
def_bv_len
int def_bv_len static
Definition at line 57 of file flow.c.
Referenced by new_du_ud(), and reaching_defs().
dilt_l
DILT* dilt_l static
Definition at line 81 of file flow.c.
Referenced by flow().
do_lv
LOGICAL do_lv static
Definition at line 66 of file flow.c.
Referenced by add_def(), add_use(), flow(), and flow_end().
do_unv
LOGICAL do_unv static
Definition at line 69 of file flow.c.
Referenced by add_def(), add_use(), and flow().
f_q
Q_ITEM* f_q
Definition at line 2722 of file flow.c.
Referenced by live_var(), and uninit_var().
first
int first
Definition at line 72 of file flow.c.
first_use
int first_use static
Definition at line 62 of file flow.c.
Referenced by add_new_uses(), add_use(), lflow_of_block(), and new_du_ud().
struct { ... } g_mark_use
Referenced by bld_lhs(), and build_do_init().
in_doinit
int in_doinit = 0 static
Definition at line 70 of file flow.c.
Referenced by add_use(), and build_do_init().
jumps_deleted
LOGICAL jumps_deleted static
Definition at line 65 of file flow.c.
Referenced by flow().
l_q
Q_ITEM* l_q
Definition at line 2723 of file flow.c.
Referenced by live_var(), and uninit_var().
last
int last
Definition at line 73 of file flow.c.
last_def
int last_def static
Definition at line 63 of file flow.c.
Referenced by add_def(), and lflow_of_block().
local_again
LOGICAL local_again static
Definition at line 64 of file flow.c.
Referenced by flow().
lp_bv_sz
int lp_bv_sz
Definition at line 100 of file flow.c.
lp_stg_base
BV* lp_stg_base
Definition at line 99 of file flow.c.
struct { ... } lv
Referenced by __fortio_fcvt(), const_eval(), flow_end(), gentab(), is_initialized(), is_live_in(), is_live_out(), live_var(), live_var_end(), live_var_init(), lv_print(), small_enough(), uninit_var(), uninit_var_end(), and uninit_var_init().
n
int n
Definition at line 94 of file flow.c.
Referenced by _cr_nme(), bld_lhs(), bld_ud(), and bld_use().
num_uses
int num_uses static
Definition at line 62 of file flow.c.
Referenced by add_new_uses(), add_use(), and lflow_of_block().
rdfon
int rdfon = 0 static
Definition at line 2411 of file flow.c.
Referenced by _rdfo(), and build_rdfo().
sets
LV_SETS* sets
Definition at line 98 of file flow.c.
stg_base
BV* stg_base
Definition at line 97 of file flow.c.
val
int val
Definition at line 2721 of file flow.c.