flang: flow_util.c File Reference
flow_util.c File Reference
Utility functions for optimizer submodule responsible for performing flow analysis. Used by the optimizer and vectorizer in the frontend and backend.
#include "flow_util.h"
Functions
void use_hash_alloc ()
void use_hash_free ()
void use_hash_reset ()
static hash_key_t use_hash_key (bool high_bit, bool use_high, int high, int mid, int low)
void use_hash_insert (int usex, bool high_bit, bool use_match_ili, int ilix, int nmex, int iltx)
int use_hash_lookup (bool high_bit, bool use_match_ili, int ilix, int nmex, int iltx)
static void use_hash_dump_one (hash_key_t key, hash_data_t data, void *context)
void use_hash_dump ()
void use_hash_check (int usex, int lusex, bool found)
Variables
static hashmap_t use_hash = NULL
Detailed Description
Utility functions for optimizer submodule responsible for performing flow analysis. Used by the optimizer and vectorizer in the frontend and backend.
Definition in file flow_util.c.
Function Documentation
use_hash_alloc()
void use_hash_alloc ()
Definition at line 28 of file flow_util.c.
References hash_functions_direct, hashmap_alloc(), and use_hash.
Referenced by flow_init(), and use_hash_reset().
use_hash_check()
void use_hash_check (int usex, int lusex, bool found)
Definition at line 156 of file flow_util.c.
References assert, and ERR_Fatal.
Referenced by add_use().
use_hash_dump()
void use_hash_dump ()
Definition at line 146 of file flow_util.c.
References hashmap_iterate(), NULL, use_hash, and use_hash_dump_one().
use_hash_dump_one()
static void use_hash_dump_one (hash_key_t key, hash_data_t data, void * context) static
Definition at line 134 of file flow_util.c.
References dfile, and FILE.
Referenced by use_hash_dump().
use_hash_free()
void use_hash_free ()
Definition at line 37 of file flow_util.c.
References hashmap_clear(), hashmap_free(), NULL, and use_hash.
Referenced by flow_end(), and use_hash_reset().
use_hash_insert()
void use_hash_insert (int usex, bool high_bit, bool use_match_ili, int ilix, int nmex, int iltx)
Definition at line 102 of file flow_util.c.
References hashmap_replace(), INT2HKEY, use_hash, and use_hash_key().
Referenced by add_use().
use_hash_key()
static hash_key_t use_hash_key (bool high_bit, bool use_high, int high, int mid, int low) static
Definition at line 67 of file flow_util.c.
References assert, ERR_Fatal, NULL, and USE_HASH_BITS.
Referenced by use_hash_insert(), and use_hash_lookup().
use_hash_lookup()
int use_hash_lookup (bool high_bit, bool use_match_ili, int ilix, int nmex, int iltx)
Definition at line 119 of file flow_util.c.
References hashmap_lookup(), HKEY2INT, NULL, use_hash, and use_hash_key().
Referenced by add_use().
use_hash_reset()
void use_hash_reset ()
Definition at line 50 of file flow_util.c.
References use_hash, use_hash_alloc(), and use_hash_free().
Referenced by add_new_uses(), and lflow_of_block().
Variable Documentation
use_hash
hashmap_t use_hash = NULL static
Definition at line 22 of file flow_util.c.
Referenced by use_hash_alloc(), use_hash_dump(), use_hash_free(), use_hash_insert(), use_hash_lookup(), and use_hash_reset().