flang: flow_util.h File Reference
flow_util.h File Reference
#include "gbldefs.h"
#include "global.h"
#include "hash.h"
#include "error.h"
Macros
#define DEBUG_USE_HASH 0
#define USE_HASH_BITS 21
Functions
void use_hash_alloc ()
void use_hash_free ()
void use_hash_reset ()
void use_hash_insert (int usex, bool high_bit, bool use_match_ili, int ilix, int nmex, int iltx)
int use_hash_lookup (bool high_bit, bool use_match_ili, int ilix, int nmex, int iltx)
void use_hash_check (int usex, int lusex, bool found)
Macro Definition Documentation
DEBUG_USE_HASH
#define DEBUG_USE_HASH 0
Definition at line 17 of file flow_util.h.
USE_HASH_BITS
#define USE_HASH_BITS 21
Definition at line 20 of file flow_util.h.
Function Documentation
use_hash_alloc()
void use_hash_alloc ()
Definition at line 28 of file flow_util.c.
References hash_functions_direct, hashmap_alloc(), and use_hash.
Referenced by flow_init(), and use_hash_reset().
use_hash_check()
void use_hash_check (int usex, int lusex, bool found)
Definition at line 156 of file flow_util.c.
References assert, and ERR_Fatal.
Referenced by add_use().
use_hash_free()
void use_hash_free ()
Definition at line 37 of file flow_util.c.
References hashmap_clear(), hashmap_free(), NULL, and use_hash.
Referenced by flow_end(), and use_hash_reset().
use_hash_insert()
void use_hash_insert (int usex, bool high_bit, bool use_match_ili, int ilix, int nmex, int iltx)
Definition at line 102 of file flow_util.c.
References hashmap_replace(), INT2HKEY, use_hash, and use_hash_key().
Referenced by add_use().
use_hash_lookup()
int use_hash_lookup (bool high_bit, bool use_match_ili, int ilix, int nmex, int iltx)
Definition at line 119 of file flow_util.c.
References hashmap_lookup(), HKEY2INT, NULL, use_hash, and use_hash_key().
Referenced by add_use().
use_hash_reset()
void use_hash_reset ()
Definition at line 50 of file flow_util.c.
References use_hash, use_hash_alloc(), and use_hash_free().
Referenced by add_new_uses(), and lflow_of_block().