flang: fltfenv.c File Reference
fltfenv.c File Reference
Set ieee floating point environment.
#include <stdint.h>
#include <fenv.h>
Functions
int __fenv_fegetround (void)
int __fenv_fesetround (int rmode)
int __fenv_fegetexceptflag (fexcept_t *flagp, int exc)
int __fenv_fesetexceptflag (fexcept_t *flagp, int exc)
int __fenv_fetestexcept (int exc)
int __fenv_feclearexcept (int exc)
int __fenv_feraiseexcept (int exc)
int __fenv_feenableexcept (int exc)
int __fenv_fedisableexcept (int exc)
int __fenv_fegetexcept (void)
int __fenv_fegetenv (fenv_t *env)
int __fenv_feholdexcept (fenv_t *env)
int __fenv_fesetenv (fenv_t *env)
int __fenv_feupdateenv (fenv_t *env)
int __fenv_fesetzerodenorm (int uflow)
Unimplemented: Set (flush to zero) underflow mode.
int __fenv_fegetzerodenorm (void)
Unimplemented: Get (flush to zero) underflow mode.
Detailed Description
Set ieee floating point environment.
Definition in file fltfenv.c.
Function Documentation
__fenv_feclearexcept()
int __fenv_feclearexcept (int exc)
Definition at line 500 of file fltfenv.c.
__fenv_fedisableexcept()
int __fenv_fedisableexcept (int exc)
Definition at line 541 of file fltfenv.c.
__fenv_feenableexcept()
int __fenv_feenableexcept (int exc)
Definition at line 535 of file fltfenv.c.
Referenced by __ktrap().
__fenv_fegetenv()
int __fenv_fegetenv (fenv_t * env)
Definition at line 553 of file fltfenv.c.
References env.
__fenv_fegetexcept()
int __fenv_fegetexcept (void)
Definition at line 547 of file fltfenv.c.
__fenv_fegetexceptflag()
int __fenv_fegetexceptflag (fexcept_t * flagp, int exc)
Definition at line 482 of file fltfenv.c.
__fenv_fegetround()
int __fenv_fegetround (void)
Definition at line 470 of file fltfenv.c.
Referenced by __fortio_ecvt(), and __fortio_fcvt().
__fenv_fegetzerodenorm()
int __fenv_fegetzerodenorm (void)
Unimplemented: Get (flush to zero) underflow mode.
Returns
1 if flush to zero is set, 0 otherwise
Definition at line 682 of file fltfenv.c.
Referenced by __nextafter(), and __nextafterf().
__fenv_feholdexcept()
int __fenv_feholdexcept (fenv_t * env)
Definition at line 559 of file fltfenv.c.
References env.
__fenv_feraiseexcept()
int __fenv_feraiseexcept (int exc)
Definition at line 506 of file fltfenv.c.
__fenv_fesetenv()
int __fenv_fesetenv (fenv_t * env)
Definition at line 565 of file fltfenv.c.
References env.
__fenv_fesetexceptflag()
int __fenv_fesetexceptflag (fexcept_t * flagp, int exc)
Definition at line 488 of file fltfenv.c.
__fenv_fesetround()
int __fenv_fesetround (int rmode)
Definition at line 476 of file fltfenv.c.
__fenv_fesetzerodenorm()
int __fenv_fesetzerodenorm (int uflow)
Unimplemented: Set (flush to zero) underflow mode.
Parameters
uflow zero to allow denorm numbers, non-zero integer to flush to zero
Definition at line 672 of file fltfenv.c.
__fenv_fetestexcept()
int __fenv_fetestexcept (int exc)
Definition at line 494 of file fltfenv.c.
Referenced by _f90io_stop().
__fenv_feupdateenv()
int __fenv_feupdateenv (fenv_t * env)
Definition at line 571 of file fltfenv.c.
References env.