flang: fltmanip.c File Reference
fltmanip.c File Reference
#include "float128.h"
Macros
#define _MAXLONGDOUBLE (1.18973149535723176508575932662800702E+4932L)
#define IX_SIZE 4 /* ix[] has 4 element and 128 bits */
#define IZ_SIZE 2 /* iz[] has 4 element and 128 bits */
#define GET_SIGN 31
#define GET_EXP1 16
#define GET_EXP2 23
#define IS_ZERO(h, j, k, l) (((h) & 0x7fffffff) == 0) && (((l) | (k) | (j)) == 0)
#define IS_MIN_NORM(h, j, k, l, s) (((h) & 0x7fffffff) == 0x00010000) && (((l) | (k) | (j)) == 0) && (s)
#define IS_MAX_NORM(h, j, k, l, s)
#define _MAXDOUBLE (1.7976931348623157e+308)
#define _MAXFLOAT (3.40282347e+38F)
Functions
float __mth_i_around (float x)
float __mth_i_remainder (float x, float y)
double __mth_i_dround (double x)
double __mth_i_dremainder (double x, double y)
int __fenv_fegetzerodenorm (void)
Unimplemented: Get (flush to zero) underflow mode.
double __nearbyint (double x)
float __nearbyintf (float x)
double __remainder (double x, double y)
float __remainderf (float x, float y)
double __nextafter (double x, double y)
float __nextafterf (float x, float y)
double __scalbn (double x, int i)
float __scalbnf (float x, int i)
Macro Definition Documentation
_MAXDOUBLE
#define _MAXDOUBLE (1.7976931348623157e+308)
Definition at line 200 of file fltmanip.c.
_MAXFLOAT
#define _MAXFLOAT (3.40282347e+38F)
Definition at line 319 of file fltmanip.c.
_MAXLONGDOUBLE
#define _MAXLONGDOUBLE (1.18973149535723176508575932662800702E+4932L)
Definition at line 85 of file fltmanip.c.
GET_EXP1
#define GET_EXP1 16
Definition at line 89 of file fltmanip.c.
GET_EXP2
#define GET_EXP2 23
Definition at line 90 of file fltmanip.c.
GET_SIGN
#define GET_SIGN 31
Definition at line 88 of file fltmanip.c.
IS_MAX_NORM
#define IS_MAX_NORM (h, j, k, l, s)
Value:
                           (((h) & 0x7fffffff) == 0x7ffeffff) && (((~((l) & 0xffffffff)) | \
                           (~((k) & 0xffffffff)) | (~((j) & 0xffffffff))) == 0) && (!(s))
Definition at line 93 of file fltmanip.c.
IS_MIN_NORM
#define IS_MIN_NORM (h, j, k, l, s) (((h) & 0x7fffffff) == 0x00010000) && (((l) | (k) | (j)) == 0) && (s)
Definition at line 92 of file fltmanip.c.
IS_ZERO
#define IS_ZERO (h, j, k, l) (((h) & 0x7fffffff) == 0) && (((l) | (k) | (j)) == 0)
Definition at line 91 of file fltmanip.c.
IX_SIZE
#define IX_SIZE 4 /* ix[] has 4 element and 128 bits */
Definition at line 86 of file fltmanip.c.
IZ_SIZE
#define IZ_SIZE 2 /* iz[] has 4 element and 128 bits */
Definition at line 87 of file fltmanip.c.
Function Documentation
__fenv_fegetzerodenorm()
int __fenv_fegetzerodenorm (void)
Unimplemented: Get (flush to zero) underflow mode.
Returns
1 if flush to zero is set, 0 otherwise
Definition at line 682 of file fltfenv.c.
Referenced by __nextafter(), and __nextafterf().
__mth_i_around()
float __mth_i_around (float x)
Definition at line 13 of file around.c.
References roundf(), and x.
Referenced by __nearbyintf().
__mth_i_dremainder()
double __mth_i_dremainder (double x, double y)
Definition at line 13 of file dremainder.c.
References remainder(), x, and y.
Referenced by __remainder().
__mth_i_dround()
double __mth_i_dround (double x)
Definition at line 13 of file dround.c.
References round(), and x.
Referenced by __nearbyint().
__mth_i_remainder()
float __mth_i_remainder (float x, float y)
Definition at line 13 of file remainder.c.
References remainderf(), x, and y.
Referenced by __remainderf().
__nearbyint()
double __nearbyint (double x)
Definition at line 45 of file fltmanip.c.
References __mth_i_dround(), and x.
__nearbyintf()
float __nearbyintf (float x)
Definition at line 51 of file fltmanip.c.
References __mth_i_around(), and x.
__nextafter()
double __nextafter (double x, double y)
Definition at line 203 of file fltmanip.c.
References __fenv_fegetzerodenorm(), _MAXDOUBLE, iyl, x, and y.
__nextafterf()
float __nextafterf (float x, float y)
Definition at line 322 of file fltmanip.c.
References __fenv_fegetzerodenorm(), _MAXFLOAT, iy, x, and y.
__remainder()
double __remainder (double x, double y)
Definition at line 65 of file fltmanip.c.
References __mth_i_dremainder(), x, and y.
__remainderf()
float __remainderf (float x, float y)
Definition at line 71 of file fltmanip.c.
References __mth_i_remainder(), x, and y.
__scalbn()
double __scalbn (double x, int i)
Definition at line 415 of file fltmanip.c.
References i, iy, and x.
__scalbnf()
float __scalbnf (float x, int i)
Definition at line 457 of file fltmanip.c.
References i, iy, and x.