flang: flush.c File Reference
flush.c File Reference
Implements Fortran FLUSH statement.
#include "global.h"
#include "async.h"
Functions
int ENTF90IO (FLUSH, flush)
Detailed Description
Implements Fortran FLUSH statement.
Definition in file flush.c.
Function Documentation
ENTF90IO()
int ENTF90IO (FLUSH , flush)
Definition at line 17 of file flush.c.
References __fort_status_init(), __fortio_errend03(), __fortio_errinit03(), __fortio_error(), __fortio_find_unit(), __io_errno(), __io_fflush, fcb::asy_rw, fcb::asyptr, bitv, f, Fio_asy_disable(), FIO_EUNIT, fcb::fp, ILLEGAL_UNIT, and s.