flang: fmtconv.c File Reference
fmtconv.c File Reference
Utility module for converting the internal representation of a data item to string form.
#include <string.h>
#include "global.h"
#include "format.h"
#include "feddesc.h"
#include "stdioInterf.h"
Macros
#define DBGBIT(v) (LOCAL_DEBUG && (dbgflag & v))
#define PP_INT1(i) (*(__INT1_T *)(i))
#define PP_INT2(i) (*(__INT2_T *)(i))
#define PP_INT4(i) (*(__INT4_T *)(i))
#define PP_INT8(i) (*(__INT8_T *)(i))
#define PP_LOG1(i) (*(__LOG1_T *)(i))
#define PP_LOG2(i) (*(__LOG2_T *)(i))
#define PP_LOG4(i) (*(__LOG4_T *)(i))
#define PP_LOG8(i) (*(__LOG8_T *)(i))
#define PP_REAL4(i) (__fortio_chk_f((__REAL4_T *)(i)))
#define PP_REAL8(i) (*(__REAL8_T *)(i))
#define PP_REAL16(i) (*(__REAL16_T *)(i))
#define MAX_CONV_INT 32
#define MAX_HX 0x80000000
#define MAX_STR "2147483648"
#define MAX_CONV_INT8 32
Functions
static char * conv_int (__BIGINT_T, int *, int *)
static char * conv_int8 (DBLINT64, int *, int *)
static void put_buf (int, const char *, int, int)
static void conv_e (int, int, int, bool, int)
static void conv_en (int, int, bool)
static void conv_es (int, int, bool)
static void conv_f (int, int)
static void cvtp_cp (int)
static void cvtp_set (int, int)
static void alloc_fpbuf (int)
static char * strip_blnk (char *, char *)
static char * __fortio_fmt_z (unsigned int)
void __fortio_printbigreal (__BIGREAL_T val)
Generate a formated REAL*8 or REAL*16 string.
char * __fortio_default_convert (char *item, int type, int item_length, int *lenp, bool dc_flag, bool plus_flag, int round)
Drive the generation of output strings based on format strings.
char * __fortio_fmt_i (__BIGINT_T val, int width, int mn, bool plus_flag)
Generate a formated INTEGER string.
char * __fortio_fmt_i8 (DBLINT64 val, int width, int mn, bool plus_flag)
Generate a formated INTEGER*8 string.
char * __fortio_fmt_d (__BIGREAL_T val, int w, int d, int sf, int type, bool plus_flag, int round)
Generate a string for a 'D' format characer.
char * __fortio_fmt_g (__BIGREAL_T val, int w, int d, int e, int sf, int type, bool plus_flag, bool e_flag, bool dc_flag, int round, int is_quad)
Generate a string for a 'G' format characer.
char * __fortio_fmt_e (__BIGREAL_T val, int w, int d, int e, int sf, int type, bool plus_flag, bool e_flag, bool dc_flag, int code, int round)
Generate a string for an 'E' format characer.
char * __fortio_fmt_f (__BIGREAL_T val, int w, int d, int sf, bool plus_flag, bool dc_flag, int round)
Generate a string for an 'F' format characer.
__BIGREAL_T __fortio_chk_f (__REAL4_T *f)
Convert REAL*4 to REAL4*8.
Variables
static int dbgflag
static int field_overflow
char __f90io_conv_buf [96] = {0}
static char * conv_bufp = __f90io_conv_buf
static size_t conv_bufsize = sizeof(__f90io_conv_buf)
static char cmplx_buf [64]
static char exp_letter = 'E'
static char * buff_pos
static char fpbuf [64]
struct {
int exp
int sign
int ndigits
int decimal_char
bool iszero
char * cvtp
char * curp
char * buf
int bufsize
__BIGREAL_T zero
} fpdat = {0, 0, 0, '.', 0, 0, 0, fpbuf, sizeof(fpbuf), 0.0}
static char hextab [17] = "0123456789ABCDEF"
Detailed Description
Utility module for converting the internal representation of a data item to string form.
__fortio_default_convert() - conversion routine which applies the default editing rules with respect to a data type.
__fortio_fmt_i() - Iw, Iw.m edit descrs.
__fortio_fmt_g() - Gw.d, Gw.dEe
__fortio_fmt_e() - Ew.d, Ew.dEe, ENw.d, ENw.dEe, ESw.d, ESw.dEe,
__fortio_fmt_d() - Dw.d
__fortio_fmt_f() - Fw.d
Definition in file fmtconv.c.
Macro Definition Documentation
DBGBIT
#define DBGBIT (v) (LOCAL_DEBUG && (dbgflag & v))
Definition at line 30 of file fmtconv.c.
MAX_CONV_INT
#define MAX_CONV_INT 32
MAX_CONV_INT8
#define MAX_CONV_INT8 32
MAX_HX
#define MAX_HX 0x80000000
MAX_STR
#define MAX_STR "2147483648"
PP_INT1
#define PP_INT1 (i) (*(__INT1_T *)(i))
Definition at line 51 of file fmtconv.c.
PP_INT2
#define PP_INT2 (i) (*(__INT2_T *)(i))
Definition at line 52 of file fmtconv.c.
PP_INT4
#define PP_INT4 (i) (*(__INT4_T *)(i))
Definition at line 53 of file fmtconv.c.
PP_INT8
#define PP_INT8 (i) (*(__INT8_T *)(i))
Definition at line 54 of file fmtconv.c.
PP_LOG1
#define PP_LOG1 (i) (*(__LOG1_T *)(i))
Definition at line 55 of file fmtconv.c.
PP_LOG2
#define PP_LOG2 (i) (*(__LOG2_T *)(i))
Definition at line 56 of file fmtconv.c.
PP_LOG4
#define PP_LOG4 (i) (*(__LOG4_T *)(i))
Definition at line 57 of file fmtconv.c.
PP_LOG8
#define PP_LOG8 (i) (*(__LOG8_T *)(i))
Definition at line 58 of file fmtconv.c.
PP_REAL16
#define PP_REAL16 (i) (*(__REAL16_T *)(i))
Definition at line 61 of file fmtconv.c.
PP_REAL4
#define PP_REAL4 (i) (__fortio_chk_f((__REAL4_T *)(i)))
Definition at line 59 of file fmtconv.c.
PP_REAL8
#define PP_REAL8 (i) (*(__REAL8_T *)(i))
Definition at line 60 of file fmtconv.c.
Function Documentation
__fortio_chk_f()
__BIGREAL_T __fortio_chk_f (__REAL4_T * f)
Convert REAL*4 to REAL4*8.
Definition at line 1188 of file fmtconv.c.
References u::d, d, f, u::i, i, and uf.
Referenced by fw_writenum().
__fortio_default_convert()
char * __fortio_default_convert (char * item, int type, int item_length, int * lenp, bool dc_flag, bool plus_flag, int round)
Drive the generation of output strings based on format strings.
Definition at line 89 of file fmtconv.c.
References __CPLX16, __CPLX32, __CPLX8, __f90io_conv_buf, __fortio_fmt_g(), __fortio_fmt_i(), __fortio_fmt_i8(), __fortio_fmt_z(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL16, __REAL4, __REAL8, __STR, __WORD16, __WORD4, __WORD8, assert, buff_pos, cmplx_buf, conv_bufp, conv_bufsize, FALSE, G_REAL16_D, G_REAL16_W, GET_FIO_CNFG_TRUE_MASK, I64_LSH, malloc(), p, PP_INT1, PP_INT2, PP_INT4, PP_LOG1, PP_LOG2, PP_LOG4, PP_REAL16, PP_REAL4, PP_REAL8, put_buf(), REAL16_E, REAL4_D, REAL4_E, REAL4_W, REAL8_D, REAL8_E, REAL8_W, round(), strip_blnk(), strlen(), TRUE, type, and void().
Referenced by __f90io_ldw(), and write_nml_val().
__fortio_fmt_d()
char * __fortio_fmt_d (__BIGREAL_T val, int w, int d, int sf, int type, bool plus_flag, int round)
Generate a string for a 'D' format characer.
Definition at line 512 of file fmtconv.c.
References __fortio_printbigreal(), __io_ecvt, __io_printf, conv_bufp, conv_e(), d, DBGBIT, exp_letter, FALSE, field_overflow, fpdat, put_buf(), round(), strlen(), TRUE, val, and w.
Referenced by fw_writenum().
__fortio_fmt_e()
char * __fortio_fmt_e (__BIGREAL_T val, int w, int d, int e, int sf, int type, bool plus_flag, bool e_flag, bool dc_flag, int code, int round)
Generate a string for an 'E' format characer.
Definition at line 704 of file fmtconv.c.
References __fortio_printbigreal(), __io_ecvt, __io_printf, conv_bufp, conv_e(), conv_en(), conv_es(), d, DBGBIT, e, FALSE, FED_ENw_d, FED_ESw_d, field_overflow, fpdat, put_buf(), round(), strlen(), TRUE, val, and w.
Referenced by fw_writenum().
__fortio_fmt_f()
char * __fortio_fmt_f (__BIGREAL_T val, int w, int d, int sf, bool plus_flag, bool dc_flag, int round)
Generate a string for an 'F' format characer.
Definition at line 775 of file fmtconv.c.
References __fortio_printbigreal(), __io_fcvt, __io_printf, conv_bufp, conv_f(), d, DBGBIT, FALSE, field_overflow, fpdat, p, put_buf(), round(), strlen(), TRUE, val, and w.
Referenced by fw_writenum().
__fortio_fmt_g()
char * __fortio_fmt_g (__BIGREAL_T val, int w, int d, int e, int sf, int type, bool plus_flag, bool e_flag, bool dc_flag, int round, int is_quad)
Generate a string for a 'G' format characer.
Definition at line 564 of file fmtconv.c.
References __fortio_printbigreal(), __io_ecvt, __io_fcvt, __io_printf, conv_bufp, conv_e(), conv_f(), d, DBGBIT, e, FALSE, field_overflow, fpdat, m, n, p, put_buf(), round(), strlen(), TRUE, val, and w.
Referenced by __fortio_default_convert(), and fw_writenum().
__fortio_fmt_i()
char * __fortio_fmt_i (__BIGINT_T val, int width, int mn, bool plus_flag)
Generate a formated INTEGER string.
Definition at line 266 of file fmtconv.c.
References conv_bufp, conv_int(), FALSE, field_overflow, i, len, neg(), p, put_buf(), TRUE, and val.
Referenced by __fortio_default_convert(), and fw_writenum().
__fortio_fmt_i8()
char * __fortio_fmt_i8 (DBLINT64 val, int width, int mn, bool plus_flag)
Generate a formated INTEGER*8 string.
Definition at line 346 of file fmtconv.c.
References conv_bufp, conv_int8(), FALSE, field_overflow, i, len, neg(), p, put_buf(), TRUE, and val.
Referenced by __fortio_default_convert(), and fw_writenum().
__fortio_fmt_z()
static char * __fortio_fmt_z (unsigned int c) static
Definition at line 1081 of file fmtconv.c.
References buff_pos, and hextab.
Referenced by __fortio_default_convert().
__fortio_printbigreal()
void __fortio_printbigreal (__BIGREAL_T val)
Generate a formated REAL*8 or REAL*16 string.
Definition at line 77 of file fmtconv.c.
References __io_printf, and val.
Referenced by __fortio_fmt_d(), __fortio_fmt_e(), __fortio_fmt_f(), __fortio_fmt_g(), and __fortio_getnum().
alloc_fpbuf()
static void alloc_fpbuf (int n) static
Definition at line 1176 of file fmtconv.c.
References fpbuf, fpdat, malloc(), and n.
Referenced by conv_e(), conv_en(), conv_es(), and conv_f().
conv_e()
static void conv_e (int d, int e, int sf, bool e_flag, int is_quad) static
Definition at line 830 of file fmtconv.c.
References __fortio_no_minus_zero(), alloc_fpbuf(), conv_int(), cvtp_cp(), cvtp_set(), d, e, exp_letter, field_overflow, fpdat, len, neg(), p, and TRUE.
Referenced by __fortio_fmt_d(), __fortio_fmt_e(), and __fortio_fmt_g().
conv_en()
static void conv_en (int d, int e, bool e_flag) static
Definition at line 906 of file fmtconv.c.
References __fortio_no_minus_zero(), alloc_fpbuf(), conv_int(), cvtp_cp(), cvtp_set(), d, e, exp_letter, FALSE, field_overflow, fpdat, len, nc, neg(), p, and TRUE.
Referenced by __fortio_fmt_e().
conv_es()
static void conv_es (int d, int e, bool e_flag) static
Definition at line 969 of file fmtconv.c.
References __fortio_no_minus_zero(), alloc_fpbuf(), conv_int(), cvtp_cp(), cvtp_set(), d, e, exp_letter, FALSE, field_overflow, fpdat, len, neg(), p, and TRUE.
Referenced by __fortio_fmt_e().
conv_f()
static void conv_f (int w, int d) static
Definition at line 1018 of file fmtconv.c.
References __fortio_no_minus_zero(), __io_printf, alloc_fpbuf(), cvtp_cp(), cvtp_set(), d, DBGBIT, field_overflow, fpdat, i, TRUE, and w.
Referenced by __fortio_fmt_f(), and __fortio_fmt_g().
conv_int()
static char * conv_int (__BIGINT_T val, int * lenp, int * negp) static
Definition at line 307 of file fmtconv.c.
References len, MAX_CONV_INT, MAX_HX, MAX_STR, n, neg(), p, tmp, and val.
Referenced by __fortio_fmt_i(), conv_e(), conv_en(), and conv_es().
conv_int8()
static char * conv_int8 (DBLINT64 val, int * lenp, int * negp) static
Definition at line 389 of file fmtconv.c.
References __fort_i64toax(), __ftn_32in64_, I64_LSH, I64_MSH, len, MAX_CONV_INT8, p, strlen(), tmp, val, and value().
Referenced by __fortio_fmt_i8().
cvtp_cp()
static void cvtp_cp (int n) static
Definition at line 1151 of file fmtconv.c.
References FALSE, fpdat, and n.
Referenced by conv_e(), conv_en(), conv_es(), and conv_f().
cvtp_set()
static void cvtp_set (int n, int ch) static
Definition at line 1169 of file fmtconv.c.
References fpdat, and n.
Referenced by conv_e(), conv_en(), conv_es(), and conv_f().
put_buf()
static void put_buf (int width, const char * valp, int len, int sign_char) static
Definition at line 453 of file fmtconv.c.
References __f90io_conv_buf, __io_printf, bufp, cnt, conv_bufp, conv_bufsize, DBGBIT, FALSE, field_overflow, fpdat, len, malloc(), and void().
Referenced by __fortio_default_convert(), __fortio_fmt_d(), __fortio_fmt_e(), __fortio_fmt_f(), __fortio_fmt_g(), __fortio_fmt_i(), and __fortio_fmt_i8().
strip_blnk()
static char * strip_blnk (char * to, char * from) static
Definition at line 1216 of file fmtconv.c.
References c.
Referenced by __fortio_default_convert().
Variable Documentation
__f90io_conv_buf
char __f90io_conv_buf[96] = {0}
Definition at line 65 of file fmtconv.c.
Referenced by __f90io_ldw(), __fortio_default_convert(), and put_buf().
buf
char* buf
Definition at line 448 of file fmtconv.c.
buff_pos
char* buff_pos static
Definition at line 73 of file fmtconv.c.
Referenced by __fortio_default_convert(), and __fortio_fmt_z().
bufsize
int bufsize
Definition at line 449 of file fmtconv.c.
cmplx_buf
char cmplx_buf[64] static
Definition at line 71 of file fmtconv.c.
Referenced by __fortio_default_convert().
conv_bufp
char* conv_bufp = __f90io_conv_buf static
Definition at line 68 of file fmtconv.c.
Referenced by __fortio_default_convert(), __fortio_fmt_d(), __fortio_fmt_e(), __fortio_fmt_f(), __fortio_fmt_g(), __fortio_fmt_i(), __fortio_fmt_i8(), and put_buf().
conv_bufsize
size_t conv_bufsize = sizeof(__f90io_conv_buf) static
Definition at line 69 of file fmtconv.c.
Referenced by __fortio_default_convert(), and put_buf().
curp
char* curp
Definition at line 447 of file fmtconv.c.
cvtp
char* cvtp
Definition at line 446 of file fmtconv.c.
dbgflag
int dbgflag static
Definition at line 28 of file fmtconv.c.
decimal_char
int decimal_char
Definition at line 440 of file fmtconv.c.
Referenced by __fortio_getnum().
exp
int exp
Definition at line 431 of file fmtconv.c.
Referenced by __exp_scalar_kernel(), __fortio_strtod(), __fss_exp_fma3(), __fss_log_fma3(), __fvs_exp_fma3(), __fvs_exp_fma3_256(), __mth_i_derfc_scaled(), __mth_i_dexp(), __mth_i_erfc_scaled(), __pgm_exp_vec128_slowpath(), __pgm_exp_vec256_slowpath(), __pgm_exp_vec512_slowpath(), __rss_log_fma3(), atoui64(), atoxufp(), checkfltol1(), emdnorm(), exp64(), fold_real64_exp(), pgio_ecvt(), put_double(), put_float(), ufpxten(), ZMPLXFUNC_Z(), and ZMPLXFUNC_Z_Z().
exp_letter
char exp_letter = 'E' static
Definition at line 72 of file fmtconv.c.
Referenced by __fortio_fmt_d(), conv_e(), conv_en(), and conv_es().
field_overflow
int field_overflow static
Definition at line 63 of file fmtconv.c.
Referenced by __fortio_fmt_d(), __fortio_fmt_e(), __fortio_fmt_f(), __fortio_fmt_g(), __fortio_fmt_i(), __fortio_fmt_i8(), conv_e(), conv_en(), conv_es(), conv_f(), and put_buf().
fpbuf
char fpbuf[64] static
Definition at line 429 of file fmtconv.c.
Referenced by alloc_fpbuf().
struct { ... } fpdat
Referenced by __fortio_fmt_d(), __fortio_fmt_e(), __fortio_fmt_f(), __fortio_fmt_g(), alloc_fpbuf(), conv_e(), conv_en(), conv_es(), conv_f(), cvtp_cp(), cvtp_set(), and put_buf().
hextab
char hextab[17] = "0123456789ABCDEF" static
Definition at line 1078 of file fmtconv.c.
Referenced by __fortio_fmt_z().
iszero
bool iszero
Definition at line 441 of file fmtconv.c.
Referenced by handle_parsing_errors().
ndigits
int ndigits
Definition at line 439 of file fmtconv.c.
Referenced by cvt(), ecvt(), and fcvt().
sign
int sign
Definition at line 435 of file fmtconv.c.
Referenced by __attribute__(), __ecvt(), __fcvt(), __fort_atoxi32(), __fort_i64toax(), __fortio_ecvt(), __fortio_fcvt(), __fortio_lldecvt(), __fortio_lldfcvt(), __fsd_acos_fma3(), __fsd_asin_fma3(), __fss_acos_fma3(), __fss_asin_fma3(), __fvd_acos_fma3(), __fvd_acos_fma3_256(), __fvd_asin_fma3(), __fvd_asin_fma3_256(), __fvs_acos_fma3(), __fvs_acos_fma3_256(), __fvs_asin_fma3(), __fvs_asin_fma3_256(), __INT_T(), atoxi(), atoxufp(), const_eval(), cvt(), ecvt(), ENTF90(), ENTF90IO(), etoasc(), fcvt(), ftn_i_dsign(), ftn_i_isign(), ftn_i_sign(), gen_call_vminmax_intrinsic(), gen_call_vminmax_neon_intrinsic(), i32tos(), init_fold_const(), neg64(), pgio_ecvt(), retval_errno_erange_overflow(), retval_errno_erange_underflow(), symbolic_divide(), ufptosci(), and uneg64().
zero
__BIGREAL_T zero
Definition at line 450 of file fmtconv.c.
Referenced by addarth(), canonical_conversion(), conv_forall(), convert_idx_scalar(), create_threadprivate_dtype(), dinit_varref(), do_IL_line(), get_vcon0(), get_vconm0(), lldbg_emit_type(), mk_swtab_ll(), no_comm_class(), ref_pd(), replace_by_zero(), search_idx(), semant3(), and sourced_alloc_and_assign().