flang: fmtgetnum.c File Reference
fmtgetnum.c File Reference
Utility module for extracting numerical values from a string.
#include "global.h"
#include "format.h"
Macros
#define DBGBIT(v) (LOCAL_DEBUG && (dbgflag & v))
Functions
int __fortio_getnum (char *currc, int *type, void *_val, int *len, bool dc_flag)
Extract integer or __BIGREAL_T scalar values from a string.
Variables
static int dbgflag
static char buf [128]
static char * buf_p = buf
static int buf_size = sizeof(buf)
Detailed Description
Utility module for extracting numerical values from a string.
Definition in file fmtgetnum.c.
Macro Definition Documentation
DBGBIT
#define DBGBIT (v) (LOCAL_DEBUG && (dbgflag & v))
Definition at line 26 of file fmtgetnum.c.
Function Documentation
__fortio_getnum()
int __fortio_getnum (char * currc, int * type, void * _val, int * len, bool dc_flag)
Extract integer or __BIGREAL_T scalar values from a string.
Definition at line 40 of file fmtgetnum.c.
References __fort_atoxi32(), __fort_atoxi64(), __fortio_printbigreal(), __io_printf, __io_strtold, buf, buf_p, buf_size, c, cp, currc, d, DBGBIT, decimal_char, FIO_EERR_DATA_CONVERSION, i, ISDIGIT, len, malloc(), NULL, TRUE, type, and val.
Referenced by get_number(), and get_token().
Variable Documentation
buf
char buf[128] static
Definition at line 28 of file fmtgetnum.c.
Referenced by __fortio_getnum().
buf_p
char* buf_p = buf static
Definition at line 29 of file fmtgetnum.c.
Referenced by __fortio_getnum().
buf_size
int buf_size = sizeof(buf) static
Definition at line 30 of file fmtgetnum.c.
Referenced by __fortio_getnum().
dbgflag
int dbgflag static
Definition at line 24 of file fmtgetnum.c.