flang: fmtread.c File Reference
fmtread.c File Reference
Fortran formatted read support.
#include <string.h>
#include "global.h"
#include "feddesc.h"
#include "format.h"
#include "fioMacros.h"
Classes
struct rpstack_struct
union ieee
struct struct_G
Macros
#define RPSTACK_SIZE 20 /* determines max paren nesting level */
#define INIT_BUFF_LEN 2008
#define GBL_SIZE 5
#define IS_INT(t) (t == __INT || t == __INT8)
#define MAXFLEN 400
#define CHAR_ONLY 1
#define CHAR_AND_VLIST 2
Typedefs
typedef struct struct_G G
Functions
static int fr_read (char *, int, int)
static INT fr_get_fmtcode (void)
static INT fr_get_val (G *)
static int fr_readnum (int, char *, int)
static int fr_init (__INT_T *, __INT_T *, __INT_T *, __INT_T *, __INT_T *, __INT8_T *, char *, __CLEN_T)
static int fr_assign (char *, int, __BIGINT_T, DBLINT64, __BIGREAL_T)
static int fr_OZreadnum (int, char *, int, int)
static int fr_Breadnum (char *, int, int)
static __BIGREAL_T fr_getreal (char *, int, int, int *)
static int fr_move_fwd (int)
static int fr_read_record (void)
static int malloc_obuff (G *, size_t)
static int realloc_obuff (G *, size_t)
static void save_gbl ()
static void restore_gbl ()
static void save_samefcb ()
static void allocate_new_gbl ()
static void free_gbl ()
__INT_T (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat, __INT_T *fmt, __INT_T *size, DCHAR(advance) DCLEN64(advance))
__INT_T (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat, __INT_T *fmt, __INT_T *size, DCHAR(advance) DCLEN(advance))
__INT_T (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat, __INT_T *fmt, __INT8_T *size, DCHAR(advance) DCLEN64(advance))
__INT_T (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat, __INT_T *fmt, __INT8_T *size, DCHAR(advance) DCLEN(advance))
__INT_T (__INT_T *istat, DCHAR(blank), DCHAR(decimal), DCHAR(pad), DCHAR(round) DCLEN64(blank) DCLEN64(decimal) DCLEN64(pad) DCLEN64(round))
__INT_T (__INT_T *istat, DCHAR(blank), DCHAR(decimal), DCHAR(pad), DCHAR(round) DCLEN(blank) DCLEN(decimal) DCLEN(pad) DCLEN(round))
__INT_T (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat, __INT_T **fmt, __INT_T *size, DCHAR(advance) DCLEN64(advance))
__INT_T (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat, __INT_T **fmt, __INT_T *size, DCHAR(advance) DCLEN(advance))
__INT_T (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat, __INT_T **fmt, __INT8_T *size, DCHAR(advance) DCLEN64(advance))
__INT_T (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat, __INT_T **fmt, __INT8_T *size, DCHAR(advance) DCLEN(advance))
static int fr_intern_init (char *cunit, __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat, __INT_T *fmt, __CLEN_T cunitlen)
__INT_T (DCHAR(cunit), __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat, __INT_T *fmt DCLEN64(cunit))
__INT_T (DCHAR(cunit), __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat, __INT_T **fmt DCLEN64(cunit))
__INT_T (char **cunit, __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat, __INT_T *fmt, __INT_T *len)
__INT_T (char **cunit, __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat, __INT_T **fmt, __INT_T *len)
int __f90io_fmt_read (int type, long length, int stride, char *item, __CLEN_T item_length)
Low level Fortran formatted read routine.
__INT_T (__INT_T *type, __INT_T *count, __INT_T *stride, DCHAR(item) DCLEN64(item))
__INT_T (__INT_T *type, __INT_T *count, __INT_T *stride, DCHAR(item) DCLEN(item))
__INT_T (__INT_T *type, __INT8_T *count, __INT_T *stride, DCHAR(item) DCLEN64(item))
__INT_T (__INT_T *type, __INT8_T *count, __INT_T *stride, DCHAR(item) DCLEN(item))
static void fr_OZconv_init (int, int)
static void fr_OZbyte (int)
static void fr_Bbyte (int)
static int _f90io_fmtr_end (void)
__INT_T ENTF90IO (FMTR_END, fmtr_end)()
__INT_T ENTCRF90IO (FMTR_END, fmtr_end)()
__INT_T ENTF90IO (DTS_FMTR, dts_fmtr)
Variables
static rpstack_struct rpstack [RPSTACK_SIZE]
static G static_gbl [GBL_SIZE]
static G * gbl = &static_gbl[0]
static G * gbl_head = &static_gbl[0]
static int gbl_avl = 0
static int gbl_size = GBL_SIZE
static int move_fwd_eor
static int OZbase
static unsigned char * OZbuff
static int numbits
static unsigned char * buff_pos
static unsigned char * buff_end
Detailed Description
Fortran formatted read support.
Definition in file fmtread.c.
Macro Definition Documentation
CHAR_AND_VLIST
#define CHAR_AND_VLIST 2
Definition at line 3424 of file fmtread.c.
CHAR_ONLY
#define CHAR_ONLY 1
Definition at line 3423 of file fmtread.c.
GBL_SIZE
#define GBL_SIZE 5
Definition at line 87 of file fmtread.c.
INIT_BUFF_LEN
#define INIT_BUFF_LEN 2008
Definition at line 42 of file fmtread.c.
IS_INT
#define IS_INT (t) (t == __INT || t == __INT8)
MAXFLEN
#define MAXFLEN 400
RPSTACK_SIZE
#define RPSTACK_SIZE 20 /* determines max paren nesting level */
Definition at line 21 of file fmtread.c.
Typedef Documentation
G
typedef struct struct_G G
Definition at line 85 of file fmtread.c.
Function Documentation
__f90io_fmt_read()
int __f90io_fmt_read (int type, long length, int stride, char * item, __CLEN_T item_length)
Low level Fortran formatted read routine.
Parameters
type data type (as defined in pghpft.h)
length # items of type to read. May be <= 0
stride distance in bytes between items
item where to transfer data to
item_length byte length
Definition at line 1250 of file fmtread.c.
References __CPLX16, __CPLX32, __CPLX8, __fortio_errend03(), __REAL16, __REAL4, __REAL8, assert, FIO_TBL::eof, EOF_FLAG, EOR_FLAG, ERR_FLAG, FIO_TBL::error, f, FIO_TYPE_SIZE, fioFcbTbls, fr_read(), free_gbl(), gbl, i, length(), NULL, restore_gbl(), stride, sz, and type.
Referenced by __INT_T().
__INT_T() [1/18]
__INT_T (__INT_T * istat, DCHAR(blank) , DCHAR(decimal) , DCHAR(pad) , DCHAR(round) DCLEN(blank) DCLEN(decimal) DCLEN(pad) DCLEN(round))
Definition at line 572 of file fmtread.c.
References __CLEN_T, CADR, CLEN, struct_G::decimal, ENTF90IO(), struct_G::pad, and round().
__INT_T() [2/18]
__INT_T (__INT_T * istat, DCHAR(blank) , DCHAR(decimal) , DCHAR(pad) , DCHAR(round) DCLEN64(blank) DCLEN64(decimal) DCLEN64(pad) DCLEN64(round))
Definition at line 516 of file fmtread.c.
References __fortio_eq_str(), __fortio_error(), G::blank_zero, CADR, CLEN, struct_G::decimal, G::decimal, DIST_STATUS_BCST, FIO_COMMA, FIO_COMPATIBLE, FIO_DOWN, FIO_ESPEC, FIO_NEAREST, FIO_NO, FIO_NULL, FIO_POINT, FIO_PROCESSOR_DEFINED, FIO_UP, FIO_YES, FIO_ZERO, gbl, GET_DIST_IOPROC, GET_DIST_LCPU, ISPRESENTC, LOCAL_MODE, struct_G::pad, G::pad, G::round, round(), and s.
__INT_T() [3/18]
__INT_T (__INT_T * type, __INT8_T * count, __INT_T * stride, DCHAR(item) DCLEN(item))
Definition at line 1458 of file fmtread.c.
References __CLEN_T, CADR, CLEN, count, ENTF90IO(), stride, and type.
__INT_T() [4/18]
__INT_T (__INT_T * type, __INT8_T * count, __INT_T * stride, DCHAR(item) DCLEN64(item))
Definition at line 1424 of file fmtread.c.
References __f90io_fmt_read(), __fort_abort(), __STR, CADR, CLEN, cnt, count, DIST_RBCSTL, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, GET_DIST_SIZE_OF, len, LOCAL_MODE, s, str, stride, and type.
__INT_T() [5/18]
__INT_T (__INT_T * type, __INT_T * count, __INT_T * stride, DCHAR(item) DCLEN(item))
Definition at line 1365 of file fmtread.c.
References __CLEN_T, CADR, CLEN, count, ENTF90IO(), stride, and type.
__INT_T() [6/18]
__INT_T (__INT_T * type, __INT_T * count, __INT_T * stride, DCHAR(item) DCLEN64(item))
Definition at line 1332 of file fmtread.c.
References __f90io_fmt_read(), __fort_abort(), __STR, CADR, CLEN, cnt, count, DIST_RBCSTL, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, GET_DIST_SIZE_OF, len, LOCAL_MODE, s, str, stride, and type.
__INT_T() [7/18]
__INT_T (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat, __INT_T ** fmt, __INT8_T * size, DCHAR(advance) DCLEN(advance))
Definition at line 798 of file fmtread.c.
References __CLEN_T, advance(), bitv, CADR, CLEN, ENTF90IO(), and size.
__INT_T() [8/18]
__INT_T (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat, __INT_T ** fmt, __INT8_T * size, DCHAR(advance) DCLEN64(advance))
Definition at line 761 of file fmtread.c.
References __CLEN_T, __fort_status_init(), __fortio_errend03(), advance(), bitv, CADR, CLEN, DIST_STATUS_BCST, fr_init(), free_gbl(), GET_DIST_IOPROC, GET_DIST_LCPU, ISPRESENTC, LOCAL_MODE, n, NULL, p, restore_gbl(), s, and size.
__INT_T() [9/18]
__INT_T (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat, __INT_T ** fmt, __INT_T * size, DCHAR(advance) DCLEN(advance))
Definition at line 743 of file fmtread.c.
References __CLEN_T, advance(), bitv, CADR, CLEN, ENTF90IO(), and size.
__INT_T() [10/18]
__INT_T (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat, __INT_T ** fmt, __INT_T * size, DCHAR(advance) DCLEN64(advance))
Definition at line 699 of file fmtread.c.
References __CLEN_T, __fort_status_init(), __fortio_errend03(), __INT_T(), advance(), bitv, CADR, CLEN, DIST_STATUS_BCST, fr_init(), free_gbl(), GET_DIST_IOPROC, GET_DIST_LCPU, ISPRESENT, ISPRESENTC, LOCAL_MODE, n, NULL, p, restore_gbl(), s, and size.
__INT_T() [11/18]
__INT_T (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat, __INT_T * fmt, __INT8_T * size, DCHAR(advance) DCLEN(advance))
Definition at line 497 of file fmtread.c.
References __CLEN_T, advance(), bitv, CADR, CLEN, ENTF90IO(), and size.
__INT_T() [12/18]
__INT_T (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat, __INT_T * fmt, __INT8_T * size, DCHAR(advance) DCLEN64(advance))
Definition at line 459 of file fmtread.c.
References __CLEN_T, __fort_status_init(), __fortio_errend03(), advance(), bitv, CADR, CLEN, DIST_STATUS_BCST, fr_init(), free_gbl(), GET_DIST_IOPROC, GET_DIST_LCPU, ISPRESENTC, LOCAL_MODE, n, NULL, p, restore_gbl(), s, and size.
__INT_T() [13/18]
__INT_T (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat, __INT_T * fmt, __INT_T * size, DCHAR(advance) DCLEN(advance))
Definition at line 440 of file fmtread.c.
References __CLEN_T, advance(), bitv, CADR, CLEN, ENTF90IO(), and size.
__INT_T() [14/18]
__INT_T (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat, __INT_T * fmt, __INT_T * size, DCHAR(advance) DCLEN64(advance))
Definition at line 395 of file fmtread.c.
References __CLEN_T, __fort_status_init(), __fortio_errend03(), advance(), bitv, CADR, CLEN, DIST_STATUS_BCST, fr_init(), free_gbl(), GET_DIST_IOPROC, GET_DIST_LCPU, ISPRESENT, ISPRESENTC, LOCAL_MODE, n, NULL, p, restore_gbl(), s, and size.
Referenced by __INT_T().
__INT_T() [15/18]
__INT_T (char ** cunit, __INT_T * rec_num, __INT_T * bitv, __INT_T * iostat, __INT_T ** fmt, __INT_T * len)
Definition at line 1201 of file fmtread.c.
References __fort_status_init(), __fortio_errend03(), bitv, DIST_STATUS_BCST, fr_intern_init(), free_gbl(), GET_DIST_IOPROC, GET_DIST_LCPU, len, LOCAL_MODE, restore_gbl(), and s.
__INT_T() [16/18]
__INT_T (char ** cunit, __INT_T * rec_num, __INT_T * bitv, __INT_T * iostat, __INT_T * fmt, __INT_T * len)
Definition at line 1153 of file fmtread.c.
References __fort_status_init(), __fortio_errend03(), bitv, DIST_STATUS_BCST, fr_intern_init(), free_gbl(), GET_DIST_IOPROC, GET_DIST_LCPU, len, LOCAL_MODE, restore_gbl(), and s.
__INT_T() [17/18]
__INT_T (DCHAR(cunit) , __INT_T * rec_num, __INT_T * bitv, __INT_T * iostat, __INT_T **fmt DCLEN64cunit)
Definition at line 1077 of file fmtread.c.
References __fort_status_init(), __fortio_errend03(), bitv, CADR, CLEN, DIST_STATUS_BCST, fr_intern_init(), free_gbl(), GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, restore_gbl(), and s.
__INT_T() [18/18]
__INT_T (DCHAR(cunit) , __INT_T * rec_num, __INT_T * bitv, __INT_T * iostat, __INT_T *fmt DCLEN64cunit)
Definition at line 1000 of file fmtread.c.
References __fort_status_init(), __fortio_errend03(), bitv, CADR, CLEN, DIST_STATUS_BCST, fr_intern_init(), free_gbl(), GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, restore_gbl(), and s.
_f90io_fmtr_end()
static int _f90io_fmtr_end (void) static
Definition at line 3349 of file fmtread.c.
References __fortio_error(), __io_errno(), __io_fseek, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FIO_TBL::error, fioFcbTbls, fr_read(), gbl, i, G::internal_file, NULL, G::rec_len, and TRUE.
Referenced by ENTCRF90IO(), and ENTF90IO().
allocate_new_gbl()
static void allocate_new_gbl () static
Definition at line 172 of file fmtread.c.
References struct_G::eor_seen, gbl, gbl_avl, gbl_head, GBL_SIZE, gbl_size, malloc(), NULL, struct_G::obuff, struct_G::obuff_len, and struct_G::rec_buff.
Referenced by fr_init(), and fr_intern_init().
ENTCRF90IO()
__INT_T ENTCRF90IO (FMTR_END , fmtr_end)
Definition at line 3409 of file fmtread.c.
References __fortio_errend03(), __fortio_fmtend(), _f90io_fmtr_end(), free_gbl(), restore_gbl(), s, and save_samefcb().
ENTF90IO() [1/2]
__INT_T ENTF90IO (DTS_FMTR , dts_fmtr)
Definition at line 3428 of file fmtread.c.
References __fortio_error(), CHAR_AND_VLIST, CHAR_ONLY, FIO_TBL::error, FED_DT, FED_END, FED_T, FED_TL, FED_TR, FED_X, FIO_ETAB_VALUE_OUT_OF_RANGE, fioFcbTbls, first, fr_get_fmtcode(), fr_get_val(), fr_read_record(), gbl, get_vlist_desc(), get_vlist_desc_i8(), i, INT, k, len, NULL, and TRUE.
ENTF90IO() [2/2]
__INT_T ENTF90IO (FMTR_END , fmtr_end)
Definition at line 3393 of file fmtread.c.
References __fortio_errend03(), __fortio_fmtend(), _f90io_fmtr_end(), DIST_STATUS_BCST, free_gbl(), GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, restore_gbl(), s, and save_samefcb().
Referenced by __INT_T().
fr_assign()
static int fr_assign (char * item, int type, __BIGINT_T ival, DBLINT64 i8val, __BIGREAL_T dval) static
Definition at line 2313 of file fmtread.c.
References __ftn_32in64_, __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL16, __REAL4, __REAL8, __WORD4, FIO_EERR_DATA_CONVERSION, FIO_EMISMATCH, I64_MSH, and type.
Referenced by fr_read(), and fr_readnum().
fr_Bbyte()
static void fr_Bbyte (int c) static
Definition at line 2855 of file fmtread.c.
References buff_pos, c, and numbits.
Referenced by fr_Breadnum().
fr_Breadnum()
static int fr_Breadnum (char * item, int type, int item_length) static
Definition at line 2671 of file fmtread.c.
References __fortio_error(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL16, __REAL4, __REAL8, __STR, __WORD4, assert, G::blank_zero, buff_end, buff_pos, c, comma_seen, FALSE, FIO_EERR_DATA_CONVERSION, FIO_EMISMATCH, FIO_TYPE_SIZE, FIO_ZERO, fr_Bbyte(), fr_get_val(), fr_move_fwd(), fr_OZconv_init(), gbl, k, OZbase, p, G::rec_len, sz, type, void(), and w.
Referenced by fr_read().
fr_get_fmtcode()
static INT fr_get_fmtcode (void) static
Definition at line 1815 of file fmtread.c.
References __fortio_error(), assert, rpstack_struct::code, rpstack_struct::count, FALSE, FED_ERROR, FED_LPAREN, FIO_EPNEST, FIO_EREPCNT, rpstack_struct::fmtpos, fr_get_val(), gbl, k, rpstack, RPSTACK_SIZE, TRUE, and void().
Referenced by ENTF90IO(), and fr_read().
fr_get_val()
static INT fr_get_val (G * g) static
Definition at line 1869 of file fmtread.c.
References fp, INT, and val.
Referenced by ENTF90IO(), fr_Breadnum(), fr_get_fmtcode(), fr_OZreadnum(), fr_read(), and fr_readnum().
fr_getreal()
static __BIGREAL_T fr_getreal (char * p, int w, int d, int * errflag) static
Definition at line 2871 of file fmtread.c.
References __io_strtold, G::blank_zero, buff, c, ieee::d, d, G::decimal, ieee::e, FALSE, FIO_COMMA, FIO_EERR_DATA_CONVERSION, FIO_ZERO, gbl, ieee::hm, ieee::i, ieee::lm, MAXFLEN, p, ieee::s, TRUE, ieee::v, and w.
Referenced by fr_readnum().
fr_init()
static int fr_init (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat, __INT_T * fmt, __INT8_T * size, char * advance, __CLEN_T advancelen) static
Definition at line 235 of file fmtread.c.
References __fortio_eq_str(), __fortio_errinit03(), __fortio_error(), __fortio_rwinit(), fcb::acc, advance(), allocate_new_gbl(), bitv, fcb::blank, G::blank_zero, fcb::decimal, G::decimal, FIO_TBL::enctab, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, f, FALSE, FED_ERROR, FIO_DIRECT, FIO_ECOMPAT, FIO_EEOR, FIO_FORMATTED, fioFcbTbls, fr_read_record(), gbl, gbl_avl, gbl_head, i, INIT_BUFF_LEN, G::internal_file, ISPRESENT, len, malloc_obuff(), NULL, fcb::pad, G::pad, G::rec_len, fcb::reclen, fcb::round, G::round, G::same_fcb_idx, save_gbl(), size, and TRUE.
Referenced by __INT_T().
fr_intern_init()
static int fr_intern_init (char * cunit, __INT_T * rec_num, __INT_T * bitv, __INT_T * iostat, __INT_T * fmt, __CLEN_T cunitlen) static
Definition at line 932 of file fmtread.c.
References __CLEN_T, __fortio_errinit03(), __fortio_error(), allocate_new_gbl(), assert, bitv, G::blank_zero, G::decimal, FIO_TBL::enctab, FALSE, FED_ERROR, FIO_COMPATIBLE, FIO_NULL, FIO_POINT, FIO_YES, fioFcbTbls, gbl, i, INIT_BUFF_LEN, G::internal_file, ISPRESENT, malloc_obuff(), p, G::pad, G::rec_len, G::round, save_gbl(), TRUE, and w.
Referenced by __INT_T().
fr_move_fwd()
static int fr_move_fwd (int len) static
Definition at line 3164 of file fmtread.c.
References __fortio_error(), FIO_DIRECT, FIO_ETOOBIG, gbl, INIT_BUFF_LEN, G::internal_file, len, move_fwd_eor, realloc_obuff(), and G::rec_len.
Referenced by fr_Breadnum(), fr_OZreadnum(), fr_read(), and fr_readnum().
fr_OZbyte()
static void fr_OZbyte (int c) static
Definition at line 2630 of file fmtread.c.
References assert, buff_pos, c, k, numbits, OZbase, and OZbuff.
Referenced by fr_OZreadnum().
fr_OZconv_init()
static void fr_OZconv_init (int w, int sz) static
Definition at line 2601 of file fmtread.c.
References buff_end, buff_pos, len, malloc(), numbits, OZbase, OZbuff, sz, and w.
Referenced by fr_Breadnum(), and fr_OZreadnum().
fr_OZreadnum()
static int fr_OZreadnum (int code, char * item, int type, int item_length) static
Definition at line 2389 of file fmtread.c.
References __fortio_error(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL16, __REAL4, __REAL8, __STR, __WORD4, assert, G::blank_zero, buff_end, buff_pos, c, comma_seen, FALSE, FED_O, FED_Ow_m, FED_Z, FED_Zw_m, FIO_EERR_DATA_CONVERSION, FIO_EMISMATCH, FIO_TYPE_SIZE, FIO_ZERO, fr_get_val(), fr_move_fwd(), fr_OZbyte(), fr_OZconv_init(), gbl, idx, k, OZbase, G::rec_len, sz, type, void(), and w.
Referenced by fr_read().
fr_read()
static int fr_read (char * item, int type, int item_length) static
Definition at line 1511 of file fmtread.c.
References __fortio_error(), __STR, assert, G::blank_zero, rpstack_struct::code, rpstack_struct::count, G::decimal, ERR_FLAG, FALSE, FED_A, FED_Aw, FED_BN, FED_Bw_m, FED_BZ, FED_COLON, FED_D, FED_DC, FED_DOLLAR, FED_DP, FED_DT, FED_Dw_d, FED_E, FED_Ee, FED_END, FED_ENw_d, FED_ERROR, FED_ESw_d, FED_Ew_d, FED_F, FED_Fw_d, FED_G, FED_Gw_d, FED_I, FED_Iw_m, FED_KANJI_STRING, FED_L, FED_LPAREN, FED_Lw, FED_O, FED_Ow_m, FED_P, FED_Q, FED_RC, FED_RD, FED_RN, FED_RP, FED_RPAREN, FED_RU, FED_RZ, FED_S, FED_SLASH, FED_SP, FED_SS, FED_STR, FED_T, FED_TL, FED_TR, FED_X, FED_Z, FED_Zw_m, FIO_COMMA, FIO_COMPATIBLE, FIO_DIRECT, FIO_DOWN, FIO_EEDITDSCR, FIO_EEOR, FIO_EINFINITE_REVERSION, FIO_ESCALEF, FIO_ETAB_VALUE_OUT_OF_RANGE, FIO_NEAREST, FIO_NULL, FIO_POINT, FIO_PROCESSOR_DEFINED, FIO_TYPE_SIZE, FIO_UP, FIO_YES, FIO_ZERO, rpstack_struct::fmtpos, fr_assign(), fr_Breadnum(), fr_get_fmtcode(), fr_get_val(), fr_move_fwd(), fr_OZreadnum(), fr_read_record(), fr_readnum(), gbl, i, idx, G::internal_file, move_fwd_eor, NULL, struct_G::pad, G::pad, G::rec_len, G::round, rpstack, TRUE, type, void(), and w.
Referenced by __f90io_fmt_read(), and _f90io_fmtr_end().
fr_read_record()
static int fr_read_record (void) static
Definition at line 3200 of file fmtread.c.
References __io_errno(), __io_feof(), __io_fgetc, __io_fread, __io_ungetc, fcb::acc, c, EOR_CRLF, f, FILE, FIO_DIRECT, FIO_EDREAD, FIO_EEOF, FIO_EEOR, fcb::fp, fp, gbl, idx, INIT_BUFF_LEN, G::internal_file, fcb::maxrec, fcb::nextrec, p, fcb::pread, realloc_obuff(), G::rec_len, and TRUE.
Referenced by ENTF90IO(), fr_init(), and fr_read().
fr_readnum()
static int fr_readnum (int code, char * item, int type) static
Definition at line 1888 of file fmtread.c.
References __fort_atoxi64(), __fortio_check_format(), __fortio_error(), __INT, __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL16, __REAL4, __REAL8, __WORD4, G::blank_zero, c, comma_seen, d, G::decimal, e, FALSE, FED_D, FED_Dw_d, FED_E, FED_Ee, FED_ENw_d, FED_ESw_d, FED_Ew_d, FED_F, FED_Fw_d, FED_G, FED_Gw_d, FED_I, FED_Iw_m, FED_L, FED_Lw, FIO_COMMA, FIO_EERR_DATA_CONVERSION, FIO_EMISMATCH, FIO_ZERO, fr_assign(), fr_get_val(), fr_getreal(), fr_move_fwd(), FTN_FALSE, FTN_TRUE, G_REAL16_D, G_REAL16_W, gbl, idx, IS_INT, REAL4_D, REAL4_W, REAL8_D, REAL8_W, G::rec_len, TRUE, type, void(), and w.
Referenced by fr_read().
free_gbl()
static void free_gbl () static
Definition at line 214 of file fmtread.c.
References gbl, gbl_avl, gbl_head, and NULL.
Referenced by __f90io_fmt_read(), __INT_T(), ENTCRF90IO(), and ENTF90IO().
malloc_obuff()
static int malloc_obuff (G * g, size_t len) static
Definition at line 3316 of file fmtread.c.
References __fortio_error(), FIO_ENOMEM, len, malloc(), and NULL.
Referenced by fr_init(), and fr_intern_init().
realloc_obuff()
static int realloc_obuff (G * g, size_t len) static
Definition at line 3334 of file fmtread.c.
References __fortio_error(), assert, FIO_ENOMEM, len, and NULL.
Referenced by fr_move_fwd(), and fr_read_record().
restore_gbl()
static void restore_gbl () static
Definition at line 130 of file fmtread.c.
References rpstack_struct::code, rpstack_struct::count, rpstack_struct::fmtpos, gbl, gbl_avl, i, move_fwd_eor, rpstack, and RPSTACK_SIZE.
Referenced by __f90io_fmt_read(), __INT_T(), ENTCRF90IO(), and ENTF90IO().
save_gbl()
static void save_gbl () static
Definition at line 116 of file fmtread.c.
References rpstack_struct::code, rpstack_struct::count, rpstack_struct::fmtpos, gbl, gbl_avl, i, move_fwd_eor, rpstack, and RPSTACK_SIZE.
Referenced by fr_init(), and fr_intern_init().
save_samefcb()
static void save_samefcb () static
Definition at line 144 of file fmtread.c.
References gbl, gbl_head, G::rec_len, and G::same_fcb_idx.
Referenced by ENTCRF90IO(), and ENTF90IO().
Variable Documentation
buff_end
unsigned char * buff_end static
Definition at line 2382 of file fmtread.c.
Referenced by fr_Breadnum(), fr_OZconv_init(), and fr_OZreadnum().
buff_pos
unsigned char* buff_pos static
Definition at line 2382 of file fmtread.c.
Referenced by fr_Bbyte(), fr_Breadnum(), fr_OZbyte(), fr_OZconv_init(), and fr_OZreadnum().
gbl
G* gbl = &static_gbl[0] static
Definition at line 90 of file fmtread.c.
Referenced by __f90io_fmt_read(), __INT_T(), _f90io_fmtr_end(), allocate_new_gbl(), ENTF90IO(), fr_Breadnum(), fr_get_fmtcode(), fr_getreal(), fr_init(), fr_intern_init(), fr_move_fwd(), fr_OZreadnum(), fr_read(), fr_read_record(), fr_readnum(), free_gbl(), restore_gbl(), save_gbl(), and save_samefcb().
gbl_avl
int gbl_avl = 0 static
Definition at line 92 of file fmtread.c.
Referenced by allocate_new_gbl(), fr_init(), free_gbl(), restore_gbl(), and save_gbl().
gbl_head
G* gbl_head = &static_gbl[0] static
Definition at line 91 of file fmtread.c.
Referenced by allocate_new_gbl(), fr_init(), free_gbl(), and save_samefcb().
gbl_size
int gbl_size = GBL_SIZE static
Definition at line 93 of file fmtread.c.
Referenced by allocate_new_gbl().
move_fwd_eor
int move_fwd_eor static
Definition at line 95 of file fmtread.c.
Referenced by fr_move_fwd(), fr_read(), restore_gbl(), and save_gbl().
numbits
int numbits static
Definition at line 2381 of file fmtread.c.
Referenced by fr_Bbyte(), fr_OZbyte(), fr_OZconv_init(), and ftn_i_kibits().
OZbase
int OZbase static
Definition at line 2379 of file fmtread.c.
Referenced by fr_Breadnum(), fr_OZbyte(), fr_OZconv_init(), and fr_OZreadnum().
OZbuff
unsigned char* OZbuff static
Definition at line 2380 of file fmtread.c.
Referenced by fr_OZbyte(), and fr_OZconv_init().
rpstack
rpstack_struct rpstack[RPSTACK_SIZE] static
Definition at line 29 of file fmtread.c.
Referenced by fr_get_fmtcode(), fr_read(), restore_gbl(), and save_gbl().
static_gbl
G static_gbl[GBL_SIZE] static
Definition at line 89 of file fmtread.c.