flang: fmtwrite.c File Reference
fmtwrite.c File Reference
Fortran formatted write support.
#include "global.h"
#include "feddesc.h"
#include "format.h"
#include "format-double.h"
#include <string.h>
Classes
struct rpstack_struct
struct struct_G
Macros
#define RPSTACK_SIZE 20 /* determines max paren nesting level */
#define INIT_BUFF_LEN 200
#define GBL_SIZE 5
#define IS_INT(t) (t == __BIGINT || t == __INT8)
#define CHAR_ONLY 1
#define CHAR_AND_VLIST 2
Typedefs
typedef struct struct_G G
Functions
static int fw_write (char *, int, int)
static int fw_slashes (G *, int)
static int fw_end_nonadvance (void)
static INT fw_get_fmtcode (void)
static INT fw_get_val (G *)
static int fw_writenum (int, char *, int)
static int fw_OZwritenum (int, char *, int, int)
static int fw_Bwritenum (char *, int, __CLEN_T)
static int fw_write_item (const char *, int)
static int fw_check_size (long)
static int fw_write_record (void)
static void save_gbl ()
static void restore_gbl ()
static void save_samefcb ()
static void allocate_new_gbl ()
static void free_gbl ()
static int fw_init (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat, __INT_T *fmt, char *advance, __CLEN_T advancelen)
__INT_T (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat, __INT_T *fmt, DCHAR(advance) DCLEN64(advance))
__INT_T (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat, __INT_T *fmt, DCHAR(advance) DCLEN(advance))
__INT_T (__INT_T *istat, DCHAR(decimal), DCHAR(sign), DCHAR(round) DCLEN64(decimal) DCLEN64(sign) DCLEN64(round))
__INT_T (__INT_T *istat, DCHAR(decimal), DCHAR(sign), DCHAR(round) DCLEN(decimal) DCLEN(sign) DCLEN(round))
__INT_T (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat, __INT_T **fmt, DCHAR(advance) DCLEN64(advance))
__INT_T (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat, __INT_T **fmt, DCHAR(advance) DCLEN(advance))
static int fw_intern_init (char *cunit, __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat, __INT_T *fmt, __CLEN_T cunitlen)
__INT_T (DCHAR(cunit), __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat, __INT_T *fmt DCLEN64(cunit))
__INT_T (DCHAR(cunit), __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat, __INT_T **fmt DCLEN64(cunit))
__INT_T (char **cunit, __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat, __INT_T *fmt, __INT_T *len)
__INT_T (char **cunit, __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat, __INT_T **fmt, __INT_T *len)
int __f90io_fmt_write (int type, long length, int stride, char *item, __CLEN_T item_length)
Low level Fortran formatted write routine.
__INT_T (__INT_T *type, __INT_T *length, __INT_T *stride, DCHAR(item) DCLEN64(item))
__INT_T (__INT_T *type, __INT_T *length, __INT_T *stride, DCHAR(item) DCLEN(item))
__INT_T (__INT_T *type, __INT8_T *length, __INT_T *stride, DCHAR(item) DCLEN64(item))
__INT_T (__INT_T *type, __INT8_T *length, __INT_T *stride, DCHAR(item) DCLEN(item))
static char * reserve_buffer (int width)
static bool call_format_double (int *result, int width, int format_char, int fraction_digits, int exponent_digits, int ESN_mode, int scale_factor, bool explicit_plus, bool comma_radix, bool elide_leading_spaces, bool elide_trailing_spaces, int rounding_mode, double x)
static __CLEN_T fw_OZconv_init (__CLEN_T)
static void fw_OZbyte (unsigned int)
static void fw_Bbyte (unsigned int)
static int _f90io_fmtw_end (void)
__INT_T ENTF90IO (FMTW_END, fmtw_end)()
__INT_T ENTCRF90IO (FMTW_END, fmtw_end)()
__INT_T ENTF90IO (SC_FMT_WRITE, sc_fmt_write)
__INT_T ENTF90IO (SC_I_FMT_WRITE, sc_i_fmt_write)
__INT_T ENTF90IO (SC_L_FMT_WRITE, sc_l_fmt_write)
__INT_T ENTF90IO (SC_F_FMT_WRITE, sc_f_fmt_write)
__INT_T ENTF90IO (SC_D_FMT_WRITE, sc_d_fmt_write)
__INT_T ENTF90IO (SC_CF_FMT_WRITE, sc_cf_fmt_write)
__INT_T ENTF90IO (SC_CD_FMT_WRITE, sc_cd_fmt_write)
__INT_T ENTF90IO (DTS_FMTW, dts_fmtw)
void ENTF90IO (DTS_STAT, dts_stat)
Variables
static rpstack_struct rpstack [RPSTACK_SIZE]
static G static_gbl [GBL_SIZE]
static G * gbl = &static_gbl[0]
static G * gbl_head = &static_gbl[0]
static int gbl_avl = 0
static int gbl_size = GBL_SIZE
static int OZbase
static char hextab [17] = "0123456789ABCDEF"
static char * OZbuff
static int bits_left
static int bits
static char * buff_pos
Detailed Description
Fortran formatted write support.
Definition in file fmtwrite.c.
Macro Definition Documentation
CHAR_AND_VLIST
#define CHAR_AND_VLIST 2
Definition at line 3054 of file fmtwrite.c.
CHAR_ONLY
#define CHAR_ONLY 1
Definition at line 3053 of file fmtwrite.c.
GBL_SIZE
#define GBL_SIZE 5
Definition at line 71 of file fmtwrite.c.
INIT_BUFF_LEN
#define INIT_BUFF_LEN 200
Definition at line 31 of file fmtwrite.c.
IS_INT
#define IS_INT (t) (t == __BIGINT || t == __INT8)
RPSTACK_SIZE
#define RPSTACK_SIZE 20 /* determines max paren nesting level */
Definition at line 21 of file fmtwrite.c.
Typedef Documentation
G
typedef struct struct_G G
Definition at line 72 of file fmtwrite.c.
Function Documentation
__f90io_fmt_write()
int __f90io_fmt_write (int type, long length, int stride, char * item, __CLEN_T item_length)
Low level Fortran formatted write routine.
Parameters
type data type (as defined in pghpft.h)
length # items of type to read. May be <= 0
stride distance in bytes between items
*item where to transfer data from
item_length byte length
Definition at line 974 of file fmtwrite.c.
References __CPLX16, __CPLX32, __CPLX8, __REAL16, __REAL4, __REAL8, assert, FIO_TBL::eof, ERR_FLAG, FIO_TBL::error, FIO_TYPE_SIZE, fioFcbTbls, fw_write(), i, length(), NULL, stride, sz, and type.
Referenced by __INT_T(), and ENTF90IO().
__INT_T() [1/14]
__INT_T (__INT_T * istat, DCHAR(decimal) , DCHAR(sign) , DCHAR(round) DCLEN(decimal) DCLEN(sign) DCLEN(round))
Definition at line 443 of file fmtwrite.c.
References __CLEN_T, CADR, CLEN, struct_G::decimal, ENTF90IO(), round(), and sign.
__INT_T() [2/14]
__INT_T (__INT_T * istat, DCHAR(decimal) , DCHAR(sign) , DCHAR(round) DCLEN64(decimal) DCLEN64(sign) DCLEN64(round))
Definition at line 388 of file fmtwrite.c.
References __fortio_eq_str(), __fortio_errend03(), __fortio_error(), CADR, CLEN, struct_G::decimal, G::decimal, DIST_STATUS_BCST, FIO_COMMA, FIO_COMPATIBLE, FIO_DOWN, FIO_ESPEC, FIO_NEAREST, FIO_PLUS, FIO_POINT, FIO_PROCESSOR_DEFINED, FIO_SUPPRESS, FIO_UP, FIO_ZERO, free_gbl(), gbl, GET_DIST_IOPROC, GET_DIST_LCPU, ISPRESENTC, LOCAL_MODE, restore_gbl(), G::round, round(), s, sign, and G::sign.
__INT_T() [3/14]
__INT_T (__INT_T * type, __INT8_T * length, __INT_T * stride, DCHAR(item) DCLEN(item))
Definition at line 1097 of file fmtwrite.c.
References __CLEN_T, CADR, CLEN, ENTF90IO(), length(), stride, and type.
__INT_T() [4/14]
__INT_T (__INT_T * type, __INT8_T * length, __INT_T * stride, DCHAR(item) DCLEN64(item))
Definition at line 1081 of file fmtwrite.c.
References __f90io_fmt_write(), __STR, CADR, CLEN, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, length(), LOCAL_MODE, s, stride, and type.
__INT_T() [5/14]
__INT_T (__INT_T * type, __INT_T * length, __INT_T * stride, DCHAR(item) DCLEN(item))
Definition at line 1039 of file fmtwrite.c.
References __CLEN_T, CADR, CLEN, ENTF90IO(), length(), stride, and type.
__INT_T() [6/14]
__INT_T (__INT_T * type, __INT_T * length, __INT_T * stride, DCHAR(item) DCLEN64(item))
Definition at line 1023 of file fmtwrite.c.
References __f90io_fmt_write(), __STR, CADR, CLEN, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, length(), LOCAL_MODE, s, stride, and type.
__INT_T() [7/14]
__INT_T (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat, __INT_T ** fmt, DCHAR(advance) DCLEN(advance))
Definition at line 549 of file fmtwrite.c.
References __CLEN_T, advance(), bitv, CADR, CLEN, and ENTF90IO().
__INT_T() [8/14]
__INT_T (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat, __INT_T ** fmt, DCHAR(advance) DCLEN64(advance))
Definition at line 508 of file fmtwrite.c.
References __CLEN_T, __fort_status_init(), __fortio_errend03(), advance(), allocate_new_gbl(), bitv, CADR, CLEN, DIST_STATUS_BCST, FALSE, free_gbl(), fw_init(), gbl, GET_DIST_IOPROC, GET_DIST_LCPU, G::internal_file, ISPRESENTC, LOCAL_MODE, NULL, restore_gbl(), s, and save_gbl().
__INT_T() [9/14]
__INT_T (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat, __INT_T * fmt, DCHAR(advance) DCLEN(advance))
Definition at line 371 of file fmtwrite.c.
References __CLEN_T, advance(), bitv, CADR, CLEN, and ENTF90IO().
__INT_T() [10/14]
__INT_T (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat, __INT_T * fmt, DCHAR(advance) DCLEN64(advance))
Definition at line 329 of file fmtwrite.c.
References __CLEN_T, __fort_status_init(), __fortio_errend03(), advance(), allocate_new_gbl(), bitv, CADR, CLEN, DIST_STATUS_BCST, FALSE, free_gbl(), fw_init(), gbl, GET_DIST_IOPROC, GET_DIST_LCPU, G::internal_file, ISPRESENTC, LOCAL_MODE, NULL, restore_gbl(), s, and save_gbl().
__INT_T() [11/14]
__INT_T (char ** cunit, __INT_T * rec_num, __INT_T * bitv, __INT_T * iostat, __INT_T ** fmt, __INT_T * len)
Definition at line 909 of file fmtwrite.c.
References __fort_status_init(), __fortio_errend03(), allocate_new_gbl(), bitv, DIST_STATUS_BCST, free_gbl(), fw_intern_init(), gbl, GET_DIST_IOPROC, GET_DIST_LCPU, G::internal_file, G::internal_unit, len, LOCAL_MODE, restore_gbl(), s, save_gbl(), and TRUE.
__INT_T() [12/14]
__INT_T (char ** cunit, __INT_T * rec_num, __INT_T * bitv, __INT_T * iostat, __INT_T * fmt, __INT_T * len)
Definition at line 847 of file fmtwrite.c.
References __fort_status_init(), __fortio_errend03(), allocate_new_gbl(), bitv, DIST_STATUS_BCST, free_gbl(), fw_intern_init(), gbl, GET_DIST_IOPROC, GET_DIST_LCPU, G::internal_file, G::internal_unit, len, LOCAL_MODE, restore_gbl(), s, save_gbl(), and TRUE.
__INT_T() [13/14]
__INT_T (DCHAR(cunit) , __INT_T * rec_num, __INT_T * bitv, __INT_T * iostat, __INT_T **fmt DCLEN64cunit)
Definition at line 757 of file fmtwrite.c.
References __fort_status_init(), __fortio_errend03(), allocate_new_gbl(), bitv, CADR, CLEN, DIST_STATUS_BCST, free_gbl(), fw_intern_init(), gbl, GET_DIST_IOPROC, GET_DIST_LCPU, G::internal_file, G::internal_unit, LOCAL_MODE, restore_gbl(), s, save_gbl(), and TRUE.
__INT_T() [14/14]
__INT_T (DCHAR(cunit) , __INT_T * rec_num, __INT_T * bitv, __INT_T * iostat, __INT_T *fmt DCLEN64cunit)
Definition at line 665 of file fmtwrite.c.
References __fort_status_init(), __fortio_errend03(), allocate_new_gbl(), bitv, CADR, CLEN, DIST_STATUS_BCST, free_gbl(), fw_intern_init(), gbl, GET_DIST_IOPROC, GET_DIST_LCPU, G::internal_file, G::internal_unit, LOCAL_MODE, restore_gbl(), s, save_gbl(), and TRUE.
_f90io_fmtw_end()
static int _f90io_fmtw_end (void) static
Definition at line 2891 of file fmtwrite.c.
References __fortio_error(), fcb::acc, assert, FIO_TBL::eof, ERR_FLAG, FIO_TBL::error, f, FIO_DIRECT, fioFcbTbls, fw_end_nonadvance(), fw_write(), fw_write_record(), gbl, G::internal_file, fcb::maxrec, fcb::nextrec, and G::rec_len.
Referenced by ENTCRF90IO(), and ENTF90IO().
allocate_new_gbl()
static void allocate_new_gbl () static
Definition at line 136 of file fmtwrite.c.
References gbl, gbl_avl, gbl_head, GBL_SIZE, gbl_size, malloc(), NULL, struct_G::obuff, struct_G::obuff_len, and struct_G::rec_buff.
Referenced by __INT_T().
call_format_double()
static bool call_format_double (int * result, int width, int format_char, int fraction_digits, int exponent_digits, int ESN_mode, int scale_factor, bool explicit_plus, bool comma_radix, bool elide_leading_spaces, bool elide_trailing_spaces, int rounding_mode, double x) static
Definition at line 1676 of file fmtwrite.c.
References __fortio_error(), __fortio_format_double(), __fortio_new_fp_formatter(), __fortio_no_minus_zero(), ERR_FLAG, formatting_control::ESN_format, formatting_control::exponent_digits, FALSE, FIO_ENOMEM, formatting_control::format_char, fraction_digits(), formatting_control::fraction_digits, fw_write_item(), malloc(), no_minus_zero, formatting_control::no_minus_zero, NULL, formatting_control::plus_sign, formatting_control::point_char, pos, reserve_buffer(), result, formatting_control::rounding, formatting_control::scale_factor, TRUE, and x.
Referenced by fw_writenum().
ENTCRF90IO()
__INT_T ENTCRF90IO (FMTW_END , fmtw_end)
Definition at line 2963 of file fmtwrite.c.
References __fortio_errend03(), __fortio_fmtend(), _f90io_fmtw_end(), free_gbl(), restore_gbl(), s, and save_samefcb().
ENTF90IO() [1/10]
__INT_T ENTF90IO (DTS_FMTW , dts_fmtw)
Definition at line 3057 of file fmtwrite.c.
References __fortio_error(), CHAR_AND_VLIST, CHAR_ONLY, ERR_FLAG, FIO_TBL::error, FED_DT, FED_END, FED_STR, FED_T, FED_TL, FED_TR, FED_X, FIO_ETAB_VALUE_OUT_OF_RANGE, fioFcbTbls, first, fw_get_fmtcode(), fw_get_val(), fw_write_item(), fw_write_record(), gbl, get_vlist_desc(), get_vlist_desc_i8(), i, INT, k, len, NULL, and TRUE.
ENTF90IO() [2/10]
void ENTF90IO (DTS_STAT , dts_stat)
Definition at line 3183 of file fmtwrite.c.
References FIO_TBL::error, fioFcbTbls, and TRUE.
ENTF90IO() [3/10]
__INT_T ENTF90IO (FMTW_END , fmtw_end)
Definition at line 2937 of file fmtwrite.c.
References __CHAR, __CINT, __fortio_errend03(), __fortio_fmtend(), _f90io_fmtw_end(), DIST_RBCSTL, DIST_STATUS_BCST, free_gbl(), gbl, GET_DIST_IOPROC, GET_DIST_LCPU, G::internal_file, G::internal_unit, len, LOCAL_MODE, restore_gbl(), s, and save_samefcb().
Referenced by __INT_T().
ENTF90IO() [4/10]
__INT_T ENTF90IO (SC_CD_FMT_WRITE , sc_cd_fmt_write)
Definition at line 3032 of file fmtwrite.c.
References __f90io_fmt_write(), and __REAL8.
ENTF90IO() [5/10]
__INT_T ENTF90IO (SC_CF_FMT_WRITE , sc_cf_fmt_write)
Definition at line 3022 of file fmtwrite.c.
References __f90io_fmt_write(), and __REAL4.
ENTF90IO() [6/10]
__INT_T ENTF90IO (SC_D_FMT_WRITE , sc_d_fmt_write)
Definition at line 3009 of file fmtwrite.c.
References __f90io_fmt_write(), and type.
ENTF90IO() [7/10]
__INT_T ENTF90IO (SC_F_FMT_WRITE , sc_f_fmt_write)
Definition at line 3003 of file fmtwrite.c.
References __f90io_fmt_write(), and type.
ENTF90IO() [8/10]
__INT_T ENTF90IO (SC_FMT_WRITE , sc_fmt_write)
Definition at line 2982 of file fmtwrite.c.
References __f90io_fmt_write(), and type.
ENTF90IO() [9/10]
__INT_T ENTF90IO (SC_I_FMT_WRITE , sc_i_fmt_write)
Definition at line 2991 of file fmtwrite.c.
References __f90io_fmt_write(), and type.
ENTF90IO() [10/10]
__INT_T ENTF90IO (SC_L_FMT_WRITE , sc_l_fmt_write)
Definition at line 2997 of file fmtwrite.c.
References __f90io_fmt_write(), and type.
free_gbl()
static void free_gbl () static
Definition at line 176 of file fmtwrite.c.
References gbl, gbl_avl, gbl_head, and NULL.
Referenced by __INT_T(), ENTCRF90IO(), and ENTF90IO().
fw_Bbyte()
static void fw_Bbyte (unsigned int c) static
Definition at line 2690 of file fmtwrite.c.
References buff_pos, and i.
Referenced by fw_Bwritenum().
fw_Bwritenum()
static int fw_Bwritenum (char * item, int type, __CLEN_T item_length) static
Definition at line 2583 of file fmtwrite.c.
References __CLEN_T, __STR, assert, ERR_FLAG, FALSE, FIO_TYPE_SIZE, fw_Bbyte(), fw_get_val(), fw_OZconv_init(), fw_write_item(), gbl, k, m, offset, OZbase, OZbuff, p, type, and w.
Referenced by fw_write().
fw_check_size()
static int fw_check_size (long len) static
Definition at line 2785 of file fmtwrite.c.
References __fortio_error(), assert, FIO_DIRECT, FIO_ENOMEM, FIO_ETOOBIG, gbl, INIT_BUFF_LEN, G::internal_file, len, NULL, G::rec_len, and void().
Referenced by fw_write_item(), fw_write_record(), and reserve_buffer().
fw_end_nonadvance()
static int fw_end_nonadvance (void) static
Definition at line 1438 of file fmtwrite.c.
References __fortio_error(), assert, rpstack_struct::code, rpstack_struct::count, G::decimal, ERR_FLAG, FALSE, FED_BN, FED_BZ, FED_COLON, FED_DC, FED_DOLLAR, FED_DP, FED_Ee, FED_END, FED_ERROR, FED_KANJI_STRING, FED_LPAREN, FED_P, FED_RC, FED_RD, FED_RN, FED_RP, FED_RPAREN, FED_RU, FED_RZ, FED_S, FED_SLASH, FED_SP, FED_SS, FED_STR, FED_T, FED_TL, FED_TR, FED_X, FIO_COMMA, FIO_COMPATIBLE, FIO_DOWN, FIO_EEDITDSCR, FIO_ESCALEF, FIO_ETAB_VALUE_OUT_OF_RANGE, FIO_NEAREST, FIO_POINT, FIO_PROCESSOR_DEFINED, FIO_UP, FIO_ZERO, rpstack_struct::fmtpos, fw_get_fmtcode(), fw_get_val(), fw_slashes(), fw_write_item(), fw_write_record(), gbl, i, G::round, rpstack, and TRUE.
Referenced by _f90io_fmtw_end().
fw_get_fmtcode()
static INT fw_get_fmtcode (void) static
Definition at line 1588 of file fmtwrite.c.
References __fortio_error(), assert, rpstack_struct::code, rpstack_struct::count, FALSE, FED_ERROR, FED_LPAREN, FIO_EPNEST, FIO_EREPCNT, rpstack_struct::fmtpos, fw_get_val(), gbl, k, rpstack, RPSTACK_SIZE, TRUE, and void().
Referenced by ENTF90IO(), fw_end_nonadvance(), and fw_write().
fw_get_val()
static INT fw_get_val (G * g) static
Definition at line 1642 of file fmtwrite.c.
References fp, and val.
Referenced by ENTF90IO(), fw_Bwritenum(), fw_end_nonadvance(), fw_get_fmtcode(), fw_OZwritenum(), fw_write(), and fw_writenum().
fw_init()
static int fw_init (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat, __INT_T * fmt, char * advance, __CLEN_T advancelen) static
Definition at line 196 of file fmtwrite.c.
References __fortio_eq_str(), __fortio_errinit03(), __fortio_error(), __fortio_rwinit(), fcb::acc, advance(), bitv, fcb::decimal, G::decimal, FIO_TBL::enctab, ERR_FLAG, f, FALSE, FED_ERROR, FIO_DIRECT, FIO_ECOMPAT, FIO_ENOMEM, FIO_FORMATTED, FIO_PLUS, fioFcbTbls, gbl, gbl_avl, gbl_head, i, if(), INIT_BUFF_LEN, ISPRESENT, len, malloc(), NULL, G::rec_len, fcb::reclen, fcb::round, G::round, G::same_fcb_idx, fcb::sign, G::sign, fcb::skip, fcb::skip_buff, and TRUE.
Referenced by __INT_T().
fw_intern_init()
static int fw_intern_init (char * cunit, __INT_T * rec_num, __INT_T * bitv, __INT_T * iostat, __INT_T * fmt, __CLEN_T cunitlen) static
Definition at line 622 of file fmtwrite.c.
References __fortio_errinit03(), __fortio_error(), assert, bitv, G::decimal, FIO_TBL::enctab, FALSE, FED_ERROR, FIO_COMPATIBLE, FIO_POINT, FIO_PROCESSOR_DEFINED, fioFcbTbls, gbl, ISPRESENT, G::rec_len, G::round, G::sign, and TRUE.
Referenced by __INT_T().
fw_OZbyte()
static void fw_OZbyte (unsigned int c) static
Definition at line 2728 of file fmtwrite.c.
References bits, bits_left, buff_pos, c, hextab, OZbase, and OZbuff.
Referenced by fw_OZwritenum().
fw_OZconv_init()
static __CLEN_T fw_OZconv_init (__CLEN_T len) static
Definition at line 2703 of file fmtwrite.c.
References __CLEN_T, bits, bits_left, buff_pos, len, malloc(), OZbase, and OZbuff.
Referenced by fw_Bwritenum(), and fw_OZwritenum().
fw_OZwritenum()
static int fw_OZwritenum (int code, char * item, int type, int item_length) static
Definition at line 2466 of file fmtwrite.c.
References __STR, assert, ERR_FLAG, FALSE, FED_O, FED_Ow_m, FED_Zw_m, FIO_TYPE_SIZE, fw_get_val(), fw_OZbyte(), fw_OZconv_init(), fw_write_item(), gbl, k, m, offset, OZbase, OZbuff, p, type, and w.
Referenced by fw_write().
fw_slashes()
static int fw_slashes (G * g, int cnt) static
Definition at line 1408 of file fmtwrite.c.
References cnt, FALSE, and fw_write_record().
Referenced by fw_end_nonadvance(), and fw_write().
fw_write()
static int fw_write (char * item, int type, int item_length) static
Definition at line 1135 of file fmtwrite.c.
References __fortio_error(), __STR, assert, rpstack_struct::code, rpstack_struct::count, G::decimal, envar_fortranopt, ERR_FLAG, f, FALSE, FED_A, FED_Aw, FED_BN, FED_Bw_m, FED_BZ, FED_COLON, FED_D, FED_DC, FED_DOLLAR, FED_DP, FED_DT, FED_Dw_d, FED_E, FED_Ee, FED_END, FED_ENw_d, FED_ERROR, FED_ESw_d, FED_Ew_d, FED_F, FED_Fw_d, FED_G, FED_G0, FED_G0_d, FED_Gw_d, FED_I, FED_Iw_m, FED_KANJI_STRING, FED_L, FED_LPAREN, FED_Lw, FED_O, FED_Ow_m, FED_P, FED_Q, FED_RC, FED_RD, FED_RN, FED_RP, FED_RPAREN, FED_RU, FED_RZ, FED_S, FED_SLASH, FED_SP, FED_SS, FED_STR, FED_T, FED_TL, FED_TR, FED_X, FED_Z, FED_Zw_m, FIO_COMMA, FIO_COMPATIBLE, FIO_DOWN, FIO_EEDITDSCR, FIO_EINFINITE_REVERSION, FIO_ESCALEF, FIO_ETAB_VALUE_OUT_OF_RANGE, FIO_NEAREST, FIO_PLUS, FIO_POINT, FIO_PROCESSOR_DEFINED, FIO_TYPE_SIZE, FIO_UP, FIO_ZERO, rpstack_struct::fmtpos, fw_Bwritenum(), fw_get_fmtcode(), fw_get_val(), fw_OZwritenum(), fw_slashes(), fw_write_item(), fw_write_record(), fw_writenum(), gbl, i, NULL, G::round, rpstack, G::sign, fcb::stdunit, TRUE, type, and void().
Referenced by __f90io_fmt_write(), and _f90io_fmtw_end().
fw_write_item()
static int fw_write_item (const char * p, int len) static
Returns
ERR_FLAG or 0
Definition at line 2757 of file fmtwrite.c.
References assert, ERR_FLAG, FALSE, fw_check_size(), gbl, len, NULL, p, and q.
Referenced by call_format_double(), ENTF90IO(), fw_Bwritenum(), fw_end_nonadvance(), fw_OZwritenum(), fw_write(), and fw_writenum().
fw_write_record()
static int fw_write_record (void) static
Definition at line 2817 of file fmtwrite.c.
References __io_binary_mode(), __io_errno(), __io_ferror(), __io_fputc(), fcb::acc, f, FALSE, fflush(), FIO_DIRECT, FIO_ETOOFAR, fcb::fp, fw_check_size(), FWRITE, gbl, G::internal_file, len, malloc(), fcb::nextrec, fcb::nonadvance, G::rec_len, G::skip, TRUE, and void().
Referenced by _f90io_fmtw_end(), ENTF90IO(), fw_end_nonadvance(), fw_slashes(), and fw_write().
fw_writenum()
static int fw_writenum (int code, char * item, int type) static
Definition at line 1854 of file fmtwrite.c.
References __BIGINT, __fortio_check_format(), __fortio_chk_f(), __fortio_error(), __fortio_fmt_d(), __fortio_fmt_e(), __fortio_fmt_f(), __fortio_fmt_g(), __fortio_fmt_i(), __fortio_fmt_i8(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL16, __REAL4, __REAL8, __WORD4, BIGREAL_W, call_format_double(), d, G::decimal, e, FALSE, FED_D, FED_Dw_d, FED_E, FED_Ee, FED_ENw_d, FED_ESw_d, FED_Ew_d, FED_F, FED_Fw_d, FED_G, FED_G0, FED_G0_d, FED_Gw_d, FED_I, FED_Iw_m, FED_L, FED_Lw, FIO_COMMA, FIO_EMISMATCH, FIO_PLUS, FLANG_FALLTHROUGH, fw_get_val(), fw_write_item(), G_REAL16_D, G_REAL16_W, gbl, GET_FIO_CNFG_TRUE_MASK, i, i4, I64_LSH, i8, IS_INT, m, p, r4, r8, REAL16_E, REAL4_D, REAL4_E, REAL4_W, REAL8_D, REAL8_E, REAL8_W, result, G::round, G::sign, TRUE, type, and w.
Referenced by fw_write().
reserve_buffer()
static char * reserve_buffer (int width) static
Definition at line 1658 of file fmtwrite.c.
References FALSE, fw_check_size(), gbl, NULL, and p.
Referenced by call_format_double().
restore_gbl()
static void restore_gbl () static
Definition at line 106 of file fmtwrite.c.
References rpstack_struct::code, rpstack_struct::count, rpstack_struct::fmtpos, gbl, gbl_avl, i, rpstack, and RPSTACK_SIZE.
Referenced by __INT_T(), ENTCRF90IO(), and ENTF90IO().
save_gbl()
static void save_gbl () static
Definition at line 93 of file fmtwrite.c.
References rpstack_struct::code, rpstack_struct::count, rpstack_struct::fmtpos, gbl, gbl_avl, i, rpstack, and RPSTACK_SIZE.
Referenced by __INT_T().
save_samefcb()
static void save_samefcb () static
Definition at line 119 of file fmtwrite.c.
References gbl, gbl_head, G::rec_len, and G::same_fcb_idx.
Referenced by ENTCRF90IO(), and ENTF90IO().
Variable Documentation
bits
int bits static
Definition at line 2458 of file fmtwrite.c.
Referenced by eshdn1(), eshup1(), fw_OZbyte(), fw_OZconv_init(), gen_llvm_expr(), gen_mulh_expr(), int128_unsigned_divide(), intern_const_int(), ll_create_int_type(), ll_create_int_type_with_addrspace(), ll_get_const_int(), make_int_lltype(), make_load(), manrnd(), and ufprnd().
bits_left
int bits_left static
Definition at line 2457 of file fmtwrite.c.
Referenced by fw_OZbyte(), and fw_OZconv_init().
buff_pos
char* buff_pos static
Definition at line 2459 of file fmtwrite.c.
Referenced by fw_Bbyte(), fw_OZbyte(), and fw_OZconv_init().
gbl
G* gbl = &static_gbl[0] static
Definition at line 75 of file fmtwrite.c.
Referenced by __INT_T(), _f90io_fmtw_end(), allocate_new_gbl(), ENTF90IO(), free_gbl(), fw_Bwritenum(), fw_check_size(), fw_end_nonadvance(), fw_get_fmtcode(), fw_init(), fw_intern_init(), fw_OZwritenum(), fw_write(), fw_write_item(), fw_write_record(), fw_writenum(), reserve_buffer(), restore_gbl(), save_gbl(), and save_samefcb().
gbl_avl
int gbl_avl = 0 static
Definition at line 77 of file fmtwrite.c.
Referenced by allocate_new_gbl(), free_gbl(), fw_init(), restore_gbl(), and save_gbl().
gbl_head
G* gbl_head = &static_gbl[0] static
Definition at line 76 of file fmtwrite.c.
Referenced by allocate_new_gbl(), free_gbl(), fw_init(), and save_samefcb().
gbl_size
int gbl_size = GBL_SIZE static
Definition at line 78 of file fmtwrite.c.
Referenced by allocate_new_gbl().
hextab
char hextab[17] = "0123456789ABCDEF" static
Definition at line 2455 of file fmtwrite.c.
Referenced by fw_OZbyte().
OZbase
int OZbase static
Definition at line 2454 of file fmtwrite.c.
Referenced by fw_Bwritenum(), fw_OZbyte(), fw_OZconv_init(), and fw_OZwritenum().
OZbuff
char* OZbuff static
Definition at line 2456 of file fmtwrite.c.
Referenced by fw_Bwritenum(), fw_OZbyte(), fw_OZconv_init(), and fw_OZwritenum().
rpstack
rpstack_struct rpstack[RPSTACK_SIZE] static
Definition at line 29 of file fmtwrite.c.
Referenced by fw_end_nonadvance(), fw_get_fmtcode(), fw_write(), restore_gbl(), and save_gbl().
static_gbl
G static_gbl[GBL_SIZE] static
Definition at line 74 of file fmtwrite.c.