flang: format.h File Reference
format.h File Reference
Macros
#define REAL4_E 2
#define REAL8_E 3
#define REAL16_E 4
#define REAL4_D 7
#define REAL8_D 16
#define REAL16_D 34
#define G_REAL16_D 36
#define REAL4_W 15
#define REAL8_W 25
#define REAL16_W 44
#define G_REAL16_W 45
#define BIGREAL_E REAL8_E
#define BIGREAL_D REAL8_D
#define BIGREAL_W REAL8_W
Functions
void __fortio_printbigreal (__BIGREAL_T)
Generate a formated REAL*8 or REAL*16 string.
char * __fortio_default_convert (char *, int, int, int *, bool, bool, int)
Drive the generation of output strings based on format strings.
char * __fortio_fmt_i (__BIGINT_T, int, int, bool)
Generate a formated INTEGER string.
char * __fortio_fmt_i8 (DBLINT64, int, int, bool)
Generate a formated INTEGER*8 string.
char * __fortio_fmt_d (__BIGREAL_T, int, int, int, int, bool, int)
Generate a string for a 'D' format characer.
char * __fortio_fmt_g (__BIGREAL_T, int, int, int, int, int, bool, bool, bool, int, int)
Generate a string for a 'G' format characer.
char * __fortio_fmt_f (__BIGREAL_T, int, int, int, bool, bool, int)
Generate a string for an 'F' format characer.
char * __fortio_fmt_e (__BIGREAL_T, int, int, int, int, int, bool, bool, bool, int, int)
Generate a string for an 'E' format characer.
__BIGREAL_T __fortio_chk_f (__REAL4_T *)
Convert REAL*4 to REAL4*8.
int __fortio_getnum (char *, int *, void *, int *, bool)
Extract integer or __BIGREAL_T scalar values from a string.
int __f90io_fmt_write (int type, long length, int stride, char *item, __CLEN_T item_length)
Low level Fortran formatted write routine.
int __f90io_fmt_read (int type, long length, int stride, char *item, __CLEN_T item_length)
Low level Fortran formatted read routine.
int __fort_atoxi32 (char *s, INT *i, int n, int base)
char string to 32-bit integer.
void __fort_i64toax (DBLINT64 from, char *to, int count, int sign, int radix)
Converts [un]signed 64 integer into a char string of the selected radix.
int __fort_atoxi64 (char *s, DBLINT64 ir, int n, int radix)
char string to 64-bit integer.
Detailed Description
Macro definitions and function declarations for Fortran formatted IO.
Definition in file format.h.
Macro Definition Documentation
BIGREAL_D
#define BIGREAL_D REAL8_D
Definition at line 37 of file format.h.
BIGREAL_E
#define BIGREAL_E REAL8_E
Definition at line 36 of file format.h.
BIGREAL_W
#define BIGREAL_W REAL8_W
Definition at line 38 of file format.h.
G_REAL16_D
#define G_REAL16_D 36
Definition at line 23 of file format.h.
G_REAL16_W
#define G_REAL16_W 45
Definition at line 33 of file format.h.
REAL16_D
#define REAL16_D 34
Definition at line 21 of file format.h.
REAL16_E
#define REAL16_E 4
Definition at line 15 of file format.h.
REAL16_W
#define REAL16_W 44
Definition at line 31 of file format.h.
REAL4_D
#define REAL4_D 7
Definition at line 19 of file format.h.
REAL4_E
#define REAL4_E 2
Definition at line 13 of file format.h.
REAL4_W
#define REAL4_W 15
Definition at line 29 of file format.h.
REAL8_D
#define REAL8_D 16
Definition at line 20 of file format.h.
REAL8_E
#define REAL8_E 3
Definition at line 14 of file format.h.
REAL8_W
#define REAL8_W 25
Definition at line 30 of file format.h.
Function Documentation
__f90io_fmt_read()
int __f90io_fmt_read (int type, long length, int stride, char * item, __CLEN_T item_length)
Low level Fortran formatted read routine.
Parameters
type data type (as defined in pghpft.h)
length # items of type to read. May be <= 0
stride distance in bytes between items
item where to transfer data to
item_length byte length
Definition at line 1250 of file fmtread.c.
References __CPLX16, __CPLX32, __CPLX8, __fortio_errend03(), __REAL16, __REAL4, __REAL8, assert, FIO_TBL::eof, EOF_FLAG, EOR_FLAG, ERR_FLAG, FIO_TBL::error, f, FIO_TYPE_SIZE, fioFcbTbls, fr_read(), free_gbl(), gbl, i, length(), NULL, restore_gbl(), stride, sz, and type.
Referenced by __INT_T().
__f90io_fmt_write()
int __f90io_fmt_write (int type, long length, int stride, char * item, __CLEN_T item_length)
Low level Fortran formatted write routine.
Parameters
type data type (as defined in pghpft.h)
length # items of type to read. May be <= 0
stride distance in bytes between items
*item where to transfer data from
item_length byte length
Definition at line 974 of file fmtwrite.c.
References __CPLX16, __CPLX32, __CPLX8, __REAL16, __REAL4, __REAL8, assert, FIO_TBL::eof, ERR_FLAG, FIO_TBL::error, FIO_TYPE_SIZE, fioFcbTbls, fw_write(), i, length(), NULL, stride, sz, and type.
Referenced by __INT_T(), and ENTF90IO().
__fort_atoxi32()
int __fort_atoxi32 (char * s, INT * i, int n, int base)
char string to 32-bit integer.
Parameters
Input string containing number to be converted (string is NOT null terminated.)
Pointer to returned integer value
Number of chars from str to convert
Radix of conversion – 2, 8, 10, 16. If base is 16, then the digits\
a-f or A-F are allowed.
Returns
-1 str does not represent a valid number in radix base -2 overflow occurred on conversion 0 No error – *ival contains the converted number.
Definition at line 80 of file utilsi64.c.
References base, end, i, n, s, sign, and value().
Referenced by __fortio_getnum().
__fort_atoxi64()
int __fort_atoxi64 (char * s, DBLINT64 ir, int n, int radix)
char string to 64-bit integer.
Parameters
Input string containing number to be converted (string is NOT null terminated.)
DBLUINT64 output value
Number of chars from str to convert
Radix of conversion – 2, 8, 10, 16. If base is 16, then the digits a-f
Returns
-1 str does not represent a valid number in radix base -2 overflow occurred on conversion 0 No error – *ir contains the converted number.
Definition at line 230 of file utilsi64.c.
References end, n, s, and toi64().
Referenced by __fortio_getnum(), and fr_readnum().
__fort_i64toax()
void __fort_i64toax (DBLINT64 from, char * to, int count, int sign, int radix)
Converts [un]signed 64 integer into a char string of the selected radix.
Parameters
input integer value
output string
number of chars in to
0 = signed conversion; 1 = unsigned
conversion radix: 2, 8, 10, 16
Definition at line 264 of file utilsi64.c.
References ASCII_OFFSET, ASTERISK, count, HEX_OFFSET, I64_LSH, I64_MSH, OVL8::i8, idx, OVL8::lsw, MINUS, OVL8::msw, neg64(), OVL8::ovl8, shf64(), sign, and strlen().
Referenced by conv_int8().
__fortio_chk_f()
__BIGREAL_T __fortio_chk_f (__REAL4_T * f)
Convert REAL*4 to REAL4*8.
Definition at line 1188 of file fmtconv.c.
References u::d, d, f, u::i, i, and uf.
Referenced by fw_writenum().
__fortio_default_convert()
char * __fortio_default_convert (char * item, int type, int item_length, int * lenp, bool dc_flag, bool plus_flag, int round)
Drive the generation of output strings based on format strings.
Definition at line 89 of file fmtconv.c.
References __CPLX16, __CPLX32, __CPLX8, __f90io_conv_buf, __fortio_fmt_g(), __fortio_fmt_i(), __fortio_fmt_i8(), __fortio_fmt_z(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL16, __REAL4, __REAL8, __STR, __WORD16, __WORD4, __WORD8, assert, buff_pos, cmplx_buf, conv_bufp, conv_bufsize, FALSE, G_REAL16_D, G_REAL16_W, GET_FIO_CNFG_TRUE_MASK, I64_LSH, malloc(), p, PP_INT1, PP_INT2, PP_INT4, PP_LOG1, PP_LOG2, PP_LOG4, PP_REAL16, PP_REAL4, PP_REAL8, put_buf(), REAL16_E, REAL4_D, REAL4_E, REAL4_W, REAL8_D, REAL8_E, REAL8_W, round(), strip_blnk(), strlen(), TRUE, type, and void().
Referenced by __f90io_ldw(), and write_nml_val().
__fortio_fmt_d()
char * __fortio_fmt_d (__BIGREAL_T val, int w, int d, int sf, int type, bool plus_flag, int round)
Generate a string for a 'D' format characer.
Definition at line 512 of file fmtconv.c.
References __fortio_printbigreal(), __io_ecvt, __io_printf, conv_bufp, conv_e(), d, DBGBIT, exp_letter, FALSE, field_overflow, fpdat, put_buf(), round(), strlen(), TRUE, val, and w.
Referenced by fw_writenum().
__fortio_fmt_e()
char * __fortio_fmt_e (__BIGREAL_T val, int w, int d, int e, int sf, int type, bool plus_flag, bool e_flag, bool dc_flag, int code, int round)
Generate a string for an 'E' format characer.
Definition at line 704 of file fmtconv.c.
References __fortio_printbigreal(), __io_ecvt, __io_printf, conv_bufp, conv_e(), conv_en(), conv_es(), d, DBGBIT, e, FALSE, FED_ENw_d, FED_ESw_d, field_overflow, fpdat, put_buf(), round(), strlen(), TRUE, val, and w.
Referenced by fw_writenum().
__fortio_fmt_f()
char * __fortio_fmt_f (__BIGREAL_T val, int w, int d, int sf, bool plus_flag, bool dc_flag, int round)
Generate a string for an 'F' format characer.
Definition at line 775 of file fmtconv.c.
References __fortio_printbigreal(), __io_fcvt, __io_printf, conv_bufp, conv_f(), d, DBGBIT, FALSE, field_overflow, fpdat, p, put_buf(), round(), strlen(), TRUE, val, and w.
Referenced by fw_writenum().
__fortio_fmt_g()
char * __fortio_fmt_g (__BIGREAL_T val, int w, int d, int e, int sf, int type, bool plus_flag, bool e_flag, bool dc_flag, int round, int is_quad)
Generate a string for a 'G' format characer.
Definition at line 564 of file fmtconv.c.
References __fortio_printbigreal(), __io_ecvt, __io_fcvt, __io_printf, conv_bufp, conv_e(), conv_f(), d, DBGBIT, e, FALSE, field_overflow, fpdat, m, n, p, put_buf(), round(), strlen(), TRUE, val, and w.
Referenced by __fortio_default_convert(), and fw_writenum().
__fortio_fmt_i()
char * __fortio_fmt_i (__BIGINT_T val, int width, int mn, bool plus_flag)
Generate a formated INTEGER string.
Definition at line 266 of file fmtconv.c.
References conv_bufp, conv_int(), FALSE, field_overflow, i, len, neg(), p, put_buf(), TRUE, and val.
Referenced by __fortio_default_convert(), and fw_writenum().
__fortio_fmt_i8()
char * __fortio_fmt_i8 (DBLINT64 val, int width, int mn, bool plus_flag)
Generate a formated INTEGER*8 string.
Definition at line 346 of file fmtconv.c.
References conv_bufp, conv_int8(), FALSE, field_overflow, i, len, neg(), p, put_buf(), TRUE, and val.
Referenced by __fortio_default_convert(), and fw_writenum().
__fortio_getnum()
int __fortio_getnum (char * currc, int * type, void * _val, int * len, bool dc_flag)
Extract integer or __BIGREAL_T scalar values from a string.
Definition at line 40 of file fmtgetnum.c.
References __fort_atoxi32(), __fort_atoxi64(), __fortio_printbigreal(), __io_printf, __io_strtold, buf, buf_p, buf_size, c, cp, currc, d, DBGBIT, decimal_char, FIO_EERR_DATA_CONVERSION, i, ISDIGIT, len, malloc(), NULL, TRUE, type, and val.
Referenced by get_number(), and get_token().
__fortio_printbigreal()
void __fortio_printbigreal (__BIGREAL_T val)
Generate a formated REAL*8 or REAL*16 string.
Definition at line 77 of file fmtconv.c.
References __io_printf, and val.
Referenced by __fortio_fmt_d(), __fortio_fmt_e(), __fortio_fmt_f(), __fortio_fmt_g(), and __fortio_getnum().