flang: format-double.h File Reference
format-double.h File Reference
#include "float128.h"
Classes
struct formatting_control
Enumerations
enum decimal_rounding {
DECIMAL_ROUND_DEFAULT , DECIMAL_ROUND_IN = 90 , DECIMAL_ROUND_UP = 69 , DECIMAL_ROUND_DOWN = 70 ,
DECIMAL_ROUND_NEAREST = 71 , DECIMAL_ROUND_COMPATIBLE = 72 , DECIMAL_ROUND_PROCESSOR_DEFINED = 73
}
Functions
void __fortio_format_double (char *out, int width, const struct formatting_control *control, double x)
void __fortio_format_quad (char *out, int width, const struct formatting_control *control, float128_t x)
Enumeration Type Documentation
decimal_rounding
enum decimal_rounding
Enumerator
DECIMAL_ROUND_DEFAULT
DECIMAL_ROUND_IN
DECIMAL_ROUND_UP
DECIMAL_ROUND_DOWN
DECIMAL_ROUND_NEAREST
DECIMAL_ROUND_COMPATIBLE
DECIMAL_ROUND_PROCESSOR_DEFINED
Definition at line 18 of file format-double.h.
Function Documentation
__fortio_format_double()
void __fortio_format_double (char * out, int width, const struct formatting_control * control, double x)
Definition at line 1160 of file format-double.c.
References ED_format(), F_format(), F_format_with_scaling(), formatting_control::format_char, G_format(), formatting_control::scale_factor, and x.
Referenced by call_format_double().
__fortio_format_quad()
void __fortio_format_quad (char * out, int width, const struct formatting_control * control, float128_t x)
Definition at line 1224 of file format-quad.c.
References ED_format(), F_format(), F_format_with_scaling(), formatting_control::format_char, G_format(), formatting_control::scale_factor, and x.