flang: format-quad.c File Reference
format-quad.c File Reference
#include "float128.h"
#include "format-double.h"
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
Classes
union raw_fp
Macros
#define EXPONENT_FIELD_BITS 15
#define EXPLICIT_MANTISSA_BITS 112
#define EXPONENT_BIAS 0x3ffe /* i.e., exponent field value of 0.5 */
#define INF_OR_NAN_EXPONENT 0x7fff
#define RJ_EXPONENT_MASK 0x7fff
#define IMPLICIT_NORMALIZED_BIT ((uint128_t)1 << EXPLICIT_MANTISSA_BITS)
#define MANTISSA_MASK (IMPLICIT_NORMALIZED_BIT - 1)
#define SIGN_BIT ((uint128_t)1 << 127)
#define MAX_EXACTLY_REPRESENTABLE_UINT128 (~(uint128_t)0 << EXPONENT_FIELD_BITS)
#define MIN_ENTIRELY_INTEGER IMPLICIT_NORMALIZED_BIT
#define MAX_INT_DECIMAL_DIGITS 4933 /* 1.0e4932 < max finite < 1.0e4933 */
#define MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS (16494 - 4931) /* 11563 */
#define RAW_BITS(x) (((union raw_fp *)&(x))->i)
#define SHIFT_HH32 96 /* shift value to get bit 96 to 127 of frac */
#define SHIFT_HL32 64 /* shift value to get high 64 to 95 frac */
#define SHIFT_LH32 32 /* shift value to get high 32 to 63 of frac */
#define INT_SIZE 32 /* bit size of integer type */
#define SHIFT_32 5 /* 32 is 2^5 */
#define BIT_SIZE 128 /* bit size of quad precision */
#define BYTE_SIZE 4 /* byte size of quad precision */
#define REMAIN_BIT 4 /* remain bit to multiply 10 */
#define WORDS_NUM1 512 /* base-(2**32) digits in little-endian order. value of 2^14/32 */
#define WORDS_NUM2 516 /* base 2**-32 digits in big-endian order. value of 2^14/32 + 4 */
#define INFINITY_STR_LEN 8 /* len of strings "Infinity". */
#define INF_STR_LEN 3 /* len of strings "Inf". */
#define DIGITS_BILLION 9 /* digits numbers of 1000000000 */
#define DIGITS_HUNDRED 2 /* digits numbers of 100 */
#define BASE_NUM 100 /* value of base is 100 */
#define BILLION 1000000000 /* number of billon */
#define MASK_4BIT 0xf /* mask of 4 bits */
#define FACTOR_10 10 /* factor 10 */
#define DIGIT_5 5 /* digit 5 */
#define DIGIT_10 10 /* digit 10 */
#define ESN_DIGITS 3 /* extra digits of ESN */
#define ESN_SCALE 3 /* scaling of ESN */
#define SUBSCRIPT_2 2 /* subscript is 2 */
#define SUBSCRIPT_3 3 /* subscript is 3 */
#define SUBSCRIPT_4 4 /* subscript is 4 */
#define DEFAULT_EXPONENT_DIGITS 2 /* default digits of exponent */
#define EXPONENT_DIGIT3 3 /* digits of exponent is 3 */
#define MAX_EXPONENT_DIGITS 4 /* max digits of exponent */
#define MAX_EXPONENT_VALUE1 9 /* max vallue of exponent while digit is 1 */
#define MAX_EXPONENT_VALUE2 99 /* max vallue of exponent while digit is 2 */
#define MAX_EXPONENT_VALUE3 999 /* max vallue of exponent while digit is 3 */
#define TRAILING_BLANK2 2 /* trailing blank is 2 */
#define TRAILING_BLANK4 4 /* trailing blank is 4 */
Typedefs
typedef __uint128_t uint128_t
Functions
static char * fill (char *out, int ch, int n)
static char * copy (char *out, const char *str, int n)
static void nan_or_infinite (char *out, int width, uint128_t raw, int sign_char)
static char * reversed_uint128 (char *reverse_out, char *limit, uint128_t x)
static void reversed_base_billion (char *reverse_out, char *limit, uint32_t x)
static uint32_t div_by_billion (uint32_t le_x[WORDS_NUM1], int *words)
static uint128_t quad_to_uint128 (float128_t x)
static int format_int_part (char *buff, int width, float128_t x)
static uint32_t mult_fraction (uint32_t be_x[WORDS_NUM2], int words, uint32_t factor)
static uint32_t mult_delimited_fraction (uint32_t be_x[WORDS_NUM2], int *words, int *upper_zero_words, uint32_t factor)
static bool decimal_increment (char *buff, int width)
static void format_fraction (char buff[MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS], int *next_digit_for_rounding, bool *is_inexact, int width, float128_t absx)
static int fraction_digits (char buff[MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS], int *next_digit_for_rounding, bool *is_inexact, int width, float128_t absx)
static enum decimal_rounding discover_native_rounding_mode (void)
static bool should_round_up (enum decimal_rounding mode, int next_decimal_digit, bool is_inexact, int last_decimal_char_or_0, bool value_is_negative)
static void format_expo (char buffer[MAX_EXPONENT_DIGITS], int expo)
static bool all_zeroes (const char *p, int n)
static void F_format (char *output_buffer, int width, const struct formatting_control *control, float128_t x)
static void F_format_with_scaling (char *output_buffer, int width, const struct formatting_control *control, float128_t x)
static void ED_format (char *out_buffer, int width, const struct formatting_control *control, int E_or_D_char, float128_t x)
static void G_format (char *out, int width, const struct formatting_control *control, float128_t x)
void __fortio_format_quad (char *out, int width, const struct formatting_control *control, float128_t x)
Variables
static char base100 [BASE_NUM][2]
Macro Definition Documentation
BASE_NUM
#define BASE_NUM 100 /* value of base is 100 */
Definition at line 82 of file format-quad.c.
BILLION
#define BILLION 1000000000 /* number of billon */
Definition at line 83 of file format-quad.c.
BIT_SIZE
#define BIT_SIZE 128 /* bit size of quad precision */
Definition at line 71 of file format-quad.c.
BYTE_SIZE
#define BYTE_SIZE 4 /* byte size of quad precision */
Definition at line 72 of file format-quad.c.
DEFAULT_EXPONENT_DIGITS
#define DEFAULT_EXPONENT_DIGITS 2 /* default digits of exponent */
Definition at line 93 of file format-quad.c.
DIGIT_10
#define DIGIT_10 10 /* digit 10 */
Definition at line 87 of file format-quad.c.
DIGIT_5
#define DIGIT_5 5 /* digit 5 */
Definition at line 86 of file format-quad.c.
DIGITS_BILLION
#define DIGITS_BILLION 9 /* digits numbers of 1000000000 */
Definition at line 80 of file format-quad.c.
DIGITS_HUNDRED
#define DIGITS_HUNDRED 2 /* digits numbers of 100 */
Definition at line 81 of file format-quad.c.
ESN_DIGITS
#define ESN_DIGITS 3 /* extra digits of ESN */
Definition at line 88 of file format-quad.c.
ESN_SCALE
#define ESN_SCALE 3 /* scaling of ESN */
Definition at line 89 of file format-quad.c.
EXPLICIT_MANTISSA_BITS
#define EXPLICIT_MANTISSA_BITS 112
Definition at line 26 of file format-quad.c.
EXPONENT_BIAS
#define EXPONENT_BIAS 0x3ffe /* i.e., exponent field value of 0.5 */
Definition at line 27 of file format-quad.c.
EXPONENT_DIGIT3
#define EXPONENT_DIGIT3 3 /* digits of exponent is 3 */
Definition at line 94 of file format-quad.c.
EXPONENT_FIELD_BITS
#define EXPONENT_FIELD_BITS 15
Definition at line 25 of file format-quad.c.
FACTOR_10
#define FACTOR_10 10 /* factor 10 */
Definition at line 85 of file format-quad.c.
IMPLICIT_NORMALIZED_BIT
#define IMPLICIT_NORMALIZED_BIT ((uint128_t)1 << EXPLICIT_MANTISSA_BITS)
Definition at line 31 of file format-quad.c.
INF_OR_NAN_EXPONENT
#define INF_OR_NAN_EXPONENT 0x7fff
Definition at line 28 of file format-quad.c.
INF_STR_LEN
#define INF_STR_LEN 3 /* len of strings "Inf". */
Definition at line 79 of file format-quad.c.
INFINITY_STR_LEN
#define INFINITY_STR_LEN 8 /* len of strings "Infinity". */
Definition at line 78 of file format-quad.c.
INT_SIZE
#define INT_SIZE 32 /* bit size of integer type */
Definition at line 69 of file format-quad.c.
MANTISSA_MASK
#define MANTISSA_MASK (IMPLICIT_NORMALIZED_BIT - 1)
Definition at line 33 of file format-quad.c.
MASK_4BIT
#define MASK_4BIT 0xf /* mask of 4 bits */
Definition at line 84 of file format-quad.c.
MAX_EXACTLY_REPRESENTABLE_UINT128
#define MAX_EXACTLY_REPRESENTABLE_UINT128 (~(uint128_t)0 << EXPONENT_FIELD_BITS)
Definition at line 37 of file format-quad.c.
MAX_EXPONENT_DIGITS
#define MAX_EXPONENT_DIGITS 4 /* max digits of exponent */
Definition at line 95 of file format-quad.c.
MAX_EXPONENT_VALUE1
#define MAX_EXPONENT_VALUE1 9 /* max vallue of exponent while digit is 1 */
Definition at line 96 of file format-quad.c.
MAX_EXPONENT_VALUE2
#define MAX_EXPONENT_VALUE2 99 /* max vallue of exponent while digit is 2 */
Definition at line 97 of file format-quad.c.
MAX_EXPONENT_VALUE3
#define MAX_EXPONENT_VALUE3 999 /* max vallue of exponent while digit is 3 */
Definition at line 98 of file format-quad.c.
MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS
#define MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS (16494 - 4931) /* 11563 */
Definition at line 54 of file format-quad.c.
MAX_INT_DECIMAL_DIGITS
#define MAX_INT_DECIMAL_DIGITS 4933 /* 1.0e4932 < max finite < 1.0e4933 */
Definition at line 46 of file format-quad.c.
MIN_ENTIRELY_INTEGER
#define MIN_ENTIRELY_INTEGER IMPLICIT_NORMALIZED_BIT
Definition at line 44 of file format-quad.c.
RAW_BITS
#define RAW_BITS (x) (((union raw_fp *)&(x))->i)
Definition at line 64 of file format-quad.c.
REMAIN_BIT
#define REMAIN_BIT 4 /* remain bit to multiply 10 */
Definition at line 73 of file format-quad.c.
RJ_EXPONENT_MASK
#define RJ_EXPONENT_MASK 0x7fff
Definition at line 30 of file format-quad.c.
SHIFT_32
#define SHIFT_32 5 /* 32 is 2^5 */
Definition at line 70 of file format-quad.c.
SHIFT_HH32
#define SHIFT_HH32 96 /* shift value to get bit 96 to 127 of frac */
Definition at line 66 of file format-quad.c.
SHIFT_HL32
#define SHIFT_HL32 64 /* shift value to get high 64 to 95 frac */
Definition at line 67 of file format-quad.c.
SHIFT_LH32
#define SHIFT_LH32 32 /* shift value to get high 32 to 63 of frac */
Definition at line 68 of file format-quad.c.
SIGN_BIT
#define SIGN_BIT ((uint128_t)1 << 127)
Definition at line 35 of file format-quad.c.
SUBSCRIPT_2
#define SUBSCRIPT_2 2 /* subscript is 2 */
Definition at line 90 of file format-quad.c.
SUBSCRIPT_3
#define SUBSCRIPT_3 3 /* subscript is 3 */
Definition at line 91 of file format-quad.c.
SUBSCRIPT_4
#define SUBSCRIPT_4 4 /* subscript is 4 */
Definition at line 92 of file format-quad.c.
TRAILING_BLANK2
#define TRAILING_BLANK2 2 /* trailing blank is 2 */
Definition at line 99 of file format-quad.c.
TRAILING_BLANK4
#define TRAILING_BLANK4 4 /* trailing blank is 4 */
Definition at line 100 of file format-quad.c.
WORDS_NUM1
#define WORDS_NUM1 512 /* base-(2**32) digits in little-endian order. value of 2^14/32 */
Definition at line 74 of file format-quad.c.
WORDS_NUM2
#define WORDS_NUM2 516 /* base 2**-32 digits in big-endian order. value of 2^14/32 + 4 */
Definition at line 76 of file format-quad.c.
Typedef Documentation
uint128_t
typedef __uint128_t uint128_t
Definition at line 20 of file format-quad.c.
Function Documentation
__fortio_format_quad()
void __fortio_format_quad (char * out, int width, const struct formatting_control * control, float128_t x)
Definition at line 1224 of file format-quad.c.
References ED_format(), F_format(), F_format_with_scaling(), formatting_control::format_char, G_format(), formatting_control::scale_factor, and x.
all_zeroes()
static bool all_zeroes (const char * p, int n) inline static
Definition at line 665 of file format-quad.c.
References n, and p.
Referenced by F_format(), F_format_with_scaling(), and G_format().
copy()
static char * copy (char * out, const char * str, int n) inline static
Definition at line 117 of file format-quad.c.
References n, and str.
Referenced by ED_format(), F_format_with_scaling(), and nan_or_infinite().
decimal_increment()
static bool decimal_increment (char * buff, int width) inline static
Definition at line 368 of file format-quad.c.
References buff.
Referenced by ED_format(), F_format(), F_format_with_scaling(), and G_format().
discover_native_rounding_mode()
static enum decimal_rounding discover_native_rounding_mode (void) inline static
Definition at line 601 of file format-quad.c.
References DECIMAL_ROUND_DOWN, DECIMAL_ROUND_IN, DECIMAL_ROUND_NEAREST, DECIMAL_ROUND_UP, and MAX_EXACTLY_REPRESENTABLE_UINT128.
Referenced by should_round_up().
div_by_billion()
static uint32_t div_by_billion (uint32_t le_x[WORDS_NUM1], int * words) inline static
Definition at line 228 of file format-quad.c.
References BILLION, INT_SIZE, j, and remainder.
Referenced by format_int_part().
ED_format()
static void ED_format (char * out_buffer, int width, const struct formatting_control * control, int E_or_D_char, float128_t x) inline static
Definition at line 873 of file format-quad.c.
References copy(), decimal_increment(), DEFAULT_EXPONENT_DIGITS, ESN_DIGITS, formatting_control::ESN_format, ESN_SCALE, EXPLICIT_MANTISSA_BITS, EXPONENT_DIGIT3, formatting_control::exponent_digits, fill(), format_expo(), format_fraction(), formatting_control::format_G0, format_int_part(), formatting_control::fraction_digits, fraction_digits(), INF_OR_NAN_EXPONENT, INF_STR_LEN, MAX_EXACTLY_REPRESENTABLE_UINT128, MAX_EXPONENT_DIGITS, MAX_EXPONENT_VALUE1, MAX_EXPONENT_VALUE2, MAX_EXPONENT_VALUE3, MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS, MAX_INT_DECIMAL_DIGITS, nan_or_infinite(), formatting_control::no_minus_zero, formatting_control::plus_sign, formatting_control::point_char, quad_to_uint128(), RAW_BITS, RJ_EXPONENT_MASK, formatting_control::rounding, formatting_control::scale_factor, should_round_up(), SIGN_BIT, SUBSCRIPT_2, SUBSCRIPT_3, and x.
Referenced by __fortio_format_quad(), and G_format().
F_format()
static void F_format (char * output_buffer, int width, const struct formatting_control * control, float128_t x) inline static
Definition at line 678 of file format-quad.c.
References all_zeroes(), decimal_increment(), EXPLICIT_MANTISSA_BITS, fill(), formatting_control::format_F0, format_fraction(), format_int_part(), formatting_control::fraction_digits, INF_OR_NAN_EXPONENT, MIN_ENTIRELY_INTEGER, nan_or_infinite(), formatting_control::no_minus_zero, formatting_control::plus_sign, formatting_control::point_char, quad_to_uint128(), RAW_BITS, RJ_EXPONENT_MASK, formatting_control::rounding, should_round_up(), SIGN_BIT, and x.
Referenced by __fortio_format_quad().
F_format_with_scaling()
static void F_format_with_scaling (char * output_buffer, int width, const struct formatting_control * control, float128_t x) static
Definition at line 775 of file format-quad.c.
References all_zeroes(), copy(), decimal_increment(), EXPLICIT_MANTISSA_BITS, fill(), formatting_control::format_F0, format_fraction(), format_int_part(), formatting_control::fraction_digits, INF_OR_NAN_EXPONENT, MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS, MAX_INT_DECIMAL_DIGITS, nan_or_infinite(), formatting_control::no_minus_zero, formatting_control::plus_sign, formatting_control::point_char, RAW_BITS, RJ_EXPONENT_MASK, formatting_control::rounding, formatting_control::scale_factor, should_round_up(), SIGN_BIT, and x.
Referenced by __fortio_format_quad().
fill()
static char * fill (char * out, int ch, int n) inline static
Definition at line 108 of file format-quad.c.
References n.
Referenced by ED_format(), F_format(), F_format_with_scaling(), format_fraction(), fraction_digits(), G_format(), and nan_or_infinite().
format_expo()
static void format_expo (char buffer[MAX_EXPONENT_DIGITS], int expo) inline static
Definition at line 652 of file format-quad.c.
References DIGIT_10, j, and MAX_EXPONENT_DIGITS.
Referenced by ED_format().
format_fraction()
static void format_fraction (char buff[MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS], int * next_digit_for_rounding, bool * is_inexact, int width, float128_t absx) inline static
Definition at line 385 of file format-quad.c.
References BILLION, BIT_SIZE, buff, BYTE_SIZE, DIGITS_BILLION, end, EXPLICIT_MANTISSA_BITS, EXPONENT_BIAS, EXPONENT_FIELD_BITS, FACTOR_10, fill(), IMPLICIT_NORMALIZED_BIT, INT_SIZE, MANTISSA_MASK, MASK_4BIT, MIN_ENTIRELY_INTEGER, mult_delimited_fraction(), quad_to_uint128(), RAW_BITS, REMAIN_BIT, RJ_EXPONENT_MASK, shift, SHIFT_32, SHIFT_HH32, SHIFT_HL32, SHIFT_LH32, SUBSCRIPT_2, SUBSCRIPT_3, and WORDS_NUM2.
Referenced by ED_format(), F_format(), F_format_with_scaling(), and G_format().
format_int_part()
static int format_int_part (char * buff, int width, float128_t x) inline static
Definition at line 262 of file format-quad.c.
References buff, DIGITS_BILLION, DIGITS_HUNDRED, div_by_billion(), EXPLICIT_MANTISSA_BITS, EXPONENT_BIAS, IMPLICIT_NORMALIZED_BIT, INT_SIZE, MANTISSA_MASK, MAX_EXACTLY_REPRESENTABLE_UINT128, NULL, quad_to_uint128(), RAW_BITS, reversed_base_billion(), reversed_uint128(), RJ_EXPONENT_MASK, shift, SHIFT_HH32, SHIFT_HL32, SHIFT_LH32, SUBSCRIPT_2, SUBSCRIPT_3, WORDS_NUM1, and x.
Referenced by ED_format(), F_format(), F_format_with_scaling(), and G_format().
fraction_digits()
static int fraction_digits (char buff[MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS], int * next_digit_for_rounding, bool * is_inexact, int width, float128_t absx) inline static
Definition at line 486 of file format-quad.c.
References BILLION, BIT_SIZE, buff, BYTE_SIZE, DIGITS_BILLION, end, EXPLICIT_MANTISSA_BITS, EXPONENT_BIAS, EXPONENT_FIELD_BITS, FACTOR_10, fill(), IMPLICIT_NORMALIZED_BIT, INT_SIZE, MANTISSA_MASK, MASK_4BIT, MIN_ENTIRELY_INTEGER, mult_delimited_fraction(), quad_to_uint128(), RAW_BITS, REMAIN_BIT, RJ_EXPONENT_MASK, shift, SHIFT_32, SHIFT_HH32, SHIFT_HL32, SHIFT_LH32, SUBSCRIPT_2, SUBSCRIPT_3, and WORDS_NUM2.
Referenced by ED_format().
G_format()
static void G_format (char * out, int width, const struct formatting_control * control, float128_t x) inline static
Definition at line 1126 of file format-quad.c.
References all_zeroes(), decimal_increment(), ED_format(), EXPLICIT_MANTISSA_BITS, formatting_control::exponent_digits, fill(), format_fraction(), format_int_part(), formatting_control::fraction_digits, INF_OR_NAN_EXPONENT, formatting_control::no_minus_zero, formatting_control::plus_sign, formatting_control::point_char, RAW_BITS, RJ_EXPONENT_MASK, formatting_control::rounding, formatting_control::scale_factor, should_round_up(), SIGN_BIT, TRAILING_BLANK2, TRAILING_BLANK4, and x.
Referenced by __fortio_format_quad().
mult_delimited_fraction()
static uint32_t mult_delimited_fraction (uint32_t be_x[WORDS_NUM2], int * words, int * upper_zero_words, uint32_t factor) inline static
Definition at line 348 of file format-quad.c.
References carry(), and mult_fraction().
Referenced by format_fraction(), and fraction_digits().
mult_fraction()
static uint32_t mult_fraction (uint32_t be_x[WORDS_NUM2], int words, uint32_t factor) inline static
Definition at line 335 of file format-quad.c.
References carry(), INT_SIZE, and x.
Referenced by mult_delimited_fraction().
nan_or_infinite()
static void nan_or_infinite (char * out, int width, uint128_t raw, int sign_char) static
Definition at line 127 of file format-quad.c.
References copy(), fill(), INFINITY_STR_LEN, MANTISSA_MASK, NULL, str, and strlen().
Referenced by ED_format(), F_format(), and F_format_with_scaling().
quad_to_uint128()
static uint128_t quad_to_uint128 (float128_t x) inline static
Definition at line 250 of file format-quad.c.
References x.
Referenced by ED_format(), F_format(), format_fraction(), format_int_part(), and fraction_digits().
reversed_base_billion()
static void reversed_base_billion (char * reverse_out, char * limit, uint32_t x) inline static
Definition at line 202 of file format-quad.c.
References base100, BASE_NUM, DIGITS_BILLION, DIGITS_HUNDRED, j, and x.
Referenced by format_int_part().
reversed_uint128()
static char * reversed_uint128 (char * reverse_out, char * limit, uint128_t x) inline static
Definition at line 176 of file format-quad.c.
References base100, BASE_NUM, DIGITS_BILLION, NULL, and x.
Referenced by format_int_part().
should_round_up()
static bool should_round_up (enum decimal_rounding mode, int next_decimal_digit, bool is_inexact, int last_decimal_char_or_0, bool value_is_negative) inline static
Definition at line 620 of file format-quad.c.
References DECIMAL_ROUND_COMPATIBLE, DECIMAL_ROUND_DOWN, DECIMAL_ROUND_IN, DECIMAL_ROUND_NEAREST, DECIMAL_ROUND_PROCESSOR_DEFINED, DECIMAL_ROUND_UP, DIGIT_5, discover_native_rounding_mode(), and mode.
Referenced by ED_format(), F_format(), F_format_with_scaling(), and G_format().
Variable Documentation
base100
char base100[BASE_NUM][2] static
Initial value:
= {
    "00", "01", "02", "03", "04", "05", "06", "07", "08", "09",
    "10", "11", "12", "13", "14", "15", "16", "17", "18", "19",
    "20", "21", "22", "23", "24", "25", "26", "27", "28", "29",
    "30", "31", "32", "33", "34", "35", "36", "37", "38", "39",
    "40", "41", "42", "43", "44", "45", "46", "47", "48", "49",
    "50", "51", "52", "53", "54", "55", "56", "57", "58", "59",
    "60", "61", "62", "63", "64", "65", "66", "67", "68", "69",
    "70", "71", "72", "73", "74", "75", "76", "77", "78", "79",
    "80", "81", "82", "83", "84", "85", "86", "87", "88", "89",
    "90", "91", "92", "93", "94", "95", "96", "97", "98", "99"}
Definition at line 153 of file format-quad.c.
Referenced by reversed_base_billion(), and reversed_uint128().