flang: format-double.c File Reference
format-double.c File Reference
#include "format-double.h"
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
Classes
union raw_fp
Macros
#define EXPONENT_FIELD_BITS 11
#define EXPLICIT_MANTISSA_BITS 52
#define EXPONENT_BIAS 0x3fe /* i.e., exponent field value of 0.5 */
#define INF_OR_NAN_EXPONENT 0x7ff
#define RJ_EXPONENT_MASK 0x7ff
#define IMPLICIT_NORMALIZED_BIT ((uint64_t) 1 << EXPLICIT_MANTISSA_BITS)
#define MANTISSA_MASK (IMPLICIT_NORMALIZED_BIT - 1) /* 0x000fffffffffffff */
#define SIGN_BIT ((uint64_t) 1 << 63) /* 0x8000000000000000 */
#define MAX_EXACTLY_REPRESENTABLE_UINT64 (~(uint64_t) 0 << EXPONENT_FIELD_BITS)
#define MIN_ENTIRELY_INTEGER IMPLICIT_NORMALIZED_BIT
#define MAX_INT_DECIMAL_DIGITS 309 /* 1.0e308 < max finite < 1.0e309 */
#define MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS (1074 - 323) /* 751 */
#define RAW_BITS(x) (((union raw_fp *) &(x))->i)
Functions
static char * fill (char *out, int ch, int n)
static char * copy (char *out, const char *str, int n)
static void nan_or_infinite (char *out, int width, uint64_t raw, int sign_char)
static char * reversed_uint64 (char *reverse_out, char *limit, uint64_t x)
static void reversed_base_billion (char *reverse_out, char *limit, uint32_t x)
static uint32_t div_by_billion (uint32_t le_x[32], int *words)
static uint64_t double_to_uint64 (double x)
static int format_int_part (char *buff, int width, double x)
static uint32_t mult_fraction (uint32_t be_x[34], int words, uint32_t factor)
static uint32_t mult_delimited_fraction (uint32_t be_x[34], int *words, int *upper_zero_words, uint32_t factor)
static bool decimal_increment (char *buff, int width)
static void format_fraction (char buff[MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS], int *next_digit_for_rounding, bool *is_inexact, int width, double absx)
static int fraction_digits (char buff[MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS], int *next_digit_for_rounding, bool *is_inexact, int width, double absx)
static enum decimal_rounding discover_native_rounding_mode (void)
static bool should_round_up (enum decimal_rounding mode, int next_decimal_digit, bool is_inexact, int last_decimal_char_or_0, bool value_is_negative)
static void format_expo (char buffer[3], int expo)
static bool all_zeroes (const char *p, int n)
static void F_format (char *output_buffer, int width, const struct formatting_control *control, double x)
static void F_format_with_scaling (char *output_buffer, int width, const struct formatting_control *control, double x)
static void ED_format (char *out_buffer, int width, const struct formatting_control *control, int E_or_D_char, double x)
static void G_format (char *out, int width, const struct formatting_control *control, double x)
void __fortio_format_double (char *out, int width, const struct formatting_control *control, double x)
Variables
static char base100 [100][2]
Macro Definition Documentation
EXPLICIT_MANTISSA_BITS
#define EXPLICIT_MANTISSA_BITS 52
Definition at line 28 of file format-double.c.
EXPONENT_BIAS
#define EXPONENT_BIAS 0x3fe /* i.e., exponent field value of 0.5 */
Definition at line 29 of file format-double.c.
EXPONENT_FIELD_BITS
#define EXPONENT_FIELD_BITS 11
Definition at line 27 of file format-double.c.
IMPLICIT_NORMALIZED_BIT
#define IMPLICIT_NORMALIZED_BIT ((uint64_t) 1 << EXPLICIT_MANTISSA_BITS)
Definition at line 33 of file format-double.c.
INF_OR_NAN_EXPONENT
#define INF_OR_NAN_EXPONENT 0x7ff
Definition at line 30 of file format-double.c.
MANTISSA_MASK
#define MANTISSA_MASK (IMPLICIT_NORMALIZED_BIT - 1) /* 0x000fffffffffffff */
Definition at line 35 of file format-double.c.
MAX_EXACTLY_REPRESENTABLE_UINT64
#define MAX_EXACTLY_REPRESENTABLE_UINT64 (~(uint64_t) 0 << EXPONENT_FIELD_BITS)
Definition at line 37 of file format-double.c.
MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS
#define MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS (1074 - 323) /* 751 */
Definition at line 54 of file format-double.c.
MAX_INT_DECIMAL_DIGITS
#define MAX_INT_DECIMAL_DIGITS 309 /* 1.0e308 < max finite < 1.0e309 */
Definition at line 46 of file format-double.c.
MIN_ENTIRELY_INTEGER
#define MIN_ENTIRELY_INTEGER IMPLICIT_NORMALIZED_BIT
Definition at line 44 of file format-double.c.
RAW_BITS
#define RAW_BITS (x) (((union raw_fp *) &(x))->i)
Definition at line 64 of file format-double.c.
RJ_EXPONENT_MASK
#define RJ_EXPONENT_MASK 0x7ff
Definition at line 32 of file format-double.c.
SIGN_BIT
#define SIGN_BIT ((uint64_t) 1 << 63) /* 0x8000000000000000 */
Definition at line 36 of file format-double.c.
Function Documentation
__fortio_format_double()
void __fortio_format_double (char * out, int width, const struct formatting_control * control, double x)
Definition at line 1160 of file format-double.c.
References ED_format(), F_format(), F_format_with_scaling(), formatting_control::format_char, G_format(), formatting_control::scale_factor, and x.
Referenced by call_format_double().
all_zeroes()
static bool all_zeroes (const char * p, int n) inline static
Definition at line 614 of file format-double.c.
References n, and p.
Referenced by F_format(), F_format_with_scaling(), and G_format().
copy()
static char * copy (char * out, const char * str, int n) inline static
Definition at line 81 of file format-double.c.
References n, and str.
Referenced by __fort_chn_1toN(), alloc_rbuf(), ED_format(), eliminate_copy(), F_format_with_scaling(), generate_copy(), nan_or_infinite(), and unique_type().
decimal_increment()
static bool decimal_increment (char * buff, int width) inline static
Definition at line 335 of file format-double.c.
References buff.
Referenced by ED_format(), F_format(), F_format_with_scaling(), and G_format().
discover_native_rounding_mode()
static enum decimal_rounding discover_native_rounding_mode (void) inline static
Definition at line 550 of file format-double.c.
References DECIMAL_ROUND_DOWN, DECIMAL_ROUND_IN, DECIMAL_ROUND_NEAREST, DECIMAL_ROUND_UP, and MAX_EXACTLY_REPRESENTABLE_UINT64.
Referenced by should_round_up().
div_by_billion()
static uint32_t div_by_billion (uint32_t le_x[32], int * words) inline static
Definition at line 190 of file format-double.c.
References j, and remainder.
Referenced by format_int_part().
double_to_uint64()
static uint64_t double_to_uint64 (double x) inline static
Definition at line 212 of file format-double.c.
References SIGN_BIT, and x.
Referenced by ED_format(), F_format(), format_fraction(), format_int_part(), and fraction_digits().
ED_format()
static void ED_format (char * out_buffer, int width, const struct formatting_control * control, int E_or_D_char, double x) inline static
Definition at line 826 of file format-double.c.
References copy(), decimal_increment(), double_to_uint64(), formatting_control::ESN_format, EXPLICIT_MANTISSA_BITS, formatting_control::exponent_digits, fill(), format_expo(), format_fraction(), format_int_part(), fraction_digits(), formatting_control::fraction_digits, INF_OR_NAN_EXPONENT, MAX_EXACTLY_REPRESENTABLE_UINT64, MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS, MAX_INT_DECIMAL_DIGITS, nan_or_infinite(), formatting_control::no_minus_zero, formatting_control::plus_sign, formatting_control::point_char, RAW_BITS, RJ_EXPONENT_MASK, formatting_control::rounding, formatting_control::scale_factor, should_round_up(), SIGN_BIT, and x.
Referenced by __fortio_format_double(), and G_format().
F_format()
static void F_format (char * output_buffer, int width, const struct formatting_control * control, double x) inline static
Definition at line 626 of file format-double.c.
References all_zeroes(), decimal_increment(), double_to_uint64(), EXPLICIT_MANTISSA_BITS, fill(), format_fraction(), format_int_part(), formatting_control::fraction_digits, INF_OR_NAN_EXPONENT, MIN_ENTIRELY_INTEGER, nan_or_infinite(), formatting_control::no_minus_zero, formatting_control::plus_sign, formatting_control::point_char, RAW_BITS, RJ_EXPONENT_MASK, formatting_control::rounding, should_round_up(), SIGN_BIT, and x.
Referenced by __fortio_format_double().
F_format_with_scaling()
static void F_format_with_scaling (char * output_buffer, int width, const struct formatting_control * control, double x) static
Definition at line 725 of file format-double.c.
References all_zeroes(), copy(), decimal_increment(), EXPLICIT_MANTISSA_BITS, fill(), format_fraction(), format_int_part(), formatting_control::fraction_digits, INF_OR_NAN_EXPONENT, MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS, MAX_INT_DECIMAL_DIGITS, nan_or_infinite(), formatting_control::no_minus_zero, formatting_control::plus_sign, formatting_control::point_char, RAW_BITS, RJ_EXPONENT_MASK, formatting_control::rounding, formatting_control::scale_factor, should_round_up(), SIGN_BIT, and x.
Referenced by __fortio_format_double().
fill()
static char * fill (char * out, int ch, int n) inline static
Definition at line 72 of file format-double.c.
References n.
Referenced by ED_format(), F_format(), F_format_with_scaling(), format_fraction(), fraction_digits(), G_format(), and nan_or_infinite().
format_expo()
static void format_expo (char buffer[3], int expo) inline static
Definition at line 601 of file format-double.c.
References j.
Referenced by ED_format().
format_fraction()
static void format_fraction (char buff[MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS], int * next_digit_for_rounding, bool * is_inexact, int width, double absx) inline static
Definition at line 352 of file format-double.c.
References buff, double_to_uint64(), end, EXPLICIT_MANTISSA_BITS, EXPONENT_BIAS, EXPONENT_FIELD_BITS, fill(), IMPLICIT_NORMALIZED_BIT, MANTISSA_MASK, MIN_ENTIRELY_INTEGER, mult_delimited_fraction(), RAW_BITS, RJ_EXPONENT_MASK, and shift.
Referenced by ED_format(), F_format(), F_format_with_scaling(), and G_format().
format_int_part()
static int format_int_part (char * buff, int width, double x) inline static
Definition at line 234 of file format-double.c.
References buff, div_by_billion(), double_to_uint64(), EXPLICIT_MANTISSA_BITS, EXPONENT_BIAS, IMPLICIT_NORMALIZED_BIT, MANTISSA_MASK, MAX_EXACTLY_REPRESENTABLE_UINT64, RAW_BITS, reversed_base_billion(), reversed_uint64(), RJ_EXPONENT_MASK, shift, and x.
Referenced by ED_format(), F_format(), F_format_with_scaling(), and G_format().
fraction_digits()
static int fraction_digits (char buff[MAX_FRACTION_SIGNIFICANT_DECIMAL_DIGITS], int * next_digit_for_rounding, bool * is_inexact, int width, double absx) inline static
Definition at line 445 of file format-double.c.
References buff, double_to_uint64(), end, EXPLICIT_MANTISSA_BITS, EXPONENT_BIAS, EXPONENT_FIELD_BITS, fill(), IMPLICIT_NORMALIZED_BIT, MANTISSA_MASK, MIN_ENTIRELY_INTEGER, mult_delimited_fraction(), RAW_BITS, RJ_EXPONENT_MASK, and shift.
Referenced by call_format_double(), and ED_format().
G_format()
static void G_format (char * out, int width, const struct formatting_control * control, double x) inline static
Definition at line 1061 of file format-double.c.
References all_zeroes(), decimal_increment(), ED_format(), EXPLICIT_MANTISSA_BITS, formatting_control::exponent_digits, fill(), format_fraction(), format_int_part(), formatting_control::fraction_digits, INF_OR_NAN_EXPONENT, formatting_control::no_minus_zero, formatting_control::plus_sign, formatting_control::point_char, RAW_BITS, RJ_EXPONENT_MASK, formatting_control::rounding, formatting_control::scale_factor, should_round_up(), SIGN_BIT, and x.
Referenced by __fortio_format_double().
mult_delimited_fraction()
static uint32_t mult_delimited_fraction (uint32_t be_x[34], int * words, int * upper_zero_words, uint32_t factor) inline static
Definition at line 315 of file format-double.c.
References carry(), and mult_fraction().
Referenced by format_fraction(), and fraction_digits().
mult_fraction()
static uint32_t mult_fraction (uint32_t be_x[34], int words, uint32_t factor) inline static
Definition at line 302 of file format-double.c.
References carry(), and x.
Referenced by mult_delimited_fraction().
nan_or_infinite()
static void nan_or_infinite (char * out, int width, uint64_t raw, int sign_char) static
Definition at line 91 of file format-double.c.
References copy(), fill(), MANTISSA_MASK, and str.
Referenced by ED_format(), F_format(), and F_format_with_scaling().
reversed_base_billion()
static void reversed_base_billion (char * reverse_out, char * limit, uint32_t x) inline static
Definition at line 164 of file format-double.c.
References base100, j, and x.
Referenced by format_int_part().
reversed_uint64()
static char * reversed_uint64 (char * reverse_out, char * limit, uint64_t x) inline static
Definition at line 138 of file format-double.c.
References base100, NULL, and x.
Referenced by format_int_part().
should_round_up()
static bool should_round_up (enum decimal_rounding mode, int next_decimal_digit, bool is_inexact, int last_decimal_char_or_0, bool value_is_negative) inline static
Definition at line 569 of file format-double.c.
References DECIMAL_ROUND_COMPATIBLE, DECIMAL_ROUND_DOWN, DECIMAL_ROUND_IN, DECIMAL_ROUND_NEAREST, DECIMAL_ROUND_PROCESSOR_DEFINED, DECIMAL_ROUND_UP, discover_native_rounding_mode(), and mode.
Referenced by ED_format(), F_format(), F_format_with_scaling(), and G_format().
Variable Documentation
base100
char base100[100][2] static
Initial value:
= {
  "00", "01", "02", "03", "04", "05", "06", "07", "08", "09",
  "10", "11", "12", "13", "14", "15", "16", "17", "18", "19",
  "20", "21", "22", "23", "24", "25", "26", "27", "28", "29",
  "30", "31", "32", "33", "34", "35", "36", "37", "38", "39",
  "40", "41", "42", "43", "44", "45", "46", "47", "48", "49",
  "50", "51", "52", "53", "54", "55", "56", "57", "58", "59",
  "60", "61", "62", "63", "64", "65", "66", "67", "68", "69",
  "70", "71", "72", "73", "74", "75", "76", "77", "78", "79",
  "80", "81", "82", "83", "84", "85", "86", "87", "88", "89",
  "90", "91", "92", "93", "94", "95", "96", "97", "98", "99"
}
Definition at line 114 of file format-double.c.
Referenced by reversed_base_billion(), and reversed_uint64().