flang: fpp.c File Reference
fpp.c File Reference
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "machar.h"
#include "version.h"
Classes
struct ifrec
struct PPSYM
struct macstk_type
Macros
#define _CS 1 /* c symbol */
#define _DI 2 /* digit */
#define _BL 4 /* blank */
#define _HD 8 /* hex digit */
#define MASK(c) ((int)c & 0xFF)
#define iscsym(c) (ctable[MASK(c)] & _CS)
#define isblank(c) (ctable[MASK(c)] & _BL)
#define ishex(c) (ctable[MASK(c)] & (_HD | _DI))
#define isident(c) (ctable[MASK(c)] & (_CS | _DI))
#define isdig(c) (ctable[MASK(c)] & _DI)
#define pperror(n, x, sev) error(n, sev, startline, x, CNULL)
#define pperr(n, sev) pperror(n, CNULL, sev)
#define PP_MAXIDLEN 1023
#define LINELEN 2048
#define HASHSIZ 1031
#define TOKMAX 2048
#define IFMAX 20
#define MACMAX 2048
#define FORMALMAX 31
#define ARGST 0xFE
#define MAX_FNAME_LEN 2050
#define MAXINC 20
#define MACSTK_MAX 100
#define NOFUNC 0xFB
#define T_IDENT 'a'
#define T_NOFIDENT 'f'
#define T_REAL 'e'
#define T_INTEGER '0'
#define T_POUND (-2)
#define T_STRING 's'
#define T_COMMENT 'c'
#define D_IF 1
#define D_ELIF 2
#define D_ELSE 3
#define D_ENDIF 4
#define D_IFDEF 5
#define D_IFNDEF 6
#define D_INCLUDE 7
#define D_DEFINE 8
#define D_UNDEF 9
#define D_LINE 10
#define D_PRAGMA 11
#define D_MODULE 12
#define D_LIST 13
#define D_NOLIST 14
#define D_IDENT 15
#define D_ERROR 16
#define D_WARNING 17
#define D_INCLUDE_NEXT 18
#define SKIP_COMMENTS XBIT(124, 0x100000)
#define ifstack(name) _ifs[iftop].name
#define INCLPATH(i) (idir.b + idir.path[i])
#define chkdef(name, val)
#define PGIF "__PGIF90__"
#define PGIF_MINOR "__PGIF90_MINOR__"
#define PGIF_PATCHLEVEL "__PGIF90_PATCHLEVEL__"
#define Number 1
#define Lparen 2
#define Rparen 3
#define Eoln 4
#define Defined 5
#define Mult 6
#define Divide 7
#define Mod 8
#define Plus 9
#define Minus 10
#define Lshift 11
#define Rshift 12
#define Lt 13
#define Gt 14
#define Le 15
#define Ge 16
#define Eq 17
#define Ne 18
#define And 19
#define Xor 20
#define Or 21
#define Andand 22
#define Oror 23
#define Question 24
#define Colon 25
#define Comma 26
#define Minusx 27 /* unary minus operation */
#define Not 28
#define Compl 29 /* ~ */
#define CHECK(t)
#define inchar() (lineptr < lineend ? *lineptr++ : _nextline())
#define DOCOPY
Typedefs
typedef char INCLENTRY[MAX_FNAME_LEN]
Functions
void accpp (void)
static int skipbl (char *tokval, int flag)
static void pr_line (const char *name, int line)
static void doline (void)
static void dopragma (void)
static void doident (void)
static void doerror (void)
static void dowarning (void)
static void clreol (void)
static int dlookup (char *name)
static int inlist (char **list, int nl, char *value)
static void dodef (void)
static void doincl (LOGICAL include_next)
static void domodule (void)
static void doundef (void)
static int subst (PPSYM *sp)
static void ifpush (void)
static INT strstore (const char *name)
static PPSYM * lookup (const char *name, int insflg)
static void delete (char *name)
static void ptok (const char *tok)
static INT doparse (void)
static INT parse (int rbp)
static int gettoken (void)
static INT tobinary (char *st, int b)
static int gtok (char *tokval, int expflag)
static int findtok (char *tokval, int truth)
static int nextok (char *tokval)
static int _nextline (void)
static void pbchar (int c)
static void pbstr (char *s)
static void mac_push (PPSYM *sp, char *lptr)
static void popstack (void)
static void macro_recur_check (PPSYM *sp)
static void stash_paths (const char *dirs)
static void fpp_display_macros ()
void fpp (void)
Variables
static char ctable [256]
static FILE * ifp
static char tokval [TOKMAX]
static int iftop
static struct ifrec _ifs [IFMAX]
static INT hashtab [HASHSIZ]
static PPSYM * hashrec
static INT nhash
static INT next_hash
static char * deftab
static INT ndef
static INT next_def
static int token
static INT tokenval
static int syntaxerr
struct {
char fname [MAX_FNAME_LEN]
char dirname [MAX_FNAME_LEN]
int lineno
int path_idx
FILE * ifp
} inclstack [MAXINC]
static int inclev = 0
static INCLENTRY * incllist
static int incfiles = 0
static int inclsize
static char * lineptr
static char * lineend
static char linebuf [LINELEN+LINELEN]
static int have_comment
static int look_for_comments
static int save_look_for_comments
static int lineloc
static int fileloc
static char cur_fname [MAX_FNAME_LEN]
static int cur_line
static char dirwork [MAX_FNAME_LEN]
static int startline
static int list_flag
static struct macstk_type macstk [MACSTK_MAX]
static int macstk_top = -1
struct {
int * path
int cnt
int sz
char * b
int b_avl
int b_sz
int last
} idir
static char * argbuf
static size_t ARGMAX = 2048
struct {
INT8 led
INT8 nud
short lbp
INT8 rbp
} PT []
Detailed Description
Fortran source preprocessor module (approximates "old-style" cpp).
Definition in file fpp.c.
Macro Definition Documentation
_BL
#define _BL 4 /* blank */
Definition at line 24 of file fpp.c.
_CS
#define _CS 1 /* c symbol */
Definition at line 22 of file fpp.c.
_DI
#define _DI 2 /* digit */
Definition at line 23 of file fpp.c.
_HD
#define _HD 8 /* hex digit */
Definition at line 25 of file fpp.c.
And
#define And 19
Definition at line 1617 of file fpp.c.
Andand
#define Andand 22
Definition at line 1620 of file fpp.c.
ARGST
#define ARGST 0xFE
Definition at line 183 of file fpp.c.
CHECK
#define CHECK (t)
Value:
  {                      \
    if (token != t)      \
      goto syntax_error; \
    token = gettoken();  \
  }
Definition at line 1671 of file fpp.c.
chkdef
#define chkdef (name, val)
Value:
  {                              \
    sp = lookup(name, 1);        \
    if (sp->value != 0)          \
      pperror(220, name, 1);     \
    else                         \
      sp->value = strstore(val); \
  }
Colon
#define Colon 25
Definition at line 1623 of file fpp.c.
Comma
#define Comma 26
Definition at line 1624 of file fpp.c.
Compl
#define Compl 29 /* ~ */
Definition at line 1627 of file fpp.c.
D_DEFINE
#define D_DEFINE 8
Definition at line 207 of file fpp.c.
D_ELIF
#define D_ELIF 2
Definition at line 201 of file fpp.c.
D_ELSE
#define D_ELSE 3
Definition at line 202 of file fpp.c.
D_ENDIF
#define D_ENDIF 4
Definition at line 203 of file fpp.c.
D_ERROR
#define D_ERROR 16
Definition at line 216 of file fpp.c.
D_IDENT
#define D_IDENT 15
Definition at line 215 of file fpp.c.
D_IF
#define D_IF 1
Definition at line 200 of file fpp.c.
D_IFDEF
#define D_IFDEF 5
Definition at line 204 of file fpp.c.
D_IFNDEF
#define D_IFNDEF 6
Definition at line 205 of file fpp.c.
D_INCLUDE
#define D_INCLUDE 7
Definition at line 206 of file fpp.c.
D_INCLUDE_NEXT
#define D_INCLUDE_NEXT 18
Definition at line 218 of file fpp.c.
D_LINE
#define D_LINE 10
Definition at line 209 of file fpp.c.
D_LIST
#define D_LIST 13
Definition at line 213 of file fpp.c.
D_MODULE
#define D_MODULE 12
Definition at line 212 of file fpp.c.
D_NOLIST
#define D_NOLIST 14
Definition at line 214 of file fpp.c.
D_PRAGMA
#define D_PRAGMA 11
Definition at line 210 of file fpp.c.
D_UNDEF
#define D_UNDEF 9
Definition at line 208 of file fpp.c.
D_WARNING
#define D_WARNING 17
Definition at line 217 of file fpp.c.
Defined
#define Defined 5
Definition at line 1603 of file fpp.c.
Divide
#define Divide 7
Definition at line 1605 of file fpp.c.
DOCOPY
#define DOCOPY
Value:
  do {                                       \
    if ((i += p - lineptr) >= TOKMAX) {      \
      pperr(243, 4);                         \
    } else {                                 \
      strncpy(tokval, lineptr, p - lineptr); \
      *(tokval += p - lineptr) = 0;          \
      lineptr = p;                           \
    }                                        \
  } while (0);
Eoln
#define Eoln 4
Definition at line 1602 of file fpp.c.
Eq
#define Eq 17
Definition at line 1615 of file fpp.c.
FORMALMAX
#define FORMALMAX 31
Definition at line 182 of file fpp.c.
Ge
#define Ge 16
Definition at line 1614 of file fpp.c.
Gt
#define Gt 14
Definition at line 1612 of file fpp.c.
HASHSIZ
#define HASHSIZ 1031
Definition at line 178 of file fpp.c.
IFMAX
#define IFMAX 20
Definition at line 180 of file fpp.c.
ifstack
#define ifstack (name) _ifs[iftop].name
Definition at line 286 of file fpp.c.
inchar
#define inchar () (lineptr < lineend ? *lineptr++ : _nextline())
Definition at line 2114 of file fpp.c.
INCLPATH
#define INCLPATH (i) (idir.b + idir.path[i])
Definition at line 320 of file fpp.c.
isblank
#define isblank (c) (ctable[MASK(c)] & _BL)
Definition at line 34 of file fpp.c.
iscsym
#define iscsym (c) (ctable[MASK(c)] & _CS)
Definition at line 33 of file fpp.c.
isdig
#define isdig (c) (ctable[MASK(c)] & _DI)
Definition at line 37 of file fpp.c.
ishex
#define ishex (c) (ctable[MASK(c)] & (_HD | _DI))
Definition at line 35 of file fpp.c.
isident
#define isident (c) (ctable[MASK(c)] & (_CS | _DI))
Definition at line 36 of file fpp.c.
Le
#define Le 15
Definition at line 1613 of file fpp.c.
LINELEN
#define LINELEN 2048
Definition at line 177 of file fpp.c.
Lparen
#define Lparen 2
Definition at line 1600 of file fpp.c.
Lshift
#define Lshift 11
Definition at line 1609 of file fpp.c.
Lt
#define Lt 13
Definition at line 1611 of file fpp.c.
MACMAX
#define MACMAX 2048
Definition at line 181 of file fpp.c.
MACSTK_MAX
#define MACSTK_MAX 100
Definition at line 187 of file fpp.c.
MASK
#define MASK (c) ((int)c & 0xFF)
Definition at line 27 of file fpp.c.
MAX_FNAME_LEN
#define MAX_FNAME_LEN 2050
Definition at line 185 of file fpp.c.
MAXINC
#define MAXINC 20
Definition at line 186 of file fpp.c.
Minus
#define Minus 10
Definition at line 1608 of file fpp.c.
Minusx
#define Minusx 27 /* unary minus operation */
Definition at line 1625 of file fpp.c.
Mod
#define Mod 8
Definition at line 1606 of file fpp.c.
Mult
#define Mult 6
Definition at line 1604 of file fpp.c.
Ne
#define Ne 18
Definition at line 1616 of file fpp.c.
NOFUNC
#define NOFUNC 0xFB
Definition at line 190 of file fpp.c.
Not
#define Not 28
Definition at line 1626 of file fpp.c.
Number
#define Number 1
Definition at line 1599 of file fpp.c.
Or
#define Or 21
Definition at line 1619 of file fpp.c.
Oror
#define Oror 23
Definition at line 1621 of file fpp.c.
PGIF
#define PGIF "__PGIF90__"
PGIF_MINOR
#define PGIF_MINOR "__PGIF90_MINOR__"
PGIF_PATCHLEVEL
#define PGIF_PATCHLEVEL "__PGIF90_PATCHLEVEL__"
Plus
#define Plus 9
Definition at line 1607 of file fpp.c.
PP_MAXIDLEN
#define PP_MAXIDLEN 1023
Definition at line 176 of file fpp.c.
pperr
#define pperr (n, sev) pperror(n, CNULL, sev)
Definition at line 174 of file fpp.c.
pperror
#define pperror (n, x, sev) error(n, sev, startline, x, CNULL)
Definition at line 173 of file fpp.c.
Question
#define Question 24
Definition at line 1622 of file fpp.c.
Rparen
#define Rparen 3
Definition at line 1601 of file fpp.c.
Rshift
#define Rshift 12
Definition at line 1610 of file fpp.c.
SKIP_COMMENTS
#define SKIP_COMMENTS XBIT(124, 0x100000)
Definition at line 281 of file fpp.c.
T_COMMENT
#define T_COMMENT 'c'
Definition at line 198 of file fpp.c.
T_IDENT
#define T_IDENT 'a'
Definition at line 192 of file fpp.c.
T_INTEGER
#define T_INTEGER '0'
Definition at line 195 of file fpp.c.
T_NOFIDENT
#define T_NOFIDENT 'f'
Definition at line 193 of file fpp.c.
T_POUND
#define T_POUND (-2)
Definition at line 196 of file fpp.c.
T_REAL
#define T_REAL 'e'
Definition at line 194 of file fpp.c.
T_STRING
#define T_STRING 's'
Definition at line 197 of file fpp.c.
TOKMAX
#define TOKMAX 2048
Definition at line 179 of file fpp.c.
Xor
#define Xor 20
Definition at line 1618 of file fpp.c.
Typedef Documentation
INCLENTRY
typedef char INCLENTRY[MAX_FNAME_LEN]
Definition at line 270 of file fpp.c.
Function Documentation
_nextline()
static int _nextline (void) static
Definition at line 2476 of file fpp.c.
References c, cur_fname, fclose(), FILE, flg, fname, fp, gbl, have_comment, i, idir, ifp, inclev, inclstack, FLG::include, j, linebuf, lineend, LINELEN, lineno, lineptr, list_flag, list_line(), look_for_comments, p, pperr, pr_line(), start, and startline.
Referenced by nextok().
accpp()
void accpp (void)
Definition at line 715 of file accpp.c.
References _ifs, acc_display_macros(), atoxi(), c, chkdef, clreol(), INCLSTACK::count, count, cp, cpp_comments, ctable, cur_fname, cur_from_stdinc, cur_line, D_DEFINE, D_ELIF, D_ELSE, D_ENDIF, D_ERROR, D_IDENT, D_IF, D_IFDEF, D_IFNDEF, D_INCLUDE, D_INCLUDE_NEXT, D_LINE, D_LIST, D_MODULE, D_NOLIST, D_PRAGMA, D_UNDEF, D_WARNING, FLG::def, deftab, dirnam(), dirname, DIRSINCS, dlookup(), dodef(), doerror(), doident(), doincl(), doline(), domodule(), doparse(), dopragma(), doundef(), dowarning(), errfatal(), FLG::es, F_PREDEF, FALSE, fileloc, findtok(), finish(), PPSYM::flags, flg, fname, FREE, INCLSTACK::from_stdinc, gbl, getenv(), gtok(), hashrec, i, idir, FLG::idir, IFMAX, ifp, INCLSTACK::ifp, ifpush(), ifsize, ifstack, iftop, in_ftn_comment, incfiles, incllist, inclstack, incsize, isdig, iswhite, linebuf, lineend, LINELEN, linelen, lineloc, INCLSTACK::lineno, lineptr, linesize, FLG::list, list_flag, FLG::list_macros, lookup(), macro_recur_check(), MAXINC, NEW, PPSYM::nformals, nifile, NULL, p, FLG::p, INCLSTACK::path_idx, pbchar(), pbstr(), pflag, PP_MAJOR, PP_MINOR, PP_PATCHLEVEL, pperr, pperror, pr_line(), ptok(), skipbl(), FLG::smp, startline, stash_paths(), FLG::stdinc, strlen(), subst(), T_IDENT, T_NSIDENT, T_PPNUM, T_SENTINEL, tmpfile(), TOKMAX, toktyp, tokval, TRUE, FLG::undef, version, void(), and XBIT.
Referenced by fpp().
clreol()
static void clreol (void) static
Definition at line 882 of file fpp.c.
References gtok(), toktyp, and tokval.
Referenced by dodef(), doident(), doincl(), doline(), domodule(), doparse(), dopragma(), doundef(), and fpp().
delete()
static void delete (char * name) static
Definition at line 1525 of file fpp.c.
References cp, deftab, hashrec, HASHSIZ, hashtab, i, m, name, PPSYM::next, p, PP_MAXIDLEN, q, and strlen().
dlookup()
static int dlookup (char * name) static
Definition at line 890 of file fpp.c.
References D_DEFINE, D_ELIF, D_ELSE, D_ENDIF, D_ERROR, D_IDENT, D_IF, D_IFDEF, D_IFNDEF, D_INCLUDE, D_INCLUDE_NEXT, D_LINE, D_LIST, D_MODULE, D_NOLIST, D_PRAGMA, D_UNDEF, D_WARNING, i, name, and val.
Referenced by fpp().
dodef()
static void dodef (void) static
Definition at line 952 of file fpp.c.
References ARGST, clreol(), deftab, FORMALMAX, gtok(), i, inlist(), isblank, iscsym, lookup(), MACMAX, PPSYM::name, p, pperr, pperror, q, skipbl(), strlen(), strstore(), T_IDENT, T_STRING, toktyp, tokval, and PPSYM::value.
Referenced by fpp().
doerror()
static void doerror (void) static
Definition at line 852 of file fpp.c.
References CNULL, error(), gtok(), startline, TOKMAX, toktyp, and tokval.
Referenced by fpp().
doident()
static void doident (void) static
Definition at line 846 of file fpp.c.
References clreol().
Referenced by fpp().
doincl()
static void doincl (LOGICAL include_next) static
Definition at line 1116 of file fpp.c.
References buff, clreol(), CNULL, dirnam(), dirname, dirwork, error(), fname, fndpath(), gbl, gtok(), i, idir, ifp, incfiles, inclev, incllist, INCLPATH, inclsize, inclstack, MAX_FNAME_LEN, MAXINC, NEED, NEW, NULL, p, pperr, pperror, pr_line(), skipbl(), strlen(), T_STRING, toktyp, tokval, type, and XBIT.
Referenced by fpp().
doline()
static void doline (void) static
Definition at line 808 of file fpp.c.
References clreol(), fname, inclev, inclstack, line, pperr, skipbl(), strlen(), T_IDENT, T_INTEGER, T_STRING, tobinary(), toktyp, and tokval.
Referenced by fpp().
domodule()
static void domodule (void) static
Definition at line 1223 of file fpp.c.
References clreol(), cp, gbl, i, NEW, PP_MAXIDLEN, pperr, skipbl(), T_IDENT, toktyp, and tokval.
Referenced by fpp().
doparse()
static INT doparse (void) static
Definition at line 1679 of file fpp.c.
References clreol(), Eoln, gettoken(), i, parse(), pperr, syntaxerr, and token.
Referenced by fpp().
dopragma()
static void dopragma (void) static
Definition at line 840 of file fpp.c.
References clreol().
Referenced by fpp().
doundef()
static void doundef (void) static
Definition at line 1246 of file fpp.c.
References clreol(), pperr, skipbl(), T_IDENT, toktyp, and tokval.
Referenced by fpp().
dowarning()
static void dowarning (void) static
Definition at line 867 of file fpp.c.
References CNULL, error(), gtok(), startline, TOKMAX, toktyp, and tokval.
Referenced by fpp().
findtok()
static int findtok (char * tokval, int truth) static
Definition at line 2067 of file fpp.c.
References flg, FLG::freeform, isblank, lookup(), nextok(), ptok(), subst(), T_IDENT, T_NOFIDENT, T_POUND, toktyp, and tokval.
Referenced by fpp().
fpp()
void fpp (void)
Definition at line 390 of file fpp.c.
References _ifs, accpp(), argbuf, ARGMAX, atoxi(), chkdef, clreol(), CNULL, count, cp, cur_fname, cur_line, D_DEFINE, D_ELIF, D_ELSE, D_ENDIF, D_ERROR, D_IDENT, D_IF, D_IFDEF, D_IFNDEF, D_INCLUDE, D_INCLUDE_NEXT, D_LINE, D_LIST, D_MODULE, D_NOLIST, D_PRAGMA, D_UNDEF, D_WARNING, FLG::def, deftab, dirnam(), dirname, DIRSINCS, dlookup(), dodef(), doerror(), doident(), doincl(), doline(), domodule(), doparse(), dopragma(), doundef(), dowarning(), errfatal(), error(), FLG::es, FALSE, fileloc, findtok(), finish(), flg, fname, fpp_display_macros(), FREE, gbl, hashrec, i, idir, FLG::idir, ifp, ifpush(), ifstack, iftop, incfiles, incllist, inclstack, isdig, lineloc, FLG::list, list_flag, FLG::list_macros, lookup(), MAX_FNAME_LEN, NEW, NULL, p, PGIF, PGIF_MINOR, PGIF_PATCHLEVEL, pperr, pperror, pr_line(), sccalloc(), skipbl(), FLG::smp, stash_paths(), FLG::stdinc, strlen(), strstore(), T_IDENT, tmpfile(), TOKMAX, toktyp, tokval, TRUE, FLG::undef, PPSYM::value, version, void(), FLG::x, and XBIT.
Referenced by init().
fpp_display_macros()
static void fpp_display_macros () static
Definition at line 375 of file fpp.c.
References deftab, gbl, hashrec, i, PPSYM::name, name, next_hash, PPSYM::value, and value().
Referenced by fpp().
gettoken()
static int gettoken (void) static
Definition at line 1832 of file fpp.c.
References And, Andand, Colon, Comma, Compl, Defined, Divide, Eoln, Eq, Ge, Gt, gtok(), Le, look_for_comments, lookup(), Lparen, Lshift, Lt, Minus, Mod, Mult, Ne, Not, Number, Or, Oror, pbstr(), Plus, pperr, Question, Rparen, Rshift, s, save_look_for_comments, skipbl(), T_IDENT, T_INTEGER, T_STRING, tobinary(), tokenval, toktyp, tokval, PPSYM::value, and Xor.
Referenced by doparse(), and parse().
gtok()
static int gtok (char * tokval, int expflag) static
Definition at line 2047 of file fpp.c.
References lookup(), nextok(), subst(), T_IDENT, T_NOFIDENT, toktyp, and tokval.
Referenced by clreol(), dodef(), doerror(), doincl(), dowarning(), gettoken(), skipbl(), and subst().
ifpush()
static void ifpush (void) static
Definition at line 1428 of file fpp.c.
References _ifs, IFMAX, ifstack, iftop, pperr, and ifrec::truth.
Referenced by fpp().
inlist()
static int inlist (char ** list, int nl, char * value) static
Definition at line 941 of file fpp.c.
References i, list, and value().
Referenced by dodef().
lookup()
static PPSYM * lookup (const char * name, int insflg) static
Definition at line 1466 of file fpp.c.
References buff, cp, deftab, hashrec, HASHSIZ, hashtab, i, m, MASK, PPSYM::name, name, NEED, NEW, PPSYM::next, next_hash, nhash, NULL, p, PP_MAXIDLEN, q, strstore(), and PPSYM::value.
Referenced by dodef(), findtok(), fpp(), gettoken(), and gtok().
mac_push()
static void mac_push (PPSYM * sp, char * lptr) static
Definition at line 2592 of file fpp.c.
References hashrec, interr(), macro_recur_check(), macstk, MACSTK_MAX, macstk_top, macstk_type::msptr, macstk_type::sav_lptr, and startline.
Referenced by subst().
macro_recur_check()
static void macro_recur_check (PPSYM * sp) static
Definition at line 2613 of file fpp.c.
References deftab, hashrec, i, macstk, macstk_top, name, and pperror.
Referenced by mac_push().
nextok()
static int nextok (char * tokval) static
Definition at line 2117 of file fpp.c.
References _nextline(), c, delim, DOCOPY, FLANG_FALLTHROUGH, flg, FLG::freeform, have_comment, i, inchar, isdig, ishex, isident, linebuf, lineend, LINELEN, lineptr, look_for_comments, MASK, NOFUNC, p, pbchar(), popstack(), pperr, SKIP_COMMENTS, T_COMMENT, T_IDENT, T_INTEGER, T_NOFIDENT, T_REAL, T_STRING, TOKMAX, toktyp, and tokval.
Referenced by findtok(), and gtok().
parse()
static INT parse (int rbp) static
Definition at line 1699 of file fpp.c.
References And, Andand, CHECK, Colon, Comma, Compl, Defined, Divide, Eoln, Eq, FALSE, Ge, gettoken(), Gt, lbp, Le, led, Lparen, Lshift, Lt, Minus, Minusx, Mod, Mult, Ne, Not, Number, Or, Oror, parse(), Plus, pperr, PT, Question, rbp, Rparen, Rshift, syntaxerr, tmp, token, tokenval, TRUE, and Xor.
Referenced by doparse(), and parse().
pbchar()
static void pbchar (int c) static
Definition at line 2569 of file fpp.c.
References c, linebuf, lineptr, look_for_comments, and pperr.
Referenced by nextok(), and subst().
pbstr()
static void pbstr (char * s) static
Definition at line 2580 of file fpp.c.
References linebuf, lineptr, look_for_comments, p, pperr, s, and strlen().
Referenced by gettoken(), and subst().
popstack()
static void popstack (void) static
Definition at line 2606 of file fpp.c.
References lineptr, macstk, and macstk_top.
Referenced by nextok().
pr_line()
static void pr_line (const char * name, int line) static
Definition at line 787 of file fpp.c.
References FLG::es, flg, gbl, inclev, line, name, and XBIT.
Referenced by _nextline(), doincl(), fpp(), and ptok().
ptok()
static void ptok (const char * tok) static
Definition at line 1568 of file fpp.c.
References cur_fname, cur_line, FILE, fname, fp, gbl, inclev, inclstack, NULL, pr_line(), startline, tok, and void().
Referenced by findtok(), and subst().
skipbl()
static int skipbl (char * tokval, int flag) static
Definition at line 364 of file fpp.c.
References gtok(), isblank, toktyp, and tokval.
Referenced by dodef(), doincl(), doline(), domodule(), doundef(), fpp(), and gettoken().
stash_paths()
static void stash_paths (const char * dirs) static
Definition at line 2623 of file fpp.c.
References DIRSEP, idir, n, NEED, NULL, path, and TRUE.
Referenced by fpp().
strstore()
static INT strstore (const char * name) static
Definition at line 1442 of file fpp.c.
References deftab, i, j, name, ndef, NEED, NEW, next_def, and strlen().
Referenced by dodef(), fpp(), and lookup().
subst()
static int subst (PPSYM * sp) static
Definition at line 1260 of file fpp.c.
References argbuf, ARGMAX, ARGST, CNULL, cur_line, d, deftab, error(), fileloc, fname, FORMALMAX, gtok(), hashrec, i, inclev, inclstack, isblank, lineloc, lineno, lineptr, mac_push(), PPSYM::name, NOFUNC, NULL, p, pbchar(), pbstr(), pperror, ptok(), q, sccrelal(), strlen(), toktyp, tokval, PPSYM::value, and XBIT.
Referenced by findtok(), and gtok().
tobinary()
static INT tobinary (char * st, int b) static
Definition at line 1989 of file fpp.c.
References b, c, FLANG_FALLTHROUGH, n, pperror, s, st, and t.
Referenced by doline(), and gettoken().
Variable Documentation
_ifs
struct ifrec _ifs[IFMAX] static
Definition at line 241 of file fpp.c.
Referenced by fpp(), and ifpush().
argbuf
char* argbuf static
Definition at line 322 of file fpp.c.
Referenced by dodef(), fpp(), and subst().
ARGMAX
size_t ARGMAX = 2048 static
Definition at line 323 of file fpp.c.
Referenced by fpp(), and subst().
b
char* b
Definition at line 314 of file fpp.c.
Referenced by tobinary().
b_avl
int b_avl
Definition at line 315 of file fpp.c.
b_sz
int b_sz
Definition at line 316 of file fpp.c.
cnt
int cnt
Definition at line 311 of file fpp.c.
ctable
char ctable[256] static
Definition at line 39 of file fpp.c.
cur_fname
char cur_fname[MAX_FNAME_LEN] static
Definition at line 289 of file fpp.c.
Referenced by _nextline(), fpp(), and ptok().
cur_line
int cur_line static
Definition at line 290 of file fpp.c.
Referenced by fpp(), ptok(), and subst().
deftab
char* deftab static
Definition at line 249 of file fpp.c.
Referenced by delete(), dodef(), fpp(), fpp_display_macros(), lookup(), macro_recur_check(), strstore(), and subst().
dirname
char dirname[MAX_FNAME_LEN]
Definition at line 260 of file fpp.c.
Referenced by _doincl(), accpp(), clause_errchk(), dirnam(), doincl(), fpp(), get_filename(), lower_fileinfo(), lower_fileinfo_llvm(), read_fileentries(), scan_include(), and semsmp().
dirwork
char dirwork[MAX_FNAME_LEN] static
Definition at line 293 of file fpp.c.
Referenced by doincl().
fileloc
int fileloc static
Definition at line 284 of file fpp.c.
Referenced by fpp(), and subst().
fname
char fname[MAX_FNAME_LEN]
Definition at line 259 of file fpp.c.
Referenced by _nextline(), doincl(), doline(), fpp(), ptok(), and subst().
hashrec
PPSYM* hashrec static
Definition at line 245 of file fpp.c.
Referenced by delete(), fpp(), fpp_display_macros(), lookup(), mac_push(), macro_recur_check(), and subst().
hashtab
INT hashtab[HASHSIZ] static
Definition at line 244 of file fpp.c.
Referenced by delete(), and lookup().
have_comment
int have_comment static
Definition at line 278 of file fpp.c.
Referenced by _nextline(), and nextok().
struct { ... } idir
Referenced by _nextline(), doincl(), fpp(), and stash_paths().
ifp
FILE* ifp static
Definition at line 220 of file fpp.c.
Referenced by _nextline(), doincl(), and fpp().
iftop
int iftop static
Definition at line 240 of file fpp.c.
Referenced by fpp(), and ifpush().
incfiles
int incfiles = 0 static
Definition at line 272 of file fpp.c.
Referenced by doincl(), and fpp().
inclev
int inclev = 0 static
Definition at line 267 of file fpp.c.
Referenced by _nextline(), doincl(), doline(), pr_line(), ptok(), and subst().
incllist
INCLENTRY* incllist static
Definition at line 271 of file fpp.c.
Referenced by doincl(), and fpp().
inclsize
int inclsize static
Definition at line 273 of file fpp.c.
Referenced by doincl().
struct { ... } inclstack[MAXINC]
Referenced by _nextline(), doincl(), doline(), fpp(), ptok(), and subst().
last
int last
Definition at line 318 of file fpp.c.
lbp
short lbp
Definition at line 1637 of file fpp.c.
Referenced by parse().
led
INT8 led
Definition at line 1632 of file fpp.c.
Referenced by parse().
linebuf
char linebuf[LINELEN+LINELEN] static
Definition at line 277 of file fpp.c.
Referenced by _nextline(), nextok(), pbchar(), and pbstr().
lineend
char * lineend static
Definition at line 276 of file fpp.c.
Referenced by _nextline(), and nextok().
lineloc
int lineloc static
Definition at line 284 of file fpp.c.
Referenced by fpp(), and subst().
lineno
int lineno
Definition at line 261 of file fpp.c.
Referenced by _ccff_info(), _do_iface(), _nextline(), _read_token(), add_no_scope_sptr(), addfile(), addinlfile(), annomod_asm(), ccff_ilt_info(), ccff_info(), check_continuation(), check_used_in_data(), chk_evar(), defer_arg_chk(), ENTCRF90IO(), ENTF90(), ENTF90IO(), export_data_file(), export_data_file_asts(), export_equiv_item(), export_ivl_ict(), export_symbol(), fih_message_ofile(), fih_messages(), fill_entry_bounds(), fill_sym(), find_rgn(), forall_dependency(), forall_dependency_scalarize(), fperror(), gen_contig_check(), get_stmt(), import(), inline_reduction_f90(), inline_small_matmul(), ll_get_outlined_funcname(), lldbg_assign_lexical_block(), lldbg_create_module_mdnode(), lldbg_emit_lexical_block(), lldbg_emit_lexical_blocks(), lldbg_emit_line(), lldbg_emit_outlined_subprogram(), lldbg_emit_subprogram(), lldbg_reserve_lexical_block(), llvm_lower_enddo_stmt(), lower_data_stmts(), lower_do_stmt(), lower_enddo_stmt(), lower_start_stmt(), lower_stmt(), par_xref_put(), parse_im_file(), print_par_xref(), printxref(), put_data_statement(), put_lineno(), qs_anno(), read_CCFF(), read_fileentries(), report_collapse(), rw_dinit_state(), sem_err104(), sequentialize(), sequentialize_call(), subccff_ilt_info(), subccff_info(), subfih(), subst(), transform_c_f_pointer(), transform_c_f_procpointer(), transform_elemental(), transform_merge(), transform_move_alloc(), and transform_mvbits().
lineptr
char* lineptr static
Definition at line 276 of file fpp.c.
Referenced by _nextline(), nextok(), pbchar(), pbstr(), popstack(), and subst().
list_flag
int list_flag static
Definition at line 298 of file fpp.c.
Referenced by _nextline(), and fpp().
look_for_comments
int look_for_comments static
Definition at line 279 of file fpp.c.
Referenced by _nextline(), gettoken(), nextok(), pbchar(), and pbstr().
macstk
struct macstk_type macstk[MACSTK_MAX] static
Definition at line 305 of file fpp.c.
Referenced by mac_push(), macro_recur_check(), and popstack().
macstk_top
int macstk_top = -1 static
Definition at line 306 of file fpp.c.
Referenced by mac_push(), macro_recur_check(), and popstack().
ndef
INT ndef static
Definition at line 250 of file fpp.c.
Referenced by strstore().
next_def
INT next_def static
Definition at line 250 of file fpp.c.
Referenced by strstore().
next_hash
INT next_hash static
Definition at line 246 of file fpp.c.
Referenced by fpp_display_macros(), and lookup().
nhash
INT nhash static
Definition at line 246 of file fpp.c.
Referenced by lookup().
nud
INT8 nud
Definition at line 1634 of file fpp.c.
path
int* path
Definition at line 310 of file fpp.c.
Referenced by stash_paths().
path_idx
int path_idx
Definition at line 262 of file fpp.c.
struct { ... } PT[]
Referenced by parse().
rbp
INT8 rbp
Definition at line 1638 of file fpp.c.
Referenced by parse().
save_look_for_comments
int save_look_for_comments static
Definition at line 280 of file fpp.c.
Referenced by gettoken().
startline
int startline static
Definition at line 296 of file fpp.c.
Referenced by _nextline(), doerror(), dowarning(), mac_push(), and ptok().
syntaxerr
int syntaxerr static
Definition at line 255 of file fpp.c.
Referenced by doparse(), and parse().
sz
int sz
Definition at line 312 of file fpp.c.
token
int token static
Definition at line 253 of file fpp.c.
Referenced by doparse(), and parse().
tokenval
INT tokenval static
Definition at line 254 of file fpp.c.
Referenced by gettoken(), and parse().
tokval
char tokval[TOKMAX] static
Definition at line 237 of file fpp.c.
Referenced by accpp(), clreol(), dodef(), doerror(), doident(), doincl(), doline(), domodule(), dopragma(), doundef(), dowarning(), findtok(), fpp(), gettoken(), gtok(), nextok(), predarg(), predicate(), skipbl(), and subst().