flang: fs_sincos_vector.cpp File Reference
fs_sincos_vector.cpp File Reference
#include <stdio.h>
#include <stdbool.h>
#include <math.h>
#include "sincosf.h"
Macros
#define CONFIG 1
#define SINCOS_COMMA
#define _CONCAT(l, r) l##r
#define CONCAT(l, r) _CONCAT(l,r)
#define _CONCAT4(ll, l, r, rr) ll##l##r##rr
#define CONCAT4(ll, l, r, rr) _CONCAT4(ll,l,r,rr)
#define FCN_NAME CONCAT(CONCAT4(__fs_,FNAME,_,VL),_avx2)
Functions
vfloat FCN_NAME (const vfloat x)
static void INLINE __reduction_slowpath (vfloat const a, S(vfloat *sr, vmask *sh) SINCOS_COMMA C(vfloat *cr, vmask *ch))
vfloat __attribute__ ((noinline)) FCN_NAME(const vfloat x)
Macro Definition Documentation
_CONCAT
#define _CONCAT (l, r) l##r
Definition at line 49 of file fs_sincos_vector.cpp.
_CONCAT4
#define _CONCAT4 (ll, l, r, rr) ll##l##r##rr
Definition at line 51 of file fs_sincos_vector.cpp.
CONCAT
#define CONCAT (l, r) _CONCAT(l,r)
Definition at line 50 of file fs_sincos_vector.cpp.
CONCAT4
#define CONCAT4 (ll, l, r, rr) _CONCAT4(ll,l,r,rr)
Definition at line 52 of file fs_sincos_vector.cpp.
CONFIG
#define CONFIG 1
Definition at line 18 of file fs_sincos_vector.cpp.
FCN_NAME
#define FCN_NAME CONCAT(CONCAT4(__fs_,FNAME,_,VL),_avx2)
Definition at line 56 of file fs_sincos_vector.cpp.
SINCOS_COMMA
#define SINCOS_COMMA
Definition at line 29 of file fs_sincos_vector.cpp.
Function Documentation
__attribute__()
vfloat __attribute__ ((noinline)) const
Definition at line 206 of file fs_sincos_vector.cpp.
References _1_OVER_PI_F, __mth_return2vectors(), __reduction_slowpath(), A_F, B_F, C, C_F, D_F, E_F, hc, kc, PI_HI_F, PI_LO_F, PI_MI_F, rc, S(), SINCOS(), SINCOS_COMMA, ss, THRESHOLD_F, ts, vabs_vf_vf(), vadd_vf_vf_vf(), vcast_vf_f(), vcast_vi2_i(), vfma_vf_vf_vf_vf(), vfmapn_vf_vf_vf_vf(), vgt_vo_vi2_vi2(), vmul_vf_vf_vf(), vsel_vf_vo_vf_vf(), vsel_vi2_vo_vi2_vi2(), vsll_vi2_vi2_i(), vsub_vf_vf_vf(), vtestz_i_vo(), vxor_vi2_vi2_vi2(), and x.
__reduction_slowpath()
static void INLINE __reduction_slowpath (vfloat const a, S(vfloat *sr, vmask *sh) SINCOS_COMMA C(vfloat *cr, vmask *ch)) static
Definition at line 70 of file fs_sincos_vector.cpp.
References a, C, cp, e, float_as_int(), hi, i, i1opi_f, ia, idx, if(), lo, m, p, PI_2_M63, prev, q, S(), s, SINCOS_COMMA, t, ull, vadd64_vi2_vi2_vi2(), vadd_vi2_vi2_vi2(), vand_vi2_vi2_vi2(), vcast_vi2_i(), vcast_vm_i_i(), veq_vo_vi2_vi2(), vmulu_vi2_vi2_vi2(), vor_vi2_vi2_vi2(), vsel_vi2_vo_vi2_vi2(), vsll64_vi2_vi2_i(), vsll_vi2_vi2_i(), vsrl64_vi2_vi2_i(), vsrl_vi2_vi2_i(), vstore_v_p_vf(), and vsub_vi2_vi2_vi2().
Referenced by __attribute__().
FCN_NAME()
vfloat FCN_NAME (const vfloat x)