flang: fs_tan_1_avx2.cpp File Reference
fs_tan_1_avx2.cpp File Reference
#include <assert.h>
#include <stdio.h>
#include <math.h>
#include <immintrin.h>
#include "common_tanf.h"
Macros
#define __TAN_F_SCALAR_H__
Functions
float __attribute__ ((noinline)) __fs_tan_1_avx2(float const a)
static float reduction_slowpath (float const a, int32_t *h)
Macro Definition Documentation
__TAN_F_SCALAR_H__
#define __TAN_F_SCALAR_H__
Definition at line 11 of file fs_tan_1_avx2.cpp.
Function Documentation
__attribute__()
float __attribute__ ((noinline)) const
Definition at line 78 of file fs_tan_1_avx2.cpp.
References _2_OVER_PI_F, A_F, B_F, C_F, D_F, E_F, F_F, float_as_int(), FMAF, h, int_as_float(), k, p, PI_2_HI_F, PI_2_LO_F, PI_2_MI_F, r, reduction_slowpath(), s, t, THRESHOLD_F, and x.
reduction_slowpath()
static float reduction_slowpath (float const a, int32_t * h) static
Definition at line 25 of file fs_tan_1_avx2.cpp.
References a, d, e, float_as_int(), h, hi, i2opi_f, ia, idx, int_as_float(), lo, m, p, PI_2_M64, q, r, result, s, and umad32wide().
Referenced by __attribute__().