flang: fs_sincos_scalar.cpp File Reference
fs_sincos_scalar.cpp File Reference
#include <assert.h>
#include <stdio.h>
#include <math.h>
#include <immintrin.h>
#include "sincosf.h"
Macros
#define SINCOS_COMMA
#define _CONCAT(l, r) l##r
#define CONCAT(l, r) _CONCAT(l,r)
#define FCN_NAME CONCAT(CONCAT(__fs_,FNAME),_1_avx2)
Functions
float FCN_NAME (const float x)
static void __attribute__ ((noinline)) reduction_slowpath(float const a
static void S (float *rs, int32_t *hs) SINCOS_COMMA C(float *rc
S (uint32_t ss=ia &0x80000000;) uint32_t result[7]
for (q=0;q< 6;q++)
if (e)
p & S (uint64_t ps=p;int32_t qs=q;qs=(result[idx+2]<< e) &0x80000000;if(ps &0x4000000000000000ULL) { ps|=0x8000000000000000ULL;qs ^=0x80000000;} *hs=qs ^ ss;double ds=(double)(int64_t) ps;ds *=PI_2_M63; *rs=(float) ds;) C(uint64_t pc
Variables
static void int32_t * hc
uint32_t ia = float_as_int(a)
uint32_t hi = 0
uint32_t lo
uint32_t e = ((ia >> 23) & 0xff) - 127
int32_t idx = 4 - ((e >> 5) & 3)
int32_t q
result [q] = hi
uint64_t p = ((uint64_t)result[idx + 2] << 32) | result[idx + 1]
pc = (int64_t)pc - 0x4000000000000000LL
double dc = (double)(int64_t)pc
dc ** rc = (float)dc
Macro Definition Documentation
_CONCAT
#define _CONCAT (l, r) l##r
Definition at line 36 of file fs_sincos_scalar.cpp.
CONCAT
#define CONCAT (l, r) _CONCAT(l,r)
Definition at line 37 of file fs_sincos_scalar.cpp.
FCN_NAME
#define FCN_NAME CONCAT(CONCAT(__fs_,FNAME),_1_avx2)
Definition at line 39 of file fs_sincos_scalar.cpp.
SINCOS_COMMA
#define SINCOS_COMMA
Definition at line 17 of file fs_sincos_scalar.cpp.
Function Documentation
__attribute__()
static void __attribute__ ((noinline)) const static
Definition at line 121 of file fs_sincos_scalar.cpp.
References _1_OVER_PI_F, _mm_cvtss_f32(), A_F, B_F, C, C_F, D_F, E_F, float_as_int(), FMAF, hc, int_as_float(), kc, p, PI_HI_F, PI_LO_F, PI_MI_F, rc, reduction_slowpath(), S(), SINCOS(), SINCOS_COMMA, ss, THRESHOLD_F, ts, va, and x.
FCN_NAME()
float FCN_NAME (const float x)
for()
for ()
Definition at line 66 of file fs_sincos_scalar.cpp.
References hi, i1opi_f, ia, lo, m, q, result, and umad32wide().
if()
if (e)
Definition at line 81 of file fs_sincos_scalar.cpp.
References e, idx, p, q, and result.
S() [1/3]
static void S (float * rs, int32_t * hs)
Referenced by __attribute__(), __erf(), __erfc(), __reduction_slowpath(), and reduction_slowpath().
S() [2/3]
S (uint32_t ss = ia &0x80000000;)
S() [3/3]
p & S (uint64_t ps = p;int32_t qs=q;qs=(result[idx+2]<< e) &0x80000000;if(ps &0x4000000000000000ULL) { ps|=0x8000000000000000ULL;qs ^=0x80000000;} *hs=qs ^ ss;double ds=(double)(int64_t) ps;ds *=PI_2_M63; *rs=(float) ds;)
Variable Documentation
dc
double dc = (double)(int64_t)pc
Definition at line 114 of file fs_sincos_scalar.cpp.
Referenced by __fort_copy(), and msg().
e
e = ((ia >> 23) & 0xff) - 127
Definition at line 56 of file fs_sincos_scalar.cpp.
Referenced by if().
hc
* hc
Initial value:
{
    uint2 m
Definition at line 49 of file fs_sincos_scalar.cpp.
Referenced by __attribute__(), __reduction_slowpath(), and reduction_slowpath().
hi
hi = 0
Definition at line 55 of file fs_sincos_scalar.cpp.
Referenced by for().
ia
ia = float_as_int(a)
Definition at line 52 of file fs_sincos_scalar.cpp.
Referenced by for().
idx
idx = 4 - ((e >> 5) & 3)
Definition at line 57 of file fs_sincos_scalar.cpp.
Referenced by if().
lo
uint32_t lo
Definition at line 55 of file fs_sincos_scalar.cpp.
Referenced by for().
p
uint64_t p = ((uint64_t)result[idx + 2] << 32) | result[idx + 1]
Definition at line 79 of file fs_sincos_scalar.cpp.
Referenced by __attribute__(), and if().
pc
pc = (int64_t)pc - 0x4000000000000000LL
Definition at line 112 of file fs_sincos_scalar.cpp.
Referenced by __attribute__(), __fort_global_reduce(), __fort_reduce_section(), __fort_replicate_result(), __io_read(), copy_xfer(), olap_recv(), olap_send(), and reduction_slowpath().
q
int32_t q
Definition at line 58 of file fs_sincos_scalar.cpp.
Referenced by for(), and if().
rc
dc* * rc = (float)dc
Definition at line 116 of file fs_sincos_scalar.cpp.
Referenced by __attribute__(), __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), __reduction_slowpath(), copy_loop(), copy_xfer(), cshift_loop(), ENTFTN(), eoshift_loop(), eoshift_scalar(), Ftn_i_i1shftc(), Ftn_i_iishftc(), ftn_i_kishftc(), Ftn_ishftc(), get_token(), and reduction_slowpath().
result
result[q] = hi
Definition at line 72 of file fs_sincos_scalar.cpp.
Referenced by for(), and if().