flang: fs_log10_scalar.cpp File Reference
fs_log10_scalar.cpp File Reference
#include <immintrin.h>
#include <common.h>
Macros
#define _JOIN2(a, b) a##b
#define JOIN2(a, b) _JOIN2(a,b)
#define log10_scalar JOIN2(__fs_log10_1_,_CPU)
Functions
float log10_scalar (float)
float __attribute__ ((noinline)) log10_scalar(float a_input)
Macro Definition Documentation
_JOIN2
#define _JOIN2 (a, b) a##b
Definition at line 16 of file fs_log10_scalar.cpp.
JOIN2
#define JOIN2 (a, b) _JOIN2(a,b)
Definition at line 17 of file fs_log10_scalar.cpp.
log10_scalar
#define log10_scalar JOIN2(__fs_log10_1_,_CPU)
Definition at line 19 of file fs_log10_scalar.cpp.
Function Documentation
__attribute__()
float __attribute__ ((noinline))
Definition at line 24 of file fs_log10_scalar.cpp.
References _mm_cvtss_f32(), a, b, CANONICAL_NAN, e, float_as_int(), i, int_as_float(), m, MANTISSA_MASK, NINF, PINF, res, t, and TWO_TO_24_F.
log10_scalar()
float log10_scalar (float)