flang: fsync3f.c File Reference
fsync3f.c File Reference
#include "io3f.h"
#include "ent3f.h"
#include "utils3f.h"
#include "stdioInterf.h"
Functions
void ENT3F (FSYNC, fsync)
Function Documentation
ENT3F()
void ENT3F (FSYNC , fsync)
Definition at line 16 of file fsync3f.c.
References __getfile3f(), __io_getfd(), f, fflush(), and FILE.