flang: ftn.c File Reference
ftn.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
Functions
void __fort_csend (int cpu, void *adr, int cnt, int str, int typ)
void __fort_crecv (int cpu, void *adr, int cnt, int str, int typ)
void ENTFTN (CSEND, csend)
void ENTFTN (CSENDCHARA, csendchara)
void ENTFTN (CSENDCHAR, csendchar)
void ENTFTN (CRECV, crecv)
void ENTFTN (CRECVCHARA, crecvchara)
void ENTFTN (CRECVCHAR, crecvchar)
Variables
static int ltypes []
Function Documentation
__fort_crecv()
void __fort_crecv (int cpu, void * adr, int cnt, int str, int typ)
Definition at line 52 of file ftn.c.
References __fort_abort(), __fort_rrecv(), cnt, cpu(), GET_DIST_LCPU, ltypes, and str.
__fort_csend()
void __fort_csend (int cpu, void * adr, int cnt, int str, int typ)
Definition at line 41 of file ftn.c.
References __fort_abort(), __fort_rsend(), cnt, cpu(), GET_DIST_LCPU, ltypes, and str.
ENTFTN() [1/6]
void ENTFTN (CRECV , crecv)
Definition at line 98 of file ftn.c.
References __fort_abort(), __fort_rrecv(), cnt, cpu(), GET_DIST_LCPU, ltypes, and str.
ENTFTN() [2/6]
void ENTFTN (CRECVCHAR , crecvchar)
Definition at line 126 of file ftn.c.
References __CLEN_T, buf, CADR, CLEN, cnt, cpu(), ENTFTN(), and str.
ENTFTN() [3/6]
void ENTFTN (CRECVCHARA , crecvchara)
Definition at line 107 of file ftn.c.
References __CLEN_T, __fort_abort(), __fort_rrecv(), __STR, buf, CADR, CLEN, cnt, cpu(), GET_DIST_LCPU, len, n, and skip.
ENTFTN() [4/6]
void ENTFTN (CSEND , csend)
Definition at line 62 of file ftn.c.
References __fort_abort(), __fort_rsend(), cnt, cpu(), GET_DIST_LCPU, ltypes, and str.
Referenced by ENTFTN().
ENTFTN() [5/6]
void ENTFTN (CSENDCHAR , csendchar)
Definition at line 90 of file ftn.c.
References __CLEN_T, buf, CADR, CLEN, cnt, cpu(), ENTFTN(), and str.
ENTFTN() [6/6]
void ENTFTN (CSENDCHARA , csendchara)
Definition at line 71 of file ftn.c.
References __CLEN_T, __fort_abort(), __fort_rsend(), __STR, buf, CADR, CLEN, cnt, cpu(), GET_DIST_LCPU, len, n, and skip.
Variable Documentation
ltypes
int ltypes[] static
Initial value:
= {
    __INT1,
    __INT2,
    __INT4,
    __INT8,
    __LOG1,
    __LOG2,
    __LOG4,
    __LOG8,
    __REAL4,
    __REAL8,
    __REAL16,
    __CPLX8,
    __CPLX16,
    __CPLX32,
    __WORD4,
    __WORD8,
    __WORD16
}
Definition at line 18 of file ftn.c.
Referenced by __fort_crecv(), __fort_csend(), ENTFTN(), get_line(), and get_line1().