flang: ftncharsup.c File Reference
ftncharsup.c File Reference
#include <stdint.h>
#include <stdio.h>
#include "global.h"
#include "stdarg.h"
#include "enames.h"
#include <string.h>
#include "llcrit.h"
#include "mpalloc.h"
Macros
#define NULL (void *)0
#define PTRSZ sizeof(char *)
#define PTRSZ sizeof(char *)
Functions
void Ftn_str_copy (int n, char *to, int to_len,...)
Copies a series of character strings into another.
void Ftn_str_cpy1 (char *to, int to_len, char *from, int from_len)
single source, no overlap
char ** Ftn_str_malloc (int size, char ***hdr)
Utility routines to allocatespace for character expressions whose lengths are known only at run-time. The compiler creates a variable to locate the list of blocks allocated during a subprogram. This variable is initialized to NULL upon entry to the subprogram. When the subprogram exits, all of the blocks are freed. Each block of space consists of n 'words':
void Ftn_str_free (char **first)
Utility routine to deallocate space for character expressions whose lengths are known only at run-time.
void Ftn_str_copy_klen (int n, char *to, int64_t to_len,...)
Copies a series of character strings into another.
void Ftn_str_cpy1_klen (char *to, int64_t to_len, char *from, int64_t from_len)
single source, no overlap
int64_t Ftn_str_index_klen (const unsigned char *const a1, const unsigned char *const a2, int64_t a1_len, int64_t a2_len)
Implements the INDEX intrinsic; is an integer function which returns the value according to the INDEX intrinsic.
int Ftn_str_index (const unsigned char *const a1, const unsigned char *const a2, int64_t a1_len, int64_t a2_len)
Implements the INDEX intrinsic; is an integer function which returns the value according to the INDEX intrinsic.
int Ftn_strcmp_klen (const unsigned char *const a1, const unsigned char *const a2, int64_t a1_len, int64_t a2_len)
Implements realational operators with string operands and the lexical intrinsics. Returns integer value:
int Ftn_strcmp (const unsigned char *const a1, const unsigned char *const a2, int a1_len, int a2_len)
Implements realational operators with string operands and the lexical intrinsics. Returns integer value:
char ** Ftn_str_malloc_klen (int64_t size, char ***hdr)
Utility routine to allocate space for character expressions whose lengths are known only at run-time.
Detailed Description
Fortran character support routines
Definition in file ftncharsup.c.
Macro Definition Documentation
NULL
#define NULL (void *)0
Definition at line 22 of file ftncharsup.c.
PTRSZ [1/2]
#define PTRSZ sizeof(char *)
PTRSZ [2/2]
#define PTRSZ sizeof(char *)
Function Documentation
Ftn_str_copy()
void Ftn_str_copy (int n, char * to, int to_len, ...)
Copies a series of character strings into another.
This function is used to implement character assignments and concatenations. It pads with blanks if the destination string is longer than the sum of the lengths of the source strings and truncates if the sum of the lengths of the source strings is longer than the destination string.
Allow the target of the concatenation to appear in its right-hand side which is standard f90 and is a common extension to f77.
Parameters
n number of source strings
to pointer to destination string
to_len length of destination string
 Vargs:
   {from           pointer to kth source string
    from_len}*     length of kth source string
Definition at line 50 of file ftncharsup.c.
References _mp_free(), _mp_malloc(), cnt, len, n, qq, and str.
Ftn_str_copy_klen()
void Ftn_str_copy_klen (int n, char * to, int64_t to_len, ...)
Copies a series of character strings into another.
This function is used to implement character assignments and concatenations. It pads with blanks if the destination string is longer than the sum of the lengths of the source strings and truncates if the sum of the lengths of the source strings is longer than the destination string.
Allow the target of the concatenation to appear in its right-hand side which is standard f90 and is a common extension to f77.
Parameters
n number of source strings
to pointer to destination string
to_len length of destination string
Varargs:
  {from           pointer to kth source string
  from_len}*      length of kth source string
Definition at line 285 of file ftncharsup.c.
References _mp_free(), _mp_malloc(), cnt, len, n, qq, and str.
Ftn_str_cpy1()
void Ftn_str_cpy1 (char * to, int to_len, char * from, int from_len)
single source, no overlap
Definition at line 160 of file ftncharsup.c.
Ftn_str_cpy1_klen()
void Ftn_str_cpy1_klen (char * to, int64_t to_len, char * from, int64_t from_len)
single source, no overlap
Definition at line 395 of file ftncharsup.c.
Ftn_str_free()
void Ftn_str_free (char ** first)
Utility routine to deallocate space for character expressions whose lengths are known only at run-time.
The compiler creates a variable to locate the list of blocks allocated during a subprogram. This variable is initialized to NULL upon entry to the subprogram. When the subprogram exits, all of the blocks are freed. Each block of space consists of n 'words':
++ first word - pointer to the next allocated block,
++ remaining word(s) - space for the character data.
Parameters
first - pointer to the compiler-created variable locating the list of allocated blocks. Ftn_str_free traverses the list of allocated blocks and frees each block.
Definition at line 249 of file ftncharsup.c.
References _mp_free(), first, next, NULL, and p.
Ftn_str_index()
int Ftn_str_index (const unsigned char *const a1, const unsigned char *const a2, int64_t a1_len, int64_t a2_len)
Implements the INDEX intrinsic; is an integer function which returns the value according to the INDEX intrinsic.
Parameters
a1 pointer to string being searched
a2 pointer to string being searched for
a1_len length of a1
a2_len length of a2
Definition at line 471 of file ftncharsup.c.
References Ftn_str_index_klen().
Ftn_str_index_klen()
int64_t Ftn_str_index_klen (const unsigned char *const a1, const unsigned char *const a2, int64_t a1_len, int64_t a2_len)
Implements the INDEX intrinsic; is an integer function which returns the value according to the INDEX intrinsic.
Parameters
a1 pointer to string being searched
a2 pointer to string being searched for
a1_len length of a1
a2_len length of a2
Definition at line 431 of file ftncharsup.c.
References FALSE, match(), and TRUE.
Referenced by Ftn_str_index().
Ftn_str_malloc()
char ** Ftn_str_malloc (int size, char *** hdr)
Utility routines to allocatespace for character expressions whose lengths are known only at run-time. The compiler creates a variable to locate the list of blocks allocated during a subprogram. This variable is initialized to NULL upon entry to the subprogram. When the subprogram exits, all of the blocks are freed. Each block of space consists of n 'words':
++ first word - pointer to the next allocated block,
++ remaining word(s) - space for the character data.
Parameters
size - number of bytes needed,
hdr - pointer to the compiler-created variable locating the list of allocated blocks. Ftn_str_malloc updates this variable.
Returns
returns a pointer to the space after the 'next pointer'.
Note that KANJI versions are unneeded since the compiler just calls Ftn_str_malloc() with an adjusted length.
Definition at line 206 of file ftncharsup.c.
References __io_stderr(), _mp_malloc(), Ftn_exit, MP_P_STDIO, MP_V_STDIO, NULL, p, PTRSZ, q, and size.
Ftn_str_malloc_klen()
char ** Ftn_str_malloc_klen (int64_t size, char *** hdr)
Utility routine to allocate space for character expressions whose lengths are known only at run-time.
The compiler creates a variable to locate the list of blocks allocated during a subprogram. This variable is initialized to NULL upon entry to the subprogram. When the subprogram exits, all of the blocks are freed. Each block of space consists of n 'words':
++ first word - pointer to the next allocated block,
++ remaining word(s) - space for the character data.
Parameters
size - number of bytes needed,
hdr - pointer to the compiler-created variable locating the list of allocated blocks. Ftn_str_malloc updates this variable.
Returns
returns a pointer to the space after the 'next pointer'.
void Ftn_str_free(char ***hdr) hdr - pointer to the compiler-created variable locating the list of allocated blocks. Ftn_str_free traverses the list of allocated blocks and frees each block.
Note that KANJI versions are unneeded since the compiler just calls Ftn_str_malloc() with an adjusted length.
Definition at line 670 of file ftncharsup.c.
References __io_stderr(), _mp_malloc(), Ftn_exit, MP_P_STDIO, MP_V_STDIO, NULL, p, PTRSZ, q, and size.
Ftn_strcmp()
int Ftn_strcmp (const unsigned char *const a1, const unsigned char *const a2, int a1_len, int a2_len)
Implements realational operators with string operands and the lexical intrinsics. Returns integer value:
0 => strings are the same
-1 => a1 lexically less than a2
1 => a1 lexically greater than a2 If the strings are of unequal lengths, treats shorter string as if it were padded with blanks.
Parameters
a1 pointer to left hand string
a2 pointer to right hand string
a1_len length of left hand string
a2_len length of right hand string
Definition at line 634 of file ftncharsup.c.
References Ftn_strcmp_klen().
Ftn_strcmp_klen()
int Ftn_strcmp_klen (const unsigned char *const a1, const unsigned char *const a2, int64_t a1_len, int64_t a2_len)
Implements realational operators with string operands and the lexical intrinsics. Returns integer value:
0 => strings are the same
-1 => a1 lexically less than a2
1 => a1 lexically greater than a2 If the strings are of unequal lengths, treats shorter string as if it were padded with blanks.
Parameters
a1 pointer to left hand string
a2 pointer to right hand string
a1_len length of left hand string
a2_len length of right hand string
Definition at line 497 of file ftncharsup.c.
References one.
Referenced by Ftn_strcmp().