flang: ftnexit.c File Reference
ftnexit.c File Reference
#include "global.h"
#include <fenv.h>
#include "fioMacros.h"
#include "llcrit.h"
Functions
void ENTF90 (EXIT, exit)
void ENTCRF90 (EXIT, exit)
static void _f90io_f2003_stop_with_ieee_warnings (int exc)
static void _f90io_stop (int exit_status, char *str, __CLEN_T str_siz, __LOG_T is_quiet, __LOG_T is_errorstop)
void ENTF90 (ERRORSTOP08a_char, errorstop08a_char)
ERROR STOP runtime when the stop code is scalar-default-char-expr.
void ENTF90 (ERRORSTOP08a_int, errorstop08a_int)
ERROR STOP runtime when the stop code is scalar-default-int-expr.
void ENTF90 (STOP08a, stop08a)
void ENTF90 (STOP08, stop08)
void ENTF90 (STOPA, stopa)
void ENTF90 (STOP, stop)
void ENTCRF90 (STOPA, stopa)
void ENTCRF90 (STOP, stop)
static void _f90io_pause (char *str, __CLEN_T str_siz)
void ENTF90 (PAUSEA, pausea)
void ENTF90 (PAUSE, pause)
void ENTCRF90 (PAUSEA, pausea)
void ENTCRF90 (PAUSE, pause)
Function Documentation
_f90io_f2003_stop_with_ieee_warnings()
static void _f90io_f2003_stop_with_ieee_warnings (int exc) static
Definition at line 29 of file ftnexit.c.
References __io_stderr().
Referenced by _f90io_stop().
_f90io_pause()
static void _f90io_pause (char * str, __CLEN_T str_siz) static
Definition at line 163 of file ftnexit.c.
References __fort_getfd, __fort_isatty, __io_feof(), __io_stderr(), __io_stdin(), MP_P_STDIO, MP_V_STDIO, and str.
Referenced by ENTCRF90(), and ENTF90().
_f90io_stop()
static void _f90io_stop (int exit_status, char * str, __CLEN_T str_siz, __LOG_T is_quiet, __LOG_T is_errorstop) static
Definition at line 48 of file ftnexit.c.
References __fenv_fetestexcept(), __fort_exit(), __fort_getenv(), __io_stderr(), _f90io_f2003_stop_with_ieee_warnings(), MP_P_STDIO, MP_V_STDIO, and str.
Referenced by ENTCRF90(), and ENTF90().
ENTCRF90() [1/5]
void ENTCRF90 (EXIT , exit)
Definition at line 23 of file ftnexit.c.
References __fort_exit(), and ISPRESENT.
Referenced by ENTCRF90().
ENTCRF90() [2/5]
void ENTCRF90 (PAUSE , pause)
Definition at line 210 of file ftnexit.c.
References __CLEN_T, CADR, CLEN, ENTCRF90(), and str.
ENTCRF90() [3/5]
void ENTCRF90 (PAUSEA , pausea)
Definition at line 202 of file ftnexit.c.
References _f90io_pause(), CADR, CLEN, ISPRESENTC, NULL, and str.
ENTCRF90() [4/5]
void ENTCRF90 (STOP , stop)
Definition at line 157 of file ftnexit.c.
References __CLEN_T, CADR, CLEN, ENTCRF90(), and str.
ENTCRF90() [5/5]
void ENTCRF90 (STOPA , stopa)
Definition at line 149 of file ftnexit.c.
References _f90io_stop(), CADR, CLEN, ISPRESENTC, NULL, and str.
ENTF90() [1/9]
void ENTF90 (ERRORSTOP08a_char , errorstop08a_char)
ERROR STOP runtime when the stop code is scalar-default-char-expr.
Parameters
isquiet is the bool value to check the QUIET clause is specified.
str is the char-expr
Definition at line 82 of file ftnexit.c.
References __fort_exit(), _f90io_stop(), CADR, CLEN, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, NULL, and str.
ENTF90() [2/9]
void ENTF90 (ERRORSTOP08a_int , errorstop08a_int)
ERROR STOP runtime when the stop code is scalar-default-int-expr.
Parameters
stop_code is the stop code integer value.
isquiet is the bool value to check the QUIET clause is specified.
Definition at line 99 of file ftnexit.c.
References __fort_exit(), _f90io_stop(), GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, and NULL.
ENTF90() [3/9]
void ENTF90 (EXIT , exit)
Definition at line 18 of file ftnexit.c.
References __fort_exit(), and ISPRESENT.
Referenced by ENTF90().
ENTF90() [4/9]
void ENTF90 (PAUSE , pause)
Definition at line 197 of file ftnexit.c.
References __CLEN_T, CADR, CLEN, ENTF90(), and str.
ENTF90() [5/9]
void ENTF90 (PAUSEA , pausea)
Definition at line 185 of file ftnexit.c.
References __fort_barrier(), _f90io_pause(), CADR, CLEN, GET_DIST_IOPROC, GET_DIST_LCPU, ISPRESENTC, LOCAL_MODE, NULL, and str.
ENTF90() [6/9]
void ENTF90 (STOP , stop)
Definition at line 144 of file ftnexit.c.
References __CLEN_T, CADR, CLEN, ENTF90(), and str.
ENTF90() [7/9]
void ENTF90 (STOP08 , stop08)
Definition at line 129 of file ftnexit.c.
References __CLEN_T, CADR, CLEN, ENTF90(), and str.
ENTF90() [8/9]
void ENTF90 (STOP08a , stop08a)
Definition at line 112 of file ftnexit.c.
References __fort_exit(), _f90io_stop(), CADR, CLEN, GET_DIST_IOPROC, GET_DIST_LCPU, ISPRESENTC, LOCAL_MODE, NULL, and str.
ENTF90() [9/9]
void ENTF90 (STOPA , stopa)
Definition at line 134 of file ftnexit.c.
References __fort_exit(), _f90io_stop(), CADR, CLEN, GET_DIST_IOPROC, GET_DIST_LCPU, ISPRESENTC, LOCAL_MODE, NULL, and str.