flang: ftni64bitsup.c File Reference
ftni64bitsup.c File Reference
#include "enames.h"
#include "dattype.h"
#include "ftni64.h"
Macros
#define REMLOOP(a, b, c) for (a = b; a >= c; a -= c)
Functions
void shf64 (DBLINT64, int, DBLINT64)
void ushf64 (DBLUINT64, int, DBLUINT64)
__I8RET_T ftn_i_kishftc (_LONGLONG_T op, int sc, int rc)
void Ftn_kmvbits (int *src, int pos, int len, int *dest, int posd)
__I8RET_T ftn_i_kibclr (int arg1, int arg2, int bit)
__I8RET_T ftn_i_kibits (int arg1, int arg2, int bitpos, int numbits)
__I8RET_T ftn_i_kibset (int arg1, int arg2, int bit)
__I8RET_T ftn_i_bktest (int arg1, int arg2, int bit)
Macro Definition Documentation
REMLOOP
#define REMLOOP (a, b, c) for (a = b; a >= c; a -= c)
Function Documentation
ftn_i_bktest()
__I8RET_T ftn_i_bktest (int arg1, int arg2, int bit)
Definition at line 293 of file ftni64bitsup.c.
References result, shf64(), tmp, and UTL_I_I64RET.
ftn_i_kibclr()
__I8RET_T ftn_i_kibclr (int arg1, int arg2, int bit)
Definition at line 215 of file ftni64bitsup.c.
References result, tmp, ushf64(), and UTL_I_I64RET.
ftn_i_kibits()
__I8RET_T ftn_i_kibits (int arg1, int arg2, int bitpos, int numbits)
Definition at line 238 of file ftni64bitsup.c.
References numbits, result, tmp, ushf64(), and UTL_I_I64RET.
ftn_i_kibset()
__I8RET_T ftn_i_kibset (int arg1, int arg2, int bit)
Definition at line 269 of file ftni64bitsup.c.
References result, shf64(), tmp, and UTL_I_I64RET.
ftn_i_kishftc()
__I8RET_T ftn_i_kishftc (_LONGLONG_T op, int sc, int rc)
CIRCULAR LEFT SHIFT
CIRCULAR RIGHT SHIFT
Definition at line 28 of file ftni64bitsup.c.
References __ftn_32in64_, u::i, I64_LSH, I64_MSH, rc, REMLOOP, ushf64(), UTL_I_I64RET, and val.
Ftn_kmvbits()
void Ftn_kmvbits (int * src, int pos, int len, int * dest, int posd)
Definition at line 124 of file ftni64bitsup.c.
References __ftn_32in64_, dest, I64_LSH, I64_MSH, len, pos, src, tmp, and ushf64().
shf64()
void shf64 (DBLINT64 arg, int count, DBLINT64 result)
Definition at line 331 of file ftni64bitsup.c.
References arg, count, and result.
Referenced by __fort_i64toax(), addarth(), choose_multiplier(), ftn_i_bktest(), ftn_i_kibset(), reciprocal_division(), reciprocal_division_64(), and ref_pd().
ushf64()
void ushf64 (DBLUINT64 arg, int count, DBLUINT64 result)
Definition at line 378 of file ftni64bitsup.c.
References arg, count, and result.
Referenced by addarth(), ftn_i_kibclr(), ftn_i_kibits(), ftn_i_kishftc(), Ftn_kmvbits(), lg64(), reciprocal_division_64(), ref_pd(), and toi64().