flang: ftnmiscsup.c File Reference
ftnmiscsup.c File Reference
#include <time.h>
#include <math.h>
#include <stdio.h>
#include "enames.h"
Typedefs
typedef int INT
Functions
static int yr2 (int yr)
void Ftn_date (char *buf, INT buf_len)
buf receives date in the form dd-mmm-yy trucated or padded to buf_len
void Ftn_datew (char buf[9])
buffer receives date in the form dd-mmm-yy.
void Ftn_jdate (INT *i, INT *j, INT *k)
i,j,k receive integer values for month, day, and year
void Ftn_idate (short *i, short *j, short *k)
i,j,k receive short integer values for month, day, and year
float Ftn_secnds (float x)
Returns the number of seconds since midnight minus the supplied value.
double Ftn_dsecnds (double x)
double precision version of secnds.
void Ftn_time (char *buf, INT buf_len)
void Ftn_timew (char buf[8])
float Ftn_ran (unsigned *seed)
returns VMS-compatible random number sequence
double Ftn_dran (unsigned *seed)
Ftn_dran double precision version of ran):
Typedef Documentation
INT
typedef int INT
Definition at line 15 of file ftnmiscsup.c.
Function Documentation
Ftn_date()
void Ftn_date (char * buf, INT buf_len)
buf receives date in the form dd-mmm-yy trucated or padded to buf_len
Definition at line 35 of file ftnmiscsup.c.
References buf, localtime(), lt, month, time(), and yr2().
Referenced by Ftn_datew().
Ftn_datew()
void Ftn_datew (char buf[9])
buffer receives date in the form dd-mmm-yy.
Definition at line 67 of file ftnmiscsup.c.
References buf, and Ftn_date().
Ftn_dran()
double Ftn_dran (unsigned * seed)
Ftn_dran double precision version of ran):
Definition at line 246 of file ftnmiscsup.c.
References Ftn_ran().
Ftn_dsecnds()
double Ftn_dsecnds (double x)
double precision version of secnds.
Definition at line 158 of file ftnmiscsup.c.
References called, f, i, localtime(), lt, time(), and x.
Referenced by ENT3F().
Ftn_idate()
void Ftn_idate (short * i, short * j, short * k)
i,j,k receive short integer values for month, day, and year
Definition at line 105 of file ftnmiscsup.c.
References Ftn_jdate(), i, j, and k.
Ftn_jdate()
void Ftn_jdate (INT * i, INT * j, INT * k)
i,j,k receive integer values for month, day, and year
Definition at line 82 of file ftnmiscsup.c.
References i, j, k, localtime(), time(), and yr2().
Referenced by Ftn_idate().
Ftn_ran()
float Ftn_ran (unsigned * seed)
returns VMS-compatible random number sequence
Definition at line 232 of file ftnmiscsup.c.
Referenced by Ftn_dran().
Ftn_secnds()
float Ftn_secnds (float x)
Returns the number of seconds since midnight minus the supplied value.
Definition at line 127 of file ftnmiscsup.c.
References called, f, i, localtime(), lt, time(), and x.
Referenced by ENT3F().
Ftn_time()
void Ftn_time (char * buf, INT buf_len)
Definition at line 189 of file ftnmiscsup.c.
References buf, localtime(), time(), and void().
Referenced by Ftn_timew().
Ftn_timew()
void Ftn_timew (char buf[8])
Definition at line 221 of file ftnmiscsup.c.
References buf, and Ftn_time().
yr2()
static int yr2 (int yr) static
Definition at line 18 of file ftnmiscsup.c.
References y.
Referenced by Ftn_date(), and Ftn_jdate().