flang: gcdiv_128.c File Reference
gcdiv_128.c File Reference
#include "mth_intrinsics.h"
Functions
vcs1_t __gc_div_1 (vcs1_t x, vcs1_t y)
vcs2_t __gc_div_2 (vcs2_t x, vcs2_t y)
double complex __gz_div_1 (double complex x, double complex y)
vcd1_t __gz_div_1v (vcd1_t x, vcd1_t y)
Function Documentation
__gc_div_1()
vcs1_t __gc_div_1 (vcs1_t x, vcs1_t y)
Definition at line 10 of file gcdiv_128.c.
References __ZGVxN1vv__mth_i_vc4vc4(), x, and y.
__gc_div_2()
vcs2_t __gc_div_2 (vcs2_t x, vcs2_t y)
Definition at line 16 of file gcdiv_128.c.
References __ZGVxN2vv__mth_i_vc4vc4(), x, and y.
__gz_div_1()
double complex __gz_div_1 (double complex x, double complex y)
Definition at line 22 of file gcdiv_128.c.
References x, and y.
__gz_div_1v()
vcd1_t __gz_div_1v (vcd1_t x, vcd1_t y)
Definition at line 28 of file gcdiv_128.c.
References __ZGVxN1vv__mth_i_vc8vc8(), x, and y.