flang: datan2.c File Reference
generic/datan2.c File Reference
#include "mthdecls.h"
Functions
double __mth_i_datan2 (double x, double y)
Function Documentation
__mth_i_datan2()
double __mth_i_datan2 (double x, double y)
Definition at line 14 of file generic/datan2.c.
References atan2(), x, and y.
Referenced by __gd_atan2_2(), __gd_atan2_2m(), and ZMPLXFUNC_Z().