flang: gerror3f.c File Reference
gerror3f.c File Reference
#include <string.h>
#include "io3f.h"
#include "ent3f.h"
#include "utils3f.h"
#include "error.h"
Macros
#define Ftn_errmsg __fortio_errmsg
Functions
void ENT3F (GERROR, gerror)
void ENT3F (GET_IOSTAT_MSG, get_iostat_msg)
void ENT3F (GET_IOSTAT_MSG_, get_iostat_msg_)
Macro Definition Documentation
Ftn_errmsg
#define Ftn_errmsg __fortio_errmsg
Definition at line 19 of file gerror3f.c.
Function Documentation
ENT3F() [1/3]
void ENT3F (GERROR , gerror)
Definition at line 21 of file gerror3f.c.
References __fcp_cstr(), __io_errno(), CADR, CLEN, p, and str.
ENT3F() [2/3]
void ENT3F (GET_IOSTAT_MSG , get_iostat_msg)
Definition at line 30 of file gerror3f.c.
References __fcp_cstr(), CADR, CLEN, Ftn_errmsg, p, and str.
ENT3F() [3/3]
void ENT3F (GET_IOSTAT_MSG_ , get_iostat_msg_)
Definition at line 38 of file gerror3f.c.
References __fcp_cstr(), CADR, CLEN, Ftn_errmsg, p, and str.