flang: getarg.c File Reference
getarg.c File Reference
Implements the iargc, cmd_arg_cnt, get_cmd_arg, getarg and get_env_var extentions.
#include <stdlib.h>
#include <string.h>
#include "fioMacros.h"
#include "utils3f.h"
Functions
int __io_get_argc ()
char ** __io_get_argv ()
static void store_int_kind (void *, __INT_T *, int)
__INT_T ENTRY (IARGC, iargc)()
void ENTF90 (GETARGA, getarga)
void ENTF90 (GETARG, getarg)
__INT4_T ENTF90 (CMD_ARG_CNT, cmd_arg_cnt)()
__INT8_T ENTF90 (KCMD_ARG_CNT, kcmd_arg_cnt)()
void ENTF90 (GET_CMD_ARGA, get_cmd_arga)
void ENTF90 (GET_CMD_ARG, get_cmd_arg)
void ENTF90 (GET_CMDA, get_cmda)
void ENTF90 (GET_CMD, get_cmd)
void ENTF90 (GET_ENV_VARA, get_env_vara)
void ENTF90 (GET_ENV_VAR, get_env_var)
Detailed Description
Implements the iargc, cmd_arg_cnt, get_cmd_arg, getarg and get_env_var extentions.
Definition in file getarg.c.
Function Documentation
__io_get_argc()
int __io_get_argc ()
Definition at line 30 of file ioargs.c.
References __argc_save.
Referenced by ENTF90(), and ENTRY().
__io_get_argv()
char ** __io_get_argv ()
Definition at line 14 of file ioargs.c.
References __argv_save.
Referenced by ENTF90().
ENTF90() [1/10]
__INT4_T ENTF90 (CMD_ARG_CNT , cmd_arg_cnt)
Definition at line 61 of file getarg.c.
References __io_get_argc(), and n.
ENTF90() [2/10]
void ENTF90 (GET_CMD , get_cmd)
Definition at line 201 of file getarg.c.
References __CLEN_T, CADR, CLEN, ENTF90(), and length().
ENTF90() [3/10]
void ENTF90 (GET_CMD_ARG , get_cmd_arg)
Definition at line 128 of file getarg.c.
References __CLEN_T, CADR, CLEN, ENTF90(), length(), and value().
ENTF90() [4/10]
void ENTF90 (GET_CMD_ARGA , get_cmd_arga)
Definition at line 77 of file getarg.c.
References __CLEN_T, __fort_varying_int(), __io_get_argc(), __io_get_argv(), CADR, CLEN, i, I8, ISPRESENT, ISPRESENTC, len, length(), n, p, q, stat, store_int_kind(), strlen(), and value().
ENTF90() [5/10]
void ENTF90 (GET_CMDA , get_cmda)
Definition at line 137 of file getarg.c.
References __CLEN_T, __io_get_argc(), __io_get_argv(), CADR, CLEN, i, ISPRESENT, ISPRESENTC, len, length(), n, p, q, stat, and store_int_kind().
ENTF90() [6/10]
void ENTF90 (GET_ENV_VAR , get_env_var)
Definition at line 267 of file getarg.c.
References __CLEN_T, CADR, CLEN, ENTF90(), length(), name, and value().
ENTF90() [7/10]
void ENTF90 (GET_ENV_VARA , get_env_vara)
Definition at line 209 of file getarg.c.
References __CLEN_T, __cstr_free(), __fort_varying_log(), __fstr2cstr(), CADR, CLEN, getenv(), i, I8, ISPRESENT, ISPRESENTC, len, length(), name, p, q, stat, store_int_kind(), and value().
ENTF90() [8/10]
void ENTF90 (GETARG , getarg)
Definition at line 55 of file getarg.c.
References __CLEN_T, arg, CADR, CLEN, ENTF90(), and n.
ENTF90() [9/10]
void ENTF90 (GETARGA , getarga)
Definition at line 29 of file getarg.c.
References __fort_varying_int(), __io_get_argc(), __io_get_argv(), arg, CADR, CLEN, i, I8, len, n, and p.
Referenced by ENTF90().
ENTF90() [10/10]
__INT8_T ENTF90 (KCMD_ARG_CNT , kcmd_arg_cnt)
Definition at line 71 of file getarg.c.
References ENTF90().
ENTRY()
__INT_T ENTRY (IARGC , iargc)
Definition at line 26 of file getarg.c.
References __io_get_argc().
store_int_kind()
static void store_int_kind (void * b, __INT_T * int_kind, int v) static
Definition at line 280 of file getarg.c.
References b.
Referenced by ENTF90().