flang: getarg3f.c File Reference
getarg3f.c File Reference
#include "ent3f.h"
Functions
int __io_get_argc ()
char ** __io_get_argv ()
void ENT3F (GETARG, getarg)
int ENT3F (IARGC, iargc)
void ftn_arg_init ()
Function Documentation
__io_get_argc()
int __io_get_argc ()
Definition at line 30 of file ioargs.c.
Referenced by ENT3F().
__io_get_argv()
char ** __io_get_argv ()
Definition at line 14 of file ioargs.c.
Referenced by ENT3F().
ENT3F() [1/2]
void ENT3F (GETARG , getarg)
Definition at line 20 of file getarg3f.c.
References __io_get_argc(), __io_get_argv(), arg, CADR, CLEN, i, len, n, p, and q.
ENT3F() [2/2]
int ENT3F (IARGC , iargc)
Definition at line 43 of file getarg3f.c.
References __io_get_argc().
ftn_arg_init()
void ftn_arg_init ()
Definition at line 52 of file getarg3f.c.