flang: getenvqq3f.c File Reference
getenvqq3f.c File Reference
#include <string.h>
#include "ent3f.h"
#include "utils3f.h"
Functions
int ENT3F (GETENVQQ, getenvqq)
Function Documentation
ENT3F()
int ENT3F (GETENVQQ , getenvqq)
Definition at line 16 of file getenvqq3f.c.
References __cstr_free(), __fcp_cstr(), __fstr2cstr(), CADR, CLEN, getenv(), i, NULL, p, q, and strlen().