flang: getlog3f.c File Reference
getlog3f.c File Reference
#include "ent3f.h"
#include "utils3f.h"
Functions
char * getlogin ()
void ENT3F (GETLOG, getlog)
Function Documentation
ENT3F()
void ENT3F (GETLOG , getlog)
Definition at line 19 of file getlog3f.c.
References __fcp_cstr(), CADR, CLEN, getlogin(), and p.
getlogin()
char * getlogin ()
Referenced by ENT3F().