flang: Positional and keyword arguments
Positional and keyword arguments
Functions
static int nz_digit_str (char *)
LOGICAL get_kwd_args (ITEM *list, int cnt, const char *kwdarg)
Extract the arguments from the semantic list into sem.argpos[] in positional order.
static LOGICAL get_keyword_args (ITEM *list, int cnt, const char *kwdarg, int pod, int pass_pos)
Similar to get_kwd_args but can also specify a pass-object dummy argument.
LOGICAL evl_kwd_args (ITEM *list, int cnt, const char *kwdarg)
Call get_kwd_args and evaluate each argument.
LOGICAL sum_scatter_args (ITEM *list, int cnt)
Variables
static LOGICAL user_subr = FALSE
Detailed Description
Support for extracting positional or keyword arguments for an intrinsic. For each intrinsic, the symbol table utility has created a string which defines the arguments and their positions in the argument list and keywords.
Optional arguments are indicating by prefixing their keywords with '*'.
Function Documentation
evl_kwd_args()
LOGICAL evl_kwd_args (ITEM * list, int cnt, const char * kwdarg)
Call get_kwd_args and evaluate each argument.
Parameters
list list of arguments
cnt maximum number of arguments allowed for intrinsic
kwdarg string defining position and keywords of arguments
Definition at line 1789 of file semfunc2.c.
References ARG_AST, ARG_STK, cnt, FALSE, get_kwd_args(), i, list, mk_id(), mkarg(), mkexpr(), S_IDENT, S_SCONST, sptr, SST_ASTG, SST_ASTP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_LSYMP, SST_SYMG, TRUE, and void().
Referenced by ref_pd(), and ref_pd_subr().
get_keyword_args()
static LOGICAL get_keyword_args (ITEM * list, int cnt, const char * kwdarg, int pod, int pass_pos) static
Similar to get_kwd_args but can also specify a pass-object dummy argument.
Parameters
list list of arguments
cnt maximum number of arguments allowed for intrinsic
kwdarg string defining position and keywords of arguments
pod if set indicates there is a passed-object dummy argument
pass_pos index of the passed-object dummy argument when pod is set
Definition at line 1561 of file semfunc2.c.
References ARG_AST, ARG_STK, SEM::argpos, cnt, CNULL, error(), FALSE, gbl, getitem(), i, SCN::id, interr(), ITEM_END, list, SCN::name, NULL, nz_digit_str(), pass_object_dummy, pass_position, pos, S_KEYWORD, scn, sem, SST_ASTG, SST_CVALG, SST_E3G, SST_IDG, strlen(), TRUE, and user_subr.
Referenced by chk_arguments(), and get_kwd_args().
get_kwd_args()
LOGICAL get_kwd_args (ITEM * list, int cnt, const char * kwdarg)
Extract the arguments from the semantic list into sem.argpos[] in positional order.
Parameters
list list of arguments
cnt maximum number of arguments allowed for intrinsic
kwdarg string defining position and keywords of arguments
Definition at line 1547 of file semfunc2.c.
References cnt, get_keyword_args(), and list.
Referenced by chk_arguments(), evl_kwd_args(), ref_intrin(), ref_intrin_subr(), ref_pd(), and ref_pd_subr().
nz_digit_str()
static int nz_digit_str (char * s) static
Definition at line 1757 of file semfunc2.c.
References s, and val.
Referenced by get_keyword_args(), and sum_scatter_args().
sum_scatter_args()
LOGICAL sum_scatter_args (ITEM * list, int cnt)
Parameters
list list of arguments
cnt maximum number of arguments allowed for intrinsic
Arguments are: array, base, indx1, ..., indxn, mask
where n = rank of base, mask is optional
Don't use get_kwd_args() since it is not designed to handle an optional argument after a variable number of arguments. Note that cnt is the actual number of arguments; get_kwd_args() & evl_kwd_args() are passed the the maximum number of arguments.
If the arguments are correct, the output (ARG_STK) will be in the order:
0      - array
1      - base
2      - mask
3      - indx1
...
3+n-1  -  indxn
Definition at line 1839 of file semfunc2.c.
References ARG_AST, ARG_STK, SEM::argpos, cnt, CNULL, error(), FALSE, gbl, getitem(), i, SCN::id, ITEM_END, list, mkexpr(), SCN::name, NULL, nz_digit_str(), pos, rank, rank_of_ast(), S_KEYWORD, scn, sem, SST_ASTG, SST_CVALG, SST_E3G, SST_IDG, str, strlen(), TRUE, and void().
Variable Documentation
user_subr
LOGICAL user_subr = FALSE static
TRUE if invoking a user subprogram
Definition at line 1537 of file semfunc2.c.
Referenced by chk_arguments(), and get_keyword_args().