flang: gsatan4.c File Reference
gsatan4.c File Reference
#include "mth_intrinsics.h"
Functions
vrs4_t __gs_atan_4 (vrs4_t x)
vrs4_t __gs_atan_4m (vrs4_t x, vis4_t mask)
vcs1_t __gc_atan_1 (vcs1_t x)
vcs2_t __gc_atan_2 (vcs2_t x)
Function Documentation
__gc_atan_1()
vcs1_t __gc_atan_1 (vcs1_t x)
Definition at line 23 of file gsatan4.c.
References __ZGVxN1v__mth_i_vc4(), and x.
__gc_atan_2()
vcs2_t __gc_atan_2 (vcs2_t x)
Definition at line 29 of file gsatan4.c.
References __ZGVxN2v__mth_i_vc4(), and x.
__gs_atan_4()
vrs4_t __gs_atan_4 (vrs4_t x)
Definition at line 11 of file gsatan4.c.
References __mth_i_atan(), __ZGVxN4v__mth_i_vr4(), and x.
__gs_atan_4m()
vrs4_t __gs_atan_4m (vrs4_t x, vis4_t mask)
Definition at line 17 of file gsatan4.c.
References __mth_i_atan(), __ZGVxM4v__mth_i_vr4(), and x.