flang: gsatan24.c File Reference
gsatan24.c File Reference
#include "mth_intrinsics.h"
Functions
vrs4_t __gs_atan2_4 (vrs4_t x, vrs4_t y)
vrs4_t __gs_atan2_4m (vrs4_t x, vrs4_t y, vis4_t mask)
Function Documentation
__gs_atan2_4()
vrs4_t __gs_atan2_4 (vrs4_t x, vrs4_t y)
Definition at line 11 of file gsatan24.c.
References __mth_i_atan2(), __ZGVxN4vv__mth_i_vr4vr4(), x, and y.
__gs_atan2_4m()
vrs4_t __gs_atan2_4m (vrs4_t x, vrs4_t y, vis4_t mask)
Definition at line 17 of file gsatan24.c.
References __mth_i_atan2(), __ZGVxM4vv__mth_i_vr4vr4(), x, and y.