flang: gsincos.cpp File Reference
gsincos.cpp File Reference
#include "mth_intrinsics.h"
Macros
#define PREC d
#define FLOAT double
#define CONCAT4_(a, b, c, d) a##b##c##d
#define CONCAT4(a, b, c, d) CONCAT4_(a,b,c,d)
#define CONCAT5_(a, b, c, d, e) a##b##c##d##e
#define CONCAT5(a, b, c, d, e) CONCAT5_(a,b,c,d,e)
#define EXPAND(a) a
#define VFLOAT CONCAT4(vr,PREC,VLEN,_t)
#define VINT CONCAT4(vi,PREC,VLEN,_t)
#define VFLOATRETURN CONCAT4(__mth_return2,VFLOAT,,)
#define GENERICNAME CONCAT4(__g,PREC,_sincos_,VLEN)
#define GENERICNAMEMASK CONCAT5(__g,PREC,_sincos_,VLEN,m)
Functions
void sincos (double, double *, double *) throw ()
VFLOAT VFLOATRETURN (VFLOAT, VFLOAT)
VFLOAT GENERICNAME (VFLOAT x)
VFLOAT GENERICNAMEMASK (VFLOAT x, VINT mask)
Macro Definition Documentation
CONCAT4
#define CONCAT4 (a, b, c, d) CONCAT4_(a,b,c,d)
Definition at line 30 of file gsincos.cpp.
CONCAT4_
#define CONCAT4_ (a, b, c, d) a##b##c##d
Definition at line 29 of file gsincos.cpp.
CONCAT5
#define CONCAT5 (a, b, c, d, e) CONCAT5_(a,b,c,d,e)
Definition at line 32 of file gsincos.cpp.
CONCAT5_
#define CONCAT5_ (a, b, c, d, e) a##b##c##d##e
Definition at line 31 of file gsincos.cpp.
EXPAND
#define EXPAND (a) a
Definition at line 33 of file gsincos.cpp.
FLOAT
#define FLOAT double
Definition at line 26 of file gsincos.cpp.
GENERICNAME
#define GENERICNAME CONCAT4(__g,PREC,_sincos_,VLEN)
Definition at line 46 of file gsincos.cpp.
GENERICNAMEMASK
#define GENERICNAMEMASK CONCAT5(__g,PREC,_sincos_,VLEN,m)
Definition at line 47 of file gsincos.cpp.
PREC
#define PREC d
Definition at line 25 of file gsincos.cpp.
VFLOAT
#define VFLOAT CONCAT4(vr,PREC,VLEN,_t)
Definition at line 34 of file gsincos.cpp.
VFLOATRETURN
#define VFLOATRETURN CONCAT4(__mth_return2,VFLOAT,,)
Definition at line 38 of file gsincos.cpp.
VINT
#define VINT CONCAT4(vi,PREC,VLEN,_t)
Definition at line 35 of file gsincos.cpp.
Function Documentation
GENERICNAME()
VFLOAT GENERICNAME (VFLOAT x)
Definition at line 75 of file gsincos.cpp.
References FLOAT, i, SINCOS(), ts, VEC_LOAD, VFLOATRETURN, and x.
GENERICNAMEMASK()
VFLOAT GENERICNAMEMASK (VFLOAT x, VINT mask)
Definition at line 88 of file gsincos.cpp.
References FLOAT, i, SINCOS(), ts, VEC_LOAD, VFLOATRETURN, and x.
sincos()
void sincos (double , double * , double *) throw ()
Referenced by gen_llvm_sincos_builtin().
VFLOATRETURN()
VFLOAT VFLOATRETURN (VFLOAT , VFLOAT)