flang: hand.c File Reference
hand.c File Reference
#include <sys/signal.h>
#include "stdioInterf.h"
#include "fioMacros.h"
Classes
struct sigs
Functions
void __fort_psignal (int lcpu, int s)
static void sighand (int s)
void __fort_sethand ()
Variables
static struct sigs sigs []
Function Documentation
__fort_psignal()
void __fort_psignal (int lcpu, int s)
Definition at line 61 of file hand.c.
References buf, n, NULL, s, sigs::sig, str, strlen(), and write.
Referenced by sighand().
__fort_sethand()
void __fort_sethand (void)
Definition at line 96 of file hand.c.
References __fort_getopt(), __fort_strtol(), n, NULL, p, q, sigs::sig, and sighand().
Referenced by __fort_begpar().
sighand()
static void sighand (int s) static
Definition at line 81 of file hand.c.
References __fort_abort(), __fort_myprocnum(), __fort_psignal(), NULL, and s.
Referenced by __fort_sethand().
Variable Documentation
sigs
struct sigs sigs[] static
Definition at line 24 of file hand.c.