flang: heapinit.c File Reference
heapinit.c File Reference
#include <signal.h>
#include "stdioInterf.h"
#include "fioMacros.h"
Functions
static void sighand (int s)
void __fort_heapinit (char *beg, char *end, int val)
Function Documentation
__fort_heapinit()
void __fort_heapinit (char * beg, char * end, int val)
Definition at line 26 of file heapinit.c.
References end, pi, sighand(), val, and void().
sighand()
static void sighand (int s) static
Definition at line 14 of file heapinit.c.
References __fort_abort(), __fort_myprocnum(), __io_stderr(), and NULL.
Referenced by __fort_heapinit().