flang: helperavx512f.h File Reference
helperavx512f.h File Reference
#include <x86intrin.h>
#include <stdint.h>
#include "misc.h"
Macros
#define FCN_AVX512(a) a##_avx512
#define _STRINGIFY(_n) #_n
#define STRINGIFY(_n) _STRINGIFY(_n)
#define ENABLE_DP
#define LOG2VECTLENDP 3
#define VECTLENDP (1 << LOG2VECTLENDP)
#define ENABLE_FMA_DP
#define ENABLE_SP
#define LOG2VECTLENSP (LOG2VECTLENDP+1)
#define VECTLENSP (1 << LOG2VECTLENSP)
#define ENABLE_FMA_SP
#define PNMASK ((vdouble) { +0.0, -0.0, +0.0, -0.0, +0.0, -0.0, +0.0, -0.0 })
#define NPMASK ((vdouble) { -0.0, +0.0, -0.0, +0.0, -0.0, +0.0, -0.0, +0.0 })
#define PNMASKf ((vfloat) { +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f })
#define NPMASKf ((vfloat) { -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f })
Typedefs
typedef __m512i vmask
typedef __mmask16 vopmask
typedef __m512d vdouble
typedef __m256i vint
typedef __m512 vfloat
typedef __m512i vint2
Functions
void Sleef_x86CpuID (int32_t out[4], uint32_t eax, uint32_t ecx)
static int cpuSupportsAVX512F ()
static INLINE void vprefetch_v_p (const void *ptr)
static INLINE int vtestallones_i_vo64 (vopmask g)
static INLINE int vtestallones_i_vo32 (vopmask g)
static vint2 vloadu_vi2_p (int32_t *p)
static void vstoreu_v_p_vi2 (int32_t *p, vint2 v)
static vint vloadu_vi_p (int32_t *p)
static void vstoreu_v_p_vi (int32_t *p, vint v)
static INLINE vmask vand_vm_vm_vm (vmask x, vmask y)
static INLINE vmask vandnot_vm_vm_vm (vmask x, vmask y)
static INLINE vmask vor_vm_vm_vm (vmask x, vmask y)
static INLINE vmask vxor_vm_vm_vm (vmask x, vmask y)
static INLINE vopmask vand_vo_vo_vo (vopmask x, vopmask y)
static INLINE vopmask vandnot_vo_vo_vo (vopmask x, vopmask y)
static INLINE vopmask vor_vo_vo_vo (vopmask x, vopmask y)
static INLINE vopmask vxor_vo_vo_vo (vopmask x, vopmask y)
static INLINE vmask vand_vm_vo64_vm (vopmask o, vmask m)
static INLINE vmask vandnot_vm_vo64_vm (vopmask o, vmask m)
static INLINE vmask vor_vm_vo64_vm (vopmask o, vmask m)
static INLINE vmask vand_vm_vo32_vm (vopmask o, vmask m)
static INLINE vmask vandnot_vm_vo32_vm (vopmask o, vmask m)
static INLINE vmask vor_vm_vo32_vm (vopmask o, vmask m)
static INLINE vopmask vcast_vo32_vo64 (vopmask o)
static INLINE vopmask vcast_vo64_vo32 (vopmask o)
static INLINE vint vrint_vi_vd (vdouble vd)
static INLINE vint vtruncate_vi_vd (vdouble vd)
static INLINE vdouble vcast_vd_vi (vint vi)
static INLINE vint vcast_vi_i (int i)
static INLINE vdouble vtruncate_vd_vd (vdouble vd)
static INLINE vdouble vrint_vd_vd (vdouble vd)
static INLINE vint2 vcastu_vi2_vi (vint vi)
static INLINE vint vcastu_vi_vi2 (vint2 vi)
static INLINE vmask vcast_vm_i_i (int i0, int i1)
static INLINE vopmask veq64_vo_vm_vm (vmask x, vmask y)
static INLINE vdouble vcast_vd_d (double d)
static INLINE vmask vreinterpret_vm_vd (vdouble vd)
static INLINE vdouble vreinterpret_vd_vm (vmask vm)
static INLINE vint2 vreinterpret_vi2_vd (vdouble vd)
static INLINE vdouble vreinterpret_vd_vi2 (vint2 vi)
static INLINE vdouble vadd_vd_vd_vd (vdouble x, vdouble y)
static INLINE vdouble vsub_vd_vd_vd (vdouble x, vdouble y)
static INLINE vdouble vmul_vd_vd_vd (vdouble x, vdouble y)
static INLINE vdouble vdiv_vd_vd_vd (vdouble x, vdouble y)
static INLINE vdouble vrec_vd_vd (vdouble x)
static INLINE vdouble vsqrt_vd_vd (vdouble x)
static INLINE vdouble vabs_vd_vd (vdouble d)
static INLINE vdouble vneg_vd_vd (vdouble d)
static INLINE vdouble vmla_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vdouble vmlapn_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vdouble vmlanp_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vdouble vmax_vd_vd_vd (vdouble x, vdouble y)
static INLINE vdouble vmin_vd_vd_vd (vdouble x, vdouble y)
static INLINE vdouble vfma_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vdouble vfmapp_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vdouble vfmapn_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vdouble vfmanp_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vdouble vfmann_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vopmask veq_vo_vd_vd (vdouble x, vdouble y)
static INLINE vopmask vneq_vo_vd_vd (vdouble x, vdouble y)
static INLINE vopmask vlt_vo_vd_vd (vdouble x, vdouble y)
static INLINE vopmask vle_vo_vd_vd (vdouble x, vdouble y)
static INLINE vopmask vnlt_vo_vd_vd (vdouble x, vdouble y)
static INLINE vopmask vgt_vo_vd_vd (vdouble x, vdouble y)
static INLINE vopmask vge_vo_vd_vd (vdouble x, vdouble y)
static INLINE vint vadd_vi_vi_vi (vint x, vint y)
static INLINE vint vadd64_vi_vi_vi (vint x, vint y)
static INLINE vint vsub_vi_vi_vi (vint x, vint y)
static INLINE vint vsub64_vi_vi_vi (vint x, vint y)
static INLINE vint vneg_vi_vi (vint e)
static INLINE vint vand_vi_vi_vi (vint x, vint y)
static INLINE vint vandnot_vi_vi_vi (vint x, vint y)
static INLINE vint vandnot_vi_vo_vi (vopmask o, vint y)
static INLINE vint vand_vi_vo_vi (vopmask o, vint y)
static INLINE vint vor_vi_vi_vi (vint x, vint y)
static INLINE vint vxor_vi_vi_vi (vint x, vint y)
static INLINE vint vsll_vi_vi_i (vint x, int c)
static INLINE vint vsrl_vi_vi_i (vint x, int c)
static INLINE vint vsra_vi_vi_i (vint x, int c)
static INLINE vint veq_vi_vi_vi (vint x, vint y)
static INLINE vint vgt_vi_vi_vi (vint x, vint y)
static INLINE vopmask veq_vo_vi_vi (vint x, vint y)
static INLINE vopmask vgt_vo_vi_vi (vint x, vint y)
static INLINE vdouble vsel_vd_vo_vd_vd (vopmask mask, vdouble x, vdouble y)
static INLINE CONST vdouble vsel_vd_vo_d_d (vopmask o, double v1, double v0)
static INLINE vdouble vsel_vd_vo_vo_vo_d_d_d_d (vopmask o0, vopmask o1, vopmask o2, double d0, double d1, double d2, double d3)
static INLINE vdouble vsel_vd_vo_vo_d_d_d (vopmask o0, vopmask o1, double d0, double d1, double d2)
static INLINE vopmask visinf_vo_vd (vdouble d)
static INLINE vopmask vispinf_vo_vd (vdouble d)
static INLINE vopmask visminf_vo_vd (vdouble d)
static INLINE vopmask visnan_vo_vd (vdouble d)
static INLINE vint vilogbk_vi_vd (vdouble d)
static INLINE vint vilogb2k_vi_vd (vdouble d)
static INLINE vdouble vgetexp_vd_vd (vdouble d)
static INLINE vfloat vgetexp_vf_vf (vfloat d)
static INLINE vdouble vgetmant_vd_vd (vdouble d)
static INLINE vfloat vgetmant_vf_vf (vfloat d)
static INLINE vdouble vfixup_vd_vd_vd_vi2_i (vdouble a, vdouble b, vint2 c, int imm)
static INLINE vfloat vfixup_vf_vf_vf_vi2_i (vfloat a, vfloat b, vint2 c, int imm)
static INLINE vdouble vset_vd_d_d (const double hi, const double lo)
static INLINE vdouble vload_vd_p (const double *ptr)
static INLINE vdouble vloadu_vd_p (const double *ptr)
static INLINE void vstore_v_p_vd (double *ptr, vdouble v)
static INLINE void vstoreu_v_p_vd (double *ptr, vdouble v)
static INLINE vint vsel_vi_vo_vi_vi (vopmask m, vint x, vint y)
static INLINE vint2 vcast_vi2_vm (vmask vm)
static INLINE vmask vcast_vm_vi2 (vint2 vi)
static INLINE vfloat vcast_vf_vi2 (vint2 vi)
static INLINE vfloat vcast_vf_f (float f)
static INLINE vint2 vcast_vi2_i (int i)
static INLINE vint2 vrint_vi2_vf (vfloat vf)
static INLINE vint2 vtruncate_vi2_vf (vfloat vf)
static INLINE vfloat vtruncate_vf_vf (vfloat vd)
static INLINE vfloat vrint_vf_vf (vfloat vd)
static INLINE vmask vreinterpret_vm_vf (vfloat vf)
static INLINE vfloat vreinterpret_vf_vm (vmask vm)
static INLINE vfloat vreinterpret_vf_vi2 (vint2 vi)
static INLINE vint2 vreinterpret_vi2_vf (vfloat vf)
static INLINE vfloat vadd_vf_vf_vf (vfloat x, vfloat y)
static INLINE vfloat vsub_vf_vf_vf (vfloat x, vfloat y)
static INLINE vfloat vmul_vf_vf_vf (vfloat x, vfloat y)
static INLINE vfloat vdiv_vf_vf_vf (vfloat x, vfloat y)
static INLINE vfloat vrec_vf_vf (vfloat x)
static INLINE vfloat vsqrt_vf_vf (vfloat x)
static INLINE vfloat vabs_vf_vf (vfloat f)
static INLINE vfloat vneg_vf_vf (vfloat d)
static INLINE vfloat vmla_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vfloat vmlapn_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vfloat vmlanp_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vfloat vmax_vf_vf_vf (vfloat x, vfloat y)
static INLINE vfloat vmin_vf_vf_vf (vfloat x, vfloat y)
static INLINE vfloat vfma_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vfloat vfmapp_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vfloat vfmapn_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vfloat vfmanp_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vfloat vfmann_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vopmask veq_vo_vf_vf (vfloat x, vfloat y)
static INLINE vopmask vneq_vo_vf_vf (vfloat x, vfloat y)
static INLINE vopmask vlt_vo_vf_vf (vfloat x, vfloat y)
static INLINE vopmask vle_vo_vf_vf (vfloat x, vfloat y)
static INLINE vopmask vnlt_vo_vf_vf (vfloat x, vfloat y)
static INLINE vopmask vgt_vo_vf_vf (vfloat x, vfloat y)
static INLINE vopmask vge_vo_vf_vf (vfloat x, vfloat y)
static INLINE vint2 vadd_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vsub_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vneg_vi2_vi2 (vint2 e)
static INLINE vint2 vand_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vandnot_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vor_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vxor_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vand_vi2_vo_vi2 (vopmask o, vint2 m)
static INLINE vint2 vandnot_vi2_vo_vi2 (vopmask o, vint2 m)
static INLINE vint2 vsll_vi2_vi2_i (vint2 x, int c)
static INLINE vint2 vsrl_vi2_vi2_i (vint2 x, int c)
static INLINE vint2 vsra_vi2_vi2_i (vint2 x, int c)
static INLINE vopmask veq_vo_vi2_vi2 (vint2 x, vint2 y)
static INLINE vopmask vgt_vo_vi2_vi2 (vint2 x, vint2 y)
static INLINE vopmask vgt64_vo_vm_vm (vmask x, vmask y)
static INLINE vopmask veq64_vo_vi2_vi2 (vint2 x, vint2 y)
static INLINE vopmask vgt64_vo_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 veq_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vgt_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vsel_vi2_vo_vi2_vi2 (vopmask m, vint2 x, vint2 y)
static INLINE vfloat vsel_vf_vo_vf_vf (vopmask m, vfloat x, vfloat y)
static INLINE CONST vfloat vsel_vf_vo_f_f (vopmask o, float v1, float v0)
static INLINE vfloat vsel_vf_vo_vo_f_f_f (vopmask o0, vopmask o1, float d0, float d1, float d2)
static INLINE vfloat vsel_vf_vo_vo_vo_f_f_f_f (vopmask o0, vopmask o1, vopmask o2, float d0, float d1, float d2, float d3)
static INLINE vopmask visinf_vo_vf (vfloat d)
static INLINE vopmask vispinf_vo_vf (vfloat d)
static INLINE vopmask visminf_vo_vf (vfloat d)
static INLINE vopmask visnan_vo_vf (vfloat d)
static INLINE vint2 vilogbk_vi2_vf (vfloat d)
static INLINE vfloat vload_vf_p (const float *ptr)
static INLINE vfloat vloadu_vf_p (const float *ptr)
static INLINE void vstore_v_p_vf (float *ptr, vfloat v)
static INLINE void vstoreu_v_p_vf (float *ptr, vfloat v)
static INLINE vdouble vposneg_vd_vd (vdouble d)
static INLINE vdouble vnegpos_vd_vd (vdouble d)
static INLINE vfloat vposneg_vf_vf (vfloat d)
static INLINE vfloat vnegpos_vf_vf (vfloat d)
static INLINE vdouble vsubadd_vd_vd_vd (vdouble x, vdouble y)
static INLINE vfloat vsubadd_vf_vf_vf (vfloat x, vfloat y)
static INLINE vdouble vmlsubadd_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vfloat vmlsubadd_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vdouble vrev21_vd_vd (vdouble vd)
static INLINE vdouble vreva2_vd_vd (vdouble vd)
static INLINE void vstream_v_p_vd (double *ptr, vdouble v)
static INLINE void vscatter2_v_p_i_i_vd (double *ptr, int offset, int step, vdouble v)
static INLINE void vsscatter2_v_p_i_i_vd (double *ptr, int offset, int step, vdouble v)
static INLINE vfloat vrev21_vf_vf (vfloat vf)
static INLINE vfloat vreva2_vf_vf (vfloat vf)
static INLINE vdouble vmoveldup_vd_vd (vdouble d0)
static INLINE vdouble vmovehdup_vd_vd (vdouble d0)
static INLINE vfloat vmoveldup_vf_vf (vfloat d0)
static INLINE vfloat vmovehdup_vf_vf (vfloat d0)
static INLINE void vstream_v_p_vf (float *ptr, vfloat v)
static INLINE void vscatter2_v_p_i_i_vf (float *ptr, int offset, int step, vfloat v)
static INLINE void vsscatter2_v_p_i_i_vf (float *ptr, int offset, int step, vfloat v)
static INLINE int vtestz_i_vo_vo (vopmask x, vopmask y)
static INLINE int vtestz_i_vo (vopmask x)
static INLINE vint2 vsll64_vi2_vi2_i (vint2 x, int c)
static INLINE vint2 vsrl64_vi2_vi2_i (vint2 x, int c)
static INLINE vint2 vmulu_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vadd64_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vsub64_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint vhi64_vi_vi2 (vint2 x)
Macro Definition Documentation
_STRINGIFY
#define _STRINGIFY (_n) #_n
Definition at line 27 of file helperavx512f.h.
ENABLE_DP
#define ENABLE_DP
Definition at line 30 of file helperavx512f.h.
ENABLE_FMA_DP
#define ENABLE_FMA_DP
Definition at line 33 of file helperavx512f.h.
ENABLE_FMA_SP
#define ENABLE_FMA_SP
Definition at line 38 of file helperavx512f.h.
ENABLE_SP
#define ENABLE_SP
Definition at line 35 of file helperavx512f.h.
FCN_AVX512
#define FCN_AVX512 (a) a##_avx512
Definition at line 23 of file helperavx512f.h.
LOG2VECTLENDP
#define LOG2VECTLENDP 3
Definition at line 31 of file helperavx512f.h.
LOG2VECTLENSP
#define LOG2VECTLENSP (LOG2VECTLENDP+1)
Definition at line 36 of file helperavx512f.h.
NPMASK
#define NPMASK ((vdouble) { -0.0, +0.0, -0.0, +0.0, -0.0, +0.0, -0.0, +0.0 })
Definition at line 427 of file helperavx512f.h.
NPMASKf
#define NPMASKf ((vfloat) { -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f })
Definition at line 429 of file helperavx512f.h.
PNMASK
#define PNMASK ((vdouble) { +0.0, -0.0, +0.0, -0.0, +0.0, -0.0, +0.0, -0.0 })
Definition at line 426 of file helperavx512f.h.
PNMASKf
#define PNMASKf ((vfloat) { +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f })
Definition at line 428 of file helperavx512f.h.
STRINGIFY
#define STRINGIFY (_n) _STRINGIFY(_n)
Definition at line 28 of file helperavx512f.h.
VECTLENDP
#define VECTLENDP (1 << LOG2VECTLENDP)
Definition at line 32 of file helperavx512f.h.
VECTLENSP
#define VECTLENSP (1 << LOG2VECTLENSP)
Definition at line 37 of file helperavx512f.h.
Typedef Documentation
vdouble
typedef __m512d vdouble
Definition at line 52 of file helperavx512f.h.
vfloat
typedef __m512 vfloat
Definition at line 55 of file helperavx512f.h.
vint
typedef __m256i vint
Definition at line 53 of file helperavx512f.h.
vint2
typedef __m512i vint2
Definition at line 56 of file helperavx512f.h.
vmask
typedef __m512i vmask
Definition at line 49 of file helperavx512f.h.
vopmask
typedef __mmask16 vopmask
Definition at line 50 of file helperavx512f.h.
Function Documentation
cpuSupportsAVX512F()
static int cpuSupportsAVX512F () static
Definition at line 64 of file helperavx512f.h.
References reg, and Sleef_x86CpuID().
Sleef_x86CpuID()
void Sleef_x86CpuID (int32_t out[4], uint32_t eax, uint32_t ecx)
Referenced by cpuSupportsAVX512F().
vabs_vd_vd()
static INLINE vdouble vabs_vd_vd (vdouble d) static
Definition at line 161 of file helperavx512f.h.
References d.
Referenced by visinf_vo_vd().
vabs_vf_vf()
static INLINE vfloat vabs_vf_vf (vfloat f) static
Definition at line 322 of file helperavx512f.h.
References f, vandnot_vm_vm_vm(), and vcast_vf_f().
Referenced by visinf_vo_vf().
vadd64_vi2_vi2_vi2()
static INLINE vint2 vadd64_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 504 of file helperavx512f.h.
References x, and y.
vadd64_vi_vi_vi()
static INLINE vint vadd64_vi_vi_vi (vint x, vint y) static
Definition at line 186 of file helperavx512f.h.
References x, and y.
vadd_vd_vd_vd()
static INLINE vdouble vadd_vd_vd_vd (vdouble x, vdouble y) static
Definition at line 155 of file helperavx512f.h.
References x, and y.
Referenced by vsubadd_vd_vd_vd().
vadd_vf_vf_vf()
static INLINE vfloat vadd_vf_vf_vf (vfloat x, vfloat y) static
Definition at line 316 of file helperavx512f.h.
References x, and y.
Referenced by vsubadd_vf_vf_vf().
vadd_vi2_vi2_vi2()
static INLINE vint2 vadd_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 344 of file helperavx512f.h.
References x, and y.
vadd_vi_vi_vi()
static INLINE vint vadd_vi_vi_vi (vint x, vint y) static
Definition at line 185 of file helperavx512f.h.
References x, and y.
vand_vi2_vi2_vi2()
static INLINE vint2 vand_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 347 of file helperavx512f.h.
References x, and y.
vand_vi2_vo_vi2()
static INLINE vint2 vand_vi2_vo_vi2 (vopmask o, vint2 m) static
Definition at line 352 of file helperavx512f.h.
References m.
vand_vi_vi_vi()
static INLINE vint vand_vi_vi_vi (vint x, vint y) static
Definition at line 191 of file helperavx512f.h.
References x, and y.
vand_vi_vo_vi()
static INLINE vint vand_vi_vo_vi (vopmask o, vint y) static
Definition at line 197 of file helperavx512f.h.
References y.
vand_vm_vm_vm()
static INLINE vmask vand_vm_vm_vm (vmask x, vmask y) static
Definition at line 98 of file helperavx512f.h.
References x, and y.
vand_vm_vo32_vm()
static INLINE vmask vand_vm_vo32_vm (vopmask o, vmask m) static
Definition at line 112 of file helperavx512f.h.
References m.
vand_vm_vo64_vm()
static INLINE vmask vand_vm_vo64_vm (vopmask o, vmask m) static
Definition at line 108 of file helperavx512f.h.
References m.
vand_vo_vo_vo()
static INLINE vopmask vand_vo_vo_vo (vopmask x, vopmask y) static
Definition at line 103 of file helperavx512f.h.
References x, and y.
vandnot_vi2_vi2_vi2()
static INLINE vint2 vandnot_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 348 of file helperavx512f.h.
References x, and y.
vandnot_vi2_vo_vi2()
static INLINE vint2 vandnot_vi2_vo_vi2 (vopmask o, vint2 m) static
Definition at line 356 of file helperavx512f.h.
References m.
vandnot_vi_vi_vi()
static INLINE vint vandnot_vi_vi_vi (vint x, vint y) static
Definition at line 192 of file helperavx512f.h.
References x, and y.
vandnot_vi_vo_vi()
static INLINE vint vandnot_vi_vo_vi (vopmask o, vint y) static
Definition at line 194 of file helperavx512f.h.
References y.
vandnot_vm_vm_vm()
static INLINE vmask vandnot_vm_vm_vm (vmask x, vmask y) static
Definition at line 99 of file helperavx512f.h.
References x, and y.
Referenced by vabs_vf_vf().
vandnot_vm_vo32_vm()
static INLINE vmask vandnot_vm_vo32_vm (vopmask o, vmask m) static
Definition at line 113 of file helperavx512f.h.
References m.
vandnot_vm_vo64_vm()
static INLINE vmask vandnot_vm_vo64_vm (vopmask o, vmask m) static
Definition at line 109 of file helperavx512f.h.
References m.
vandnot_vo_vo_vo()
static INLINE vopmask vandnot_vo_vo_vo (vopmask x, vopmask y) static
Definition at line 104 of file helperavx512f.h.
References x, and y.
vcast_vd_d()
static INLINE vdouble vcast_vd_d (double d) static
Definition at line 149 of file helperavx512f.h.
References d.
Referenced by vsel_vd_vo_d_d().
vcast_vd_vi()
static INLINE vdouble vcast_vd_vi (vint vi) static
Definition at line 129 of file helperavx512f.h.
Referenced by vrint_vd_vd(), and vtruncate_vd_vd().
vcast_vf_f()
static INLINE vfloat vcast_vf_f (float f) static
Definition at line 303 of file helperavx512f.h.
References f.
Referenced by vabs_vf_vf(), visinf_vo_vf(), visminf_vo_vf(), vispinf_vo_vf(), vneg_vf_vf(), vrec_vf_vf(), vsel_vf_vo_f_f(), vsel_vf_vo_vo_f_f_f(), and vsel_vf_vo_vo_vo_f_f_f_f().
vcast_vf_vi2()
static INLINE vfloat vcast_vf_vi2 (vint2 vi) static
Definition at line 302 of file helperavx512f.h.
References vcast_vm_vi2().
Referenced by vrint_vf_vf(), and vtruncate_vf_vf().
vcast_vi2_i()
static INLINE vint2 vcast_vi2_i (int i) static
Definition at line 304 of file helperavx512f.h.
References i.
Referenced by vneg_vi2_vi2().
vcast_vi2_vm()
static INLINE vint2 vcast_vi2_vm (vmask vm) static
Definition at line 299 of file helperavx512f.h.
Referenced by vrint_vi2_vf(), and vtruncate_vi2_vf().
vcast_vi_i()
static INLINE vint vcast_vi_i (int i) static
Definition at line 130 of file helperavx512f.h.
References i.
Referenced by vneg_vi_vi().
vcast_vm_i_i()
static INLINE vmask vcast_vm_i_i (int i0, int i1) static
Definition at line 143 of file helperavx512f.h.
vcast_vm_vi2()
static INLINE vmask vcast_vm_vi2 (vint2 vi) static
Definition at line 300 of file helperavx512f.h.
Referenced by vcast_vf_vi2().
vcast_vo32_vo64()
static INLINE vopmask vcast_vo32_vo64 (vopmask o) static
Definition at line 116 of file helperavx512f.h.
vcast_vo64_vo32()
static INLINE vopmask vcast_vo64_vo32 (vopmask o) static
Definition at line 117 of file helperavx512f.h.
vcastu_vi2_vi()
static INLINE vint2 vcastu_vi2_vi (vint vi) static
Definition at line 135 of file helperavx512f.h.
vcastu_vi_vi2()
static INLINE vint vcastu_vi_vi2 (vint2 vi) static
Definition at line 139 of file helperavx512f.h.
vdiv_vd_vd_vd()
static INLINE vdouble vdiv_vd_vd_vd (vdouble x, vdouble y) static
Definition at line 158 of file helperavx512f.h.
References x, and y.
vdiv_vf_vf_vf()
static INLINE vfloat vdiv_vf_vf_vf (vfloat x, vfloat y) static
Definition at line 319 of file helperavx512f.h.
References x, and y.
Referenced by vrec_vf_vf().
veq64_vo_vi2_vi2()
static INLINE vopmask veq64_vo_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 367 of file helperavx512f.h.
References x, and y.
veq64_vo_vm_vm()
static INLINE vopmask veq64_vo_vm_vm (vmask x, vmask y) static
Definition at line 145 of file helperavx512f.h.
References x, and y.
veq_vi2_vi2_vi2()
static INLINE vint2 veq_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 371 of file helperavx512f.h.
References m, x, and y.
veq_vi_vi_vi()
static INLINE vint veq_vi_vi_vi (vint x, vint y) static
Definition at line 207 of file helperavx512f.h.
References x, and y.
veq_vo_vd_vd()
static INLINE vopmask veq_vo_vd_vd (vdouble x, vdouble y) static
Definition at line 175 of file helperavx512f.h.
References x, and y.
veq_vo_vf_vf()
static INLINE vopmask veq_vo_vf_vf (vfloat x, vfloat y) static
Definition at line 336 of file helperavx512f.h.
References x, and y.
Referenced by visinf_vo_vf(), visminf_vo_vf(), and vispinf_vo_vf().
veq_vo_vi2_vi2()
static INLINE vopmask veq_vo_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 363 of file helperavx512f.h.
References x, and y.
veq_vo_vi_vi()
static INLINE vopmask veq_vo_vi_vi (vint x, vint y) static
Definition at line 210 of file helperavx512f.h.
References x, and y.
vfixup_vd_vd_vd_vi2_i()
static INLINE vdouble vfixup_vd_vd_vd_vi2_i (vdouble a, vdouble b, vint2 c, int imm) static
Definition at line 270 of file helperavx512f.h.
References a, b, and imm().
vfixup_vf_vf_vf_vi2_i()
static INLINE vfloat vfixup_vf_vf_vf_vi2_i (vfloat a, vfloat b, vint2 c, int imm) static
Definition at line 271 of file helperavx512f.h.
References a, b, and imm().
vfma_vd_vd_vd_vd()
static INLINE vdouble vfma_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 169 of file helperavx512f.h.
References x, y, and z.
vfma_vf_vf_vf_vf()
static INLINE vfloat vfma_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 330 of file helperavx512f.h.
References x, y, and z.
vfmann_vd_vd_vd_vd()
static INLINE vdouble vfmann_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 173 of file helperavx512f.h.
References x, y, and z.
vfmann_vf_vf_vf_vf()
static INLINE vfloat vfmann_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 334 of file helperavx512f.h.
References x, y, and z.
vfmanp_vd_vd_vd_vd()
static INLINE vdouble vfmanp_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 172 of file helperavx512f.h.
References x, y, and z.
vfmanp_vf_vf_vf_vf()
static INLINE vfloat vfmanp_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 333 of file helperavx512f.h.
References x, y, and z.
vfmapn_vd_vd_vd_vd()
static INLINE vdouble vfmapn_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 171 of file helperavx512f.h.
References x, y, and z.
vfmapn_vf_vf_vf_vf()
static INLINE vfloat vfmapn_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 332 of file helperavx512f.h.
References x, y, and z.
vfmapp_vd_vd_vd_vd()
static INLINE vdouble vfmapp_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 170 of file helperavx512f.h.
References x, y, and z.
vfmapp_vf_vf_vf_vf()
static INLINE vfloat vfmapp_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 331 of file helperavx512f.h.
References x, y, and z.
vge_vo_vd_vd()
static INLINE vopmask vge_vo_vd_vd (vdouble x, vdouble y) static
Definition at line 181 of file helperavx512f.h.
References x, and y.
vge_vo_vf_vf()
static INLINE vopmask vge_vo_vf_vf (vfloat x, vfloat y) static
Definition at line 342 of file helperavx512f.h.
References x, and y.
vgetexp_vd_vd()
static INLINE vdouble vgetexp_vd_vd (vdouble d) static
Definition at line 260 of file helperavx512f.h.
References d.
Referenced by __attribute__().
vgetexp_vf_vf()
static INLINE vfloat vgetexp_vf_vf (vfloat d) static
Definition at line 261 of file helperavx512f.h.
References d.
vgetmant_vd_vd()
static INLINE vdouble vgetmant_vd_vd (vdouble d) static
Definition at line 263 of file helperavx512f.h.
References d.
Referenced by __attribute__().
vgetmant_vf_vf()
static INLINE vfloat vgetmant_vf_vf (vfloat d) static
Definition at line 264 of file helperavx512f.h.
References d.
vgt64_vo_vi2_vi2()
static INLINE vopmask vgt64_vo_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 368 of file helperavx512f.h.
References x, and y.
vgt64_vo_vm_vm()
static INLINE vopmask vgt64_vo_vm_vm (vmask x, vmask y) static
Definition at line 366 of file helperavx512f.h.
References x, and y.
vgt_vi2_vi2_vi2()
static INLINE vint2 vgt_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 375 of file helperavx512f.h.
References m, x, and y.
vgt_vi_vi_vi()
static INLINE vint vgt_vi_vi_vi (vint x, vint y) static
Definition at line 208 of file helperavx512f.h.
References x, and y.
vgt_vo_vd_vd()
static INLINE vopmask vgt_vo_vd_vd (vdouble x, vdouble y) static
Definition at line 180 of file helperavx512f.h.
References x, and y.
vgt_vo_vf_vf()
static INLINE vopmask vgt_vo_vf_vf (vfloat x, vfloat y) static
Definition at line 341 of file helperavx512f.h.
References x, and y.
vgt_vo_vi2_vi2()
static INLINE vopmask vgt_vo_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 364 of file helperavx512f.h.
References x, and y.
vgt_vo_vi_vi()
static INLINE vopmask vgt_vo_vi_vi (vint x, vint y) static
Definition at line 213 of file helperavx512f.h.
References x, and y.
vhi64_vi_vi2()
static INLINE vint vhi64_vi_vi2 (vint2 x) static
Definition at line 507 of file helperavx512f.h.
References x.
vilogb2k_vi_vd()
static INLINE vint vilogb2k_vi_vd (vdouble d) static
Definition at line 258 of file helperavx512f.h.
References d, and vrint_vi_vd().
vilogbk_vi2_vf()
static INLINE vint2 vilogbk_vi2_vf (vfloat d) static
Definition at line 407 of file helperavx512f.h.
References d, and vrint_vi2_vf().
vilogbk_vi_vd()
static INLINE vint vilogbk_vi_vd (vdouble d) static
Definition at line 254 of file helperavx512f.h.
References d, and vrint_vi_vd().
visinf_vo_vd()
static INLINE vopmask visinf_vo_vd (vdouble d) static
Definition at line 238 of file helperavx512f.h.
References d, and vabs_vd_vd().
visinf_vo_vf()
static INLINE vopmask visinf_vo_vf (vfloat d) static
Definition at line 402 of file helperavx512f.h.
References d, vabs_vf_vf(), vcast_vf_f(), and veq_vo_vf_vf().
visminf_vo_vd()
static INLINE vopmask visminf_vo_vd (vdouble d) static
Definition at line 246 of file helperavx512f.h.
References d.
visminf_vo_vf()
static INLINE vopmask visminf_vo_vf (vfloat d) static
Definition at line 404 of file helperavx512f.h.
References d, vcast_vf_f(), and veq_vo_vf_vf().
visnan_vo_vd()
static INLINE vopmask visnan_vo_vd (vdouble d) static
Definition at line 250 of file helperavx512f.h.
References d.
visnan_vo_vf()
static INLINE vopmask visnan_vo_vf (vfloat d) static
Definition at line 405 of file helperavx512f.h.
References d, and vneq_vo_vf_vf().
vispinf_vo_vd()
static INLINE vopmask vispinf_vo_vd (vdouble d) static
Definition at line 242 of file helperavx512f.h.
References d.
vispinf_vo_vf()
static INLINE vopmask vispinf_vo_vf (vfloat d) static
Definition at line 403 of file helperavx512f.h.
References d, vcast_vf_f(), and veq_vo_vf_vf().
vle_vo_vd_vd()
static INLINE vopmask vle_vo_vd_vd (vdouble x, vdouble y) static
Definition at line 178 of file helperavx512f.h.
References x, and y.
vle_vo_vf_vf()
static INLINE vopmask vle_vo_vf_vf (vfloat x, vfloat y) static
Definition at line 339 of file helperavx512f.h.
References x, and y.
vload_vd_p()
static INLINE vdouble vload_vd_p (const double * ptr) static
Definition at line 285 of file helperavx512f.h.
vload_vf_p()
static INLINE vfloat vload_vf_p (const float * ptr) static
Definition at line 418 of file helperavx512f.h.
vloadu_vd_p()
static INLINE vdouble vloadu_vd_p (const double * ptr) static
Definition at line 286 of file helperavx512f.h.
vloadu_vf_p()
static INLINE vfloat vloadu_vf_p (const float * ptr) static
Definition at line 419 of file helperavx512f.h.
vloadu_vi2_p()
static vint2 vloadu_vi2_p (int32_t * p) static
Definition at line 91 of file helperavx512f.h.
References p.
vloadu_vi_p()
static vint vloadu_vi_p (int32_t * p) static
Definition at line 93 of file helperavx512f.h.
References p.
vlt_vo_vd_vd()
static INLINE vopmask vlt_vo_vd_vd (vdouble x, vdouble y) static
Definition at line 177 of file helperavx512f.h.
References x, and y.
vlt_vo_vf_vf()
static INLINE vopmask vlt_vo_vf_vf (vfloat x, vfloat y) static
Definition at line 338 of file helperavx512f.h.
References x, and y.
vmax_vd_vd_vd()
static INLINE vdouble vmax_vd_vd_vd (vdouble x, vdouble y) static
Definition at line 166 of file helperavx512f.h.
References x, and y.
vmax_vf_vf_vf()
static INLINE vfloat vmax_vf_vf_vf (vfloat x, vfloat y) static
Definition at line 327 of file helperavx512f.h.
References x, and y.
vmin_vd_vd_vd()
static INLINE vdouble vmin_vd_vd_vd (vdouble x, vdouble y) static
Definition at line 167 of file helperavx512f.h.
References x, and y.
vmin_vf_vf_vf()
static INLINE vfloat vmin_vf_vf_vf (vfloat x, vfloat y) static
Definition at line 328 of file helperavx512f.h.
References x, and y.
vmla_vd_vd_vd_vd()
static INLINE vdouble vmla_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 163 of file helperavx512f.h.
References x, y, and z.
vmla_vf_vf_vf_vf()
static INLINE vfloat vmla_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 324 of file helperavx512f.h.
References x, y, and z.
vmlanp_vd_vd_vd_vd()
static INLINE vdouble vmlanp_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 165 of file helperavx512f.h.
References x, y, and z.
vmlanp_vf_vf_vf_vf()
static INLINE vfloat vmlanp_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 326 of file helperavx512f.h.
References x, y, and z.
vmlapn_vd_vd_vd_vd()
static INLINE vdouble vmlapn_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 164 of file helperavx512f.h.
References x, y, and z.
vmlapn_vf_vf_vf_vf()
static INLINE vfloat vmlapn_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 325 of file helperavx512f.h.
References x, y, and z.
vmlsubadd_vd_vd_vd_vd()
static INLINE vdouble vmlsubadd_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 439 of file helperavx512f.h.
References x, y, and z.
vmlsubadd_vf_vf_vf_vf()
static INLINE vfloat vmlsubadd_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 440 of file helperavx512f.h.
References x, y, and z.
vmovehdup_vd_vd()
static INLINE vdouble vmovehdup_vd_vd (vdouble d0) static
Definition at line 477 of file helperavx512f.h.
vmovehdup_vf_vf()
static INLINE vfloat vmovehdup_vf_vf (vfloat d0) static
Definition at line 480 of file helperavx512f.h.
vmoveldup_vd_vd()
static INLINE vdouble vmoveldup_vd_vd (vdouble d0) static
Definition at line 476 of file helperavx512f.h.
vmoveldup_vf_vf()
static INLINE vfloat vmoveldup_vf_vf (vfloat d0) static
Definition at line 479 of file helperavx512f.h.
vmul_vd_vd_vd()
static INLINE vdouble vmul_vd_vd_vd (vdouble x, vdouble y) static
Definition at line 157 of file helperavx512f.h.
References x, and y.
vmul_vf_vf_vf()
static INLINE vfloat vmul_vf_vf_vf (vfloat x, vfloat y) static
Definition at line 318 of file helperavx512f.h.
References x, and y.
vmulu_vi2_vi2_vi2()
static INLINE vint2 vmulu_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 503 of file helperavx512f.h.
References x, and y.
vneg_vd_vd()
static INLINE vdouble vneg_vd_vd (vdouble d) static
Definition at line 162 of file helperavx512f.h.
References d.
vneg_vf_vf()
static INLINE vfloat vneg_vf_vf (vfloat d) static
Definition at line 323 of file helperavx512f.h.
References d, vcast_vf_f(), and vxor_vm_vm_vm().
vneg_vi2_vi2()
static INLINE vint2 vneg_vi2_vi2 (vint2 e) static
Definition at line 346 of file helperavx512f.h.
References e, vcast_vi2_i(), and vsub_vi2_vi2_vi2().
vneg_vi_vi()
static INLINE vint vneg_vi_vi (vint e) static
Definition at line 189 of file helperavx512f.h.
References e, vcast_vi_i(), and vsub_vi_vi_vi().
vnegpos_vd_vd()
static INLINE vdouble vnegpos_vd_vd (vdouble d) static
Definition at line 432 of file helperavx512f.h.
References d, NPMASK, and vxor_vm_vm_vm().
Referenced by vsubadd_vd_vd_vd().
vnegpos_vf_vf()
static INLINE vfloat vnegpos_vf_vf (vfloat d) static
Definition at line 434 of file helperavx512f.h.
References d, NPMASKf, and vxor_vm_vm_vm().
Referenced by vsubadd_vf_vf_vf().
vneq_vo_vd_vd()
static INLINE vopmask vneq_vo_vd_vd (vdouble x, vdouble y) static
Definition at line 176 of file helperavx512f.h.
References x, and y.
vneq_vo_vf_vf()
static INLINE vopmask vneq_vo_vf_vf (vfloat x, vfloat y) static
Definition at line 337 of file helperavx512f.h.
References x, and y.
Referenced by visnan_vo_vf().
vnlt_vo_vd_vd()
static INLINE vopmask vnlt_vo_vd_vd (vdouble x, vdouble y) static
Definition at line 179 of file helperavx512f.h.
References x, and y.
vnlt_vo_vf_vf()
static INLINE vopmask vnlt_vo_vf_vf (vfloat x, vfloat y) static
Definition at line 340 of file helperavx512f.h.
References x, and y.
vor_vi2_vi2_vi2()
static INLINE vint2 vor_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 349 of file helperavx512f.h.
References x, and y.
vor_vi_vi_vi()
static INLINE vint vor_vi_vi_vi (vint x, vint y) static
Definition at line 201 of file helperavx512f.h.
References x, and y.
vor_vm_vm_vm()
static INLINE vmask vor_vm_vm_vm (vmask x, vmask y) static
Definition at line 100 of file helperavx512f.h.
References x, and y.
vor_vm_vo32_vm()
static INLINE vmask vor_vm_vo32_vm (vopmask o, vmask m) static
Definition at line 114 of file helperavx512f.h.
References m.
vor_vm_vo64_vm()
static INLINE vmask vor_vm_vo64_vm (vopmask o, vmask m) static
Definition at line 110 of file helperavx512f.h.
References m.
vor_vo_vo_vo()
static INLINE vopmask vor_vo_vo_vo (vopmask x, vopmask y) static
Definition at line 105 of file helperavx512f.h.
References x, and y.
vposneg_vd_vd()
static INLINE vdouble vposneg_vd_vd (vdouble d) static
Definition at line 431 of file helperavx512f.h.
References d, PNMASK, and vxor_vm_vm_vm().
vposneg_vf_vf()
static INLINE vfloat vposneg_vf_vf (vfloat d) static
Definition at line 433 of file helperavx512f.h.
References d, PNMASKf, and vxor_vm_vm_vm().
vprefetch_v_p()
static INLINE void vprefetch_v_p (const void * ptr) static
Definition at line 79 of file helperavx512f.h.
vrec_vd_vd()
static INLINE vdouble vrec_vd_vd (vdouble x) static
Definition at line 159 of file helperavx512f.h.
References x.
vrec_vf_vf()
static INLINE vfloat vrec_vf_vf (vfloat x) static
Definition at line 320 of file helperavx512f.h.
References vcast_vf_f(), vdiv_vf_vf_vf(), and x.
vreinterpret_vd_vi2()
static INLINE vdouble vreinterpret_vd_vi2 (vint2 vi) static
Definition at line 153 of file helperavx512f.h.
vreinterpret_vd_vm()
static INLINE vdouble vreinterpret_vd_vm (vmask vm) static
Definition at line 151 of file helperavx512f.h.
vreinterpret_vf_vi2()
static INLINE vfloat vreinterpret_vf_vi2 (vint2 vi) static
Definition at line 313 of file helperavx512f.h.
vreinterpret_vf_vm()
static INLINE vfloat vreinterpret_vf_vm (vmask vm) static
Definition at line 311 of file helperavx512f.h.
vreinterpret_vi2_vd()
static INLINE vint2 vreinterpret_vi2_vd (vdouble vd) static
Definition at line 152 of file helperavx512f.h.
vreinterpret_vi2_vf()
static INLINE vint2 vreinterpret_vi2_vf (vfloat vf) static
Definition at line 314 of file helperavx512f.h.
vreinterpret_vm_vd()
static INLINE vmask vreinterpret_vm_vd (vdouble vd) static
Definition at line 150 of file helperavx512f.h.
vreinterpret_vm_vf()
static INLINE vmask vreinterpret_vm_vf (vfloat vf) static
Definition at line 310 of file helperavx512f.h.
vrev21_vd_vd()
static INLINE vdouble vrev21_vd_vd (vdouble vd) static
Definition at line 442 of file helperavx512f.h.
vrev21_vf_vf()
static INLINE vfloat vrev21_vf_vf (vfloat vf) static
Definition at line 468 of file helperavx512f.h.
vreva2_vd_vd()
static INLINE vdouble vreva2_vd_vd (vdouble vd) static
Definition at line 446 of file helperavx512f.h.
vreva2_vf_vf()
static INLINE vfloat vreva2_vf_vf (vfloat vf) static
Definition at line 472 of file helperavx512f.h.
vrint_vd_vd()
static INLINE vdouble vrint_vd_vd (vdouble vd) static
Definition at line 133 of file helperavx512f.h.
References vcast_vd_vi(), and vrint_vi_vd().
vrint_vf_vf()
static INLINE vfloat vrint_vf_vf (vfloat vd) static
Definition at line 308 of file helperavx512f.h.
References vcast_vf_vi2(), and vrint_vi2_vf().
vrint_vi2_vf()
static INLINE vint2 vrint_vi2_vf (vfloat vf) static
Definition at line 305 of file helperavx512f.h.
References vcast_vi2_vm().
Referenced by vilogbk_vi2_vf(), and vrint_vf_vf().
vrint_vi_vd()
static INLINE vint vrint_vi_vd (vdouble vd) static
Definition at line 121 of file helperavx512f.h.
Referenced by vilogb2k_vi_vd(), vilogbk_vi_vd(), and vrint_vd_vd().
vscatter2_v_p_i_i_vd()
static INLINE void vscatter2_v_p_i_i_vd (double * ptr, int offset, int step, vdouble v) static
Definition at line 452 of file helperavx512f.h.
References offset.
vscatter2_v_p_i_i_vf()
static INLINE void vscatter2_v_p_i_i_vf (float * ptr, int offset, int step, vfloat v) static
Definition at line 484 of file helperavx512f.h.
References offset.
Referenced by vsscatter2_v_p_i_i_vf().
vsel_vd_vo_d_d()
static INLINE CONST vdouble vsel_vd_vo_d_d (vopmask o, double v1, double v0) static
Definition at line 221 of file helperavx512f.h.
References vcast_vd_d(), and vsel_vd_vo_vd_vd().
vsel_vd_vo_vd_vd()
static INLINE vdouble vsel_vd_vo_vd_vd (vopmask mask, vdouble x, vdouble y) static
Definition at line 217 of file helperavx512f.h.
References x, and y.
Referenced by vsel_vd_vo_d_d(), and vsel_vd_vo_vo_vo_d_d_d_d().
vsel_vd_vo_vo_d_d_d()
static INLINE vdouble vsel_vd_vo_vo_d_d_d (vopmask o0, vopmask o1, double d0, double d1, double d2) static
Definition at line 234 of file helperavx512f.h.
References vsel_vd_vo_vo_vo_d_d_d_d().
vsel_vd_vo_vo_vo_d_d_d_d()
static INLINE vdouble vsel_vd_vo_vo_vo_d_d_d_d (vopmask o0, vopmask o1, vopmask o2, double d0, double d1, double d2, double d3) static
Definition at line 226 of file helperavx512f.h.
References vsel_vd_vo_vd_vd().
Referenced by vsel_vd_vo_vo_d_d_d().
vsel_vf_vo_f_f()
static INLINE CONST vfloat vsel_vf_vo_f_f (vopmask o, float v1, float v0) static
Definition at line 390 of file helperavx512f.h.
References vcast_vf_f(), and vsel_vf_vo_vf_vf().
Referenced by vsel_vf_vo_vo_f_f_f(), and vsel_vf_vo_vo_vo_f_f_f_f().
vsel_vf_vo_vf_vf()
static INLINE vfloat vsel_vf_vo_vf_vf (vopmask m, vfloat x, vfloat y) static
Definition at line 384 of file helperavx512f.h.
References m, x, and y.
Referenced by vsel_vf_vo_f_f(), vsel_vf_vo_vo_f_f_f(), and vsel_vf_vo_vo_vo_f_f_f_f().
vsel_vf_vo_vo_f_f_f()
static INLINE vfloat vsel_vf_vo_vo_f_f_f (vopmask o0, vopmask o1, float d0, float d1, float d2) static
Definition at line 394 of file helperavx512f.h.
References vcast_vf_f(), vsel_vf_vo_f_f(), and vsel_vf_vo_vf_vf().
vsel_vf_vo_vo_vo_f_f_f_f()
static INLINE vfloat vsel_vf_vo_vo_vo_f_f_f_f (vopmask o0, vopmask o1, vopmask o2, float d0, float d1, float d2, float d3) static
Definition at line 398 of file helperavx512f.h.
References vcast_vf_f(), vsel_vf_vo_f_f(), and vsel_vf_vo_vf_vf().
vsel_vi2_vo_vi2_vi2()
static INLINE vint2 vsel_vi2_vo_vi2_vi2 (vopmask m, vint2 x, vint2 y) static
Definition at line 380 of file helperavx512f.h.
References m, x, and y.
vsel_vi_vo_vi_vi()
static INLINE vint vsel_vi_vo_vi_vi (vopmask m, vint x, vint y) static
Definition at line 293 of file helperavx512f.h.
References m, x, and y.
vset_vd_d_d()
static INLINE vdouble vset_vd_d_d (const double hi, const double lo) static
Definition at line 283 of file helperavx512f.h.
References hi, and lo.
vsll64_vi2_vi2_i()
static INLINE vint2 vsll64_vi2_vi2_i (vint2 x, int c) static
Definition at line 500 of file helperavx512f.h.
References x.
vsll_vi2_vi2_i()
static INLINE vint2 vsll_vi2_vi2_i (vint2 x, int c) static
Definition at line 360 of file helperavx512f.h.
References x.
vsll_vi_vi_i()
static INLINE vint vsll_vi_vi_i (vint x, int c) static
Definition at line 203 of file helperavx512f.h.
References x.
vsqrt_vd_vd()
static INLINE vdouble vsqrt_vd_vd (vdouble x) static
Definition at line 160 of file helperavx512f.h.
References x.
vsqrt_vf_vf()
static INLINE vfloat vsqrt_vf_vf (vfloat x) static
Definition at line 321 of file helperavx512f.h.
References x.
vsra_vi2_vi2_i()
static INLINE vint2 vsra_vi2_vi2_i (vint2 x, int c) static
Definition at line 362 of file helperavx512f.h.
References x.
vsra_vi_vi_i()
static INLINE vint vsra_vi_vi_i (vint x, int c) static
Definition at line 205 of file helperavx512f.h.
References x.
vsrl64_vi2_vi2_i()
static INLINE vint2 vsrl64_vi2_vi2_i (vint2 x, int c) static
Definition at line 501 of file helperavx512f.h.
References x.
vsrl_vi2_vi2_i()
static INLINE vint2 vsrl_vi2_vi2_i (vint2 x, int c) static
Definition at line 361 of file helperavx512f.h.
References x.
vsrl_vi_vi_i()
static INLINE vint vsrl_vi_vi_i (vint x, int c) static
Definition at line 204 of file helperavx512f.h.
References x.
vsscatter2_v_p_i_i_vd()
static INLINE void vsscatter2_v_p_i_i_vd (double * ptr, int offset, int step, vdouble v) static
Definition at line 459 of file helperavx512f.h.
References offset.
vsscatter2_v_p_i_i_vf()
static INLINE void vsscatter2_v_p_i_i_vf (float * ptr, int offset, int step, vfloat v) static
Definition at line 495 of file helperavx512f.h.
References offset, and vscatter2_v_p_i_i_vf().
vstore_v_p_vd()
static INLINE void vstore_v_p_vd (double * ptr, vdouble v) static
Definition at line 288 of file helperavx512f.h.
vstore_v_p_vf()
static INLINE void vstore_v_p_vf (float * ptr, vfloat v) static
Definition at line 421 of file helperavx512f.h.
vstoreu_v_p_vd()
static INLINE void vstoreu_v_p_vd (double * ptr, vdouble v) static
Definition at line 289 of file helperavx512f.h.
vstoreu_v_p_vf()
static INLINE void vstoreu_v_p_vf (float * ptr, vfloat v) static
Definition at line 422 of file helperavx512f.h.
vstoreu_v_p_vi()
static void vstoreu_v_p_vi (int32_t * p, vint v) static
Definition at line 94 of file helperavx512f.h.
References p.
vstoreu_v_p_vi2()
static void vstoreu_v_p_vi2 (int32_t * p, vint2 v) static
Definition at line 92 of file helperavx512f.h.
References p.
vstream_v_p_vd()
static INLINE void vstream_v_p_vd (double * ptr, vdouble v) static
Definition at line 450 of file helperavx512f.h.
vstream_v_p_vf()
static INLINE void vstream_v_p_vf (float * ptr, vfloat v) static
Definition at line 482 of file helperavx512f.h.
vsub64_vi2_vi2_vi2()
static INLINE vint2 vsub64_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 505 of file helperavx512f.h.
References x, and y.
vsub64_vi_vi_vi()
static INLINE vint vsub64_vi_vi_vi (vint x, vint y) static
Definition at line 188 of file helperavx512f.h.
References x, and y.
vsub_vd_vd_vd()
static INLINE vdouble vsub_vd_vd_vd (vdouble x, vdouble y) static
Definition at line 156 of file helperavx512f.h.
References x, and y.
vsub_vf_vf_vf()
static INLINE vfloat vsub_vf_vf_vf (vfloat x, vfloat y) static
Definition at line 317 of file helperavx512f.h.
References x, and y.
vsub_vi2_vi2_vi2()
static INLINE vint2 vsub_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 345 of file helperavx512f.h.
References x, and y.
Referenced by vneg_vi2_vi2().
vsub_vi_vi_vi()
static INLINE vint vsub_vi_vi_vi (vint x, vint y) static
Definition at line 187 of file helperavx512f.h.
References x, and y.
Referenced by vneg_vi_vi().
vsubadd_vd_vd_vd()
static INLINE vdouble vsubadd_vd_vd_vd (vdouble x, vdouble y) static
Definition at line 436 of file helperavx512f.h.
References vadd_vd_vd_vd(), vnegpos_vd_vd(), x, and y.
vsubadd_vf_vf_vf()
static INLINE vfloat vsubadd_vf_vf_vf (vfloat x, vfloat y) static
Definition at line 437 of file helperavx512f.h.
References vadd_vf_vf_vf(), vnegpos_vf_vf(), x, and y.
vtestallones_i_vo32()
static INLINE int vtestallones_i_vo32 (vopmask g) static
Definition at line 86 of file helperavx512f.h.
vtestallones_i_vo64()
static INLINE int vtestallones_i_vo64 (vopmask g) static
Definition at line 85 of file helperavx512f.h.
vtestz_i_vo()
static INLINE int vtestz_i_vo (vopmask x) static
Definition at line 498 of file helperavx512f.h.
References x.
vtestz_i_vo_vo()
static INLINE int vtestz_i_vo_vo (vopmask x, vopmask y) static
Definition at line 497 of file helperavx512f.h.
References x, and y.
vtruncate_vd_vd()
static INLINE vdouble vtruncate_vd_vd (vdouble vd) static
Definition at line 132 of file helperavx512f.h.
References vcast_vd_vi(), and vtruncate_vi_vd().
vtruncate_vf_vf()
static INLINE vfloat vtruncate_vf_vf (vfloat vd) static
Definition at line 307 of file helperavx512f.h.
References vcast_vf_vi2(), and vtruncate_vi2_vf().
vtruncate_vi2_vf()
static INLINE vint2 vtruncate_vi2_vf (vfloat vf) static
Definition at line 306 of file helperavx512f.h.
References vcast_vi2_vm().
Referenced by vtruncate_vf_vf().
vtruncate_vi_vd()
static INLINE vint vtruncate_vi_vd (vdouble vd) static
Definition at line 125 of file helperavx512f.h.
Referenced by vtruncate_vd_vd().
vxor_vi2_vi2_vi2()
static INLINE vint2 vxor_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 350 of file helperavx512f.h.
References x, and y.
vxor_vi_vi_vi()
static INLINE vint vxor_vi_vi_vi (vint x, vint y) static
Definition at line 202 of file helperavx512f.h.
References x, and y.
vxor_vm_vm_vm()
static INLINE vmask vxor_vm_vm_vm (vmask x, vmask y) static
Definition at line 101 of file helperavx512f.h.
References x, and y.
Referenced by vneg_vf_vf(), vnegpos_vd_vd(), vnegpos_vf_vf(), vposneg_vd_vd(), and vposneg_vf_vf().
vxor_vo_vo_vo()
static INLINE vopmask vxor_vo_vo_vo (vopmask x, vopmask y) static
Definition at line 106 of file helperavx512f.h.
References x, and y.