flang: helperavx2.h File Reference
helperavx2.h File Reference
#include <x86intrin.h>
#include <stdint.h>
#include "misc.h"
Macros
#define ENABLE_DP
#define LOG2VECTLENDP 2
#define VECTLENDP (1 << LOG2VECTLENDP)
#define ENABLE_FMA_DP
#define ENABLE_SP
#define LOG2VECTLENSP (LOG2VECTLENDP+1)
#define VECTLENSP (1 << LOG2VECTLENSP)
#define ENABLE_FMA_SP
#define PNMASK ((vdouble) { +0.0, -0.0, +0.0, -0.0 })
#define NPMASK ((vdouble) { -0.0, +0.0, -0.0, +0.0 })
#define PNMASKf ((vfloat) { +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f })
#define NPMASKf ((vfloat) { -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f })
Typedefs
typedef __m256i vmask
typedef __m256i vopmask
typedef __m256d vdouble
typedef __m128i vint
typedef __m256 vfloat
typedef __m256i vint2
Functions
void Sleef_x86CpuID (int32_t out[4], uint32_t eax, uint32_t ecx)
static int cpuSupportsAVX2 ()
static int cpuSupportsFMA ()
static INLINE void vprefetch_v_p (const char *ptr)
static INLINE int vtestallones_i_vo32 (vopmask g)
static INLINE int vtestallones_i_vo64 (vopmask g)
static INLINE vdouble vcast_vd_d (double d)
static INLINE vmask vreinterpret_vm_vd (vdouble vd)
static INLINE vdouble vreinterpret_vd_vm (vmask vm)
static INLINE vint2 vreinterpret_vi2_vd (vdouble vd)
static INLINE vdouble vreinterpret_vd_vi2 (vint2 vi)
static vint2 vloadu_vi2_p (int32_t *p)
static void vstoreu_v_p_vi2 (int32_t *p, vint2 v)
static vint vloadu_vi_p (int32_t *p)
static void vstoreu_v_p_vi (int32_t *p, vint v)
static INLINE vmask vand_vm_vm_vm (vmask x, vmask y)
static INLINE vmask vandnot_vm_vm_vm (vmask x, vmask y)
static INLINE vmask vor_vm_vm_vm (vmask x, vmask y)
static INLINE vmask vxor_vm_vm_vm (vmask x, vmask y)
static INLINE vopmask vand_vo_vo_vo (vopmask x, vopmask y)
static INLINE vopmask vandnot_vo_vo_vo (vopmask x, vopmask y)
static INLINE vopmask vor_vo_vo_vo (vopmask x, vopmask y)
static INLINE vopmask vxor_vo_vo_vo (vopmask x, vopmask y)
static INLINE vmask vand_vm_vo64_vm (vopmask x, vmask y)
static INLINE vmask vandnot_vm_vo64_vm (vopmask x, vmask y)
static INLINE vmask vor_vm_vo64_vm (vopmask x, vmask y)
static INLINE vmask vxor_vm_vo64_vm (vopmask x, vmask y)
static INLINE vmask vand_vm_vo32_vm (vopmask x, vmask y)
static INLINE vmask vandnot_vm_vo32_vm (vopmask x, vmask y)
static INLINE vmask vor_vm_vo32_vm (vopmask x, vmask y)
static INLINE vmask vxor_vm_vo32_vm (vopmask x, vmask y)
static INLINE vopmask vcast_vo32_vo64 (vopmask o)
static INLINE vopmask vcast_vo64_vo32 (vopmask o)
static INLINE vint vrint_vi_vd (vdouble vd)
static INLINE vint vtruncate_vi_vd (vdouble vd)
static INLINE vdouble vrint_vd_vd (vdouble vd)
static INLINE vfloat vrint_vf_vf (vfloat vd)
static INLINE vdouble vtruncate_vd_vd (vdouble vd)
static INLINE vfloat vtruncate_vf_vf (vfloat vf)
static INLINE vdouble vcast_vd_vi (vint vi)
static INLINE vint vcast_vi_i (int i)
static INLINE vint2 vcastu_vi2_vi (vint vi)
static INLINE vint vcastu_vi_vi2 (vint2 vi)
static INLINE vmask vcast_vm_i_i (int i0, int i1)
static INLINE vopmask veq64_vo_vm_vm (vmask x, vmask y)
static INLINE vopmask vgt64_vo_vm_vm (vmask x, vmask y)
static INLINE vdouble vadd_vd_vd_vd (vdouble x, vdouble y)
static INLINE vdouble vsub_vd_vd_vd (vdouble x, vdouble y)
static INLINE vdouble vmul_vd_vd_vd (vdouble x, vdouble y)
static INLINE vdouble vdiv_vd_vd_vd (vdouble x, vdouble y)
static INLINE vdouble vrec_vd_vd (vdouble x)
static INLINE vdouble vsqrt_vd_vd (vdouble x)
static INLINE vdouble vabs_vd_vd (vdouble d)
static INLINE vdouble vneg_vd_vd (vdouble d)
static INLINE vdouble vmla_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vdouble vmlapn_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vdouble vmlanp_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vdouble vmax_vd_vd_vd (vdouble x, vdouble y)
static INLINE vdouble vmin_vd_vd_vd (vdouble x, vdouble y)
static INLINE vdouble vfma_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vdouble vfmapp_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vdouble vfmapn_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vdouble vfmanp_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vdouble vfmann_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vopmask veq_vo_vd_vd (vdouble x, vdouble y)
static INLINE vopmask vneq_vo_vd_vd (vdouble x, vdouble y)
static INLINE vopmask vlt_vo_vd_vd (vdouble x, vdouble y)
static INLINE vopmask vle_vo_vd_vd (vdouble x, vdouble y)
static INLINE vopmask vnlt_vo_vd_vd (vdouble x, vdouble y)
static INLINE vopmask vgt_vo_vd_vd (vdouble x, vdouble y)
static INLINE vopmask vge_vo_vd_vd (vdouble x, vdouble y)
static INLINE vint vadd_vi_vi_vi (vint x, vint y)
static INLINE vint vsub_vi_vi_vi (vint x, vint y)
static INLINE vint vneg_vi_vi (vint e)
static INLINE vint vand_vi_vi_vi (vint x, vint y)
static INLINE vint vandnot_vi_vi_vi (vint x, vint y)
static INLINE vint vor_vi_vi_vi (vint x, vint y)
static INLINE vint vxor_vi_vi_vi (vint x, vint y)
static INLINE vint vandnot_vi_vo_vi (vopmask m, vint y)
static INLINE vint vand_vi_vo_vi (vopmask m, vint y)
static INLINE vint vsll_vi_vi_i (vint x, int c)
static INLINE vint vsrl_vi_vi_i (vint x, int c)
static INLINE vint vsra_vi_vi_i (vint x, int c)
static INLINE vint veq_vi_vi_vi (vint x, vint y)
static INLINE vint vgt_vi_vi_vi (vint x, vint y)
static INLINE vopmask veq_vo_vi_vi (vint x, vint y)
static INLINE vopmask vgt_vo_vi_vi (vint x, vint y)
static INLINE vint vsel_vi_vo_vi_vi (vopmask m, vint x, vint y)
static INLINE vdouble vsel_vd_vo_vd_vd (vopmask o, vdouble x, vdouble y)
static INLINE vdouble vsel_vd_vo_d_d (vopmask o, double v1, double v0)
static INLINE vdouble vsel_vd_vo_vo_vo_d_d_d_d (vopmask o0, vopmask o1, vopmask o2, double d0, double d1, double d2, double d3)
static INLINE vdouble vsel_vd_vo_vo_d_d_d (vopmask o0, vopmask o1, double d0, double d1, double d2)
static INLINE vopmask visinf_vo_vd (vdouble d)
static INLINE vopmask vispinf_vo_vd (vdouble d)
static INLINE vopmask visminf_vo_vd (vdouble d)
static INLINE vopmask visnan_vo_vd (vdouble d)
static INLINE vdouble vset_vd_d_d (const double hi, const double lo)
static INLINE vdouble vload_vd_p (const double *ptr)
static INLINE vdouble vloadu_vd_p (const double *ptr)
static INLINE void vstore_v_p_vd (double *ptr, vdouble v)
static INLINE void vstoreu_v_p_vd (double *ptr, vdouble v)
static INLINE vint2 vcast_vi2_vm (vmask vm)
static INLINE vmask vcast_vm_vi2 (vint2 vi)
static INLINE vint2 vrint_vi2_vf (vfloat vf)
static INLINE vint2 vtruncate_vi2_vf (vfloat vf)
static INLINE vfloat vcast_vf_vi2 (vint2 vi)
static INLINE vfloat vcast_vf_f (float f)
static INLINE vint2 vcast_vi2_i (int i)
static INLINE vmask vreinterpret_vm_vf (vfloat vf)
static INLINE vfloat vreinterpret_vf_vm (vmask vm)
static INLINE vfloat vreinterpret_vf_vi2 (vint2 vi)
static INLINE vint2 vreinterpret_vi2_vf (vfloat vf)
static INLINE vfloat vadd_vf_vf_vf (vfloat x, vfloat y)
static INLINE vfloat vsub_vf_vf_vf (vfloat x, vfloat y)
static INLINE vfloat vmul_vf_vf_vf (vfloat x, vfloat y)
static INLINE vfloat vdiv_vf_vf_vf (vfloat x, vfloat y)
static INLINE vfloat vrec_vf_vf (vfloat x)
static INLINE vfloat vsqrt_vf_vf (vfloat x)
static INLINE vfloat vabs_vf_vf (vfloat f)
static INLINE vfloat vneg_vf_vf (vfloat d)
static INLINE vfloat vmla_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vfloat vmlapn_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vfloat vmlanp_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vfloat vmax_vf_vf_vf (vfloat x, vfloat y)
static INLINE vfloat vmin_vf_vf_vf (vfloat x, vfloat y)
static INLINE vfloat vfma_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vfloat vfmapp_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vfloat vfmapn_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vfloat vfmanp_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vfloat vfmann_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vopmask veq_vo_vf_vf (vfloat x, vfloat y)
static INLINE vopmask vneq_vo_vf_vf (vfloat x, vfloat y)
static INLINE vopmask vlt_vo_vf_vf (vfloat x, vfloat y)
static INLINE vopmask vle_vo_vf_vf (vfloat x, vfloat y)
static INLINE vopmask vnlt_vo_vf_vf (vfloat x, vfloat y)
static INLINE vopmask vgt_vo_vf_vf (vfloat x, vfloat y)
static INLINE vopmask vge_vo_vf_vf (vfloat x, vfloat y)
static INLINE vint2 vadd_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vsub_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vneg_vi2_vi2 (vint2 e)
static INLINE vint2 vand_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vandnot_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vor_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vxor_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vand_vi2_vo_vi2 (vopmask x, vint2 y)
static INLINE vint2 vandnot_vi2_vo_vi2 (vopmask x, vint2 y)
static INLINE vint2 vsll_vi2_vi2_i (vint2 x, int c)
static INLINE vint2 vsrl_vi2_vi2_i (vint2 x, int c)
static INLINE vint2 vsra_vi2_vi2_i (vint2 x, int c)
static INLINE vopmask veq_vo_vi2_vi2 (vint2 x, vint2 y)
static INLINE vopmask vgt_vo_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 veq_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vgt_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vopmask veq64_vo_vi2_vi2 (vint2 x, vint2 y)
static INLINE vopmask vgt64_vo_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 veq64_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vgt64_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vsel_vi2_vo_vi2_vi2 (vopmask m, vint2 x, vint2 y)
static INLINE vfloat vsel_vf_vo_vf_vf (vopmask o, vfloat x, vfloat y)
static INLINE CONST vfloat vsel_vf_vo_f_f (vopmask o, float v1, float v0)
static INLINE vfloat vsel_vf_vo_vo_f_f_f (vopmask o0, vopmask o1, float d0, float d1, float d2)
static INLINE vfloat vsel_vf_vo_vo_vo_f_f_f_f (vopmask o0, vopmask o1, vopmask o2, float d0, float d1, float d2, float d3)
static INLINE vopmask visinf_vo_vf (vfloat d)
static INLINE vopmask vispinf_vo_vf (vfloat d)
static INLINE vopmask visminf_vo_vf (vfloat d)
static INLINE vopmask visnan_vo_vf (vfloat d)
static INLINE vfloat vload_vf_p (const float *ptr)
static INLINE vfloat vloadu_vf_p (const float *ptr)
static INLINE void vstore_v_p_vf (float *ptr, vfloat v)
static INLINE void vstoreu_v_p_vf (float *ptr, vfloat v)
static INLINE vdouble vposneg_vd_vd (vdouble d)
static INLINE vdouble vnegpos_vd_vd (vdouble d)
static INLINE vfloat vposneg_vf_vf (vfloat d)
static INLINE vfloat vnegpos_vf_vf (vfloat d)
static INLINE vdouble vsubadd_vd_vd_vd (vdouble x, vdouble y)
static INLINE vfloat vsubadd_vf_vf_vf (vfloat x, vfloat y)
static INLINE vdouble vmlsubadd_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z)
static INLINE vfloat vmlsubadd_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z)
static INLINE vdouble vrev21_vd_vd (vdouble d0)
static INLINE vdouble vreva2_vd_vd (vdouble d0)
static INLINE void vstream_v_p_vd (double *ptr, vdouble v)
static INLINE void vscatter2_v_p_i_i_vd (double *ptr, int offset, int step, vdouble v)
static INLINE void vsscatter2_v_p_i_i_vd (double *ptr, int offset, int step, vdouble v)
static INLINE vfloat vrev21_vf_vf (vfloat d0)
static INLINE vfloat vreva2_vf_vf (vfloat d0)
static INLINE vfloat vmoveldup_vf_vf (vfloat d0)
static INLINE vfloat vmovehdup_vf_vf (vfloat d0)
static INLINE vdouble vmoveldup_vd_vd (vdouble d0)
static INLINE vdouble vmovehdup_vd_vd (vdouble d0)
static INLINE void vstream_v_p_vf (float *ptr, vfloat v)
static INLINE void vscatter2_v_p_i_i_vf (float *ptr, int offset, int step, vfloat v)
static INLINE void vsscatter2_v_p_i_i_vf (float *ptr, int offset, int step, vfloat v)
static INLINE int vtestz_i_vf_vf (vfloat x, vfloat y)
static INLINE int vtestz_i_vo_vo (vopmask x, vopmask y)
static INLINE int vtestz_i_vo (vopmask x)
static INLINE vint2 vsll64_vi2_vi2_i (vint2 x, int c)
static INLINE vint2 vsrl64_vi2_vi2_i (vint2 x, int c)
static INLINE vint2 vmulu_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vadd64_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vint2 vsub64_vi2_vi2_vi2 (vint2 x, vint2 y)
static INLINE vdouble vcvtsi64_vd_vi2 (vint2 x)
static INLINE vint vhi64_vi_vi2 (vint2 x)
Macro Definition Documentation
ENABLE_DP
#define ENABLE_DP
Definition at line 18 of file helperavx2.h.
ENABLE_FMA_DP
#define ENABLE_FMA_DP
Definition at line 21 of file helperavx2.h.
ENABLE_FMA_SP
#define ENABLE_FMA_SP
Definition at line 26 of file helperavx2.h.
ENABLE_SP
#define ENABLE_SP
Definition at line 23 of file helperavx2.h.
LOG2VECTLENDP
#define LOG2VECTLENDP 2
Definition at line 19 of file helperavx2.h.
LOG2VECTLENSP
#define LOG2VECTLENSP (LOG2VECTLENDP+1)
Definition at line 24 of file helperavx2.h.
NPMASK
#define NPMASK ((vdouble) { -0.0, +0.0, -0.0, +0.0 })
Definition at line 372 of file helperavx2.h.
NPMASKf
#define NPMASKf ((vfloat) { -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f })
Definition at line 374 of file helperavx2.h.
PNMASK
#define PNMASK ((vdouble) { +0.0, -0.0, +0.0, -0.0 })
Definition at line 371 of file helperavx2.h.
PNMASKf
#define PNMASKf ((vfloat) { +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f, +0.0f, -0.0f })
Definition at line 373 of file helperavx2.h.
VECTLENDP
#define VECTLENDP (1 << LOG2VECTLENDP)
Definition at line 20 of file helperavx2.h.
VECTLENSP
#define VECTLENSP (1 << LOG2VECTLENSP)
Definition at line 25 of file helperavx2.h.
Typedef Documentation
vdouble
typedef __m256d vdouble
Definition at line 40 of file helperavx2.h.
vfloat
typedef __m256 vfloat
Definition at line 43 of file helperavx2.h.
vint
typedef __m128i vint
Definition at line 41 of file helperavx2.h.
vint2
typedef __m256i vint2
Definition at line 44 of file helperavx2.h.
vmask
typedef __m256i vmask
Definition at line 37 of file helperavx2.h.
vopmask
typedef __m256i vopmask
Definition at line 38 of file helperavx2.h.
Function Documentation
cpuSupportsAVX2()
static int cpuSupportsAVX2 () static
Definition at line 52 of file helperavx2.h.
References reg, and Sleef_x86CpuID().
cpuSupportsFMA()
static int cpuSupportsFMA () static
Definition at line 58 of file helperavx2.h.
References reg, and Sleef_x86CpuID().
Sleef_x86CpuID()
void Sleef_x86CpuID (int32_t out[4], uint32_t eax, uint32_t ecx)
Referenced by cpuSupportsAVX2(), and cpuSupportsFMA().
vabs_vd_vd()
static INLINE vdouble vabs_vd_vd (vdouble d) static
Definition at line 163 of file helperavx2.h.
References d.
Referenced by visinf_vo_vd().
vabs_vf_vf()
static INLINE vfloat vabs_vf_vf (vfloat f) static
Definition at line 281 of file helperavx2.h.
References f, vandnot_vm_vm_vm(), vcast_vf_f(), vreinterpret_vf_vm(), and vreinterpret_vm_vf().
Referenced by __attribute__(), and visinf_vo_vf().
vadd64_vi2_vi2_vi2()
static INLINE vint2 vadd64_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 431 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), __reduction_slowpath(), and __vldexp_manual().
vadd_vd_vd_vd()
static INLINE vdouble vadd_vd_vd_vd (vdouble x, vdouble y) static
Definition at line 157 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), __vcis_d_kernel(), __vldexp_manual(), and vfast2sum_dp().
vadd_vf_vf_vf()
static INLINE vfloat vadd_vf_vf_vf (vfloat x, vfloat y) static
Definition at line 275 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), __vcis_kernel(), __vldexpf_manual(), and vfast2sum().
vadd_vi2_vi2_vi2()
static INLINE vint2 vadd_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 303 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), __reduction_slowpath(), __vcis_d_kernel(), __vcis_kernel(), __vldexp_manual(), and __vldexpf_manual().
vadd_vi_vi_vi()
static INLINE vint vadd_vi_vi_vi (vint x, vint y) static
Definition at line 187 of file helperavx2.h.
References x, and y.
vand_vi2_vi2_vi2()
static INLINE vint2 vand_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 307 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), __reduction_slowpath(), __tan_f_vec(), __vcis_d_kernel(), __vcis_kernel(), __vldexp_manual(), __vldexpf_manual(), cexp_vec(), cexpf_vec(), and vand_vi2_vo_vi2().
vand_vi2_vo_vi2()
static INLINE vint2 vand_vi2_vo_vi2 (vopmask x, vint2 y) static
Definition at line 312 of file helperavx2.h.
References vand_vi2_vi2_vi2(), vcast_vi2_vm(), x, and y.
Referenced by __vldexpf_manual().
vand_vi_vi_vi()
static INLINE vint vand_vi_vi_vi (vint x, vint y) static
Definition at line 191 of file helperavx2.h.
References x, and y.
vand_vi_vo_vi()
static INLINE vint vand_vi_vo_vi (vopmask m, vint y) static
Definition at line 197 of file helperavx2.h.
References m, and y.
vand_vm_vm_vm()
static INLINE vmask vand_vm_vm_vm (vmask x, vmask y) static
Definition at line 100 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.
Referenced by __attribute__().
vand_vm_vo32_vm()
static INLINE vmask vand_vm_vo32_vm (vopmask x, vmask y) static
Definition at line 115 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.
vand_vm_vo64_vm()
static INLINE vmask vand_vm_vo64_vm (vopmask x, vmask y) static
Definition at line 110 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.
Referenced by __vldexp_manual().
vand_vo_vo_vo()
static INLINE vopmask vand_vo_vo_vo (vopmask x, vopmask y) static
Definition at line 105 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.
vandnot_vi2_vi2_vi2()
static INLINE vint2 vandnot_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 308 of file helperavx2.h.
References x, and y.
Referenced by cexp_vec(), cexpf_vec(), and vandnot_vi2_vo_vi2().
vandnot_vi2_vo_vi2()
static INLINE vint2 vandnot_vi2_vo_vi2 (vopmask x, vint2 y) static
Definition at line 313 of file helperavx2.h.
References vandnot_vi2_vi2_vi2(), vcast_vi2_vm(), x, and y.
Referenced by __vldexpf_manual().
vandnot_vi_vi_vi()
static INLINE vint vandnot_vi_vi_vi (vint x, vint y) static
Definition at line 192 of file helperavx2.h.
References x, and y.
vandnot_vi_vo_vi()
static INLINE vint vandnot_vi_vo_vi (vopmask m, vint y) static
Definition at line 196 of file helperavx2.h.
References m, and y.
vandnot_vm_vm_vm()
static INLINE vmask vandnot_vm_vm_vm (vmask x, vmask y) static
Definition at line 101 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.
Referenced by vabs_vf_vf().
vandnot_vm_vo32_vm()
static INLINE vmask vandnot_vm_vo32_vm (vopmask x, vmask y) static
Definition at line 116 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.
vandnot_vm_vo64_vm()
static INLINE vmask vandnot_vm_vo64_vm (vopmask x, vmask y) static
Definition at line 111 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.
Referenced by __vldexp_manual().
vandnot_vo_vo_vo()
static INLINE vopmask vandnot_vo_vo_vo (vopmask x, vopmask y) static
Definition at line 106 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.
Referenced by __vldexp_manual(), and __vldexpf_manual().
vcast_vd_d()
static INLINE vdouble vcast_vd_d (double d) static
Definition at line 85 of file helperavx2.h.
References d.
Referenced by __attribute__().
vcast_vd_vi()
static INLINE vdouble vcast_vd_vi (vint vi) static
Definition at line 136 of file helperavx2.h.
Referenced by __attribute__().
vcast_vf_f()
static INLINE vfloat vcast_vf_f (float f) static
Definition at line 267 of file helperavx2.h.
References f.
Referenced by __attribute__(), __tan_f_vec(), __tan_kernel(), vabs_vf_vf(), visinf_vo_vf(), visminf_vo_vf(), vispinf_vo_vf(), vneg_vf_vf(), vrec_vf_vf(), vsel_vf_vo_f_f(), vsel_vf_vo_vo_f_f_f(), and vsel_vf_vo_vo_vo_f_f_f_f().
vcast_vf_vi2()
static INLINE vfloat vcast_vf_vi2 (vint2 vi) static
Definition at line 266 of file helperavx2.h.
References vcast_vm_vi2().
Referenced by __attribute__(), and __vldexpf_kernel().
vcast_vi2_i()
static INLINE vint2 vcast_vi2_i (int i) static
Definition at line 268 of file helperavx2.h.
References i.
Referenced by __attribute__(), __reduction_slowpath(), __tan_f_vec(), __tan_kernel(), and vneg_vi2_vi2().
vcast_vi2_vm()
static INLINE vint2 vcast_vi2_vm (vmask vm) static
Definition at line 261 of file helperavx2.h.
Referenced by vand_vi2_vo_vi2(), vandnot_vi2_vo_vi2(), vreinterpret_vi2_vf(), vrint_vi2_vf(), and vtruncate_vi2_vf().
vcast_vi_i()
static INLINE vint vcast_vi_i (int i) static
Definition at line 137 of file helperavx2.h.
References i.
Referenced by __attribute__(), and vneg_vi_vi().
vcast_vm_i_i()
static INLINE vmask vcast_vm_i_i (int i0, int i1) static
Definition at line 148 of file helperavx2.h.
Referenced by __attribute__(), and __reduction_slowpath().
vcast_vm_vi2()
static INLINE vmask vcast_vm_vi2 (vint2 vi) static
Definition at line 262 of file helperavx2.h.
Referenced by vcast_vf_vi2(), and vreinterpret_vf_vi2().
vcast_vo32_vo64()
static INLINE vopmask vcast_vo32_vo64 (vopmask o) static
Definition at line 120 of file helperavx2.h.
vcast_vo64_vo32()
static INLINE vopmask vcast_vo64_vo32 (vopmask o) static
Definition at line 124 of file helperavx2.h.
vcastu_vi2_vi()
static INLINE vint2 vcastu_vi2_vi (vint vi) static
Definition at line 139 of file helperavx2.h.
vcastu_vi_vi2()
static INLINE vint vcastu_vi_vi2 (vint2 vi) static
Definition at line 143 of file helperavx2.h.
vcvtsi64_vd_vi2()
static INLINE vdouble vcvtsi64_vd_vi2 (vint2 x) static
Definition at line 435 of file helperavx2.h.
References i, td, and x.
vdiv_vd_vd_vd()
static INLINE vdouble vdiv_vd_vd_vd (vdouble x, vdouble y) static
Definition at line 160 of file helperavx2.h.
References x, and y.
vdiv_vf_vf_vf()
static INLINE vfloat vdiv_vf_vf_vf (vfloat x, vfloat y) static
Definition at line 278 of file helperavx2.h.
References x, and y.
Referenced by __tan_kernel(), and vrec_vf_vf().
veq64_vi2_vi2_vi2()
static INLINE vint2 veq64_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 326 of file helperavx2.h.
References x, and y.
veq64_vo_vi2_vi2()
static INLINE vopmask veq64_vo_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 324 of file helperavx2.h.
References x, and y.
Referenced by __attribute__().
veq64_vo_vm_vm()
static INLINE vopmask veq64_vo_vm_vm (vmask x, vmask y) static
Definition at line 152 of file helperavx2.h.
References x, and y.
Referenced by __vcis_d_kernel(), and __vldexp_manual().
veq_vi2_vi2_vi2()
static INLINE vint2 veq_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 321 of file helperavx2.h.
References x, and y.
veq_vi_vi_vi()
static INLINE vint veq_vi_vi_vi (vint x, vint y) static
Definition at line 203 of file helperavx2.h.
References x, and y.
veq_vo_vd_vd()
static INLINE vopmask veq_vo_vd_vd (vdouble x, vdouble y) static
Definition at line 177 of file helperavx2.h.
References vreinterpret_vm_vd(), x, and y.
Referenced by __attribute__(), and cexp_vec().
veq_vo_vf_vf()
static INLINE vopmask veq_vo_vf_vf (vfloat x, vfloat y) static
Definition at line 295 of file helperavx2.h.
References vreinterpret_vm_vf(), x, and y.
Referenced by __attribute__(), cexpf_vec(), visinf_vo_vf(), visminf_vo_vf(), and vispinf_vo_vf().
veq_vo_vi2_vi2()
static INLINE vopmask veq_vo_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 319 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), __reduction_slowpath(), __tan_kernel(), __vcis_kernel(), and __vldexpf_manual().
veq_vo_vi_vi()
static INLINE vopmask veq_vo_vi_vi (vint x, vint y) static
Definition at line 206 of file helperavx2.h.
References x, and y.
vfma_vd_vd_vd_vd()
static INLINE vdouble vfma_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 171 of file helperavx2.h.
References x, y, and z.
Referenced by __attribute__(), __vcis_d_kernel(), __vexp_d_kernel(), and __vexp_d_poly().
vfma_vf_vf_vf_vf()
static INLINE vfloat vfma_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 289 of file helperavx2.h.
References x, y, and z.
Referenced by __attribute__(), __tan_f_vec(), __tan_kernel(), __vcis_kernel(), __vexp_kernel(), and __vexp_poly().
vfmann_vd_vd_vd_vd()
static INLINE vdouble vfmann_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 175 of file helperavx2.h.
References x, y, and z.
vfmann_vf_vf_vf_vf()
static INLINE vfloat vfmann_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 293 of file helperavx2.h.
References x, y, and z.
vfmanp_vd_vd_vd_vd()
static INLINE vdouble vfmanp_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 174 of file helperavx2.h.
References x, y, and z.
vfmanp_vf_vf_vf_vf()
static INLINE vfloat vfmanp_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 292 of file helperavx2.h.
References x, y, and z.
vfmapn_vd_vd_vd_vd()
static INLINE vdouble vfmapn_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 173 of file helperavx2.h.
References x, y, and z.
Referenced by __attribute__(), and vfast2mul_dp().
vfmapn_vf_vf_vf_vf()
static INLINE vfloat vfmapn_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 291 of file helperavx2.h.
References x, y, and z.
Referenced by __attribute__(), and vfast2mul().
vfmapp_vd_vd_vd_vd()
static INLINE vdouble vfmapp_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 172 of file helperavx2.h.
References x, y, and z.
vfmapp_vf_vf_vf_vf()
static INLINE vfloat vfmapp_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 290 of file helperavx2.h.
References x, y, and z.
vge_vo_vd_vd()
static INLINE vopmask vge_vo_vd_vd (vdouble x, vdouble y) static
Definition at line 183 of file helperavx2.h.
References vreinterpret_vm_vd(), x, and y.
vge_vo_vf_vf()
static INLINE vopmask vge_vo_vf_vf (vfloat x, vfloat y) static
Definition at line 301 of file helperavx2.h.
References vreinterpret_vm_vf(), x, and y.
vgt64_vi2_vi2_vi2()
static INLINE vint2 vgt64_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 327 of file helperavx2.h.
References x, and y.
vgt64_vo_vi2_vi2()
static INLINE vopmask vgt64_vo_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 325 of file helperavx2.h.
References x, and y.
Referenced by __attribute__().
vgt64_vo_vm_vm()
static INLINE vopmask vgt64_vo_vm_vm (vmask x, vmask y) static
Definition at line 153 of file helperavx2.h.
References x, and y.
Referenced by __vldexp_manual().
vgt_vi2_vi2_vi2()
static INLINE vint2 vgt_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 322 of file helperavx2.h.
References x, and y.
vgt_vi_vi_vi()
static INLINE vint vgt_vi_vi_vi (vint x, vint y) static
Definition at line 204 of file helperavx2.h.
References x, and y.
vgt_vo_vd_vd()
static INLINE vopmask vgt_vo_vd_vd (vdouble x, vdouble y) static
Definition at line 182 of file helperavx2.h.
References vreinterpret_vm_vd(), x, and y.
Referenced by __attribute__(), __vcis_d_kernel(), and __vexp_d_kernel().
vgt_vo_vf_vf()
static INLINE vopmask vgt_vo_vf_vf (vfloat x, vfloat y) static
Definition at line 300 of file helperavx2.h.
References vreinterpret_vm_vf(), x, and y.
Referenced by __attribute__(), __vcis_kernel(), and __vexp_kernel().
vgt_vo_vi2_vi2()
static INLINE vopmask vgt_vo_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 320 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), __tan_f_vec(), and __vldexpf_manual().
vgt_vo_vi_vi()
static INLINE vopmask vgt_vo_vi_vi (vint x, vint y) static
Definition at line 207 of file helperavx2.h.
References x, and y.
vhi64_vi_vi2()
static INLINE vint vhi64_vi_vi2 (vint2 x) static
Definition at line 448 of file helperavx2.h.
References x.
Referenced by __attribute__().
visinf_vo_vd()
static INLINE vopmask visinf_vo_vd (vdouble d) static
Definition at line 226 of file helperavx2.h.
References d, vabs_vd_vd(), and vreinterpret_vm_vd().
visinf_vo_vf()
static INLINE vopmask visinf_vo_vf (vfloat d) static
Definition at line 349 of file helperavx2.h.
References d, vabs_vf_vf(), vcast_vf_f(), and veq_vo_vf_vf().
visminf_vo_vd()
static INLINE vopmask visminf_vo_vd (vdouble d) static
Definition at line 234 of file helperavx2.h.
References d, and vreinterpret_vm_vd().
visminf_vo_vf()
static INLINE vopmask visminf_vo_vf (vfloat d) static
Definition at line 351 of file helperavx2.h.
References d, vcast_vf_f(), and veq_vo_vf_vf().
visnan_vo_vd()
static INLINE vopmask visnan_vo_vd (vdouble d) static
Definition at line 238 of file helperavx2.h.
References d, and vreinterpret_vm_vd().
visnan_vo_vf()
static INLINE vopmask visnan_vo_vf (vfloat d) static
Definition at line 352 of file helperavx2.h.
References d, and vneq_vo_vf_vf().
vispinf_vo_vd()
static INLINE vopmask vispinf_vo_vd (vdouble d) static
Definition at line 230 of file helperavx2.h.
References d, and vreinterpret_vm_vd().
vispinf_vo_vf()
static INLINE vopmask vispinf_vo_vf (vfloat d) static
Definition at line 350 of file helperavx2.h.
References d, vcast_vf_f(), and veq_vo_vf_vf().
vle_vo_vd_vd()
static INLINE vopmask vle_vo_vd_vd (vdouble x, vdouble y) static
Definition at line 180 of file helperavx2.h.
References vreinterpret_vm_vd(), x, and y.
Referenced by __vexp_d_kernel().
vle_vo_vf_vf()
static INLINE vopmask vle_vo_vf_vf (vfloat x, vfloat y) static
Definition at line 298 of file helperavx2.h.
References vreinterpret_vm_vf(), x, and y.
Referenced by __vexp_kernel().
vload_vd_p()
static INLINE vdouble vload_vd_p (const double * ptr) static
Definition at line 253 of file helperavx2.h.
vload_vf_p()
static INLINE vfloat vload_vf_p (const float * ptr) static
Definition at line 363 of file helperavx2.h.
vloadu_vd_p()
static INLINE vdouble vloadu_vd_p (const double * ptr) static
Definition at line 254 of file helperavx2.h.
vloadu_vf_p()
static INLINE vfloat vloadu_vf_p (const float * ptr) static
Definition at line 364 of file helperavx2.h.
vloadu_vi2_p()
static vint2 vloadu_vi2_p (int32_t * p) static
Definition at line 93 of file helperavx2.h.
References p.
vloadu_vi_p()
static vint vloadu_vi_p (int32_t * p) static
Definition at line 95 of file helperavx2.h.
References p.
vlt_vo_vd_vd()
static INLINE vopmask vlt_vo_vd_vd (vdouble x, vdouble y) static
Definition at line 179 of file helperavx2.h.
References vreinterpret_vm_vd(), x, and y.
vlt_vo_vf_vf()
static INLINE vopmask vlt_vo_vf_vf (vfloat x, vfloat y) static
Definition at line 297 of file helperavx2.h.
References vreinterpret_vm_vf(), x, and y.
vmax_vd_vd_vd()
static INLINE vdouble vmax_vd_vd_vd (vdouble x, vdouble y) static
Definition at line 168 of file helperavx2.h.
References x, and y.
vmax_vf_vf_vf()
static INLINE vfloat vmax_vf_vf_vf (vfloat x, vfloat y) static
Definition at line 286 of file helperavx2.h.
References x, and y.
vmin_vd_vd_vd()
static INLINE vdouble vmin_vd_vd_vd (vdouble x, vdouble y) static
Definition at line 169 of file helperavx2.h.
References x, and y.
vmin_vf_vf_vf()
static INLINE vfloat vmin_vf_vf_vf (vfloat x, vfloat y) static
Definition at line 287 of file helperavx2.h.
References x, and y.
vmla_vd_vd_vd_vd()
static INLINE vdouble vmla_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 165 of file helperavx2.h.
References x, y, and z.
Referenced by vmlsubadd_vd_vd_vd_vd().
vmla_vf_vf_vf_vf()
static INLINE vfloat vmla_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 283 of file helperavx2.h.
References x, y, and z.
Referenced by vmlsubadd_vf_vf_vf_vf().
vmlanp_vd_vd_vd_vd()
static INLINE vdouble vmlanp_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 167 of file helperavx2.h.
References x, y, and z.
vmlanp_vf_vf_vf_vf()
static INLINE vfloat vmlanp_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 285 of file helperavx2.h.
References x, y, and z.
vmlapn_vd_vd_vd_vd()
static INLINE vdouble vmlapn_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 166 of file helperavx2.h.
References x, y, and z.
vmlapn_vf_vf_vf_vf()
static INLINE vfloat vmlapn_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 284 of file helperavx2.h.
References x, y, and z.
vmlsubadd_vd_vd_vd_vd()
static INLINE vdouble vmlsubadd_vd_vd_vd_vd (vdouble x, vdouble y, vdouble z) static
Definition at line 384 of file helperavx2.h.
References vmla_vd_vd_vd_vd(), vnegpos_vd_vd(), x, y, and z.
vmlsubadd_vf_vf_vf_vf()
static INLINE vfloat vmlsubadd_vf_vf_vf_vf (vfloat x, vfloat y, vfloat z) static
Definition at line 385 of file helperavx2.h.
References vmla_vf_vf_vf_vf(), vnegpos_vf_vf(), x, y, and z.
vmovehdup_vd_vd()
static INLINE vdouble vmovehdup_vd_vd (vdouble d0) static
Definition at line 409 of file helperavx2.h.
Referenced by cexp_vec().
vmovehdup_vf_vf()
static INLINE vfloat vmovehdup_vf_vf (vfloat d0) static
Definition at line 406 of file helperavx2.h.
Referenced by cexpf_vec().
vmoveldup_vd_vd()
static INLINE vdouble vmoveldup_vd_vd (vdouble d0) static
Definition at line 408 of file helperavx2.h.
Referenced by cexp_vec().
vmoveldup_vf_vf()
static INLINE vfloat vmoveldup_vf_vf (vfloat d0) static
Definition at line 405 of file helperavx2.h.
Referenced by cexpf_vec().
vmul_vd_vd_vd()
static INLINE vdouble vmul_vd_vd_vd (vdouble x, vdouble y) static
Definition at line 159 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), __vcis_d_kernel(), __vexp_d_kernel(), __vexp_d_poly(), __vldexp_manual(), cexp_vec(), and vfast2mul_dp().
vmul_vf_vf_vf()
static INLINE vfloat vmul_vf_vf_vf (vfloat x, vfloat y) static
Definition at line 277 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), __tan_f_vec(), __tan_kernel(), __vcis_kernel(), __vexp_kernel(), __vldexpf_manual(), cexpf_vec(), and vfast2mul().
vmulu_vi2_vi2_vi2()
static INLINE vint2 vmulu_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 430 of file helperavx2.h.
References x, and y.
Referenced by __reduction_slowpath().
vneg_vd_vd()
static INLINE vdouble vneg_vd_vd (vdouble d) static
Definition at line 164 of file helperavx2.h.
References d.
vneg_vf_vf()
static INLINE vfloat vneg_vf_vf (vfloat d) static
Definition at line 282 of file helperavx2.h.
References d, vcast_vf_f(), vreinterpret_vf_vm(), vreinterpret_vm_vf(), and vxor_vm_vm_vm().
vneg_vi2_vi2()
static INLINE vint2 vneg_vi2_vi2 (vint2 e) static
Definition at line 305 of file helperavx2.h.
References e, vcast_vi2_i(), and vsub_vi2_vi2_vi2().
vneg_vi_vi()
static INLINE vint vneg_vi_vi (vint e) static
Definition at line 189 of file helperavx2.h.
References e, vcast_vi_i(), and vsub_vi_vi_vi().
vnegpos_vd_vd()
static INLINE vdouble vnegpos_vd_vd (vdouble d) static
Definition at line 377 of file helperavx2.h.
References d, NPMASK, vreinterpret_vd_vm(), vreinterpret_vm_vd(), and vxor_vm_vm_vm().
Referenced by vmlsubadd_vd_vd_vd_vd().
vnegpos_vf_vf()
static INLINE vfloat vnegpos_vf_vf (vfloat d) static
Definition at line 379 of file helperavx2.h.
References d, NPMASKf, vreinterpret_vf_vm(), vreinterpret_vm_vf(), and vxor_vm_vm_vm().
Referenced by vmlsubadd_vf_vf_vf_vf().
vneq_vo_vd_vd()
static INLINE vopmask vneq_vo_vd_vd (vdouble x, vdouble y) static
Definition at line 178 of file helperavx2.h.
References vreinterpret_vm_vd(), x, and y.
Referenced by __attribute__().
vneq_vo_vf_vf()
static INLINE vopmask vneq_vo_vf_vf (vfloat x, vfloat y) static
Definition at line 296 of file helperavx2.h.
References vreinterpret_vm_vf(), x, and y.
Referenced by __attribute__(), and visnan_vo_vf().
vnlt_vo_vd_vd()
static INLINE vopmask vnlt_vo_vd_vd (vdouble x, vdouble y) static
Definition at line 181 of file helperavx2.h.
References vreinterpret_vm_vd(), x, and y.
vnlt_vo_vf_vf()
static INLINE vopmask vnlt_vo_vf_vf (vfloat x, vfloat y) static
Definition at line 299 of file helperavx2.h.
References vreinterpret_vm_vf(), x, and y.
vor_vi2_vi2_vi2()
static INLINE vint2 vor_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 309 of file helperavx2.h.
References x, and y.
Referenced by __reduction_slowpath(), __vcis_d_kernel(), __vcis_kernel(), __vldexp_manual(), __vldexpf_manual(), cexp_vec(), and cexpf_vec().
vor_vi_vi_vi()
static INLINE vint vor_vi_vi_vi (vint x, vint y) static
Definition at line 193 of file helperavx2.h.
References x, and y.
vor_vm_vm_vm()
static INLINE vmask vor_vm_vm_vm (vmask x, vmask y) static
Definition at line 102 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.
Referenced by __attribute__().
vor_vm_vo32_vm()
static INLINE vmask vor_vm_vo32_vm (vopmask x, vmask y) static
Definition at line 117 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.
vor_vm_vo64_vm()
static INLINE vmask vor_vm_vo64_vm (vopmask x, vmask y) static
Definition at line 112 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.
vor_vo_vo_vo()
static INLINE vopmask vor_vo_vo_vo (vopmask x, vopmask y) static
Definition at line 107 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.
Referenced by __vldexp_manual(), and __vldexpf_manual().
vposneg_vd_vd()
static INLINE vdouble vposneg_vd_vd (vdouble d) static
Definition at line 376 of file helperavx2.h.
References d, PNMASK, vreinterpret_vd_vm(), vreinterpret_vm_vd(), and vxor_vm_vm_vm().
vposneg_vf_vf()
static INLINE vfloat vposneg_vf_vf (vfloat d) static
Definition at line 378 of file helperavx2.h.
References d, PNMASKf, vreinterpret_vf_vm(), vreinterpret_vm_vf(), and vxor_vm_vm_vm().
vprefetch_v_p()
static INLINE void vprefetch_v_p (const char * ptr) static
Definition at line 73 of file helperavx2.h.
vrec_vd_vd()
static INLINE vdouble vrec_vd_vd (vdouble x) static
Definition at line 161 of file helperavx2.h.
References x.
vrec_vf_vf()
static INLINE vfloat vrec_vf_vf (vfloat x) static
Definition at line 279 of file helperavx2.h.
References vcast_vf_f(), vdiv_vf_vf_vf(), and x.
vreinterpret_vd_vi2()
static INLINE vdouble vreinterpret_vd_vi2 (vint2 vi) static
Definition at line 89 of file helperavx2.h.
vreinterpret_vd_vm()
static INLINE vdouble vreinterpret_vd_vm (vmask vm) static
Definition at line 87 of file helperavx2.h.
Referenced by __attribute__(), vand_vm_vm_vm(), vand_vm_vo32_vm(), vand_vm_vo64_vm(), vand_vo_vo_vo(), vandnot_vm_vm_vm(), vandnot_vm_vo32_vm(), vandnot_vm_vo64_vm(), vandnot_vo_vo_vo(), vnegpos_vd_vd(), vor_vm_vm_vm(), vor_vm_vo32_vm(), vor_vm_vo64_vm(), vor_vo_vo_vo(), vposneg_vd_vd(), vxor_vm_vm_vm(), vxor_vm_vo32_vm(), vxor_vm_vo64_vm(), and vxor_vo_vo_vo().
vreinterpret_vf_vi2()
static INLINE vfloat vreinterpret_vf_vi2 (vint2 vi) static
Definition at line 272 of file helperavx2.h.
References vcast_vm_vi2(), and vreinterpret_vf_vm().
vreinterpret_vf_vm()
static INLINE vfloat vreinterpret_vf_vm (vmask vm) static
Definition at line 270 of file helperavx2.h.
Referenced by __attribute__(), vabs_vf_vf(), vneg_vf_vf(), vnegpos_vf_vf(), vposneg_vf_vf(), and vreinterpret_vf_vi2().
vreinterpret_vi2_vd()
static INLINE vint2 vreinterpret_vi2_vd (vdouble vd) static
Definition at line 88 of file helperavx2.h.
vreinterpret_vi2_vf()
static INLINE vint2 vreinterpret_vi2_vf (vfloat vf) static
Definition at line 273 of file helperavx2.h.
References vcast_vi2_vm(), and vreinterpret_vm_vf().
vreinterpret_vm_vd()
static INLINE vmask vreinterpret_vm_vd (vdouble vd) static
Definition at line 86 of file helperavx2.h.
Referenced by __attribute__(), vand_vm_vm_vm(), vand_vm_vo32_vm(), vand_vm_vo64_vm(), vand_vo_vo_vo(), vandnot_vm_vm_vm(), vandnot_vm_vo32_vm(), vandnot_vm_vo64_vm(), vandnot_vo_vo_vo(), veq_vo_vd_vd(), vge_vo_vd_vd(), vgt_vo_vd_vd(), visinf_vo_vd(), visminf_vo_vd(), visnan_vo_vd(), vispinf_vo_vd(), vle_vo_vd_vd(), vlt_vo_vd_vd(), vnegpos_vd_vd(), vneq_vo_vd_vd(), vnlt_vo_vd_vd(), vor_vm_vm_vm(), vor_vm_vo32_vm(), vor_vm_vo64_vm(), vor_vo_vo_vo(), vposneg_vd_vd(), vxor_vm_vm_vm(), vxor_vm_vo32_vm(), vxor_vm_vo64_vm(), and vxor_vo_vo_vo().
vreinterpret_vm_vf()
static INLINE vmask vreinterpret_vm_vf (vfloat vf) static
Definition at line 269 of file helperavx2.h.
Referenced by __attribute__(), vabs_vf_vf(), veq_vo_vf_vf(), vge_vo_vf_vf(), vgt_vo_vf_vf(), vle_vo_vf_vf(), vlt_vo_vf_vf(), vneg_vf_vf(), vnegpos_vf_vf(), vneq_vo_vf_vf(), vnlt_vo_vf_vf(), vposneg_vf_vf(), and vreinterpret_vi2_vf().
vrev21_vd_vd()
static INLINE vdouble vrev21_vd_vd (vdouble d0) static
Definition at line 387 of file helperavx2.h.
Referenced by __vcis_d_kernel().
vrev21_vf_vf()
static INLINE vfloat vrev21_vf_vf (vfloat d0) static
Definition at line 403 of file helperavx2.h.
Referenced by __vcis_kernel().
vreva2_vd_vd()
static INLINE vdouble vreva2_vd_vd (vdouble d0) static
Definition at line 388 of file helperavx2.h.
vreva2_vf_vf()
static INLINE vfloat vreva2_vf_vf (vfloat d0) static
Definition at line 404 of file helperavx2.h.
vrint_vd_vd()
static INLINE vdouble vrint_vd_vd (vdouble vd) static
Definition at line 132 of file helperavx2.h.
vrint_vf_vf()
static INLINE vfloat vrint_vf_vf (vfloat vd) static
Definition at line 133 of file helperavx2.h.
vrint_vi2_vf()
static INLINE vint2 vrint_vi2_vf (vfloat vf) static
Definition at line 264 of file helperavx2.h.
References vcast_vi2_vm().
vrint_vi_vd()
static INLINE vint vrint_vi_vd (vdouble vd) static
Definition at line 130 of file helperavx2.h.
vscatter2_v_p_i_i_vd()
static INLINE void vscatter2_v_p_i_i_vd (double * ptr, int offset, int step, vdouble v) static
Definition at line 391 of file helperavx2.h.
References offset.
vscatter2_v_p_i_i_vf()
static INLINE void vscatter2_v_p_i_i_vf (float * ptr, int offset, int step, vfloat v) static
Definition at line 413 of file helperavx2.h.
References offset.
Referenced by vsscatter2_v_p_i_i_vf().
vsel_vd_vo_d_d()
static INLINE vdouble vsel_vd_vo_d_d (vopmask o, double v1, double v0) static
Definition at line 212 of file helperavx2.h.
vsel_vd_vo_vd_vd()
static INLINE vdouble vsel_vd_vo_vd_vd (vopmask o, vdouble x, vdouble y) static
Definition at line 211 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), __vcis_d_kernel(), __vexp_d_kernel(), cexp_vec(), and vsel_vd_vo_vo_vo_d_d_d_d().
vsel_vd_vo_vo_d_d_d()
static INLINE vdouble vsel_vd_vo_vo_d_d_d (vopmask o0, vopmask o1, double d0, double d1, double d2) static
Definition at line 222 of file helperavx2.h.
References vsel_vd_vo_vo_vo_d_d_d_d().
vsel_vd_vo_vo_vo_d_d_d_d()
static INLINE vdouble vsel_vd_vo_vo_vo_d_d_d_d (vopmask o0, vopmask o1, vopmask o2, double d0, double d1, double d2, double d3) static
Definition at line 214 of file helperavx2.h.
References vsel_vd_vo_vd_vd().
Referenced by vsel_vd_vo_vo_d_d_d().
vsel_vf_vo_f_f()
static INLINE CONST vfloat vsel_vf_vo_f_f (vopmask o, float v1, float v0) static
Definition at line 337 of file helperavx2.h.
References vcast_vf_f(), and vsel_vf_vo_vf_vf().
Referenced by vsel_vf_vo_vo_f_f_f(), and vsel_vf_vo_vo_vo_f_f_f_f().
vsel_vf_vo_vf_vf()
static INLINE vfloat vsel_vf_vo_vf_vf (vopmask o, vfloat x, vfloat y) static
Definition at line 333 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), __tan_f_vec(), __tan_kernel(), __vcis_kernel(), __vexp_kernel(), cexpf_vec(), vsel_vf_vo_f_f(), vsel_vf_vo_vo_f_f_f(), and vsel_vf_vo_vo_vo_f_f_f_f().
vsel_vf_vo_vo_f_f_f()
static INLINE vfloat vsel_vf_vo_vo_f_f_f (vopmask o0, vopmask o1, float d0, float d1, float d2) static
Definition at line 341 of file helperavx2.h.
References vcast_vf_f(), vsel_vf_vo_f_f(), and vsel_vf_vo_vf_vf().
vsel_vf_vo_vo_vo_f_f_f_f()
static INLINE vfloat vsel_vf_vo_vo_vo_f_f_f_f (vopmask o0, vopmask o1, vopmask o2, float d0, float d1, float d2, float d3) static
Definition at line 345 of file helperavx2.h.
References vcast_vf_f(), vsel_vf_vo_f_f(), and vsel_vf_vo_vf_vf().
vsel_vi2_vo_vi2_vi2()
static INLINE vint2 vsel_vi2_vo_vi2_vi2 (vopmask m, vint2 x, vint2 y) static
Definition at line 329 of file helperavx2.h.
References m, x, and y.
Referenced by __attribute__(), and __reduction_slowpath().
vsel_vi_vo_vi_vi()
static INLINE vint vsel_vi_vo_vi_vi (vopmask m, vint x, vint y) static
Definition at line 209 of file helperavx2.h.
References m, x, and y.
vset_vd_d_d()
static INLINE vdouble vset_vd_d_d (const double hi, const double lo) static
Definition at line 251 of file helperavx2.h.
References hi, and lo.
vsll64_vi2_vi2_i()
static INLINE vint2 vsll64_vi2_vi2_i (vint2 x, int c) static
Definition at line 427 of file helperavx2.h.
References x.
Referenced by __attribute__(), __reduction_slowpath(), __vcis_d_kernel(), and __vldexp_manual().
vsll_vi2_vi2_i()
static INLINE vint2 vsll_vi2_vi2_i (vint2 x, int c) static
Definition at line 315 of file helperavx2.h.
References x.
Referenced by __attribute__(), __reduction_slowpath(), __tan_f_vec(), __vcis_kernel(), __vexp_d_kernel(), __vexp_kernel(), and __vldexpf_manual().
vsll_vi_vi_i()
static INLINE vint vsll_vi_vi_i (vint x, int c) static
Definition at line 199 of file helperavx2.h.
References x.
vsqrt_vd_vd()
static INLINE vdouble vsqrt_vd_vd (vdouble x) static
Definition at line 162 of file helperavx2.h.
References x.
vsqrt_vf_vf()
static INLINE vfloat vsqrt_vf_vf (vfloat x) static
Definition at line 280 of file helperavx2.h.
References x.
vsra_vi2_vi2_i()
static INLINE vint2 vsra_vi2_vi2_i (vint2 x, int c) static
Definition at line 317 of file helperavx2.h.
References x.
Referenced by __attribute__(), __vexp_d_kernel(), and __vexp_kernel().
vsra_vi_vi_i()
static INLINE vint vsra_vi_vi_i (vint x, int c) static
Definition at line 201 of file helperavx2.h.
References x.
Referenced by __attribute__().
vsrl64_vi2_vi2_i()
static INLINE vint2 vsrl64_vi2_vi2_i (vint2 x, int c) static
Definition at line 428 of file helperavx2.h.
References x.
Referenced by __reduction_slowpath(), and __vldexp_manual().
vsrl_vi2_vi2_i()
static INLINE vint2 vsrl_vi2_vi2_i (vint2 x, int c) static
Definition at line 316 of file helperavx2.h.
References x.
Referenced by __reduction_slowpath(), and __vldexpf_manual().
vsrl_vi_vi_i()
static INLINE vint vsrl_vi_vi_i (vint x, int c) static
Definition at line 200 of file helperavx2.h.
References x.
vsscatter2_v_p_i_i_vd()
static INLINE void vsscatter2_v_p_i_i_vd (double * ptr, int offset, int step, vdouble v) static
Definition at line 396 of file helperavx2.h.
References offset.
vsscatter2_v_p_i_i_vf()
static INLINE void vsscatter2_v_p_i_i_vf (float * ptr, int offset, int step, vfloat v) static
Definition at line 420 of file helperavx2.h.
References offset, and vscatter2_v_p_i_i_vf().
vstore_v_p_vd()
static INLINE void vstore_v_p_vd (double * ptr, vdouble v) static
Definition at line 256 of file helperavx2.h.
vstore_v_p_vf()
static INLINE void vstore_v_p_vf (float * ptr, vfloat v) static
Definition at line 366 of file helperavx2.h.
Referenced by __reduction_slowpath().
vstoreu_v_p_vd()
static INLINE void vstoreu_v_p_vd (double * ptr, vdouble v) static
Definition at line 257 of file helperavx2.h.
vstoreu_v_p_vf()
static INLINE void vstoreu_v_p_vf (float * ptr, vfloat v) static
Definition at line 367 of file helperavx2.h.
vstoreu_v_p_vi()
static void vstoreu_v_p_vi (int32_t * p, vint v) static
Definition at line 96 of file helperavx2.h.
References p.
vstoreu_v_p_vi2()
static void vstoreu_v_p_vi2 (int32_t * p, vint2 v) static
Definition at line 94 of file helperavx2.h.
References p.
vstream_v_p_vd()
static INLINE void vstream_v_p_vd (double * ptr, vdouble v) static
Definition at line 390 of file helperavx2.h.
vstream_v_p_vf()
static INLINE void vstream_v_p_vf (float * ptr, vfloat v) static
Definition at line 411 of file helperavx2.h.
vsub64_vi2_vi2_vi2()
static INLINE vint2 vsub64_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 432 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), and __vexp_d_kernel().
vsub_vd_vd_vd()
static INLINE vdouble vsub_vd_vd_vd (vdouble x, vdouble y) static
Definition at line 158 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), __vcis_d_kernel(), __vexp_d_kernel(), and vfast2sum_dp().
vsub_vf_vf_vf()
static INLINE vfloat vsub_vf_vf_vf (vfloat x, vfloat y) static
Definition at line 276 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), __tan_f_vec(), __vcis_kernel(), __vexp_kernel(), and vfast2sum().
vsub_vi2_vi2_vi2()
static INLINE vint2 vsub_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 304 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), __reduction_slowpath(), __vexp_kernel(), and vneg_vi2_vi2().
vsub_vi_vi_vi()
static INLINE vint vsub_vi_vi_vi (vint x, vint y) static
Definition at line 188 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), and vneg_vi_vi().
vsubadd_vd_vd_vd()
static INLINE vdouble vsubadd_vd_vd_vd (vdouble x, vdouble y) static
Definition at line 381 of file helperavx2.h.
References x, and y.
vsubadd_vf_vf_vf()
static INLINE vfloat vsubadd_vf_vf_vf (vfloat x, vfloat y) static
Definition at line 382 of file helperavx2.h.
References x, and y.
vtestallones_i_vo32()
static INLINE int vtestallones_i_vo32 (vopmask g) static
Definition at line 75 of file helperavx2.h.
vtestallones_i_vo64()
static INLINE int vtestallones_i_vo64 (vopmask g) static
Definition at line 79 of file helperavx2.h.
vtestz_i_vf_vf()
static INLINE int vtestz_i_vf_vf (vfloat x, vfloat y) static
Definition at line 422 of file helperavx2.h.
References x, and y.
vtestz_i_vo()
static INLINE int vtestz_i_vo (vopmask x) static
Definition at line 425 of file helperavx2.h.
References x.
Referenced by __attribute__(), __tan_f_vec(), __vcis_d_kernel(), and __vcis_kernel().
vtestz_i_vo_vo()
static INLINE int vtestz_i_vo_vo (vopmask x, vopmask y) static
Definition at line 423 of file helperavx2.h.
References x, and y.
vtruncate_vd_vd()
static INLINE vdouble vtruncate_vd_vd (vdouble vd) static
Definition at line 134 of file helperavx2.h.
vtruncate_vf_vf()
static INLINE vfloat vtruncate_vf_vf (vfloat vf) static
Definition at line 135 of file helperavx2.h.
vtruncate_vi2_vf()
static INLINE vint2 vtruncate_vi2_vf (vfloat vf) static
Definition at line 265 of file helperavx2.h.
References vcast_vi2_vm().
vtruncate_vi_vd()
static INLINE vint vtruncate_vi_vd (vdouble vd) static
Definition at line 131 of file helperavx2.h.
vxor_vi2_vi2_vi2()
static INLINE vint2 vxor_vi2_vi2_vi2 (vint2 x, vint2 y) static
Definition at line 310 of file helperavx2.h.
References x, and y.
Referenced by __attribute__(), __reduction_slowpath(), __vcis_d_kernel(), and __vcis_kernel().
vxor_vi_vi_vi()
static INLINE vint vxor_vi_vi_vi (vint x, vint y) static
Definition at line 194 of file helperavx2.h.
References x, and y.
vxor_vm_vm_vm()
static INLINE vmask vxor_vm_vm_vm (vmask x, vmask y) static
Definition at line 103 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.
Referenced by __attribute__(), vneg_vf_vf(), vnegpos_vd_vd(), vnegpos_vf_vf(), vposneg_vd_vd(), and vposneg_vf_vf().
vxor_vm_vo32_vm()
static INLINE vmask vxor_vm_vo32_vm (vopmask x, vmask y) static
Definition at line 118 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.
vxor_vm_vo64_vm()
static INLINE vmask vxor_vm_vo64_vm (vopmask x, vmask y) static
Definition at line 113 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.
vxor_vo_vo_vo()
static INLINE vopmask vxor_vo_vo_vo (vopmask x, vopmask y) static
Definition at line 108 of file helperavx2.h.
References vreinterpret_vd_vm(), vreinterpret_vm_vd(), x, and y.