flang: hlvect.c File Reference
hlvect.c File Reference
high level vectorization utils
#include "gbldefs.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "dtypeutl.h"
#include "ast.h"
#include "nme.h"
#include "optimize.h"
#include "hlvect.h"
#include "fdirect.h"
#include "ccffinfo.h"
#include "symutl.h"
#include "induc.h"
#include <stdarg.h>
Enumerations
enum {
NO_CAUSE , NEST_CAUSE , CALL_CAUSE , MEXIT_CAUSE ,
PRAGMA_CAUSE , COUNTABLE_CAUSE , COUNT_CAUSE , STMT_CAUSE ,
IN_MASTER , IN_CRITICAL
}
Functions
void dumpnme (int n)
void dumploop (int l)
void unmark_vinduc (int loop)
void mark_vinduc (int loop)
int hlv_getsym (int phase, int type)
void vdel_bih (int bihx)
LOGICAL is_parent_loop (int lpParent, int lpChild)
void dump_memrefs (int start, int cnt)
void dump_vinduc (int start, int cnt)
void dump_vloops (int first, int base)
int hlv_getvsym (int baseDtype)
void dump_memref_hdr (void)
void dump_one_memref (int i)
void dump_memref_list (int base)
void dump_one_vloop (int i, int level)
Variables
HLVECT hlv = {0}
VTMP hlv_temps [VT_PHASES][VT_MAX]
VTMP hlv_vtemps
static int vdel_lst
Detailed Description
high level vectorization utils
Definition in file hlvect.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NO_CAUSE
NEST_CAUSE
CALL_CAUSE
MEXIT_CAUSE
PRAGMA_CAUSE
COUNTABLE_CAUSE
COUNT_CAUSE
STMT_CAUSE
IN_MASTER
IN_CRITICAL
Definition at line 163 of file hlvect.c.
Function Documentation
dump_memref_hdr()
void dump_memref_hdr (void)
Definition at line 385 of file hlvect.c.
References gbl.
Referenced by dump_memref_list(), and dump_memrefs().
dump_memref_list()
void dump_memref_list (int base)
Definition at line 444 of file hlvect.c.
References base, dump_memref_hdr(), dump_one_memref(), and MR_NEXT.
dump_memrefs()
void dump_memrefs (int start, int cnt)
Definition at line 431 of file hlvect.c.
References cnt, dump_memref_hdr(), dump_one_memref(), end, i, and start.
Referenced by build_loop_dd().
dump_one_memref()
void dump_one_memref (int i)
Definition at line 392 of file hlvect.c.
References dump_dd(), dumpname(), gbl, i, MR_ARRAY, MR_BASED, MR_EXP, MR_FG, MR_FSUBS, MR_ILI, MR_ILT, MR_INDIR, MR_INDUC, MR_INVAL, MR_INVAR, MR_INVEC, MR_IVUSE, MR_LOOP, MR_NEST, MR_NME, MR_RG, MR_SCALR, MR_SUBCNT, MR_SUBST, MR_SUCC, MR_TYPE, and printast().
Referenced by dump_memref_list(), and dump_memrefs().
dump_one_vloop()
void dump_one_vloop (int i, int level)
Definition at line 451 of file hlvect.c.
References gbl, i, j, level(), VL_CAND, VL_CHILD, VL_ICNT, VL_ISTART, VL_LBND, VL_LPCNT, VL_MRCNT, VL_MRECNT, VL_MRSTART, VL_NEST, VL_PERF, VL_SIBLING, VL_UBND, and VL_ZTRIP.
Referenced by build_dd(), and dump_vloops().
dump_vinduc()
void dump_vinduc (int start, int cnt)
Definition at line 486 of file hlvect.c.
References basesym_of(), cnt, DBGBIT, end, gbl, getprint(), i, printast(), start, VIND_ALIAS, VIND_DELETE, VIND_INIT, VIND_LOAD, VIND_MIDF, VIND_NIU, VIND_NM, VIND_OPC, VIND_PTR, VIND_SKIP, and VIND_TOTSKIP.
dump_vloops()
void dump_vloops (int first, int base)
Definition at line 475 of file hlvect.c.
References base, dump_one_vloop(), dump_vloops(), first, i, VL_CHILD, and VL_SIBLING.
Referenced by build_dd(), and dump_vloops().
dumploop()
void dumploop (int l)
Definition at line 2140 of file dump.c.
dumpnme()
void dumpnme (int n)
Definition at line 2090 of file dump.c.
hlv_getsym()
int hlv_getsym (int phase, int type)
Definition at line 279 of file hlvect.c.
References hlv_temps, p, sptr, sym_get_scalar(), TRUE, and type.
hlv_getvsym()
int hlv_getvsym (int baseDtype)
Definition at line 292 of file hlvect.c.
References AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_UPAST, AD_UPBD, astb, DT_INT, get_array_dtype(), getsymf(), hlv_vtemps, ASTB::i0, ASTB::i1, VTMP::iavl, VTMP::iavl_max, mk_cval(), VTMP::pfx, sptr, STRIPSIZE, and TRUE.
is_parent_loop()
static LOGICAL is_parent_loop (int lpParent, int lpChild)
Definition at line 4521 of file outconv.c.
References FALSE, lp, LP_PARENT, and TRUE.
mark_vinduc()
void mark_vinduc (int loop)
Definition at line 243 of file hlvect.c.
References end, i, NME_RFPTR, VIND_NM, VL_ICNT, and VL_ISTART.
unmark_vinduc()
void unmark_vinduc (int loop)
Definition at line 254 of file hlvect.c.
References end, i, NME_RFPTR, VIND_NM, VL_ICNT, and VL_ISTART.
vdel_bih()
void vdel_bih (int bihx)
Definition at line 321 of file hlvect.c.
References BIH_RGSET, and vdel_lst.
Variable Documentation
hlv
HLVECT hlv = {0}
Definition at line 137 of file hlvect.c.
Referenced by build_nat_loop(), dd_array_conflict(), dd_succ(), dumpmr(), dumpvind(), dumpvinds(), dumpvloop(), dumpvloops(), dumpvloops2(), dumpvnest(), dumpvnest2(), and fill_subscripts().
hlv_temps
VTMP hlv_temps[VT_PHASES][VT_MAX]
Initial value:
= {
    {
        {0, 0, 0, "ivi", DT_INT4},
        {0, 0, 0, "ivp", DT_CPTR},
    },
    {
        {0, 0, 0, "ndi", DT_INT4},
        {0, 0, 0, "ndp", DT_CPTR},
        {0, 0, 0, "nds", DT_REAL4},
        {0, 0, 0, "ndd", DT_REAL8},
    },
}
Definition at line 143 of file hlvect.c.
Referenced by hlv_getsym().
hlv_vtemps
VTMP hlv_vtemps
Initial value:
= {
    0, 0, 0, "vt", DT_INT4,
}
Definition at line 158 of file hlvect.c.
Referenced by hlv_getvsym().
vdel_lst
int vdel_lst static
Definition at line 176 of file hlvect.c.
Referenced by vdel_bih().