flang: hlvect.h File Reference
hlvect.h File Reference
include file for high-level vectorizer
#include <stdint.h>
Classes
struct VPRAGMAS
struct VLOOP
struct DDEDGE
struct SUBS
struct MEMREF
struct VIND
struct STMT
struct VPSI
struct REGION
struct VTMP
struct SCALAR
struct EXPARR
struct HLVECT
Macros
#define MAX_LOOPS 14
#define VL_LOOP(i) hlv.lpbase[i].lp
#define VL_CHILD(i) hlv.lpbase[i].child
#define VL_SIBLING(i) hlv.lpbase[i].sibling
#define VL_NEST(i) hlv.lpbase[i].nest
#define VL_FLAGS(i) hlv.lpbase[i].flags.all
#define VL_MRSTART(i) hlv.lpbase[i].mrstart
#define VL_MRCNT(i) hlv.lpbase[i].mrcnt
#define VL_MRECNT(i) hlv.lpbase[i].mrecnt
#define VL_ISTART(i) hlv.lpbase[i].istart
#define VL_ICNT(i) hlv.lpbase[i].icnt
#define VL_UBND(i) hlv.lpbase[i].ubnd
#define VL_LBND(i) hlv.lpbase[i].lbnd
#define VL_IUBND(i) hlv.lpbase[i].iubnd
#define VL_AUBND(i) hlv.lpbase[i].aubnd
#define VL_ILBND(i) hlv.lpbase[i].ilbnd
#define VL_ALBND(i) hlv.lpbase[i].albnd
#define VL_LPCNT(i) hlv.lpbase[i].lpcnt
#define VL_SCLIST(i) hlv.lpbase[i].sclist
#define VL_EALIST(i) hlv.lpbase[i].ealist
#define VL_PREBIH(i) hlv.lpbase[i].prebih
#define VL_EXITBIH(i) hlv.lpbase[i].exitbih
#define VL_IVLIST(i) hlv.lpbase[i].ivlist
#define VL_PRAGMAS(i) hlv.lpbase[i].pragmas
#define VLP_DEPCHK(i) hlv.lpbase[i].pragmas.depchk
#define VLP_ASSOC(i) hlv.lpbase[i].pragmas.assoc
#define VLP_EQVCHK(i) hlv.lpbase[i].pragmas.eqvchk
#define VLP_LSTVAL(i) hlv.lpbase[i].pragmas.lstval
#define VLP_RECOG(i) hlv.lpbase[i].pragmas.recog
#define VLP_TRANS(i) hlv.lpbase[i].pragmas.trans
#define VLP_SAFECALL(i) hlv.lpbase[i].pragmas.safecall
#define VLP_SHORTLP(i) hlv.lpbase[i].pragmas.shortloop
#define VLP_MINCNT(i) hlv.lpbase[i].pragmas.mincnt
#define VLP_LDSTSPLIT(i) hlv.lpbase[i].pragmas.ldstsplit
#define VLP_OPSPLIT(i) hlv.lpbase[i].pragmas.opsplit
#define VP_DEPCHK(i) i.depchk
#define VP_ASSOC(i) i.assoc
#define VP_EQVCHK(i) i.eqvchk
#define VP_LSTVAL(i) i.lstval
#define VP_RECOG(i) i.recog
#define VP_TRANS(i) i.trans
#define VP_SAFECALL(i) i.safecall
#define VP_SHORTLP(i) i.shortloop
#define VP_MINCNT(i) i.mincnt
#define VP_LDSTSPLIT(i) i.ldstsplit
#define VP_OPSPLIT(i) i.opsplit
#define VL_CAND(i) hlv.lpbase[i].flags.bits.cand
#define VL_PERF(i) hlv.lpbase[i].flags.bits.perf
#define VL_DEL(i) hlv.lpbase[i].flags.bits.del
#define VL_ZTRIP(i) hlv.lpbase[i].flags.bits.ztrip
#define DIRV_ENTSIZ 4
#define DIRV_ENTMSK (DIRVEC)15
#define DIRV_ENTRYG(dirv, idx) (((dirv) >> ((idx)*DIRV_ENTSIZ)) & DIRV_ENTMSK)
#define DIRV_ENTRYP(dirv, idx, dirent) ((dirv) |= ((dirent & DIRV_ENTMSK) << ((idx)*DIRV_ENTSIZ)))
#define DIRV_ENTRYC(dirv, idx) ((dirv) &= ~(DIRV_ENTMSK << ((idx)*DIRV_ENTSIZ)))
#define DIRV_ALLEQ ((DIRVEC)0x8000000000000000L)
#define DIRV_MASK ((DIRVEC)0x0FFFFFFFFFFFFFFFL)
#define DIRV_LT (DIRVEC)1L
#define DIRV_EQ (DIRVEC)2L
#define DIRV_GT (DIRVEC)4L
#define DIRV_RD (DIRVEC)8L
#define DIRV_NONE (DIRVEC)0L
#define DIRV_STAR (DIRV_LT | DIRV_EQ | DIRV_GT)
#define DIRV_DIRPART(dirv) ((dirv) & (DIRV_MASK))
#define DIRV_INFOPART(dirv) ((dirv) & ~(DIRV_MASK))
#define HLV_AREA 10
#define HLV_AREA1 11
#define DD_SINK(p) (p)->sink
#define DD_DIRVEC(p) (p)->dirvec
#define DD_FLAGS(p) (p)->flags.all
#define DD_NEXT(p) (p)->next
#define DIRV_FFLOW 0
#define DIRV_FANTI 1
#define DIRV_FOUT 2
#define DD_TYPE(i) (i)->flags.bits.type
#define DIRV_BIGPOS (MAX_LOOPS + 1)
#define SB_STOP(i) hlv.subbase[i].flags.bits.stop
#define SB_PTR(i) hlv.subbase[i].flags.bits.ptr
#define SB_IVUSE(i) hlv.subbase[i].flags.bits.ivuse
#define SB_BASE(i) hlv.subbase[i].bases[0]
#define SB_BASES(i) hlv.subbase[i].bases
#define SB_STRIDE(i) hlv.subbase[i].stride
#define MR_ILI(i) hlv.mrbase[i].ili
#define MR_ILT(i) hlv.mrbase[i].ilt
#define MR_FG(i) hlv.mrbase[i].fg
#define MR_NME(i) hlv.mrbase[i].nme
#define MR_STMT(i) hlv.mrbase[i].stmt
#define MR_TYPE(i) hlv.mrbase[i].type
#define MR_NEST(i) hlv.mrbase[i].nest
#define MR_FLAGS(i) hlv.mrbase[i].flags.all
#define MR_SUBST(i) hlv.mrbase[i].subst
#define MR_SUBCNT(i) hlv.mrbase[i].subcnt
#define MR_LOOP(i) hlv.mrbase[i].loop
#define MR_RG(i) hlv.mrbase[i].rg
#define MR_SUCC(i) hlv.mrbase[i].succ
#define MR_FSUBS(i) hlv.mrbase[i].fsubs
#define MR_CSEILI(i) hlv.mrbase[i].cseili
#define MR_NEXT(i) hlv.mrbase[i].next
#define MR_PREV(i) hlv.mrbase[i].prev
#define MR_IV(i) hlv.mrbase[i].iv
#define MR_SCLR(i) hlv.mrbase[i].iv
#define MR_EXPARR(i) hlv.mrbase[i].iv
#define MR_REWR(i) hlv.mrbase[i].rewr
#define MR_IVUSE(i) hlv.mrbase[i].flags.bits.ivuse
#define MR_ARRAY(i) hlv.mrbase[i].flags.bits.array
#define MR_INDIR(i) hlv.mrbase[i].flags.bits.indir
#define MR_SCALR(i) hlv.mrbase[i].flags.bits.scalr
#define MR_BASED(i) hlv.mrbase[i].flags.bits.based
#define MR_EXP(i) hlv.mrbase[i].flags.bits.exp
#define MR_INVAL(i) hlv.mrbase[i].flags.bits.inval
#define MR_INIT(i) hlv.mrbase[i].flags.bits.init
#define MR_INDUC(i) hlv.mrbase[i].flags.bits.induc
#define MR_INVAR(i) hlv.mrbase[i].flags.bits.invar
#define MR_INVEC(i) hlv.mrbase[i].flags.bits.invec
#define VIND_NM(i) hlv.indbase[i].nm
#define VIND_LOAD(i) hlv.indbase[i].load
#define VIND_INIT(i) hlv.indbase[i].init
#define VIND_ORIGINIT(i) hlv.indbase[i].originit
#define VIND_PTR(i) hlv.indbase[i].flags.bits.ptr
#define VIND_DELETE(i) hlv.indbase[i].flags.bits.delete
#define VIND_NIU(i) hlv.indbase[i].flags.bits.niu
#define VIND_MIDF(i) hlv.indbase[i].flags.bits.midf
#define VIND_ALIAS(i) hlv.indbase[i].flags.bits.alias
#define VIND_NOINV(i) hlv.indbase[i].flags.bits.noinv
#define VIND_OMIT(i) hlv.indbase[i].flags.bits.omit
#define VIND_VISIT(i) hlv.indbase[i].flags.bits.visit
#define VIND_ALAST(i) hlv.indbase[i].flags.bits.alast
#define VIND_SAVE(i) hlv.indbase[i].flags.bits.save
#define VIND_OPC(i) hlv.indbase[i].opc
#define VIND_TOTSKIP(i) hlv.indbase[i].totskip
#define VIND_SKIP(i) hlv.indbase[i].skip
#define ST_ILT(i) hlv.stbase[i].ilt
#define ST_MRLIST(i) hlv.stbase[i].mrlist
#define ST_NEXT(i) hlv.stbase[i].next
#define ST_PREV(i) hlv.stbase[i].prev
#define ST_FLAG(i) hlv.stbase[i].flag
#define ST_REDUC(i) hlv.stbase[i].flags.bits.reduc
#define RG_NEXT(i) hlv.rgbase[i].next
#define RG_PREV(i) hlv.rgbase[i].prev
#define RG_OUTER(i) hlv.rgbase[i].outer
#define RG_INNER(i) hlv.rgbase[i].inner
#define RG_ORIG(i) hlv.rgbase[i].orig
#define RG_SLIST(i) hlv.rgbase[i].slist
#define RG_NODENUM(i) hlv.rgbase[i].nodenum
#define RG_STRIPLEN(i) hlv.rgbase[i].nodenum
#define RG_CYCLE(i) hlv.rgbase[i].cycle
#define RG_NEST(i) hlv.rgbase[i].nest
#define RG_ORIGNEST(i) hlv.rgbase[i].orignest
#define RG_TOP(i) hlv.rgbase[i].top
#define RG_ZTRIP(i) hlv.rgbase[i].ztrip
#define RG_CNT(i) hlv.rgbase[i].cnt
#define RG_SUCC(i) hlv.rgbase[i].succ
#define RG_FLAGS(i) hlv.rgbase[i].flags.all
#define RG_BIH(i) hlv.rgbase[i].bih
#define RG_BIHHD(i) hlv.rgbase[i].bih
#define RG_BIHTL(i) hlv.rgbase[i].bihtl
#define RG_BIHAFTER(i) hlv.rgbase[i].bihafter
#define RG_LLVI(i) hlv.rgbase[i].llvi
#define RG_SLBND(i) hlv.rgbase[i].slbnd
#define RG_SUBND(i) hlv.rgbase[i].subnd
#define RG_LBND(i) hlv.rgbase[i].ilbnd
#define RG_UBND(i) hlv.rgbase[i].iubnd
#define RG_MIV(i) hlv.rgbase[i].miv
#define RG_MREG(i) hlv.rgbase[i].mreg
#define RG_MIVSTORE(i) hlv.rgbase[i].miv_store
#define RG_CNTLOAD(i) hlv.rgbase[i].cnt_load
#define RG_CIF(i) hlv.rgbase[i].flags.bits.cif
#define RG_MARKED(i) hlv.rgbase[i].flags.bits.marked
#define RG_RECURRENCE(i) hlv.rgbase[i].flags.bits.recurrence
#define RG_SELF(i) hlv.rgbase[i].flags.bits.self
#define RG_STRIP(i) hlv.rgbase[i].flags.bits.strip
#define RG_BLOCK(i) hlv.rgbase[i].flags.bits.block
#define RG_PARALLEL(i) hlv.rgbase[i].flags.bits.parallel
#define RG_CALL(i) hlv.rgbase[i].flags.bits.call
#define RG_LABEL(i) hlv.rgbase[i].label
#define RG_BLOCKRG(i) hlv.rgbase[i].blockrg
#define VT_INT 0 /* integer temp */
#define VT_PTR 1 /* pointer temp */
#define VT_SP 2 /* single precision */
#define VT_DP 3 /* double precision */
#define VT_MAX 4
#define VT_PHINIT 0 /* initial value phase */
#define VT_PHIND 1 /* induction phase */
#define VT_PHASES 2 /* number of phases of temps */
#define SCLR_NME(i) hlv.scbase[i].nme
#define SCLR_NEXT(i) hlv.scbase[i].next
#define SCLR_FLAG(i) hlv.scbase[i].flags.bits.flag
#define SCLR_SPAN(i) hlv.scbase[i].flags.bits.span
#define SCLR_ARRSYM(i) hlv.scbase[i].arrsym
#define SCLR_MASKSYM(i) hlv.scbase[i].masksym
#define LOOPMASKG(m, i) ((m >> i) & 1)
#define LOOPMASKC(m, i) (m &= ~(1 << i))
#define LOOPMASKS(m, i) (m |= (1 << i))
#define EXPARR_NEST(e) hlv.eabase[e].nest
#define EXPARR_INVLOOPS(e) hlv.eabase[e].invloops
#define EXPARR_TMPSYM(e) hlv.eabase[e].tmpsym
#define EXPARR_NEXT(e) hlv.eabase[e].next
#define EXPARR_LASTVAL(e) hlv.eabase[e].flags.bits.lastval
#define EXPARR_UNIQUESECN(e) hlv.eabase[e].flags.bits.uniquesecn
#define STRIPSIZE 1024
Typedefs
typedef BIGUINT64 DIRVEC
typedef struct DDEDGE DDEDGE
typedef struct VPSI VPSI
typedef struct VPSI * VPSI_P
typedef UINT16 LOOPMASK
Functions
void vect_flg_defaults (void)
void vectorize (void)
void mark_vinduc (int loop)
void unmark_vinduc (int loop)
int hlv_getsym (int phase, int type)
int hlv_getvsym (int baseDtype)
void vdel_bih (int bihx)
void open_vpragma (int lp)
LOGICAL is_parent_loop (int lpParent, int lpChild)
void build_dd (int loop)
Build the data dependency graph.
void dd_edge (int src, int sink, DIRVEC vec)
DIRVEC dirv_inverse (DIRVEC vec)
Invert a direction vector.
DIRVEC dirv_fulldep (int level)
Generate full dependence at a given level.
DIRVEC dirv_exo (int level, int flag)
Generate legal execution order direction vectors.
int dirv_chkzero (DIRVEC dir, int n)
void dirv_gen (DIRVEC dir, int *map, int nest, int ig, void(*f)(DIRVEC))
LOGICAL dd_array_conflict (int astliTriples, int astArrSrc, int astArrSink, int bSinkAfterSrc)
Return TRUE if there is a forward dependence from astArrSrc (the source) to astArrSink (the sink) within an iteration space described by a triplet list beginning at astliTriples.
int dd_symbolic (int il)
Perform symbolic algebraic simplification of term il.
void hlvtrans (int loop)
void regmark (int rg, int rgm, int flag)
int remove_accum (int astx, int subast, int optype)
int is_perfect (int rg)
int get_generic_minmax (int optype)
double score_loop_i860 (int *a)
double score_loop_sparc (int *a)
double score_loop_vpu (int *a)
double score_loop_hpf (int *a)
LOGICAL has_reduction (int rg, int *map, int nest)
void vpar (void)
void llvect (void)
void gen_llinfo (int reg)
void reg_parmark (int rg)
LOGICAL has_recurrence (int rg, int nest, int *mapx, int *mapy)
int parmethod (int rg, int nest, int *mapx, int *mapy)
Variables
VTMP hlv_temps [VT_PHASES][VT_MAX]
VTMP hlv_vtemps
HLVECT hlv
Detailed Description
include file for high-level vectorizer
Definition in file hlvect.h.
Macro Definition Documentation
DD_DIRVEC
#define DD_DIRVEC (p) (p)->dirvec
Definition at line 190 of file hlvect.h.
DD_FLAGS
#define DD_FLAGS (p) (p)->flags.all
Definition at line 191 of file hlvect.h.
DD_NEXT
#define DD_NEXT (p) (p)->next
Definition at line 192 of file hlvect.h.
DD_SINK
#define DD_SINK (p) (p)->sink
Definition at line 189 of file hlvect.h.
DD_TYPE
#define DD_TYPE (i) (i)->flags.bits.type
Definition at line 198 of file hlvect.h.
DIRV_ALLEQ
#define DIRV_ALLEQ ((DIRVEC)0x8000000000000000L)
Definition at line 148 of file hlvect.h.
DIRV_BIGPOS
#define DIRV_BIGPOS (MAX_LOOPS + 1)
Definition at line 201 of file hlvect.h.
DIRV_DIRPART
#define DIRV_DIRPART (dirv) ((dirv) & (DIRV_MASK))
Definition at line 165 of file hlvect.h.
DIRV_ENTMSK
#define DIRV_ENTMSK (DIRVEC)15
Definition at line 138 of file hlvect.h.
DIRV_ENTRYC
#define DIRV_ENTRYC (dirv, idx) ((dirv) &= ~(DIRV_ENTMSK << ((idx)*DIRV_ENTSIZ)))
Definition at line 146 of file hlvect.h.
DIRV_ENTRYG
#define DIRV_ENTRYG (dirv, idx) (((dirv) >> ((idx)*DIRV_ENTSIZ)) & DIRV_ENTMSK)
Definition at line 141 of file hlvect.h.
DIRV_ENTRYP
#define DIRV_ENTRYP (dirv, idx, dirent) ((dirv) |= ((dirent & DIRV_ENTMSK) << ((idx)*DIRV_ENTSIZ)))
Definition at line 143 of file hlvect.h.
DIRV_ENTSIZ
#define DIRV_ENTSIZ 4
Definition at line 137 of file hlvect.h.
DIRV_EQ
#define DIRV_EQ (DIRVEC)2L
Definition at line 155 of file hlvect.h.
DIRV_FANTI
#define DIRV_FANTI 1
Definition at line 195 of file hlvect.h.
DIRV_FFLOW
#define DIRV_FFLOW 0
Definition at line 194 of file hlvect.h.
DIRV_FOUT
#define DIRV_FOUT 2
Definition at line 196 of file hlvect.h.
DIRV_GT
#define DIRV_GT (DIRVEC)4L
Definition at line 156 of file hlvect.h.
DIRV_INFOPART
#define DIRV_INFOPART (dirv) ((dirv) & ~(DIRV_MASK))
Definition at line 166 of file hlvect.h.
DIRV_LT
#define DIRV_LT (DIRVEC)1L
Definition at line 154 of file hlvect.h.
DIRV_MASK
#define DIRV_MASK ((DIRVEC)0x0FFFFFFFFFFFFFFFL)
Definition at line 149 of file hlvect.h.
DIRV_NONE
#define DIRV_NONE (DIRVEC)0L
Definition at line 158 of file hlvect.h.
DIRV_RD
#define DIRV_RD (DIRVEC)8L
Definition at line 157 of file hlvect.h.
DIRV_STAR
#define DIRV_STAR (DIRV_LT | DIRV_EQ | DIRV_GT)
Definition at line 160 of file hlvect.h.
EXPARR_INVLOOPS
#define EXPARR_INVLOOPS (e) hlv.eabase[e].invloops
Definition at line 554 of file hlvect.h.
EXPARR_LASTVAL
#define EXPARR_LASTVAL (e) hlv.eabase[e].flags.bits.lastval
Definition at line 557 of file hlvect.h.
EXPARR_NEST
#define EXPARR_NEST (e) hlv.eabase[e].nest
Definition at line 553 of file hlvect.h.
EXPARR_NEXT
#define EXPARR_NEXT (e) hlv.eabase[e].next
Definition at line 556 of file hlvect.h.
EXPARR_TMPSYM
#define EXPARR_TMPSYM (e) hlv.eabase[e].tmpsym
Definition at line 555 of file hlvect.h.
EXPARR_UNIQUESECN
#define EXPARR_UNIQUESECN (e) hlv.eabase[e].flags.bits.uniquesecn
Definition at line 558 of file hlvect.h.
HLV_AREA
#define HLV_AREA 10
Definition at line 169 of file hlvect.h.
HLV_AREA1
#define HLV_AREA1 11
Definition at line 172 of file hlvect.h.
LOOPMASKC
#define LOOPMASKC (m, i) (m &= ~(1 << i))
Definition at line 531 of file hlvect.h.
LOOPMASKG
#define LOOPMASKG (m, i) ((m >> i) & 1)
Definition at line 530 of file hlvect.h.
LOOPMASKS
#define LOOPMASKS (m, i) (m |= (1 << i))
Definition at line 532 of file hlvect.h.
MAX_LOOPS
#define MAX_LOOPS 14
Definition at line 18 of file hlvect.h.
MR_ARRAY
#define MR_ARRAY (i) hlv.mrbase[i].flags.bits.array
Definition at line 301 of file hlvect.h.
MR_BASED
#define MR_BASED (i) hlv.mrbase[i].flags.bits.based
Definition at line 304 of file hlvect.h.
MR_CSEILI
#define MR_CSEILI (i) hlv.mrbase[i].cseili
Definition at line 292 of file hlvect.h.
MR_EXP
#define MR_EXP (i) hlv.mrbase[i].flags.bits.exp
Definition at line 306 of file hlvect.h.
MR_EXPARR
#define MR_EXPARR (i) hlv.mrbase[i].iv
Definition at line 297 of file hlvect.h.
MR_FG
#define MR_FG (i) hlv.mrbase[i].fg
Definition at line 280 of file hlvect.h.
MR_FLAGS
#define MR_FLAGS (i) hlv.mrbase[i].flags.all
Definition at line 285 of file hlvect.h.
MR_FSUBS
#define MR_FSUBS (i) hlv.mrbase[i].fsubs
Definition at line 291 of file hlvect.h.
MR_ILI
#define MR_ILI (i) hlv.mrbase[i].ili
Definition at line 278 of file hlvect.h.
MR_ILT
#define MR_ILT (i) hlv.mrbase[i].ilt
Definition at line 279 of file hlvect.h.
MR_INDIR
#define MR_INDIR (i) hlv.mrbase[i].flags.bits.indir
Definition at line 302 of file hlvect.h.
MR_INDUC
#define MR_INDUC (i) hlv.mrbase[i].flags.bits.induc
Definition at line 310 of file hlvect.h.
MR_INIT
#define MR_INIT (i) hlv.mrbase[i].flags.bits.init
Definition at line 308 of file hlvect.h.
MR_INVAL
#define MR_INVAL (i) hlv.mrbase[i].flags.bits.inval
Definition at line 307 of file hlvect.h.
MR_INVAR
#define MR_INVAR (i) hlv.mrbase[i].flags.bits.invar
Definition at line 311 of file hlvect.h.
MR_INVEC
#define MR_INVEC (i) hlv.mrbase[i].flags.bits.invec
Definition at line 312 of file hlvect.h.
MR_IV
#define MR_IV (i) hlv.mrbase[i].iv
Definition at line 295 of file hlvect.h.
MR_IVUSE
#define MR_IVUSE (i) hlv.mrbase[i].flags.bits.ivuse
Definition at line 300 of file hlvect.h.
MR_LOOP
#define MR_LOOP (i) hlv.mrbase[i].loop
Definition at line 288 of file hlvect.h.
MR_NEST
#define MR_NEST (i) hlv.mrbase[i].nest
Definition at line 284 of file hlvect.h.
MR_NEXT
#define MR_NEXT (i) hlv.mrbase[i].next
Definition at line 293 of file hlvect.h.
MR_NME
#define MR_NME (i) hlv.mrbase[i].nme
Definition at line 281 of file hlvect.h.
MR_PREV
#define MR_PREV (i) hlv.mrbase[i].prev
Definition at line 294 of file hlvect.h.
MR_REWR
#define MR_REWR (i) hlv.mrbase[i].rewr
Definition at line 298 of file hlvect.h.
MR_RG
#define MR_RG (i) hlv.mrbase[i].rg
Definition at line 289 of file hlvect.h.
MR_SCALR
#define MR_SCALR (i) hlv.mrbase[i].flags.bits.scalr
Definition at line 303 of file hlvect.h.
MR_SCLR
#define MR_SCLR (i) hlv.mrbase[i].iv
Definition at line 296 of file hlvect.h.
MR_STMT
#define MR_STMT (i) hlv.mrbase[i].stmt
Definition at line 282 of file hlvect.h.
MR_SUBCNT
#define MR_SUBCNT (i) hlv.mrbase[i].subcnt
Definition at line 287 of file hlvect.h.
MR_SUBST
#define MR_SUBST (i) hlv.mrbase[i].subst
Definition at line 286 of file hlvect.h.
MR_SUCC
#define MR_SUCC (i) hlv.mrbase[i].succ
Definition at line 290 of file hlvect.h.
MR_TYPE
#define MR_TYPE (i) hlv.mrbase[i].type
Definition at line 283 of file hlvect.h.
RG_BIH
#define RG_BIH (i) hlv.rgbase[i].bih
Definition at line 451 of file hlvect.h.
RG_BIHAFTER
#define RG_BIHAFTER (i) hlv.rgbase[i].bihafter
Definition at line 454 of file hlvect.h.
RG_BIHHD
#define RG_BIHHD (i) hlv.rgbase[i].bih
Definition at line 452 of file hlvect.h.
RG_BIHTL
#define RG_BIHTL (i) hlv.rgbase[i].bihtl
Definition at line 453 of file hlvect.h.
RG_BLOCK
#define RG_BLOCK (i) hlv.rgbase[i].flags.bits.block
Definition at line 469 of file hlvect.h.
RG_BLOCKRG
#define RG_BLOCKRG (i) hlv.rgbase[i].blockrg
Definition at line 473 of file hlvect.h.
RG_CALL
#define RG_CALL (i) hlv.rgbase[i].flags.bits.call
Definition at line 471 of file hlvect.h.
RG_CIF
#define RG_CIF (i) hlv.rgbase[i].flags.bits.cif
Definition at line 464 of file hlvect.h.
RG_CNT
#define RG_CNT (i) hlv.rgbase[i].cnt
Definition at line 448 of file hlvect.h.
RG_CNTLOAD
#define RG_CNTLOAD (i) hlv.rgbase[i].cnt_load
Definition at line 463 of file hlvect.h.
RG_CYCLE
#define RG_CYCLE (i) hlv.rgbase[i].cycle
Definition at line 443 of file hlvect.h.
RG_FLAGS
#define RG_FLAGS (i) hlv.rgbase[i].flags.all
Definition at line 450 of file hlvect.h.
RG_INNER
#define RG_INNER (i) hlv.rgbase[i].inner
Definition at line 438 of file hlvect.h.
RG_LABEL
#define RG_LABEL (i) hlv.rgbase[i].label
Definition at line 472 of file hlvect.h.
RG_LBND
#define RG_LBND (i) hlv.rgbase[i].ilbnd
Definition at line 458 of file hlvect.h.
RG_LLVI
#define RG_LLVI (i) hlv.rgbase[i].llvi
Definition at line 455 of file hlvect.h.
RG_MARKED
#define RG_MARKED (i) hlv.rgbase[i].flags.bits.marked
Definition at line 465 of file hlvect.h.
RG_MIV
#define RG_MIV (i) hlv.rgbase[i].miv
Definition at line 460 of file hlvect.h.
RG_MIVSTORE
#define RG_MIVSTORE (i) hlv.rgbase[i].miv_store
Definition at line 462 of file hlvect.h.
RG_MREG
#define RG_MREG (i) hlv.rgbase[i].mreg
Definition at line 461 of file hlvect.h.
RG_NEST
#define RG_NEST (i) hlv.rgbase[i].nest
Definition at line 444 of file hlvect.h.
RG_NEXT
#define RG_NEXT (i) hlv.rgbase[i].next
Definition at line 435 of file hlvect.h.
RG_NODENUM
#define RG_NODENUM (i) hlv.rgbase[i].nodenum
Definition at line 441 of file hlvect.h.
RG_ORIG
#define RG_ORIG (i) hlv.rgbase[i].orig
Definition at line 439 of file hlvect.h.
RG_ORIGNEST
#define RG_ORIGNEST (i) hlv.rgbase[i].orignest
Definition at line 445 of file hlvect.h.
RG_OUTER
#define RG_OUTER (i) hlv.rgbase[i].outer
Definition at line 437 of file hlvect.h.
RG_PARALLEL
#define RG_PARALLEL (i) hlv.rgbase[i].flags.bits.parallel
Definition at line 470 of file hlvect.h.
RG_PREV
#define RG_PREV (i) hlv.rgbase[i].prev
Definition at line 436 of file hlvect.h.
RG_RECURRENCE
#define RG_RECURRENCE (i) hlv.rgbase[i].flags.bits.recurrence
Definition at line 466 of file hlvect.h.
RG_SELF
#define RG_SELF (i) hlv.rgbase[i].flags.bits.self
Definition at line 467 of file hlvect.h.
RG_SLBND
#define RG_SLBND (i) hlv.rgbase[i].slbnd
Definition at line 456 of file hlvect.h.
RG_SLIST
#define RG_SLIST (i) hlv.rgbase[i].slist
Definition at line 440 of file hlvect.h.
RG_STRIP
#define RG_STRIP (i) hlv.rgbase[i].flags.bits.strip
Definition at line 468 of file hlvect.h.
RG_STRIPLEN
#define RG_STRIPLEN (i) hlv.rgbase[i].nodenum
Definition at line 442 of file hlvect.h.
RG_SUBND
#define RG_SUBND (i) hlv.rgbase[i].subnd
Definition at line 457 of file hlvect.h.
RG_SUCC
#define RG_SUCC (i) hlv.rgbase[i].succ
Definition at line 449 of file hlvect.h.
RG_TOP
#define RG_TOP (i) hlv.rgbase[i].top
Definition at line 446 of file hlvect.h.
RG_UBND
#define RG_UBND (i) hlv.rgbase[i].iubnd
Definition at line 459 of file hlvect.h.
RG_ZTRIP
#define RG_ZTRIP (i) hlv.rgbase[i].ztrip
Definition at line 447 of file hlvect.h.
SB_BASE
#define SB_BASE (i) hlv.subbase[i].bases[0]
Definition at line 228 of file hlvect.h.
SB_BASES
#define SB_BASES (i) hlv.subbase[i].bases
Definition at line 229 of file hlvect.h.
SB_IVUSE
#define SB_IVUSE (i) hlv.subbase[i].flags.bits.ivuse
Definition at line 227 of file hlvect.h.
SB_PTR
#define SB_PTR (i) hlv.subbase[i].flags.bits.ptr
Definition at line 226 of file hlvect.h.
SB_STOP
#define SB_STOP (i) hlv.subbase[i].flags.bits.stop
Definition at line 225 of file hlvect.h.
SB_STRIDE
#define SB_STRIDE (i) hlv.subbase[i].stride
Definition at line 230 of file hlvect.h.
SCLR_ARRSYM
#define SCLR_ARRSYM (i) hlv.scbase[i].arrsym
Definition at line 521 of file hlvect.h.
SCLR_FLAG
#define SCLR_FLAG (i) hlv.scbase[i].flags.bits.flag
Definition at line 519 of file hlvect.h.
SCLR_MASKSYM
#define SCLR_MASKSYM (i) hlv.scbase[i].masksym
Definition at line 522 of file hlvect.h.
SCLR_NEXT
#define SCLR_NEXT (i) hlv.scbase[i].next
Definition at line 518 of file hlvect.h.
SCLR_NME
#define SCLR_NME (i) hlv.scbase[i].nme
Definition at line 517 of file hlvect.h.
SCLR_SPAN
#define SCLR_SPAN (i) hlv.scbase[i].flags.bits.span
Definition at line 520 of file hlvect.h.
ST_FLAG
#define ST_FLAG (i) hlv.stbase[i].flag
Definition at line 382 of file hlvect.h.
ST_ILT
#define ST_ILT (i) hlv.stbase[i].ilt
Definition at line 378 of file hlvect.h.
ST_MRLIST
#define ST_MRLIST (i) hlv.stbase[i].mrlist
Definition at line 379 of file hlvect.h.
ST_NEXT
#define ST_NEXT (i) hlv.stbase[i].next
Definition at line 380 of file hlvect.h.
ST_PREV
#define ST_PREV (i) hlv.stbase[i].prev
Definition at line 381 of file hlvect.h.
ST_REDUC
#define ST_REDUC (i) hlv.stbase[i].flags.bits.reduc
Definition at line 383 of file hlvect.h.
STRIPSIZE
#define STRIPSIZE 1024
Definition at line 643 of file hlvect.h.
VIND_ALAST
#define VIND_ALAST (i) hlv.indbase[i].flags.bits.alast
Definition at line 355 of file hlvect.h.
VIND_ALIAS
#define VIND_ALIAS (i) hlv.indbase[i].flags.bits.alias
Definition at line 351 of file hlvect.h.
VIND_DELETE
#define VIND_DELETE (i) hlv.indbase[i].flags.bits.delete
Definition at line 348 of file hlvect.h.
VIND_INIT
#define VIND_INIT (i) hlv.indbase[i].init
Definition at line 345 of file hlvect.h.
VIND_LOAD
#define VIND_LOAD (i) hlv.indbase[i].load
Definition at line 344 of file hlvect.h.
VIND_MIDF
#define VIND_MIDF (i) hlv.indbase[i].flags.bits.midf
Definition at line 350 of file hlvect.h.
VIND_NIU
#define VIND_NIU (i) hlv.indbase[i].flags.bits.niu
Definition at line 349 of file hlvect.h.
VIND_NM
#define VIND_NM (i) hlv.indbase[i].nm
Definition at line 343 of file hlvect.h.
VIND_NOINV
#define VIND_NOINV (i) hlv.indbase[i].flags.bits.noinv
Definition at line 352 of file hlvect.h.
VIND_OMIT
#define VIND_OMIT (i) hlv.indbase[i].flags.bits.omit
Definition at line 353 of file hlvect.h.
VIND_OPC
#define VIND_OPC (i) hlv.indbase[i].opc
Definition at line 357 of file hlvect.h.
VIND_ORIGINIT
#define VIND_ORIGINIT (i) hlv.indbase[i].originit
Definition at line 346 of file hlvect.h.
VIND_PTR
#define VIND_PTR (i) hlv.indbase[i].flags.bits.ptr
Definition at line 347 of file hlvect.h.
VIND_SAVE
#define VIND_SAVE (i) hlv.indbase[i].flags.bits.save
Definition at line 356 of file hlvect.h.
VIND_SKIP
#define VIND_SKIP (i) hlv.indbase[i].skip
Definition at line 359 of file hlvect.h.
VIND_TOTSKIP
#define VIND_TOTSKIP (i) hlv.indbase[i].totskip
Definition at line 358 of file hlvect.h.
VIND_VISIT
#define VIND_VISIT (i) hlv.indbase[i].flags.bits.visit
Definition at line 354 of file hlvect.h.
VL_ALBND
#define VL_ALBND (i) hlv.lpbase[i].albnd
Definition at line 85 of file hlvect.h.
VL_AUBND
#define VL_AUBND (i) hlv.lpbase[i].aubnd
Definition at line 83 of file hlvect.h.
VL_CAND
#define VL_CAND (i) hlv.lpbase[i].flags.bits.cand
Definition at line 119 of file hlvect.h.
VL_CHILD
#define VL_CHILD (i) hlv.lpbase[i].child
Definition at line 71 of file hlvect.h.
VL_DEL
#define VL_DEL (i) hlv.lpbase[i].flags.bits.del
Definition at line 121 of file hlvect.h.
VL_EALIST
#define VL_EALIST (i) hlv.lpbase[i].ealist
Definition at line 88 of file hlvect.h.
VL_EXITBIH
#define VL_EXITBIH (i) hlv.lpbase[i].exitbih
Definition at line 90 of file hlvect.h.
VL_FLAGS
#define VL_FLAGS (i) hlv.lpbase[i].flags.all
Definition at line 74 of file hlvect.h.
VL_ICNT
#define VL_ICNT (i) hlv.lpbase[i].icnt
Definition at line 79 of file hlvect.h.
VL_ILBND
#define VL_ILBND (i) hlv.lpbase[i].ilbnd
Definition at line 84 of file hlvect.h.
VL_ISTART
#define VL_ISTART (i) hlv.lpbase[i].istart
Definition at line 78 of file hlvect.h.
VL_IUBND
#define VL_IUBND (i) hlv.lpbase[i].iubnd
Definition at line 82 of file hlvect.h.
VL_IVLIST
#define VL_IVLIST (i) hlv.lpbase[i].ivlist
Definition at line 91 of file hlvect.h.
VL_LBND
#define VL_LBND (i) hlv.lpbase[i].lbnd
Definition at line 81 of file hlvect.h.
VL_LOOP
#define VL_LOOP (i) hlv.lpbase[i].lp
Definition at line 70 of file hlvect.h.
VL_LPCNT
#define VL_LPCNT (i) hlv.lpbase[i].lpcnt
Definition at line 86 of file hlvect.h.
VL_MRCNT
#define VL_MRCNT (i) hlv.lpbase[i].mrcnt
Definition at line 76 of file hlvect.h.
VL_MRECNT
#define VL_MRECNT (i) hlv.lpbase[i].mrecnt
Definition at line 77 of file hlvect.h.
VL_MRSTART
#define VL_MRSTART (i) hlv.lpbase[i].mrstart
Definition at line 75 of file hlvect.h.
VL_NEST
#define VL_NEST (i) hlv.lpbase[i].nest
Definition at line 73 of file hlvect.h.
VL_PERF
#define VL_PERF (i) hlv.lpbase[i].flags.bits.perf
Definition at line 120 of file hlvect.h.
VL_PRAGMAS
#define VL_PRAGMAS (i) hlv.lpbase[i].pragmas
Definition at line 92 of file hlvect.h.
VL_PREBIH
#define VL_PREBIH (i) hlv.lpbase[i].prebih
Definition at line 89 of file hlvect.h.
VL_SCLIST
#define VL_SCLIST (i) hlv.lpbase[i].sclist
Definition at line 87 of file hlvect.h.
VL_SIBLING
#define VL_SIBLING (i) hlv.lpbase[i].sibling
Definition at line 72 of file hlvect.h.
VL_UBND
#define VL_UBND (i) hlv.lpbase[i].ubnd
Definition at line 80 of file hlvect.h.
VL_ZTRIP
#define VL_ZTRIP (i) hlv.lpbase[i].flags.bits.ztrip
Definition at line 122 of file hlvect.h.
VLP_ASSOC
#define VLP_ASSOC (i) hlv.lpbase[i].pragmas.assoc
Definition at line 95 of file hlvect.h.
VLP_DEPCHK
#define VLP_DEPCHK (i) hlv.lpbase[i].pragmas.depchk
Definition at line 94 of file hlvect.h.
VLP_EQVCHK
#define VLP_EQVCHK (i) hlv.lpbase[i].pragmas.eqvchk
Definition at line 96 of file hlvect.h.
VLP_LDSTSPLIT
#define VLP_LDSTSPLIT (i) hlv.lpbase[i].pragmas.ldstsplit
Definition at line 103 of file hlvect.h.
VLP_LSTVAL
#define VLP_LSTVAL (i) hlv.lpbase[i].pragmas.lstval
Definition at line 97 of file hlvect.h.
VLP_MINCNT
#define VLP_MINCNT (i) hlv.lpbase[i].pragmas.mincnt
Definition at line 102 of file hlvect.h.
VLP_OPSPLIT
#define VLP_OPSPLIT (i) hlv.lpbase[i].pragmas.opsplit
Definition at line 104 of file hlvect.h.
VLP_RECOG
#define VLP_RECOG (i) hlv.lpbase[i].pragmas.recog
Definition at line 98 of file hlvect.h.
VLP_SAFECALL
#define VLP_SAFECALL (i) hlv.lpbase[i].pragmas.safecall
Definition at line 100 of file hlvect.h.
VLP_SHORTLP
#define VLP_SHORTLP (i) hlv.lpbase[i].pragmas.shortloop
Definition at line 101 of file hlvect.h.
VLP_TRANS
#define VLP_TRANS (i) hlv.lpbase[i].pragmas.trans
Definition at line 99 of file hlvect.h.
VP_ASSOC
#define VP_ASSOC (i) i.assoc
Definition at line 107 of file hlvect.h.
VP_DEPCHK
#define VP_DEPCHK (i) i.depchk
Definition at line 106 of file hlvect.h.
VP_EQVCHK
#define VP_EQVCHK (i) i.eqvchk
Definition at line 108 of file hlvect.h.
VP_LDSTSPLIT
#define VP_LDSTSPLIT (i) i.ldstsplit
Definition at line 115 of file hlvect.h.
VP_LSTVAL
#define VP_LSTVAL (i) i.lstval
Definition at line 109 of file hlvect.h.
VP_MINCNT
#define VP_MINCNT (i) i.mincnt
Definition at line 114 of file hlvect.h.
VP_OPSPLIT
#define VP_OPSPLIT (i) i.opsplit
Definition at line 116 of file hlvect.h.
VP_RECOG
#define VP_RECOG (i) i.recog
Definition at line 110 of file hlvect.h.
VP_SAFECALL
#define VP_SAFECALL (i) i.safecall
Definition at line 112 of file hlvect.h.
VP_SHORTLP
#define VP_SHORTLP (i) i.shortloop
Definition at line 113 of file hlvect.h.
VP_TRANS
#define VP_TRANS (i) i.trans
Definition at line 111 of file hlvect.h.
VT_DP
#define VT_DP 3 /* double precision */
Definition at line 489 of file hlvect.h.
VT_INT
#define VT_INT 0 /* integer temp */
Definition at line 486 of file hlvect.h.
VT_MAX
#define VT_MAX 4
Definition at line 490 of file hlvect.h.
VT_PHASES
#define VT_PHASES 2 /* number of phases of temps */
Definition at line 494 of file hlvect.h.
VT_PHIND
#define VT_PHIND 1 /* induction phase */
Definition at line 493 of file hlvect.h.
VT_PHINIT
#define VT_PHINIT 0 /* initial value phase */
Definition at line 492 of file hlvect.h.
VT_PTR
#define VT_PTR 1 /* pointer temp */
Definition at line 487 of file hlvect.h.
VT_SP
#define VT_SP 2 /* single precision */
Definition at line 488 of file hlvect.h.
Typedef Documentation
DDEDGE
typedef struct DDEDGE DDEDGE
DIRVEC
typedef BIGUINT64 DIRVEC
Definition at line 135 of file hlvect.h.
LOOPMASK
typedef UINT16 LOOPMASK
Definition at line 528 of file hlvect.h.
VPSI
typedef struct VPSI VPSI
VPSI_P
typedef struct VPSI * VPSI_P
Function Documentation
build_dd()
void build_dd (int loop)
Build the data dependency graph.
Definition at line 268 of file datadep.c.
References build_loop_dd(), cln_visit(), DBGBIT, ddinfo, dump_one_vloop(), dump_vloops(), gbl, i, VL_CHILD, and VL_SIBLING.
dd_array_conflict()
LOGICAL dd_array_conflict (int astliTriples, int astArrSrc, int astArrSink, int bSinkAfterSrc)
Return TRUE if there is a forward dependence from astArrSrc (the source) to astArrSink (the sink) within an iteration space described by a triplet list beginning at astliTriples.
bSinkAfterSrc should be:
1 if the sink is lexically after the source.
0 if the sink is lexically before the source.
-1 if this is a FORALL test
Definition at line 2342 of file datadep.c.
References ASD_NDIM, assert, astb, ASTLI_NEXT, ASTLI_TRIPLE, ASTB::bnd, BZERO, cln_visit(), CNSTG, dd_edge(), DD_NEXT, ddinfo, dirv_chkzero(), DIRV_ENTRYG, dirv_exo(), dirv_gen(), DIRV_GT, DIRV_LT, DDEDGE::dirvec, do_subscript(), ASTB::dtype, FALSE, fill_subscripts(), FREE, freearea(), fwd, fwd_func(), hlv, HLV_AREA1, i, interr(), IS_CNST, ISZ_T, lp, HLVECT::lpavail, HLVECT::lpbase, HLVECT::lpsize, MAX_LOOPS, mk_binop(), MR_ILI, MR_SUBCNT, MR_SUBST, MR_SUCC, MR_TYPE, HLVECT::mravail, HLVECT::mrbase, HLVECT::mrsize, NEED, NEW, DV::next, nsubs, NULL, OP_SUB, SB_BASE, SB_BASES, SB_STRIDE, sub, HLVECT::subavail, HLVECT::subbase, HLVECT::subsize, t, TRUE, val, DV::vec, VL_LBND, VL_UBND, VP_DEPCHK, and ASTB::zero.
Referenced by Conflict_(), and name_dependent_check().
dd_edge()
void dd_edge (int src, int sink, DIRVEC vec)
Definition at line 557 of file datadep.c.
References DD_DIRVEC, DD_NEXT, DD_SINK, DD_TYPE, ddinfo, def, DEF_FG, DEF_NEXT, DIRV_BIGPOS, DIRV_FANTI, DIRV_FFLOW, DIRV_FOUT, dirv_gen(), dirv_print(), edge_func(), FG_LOOP, getitem(), HLV_AREA, inloop(), interr(), lp, LP_PARENT, MR_ILT, MR_INVAL, MR_NME, MR_SUCC, MR_TYPE, NME_DEF, p, sink, skip, src, TRACE0, TRACE3, type, and vec.
Referenced by chkref(), and dd_array_conflict().
dd_symbolic()
int dd_symbolic (int il)
Perform symbolic algebraic simplification of term il.
NOTE: Call freearea(HLV_AREA1) after calling this function.
Definition at line 3009 of file datadep.c.
References FALSE, ili_symbolic(), TRUE, and use_visit.
Referenced by opt_binop().
dirv_chkzero()
int dirv_chkzero (DIRVEC dir, int n)
Definition at line 3020 of file datadep.c.
References DIRV_ENTRYG, i, and n.
Referenced by chkref(), and dd_array_conflict().
dirv_exo()
DIRVEC dirv_exo (int level, int flag)
Generate legal execution order direction vectors.
Parameters
level loop nesting level
flag says whether all '=' allowed
Definition at line 2018 of file datadep.c.
References DIRV_ALLEQ, DIRV_ENTRYP, DIRV_EQ, DIRV_LT, DIRV_STAR, i, level(), and vec.
Referenced by chkref(), and dd_array_conflict().
dirv_fulldep()
DIRVEC dirv_fulldep (int level)
Generate full dependence at a given level.
Definition at line 1999 of file datadep.c.
References DIRV_ALLEQ, DIRV_ENTSIZ, DIRV_STAR, i, level(), and vec.
Referenced by dd_compute(), do_subscript(), resolve_pp(), resolve_pv(), resolve_uv(), and resolve_vv().
dirv_gen()
void dirv_gen (DIRVEC dir, int * map, int nest, int ig, void(*)(DIRVEC) f)
Definition at line 2125 of file datadep.c.
References DIRV_ENTRYG, dirv_permute(), dovec(), f, i, and MAX_LOOPS.
Referenced by dd_array_conflict(), and dd_edge().
dirv_inverse()
DIRVEC dirv_inverse (DIRVEC vec)
Invert a direction vector.
Definition at line 1967 of file datadep.c.
References DIRV_ENTRYG, DIRV_ENTRYP, DIRV_INFOPART, i, MAX_LOOPS, t, and vec.
Referenced by chkref().
gen_llinfo()
void gen_llinfo (int reg)
get_generic_minmax()
int get_generic_minmax (int optype)
has_recurrence()
LOGICAL has_recurrence (int rg, int nest, int * mapx, int * mapy)
has_reduction()
LOGICAL has_reduction (int rg, int * map, int nest)
hlv_getsym()
int hlv_getsym (int phase, int type)
Definition at line 279 of file hlvect.c.
References hlv_temps, p, sptr, sym_get_scalar(), TRUE, and type.
hlv_getvsym()
int hlv_getvsym (int baseDtype)
Definition at line 292 of file hlvect.c.
References AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_UPAST, AD_UPBD, astb, DT_INT, get_array_dtype(), getsymf(), hlv_vtemps, ASTB::i0, ASTB::i1, VTMP::iavl, VTMP::iavl_max, mk_cval(), VTMP::pfx, sptr, STRIPSIZE, and TRUE.
hlvtrans()
void hlvtrans (int loop)
is_parent_loop()
LOGICAL is_parent_loop (int lpParent, int lpChild)
is_perfect()
int is_perfect (int rg)
llvect()
void llvect (void)
mark_vinduc()
void mark_vinduc (int loop)
Definition at line 243 of file hlvect.c.
References end, i, NME_RFPTR, VIND_NM, VL_ICNT, and VL_ISTART.
open_vpragma()
void open_vpragma (int lp)
parmethod()
int parmethod (int rg, int nest, int * mapx, int * mapy)
reg_parmark()
void reg_parmark (int rg)
regmark()
void regmark (int rg, int rgm, int flag)
remove_accum()
int remove_accum (int astx, int subast, int optype)
score_loop_hpf()
double score_loop_hpf (int * a)
score_loop_i860()
double score_loop_i860 (int * a)
score_loop_sparc()
double score_loop_sparc (int * a)
score_loop_vpu()
double score_loop_vpu (int * a)
unmark_vinduc()
void unmark_vinduc (int loop)
Definition at line 254 of file hlvect.c.
References end, i, NME_RFPTR, VIND_NM, VL_ICNT, and VL_ISTART.
vdel_bih()
void vdel_bih (int bihx)
Definition at line 321 of file hlvect.c.
References BIH_RGSET, and vdel_lst.
vect_flg_defaults()
void vect_flg_defaults (void)
vectorize()
void vectorize (void)
Referenced by cons_vec_always_metadata().
vpar()
void vpar (void)
Variable Documentation
hlv
HLVECT hlv extern
Definition at line 137 of file hlvect.c.
Referenced by build_nat_loop(), dd_array_conflict(), dd_succ(), dumpmr(), dumpvind(), dumpvinds(), dumpvloop(), dumpvloops(), dumpvloops2(), dumpvnest(), dumpvnest2(), and fill_subscripts().
hlv_temps
VTMP hlv_temps[VT_PHASES][VT_MAX] extern
Definition at line 143 of file hlvect.c.
Referenced by hlv_getsym().
hlv_vtemps
VTMP hlv_vtemps extern
Definition at line 158 of file hlvect.c.
Referenced by hlv_getvsym().