flang: host-fp-folding.c File Reference
host-fp-folding.c File Reference
Implement floating-point folding with host arithmetic.
#include "fp-folding.h"
#include <assert.h>
#include <complex.h>
#include <errno.h>
#include <fenv.h>
#include <float.h>
#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
Macros
#define COMPARE_BODY
Functions
void fold_sanity_check (void)
static void configure_denormals (bool denorms_are_zeros, bool flush_to_zero)
enum fold_relation fold_real32_compare (const float32_t *x, const float32_t *y)
enum fold_relation fold_real64_compare (const float64_t *x, const float64_t *y)
enum fold_relation fold_real128_compare (const float128_t *x, const float128_t *y)
static void set_up_floating_point_environment (fenv_t *fenv)
static enum fold_status interpret_exceptions (int exceptions, int errno_capture)
static enum fold_status check_and_restore_floating_point_environment (const fenv_t *saved_fenv)
enum fold_status fold_int32_from_real32 (int32_t *res, const float32_t *arg)
enum fold_status fold_int64_from_real32 (int64_t *res, const float32_t *arg)
enum fold_status fold_uint64_from_real32 (uint64_t *res, const float32_t *arg)
enum fold_status fold_uint32_from_real32 (uint32_t *res, const float32_t *arg)
enum fold_status fold_real32_from_int64 (float32_t *res, const int64_t *arg)
enum fold_status fold_real32_from_uint64 (float32_t *res, const uint64_t *arg)
enum fold_status fold_real32_from_real64 (float32_t *res, const float64_t *arg)
enum fold_status fold_real32_from_real128 (float32_t *res, const float128_t *arg)
enum fold_status fold_real32_negate (float32_t *res, const float32_t *arg)
enum fold_status fold_real32_abs (float32_t *res, const float32_t *arg)
enum fold_status fold_real32_sqrt (float32_t *res, const float32_t *arg)
enum fold_status fold_real32_add (float32_t *res, const float32_t *x, const float32_t *y)
enum fold_status fold_real32_subtract (float32_t *res, const float32_t *x, const float32_t *y)
enum fold_status fold_real32_multiply (float32_t *res, const float32_t *x, const float32_t *y)
enum fold_status fold_real32_divide (float32_t *res, const float32_t *x, const float32_t *y)
enum fold_status fold_real32_pow (float32_t *res, const float32_t *x, const float32_t *y)
enum fold_status fold_real32_sin (float32_t *res, const float32_t *arg)
enum fold_status fold_real32_cos (float32_t *res, const float32_t *arg)
enum fold_status fold_real32_tan (float32_t *res, const float32_t *arg)
enum fold_status fold_real32_asin (float32_t *res, const float32_t *arg)
enum fold_status fold_real32_acos (float32_t *res, const float32_t *arg)
enum fold_status fold_real32_atan (float32_t *res, const float32_t *arg)
enum fold_status fold_real32_atan2 (float32_t *res, const float32_t *x, const float32_t *y)
enum fold_status fold_real32_exp (float32_t *res, const float32_t *arg)
enum fold_status fold_real32_log (float32_t *res, const float32_t *arg)
enum fold_status fold_real32_log10 (float32_t *res, const float32_t *arg)
enum fold_status fold_int32_from_real64 (int32_t *res, const float64_t *arg)
enum fold_status fold_int64_from_real64 (int64_t *res, const float64_t *arg)
enum fold_status fold_uint32_from_real64 (uint32_t *res, const float64_t *arg)
enum fold_status fold_uint64_from_real64 (uint64_t *res, const float64_t *arg)
enum fold_status fold_real64_from_int64 (float64_t *res, const int64_t *arg)
enum fold_status fold_real64_from_uint64 (float64_t *res, const uint64_t *arg)
enum fold_status fold_real64_from_real32 (float64_t *res, const float32_t *arg)
enum fold_status fold_real64_from_real128 (float64_t *res, const float128_t *arg)
enum fold_status fold_real64_negate (float64_t *res, const float64_t *arg)
enum fold_status fold_real64_abs (float64_t *res, const float64_t *arg)
enum fold_status fold_real64_sqrt (float64_t *res, const float64_t *arg)
enum fold_status fold_real64_add (float64_t *res, const float64_t *x, const float64_t *y)
enum fold_status fold_real64_subtract (float64_t *res, const float64_t *x, const float64_t *y)
enum fold_status fold_real64_multiply (float64_t *res, const float64_t *x, const float64_t *y)
enum fold_status fold_real64_divide (float64_t *res, const float64_t *x, const float64_t *y)
enum fold_status fold_real64_pow (float64_t *res, const float64_t *x, const float64_t *y)
enum fold_status fold_real64_sin (float64_t *res, const float64_t *arg)
enum fold_status fold_real64_cos (float64_t *res, const float64_t *arg)
enum fold_status fold_real64_tan (float64_t *res, const float64_t *arg)
enum fold_status fold_real64_asin (float64_t *res, const float64_t *arg)
enum fold_status fold_real64_acos (float64_t *res, const float64_t *arg)
enum fold_status fold_real64_atan (float64_t *res, const float64_t *arg)
enum fold_status fold_real64_atan2 (float64_t *res, const float64_t *x, const float64_t *y)
enum fold_status fold_real64_exp (float64_t *res, const float64_t *arg)
enum fold_status fold_real64_log (float64_t *res, const float64_t *arg)
enum fold_status fold_real64_log10 (float64_t *res, const float64_t *arg)
enum fold_status fold_int32_from_real128 (int32_t *res, const float128_t *arg)
enum fold_status fold_int64_from_real128 (int64_t *res, const float128_t *arg)
enum fold_status fold_uint32_from_real128 (uint32_t *res, const float128_t *arg)
enum fold_status fold_uint64_from_real128 (uint64_t *res, const float128_t *arg)
enum fold_status fold_real128_from_int64 (float128_t *res, const int64_t *arg)
enum fold_status fold_real128_from_uint64 (float128_t *res, const uint64_t *arg)
enum fold_status fold_real128_from_real32 (float128_t *res, const float32_t *arg)
enum fold_status fold_real128_from_real64 (float128_t *res, const float64_t *arg)
enum fold_status fold_real128_negate (float128_t *res, const float128_t *arg)
enum fold_status fold_real128_abs (float128_t *res, const float128_t *arg)
enum fold_status fold_real128_sqrt (float128_t *res, const float128_t *arg)
enum fold_status fold_real128_add (float128_t *res, const float128_t *x, const float128_t *y)
enum fold_status fold_real128_subtract (float128_t *res, const float128_t *x, const float128_t *y)
enum fold_status fold_real128_multiply (float128_t *res, const float128_t *x, const float128_t *y)
enum fold_status fold_real128_divide (float128_t *res, const float128_t *x, const float128_t *y)
enum fold_status fold_real128_pow (float128_t *res, const float128_t *x, const float128_t *y)
enum fold_status fold_real128_sin (float128_t *res, const float128_t *arg)
enum fold_status fold_real128_cos (float128_t *res, const float128_t *arg)
enum fold_status fold_real128_tan (float128_t *res, const float128_t *arg)
enum fold_status fold_real128_asin (float128_t *res, const float128_t *arg)
enum fold_status fold_real128_acos (float128_t *res, const float128_t *arg)
enum fold_status fold_real128_atan (float128_t *res, const float128_t *arg)
enum fold_status fold_real128_atan2 (float128_t *res, const float128_t *x, const float128_t *y)
enum fold_status fold_real128_exp (float128_t *res, const float128_t *arg)
enum fold_status fold_real128_log (float128_t *res, const float128_t *arg)
enum fold_status fold_real128_log10 (float128_t *res, const float128_t *arg)
enum fold_status fold_complex32_pow (FLOAT_COMPLEX_TYPE *res, const FLOAT_COMPLEX_TYPE *x, const FLOAT_COMPLEX_TYPE *y)
enum fold_status fold_complex64_pow (DOUBLE_COMPLEX_TYPE *res, const DOUBLE_COMPLEX_TYPE *x, const DOUBLE_COMPLEX_TYPE *y)
enum fold_status fold_complex128_pow (LONG_DOUBLE_COMPLEX_TYPE *res, const LONG_DOUBLE_COMPLEX_TYPE *x, const LONG_DOUBLE_COMPLEX_TYPE *y)
Detailed Description
Implement floating-point folding with host arithmetic.
Implements the compile-time evaluation interfaces of "fp-folding.h" using the native host floating-point arithmetic operations and math library.
Definition in file host-fp-folding.c.
Macro Definition Documentation
COMPARE_BODY
#define COMPARE_BODY
Value:
  { \
  enum fold_relation rel = FOLD_UN; \
  fenv_t fenv; \
  if (feholdexcept(&fenv) != 0) \
    fprintf(stderr, "feholdexcept() failed: %s\n", strerror(errno)); \
  configure_denormals(false, false); \
  if (*x < *y) \
    rel = FOLD_LT; \
  else if (*x == *y) \
    rel = FOLD_EQ; \
  else if (*x > *y) \
    rel = FOLD_GT; \
  if (fesetenv(&fenv) != 0) \
    fprintf(stderr, "fesetenv() failed: %s\n", strerror(errno)); \
  return rel; \
}
Definition at line 107 of file host-fp-folding.c.
Function Documentation
check_and_restore_floating_point_environment()
static enum fold_status check_and_restore_floating_point_environment (const fenv_t * saved_fenv) static
Definition at line 189 of file host-fp-folding.c.
References interpret_exceptions().
Referenced by fold_complex128_pow(), fold_complex32_pow(), fold_complex64_pow(), fold_int32_from_real128(), fold_int32_from_real32(), fold_int32_from_real64(), fold_int64_from_real128(), fold_int64_from_real32(), fold_int64_from_real64(), fold_real128_abs(), fold_real128_acos(), fold_real128_add(), fold_real128_asin(), fold_real128_atan(), fold_real128_atan2(), fold_real128_cos(), fold_real128_divide(), fold_real128_exp(), fold_real128_from_int64(), fold_real128_from_real32(), fold_real128_from_real64(), fold_real128_from_uint64(), fold_real128_log(), fold_real128_log10(), fold_real128_multiply(), fold_real128_negate(), fold_real128_pow(), fold_real128_sin(), fold_real128_sqrt(), fold_real128_subtract(), fold_real128_tan(), fold_real32_abs(), fold_real32_acos(), fold_real32_add(), fold_real32_asin(), fold_real32_atan(), fold_real32_atan2(), fold_real32_cos(), fold_real32_divide(), fold_real32_exp(), fold_real32_from_int64(), fold_real32_from_real128(), fold_real32_from_real64(), fold_real32_from_uint64(), fold_real32_log(), fold_real32_log10(), fold_real32_multiply(), fold_real32_negate(), fold_real32_pow(), fold_real32_sin(), fold_real32_sqrt(), fold_real32_subtract(), fold_real32_tan(), fold_real64_abs(), fold_real64_acos(), fold_real64_add(), fold_real64_asin(), fold_real64_atan(), fold_real64_atan2(), fold_real64_cos(), fold_real64_divide(), fold_real64_exp(), fold_real64_from_int64(), fold_real64_from_real128(), fold_real64_from_real32(), fold_real64_from_uint64(), fold_real64_log(), fold_real64_log10(), fold_real64_multiply(), fold_real64_negate(), fold_real64_pow(), fold_real64_sin(), fold_real64_sqrt(), fold_real64_subtract(), fold_real64_tan(), fold_uint32_from_real128(), fold_uint32_from_real32(), fold_uint32_from_real64(), fold_uint64_from_real128(), fold_uint64_from_real32(), and fold_uint64_from_real64().
configure_denormals()
static void configure_denormals (bool denorms_are_zeros, bool flush_to_zero) static
Definition at line 74 of file host-fp-folding.c.
Referenced by set_up_floating_point_environment().
fold_complex128_pow()
enum fold_status fold_complex128_pow (LONG_DOUBLE_COMPLEX_TYPE * res, const LONG_DOUBLE_COMPLEX_TYPE * x, const LONG_DOUBLE_COMPLEX_TYPE * y)
Definition at line 932 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xcqpow().
fold_complex32_pow()
enum fold_status fold_complex32_pow (FLOAT_COMPLEX_TYPE * res, const FLOAT_COMPLEX_TYPE * x, const FLOAT_COMPLEX_TYPE * y)
Definition at line 912 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), DCMPLX_TO_FCMPLX, FCMPLX_TO_DCMPLX, res, set_up_floating_point_environment(), x, and y.
Referenced by xcfpow().
fold_complex64_pow()
enum fold_status fold_complex64_pow (DOUBLE_COMPLEX_TYPE * res, const DOUBLE_COMPLEX_TYPE * x, const DOUBLE_COMPLEX_TYPE * y)
Definition at line 922 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), DCMPLX_TO_LCMPLX, LCMPLX_TO_DCMPLX, res, set_up_floating_point_environment(), x, and y.
Referenced by xcdpow().
fold_int32_from_real128()
enum fold_status fold_int32_from_real128 (int32_t * res, const float128_t * arg)
Definition at line 678 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqfix().
fold_int32_from_real32()
enum fold_status fold_int32_from_real32 (int32_t * res, const float32_t * arg)
Definition at line 206 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xfisint(), and xfix().
fold_int32_from_real64()
enum fold_status fold_int32_from_real64 (int32_t * res, const float64_t * arg)
Definition at line 442 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xdfix(), and xdisint().
fold_int64_from_real128()
enum fold_status fold_int64_from_real128 (int64_t * res, const float128_t * arg)
Definition at line 687 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqfix64().
fold_int64_from_real32()
enum fold_status fold_int64_from_real32 (int64_t * res, const float32_t * arg)
Definition at line 215 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xfix64(), and xfixu64().
fold_int64_from_real64()
enum fold_status fold_int64_from_real64 (int64_t * res, const float64_t * arg)
Definition at line 451 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xdfix64(), and xdfixu64().
fold_real128_abs()
enum fold_status fold_real128_abs (float128_t * res, const float128_t * arg)
Definition at line 759 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqabsv().
fold_real128_acos()
enum fold_status fold_real128_acos (float128_t * res, const float128_t * arg)
Definition at line 858 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqacos().
fold_real128_add()
enum fold_status fold_real128_add (float128_t * res, const float128_t * x, const float128_t * y)
Definition at line 777 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xqadd().
fold_real128_asin()
enum fold_status fold_real128_asin (float128_t * res, const float128_t * arg)
Definition at line 849 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqasin().
fold_real128_atan()
enum fold_status fold_real128_atan (float128_t * res, const float128_t * arg)
Definition at line 867 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqatan().
fold_real128_atan2()
enum fold_status fold_real128_atan2 (float128_t * res, const float128_t * x, const float128_t * y)
Definition at line 876 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xqatan2().
fold_real128_compare()
enum fold_relation fold_real128_compare (const float128_t * x, const float128_t * y)
Definition at line 137 of file host-fp-folding.c.
References COMPARE_BODY.
Referenced by xqcmp().
fold_real128_cos()
enum fold_status fold_real128_cos (float128_t * res, const float128_t * arg)
Definition at line 831 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqcos().
fold_real128_divide()
enum fold_status fold_real128_divide (float128_t * res, const float128_t * x, const float128_t * y)
Definition at line 804 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xqdiv().
fold_real128_exp()
enum fold_status fold_real128_exp (float128_t * res, const float128_t * arg)
Definition at line 885 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqexp().
fold_real128_from_int64()
enum fold_status fold_real128_from_int64 (float128_t * res, const int64_t * arg)
Definition at line 714 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqfloat(), xqfloatu(), and xqflt64().
fold_real128_from_real32()
enum fold_status fold_real128_from_real32 (float128_t * res, const float32_t * arg)
Definition at line 732 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xftoq().
fold_real128_from_real64()
enum fold_status fold_real128_from_real64 (float128_t * res, const float64_t * arg)
Definition at line 741 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xdtoq().
fold_real128_from_uint64()
enum fold_status fold_real128_from_uint64 (float128_t * res, const uint64_t * arg)
Definition at line 723 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqfltu64().
fold_real128_log()
enum fold_status fold_real128_log (float128_t * res, const float128_t * arg)
Definition at line 894 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqlog().
fold_real128_log10()
enum fold_status fold_real128_log10 (float128_t * res, const float128_t * arg)
Definition at line 903 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqlog10().
fold_real128_multiply()
enum fold_status fold_real128_multiply (float128_t * res, const float128_t * x, const float128_t * y)
Definition at line 795 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xqmul().
fold_real128_negate()
enum fold_status fold_real128_negate (float128_t * res, const float128_t * arg)
Definition at line 750 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqneg().
fold_real128_pow()
enum fold_status fold_real128_pow (float128_t * res, const float128_t * x, const float128_t * y)
Definition at line 813 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xqpow().
fold_real128_sin()
enum fold_status fold_real128_sin (float128_t * res, const float128_t * arg)
Definition at line 822 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqsin().
fold_real128_sqrt()
enum fold_status fold_real128_sqrt (float128_t * res, const float128_t * arg)
Definition at line 768 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqsqrt().
fold_real128_subtract()
enum fold_status fold_real128_subtract (float128_t * res, const float128_t * x, const float128_t * y)
Definition at line 786 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xqsub().
fold_real128_tan()
enum fold_status fold_real128_tan (float128_t * res, const float128_t * arg)
Definition at line 840 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqtan().
fold_real32_abs()
enum fold_status fold_real32_abs (float32_t * res, const float32_t * arg)
Definition at line 287 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xfabsv().
fold_real32_acos()
enum fold_status fold_real32_acos (float32_t * res, const float32_t * arg)
Definition at line 386 of file host-fp-folding.c.
References acosf(), arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xfacos().
fold_real32_add()
enum fold_status fold_real32_add (float32_t * res, const float32_t * x, const float32_t * y)
Definition at line 305 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xfadd().
fold_real32_asin()
enum fold_status fold_real32_asin (float32_t * res, const float32_t * arg)
Definition at line 377 of file host-fp-folding.c.
References arg, asinf(), check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xfasin().
fold_real32_atan()
enum fold_status fold_real32_atan (float32_t * res, const float32_t * arg)
Definition at line 395 of file host-fp-folding.c.
References arg, atanf(), check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xfatan().
fold_real32_atan2()
enum fold_status fold_real32_atan2 (float32_t * res, const float32_t * x, const float32_t * y)
Definition at line 404 of file host-fp-folding.c.
References atan2f(), check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xfatan2().
fold_real32_compare()
enum fold_relation fold_real32_compare (const float32_t * x, const float32_t * y)
Definition at line 125 of file host-fp-folding.c.
References COMPARE_BODY.
Referenced by xfcmp(), and xfisint().
fold_real32_cos()
enum fold_status fold_real32_cos (float32_t * res, const float32_t * arg)
Definition at line 359 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), cosf(), res, and set_up_floating_point_environment().
Referenced by xfcos().
fold_real32_divide()
enum fold_status fold_real32_divide (float32_t * res, const float32_t * x, const float32_t * y)
Definition at line 332 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xfdiv(), and xfrcp().
fold_real32_exp()
enum fold_status fold_real32_exp (float32_t * res, const float32_t * arg)
Definition at line 413 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), expf(), res, and set_up_floating_point_environment().
Referenced by xfexp().
fold_real32_from_int64()
enum fold_status fold_real32_from_int64 (float32_t * res, const int64_t * arg)
Definition at line 242 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xffloat(), xffloatu(), xfisint(), xflt64(), and xfrcp().
fold_real32_from_real128()
enum fold_status fold_real32_from_real128 (float32_t * res, const float128_t * arg)
Definition at line 269 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqtof().
fold_real32_from_real64()
enum fold_status fold_real32_from_real64 (float32_t * res, const float64_t * arg)
Definition at line 260 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xsngl().
fold_real32_from_uint64()
enum fold_status fold_real32_from_uint64 (float32_t * res, const uint64_t * arg)
Definition at line 251 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xfltu64().
fold_real32_log()
enum fold_status fold_real32_log (float32_t * res, const float32_t * arg)
Definition at line 422 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), logf(), res, and set_up_floating_point_environment().
Referenced by xflog().
fold_real32_log10()
enum fold_status fold_real32_log10 (float32_t * res, const float32_t * arg)
Definition at line 431 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), log10f(), res, and set_up_floating_point_environment().
Referenced by xflog10().
fold_real32_multiply()
enum fold_status fold_real32_multiply (float32_t * res, const float32_t * x, const float32_t * y)
Definition at line 323 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xfmul().
fold_real32_negate()
enum fold_status fold_real32_negate (float32_t * res, const float32_t * arg)
Definition at line 278 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xfneg().
fold_real32_pow()
enum fold_status fold_real32_pow (float32_t * res, const float32_t * x, const float32_t * y)
Definition at line 341 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), powf(), res, set_up_floating_point_environment(), x, and y.
Referenced by xfpow().
fold_real32_sin()
enum fold_status fold_real32_sin (float32_t * res, const float32_t * arg)
Definition at line 350 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), and sinf().
Referenced by xfsin().
fold_real32_sqrt()
enum fold_status fold_real32_sqrt (float32_t * res, const float32_t * arg)
Definition at line 296 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), and sqrtf().
Referenced by xfsqrt().
fold_real32_subtract()
enum fold_status fold_real32_subtract (float32_t * res, const float32_t * x, const float32_t * y)
Definition at line 314 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xfsub().
fold_real32_tan()
enum fold_status fold_real32_tan (float32_t * res, const float32_t * arg)
Definition at line 368 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), and tanf().
Referenced by xftan().
fold_real64_abs()
enum fold_status fold_real64_abs (float64_t * res, const float64_t * arg)
Definition at line 523 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), fabs, res, and set_up_floating_point_environment().
Referenced by xdabsv().
fold_real64_acos()
enum fold_status fold_real64_acos (float64_t * res, const float64_t * arg)
Definition at line 622 of file host-fp-folding.c.
References acos(), arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xdacos().
fold_real64_add()
enum fold_status fold_real64_add (float64_t * res, const float64_t * x, const float64_t * y)
Definition at line 541 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xdadd().
fold_real64_asin()
enum fold_status fold_real64_asin (float64_t * res, const float64_t * arg)
Definition at line 613 of file host-fp-folding.c.
References arg, asin(), check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xdasin().
fold_real64_atan()
enum fold_status fold_real64_atan (float64_t * res, const float64_t * arg)
Definition at line 631 of file host-fp-folding.c.
References arg, atan(), check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xdatan().
fold_real64_atan2()
enum fold_status fold_real64_atan2 (float64_t * res, const float64_t * x, const float64_t * y)
Definition at line 640 of file host-fp-folding.c.
References atan2(), check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xdatan2().
fold_real64_compare()
enum fold_relation fold_real64_compare (const float64_t * x, const float64_t * y)
Definition at line 131 of file host-fp-folding.c.
References COMPARE_BODY.
Referenced by xdcmp(), and xdisint().
fold_real64_cos()
enum fold_status fold_real64_cos (float64_t * res, const float64_t * arg)
Definition at line 595 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), cos(), res, and set_up_floating_point_environment().
Referenced by xdcos().
fold_real64_divide()
enum fold_status fold_real64_divide (float64_t * res, const float64_t * x, const float64_t * y)
Definition at line 568 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xddiv(), and xdrcp().
fold_real64_exp()
enum fold_status fold_real64_exp (float64_t * res, const float64_t * arg)
Definition at line 649 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), exp, res, and set_up_floating_point_environment().
Referenced by xdexp().
fold_real64_from_int64()
enum fold_status fold_real64_from_int64 (float64_t * res, const int64_t * arg)
Definition at line 478 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xdfloat(), xdfloatu(), xdflt64(), xdisint(), and xdrcp().
fold_real64_from_real128()
enum fold_status fold_real64_from_real128 (float64_t * res, const float128_t * arg)
Definition at line 505 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqtod().
fold_real64_from_real32()
enum fold_status fold_real64_from_real32 (float64_t * res, const float32_t * arg)
Definition at line 496 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xdble().
fold_real64_from_uint64()
enum fold_status fold_real64_from_uint64 (float64_t * res, const uint64_t * arg)
Definition at line 487 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xdfltu64().
fold_real64_log()
enum fold_status fold_real64_log (float64_t * res, const float64_t * arg)
Definition at line 658 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), log(), res, and set_up_floating_point_environment().
Referenced by xdlog().
fold_real64_log10()
enum fold_status fold_real64_log10 (float64_t * res, const float64_t * arg)
Definition at line 667 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), log10(), res, and set_up_floating_point_environment().
Referenced by xdlog10().
fold_real64_multiply()
enum fold_status fold_real64_multiply (float64_t * res, const float64_t * x, const float64_t * y)
Definition at line 559 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xdmul().
fold_real64_negate()
enum fold_status fold_real64_negate (float64_t * res, const float64_t * arg)
Definition at line 514 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xdneg().
fold_real64_pow()
enum fold_status fold_real64_pow (float64_t * res, const float64_t * x, const float64_t * y)
Definition at line 577 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), pow(), res, set_up_floating_point_environment(), x, and y.
Referenced by xdpow().
fold_real64_sin()
enum fold_status fold_real64_sin (float64_t * res, const float64_t * arg)
Definition at line 586 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), and sin().
Referenced by xdsin().
fold_real64_sqrt()
enum fold_status fold_real64_sqrt (float64_t * res, const float64_t * arg)
Definition at line 532 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), and sqrt().
Referenced by xdsqrt().
fold_real64_subtract()
enum fold_status fold_real64_subtract (float64_t * res, const float64_t * x, const float64_t * y)
Definition at line 550 of file host-fp-folding.c.
References check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), x, and y.
Referenced by xdsub().
fold_real64_tan()
enum fold_status fold_real64_tan (float64_t * res, const float64_t * arg)
Definition at line 604 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, set_up_floating_point_environment(), and tan().
Referenced by xdtan().
fold_sanity_check()
void fold_sanity_check (void)
Definition at line 51 of file host-fp-folding.c.
References assert.
fold_uint32_from_real128()
enum fold_status fold_uint32_from_real128 (uint32_t * res, const float128_t * arg)
Definition at line 696 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqfixu().
fold_uint32_from_real32()
enum fold_status fold_uint32_from_real32 (uint32_t * res, const float32_t * arg)
Definition at line 233 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xfixu().
fold_uint32_from_real64()
enum fold_status fold_uint32_from_real64 (uint32_t * res, const float64_t * arg)
Definition at line 460 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xdfixu().
fold_uint64_from_real128()
enum fold_status fold_uint64_from_real128 (uint64_t * res, const float128_t * arg)
Definition at line 705 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
Referenced by xqfixu64().
fold_uint64_from_real32()
enum fold_status fold_uint64_from_real32 (uint64_t * res, const float32_t * arg)
Definition at line 224 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
fold_uint64_from_real64()
enum fold_status fold_uint64_from_real64 (uint64_t * res, const float64_t * arg)
Definition at line 469 of file host-fp-folding.c.
References arg, check_and_restore_floating_point_environment(), res, and set_up_floating_point_environment().
interpret_exceptions()
static enum fold_status interpret_exceptions (int exceptions, int errno_capture) static
Definition at line 165 of file host-fp-folding.c.
References FOLD_INEXACT, FOLD_INVALID, FOLD_OK, FOLD_OVERFLOW, and FOLD_UNDERFLOW.
Referenced by check_and_restore_floating_point_environment().
set_up_floating_point_environment()
static void set_up_floating_point_environment (fenv_t * fenv) static
Definition at line 152 of file host-fp-folding.c.
References configure_denormals().
Referenced by fold_complex128_pow(), fold_complex32_pow(), fold_complex64_pow(), fold_int32_from_real128(), fold_int32_from_real32(), fold_int32_from_real64(), fold_int64_from_real128(), fold_int64_from_real32(), fold_int64_from_real64(), fold_real128_abs(), fold_real128_acos(), fold_real128_add(), fold_real128_asin(), fold_real128_atan(), fold_real128_atan2(), fold_real128_cos(), fold_real128_divide(), fold_real128_exp(), fold_real128_from_int64(), fold_real128_from_real32(), fold_real128_from_real64(), fold_real128_from_uint64(), fold_real128_log(), fold_real128_log10(), fold_real128_multiply(), fold_real128_negate(), fold_real128_pow(), fold_real128_sin(), fold_real128_sqrt(), fold_real128_subtract(), fold_real128_tan(), fold_real32_abs(), fold_real32_acos(), fold_real32_add(), fold_real32_asin(), fold_real32_atan(), fold_real32_atan2(), fold_real32_cos(), fold_real32_divide(), fold_real32_exp(), fold_real32_from_int64(), fold_real32_from_real128(), fold_real32_from_real64(), fold_real32_from_uint64(), fold_real32_log(), fold_real32_log10(), fold_real32_multiply(), fold_real32_negate(), fold_real32_pow(), fold_real32_sin(), fold_real32_sqrt(), fold_real32_subtract(), fold_real32_tan(), fold_real64_abs(), fold_real64_acos(), fold_real64_add(), fold_real64_asin(), fold_real64_atan(), fold_real64_atan2(), fold_real64_cos(), fold_real64_divide(), fold_real64_exp(), fold_real64_from_int64(), fold_real64_from_real128(), fold_real64_from_real32(), fold_real64_from_uint64(), fold_real64_log(), fold_real64_log10(), fold_real64_multiply(), fold_real64_negate(), fold_real64_pow(), fold_real64_sin(), fold_real64_sqrt(), fold_real64_subtract(), fold_real64_tan(), fold_uint32_from_real128(), fold_uint32_from_real32(), fold_uint32_from_real64(), fold_uint64_from_real128(), fold_uint64_from_real32(), and fold_uint64_from_real64().