flang: hpfutl.c File Reference
hpfutl.c File Reference
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "soc.h"
#include "semant.h"
#include "ast.h"
#include "gramtk.h"
#include "hpfutl.h"
#include "optimize.h"
#include "hlvect.h"
Functions
int mk_ceil_div (int num, int den)
int opt_binop (int opc, int op1, int op2, int dtype)
int opt_unop (int opc, int op, int dtype)
int opt_ast (int a)
int mk_size (int low, int high)
int search_basearr (int ast)
Function Documentation
mk_ceil_div()
int mk_ceil_div (int num, int den)
Definition at line 22 of file hpfutl.c.
References a, DT_INT, mk_cval(), num, one, OP_ADD, OP_DIV, OP_SUB, opt_ast(), and opt_binop().
mk_size()
int mk_size (int low, int high)
Definition at line 63 of file hpfutl.c.
References DT_INT, get_int_cval(), mk_cval(), OP_ADD, OP_SUB, opt_ast(), opt_binop(), and t.
Referenced by trans_mkproc().
opt_ast()
int opt_ast (int a)
Definition at line 53 of file hpfutl.c.
References a.
Referenced by mk_ceil_div(), and mk_size().
opt_binop()
int opt_binop (int opc, int op1, int op2, int dtype)
Definition at line 37 of file hpfutl.c.
References ast, dd_symbolic(), freearea(), HLV_AREA1, and mk_binop().
Referenced by canonical_conversion(), forall_2_sec(), handle_shift(), inline_shifts(), mk_ceil_div(), mk_size(), search_idx(), and triplet_extent().
opt_unop()
int opt_unop (int opc, int op, int dtype)
Definition at line 47 of file hpfutl.c.
References mk_unop().
Referenced by search_idx().
search_basearr()
int search_basearr (int ast)
Definition at line 81 of file hpfutl.c.
References ast, interr(), and search_basearr().
Referenced by search_basearr().