flang: ili-rewrite.h File Reference
ili-rewrite.h File Reference
#include "fastset.h"
Classes
struct ILI_coordinates
Visitation context structure passed to callbacks.
Macros
#define GetLiveILIs(coor) (coor->context)
Typedefs
typedef int(* ILI_visitor) (const struct ILI_coordinates *at)
typedef bool(* ILI_tree_scan_visitor) (void *visitor_context, int ili)
typedef struct ILI_coordinates ILI_coordinates
Visitation context structure passed to callbacks.
Functions
bool visit_ilis (ILI_visitor visitor, void *visitor_context, bool context_insensitive)
ILI rewriting driver. Returns TRUE if any change occurs.
int update_ili_operand (int ili, int opnd_index, int new_opnd)
Utility for callbacks: given an ILI index, create a new ILI in which one operand has been replaced.
void collect_root_ilis (fastset *root_ilis)
Collects the set of ILT root expression ILIs.
void collect_live_ilis (fastset *live)
Collects the set of live ILIs.
void collect_tree_ilis (fastset *tree_ilis, int ili, bool scan_cses)
Collects the set of ILIs in an ILI expression tree.
bool scan_ili_tree (ILI_tree_scan_visitor visitor, void *visitor_context, int ili)
ILI tree scanning in preorder with a callback. A true return from the callback causes the scan to immediately return TRUE. Does not descend into IL_CSExx operands; recurse thither from the visitor if that's what you really want.
Macro Definition Documentation
GetLiveILIs
#define GetLiveILIs (coor) (coor->context)
Definition at line 90 of file ili-rewrite.h.
Typedef Documentation
ILI_coordinates
typedef struct ILI_coordinates ILI_coordinates
Visitation context structure passed to callbacks.
ILI_tree_scan_visitor
typedef bool(* ILI_tree_scan_visitor) (void *visitor_context, int ili)
Definition at line 65 of file ili-rewrite.h.
ILI_visitor
typedef int(* ILI_visitor) (const struct ILI_coordinates *at)
Definition at line 63 of file ili-rewrite.h.
Function Documentation
collect_live_ilis()
void collect_live_ilis (fastset * live)
Collects the set of live ILIs.
Definition at line 431 of file ili-rewrite.cpp.
References CHECK, fastset_vacate(), noop_visitor(), and visit_ilis().
collect_root_ilis()
void collect_root_ilis (fastset * root_ilis)
Collects the set of ILT root expression ILIs.
Definition at line 404 of file ili-rewrite.cpp.
References BIH_ILTFIRST, BIH_LAST, BIH_NEXT, fastset_add(), fastset_vacate(), gbl, ili, ilt, ILT_ILIP, ILT_NEXT, rdilts(), and wrilts().
collect_tree_ilis()
void collect_tree_ilis (fastset * tree_ilis, int ili, bool scan_cses)
Collects the set of ILIs in an ILI expression tree.
Definition at line 462 of file ili-rewrite.cpp.
References collect_tree_ilis(), fastset_add(), fastset_contains(), IL_ISLINK, IL_OPRS, ili, ILI_ALT, ILI_OPC, ILI_OPND, is_cseili_opcode(), and j.
Referenced by collect_tree_ilis().
scan_ili_tree()
bool scan_ili_tree (ILI_tree_scan_visitor visitor, void * visitor_context, int ili)
ILI tree scanning in preorder with a callback. A true return from the callback causes the scan to immediately return TRUE. Does not descend into IL_CSExx operands; recurse thither from the visitor if that's what you really want.
Definition at line 440 of file ili-rewrite.cpp.
References IL_ISLINK, IL_OPRS, ili, ILI_ALT, ILI_OPC, ILI_OPND, is_cseili_opcode(), j, and scan_ili_tree().
Referenced by scan_ili_tree().
update_ili_operand()
int update_ili_operand (int ili, int opnd_index, int new_opnd)
Utility for callbacks: given an ILI index, create a new ILI in which one operand has been replaced.
Definition at line 374 of file ili-rewrite.cpp.
References addili(), ILI::alt, get_ili_ns(), IL_OPRS, ili, ILI_ALT, ILI_OPC, ILI_OPND, j, ILI::opc, and ILI::opnd.
visit_ilis()
bool visit_ilis (ILI_visitor visitor, void * visitor_context, bool context_insensitive)
ILI rewriting driver. Returns TRUE if any change occurs.
The traversal is in block sequence order, with the ILTs being visited in forward order within each block.
The void *visitor_context is passed to the visitation callback as at->context.
Set the "context_insensitive" flag to TRUE for faster processing when the rewriting visitor is known to not be sensitive to the context (i.e., it always maps ILI 'x' to the same 'y' in any statement).
Definition at line 302 of file ili-rewrite.cpp.
References ad1ili(), ILI_coordinates::bih, BIH_FT, BIH_ILTFIRST, BIH_LAST, BIH_NEXT, ILI_coordinates::context, dbgprintf, DEBUGGING, FREE, gbl, has_cse(), ILI_coordinates::ili, hidden_state::ili_backmap, hidden_state::ili_bih, hidden_state::ili_map, ILI_OPC, ilib, ILI_coordinates::ilt, ILT_BR, ILT_ILIP, ILT_NEXT, hidden_state::is_context_insensitive, j, hidden_state::limit, NEW, new_ili(), NULL, ILI_coordinates::original_ili, ILI_coordinates::parent, ILI_coordinates::parent_opnd, rdilts(), ILI_coordinates::this_ili_improved, visit_ili_operands(), ILI_coordinates::visitor, and wrilts().
Referenced by collect_live_ilis().