flang: ili-rewrite.cpp File Reference
ili-rewrite.cpp File Reference
#include "gbldefs.h"
#include "error.h"
#include "fastset.h"
#include "global.h"
#include "go.h"
#include "symtab.h"
#include "ili.h"
#include "ili-rewrite.h"
Classes
struct hidden_state
Macros
#define DEBUGGING (DBGBIT(64, 8) != 0)
Functions
static bool addili_changed_ili (int ili, const ILI *saved)
static bool is_jsr (int opc)
static int visit_ili_operands (bool *result_cse, const ILI_coordinates *at, struct hidden_state *state)
static int visit_nme_subscript (int nme, bool *operand_cse, ILI_coordinates *at, struct hidden_state *state)
bool visit_ilis (ILI_visitor visitor, void *visitor_context, bool is_context_insensitive)
ILI rewriting driver. Returns TRUE if any change occurs.
int update_ili_operand (int ili, int opnd_index, int new_opnd)
Utility for callbacks: given an ILI index, create a new ILI in which one operand has been replaced.
void collect_root_ilis (fastset *root_ilis)
Collects the set of ILT root expression ILIs.
static int noop_visitor (const ILI_coordinates *at)
void collect_live_ilis (fastset *live)
Collects the set of live ILIs.
bool scan_ili_tree (ILI_tree_scan_visitor visitor, void *visitor_context, int ili)
ILI tree scanning in preorder with a callback. A true return from the callback causes the scan to immediately return TRUE. Does not descend into IL_CSExx operands; recurse thither from the visitor if that's what you really want.
void collect_tree_ilis (fastset *tree_ilis, int ili, bool scan_cses)
Collects the set of ILIs in an ILI expression tree.
Macro Definition Documentation
DEBUGGING
#define DEBUGGING (DBGBIT(64, 8) != 0)
Definition at line 18 of file ili-rewrite.cpp.
Function Documentation
addili_changed_ili()
static bool addili_changed_ili (int ili, const ILI * saved) static
Definition at line 30 of file ili-rewrite.cpp.
References ILI::alt, IL_OPRS, ili, ILI_ALT, ILI_OPC, ILI_OPND, j, ILI::opc, and ILI::opnd.
Referenced by visit_ili_operands().
collect_live_ilis()
void collect_live_ilis (fastset * live)
Collects the set of live ILIs.
Definition at line 431 of file ili-rewrite.cpp.
References CHECK, fastset_vacate(), noop_visitor(), and visit_ilis().
collect_root_ilis()
void collect_root_ilis (fastset * root_ilis)
Collects the set of ILT root expression ILIs.
Definition at line 404 of file ili-rewrite.cpp.
References BIH_ILTFIRST, BIH_LAST, BIH_NEXT, fastset_add(), fastset_vacate(), gbl, ili, ilt, ILT_ILIP, ILT_NEXT, rdilts(), and wrilts().
collect_tree_ilis()
void collect_tree_ilis (fastset * tree_ilis, int ili, bool scan_cses)
Collects the set of ILIs in an ILI expression tree.
Definition at line 462 of file ili-rewrite.cpp.
References collect_tree_ilis(), fastset_add(), fastset_contains(), IL_ISLINK, IL_OPRS, ili, ILI_ALT, ILI_OPC, ILI_OPND, is_cseili_opcode(), and j.
Referenced by collect_tree_ilis().
is_jsr()
static bool is_jsr (int opc) static
Definition at line 46 of file ili-rewrite.cpp.
Referenced by visit_ili_operands().
noop_visitor()
static int noop_visitor (const ILI_coordinates * at) static
Definition at line 423 of file ili-rewrite.cpp.
References fastset_add(), GetLiveILIs, and ILI_coordinates::ili.
Referenced by collect_live_ilis().
scan_ili_tree()
bool scan_ili_tree (ILI_tree_scan_visitor visitor, void * visitor_context, int ili)
ILI tree scanning in preorder with a callback. A true return from the callback causes the scan to immediately return TRUE. Does not descend into IL_CSExx operands; recurse thither from the visitor if that's what you really want.
Definition at line 440 of file ili-rewrite.cpp.
References IL_ISLINK, IL_OPRS, ili, ILI_ALT, ILI_OPC, ILI_OPND, is_cseili_opcode(), j, and scan_ili_tree().
Referenced by scan_ili_tree().
update_ili_operand()
int update_ili_operand (int ili, int opnd_index, int new_opnd)
Utility for callbacks: given an ILI index, create a new ILI in which one operand has been replaced.
Definition at line 374 of file ili-rewrite.cpp.
References addili(), ILI::alt, get_ili_ns(), IL_OPRS, ili, ILI_ALT, ILI_OPC, ILI_OPND, j, ILI::opc, and ILI::opnd.
visit_ili_operands()
static int visit_ili_operands (bool * result_cse, const ILI_coordinates * at, struct hidden_state * state) static
Definition at line 106 of file ili-rewrite.cpp.
References addili(), addili_changed_ili(), ILI_coordinates::bih, CHECK, dbgprintf, DEBUGGING, dummy, get_ili_ns(), ILI_coordinates::has_cse, IL_ISLINK, IL_OPRFLAG, IL_OPRS, ILI_coordinates::ili, ILI_ALT, hidden_state::ili_backmap, hidden_state::ili_bih, hidden_state::ili_map, ILI_OPC, ILI_OPND, ILIO_NME, ILI_coordinates::ilt, hidden_state::is_context_insensitive, is_cseili_opcode(), is_jsr(), j, hidden_state::limit, NEED, new_ili(), ILI_coordinates::original_ili, ILI_coordinates::parent, ILI_coordinates::parent_opnd, result, ILI_coordinates::this_ili_improved, visit_ili_operands(), visit_nme_subscript(), and ILI_coordinates::visitor.
Referenced by visit_ili_operands(), visit_ilis(), and visit_nme_subscript().
visit_ilis()
bool visit_ilis (ILI_visitor visitor, void * visitor_context, bool context_insensitive)
ILI rewriting driver. Returns TRUE if any change occurs.
The traversal is in block sequence order, with the ILTs being visited in forward order within each block.
The void *visitor_context is passed to the visitation callback as at->context.
Set the "context_insensitive" flag to TRUE for faster processing when the rewriting visitor is known to not be sensitive to the context (i.e., it always maps ILI 'x' to the same 'y' in any statement).
Definition at line 302 of file ili-rewrite.cpp.
References ad1ili(), ILI_coordinates::bih, BIH_FT, BIH_ILTFIRST, BIH_LAST, BIH_NEXT, ILI_coordinates::context, dbgprintf, DEBUGGING, FREE, gbl, has_cse(), ILI_coordinates::ili, hidden_state::ili_backmap, hidden_state::ili_bih, hidden_state::ili_map, ILI_OPC, ilib, ILI_coordinates::ilt, ILT_BR, ILT_ILIP, ILT_NEXT, hidden_state::is_context_insensitive, j, hidden_state::limit, NEW, new_ili(), NULL, ILI_coordinates::original_ili, ILI_coordinates::parent, ILI_coordinates::parent_opnd, rdilts(), ILI_coordinates::this_ili_improved, visit_ili_operands(), ILI_coordinates::visitor, and wrilts().
Referenced by collect_live_ilis().
visit_nme_subscript()
static int visit_nme_subscript (int nme, bool * operand_cse, ILI_coordinates * at, struct hidden_state * state) static
Definition at line 77 of file ili-rewrite.cpp.
References add_arrnme(), addnme(), base, ILI_coordinates::ili, NME_CNST, NME_INLARR, NME_NM, NME_SUB, NME_SYM, NME_TYPE, NME_VOL, NT_ARR, NT_IND, NT_MEM, ILI_coordinates::original_ili, sub, visit_ili_operands(), and visit_nme_subscript().
Referenced by visit_ili_operands(), and visit_nme_subscript().