flang: ilidir.c File Reference
ilidir.c File Reference
ILI directive module.
#include "ilidir.h"
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "fdirect.h"
Macros
#define TR0(s)
#define TR1(s, a)
#define TR2(s, a, b)
#define TR3(s, a, b, c)
#define STK_SZ 128
Functions
static int find_lpprg (int line)
Find the set of loop pragmas associated with a line number (the set's beginning and ending line numbers enclose the requested line number).
void ili_lpprg_init (void)
All blocks have been created for a function (called at end of expand).
void open_pragma (int line)
Find and open the set of loop pragmas associated with a line number.
void close_pragma (void)
Close the current pragmas => load the pragmas which have routine scope.
void push_pragma (int line)
Find and open and stack the set of loop pragmas associated with a line number.
void pop_pragma (void)
Pop the set from the stack and open/restore the set which is on the top of stack.
Variables
static int first
static bool opened
static int stk [STK_SZ]
static int top = 0
Detailed Description
ILI directive module.
Utility routines are valid after the semantic analyzer and after basic blocks have been created for a function.
Definition in file ilidir.c.
Macro Definition Documentation
STK_SZ
#define STK_SZ 128
Definition at line 198 of file ilidir.c.
TR0
#define TR0 (s)
Definition at line 37 of file ilidir.c.
TR1
#define TR1 (s, a)
Definition at line 38 of file ilidir.c.
TR2
#define TR2 (s, a, b)
Definition at line 39 of file ilidir.c.
TR3
#define TR3 (s, a, b, c)
Definition at line 40 of file ilidir.c.
Function Documentation
close_pragma()
void close_pragma (void)
Close the current pragmas => load the pragmas which have routine scope.
...
Definition at line 105 of file ilidir.c.
References direct, load_dirset(), NULL, opened, and DIRECT::rou_begin.
Referenced by eliminate_redundant(), emit_copy_section(), emit_gatherx(), emit_scatterx_gatherx(), forall_dependency(), forall_dependency_scalarize(), hoist_loop(), lflow_of_block(), optimize(), resolve_pp(), resolve_pv(), rewrite_calls(), and schedule().
find_lpprg()
static int find_lpprg (int line) static
Find the set of loop pragmas associated with a line number (the set's beginning and ending line numbers enclose the requested line number).
Since the loop sets occur in lexical order, the last loop set found is the set with beginning line number is the floor of the requested line number.
Definition at line 176 of file ilidir.c.
References DIRECT::avail, lpprg_::beg_line, direct, first, i, line, DIRECT::lpg, match(), DIRECT::stgb, and TR2.
Referenced by open_pragma(), and push_pragma().
ili_lpprg_init()
void ili_lpprg_init (void)
All blocks have been created for a function (called at end of expand).
...
Definition at line 55 of file ilidir.c.
References DIRECT::avail, lpprg_::beg_line, direct, lpprg_::end_line, first, GBL_CURRFUNC, i, DIRECT::lpg, DIRECT::stgb, SYMNAME, TR1, and TR3.
Referenced by expand().
open_pragma()
void open_pragma (int line)
Find and open the set of loop pragmas associated with a line number.
...
SHOULD have a matching close_pragma().
Definition at line 81 of file ilidir.c.
References lpprg_::beg_line, direct, lpprg_::dirset, lpprg_::end_line, find_lpprg(), line, load_dirset(), DIRECT::lpg, match(), opened, DIRECT::stgb, and TR2.
Referenced by eliminate_redundant(), forall_dependency(), forall_dependency_scalarize(), hoist_loop(), lflow_of_block(), optimize(), resolve_pp(), resolve_pv(), rewrite_calls(), and schedule().
pop_pragma()
void pop_pragma (void)
Pop the set from the stack and open/restore the set which is on the top of stack.
...
Definition at line 240 of file ilidir.c.
References direct, lpprg_::dirset, ERR_Severe, gbl, interr(), load_dirset(), DIRECT::lpg, match(), DIRECT::rou_begin, DIRECT::stgb, stk, top, TR0, and TR1.
push_pragma()
void push_pragma (int line)
Find and open and stack the set of loop pragmas associated with a line number.
...
MUST have a matching pop_pragma(). If a match isn't found, push the routine's set.
Definition at line 211 of file ilidir.c.
References lpprg_::beg_line, direct, lpprg_::dirset, lpprg_::end_line, ERR_Severe, find_lpprg(), interr(), line, load_dirset(), DIRECT::lpg, match(), DIRECT::rou_begin, DIRECT::stgb, stk, STK_SZ, top, TR0, and TR2.
Variable Documentation
first
int first static
Definition at line 44 of file ilidir.c.
Referenced by find_lpprg(), and ili_lpprg_init().
opened
bool opened static
Definition at line 46 of file ilidir.c.
Referenced by __INT_T(), close_pragma(), ENTCRF90IO(), ENTF90IO(), inquire(), and open_pragma().
stk
int stk[STK_SZ] static
Definition at line 200 of file ilidir.c.
Referenced by chk_expr(), chk_fmtid(), chk_unitid(), chk_var(), dumpsst(), gen_spec_item_tmp(), is_sst_const(), is_varref(), pop_pragma(), push_pragma(), put_ffield(), and put_vlist().
top
int top = 0 static
Definition at line 201 of file ilidir.c.
Referenced by pop_pragma(), and push_pragma().