flang: ilidir.h File Reference
ilidir.h File Reference
Functions
void close_pragma (void)
...
void ili_lpprg_init (void)
...
void open_pragma (int line)
...
void pop_pragma (void)
...
void push_pragma (int line)
...
Function Documentation
close_pragma()
void close_pragma (void)
...
...
Definition at line 105 of file ilidir.c.
ili_lpprg_init()
void ili_lpprg_init (void)
...
...
Definition at line 55 of file ilidir.c.
References DIRECT::avail, lpprg_::beg_line, direct, lpprg_::end_line, first, GBL_CURRFUNC, i, DIRECT::lpg, DIRECT::stgb, SYMNAME, TR1, and TR3.
Referenced by expand().
open_pragma()
void open_pragma (int line)
...
...
SHOULD have a matching close_pragma().
Definition at line 81 of file ilidir.c.
pop_pragma()
void pop_pragma (void)
...
...
Definition at line 240 of file ilidir.c.
References direct, lpprg_::dirset, ERR_Severe, gbl, interr(), load_dirset(), DIRECT::lpg, match(), DIRECT::rou_begin, DIRECT::stgb, stk, top, TR0, and TR1.
push_pragma()
void push_pragma (int line)
...
...
MUST have a matching pop_pragma(). If a match isn't found, push the routine's set.
Definition at line 211 of file ilidir.c.
References lpprg_::beg_line, direct, lpprg_::dirset, lpprg_::end_line, ERR_Severe, find_lpprg(), interr(), line, load_dirset(), DIRECT::lpg, match(), DIRECT::rou_begin, DIRECT::stgb, stk, STK_SZ, top, TR0, and TR2.