flang: ilitp.cpp File Reference
ilitp.cpp File Reference
#include "universal.h"
#include "scutil.h"
#include "sharedefs.h"
#include "ili.h"
#include "utils.h"
Classes
struct processed_flags
Macros
#define ISZ_T INT
#define UISZ_T UINT
#define STASH(string) strcpy((char*)malloc(strlen(string) + 1), string)
Functions
static void do_IL_line (int pass)
static void do_AT_line (void)
static void do_CG_line (void)
static void do_latency (const char *lat, int shift)
static void do_SI_line (void)
static int lookup_ili (const char *name)
static void error (const char *text, const char *additional_text=nullptr)
static bool match (const std::string &s, const char *nroffCmd)
Return true iff s begins with first 3 characters of nroffCmd.
static bool introduces_ILI (const std::string &buff)
static bool elaborates_ILI (const std::string &buff)
static int get_template_size (std::string &buff)
static void get_template_expansion (std::string &buff)
static void open_input_file (const char *filename)
static bool get_input_line (std::string &buff)
int main (int argc, char *argv[])
...
Variables
static int opcode_num = 0
static int max_ili_num
static std::string buff
std::vector< processed_flags > processed
ILIINFO ilis [1050]
SCHINFO schinfo [1050]
static std::string template_buff
static int template_size
static int template_index = -1
static int template_base_opcode_num = -1
static NroffInStream input_file
Macro Definition Documentation
ISZ_T
#define ISZ_T INT
Definition at line 42 of file ilitp.cpp.
STASH
#define STASH (string) strcpy((char*)malloc(strlen(string) + 1), string)
Definition at line 75 of file ilitp.cpp.
UISZ_T
#define UISZ_T UINT
Definition at line 43 of file ilitp.cpp.
Function Documentation
do_AT_line()
static void do_AT_line (void) static
Definition at line 542 of file ilitp.cpp.
References ILIINFO::attr, buff, error(), i, IL_IATYPE, IL_OPRFLAG, IL_SSENME, ILIA_128, ILIA_256, ILIA_512, ILIA_AR, ILIA_CD, ILIA_CQ, ILIA_CS, ILIA_CSE, ILIA_DOM, ILIA_DOUBLEDOUBLE, ILIA_DP, ILIA_FLOAT128, ILIA_HP, ILIA_IR, ILIA_KR, ILIA_LNK, ILIA_QP, ILIA_SP, ILIA_TRM, ILIA_X87, ILIO_ARLNK, ILIO_NME, ilis, ILTY_ARTH, ILTY_BRANCH, ILTY_CONS, ILTY_DEFINE, ILTY_LOAD, ILTY_MOVE, ILTY_OTHER, ILTY_PLOAD, ILTY_PROC, ILTY_PSTORE, ILTY_STORE, opcode_num, and processed.
Referenced by main().
do_CG_line()
static void do_CG_line (void) static
Definition at line 688 of file ilitp.cpp.
References ILIINFO::accel, ILIINFO::asm_nop, ILIINFO::asm_special, ILIINFO::avx3_special, ILIINFO::avx_only, ILIINFO::avx_special, buff, ILIINFO::ccarith, ILIINFO::cclogical, ILIINFO::ccmod, ILIINFO::CGonly, ILIINFO::conditional_branch, error(), i, ilis, lookup_ili(), ILIINFO::memarg, ILIINFO::memdest, ILIINFO::move, name, ILIINFO::notAILI, ILIINFO::notCG, NULL, ILIINFO::opcod, opcode_num, processed, ILIINFO::replaceby, ILIINFO::shiftop, ILIINFO::size, ILIINFO::sse_avx, ILIINFO::ssedp, ILIINFO::ssest, STASH, and ILIINFO::terminal.
Referenced by main().
do_IL_line()
static void do_IL_line (int pass) static
Definition at line 425 of file ilitp.cpp.
References buff, error(), i, ILIO_128LNK, ILIO_256LNK, ILIO_512LNK, ILIO_AR, ILIO_ARLNK, ILIO_CD, ILIO_CDLNK, ILIO_CQLNK, ILIO_CS, ILIO_CSLNK, ILIO_DOUBLEDOUBLE, ILIO_DOUBLEDOUBLELNK, ILIO_DP, ILIO_DPLNK, ILIO_FLOAT128LNK, ILIO_HP, ILIO_HPLNK, ILIO_IR, ILIO_IRLNK, ILIO_KR, ILIO_KRLNK, ILIO_LNK, ILIO_NME, ILIO_QP, ILIO_QPLNK, ILIO_SP, ILIO_SPLNK, ILIO_STC, ILIO_SYM, ILIO_X87, ILIO_X87LNK, ILIO_XMM, ilis, k, MAX_OPNDS, name, ILIINFO::name, opcode_num, ILIINFO::oprflag, ILIINFO::oprs, processed, schinfo, STASH, token, and zero.
Referenced by main().
do_latency()
static void do_latency (const char * lat, int shift) static
Definition at line 815 of file ilitp.cpp.
References error(), SCHINFO::latency, opcode_num, RM_SHIFT, schinfo, and shift.
Referenced by do_SI_line().
do_SI_line()
static void do_SI_line (void) static
Definition at line 846 of file ilitp.cpp.
References SCHINFO::attrs, buff, DEC_DBL, DEC_DIR, DEC_VEC, do_latency(), error(), i, LD_SHIFT, opcode_num, P_FADD, P_FMUL, P_FST, processed, RM_SHIFT, SCH_ATTR, schinfo, shift, and ST_SHIFT.
Referenced by main().
elaborates_ILI()
static bool elaborates_ILI (const std::string & buff) static
Definition at line 108 of file ilitp.cpp.
References buff, and match().
Referenced by get_input_line().
error()
static void error (const char * text, const char * additional_text) static
Print an error message.
Definition at line 932 of file ilitp.cpp.
References input_file.
Referenced by do_AT_line(), do_CG_line(), do_IL_line(), do_latency(), do_SI_line(), get_template_expansion(), get_template_size(), lookup_ili(), main(), and open_input_file().
get_input_line()
static bool get_input_line (std::string & buff) static
Get next line of input, expanding any include files (.so directives) or implicit templates ({...}).
Definition at line 215 of file ilitp.cpp.
References buff, elaborates_ILI(), get_template_expansion(), get_template_size(), getline(), input_file, introduces_ILI(), opcode_num, template_base_opcode_num, template_buff, template_index, and template_size.
Referenced by main().
get_template_expansion()
static void get_template_expansion (std::string & buff) static
Definition at line 160 of file ilitp.cpp.
References buff, error(), i, p, template_buff, template_index, and template_size.
Referenced by get_input_line().
get_template_size()
static int get_template_size (std::string & buff) static
Definition at line 137 of file ilitp.cpp.
References buff, error(), s, and size.
Referenced by get_input_line().
introduces_ILI()
static bool introduces_ILI (const std::string & buff) static
Definition at line 86 of file ilitp.cpp.
References buff, and match().
Referenced by get_input_line(), and main().
lookup_ili()
static int lookup_ili (const char * name) static
Definition at line 913 of file ilitp.cpp.
References error(), i, ilis, max_ili_num, and name.
Referenced by do_CG_line().
main()
int main (int argc, char * argv[])
...
...
Parameters
argc number of command-line arguments \pram argv array of command-line argument strings
...
Definition at line 269 of file ilitp.cpp.
References buff, collectIncludePaths(), do_AT_line(), do_CG_line(), do_IL_line(), do_SI_line(), error(), fclose(), FILE, get_input_line(), i, ilis, introduces_ILI(), j, match(), max_ili_num, MAX_OPNDS, name, NULL, opcode_num, open_input_file(), processed, schinfo, and size.
match()
static bool match (const std::string & s, const char * nroffCmd) static
Return true iff s begins with first 3 characters of nroffCmd.
Definition at line 79 of file ilitp.cpp.
References s.
Referenced by elaborates_ILI(), introduces_ILI(), and main().
open_input_file()
static void open_input_file (const char * filename) static
Open an input file and push it on the file filestack.
Definition at line 205 of file ilitp.cpp.
References error(), filename, and input_file.
Referenced by main().
Variable Documentation
buff
std::string buff static
Definition at line 51 of file ilitp.cpp.
Referenced by do_AT_line(), do_CG_line(), do_IL_line(), do_SI_line(), elaborates_ILI(), get_input_line(), get_template_expansion(), get_template_size(), introduces_ILI(), and main().
ilis
ILIINFO ilis[1050]
Definition at line 64 of file ilitp.cpp.
Referenced by _printili(), add_sincos_imap_loads(), addarth(), block_branches_to(), build_csed_list(), chk_block(), compl_br(), dmp_rat(), do_AT_line(), do_CG_line(), do_IL_line(), dump_cand(), exp_estmt(), exp_label(), exp_mac(), get_ili(), lookup_ili(), main(), remove_from_csed_list(), rlleFindLL(), rlleReplace(), ILMTPApp::run(), schedule(), sincos_argument_valid(), sincos_input_uses(), srcfunc(), verify_ili_aux(), widenAddNarrowVars(), widenAddressArithmetic(), widenAnyAddressing(), widenApplyCse(), widenApplyVarMap(), and widenElimAddrTaken().
input_file
NroffInStream input_file static
Definition at line 201 of file ilitp.cpp.
Referenced by error(), get_input_line(), and open_input_file().
max_ili_num
int max_ili_num static
Definition at line 50 of file ilitp.cpp.
Referenced by lookup_ili(), and main().
opcode_num
int opcode_num = 0 static
Definition at line 49 of file ilitp.cpp.
Referenced by do_AT_line(), do_CG_line(), do_IL_line(), do_latency(), do_SI_line(), get_input_line(), and main().
processed
std::vector<processed_flags> processed
Definition at line 62 of file ilitp.cpp.
Referenced by do_AT_line(), do_CG_line(), do_IL_line(), do_SI_line(), and main().
schinfo
SCHINFO schinfo[1050]
Definition at line 65 of file ilitp.cpp.
Referenced by do_IL_line(), do_latency(), do_SI_line(), and main().
template_base_opcode_num
int template_base_opcode_num = -1 static
Definition at line 134 of file ilitp.cpp.
Referenced by get_input_line().
template_buff
std::string template_buff static
Definition at line 120 of file ilitp.cpp.
Referenced by get_input_line(), and get_template_expansion().
template_index
int template_index = -1 static
Definition at line 131 of file ilitp.cpp.
Referenced by get_input_line(), and get_template_expansion().
template_size
int template_size static
Definition at line 125 of file ilitp.cpp.
Referenced by get_input_line(), and get_template_expansion().