flang: iliutil.cpp File Reference
iliutil.cpp File Reference
ILI utility module.
#include "pgifeat.h"
#include "iliutil.h"
#include "exputil.h"
#include "expreg.h"
#include "regutil.h"
#include "machreg.h"
#include "expand.h"
#include "machar.h"
#include "outliner.h"
#include "assem.h"
#include "mach.h"
#include "dtypeutl.h"
#include "llutil.h"
#include "llassem.h"
#include "llmputil.h"
#include "expsmp.h"
#include "verify.h"
#include "nme.h"
#include <stdarg.h>
#include "scutil.h"
#include "symfun.h"
#include "mth.h"
Classes
union ATOMIC_ENCODER
struct rewrtstruct
struct argtype
Macros
#define EXPANDER_DECLARE_INTERNAL
#define IL_spfunc IL_DFRSP
#define IL_dpfunc IL_DFRDP
#define IL_qpfunc IL_DFRQP
#define mk_prototype (SPTR) mk_prototype_llvm
#define ILTABSZ 5
#define ILHSHSZ 173
#define MAXILIS 67108864
#define GARB_UNREACHABLE 0
#define GARB_VISITED 1
#define CCRelationILIOpnd(p, n) (p)->opnd[n]
#define DTypeILIOpnd(p, n) (p)->opnd[n]
#define ConvertMSZ(n) (n)
#define ConvertATOMIC_RMW_OP(n) (n)
#define sptrGetILI get_ili
#define IS_FLT0 is_flt0
#define IS_DBL0 is_dbl0
#define IS_QUAD0 is_quad0
#define GETVAL64(a, b)
#define GETVALI64(a, b)
#define GETVAL128(a, b)
#define GETVALI128(a, b)
#define RED_DAMV (!XBIT(15, 0x100))
#define __MAXPOW 10
#define OT_UNARY 1
#define OT_BINARY 2
#define OT_LEAF 3
#define SIZEOF(array) (sizeof(array) / sizeof(char *))
Typedefs
typedef struct rewrtstruct rewrtstruct
Functions
static int addarth (ILI *ilip)
adds arithmetic ili
static int red_iadd (int ilix, INT con)
constant folds the integer add ili (iadd)
static int red_kadd (int ilix, INT con[2])
constant folds the integer*8 add ili (kadd)
static int red_aadd (int ilix, SPTR sym, ISZ_T off, int scale)
constant folds the address add ili (aadd)
static int red_damv (int opr, int damv, int scale)
combines the operand of damv's in an aadd expr
static int red_minmax (ILI_OP, int, int)
static int red_negate (int old, ILI_OP neg_opc, int mult_opc, int div_opc)
Transform -(c<OP>x<OP>y) into (-c)<OP>x<OP>y; OP is a mult or divide.
static int addbran (ILI *ilip)
adds branch ili
static int addother (ILI *)
static INT icmp (INT v1, INT v2)
compare two INTs
static INT cmp_to_log (INT val, int rel)
convert a compare value to a logical value for a relation
static bool isub_ovf (INT c1, INT c2, INT *r)
Subtract two integers and check for overflow.
static bool iadd_ovf (INT c1, INT c2, INT *r)
Add two integers and check for overflow.
static int get_ili (ILI *ilip)
enter ili into ILI area by attempting to share
static int new_ili (ILI *ilip)
enter ili into ILI area (no sharing)
static int ad1altili (ILI_OP opc, int opn1, int alt)
add an ili with one operand which has an alternate
static int ad2altili (ILI_OP opc, int opn1, int opn2, int alt)
Add an ili with two operands which has an alternate.
static int ad3altili (ILI_OP opc, int opn1, int opn2, int opn3, int alt)
Add an ili with three operands which has an alternate.
static int ad2func_int (ILI_OP opc, const char *name, int opn1, int opn2)
Add func call with 2 integer arguments returning integer value.
static int gen_sincos (ILI_OP, int, ILI_OP, ILI_OP, MTH_FN, DTYPE, ILI_OP)
static bool do_newton_sqrt (void)
static int _pwr2 (INT val, int max_pwr)
Determine if 'val' is a power of 2; the range of the powers is 1 ... max_pwr, inclusive.
static int _kpwr2 (INT cv1, INT cv2, int max_pwr)
Determine if the 64-bit value represented by (cv1<<32)+cv2 is a power of 2; the range of the powers is 1 ... max_pwr, inclusive.
static int _ipowi (int, int)
static int _xpowi (int, int, ILI_OP)
static int _frsqrt (int)
static int _mkfunc (const char *)
static int DblIsSingle (SPTR dd)
static int _lshift_one (int ili)
Check if the expression is shifting one left; if so, return its the shift count.
static int cmpz_of_cmp (int, CC_RELATION)
static bool is_zero_one (int)
static bool _is_nanf (int)
static INT value_of_irlnk_operand (int ilix, int default_value)
void ili_init (void)
initialize ili area
void ili_cleanup (void)
...
int addili (ILI *ilip)
principle add ili routine
int ad1ili (ILI_OP opc, int opn1)
add ili with one operand
int ad2ili (ILI_OP opc, int opn1, int opn2)
add ili with two operands
static int ad1func_cmplx (ILI_OP opc, char *name, int opn1)
Add func call with 1 complex argument returning complex value.
static int ad2func_cmplx (ILI_OP opc, char *name, int opn1, int opn2)
Add func call with 2 arguments returning complex value.
static int ad1func_cmplx_abi (ILI_OP opc, char *name, int opn1)
Add func call with 1 complex argument returning complex value.
static int ad2func_cmplx_abi (ILI_OP opc, char *name, int opn1, int opn2)
Add func call with 2 arguments returning complex value.
static int ad1mathfunc_cmplx (MTH_FN fn, ILI_OP opc, int op1, DTYPE res_dt, DTYPE arg1_dt)
Add func call with 1 complex argument returning complex value.
static int ad2mathfunc_cmplx (MTH_FN fn, ILI_OP opc, int op1, int op2, DTYPE res_dt, DTYPE arg1_dt, DTYPE arg2_dt)
Add func call with 2 complex arguments returning complex value.
static int ad_func (ILI_OP result_opc, ILI_OP call_opc, const char *func_name, int nargs,...)
char * gnr_math (const char *root, int widthc, int typec, const char *oldname, int masked)
...
static char * vect_math (MTH_FN fn, const char *root, int nargs, DTYPE vdt, int vopc, int vdt1, int vdt2, bool mask)
char * fast_math (const char *root, int widthc, int typec, const char *oldname)
...
char * relaxed_math (const char *root, int widthc, int typec, const char *oldname)
Called if and only if there exists the possiblity of a -Mfprelaxed=intrinsic version of the routine.
int ad2func_kint (ILI_OP opc, const char *name, int opn1, int opn2)
Add func call with 2 integer*8 arguments returning integer*8 value.
int ad3ili (ILI_OP opc, int opn1, int opn2, int opn3)
add ili with three operands
int ad4ili (ILI_OP opc, int opn1, int opn2, int opn3, int opn4)
add ili with four operands
static int ad4altili (ILI_OP opc, int opn1, int opn2, int opn3, int opn4, int alt)
int ad5ili (ILI_OP opc, int opn1, int opn2, int opn3, int opn4, int opn5)
add ili with five operands
int ad_icon (INT val)
add ICON ili with specified constant value
int ad_kcon (INT m32, INT l32)
Add KCON ili of an 64-bit constant whose value consists of m32 (most significant 32 bits) and l32 (least significant 32 bits).
int ad_kconi (ISZ_T v)
Add kcon ili of an 64-bit constant.
int ad_aconi (ISZ_T val)
add ACON ili with specified (integer) constant
int ad_aconk (INT m32, INT l32)
Add acon ili of an 64-bit constant whose value consists of m32 (most significant 32 bits) and l32 (least significant 32 bits).
int ad_acon (SPTR sym, ISZ_T val)
add ACON ili with specified symbol and offset
int ad_cse (int ilix)
add CSE ili of an ili
int ad_load (int stx)
Given a store ILI, generate the equivalent load ILI.
int ad_free (int ilix)
Add a IL_FREEx with given operand.
int ili_opnd (int ilix, int n)
return nth operand of ili - skipping past CSE ili if present
ILI_OP ldopc_from_stopc (ILI_OP stopc)
Given a store opc, return a corresponding load opc.
void ldst_msz (DTYPE dtype, ILI_OP *ld, ILI_OP *st, MSZ *siz)
...
static int lg (unsigned d)
Return i such that 2**i > |n| >= 2**(i+1)
static int lg64 (DBLUINT64 d)
void choose_multiplier (int N, unsigned dd, int prec)
...
void choose_multiplier_64 (int N, DBLUINT64 dd, int prec)
...
static int ICON (INT v)
static int MULSH (int ilix, int iliy)
static int KMULSH (int ilix, int iliy)
static int KMULUH (int ilix, int iliy)
static int MULUH (int ilix, int iliy)
static int MUL (int ilix, int iliy)
static int KMUL (int ilix, int iliy)
static int XSIGN (int ilix, int N)
static int KXSIGN (int ilix, int N)
static int reciprocal_division (int n, INT divisor, int sgnd)
static int reciprocal_division_64 (int n, DBLINT64 divisor, int sgnd)
static int reciprocal_mod (int n, int d, int sgnd)
static int reciprocal_mod_64 (int n, DBLINT64 d, int sgnd)
static bool _is_nand (SPTR sptr)
bool is_floating_comparison_opcode (ILI_OP opc)
...
int compl_br (int ilix, int lbl)
adds a branch ili by complementing the condition
int get_ili_ns (ILI *ilip)
...
static void mark_ili (int)
static int sort_free_list (int head)
Sort the free list.
void garbage_collect (void(*mark_function)(int))
...
static void mark_nme (int, int)
static void mark_ilitree (int ili, int val)
bool func_in (int ilix)
Search the ili subtree located by ilix for functions.
bool qjsr_in (int ilix)
Search the ili subtree located by ilix for QJSRs.
bool _find_ili (int ilix, int find_this)
...
bool find_ili (int tree, int it)
determine if an ili occurs in an ili subtree
static int rewr_ (int)
static int rewr_nm (int)
static bool has_nme (int)
static void rewr_cln (int)
static void rewr_cln_nm (int)
void rewr_these_ili (int oldili, int newili)
...
void rewr_these_ili_nme (int oldili, int newili, int oldnme, int newnme)
...
int get_rewr_new_nme (int nmex)
...
int save_rewr_count (void)
...
void restore_rewr_count (int c)
...
int rewr_ili (int tree, int old, int New)
...
int rewr_ili_nme (int tree, int oldili, int newili, int oldnme, int newnme, int douse, int dodef)
...
static int rewr_indirect_nme (int nmex)
static int build_pointer_tree (int ilix, ISZ_T offset)
void rewr_cln_ili (void)
...
static void prsym (int sym, FILE *ff)
static ILI_OP opc_comp_zero_one (int cmp_ili, int *invert_cc, int *label_op)
int simplified_cmp_ili (int cmp_ili)
returns simplified version of comparison ili
const char * dump_msz (MSZ ms)
...
static const char * atomic_origin_name (ATOMIC_ORIGIN origin)
static const char * atomic_rmw_op_name (ATOMIC_RMW_OP op)
void dump_atomic_info (FILE *f, ATOMIC_INFO info)
...
void dump_ili (FILE *f, int i)
...
static void dilitree (int i)
void dmpili (void)
ILI dump routine.
static void prnme (int opn, int ili)
static void prcon (int sptr)
static int optype (ILI_OP opc)
void prilitree (int i)
...
void dmpilitree (int i)
...
void ddilitree (int i, int flag)
...
void _ddilitree (int i, int flag)
...
static int get_encl_function (int sptr)
static SPTR find_host_function ()
Finds the corresponding host function of the device outlined function.
bool is_llvm_local_private (int sptr)
...
bool is_llvm_local (int sptr, int funcsptr)
...
static int ll_internref_ili (SPTR sptr)
static int ll_taskprivate_inhost_ili (SPTR sptr)
static int ll_uplevel_addr_ili (SPTR sptr, bool is_task_priv)
int mk_charlen_parref_sptr (SPTR sptr)
...
int mk_address (SPTR sptr)
create ili representing the address of a variable
int compute_address (SPTR sptr)
...
int ili_traverse (int(*visit_f)(int), int ilix)
Initialize for a traversal and call the traversal routine.
void ili_visit (int ilix, int v)
Add an ili to visit_list and set its VISIT field.
void ili_unvisit (void)
Clear the VISIT & VLIST fields of the ili in the visit_list.
static int _jsrsearch (int ilix)
Look for 'JSR' in this tree.
int jsrsearch (int ilix)
Search for "jsrs".
int alt_qjsr (int ilix)
...
int qjsrsearch (int ilix)
Look for 'QJSR' in this tree.
int ili_get_vect_arg_count (int ilix)
If a VECT ili, return its dtype, 0 otherwise.
DTYPE ili_get_vect_dtype (int ilix)
...
MSZ mem_size (TY_KIND ty)
Return MSZ_ for each datatype, or -1 if an aggregate type.
ISZ_T get_isz_conili (int ili)
...
int sel_icnst (ISZ_T val, int isi8)
Select an integer constant ili, ICON or KCON.
int sel_iconv (int ili, int isi8)
Select an integer conversion: IR/KR to IR, or IR/KR to KR.
int sel_decr (int ili, int isi8)
Select an IR or KR substract by 1.
int sel_aconv (int ili)
Select an IR or KR conversion to AR.
int is_argili_opcode (ILI_OP opc)
...
int is_cseili_opcode (ILI_OP opc)
...
int is_freeili_opcode (ILI_OP opc)
...
int is_mvili_opcode (ILI_OP opc)
...
int is_rgdfili_opcode (ILI_OP opc)
...
int is_daili_opcode (ILI_OP opc)
...
int is_dfrili_opcode (ILI_OP opc)
...
bool is_integer_comparison_opcode (ILI_OP opc)
...
bool is_unsigned_opcode (ILI_OP opc)
...
int has_cse (int ilix)
...
int mkfunc_avx (char *nmptr, int avxp)
...
int ili_subscript (int sub)
...
int ili_isdeleted (int ili)
...
void initcallargs (int count)
...
void addcallarg (int ili, int nme, int dtype)
...
int gencallargs (void)
...
int genretvalue (int ilix, ILI_OP resultopc)
...
int ilstckind (ILI_OP opc, int opnum)
...
const char * scond (int c)
...
int ikmove (int ilix)
...
int uikmove (int ilix)
...
int kimove (int ilix)
...
CC_RELATION complement_int_cc (CC_RELATION cc)
...
CC_RELATION complement_ieee_cc (CC_RELATION cc)
...
CC_RELATION commute_cc (CC_RELATION cc)
...
CC_RELATION combine_int_ccs (CC_RELATION binary_cc, CC_RELATION zero_cc)
...
CC_RELATION combine_ieee_ccs (CC_RELATION binary_cc, CC_RELATION zero_cc)
...
bool cc_includes_equality (CC_RELATION cc)
...
bool ccs_are_complementary (CC_RELATION cc1, CC_RELATION cc2)
...
int ll_ad_outlined_func (ILI_OP result_opc, ILI_OP call_opc, char *func_name, int narg, int arg1, int arg2, int arg3)
...
int ili_throw_label (int ilix)
...
static char dt_to_mthtype (char mtype)
void llmk_math_name (char *buff, int fn, int vectlen, bool mask, DTYPE res_dt)
LLVM wrapper for make_math_name()
char * make_math_name (MTH_FN fn, int vectlen, bool mask, DTYPE res_dt)
...
char * make_math_name_vabi (MTH_FN fn, int vectlen, bool mask, DTYPE res_dt)
...
char * make_math (MTH_FN fn, SPTR *fptr, int vectlen, bool mask, DTYPE res_dt, int nargs, int arg1_dt,...)
...
static int atomic_encode_aux (MSZ msz, SYNC_SCOPE scope, ATOMIC_ORIGIN origin, ATOMIC_RMW_OP op)
int atomic_encode (MSZ msz, SYNC_SCOPE scope, ATOMIC_ORIGIN origin)
...
int atomic_encode_rmw (MSZ msz, SYNC_SCOPE scope, ATOMIC_ORIGIN origin, ATOMIC_RMW_OP op)
...
ATOMIC_INFO atomic_decode (int encoding)
...
int atomic_info_index (ILI_OP opc)
...
ATOMIC_INFO atomic_info (int ilix)
...
static MEMORY_ORDER memory_order_from_operand (int ilix)
int ad_cmpxchg (ILI_OP opc, int ilix_val, int ilix_loc, int nme, int stc_atomic_info, int ilix_comparand, int ilix_is_weak, int ilix_success, int ilix_failure)
add ili for CMPXCHGx
static int get_dst_of_cmpxchg (int ilix)
bool cmpxchg_is_weak (int ilix)
...
int cmpxchg_loc (int ilix)
...
CMPXCHG_MEMORY_ORDER cmpxchg_memory_order (int ilix)
...
MEMORY_ORDER memory_order (int ilix)
...
bool is_omp_atomic_ld (int ilix)
...
bool is_omp_atomic_st (int ilix)
...
static int ivconst (ISZ_T valconst)
int imul_const_ili (ISZ_T valconst, int valilix)
...
int imul_ili_ili (int leftx, int rightx)
...
int iadd_const_ili (ISZ_T valconst, int valilix)
...
int iadd_ili_ili (int leftx, int rightx)
...
int isub_ili_ili (int leftx, int rightx)
...
int idiv_ili_const (int valilix, ISZ_T valconst)
...
int idiv_ili_ili (int leftx, int rightx)
...
int imax_ili_ili (int leftx, int rightx)
...
int imin_ili_ili (int leftx, int rightx)
...
Variables
bool share_proc_ili = false
bool share_qjsr_ili = false
bool ishft
static int ilhsh [ILTABSZ][ILHSHSZ]
static bool safe_qjsr = false
static int shpost
static DBLINT64 mrecip
static DBLINT64 twon
static DBLINT64 twonm1
static INT128 mrecip_128
static INT128 twon_128
static INT128 twonm1_128
static int visit_list = 0
static int rewr_old
static int rewr_new
static int rewr_old_nme
static int rewr_new_nme
static int rewr_use = 1
static int rewr_def = 1
static int need_to_rename = 0
static int rewrite_nme_indirect = 0
struct {
int * base
int size
int cnt
} rewrb = {NULL, 0, 0}
struct {
rewrtstruct * base
int size
int cnt
int all_acon
} rewrt = {NULL, 0, 0, 0}
static argtype * args
static int nargs
static int argsize
static bool override_abi = false
char memory_order_fail_table [MO_MAX_DEF+1][MO_MAX_DEF+1]
Table used by cmpxchg_memory_order.
Detailed Description
ILI utility module.
Definition in file iliutil.cpp.
Macro Definition Documentation
__MAXPOW
#define __MAXPOW 10
CCRelationILIOpnd
#define CCRelationILIOpnd (p, n) (p)->opnd[n]
Definition at line 142 of file iliutil.cpp.
ConvertATOMIC_RMW_OP
#define ConvertATOMIC_RMW_OP (n) (n)
Definition at line 145 of file iliutil.cpp.
ConvertMSZ
#define ConvertMSZ (n) (n)
Definition at line 144 of file iliutil.cpp.
DTypeILIOpnd
#define DTypeILIOpnd (p, n) (p)->opnd[n]
Definition at line 143 of file iliutil.cpp.
EXPANDER_DECLARE_INTERNAL
#define EXPANDER_DECLARE_INTERNAL
Definition at line 19 of file iliutil.cpp.
GARB_UNREACHABLE
#define GARB_UNREACHABLE 0
Definition at line 122 of file iliutil.cpp.
GARB_VISITED
#define GARB_VISITED 1
Definition at line 123 of file iliutil.cpp.
GETVAL128
#define GETVAL128 (a, b)
Value:
  do {                       \
    a.numq[0] = CONVAL1G(b); \
    a.numq[1] = CONVAL2G(b); \
    a.numq[2] = CONVAL3G(b); \
    a.numq[3] = CONVAL4G(b); \
  } while (0)
GETVAL64
#define GETVAL64 (a, b)
Value:
  do {                       \
    a.numd[0] = CONVAL1G(b); \
    a.numd[1] = CONVAL2G(b); \
  } while (0)
GETVALI128
#define GETVALI128 (a, b)
Value:
  do {                       \
    a.numi[0] = CONVAL1G(b); \
    a.numi[1] = CONVAL2G(b); \
    a.numi[2] = CONVAL3G(b); \
    a.numi[3] = CONVAL4G(b); \
  } while (0)
GETVALI64
#define GETVALI64 (a, b)
Value:
  do {                       \
    a.numi[0] = CONVAL1G(b); \
    a.numi[1] = CONVAL2G(b); \
  } while (0)
IL_dpfunc
#define IL_dpfunc IL_DFRDP
Definition at line 62 of file iliutil.cpp.
IL_qpfunc
#define IL_qpfunc IL_DFRQP
Definition at line 63 of file iliutil.cpp.
IL_spfunc
#define IL_spfunc IL_DFRSP
Definition at line 61 of file iliutil.cpp.
ILHSHSZ
#define ILHSHSZ 173
Definition at line 116 of file iliutil.cpp.
ILTABSZ
#define ILTABSZ 5
Definition at line 115 of file iliutil.cpp.
IS_DBL0
#define IS_DBL0 is_dbl0
Definition at line 2390 of file iliutil.cpp.
IS_FLT0
#define IS_FLT0 is_flt0
Definition at line 2389 of file iliutil.cpp.
IS_QUAD0
#define IS_QUAD0 is_quad0
Definition at line 2391 of file iliutil.cpp.
MAXILIS
#define MAXILIS 67108864
Definition at line 117 of file iliutil.cpp.
mk_prototype
#define mk_prototype (SPTR) mk_prototype_llvm
Definition at line 113 of file iliutil.cpp.
OT_BINARY
#define OT_BINARY 2
Definition at line 11291 of file iliutil.cpp.
OT_LEAF
#define OT_LEAF 3
Definition at line 11292 of file iliutil.cpp.
OT_UNARY
#define OT_UNARY 1
Definition at line 11290 of file iliutil.cpp.
RED_DAMV
#define RED_DAMV (!XBIT(15, 0x100))
SIZEOF
#define SIZEOF (array) (sizeof(array) / sizeof(char *))
Definition at line 14081 of file iliutil.cpp.
sptrGetILI
#define sptrGetILI get_ili
Definition at line 146 of file iliutil.cpp.
Typedef Documentation
rewrtstruct
typedef struct rewrtstruct rewrtstruct
Function Documentation
_ddilitree()
void _ddilitree (int i, int flag)
...
Definition at line 12412 of file iliutil.cpp.
_find_ili()
bool _find_ili (int ilix, int find_this)
...
Definition at line 9834 of file iliutil.cpp.
_frsqrt()
static int _frsqrt (int x) static
Definition at line 13220 of file iliutil.cpp.
Referenced by addarth().
_ipowi()
static int _ipowi (int x, int i) static
Definition at line 13149 of file iliutil.cpp.
Referenced by addarth().
_is_nand()
static bool _is_nand (SPTR sptr) static
Definition at line 8351 of file iliutil.cpp.
References CONVAL2G, e, m, and sptr.
Referenced by addbran().
_is_nanf()
static bool _is_nanf (int sptr) static
Definition at line 14460 of file iliutil.cpp.
Referenced by addbran().
_jsrsearch()
static int _jsrsearch (int ilix) static
Look for 'JSR' in this tree.
Definition at line 12772 of file iliutil.cpp.
_kpwr2()
static int _kpwr2 (INT cv1, INT cv2, int max_pwr) static
Determine if the 64-bit value represented by (cv1<<32)+cv2 is a power of 2; the range of the powers is 1 ... max_pwr, inclusive.
Definition at line 7854 of file iliutil.cpp.
References _pwr2(), and i.
Referenced by addarth().
_lshift_one()
static int _lshift_one (int ili) static
Check if the expression is shifting one left; if so, return its the shift count.
Definition at line 13882 of file iliutil.cpp.
Referenced by addarth().
_mkfunc()
static int _mkfunc (const char * name) static
Definition at line 13817 of file iliutil.cpp.
Referenced by ad1func_cmplx(), ad1func_cmplx_abi(), ad2func_cmplx(), ad2func_cmplx_abi(), ad2func_int(), ad2func_kint(), ad_func(), and addarth().
_pwr2()
static int _pwr2 (INT val, int max_pwr) static
Determine if 'val' is a power of 2; the range of the powers is 1 ... max_pwr, inclusive.
Definition at line 7836 of file iliutil.cpp.
References i, and val.
Referenced by _kpwr2(), and addarth().
_xpowi()
static int _xpowi (int opn, int pwr, ILI_OP opc) static
Raising an operand to a constant power >= 1. generate ILI which maximize cse's (i.e., generate a balanced tree).
opn – operand (ILI) raised to power 'pwd'
pwr – power (constant)
opc – mult ILI opcode
Definition at line 13187 of file iliutil.cpp.
Referenced by addarth().
ad1altili()
static int ad1altili (ILI_OP opc, int opn1, int alt) static
add an ili with one operand which has an alternate
The routine is static – only addili should create ALT ili.
Definition at line 414 of file iliutil.cpp.
References get_ili(), ILI_ALT, ILI::opc, and ILI::opnd.
Referenced by ad1mathfunc_cmplx(), addarth(), and gen_sincos().
ad1func_cmplx()
static int ad1func_cmplx (ILI_OP opc, char * name, int opn1) static
Add func call with 1 complex argument returning complex value.
Note that a double complex value will be presented as a packed argument, i.e., a double complex vector of length 1
Parameters
opc must be a function call ili opcode: QJSR, JSR
Definition at line 493 of file iliutil.cpp.
References _mkfunc(), ad1ili(), ad2ili(), ad3ili(), CD_RETVAL, CS_RETVAL, DP, IL_RES, ILI_OPC, ILIA_CS, name, and tmp.
Referenced by ad1mathfunc_cmplx().
ad1func_cmplx_abi()
static int ad1func_cmplx_abi (ILI_OP opc, char * name, int opn1) static
Add func call with 1 complex argument returning complex value.
The C ABI is used here. A complex will be treated as if it's a struct 2 parts. On x64, a complex double will be passed as 2 arguments; the vector abi will pass the complex double packed in a single register or memory unit.
Parameters
opc must be a function call ili opcode: QJSR, JSR
Definition at line 575 of file iliutil.cpp.
References _mkfunc(), ad1ili(), ad2ili(), ad3ili(), CD_RETVAL, CS_RETVAL, DP, IL_RES, ILI_OPC, ILIA_CS, name, and tmp.
Referenced by ad1mathfunc_cmplx().
ad1ili()
int ad1ili (ILI_OP opc, int opn1)
add ili with one operand
...
Definition at line 396 of file iliutil.cpp.
References addili(), ILI::opc, and ILI::opnd.
Referenced by ad1func_cmplx(), ad1func_cmplx_abi(), ad2func_cmplx(), ad2func_cmplx_abi(), ad2func_int(), ad2func_kint(), ad_acon(), ad_aconi(), ad_aconk(), ad_cse(), ad_free(), ad_func(), ad_icon(), ad_kcon(), ad_kconi(), addarth(), addbran(), addili(), addother(), gen_sincos(), ICON(), ili_init(), reciprocal_division(), reciprocal_division_64(), red_damv(), red_iadd(), red_kadd(), and red_negate().
ad1mathfunc_cmplx()
static int ad1mathfunc_cmplx (MTH_FN fn, ILI_OP opc, int op1, DTYPE res_dt, DTYPE arg1_dt) static
Add func call with 1 complex argument returning complex value.
Assumes the new (as defined by make_math) naming scheme. For passing complex and returning types, we can either follow the C ABI which says complex is the same as a struct of two parts; or, we can follow the vector ABI which views a complex scalar as a vector complex vector of length 1, i.e., the complex is 'packed'. For now, we use the C abi'.
Parameters
opc must be a function call ili opcode: QJSR, JSR
Definition at line 659 of file iliutil.cpp.
References ad1altili(), ad1func_cmplx(), ad1func_cmplx_abi(), fn, fname, make_math(), NULL, and XBIT_VECTORABI_FOR_SCALAR.
Referenced by addarth().
ad2altili()
static int ad2altili (ILI_OP opc, int opn1, int opn2, int alt) static
Add an ili with two operands which has an alternate.
The routine isstatic – only addili should create ALT ili.
Definition at line 453 of file iliutil.cpp.
References get_ili(), ILI_ALT, ILI::opc, and ILI::opnd.
Referenced by ad2mathfunc_cmplx(), and addarth().
ad2func_cmplx()
static int ad2func_cmplx (ILI_OP opc, char * name, int opn1, int opn2) static
Add func call with 2 arguments returning complex value.
The 2 arguments could be double complex or the 1st argument is double complex and the 2nd argument is integer.
A double complex value will be presented as a packed argument, i.e., a double complex vector of length 1
Parameters
opc must be a function call ili opcode: QJSR, JSR
Definition at line 519 of file iliutil.cpp.
References _mkfunc(), ad1ili(), ad2ili(), ad3ili(), CD_RETVAL, CS_RETVAL, DP, ERR_unused, IL_RES, ILI_OPC, ILIA_CD, ILIA_CS, ILIA_IR, ILIA_KR, interr(), IR, name, and tmp.
Referenced by ad2mathfunc_cmplx(), and addarth().
ad2func_cmplx_abi()
static int ad2func_cmplx_abi (ILI_OP opc, char * name, int opn1, int opn2) static
Add func call with 2 arguments returning complex value.
The 2 arguments could be double complex or the 1st argument is double complex and the 2nd argument is integer. The C ABI is used here. A complex will be treated as if it's a struct 2 parts. On x64, a complex double will be passed as 2 arguments; the vector abi will pass the complex double packed in a single register or memory unit.
Parameters
opc must be a function call ili opcode: QJSR, JSR
Definition at line 602 of file iliutil.cpp.
References _mkfunc(), ad1ili(), ad2ili(), ad3ili(), CD_RETVAL, CS_RETVAL, DP, ERR_unused, IL_RES, ILI_OPC, ILIA_CD, ILIA_CS, ILIA_IR, ILIA_KR, interr(), IR, name, and tmp.
Referenced by ad2mathfunc_cmplx().
ad2func_int()
static int ad2func_int (ILI_OP opc, const char * name, int opn1, int opn2) static
Add func call with 2 integer arguments returning integer value.
Parameters
opc must be a function call ili opcode: QJSR, JSR
Definition at line 475 of file iliutil.cpp.
References _mkfunc(), ad1ili(), ad2ili(), IR_RETVAL, name, and tmp.
Referenced by addarth().
ad2func_kint()
int ad2func_kint (ILI_OP opc, const char * name, int opn1, int opn2)
Add func call with 2 integer*8 arguments returning integer*8 value.
...
Parameters
opc must be a function call ili opcode: QJSR, JSR
Definition at line 1216 of file iliutil.cpp.
References _mkfunc(), ad1ili(), ad2ili(), KR_RETVAL, name, and tmp.
Referenced by exp_ac().
ad2ili()
int ad2ili (ILI_OP opc, int opn1, int opn2)
add ili with two operands
...
Definition at line 435 of file iliutil.cpp.
References addili(), ILI::opc, and ILI::opnd.
Referenced by ad1func_cmplx(), ad1func_cmplx_abi(), ad2func_cmplx(), ad2func_cmplx_abi(), ad2func_int(), ad2func_kint(), ad_func(), ad_load(), addarth(), addbran(), addili(), KMUL(), KMULSH(), KMULUH(), KXSIGN(), MUL(), MULSH(), MULUH(), reciprocal_division(), reciprocal_division_64(), reciprocal_mod(), reciprocal_mod_64(), red_damv(), red_negate(), and XSIGN().
ad2mathfunc_cmplx()
static int ad2mathfunc_cmplx (MTH_FN fn, ILI_OP opc, int op1, int op2, DTYPE res_dt, DTYPE arg1_dt, DTYPE arg2_dt) static
Add func call with 2 complex arguments returning complex value.
Assumes the new (as defined by make_math) naming scheme. For passing complex and returning types, we can either follow the C ABI which says complex is the same as a struct of two parts; or, we can follow the vector ABI which views a complex scalar as a vector complex vector of length 1, i.e., the complex is 'packed'. For now, we use the 'vector abi'.
Parameters
opc must be a function call ili opcode: QJSR, JSR
Definition at line 684 of file iliutil.cpp.
References ad2altili(), ad2func_cmplx(), ad2func_cmplx_abi(), fn, fname, make_math(), NULL, and XBIT_VECTORABI_FOR_SCALAR.
Referenced by addarth().
ad3altili()
static int ad3altili (ILI_OP opc, int opn1, int opn2, int opn3, int alt) static
Add an ili with three operands which has an alternate.
The routine isstatic – only addili should create ALT ili.
Definition at line 1245 of file iliutil.cpp.
References get_ili(), ILI_ALT, ILI::opc, and ILI::opnd.
Referenced by addarth().
ad3ili()
int ad3ili (ILI_OP opc, int opn1, int opn2, int opn3)
add ili with three operands
Definition at line 1227 of file iliutil.cpp.
References addili(), ILI::opc, and ILI::opnd.
Referenced by _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_smove(), ad1func_cmplx(), ad1func_cmplx_abi(), ad2func_cmplx(), ad2func_cmplx_abi(), ad_func(), ad_load(), add_arglnk_closure(), add_ptr_subscript(), add_reg_arg_ili(), addarth(), addbran(), addCopyinInplace(), addother(), allochartmp(), allocThreadprivate(), arg_ar(), assign1(), begin_entry(), block_str_move(), charlen(), check_ilm(), cmplx_to_mem(), compute_sdsc_subscr(), cp_byval_mem_arg(), create_array_ref(), create_atomic_capture_seq(), create_atomic_read_seq(), create_atomic_seq(), create_atomic_write_seq(), create_ref(), create_sdsc_subscr(), exp_ac(), exp_add_copy(), exp_bran(), exp_call(), exp_end(), exp_fstring(), exp_header(), exp_load(), exp_misc(), exp_mp_atomic_capture(), exp_pure(), exp_qjsr(), exp_restore_mxcsr(), exp_smp(), exp_store(), exp_strx(), exp_szero(), exp_type_bound_proc_call(), exp_zqjsr(), finish_array(), gen_bindC_retval(), gen_funcret(), genIntLoad(), genload(), genswitch(), get_chain_pointer_closure(), get_complex_update_operand(), get_sdsc_element(), is_blockaddr_store(), jsrAddArg(), ld_sptr(), ll_ad_outlined_func2(), ll_get_gtid_val_ili(), ll_load_outlined_args(), ll_make_outlined_gjsr(), llLoadGtid(), llvmAddConcurEntryBlk(), load_uplevel_addresses(), loadCharLen(), makeCopyprivArray(), makeCopyprivArray_tls(), mk_charlen_address(), mk_function_call(), mk_kmpc_api_call(), red_damv(), redundantLdLdElim(), ref_threadprivate(), ref_threadprivate_var(), rm_smove(), sectionCreateBlock(), setTaskloopVars(), storechartmp(), storedums(), toUplevelAddr(), widenProcessDirectLoad(), and widenProcessIndirectLoad().
ad4altili()
static int ad4altili (ILI_OP opc, int opn1, int opn2, int opn3, int opn4, int alt) static
Definition at line 1277 of file iliutil.cpp.
References get_ili(), ILI_ALT, ILI::opc, and ILI::opnd.
Referenced by addarth().
ad4ili()
int ad4ili (ILI_OP opc, int opn1, int opn2, int opn3, int opn4)
add ili with four operands
Definition at line 1263 of file iliutil.cpp.
References addili(), ILI::opc, and ILI::opnd.
Referenced by _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_mp_atomic_write(), _exp_smove(), ad_func(), add_gargl_closure(), addbran(), addCopyinInplace(), block_str_move(), check_ilm(), cmplx_to_mem(), cp_byval_mem_arg(), create_atomic_capture_seq(), create_atomic_read_seq(), create_atomic_seq(), create_atomic_write_seq(), exp_add_copy(), exp_bran(), exp_call(), exp_end(), exp_fstring(), exp_misc(), exp_mp_atomic_capture(), exp_mp_atomic_update(), exp_smp(), exp_store(), exp_type_bound_proc_call(), gen_bindC_retval(), genIntStore(), genSizeAcon(), genswitch(), get_complex_update_operand(), handle_nested_threadprivate(), is_blockaddr_store(), ll_make_kmpc_task_arg(), ll_make_outlined_garg(), llLoadGtid(), load_uplevel_addresses(), loadUplevelArgsForRegion(), makeCopyprivArray(), makeCopyprivArray_tls(), redundantLdLdElim(), rm_smove(), sectionCreateBlock(), setTaskloopVars(), store_aret(), storechartmp(), storedums(), widenInsertWideStore(), and widenPushdown().
ad5ili()
int ad5ili (ILI_OP opc, int opn1, int opn2, int opn3, int opn4, int opn5)
add ili with five operands
Definition at line 1295 of file iliutil.cpp.
References addili(), ILI::opc, and ILI::opnd.
Referenced by _exp_mp_atomic_write(), _exp_smove(), cloneUplevel(), exp_mp_atomic_capture(), exp_mp_atomic_update(), expand_smove(), and pp_params().
ad_acon()
int ad_acon (SPTR sym, ISZ_T val)
add ACON ili with specified symbol and offset
Definition at line 1356 of file iliutil.cpp.
References ad1ili(), get_acon(), and val.
Referenced by allochartmp(), allocThreadprivate(), begin_entry(), check_ilm(), cloneUplevel(), cmplx_to_mem(), cp_byval_mem_arg(), create_ref(), exp_add_copy(), exp_bran(), exp_call(), exp_end(), exp_header(), exp_pure(), exp_qjsr(), exp_restore_mxcsr(), exp_smp(), exp_zqjsr(), gen_bindC_retval(), gen_funcret(), genIntLoad(), genIntStore(), genSizeAcon(), genswitch(), get_chain_pointer_closure(), is_blockaddr_store(), ll_get_gtid_addr_ili(), ll_get_gtid_val_ili(), ll_load_outlined_args(), ll_make_kmpc_copyprivate(), ll_make_kmpc_critical(), ll_make_kmpc_end_critical(), ll_make_kmpc_task(), ll_make_kmpc_task_arg(), ll_make_kmpc_task_begin_if0(), ll_make_kmpc_task_complete_if0(), ll_make_outlined_task_call(), ll_make_sections_args(), llGetThreadprivateAddr(), llLoadGtid(), llvmAddConcurEntryBlk(), load_uplevel_addresses(), loadUplevelArgsForRegion(), makeCopyprivArray(), makeCopyprivArray_tls(), mk_charlen_address(), mk_swlist(), pp_params(), red_aadd(), ref_threadprivate(), ref_threadprivate_var(), sectionCreateBlock(), setTaskloopVars(), store_aret(), storechartmp(), and toUplevelAddr().
ad_aconi()
int ad_aconi (ISZ_T val)
add ACON ili with specified (integer) constant
Definition at line 1338 of file iliutil.cpp.
References ad1ili(), get_acon(), SPTR_NULL, and val.
Referenced by _exp_smove(), addili(), assign1(), block_str_move(), cmplx_to_mem(), create_ref(), exp_ac(), exp_call(), exp_load(), exp_qjsr(), exp_smp(), exp_store(), exp_type_bound_proc_call(), exp_zqjsr(), get_chain_pointer_closure(), get_sdsc_element(), ll_load_outlined_args(), ll_make_kmpc_critical(), ll_make_kmpc_end_critical(), ll_make_outlined_call(), makeCopyprivArray(), mk_charlen_address(), red_aadd(), ref_threadprivate(), rm_smove(), setTaskloopVars(), and toUplevelAddr().
ad_aconk()
int ad_aconk (INT m32, INT l32)
Add acon ili of an 64-bit constant whose value consists of m32 (most significant 32 bits) and l32 (least significant 32 bits).
Definition at line 1344 of file iliutil.cpp.
References ad1ili(), get_acon(), INT64_2_ISZ, ISZ_T, and SPTR_NULL.
Referenced by addili().
ad_cmpxchg()
int ad_cmpxchg (ILI_OP opc, int ilix_val, int ilix_loc, int nme, int stc_atomic_info, int ilix_comparand, int ilix_is_weak, int ilix_success, int ilix_failure)
add ili for CMPXCHGx
...
Actually two ilis are created, one for the CMPXCHGx and a CMPXCHG_DST to hold the operands that won't fit.
Parameters
opc an IL_CMPXCHGx opcode
ilix_val ILI expression for value to be stored if operation succeeds
ilix_loc ILI address expression for location to be updated.
nme NME for destination.
stc_atomic_info information packed by routine atomic_encode.
ilix_comparand value to compare against
ilix_is_weak if 1 then operation is allowed to spuriously fail occasionally. Should be 0 otherwise.
ilix_success ILI expression for memory order on success
ilix_failure ILI expression for memory order on failure
Definition at line 14788 of file iliutil.cpp.
Referenced by _exp_mp_atomic_update().
ad_cse()
int ad_cse (int ilix)
add CSE ili of an ili
Definition at line 1362 of file iliutil.cpp.
References ad1ili(), ERR_Severe, FLANG_FALLTHROUGH, IL_RES, ili_get_vect_dtype(), ILI_OPC, ILIA_AR, ILIA_CD, ILIA_CS, ILIA_DP, ILIA_FLOAT128, ILIA_IR, ILIA_KR, ILIA_LNK, ILIA_QP, ILIA_SP, and interr().
Referenced by _exp_mp_atomic_update(), check_ilm(), and exp_store().
ad_free()
int ad_free (int ilix)
Add a IL_FREEx with given operand.
Definition at line 1467 of file iliutil.cpp.
References ad1ili(), ERR_Fatal, IL_RES, ILI_OPC, ILIA_AR, ILIA_CD, ILIA_CS, ILIA_DP, ILIA_FLOAT128, ILIA_IR, ILIA_KR, ILIA_SP, interr(), and r.
Referenced by addother(), and exp_estmt().
ad_func()
static int ad_func (ILI_OP result_opc, ILI_OP call_opc, const char * func_name, int nargs, ...) static
Definition at line 703 of file iliutil.cpp.
References _mkfunc(), ad1ili(), ad2ili(), ad3ili(), ad4ili(), AR_RETVAL, arg, ARG_IR, args, assert, BZERO, CS_RETVAL, DP, DP_RETVAL, ERR_Fatal, ERR_Severe, ERR_unused, func, i, IL_OPRS, IL_RES, IL_TYPE, IL_VECT, ILI_OPC, ILI_OPND, ILIA_AR, ILIA_CD, ILIA_CS, ILIA_DP, ILIA_FLOAT128, ILIA_IR, ILIA_KR, ILIA_QP, ILIA_SP, ILTY_ARTH, ILTY_CONS, ILTY_LOAD, ILTY_OTHER, interr(), IR, IR_RETVAL, KR_RETVAL, nargs, QP, QP_RETVAL, reg, SP, and SP_RETVAL.
Referenced by addarth(), addother(), and gen_sincos().
ad_icon()
int ad_icon (INT val)
add ICON ili with specified constant value
Definition at line 1309 of file iliutil.cpp.
References ad1ili(), DT_INT, getcon(), and val.
Referenced by addarth(), addbran(), addili(), red_damv(), and red_iadd().
ad_kcon()
int ad_kcon (INT m32, INT l32)
Add KCON ili of an 64-bit constant whose value consists of m32 (most significant 32 bits) and l32 (least significant 32 bits).
Definition at line 1317 of file iliutil.cpp.
References ad1ili(), and getcon().
Referenced by addarth(), addbran(), block_str_move(), exp_alloca(), kanji_bytes(), kanji_divide(), ld_sptr(), reciprocal_division(), reciprocal_division_64(), and reciprocal_mod_64().
ad_kconi()
int ad_kconi (ISZ_T v)
Add kcon ili of an 64-bit constant.
Definition at line 1327 of file iliutil.cpp.
References ad1ili(), getcon(), ISZ_2_INT64, num, and s.
Referenced by addili(), compute_sdsc_subscr(), create_array_subscr(), create_sdsc_subscr(), exp_alloca(), exp_fstring(), exp_load(), exp_misc(), exp_smp(), gen_abs_expr(), gen_base_addr_operand(), gen_binary_expr(), gen_llvm_expr(), ll_make_kmpc_copyprivate(), and red_damv().
ad_load()
int ad_load (int stx)
Given a store ILI, generate the equivalent load ILI.
Definition at line 1412 of file iliutil.cpp.
References ad2ili(), ad3ili(), base, ILI_OPC, ILI_OPND, load, MSZ_F16, MSZ_F32, MSZ_F4, MSZ_F8, and MSZ_I8.
Referenced by check_ilm().
addarth()
static int addarth (ILI * ilip) static
adds arithmetic ili
Definition at line 2398 of file iliutil.cpp.
References __MAXPOW, _frsqrt(), _ipowi(), _kpwr2(), _lshift_one(), _mkfunc(), _pwr2(), _xpowi(), ACONOFFG, ad1altili(), ad1ili(), ad1mathfunc_cmplx(), ad2altili(), ad2func_cmplx(), ad2func_int(), ad2ili(), ad2mathfunc_cmplx(), ad3altili(), ad3ili(), ad4altili(), ad_func(), ad_icon(), ad_kcon(), add64(), and64(), ARGS_NUMBER, assert, CC_EQ, CC_GE, CC_GT, CC_LE, CC_LT, CC_NE, CCRelationILIOpnd, cmp64(), cmp_to_log(), commute_cc(), CONVAL2G, STB::dbl0, STB::dbl1, STB::dbl2, DblIsSingle(), div64(), do_newton_sqrt(), DP, DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, DTypeILIOpnd, ERR_Fatal, ERR_Informational, expb, fast_math(), FEATURE_ABM, FEATURE_AVX, FEATURE_SSE42, flg, STB::flt0, STB::flt1, STB::flt2, FMTH_I_ALOG, FMTH_I_ALOG10, FMTH_I_AMOD, FMTH_I_CBRT, FMTH_I_CDDIV, FMTH_I_COS, FMTH_I_COSH, FMTH_I_CSDIV, FMTH_I_DCOSH, FMTH_I_DEXP, FMTH_I_DLOG, FMTH_I_DLOG10, FMTH_I_DMOD, FMTH_I_DPOWD, FMTH_I_DSIN, FMTH_I_DSINH, FMTH_I_EXP, FMTH_I_RPOWF, FMTH_I_SIN, FMTH_I_SINH, fname, func_in(), gbl, gen_sincos(), get_acon(), get_ili(), get_vcon_scalar(), getcon(), GETVAL128, GETVAL64, GETVALI64, gnr_math(), i, STB::i0, STB::i1, iadd_ovf(), icmp(), FLG::ieee, IEEE_CMP, IL_AADD, IL_ASUB, IL_COMM, IL_dpfunc, IL_IADD, IL_IDIV, IL_IMUL, IL_INEG, IL_ISLINK, IL_ISUB, IL_MOD, IL_OPRFLAG, IL_OPRS, IL_qpfunc, IL_RES, IL_spfunc, IL_TYPE, IL_VECT, ili_get_vect_dtype(), ILI_OPC, ILI_OPND, ILI_SymOPND, ILIA_IR, ILIA_KR, ILIO_STC, ILIO_SYM, ilis, ILTY_ARTH, ILTY_CONS, ILTY_LOAD, ILTY_MOVE, interr(), IR, is_dbl0(), IS_DBL0, is_flt0(), IS_FLT0, IS_LCL_OR_DUM, is_quad0(), is_zero_one(), ishft, isub_ovf(), ISZ_T, STB::k0, STB::k1, KR_RETVAL, make_math(), mk_prototype, MTH_acos, MTH_aint, MTH_asin, MTH_atan, MTH_atan2, MTH_ceil, MTH_cos, MTH_cosh, MTH_div, MTH_exp, MTH_floor, MTH_I_ACOS, MTH_I_AINT, MTH_I_ALOG, MTH_I_ALOG10, MTH_I_AMOD, MTH_I_ASIN, MTH_I_ATAN, MTH_I_ATAN2, MTH_I_COS, MTH_I_COSH, MTH_I_DACOS, MTH_I_DASIN, MTH_I_DATAN, MTH_I_DATAN2, MTH_I_DCEIL, MTH_I_DCOS, MTH_I_DCOSH, MTH_I_DDIV, MTH_I_DEXP, MTH_I_DFLOOR, MTH_I_DINT, MTH_I_DJN, MTH_I_DLOG, MTH_I_DLOG10, MTH_I_DMOD, MTH_I_DPOWD, MTH_I_DPOWI, MTH_I_DPOWK, MTH_I_DSIGN, MTH_I_DSIN, MTH_I_DSINH, MTH_I_DTAN, MTH_I_DTANH, MTH_I_DYN, MTH_I_EXP, MTH_I_FCEIL, MTH_I_FFLOOR, MTH_I_FSIGN, MTH_I_IDIV, MTH_I_IDNINT, MTH_I_ILEADZ, MTH_I_ILEADZI, MTH_I_IMOD, MTH_I_IPOPCNT, MTH_I_IPOPCNTI, MTH_I_IPOPPAR, MTH_I_IPOPPARI, MTH_I_IPOWI, MTH_I_IQNINT, MTH_I_ITRAILZ, MTH_I_ITRAILZI, MTH_I_JN, MTH_I_KIDNINT, MTH_I_KLEADZ, MTH_I_KNINT, MTH_I_KPOPCNT, MTH_I_KPOPPAR, MTH_I_KPOWI, MTH_I_KPOWK, MTH_I_KTRAILZ, MTH_I_LOG, MTH_I_NINT, MTH_I_QACOS, MTH_I_QASIN, MTH_I_QATAN, MTH_I_QATAN2, MTH_I_QCEIL, MTH_I_QEXP, MTH_I_QFLOOR, MTH_I_QINT, MTH_I_QLOG, MTH_I_QMOD, MTH_I_QPOWI, MTH_I_QPOWK, MTH_I_QPOWQ, MTH_I_QTAN, MTH_I_RDIV, MTH_I_RPOWF, MTH_I_RPOWI, MTH_I_RPOWK, MTH_I_SIN, MTH_I_SINH, MTH_I_TAN, MTH_I_TANH, MTH_I_UICMP, MTH_I_UIDIV, MTH_I_UIMOD, MTH_I_YN, MTH_log, MTH_log10, MTH_mod, MTH_pow, MTH_powi, MTH_powi1, MTH_powk, MTH_powk1, MTH_sin, MTH_sinh, MTH_sqrt, MTH_tan, MTH_tanh, mul64(), neg64(), new_ili(), NUMI_SIZE, NUMU_SIZE, ILI::opc, ILI::opnd, POW1, POW2, STB::quad0, STB::quad1, reciprocal_division(), reciprocal_division_64(), reciprocal_mod(), reciprocal_mod_64(), red_aadd(), RED_DAMV, red_damv(), red_iadd(), red_kadd(), red_minmax(), red_negate(), relaxed_math(), res, root, shf64(), SP, SPTR_NULL, stb, sub64(), SymConval2, TEST_FEATURE, TEST_FEATURE2, tmp, ucmp64(), udiv64(), EXP::uicmp, umul64(), ushf64(), vect_math(), VECTLEN1, void(), XBIT, XBIT_NEW_MATH_NAMES, XBIT_NEW_RELAXEDMATH, xdabsv(), xdadd(), xdatan(), xdble(), xdcmp(), xddiv(), xdfix(), xdfix64(), xdfixu(), xdfloat(), xdfloatu(), xdflt64(), xdfltu64(), xdisint(), xdmul(), xdneg(), xdsqrt(), xdsub(), xfabsv(), xfadd(), xfatan(), xfcmp(), xfdiv(), xffloat(), xffloatu(), xfisint(), xfix(), xfix64(), xfixu(), xflt64(), xfltu64(), xfmul(), xfneg(), xfsqrt(), xfsub(), xqabsv(), xqadd(), xqatan(), xqatan2(), xqisint(), xqneg(), xqsqrt(), xqsub(), xsngl(), xucmp(), xudiv(), xumod(), and zero.
Referenced by addili().
addbran()
static int addbran (ILI * ilip) static
adds branch ili
Definition at line 8529 of file iliutil.cpp.
References _is_nand(), _is_nanf(), ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad_icon(), ad_kcon(), assert, CC_EQ, CC_GE, CC_GT, CC_ILI_OPND, CC_LE, CC_LT, CC_NE, CC_NOTGT, CC_NOTLT, CC_NOTNE, CCRelationILIOpnd, SWEL::clabel, cmp64(), combine_ieee_ccs(), combine_int_ccs(), commute_cc(), CONVAL2G, STB::dbl0, ERR_Severe, MACHTYPE::feature, FEATURE_SCALAR_SSE, STB::flt0, func_in(), get_ili(), GETVALI64, STB::i0, STB::i1, icmp(), IEEE_CMP, IL_RES, ILI_ALT, ILI_OPC, ILI_OPND, ILI_SymOPND, ILIA_KR, IS_DBL0, IS_FLT0, IS_LCL_OR_DUM, IS_QUAD0, is_zero_one(), STB::k0, mach, n, ILI::opc, ILI::opnd, STB::quad0, RFCNTD, RFCNTI, stb, switch_base, tmp, ucmp64(), and xucmp().
Referenced by addili().
addcallarg()
void addcallarg (int ili, int nme, int dtype)
...
Definition at line 14020 of file iliutil.cpp.
Referenced by create_atomic_seq().
addili()
int addili (ILI * ilip)
principle add ili routine
...
Definition at line 187 of file iliutil.cpp.
References ACONOFFG, ad1ili(), ad2ili(), ad_aconi(), ad_aconk(), ad_icon(), ad_kconi(), addarth(), addbran(), addother(), assert, BIH_QJSR, CONVAL2G, EXP::curbih, DBGBIT, dump_ili(), ERR_Fatal, ERR_Severe, expb, gbl, get_ili(), getcon(), IL_IADD, IL_ISUB, IL_TYPE, ILI_OPC, ILI_OPND, iltb, ILTY_ARTH, ILTY_BRANCH, ILTY_CONS, ILTY_DEFINE, ILTY_LOAD, ILTY_MOVE, ILTY_OTHER, ILTY_PLOAD, ILTY_PROC, ILTY_PSTORE, ILTY_STORE, interr(), ISZ_2_INT64, new_ili(), ILI::opc, ILI::opnd, EXP::qjsr_flag, ILTB::qjsrfg, safe_qjsr, share_proc_ili, share_qjsr_ili, tmp, verify_ili(), and VERIFY_ILI_SHALLOW.
Referenced by ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad5ili(), compl_br(), exp_mac(), update_ili_operand(), and visit_ili_operands().
addother()
static int addother (ILI * ilip) static
Definition at line 8375 of file iliutil.cpp.
References ad1ili(), ad3ili(), ad_free(), ad_func(), ILTB::callfg, CC_ILI_OPND, cmpz_of_cmp(), CONVAL2G, STB::dbl0, DT_CMPLX, DT_DCMPLX, DT_FLOAT, STB::flt0, func_in(), get_ili(), getcon(), IL_TYPE, ILI_ALT, ILI_OPC, ILI_OPND, iltb, ILTY_CONS, MO_RELAXED, MO_SEQ_CST, new_ili(), ILI::opc, ILI::opnd, stb, and value_of_irlnk_operand().
Referenced by addili().
alt_qjsr()
int alt_qjsr (int ilix)
...
Definition at line 12813 of file iliutil.cpp.
atomic_decode()
ATOMIC_INFO atomic_decode (int encoding)
...
Decode ATOMIC_INFO from an int that was created with atomic_encode or atomic_encode_rmw.
Definition at line 14689 of file iliutil.cpp.
atomic_encode()
int atomic_encode (MSZ msz, SYNC_SCOPE scope, ATOMIC_ORIGIN origin)
...
Encode the given information into an int that can be used as the operand for a ATOMICLDx, ATOMICSTx, or CMPXCHGx.
Definition at line 14668 of file iliutil.cpp.
Referenced by _exp_mp_atomic_update(), exp_mp_atomic_read(), exp_mp_atomic_write(), and get_complex_update_operand().
atomic_encode_aux()
static int atomic_encode_aux (MSZ msz, SYNC_SCOPE scope, ATOMIC_ORIGIN origin, ATOMIC_RMW_OP op) static
Definition at line 14645 of file iliutil.cpp.
atomic_encode_rmw()
int atomic_encode_rmw (MSZ msz, SYNC_SCOPE scope, ATOMIC_ORIGIN origin, ATOMIC_RMW_OP op)
...
Encode atomic info for an ATOMICRMW instruction.
Definition at line 14675 of file iliutil.cpp.
Referenced by exp_mp_atomic_capture(), and exp_mp_atomic_update().
atomic_info()
ATOMIC_INFO atomic_info (int ilix)
...
Get ATOMIC_INFO associated with a given ILI instruction
Definition at line 14737 of file iliutil.cpp.
Referenced by gen_llvm_atomicrmw_expr(), gen_llvm_cmpxchg(), and ll_instr_flags_for_memory_order_and_scope().
atomic_info_index()
int atomic_info_index (ILI_OP opc)
...
Get index of ATOMIC_INFO operand for a given ILI instruction.
Definition at line 14703 of file iliutil.cpp.
atomic_origin_name()
static const char * atomic_origin_name (ATOMIC_ORIGIN origin) static
Return print name of an ATOMIC_ORIGIN value
Definition at line 10818 of file iliutil.cpp.
atomic_rmw_op_name()
static const char * atomic_rmw_op_name (ATOMIC_RMW_OP op) static
Definition at line 10831 of file iliutil.cpp.
build_pointer_tree()
static int build_pointer_tree (int ilix, ISZ_T offset) static
Definition at line 10159 of file iliutil.cpp.
cc_includes_equality()
bool cc_includes_equality (CC_RELATION cc)
...
Definition at line 14393 of file iliutil.cpp.
ccs_are_complementary()
bool ccs_are_complementary (CC_RELATION cc1, CC_RELATION cc2)
...
Definition at line 14419 of file iliutil.cpp.
choose_multiplier()
void choose_multiplier (int N, unsigned dd, int prec)
...
Definition at line 1796 of file iliutil.cpp.
References add64(), cmp64(), d, div64(), lg(), mrecip, mul64(), shf64(), shpost, sub64(), twon, and twonm1.
Referenced by reciprocal_division().
choose_multiplier_64()
void choose_multiplier_64 (int N, DBLUINT64 dd, int prec)
...
Definition at line 1849 of file iliutil.cpp.
References add128(), cmp128(), d, div128(), lg64(), mrecip_128, mul128l(), shf128(), shpost, sub128(), twon_128, and twonm1_128.
Referenced by reciprocal_division_64().
cmp_to_log()
static INT cmp_to_log (INT val, int rel) static
convert a compare value to a logical value for a relation
Converts the result (val) of comparison to a logical value based on the relation rel. The possible values of a comparison and their meanings are:
  -1  -  op1 < op2
   0  -  op1 = op2
   1  -  op1 > op2
The values of rel and their meanings are enumerated in the switch statement.
Definition at line 9384 of file iliutil.cpp.
References CC_EQ, CC_GE, CC_GT, CC_LE, CC_LT, CC_NE, CC_NOTEQ, CC_NOTGE, CC_NOTGT, CC_NOTLE, CC_NOTLT, CC_NOTNE, ERR_Severe, icmp(), interr(), rel(), SCFTN_FALSE, SCFTN_TRUE, and val.
Referenced by addarth().
cmpxchg_is_weak()
bool cmpxchg_is_weak (int ilix)
...
For a IL_CMPXCHGx operation, return true if it is allowed to spuriously fail occcasionally. Returns false when in doubt.
Definition at line 14815 of file iliutil.cpp.
Referenced by gen_llvm_cmpxchg().
cmpxchg_loc()
int cmpxchg_loc (int ilix)
...
For an IL_CMPXCHGx instruction, return address expression of location.
Definition at line 14823 of file iliutil.cpp.
Referenced by gen_llvm_cmpxchg().
cmpxchg_memory_order()
CMPXCHG_MEMORY_ORDER cmpxchg_memory_order (int ilix)
...
For an IL_CMPXCHGx instruction, return memory orders for success and failure cases.
Definition at line 14862 of file iliutil.cpp.
Referenced by gen_llvm_cmpxchg().
cmpz_of_cmp()
static int cmpz_of_cmp (int op1, CC_RELATION cmpz_relation) static
Definition at line 13913 of file iliutil.cpp.
Referenced by addother().
combine_ieee_ccs()
CC_RELATION combine_ieee_ccs (CC_RELATION binary_cc, CC_RELATION zero_cc)
...
Definition at line 14354 of file iliutil.cpp.
Referenced by addbran().
combine_int_ccs()
CC_RELATION combine_int_ccs (CC_RELATION binary_cc, CC_RELATION zero_cc)
...
Definition at line 14320 of file iliutil.cpp.
Referenced by addbran().
commute_cc()
CC_RELATION commute_cc (CC_RELATION cc)
...
Definition at line 14286 of file iliutil.cpp.
Referenced by addarth(), and addbran().
compl_br()
int compl_br (int ilix, int lbl)
adds a branch ili by complementing the condition
...
This routine adds a branch ili whose condition is the complement of the condition specified by the ili ilix. lbl is the target of the branch. The complement is defined by the following: (Z, NZ), (LT, GE), LE, GT)
Definition at line 9337 of file iliutil.cpp.
References addili(), CC_ILI_OPND, complement_ieee_cc(), complement_int_cc(), i, ILI_OPC, ILI_OPND, ilis, is_floating_comparison_opcode(), ILI::opc, ILI::opnd, and ILIINFO::oprs.
Referenced by chk_block(), and exp_label().
complement_ieee_cc()
CC_RELATION complement_ieee_cc (CC_RELATION cc)
...
Definition at line 14249 of file iliutil.cpp.
Referenced by compl_br().
complement_int_cc()
CC_RELATION complement_int_cc (CC_RELATION cc)
...
Definition at line 14227 of file iliutil.cpp.
Referenced by compl_br().
compute_address()
int compute_address (SPTR sptr)
...
Definition at line 12709 of file iliutil.cpp.
Referenced by genload().
DblIsSingle()
static int DblIsSingle (SPTR dd) static
Definition at line 13828 of file iliutil.cpp.
Referenced by addarth().
ddilitree()
void ddilitree (int i, int flag)
...
Definition at line 12398 of file iliutil.cpp.
Referenced by dump_ilt().
dilitree()
static void dilitree (int i) static
Definition at line 11195 of file iliutil.cpp.
dmpili()
void dmpili (void)
ILI dump routine.
...
Definition at line 11258 of file iliutil.cpp.
Referenced by expand(), and schedule().
dmpilitree()
void dmpilitree (int i)
...
Definition at line 12385 of file iliutil.cpp.
Referenced by dump_ilt().
do_newton_sqrt()
static bool do_newton_sqrt (void) static
Definition at line 7821 of file iliutil.cpp.
References flg, FLG::ieee, MACH_INTEL_PENTIUM4, TEST_MACH, and XBIT.
Referenced by addarth().
dt_to_mthtype()
static char dt_to_mthtype (char mtype) static
Definition at line 14541 of file iliutil.cpp.
dump_atomic_info()
void dump_atomic_info (FILE * f, ATOMIC_INFO info)
...
Definition at line 10852 of file iliutil.cpp.
dump_ili()
void dump_ili (FILE * f, int i)
...
Definition at line 10865 of file iliutil.cpp.
Referenced by addili().
dump_msz()
const char * dump_msz (MSZ ms)
...
Definition at line 10765 of file iliutil.cpp.
fast_math()
char * fast_math (const char * root, int widthc, int typec, const char * oldname)
...
Definition at line 1096 of file iliutil.cpp.
References FEATURE_FMA4, FEATURE_SSE3, MACH_AMD_BULLDOZER, MACH_AMD_GH, MACH_INTEL_SANDYBRIDGE, root, TEST_FEATURE, TEST_MACH, and XBIT.
Referenced by addarth(), relaxed_math(), and vect_math().
find_host_function()
static SPTR find_host_function () static
Finds the corresponding host function of the device outlined function.
Definition at line 12446 of file iliutil.cpp.
find_ili()
bool find_ili (int tree, int it)
determine if an ili occurs in an ili subtree
...
Definition at line 9870 of file iliutil.cpp.
Referenced by exp_mp_atomic_capture(), get_complex_update_operand(), get_simple_update_operand(), and load_op_match_lhs().
func_in()
bool func_in (int ilix)
Search the ili subtree located by ilix for functions.
...
Definition at line 9781 of file iliutil.cpp.
Referenced by addarth(), addbran(), addother(), and simple_ili().
garbage_collect()
void garbage_collect (void(*)(int) mark_function)
...
Definition at line 9612 of file iliutil.cpp.
gen_sincos()
static int gen_sincos (ILI_OP opc, int op1, ILI_OP sincos_opc, ILI_OP fopc, MTH_FN fn, DTYPE dt, ILI_OP dfr_opc) static
Definition at line 7780 of file iliutil.cpp.
References ad1altili(), ad1ili(), ad_func(), dt, fn, fname, make_math(), NULL, and XBIT.
Referenced by addarth().
gencallargs()
int gencallargs (void)
...
Definition at line 14031 of file iliutil.cpp.
Referenced by create_atomic_seq().
genretvalue()
int genretvalue (int ilix, ILI_OP resultopc)
...
Definition at line 14052 of file iliutil.cpp.
Referenced by _make_mp_get_threadprivate(), and ll_ad_outlined_func2().
get_dst_of_cmpxchg()
static int get_dst_of_cmpxchg (int ilix) static
Get the IL_CMPXCHG_DST instruction underlying a IL_CMPXCHGx instruction.
Definition at line 14801 of file iliutil.cpp.
get_encl_function()
static int get_encl_function (int sptr) static
Definition at line 12428 of file iliutil.cpp.
get_ili()
static int get_ili (ILI * ilip) static
enter ili into ILI area by attempting to share
Definition at line 9455 of file iliutil.cpp.
References assert, get_ili(), i, ILHSHSZ, ili, ilis, ILTABSZ, ILI::opc, ILI::opnd, ILIINFO::oprs, p, and val.
Referenced by ad1altili(), ad2altili(), ad3altili(), ad4altili(), addarth(), addbran(), addili(), addother(), get_ili(), red_aadd(), red_iadd(), red_kadd(), and red_minmax().
get_ili_ns()
int get_ili_ns (ILI * ilip)
...
Definition at line 9527 of file iliutil.cpp.
Referenced by update_ili_operand(), and visit_ili_operands().
get_isz_conili()
ISZ_T get_isz_conili (int ili)
...
Definition at line 13253 of file iliutil.cpp.
get_rewr_new_nme()
int get_rewr_new_nme (int nmex)
...
Definition at line 9985 of file iliutil.cpp.
gnr_math()
char * gnr_math (const char * root, int widthc, int typec, const char * oldname, int masked)
...
Definition at line 926 of file iliutil.cpp.
References root.
Referenced by addarth(), and vect_math().
has_cse()
int has_cse (int ilix)
...
Definition at line 13589 of file iliutil.cpp.
Referenced by visit_ilis().
has_nme()
static bool has_nme (int nme) static
Definition at line 10372 of file iliutil.cpp.
iadd_const_ili()
int iadd_const_ili (ISZ_T valconst, int valilix)
...
Definition at line 15034 of file iliutil.cpp.
iadd_ili_ili()
int iadd_ili_ili (int leftx, int rightx)
...
Definition at line 15068 of file iliutil.cpp.
iadd_ovf()
static bool iadd_ovf (INT c1, INT c2, INT * r) static
Add two integers and check for overflow.
Definition at line 9440 of file iliutil.cpp.
References r.
Referenced by addarth().
icmp()
static INT icmp (INT v1, INT v2) static
compare two INTs
Definition at line 9361 of file iliutil.cpp.
Referenced by addarth(), addbran(), and cmp_to_log().
ICON()
static int ICON (INT v) static
Definition at line 1924 of file iliutil.cpp.
References ad1ili(), DT_INT, getcon(), and r.
Referenced by KXSIGN(), MULSH(), MULUH(), reciprocal_division(), reciprocal_division_64(), reciprocal_mod(), and XSIGN().
idiv_ili_const()
int idiv_ili_const (int valilix, ISZ_T valconst)
...
Definition at line 15193 of file iliutil.cpp.
idiv_ili_ili()
int idiv_ili_ili (int leftx, int rightx)
...
Definition at line 15213 of file iliutil.cpp.
ikmove()
int ikmove (int ilix)
...
Definition at line 14185 of file iliutil.cpp.
Referenced by compute_sdsc_subscr(), create_array_ref(), create_array_subscr(), create_sdsc_subscr(), exp_alloca(), finish_array(), forceK(), inlarr(), ll_make_atomic_compare_xchg(), ll_make_atomic_load(), ll_make_atomic_store(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), and ll_make_kmpc_for_static_init().
ili_cleanup()
void ili_cleanup (void)
...
Definition at line 178 of file iliutil.cpp.
References ilib, and STG_DELETE.
ili_get_vect_arg_count()
int ili_get_vect_arg_count (int ilix)
If a VECT ili, return its dtype, 0 otherwise.
...
Definition at line 12914 of file iliutil.cpp.
Referenced by cleanup_unneeded_sincos_calls(), and gen_llvm_vsincos_call().
ili_get_vect_dtype()
DTYPE ili_get_vect_dtype (int ilix)
...
Definition at line 12991 of file iliutil.cpp.
Referenced by _assn_rtemp(), ad_cse(), addarth(), exp_store(), gen_binary_expr(), gen_binary_vexpr(), gen_llvm_expr(), gen_llvm_vsincos_call(), gen_minmax_expr(), gen_vect_compare_operand(), have_masked_intrinsic(), make_stmt(), select_rtemp(), and vect_llvm_intrinsic_name().
ili_init()
void ili_init (void)
initialize ili area
...
Definition at line 153 of file iliutil.cpp.
References ad1ili(), cnt, ilhsh, ILHSHSZ, ilib, ILTABSZ, p, STG_ALLOC, and STG_SET_FREELINK.
Referenced by ds_init().
ili_isdeleted()
int ili_isdeleted (int ili)
...
Definition at line 13995 of file iliutil.cpp.
Referenced by build_sym_nme().
ili_opnd()
int ili_opnd (int ilix, int n)
return nth operand of ili - skipping past CSE ili if present
Definition at line 1508 of file iliutil.cpp.
References ILI_OPC, ILI_OPND, and n.
Referenced by exp_call(), and find_load_cse().
ili_subscript()
int ili_subscript (int sub)
...
Definition at line 13981 of file iliutil.cpp.
Referenced by add_arrnme().
ili_throw_label()
int ili_throw_label (int ilix)
...
Definition at line 14493 of file iliutil.cpp.
Referenced by dump_ilt(), gen_call_expr(), and verify_ilt().
ili_traverse()
int ili_traverse (int(*)(int) visit_f, int ilix)
Initialize for a traversal and call the traversal routine.
...
The traversal routine sets the ILI_VISIT & ILI_VLIST fields.
Definition at line 12731 of file iliutil.cpp.
ili_unvisit()
void ili_unvisit (void)
Clear the VISIT & VLIST fields of the ili in the visit_list.
...
Definition at line 12756 of file iliutil.cpp.
Referenced by get_complex_update_operand(), and load_op_match_lhs().
ili_visit()
void ili_visit (int ilix, int v)
Add an ili to visit_list and set its VISIT field.
...
Definition at line 12744 of file iliutil.cpp.
ilstckind()
int ilstckind (ILI_OP opc, int opnum)
...
Definition at line 14088 of file iliutil.cpp.
Referenced by putstc().
imax_ili_ili()
int imax_ili_ili (int leftx, int rightx)
...
Definition at line 15227 of file iliutil.cpp.
imin_ili_ili()
int imin_ili_ili (int leftx, int rightx)
...
Definition at line 15241 of file iliutil.cpp.
imul_const_ili()
int imul_const_ili (ISZ_T valconst, int valilix)
...
Definition at line 14999 of file iliutil.cpp.
imul_ili_ili()
int imul_ili_ili (int leftx, int rightx)
...
Definition at line 15019 of file iliutil.cpp.
initcallargs()
void initcallargs (int count)
...
Definition at line 14010 of file iliutil.cpp.
Referenced by create_atomic_seq().
is_argili_opcode()
int is_argili_opcode (ILI_OP opc)
...
Definition at line 13321 of file iliutil.cpp.
Referenced by gen_va_end(), and gen_va_start().
is_cseili_opcode()
int is_cseili_opcode (ILI_OP opc)
...
Definition at line 13344 of file iliutil.cpp.
Referenced by build_csed_list(), cancel_store(), collect_tree_ilis(), eval_ilm_argument1(), remove_from_csed_list(), scan_ili_tree(), and visit_ili_operands().
is_daili_opcode()
int is_daili_opcode (ILI_OP opc)
...
Definition at line 13431 of file iliutil.cpp.
Referenced by jsrAddArg().
is_dfrili_opcode()
int is_dfrili_opcode (ILI_OP opc)
...
Definition at line 13458 of file iliutil.cpp.
is_floating_comparison_opcode()
bool is_floating_comparison_opcode (ILI_OP opc)
...
Definition at line 13524 of file iliutil.cpp.
Referenced by compl_br().
is_freeili_opcode()
int is_freeili_opcode (ILI_OP opc)
...
Definition at line 13368 of file iliutil.cpp.
Referenced by check_ilm(), and schedule().
is_integer_comparison_opcode()
bool is_integer_comparison_opcode (ILI_OP opc)
...
Definition at line 13485 of file iliutil.cpp.
is_llvm_local()
bool is_llvm_local (int sptr, int funcsptr)
...
Definition at line 12468 of file iliutil.cpp.
is_llvm_local_private()
bool is_llvm_local_private (int sptr)
...
Definition at line 12452 of file iliutil.cpp.
Referenced by compute_sdsc_subscr(), create_sdsc_subscr(), llmp_task_get_private(), load_uplevel_addresses(), loadUplevelArgsForRegion(), and update_local_nme().
is_mvili_opcode()
int is_mvili_opcode (ILI_OP opc)
...
Definition at line 13390 of file iliutil.cpp.
Referenced by schedule().
is_omp_atomic_ld()
bool is_omp_atomic_ld (int ilix)
...
Definition at line 14931 of file iliutil.cpp.
Referenced by make_load().
is_omp_atomic_st()
bool is_omp_atomic_st (int ilix)
...
Definition at line 14952 of file iliutil.cpp.
is_rgdfili_opcode()
int is_rgdfili_opcode (ILI_OP opc)
...
Definition at line 13415 of file iliutil.cpp.
Referenced by schedule().
is_unsigned_opcode()
bool is_unsigned_opcode (ILI_OP opc)
...
Definition at line 13551 of file iliutil.cpp.
is_zero_one()
static bool is_zero_one (int ili) static
Definition at line 13975 of file iliutil.cpp.
Referenced by addarth(), and addbran().
isub_ili_ili()
int isub_ili_ili (int leftx, int rightx)
...
Definition at line 15115 of file iliutil.cpp.
isub_ovf()
static bool isub_ovf (INT c1, INT c2, INT * r) static
Subtract two integers and check for overflow.
Definition at line 9427 of file iliutil.cpp.
References r.
Referenced by addarth().
ivconst()
static int ivconst (ISZ_T valconst) static
Definition at line 14979 of file iliutil.cpp.
jsrsearch()
int jsrsearch (int ilix)
Search for "jsrs".
...
Definition at line 12806 of file iliutil.cpp.
kimove()
int kimove (int ilix)
...
Definition at line 14213 of file iliutil.cpp.
Referenced by compute_sdsc_subscr(), create_array_ref(), exp_ac(), exp_agoto(), exp_array(), exp_get_sdsc_len(), finish_array(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), and setTaskloopVars().
KMUL()
static int KMUL (int ilix, int iliy) static
Definition at line 2016 of file iliutil.cpp.
References ad2ili(), and t1.
Referenced by reciprocal_mod_64().
KMULSH()
static int KMULSH (int ilix, int iliy) static
Definition at line 1960 of file iliutil.cpp.
References ad2ili(), and t1.
Referenced by reciprocal_division_64().
KMULUH()
static int KMULUH (int ilix, int iliy) static
Definition at line 1970 of file iliutil.cpp.
References ad2ili(), and t1.
Referenced by reciprocal_division_64().
KXSIGN()
static int KXSIGN (int ilix, int N) static
Definition at line 2036 of file iliutil.cpp.
References ad2ili(), ICON(), t, and t1.
Referenced by reciprocal_division_64().
ldopc_from_stopc()
ILI_OP ldopc_from_stopc (ILI_OP stopc)
Given a store opc, return a corresponding load opc.
...
Definition at line 1521 of file iliutil.cpp.
ldst_msz()
void ldst_msz (DTYPE dtype, ILI_OP * ld, ILI_OP * st, MSZ * siz)
...
Definition at line 1570 of file iliutil.cpp.
References DTY, DTyAlgTySize, ld, MSZ_BYTE, MSZ_DFLWORD, MSZ_F16, MSZ_F4, MSZ_F8, MSZ_FWORD, MSZ_I8, MSZ_PTR, MSZ_SBYTE, MSZ_SHWORD, MSZ_WORD, st, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, and TY_SLOG.
Referenced by _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_mp_atomic_write(), exp_mp_atomic_capture(), exp_mp_atomic_read(), exp_mp_atomic_update(), exp_smp(), get_complex_update_operand(), and setTaskloopVars().
lg()
static int lg (unsigned d) static
Return i such that 2**i > |n| >= 2**(i+1)
Use reciprocal division to compute n/d where d is a compile-time constant. See PLDI '94, "Division by invariant integers using multiplication" by Granlund and Montgomery.
Definition at line 1756 of file iliutil.cpp.
References d, and i.
Referenced by choose_multiplier(), and reciprocal_division().
lg64()
static int lg64 (DBLUINT64 d) static
Definition at line 1769 of file iliutil.cpp.
References d, i, ucmp64(), and ushf64().
Referenced by choose_multiplier_64(), and reciprocal_division_64().
ll_ad_outlined_func()
int ll_ad_outlined_func (ILI_OP result_opc, ILI_OP call_opc, char * func_name, int narg, int arg1, int arg2, int arg3)
...
Definition at line 14453 of file iliutil.cpp.
Referenced by ll_make_outlined_call().
ll_internref_ili()
static int ll_internref_ili (SPTR sptr) static
Definition at line 12479 of file iliutil.cpp.
ll_taskprivate_inhost_ili()
static int ll_taskprivate_inhost_ili (SPTR sptr) static
Definition at line 12515 of file iliutil.cpp.
ll_uplevel_addr_ili()
static int ll_uplevel_addr_ili (SPTR sptr, bool is_task_priv) static
Definition at line 12552 of file iliutil.cpp.
llmk_math_name()
void llmk_math_name (char * buff, int fn, int vectlen, bool mask, DTYPE res_dt)
LLVM wrapper for make_math_name()
...
Parameters
buff (output), must be preallocated, should have a size > 32
Definition at line 14568 of file iliutil.cpp.
Referenced by cleanup_unneeded_sincos_calls(), gen_llvm_sincos_call(), and gen_llvm_vsincos_call().
make_math()
char * make_math (MTH_FN fn, SPTR * fptr, int vectlen, bool mask, DTYPE res_dt, int nargs, int arg1_dt, ...)
...
Definition at line 14619 of file iliutil.cpp.
Referenced by ad1mathfunc_cmplx(), ad2mathfunc_cmplx(), addarth(), and gen_sincos().
make_math_name()
char * make_math_name (MTH_FN fn, int vectlen, bool mask, DTYPE res_dt)
...
Definition at line 14578 of file iliutil.cpp.
Referenced by vect_math().
make_math_name_vabi()
char * make_math_name_vabi (MTH_FN fn, int vectlen, bool mask, DTYPE res_dt)
...
Definition at line 14602 of file iliutil.cpp.
mark_ili()
static void mark_ili (int val) static
Definition at line 9763 of file iliutil.cpp.
mark_ilitree()
static void mark_ilitree (int ili, int val) static
Definition at line 9725 of file iliutil.cpp.
mark_nme()
static void mark_nme (int nme, int val) static
Definition at line 9752 of file iliutil.cpp.
mem_size()
MSZ mem_size (TY_KIND ty)
Return MSZ_ for each datatype, or -1 if an aggregate type.
...
Result is the memory reference size, not including padding. For example, TY_X87 on x86 targets maps to F10.
The logic is custom to each target.
Definition at line 13082 of file iliutil.cpp.
Referenced by exp_mp_atomic_capture(), exp_mp_atomic_update(), exp_mp_atomic_write(), ld_sptr(), and process_formal_arguments().
memory_order()
MEMORY_ORDER memory_order (int ilix)
...
Get MEMORY_ORDER associated with given ILI instruction. If the memory order operand is not a constant, require a conservative bound. If there are different memory orders for success/failure, return an upper bound.
For IL_CMPXCHGx instructions, the memory order is always the "success" order, since the "failure" order is not allowed to be stronger.
The "failure" order cannot be stronger than the "success" order, so return the success order.
Definition at line 14887 of file iliutil.cpp.
Referenced by ll_instr_flags_for_memory_order_and_scope().
memory_order_from_operand()
static MEMORY_ORDER memory_order_from_operand (int ilix) static
Given an ILI expression for a memory order, return a MEMORY_ORDER at least as strong as what the expression specifies.
Definition at line 14759 of file iliutil.cpp.
mk_address()
int mk_address (SPTR sptr)
create ili representing the address of a variable
...
Definition at line 12651 of file iliutil.cpp.
Referenced by _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_mp_atomic_write(), add_ptr_subscript(), addCopyinInplace(), begin_entry(), charaddr(), charlen(), cloneUplevel(), compute_sdsc_subscr(), create_ref(), create_sdsc_subscr(), exp_call(), exp_header(), exp_load(), exp_misc(), exp_mp_atomic_capture(), exp_mp_atomic_update(), exp_smp(), exp_type_bound_proc_call(), get_chain_pointer_closure(), get_complex_update_operand(), get_sdsc_element(), ld_sptr(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), ll_make_outlined_call2(), llLoadGtid(), llvmAddConcurEntryBlk(), load_uplevel_addresses(), loadCharLen(), loadUplevelArgsForRegion(), makeCopyprivArray(), makeCopyprivArray_tls(), and setTaskloopVars().
mk_charlen_parref_sptr()
int mk_charlen_parref_sptr (SPTR sptr)
...
Definition at line 12631 of file iliutil.cpp.
Referenced by charlen().
mkfunc_avx()
int mkfunc_avx (char * nmptr, int avxp)
...
Definition at line 13800 of file iliutil.cpp.
MUL()
static int MUL (int ilix, int iliy) static
Definition at line 2005 of file iliutil.cpp.
References ad2ili(), IL_IMUL, and t1.
Referenced by reciprocal_mod().
MULSH()
static int MULSH (int ilix, int iliy) static
Definition at line 1948 of file iliutil.cpp.
References ad2ili(), ICON(), t1, t2, and t3.
Referenced by reciprocal_division().
MULUH()
static int MULUH (int ilix, int iliy) static
Definition at line 1979 of file iliutil.cpp.
References ad2ili(), ICON(), t1, t2, and t3.
Referenced by reciprocal_division().
new_ili()
static int new_ili (ILI * ilip) static
enter ili into ILI area (no sharing)
Definition at line 9536 of file iliutil.cpp.
Referenced by addarth(), addili(), addother(), visit_ili_operands(), and visit_ilis().
opc_comp_zero_one()
static ILI_OP opc_comp_zero_one (int cmp_ili, int * invert_cc, int * label_op) static
Definition at line 10576 of file iliutil.cpp.
optype()
static int optype (ILI_OP opc) static
Definition at line 11370 of file iliutil.cpp.
Referenced by __fortio_rwinit(), ad2ili(), addcomponents(), binop_init_list(), fill_ast(), findcomponents(), forall_lhs_indirection(), getoperand(), hash_binop(), hash_unop(), MakeReplacement(), mk_binop(), mk_conformable_test(), mk_poly_test(), mk_unop(), print_ast(), putoptype(), rewrite_func_ast(), schedule(), and unop_init_list().
prcon()
static void prcon (int sptr) static
Definition at line 11361 of file iliutil.cpp.
prilitree()
void prilitree (int i)
...
Definition at line 11404 of file iliutil.cpp.
prnme()
static void prnme (int opn, int ili) static
Definition at line 11295 of file iliutil.cpp.
prsym()
static void prsym (int sym, FILE * ff) static
Definition at line 10566 of file iliutil.cpp.
qjsr_in()
bool qjsr_in (int ilix)
Search the ili subtree located by ilix for QJSRs.
...
This routine is used instead of ili_traverse of qjrsearch when the visit_list is already being used (ili_traverse needs the visit_list).
Definition at line 9804 of file iliutil.cpp.
Referenced by check_ilm().
qjsrsearch()
int qjsrsearch (int ilix)
Look for 'QJSR' in this tree.
...
Definition at line 12875 of file iliutil.cpp.
reciprocal_division()
static int reciprocal_division (int n, INT divisor, int sgnd) static
Definition at line 2097 of file iliutil.cpp.
References ad1ili(), ad2ili(), ad_kcon(), choose_multiplier(), cmp64(), ICON(), IL_IADD, IL_INEG, IL_ISUB, lg(), mrecip, MULSH(), MULUH(), n, q, shf64(), shpost, sub64(), t1, t2, twon, twonm1, and XSIGN().
Referenced by addarth(), and reciprocal_mod().
reciprocal_division_64()
static int reciprocal_division_64 (int n, DBLINT64 divisor, int sgnd) static
Definition at line 2211 of file iliutil.cpp.
References ad1ili(), ad2ili(), ad_kcon(), and64(), choose_multiplier_64(), cmp128(), cmp64(), ICON(), INT, KMULSH(), KMULUH(), KXSIGN(), lg64(), mrecip_128, n, neg64(), q, shf64(), shpost, sub128(), t1, t2, twon_128, twonm1_128, and ushf64().
Referenced by addarth(), and reciprocal_mod_64().
reciprocal_mod()
static int reciprocal_mod (int n, int d, int sgnd) static
Definition at line 2329 of file iliutil.cpp.
References ad2ili(), d, ICON(), IL_ISUB, MUL(), n, reciprocal_division(), and sub.
Referenced by addarth().
reciprocal_mod_64()
static int reciprocal_mod_64 (int n, DBLINT64 d, int sgnd) static
Definition at line 2349 of file iliutil.cpp.
References ad2ili(), ad_kcon(), d, KMUL(), n, reciprocal_division_64(), and sub.
Referenced by addarth().
red_aadd()
static int red_aadd (int ilix, SPTR sym, ISZ_T off, int scale) static
constant folds the address add ili (aadd)
Definition at line 8086 of file iliutil.cpp.
References ACONOFFG, ad_acon(), ad_aconi(), get_ili(), IL_AADD, IL_ASUB, ILI_OPC, ILI_OPND, ILI_SymOPND, ISZ_T, off, ILI::opc, ILI::opnd, red_aadd(), scale, SPTR_NULL, sptrGetILI, and SymConval1.
Referenced by addarth(), and red_aadd().
red_damv()
static int red_damv (int opr, int damv, int scale) static
combines the operand of damv's in an aadd expr
Routine which simplifies an aadd expression where one of the operands is a damv ILI. This routine combines the operand of the damv with any other damv's in opr by performing an iadd followed by a damv.
Parameters
opr locates expression of an aadd
damv damv ILI
scale scale of aadd - if >= 0 scale operand of damv, if < 0
scale operand of opr if damv
Definition at line 8206 of file iliutil.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad_icon(), ad_kconi(), IL_AADD, IL_ASUB, IL_IADD, IL_IMUL, IL_RES, ILI_OPC, ILI_OPND, ILIA_IR, ILIA_KR, red_damv(), scale, and tmp.
Referenced by addarth(), and red_damv().
red_iadd()
static int red_iadd (int ilix, INT con) static
constant folds the integer add ili (iadd)
Definition at line 7882 of file iliutil.cpp.
References ad1ili(), ad_icon(), CONVAL2G, get_ili(), STB::i0, IL_IADD, IL_INEG, IL_ISUB, ILI_OPC, ILI_OPND, ILI::opc, ILI::opnd, red_iadd(), stb, and val.
Referenced by addarth(), and red_iadd().
red_kadd()
static int red_kadd (int ilix, INT con[2]) static
constant folds the integer*8 add ili (kadd)
Definition at line 7984 of file iliutil.cpp.
References ad1ili(), add64(), CONVAL2G, get_ili(), getcon(), ILI_OPC, ILI_OPND, STB::k0, neg64(), ILI::opc, ILI::opnd, red_kadd(), stb, tmp, and val.
Referenced by addarth(), and red_kadd().
red_minmax()
static int red_minmax (ILI_OP opc, int op1, int op2) static
Simplify
   max( max(x, y), y )
   max( y, max(x, y) )
as
   max(x, y)
Definition at line 8283 of file iliutil.cpp.
References get_ili(), ILI_OPC, ILI_OPND, ILI::opc, and ILI::opnd.
Referenced by addarth().
red_negate()
static int red_negate (int old, ILI_OP neg_opc, int mult_opc, int div_opc) static
Transform -(c<OP>x<OP>y) into (-c)<OP>x<OP>y; OP is a mult or divide.
Definition at line 8305 of file iliutil.cpp.
References ad1ili(), ad2ili(), IL_TYPE, ILI_OPC, ILI_OPND, ILTY_CONS, red_negate(), and XBIT.
Referenced by addarth(), and red_negate().
relaxed_math()
char * relaxed_math (const char * root, int widthc, int typec, const char * oldname)
Called if and only if there exists the possiblity of a -Mfprelaxed=intrinsic version of the routine.
...
Definition at line 1173 of file iliutil.cpp.
References fast_math(), FEATURE_FMA4, FEATURE_SIMD128, MACH_AMD_BULLDOZER, MACH_INTEL_SANDYBRIDGE, root, TEST_FEATURE, TEST_MACH, and XBIT_NEW_RELAXEDMATH.
Referenced by addarth(), exp_ac(), and vect_math().
restore_rewr_count()
void restore_rewr_count (int c)
...
Definition at line 10005 of file iliutil.cpp.
rewr_()
static int rewr_ (int tree) static
Definition at line 10165 of file iliutil.cpp.
rewr_cln()
static void rewr_cln (int tree) static
Definition at line 10508 of file iliutil.cpp.
rewr_cln_ili()
void rewr_cln_ili (void)
...
Definition at line 10478 of file iliutil.cpp.
Referenced by exp_mp_atomic_capture(), and get_complex_update_operand().
rewr_cln_nm()
static void rewr_cln_nm (int nme) static
Definition at line 10534 of file iliutil.cpp.
rewr_ili()
int rewr_ili (int tree, int old, int New)
...
Definition at line 10016 of file iliutil.cpp.
Referenced by exp_mp_atomic_capture(), and get_complex_update_operand().
rewr_ili_nme()
int rewr_ili_nme (int tree, int oldili, int newili, int oldnme, int newnme, int douse, int dodef)
...
Rewrites the ili tree 'tree', changing 'oldili' into 'newili' and the nme 'oldnme' into 'newnme'; saves 'tree' in 'rewrb'.
Must be followed by a call to rewr_cln_ili.
Definition at line 10067 of file iliutil.cpp.
rewr_indirect_nme()
static int rewr_indirect_nme (int nmex) static
Definition at line 10103 of file iliutil.cpp.
rewr_nm()
static int rewr_nm (int nme) static
Definition at line 10398 of file iliutil.cpp.
rewr_these_ili()
void rewr_these_ili (int oldili, int newili)
...
Definition at line 9943 of file iliutil.cpp.
rewr_these_ili_nme()
void rewr_these_ili_nme (int oldili, int newili, int oldnme, int newnme)
...
Definition at line 9964 of file iliutil.cpp.
save_rewr_count()
int save_rewr_count (void)
...
Definition at line 9999 of file iliutil.cpp.
scond()
const char * scond (int c)
...
Definition at line 14168 of file iliutil.cpp.
Referenced by putstc().
sel_aconv()
int sel_aconv (int ili)
Select an IR or KR conversion to AR.
...
Definition at line 13307 of file iliutil.cpp.
sel_decr()
int sel_decr (int ili, int isi8)
Select an IR or KR substract by 1.
...
Definition at line 13297 of file iliutil.cpp.
sel_icnst()
int sel_icnst (ISZ_T val, int isi8)
Select an integer constant ili, ICON or KCON.
...
Definition at line 13270 of file iliutil.cpp.
Referenced by create_array_subscr(), and inlarr().
sel_iconv()
int sel_iconv (int ili, int isi8)
Select an integer conversion: IR/KR to IR, or IR/KR to KR.
...
Definition at line 13281 of file iliutil.cpp.
Referenced by _make_mp_get_threadprivate(), addCopyinInplace(), arg_ir(), arg_kr(), exp_call(), exp_fstring(), exp_smp(), inlarr(), loadUplevelArgsForRegion(), and makeCopyprivArray_tls().
simplified_cmp_ili()
int simplified_cmp_ili (int cmp_ili)
returns simplified version of comparison ili
...
Parameters
cmp_ili Comparison ILI
simplify following eight cases:
(1)
         X = IL_xxCMP A, B, cmp_op
         Y = IL_ICMP X, 1, eq
     =>
         Y = IL_xxCMP A, B, cmp_op
(2)
         X = IL_xxCMPZ A, cmp_op
         Y = IL_ICMP X, 1, eq
     =>
         Y = IL_xxCMPZ A, cmp_op
(3)
         X = IL_xxCMP A, B, cmp_op
         Y = IL_ICMP X, 1, ne
     =>
         Y = IL_xxCMP A, B, ~cmp_op
(4)
         X = IL_xxCMPZ A, cmp_op
         Y = IL_ICMP X, 1, ne
     =>
         Y = IL_xxCMPZ A, ~cmp_op
(5)
         X = IL_xxCMP A, B, cmp_op
         Y = IL_ICMPZ X, eq
     =>
         Y = IL_xxCMP A, B, ~cmp_op
(6)
         X = IL_xxCMPZ A, cmp_op
         Y = IL_ICMPZ X, eq
     =>
         Y = IL_xxCMPZ A, ~cmp_op
(7)
         X = IL_xxCMP A, B, cmp_op
         Y = IL_ICMPZ X, ne
     =>
         Y = IL_xxCMP A, B, cmp_op
(8)
         X = IL_xxCMPZ A, cmp_op
         Y = IL_ICMPZ X, ne
     =>
         Y = IL_xxCMPZ A, cmp_op
This algorithm is applied recursively to simplify chains of comparison to one and zero
Definition at line 10665 of file iliutil.cpp.
sort_free_list()
static int sort_free_list (int head) static
Sort the free list.
Sorting the free list removes a source of indeterminacy from the compiler's intermediate representation that would otherwise be introduced by hashing the ILIs.
Definition at line 9577 of file iliutil.cpp.
uikmove()
int uikmove (int ilix)
...
Definition at line 14199 of file iliutil.cpp.
value_of_irlnk_operand()
static INT value_of_irlnk_operand (int ilix, int default_value) static
Return value of irlnk operand if its value is known, otherwise return default_value.
Definition at line 14745 of file iliutil.cpp.
Referenced by addother().
vect_math()
static char * vect_math (MTH_FN fn, const char * root, int nargs, DTYPE vdt, int vopc, int vdt1, int vdt2, bool mask) static
Definition at line 951 of file iliutil.cpp.
References assert, DT_DBLE, DT_FLOAT, DT_INT, DTY, DTySeqTyElement, DTyVecLength, ERR_Fatal, ERR_Severe, fast_math(), fn, func, get_vector_dtype(), gnr_math(), interr(), make_math_name(), mk_prototype, MTH_mod, nargs, relaxed_math(), root, TY_DBLE, TY_FLOAT, XBIT_NEW_MATH_NAMES, and XBIT_NEW_RELAXEDMATH.
Referenced by addarth().
XSIGN()
static int XSIGN (int ilix, int N) static
Definition at line 2027 of file iliutil.cpp.
References ad2ili(), ICON(), t, and t1.
Referenced by reciprocal_division().
Variable Documentation
all_acon
int all_acon
Definition at line 9936 of file iliutil.cpp.
args
argtype* args static
Definition at line 14006 of file iliutil.cpp.
Referenced by _dumpilmtree(), _find_lhs_on_rhs_conflict(), _find_pointer_assignments_f90(), _find_rhs_def_conflict(), _findrefs(), _is_another_shift(), _linearize_func(), _PDsize(), _rewrite_scalar_fuctions(), _RTE_size(), ad_func(), build_array_ref(), convert_template_instance(), create_global(), dast(), dastreex(), dump_loop_args(), dumpilmtrees(), dumpsingleilm(), exp_pure(), exp_smp(), f90_function(), f90_value_function(), f90_value_function_I2(), find_descrs(), find_lhs_on_rhs_conflict(), find_rhs_conflict(), fixup_x86_abi_return(), gen_llvm_expr(), gen_poly_element_arg(), get_intrinsic_call_ops(), get_lhs_first_defs(), handle_arguments(), ILMTPApp::ILMTPApp(), inline_reduction_f90(), inline_shifts(), inline_small_matmul(), intrinsic_arg_dtype(), isptrdef_in_path(), leave_arg(), ll_ad_outlined_func2(), ll_add_func_proto(), ll_convert_iface_sptr(), ll_create_function_type(), ll_get_function_pointer(), ll_make_kmpc_atomic_read(), ll_make_kmpc_atomic_write(), ll_make_kmpc_copyprivate(), ll_make_kmpc_critical(), ll_make_kmpc_dispatch_fini(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_end_critical(), ll_make_kmpc_end_serialized_parallel(), ll_make_kmpc_flush(), ll_make_kmpc_for_static_init(), ll_make_kmpc_for_static_init_args(), ll_make_kmpc_fork_call(), ll_make_kmpc_fork_teams(), ll_make_kmpc_generic_ptr(), ll_make_kmpc_generic_ptr_2int(), ll_make_kmpc_generic_ptr_int(), ll_make_kmpc_proto(), ll_make_kmpc_push_num_teams(), ll_make_kmpc_serialized_parallel(), ll_make_kmpc_task(), ll_make_kmpc_task_arg(), ll_make_kmpc_task_begin_if0(), ll_make_kmpc_task_complete_if0(), ll_make_kmpc_task_yield(), ll_make_kmpc_taskloop(), ll_make_kmpc_threadprivate(), ll_make_kmpc_threadprivate_cached(), ll_make_kmpc_threadprivate_register(), ll_make_kmpc_threadprivate_register_vec(), ll_make_outlined_call2(), ll_make_outlined_task_call(), ll_make_sections_args(), lower_function(), lower_intrinsic(), lower_stmt(), Machar::Machar(), makeOutlinedFunc(), N2Rst::N2Rst(), ptrdefs_has_lhsconflict(), ref_stfunc(), rewrite_asn(), rewrite_calls(), rewrite_sub_ast(), sfloat(), size_shape(), SyminiF90::SyminiF90(), Symutil::Symutil(), and vmk_prototype().
argsize
int argsize static
Definition at line 14007 of file iliutil.cpp.
base
rewrtstruct* base
Definition at line 9924 of file iliutil.cpp.
Referenced by ad_load().
cnt
int cnt
Definition at line 9926 of file iliutil.cpp.
Referenced by ili_init().
ilhsh
int ilhsh[ILTABSZ][ILHSHSZ] static
Definition at line 119 of file iliutil.cpp.
Referenced by ili_init().
ishft
bool ishft extern
Definition at line 77 of file exp_ftn.cpp.
Referenced by addarth(), and exp_ac().
memory_order_fail_table
char memory_order_fail_table[MO_MAX_DEF+1][MO_MAX_DEF+1]
Initial value:
= {
    {MO_RELAXED, MO_RELAXED, MO_RELAXED, MO_RELAXED, MO_RELAXED, MO_RELAXED},
    {MO_RELAXED, MO_CONSUME, MO_CONSUME, MO_RELAXED, MO_CONSUME, MO_CONSUME},
    {MO_RELAXED, MO_CONSUME, MO_ACQUIRE, MO_RELAXED, MO_ACQUIRE, MO_ACQUIRE},
    {MO_RELAXED, MO_RELAXED, MO_RELAXED, MO_RELAXED, MO_RELAXED, MO_RELAXED},
    {MO_RELAXED, MO_CONSUME, MO_ACQUIRE, MO_RELAXED, MO_ACQUIRE, MO_ACQUIRE},
    {MO_RELAXED, MO_CONSUME, MO_ACQUIRE, MO_RELAXED, MO_ACQUIRE, MO_SEQ_CST},
}
Table used by cmpxchg_memory_order.
Indexed by [succ][fail], it returns an weakened value for failure
per rules in C++11 standard and LLVM. The weakenings guarantee that the failure value is no stronger than the succ value and has no "release" aspect to it.
Element type is char to save space.
this table is also used by accelerator CG, so DON'T make it as static
Definition at line 14842 of file iliutil.cpp.
mrecip
DBLINT64 mrecip static
Definition at line 1792 of file iliutil.cpp.
Referenced by choose_multiplier(), and reciprocal_division().
mrecip_128
INT128 mrecip_128 static
Definition at line 1845 of file iliutil.cpp.
Referenced by choose_multiplier_64(), and reciprocal_division_64().
nargs
int nargs static
Definition at line 14007 of file iliutil.cpp.
Referenced by _olap_conflict(), _transform_func(), ad_func(), aliased_args(), build_array_ref(), build_conformable_func_node(), check_desc(), check_desc_args(), Conflict_(), conv_deallocate(), convert_subscript_in_expr(), copy_inargs(), emit_alnd(), emit_fl(), emit_get_scalar_sub(), emit_kopy_in(), emit_permute_section(), emit_secd(), emit_sum_scatterx(), ENTF90(), eval_max(), eval_min(), exp_call(), exp_pure(), exp_qjsr(), exp_zqjsr(), extent(), extract_shape_from_args(), f90_function(), f90_value_function(), f90_value_function_I2(), fill_cyclic_k(), find_descrs(), find_presence(), func_has_char_args(), gen_arg_operand(), gen_copy_out(), gen_islocal_index(), gen_localize_index(), gen_ptr_in(), gen_ptr_out(), generate_copy(), generate_gather(), generate_get_scalar(), generate_hcycliclp(), generate_hlocalizebnds(), get_scalar_in_expr(), has_opt_args(), init_sdsc(), init_sdsc_bounds(), inline_ast(), inline_spread_shifts(), insert_comm_before(), insert_forall_comm(), is_call_dependent(), is_ptrast_arg(), ll_abi_alloc(), ll_ad_outlined_func2(), ll_add_func_proto(), ll_make_outlined_call(), ll_make_outlined_call2(), ll_make_outlined_garg(), lower_intrinsic(), make_function_type_from_args(), make_sec_from_ast_chk(), make_simple_template_from_ast(), make_temp_descriptor(), matmul(), missing_optionals(), mk_prototype(), mk_prototype_llvm(), mmul(), need_intr_argbf(), normalize_forall(), not_in_arrfn(), pp_entries(), pp_entries_mixedstrlen(), pp_params(), pp_params_mixedstrlen(), process_ll_abi_func_ftn_mod(), put_call_comm(), put_forall_pcalls(), remove_alias(), remove_from_scalar_subscript(), remove_function_common_from_scalar_subscript(), remove_parent_from_ast(), reorder_args(), replace_expr(), replace_vector_subscript(), reshape(), rewrite_func_ast(), rewrite_sub_args(), scalar_communication(), search_conform_array(), shape_comm(), shape_comm_in_expr(), tag_forall_comm(), trans_mkproc(), transform_all_call(), transform_associated(), transform_c_f_pointer(), transform_c_f_procpointer(), transform_call(), transform_elemental(), transform_merge(), transform_move_alloc(), transform_mvbits(), transform_ptr(), transform_pure_function(), vect_math(), and vmk_prototype().
need_to_rename
int need_to_rename = 0 static
Definition at line 9919 of file iliutil.cpp.
override_abi
bool override_abi = false static
Definition at line 14575 of file iliutil.cpp.
rewr_def
int rewr_def = 1 static
Definition at line 9918 of file iliutil.cpp.
rewr_new
int rewr_new static
Definition at line 9917 of file iliutil.cpp.
rewr_new_nme
int rewr_new_nme static
Definition at line 9917 of file iliutil.cpp.
rewr_old
int rewr_old static
Definition at line 9917 of file iliutil.cpp.
rewr_old_nme
int rewr_old_nme static
Definition at line 9917 of file iliutil.cpp.
rewr_use
int rewr_use = 1 static
Definition at line 9918 of file iliutil.cpp.
struct { ... } rewrb
rewrite_nme_indirect
int rewrite_nme_indirect = 0 static
Definition at line 9920 of file iliutil.cpp.
struct { ... } rewrt
safe_qjsr
bool safe_qjsr = false static
Definition at line 120 of file iliutil.cpp.
Referenced by addili().
share_proc_ili
bool share_proc_ili = false
Definition at line 65 of file iliutil.cpp.
Referenced by addili(), expand(), and makeCall().
share_qjsr_ili
bool share_qjsr_ili = false
Definition at line 66 of file iliutil.cpp.
Referenced by addili(), and makeCall().
shpost
int shpost static
Definition at line 1791 of file iliutil.cpp.
Referenced by choose_multiplier(), choose_multiplier_64(), reciprocal_division(), and reciprocal_division_64().
size
int size
Definition at line 9925 of file iliutil.cpp.
twon
DBLINT64 twon static
Definition at line 1793 of file iliutil.cpp.
Referenced by choose_multiplier(), and reciprocal_division().
twon_128
INT128 twon_128 static
Definition at line 1846 of file iliutil.cpp.
Referenced by choose_multiplier_64(), and reciprocal_division_64().
twonm1
DBLINT64 twonm1 static
Definition at line 1793 of file iliutil.cpp.
Referenced by choose_multiplier(), and reciprocal_division().
twonm1_128
INT128 twonm1_128 static
Definition at line 1846 of file iliutil.cpp.
Referenced by choose_multiplier_64(), and reciprocal_division_64().
visit_list
int visit_list = 0 static
Definition at line 9831 of file iliutil.cpp.