flang: iliutil.h File Reference
iliutil.h File Reference
#include "gbldefs.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "ilm.h"
#include "ilmtp.h"
#include "ili.h"
#include "mth.h"
Macros
#define CC_ILI_OPND ILI_OPND
#define DT_ILI_OPND ILI_OPND
#define GetAtomicDecodeMsz(E) atomic_decode(E).msz
Functions
ATOMIC_INFO atomic_decode (int encoding)
...
ATOMIC_INFO atomic_info (int ilix)
...
ISZ_T get_isz_conili (int ili)
...
bool cc_includes_equality (CC_RELATION cc)
...
bool ccs_are_complementary (CC_RELATION cc1, CC_RELATION cc2)
...
bool cmpxchg_is_weak (int ilix)
...
bool _find_ili (int ilix, int find_this)
...
bool find_ili (int tree, int it)
...
bool func_in (int ilix)
...
bool is_floating_comparison_opcode (ILI_OP opc)
...
bool is_integer_comparison_opcode (ILI_OP opc)
...
bool is_llvm_local (int sptr, int funcsptr)
...
bool is_llvm_local_private (int sptr)
...
bool is_omp_atomic_ld (int ilix)
...
bool is_omp_atomic_st (int ilix)
...
bool is_unsigned_opcode (ILI_OP opc)
...
bool qjsr_in (int ilix)
...
CC_RELATION combine_ieee_ccs (CC_RELATION binary_cc, CC_RELATION zero_cc)
...
CC_RELATION combine_int_ccs (CC_RELATION binary_cc, CC_RELATION zero_cc)
...
CC_RELATION commute_cc (CC_RELATION cc)
...
CC_RELATION complement_ieee_cc (CC_RELATION cc)
...
CC_RELATION complement_int_cc (CC_RELATION cc)
...
const char * dump_msz (MSZ ms)
...
char * fast_math (const char *root, int widthc, int typec, const char *oldname)
...
char * gnr_math (const char *root, int widthc, int typec, const char *oldname, int masked)
...
char * make_math (MTH_FN fn, SPTR *fptr, int vectlen, bool mask, DTYPE res_dt, int nargs, int arg1_dt_,...)
...
char * make_math_name (MTH_FN fn, int vectlen, bool mask, DTYPE res_dt)
...
char * make_math_name_vabi (MTH_FN fn, int vectlen, bool mask, DTYPE res_dt)
...
char * relaxed_math (const char *root, int widthc, int typec, const char *oldname)
...
const char * scond (int c)
...
CMPXCHG_MEMORY_ORDER cmpxchg_memory_order (int ilix)
...
DTYPE ili_get_vect_dtype (int ilix)
...
ILI_OP ldopc_from_stopc (ILI_OP stopc)
...
int ad1ili (ILI_OP opc, int opn1)
...
int ad2func_kint (ILI_OP opc, const char *name, int opn1, int opn2)
...
int ad2ili (ILI_OP opc, int opn1, int opn2)
...
int ad3ili (ILI_OP opc, int opn1, int opn2, int opn3)
add ili with three operands
int ad4ili (ILI_OP opc, int opn1, int opn2, int opn3, int opn4)
add ili with four operands
int ad5ili (ILI_OP opc, int opn1, int opn2, int opn3, int opn4, int opn5)
add ili with five operands
int ad_aconi (ISZ_T val)
add ACON ili with specified (integer) constant
int ad_acon (SPTR sym, ISZ_T val)
add ACON ili with specified symbol and offset
int ad_aconk (INT m32, INT l32)
Add acon ili of an 64-bit constant whose value consists of m32 (most significant 32 bits) and l32 (least significant 32 bits).
int ad_cmpxchg (ILI_OP opc, int ilix_val, int ilix_loc, int nme, int stc_atomic_info, int ilix_comparand, int ilix_is_weak, int ilix_success, int ilix_failure)
...
int ad_cse (int ilix)
add CSE ili of an ili
int addili (ILI *ilip)
...
int ad_free (int ilix)
Add a IL_FREEx with given operand.
int ad_icon (INT val)
add ICON ili with specified constant value
int ad_kconi (ISZ_T v)
Add kcon ili of an 64-bit constant.
int ad_kcon (INT m32, INT l32)
Add KCON ili of an 64-bit constant whose value consists of m32 (most significant 32 bits) and l32 (least significant 32 bits).
int ad_load (int stx)
Given a store ILI, generate the equivalent load ILI.
int alt_qjsr (int ilix)
...
int atomic_encode (MSZ msz, SYNC_SCOPE scope, ATOMIC_ORIGIN origin)
...
int atomic_encode_rmw (MSZ msz, SYNC_SCOPE scope, ATOMIC_ORIGIN origin, ATOMIC_RMW_OP op)
...
int atomic_info_index (ILI_OP opc)
...
int cmpxchg_loc (int ilix)
...
int compl_br (int ilix, int lbl)
...
int compute_address (SPTR sptr)
...
int gencallargs (void)
...
int genregcallargs (void)
...
int genretvalue (int ilix, ILI_OP resultopc)
...
int get_ili_ns (ILI *ilip)
...
int get_rewr_new_nme (int nmex)
...
int has_cse (int ilix)
...
int iadd_const_ili (ISZ_T valconst, int valilix)
...
int iadd_ili_ili (int leftx, int rightx)
...
int idiv_ili_const (int valilix, ISZ_T valconst)
...
int idiv_ili_ili (int leftx, int rightx)
...
int ikmove (int ilix)
...
int ili_get_vect_arg_count (int ilix)
...
int ili_isdeleted (int ili)
...
int ili_opnd (int ilix, int n)
return nth operand of ili - skipping past CSE ili if present
int ili_subscript (int sub)
...
int ili_throw_label (int ilix)
...
int ili_traverse (int(*visit_f)(int), int ilix)
...
int ilstckind (ILI_OP opc, int opnum)
...
int imax_ili_ili (int leftx, int rightx)
...
int imin_ili_ili (int leftx, int rightx)
...
int imul_const_ili (ISZ_T valconst, int valilix)
...
int imul_ili_ili (int leftx, int rightx)
...
int is_argili_opcode (ILI_OP opc)
...
int is_cseili_opcode (ILI_OP opc)
...
int is_daili_opcode (ILI_OP opc)
...
int is_dfrili_opcode (ILI_OP opc)
...
int is_freeili_opcode (ILI_OP opc)
...
int is_mvili_opcode (ILI_OP opc)
...
int is_rgdfili_opcode (ILI_OP opc)
...
int isub_ili_ili (int leftx, int rightx)
...
int jsrsearch (int ilix)
...
int kimove (int ilix)
...
int ll_ad_outlined_func (ILI_OP result_opc, ILI_OP call_opc, char *func_name, int narg, int arg1, int arg2, int arg3)
...
int mk_address (SPTR sptr)
...
int mk_charlen_parref_sptr (SPTR sptr)
...
int mkfunc_avx (char *nmptr, int avxp)
...
int qjsrsearch (int ilix)
...
int rewr_ili (int tree, int old, int New)
...
int rewr_ili_nme (int tree, int oldili, int newili, int oldnme, int newnme, int douse, int dodef)
...
int save_rewr_count (void)
...
int sel_aconv (int ili)
...
int sel_decr (int ili, int isi8)
...
int sel_icnst (ISZ_T val, int isi8)
...
int sel_iconv (int ili, int isi8)
...
int simplified_cmp_ili (int cmp_ili)
...
int uikmove (int ilix)
...
MEMORY_ORDER memory_order (int ilix)
...
MSZ mem_size (TY_KIND ty)
...
void addcallarg (int ili, int nme, int dtype)
...
void choose_multiplier_64 (int N, DBLUINT64 dd, int prec)
...
void choose_multiplier (int N, unsigned dd, int prec)
...
void _ddilitree (int i, int flag)
...
void ddilitree (int i, int flag)
...
void dmpilitree (int i)
...
void dmpili (void)
...
void dump_atomic_info (FILE *f, ATOMIC_INFO info)
...
void dump_ili (FILE *f, int i)
...
void garbage_collect (void(*mark_function)(int))
...
void ili_cleanup (void)
...
void ili_init (void)
...
void ili_unvisit (void)
...
void ili_visit (int ilix, int v)
...
void initcallargs (int count)
...
void inline_mulh (void)
...
void ldst_msz (DTYPE dtype, ILI_OP *ld, ILI_OP *st, MSZ *siz)
...
void llmk_math_name (char *buff, int fn, int vectlen, bool mask, DTYPE res_dt)
...
void prilitree (int i)
...
void restore_rewr_count (int c)
...
void rewr_cln_ili (void)
...
void rewr_these_ili (int oldili, int newili)
...
void rewr_these_ili_nme (int oldili, int newili, int oldnme, int newnme)
...
Variables
bool share_proc_ili
bool share_qjsr_ili
Macro Definition Documentation
CC_ILI_OPND
#define CC_ILI_OPND ILI_OPND
Definition at line 31 of file iliutil.h.
DT_ILI_OPND
#define DT_ILI_OPND ILI_OPND
Definition at line 32 of file iliutil.h.
GetAtomicDecodeMsz
#define GetAtomicDecodeMsz (E) atomic_decode(E).msz
Definition at line 45 of file iliutil.h.
Function Documentation
_ddilitree()
void _ddilitree (int i, int flag)
...
Definition at line 12412 of file iliutil.cpp.
_find_ili()
bool _find_ili (int ilix, int find_this)
...
Definition at line 9834 of file iliutil.cpp.
ad1ili()
int ad1ili (ILI_OP opc, int opn1)
...
...
Definition at line 396 of file iliutil.cpp.
References addili(), ILI::opc, and ILI::opnd.
Referenced by ad1func_cmplx(), ad1func_cmplx_abi(), ad2func_cmplx(), ad2func_cmplx_abi(), ad2func_int(), ad2func_kint(), ad_acon(), ad_aconi(), ad_aconk(), ad_cse(), ad_free(), ad_func(), ad_icon(), ad_kcon(), ad_kconi(), addarth(), addbran(), addili(), addother(), gen_sincos(), ICON(), ili_init(), reciprocal_division(), reciprocal_division_64(), red_damv(), red_iadd(), red_kadd(), and red_negate().
ad2func_kint()
int ad2func_kint (ILI_OP opc, const char * name, int opn1, int opn2)
...
...
Parameters
opc must be a function call ili opcode: QJSR, JSR
Definition at line 1216 of file iliutil.cpp.
References _mkfunc(), ad1ili(), ad2ili(), KR_RETVAL, name, and tmp.
Referenced by exp_ac().
ad2ili()
int ad2ili (ILI_OP opc, int opn1, int opn2)
...
...
Definition at line 435 of file iliutil.cpp.
References addili(), ILI::opc, and ILI::opnd.
Referenced by ad1func_cmplx(), ad1func_cmplx_abi(), ad2func_cmplx(), ad2func_cmplx_abi(), ad2func_int(), ad2func_kint(), ad_func(), ad_load(), addarth(), addbran(), addili(), KMUL(), KMULSH(), KMULUH(), KXSIGN(), MUL(), MULSH(), MULUH(), reciprocal_division(), reciprocal_division_64(), reciprocal_mod(), reciprocal_mod_64(), red_damv(), red_negate(), and XSIGN().
ad3ili()
int ad3ili (ILI_OP opc, int opn1, int opn2, int opn3)
add ili with three operands
Definition at line 1227 of file iliutil.cpp.
References addili(), ILI::opc, and ILI::opnd.
Referenced by _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_smove(), ad1func_cmplx(), ad1func_cmplx_abi(), ad2func_cmplx(), ad2func_cmplx_abi(), ad_func(), ad_load(), add_arglnk_closure(), add_ptr_subscript(), add_reg_arg_ili(), addarth(), addbran(), addCopyinInplace(), addother(), allochartmp(), allocThreadprivate(), arg_ar(), assign1(), begin_entry(), block_str_move(), charlen(), check_ilm(), cmplx_to_mem(), compute_sdsc_subscr(), cp_byval_mem_arg(), create_array_ref(), create_atomic_capture_seq(), create_atomic_read_seq(), create_atomic_seq(), create_atomic_write_seq(), create_ref(), create_sdsc_subscr(), exp_ac(), exp_add_copy(), exp_bran(), exp_call(), exp_end(), exp_fstring(), exp_header(), exp_load(), exp_misc(), exp_mp_atomic_capture(), exp_pure(), exp_qjsr(), exp_restore_mxcsr(), exp_smp(), exp_store(), exp_strx(), exp_szero(), exp_type_bound_proc_call(), exp_zqjsr(), finish_array(), gen_bindC_retval(), gen_funcret(), genIntLoad(), genload(), genswitch(), get_chain_pointer_closure(), get_complex_update_operand(), get_sdsc_element(), is_blockaddr_store(), jsrAddArg(), ld_sptr(), ll_ad_outlined_func2(), ll_get_gtid_val_ili(), ll_load_outlined_args(), ll_make_outlined_gjsr(), llLoadGtid(), llvmAddConcurEntryBlk(), load_uplevel_addresses(), loadCharLen(), makeCopyprivArray(), makeCopyprivArray_tls(), mk_charlen_address(), mk_function_call(), mk_kmpc_api_call(), red_damv(), redundantLdLdElim(), ref_threadprivate(), ref_threadprivate_var(), rm_smove(), sectionCreateBlock(), setTaskloopVars(), storechartmp(), storedums(), toUplevelAddr(), widenProcessDirectLoad(), and widenProcessIndirectLoad().
ad4ili()
int ad4ili (ILI_OP opc, int opn1, int opn2, int opn3, int opn4)
add ili with four operands
Definition at line 1263 of file iliutil.cpp.
References addili(), ILI::opc, and ILI::opnd.
Referenced by _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_mp_atomic_write(), _exp_smove(), ad_func(), add_gargl_closure(), addbran(), addCopyinInplace(), block_str_move(), check_ilm(), cmplx_to_mem(), cp_byval_mem_arg(), create_atomic_capture_seq(), create_atomic_read_seq(), create_atomic_seq(), create_atomic_write_seq(), exp_add_copy(), exp_bran(), exp_call(), exp_end(), exp_fstring(), exp_misc(), exp_mp_atomic_capture(), exp_mp_atomic_update(), exp_smp(), exp_store(), exp_type_bound_proc_call(), gen_bindC_retval(), genIntStore(), genSizeAcon(), genswitch(), get_complex_update_operand(), handle_nested_threadprivate(), is_blockaddr_store(), ll_make_kmpc_task_arg(), ll_make_outlined_garg(), llLoadGtid(), load_uplevel_addresses(), loadUplevelArgsForRegion(), makeCopyprivArray(), makeCopyprivArray_tls(), redundantLdLdElim(), rm_smove(), sectionCreateBlock(), setTaskloopVars(), store_aret(), storechartmp(), storedums(), widenInsertWideStore(), and widenPushdown().
ad5ili()
int ad5ili (ILI_OP opc, int opn1, int opn2, int opn3, int opn4, int opn5)
add ili with five operands
Definition at line 1295 of file iliutil.cpp.
References addili(), ILI::opc, and ILI::opnd.
Referenced by _exp_mp_atomic_write(), _exp_smove(), cloneUplevel(), exp_mp_atomic_capture(), exp_mp_atomic_update(), expand_smove(), and pp_params().
ad_acon()
int ad_acon (SPTR sym, ISZ_T val)
add ACON ili with specified symbol and offset
Definition at line 1356 of file iliutil.cpp.
References ad1ili(), get_acon(), and val.
Referenced by allochartmp(), allocThreadprivate(), begin_entry(), check_ilm(), cloneUplevel(), cmplx_to_mem(), cp_byval_mem_arg(), create_ref(), exp_add_copy(), exp_bran(), exp_call(), exp_end(), exp_header(), exp_pure(), exp_qjsr(), exp_restore_mxcsr(), exp_smp(), exp_zqjsr(), gen_bindC_retval(), gen_funcret(), genIntLoad(), genIntStore(), genSizeAcon(), genswitch(), get_chain_pointer_closure(), is_blockaddr_store(), ll_get_gtid_addr_ili(), ll_get_gtid_val_ili(), ll_load_outlined_args(), ll_make_kmpc_copyprivate(), ll_make_kmpc_critical(), ll_make_kmpc_end_critical(), ll_make_kmpc_task(), ll_make_kmpc_task_arg(), ll_make_kmpc_task_begin_if0(), ll_make_kmpc_task_complete_if0(), ll_make_outlined_task_call(), ll_make_sections_args(), llGetThreadprivateAddr(), llLoadGtid(), llvmAddConcurEntryBlk(), load_uplevel_addresses(), loadUplevelArgsForRegion(), makeCopyprivArray(), makeCopyprivArray_tls(), mk_charlen_address(), mk_swlist(), pp_params(), red_aadd(), ref_threadprivate(), ref_threadprivate_var(), sectionCreateBlock(), setTaskloopVars(), store_aret(), storechartmp(), and toUplevelAddr().
ad_aconi()
int ad_aconi (ISZ_T val)
add ACON ili with specified (integer) constant
Definition at line 1338 of file iliutil.cpp.
References ad1ili(), get_acon(), SPTR_NULL, and val.
Referenced by _exp_smove(), addili(), assign1(), block_str_move(), cmplx_to_mem(), create_ref(), exp_ac(), exp_call(), exp_load(), exp_qjsr(), exp_smp(), exp_store(), exp_type_bound_proc_call(), exp_zqjsr(), get_chain_pointer_closure(), get_sdsc_element(), ll_load_outlined_args(), ll_make_kmpc_critical(), ll_make_kmpc_end_critical(), ll_make_outlined_call(), makeCopyprivArray(), mk_charlen_address(), red_aadd(), ref_threadprivate(), rm_smove(), setTaskloopVars(), and toUplevelAddr().
ad_aconk()
int ad_aconk (INT m32, INT l32)
Add acon ili of an 64-bit constant whose value consists of m32 (most significant 32 bits) and l32 (least significant 32 bits).
Definition at line 1344 of file iliutil.cpp.
References ad1ili(), get_acon(), INT64_2_ISZ, ISZ_T, and SPTR_NULL.
Referenced by addili().
ad_cmpxchg()
int ad_cmpxchg (ILI_OP opc, int ilix_val, int ilix_loc, int nme, int stc_atomic_info, int ilix_comparand, int ilix_is_weak, int ilix_success, int ilix_failure)
...
...
Actually two ilis are created, one for the CMPXCHGx and a CMPXCHG_DST to hold the operands that won't fit.
Parameters
opc an IL_CMPXCHGx opcode
ilix_val ILI expression for value to be stored if operation succeeds
ilix_loc ILI address expression for location to be updated.
nme NME for destination.
stc_atomic_info information packed by routine atomic_encode.
ilix_comparand value to compare against
ilix_is_weak if 1 then operation is allowed to spuriously fail occasionally. Should be 0 otherwise.
ilix_success ILI expression for memory order on success
ilix_failure ILI expression for memory order on failure
Definition at line 14788 of file iliutil.cpp.
Referenced by _exp_mp_atomic_update().
ad_cse()
int ad_cse (int ilix)
add CSE ili of an ili
Definition at line 1362 of file iliutil.cpp.
References ad1ili(), ERR_Severe, FLANG_FALLTHROUGH, IL_RES, ili_get_vect_dtype(), ILI_OPC, ILIA_AR, ILIA_CD, ILIA_CS, ILIA_DP, ILIA_FLOAT128, ILIA_IR, ILIA_KR, ILIA_LNK, ILIA_QP, ILIA_SP, and interr().
Referenced by _exp_mp_atomic_update(), check_ilm(), and exp_store().
ad_free()
int ad_free (int ilix)
Add a IL_FREEx with given operand.
Definition at line 1467 of file iliutil.cpp.
References ad1ili(), ERR_Fatal, IL_RES, ILI_OPC, ILIA_AR, ILIA_CD, ILIA_CS, ILIA_DP, ILIA_FLOAT128, ILIA_IR, ILIA_KR, ILIA_SP, interr(), and r.
Referenced by addother(), and exp_estmt().
ad_icon()
int ad_icon (INT val)
add ICON ili with specified constant value
Definition at line 1309 of file iliutil.cpp.
References ad1ili(), DT_INT, getcon(), and val.
Referenced by addarth(), addbran(), addili(), red_damv(), and red_iadd().
ad_kcon()
int ad_kcon (INT m32, INT l32)
Add KCON ili of an 64-bit constant whose value consists of m32 (most significant 32 bits) and l32 (least significant 32 bits).
Definition at line 1317 of file iliutil.cpp.
References ad1ili(), and getcon().
Referenced by addarth(), addbran(), block_str_move(), exp_alloca(), kanji_bytes(), kanji_divide(), ld_sptr(), reciprocal_division(), reciprocal_division_64(), and reciprocal_mod_64().
ad_kconi()
int ad_kconi (ISZ_T v)
Add kcon ili of an 64-bit constant.
Definition at line 1327 of file iliutil.cpp.
References ad1ili(), getcon(), ISZ_2_INT64, num, and s.
Referenced by addili(), compute_sdsc_subscr(), create_array_subscr(), create_sdsc_subscr(), exp_alloca(), exp_fstring(), exp_load(), exp_misc(), exp_smp(), gen_abs_expr(), gen_base_addr_operand(), gen_binary_expr(), gen_llvm_expr(), ll_make_kmpc_copyprivate(), and red_damv().
ad_load()
int ad_load (int stx)
Given a store ILI, generate the equivalent load ILI.
Definition at line 1412 of file iliutil.cpp.
References ad2ili(), ad3ili(), base, ILI_OPC, ILI_OPND, load, MSZ_F16, MSZ_F32, MSZ_F4, MSZ_F8, and MSZ_I8.
Referenced by check_ilm().
addcallarg()
void addcallarg (int ili, int nme, int dtype)
...
Definition at line 14020 of file iliutil.cpp.
Referenced by create_atomic_seq().
addili()
int addili (ILI * ilip)
...
...
Definition at line 187 of file iliutil.cpp.
References ACONOFFG, ad1ili(), ad2ili(), ad_aconi(), ad_aconk(), ad_icon(), ad_kconi(), addarth(), addbran(), addother(), assert, BIH_QJSR, CONVAL2G, EXP::curbih, DBGBIT, dump_ili(), ERR_Fatal, ERR_Severe, expb, gbl, get_ili(), getcon(), IL_IADD, IL_ISUB, IL_TYPE, ILI_OPC, ILI_OPND, iltb, ILTY_ARTH, ILTY_BRANCH, ILTY_CONS, ILTY_DEFINE, ILTY_LOAD, ILTY_MOVE, ILTY_OTHER, ILTY_PLOAD, ILTY_PROC, ILTY_PSTORE, ILTY_STORE, interr(), ISZ_2_INT64, new_ili(), ILI::opc, ILI::opnd, EXP::qjsr_flag, ILTB::qjsrfg, safe_qjsr, share_proc_ili, share_qjsr_ili, tmp, verify_ili(), and VERIFY_ILI_SHALLOW.
Referenced by ad1ili(), ad2ili(), ad3ili(), ad4ili(), ad5ili(), compl_br(), exp_mac(), update_ili_operand(), and visit_ili_operands().
alt_qjsr()
int alt_qjsr (int ilix)
...
Definition at line 12813 of file iliutil.cpp.
atomic_decode()
ATOMIC_INFO atomic_decode (int encoding)
...
Decode ATOMIC_INFO from an int that was created with atomic_encode or atomic_encode_rmw.
Definition at line 14689 of file iliutil.cpp.
atomic_encode()
int atomic_encode (MSZ msz, SYNC_SCOPE scope, ATOMIC_ORIGIN origin)
...
Encode the given information into an int that can be used as the operand for a ATOMICLDx, ATOMICSTx, or CMPXCHGx.
Definition at line 14668 of file iliutil.cpp.
Referenced by _exp_mp_atomic_update(), exp_mp_atomic_read(), exp_mp_atomic_write(), and get_complex_update_operand().
atomic_encode_rmw()
int atomic_encode_rmw (MSZ msz, SYNC_SCOPE scope, ATOMIC_ORIGIN origin, ATOMIC_RMW_OP op)
...
Encode atomic info for an ATOMICRMW instruction.
Definition at line 14675 of file iliutil.cpp.
Referenced by exp_mp_atomic_capture(), and exp_mp_atomic_update().
atomic_info()
ATOMIC_INFO atomic_info (int ilix)
...
Get ATOMIC_INFO associated with a given ILI instruction
Definition at line 14737 of file iliutil.cpp.
Referenced by gen_llvm_atomicrmw_expr(), gen_llvm_cmpxchg(), and ll_instr_flags_for_memory_order_and_scope().
atomic_info_index()
int atomic_info_index (ILI_OP opc)
...
Get index of ATOMIC_INFO operand for a given ILI instruction.
Definition at line 14703 of file iliutil.cpp.
cc_includes_equality()
bool cc_includes_equality (CC_RELATION cc)
...
Definition at line 14393 of file iliutil.cpp.
ccs_are_complementary()
bool ccs_are_complementary (CC_RELATION cc1, CC_RELATION cc2)
...
Definition at line 14419 of file iliutil.cpp.
choose_multiplier()
void choose_multiplier (int N, unsigned dd, int prec)
...
Definition at line 1796 of file iliutil.cpp.
References add64(), cmp64(), d, div64(), lg(), mrecip, mul64(), shf64(), shpost, sub64(), twon, and twonm1.
Referenced by reciprocal_division().
choose_multiplier_64()
void choose_multiplier_64 (int N, DBLUINT64 dd, int prec)
...
Definition at line 1849 of file iliutil.cpp.
References add128(), cmp128(), d, div128(), lg64(), mrecip_128, mul128l(), shf128(), shpost, sub128(), twon_128, and twonm1_128.
Referenced by reciprocal_division_64().
cmpxchg_is_weak()
bool cmpxchg_is_weak (int ilix)
...
For a IL_CMPXCHGx operation, return true if it is allowed to spuriously fail occcasionally. Returns false when in doubt.
Definition at line 14815 of file iliutil.cpp.
Referenced by gen_llvm_cmpxchg().
cmpxchg_loc()
int cmpxchg_loc (int ilix)
...
For an IL_CMPXCHGx instruction, return address expression of location.
Definition at line 14823 of file iliutil.cpp.
Referenced by gen_llvm_cmpxchg().
cmpxchg_memory_order()
CMPXCHG_MEMORY_ORDER cmpxchg_memory_order (int ilix)
...
For an IL_CMPXCHGx instruction, return memory orders for success and failure cases.
Definition at line 14862 of file iliutil.cpp.
Referenced by gen_llvm_cmpxchg().
combine_ieee_ccs()
CC_RELATION combine_ieee_ccs (CC_RELATION binary_cc, CC_RELATION zero_cc)
...
Definition at line 14354 of file iliutil.cpp.
Referenced by addbran().
combine_int_ccs()
CC_RELATION combine_int_ccs (CC_RELATION binary_cc, CC_RELATION zero_cc)
...
Definition at line 14320 of file iliutil.cpp.
Referenced by addbran().
commute_cc()
CC_RELATION commute_cc (CC_RELATION cc)
...
Definition at line 14286 of file iliutil.cpp.
Referenced by addarth(), and addbran().
compl_br()
int compl_br (int ilix, int lbl)
...
...
This routine adds a branch ili whose condition is the complement of the condition specified by the ili ilix. lbl is the target of the branch. The complement is defined by the following: (Z, NZ), (LT, GE), LE, GT)
Definition at line 9337 of file iliutil.cpp.
References addili(), CC_ILI_OPND, complement_ieee_cc(), complement_int_cc(), i, ILI_OPC, ILI_OPND, ilis, is_floating_comparison_opcode(), ILI::opc, ILI::opnd, and ILIINFO::oprs.
Referenced by chk_block(), and exp_label().
complement_ieee_cc()
CC_RELATION complement_ieee_cc (CC_RELATION cc)
...
Definition at line 14249 of file iliutil.cpp.
Referenced by compl_br().
complement_int_cc()
CC_RELATION complement_int_cc (CC_RELATION cc)
...
Definition at line 14227 of file iliutil.cpp.
Referenced by compl_br().
compute_address()
int compute_address (SPTR sptr)
...
Definition at line 12709 of file iliutil.cpp.
Referenced by genload().
ddilitree()
void ddilitree (int i, int flag)
...
Definition at line 12398 of file iliutil.cpp.
Referenced by dump_ilt().
dmpili()
void dmpili (void)
...
...
Definition at line 11258 of file iliutil.cpp.
Referenced by expand(), and schedule().
dmpilitree()
void dmpilitree (int i)
...
Definition at line 12385 of file iliutil.cpp.
Referenced by dump_ilt().
dump_atomic_info()
void dump_atomic_info (FILE * f, ATOMIC_INFO info)
...
Definition at line 10852 of file iliutil.cpp.
dump_ili()
void dump_ili (FILE * f, int i)
...
Definition at line 10865 of file iliutil.cpp.
Referenced by addili().
dump_msz()
const char * dump_msz (MSZ ms)
...
Definition at line 10765 of file iliutil.cpp.
fast_math()
char * fast_math (const char * root, int widthc, int typec, const char * oldname)
...
Definition at line 1096 of file iliutil.cpp.
References FEATURE_FMA4, FEATURE_SSE3, MACH_AMD_BULLDOZER, MACH_AMD_GH, MACH_INTEL_SANDYBRIDGE, root, TEST_FEATURE, TEST_MACH, and XBIT.
Referenced by addarth(), relaxed_math(), and vect_math().
find_ili()
bool find_ili (int tree, int it)
...
...
Definition at line 9870 of file iliutil.cpp.
Referenced by exp_mp_atomic_capture(), get_complex_update_operand(), get_simple_update_operand(), and load_op_match_lhs().
func_in()
bool func_in (int ilix)
...
...
Definition at line 9781 of file iliutil.cpp.
Referenced by addarth(), addbran(), addother(), and simple_ili().
garbage_collect()
void garbage_collect (void(*)(int) mark_function)
...
Definition at line 9612 of file iliutil.cpp.
gencallargs()
int gencallargs (void)
...
Definition at line 14031 of file iliutil.cpp.
Referenced by create_atomic_seq().
genregcallargs()
int genregcallargs (void)
...
genretvalue()
int genretvalue (int ilix, ILI_OP resultopc)
...
Definition at line 14052 of file iliutil.cpp.
Referenced by _make_mp_get_threadprivate(), and ll_ad_outlined_func2().
get_ili_ns()
int get_ili_ns (ILI * ilip)
...
Definition at line 9527 of file iliutil.cpp.
Referenced by update_ili_operand(), and visit_ili_operands().
get_isz_conili()
ISZ_T get_isz_conili (int ili)
...
Definition at line 13253 of file iliutil.cpp.
get_rewr_new_nme()
int get_rewr_new_nme (int nmex)
...
Definition at line 9985 of file iliutil.cpp.
gnr_math()
char * gnr_math (const char * root, int widthc, int typec, const char * oldname, int masked)
...
Definition at line 926 of file iliutil.cpp.
References root.
Referenced by addarth(), and vect_math().
has_cse()
int has_cse (int ilix)
...
Definition at line 13589 of file iliutil.cpp.
Referenced by visit_ilis().
iadd_const_ili()
int iadd_const_ili (ISZ_T valconst, int valilix)
...
Definition at line 15034 of file iliutil.cpp.
iadd_ili_ili()
int iadd_ili_ili (int leftx, int rightx)
...
Definition at line 15068 of file iliutil.cpp.
idiv_ili_const()
int idiv_ili_const (int valilix, ISZ_T valconst)
...
Definition at line 15193 of file iliutil.cpp.
idiv_ili_ili()
int idiv_ili_ili (int leftx, int rightx)
...
Definition at line 15213 of file iliutil.cpp.
ikmove()
int ikmove (int ilix)
...
Definition at line 14185 of file iliutil.cpp.
Referenced by compute_sdsc_subscr(), create_array_ref(), create_array_subscr(), create_sdsc_subscr(), exp_alloca(), finish_array(), forceK(), inlarr(), ll_make_atomic_compare_xchg(), ll_make_atomic_load(), ll_make_atomic_store(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), and ll_make_kmpc_for_static_init().
ili_cleanup()
void ili_cleanup (void)
...
Definition at line 178 of file iliutil.cpp.
References ilib, and STG_DELETE.
ili_get_vect_arg_count()
int ili_get_vect_arg_count (int ilix)
...
...
Definition at line 12914 of file iliutil.cpp.
Referenced by cleanup_unneeded_sincos_calls(), and gen_llvm_vsincos_call().
ili_get_vect_dtype()
DTYPE ili_get_vect_dtype (int ilix)
...
Definition at line 12991 of file iliutil.cpp.
Referenced by _assn_rtemp(), ad_cse(), addarth(), exp_store(), gen_binary_expr(), gen_binary_vexpr(), gen_llvm_expr(), gen_llvm_vsincos_call(), gen_minmax_expr(), gen_vect_compare_operand(), have_masked_intrinsic(), make_stmt(), select_rtemp(), and vect_llvm_intrinsic_name().
ili_init()
void ili_init (void)
...
...
Definition at line 153 of file iliutil.cpp.
References ad1ili(), cnt, ilhsh, ILHSHSZ, ilib, ILTABSZ, p, STG_ALLOC, and STG_SET_FREELINK.
Referenced by ds_init().
ili_isdeleted()
int ili_isdeleted (int ili)
...
Definition at line 13995 of file iliutil.cpp.
Referenced by build_sym_nme().
ili_opnd()
int ili_opnd (int ilix, int n)
return nth operand of ili - skipping past CSE ili if present
Definition at line 1508 of file iliutil.cpp.
References ILI_OPC, ILI_OPND, and n.
Referenced by exp_call(), and find_load_cse().
ili_subscript()
int ili_subscript (int sub)
...
Definition at line 13981 of file iliutil.cpp.
Referenced by add_arrnme().
ili_throw_label()
int ili_throw_label (int ilix)
...
Definition at line 14493 of file iliutil.cpp.
Referenced by dump_ilt(), gen_call_expr(), and verify_ilt().
ili_traverse()
int ili_traverse (int(*)(int) visit_f, int ilix)
...
...
The traversal routine sets the ILI_VISIT & ILI_VLIST fields.
Definition at line 12731 of file iliutil.cpp.
ili_unvisit()
void ili_unvisit (void)
...
...
Definition at line 12756 of file iliutil.cpp.
Referenced by get_complex_update_operand(), and load_op_match_lhs().
ili_visit()
void ili_visit (int ilix, int v)
...
...
Definition at line 12744 of file iliutil.cpp.
ilstckind()
int ilstckind (ILI_OP opc, int opnum)
...
Definition at line 14088 of file iliutil.cpp.
Referenced by putstc().
imax_ili_ili()
int imax_ili_ili (int leftx, int rightx)
...
Definition at line 15227 of file iliutil.cpp.
imin_ili_ili()
int imin_ili_ili (int leftx, int rightx)
...
Definition at line 15241 of file iliutil.cpp.
imul_const_ili()
int imul_const_ili (ISZ_T valconst, int valilix)
...
Definition at line 14999 of file iliutil.cpp.
imul_ili_ili()
int imul_ili_ili (int leftx, int rightx)
...
Definition at line 15019 of file iliutil.cpp.
initcallargs()
void initcallargs (int count)
...
Definition at line 14010 of file iliutil.cpp.
Referenced by create_atomic_seq().
inline_mulh()
void inline_mulh (void)
...
is_argili_opcode()
int is_argili_opcode (ILI_OP opc)
...
Definition at line 13321 of file iliutil.cpp.
Referenced by gen_va_end(), and gen_va_start().
is_cseili_opcode()
int is_cseili_opcode (ILI_OP opc)
...
Definition at line 13344 of file iliutil.cpp.
Referenced by build_csed_list(), cancel_store(), collect_tree_ilis(), eval_ilm_argument1(), remove_from_csed_list(), scan_ili_tree(), and visit_ili_operands().
is_daili_opcode()
int is_daili_opcode (ILI_OP opc)
...
Definition at line 13431 of file iliutil.cpp.
Referenced by jsrAddArg().
is_dfrili_opcode()
int is_dfrili_opcode (ILI_OP opc)
...
Definition at line 13458 of file iliutil.cpp.
is_floating_comparison_opcode()
bool is_floating_comparison_opcode (ILI_OP opc)
...
Definition at line 13524 of file iliutil.cpp.
Referenced by compl_br().
is_freeili_opcode()
int is_freeili_opcode (ILI_OP opc)
...
Definition at line 13368 of file iliutil.cpp.
Referenced by check_ilm(), and schedule().
is_integer_comparison_opcode()
bool is_integer_comparison_opcode (ILI_OP opc)
...
Definition at line 13485 of file iliutil.cpp.
is_llvm_local()
bool is_llvm_local (int sptr, int funcsptr)
...
Definition at line 12468 of file iliutil.cpp.
is_llvm_local_private()
bool is_llvm_local_private (int sptr)
...
Definition at line 12452 of file iliutil.cpp.
Referenced by compute_sdsc_subscr(), create_sdsc_subscr(), llmp_task_get_private(), load_uplevel_addresses(), loadUplevelArgsForRegion(), and update_local_nme().
is_mvili_opcode()
int is_mvili_opcode (ILI_OP opc)
...
Definition at line 13390 of file iliutil.cpp.
Referenced by schedule().
is_omp_atomic_ld()
bool is_omp_atomic_ld (int ilix)
...
Definition at line 14931 of file iliutil.cpp.
Referenced by make_load().
is_omp_atomic_st()
bool is_omp_atomic_st (int ilix)
...
Definition at line 14952 of file iliutil.cpp.
is_rgdfili_opcode()
int is_rgdfili_opcode (ILI_OP opc)
...
Definition at line 13415 of file iliutil.cpp.
Referenced by schedule().
is_unsigned_opcode()
bool is_unsigned_opcode (ILI_OP opc)
...
Definition at line 13551 of file iliutil.cpp.
isub_ili_ili()
int isub_ili_ili (int leftx, int rightx)
...
Definition at line 15115 of file iliutil.cpp.
jsrsearch()
int jsrsearch (int ilix)
...
...
Definition at line 12806 of file iliutil.cpp.
kimove()
int kimove (int ilix)
...
Definition at line 14213 of file iliutil.cpp.
Referenced by compute_sdsc_subscr(), create_array_ref(), exp_ac(), exp_agoto(), exp_array(), exp_get_sdsc_len(), finish_array(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), and setTaskloopVars().
ldopc_from_stopc()
ILI_OP ldopc_from_stopc (ILI_OP stopc)
...
...
Definition at line 1521 of file iliutil.cpp.
ldst_msz()
void ldst_msz (DTYPE dtype, ILI_OP * ld, ILI_OP * st, MSZ * siz)
...
Definition at line 1570 of file iliutil.cpp.
References DTY, DTyAlgTySize, ld, MSZ_BYTE, MSZ_DFLWORD, MSZ_F16, MSZ_F4, MSZ_F8, MSZ_FWORD, MSZ_I8, MSZ_PTR, MSZ_SBYTE, MSZ_SHWORD, MSZ_WORD, st, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, and TY_SLOG.
Referenced by _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_mp_atomic_write(), exp_mp_atomic_capture(), exp_mp_atomic_read(), exp_mp_atomic_update(), exp_smp(), get_complex_update_operand(), and setTaskloopVars().
ll_ad_outlined_func()
int ll_ad_outlined_func (ILI_OP result_opc, ILI_OP call_opc, char * func_name, int narg, int arg1, int arg2, int arg3)
...
Definition at line 14453 of file iliutil.cpp.
Referenced by ll_make_outlined_call().
llmk_math_name()
void llmk_math_name (char * buff, int fn, int vectlen, bool mask, DTYPE res_dt)
...
...
Parameters
buff (output), must be preallocated, should have a size > 32
Definition at line 14568 of file iliutil.cpp.
Referenced by cleanup_unneeded_sincos_calls(), gen_llvm_sincos_call(), and gen_llvm_vsincos_call().
make_math()
char * make_math (MTH_FN fn, SPTR * fptr, int vectlen, bool mask, DTYPE res_dt, int nargs, int arg1_dt_, ...)
...
Definition at line 14619 of file iliutil.cpp.
Referenced by ad1mathfunc_cmplx(), ad2mathfunc_cmplx(), addarth(), and gen_sincos().
make_math_name()
char * make_math_name (MTH_FN fn, int vectlen, bool mask, DTYPE res_dt)
...
Definition at line 14578 of file iliutil.cpp.
Referenced by vect_math().
make_math_name_vabi()
char * make_math_name_vabi (MTH_FN fn, int vectlen, bool mask, DTYPE res_dt)
...
Definition at line 14602 of file iliutil.cpp.
mem_size()
MSZ mem_size (TY_KIND ty)
...
...
Result is the memory reference size, not including padding. For example, TY_X87 on x86 targets maps to F10.
The logic is custom to each target.
Definition at line 13082 of file iliutil.cpp.
Referenced by exp_mp_atomic_capture(), exp_mp_atomic_update(), exp_mp_atomic_write(), ld_sptr(), and process_formal_arguments().
memory_order()
MEMORY_ORDER memory_order (int ilix)
...
Get MEMORY_ORDER associated with given ILI instruction. If the memory order operand is not a constant, require a conservative bound. If there are different memory orders for success/failure, return an upper bound.
For IL_CMPXCHGx instructions, the memory order is always the "success" order, since the "failure" order is not allowed to be stronger.
The "failure" order cannot be stronger than the "success" order, so return the success order.
Definition at line 14887 of file iliutil.cpp.
Referenced by ll_instr_flags_for_memory_order_and_scope().
mk_address()
int mk_address (SPTR sptr)
...
...
Definition at line 12651 of file iliutil.cpp.
Referenced by _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_mp_atomic_write(), add_ptr_subscript(), addCopyinInplace(), begin_entry(), charaddr(), charlen(), cloneUplevel(), compute_sdsc_subscr(), create_ref(), create_sdsc_subscr(), exp_call(), exp_header(), exp_load(), exp_misc(), exp_mp_atomic_capture(), exp_mp_atomic_update(), exp_smp(), exp_type_bound_proc_call(), get_chain_pointer_closure(), get_complex_update_operand(), get_sdsc_element(), ld_sptr(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), ll_make_outlined_call2(), llLoadGtid(), llvmAddConcurEntryBlk(), load_uplevel_addresses(), loadCharLen(), loadUplevelArgsForRegion(), makeCopyprivArray(), makeCopyprivArray_tls(), and setTaskloopVars().
mk_charlen_parref_sptr()
int mk_charlen_parref_sptr (SPTR sptr)
...
Definition at line 12631 of file iliutil.cpp.
Referenced by charlen().
mkfunc_avx()
int mkfunc_avx (char * nmptr, int avxp)
...
Definition at line 13800 of file iliutil.cpp.
prilitree()
void prilitree (int i)
...
Definition at line 11404 of file iliutil.cpp.
qjsr_in()
bool qjsr_in (int ilix)
...
...
This routine is used instead of ili_traverse of qjrsearch when the visit_list is already being used (ili_traverse needs the visit_list).
Definition at line 9804 of file iliutil.cpp.
Referenced by check_ilm().
qjsrsearch()
int qjsrsearch (int ilix)
...
...
Definition at line 12875 of file iliutil.cpp.
relaxed_math()
char * relaxed_math (const char * root, int widthc, int typec, const char * oldname)
...
...
Definition at line 1173 of file iliutil.cpp.
References fast_math(), FEATURE_FMA4, FEATURE_SIMD128, MACH_AMD_BULLDOZER, MACH_INTEL_SANDYBRIDGE, root, TEST_FEATURE, TEST_MACH, and XBIT_NEW_RELAXEDMATH.
Referenced by addarth(), exp_ac(), and vect_math().
restore_rewr_count()
void restore_rewr_count (int c)
...
Definition at line 10005 of file iliutil.cpp.
rewr_cln_ili()
void rewr_cln_ili (void)
...
Definition at line 10478 of file iliutil.cpp.
Referenced by exp_mp_atomic_capture(), and get_complex_update_operand().
rewr_ili()
int rewr_ili (int tree, int old, int New)
...
Definition at line 10016 of file iliutil.cpp.
Referenced by exp_mp_atomic_capture(), and get_complex_update_operand().
rewr_ili_nme()
int rewr_ili_nme (int tree, int oldili, int newili, int oldnme, int newnme, int douse, int dodef)
...
Rewrites the ili tree 'tree', changing 'oldili' into 'newili' and the nme 'oldnme' into 'newnme'; saves 'tree' in 'rewrb'.
Must be followed by a call to rewr_cln_ili.
Definition at line 10067 of file iliutil.cpp.
rewr_these_ili()
void rewr_these_ili (int oldili, int newili)
...
Definition at line 9943 of file iliutil.cpp.
rewr_these_ili_nme()
void rewr_these_ili_nme (int oldili, int newili, int oldnme, int newnme)
...
Definition at line 9964 of file iliutil.cpp.
save_rewr_count()
int save_rewr_count (void)
...
Definition at line 9999 of file iliutil.cpp.
scond()
const char * scond (int c)
...
Definition at line 14168 of file iliutil.cpp.
Referenced by putstc().
sel_aconv()
int sel_aconv (int ili)
...
...
Definition at line 13307 of file iliutil.cpp.
sel_decr()
int sel_decr (int ili, int isi8)
...
...
Definition at line 13297 of file iliutil.cpp.
sel_icnst()
int sel_icnst (ISZ_T val, int isi8)
...
...
Definition at line 13270 of file iliutil.cpp.
Referenced by create_array_subscr(), and inlarr().
sel_iconv()
int sel_iconv (int ili, int isi8)
...
...
Definition at line 13281 of file iliutil.cpp.
Referenced by _make_mp_get_threadprivate(), addCopyinInplace(), arg_ir(), arg_kr(), exp_call(), exp_fstring(), exp_smp(), inlarr(), loadUplevelArgsForRegion(), and makeCopyprivArray_tls().
simplified_cmp_ili()
int simplified_cmp_ili (int cmp_ili)
...
...
Parameters
cmp_ili Comparison ILI
simplify following eight cases:
(1)
         X = IL_xxCMP A, B, cmp_op
         Y = IL_ICMP X, 1, eq
     =>
         Y = IL_xxCMP A, B, cmp_op
(2)
         X = IL_xxCMPZ A, cmp_op
         Y = IL_ICMP X, 1, eq
     =>
         Y = IL_xxCMPZ A, cmp_op
(3)
         X = IL_xxCMP A, B, cmp_op
         Y = IL_ICMP X, 1, ne
     =>
         Y = IL_xxCMP A, B, ~cmp_op
(4)
         X = IL_xxCMPZ A, cmp_op
         Y = IL_ICMP X, 1, ne
     =>
         Y = IL_xxCMPZ A, ~cmp_op
(5)
         X = IL_xxCMP A, B, cmp_op
         Y = IL_ICMPZ X, eq
     =>
         Y = IL_xxCMP A, B, ~cmp_op
(6)
         X = IL_xxCMPZ A, cmp_op
         Y = IL_ICMPZ X, eq
     =>
         Y = IL_xxCMPZ A, ~cmp_op
(7)
         X = IL_xxCMP A, B, cmp_op
         Y = IL_ICMPZ X, ne
     =>
         Y = IL_xxCMP A, B, cmp_op
(8)
         X = IL_xxCMPZ A, cmp_op
         Y = IL_ICMPZ X, ne
     =>
         Y = IL_xxCMPZ A, cmp_op
This algorithm is applied recursively to simplify chains of comparison to one and zero
Definition at line 10665 of file iliutil.cpp.
uikmove()
int uikmove (int ilix)
...
Definition at line 14199 of file iliutil.cpp.
Variable Documentation
share_proc_ili
bool share_proc_ili extern
Definition at line 65 of file iliutil.cpp.
Referenced by addili().
share_qjsr_ili
bool share_qjsr_ili extern
Definition at line 66 of file iliutil.cpp.
Referenced by addili().