flang: ilmutil.cpp File Reference
ilmutil.cpp File Reference
#include "ilmutil.h"
#include "error.h"
#include "ilmtp.h"
#include "ilm.h"
#include "fih.h"
#include "semant.h"
#include "pragma.h"
#include "outliner.h"
#include "symfun.h"
#include "mp.h"
Macros
#define GILMSAVE 2
#define TY(n) ((int)(n & 0x03))
#define ILMNAME(opc) ((opc) > 0 && (opc) < N_ILM ? ilms[opc].name : "???")
#define SPECIALOPC 65000
Functions
void addlabel (int sptr)
...
int ad1ilm (int opc)
...
int ad2ilm (int opc, int opr1)
...
int ad3ilm (int opc, int opr1, int opr2)
...
int ad4ilm (int opc, int opr1, int opr2, int opr3)
...
int ad5ilm (int opc, int opr1, int opr2, int opr3, int opr4)
...
int adNilm (int n, int opc,...)
...
int ilm_callee_index (ILM_OP opc)
FIXME.
SYMTYPE ilm_symtype_of_return_slot (DTYPE ret_type)
int ilm_return_slot_index (ILM_T *ilmp)
Determine if the ILM performs a call and the call has a pointer to a return slot. If so, return the operand index of the slot. Otherwise return 0. Returns 0 for non-call ILMs.
void init_ilm (int ilmsize)
...
void init_global_ilm_mode ()
...
void reset_global_ilm_position ()
...
void init_global_ilm_position ()
...
void init_next_gilm ()
...
void swap_next_gilm ()
...
void gwrilms (int nilms)
...
void fini_next_gilm ()
...
void fini_ilm ()
...
void wrilms (int linenum)
...
ILM_T * save_ilms (int area)
...
ILM_T * save_ilms0 (void *area)
...
void add_ilms (ILM_T *p)
...
void reloc_ilms (ILM_T *p)
...
void mkbranch (int ilmptr, int truelb, int flag)
...
int _dumponeilm (ILM_T *ilm_base, int i, int check)
...
void _dumpilms (ILM_T *ilm_base, int check)
...
void dumpilms ()
...
void dmpilms ()
...
static void putsym (int sptr)
static void put_dtype (DTYPE dtype)
Write a DTYPE to xfile. This routine is spelled with an underscore to distinguish it from routine putdtype in mwd.c.
void dumpsingleilm (ILM_T *ilm_base, int i)
...
static void _dumpilmtree (int i, int indent)
void dumpilmtree (int ilmptr)
...
void dumpilmtrees ()
...
void rewindilms ()
...
long get_ilmpos ()
...
long get_ilmstart ()
...
void set_ilmpos (long pos)
...
void set_ilmstart (int start)
...
int get_entry ()
...
int rdgilms (int mode)
...
void SaveGilms (FILE *fil)
...
void RestoreGilms (FILE *fil)
...
void set_gilmb_mode (int mode)
...
int rdilms ()
...
void restartilms (void)
...
int count_ilms ()
...
Variables
ILMB ilmb
GILMB gilmb = {0, 0, 0, 0, 0, 0, 0, 0}
GILMB next_gilmb = {0, 0, 0, 0, 0, 0, 0, 0}
int ilmpos = 0
ILM_T * ilm_base
static int gilmb_mode = 0
static const char * nullname = ""
static int globfile = 0
static int globindex = 0
static int xsize
static int xavl
static int * x
static FILE * xfile
static long gilmpos = 0
static int saveilmstart = 0
static int saveilmcount = 0
Macro Definition Documentation
GILMSAVE
#define GILMSAVE 2
Definition at line 47 of file ilmutil.cpp.
ILMNAME
#define ILMNAME (opc) ((opc) > 0 && (opc) < N_ILM ? ilms[opc].name : "???")
Definition at line 66 of file ilmutil.cpp.
SPECIALOPC
#define SPECIALOPC 65000
TY
#define TY (n) ((int)(n & 0x03))
Definition at line 53 of file ilmutil.cpp.
Function Documentation
_dumpilms()
void _dumpilms (ILM_T * ilm_base, int check)
...
Definition at line 1372 of file ilmutil.cpp.
References _dumponeilm(), BOS_SIZE, check(), DEBUG, gbl, ILMB::globalilmcount, ILMB::globalilmstart, globfile, globindex, i, ilm_base, ilmb, and NULL.
Referenced by dmpilms(), and dumpilms().
_dumpilmtree()
static void _dumpilmtree (int i, int indent) static
Definition at line 1612 of file ilmutil.cpp.
References _dumpilmtree(), args, getprint(), i, ILMA, ilms, indent, j, name, OPR_LNK, OPR_N, OPR_STC, OPR_SYM, ILMINFO::oprflag, ILMINFO::oprs, put_dtype(), TY, val, and xfile.
Referenced by _dumpilmtree(), dumpilmtree(), and dumpilmtrees().
_dumponeilm()
int _dumponeilm (ILM_T * ilm_base, int i, int check)
...
Definition at line 824 of file ilmutil.cpp.
References BOS_SIZE, check(), DBGBIT, gbl, getprint(), globfile, globindex, i, ilm_base, ilms, j, k, MP_CMB_DISTRIBUTE, MP_CMB_FOR, MP_CMB_PARALLEL, MP_CMB_SIMD, MP_CMB_TEAMS, MP_TGT_DEPEND_IN, MP_TGT_DEPEND_OUT, MP_TGT_IFPAR, MP_TGT_IFTARGET, MP_TGT_NOWAIT, ILMINFO::name, OPR_LNK, OPR_N, OPR_STC, OPR_SYM, ILMINFO::oprflag, ILMINFO::oprs, PR_ACCASYNC, PR_ACCATTACH, PR_ACCAUTO, PR_ACCBEGINDIR, PR_ACCCACHE, PR_ACCCACHEARG, PR_ACCCACHEDIR, PR_ACCCACHEREADONLY, PR_ACCCOLLAPSE, PR_ACCCOMPARE, PR_ACCCOPY, PR_ACCCOPYIN, PR_ACCCOPYOUT, PR_ACCCREATE, PR_ACCCUDACALL, PR_ACCDATAREG, PR_ACCDEFNONE, PR_ACCDEFPRESENT, PR_ACCDELETE, PR_ACCDETACH, PR_ACCDEVICEID, PR_ACCDEVICEPTR, PR_ACCDEVICERES, PR_ACCDEVSYM, PR_ACCEL, PR_ACCELLP, PR_ACCENDDATAREG, PR_ACCENDHOSTDATA, PR_ACCENDIMPDATAREG, PR_ACCENDKERNELS, PR_ACCENDPARCONSTRUCT, PR_ACCENDSCALARREG, PR_ACCENDSERIAL, PR_ACCENTERDATA, PR_ACCEXITDATA, PR_ACCFINALEXITDATA, PR_ACCFIRSTPRIVATE, PR_ACCFORCECOLLAPSE, PR_ACCGANG, PR_ACCGANGCHUNK, PR_ACCGANGDIM, PR_ACCHOST, PR_ACCHOSTDATA, PR_ACCIF, PR_ACCIMPDATAREG, PR_ACCIMPDATAREGX, PR_ACCINDEPENDENT, PR_ACCKERNEL, PR_ACCKERNELS, PR_ACCKLOOP, PR_ACCLINK, PR_ACCLOCAL, PR_ACCLOOPPRIVATE, PR_ACCMIRROR, PR_ACCNO_CREATE, PR_ACCNOWAIT, PR_ACCNUMGANGS, PR_ACCNUMGANGS2, PR_ACCNUMGANGS3, PR_ACCNUMWORKERS, PR_ACCPARALLEL, PR_ACCPARCONSTRUCT, PR_ACCPARUNROLL, PR_ACCPCOPY, PR_ACCPCOPYIN, PR_ACCPCOPYOUT, PR_ACCPCREATE, PR_ACCPDELETE, PR_ACCPLOOP, PR_ACCPNOT, PR_ACCPRESENT, PR_ACCPRIVATE, PR_ACCREDUCTION, PR_ACCREDUCTOP, PR_ACCREFLECT, PR_ACCSCALARREG, PR_ACCSEQ, PR_ACCSEQUNROLL, PR_ACCSERIAL, PR_ACCSHORTLOOP, PR_ACCSLOOP, PR_ACCTILE, PR_ACCTKLOOP, PR_ACCTPLOOP, PR_ACCTSLOOP, PR_ACCUNROLL, PR_ACCUPDATE, PR_ACCUPDATEDEVICE, PR_ACCUPDATEDEVICEIFP, PR_ACCUPDATEHOST, PR_ACCUPDATEHOSTIFP, PR_ACCUPDATESELF, PR_ACCUPDATESELFIFP, PR_ACCUSEDEVICE, PR_ACCUSEDEVICEIFP, PR_ACCVECTOR, PR_ACCVECUNROLL, PR_ACCVLENGTH, PR_ACCWAIT, PR_ACCWAITARG, PR_ACCWAITDIR, PR_ACCWORKER, PR_ALWAYSINLINE, PR_CUFLOOPPRIVATE, PR_ENDACCEL, PR_ENDKERNEL, PR_INLINEALIGN, PR_INLINEAS, PR_INLINEONLY, PR_INLINETYPE, PR_INLININGOFF, PR_INLININGON, PR_KERNEL, PR_KERNEL_BLOCK, PR_KERNEL_DEVICE, PR_KERNEL_GRID, PR_KERNEL_NEST, PR_KERNEL_STREAM, PR_KERNELBEGIN, PR_KERNELTILE, PR_MAPALLOC, PR_MAPDELETE, PR_MAPFROM, PR_MAPRELEASE, PR_MAPTO, PR_MAPTOFROM, PR_MAYINLINE, PR_NEVERINLINE, PR_NONE, PR_PCASTCOMPARE, PR_PGICOMPARE, s, SPECIALOPC, TY, and val.
Referenced by _dumpilms(), and expdumpilms().
ad1ilm()
int ad1ilm (int opc)
...
Definition at line 73 of file ilmutil.cpp.
References DBGBIT, gbl, ILMB::ilm_base, ILMB::ilm_size, ILMB::ilmavl, ilmb, ILMNAME, and NEED.
Referenced by read_ilm().
ad2ilm()
int ad2ilm (int opc, int opr1)
...
Definition at line 91 of file ilmutil.cpp.
References DBGBIT, gbl, ILMB::ilm_base, ILMB::ilm_size, ILMB::ilmavl, ilmb, ILMNAME, NEED, and p.
Referenced by addlabel().
ad3ilm()
int ad3ilm (int opc, int opr1, int opr2)
...
Definition at line 114 of file ilmutil.cpp.
References DBGBIT, gbl, ILMB::ilm_base, ILMB::ilm_size, ILMB::ilmavl, ilmb, ILMNAME, NEED, and p.
Referenced by mkbranch().
ad4ilm()
int ad4ilm (int opc, int opr1, int opr2, int opr3)
...
Definition at line 139 of file ilmutil.cpp.
References DBGBIT, gbl, ILMB::ilm_base, ILMB::ilm_size, ILMB::ilmavl, ilmb, ILMNAME, NEED, and p.
ad5ilm()
int ad5ilm (int opc, int opr1, int opr2, int opr3, int opr4)
...
Definition at line 165 of file ilmutil.cpp.
References DBGBIT, gbl, ILMB::ilm_base, ILMB::ilm_size, ILMB::ilmavl, ilmb, ILMNAME, NEED, and p.
add_ilms()
void add_ilms (ILM_T * p)
...
Definition at line 531 of file ilmutil.cpp.
References assert, BCOPY, count, ERR_Fatal, ILMB::ilm_base, ILMB::ilm_size, ILMB::ilmavl, ilmb, NEED, NULL, and p.
addlabel()
void addlabel (int sptr)
...
Definition at line 58 of file ilmutil.cpp.
References ad2ilm(), sptr, and void().
Referenced by insert_begin_scope_label(), and insert_end_scope_label().
adNilm()
int adNilm (int n, int opc, ...)
...
Add 'n' ILM words to current ILM buffer, including the opc.
Definition at line 192 of file ilmutil.cpp.
References assert, DBGBIT, ERR_Fatal, gbl, i, ILMB::ilm_base, ILMB::ilm_size, ILMB::ilmavl, ilmb, ILMNAME, n, NEED, and p.
count_ilms()
int count_ilms (void)
...
Definition at line 2043 of file ilmutil.cpp.
References assert, BOS_SIZE, DEBUG, ERR_Severe, ILMB::ilm_base, ilmb, ilms, IM_NOINLC, IM_null, IM_VAR, len, and ILMINFO::oprs.
dmpilms()
void dmpilms (void)
...
Definition at line 1422 of file ilmutil.cpp.
References _dumpilms(), ILMB::ilm_base, and ilmb.
Referenced by dinit_data(), save_ilms(), save_ilms0(), and wrilms().
dumpilms()
void dumpilms (void)
...
Definition at line 1413 of file ilmutil.cpp.
References _dumpilms(), BOS_SIZE, gbl, ILMB::ilm_base, ILMA, ILMB::ilmavl, ilmb, and NULL.
Referenced by dinit(), expand(), and rdilms().
dumpilmtree()
void dumpilmtree (int ilmptr)
...
Definition at line 1684 of file ilmutil.cpp.
References _dumpilmtree(), FREE, gbl, ILMA, NEW, x, xavl, xfile, and xsize.
dumpilmtrees()
void dumpilmtrees (void)
...
Definition at line 1703 of file ilmutil.cpp.
References _dumpilmtree(), args, FREE, gbl, i, ILMA, ILMB::ilmavl, ilmb, ilms, IM_TRM, NEW, OPR_N, ILMINFO::oprflag, ILMINFO::oprs, TY, x, xavl, xfile, and xsize.
dumpsingleilm()
void dumpsingleilm (ILM_T * ilm_base, int i)
...
Definition at line 1556 of file ilmutil.cpp.
References args, gbl, getprint(), i, ilm_base, ilms, j, ILMINFO::name, OPR_LNK, OPR_N, OPR_STC, OPR_SYM, ILMINFO::oprflag, ILMINFO::oprs, TY, and val.
fini_ilm()
void fini_ilm (void)
...
Definition at line 407 of file ilmutil.cpp.
References FREE, gilmb, gilmb_mode, GILMB::globalilmfirst, GILMB::globalilmtotal, ILMB::ilm_base, GILMB::ilm_base, GILMB::ilm_size, GILMB::ilmavl, ilmb, GILMB::ilmpos, and NULL.
fini_next_gilm()
void fini_next_gilm (void)
...
Definition at line 394 of file ilmutil.cpp.
References FREE, GILMB::ilm_base, GILMB::ilm_size, GILMB::ilmavl, GILMB::ilmpos, next_gilmb, and NULL.
get_entry()
int get_entry (void)
...
Definition at line 1773 of file ilmutil.cpp.
References BOS_SIZE, gilmb, GILMSAVE, and GILMB::ilm_base.
get_ilmpos()
long get_ilmpos (void)
...
Definition at line 1742 of file ilmutil.cpp.
References gilmpos.
get_ilmstart()
long get_ilmstart (void)
...
Definition at line 1748 of file ilmutil.cpp.
References gilmb, ILMB::globalilmcount, GILMB::globalilmfirst, ILMB::globalilmstart, GILMB::globalilmtotal, and ilmb.
gwrilms()
void gwrilms (int nilms)
...
Definition at line 373 of file ilmutil.cpp.
References BCOPY, BOS_SIZE, GILMSAVE, ILMB::globalilmcount, ILMB::globalilmstart, ILMB::ilm_base, GILMB::ilm_base, GILMB::ilm_size, ILMB::ilmavl, GILMB::ilmavl, ilmb, NEED, and next_gilmb.
ilm_callee_index()
int ilm_callee_index (ILM_OP opc)
FIXME.
Returns
index of callee for given operation, which must have type IMTY_PROC. index+k is the index for the kth argument. index-1 is the index of the dtype for the function signature if there is one.
Definition at line 223 of file ilmutil.cpp.
References assert, ERR_Fatal, IM_TYPE, and IMTY_PROC.
Referenced by exp_pure().
ilm_return_slot_index()
int ilm_return_slot_index (ILM_T * ilmp)
Determine if the ILM performs a call and the call has a pointer to a return slot. If so, return the operand index of the slot. Otherwise return 0. Returns 0 for non-call ILMs.
Definition at line 254 of file ilmutil.cpp.
References DEBUG_ASSERT, ERR_Severe, and interr().
Referenced by exp_store().
ilm_symtype_of_return_slot()
SYMTYPE ilm_symtype_of_return_slot (DTYPE ret_type)
Definition at line 240 of file ilmutil.cpp.
References DT_ISCMPLX, and DTY.
init_global_ilm_mode()
void init_global_ilm_mode (void)
...
Definition at line 306 of file ilmutil.cpp.
References gilmb, GILMB::globalilmfirst, GILMB::globalilmtotal, GILMB::ilm_base, ILMB::ilm_size, GILMB::ilm_size, GILMB::ilmavl, ilmb, GILMB::ilmpos, and NEW.
Referenced by main().
init_global_ilm_position()
void init_global_ilm_position (void)
...
Definition at line 327 of file ilmutil.cpp.
References gilmb, ILMB::globalilmcount, GILMB::globalilmcount, ILMB::globalilmstart, GILMB::globalilmstart, and ilmb.
init_ilm()
void init_ilm (int ilmsize)
...
Definition at line 288 of file ilmutil.cpp.
References BOS_SIZE, BZERO, FIH_DIRNAME, FIH_FILENAME, FIH_FULLNAME, fihb, ILMB::ilm_base, ILMB::ilm_size, ILMB::ilmavl, ilmb, NEW, NULL, nullname, FIHB::stg_avail, FIHB::stg_base, and FIHB::stg_size.
init_next_gilm()
void init_next_gilm (void)
...
Definition at line 338 of file ilmutil.cpp.
References gilmb, GILMSAVE, ILMB::globalilmcount, GILMB::globalilmcount, ILMB::globalilmstart, GILMB::globalilmstart, GILMB::ilm_base, GILMB::ilm_size, GILMB::ilmavl, ilmb, GILMB::ilmpos, NEW, and next_gilmb.
mkbranch()
void mkbranch (int ilmptr, int truelb, int flag)
...
Definition at line 631 of file ilmutil.cpp.
References ad3ilm(), getlab(), ILMA, ILMB::ilmavl, ilmb, IS_COMPARE, mkbranch(), and RFCNTI.
Referenced by mkbranch().
put_dtype()
static void put_dtype (DTYPE dtype) static
Write a DTYPE to xfile. This routine is spelled with an underscore to distinguish it from routine putdtype in mwd.c.
Definition at line 1459 of file ilmutil.cpp.
References AD_DPTR, AD_LWBD, AD_NUMDIM, AD_UPBD, DTY, DTyAlgTyMember, DTyAlgTyTag, DTyAlgTyTagNeg, DTyCharLength, DTySeqTyElement, DTySet, i, ISZ_PF, NOSYM, put_dtype(), putsym(), stb, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_SINT, TY_WORD, STB::tynames, and xfile.
Referenced by _dumpilmtree(), and put_dtype().
putsym()
static void putsym (int sptr) static
Definition at line 1433 of file ilmutil.cpp.
References NEED, sptr, SYMNAME, x, xavl, xfile, and xsize.
Referenced by put_dtype().
rdgilms()
int rdgilms (int mode)
...
Definition at line 1788 of file ilmutil.cpp.
References assert, BOS_SIZE, DBGBIT, ERR_Severe, flg, gbl, gilmb, gilmb_mode, gilmpos, GILMSAVE, GILMB::globalilmfirst, GILMB::globalilmtotal, i, GILMB::ilm_base, GILMB::ilm_size, GILMB::ilmavl, GILMB::ilmpos, ilms, IM_VAR, len, llvm_ilms_rewrite_mode(), mode, ILMINFO::name, NEED, ILMINFO::oprs, pos, rewindilms(), and FLG::smp.
Referenced by process_input().
rdilms()
int rdilms (void)
...
Definition at line 1935 of file ilmutil.cpp.
References assert, BCOPY, BOS_SIZE, DBGBIT, dumpilms(), ERR_Severe, fihb, gbl, gilmb, gilmb_mode, GILMSAVE, ILMB::globalilmcount, ILMB::globalilmstart, i, ILMB::ilm_base, GILMB::ilm_base, ILMB::ilm_size, ILMB::ilmavl, GILMB::ilmavl, ilmb, GILMB::ilmpos, NEED, and FIHB::nextfindex.
Referenced by AssignAddresses(), and expand().
reloc_ilms()
void reloc_ilms (ILM_T * p)
...
Definition at line 557 of file ilmutil.cpp.
References assert, BCOPY, BOS_SIZE, count, ERR_Fatal, ERR_Severe, ILMB::ilm_base, ILMB::ilm_size, ILMA, ILMB::ilmavl, ilmb, ilms, IM_OPRFLAG, IM_VAR, len, NEED, NULL, OPR_LNK, ILMINFO::oprs, and p.
reset_global_ilm_position()
void reset_global_ilm_position (void)
...
Definition at line 319 of file ilmutil.cpp.
References gilmb, GILMSAVE, ILMB::globalilmcount, GILMB::globalilmcount, ILMB::globalilmstart, GILMB::globalilmstart, ilmb, and GILMB::ilmpos.
Referenced by AssignAddresses(), and rewindilms().
restartilms()
void restartilms (void)
...
Definition at line 2028 of file ilmutil.cpp.
References assert, ERR_Severe, gbl, ILMB::globalilmcount, ILMB::globalilmstart, i, ilmb, saveilmcount, and saveilmstart.
RestoreGilms()
void RestoreGilms (FILE * fil)
...
Definition at line 1902 of file ilmutil.cpp.
References BOS_SIZE, ERR_Fatal, error(), gilmb, gilmb_mode, GILMSAVE, GILMB::ilm_base, GILMB::ilm_size, GILMB::ilmavl, GILMB::ilmpos, and NEED.
rewindilms()
void rewindilms (void)
...
Definition at line 1998 of file ilmutil.cpp.
References assert, BZERO, FIHB::currfindex, FIHB::currftag, ERR_Severe, FIH_DIRNAME, FIH_FILENAME, FIH_FULLNAME, fihb, gbl, gilmb_mode, ILMB::globalilmcount, ILMB::globalilmstart, i, ilmb, NEW, FIHB::nextfindex, FIHB::nextftag, NULL, nullname, reset_global_ilm_position(), saveilmcount, saveilmstart, FIHB::stg_avail, FIHB::stg_base, and FIHB::stg_size.
Referenced by exp_init(), and rdgilms().
save_ilms()
ILM_T * save_ilms (int area)
...
Definition at line 470 of file ilmutil.cpp.
References area, BCOPY, BOS_SIZE, count, DBGBIT, dmpilms(), gbl, getitem(), ILMB::ilm_base, ILMA, ILMB::ilmavl, ilmb, NULL, p, and q.
save_ilms0()
ILM_T * save_ilms0 (void * area)
...
Definition at line 499 of file ilmutil.cpp.
References area, BCOPY, BOS_SIZE, count, DBGBIT, dmpilms(), gbl, ILMB::ilm_base, ILMA, ILMB::ilmavl, ilmb, NULL, p, and q.
SaveGilms()
void SaveGilms (FILE * fil)
...
Definition at line 1885 of file ilmutil.cpp.
References ERR_Fatal, error(), gilmb, GILMB::ilm_base, and GILMB::ilmavl.
set_gilmb_mode()
void set_gilmb_mode (int mode)
...
Definition at line 1926 of file ilmutil.cpp.
References gilmb_mode, and mode.
set_ilmpos()
void set_ilmpos (long pos)
...
Definition at line 1756 of file ilmutil.cpp.
References ERR_Fatal, gbl, interr(), pos, and r.
set_ilmstart()
void set_ilmstart (int start)
...
Definition at line 1766 of file ilmutil.cpp.
References ILMB::globalilmcount, ILMB::globalilmstart, ilmb, and start.
swap_next_gilm()
void swap_next_gilm (void)
...
Definition at line 355 of file ilmutil.cpp.
References gilmb, GILMSAVE, ILMB::globalilmcount, GILMB::globalilmcount, GILMB::globalilmfirst, ILMB::globalilmstart, GILMB::globalilmstart, GILMB::globalilmtotal, GILMB::ilmavl, ilmb, GILMB::ilmpos, and next_gilmb.
wrilms()
void wrilms (int linenum)
...
Definition at line 427 of file ilmutil.cpp.
References BOS_SIZE, CNULL, DBGBIT, dmpilms(), ERR_Fatal, error(), gbl, gilmb_mode, ILMB::ilm_base, ILMB::ilmavl, ilmb, linenum, p, sem, and SEM::wrilms.
Referenced by read_ilm().
Variable Documentation
gilmb
GILMB gilmb = {0, 0, 0, 0, 0, 0, 0, 0}
Definition at line 42 of file ilmutil.cpp.
Referenced by fini_ilm(), get_entry(), get_ilmstart(), init_global_ilm_mode(), init_global_ilm_position(), init_next_gilm(), rdgilms(), rdilms(), reset_global_ilm_position(), RestoreGilms(), SaveGilms(), and swap_next_gilm().
gilmb_mode
int gilmb_mode = 0 static
Definition at line 51 of file ilmutil.cpp.
Referenced by fini_ilm(), rdgilms(), rdilms(), RestoreGilms(), rewindilms(), set_gilmb_mode(), and wrilms().
gilmpos
long gilmpos = 0 static
Definition at line 1739 of file ilmutil.cpp.
Referenced by get_ilmpos(), ll_set_outlined_currsub(), and rdgilms().
globfile
int globfile = 0 static
Definition at line 818 of file ilmutil.cpp.
Referenced by _dumpilms(), and _dumponeilm().
globindex
int globindex = 0 static
Definition at line 818 of file ilmutil.cpp.
Referenced by _dumpilms(), and _dumponeilm().
ilm_base
ILM_T* ilm_base extern
Referenced by _dumpilms(), _dumponeilm(), and dumpsingleilm().
ilmb
ILMB ilmb
Definition at line 40 of file ilmutil.cpp.
Referenced by _dumpilms(), ad1ilm(), ad2ilm(), ad3ilm(), ad4ilm(), ad5ilm(), add_ilms(), adNilm(), Begindata(), check_ilm(), compute_sdsc_subscr(), compute_subscr(), count_ilms(), dinit(), dinit_data(), dinit_end(), dmpilms(), do_dinit(), dumpilms(), dumpilmtrees(), eval_fvec(), eval_ilm(), exp_ac(), exp_array(), exp_bran(), exp_call(), exp_load(), exp_misc(), exp_pure(), exp_qjsr(), exp_smp(), exp_store(), exp_zqjsr(), expand(), expdumpilms(), find_scope_labels(), fini_ilm(), get_dtype_from_ilm(), get_ilmstart(), getstr(), gwrilms(), ilm_outlined_pad_ilm(), init_global_ilm_mode(), init_global_ilm_position(), init_ilm(), init_next_gilm(), inlarr(), is_ishft(), ll_rewrite_ilms(), ll_write_ilm_header(), llGetILMLen(), mkbranch(), optional_missing_ilm(), rdilms(), read_ilm(), reloc_ilms(), reset_global_ilm_position(), restartilms(), restartRewritingILM(), rewindilms(), save_ilms(), save_ilms0(), semant_init(), semant_reinit(), set_ilmstart(), setfile(), start_taskdup(), struct_ret_tmp(), swap_next_gilm(), and wrilms().
ilmpos
int ilmpos = 0
Definition at line 49 of file ilmutil.cpp.
next_gilmb
GILMB next_gilmb = {0, 0, 0, 0, 0, 0, 0, 0}
Definition at line 43 of file ilmutil.cpp.
Referenced by fini_next_gilm(), gwrilms(), init_next_gilm(), and swap_next_gilm().
nullname
const char* nullname = "" static
Definition at line 282 of file ilmutil.cpp.
Referenced by init_ilm(), and rewindilms().
saveilmcount
int saveilmcount = 0 static
Definition at line 1992 of file ilmutil.cpp.
Referenced by restartilms(), and rewindilms().
saveilmstart
int saveilmstart = 0 static
Definition at line 1992 of file ilmutil.cpp.
Referenced by restartilms(), and rewindilms().
x
int* x static
Definition at line 1429 of file ilmutil.cpp.
Referenced by dumpilmtree(), dumpilmtrees(), and putsym().
xavl
int xavl static
Definition at line 1428 of file ilmutil.cpp.
Referenced by dumpilmtree(), dumpilmtrees(), and putsym().
xfile
FILE* xfile static
Definition at line 1430 of file ilmutil.cpp.
Referenced by _dumpilmtree(), dumpilmtree(), dumpilmtrees(), put_dtype(), and putsym().
xsize
int xsize static
Definition at line 1428 of file ilmutil.cpp.
Referenced by dumpilmtree(), dumpilmtrees(), and putsym().