flang: iltutil.cpp File Reference
iltutil.cpp File Reference
ILT utility module.
#include "iltutil.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "ilm.h"
#include "fih.h"
#include "ili.h"
#include "expand.h"
#include "ccffinfo.h"
#include <stdarg.h>
Macros
#define MAXILT 67108864
Functions
void ilt_init (void)
Initialize the ILT area.
void ilt_cleanup (void)
...
int addilt (int after, int ilix)
Add an ilt.
void delilt (int iltx)
Delete an ilt from a block which is "read" and reuse it.
void unlnkilt (int iltx, int bihx, bool reuse)
delete an ilt where the block may not be "read", and possibly reuse it
void relnkilt (int iltx, int bihx)
...
void moveilt (int iltx, int before)
Move an ilt before another ilt.
static void srcfunc (int ilix)
int reduce_ilt (int iltx, int ilix)
Reduce an ilt to a sequence of function ilts.
void dump_ilt (FILE *ff, int bihx)
Dump ILT to a file.
void dmpilt (int bihx)
Dump ILT to global debug file.
void wrilts (int bihx)
Write out an ilt/ili block given its bih.
void rdilts (int bihx)
Read in an ilt/ili block.
void * ccff_ilt_info (int msgtype, const char *msgid, int iltx, int bihx, const char *message,...)
...
void * subccff_ilt_info (void *xparent, int msgtype, const char *msgid, int iltx, int bihx, const char *message,...)
...
Variables
static int iltcur
Detailed Description
ILT utility module.
Definition in file iltutil.cpp.
Macro Definition Documentation
MAXILT
#define MAXILT 67108864
Definition at line 23 of file iltutil.cpp.
Function Documentation
addilt()
int addilt (int after, int ilix)
Add an ilt.
...
Add an ilt inserting it after the ilt "after"; ilix locates the ili which represents the root of the ili tree
Definition at line 50 of file iltutil.cpp.
References after, bihb, BIHB::callfg, ILTB::callfg, FIHB::currfindex, FIHB::currftag, fihb, gbl, i, IL_TYPE, ILI_OPC, ILT_NEXT, ILT_PREV, iltb, ILTY_BRANCH, ILTY_STORE, BIHB::ldvol, ILTB::ldvol, FIHB::nextfindex, FIHB::nextftag, p, BIHB::qjsrfg, ILTB::qjsrfg, STG_NEXT_FREELIST, BIHB::stvol, ILTB::stvol, and type.
Referenced by assign1(), check_ilm(), chk_block(), cr_block(), exp_end(), exp_header(), exp_label(), exp_scope_label(), exp_smp(), flsh_saveili(), gsmove_chk_block(), llvmAddConcurEntryBlk(), llvmAddConcurExitBlk(), redundantLdLdElim(), reg_assign1(), rm_smove(), srcfunc(), storedums(), and widenInsertWideStore().
ccff_ilt_info()
void * ccff_ilt_info (int msgtype, const char * msgid, int iltx, int bihx, const char * message, ...)
...
Definition at line 514 of file iltutil.cpp.
References _ccff_info(), BIH_FINDEX, BIH_LINENO, ILT_FINDEX, ILT_LINENO, lineno, and NULL.
delilt()
void delilt (int iltx)
Delete an ilt from a block which is "read" and reuse it.
...
Definition at line 94 of file iltutil.cpp.
References ILT_FREE, ILT_IGNORE, ILT_ILIP, ILT_NEXT, ILT_PREV, iltb, next, prev, and STG_ADD_FREELIST.
dmpilt()
void dmpilt (int bihx)
Dump ILT to global debug file.
...
Synonym to dump_ilt() with gbl.dbgfil as the file argument
Parameters
bihx - BIH number
Definition at line 451 of file iltutil.cpp.
References dump_ilt(), and gbl.
Referenced by wrilts().
dump_ilt()
void dump_ilt (FILE * ff, int bihx)
Dump ILT to a file.
...
Parameters
ff - file pointer
bihx - BIH number
Definition at line 260 of file iltutil.cpp.
References assert, BIH_ASM, BIH_ASSN, BIH_COMBST, BIH_CS, BIH_DOCONC, BIH_EN, BIH_ENLAB, BIH_EX, BIH_FINDEX, BIH_FT, BIH_GUARDEE, BIH_GUARDER, BIH_HEAD, BIH_ILTFIRST, BIH_ILTLAST, BIH_INNERMOST, BIH_LABEL, BIH_LAST, BIH_LDVOL, BIH_LINENO, BIH_LPCNTFROM, BIH_MEXITS, BIH_MIDIOM, BIH_NOBLA, BIH_NOMERGE, BIH_NOSIMD, BIH_NOUNROLL, BIH_PAR, BIH_PARALN, BIH_PARLOOP, BIH_PARSECT, BIH_PL, BIH_QJSR, BIH_RD, BIH_RESID, BIH_SIMD, BIH_SMOVE, BIH_STREG, BIH_STVOL, BIH_TAIL, BIH_TASK, BIH_UJRES, BIH_UNROLL, BIH_UNROLL_COUNT, BIH_VCAND, BIH_VPAR, BIH_XT, BIH_ZTRP, DBGBIT, ddilitree(), dmpilitree(), ERR_Severe, ili_throw_label(), ILT_BR, ILT_CAN_THROW, ILT_CPLX, ILT_DBGLINE, ILT_DELEBB, ILT_DELETE, ILT_EX, ILT_IGNORE, ILT_ILIP, ILT_INV, ILT_MCACHE, ILT_NEXT, ILT_PREDC, ILT_SPLIT, ILT_ST, iltb, NULL, p, ILTB::privtmp, and q.
Referenced by dmpilt(), dump_blocks(), and dump_one_block().
ilt_cleanup()
void ilt_cleanup (void)
...
Definition at line 37 of file iltutil.cpp.
References iltb, and STG_DELETE.
ilt_init()
void ilt_init (void)
Initialize the ILT area.
...
Definition at line 30 of file iltutil.cpp.
References iltb, next, STG_ALLOC, and STG_SET_FREELINK.
Referenced by ds_init().
moveilt()
void moveilt (int iltx, int before)
Move an ilt before another ilt.
...
remove iltx from list
insert iltx before 'before'
Definition at line 178 of file iltutil.cpp.
References i, ILT_NEXT, ILT_PREV, and j.
rdilts()
void rdilts (int bihx)
Read in an ilt/ili block.
...
'read' a flowgraph node.
"Read" in the block specified by bihx. the 0th entry in the ILT area (next and prev) are set to the first and last ilts respectively
Definition at line 493 of file iltutil.cpp.
References BIH_EX, BIH_FINDEX, BIH_FTAG, BIH_ILTFIRST, BIH_ILTLAST, BIH_LDVOL, BIH_QJSR, BIH_RD, BIH_STVOL, bihb, BIHB::callfg, FIHB::currfindex, FIHB::currftag, fihb, ILT_NEXT, ILT_PREV, BIHB::ldvol, FIHB::nextfindex, FIHB::nextftag, BIHB::qjsrfg, and BIHB::stvol.
reduce_ilt()
int reduce_ilt (int iltx, int ilix)
Reduce an ilt to a sequence of function ilts.
...
Reduces the ili tree located by ilix producing ilts which locate function ilis occuring in ilix. This routine sets iltucr with iltx which indicates where ilts are to be added and calls srcfunc.
Definition at line 245 of file iltutil.cpp.
References iltcur, and srcfunc().
Referenced by chk_block(), and exp_label().
relnkilt()
void relnkilt (int iltx, int bihx)
...
Definition at line 160 of file iltutil.cpp.
References BIH_ILTFIRST, BIH_ILTLAST, ILT_FREE, ILT_NEXT, ILT_PREV, and j.
srcfunc()
static void srcfunc (int ilix) static
search the ili subtree located by ilix for functions and creating an ilt for each one found. The static variable iltcur (local to this module indicates where an ilt is added. iltcur is updated to locate the new ilt
Definition at line 201 of file iltutil.cpp.
References ad1ili(), addilt(), ILTB::callfg, i, IL_ISLINK, IL_TYPE, ILI_OPC, ILI_OPND, ilis, iltb, iltcur, ILTY_PROC, ILIINFO::oprs, and srcfunc().
Referenced by reduce_ilt(), and srcfunc().
subccff_ilt_info()
void * subccff_ilt_info (void * xparent, int msgtype, const char * msgid, int iltx, int bihx, const char * message, ...)
...
Definition at line 542 of file iltutil.cpp.
References _ccff_info(), BIH_FINDEX, BIH_LINENO, ILT_FINDEX, ILT_LINENO, lineno, and NULL.
unlnkilt()
void unlnkilt (int iltx, int bihx, bool reuse)
delete an ilt where the block may not be "read", and possibly reuse it
...
Parameters
iltx ilt to be deleted
bihx bih of block from which ilt is deleted (0 => read)
reuse true if ilt is to be reused
Definition at line 119 of file iltutil.cpp.
References BIH_ILTFIRST, BIH_ILTLAST, i, ILT_FREE, ILT_IGNORE, ILT_ILIP, ILT_NEXT, ILT_PREV, iltb, j, and STG_ADD_FREELIST.
wrilts()
void wrilts (int bihx)
Write out an ilt/ili block given its bih.
...
'write' the flowgraph node.
Write out ilts for the block denoted by bih. Various flags have already been set in bih. This routine buffers up the ilt block in the bih area.
Definition at line 462 of file iltutil.cpp.
References BIH_FINDEX, BIH_FTAG, BIH_ILTFIRST, BIH_ILTLAST, bihb, BIHB::callfg, FIHB::currfindex, FIHB::currftag, FLG::dbg, dmpilt(), fihb, flg, gbl, ILT_NEXT, ILT_PREV, BIHB::ldvol, FIHB::nextfindex, FIHB::nextftag, BIHB::qjsrfg, and BIHB::stvol.
Variable Documentation
iltcur
int iltcur static
Definition at line 25 of file iltutil.cpp.
Referenced by reduce_ilt(), and srcfunc().