flang: iltutil.h File Reference
iltutil.h File Reference
#include "gbldefs.h"
#include <stdio.h>
Functions
int addilt (int after, int ilix)
...
int reduce_ilt (int iltx, int ilix)
...
void * ccff_ilt_info (int msgtype, const char *msgid, int iltx, int bihx, const char *message,...)
...
void delilt (int iltx)
...
void dmpilt (int bihx)
...
void dump_ilt (FILE *ff, int bihx)
...
void ilt_cleanup (void)
...
void ilt_init (void)
...
void moveilt (int iltx, int before)
...
void rdilts (int bihx)
...
void relnkilt (int iltx, int bihx)
...
void * subccff_ilt_info (void *xparent, int msgtype, const char *msgid, int iltx, int bihx, const char *message,...)
...
void unlnkilt (int iltx, int bihx, bool reuse)
...
void wrilts (int bihx)
...
Function Documentation
addilt()
int addilt (int after, int ilix)
...
...
Add an ilt inserting it after the ilt "after"; ilix locates the ili which represents the root of the ili tree
Definition at line 50 of file iltutil.cpp.
References after, bihb, BIHB::callfg, ILTB::callfg, FIHB::currfindex, FIHB::currftag, fihb, gbl, i, IL_TYPE, ILI_OPC, ILT_NEXT, ILT_PREV, iltb, ILTY_BRANCH, ILTY_STORE, BIHB::ldvol, ILTB::ldvol, FIHB::nextfindex, FIHB::nextftag, p, BIHB::qjsrfg, ILTB::qjsrfg, STG_NEXT_FREELIST, BIHB::stvol, ILTB::stvol, and type.
Referenced by assign1(), check_ilm(), chk_block(), cr_block(), exp_end(), exp_header(), exp_label(), exp_scope_label(), exp_smp(), flsh_saveili(), gsmove_chk_block(), llvmAddConcurEntryBlk(), llvmAddConcurExitBlk(), redundantLdLdElim(), reg_assign1(), rm_smove(), srcfunc(), storedums(), and widenInsertWideStore().
ccff_ilt_info()
void * ccff_ilt_info (int msgtype, const char * msgid, int iltx, int bihx, const char * message, ...)
...
Definition at line 514 of file iltutil.cpp.
delilt()
void delilt (int iltx)
...
...
Definition at line 1769 of file fgraph.c.
References ILT_FREE, ILT_IGNORE, ILT_ILIP, ILT_NEXT, ILT_PREV, iltb, next, prev, stdx, STG_ADD_FREELIST, TRUE, and unlnkilt().
Referenced by exp_remove_gsmove(), and remove_scope_labels().
dmpilt()
void dmpilt (int bihx)
...
...
Synonym to dump_ilt() with gbl.dbgfil as the file argument
Parameters
bihx - BIH number
Definition at line 1775 of file fgraph.c.
References dump_ilt(), dump_node(), fgx, and gbl.
Referenced by flow(), schedule(), and wrilts().
dump_ilt()
void dump_ilt (FILE * ff, int bihx)
...
...
Parameters
ff - file pointer
bihx - BIH number
Definition at line 260 of file iltutil.cpp.
References assert, BIH_ASM, BIH_ASSN, BIH_COMBST, BIH_CS, BIH_DOCONC, BIH_EN, BIH_ENLAB, BIH_EX, BIH_FINDEX, BIH_FT, BIH_GUARDEE, BIH_GUARDER, BIH_HEAD, BIH_ILTFIRST, BIH_ILTLAST, BIH_INNERMOST, BIH_LABEL, BIH_LAST, BIH_LDVOL, BIH_LINENO, BIH_LPCNTFROM, BIH_MEXITS, BIH_MIDIOM, BIH_NOBLA, BIH_NOMERGE, BIH_NOSIMD, BIH_NOUNROLL, BIH_PAR, BIH_PARALN, BIH_PARLOOP, BIH_PARSECT, BIH_PL, BIH_QJSR, BIH_RD, BIH_RESID, BIH_SIMD, BIH_SMOVE, BIH_STREG, BIH_STVOL, BIH_TAIL, BIH_TASK, BIH_UJRES, BIH_UNROLL, BIH_UNROLL_COUNT, BIH_VCAND, BIH_VPAR, BIH_XT, BIH_ZTRP, DBGBIT, ddilitree(), dmpilitree(), ERR_Severe, ili_throw_label(), ILT_BR, ILT_CAN_THROW, ILT_CPLX, ILT_DBGLINE, ILT_DELEBB, ILT_DELETE, ILT_EX, ILT_IGNORE, ILT_ILIP, ILT_INV, ILT_MCACHE, ILT_NEXT, ILT_PREDC, ILT_SPLIT, ILT_ST, iltb, NULL, p, ILTB::privtmp, and q.
Referenced by dmpilt(), dump_blocks(), and dump_one_block().
ilt_cleanup()
void ilt_cleanup (void)
...
Definition at line 37 of file iltutil.cpp.
References iltb, and STG_DELETE.
ilt_init()
void ilt_init (void)
...
...
Definition at line 30 of file iltutil.cpp.
References iltb, next, STG_ALLOC, and STG_SET_FREELINK.
Referenced by ds_init().
moveilt()
void moveilt (int iltx, int before)
...
...
remove iltx from list
insert iltx before 'before'
Definition at line 178 of file iltutil.cpp.
References i, ILT_NEXT, ILT_PREV, and j.
rdilts()
void rdilts (int bihx)
...
...
This defines the 0th STD entry to locate the beginning and end STDs of the node. The STD state (values of the STDs in the 0th entry and the beginning and last STDs of the flowgraph node) is saved. After a node has been read, its STD list has the following properties:
the list is terminated by 0.
STD_NEXT(0) locates the first STD in the list.
STD_PREV(0) locates the last STD in the list.
...
'read' a flowgraph node.
"Read" in the block specified by bihx. the 0th entry in the ILT area (next and prev) are set to the first and last ilts respectively
Definition at line 1636 of file fgraph.c.
References BIH_EX, BIH_FINDEX, BIH_FTAG, BIH_ILTFIRST, BIH_ILTLAST, BIH_LDVOL, BIH_QJSR, BIH_RD, BIH_STVOL, bihb, BIHB::callfg, FIHB::currfindex, FIHB::currftag, f, FG_LNEXT, FG_LPREV, FG_STDFIRST, FG_STDLAST, fgx, fihb, ILT_NEXT, ILT_PREV, BIHB::ldvol, n, FIHB::nextfindex, FIHB::nextftag, p, BIHB::qjsrfg, rw_state, STD_NEXT, STD_PREV, and BIHB::stvol.
Referenced by _avail(), add_loop_hd(), add_single_loop_exit(), check_ilm(), collect_root_ilis(), exp_end(), exp_mp_func_prologue(), exp_remove_gsmove(), exp_smp(), get_temp_forall2(), is_branch_between(), is_contains_ast_between(), lflow_of_block(), ll_save_gtid_val(), llvmAddConcurEntryBlk(), llvmAddConcurExitBlk(), mk_dealloc_stub(), mk_loop_hdtl(), move_invar_std(), must_follow(), reassociate(), reg_assign1(), remove_scope_labels(), resetMppBih(), resetTaskBih(), rm_smove(), smp_conflict(), storedums(), and visit_ilis().
reduce_ilt()
int reduce_ilt (int iltx, int ilix)
...
...
Reduces the ili tree located by ilix producing ilts which locate function ilis occuring in ilix. This routine sets iltucr with iltx which indicates where ilts are to be added and calls srcfunc.
Definition at line 245 of file iltutil.cpp.
References iltcur, and srcfunc().
Referenced by chk_block(), and exp_label().
relnkilt()
void relnkilt (int iltx, int bihx)
...
Definition at line 160 of file iltutil.cpp.
References BIH_ILTFIRST, BIH_ILTLAST, ILT_FREE, ILT_NEXT, ILT_PREV, and j.
subccff_ilt_info()
void * subccff_ilt_info (void * xparent, int msgtype, const char * msgid, int iltx, int bihx, const char * message, ...)
...
Definition at line 542 of file iltutil.cpp.
unlnkilt()
void unlnkilt (int iltx, int bihx, bool reuse)
...
...
Parameters
iltx ilt to be deleted
bihx bih of block from which ilt is deleted (0 => read)
reuse true if ilt is to be reused
Definition at line 119 of file iltutil.cpp.
References BIH_ILTFIRST, BIH_ILTLAST, i, ILT_FREE, ILT_IGNORE, ILT_ILIP, ILT_NEXT, ILT_PREV, iltb, j, and STG_ADD_FREELIST.
wrilts()
void wrilts (int bihx)
...
...
This restores the STD list to be a single list of all of the STDs in the function. The STD state is restored.
...
'write' the flowgraph node.
Write out ilts for the block denoted by bih. Various flags have already been set in bih. This routine buffers up the ilt block in the bih area.
Definition at line 1679 of file fgraph.c.
References assert, BIH_FINDEX, BIH_FTAG, BIH_ILTFIRST, BIH_ILTLAST, bihb, BIHB::callfg, FIHB::currfindex, FIHB::currftag, FLG::dbg, dmpilt(), f, FG_STDFIRST, FG_STDLAST, fgx, fihb, flg, gbl, ILT_NEXT, ILT_PREV, BIHB::ldvol, n, FIHB::nextfindex, FIHB::nextftag, p, BIHB::qjsrfg, rw_state, STD_NEXT, STD_PREV, and BIHB::stvol.
Referenced by _avail(), add_loop_hd(), add_single_loop_exit(), check_ilm(), collect_root_ilis(), exp_end(), exp_mp_func_prologue(), exp_remove_gsmove(), exp_smp(), get_temp_forall2(), is_branch_between(), is_contains_ast_between(), lflow_of_block(), ll_save_gtid_val(), llvmAddConcurEntryBlk(), llvmAddConcurExitBlk(), mk_dealloc_stub(), mk_loop_hdtl(), move_invar_std(), must_follow(), reassociate(), reg_assign1(), remove_scope_labels(), resetMppBih(), resetTaskBih(), rm_smove(), smp_conflict(), storedums(), visit_ilis(), and wr_block().