flang: hash.h File Reference
include/flang/ADT/hash.h File Reference
General-Purpose Hash Tables.
Classes
struct hash_functions_
struct hash_accu_
Macros
#define INT2HKEY(i) (hash_key_t)(long)(i)
#define HKEY2INT(k) (int)(long)(k)
#define HASH_ACCU_INIT
#define HASH_ACCU_ADD(accu, data)
#define HASH_ACCU_FINISH(accu)
#define HASH_ACCU_VALUE(accu) ((accu).a + 0)
Typedefs
typedef unsigned hash_value_t
typedef const void * hash_key_t
typedef hash_value_t(* hash_function_t) (hash_key_t)
typedef int(* hash_equality_t) (hash_key_t, hash_key_t)
typedef struct hash_functions_ hash_functions_t
typedef struct hashset_ * hashset_t
Hash Set.
typedef struct hashmap_ * hashmap_t
Hash Map.
typedef const void * hash_data_t
typedef struct hash_accu_ hash_accu_t
Functions
hashset_t hashset_alloc (hash_functions_t)
Allocate a hashset which uses the provided functions to interpret keys.
void hashset_free (hashset_t)
Free all memory used by a hashset.
void hashset_clear (hashset_t)
Erase all keys in the set.
unsigned hashset_size (hashset_t)
Get the number of keys in the set.
hash_key_t hashset_lookup (hashset_t, hash_key_t)
Look up a key and return the equivalent stored key, or NULL.
void hashset_insert (hashset_t, hash_key_t)
Insert a new key.
hash_key_t hashset_replace (hashset_t, hash_key_t)
Insert a new key or replace an existing key.
hash_key_t hashset_erase (hashset_t, hash_key_t)
Erase a key from the set and return it.
void hashset_iterate (hashset_t, void(*f)(hash_key_t, void *context), void *context)
Call f with every key in the hash set.
hashmap_t hashmap_alloc (hash_functions_t)
Allocate a hashmap.
void hashmap_free (hashmap_t)
Free all memory used by a hashmap.
void hashmap_clear (hashmap_t)
Erase all (key, data) entries in the map.
unsigned hashmap_size (hashmap_t)
Return the number of (key, data) pairs in the map.
hash_key_t hashmap_lookup (hashmap_t, hash_key_t, hash_data_t *data)
Look up a key and return the equivalent stored key, or NULL.
void hashmap_insert (hashmap_t, hash_key_t, hash_data_t)
Insert a new (key, data) pair.
hash_key_t hashmap_replace (hashmap_t, hash_key_t, hash_data_t *data)
Insert or replace a (key, data) pair.
hash_key_t hashmap_erase (hashmap_t, hash_key_t, hash_data_t *data)
Erase a key from the map and return it.
void hashmap_iterate (hashmap_t, void(*f)(hash_key_t, hash_data_t, void *context), void *context)
Call f with every (key, data) pair in the hash map.
Variables
const hash_functions_t hash_functions_strings
Predefined hash functions for strings.
const hash_functions_t hash_functions_direct
Predefined hash functions for directly hashed keys.
Detailed Description
General-Purpose Hash Tables.
These two hash table implementations store void pointers as keys, using user-provided functions for hashing and equality testing. The void pointers are not interpreted by the hash table implementation, except:
The void pointers are passed to the provided hash() and equals() functions.
The sentinel values NULL and (void*)~0UL have special meanings and cannot be used as keys.
The equality function should return non-zero for equal hash keys. At a minimum, the provided functions must satisfy:
equals(a, b) ==> hash(a) = hash(b)
The hash() function should avoid clustering in the low bits of the hash value.
A NULL equals() function is equivalent to a function returning a == b, but faster.
Definition in file include/flang/ADT/hash.h.
Macro Definition Documentation
HASH_ACCU_ADD
#define HASH_ACCU_ADD (accu, data)
Value:
  do {                                \
    (accu).a += (hash_value_t)(data); \
    (accu).a += (accu).a << 10;       \
    (accu).a ^= (accu).a >> 6;        \
  } while (0)
Definition at line 235 of file include/flang/ADT/hash.h.
HASH_ACCU_FINISH
#define HASH_ACCU_FINISH (accu)
Value:
  do {                          \
    (accu).a += (accu).a << 3;  \
    (accu).a ^= (accu).a >> 11; \
    (accu).a += (accu).a << 15; \
  } while (0)
Definition at line 242 of file include/flang/ADT/hash.h.
HASH_ACCU_INIT
#define HASH_ACCU_INIT
Value:
  {                    \
    0                  \
  }
Definition at line 230 of file include/flang/ADT/hash.h.
HASH_ACCU_VALUE
#define HASH_ACCU_VALUE (accu) ((accu).a + 0)
Definition at line 249 of file include/flang/ADT/hash.h.
HKEY2INT
#define HKEY2INT (k) (int)(long)(k)
Definition at line 60 of file include/flang/ADT/hash.h.
INT2HKEY
#define INT2HKEY (i) (hash_key_t)(long)(i)
Definition at line 59 of file include/flang/ADT/hash.h.
Typedef Documentation
hash_accu_t
typedef struct hash_accu_ hash_accu_t
hash_data_t
typedef const void* hash_data_t
Definition at line 142 of file include/flang/ADT/hash.h.
hash_equality_t
typedef int(* hash_equality_t) (hash_key_t, hash_key_t)
Definition at line 39 of file include/flang/ADT/hash.h.
hash_function_t
typedef hash_value_t(* hash_function_t) (hash_key_t)
Definition at line 38 of file include/flang/ADT/hash.h.
hash_functions_t
typedef struct hash_functions_ hash_functions_t
hash_key_t
typedef const void* hash_key_t
Definition at line 36 of file include/flang/ADT/hash.h.
hash_value_t
typedef unsigned hash_value_t
Definition at line 35 of file include/flang/ADT/hash.h.
hashmap_t
typedef struct hashmap_* hashmap_t
Hash Map.
A hashmap_t is a hash table that maps a set of keys to data pointers.
The keys are treated exactly the same as for a hashset_t, and have the same restrictions (i.e., no NULL and ~0UL keys allowed). The data pointers can have any value.
Definition at line 141 of file include/flang/ADT/hash.h.
hashset_t
typedef struct hashset_* hashset_t
Hash Set.
A hashset_t is a hash table that stores a set of keys with no associated information.
Definition at line 67 of file include/flang/ADT/hash.h.
Function Documentation
hashmap_alloc()
hashmap_t hashmap_alloc (hash_functions_t f)
Allocate a hashmap.
The returned handle must be freed with hashmap_free().
Definition at line 222 of file lib/ADT/hash.c.
References alloc_tables(), f, and h.
Referenced by add_sincos_map(), build_kmpc_api_name(), cg_llvm_init(), create_action_map(), create_arg_parser(), gen_llvm_sincos_call(), gen_llvm_vsincos_call(), ll_create_module(), ll_proto_init(), lldbg_emit_subprogram(), redundantLdLdElim(), use_hash_alloc(), and widenAddressArith().
hashmap_clear()
void hashmap_clear (hashmap_t h)
Erase all (key, data) entries in the map.
Definition at line 255 of file lib/ADT/hash.c.
References alloc_tables(), and h.
Referenced by ll_reset_module_types(), lldbg_cleanup_missing_bounds(), process_global_lifetime_debug(), redundantLdLdElim(), schedule(), sincos_clear_all_args(), and use_hash_free().
hashmap_erase()
hash_key_t hashmap_erase (hashmap_t h, hash_key_t key, hash_data_t * data)
Erase a key from the map and return it.
If a (key, data) pair was erased and data is not NULL, update *data with the erased data value.
If no key was erased, return NULL and leave *data unchanged.
Definition at line 380 of file lib/ADT/hash.c.
References DTABLE, ERASED, h, i, NULL, and search().
Referenced by ll_remove_struct_type(), lldbg_create_aggregate_members_type(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_emit_global_variable(), lldbg_emit_local_variable(), and sincos_clear_arg_helper().
hashmap_free()
void hashmap_free (hashmap_t h)
Free all memory used by a hashmap.
Note that any memory referenced by keys and data pointers in the map is not freed.
Definition at line 239 of file lib/ADT/hash.c.
References h.
Referenced by destroy_action_map(), destroy_arg_parser(), ll_destroy_module(), redundantLdLdElim(), remove_dead_sincos_calls(), use_hash_free(), and widenAddressArith().
hashmap_insert()
void hashmap_insert (hashmap_t h, hash_key_t key, hash_data_t data)
Insert a new (key, data) pair.
This function assumes that no equivalent key is present in the map, i.e. hashmap_lookup() would return NULL.
Use hashmap_replace() if an equivalent key may exist in the map already.
Definition at line 310 of file lib/ADT/hash.c.
References assert, DTABLE, ERASED, ERR_Fatal, h, hashmap_lookup(), i, insertion_point(), NEED_REHASH, NULL, and rehash().
Referenced by add_action(), add_generic_argument(), build_kmpc_api_name(), copy_action(), get_intrinsic(), intern_constant(), ll_add_global_debug(), ll_add_module_debug(), ll_get_md_node(), ll_proto_add(), lldbg_fwd_local_variable(), process_formal_arguments(), and redundantLdLdElim().
hashmap_iterate()
void hashmap_iterate (hashmap_t h, void(*)(hash_key_t, hash_data_t, void *context) f, void * context)
Call f with every (key, data) pair in the hash map.
The function f must not modify the hash table.
Definition at line 410 of file lib/ADT/hash.c.
References f, h, ISKEY, n, and size.
Referenced by destroy_arg_parser(), lldbg_cleanup_missing_bounds(), redundantLdLdElim(), sincos_clear_specific_arg(), use_hash_dump(), and widenAddressArith().
hashmap_lookup()
hash_key_t hashmap_lookup (hashmap_t h, hash_key_t key, hash_data_t * data)
Look up a key and return the equivalent stored key, or NULL.
If if a key was found and data is not NULL, *data will be set to the corresponding data value, otherwise it is not changed.
Definition at line 281 of file lib/ADT/hash.c.
References DTABLE, h, i, k, and search().
Referenced by add_action(), add_generic_argument(), add_sincos_map(), build_kmpc_api_name(), cleanup_unneeded_sincos_calls(), copy_action(), execute_actions_for_keyword(), get_intrinsic(), get_last_sincos(), insert_jump_entry_instr(), intern_constant(), ll_add_global_debug(), ll_add_module_debug(), ll_get_global_debug(), ll_get_md_node(), ll_get_module_debug(), ll_get_struct_type(), ll_named_struct_type_exists(), ll_proto_add(), ll_proto_get_abi(), ll_proto_has_defined_body(), ll_proto_is_weak(), ll_proto_set_abi(), ll_proto_set_defined_body(), ll_proto_set_intrinsic(), ll_proto_set_weak(), lldbg_create_aggregate_members_type(), lldbg_emit_global_variable(), lldbg_emit_local_variable(), lldbg_emit_subprogram(), lldbg_fwd_local_variable(), parse_arguments(), print_function_signature(), process_auto_sptr(), process_sptr_offset(), redundantLdLdElim(), remove_dead_sincos_calls(), rlleReplace(), sincos_argument_valid(), use_hash_lookup(), widenApplyCse(), widenApplyFree(), widenApplyStore(), and widenApplyVarMap().
hashmap_replace()
hash_key_t hashmap_replace (hashmap_t h, hash_key_t key, hash_data_t * data)
Insert or replace a (key, data) pair.
If an equivalent key already exists, replace it with the new key and *data, and return the old key. On return, *data is set to the old data.
If no equivalent key is present, insert the new key and *data and return NULL. The *data value is not updated.
Definition at line 345 of file lib/ADT/hash.c.
References DTABLE, h, hashmap_insert(), i, ISKEY, NULL, and search().
Referenced by add_sincos_imap(), add_sincos_imap_loads(), add_sincos_map(), gatherLocals(), ll_create_named_struct_type(), ll_finish_variable(), lldbg_emit_subprogram(), redundantLdLdElim(), rlleFindLL(), use_hash_insert(), widenProcessDirectLoad(), and widenProcessIndirectLoad().
hashmap_size()
unsigned hashmap_size (hashmap_t h)
Return the number of (key, data) pairs in the map.
Definition at line 269 of file lib/ADT/hash.c.
References h.
Referenced by lldbg_cleanup_missing_bounds(), and redundantLdLdElim().
hashset_alloc()
hashset_t hashset_alloc (hash_functions_t f)
Allocate a hashset which uses the provided functions to interpret keys.
The returned hashset_t handle should be passed to hashset_free() to deallocate memory.
Definition at line 213 of file lib/ADT/hash.c.
References alloc_tables(), f, and h.
Referenced by add_debug_cmnblk_variables(), create_arg_parser(), dinits(), ll_create_local_name(), ll_create_local_object(), ll_create_module(), lldbg_emit_imported_entity(), print_entry_subroutine(), redundantLdLdElim(), verify_all_blocks(), widenAddressArith(), and widenPruneAcon().
hashset_clear()
void hashset_clear (hashset_t h)
Erase all keys in the set.
Definition at line 247 of file lib/ADT/hash.c.
References alloc_tables(), and h.
Referenced by dinits(), parse_arguments(), print_entry_subroutine(), and verify_all_blocks().
hashset_erase()
hash_key_t hashset_erase (hashset_t h, hash_key_t key)
Erase a key from the set and return it.
Return NULL if no equivalent key was found.
Definition at line 365 of file lib/ADT/hash.c.
References ERASED, h, i, NULL, and search().
Referenced by widenElimAddrTaken().
hashset_free()
void hashset_free (hashset_t h)
Free all memory used by a hashset.
Note that any memory referenced by keys in the set is not freed.
Definition at line 231 of file lib/ADT/hash.c.
References h.
Referenced by ll_destroy_function(), ll_destroy_module(), print_entry_subroutine(), redundantLdLdElim(), verify_all_blocks(), widenAddressArith(), and widenPruneAcon().
hashset_insert()
void hashset_insert (hashset_t h, hash_key_t key)
Insert a new key.
Note that this function assumes that no equivalent key is present in the set, i.e. hashset_lookup() would return false.
Use hashset_replace() if an equivalent key may be in the set already.
The key cannot be NULL or (hash_key_t)~0UL.
Definition at line 291 of file lib/ADT/hash.c.
References assert, ERASED, ERR_Fatal, h, hashset_lookup(), i, insertion_point(), NEED_REHASH, NULL, and rehash().
Referenced by add_debug_cmnblk_variables(), lldbg_emit_imported_entity(), print_entry_subroutine(), rlleMakeSet(), unique_name(), and unique_type().
hashset_iterate()
void hashset_iterate (hashset_t h, void(*)(hash_key_t, void *context) f, void * context)
Call f with every key in the hash set.
Note that the iteration order is a function of both the hash function and the sequence of hashset_* calls leading up to this one. If pointers are directly hashed, address space layout randomization can cause different iteration orders in otherwise identical executions.
The function f must not modify the hash table.
Definition at line 397 of file lib/ADT/hash.c.
References f, for(), h, ISKEY, n, and size.
Referenced by dump_all_dinits(), ll_destroy_function(), verify_all_blocks(), widenAddressArith(), and widenPruneAcon().
hashset_lookup()
hash_key_t hashset_lookup (hashset_t h, hash_key_t key)
Look up a key and return the equivalent stored key, or NULL.
Definition at line 275 of file lib/ADT/hash.c.
References h, and search().
Referenced by add_debug_cmnblk_variables(), ll_named_struct_type_exists(), lldbg_emit_imported_entity(), print_entry_subroutine(), pruneAcon(), rlleFindLL(), unique_name(), unique_type(), was_value_set(), and widenElimAddrTaken().
hashset_replace()
hash_key_t hashset_replace (hashset_t h, hash_key_t key)
Insert a new key or replace an existing key.
If an equivalent key already exists, replace it with the new key and return the old one. If no equivalent key is in the set, insert the new key and return NULL.
Definition at line 330 of file lib/ADT/hash.c.
References h, hashset_insert(), i, ISKEY, NULL, and search().
Referenced by add_generic_argument(), collect_referenced_locals(), dinits(), parse_arguments(), pruneAcon(), widenAddNarrowVars(), and widenGatherAcon().
hashset_size()
unsigned hashset_size (hashset_t h)
Get the number of keys in the set.
Definition at line 263 of file lib/ADT/hash.c.
References h.
Referenced by unique_name(), and widenAddressArith().
Variable Documentation
hash_functions_direct
const hash_functions_t hash_functions_direct extern
Predefined hash functions for directly hashed keys.
The pointers are compared by value with no indirection. These hash functions can also be used for integer keys. Just cast the integers to hash_key_t.
Definition at line 459 of file lib/ADT/hash.c.
Referenced by add_sincos_map(), cg_llvm_init(), create_arg_parser(), dinits(), gen_llvm_sincos_call(), gen_llvm_vsincos_call(), ll_create_module(), lldbg_emit_subprogram(), print_entry_subroutine(), redundantLdLdElim(), use_hash_alloc(), verify_all_blocks(), widenAddressArith(), and widenPruneAcon().
hash_functions_strings
const hash_functions_t hash_functions_strings extern
Predefined hash functions for strings.
The hash keys are interpreted as pointers to NUL-terminated strings.
Definition at line 441 of file lib/ADT/hash.c.
Referenced by add_debug_cmnblk_variables(), build_kmpc_api_name(), cg_llvm_init(), create_action_map(), create_arg_parser(), ll_create_local_name(), ll_create_local_object(), ll_create_module(), ll_proto_init(), and lldbg_emit_imported_entity().