flang: initpar.c File Reference
initpar.c File Reference
FIXME.
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <memory.h>
#include <sys/time.h>
#include "global.h"
#include "stdioInterf.h"
#include "fioMacros.h"
#include "open_close.h"
#include "format.h"
#include "fort_vars.h"
Macros
#define MAXOPTS 128
Functions
char * __fort_getgbuf (long)
void __fort_init_consts ()
void __fort_print_version ()
int __io_get_argc ()
char ** __io_get_argv ()
void __io_set_argc (int)
WIN_API __INT_T ENTCOMN (NP, np)[]
WIN_API __INT_T ENTCOMN (ME, me)[]
int __fort_myprocnum ()
int __fort_ncpus ()
int __fort_getioproc ()
int __fort_is_ioproc ()
void __fort_abort (const char *s)
void __fort_abortp (const char *s)
void __fort_exit (int s)
static void __fort_initarg ()
char * __fort_getenv (const char *nm)
getenv (uses env, not environ)
static void __fort_initopt ()
const char * __fort_getopt (const char *opt)
static void getopt_abort (const char *problem, const char *opt)
long __fort_getoptn (const char *opt, long def)
int __fort_getoptb (const char *opt, int def)
static void __fort_istat ()
static void __fort_initcom ()
void __fort_procargs ()
static char * __fort_passarg (int fr, int tol, int toh, char *val)
void __fort_passargs (int fr, int tol, int toh)
static void term ()
void ENTFTN (INIT, init)
void __fort_pull_them_in ()
void __attribute__ ((constructor))
Variables
WIN_MSVCRT_IMP char ** environ
static char ** arg
static char ** env
static char * opts [MAXOPTS]
static char * optarea
struct {
char consts
char atexit
} inited
static char * dumarg = NULL
Detailed Description
FIXME.
Definition in file initpar.c.
Macro Definition Documentation
MAXOPTS
#define MAXOPTS 128
Definition at line 57 of file initpar.c.
Function Documentation
__attribute__()
void __attribute__ ((constructor))
Definition at line 835 of file initpar.c.
References __fort_init_consts(), __fort_np2, __fort_tcpus, atexit, inited, and term().
__fort_abort()
void __fort_abort (const char * s)
Definition at line 320 of file initpar.c.
References __fort_abortx(), __fort_lcpu, buf, NULL, s, strlen(), and write.
Referenced by __alloc04(), __auto_alloc(), __fort_abortp(), __fort_adjbase(), __fort_adjust_index_array(), __fort_alloc(), __fort_associated(), __fort_calloc(), __fort_comm_merge(), __fort_coord_to_procnum(), __fort_copy(), __fort_create_conforming_index_array(), __fort_create_conforming_mask_array(), __fort_crecv(), __fort_csend(), __fort_cyclic_loop(), __fort_dealloc(), __fort_dealloc03(), __fort_defaultproc(), __fort_doit(), __fort_ebcopys(), __fort_erecv(), __fort_esend(), __fort_fetch_int(), __fort_fetch_int_element(), __fort_fetch_int_vector(), __fort_fetch_log(), __fort_finish_descriptor(), __fort_gen_block_bounds(), __fort_get_scalar(), __fort_getarg(), __fort_getdir(), __fort_global_reduce(), __fort_inherit_template(), __fort_init_consts(), __fort_initopt(), __fort_kalloc(), __fort_local_address(), __fort_local_offset(), __fort_localize(), __fort_malloc(), __fort_par_read(), __fort_procnum_to_coord(), __fort_realloc(), __fort_recvl(), __fort_red_abort(), __fort_reverse_array(), __fort_sendl(), __fort_set_alignment(), __fort_set_sectionx(), __fort_set_single(), __fort_store_int(), __fort_store_int_element(), __fort_store_int_vector(), __fort_store_log(), __fort_trac_init(), __fort_use_allocation(), __fort_varying_int(), __fort_varying_log(), __fort_zwrite(), __fortio_eoferr(), __fortio_eorerr(), __fortio_error(), __fortio_main(), __INT_T(), __LOG_T(), advance(), advance_permuted(), block_setup(), comm_sked_start(), copy_in_abort(), copy_loop(), copy_none(), copy_xfer(), cyclic_setup(), DCLEN64(), ENTF90(), ENTFTN(), fetch_int(), fetch_vector(), gathscat_abort(), getopt_abort(), global_reduce_abort(), if(), mmul_mxm(), mmul_mxv(), mmul_vxm(), nullify(), olap_copy(), olap_recv(), olap_send(), olap_shift(), olap_start(), print_row(), proc_setup(), ptr_asgn(), ptr_out(), put_int(), sighand(), store_element(), store_int(), store_int_kind(), store_log(), store_vector(), store_vector_int(), and void().
__fort_abortp()
void __fort_abortp (const char * s)
Definition at line 334 of file initpar.c.
References __fort_abort(), __fort_lcpu, __io_stderr(), NULL, and s.
Referenced by __fort_gethostname(), __fort_par_close(), __fort_par_open(), __fort_par_read(), __fort_par_seek(), __fort_par_unlink(), __fort_par_write(), __fort_second(), __fort_zclose(), __fort_zopen(), and __fort_zwrite().
__fort_exit()
void __fort_exit (int s)
Definition at line 344 of file initpar.c.
References s.
Referenced by _f90io_stop(), ENTCRF90(), and ENTF90().
__fort_getenv()
char * __fort_getenv (const char * nm)
getenv (uses env, not environ)
Definition at line 378 of file initpar.c.
References e, env, environ, n, NULL, and strlen().
Referenced by __fort_getopt(), __fort_initopt(), __fortio_init(), __fortio_open(), _f90io_stop(), and ENTFTN().
__fort_getgbuf()
char * __fort_getgbuf (long len)
Definition at line 345 of file xfer.c.
Referenced by __fort_pull_them_in().
__fort_getioproc()
int __fort_getioproc ()
Definition at line 304 of file initpar.c.
References __fort_ioproc.
__fort_getopt()
const char * __fort_getopt (const char * opt)
Definition at line 440 of file initpar.c.
References __fort_getenv(), arg, env, n, NULL, opt, p, and q.
Referenced by __fort_fixmnt(), __fort_gethostname(), __fort_getmap(), __fort_getoptb(), __fort_getoptn(), __fort_initcom(), __fort_istat(), __fort_sethand(), __fort_trac_init(), and ENTFTN().
__fort_getoptb()
int __fort_getoptb (const char * opt, int def)
Definition at line 526 of file initpar.c.
References __fort_getopt(), def, getopt_abort(), n, NULL, opt, and p.
Referenced by ENTFTN().
__fort_getoptn()
long __fort_getoptn (const char * opt, long def)
Definition at line 508 of file initpar.c.
References __fort_getopt(), __fort_strtol(), def, getopt_abort(), n, NULL, opt, p, and q.
Referenced by ENTFTN().
__fort_init_consts()
void __fort_init_consts ()
Definition at line 667 of file const.c.
References __fort_abort(), __fort_mask_log, __fort_masks, __fort_shifts, __fort_size_of, __fort_true_log, __fort_trues, __LOG, __NONE, __NTYPES, DIST_DESC_DIM_INT_LEN, DIST_DESC_DIM_PTR_LEN, DIST_DESC_HDR_INT_LEN, DIST_DESC_HDR_PTR_LEN, F90_DESC_DIM_INT_LEN, F90_DESC_DIM_PTR_LEN, F90_DESC_HDR_INT_LEN, F90_DESC_HDR_PTR_LEN, GET_FIO_CNFG_FTN_TRUE, GET_FIO_CNFG_FTN_TRUE_ADDR, GET_FIO_CNFG_TRUE_MASK, GET_FIO_CNFG_TRUE_MASK_ADDR, i, j, k, m, MAX_FOR_INT_TYPE, max_int1, max_int2, max_int4, max_int8, max_str, MAXDIMS, min_int1, min_int2, min_int4, min_int8, min_str, RECIP, RECIP_DIV, RECIP_DIVMOD, RECIP_MOD, and t.
Referenced by __attribute__(), and ENTFTN().
__fort_initarg()
static void __fort_initarg () static
Definition at line 354 of file initpar.c.
References __io_environ(), __io_get_argv(), arg, dumarg, env, and environ.
Referenced by __fort_procargs().
__fort_initcom()
static void __fort_initcom () static
Definition at line 594 of file initpar.c.
References __fort_debug, __fort_debugn, __fort_getopt(), __fort_istat(), __fort_quiet, __fort_strtol(), __fort_tcpus, __fort_test, getopt_abort(), k, n, p, q, Q_PROF_AVG, Q_PROF_NONE, and strlen().
Referenced by __fort_passargs(), and __fort_procargs().
__fort_initopt()
static void __fort_initopt () static
Definition at line 401 of file initpar.c.
References __fort_abort(), __fort_free(), __fort_getenv(), __fort_malloc(), i, MAXOPTS, NULL, optarea, p, q, and strlen().
Referenced by __fort_passargs(), and __fort_procargs().
__fort_is_ioproc()
int __fort_is_ioproc (void)
Definition at line 312 of file initpar.c.
References __fort_ioproc, and __fort_lcpu.
Referenced by __fort_stat_term().
__fort_istat()
static void __fort_istat () static
Definition at line 546 of file initpar.c.
References __fort_getopt(), __fort_quiet, getopt_abort(), NULL, p, Q_CPU, Q_CPUS, Q_MEM, Q_MEMS, Q_MSG, Q_MSGS, Q_PROF, and Q_TRAC.
Referenced by __fort_initcom().
__fort_myprocnum()
int __fort_myprocnum (void)
Definition at line 79 of file initpar.c.
References __fort_lcpu.
Referenced by __fort_bcstchn(), __fort_chn_1toN(), and sighand().
__fort_ncpus()
int __fort_ncpus ()
Definition at line 87 of file initpar.c.
References __fort_tcpus.
__fort_passarg()
static char * __fort_passarg (int fr, int tol, int toh, char * val) static
Definition at line 670 of file initpar.c.
References __fort_lcpu, __fort_malloc(), __fort_rrecvl(), __fort_rsendl(), __UCHAR, cpu(), len, NULL, p, strlen(), and val.
Referenced by __fort_passargs().
__fort_passargs()
void __fort_passargs (int fr, int tol, int toh)
Definition at line 700 of file initpar.c.
References __fort_initcom(), __fort_initopt(), __fort_lcpu, __fort_malloc(), __fort_passarg(), __fort_rrecvl(), __fort_rsendl(), __UCHAR, arg, cpu(), env, n, NULL, and strlen().
__fort_print_version()
void __fort_print_version ()
Definition at line 33 of file runtime/flang/version.c.
References __io_stderr(), TRANSNAM, and version.
Referenced by ENTFTN().
__fort_procargs()
void __fort_procargs (void)
Definition at line 656 of file initpar.c.
References __fort_initarg(), __fort_initcom(), __fort_initopt(), and arg.
Referenced by __fort_begpar().
__fort_pull_them_in()
void __fort_pull_them_in ()
Definition at line 817 of file initpar.c.
References __fort_getgbuf(), __fort_rrecv(), __fort_rsend(), and __fort_zopen().
__io_get_argc()
int __io_get_argc ()
Definition at line 30 of file ioargs.c.
__io_get_argv()
char ** __io_get_argv ()
Definition at line 14 of file ioargs.c.
Referenced by __fort_initarg().
__io_set_argc()
void __io_set_argc (int v)
Definition at line 38 of file ioargs.c.
References __argc_save.
ENTCOMN() [1/2]
WIN_API __INT_T ENTCOMN (ME , me)
ENTCOMN() [2/2]
WIN_API __INT_T ENTCOMN (NP , np)
Referenced by ENTFTN().
ENTFTN()
void ENTFTN (INIT , init)
Definition at line 782 of file initpar.c.
References __fort_begpar(), __fort_entry_init(), __fort_getopt(), __fort_getoptb(), __fort_init_consts(), __fort_lcpu, __fort_np2, __fort_print_version(), __fort_setarg(), __fort_tcpus, __fort_zmem, atexit, ENTCOMN(), inited, n, and term().
getopt_abort()
static void getopt_abort (const char * problem, const char * opt) static
Definition at line 489 of file initpar.c.
References __fort_abort(), buf, opt, p, and q.
Referenced by __fort_getoptb(), __fort_getoptn(), __fort_initcom(), and __fort_istat().
term()
static void term () static
Definition at line 771 of file initpar.c.
References __f90_allo_term(), __fort_endpar(), __fort_entry_term(), and __fortio_cleanup().
Referenced by __attribute__(), const_eval(), ENTFTN(), and init_fold_const().
Variable Documentation
arg
char** arg static
Definition at line 54 of file initpar.c.
Referenced by __fort_getopt(), __fort_initarg(), __fort_passargs(), __fort_procargs(), __mth_i_abs(), __mth_i_acos(), __mth_i_acosh(), __mth_i_asin(), __mth_i_asinh(), __mth_i_bessel_j0(), __mth_i_bessel_j1(), __mth_i_bessel_jn(), __mth_i_bessel_y0(), __mth_i_bessel_y1(), __mth_i_bessel_yn(), __mth_i_dacos(), __mth_i_dacosh(), __mth_i_dasin(), __mth_i_dasinh(), __mth_i_dbessel_j0(), __mth_i_dbessel_j1(), __mth_i_dbessel_jn(), __mth_i_dbessel_y0(), __mth_i_dbessel_y1(), __mth_i_dbessel_yn(), __mth_i_derf(), __mth_i_derfc(), __mth_i_derfc_scaled(), __mth_i_dgamma(), __mth_i_dlog_gamma(), __mth_i_erf(), __mth_i_erfc(), __mth_i_erfc_scaled(), __mth_i_fabs(), __mth_i_gamma(), __mth_i_log(), __mth_i_log10(), __mth_i_log_gamma(), __mth_i_qabs(), __mth_i_qacosh(), __mth_i_qasinh(), __mth_i_qcosh(), __mth_i_qerf(), __mth_i_qerfc(), __mth_i_qerfc_scaled(), __mth_i_qgamma(), __mth_i_qlog_gamma(), __mth_i_qsinh(), _do_iface(), _find_pointer_assignments_f90(), _is_atomic_update_binop(), _linearize_func(), _non_private(), _PDbound(), _PDsize(), ad_func(), add_arg(), add_assumshp(), add_byval(), add_io_arg(), aliased_args(), amd64_coerce(), arg_is_refd(), args_match(), assumshp_args(), ast_clear_repl(), begin_entry(), bld_ud(), check_arg_isalloc(), check_subprogram(), chk_adjarr(), chk_arguments(), classify_common(), cloneUplevel(), cons_vectorlength_scalable_metadata(), copy_inargs(), copy_scalar_intent_in(), count_formal_args(), create_atomic_capture_seq(), create_atomic_read_seq(), create_atomic_seq(), create_atomic_write_seq(), cvt(), declare_array_dummys(), declare_dummy_array(), define_stfunc(), ecvt(), emit_kopy_in(), emit_redim(), emit_scalar_kopy_in(), ENT3F(), ENTF90(), eval_abs(), eval_adjustl(), eval_adjustr(), eval_ceiling(), eval_char(), eval_floor(), eval_fltconvert(), eval_ichar(), eval_index(), eval_int(), eval_ishft(), eval_len_trim(), eval_max(), eval_merge(), eval_min(), eval_minval_or_maxval(), eval_mod(), eval_nint(), eval_repeat(), eval_reshape(), eval_scale(), eval_scan(), eval_selected_char_kind(), eval_selected_int_kind(), eval_selected_real_kind(), eval_shape(), eval_size(), eval_sqrt(), eval_transfer(), eval_trim(), eval_ul_bound(), eval_verify(), exp64(), exp_ac(), exp_misc(), exp_restore_mxcsr(), exp_type_bound_proc_call(), export_some_args(), export_some_procedure(), fcvt(), find_assumshp_dep(), find_by_name_stype_arg(), find_descrs(), find_operator(), fix_args(), fold_int32_from_real128(), fold_int32_from_real32(), fold_int32_from_real64(), fold_int64_from_real128(), fold_int64_from_real32(), fold_int64_from_real64(), fold_real128_abs(), fold_real128_acos(), fold_real128_asin(), fold_real128_atan(), fold_real128_cos(), fold_real128_exp(), fold_real128_from_int64(), fold_real128_from_real32(), fold_real128_from_real64(), fold_real128_from_uint64(), fold_real128_log(), fold_real128_log10(), fold_real128_negate(), fold_real128_sin(), fold_real128_sqrt(), fold_real128_tan(), fold_real32_abs(), fold_real32_acos(), fold_real32_asin(), fold_real32_atan(), fold_real32_cos(), fold_real32_exp(), fold_real32_from_int64(), fold_real32_from_real128(), fold_real32_from_real64(), fold_real32_from_uint64(), fold_real32_log(), fold_real32_log10(), fold_real32_negate(), fold_real32_sin(), fold_real32_sqrt(), fold_real32_tan(), fold_real64_abs(), fold_real64_acos(), fold_real64_asin(), fold_real64_atan(), fold_real64_cos(), fold_real64_exp(), fold_real64_from_int64(), fold_real64_from_real128(), fold_real64_from_real32(), fold_real64_from_uint64(), fold_real64_log(), fold_real64_log10(), fold_real64_negate(), fold_real64_sin(), fold_real64_sqrt(), fold_real64_tan(), fold_uint32_from_real128(), fold_uint32_from_real32(), fold_uint32_from_real64(), fold_uint64_from_real128(), fold_uint64_from_real32(), fold_uint64_from_real64(), gen_arg_operand(), gen_call_class_obj_size(), gen_cmplxpart_intr(), gen_copy_out(), gen_llvm_expr(), gen_llvm_sincos_call(), gen_ptr_in(), gen_ptr_out(), gen_scalar_to_vector_helper(), gen_scalar_to_vector_no_shuffle(), gen_va_end(), gen_va_start(), get_argdt(), get_array_pointer(), get_charintrin_temp(), get_type_descr_arg(), get_type_descr_arg2(), get_type_descr_dummy(), gethost_dumlen(), iface_arg(), iface_intrinsic(), ignore_tkr(), ignore_tkr_all(), ILMTPApp::ILMTPApp(), init_newargs(), inline_ast(), instantiate_interface(), interface_for_entry(), interface_for_llvmiface(), is_arg_in_entry(), is_argp_in_entry(), is_atomic_update_binop(), is_kopy_in_needed(), leave_arg(), ll_abi_classify_arg_dtype(), ll_abi_complete_arg_info(), ll_ad_outlined_func2(), ll_make_atomic_compare_xchg(), ll_make_atomic_load(), ll_make_atomic_store(), ll_process_routine_parameters(), lldbg_emit_expression_mdnode(), llLoadGtid(), lower_intrinsic(), Machar::Machar(), make_arg_copy(), make_keyword_str(), make_lltype_from_abi_arg(), make_lltype_from_arg_noproto(), markmodified(), missing_optionals(), mk_result_sptr(), mod_add_subprogram(), mod_end_subprogram_two(), move_alloc_arg(), mul64_10(), needs_redim(), neg64(), newargs_for_entry(), not64(), not_in_arrfn(), omp_init_nest_lock_with_hint(), omp_init_nest_lock_with_hint_(), parse_arguments(), plower_arg(), pop_subprogram(), precompute_arg_intrin(), precompute_args(), print_arg_attributes(), print_ast(), print_entry_subroutine(), print_function_signature(), print_header(), process_formal_arguments(), put_arg_table(), put_call(), put_forall_pcalls(), queue_symbol(), replace_arguments(), replace_fval_in_params(), replace_parms(), resolvePass(), rewrite_cmplxpart_rval(), rewrite_func_ast(), rewrite_inlined_args(), rewrite_sub_args(), rewrite_triples(), semant2(), semant3(), semfin(), semsmp(), set_assumed_bounds(), set_assumsz_bound(), setTaskloopVars(), shape_comm(), shf128(), shf128by1(), shf64(), SyminiF90::SyminiF90(), SyminiFE90::SyminiFE90(), Symutil::Symutil(), to_assumed_shape(), transform_call(), umul64_10(), undouble_callee_args_f90(), undouble_callee_args_llvmf90(), uneg64(), update_arg_info(), update_shape_info(), update_shape_info_expr(), use_dummy_desc(), and ushf64().
atexit
char atexit
Definition at line 63 of file initpar.c.
Referenced by __attribute__(), and ENTFTN().
consts
char consts
Definition at line 62 of file initpar.c.
dumarg
char* dumarg = NULL static
Definition at line 351 of file initpar.c.
Referenced by __fort_initarg().
env
char** env static
Definition at line 55 of file initpar.c.
Referenced by __fenv_fegetenv(), __fenv_feholdexcept(), __fenv_fesetenv(), __fenv_feupdateenv(), __fort_getenv(), __fort_getopt(), __fort_initarg(), and __fort_passargs().
environ
WIN_MSVCRT_IMP char** environ
Definition at line 42 of file initpar.c.
Referenced by __fort_getenv(), __fort_initarg(), and __io_environ().
struct { ... } inited
Referenced by __attribute__(), do_fixup_param_vars_for_derived_arrays(), ENTFTN(), and semant1().
optarea
char* optarea static
Definition at line 59 of file initpar.c.
Referenced by __fort_initopt().
opts
char* opts[MAXOPTS] static
Definition at line 58 of file initpar.c.