flang: init.c File Reference
init.c File Reference
Stubs.
#include "stdioInterf.h"
#include "fioMacros.h"
Functions
void __fort_abortx (void)
Abort the whole mess.
void __fort_endpar (void)
End of parallel program.
void __fort_begpar (int ncpus)
Begin parallel program.
void __fort_barrier ()
void ENTFTN (BARRIER, barrier)()
__INT_T ENTFTN (TID, tid)
Variables
static int tid = 0
const char * __fort_transnam = "rpm1"
Detailed Description
Stubs.
Definition in file init.c.
Function Documentation
__fort_abortx()
void __fort_abortx (void)
Abort the whole mess.
Definition at line 35 of file init.c.
References __abort(), __fort_traceback(), and NULL.
Referenced by __fort_abort().
__fort_barrier()
void __fort_barrier (void)
Definition at line 65 of file init.c.
Referenced by __fort_par_close(), __fort_par_open(), __fort_par_read(), __fort_par_unlink(), __fort_par_write(), __fortio_cleanup(), and ENTF90().
__fort_begpar()
void __fort_begpar (int ncpus)
Begin parallel program.
Definition at line 49 of file init.c.
References __fort_procargs(), __fort_sethand(), __io_stderr(), GET_DIST_TCPUS, SET_DIST_LCPU, SET_DIST_TCPUS, SET_DIST_TIDS, and tid.
Referenced by ENTFTN().
__fort_endpar()
void __fort_endpar (void)
End of parallel program.
Definition at line 43 of file init.c.
Referenced by term().
ENTFTN() [1/2]
void ENTFTN (BARRIER , barrier)
Definition at line 69 of file init.c.
ENTFTN() [2/2]
__INT_T ENTFTN (TID , tid)
Definition at line 72 of file init.c.
Variable Documentation
__fort_transnam
const char* __fort_transnam = "rpm1"
Definition at line 19 of file init.c.
tid
int tid = 0 static
Definition at line 17 of file init.c.
Referenced by __fort_begpar(), _mp_copyin_move_multiple(), and do_targets().