flang: inliner.c File Reference
inliner.c File Reference
inliner utils definitions
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "ast.h"
#include "gramtk.h"
#include "semant.h"
#include "optimize.h"
#include "interf.h"
#include "inliner.h"
#include "ccffinfo.h"
#include "fdirect.h"
Classes
struct fitem
struct libentry
struct argrep
Macros
#define TRACE0(s)
#define TRACE1(s, a1)
#define TRACE2(s, a1, a2)
#define TRACE3(s, a1, a2, a3)
#define INLINER_VERSION 14
#define MAX_INLINE_NAME 42
#define MAX_FNAME_LEN 2048
#define TOC_HEADER_FMT "Inliner TOC V.%d"
#define TOC_ENTRY_FMT "%s %s %s %s"
#define MODNAME_FMT "i%d.e"
#define ERROR(s, v)
#define MAX_LINE_LEN 400
#define PERM_AREA 8
#define STASH(p, area) strcpy(getitem(area, strlen(p) + 1), p);
#define AR_SPTRDUMMY(i) parbase[i].sptrDummy
#define AR_ASTACT(i) parbase[i].astAct
Typedefs
typedef struct fitem FI
typedef struct libentry LE
typedef struct argrep AR
Functions
static void inline_stds (int stdStart, int stdLast, int iLevels, int level)
static int inline_ast (int std, int ast, int iLevels, int level)
static LOGICAL inline_func (int std, int ast, int iLevels, int level, int *pEntry)
static void modify_inlined_stds (int sptrEntry, int ast, int stdstart, int stdend)
static int find_entry (int sptrCall)
static int copy_inargs (int sptrEntry, int astCall, int stdStart, int stdEnd)
static void remove_inlined_stds ()
static void remove_inlined_symbols (int)
static int promote_assumsz_arg (int sptrDummy, int astArg)
static void allocate_adjarrs (int stdstart, int stdend)
static void allocate_array (int sptr, int stdStart, int stdEnd)
static void remove_returns (int stdstart, int stdend)
static void move_labels (int stdstart, int stdlast)
static void rewrite_inlined_args (int astCall, int sptrEntry, int stdstart, int stdend)
static int replace_arg (int astDummy, int astAct)
static void assign_bounds (int sptrDummy, int astAct, int std)
static int get_subscr (int ast, unsigned int dim)
static void load_TOC (char *sDir)
static void store_funcname (char *sFunc)
static LE * find_libentry (const char *sMod, const char *sHost, char *sFunc)
static LOGICAL tkr_match_arg (int dtypDummy, int dtypAct)
static LOGICAL aliased_args (int sptrEntry, int astCall)
static LOGICAL make_arg_copy (int sptrEntry, int astCall, unsigned int arg)
void extractor_command_info (char *sDir, int nInsts, char *sFunc)
LOGICAL extractor_possible (void)
void extractor (void)
void extractor_end (void)
void inline_add_lib (char *sDir)
void inline_add_func (char *sFunc, int n)
void inliner (void)
static void use_old_subprograms (int oldsymavl)
static void erase_entry (int oldsymavl)
void remove_alias (int std, int ast)
static LOGICAL missing_optionals (int sptrEntry, int astCall)
static int removelist (int listhead, int oldsymavl)
static int removeautolist (int listhead, int oldsymavl)
static int replace_parms (int ast, void *extra_arg)
static void load_inline_file (char *sDir)
Variables
static char * sExtDir = NULL
static FI * pfiStart = NULL
static LE * pleStart = NULL
static int sptrHigh = 0
static int nLevels = 1
static AR * parbase
static int iarsize
static int iaravail
static int stdEnd
static int ninlined = 0
static int nskip = 0
static int use_old_subprogram_limits [2] = {0, 0}
Detailed Description
inliner utils definitions
Definition in file inliner.c.
Macro Definition Documentation
AR_ASTACT
#define AR_ASTACT (i) parbase[i].astAct
Definition at line 94 of file inliner.c.
AR_SPTRDUMMY
#define AR_SPTRDUMMY (i) parbase[i].sptrDummy
Definition at line 93 of file inliner.c.
ERROR
#define ERROR (s, v)
Value:
  {                  \
    interr(s, v, 1); \
    return;          \
  }
Definition at line 66 of file inliner.c.
INLINER_VERSION
#define INLINER_VERSION 14
Definition at line 58 of file inliner.c.
MAX_FNAME_LEN
#define MAX_FNAME_LEN 2048
Definition at line 61 of file inliner.c.
MAX_INLINE_NAME
#define MAX_INLINE_NAME 42
Definition at line 60 of file inliner.c.
MAX_LINE_LEN
#define MAX_LINE_LEN 400
Definition at line 71 of file inliner.c.
MODNAME_FMT
#define MODNAME_FMT "i%d.e"
Definition at line 64 of file inliner.c.
PERM_AREA
#define PERM_AREA 8
Definition at line 72 of file inliner.c.
STASH
#define STASH (p, area) strcpy(getitem(area, strlen(p) + 1), p);
Definition at line 73 of file inliner.c.
TOC_ENTRY_FMT
#define TOC_ENTRY_FMT "%s %s %s %s"
Definition at line 63 of file inliner.c.
TOC_HEADER_FMT
#define TOC_HEADER_FMT "Inliner TOC V.%d"
Definition at line 62 of file inliner.c.
TRACE0
#define TRACE0 (s)
Value:
  if (DBGBIT(49, 1)) \
  fprintf(gbl.dbgfil, s)
Definition at line 37 of file inliner.c.
TRACE1
#define TRACE1 (s, a1)
Value:
  if (DBGBIT(49, 1))  \
  fprintf(gbl.dbgfil, s, a1)
Definition at line 40 of file inliner.c.
TRACE2
#define TRACE2 (s, a1, a2)
Value:
  if (DBGBIT(49, 1))      \
  fprintf(gbl.dbgfil, s, a1, a2)
Definition at line 43 of file inliner.c.
TRACE3
#define TRACE3 (s, a1, a2, a3)
Value:
  if (DBGBIT(49, 1))          \
  fprintf(gbl.dbgfil, s, a1, a2, a3)
Definition at line 46 of file inliner.c.
Typedef Documentation
AR
typedef struct argrep AR
FI
typedef struct fitem FI
LE
typedef struct libentry LE
Function Documentation
aliased_args()
static LOGICAL aliased_args (int sptrEntry, int astCall) static
Definition at line 2225 of file inliner.c.
References A_ARGCNTG, arg, argt, ARGT_ARG, assert, contains_ast(), FALSE, make_arg_copy(), nargs, and TRUE.
Referenced by inline_func().
allocate_adjarrs()
static void allocate_adjarrs (int stdstart, int stdend) static
Definition at line 1353 of file inliner.c.
References allocate_array(), sptr, sptrHigh, and stb.
Referenced by modify_inlined_stds().
allocate_array()
static void allocate_array (int sptr, int stdStart, int stdEnd) static
Definition at line 1367 of file inliner.c.
References A_TKNP, AD_ADJARR, AD_DEFER, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_NUMDIM, AD_UPAST, AD_UPBD, add_stmt_after(), ast, dim, DT_INT, FALSE, mk_assn_stmt(), mk_extent(), mk_id(), mk_stmt(), mk_subscr(), mk_triple(), ndims, sptr, STD_PREV, sym_get_scalar(), and TRUE.
Referenced by allocate_adjarrs().
assign_bounds()
static void assign_bounds (int sptrDummy, int astAct, int std) static
Definition at line 2005 of file inliner.c.
References AD_DPTR, AD_LWAST, AD_NUMDIM, AD_UPAST, add_stmt_before(), assert, ast, dim, DT_INT, memsym_of_ast(), mk_assn_stmt(), mk_binop(), OP_SUB, rank_of_sym(), SHD_LWB, SHD_NDIM, SHD_UPB, and std.
Referenced by rewrite_inlined_args().
copy_inargs()
static int copy_inargs (int sptrEntry, int astCall, int stdStart, int stdEnd) static
Definition at line 1036 of file inliner.c.
References A_ARGCNTG, A_TKNP, AD_DPTR, AD_LWAST, AD_LWBD, AD_UPAST, AD_UPBD, add_stmt_after(), add_stmt_before(), arg, ARGT_ARG, assert, ast, astb, aux, DDTG, dim, AUX::dpdsc_base, DT_INT, DTY, error(), gbl, ASTB::i1, make_arg_copy(), mk_argt(), mk_assn_stmt(), mk_binop(), mk_func_node(), mk_id(), mk_stmt(), mk_subscr(), mk_triple(), nargs, ndims, NULL, OP_ADD, OP_DIV, OP_SUB, promote_assumsz_arg(), remove_inlined_stds(), SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, sym_get_array(), sym_get_scalar(), and SYMNAME.
Referenced by modify_inlined_stds().
erase_entry()
static void erase_entry (int oldsymavl) static
Definition at line 759 of file inliner.c.
References sptr, and stb.
Referenced by inline_func().
extractor()
void extractor (void)
Definition at line 362 of file inliner.c.
References error(), ERROR, errsev(), export_inline(), extractor_possible(), fd, FILE, find_libentry(), gbl, getitem(), MAX_FNAME_LEN, MODNAME_FMT, NULL, PERM_AREA, libentry::pleNext, pleStart, sExtDir, libentry::sFunc, libentry::sHost, libentry::sMod, libentry::sModFile, STASH, SYMNAME, and TRACE0.
extractor_command_info()
void extractor_command_info (char * sDir, int nInsts, char * sFunc)
Definition at line 139 of file inliner.c.
References load_TOC(), and store_funcname().
extractor_end()
void extractor_end (void)
Definition at line 429 of file inliner.c.
References error(), fclose(), fd, FILE, fndpath(), freearea(), gbl, INLINER_VERSION, MAX_FNAME_LEN, NULL, PERM_AREA, libentry::pleNext, pleStart, sExtDir, libentry::sFunc, libentry::sHost, libentry::sMod, libentry::sModFile, TOC_ENTRY_FMT, and TOC_HEADER_FMT.
extractor_possible()
LOGICAL extractor_possible (void)
Definition at line 151 of file inliner.c.
References ccff_info(), STB::curr_scope, DTY, FALSE, STB::firstusym, gbl, MSGNEGINLINER, NOSYM, NULL, fitem::pfiNext, pfiStart, RU_FUNC, RU_SUBR, fitem::sFunc, sptr, ST_ISVAR, stb, std, STD_AST, STD_NEXT, SYMNAME, TRACE0, TRACE1, TRUE, TY_CHAR, TY_NCHAR, and XBIT.
Referenced by extractor().
find_entry()
static int find_entry (int sptrCall) static
Definition at line 1016 of file inliner.c.
References assert, sptr, sptrHigh, and stb.
Referenced by inline_func().
find_libentry()
static LE * find_libentry (const char * sMod, const char * sHost, char * sFunc) static
Definition at line 2189 of file inliner.c.
References NULL, libentry::pleNext, pleStart, libentry::sFunc, libentry::sHost, and libentry::sMod.
Referenced by extractor(), and inline_func().
get_subscr()
static int get_subscr (int ast, unsigned int dim) static
Definition at line 2050 of file inliner.c.
References AD_DPTR, AD_LWAST, AD_NUMDIM, AD_UPAST, ASD_NDIM, ASD_SUBS, assert, ast, astb, dim, DTY, ASTB::i1, interr(), and mk_triple().
Referenced by replace_arg().
inline_add_func()
void inline_add_func (char * sFunc, int n)
Definition at line 469 of file inliner.c.
References n, nLevels, and store_funcname().
inline_add_lib()
void inline_add_lib (char * sDir)
Definition at line 463 of file inliner.c.
References load_TOC().
inline_ast()
static int inline_ast (int std, int ast, int iLevels, int level) static
Definition at line 545 of file inliner.c.
References A_ARGCNTG, A_OPTYPEG, A_OPTYPEP, arg, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, FALSE, flg, inline_ast(), inline_func(), level(), mk_argt(), mk_assn_stmt(), mk_binop(), mk_convert(), mk_func_node(), mk_id(), mk_paren(), mk_stmt(), mk_subscr(), mk_substr(), mk_triple(), mk_unop(), nargs, ninlined, nsubs, std, sub, TRUE, unmk_argt(), and FLG::x.
Referenced by inline_ast(), and inline_stds().
inline_func()
static LOGICAL inline_func (int std, int ast, int iLevels, int level, int * pEntry) static
Definition at line 805 of file inliner.c.
References aliased_args(), assert, ast, ccff_info(), erase_entry(), error(), FALSE, fd, FILE, find_entry(), find_libentry(), flg, gbl, import_inline(), inline_stds(), level(), MAX_FNAME_LEN, missing_optionals(), modify_inlined_stds(), MSGNEGINLINER, ninlined, NOSYM, nskip, NULL, fitem::pfiNext, pfiStart, remove_alias(), remove_inlined_stds(), remove_inlined_symbols(), sExtDir, fitem::sFunc, libentry::sModFile, sptrHigh, stb, std, STD_LINENO, STD_NEXT, STD_PREV, stdEnd, SYMNAME, TRUE, use_old_subprograms(), FLG::x, and XBIT.
Referenced by inline_ast().
inline_stds()
static void inline_stds (int stdStart, int stdLast, int iLevels, int level) static
Definition at line 511 of file inliner.c.
References A_STDP, ast, delete_stmt(), gbl, inline_ast(), level(), std, STD_AST, STD_LINENO, and STD_NEXT.
Referenced by inline_func(), and inliner().
inliner()
void inliner (void)
Definition at line 483 of file inliner.c.
References DBGBIT, dump_std(), flg, gbl, inline_stds(), ninlined, nLevels, nskip, sExtDir, STD_NEXT, STD_PREV, FLG::x, and XBIT.
load_inline_file()
static void load_inline_file (char * sDir) static
Definition at line 2078 of file inliner.c.
References fclose(), fd, FILE, fndpath(), MAX_FNAME_LEN, MAX_LINE_LEN, and store_funcname().
Referenced by load_TOC().
load_TOC()
static void load_TOC (char * sDir) static
Definition at line 2112 of file inliner.c.
References ERROR, fclose(), fd, FILE, fndpath(), getitem(), INLINER_VERSION, load_inline_file(), MAX_FNAME_LEN, MAX_LINE_LEN, NULL, PERM_AREA, libentry::pleNext, pleStart, sExtDir, libentry::sFunc, libentry::sHost, libentry::sMod, libentry::sModFile, STASH, TOC_ENTRY_FMT, and TOC_HEADER_FMT.
Referenced by extractor_command_info(), and inline_add_lib().
make_arg_copy()
static LOGICAL make_arg_copy (int sptrEntry, int astCall, unsigned int arg) static
Definition at line 2261 of file inliner.c.
References A_ARGCNTG, A_ISLVAL, arg, ARGT_ARG, assert, astb, aux, AUX::dpdsc_base, FALSE, and ASTB::ptr0.
Referenced by aliased_args(), and copy_inargs().
missing_optionals()
static LOGICAL missing_optionals (int sptrEntry, int astCall) static
Definition at line 780 of file inliner.c.
References A_ARGCNTG, arg, argt, ARGT_ARG, astb, aux, AUX::dpdsc_base, FALSE, nargs, ASTB::ptr0, and TRUE.
Referenced by inline_func().
modify_inlined_stds()
static void modify_inlined_stds (int sptrEntry, int ast, int stdstart, int stdend) static
Definition at line 983 of file inliner.c.
References allocate_adjarrs(), ast, copy_inargs(), interr(), move_labels(), remove_returns(), and rewrite_inlined_args().
Referenced by inline_func().
move_labels()
static void move_labels (int stdstart, int stdlast) static
Definition at line 1474 of file inliner.c.
References add_stmt_before(), ast, FLANG_FALLTHROUGH, interr(), mk_stmt(), std, STD_AST, STD_LABEL, and STD_NEXT.
Referenced by modify_inlined_stds().
promote_assumsz_arg()
static int promote_assumsz_arg (int sptrDummy, int astArg) static
Definition at line 1297 of file inliner.c.
References ADD_ASSUMSZ, ADD_LWAST, ADD_NUMDIM, ADD_UPAST, ASD_NDIM, ASD_SUBS, ast, DTY, get_array_dtype(), memsym_of_ast(), mk_subscr(), mk_triple(), nsubs, sptr, and sub.
Referenced by copy_inargs(), and rewrite_inlined_args().
remove_alias()
void remove_alias (int std, int ast)
Definition at line 3687 of file rest.c.
References A_ARGCNTG, argt, ARGT_ARG, ast, i, pure_gbl::local_mode, nargs, remove_from_scalar_subscript(), remove_function_common_from_scalar_subscript(), and std.
Referenced by inline_func().
remove_inlined_stds()
static void remove_inlined_stds () static
Definition at line 1142 of file inliner.c.
References STD_NEXT, STD_PREV, and stdEnd.
Referenced by copy_inargs(), inline_func(), and rewrite_inlined_args().
remove_inlined_symbols()
static void remove_inlined_symbols (int oldsymavl) static
Definition at line 1167 of file inliner.c.
References CONVAL2G, DTY, gbl, HASH_CON, HASH_ID, STB::hashtb, interr(), len, STB::n_base, removeautolist(), removelist(), s, sptr, stb, strlen(), SYMNAME, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by inline_func().
remove_returns()
static void remove_returns (int stdstart, int stdend) static
Definition at line 1433 of file inliner.c.
References A_STDP, assert, ast, FALSE, gbl, getlab(), mk_label(), mk_stmt(), RFCNTI, std, STD_AST, STD_LABEL, STD_LINENO, STD_NEXT, and TRUE.
Referenced by modify_inlined_stds().
removeautolist()
static int removeautolist (int listhead, int oldsymavl) static
Definition at line 1158 of file inliner.c.
Referenced by remove_inlined_symbols().
removelist()
static int removelist (int listhead, int oldsymavl) static
Definition at line 1149 of file inliner.c.
Referenced by remove_inlined_symbols().
replace_arg()
static int replace_arg (int astDummy, int astAct) static
Definition at line 1888 of file inliner.c.
References AD_DPTR, AD_LWAST, AD_NUMDIM, assert, ast, astb, DDTG, dim, DT_INT, get_array_dtype(), get_subscr(), ASTB::i1, memsym_of_ast(), mk_binop(), mk_convert(), mk_subscr(), mk_triple(), OP_ADD, OP_MUL, OP_SUB, rank_of_sym(), SHD_LWB, SHD_NDIM, and SHD_STRIDE.
Referenced by replace_parms().
replace_parms()
static int replace_parms (int ast, void * extra_arg) static
Definition at line 1529 of file inliner.c.
References A_ARGCNTG, A_OPTYPEG, AR_ASTACT, AR_SPTRDUMMY, arg, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, ast, ast_replace(), ast_rewrite(), ast_traverse(), astb, dim, DTY, FALSE, FUNCLINEG, getcon(), iaravail, interr(), j, mk_cnst(), mk_id(), mk_member(), mk_subscr(), ndims, NOSYM, NULL, ASTB::ptr0, replace_arg(), replace_parms(), sptr, sym_of_ast(), TRUE, and use_old_subprogram_limits.
Referenced by replace_parms(), and rewrite_inlined_args().
rewrite_inlined_args()
static void rewrite_inlined_args (int astCall, int sptrEntry, int stdstart, int stdend) static
Definition at line 1717 of file inliner.c.
References A_STDP, AD_DPTR, AD_LWBD, AD_NUMDIM, AD_UPBD, AR_ASTACT, AR_SPTRDUMMY, arg, ARGT_ARG, assign_bounds(), ast, ast_rewrite(), ast_traverse(), ast_unvisit(), ast_visit(), astb, aux, BZERO, ccff_info(), check_member(), DDTG, dim, AUX::dpdsc_base, DTY, FREE, gbl, iaravail, iarsize, memsym_of_ast(), mk_id(), MSGNEGINLINER, ndims, NEED, NEW, NULL, parbase, promote_assumsz_arg(), ASTB::ptr0, remove_inlined_stds(), replace_parms(), sptr, sptrHigh, stb, std, STD_AST, STD_NEXT, sym_get_ptr(), SYMNAME, tkr_match_arg(), TY_CHAR, TY_NCHAR, and XBIT.
Referenced by modify_inlined_stds().
store_funcname()
static void store_funcname (char * sFunc) static
Definition at line 2173 of file inliner.c.
References ERROR, getitem(), PERM_AREA, fitem::pfiNext, pfiStart, fitem::sFunc, and STASH.
Referenced by extractor_command_info(), inline_add_func(), and load_inline_file().
tkr_match_arg()
static LOGICAL tkr_match_arg (int dtypDummy, int dtypAct) static
Definition at line 2205 of file inliner.c.
References FALSE, rank_of(), and tk_match_arg().
Referenced by rewrite_inlined_args().
use_old_subprograms()
static void use_old_subprograms (int oldsymavl) static
Definition at line 711 of file inliner.c.
References FUNCLINEP, NOSYM, sptr, sptrHigh, stb, and use_old_subprogram_limits.
Referenced by inline_func().
Variable Documentation
iaravail
int iaravail static
Definition at line 132 of file inliner.c.
Referenced by replace_parms(), and rewrite_inlined_args().
iarsize
int iarsize static
Definition at line 131 of file inliner.c.
Referenced by rewrite_inlined_args().
ninlined
int ninlined = 0 static
Definition at line 477 of file inliner.c.
Referenced by inline_ast(), inline_func(), and inliner().
nLevels
int nLevels = 1 static
Definition at line 129 of file inliner.c.
Referenced by inline_add_func(), and inliner().
nskip
int nskip = 0 static
Definition at line 478 of file inliner.c.
Referenced by inline_func(), and inliner().
parbase
AR* parbase static
Definition at line 130 of file inliner.c.
Referenced by rewrite_inlined_args().
pfiStart
FI* pfiStart = NULL static
Definition at line 126 of file inliner.c.
Referenced by extractor_possible(), inline_func(), and store_funcname().
pleStart
LE* pleStart = NULL static
Definition at line 127 of file inliner.c.
Referenced by extractor(), extractor_end(), find_libentry(), and load_TOC().
sExtDir
char* sExtDir = NULL static
Definition at line 125 of file inliner.c.
Referenced by extractor(), extractor_end(), inline_func(), inliner(), and load_TOC().
sptrHigh
int sptrHigh = 0 static
Definition at line 128 of file inliner.c.
Referenced by allocate_adjarrs(), find_entry(), inline_func(), rewrite_inlined_args(), and use_old_subprograms().
stdEnd
int stdEnd static
Definition at line 133 of file inliner.c.
Referenced by inline_func(), and remove_inlined_stds().
use_old_subprogram_limits
int use_old_subprogram_limits[2] = {0, 0} static
Definition at line 709 of file inliner.c.
Referenced by replace_parms(), and use_old_subprograms().