flang: inliner.h File Reference
inliner.h File Reference
publicly accessible functions for inliner
Functions
void extractor_command_info (char *sDir, int ignore, char *sFunc)
void extractor_end (void)
void extractor (void)
int extractor_possible (void)
void inline_add_lib (char *sDir)
void inline_add_func (char *sFunc, int nSize)
void inliner (void)
Detailed Description
publicly accessible functions for inliner
Definition in file inliner.h.
Function Documentation
extractor()
void extractor (void)
Definition at line 362 of file inliner.c.
extractor_command_info()
void extractor_command_info (char * sDir, int ignore, char * sFunc)
Definition at line 139 of file inliner.c.
References load_TOC(), and store_funcname().
extractor_end()
void extractor_end (void)
Definition at line 429 of file inliner.c.
extractor_possible()
int extractor_possible (void)
Definition at line 151 of file inliner.c.
References ccff_info(), STB::curr_scope, DTY, FALSE, STB::firstusym, gbl, MSGNEGINLINER, NOSYM, NULL, fitem::pfiNext, pfiStart, RU_FUNC, RU_SUBR, fitem::sFunc, sptr, ST_ISVAR, stb, std, STD_AST, STD_NEXT, SYMNAME, TRACE0, TRACE1, TRUE, TY_CHAR, TY_NCHAR, and XBIT.
Referenced by extractor().
inline_add_func()
void inline_add_func (char * sFunc, int nSize)
Definition at line 469 of file inliner.c.
References n, nLevels, and store_funcname().
inline_add_lib()
void inline_add_lib (char * sDir)
Definition at line 463 of file inliner.c.
References load_TOC().
inliner()
void inliner (void)
Definition at line 483 of file inliner.c.
References DBGBIT, dump_std(), flg, gbl, inline_stds(), ninlined, nLevels, nskip, sExtDir, STD_NEXT, STD_PREV, FLG::x, and XBIT.