flang: inquire.c File Reference
inquire.c File Reference
Implements Fortran INQUIRE statement.
#include <stdarg.h>
#include <string.h>
#include "global.h"
#include "async.h"
Macros
#define SINTN 64 /* max number of return ints */
Functions
static void copystr (char *dst, int len, const char *src)
static int inquire (__INT_T *unit, char *file_ptr, __INT_T *bitv, __INT_T *iostat, bool *exist, bool *opened, __INT8_T *number, bool *named, char *name_ptr, char *acc_ptr, char *sequential_ptr, char *direct_ptr, char *form_ptr, char *formatted_ptr, char *unformatted_ptr, __INT8_T *recl, __INT8_T *nextrec, char *blank_ptr, char *position_ptr, char *action_ptr, char *read_ptr, char *write0_ptr, char *readwrite_ptr, char *delim_ptr, char *pad_ptr, __INT_T *id, __INT_T *pending, __INT8_T *pos, __INT8_T *size, char *asynchronous_ptr, char *decimal_ptr, char *encoding_ptr, char *sign_ptr, char *stream_ptr, char *round_ptr, __CLEN_T file_siz, __CLEN_T name_siz, __CLEN_T acc_siz, __CLEN_T sequential_siz, __CLEN_T direct_siz, __CLEN_T form_siz, __CLEN_T formatted_siz, __CLEN_T unformatted_siz, __CLEN_T blank_siz, __CLEN_T position_siz, __CLEN_T action_siz, __CLEN_T read_siz, __CLEN_T write0_siz, __CLEN_T readwrite_siz, __CLEN_T delim_siz, __CLEN_T pad_siz, int asynchronous_siz, int decimal_siz, int encoding_siz, int sign_siz, int stream_siz, int round_siz)
int ENTF90IO (INQUIREA, inquirea)
int ENTF90IO (INQUIRE, inquire)
int ENTF90IO (INQUIRE2003A, inquire2003a)
int ENTF90IO (INQUIRE2003, inquire2003)
int ENTCRF90IO (INQUIREa, inquirea)
int ENTCRF90IO (INQUIRE, inquire)
int ENTCRF90IO (INQUIRE2003A, inquire2003a)
int ENTCRF90IO (INQUIRE2003, inquire2003)
__INT_T (__INT_T *istat, __INT_T *id, __INT_T *pending, __INT8_T *pos, __INT_T *size, DCHAR(asynchronous), DCHAR(decimal), DCHAR(encoding), DCHAR(sign), DCHAR(stream) DCLEN64(asynchronous) DCLEN64(decimal) DCLEN64(encoding) DCLEN64(sign) DCLEN64(stream))
__INT_T (__INT_T *istat, __INT_T *id, __INT_T *pending, __INT8_T *pos, __INT_T *size, DCHAR(asynchronous), DCHAR(decimal), DCHAR(encoding), DCHAR(sign), DCHAR(stream) DCLEN(asynchronous) DCLEN(decimal) DCLEN(encoding) DCLEN(sign) DCLEN(stream))
__INT_T ENTF90IO (INQUIRE03A, inquire03a)
__INT_T ENTF90IO (INQUIRE03, inquire03)
__INT_T (__INT_T *unit, DCHAR(file), __INT_T *bitv, __INT_T *iostat, bool *exist, bool *opened, __INT8_T *number, bool *named, DCHAR(name), DCHAR(acc), DCHAR(sequential), DCHAR(direct), DCHAR(form), DCHAR(formatted), DCHAR(unformatted), __INT8_T *recl, __INT8_T *nextrec, DCHAR(blank), DCHAR(position), DCHAR(action), DCHAR(read), DCHAR(write0), DCHAR(readwrite), DCHAR(delim), DCHAR(pad), __INT_T *id, __INT_T *pending, __INT8_T *pos, __INT8_T *size, DCHAR(asynchronous), DCHAR(decimal), DCHAR(encoding), DCHAR(sign), DCHAR(stream), DCHAR(round) DCLEN64(file) DCLEN64(name) DCLEN64(acc) DCLEN64(sequential) DCLEN64(direct) DCLEN64(form) DCLEN64(formatted) DCLEN64(unformatted) DCLEN64(blank) DCLEN64(position) DCLEN64(action) DCLEN64(read) DCLEN64(write0) DCLEN64(readwrite) DCLEN64(delim) DCLEN64(pad) DCLEN64(asynchronous) DCLEN64(decimal) DCLEN64(encoding) DCLEN64(sign) DCLEN64(stream) DCLEN64(round))
__INT_T (__INT_T *unit, DCHAR(file), __INT_T *bitv, __INT_T *iostat, bool *exist, bool *opened, __INT8_T *number, bool *named, DCHAR(name), DCHAR(acc), DCHAR(sequential), DCHAR(direct), DCHAR(form), DCHAR(formatted), DCHAR(unformatted), __INT8_T *recl, __INT8_T *nextrec, DCHAR(blank), DCHAR(position), DCHAR(action), DCHAR(read), DCHAR(write0), DCHAR(readwrite), DCHAR(delim), DCHAR(pad), __INT_T *id, __INT_T *pending, __INT8_T *pos, __INT8_T *size, DCHAR(asynchronous), DCHAR(decimal), DCHAR(encoding), DCHAR(sign), DCHAR(stream), DCHAR(round) DCLEN(file) DCLEN(name) DCLEN(acc) DCLEN(sequential) DCLEN(direct) DCLEN(form) DCLEN(formatted) DCLEN(unformatted) DCLEN(blank) DCLEN(position) DCLEN(action) DCLEN(read) DCLEN(write0) DCLEN(readwrite) DCLEN(delim) DCLEN(pad) DCLEN(asynchronous) DCLEN(decimal) DCLEN(encoding) DCLEN(sign) DCLEN(stream) DCLEN(round))
Variables
static FIO_FCB * f2
Detailed Description
Implements Fortran INQUIRE statement.
Definition in file inquire.c.
Macro Definition Documentation
SINTN
#define SINTN 64 /* max number of return ints */
Definition at line 36 of file inquire.c.
Function Documentation
__INT_T() [1/4]
__INT_T (__INT_T * istat, __INT_T * id, __INT_T * pending, __INT8_T * pos, __INT_T * size, DCHAR(asynchronous) , DCHAR(decimal) , DCHAR(encoding) , DCHAR(sign) , DCHAR(stream) DCLEN(asynchronous) DCLEN(decimal) DCLEN(encoding) DCLEN(sign) DCLEN(stream))
Definition at line 1542 of file inquire.c.
References __CLEN_T, CADR, CLEN, ENTF90IO(), pos, sign, and size.
__INT_T() [2/4]
__INT_T (__INT_T * istat, __INT_T * id, __INT_T * pending, __INT8_T * pos, __INT_T * size, DCHAR(asynchronous) , DCHAR(decimal) , DCHAR(encoding) , DCHAR(sign) , DCHAR(stream) DCLEN64(asynchronous) DCLEN64(decimal) DCLEN64(encoding) DCLEN64(sign) DCLEN64(stream))
Definition at line 1449 of file inquire.c.
References __fortio_error(), __io_errno(), __io_fseek, __io_ftellx, fcb::acc, fcb::asyptr, CADR, CLEN, copystr(), cp, currpos, fcb::decimal, fcb::encoding, f, f2, FIO_COMMA, FIO_FORMATTED, FIO_PLUS, FIO_POINT, FIO_STREAM, FIO_SUPPRESS, FIO_UTF_8, fcb::form, fcb::fp, FTN_FALSE, ISPRESENTC, NULL, pos, sign, fcb::sign, and size.
Referenced by ENTCRF90IO(), and ENTF90IO().
__INT_T() [3/4]
__INT_T (__INT_T * unit, DCHAR(file) , __INT_T * bitv, __INT_T * iostat, bool * exist, bool * opened, __INT8_T * number, bool * named, DCHAR(name) , DCHAR(acc) , DCHAR(sequential) , DCHAR(direct) , DCHAR(form) , DCHAR(formatted) , DCHAR(unformatted) , __INT8_T * recl, __INT8_T * nextrec, DCHAR(blank) , DCHAR(position) , DCHAR(action) , DCHAR(read) , DCHAR(write0) , DCHAR(readwrite) , DCHAR(delim) , DCHAR(pad) , __INT_T * id, __INT_T * pending, __INT8_T * pos, __INT8_T * size, DCHAR(asynchronous) , DCHAR(decimal) , DCHAR(encoding) , DCHAR(sign) , DCHAR(stream) , DCHAR(round) DCLEN(file) DCLEN(name) DCLEN(acc) DCLEN(sequential) DCLEN(direct) DCLEN(form) DCLEN(formatted) DCLEN(unformatted) DCLEN(blank) DCLEN(position) DCLEN(action) DCLEN(read) DCLEN(write0) DCLEN(readwrite) DCLEN(delim) DCLEN(pad) DCLEN(asynchronous) DCLEN(decimal) DCLEN(encoding) DCLEN(sign) DCLEN(stream) DCLEN(round))
Definition at line 2534 of file inquire.c.
References __CLEN_T, bitv, CADR, CLEN, delim, direct, ENTF90IO(), exist, name, opened, pos, read, round(), sign, and size.
__INT_T() [4/4]
__INT_T (__INT_T * unit, DCHAR(file) , __INT_T * bitv, __INT_T * iostat, bool * exist, bool * opened, __INT8_T * number, bool * named, DCHAR(name) , DCHAR(acc) , DCHAR(sequential) , DCHAR(direct) , DCHAR(form) , DCHAR(formatted) , DCHAR(unformatted) , __INT8_T * recl, __INT8_T * nextrec, DCHAR(blank) , DCHAR(position) , DCHAR(action) , DCHAR(read) , DCHAR(write0) , DCHAR(readwrite) , DCHAR(delim) , DCHAR(pad) , __INT_T * id, __INT_T * pending, __INT8_T * pos, __INT8_T * size, DCHAR(asynchronous) , DCHAR(decimal) , DCHAR(encoding) , DCHAR(sign) , DCHAR(stream) , DCHAR(round) DCLEN64(file) DCLEN64(name) DCLEN64(acc) DCLEN64(sequential) DCLEN64(direct) DCLEN64(form) DCLEN64(formatted) DCLEN64(unformatted) DCLEN64(blank) DCLEN64(position) DCLEN64(action) DCLEN64(read) DCLEN64(write0) DCLEN64(readwrite) DCLEN64(delim) DCLEN64(pad) DCLEN64(asynchronous) DCLEN64(decimal) DCLEN64(encoding) DCLEN64(sign) DCLEN64(stream) DCLEN64(round))
Definition at line 2115 of file inquire.c.
References __CHAR, __CINT, __CLEN_T, __fort_free(), __fort_malloc(), __fortio_errend03(), __INT8, bitv, CADR, CLEN, delim, direct, DIST_RBCST, exist, FIO_BITV_IOSTAT, GET_DIST_IOPROC, GET_DIST_LCPU, inquire(), ISPRESENT, ISPRESENTC, LOCAL_MODE, name, NULL, opened, pos, read, round(), s, sign, SINTN, and size.
copystr()
static void copystr (char * dst, int len, const char * src) static
Definition at line 25 of file inquire.c.
References end, len, and src.
Referenced by __INT_T(), and inquire().
ENTCRF90IO() [1/4]
int ENTCRF90IO (INQUIRE , inquire)
Definition at line 1281 of file inquire.c.
References __CLEN_T, bitv, CADR, CLEN, delim, direct, ENTCRF90IO(), exist, name, opened, and read.
ENTCRF90IO() [2/4]
int ENTCRF90IO (INQUIRE2003 , inquire2003)
Definition at line 1419 of file inquire.c.
References __CLEN_T, bitv, CADR, CLEN, delim, direct, ENTCRF90IO(), exist, name, opened, and read.
ENTCRF90IO() [3/4]
int ENTCRF90IO (INQUIRE2003A , inquire2003a)
Definition at line 1310 of file inquire.c.
References __CLEN_T, __fortio_errend03(), bitv, CADR, CLEN, delim, direct, exist, inquire(), ISPRESENTC, name, NULL, opened, read, and s.
ENTCRF90IO() [4/4]
int ENTCRF90IO (INQUIREa , inquirea)
Definition at line 1163 of file inquire.c.
References __CLEN_T, __fortio_errend03(), __INT_T(), bitv, CADR, CLEN, delim, direct, exist, inquire(), ISPRESENT, ISPRESENTC, name, NULL, opened, read, and s.
Referenced by ENTCRF90IO().
ENTF90IO() [1/6]
int ENTF90IO (INQUIRE , inquire)
Definition at line 779 of file inquire.c.
References __CLEN_T, bitv, CADR, CLEN, delim, direct, ENTF90IO(), exist, name, opened, and read.
ENTF90IO() [2/6]
__INT_T ENTF90IO (INQUIRE03 , inquire03)
Definition at line 2031 of file inquire.c.
References __CLEN_T, bitv, CADR, CLEN, delim, direct, ENTF90IO(), exist, name, opened, pos, read, round(), sign, and size.
ENTF90IO() [3/6]
__INT_T ENTF90IO (INQUIRE03A , inquire03a)
Definition at line 1560 of file inquire.c.
References __CHAR, __CINT, __CLEN_T, __fort_free(), __fort_malloc(), __fortio_errend03(), __INT8, __INT_T(), bitv, CADR, CLEN, delim, direct, DIST_RBCST, exist, FIO_BITV_IOSTAT, GET_DIST_IOPROC, GET_DIST_LCPU, inquire(), ISPRESENT, ISPRESENTC, LOCAL_MODE, name, NULL, opened, pos, read, round(), s, sign, SINTN, and size.
ENTF90IO() [4/6]
int ENTF90IO (INQUIRE2003 , inquire2003)
Definition at line 1136 of file inquire.c.
References __CLEN_T, bitv, CADR, CLEN, delim, direct, ENTF90IO(), exist, name, opened, and read.
ENTF90IO() [5/6]
int ENTF90IO (INQUIRE2003A , inquire2003a)
Definition at line 808 of file inquire.c.
References __CHAR, __CINT, __CLEN_T, __fort_free(), __fort_malloc(), __fortio_errend03(), __INT_T(), bitv, CADR, CLEN, delim, direct, DIST_RBCST, exist, FIO_BITV_IOSTAT, GET_DIST_IOPROC, GET_DIST_LCPU, inquire(), ISPRESENT, ISPRESENTC, LOCAL_MODE, name, NULL, opened, read, s, and SINTN.
ENTF90IO() [6/6]
int ENTF90IO (INQUIREA , inquirea)
Definition at line 451 of file inquire.c.
References __CHAR, __CINT, __CLEN_T, __fort_free(), __fort_malloc(), __fortio_errend03(), __INT_T(), bitv, CADR, CLEN, delim, direct, DIST_RBCST, exist, FIO_BITV_IOSTAT, GET_DIST_IOPROC, GET_DIST_LCPU, inquire(), ISPRESENT, ISPRESENTC, LOCAL_MODE, name, NULL, opened, read, s, and SINTN.
Referenced by __INT_T(), and ENTF90IO().
inquire()
static int inquire (__INT_T * unit, char * file_ptr, __INT_T * bitv, __INT_T * iostat, bool * exist, bool * opened, __INT8_T * number, bool * named, char * name_ptr, char * acc_ptr, char * sequential_ptr, char * direct_ptr, char * form_ptr, char * formatted_ptr, char * unformatted_ptr, __INT8_T * recl, __INT8_T * nextrec, char * blank_ptr, char * position_ptr, char * action_ptr, char * read_ptr, char * write0_ptr, char * readwrite_ptr, char * delim_ptr, char * pad_ptr, __INT_T * id, __INT_T * pending, __INT8_T * pos, __INT8_T * size, char * asynchronous_ptr, char * decimal_ptr, char * encoding_ptr, char * sign_ptr, char * stream_ptr, char * round_ptr, __CLEN_T file_siz, __CLEN_T name_siz, __CLEN_T acc_siz, __CLEN_T sequential_siz, __CLEN_T direct_siz, __CLEN_T form_siz, __CLEN_T formatted_siz, __CLEN_T unformatted_siz, __CLEN_T blank_siz, __CLEN_T position_siz, __CLEN_T action_siz, __CLEN_T read_siz, __CLEN_T write0_siz, __CLEN_T readwrite_siz, __CLEN_T delim_siz, __CLEN_T pad_siz, int asynchronous_siz, int decimal_siz, int encoding_siz, int sign_siz, int stream_siz, int round_siz) static
Definition at line 41 of file inquire.c.
References __CLEN_T, __fort_access, __fortio_errinit03(), __fortio_error(), __fortio_find_unit(), __io_errno(), __io_fclose, __io_fopen, __io_fseek, __io_ftellx, fcb::acc, fcb::action, fcb::asy_rw, fcb::asyptr, bitv, fcb::blank, copystr(), cp, currpos, fcb::decimal, fcb::delim, fcb::encoding, exist, f, f2, FIO_TBL::fcbs, FILE, FIO_APOSTROPHE, FIO_APPEND, Fio_asy_disable(), FIO_COMMA, FIO_COMPATIBLE, FIO_DIRECT, FIO_DOWN, FIO_FORMATTED, FIO_NEAREST, FIO_NULL, FIO_PLUS, FIO_POINT, FIO_PROCESSOR_DEFINED, FIO_QUOTE, FIO_READ, FIO_READWRITE, FIO_REWIND, FIO_SEQUENTIAL, FIO_STAT_INTERNAL_UNIT, FIO_STREAM, FIO_SUPPRESS, FIO_UP, FIO_UTF_8, FIO_WRITE, FIO_YES, FIO_ZERO, fioFcbTbls, fcb::form, fcb::fp, FTN_FALSE, FTN_TRUE, i, ILLEGAL_UNIT, len, malloc(), MAX_NAMELEN, fcb::name, fcb::named, fcb::next, fcb::nextrec, NULL, opened, fcb::pad, fcb::pos, pos, fcb::reclen, fcb::round, fcb::sign, size, strlen(), tmpnam(), fcb::unit, void(), and fcb::wordlen.
Referenced by __INT_T(), ENTCRF90IO(), and ENTF90IO().
Variable Documentation
f2
FIO_FCB* f2 static
Definition at line 23 of file inquire.c.
Referenced by __INT_T(), chk_overlap(), ENTF90(), export_one_ast(), export_symbol(), fill_ast(), fill_ST_MODULE(), fill_sym(), inquire(), mth_i_alog(), mth_i_dlog(), mth_i_log(), qscmp(), symdentry(), xfadd(), xfatan2(), xfcmp(), xfdiv(), xfmul(), xfpow(), and xfsub().