flang: int128.c File Reference
int128.c File Reference
Implement 128-bit integer operations.
#include "int128.h"
#include <assert.h>
#include <stdbool.h>
#include <stdint.h>
Macros
#define MSB32 0x80000000
Functions
void int128_from_uint64 (int128_t *result, uint64_t x)
void int128_from_int64 (int128_t *result, int64_t x)
bool int128_to_uint64 (uint64_t *result, const int128_t *x)
bool int128_to_int64 (int64_t *result, const int128_t *x)
int int128_unsigned_compare (const int128_t *x, const int128_t *y)
int int128_signed_compare (const int128_t *x, const int128_t *y)
int int128_count_leading_zeros (const int128_t *x)
void int128_ones_complement (int128_t *result, const int128_t *x)
bool int128_twos_complement (int128_t *result, const int128_t *x)
void int128_and (int128_t *result, const int128_t *x, const int128_t *y)
void int128_or (int128_t *result, const int128_t *x, const int128_t *y)
void int128_xor (int128_t *result, const int128_t *x, const int128_t *y)
void int128_shift_left (int128_t *result, const int128_t *x, int count)
void int128_shift_right_logical (int128_t *result, const int128_t *x, int count)
bool int128_unsigned_add (int128_t *result, const int128_t *x, const int128_t *y)
bool int128_signed_add (int128_t *result, const int128_t *x, const int128_t *y)
bool int128_signed_subtract (int128_t *result, const int128_t *x, const int128_t *y)
void int128_unsigned_multiply (int128_t *high, int128_t *low, const int128_t *x, const int128_t *y)
void int128_signed_multiply (int128_t *high, int128_t *low, const int128_t *x, const int128_t *y)
bool int128_unsigned_divide (int128_t *quotient, int128_t *remainder, const int128_t *dividend, const int128_t *divisor)
bool int128_signed_divide (int128_t *quotient, int128_t *remainder, const int128_t *dividend, const int128_t *divisor)
Variables
static const int128_t zero = { { 0, 0, 0, 0 } }
static const int128_t one = { { 1, 0, 0, 0 } }
Detailed Description
Implement 128-bit integer operations.
Wraps GCC's __int128 with portable interfaces when __int128 is available; implements 128-bit integer arithmetic with 64-bit operations when it is not.
Definition in file int128.c.
Macro Definition Documentation
MSB32
#define MSB32 0x80000000
Definition at line 166 of file int128.c.
Function Documentation
int128_and()
void int128_and (int128_t * result, const int128_t * x, const int128_t * y)
Definition at line 263 of file int128.c.
References j, result, x, and y.
int128_count_leading_zeros()
int int128_count_leading_zeros (const int128_t * x)
Definition at line 230 of file int128.c.
References assert, j, k, MSB32, w, and x.
Referenced by int128_unsigned_divide().
int128_from_int64()
void int128_from_int64 (int128_t * result, int64_t x)
Definition at line 180 of file int128.c.
References result, and x.
Referenced by unwrap_i128().
int128_from_uint64()
void int128_from_uint64 (int128_t * result, uint64_t x)
Definition at line 172 of file int128.c.
References result, and x.
Referenced by unwrap_i128().
int128_ones_complement()
void int128_ones_complement (int128_t * result, const int128_t * x)
Definition at line 247 of file int128.c.
References j, and result.
Referenced by int128_signed_multiply(), and int128_twos_complement().
int128_or()
void int128_or (int128_t * result, const int128_t * x, const int128_t * y)
Definition at line 272 of file int128.c.
References j, result, x, and y.
Referenced by unwrap_i128().
int128_shift_left()
void int128_shift_left (int128_t * result, const int128_t * x, int count)
Definition at line 290 of file int128.c.
References assert, count, j, off, result, and x.
Referenced by int128_unsigned_divide(), shf128(), and unwrap_i128().
int128_shift_right_logical()
void int128_shift_right_logical (int128_t * result, const int128_t * x, int count)
Definition at line 317 of file int128.c.
References assert, count, j, off, result, and x.
Referenced by shf128(), and wrap_i128().
int128_signed_add()
bool int128_signed_add (int128_t * result, const int128_t * x, const int128_t * y)
Definition at line 357 of file int128.c.
References int128_unsigned_add(), MSB32, result, x, and y.
Referenced by int128_signed_subtract(), and int128_twos_complement().
int128_signed_compare()
int int128_signed_compare (const int128_t * x, const int128_t * y)
Definition at line 216 of file int128.c.
References int128_unsigned_compare(), MSB32, x, and y.
Referenced by cmp128(), int128_signed_divide(), and int128_signed_multiply().
int128_signed_divide()
bool int128_signed_divide (int128_t * quotient, int128_t * remainder, const int128_t * dividend, const int128_t * divisor)
Definition at line 469 of file int128.c.
References int128_signed_compare(), int128_twos_complement(), int128_unsigned_divide(), num, remainder, tmp, and zero.
Referenced by div128().
int128_signed_multiply()
void int128_signed_multiply (int128_t * high, int128_t * low, const int128_t * x, const int128_t * y)
Definition at line 413 of file int128.c.
References int128_ones_complement(), int128_signed_compare(), int128_twos_complement(), int128_unsigned_add(), int128_unsigned_multiply(), one, x, xneg, y, and zero.
Referenced by mul128l().
int128_signed_subtract()
bool int128_signed_subtract (int128_t * result, const int128_t * x, const int128_t * y)
Definition at line 364 of file int128.c.
References int128_signed_add(), int128_twos_complement(), result, tmp, x, and y.
Referenced by int128_unsigned_divide(), and sub128().
int128_to_int64()
bool int128_to_int64 (int64_t * result, const int128_t * x)
Definition at line 195 of file int128.c.
References result, and x.
Referenced by wrap_i128().
int128_to_uint64()
bool int128_to_uint64 (uint64_t * result, const int128_t * x)
Definition at line 188 of file int128.c.
References result, and x.
int128_twos_complement()
bool int128_twos_complement (int128_t * result, const int128_t * x)
Definition at line 256 of file int128.c.
References int128_ones_complement(), int128_signed_add(), one, result, and x.
Referenced by int128_signed_divide(), int128_signed_multiply(), and int128_signed_subtract().
int128_unsigned_add()
bool int128_unsigned_add (int128_t * result, const int128_t * x, const int128_t * y)
Definition at line 344 of file int128.c.
References carry(), j, result, x, and y.
Referenced by add128(), int128_signed_add(), int128_signed_multiply(), and int128_unsigned_divide().
int128_unsigned_compare()
int int128_unsigned_compare (const int128_t * x, const int128_t * y)
Definition at line 203 of file int128.c.
References j, x, and y.
Referenced by int128_signed_compare(), and int128_unsigned_divide().
int128_unsigned_divide()
bool int128_unsigned_divide (int128_t * quotient, int128_t * remainder, const int128_t * dividend, const int128_t * divisor)
Definition at line 438 of file int128.c.
References bits, int128_count_leading_zeros(), int128_shift_left(), int128_signed_subtract(), int128_unsigned_add(), int128_unsigned_compare(), one, remainder, tmp, top, and zero.
Referenced by int128_signed_divide().
int128_unsigned_multiply()
void int128_unsigned_multiply (int128_t * high, int128_t * low, const int128_t * x, const int128_t * y)
Definition at line 372 of file int128.c.
References for(), j, k, int128_t::part, res, x, and y.
Referenced by int128_signed_multiply().
int128_xor()
void int128_xor (int128_t * result, const int128_t * x, const int128_t * y)
Definition at line 281 of file int128.c.
References j, result, x, and y.
Variable Documentation
one
const int128_t one = { { 1, 0, 0, 0 } } static
Definition at line 169 of file int128.c.
Referenced by int128_signed_multiply(), int128_twos_complement(), and int128_unsigned_divide().
zero
const int128_t zero = { { 0, 0, 0, 0 } } static
Definition at line 168 of file int128.c.
Referenced by int128_signed_divide(), int128_signed_multiply(), and int128_unsigned_divide().