flang: interf.c File Reference
interf.c File Reference
Routines for importing symbols from .mod files and from IPA.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "dtypeutl.h"
#include "machar.h"
#include "semant.h"
#include "ast.h"
#include "dinit.h"
#include "soc.h"
#include "state.h"
#include "lz.h"
#include "rtlRtns.h"
#include "interf.h"
#include "trace.h"
#include "fih.h"
#include "symutl.h"
#include "lower.h"
#include "extern.h"
Classes
struct DITEM
struct symitem
struct alnitem
struct dstitem
struct ASTITEM
struct STDITEM
struct SHDITEM
struct ARGTITEM
struct ASDITEM
struct ASTLIITEM
struct MODPITEM
struct uses_list
struct to_be_imported
Macros
#define INSIDE_INTERF
#define INTERFH_RCSID
#define TRACEFLAG 48
#define TRACEBIT 1
#define TRACESTRING "interf-"
#define MAX_FNAME_LEN 2050
#define MOD_SUFFIX ".mod"
#define MOD_AREA 18
#define PERM_AREA 8
#define MOD_USE_AREA 4
#define MN_NENTRIES 2
#define ASTZHASHSIZE 1024
#define ASTZHASHMASK 0x03ff
#define SYMHASHSIZE 521
#define DTHASHSIZE 521
#define BUFF_LEN 4096
#define READ_LINE p = read_line(fd)
#define READ_LZLINE currp = p = ulz(fdlz)
#define IMPORT_WHICH_PRELINK -1
#define IMPORT_WHICH_IPA -2
#define IMPORT_WHICH_INLINE -3
#define IMPORT_WHICH_HOST -4
#define IMPORT_WHICH_NESTED -5
#define GETFIELD(f) ps->sym.f = get_num(10)
#define GETFIELD(f) astb.stg_base[0].f = pa->a.f
#define GETBIT(f)
#define GETBIT(f)
#define GETBIT(f)
#define GETFIELD(f) stb.stg_base[sptr].f = ps->sym.f
Typedefs
typedef struct symitem SYMITEM
typedef struct alnitem ALNITEM
typedef struct dstitem DSTITEM
typedef struct uses_list USES_LIST
typedef struct to_be_imported TOBE_IMPORTED_LIST
Functions
static void put_dinit_record (int ptype, INT pcon)
Change symbol number, if necessary, and write record to data init file.
static void put_data_statement (int, int, int, lzhandle *, const char *, int)
static int import_mk_newsym (char *name, int stype)
void interf_init ()
'interface' initialization, called once per compilation (source file).
static char * read_line (FILE *)
static ISZ_T get_num (int)
static void get_string (char *)
static void get_nstring (char *dest, int len)
read 'len' characters
static void new_dtypes (void)
static int new_dtype (int)
static void new_asts (void)
static int new_ast (int)
static void new_stds (void)
static int new_std (int)
static int new_argt (int offset)
Look up an (old) argt.
static int new_asd (int offset)
Look up an (old) asd.
static int new_astli (int offset, int atype)
Look up an (old) ast list.
static int new_shape (int offset)
Look up an (old) shd.
static int new_symbol (int)
static int new_symbol_if_module (int old_sptr)
static void new_symbol_and_link (int, int *, SYMITEM **)
static void fill_links_symbol (SYMITEM *ps, WantPrivates wantPrivates)
Fill DTYPE, and symbol links to other symbol links.
static int can_find_symbol (int)
static int can_find_dtype (int)
static int new_installed_dtype (int old_dt)
static DITEM * finddthash (int old_dt)
static void import_constant (SYMITEM *ps)
static void import_symbol (SYMITEM *ps)
static void import_ptr_constant (SYMITEM *ps)
static void import (lzhandle *fdlz, WantPrivates wantPrivates, int ivsn)
This is the main module import function.
static int import_skip_use_stmts (lzhandle *fdlz)
Look for any 'use' statements and skip over them.
static void import_done (lzhandle *, int nested)
static lzhandle * import_header_only (FILE *fd, const char *file_name, int import_which, int *ivsn_return)
static void get_component_init (lzhandle *, const char *, char *, int)
void import_init (void)
Initialize import of module symbols, etc.
void import_fini (void)
Wrap-up module symbol import phase.
static void add_imported (int modulesym)
static void set_message (int import_which, const char *file_name)
static int import_use_stmts (lzhandle *fdlz, TOBE_IMPORTED_LIST *, const char *, int, int)
static int get_module_file_name_from_user (TOBE_IMPORTED_LIST *il, const char *from_file_name)
static void dump_list_node (USES_LIST *node, int indent)
void dump_use_tree (void)
void init_use_tree (void)
void remove_from_use_tree (char *module)
static TOBE_IMPORTED_LIST * already_to_be_used (char *modulename, int public, int except)
static void clear_list_nodes_visited (USES_LIST *list)
Clear visited nodes in the module use_tree.
static USES_LIST * find_next_modname_in_list (char *name, USES_LIST *list)
static TOBE_IMPORTED_LIST * find_modname_in_list (char *name, USES_LIST *list)
Search list on name (only)
static TOBE_IMPORTED_LIST * find_use_node_in_list (char *name, int exception, USES_LIST *ul)
Search list for use node using name and exception list.
LOGICAL imported_directly (char *name, int except)
static void add_to_use_tree (TOBE_IMPORTED_LIST *um)
Add a TOBE_IMPORTED_LIST item to the end of the use_tree list.
static TOBE_IMPORTED_LIST * insert_node_into_use_tree (char *modulename)
Create and insert a TOBE_IMPORTED_LIST item into the beginning of the use_tree.
static USES_LIST ** add_use_tree_uses (USES_LIST **curr_use_list, TOBE_IMPORTED_LIST *il)
Add il into curr_use_list after *curr_use_list item.
static TOBE_IMPORTED_LIST * add_to_be_used_list (char *modulename, int public, int except, TOBE_IMPORTED_LIST *ilfrom, const char *from_file_name)
static int alreadyused (char *modulename)
static void add_use_edge (TOBE_IMPORTED_LIST *ilfrom, TOBE_IMPORTED_LIST *il, int directlyused)
static void update_list_exceptions (USES_LIST *list)
void update_use_tree_exceptions (void)
int get_module_file_name (char *module_file_name, char *full_file_name, int len)
static void topsort (TOBE_IMPORTED_LIST *il)
static int sym_visible_in_scope (USES_LIST *list, int sptrsym, char *symscopenm)
static LOGICAL scope_in_scope_stack (int sptr)
int aliased_sym_visible (int sptralias)
Determine if there is a path through the USEs that makes the symbol aliased by sptralias visible.
static LOGICAL alias_may_need_adjustment (int sptralias, int currmod)
void adjust_symbol_accessibility (int currmod)
static void do_nested_uses (WantPrivates wantPrivates)
static void addmodfile (const char *filename)
Add .mod file to list of .mod files used.
static lzhandle * import_header (FILE *fd, const char *file_name, int import_which, int *ivsn_return)
static int find_nmptr (char *symname)
Find a NMPTR that shares NMPTR for different symbols with the same name.
static int find_member_name (char *symname, int stype, int scopesym, int offset)
static void inithash (void)
static void inserthash (int sptr, SYMITEM *ps)
static SYMITEM * findhash (int sptr)
static void insertdthash (int old_dt, int d)
static int adjust_pre34_dty (int dty)
static int adjust_pre34_dtype (int dtype)
int import_inline (FILE *fd, char *file_name)
int import_static (FILE *fd, char *file_name)
import a routine for static analysis
SPTR import_module (FILE *fd, char *file_name, SPTR modsym, WantPrivates wantPrivates, int scope_level)
This is called either for a USE statement, or to import the specification part of a module for the contained subprograms.
void import_module_end (void)
void import_module_print (void)
void import_host (FILE *fd, const char *file_name, int oldsymavl, int oldastavl, int olddtyavl, int modbase, int moddiff, int oldscope, int newscope)
This is called to restore symbol table, etc., data for contained subprograms.
void export_fix_host_append_list (int(*)(int))
void import_host_subprogram (FILE *fd, const char *file_name, int oldsymavl, int oldastavl, int olddtyavl, int modbase, int moddiff)
This is called to restore symbol table, etc., data for contained subprograms.
static int ipa_ast (int a)
static int dindex (int dtype)
static int get_symbolxref (int sptr)
static VAR * getivl (lzhandle *fdlz, const char *file_name, int ipa)
static ACL * getict (lzhandle *fdlz, const char *file_name, int ipa)
static int install_dtype (DITEM *pd)
static int fill_ast (ASTITEM *pa)
static void fill_ST_MODULE (SYMITEM *ps, int sptr)
static void fill_sym (SYMITEM *ps, int sptr)
void rw_import_state (RW_ROUTINE, RW_FILE)
Variables
static LOGICAL inmodulecontains = FALSE
static int for_module = 0
static LOGICAL for_inliner = FALSE
static LOGICAL for_interproc = FALSE
static LOGICAL for_static = FALSE
static LOGICAL for_host = FALSE
static LOGICAL old_astversion = FALSE
static int top_scope_level = 0
static int import_errno = 0
static int import_osym = 0
static int BASEsym
static int BASEast
static int BASEdty
static int BASEmod
static int ADJmod
static int HOST_OLDSCOPE = 0
static int HOST_NEWSCOPE = 0
static char ** modinclist = NULL
static int modinclistsize = 0
static int modinclistavl = 0
struct {
DITEM * base
int avl
int sz
} dtz
struct {
int * base
int avl
int sz
} flz
struct {
int * base
int avl
int sz
} ovz
struct {
int * base
int avl
int sz
} mdz
struct {
ASTITEM * base
int avl
int sz
} astz
static int astzhash [ASTZHASHSIZE]
struct {
STDITEM * base
int avl
int sz
} stdz
struct {
SHDITEM * base
int avl
int sz
} shdz
struct {
ARGTITEM * base
int avl
int sz
} argtz
struct {
ASDITEM * base
int avl
int sz
} asdz
struct {
ASTLIITEM * base
int avl
int sz
} astliz
struct {
MODPITEM * base
int avl
int sz
} modpz
static SYMITEM * symbol_list
static ALNITEM * align_list
static DSTITEM * dist_list
static SYMITEM * symhash [SYMHASHSIZE]
static int dthash [DTHASHSIZE]
static char * buff = NULL
static int buff_sz
static char * currp
static char import_name [MAXIDLEN+1]
static int curr_platform = MOD_ANY
static char * import_sourcename = NULL
static int import_sourcename_len = 0
static LOGICAL ignore_private = FALSE
static int curr_import_findex = 0
static int dtype_ivsn = 0
static const char * import_file_name
struct imported_modules_struct imported_modules = {NULL, 0, 0, 0, 0}
static const char * import_corrupt_msg
static const char * import_oldfile_msg
static const char * import_incompatible_msg
static TOBE_IMPORTED_LIST * to_be_used_list_head
static TOBE_IMPORTED_LIST * to_be_used_list_tail
static TOBE_IMPORTED_LIST * to_be_used_list_order_head
static TOBE_IMPORTED_LIST * to_be_used_list_order_tail
static USES_LIST * use_tree = NULL
static USES_LIST * use_tree_end = NULL
static int module_base = 0
static int original_symavl = 0
static unsigned A_IDSTR_mask = (1 << 5)
static LOGICAL any_ptr_constant = FALSE
static int IPARECOMPILE = FALSE
Detailed Description
Routines for importing symbols from .mod files and from IPA.
Definition in file interf.c.
Macro Definition Documentation
ASTZHASHMASK
#define ASTZHASHMASK 0x03ff
Definition at line 240 of file interf.c.
ASTZHASHSIZE
#define ASTZHASHSIZE 1024
Definition at line 239 of file interf.c.
BUFF_LEN
#define BUFF_LEN 4096
Definition at line 288 of file interf.c.
DTHASHSIZE
#define DTHASHSIZE 521
Definition at line 285 of file interf.c.
GETBIT [1/3]
#define GETBIT (f)
Value:
  astb.std.stg_base[std].flags.bits.f = (flags & bit) ? 1 : 0; \
  bit <<= 1;
GETBIT [2/3]
#define GETBIT (f)
Value:
  stb.stg_base[0].f = (flags & bit) ? 1 : 0; \
  bit <<= 1;
GETBIT [3/3]
#define GETBIT (f)
Value:
  stb.stg_base[sptr].f = (flags & bit) ? 1 : 0; \
  bit <<= 1;
GETFIELD [1/3]
#define GETFIELD (f) ps->sym.f = get_num(10)
GETFIELD [2/3]
#define GETFIELD (f) astb.stg_base[0].f = pa->a.f
GETFIELD [3/3]
#define GETFIELD (f) stb.stg_base[sptr].f = ps->sym.f
IMPORT_WHICH_HOST
#define IMPORT_WHICH_HOST -4
Definition at line 396 of file interf.c.
IMPORT_WHICH_INLINE
#define IMPORT_WHICH_INLINE -3
Definition at line 395 of file interf.c.
IMPORT_WHICH_IPA
#define IMPORT_WHICH_IPA -2
Definition at line 394 of file interf.c.
IMPORT_WHICH_NESTED
#define IMPORT_WHICH_NESTED -5
Definition at line 397 of file interf.c.
IMPORT_WHICH_PRELINK
#define IMPORT_WHICH_PRELINK -1
Definition at line 393 of file interf.c.
INSIDE_INTERF
#define INSIDE_INTERF
Definition at line 27 of file interf.c.
INTERFH_RCSID
#define INTERFH_RCSID
Definition at line 28 of file interf.c.
MAX_FNAME_LEN
#define MAX_FNAME_LEN 2050
Definition at line 64 of file interf.c.
MN_NENTRIES
#define MN_NENTRIES 2
Definition at line 230 of file interf.c.
MOD_AREA
#define MOD_AREA 18
Definition at line 100 of file interf.c.
MOD_SUFFIX
#define MOD_SUFFIX ".mod"
Definition at line 65 of file interf.c.
MOD_USE_AREA
#define MOD_USE_AREA 4
Definition at line 102 of file interf.c.
PERM_AREA
#define PERM_AREA 8
Definition at line 101 of file interf.c.
READ_LINE
#define READ_LINE p = read_line(fd)
Definition at line 386 of file interf.c.
READ_LZLINE
#define READ_LZLINE currp = p = ulz(fdlz)
Definition at line 387 of file interf.c.
SYMHASHSIZE
#define SYMHASHSIZE 521
Definition at line 283 of file interf.c.
TRACEBIT
#define TRACEBIT 1
Definition at line 32 of file interf.c.
TRACEFLAG
#define TRACEFLAG 48
Definition at line 31 of file interf.c.
TRACESTRING
#define TRACESTRING "interf-"
Definition at line 33 of file interf.c.
Typedef Documentation
ALNITEM
typedef struct alnitem ALNITEM
DSTITEM
typedef struct dstitem DSTITEM
SYMITEM
typedef struct symitem SYMITEM
TOBE_IMPORTED_LIST
typedef struct to_be_imported TOBE_IMPORTED_LIST
USES_LIST
typedef struct uses_list USES_LIST
The USE processing builds a 'use-graph'; each module that is directly or indirectly used is a node in the graph, with an edge to all the modules used by that node. If a module is used publicly and privately, or used with different 'except' lists, each is a different node in the graph. The USE graph must be acyclic (this is checked). Each module file is read in once for each node in the graph (this could be optimized with some work to be once for each module, but we expect the effect to be small). A depth-first traversal of the graph gives a topological order of the nodes, giving a legal order in which to import the USES_LIST is the list of modules used by this module
Function Documentation
add_imported()
static void add_imported (int modulesym) static
Definition at line 369 of file interf.c.
References imported_modules_struct::avail, getitem(), imported_modules, imported_modules_struct::list, IMPORT_LIST::modulename, IMPORT_LIST::modulesym, NEED, PERM_AREA, imported_modules_struct::size, strlen(), SYMNAME, and Trace.
Referenced by do_nested_uses(), and import_module().
add_to_be_used_list()
static TOBE_IMPORTED_LIST * add_to_be_used_list (char * modulename, int public, int except, TOBE_IMPORTED_LIST * ilfrom, const char * from_file_name) static
Definition at line 708 of file interf.c.
References add_isoc_intrinsics(), already_to_be_used(), convert_2dollar_signs_to_hyphen(), DBGBIT, error(), to_be_imported::exceptlist, FALSE, to_be_imported::fullfilename, gbl, get_module_file_name(), get_module_file_name_from_user(), getitem(), MAX_FNAME_LEN, MOD_SUFFIX, MOD_USE_AREA, to_be_imported::modulefilename, to_be_imported::modulename, to_be_imported::next, NULL, to_be_imported::order, to_be_imported::prev, to_be_imported::public, to_be_imported::sl, strlen(), to_be_used_list_head, to_be_used_list_tail, to_be_imported::uses, and to_be_imported::visited.
Referenced by import_use_stmts().
add_to_use_tree()
static void add_to_use_tree (TOBE_IMPORTED_LIST * um) static
Add a TOBE_IMPORTED_LIST item to the end of the use_tree list.
Definition at line 628 of file interf.c.
References uses_list::directlyused, getitem(), MOD_USE_AREA, uses_list::next, NULL, uses_list::use_module, use_tree, and use_tree_end.
Referenced by rw_import_state().
add_use_edge()
static void add_use_edge (TOBE_IMPORTED_LIST * ilfrom, TOBE_IMPORTED_LIST * il, int directlyused) static
Definition at line 784 of file interf.c.
References uses_list::directlyused, getitem(), MOD_USE_AREA, uses_list::next, NULL, uses_list::use_module, and to_be_imported::uses.
Referenced by import_use_stmts().
add_use_tree_uses()
static USES_LIST ** add_use_tree_uses (USES_LIST ** curr_use_list, TOBE_IMPORTED_LIST * il) static
Add il into curr_use_list after *curr_use_list item.
Definition at line 689 of file interf.c.
References uses_list::directlyused, getitem(), MOD_USE_AREA, uses_list::next, NULL, tmp, and uses_list::use_module.
Referenced by import_use_stmts().
addmodfile()
static void addmodfile (const char * filename) static
Add .mod file to list of .mod files used.
Definition at line 1578 of file interf.c.
References filename, m, modinclist, modinclistavl, modinclistsize, NEED, sccalloc(), and strlen().
Referenced by import_header().
adjust_pre34_dty()
static int adjust_pre34_dty (int dty) static
Definition at line 1870 of file interf.c.
Referenced by import().
adjust_pre34_dtype()
static int adjust_pre34_dtype (int dtype) static
Definition at line 1886 of file interf.c.
Referenced by new_dtype(), and new_installed_dtype().
adjust_symbol_accessibility()
void adjust_symbol_accessibility (int currmod)
Definition at line 1104 of file interf.c.
References alias_may_need_adjustment(), aliased_sym_visible(), STB::firstosym, STB::firstusym, gbl, sptr, stb, and use_tree.
Referenced by apply_use().
alias_may_need_adjustment()
static LOGICAL alias_may_need_adjustment (int sptralias, int currmod) static
Definition at line 1049 of file interf.c.
References FALSE, gbl, SEM::interface, sem, and TRUE.
Referenced by adjust_symbol_accessibility().
aliased_sym_visible()
int aliased_sym_visible (int sptralias)
Determine if there is a path through the USEs that makes the symbol aliased by sptralias visible.
If so, return the sptr of the module containing the symbol definition or, in some cases, the sptr of the module containing the exposing alias. Otherwise return 0.
Definition at line 1018 of file interf.c.
References clear_list_nodes_visited(), scope_in_scope_stack(), sptr, sym_visible_in_scope(), SYMNAME, and use_tree.
Referenced by adjust_symbol_accessibility(), and find_def_in_most_recent_scope().
already_to_be_used()
static TOBE_IMPORTED_LIST * already_to_be_used (char * modulename, int public, int except) static
Definition at line 534 of file interf.c.
References to_be_imported::exceptlist, to_be_imported::modulename, to_be_imported::next, NULL, to_be_imported::public, same_sym_list(), and to_be_used_list_head.
Referenced by add_to_be_used_list(), and import_use_stmts().
alreadyused()
static int alreadyused (char * modulename) static
Definition at line 761 of file interf.c.
References imported_modules_struct::avail, gbl, imported_modules, imported_modules_struct::list, to_be_imported::modulename, IMPORT_LIST::modulename, IMPORT_LIST::modulesym, sptr, and SYMNAME.
Referenced by do_nested_uses(), and import_module().
can_find_dtype()
static int can_find_dtype (int old_dt) static
Definition at line 6286 of file interf.c.
References finddthash(), and pd.
Referenced by fill_links_symbol().
can_find_symbol()
static int can_find_symbol (int old_sptr) static
Definition at line 6275 of file interf.c.
References findhash().
Referenced by fill_links_symbol(), and install_dtype().
clear_list_nodes_visited()
static void clear_list_nodes_visited (USES_LIST * list) static
Clear visited nodes in the module use_tree.
Intended to operate on the use_tree only. Does not follow indirect links nor does it recurse through private modules uses.
Definition at line 557 of file interf.c.
References clear_list_nodes_visited(), uses_list::directlyused, list, uses_list::next, to_be_imported::public, uses_list::use_module, to_be_imported::uses, and to_be_imported::visited.
Referenced by aliased_sym_visible(), and clear_list_nodes_visited().
dindex()
static int dindex (int dtype) static
Definition at line 6507 of file interf.c.
References new_dtype().
Referenced by get_component_init(), getict(), and getivl().
do_nested_uses()
static void do_nested_uses (WantPrivates wantPrivates) static
Definition at line 1134 of file interf.c.
References add_imported(), alreadyused(), astb, base, BASEast, BASEdty, BASEsym, curr_scope(), STB::curr_scope, DBGBIT, error(), SCOPESTACK::except, to_be_imported::exceptlist, FALSE, fclose(), fd, FILE, ASTB::firstuast, STB::firstusym, for_host, for_module, to_be_imported::fullfilename, gbl, get_module_file_name(), getitem(), have_use_scope(), i, import_done(), import_header_only(), import_mk_newsym(), import_osym, import_skip_use_stmts(), import_use_stmts(), IMPORT_WHICH_NESTED, MAX_FNAME_LEN, MOD_SUFFIX, MOD_USE_AREA, to_be_imported::modulefilename, to_be_imported::modulename, to_be_imported::next, NULL, to_be_imported::order, pop_scope_level(), to_be_imported::public, push_scope_level(), restore_scope_level(), s, save_scope_level(), SEM::scope_level, SCOPE_USE, sem, to_be_imported::sl, stb, strlen(), SYMI_NEXT, SYMI_SPTR, to_be_used_list_head, to_be_used_list_order_head, to_be_used_list_order_tail, top_scope_level, topsort(), TRUE, and to_be_imported::visited.
Referenced by import_header().
dump_list_node()
static void dump_list_node (USES_LIST * node, int indent) static
Definition at line 481 of file interf.c.
References dump_list_node(), i, indent, and n.
Referenced by dump_list_node(), and dump_use_tree().
dump_use_tree()
void dump_use_tree (void)
Definition at line 504 of file interf.c.
References dump_list_node(), and use_tree.
export_fix_host_append_list()
void export_fix_host_append_list (int(*)(int) newsym)
Definition at line 633 of file exterf.c.
References host_append_list, newsym(), NULL, p, and Trace.
Referenced by import_host_subprogram().
fill_ast()
static int fill_ast (ASTITEM * pa) static
Definition at line 4183 of file interf.c.
References A_ARGCNTG, A_ARGCNTP, A_IDSTR_mask, A_OPTYPEG, A_OPTYPEP, A_TKNG, A_TKNP, argt, argtz, asdz, ast, astb, aux, BZERO, count, DBGBIT, AUX::dpdsc_base, STB::dt_int, DT_INT, DTY, symitem::dtype, f2, for_inliner, gbl, GETFIELD, i, import_file_name, interr(), j, AUX::list, mk_assn_stmt(), mk_binop(), mk_cmplxc(), mk_cnst(), mk_convert(), mk_id(), mk_init(), mk_label(), mk_member(), mk_paren(), mk_stmt(), mk_subscr(), mk_substr(), mk_triple(), mk_unop(), mkRteRtnNm(), new_argt(), new_asd(), new_ast(), new_astli(), new_dtype(), new_installed_dtype(), new_node(), new_shape(), new_std(), new_symbol(), new_symbol_and_link(), NULL, optype(), pa, RTE_lb, RTE_size, RTE_ub, symitem::sc, sptr, stb, std, stride, sym_mkfunc_nodesc(), Trace, type, STB::user, and void().
Referenced by new_ast(), and new_asts().
fill_links_symbol()
static void fill_links_symbol (SYMITEM * ps, WantPrivates wantPrivates) static
Fill DTYPE, and symbol links to other symbol links.
Definition at line 5699 of file interf.c.
References add_param(), assert, ast, bind_intrinsic_opr(), can_find_dtype(), can_find_symbol(), CMEMLP, CONVAL2G, CONVAL2P, DTY, symitem::dtype, end_param(), first, FLANG_FALLTHROUGH, for_host, for_inliner, for_interproc, for_module, for_static, gbl, get_type(), GSAMEG, GSAMEP, ignore_private, INCLUDE_PRIVATES, interr(), last, mem(), mk_cval(), mk_cval1(), mk_id(), module_base, new_ast(), new_dtype(), symitem::new_sptr, new_symbol(), new_symbol_if_module(), SEM::nml, nml, NML_NEXT, NML_SPTR, NOSYM, PARAMVALG, PARAMVALP, pop_sym(), symitem::sc, SYM::scope, sem, SOC_NEXT, SOC_SPTR, symitem::socptr, sptr, symitem::sptr, symitem::stype, symitem::sym, symitem::symlk, symitem::ty, TY_CHAR, TY_CMPLX, TY_DCMPLX, TY_ISWORD, and TY_NCHAR.
Referenced by import().
fill_ST_MODULE()
static void fill_ST_MODULE (SYMITEM * ps, int sptr) static
Definition at line 5061 of file interf.c.
References f2, flags, symitem::flags1, symitem::flags2, symitem::flags3, symitem::flags4, GETBIT, sptr, and stb.
Referenced by import_symbol().
fill_sym()
static void fill_sym (SYMITEM * ps, int sptr) static
Definition at line 5218 of file interf.c.
References symitem::dtype, f2, flags, symitem::flags1, symitem::flags2, symitem::flags3, symitem::flags4, GETBIT, GETFIELD, lineno, symitem::sc, scope, sptr, stb, symitem::stype, symitem::symlk, and uname.
Referenced by import_symbol().
find_member_name()
static int find_member_name (char * symname, int stype, int scopesym, int offset) static
Definition at line 1708 of file interf.c.
References base, gbl, HASH_ID, STB::hashtb, len, offset, scope, sptr, stb, strlen(), and SYMNAME.
Referenced by import().
find_modname_in_list()
static TOBE_IMPORTED_LIST * find_modname_in_list (char * name, USES_LIST * list) static
Search list on name (only)
Use ONLY if it is guaranteed that the module can be on the list only once or the first item on the list is the desired item.
Definition at line 590 of file interf.c.
References list, to_be_imported::modulename, name, uses_list::next, NULL, to_be_imported::public, and uses_list::use_module.
Referenced by import_module().
find_next_modname_in_list()
static USES_LIST * find_next_modname_in_list (char * name, USES_LIST * list) static
Definition at line 572 of file interf.c.
References list, to_be_imported::modulename, name, uses_list::next, NULL, and uses_list::use_module.
Referenced by sym_visible_in_scope().
find_nmptr()
static int find_nmptr (char * symname) static
Find a NMPTR that shares NMPTR for different symbols with the same name.
Note that putsname always inserts a new name into the name table.
Definition at line 1669 of file interf.c.
References HASH_ID, STB::hashtb, len, putsname(), stb, strlen(), and SYMNAME.
Referenced by import_constant().
find_use_node_in_list()
static TOBE_IMPORTED_LIST * find_use_node_in_list (char * name, int exception, USES_LIST * ul) static
Search list for use node using name and exception list.
Definition at line 604 of file interf.c.
References to_be_imported::exceptlist, to_be_imported::modulename, name, uses_list::next, NULL, to_be_imported::public, same_sym_list(), and uses_list::use_module.
Referenced by imported_directly().
finddthash()
static DITEM * finddthash (int old_dt) static
Definition at line 1851 of file interf.c.
References d, dthash, dtz, h, NULL, pd, and SYMHASHSIZE.
Referenced by can_find_dtype(), new_dtype(), and new_installed_dtype().
findhash()
static SYMITEM * findhash (int sptr) static
Definition at line 1829 of file interf.c.
References h, symitem::hashnext, NULL, sptr, symitem::sptr, symhash, and SYMHASHSIZE.
Referenced by can_find_symbol(), import(), new_symbol(), new_symbol_and_link(), and new_symbol_if_module().
get_component_init()
static void get_component_init (lzhandle * fdlz, const char * file_name, char * p, int ipa) static
Definition at line 3971 of file interf.c.
References AC_TYPEINIT, assert, ast, _acl::ast, dindex(), DTY, _acl::dtype, GET_ACL, get_num(), get_symbolxref(), getict(), _acl::id, ipa(), ipa_ast(), new_ast(), new_dtype(), new_symbol(), p, PERM_AREA, _acl::ptrdtype, put_getitem_p(), _acl::repeatc, sptr, _acl::sptr, _acl::subc, and _acl::u1.
Referenced by import().
get_module_file_name()
int get_module_file_name (char * module_file_name, char * full_file_name, int len)
Definition at line 860 of file interf.c.
References DIRSINCS, DIRWORK, flg, fndpath(), i, FLG::idir, len, moddir_list::module_directory, module_directory_list, moddir_list::next, and FLG::stdinc.
Referenced by add_to_be_used_list(), do_nested_uses(), and open_module().
get_module_file_name_from_user()
static int get_module_file_name_from_user (TOBE_IMPORTED_LIST * il, const char * from_file_name) static
Definition at line 829 of file interf.c.
References fndpath(), FREE, to_be_imported::fullfilename, MAX_FNAME_LEN, to_be_imported::modulefilename, and NULL.
Referenced by add_to_be_used_list().
get_nstring()
static void get_nstring (char * dest, int len) static
read 'len' characters
Definition at line 3352 of file interf.c.
References currp, dest, i, and len.
Referenced by import_header_only().
get_num()
static ISZ_T get_num (int radix) static
Definition at line 3311 of file interf.c.
References atoxi64(), currp, INT64_2_ISZ, ISZ_T, num, and val.
Referenced by get_component_init(), getict(), getivl(), import(), import_header_only(), and import_use_stmts().
get_string()
static void get_string (char * dest) static
Definition at line 3335 of file interf.c.
References currp, dest, and i.
Referenced by import(), import_header_only(), and import_use_stmts().
get_symbolxref()
static int get_symbolxref (int sptr) static
Definition at line 6513 of file interf.c.
References new_symbol(), and sptr.
Referenced by get_component_init(), and getict().
getict()
static ACL * getict (lzhandle * fdlz, const char * file_name, int ipa) static
Definition at line 3578 of file interf.c.
References AC_ACONST, AC_AST, AC_ICONST, AC_IDO, AC_IEXPR, AC_SCONST, AC_TYPEINIT, AC_VMSSTRUCT, AC_VMSUNION, ast, _acl::ast, BINOP, currp, dindex(), _acl::doinfo, _acl::dtype, error(), _acl::expr, first, gbl, GET_ACL, get_num(), get_symbolxref(), getict(), getitem(), i, _acl::i, _acl::id, import_corrupt_msg, import_file_name, DOINFO::index_var, DOINFO::init_expr, ipa(), ipa_ast(), _acl::is_const, DOINFO::limit_expr, AEXPR::lop, new_ast(), new_dtype(), new_symbol(), _acl::next, NULL, AEXPR::op, p, PERM_AREA, prev, _acl::ptrdtype, READ_LZLINE, _acl::repeatc, AEXPR::rop, save_struct_init(), sptr, _acl::sptr, DOINFO::step_expr, _acl::subc, Trace, and _acl::u1.
Referenced by get_component_init(), getict(), and put_data_statement().
getivl()
static VAR * getivl (lzhandle * fdlz, const char * file_name, int ipa) static
Definition at line 3460 of file interf.c.
References ast, currp, dindex(), Doend, VAR::doend, Dostart, VAR::dostart, VAR::dtype, error(), first, gbl, get_num(), getitem(), getivl(), VAR::id, import_corrupt_msg, import_file_name, VAR::indvar, ipa(), ipa_ast(), VAR::lowbd, new_ast(), new_dtype(), VAR::next, NULL, p, PERM_AREA, prev, VAR::ptr, READ_LZLINE, VAR::step, VAR::u, VAR::upbd, Varref, and VAR::varref.
Referenced by getivl(), and put_data_statement().
import()
static void import (lzhandle * fdlz, WantPrivates wantPrivates, int ivsn) static
This is the main module import function.
Below is the file format and order in which fields are read in.
    version Vnn modulename
    file  len filename firstosymbol compress
    date  mm/dd/yyyy  hh:mm:ss
    uses* use modulename public/private exceptcount except*
  direct/indirect
    enduse
    astline A astndx type flags shape hashlk w3 w4 w5 w6 w7 w8 w9 w10 hw21
  hw22 w12 opt1 opt2 repl visit w18
    container  C hostsptr hoststype
    datatype   D datatype ty_val [type-specific information]
    dtyper  d datatype sptrstype symboloffset modulename symbolname
    dtyper  e datatype sptrstype scopestype scopename symbolname
    equiv E lineno sptr first substring subscript* 0
    formal  F functionsptr numargs arg*
    align G alignptr target alignee aligntype alignsym ...
    shadow  H sptr dims
    overlap L sptr overlapsptr
    mangled M sptr nmangled [mangledsptr mangledmember]*
    overload  O sptr noverloaded overloaded*
    predecl P sptr
    generic Q sptr modproc* 0
    renamesym R sptr stype modoffset modname symname
    sym S sptr stype sc b3 b4 dtype symlk scope nmptr flags1 flags2 ...
    shape T count [lwb upb stride]*
    distrib U dist rank targettype isstar inherit formattype proc dynamic
  orig...
    std V stdidx astidx label lineno flags
    argt  W nargs [arg]*
    asd X ndim [subscript]*
    astli Y [sptr triplet]* -1
    endsection  Z
Definition at line 1943 of file interf.c.
References A_IDSTR_mask, ADD_ADJARR, ADD_ASSUMSHP, ADD_ASSUMSZ, add_astli(), ADD_DEFER, ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_NOBOUNDS, ADD_NUMELM, add_symitem(), ADD_UPAST, ADD_UPBD, ADD_ZBASE, adjust_pre34_dty(), align_list, any_ptr_constant, ARGT_ARG, argtz, asdz, assert, STDITEM::ast, astb, ASTLI_FLAGS, ASTLI_HEAD, ASTLI_SPTR, ASTLI_TRIPLE, astliz, astz, astzhash, ASTZHASHMASK, ASTZHASHSIZE, aux, SOC::avail, SYM::b3, SYM::b4, SOC::base, BZERO, ARGTITEM::callfg, curr_scope(), STB::curr_scope, currp, DBGBIT, dist_list, DLL_EXPORT, DLL_IMPORT, DLLG, DLLP, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, DTY, symitem::dtype, dtype_ivsn, dtz, EQV, SEM::eqv_avail, SEM::eqv_base, EQV_NUMSS, SEM::eqv_size, EQV_SS, SEM::eqv_ss_avail, SEM::eqv_ss_base, SEM::eqv_ss_size, SEM::eqvlist, ERR_Fatal, ERR_Severe, error(), exportb, FALSE, fill_links_symbol(), find_member_name(), findByNameStypeScope(), findhash(), ASTB::firstuast, STB::firstusym, STDITEM::flags, symitem::flags1, symitem::flags2, symitem::flags3, symitem::flags4, FLANG_FALLTHROUGH, flz, for_host, for_module, for_static, FREE, gbl, get_array_dtype(), get_component_init(), get_int_cval(), get_num(), get_string(), get_type(), GETFIELD, getitem(), getsymbol(), GSAMEG, GSAMEP, EXPORTB::hmark, i, ignore_private, import_constant(), import_corrupt_msg, import_file_name, import_ptr_constant(), import_symbol(), INCLUDE_PRIVATES, inithash(), insertdthash(), inserthash(), ARGTITEM::installed, ASDITEM::installed, ASTLIITEM::installed, SEM::interface, interr(), interrf(), j, STDITEM::label, lineno, STDITEM::lineno, SHDITEM::lwb, MAXIDLEN, EXPORTB::maxsptr, mdz, mk_argt(), MN_NENTRIES, MOD_AREA, modpz, module_base, symitem::name, SHDITEM::ndim, ASDITEM::ndim, ndims, NEED, NEW, STDITEM::new, SHDITEM::new, ARGTITEM::new, ASTLIITEM::new, new_ast(), new_asts(), new_dtypes(), symitem::new_sptr, new_stds(), new_symbol(), symitem::next, nml, AUX::nml_avl, AUX::nml_base, NML_LINENO, NML_NEXT, AUX::nml_size, NML_SPTR, SYM::nmptr, NOSYM, NULL, offset, STDITEM::old, old_astversion, original_symavl, ovz, p, pa, pd, put_data_statement(), put_dinit_record(), READ_LZLINE, s, symitem::sc, SYM::scope, SEM::scope_stack, sem, shdz, SHDITEM::shp, SOC::size, soc, SOC_NEXT, SOC_SPTR, symitem::socptr, sptr, symitem::sptr, ss, start_astli(), stb, stdz, SHDITEM::stride, strlen(), symitem::strptr, symitem::stype, STB::stypes, ASDITEM::subs, substring, symitem::sym, symbol_list, symdmp(), SYMI_NEXT, SYMI_SPTR, symitem::symlk, SYMNAME, Trace, TRUE, symitem::ty, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, uname, and SHDITEM::upb.
import_constant()
static void import_constant (SYMITEM * ps) static
Definition at line 5414 of file interf.c.
References any_ptr_constant, astb, BCOPY, CONVAL2G, DTY, symitem::dtype, find_nmptr(), getcon(), getstring(), ASTB::i1, import_symbol(), interr(), ASTB::k1, symitem::name, new_dtype(), symitem::new_sptr, SYM::nmptr, sptr, symitem::sptr, stb, strlen(), symitem::strptr, symitem::sym, Trace, TRUE, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, and val.
Referenced by import().
import_done()
static void import_done (lzhandle * fdlz, int nested) static
Definition at line 1639 of file interf.c.
References buff, FALSE, for_inliner, for_interproc, for_module, for_static, FREE, freearea(), import_corrupt_msg, import_file_name, import_incompatible_msg, import_oldfile_msg, init_use_tree(), inmodulecontains, MOD_AREA, MOD_USE_AREA, NULL, and ulzfini().
Referenced by do_nested_uses(), import_host(), import_host_subprogram(), import_inline(), import_module(), and import_static().
import_fini()
void import_fini (void)
Wrap-up module symbol import phase.
Definition at line 361 of file interf.c.
References imported_modules_struct::avail, FREE, imported_modules, imported_modules_struct::list, and imported_modules_struct::size.
Referenced by sem_fini().
import_header()
static lzhandle * import_header (FILE * fd, const char * file_name, int import_which, int * ivsn_return) static
Definition at line 1594 of file interf.c.
References addmodfile(), curr_import_findex, do_nested_uses(), fd, to_be_imported::fullfilename, i, import_header_only(), import_use_stmts(), INCLUDE_PRIVATES, modinclist, modinclistavl, modinclistsize, NEW, to_be_imported::next, NULL, set_message(), to_be_used_list_head, to_be_used_list_tail, ulzfini(), and XBIT.
Referenced by import_host(), import_host_subprogram(), import_inline(), import_module(), and import_static().
import_header_only()
static lzhandle * import_header_only (FILE * fd, const char * file_name, int import_which, int * ivsn_return) static
Definition at line 1306 of file interf.c.
References BASEdty, buff, BUFF_LEN, buff_sz, can_map_initsym(), compress(), curr_platform, currp, DBGBIT, DT_MAX_43, error(), fd, for_static, FREE, gbl, get_nstring(), get_num(), get_string(), getitem(), import_corrupt_msg, import_errno, import_file_name, import_incompatible_msg, import_name, import_oldfile_msg, import_osym, import_sourcename, import_sourcename_len, j, NEW, NULL, p, READ_LINE, READ_LZLINE, set_message(), ulzfini(), ulzinit(), and XBIT.
Referenced by do_nested_uses(), and import_header().
import_host()
void import_host (FILE * fd, const char * file_name, int oldsymavl, int oldastavl, int olddtyavl, int modbase, int moddiff, int oldscope, int newscope)
This is called to restore symbol table, etc., data for contained subprograms.
Definition at line 3259 of file interf.c.
References ADJmod, BASEast, BASEdty, BASEmod, BASEsym, FALSE, fd, for_host, HOST_NEWSCOPE, HOST_OLDSCOPE, import_done(), import_header(), IMPORT_WHICH_HOST, INCLUDE_PRIVATES, and TRUE.
Referenced by restore_internal_subprograms(), and restore_module_state().
import_host_subprogram()
void import_host_subprogram (FILE * fd, const char * file_name, int oldsymavl, int oldastavl, int olddtyavl, int modbase, int moddiff)
This is called to restore symbol table, etc., data for contained subprograms.
Definition at line 3289 of file interf.c.
References ADJmod, BASEast, BASEdty, BASEmod, BASEsym, export_fix_host_append_list(), FALSE, fd, for_host, import_done(), import_header(), IMPORT_WHICH_HOST, INCLUDE_PRIVATES, new_symbol(), and TRUE.
Referenced by restore_host_state().
import_init()
void import_init (void)
Initialize import of module symbols, etc.
Definition at line 349 of file interf.c.
References imported_modules_struct::avail, exterf_init(), imported_modules, imported_modules_struct::list, NEW, and imported_modules_struct::size.
Referenced by semant_init().
import_inline()
int import_inline (FILE * fd, char * file_name)
Definition at line 3091 of file interf.c.
References ADJmod, astb, BASEast, BASEdty, BASEmod, BASEsym, DBGBIT, dmp_dtype(), STB::dt, dump_ast(), fclose(), fd, ASTB::firstuast, STB::firstusym, gbl, import_done(), import_errno, import_header(), IMPORT_WHICH_INLINE, INCLUDE_PRIVATES, stb, and symdmp().
Referenced by inline_func().
import_mk_newsym()
static int import_mk_newsym (char * name, int stype) static
Definition at line 6435 of file interf.c.
References getsymbol(), insert_sym(), name, and sptr.
Referenced by do_nested_uses(), and import_module().
import_module()
SPTR import_module (FILE * fd, char * file_name, SPTR modsym, WantPrivates wantPrivates, int scope_level)
This is called either for a USE statement, or to import the specification part of a module for the contained subprograms.
Definition at line 3156 of file interf.c.
References add_imported(), ADJmod, alreadyused(), astb, BASEast, BASEdty, BASEmod, BASEsym, STB::curr_scope, fd, find_modname_in_list(), ASTB::firstuast, STB::firstusym, import_done(), import_header(), import_mk_newsym(), IPARECOMPILE, push_scope_level(), restore_scope_level(), save_scope_level(), SEM::scope_level, SCOPE_USE, sem, to_be_imported::sl, SPTR_NULL, stb, SYMNAME, top_scope_level, and use_tree.
Referenced by apply_use().
import_module_end()
void import_module_end (void)
Definition at line 3210 of file interf.c.
import_module_print()
void import_module_print (void)
Definition at line 3215 of file interf.c.
References basenam(), c, CNULL, error(), f, FILE, fname, fp, gbl, m, modinclist, modinclistavl, NULL, sccalloc(), strlen(), and XBIT.
Referenced by finish().
import_ptr_constant()
static void import_ptr_constant (SYMITEM * ps) static
Definition at line 5665 of file interf.c.
References BCOPY, CONVAL2G, DTY, symitem::dtype, getcon(), symitem::name, new_dtype(), symitem::new_sptr, new_symbol(), sptr, symitem::sptr, stb, symitem::stype, symitem::sym, Trace, and val.
Referenced by import().
import_skip_use_stmts()
static int import_skip_use_stmts (lzhandle * fdlz) static
Look for any 'use' statements and skip over them.
Definition at line 1560 of file interf.c.
References currp, error(), gbl, import_corrupt_msg, import_file_name, NULL, p, and READ_LZLINE.
Referenced by do_nested_uses().
import_static()
int import_static (FILE * fd, char * file_name)
import a routine for static analysis
Definition at line 3133 of file interf.c.
References ADJmod, astb, BASEast, BASEdty, BASEmod, BASEsym, fd, ASTB::firstuast, STB::firstusym, import_done(), import_errno, import_header(), IMPORT_WHICH_PRELINK, INCLUDE_PRIVATES, and stb.
import_symbol()
static void import_symbol (SYMITEM * ps) static
Definition at line 5497 of file interf.c.
References BASEsym, BCOPY, CONVAL2G, STB::curr_scope, FLG::debug, DTY, symitem::dtype, FALSE, fill_ST_MODULE(), fill_sym(), first_hash(), flg, for_host, for_inliner, for_module, getcon(), getlab(), getocsym(), getsymbol(), insert_sym(), module_base, symitem::name, new_dtype(), symitem::new_sptr, new_symbol(), NOSYM, original_symavl, STB::ovclass, symitem::sc, SYM::scope, set_modusename(), sptr, symitem::sptr, ST_ISVAR, stb, symitem::stype, symitem::sym, Trace, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, val, SYM::w28, and XBIT.
Referenced by import(), and import_constant().
import_use_stmts()
static int import_use_stmts (lzhandle * fdlz, TOBE_IMPORTED_LIST * ilfrom, const char * from_file_name, int import_which, int nested_public) static
Definition at line 1474 of file interf.c.
References add_symitem(), add_to_be_used_list(), add_use_edge(), add_use_tree_uses(), already_to_be_used(), currp, DBGBIT, direct, error(), gbl, get_num(), get_scope_level(), get_string(), SEM::ieee_features, import_corrupt_msg, import_file_name, insert_node_into_use_tree(), MAXIDLEN, to_be_imported::modulename, n, next_scope_kind_symname(), NULL, p, READ_LZLINE, s, scope, SCOPE_MODULE, SEM::scope_stack, sem, to_be_imported::sl, SYMNAME, and TRUE.
Referenced by do_nested_uses(), and import_header().
imported_directly()
LOGICAL imported_directly (char * name, int except)
Definition at line 620 of file interf.c.
References find_use_node_in_list(), name, NULL, and use_tree.
Referenced by export_header().
init_use_tree()
void init_use_tree (void)
Definition at line 513 of file interf.c.
References use_tree, and use_tree_end.
Referenced by begin_module(), end_module(), import_done(), mod_init(), and rw_import_state().
inithash()
static void inithash (void) static
Definition at line 1808 of file interf.c.
References dthash, DTHASHSIZE, i, NULL, symhash, and SYMHASHSIZE.
Referenced by import().
insert_node_into_use_tree()
static TOBE_IMPORTED_LIST * insert_node_into_use_tree (char * modulename) static
Create and insert a TOBE_IMPORTED_LIST item into the beginning of the use_tree.
Definition at line 647 of file interf.c.
References DBGBIT, uses_list::directlyused, to_be_imported::exceptlist, FALSE, to_be_imported::fullfilename, gbl, getitem(), MOD_USE_AREA, to_be_imported::modulefilename, to_be_imported::modulename, uses_list::next, to_be_imported::next, NULL, to_be_imported::order, to_be_imported::prev, to_be_imported::public, to_be_imported::sl, strlen(), uses_list::use_module, use_tree, use_tree_end, to_be_imported::uses, and to_be_imported::visited.
Referenced by import_use_stmts().
insertdthash()
static void insertdthash (int old_dt, int d) static
Definition at line 1842 of file interf.c.
References d, dthash, DTHASHSIZE, dtz, and h.
Referenced by import().
inserthash()
static void inserthash (int sptr, SYMITEM * ps) static
Definition at line 1820 of file interf.c.
References h, symitem::hashnext, sptr, symhash, and SYMHASHSIZE.
Referenced by import().
install_dtype()
static int install_dtype (DITEM * pd) static
Definition at line 4024 of file interf.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_NUMDIM, ADD_NUMELM, ADD_UPAST, ADD_UPBD, ADD_ZBASE, aux, can_find_symbol(), AUX::dpdsc_base, DT_INT, DTY, i, interr(), new_ast(), new_dtype(), new_symbol(), NOSYM, pd, TRUE, TY_CHAR, and TY_NCHAR.
Referenced by new_dtypes(), and new_installed_dtype().
interf_init()
void interf_init (void)
'interface' initialization, called once per compilation (source file).
Definition at line 71 of file interf.c.
References assert.
Referenced by init().
ipa_ast()
static int ipa_ast (int a) static
Definition at line 6501 of file interf.c.
References a, and new_ast().
Referenced by get_component_init(), getict(), and getivl().
new_argt()
static int new_argt (int offset) static
Look up an (old) argt.
If this is the first lookup, process the argument asts from the old argt. The space for the new argt has already been allocated and the 'arg' fields in the argt are overwritten by new asts.
Returns
the index of the ASDITEM (NOT the new argt).
Definition at line 4929 of file interf.c.
References argt, ARGT_ARG, ARGT_CNT, argtz, ast, cnt, j, new_ast(), offset, and TRUE.
Referenced by fill_ast().
new_asd()
static int new_asd (int offset) static
Look up an (old) asd.
If this is the first lookup, process the subscript ASTs; return the index of the ASDITEM item. NOTE: this function doesn't create a NEW asd; it will provide the necessary information for an ensuing call to mk_subscr().
Definition at line 4962 of file interf.c.
References asdz, ast, cnt, j, new_ast(), offset, and TRUE.
Referenced by fill_ast().
new_ast()
static int new_ast (int old_ast) static
Definition at line 4842 of file interf.c.
References astz, astzhash, ASTZHASHMASK, BASEast, error(), fill_ast(), gbl, import_file_name, interr(), pa, s, and Trace.
Referenced by bblock(), byvalue_ref_arg(), construct_intrinsic_acl(), fill_ast(), fill_links_symbol(), func_call2(), get_component_init(), getict(), getivl(), import(), init_derived_type(), install_dtype(), ipa_ast(), new_argt(), new_asd(), new_astli(), new_shape(), new_stds(), ptrfunc_call(), and rewrite_cptr_references().
new_astli()
static int new_astli (int offset, int atype) static
Look up an (old) ast list.
If this is the first lookup, process the information of each item in the list. The space for the new astli has already been allocated and the fields in each astli item are overwritten.
Returns
the index to the head of the 'new' ast list
Definition at line 4988 of file interf.c.
References ast, ASTLI_AST, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, astliz, interr(), new_ast(), new_symbol(), offset, sptr, and TRUE.
Referenced by fill_ast().
new_asts()
static void new_asts (void) static
Definition at line 4831 of file interf.c.
References astb, astz, BZERO, fill_ast(), i, and void().
Referenced by import().
new_dtype()
static int new_dtype (int old_dt) static
Definition at line 4115 of file interf.c.
References adjust_pre34_dtype(), BASEdty, DT_INT, dtype_ivsn, finddthash(), interr(), NULL, and pd.
Referenced by create_parameterized_dt(), dindex(), fill_ast(), fill_links_symbol(), fix_mem_bounds2(), fixup_nme(), get_component_init(), get_parameterized_dt(), getict(), getivl(), import_constant(), import_ptr_constant(), import_symbol(), install_dtype(), and update_return_type_for_ccfunc().
new_dtypes()
static void new_dtypes (void) static
Definition at line 4155 of file interf.c.
References EXPORTB::dt, STB::dt, DTY, dtz, exportb, EXPORTB::hmark, inmodulecontains, install_dtype(), j, new_symbol(), pd, and stb.
Referenced by import().
new_installed_dtype()
static int new_installed_dtype (int old_dt) static
Definition at line 4132 of file interf.c.
References adjust_pre34_dtype(), BASEdty, DT_INT, dtype_ivsn, finddthash(), install_dtype(), interr(), NULL, and pd.
Referenced by fill_ast().
new_shape()
static int new_shape (int offset) static
Look up an (old) shd.
If this is the first lookup, process the specifiers (asts) for each dimension. After all of the specifiers have been processed, create a new shape descriptor, stashing its index in the SHDITEM and return the index to the new shape descriptor.
Definition at line 5030 of file interf.c.
References add_shape_rank(), add_shape_spec(), ast, cnt, j, SHDITEM::lwb, mk_shape(), SHDITEM::ndim, SHDITEM::new, new_ast(), offset, shdz, SHDITEM::shp, SHDITEM::stride, and SHDITEM::upb.
Referenced by fill_ast().
new_std()
static int new_std (int old_std) static
Definition at line 4906 of file interf.c.
References i, STDITEM::new, STDITEM::old, and stdz.
Referenced by bblock(), and fill_ast().
new_stds()
static void new_stds (void) static
Definition at line 4867 of file interf.c.
References add_stmt(), ast, STDITEM::ast, cs, flags, STDITEM::flags, GETBIT, i, STDITEM::label, STDITEM::lineno, new_ast(), new_symbol(), par, parsect, st, std, STD_LABEL, STD_LINENO, and stdz.
Referenced by import().
new_symbol()
static int new_symbol (int old_sptr) static
Definition at line 6161 of file interf.c.
References ADJmod, BASEmod, BASEsym, findhash(), HOST_NEWSCOPE, HOST_OLDSCOPE, import_osym, interr(), map_initsym(), symitem::new_sptr, and sptr.
Referenced by fill_ast(), fill_links_symbol(), get_component_init(), get_symbolxref(), getict(), import(), import_host_subprogram(), import_ptr_constant(), import_symbol(), install_dtype(), new_astli(), new_dtypes(), new_stds(), and put_dinit_record().
new_symbol_and_link()
static void new_symbol_and_link (int old_sptr, int * pnew, SYMITEM ** pps) static
Definition at line 6214 of file interf.c.
References ADJmod, BASEmod, BASEsym, findhash(), import_osym, interr(), map_initsym(), symitem::new_sptr, NULL, and sptr.
Referenced by fill_ast().
new_symbol_if_module()
static int new_symbol_if_module (int old_sptr) static
Definition at line 6183 of file interf.c.
References ADJmod, BASEmod, BASEsym, findhash(), import_osym, map_initsym(), symitem::new_sptr, sptr, and symitem::stype.
Referenced by fill_links_symbol().
put_data_statement()
static void put_data_statement (int lineno, int anyivl, int anyict, lzhandle * fdlz, const char * file_name, int ipa) static
Definition at line 3906 of file interf.c.
References astb, CNULL, CONVAL2P, STB::curr_scope, ASTB::df, SEM::dinit_nbr_inits, errfatal(), error(), for_interproc, for_module, gbl, getict(), getivl(), VAR::id, ipa(), lineno, NULL, VAR::ptr, put_getitem_p(), sem, sptr, stb, sym_of_ast(), tmpfile(), Trace, VAR::u, Varref, and VAR::varref.
Referenced by import().
put_dinit_record()
static void put_dinit_record (int ptype, INT pcon) static
Change symbol number, if necessary, and write record to data init file.
Definition at line 3401 of file interf.c.
References DINIT_END, DINIT_ENDARY, DINIT_ENDTYPE, DINIT_FMT, DINIT_LABEL, DINIT_LOC, DINIT_NML, DINIT_OFFSET, dinit_put(), DINIT_REPEAT, DINIT_STARTARY, DINIT_STR, DINIT_TYPEDEF, DINIT_ZEROES, DTY, new_symbol(), sptr, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, and TY_SLOG.
Referenced by import().
read_line()
static char * read_line (FILE * fd) static
Definition at line 3067 of file interf.c.
References buff, BUFF_LEN, buff_sz, currp, fd, i, NULL, sccrelal(), and TRUE.
Referenced by _read_token().
remove_from_use_tree()
void remove_from_use_tree (char * module)
Definition at line 518 of file interf.c.
References n, uses_list::next, prev, and use_tree.
Referenced by apply_use_stmts().
rw_import_state()
void rw_import_state (RW_ROUTINE , RW_FILE)
Definition at line 6451 of file interf.c.
References add_to_use_tree(), imported_modules_struct::avail, i, imported_modules, init_use_tree(), ISREAD, imported_modules_struct::list, uses_list::next, NULL, RW_FD, RW_SCALAR, uses_list::use_module, and use_tree.
Referenced by rw_host_state().
scope_in_scope_stack()
static LOGICAL scope_in_scope_stack (int sptr) static
Definition at line 1002 of file interf.c.
References curr_scope(), SEM::interface, next_scope_kind(), next_scope_sptr(), SCOPE_INTERFACE, sem, and sptr.
Referenced by aliased_sym_visible().
set_message()
static void set_message (int import_which, const char * file_name) static
Definition at line 400 of file interf.c.
References for_host, for_inliner, for_interproc, for_module, for_static, import_corrupt_msg, import_file_name, import_incompatible_msg, import_oldfile_msg, IMPORT_WHICH_HOST, IMPORT_WHICH_INLINE, IMPORT_WHICH_IPA, IMPORT_WHICH_PRELINK, and TRUE.
Referenced by import_header(), and import_header_only().
sym_visible_in_scope()
static int sym_visible_in_scope (USES_LIST * list, int sptrsym, char * symscopenm) static
Definition at line 922 of file interf.c.
References uses_list::directlyused, FALSE, find_next_modname_in_list(), get_scope(), is_except_in_scope(), is_private_in_scope(), list, n, uses_list::next, to_be_imported::public, scope, SEM::scope_level, SEM::scope_stack, sem, to_be_imported::sl, SCOPESTACK::sptr, stb, sym_visible_in_scope(), SCOPESTACK::symavl, TRUE, uses_list::use_module, to_be_imported::uses, and to_be_imported::visited.
Referenced by aliased_sym_visible(), and sym_visible_in_scope().
topsort()
static void topsort (TOBE_IMPORTED_LIST * il) static
Definition at line 901 of file interf.c.
References FALSE, uses_list::next, NULL, to_be_imported::order, to_be_used_list_order_head, to_be_used_list_order_tail, topsort(), TRUE, uses_list::use_module, to_be_imported::uses, and to_be_imported::visited.
Referenced by do_nested_uses(), and topsort().
update_list_exceptions()
static void update_list_exceptions (USES_LIST * list) static
Definition at line 802 of file interf.c.
References uses_list::directlyused, SCOPESTACK::except, to_be_imported::exceptlist, get_scope(), list, uses_list::next, to_be_imported::public, SEM::scope_size, sem, to_be_imported::sl, update_list_exceptions(), uses_list::use_module, and to_be_imported::uses.
Referenced by update_list_exceptions(), and update_use_tree_exceptions().
update_use_tree_exceptions()
void update_use_tree_exceptions (void)
Definition at line 823 of file interf.c.
References update_list_exceptions(), and use_tree.
Referenced by apply_use().
Variable Documentation
A_IDSTR_mask
unsigned A_IDSTR_mask = (1 << 5) static
Definition at line 1902 of file interf.c.
Referenced by fill_ast(), and import().
ADJmod
int ADJmod static
Definition at line 58 of file interf.c.
Referenced by import_host(), import_host_subprogram(), import_inline(), import_module(), import_static(), new_symbol(), new_symbol_and_link(), and new_symbol_if_module().
align_list
ALNITEM* align_list static
Definition at line 280 of file interf.c.
Referenced by import().
any_ptr_constant
LOGICAL any_ptr_constant = FALSE static
Definition at line 1903 of file interf.c.
Referenced by import(), and import_constant().
struct { ... } argtz
Referenced by fill_ast(), import(), and new_argt().
struct { ... } asdz
Referenced by fill_ast(), import(), and new_asd().
struct { ... } astliz
Referenced by import(), and new_astli().
struct { ... } astz
Referenced by import(), new_ast(), and new_asts().
astzhash
int astzhash[ASTZHASHSIZE] static
Definition at line 241 of file interf.c.
Referenced by import(), and new_ast().
avl
int avl
Definition at line 209 of file interf.c.
base
MODPITEM* base
Definition at line 208 of file interf.c.
Referenced by do_nested_uses(), and find_member_name().
BASEast
int BASEast static
Definition at line 58 of file interf.c.
Referenced by do_nested_uses(), import_host(), import_host_subprogram(), import_inline(), import_module(), import_static(), and new_ast().
BASEdty
int BASEdty static
Definition at line 58 of file interf.c.
Referenced by do_nested_uses(), import_header_only(), import_host(), import_host_subprogram(), import_inline(), import_module(), import_static(), new_dtype(), and new_installed_dtype().
BASEmod
int BASEmod static
Definition at line 58 of file interf.c.
Referenced by import_host(), import_host_subprogram(), import_inline(), import_module(), import_static(), new_symbol(), new_symbol_and_link(), and new_symbol_if_module().
BASEsym
int BASEsym static
Definition at line 58 of file interf.c.
Referenced by do_nested_uses(), import_host(), import_host_subprogram(), import_inline(), import_module(), import_static(), import_symbol(), new_symbol(), new_symbol_and_link(), and new_symbol_if_module().
buff
char* buff = NULL static
Definition at line 289 of file interf.c.
Referenced by import_done(), import_header_only(), and read_line().
buff_sz
int buff_sz static
Definition at line 290 of file interf.c.
Referenced by import_header_only(), and read_line().
curr_import_findex
int curr_import_findex = 0 static
Definition at line 299 of file interf.c.
Referenced by import_header().
curr_platform
int curr_platform = MOD_ANY static
Definition at line 294 of file interf.c.
Referenced by import_header_only().
currp
char* currp static
Definition at line 291 of file interf.c.
Referenced by get_nstring(), get_num(), get_string(), getict(), getivl(), import(), import_header_only(), import_skip_use_stmts(), import_use_stmts(), and read_line().
dist_list
DSTITEM* dist_list static
Definition at line 281 of file interf.c.
Referenced by import().
dthash
int dthash[DTHASHSIZE] static
Definition at line 286 of file interf.c.
Referenced by finddthash(), inithash(), and insertdthash().
dtype_ivsn
int dtype_ivsn = 0 static
Definition at line 307 of file interf.c.
Referenced by import(), new_dtype(), and new_installed_dtype().
struct { ... } dtz
Referenced by finddthash(), import(), insertdthash(), and new_dtypes().
struct { ... } flz
Referenced by import().
for_host
LOGICAL for_host = FALSE static
Definition at line 47 of file interf.c.
Referenced by do_nested_uses(), fill_links_symbol(), import(), import_host(), import_host_subprogram(), import_symbol(), and set_message().
for_inliner
LOGICAL for_inliner = FALSE static
Definition at line 44 of file interf.c.
Referenced by fill_ast(), fill_links_symbol(), import_done(), import_symbol(), and set_message().
for_interproc
LOGICAL for_interproc = FALSE static
Definition at line 45 of file interf.c.
Referenced by fill_links_symbol(), import_done(), put_data_statement(), and set_message().
for_module
int for_module = 0 static
Definition at line 43 of file interf.c.
Referenced by do_nested_uses(), fill_links_symbol(), import(), import_done(), import_symbol(), put_data_statement(), and set_message().
for_static
LOGICAL for_static = FALSE static
Definition at line 46 of file interf.c.
Referenced by fill_links_symbol(), import(), import_done(), import_header_only(), and set_message().
HOST_NEWSCOPE
int HOST_NEWSCOPE = 0 static
Definition at line 59 of file interf.c.
Referenced by import_host(), and new_symbol().
HOST_OLDSCOPE
int HOST_OLDSCOPE = 0 static
Definition at line 59 of file interf.c.
Referenced by import_host(), and new_symbol().
ignore_private
LOGICAL ignore_private = FALSE static
Definition at line 298 of file interf.c.
Referenced by fill_links_symbol(), and import().
import_corrupt_msg
const char* import_corrupt_msg static
Definition at line 389 of file interf.c.
Referenced by getict(), getivl(), import(), import_done(), import_header_only(), import_skip_use_stmts(), import_use_stmts(), and set_message().
import_errno
int import_errno = 0 static
Definition at line 51 of file interf.c.
Referenced by import_header_only(), import_inline(), and import_static().
import_file_name
const char* import_file_name static
Definition at line 334 of file interf.c.
Referenced by fill_ast(), getict(), getivl(), import(), import_done(), import_header_only(), import_skip_use_stmts(), import_use_stmts(), new_ast(), and set_message().
import_incompatible_msg
const char* import_incompatible_msg static
Definition at line 391 of file interf.c.
Referenced by import_done(), import_header_only(), and set_message().
import_name
char import_name[MAXIDLEN+1] static
Definition at line 292 of file interf.c.
Referenced by import_header_only().
import_oldfile_msg
const char* import_oldfile_msg static
Definition at line 390 of file interf.c.
Referenced by import_done(), import_header_only(), and set_message().
import_osym
int import_osym = 0 static
Definition at line 52 of file interf.c.
Referenced by do_nested_uses(), import_header_only(), new_symbol(), new_symbol_and_link(), and new_symbol_if_module().
import_sourcename
char* import_sourcename = NULL static
Definition at line 296 of file interf.c.
Referenced by import_header_only().
import_sourcename_len
int import_sourcename_len = 0 static
Definition at line 297 of file interf.c.
Referenced by import_header_only().
imported_modules
struct imported_modules_struct imported_modules = {NULL, 0, 0, 0, 0}
Definition at line 345 of file interf.c.
Referenced by add_imported(), alreadyused(), import_fini(), import_init(), and rw_import_state().
inmodulecontains
LOGICAL inmodulecontains = FALSE static
Definition at line 41 of file interf.c.
Referenced by import_done(), and new_dtypes().
IPARECOMPILE
int IPARECOMPILE = FALSE static
Definition at line 3150 of file interf.c.
Referenced by import_module().
struct { ... } mdz
Referenced by import().
modinclist
char** modinclist = NULL static
Definition at line 61 of file interf.c.
Referenced by addmodfile(), import_header(), and import_module_print().
modinclistavl
int modinclistavl = 0 static
Definition at line 62 of file interf.c.
Referenced by addmodfile(), import_header(), and import_module_print().
modinclistsize
int modinclistsize = 0 static
Definition at line 62 of file interf.c.
Referenced by addmodfile(), and import_header().
struct { ... } modpz
Referenced by import().
module_base
int module_base = 0 static
Definition at line 1802 of file interf.c.
Referenced by fill_links_symbol(), import(), and import_symbol().
old_astversion
LOGICAL old_astversion = FALSE static
Definition at line 48 of file interf.c.
Referenced by import().
original_symavl
int original_symavl = 0 static
Definition at line 1901 of file interf.c.
Referenced by import(), and import_symbol().
struct { ... } ovz
Referenced by import().
struct { ... } shdz
Referenced by import(), and new_shape().
struct { ... } stdz
Referenced by import(), new_std(), and new_stds().
symbol_list
SYMITEM* symbol_list static
Definition at line 279 of file interf.c.
Referenced by import().
symhash
SYMITEM* symhash[SYMHASHSIZE] static
Definition at line 284 of file interf.c.
Referenced by findhash(), inithash(), and inserthash().
sz
int sz
Definition at line 210 of file interf.c.
to_be_used_list_head
TOBE_IMPORTED_LIST* to_be_used_list_head static
Definition at line 469 of file interf.c.
Referenced by add_to_be_used_list(), already_to_be_used(), do_nested_uses(), and import_header().
to_be_used_list_order_head
TOBE_IMPORTED_LIST* to_be_used_list_order_head static
Definition at line 470 of file interf.c.
Referenced by do_nested_uses(), and topsort().
to_be_used_list_order_tail
TOBE_IMPORTED_LIST * to_be_used_list_order_tail static
Definition at line 471 of file interf.c.
Referenced by do_nested_uses(), and topsort().
to_be_used_list_tail
TOBE_IMPORTED_LIST * to_be_used_list_tail static
Definition at line 469 of file interf.c.
Referenced by add_to_be_used_list(), and import_header().
top_scope_level
int top_scope_level = 0 static
Definition at line 49 of file interf.c.
Referenced by do_nested_uses(), and import_module().
use_tree
USES_LIST* use_tree = NULL static
Definition at line 472 of file interf.c.
Referenced by add_to_use_tree(), adjust_symbol_accessibility(), aliased_sym_visible(), dump_use_tree(), import_module(), imported_directly(), init_use_tree(), insert_node_into_use_tree(), remove_from_use_tree(), rw_import_state(), and update_use_tree_exceptions().
use_tree_end
USES_LIST * use_tree_end = NULL static
Definition at line 473 of file interf.c.
Referenced by add_to_use_tree(), init_use_tree(), and insert_node_into_use_tree().