flang: interf.h File Reference
interf.h File Reference
Various definitions and prototypes for importing/exporting modules and IPA information.
Classes
struct EXPORTB
struct moddir_list
struct IMPORT_LIST
struct imported_modules_struct
Macros
#define USE_AREA 11
#define USE_TREE_AREA 14
Typedefs
typedef struct moddir_list moddir_list
Enumerations
enum WantPrivates { INCLUDE_PRIVATES , EXCLUDE_PRIVATES }
Functions
int symbol_is_visible (int sptralias)
void adjust_symbol_accessibility (int)
void update_use_tree_exceptions (void)
void export_module (FILE *, char *, int, int)
Save the module file for use when exporting contained subprograms.
void export_append_sym (int)
void export_append_host_sym (int)
void export_host_subprogram (FILE *, int, int, int, int)
void export_module_subprogram (FILE *, int, int, int, int)
int get_module_file_name (char *modulename, char *filename, int len)
void import_init (void)
Initialize import of module symbols, etc.
int import_inline (FILE *, char *)
int import_interproc (FILE *, char *, char *, char *)
int import_static (FILE *, char *)
import a routine for static analysis
SPTR import_module (FILE *, char *, SPTR, WantPrivates, int)
This is called either for a USE statement, or to import the specification part of a module for the contained subprograms.
void import_host (FILE *, const char *, int, int, int, int, int, int, int)
This is called to restore symbol table, etc., data for contained subprograms.
void import_module_end (void)
int imported_directly (char *name, int except)
void init_use_tree (void)
void remove_from_use_tree (char *module)
int aliased_sym_visible (int sptralias)
Determine if there is a path through the USEs that makes the symbol aliased by sptralias visible.
void interf_init (void)
'interface' initialization, called once per compilation (source file).
void ipa_import_open (char *import_file, BIGUINT offset)
void ipa_export_open (char *export_filename)
void ipa_export (void)
void ipa_export_close (void)
Variables
moddir_list * module_directory_list
EXPORTB exportb
struct imported_modules_struct imported_modules
Detailed Description
Various definitions and prototypes for importing/exporting modules and IPA information.
Definition in file interf.h.
Macro Definition Documentation
USE_AREA
#define USE_AREA 11
Definition at line 71 of file interf.h.
USE_TREE_AREA
#define USE_TREE_AREA 14
Definition at line 72 of file interf.h.
Typedef Documentation
moddir_list
typedef struct moddir_list moddir_list
Enumeration Type Documentation
WantPrivates
enum WantPrivates
When importing a module, to mark whether to import private members or not.
Enumerator
INCLUDE_PRIVATES
EXCLUDE_PRIVATES
Definition at line 78 of file interf.h.
Function Documentation
adjust_symbol_accessibility()
void adjust_symbol_accessibility (int currmod)
Definition at line 1104 of file interf.c.
References alias_may_need_adjustment(), aliased_sym_visible(), STB::firstosym, STB::firstusym, gbl, sptr, stb, and use_tree.
Referenced by apply_use().
aliased_sym_visible()
int aliased_sym_visible (int sptralias)
Determine if there is a path through the USEs that makes the symbol aliased by sptralias visible.
If so, return the sptr of the module containing the symbol definition or, in some cases, the sptr of the module containing the exposing alias. Otherwise return 0.
Definition at line 1018 of file interf.c.
References clear_list_nodes_visited(), scope_in_scope_stack(), sptr, sym_visible_in_scope(), SYMNAME, and use_tree.
Referenced by adjust_symbol_accessibility(), and find_def_in_most_recent_scope().
export_append_host_sym()
void export_append_host_sym (int sym)
Definition at line 621 of file exterf.c.
References APPEND_AREA, getitem(), host_append_list, p, SYMNAME, and Trace.
Referenced by restore_host_state().
export_append_sym()
void export_append_sym (int sym)
Definition at line 575 of file exterf.c.
References APPEND_AREA, append_list, getitem(), p, SYMNAME, and Trace.
Referenced by declsym(), and mod_add_subprogram().
export_host_subprogram()
void export_host_subprogram (FILE * host_file, int host_sym, int limitsptr, int limitast, int limitdtype)
Definition at line 790 of file exterf.c.
References ADD_DEFER, ast_unvisit(), ast_visit(), DTY, export_dtypes(), export_header(), export_outer_derived_dtypes(), export_some_args(), export_some_fini(), export_some_init(), export_some_procedure(), export_symbol(), FALSE, fflush(), fixup_host_symbol_dtype(), for_contained, gbl, host_append_list, interr(), limitsptr, lzfinifile(), mark_dtype_ast_idstr(), SEM::mod_cnt, SEM::mod_sym, NULL, outlz, p, queue_symbol(), sem, sym_module, SYMNAME, Trace, and TRUE.
Referenced by restore_host_state().
export_module()
void export_module (FILE * module_file, char * export_name, int modulesym, int cleanup)
Save the module file for use when exporting contained subprograms.
Definition at line 562 of file exterf.c.
References cleanup(), export(), exporting_module, FALSE, for_module, sym_module, Trace, and TRUE.
Referenced by export_all().
export_module_subprogram()
void export_module_subprogram (FILE * subprog_file, int subprog_sym, int limitsptr, int limitast, int limitdtype)
Definition at line 845 of file exterf.c.
References append_list, ast_unvisit(), ast_visit(), DLL_EXPORT, DLLP, export_dtypes(), export_header(), export_some_args(), export_some_fini(), export_some_init(), export_some_procedure(), export_symbol(), FALSE, fflush(), FLANG_FALLTHROUGH, for_contained, gbl, interr(), limitsptr, lzfinifile(), SEM::mod_dllexport, SEM::mod_sym, NOSYM, NULL, outlz, p, queue_symbol(), sem, sptr, stb, sym_module, symbol_flag, SYMNAME, Trace, and TRUE.
Referenced by reset_module_state().
get_module_file_name()
int get_module_file_name (char * modulename, char * filename, int len)
Definition at line 860 of file interf.c.
References DIRSINCS, DIRWORK, flg, fndpath(), i, FLG::idir, len, moddir_list::module_directory, module_directory_list, moddir_list::next, and FLG::stdinc.
Referenced by add_to_be_used_list(), do_nested_uses(), and open_module().
import_host()
void import_host (FILE * fd, const char * file_name, int oldsymavl, int oldastavl, int olddtyavl, int modbase, int moddiff, int oldscope, int newscope)
This is called to restore symbol table, etc., data for contained subprograms.
Definition at line 3259 of file interf.c.
References ADJmod, BASEast, BASEdty, BASEmod, BASEsym, FALSE, fd, for_host, HOST_NEWSCOPE, HOST_OLDSCOPE, import_done(), import_header(), IMPORT_WHICH_HOST, INCLUDE_PRIVATES, and TRUE.
Referenced by restore_internal_subprograms(), and restore_module_state().
import_init()
void import_init (void)
Initialize import of module symbols, etc.
Definition at line 349 of file interf.c.
References imported_modules_struct::avail, exterf_init(), imported_modules, imported_modules_struct::list, NEW, and imported_modules_struct::size.
Referenced by semant_init().
import_inline()
int import_inline (FILE * fd, char * file_name)
Definition at line 3091 of file interf.c.
References ADJmod, astb, BASEast, BASEdty, BASEmod, BASEsym, DBGBIT, dmp_dtype(), STB::dt, dump_ast(), fclose(), fd, ASTB::firstuast, STB::firstusym, gbl, import_done(), import_errno, import_header(), IMPORT_WHICH_INLINE, INCLUDE_PRIVATES, stb, and symdmp().
Referenced by inline_func().
import_interproc()
int import_interproc (FILE * , char * , char * , char *)
import_module()
SPTR import_module (FILE * fd, char * file_name, SPTR modsym, WantPrivates wantPrivates, int scope_level)
This is called either for a USE statement, or to import the specification part of a module for the contained subprograms.
Definition at line 3156 of file interf.c.
References add_imported(), ADJmod, alreadyused(), astb, BASEast, BASEdty, BASEmod, BASEsym, STB::curr_scope, fd, find_modname_in_list(), ASTB::firstuast, STB::firstusym, import_done(), import_header(), import_mk_newsym(), IPARECOMPILE, push_scope_level(), restore_scope_level(), save_scope_level(), SEM::scope_level, SCOPE_USE, sem, to_be_imported::sl, SPTR_NULL, stb, SYMNAME, top_scope_level, and use_tree.
Referenced by apply_use().
import_module_end()
void import_module_end (void)
Definition at line 3210 of file interf.c.
import_static()
int import_static (FILE * fd, char * file_name)
import a routine for static analysis
Definition at line 3133 of file interf.c.
References ADJmod, astb, BASEast, BASEdty, BASEmod, BASEsym, fd, ASTB::firstuast, STB::firstusym, import_done(), import_errno, import_header(), IMPORT_WHICH_PRELINK, INCLUDE_PRIVATES, and stb.
imported_directly()
int imported_directly (char * name, int except)
Definition at line 620 of file interf.c.
References find_use_node_in_list(), name, NULL, and use_tree.
Referenced by export_header().
init_use_tree()
void init_use_tree (void)
Definition at line 513 of file interf.c.
References use_tree, and use_tree_end.
Referenced by begin_module(), end_module(), import_done(), mod_init(), and rw_import_state().
interf_init()
void interf_init (void)
'interface' initialization, called once per compilation (source file).
Definition at line 71 of file interf.c.
References assert.
Referenced by init().
ipa_export()
void ipa_export (void)
Definition at line 1491 of file main.c.
ipa_export_close()
void ipa_export_close (void)
Definition at line 1492 of file main.c.
Referenced by finish().
ipa_export_open()
void ipa_export_open (char * export_filename)
Definition at line 1496 of file main.c.
ipa_import_open()
void ipa_import_open (char * import_file, BIGUINT offset)
Definition at line 1500 of file main.c.
remove_from_use_tree()
void remove_from_use_tree (char * module)
Definition at line 518 of file interf.c.
References n, uses_list::next, prev, and use_tree.
Referenced by apply_use_stmts().
symbol_is_visible()
int symbol_is_visible (int sptralias)
update_use_tree_exceptions()
void update_use_tree_exceptions (void)
Definition at line 823 of file interf.c.
References update_list_exceptions(), and use_tree.
Referenced by apply_use().
Variable Documentation
exportb
EXPORTB exportb extern
Definition at line 96 of file exterf.c.
Referenced by apply_use_stmts(), end_module(), export(), export_ieee_arith_libraries(), export_iso_c_libraries(), export_iso_fortran_env_libraries(), import(), mod_init(), and new_dtypes().
imported_modules
struct imported_modules_struct imported_modules
module_directory_list
moddir_list* module_directory_list extern
Definition at line 1143 of file main.c.
Referenced by export_all(), get_module_file_name(), and init().