flang: invar.c File Reference
invar.c File Reference
optimizer submodule responsible for invariant analysis for a given loop. Used by the optimizer and vectorizer.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "ast.h"
#include "nme.h"
#include "optimize.h"
#include "semant.h"
Functions
static LOGICAL invar_src (int)
static void invar_init (int)
static void invar_mark (int)
static void invar_end (int)
static void invar_motion (int)
static void initnames (STL *)
static void cleannames (STL *)
void invariant (int lp)
void invariant_nomotion (int lp)
void invariant_mark (int ilix, int mark)
void invariant_unmark (void)
void invariant_unmarkv (void)
void restore_hoist_stmt (int lp)
LOGICAL is_invariant (int ilix)
static void compute_invariant (int, int *)
static LOGICAL is_std_hoistable (int, int)
static LOGICAL def_in_innerlp (int lpx, int def_lp)
static LOGICAL has_def_inlp (int ast, int lp, int std)
static LOGICAL is_hoistable (int ast, int std, int lp)
LOGICAL is_sym_invariant_safe (int nme, int lpx)
Variables
static int lpx
static int fgx
static int stdx
static LOGICAL safe
static LOGICAL mark_value
static LOGICAL mark_return
Detailed Description
optimizer submodule responsible for invariant analysis for a given loop. Used by the optimizer and vectorizer.
NOTE: During the detection phase of the analysis, stores are analyzed by traversing the store lists of a loop and its children. A store is marked by recording the store item in the corresponding name's stl field. The lifetime of the names' stl fields extends after the analysis phase so that the general query function, is_invariant, can be provided. The stl fields (and ili marked during the analysis) are cleaned up in unmark/unmarkv.
Definition in file invar.c.
Function Documentation
cleannames()
static void cleannames (STL * stlitem) static
Definition at line 310 of file invar.c.
References cleannames(), i, NME_STL, NULL, STORE_NEXT, STORE_NM, and tmp.
Referenced by cleannames(), invariant_unmark(), and invariant_unmarkv().
compute_invariant()
static void compute_invariant (int ast, int * dummy) static
Definition at line 355 of file invar.c.
References A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, ast, AST_INVP, AST_ISINV, astb, ASTB::atypes, cnt, compute_invariant(), DDTG, DT_ISCMPLX, DT_ISREAL, flg, gbl, i, INV, invariant_mark(), is_alloc_ast(), is_dealloc_ast(), is_sym_invariant_safe(), lpx, mark_value, ndim, NME_STL, NME_TYPE, NOT_INV, NT_VAR, NULL, FLG::opt, OPTDBG, safe, ss, ST_ISVAR, std, stdx, SYMNAME, T_INV, TRUE, and XBIT.
Referenced by compute_invariant(), and invar_src().
def_in_innerlp()
static LOGICAL def_in_innerlp (int lpx, int def_lp) static
Definition at line 603 of file invar.c.
References FALSE, lp, LP_CHILD, LP_SIBLING, lpx, and TRUE.
Referenced by has_def_inlp(), and is_hoistable().
has_def_inlp()
static LOGICAL has_def_inlp (int ast, int lp, int std) static
Definition at line 620 of file invar.c.
References ASD_NDIM, ASD_SUBS, ast, def, DEF_ADDR, DEF_FG, def_in_innerlp(), DEF_LHS, DEF_NEXT, DEF_STD, FALSE, FG_LOOP, lp, ndim, NME_DEF, NME_NM, NME_TYPE, NT_ARR, std, and TRUE.
Referenced by is_std_hoistable().
initnames()
static void initnames (STL * stlitem) static
Definition at line 285 of file invar.c.
References i, initnames(), j, NME_STL, NULL, STORE_NEXT, STORE_NM, STORE_TYPE, and tmp.
Referenced by initnames(), and invar_init().
invar_end()
static void invar_end (int lp) static
Definition at line 275 of file invar.c.
References lp, and restore_hoist_stmt().
Referenced by invariant(), and invariant_nomotion().
invar_init()
static void invar_init (int lp) static
Definition at line 183 of file invar.c.
References gbl, initnames(), lp, LP_STL, lpx, opt, and OPTDBG.
Referenced by invariant(), and invariant_nomotion().
invar_mark()
static void invar_mark (int lp) static
Definition at line 201 of file invar.c.
References FALSE, FG_CS, FG_NEXT, FG_STDFIRST, FG_STDLAST, fgx, gbl, INV, invar_src(), is_dominator(), lp, LP_CS, LP_FG, LP_TAIL, mark_return, mark_value, NOT_INV, OPTDBG, safe, STD_AST, STD_NEXT, stdx, TRUE, and void().
Referenced by invariant(), and invariant_nomotion().
invar_motion()
static void invar_motion (int std) static
Definition at line 572 of file invar.c.
References ast, FALSE, hoist_stmt(), is_alloc_ast(), is_dealloc_ast(), is_std_hoistable(), LP_FG, lpx, std, and STD_AST.
Referenced by invariant().
invar_src()
static LOGICAL invar_src (int ast) static
Definition at line 346 of file invar.c.
References ast, AST_ISINV, ast_traverse(), ast_unvisit(), ast_visit(), compute_invariant(), and NULL.
Referenced by invar_mark(), and is_invariant().
invariant()
void invariant (int lp)
Definition at line 77 of file invar.c.
References FG_LNEXT, FG_STDFIRST, FG_STDLAST, fgx, flg, invar_end(), invar_init(), invar_mark(), invar_motion(), lp, LP_CS, LP_DSTDF, LP_HEAD, LP_HSTDF, LP_MEXITS, LP_PARLOOP, LP_TAIL, FLG::opt, STD_ACCEL, STD_KERNEL, STD_NEXT, stdx, and XBIT.
Referenced by optimize().
invariant_mark()
void invariant_mark (int ilix, int mark)
Definition at line 127 of file invar.c.
References AST_INVP, i, mark(), opt, and OPT_NEED.
Referenced by compute_invariant(), and hoist_std().
invariant_nomotion()
void invariant_nomotion (int lp)
Definition at line 116 of file invar.c.
References invar_end(), invar_init(), invar_mark(), and lp.
Referenced by get_loopcounts(), and hoist_loop().
invariant_unmark()
void invariant_unmark (void)
Definition at line 143 of file invar.c.
References AST_INVP, AST_ISINV_TEMP, cleannames(), i, LP_STL, lpx, and opt.
invariant_unmarkv()
void invariant_unmarkv (void)
Definition at line 165 of file invar.c.
References AST_INVP, cleannames(), i, LP_STL, lpx, and opt.
Referenced by get_loopcounts(), and hoist_loop().
is_hoistable()
static LOGICAL is_hoistable (int ast, int std, int lp) static
Definition at line 675 of file invar.c.
References ASD_NDIM, ASD_SUBS, ast, def, DEF_ADDR, DEF_DU, DEF_FG, def_in_innerlp(), DEF_NEXT, DEF_STD, FALSE, FG_LOOP, hoist_stmt(), i, is_hoistable(), is_std_hoistable(), lp, LP_CALLFG, LP_CALLINTERNAL, LP_CHILD, LP_FG, LP_STL, ndim, DU_TAG::next, NME_DEF, NME_NM, NME_SYM, NME_TYPE, NT_VAR, r, s, sptr, std, STL_TAG::store, STORE_NEXT, STORE_NM, TRUE, DU_TAG::use, and USE_STD.
Referenced by is_hoistable(), and is_std_hoistable().
is_invariant()
LOGICAL is_invariant (int ilix)
Definition at line 331 of file invar.c.
References gbl, invar_src(), and OPTDBG.
Referenced by has_invar_subs(), hoist_std(), is_invariant_base(), and is_invariant_list().
is_std_hoistable()
static LOGICAL is_std_hoistable (int std, int lpx) static
Definition at line 822 of file invar.c.
References a, ast, FALSE, has_def_inlp(), i, is_alloc_ast(), is_dealloc_ast(), is_hoistable(), LP_CALLFG, LP_CALLINTERNAL, lpx, n, r, s, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, std, STD_AST, and TRUE.
Referenced by invar_motion(), and is_hoistable().
is_sym_invariant_safe()
LOGICAL is_sym_invariant_safe (int nme, int lpx)
Definition at line 959 of file invar.c.
References FALSE, IS_LCL_OR_DUM, IS_PRIVATE, is_sym_ptrsafe(), LP_CALLFG, LP_CALLINTERNAL, LP_CSECT, LP_PARREGN, LP_PARSECT, LP_PTR_STORE, LP_STL_PAR, lpx, NME_SYM, NULL, q, and TRUE.
Referenced by compute_invariant(), and hoist_std().
restore_hoist_stmt()
void restore_hoist_stmt (int lp)
Definition at line 5811 of file outconv.c.
References FG_LNEXT, FG_LPREV, FG_STDFIRST, FG_STDLAST, lp, LP_DSTDF, LP_HEAD, LP_HSTDF, LP_TAIL, next, prev, std, STD_FG, STD_NEXT, and STD_PREV.
Referenced by invar_end().
Variable Documentation
fgx
int fgx static
Definition at line 66 of file invar.c.
Referenced by add_empty_succ(), add_pred(), add_succ(), alldefs_allocsafe(), append_succ(), can_copy_def(), copy_const(), def_in_out(), def_ok(), delete_fg(), dmpilt(), fillin_succ(), find_bivs(), find_next_reaching_def(), find_rdef(), flowgraph(), get_lhs_first_defs(), invar_mark(), invariant(), lhs_needtmp(), pred_of_loop(), rdilts(), sortloops(), unlnkilt(), and wrilts().
lpx
int lpx static
Definition at line 66 of file invar.c.
Referenced by compute_invariant(), def_in_innerlp(), invar_init(), invar_motion(), invariant_unmark(), invariant_unmarkv(), is_std_hoistable(), and is_sym_invariant_safe().
mark_return
LOGICAL mark_return static
Definition at line 71 of file invar.c.
Referenced by invar_mark().
mark_value
LOGICAL mark_value static
Definition at line 68 of file invar.c.
Referenced by compute_invariant(), and invar_mark().
safe
LOGICAL safe static
Definition at line 67 of file invar.c.
Referenced by compute_invariant(), and invar_mark().
stdx
int stdx static
Definition at line 66 of file invar.c.
Referenced by _ptrassign(), _ptrassign_copy(), _ptrassign_set(), _ptrassign_set_ast(), analyze(), bblock(), check_pte(), compute_invariant(), delilt(), do_targets(), dsstd(), dsstds(), dstd(), dstdp(), dstdps(), dstdr(), dstds(), dstdtree(), dumpstdtrees(), f90_fini_pointsto(), f90_init(), find_pointer_assignments_f90(), flowgraph(), inline_RTE_set_type(), invar_mark(), invariant(), points_to(), points_to_anal(), pstride_analysis(), putstdassigns(), putstdpta(), remove_block(), save_contained(), set_std_fg(), set_std_pta(), unconditional_branches(), and unlnkilt().