flang: ioargs.c File Reference
ioargs.c File Reference
Functions
char ** __io_get_argv ()
void __io_set_argv (char **v)
int __io_get_argc ()
void __io_set_argc (int v)
Variables
char ** __argv_save
int __argc_save
Function Documentation
__io_get_argc()
int __io_get_argc ()
Definition at line 30 of file ioargs.c.
References __argc_save.
Referenced by ENT3F(), ENTF90(), and ENTRY().
__io_get_argv()
char ** __io_get_argv ()
Definition at line 14 of file ioargs.c.
References __argv_save.
Referenced by __fort_initarg(), ENT3F(), ENTF90(), and print_back_trace_line().
__io_set_argc()
void __io_set_argc (int v)
Definition at line 38 of file ioargs.c.
References __argc_save.
Referenced by main().
__io_set_argv()
void __io_set_argv (char ** v)
Definition at line 22 of file ioargs.c.
References __argv_save.
Referenced by main().
Variable Documentation
__argc_save
int __argc_save
Definition at line 9 of file ioargs.c.
Referenced by __io_get_argc(), and __io_set_argc().
__argv_save
char** __argv_save
Definition at line 8 of file ioargs.c.
Referenced by __io_get_argv(), and __io_set_argv().