flang: iostdinit.c File Reference
iostdinit.c File Reference
#include <stdio.h>
#include <sys/stat.h>
#include <unistd.h>
#include <time.h>
#include <errno.h>
Functions
char ** __io_environ ()
int __io_errno ()
void __io_set_errno (int value)
void * __io_stdin (void)
void * __io_stdout (void)
void * __io_stderr (void)
int __io_getc (void *p)
int __io_putc (int x, void *p)
int __io_getchar (void)
int __io_putchar (int x)
void __io_clearerr (void *p)
int __io_feof (void *p)
int __io_ferror (void *p)
int __io_getfd (void *fp)
int __io_isatty (int fd)
int __io_binary_mode (void *fp)
int __io_setmode_binary (void *fp)
int __io_ispipe (void *f)
size_t __io_fwrite (char *ptr, size_t size, size_t nitems, FILE *stream)
int __io_timezone (void *tm)
Variables
char ** environ
time_t timezone
Function Documentation
__io_binary_mode()
int __io_binary_mode (void * fp)
Definition at line 170 of file iostdinit.c.
References FILE, fp, mode, and void().
Referenced by __fortio_close(), _f90io_backspace(), _f90io_rewind(), emit_eol(), fw_write_record(), and write_record().
__io_clearerr()
void __io_clearerr (void * p)
Definition at line 134 of file iostdinit.c.
References FILE, and p.
__io_environ()
char ** __io_environ ()
Definition at line 37 of file iostdinit.c.
References environ.
Referenced by __fort_initarg(), and main().
__io_errno()
int __io_errno (void)
Definition at line 51 of file iostdinit.c.
Referenced by __f90io_unf_read(), __f90io_unf_write(), __f90io_usw_read(), __f90io_usw_write(), __fortio_close(), __fortio_open(), __fortio_rwinit(), __fortio_trunc(), __fortio_zeropad(), __INT_T(), __unf_end(), __unf_init(), __usw_end(), _f90io_backspace(), _f90io_fmtr_end(), _f90io_ldw_end(), _f90io_rewind(), asy_wait(), ENT3F(), ENTF90IO(), fr_read_record(), fw_write_record(), inquire(), read_record(), skip_record(), skip_to_nextrec(), write_item(), and write_record().
__io_feof()
int __io_feof (void * p)
Definition at line 140 of file iostdinit.c.
References FILE, and p.
Referenced by __f90io_unf_read(), __f90io_usw_read(), __unf_init(), _f90io_pause(), ENT3F(), fr_read_record(), read_record(), and skip_record().
__io_ferror()
int __io_ferror (void * p)
Definition at line 146 of file iostdinit.c.
References FILE, and p.
Referenced by __fortio_close(), _f90io_backspace(), _f90io_rewind(), and fw_write_record().
__io_fwrite()
size_t __io_fwrite (char * ptr, size_t size, size_t nitems, FILE * stream)
Definition at line 228 of file iostdinit.c.
References c, i, and size.
__io_getc()
int __io_getc (void * p)
Definition at line 109 of file iostdinit.c.
References FILE, and p.
__io_getchar()
int __io_getchar (void)
Definition at line 122 of file iostdinit.c.
__io_getfd()
int __io_getfd (void * fp)
Definition at line 154 of file iostdinit.c.
References FILE, and fp.
Referenced by ENT3F(), and Fio_asy_open().
__io_isatty()
int __io_isatty (int fd)
Definition at line 162 of file iostdinit.c.
References fd.
Referenced by __isatty3f().
__io_ispipe()
int __io_ispipe (void * f)
Definition at line 207 of file iostdinit.c.
References f, FILE, st, and stat.
__io_putc()
int __io_putc (int x, void * p)
Definition at line 115 of file iostdinit.c.
References FILE, p, and x.
__io_putchar()
int __io_putchar (int x)
Definition at line 128 of file iostdinit.c.
References x.
Referenced by __fort_get_scalar().
__io_set_errno()
void __io_set_errno (int value)
Definition at line 59 of file iostdinit.c.
References value().
Referenced by asy_wait(), ENT3F(), Fio_asy_open(), and ufptod().
__io_setmode_binary()
int __io_setmode_binary (void * fp)
Definition at line 193 of file iostdinit.c.
References FILE, fp, and mode.
__io_stderr()
void * __io_stderr (void)
Definition at line 79 of file iostdinit.c.
Referenced by __abort(), __abort_err(), __abort_init(), __abort_trace(), __fort_abortp(), __fort_begpar(), __fort_check_map(), __fort_describe(), __fort_dump_type(), __fort_getmap(), __fort_print_local(), __fort_print_scalar(), __fort_print_vector(), __fort_print_version(), __fort_show_flags(), __fort_show_index(), __fort_show_scalar(), __fort_show_section(), __fortio_eoferr(), __fortio_eorerr(), __fortio_error(), __fortio_init(), __getfile3f(), __llcrit_atfork(), _f90io_f2003_stop_with_ieee_warnings(), _f90io_pause(), _f90io_stop(), _mp_bcs_nest(), _mp_bcs_nest_red(), cpu(), ENT3F(), ENTF90(), ENTF90COMN(), ENTFTN(), Ftn_str_malloc(), Ftn_str_malloc_klen(), ioerrinfo(), MAIN__(), mem(), msg(), print_back_trace_line(), print_loop(), print_row(), and sighand().
__io_stdin()
void * __io_stdin (void)
Definition at line 67 of file iostdinit.c.
Referenced by __fortio_init(), __getfile3f(), and _f90io_pause().
__io_stdout()
void * __io_stdout (void)
Definition at line 73 of file iostdinit.c.
Referenced by __fortio_init(), and __getfile3f().
__io_timezone()
int __io_timezone (void * tm)
Definition at line 263 of file iostdinit.c.
References timezone.
Referenced by ENTFTN().
Variable Documentation
environ
char** environ extern
Definition at line 42 of file initpar.c.
Referenced by __fort_getenv(), __fort_initarg(), and __io_environ().
timezone
time_t timezone extern
Referenced by __fort_gettb(), __fort_second(), __io_timezone(), and ENTFTN().