flang: iterat.c File Reference
iterat.c File Reference
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "soc.h"
#include "semant.h"
#include "ast.h"
#include "gramtk.h"
#include "symutl.h"
#include "extern.h"
#include "comm.h"
#include "ccffinfo.h"
#include "hlvect.h"
Functions
int is_array_element_in_forall (int subs, int std)
LOGICAL is_name_in_expr (int expr, int isptr)
LOGICAL is_lonely_idx (int expr, int isptr)
static void build_dlist (int depends, int forall_list, int lstdx, int rstdx)
static LOGICAL subscr_dependent_check (int expr)
static char * build_name_buffer (int *list, int avl)
static LOGICAL name_dependent_check (int expr)
static LOGICAL expr_dependent_check (int expr)
LOGICAL expr_dependent (int expr, int depends, int lstdx, int rstdx)
LOGICAL is_dependent (int lhs, int rhs, int forall, int lstdx, int rstdx)
LOGICAL subscr_dependent (int expr, int depends, int lstdx, int rstdx)
int replace_expr (int sub_expr, int isptr, int expr, int indirection)
LOGICAL is_equivalence (int sptr1, int sptr2)
Variables
struct {
int * elist
int * dlist
int esize
int eavl
int dsize
int davl
int estdx
int dstdx
int dexpr
int forall_list
} dep = {NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0}
Function Documentation
build_dlist()
static void build_dlist (int depends, int forall_list, int lstdx, int rstdx) static
Definition at line 232 of file iterat.c.
References d, dep, forall_list, interr(), NEED, and NEW.
Referenced by expr_dependent(), is_dependent(), and subscr_dependent().
build_name_buffer()
static char * build_name_buffer (int * list, int avl) static
Definition at line 276 of file iterat.c.
References avl, i, len, list, malloc(), strlen(), and SYMNAME.
Referenced by name_dependent_check().
expr_dependent()
LOGICAL expr_dependent (int expr, int depends, int lstdx, int rstdx)
Definition at line 631 of file iterat.c.
References build_dlist(), and expr_dependent_check().
Referenced by dd_compute(), is_use_lhs(), is_use_lhs_final(), put_forall_pcalls(), remove_from_scalar_subscript(), and rewrite_calls().
expr_dependent_check()
static LOGICAL expr_dependent_check (int expr) static
Definition at line 479 of file iterat.c.
References A_ARGCNTG, argt, ARGT_ARG, expr_dependent_check(), FALSE, i, interr(), n, name_dependent_check(), and TRUE.
Referenced by expr_dependent(), expr_dependent_check(), is_dependent(), and subscr_dependent_check().
is_array_element_in_forall()
int is_array_element_in_forall (int subs, int std)
Definition at line 29 of file iterat.c.
References ASD_NDIM, ASD_SUBS, ast, ASTLI_NEXT, ASTLI_SPTR, i, is_name_in_expr(), j, list, ndim, std, and STD_AST.
Referenced by insert_forall_comm(), and scalar_communication().
is_dependent()
LOGICAL is_dependent (int lhs, int rhs, int forall, int lstdx, int rstdx)
Definition at line 638 of file iterat.c.
References build_dlist(), expr_dependent_check(), FALSE, and lhs.
Referenced by forall_dependency(), forall_dependency_scalarize(), and is_call_dependent().
is_equivalence()
LOGICAL is_equivalence (int sptr1, int sptr2)
Definition at line 725 of file iterat.c.
References FALSE, p, SOC_NEXT, SOC_SPTR, and TRUE.
Referenced by is_name_in_expr(), and name_dependent_check().
is_lonely_idx()
LOGICAL is_lonely_idx (int expr, int isptr)
Definition at line 143 of file iterat.c.
References A_ARGCNTG, argt, ARGT_ARG, FALSE, i, interr(), is_lonely_idx(), n, and TRUE.
Referenced by is_lonely_idx().
is_name_in_expr()
LOGICAL is_name_in_expr (int expr, int isptr)
Definition at line 57 of file iterat.c.
References A_ARGCNTG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, FALSE, i, interr(), is_equivalence(), is_name_in_expr(), n, sptr, and TRUE.
Referenced by canonical_conversion(), eliminate_extra_idx(), forall_semantic(), inline_reduction_f90(), is_array_element_in_forall(), is_duplicate(), is_multiple_idx_in_list(), is_name_in_expr(), and same_forall_bnds().
name_dependent_check()
static LOGICAL name_dependent_check (int expr) static
Definition at line 303 of file iterat.c.
References build_name_buffer(), ccff_info(), d, dd_array_conflict(), DDTG, ddtype(), dep, FLG::depchk, DTY, e, FALSE, flg, i, interr(), is_equivalence(), MSGFTN, NEED, NEW, NULL, FLG::opt, pta_conflict(), STD_LINENO, subscr_dependent_check(), TRUE, and XBIT.
Referenced by expr_dependent_check().
replace_expr()
int replace_expr (int sub_expr, int isptr, int expr, int indirection)
Definition at line 658 of file iterat.c.
References A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, i, mk_binop(), mk_convert(), mk_paren(), mk_subscr(), mk_unop(), nargs, ndim, replace_expr(), sptr, and sptr_of_subscript().
Referenced by forall_2_sec(), and replace_expr().
subscr_dependent()
LOGICAL subscr_dependent (int expr, int depends, int lstdx, int rstdx)
Definition at line 647 of file iterat.c.
References build_dlist(), and subscr_dependent_check().
Referenced by is_fusable().
subscr_dependent_check()
static LOGICAL subscr_dependent_check (int expr) static
Definition at line 554 of file iterat.c.
References A_ARGCNTG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, expr_dependent_check(), FALSE, i, interr(), n, subscr_dependent_check(), and TRUE.
Referenced by name_dependent_check(), subscr_dependent(), and subscr_dependent_check().
Variable Documentation
davl
int davl
Definition at line 218 of file iterat.c.
struct { ... } dep
Referenced by build_dlist(), and name_dependent_check().
dexpr
int dexpr
Definition at line 220 of file iterat.c.
dlist
int* dlist
Definition at line 216 of file iterat.c.
dsize
int dsize
Definition at line 218 of file iterat.c.
Referenced by gen_call_expr().
dstdx
int dstdx
Definition at line 219 of file iterat.c.
eavl
int eavl
Definition at line 217 of file iterat.c.
elist
int* elist
Definition at line 215 of file iterat.c.
esize
int esize
Definition at line 217 of file iterat.c.
estdx
int estdx
Definition at line 219 of file iterat.c.
forall_list
int forall_list
Definition at line 220 of file iterat.c.
Referenced by build_dlist(), and contains_forall_index().