flang: kmpcutil.h File Reference
kmpcutil.h File Reference
Various definitions for the kmpc runtime.
#include "gbldefs.h"
#include "global.h"
#include "symtab.h"
#include "ili.h"
Classes
struct _loop_args_t
struct kmpc_api_entry_t
struct any_kmpc_struct
Macros
#define KMPC_TASK_UNTIED 0x00
#define KMPC_TASK_TIED 0x01
#define KMPC_TASK_FINAL 0x02
#define KMPC_TASK_MERGED_IF0 0x04
#define KMPC_TASK_DTOR_THK 0x08
#define KMPC_TASK_PROXY 0x10
#define KMPC_TASK_PRIORITY 0x20
Typedefs
typedef enum _kmpc_sched_e kmpc_sched_e
typedef enum RegionType RegionType
typedef struct _loop_args_t loop_args_t
typedef struct any_kmpc_struct KMPC_ST_TYPE
Enumerations
enum _kmpc_sched_e {
KMP_SCH_NONE = 0 , KMP_SCH_LOWER = 32 , KMP_SCH_STATIC_CHUNKED = 33 , KMP_SCH_STATIC = 34 ,
KMP_SCH_DYNAMIC_CHUNKED = 35 , KMP_SCH_GUIDED_CHUNKED = 36 , KMP_SCH_RUNTIME_CHUNKED = 37 , KMP_SCH_AUTO = 38 ,
KMP_SCH_STATIC_STEAL = 44 , KMP_SCH_UPPER = 45 , KMP_ORD_LOWER = 64 , KMP_ORD_STATIC_CHUNKED = 65 ,
KMP_ORD_STATIC = 66 , KMP_ORD_DYNAMIC_CHUNKED = 67 , KMP_ORD_GUIDED_CHUNKED = 68 , KMP_ORD_RUNTIME = 69 ,
KMP_ORD_AUTO = 70 , KMP_ORD_UPPER = 72 , KMP_DISTRIBUTE_STATIC_CHUNKED = 91 , KMP_DISTRIBUTE_STATIC = 92 ,
KMP_DISTRIBUTE_STATIC_CHUNKED_CHUNKONE = 93 , KMP_NM_LOWER = 160 , KMP_NM_STATIC = 162 , KMP_NM_GUIDED_CHUNKED = 164 ,
KMP_NM_AUTO = 166 , KMP_NM_ORD_STATIC = 194 , KMP_NM_ORD_AUTO = 198 , KMP_NM_UPPER = 200 ,
KMP_SCH_DEFAULT = KMP_SCH_STATIC
}
enum RegionType { OPENMP , OPENACC }
enum {
KMPC_API_BAD , KMPC_API_FORK_CALL , KMPC_API_BARRIER , KMPC_API_CANCEL_BARRIER ,
KMPC_API_COPYPRIVATE , KMPC_API_CRITICAL , KMPC_API_END_CRITICAL , KMPC_API_SINGLE ,
KMPC_API_END_SINGLE , KMPC_API_MASTER , KMPC_API_END_MASTER , KMPC_API_FLUSH ,
KMPC_API_ORDERED , KMPC_API_END_ORDERED , KMPC_API_FOR_STATIC_INIT , KMPC_API_FOR_STATIC_FINI ,
KMPC_API_DISPATCH_INIT , KMPC_API_DISPATCH_NEXT , KMPC_API_DISPATCH_FINI , KMPC_API_GLOBAL_THREAD_NUM ,
KMPC_API_GLOBAL_NUM_THREADS , KMPC_API_BOUND_THREAD_NUM , KMPC_API_BOUND_NUM_THREADS , KMPC_API_PUSH_NUM_THREADS ,
KMPC_API_SERIALIZED_PARALLEL , KMPC_API_END_SERIALIZED_PARALLEL , KMPC_API_THREADPRIVATE_CACHED , KMPC_API_THREADPRIVATE_REGISTER_VEC ,
KMPC_API_THREADPRIVATE_REGISTER , KMPC_API_TASK_ALLOC , KMPC_API_TASK , KMPC_API_TASK_BEGIN_IF0 ,
KMPC_API_TASK_COMPLETE_IF0 , KMPC_API_TASK_WAIT , KMPC_API_TASK_YIELD , KMPC_API_CANCEL ,
KMPC_API_CANCELLATIONPOINT , KMPC_API_TASKGROUP , KMPC_API_END_TASKGROUP , KMPC_API_TASK_WITH_DEPS ,
KMPC_API_WAIT_DEPS , KMPC_API_TASKLOOP , KMPC_API_THREADPRIVATE , KMPC_API_PUSH_NUM_TEAMS ,
KMPC_API_FORK_TEAMS , KMPC_API_DIST_FOR_STATIC_INIT , KMPC_API_DIST_DISPATCH_INIT , KMPC_API_PUSH_PROC_BIND ,
KMPC_API_ATOMIC_RD , KMPC_API_ATOMIC_WR , KMPC_API_PUSH_TARGET_TRIPCOUNT , KMPC_API_FOR_STATIC_INIT_SIMPLE_SPMD ,
KMPC_API_SPMD_KERNEL_INIT , KMPC_API_KERNEL_INIT_PARAMS , KMPC_API_SHUFFLE_I32 , KMPC_API_SHUFFLE_I64 ,
KMPC_API_NVPTX_PARALLEL_REDUCE_NOWAIT_SIMPLE_SPMD , KMPC_API_NVPTX_END_REDUCE_NOWAIT , KMPC_API_N_ENTRIES
}
Functions
int ll_make_kmpc_atomic_read (int *opnd, DTYPE dtype)
...
int ll_make_kmpc_atomic_write (int *opnd, DTYPE dtype)
...
int ll_make_kmpc_barrier (void)
...
int ll_make_kmpc_bound_num_threads (void)
...
int ll_make_kmpc_bound_thread_num (void)
...
int ll_make_kmpc_cancel_barrier (void)
...
int ll_make_kmpc_cancel (int argili)
...
int ll_make_kmpc_cancellationpoint (int argili)
...
int ll_make_kmpc_copyprivate (SPTR array_sptr, int single_ili, int copyfunc_acon)
Return a result or JSR ili to __kmpc_copyprivate()
int ll_make_kmpc_critical (SPTR sem)
Return a result or JSR ili to __kmpc_critical()
int ll_make_kmpc_dispatch_fini (DTYPE dtype)
...
int ll_make_kmpc_dispatch_init (const loop_args_t *inargs)
...
int ll_make_kmpc_dispatch_next (SPTR lower, SPTR upper, SPTR stride, SPTR last, DTYPE dtype)
int ll_make_kmpc_dist_dispatch_init (const loop_args_t *inargs)
...
int ll_make_kmpc_dist_for_static_init (const loop_args_t *inargs)
...
int ll_make_kmpc_end_critical (SPTR sem)
Return a result or JSR ili to __kmpc_end_critical()
int ll_make_kmpc_end_master (void)
...
int ll_make_kmpc_end_ordered (void)
...
int ll_make_kmpc_end_serialized_parallel (void)
...
int ll_make_kmpc_end_single (void)
...
int ll_make_kmpc_end_taskgroup (void)
...
int ll_make_kmpc_flush (void)
Return a result or JSR ili to __kmpc_flush()
int ll_make_kmpc_fork_call (SPTR sptr, int argc, int *arglist, RegionType rt, int ngangs_ili)
...
int ll_make_kmpc_fork_teams (SPTR sptr, int argc, int *arglist)
...
int ll_make_kmpc_for_static_fini (void)
...
int ll_make_kmpc_for_static_init_args (DTYPE dtype, int *inargs)
...
int ll_make_kmpc_for_static_init (const loop_args_t *inargs)
...
int ll_make_kmpc_global_num_threads (void)
...
int ll_make_kmpc_global_thread_num (void)
...
int ll_make_kmpc_master (void)
...
int ll_make_kmpc_omp_wait_deps (const loop_args_t *inargs)
...
int ll_make_kmpc_ordered (void)
...
int ll_make_kmpc_push_num_teams (int nteams_ili, int thread_limit_ili)
...
int ll_make_kmpc_push_num_threads (int argili)
...
int ll_make_kmpc_push_proc_bind (int argili)
...
int ll_make_kmpc_serialized_parallel (void)
...
int ll_make_kmpc_single (void)
...
DTYPE ll_make_kmpc_struct_type (int count, const char *name, KMPC_ST_TYPE *meminfo, ISZ_T sz)
...
SPTR ll_make_kmpc_task_arg (SPTR base, SPTR sptr, SPTR scope_sptr, SPTR flags_sptr)
int ll_make_kmpc_task_begin_if0 (SPTR task_sptr)
int ll_make_kmpc_task_complete_if0 (SPTR task_sptr)
int ll_make_kmpc_taskgroup (void)
...
int ll_make_kmpc_task (SPTR task_sptr)
...
int ll_make_kmpc_taskloop (int *inargs)
...
int ll_make_kmpc_task_wait (void)
...
int ll_make_kmpc_task_with_deps (const loop_args_t *inargs)
...
int ll_make_kmpc_task_yield (void)
...
int ll_make_kmpc_threadprivate_cached (int data_ili, int size_ili, int cache_ili)
...
int ll_make_kmpc_threadprivate (int data_ili, int size_ili)
...
int ll_make_kmpc_threadprivate_register (int data_ili, int ctor_ili, int cctor_ili, int dtor_ili)
...
int ll_make_kmpc_threadprivate_register_vec (int data_ili, int ctor_ili, int cctor_ili, int dtor_ili, int size_ili)
...
int mp_to_kmpc_tasking_flags (const int mp)
...
kmpc_sched_e mp_sched_to_kmpc_sched (int sched)
Given a MP_ or DI_ schedule type and return the KMPC equivalent.
void reset_kmpc_ident_dtype (void)
...
Detailed Description
Various definitions for the kmpc runtime.
Definition in file kmpcutil.h.
Macro Definition Documentation
KMPC_TASK_DTOR_THK
#define KMPC_TASK_DTOR_THK 0x08
Definition at line 27 of file kmpcutil.h.
KMPC_TASK_FINAL
#define KMPC_TASK_FINAL 0x02
Definition at line 25 of file kmpcutil.h.
KMPC_TASK_MERGED_IF0
#define KMPC_TASK_MERGED_IF0 0x04
Definition at line 26 of file kmpcutil.h.
KMPC_TASK_PRIORITY
#define KMPC_TASK_PRIORITY 0x20
Definition at line 29 of file kmpcutil.h.
KMPC_TASK_PROXY
#define KMPC_TASK_PROXY 0x10
Definition at line 28 of file kmpcutil.h.
KMPC_TASK_TIED
#define KMPC_TASK_TIED 0x01
Definition at line 24 of file kmpcutil.h.
KMPC_TASK_UNTIED
#define KMPC_TASK_UNTIED 0x00
Definition at line 23 of file kmpcutil.h.
Typedef Documentation
kmpc_sched_e
typedef enum _kmpc_sched_e kmpc_sched_e
KMPC_ST_TYPE
typedef struct any_kmpc_struct KMPC_ST_TYPE
loop_args_t
typedef struct _loop_args_t loop_args_t
RegionType
typedef enum RegionType RegionType
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
KMPC_API_BAD
KMPC_API_FORK_CALL
KMPC_API_BARRIER
KMPC_API_CANCEL_BARRIER
KMPC_API_COPYPRIVATE
KMPC_API_CRITICAL
KMPC_API_END_CRITICAL
KMPC_API_SINGLE
KMPC_API_END_SINGLE
KMPC_API_MASTER
KMPC_API_END_MASTER
KMPC_API_FLUSH
KMPC_API_ORDERED
KMPC_API_END_ORDERED
KMPC_API_FOR_STATIC_INIT
KMPC_API_FOR_STATIC_FINI
KMPC_API_DISPATCH_INIT
KMPC_API_DISPATCH_NEXT
KMPC_API_DISPATCH_FINI
KMPC_API_GLOBAL_THREAD_NUM
KMPC_API_GLOBAL_NUM_THREADS
KMPC_API_BOUND_THREAD_NUM
KMPC_API_BOUND_NUM_THREADS
KMPC_API_PUSH_NUM_THREADS
KMPC_API_SERIALIZED_PARALLEL
KMPC_API_END_SERIALIZED_PARALLEL
KMPC_API_THREADPRIVATE_CACHED
KMPC_API_THREADPRIVATE_REGISTER_VEC
KMPC_API_THREADPRIVATE_REGISTER
KMPC_API_TASK_ALLOC
KMPC_API_TASK
KMPC_API_TASK_BEGIN_IF0
KMPC_API_TASK_COMPLETE_IF0
KMPC_API_TASK_WAIT
KMPC_API_TASK_YIELD
KMPC_API_CANCEL
KMPC_API_CANCELLATIONPOINT
KMPC_API_TASKGROUP
KMPC_API_END_TASKGROUP
KMPC_API_TASK_WITH_DEPS
KMPC_API_WAIT_DEPS
KMPC_API_TASKLOOP
KMPC_API_THREADPRIVATE
KMPC_API_PUSH_NUM_TEAMS
KMPC_API_FORK_TEAMS
KMPC_API_DIST_FOR_STATIC_INIT
KMPC_API_DIST_DISPATCH_INIT
KMPC_API_PUSH_PROC_BIND
KMPC_API_ATOMIC_RD
KMPC_API_ATOMIC_WR
KMPC_API_PUSH_TARGET_TRIPCOUNT
KMPC_API_FOR_STATIC_INIT_SIMPLE_SPMD
KMPC_API_SPMD_KERNEL_INIT
KMPC_API_KERNEL_INIT_PARAMS
KMPC_API_SHUFFLE_I32
KMPC_API_SHUFFLE_I64
KMPC_API_NVPTX_PARALLEL_REDUCE_NOWAIT_SIMPLE_SPMD
KMPC_API_NVPTX_END_REDUCE_NOWAIT
KMPC_API_N_ENTRIES
Definition at line 102 of file kmpcutil.h.
_kmpc_sched_e
enum _kmpc_sched_e
Enumerator
KMP_SCH_NONE
KMP_SCH_LOWER
KMP_SCH_STATIC_CHUNKED
KMP_SCH_STATIC
KMP_SCH_DYNAMIC_CHUNKED
KMP_SCH_GUIDED_CHUNKED
KMP_SCH_RUNTIME_CHUNKED
KMP_SCH_AUTO
KMP_SCH_STATIC_STEAL
KMP_SCH_UPPER
KMP_ORD_LOWER
KMP_ORD_STATIC_CHUNKED
KMP_ORD_STATIC
KMP_ORD_DYNAMIC_CHUNKED
KMP_ORD_GUIDED_CHUNKED
KMP_ORD_RUNTIME
KMP_ORD_AUTO
KMP_ORD_UPPER
KMP_DISTRIBUTE_STATIC_CHUNKED
KMP_DISTRIBUTE_STATIC
KMP_DISTRIBUTE_STATIC_CHUNKED_CHUNKONE
KMP_NM_LOWER
KMP_NM_STATIC
KMP_NM_GUIDED_CHUNKED
KMP_NM_AUTO
KMP_NM_ORD_STATIC
KMP_NM_ORD_AUTO
KMP_NM_UPPER
KMP_SCH_DEFAULT
Definition at line 36 of file kmpcutil.h.
RegionType
enum RegionType
Enumerator
OPENMP
OPENACC
Definition at line 68 of file kmpcutil.h.
Function Documentation
ll_make_kmpc_atomic_read()
int ll_make_kmpc_atomic_read (int * opnd, DTYPE dtype)
...
Definition at line 1464 of file kmpcutil.cpp.
References args, DT_CMPLX, DT_CPTR, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, DT_LOG, gen_null_arg(), KMPC_API_ATOMIC_RD, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and size_of().
Referenced by _exp_mp_atomic_read().
ll_make_kmpc_atomic_write()
int ll_make_kmpc_atomic_write (int * opnd, DTYPE dtype)
...
Definition at line 1420 of file kmpcutil.cpp.
References args, DT_CMPLX, DT_CPTR, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, DT_LOG, gen_null_arg(), KMPC_API_ATOMIC_WR, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and size_of().
Referenced by _exp_mp_atomic_write().
ll_make_kmpc_barrier()
int ll_make_kmpc_barrier (void)
...
Referenced by addCopyinInplace(), exp_smp(), makeCopyprivArray_tls(), and section_create_endblock().
ll_make_kmpc_bound_num_threads()
int ll_make_kmpc_bound_num_threads (void)
...
ll_make_kmpc_bound_thread_num()
int ll_make_kmpc_bound_thread_num (void)
...
ll_make_kmpc_cancel()
int ll_make_kmpc_cancel (int argili)
...
Referenced by exp_smp().
ll_make_kmpc_cancel_barrier()
int ll_make_kmpc_cancel_barrier (void)
...
ll_make_kmpc_cancellationpoint()
int ll_make_kmpc_cancellationpoint (int argili)
...
Referenced by exp_smp().
ll_make_kmpc_copyprivate()
int ll_make_kmpc_copyprivate (SPTR array_sptr, int single_ili, int copyfunc_acon)
Return a result or JSR ili to __kmpc_copyprivate()
Definition at line 761 of file kmpcutil.cpp.
References ad_acon(), ad_icon, ad_kconi(), args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_COPYPRIVATE, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and TARGET_PTRSIZE.
Referenced by exp_smp().
ll_make_kmpc_critical()
int ll_make_kmpc_critical (SPTR sem)
Return a result or JSR ili to __kmpc_critical()
Definition at line 783 of file kmpcutil.cpp.
References ad_acon(), ad_aconi(), args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_CRITICAL, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and sem.
Referenced by add_mp_p(), and addMpUnp().
ll_make_kmpc_dispatch_fini()
int ll_make_kmpc_dispatch_fini (DTYPE dtype)
...
Definition at line 1347 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, gen_null_arg(), is_signed(), KMPC_API_DISPATCH_FINI, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and size_of().
Referenced by exp_smp().
ll_make_kmpc_dispatch_init()
int ll_make_kmpc_dispatch_init (const loop_args_t * inargs)
...
Definition at line 1246 of file kmpcutil.cpp.
References ad_icon, args, chunk, _loop_args_t::chunk, DBGBIT, DT_CPTR, DT_INT, _loop_args_t::dtype, dump_loop_args(), gen_null_arg(), ikmove(), is_signed(), kimove(), KMPC_API_DISPATCH_INIT, ld_sptr(), ll_get_gtid_val_ili(), lower(), _loop_args_t::lower, mk_kmpc_api_call(), mp_sched_to_kmpc_sched(), _loop_args_t::sched, size_of(), stride, _loop_args_t::stride, _loop_args_t::upper, and upper().
Referenced by exp_smp().
ll_make_kmpc_dispatch_next()
int ll_make_kmpc_dispatch_next (SPTR lower, SPTR upper, SPTR stride, SPTR last, DTYPE dtype)
Return a result or JSR ili to __kmpc_dispatch_next_<size><signed|unsigned> lower, upper, stride: sptrs
Definition at line 1217 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, GBL_CURRFUNC, gen_null_arg(), getccsym_sc(), is_signed(), KMPC_API_DISPATCH_NEXT, last, ll_get_gtid_val_ili(), lower(), mk_address(), mk_kmpc_api_call(), size_of(), stb, stride, and upper().
Referenced by exp_smp().
ll_make_kmpc_dist_dispatch_init()
int ll_make_kmpc_dist_dispatch_init (const loop_args_t * inargs)
...
Definition at line 1292 of file kmpcutil.cpp.
References ad_icon, args, chunk, _loop_args_t::chunk, DBGBIT, DT_CPTR, DT_INT, _loop_args_t::dtype, dump_loop_args(), GBL_CURRFUNC, gen_null_arg(), getccsym_sc(), ikmove(), is_signed(), kimove(), KMPC_API_DIST_DISPATCH_INIT, last, _loop_args_t::last, ld_sptr(), ll_get_gtid_val_ili(), lower(), _loop_args_t::lower, mk_address(), mk_kmpc_api_call(), mp_sched_to_kmpc_sched(), _loop_args_t::sched, size_of(), stb, stride, _loop_args_t::stride, _loop_args_t::upper, and upper().
Referenced by exp_smp().
ll_make_kmpc_dist_for_static_init()
int ll_make_kmpc_dist_for_static_init (const loop_args_t * inargs)
...
Definition at line 1162 of file kmpcutil.cpp.
References ad_icon, args, chunk, _loop_args_t::chunk, DBGBIT, DT_CPTR, DT_INT, _loop_args_t::dtype, dump_loop_args(), GBL_CURRFUNC, gen_null_arg(), getccsym_sc(), ikmove(), is_signed(), kimove(), KMPC_API_DIST_FOR_STATIC_INIT, last, _loop_args_t::last, ld_sptr(), ll_get_gtid_val_ili(), lower(), _loop_args_t::lower, mk_address(), mk_kmpc_api_call(), mp_sched_to_kmpc_sched(), _loop_args_t::sched, size_of(), stb, stride, _loop_args_t::stride, _loop_args_t::upper, upper(), and _loop_args_t::upperd.
Referenced by exp_smp().
ll_make_kmpc_end_critical()
int ll_make_kmpc_end_critical (SPTR sem)
Return a result or JSR ili to __kmpc_end_critical()
Definition at line 797 of file kmpcutil.cpp.
References ad_acon(), ad_aconi(), args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_END_CRITICAL, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and sem.
Referenced by add_mp_v(), and addMpUnv().
ll_make_kmpc_end_master()
int ll_make_kmpc_end_master (void)
...
Referenced by exp_smp().
ll_make_kmpc_end_ordered()
int ll_make_kmpc_end_ordered (void)
...
Referenced by exp_smp().
ll_make_kmpc_end_serialized_parallel()
int ll_make_kmpc_end_serialized_parallel (void)
...
Definition at line 836 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_END_SERIALIZED_PARALLEL, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_end_single()
int ll_make_kmpc_end_single (void)
...
Referenced by exp_smp().
ll_make_kmpc_end_taskgroup()
int ll_make_kmpc_end_taskgroup (void)
...
Referenced by exp_smp().
ll_make_kmpc_flush()
int ll_make_kmpc_flush (void)
Return a result or JSR ili to __kmpc_flush()
Definition at line 752 of file kmpcutil.cpp.
References args, DT_CPTR, gen_null_arg(), KMPC_API_FLUSH, and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_for_static_fini()
int ll_make_kmpc_for_static_fini (void)
...
Referenced by exp_smp(), and section_create_endblock().
ll_make_kmpc_for_static_init()
int ll_make_kmpc_for_static_init (const loop_args_t * inargs)
...
Definition at line 1109 of file kmpcutil.cpp.
References ad_icon, args, chunk, _loop_args_t::chunk, DBGBIT, DT_CPTR, DT_INT, _loop_args_t::dtype, dump_loop_args(), GBL_CURRFUNC, gen_null_arg(), getccsym_sc(), ikmove(), is_signed(), kimove(), KMPC_API_FOR_STATIC_INIT, last, _loop_args_t::last, ld_sptr(), ll_get_gtid_val_ili(), lower(), _loop_args_t::lower, mk_address(), mk_kmpc_api_call(), mp_sched_to_kmpc_sched(), _loop_args_t::sched, size_of(), stb, stride, _loop_args_t::stride, _loop_args_t::upper, and upper().
Referenced by exp_smp().
ll_make_kmpc_for_static_init_args()
int ll_make_kmpc_for_static_init_args (DTYPE dtype, int * inargs)
...
Definition at line 1080 of file kmpcutil.cpp.
References ad_icon, args, DT_CPTR, DT_INT, gen_null_arg(), is_signed(), KMPC_API_FOR_STATIC_INIT, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and size_of().
Referenced by exp_smp().
ll_make_kmpc_fork_call()
int ll_make_kmpc_fork_call (SPTR sptr, int argc, int * arglist, RegionType rt, int ngangs_ili)
...
Definition at line 706 of file kmpcutil.cpp.
References ad1ili(), ad_icon, args, DT_CPTR, DT_INT, gen_null_arg(), get_acon(), KMPC_API_FORK_CALL, mk_kmpc_api_call(), OPENACC, and sptr.
Referenced by exp_smp().
ll_make_kmpc_fork_teams()
int ll_make_kmpc_fork_teams (SPTR sptr, int argc, int * arglist)
...
Definition at line 739 of file kmpcutil.cpp.
References ad1ili(), ad_icon, args, DT_CPTR, DT_INT, gen_null_arg(), get_acon(), KMPC_API_FORK_TEAMS, mk_kmpc_api_call(), and sptr.
Referenced by exp_smp().
ll_make_kmpc_global_num_threads()
int ll_make_kmpc_global_num_threads (void)
...
ll_make_kmpc_global_thread_num()
int ll_make_kmpc_global_thread_num (void)
...
Referenced by llLoadGtid().
ll_make_kmpc_master()
int ll_make_kmpc_master (void)
...
Referenced by exp_smp().
ll_make_kmpc_omp_wait_deps()
int ll_make_kmpc_omp_wait_deps (const loop_args_t * inargs)
...
Definition at line 1394 of file kmpcutil.cpp.
ll_make_kmpc_ordered()
int ll_make_kmpc_ordered (void)
...
Referenced by exp_smp().
ll_make_kmpc_push_num_teams()
int ll_make_kmpc_push_num_teams (int nteams_ili, int thread_limit_ili)
...
Definition at line 812 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_PUSH_NUM_TEAMS, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_push_num_threads()
int ll_make_kmpc_push_num_threads (int argili)
...
Referenced by exp_smp().
ll_make_kmpc_push_proc_bind()
int ll_make_kmpc_push_proc_bind (int argili)
...
Referenced by exp_smp().
ll_make_kmpc_serialized_parallel()
int ll_make_kmpc_serialized_parallel (void)
...
Definition at line 825 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_SERIALIZED_PARALLEL, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_single()
int ll_make_kmpc_single (void)
...
Referenced by exp_smp().
ll_make_kmpc_struct_type()
DTYPE ll_make_kmpc_struct_type (int count, const char * name, KMPC_ST_TYPE * meminfo, ISZ_T sz)
...
Definition at line 385 of file kmpcutil.cpp.
References addnewsym(), cg_get_type(), count, DTySetAlgTy, getsymbol(), i, mem(), MXIDLEN, name, NOSYM, size_of(), SPTR_NULL, and sz.
Referenced by ll_make_uplevel_type().
ll_make_kmpc_task()
int ll_make_kmpc_task (SPTR task_sptr)
...
Definition at line 963 of file kmpcutil.cpp.
References ad2ili(), ad_acon(), addnme(), args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_TASK, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and NT_VAR.
Referenced by exp_smp().
ll_make_kmpc_task_arg()
SPTR ll_make_kmpc_task_arg (SPTR base, SPTR sptr, SPTR scope_sptr, SPTR flags_sptr)
Return an sptr to the allocated task object: __kmp_omp_task_alloc()
Parameters
base sptr for storing return value from __kmpc_omp_task_alloc
sptr sptr representing the outlined function that is the task
scope_sptr ST_BLOCK containing the uplevel block
flags MP_TASK_xxx flags (see mp.h)
Definition at line 911 of file kmpcutil.cpp.
References ad4ili(), ad_acon(), ad_icon, addnme(), args, base, chk_block(), DT_CPTR, DT_INT, gen_null_arg(), getTaskSharedSize(), KMPC_API_TASK_ALLOC, ld_sptr(), ll_get_gtid_val_ili(), ll_get_uplevel_sym(), llmp_get_task(), llmp_task_get_size(), mk_kmpc_api_call(), MSZ_PTR, NT_VAR, size, size_of(), sptr, SPTR_NULL, and task.
Referenced by exp_smp().
ll_make_kmpc_task_begin_if0()
int ll_make_kmpc_task_begin_if0 (SPTR task_sptr)
Return a JSR ili to __kmpc_omp_task_begin_if0.
Parameters
task_sptr sptr representing the allocated task
Definition at line 987 of file kmpcutil.cpp.
References ad2ili(), ad_acon(), args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_TASK_BEGIN_IF0, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_task_complete_if0()
int ll_make_kmpc_task_complete_if0 (SPTR task_sptr)
Return a JSR ili to __kmpc_omp_task_complete_if0.
Parameters
task_sptr sptr representing the allocated task
Definition at line 998 of file kmpcutil.cpp.
References ad2ili(), ad_acon(), args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_TASK_COMPLETE_IF0, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_task_wait()
int ll_make_kmpc_task_wait (void)
...
Referenced by exp_smp().
ll_make_kmpc_task_with_deps()
int ll_make_kmpc_task_with_deps (const loop_args_t * inargs)
...
Definition at line 1388 of file kmpcutil.cpp.
ll_make_kmpc_task_yield()
int ll_make_kmpc_task_yield (void)
...
Definition at line 976 of file kmpcutil.cpp.
References ad_icon, args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_TASK_YIELD, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_taskgroup()
int ll_make_kmpc_taskgroup (void)
...
Referenced by exp_smp().
ll_make_kmpc_taskloop()
int ll_make_kmpc_taskloop (int * inargs)
...
Definition at line 1365 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_TASKLOOP, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_threadprivate()
int ll_make_kmpc_threadprivate (int data_ili, int size_ili)
...
Definition at line 1407 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_THREADPRIVATE, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
ll_make_kmpc_threadprivate_cached()
int ll_make_kmpc_threadprivate_cached (int data_ili, int size_ili, int cache_ili)
...
Definition at line 847 of file kmpcutil.cpp.
References ad1ili(), args, DT_CPTR, DT_INT, gen_null_arg(), IL_RES, ILI_OPC, ILIA_KR, KMPC_API_THREADPRIVATE_CACHED, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by allocThreadprivate().
ll_make_kmpc_threadprivate_register()
int ll_make_kmpc_threadprivate_register (int data_ili, int ctor_ili, int cctor_ili, int dtor_ili)
...
Definition at line 865 of file kmpcutil.cpp.
References args, DT_CPTR, gen_null_arg(), KMPC_API_THREADPRIVATE_REGISTER, and mk_kmpc_api_call().
ll_make_kmpc_threadprivate_register_vec()
int ll_make_kmpc_threadprivate_register_vec (int data_ili, int ctor_ili, int cctor_ili, int dtor_ili, int size_ili)
...
Definition at line 879 of file kmpcutil.cpp.
References args, DT_CPTR, gen_null_arg(), KMPC_API_THREADPRIVATE_REGISTER_VEC, and mk_kmpc_api_call().
mp_sched_to_kmpc_sched()
kmpc_sched_e mp_sched_to_kmpc_sched (int sched)
Given a MP_ or DI_ schedule type and return the KMPC equivalent.
Definition at line 1013 of file kmpcutil.cpp.
References ERR_Warning, error(), gbl, KMP_DISTRIBUTE_STATIC, KMP_DISTRIBUTE_STATIC_CHUNKED, KMP_DISTRIBUTE_STATIC_CHUNKED_CHUNKONE, KMP_ORD_AUTO, KMP_ORD_DYNAMIC_CHUNKED, KMP_ORD_RUNTIME, KMP_ORD_STATIC, KMP_ORD_STATIC_CHUNKED, KMP_SCH_AUTO, KMP_SCH_DEFAULT, KMP_SCH_DYNAMIC_CHUNKED, KMP_SCH_GUIDED_CHUNKED, KMP_SCH_RUNTIME_CHUNKED, KMP_SCH_STATIC, KMP_SCH_STATIC_CHUNKED, MP_SCH_ATTR_CHUNKED, MP_SCH_ATTR_DEVICEDIST, MP_SCH_ATTR_ORDERED, MP_SCH_BLK_ALN, MP_SCH_BLK_CYC, MP_SCH_CHUNK_1, NULL, and SCHED_PREFIX.
Referenced by exp_smp(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), and ll_make_kmpc_for_static_init().
mp_to_kmpc_tasking_flags()
int mp_to_kmpc_tasking_flags (const int mp)
...
Definition at line 900 of file kmpcutil.cpp.
References KMPC_TASK_FINAL, KMPC_TASK_PRIORITY, KMPC_TASK_TIED, KMPC_TASK_UNTIED, MP_TASK_FINAL, MP_TASK_PRIORITY, and MP_TASK_UNTIED.
Referenced by exp_smp().
reset_kmpc_ident_dtype()
void reset_kmpc_ident_dtype (void)
...
Definition at line 1400 of file kmpcutil.cpp.
References kmpc_ident_dtype.
Referenced by ll_reset_parfile(), ll_reset_parfile_(), and llvmAddConcurEntryBlk().