flang: kmpcutil.cpp File Reference
kmpcutil.cpp File Reference
outliner.c - extract regions into subroutines; add uplevel references as arguments
#include <stdio.h>
#include "kmpcutil.h"
#include "error.h"
#include "semant.h"
#include "ilmtp.h"
#include "ilm.h"
#include "ili.h"
#include "expand.h"
#include "exputil.h"
#include "outliner.h"
#include "machreg.h"
#include "mp.h"
#include "ll_structure.h"
#include "llmputil.h"
#include "llutil.h"
#include "cgllvm.h"
#include "cgmain.h"
#include <unistd.h>
#include "regutil.h"
#include "dtypeutl.h"
#include "llassem.h"
#include "ll_ftn.h"
#include "symfun.h"
#include "mwd.h"
Macros
#define _GNU_SOURCE
#define MXIDLEN 250
#define DT_VOID_NONE DT_NONE
#define KMPC_FLAG_NONE 0x00
#define KMPC_FLAG_STR_FMT 0x01 /* Treat KMPC_NAME as a format str */
#define KMPC_NAME(_api) kmpc_api_calls[KMPC_CHK(_api)].name
#define KMPC_RET_DTYPE(_api) kmpc_api_calls[KMPC_CHK(_api)].ret_dtype
#define KMPC_RET_ILIOPC(_api) kmpc_api_calls[KMPC_CHK(_api)].ret_iliopc
#define KMPC_FLAGS(_api) kmpc_api_calls[KMPC_CHK(_api)].flags
#define KMPC_CHK(_api) (((_api) > KMPC_API_BAD && (_api) < KMPC_API_N_ENTRIES) ? _api : KMPC_API_BAD)
#define KMPC_GENERIC_P(_fn, _api)
#define KMPC_GENERIC_P_I(_fn, _api)
#define KMPC_GENERIC_P_2I(_fn, _api, argili)
#define SCHED_PREFIX(_enum_val) (MP_SCH_##_enum_val)
Functions
static void dump_loop_args (const loop_args_t *args)
static int ld_sptr (SPTR sptr)
static int gen_null_arg ()
DTYPE ll_make_kmpc_struct_type (int count, const char *name, KMPC_ST_TYPE *meminfo, ISZ_T sz)
...
static SPTR ll_make_kmpc_proto (const char *nm, int kmpc_api, int argc, DTYPE *args)
static const char * build_kmpc_api_name (int kmpc_api, va_list va)
static int mk_kmpc_api_call (int kmpc_api, int n_args, DTYPE *arg_dtypes, int *arg_ilis,...)
static int ll_make_kmpc_generic_ptr (int kmpc_api)
static int ll_make_kmpc_generic_ptr_int (int kmpc_api)
static int ll_make_kmpc_generic_ptr_2int (int kmpc_api, int argili)
KMPC_GENERIC_P_2I (ll_make_kmpc_push_num_threads, KMPC_API_PUSH_NUM_THREADS, argili) KMPC_GENERIC_P_2I(ll_make_kmpc_cancellationpoint
argili int ll_make_kmpc_fork_call (SPTR sptr, int argc, int *arglist, RegionType rt, int ngangs_ili)
...
int ll_make_kmpc_fork_teams (SPTR sptr, int argc, int *arglist)
...
int ll_make_kmpc_flush (void)
Return a result or JSR ili to __kmpc_flush()
int ll_make_kmpc_copyprivate (SPTR array_sptr, int single_ili, int copyfunc_acon)
Return a result or JSR ili to __kmpc_copyprivate()
int ll_make_kmpc_critical (SPTR sem)
Return a result or JSR ili to __kmpc_critical()
int ll_make_kmpc_end_critical (SPTR sem)
Return a result or JSR ili to __kmpc_end_critical()
int ll_make_kmpc_push_num_teams (int nteams_ili, int thread_limit_ili)
...
int ll_make_kmpc_serialized_parallel (void)
...
int ll_make_kmpc_end_serialized_parallel (void)
...
int ll_make_kmpc_threadprivate_cached (int data_ili, int size_ili, int cache_ili)
...
int ll_make_kmpc_threadprivate_register (int data_ili, int ctor_ili, int cctor_ili, int dtor_ili)
...
int ll_make_kmpc_threadprivate_register_vec (int data_ili, int ctor_ili, int cctor_ili, int dtor_ili, int size_ili)
...
int mp_to_kmpc_tasking_flags (const int mp)
...
SPTR ll_make_kmpc_task_arg (SPTR base, SPTR sptr, SPTR scope_sptr, SPTR flags_sptr)
int ll_make_kmpc_task (SPTR task_sptr)
...
int ll_make_kmpc_task_yield (void)
...
int ll_make_kmpc_task_begin_if0 (SPTR task_sptr)
int ll_make_kmpc_task_complete_if0 (SPTR task_sptr)
kmpc_sched_e mp_sched_to_kmpc_sched (int sched)
Given a MP_ or DI_ schedule type and return the KMPC equivalent.
static bool is_signed (int dtype)
int ll_make_kmpc_for_static_init_args (DTYPE dtype, int *inargs)
...
int ll_make_kmpc_for_static_init (const loop_args_t *inargs)
...
int ll_make_kmpc_dist_for_static_init (const loop_args_t *inargs)
...
int ll_make_kmpc_dispatch_next (SPTR lower, SPTR upper, SPTR stride, SPTR last, DTYPE dtype)
int ll_make_kmpc_dispatch_init (const loop_args_t *inargs)
...
int ll_make_kmpc_dist_dispatch_init (const loop_args_t *inargs)
...
int ll_make_kmpc_dispatch_fini (DTYPE dtype)
...
int ll_make_kmpc_taskloop (int *inargs)
...
int ll_make_kmpc_task_with_deps (const loop_args_t *inargs)
...
int ll_make_kmpc_omp_wait_deps (const loop_args_t *inargs)
...
void reset_kmpc_ident_dtype (void)
...
int ll_make_kmpc_threadprivate (int data_ili, int size_ili)
...
int ll_make_kmpc_atomic_write (int *opnd, DTYPE dtype)
...
int ll_make_kmpc_atomic_read (int *opnd, DTYPE dtype)
...
Variables
static DTYPE kmpc_ident_dtype
static const struct kmpc_api_entry_t kmpc_api_calls []
KMPC_API_CANCELLATIONPOINT
Detailed Description
outliner.c - extract regions into subroutines; add uplevel references as arguments
Definition in file kmpcutil.cpp.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 15 of file kmpcutil.cpp.
DT_VOID_NONE
#define DT_VOID_NONE DT_NONE
Definition at line 53 of file kmpcutil.cpp.
KMPC_CHK
#define KMPC_CHK (_api) (((_api) > KMPC_API_BAD && (_api) < KMPC_API_N_ENTRIES) ? _api : KMPC_API_BAD)
Definition at line 304 of file kmpcutil.cpp.
KMPC_FLAG_NONE
#define KMPC_FLAG_NONE 0x00
Definition at line 55 of file kmpcutil.cpp.
KMPC_FLAG_STR_FMT
#define KMPC_FLAG_STR_FMT 0x01 /* Treat KMPC_NAME as a format str */
Definition at line 56 of file kmpcutil.cpp.
KMPC_FLAGS
#define KMPC_FLAGS (_api) kmpc_api_calls[KMPC_CHK(_api)].flags
Definition at line 302 of file kmpcutil.cpp.
KMPC_GENERIC_P
#define KMPC_GENERIC_P (_fn, _api)
Value:
  int _fn(void)                            \
  {                                        \
    return ll_make_kmpc_generic_ptr(_api); \
  }
Definition at line 619 of file kmpcutil.cpp.
KMPC_GENERIC_P_2I
#define KMPC_GENERIC_P_2I (_fn, _api, argili)
Value:
  int _fn(int argili)                                   \
  {                                                     \
    return ll_make_kmpc_generic_ptr_2int(_api, argili); \
  }
Definition at line 692 of file kmpcutil.cpp.
KMPC_GENERIC_P_I
#define KMPC_GENERIC_P_I (_fn, _api)
Value:
  int _fn(void)                                \
  {                                            \
    return ll_make_kmpc_generic_ptr_int(_api); \
  }
Definition at line 651 of file kmpcutil.cpp.
KMPC_NAME
#define KMPC_NAME (_api) kmpc_api_calls[KMPC_CHK(_api)].name
Definition at line 298 of file kmpcutil.cpp.
KMPC_RET_DTYPE
#define KMPC_RET_DTYPE (_api) kmpc_api_calls[KMPC_CHK(_api)].ret_dtype
Definition at line 299 of file kmpcutil.cpp.
KMPC_RET_ILIOPC
#define KMPC_RET_ILIOPC (_api) kmpc_api_calls[KMPC_CHK(_api)].ret_iliopc
Definition at line 301 of file kmpcutil.cpp.
MXIDLEN
#define MXIDLEN 250
Definition at line 49 of file kmpcutil.cpp.
SCHED_PREFIX
#define SCHED_PREFIX (_enum_val) (MP_SCH_##_enum_val)
Definition at line 1011 of file kmpcutil.cpp.
Function Documentation
build_kmpc_api_name()
static const char * build_kmpc_api_name (int kmpc_api, va_list va) static
Definition at line 530 of file kmpcutil.cpp.
References assert, ERR_Fatal, hash_functions_strings, hashmap_alloc(), hashmap_insert(), hashmap_lookup(), KMPC_FLAG_STR_FMT, KMPC_FLAGS, KMPC_NAME, NULL, res, va, and vasprintf().
Referenced by mk_kmpc_api_call().
dump_loop_args()
static void dump_loop_args (const loop_args_t * args) static
Definition at line 326 of file kmpcutil.cpp.
References args, DTY, argtype::dtype, FILE, fp, gbl, stb, SYMNAME, and STB::tynames.
Referenced by ll_make_kmpc_dispatch_init(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), and ll_make_kmpc_for_static_init().
gen_null_arg()
static int gen_null_arg () static
Definition at line 372 of file kmpcutil.cpp.
References ad1ili(), DT_INT, getcon(), ili, and tmp.
Referenced by ll_make_kmpc_atomic_read(), ll_make_kmpc_atomic_write(), ll_make_kmpc_copyprivate(), ll_make_kmpc_critical(), ll_make_kmpc_dispatch_fini(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_end_critical(), ll_make_kmpc_end_serialized_parallel(), ll_make_kmpc_flush(), ll_make_kmpc_for_static_init(), ll_make_kmpc_for_static_init_args(), ll_make_kmpc_fork_call(), ll_make_kmpc_fork_teams(), ll_make_kmpc_generic_ptr(), ll_make_kmpc_generic_ptr_2int(), ll_make_kmpc_generic_ptr_int(), ll_make_kmpc_push_num_teams(), ll_make_kmpc_serialized_parallel(), ll_make_kmpc_task(), ll_make_kmpc_task_arg(), ll_make_kmpc_task_begin_if0(), ll_make_kmpc_task_complete_if0(), ll_make_kmpc_task_yield(), ll_make_kmpc_taskloop(), ll_make_kmpc_threadprivate(), ll_make_kmpc_threadprivate_cached(), ll_make_kmpc_threadprivate_register(), and ll_make_kmpc_threadprivate_register_vec().
is_signed()
static bool is_signed (int dtype) static
Definition at line 1070 of file kmpcutil.cpp.
Referenced by ll_make_kmpc_dispatch_fini(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), and ll_make_kmpc_for_static_init_args().
KMPC_GENERIC_P_2I()
KMPC_GENERIC_P_2I (ll_make_kmpc_push_num_threads , KMPC_API_PUSH_NUM_THREADS , argili)
ld_sptr()
static int ld_sptr (SPTR sptr) static
Definition at line 350 of file kmpcutil.cpp.
References ad3ili(), ad_icon, ad_kcon(), addnme(), assert, CONVAL2G, DTY, ERR_Fatal, ili, ILI_OPC, ILI_OPND, ISZ_T, mem_size(), mk_address(), MSZ_I8, NT_VAR, size_of(), sptr, and sz.
Referenced by ll_make_kmpc_dispatch_init(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), and ll_make_kmpc_task_arg().
ll_make_kmpc_atomic_read()
int ll_make_kmpc_atomic_read (int * opnd, DTYPE dtype)
...
Definition at line 1464 of file kmpcutil.cpp.
References args, DT_CMPLX, DT_CPTR, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, DT_LOG, gen_null_arg(), KMPC_API_ATOMIC_RD, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and size_of().
Referenced by _exp_mp_atomic_read().
ll_make_kmpc_atomic_write()
int ll_make_kmpc_atomic_write (int * opnd, DTYPE dtype)
...
Definition at line 1420 of file kmpcutil.cpp.
References args, DT_CMPLX, DT_CPTR, DT_DBLE, DT_DCMPLX, DT_FLOAT, DT_INT, DT_LOG, gen_null_arg(), KMPC_API_ATOMIC_WR, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and size_of().
Referenced by _exp_mp_atomic_write().
ll_make_kmpc_copyprivate()
int ll_make_kmpc_copyprivate (SPTR array_sptr, int single_ili, int copyfunc_acon)
Return a result or JSR ili to __kmpc_copyprivate()
Definition at line 761 of file kmpcutil.cpp.
References ad_acon(), ad_icon, ad_kconi(), args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_COPYPRIVATE, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and TARGET_PTRSIZE.
Referenced by exp_smp().
ll_make_kmpc_critical()
int ll_make_kmpc_critical (SPTR sem)
Return a result or JSR ili to __kmpc_critical()
Definition at line 783 of file kmpcutil.cpp.
References ad_acon(), ad_aconi(), args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_CRITICAL, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and sem.
Referenced by add_mp_p(), and addMpUnp().
ll_make_kmpc_dispatch_fini()
int ll_make_kmpc_dispatch_fini (DTYPE dtype)
...
Definition at line 1347 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, gen_null_arg(), is_signed(), KMPC_API_DISPATCH_FINI, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and size_of().
Referenced by exp_smp().
ll_make_kmpc_dispatch_init()
int ll_make_kmpc_dispatch_init (const loop_args_t * inargs)
...
Definition at line 1246 of file kmpcutil.cpp.
References ad_icon, args, chunk, _loop_args_t::chunk, DBGBIT, DT_CPTR, DT_INT, _loop_args_t::dtype, dump_loop_args(), gen_null_arg(), ikmove(), is_signed(), kimove(), KMPC_API_DISPATCH_INIT, ld_sptr(), ll_get_gtid_val_ili(), lower(), _loop_args_t::lower, mk_kmpc_api_call(), mp_sched_to_kmpc_sched(), _loop_args_t::sched, size_of(), stride, _loop_args_t::stride, _loop_args_t::upper, and upper().
Referenced by exp_smp().
ll_make_kmpc_dispatch_next()
int ll_make_kmpc_dispatch_next (SPTR lower, SPTR upper, SPTR stride, SPTR last, DTYPE dtype)
Return a result or JSR ili to __kmpc_dispatch_next_<size><signed|unsigned> lower, upper, stride: sptrs
Definition at line 1217 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, GBL_CURRFUNC, gen_null_arg(), getccsym_sc(), is_signed(), KMPC_API_DISPATCH_NEXT, last, ll_get_gtid_val_ili(), lower(), mk_address(), mk_kmpc_api_call(), size_of(), stb, stride, and upper().
Referenced by exp_smp().
ll_make_kmpc_dist_dispatch_init()
int ll_make_kmpc_dist_dispatch_init (const loop_args_t * inargs)
...
Definition at line 1292 of file kmpcutil.cpp.
References ad_icon, args, chunk, _loop_args_t::chunk, DBGBIT, DT_CPTR, DT_INT, _loop_args_t::dtype, dump_loop_args(), GBL_CURRFUNC, gen_null_arg(), getccsym_sc(), ikmove(), is_signed(), kimove(), KMPC_API_DIST_DISPATCH_INIT, last, _loop_args_t::last, ld_sptr(), ll_get_gtid_val_ili(), lower(), _loop_args_t::lower, mk_address(), mk_kmpc_api_call(), mp_sched_to_kmpc_sched(), _loop_args_t::sched, size_of(), stb, stride, _loop_args_t::stride, _loop_args_t::upper, and upper().
Referenced by exp_smp().
ll_make_kmpc_dist_for_static_init()
int ll_make_kmpc_dist_for_static_init (const loop_args_t * inargs)
...
Definition at line 1162 of file kmpcutil.cpp.
References ad_icon, args, chunk, _loop_args_t::chunk, DBGBIT, DT_CPTR, DT_INT, _loop_args_t::dtype, dump_loop_args(), GBL_CURRFUNC, gen_null_arg(), getccsym_sc(), ikmove(), is_signed(), kimove(), KMPC_API_DIST_FOR_STATIC_INIT, last, _loop_args_t::last, ld_sptr(), ll_get_gtid_val_ili(), lower(), _loop_args_t::lower, mk_address(), mk_kmpc_api_call(), mp_sched_to_kmpc_sched(), _loop_args_t::sched, size_of(), stb, stride, _loop_args_t::stride, _loop_args_t::upper, upper(), and _loop_args_t::upperd.
Referenced by exp_smp().
ll_make_kmpc_end_critical()
int ll_make_kmpc_end_critical (SPTR sem)
Return a result or JSR ili to __kmpc_end_critical()
Definition at line 797 of file kmpcutil.cpp.
References ad_acon(), ad_aconi(), args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_END_CRITICAL, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and sem.
Referenced by add_mp_v(), and addMpUnv().
ll_make_kmpc_end_serialized_parallel()
int ll_make_kmpc_end_serialized_parallel (void)
...
Definition at line 836 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_END_SERIALIZED_PARALLEL, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_flush()
int ll_make_kmpc_flush (void)
Return a result or JSR ili to __kmpc_flush()
Definition at line 752 of file kmpcutil.cpp.
References args, DT_CPTR, gen_null_arg(), KMPC_API_FLUSH, and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_for_static_init()
int ll_make_kmpc_for_static_init (const loop_args_t * inargs)
...
Definition at line 1109 of file kmpcutil.cpp.
References ad_icon, args, chunk, _loop_args_t::chunk, DBGBIT, DT_CPTR, DT_INT, _loop_args_t::dtype, dump_loop_args(), GBL_CURRFUNC, gen_null_arg(), getccsym_sc(), ikmove(), is_signed(), kimove(), KMPC_API_FOR_STATIC_INIT, last, _loop_args_t::last, ld_sptr(), ll_get_gtid_val_ili(), lower(), _loop_args_t::lower, mk_address(), mk_kmpc_api_call(), mp_sched_to_kmpc_sched(), _loop_args_t::sched, size_of(), stb, stride, _loop_args_t::stride, _loop_args_t::upper, and upper().
Referenced by exp_smp().
ll_make_kmpc_for_static_init_args()
int ll_make_kmpc_for_static_init_args (DTYPE dtype, int * inargs)
...
Definition at line 1080 of file kmpcutil.cpp.
References ad_icon, args, DT_CPTR, DT_INT, gen_null_arg(), is_signed(), KMPC_API_FOR_STATIC_INIT, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and size_of().
Referenced by exp_smp().
ll_make_kmpc_fork_call()
argili int ll_make_kmpc_fork_call (SPTR sptr, int argc, int * arglist, RegionType rt, int ngangs_ili)
...
Definition at line 706 of file kmpcutil.cpp.
References ad1ili(), ad_icon, args, DT_CPTR, DT_INT, gen_null_arg(), get_acon(), KMPC_API_FORK_CALL, mk_kmpc_api_call(), OPENACC, and sptr.
Referenced by exp_smp().
ll_make_kmpc_fork_teams()
int ll_make_kmpc_fork_teams (SPTR sptr, int argc, int * arglist)
...
Definition at line 739 of file kmpcutil.cpp.
References ad1ili(), ad_icon, args, DT_CPTR, DT_INT, gen_null_arg(), get_acon(), KMPC_API_FORK_TEAMS, mk_kmpc_api_call(), and sptr.
Referenced by exp_smp().
ll_make_kmpc_generic_ptr()
static int ll_make_kmpc_generic_ptr (int kmpc_api) static
Definition at line 611 of file kmpcutil.cpp.
References args, DT_CPTR, gen_null_arg(), and mk_kmpc_api_call().
ll_make_kmpc_generic_ptr_2int()
static int ll_make_kmpc_generic_ptr_2int (int kmpc_api, int argili) static
Definition at line 677 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, flg, gen_null_arg(), ll_get_gtid_val_ili(), mk_kmpc_api_call(), ompaccel_nvvm_get_gbl_tid(), and FLG::omptarget.
ll_make_kmpc_generic_ptr_int()
static int ll_make_kmpc_generic_ptr_int (int kmpc_api) static
Definition at line 637 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, gbl, gen_null_arg(), ll_get_gtid_val_ili(), mk_kmpc_api_call(), and ompaccel_nvvm_get_gbl_tid().
ll_make_kmpc_omp_wait_deps()
int ll_make_kmpc_omp_wait_deps (const loop_args_t * inargs)
...
Definition at line 1394 of file kmpcutil.cpp.
ll_make_kmpc_proto()
static SPTR ll_make_kmpc_proto (const char * nm, int kmpc_api, int argc, DTYPE * args) static
Definition at line 447 of file kmpcutil.cpp.
References args, getsymbol(), LL_ABI_Info_::is_varargs, KMPC_API_FORK_CALL, KMPC_API_FORK_TEAMS, KMPC_NAME, KMPC_RET_DTYPE, ll_make_ftn_outlined_params(), ll_process_routine_parameters(), ll_proto_get_abi(), and kmpc_api_entry_t::ret_dtype.
Referenced by mk_kmpc_api_call().
ll_make_kmpc_push_num_teams()
int ll_make_kmpc_push_num_teams (int nteams_ili, int thread_limit_ili)
...
Definition at line 812 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_PUSH_NUM_TEAMS, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_serialized_parallel()
int ll_make_kmpc_serialized_parallel (void)
...
Definition at line 825 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_SERIALIZED_PARALLEL, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_struct_type()
DTYPE ll_make_kmpc_struct_type (int count, const char * name, KMPC_ST_TYPE * meminfo, ISZ_T sz)
...
Definition at line 385 of file kmpcutil.cpp.
References addnewsym(), cg_get_type(), count, DTySetAlgTy, getsymbol(), i, mem(), MXIDLEN, name, NOSYM, size_of(), SPTR_NULL, and sz.
Referenced by ll_make_uplevel_type().
ll_make_kmpc_task()
int ll_make_kmpc_task (SPTR task_sptr)
...
Definition at line 963 of file kmpcutil.cpp.
References ad2ili(), ad_acon(), addnme(), args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_TASK, ll_get_gtid_val_ili(), mk_kmpc_api_call(), and NT_VAR.
Referenced by exp_smp().
ll_make_kmpc_task_arg()
SPTR ll_make_kmpc_task_arg (SPTR base, SPTR sptr, SPTR scope_sptr, SPTR flags_sptr)
Return an sptr to the allocated task object: __kmp_omp_task_alloc()
Parameters
base sptr for storing return value from __kmpc_omp_task_alloc
sptr sptr representing the outlined function that is the task
scope_sptr ST_BLOCK containing the uplevel block
flags MP_TASK_xxx flags (see mp.h)
Definition at line 911 of file kmpcutil.cpp.
References ad4ili(), ad_acon(), ad_icon, addnme(), args, base, chk_block(), DT_CPTR, DT_INT, gen_null_arg(), getTaskSharedSize(), KMPC_API_TASK_ALLOC, ld_sptr(), ll_get_gtid_val_ili(), ll_get_uplevel_sym(), llmp_get_task(), llmp_task_get_size(), mk_kmpc_api_call(), MSZ_PTR, NT_VAR, size, size_of(), sptr, SPTR_NULL, and task.
Referenced by exp_smp().
ll_make_kmpc_task_begin_if0()
int ll_make_kmpc_task_begin_if0 (SPTR task_sptr)
Return a JSR ili to __kmpc_omp_task_begin_if0.
Parameters
task_sptr sptr representing the allocated task
Definition at line 987 of file kmpcutil.cpp.
References ad2ili(), ad_acon(), args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_TASK_BEGIN_IF0, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_task_complete_if0()
int ll_make_kmpc_task_complete_if0 (SPTR task_sptr)
Return a JSR ili to __kmpc_omp_task_complete_if0.
Parameters
task_sptr sptr representing the allocated task
Definition at line 998 of file kmpcutil.cpp.
References ad2ili(), ad_acon(), args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_TASK_COMPLETE_IF0, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_task_with_deps()
int ll_make_kmpc_task_with_deps (const loop_args_t * inargs)
...
Definition at line 1388 of file kmpcutil.cpp.
ll_make_kmpc_task_yield()
int ll_make_kmpc_task_yield (void)
...
Definition at line 976 of file kmpcutil.cpp.
References ad_icon, args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_TASK_YIELD, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_taskloop()
int ll_make_kmpc_taskloop (int * inargs)
...
Definition at line 1365 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_TASKLOOP, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by exp_smp().
ll_make_kmpc_threadprivate()
int ll_make_kmpc_threadprivate (int data_ili, int size_ili)
...
Definition at line 1407 of file kmpcutil.cpp.
References args, DT_CPTR, DT_INT, gen_null_arg(), KMPC_API_THREADPRIVATE, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
ll_make_kmpc_threadprivate_cached()
int ll_make_kmpc_threadprivate_cached (int data_ili, int size_ili, int cache_ili)
...
Definition at line 847 of file kmpcutil.cpp.
References ad1ili(), args, DT_CPTR, DT_INT, gen_null_arg(), IL_RES, ILI_OPC, ILIA_KR, KMPC_API_THREADPRIVATE_CACHED, ll_get_gtid_val_ili(), and mk_kmpc_api_call().
Referenced by allocThreadprivate().
ll_make_kmpc_threadprivate_register()
int ll_make_kmpc_threadprivate_register (int data_ili, int ctor_ili, int cctor_ili, int dtor_ili)
...
Definition at line 865 of file kmpcutil.cpp.
References args, DT_CPTR, gen_null_arg(), KMPC_API_THREADPRIVATE_REGISTER, and mk_kmpc_api_call().
ll_make_kmpc_threadprivate_register_vec()
int ll_make_kmpc_threadprivate_register_vec (int data_ili, int ctor_ili, int cctor_ili, int dtor_ili, int size_ili)
...
Definition at line 879 of file kmpcutil.cpp.
References args, DT_CPTR, gen_null_arg(), KMPC_API_THREADPRIVATE_REGISTER_VEC, and mk_kmpc_api_call().
mk_kmpc_api_call()
static int mk_kmpc_api_call (int kmpc_api, int n_args, DTYPE * arg_dtypes, int * arg_ilis, ...) static
Definition at line 568 of file kmpcutil.cpp.
References ad3ili(), ALLOCA, build_kmpc_api_name(), i, ILI_ALT, ILI_OPND, KMPC_RET_ILIOPC, ll_ad_outlined_func2(), ll_make_kmpc_proto(), ll_make_outlined_garg(), sym_is_refd(), update_acc_with_fn(), and va.
Referenced by ll_make_kmpc_atomic_read(), ll_make_kmpc_atomic_write(), ll_make_kmpc_copyprivate(), ll_make_kmpc_critical(), ll_make_kmpc_dispatch_fini(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_end_critical(), ll_make_kmpc_end_serialized_parallel(), ll_make_kmpc_flush(), ll_make_kmpc_for_static_init(), ll_make_kmpc_for_static_init_args(), ll_make_kmpc_fork_call(), ll_make_kmpc_fork_teams(), ll_make_kmpc_generic_ptr(), ll_make_kmpc_generic_ptr_2int(), ll_make_kmpc_generic_ptr_int(), ll_make_kmpc_push_num_teams(), ll_make_kmpc_serialized_parallel(), ll_make_kmpc_task(), ll_make_kmpc_task_arg(), ll_make_kmpc_task_begin_if0(), ll_make_kmpc_task_complete_if0(), ll_make_kmpc_task_yield(), ll_make_kmpc_taskloop(), ll_make_kmpc_threadprivate(), ll_make_kmpc_threadprivate_cached(), ll_make_kmpc_threadprivate_register(), and ll_make_kmpc_threadprivate_register_vec().
mp_sched_to_kmpc_sched()
kmpc_sched_e mp_sched_to_kmpc_sched (int sched)
Given a MP_ or DI_ schedule type and return the KMPC equivalent.
Definition at line 1013 of file kmpcutil.cpp.
References ERR_Warning, error(), gbl, KMP_DISTRIBUTE_STATIC, KMP_DISTRIBUTE_STATIC_CHUNKED, KMP_DISTRIBUTE_STATIC_CHUNKED_CHUNKONE, KMP_ORD_AUTO, KMP_ORD_DYNAMIC_CHUNKED, KMP_ORD_RUNTIME, KMP_ORD_STATIC, KMP_ORD_STATIC_CHUNKED, KMP_SCH_AUTO, KMP_SCH_DEFAULT, KMP_SCH_DYNAMIC_CHUNKED, KMP_SCH_GUIDED_CHUNKED, KMP_SCH_RUNTIME_CHUNKED, KMP_SCH_STATIC, KMP_SCH_STATIC_CHUNKED, MP_SCH_ATTR_CHUNKED, MP_SCH_ATTR_DEVICEDIST, MP_SCH_ATTR_ORDERED, MP_SCH_BLK_ALN, MP_SCH_BLK_CYC, MP_SCH_CHUNK_1, NULL, and SCHED_PREFIX.
Referenced by exp_smp(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), and ll_make_kmpc_for_static_init().
mp_to_kmpc_tasking_flags()
int mp_to_kmpc_tasking_flags (const int mp)
...
Definition at line 900 of file kmpcutil.cpp.
References KMPC_TASK_FINAL, KMPC_TASK_PRIORITY, KMPC_TASK_TIED, KMPC_TASK_UNTIED, MP_TASK_FINAL, MP_TASK_PRIORITY, and MP_TASK_UNTIED.
Referenced by exp_smp().
reset_kmpc_ident_dtype()
void reset_kmpc_ident_dtype (void)
...
Definition at line 1400 of file kmpcutil.cpp.
References kmpc_ident_dtype.
Referenced by ll_reset_parfile(), ll_reset_parfile_(), and llvmAddConcurEntryBlk().
Variable Documentation
kmpc_api_calls
const struct kmpc_api_entry_t kmpc_api_calls[] static
Definition at line 206 of file kmpcutil.cpp.
KMPC_API_CANCELLATIONPOINT
KMPC_API_CANCELLATIONPOINT
Definition at line 701 of file kmpcutil.cpp.
kmpc_ident_dtype
DTYPE kmpc_ident_dtype static
Definition at line 50 of file kmpcutil.cpp.
Referenced by reset_kmpc_ident_dtype().