flang: komp.h File Reference
komp.h File Reference
#include <stdint.h>
Classes
struct omp_lock_t
struct omp_nest_lock_t
Typedefs
typedef struct omp_lock_t omp_lock_t
typedef struct omp_nest_lock_t omp_nest_lock_t
typedef enum omp_sched_t omp_sched_t
typedef enum omp_proc_bind_t omp_proc_bind_t
typedef enum omp_lock_hint_t omp_lock_hint_t
typedef int _Atomic_word
typedef void ident_t
typedef int kmp_int32
typedef long long kmp_int64
typedef kmp_int64 kmp_critical_name[4]
Enumerations
enum omp_sched_t { omp_sched_static = 1 , omp_sched_dynamic = 2 , omp_sched_guided = 3 , omp_sched_auto = 4 }
enum omp_proc_bind_t {
omp_proc_bind_false = 0 , omp_proc_bind_true = 1 , omp_proc_bind_master = 2 , omp_proc_bind_close = 3 ,
omp_proc_bind_spread = 4 , MP_PROC_BIND_FALSE = 0 , MP_PROC_BIND_TRUE , MP_PROC_BIND_MASTER ,
MP_PROC_BIND_CLOSE , MP_PROC_BIND_SPREAD
}
enum omp_lock_hint_t {
omp_lock_hint_none = 0 , omp_lock_hint_uncontended = 1 , omp_lock_hint_contended = (1<<1) , omp_lock_hint_nonspeculative = (1<<2) ,
omp_lock_hint_speculative = (1<<3) , kmp_lock_hint_hle = (1<<16) , kmp_lock_hint_rtm = (1<<17) , kmp_lock_hint_adaptive = (1<<18)
}
Functions
void omp_set_num_threads (int n)
int omp_get_thread_num (void)
int omp_get_num_procs (void)
int omp_get_num_threads (void)
int omp_get_max_threads (void)
int omp_in_parallel (void)
int omp_in_final (void)
void omp_set_dynamic (int n)
int omp_get_dynamic (void)
void omp_set_nested (int n)
int omp_get_nested (void)
void omp_init_lock (omp_lock_t *s)
void omp_destroy_lock (omp_lock_t *s)
void omp_set_lock (omp_lock_t *s)
void omp_unset_lock (omp_lock_t *s)
int omp_test_lock (omp_lock_t *s)
void omp_init_nest_lock (omp_nest_lock_t *s)
void omp_destroy_nest_lock (omp_nest_lock_t *s)
void omp_set_nest_lock (omp_nest_lock_t *s)
void omp_unset_nest_lock (omp_nest_lock_t *s)
int omp_test_nest_lock (omp_nest_lock_t *s)
double omp_get_wtime (void)
double omp_get_wtick (void)
long omp_get_stack_size (void)
void omp_set_stack_size (long l)
int omp_get_thread_limit (void)
void omp_set_max_active_levels (int)
int omp_get_max_active_levels (void)
int omp_get_level (void)
int omp_get_ancestor_thread_num (int)
int omp_get_team_size (int)
int omp_get_active_level (void)
void omp_set_schedule (omp_sched_t, int)
void omp_get_schedule (omp_sched_t *, int *)
void _mp_atomic_add (int *, int)
void _mp_exchange_and_add (int *, int)
void omp_init_lock_with_hint (omp_lock_t *, omp_lock_hint_t)
void omp_init_nest_lock_with_hint (omp_nest_lock_t *, omp_lock_hint_t)
int omp_get_default_device (void)
void omp_set_default_device (int)
int omp_is_initial_device (void)
int omp_get_num_devices (void)
int omp_get_num_teams (void)
int omp_get_team_num (void)
int omp_get_cancellation (void)
omp_proc_bind_t omp_get_proc_bind (void)
int omp_get_place_num_procs (int place_num)
void omp_get_place_proc_ids (int place_num, int *ids)
int omp_get_place_num (void)
int omp_get_partition_num_places (void)
void omp_get_partition_place_nums (int *place_nums)
int omp_get_initial_device (void)
int omp_get_max_task_priority (void)
void * omp_target_alloc (size_t size, int device_num)
void omp_target_free (void *device_ptr, int device_num)
int omp_target_is_present (void *ptr, int device_num)
int omp_target_memcpy (void *dst, void *src, size_t length, size_t dst_offset, size_t src_offset, int dst_device_num, int src_device_num)
int omp_target_memcpy_rect (void *dst, void *src, size_t element_size, int num_dims, const size_t *volume, const size_t *dst_offsets, const size_t *src_offsets, const size_t *dst_dimensions, const size_t *src_dimensions, int dst_device_num, int src_device_num)
int omp_target_associate_ptr (void *host_ptr, void *device_ptr, size_t size, size_t device_offset, int device_num)
int omp_target_disassociate_ptr (void *ptr, int device_num)
kmp_int32 __kmpc_global_thread_num (ident_t *)
void __kmpc_critical (ident_t *, kmp_int32, kmp_critical_name *)
void __kmpc_end_critical (ident_t *, kmp_int32, kmp_critical_name *)
void * __kmpc_threadprivate_cached (ident_t *, kmp_int32, void *, size_t, void ***)
void * __kmpc_threadprivate (ident_t *, kmp_int32, void *, size_t)
void __kmpc_barrier (ident_t *, kmp_int32)
Typedef Documentation
_Atomic_word
typedef int _Atomic_word
Definition at line 92 of file komp.h.
ident_t
typedef void ident_t
Definition at line 176 of file komp.h.
kmp_critical_name
typedef kmp_int64 kmp_critical_name[4]
Definition at line 195 of file komp.h.
kmp_int32
typedef int kmp_int32
Definition at line 190 of file komp.h.
kmp_int64
typedef long long kmp_int64
Definition at line 191 of file komp.h.
omp_lock_hint_t
typedef enum omp_lock_hint_t omp_lock_hint_t
omp_lock_t
typedef struct omp_lock_t omp_lock_t
omp_nest_lock_t
typedef struct omp_nest_lock_t omp_nest_lock_t
omp_proc_bind_t
typedef enum omp_proc_bind_t omp_proc_bind_t
omp_sched_t
typedef enum omp_sched_t omp_sched_t
Enumeration Type Documentation
omp_lock_hint_t
enum omp_lock_hint_t
Enumerator
omp_lock_hint_none
omp_lock_hint_uncontended
omp_lock_hint_contended
omp_lock_hint_nonspeculative
omp_lock_hint_speculative
kmp_lock_hint_hle
kmp_lock_hint_rtm
kmp_lock_hint_adaptive
Definition at line 42 of file komp.h.
omp_proc_bind_t
enum omp_proc_bind_t
Enumerator
omp_proc_bind_false
omp_proc_bind_true
omp_proc_bind_master
omp_proc_bind_close
omp_proc_bind_spread
MP_PROC_BIND_FALSE
MP_PROC_BIND_TRUE
MP_PROC_BIND_MASTER
MP_PROC_BIND_CLOSE
MP_PROC_BIND_SPREAD
Definition at line 33 of file komp.h.
omp_sched_t
enum omp_sched_t
Enumerator
omp_sched_static
omp_sched_dynamic
omp_sched_guided
omp_sched_auto
Definition at line 25 of file komp.h.
Function Documentation
__kmpc_barrier()
void __kmpc_barrier (ident_t * id, kmp_int32 tn)
Definition at line 646 of file ompstubs.c.
Referenced by _mp_copyin_move(), _mp_copyin_move_al(), _mp_copyin_move_cpp(), _mp_copyin_move_multiple(), _mp_copyin_move_tls(), _mp_copypriv(), _mp_copypriv_al(), _mp_copypriv_move(), and _mp_copypriv_move_tls().
__kmpc_critical()
void __kmpc_critical (ident_t * id, kmp_int32 tn, kmp_critical_name * sem)
Definition at line 612 of file ompstubs.c.
Referenced by _mp_bcs(), _mp_bcs_stdio(), and _mp_p().
__kmpc_end_critical()
void __kmpc_end_critical (ident_t * id, kmp_int32 tn, kmp_critical_name * sem)
Definition at line 622 of file ompstubs.c.
Referenced by _mp_ecs(), _mp_ecs_stdio(), and _mp_v().
__kmpc_global_thread_num()
kmp_int32 __kmpc_global_thread_num (ident_t * id)
Definition at line 600 of file ompstubs.c.
Referenced by _mp_bcs(), _mp_bcs_stdio(), _mp_cdecl(), _mp_cdecli(), _mp_cdeclp(), _mp_copyin_move(), _mp_copyin_move_al(), _mp_copyin_move_cpp(), _mp_copyin_move_cpp_new(), _mp_copyin_move_multiple(), _mp_copyin_move_tls(), _mp_copypriv(), _mp_copypriv_al(), _mp_copypriv_move(), _mp_copypriv_move_tls(), _mp_ecs(), _mp_ecs_stdio(), _mp_p(), and _mp_v().
__kmpc_threadprivate()
void * __kmpc_threadprivate (ident_t * id, kmp_int32 tn, void * data, size_t size)
Definition at line 656 of file ompstubs.c.
Referenced by _mp_copyin_move_tls(), _mp_copypriv_move_tls(), and _mp_get_threadprivate().
__kmpc_threadprivate_cached()
void * __kmpc_threadprivate_cached (ident_t * id, kmp_int32 tn, void * data, size_t size, void *** cache)
Definition at line 632 of file ompstubs.c.
Referenced by _mp_cdecl(), _mp_cdecli(), _mp_cdeclp(), _mp_copyin_move(), _mp_copyin_move_al(), _mp_copyin_move_cpp(), _mp_copyin_move_cpp_new(), _mp_copyin_move_multiple(), and _mp_copypriv_move().
_mp_atomic_add()
void _mp_atomic_add (int * , int)
_mp_exchange_and_add()
void _mp_exchange_and_add (int * , int)
omp_destroy_lock()
void omp_destroy_lock (omp_lock_t * s)
Definition at line 280 of file ompstubs.c.
omp_destroy_nest_lock()
void omp_destroy_nest_lock (omp_nest_lock_t * s)
Definition at line 312 of file ompstubs.c.
omp_get_active_level()
int omp_get_active_level (void)
Definition at line 258 of file ompstubs.c.
omp_get_ancestor_thread_num()
int omp_get_ancestor_thread_num (int level)
Definition at line 222 of file ompstubs.c.
References level().
omp_get_cancellation()
int omp_get_cancellation (void)
Definition at line 354 of file ompstubs.c.
omp_get_default_device()
int omp_get_default_device (void)
Definition at line 457 of file ompstubs.c.
omp_get_dynamic()
int omp_get_dynamic (void)
Definition at line 130 of file ompstubs.c.
omp_get_initial_device()
int omp_get_initial_device (void)
Definition at line 517 of file ompstubs.c.
omp_get_level()
int omp_get_level (void)
Definition at line 210 of file ompstubs.c.
omp_get_max_active_levels()
int omp_get_max_active_levels (void)
Definition at line 198 of file ompstubs.c.
omp_get_max_task_priority()
int omp_get_max_task_priority (void)
Definition at line 529 of file ompstubs.c.
omp_get_max_threads()
int omp_get_max_threads (void)
Definition at line 98 of file ompstubs.c.
omp_get_nested()
int omp_get_nested (void)
Definition at line 152 of file ompstubs.c.
omp_get_num_devices()
int omp_get_num_devices (void)
Definition at line 469 of file ompstubs.c.
omp_get_num_procs()
int omp_get_num_procs (void)
Definition at line 74 of file ompstubs.c.
omp_get_num_teams()
int omp_get_num_teams (void)
Definition at line 481 of file ompstubs.c.
omp_get_num_threads()
int omp_get_num_threads (void)
Definition at line 86 of file ompstubs.c.
omp_get_partition_num_places()
int omp_get_partition_num_places (void)
Definition at line 425 of file ompstubs.c.
omp_get_partition_place_nums()
void omp_get_partition_place_nums (int * place_nums)
Definition at line 437 of file ompstubs.c.
omp_get_place_num()
int omp_get_place_num (void)
Definition at line 413 of file ompstubs.c.
omp_get_place_num_procs()
int omp_get_place_num_procs (int place_num)
Definition at line 390 of file ompstubs.c.
omp_get_place_proc_ids()
void omp_get_place_proc_ids (int place_num, int * ids)
Definition at line 401 of file ompstubs.c.
omp_get_proc_bind()
omp_proc_bind_t omp_get_proc_bind (void)
Definition at line 372 of file ompstubs.c.
omp_get_schedule()
void omp_get_schedule (omp_sched_t * kind, int * modifier)
Definition at line 174 of file ompstubs.c.
References kind, and omp_sched_static.
omp_get_stack_size()
long omp_get_stack_size (void)
omp_get_team_num()
int omp_get_team_num (void)
Definition at line 493 of file ompstubs.c.
omp_get_team_size()
int omp_get_team_size (int level)
Definition at line 240 of file ompstubs.c.
References level().
omp_get_thread_limit()
int omp_get_thread_limit (void)
Definition at line 20 of file ompstubs.c.
omp_get_thread_num()
int omp_get_thread_num (void)
Definition at line 110 of file ompstubs.c.
omp_get_wtick()
double omp_get_wtick (void)
Definition at line 574 of file ompstubs.c.
omp_get_wtime()
double omp_get_wtime (void)
Definition at line 554 of file ompstubs.c.
omp_in_final()
int omp_in_final (void)
Definition at line 594 of file ompstubs.c.
omp_in_parallel()
int omp_in_parallel (void)
Definition at line 32 of file ompstubs.c.
omp_init_lock()
void omp_init_lock (omp_lock_t * s)
Definition at line 270 of file ompstubs.c.
omp_init_lock_with_hint()
void omp_init_lock_with_hint (omp_lock_t * , omp_lock_hint_t)
omp_init_nest_lock()
void omp_init_nest_lock (omp_nest_lock_t * s)
Definition at line 302 of file ompstubs.c.
Referenced by _mp_bcs_nest(), _mp_bcs_nest_red(), omp_init_nest_lock_with_hint(), and omp_init_nest_lock_with_hint_().
omp_init_nest_lock_with_hint()
void omp_init_nest_lock_with_hint (omp_nest_lock_t * lock, omp_lock_hint_t hint)
Definition at line 541 of file ompstubs.c.
References arg, and omp_init_nest_lock().
omp_is_initial_device()
int omp_is_initial_device (void)
Definition at line 505 of file ompstubs.c.
omp_set_default_device()
void omp_set_default_device (int device_num)
Definition at line 447 of file ompstubs.c.
omp_set_dynamic()
void omp_set_dynamic (int n)
Definition at line 120 of file ompstubs.c.
omp_set_lock()
void omp_set_lock (omp_lock_t * s)
Definition at line 54 of file ompstubs.c.
omp_set_max_active_levels()
void omp_set_max_active_levels (int max_active_levels)
Definition at line 188 of file ompstubs.c.
omp_set_nest_lock()
void omp_set_nest_lock (omp_nest_lock_t * s)
Definition at line 322 of file ompstubs.c.
Referenced by _mp_bcs_nest(), and _mp_bcs_nest_red().
omp_set_nested()
void omp_set_nested (int n)
Definition at line 142 of file ompstubs.c.
omp_set_num_threads()
void omp_set_num_threads (int n)
Definition at line 44 of file ompstubs.c.
omp_set_schedule()
void omp_set_schedule (omp_sched_t kind, int modifier)
Definition at line 164 of file ompstubs.c.
omp_set_stack_size()
void omp_set_stack_size (long l)
omp_target_alloc()
void * omp_target_alloc (size_t size, int device_num)
omp_target_associate_ptr()
int omp_target_associate_ptr (void * host_ptr, void * device_ptr, size_t size, size_t device_offset, int device_num)
omp_target_disassociate_ptr()
int omp_target_disassociate_ptr (void * ptr, int device_num)
omp_target_free()
void omp_target_free (void * device_ptr, int device_num)
omp_target_is_present()
int omp_target_is_present (void * ptr, int device_num)
omp_target_memcpy()
int omp_target_memcpy (void * dst, void * src, size_t length, size_t dst_offset, size_t src_offset, int dst_device_num, int src_device_num)
omp_target_memcpy_rect()
int omp_target_memcpy_rect (void * dst, void * src, size_t element_size, int num_dims, const size_t * volume, const size_t * dst_offsets, const size_t * src_offsets, const size_t * dst_dimensions, const size_t * src_dimensions, int dst_device_num, int src_device_num)
omp_test_lock()
int omp_test_lock (omp_lock_t * s)
Definition at line 290 of file ompstubs.c.
omp_test_nest_lock()
int omp_test_nest_lock (omp_nest_lock_t * s)
Definition at line 342 of file ompstubs.c.
omp_unset_lock()
void omp_unset_lock (omp_lock_t * s)
Definition at line 64 of file ompstubs.c.
omp_unset_nest_lock()
void omp_unset_nest_lock (omp_nest_lock_t * s)
Definition at line 332 of file ompstubs.c.
Referenced by _mp_ecs_nest(), and _mp_ecs_nest_red().