flang: kwddf.h File Reference
kwddf.h File Reference
Classes
struct KWORD
struct KTABLE
Macros
#define TKF_ARRAY -1
#define TKF_ATOMIC -2
#define TKF_CANCELLATION -3
#define TKF_DISTPAR -4
#define TKF_DOCONCURRENT -5
#define TKF_DOUBLE -6
#define TKF_DOWHILE -7
#define TKF_ENDDISTPAR -8
#define TKF_GO -9
#define TKF_NO -10
#define TKF_SELECT -11
#define TKF_TARGETENTER -12
#define TKF_TARGETEXIT -13
#define _CS 1 /* alpha symbol */
#define _DI 2 /* digit */
#define _BL 4 /* blank */
#define _HD 8 /* hex digit */
#define _HO 16 /* Hollerith constant indicator */
#define iscsym(c) (ctable[c] & _CS)
#define isblank(c) (ctable[c] & _BL)
#define iswhite(c) ((c) <= ' ')
#define ishex(c) (ctable[c] & (_HD | _DI))
#define isident(c) (ctable[c] & (_CS | _DI))
#define isdig(c) (ctable[c] & _DI)
#define isodigit(c) ((c) >= '0' && (c) <= '7')
#define isholl(c) (ctable[c] & _HO)
Variables
static KWORD t1 []
static KWORD t2 []
static KWORD t3 []
static KWORD t4 []
static KWORD t5 []
static KWORD t6 []
static KWORD t7 []
static KWORD t8 []
static KWORD t9 []
static KWORD t11 []
static KWORD t12 []
static KTABLE normalkw = {sizeof(t1) / sizeof(KWORD), &t1[0], {}, {}}
static KTABLE logicalkw = {sizeof(t2) / sizeof(KWORD), &t2[0], {}, {}}
static KTABLE iokw = {sizeof(t3) / sizeof(KWORD), &t3[0], {}, {}}
static KTABLE formatkw = {sizeof(t4) / sizeof(KWORD), &t4[0], {}, {}}
static KTABLE parallelkw = {sizeof(t5) / sizeof(KWORD), &t5[0], {}, {}}
static KTABLE parbegkw = {sizeof(t6) / sizeof(KWORD), &t6[0], {}, {}}
static KTABLE deckw = {sizeof(t7) / sizeof(KWORD), &t7[0], {}, {}}
static KTABLE pragma_kw = {sizeof(t8) / sizeof(KWORD), &t8[0], {}, {}}
static KTABLE ppragma_kw = {sizeof(t9) / sizeof(KWORD), &t9[0], {}, {}}
static KTABLE kernel_kw = {sizeof(t11) / sizeof(KWORD), &t11[0], {}, {}}
static KTABLE pgi_kw = {sizeof(t12) / sizeof(KWORD), &t12[0], {}, {}}
static char ctable [256]
Macro Definition Documentation
_BL
#define _BL 4 /* blank */
Definition at line 581 of file kwddf.h.
_CS
#define _CS 1 /* alpha symbol */
Definition at line 579 of file kwddf.h.
_DI
#define _DI 2 /* digit */
Definition at line 580 of file kwddf.h.
_HD
#define _HD 8 /* hex digit */
Definition at line 582 of file kwddf.h.
_HO
#define _HO 16 /* Hollerith constant indicator */
Definition at line 583 of file kwddf.h.
isblank
#define isblank (c) (ctable[c] & _BL)
Definition at line 588 of file kwddf.h.
iscsym
#define iscsym (c) (ctable[c] & _CS)
Definition at line 586 of file kwddf.h.
isdig
#define isdig (c) (ctable[c] & _DI)
Definition at line 593 of file kwddf.h.
ishex
#define ishex (c) (ctable[c] & (_HD | _DI))
Definition at line 591 of file kwddf.h.
isholl
#define isholl (c) (ctable[c] & _HO)
Definition at line 595 of file kwddf.h.
isident
#define isident (c) (ctable[c] & (_CS | _DI))
Definition at line 592 of file kwddf.h.
isodigit
#define isodigit (c) ((c) >= '0' && (c) <= '7')
Definition at line 594 of file kwddf.h.
iswhite
#define iswhite (c) ((c) <= ' ')
Definition at line 590 of file kwddf.h.
TKF_ARRAY
#define TKF_ARRAY -1
Definition at line 68 of file kwddf.h.
TKF_ATOMIC
#define TKF_ATOMIC -2
Definition at line 69 of file kwddf.h.
TKF_CANCELLATION
#define TKF_CANCELLATION -3
Definition at line 70 of file kwddf.h.
TKF_DISTPAR
#define TKF_DISTPAR -4
Definition at line 71 of file kwddf.h.
TKF_DOCONCURRENT
#define TKF_DOCONCURRENT -5
Definition at line 72 of file kwddf.h.
TKF_DOUBLE
#define TKF_DOUBLE -6
Definition at line 73 of file kwddf.h.
TKF_DOWHILE
#define TKF_DOWHILE -7
Definition at line 74 of file kwddf.h.
TKF_ENDDISTPAR
#define TKF_ENDDISTPAR -8
Definition at line 75 of file kwddf.h.
TKF_GO
#define TKF_GO -9
Definition at line 76 of file kwddf.h.
TKF_NO
#define TKF_NO -10
Definition at line 77 of file kwddf.h.
TKF_SELECT
#define TKF_SELECT -11
Definition at line 78 of file kwddf.h.
TKF_TARGETENTER
#define TKF_TARGETENTER -12
Definition at line 79 of file kwddf.h.
TKF_TARGETEXIT
#define TKF_TARGETEXIT -13
Definition at line 80 of file kwddf.h.
Variable Documentation
ctable
char ctable[256] static
Definition at line 597 of file kwddf.h.
deckw
KTABLE deckw = {sizeof(t7) / sizeof(KWORD), &t7[0], {}, {}} static
Definition at line 565 of file kwddf.h.
Referenced by classify_dec(), and scan_init().
formatkw
KTABLE formatkw = {sizeof(t4) / sizeof(KWORD), &t4[0], {}, {}} static
Definition at line 562 of file kwddf.h.
Referenced by alpha(), and scan_init().
iokw
KTABLE iokw = {sizeof(t3) / sizeof(KWORD), &t3[0], {}, {}} static
Definition at line 561 of file kwddf.h.
Referenced by alpha(), and scan_init().
kernel_kw
KTABLE kernel_kw = {sizeof(t11) / sizeof(KWORD), &t11[0], {}, {}} static
Definition at line 568 of file kwddf.h.
Referenced by alpha(), classify_kernel_pragma(), and scan_init().
logicalkw
KTABLE logicalkw = {sizeof(t2) / sizeof(KWORD), &t2[0], {}, {}} static
Definition at line 560 of file kwddf.h.
Referenced by do_dot(), and scan_init().
normalkw
KTABLE normalkw = {sizeof(t1) / sizeof(KWORD), &t1[0], {}, {}} static
Definition at line 559 of file kwddf.h.
Referenced by alpha(), and scan_init().
parallelkw
KTABLE parallelkw = {sizeof(t5) / sizeof(KWORD), &t5[0], {}, {}} static
Definition at line 563 of file kwddf.h.
Referenced by alpha(), and scan_init().
parbegkw
KTABLE parbegkw = {sizeof(t6) / sizeof(KWORD), &t6[0], {}, {}} static
Definition at line 564 of file kwddf.h.
Referenced by classify_smp(), and scan_init().
pgi_kw
KTABLE pgi_kw = {sizeof(t12) / sizeof(KWORD), &t12[0], {}, {}} static
Definition at line 569 of file kwddf.h.
Referenced by classify_pgi_dir(), and scan_init().
ppragma_kw
KTABLE ppragma_kw = {sizeof(t9) / sizeof(KWORD), &t9[0], {}, {}} static
Definition at line 567 of file kwddf.h.
Referenced by check_pgi_pragma(), classify_pgi_pragma(), and scan_init().
pragma_kw
KTABLE pragma_kw = {sizeof(t8) / sizeof(KWORD), &t8[0], {}, {}} static
Definition at line 566 of file kwddf.h.
Referenced by classify_pragma(), and scan_init().
t1
KWORD t1[] static
Definition at line 82 of file kwddf.h.
t11
KWORD t11[] static
Initial value:
= {
    {"", 0, 0},
    {"do", TK_DO, 0},
    {"kernel", TK_KERNEL, 0},
    {"nowait", TK_NOWAIT, 0},
}
Definition at line 543 of file kwddf.h.
t12
KWORD t12[] static
Initial value:
= {
    {"", 0, 0},
    {"compare", TK_PGICOMPARE, 0},
}
Definition at line 551 of file kwddf.h.
t2
KWORD t2[] static
Initial value:
= {
                     {"", 0, 0},
                     {"a", TK_AND, TRUE},
                     {"and", TK_AND, FALSE},
                     {"eq", TK_EQ, FALSE},
                     {"eqv", TK_EQV, FALSE},
                     {"f", TK_LOGCONST, TRUE},
                     {"false", TK_LOGCONST, FALSE},
                     {"ge", TK_GE, FALSE},
                     {"gt", TK_GT, FALSE},
                     {"le", TK_LE, FALSE},
                     {"lt", TK_LT, FALSE},
                     {"n", TK_NOTX, TRUE},
                     {"ne", TK_NE, FALSE},
                     {"neqv", TK_NEQV, FALSE},
                     {"not", TK_NOT, FALSE},
                     {"o", TK_ORX, TRUE},
                     {"or", TK_OR, FALSE},
                     {"t", TK_LOGCONST, TRUE},
                     {"true", TK_LOGCONST, FALSE},
                     {"x", TK_XORX, TRUE},
                     {"xor", TK_XOR, TRUE}}
Definition at line 233 of file kwddf.h.
t3
KWORD t3[] static
Definition at line 256 of file kwddf.h.
t4
KWORD t4[] static
Definition at line 319 of file kwddf.h.
t5
KWORD t5[] static
Definition at line 356 of file kwddf.h.
t6
KWORD t6[] static
Definition at line 414 of file kwddf.h.
t7
KWORD t7[] static
Initial value:
= {
    {"", 0, 0},
    {"alias", TK_ALIAS, 0},
    {"attributes", TK_ATTRIBUTES, 0},
    {"craydistributepoint", TK_DISTRIBUTEPOINT, 0},
    {"distribute", TK_DISTRIBUTE, 0},
    {"distributepoint", TK_DISTRIBUTEPOINT, 0},
}
Definition at line 517 of file kwddf.h.
t8
KWORD t8[] static
Initial value:
= {
    {"", 0, 0},
    {"local", TK_LOCAL, 0},
    {"prefetch", TK_PREFETCH, 0},
}
Definition at line 527 of file kwddf.h.
Referenced by __fsd_pow_fma3(), __fvd_pow_fma3(), __fvd_pow_fma3_256(), and ENTF90().
t9
KWORD t9[] static
Initial value:
= {
    {"", 0, 0},
    {"defaultkind", TK_DFLT, 0},
    {"ignore_tkr", TK_IGNORE_TKR, 0},
    {"movedesc", TK_MOVEDESC, 0},
    {"prefetch", TK_PREFETCH, 0},
}
Definition at line 534 of file kwddf.h.