flang: ldexp_d_common.h File Reference
ldexp_d_common.h File Reference
#include "math_common.h"
#include "sleef_common.h"
Functions
static double INLINE __ldexp_d_scalar_kernel (double a, long long int scale)
static vdouble INLINE __vldexp_manual (vdouble va, vdouble vscale)
static vdouble INLINE __vldexp_kernel (vdouble va, vdouble vscale)
Function Documentation
__ldexp_d_scalar_kernel()
static double INLINE __ldexp_d_scalar_kernel (double a, long long int scale) static
Definition at line 12 of file ldexp_d_common.h.
References a, D2L(), DB_EXP_BIAS, DB_EXP_MASK, DB_EXP_MAX, DB_EXP_MIN, DB_PREC_BITS, DB_SIGN_BIT, L2D(), PRINT, res, result, scale, and ull.
Referenced by cexp_scalar_default_abi().
__vldexp_kernel()
static vdouble INLINE __vldexp_kernel (vdouble va, vdouble vscale) static
Definition at line 176 of file ldexp_d_common.h.
References __vldexp_manual(), _VL, JOIN, JOIN3, PRINT, va, and vD2L.
Referenced by cexp_vec().
__vldexp_manual()
static vdouble INLINE __vldexp_manual (vdouble va, vdouble vscale) static
Definition at line 94 of file ldexp_d_common.h.
References DB_EXP_BIAS, DB_EXP_MASK, DB_EXP_MAX, DB_EXP_MIN, DB_PREC_BITS, DB_SIGN_BIT, PRINT, result, va, vadd64_vi2_vi2_vi2(), vadd_vd_vd_vd(), vadd_vi2_vi2_vi2(), vand_vi2_vi2_vi2(), vand_vm_vo64_vm(), vandnot_vm_vo64_vm(), vandnot_vo_vo_vo(), vD2L, veq64_vo_vm_vm(), vgt64_vo_vm_vm(), vL2D, vmul_vd_vd_vd(), vor_vi2_vi2_vi2(), vor_vo_vo_vo(), vSETll, vsll64_vi2_vi2_i(), vsrl64_vi2_vi2_i(), and zero_mask.
Referenced by __vldexp_kernel().