flang: ldexp_common.h File Reference
ldexp_common.h File Reference
#include "math_common.h"
#include "sleef_common.h"
Functions
static float INLINE __ldexpf_scalar_kernel (float a, int scale)
static vfloat INLINE __vldexpf_manual (vfloat va, vfloat vscale)
static vfloat INLINE __vldexpf_kernel (vfloat va, vfloat vscale)
Function Documentation
__ldexpf_scalar_kernel()
static float INLINE __ldexpf_scalar_kernel (float a, int scale) static
Definition at line 12 of file ldexp_common.h.
References _mm_cvtss_f32(), a, F2I(), FL_EXP_BIAS, FL_EXP_MASK, FL_EXP_MAX, FL_EXP_MIN, FL_PREC_BITS, FL_SIGN_BIT, I2F(), PRINT, res, result, and scale.
__vldexpf_kernel()
static vfloat INLINE __vldexpf_kernel (vfloat va, vfloat vscale) static
Definition at line 171 of file ldexp_common.h.
References __vldexpf_manual(), _VL, JOIN, JOIN3, PRINT, va, vcast_vf_vi2(), and vF2I.
Referenced by cexpf_vec().
__vldexpf_manual()
static vfloat INLINE __vldexpf_manual (vfloat va, vfloat vscale) static
Definition at line 89 of file ldexp_common.h.
References FL_EXP_BIAS, FL_EXP_MASK, FL_EXP_MAX, FL_EXP_MIN, FL_PREC_BITS, FL_SIGN_BIT, PRINT, result, va, vadd_vf_vf_vf(), vadd_vi2_vi2_vi2(), vand_vi2_vi2_vi2(), vand_vi2_vo_vi2(), vandnot_vi2_vo_vi2(), vandnot_vo_vo_vo(), veq_vo_vi2_vi2(), vF2I, vgt_vo_vi2_vi2(), vI2F, vmul_vf_vf_vf(), vor_vi2_vi2_vi2(), vor_vo_vo_vo(), vSETi, vsll_vi2_vi2_i(), vsrl_vi2_vi2_i(), and zero_mask.
Referenced by __vldexpf_kernel().