flang: ldread.c File Reference
ldread.c File Reference
List-directed read module.
#include "global.h"
#include "format.h"
#include "list_io.h"
#include <string.h>
Classes
struct struct_G
union ieee
Macros
#define DBGBIT(v) (LOCAL_DEBUG && (dbgflag & v))
#define RBUF_SIZE 256
#define GBL_SIZE 5
#define TK_ERROR 1
#define TK_NULL 2
#define TK_SLASH 3
#define TK_VAL 4
#define TK_VALS 5
#define BEGINS_NUM(c) (ISDIGIT(c) || (c) == '.')
#define ISDELIMITER(c) ((c) == ',' || (c) == ' ' || (c) == '\t' || (c) == '/' || (c == '\n'))
Typedefs
typedef struct struct_G G
Functions
int read_record_internal (void)
static int read_record (void)
static char * alloc_rbuf (int, bool)
static int skip_record (void)
static void shared_init (void)
static void get_token (void)
static void get_number (void)
Extract integer, real, or double precision constant token:
static void get_cmplx (void)
A left paren has been found. Create a complex constant. currc locates character after '('.
static void get_infinity (void)
An 'I' has been found. Is it an infinity? Valid are +inf, -inf, inf, +infinity, -infinity, infinity.
static void get_nan (void)
An 'N' has been found. Is it a NaN? Valid are nan and nan(ddd...)
static __BIGREAL_T to_bigreal (AVAL *)
static void get_qstr (int quote)
A quote has been seen (' or "). Create a character constant.
static void get_junk (void)
Non-quoted strings in list-directed input.
static bool skip_spaces (void)
static bool find_char (int)
static void save_gbl ()
static void restore_gbl ()
static void save_samefcb ()
static void allocate_new_gbl ()
static void free_gbl ()
static int _f90io_ldr_init (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat)
__INT_T (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat)
__INT_T (__INT_T *istat, DCHAR(blank), DCHAR(decimal), DCHAR(pad), DCHAR(round) DCLEN64(blank) DCLEN64(decimal) DCLEN64(pad) DCLEN64(round))
__INT_T (__INT_T *istat, DCHAR(blank), DCHAR(decimal), DCHAR(pad), DCHAR(round) DCLEN(blank) DCLEN(decimal) DCLEN(pad) DCLEN(round))
static int _f90io_ldr_intern_init (char *cunit, __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat, __CLEN_T cunit_siz)
__INT_T (DCHAR(cunit), __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat DCLEN64(cunit))
__INT_T (char **cunit, __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat, __INT_T *len)
int __f90io_ldr (int type, long length, int stride, char *item, __CLEN_T itemlen)
list-directed external file read initialization (defined in ldread.c)
__INT_T (__INT_T *type, __INT_T *count, __INT_T *stride, DCHAR(item) DCLEN64(item))
__INT_T (__INT_T *type, __INT_T *count, __INT_T *stride, DCHAR(item) DCLEN(item))
__INT_T (__INT_T *type, __INT8_T *count, __INT_T *stride, DCHAR(item) DCLEN64(item))
__INT_T (__INT_T *type, __INT8_T *count, __INT_T *stride, DCHAR(item) DCLEN(item))
static int is_repeat_count (char *p)
Given that a string begins with a digit, is it a repeat count?
static int _f90io_ldr_end (void)
__INT_T ENTF90IO (LDR_END, ldr_end)()
__INT_T ENTCRF90IO (LDR_END, ldr_end)()
Variables
static int dbgflag
static FIO_FCB * fcb
static bool accessed
static unsigned int byte_cnt
static int n_irecs
static bool internal_file
static int rec_len
static int gbl_dtype
static char rbuf [RBUF_SIZE+1]
static unsigned rbuf_size = RBUF_SIZE
static char * rbufp = rbuf
static char * currc
static char * in_recp
static G static_gbl [GBL_SIZE]
static G * gbl = &static_gbl[0]
static G * gbl_head = &static_gbl[0]
static int gbl_avl = 0
static int gbl_size = GBL_SIZE
static AVAL tknval
static int tkntyp
static int scan_err
static int repeat_cnt
static int prev_tkntyp
static bool comma_seen
static char chval [128]
static int chval_size = sizeof(chval)
static char * chvalp = chval
Detailed Description
List-directed read module.
Definition in file ldread.c.
Macro Definition Documentation
BEGINS_NUM
#define BEGINS_NUM (c) (ISDIGIT(c) || (c) == '.')
Definition at line 871 of file ldread.c.
DBGBIT
#define DBGBIT (v) (LOCAL_DEBUG && (dbgflag & v))
Definition at line 22 of file ldread.c.
GBL_SIZE
#define GBL_SIZE 5
Definition at line 84 of file ldread.c.
ISDELIMITER
#define ISDELIMITER (c) ((c) == ',' || (c) == ' ' || (c) == '\t' || (c) == '/' || (c == '\n'))
Definition at line 872 of file ldread.c.
RBUF_SIZE
#define RBUF_SIZE 256
Definition at line 45 of file ldread.c.
TK_ERROR
#define TK_ERROR 1
Definition at line 107 of file ldread.c.
TK_NULL
#define TK_NULL 2
Definition at line 108 of file ldread.c.
TK_SLASH
#define TK_SLASH 3
Definition at line 109 of file ldread.c.
TK_VAL
#define TK_VAL 4
Definition at line 110 of file ldread.c.
TK_VALS
#define TK_VALS 5
Definition at line 111 of file ldread.c.
Typedef Documentation
G
typedef struct struct_G G
Definition at line 86 of file ldread.c.
Function Documentation
__f90io_ldr()
int __f90io_ldr (int type, long length, int stride, char * item, __CLEN_T itemlen)
list-directed external file read initialization (defined in ldread.c)
Parameters
type data type (as defined in pghpft.h)
length # items of type to read
stride distance in bytes between items
item where to transfer data to
itemlen
Definition at line 618 of file ldread.c.
References __fortio_assign(), __fortio_errend03(), __fortio_error(), __io_printf, __NCHAR, __STR, byte_cnt, DBGBIT, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FIO_TBL::error, FIO_EERR_DATA_CONVERSION, fioFcbTbls, free_gbl(), gbl_dtype, get_token(), length(), prev_tkntyp, read_record(), restore_gbl(), scan_err, stride, TK_ERROR, TK_NULL, TK_SLASH, TK_VAL, TK_VALS, tkntyp, tknval, and type.
Referenced by __INT_T().
__INT_T() [1/9]
__INT_T (__INT_T * istat, DCHAR(blank) , DCHAR(decimal) , DCHAR(pad) , DCHAR(round) DCLEN(blank) DCLEN(decimal) DCLEN(pad) DCLEN(round))
Definition at line 457 of file ldread.c.
References __CLEN_T, CADR, CLEN, ENTF90IO(), and round().
__INT_T() [2/9]
__INT_T (__INT_T * istat, DCHAR(blank) , DCHAR(decimal) , DCHAR(pad) , DCHAR(round) DCLEN64(blank) DCLEN64(decimal) DCLEN64(pad) DCLEN64(round))
Definition at line 396 of file ldread.c.
References __fortio_eq_str(), __fortio_errend03(), __fortio_error(), G::blank_zero, CADR, CLEN, G::decimal, DIST_STATUS_BCST, FIO_COMMA, FIO_COMPATIBLE, FIO_DOWN, FIO_ESPEC, FIO_NEAREST, FIO_NO, FIO_NULL, FIO_POINT, FIO_PROCESSOR_DEFINED, FIO_UP, FIO_YES, FIO_ZERO, free_gbl(), gbl, GET_DIST_IOPROC, GET_DIST_LCPU, ISPRESENTC, LOCAL_MODE, G::pad, restore_gbl(), G::round, round(), and s.
__INT_T() [3/9]
__INT_T (__INT_T * type, __INT8_T * count, __INT_T * stride, DCHAR(item) DCLEN(item))
Definition at line 815 of file ldread.c.
References __CLEN_T, CADR, CLEN, count, ENTF90IO(), stride, and type.
__INT_T() [4/9]
__INT_T (__INT_T * type, __INT8_T * count, __INT_T * stride, DCHAR(item) DCLEN64(item))
Definition at line 782 of file ldread.c.
References __CLEN_T, __f90io_ldr(), __fort_abort(), __STR, CADR, CLEN, cnt, count, DIST_RBCSTL, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, GET_DIST_SIZE_OF, len, LOCAL_MODE, s, str, stride, and type.
__INT_T() [5/9]
__INT_T (__INT_T * type, __INT_T * count, __INT_T * stride, DCHAR(item) DCLEN(item))
Definition at line 725 of file ldread.c.
References __CLEN_T, CADR, CLEN, count, ENTF90IO(), stride, and type.
__INT_T() [6/9]
__INT_T (__INT_T * type, __INT_T * count, __INT_T * stride, DCHAR(item) DCLEN64(item))
Definition at line 693 of file ldread.c.
References __CLEN_T, __f90io_ldr(), __fort_abort(), __STR, CADR, CLEN, cnt, count, DIST_RBCSTL, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, GET_DIST_SIZE_OF, len, LOCAL_MODE, s, str, stride, and type.
__INT_T() [7/9]
__INT_T (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat)
Definition at line 376 of file ldread.c.
References __fort_status_init(), __fortio_errend03(), _f90io_ldr_init(), bitv, DIST_STATUS_BCST, free_gbl(), GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, restore_gbl(), and s.
__INT_T() [8/9]
__INT_T (char ** cunit, __INT_T * rec_num, __INT_T * bitv, __INT_T * iostat, __INT_T * len)
Definition at line 572 of file ldread.c.
References __fort_status_init(), _f90io_ldr_intern_init(), bitv, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, len, LOCAL_MODE, and s.
__INT_T() [9/9]
__INT_T (DCHAR(cunit) , __INT_T * rec_num, __INT_T * bitv, __INT_T *iostat DCLEN64cunit)
Definition at line 513 of file ldread.c.
References __fort_status_init(), _f90io_ldr_intern_init(), bitv, CADR, CLEN, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, and s.
_f90io_ldr_end()
static int _f90io_ldr_end (void) static
Definition at line 1731 of file ldread.c.
References __fortio_error(), __io_printf, byte_cnt, DBGBIT, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FIO_TBL::error, fioFcbTbls, gbl, and skip_record().
Referenced by ENTCRF90IO(), and ENTF90IO().
_f90io_ldr_init()
static int _f90io_ldr_init (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat) static
Definition at line 297 of file ldread.c.
References __fortio_errinit03(), __fortio_rwinit(), accessed, G::accessed, allocate_new_gbl(), bitv, G::blank_zero, byte_cnt, G::byte_cnt, comma_seen, currc, G::currc, fcb::decimal, G::decimal, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FALSE, FIO_FORMATTED, fioFcbTbls, gbl, gbl_avl, gbl_dtype, gbl_head, i, in_recp, G::in_recp, internal_file, G::internal_file, malloc(), n_irecs, G::n_irecs, NULL, G::pad, prev_tkntyp, rbuf, rbuf_size, rbufp, G::rbufp, rec_len, G::rec_len, fcb::reclen, repeat_cnt, G::round, G::same_fcb_idx, save_gbl(), shared_init(), and fcb::skip.
Referenced by __INT_T().
_f90io_ldr_intern_init()
static int _f90io_ldr_intern_init (char * cunit, __INT_T * rec_num, __INT_T * bitv, __INT_T * iostat, __CLEN_T cunit_siz) static
Definition at line 490 of file ldread.c.
References __fortio_errinit03(), allocate_new_gbl(), bitv, in_recp, internal_file, n_irecs, rec_len, save_gbl(), shared_init(), and TRUE.
Referenced by __INT_T().
alloc_rbuf()
static char * alloc_rbuf (int size, bool copy) static
Definition at line 1659 of file ldread.c.
References copy(), malloc(), rbuf, rbuf_size, rbufp, size, and void().
Referenced by read_record().
allocate_new_gbl()
static void allocate_new_gbl () static
Definition at line 253 of file ldread.c.
References gbl, gbl_avl, gbl_head, GBL_SIZE, gbl_size, malloc(), G::rbuf, RBUF_SIZE, and G::rbufp.
Referenced by _f90io_ldr_init(), and _f90io_ldr_intern_init().
ENTCRF90IO()
__INT_T ENTCRF90IO (LDR_END , ldr_end)
Definition at line 1771 of file ldread.c.
References __fortio_errend03(), _f90io_ldr_end(), free_gbl(), restore_gbl(), s, and save_samefcb().
ENTF90IO()
__INT_T ENTF90IO (LDR_END , ldr_end)
Definition at line 1755 of file ldread.c.
References __fortio_errend03(), _f90io_ldr_end(), DIST_STATUS_BCST, free_gbl(), GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, restore_gbl(), s, and save_samefcb().
Referenced by __INT_T().
find_char()
static bool find_char (int ch) static
Definition at line 1530 of file ldread.c.
References currc, FALSE, skip_spaces(), and TRUE.
Referenced by get_cmplx().
free_gbl()
static void free_gbl () static
Definition at line 281 of file ldread.c.
References gbl, gbl_avl, and gbl_head.
Referenced by __f90io_ldr(), __INT_T(), ENTCRF90IO(), and ENTF90IO().
get_cmplx()
static void get_cmplx (void) static
A left paren has been found. Create a complex constant. currc locates character after '('.
Definition at line 1251 of file ldread.c.
References __BIGCPLX, __BIGREAL, __NCHAR, __STR, atag::cmplx, atag::d, G::decimal, atag::dtype, find_char(), FIO_COMMA, FIO_ELEX, gbl, get_token(), scan_err, TK_ERROR, TK_VAL, tkntyp, tknval, to_bigreal(), and atag::val.
Referenced by get_token().
get_infinity()
static void get_infinity (void) static
An 'I' has been found. Is it an infinity? Valid are +inf, -inf, inf, +infinity, -infinity, infinity.
Definition at line 1287 of file ldread.c.
References __BIGREAL, c, currc, ieee::d, atag::d, atag::dtype, FIO_ELEX, ieee::i, ISDELIMITER, ieee::s, scan_err, TK_ERROR, TK_VAL, tkntyp, tknval, ieee::v, and atag::val.
Referenced by get_token().
get_junk()
static void get_junk (void) static
Non-quoted strings in list-directed input.
Definition at line 1476 of file ldread.c.
References atag::c, chval, chval_size, chvalp, currc, atag::dtype, FIO_ELEX, gbl_dtype, ISDELIMITER, len, atag::len, malloc(), read_record(), scan_err, atag::str, TK_ERROR, TK_VAL, tkntyp, tknval, TRUE, atag::val, and void().
Referenced by get_token().
get_nan()
static void get_nan (void) static
An 'N' has been found. Is it a NaN? Valid are nan and nan(ddd...)
Definition at line 1349 of file ldread.c.
References __BIGREAL, c, currc, ieee::d, atag::d, atag::dtype, ieee::e, FIO_ELEX, ieee::hm, ieee::i, ISDELIMITER, ieee::lm, scan_err, TK_ERROR, TK_VAL, tkntyp, tknval, TRUE, ieee::v, and atag::val.
Referenced by get_token().
get_number()
static void get_number (void) static
Extract integer, real, or double precision constant token:
Definition at line 1198 of file ldread.c.
References __BIGINT, __BIGREAL, __fortio_getnum(), __INT8, currc, atag::d, d, G::decimal, atag::dtype, FALSE, FIO_COMMA, FIO_EERR_DATA_CONVERSION, gbl, gbl_dtype, atag::i, i, atag::i8v, len, REAL_ALLOWED, scan_err, TK_ERROR, TK_VAL, tkntyp, tknval, TRUE, type, atag::val, and val.
Referenced by get_token().
get_qstr()
static void get_qstr (int quote) static
A quote has been seen (' or "). Create a character constant.
Definition at line 1434 of file ldread.c.
References atag::c, chval, chval_size, chvalp, currc, atag::dtype, FIO_ELEX, gbl_dtype, len, atag::len, malloc(), quote, read_record(), scan_err, atag::str, TK_ERROR, TK_VALS, tkntyp, tknval, TRUE, atag::val, and void().
Referenced by get_token().
get_token()
static void get_token (void) static
Definition at line 878 of file ldread.c.
References __BIGINT, __BIGLOG, __io_printf, __NCHAR, __STR, BEGINS_NUM, comma_seen, currc, DBGBIT, G::decimal, atag::dtype, FALSE, FIO_COMMA, FIO_ELEX, FTN_FALSE, FTN_TRUE, gbl, gbl_dtype, get_cmplx(), get_infinity(), get_junk(), get_nan(), get_number(), get_qstr(), get_token(), atag::i, is_repeat_count(), ISDELIMITER, ISDIGIT, prev_tkntyp, rc, read_record(), repeat_cnt, scan_err, TK_ERROR, TK_NULL, TK_SLASH, TK_VAL, tkntyp, tknval, TRUE, and atag::val.
Referenced by __f90io_ldr(), _parser(), addfield(), get_cmplx(), get_token(), and proc_sym().
is_repeat_count()
static int is_repeat_count (char * p) static
Given that a string begins with a digit, is it a repeat count?
If a string of digits is immediately followed by '*', then the digit string is a repeat count.
Definition at line 1175 of file ldread.c.
References ISDIGIT, p, q, and TRUE.
Referenced by get_token().
read_record()
static int read_record (void) static
Definition at line 1547 of file ldread.c.
References __io_errno(), __io_feof(), __io_fgetc, __io_fread, __io_printf, __io_ungetc, fcb::acc, accessed, alloc_rbuf(), byte_cnt, comma_seen, currc, DBGBIT, EOR_CRLF, f, FALSE, FIO_DIRECT, FIO_EDREAD, FIO_EEOF, fcb::fp, in_recp, internal_file, fcb::maxrec, n_irecs, fcb::nextrec, p, fcb::pback, fcb::pread, rbuf_size, rbufp, read_record_internal(), rec_len, TRUE, and void().
Referenced by __f90io_ldr(), get_junk(), get_qstr(), get_token(), and skip_spaces().
read_record_internal()
int read_record_internal (void)
Definition at line 478 of file runtime/flang/error.c.
References current_unit, FIO_BITV_NONE, FIO_EEOF, and iobitv.
Referenced by read_record().
restore_gbl()
static void restore_gbl () static
Definition at line 172 of file ldread.c.
References accessed, G::accessed, assert, byte_cnt, G::byte_cnt, comma_seen, currc, G::currc, gbl, gbl_avl, gbl_dtype, in_recp, G::in_recp, internal_file, G::internal_file, malloc(), n_irecs, G::n_irecs, NULL, prev_tkntyp, rbuf, rbuf_size, rbufp, G::rbufp, rec_len, G::rec_len, repeat_cnt, scan_err, tkntyp, and tknval.
Referenced by __f90io_ldr(), __INT_T(), ENTCRF90IO(), and ENTF90IO().
save_gbl()
static void save_gbl () static
Definition at line 135 of file ldread.c.
References accessed, G::accessed, assert, byte_cnt, G::byte_cnt, comma_seen, currc, G::currc, fcb, gbl, gbl_avl, gbl_dtype, in_recp, G::in_recp, internal_file, G::internal_file, malloc(), n_irecs, G::n_irecs, NULL, prev_tkntyp, G::rbuf, RBUF_SIZE, rbuf_size, rbufp, G::rbufp, rec_len, G::rec_len, repeat_cnt, scan_err, tkntyp, and tknval.
Referenced by _f90io_ldr_init(), and _f90io_ldr_intern_init().
save_samefcb()
static void save_samefcb () static
Definition at line 212 of file ldread.c.
References accessed, G::accessed, assert, G::blank_zero, byte_cnt, G::byte_cnt, currc, G::currc, G::decimal, gbl, gbl_dtype, gbl_head, in_recp, G::in_recp, internal_file, G::internal_file, malloc(), n_irecs, G::n_irecs, NULL, G::pad, prev_tkntyp, G::rbuf, rbuf_size, rbufp, G::rbufp, rec_len, G::rec_len, repeat_cnt, G::round, and G::same_fcb_idx.
Referenced by ENTCRF90IO(), and ENTF90IO().
shared_init()
static void shared_init (void) static
Definition at line 606 of file ldread.c.
References accessed, byte_cnt, comma_seen, FALSE, prev_tkntyp, and repeat_cnt.
Referenced by _f90io_ldr_init(), and _f90io_ldr_intern_init().
skip_record()
static int skip_record (void) static
Definition at line 1675 of file ldread.c.
References __io_errno(), __io_feof(), __io_fgetc, __io_fseek, __io_ungetc, fcb::acc, fcb::coherent, FIO_DIRECT, FIO_EDREAD, FIO_EEOF, fcb::fp, gbl, internal_file, fcb::maxrec, n_irecs, fcb::nextrec, rec_len, and TRUE.
Referenced by _f90io_ldr_end().
skip_spaces()
static bool skip_spaces (void) static
Definition at line 1514 of file ldread.c.
References currc, FALSE, read_record(), scan_err, and TRUE.
Referenced by find_char().
to_bigreal()
static __BIGREAL_T to_bigreal (AVAL * valp) static
Definition at line 1414 of file ldread.c.
References __BIGINT, __BIGLOG, __BIGREAL, __INT8, __LOG8, assert, atag::d, atag::dtype, atag::i, and atag::val.
Referenced by get_cmplx().
Variable Documentation
accessed
bool accessed static
Definition at line 37 of file ldread.c.
Referenced by _f90io_ldr_init(), read_record(), restore_gbl(), save_gbl(), save_samefcb(), and shared_init().
byte_cnt
unsigned int byte_cnt static
Definition at line 38 of file ldread.c.
Referenced by __f90io_ldr(), _f90io_ldr_end(), _f90io_ldr_init(), read_record(), restore_gbl(), save_gbl(), save_samefcb(), and shared_init().
chval
char chval[128] static
Definition at line 1426 of file ldread.c.
Referenced by get_junk(), and get_qstr().
chval_size
int chval_size = sizeof(chval) static
Definition at line 1427 of file ldread.c.
Referenced by get_junk(), and get_qstr().
chvalp
char* chvalp = chval static
Definition at line 1428 of file ldread.c.
Referenced by get_junk(), and get_qstr().
comma_seen
bool comma_seen static
Definition at line 132 of file ldread.c.
Referenced by _f90io_ldr_init(), fr_Breadnum(), fr_OZreadnum(), fr_readnum(), get_token(), read_record(), restore_gbl(), save_gbl(), and shared_init().
currc
char* currc static
Definition at line 50 of file ldread.c.
Referenced by __fortio_getnum(), _f90io_ldr_init(), find_char(), get_infinity(), get_junk(), get_nan(), get_number(), get_qstr(), get_token(), read_record(), restore_gbl(), save_gbl(), save_samefcb(), and skip_spaces().
dbgflag
int dbgflag static
Definition at line 20 of file ldread.c.
fcb
FIO_FCB* fcb static
Definition at line 36 of file ldread.c.
Referenced by save_gbl().
gbl
G* gbl = &static_gbl[0] static
Definition at line 89 of file ldread.c.
Referenced by __INT_T(), _f90io_ldr_end(), _f90io_ldr_init(), allocate_new_gbl(), free_gbl(), get_cmplx(), get_number(), get_token(), restore_gbl(), save_gbl(), save_samefcb(), and skip_record().
gbl_avl
int gbl_avl = 0 static
Definition at line 91 of file ldread.c.
Referenced by _f90io_ldr_init(), allocate_new_gbl(), free_gbl(), restore_gbl(), and save_gbl().
gbl_dtype
int gbl_dtype static
Definition at line 43 of file ldread.c.
Referenced by __f90io_ldr(), _f90io_ldr_init(), get_junk(), get_number(), get_qstr(), get_token(), restore_gbl(), save_gbl(), and save_samefcb().
gbl_head
G* gbl_head = &static_gbl[0] static
Definition at line 90 of file ldread.c.
Referenced by _f90io_ldr_init(), allocate_new_gbl(), free_gbl(), and save_samefcb().
gbl_size
int gbl_size = GBL_SIZE static
Definition at line 92 of file ldread.c.
Referenced by allocate_new_gbl().
in_recp
char* in_recp static
Definition at line 52 of file ldread.c.
Referenced by _f90io_ldr_init(), _f90io_ldr_intern_init(), read_record(), restore_gbl(), save_gbl(), and save_samefcb().
internal_file
bool internal_file static
Definition at line 40 of file ldread.c.
Referenced by _f90io_ldr_init(), _f90io_ldr_intern_init(), read_record(), restore_gbl(), save_gbl(), save_samefcb(), and skip_record().
n_irecs
int n_irecs static
Definition at line 39 of file ldread.c.
Referenced by _f90io_ldr_init(), _f90io_ldr_intern_init(), read_record(), restore_gbl(), save_gbl(), save_samefcb(), and skip_record().
prev_tkntyp
int prev_tkntyp static
Definition at line 131 of file ldread.c.
Referenced by __f90io_ldr(), _f90io_ldr_init(), get_token(), restore_gbl(), save_gbl(), save_samefcb(), and shared_init().
rbuf
char rbuf[RBUF_SIZE+1] static
Definition at line 46 of file ldread.c.
Referenced by _f90io_ldr_init(), alloc_rbuf(), and restore_gbl().
rbuf_size
unsigned rbuf_size = RBUF_SIZE static
Definition at line 47 of file ldread.c.
Referenced by _f90io_ldr_init(), alloc_rbuf(), read_record(), restore_gbl(), save_gbl(), and save_samefcb().
rbufp
char* rbufp = rbuf static
Definition at line 49 of file ldread.c.
Referenced by _f90io_ldr_init(), alloc_rbuf(), read_record(), restore_gbl(), save_gbl(), and save_samefcb().
rec_len
int rec_len static
Definition at line 41 of file ldread.c.
Referenced by _f90io_ldr_init(), _f90io_ldr_intern_init(), read_record(), restore_gbl(), save_gbl(), save_samefcb(), and skip_record().
repeat_cnt
int repeat_cnt static
Definition at line 130 of file ldread.c.
Referenced by _f90io_ldr_init(), emit_init(), get_struct_from_dsrt2(), get_token(), process_dsrt(), restore_gbl(), save_gbl(), save_samefcb(), and shared_init().
scan_err
int scan_err static
Definition at line 127 of file ldread.c.
Referenced by __f90io_ldr(), get_cmplx(), get_infinity(), get_junk(), get_nan(), get_number(), get_qstr(), get_token(), restore_gbl(), save_gbl(), and skip_spaces().
static_gbl
G static_gbl[GBL_SIZE] static
Definition at line 88 of file ldread.c.
tkntyp
int tkntyp static
Definition at line 126 of file ldread.c.
Referenced by __f90io_ldr(), _parser(), get_cmplx(), get_infinity(), get_junk(), get_nan(), get_number(), get_qstr(), get_token(), is_declaration(), is_executable(), next_state(), prettytoken(), restore_gbl(), and save_gbl().
tknval
AVAL tknval static
Definition at line 125 of file ldread.c.
Referenced by __f90io_ldr(), get_cmplx(), get_infinity(), get_junk(), get_nan(), get_number(), get_qstr(), get_token(), prettytoken(), restore_gbl(), and save_gbl().