flang: ldwrite.c File Reference
ldwrite.c File Reference
Lst-directed write module.
#include "global.h"
#include "format.h"
#include "list_io.h"
#include <string.h>
Classes
struct struct_G
Macros
#define DBGBIT(v) (LOCAL_DEBUG && (dbgflag & v))
#define GBL_SIZE 5
#define BL_BUF bl_buf
#define BL_BUFSZ sizeof(bl_buf)
Typedefs
typedef struct struct_G G
Functions
static int write_item (const char *, int)
static int write_record (void)
static void save_gbl ()
static void save_samefcb ()
static void restore_gbl ()
static void allocate_new_gbl ()
static void free_gbl ()
static int _f90io_ldw_init (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat)
__INT_T (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat)
__INT_T (__INT_T *istat, DCHAR(decimal), DCHAR(delim), DCHAR(sign) DCLEN64(decimal) DCLEN64(delim) DCLEN64(sign))
__INT_T (__INT_T *istat, DCHAR(decimal), DCHAR(delim), DCHAR(sign) DCLEN(decimal) DCLEN(delim) DCLEN(sign))
static int _f90io_ldw_intern_init (char *cunit, __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat, __CLEN_T cunit_len)
__INT_T (DCHAR(cunit), __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat DCLEN64(cunit))
__INT_T (char **cunit, __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat, __INT_T *len)
int __f90io_ldw (int type, long length, int stride, char *item, __CLEN_T item_length)
list-directed external file write initializations (defined in ldwrite.c)
__INT_T (__INT_T *type, __INT_T *length, __INT_T *stride, DCHAR(item) DCLEN64(item))
__INT_T (__INT_T *type, __INT_T *length, __INT_T *stride, DCHAR(item) DCLEN(item))
__INT_T (__INT_T *type, __INT8_T *length, __INT_T *stride, DCHAR(item) DCLEN64(item))
__INT_T (__INT_T *type, __INT8_T *length, __INT_T *stride, DCHAR(item) DCLEN(item))
static int _f90io_ldw_end ()
__INT_T ENTF90IO (LDW_END, ldw_end)()
__INT_T ENTCRF90IO (LDW_END, ldw_end)()
__INT_T ENTF90IO (SC_LDW, sc_ldw)
__INT_T ENTF90IO (SC_I_LDW, sc_i_ldw)
__INT_T ENTF90IO (SC_L_LDW, sc_l_ldw)
__INT_T ENTF90IO (SC_F_LDW, sc_f_ldw)
__INT_T ENTF90IO (SC_D_LDW, sc_d_ldw)
__INT_T ENTF90IO (SC_Q_LDW, sc_q_ldw)
__INT_T ENTF90IO (SC_CF_LDW, sc_cf_ldw)
__INT_T ENTF90IO (SC_CD_LDW, sc_cd_ldw)
__INT_T ENTF90IO (SC_CH_LDW, sc_ch_ldw)
Variables
static int dbgflag
static FIO_FCB * fcb
static char * in_recp
static char * in_curp
static bool record_written
static int byte_cnt
static int rec_len
static int n_irecs
static bool write_called
static bool internal_file
static char * internal_unit
static char delim
static int last_type
static G static_gbl [GBL_SIZE]
static G * gbl = &static_gbl[0]
static G * gbl_head = &static_gbl[0]
static int gbl_avl = 0
static int gbl_size = GBL_SIZE
char __f90io_conv_buf []
Detailed Description
Lst-directed write module.
Definition in file ldwrite.c.
Macro Definition Documentation
BL_BUF
#define BL_BUF bl_buf
BL_BUFSZ
#define BL_BUFSZ sizeof(bl_buf)
DBGBIT
#define DBGBIT (v) (LOCAL_DEBUG && (dbgflag & v))
Definition at line 22 of file ldwrite.c.
GBL_SIZE
#define GBL_SIZE 5
Definition at line 64 of file ldwrite.c.
Typedef Documentation
G
typedef struct struct_G G
Definition at line 65 of file ldwrite.c.
Function Documentation
__f90io_ldw()
int __f90io_ldw (int type, long length, int stride, char * item, __CLEN_T item_length)
list-directed external file write initializations (defined in ldwrite.c)
Parameters
type data type (as defined in pghpft.h)
length # items of type to write. May be <= 0
stride distance in bytes between items
item where to transfer data from
item_length
Definition at line 559 of file ldwrite.c.
References __f90io_conv_buf, __fortio_default_convert(), __fortio_errend03(), __fortio_error(), __io_printf, __STR, byte_cnt, DBGBIT, G::decimal, delim, ERR_FLAG, FIO_TBL::error, FALSE, FIO_COMMA, FIO_PLUS, fioFcbTbls, free_gbl(), gbl, Is_complex, last_type, length(), malloc(), p, restore_gbl(), G::round, G::sign, stride, TRUE, type, write_called, and write_item().
Referenced by __INT_T(), and ENTF90IO().
__INT_T() [1/9]
__INT_T (__INT_T * istat, DCHAR(decimal) , DCHAR(delim) , DCHAR(sign) DCLEN(decimal) DCLEN(delim) DCLEN(sign))
Definition at line 370 of file ldwrite.c.
References __CLEN_T, CADR, CLEN, struct_G::decimal, delim, ENTF90IO(), and sign.
__INT_T() [2/9]
__INT_T (__INT_T * istat, DCHAR(decimal) , DCHAR(delim) , DCHAR(sign) DCLEN64(decimal) DCLEN64(delim) DCLEN64(sign))
Definition at line 317 of file ldwrite.c.
References __fortio_eq_str(), __fortio_errend03(), __fortio_error(), CADR, CLEN, struct_G::decimal, G::decimal, delim, DIST_STATUS_BCST, FIO_COMMA, FIO_ESPEC, FIO_PLUS, FIO_POINT, FIO_PROCESSOR_DEFINED, FIO_SUPPRESS, free_gbl(), gbl, GET_DIST_IOPROC, GET_DIST_LCPU, ISPRESENTC, LOCAL_MODE, restore_gbl(), s, sign, and G::sign.
__INT_T() [3/9]
__INT_T (__INT_T * type, __INT8_T * length, __INT_T * stride, DCHAR(item) DCLEN(item))
Definition at line 732 of file ldwrite.c.
References __CLEN_T, CADR, CLEN, ENTF90IO(), length(), stride, and type.
__INT_T() [4/9]
__INT_T (__INT_T * type, __INT8_T * length, __INT_T * stride, DCHAR(item) DCLEN64(item))
Definition at line 716 of file ldwrite.c.
References __f90io_ldw(), __STR, CADR, CLEN, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, length(), LOCAL_MODE, s, stride, and type.
__INT_T() [5/9]
__INT_T (__INT_T * type, __INT_T * length, __INT_T * stride, DCHAR(item) DCLEN(item))
Definition at line 675 of file ldwrite.c.
References __CLEN_T, CADR, CLEN, ENTF90IO(), length(), stride, and type.
__INT_T() [6/9]
__INT_T (__INT_T * type, __INT_T * length, __INT_T * stride, DCHAR(item) DCLEN64(item))
Definition at line 659 of file ldwrite.c.
References __f90io_ldw(), __STR, CADR, CLEN, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, length(), LOCAL_MODE, s, stride, and type.
__INT_T() [7/9]
__INT_T (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat)
Definition at line 237 of file ldwrite.c.
References __fort_status_init(), __fortio_errend03(), _f90io_ldw_init(), bitv, DIST_STATUS_BCST, FALSE, free_gbl(), gbl, GET_DIST_IOPROC, GET_DIST_LCPU, internal_file, G::internal_file, LOCAL_MODE, restore_gbl(), and s.
__INT_T() [8/9]
__INT_T (char ** cunit, __INT_T * rec_num, __INT_T * bitv, __INT_T * iostat, __INT_T * len)
Definition at line 498 of file ldwrite.c.
References __fort_status_init(), __fortio_errend03(), _f90io_ldw_intern_init(), bitv, DIST_STATUS_BCST, free_gbl(), gbl, GET_DIST_IOPROC, GET_DIST_LCPU, internal_file, G::internal_file, internal_unit, G::internal_unit, len, LOCAL_MODE, restore_gbl(), s, and TRUE.
__INT_T() [9/9]
__INT_T (DCHAR(cunit) , __INT_T * rec_num, __INT_T * bitv, __INT_T *iostat DCLEN64cunit)
Definition at line 415 of file ldwrite.c.
References __fort_status_init(), __fortio_errend03(), _f90io_ldw_intern_init(), bitv, CADR, CLEN, DIST_STATUS_BCST, free_gbl(), gbl, GET_DIST_IOPROC, GET_DIST_LCPU, internal_file, G::internal_file, internal_unit, G::internal_unit, LOCAL_MODE, restore_gbl(), s, and TRUE.
_f90io_ldw_end()
static int _f90io_ldw_end () static
Definition at line 891 of file ldwrite.c.
References __fortio_error(), __io_errno(), fcb::acc, byte_cnt, ERR_FLAG, FIO_TBL::error, FALSE, FIO_DIRECT, fioFcbTbls, fcb::fp, FWRITE, gbl, in_curp, in_recp, internal_file, fcb::maxrec, fcb::nextrec, fcb::nonadvance, rec_len, record_written, write_called, and write_record().
Referenced by ENTCRF90IO(), and ENTF90IO().
_f90io_ldw_init()
static int _f90io_ldw_init (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat) static
Definition at line 171 of file ldwrite.c.
References __fortio_errinit03(), __fortio_rwinit(), __NONE, allocate_new_gbl(), bitv, byte_cnt, G::byte_cnt, fcb::decimal, G::decimal, fcb::delim, delim, G::delim, ERR_FLAG, FALSE, FIO_APOSTROPHE, FIO_FORMATTED, FIO_QUOTE, gbl, gbl_avl, gbl_head, i, if(), in_curp, G::in_curp, in_recp, G::in_recp, last_type, n_irecs, G::n_irecs, NULL, rec_len, G::rec_len, fcb::reclen, record_written, fcb::round, G::round, G::same_fcb_idx, save_gbl(), fcb::sign, G::sign, fcb::skip, and write_called.
Referenced by __INT_T().
_f90io_ldw_intern_init()
static int _f90io_ldw_intern_init (char * cunit, __INT_T * rec_num, __INT_T * bitv, __INT_T * iostat, __CLEN_T cunit_len) static
Definition at line 385 of file ldwrite.c.
References __fortio_errinit(), __NONE, allocate_new_gbl(), bitv, byte_cnt, delim, in_curp, in_recp, last_type, n_irecs, rec_len, save_gbl(), and void().
Referenced by __INT_T().
allocate_new_gbl()
static void allocate_new_gbl () static
Definition at line 134 of file ldwrite.c.
References gbl, gbl_avl, gbl_head, GBL_SIZE, gbl_size, and malloc().
Referenced by _f90io_ldw_init(), and _f90io_ldw_intern_init().
ENTCRF90IO()
__INT_T ENTCRF90IO (LDW_END , ldw_end)
Definition at line 959 of file ldwrite.c.
References __fortio_errend03(), _f90io_ldw_end(), free_gbl(), restore_gbl(), s, and save_samefcb().
ENTF90IO() [1/10]
__INT_T ENTF90IO (LDW_END , ldw_end)
Definition at line 934 of file ldwrite.c.
References __CHAR, __CINT, __fortio_errend03(), _f90io_ldw_end(), DIST_RBCSTL, DIST_STATUS_BCST, free_gbl(), GET_DIST_IOPROC, GET_DIST_LCPU, in_recp, internal_file, internal_unit, len, LOCAL_MODE, restore_gbl(), s, and save_samefcb().
Referenced by __INT_T().
ENTF90IO() [2/10]
__INT_T ENTF90IO (SC_CD_LDW , sc_cd_ldw)
Definition at line 1053 of file ldwrite.c.
References __f90io_ldw(), and type.
ENTF90IO() [3/10]
__INT_T ENTF90IO (SC_CF_LDW , sc_cf_ldw)
Definition at line 1041 of file ldwrite.c.
References __f90io_ldw(), and type.
ENTF90IO() [4/10]
__INT_T ENTF90IO (SC_CH_LDW , sc_ch_ldw)
Definition at line 1079 of file ldwrite.c.
References __f90io_ldw(), len, and type.
ENTF90IO() [5/10]
__INT_T ENTF90IO (SC_D_LDW , sc_d_ldw)
Definition at line 1029 of file ldwrite.c.
References __f90io_ldw(), and type.
ENTF90IO() [6/10]
__INT_T ENTF90IO (SC_F_LDW , sc_f_ldw)
Definition at line 1023 of file ldwrite.c.
References __f90io_ldw(), and type.
ENTF90IO() [7/10]
__INT_T ENTF90IO (SC_I_LDW , sc_i_ldw)
Definition at line 1011 of file ldwrite.c.
References __f90io_ldw(), and type.
ENTF90IO() [8/10]
__INT_T ENTF90IO (SC_L_LDW , sc_l_ldw)
Definition at line 1017 of file ldwrite.c.
References __f90io_ldw(), and type.
ENTF90IO() [9/10]
__INT_T ENTF90IO (SC_LDW , sc_ldw)
Definition at line 1002 of file ldwrite.c.
References __f90io_ldw(), and type.
ENTF90IO() [10/10]
__INT_T ENTF90IO (SC_Q_LDW , sc_q_ldw)
Definition at line 1035 of file ldwrite.c.
References __f90io_ldw(), and type.
free_gbl()
static void free_gbl () static
Definition at line 155 of file ldwrite.c.
References gbl, gbl_avl, and gbl_head.
Referenced by __f90io_ldw(), __INT_T(), ENTCRF90IO(), and ENTF90IO().
restore_gbl()
static void restore_gbl () static
Definition at line 115 of file ldwrite.c.
References byte_cnt, G::byte_cnt, delim, G::delim, gbl, gbl_avl, in_curp, G::in_curp, in_recp, G::in_recp, internal_file, G::internal_file, internal_unit, G::internal_unit, last_type, n_irecs, G::n_irecs, rec_len, G::rec_len, record_written, and write_called.
Referenced by __f90io_ldw(), __INT_T(), ENTCRF90IO(), and ENTF90IO().
save_gbl()
static void save_gbl () static
Definition at line 79 of file ldwrite.c.
References byte_cnt, G::byte_cnt, delim, G::delim, fcb, gbl, gbl_avl, in_curp, G::in_curp, in_recp, G::in_recp, last_type, n_irecs, G::n_irecs, rec_len, G::rec_len, record_written, and write_called.
Referenced by _f90io_ldw_init(), and _f90io_ldw_intern_init().
save_samefcb()
static void save_samefcb () static
Definition at line 96 of file ldwrite.c.
References byte_cnt, G::byte_cnt, delim, G::delim, gbl, gbl_head, in_curp, G::in_curp, in_recp, G::in_recp, last_type, n_irecs, G::n_irecs, rec_len, G::rec_len, record_written, G::same_fcb_idx, and write_called.
Referenced by ENTCRF90IO(), and ENTF90IO().
write_item()
static int write_item (const char * p, int len) static
Definition at line 770 of file ldwrite.c.
References __io_errno(), __io_printf, fcb::acc, byte_cnt, DBGBIT, FALSE, FIO_DIRECT, FIO_ETOOBIG, FIO_ETOOFAR, fcb::fp, FWRITE, in_curp, in_recp, internal_file, len, n_irecs, p, rec_len, fcb::reclen, record_written, void(), and write_record().
Referenced by __f90io_ldw().
write_record()
static int write_record (void) static
Definition at line 843 of file ldwrite.c.
References __io_binary_mode(), __io_errno(), __io_printf, __NONE, fcb::acc, assert, BL_BUF, BL_BUFSZ, byte_cnt, DBGBIT, FIO_TBL::eof, FIO_TBL::error, FIO_DIRECT, fioFcbTbls, fcb::fp, FWRITE, internal_file, j, last_type, n, fcb::nextrec, struct_G::pad, rec_len, record_written, and TRUE.
Referenced by _f90io_ldw_end(), and write_item().
Variable Documentation
__f90io_conv_buf
char __f90io_conv_buf[] extern
Definition at line 65 of file fmtconv.c.
Referenced by __f90io_ldw(), __fortio_default_convert(), and put_buf().
byte_cnt
int byte_cnt static
Definition at line 30 of file ldwrite.c.
Referenced by __f90io_ldw(), _f90io_ldw_end(), _f90io_ldw_init(), _f90io_ldw_intern_init(), restore_gbl(), save_gbl(), save_samefcb(), write_item(), and write_record().
dbgflag
int dbgflag static
Definition at line 20 of file ldwrite.c.
delim
char delim static
Definition at line 36 of file ldwrite.c.
Referenced by __f90io_ldw(), __INT_T(), _f90io_ldw_init(), _f90io_ldw_intern_init(), crunch(), dodef(), doincl(), ENTCRF90IO(), ENTF90IO(), get_token(), nextok(), restore_gbl(), save_gbl(), and save_samefcb().
fcb
FIO_FCB* fcb static
Definition at line 24 of file ldwrite.c.
Referenced by save_gbl().
gbl
G* gbl = &static_gbl[0] static
Definition at line 68 of file ldwrite.c.
Referenced by __f90io_ldw(), __INT_T(), _f90io_ldw_end(), _f90io_ldw_init(), allocate_new_gbl(), free_gbl(), restore_gbl(), save_gbl(), and save_samefcb().
gbl_avl
int gbl_avl = 0 static
Definition at line 70 of file ldwrite.c.
Referenced by _f90io_ldw_init(), allocate_new_gbl(), free_gbl(), restore_gbl(), and save_gbl().
gbl_head
G* gbl_head = &static_gbl[0] static
Definition at line 69 of file ldwrite.c.
Referenced by _f90io_ldw_init(), allocate_new_gbl(), free_gbl(), and save_samefcb().
gbl_size
int gbl_size = GBL_SIZE static
Definition at line 71 of file ldwrite.c.
Referenced by allocate_new_gbl().
in_curp
char* in_curp static
Definition at line 27 of file ldwrite.c.
Referenced by _f90io_ldw_end(), _f90io_ldw_init(), _f90io_ldw_intern_init(), restore_gbl(), save_gbl(), save_samefcb(), and write_item().
in_recp
char* in_recp static
Definition at line 26 of file ldwrite.c.
Referenced by _f90io_ldw_end(), _f90io_ldw_init(), _f90io_ldw_intern_init(), ENTF90IO(), restore_gbl(), save_gbl(), save_samefcb(), and write_item().
internal_file
bool internal_file static
Definition at line 34 of file ldwrite.c.
Referenced by __INT_T(), _f90io_ldw_end(), ENTF90IO(), restore_gbl(), write_item(), and write_record().
internal_unit
char* internal_unit static
Definition at line 35 of file ldwrite.c.
Referenced by __INT_T(), dtio_read_scalar(), ENTF90IO(), and restore_gbl().
last_type
int last_type static
Definition at line 38 of file ldwrite.c.
Referenced by __f90io_ldw(), _f90io_ldw_init(), _f90io_ldw_intern_init(), restore_gbl(), save_gbl(), save_samefcb(), and write_record().
n_irecs
int n_irecs static
Definition at line 32 of file ldwrite.c.
Referenced by _f90io_ldw_init(), _f90io_ldw_intern_init(), restore_gbl(), save_gbl(), save_samefcb(), and write_item().
rec_len
int rec_len static
Definition at line 31 of file ldwrite.c.
Referenced by _f90io_ldw_end(), _f90io_ldw_init(), _f90io_ldw_intern_init(), restore_gbl(), save_gbl(), save_samefcb(), write_item(), and write_record().
record_written
bool record_written static
Definition at line 29 of file ldwrite.c.
Referenced by _f90io_ldw_end(), _f90io_ldw_init(), restore_gbl(), save_gbl(), save_samefcb(), write_item(), and write_record().
static_gbl
G static_gbl[GBL_SIZE] static
Definition at line 67 of file ldwrite.c.
write_called
bool write_called static
Definition at line 33 of file ldwrite.c.
Referenced by __f90io_ldw(), _f90io_ldw_end(), _f90io_ldw_init(), restore_gbl(), save_gbl(), and save_samefcb().