flang: legacy-folding-api.c File Reference
legacy-folding-api.c File Reference
Implement legacy folding interfaces.
#include "legacy-folding-api.h"
#include "fp-folding.h"
#include "int128.h"
#include <assert.h>
#include <ctype.h>
#include <errno.h>
#include <inttypes.h>
#include <limits.h>
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
Functions
static bool is_host_little_endian (void)
static void unwrap_l (int64_t *x, const DBLINT64 y)
static void unwrap_u (uint64_t *x, const DBLUINT64 y)
static void wrap_l (DBLINT64 res, int64_t *x)
static void wrap_u (DBLUINT64 res, uint64_t *x)
static void unwrap_f (float32_t *f, IEEE32 *x)
static void wrap_f (IEEE32 *f, float32_t *x)
static void unwrap_d (float64_t *x, const IEEE64 d)
static void wrap_d (IEEE64 res, const float64_t *x)
void xdtomd (IEEE64 d, double *md)
void xmdtod (double md, IEEE64 d)
int cmp64 (DBLINT64 arg1, DBLINT64 arg2)
int ucmp64 (DBLUINT64 arg1, DBLUINT64 arg2)
void add64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
void div64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
void exp64 (DBLINT64 arg, INT exp, DBLINT64 result)
void mul64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
void mul64_10 (DBLINT64 arg, DBLINT64 result)
void neg64 (DBLINT64 arg, DBLINT64 result)
void shf64 (DBLINT64 arg, int count, DBLINT64 result)
void sub64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
void uadd64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
void uneg64 (DBLUINT64 arg, DBLUINT64 result)
void ushf64 (DBLUINT64 arg, int count, DBLUINT64 result)
void usub64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
void udiv64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
void umul64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
void umul64_10 (DBLUINT64 arg, DBLUINT64 result)
void and64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
void not64 (DBLINT64 arg, DBLINT64 result)
void or64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
void xor64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
void ui64toax (DBLINT64 from, char *to, int size, int is_unsigned, int radix)
static void unwrap_i128 (int128_t *result, const INT128 i)
static void wrap_i128 (INT128 i, const int128_t *x)
void shf128 (INT128 arg, int count, INT128 result)
void add128 (INT128 arg1, INT128 arg2, INT128 result)
void sub128 (INT128 arg1, INT128 arg2, INT128 result)
int cmp128 (INT128 arg1, INT128 arg2)
void mul128l (INT128 arg1, INT128 arg2, INT128 result)
void div128 (INT128 arg1, INT128 arg2, INT128 result)
static void check (enum fold_status status)
void xfix (IEEE32 f, INT *i)
void xfixu (IEEE32 f, UINT *u)
void xffixu (IEEE32 f, UINT *u)
void xfix64 (IEEE32 f, DBLINT64 l)
void xfixu64 (IEEE32 f, DBLUINT64 u)
void xffloat (INT i, IEEE32 *f)
void xffloatu (UINT u, IEEE32 *f)
void xflt64 (DBLINT64 l, IEEE32 *f)
void xfltu64 (DBLUINT64 u, IEEE32 *f)
void xfadd (IEEE32 f1, IEEE32 f2, IEEE32 *r)
void xfsub (IEEE32 f1, IEEE32 f2, IEEE32 *r)
void xfneg (IEEE32 f, IEEE32 *r)
void xfmul (IEEE32 f1, IEEE32 f2, IEEE32 *r)
void xfdiv (IEEE32 f1, IEEE32 f2, IEEE32 *r)
void xfrcp (IEEE32 f, IEEE32 *r)
void xfabsv (IEEE32 f, IEEE32 *r)
void xfsqrt (IEEE32 f, IEEE32 *r)
void xfpow (IEEE32 f1, IEEE32 f2, IEEE32 *r)
void xfsin (IEEE32 f, IEEE32 *r)
void xfcos (IEEE32 f, IEEE32 *r)
void xftan (IEEE32 f, IEEE32 *r)
void xfasin (IEEE32 f, IEEE32 *r)
void xfacos (IEEE32 f, IEEE32 *r)
void xfatan (IEEE32 f, IEEE32 *r)
void xfatan2 (IEEE32 f1, IEEE32 f2, IEEE32 *r)
void xfexp (IEEE32 f, IEEE32 *r)
void xflog (IEEE32 f, IEEE32 *r)
void xflog10 (IEEE32 f, IEEE32 *r)
int xfcmp (IEEE32 f1, IEEE32 f2)
int xfisint (IEEE32 f, int *i)
static void get_literal (char *buffer, size_t length, const char *s, int n, bool is_hex)
static int handle_parsing_errors (const char *buffer, const char *end, int errno_capture, bool iszero)
static int parse_f (const char *s, IEEE32 *f, int n, bool is_hex)
int atoxf (const char *s, IEEE32 *f, int n)
int hxatoxf (const char *s, IEEE32 *f, int n)
void xdfix (IEEE64 d, INT *i)
void xdfixu (IEEE64 d, UINT *u)
void xdfix64 (IEEE64 d, DBLINT64 l)
void xdfixu64 (IEEE64 d, DBLUINT64 u)
void xdfloat (INT i, IEEE64 d)
void xdfloatu (UINT u, IEEE64 d)
void xdflt64 (DBLINT64 l, IEEE64 d)
void xdfltu64 (DBLUINT64 u, IEEE64 d)
void xdble (IEEE32 f, IEEE64 r)
void xsngl (IEEE64 d, IEEE32 *r)
void xdadd (IEEE64 d1, IEEE64 d2, IEEE64 r)
void xdsub (IEEE64 d1, IEEE64 d2, IEEE64 r)
void xdneg (IEEE64 d, IEEE64 r)
void xdmul (IEEE64 d1, IEEE64 d2, IEEE64 r)
void xddiv (IEEE64 d1, IEEE64 d2, IEEE64 r)
void xdrcp (IEEE64 d, IEEE64 r)
void xdabsv (IEEE64 d, IEEE64 r)
void xdsqrt (IEEE64 d, IEEE64 r)
void xdpow (IEEE64 d1, IEEE64 d2, IEEE64 r)
void xdsin (IEEE64 d, IEEE64 r)
void xdcos (IEEE64 d, IEEE64 r)
void xdtan (IEEE64 d, IEEE64 r)
void xdasin (IEEE64 d, IEEE64 r)
void xdacos (IEEE64 d, IEEE64 r)
void xdatan (IEEE64 d, IEEE64 r)
void xdatan2 (IEEE64 d1, IEEE64 d2, IEEE64 r)
void xdexp (IEEE64 d, IEEE64 r)
void xdlog (IEEE64 d, IEEE64 r)
void xdlog10 (IEEE64 d, IEEE64 r)
int xdcmp (IEEE64 d1, IEEE64 d2)
int xdisint (IEEE64 d, int *i)
static int parse_d (const char *s, IEEE64 d, int n, bool is_hex)
int atoxd (const char *s, IEEE64 d, int n)
int hxatoxd (const char *s, IEEE64 d, int n)
static void unwrap_q (float128_t *x, IEEE128 q)
static void wrap_q (IEEE128 res, float128_t *x)
void xqfix (IEEE128 q, INT *i)
void xqfixu (IEEE128 q, UINT *u)
void xqfix64 (IEEE128 q, DBLINT64 l)
void xqfixu64 (IEEE128 q, DBLUINT64 u)
void xqflt64 (DBLINT64 l, IEEE128 q)
void xqfloat (INT i, IEEE128 q)
void xqfloatu (UINT u, IEEE128 q)
void xqfltu64 (DBLUINT64 u, IEEE128 q)
void xftoq (IEEE32 f, IEEE128 q)
void xdtoq (IEEE64 d, IEEE128 q)
void xqtof (IEEE128 q, IEEE32 *r)
void xqtod (IEEE128 q, IEEE64 d)
void xqadd (IEEE128 q1, IEEE128 q2, IEEE128 r)
void xqsub (IEEE128 q1, IEEE128 q2, IEEE128 r)
void xqneg (IEEE128 q, IEEE128 r)
void xqmul (IEEE128 q1, IEEE128 q2, IEEE128 r)
void xqdiv (IEEE128 q1, IEEE128 q2, IEEE128 r)
void xqabsv (IEEE128 q, IEEE128 r)
void xqsqrt (IEEE128 q, IEEE128 r)
void xqpow (IEEE128 q1, IEEE128 q2, IEEE128 r)
void xqsin (IEEE128 q, IEEE128 r)
void xqcos (IEEE128 q, IEEE128 r)
void xqtan (IEEE128 q, IEEE128 r)
void xqasin (IEEE128 q, IEEE128 r)
void xqacos (IEEE128 q, IEEE128 r)
void xqatan (IEEE128 q, IEEE128 r)
void xqatan2 (IEEE128 q1, IEEE128 q2, IEEE128 r)
void xqexp (IEEE128 q, IEEE128 r)
void xqlog (IEEE128 q, IEEE128 r)
void xqlog10 (IEEE128 q, IEEE128 r)
int xqcmp (IEEE128 q1, IEEE128 q2)
static int parse_q (const char *s, IEEE128 q, int n, bool is_hex)
int atoxq (const char *s, IEEE128 q, int n)
int hxatoxq (const char *s, IEEE128 q, int n)
INT xudiv (UINT n, UINT d, UINT *r)
INT xumod (UINT n, UINT d, UINT *r)
INT xucmp (INT sa, INT sb)
static const char * get_int_literal (const char *s, int n, char *buffer, size_t buffer_length, bool *is_negative)
static int generic_atoxi (uint64_t *v, bool *is_negative, const char *s, int n, int base)
int atoxi (const char *s, INT *i, int n, int base)
int atoxi64 (const char *s, DBLINT64 i, int n, int base)
int atosi32 (const char *s, INT *i, int n, int base)
int atosi64 (const char *s, DBLINT64 i, int n, int base)
void cprintf (char *buffer, const char *format, INT *val)
void xcfpow (IEEE32 r1, IEEE32 i1, IEEE32 r2, IEEE32 i2, IEEE32 *rr, IEEE32 *ir)
void xcdpow (IEEE64 r1, IEEE64 i1, IEEE64 r2, IEEE64 i2, IEEE64 rr, IEEE64 ir)
void xcqpow (IEEE128 r1, IEEE128 i1, IEEE128 r2, IEEE128 i2, IEEE128 rr, IEEE128 ir)
Detailed Description
Implement legacy folding interfaces.
Implement the legacy compile-time evaluation library atop native host integer arithmetic, the floating-point folding package, and whatever 128-bit integer support has been supplied in int128.h.
These interfaces date back to the days when IEEE-754 floating-point arithmetic was a novelty and cross-compilation was a common practice. They were formerly implemented with an IEEE-754 arithmetic emulation software package that had been translated into C from its original PDP-11 assembly language. These interfaces have been cleaned up to some degree, though more work remains to be done. This particular implementation is new, and comprises mostly conversions between the operand and result types of these legacy interfaces and those of the underlying integer and floating-point folding packages.
Definition in file legacy-folding-api.c.
Function Documentation
add128()
void add128 (INT128 arg1, INT128 arg2, INT128 result)
Definition at line 427 of file legacy-folding-api.c.
References int128_unsigned_add(), result, unwrap_i128(), wrap_i128(), x, y, and z.
Referenced by choose_multiplier_64().
add64()
void add64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 161 of file legacy-folding-api.c.
References res, result, unwrap_l(), and wrap_l().
Referenced by addarth(), choose_multiplier(), const_fold(), init_fold_const(), lldbg_create_subrange_mdnode_pre11(), mk_swtab_ll(), red_kadd(), and ref_pd().
and64()
void and64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 315 of file legacy-folding-api.c.
References res, result, unwrap_l(), and wrap_l().
Referenced by addarth(), binop(), reciprocal_division_64(), and ref_intrin().
atosi32()
int atosi32 (const char * s, INT * i, int n, int base)
Definition at line 2372 of file legacy-folding-api.c.
References atoxi(), base, i, n, and s.
Referenced by get_number(), and get_prefixed_int().
atosi64()
int atosi64 (const char * s, DBLINT64 i, int n, int base)
Definition at line 2378 of file legacy-folding-api.c.
References atoxi64(), base, i, n, and s.
atoxd()
int atoxd (const char * s, IEEE64 d, int n)
Definition at line 1176 of file legacy-folding-api.c.
References d, n, parse_d(), and s.
Referenced by _huge(), add_fp_constants(), exp_mac(), get_number(), and ref_pd().
atoxf()
int atoxf (const char * s, IEEE32 * f, int n)
Definition at line 850 of file legacy-folding-api.c.
References f, n, parse_f(), and s.
Referenced by add_fp_constants(), exp_mac(), and get_number().
atoxi()
int atoxi (const char * s, INT * i, int n, int base)
Definition at line 2334 of file legacy-folding-api.c.
References base, generic_atoxi(), i, INT32_MAX, n, s, and UINT32_MAX.
Referenced by accpp(), atosi32(), exp_mac(), ff_get_label(), fpp(), get_kind_id(), get_nondec(), get_num(), get_prefixed_int(), get_stmt(), and tobinary().
atoxi64()
int atoxi64 (const char * s, DBLINT64 i, int n, int base)
Definition at line 2350 of file legacy-folding-api.c.
References base, generic_atoxi(), i, n, s, and wrap_l().
Referenced by atosi64(), exp_mac(), get_num(), get_number(), get_prefixed_int(), and tobinary64().
atoxq()
int atoxq (const char * s, IEEE128 q, int n)
Definition at line 2236 of file legacy-folding-api.c.
References n, parse_q(), q, and s.
Referenced by add_fp_constants(), and get_number().
check()
static void check (enum fold_status status) static
Definition at line 485 of file legacy-folding-api.c.
References FOLD_INEXACT, FOLD_INVALID, FOLD_OK, FOLD_OVERFLOW, FOLD_UNDERFLOW, FPE_FPOVF, FPE_FPUNF, FPE_INVOP, and fperror().
Referenced by _dumpilms(), _dumponeilm(), checkversion(), expdumpilms(), lower_check_stack(), xcdpow(), xcfpow(), xcqpow(), xdabsv(), xdacos(), xdadd(), xdasin(), xdatan(), xdatan2(), xdble(), xdcos(), xddiv(), xdexp(), xdfix(), xdfix64(), xdfixu(), xdfixu64(), xdfloat(), xdfloatu(), xdflt64(), xdfltu64(), xdisint(), xdlog(), xdlog10(), xdmul(), xdneg(), xdpow(), xdrcp(), xdsin(), xdsqrt(), xdsub(), xdtan(), xdtoq(), xfabsv(), xfacos(), xfadd(), xfasin(), xfatan(), xfatan2(), xfcos(), xfdiv(), xfexp(), xffloat(), xffloatu(), xfisint(), xfix(), xfix64(), xfixu(), xfixu64(), xflog(), xflog10(), xflt64(), xfltu64(), xfmul(), xfneg(), xfpow(), xfrcp(), xfsin(), xfsqrt(), xfsub(), xftan(), xftoq(), xqabsv(), xqacos(), xqadd(), xqasin(), xqatan(), xqatan2(), xqcos(), xqdiv(), xqexp(), xqfix(), xqfix64(), xqfixu(), xqfixu64(), xqfloat(), xqfloatu(), xqflt64(), xqfltu64(), xqlog(), xqlog10(), xqmul(), xqneg(), xqpow(), xqsin(), xqsqrt(), xqsub(), xqtan(), xqtod(), xqtof(), and xsngl().
cmp128()
int cmp128 (INT128 arg1, INT128 arg2)
Definition at line 447 of file legacy-folding-api.c.
References int128_signed_compare(), unwrap_i128(), x, and y.
Referenced by choose_multiplier_64(), and reciprocal_division_64().
cmp64()
int cmp64 (DBLINT64 arg1, DBLINT64 arg2)
Definition at line 143 of file legacy-folding-api.c.
References unwrap_l(), y, and z.
Referenced by addarth(), addbran(), binop(), choose_multiplier(), const_fold(), eval_abs(), extent_of_shape(), flowgraph(), init_fold_const(), mk_binop(), mk_swtab_ll(), negative_constant(), reciprocal_division(), reciprocal_division_64(), reduce_i8add(), ref_intrin(), and ref_pd().
cprintf()
void cprintf (char * buffer, const char * format, INT * val)
Definition at line 2388 of file legacy-folding-api.c.
References d, E, f, NULL, off, p, unwrap_d(), unwrap_f(), unwrap_q(), val, and x.
Referenced by gen_constant(), getprint(), prettytoken(), printname(), put_double(), put_float(), and write_constant_value().
div128()
void div128 (INT128 arg1, INT128 arg2, INT128 result)
Definition at line 468 of file legacy-folding-api.c.
References int128_signed_divide(), remainder, result, unwrap_i128(), wrap_i128(), x, and y.
Referenced by choose_multiplier_64().
div64()
void div64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 171 of file legacy-folding-api.c.
References num, res, result, unwrap_l(), and wrap_l().
Referenced by addarth(), choose_multiplier(), const_fold(), init_fold_const(), mod64(), and ref_intrin().
exp64()
void exp64 (DBLINT64 arg, INT exp, DBLINT64 result)
Definition at line 181 of file legacy-folding-api.c.
References arg, base, exp, result, unwrap_l(), wrap_l(), and x.
generic_atoxi()
static int generic_atoxi (uint64_t * v, bool * is_negative, const char * s, int n, int base) static
Definition at line 2316 of file legacy-folding-api.c.
References base, end, get_int_literal(), n, and s.
Referenced by atoxi(), and atoxi64().
get_int_literal()
static const char * get_int_literal (const char * s, int n, char * buffer, size_t buffer_length, bool * is_negative) static
Definition at line 2286 of file legacy-folding-api.c.
References n, NULL, and s.
Referenced by generic_atoxi().
get_literal()
static void get_literal (char * buffer, size_t length, const char * s, int n, bool is_hex) static
Definition at line 792 of file legacy-folding-api.c.
References assert, length(), n, p, and s.
Referenced by parse_d(), parse_f(), and parse_q().
handle_parsing_errors()
static int handle_parsing_errors (const char * buffer, const char * end, int errno_capture, bool iszero) static
Definition at line 822 of file legacy-folding-api.c.
References end, iszero, and strlen().
Referenced by parse_d(), parse_f(), and parse_q().
hxatoxd()
int hxatoxd (const char * s, IEEE64 d, int n)
Definition at line 1182 of file legacy-folding-api.c.
References d, n, parse_d(), and s.
hxatoxf()
int hxatoxf (const char * s, IEEE32 * f, int n)
Definition at line 856 of file legacy-folding-api.c.
References f, n, parse_f(), and s.
hxatoxq()
int hxatoxq (const char * s, IEEE128 q, int n)
Definition at line 2242 of file legacy-folding-api.c.
References n, parse_q(), q, and s.
is_host_little_endian()
static bool is_host_little_endian (void) static
Definition at line 43 of file legacy-folding-api.c.
References one.
Referenced by unwrap_d(), unwrap_q(), wrap_d(), and wrap_q().
mul128l()
void mul128l (INT128 arg1, INT128 arg2, INT128 result)
Definition at line 458 of file legacy-folding-api.c.
References int128_signed_multiply(), result, unwrap_i128(), wrap_i128(), x, and y.
Referenced by choose_multiplier_64().
mul64()
void mul64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 191 of file legacy-folding-api.c.
References res, result, unwrap_l(), and wrap_l().
Referenced by _xtok(), addarth(), choose_multiplier(), const_fold(), init_fold_const(), mod64(), and ref_intrin().
mul64_10()
void mul64_10 (DBLINT64 arg, DBLINT64 result)
Definition at line 201 of file legacy-folding-api.c.
References arg, i, result, unwrap_l(), and wrap_l().
neg64()
void neg64 (DBLINT64 arg, DBLINT64 result)
Definition at line 210 of file legacy-folding-api.c.
References arg, i, result, sign, unwrap_l(), and wrap_l().
Referenced by addarth(), eval_abs(), reciprocal_division_64(), red_kadd(), ref_intrin(), and ref_pd().
not64()
void not64 (DBLINT64 arg, DBLINT64 result)
Definition at line 325 of file legacy-folding-api.c.
References arg, i, result, unwrap_l(), and wrap_l().
Referenced by ref_intrin().
or64()
void or64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 334 of file legacy-folding-api.c.
References res, result, unwrap_l(), and wrap_l().
Referenced by binop(), and ref_intrin().
parse_d()
static int parse_d (const char * s, IEEE64 d, int n, bool is_hex) static
Definition at line 1162 of file legacy-folding-api.c.
References d, end, get_literal(), handle_parsing_errors(), n, s, strtod(), wrap_d(), and x.
Referenced by atoxd(), and hxatoxd().
parse_f()
static int parse_f (const char * s, IEEE32 * f, int n, bool is_hex) static
Definition at line 836 of file legacy-folding-api.c.
References end, f, get_literal(), handle_parsing_errors(), n, s, wrap_f(), and x.
Referenced by atoxf(), and hxatoxf().
parse_q()
static int parse_q (const char * s, IEEE128 q, int n, bool is_hex) static
Definition at line 2222 of file legacy-folding-api.c.
References end, get_literal(), handle_parsing_errors(), n, q, s, strtold(), wrap_q(), and x.
Referenced by atoxq(), and hxatoxq().
shf128()
void shf128 (INT128 arg, int count, INT128 result)
Definition at line 413 of file legacy-folding-api.c.
References arg, count, int128_shift_left(), int128_shift_right_logical(), res, result, unwrap_i128(), wrap_i128(), and x.
shf64()
void shf64 (DBLINT64 arg, int count, DBLINT64 result)
Definition at line 219 of file legacy-folding-api.c.
References arg, count, result, unwrap_l(), wrap_l(), and x.
sub128()
void sub128 (INT128 arg1, INT128 arg2, INT128 result)
Definition at line 437 of file legacy-folding-api.c.
References int128_signed_subtract(), result, unwrap_i128(), wrap_i128(), x, y, and z.
Referenced by choose_multiplier_64(), and reciprocal_division_64().
sub64()
void sub64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 233 of file legacy-folding-api.c.
References res, result, unwrap_l(), and wrap_l().
Referenced by addarth(), choose_multiplier(), const_fold(), init_fold_const(), lldbg_create_subrange_mdnode_pre11(), mk_swtab_ll(), mod64(), reciprocal_division(), and ref_intrin().
uadd64()
void uadd64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
Definition at line 243 of file legacy-folding-api.c.
References res, result, unwrap_u(), and wrap_u().
ucmp64()
int ucmp64 (DBLUINT64 arg1, DBLUINT64 arg2)
Definition at line 152 of file legacy-folding-api.c.
References unwrap_u(), y, and z.
Referenced by addarth(), addbran(), and lg64().
udiv64()
void udiv64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
Definition at line 286 of file legacy-folding-api.c.
References num, res, result, unwrap_u(), and wrap_u().
Referenced by addarth(), and umod64().
ui64toax()
void ui64toax (DBLINT64 from, char * to, int size, int is_unsigned, int radix)
Definition at line 354 of file legacy-folding-api.c.
References assert, size, unwrap_l(), and x.
Referenced by gen_constant(), getprint(), printname(), put_int8(), and write_constant_value().
umul64()
void umul64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
Definition at line 296 of file legacy-folding-api.c.
References res, result, unwrap_u(), and wrap_u().
Referenced by addarth(), and umod64().
umul64_10()
void umul64_10 (DBLUINT64 arg, DBLUINT64 result)
Definition at line 306 of file legacy-folding-api.c.
References arg, result, unwrap_u(), and wrap_u().
uneg64()
void uneg64 (DBLUINT64 arg, DBLUINT64 result)
Definition at line 253 of file legacy-folding-api.c.
References arg, result, sign, unwrap_u(), and wrap_u().
unwrap_d()
static void unwrap_d (float64_t * x, const IEEE64 d) static
Definition at line 97 of file legacy-folding-api.c.
References d, u::i, i, is_host_little_endian(), and x.
Referenced by cprintf(), xcdpow(), xdabsv(), xdacos(), xdadd(), xdasin(), xdatan(), xdatan2(), xdcmp(), xdcos(), xddiv(), xdexp(), xdfix(), xdfix64(), xdfixu(), xdfixu64(), xdisint(), xdlog(), xdlog10(), xdmul(), xdneg(), xdpow(), xdrcp(), xdsin(), xdsqrt(), xdsub(), xdtan(), xdtomd(), xdtoq(), and xsngl().
unwrap_f()
static void unwrap_f (float32_t * f, IEEE32 * x) static
Definition at line 85 of file legacy-folding-api.c.
References f, and x.
Referenced by cprintf(), xcfpow(), xdble(), xfabsv(), xfacos(), xfadd(), xfasin(), xfatan(), xfatan2(), xfcmp(), xfcos(), xfdiv(), xfexp(), xfisint(), xfix(), xfix64(), xfixu(), xfixu64(), xflog(), xflog10(), xfmul(), xfneg(), xfpow(), xfrcp(), xfsin(), xfsqrt(), xfsub(), xftan(), and xftoq().
unwrap_i128()
static void unwrap_i128 (int128_t * result, const INT128 i) static
Definition at line 387 of file legacy-folding-api.c.
References i, int128_from_int64(), int128_from_uint64(), int128_or(), int128_shift_left(), j, and result.
Referenced by add128(), cmp128(), div128(), mul128l(), shf128(), and sub128().
unwrap_l()
static void unwrap_l (int64_t * x, const DBLINT64 y) static
Definition at line 59 of file legacy-folding-api.c.
References x, and y.
Referenced by add64(), and64(), cmp64(), div64(), exp64(), mul64(), mul64_10(), neg64(), not64(), or64(), shf64(), sub64(), ui64toax(), xdflt64(), xflt64(), xor64(), and xqflt64().
unwrap_q()
static void unwrap_q (float128_t * x, IEEE128 q) static
Definition at line 1878 of file legacy-folding-api.c.
References u::i, i, is_host_little_endian(), q, and x.
Referenced by cprintf(), xcqpow(), xqabsv(), xqacos(), xqadd(), xqasin(), xqatan(), xqatan2(), xqcmp(), xqcos(), xqdiv(), xqexp(), xqfix(), xqfix64(), xqfixu(), xqfixu64(), xqlog(), xqlog10(), xqmul(), xqneg(), xqpow(), xqsin(), xqsqrt(), xqsub(), xqtan(), xqtod(), and xqtof().
unwrap_u()
static void unwrap_u (uint64_t * x, const DBLUINT64 y) static
Definition at line 65 of file legacy-folding-api.c.
References x, and y.
Referenced by uadd64(), ucmp64(), udiv64(), umul64(), umul64_10(), uneg64(), ushf64(), usub64(), xdfltu64(), xfltu64(), and xqfltu64().
ushf64()
void ushf64 (DBLUINT64 arg, int count, DBLUINT64 result)
Definition at line 262 of file legacy-folding-api.c.
References arg, count, result, unwrap_u(), and wrap_u().
usub64()
void usub64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
Definition at line 276 of file legacy-folding-api.c.
References res, result, unwrap_u(), and wrap_u().
Referenced by umod64().
wrap_d()
static void wrap_d (IEEE64 res, const float64_t * x) static
Definition at line 110 of file legacy-folding-api.c.
References u::d, d, u::i, i, is_host_little_endian(), res, and x.
Referenced by parse_d(), xcdpow(), xdabsv(), xdacos(), xdadd(), xdasin(), xdatan(), xdatan2(), xdble(), xdcos(), xddiv(), xdexp(), xdfloat(), xdfloatu(), xdflt64(), xdfltu64(), xdlog(), xdlog10(), xdmul(), xdneg(), xdpow(), xdrcp(), xdsin(), xdsqrt(), xdsub(), xdtan(), xmdtod(), and xqtod().
wrap_f()
static void wrap_f (IEEE32 * f, float32_t * x) static
Definition at line 91 of file legacy-folding-api.c.
References f, and x.
Referenced by parse_f(), xcfpow(), xfabsv(), xfacos(), xfadd(), xfasin(), xfatan(), xfatan2(), xfcos(), xfdiv(), xfexp(), xffloat(), xffloatu(), xflog(), xflog10(), xflt64(), xfltu64(), xfmul(), xfneg(), xfpow(), xfrcp(), xfsin(), xfsqrt(), xfsub(), xftan(), xqtof(), and xsngl().
wrap_i128()
static void wrap_i128 (INT128 i, const int128_t * x) static
Definition at line 400 of file legacy-folding-api.c.
References i, int128_shift_right_logical(), int128_to_int64(), j, t, and x.
Referenced by add128(), div128(), mul128l(), shf128(), and sub128().
wrap_l()
static void wrap_l (DBLINT64 res, int64_t * x) static
Definition at line 71 of file legacy-folding-api.c.
References res, and x.
Referenced by add64(), and64(), atoxi64(), div64(), exp64(), mul64(), mul64_10(), neg64(), not64(), or64(), shf64(), sub64(), xdfix64(), xfix64(), xor64(), and xqfix64().
wrap_q()
static void wrap_q (IEEE128 res, float128_t * x) static
Definition at line 1893 of file legacy-folding-api.c.
References u::i, i, is_host_little_endian(), q, res, and x.
Referenced by parse_q(), xcqpow(), xdtoq(), xftoq(), xqabsv(), xqacos(), xqadd(), xqasin(), xqatan(), xqatan2(), xqcos(), xqdiv(), xqexp(), xqfloat(), xqfloatu(), xqflt64(), xqfltu64(), xqlog(), xqlog10(), xqmul(), xqneg(), xqpow(), xqsin(), xqsqrt(), xqsub(), and xqtan().
wrap_u()
static void wrap_u (DBLUINT64 res, uint64_t * x) static
Definition at line 78 of file legacy-folding-api.c.
References res, and x.
Referenced by uadd64(), udiv64(), umul64(), umul64_10(), uneg64(), ushf64(), usub64(), xdfixu64(), xfixu64(), and xqfixu64().
xcdpow()
void xcdpow (IEEE64 r1, IEEE64 i1, IEEE64 r2, IEEE64 i2, IEEE64 rr, IEEE64 ir)
Definition at line 2460 of file legacy-folding-api.c.
References check(), cimag, creal, DOUBLE_COMPLEX_CREATE, DOUBLE_COMPLEX_TYPE, fold_complex64_pow(), iy, unwrap_d(), wrap_d(), x, y, and z.
Referenced by const_fold(), and init_fold_const().
xcfpow()
void xcfpow (IEEE32 r1, IEEE32 i1, IEEE32 r2, IEEE32 i2, IEEE32 * rr, IEEE32 * ir)
Definition at line 2437 of file legacy-folding-api.c.
References check(), cimagf, crealf, FLOAT_COMPLEX_CREATE, FLOAT_COMPLEX_TYPE, fold_complex32_pow(), iy, unwrap_f(), wrap_f(), x, y, and z.
Referenced by const_fold(), and init_fold_const().
xcqpow()
void xcqpow (IEEE128 r1, IEEE128 i1, IEEE128 r2, IEEE128 i2, IEEE128 rr, IEEE128 ir)
Definition at line 2483 of file legacy-folding-api.c.
References check(), fold_complex128_pow(), iy, LONG_DOUBLE_COMPLEX_CREATE, LONG_DOUBLE_COMPLEX_TYPE, unwrap_q(), wrap_q(), x, y, and z.
Referenced by const_fold(), and init_fold_const().
xdabsv()
void xdabsv (IEEE64 d, IEEE64 r)
Definition at line 1022 of file legacy-folding-api.c.
References check(), d, fold_real64_abs(), r, unwrap_d(), wrap_d(), x, and y.
Referenced by addarth(), eval_abs(), and ref_intrin().
xdacos()
void xdacos (IEEE64 d, IEEE64 r)
Definition at line 1086 of file legacy-folding-api.c.
References check(), d, fold_real64_acos(), r, unwrap_d(), wrap_d(), x, and y.
xdadd()
void xdadd (IEEE64 d1, IEEE64 d2, IEEE64 r)
Definition at line 962 of file legacy-folding-api.c.
References check(), fold_real64_add(), r, unwrap_d(), wrap_d(), x, y, and z.
Referenced by _xtok(), addarth(), const_fold(), and init_fold_const().
xdasin()
void xdasin (IEEE64 d, IEEE64 r)
Definition at line 1077 of file legacy-folding-api.c.
References check(), d, fold_real64_asin(), r, unwrap_d(), wrap_d(), x, and y.
xdatan()
void xdatan (IEEE64 d, IEEE64 r)
Definition at line 1095 of file legacy-folding-api.c.
References check(), d, fold_real64_atan(), r, unwrap_d(), wrap_d(), x, and y.
Referenced by addarth().
xdatan2()
void xdatan2 (IEEE64 d1, IEEE64 d2, IEEE64 r)
Definition at line 1104 of file legacy-folding-api.c.
References check(), fold_real64_atan2(), r, unwrap_d(), wrap_d(), x, y, and z.
xdble()
void xdble (IEEE32 f, IEEE64 r)
Definition at line 942 of file legacy-folding-api.c.
References check(), f, fold_real64_from_real32(), r, unwrap_f(), wrap_d(), x, and y.
Referenced by addarth(), check_ccon(), cngcon(), convert_cnst(), gen_constant(), ref_intrin(), and write_constant_value().
xdcmp()
int xdcmp (IEEE64 d1, IEEE64 d2)
Definition at line 1141 of file legacy-folding-api.c.
References fold_real64_compare(), unwrap_d(), y, and z.
Referenced by addarth(), const_fold(), init_fold_const(), negative_constant(), and ref_intrin().
xdcos()
void xdcos (IEEE64 d, IEEE64 r)
Definition at line 1059 of file legacy-folding-api.c.
References check(), d, fold_real64_cos(), r, unwrap_d(), wrap_d(), x, and y.
xddiv()
void xddiv (IEEE64 d1, IEEE64 d2, IEEE64 r)
Definition at line 1001 of file legacy-folding-api.c.
References check(), fold_real64_divide(), r, unwrap_d(), wrap_d(), x, y, and z.
Referenced by _ddiv(), addarth(), and eval_mod().
xdexp()
void xdexp (IEEE64 d, IEEE64 r)
Definition at line 1114 of file legacy-folding-api.c.
References check(), d, fold_real64_exp(), r, unwrap_d(), wrap_d(), x, and y.
xdfix()
void xdfix (IEEE64 d, INT * i)
Definition at line 866 of file legacy-folding-api.c.
References check(), d, fold_int32_from_real64(), i, unwrap_d(), and x.
Referenced by addarth(), cngcon(), and convert_cnst().
xdfix64()
void xdfix64 (IEEE64 d, DBLINT64 l)
Definition at line 882 of file legacy-folding-api.c.
References check(), d, fold_int64_from_real64(), unwrap_d(), wrap_l(), x, and y.
Referenced by addarth(), cngcon(), and convert_cnst().
xdfixu()
void xdfixu (IEEE64 d, UINT * u)
Definition at line 874 of file legacy-folding-api.c.
References check(), d, fold_uint32_from_real64(), unwrap_d(), and x.
Referenced by addarth().
xdfixu64()
void xdfixu64 (IEEE64 d, DBLUINT64 u)
Definition at line 892 of file legacy-folding-api.c.
References check(), d, fold_int64_from_real64(), unwrap_d(), wrap_u(), x, and y.
xdfloat()
void xdfloat (INT i, IEEE64 d)
Definition at line 904 of file legacy-folding-api.c.
References check(), d, fold_real64_from_int64(), i, wrap_d(), and x.
Referenced by addarth(), cngcon(), and convert_cnst().
xdfloatu()
void xdfloatu (UINT u, IEEE64 d)
Definition at line 913 of file legacy-folding-api.c.
References check(), d, fold_real64_from_int64(), wrap_d(), and x.
Referenced by addarth().
xdflt64()
void xdflt64 (DBLINT64 l, IEEE64 d)
Definition at line 922 of file legacy-folding-api.c.
References check(), d, fold_real64_from_int64(), unwrap_l(), wrap_d(), x, and y.
Referenced by addarth(), cngcon(), and convert_cnst().
xdfltu64()
void xdfltu64 (DBLUINT64 u, IEEE64 d)
Definition at line 932 of file legacy-folding-api.c.
References check(), d, fold_real64_from_uint64(), unwrap_u(), wrap_d(), x, and y.
Referenced by addarth().
xdisint()
int xdisint (IEEE64 d, int * i)
Definition at line 1150 of file legacy-folding-api.c.
References check(), d, FOLD_EQ, fold_int32_from_real64(), fold_real64_compare(), fold_real64_from_int64(), i, k, unwrap_d(), x, and y.
Referenced by addarth(), and chkopnds().
xdlog()
void xdlog (IEEE64 d, IEEE64 r)
Definition at line 1123 of file legacy-folding-api.c.
References check(), d, fold_real64_log(), r, unwrap_d(), wrap_d(), x, and y.
xdlog10()
void xdlog10 (IEEE64 d, IEEE64 r)
Definition at line 1132 of file legacy-folding-api.c.
References check(), d, fold_real64_log10(), r, unwrap_d(), wrap_d(), x, and y.
xdmul()
void xdmul (IEEE64 d1, IEEE64 d2, IEEE64 r)
Definition at line 991 of file legacy-folding-api.c.
References check(), fold_real64_multiply(), r, unwrap_d(), wrap_d(), x, y, and z.
Referenced by _ddiv(), _xtok(), addarth(), const_fold(), eval_mod(), eval_scale(), init_fold_const(), and ref_intrin().
xdneg()
void xdneg (IEEE64 d, IEEE64 r)
Definition at line 982 of file legacy-folding-api.c.
References check(), d, fold_real64_negate(), r, unwrap_d(), wrap_d(), x, and y.
Referenced by add_fp_constants(), addarth(), init_negate_const(), negate_const(), negate_const_be(), ref_intrin(), and sym_init().
xdpow()
void xdpow (IEEE64 d1, IEEE64 d2, IEEE64 r)
Definition at line 1040 of file legacy-folding-api.c.
References check(), fold_real64_pow(), r, unwrap_d(), wrap_d(), x, y, and z.
Referenced by const_fold(), and init_fold_const().
xdrcp()
void xdrcp (IEEE64 d, IEEE64 r)
Definition at line 1011 of file legacy-folding-api.c.
References check(), d, fold_real64_divide(), fold_real64_from_int64(), one, r, unwrap_d(), wrap_d(), x, and y.
Referenced by _ddiv().
xdsin()
void xdsin (IEEE64 d, IEEE64 r)
Definition at line 1050 of file legacy-folding-api.c.
References check(), d, fold_real64_sin(), r, unwrap_d(), wrap_d(), x, and y.
xdsqrt()
void xdsqrt (IEEE64 d, IEEE64 r)
Definition at line 1031 of file legacy-folding-api.c.
References check(), d, fold_real64_sqrt(), r, unwrap_d(), wrap_d(), x, and y.
Referenced by addarth(), and eval_sqrt().
xdsub()
void xdsub (IEEE64 d1, IEEE64 d2, IEEE64 r)
Definition at line 972 of file legacy-folding-api.c.
References check(), fold_real64_subtract(), r, unwrap_d(), wrap_d(), x, y, and z.
Referenced by _xtok(), addarth(), const_fold(), eval_mod(), and init_fold_const().
xdtan()
void xdtan (IEEE64 d, IEEE64 r)
Definition at line 1068 of file legacy-folding-api.c.
References check(), d, fold_real64_tan(), r, unwrap_d(), wrap_d(), x, and y.
xdtomd()
void xdtomd (IEEE64 d, double * md)
Definition at line 127 of file legacy-folding-api.c.
References d, and unwrap_d().
Referenced by gen_constant(), and write_constant_value().
xdtoq()
void xdtoq (IEEE64 d, IEEE128 q)
Definition at line 1992 of file legacy-folding-api.c.
References check(), d, fold_real128_from_real64(), q, unwrap_d(), wrap_q(), x, and y.
Referenced by check_ccon(), cngcon(), and convert_cnst().
xfabsv()
void xfabsv (IEEE32 f, IEEE32 * r)
Definition at line 646 of file legacy-folding-api.c.
References check(), f, fold_real32_abs(), r, unwrap_f(), wrap_f(), x, and y.
Referenced by addarth(), eval_abs(), and ref_intrin().
xfacos()
void xfacos (IEEE32 f, IEEE32 * r)
Definition at line 710 of file legacy-folding-api.c.
References check(), f, fold_real32_acos(), r, unwrap_f(), wrap_f(), x, and y.
xfadd()
void xfadd (IEEE32 f1, IEEE32 f2, IEEE32 * r)
Definition at line 586 of file legacy-folding-api.c.
References check(), f2, fold_real32_add(), r, unwrap_f(), wrap_f(), x, y, and z.
Referenced by _xtok(), addarth(), const_fold(), eval_abs(), eval_nint(), init_fold_const(), ref_intrin(), and ref_pd().
xfasin()
void xfasin (IEEE32 f, IEEE32 * r)
Definition at line 701 of file legacy-folding-api.c.
References check(), f, fold_real32_asin(), r, unwrap_f(), wrap_f(), x, and y.
xfatan()
void xfatan (IEEE32 f, IEEE32 * r)
Definition at line 719 of file legacy-folding-api.c.
References check(), f, fold_real32_atan(), r, unwrap_f(), wrap_f(), x, and y.
Referenced by addarth().
xfatan2()
void xfatan2 (IEEE32 f1, IEEE32 f2, IEEE32 * r)
Definition at line 728 of file legacy-folding-api.c.
References check(), f2, fold_real32_atan2(), r, unwrap_f(), wrap_f(), x, y, and z.
xfcmp()
int xfcmp (IEEE32 f1, IEEE32 f2)
Definition at line 765 of file legacy-folding-api.c.
References f2, fold_real32_compare(), unwrap_f(), y, and z.
Referenced by addarth(), cmp_acl(), const_fold(), eval_ceiling(), eval_floor(), eval_max(), eval_min(), eval_nint(), init_fold_const(), negative_constant(), ref_intrin(), and ref_pd().
xfcos()
void xfcos (IEEE32 f, IEEE32 * r)
Definition at line 683 of file legacy-folding-api.c.
References check(), f, fold_real32_cos(), r, unwrap_f(), wrap_f(), x, and y.
xfdiv()
void xfdiv (IEEE32 f1, IEEE32 f2, IEEE32 * r)
Definition at line 625 of file legacy-folding-api.c.
References check(), f2, fold_real32_divide(), r, unwrap_f(), wrap_f(), x, y, and z.
Referenced by _fdiv(), addarth(), and eval_mod().
xfexp()
void xfexp (IEEE32 f, IEEE32 * r)
Definition at line 738 of file legacy-folding-api.c.
References check(), f, fold_real32_exp(), r, unwrap_f(), wrap_f(), x, and y.
xffixu()
void xffixu (IEEE32 f, UINT * u)
Definition at line 520 of file legacy-folding-api.c.
References f, and xfixu().
xffloat()
void xffloat (INT i, IEEE32 * f)
Definition at line 548 of file legacy-folding-api.c.
References check(), f, fold_real32_from_int64(), i, wrap_f(), and x.
Referenced by addarth(), cngcon(), and convert_cnst().
xffloatu()
void xffloatu (UINT u, IEEE32 * f)
Definition at line 557 of file legacy-folding-api.c.
References check(), f, fold_real32_from_int64(), wrap_f(), and x.
Referenced by addarth().
xfisint()
int xfisint (IEEE32 f, int * i)
Definition at line 774 of file legacy-folding-api.c.
References check(), f, FOLD_EQ, fold_int32_from_real32(), fold_real32_compare(), fold_real32_from_int64(), i, k, unwrap_f(), x, and y.
Referenced by addarth(), and chkopnds().
xfix()
void xfix (IEEE32 f, INT * i)
Definition at line 504 of file legacy-folding-api.c.
References check(), f, fold_int32_from_real32(), i, unwrap_f(), and x.
Referenced by addarth(), cngcon(), and convert_cnst().
xfix64()
void xfix64 (IEEE32 f, DBLINT64 l)
Definition at line 526 of file legacy-folding-api.c.
References check(), f, fold_int64_from_real32(), unwrap_f(), wrap_l(), x, and y.
Referenced by addarth(), cngcon(), and convert_cnst().
xfixu()
void xfixu (IEEE32 f, UINT * u)
Definition at line 512 of file legacy-folding-api.c.
References check(), f, fold_uint32_from_real32(), unwrap_f(), and x.
Referenced by addarth(), and xffixu().
xfixu64()
void xfixu64 (IEEE32 f, DBLUINT64 u)
Definition at line 536 of file legacy-folding-api.c.
References check(), f, fold_int64_from_real32(), unwrap_f(), wrap_u(), x, and y.
xflog()
void xflog (IEEE32 f, IEEE32 * r)
Definition at line 747 of file legacy-folding-api.c.
References check(), f, fold_real32_log(), r, unwrap_f(), wrap_f(), x, and y.
xflog10()
void xflog10 (IEEE32 f, IEEE32 * r)
Definition at line 756 of file legacy-folding-api.c.
References check(), f, fold_real32_log10(), r, unwrap_f(), wrap_f(), x, and y.
xflt64()
void xflt64 (DBLINT64 l, IEEE32 * f)
Definition at line 566 of file legacy-folding-api.c.
References check(), f, fold_real32_from_int64(), unwrap_l(), wrap_f(), x, and y.
Referenced by addarth(), cngcon(), and convert_cnst().
xfltu64()
void xfltu64 (DBLUINT64 u, IEEE32 * f)
Definition at line 576 of file legacy-folding-api.c.
References check(), f, fold_real32_from_uint64(), unwrap_u(), wrap_f(), x, and y.
Referenced by addarth().
xfmul()
void xfmul (IEEE32 f1, IEEE32 f2, IEEE32 * r)
Definition at line 615 of file legacy-folding-api.c.
References check(), f2, fold_real32_multiply(), r, unwrap_f(), wrap_f(), x, y, and z.
Referenced by _fdiv(), _xtok(), addarth(), const_fold(), eval_abs(), eval_mod(), eval_scale(), and init_fold_const().
xfneg()
void xfneg (IEEE32 f, IEEE32 * r)
Definition at line 606 of file legacy-folding-api.c.
References check(), f, fold_real32_negate(), r, unwrap_f(), wrap_f(), x, and y.
Referenced by add_fp_constants(), addarth(), init_negate_const(), negate_const(), negate_const_be(), ref_intrin(), and sym_init().
xfpow()
void xfpow (IEEE32 f1, IEEE32 f2, IEEE32 * r)
Definition at line 664 of file legacy-folding-api.c.
References check(), f2, fold_real32_pow(), r, unwrap_f(), wrap_f(), x, y, and z.
Referenced by const_fold(), and init_fold_const().
xfrcp()
void xfrcp (IEEE32 f, IEEE32 * r)
Definition at line 635 of file legacy-folding-api.c.
References check(), f, fold_real32_divide(), fold_real32_from_int64(), one, r, unwrap_f(), wrap_f(), x, and y.
Referenced by _fdiv().
xfsin()
void xfsin (IEEE32 f, IEEE32 * r)
Definition at line 674 of file legacy-folding-api.c.
References check(), f, fold_real32_sin(), r, unwrap_f(), wrap_f(), x, and y.
xfsqrt()
void xfsqrt (IEEE32 f, IEEE32 * r)
Definition at line 655 of file legacy-folding-api.c.
References check(), f, fold_real32_sqrt(), r, unwrap_f(), wrap_f(), x, and y.
Referenced by addarth(), eval_abs(), and eval_sqrt().
xfsub()
void xfsub (IEEE32 f1, IEEE32 f2, IEEE32 * r)
Definition at line 596 of file legacy-folding-api.c.
References check(), f2, fold_real32_subtract(), r, unwrap_f(), wrap_f(), x, y, and z.
Referenced by _xtok(), addarth(), const_fold(), eval_mod(), eval_nint(), init_fold_const(), ref_intrin(), and ref_pd().
xftan()
void xftan (IEEE32 f, IEEE32 * r)
Definition at line 692 of file legacy-folding-api.c.
References check(), f, fold_real32_tan(), r, unwrap_f(), wrap_f(), x, and y.
xftoq()
void xftoq (IEEE32 f, IEEE128 q)
Definition at line 1982 of file legacy-folding-api.c.
References check(), f, fold_real128_from_real32(), q, unwrap_f(), wrap_q(), x, and y.
Referenced by check_ccon(), cngcon(), and convert_cnst().
xmdtod()
void xmdtod (double md, IEEE64 d)
Definition at line 133 of file legacy-folding-api.c.
References d, and wrap_d().
Referenced by gen_abs_expr(), and gen_llvm_expr().
xor64()
void xor64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 344 of file legacy-folding-api.c.
References res, result, unwrap_l(), and wrap_l().
Referenced by binop(), ref_intrin(), and ref_pd().
xqabsv()
void xqabsv (IEEE128 q, IEEE128 r)
Definition at line 2071 of file legacy-folding-api.c.
References check(), fold_real128_abs(), q, r, unwrap_q(), wrap_q(), x, and y.
Referenced by addarth(), eval_abs(), and ref_intrin().
xqacos()
void xqacos (IEEE128 q, IEEE128 r)
Definition at line 2135 of file legacy-folding-api.c.
References check(), fold_real128_acos(), q, r, unwrap_q(), wrap_q(), x, and y.
xqadd()
void xqadd (IEEE128 q1, IEEE128 q2, IEEE128 r)
Definition at line 2022 of file legacy-folding-api.c.
References check(), fold_real128_add(), r, unwrap_q(), wrap_q(), x, y, and z.
Referenced by _xtok(), addarth(), const_fold(), and init_fold_const().
xqasin()
void xqasin (IEEE128 q, IEEE128 r)
Definition at line 2126 of file legacy-folding-api.c.
References check(), fold_real128_asin(), q, r, unwrap_q(), wrap_q(), x, and y.
xqatan()
void xqatan (IEEE128 q, IEEE128 r)
Definition at line 2144 of file legacy-folding-api.c.
References check(), fold_real128_atan(), q, r, unwrap_q(), wrap_q(), x, and y.
Referenced by addarth().
xqatan2()
void xqatan2 (IEEE128 q1, IEEE128 q2, IEEE128 r)
Definition at line 2153 of file legacy-folding-api.c.
References check(), fold_real128_atan2(), r, unwrap_q(), wrap_q(), x, y, and z.
Referenced by addarth().
xqcmp()
int xqcmp (IEEE128 q1, IEEE128 q2)
Definition at line 2190 of file legacy-folding-api.c.
References fold_real128_compare(), unwrap_q(), y, and z.
Referenced by const_fold(), and init_fold_const().
xqcos()
void xqcos (IEEE128 q, IEEE128 r)
Definition at line 2108 of file legacy-folding-api.c.
References check(), fold_real128_cos(), q, r, unwrap_q(), wrap_q(), x, and y.
xqdiv()
void xqdiv (IEEE128 q1, IEEE128 q2, IEEE128 r)
Definition at line 2061 of file legacy-folding-api.c.
References check(), fold_real128_divide(), r, unwrap_q(), wrap_q(), x, y, and z.
Referenced by const_fold(), eval_mod(), and init_fold_const().
xqexp()
void xqexp (IEEE128 q, IEEE128 r)
Definition at line 2163 of file legacy-folding-api.c.
References check(), fold_real128_exp(), q, r, unwrap_q(), wrap_q(), x, and y.
xqfix()
void xqfix (IEEE128 q, INT * i)
Definition at line 1908 of file legacy-folding-api.c.
References check(), fold_int32_from_real128(), i, q, unwrap_q(), and y.
Referenced by cngcon(), and convert_cnst().
xqfix64()
void xqfix64 (IEEE128 q, DBLINT64 l)
Definition at line 1924 of file legacy-folding-api.c.
References check(), fold_int64_from_real128(), q, unwrap_q(), wrap_l(), x, and y.
Referenced by cngcon(), and convert_cnst().
xqfixu()
void xqfixu (IEEE128 q, UINT * u)
Definition at line 1916 of file legacy-folding-api.c.
References check(), fold_uint32_from_real128(), q, unwrap_q(), and y.
xqfixu64()
void xqfixu64 (IEEE128 q, DBLUINT64 u)
Definition at line 1934 of file legacy-folding-api.c.
References check(), fold_uint64_from_real128(), q, unwrap_q(), wrap_u(), x, and y.
xqfloat()
void xqfloat (INT i, IEEE128 q)
Definition at line 1954 of file legacy-folding-api.c.
References check(), fold_real128_from_int64(), i, q, wrap_q(), and x.
Referenced by cngcon(), and convert_cnst().
xqfloatu()
void xqfloatu (UINT u, IEEE128 q)
Definition at line 1963 of file legacy-folding-api.c.
References check(), fold_real128_from_int64(), q, wrap_q(), and x.
xqflt64()
void xqflt64 (DBLINT64 l, IEEE128 q)
Definition at line 1944 of file legacy-folding-api.c.
References check(), fold_real128_from_int64(), q, unwrap_l(), wrap_q(), x, and y.
Referenced by cngcon(), and convert_cnst().
xqfltu64()
void xqfltu64 (DBLUINT64 u, IEEE128 q)
Definition at line 1972 of file legacy-folding-api.c.
References check(), fold_real128_from_uint64(), q, unwrap_u(), wrap_q(), x, and y.
xqlog()
void xqlog (IEEE128 q, IEEE128 r)
Definition at line 2172 of file legacy-folding-api.c.
References check(), fold_real128_log(), q, r, unwrap_q(), wrap_q(), x, and y.
xqlog10()
void xqlog10 (IEEE128 q, IEEE128 r)
Definition at line 2181 of file legacy-folding-api.c.
References check(), fold_real128_log10(), q, r, unwrap_q(), wrap_q(), x, and y.
xqmul()
void xqmul (IEEE128 q1, IEEE128 q2, IEEE128 r)
Definition at line 2051 of file legacy-folding-api.c.
References check(), fold_real128_multiply(), r, unwrap_q(), wrap_q(), x, y, and z.
Referenced by _xtok(), const_fold(), eval_mod(), eval_scale(), and init_fold_const().
xqneg()
void xqneg (IEEE128 q, IEEE128 r)
Definition at line 2042 of file legacy-folding-api.c.
References check(), fold_real128_negate(), q, r, unwrap_q(), wrap_q(), x, and y.
Referenced by add_fp_constants(), addarth(), init_negate_const(), negate_const(), and negate_const_be().
xqpow()
void xqpow (IEEE128 q1, IEEE128 q2, IEEE128 r)
Definition at line 2089 of file legacy-folding-api.c.
References check(), fold_real128_pow(), r, unwrap_q(), wrap_q(), x, y, and z.
Referenced by const_fold(), and init_fold_const().
xqsin()
void xqsin (IEEE128 q, IEEE128 r)
Definition at line 2099 of file legacy-folding-api.c.
References check(), fold_real128_sin(), q, r, unwrap_q(), wrap_q(), x, and y.
xqsqrt()
void xqsqrt (IEEE128 q, IEEE128 r)
Definition at line 2080 of file legacy-folding-api.c.
References check(), fold_real128_sqrt(), q, r, unwrap_q(), wrap_q(), x, and y.
Referenced by addarth(), and eval_sqrt().
xqsub()
void xqsub (IEEE128 q1, IEEE128 q2, IEEE128 r)
Definition at line 2032 of file legacy-folding-api.c.
References check(), fold_real128_subtract(), r, unwrap_q(), wrap_q(), x, y, and z.
Referenced by _xtok(), addarth(), const_fold(), eval_mod(), and init_fold_const().
xqtan()
void xqtan (IEEE128 q, IEEE128 r)
Definition at line 2117 of file legacy-folding-api.c.
References check(), fold_real128_tan(), q, r, unwrap_q(), wrap_q(), x, and y.
xqtod()
void xqtod (IEEE128 q, IEEE64 d)
Definition at line 2012 of file legacy-folding-api.c.
References check(), d, fold_real64_from_real128(), q, unwrap_q(), wrap_d(), x, and y.
Referenced by cngcon(), and convert_cnst().
xqtof()
void xqtof (IEEE128 q, IEEE32 * r)
Definition at line 2002 of file legacy-folding-api.c.
References check(), fold_real32_from_real128(), q, r, unwrap_q(), wrap_f(), x, and y.
Referenced by cngcon(), and convert_cnst().
xsngl()
void xsngl (IEEE64 d, IEEE32 * r)
Definition at line 952 of file legacy-folding-api.c.
References check(), d, fold_real32_from_real64(), r, unwrap_d(), wrap_f(), x, and y.
Referenced by addarth(), cngcon(), and convert_cnst().
xucmp()
INT xucmp (INT sa, INT sb)
Definition at line 2271 of file legacy-folding-api.c.
References a, b, sa, and sb.
Referenced by addarth(), addbran(), and const_fold().
xudiv()
INT xudiv (UINT n, UINT d, UINT * r)
Definition at line 2252 of file legacy-folding-api.c.
References d, n, and r.
Referenced by addarth().
xumod()
INT xumod (UINT n, UINT d, UINT * r)
Definition at line 2261 of file legacy-folding-api.c.
References d, n, and r.
Referenced by addarth().