flang: legacy-util-api.h File Reference
legacy-util-api.h File Reference
Legacy utility interfaces.
#include <ctype.h>
#include <limits.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
Macros
#define DIRSEP ':'
#define DIRWORK ""
#define DIRSINCS "/usr/include"
#define UNKFILE "" /* No extension. */
#define LISTFILE ".lst" /* Listing file. */
#define OBJFILE ".o" /* Object module file. */
#define IMGFILE ".out" /* Image module file. */
#define SYMFILE ".dbg" /* Symbol file. */
#define OVDFILE ".ovd" /* Overlay description file. */
#define OBJLFILE ".a" /* Object library file. */
#define IMGLFILE ".ilb" /* Image library file. */
#define MAPFILE ".map" /* Map file from linker. */
#define CFILE ".c" /* C source */
#define IFILE ".i" /* C .i file */
#define FTNFILE ".f" /* Fortran source */
#define ASMFILE ".s" /* asm source */
Functions
void basenam (const char *orig_path, const char *optional_suffix, char *basename)
void dirnam (const char *orig_path, char *dirname)
int fndpath (const char *file, char *path, size_t max_length, const char *dirs)
char * mkperm (char *pattern, const char *oldext, const char *newext)
unsigned long get_rutime (void)
Detailed Description
Legacy utility interfaces.
This header comprises declarations and definitions from the original scutil/hammer/linux86-64/include/scutil.h header file that don't pertain to constant representation or the compile-time evaluation of operations.
Definition in file legacy-util-api.h.
Macro Definition Documentation
ASMFILE
#define ASMFILE ".s" /* asm source */
Definition at line 79 of file legacy-util-api.h.
CFILE
#define CFILE ".c" /* C source */
Definition at line 76 of file legacy-util-api.h.
DIRSEP
#define DIRSEP ':'
Definition at line 56 of file legacy-util-api.h.
DIRSINCS
#define DIRSINCS "/usr/include"
Definition at line 59 of file legacy-util-api.h.
DIRWORK
#define DIRWORK ""
Definition at line 58 of file legacy-util-api.h.
FTNFILE
#define FTNFILE ".f" /* Fortran source */
Definition at line 78 of file legacy-util-api.h.
IFILE
#define IFILE ".i" /* C .i file */
Definition at line 77 of file legacy-util-api.h.
IMGFILE
#define IMGFILE ".out" /* Image module file. */
Definition at line 70 of file legacy-util-api.h.
IMGLFILE
#define IMGLFILE ".ilb" /* Image library file. */
Definition at line 74 of file legacy-util-api.h.
LISTFILE
#define LISTFILE ".lst" /* Listing file. */
Definition at line 68 of file legacy-util-api.h.
MAPFILE
#define MAPFILE ".map" /* Map file from linker. */
Definition at line 75 of file legacy-util-api.h.
OBJFILE
#define OBJFILE ".o" /* Object module file. */
Definition at line 69 of file legacy-util-api.h.
OBJLFILE
#define OBJLFILE ".a" /* Object library file. */
Definition at line 73 of file legacy-util-api.h.
OVDFILE
#define OVDFILE ".ovd" /* Overlay description file. */
Definition at line 72 of file legacy-util-api.h.
SYMFILE
#define SYMFILE ".dbg" /* Symbol file. */
Definition at line 71 of file legacy-util-api.h.
UNKFILE
#define UNKFILE "" /* No extension. */
Definition at line 67 of file legacy-util-api.h.
Function Documentation
basenam()
void basenam (const char * orig_path, const char * optional_suffix, char * basename)
Definition at line 21 of file path-utils.c.
References fn, length(), NULL, and strlen().
Referenced by import_module_print(), and init().
dirnam()
void dirnam (const char * orig_path, char * dirname)
Definition at line 44 of file path-utils.c.
References dirname, length(), and NULL.
Referenced by _doincl(), accpp(), doincl(), fpp(), and scan_include().
fndpath()
int fndpath (const char * file, char * path, size_t max_length, const char * dirs)
Definition at line 59 of file path-utils.c.
References access, end, NULL, p, path, and strlen().
Referenced by _doincl(), doincl(), extractor_end(), get_module_file_name(), get_module_file_name_from_user(), load_inline_file(), load_TOC(), push_include(), and scan_include().
get_rutime()
unsigned long get_rutime (void)
Definition at line 21 of file cpu-stopwatch.c.
References last, times(), tms::tms_stime, and tms::tms_utime.
Referenced by main(), and process_input().
mkperm()
char * mkperm (char * pattern, const char * oldext, const char * newext)
Definition at line 99 of file path-utils.c.
References length(), and strlen().
Referenced by mkfname().