flang: legacy-folding-api.h File Reference
legacy-folding-api.h File Reference
Legacy constant folding API.
#include "legacy-ints.h"
Macros
#define FPE_NOERR 0 /* Everything OK */
#define FPE_FPOVF (-2) /* floating point overflow */
#define FPE_FPUNF (-3) /* floating point underflow */
#define FPE_IOVF (-2) /* integer overflow (fix/dfix only) */
#define FPE_INVOP (-1) /* invalid operand */
#define FPE_DIVZ (-2) /* reciprocal of zero */
#define ftomf(f, mf) ((mf)= *((float *)&(f)))
#define mftof(mf, f) (*((float *)&(f))=(mf))
Typedefs
typedef int32_t IEEE32
typedef int32_t IEEE64[2]
typedef int32_t IEEE80[3]
typedef IEEE64 IEEE6464[2]
typedef int32_t IEEE128[4]
typedef int32_t INT128[4]
typedef int32_t UINT128[4]
typedef IEEE32 SNGL
typedef IEEE64 DBLE
typedef IEEE128 QUAD
Functions
void fperror (int errcode)
void xdtomd (IEEE64 d, double *md)
void xmdtod (double md, IEEE64 d)
void xmqtoq (long double mq, IEEE128 q)
int cmp64 (DBLINT64 arg1, DBLINT64 arg2)
int ucmp64 (DBLUINT64 arg1, DBLUINT64 arg2)
void add64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
void div64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
void exp64 (DBLINT64 base, int exp, DBLINT64 result)
void mul64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
void mul64_10 (DBLINT64 arg1, DBLINT64 result)
void neg64 (DBLINT64 arg, DBLINT64 result)
void shf64 (DBLINT64 arg, int count, DBLINT64 result)
void sub64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
void uadd64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
void uneg64 (DBLUINT64 arg, DBLUINT64 result)
void ushf64 (DBLUINT64 arg, int count, DBLUINT64 result)
void usub64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
void udiv64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
void umul64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
void umul64_10 (DBLUINT64 arg1, DBLUINT64 result)
void and64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
void not64 (DBLINT64 arg, DBLINT64 result)
void or64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
void xor64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
void mul128 (DBLINT64 arg1, DBLINT64 arg2, INT result[4])
void shf128 (INT arg[4], int count, INT result[4])
void shf128_1 (INT arg[4], INT result[4])
void shf128_m1 (INT arg[4], INT result[4])
void neg128 (INT arg[4], INT result[4])
void add128 (INT128, INT128, INT128)
void sub128 (INT128, INT128, INT128)
int cmp128 (INT128, INT128)
int ucmp128 (UINT128, UINT128)
void div128 (INT128, INT128, INT128)
void mul256 (INT128, INT128, INT[])
void mul128l (INT128, INT128, INT128)
void negN (INT[], INT[], INT)
void shfN (INT[], INT, INT[], INT)
void shfN_1 (INT[], INT[], INT)
void shfN_m1 (INT[], INT[], INT)
int atoxi (const char *s, INT *i, int n, int base)
int atosi32 (const char *s, INT *i, int n, int base)
int atoxf (const char *s, IEEE32 *f, int n)
int atoxd (const char *s, IEEE64 d, int n)
int atoxe (const char *s, IEEE80 e, int n)
int atoxdd (const char *s, IEEE6464 dd, int n)
int atoxq (const char *s, IEEE128 q, int n)
int hxatoxf (const char *s, IEEE32 *f, int n)
int hxatoxd (const char *s, IEEE64 d, int n)
int hxatoxe (const char *s, IEEE80 e, int n)
int hxatoxdd (const char *s, IEEE6464 dd, int n)
int hxatoxq (const char *s, IEEE128 q, int n)
void cprintf (char *s, const char *format, INT *val)
int atoxi64 (const char *s, DBLINT64 ir, int n, int radix)
int atosi64 (const char *, DBLINT64, int, int)
void ui64toax (DBLINT64 from, char *to, int count, int sign, int radix)
void xqfix64 (IEEE128 q, DBLINT64 i)
void xqfixu64 (IEEE128 q, DBLUINT64 i)
void xefix64 (IEEE80 e, DBLINT64 i)
void xefixu64 (IEEE80 e, DBLUINT64 i)
void xddfix64 (IEEE6464 dd, DBLINT64 i)
void xddfixu64 (IEEE6464 dd, DBLUINT64 i)
void xdfix64 (IEEE64 d, DBLINT64 i)
void xdfixu64 (IEEE64 d, DBLUINT64 i)
void xfix64 (IEEE32 f, DBLINT64 i)
void xfixu64 (IEEE32 f, DBLUINT64 i)
void xfixu (IEEE32 f, UINT *r)
void xqflt64 (DBLINT64 i, IEEE128 q)
void xqfltu64 (DBLUINT64 i, IEEE128 q)
void xeflt64 (DBLINT64 i, IEEE80 e)
void xefltu64 (DBLUINT64 i, IEEE80 e)
void xddflt64 (DBLINT64 i, IEEE6464 dd)
void xddfltu64 (DBLUINT64 i, IEEE6464 dd)
void xdflt64 (DBLINT64 i, IEEE64 d)
void xdfltu64 (DBLUINT64 i, IEEE64 d)
void xflt64 (DBLINT64 i, IEEE32 *f)
void xfltu64 (DBLUINT64 i, IEEE32 *f)
void xfadd (IEEE32 f1, IEEE32 f2, IEEE32 *r)
void xdadd (IEEE64 d1, IEEE64 d2, IEEE64 r)
void xeadd (IEEE80 e1, IEEE80 e2, IEEE80 r)
void xddadd (IEEE6464 dd1, IEEE6464 dd2, IEEE6464 r)
void xqadd (IEEE128 q1, IEEE128 q2, IEEE128 r)
void xfsub (IEEE32 f1, IEEE32 f2, IEEE32 *r)
void xdsub (IEEE64 d1, IEEE64 d2, IEEE64 r)
void xesub (IEEE80 e1, IEEE80 e2, IEEE80 r)
void xddsub (IEEE6464 dd1, IEEE6464 dd2, IEEE6464 r)
void xqsub (IEEE128 q1, IEEE128 q2, IEEE128 r)
int xdisint (IEEE64 d, int *r)
int xqisint (IEEE128 q, int *r)
void xfneg (IEEE32 f1, IEEE32 *r)
void xdneg (IEEE64 d1, IEEE64 r)
void xeneg (IEEE80 e1, IEEE80 r)
void xddneg (IEEE6464 dd1, IEEE6464 r)
void xqneg (IEEE128 q1, IEEE128 r)
void xfmul (IEEE32 f1, IEEE32 f2, IEEE32 *r)
void xdmul (IEEE64 d1, IEEE64 d2, IEEE64 r)
void xemul (IEEE80 e1, IEEE80 e2, IEEE80 r)
void xddmul (IEEE6464 dd1, IEEE6464 dd2, IEEE6464 r)
void xqmul (IEEE128 q1, IEEE128 q2, IEEE128 r)
void xfdiv (IEEE32 f1, IEEE32 f2, IEEE32 *r)
void xddiv (IEEE64 d1, IEEE64 d2, IEEE64 r)
void xediv (IEEE80 e1, IEEE80 e2, IEEE80 r)
void xdddiv (IEEE6464 dd1, IEEE6464 dd2, IEEE6464 r)
void xqdiv (IEEE128 q1, IEEE128 q2, IEEE128 r)
void xdrcp (IEEE64 d, IEEE64 recip)
void xfrcp (IEEE32 f, IEEE32 *recip)
void xfabsv (IEEE32 f, IEEE32 *r)
int xfisint (IEEE32 f, int *r)
void xfsqrt (IEEE32 f, IEEE32 *r)
void xdabsv (IEEE64 f, IEEE64 r)
void xeabsv (IEEE80 e, IEEE80 r)
void xddabsv (IEEE6464 dd, IEEE6464 r)
void xqabsv (IEEE128 f, IEEE128 r)
void xdsqrt (IEEE64 f, IEEE64 r)
void xqsqrt (IEEE128 f, IEEE128 r)
void xfpow (IEEE32 f1, IEEE32 f2, IEEE32 *r)
void xdpow (IEEE64 d1, IEEE64 d2, IEEE64 r)
void xepow (IEEE80 e1, IEEE80 e2, IEEE80 r)
void xddpow (IEEE6464 dd1, IEEE6464 dd2, IEEE6464 r)
void xqpow (IEEE128 q1, IEEE128 q2, IEEE128 r)
void xfsin (IEEE32, IEEE32 *)
void xdsin (IEEE64, IEEE64)
void xesin (IEEE80, IEEE80)
void xddsin (IEEE6464, IEEE6464)
void xqsin (IEEE128, IEEE128)
void xfcos (IEEE32, IEEE32 *)
void xdcos (IEEE64, IEEE64)
void xecos (IEEE80, IEEE80)
void xddcos (IEEE6464, IEEE6464)
void xqcos (IEEE128, IEEE128)
void xftan (IEEE32, IEEE32 *)
void xdtan (IEEE64, IEEE64)
void xetan (IEEE80, IEEE80)
void xddtan (IEEE6464, IEEE6464)
void xqtan (IEEE128, IEEE128)
void xfasin (IEEE32, IEEE32 *)
void xdasin (IEEE64, IEEE64)
void xeasin (IEEE80, IEEE80)
void xddasin (IEEE6464, IEEE6464)
void xqasin (IEEE128, IEEE128)
void xfacos (IEEE32, IEEE32 *)
void xdacos (IEEE64, IEEE64)
void xeacos (IEEE80, IEEE80)
void xddacos (IEEE6464, IEEE6464)
void xqacos (IEEE128, IEEE128)
void xfatan (IEEE32, IEEE32 *)
void xdatan (IEEE64, IEEE64)
void xeatan (IEEE80, IEEE80)
void xddatan (IEEE6464, IEEE6464)
void xqatan (IEEE128, IEEE128)
void xfatan2 (IEEE32, IEEE32, IEEE32 *)
void xdatan2 (IEEE64, IEEE64, IEEE64)
void xeatan2 (IEEE80, IEEE80, IEEE80)
void xddatan2 (IEEE6464, IEEE6464, IEEE6464)
void xqatan2 (IEEE128, IEEE128, IEEE128)
void xfexp (IEEE32, IEEE32 *)
void xdexp (IEEE64, IEEE64)
void xeexp (IEEE80, IEEE80)
void xddexp (IEEE6464, IEEE6464)
void xqexp (IEEE128, IEEE128)
void xflog (IEEE32, IEEE32 *)
void xdlog (IEEE64, IEEE64)
void xelog (IEEE80, IEEE80)
void xddlog (IEEE6464, IEEE6464)
void xqlog (IEEE128, IEEE128)
void xflog10 (IEEE32, IEEE32 *)
void xdlog10 (IEEE64, IEEE64)
void xelog10 (IEEE80, IEEE80)
void xddlog10 (IEEE6464, IEEE6464)
void xqlog10 (IEEE128, IEEE128)
void xffloat (INT i, IEEE32 *f)
void xdfloat (INT i, IEEE64 d)
void xefloat (INT i, IEEE80 e)
void xddfloat (INT i, IEEE6464 dd)
void xqfloat (INT i, IEEE128 q)
void xfix (IEEE32 f, INT *i)
void xdfix (IEEE64 d, INT *i)
void xefix (IEEE80 e, INT *i)
void xddfix (IEEE6464 dd, INT *i)
void xqfix (IEEE128 q, INT *i)
void xdble (IEEE32 f, IEEE64 r)
void xsngl (IEEE64 d, IEEE32 *r)
void xdtoe (IEEE64 d, IEEE80 r)
void xdtodd (IEEE64 d, IEEE6464 r)
void xdtoq (IEEE64 d, IEEE128 r)
void xftoe (IEEE32 d, IEEE80 r)
void xftodd (IEEE32 d, IEEE6464 r)
void xftoq (IEEE32 d, IEEE128 r)
void xetof (IEEE80 e, IEEE32 *r)
void xetod (IEEE80 e, IEEE64 r)
void xetoq (IEEE80 e, IEEE128 r)
void xddtof (IEEE6464 dd, IEEE32 *r)
void xddtod (IEEE6464 dd, IEEE64 r)
void xddtoq (IEEE6464 dd, IEEE128 r)
void xqtodd (IEEE128 q, IEEE6464 r)
void xqtoe (IEEE128 q, IEEE80 r)
void xqtod (IEEE128 q, IEEE64 r)
void xqtof (IEEE128 q, IEEE32 *)
int xudiv (UINT n, UINT d, UINT *r)
int xumod (UINT n, UINT d, UINT *r)
void xqfixu (IEEE128 q, UINT *r)
void xqfloatu (UINT i, IEEE128 r)
void xddfixu (IEEE6464 dd, UINT *r)
void xddfloatu (UINT i, IEEE6464 r)
void xefixu (IEEE80 e, UINT *r)
void xefloatu (UINT i, IEEE80 r)
void xdfixu (IEEE64 d, UINT *r)
void xdfloatu (UINT i, IEEE64 r)
void xffixu (IEEE32 f, UINT *r)
void xffloatu (UINT i, IEEE32 *r)
int xqcmp (IEEE128 q1, IEEE128 q2)
int xddcmp (IEEE6464 dd1, IEEE6464 dd2)
int xecmp (IEEE80 e1, IEEE80 e2)
int xdcmp (IEEE64 d1, IEEE64 d2)
int xfcmp (IEEE32 f1, IEEE32 f2)
int xucmp (INT a, INT b)
void xcfpow (IEEE32 r1, IEEE32 i1, IEEE32 r2, IEEE32 i2, IEEE32 *rr, IEEE32 *ir)
void xcdpow (IEEE64 r1, IEEE64 i1, IEEE64 r2, IEEE64 i2, IEEE64 rr, IEEE64 ir)
void xcqpow (IEEE128 r1, IEEE128 i1, IEEE128 r2, IEEE128 i2, IEEE128 rr, IEEE128 ir)
Detailed Description
Legacy constant folding API.
This header comprises declarations and definitions from the original scutil/hammer/linux86-64/include/scutil.h header file that pertain to the representation of constants as arrays of 32-bit integers, scanning and formatting of numeric literals, and compile-time evaluation of operations.
Definition in file legacy-folding-api.h.
Macro Definition Documentation
FPE_DIVZ
#define FPE_DIVZ (-2) /* reciprocal of zero */
Definition at line 54 of file legacy-folding-api.h.
FPE_FPOVF
#define FPE_FPOVF (-2) /* floating point overflow */
Definition at line 50 of file legacy-folding-api.h.
FPE_FPUNF
#define FPE_FPUNF (-3) /* floating point underflow */
Definition at line 51 of file legacy-folding-api.h.
FPE_INVOP
#define FPE_INVOP (-1) /* invalid operand */
Definition at line 53 of file legacy-folding-api.h.
FPE_IOVF
#define FPE_IOVF (-2) /* integer overflow (fix/dfix only) */
Definition at line 52 of file legacy-folding-api.h.
FPE_NOERR
#define FPE_NOERR 0 /* Everything OK */
Definition at line 49 of file legacy-folding-api.h.
ftomf
#define ftomf (f, mf) ((mf)= *((float *)&(f)))
Definition at line 57 of file legacy-folding-api.h.
mftof
#define mftof (mf, f) (*((float *)&(f))=(mf))
Definition at line 58 of file legacy-folding-api.h.
Typedef Documentation
DBLE
typedef IEEE64 DBLE
Definition at line 41 of file legacy-folding-api.h.
IEEE128
typedef int32_t IEEE128[4]
Definition at line 35 of file legacy-folding-api.h.
IEEE32
typedef int32_t IEEE32
Definition at line 31 of file legacy-folding-api.h.
IEEE64
typedef int32_t IEEE64[2]
Definition at line 32 of file legacy-folding-api.h.
IEEE6464
typedef IEEE64 IEEE6464[2]
Definition at line 34 of file legacy-folding-api.h.
IEEE80
typedef int32_t IEEE80[3]
Definition at line 33 of file legacy-folding-api.h.
INT128
typedef int32_t INT128[4]
Definition at line 36 of file legacy-folding-api.h.
QUAD
typedef IEEE128 QUAD
Definition at line 42 of file legacy-folding-api.h.
SNGL
typedef IEEE32 SNGL
Definition at line 40 of file legacy-folding-api.h.
UINT128
typedef int32_t UINT128[4]
Definition at line 37 of file legacy-folding-api.h.
Function Documentation
add128()
void add128 (INT128 arg1, INT128 arg2, INT128 result)
Definition at line 427 of file legacy-folding-api.c.
References int128_unsigned_add(), result, unwrap_i128(), wrap_i128(), x, y, and z.
Referenced by choose_multiplier_64().
add64()
void add64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 161 of file legacy-folding-api.c.
References res, result, unwrap_l(), and wrap_l().
Referenced by addarth(), choose_multiplier(), const_fold(), init_fold_const(), lldbg_create_subrange_mdnode_pre11(), mk_swtab_ll(), red_kadd(), and ref_pd().
and64()
void and64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 315 of file legacy-folding-api.c.
References res, result, unwrap_l(), and wrap_l().
Referenced by addarth(), binop(), reciprocal_division_64(), and ref_intrin().
atosi32()
int atosi32 (const char * s, INT * i, int n, int base)
Definition at line 2372 of file legacy-folding-api.c.
References atoxi(), base, i, n, and s.
Referenced by get_number(), and get_prefixed_int().
atosi64()
int atosi64 (const char * s, DBLINT64 i, int n, int base)
Definition at line 2378 of file legacy-folding-api.c.
References atoxi64(), base, i, n, and s.
atoxd()
int atoxd (const char * s, IEEE64 d, int n)
Definition at line 1176 of file legacy-folding-api.c.
References d, n, parse_d(), and s.
Referenced by _huge(), add_fp_constants(), exp_mac(), get_number(), and ref_pd().
atoxdd()
int atoxdd (const char * s, IEEE6464 dd, int n)
atoxe()
int atoxe (const char * s, IEEE80 e, int n)
Referenced by add_fp_constants().
atoxf()
int atoxf (const char * s, IEEE32 * f, int n)
Definition at line 850 of file legacy-folding-api.c.
References f, n, parse_f(), and s.
Referenced by add_fp_constants(), exp_mac(), and get_number().
atoxi()
int atoxi (const char * s, INT * i, int n, int base)
Definition at line 2334 of file legacy-folding-api.c.
References base, generic_atoxi(), i, INT32_MAX, n, s, and UINT32_MAX.
Referenced by accpp(), atosi32(), exp_mac(), ff_get_label(), fpp(), get_kind_id(), get_nondec(), get_num(), get_prefixed_int(), get_stmt(), and tobinary().
atoxi64()
int atoxi64 (const char * s, DBLINT64 ir, int n, int radix)
Definition at line 2350 of file legacy-folding-api.c.
References base, generic_atoxi(), i, n, s, and wrap_l().
Referenced by atosi64(), exp_mac(), get_num(), get_number(), get_prefixed_int(), and tobinary64().
atoxq()
int atoxq (const char * s, IEEE128 q, int n)
Definition at line 2236 of file legacy-folding-api.c.
References n, parse_q(), q, and s.
Referenced by add_fp_constants(), and get_number().
cmp128()
int cmp128 (INT128 arg1, INT128 arg2)
Definition at line 447 of file legacy-folding-api.c.
References int128_signed_compare(), unwrap_i128(), x, and y.
Referenced by choose_multiplier_64(), and reciprocal_division_64().
cmp64()
int cmp64 (DBLINT64 arg1, DBLINT64 arg2)
Definition at line 143 of file legacy-folding-api.c.
References unwrap_l(), y, and z.
Referenced by addarth(), addbran(), binop(), choose_multiplier(), const_fold(), eval_abs(), extent_of_shape(), flowgraph(), init_fold_const(), mk_binop(), mk_swtab_ll(), negative_constant(), reciprocal_division(), reciprocal_division_64(), reduce_i8add(), ref_intrin(), and ref_pd().
cprintf()
void cprintf (char * s, const char * format, INT * val)
Definition at line 2388 of file legacy-folding-api.c.
References d, E, f, NULL, off, p, unwrap_d(), unwrap_f(), unwrap_q(), val, and x.
Referenced by gen_constant(), getprint(), prettytoken(), printname(), put_double(), put_float(), and write_constant_value().
div128()
void div128 (INT128 arg1, INT128 arg2, INT128 result)
Definition at line 468 of file legacy-folding-api.c.
References int128_signed_divide(), remainder, result, unwrap_i128(), wrap_i128(), x, and y.
Referenced by choose_multiplier_64().
div64()
void div64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 171 of file legacy-folding-api.c.
References num, res, result, unwrap_l(), and wrap_l().
Referenced by addarth(), choose_multiplier(), const_fold(), init_fold_const(), mod64(), and ref_intrin().
exp64()
void exp64 (DBLINT64 base, int exp, DBLINT64 result)
Definition at line 181 of file legacy-folding-api.c.
References arg, base, exp, result, unwrap_l(), wrap_l(), and x.
fperror()
static void fperror (int errcode)
Definition at line 2408 of file flang/fpcvt.c.
References FP_ILLEGAL_INPUT_OR_NAN, FP_NOERR, FP_OVERFLOW_ERROR, FP_UNDERFLOW_ERROR, and x.
Referenced by check().
hxatoxd()
int hxatoxd (const char * s, IEEE64 d, int n)
Definition at line 1182 of file legacy-folding-api.c.
References d, n, parse_d(), and s.
hxatoxdd()
int hxatoxdd (const char * s, IEEE6464 dd, int n)
hxatoxe()
int hxatoxe (const char * s, IEEE80 e, int n)
hxatoxf()
int hxatoxf (const char * s, IEEE32 * f, int n)
Definition at line 856 of file legacy-folding-api.c.
References f, n, parse_f(), and s.
hxatoxq()
int hxatoxq (const char * s, IEEE128 q, int n)
Definition at line 2242 of file legacy-folding-api.c.
References n, parse_q(), q, and s.
mul128()
void mul128 (DBLINT64 arg1, DBLINT64 arg2, INT result[4])
mul128l()
void mul128l (INT128 arg1, INT128 arg2, INT128 result)
Definition at line 458 of file legacy-folding-api.c.
References int128_signed_multiply(), result, unwrap_i128(), wrap_i128(), x, and y.
Referenced by choose_multiplier_64().
mul256()
void mul256 (INT128 , INT128 , INT [])
mul64()
void mul64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 191 of file legacy-folding-api.c.
References res, result, unwrap_l(), and wrap_l().
Referenced by _xtok(), addarth(), choose_multiplier(), const_fold(), init_fold_const(), mod64(), and ref_intrin().
mul64_10()
void mul64_10 (DBLINT64 arg1, DBLINT64 result)
Definition at line 201 of file legacy-folding-api.c.
References arg, i, result, unwrap_l(), and wrap_l().
neg128()
void neg128 (INT arg[4], INT result[4])
neg64()
static void neg64 (DBLINT64 arg, DBLINT64 result)
Definition at line 530 of file utilsi64.c.
References arg, i, result, sign, unwrap_l(), and wrap_l().
Referenced by addarth(), eval_abs(), reciprocal_division_64(), red_kadd(), ref_intrin(), and ref_pd().
negN()
void negN (INT [], INT [], INT)
not64()
void not64 (DBLINT64 arg, DBLINT64 result)
Definition at line 325 of file legacy-folding-api.c.
References arg, i, result, unwrap_l(), and wrap_l().
Referenced by ref_intrin().
or64()
void or64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 334 of file legacy-folding-api.c.
References res, result, unwrap_l(), and wrap_l().
Referenced by binop(), and ref_intrin().
shf128()
void shf128 (INT arg[4], int count, INT result[4])
Referenced by choose_multiplier_64().
shf128_1()
void shf128_1 (INT arg[4], INT result[4])
shf128_m1()
void shf128_m1 (INT arg[4], INT result[4])
shf64()
void shf64 (DBLINT64 arg, int count, DBLINT64 result)
Definition at line 331 of file ftni64bitsup.c.
References arg, count, and result.
Referenced by addarth(), choose_multiplier(), reciprocal_division(), reciprocal_division_64(), and ref_pd().
shfN()
void shfN (INT [], INT , INT [], INT)
shfN_1()
void shfN_1 (INT [], INT [], INT)
shfN_m1()
void shfN_m1 (INT [], INT [], INT)
sub128()
void sub128 (INT128 arg1, INT128 arg2, INT128 result)
Definition at line 437 of file legacy-folding-api.c.
References int128_signed_subtract(), result, unwrap_i128(), wrap_i128(), x, y, and z.
Referenced by choose_multiplier_64(), and reciprocal_division_64().
sub64()
void sub64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 233 of file legacy-folding-api.c.
References res, result, unwrap_l(), and wrap_l().
Referenced by addarth(), choose_multiplier(), const_fold(), init_fold_const(), lldbg_create_subrange_mdnode_pre11(), mk_swtab_ll(), mod64(), reciprocal_division(), and ref_intrin().
uadd64()
void uadd64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
Definition at line 243 of file legacy-folding-api.c.
References res, result, unwrap_u(), and wrap_u().
ucmp128()
int ucmp128 (UINT128 , UINT128)
ucmp64()
static int ucmp64 (DBLUINT64 arg1, DBLUINT64 arg2)
Definition at line 554 of file utilsi64.c.
References unwrap_u(), y, and z.
Referenced by addarth(), addbran(), and lg64().
udiv64()
void udiv64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
Definition at line 286 of file legacy-folding-api.c.
References num, res, result, unwrap_u(), and wrap_u().
Referenced by addarth(), and umod64().
ui64toax()
void ui64toax (DBLINT64 from, char * to, int count, int sign, int radix)
Definition at line 354 of file legacy-folding-api.c.
References assert, size, unwrap_l(), and x.
Referenced by gen_constant(), getprint(), printname(), put_int8(), and write_constant_value().
umul64()
void umul64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
Definition at line 296 of file legacy-folding-api.c.
References res, result, unwrap_u(), and wrap_u().
Referenced by addarth(), and umod64().
umul64_10()
void umul64_10 (DBLUINT64 arg1, DBLUINT64 result)
Definition at line 306 of file legacy-folding-api.c.
References arg, result, unwrap_u(), and wrap_u().
uneg64()
static void uneg64 (DBLUINT64 arg, DBLUINT64 result)
Definition at line 541 of file utilsi64.c.
References arg, result, sign, unwrap_u(), and wrap_u().
ushf64()
void ushf64 (DBLUINT64 arg, int count, DBLUINT64 result)
Definition at line 378 of file ftni64bitsup.c.
References arg, count, and result.
Referenced by addarth(), lg64(), reciprocal_division_64(), and ref_pd().
usub64()
void usub64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
Definition at line 276 of file legacy-folding-api.c.
References res, result, unwrap_u(), and wrap_u().
Referenced by umod64().
xcdpow()
void xcdpow (IEEE64 r1, IEEE64 i1, IEEE64 r2, IEEE64 i2, IEEE64 rr, IEEE64 ir)
Definition at line 2460 of file legacy-folding-api.c.
References check(), cimag, creal, DOUBLE_COMPLEX_CREATE, DOUBLE_COMPLEX_TYPE, fold_complex64_pow(), iy, unwrap_d(), wrap_d(), x, y, and z.
Referenced by const_fold(), and init_fold_const().
xcfpow()
void xcfpow (IEEE32 r1, IEEE32 i1, IEEE32 r2, IEEE32 i2, IEEE32 * rr, IEEE32 * ir)
Definition at line 2437 of file legacy-folding-api.c.
References check(), cimagf, crealf, FLOAT_COMPLEX_CREATE, FLOAT_COMPLEX_TYPE, fold_complex32_pow(), iy, unwrap_f(), wrap_f(), x, y, and z.
Referenced by const_fold(), and init_fold_const().
xcqpow()
void xcqpow (IEEE128 r1, IEEE128 i1, IEEE128 r2, IEEE128 i2, IEEE128 rr, IEEE128 ir)
Definition at line 2483 of file legacy-folding-api.c.
References check(), fold_complex128_pow(), iy, LONG_DOUBLE_COMPLEX_CREATE, LONG_DOUBLE_COMPLEX_TYPE, unwrap_q(), wrap_q(), x, y, and z.
Referenced by const_fold(), and init_fold_const().
xdabsv()
void xdabsv (IEEE64 f, IEEE64 r)
Definition at line 1022 of file legacy-folding-api.c.
References check(), d, fold_real64_abs(), r, unwrap_d(), wrap_d(), x, and y.
Referenced by addarth(), eval_abs(), and ref_intrin().
xdacos()
void xdacos (IEEE64 d, IEEE64 r)
Definition at line 1086 of file legacy-folding-api.c.
References check(), d, fold_real64_acos(), r, unwrap_d(), wrap_d(), x, and y.
xdadd()
void xdadd (IEEE64 d1, IEEE64 d2, IEEE64 r)
Definition at line 962 of file legacy-folding-api.c.
References check(), fold_real64_add(), r, unwrap_d(), wrap_d(), x, y, and z.
Referenced by _xtok(), addarth(), const_fold(), and init_fold_const().
xdasin()
void xdasin (IEEE64 d, IEEE64 r)
Definition at line 1077 of file legacy-folding-api.c.
References check(), d, fold_real64_asin(), r, unwrap_d(), wrap_d(), x, and y.
xdatan()
void xdatan (IEEE64 d, IEEE64 r)
Definition at line 1095 of file legacy-folding-api.c.
References check(), d, fold_real64_atan(), r, unwrap_d(), wrap_d(), x, and y.
Referenced by addarth().
xdatan2()
void xdatan2 (IEEE64 d1, IEEE64 d2, IEEE64 r)
Definition at line 1104 of file legacy-folding-api.c.
References check(), fold_real64_atan2(), r, unwrap_d(), wrap_d(), x, y, and z.
xdble()
void xdble (IEEE32 f, IEEE64 r)
Definition at line 942 of file legacy-folding-api.c.
References check(), f, fold_real64_from_real32(), r, unwrap_f(), wrap_d(), x, and y.
Referenced by addarth(), check_ccon(), cngcon(), convert_cnst(), gen_constant(), ref_intrin(), and write_constant_value().
xdcmp()
int xdcmp (IEEE64 d1, IEEE64 d2)
Definition at line 1141 of file legacy-folding-api.c.
References fold_real64_compare(), unwrap_d(), y, and z.
Referenced by addarth(), const_fold(), init_fold_const(), negative_constant(), and ref_intrin().
xdcos()
void xdcos (IEEE64 d, IEEE64 r)
Definition at line 1059 of file legacy-folding-api.c.
References check(), d, fold_real64_cos(), r, unwrap_d(), wrap_d(), x, and y.
xddabsv()
void xddabsv (IEEE6464 dd, IEEE6464 r)
xddacos()
void xddacos (IEEE6464 , IEEE6464)
xddadd()
void xddadd (IEEE6464 dd1, IEEE6464 dd2, IEEE6464 r)
xddasin()
void xddasin (IEEE6464 , IEEE6464)
xddatan()
void xddatan (IEEE6464 , IEEE6464)
xddatan2()
void xddatan2 (IEEE6464 , IEEE6464 , IEEE6464)
xddcmp()
int xddcmp (IEEE6464 dd1, IEEE6464 dd2)
xddcos()
void xddcos (IEEE6464 , IEEE6464)
xdddiv()
void xdddiv (IEEE6464 dd1, IEEE6464 dd2, IEEE6464 r)
xddexp()
void xddexp (IEEE6464 , IEEE6464)
xddfix()
void xddfix (IEEE6464 dd, INT * i)
xddfix64()
void xddfix64 (IEEE6464 dd, DBLINT64 i)
xddfixu()
void xddfixu (IEEE6464 dd, UINT * r)
xddfixu64()
void xddfixu64 (IEEE6464 dd, DBLUINT64 i)
xddfloat()
void xddfloat (INT i, IEEE6464 dd)
xddfloatu()
void xddfloatu (UINT i, IEEE6464 r)
xddflt64()
void xddflt64 (DBLINT64 i, IEEE6464 dd)
xddfltu64()
void xddfltu64 (DBLUINT64 i, IEEE6464 dd)
xddiv()
void xddiv (IEEE64 d1, IEEE64 d2, IEEE64 r)
Definition at line 1001 of file legacy-folding-api.c.
References check(), fold_real64_divide(), r, unwrap_d(), wrap_d(), x, y, and z.
Referenced by _ddiv(), addarth(), and eval_mod().
xddlog()
void xddlog (IEEE6464 , IEEE6464)
xddlog10()
void xddlog10 (IEEE6464 , IEEE6464)
xddmul()
void xddmul (IEEE6464 dd1, IEEE6464 dd2, IEEE6464 r)
xddneg()
void xddneg (IEEE6464 dd1, IEEE6464 r)
xddpow()
void xddpow (IEEE6464 dd1, IEEE6464 dd2, IEEE6464 r)
xddsin()
void xddsin (IEEE6464 , IEEE6464)
xddsub()
void xddsub (IEEE6464 dd1, IEEE6464 dd2, IEEE6464 r)
xddtan()
void xddtan (IEEE6464 , IEEE6464)
xddtod()
void xddtod (IEEE6464 dd, IEEE64 r)
xddtof()
void xddtof (IEEE6464 dd, IEEE32 * r)
xddtoq()
void xddtoq (IEEE6464 dd, IEEE128 r)
xdexp()
void xdexp (IEEE64 d, IEEE64 r)
Definition at line 1114 of file legacy-folding-api.c.
References check(), d, fold_real64_exp(), r, unwrap_d(), wrap_d(), x, and y.
xdfix()
void xdfix (IEEE64 d, INT * i)
Definition at line 866 of file legacy-folding-api.c.
References check(), d, fold_int32_from_real64(), i, unwrap_d(), and x.
Referenced by addarth(), cngcon(), and convert_cnst().
xdfix64()
void xdfix64 (IEEE64 d, DBLINT64 i)
Definition at line 882 of file legacy-folding-api.c.
References check(), d, fold_int64_from_real64(), unwrap_d(), wrap_l(), x, and y.
Referenced by addarth(), cngcon(), and convert_cnst().
xdfixu()
void xdfixu (IEEE64 d, UINT * r)
Definition at line 874 of file legacy-folding-api.c.
References check(), d, fold_uint32_from_real64(), unwrap_d(), and x.
Referenced by addarth().
xdfixu64()
void xdfixu64 (IEEE64 d, DBLUINT64 i)
Definition at line 892 of file legacy-folding-api.c.
References check(), d, fold_int64_from_real64(), unwrap_d(), wrap_u(), x, and y.
xdfloat()
void xdfloat (INT i, IEEE64 d)
Definition at line 904 of file legacy-folding-api.c.
References check(), d, fold_real64_from_int64(), i, wrap_d(), and x.
Referenced by addarth(), cngcon(), and convert_cnst().
xdfloatu()
void xdfloatu (UINT i, IEEE64 r)
Definition at line 913 of file legacy-folding-api.c.
References check(), d, fold_real64_from_int64(), wrap_d(), and x.
Referenced by addarth().
xdflt64()
void xdflt64 (DBLINT64 i, IEEE64 d)
Definition at line 922 of file legacy-folding-api.c.
References check(), d, fold_real64_from_int64(), unwrap_l(), wrap_d(), x, and y.
Referenced by addarth(), cngcon(), and convert_cnst().
xdfltu64()
void xdfltu64 (DBLUINT64 i, IEEE64 d)
Definition at line 932 of file legacy-folding-api.c.
References check(), d, fold_real64_from_uint64(), unwrap_u(), wrap_d(), x, and y.
Referenced by addarth().
xdisint()
int xdisint (IEEE64 d, int * r)
Definition at line 1150 of file legacy-folding-api.c.
References check(), d, FOLD_EQ, fold_int32_from_real64(), fold_real64_compare(), fold_real64_from_int64(), i, k, unwrap_d(), x, and y.
Referenced by addarth(), and chkopnds().
xdlog()
void xdlog (IEEE64 d, IEEE64 r)
Definition at line 1123 of file legacy-folding-api.c.
References check(), d, fold_real64_log(), r, unwrap_d(), wrap_d(), x, and y.
xdlog10()
void xdlog10 (IEEE64 d, IEEE64 r)
Definition at line 1132 of file legacy-folding-api.c.
References check(), d, fold_real64_log10(), r, unwrap_d(), wrap_d(), x, and y.
xdmul()
void xdmul (IEEE64 d1, IEEE64 d2, IEEE64 r)
Definition at line 991 of file legacy-folding-api.c.
References check(), fold_real64_multiply(), r, unwrap_d(), wrap_d(), x, y, and z.
Referenced by _ddiv(), _xtok(), addarth(), const_fold(), eval_mod(), eval_scale(), init_fold_const(), and ref_intrin().
xdneg()
void xdneg (IEEE64 d1, IEEE64 r)
Definition at line 982 of file legacy-folding-api.c.
References check(), d, fold_real64_negate(), r, unwrap_d(), wrap_d(), x, and y.
Referenced by add_fp_constants(), addarth(), init_negate_const(), negate_const(), negate_const_be(), ref_intrin(), and sym_init().
xdpow()
void xdpow (IEEE64 d1, IEEE64 d2, IEEE64 r)
Definition at line 1040 of file legacy-folding-api.c.
References check(), fold_real64_pow(), r, unwrap_d(), wrap_d(), x, y, and z.
Referenced by const_fold(), and init_fold_const().
xdrcp()
void xdrcp (IEEE64 d, IEEE64 recip)
Definition at line 1011 of file legacy-folding-api.c.
References check(), d, fold_real64_divide(), fold_real64_from_int64(), one, r, unwrap_d(), wrap_d(), x, and y.
Referenced by _ddiv().
xdsin()
void xdsin (IEEE64 d, IEEE64 r)
Definition at line 1050 of file legacy-folding-api.c.
References check(), d, fold_real64_sin(), r, unwrap_d(), wrap_d(), x, and y.
xdsqrt()
void xdsqrt (IEEE64 f, IEEE64 r)
Definition at line 1031 of file legacy-folding-api.c.
References check(), d, fold_real64_sqrt(), r, unwrap_d(), wrap_d(), x, and y.
Referenced by addarth(), and eval_sqrt().
xdsub()
void xdsub (IEEE64 d1, IEEE64 d2, IEEE64 r)
Definition at line 972 of file legacy-folding-api.c.
References check(), fold_real64_subtract(), r, unwrap_d(), wrap_d(), x, y, and z.
Referenced by _xtok(), addarth(), const_fold(), eval_mod(), and init_fold_const().
xdtan()
void xdtan (IEEE64 d, IEEE64 r)
Definition at line 1068 of file legacy-folding-api.c.
References check(), d, fold_real64_tan(), r, unwrap_d(), wrap_d(), x, and y.
xdtodd()
void xdtodd (IEEE64 d, IEEE6464 r)
xdtoe()
void xdtoe (IEEE64 d, IEEE80 r)
xdtomd()
void xdtomd (IEEE64 d, double * md)
Definition at line 127 of file legacy-folding-api.c.
References d, and unwrap_d().
Referenced by gen_constant(), and write_constant_value().
xdtoq()
void xdtoq (IEEE64 d, IEEE128 r)
Definition at line 1992 of file legacy-folding-api.c.
References check(), d, fold_real128_from_real64(), q, unwrap_d(), wrap_q(), x, and y.
Referenced by check_ccon(), cngcon(), and convert_cnst().
xeabsv()
void xeabsv (IEEE80 e, IEEE80 r)
xeacos()
void xeacos (IEEE80 , IEEE80)
xeadd()
void xeadd (IEEE80 e1, IEEE80 e2, IEEE80 r)
xeasin()
void xeasin (IEEE80 , IEEE80)
xeatan()
void xeatan (IEEE80 , IEEE80)
xeatan2()
void xeatan2 (IEEE80 , IEEE80 , IEEE80)
xecmp()
int xecmp (IEEE80 e1, IEEE80 e2)
xecos()
void xecos (IEEE80 , IEEE80)
xediv()
void xediv (IEEE80 e1, IEEE80 e2, IEEE80 r)
xeexp()
void xeexp (IEEE80 , IEEE80)
xefix()
void xefix (IEEE80 e, INT * i)
xefix64()
void xefix64 (IEEE80 e, DBLINT64 i)
xefixu()
void xefixu (IEEE80 e, UINT * r)
xefixu64()
void xefixu64 (IEEE80 e, DBLUINT64 i)
xefloat()
void xefloat (INT i, IEEE80 e)
xefloatu()
void xefloatu (UINT i, IEEE80 r)
xeflt64()
void xeflt64 (DBLINT64 i, IEEE80 e)
xefltu64()
void xefltu64 (DBLUINT64 i, IEEE80 e)
xelog()
void xelog (IEEE80 , IEEE80)
xelog10()
void xelog10 (IEEE80 , IEEE80)
xemul()
void xemul (IEEE80 e1, IEEE80 e2, IEEE80 r)
xeneg()
void xeneg (IEEE80 e1, IEEE80 r)
Referenced by add_fp_constants().
xepow()
void xepow (IEEE80 e1, IEEE80 e2, IEEE80 r)
xesin()
void xesin (IEEE80 , IEEE80)
xesub()
void xesub (IEEE80 e1, IEEE80 e2, IEEE80 r)
xetan()
void xetan (IEEE80 , IEEE80)
xetod()
void xetod (IEEE80 e, IEEE64 r)
xetof()
void xetof (IEEE80 e, IEEE32 * r)
xetoq()
void xetoq (IEEE80 e, IEEE128 r)
xfabsv()
void xfabsv (IEEE32 f, IEEE32 * r)
Definition at line 646 of file legacy-folding-api.c.
References check(), f, fold_real32_abs(), r, unwrap_f(), wrap_f(), x, and y.
Referenced by addarth(), eval_abs(), and ref_intrin().
xfacos()
void xfacos (IEEE32 f, IEEE32 * r)
Definition at line 710 of file legacy-folding-api.c.
References check(), f, fold_real32_acos(), r, unwrap_f(), wrap_f(), x, and y.
xfadd()
void xfadd (IEEE32 f1, IEEE32 f2, IEEE32 * r)
Definition at line 586 of file legacy-folding-api.c.
References check(), f2, fold_real32_add(), r, unwrap_f(), wrap_f(), x, y, and z.
Referenced by _xtok(), addarth(), const_fold(), eval_abs(), eval_nint(), init_fold_const(), ref_intrin(), and ref_pd().
xfasin()
void xfasin (IEEE32 f, IEEE32 * r)
Definition at line 701 of file legacy-folding-api.c.
References check(), f, fold_real32_asin(), r, unwrap_f(), wrap_f(), x, and y.
xfatan()
void xfatan (IEEE32 f, IEEE32 * r)
Definition at line 719 of file legacy-folding-api.c.
References check(), f, fold_real32_atan(), r, unwrap_f(), wrap_f(), x, and y.
Referenced by addarth().
xfatan2()
void xfatan2 (IEEE32 f1, IEEE32 f2, IEEE32 * r)
Definition at line 728 of file legacy-folding-api.c.
References check(), f2, fold_real32_atan2(), r, unwrap_f(), wrap_f(), x, y, and z.
xfcmp()
int xfcmp (IEEE32 f1, IEEE32 f2)
Definition at line 765 of file legacy-folding-api.c.
References f2, fold_real32_compare(), unwrap_f(), y, and z.
Referenced by addarth(), cmp_acl(), const_fold(), eval_ceiling(), eval_floor(), eval_max(), eval_min(), eval_nint(), init_fold_const(), negative_constant(), ref_intrin(), and ref_pd().
xfcos()
void xfcos (IEEE32 f, IEEE32 * r)
Definition at line 683 of file legacy-folding-api.c.
References check(), f, fold_real32_cos(), r, unwrap_f(), wrap_f(), x, and y.
xfdiv()
void xfdiv (IEEE32 f1, IEEE32 f2, IEEE32 * r)
Definition at line 625 of file legacy-folding-api.c.
References check(), f2, fold_real32_divide(), r, unwrap_f(), wrap_f(), x, y, and z.
Referenced by _fdiv(), addarth(), and eval_mod().
xfexp()
void xfexp (IEEE32 f, IEEE32 * r)
Definition at line 738 of file legacy-folding-api.c.
References check(), f, fold_real32_exp(), r, unwrap_f(), wrap_f(), x, and y.
xffixu()
void xffixu (IEEE32 f, UINT * r)
Definition at line 520 of file legacy-folding-api.c.
References f, and xfixu().
xffloat()
void xffloat (INT i, IEEE32 * f)
Definition at line 548 of file legacy-folding-api.c.
References check(), f, fold_real32_from_int64(), i, wrap_f(), and x.
Referenced by addarth(), cngcon(), and convert_cnst().
xffloatu()
void xffloatu (UINT i, IEEE32 * r)
Definition at line 557 of file legacy-folding-api.c.
References check(), f, fold_real32_from_int64(), wrap_f(), and x.
Referenced by addarth().
xfisint()
int xfisint (IEEE32 f, int * r)
Definition at line 774 of file legacy-folding-api.c.
References check(), f, FOLD_EQ, fold_int32_from_real32(), fold_real32_compare(), fold_real32_from_int64(), i, k, unwrap_f(), x, and y.
Referenced by addarth(), and chkopnds().
xfix()
void xfix (IEEE32 f, INT * i)
Definition at line 504 of file legacy-folding-api.c.
References check(), f, fold_int32_from_real32(), i, unwrap_f(), and x.
Referenced by addarth(), cngcon(), and convert_cnst().
xfix64()
void xfix64 (IEEE32 f, DBLINT64 i)
Definition at line 526 of file legacy-folding-api.c.
References check(), f, fold_int64_from_real32(), unwrap_f(), wrap_l(), x, and y.
Referenced by addarth(), cngcon(), and convert_cnst().
xfixu()
void xfixu (IEEE32 f, UINT * r)
Definition at line 512 of file legacy-folding-api.c.
References check(), f, fold_uint32_from_real32(), unwrap_f(), and x.
Referenced by addarth(), and xffixu().
xfixu64()
void xfixu64 (IEEE32 f, DBLUINT64 i)
Definition at line 536 of file legacy-folding-api.c.
References check(), f, fold_int64_from_real32(), unwrap_f(), wrap_u(), x, and y.
xflog()
void xflog (IEEE32 f, IEEE32 * r)
Definition at line 747 of file legacy-folding-api.c.
References check(), f, fold_real32_log(), r, unwrap_f(), wrap_f(), x, and y.
xflog10()
void xflog10 (IEEE32 f, IEEE32 * r)
Definition at line 756 of file legacy-folding-api.c.
References check(), f, fold_real32_log10(), r, unwrap_f(), wrap_f(), x, and y.
xflt64()
void xflt64 (DBLINT64 i, IEEE32 * f)
Definition at line 566 of file legacy-folding-api.c.
References check(), f, fold_real32_from_int64(), unwrap_l(), wrap_f(), x, and y.
Referenced by addarth(), cngcon(), and convert_cnst().
xfltu64()
void xfltu64 (DBLUINT64 i, IEEE32 * f)
Definition at line 576 of file legacy-folding-api.c.
References check(), f, fold_real32_from_uint64(), unwrap_u(), wrap_f(), x, and y.
Referenced by addarth().
xfmul()
void xfmul (IEEE32 f1, IEEE32 f2, IEEE32 * r)
Definition at line 615 of file legacy-folding-api.c.
References check(), f2, fold_real32_multiply(), r, unwrap_f(), wrap_f(), x, y, and z.
Referenced by _fdiv(), _xtok(), addarth(), const_fold(), eval_abs(), eval_mod(), eval_scale(), and init_fold_const().
xfneg()
void xfneg (IEEE32 f1, IEEE32 * r)
Definition at line 606 of file legacy-folding-api.c.
References check(), f, fold_real32_negate(), r, unwrap_f(), wrap_f(), x, and y.
Referenced by add_fp_constants(), addarth(), init_negate_const(), negate_const(), negate_const_be(), ref_intrin(), and sym_init().
xfpow()
void xfpow (IEEE32 f1, IEEE32 f2, IEEE32 * r)
Definition at line 664 of file legacy-folding-api.c.
References check(), f2, fold_real32_pow(), r, unwrap_f(), wrap_f(), x, y, and z.
Referenced by const_fold(), and init_fold_const().
xfrcp()
void xfrcp (IEEE32 f, IEEE32 * recip)
Definition at line 635 of file legacy-folding-api.c.
References check(), f, fold_real32_divide(), fold_real32_from_int64(), one, r, unwrap_f(), wrap_f(), x, and y.
Referenced by _fdiv().
xfsin()
void xfsin (IEEE32 f, IEEE32 * r)
Definition at line 674 of file legacy-folding-api.c.
References check(), f, fold_real32_sin(), r, unwrap_f(), wrap_f(), x, and y.
xfsqrt()
void xfsqrt (IEEE32 f, IEEE32 * r)
Definition at line 655 of file legacy-folding-api.c.
References check(), f, fold_real32_sqrt(), r, unwrap_f(), wrap_f(), x, and y.
Referenced by addarth(), eval_abs(), and eval_sqrt().
xfsub()
void xfsub (IEEE32 f1, IEEE32 f2, IEEE32 * r)
Definition at line 596 of file legacy-folding-api.c.
References check(), f2, fold_real32_subtract(), r, unwrap_f(), wrap_f(), x, y, and z.
Referenced by _xtok(), addarth(), const_fold(), eval_mod(), eval_nint(), init_fold_const(), ref_intrin(), and ref_pd().
xftan()
void xftan (IEEE32 f, IEEE32 * r)
Definition at line 692 of file legacy-folding-api.c.
References check(), f, fold_real32_tan(), r, unwrap_f(), wrap_f(), x, and y.
xftodd()
void xftodd (IEEE32 d, IEEE6464 r)
xftoe()
void xftoe (IEEE32 d, IEEE80 r)
xftoq()
void xftoq (IEEE32 d, IEEE128 r)
Definition at line 1982 of file legacy-folding-api.c.
References check(), f, fold_real128_from_real32(), q, unwrap_f(), wrap_q(), x, and y.
Referenced by check_ccon(), cngcon(), and convert_cnst().
xmdtod()
void xmdtod (double md, IEEE64 d)
Definition at line 133 of file legacy-folding-api.c.
References d, and wrap_d().
Referenced by gen_abs_expr(), and gen_llvm_expr().
xmqtoq()
void xmqtoq (long double mq, IEEE128 q)
Referenced by gen_llvm_expr().
xor64()
void xor64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 344 of file legacy-folding-api.c.
References res, result, unwrap_l(), and wrap_l().
Referenced by binop(), ref_intrin(), and ref_pd().
xqabsv()
void xqabsv (IEEE128 f, IEEE128 r)
Definition at line 2071 of file legacy-folding-api.c.
References check(), fold_real128_abs(), q, r, unwrap_q(), wrap_q(), x, and y.
Referenced by addarth(), eval_abs(), and ref_intrin().
xqacos()
void xqacos (IEEE128 q, IEEE128 r)
Definition at line 2135 of file legacy-folding-api.c.
References check(), fold_real128_acos(), q, r, unwrap_q(), wrap_q(), x, and y.
xqadd()
void xqadd (IEEE128 q1, IEEE128 q2, IEEE128 r)
Definition at line 2022 of file legacy-folding-api.c.
References check(), fold_real128_add(), r, unwrap_q(), wrap_q(), x, y, and z.
Referenced by _xtok(), addarth(), const_fold(), and init_fold_const().
xqasin()
void xqasin (IEEE128 q, IEEE128 r)
Definition at line 2126 of file legacy-folding-api.c.
References check(), fold_real128_asin(), q, r, unwrap_q(), wrap_q(), x, and y.
xqatan()
void xqatan (IEEE128 q, IEEE128 r)
Definition at line 2144 of file legacy-folding-api.c.
References check(), fold_real128_atan(), q, r, unwrap_q(), wrap_q(), x, and y.
Referenced by addarth().
xqatan2()
void xqatan2 (IEEE128 q1, IEEE128 q2, IEEE128 r)
Definition at line 2153 of file legacy-folding-api.c.
References check(), fold_real128_atan2(), r, unwrap_q(), wrap_q(), x, y, and z.
Referenced by addarth().
xqcmp()
int xqcmp (IEEE128 q1, IEEE128 q2)
Definition at line 2190 of file legacy-folding-api.c.
References fold_real128_compare(), unwrap_q(), y, and z.
Referenced by const_fold(), and init_fold_const().
xqcos()
void xqcos (IEEE128 q, IEEE128 r)
Definition at line 2108 of file legacy-folding-api.c.
References check(), fold_real128_cos(), q, r, unwrap_q(), wrap_q(), x, and y.
xqdiv()
void xqdiv (IEEE128 q1, IEEE128 q2, IEEE128 r)
Definition at line 2061 of file legacy-folding-api.c.
References check(), fold_real128_divide(), r, unwrap_q(), wrap_q(), x, y, and z.
Referenced by const_fold(), eval_mod(), and init_fold_const().
xqexp()
void xqexp (IEEE128 q, IEEE128 r)
Definition at line 2163 of file legacy-folding-api.c.
References check(), fold_real128_exp(), q, r, unwrap_q(), wrap_q(), x, and y.
xqfix()
void xqfix (IEEE128 q, INT * i)
Definition at line 1908 of file legacy-folding-api.c.
References check(), fold_int32_from_real128(), i, q, unwrap_q(), and y.
Referenced by cngcon(), and convert_cnst().
xqfix64()
void xqfix64 (IEEE128 q, DBLINT64 i)
Definition at line 1924 of file legacy-folding-api.c.
References check(), fold_int64_from_real128(), q, unwrap_q(), wrap_l(), x, and y.
Referenced by cngcon(), and convert_cnst().
xqfixu()
void xqfixu (IEEE128 q, UINT * r)
Definition at line 1916 of file legacy-folding-api.c.
References check(), fold_uint32_from_real128(), q, unwrap_q(), and y.
xqfixu64()
void xqfixu64 (IEEE128 q, DBLUINT64 i)
Definition at line 1934 of file legacy-folding-api.c.
References check(), fold_uint64_from_real128(), q, unwrap_q(), wrap_u(), x, and y.
xqfloat()
void xqfloat (INT i, IEEE128 q)
Definition at line 1954 of file legacy-folding-api.c.
References check(), fold_real128_from_int64(), i, q, wrap_q(), and x.
Referenced by cngcon(), and convert_cnst().
xqfloatu()
void xqfloatu (UINT i, IEEE128 r)
Definition at line 1963 of file legacy-folding-api.c.
References check(), fold_real128_from_int64(), q, wrap_q(), and x.
xqflt64()
void xqflt64 (DBLINT64 i, IEEE128 q)
Definition at line 1944 of file legacy-folding-api.c.
References check(), fold_real128_from_int64(), q, unwrap_l(), wrap_q(), x, and y.
Referenced by cngcon(), and convert_cnst().
xqfltu64()
void xqfltu64 (DBLUINT64 i, IEEE128 q)
Definition at line 1972 of file legacy-folding-api.c.
References check(), fold_real128_from_uint64(), q, unwrap_u(), wrap_q(), x, and y.
xqisint()
int xqisint (IEEE128 q, int * r)
Referenced by addarth(), and chkopnds().
xqlog()
void xqlog (IEEE128 q, IEEE128 r)
Definition at line 2172 of file legacy-folding-api.c.
References check(), fold_real128_log(), q, r, unwrap_q(), wrap_q(), x, and y.
xqlog10()
void xqlog10 (IEEE128 q, IEEE128 r)
Definition at line 2181 of file legacy-folding-api.c.
References check(), fold_real128_log10(), q, r, unwrap_q(), wrap_q(), x, and y.
xqmul()
void xqmul (IEEE128 q1, IEEE128 q2, IEEE128 r)
Definition at line 2051 of file legacy-folding-api.c.
References check(), fold_real128_multiply(), r, unwrap_q(), wrap_q(), x, y, and z.
Referenced by _xtok(), const_fold(), eval_mod(), eval_scale(), and init_fold_const().
xqneg()
void xqneg (IEEE128 q1, IEEE128 r)
Definition at line 2042 of file legacy-folding-api.c.
References check(), fold_real128_negate(), q, r, unwrap_q(), wrap_q(), x, and y.
Referenced by add_fp_constants(), addarth(), init_negate_const(), negate_const(), and negate_const_be().
xqpow()
void xqpow (IEEE128 q1, IEEE128 q2, IEEE128 r)
Definition at line 2089 of file legacy-folding-api.c.
References check(), fold_real128_pow(), r, unwrap_q(), wrap_q(), x, y, and z.
Referenced by const_fold(), and init_fold_const().
xqsin()
void xqsin (IEEE128 q, IEEE128 r)
Definition at line 2099 of file legacy-folding-api.c.
References check(), fold_real128_sin(), q, r, unwrap_q(), wrap_q(), x, and y.
xqsqrt()
void xqsqrt (IEEE128 f, IEEE128 r)
Definition at line 2080 of file legacy-folding-api.c.
References check(), fold_real128_sqrt(), q, r, unwrap_q(), wrap_q(), x, and y.
Referenced by addarth(), and eval_sqrt().
xqsub()
void xqsub (IEEE128 q1, IEEE128 q2, IEEE128 r)
Definition at line 2032 of file legacy-folding-api.c.
References check(), fold_real128_subtract(), r, unwrap_q(), wrap_q(), x, y, and z.
Referenced by _xtok(), addarth(), const_fold(), eval_mod(), and init_fold_const().
xqtan()
void xqtan (IEEE128 q, IEEE128 r)
Definition at line 2117 of file legacy-folding-api.c.
References check(), fold_real128_tan(), q, r, unwrap_q(), wrap_q(), x, and y.
xqtod()
void xqtod (IEEE128 q, IEEE64 r)
Definition at line 2012 of file legacy-folding-api.c.
References check(), d, fold_real64_from_real128(), q, unwrap_q(), wrap_d(), x, and y.
Referenced by cngcon(), and convert_cnst().
xqtodd()
void xqtodd (IEEE128 q, IEEE6464 r)
xqtoe()
void xqtoe (IEEE128 q, IEEE80 r)
xqtof()
void xqtof (IEEE128 q, IEEE32 * r)
Definition at line 2002 of file legacy-folding-api.c.
References check(), fold_real32_from_real128(), q, r, unwrap_q(), wrap_f(), x, and y.
Referenced by cngcon(), and convert_cnst().
xsngl()
void xsngl (IEEE64 d, IEEE32 * r)
Definition at line 952 of file legacy-folding-api.c.
References check(), d, fold_real32_from_real64(), r, unwrap_d(), wrap_f(), x, and y.
Referenced by addarth(), cngcon(), and convert_cnst().
xucmp()
int xucmp (INT a, INT b)
Definition at line 2271 of file legacy-folding-api.c.
References a, b, sa, and sb.
Referenced by addarth(), addbran(), and const_fold().
xudiv()
int xudiv (UINT n, UINT d, UINT * r)
Definition at line 2252 of file legacy-folding-api.c.
References d, n, and r.
Referenced by addarth().
xumod()
int xumod (UINT n, UINT d, UINT * r)
Definition at line 2261 of file legacy-folding-api.c.
References d, n, and r.
Referenced by addarth().