flang: hash.c File Reference
lib/ADT/hash.c File Reference
Open addressing, quadratically probed hash tables.
#include "flang/ADT/hash.h"
#include "flang/Error/pgerror.h"
#include <stdlib.h>
#include <string.h>
Classes
struct hashset_
struct hashmap_
A hashmap adds a table of data pointers after the hashset table.
Macros
#define ERASED (hash_key_t) ~0UL
#define ISKEY(k) ((k) != NULL && (k) != ERASED)
#define DTABLE(h) (((h)->table + 1) + (h)->mask)
#define NEED_REHASH(h) ((h)->entries + (h)->erased >= (h)->mask - (h)->mask / 8)
#define MINSIZE 16
Functions
static unsigned search (hashset_t h, hash_key_t key)
Search for key, return index that terminated the search.
static unsigned insertion_point (hashset_t h, hash_key_t key)
Find insertion point for key.
static unsigned mask_for_entries (unsigned n)
static void alloc_tables (hashset_t h, int with_dtable)
static void rehash (hashset_t h, int with_dtable)
hashset_t hashset_alloc (hash_functions_t f)
Allocate a hashset which uses the provided functions to interpret keys.
hashmap_t hashmap_alloc (hash_functions_t f)
Allocate a hashmap.
void hashset_free (hashset_t h)
Free all memory used by a hashset.
void hashmap_free (hashmap_t h)
Free all memory used by a hashmap.
void hashset_clear (hashset_t h)
Erase all keys in the set.
void hashmap_clear (hashmap_t h)
Erase all (key, data) entries in the map.
unsigned hashset_size (hashset_t h)
Get the number of keys in the set.
unsigned hashmap_size (hashmap_t h)
Return the number of (key, data) pairs in the map.
hash_key_t hashset_lookup (hashset_t h, hash_key_t key)
Look up a key and return the equivalent stored key, or NULL.
hash_key_t hashmap_lookup (hashmap_t h, hash_key_t key, hash_data_t *data)
Look up a key and return the equivalent stored key, or NULL.
void hashset_insert (hashset_t h, hash_key_t key)
Insert a new key.
void hashmap_insert (hashmap_t h, hash_key_t key, hash_data_t data)
Insert a new (key, data) pair.
hash_key_t hashset_replace (hashset_t h, hash_key_t key)
Insert a new key or replace an existing key.
hash_key_t hashmap_replace (hashmap_t h, hash_key_t key, hash_data_t *data)
Insert or replace a (key, data) pair.
hash_key_t hashset_erase (hashset_t h, hash_key_t key)
Erase a key from the set and return it.
hash_key_t hashmap_erase (hashmap_t h, hash_key_t key, hash_data_t *data)
Erase a key from the map and return it.
void hashset_iterate (hashset_t h, void(*f)(hash_key_t, void *context), void *context)
Call f with every key in the hash set.
void hashmap_iterate (hashmap_t h, void(*f)(hash_key_t, hash_data_t, void *context), void *context)
Call f with every (key, data) pair in the hash map.
static hash_value_t string_hash (hash_key_t key)
static int string_equals (hash_key_t a, hash_key_t b)
static hash_value_t direct_hash (hash_key_t key)
Variables
const hash_functions_t hash_functions_strings = {string_hash, string_equals}
Predefined hash functions for strings.
const hash_functions_t hash_functions_direct = {direct_hash, NULL}
Predefined hash functions for directly hashed keys.
Detailed Description
Open addressing, quadratically probed hash tables.
All keys are kept in a single array with 2^n entries. A key is first looked up at index hash(k) mod 2^k, then following a quadratic sequence of offsets. The quadratic probing has decent locality of reference for the first few probes.
The search terminates when the key is found or a NULL is encountered. A special ERASED marker is used to avoid severing probe sequences when erasing keys.
Definition in file lib/ADT/hash.c.
Macro Definition Documentation
DTABLE
#define DTABLE (h) (((h)->table + 1) + (h)->mask)
Definition at line 55 of file lib/ADT/hash.c.
ERASED
#define ERASED (hash_key_t) ~0UL
Definition at line 33 of file lib/ADT/hash.c.
ISKEY
#define ISKEY (k) ((k) != NULL && (k) != ERASED)
Definition at line 34 of file lib/ADT/hash.c.
MINSIZE
#define MINSIZE 16
Definition at line 145 of file lib/ADT/hash.c.
NEED_REHASH
#define NEED_REHASH (h) ((h)->entries + (h)->erased >= (h)->mask - (h)->mask / 8)
Definition at line 144 of file lib/ADT/hash.c.
Function Documentation
alloc_tables()
static void alloc_tables (hashset_t h, int with_dtable) static
Definition at line 167 of file lib/ADT/hash.c.
References h, and mask_for_entries().
Referenced by hashmap_alloc(), hashmap_clear(), hashset_alloc(), hashset_clear(), and rehash().
direct_hash()
static hash_value_t direct_hash (hash_key_t key) static
Definition at line 445 of file lib/ADT/hash.c.
References HASH_ACCU_ADD, HASH_ACCU_FINISH, HASH_ACCU_INIT, HASH_ACCU_VALUE, and k.
hashmap_alloc()
hashmap_t hashmap_alloc (hash_functions_t f)
Allocate a hashmap.
The returned handle must be freed with hashmap_free().
Definition at line 222 of file lib/ADT/hash.c.
hashmap_clear()
void hashmap_clear (hashmap_t h)
Erase all (key, data) entries in the map.
Definition at line 255 of file lib/ADT/hash.c.
hashmap_erase()
hash_key_t hashmap_erase (hashmap_t h, hash_key_t key, hash_data_t * data)
Erase a key from the map and return it.
If a (key, data) pair was erased and data is not NULL, update *data with the erased data value.
If no key was erased, return NULL and leave *data unchanged.
Definition at line 380 of file lib/ADT/hash.c.
hashmap_free()
void hashmap_free (hashmap_t h)
Free all memory used by a hashmap.
Note that any memory referenced by keys and data pointers in the map is not freed.
Definition at line 239 of file lib/ADT/hash.c.
hashmap_insert()
void hashmap_insert (hashmap_t h, hash_key_t key, hash_data_t data)
Insert a new (key, data) pair.
This function assumes that no equivalent key is present in the map, i.e. hashmap_lookup() would return NULL.
Use hashmap_replace() if an equivalent key may exist in the map already.
Definition at line 310 of file lib/ADT/hash.c.
Referenced by hashmap_replace().
hashmap_iterate()
void hashmap_iterate (hashmap_t h, void(*)(hash_key_t, hash_data_t, void *context) f, void * context)
Call f with every (key, data) pair in the hash map.
The function f must not modify the hash table.
Definition at line 410 of file lib/ADT/hash.c.
hashmap_lookup()
hash_key_t hashmap_lookup (hashmap_t h, hash_key_t key, hash_data_t * data)
Look up a key and return the equivalent stored key, or NULL.
If if a key was found and data is not NULL, *data will be set to the corresponding data value, otherwise it is not changed.
Definition at line 281 of file lib/ADT/hash.c.
Referenced by hashmap_insert().
hashmap_replace()
hash_key_t hashmap_replace (hashmap_t h, hash_key_t key, hash_data_t * data)
Insert or replace a (key, data) pair.
If an equivalent key already exists, replace it with the new key and *data, and return the old key. On return, *data is set to the old data.
If no equivalent key is present, insert the new key and *data and return NULL. The *data value is not updated.
Definition at line 345 of file lib/ADT/hash.c.
hashmap_size()
unsigned hashmap_size (hashmap_t h)
Return the number of (key, data) pairs in the map.
Definition at line 269 of file lib/ADT/hash.c.
hashset_alloc()
hashset_t hashset_alloc (hash_functions_t f)
Allocate a hashset which uses the provided functions to interpret keys.
The returned hashset_t handle should be passed to hashset_free() to deallocate memory.
Definition at line 213 of file lib/ADT/hash.c.
hashset_clear()
void hashset_clear (hashset_t h)
Erase all keys in the set.
Definition at line 247 of file lib/ADT/hash.c.
hashset_erase()
hash_key_t hashset_erase (hashset_t h, hash_key_t key)
Erase a key from the set and return it.
Return NULL if no equivalent key was found.
Definition at line 365 of file lib/ADT/hash.c.
hashset_free()
void hashset_free (hashset_t h)
Free all memory used by a hashset.
Note that any memory referenced by keys in the set is not freed.
Definition at line 231 of file lib/ADT/hash.c.
hashset_insert()
void hashset_insert (hashset_t h, hash_key_t key)
Insert a new key.
Note that this function assumes that no equivalent key is present in the set, i.e. hashset_lookup() would return false.
Use hashset_replace() if an equivalent key may be in the set already.
The key cannot be NULL or (hash_key_t)~0UL.
Definition at line 291 of file lib/ADT/hash.c.
Referenced by hashset_replace().
hashset_iterate()
void hashset_iterate (hashset_t h, void(*)(hash_key_t, void *context) f, void * context)
Call f with every key in the hash set.
Note that the iteration order is a function of both the hash function and the sequence of hashset_* calls leading up to this one. If pointers are directly hashed, address space layout randomization can cause different iteration orders in otherwise identical executions.
The function f must not modify the hash table.
Definition at line 397 of file lib/ADT/hash.c.
hashset_lookup()
hash_key_t hashset_lookup (hashset_t h, hash_key_t key)
Look up a key and return the equivalent stored key, or NULL.
Definition at line 275 of file lib/ADT/hash.c.
Referenced by hashset_insert().
hashset_replace()
hash_key_t hashset_replace (hashset_t h, hash_key_t key)
Insert a new key or replace an existing key.
If an equivalent key already exists, replace it with the new key and return the old one. If no equivalent key is in the set, insert the new key and return NULL.
Definition at line 330 of file lib/ADT/hash.c.
hashset_size()
unsigned hashset_size (hashset_t h)
Get the number of keys in the set.
Definition at line 263 of file lib/ADT/hash.c.
insertion_point()
static unsigned insertion_point (hashset_t h, hash_key_t key) static
Find insertion point for key.
Definition at line 122 of file lib/ADT/hash.c.
References assert, ERR_Fatal, h, HKEY2INT, ISKEY, p, and s.
Referenced by hashmap_insert(), hashset_insert(), and rehash().
mask_for_entries()
static unsigned mask_for_entries (unsigned n) static
Definition at line 148 of file lib/ADT/hash.c.
References assert, ERR_Fatal, m, MINSIZE, and n.
Referenced by alloc_tables().
rehash()
static void rehash (hashset_t h, int with_dtable) static
Definition at line 186 of file lib/ADT/hash.c.
References alloc_tables(), DTABLE, h, i, insertion_point(), ISKEY, n, and NULL.
Referenced by hashmap_insert(), and hashset_insert().
search()
static unsigned search (hashset_t h, hash_key_t key) static
Search for key, return index that terminated the search.
Definition at line 92 of file lib/ADT/hash.c.
References assert, ERASED, ERR_Fatal, h, HKEY2INT, ISKEY, p, and s.
Referenced by hashmap_erase(), hashmap_lookup(), hashmap_replace(), hashset_erase(), hashset_lookup(), and hashset_replace().
string_equals()
static int string_equals (hash_key_t a, hash_key_t b) static
Definition at line 436 of file lib/ADT/hash.c.
References a, and b.
string_hash()
static hash_value_t string_hash (hash_key_t key) static
Definition at line 425 of file lib/ADT/hash.c.
References HASH_ACCU_ADD, HASH_ACCU_FINISH, HASH_ACCU_INIT, HASH_ACCU_VALUE, and p.
Variable Documentation
hash_functions_direct
const hash_functions_t hash_functions_direct = {direct_hash, NULL}
Predefined hash functions for directly hashed keys.
The pointers are compared by value with no indirection. These hash functions can also be used for integer keys. Just cast the integers to hash_key_t.
Definition at line 459 of file lib/ADT/hash.c.
hash_functions_strings
const hash_functions_t hash_functions_strings = {string_hash, string_equals}
Predefined hash functions for strings.
The hash keys are interpreted as pointers to NUL-terminated strings.
Definition at line 441 of file lib/ADT/hash.c.