flang: libm_amd.h File Reference
libm_amd.h File Reference
#include <math.h>
Classes
struct _complex
Macros
#define weak_alias(name, aliasname) _weak_alias(name, aliasname)
#define _weak_alias(name, aliasname) extern __typeof(name) aliasname __attribute__((weak, alias(#name)));
#define _concat3(l, m, r) l##m##r
#define concat3(l, m, r) _concat3(l,m,r)
#define FN_PROTO_SUFFIX
#define FN_PROTOTYPE(fname) concat3(__, fname,FN_PROTO_SUFFIX)
#define _COMPLEX_DEFINED
#define COMPLEX struct _complex
Typedefs
typedef long __INT8_T
typedef unsigned long __UINT8_T
Functions
double FN_PROTOTYPE() mth_i_dexp2 (double x)
double FN_PROTOTYPE() mth_i_dlog2 (double x)
double acos (double x)
float acosf (float x)
double asin (double x)
float asinf (float x)
double atan (double x)
float atanf (float x)
double atan2 (double x, double y)
float atan2f (float x, float y)
double ceil (double x)
float ceilf (float x)
double chgsign (double x)
float chgsignf (float x)
double copysign (double x, double y)
float copysignf (float x, float y)
double cos (double x)
float cosf (float x)
double cosh (double x)
float coshf (float x)
double exp (double x)
float expf (float x)
float exp2f (float x)
double exp10 (double x)
float exp10f (float x)
double fdim (double x, double y)
float fdimf (float x, float y)
int finite (double x)
int finitef (float x)
double floor (double x)
float floorf (float x)
double fma (double x, double y, double z)
float fmaf (float x, float y, float z)
double fmax (double x, double y)
float fmaxf (float x, float y)
double fmin (double x, double y)
float fminf (float x, float y)
double fmod (double x, double y)
float fmodf (float x, float y)
double hypot (double x, double y)
float hypotf (float x, float y)
double ldexp (double x, int exp)
float ldexpf (float x, int exp)
double log (double x)
float logf (float x)
float log2f (float x)
double log10 (double x)
float log10f (float x)
double logb (double x)
float logbf (float x)
double modf (double x, double *iptr)
float modff (float x, float *iptr)
double nextafter (double x, double y)
float nextafterf (float x, float y)
double pow (double x, double y)
float powf (float x, float y)
double pow10 (double x)
float pow10f (float x)
double remainder (double x, double y)
float remainderf (float x, float y)
void __remainder_piby2 (double x, double *r, double *rr, int *region)
void __remainder_piby2f (float x, double *r, int *region)
double sin (double x)
float sinf (float x)
void sincos (double x, double *s, double *c)
void sincosf (float x, float *s, float *c)
double sinh (double x)
float sinhf (float x)
double sqrt (double x)
float sqrtf (float x)
double tan (double x)
float tanf (float x)
double tanh (double x)
float tanhf (float x)
double trunc (double x)
float truncf (float x)
Macro Definition Documentation
_COMPLEX_DEFINED
#define _COMPLEX_DEFINED
Definition at line 100 of file libm_amd.h.
_concat3
#define _concat3 (l, m, r) l##m##r
Definition at line 62 of file libm_amd.h.
_weak_alias
#define _weak_alias (name, aliasname) extern __typeof(name) aliasname __attribute__((weak, alias(#name)));
Definition at line 51 of file libm_amd.h.
COMPLEX
#define COMPLEX struct _complex
Definition at line 103 of file libm_amd.h.
concat3
#define concat3 (l, m, r) _concat3(l,m,r)
Definition at line 63 of file libm_amd.h.
FN_PROTO_SUFFIX
#define FN_PROTO_SUFFIX
Definition at line 65 of file libm_amd.h.
FN_PROTOTYPE
#define FN_PROTOTYPE (fname) concat3(__, fname,FN_PROTO_SUFFIX)
Definition at line 67 of file libm_amd.h.
weak_alias
#define weak_alias (name, aliasname) _weak_alias(name, aliasname)
Definition at line 50 of file libm_amd.h.
Typedef Documentation
__INT8_T
typedef long __INT8_T
Definition at line 72 of file libm_amd.h.
__UINT8_T
typedef unsigned long __UINT8_T
Definition at line 73 of file libm_amd.h.
Function Documentation
__remainder_piby2()
void __remainder_piby2 (double x, double * r, double * rr, int * region)
__remainder_piby2f()
void __remainder_piby2f (float x, double * r, int * region)
acos()
double acos (double x)
Referenced by __mth_i_dacos(), __mth_i_dacosd(), and fold_real64_acos().
acosf()
float acosf (float x)
Referenced by __mth_i_acos(), __mth_i_acosd(), and fold_real32_acos().
asin()
double asin (double x)
Referenced by __mth_i_dasin(), __mth_i_dasind(), and fold_real64_asin().
asinf()
float asinf (float x)
Referenced by __mth_i_asin(), __mth_i_asind(), and fold_real32_asin().
atan()
double atan (double x)
Referenced by __mth_i_datan(), __mth_i_datand(), and fold_real64_atan().
atan2()
double atan2 (double x, double y)
Referenced by __mth_i_datan2(), __mth_i_datan2d(), fold_real64_atan2(), and ZMPLXFUNC_Z_Z().
atan2f()
float atan2f (float x, float y)
Referenced by __mth_i_atan2(), __mth_i_atan2d(), CMPLXFUNC_C(), CMPLXFUNC_C_C(), and fold_real32_atan2().
atanf()
float atanf (float x)
Referenced by __mth_i_atan(), __mth_i_atand(), and fold_real32_atan().
ceil()
double ceil (double x)
Referenced by __mth_i_dceil().
ceilf()
float ceilf (float x)
Referenced by __mth_i_ceil().
chgsign()
double chgsign (double x)
chgsignf()
float chgsignf (float x)
copysign()
double copysign (double x, double y)
Referenced by __attribute__(), atan2_d_scalar(), atan2_scalar(), cexp_scalar_default_abi(), and ZMPLXFUNC_Z().
copysignf()
float copysignf (float x, float y)
Referenced by __attribute__(), atan2_scalar(), and CMPLXFUNC_C().
cos()
double cos (double x)
Referenced by __mth_i_dcos(), __mth_i_dcosd(), fold_real64_cos(), ZMPLXFUNC_Z(), and ZMPLXFUNC_Z_Z().
cosf()
float cosf (float x)
Referenced by __mth_i_cos(), __mth_i_cosd(), CMPLXFUNC_C(), CMPLXFUNC_C_C(), and fold_real32_cos().
cosh()
double cosh (double x)
Referenced by __mth_i_dcosh(), and ZMPLXFUNC_Z().
coshf()
float coshf (float x)
Referenced by __mth_i_cosh(), and CMPLXFUNC_C().
exp()
double exp (double x)
exp10()
double exp10 (double x)
Referenced by ufptosci().
exp10f()
float exp10f (float x)
exp2f()
float exp2f (float x)
expf()
float expf (float x)
Referenced by __mth_i_exp(), CMPLXFUNC_C(), CMPLXFUNC_C_C(), and fold_real32_exp().
fdim()
double fdim (double x, double y)
fdimf()
float fdimf (float x, float y)
finite()
int finite (double x)
finitef()
int finitef (float x)
floor()
double floor (double x)
Referenced by __mth_i_dfloor().
floorf()
float floorf (float x)
Referenced by __mth_i_floor().
fma()
double fma (double x, double y, double z)
Referenced by __attribute__(), __exp_d_scalar_kernel(), fast2mul_dp(), and maybe_generate_fma().
fmaf()
float fmaf (float x, float y, float z)
Referenced by __attribute__(), __exp_poly(), and __exp_scalar_kernel().
fmax()
double fmax (double x, double y)
fmaxf()
float fmaxf (float x, float y)
fmin()
double fmin (double x, double y)
Referenced by vrs_set_arg().
fminf()
float fminf (float x, float y)
fmod()
double fmod (double x, double y)
Referenced by __mth_i_dmod(), __mth_i_dtand(), and ENTF90().
fmodf()
float fmodf (float x, float y)
Referenced by __mth_i_amod(), and __mth_i_tand().
hypot()
double hypot (double x, double y)
Referenced by __mth_i_dhypot(), DBLFUNC_C(), ZMPLXFUNC_Z(), and ZMPLXFUNC_Z_Z().
hypotf()
float hypotf (float x, float y)
Referenced by __mth_i_hypot(), CMPLXFUNC_C(), CMPLXFUNC_C_C(), and FLTFUNC_C().
ldexp()
double ldexp (double x, int exp)
ldexpf()
float ldexpf (float x, int exp)
log()
double log (double x)
Referenced by __mth_i_dlog(), fold_real64_log(), ZMPLXFUNC_Z(), and ZMPLXFUNC_Z_Z().
log10()
double log10 (double x)
Referenced by __mth_i_dlog10(), and fold_real64_log10().
log10f()
float log10f (float x)
Referenced by __mth_i_alog10(), __mth_i_log10(), and fold_real32_log10().
log2f()
float log2f (float x)
logb()
double logb (double x)
logbf()
float logbf (float x)
logf()
float logf (float x)
Referenced by __mth_i_alog(), __mth_i_log(), CMPLXFUNC_C(), CMPLXFUNC_C_C(), and fold_real32_log().
modf()
double modf (double x, double * iptr)
Referenced by __mth_i_dnint(), and cvt().
modff()
float modff (float x, float * iptr)
Referenced by __mth_i_anint().
mth_i_dexp2()
double FN_PROTOTYPE() mth_i_dexp2 (double x)
Definition at line 74 of file dexp2.c.
References EMAX_DP64, EMIN_DP64, GET_BITS_DP64, m, MANTBITS_DP64, PUT_BITS_DP64, retval_errno_erange_overflow(), retval_errno_erange_underflow(), SIGNBIT_DP64, x, y, y1(), and z.
Referenced by mth_i_rpowr().
mth_i_dlog2()
double FN_PROTOTYPE() mth_i_dlog2 (double x)
Referenced by mth_i_rpowr().
nextafter()
double nextafter (double x, double y)
nextafterf()
float nextafterf (float x, float y)
pow()
double pow (double x, double y)
Referenced by __mth_i_dpowd(), and fold_real64_pow().
pow10()
double pow10 (double x)
pow10f()
float pow10f (float x)
powf()
float powf (float x, float y)
Referenced by __mth_i_rpowr(), and fold_real32_pow().
remainder()
double remainder (double x, double y)
remainderf()
float remainderf (float x, float y)
sin()
double sin (double x)
Referenced by __mth_i_dsin(), __mth_i_dsind(), fold_real64_sin(), ZMPLXFUNC_Z(), and ZMPLXFUNC_Z_Z().
sincos()
void sincos (double x, double * s, double * c)
sincosf()
void sincosf (float x, float * s, float * c)
sinf()
float sinf (float x)
Referenced by __mth_i_sin(), __mth_i_sind(), CMPLXFUNC_C(), CMPLXFUNC_C_C(), and fold_real32_sin().
sinh()
double sinh (double x)
Referenced by __mth_i_dsinh(), and ZMPLXFUNC_Z().
sinhf()
float sinhf (float x)
Referenced by __mth_i_sinh(), and CMPLXFUNC_C().
sqrt()
double sqrt (double x)
Referenced by __fsd_acos_fma3(), __fsd_asin_fma3(), __mth_i_dsqrt(), fold_real64_sqrt(), mth_i_rpowr(), NORM2_REAL4(), NORM2_REAL8(), and ZMPLXFUNC_Z().
sqrtf()
float sqrtf (float x)
Referenced by __fss_acos_fma3(), __fss_asin_fma3(), __mth_i_sqrt(), CMPLXFUNC_C(), and fold_real32_sqrt().
tan()
double tan (double x)
Referenced by __mth_i_dtan(), __mth_i_dtand(), and fold_real64_tan().
tanf()
float tanf (float x)
Referenced by __mth_i_tan(), __mth_i_tand(), and fold_real32_tan().
tanh()
double tanh (double x)
Referenced by __mth_i_dtanh().
tanhf()
float tanhf (float x)
Referenced by __mth_i_tanh().
trunc()
double trunc (double x)
Referenced by __mth_i_derfc_scaled(), and __mth_i_erfc_scaled().
truncf()
float truncf (float x)