flang: fpcvt.c File Reference
libpgmath/lib/common/fpcvt.c File Reference
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
Classes
union ieee
struct UFP
Macros
#define IEEE64_SUBNORMAL(a) (a.v.e == 0 && (a.v.hm != 0L || a.v.lm != 0L))
#define NDIG 25
Typedefs
typedef long INT
typedef unsigned long UINT
typedef double IEEE64
Enumerations
enum VAL {
ZERO , NIL , NORMAL , BIG ,
INFIN , NAN , DIVZ , SUBNORMAL ,
ZERO , NIL , NORMAL , BIG ,
INFIN , NAN , DIVZ , SUBNORMAL ,
ZERO , NIL , NORMAL , BIG ,
INFIN , NAN , DIVZ
}
Functions
static void ui64toa (INT m[2], char *s, int n, int decpl)
static void manshftr (INT m[4], int n)
static void manshftl (register INT m[4], int n)
static void manadd (register INT m1[4], register INT m2[4])
static void manrnd (INT m[4], int bits)
static void manneg (register INT m[4])
static void manmul (register INT m1[4], register INT m2[4])
static void ufpnorm (register UFP *u)
static int ufpdnorm (UFP *u, int bias)
static void ufprnd (UFP *u, int bits)
static void ufpxten (UFP *u, int exp)
static void ufptosci (UFP *u, char *s, int dp, int *decpt, int *sign)
static void dtoufp (IEEE64 d, register UFP *u)
static void ufptod (register UFP *u, IEEE64 *r)
static int atoxi (register char *s, INT *i, int n, int base)
static void atoui64 (char *s, INT m[2], int n, INT *exp)
static void atoxufp (char *s, UFP *u, char **p)
static char * pgio_ecvt (double value, int ndigit, int *decpt, int *sign)
char * __ecvt (double value, int ndigit, int *decpt, int *sign)
char * __fcvt (double v, int prec, int *decpt, int *sign)
Variables
static INT ftab1 [29][3]
static INT ftab2 [25][3]
Macro Definition Documentation
IEEE64_SUBNORMAL
#define IEEE64_SUBNORMAL (a) (a.v.e == 0 && (a.v.hm != 0L || a.v.lm != 0L))
Definition at line 52 of file libpgmath/lib/common/fpcvt.c.
NDIG
#define NDIG 25
Definition at line 708 of file libpgmath/lib/common/fpcvt.c.
Typedef Documentation
IEEE64
typedef double IEEE64
Definition at line 43 of file libpgmath/lib/common/fpcvt.c.
INT
typedef long INT
Definition at line 41 of file libpgmath/lib/common/fpcvt.c.
UINT
typedef unsigned long UINT
Definition at line 42 of file libpgmath/lib/common/fpcvt.c.
Enumeration Type Documentation
VAL
enum VAL
Enumerator
ZERO
NIL
NORMAL
BIG
INFIN
NAN
DIVZ
SUBNORMAL
ZERO
NIL
NORMAL
BIG
INFIN
NAN
DIVZ
SUBNORMAL
ZERO
NIL
NORMAL
BIG
INFIN
NAN
DIVZ
Definition at line 44 of file libpgmath/lib/common/fpcvt.c.
Function Documentation
__ecvt()
char * __ecvt (double value, int ndigit, int * decpt, int * sign)
Definition at line 805 of file libpgmath/lib/common/fpcvt.c.
References buf, carry(), ieee::d, dtoufp(), ieee::e, ecvt(), ieee::hm, i, IEEE64_SUBNORMAL, INFIN, j, ieee::lm, n, NAN, NORMAL, pgio_ecvt(), ieee::s, s, sign, SUBNORMAL, ufptosci(), ieee::v, value(), and ZERO.
Referenced by __fcvt().
__fcvt()
char * __fcvt (double v, int prec, int * decpt, int * sign)
Definition at line 909 of file libpgmath/lib/common/fpcvt.c.
References __ecvt(), i, j, n, p, sign, tmp, and ieee::v.
atoui64()
static void atoui64 (char * s, INT m[2], int n, INT * exp) static
Definition at line 536 of file libpgmath/lib/common/fpcvt.c.
References end, exp, hi, lo, m, n, and s.
Referenced by atoxufp().
atoxi()
static int atoxi (register char * s, INT * i, int n, int base) static
Definition at line 447 of file libpgmath/lib/common/fpcvt.c.
References base, end, i, n, s, sign, and value().
Referenced by atoxufp().
atoxufp()
static void atoxufp (char * s, UFP * u, char ** p) static
Definition at line 585 of file libpgmath/lib/common/fpcvt.c.
References atoui64(), atoxi(), BIG, exp, NORMAL, p, s, sign, start, and ZERO.
dtoufp()
static void dtoufp (IEEE64 d, register UFP * u) static
Definition at line 360 of file libpgmath/lib/common/fpcvt.c.
References d, IEEE64_SUBNORMAL, INFIN, NAN, NORMAL, SUBNORMAL, ieee::v, and ZERO.
Referenced by __ecvt().
manadd()
static void manadd (register INT m1[4], register INT m2[4]) static
Definition at line 129 of file libpgmath/lib/common/fpcvt.c.
References carry(), hi, i, lo, m2, t1, and t2.
Referenced by manneg(), and manrnd().
manmul()
static void manmul (register INT m1[4], register INT m2[4]) static
Definition at line 189 of file libpgmath/lib/common/fpcvt.c.
References carry(), i, j, k, m2, n1, n2, and p.
Referenced by ufpxten().
manneg()
static void manneg (register INT m[4]) static
Definition at line 179 of file libpgmath/lib/common/fpcvt.c.
References i, m, manadd(), and one.
manrnd()
static void manrnd (INT m[4], int bits) static
Definition at line 150 of file libpgmath/lib/common/fpcvt.c.
References bits, m, manadd(), manshftl(), manshftr(), one, and round().
Referenced by ufpdnorm(), ufprnd(), and ufptosci().
manshftl()
static void manshftl (register INT m[4], int n) static
Definition at line 108 of file libpgmath/lib/common/fpcvt.c.
References i, j, m, and n.
Referenced by manrnd(), ufpdnorm(), ufpnorm(), ufptosci(), and ufpxten().
manshftr()
static void manshftr (INT m[4], int n) static
Definition at line 87 of file libpgmath/lib/common/fpcvt.c.
References i, j, m, and n.
Referenced by manrnd(), ufpdnorm(), ufpnorm(), ufptosci(), and ufpxten().
pgio_ecvt()
static char * pgio_ecvt (double value, int ndigit, int * decpt, int * sign) static
Definition at line 721 of file libpgmath/lib/common/fpcvt.c.
References exp, i, num, p, s, sign, and value().
Referenced by __ecvt().
ufpdnorm()
static int ufpdnorm (UFP * u, int bias) static
Definition at line 235 of file libpgmath/lib/common/fpcvt.c.
References manrnd(), manshftl(), and manshftr().
Referenced by ufptod().
ufpnorm()
static void ufpnorm (register UFP * u) static
Definition at line 219 of file libpgmath/lib/common/fpcvt.c.
References manshftl(), and manshftr().
Referenced by ufprnd(), ufptosci(), and ufpxten().
ufprnd()
static void ufprnd (UFP * u, int bits) static
Definition at line 256 of file libpgmath/lib/common/fpcvt.c.
References bits, manrnd(), and ufpnorm().
Referenced by ufptod().
ufptod()
static void ufptod (register UFP * u, IEEE64 * r) static
Definition at line 392 of file libpgmath/lib/common/fpcvt.c.
References BIG, DIVZ, INFIN, NAN, NIL, NORMAL, r, SUBNORMAL, ufpdnorm(), ufprnd(), ieee::v, void(), and ZERO.
ufptosci()
static void ufptosci (UFP * u, char * s, int dp, int * decpt, int * sign) static
Definition at line 319 of file libpgmath/lib/common/fpcvt.c.
References exp10(), INFIN, manrnd(), manshftl(), manshftr(), NAN, s, sign, strlen(), SUBNORMAL, ufpnorm(), ufpxten(), and ui64toa().
Referenced by __ecvt().
ufpxten()
static void ufpxten (UFP * u, int exp) static
Definition at line 298 of file libpgmath/lib/common/fpcvt.c.
References BIG, exp, ftab1, ftab2, i, j, manmul(), manshftl(), manshftr(), NIL, and ufpnorm().
Referenced by ufptosci().
ui64toa()
static void ui64toa (INT m[2], char * s, int n, int decpl) static
Definition at line 54 of file libpgmath/lib/common/fpcvt.c.
References buff, hi, i, j, lo, m, n, and s.
Referenced by ufptosci().
Variable Documentation
ftab1
INT ftab1[29][3] static
Initial value:
= {
    {0xA05C0DD7, 0x0F6E1619, -1162}, {0xA5CED43B, 0x7E3E9188, -1079},
    {0xAB70FE17, 0xC79AC6CA, -996},  {0xB1442798, 0xF49FFB4A, -913},
    {0xB749FAED, 0x14125D36, -830},  {0xBD8430BD, 0x08277231, -747},
    {0xC3F490AA, 0x77BD60FC, -664},  {0xCA9CF1D2, 0x06FDC03B, -581},
    {0xD17F3B51, 0xFCA3A7A0, -498},  {0xD89D64D5, 0x7A607744, -415},
    {0xDFF97724, 0x70297EBD, -332},  {0xE7958CB8, 0x7392C2C2, -249},
    {0xEF73D256, 0xA5C0F77C, -166},  {0xF79687AE, 0xD3EEC551, -83},
    {0x80000000, 0x00000000, 1},     {0x84595161, 0x401484A0, 84},
    {0x88D8762B, 0xF324CD0F, 167},   {0x8D7EB760, 0x70A08AEC, 250},
    {0x924D692C, 0xA61BE758, 333},   {0x9745EB4D, 0x50CE6332, 416},
    {0x9C69A972, 0x84B578D7, 499},   {0xA1BA1BA7, 0x9E1632DC, 582},
    {0xA738C6BE, 0xBB12D16C, 665},   {0xACE73CBF, 0xDC0BFB7B, 748},
    {0xB2C71D5B, 0xCA9023F8, 831},   {0xB8DA1662, 0xE7B00A17, 914},
    {0xBF21E440, 0x03ACDD2C, 997},   {0xC5A05277, 0x621BE293, 1080},
    {0xCC573C2A, 0x0ECCDAA6, 1163},
}
Definition at line 264 of file libpgmath/lib/common/fpcvt.c.
Referenced by ufpxten().
ftab2
INT ftab2[25][3] static
Initial value:
= {
    {0x80000000, 0x00000000, 1},  {0xA0000000, 0x00000000, 4},
    {0xC8000000, 0x00000000, 7},  {0xFA000000, 0x00000000, 10},
    {0x9C400000, 0x00000000, 14}, {0xC3500000, 0x00000000, 17},
    {0xF4240000, 0x00000000, 20}, {0x98968000, 0x00000000, 24},
    {0xBEBC2000, 0x00000000, 27}, {0xEE6B2800, 0x00000000, 30},
    {0x9502F900, 0x00000000, 34}, {0xBA43B740, 0x00000000, 37},
    {0xE8D4A510, 0x00000000, 40}, {0x9184E72A, 0x00000000, 44},
    {0xB5E620F4, 0x80000000, 47}, {0xE35FA931, 0xA0000000, 50},
    {0x8E1BC9BF, 0x04000000, 54}, {0xB1A2BC2E, 0xC5000000, 57},
    {0xDE0B6B3A, 0x76400000, 60}, {0x8AC72304, 0x89E80000, 64},
    {0xAD78EBC5, 0xAC620000, 67}, {0xD8D726B7, 0x177A8000, 70},
    {0x87867832, 0x6EAC9000, 74}, {0xA968163F, 0x0A57B400, 77},
    {0xD3C21BCE, 0xCCEDA100, 80},
}
Definition at line 282 of file libpgmath/lib/common/fpcvt.c.
Referenced by ufpxten().