flang: mthdecls.h File Reference
libpgmath/lib/x86_64/mthdecls.h File Reference
mthdecls.h - Fortran math support (all platforms/targets)
#include <math.h>
#include <complex.h>
Classes
struct cmplx_t
struct dcmplx_t
Macros
#define DEG_TO_RAD 0.174532925199432957692E-1
#define RAD_TO_DEG 0.572957795130823208769E+2
#define CNVRTDEG(degrees) ((degrees)*DEG_TO_RAD)
#define CNVRTRAD(radians) ((radians)*RAD_TO_DEG)
#define PGMATH_CMPLX_CONST(r, i) r + I*i
#define MTHCONCAT___(l, r) l##r
#define MTHCONCAT__(l, r) MTHCONCAT___(l,r)
#define __MTH_C99_CMPLX_SUFFIX _c99
#define FLTFUNC_C_(_f) float _f(float real, float imag)
#define DBLFUNC_C_(_f) double _f(double real, double imag)
#define CMPLXFUNC_C_(_f) void _f(cmplx_t *cmplx, float real, float imag)
#define CMPLXFUNC_C_C_(_f)
#define CMPLXFUNC_C_F_(_f) void _f(cmplx_t *cmplx, float real, float imag, float r)
#define CMPLXFUNC_C_I_(_f) void _f(cmplx_t *cmplx, float real, float imag, int i)
#define CMPLXFUNC_C_K_(_f) void _f(cmplx_t *cmplx, float real, float imag, long long i)
#define ZMPLXFUNC_Z_(_f) void _f(dcmplx_t *dcmplx, double real, double imag)
#define ZMPLXFUNC_Z_Z_(_f)
#define ZMPLXFUNC_Z_D_(_f) void _f(dcmplx_t *dcmplx, double real, double imag, double d)
#define ZMPLXFUNC_Z_I_(_f) void _f(dcmplx_t *dcmplx, double real, double imag, int i)
#define ZMPLXFUNC_Z_K_(_f) void _f(dcmplx_t *dcmplx, double real, double imag, long long i)
#define FLTFUNC_C_C99_(_f)
#define DBLFUNC_C_C99_(_f)
#define CMPLXFUNC_C_C99_(_f)
#define CMPLXFUNC_C_C_C99_(_f)
#define CMPLXFUNC_C_F_C99_(_f)
#define CMPLXFUNC_C_I_C99_(_f)
#define CMPLXFUNC_C_K_C99_(_f)
#define ZMPLXFUNC_Z_C99_(_f)
#define ZMPLXFUNC_Z_Z_C99_(_f)
#define ZMPLXFUNC_Z_D_C99_(_f)
#define ZMPLXFUNC_Z_I_C99_(_f)
#define ZMPLXFUNC_Z_K_C99_(_f)
#define FLTFUNC_C(_f) FLTFUNC_C_(_f)
#define DBLFUNC_C(_f) DBLFUNC_C_(_f)
#define CMPLXFUNC_C(_f) CMPLXFUNC_C_(_f)
#define CMPLXFUNC_C_C(_f) CMPLXFUNC_C_C_(_f)
#define CMPLXFUNC_C_F(_f) CMPLXFUNC_C_F_(_f)
#define CMPLXFUNC_C_I(_f) CMPLXFUNC_C_I_(_f)
#define CMPLXFUNC_C_K(_f) CMPLXFUNC_C_K_(_f)
#define ZMPLXFUNC_Z(_f) ZMPLXFUNC_Z_(_f)
#define ZMPLXFUNC_Z_Z(_f) ZMPLXFUNC_Z_Z_(_f)
#define ZMPLXFUNC_Z_D(_f) ZMPLXFUNC_Z_D_(_f)
#define ZMPLXFUNC_Z_I(_f) ZMPLXFUNC_Z_I_(_f)
#define ZMPLXFUNC_Z_K(_f) ZMPLXFUNC_Z_K_(_f)
#define CMPLXARGS_C
#define ZMPLXARGS_Z
#define CMPLXARGS_C_C
#define CMPLXARGS_C_F
#define CMPLXARGS_C_I
#define CMPLXARGS_C_K
#define ZMPLXARGS_Z_Z
#define ZMPLXARGS_Z_D
#define ZMPLXARGS_Z_I
#define ZMPLXARGS_Z_K
#define CRETURN_F_F(_r, _i) do { cmplx->real = (_r); cmplx->imag = (_i); return; } while (0)
#define ZRETURN_D_D(_r, _i) do { dcmplx->real = (_r); dcmplx->imag = (_i); return; } while (0)
#define CRETURN_C(_c) do { (*cmplx = *((cmplx_t *)&(_c))); return; } while (0)
#define ZRETURN_Z(_z) do { (*dcmplx = *((dcmplx_t *)&(_z))); return; } while (0)
#define CRETURN_F(_f) return (_f)
#define ZRETURN_D(_d) return (_d)
#define CMPLX_CALL_CR_C_C(_f, _cr, _c1, _c2)
#define ZMPLX_CALL_ZR_Z_Z(_f, _zr, _z1, _z2)
#define FLTDECL_C(_f) FLTFUNC_C_(_f) ; FLTFUNC_C_C99_(_f);
#define DBLDECL_C(_f) DBLFUNC_C_(_f) ; DBLFUNC_C_C99_(_f);
#define CMPLXDECL_C(_f) CMPLXFUNC_C_(_f) ; CMPLXFUNC_C_C99_(_f);
#define CMPLXDECL_C_C(_f) CMPLXFUNC_C_C_(_f) ; CMPLXFUNC_C_C_C99_(_f);
#define CMPLXDECL_C_F(_f) CMPLXFUNC_C_F_(_f) ; CMPLXFUNC_C_F_C99_(_f);
#define CMPLXDECL_C_I(_f) CMPLXFUNC_C_I_(_f) ; CMPLXFUNC_C_I_C99_(_f);
#define CMPLXDECL_C_K(_f) CMPLXFUNC_C_K_(_f) ; CMPLXFUNC_C_K_C99_(_f);
#define ZMPLXDECL_Z(_f) ZMPLXFUNC_Z_(_f) ; ZMPLXFUNC_Z_C99_(_f);
#define ZMPLXDECL_Z_Z(_f) ZMPLXFUNC_Z_Z_(_f) ; ZMPLXFUNC_Z_Z_C99_(_f);
#define ZMPLXDECL_Z_D(_f) ZMPLXFUNC_Z_D_(_f) ; ZMPLXFUNC_Z_D_C99_(_f);
#define ZMPLXDECL_Z_I(_f) ZMPLXFUNC_Z_I_(_f) ; ZMPLXFUNC_Z_I_C99_(_f);
#define ZMPLXDECL_Z_K(_f) ZMPLXFUNC_Z_K_(_f) ; ZMPLXFUNC_Z_K_C99_(_f);
#define BESSEL_J0F j0f
#define BESSEL_J1F j1f
#define BESSEL_JNF jnf
#define BESSEL_Y0F y0f
#define BESSEL_Y1F y1f
#define BESSEL_YNF ynf
#define BESSEL_J0 j0
#define BESSEL_J1 j1
#define BESSEL_JN jn
#define BESSEL_Y0 y0
#define BESSEL_Y1 y1
#define BESSEL_YN yn
#define __CDECL
#define __mth_sincos(_a, _s, _c) sincosf(_a,_s,_c)
#define __mth_dsincos(_a, _s, _c) sincos(_a,_s,_c)
Typedefs
typedef float _Complex float_complex_t
typedef double _Complex double_complex_t
Functions
static __attribute__ ((always_inline)) float_complex_t pgmath_cmplxf(float r
float __mth_i_acos (float f)
float __mth_i_acosh (float f)
float __mth_i_alog (float f)
float __mth_i_alog10 (float f)
float __mth_i_asin (float f)
float __mth_i_asinh (float f)
float __mth_i_atan (float f)
float __mth_i_atanh (float f)
float __mth_i_atan2 (float f, float g)
float __mth_i_exp (float f)
float __mth_i_rpowr (float f, float g)
float __mth_i_sin (float f)
float __mth_i_sinh (float f)
float __mth_i_sqrt (float f)
float __mth_i_tan (float f)
float __mth_i_tanh (float f)
float __mth_i_amod (float f, float g)
float __mth_i_aint (float f)
float __mth_i_anint (float f)
float __mth_i_cosh (float f)
float __mth_i_cos (float f)
float __mth_i_rpowi (float x, int i)
float __mth_i_rpowk (float x, long long i)
float __pmth_i_rpowi (float x, int i)
float __pmth_i_rpowk (float x, long long i)
float __mth_i_acosd (float f)
float __mth_i_asind (float f)
float __mth_i_atand (float f)
float __mth_i_atan2d (float f, float g)
float __mth_i_sind (float f)
float __mth_i_tand (float f)
float __mth_i_cosd (float f)
float __mth_i_erf (float f)
float __mth_i_erfc (float f)
float __mth_i_erfc_scaled (float f)
float __mth_i_gamma (float f)
float __mth_i_log_gamma (float f)
float __mth_i_hypotf (float x, float y)
float __mth_i_bessel_j0 (float arg)
float __mth_i_bessel_j1 (float arg)
float __mth_i_bessel_jn (int n, float arg)
float __f90_bessel_jn (int n1, int n2, float f)
float __mth_i_bessel_y0 (float arg)
float __mth_i_bessel_y1 (float arg)
float __mth_i_bessel_yn (int n, float arg)
float __f90_bessel_yn (int n1, int n2, float f)
float __mth_i_ceil (float)
float __mth_i_floor (float)
int __mth_i_idnint (double d)
int __mth_i_mod (int i, int j)
int __mth_i_nint (float d)
int __mth_i_ipowi (int x, int i)
double __mth_i_dacos (double d)
double __mth_i_dacosh (double d)
double __mth_i_dasin (double d)
double __mth_i_dasinh (double d)
double __mth_i_datan (double d)
double __mth_i_datanh (double d)
double __mth_i_datan2 (double x, double y)
double __mth_i_dcos (double d)
double __mth_i_dcosh (double d)
double __mth_i_dexp (double d)
double __mth_i_dlog (double d)
double __mth_i_dlog10 (double d)
double __mth_i_dpowd (double x, double y)
double __mth_i_dsin (double d)
double __mth_i_dsinh (double d)
double __mth_i_dsqrt (double d)
double __mth_i_dtan (double d)
double __mth_i_dtanh (double d)
double __mth_i_dmod (double f, double g)
double __mth_i_dint (double d)
double __mth_i_dnint (double d)
double __mth_i_dpowi (double x, int i)
double __mth_i_dpowk (double x, long long i)
double __pmth_i_dpowi (double x, int i)
double __pmth_i_dpowk (double x, long long i)
double __mth_i_dacosd (double f)
double __mth_i_dasind (double f)
double __mth_i_datand (double f)
double __mth_i_datan2d (double f, double g)
double __mth_i_dsind (double f)
double __mth_i_dtand (double f)
double __mth_i_dcosd (double f)
double __mth_i_derf (double f)
double __mth_i_derfc (double f)
double __mth_i_derfc_scaled (double f)
double __mth_i_dgamma (double f)
double __mth_i_dlog_gamma (double f)
double __mth_i_dhypot (double, double)
double __mth_i_pow (double, double)
double __mth_i_dbessel_j0 (double arg)
double __mth_i_dbessel_j1 (double arg)
double __mth_i_dbessel_jn (int n, double arg)
double __f90_dbessel_jn (int n1, int n, double d)
double __mth_i_dbessel_y0 (double arg)
double __mth_i_dbessel_y1 (double arg)
double __mth_i_dbessel_yn (int n, double arg)
double __f90_dbessel_yn (int n1, int n, double d)
double __mth_i_dceil (double)
double __mth_i_dfloor (double)
static void __mth_sincos (float angle, float *s, float *c) __attribute__((always_inline))
static void __mth_dsincos (double angle, double *s, double *c) __attribute__((always_inline))
FLTDECL_C (__mth_i_cabs)
CMPLXDECL_C (__mth_i_cacos)
CMPLXDECL_C (__mth_i_casin)
CMPLXDECL_C (__mth_i_catan)
CMPLXDECL_C (__mth_i_ccos)
CMPLXDECL_C (__mth_i_ccosh)
__CDECL CMPLXDECL_C_C (__mth_i_cdiv)
__CDECL CMPLXDECL_C_F (__mth_i_cdivr)
CMPLXDECL_C (__mth_i_cexp)
CMPLXDECL_C (__mth_i_clog)
__CDECL CMPLXDECL_C_C (__mth_i_cpowc)
CMPLXDECL_C_I (__mth_i_cpowi)
CMPLXDECL_C_K (__mth_i_cpowk)
CMPLXDECL_C (__mth_i_csin)
CMPLXDECL_C (__mth_i_csinh)
CMPLXDECL_C (__mth_i_csqrt)
CMPLXDECL_C (__mth_i_ctan)
CMPLXDECL_C (__mth_i_ctanh)
DBLDECL_C (__mth_i_cdabs)
ZMPLXDECL_Z (__mth_i_cdacos)
ZMPLXDECL_Z (__mth_i_cdasin)
ZMPLXDECL_Z (__mth_i_cdatan)
ZMPLXDECL_Z (__mth_i_cdcos)
ZMPLXDECL_Z (__mth_i_cdcosh)
__CDECL ZMPLXDECL_Z_Z (__mth_i_cddiv)
__CDECL ZMPLXDECL_Z_D (__mth_i_cddivd)
ZMPLXDECL_Z (__mth_i_cdexp)
ZMPLXDECL_Z (__mth_i_cdlog)
__CDECL ZMPLXDECL_Z_Z (__mth_i_cdpowcd)
ZMPLXDECL_Z_I (__mth_i_cdpowi)
ZMPLXDECL_Z_K (__mth_i_cdpowk)
ZMPLXDECL_Z (__mth_i_cdsin)
ZMPLXDECL_Z (__mth_i_cdsinh)
ZMPLXDECL_Z (__mth_i_cdsqrt)
ZMPLXDECL_Z (__mth_i_cdtan)
ZMPLXDECL_Z (__mth_i_cdtanh)
Variables
static float i
_cf _f [0] = r
return _cf _c
_zd _d [0] = r
return _zd _z
Detailed Description
mthdecls.h - Fortran math support (all platforms/targets)
Definition in file libpgmath/lib/x86_64/mthdecls.h.
Macro Definition Documentation
__CDECL
#define __CDECL
Definition at line 521 of file libpgmath/lib/x86_64/mthdecls.h.
__MTH_C99_CMPLX_SUFFIX
#define __MTH_C99_CMPLX_SUFFIX _c99
Definition at line 94 of file libpgmath/lib/x86_64/mthdecls.h.
__mth_dsincos
#define __mth_dsincos (_a, _s, _c) sincos(_a,_s,_c)
Definition at line 632 of file libpgmath/lib/x86_64/mthdecls.h.
__mth_sincos
#define __mth_sincos (_a, _s, _c) sincosf(_a,_s,_c)
Definition at line 631 of file libpgmath/lib/x86_64/mthdecls.h.
BESSEL_J0
#define BESSEL_J0 j0
Definition at line 388 of file libpgmath/lib/x86_64/mthdecls.h.
BESSEL_J0F
#define BESSEL_J0F j0f
Definition at line 381 of file libpgmath/lib/x86_64/mthdecls.h.
BESSEL_J1
#define BESSEL_J1 j1
Definition at line 389 of file libpgmath/lib/x86_64/mthdecls.h.
BESSEL_J1F
#define BESSEL_J1F j1f
Definition at line 382 of file libpgmath/lib/x86_64/mthdecls.h.
BESSEL_JN
#define BESSEL_JN jn
Definition at line 390 of file libpgmath/lib/x86_64/mthdecls.h.
BESSEL_JNF
#define BESSEL_JNF jnf
Definition at line 383 of file libpgmath/lib/x86_64/mthdecls.h.
BESSEL_Y0
#define BESSEL_Y0 y0
Definition at line 391 of file libpgmath/lib/x86_64/mthdecls.h.
BESSEL_Y0F
#define BESSEL_Y0F y0f
Definition at line 384 of file libpgmath/lib/x86_64/mthdecls.h.
BESSEL_Y1
#define BESSEL_Y1 y1
Definition at line 392 of file libpgmath/lib/x86_64/mthdecls.h.
BESSEL_Y1F
#define BESSEL_Y1F y1f
Definition at line 385 of file libpgmath/lib/x86_64/mthdecls.h.
BESSEL_YN
#define BESSEL_YN yn
Definition at line 393 of file libpgmath/lib/x86_64/mthdecls.h.
BESSEL_YNF
#define BESSEL_YNF ynf
Definition at line 386 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLX_CALL_CR_C_C
#define CMPLX_CALL_CR_C_C (_f, _cr, _c1, _c2)
Value:
{ _f(cmplx, crealf(_c1), cimagf(_c1), crealf(_c2), cimagf(_c2)); \
  *(cmplx_t *)&_cr = *cmplx; }
Definition at line 263 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXARGS_C
#define CMPLXARGS_C
Value:
        float_complex_t                                \
        carg = pgmath_cmplxf(real, imag)
Definition at line 239 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXARGS_C_C
#define CMPLXARGS_C_C
Value:
        float_complex_t                                \
        carg1 = pgmath_cmplxf(real1, imag1),\
        carg2 = pgmath_cmplxf(real2, imag2)
Definition at line 243 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXARGS_C_F
#define CMPLXARGS_C_F
Definition at line 246 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXARGS_C_I
#define CMPLXARGS_C_I
Definition at line 247 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXARGS_C_K
#define CMPLXARGS_C_K
Definition at line 248 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXDECL_C
#define CMPLXDECL_C (_f) CMPLXFUNC_C_(_f) ; CMPLXFUNC_C_C99_(_f);
Definition at line 325 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXDECL_C_C
#define CMPLXDECL_C_C (_f) CMPLXFUNC_C_C_(_f) ; CMPLXFUNC_C_C_C99_(_f);
Definition at line 326 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXDECL_C_F
#define CMPLXDECL_C_F (_f) CMPLXFUNC_C_F_(_f) ; CMPLXFUNC_C_F_C99_(_f);
Definition at line 327 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXDECL_C_I
#define CMPLXDECL_C_I (_f) CMPLXFUNC_C_I_(_f) ; CMPLXFUNC_C_I_C99_(_f);
Definition at line 328 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXDECL_C_K
#define CMPLXDECL_C_K (_f) CMPLXFUNC_C_K_(_f) ; CMPLXFUNC_C_K_C99_(_f);
Definition at line 329 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXFUNC_C
#define CMPLXFUNC_C (_f) CMPLXFUNC_C_(_f)
Definition at line 227 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXFUNC_C_
#define CMPLXFUNC_C_ (_f) void _f(cmplx_t *cmplx, float real, float imag)
Definition at line 158 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXFUNC_C_C
#define CMPLXFUNC_C_C (_f) CMPLXFUNC_C_C_(_f)
Definition at line 228 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXFUNC_C_C99_
#define CMPLXFUNC_C_C99_ (_f)
Value:
        float_complex_t MTHCONCAT__(_f,__MTH_C99_CMPLX_SUFFIX) \
        (float_complex_t carg)
Definition at line 190 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXFUNC_C_C_
#define CMPLXFUNC_C_C_ (_f)
Value:
        void _f(cmplx_t *cmplx, float real1, float imag1, \
                                  float real2, float imag2)
Definition at line 160 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXFUNC_C_C_C99_
#define CMPLXFUNC_C_C_C99_ (_f)
Value:
        float_complex_t MTHCONCAT__(_f,__MTH_C99_CMPLX_SUFFIX) \
        (float_complex_t carg1, float_complex_t carg2)
Definition at line 193 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXFUNC_C_F
#define CMPLXFUNC_C_F (_f) CMPLXFUNC_C_F_(_f)
Definition at line 229 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXFUNC_C_F_
#define CMPLXFUNC_C_F_ (_f) void _f(cmplx_t *cmplx, float real, float imag, float r)
Definition at line 163 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXFUNC_C_F_C99_
#define CMPLXFUNC_C_F_C99_ (_f)
Value:
        float_complex_t MTHCONCAT__(_f,__MTH_C99_CMPLX_SUFFIX) \
        (float_complex_t carg, float r)
Definition at line 196 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXFUNC_C_I
#define CMPLXFUNC_C_I (_f) CMPLXFUNC_C_I_(_f)
Definition at line 230 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXFUNC_C_I_
#define CMPLXFUNC_C_I_ (_f) void _f(cmplx_t *cmplx, float real, float imag, int i)
Definition at line 165 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXFUNC_C_I_C99_
#define CMPLXFUNC_C_I_C99_ (_f)
Value:
        float_complex_t MTHCONCAT__(_f,__MTH_C99_CMPLX_SUFFIX) \
        (float_complex_t carg, int i)
Definition at line 199 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXFUNC_C_K
#define CMPLXFUNC_C_K (_f) CMPLXFUNC_C_K_(_f)
Definition at line 231 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXFUNC_C_K_
#define CMPLXFUNC_C_K_ (_f) void _f(cmplx_t *cmplx, float real, float imag, long long i)
Definition at line 167 of file libpgmath/lib/x86_64/mthdecls.h.
CMPLXFUNC_C_K_C99_
#define CMPLXFUNC_C_K_C99_ (_f)
Value:
        float_complex_t MTHCONCAT__(_f,__MTH_C99_CMPLX_SUFFIX) \
        (float_complex_t carg, long long i)
Definition at line 202 of file libpgmath/lib/x86_64/mthdecls.h.
CNVRTDEG
#define CNVRTDEG (degrees) ((degrees)*DEG_TO_RAD)
Definition at line 17 of file libpgmath/lib/x86_64/mthdecls.h.
CNVRTRAD
#define CNVRTRAD (radians) ((radians)*RAD_TO_DEG)
Definition at line 18 of file libpgmath/lib/x86_64/mthdecls.h.
CRETURN_C
#define CRETURN_C (_c) do { (*cmplx = *((cmplx_t *)&(_c))); return; } while (0)
Definition at line 258 of file libpgmath/lib/x86_64/mthdecls.h.
CRETURN_F
#define CRETURN_F (_f) return (_f)
Definition at line 260 of file libpgmath/lib/x86_64/mthdecls.h.
CRETURN_F_F
#define CRETURN_F_F (_r, _i) do { cmplx->real = (_r); cmplx->imag = (_i); return; } while (0)
Definition at line 256 of file libpgmath/lib/x86_64/mthdecls.h.
DBLDECL_C
#define DBLDECL_C (_f) DBLFUNC_C_(_f) ; DBLFUNC_C_C99_(_f);
Definition at line 323 of file libpgmath/lib/x86_64/mthdecls.h.
DBLFUNC_C
#define DBLFUNC_C (_f) DBLFUNC_C_(_f)
Definition at line 225 of file libpgmath/lib/x86_64/mthdecls.h.
DBLFUNC_C_
#define DBLFUNC_C_ (_f) double _f(double real, double imag)
Definition at line 155 of file libpgmath/lib/x86_64/mthdecls.h.
DBLFUNC_C_C99_
#define DBLFUNC_C_C99_ (_f)
Value:
        double MTHCONCAT__(_f,__MTH_C99_CMPLX_SUFFIX) \
        (double_complex_t zarg)
Definition at line 186 of file libpgmath/lib/x86_64/mthdecls.h.
DEG_TO_RAD
#define DEG_TO_RAD 0.174532925199432957692E-1
Definition at line 14 of file libpgmath/lib/x86_64/mthdecls.h.
FLTDECL_C
#define FLTDECL_C (_f) FLTFUNC_C_(_f) ; FLTFUNC_C_C99_(_f);
Definition at line 322 of file libpgmath/lib/x86_64/mthdecls.h.
FLTFUNC_C
#define FLTFUNC_C (_f) FLTFUNC_C_(_f)
Definition at line 224 of file libpgmath/lib/x86_64/mthdecls.h.
FLTFUNC_C_
#define FLTFUNC_C_ (_f) float _f(float real, float imag)
Definition at line 153 of file libpgmath/lib/x86_64/mthdecls.h.
FLTFUNC_C_C99_
#define FLTFUNC_C_C99_ (_f)
Value:
        float MTHCONCAT__(_f,__MTH_C99_CMPLX_SUFFIX) \
        (float_complex_t carg)
Definition at line 183 of file libpgmath/lib/x86_64/mthdecls.h.
MTHCONCAT__
#define MTHCONCAT__ (l, r) MTHCONCAT___(l,r)
Definition at line 92 of file libpgmath/lib/x86_64/mthdecls.h.
MTHCONCAT___
#define MTHCONCAT___ (l, r) l##r
Definition at line 91 of file libpgmath/lib/x86_64/mthdecls.h.
PGMATH_CMPLX_CONST
#define PGMATH_CMPLX_CONST (r, i) r + I*i
Definition at line 59 of file libpgmath/lib/x86_64/mthdecls.h.
RAD_TO_DEG
#define RAD_TO_DEG 0.572957795130823208769E+2
Definition at line 16 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLX_CALL_ZR_Z_Z
#define ZMPLX_CALL_ZR_Z_Z (_f, _zr, _z1, _z2)
Value:
{ _f(dcmplx, creal(_z1), cimag(_z1), creal(_z2), cimag(_z2)); \
  *(dcmplx_t *)&_zr = *dcmplx; }
Definition at line 266 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXARGS_Z
#define ZMPLXARGS_Z
Value:
        double_complex_t                               \
        zarg = pgmath_cmplx(real, imag)
Definition at line 241 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXARGS_Z_D
#define ZMPLXARGS_Z_D
Definition at line 252 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXARGS_Z_I
#define ZMPLXARGS_Z_I
Definition at line 253 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXARGS_Z_K
#define ZMPLXARGS_Z_K
Definition at line 254 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXARGS_Z_Z
#define ZMPLXARGS_Z_Z
Value:
        double_complex_t                               \
        zarg1 = pgmath_cmplx(real1, imag1),\
        zarg2 = pgmath_cmplx(real2, imag2)
Definition at line 249 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXDECL_Z
#define ZMPLXDECL_Z (_f) ZMPLXFUNC_Z_(_f) ; ZMPLXFUNC_Z_C99_(_f);
Definition at line 331 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXDECL_Z_D
#define ZMPLXDECL_Z_D (_f) ZMPLXFUNC_Z_D_(_f) ; ZMPLXFUNC_Z_D_C99_(_f);
Definition at line 333 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXDECL_Z_I
#define ZMPLXDECL_Z_I (_f) ZMPLXFUNC_Z_I_(_f) ; ZMPLXFUNC_Z_I_C99_(_f);
Definition at line 334 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXDECL_Z_K
#define ZMPLXDECL_Z_K (_f) ZMPLXFUNC_Z_K_(_f) ; ZMPLXFUNC_Z_K_C99_(_f);
Definition at line 335 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXDECL_Z_Z
#define ZMPLXDECL_Z_Z (_f) ZMPLXFUNC_Z_Z_(_f) ; ZMPLXFUNC_Z_Z_C99_(_f);
Definition at line 332 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXFUNC_Z
#define ZMPLXFUNC_Z (_f) ZMPLXFUNC_Z_(_f)
Definition at line 233 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXFUNC_Z_
#define ZMPLXFUNC_Z_ (_f) void _f(dcmplx_t *dcmplx, double real, double imag)
Definition at line 170 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXFUNC_Z_C99_
#define ZMPLXFUNC_Z_C99_ (_f)
Value:
        double_complex_t MTHCONCAT__(_f,__MTH_C99_CMPLX_SUFFIX) \
        (double_complex_t zarg)
Definition at line 206 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXFUNC_Z_D
#define ZMPLXFUNC_Z_D (_f) ZMPLXFUNC_Z_D_(_f)
Definition at line 235 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXFUNC_Z_D_
#define ZMPLXFUNC_Z_D_ (_f) void _f(dcmplx_t *dcmplx, double real, double imag, double d)
Definition at line 175 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXFUNC_Z_D_C99_
#define ZMPLXFUNC_Z_D_C99_ (_f)
Value:
        double_complex_t MTHCONCAT__(_f,__MTH_C99_CMPLX_SUFFIX) \
        (double_complex_t zarg, double d)
Definition at line 212 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXFUNC_Z_I
#define ZMPLXFUNC_Z_I (_f) ZMPLXFUNC_Z_I_(_f)
Definition at line 236 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXFUNC_Z_I_
#define ZMPLXFUNC_Z_I_ (_f) void _f(dcmplx_t *dcmplx, double real, double imag, int i)
Definition at line 177 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXFUNC_Z_I_C99_
#define ZMPLXFUNC_Z_I_C99_ (_f)
Value:
        double_complex_t MTHCONCAT__(_f,__MTH_C99_CMPLX_SUFFIX) \
        (double_complex_t zarg, int i)
Definition at line 215 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXFUNC_Z_K
#define ZMPLXFUNC_Z_K (_f) ZMPLXFUNC_Z_K_(_f)
Definition at line 237 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXFUNC_Z_K_
#define ZMPLXFUNC_Z_K_ (_f) void _f(dcmplx_t *dcmplx, double real, double imag, long long i)
Definition at line 179 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXFUNC_Z_K_C99_
#define ZMPLXFUNC_Z_K_C99_ (_f)
Value:
        double_complex_t MTHCONCAT__(_f,__MTH_C99_CMPLX_SUFFIX) \
        (double_complex_t zarg, long long i)
Definition at line 218 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXFUNC_Z_Z
#define ZMPLXFUNC_Z_Z (_f) ZMPLXFUNC_Z_Z_(_f)
Definition at line 234 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXFUNC_Z_Z_
#define ZMPLXFUNC_Z_Z_ (_f)
Value:
        void _f(dcmplx_t *dcmplx, double real1, double imag1, \
                                    double real2, double imag2)
Definition at line 172 of file libpgmath/lib/x86_64/mthdecls.h.
ZMPLXFUNC_Z_Z_C99_
#define ZMPLXFUNC_Z_Z_C99_ (_f)
Value:
        double_complex_t MTHCONCAT__(_f,__MTH_C99_CMPLX_SUFFIX) \
        (double_complex_t zarg1, double_complex_t zarg2)
Definition at line 209 of file libpgmath/lib/x86_64/mthdecls.h.
ZRETURN_D
#define ZRETURN_D (_d) return (_d)
Definition at line 261 of file libpgmath/lib/x86_64/mthdecls.h.
ZRETURN_D_D
#define ZRETURN_D_D (_r, _i) do { dcmplx->real = (_r); dcmplx->imag = (_i); return; } while (0)
Definition at line 257 of file libpgmath/lib/x86_64/mthdecls.h.
ZRETURN_Z
#define ZRETURN_Z (_z) do { (*dcmplx = *((dcmplx_t *)&(_z))); return; } while (0)
Definition at line 259 of file libpgmath/lib/x86_64/mthdecls.h.
Typedef Documentation
double_complex_t
typedef double _Complex double_complex_t
Definition at line 58 of file libpgmath/lib/x86_64/mthdecls.h.
float_complex_t
typedef float _Complex float_complex_t
Definition at line 57 of file libpgmath/lib/x86_64/mthdecls.h.
Function Documentation
__attribute__()
static __attribute__ ((always_inline)) inline static
References _c, and _f.
__f90_bessel_jn()
float __f90_bessel_jn (int n1, int n2, float f)
__f90_bessel_yn()
float __f90_bessel_yn (int n1, int n2, float f)
__f90_dbessel_jn()
double __f90_dbessel_jn (int n1, int n, double d)
__f90_dbessel_yn()
double __f90_dbessel_yn (int n1, int n, double d)
__mth_dsincos()
static void __mth_dsincos (double angle, double * s, double * c) inline static
__mth_i_acos()
float __mth_i_acos (float f)
Definition at line 12 of file generic/acos.c.
References acosf(), arg, and f.
__mth_i_acosd()
float __mth_i_acosd (float f)
Definition at line 11 of file acosd.c.
References acosf(), CNVRTRAD, and f.
__mth_i_acosh()
float __mth_i_acosh (float f)
Definition at line 14 of file generic/acosh.c.
References arg, and f.
__mth_i_aint()
float __mth_i_aint (float f)
Definition at line 31 of file aint.c.
__mth_i_alog()
float __mth_i_alog (float f)
Definition at line 11 of file generic/alog.c.
__mth_i_alog10()
float __mth_i_alog10 (float f)
Definition at line 11 of file alog10.c.
__mth_i_amod()
float __mth_i_amod (float f, float g)
Definition at line 12 of file amod.c.
References f, and fmodf().
__mth_i_anint()
float __mth_i_anint (float f)
Definition at line 44 of file anint.c.
__mth_i_asin()
float __mth_i_asin (float f)
Definition at line 11 of file generic/asin.c.
References arg, asinf(), and f.
__mth_i_asind()
float __mth_i_asind (float f)
Definition at line 11 of file asind.c.
References asinf(), CNVRTRAD, and f.
__mth_i_asinh()
float __mth_i_asinh (float f)
Definition at line 14 of file generic/asinh.c.
References arg, and f.
__mth_i_atan()
float __mth_i_atan (float f)
Definition at line 11 of file generic/atan.c.
__mth_i_atan2()
float __mth_i_atan2 (float f, float g)
Definition at line 11 of file generic/atan2.c.
__mth_i_atan2d()
float __mth_i_atan2d (float f, float g)
Definition at line 11 of file atan2d.c.
References atan2f(), CNVRTRAD, and f.
__mth_i_atand()
float __mth_i_atand (float f)
Definition at line 11 of file atand.c.
References atanf(), CNVRTRAD, and f.
__mth_i_atanh()
float __mth_i_atanh (float f)
Definition at line 11 of file generic/atanh.c.
References f.
__mth_i_bessel_j0()
float __mth_i_bessel_j0 (float arg)
Definition at line 14 of file bessel_j0.c.
__mth_i_bessel_j1()
float __mth_i_bessel_j1 (float arg)
Definition at line 14 of file bessel_j1.c.
__mth_i_bessel_jn()
float __mth_i_bessel_jn (int n, float arg)
Definition at line 14 of file bessel_jn.c.
__mth_i_bessel_y0()
float __mth_i_bessel_y0 (float arg)
Definition at line 14 of file bessel_y0.c.
__mth_i_bessel_y1()
float __mth_i_bessel_y1 (float arg)
Definition at line 14 of file bessel_y1.c.
__mth_i_bessel_yn()
float __mth_i_bessel_yn (int n, float arg)
Definition at line 14 of file bessel_yn.c.
__mth_i_ceil()
float __mth_i_ceil (float x)
Definition at line 46 of file ceil.c.
References ceilf(), and x.
__mth_i_cos()
float __mth_i_cos (float f)
Definition at line 11 of file cos.c.
__mth_i_cosd()
float __mth_i_cosd (float f)
Definition at line 11 of file cosd.c.
References CNVRTDEG, cosf(), and f.
__mth_i_cosh()
float __mth_i_cosh (float f)
Definition at line 11 of file generic/cosh.c.
__mth_i_dacos()
double __mth_i_dacos (double d)
Definition at line 13 of file dacos.c.
References acos(), arg, and f.
__mth_i_dacosd()
double __mth_i_dacosd (double f)
Definition at line 10 of file dacosd.c.
References acos(), CNVRTRAD, and d.
__mth_i_dacosh()
double __mth_i_dacosh (double d)
Definition at line 14 of file generic/dacosh.c.
References arg, and f.
__mth_i_dasin()
double __mth_i_dasin (double d)
Definition at line 10 of file dasin.c.
References arg, asin(), and f.
__mth_i_dasind()
double __mth_i_dasind (double f)
Definition at line 10 of file dasind.c.
References asin(), CNVRTRAD, and d.
__mth_i_dasinh()
double __mth_i_dasinh (double d)
Definition at line 14 of file generic/dasinh.c.
References arg, and f.
__mth_i_datan()
double __mth_i_datan (double d)
Definition at line 14 of file generic/datan.c.
__mth_i_datan2()
double __mth_i_datan2 (double x, double y)
Definition at line 14 of file generic/datan2.c.
__mth_i_datan2d()
double __mth_i_datan2d (double f, double g)
Definition at line 10 of file datan2d.c.
References atan2(), CNVRTRAD, x, and y.
__mth_i_datand()
double __mth_i_datand (double f)
Definition at line 10 of file datand.c.
References atan(), CNVRTRAD, and d.
__mth_i_datanh()
double __mth_i_datanh (double d)
Definition at line 11 of file generic/datanh.c.
References d.
__mth_i_dbessel_j0()
double __mth_i_dbessel_j0 (double arg)
Definition at line 14 of file dbessel_j0.c.
__mth_i_dbessel_j1()
double __mth_i_dbessel_j1 (double arg)
Definition at line 14 of file dbessel_j1.c.
__mth_i_dbessel_jn()
double __mth_i_dbessel_jn (int n, double arg)
Definition at line 14 of file dbessel_jn.c.
__mth_i_dbessel_y0()
double __mth_i_dbessel_y0 (double arg)
Definition at line 14 of file dbessel_y0.c.
__mth_i_dbessel_y1()
double __mth_i_dbessel_y1 (double arg)
Definition at line 14 of file dbessel_y1.c.
__mth_i_dbessel_yn()
double __mth_i_dbessel_yn (int n, double arg)
Definition at line 14 of file dbessel_yn.c.
__mth_i_dceil()
double __mth_i_dceil (double x)
Definition at line 46 of file dceil.c.
References ceil(), and x.
__mth_i_dcos()
double __mth_i_dcos (double d)
Definition at line 10 of file dcos.c.
__mth_i_dcosd()
double __mth_i_dcosd (double f)
Definition at line 10 of file dcosd.c.
References CNVRTDEG, cos(), and d.
__mth_i_dcosh()
double __mth_i_dcosh (double d)
Definition at line 10 of file generic/dcosh.c.
__mth_i_derf()
double __mth_i_derf (double f)
Definition at line 15 of file erf.c.
References arg, erf(), and f.
__mth_i_derfc()
double __mth_i_derfc (double f)
Definition at line 14 of file erfc.c.
References arg, erfc(), and f.
__mth_i_derfc_scaled()
double __mth_i_derfc_scaled (double f)
Definition at line 64 of file erfc_scaled.c.
References a, arg, b, d, exp, fabs, four, i, one, p, q, result, sixten, sqrpi, thresh, tmp, trunc(), x, xbig, xhuge, xinfr8, xmaxr8, xneg, xsmallr8, y, and zero.
__mth_i_dexp()
double __mth_i_dexp (double d)
Definition at line 10 of file generic/dexp.c.
__mth_i_dfloor()
double __mth_i_dfloor (double x)
Definition at line 46 of file dfloor.c.
References floor(), and x.
__mth_i_dgamma()
double __mth_i_dgamma (double f)
Definition at line 14 of file gamma.c.
References arg, and f.
__mth_i_dhypot()
double __mth_i_dhypot (double x, double y)
Definition at line 14 of file hypot.c.
References f, hypot(), x, and y.
__mth_i_dint()
double __mth_i_dint (double d)
Definition at line 34 of file dint.c.
__mth_i_dlog()
double __mth_i_dlog (double d)
Definition at line 10 of file generic/dlog.c.
__mth_i_dlog10()
double __mth_i_dlog10 (double d)
Definition at line 14 of file dlog10.c.
__mth_i_dlog_gamma()
double __mth_i_dlog_gamma (double f)
Definition at line 14 of file log_gamma.c.
References arg, and f.
__mth_i_dmod()
double __mth_i_dmod (double f, double g)
Definition at line 12 of file dmod.c.
References f, and fmod().
__mth_i_dnint()
double __mth_i_dnint (double d)
Definition at line 44 of file dnint.c.
__mth_i_dpowd()
double __mth_i_dpowd (double x, double y)
Definition at line 10 of file dpowd.c.
__mth_i_dpowi()
double __mth_i_dpowi (double x, int i)
Definition at line 11 of file dpowi.c.
References f, i, k, and x.
__mth_i_dpowk()
double __mth_i_dpowk (double x, long long i)
Definition at line 11 of file dpowk.c.
References f, i, k, and x.
__mth_i_dsin()
double __mth_i_dsin (double d)
Definition at line 10 of file dsin.c.
__mth_i_dsind()
double __mth_i_dsind (double f)
Definition at line 10 of file dsind.c.
References CNVRTDEG, d, and sin().
__mth_i_dsinh()
double __mth_i_dsinh (double d)
Definition at line 10 of file generic/dsinh.c.
__mth_i_dsqrt()
double __mth_i_dsqrt (double d)
Definition at line 10 of file generic/dsqrt.c.
References __builtin_sqrt(), and d.
__mth_i_dtan()
double __mth_i_dtan (double d)
Definition at line 10 of file generic/dtan.c.
__mth_i_dtand()
double __mth_i_dtand (double f)
Definition at line 14 of file dtand.c.
References CNVRTDEG, u::d, d, fabs, fmod(), HFPI, MYPI, t, and tan().
__mth_i_dtanh()
double __mth_i_dtanh (double d)
Definition at line 10 of file generic/dtanh.c.
__mth_i_erf()
float __mth_i_erf (float f)
Definition at line 15 of file erff.c.
References arg, erff(), and f.
__mth_i_erfc()
float __mth_i_erfc (float f)
Definition at line 14 of file erfcf.c.
References arg, and f.
__mth_i_erfc_scaled()
float __mth_i_erfc_scaled (float f)
Definition at line 64 of file erfc_scaledf.c.
References a, arg, b, d, exp, fabs, four, i, one, p, q, result, sixten, sqrpi, thresh, tmp, trunc(), x, xbig, xhuge, xinfr4, xmaxr4, xneg, xsmallr4, y, and zero.
__mth_i_exp()
float __mth_i_exp (float f)
Definition at line 11 of file generic/exp.c.
__mth_i_floor()
float __mth_i_floor (float x)
Definition at line 46 of file floor.c.
References floorf(), and x.
__mth_i_gamma()
float __mth_i_gamma (float f)
Definition at line 14 of file gammaf.c.
References arg, and f.
__mth_i_hypotf()
float __mth_i_hypotf (float x, float y)
__mth_i_idnint()
int __mth_i_idnint (double d)
Definition at line 10 of file idnint.c.
References d.
__mth_i_ipowi()
int __mth_i_ipowi (int x, int i)
Definition at line 11 of file ipowi.c.
References f, i, and x.
__mth_i_log_gamma()
float __mth_i_log_gamma (float f)
Definition at line 14 of file log_gammaf.c.
References arg, and f.
__mth_i_mod()
int __mth_i_mod (int i, int j)
Definition at line 11 of file mod.c.
References i, and j.
__mth_i_nint()
int __mth_i_nint (float d)
Definition at line 9 of file nint.c.
__mth_i_pow()
double __mth_i_pow (double , double)
__mth_i_rpowi()
float __mth_i_rpowi (float x, int i)
Definition at line 12 of file rpowi.c.
__mth_i_rpowk()
float __mth_i_rpowk (float x, long long i)
Definition at line 12 of file rpowk.c.
__mth_i_rpowr()
float __mth_i_rpowr (float f, float g)
Definition at line 11 of file rpowr.c.
__mth_i_sin()
float __mth_i_sin (float f)
Definition at line 11 of file sin.c.
__mth_i_sind()
float __mth_i_sind (float f)
Definition at line 11 of file sind.c.
__mth_i_sinh()
float __mth_i_sinh (float f)
Definition at line 11 of file generic/sinh.c.
__mth_i_sqrt()
float __mth_i_sqrt (float f)
Definition at line 11 of file generic/sqrt.c.
References __builtin_sqrtf(), and f.
__mth_i_tan()
float __mth_i_tan (float f)
Definition at line 11 of file generic/tan.c.
__mth_i_tand()
float __mth_i_tand (float f)
Definition at line 13 of file tand.c.
__mth_i_tanh()
float __mth_i_tanh (float f)
Definition at line 11 of file generic/tanh.c.
__mth_sincos()
static void __mth_sincos (float angle, float * s, float * c) inline static
__pmth_i_dpowi()
double __pmth_i_dpowi (double x, int i)
Definition at line 52 of file p_dpowi.c.
__pmth_i_dpowk()
double __pmth_i_dpowk (double x, long long i)
Definition at line 20 of file p_dpowi.c.
Referenced by __pmth_i_dpowi().
__pmth_i_rpowi()
float __pmth_i_rpowi (float x, int i)
Definition at line 52 of file p_rpowi.c.
__pmth_i_rpowk()
float __pmth_i_rpowk (float x, long long i)
Definition at line 20 of file p_rpowi.c.
Referenced by __pmth_i_rpowi().
CMPLXDECL_C() [1/12]
CMPLXDECL_C (__mth_i_cacos)
CMPLXDECL_C() [2/12]
CMPLXDECL_C (__mth_i_casin)
CMPLXDECL_C() [3/12]
CMPLXDECL_C (__mth_i_catan)
CMPLXDECL_C() [4/12]
CMPLXDECL_C (__mth_i_ccos)
CMPLXDECL_C() [5/12]
CMPLXDECL_C (__mth_i_ccosh)
CMPLXDECL_C() [6/12]
CMPLXDECL_C (__mth_i_cexp)
CMPLXDECL_C() [7/12]
CMPLXDECL_C (__mth_i_clog)
CMPLXDECL_C() [8/12]
CMPLXDECL_C (__mth_i_csin)
CMPLXDECL_C() [9/12]
CMPLXDECL_C (__mth_i_csinh)
CMPLXDECL_C() [10/12]
CMPLXDECL_C (__mth_i_csqrt)
CMPLXDECL_C() [11/12]
CMPLXDECL_C (__mth_i_ctan)
CMPLXDECL_C() [12/12]
CMPLXDECL_C (__mth_i_ctanh)
CMPLXDECL_C_C() [1/2]
__CDECL CMPLXDECL_C_C (__mth_i_cdiv)
CMPLXDECL_C_C() [2/2]
__CDECL CMPLXDECL_C_C (__mth_i_cpowc)
CMPLXDECL_C_F()
__CDECL CMPLXDECL_C_F (__mth_i_cdivr)
CMPLXDECL_C_I()
CMPLXDECL_C_I (__mth_i_cpowi)
CMPLXDECL_C_K()
CMPLXDECL_C_K (__mth_i_cpowk)
DBLDECL_C()
DBLDECL_C (__mth_i_cdabs)
FLTDECL_C()
FLTDECL_C (__mth_i_cabs)
ZMPLXDECL_Z() [1/12]
ZMPLXDECL_Z (__mth_i_cdacos)
ZMPLXDECL_Z() [2/12]
ZMPLXDECL_Z (__mth_i_cdasin)
ZMPLXDECL_Z() [3/12]
ZMPLXDECL_Z (__mth_i_cdatan)
ZMPLXDECL_Z() [4/12]
ZMPLXDECL_Z (__mth_i_cdcos)
ZMPLXDECL_Z() [5/12]
ZMPLXDECL_Z (__mth_i_cdcosh)
ZMPLXDECL_Z() [6/12]
ZMPLXDECL_Z (__mth_i_cdexp)
ZMPLXDECL_Z() [7/12]
ZMPLXDECL_Z (__mth_i_cdlog)
ZMPLXDECL_Z() [8/12]
ZMPLXDECL_Z (__mth_i_cdsin)
ZMPLXDECL_Z() [9/12]
ZMPLXDECL_Z (__mth_i_cdsinh)
ZMPLXDECL_Z() [10/12]
ZMPLXDECL_Z (__mth_i_cdsqrt)
ZMPLXDECL_Z() [11/12]
ZMPLXDECL_Z (__mth_i_cdtan)
ZMPLXDECL_Z() [12/12]
ZMPLXDECL_Z (__mth_i_cdtanh)
ZMPLXDECL_Z_D()
__CDECL ZMPLXDECL_Z_D (__mth_i_cddivd)
ZMPLXDECL_Z_I()
ZMPLXDECL_Z_I (__mth_i_cdpowi)
ZMPLXDECL_Z_K()
ZMPLXDECL_Z_K (__mth_i_cdpowk)
ZMPLXDECL_Z_Z() [1/2]
__CDECL ZMPLXDECL_Z_Z (__mth_i_cddiv)
ZMPLXDECL_Z_Z() [2/2]
__CDECL ZMPLXDECL_Z_Z (__mth_i_cdpowcd)
Variable Documentation
_c
return _cf _c
Definition at line 112 of file libpgmath/lib/x86_64/mthdecls.h.
Referenced by __attribute__().
_d
_zd _d[1] = r
Definition at line 129 of file libpgmath/lib/x86_64/mthdecls.h.
_f
_cf _f[1] = r
Definition at line 110 of file libpgmath/lib/x86_64/mthdecls.h.
Referenced by __attribute__().
_z
return _zd _z
Definition at line 131 of file libpgmath/lib/x86_64/mthdecls.h.
i
double i
Initial value:
{
    struct {
        union {
            float_complex_t _c;
            float _f[2];
        };
    } _cf
Definition at line 102 of file libpgmath/lib/x86_64/mthdecls.h.