flang: listing.cpp File Reference
listing.cpp File Reference
#include "listing.h"
#include "gbldefs.h"
#include "global.h"
#include "version.h"
Functions
static void list_ln (const char *beg, const char *txt)
void list_init (FILE *fd)
...
void list_line (const char *txt)
...
void list_page (void)
...
Variables
static int pgpos = 1
Fortran source listing file module.
static FILE * lf
static int pgno
const int LPP = 60
Function Documentation
list_init()
void list_init (FILE * fd)
...
Definition at line 50 of file listing.cpp.
References FLG::asmcode, buf, FLG::code, DBGBIT, FLG::dclchk, FLG::debug, FLG::depchk, FLG::depwarn, FLG::dlines, FLG::extend_source, fd, flg, gbl, FLG::idir, FLG::include, FLG::inform, lf, FLG::line, FLG::list, list_line(), list_ln(), FLG::object, FLG::onetrip, FLG::opt, p, pgno, FLG::profile, FLG::save, FLG::standard, FLG::symbol, FLG::ucase, and FLG::xref.
Referenced by init().
list_line()
void list_line (const char * txt)
...
Definition at line 67 of file listing.cpp.
References list_ln().
Referenced by _nextline(), display_error(), ff_get_noncomment(), ff_get_stmt(), get_stmt(), list_init(), list_page(), par_body(), print_par_xref(), printxref(), push_include(), putentry(), reptime(), and scan_include().
list_ln()
static void list_ln (const char * beg, const char * txt) static
Definition at line 24 of file listing.cpp.
References DBGBIT, gbl, lf, LPP, pgno, pgpos, and version.
Referenced by list_init(), and list_line().
list_page()
void list_page (void)
...
Definition at line 75 of file listing.cpp.
References DBGBIT, lf, list_line(), and pgpos.
Referenced by ff_get_stmt(), get_stmt(), init(), print_par_xref(), and printxref().
Variable Documentation
lf
FILE* lf static
Definition at line 18 of file listing.cpp.
Referenced by list_init(), list_ln(), and list_page().
LPP
const int LPP = 60
Definition at line 21 of file listing.cpp.
Referenced by list_ln().
pgno
int pgno static
Definition at line 19 of file listing.cpp.
Referenced by list_init(), and list_ln().
pgpos
int pgpos = 1 static
Fortran source listing file module.
Definition at line 17 of file listing.cpp.
Referenced by list_ln(), and list_page().