flang: listing.h File Reference
listing.h File Reference
#include <stdio.h>
Functions
void list_init (FILE *fd)
...
void list_line (const char *txt)
...
void list_page (void)
...
Function Documentation
list_init()
void list_init (FILE * fd)
...
Definition at line 25 of file listing.c.
References DBGBIT, fd, gbl, lf, list_line(), list_ln(), and pgno.
list_line()
void list_line (const char * txt)
...
Definition at line 97 of file listing.c.
References list_ln().
Referenced by list_init(), and list_page().
list_page()
void list_page (void)
...
Definition at line 130 of file listing.c.
References DBGBIT, lf, list_line(), and pgpos.