flang: list_io.h File Reference
list_io.h File Reference
Functions
int __f90io_ldr (int type, long length, int stride, char *item, __CLEN_T itemlen)
list-directed external file read initialization (defined in ldread.c)
int __f90io_ldw (int type, long length, int stride, char *item, __CLEN_T item_length)
list-directed external file write initializations (defined in ldwrite.c)
Detailed Description
Function declarations for Fortran list IO (files ldread.c/ldwrite.c).
Definition in file list_io.h.
Function Documentation
__f90io_ldr()
int __f90io_ldr (int type, long length, int stride, char * item, __CLEN_T itemlen)
list-directed external file read initialization (defined in ldread.c)
Parameters
type data type (as defined in pghpft.h)
length # items of type to read
stride distance in bytes between items
item where to transfer data to
itemlen
Definition at line 618 of file ldread.c.
References __fortio_assign(), __fortio_errend03(), __fortio_error(), __io_printf, __NCHAR, __STR, byte_cnt, DBGBIT, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FIO_TBL::error, FIO_EERR_DATA_CONVERSION, fioFcbTbls, free_gbl(), gbl_dtype, get_token(), length(), prev_tkntyp, read_record(), restore_gbl(), scan_err, stride, TK_ERROR, TK_NULL, TK_SLASH, TK_VAL, TK_VALS, tkntyp, tknval, and type.
Referenced by __INT_T().
__f90io_ldw()
int __f90io_ldw (int type, long length, int stride, char * item, __CLEN_T item_length)
list-directed external file write initializations (defined in ldwrite.c)
Parameters
type data type (as defined in pghpft.h)
length # items of type to write. May be <= 0
stride distance in bytes between items
item where to transfer data from
item_length
Definition at line 559 of file ldwrite.c.
References __f90io_conv_buf, __fortio_default_convert(), __fortio_errend03(), __fortio_error(), __io_printf, __STR, byte_cnt, DBGBIT, G::decimal, delim, ERR_FLAG, FIO_TBL::error, FALSE, FIO_COMMA, FIO_PLUS, fioFcbTbls, free_gbl(), gbl, Is_complex, last_type, length(), malloc(), p, restore_gbl(), G::round, G::sign, stride, TRUE, type, write_called, and write_item().
Referenced by __INT_T(), and ENTF90IO().