flang: listing.c File Reference
listing.c File Reference
Fortran source listing file module.
#include "gbldefs.h"
#include "global.h"
#include "version.h"
Macros
#define LPP 60
Functions
static void list_ln (const char *, const char *)
void list_init (FILE *fd)
...
void list_line (const char *txt)
...
void list_page (void)
...
Variables
static int pgpos = 1
static FILE * lf
static int pgno
Detailed Description
Fortran source listing file module.
Definition in file listing.c.
Macro Definition Documentation
LPP
#define LPP 60
Definition at line 20 of file listing.c.
Function Documentation
list_init()
void list_init (FILE * fd)
...
Definition at line 25 of file listing.c.
list_line()
void list_line (const char * txt)
...
Definition at line 97 of file listing.c.
Referenced by list_init(), and list_page().
list_ln()
static void list_ln (const char * beg, const char * txt) static
Definition at line 103 of file listing.c.
References DBGBIT, gbl, lf, LPP, pgno, pgpos, and version.
Referenced by list_init(), and list_line().
list_page()
void list_page (void)
...
Definition at line 130 of file listing.c.
Variable Documentation
lf
FILE* lf static
Definition at line 17 of file listing.c.
Referenced by list_init(), list_ln(), and list_page().
pgno
int pgno static
Definition at line 18 of file listing.c.
Referenced by list_init(), and list_ln().
pgpos
int pgpos = 1 static
Definition at line 16 of file listing.c.
Referenced by list_ln(), and list_page().