flang: ll_ftn.h File Reference
ll_ftn.h File Reference
#include "gbldefs.h"
#include "symtab.h"
#include "ll_structure.h"
Functions
ISZ_T get_socptr_offset (int sptr)
...
bool has_multiple_entries (int sptr)
...
bool is_fastcall (int ilix)
...
char * get_entret_arg_name (void)
...
char * get_llvm_ifacenm (SPTR sptr)
...
char * get_local_overlap_var (void)
...
int get_entries_argnum (void)
SPTR get_iface_sptr (SPTR sptr)
...
SPTR get_master_sptr (void)
...
DTYPE get_return_type (SPTR func_sptr)
...
int is_iso_cptr (DTYPE d_dtype)
...
int mk_charlen_address (int sptr)
...
LL_Type * get_ftn_lltype (SPTR sptr)
...
LL_Type * get_local_overlap_vartype (void)
...
void assign_array_lltype (DTYPE dtype, int size, int sptr)
...
void fix_llvm_fptriface (void)
...
void get_local_overlap_size (void)
...
void ll_process_routine_parameters (SPTR func_sptr)
...
void print_entry_subroutine (LL_Module *module)
Write out all Entry's as a separate routine.
void reset_equiv_var (void)
...
void reset_master_sptr (void)
...
void stb_process_routine_parameters (void)
...
void store_llvm_localfptr (void)
void write_llvm_lltype (int sptr)
...
void write_local_overlap (void)
...
void write_master_entry_routine (void)
...
bool need_charlen (DTYPE)
...
Variables
SPTR master_sptr
Function Documentation
assign_array_lltype()
void assign_array_lltype (DTYPE dtype, int size, int sptr)
...
Definition at line 630 of file ll_ftn.cpp.
References LLTYPE, make_array_lltype(), make_lltype_from_dtype(), size, and sptr.
fix_llvm_fptriface()
void fix_llvm_fptriface (void)
...
Definition at line 678 of file ll_ftn.cpp.
References CMPLXFUNC_C, DT_ISCMPLX, DTY, STB::firstusym, gbl, get_iface_sptr(), get_llvm_ifacenm(), ll_process_routine_parameters(), llvm_funcptr_store(), sptr, stb, and stb_process_iface_chlen().
Referenced by process_stb_file().
get_entret_arg_name()
char * get_entret_arg_name (void)
...
Definition at line 1359 of file ll_ftn.cpp.
References aux, AUX::dpdsc_base, get_llvm_name(), and master_sptr.
Referenced by store_return_value_for_entry().
get_entries_argnum()
int get_entries_argnum (void)
This function collect all arguments from all Entry include main routine, removing the duplicates, put into new dpdsc Returns the master_sptr value
Definition at line 880 of file ll_ftn.cpp.
References addnewsym(), aux, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, DT_INT, gbl, has_multiple_entries(), i, ll_process_routine_parameters(), make_new_funcsptr(), master_sptr, name, NEED, NOSYM, opt, sptr, stb, and sym_is_refd().
Referenced by schedule().
get_ftn_lltype()
LL_Type * get_ftn_lltype (SPTR sptr)
...
Definition at line 1391 of file ll_ftn.cpp.
References get_ftn_cmblk_lltype(), get_ftn_extern_lltype(), get_ftn_static_lltype(), LLTYPE, NULL, process_sptr(), and sptr.
get_iface_sptr()
SPTR get_iface_sptr (SPTR sptr)
...
Definition at line 158 of file ll_ftn.cpp.
References DTY, DTyInterface, DTySeqTyElement, sptr, and SPTR_NULL.
Referenced by fix_llvm_fptriface(), get_ftn_func_lltype(), and make_lltype_from_sptr().
get_llvm_ifacenm()
char * get_llvm_ifacenm (SPTR sptr)
...
Definition at line 144 of file ll_ftn.cpp.
References assert, ERR_Fatal, gbl, get_llvm_name(), getitem(), LLVM_LONGTERM_AREA, MAXARGLEN, sptr, and strlen().
Referenced by fix_llvm_fptriface(), get_ftn_func_name(), ll_abi_from_call_site(), ll_convert_iface_sptr(), ll_proto_key(), process_ll_abi_func_ftn_mod(), set_ag_ref(), and write_externs().
get_local_overlap_size()
void get_local_overlap_size (void)
...
Definition at line 772 of file ll_ftn.cpp.
References ALIGN, equiv_type, f90_equiv_sz, gbl, get_llvm_name(), getitem(), ISZ_T, LLVM_LONGTERM_AREA, make_array_lltype(), make_lltype_from_dtype(), name, and strlen().
Referenced by schedule().
get_local_overlap_var()
char * get_local_overlap_var (void)
...
Definition at line 790 of file ll_ftn.cpp.
get_local_overlap_vartype()
LL_Type * get_local_overlap_vartype (void)
...
Definition at line 796 of file ll_ftn.cpp.
get_master_sptr()
SPTR get_master_sptr (void)
...
Definition at line 828 of file ll_ftn.cpp.
References master_sptr.
Referenced by ll_process_routine_parameters(), process_ll_abi_func_ftn_mod(), and schedule().
get_return_type()
DTYPE get_return_type (SPTR func_sptr)
...
...
Parameters
func_sptr Symbol id of function to examine
Definition at line 588 of file ll_ftn.cpp.
References CMPLXFUNC_C, DTY, is_iso_cptr(), TY_CHAR, TY_CMPLX, TY_DCMPLX, and TY_NCHAR.
Referenced by analyze_ret_info(), insert_entry_label(), ll_process_routine_parameters(), make_gblsym(), process_ll_abi_func_ftn_mod(), schedule(), and write_externs().
get_socptr_offset()
ISZ_T get_socptr_offset (int sptr)
...
Definition at line 834 of file ll_ftn.cpp.
has_multiple_entries()
bool has_multiple_entries (int sptr)
...
Definition at line 1346 of file ll_ftn.cpp.
References NOSYM, and sptr.
Referenced by analyze_ret_info(), exp_mp_func_prologue(), gen_return_operand(), get_entries_argnum(), get_ftn_func_name(), insert_jump_entry_instr(), make_stmt(), schedule(), write_instructions(), and write_routine_definition().
is_fastcall()
bool is_fastcall (int ilix)
...
Definition at line 78 of file ll_ftn.cpp.
References ILI_OPC, and ILI_OPND.
is_iso_cptr()
int is_iso_cptr (DTYPE d_dtype)
...
Definition at line 3946 of file dtypeutl.c.
References DTY, DTyAlgTyTag, DTySeqTyElement, and get_iso_derivedtype().
Referenced by _constructf90(), assign(), byvalue_ref_arg(), cmpat_dtype_with_size(), cngtyp2(), find_byval_ref(), func_call2(), get_return_type(), has_private(), ll_process_routine_parameters(), llvm_check_retval_inargs(), lower_ast(), lower_visit_symbol(), normalize_forall(), process_ll_abi_func_ftn_mod(), ptrfunc_call(), ptrsubr_call(), ref_pd(), rewrite_cptr_references(), semant3(), semantio(), and subr_call2().
ll_process_routine_parameters()
void ll_process_routine_parameters (SPTR func_sptr)
...
Definition at line 227 of file ll_ftn.cpp.
References add_ag_typename(), addag_llvm_argdtlist(), arg, assert, aux, char_type(), CMPLXFUNC_C, cpu_llvm_module, create_display_temp_arg(), AUX::curr_entry, DBGTRACE5, DBGTRACEIN, DBGTRACEOUT, ENTRY::display, AUX::dpdsc_base, DT_INT, DT_ISCMPLX, DTY, DTyCharLength, DTYG, DTySeqTyElement, ERR_unused, find_ag(), flg, freearea(), func_has_char_args(), gbl, gen_ref_arg(), generic_dummy_dtype(), get_ag(), get_ftn_func_name(), get_llvm_funcptr_ag(), get_llvm_name(), get_master_sptr(), get_return_type(), getdumlen(), getitem(), LL_ABI_Info_::is_fortran, is_iso_cptr(), is_llvmag_entry(), is_struct_kind(), len, ll_abi_alloc(), ll_abi_classify_arg_dtype(), ll_abi_complete_arg_info(), ll_abi_free(), LL_ARG_UNKNOWN, ll_proto_add_sptr(), ll_proto_get_abi(), ll_proto_key(), ll_shallow_copy_uplevel(), LLVM_SHORTTERM_AREA, make_generic_dummy_lltype(), make_lltype_from_abi_arg(), make_lltype_from_dtype(), LL_ABI_Info_::nargs, char_len::next, NOSYM, NULL, params, process_ll_abi_func_ftn(), STB::scnames, set_ag_argdtlist_is_valid(), set_ag_lltype(), set_ag_return_lltype(), set_llvm_iface_oldname(), set_llvmag_entry(), FLG::smp, char_len::sptr, SPTR_NULL, stb, TY_CHAR, TY_NCHAR, STB::tynames, type, and XBIT.
Referenced by exp_smp(), fix_llvm_fptriface(), get_entries_argnum(), ll_load_outlined_args(), ll_make_kmpc_proto(), mk_function_call(), and stb_process_routine_parameters().
mk_charlen_address()
int mk_charlen_address (int sptr)
...
Definition at line 1367 of file ll_ftn.cpp.
References ad2ili(), ad3ili(), ad_acon(), ad_aconi(), addnme(), aux, AUX::curr_entry, ENTRY::display, get_sptr_uplevel_address(), IL_AADD, ili, mem(), NT_VAR, off, and sptr.
Referenced by charlen().
need_charlen()
bool need_charlen (DTYPE dtype)
...
Definition at line 59 of file ll_ftn.cpp.
References DTY, DTYG, DTySeqTyElement, TY_CHAR, and TY_NCHAR.
Referenced by loadUplevelArgsForRegion().
print_entry_subroutine()
void print_entry_subroutine (LL_Module * module)
Write out all Entry's as a separate routine.
Each entry will call a master/common routine (MCR). The first argument to the MCR will determine which label(Entry) control will jump to upon entry into the MCR. If the MCR is a function, the next argument will be the function's return value. The next argument(s) will be all non-duplicate aggregate arguments for all entries. The MCR will always effectively be a subroutine.
Definition at line 1067 of file ll_ftn.cpp.
reset_equiv_var()
void reset_equiv_var (void)
...
Definition at line 815 of file ll_ftn.cpp.
reset_master_sptr()
void reset_master_sptr (void)
...
Definition at line 822 of file ll_ftn.cpp.
stb_process_routine_parameters()
void stb_process_routine_parameters (void)
...
Definition at line 131 of file ll_ftn.cpp.
References gbl, ll_process_routine_parameters(), NOSYM, and stb_process_iface_chlen().
Referenced by process_stb_file(), and schedule().
store_llvm_localfptr()
void store_llvm_localfptr (void)
Store interface function name in fptr_local table. This table is done per routine. It stores the name that will be used to search for function signature of what it points to. The interface name is in the form of <getname(gbl.currsub)>$<getname(iface)>, which is done in get_llvm_ifacenm().
Definition at line 751 of file ll_ftn.cpp.
References gbl.
Referenced by schedule().
write_llvm_lltype()
void write_llvm_lltype (int sptr)
...
Definition at line 636 of file ll_ftn.cpp.
References LLTYPE, sptr, and write_type().
write_local_overlap()
void write_local_overlap (void)
...
Definition at line 802 of file ll_ftn.cpp.
write_master_entry_routine()
void write_master_entry_routine (void)
...
Definition at line 1352 of file ll_ftn.cpp.
References a, build_routine_and_parameter_entries(), master_sptr, NULL, and process_ll_abi_func_ftn().
Referenced by write_routine_definition().
Variable Documentation
master_sptr
SPTR master_sptr extern
Definition at line 52 of file ll_ftn.cpp.
Referenced by get_entret_arg_name(), get_entries_argnum(), get_master_sptr(), insert_jump_entry_instr(), print_entry_subroutine(), reset_master_sptr(), write_dummy_as_local_in_entry(), and write_master_entry_routine().