flang: ll_ftn.cpp File Reference
ll_ftn.cpp File Reference
#include "ll_ftn.h"
#include "exp_rte.h"
#include "ili.h"
#include "dinit.h"
#include "cg.h"
#include "mach.h"
#include "fih.h"
#include "pd.h"
#include "llutil.h"
#include <stdlib.h>
#include "expand.h"
#include "llassem.h"
#include "cgllvm.h"
#include "cgmain.h"
#include "symfun.h"
Classes
struct char_len
Macros
#define DBGTRON DBGBIT(12, 0x20)
#define DBGTRACEIN(str) DBGXTRACEIN(DBGTRON, 1, str)
#define DBGTRACEOUT(str) DBGXTRACEOUT(DBGTRON, 1, str)
#define DBGDUMPLLTYPE(str, llt) DBGXDUMPLLTYPE(DBGTRON, 1, str, llt)
#define DBGTRACE5(str, p1, p2, p3, p4, p5) DBGXTRACE5(DBGTRON, 1, str, p1, p2, p3, p4, p5)
#define MAXARGLEN 256
#define LLVM_SHORTTERM_AREA 14
Typedefs
typedef struct char_len sclen
Functions
static SPTR create_display_temp_arg (DTYPE ref_dtype)
Create a procedure DUMMY argument to hold a closure/display pointer.
bool need_charlen (DTYPE dtype)
...
bool is_fastcall (int ilix)
...
static void stb_process_iface_chlen (int sptr)
void stb_process_routine_parameters (void)
...
char * get_llvm_ifacenm (SPTR sptr)
...
SPTR get_iface_sptr (SPTR sptr)
...
static const char * get_ftn_func_name (SPTR func_sptr, bool *has_iface)
static void gen_ref_arg (SPTR param_sptr, SPTR func_sptr, LL_Type *ref_dummy, int param_num, SPTR gblsym)
Called by ll_process_routine_parameters() to generate a pass by reference parameter.
void ll_process_routine_parameters (SPTR func_sptr)
...
int is_iso_cptr (DTYPE d_dtype)
...
DTYPE get_return_type (SPTR func_sptr)
Get the return DTYPE of the function, func_sptr.
void assign_array_lltype (DTYPE dtype, int size, int sptr)
...
void write_llvm_lltype (int sptr)
...
void fix_llvm_fptriface (void)
...
void store_llvm_localfptr (void)
void get_local_overlap_size (void)
...
char * get_local_overlap_var (void)
...
LL_Type * get_local_overlap_vartype (void)
...
void write_local_overlap (void)
...
void reset_equiv_var (void)
...
void reset_master_sptr (void)
...
SPTR get_master_sptr (void)
...
ISZ_T get_socptr_offset (int sptr)
...
static char * get_master_entry_name (SPTR sptr)
static SPTR make_new_funcsptr (SPTR oldsptr)
int get_entries_argnum (void)
static void DeclareSPtrAsLocal (SPTR sptr, int flag)
static void write_dummy_as_local_in_entry (int sptr)
void print_entry_subroutine (LL_Module *module)
Write out all Entry's as a separate routine.
bool has_multiple_entries (int sptr)
...
void write_master_entry_routine (void)
...
char * get_entret_arg_name (void)
...
int mk_charlen_address (int sptr)
...
LL_Type * get_ftn_lltype (SPTR sptr)
...
Variables
SPTR master_sptr = SPTR_NULL
static ISZ_T f90_equiv_sz = 0
static LL_Type * equiv_type
static char * equiv_var
Detailed Description
FIXME - document what this is
Definition in file ll_ftn.cpp.
Macro Definition Documentation
DBGDUMPLLTYPE
#define DBGDUMPLLTYPE (str, llt) DBGXDUMPLLTYPE(DBGTRON, 1, str, llt)
Definition at line 40 of file ll_ftn.cpp.
DBGTRACE5
#define DBGTRACE5 (str, p1, p2, p3, p4, p5) DBGXTRACE5(DBGTRON, 1, str, p1, p2, p3, p4, p5)
Definition at line 41 of file ll_ftn.cpp.
DBGTRACEIN
#define DBGTRACEIN (str) DBGXTRACEIN(DBGTRON, 1, str)
Definition at line 38 of file ll_ftn.cpp.
DBGTRACEOUT
#define DBGTRACEOUT (str) DBGXTRACEOUT(DBGTRON, 1, str)
Definition at line 39 of file ll_ftn.cpp.
DBGTRON
#define DBGTRON DBGBIT(12, 0x20)
Definition at line 37 of file ll_ftn.cpp.
LLVM_SHORTTERM_AREA
#define LLVM_SHORTTERM_AREA 14
Definition at line 45 of file ll_ftn.cpp.
MAXARGLEN
#define MAXARGLEN 256
Definition at line 44 of file ll_ftn.cpp.
Typedef Documentation
sclen
typedef struct char_len sclen
Function Documentation
assign_array_lltype()
void assign_array_lltype (DTYPE dtype, int size, int sptr)
...
Definition at line 630 of file ll_ftn.cpp.
References LLTYPE, make_array_lltype(), make_lltype_from_dtype(), size, and sptr.
create_display_temp_arg()
static SPTR create_display_temp_arg (DTYPE ref_dtype) static
Create a procedure DUMMY argument to hold a closure/display pointer.
Parameters
ref_dtype is a dtype for the display argument.
Returns
the symbol table pointer of the newly created display argument.
Definition at line 218 of file ll_ftn.cpp.
References gbl, and getccsym().
Referenced by ll_process_routine_parameters().
DeclareSPtrAsLocal()
static void DeclareSPtrAsLocal (SPTR sptr, int flag) static
Definition at line 999 of file ll_ftn.cpp.
References generic_dummy_dtype(), get_llvm_name(), make_lltype_from_dtype(), print_nl(), print_token(), sptr, and write_type().
Referenced by write_dummy_as_local_in_entry().
fix_llvm_fptriface()
void fix_llvm_fptriface (void)
...
Definition at line 678 of file ll_ftn.cpp.
References CMPLXFUNC_C, DT_ISCMPLX, DTY, STB::firstusym, gbl, get_iface_sptr(), get_llvm_ifacenm(), ll_process_routine_parameters(), llvm_funcptr_store(), sptr, stb, and stb_process_iface_chlen().
Referenced by process_stb_file().
gen_ref_arg()
static void gen_ref_arg (SPTR param_sptr, SPTR func_sptr, LL_Type * ref_dummy, int param_num, SPTR gblsym) static
Called by ll_process_routine_parameters() to generate a pass by reference parameter.
Definition at line 200 of file ll_ftn.cpp.
References addag_llvm_argdtlist(), make_lltype_from_dtype(), and make_ptr_lltype().
Referenced by ll_process_routine_parameters().
get_entret_arg_name()
char * get_entret_arg_name (void)
...
Definition at line 1359 of file ll_ftn.cpp.
References aux, AUX::dpdsc_base, get_llvm_name(), and master_sptr.
Referenced by store_return_value_for_entry().
get_entries_argnum()
int get_entries_argnum (void)
This function collect all arguments from all Entry include main routine, removing the duplicates, put into new dpdsc Returns the master_sptr value
Definition at line 880 of file ll_ftn.cpp.
References addnewsym(), aux, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, DT_INT, gbl, has_multiple_entries(), i, ll_process_routine_parameters(), make_new_funcsptr(), master_sptr, name, NEED, NOSYM, opt, sptr, stb, and sym_is_refd().
Referenced by schedule().
get_ftn_func_name()
static const char * get_ftn_func_name (SPTR func_sptr, bool * has_iface) static
Definition at line 173 of file ll_ftn.cpp.
References gbl, get_llvm_ifacenm(), get_llvm_name(), get_main_progname(), has_multiple_entries(), NULL, and RU_PROG.
Referenced by ll_process_routine_parameters().
get_ftn_lltype()
LL_Type * get_ftn_lltype (SPTR sptr)
...
Definition at line 1391 of file ll_ftn.cpp.
References get_ftn_cmblk_lltype(), get_ftn_extern_lltype(), get_ftn_static_lltype(), LLTYPE, NULL, process_sptr(), and sptr.
get_iface_sptr()
SPTR get_iface_sptr (SPTR sptr)
...
Definition at line 158 of file ll_ftn.cpp.
References DTY, DTyInterface, DTySeqTyElement, sptr, and SPTR_NULL.
Referenced by fix_llvm_fptriface(), get_ftn_func_lltype(), and make_lltype_from_sptr().
get_llvm_ifacenm()
char * get_llvm_ifacenm (SPTR sptr)
...
Definition at line 144 of file ll_ftn.cpp.
References assert, ERR_Fatal, gbl, get_llvm_name(), getitem(), LLVM_LONGTERM_AREA, MAXARGLEN, sptr, and strlen().
Referenced by fix_llvm_fptriface(), get_ftn_func_name(), ll_abi_from_call_site(), ll_convert_iface_sptr(), ll_proto_key(), process_ll_abi_func_ftn_mod(), set_ag_ref(), and write_externs().
get_local_overlap_size()
void get_local_overlap_size (void)
...
Definition at line 772 of file ll_ftn.cpp.
References ALIGN, equiv_type, f90_equiv_sz, gbl, get_llvm_name(), getitem(), ISZ_T, LLVM_LONGTERM_AREA, make_array_lltype(), make_lltype_from_dtype(), name, and strlen().
Referenced by schedule().
get_local_overlap_var()
char * get_local_overlap_var (void)
...
Definition at line 790 of file ll_ftn.cpp.
References equiv_var.
Referenced by process_local_sptr().
get_local_overlap_vartype()
LL_Type * get_local_overlap_vartype (void)
...
Definition at line 796 of file ll_ftn.cpp.
References equiv_type.
Referenced by make_lltype_from_sptr().
get_master_entry_name()
static char * get_master_entry_name (SPTR sptr) static
Definition at line 840 of file ll_ftn.cpp.
References get_llvm_name(), MAXARGLEN, and sptr.
Referenced by make_new_funcsptr().
get_master_sptr()
SPTR get_master_sptr (void)
...
Definition at line 828 of file ll_ftn.cpp.
References master_sptr.
Referenced by ll_process_routine_parameters(), process_ll_abi_func_ftn_mod(), and schedule().
get_return_type()
DTYPE get_return_type (SPTR func_sptr)
Get the return DTYPE of the function, func_sptr.
...
Parameters
func_sptr Symbol id of function to examine
Definition at line 588 of file ll_ftn.cpp.
References CMPLXFUNC_C, DTY, is_iso_cptr(), TY_CHAR, TY_CMPLX, TY_DCMPLX, and TY_NCHAR.
Referenced by analyze_ret_info(), insert_entry_label(), ll_process_routine_parameters(), make_gblsym(), process_ll_abi_func_ftn_mod(), schedule(), and write_externs().
get_socptr_offset()
ISZ_T get_socptr_offset (int sptr)
...
Definition at line 834 of file ll_ftn.cpp.
References f90_equiv_sz, and sptr.
Referenced by variable_offset_in_aggregate().
has_multiple_entries()
bool has_multiple_entries (int sptr)
...
Definition at line 1346 of file ll_ftn.cpp.
References NOSYM, and sptr.
Referenced by analyze_ret_info(), exp_mp_func_prologue(), gen_return_operand(), get_entries_argnum(), get_ftn_func_name(), insert_jump_entry_instr(), make_stmt(), schedule(), write_instructions(), and write_routine_definition().
is_fastcall()
bool is_fastcall (int ilix)
...
Definition at line 78 of file ll_ftn.cpp.
References ILI_OPC, and ILI_OPND.
is_iso_cptr()
int is_iso_cptr (DTYPE d_dtype)
...
Definition at line 566 of file ll_ftn.cpp.
References DTY, DTyAlgTyTag, and DTySeqTyElement.
Referenced by get_return_type(), and ll_process_routine_parameters().
ll_process_routine_parameters()
void ll_process_routine_parameters (SPTR func_sptr)
...
Definition at line 227 of file ll_ftn.cpp.
References add_ag_typename(), addag_llvm_argdtlist(), arg, assert, aux, char_type(), CMPLXFUNC_C, cpu_llvm_module, create_display_temp_arg(), AUX::curr_entry, DBGTRACE5, DBGTRACEIN, DBGTRACEOUT, ENTRY::display, AUX::dpdsc_base, DT_INT, DT_ISCMPLX, DTY, DTyCharLength, DTYG, DTySeqTyElement, ERR_unused, find_ag(), flg, freearea(), func_has_char_args(), gbl, gen_ref_arg(), generic_dummy_dtype(), get_ag(), get_ftn_func_name(), get_llvm_funcptr_ag(), get_llvm_name(), get_master_sptr(), get_return_type(), getdumlen(), getitem(), LL_ABI_Info_::is_fortran, is_iso_cptr(), is_llvmag_entry(), is_struct_kind(), len, ll_abi_alloc(), ll_abi_classify_arg_dtype(), ll_abi_complete_arg_info(), ll_abi_free(), LL_ARG_UNKNOWN, ll_proto_add_sptr(), ll_proto_get_abi(), ll_proto_key(), ll_shallow_copy_uplevel(), LLVM_SHORTTERM_AREA, make_generic_dummy_lltype(), make_lltype_from_abi_arg(), make_lltype_from_dtype(), LL_ABI_Info_::nargs, char_len::next, NOSYM, NULL, params, process_ll_abi_func_ftn(), STB::scnames, set_ag_argdtlist_is_valid(), set_ag_lltype(), set_ag_return_lltype(), set_llvm_iface_oldname(), set_llvmag_entry(), FLG::smp, char_len::sptr, SPTR_NULL, stb, TY_CHAR, TY_NCHAR, STB::tynames, type, and XBIT.
Referenced by exp_smp(), fix_llvm_fptriface(), get_entries_argnum(), ll_load_outlined_args(), ll_make_kmpc_proto(), mk_function_call(), and stb_process_routine_parameters().
make_new_funcsptr()
static SPTR make_new_funcsptr (SPTR oldsptr) static
Definition at line 848 of file ll_ftn.cpp.
References CUDAG, CUDAP, FUNCLINEG, FUNCLINEP, get_master_entry_name(), getsym(), NOSYM, sptr, strlen(), and sym_is_refd().
Referenced by get_entries_argnum().
mk_charlen_address()
int mk_charlen_address (int sptr)
...
Definition at line 1367 of file ll_ftn.cpp.
References ad2ili(), ad3ili(), ad_acon(), ad_aconi(), addnme(), aux, AUX::curr_entry, ENTRY::display, get_sptr_uplevel_address(), IL_AADD, ili, mem(), NT_VAR, off, and sptr.
Referenced by charlen().
need_charlen()
bool need_charlen (DTYPE dtype)
...
Definition at line 59 of file ll_ftn.cpp.
References DTY, DTYG, DTySeqTyElement, TY_CHAR, and TY_NCHAR.
Referenced by loadUplevelArgsForRegion().
print_entry_subroutine()
void print_entry_subroutine (LL_Module * module)
Write out all Entry's as a separate routine.
Each entry will call a master/common routine (MCR). The first argument to the MCR will determine which label(Entry) control will jump to upon entry into the MCR. If the MCR is a function, the next argument will be the function's return value. The next argument(s) will be all non-duplicate aggregate arguments for all entries. The MCR will always effectively be a subroutine.
Definition at line 1067 of file ll_ftn.cpp.
References arg, LL_ABI_Info_::arg, aux, build_routine_and_parameter_entries(), CMPLXFUNC_C, AUX::dpdsc_base, DT_INT, DT_ISCMPLX, DTY, DTYG, DTySeqTyElement, LL_ABI_Info_::extend_abi_return, func_has_char_args(), gbl, get_llvm_name(), getdumlen(), getitem(), hash_functions_direct, hashset_alloc(), hashset_clear(), hashset_free(), hashset_insert(), hashset_lookup(), i, INT2HKEY, LL_Module::ir, ll_feature_explicit_gep_load_type, ll_proto_add_sptr(), ll_proto_key(), ll_proto_set_defined_body(), LLTYPE, LLVM_SHORTTERM_AREA, make_generic_dummy_lltype(), make_lltype_from_abi_arg(), make_lltype_from_dtype(), make_ptr_lltype(), make_tmps(), master_sptr, LL_ABI_Info_::nargs, char_len::next, NOSYM, NULL, num, print_nl(), print_space(), print_tmp_name(), print_token(), process_ll_abi_func_ftn(), process_sptr(), reset_expr_id(), SNAME, sptr, char_len::sptr, LL_ABI_ArgInfo_::sptr, tmp, TY_CHAR, TY_NCHAR, write_dummy_as_local_in_entry(), and write_type().
Referenced by schedule().
reset_equiv_var()
void reset_equiv_var (void)
...
Definition at line 815 of file ll_ftn.cpp.
References equiv_type, and NULL.
Referenced by assem_end().
reset_master_sptr()
void reset_master_sptr (void)
...
Definition at line 822 of file ll_ftn.cpp.
References master_sptr, and SPTR_NULL.
Referenced by assem_end().
stb_process_iface_chlen()
static void stb_process_iface_chlen (int sptr) static
Definition at line 102 of file ll_ftn.cpp.
References aux, DDTG, AUX::dpdsc_base, e, getdumlen(), i, and sptr.
Referenced by fix_llvm_fptriface(), and stb_process_routine_parameters().
stb_process_routine_parameters()
void stb_process_routine_parameters (void)
...
Definition at line 131 of file ll_ftn.cpp.
References gbl, ll_process_routine_parameters(), NOSYM, and stb_process_iface_chlen().
Referenced by process_stb_file(), and schedule().
store_llvm_localfptr()
void store_llvm_localfptr (void)
Store interface function name in fptr_local table. This table is done per routine. It stores the name that will be used to search for function signature of what it points to. The interface name is in the form of <getname(gbl.currsub)>$<getname(iface)>, which is done in get_llvm_ifacenm().
Definition at line 751 of file ll_ftn.cpp.
References gbl.
Referenced by schedule().
write_dummy_as_local_in_entry()
static void write_dummy_as_local_in_entry (int sptr) static
Definition at line 1019 of file ll_ftn.cpp.
References aux, DeclareSPtrAsLocal(), AUX::dpdsc_base, i, master_sptr, and sptr.
Referenced by print_entry_subroutine().
write_llvm_lltype()
void write_llvm_lltype (int sptr)
...
Definition at line 636 of file ll_ftn.cpp.
References LLTYPE, sptr, and write_type().
write_local_overlap()
void write_local_overlap (void)
...
Definition at line 802 of file ll_ftn.cpp.
References equiv_type, print_token(), and write_type().
Referenced by schedule().
write_master_entry_routine()
void write_master_entry_routine (void)
...
Definition at line 1352 of file ll_ftn.cpp.
References a, build_routine_and_parameter_entries(), master_sptr, NULL, and process_ll_abi_func_ftn().
Referenced by write_routine_definition().
Variable Documentation
equiv_type
LL_Type* equiv_type static
Definition at line 55 of file ll_ftn.cpp.
Referenced by get_local_overlap_size(), get_local_overlap_vartype(), reset_equiv_var(), and write_local_overlap().
equiv_var
char* equiv_var static
Definition at line 56 of file ll_ftn.cpp.
Referenced by get_local_overlap_var().
f90_equiv_sz
ISZ_T f90_equiv_sz = 0 static
Definition at line 54 of file ll_ftn.cpp.
Referenced by get_local_overlap_size(), and get_socptr_offset().
master_sptr
SPTR master_sptr = SPTR_NULL
Definition at line 52 of file ll_ftn.cpp.
Referenced by get_entret_arg_name(), get_entries_argnum(), get_master_sptr(), insert_jump_entry_instr(), print_entry_subroutine(), reset_master_sptr(), write_dummy_as_local_in_entry(), and write_master_entry_routine().