flang: ll_structure.cpp File Reference
ll_structure.cpp File Reference
LLVM bridge representation.
#include "gbldefs.h"
#include "error.h"
#include "ll_builder.h"
#include "ll_structure.h"
#include "lldebug.h"
#include "global.h"
#include "go.h"
#include "llassem.h"
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
Classes
struct triple_info
Macros
#define NEEDS_ESC(C) ((C) < 32 || (C) >= 127 || (C) == '\\' || (C) == '"')
#define MIN_FLEX_SIZE 4
Functions
LL_IRVersion get_llvm_version (void)
Get the LLVM version being used The -x 249 flag is set by the -Mllvm= driver option.
static void * ll_manage_mem (LLVMModuleRef module, void *space)
static char * ll_manage_strdup (LLVMModuleRef module, const char *str)
static void * ll_manage_calloc (LLVMModuleRef module, size_t members, size_t member_size)
static void * ll_manage_malloc (LLVMModuleRef module, size_t malloc_size)
static void ll_destroy_instruction (struct LL_Instruction_ *instruction)
static void ll_destroy_basic_block (struct LL_BasicBlock_ *basic_block)
static void free_iterator (hash_key_t key, void *context)
void ll_destroy_function (struct LL_Function_ *function)
Deallocate all memory used by function.
void ll_destroy_mem (struct LL_ManagedMallocs_ *current)
...
static BIGUINT64 get_num_subtypes (const struct LL_Type_ *type)
static hash_value_t types_hash (hash_key_t key)
static int types_equal (hash_key_t key_a, hash_key_t key_b)
static char * unique_name (hashset_t names, char prefix, const char *format, va_list ap)
static hash_value_t constants_hash (hash_key_t key)
static int constants_equal (hash_key_t key_a, hash_key_t key_b)
static hash_value_t mdnode_hash (hash_key_t key)
static int mdnode_equal (hash_key_t key_a, hash_key_t key_b)
void llObjtodbgPush (LL_ObjToDbgList *odl, LL_MDRef md)
...
void llObjtodbgFree (LL_ObjToDbgList *ods)
...
void ll_reset_module_types (LLVMModuleRef module)
Reset the id map for named struct types.
static void compute_ir_feature_vector (LLVMModuleRef module, enum LL_IRVersion vers)
Compute the set of IR features in module when generating IR for the specified LLVM version.
unsigned ll_feature_dwarf_version (const LL_IRFeatures *feature)
Convert the cached DWARF version to an unsigned.
static void compute_datalayout (LLVMModuleRef module)
void ll_destroy_module (LLVMModuleRef module)
...
LLVMModuleRef ll_create_module (const char *module_name, const char *target_triple, enum LL_IRVersion llvm_ir_version)
...
void add_linker_directives (LLVMModuleRef module)
struct LL_Function_ * ll_create_function (LLVMModuleRef module, const char *name, LL_Type *return_type, int is_kernel, int launch_bounds, int launch_bounds_minctasm, const char *calling_convention, enum LL_LinkageType linkage)
...
LL_Function * ll_create_function_from_type (LL_Type *func_type, const char *name)
Create an LL_Function.
LL_Function * ll_create_device_function_from_type (LLVMModuleRef module, LL_Type *func_type, const char *name, int is_kernel, int launch_bounds, const char *calling_convention, enum LL_LinkageType linkage)
Creates NVVM function.
void ll_create_sym (struct LL_Symbols_ *symbol_table, unsigned index, LL_Value *new_value)
...
void ll_set_function_num_arguments (struct LL_Function_ *function, int num_args)
...
void ll_set_function_argument (struct LL_Function_ *function, int index, LL_Value *argument)
...
const char * ll_get_str_type_for_basic_type (enum LL_BaseDataType type)
...
static ISZ_T LLTypeGetBytesUnchecked (LL_Type *type, int *noSize)
Get the size of a type in bytes without checks.
ISZ_T ll_type_bytes (LL_Type *type)
Get the size of a type in bytes.
ISZ_T ll_type_bytes_unchecked (LL_Type *type)
Get the size of a type in bytes without checks.
unsigned ll_type_int_bits (LL_Type *type)
Get the number of bits in the given integer type.
int ll_type_is_pointer_to_function (LL_Type *ty)
...
LL_Type * ll_type_array_elety (LL_Type *ty)
...
int ll_type_is_fp (LL_Type *ty)
...
int ll_type_is_mem_seq (LL_Type *ty)
...
static LL_Value * ll_create_blank_value (LLVMModuleRef module, const char *data)
Create a "blank" value.
LL_Value * ll_create_pointer_value (LLVMModuleRef module, enum LL_BaseDataType type, const char *data, int addrspace)
...
LL_Value * ll_create_value_from_type (LLVMModuleRef module, LL_Type *type, const char *data)
...
LL_Value * ll_create_array_value_from_type (LLVMModuleRef module, LL_Type *type, const char *data, int addrspace)
...
LL_Value * ll_create_pointer_value_from_type (LLVMModuleRef module, LL_Type *type, const char *data, int addrspace)
...
int ll_get_pointer_addrspace (LL_Type *ptr)
get pointer's address space
static struct LL_Type_ * unique_type (LLVMModuleRef module, const struct LL_Type_ *type)
LL_Type * ll_create_basic_type (LLVMModuleRef module, enum LL_BaseDataType type, int addrspace)
...
LL_Type * ll_create_int_type_with_addrspace (LLVMModuleRef module, unsigned bits, int addrspace)
Create an integer type with bits bits.
LL_Type * ll_create_int_type (LLVMModuleRef module, unsigned bits)
Create an integer type with bits bits.
LL_Type * ll_get_addrspace_type (LL_Type *type, int addrspace)
Get a version of type in different address space.
LL_Type * ll_get_pointer_type (LL_Type *type)
Create a pointer type pointing to the given pointee type.
LL_Type * ll_get_array_type (LL_Type *type, BIGUINT64 num_elements, int addrspace)
...
LL_Type * ll_get_vector_type (LL_Type *type, unsigned num_elements)
Get a vector type <num x elem>
void ll_set_struct_body (LL_Type *ctype, LL_Type *const *elements, unsigned *const offsets, char *const pads, unsigned num_elements, int is_packed)
Replace the entire body of a named struct type. This may be used to change the number of elements in an existing named struct.
LL_Value * ll_named_struct_type_exists (LLVMModuleRef module, int id, const char *format,...)
...
LL_Type * ll_create_named_struct_type (LLVMModuleRef module, int id, bool unique, const char *format,...)
Create a new named struct type in the module.
void ll_remove_struct_type (LLVMModuleRef module, int struct_id)
Remove struct type from hashmap.
LL_Type * ll_get_struct_type (LLVMModuleRef module, int struct_id, int required)
Get an existing named struct type by id.
LL_Type * ll_create_anon_struct_type (LLVMModuleRef module, LL_Type *elements[], unsigned num_elements, bool is_packed, int addrspace)
Get an anonymous struct type.
LL_Type * ll_create_function_type (LLVMModuleRef module, LL_Type *args[], unsigned num_args, int is_varargs)
Get a function type.
const char * ll_get_calling_conv_str (enum LL_CallConv cc)
Get the textual representation of a calling convention.
static unsigned intern_constant (LLVMModuleRef module, LL_Type *type, const char *data)
static unsigned intern_const_int (LLVMModuleRef module, unsigned bits, long long value)
LL_Value * ll_get_const_int (LLVMModuleRef module, unsigned bits, long long value)
Get a shared LL_Value representing a constant integer of up to 64 bits.
LL_Value * ll_get_global_pointer (const char *name, LL_Type *type)
Get a pointer to an LLVM global given its name and type.
LL_Value * ll_get_function_pointer (LLVMModuleRef module, LL_Function *function)
Get the constant function pointer value representing a function.
static LL_Type * apply_gep_index (LL_Type *type, unsigned idx)
LL_Value * ll_get_const_gep (LLVMModuleRef module, LL_Value *ptr, unsigned num_idx,...)
Get a shared LL_Value representing a constant getelementptr of the provided pointer value.
LL_Value * ll_get_const_bitcast (LLVMModuleRef module, LL_Value *value, LL_Type *type)
Get a shared LL_Value representing a constant bitcast of value to type.
LL_Value * ll_get_const_addrspacecast (LLVMModuleRef module, LL_Value *value, LL_Type *type)
Get a shared LL_Value representing an addrspacecast of the pointer value to type.
LL_MDRef ll_get_md_i1 (int value)
Get an LL_MDRef representing an i1 boolean value.
LL_MDRef ll_get_md_i32 (LLVMModuleRef module, int value)
Get an LL_MDRef representing an i32 integer value.
LL_MDRef ll_get_md_i64 (LLVMModuleRef module, long long value)
Get an LL_MDRef representing an i64 integer value.
LL_MDRef ll_get_md_rawstring (LLVMModuleRef module, const void *rawstr, size_t length)
Get an LL_MDRef representing a raw binary string.
LL_MDRef ll_get_md_string (LLVMModuleRef module, const char *str)
Get an LL_MDRef representing a string.
LL_MDRef ll_get_md_value (LLVMModuleRef module, LL_Value *value)
Get an LL_MDRef representing an arbitrary LLVM constant value.
static LL_MDNode * alloc_mdnode (LLVMModuleRef module, enum LL_MDClass mdclass, const LL_MDRef *elems, unsigned nelems, int is_distinct)
static LL_MDNode * alloc_flexible_mdnode (LLVMModuleRef module, const LL_MDRef *elems, unsigned nelems)
static void mdnode_append (LLVMModuleRef module, LL_MDNode **pnode, LL_MDRef elem)
Append element to flexible mdnode.
unsigned ll_reserve_md_node (LLVMModuleRef module)
Reserve a slot for an LL_MDNode.
static INLINE unsigned insert_mdnode (LLVMModuleRef module, LL_MDNode *node)
Insert an allocated mdnode into the module's list.
void ll_set_md_node (LLVMModuleRef module, unsigned mdNum, LL_MDNode *node)
...
LL_MDRef ll_get_md_node (LLVMModuleRef module, enum LL_MDClass mdclass, const LL_MDRef *elems, unsigned nelems)
Get an LL_MDRef representing a numbered metadata node.
void ll_add_global_debug (LLVMModuleRef module, int sptr, LL_MDRef mdnode)
Add sptr → mdnode to global debug map.
LL_MDRef ll_get_global_debug (LLVMModuleRef module, int sptr)
...
LL_MDRef ll_create_distinct_md_node (LLVMModuleRef module, enum LL_MDClass mdclass, const LL_MDRef *elems, unsigned nelems)
Create a distinct metadata node which will not be uniqued with other identical metadata nodes.
LL_MDRef ll_create_flexible_md_node (LLVMModuleRef module)
Create a distinct metadata node that can have elements appended.
void ll_extend_md_node (LLVMModuleRef module, LL_MDRef flexnode, LL_MDRef elem)
Append an element to end of a flexible metadata node.
void ll_update_md_node (LLVMModuleRef module, LL_MDRef node_to_update, unsigned elem_index, LL_MDRef elem)
Update one of the elements in a metadata node.
void ll_set_named_md_node (LLVMModuleRef module, enum LL_MDName name, const LL_MDRef *elems, unsigned nelems)
Add a named metadata node to the module.
void ll_extend_named_md_node (LLVMModuleRef module, enum LL_MDName name, LL_MDRef elem)
Append an element to a named metadata node.
void ll_append_llvm_used (LLVMModuleRef module, LL_Value *ptr)
Append a pointer to the @llvm.used global.
static void append_global (LLVMModuleRef module, LL_Object *object)
static LL_Object * create_global (LLVMModuleRef module, enum LL_ObjectKind kind, LL_Type *type, int addrspace, const char *format, va_list args)
LL_Object * ll_create_global_alias (LL_Value *aliasee_ptr, const char *format,...)
Create a new global alias.
const char * ll_create_local_name (LL_Function *function, const char *format,...)
Create a new unique name for a local value in function.
LL_Object * ll_create_local_object (LL_Function *function, LL_Type *type, unsigned align_bytes, const char *format,...)
Create a new local object in function.
const char * ll_proto_key (SPTR func_sptr)
Find the function (interface) name to be used as a key.
void ll_proto_init (void)
Initialization.
static void ll_proto_update_name (LL_FnProto *proto, const char *fnname)
LL_FnProto * ll_proto_add (const char *fnname, struct LL_ABI_Info_ *abi)
Uniquely instantiate a new proto to the global map.
LL_FnProto * ll_proto_add_sptr (SPTR func_sptr, struct LL_ABI_Info_ *abi)
Convienience routine to ll_proto_add.
void ll_proto_set_abi (const char *fnname, struct LL_ABI_Info_ *abi)
...
struct LL_ABI_Info_ * ll_proto_get_abi (const char *fnname)
...
void ll_proto_set_defined_body (const char *fnname, bool has_defined)
Set the flag "function has body".
bool ll_proto_has_defined_body (const char *fnname)
...
void ll_proto_set_weak (const char *fnname, bool is_weak)
Set the flag "function is weak".
bool ll_proto_is_weak (const char *fnname)
...
void ll_proto_set_intrinsic (const char *fnname, const char *intrinsic_decl_str)
Set compiler generated intrinsic string.
void ll_proto_iterate (LL_FnProto_Handler callback)
...
static void dump_proto (int counter, const LL_FnProto *proto)
void ll_proto_dump (void)
Debugging: Dump the contents of the map.
void ll_add_module_debug (hashmap_t map, const char *module_name, LL_MDRef mdnode)
Add module_name → mdnode to module debug map.
LL_MDRef ll_get_module_debug (hashmap_t map, const char *module_name)
Variables
static const hash_functions_t types_hash_functions = {types_hash, types_equal}
static const hash_functions_t constants_hash_functions
static const hash_functions_t mdnode_hash_functions
static const struct triple_info known_triples []
static hashmap_t _ll_proto_map
static LL_FnProto * _ll_proto_head
Detailed Description
LLVM bridge representation.
Definition in file ll_structure.cpp.
Macro Definition Documentation
MIN_FLEX_SIZE
#define MIN_FLEX_SIZE 4
Definition at line 2089 of file ll_structure.cpp.
NEEDS_ESC
#define NEEDS_ESC (C) ((C) < 32 || (C) >= 127 || (C) == '\\' || (C) == '"')
Definition at line 1984 of file ll_structure.cpp.
Function Documentation
add_linker_directives()
void add_linker_directives (LLVMModuleRef module)
Definition at line 593 of file ll_structure.cpp.
References LL_IRFeatures_::debug_info_version, flg, get_llvm_version(), i, LL_Module::ir, FLG::linker_directives, ll_extend_named_md_node(), ll_feature_versioned_dw_tag, LL_Version_5_0, llmd_add_i32(), llmd_add_md(), llmd_add_string(), llmd_finish(), llmd_init(), MD_llvm_linker_options, and MD_llvm_module_flags.
Referenced by ll_create_module().
alloc_flexible_mdnode()
static LL_MDNode * alloc_flexible_mdnode (LLVMModuleRef module, const LL_MDRef * elems, unsigned nelems) static
Definition at line 2093 of file ll_structure.cpp.
References assert, LL_MDNode::elem, ERR_Fatal, LL_MDNode::is_distinct, LL_MDNode::is_flexible, LL_PlainMDNode, malloc(), LL_MDNode::mdclass, MIN_FLEX_SIZE, LL_MDNode::num_elems, and size.
Referenced by ll_create_flexible_md_node(), ll_extend_named_md_node(), and ll_set_named_md_node().
alloc_mdnode()
static LL_MDNode * alloc_mdnode (LLVMModuleRef module, enum LL_MDClass mdclass, const LL_MDRef * elems, unsigned nelems, int is_distinct) static
Definition at line 2071 of file ll_structure.cpp.
References assert, LL_MDNode::elem, ERR_Fatal, LL_MDNode::is_distinct, LL_MDNode::is_flexible, malloc(), LL_MDNode::mdclass, and LL_MDNode::num_elems.
Referenced by ll_create_distinct_md_node(), and ll_get_md_node().
append_global()
static void append_global (LLVMModuleRef module, LL_Object * object) static
Definition at line 2372 of file ll_structure.cpp.
References LL_Module::first_global, LL_Module::last_global, LL_Type_::module, LL_Object::next, and NULL.
Referenced by create_global().
apply_gep_index()
static LL_Type * apply_gep_index (LL_Type * type, unsigned idx) static
Definition at line 1781 of file ll_structure.cpp.
References ERR_Fatal, idx, interr(), LL_ARRAY, LL_PTR, LL_STRUCT, LL_VECTOR, NULL, LL_Type_::sub_elements, and type.
Referenced by ll_get_const_gep().
compute_datalayout()
static void compute_datalayout (LLVMModuleRef module) static
Definition at line 472 of file ll_structure.cpp.
References triple_info::datalayout, LL_Module::datalayout_string, known_triples, triple_info::prefix, strlen(), and LL_Module::target_triple.
Referenced by ll_create_module().
compute_ir_feature_vector()
static void compute_ir_feature_vector (LLVMModuleRef module, enum LL_IRVersion vers) static
Compute the set of IR features in module when generating IR for the specified LLVM version.
Definition at line 388 of file ll_structure.cpp.
References LL_IRFeatures_::debug_info_version, LL_IRFeatures_::dwarf_version, InitializeDIFlags(), LL_Module::ir, LL_IRFeatures_::is_nvvm, LL_IRFeatures_::is_spir, LL_DWARF_Version_2, LL_DWARF_Version_3, LL_DWARF_Version_4, LL_DWARF_Version_5, ll_feature_versioned_dw_tag, LL_Version_3_7, LL_Type_::module, LL_Module::target_triple, LL_IRFeatures_::version, and XBIT.
Referenced by ll_create_module().
constants_equal()
static int constants_equal (hash_key_t key_a, hash_key_t key_b) static
Definition at line 290 of file ll_structure.cpp.
References a, and b.
constants_hash()
static hash_value_t constants_hash (hash_key_t key) static
Definition at line 275 of file ll_structure.cpp.
References HASH_ACCU_ADD, HASH_ACCU_FINISH, HASH_ACCU_INIT, HASH_ACCU_VALUE, p, and t.
create_global()
static LL_Object * create_global (LLVMModuleRef module, enum LL_ObjectKind kind, LL_Type * type, int addrspace, const char * format, va_list args) static
Definition at line 2383 of file ll_structure.cpp.
References LL_Type_::addrspace, append_global(), args, kind, LL_EXTERNAL_LINKAGE, ll_get_addrspace_type(), ll_get_pointer_type(), ll_manage_calloc(), LL_Type_::module, type, unique_name(), and LL_Module::used_global_names.
Referenced by ll_create_global_alias().
dump_proto()
static void dump_proto (int counter, const LL_FnProto * proto) static
Definition at line 2744 of file ll_structure.cpp.
References LL_FnProto_::abi, FILE, LL_FnProto_::fn_name, gbl, LL_FnProto_::has_defined_body, LL_FnProto_::intrinsic_decl_str, and LL_FnProto_::is_weak.
Referenced by ll_proto_dump().
free_iterator()
static void free_iterator (hash_key_t key, void * context) static
Definition at line 98 of file ll_structure.cpp.
References void().
Referenced by ll_destroy_function().
get_llvm_version()
LL_IRVersion get_llvm_version (void)
Get the LLVM version being used The -x 249 flag is set by the -Mllvm= driver option.
...
Definition at line 30 of file ll_structure.cpp.
References flg, LL_Version_3_2, and FLG::x.
Referenced by add_linker_directives(), cg_llvm_init(), schedule(), and write_extern_inits().
get_num_subtypes()
static BIGUINT64 get_num_subtypes (const struct LL_Type_ * type) static
Definition at line 154 of file ll_structure.cpp.
References LL_ARRAY, LL_PTR, LL_VECTOR, and type.
Referenced by types_equal(), and types_hash().
insert_mdnode()
static INLINE unsigned insert_mdnode (LLVMModuleRef module, LL_MDNode * node) static
Insert an allocated mdnode into the module's list.
Returns
the new node number (the position in the list)
The node number is one higher than the index into mdnodes, so node !10 lives in slot 9.
Definition at line 2174 of file ll_structure.cpp.
References ll_reserve_md_node(), LL_Module::mdnodes, and LL_Type_::module.
Referenced by ll_create_distinct_md_node(), ll_create_flexible_md_node(), and ll_get_md_node().
intern_const_int()
static unsigned intern_const_int (LLVMModuleRef module, unsigned bits, long long value) static
Definition at line 1715 of file ll_structure.cpp.
References bits, buf, intern_constant(), ll_create_int_type(), LL_Type_::module, type, and value().
Referenced by ll_get_const_int(), ll_get_md_i32(), and ll_get_md_i64().
intern_constant()
static unsigned intern_constant (LLVMModuleRef module, LL_Type * type, const char * data) static
Definition at line 1683 of file ll_structure.cpp.
References LL_Module::constants, LL_Module::constants_alloc, LL_Module::constants_count, LL_Module::constants_map, LL_Value::data, hashmap_insert(), hashmap_lookup(), HKEY2INT, INT2HKEY, ll_create_value_from_type(), LL_Type_::module, slot, type, and LL_Value::type_struct.
Referenced by intern_const_int(), ll_get_const_addrspacecast(), ll_get_const_bitcast(), ll_get_const_gep(), ll_get_global_pointer(), and ll_get_md_value().
ll_add_global_debug()
void ll_add_global_debug (LLVMModuleRef module, int sptr, LL_MDRef mdnode)
Add sptr → mdnode to global debug map.
...
Parameters
module The module containing the map
sptr The key to be added
mdnode The value to be added
If the key, sptr, is already in the map, the map is unaltered.
Definition at line 2224 of file ll_structure.cpp.
References LL_Module::global_debug_map, hashmap_insert(), hashmap_lookup(), INT2HKEY, LL_Type_::module, sptr, and value().
Referenced by lldbg_create_deferred_len_string_type_mdnode(), and lldbg_emit_global_variable().
ll_add_module_debug()
void ll_add_module_debug (hashmap_t map, const char * module_name, LL_MDRef mdnode)
Add module_name → mdnode to module debug map.
Parameters
module The module containing the map
module_name The key to be added
mdnode The value to be added
If the key, module_name, is already in the map, the map is unaltered.
Definition at line 2779 of file ll_structure.cpp.
References hashmap_insert(), hashmap_lookup(), and INT2HKEY.
Referenced by lldbg_create_module_mdnode(), lldbg_emit_common_block_mdnode(), and lldbg_emit_global_variable().
ll_append_llvm_used()
void ll_append_llvm_used (LLVMModuleRef module, LL_Value * ptr)
Append a pointer to the @llvm.used global.
...
Pointer bitcasts and/or addrspacecasts will be added as needed.
Definition at line 2342 of file ll_structure.cpp.
References LL_Type_::addrspace, ll_create_int_type(), ll_create_sym(), ll_get_const_addrspacecast(), ll_get_const_bitcast(), ll_get_pointer_addrspace(), ll_get_pointer_type(), LL_Module::llvm_used, LL_Type_::module, LL_Module::num_llvm_used, LL_Value::type_struct, and LL_Symbols_::values.
ll_create_anon_struct_type()
LL_Type * ll_create_anon_struct_type (LLVMModuleRef module, LL_Type * elements[], unsigned num_elements, bool is_packed, int addrspace)
Get an anonymous struct type.
...
Anonymous structs are identified by their contents, they don't have a name. This will either return an existing anonymous struct type with the required elements, or create a new type with a copy of the elements array.
A packed struct has alignment 1 and no padding between members.
Definition at line 1519 of file ll_structure.cpp.
References LL_Type_::addrspace, LL_Type_::data_type, LL_Type_::flags, i, len, ll_manage_malloc(), LL_STRUCT, ll_type_bytes(), LL_TYPE_IS_PACKED_STRUCT, LL_Type_::module, NULL, offset, pos, str, LL_Type_::str, strlen(), LL_Type_::sub_elements, LL_Type_::sub_offsets, LL_Type_::sub_padding, LL_Type_::sub_types, and unique_type().
Referenced by amd64_coerce(), gen_llvm_cmpxchg(), gen_vsincos_return_type(), ll_coercion_type(), and ll_convert_basic_dtype_with_addrspace().
ll_create_array_value_from_type()
LL_Value * ll_create_array_value_from_type (LLVMModuleRef module, LL_Type * type, const char * data, int addrspace)
...
Definition at line 1039 of file ll_structure.cpp.
References ll_create_blank_value(), ll_get_array_type(), type, and LL_Value::type_struct.
ll_create_basic_type()
LL_Type * ll_create_basic_type (LLVMModuleRef module, enum LL_BaseDataType type, int addrspace)
...
Definition at line 1100 of file ll_structure.cpp.
References LL_Type_::addrspace, assert, LL_Type_::data_type, ERR_Fatal, LL_Type_::flags, ll_get_str_type_for_basic_type(), LL_X86_MMX, LL_Type_::module, NULL, LL_Type_::str, LL_Type_::sub_elements, LL_Type_::sub_offsets, LL_Type_::sub_padding, LL_Type_::sub_types, type, and unique_type().
Referenced by add_ctor(), add_external_function_declaration(), amd64_coerce(), classify_common(), convert_dtype(), gen_llvm_cmpxchg(), layout_struct_body(), ll_abi_classify_arg_dtype(), ll_abi_classify_return_dtype(), ll_abi_function_type(), ll_abi_return_type(), ll_convert_basic_dtype_with_addrspace(), ll_create_int_type_with_addrspace(), ll_create_pointer_value(), make_lltype_from_sptr(), and make_void_lltype().
ll_create_blank_value()
static LL_Value * ll_create_blank_value (LLVMModuleRef module, const char * data) static
Create a "blank" value.
Definition at line 1001 of file ll_structure.cpp.
References LL_Value::align_bytes, LL_Value::data, LL_Value::dbg_mdnode, LL_Value::dbg_sptr, LL_Value::flags, LL_Value::linkage, LL_DEFAULT, ll_get_md_null, ll_manage_malloc(), ll_manage_strdup(), LL_NO_LINKAGE, LL_Value::mvtype, NULL, LL_Value::storage, and LL_Value::type_struct.
Referenced by ll_create_array_value_from_type(), ll_create_pointer_value(), ll_create_pointer_value_from_type(), and ll_create_value_from_type().
ll_create_device_function_from_type()
LL_Function * ll_create_device_function_from_type (LLVMModuleRef module, LL_Type * func_type, const char * name, int is_kernel, int launch_bounds, const char * calling_convention, enum LL_LinkageType linkage)
Creates NVVM function.
Definition at line 700 of file ll_structure.cpp.
References LL_Function_::calling_convention, CHECK, LL_Type_::data_type, LL_Module::first, is_kernel, LL_Function_::is_kernel, LL_Module::last, LL_Function_::launch_bounds, LL_Function_::linkage, LL_FUNCTION, ll_manage_calloc(), ll_manage_strdup(), ll_set_function_num_arguments(), LL_Function_::local_vars, name, LL_Function_::name, LL_Function_::next, NULL, LL_Symbols_::num_values, LL_Function_::return_type, LL_Type_::sub_elements, LL_Type_::sub_types, and LL_Symbols_::values.
Referenced by schedule().
ll_create_distinct_md_node()
LL_MDRef ll_create_distinct_md_node (LLVMModuleRef module, enum LL_MDClass mdclass, const LL_MDRef * elems, unsigned nelems)
Create a distinct metadata node which will not be uniqued with other identical metadata nodes.
...
Definition at line 2250 of file ll_structure.cpp.
References alloc_mdnode(), insert_mdnode(), LL_MDREF_INITIALIZER, MDRef_Node, and LL_Type_::module.
Referenced by ll_finish_variable(), llmd_finish(), and schedule().
ll_create_flexible_md_node()
LL_MDRef ll_create_flexible_md_node (LLVMModuleRef module)
Create a distinct metadata node that can have elements appended.
...
Definition at line 2262 of file ll_structure.cpp.
References alloc_flexible_mdnode(), insert_mdnode(), LL_MDREF_INITIALIZER, MDRef_Node, LL_Type_::module, and NULL.
Referenced by cons_loop_id_md(), lldbg_create_compile_unit_mdnode(), lldbg_create_outlined_parameters_node(), lldbg_emit_outlined_subprogram(), lldbg_emit_subprogram(), and lldbg_emit_type().
ll_create_function()
struct LL_Function_ * ll_create_function (LLVMModuleRef module, const char * name, LL_Type * return_type, int is_kernel, int launch_bounds, int launch_bounds_minctasm, const char * calling_convention, enum LL_LinkageType linkage)
...
Definition at line 641 of file ll_structure.cpp.
References LL_Function_::arguments, LL_Function_::calling_convention, LL_Function_::first, LL_Module::first, is_kernel, LL_Function_::is_kernel, LL_Function_::last, LL_Module::last, LL_Function_::launch_bounds, LL_Function_::launch_bounds_minctasm, LL_Function_::linkage, ll_manage_calloc(), ll_manage_strdup(), LL_Function_::local_vars, name, LL_Function_::name, LL_Function_::next, NULL, LL_Function_::num_args, LL_Function_::num_locals, LL_Symbols_::num_values, LL_Function_::return_type, and LL_Symbols_::values.
Referenced by add_ctor().
ll_create_function_from_type()
LL_Function * ll_create_function_from_type (LL_Type * func_type, const char * name)
Create an LL_Function.
...
Must be given its name and full LL_FUNCTION type. Note: This does not add the new function to the module's list of functions.
Definition at line 683 of file ll_structure.cpp.
References CHECK, LL_Type_::data_type, LL_FUNCTION, ll_manage_strdup(), ll_set_function_num_arguments(), LL_Type_::module, name, LL_Function_::name, LL_Function_::return_type, LL_Type_::sub_elements, and LL_Type_::sub_types.
Referenced by schedule().
ll_create_function_type()
LL_Type * ll_create_function_type (LLVMModuleRef module, LL_Type * args[], unsigned num_args, int is_varargs)
Get a function type.
...
The return type is passed as args[0], so the args[] array should have a total of num_args+1 elements.
Definition at line 1582 of file ll_structure.cpp.
References LL_Type_::addrspace, args, LL_Type_::data_type, LL_Type_::flags, i, len, LL_FUNCTION, ll_manage_malloc(), LL_TYPE_IS_VARARGS_FUNC, LL_Type_::module, NULL, pos, str, LL_Type_::str, strlen(), LL_Type_::sub_elements, LL_Type_::sub_offsets, LL_Type_::sub_padding, LL_Type_::sub_types, and unique_type().
Referenced by fixup_x86_abi_return(), ll_abi_function_type(), ll_add_func_proto(), ll_convert_iface_sptr(), ll_get_function_pointer(), and make_function_type_from_args().
ll_create_global_alias()
LL_Object * ll_create_global_alias (LL_Value * aliasee_ptr, const char * format, ...)
Create a new global alias.
...
The name of the alias object is produced by the sprintf-link format string and arguments. If the generated name clashes with an existing global object in the module, a unique name will be generated.
The aliasee must be the address of another global object or a constant expression computing an address inside a global object.
Definition at line 2413 of file ll_structure.cpp.
References LL_Type_::addrspace, create_global(), ll_get_pointer_addrspace(), LLInit_ConstExpr, LLObj_Alias, LL_Type_::module, LL_Type_::sub_types, and LL_Value::type_struct.
ll_create_int_type()
LL_Type * ll_create_int_type (LLVMModuleRef module, unsigned bits)
Create an integer type with bits bits.
...
Parameters
module The LLVM module
bits The number of bits used in the representation
Returns
A uniqued integral LL_Type
See LL_BaseDataType for all the integer bitwidths supported.
Definition at line 1192 of file ll_structure.cpp.
References bits, LL_AddrSp_Default, ll_create_int_type_with_addrspace(), and LL_Type_::module.
Referenced by amd64_coerce(), gen_llvm_expr(), gen_ptr_offset_val(), insert_llvm_dbg_value(), intern_const_int(), ll_append_llvm_used(), ll_coercion_type(), make_int_lltype(), make_lltype_from_sptr(), and process_symlinked_sptr().
ll_create_int_type_with_addrspace()
LL_Type * ll_create_int_type_with_addrspace (LLVMModuleRef module, unsigned bits, int addrspace)
Create an integer type with bits bits.
...
Parameters
module The LLVM module
bits The number of bits used in the representation
addrspace The address space where type will be in
Returns
A uniqued integral LL_Type
See LL_BaseDataType for all the integer bitwidths supported.
Definition at line 1139 of file ll_structure.cpp.
References LL_Type_::addrspace, bits, ERR_Fatal, interr(), ll_create_basic_type(), LL_I1, LL_I128, LL_I16, LL_I24, LL_I256, LL_I32, LL_I40, LL_I48, LL_I56, LL_I64, LL_I8, LL_NOTYPE, and LL_Type_::module.
Referenced by convert_dtype(), and ll_create_int_type().
ll_create_local_name()
const char * ll_create_local_name (LL_Function * function, const char * format, ...)
Create a new unique name for a local value in function.
...
The name is based on the provided printf-style format string and arguments. The leading % character should not be part for the format string.
Returns a pointer to a unique local name in function, including the leading %. The memory for the returned name is managed by the function.
Definition at line 2442 of file ll_structure.cpp.
References hash_functions_strings, hashset_alloc(), name, unique_name(), and LL_Function_::used_local_names.
Referenced by process_auto_sptr(), and process_formal_arguments().
ll_create_local_object()
LL_Object * ll_create_local_object (LL_Function * function, LL_Type * type, unsigned align_bytes, const char * format, ...)
Create a new local object in function.
...
The object will be allocated by an LLVM alloca instruction in the entry block. It will not be initialized.
The name of the local object is produced by the sprintf-link format string and arguments. If the generated name clashes with an existing local value in the function, a unique name will be generated.
Definition at line 2468 of file ll_structure.cpp.
References LL_Function_::first_local, hash_functions_strings, hashset_alloc(), LL_Function_::last_local, ll_get_pointer_type(), LL_INTERNAL_LINKAGE, ll_manage_calloc(), LLObj_Local, LL_Object::next, type, unique_name(), and LL_Function_::used_local_names.
Referenced by gen_name_private_sptr(), process_auto_sptr(), process_formal_arguments(), and process_local_sptr().
ll_create_module()
LLVMModuleRef ll_create_module (const char * module_name, const char * target_triple, enum LL_IRVersion llvm_ir_version)
...
Definition at line 539 of file ll_structure.cpp.
References add_linker_directives(), LL_Module::anon_types, LL_Module::common_debug_map, compute_datalayout(), compute_ir_feature_vector(), LL_Module::constants, LL_Module::constants_alloc, constants_hash_functions, LL_Module::constants_map, LL_Module::extern_func_refs, LL_Module::first, LL_Module::first_malloc, flg, LL_Module::global_debug_map, hash_functions_direct, hash_functions_strings, hashmap_alloc(), hashset_alloc(), LL_Module::last, FLG::linker_directives, ll_manage_strdup(), mdnode_hash_functions, LL_Module::mdnodes, LL_Module::mdnodes_alloc, LL_Module::mdnodes_fwdvars, LL_Module::mdnodes_map, LL_Module::mdstrings, LL_Module::mdstrings_alloc, LL_Module::mdstrings_map, LL_Module::module_debug_map, LL_Module::module_name, LL_Module::module_vars, LL_Module::modvar_debug_map, NULL, LL_Module::num_module_vars, LL_Module::num_refs, LL_Module::num_user_structs, LL_Symbols_::num_values, LL_Module::target_triple, types_hash_functions, LL_Module::used_global_names, LL_Module::used_type_names, LL_Module::user_structs, LL_Module::user_structs_byid, LL_Symbols_::values, and LL_Module::written_user_structs.
Referenced by cg_llvm_init().
ll_create_named_struct_type()
LL_Type * ll_create_named_struct_type (LLVMModuleRef module, int id, bool unique, const char * format, ...)
Create a new named struct type in the module.
...
Type can be uniquely named if parameter unique is set to true
If id is positive, the new struct type is associated with the id so it can be retrieved with ll_get_struct_type(). Usually, the TY_STRUCT dtype is used as an id.
It is an error to create multiple types with the same positive id, unless ll_reset_module_types() is called in between.
A zero or negative id is ignored.
The name of the new struct type will be based on the printf-style format and additional arguments. A '' character will be prepended, don't include one in the format string.
The new struct name may not be exactly as requested, so don't depend on it. The type name may be modified to ensure its uniqueness.
Definition at line 1430 of file ll_structure.cpp.
References assert, LL_Type_::data_type, ERR_Fatal, LL_Type_::flags, hashmap_replace(), INT2HKEY, ll_create_sym(), ll_create_value_from_type(), ll_named_struct_type_exists(), ll_remove_struct_type(), LL_STRUCT, LL_TYPE_IS_NAMED_STRUCT, LL_Type_::module, LL_Module::num_user_structs, LL_Type_::str, LL_Value::type_struct, unique_name(), LL_Module::used_type_names, LL_Module::user_structs, and LL_Module::user_structs_byid.
Referenced by ll_convert_struct_dtype().
ll_create_pointer_value()
LL_Value * ll_create_pointer_value (LLVMModuleRef module, enum LL_BaseDataType type, const char * data, int addrspace)
...
Definition at line 1017 of file ll_structure.cpp.
References ll_create_basic_type(), ll_create_blank_value(), ll_get_pointer_type(), type, and LL_Value::type_struct.
ll_create_pointer_value_from_type()
LL_Value * ll_create_pointer_value_from_type (LLVMModuleRef module, LL_Type * type, const char * data, int addrspace)
...
Definition at line 1048 of file ll_structure.cpp.
References ll_create_blank_value(), ll_get_addrspace_type(), ll_get_pointer_type(), type, and LL_Value::type_struct.
Referenced by schedule().
ll_create_sym()
void ll_create_sym (struct LL_Symbols_ * symbol_table, unsigned index, LL_Value * new_value)
...
Definition at line 737 of file ll_structure.cpp.
References index, LL_Symbols_::num_values, and LL_Symbols_::values.
Referenced by ll_append_llvm_used(), and ll_create_named_struct_type().
ll_create_value_from_type()
LL_Value * ll_create_value_from_type (LLVMModuleRef module, LL_Type * type, const char * data)
...
Definition at line 1031 of file ll_structure.cpp.
References ll_create_blank_value(), type, and LL_Value::type_struct.
Referenced by add_global_define(), addDebugForGlobalVar(), gen_ptr_offset_val(), intern_constant(), ll_create_named_struct_type(), and lldbg_function_end().
ll_destroy_basic_block()
static void ll_destroy_basic_block (struct LL_BasicBlock_ * basic_block) static
Definition at line 81 of file ll_structure.cpp.
References current, LL_BasicBlock_::first, ll_destroy_instruction(), LL_BasicBlock_::name, next, and NULL.
Referenced by ll_destroy_function().
ll_destroy_function()
void ll_destroy_function (LL_Function * function)
Deallocate all memory used by function.
Note that this function is called automatically by ll_destroy_module(), so it should only be called explicitly for functions that are not in the module's linked list.
Definition at line 108 of file ll_structure.cpp.
References LL_Function_::arguments, current, LL_Function_::first, free_iterator(), hashset_free(), hashset_iterate(), ll_destroy_basic_block(), next, NULL, and LL_Function_::used_local_names.
Referenced by ll_destroy_module(), and schedule().
ll_destroy_instruction()
static void ll_destroy_instruction (struct LL_Instruction_ * instruction) static
Definition at line 67 of file ll_structure.cpp.
References LL_Instruction_::comment, and LL_Instruction_::operands.
Referenced by ll_destroy_basic_block().
ll_destroy_mem()
void ll_destroy_mem (struct LL_ManagedMallocs_ * current)
...
Definition at line 134 of file ll_structure.cpp.
References current.
Referenced by ll_destroy_module().
ll_destroy_module()
void ll_destroy_module (LLVMModuleRef module)
...
Definition at line 482 of file ll_structure.cpp.
References LL_Module::anon_types, LL_Module::common_debug_map, LL_Module::constants, LL_Module::constants_map, current, LL_Module::debug_info, LL_Module::first, LL_Module::first_malloc, LL_Module::global_debug_map, hashmap_free(), hashset_free(), i, ll_destroy_function(), ll_destroy_mem(), lldbg_free(), MD_NUM_NAMES, LL_Module::mdnodes, LL_Module::mdnodes_count, LL_Module::mdnodes_map, LL_Module::mdstrings, LL_Module::mdstrings_count, LL_Module::mdstrings_map, LL_Module::module_debug_map, LL_Module::module_vars, LL_Module::modvar_debug_map, LL_Module::named_mdnodes, next, LL_ManagedMallocs_::next, NULL, LL_Module::used_global_names, LL_Module::used_type_names, LL_Module::user_structs, LL_Module::user_structs_byid, and LL_Symbols_::values.
ll_extend_md_node()
void ll_extend_md_node (LLVMModuleRef module, LL_MDRef flexnode, LL_MDRef elem)
Append an element to end of a flexible metadata node.
...
The node must have been created by ll_create_flexible_md_node()
Definition at line 2275 of file ll_structure.cpp.
References assert, ERR_Fatal, LL_MDREF_kind, LL_MDREF_value, mdnode_append(), LL_Module::mdnodes, MDRef_Node, LL_Type_::module, and slot.
Referenced by cons_loop_id_md(), cons_vec_always_metadata(), construct_vectorlength_metadata(), lldbg_create_aggregate_members_type(), lldbg_create_global_variable_mdnode(), lldbg_create_imported_entity(), lldbg_create_subprogram_mdnode(), lldbg_emit_lv_list(), lldbg_emit_outlined_parameter_list(), lldbg_emit_subprogram(), and schedule().
ll_extend_named_md_node()
void ll_extend_named_md_node (LLVMModuleRef module, enum LL_MDName name, LL_MDRef elem)
Append an element to a named metadata node.
...
Creates the named metadata node if needed.
Definition at line 2326 of file ll_structure.cpp.
References alloc_flexible_mdnode(), assert, ERR_Fatal, MD_NUM_NAMES, mdnode_append(), LL_Type_::module, name, and LL_Module::named_mdnodes.
Referenced by add_linker_directives(), lldbg_create_compile_unit_mdnode(), and lldbg_init().
ll_feature_dwarf_version()
unsigned ll_feature_dwarf_version (const LL_IRFeatures * feature)
Convert the cached DWARF version to an unsigned.
...
The DWARF version is either the default or specified from the command-line.
Definition at line 434 of file ll_structure.cpp.
References feature, LL_DWARF_Version_2, LL_DWARF_Version_3, LL_DWARF_Version_4, and LL_DWARF_Version_5.
Referenced by lldbg_init().
ll_get_addrspace_type()
LL_Type * ll_get_addrspace_type (LL_Type * type, int addrspace)
Get a version of type in different address space.
...
Note: In LLVM IR only pointer types have an address space.
Definition at line 1203 of file ll_structure.cpp.
References LL_Type_::addrspace, type, and unique_type().
Referenced by create_global(), ll_create_pointer_value_from_type(), and ll_get_const_gep().
ll_get_array_type()
LL_Type * ll_get_array_type (LL_Type * type, BIGUINT64 num_elements, int addrspace)
...
Definition at line 1261 of file ll_structure.cpp.
References LL_Type_::addrspace, BIGIPFSZ, LL_Type_::data_type, LL_Type_::flags, LL_ARRAY, ll_manage_malloc(), LL_Type_::module, NULL, prefix, LL_Type_::str, strlen(), LL_Type_::sub_elements, LL_Type_::sub_offsets, LL_Type_::sub_padding, LL_Type_::sub_types, suffix, type, and unique_type().
Referenced by check_vector_registers(), check_vfp(), classify_common(), layout_struct_body(), ll_abi_classify_arg_dtype(), ll_coercion_type(), ll_convert_array_dtype(), ll_create_array_value_from_type(), make_array_lltype(), make_lltype_from_sptr(), process_symlinked_sptr(), and set_vect3_to_size4().
ll_get_calling_conv_str()
const char * ll_get_calling_conv_str (enum LL_CallConv cc)
Get the textual representation of a calling convention.
...
Definition at line 1636 of file ll_structure.cpp.
References ERR_Fatal, interr(), LL_CallConv_AAPCS, LL_CallConv_AAPCS_VFP, LL_CallConv_APCS, LL_CallConv_C, LL_CallConv_Cold, LL_CallConv_Fast, LL_CallConv_PTX_Device, LL_CallConv_PTX_Kernel, LL_CallConv_SPIR_FUNC, LL_CallConv_SPIR_KERNEL, LL_CallConv_X86_FastCall, LL_CallConv_X86_StdCall, LL_CallConv_X86_ThisCall, and LL_CallConv_X86_VectorCall.
Referenced by print_function_signature(), and write_I_CALL().
ll_get_const_addrspacecast()
LL_Value * ll_get_const_addrspacecast (LLVMModuleRef module, LL_Value * value, LL_Type * type)
Get a shared LL_Value representing an addrspacecast of the pointer value to type.
...
When targeting LLVM version that don't have the addrspacecast instruction, this will use ptrtoint/inttoptr instead.
Definition at line 1911 of file ll_structure.cpp.
References assert, LL_Module::constants, ERR_Fatal, intern_constant(), LL_Module::ir, ll_feature_use_addrspacecast, ll_get_pointer_addrspace(), ll_type_bytes(), malloc(), LL_Type_::module, name, slot, strlen(), type, and value().
Referenced by ll_append_llvm_used().
ll_get_const_bitcast()
LL_Value * ll_get_const_bitcast (LLVMModuleRef module, LL_Value * value, LL_Type * type)
Get a shared LL_Value representing a constant bitcast of value to type.
...
This creates a bitcast expression that may be used to initialize globals and metadata. It does not create an LL_BITCAST instruction.
Definition at line 1883 of file ll_structure.cpp.
References LL_Module::constants, intern_constant(), malloc(), LL_Type_::module, name, slot, strlen(), type, and value().
Referenced by gen_ptr_offset_val(), and ll_append_llvm_used().
ll_get_const_gep()
LL_Value * ll_get_const_gep (LLVMModuleRef module, LL_Value * ptr, unsigned num_idx, ...)
Get a shared LL_Value representing a constant getelementptr of the provided pointer value.
...
This creates a gep-expression that may be used to initialize globals and metadata. It does not create an LL_GEP instruction.
The num_idx argument is the number of index operands on the gep expression. It should be at least 1.
The gep indices following num_idx should be ints.
Note: element type is the exected element type, this does not get elements of any different type.
Definition at line 1820 of file ll_structure.cpp.
References apply_gep_index(), assert, LL_Module::constants, LL_Value::data, ERR_Fatal, idx, intern_constant(), LL_Module::ir, ll_feature_explicit_gep_load_type, ll_get_addrspace_type(), ll_get_pointer_addrspace(), ll_get_pointer_type(), LL_PTR, malloc(), LL_Type_::module, name, p, slot, LL_Type_::str, strlen(), LL_Type_::sub_types, type, and LL_Value::type_struct.
Referenced by gen_ptr_offset_val().
ll_get_const_int()
LL_Value * ll_get_const_int (LLVMModuleRef module, unsigned bits, long long value)
Get a shared LL_Value representing a constant integer of up to 64 bits.
...
Definition at line 1729 of file ll_structure.cpp.
References bits, LL_Module::constants, intern_const_int(), LL_Type_::module, slot, and value().
ll_get_function_pointer()
LL_Value * ll_get_function_pointer (LLVMModuleRef module, LL_Function * function)
Get the constant function pointer value representing a function.
...
Note that the type of this function pointer depends on the added function arguments.
Definition at line 1762 of file ll_structure.cpp.
References args, LL_Function_::arguments, i, ll_create_function_type(), ll_get_global_pointer(), malloc(), LL_Type_::module, LL_Function_::name, LL_Function_::num_args, LL_Function_::return_type, and LL_Value::type_struct.
ll_get_global_debug()
LL_MDRef ll_get_global_debug (LLVMModuleRef module, int sptr)
...
Definition at line 2235 of file ll_structure.cpp.
References LL_Module::global_debug_map, hashmap_lookup(), HKEY2INT, INT2HKEY, LL_MDREF_ctor, LL_Type_::module, and sptr.
Referenced by lldbg_create_cmblk_mem_mdnode_list(), lldbg_create_ftn_subrange_via_sdsc(), and lldbg_emit_global_variable().
ll_get_global_pointer()
LL_Value * ll_get_global_pointer (const char * name, LL_Type * type)
Get a pointer to an LLVM global given its name and type.
...
This will prepend @ to the name and add one level of indirection to the type.
Definition at line 1742 of file ll_structure.cpp.
References intern_constant(), ll_get_pointer_type(), malloc(), name, slot, strlen(), and type.
Referenced by ll_get_function_pointer().
ll_get_md_i1()
LL_MDRef ll_get_md_i1 (int value)
Get an LL_MDRef representing an i1 boolean value.
...
Definition at line 1951 of file ll_structure.cpp.
References assert, ERR_Fatal, LL_MDREF_INITIALIZER, MDRef_SmallInt1, and value().
Referenced by cons_novectorize_metadata(), cons_vectorize_metadata(), cons_vectorlength_scalable_metadata(), and llmd_add_i1().
ll_get_md_i32()
LL_MDRef ll_get_md_i32 (LLVMModuleRef module, int value)
Get an LL_MDRef representing an i32 integer value.
...
Definition at line 1961 of file ll_structure.cpp.
References intern_const_int(), LL_MDREF_ctor, MDRef_Constant, MDRef_SmallInt32, LL_Type_::module, and value().
Referenced by cons_unroll_count_metadata(), construct_vectorlength_metadata(), and llmd_add_i32().
ll_get_md_i64()
LL_MDRef ll_get_md_i64 (LLVMModuleRef module, long long value)
Get an LL_MDRef representing an i64 integer value.
...
Definition at line 1973 of file ll_structure.cpp.
References intern_const_int(), LL_MDREF_ctor, LL_MDREF_INITIALIZER, MDRef_Constant, MDRef_SmallInt64, LL_Type_::module, and value().
Referenced by get_omnipotent_pointer(), get_tbaa_metadata(), init_subrange_bound(), lldbg_emit_type(), llmd_add_i64(), and locset_to_tbaa_info().
ll_get_md_node()
LL_MDRef ll_get_md_node (LLVMModuleRef module, enum LL_MDClass mdclass, const LL_MDRef * elems, unsigned nelems)
Get an LL_MDRef representing a numbered metadata node.
...
Definition at line 2194 of file ll_structure.cpp.
References alloc_mdnode(), hashmap_insert(), hashmap_lookup(), HKEY2INT, insert_mdnode(), INT2HKEY, LL_MDREF_ctor, LL_MDREF_INITIALIZER, LL_Module::mdnodes_map, MDRef_Node, and LL_Type_::module.
Referenced by cons_loop_parallel_accesses_metadata(), cons_nounroll_metadata(), cons_novectorize_metadata(), cons_unroll_count_metadata(), cons_unroll_metadata(), cons_vectorize_metadata(), cons_vectorlength_scalable_metadata(), construct_vectorlength_metadata(), get_omnipotent_pointer(), get_tbaa_metadata(), ll_finish_variable(), lldbg_create_compile_unit_mdnode(), lldbg_create_subprogram_mdnode(), llmd_finish(), and locset_to_tbaa_info().
ll_get_md_rawstring()
LL_MDRef ll_get_md_rawstring (LLVMModuleRef module, const void * rawstr, size_t length)
Get an LL_MDRef representing a raw binary string.
...
The string can contain arbitrary bytes, including nuls; appropriate escaping will be added.
Definition at line 1993 of file ll_structure.cpp.
References i, NEEDS_ESC, and p.
Referenced by ll_get_md_string().
ll_get_md_string()
LL_MDRef ll_get_md_string (LLVMModuleRef module, const char * str)
Get an LL_MDRef representing a string.
...
The string can contain arbitrary bytes, except for nul; appropriate escaping will be added.
Definition at line 2054 of file ll_structure.cpp.
References ll_get_md_rawstring(), LL_Type_::module, str, and strlen().
Referenced by cons_loop_parallel_accesses_metadata(), cons_nounroll_metadata(), cons_novectorize_metadata(), cons_unroll_count_metadata(), cons_unroll_metadata(), cons_vectorize_metadata(), cons_vectorlength_scalable_metadata(), construct_vectorlength_metadata(), get_omnipotent_pointer(), llmd_add_string(), and locset_to_tbaa_info().
ll_get_md_value()
LL_MDRef ll_get_md_value (LLVMModuleRef module, LL_Value * value)
Get an LL_MDRef representing an arbitrary LLVM constant value.
...
Definition at line 2063 of file ll_structure.cpp.
References intern_constant(), LL_MDREF_ctor, MDRef_Constant, LL_Type_::module, and value().
Referenced by lldbg_create_global_variable_mdnode(), lldbg_set_func_ptr(), and llmd_add_value().
ll_get_module_debug()
LL_MDRef ll_get_module_debug (hashmap_t map, const char * module_name)
Definition at line 2787 of file ll_structure.cpp.
References hashmap_lookup(), HKEY2INT, and LL_MDREF_ctor.
Referenced by lldbg_create_imported_entity(), lldbg_emit_common_block_mdnode(), lldbg_emit_module_mdnode(), and process_cmnblk_data().
ll_get_pointer_addrspace()
int ll_get_pointer_addrspace (LL_Type * ptr)
get pointer's address space
...
Parameters
ptr A pointer type
Given a pointer type, return the address space that is being pointed into.
Definition at line 1064 of file ll_structure.cpp.
References LL_Type_::addrspace, assert, LL_Type_::data_type, ERR_Fatal, LL_PTR, and LL_Type_::sub_types.
Referenced by ll_append_llvm_used(), ll_create_global_alias(), ll_get_const_addrspacecast(), ll_get_const_gep(), and ll_write_global_objects().
ll_get_pointer_type()
LL_Type * ll_get_pointer_type (LL_Type * type)
Create a pointer type pointing to the given pointee type.
...
Definition at line 1220 of file ll_structure.cpp.
References LL_Type_::addrspace, LL_Type_::data_type, LL_Type_::flags, ll_manage_malloc(), LL_PTR, LL_Type_::module, NULL, size, LL_Type_::str, strlen(), LL_Type_::sub_elements, LL_Type_::sub_offsets, LL_Type_::sub_padding, LL_Type_::sub_types, type, and unique_type().
Referenced by add_external_function_declaration(), addDebugForGlobalVar(), convert_dtype(), create_global(), gen_ptr_offset_val(), layout_struct_body(), ll_abi_classify_arg_dtype(), ll_abi_complete_arg_info(), ll_append_llvm_used(), ll_create_local_object(), ll_create_pointer_value(), ll_create_pointer_value_from_type(), ll_get_const_gep(), ll_get_global_pointer(), lldbg_function_end(), make_lltype_from_sptr(), make_ptr_lltype(), maybe_do_gep_folding(), maybe_fixup_x86_abi_return(), process_formal_arguments(), put_addr(), set_vect3_to_size4(), and write_operand().
ll_get_str_type_for_basic_type()
const char * ll_get_str_type_for_basic_type (enum LL_BaseDataType type)
...
Definition at line 767 of file ll_structure.cpp.
References LL_DOUBLE, LL_FLOAT, LL_FP128, LL_HALF, LL_I1, LL_I128, LL_I16, LL_I24, LL_I256, LL_I32, LL_I40, LL_I48, LL_I56, LL_I64, LL_I8, LL_LABEL, LL_METADATA, LL_NOTYPE, LL_PPC_FP128, LL_VOID, LL_X86_FP80, LL_X86_MMX, and type.
Referenced by ll_create_basic_type().
ll_get_struct_type()
LL_Type * ll_get_struct_type (LLVMModuleRef module, int struct_id, int required)
Get an existing named struct type by id.
...
The id must be positive.
If no named struct type has been created with that id, NULL is returned. If required is true, an internal compiler error is signaled instead of returning NULL.
Definition at line 1494 of file ll_structure.cpp.
References assert, ERR_Fatal, hashmap_lookup(), INT2HKEY, LL_Type_::module, NULL, LL_Value::type_struct, and LL_Module::user_structs_byid.
Referenced by ll_abi_classify_arg_dtype(), and ll_convert_struct_dtype().
ll_get_vector_type()
LL_Type * ll_get_vector_type (LL_Type * type, unsigned num_elements)
Get a vector type <num x elem>
...
Definition at line 1301 of file ll_structure.cpp.
References LL_Type_::addrspace, LL_Type_::data_type, LL_Type_::flags, ll_manage_malloc(), LL_VECTOR, LL_Type_::module, NULL, prefix, LL_Type_::str, strlen(), LL_Type_::sub_elements, LL_Type_::sub_offsets, LL_Type_::sub_padding, LL_Type_::sub_types, type, and unique_type().
Referenced by amd64_coerce(), convert_dtype(), gen_binary_expr(), gen_llvm_expr(), gen_resized_vect(), gen_vect_compare_operand(), make_vector_lltype(), maybe_generate_fma(), and set_vect3_to_size4().
ll_manage_calloc()
static void * ll_manage_calloc (LLVMModuleRef module, size_t members, size_t member_size) static
Definition at line 53 of file ll_structure.cpp.
References ll_manage_mem().
Referenced by create_global(), ll_create_device_function_from_type(), ll_create_function(), and ll_create_local_object().
ll_manage_malloc()
static void * ll_manage_malloc (LLVMModuleRef module, size_t malloc_size) static
Definition at line 60 of file ll_structure.cpp.
References ll_manage_mem(), and malloc().
Referenced by ll_create_anon_struct_type(), ll_create_blank_value(), ll_create_function_type(), ll_get_array_type(), ll_get_pointer_type(), ll_get_vector_type(), and unique_type().
ll_manage_mem()
static void * ll_manage_mem (LLVMModuleRef module, void * space) static
Definition at line 36 of file ll_structure.cpp.
References LL_Module::first_malloc, malloc(), and mem().
Referenced by ll_manage_calloc(), ll_manage_malloc(), and ll_manage_strdup().
ll_manage_strdup()
static char * ll_manage_strdup (LLVMModuleRef module, const char * str) static
Definition at line 47 of file ll_structure.cpp.
References ll_manage_mem(), and str.
Referenced by ll_create_blank_value(), ll_create_device_function_from_type(), ll_create_function(), ll_create_function_from_type(), and ll_create_module().
ll_named_struct_type_exists()
LL_Value * ll_named_struct_type_exists (LLVMModuleRef module, int id, const char * format, ...)
...
Definition at line 1383 of file ll_structure.cpp.
References hashmap_lookup(), hashset_lookup(), INT2HKEY, LL_Type_::module, NULL, LL_Module::used_type_names, and LL_Module::user_structs_byid.
Referenced by ll_create_named_struct_type().
ll_proto_add()
LL_FnProto * ll_proto_add (const char * fnname, struct LL_ABI_Info_ * abi)
Uniquely instantiate a new proto to the global map.
...
Definition at line 2570 of file ll_structure.cpp.
References _ll_proto_head, _ll_proto_map, LL_FnProto_::abi, ERR_Fatal, LL_FnProto_::fn_name, hashmap_insert(), hashmap_lookup(), interr(), and LL_FnProto_::next.
Referenced by add_ctor(), add_external_function_declaration(), ll_add_func_proto(), and ll_proto_add_sptr().
ll_proto_add_sptr()
LL_FnProto * ll_proto_add_sptr (SPTR func_sptr, struct LL_ABI_Info_ * abi)
Convienience routine to ll_proto_add.
...
Also sets the proper name to use when defining/declaring the function.
Definition at line 2611 of file ll_structure.cpp.
References get_llvm_name(), ll_proto_add(), ll_proto_key(), and ll_proto_update_name().
Referenced by add_external_function_declaration(), ll_process_routine_parameters(), print_entry_subroutine(), and schedule().
ll_proto_dump()
void ll_proto_dump (void)
Debugging: Dump the contents of the map.
...
Definition at line 2758 of file ll_structure.cpp.
References _ll_proto_head, dump_proto(), FILE, gbl, and LL_FnProto_::next.
ll_proto_get_abi()
struct LL_ABI_Info_ * ll_proto_get_abi (const char * fnname)
...
Definition at line 2632 of file ll_structure.cpp.
References _ll_proto_map, LL_FnProto_::abi, hashmap_lookup(), and NULL.
Referenced by ll_make_kmpc_proto(), ll_process_routine_parameters(), process_ll_abi_func_ftn_mod(), write_final_table(), and write_vft().
ll_proto_has_defined_body()
bool ll_proto_has_defined_body (const char * fnname)
...
Definition at line 2665 of file ll_structure.cpp.
References _ll_proto_map, ERR_Fatal, LL_FnProto_::has_defined_body, hashmap_lookup(), interr(), and NULL.
ll_proto_init()
void ll_proto_init (void)
Initialization.
...
Should only ever be called once for the entire compilation
Definition at line 2549 of file ll_structure.cpp.
References _ll_proto_map, ERR_Fatal, hash_functions_strings, hashmap_alloc(), and interr().
Referenced by cg_llvm_init(), and ll_add_func_proto().
ll_proto_is_weak()
bool ll_proto_is_weak (const char * fnname)
...
Definition at line 2701 of file ll_structure.cpp.
References _ll_proto_map, ERR_Fatal, hashmap_lookup(), interr(), LL_FnProto_::is_weak, and NULL.
ll_proto_iterate()
void ll_proto_iterate (LL_FnProto_Handler callback)
...
Definition at line 2736 of file ll_structure.cpp.
References _ll_proto_head, and LL_FnProto_::next.
Referenced by write_external_function_declarations().
ll_proto_key()
const char * ll_proto_key (SPTR func_sptr)
Find the function (interface) name to be used as a key.
...
Parameters
func_sptr An sptr to a function symbol
Given a function sptr return the function name (or interface name) to be used as a key for the rest of the fnname arguments for the ll_proto_* API.
Definition at line 2519 of file ll_structure.cpp.
References assert, find_ag(), get_llvm_ifacenm(), get_llvm_name(), and NULL.
Referenced by add_external_function_declaration(), build_routine_and_parameter_entries(), ll_process_routine_parameters(), ll_proto_add_sptr(), print_entry_subroutine(), process_ll_abi_func_ftn_mod(), write_final_table(), and write_vft().
ll_proto_set_abi()
void ll_proto_set_abi (const char * fnname, struct LL_ABI_Info_ * abi)
...
Definition at line 2619 of file ll_structure.cpp.
References _ll_proto_map, LL_FnProto_::abi, hashmap_lookup(), and NULL.
Referenced by process_ll_abi_func_ftn_mod().
ll_proto_set_defined_body()
void ll_proto_set_defined_body (const char * fnname, bool has_defined)
Set the flag "function has body".
...
Parameters
fnname a key (function name)
has_defined true iff fnname is a definition
Sets the bit representing the information that the body of the function represented by fnname is defined.
Definition at line 2651 of file ll_structure.cpp.
References _ll_proto_map, ERR_Fatal, LL_FnProto_::has_defined_body, hashmap_lookup(), interr(), and NULL.
Referenced by build_routine_and_parameter_entries(), print_entry_subroutine(), and write_module_as_subroutine().
ll_proto_set_intrinsic()
void ll_proto_set_intrinsic (const char * fnname, const char * intrinsic_decl_str)
Set compiler generated intrinsic string.
...
Parameters
fnname The key to lookup the prototype
intrinsic_decl_str The LLVM declare statement text
The prototype of fnname must already have been added to the map.
Definition at line 2722 of file ll_structure.cpp.
References _ll_proto_map, ERR_Fatal, hashmap_lookup(), interr(), LL_FnProto_::intrinsic_decl_str, and NULL.
Referenced by add_ctor(), and add_external_function_declaration().
ll_proto_set_weak()
void ll_proto_set_weak (const char * fnname, bool is_weak)
Set the flag "function is weak".
...
Parameters
fnname a key (function name)
is_weak true iff fnname is weak
Sets the bit representing the information that the function represented by fnname is weak.
Definition at line 2687 of file ll_structure.cpp.
References _ll_proto_map, ERR_Fatal, hashmap_lookup(), interr(), LL_FnProto_::is_weak, and NULL.
Referenced by add_external_function_declaration(), and build_routine_and_parameter_entries().
ll_proto_update_name()
static void ll_proto_update_name (LL_FnProto * proto, const char * fnname) static
Definition at line 2560 of file ll_structure.cpp.
References LL_FnProto_::fn_name.
Referenced by ll_proto_add_sptr().
ll_remove_struct_type()
void ll_remove_struct_type (LLVMModuleRef module, int struct_id)
Remove struct type from hashmap.
...
This is required whenever a struct has a same dtype but in different modules defined in same file
Definition at line 1479 of file ll_structure.cpp.
References hashmap_erase(), INT2HKEY, LL_Type_::module, NULL, and LL_Module::user_structs_byid.
Referenced by ll_create_named_struct_type().
ll_reserve_md_node()
unsigned ll_reserve_md_node (LLVMModuleRef module)
Reserve a slot for an LL_MDNode.
...
Parameters
module the LL_Module
Returns
the reserved slot plus 1
Definition at line 2153 of file ll_structure.cpp.
References LL_Module::mdnodes, LL_Module::mdnodes_alloc, LL_Module::mdnodes_count, LL_Type_::module, NULL, and slot.
Referenced by insert_mdnode(), and lldbg_fwd_local_variable().
ll_reset_module_types()
void ll_reset_module_types (LLVMModuleRef module)
Reset the id map for named struct types.
...
This means that ll_get_struct_type() will not return any of the struct types created so far, and previously used type ids can be reused.
Reset the id -> type mapping, but deliberately keep the used_type_names set. We still want to guarantee globally unique type names in the module.
Definition at line 378 of file ll_structure.cpp.
References hashmap_clear(), LL_Type_::module, and LL_Module::user_structs_byid.
Referenced by cg_llvm_fnend().
ll_set_function_argument()
void ll_set_function_argument (struct LL_Function_ * function, int index, LL_Value * argument)
...
Definition at line 760 of file ll_structure.cpp.
References LL_Function_::arguments, and index.
ll_set_function_num_arguments()
void ll_set_function_num_arguments (struct LL_Function_ * function, int num_args)
...
Definition at line 753 of file ll_structure.cpp.
References LL_Function_::arguments, and LL_Function_::num_args.
Referenced by add_prototype(), ll_create_device_function_from_type(), and ll_create_function_from_type().
ll_set_md_node()
void ll_set_md_node (LLVMModuleRef module, unsigned mdNum, LL_MDNode * node)
...
Definition at line 2182 of file ll_structure.cpp.
References assert, ERR_Fatal, LL_Module::mdnodes, and LL_Type_::module.
Referenced by ll_finish_variable().
ll_set_named_md_node()
void ll_set_named_md_node (LLVMModuleRef module, enum LL_MDName name, const LL_MDRef * elems, unsigned nelems)
Add a named metadata node to the module.
...
Definition at line 2312 of file ll_structure.cpp.
References alloc_flexible_mdnode(), assert, ERR_Fatal, MD_NUM_NAMES, LL_Type_::module, name, and LL_Module::named_mdnodes.
ll_set_struct_body()
void ll_set_struct_body (LL_Type * ctype, LL_Type *const * elements, unsigned *const offsets, char *const pads, unsigned num_elements, int is_packed)
Replace the entire body of a named struct type. This may be used to change the number of elements in an existing named struct.
...
It is not possible to change the body of an anonymous struct type.
The struct type is identified by the LL_Value returned from ll_create_named_struct_type().
Definition at line 1347 of file ll_structure.cpp.
References assert, ERR_Fatal, LL_STRUCT, LL_TYPE_IS_NAMED_STRUCT, LL_TYPE_IS_PACKED_STRUCT, NULL, and type.
Referenced by layout_struct_body().
ll_type_array_elety()
LL_Type * ll_type_array_elety (LL_Type * ty)
...
Definition at line 962 of file ll_structure.cpp.
References LL_Type_::data_type, LL_ARRAY, and LL_Type_::sub_types.
Referenced by match_types().
ll_type_bytes()
ISZ_T ll_type_bytes (LL_Type * type)
Get the size of a type in bytes.
...
Parameters
type The type to be examined
Returns
size of an object of type type or 0
Definition at line 896 of file ll_structure.cpp.
References ERR_Fatal, interr(), ISZ_T, LLTypeGetBytesUnchecked(), size, and type.
Referenced by convert_int_size(), convert_mismatched_types(), convert_operand(), gen_base_addr_operand(), gen_llvm_expr(), gen_resized_vect(), layout_struct_body(), ll_create_anon_struct_type(), ll_get_const_addrspacecast(), ll_write_local_objects(), LLTypeGetBytesUnchecked(), make_bitcast(), make_conststring_op(), make_stmt(), match_types(), print_llsize(), print_llsize_tobuf(), process_formal_arguments(), and write_constant_value().
ll_type_bytes_unchecked()
ISZ_T ll_type_bytes_unchecked (LL_Type * type)
Get the size of a type in bytes without checks.
...
Parameters
type The type to be examined
Returns
size of object of type type or 0
Definition at line 912 of file ll_structure.cpp.
References LLTypeGetBytesUnchecked(), NULL, and type.
Referenced by gen_address_operand().
ll_type_int_bits()
unsigned ll_type_int_bits (LL_Type * type)
Get the number of bits in the given integer type.
...
Parameters
type The LL_Type to inspect
Returns
0 iff type is not an integer type
Definition at line 923 of file ll_structure.cpp.
References LL_I1, LL_I128, LL_I16, LL_I24, LL_I256, LL_I32, LL_I40, LL_I48, LL_I56, LL_I64, LL_I8, and type.
Referenced by convert_int_size(), convert_int_to_ptr(), convert_mismatched_types(), gen_base_addr_operand(), gen_const_expr(), gen_llvm_expr(), make_load(), make_stmt(), match_types(), process_formal_arguments(), sign_extend_int(), write_ftn_type(), write_operand(), and zero_extend_int().
ll_type_is_fp()
int ll_type_is_fp (LL_Type * ty)
...
Definition at line 968 of file ll_structure.cpp.
References LL_Type_::data_type, LL_DOUBLE, LL_FLOAT, LL_FP128, LL_HALF, LL_PPC_FP128, and LL_X86_FP80.
Referenced by convert_mismatched_types(), gen_llvm_expr(), process_formal_arguments(), and write_operand().
ll_type_is_mem_seq()
int ll_type_is_mem_seq (LL_Type * ty)
...
Definition at line 985 of file ll_structure.cpp.
References LL_Type_::data_type, LL_ARRAY, and LL_PTR.
Referenced by gen_llvm_expr().
ll_type_is_pointer_to_function()
int ll_type_is_pointer_to_function (LL_Type * ty)
...
Definition at line 955 of file ll_structure.cpp.
References LL_Type_::data_type, LL_FUNCTION, LL_PTR, and LL_Type_::sub_types.
Referenced by write_I_CALL().
ll_update_md_node()
void ll_update_md_node (LLVMModuleRef module, LL_MDRef node_to_update, unsigned elem_index, LL_MDRef elem)
Update one of the elements in a metadata node.
...
The node being updated must be either distinct or flexible, it is not allowed to update nodes that may be shared.
Definition at line 2290 of file ll_structure.cpp.
References assert, LL_MDNode::elem, ERR_Fatal, LL_MDNode::is_distinct, LL_MDNode::is_flexible, LL_MDREF_kind, LL_MDREF_value, LL_Module::mdnodes, MDRef_Node, LL_Type_::module, and slot.
Referenced by lldbg_set_func_ptr().
llObjtodbgFree()
void llObjtodbgFree (LL_ObjToDbgList * ods)
...
Definition at line 359 of file ll_structure.cpp.
References n, and LL_ObjToDbgList::next.
Referenced by assemble_end(), and ll_write_object_dbg_references().
llObjtodbgPush()
void llObjtodbgPush (LL_ObjToDbgList * odl, LL_MDRef md)
...
Definition at line 346 of file ll_structure.cpp.
References LL_ObjToDbgBucketSize, llObjtodbgCreate(), and p.
Referenced by llObjtodbgAddUnique().
LLTypeGetBytesUnchecked()
static ISZ_T LLTypeGetBytesUnchecked (LL_Type * type, int * noSize) static
Get the size of a type in bytes without checks.
Parameters
type The type to be examined
noSize Set if not null and type isn't concrete [output]
Returns
size of an object of type type or 0
Definition at line 827 of file ll_structure.cpp.
References i, ISZ_T, LL_ARRAY, LL_DOUBLE, LL_FLOAT, LL_FP128, LL_HALF, LL_I1, LL_I128, LL_I16, LL_I24, LL_I256, LL_I32, LL_I40, LL_I48, LL_I56, LL_I64, LL_I8, LL_PPC_FP128, LL_PTR, LL_STRUCT, ll_type_bytes(), LL_VECTOR, LL_X86_FP80, sum(), and type.
Referenced by ll_type_bytes(), and ll_type_bytes_unchecked().
mdnode_append()
static void mdnode_append (LLVMModuleRef module, LL_MDNode ** pnode, LL_MDRef elem) static
Append element to flexible mdnode.
Definition at line 2131 of file ll_structure.cpp.
References assert, LL_MDNode::elem, ERR_Fatal, and MIN_FLEX_SIZE.
Referenced by ll_extend_md_node(), and ll_extend_named_md_node().
mdnode_equal()
static int mdnode_equal (hash_key_t key_a, hash_key_t key_b) static
Definition at line 326 of file ll_structure.cpp.
References a, b, and i.
mdnode_hash()
static hash_value_t mdnode_hash (hash_key_t key) static
Definition at line 309 of file ll_structure.cpp.
References HASH_ACCU_ADD, HASH_ACCU_FINISH, HASH_ACCU_INIT, HASH_ACCU_VALUE, i, LL_MDREF_kind, LL_MDREF_value, and t.
types_equal()
static int types_equal (hash_key_t key_a, hash_key_t key_b) static
Definition at line 188 of file ll_structure.cpp.
References a, b, F90_Desc::flags, get_num_subtypes(), i, LL_STRUCT, LL_TYPE_IS_NAMED_STRUCT, and n.
types_hash()
static hash_value_t types_hash (hash_key_t key) static
Definition at line 167 of file ll_structure.cpp.
References get_num_subtypes(), HASH_ACCU_ADD, HASH_ACCU_FINISH, HASH_ACCU_INIT, HASH_ACCU_VALUE, i, and t.
unique_name()
static char * unique_name (hashset_t names, char prefix, const char * format, va_list ap) static
Definition at line 232 of file ll_structure.cpp.
References count, hashset_insert(), hashset_lookup(), hashset_size(), prefix, strlen(), and unique_name().
Referenced by create_global(), ll_create_local_name(), ll_create_local_object(), ll_create_named_struct_type(), and unique_name().
unique_type()
static struct LL_Type_ * unique_type (LLVMModuleRef module, const struct LL_Type_ * type) static
Definition at line 1081 of file ll_structure.cpp.
References LL_Module::anon_types, copy(), hashset_insert(), hashset_lookup(), ll_manage_malloc(), LL_Type_::module, and type.
Referenced by ll_create_anon_struct_type(), ll_create_basic_type(), ll_create_function_type(), ll_get_addrspace_type(), ll_get_array_type(), ll_get_pointer_type(), and ll_get_vector_type().
Variable Documentation
_ll_proto_head
LL_FnProto* _ll_proto_head static
Definition at line 2508 of file ll_structure.cpp.
Referenced by ll_proto_add(), ll_proto_dump(), and ll_proto_iterate().
_ll_proto_map
hashmap_t _ll_proto_map static
Definition at line 2500 of file ll_structure.cpp.
Referenced by ll_proto_add(), ll_proto_get_abi(), ll_proto_has_defined_body(), ll_proto_init(), ll_proto_is_weak(), ll_proto_set_abi(), ll_proto_set_defined_body(), ll_proto_set_intrinsic(), and ll_proto_set_weak().
constants_hash_functions
const hash_functions_t constants_hash_functions static
Initial value:
= {constants_hash,
                                                          constants_equal}
Definition at line 298 of file ll_structure.cpp.
Referenced by ll_create_module().
known_triples
const struct triple_info known_triples[] static
Initial value:
= {
    {"nvptx64-", "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64"
                 "-f32:32:32-f64:64:64-v16:16:16-v32:32:32-v64:64:64-v128:128:"
                 "128-n16:32:64"},
    {"spir64-", "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64"
                "-f32:32:32-f64:64:64-v16:16:16-v24:32:32-v32:32:32-v48:64:64"
                "-v64:64:64-v96:128:128-v128:128:128-v192:256:256"
                "-v256:256:256-v512:512:512-v1024:1024:1024"},
    {"i386", "e-p:32:32-f64:32:64-f80:32-n8:16:32-S128"},
    {"x86_64-apple", "e-m:o-i64:64-f80:128-n8:16:32:64-S128"},
    {"x86_64-", "e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"},
    {"armv7-", "e-p:32:32-i64:64-v128:64:128-n32-S64"},
    {"aarch64-", "e-m:e-i64:64-i128:128-n32:64-S128"},
    {"powerpc64le", "e-p:64:64-i64:64-n32:64"},
    {"", ""}}
Definition at line 453 of file ll_structure.cpp.
Referenced by compute_datalayout().
mdnode_hash_functions
const hash_functions_t mdnode_hash_functions static
Initial value:
= {mdnode_hash,
                                                       mdnode_equal}
Definition at line 342 of file ll_structure.cpp.
Referenced by ll_create_module().
types_hash_functions
const hash_functions_t types_hash_functions = {types_hash, types_equal} static
Definition at line 221 of file ll_structure.cpp.
Referenced by ll_create_module().