flang: ll_write.cpp File Reference
ll_write.cpp File Reference
#include "gbldefs.h"
#include "error.h"
#include "ll_structure.h"
#include "ll_write.h"
#include "global.h"
#include "mach.h"
#include "dwarf2.h"
#include "llutil.h"
#include <stdlib.h>
#include <string.h>
#include <limits.h>
Classes
struct MDTemplate
Templates for printing specialized metadata nodes.
struct MDDispatch
Macros
#define SPACES " "
#define TF ((enum FieldType)0)
#define NextMDName(N) ++(N)
Typedefs
typedef struct MDTemplate MDTemplate
Templates for printing specialized metadata nodes.
typedef const LL_MDNode * MDNodeRef
typedef void(* MDDispatchMethod) (FILE *out, LLVMModuleRef mod, MDNodeRef mdnode, unsigned mdi)
typedef struct MDDispatch MDDispatch
Enumerations
enum FieldType {
UnsignedField , SignedField , BoolField , NodeField ,
StringField , ValueField , DWTagField , DWLangField ,
DWVirtualityField , DWEncodingField , DWEmissionField , SignedOrMDField ,
DebugNameTableKindField
}
enum FieldFlags { FlgMandatory = 0x1 , FlgOptional = 0x2 , FlgHidden = 0x4 , FlgSkip1 = 0x8 }
Functions
static const char * ll_get_atomic_memorder (LL_Instruction *inst)
static const char * ll_get_linkage_string (enum LL_LinkageType linkage)
void ll_write_module_header (FILE *out, LLVMModuleRef module)
Write out the header of a module.
void ll_write_user_structs (FILE *out, LLVMModuleRef module)
Write out definitions for named struct types in module.
static const char * get_op_name (enum LL_Op op)
static void add_prototype (LL_Instruction *instruction)
static bool defined_in_module (LL_Function *function, LLVMModuleRef module)
static void write_prototypes (FILE *out, LLVMModuleRef module)
static void clear_prototypes (void)
static void render_bitcast (FILE *out, LL_Instruction *inst)
static void render_store (FILE *out, LL_Instruction *inst)
static const char * ll_get_atomic_opr (LL_Instruction *inst)
void ll_write_instruction (FILE *out, LL_Instruction *inst, LL_Module *module, int no_return)
...
void ll_write_object_dbg_references (FILE *out, LL_Module *m, LL_ObjToDbgList *ods)
Emit a list of !dbg n annotations.
void ll_write_basicblock (FILE *out, LL_Function *function, LL_BasicBlock *block, LL_Module *module, int no_return)
...
void ll_write_local_objects (FILE *out, LL_Function *function)
Write out definitions of local objects in function as a series of alloca instructions.
void ll_write_function (FILE *out, LL_Function *function, LL_Module *module, bool no_return, const char *prefix)
...
void write_mdref (FILE *out, LL_Module *module, LL_MDRef rmdref, int omit_metadata_type)
Write out an LL_MDRef from module.
static const char * dwarf_emission_name (int value)
generate full DWARF debug emission mode
static const char * dwarf_table_name (int value)
generate DWARF table kind
static int write_mdfield (FILE *out, LL_Module *module, int needs_comma, LL_MDRef mdref, const MDTemplate *tmpl)
Write out an an LL_MDRef as a field in a specialised MDNode class.
static void write_mdnode_plain (FILE *out, LL_Module *module, const LL_MDNode *node, int omit_metadata_type)
static void write_mdnode_spec (FILE *out, LL_Module *module, const LL_MDNode *node, const MDTemplate *tmpl)
static const char * get_metadata_name (LL_MDName name)
Get the textual name for module-level named metadata.
static void emitRegular (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDICompileUnit (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDIFile (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDIBasicType (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDIBasicStringType (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDIStringType (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDISubroutineType (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDIDerivedType (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDICompositeType (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDIFortranArrayType (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDISubRange (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDIFortranSubrange (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDIEnumerator (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDINamespace (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDIModule (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDIGlobalVariable (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDISubprogram (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDILexicalBlock (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDILexicalBlockFile (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDILocation (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDILocalVariable (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDIExpression (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDIGlobalVariableExpression (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDIImportedEntity (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDICommonBlock (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static void emitDIGenericSubRange (FILE *, LLVMModuleRef, MDNodeRef, unsigned)
static INLINE void emitRegularPrefix (FILE *out, unsigned mdi)
static INLINE bool useSpecialized (LLVMModuleRef mod)
static INLINE void emitRegular (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static INLINE void emitSpec (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi, const MDTemplate *tmpl)
static INLINE void emitUnspec (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi, const MDTemplate *tmpl)
static void emitTmpl (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi, const MDTemplate *tmpl)
static void emitDICompileUnit (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDIFile (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDIBasicType (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDIStringType (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDIBasicStringType (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDISubroutineType (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDIDerivedType (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDICompositeType (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDIFortranArrayType (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDISubRange (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDIGenericSubRange (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDIFortranSubrange (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDIEnumerator (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDINamespace (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDIModule (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnd, unsigned mdi)
static void emitDIGlobalVariable (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDISubprogram (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDILexicalBlock (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDILexicalBlockFile (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDILocation (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDILocalVariable (FILE *out, LLVMModuleRef mod, const LL_MDNode *node, unsigned mdi)
static void emitDIImportedEntity (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDICommonBlock (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static INLINE const char * ll_dw_op_to_name (LL_DW_OP_t op)
static INLINE const char * decode_expression_op (LLVMModuleRef mod, LL_MDRef md, char *buff)
static void emitComplexDIExpression (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDIExpression (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void emitDIGlobalVariableExpression (FILE *out, LLVMModuleRef mod, const LL_MDNode *mdnode, unsigned mdi)
static void write_metadata_node (FILE *out, LLVMModuleRef module, MDNodeRef node, unsigned mdi)
void ll_write_metadata (FILE *out, LLVMModuleRef module)
Write out all the module metadata.
void ll_write_global_var_signature (FILE *out, LL_Value *variable)
...
void ll_write_llvm_used (FILE *out, LLVMModuleRef module)
Write definition of the special @llvm.used global.
void ll_write_global_objects (FILE *out, LLVMModuleRef module)
Write out definitions or declarations of global LL_Objects.
void ll_write_module (FILE *out, LL_Module *module, int generate_no_return_variants, const char *no_return_prefix)
...
Variables
static LL_Function * called
static int debug_calls = 0
static int text_calls = 0
static const char * szatomic_opr [10]
static const char * szmemorder [7]
static const MDTemplate Tmpl_DILocation []
static const MDTemplate Tmpl_MDLocation []
static const MDTemplate Tmpl_DIFile_pair []
static const MDTemplate Tmpl_DIFile_tagged []
static const MDTemplate Tmpl_DIFile_pre34 []
static const MDTemplate Tmpl_DICompileUnit []
static const MDTemplate Tmpl_DICompileUnit_ver39 []
static const MDTemplate Tmpl_DICompileUnit_pre34 []
static const MDTemplate Tmpl_DINamespace_pre34 []
static const MDTemplate Tmpl_DINamespace_post34 []
static const MDTemplate Tmpl_DINamespace_5 []
static const MDTemplate Tmpl_DIModule []
static const MDTemplate Tmpl_DIModule_11 []
static const MDTemplate Tmpl_DISubprogram []
static const MDTemplate Tmpl_DISubprogram_13 []
static const MDTemplate Tmpl_DISubprogram_90 []
static const MDTemplate Tmpl_DISubprogram_70 []
static const MDTemplate Tmpl_DISubprogram_38 []
static const MDTemplate Tmpl_DISubprogram_39 []
static const MDTemplate Tmpl_DILexicalBlock []
static const MDTemplate Tmpl_DILexicalBlock_pre34 []
static const MDTemplate Tmpl_DILexicalBlockFile []
static const MDTemplate Tmpl_DIExpression []
static const MDTemplate Tmpl_DILocalVariable_38 []
static const MDTemplate Tmpl_DILocalVariable_embedded_argnum []
static const MDTemplate Tmpl_DIGlobalVariable []
static const MDTemplate Tmpl_DIGlobalVariable4 []
static const MDTemplate Tmpl_DIGlobalVariableExpression []
static const MDTemplate Tmpl_DIBasicType_pre34 []
static const MDTemplate Tmpl_DIBasicType []
static const MDTemplate Tmpl_DIStringType_old []
static const MDTemplate Tmpl_DIStringType []
static const MDTemplate Tmpl_DISubroutineType []
static const MDTemplate Tmpl_DIDerivedType_pre34 []
static const MDTemplate Tmpl_DIDerivedType []
static const MDTemplate Tmpl_DICompositeType_pre34 []
static const MDTemplate Tmpl_DICompositeType []
static const MDTemplate Tmpl_DIFortranArrayType []
static const MDTemplate Tmpl_DISubrange_pre11 []
static const MDTemplate Tmpl_DISubrange []
static const MDTemplate Tmpl_DIGenericSubrange []
static const MDTemplate Tmpl_DISubrange_pre37 []
static const MDTemplate Tmpl_DIFortranSubrange []
static const MDTemplate Tmpl_DIEnumerator []
static const MDTemplate Tmpl_DIImportedEntity_pre11 []
static const MDTemplate Tmpl_DIImportedEntity []
static const MDTemplate Tmpl_DICommonBlock []
static MDDispatch mdDispTable [LL_MDClass_MAX]
Macro Definition Documentation
NextMDName
#define NextMDName (N) ++(N)
Definition at line 2329 of file ll_write.cpp.
SPACES
#define SPACES " "
Definition at line 28 of file ll_write.cpp.
TF
#define TF ((enum FieldType)0)
Definition at line 862 of file ll_write.cpp.
Typedef Documentation
MDDispatch
typedef struct MDDispatch MDDispatch
MDDispatchMethod
typedef void(* MDDispatchMethod) (FILE *out, LLVMModuleRef mod, MDNodeRef mdnode, unsigned mdi)
Definition at line 1855 of file ll_write.cpp.
MDNodeRef
typedef const LL_MDNode* MDNodeRef
Definition at line 1825 of file ll_write.cpp.
MDTemplate
typedef struct MDTemplate MDTemplate
Templates for printing specialized metadata nodes.
A template is an array of MDTemplate structs with nf+1 elements where nf is the number of fields.
The first entry of the array is the class name without the leading bang (e.g., "MDLocation"), and the "flags" field contains nf.
The remaining entries correspond to the node elements, the names are field names without the trailing colon.
Enumeration Type Documentation
FieldFlags
enum FieldFlags
Enumerator
FlgMandatory
Field must be present, even with a default value
FlgOptional
Field does not have to be present in the MDNode
FlgHidden
Field is never printed
FlgSkip1
special skip handling of signed constant
Definition at line 837 of file ll_write.cpp.
FieldType
enum FieldType
Enumerator
UnsignedField
SignedField
BoolField
NodeField
StringField
ValueField
DWTagField
DWLangField
DWVirtualityField
DWEncodingField
DWEmissionField
SignedOrMDField
DebugNameTableKindField
Definition at line 821 of file ll_write.cpp.
Function Documentation
add_prototype()
static void add_prototype (LL_Instruction * instruction) static
Definition at line 194 of file ll_write.cpp.
References LL_Function_::arguments, LL_Function_::attributes, called, LL_Value::data, i, ll_set_function_num_arguments(), malloc(), LL_Function_::name, LL_Function_::next, NULL, LL_Function_::num_args, LL_Instruction_::num_operands, LL_Instruction_::operands, LL_Function_::return_type, LL_Value::storage, and LL_Value::type_struct.
Referenced by ll_write_instruction().
clear_prototypes()
static void clear_prototypes (void) static
Definition at line 285 of file ll_write.cpp.
References LL_Function_::arguments, called, LL_Function_::next, and NULL.
Referenced by ll_write_module().
decode_expression_op()
static INLINE const char * decode_expression_op (LLVMModuleRef mod, LL_MDRef md, char * buff) static
Definition at line 2249 of file ll_write.cpp.
References buff, LL_Module::constants, DEBUG_ASSERT, ll_dw_op_to_name(), LL_MDREF_kind, LL_MDREF_value, MDRef_Constant, MDRef_SmallInt32, and value().
Referenced by emitComplexDIExpression().
defined_in_module()
static bool defined_in_module (LL_Function * function, LLVMModuleRef module) static
Definition at line 230 of file ll_write.cpp.
References LL_Module::first, LL_Function_::name, LL_Function_::next, and NULL.
Referenced by write_prototypes().
dwarf_emission_name()
static const char * dwarf_emission_name (int value) static
generate full DWARF debug emission mode
Definition at line 1560 of file ll_write.cpp.
References value().
Referenced by write_mdfield().
dwarf_table_name()
static const char * dwarf_table_name (int value) static
generate DWARF table kind
Definition at line 1576 of file ll_write.cpp.
References value().
Referenced by write_mdfield().
emitComplexDIExpression()
static void emitComplexDIExpression (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2269 of file ll_write.cpp.
References buff, cnt, decode_expression_op(), LL_MDNode::elem, emitRegularPrefix(), i, and LL_MDNode::num_elems.
Referenced by emitDIExpression().
emitDIBasicStringType() [1/2]
static void emitDIBasicStringType (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDIBasicStringType() [2/2]
static void emitDIBasicStringType (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 1991 of file ll_write.cpp.
References emitTmpl(), and Tmpl_DIStringType_old.
emitDIBasicType() [1/2]
static void emitDIBasicType (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDIBasicType() [2/2]
static void emitDIBasicType (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 1972 of file ll_write.cpp.
References emitTmpl(), LL_Module::ir, ll_feature_debug_info_pre34, Tmpl_DIBasicType, and Tmpl_DIBasicType_pre34.
emitDICommonBlock() [1/2]
static void emitDICommonBlock (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDICommonBlock() [2/2]
static void emitDICommonBlock (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2203 of file ll_write.cpp.
References emitTmpl(), and Tmpl_DICommonBlock.
emitDICompileUnit() [1/2]
static void emitDICompileUnit (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDICompileUnit() [2/2]
static void emitDICompileUnit (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 1943 of file ll_write.cpp.
References emitTmpl(), LL_Module::ir, ll_feature_debug_info_pre34, ll_feature_subprogram_not_in_cu, Tmpl_DICompileUnit, Tmpl_DICompileUnit_pre34, and Tmpl_DICompileUnit_ver39.
emitDICompositeType() [1/2]
static void emitDICompositeType (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDICompositeType() [2/2]
static void emitDICompositeType (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2016 of file ll_write.cpp.
References emitTmpl(), LL_Module::ir, ll_feature_debug_info_pre34, Tmpl_DICompositeType, and Tmpl_DICompositeType_pre34.
emitDIDerivedType() [1/2]
static void emitDIDerivedType (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDIDerivedType() [2/2]
static void emitDIDerivedType (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2005 of file ll_write.cpp.
References emitTmpl(), LL_Module::ir, ll_feature_debug_info_pre34, Tmpl_DIDerivedType, and Tmpl_DIDerivedType_pre34.
emitDIEnumerator() [1/2]
static void emitDIEnumerator (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDIEnumerator() [2/2]
static void emitDIEnumerator (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2063 of file ll_write.cpp.
References emitTmpl(), and Tmpl_DIEnumerator.
emitDIExpression() [1/2]
static void emitDIExpression (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDIExpression() [2/2]
static void emitDIExpression (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2287 of file ll_write.cpp.
References emitComplexDIExpression(), emitSpec(), emitUnspec(), LL_MDNode::num_elems, Tmpl_DIExpression, and useSpecialized().
emitDIFile() [1/2]
static void emitDIFile (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDIFile() [2/2]
static void emitDIFile (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 1958 of file ll_write.cpp.
References LL_MDNode::elem, emitTmpl(), emitUnspec(), LL_Module::ir, ll_feature_debug_info_pre34, LL_MDREF_kind, MDRef_String, Tmpl_DIFile_pair, Tmpl_DIFile_pre34, and Tmpl_DIFile_tagged.
emitDIFortranArrayType() [1/2]
static void emitDIFortranArrayType (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDIFortranArrayType() [2/2]
static void emitDIFortranArrayType (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2027 of file ll_write.cpp.
References emitTmpl(), and Tmpl_DIFortranArrayType.
emitDIFortranSubrange() [1/2]
static void emitDIFortranSubrange (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDIFortranSubrange() [2/2]
static void emitDIFortranSubrange (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2056 of file ll_write.cpp.
References emitTmpl(), and Tmpl_DIFortranSubrange.
emitDIGenericSubRange() [1/2]
static void emitDIGenericSubRange (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDIGenericSubRange() [2/2]
static void emitDIGenericSubRange (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2049 of file ll_write.cpp.
References emitTmpl(), and Tmpl_DIGenericSubrange.
emitDIGlobalVariable() [1/2]
static void emitDIGlobalVariable (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDIGlobalVariable() [2/2]
static void emitDIGlobalVariable (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2095 of file ll_write.cpp.
References emitTmpl(), LL_Module::ir, ll_feature_from_global_to_md, Tmpl_DIGlobalVariable, and Tmpl_DIGlobalVariable4.
emitDIGlobalVariableExpression() [1/2]
static void emitDIGlobalVariableExpression (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDIGlobalVariableExpression() [2/2]
static void emitDIGlobalVariableExpression (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2306 of file ll_write.cpp.
References emitTmpl(), and Tmpl_DIGlobalVariableExpression.
emitDIImportedEntity() [1/2]
static void emitDIImportedEntity (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDIImportedEntity() [2/2]
static void emitDIImportedEntity (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2191 of file ll_write.cpp.
References emitTmpl(), LL_Module::ir, ll_feature_debug_info_ver11, Tmpl_DIImportedEntity, and Tmpl_DIImportedEntity_pre11.
emitDILexicalBlock() [1/2]
static void emitDILexicalBlock (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDILexicalBlock() [2/2]
static void emitDILexicalBlock (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2143 of file ll_write.cpp.
References emitTmpl(), LL_Module::ir, ll_feature_debug_info_pre34, Tmpl_DILexicalBlock, and Tmpl_DILexicalBlock_pre34.
emitDILexicalBlockFile() [1/2]
static void emitDILexicalBlockFile (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDILexicalBlockFile() [2/2]
static void emitDILexicalBlockFile (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2154 of file ll_write.cpp.
References emitTmpl(), and Tmpl_DILexicalBlockFile.
emitDILocalVariable() [1/2]
static void emitDILocalVariable (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDILocalVariable() [2/2]
static void emitDILocalVariable (FILE * out, LLVMModuleRef mod, const LL_MDNode * node, unsigned mdi) static
Definition at line 2175 of file ll_write.cpp.
References emitTmpl(), LL_Module::ir, ll_feature_dbg_local_variable_embeds_argnum, ll_feature_debug_info_ver38, Tmpl_DILocalVariable_38, Tmpl_DILocalVariable_embedded_argnum, and Tmpl_DILocation.
emitDILocation() [1/2]
static void emitDILocation (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDILocation() [2/2]
static void emitDILocation (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2161 of file ll_write.cpp.
References emitTmpl(), emitUnspec(), LL_Module::ir, ll_feature_debug_info_DI_syntax, ll_feature_debug_info_mdlocation, Tmpl_DILocation, and Tmpl_MDLocation.
emitDIModule() [1/2]
static void emitDIModule (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDIModule() [2/2]
static void emitDIModule (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnd, unsigned mdi) static
Definition at line 2085 of file ll_write.cpp.
References emitTmpl(), LL_Module::ir, ll_feature_debug_info_ver11, Tmpl_DIModule, and Tmpl_DIModule_11.
emitDINamespace() [1/2]
static void emitDINamespace (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDINamespace() [2/2]
static void emitDINamespace (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2070 of file ll_write.cpp.
References emitTmpl(), LL_Module::ir, ll_feature_debug_info_pre34, ll_feature_no_file_in_namespace, Tmpl_DINamespace_5, Tmpl_DINamespace_post34, and Tmpl_DINamespace_pre34.
emitDIStringType() [1/2]
static void emitDIStringType (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDIStringType() [2/2]
static void emitDIStringType (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 1983 of file ll_write.cpp.
References emitTmpl(), and Tmpl_DIStringType.
emitDISubprogram() [1/2]
static void emitDISubprogram (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDISubprogram() [2/2]
static void emitDISubprogram (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2106 of file ll_write.cpp.
References emitRegular(), emitTmpl(), LL_Module::ir, ll_feature_debug_info_pre34, ll_feature_debug_info_ver13, ll_feature_debug_info_ver38, ll_feature_debug_info_ver70, ll_feature_debug_info_ver90, ll_feature_subprogram_not_in_cu, Tmpl_DISubprogram, Tmpl_DISubprogram_13, Tmpl_DISubprogram_38, Tmpl_DISubprogram_39, Tmpl_DISubprogram_70, and Tmpl_DISubprogram_90.
emitDISubRange() [1/2]
static void emitDISubRange (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDISubRange() [2/2]
static void emitDISubRange (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 2034 of file ll_write.cpp.
References emitTmpl(), LL_Module::ir, ll_feature_debug_info_subrange_needs_count, ll_feature_debug_info_ver90, Tmpl_DISubrange, Tmpl_DISubrange_pre11, and Tmpl_DISubrange_pre37.
emitDISubroutineType() [1/2]
static void emitDISubroutineType (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
emitDISubroutineType() [2/2]
static void emitDISubroutineType (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 1998 of file ll_write.cpp.
References emitTmpl(), and Tmpl_DISubroutineType.
emitRegular() [1/2]
static void emitRegular (FILE * , LLVMModuleRef , MDNodeRef , unsigned) static
Referenced by emitDISubprogram(), and emitUnspec().
emitRegular() [2/2]
static INLINE void emitRegular (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi) static
Definition at line 1908 of file ll_write.cpp.
References emitRegularPrefix(), LL_Module::ir, ll_feature_omit_metadata_type, and write_mdnode_plain().
emitRegularPrefix()
static INLINE void emitRegularPrefix (FILE * out, unsigned mdi) static
Definition at line 1895 of file ll_write.cpp.
Referenced by emitComplexDIExpression(), emitRegular(), and emitSpec().
emitSpec()
static INLINE void emitSpec (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi, const MDTemplate * tmpl) static
Definition at line 1915 of file ll_write.cpp.
References emitRegularPrefix(), and write_mdnode_spec().
Referenced by emitDIExpression(), emitTmpl(), and emitUnspec().
emitTmpl()
static void emitTmpl (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi, const MDTemplate * tmpl) static
Definition at line 1932 of file ll_write.cpp.
References emitSpec(), emitUnspec(), and useSpecialized().
Referenced by emitDIBasicStringType(), emitDIBasicType(), emitDICommonBlock(), emitDICompileUnit(), emitDICompositeType(), emitDIDerivedType(), emitDIEnumerator(), emitDIFile(), emitDIFortranArrayType(), emitDIFortranSubrange(), emitDIGenericSubRange(), emitDIGlobalVariable(), emitDIGlobalVariableExpression(), emitDIImportedEntity(), emitDILexicalBlock(), emitDILexicalBlockFile(), emitDILocalVariable(), emitDILocation(), emitDIModule(), emitDINamespace(), emitDIStringType(), emitDISubprogram(), emitDISubRange(), and emitDISubroutineType().
emitUnspec()
static INLINE void emitUnspec (FILE * out, LLVMModuleRef mod, const LL_MDNode * mdnode, unsigned mdi, const MDTemplate * tmpl) static
Definition at line 1923 of file ll_write.cpp.
References emitRegular(), and emitSpec().
Referenced by emitDIExpression(), emitDIFile(), emitDILocation(), and emitTmpl().
get_metadata_name()
static const char * get_metadata_name (LL_MDName name) static
Get the textual name for module-level named metadata.
Definition at line 1804 of file ll_write.cpp.
References ERR_Fatal, interr(), MD_llvm_dbg_cu, MD_llvm_linker_options, MD_llvm_module_flags, MD_nvvm_annotations, MD_nvvmir_version, MD_opencl_kernels, name, and NULL.
Referenced by ll_write_metadata().
get_op_name()
static const char * get_op_name (enum LL_Op op) static
Definition at line 109 of file ll_write.cpp.
References LL_ADD, LL_AND, LL_ASHR, LL_ATOMICRMW, LL_BITCAST, LL_CMPXCHG, LL_EXTRACTELEM, LL_EXTRACTVALUE, LL_FADD, LL_FCMP, LL_FDIV, LL_FMUL, LL_FNEG, LL_FPEXT, LL_FPTOSI, LL_FPTOUI, LL_FPTRUNC, LL_FSUB, LL_ICMP, LL_INSERTELEM, LL_INSERTVALUE, LL_INTTOPTR, LL_LSHR, LL_MUL, LL_OR, LL_PTRTOINT, LL_SDIV, LL_SEXT, LL_SHL, LL_SITOFP, LL_SREM, LL_SUB, LL_TRUNC, LL_UDIV, LL_UITOFP, LL_UREM, LL_XOR, and LL_ZEXT.
Referenced by ll_write_instruction().
ll_dw_op_to_name()
static INLINE const char * ll_dw_op_to_name (LL_DW_OP_t op) static
Definition at line 2210 of file ll_write.cpp.
References DEBUG_ASSERT, LL_DW_OP_and, LL_DW_OP_constu, LL_DW_OP_deref, LL_DW_OP_dup, LL_DW_OP_LLVM_fragment, LL_DW_OP_minus, LL_DW_OP_mul, LL_DW_OP_over, LL_DW_OP_plus, LL_DW_OP_plus_uconst, LL_DW_OP_push_object_address, LL_DW_OP_stack_value, LL_DW_OP_swap, and LL_DW_OP_xderef.
Referenced by decode_expression_op().
ll_get_atomic_memorder()
static const char * ll_get_atomic_memorder (LL_Instruction * inst) static
Definition at line 375 of file ll_write.cpp.
References ATOMIC_ACQ_REL_FLAG, ATOMIC_ACQUIRE_FLAG, ATOMIC_MEM_ORD_FLAGS, ATOMIC_MONOTONIC_FLAG, ATOMIC_RELEASE_FLAG, ATOMIC_SEQ_CST_FLAG, ERR_Severe, LL_Instruction_::flags, idx, interr(), NULL, and szmemorder.
Referenced by ll_write_instruction().
ll_get_atomic_opr()
static const char * ll_get_atomic_opr (LL_Instruction * inst) static
Definition at line 349 of file ll_write.cpp.
References assert, ATOMIC_ADD_FLAG, ATOMIC_AND_FLAG, ATOMIC_MAX_FLAG, ATOMIC_MIN_FLAG, ATOMIC_OR_FLAG, ATOMIC_RMW_OP_FLAGS, ATOMIC_SUB_FLAG, ATOMIC_XCHG_FLAG, ATOMIC_XOR_FLAG, ERR_Fatal, flags, LL_Instruction_::flags, idx, NULL, and szatomic_opr.
Referenced by ll_write_instruction().
ll_get_linkage_string()
static const char * ll_get_linkage_string (enum LL_LinkageType linkage) static
Definition at line 42 of file ll_write.cpp.
References LL_COMMON_LINKAGE, LL_EXTERNAL_LINKAGE, LL_INTERNAL_LINKAGE, LL_NO_LINKAGE, and LL_WEAK_LINKAGE.
Referenced by ll_write_function(), ll_write_global_objects(), and ll_write_module().
ll_write_basicblock()
void ll_write_basicblock (FILE * out, LL_Function * function, LL_BasicBlock * block, LL_Module * module, int no_return)
...
Definition at line 684 of file ll_write.cpp.
References LL_BasicBlock_::first, LL_Function_::first, ll_write_instruction(), ll_write_local_objects(), LL_BasicBlock_::name, and LL_Instruction_::next.
Referenced by ll_write_function().
ll_write_function()
void ll_write_function (FILE * out, LL_Function * function, LL_Module * module, bool no_return, const char * prefix)
...
Definition at line 786 of file ll_write.cpp.
References LL_Function_::arguments, LL_Function_::calling_convention, LL_Value::data, LL_Function_::first, LL_Value::flags, i, LL_Function_::linkage, ll_get_linkage_string(), ll_write_basicblock(), LL_Function_::name, LL_BasicBlock_::next, LL_Function_::num_args, prefix, LL_Function_::return_type, LL_Type_::str, LL_Value::type_struct, and VAL_IS_NOALIAS_PARAM.
Referenced by ll_write_module().
ll_write_global_objects()
void ll_write_global_objects (FILE * out, LLVMModuleRef module)
Write out definitions or declarations of global LL_Objects.
...
If this function is called more than once, only the new objects added since the last call will be written.
Definition at line 2426 of file ll_write.cpp.
References LL_Object::address, LL_Object::align_bytes, LL_Object::const_expr, LL_Value::data, ERR_Fatal, LL_Module::first_global, LL_Object::init_data, LL_Object::init_style, interr(), LL_Object::kind, LL_Module::last_global, LL_Object::linkage, LL_EXTERNAL_LINKAGE, ll_get_linkage_string(), ll_get_pointer_addrspace(), LLInit_ConstExpr, LLInit_Declaration, LLInit_Function, LLInit_Zero, LLObj_Alias, LLObj_Const, LLObj_Global, LL_Object::next, NULL, LL_Type_::str, LL_Object::type, and LL_Value::type_struct.
Referenced by ll_write_module().
ll_write_global_var_signature()
void ll_write_global_var_signature (FILE * out, LL_Value * variable)
...
Definition at line 2356 of file ll_write.cpp.
References LL_Value::data, LL_GLOBAL, and LL_Value::mvtype.
ll_write_instruction()
void ll_write_instruction (FILE * out, LL_Instruction * inst, LL_Module * module, int no_return)
...
Definition at line 396 of file ll_write.cpp.
References add_prototype(), LL_Instruction_::comment, LL_Value::data, LL_Type_::data_type, LL_Instruction_::dbg_line_op, fflush(), LL_Instruction_::flags, get_op_name(), i, IN_MODULE_CALL, INST_CANCELED, INST_INBOUND, INST_INDIRECT_CALL, INST_VOLATILE, LL_Module::ir, LL_ADD, LL_ALLOCA, LL_AND, LL_ASHR, LL_ASM, LL_ATOMICRMW, LL_BITCAST, LL_BR, LL_CALL, LL_CMPXCHG, LL_EXTRACTELEM, LL_EXTRACTVALUE, LL_FADD, LL_FCMP, LL_FDIV, ll_feature_explicit_gep_load_type, LL_FMUL, LL_FNEG, LL_FPEXT, LL_FPTOSI, LL_FPTOUI, LL_FPTRUNC, LL_FSUB, LL_GEP, ll_get_atomic_memorder(), ll_get_atomic_opr(), LL_ICMP, LL_INSERTELEM, LL_INSERTVALUE, LL_INTTOPTR, LL_LOAD, LL_LSHR, LL_MDREF_IS_NULL, LL_MDREF_value, LL_MUL, LL_NONE, LL_OR, LL_PTRTOINT, LL_RET, LL_SDIV, LL_SELECT, LL_SEXT, LL_SHL, LL_SITOFP, LL_SREM, LL_STORE, LL_SUB, LL_SWITCH, LL_TEXTCALL, LL_TRUNC, LL_UBR, LL_UDIV, LL_UITOFP, LL_UNREACHABLE, LL_UREM, LL_VOID, LL_XOR, LL_ZEXT, LL_Instruction_::num_operands, LL_Instruction_::op, LL_Instruction_::operands, render_bitcast(), render_store(), SPACES, LL_Type_::str, LL_Type_::sub_types, text_calls, and LL_Value::type_struct.
Referenced by ll_write_basicblock().
ll_write_llvm_used()
void ll_write_llvm_used (FILE * out, LLVMModuleRef module)
Write definition of the special @llvm.used global.
...
Definition at line 2370 of file ll_write.cpp.
References LL_Value::data, i, LL_Module::llvm_used, LL_Module::num_llvm_used, LL_Type_::str, LL_Value::type_struct, and LL_Symbols_::values.
Referenced by ll_write_module().
ll_write_local_objects()
void ll_write_local_objects (FILE * out, LL_Function * function)
Write out definitions of local objects in function as a series of alloca instructions.
...
Unlike ll_write_global_objects(), this function only expects to be called once per function.
Definition at line 709 of file ll_write.cpp.
References LL_Object::address, LL_Object::align_bytes, assert, LL_Value::data, ERR_Fatal, LL_Function_::first_local, i, LL_Object::kind, ll_type_bytes(), LLObj_LocalBuffered, make_lltype_from_sptr(), name, LL_Object::next, SNAME, LL_Object::sptr, LL_Type_::str, LL_Object::type, and XBIT.
Referenced by ll_write_basicblock(), and schedule().
ll_write_metadata()
void ll_write_metadata (FILE * out, LLVMModuleRef module)
Write out all the module metadata.
...
Write out all the so-called named metadata and then the regular metadata
Definition at line 2338 of file ll_write.cpp.
References get_metadata_name(), i, j, MD_llvm_module_flags, MD_NUM_NAMES, LL_Module::mdnodes, LL_Module::mdnodes_count, LL_Module::named_mdnodes, NextMDName, write_mdnode_plain(), and write_metadata_node().
Referenced by cg_llvm_end(), and ll_write_module().
ll_write_module()
void ll_write_module (FILE * out, LL_Module * module, int generate_no_return_variants, const char * no_return_prefix)
...
Definition at line 2495 of file ll_write.cpp.
References LL_Type_::addrspace, LL_Value::align_bytes, clear_prototypes(), LL_Value::data, LL_Type_::data_type, LL_Module::first, LL_Value::flags, i, LL_Value::linkage, LL_COMMON_LINKAGE, LL_CONSTANT, LL_DEVICE, LL_DOUBLE, LL_EXTERNAL_LINKAGE, LL_FLOAT, ll_get_linkage_string(), LL_GLOBAL, LL_I1, LL_I16, LL_I32, LL_I64, LL_I8, LL_INTERNAL_LINKAGE, LL_NO_LINKAGE, LL_PTR, LL_WEAK_LINKAGE, ll_write_function(), ll_write_global_objects(), ll_write_llvm_used(), ll_write_metadata(), ll_write_module_header(), ll_write_user_structs(), LL_Module::module_vars, LL_Value::mvtype, LL_Function_::next, LL_Module::num_module_vars, LL_Value::storage, LL_Type_::str, LL_Type_::sub_types, LL_Value::type_struct, VAL_IS_TEXTURE, LL_Symbols_::values, and write_prototypes().
ll_write_module_header()
void ll_write_module_header (FILE * out, LLVMModuleRef module)
Write out the header of a module.
...
The header is: Module ID, target triple, and datalayout
Definition at line 65 of file ll_write.cpp.
References LL_Module::datalayout_string, LL_Module::module_name, and LL_Module::target_triple.
Referenced by init_gpu_output_file(), init_output_file(), and ll_write_module().
ll_write_object_dbg_references()
void ll_write_object_dbg_references (FILE * out, LL_Module * m, LL_ObjToDbgList * ods)
Emit a list of !dbg n annotations.
...
Parameters
ods the object to !dbg list
In LLVM 4.0, we can generate a list of comma separated !dbg metadata to link the object to a number of debug metadata descriptions.
Definition at line 671 of file ll_write.cpp.
References i, ll_feature_from_global_to_md, LL_MDREF_value, llObjtodbgAtEnd(), llObjtodbgFirst(), llObjtodbgFree(), llObjtodbgGet(), llObjtodbgNext(), and m.
Referenced by write_bss(), and write_statics().
ll_write_user_structs()
void ll_write_user_structs (FILE * out, LLVMModuleRef module)
Write out definitions for named struct types in module.
...
If this function is called more than once, only the new types added since the last call are written.
Definition at line 82 of file ll_write.cpp.
References i, j, LL_TYPE_IS_PACKED_STRUCT, type, LL_Module::user_structs, val, LL_Symbols_::values, and LL_Module::written_user_structs.
Referenced by ll_write_module().
render_bitcast()
static void render_bitcast (FILE * out, LL_Instruction * inst) static
Definition at line 300 of file ll_write.cpp.
References LL_Value::data, LL_Type_::data_type, LL_PTR, LL_Instruction_::operands, SPACES, LL_Type_::str, and LL_Value::type_struct.
Referenced by ll_write_instruction().
render_store()
static void render_store (FILE * out, LL_Instruction * inst) static
Definition at line 315 of file ll_write.cpp.
References LL_Value::data, LL_Type_::data_type, LL_Instruction_::flags, INST_VOLATILE, LL_FLOAT, LL_PTR, LL_Instruction_::num_operands, LL_Instruction_::operands, SPACES, LL_Type_::str, szmemorder, and LL_Value::type_struct.
Referenced by ll_write_instruction().
useSpecialized()
static INLINE bool useSpecialized (LLVMModuleRef mod) static
Simple helper function
Definition at line 1902 of file ll_write.cpp.
References LL_Module::ir, and ll_feature_use_specialized_mdnodes.
Referenced by emitDIExpression(), and emitTmpl().
write_mdfield()
static int write_mdfield (FILE * out, LL_Module * module, int needs_comma, LL_MDRef mdref, const MDTemplate * tmpl) static
Write out an an LL_MDRef as a field in a specialised MDNode class.
Parameters
out file to write to
module module containing the metadata
node the metadata node to be written
needs_comma If true, print a ", " before the field label
Returns
true iff the field was actually printed
Includes priting the "name:" label. The field is not printed if it has its default value.
The formatting is guided by the field type from the MDTemplate, and the MDRef types are validated.
Definition at line 1605 of file ll_write.cpp.
References assert, BoolField, LL_Module::constants, LL_Value::data, DebugNameTableKindField, dwarf_emission_name(), dwarf_encoding_name(), dwarf_lang_name(), dwarf_table_name(), dwarf_tag_name(), dwarf_virtuality_name(), DWEmissionField, DWEncodingField, DWLangField, DWTagField, DWVirtualityField, ERR_Fatal, ERR_unused, MDTemplate::flags, FlgHidden, FlgMandatory, FlgSkip1, interr(), ISZ_PF, ISZ_T, LL_MDREF_kind, LL_MDREF_value, M, MDRef_Constant, MDRef_Node, MDRef_SmallInt1, MDRef_SmallInt32, MDRef_SmallInt64, MDRef_String, LL_Module::mdstrings, MDTemplate::name, NodeField, NULL, prefix, SignedField, SignedOrMDField, LL_Type_::str, StringField, MDTemplate::type, LL_Value::type_struct, UnsignedField, value(), and ValueField.
Referenced by write_mdnode_spec().
write_mdnode_plain()
static void write_mdnode_plain (FILE * out, LL_Module * module, const LL_MDNode * node, int omit_metadata_type) static
Definition at line 1751 of file ll_write.cpp.
References LL_MDNode::elem, i, LL_Module::ir, LL_MDNode::is_distinct, ll_feature_use_distinct_metadata, LL_MDREF_INITIALIZER, LL_MDNode::num_elems, and write_mdref().
Referenced by emitRegular(), and ll_write_metadata().
write_mdnode_spec()
static void write_mdnode_spec (FILE * out, LL_Module * module, const LL_MDNode * node, const MDTemplate * tmpl) static
Definition at line 1780 of file ll_write.cpp.
References assert, LL_MDNode::elem, ERR_Fatal, MDTemplate::flags, i, LL_Module::ir, LL_MDNode::is_distinct, ll_feature_use_distinct_metadata, MDTemplate::name, LL_MDNode::num_elems, and write_mdfield().
Referenced by emitSpec().
write_mdref()
void write_mdref (FILE * out, LL_Module * module, LL_MDRef rmdref, int omit_metadata_type)
Write out an LL_MDRef from module.
...
Parameters
out output file
module the LLVM module
rmdref the metadata node to be written
omit_metadata_type if true then omit metadata keyword
This functions writes a metadata reference as it appears in metadata context, such as inside a metadata node definition, or following a !dbg tag.
Metadata references may use a different syntax when used as function arguments, depending on the LLVM version. That is not dealt with by this function.
Definition at line 1506 of file ll_write.cpp.
References assert, LL_Module::constants, LL_Module::constants_count, ERR_Fatal, interr(), LL_MDREF_kind, LL_MDREF_value, MDRef_Constant, MDRef_Node, MDRef_SmallInt1, MDRef_SmallInt32, MDRef_SmallInt64, MDRef_String, LL_Module::mdstrings, and LL_Module::mdstrings_count.
Referenced by write_mdnode_plain().
write_metadata_node()
static void write_metadata_node (FILE * out, LLVMModuleRef module, MDNodeRef node, unsigned mdi) static
Definition at line 2313 of file ll_write.cpp.
References DEBUG_ASSERT, LL_MDClass_MAX, LL_MDNode::mdclass, mdDispTable, and MDDispatch::method.
Referenced by ll_write_metadata().
write_prototypes()
static void write_prototypes (FILE * out, LLVMModuleRef module) static
Definition at line 243 of file ll_write.cpp.
References LL_Function_::arguments, LL_Function_::attributes, called, LL_Value::data, debug_calls, defined_in_module(), LL_Module::extern_func_refs, i, LL_Function_::name, LL_Function_::next, NULL, LL_Function_::num_args, LL_Module::num_refs, LL_Function_::return_type, LL_Type_::str, text_calls, and LL_Value::type_struct.
Referenced by ll_write_module().
Variable Documentation
called
LL_Function* called static
Definition at line 36 of file ll_write.cpp.
Referenced by add_prototype(), clear_prototypes(), ENTFTN(), finish(), Ftn_dsecnds(), Ftn_secnds(), and write_prototypes().
debug_calls
int debug_calls = 0 static
Definition at line 37 of file ll_write.cpp.
Referenced by write_prototypes().
mdDispTable
MDDispatch mdDispTable[LL_MDClass_MAX] static
Definition at line 1862 of file ll_write.cpp.
Referenced by write_metadata_node().
szatomic_opr
const char* szatomic_opr[10] static
Initial value:
= {"none", "xchg", "add", "sub", "and",
                                       "nand", "or",   "xor", "max", "min"}
Definition at line 346 of file ll_write.cpp.
Referenced by ll_get_atomic_opr().
szmemorder
const char* szmemorder[7] static
Initial value:
= {"undef",   "monotonic", "undef",  "acquire",
                                    "release", "acq_rel",   "seq_cst"}
Definition at line 372 of file ll_write.cpp.
Referenced by ll_get_atomic_memorder(), and render_store().
text_calls
int text_calls = 0 static
Definition at line 38 of file ll_write.cpp.
Referenced by ll_write_instruction(), and write_prototypes().
Tmpl_DIBasicType
const MDTemplate Tmpl_DIBasicType[] static
Initial value:
= {
  { "DIBasicType", TF, 10 },
  { "tag",                      DWTagField,      0 },
  { "unused",                   NodeField,       FlgHidden },
  { "unused",                   NodeField,       FlgHidden },
  { "name",                     StringField,     0 },
  { "line",                     UnsignedField,   0 },
  { "size",                     UnsignedField,   0 },
  { "align",                    UnsignedField,   0 },
  { "offset",                   UnsignedField,   0 },
  { "flags",                    UnsignedField,   0 },
  { "encoding",                 DWEncodingField, 0 }
}
Definition at line 1277 of file ll_write.cpp.
Referenced by emitDIBasicType().
Tmpl_DIBasicType_pre34
const MDTemplate Tmpl_DIBasicType_pre34[] static
Initial value:
= {
  { "DIBasicType", TF, 10 },
  { "tag",                      DWTagField,      0 },
  { "scope",                    NodeField,       0 },
  { "name",                     StringField,     0 },
  { "file",                     NodeField,       0 },
  { "line",                     UnsignedField,   0 },
  { "size",                     UnsignedField,   0 },
  { "align",                    UnsignedField,   0 },
  { "offset",                   UnsignedField,   0 },
  { "flags",                    UnsignedField,   0 },
  { "encoding",                 DWEncodingField, 0 }
}
Definition at line 1263 of file ll_write.cpp.
Referenced by emitDIBasicType().
Tmpl_DICommonBlock
const MDTemplate Tmpl_DICommonBlock[] static
Initial value:
= {
  { "DICommonBlock", TF, 3 },
  { "scope",                    NodeField,   0 },
  { "declaration",              NodeField,   0 },
  { "name",                     StringField, 0 }
}
Definition at line 1480 of file ll_write.cpp.
Referenced by emitDICommonBlock().
Tmpl_DICompileUnit
const MDTemplate Tmpl_DICompileUnit[] static
Initial value:
= {
  { "DICompileUnit", TF, 13 },
  { "tag",                      DWTagField,    FlgHidden },
  { "file",                     NodeField,     0 },
  { "language",                 DWLangField,   0 },
  { "producer",                 StringField,   0 },
  { "isOptimized",              BoolField,     0 },
  { "flags",                    StringField,   0 },
  { "runtimeVersion",           UnsignedField, 0 },
  { "enums",                    NodeField,     0 },
  { "retainedTypes",            NodeField,     0 },
  { "subprograms",              NodeField,     0 },
  { "globals",                  NodeField,     0 },
  { "imports",                  NodeField,     0 },
  { "splitDebugFilename",       StringField,   0 }
}
Definition at line 907 of file ll_write.cpp.
Referenced by emitDICompileUnit().
Tmpl_DICompileUnit_pre34
const MDTemplate Tmpl_DICompileUnit_pre34[] static
Initial value:
= {
  { "DICompileUnit", TF, 14 },
  { "tag",                      DWTagField,    FlgHidden },
  { "unused",                   NodeField,     FlgHidden },
  { "language",                 DWLangField,   0 },
  { "filename",                 StringField,   0 },
  { "directory",                StringField,   0 },
  { "producer",                 StringField,   0 },
  { "isMain",                   BoolField,     0 },
  { "isOptimized",              BoolField,     0 },
  { "flags",                    StringField,   0 },
  { "runtimeVersion",           UnsignedField, 0 },
  { "enums",                    NodeField,     0 },
  { "retainedTypes",            NodeField,     0 },
  { "subprograms",              NodeField,     0 },
  { "globals",                  NodeField,     0 }
}
Definition at line 943 of file ll_write.cpp.
Referenced by emitDICompileUnit().
Tmpl_DICompileUnit_ver39
const MDTemplate Tmpl_DICompileUnit_ver39[] static
Initial value:
= {
  { "DICompileUnit", TF, 14 },
  { "tag",                      DWTagField,              FlgHidden },
  { "file",                     NodeField,               0 },
  { "language",                 DWLangField,             0 },
  { "producer",                 StringField,             0 },
  { "isOptimized",              BoolField,               0 },
  { "flags",                    StringField,             0 },
  { "runtimeVersion",           UnsignedField,           0 },
  { "enums",                    NodeField,               0 },
  { "retainedTypes",            NodeField,               0 },
  { "globals",                  NodeField,               0 },
  { "emissionKind",             DWEmissionField,         0 },
  { "imports",                  NodeField,               0 },
  { "splitDebugFilename",       StringField,             0 },
  { "nameTableKind",            DebugNameTableKindField, 0 }
}
Definition at line 925 of file ll_write.cpp.
Referenced by emitDICompileUnit().
Tmpl_DICompositeType
const MDTemplate Tmpl_DICompositeType[] static
Initial value:
= {
  { "DICompositeType", TF, 19 },
  { "tag",                      DWTagField,    0 },
  { "file",                     NodeField,     0 },
  { "scope",                    NodeField,     0 },
  { "name",                     StringField,   0 },
  { "line",                     UnsignedField, 0 },
  { "size",                     UnsignedField, 0 },
  { "align",                    UnsignedField, 0 },
  { "offset",                   UnsignedField, 0 },
  { "flags",                    UnsignedField, 0 },
  { "baseType",                 NodeField,     0 },
  { "elements",                 NodeField,     0 },
  { "runtimeLang",              DWLangField,   0 },
  { "vtableHolder",             NodeField,     0 },
  { "templateParams",           NodeField,     0 },
  { "identifier",               StringField,   0 },
  { "dataLocation",             NodeField,     0 },
  { "associated",               NodeField,     0 },
  { "allocated",                NodeField,     0 },
  { "rank",                     NodeField,     0 }
}
Definition at line 1376 of file ll_write.cpp.
Referenced by emitDICompositeType().
Tmpl_DICompositeType_pre34
const MDTemplate Tmpl_DICompositeType_pre34[] static
Initial value:
= {
  { "DICompositeType", TF, 13 },
  { "tag",                      DWTagField,    0 },
  { "scope",                    NodeField,     0 },
  { "name",                     StringField,   0 },
  { "file",                     NodeField,     0 },
  { "line",                     UnsignedField, 0 },
  { "size",                     UnsignedField, 0 },
  { "align",                    UnsignedField, 0 },
  { "offset",                   UnsignedField, 0 },
  { "flags",                    UnsignedField, 0 },
  { "baseType",                 NodeField,     0 },
  { "elements",                 NodeField,     0 },
  { "runtimeLang",              DWLangField,   0 },
  { "unused",                   NodeField,     FlgHidden }
}
Definition at line 1359 of file ll_write.cpp.
Referenced by emitDICompositeType().
Tmpl_DIDerivedType
const MDTemplate Tmpl_DIDerivedType[] static
Initial value:
= {
  { "DIDerivedType", TF, 10 },
  { "tag",                      DWTagField,    0 },
  { "file",                     NodeField,     0 },
  { "scope",                    NodeField,     0 },
  { "name",                     StringField,   0 },
  { "line",                     UnsignedField, 0 },
  { "size",                     UnsignedField, 0 },
  { "align",                    UnsignedField, 0 },
  { "offset",                   UnsignedField, 0 },
  { "flags",                    UnsignedField, 0 },
  { "baseType",                 NodeField,     0 }
}
Definition at line 1345 of file ll_write.cpp.
Referenced by emitDIDerivedType().
Tmpl_DIDerivedType_pre34
const MDTemplate Tmpl_DIDerivedType_pre34[] static
Initial value:
= {
  { "DIDerivedType", TF, 10 },
  { "tag",                      DWTagField,    0 },
  { "scope",                    NodeField,     0 },
  { "name",                     StringField,   0 },
  { "file",                     NodeField,     0 },
  { "line",                     UnsignedField, 0 },
  { "size",                     UnsignedField, 0 },
  { "align",                    UnsignedField, 0 },
  { "offset",                   UnsignedField, 0 },
  { "flags",                    UnsignedField, 0 },
  { "baseType",                 NodeField,     0 }
}
Definition at line 1331 of file ll_write.cpp.
Referenced by emitDIDerivedType().
Tmpl_DIEnumerator
const MDTemplate Tmpl_DIEnumerator[] static
Initial value:
= {
  { "DIEnumerator", TF, 3 },
  { "tag",                      DWTagField,  FlgHidden },
  { "name",                     StringField, 0 },
  { "value",                    SignedField, FlgMandatory }
}
Definition at line 1452 of file ll_write.cpp.
Referenced by emitDIEnumerator().
Tmpl_DIExpression
const MDTemplate Tmpl_DIExpression[] static
Initial value:
= {
  { "DIExpression", TF, 0 }
}
Definition at line 1178 of file ll_write.cpp.
Referenced by emitDIExpression().
Tmpl_DIFile_pair
const MDTemplate Tmpl_DIFile_pair[] static
Initial value:
= {
  { "DIFile", TF, 2 },
  { "filename",                 StringField,   0 },
  { "directory",                StringField,   0 }
}
Definition at line 885 of file ll_write.cpp.
Referenced by emitDIFile().
Tmpl_DIFile_pre34
const MDTemplate Tmpl_DIFile_pre34[] static
Initial value:
= {
  { "DIFile", TF, 4 },
  { "tag",                      DWTagField,  0 },
  { "filename",                 StringField, 0 },
  { "directory",                StringField, 0 },
  { "context",                  NodeField,   0 }
}
Definition at line 899 of file ll_write.cpp.
Referenced by emitDIFile().
Tmpl_DIFile_tagged
const MDTemplate Tmpl_DIFile_tagged[] static
Initial value:
= {
  { "DIFile", TF, 2 },
  { "tag",                      DWTagField, 0 },
  { "pair",                     NodeField,  0 }
}
Definition at line 892 of file ll_write.cpp.
Referenced by emitDIFile().
Tmpl_DIFortranArrayType
const MDTemplate Tmpl_DIFortranArrayType[] static
Initial value:
= {
  { "DIFortranArrayType", TF, 7 },
  { "tag",                      DWTagField,    0 },
  { "scope",                    NodeField,     0 },
  { "line",                     UnsignedField, 0 },
  { "size",                     UnsignedField, 0 },
  { "align",                    UnsignedField, 0 },
  { "baseType",                 NodeField,     0 },
  { "elements",                 NodeField,     0 }
}
Definition at line 1399 of file ll_write.cpp.
Referenced by emitDIFortranArrayType().
Tmpl_DIFortranSubrange
const MDTemplate Tmpl_DIFortranSubrange[] static
Initial value:
= {
  { "DIFortranSubrange", TF, 7 },
  { "tag",                      DWTagField,  FlgHidden },
  { "constLowerBound",          SignedField, 0 },
  { "constUpperBound",          SignedField, FlgSkip1 },
  { "lowerBound",               NodeField,   0 },
  { "lowerBoundExpression",     NodeField,   0 },
  { "upperBound",               NodeField,   0 },
  { "upperBoundExpression",     NodeField,   0 }
}
Definition at line 1441 of file ll_write.cpp.
Referenced by emitDIFortranSubrange().
Tmpl_DIGenericSubrange
const MDTemplate Tmpl_DIGenericSubrange[] static
Initial value:
= {
  { "DIGenericSubrange", TF, 4 },
  { "tag",                      DWTagField,      FlgHidden },
  { "lowerBound",               SignedOrMDField, 0 },
  { "upperBound",               SignedOrMDField, FlgMandatory },
  { "stride",                   SignedOrMDField, FlgMandatory }
}
Definition at line 1426 of file ll_write.cpp.
Referenced by emitDIGenericSubRange().
Tmpl_DIGlobalVariable
const MDTemplate Tmpl_DIGlobalVariable[] static
Initial value:
= {
  { "DIGlobalVariable", TF, 14 },
  { "tag",                      DWTagField,    FlgHidden },
  { "unused",                   NodeField,     FlgHidden },
  { "scope",                    NodeField,     0 },
  { "name",                     StringField,   0 },
  { "displayName",              StringField,   FlgHidden },
  { "linkageName",              StringField,   0 },
  { "file",                     NodeField,     0 },
  { "line",                     UnsignedField, 0 },
  { "type",                     NodeField,     0 },
  { "isLocal",                  BoolField,     0 },
  { "isDefinition",             BoolField,     0 },
  { "variable",                 ValueField,    0 },
  { "flags",                    UnsignedField, 0 },
  { "addrspace",                UnsignedField, FlgOptional }
}
Definition at line 1221 of file ll_write.cpp.
Referenced by emitDIGlobalVariable().
Tmpl_DIGlobalVariable4
const MDTemplate Tmpl_DIGlobalVariable4[] static
Initial value:
= {
  { "DIGlobalVariable", TF, 13 },
  { "tag",                      DWTagField,    FlgHidden },
  { "unused",                   NodeField,     FlgHidden },
  { "scope",                    NodeField,     0 },
  { "name",                     StringField,   0 },
  { "displayName",              StringField,   FlgHidden },
  { "linkageName",              StringField,   0 },
  { "file",                     NodeField,     0 },
  { "line",                     UnsignedField, 0 },
  { "type",                     NodeField,     0 },
  { "isLocal",                  BoolField,     0 },
  { "isDefinition",             BoolField,     0 },
  { "flags",                    UnsignedField, 0 },
  { "addrspace",                UnsignedField, FlgOptional }
}
Definition at line 1240 of file ll_write.cpp.
Referenced by emitDIGlobalVariable().
Tmpl_DIGlobalVariableExpression
const MDTemplate Tmpl_DIGlobalVariableExpression[] static
Initial value:
= {
  { "DIGlobalVariableExpression", TF, 2 },
  { "var",                      NodeField, 0 },
  { "expr",                     NodeField, 0 }
}
Definition at line 1257 of file ll_write.cpp.
Referenced by emitDIGlobalVariableExpression().
Tmpl_DIImportedEntity
const MDTemplate Tmpl_DIImportedEntity[] static
Initial value:
= {
  { "DIImportedEntity", TF, 7 },
  { "tag",                      DWTagField,    0 },
  { "entity",                   NodeField,     0 },
  { "scope",                    NodeField,     0 },
  { "file",                     NodeField,     0 },
  { "line",                     UnsignedField, 0 },
  { "name",                     StringField,   0 },
  { "elements",                 NodeField,     0 }
}
Definition at line 1469 of file ll_write.cpp.
Referenced by emitDIImportedEntity().
Tmpl_DIImportedEntity_pre11
const MDTemplate Tmpl_DIImportedEntity_pre11[] static
Initial value:
= {
  { "DIImportedEntity", TF, 6 },
  { "tag",                      DWTagField,    0 },
  { "entity",                   NodeField,     0 },
  { "scope",                    NodeField,     0 },
  { "file",                     NodeField,     0 },
  { "line",                     UnsignedField, 0 },
  { "name",                     StringField,   0 }
}
Definition at line 1459 of file ll_write.cpp.
Referenced by emitDIImportedEntity().
Tmpl_DILexicalBlock
const MDTemplate Tmpl_DILexicalBlock[] static
Initial value:
= {
  { "DILexicalBlock", TF, 6 },
  { "tag",                      DWTagField,    FlgHidden },
  { "file",                     NodeField,     0 },
  { "scope",                    NodeField,     0 },
  { "line",                     UnsignedField, 0 },
  { "column",                   UnsignedField, 0 },
  { "discriminator",            UnsignedField, FlgHidden | FlgOptional }
}
Definition at line 1150 of file ll_write.cpp.
Referenced by emitDILexicalBlock().
Tmpl_DILexicalBlock_pre34
const MDTemplate Tmpl_DILexicalBlock_pre34[] static
Initial value:
= {
  { "DILexicalBlock", TF, 6 },
  { "tag",                      DWTagField,    FlgHidden },
  { "scope",                    NodeField,     0 },
  { "line",                     UnsignedField, 0 },
  { "column",                   UnsignedField, 0 },
  { "file",                     NodeField,     0 },
  { "discriminator",            UnsignedField, FlgOptional }
}
Definition at line 1160 of file ll_write.cpp.
Referenced by emitDILexicalBlock().
Tmpl_DILexicalBlockFile
const MDTemplate Tmpl_DILexicalBlockFile[] static
Initial value:
= {
  { "DILexicalBlock", TF, 4 },
  { "tag",                      DWTagField,    FlgHidden },
  { "file",                     NodeField,     0 },
  { "scope",                    NodeField,     0 },
  { "discriminator",            UnsignedField, 0 }
}
Definition at line 1170 of file ll_write.cpp.
Referenced by emitDILexicalBlockFile().
Tmpl_DILocalVariable_38
const MDTemplate Tmpl_DILocalVariable_38[] static
Initial value:
= {
  { "DILocalVariable", TF, 8 },
  { "scope",                    NodeField,     0 },
  { "name",                     StringField,   0 },
  { "arg",                      UnsignedField, 0 },
  { "file",                     NodeField,     0 },
  { "line",                     UnsignedField, 0 },
  { "type",                     NodeField,     0 },
  { "flags",                    UnsignedField, 0 },
  { "inlinedAt",                UnsignedField, 0 }
}
Definition at line 1197 of file ll_write.cpp.
Referenced by emitDILocalVariable().
Tmpl_DILocalVariable_embedded_argnum
const MDTemplate Tmpl_DILocalVariable_embedded_argnum[] static
Initial value:
= {
  { "DILocalVariable", TF, 8 },
  { "tag",                      DWTagField,    0 },
  { "scope",                    NodeField,     0 },
  { "name",                     StringField,   0 },
  { "file",                     NodeField,     0 },
  { "line_and_arg",             UnsignedField, 0 },
  { "type",                     NodeField,     0 },
  { "flags",                    UnsignedField, 0 },
  { "inlinedAt",                UnsignedField, 0 }
}
Definition at line 1209 of file ll_write.cpp.
Referenced by emitDILocalVariable().
Tmpl_DILocation
const MDTemplate Tmpl_DILocation[] static
Initial value:
= {
  { "DILocation", TF, 4 },
  { "line",                     UnsignedField, 0 },
  { "column",                   UnsignedField, 0 },
  { "scope",                    NodeField,     FlgMandatory },
  { "inlinedAt",                NodeField,     0}
}
Definition at line 867 of file ll_write.cpp.
Referenced by emitDILocalVariable(), and emitDILocation().
Tmpl_DIModule
const MDTemplate Tmpl_DIModule[] static
Initial value:
= {
  { "DIModule", TF, 3 },
  { "tag",                      DWTagField,  FlgHidden },
  { "scope",                    NodeField,   0 },
  { "name",                     StringField, 0 }
}
Definition at line 988 of file ll_write.cpp.
Referenced by emitDIModule().
Tmpl_DIModule_11
const MDTemplate Tmpl_DIModule_11[] static
Initial value:
= {
  { "DIModule", TF, 5 },
  { "tag",                      DWTagField,    FlgHidden },
  { "scope",                    NodeField,     0 },
  { "name",                     StringField,   0 },
  { "file",                     NodeField,     0 },
  { "line",                     UnsignedField, 0 },
}
Definition at line 998 of file ll_write.cpp.
Referenced by emitDIModule().
Tmpl_DINamespace_5
const MDTemplate Tmpl_DINamespace_5[] static
Initial value:
= {
  { "DINamespace", TF, 5 },
  { "tag",                      DWTagField,    FlgHidden },
  { "file",                     NodeField,     FlgHidden },
  { "scope",                    NodeField,     0 },
  { "name",                     StringField,   0 },
  { "line",                     UnsignedField, FlgHidden }
}
Definition at line 979 of file ll_write.cpp.
Referenced by emitDINamespace().
Tmpl_DINamespace_post34
const MDTemplate Tmpl_DINamespace_post34[] static
Initial value:
= {
  { "DINamespace", TF, 5 },
  { "tag",                      DWTagField,    FlgHidden },
  { "file",                     NodeField,     0 },
  { "scope",                    NodeField,     0 },
  { "name",                     StringField,   0 },
  { "line",                     UnsignedField, 0 }
}
Definition at line 970 of file ll_write.cpp.
Referenced by emitDINamespace().
Tmpl_DINamespace_pre34
const MDTemplate Tmpl_DINamespace_pre34[] static
Initial value:
= {
  { "DINamespace", TF, 5 },
  { "tag",                      DWTagField,    0 },
  { "scope",                    NodeField,     0 },
  { "name",                     StringField,   0 },
  { "file",                     NodeField,     0 },
  { "line",                     UnsignedField, 0 }
}
Definition at line 961 of file ll_write.cpp.
Referenced by emitDINamespace().
Tmpl_DIStringType
const MDTemplate Tmpl_DIStringType[] static
Initial value:
= {
  { "DIStringType", TF, 7 },
  { "tag",                      DWTagField,    FlgHidden },
  { "name",                     StringField,   0 },
  { "size",                     UnsignedField, 0 },
  { "align",                    UnsignedField, 0 },
  { "encoding",                 UnsignedField, FlgHidden },
  { "stringLength",             NodeField,     0 },
  { "stringLengthExpression",   NodeField,     0 }
}
Definition at line 1301 of file ll_write.cpp.
Referenced by emitDIStringType().
Tmpl_DIStringType_old
const MDTemplate Tmpl_DIStringType_old[] static
Initial value:
= {
  { "DIBasicType", TF, 5 },
  { "tag",                      DWTagField,      0 },
  { "name",                     StringField,     0 },
  { "size",                     UnsignedField,   0 },
  { "align",                    UnsignedField,   0 },
  { "encoding",                 DWEncodingField, 0 }
}
Definition at line 1292 of file ll_write.cpp.
Referenced by emitDIBasicStringType().
Tmpl_DISubprogram
const MDTemplate Tmpl_DISubprogram[] static
Initial value:
= {
  { "DISubprogram", TF, 20 },
  { "tag",                      DWTagField,        FlgHidden },
  { "file",                     NodeField,         0 },
  { "scope",                    NodeField,         0 },
  { "name",                     StringField,       0 },
  { "displayName",              StringField,       FlgHidden },
  { "linkageName",              StringField,       0 },
  { "line",                     UnsignedField,     0 },
  { "type",                     NodeField,         0 },
  { "isLocal",                  BoolField,         0 },
  { "isDefinition",             BoolField,         0 },
  { "virtuality",               DWVirtualityField, 0 },
  { "virtualIndex",             UnsignedField,     0 },
  { "containingType",           NodeField,         0 },
  { "flags",                    UnsignedField,     0 },
  { "isOptimized",              BoolField,         0 },
  { "function",                 ValueField,        0 },
  { "templateParams",           NodeField,         0 },
  { "declaration",              NodeField,         0 },
  { "variables",                NodeField,         0 },
  { "scopeLine",                UnsignedField,     0 }
}
Definition at line 1007 of file ll_write.cpp.
Referenced by emitDISubprogram().
Tmpl_DISubprogram_13
const MDTemplate Tmpl_DISubprogram_13[] static
Initial value:
= {
  { "DISubprogram", TF, 19 },
  { "tag",                      DWTagField,        FlgHidden },
  { "file",                     NodeField,         0 },
  { "scope",                    NodeField,         0 },
  { "name",                     StringField,       0 },
  { "displayName",              StringField,       FlgHidden },
  { "linkageName",              StringField,       0 },
  { "line",                     UnsignedField,     0 },
  { "type",                     NodeField,         0 },
  { "virtuality",               DWVirtualityField, 0 },
  { "virtualIndex",             UnsignedField,     0 },
  { "containingType",           NodeField,         0 },
  { "flags",                    UnsignedField,     0 },
  { "spFlags",                  UnsignedField,     0 },
  { "function",                 ValueField,        FlgHidden },
  { "templateParams",           NodeField,         0 },
  { "declaration",              NodeField,         0 },
  { "unit",                     NodeField,         0 },
  { "retainedNodes",            NodeField,         0 },
  { "scopeLine",                UnsignedField,     0 }
}
Definition at line 1031 of file ll_write.cpp.
Referenced by emitDISubprogram().
Tmpl_DISubprogram_38
const MDTemplate Tmpl_DISubprogram_38[] static
Initial value:
= {
  { "DISubprogram", TF, 20 },
  { "tag",                      DWTagField,        FlgHidden },
  { "file",                     NodeField,         0 },
  { "scope",                    NodeField,         0 },
  { "name",                     StringField,       0 },
  { "displayName",              StringField,       FlgHidden },
  { "linkageName",              StringField,       0 },
  { "line",                     UnsignedField,     0 },
  { "type",                     NodeField,         0 },
  { "isLocal",                  BoolField,         0 },
  { "isDefinition",             BoolField,         0 },
  { "virtuality",               DWVirtualityField, 0 },
  { "virtualIndex",             UnsignedField,     0 },
  { "containingType",           NodeField,         0 },
  { "flags",                    UnsignedField,     0 },
  { "isOptimized",              BoolField,         0 },
  { "function",                 ValueField,        FlgHidden },
  { "templateParams",           NodeField,         0 },
  { "declaration",              NodeField,         0 },
  { "variables",                NodeField,         0 },
  { "scopeLine",                UnsignedField,     0 }
}
Definition at line 1100 of file ll_write.cpp.
Referenced by emitDISubprogram().
Tmpl_DISubprogram_39
const MDTemplate Tmpl_DISubprogram_39[] static
Initial value:
= {
  { "DISubprogram", TF, 21 },
  { "tag",                      DWTagField,        FlgHidden },
  { "file",                     NodeField,         0 },
  { "scope",                    NodeField,         0 },
  { "name",                     StringField,       0 },
  { "displayName",              StringField,       FlgHidden },
  { "linkageName",              StringField,       0 },
  { "line",                     UnsignedField,     0 },
  { "type",                     NodeField,         0 },
  { "isLocal",                  BoolField,         0 },
  { "isDefinition",             BoolField,         0 },
  { "virtuality",               DWVirtualityField, 0 },
  { "virtualIndex",             UnsignedField,     0 },
  { "containingType",           NodeField,         0 },
  { "flags",                    UnsignedField,     0 },
  { "isOptimized",              BoolField,         0 },
  { "function",                 ValueField,        FlgHidden },
  { "templateParams",           NodeField,         0 },
  { "declaration",              NodeField,         0 },
  { "unit",                     NodeField,         0 },
  { "variables",                NodeField,         0 },
  { "scopeLine",                UnsignedField,     0 }
}
"unit" was added in LLVM 3.9 for DISubprogram
Definition at line 1125 of file ll_write.cpp.
Referenced by emitDISubprogram().
Tmpl_DISubprogram_70
const MDTemplate Tmpl_DISubprogram_70[] static
Initial value:
= {
  { "DISubprogram", TF, 20 },
  { "tag",                      DWTagField,        FlgHidden },
  { "file",                     NodeField,         0 },
  { "scope",                    NodeField,         0 },
  { "name",                     StringField,       0 },
  { "displayName",              StringField,       FlgHidden },
  { "linkageName",              StringField,       0 },
  { "line",                     UnsignedField,     0 },
  { "type",                     NodeField,         0 },
  { "isLocal",                  BoolField,         0 },
  { "isDefinition",             BoolField,         0 },
  { "virtuality",               DWVirtualityField, 0 },
  { "virtualIndex",             UnsignedField,     0 },
  { "containingType",           NodeField,         0 },
  { "flags",                    UnsignedField,     0 },
  { "isOptimized",              BoolField,         0 },
  { "function",                 ValueField,        FlgHidden },
  { "templateParams",           NodeField,         0 },
  { "declaration",              NodeField,         0 },
  { "unit",                     NodeField,         0 },
  { "scopeLine",                UnsignedField,     0 }
}
Definition at line 1076 of file ll_write.cpp.
Referenced by emitDISubprogram().
Tmpl_DISubprogram_90
const MDTemplate Tmpl_DISubprogram_90[] static
Initial value:
= {
  { "DISubprogram", TF, 18 },
  { "tag",                      DWTagField,        FlgHidden },
  { "file",                     NodeField,         0 },
  { "scope",                    NodeField,         0 },
  { "name",                     StringField,       0 },
  { "displayName",              StringField,       FlgHidden },
  { "linkageName",              StringField,       0 },
  { "line",                     UnsignedField,     0 },
  { "type",                     NodeField,         0 },
  { "virtuality",               DWVirtualityField, 0 },
  { "virtualIndex",             UnsignedField,     0 },
  { "containingType",           NodeField,         0 },
  { "flags",                    UnsignedField,     0 },
  { "spFlags",                  UnsignedField,     0 },
  { "function",                 ValueField,        FlgHidden },
  { "templateParams",           NodeField,         0 },
  { "declaration",              NodeField,         0 },
  { "unit",                     NodeField,         0 },
  { "scopeLine",                UnsignedField,     0 }
}
Definition at line 1054 of file ll_write.cpp.
Referenced by emitDISubprogram().
Tmpl_DISubrange
const MDTemplate Tmpl_DISubrange[] static
Initial value:
= {
  { "DISubrange", TF, 5 },
  { "tag",                      DWTagField,      FlgHidden },
  { "count",                    SignedOrMDField, 0 },
  { "lowerBound",               SignedOrMDField, 0 },
  { "upperBound",               SignedOrMDField, 0 },
  { "stride",                   SignedOrMDField, 0 }
}
Definition at line 1417 of file ll_write.cpp.
Referenced by emitDISubRange().
Tmpl_DISubrange_pre11
const MDTemplate Tmpl_DISubrange_pre11[] static
Initial value:
= {
  { "DISubrange", TF, 3 },
  { "tag",                      DWTagField,  FlgHidden },
  { "lowerBound",               SignedField, 0 },
  { "count",                    SignedField, FlgMandatory }
}
Definition at line 1410 of file ll_write.cpp.
Referenced by emitDISubRange().
Tmpl_DISubrange_pre37
const MDTemplate Tmpl_DISubrange_pre37[] static
Initial value:
= {
  { "DISubrange", TF, 3 },
  { "tag",                      DWTagField,  FlgHidden },
  { "lowerBound",               SignedField, 0 },
  { "upperBound",               SignedField, 0 }
}
Definition at line 1434 of file ll_write.cpp.
Referenced by emitDISubRange().
Tmpl_DISubroutineType
const MDTemplate Tmpl_DISubroutineType[] static
Initial value:
= {
  { "DISubroutineType", TF, 15 },
  { "tag",                      DWTagField,    FlgHidden },
  { "unused",                   UnsignedField, 0 },
  { "unused",                   NodeField,     0 },
  { "name",                     StringField,   0 },
  { "unused",                   UnsignedField, 0 },
  { "unused",                   UnsignedField, 0 },
  { "unused",                   UnsignedField, 0 },
  { "unused",                   UnsignedField, 0 },
  { "unused",                   UnsignedField, 0 },
  { "unused",                   NodeField,     0 },
  { "types",                    NodeField,     0 },
  { "unused",                   UnsignedField, 0 },
  { "unused",                   NodeField,     0 },
  { "unused",                   NodeField,     0 },
  { "cc",                       UnsignedField, 0 }
}
Definition at line 1312 of file ll_write.cpp.
Referenced by emitDISubroutineType().
Tmpl_MDLocation
const MDTemplate Tmpl_MDLocation[] static
Initial value:
= {
  { "MDLocation", TF, 4 },
  { "line",                     UnsignedField, 0 },
  { "column",                   UnsignedField, 0 },
  { "scope",                    NodeField,     FlgMandatory },
  { "inlinedAt",                NodeField,     0 }
}
Definition at line 876 of file ll_write.cpp.
Referenced by emitDILocation().