flang: ll_write.h File Reference
ll_write.h File Reference
#include <stdio.h>
#include "ll_structure.h"
Functions
void ll_write_basicblock (FILE *out, LL_Function *function, LL_BasicBlock *block, LL_Module *module, int no_return)
...
void ll_write_function (FILE *out, LL_Function *function, LL_Module *module, bool no_return, const char *prefix)
...
void ll_write_global_objects (FILE *out, LLVMModuleRef module)
...
void ll_write_global_var_signature (FILE *out, LL_Value *variable)
...
void ll_write_instruction (FILE *out, struct LL_Instruction_ *inst, LL_Module *module, int no_return)
...
void ll_write_llvm_used (FILE *out, LLVMModuleRef module)
...
void ll_write_local_objects (FILE *out, LL_Function *function)
...
void ll_write_metadata (FILE *out, LLVMModuleRef module)
...
void ll_write_module (FILE *out, LL_Module *module, int no_return, const char *no_return_prefix)
...
void ll_write_module_header (FILE *out, LLVMModuleRef module)
...
void ll_write_object_dbg_references (FILE *out, LL_Module *m, LL_ObjToDbgList *ods)
...
void ll_write_user_structs (FILE *out, LLVMModuleRef module)
...
void write_mdref (FILE *out, LL_Module *module, LL_MDRef rmdref, int omit_metadata_type)
...
void ll_build_metadata_device (FILE *out, LLVMModuleRef module)
Build llvm metadata information specificly for llvm nvptx backend.
Function Documentation
ll_build_metadata_device()
void ll_build_metadata_device (FILE * out, LLVMModuleRef module)
Build llvm metadata information specificly for llvm nvptx backend.
Referenced by cg_llvm_end().
ll_write_basicblock()
void ll_write_basicblock (FILE * out, LL_Function * function, LL_BasicBlock * block, LL_Module * module, int no_return)
...
Definition at line 684 of file ll_write.cpp.
References LL_BasicBlock_::first, LL_Function_::first, ll_write_instruction(), ll_write_local_objects(), LL_BasicBlock_::name, and LL_Instruction_::next.
Referenced by ll_write_function().
ll_write_function()
void ll_write_function (FILE * out, LL_Function * function, LL_Module * module, bool no_return, const char * prefix)
...
Definition at line 786 of file ll_write.cpp.
References LL_Function_::arguments, LL_Function_::calling_convention, LL_Value::data, LL_Function_::first, LL_Value::flags, i, LL_Function_::linkage, ll_get_linkage_string(), ll_write_basicblock(), LL_Function_::name, LL_BasicBlock_::next, LL_Function_::num_args, prefix, LL_Function_::return_type, LL_Type_::str, LL_Value::type_struct, and VAL_IS_NOALIAS_PARAM.
Referenced by ll_write_module().
ll_write_global_objects()
void ll_write_global_objects (FILE * out, LLVMModuleRef module)
...
...
If this function is called more than once, only the new objects added since the last call will be written.
Definition at line 2426 of file ll_write.cpp.
References LL_Object::address, LL_Object::align_bytes, LL_Object::const_expr, LL_Value::data, ERR_Fatal, LL_Module::first_global, LL_Object::init_data, LL_Object::init_style, interr(), LL_Object::kind, LL_Module::last_global, LL_Object::linkage, LL_EXTERNAL_LINKAGE, ll_get_linkage_string(), ll_get_pointer_addrspace(), LLInit_ConstExpr, LLInit_Declaration, LLInit_Function, LLInit_Zero, LLObj_Alias, LLObj_Const, LLObj_Global, LL_Object::next, NULL, LL_Type_::str, LL_Object::type, and LL_Value::type_struct.
Referenced by ll_write_module().
ll_write_global_var_signature()
void ll_write_global_var_signature (FILE * out, LL_Value * variable)
...
Definition at line 2356 of file ll_write.cpp.
References LL_Value::data, LL_GLOBAL, and LL_Value::mvtype.
ll_write_instruction()
void ll_write_instruction (FILE * out, struct LL_Instruction_ * inst, LL_Module * module, int no_return)
...
Definition at line 396 of file ll_write.cpp.
References add_prototype(), LL_Instruction_::comment, LL_Value::data, LL_Type_::data_type, LL_Instruction_::dbg_line_op, fflush(), LL_Instruction_::flags, get_op_name(), i, IN_MODULE_CALL, INST_CANCELED, INST_INBOUND, INST_INDIRECT_CALL, INST_VOLATILE, LL_Module::ir, LL_ADD, LL_ALLOCA, LL_AND, LL_ASHR, LL_ASM, LL_ATOMICRMW, LL_BITCAST, LL_BR, LL_CALL, LL_CMPXCHG, LL_EXTRACTELEM, LL_EXTRACTVALUE, LL_FADD, LL_FCMP, LL_FDIV, ll_feature_explicit_gep_load_type, LL_FMUL, LL_FNEG, LL_FPEXT, LL_FPTOSI, LL_FPTOUI, LL_FPTRUNC, LL_FSUB, LL_GEP, ll_get_atomic_memorder(), ll_get_atomic_opr(), LL_ICMP, LL_INSERTELEM, LL_INSERTVALUE, LL_INTTOPTR, LL_LOAD, LL_LSHR, LL_MDREF_IS_NULL, LL_MDREF_value, LL_MUL, LL_NONE, LL_OR, LL_PTRTOINT, LL_RET, LL_SDIV, LL_SELECT, LL_SEXT, LL_SHL, LL_SITOFP, LL_SREM, LL_STORE, LL_SUB, LL_SWITCH, LL_TEXTCALL, LL_TRUNC, LL_UBR, LL_UDIV, LL_UITOFP, LL_UNREACHABLE, LL_UREM, LL_VOID, LL_XOR, LL_ZEXT, LL_Instruction_::num_operands, LL_Instruction_::op, LL_Instruction_::operands, render_bitcast(), render_store(), SPACES, LL_Type_::str, LL_Type_::sub_types, text_calls, and LL_Value::type_struct.
Referenced by ll_write_basicblock().
ll_write_llvm_used()
void ll_write_llvm_used (FILE * out, LLVMModuleRef module)
...
...
Definition at line 2370 of file ll_write.cpp.
References LL_Value::data, i, LL_Module::llvm_used, LL_Module::num_llvm_used, LL_Type_::str, LL_Value::type_struct, and LL_Symbols_::values.
Referenced by ll_write_module().
ll_write_local_objects()
void ll_write_local_objects (FILE * out, LL_Function * function)
...
...
Unlike ll_write_global_objects(), this function only expects to be called once per function.
Definition at line 709 of file ll_write.cpp.
References LL_Object::address, LL_Object::align_bytes, assert, LL_Value::data, ERR_Fatal, LL_Function_::first_local, i, LL_Object::kind, ll_type_bytes(), LLObj_LocalBuffered, make_lltype_from_sptr(), name, LL_Object::next, SNAME, LL_Object::sptr, LL_Type_::str, LL_Object::type, and XBIT.
Referenced by ll_write_basicblock(), and schedule().
ll_write_metadata()
void ll_write_metadata (FILE * out, LLVMModuleRef module)
...
...
Write out all the so-called named metadata and then the regular metadata
Definition at line 2338 of file ll_write.cpp.
References get_metadata_name(), i, j, MD_llvm_module_flags, MD_NUM_NAMES, LL_Module::mdnodes, LL_Module::mdnodes_count, LL_Module::named_mdnodes, NextMDName, write_mdnode_plain(), and write_metadata_node().
Referenced by cg_llvm_end(), and ll_write_module().
ll_write_module()
void ll_write_module (FILE * out, LL_Module * module, int no_return, const char * no_return_prefix)
...
Definition at line 2495 of file ll_write.cpp.
References LL_Type_::addrspace, LL_Value::align_bytes, clear_prototypes(), LL_Value::data, LL_Type_::data_type, LL_Module::first, LL_Value::flags, i, LL_Value::linkage, LL_COMMON_LINKAGE, LL_CONSTANT, LL_DEVICE, LL_DOUBLE, LL_EXTERNAL_LINKAGE, LL_FLOAT, ll_get_linkage_string(), LL_GLOBAL, LL_I1, LL_I16, LL_I32, LL_I64, LL_I8, LL_INTERNAL_LINKAGE, LL_NO_LINKAGE, LL_PTR, LL_WEAK_LINKAGE, ll_write_function(), ll_write_global_objects(), ll_write_llvm_used(), ll_write_metadata(), ll_write_module_header(), ll_write_user_structs(), LL_Module::module_vars, LL_Value::mvtype, LL_Function_::next, LL_Module::num_module_vars, LL_Value::storage, LL_Type_::str, LL_Type_::sub_types, LL_Value::type_struct, VAL_IS_TEXTURE, LL_Symbols_::values, and write_prototypes().
ll_write_module_header()
void ll_write_module_header (FILE * out, LLVMModuleRef module)
...
...
The header is: Module ID, target triple, and datalayout
Definition at line 65 of file ll_write.cpp.
References LL_Module::datalayout_string, LL_Module::module_name, and LL_Module::target_triple.
Referenced by init_gpu_output_file(), init_output_file(), and ll_write_module().
ll_write_object_dbg_references()
void ll_write_object_dbg_references (FILE * out, LL_Module * m, LL_ObjToDbgList * ods)
...
...
Parameters
ods the object to !dbg list
In LLVM 4.0, we can generate a list of comma separated !dbg metadata to link the object to a number of debug metadata descriptions.
Definition at line 671 of file ll_write.cpp.
References i, ll_feature_from_global_to_md, LL_MDREF_value, llObjtodbgAtEnd(), llObjtodbgFirst(), llObjtodbgFree(), llObjtodbgGet(), llObjtodbgNext(), and m.
Referenced by write_bss(), and write_statics().
ll_write_user_structs()
void ll_write_user_structs (FILE * out, LLVMModuleRef module)
...
...
If this function is called more than once, only the new types added since the last call are written.
Definition at line 82 of file ll_write.cpp.
References i, j, LL_TYPE_IS_PACKED_STRUCT, type, LL_Module::user_structs, val, LL_Symbols_::values, and LL_Module::written_user_structs.
Referenced by ll_write_module().
write_mdref()
void write_mdref (FILE * out, LL_Module * module, LL_MDRef rmdref, int omit_metadata_type)
...
...
Parameters
out output file
module the LLVM module
rmdref the metadata node to be written
omit_metadata_type if true then omit metadata keyword
This functions writes a metadata reference as it appears in metadata context, such as inside a metadata node definition, or following a !dbg tag.
Metadata references may use a different syntax when used as function arguments, depending on the LLVM version. That is not dealt with by this function.
Definition at line 1506 of file ll_write.cpp.
References assert, LL_Module::constants, LL_Module::constants_count, ERR_Fatal, interr(), LL_MDREF_kind, LL_MDREF_value, MDRef_Constant, MDRef_Node, MDRef_SmallInt1, MDRef_SmallInt32, MDRef_SmallInt64, MDRef_String, LL_Module::mdstrings, and LL_Module::mdstrings_count.
Referenced by write_mdnode_plain().