flang: ll_builder.h File Reference
ll_builder.h File Reference
Convenience functions for constructing LLVM IR.
#include "ll_structure.h"
#include "llutil.h"
Macros
#define LL_MD_IS_NULL(MD) (!(MD))
Typedefs
typedef struct LLMD_Builder_ * LLMD_Builder
Functions
LLMD_Builder llmd_init (LL_Module *module)
...
void llmd_add_null (LLMD_Builder mdb)
...
void llmd_add_i1 (LLMD_Builder mdb, int value)
...
void llmd_add_i32 (LLMD_Builder mdb, int value)
...
void llmd_add_i64 (LLMD_Builder mdb, long long value)
...
void llmd_add_i64_lsb_msb (LLMD_Builder mdb, unsigned lsb, unsigned msb)
...
void llmd_add_INT64 (LLMD_Builder mdb, DBLINT64 value)
...
void llmd_add_string (LLMD_Builder mdb, const char *value)
...
void llmd_add_md (LLMD_Builder mdb, LL_MDRef mdnode)
...
void llmd_add_value (LLMD_Builder mdb, LL_Value *value)
...
void llmd_reverse (LLMD_Builder mdb)
...
unsigned llmd_get_nelems (LLMD_Builder mdb)
...
void llmd_set_distinct (LLMD_Builder mdb)
...
void llmd_set_class (LLMD_Builder mdb, enum LL_MDClass mdclass)
...
LL_MDRef llmd_finish (LLMD_Builder mdb)
...
LL_MDRef ll_finish_variable (LLMD_Builder mdb, LL_MDRef fwd)
...
Detailed Description
Convenience functions for constructing LLVM IR.
Definition in file ll_builder.h.
Macro Definition Documentation
LL_MD_IS_NULL
#define LL_MD_IS_NULL (MD) (!(MD))
Definition at line 31 of file ll_builder.h.
Typedef Documentation
LLMD_Builder
typedef struct LLMD_Builder_* LLMD_Builder
Definition at line 29 of file ll_builder.h.
Function Documentation
ll_finish_variable()
LL_MDRef ll_finish_variable (LLMD_Builder mdb, LL_MDRef fwd)
...
Definition at line 149 of file ll_builder.cpp.
References LLMD_Builder_::elems, fwd, hashmap_replace(), LLMD_Builder_::init_elems, INT2HKEY, LLMD_Builder_::is_distinct, ll_create_distinct_md_node(), ll_get_md_node(), LL_MDREF_IS_NULL, LL_MDREF_value, ll_set_md_node(), LLMD_Builder_::mdclass, LL_Module::mdnodes, LL_Module::mdnodes_count, LL_Module::mdnodes_map, LLMD_Builder_::module, LLMD_Builder_::nelems, and slot.
Referenced by lldbg_create_global_variable_mdnode(), lldbg_create_local_variable_mdnode(), and lldbg_create_member_mdnode().
llmd_add_i1()
void llmd_add_i1 (LLMD_Builder mdb, int value)
...
Definition at line 68 of file ll_builder.cpp.
References ll_get_md_i1(), llmd_add_md(), and value().
Referenced by lldbg_create_compile_unit_mdnode(), and lldbg_create_subprogram_mdnode().
llmd_add_i32()
void llmd_add_i32 (LLMD_Builder mdb, int value)
...
Definition at line 74 of file ll_builder.cpp.
References ll_get_md_i32(), llmd_add_md(), LLMD_Builder_::module, and value().
Referenced by add_linker_directives(), lldbg_create_aggregate_type_mdnode(), lldbg_create_array_type_mdnode(), lldbg_create_assumed_len_string_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_block_mdnode(), lldbg_create_compile_unit_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_file_mdnode(), lldbg_create_ftn_array_type_mdnode(), lldbg_create_ftn_subrange_mdnode(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_create_generic_subrange_mdnode(), lldbg_create_global_variable_mdnode(), lldbg_create_imported_entity(), lldbg_create_local_variable_mdnode(), lldbg_create_location_mdnode(), lldbg_create_member_mdnode(), lldbg_create_module_flag_mdnode(), lldbg_create_module_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_create_string_type_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_create_subrange_mdnode(), lldbg_create_subrange_mdnode_pre11(), lldbg_create_subroutine_type_mdnode(), lldbg_create_unspecified_mdnode(), lldbg_create_vector_type_mdnode(), and lldbg_emit_expression_mdnode().
llmd_add_i64()
void llmd_add_i64 (LLMD_Builder mdb, long long value)
...
Definition at line 80 of file ll_builder.cpp.
References ll_get_md_i64(), llmd_add_md(), LLMD_Builder_::module, and value().
Referenced by lldbg_create_assumed_len_string_type_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_ftn_array_type_mdnode(), lldbg_create_ftn_subrange_mdnode(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_create_string_type_mdnode(), lldbg_create_subroutine_type_mdnode(), and llmd_add_i64_lsb_msb().
llmd_add_i64_lsb_msb()
void llmd_add_i64_lsb_msb (LLMD_Builder mdb, unsigned lsb, unsigned msb)
...
Definition at line 86 of file ll_builder.cpp.
References llmd_add_i64(), and value().
Referenced by llmd_add_INT64().
llmd_add_INT64()
void llmd_add_INT64 (LLMD_Builder mdb, DBLINT64 value)
...
Definition at line 95 of file ll_builder.cpp.
References llmd_add_i64_lsb_msb(), and value().
Referenced by lldbg_create_aggregate_type_mdnode(), lldbg_create_array_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_ftn_array_type_mdnode(), lldbg_create_member_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_create_string_type_mdnode(), lldbg_create_subrange_mdnode_pre11(), and lldbg_create_vector_type_mdnode().
llmd_add_md()
void llmd_add_md (LLMD_Builder mdb, LL_MDRef value)
...
Definition at line 54 of file ll_builder.cpp.
References LLMD_Builder_::capacity, LLMD_Builder_::elems, grow(), and LLMD_Builder_::nelems.
Referenced by add_linker_directives(), lldbg_create_aggregate_type_mdnode(), lldbg_create_array_type_mdnode(), lldbg_create_assumed_len_string_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_block_mdnode(), lldbg_create_common_block_mdnode(), lldbg_create_compile_unit_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_file_mdnode(), lldbg_create_ftn_array_type_mdnode(), lldbg_create_ftn_subrange_mdnode(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_create_generic_subrange_mdnode(), lldbg_create_global_variable_mdnode(), lldbg_create_imported_entity(), lldbg_create_local_variable_mdnode(), lldbg_create_location_mdnode(), lldbg_create_member_mdnode(), lldbg_create_module_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_create_subrange_mdnode(), lldbg_create_subroutine_type_mdnode(), lldbg_create_vector_type_mdnode(), lldbg_emit_parameter_list(), lldbg_emit_type(), llmd_add_i1(), llmd_add_i32(), llmd_add_i64(), llmd_add_null(), llmd_add_string(), and llmd_add_value().
llmd_add_null()
void llmd_add_null (LLMD_Builder mdb)
...
Definition at line 62 of file ll_builder.cpp.
References ll_get_md_null, and llmd_add_md().
Referenced by lldbg_create_aggregate_type_mdnode(), lldbg_create_array_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_ftn_subrange_mdnode(), lldbg_create_generic_subrange_mdnode(), lldbg_create_location_mdnode(), lldbg_create_module_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_create_subrange_mdnode(), lldbg_create_subroutine_type_mdnode(), and lldbg_create_vector_type_mdnode().
llmd_add_string()
void llmd_add_string (LLMD_Builder mdb, const char * value)
...
Definition at line 102 of file ll_builder.cpp.
References ll_get_md_string(), LL_MDREF_ctor, llmd_add_md(), LLMD_Builder_::module, and value().
Referenced by add_linker_directives(), lldbg_create_aggregate_type_mdnode(), lldbg_create_array_type_mdnode(), lldbg_create_assumed_len_string_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_common_block_mdnode(), lldbg_create_compile_unit_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_file_mdnode(), lldbg_create_global_variable_mdnode(), lldbg_create_imported_entity(), lldbg_create_local_variable_mdnode(), lldbg_create_member_mdnode(), lldbg_create_module_flag_mdnode(), lldbg_create_module_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_create_string_type_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_create_subroutine_type_mdnode(), and lldbg_create_vector_type_mdnode().
llmd_add_value()
void llmd_add_value (LLMD_Builder mdb, LL_Value * value)
...
Definition at line 109 of file ll_builder.cpp.
References ll_get_md_value(), llmd_add_md(), LLMD_Builder_::module, and value().
llmd_finish()
LL_MDRef llmd_finish (LLMD_Builder mdb)
...
Definition at line 184 of file ll_builder.cpp.
References LLMD_Builder_::elems, LLMD_Builder_::init_elems, LLMD_Builder_::is_distinct, ll_create_distinct_md_node(), ll_get_md_node(), LLMD_Builder_::mdclass, LLMD_Builder_::module, and LLMD_Builder_::nelems.
Referenced by add_linker_directives(), lldbg_create_aggregate_type_mdnode(), lldbg_create_array_type_mdnode(), lldbg_create_assumed_len_string_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_block_mdnode(), lldbg_create_common_block_mdnode(), lldbg_create_compile_unit_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_file_mdnode(), lldbg_create_ftn_array_type_mdnode(), lldbg_create_ftn_subrange_mdnode(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_create_generic_subrange_mdnode(), lldbg_create_global_variable_mdnode(), lldbg_create_imported_entity(), lldbg_create_local_variable_mdnode(), lldbg_create_location_mdnode(), lldbg_create_module_flag_mdnode(), lldbg_create_module_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_create_string_type_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_create_subrange_mdnode(), lldbg_create_subrange_mdnode_pre11(), lldbg_create_subroutine_type_mdnode(), lldbg_create_unspecified_mdnode(), lldbg_create_vector_type_mdnode(), lldbg_emit_empty_expression_mdnode(), lldbg_emit_expression_mdnode(), lldbg_emit_parameter_list(), and lldbg_emit_type().
llmd_get_nelems()
unsigned llmd_get_nelems (LLMD_Builder mdb)
...
Definition at line 131 of file ll_builder.cpp.
References LLMD_Builder_::nelems.
Referenced by lldbg_create_subprogram_mdnode().
llmd_init()
LLMD_Builder llmd_init (LL_Module * module)
...
Definition at line 27 of file ll_builder.cpp.
References LLMD_Builder_::capacity, LLMD_Builder_::elems, LLMD_Builder_::init_elems, and LLMD_Builder_::module.
Referenced by add_linker_directives(), lldbg_create_aggregate_type_mdnode(), lldbg_create_array_type_mdnode(), lldbg_create_assumed_len_string_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_block_mdnode(), lldbg_create_common_block_mdnode(), lldbg_create_compile_unit_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_file_mdnode(), lldbg_create_ftn_array_type_mdnode(), lldbg_create_ftn_subrange_mdnode(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_create_generic_subrange_mdnode(), lldbg_create_global_variable_mdnode(), lldbg_create_imported_entity(), lldbg_create_local_variable_mdnode(), lldbg_create_location_mdnode(), lldbg_create_member_mdnode(), lldbg_create_module_flag_mdnode(), lldbg_create_module_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_create_string_type_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_create_subrange_mdnode(), lldbg_create_subrange_mdnode_pre11(), lldbg_create_subroutine_type_mdnode(), lldbg_create_unspecified_mdnode(), lldbg_create_vector_type_mdnode(), lldbg_emit_empty_expression_mdnode(), lldbg_emit_expression_mdnode(), lldbg_emit_parameter_list(), and lldbg_emit_type().
llmd_reverse()
void llmd_reverse (LLMD_Builder mdb)
...
Definition at line 115 of file ll_builder.cpp.
References e, LLMD_Builder_::elems, i, j, LLMD_Builder_::nelems, and t.
llmd_set_class()
void llmd_set_class (LLMD_Builder mdb, enum LL_MDClass)
...
Definition at line 143 of file ll_builder.cpp.
References LLMD_Builder_::mdclass.
Referenced by lldbg_create_aggregate_type_mdnode(), lldbg_create_array_type_mdnode(), lldbg_create_assumed_len_string_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_block_mdnode(), lldbg_create_common_block_mdnode(), lldbg_create_compile_unit_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_file_mdnode(), lldbg_create_ftn_array_type_mdnode(), lldbg_create_ftn_subrange_mdnode(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_create_generic_subrange_mdnode(), lldbg_create_global_variable_mdnode(), lldbg_create_imported_entity(), lldbg_create_local_variable_mdnode(), lldbg_create_location_mdnode(), lldbg_create_member_mdnode(), lldbg_create_module_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_create_string_type_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_create_subrange_mdnode(), lldbg_create_subrange_mdnode_pre11(), lldbg_create_subroutine_type_mdnode(), lldbg_create_vector_type_mdnode(), lldbg_emit_empty_expression_mdnode(), and lldbg_emit_expression_mdnode().
llmd_set_distinct()
void llmd_set_distinct (LLMD_Builder mdb)
...
Definition at line 137 of file ll_builder.cpp.
References LLMD_Builder_::is_distinct.
Referenced by lldbg_create_common_block_mdnode(), lldbg_create_compile_unit_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_global_variable_mdnode(), lldbg_create_local_variable_mdnode(), and lldbg_create_subprogram_mdnode().