flang: ll_structure.h File Reference
ll_structure.h File Reference
LLVM bridge representation.
#include "gbldefs.h"
#include "global.h"
#include "flang/ADT/hash.h"
#include <stdio.h>
Classes
struct LL_IRFeatures_
LLVM IR Feature Vector.
struct LL_Type_
LL_Type represents an LLVM type.
struct LL_ObjToDbgList
Bucket list for object to !dbg metadata.
struct LL_ObjToDbgListIter
Iterator for iterating over a LL_ObjToDbgList.
struct LL_MDNode
struct LL_Value
struct LL_Object
Data structure representing an LLVM Object.
struct LL_Symbols_
struct LL_ManagedMallocs_
struct LL_Instruction_
struct LL_BasicBlock_
struct LL_Function_
struct LL_Module
LLVM Module proxy.
struct LL_FnProto_
Map from function (keyed by linker name) to ABI.
Macros
#define ll_feature_use_addrspacecast(f) ((f)->version >= LL_Version_3_4)
#define ll_feature_debug_info_global_aliases(f) ((f)->version >= LL_Version_3_4)
#define ll_feature_debug_info_pre34(f) ((f)->version < LL_Version_3_4)
#define ll_feature_emit_nvvmir_version(f) ((f)->version >= LL_Version_3_4)
#define ll_feature_versioned_dw_tag(f) ((f)->version <= LL_Version_3_5)
#define ll_feature_omit_metadata_type(f) ((f)->version >= LL_Version_3_6)
#define ll_feature_debug_info_mdlocation(f) ((f)->version >= LL_Version_3_6)
#define ll_feature_alias_flags_first(f) ((f)->version >= LL_Version_3_7)
#define ll_feature_emit_func_signature_for_call(f) ((f)->version >= LL_Version_3_7)
#define ll_feature_dbg_local_variable_embeds_argnum(f) ((f)->version < LL_Version_3_7)
#define ll_feature_explicit_gep_load_type(f) ((f)->version >= LL_Version_3_7)
#define ll_feature_metadata_args_struct(f) ((f)->version < LL_Version_3_7)
#define ll_feature_use_specialized_mdnodes(f) ((f)->version >= LL_Version_3_7)
#define ll_feature_debug_info_need_file_descriptions(f) ((f)->version >= LL_Version_3_7)
#define ll_feature_dbg_declare_needs_expression_md(f) ((f)->version >= LL_Version_3_7)
#define ll_feature_eh_personality_on_landingpad(f) ((f)->version < LL_Version_3_7)
#define ll_feature_debug_info_DI_syntax(f) ((f)->version >= LL_Version_3_7)
#define ll_feature_debug_info_subrange_needs_count(f) ((f)->version >= LL_Version_3_7)
#define ll_feature_debug_info_ver38(f) ((f)->version >= LL_Version_3_8)
#define ll_feature_debug_info_ver70(f) ((f)->version >= LL_Version_7_0)
#define ll_feature_debug_info_ver80(f) ((f)->version >= LL_Version_8_0)
#define ll_feature_debug_info_ver90(f) ((f)->version >= LL_Version_9_0)
#define ll_feature_debug_info_ver11(f) ((f)->version >= LL_Version_11_0)
#define ll_feature_debug_info_ver12(f) ((f)->version >= LL_Version_12_0)
#define ll_feature_debug_info_ver13(f) ((f)->version >= LL_Version_13_0)
#define ll_feature_three_argument_ctor_and_dtor(f) ((f)->version >= LL_Version_9_0)
#define ll_feature_use_distinct_metadata(f) ((f)->version >= LL_Version_3_8)
#define ll_feature_subprogram_not_in_cu(f) ((f)->version >= LL_Version_3_9)
#define ll_feature_from_global_to_md(f) ((f)->version >= LL_Version_4_0)
#define ll_feature_use_5_diexpression(f) ((f)->version >= LL_Version_5_0)
#define ll_feature_create_dimodule(f) ((f)->version >= LL_Version_5_0)
#define ll_feature_has_diextensions(f) (false)
#define ll_feature_no_file_in_namespace(f) ((f)->version >= LL_Version_5_0)
#define LL_TYPE_IS_VARARGS_FUNC 0x01
#define LL_TYPE_IS_PACKED_STRUCT 0x02
#define LL_TYPE_IS_NAMED_STRUCT 0x04
#define LL_MDREF_kind(md) ((md) & ((1 << 3) - 1))
#define LL_MDREF_value(md) ((md) >> 3)
#define LL_MDREF_ctor(k, v) (((v) << 3) | LL_MDREF_kind(k))
#define LL_MDREF_INITIALIZER(key, val) LL_MDREF_ctor(key, val)
#define LL_MDREF_IS_NULL(md) ((md) == 0)
#define LL_ObjToDbgBucketSize 13
#define VAL_IS_GLOBAL_OFFSET 0x1
#define VAL_IS_TEXTURE 0x2
#define VAL_IS_ARGSTRUCT_MEMBER 0x4
#define VAL_IS_PARAM 0x8
#define VAL_IS_BYVAL_PARAM 0x10
#define VAL_IS_NOALIAS_PARAM 0x20
#define VAL_IS_ASM_OUTPUT 0x40
#define VAL_IS_ASM_INPUT 0x80
#define VAL_IS_KERNEL_REF 0x1000
#define IN_MODULE_CALL 0x1
#define INST_CANCELED 0x2
#define INST_VOLATILE 0x4
#define INST_INBOUND 0x8
#define INST_INDIRECT_CALL 0x10
#define ll_get_md_null() LL_MDREF_INITIALIZER(MDRef_Node, 0)
Typedefs
typedef enum LL_Op LL_Op
typedef enum LL_ModuleVarType LL_ModuleVarType
typedef enum LL_BaseDataType LL_BaseDataType
typedef enum LL_AddressSpace LL_AddressSpace_t
typedef enum LL_AddressSpaceNVVM LL_AddressSpaceNVVM_t
typedef enum LL_CallConv LL_CallConv
Calling conventions. See the LLVM source file include/llvm/IR/CallingConv.h for the complete list.
typedef enum LL_IRVersion LL_IRVersion
Supported LLVM IR versions.
typedef enum LL_DWARFVersion LL_DWARFVersion
typedef struct LL_IRFeatures_ LL_IRFeatures
LLVM IR Feature Vector.
typedef struct LL_Module * LLVMModuleRef
typedef const struct LL_Type_ LL_Type
LL_Type represents an LLVM type.
typedef unsigned LL_MDRef
LLVM Metadata.
typedef struct LL_ObjToDbgList LL_ObjToDbgList
Bucket list for object to !dbg metadata.
typedef struct LL_ObjToDbgListIter LL_ObjToDbgListIter
Iterator for iterating over a LL_ObjToDbgList.
typedef enum LL_MDClass LL_MDClass
Classes for specialized metadata nodes.
typedef struct LL_MDNode LL_MDNode
typedef enum LL_DW_OP_t LL_DW_OP_t
typedef enum LL_MDName LL_MDName
Named module-level metadata.
typedef struct LL_Value LL_Value
typedef void(* LL_PrintInitializerFunction) (FILE *out, struct LL_Object *object)
Ptr to function used to print out the initializer for an LL_Object.
typedef struct LL_Object LL_Object
Data structure representing an LLVM Object.
typedef struct LL_Symbols_ LL_Symbols
typedef struct LL_ManagedMallocs_ LL_ManagedMallocs
typedef struct LL_Instruction_ LL_Instruction
typedef struct LL_BasicBlock_ LL_BasicBlock
typedef struct LL_Function_ LL_Function
typedef struct LL_DebugInfo LL_DebugInfo
typedef struct LL_Module LL_Module
LLVM Module proxy.
typedef struct LL_FnProto_ LL_FnProto
Map from function (keyed by linker name) to ABI.
typedef void(* LL_FnProto_Handler) (LL_FnProto *proto)
Iterate across all entries in the map and callback the handler.
Enumerations
enum LL_Op {
LL_ADD , LL_FADD , LL_SUB , LL_FSUB ,
LL_MUL , LL_FMUL , LL_UDIV , LL_SDIV ,
LL_UREM , LL_SREM , LL_FDIV , LL_OR ,
LL_XOR , LL_ASHR , LL_LSHR , LL_SHL ,
LL_AND , LL_STORE , LL_LOAD , LL_SEXT ,
LL_ZEXT , LL_TRUNC , LL_SITOFP , LL_UITOFP ,
LL_FPTOSI , LL_FPTOUI , LL_FPTRUNC , LL_FPEXT ,
LL_CALL , LL_RET , LL_ICMP , LL_FCMP ,
LL_BR , LL_UBR , LL_SELECT , LL_GEP ,
LL_BITCAST , LL_INTTOPTR , LL_PTRTOINT , LL_ALLOCA ,
LL_TEXTCALL , LL_UNREACHABLE , LL_SWITCH , LL_EXTRACTVALUE ,
LL_INSERTVALUE , LL_ATOMICRMW , LL_CMPXCHG , LL_ASM ,
LL_EXTRACTELEM , LL_INSERTELEM , LL_FNEG , LL_NONE
}
enum LL_ModuleVarType {
LL_DEFAULT = 0x1 , LL_GLOBAL = 0x1 << 1 , LL_SHARED = 0x1 << 2 , LL_LOCAL = 0x1 << 3 ,
LL_DEVICE = 0x1 << 4 , LL_CONSTANT = 0x1 << 5
}
enum LL_LinkageType {
LL_INTERNAL_LINKAGE = 1 , LL_COMMON_LINKAGE , LL_EXTERNAL_LINKAGE , LL_WEAK_LINKAGE ,
LL_NO_LINKAGE
}
enum LL_BaseDataType {
LL_NOTYPE = 0 , LL_LABEL , LL_METADATA , LL_VOID ,
LL_I1 , LL_I8 , LL_I16 , LL_I24 ,
LL_I32 , LL_I40 , LL_I48 , LL_I56 ,
LL_I64 , LL_I128 , LL_I256 , LL_HALF ,
LL_FLOAT , LL_DOUBLE , LL_FP128 , LL_X86_FP80 ,
LL_PPC_FP128 , LL_X86_MMX , LL_PTR , LL_ARRAY ,
LL_VECTOR , LL_STRUCT , LL_FUNCTION
}
enum LL_AddressSpace { LL_AddrSp_Default = 0 }
enum LL_AddressSpaceNVVM {
LL_AddrSp_NVVM_Generic = 0 , LL_AddrSp_NVVM_Global = 1 , LL_AddrSp_NVVM_InternalUse = 2 , LL_AddrSp_NVVM_Shared = 3 ,
LL_AddrSp_NVVM_Const = 4 , LL_AddrSp_NVVM_Local = 5
}
enum LL_CallConv {
LL_CallConv_C = 0 , LL_CallConv_Fast = 8 , LL_CallConv_Cold = 9 , LL_CallConv_X86_StdCall = 64 ,
LL_CallConv_X86_FastCall = 65 , LL_CallConv_X86_ThisCall = 70 , LL_CallConv_X86_VectorCall = 80 , LL_CallConv_APCS = 66 ,
LL_CallConv_AAPCS = 67 , LL_CallConv_AAPCS_VFP = 68 , LL_CallConv_PTX_Kernel = 71 , LL_CallConv_PTX_Device = 72 ,
LL_CallConv_SPIR_FUNC = 75 , LL_CallConv_SPIR_KERNEL = 76
}
Calling conventions. See the LLVM source file include/llvm/IR/CallingConv.h for the complete list.
enum LL_IRVersion {
LL_Version_3_1 = 31 , LL_Version_3_2 = 32 , LL_Version_3_4 = 34 , LL_Version_3_5 = 35 ,
LL_Version_3_6 = 36 , LL_Version_3_7 = 37 , LL_Version_3_8 = 38 , LL_Version_3_9 = 39 ,
LL_Version_4_0 = 40 , LL_Version_5_0 = 50 , LL_Version_6_0 = 60 , LL_Version_7_0 = 70 ,
LL_Version_8_0 = 80 , LL_Version_9_0 = 90 , LL_Version_11_0 = 110 , LL_Version_12_0 = 120 ,
LL_Version_13_0 = 130 , LL_Version_trunk = 1023
}
Supported LLVM IR versions.
enum LL_DWARFVersion { LL_DWARF_Version_2 , LL_DWARF_Version_3 , LL_DWARF_Version_4 , LL_DWARF_Version_5 }
enum LL_MDRef_Kind {
MDRef_Node , MDRef_String , MDRef_Constant , MDRef_SmallInt1 ,
MDRef_SmallInt32 , MDRef_SmallInt64
}
Metadata node types.
enum LL_MDClass {
LL_PlainMDNode , LL_DICompileUnit , LL_DIFile , LL_DIBasicType ,
LL_DISubroutineType , LL_DIDerivedType , LL_DICompositeType , LL_DIFortranArrayType ,
LL_DISubRange , LL_DIFortranSubrange , LL_DIEnumerator , LL_DITemplateTypeParameter ,
LL_DITemplateValueParameter , LL_DINamespace , LL_DIModule , LL_DIGlobalVariable ,
LL_DISubprogram , LL_DILexicalBlock , LL_DILexicalBlockFile , LL_DILocation ,
LL_DILocalVariable , LL_DIExpression , LL_DIObjCProperty , LL_DIImportedEntity ,
LL_DIGlobalVariableExpression , LL_DIBasicType_string , LL_DIStringType , LL_DICommonBlock ,
LL_DIGenericSubRange , LL_MDClass_MAX
}
Classes for specialized metadata nodes.
enum LL_DW_OP_t {
LL_DW_OP_NONE , LL_DW_OP_deref , LL_DW_OP_plus , LL_DW_OP_minus ,
LL_DW_OP_dup , LL_DW_OP_LLVM_fragment , LL_DW_OP_swap , LL_DW_OP_xderef ,
LL_DW_OP_stack_value , LL_DW_OP_constu , LL_DW_OP_plus_uconst , LL_DW_OP_int ,
LL_DW_OP_push_object_address , LL_DW_OP_mul , LL_DW_OP_over , LL_DW_OP_and ,
LL_DW_OP_MAX
}
enum LL_MDName {
MD_llvm_module_flags , MD_llvm_dbg_cu , MD_llvm_linker_options , MD_opencl_kernels ,
MD_nvvm_annotations , MD_nvvmir_version , MD_NUM_NAMES
}
Named module-level metadata.
enum LL_ObjectKind {
LLObj_Global , LLObj_Const , LLObj_Alias , LLObj_Local ,
LLObj_LocalBuffered
}
LL_Object represents an object stored in memory.
enum LL_ObjectInitStyle { LLInit_Declaration , LLInit_Zero , LLInit_ConstExpr , LLInit_Function }
Functions
LL_IRVersion get_llvm_version (void)
...
unsigned ll_feature_dwarf_version (const LL_IRFeatures *feature)
...
static INLINE bool ll_dw_op_ok (LL_DW_OP_t op)
LL_Value * ll_get_const_addrspacecast (LLVMModuleRef module, LL_Value *value, LL_Type *type)
...
void write_mdref (FILE *out, LLVMModuleRef module, LL_MDRef rmdref, int omit_metadata_type)
void ll_add_module_debug (hashmap_t map, const char *module_name, LL_MDRef mdnode)
Add module_name → mdnode to module debug map.
LL_MDRef ll_get_module_debug (hashmap_t map, const char *module_name)
static INLINE LL_ObjToDbgList * llObjtodbgCreate (void)
static INLINE void llObjtodbgFirst (LL_ObjToDbgList *ods, LL_ObjToDbgListIter *iter)
static INLINE bool llObjtodbgAtEnd (LL_ObjToDbgListIter *iter)
static INLINE void llObjtodbgNext (LL_ObjToDbgListIter *iter)
static INLINE LL_MDRef llObjtodbgGet (LL_ObjToDbgListIter *iter)
ISZ_T ll_type_bytes (LL_Type *type)
...
ISZ_T ll_type_bytes_unchecked (LL_Type *type)
...
bool ll_proto_has_defined_body (const char *fnname)
...
bool ll_proto_is_weak (const char *fnname)
...
const char * ll_create_local_name (LL_Function *function, const char *format,...)
...
const char * ll_get_calling_conv_str (enum LL_CallConv cc)
...
const char * ll_get_str_type_for_basic_type (enum LL_BaseDataType type)
...
const char * ll_proto_key (SPTR func_sptr)
...
int ll_get_pointer_addrspace (LL_Type *ptr)
...
int ll_type_is_fp (LL_Type *ty)
...
int ll_type_is_mem_seq (LL_Type *ty)
...
int ll_type_is_pointer_to_function (LL_Type *ty)
...
LL_FnProto * ll_proto_add (const char *fnname, struct LL_ABI_Info_ *abi)
...
LL_FnProto * ll_proto_add_sptr (SPTR func_sptr, struct LL_ABI_Info_ *abi)
...
LL_Function * ll_create_function_from_type (LL_Type *func_type, const char *name)
...
LL_MDRef ll_create_distinct_md_node (LLVMModuleRef module, enum LL_MDClass mdclass, const LL_MDRef *elems, unsigned nelems)
...
LL_MDRef ll_create_flexible_md_node (LLVMModuleRef module)
...
LL_MDRef ll_get_global_debug (LLVMModuleRef module, int sptr)
...
LL_MDRef ll_get_md_i1 (int value)
...
LL_MDRef ll_get_md_i32 (LLVMModuleRef module, int value)
...
LL_MDRef ll_get_md_i64 (LLVMModuleRef module, long long value)
...
LL_MDRef ll_get_md_node (LLVMModuleRef module, enum LL_MDClass mdclass, const LL_MDRef *elems, unsigned nelems)
...
LL_MDRef ll_get_md_rawstring (LLVMModuleRef module, const void *rawstr, size_t length)
...
LL_MDRef ll_get_md_string (LLVMModuleRef module, const char *str)
...
LL_MDRef ll_get_md_value (LLVMModuleRef module, LL_Value *value)
...
LL_Object * ll_create_global_alias (LL_Value *aliasee_ptr, const char *format,...)
...
LL_Object * ll_create_local_object (LL_Function *function, LL_Type *type, unsigned align_bytes, const char *format,...)
...
LL_Type * ll_create_anon_struct_type (LLVMModuleRef module, LL_Type *elements[], unsigned num_elements, bool is_packed, int addrspace)
...
LL_Type * ll_create_basic_type (LLVMModuleRef module, enum LL_BaseDataType type, int addrspace)
...
LL_Type * ll_create_function_type (LLVMModuleRef module, LL_Type *args[], unsigned num_args, int is_varargs)
...
LL_Type * ll_create_int_type_with_addrspace (LLVMModuleRef module, unsigned bits, int addrspace)
...
LL_Type * ll_create_int_type (LLVMModuleRef module, unsigned bits)
...
LL_Type * ll_create_named_struct_type (LLVMModuleRef module, int id, bool unique, const char *format,...)
...
LL_Type * ll_get_addrspace_type (LL_Type *type, int addrspace)
...
LL_Type * ll_get_array_type (LL_Type *type, BIGUINT64 num_elements, int addrspace)
...
LL_Type * ll_get_pointer_type (LL_Type *type)
...
LL_Type * ll_get_struct_type (LLVMModuleRef module, int struct_id, int required)
...
LL_Type * ll_get_vector_type (LL_Type *type, unsigned num_elements)
...
LL_Type * ll_type_array_elety (LL_Type *ty)
...
LL_Value * ll_create_array_value_from_type (LLVMModuleRef module, LL_Type *type, const char *data, int addrspace)
...
LL_Value ** ll_create_operands (LLVMModuleRef module, int num_operands)
...
LL_Value * ll_create_pointer_value_from_type (LLVMModuleRef module, LL_Type *type, const char *data, int addrspace)
...
LL_Value * ll_create_pointer_value (LLVMModuleRef module, enum LL_BaseDataType type, const char *data, int addrspace)
...
LL_Value * ll_create_value_from_type (LLVMModuleRef module, LL_Type *type, const char *data)
...
LL_Value * ll_get_const_bitcast (LLVMModuleRef module, LL_Value *value, LL_Type *type)
...
LL_Value * ll_get_const_gep (LLVMModuleRef module, LL_Value *ptr, unsigned num_idx,...)
...
LL_Value * ll_get_const_int (LLVMModuleRef module, unsigned bits, long long value)
...
LL_Value * ll_get_function_pointer (LLVMModuleRef module, LL_Function *function)
...
LL_Value * ll_get_global_pointer (const char *name, LL_Type *type)
...
LL_Value * ll_named_struct_type_exists (LLVMModuleRef module, int id, const char *format,...)
...
LLVMModuleRef ll_create_module (const char *module_name, const char *target_triple, enum LL_IRVersion llvm_ir_version)
...
struct LL_ABI_Info_ * ll_proto_get_abi (const char *fnname)
...
LL_Function * ll_create_function (LLVMModuleRef module, const char *name, LL_Type *return_type, int is_kernel, int launch_bounds, int launch_bounds_minctasm, const char *calling_convention, enum LL_LinkageType linkage)
...
unsigned ll_reserve_md_node (LLVMModuleRef module)
...
unsigned ll_type_int_bits (LL_Type *type)
...
void ll_add_global_debug (LLVMModuleRef module, int sptr, LL_MDRef mdnode)
...
void ll_append_llvm_used (LLVMModuleRef module, LL_Value *ptr)
...
void ll_create_sym (struct LL_Symbols_ *symbol_table, unsigned index, LL_Value *new_value)
...
void ll_destroy_function (LL_Function *function)
Deallocate all memory used by function.
void ll_destroy_mem (struct LL_ManagedMallocs_ *current)
...
void ll_destroy_module (LLVMModuleRef module)
...
void ll_extend_md_node (LLVMModuleRef module, LL_MDRef flexnode, LL_MDRef elem)
...
void ll_extend_named_md_node (LLVMModuleRef module, enum LL_MDName name, LL_MDRef elem)
...
void llObjtodbgFree (LL_ObjToDbgList *ods)
...
void add_linker_directives (LLVMModuleRef module)
void llObjtodbgPush (LL_ObjToDbgList *odl, LL_MDRef md)
...
void ll_proto_dump (void)
...
void ll_proto_init (void)
...
void ll_proto_iterate (LL_FnProto_Handler callback)
...
void ll_proto_set_abi (const char *fnname, struct LL_ABI_Info_ *abi)
...
void ll_proto_set_defined_body (const char *fnname, bool has_defined)
...
void ll_proto_set_intrinsic (const char *fnname, const char *intrinsic_decl_str)
...
void ll_proto_set_weak (const char *fnname, bool is_weak)
...
void ll_remove_struct_type (LLVMModuleRef module, int struct_id)
...
void ll_reset_module_types (LLVMModuleRef module)
...
void ll_set_function_argument (LL_Function *function, int index, LL_Value *argument)
...
void ll_set_function_num_arguments (LL_Function *function, int num_args)
...
void ll_set_md_node (LLVMModuleRef module, unsigned mdNum, LL_MDNode *node)
...
void ll_set_named_md_node (LLVMModuleRef module, enum LL_MDName name, const LL_MDRef *elems, unsigned nelems)
...
void ll_set_struct_body (LL_Type *ctype, LL_Type *const *elements, unsigned *const offsets, char *const pads, unsigned num_elements, int is_packed)
...
void ll_update_md_node (LLVMModuleRef module, LL_MDRef node_to_update, unsigned elem_index, LL_MDRef elem)
...
LL_Function * ll_create_device_function_from_type (LLVMModuleRef module, LL_Type *func_type, const char *name, int, int, const char *, enum LL_LinkageType)
Creates NVVM function.
Detailed Description
LLVM bridge representation.
Definition in file ll_structure.h.
Macro Definition Documentation
IN_MODULE_CALL
#define IN_MODULE_CALL 0x1
Definition at line 874 of file ll_structure.h.
INST_CANCELED
#define INST_CANCELED 0x2
Definition at line 875 of file ll_structure.h.
INST_INBOUND
#define INST_INBOUND 0x8
Definition at line 878 of file ll_structure.h.
INST_INDIRECT_CALL
#define INST_INDIRECT_CALL 0x10
Definition at line 879 of file ll_structure.h.
INST_VOLATILE
#define INST_VOLATILE 0x4
Definition at line 876 of file ll_structure.h.
ll_feature_alias_flags_first
#define ll_feature_alias_flags_first (f) ((f)->version >= LL_Version_3_7)
Definition at line 494 of file ll_structure.h.
ll_feature_create_dimodule
#define ll_feature_create_dimodule (f) ((f)->version >= LL_Version_5_0)
Definition at line 524 of file ll_structure.h.
ll_feature_dbg_declare_needs_expression_md
#define ll_feature_dbg_declare_needs_expression_md (f) ((f)->version >= LL_Version_3_7)
Definition at line 504 of file ll_structure.h.
ll_feature_dbg_local_variable_embeds_argnum
#define ll_feature_dbg_local_variable_embeds_argnum (f) ((f)->version < LL_Version_3_7)
Definition at line 497 of file ll_structure.h.
ll_feature_debug_info_DI_syntax
#define ll_feature_debug_info_DI_syntax (f) ((f)->version >= LL_Version_3_7)
Definition at line 508 of file ll_structure.h.
ll_feature_debug_info_global_aliases
#define ll_feature_debug_info_global_aliases (f) ((f)->version >= LL_Version_3_4)
Definition at line 488 of file ll_structure.h.
ll_feature_debug_info_mdlocation
#define ll_feature_debug_info_mdlocation (f) ((f)->version >= LL_Version_3_6)
Definition at line 493 of file ll_structure.h.
ll_feature_debug_info_need_file_descriptions
#define ll_feature_debug_info_need_file_descriptions (f) ((f)->version >= LL_Version_3_7)
Definition at line 502 of file ll_structure.h.
ll_feature_debug_info_pre34
#define ll_feature_debug_info_pre34 (f) ((f)->version < LL_Version_3_4)
Definition at line 489 of file ll_structure.h.
ll_feature_debug_info_subrange_needs_count
#define ll_feature_debug_info_subrange_needs_count (f) ((f)->version >= LL_Version_3_7)
Definition at line 509 of file ll_structure.h.
ll_feature_debug_info_ver11
#define ll_feature_debug_info_ver11 (f) ((f)->version >= LL_Version_11_0)
Definition at line 515 of file ll_structure.h.
ll_feature_debug_info_ver12
#define ll_feature_debug_info_ver12 (f) ((f)->version >= LL_Version_12_0)
Definition at line 516 of file ll_structure.h.
ll_feature_debug_info_ver13
#define ll_feature_debug_info_ver13 (f) ((f)->version >= LL_Version_13_0)
Definition at line 517 of file ll_structure.h.
ll_feature_debug_info_ver38
#define ll_feature_debug_info_ver38 (f) ((f)->version >= LL_Version_3_8)
Definition at line 511 of file ll_structure.h.
ll_feature_debug_info_ver70
#define ll_feature_debug_info_ver70 (f) ((f)->version >= LL_Version_7_0)
Definition at line 512 of file ll_structure.h.
ll_feature_debug_info_ver80
#define ll_feature_debug_info_ver80 (f) ((f)->version >= LL_Version_8_0)
Definition at line 513 of file ll_structure.h.
ll_feature_debug_info_ver90
#define ll_feature_debug_info_ver90 (f) ((f)->version >= LL_Version_9_0)
Definition at line 514 of file ll_structure.h.
ll_feature_eh_personality_on_landingpad
#define ll_feature_eh_personality_on_landingpad (f) ((f)->version < LL_Version_3_7)
Definition at line 506 of file ll_structure.h.
ll_feature_emit_func_signature_for_call
#define ll_feature_emit_func_signature_for_call (f) ((f)->version >= LL_Version_3_7)
Definition at line 495 of file ll_structure.h.
ll_feature_emit_nvvmir_version
#define ll_feature_emit_nvvmir_version (f) ((f)->version >= LL_Version_3_4)
Definition at line 490 of file ll_structure.h.
ll_feature_explicit_gep_load_type
#define ll_feature_explicit_gep_load_type (f) ((f)->version >= LL_Version_3_7)
Definition at line 499 of file ll_structure.h.
ll_feature_from_global_to_md
#define ll_feature_from_global_to_md (f) ((f)->version >= LL_Version_4_0)
Definition at line 522 of file ll_structure.h.
ll_feature_has_diextensions
#define ll_feature_has_diextensions (f) (false)
Definition at line 528 of file ll_structure.h.
ll_feature_metadata_args_struct
#define ll_feature_metadata_args_struct (f) ((f)->version < LL_Version_3_7)
Definition at line 500 of file ll_structure.h.
ll_feature_no_file_in_namespace
#define ll_feature_no_file_in_namespace (f) ((f)->version >= LL_Version_5_0)
Definition at line 530 of file ll_structure.h.
ll_feature_omit_metadata_type
#define ll_feature_omit_metadata_type (f) ((f)->version >= LL_Version_3_6)
Definition at line 492 of file ll_structure.h.
ll_feature_subprogram_not_in_cu
#define ll_feature_subprogram_not_in_cu (f) ((f)->version >= LL_Version_3_9)
Definition at line 521 of file ll_structure.h.
ll_feature_three_argument_ctor_and_dtor
#define ll_feature_three_argument_ctor_and_dtor (f) ((f)->version >= LL_Version_9_0)
Definition at line 518 of file ll_structure.h.
ll_feature_use_5_diexpression
#define ll_feature_use_5_diexpression (f) ((f)->version >= LL_Version_5_0)
Definition at line 523 of file ll_structure.h.
ll_feature_use_addrspacecast
#define ll_feature_use_addrspacecast (f) ((f)->version >= LL_Version_3_4)
Definition at line 487 of file ll_structure.h.
ll_feature_use_distinct_metadata
#define ll_feature_use_distinct_metadata (f) ((f)->version >= LL_Version_3_8)
Definition at line 520 of file ll_structure.h.
ll_feature_use_specialized_mdnodes
#define ll_feature_use_specialized_mdnodes (f) ((f)->version >= LL_Version_3_7)
Definition at line 501 of file ll_structure.h.
ll_feature_versioned_dw_tag
#define ll_feature_versioned_dw_tag (f) ((f)->version <= LL_Version_3_5)
Definition at line 491 of file ll_structure.h.
ll_get_md_null
#define ll_get_md_null () LL_MDREF_INITIALIZER(MDRef_Node, 0)
Definition at line 1029 of file ll_structure.h.
LL_MDREF_ctor
#define LL_MDREF_ctor (k, v) (((v) << 3) | LL_MDREF_kind(k))
Definition at line 606 of file ll_structure.h.
LL_MDREF_INITIALIZER
#define LL_MDREF_INITIALIZER (key, val) LL_MDREF_ctor(key, val)
Definition at line 607 of file ll_structure.h.
LL_MDREF_IS_NULL
#define LL_MDREF_IS_NULL (md) ((md) == 0)
Definition at line 608 of file ll_structure.h.
LL_MDREF_kind
#define LL_MDREF_kind (md) ((md) & ((1 << 3) - 1))
Definition at line 604 of file ll_structure.h.
LL_MDREF_value
#define LL_MDREF_value (md) ((md) >> 3)
Definition at line 605 of file ll_structure.h.
LL_ObjToDbgBucketSize
#define LL_ObjToDbgBucketSize 13
Definition at line 616 of file ll_structure.h.
LL_TYPE_IS_NAMED_STRUCT
#define LL_TYPE_IS_NAMED_STRUCT 0x04
Definition at line 576 of file ll_structure.h.
LL_TYPE_IS_PACKED_STRUCT
#define LL_TYPE_IS_PACKED_STRUCT 0x02
Definition at line 575 of file ll_structure.h.
LL_TYPE_IS_VARARGS_FUNC
#define LL_TYPE_IS_VARARGS_FUNC 0x01
Definition at line 574 of file ll_structure.h.
VAL_IS_ARGSTRUCT_MEMBER
#define VAL_IS_ARGSTRUCT_MEMBER 0x4
Definition at line 762 of file ll_structure.h.
VAL_IS_ASM_INPUT
#define VAL_IS_ASM_INPUT 0x80
Definition at line 771 of file ll_structure.h.
VAL_IS_ASM_OUTPUT
#define VAL_IS_ASM_OUTPUT 0x40
Definition at line 769 of file ll_structure.h.
VAL_IS_BYVAL_PARAM
#define VAL_IS_BYVAL_PARAM 0x10
Definition at line 766 of file ll_structure.h.
VAL_IS_GLOBAL_OFFSET
#define VAL_IS_GLOBAL_OFFSET 0x1
Definition at line 759 of file ll_structure.h.
VAL_IS_KERNEL_REF
#define VAL_IS_KERNEL_REF 0x1000
Definition at line 772 of file ll_structure.h.
VAL_IS_NOALIAS_PARAM
#define VAL_IS_NOALIAS_PARAM 0x20
Definition at line 767 of file ll_structure.h.
VAL_IS_PARAM
#define VAL_IS_PARAM 0x8
Definition at line 764 of file ll_structure.h.
VAL_IS_TEXTURE
#define VAL_IS_TEXTURE 0x2
Definition at line 760 of file ll_structure.h.
Typedef Documentation
LL_AddressSpace_t
typedef enum LL_AddressSpace LL_AddressSpace_t
LL_AddressSpaceNVVM_t
typedef enum LL_AddressSpaceNVVM LL_AddressSpaceNVVM_t
LL_BaseDataType
typedef enum LL_BaseDataType LL_BaseDataType
LL_BasicBlock
typedef struct LL_BasicBlock_ LL_BasicBlock
LL_CallConv
typedef enum LL_CallConv LL_CallConv
Calling conventions. See the LLVM source file include/llvm/IR/CallingConv.h for the complete list.
LL_DebugInfo
typedef struct LL_DebugInfo LL_DebugInfo
Definition at line 914 of file ll_structure.h.
LL_DW_OP_t
typedef enum LL_DW_OP_t LL_DW_OP_t
LL_DWARFVersion
typedef enum LL_DWARFVersion LL_DWARFVersion
LL_FnProto
typedef struct LL_FnProto_ LL_FnProto
Map from function (keyed by linker name) to ABI.
LL_FnProto_Handler
typedef void(* LL_FnProto_Handler) (LL_FnProto *proto)
Iterate across all entries in the map and callback the handler.
Definition at line 1006 of file ll_structure.h.
LL_Function
typedef struct LL_Function_ LL_Function
LL_Instruction
typedef struct LL_Instruction_ LL_Instruction
LL_IRFeatures
typedef struct LL_IRFeatures_ LL_IRFeatures
LLVM IR Feature Vector.
IR versions are translated to a feature vector that controls the shape of the generated IR. Code generation should always check the feature vector instead of comparing version numbers directly.
LL_IRVersion
typedef enum LL_IRVersion LL_IRVersion
Supported LLVM IR versions.
We can generate LLVM IR for multiple versions of LLVM. The numeric value of these version enumerators must match the x-bits set by the rcfiles.
The CPU target version is set by -x 249 from rcfiles/llvmrc.
LL_ManagedMallocs
typedef struct LL_ManagedMallocs_ LL_ManagedMallocs
LL_MDClass
typedef enum LL_MDClass LL_MDClass
Classes for specialized metadata nodes.
Plain metadata nodes are simply printed as !{ ... }, but starting with LLVM 3.6, metadata nodes can be specialized to contain a certain class of data, and they look like: !MDLocation(line: 2900, column:42, ...).
The metadata node classes should also be used when targeting LLVM < 3.6. They will be used to annotate the emitted plain metadata nodes in comments.
LL_MDName
typedef enum LL_MDName LL_MDName
Named module-level metadata.
We support a predefined set of well-known metadata names. When adding a new name here, also update get_metadata_name() in ll_write.c.
LL_MDNode
typedef struct LL_MDNode LL_MDNode
The internal representation of metadata nodes shouldn't be needed outside ll_structure.c and ll_write.c.
LL_MDRef
typedef unsigned LL_MDRef
LLVM Metadata.
Metadata nodes are constant manifestly typed tuples of references to other metadata nodes, metadata strings, or LLVM constants. The values that can be stored in a metadata node are represented as an array of LL_MDRef references.
Metadata nodes and strings are normally uniqued to save space, but it is possible to create distinct metadata nodes that don't participate in uniquing.
Metadata can appear as annotations on instructions, or as module-global named metadata.
LL_MDRef is a compact manifestly typed reference to the kind of data that can be stored in a metadata node. An LL_MDRef can refer to:
A numbered metadata node, or NULL.
A metadata string.
A constant LLVM value.
LL_MDRef is passed around by value. It should be treated as an opaque type. It cannot be transferred between different LL_Module instances.
Definition at line 602 of file ll_structure.h.
LL_Module
typedef struct LL_Module LL_Module
LLVM Module proxy.
LL_ModuleVarType
typedef enum LL_ModuleVarType LL_ModuleVarType
LL_Object
typedef struct LL_Object LL_Object
Data structure representing an LLVM Object.
Warning: we don't support linkage types yet, that is a drawback in some cases
LL_ObjToDbgList
typedef struct LL_ObjToDbgList LL_ObjToDbgList
Bucket list for object to !dbg metadata.
Sized to fit in 64 bytes to keep in a cache line (or 2)
LL_ObjToDbgListIter
typedef struct LL_ObjToDbgListIter LL_ObjToDbgListIter
Iterator for iterating over a LL_ObjToDbgList.
LL_Op
typedef enum LL_Op LL_Op
LL_PrintInitializerFunction
typedef void(* LL_PrintInitializerFunction) (FILE *out, struct LL_Object *object)
Ptr to function used to print out the initializer for an LL_Object.
The function should print both the type and the value of the initializer. It should not print a newline after the initializer.
Definition at line 809 of file ll_structure.h.
LL_Symbols
typedef struct LL_Symbols_ LL_Symbols
LL_Type
typedef const struct LL_Type_ LL_Type
LL_Type represents an LLVM type.
These structs are uniqued, so they should never be modified.
LL_Value
typedef struct LL_Value LL_Value
LLVMModuleRef
typedef struct LL_Module* LLVMModuleRef
Definition at line 539 of file ll_structure.h.
Enumeration Type Documentation
LL_AddressSpace
enum LL_AddressSpace
Enumerator
LL_AddrSp_Default
Definition at line 86 of file ll_structure.h.
LL_AddressSpaceNVVM
enum LL_AddressSpaceNVVM
Enumerator
LL_AddrSp_NVVM_Generic
LL_AddrSp_NVVM_Global
LL_AddrSp_NVVM_InternalUse
LL_AddrSp_NVVM_Shared
LL_AddrSp_NVVM_Const
LL_AddrSp_NVVM_Local
Definition at line 88 of file ll_structure.h.
LL_BaseDataType
enum LL_BaseDataType
Enumerator
LL_NOTYPE
LL_LABEL
LL_METADATA
LL_VOID
LL_I1
LL_I8
LL_I16
LL_I24
LL_I32
LL_I40
LL_I48
LL_I56
LL_I64
LL_I128
LL_I256
LL_HALF
IEEE half precision floating point.
LL_FLOAT
IEEE single precision floating point.
LL_DOUBLE
IEEE double precision floating point.
LL_FP128
IEEE quad precision floating point.
LL_X86_FP80
Intel x87 80-bit floating point.
LL_PPC_FP128
PowerPC style double-double.
LL_X86_MMX
x86 representation of a value held in MMX register.
LL_PTR
LL_ARRAY
LL_VECTOR
LL_STRUCT
LL_FUNCTION
Definition at line 56 of file ll_structure.h.
LL_CallConv
enum LL_CallConv
Calling conventions. See the LLVM source file include/llvm/IR/CallingConv.h for the complete list.
Enumerator
LL_CallConv_C
This is the default.
LL_CallConv_Fast
LL_CallConv_Cold
LL_CallConv_X86_StdCall
LL_CallConv_X86_FastCall
LL_CallConv_X86_ThisCall
LL_CallConv_X86_VectorCall
LL_CallConv_APCS
LL_CallConv_AAPCS
LL_CallConv_AAPCS_VFP
LL_CallConv_PTX_Kernel
LL_CallConv_PTX_Device
LL_CallConv_SPIR_FUNC
LL_CallConv_SPIR_KERNEL
Definition at line 101 of file ll_structure.h.
LL_DW_OP_t
enum LL_DW_OP_t
Enumerator
LL_DW_OP_NONE
bogus value
LL_DW_OP_deref
LL_DW_OP_plus
LL_DW_OP_minus
LL_DW_OP_dup
LL_DW_OP_LLVM_fragment
LL_DW_OP_swap
LL_DW_OP_xderef
LL_DW_OP_stack_value
LL_DW_OP_constu
LL_DW_OP_plus_uconst
LL_DW_OP_int
LL_DW_OP_push_object_address
LL_DW_OP_mul
LL_DW_OP_over
LL_DW_OP_and
LL_DW_OP_MAX
must be last value
Definition at line 700 of file ll_structure.h.
LL_DWARFVersion
enum LL_DWARFVersion
Enumerator
LL_DWARF_Version_2
LL_DWARF_Version_3
LL_DWARF_Version_4
LL_DWARF_Version_5
Definition at line 157 of file ll_structure.h.
LL_IRVersion
enum LL_IRVersion
Supported LLVM IR versions.
We can generate LLVM IR for multiple versions of LLVM. The numeric value of these version enumerators must match the x-bits set by the rcfiles.
The CPU target version is set by -x 249 from rcfiles/llvmrc.
Enumerator
LL_Version_3_1
LL_Version_3_2
LL_Version_3_4
LL_Version_3_5
LL_Version_3_6
LL_Version_3_7
LL_Version_3_8
LL_Version_3_9
LL_Version_4_0
LL_Version_5_0
LL_Version_6_0
LL_Version_7_0
LL_Version_8_0
LL_Version_9_0
LL_Version_11_0
LL_Version_12_0
LL_Version_13_0
LL_Version_trunk
Definition at line 134 of file ll_structure.h.
LL_LinkageType
enum LL_LinkageType
Enumerator
LL_INTERNAL_LINKAGE
LL_COMMON_LINKAGE
LL_EXTERNAL_LINKAGE
LL_WEAK_LINKAGE
LL_NO_LINKAGE
Definition at line 48 of file ll_structure.h.
LL_MDClass
enum LL_MDClass
Classes for specialized metadata nodes.
Plain metadata nodes are simply printed as !{ ... }, but starting with LLVM 3.6, metadata nodes can be specialized to contain a certain class of data, and they look like: !MDLocation(line: 2900, column:42, ...).
The metadata node classes should also be used when targeting LLVM < 3.6. They will be used to annotate the emitted plain metadata nodes in comments.
Enumerator
LL_PlainMDNode
not a DIxxx metadata
LL_DICompileUnit
LL_DIFile
LL_DIBasicType
LL_DISubroutineType
LL_DIDerivedType
LL_DICompositeType
LL_DIFortranArrayType
LL_DISubRange
LL_DIFortranSubrange
LL_DIEnumerator
LL_DITemplateTypeParameter
LL_DITemplateValueParameter
LL_DINamespace
LL_DIModule
LL_DIGlobalVariable
LL_DISubprogram
LL_DILexicalBlock
LL_DILexicalBlockFile
LL_DILocation
LL_DILocalVariable
LL_DIExpression
LL_DIObjCProperty
LL_DIImportedEntity
LL_DIGlobalVariableExpression
LL_DIBasicType_string
LL_DIStringType
LL_DICommonBlock
LL_DIGenericSubRange
LL_MDClass_MAX
must be last value and < 64 (6 bits)
Definition at line 655 of file ll_structure.h.
LL_MDName
enum LL_MDName
Named module-level metadata.
We support a predefined set of well-known metadata names. When adding a new name here, also update get_metadata_name() in ll_write.c.
Enumerator
MD_llvm_module_flags
Module flags, defined in the LLVM Language Reference Manual.
MD_llvm_dbg_cu
DWARF compilation unit descriptors, from "Source Level Debugging with LLVM".
MD_llvm_linker_options
MD_opencl_kernels
SPIR
MD_nvvm_annotations
CUDA
MD_nvvmir_version
CUDA
MD_NUM_NAMES
Must be last.
Definition at line 732 of file ll_structure.h.
LL_MDRef_Kind
enum LL_MDRef_Kind
Metadata node types.
Enumerator
MDRef_Node
Value=0 -> null, otherwise MDNode !n
MDRef_String
Value is an index into module->mdstrings.
MDRef_Constant
Value is an index into module->constants.
MDRef_SmallInt1
Valus is an i1 constant (0 or 1).
MDRef_SmallInt32
Value is a small unsigned i32 value (within the range of mdref.value).
MDRef_SmallInt64
Value is a small unsigned i64 value (within the range of mdref.value).
Definition at line 634 of file ll_structure.h.
LL_ModuleVarType
enum LL_ModuleVarType
Enumerator
LL_DEFAULT
LL_GLOBAL
LL_SHARED
LL_LOCAL
LL_DEVICE
LL_CONSTANT
Definition at line 39 of file ll_structure.h.
LL_ObjectInitStyle
enum LL_ObjectInitStyle
Enumerator
LLInit_Declaration
Declaration of an object that is initialized in another module.
LLInit_Zero
Object is initialized with all zeros.
LLInit_ConstExpr
Object is initialized with a constant expression in LL_Object::initializer
LLInit_Function
Object's initializer is printed by the provided function pointer.
Definition at line 789 of file ll_structure.h.
LL_ObjectKind
enum LL_ObjectKind
LL_Object represents an object stored in memory.
An object belongs to an address space, and it always has an address. LL_Object can represent different kinds of objects.
Enumerator
LLObj_Global
A global variable
LLObj_Const
A global constant
LLObj_Alias
An alias referencing part of on other object
LLObj_Local
A local variable on the stack
LLObj_LocalBuffered
A local variable on the stack for formals bigger than actuals
Definition at line 780 of file ll_structure.h.
LL_Op
enum LL_Op
Enumerator
LL_ADD
LL_FADD
LL_SUB
LL_FSUB
LL_MUL
LL_FMUL
LL_UDIV
LL_SDIV
LL_UREM
LL_SREM
LL_FDIV
LL_OR
LL_XOR
LL_ASHR
LL_LSHR
LL_SHL
LL_AND
LL_STORE
LL_LOAD
LL_SEXT
LL_ZEXT
LL_TRUNC
LL_SITOFP
LL_UITOFP
LL_FPTOSI
LL_FPTOUI
LL_FPTRUNC
LL_FPEXT
LL_CALL
LL_RET
LL_ICMP
LL_FCMP
LL_BR
LL_UBR
LL_SELECT
LL_GEP
LL_BITCAST
LL_INTTOPTR
LL_PTRTOINT
LL_ALLOCA
LL_TEXTCALL
LL_UNREACHABLE
LL_SWITCH
LL_EXTRACTVALUE
LL_INSERTVALUE
LL_ATOMICRMW
LL_CMPXCHG
LL_ASM
LL_EXTRACTELEM
LL_INSERTELEM
LL_FNEG
LL_NONE
Definition at line 23 of file ll_structure.h.
Function Documentation
add_linker_directives()
void add_linker_directives (LLVMModuleRef module)
Definition at line 593 of file ll_structure.cpp.
References LL_IRFeatures_::debug_info_version, flg, get_llvm_version(), i, LL_Module::ir, FLG::linker_directives, ll_extend_named_md_node(), ll_feature_versioned_dw_tag, LL_Version_5_0, llmd_add_i32(), llmd_add_md(), llmd_add_string(), llmd_finish(), llmd_init(), MD_llvm_linker_options, and MD_llvm_module_flags.
Referenced by ll_create_module().
get_llvm_version()
LL_IRVersion get_llvm_version (void)
...
...
Definition at line 30 of file ll_structure.cpp.
References flg, LL_Version_3_2, and FLG::x.
Referenced by add_linker_directives(), cg_llvm_init(), schedule(), and write_extern_inits().
ll_add_global_debug()
void ll_add_global_debug (LLVMModuleRef module, int sptr, LL_MDRef mdnode)
...
...
Parameters
module The module containing the map
sptr The key to be added
mdnode The value to be added
If the key, sptr, is already in the map, the map is unaltered.
Definition at line 2224 of file ll_structure.cpp.
References LL_Module::global_debug_map, hashmap_insert(), hashmap_lookup(), INT2HKEY, LL_Type_::module, sptr, and value().
Referenced by lldbg_create_deferred_len_string_type_mdnode(), and lldbg_emit_global_variable().
ll_add_module_debug()
void ll_add_module_debug (hashmap_t map, const char * module_name, LL_MDRef mdnode)
Add module_name → mdnode to module debug map.
Parameters
module The module containing the map
module_name The key to be added
mdnode The value to be added
If the key, module_name, is already in the map, the map is unaltered.
Definition at line 2779 of file ll_structure.cpp.
References hashmap_insert(), hashmap_lookup(), and INT2HKEY.
Referenced by lldbg_create_module_mdnode(), lldbg_emit_common_block_mdnode(), and lldbg_emit_global_variable().
ll_append_llvm_used()
void ll_append_llvm_used (LLVMModuleRef module, LL_Value * ptr)
...
...
Pointer bitcasts and/or addrspacecasts will be added as needed.
Definition at line 2342 of file ll_structure.cpp.
References LL_Type_::addrspace, ll_create_int_type(), ll_create_sym(), ll_get_const_addrspacecast(), ll_get_const_bitcast(), ll_get_pointer_addrspace(), ll_get_pointer_type(), LL_Module::llvm_used, LL_Type_::module, LL_Module::num_llvm_used, LL_Value::type_struct, and LL_Symbols_::values.
ll_create_anon_struct_type()
LL_Type * ll_create_anon_struct_type (LLVMModuleRef module, LL_Type * elements[], unsigned num_elements, bool is_packed, int addrspace)
...
...
Anonymous structs are identified by their contents, they don't have a name. This will either return an existing anonymous struct type with the required elements, or create a new type with a copy of the elements array.
A packed struct has alignment 1 and no padding between members.
Definition at line 1519 of file ll_structure.cpp.
References LL_Type_::addrspace, LL_Type_::data_type, LL_Type_::flags, i, len, ll_manage_malloc(), LL_STRUCT, ll_type_bytes(), LL_TYPE_IS_PACKED_STRUCT, LL_Type_::module, NULL, offset, pos, str, LL_Type_::str, strlen(), LL_Type_::sub_elements, LL_Type_::sub_offsets, LL_Type_::sub_padding, LL_Type_::sub_types, and unique_type().
Referenced by amd64_coerce(), gen_llvm_cmpxchg(), gen_vsincos_return_type(), ll_coercion_type(), and ll_convert_basic_dtype_with_addrspace().
ll_create_array_value_from_type()
LL_Value * ll_create_array_value_from_type (LLVMModuleRef module, LL_Type * type, const char * data, int addrspace)
...
Definition at line 1039 of file ll_structure.cpp.
References ll_create_blank_value(), ll_get_array_type(), type, and LL_Value::type_struct.
ll_create_basic_type()
LL_Type * ll_create_basic_type (LLVMModuleRef module, enum LL_BaseDataType type, int addrspace)
...
Definition at line 1100 of file ll_structure.cpp.
References LL_Type_::addrspace, assert, LL_Type_::data_type, ERR_Fatal, LL_Type_::flags, ll_get_str_type_for_basic_type(), LL_X86_MMX, LL_Type_::module, NULL, LL_Type_::str, LL_Type_::sub_elements, LL_Type_::sub_offsets, LL_Type_::sub_padding, LL_Type_::sub_types, type, and unique_type().
Referenced by add_ctor(), add_external_function_declaration(), amd64_coerce(), classify_common(), convert_dtype(), gen_llvm_cmpxchg(), layout_struct_body(), ll_abi_classify_arg_dtype(), ll_abi_classify_return_dtype(), ll_abi_function_type(), ll_abi_return_type(), ll_convert_basic_dtype_with_addrspace(), ll_create_int_type_with_addrspace(), ll_create_pointer_value(), make_lltype_from_sptr(), and make_void_lltype().
ll_create_device_function_from_type()
LL_Function * ll_create_device_function_from_type (LLVMModuleRef module, LL_Type * func_type, const char * name, int is_kernel, int launch_bounds, const char * calling_convention, enum LL_LinkageType)
Creates NVVM function.
Definition at line 700 of file ll_structure.cpp.
References LL_Function_::calling_convention, CHECK, LL_Type_::data_type, LL_Module::first, is_kernel, LL_Function_::is_kernel, LL_Module::last, LL_Function_::launch_bounds, LL_Function_::linkage, LL_FUNCTION, ll_manage_calloc(), ll_manage_strdup(), ll_set_function_num_arguments(), LL_Function_::local_vars, name, LL_Function_::name, LL_Function_::next, NULL, LL_Symbols_::num_values, LL_Function_::return_type, LL_Type_::sub_elements, LL_Type_::sub_types, and LL_Symbols_::values.
Referenced by schedule().
ll_create_distinct_md_node()
LL_MDRef ll_create_distinct_md_node (LLVMModuleRef module, enum LL_MDClass mdclass, const LL_MDRef * elems, unsigned nelems)
...
...
Definition at line 2250 of file ll_structure.cpp.
References alloc_mdnode(), insert_mdnode(), LL_MDREF_INITIALIZER, MDRef_Node, and LL_Type_::module.
Referenced by ll_finish_variable(), llmd_finish(), and schedule().
ll_create_flexible_md_node()
LL_MDRef ll_create_flexible_md_node (LLVMModuleRef module)
...
...
Definition at line 2262 of file ll_structure.cpp.
References alloc_flexible_mdnode(), insert_mdnode(), LL_MDREF_INITIALIZER, MDRef_Node, LL_Type_::module, and NULL.
Referenced by cons_loop_id_md(), lldbg_create_compile_unit_mdnode(), lldbg_create_outlined_parameters_node(), lldbg_emit_outlined_subprogram(), lldbg_emit_subprogram(), and lldbg_emit_type().
ll_create_function()
LL_Function * ll_create_function (LLVMModuleRef module, const char * name, LL_Type * return_type, int is_kernel, int launch_bounds, int launch_bounds_minctasm, const char * calling_convention, enum LL_LinkageType linkage)
...
Definition at line 641 of file ll_structure.cpp.
References LL_Function_::arguments, LL_Function_::calling_convention, LL_Function_::first, LL_Module::first, is_kernel, LL_Function_::is_kernel, LL_Function_::last, LL_Module::last, LL_Function_::launch_bounds, LL_Function_::launch_bounds_minctasm, LL_Function_::linkage, ll_manage_calloc(), ll_manage_strdup(), LL_Function_::local_vars, name, LL_Function_::name, LL_Function_::next, NULL, LL_Function_::num_args, LL_Function_::num_locals, LL_Symbols_::num_values, LL_Function_::return_type, and LL_Symbols_::values.
Referenced by add_ctor().
ll_create_function_from_type()
LL_Function * ll_create_function_from_type (LL_Type * func_type, const char * name)
...
...
Must be given its name and full LL_FUNCTION type. Note: This does not add the new function to the module's list of functions.
Definition at line 683 of file ll_structure.cpp.
References CHECK, LL_Type_::data_type, LL_FUNCTION, ll_manage_strdup(), ll_set_function_num_arguments(), LL_Type_::module, name, LL_Function_::name, LL_Function_::return_type, LL_Type_::sub_elements, and LL_Type_::sub_types.
Referenced by schedule().
ll_create_function_type()
LL_Type * ll_create_function_type (LLVMModuleRef module, LL_Type * args[], unsigned num_args, int is_varargs)
...
...
The return type is passed as args[0], so the args[] array should have a total of num_args+1 elements.
Definition at line 1582 of file ll_structure.cpp.
References LL_Type_::addrspace, args, LL_Type_::data_type, LL_Type_::flags, i, len, LL_FUNCTION, ll_manage_malloc(), LL_TYPE_IS_VARARGS_FUNC, LL_Type_::module, NULL, pos, str, LL_Type_::str, strlen(), LL_Type_::sub_elements, LL_Type_::sub_offsets, LL_Type_::sub_padding, LL_Type_::sub_types, and unique_type().
Referenced by fixup_x86_abi_return(), ll_abi_function_type(), ll_add_func_proto(), ll_convert_iface_sptr(), ll_get_function_pointer(), and make_function_type_from_args().
ll_create_global_alias()
LL_Object * ll_create_global_alias (LL_Value * aliasee_ptr, const char * format, ...)
...
...
The name of the alias object is produced by the sprintf-link format string and arguments. If the generated name clashes with an existing global object in the module, a unique name will be generated.
The aliasee must be the address of another global object or a constant expression computing an address inside a global object.
Definition at line 2413 of file ll_structure.cpp.
References LL_Type_::addrspace, create_global(), ll_get_pointer_addrspace(), LLInit_ConstExpr, LLObj_Alias, LL_Type_::module, LL_Type_::sub_types, and LL_Value::type_struct.
ll_create_int_type()
LL_Type * ll_create_int_type (LLVMModuleRef module, unsigned bits)
...
...
Parameters
module The LLVM module
bits The number of bits used in the representation
Returns
A uniqued integral LL_Type
See LL_BaseDataType for all the integer bitwidths supported.
Definition at line 1192 of file ll_structure.cpp.
References bits, LL_AddrSp_Default, ll_create_int_type_with_addrspace(), and LL_Type_::module.
Referenced by amd64_coerce(), gen_llvm_expr(), gen_ptr_offset_val(), insert_llvm_dbg_value(), intern_const_int(), ll_append_llvm_used(), ll_coercion_type(), make_int_lltype(), make_lltype_from_sptr(), and process_symlinked_sptr().
ll_create_int_type_with_addrspace()
LL_Type * ll_create_int_type_with_addrspace (LLVMModuleRef module, unsigned bits, int addrspace)
...
...
Parameters
module The LLVM module
bits The number of bits used in the representation
addrspace The address space where type will be in
Returns
A uniqued integral LL_Type
See LL_BaseDataType for all the integer bitwidths supported.
Definition at line 1139 of file ll_structure.cpp.
References LL_Type_::addrspace, bits, ERR_Fatal, interr(), ll_create_basic_type(), LL_I1, LL_I128, LL_I16, LL_I24, LL_I256, LL_I32, LL_I40, LL_I48, LL_I56, LL_I64, LL_I8, LL_NOTYPE, and LL_Type_::module.
Referenced by convert_dtype(), and ll_create_int_type().
ll_create_local_name()
const char * ll_create_local_name (LL_Function * function, const char * format, ...)
...
...
The name is based on the provided printf-style format string and arguments. The leading % character should not be part for the format string.
Returns a pointer to a unique local name in function, including the leading %. The memory for the returned name is managed by the function.
Definition at line 2442 of file ll_structure.cpp.
References hash_functions_strings, hashset_alloc(), name, unique_name(), and LL_Function_::used_local_names.
Referenced by process_auto_sptr(), and process_formal_arguments().
ll_create_local_object()
LL_Object * ll_create_local_object (LL_Function * function, LL_Type * type, unsigned align_bytes, const char * format, ...)
...
...
The object will be allocated by an LLVM alloca instruction in the entry block. It will not be initialized.
The name of the local object is produced by the sprintf-link format string and arguments. If the generated name clashes with an existing local value in the function, a unique name will be generated.
Definition at line 2468 of file ll_structure.cpp.
References LL_Function_::first_local, hash_functions_strings, hashset_alloc(), LL_Function_::last_local, ll_get_pointer_type(), LL_INTERNAL_LINKAGE, ll_manage_calloc(), LLObj_Local, LL_Object::next, type, unique_name(), and LL_Function_::used_local_names.
Referenced by gen_name_private_sptr(), process_auto_sptr(), process_formal_arguments(), and process_local_sptr().
ll_create_module()
LLVMModuleRef ll_create_module (const char * module_name, const char * target_triple, enum LL_IRVersion llvm_ir_version)
...
Definition at line 539 of file ll_structure.cpp.
References add_linker_directives(), LL_Module::anon_types, LL_Module::common_debug_map, compute_datalayout(), compute_ir_feature_vector(), LL_Module::constants, LL_Module::constants_alloc, constants_hash_functions, LL_Module::constants_map, LL_Module::extern_func_refs, LL_Module::first, LL_Module::first_malloc, flg, LL_Module::global_debug_map, hash_functions_direct, hash_functions_strings, hashmap_alloc(), hashset_alloc(), LL_Module::last, FLG::linker_directives, ll_manage_strdup(), mdnode_hash_functions, LL_Module::mdnodes, LL_Module::mdnodes_alloc, LL_Module::mdnodes_fwdvars, LL_Module::mdnodes_map, LL_Module::mdstrings, LL_Module::mdstrings_alloc, LL_Module::mdstrings_map, LL_Module::module_debug_map, LL_Module::module_name, LL_Module::module_vars, LL_Module::modvar_debug_map, NULL, LL_Module::num_module_vars, LL_Module::num_refs, LL_Module::num_user_structs, LL_Symbols_::num_values, LL_Module::target_triple, types_hash_functions, LL_Module::used_global_names, LL_Module::used_type_names, LL_Module::user_structs, LL_Module::user_structs_byid, LL_Symbols_::values, and LL_Module::written_user_structs.
Referenced by cg_llvm_init().
ll_create_named_struct_type()
LL_Type * ll_create_named_struct_type (LLVMModuleRef module, int id, bool unique, const char * format, ...)
...
...
Type can be uniquely named if parameter unique is set to true
If id is positive, the new struct type is associated with the id so it can be retrieved with ll_get_struct_type(). Usually, the TY_STRUCT dtype is used as an id.
It is an error to create multiple types with the same positive id, unless ll_reset_module_types() is called in between.
A zero or negative id is ignored.
The name of the new struct type will be based on the printf-style format and additional arguments. A '' character will be prepended, don't include one in the format string.
The new struct name may not be exactly as requested, so don't depend on it. The type name may be modified to ensure its uniqueness.
Definition at line 1430 of file ll_structure.cpp.
References assert, LL_Type_::data_type, ERR_Fatal, LL_Type_::flags, hashmap_replace(), INT2HKEY, ll_create_sym(), ll_create_value_from_type(), ll_named_struct_type_exists(), ll_remove_struct_type(), LL_STRUCT, LL_TYPE_IS_NAMED_STRUCT, LL_Type_::module, LL_Module::num_user_structs, LL_Type_::str, LL_Value::type_struct, unique_name(), LL_Module::used_type_names, LL_Module::user_structs, and LL_Module::user_structs_byid.
Referenced by ll_convert_struct_dtype().
ll_create_operands()
LL_Value ** ll_create_operands (LLVMModuleRef module, int num_operands)
...
ll_create_pointer_value()
LL_Value * ll_create_pointer_value (LLVMModuleRef module, enum LL_BaseDataType type, const char * data, int addrspace)
...
Definition at line 1017 of file ll_structure.cpp.
References ll_create_basic_type(), ll_create_blank_value(), ll_get_pointer_type(), type, and LL_Value::type_struct.
ll_create_pointer_value_from_type()
LL_Value * ll_create_pointer_value_from_type (LLVMModuleRef module, LL_Type * type, const char * data, int addrspace)
...
Definition at line 1048 of file ll_structure.cpp.
References ll_create_blank_value(), ll_get_addrspace_type(), ll_get_pointer_type(), type, and LL_Value::type_struct.
Referenced by schedule().
ll_create_sym()
void ll_create_sym (struct LL_Symbols_ * symbol_table, unsigned index, LL_Value * new_value)
...
Definition at line 737 of file ll_structure.cpp.
References index, LL_Symbols_::num_values, and LL_Symbols_::values.
Referenced by ll_append_llvm_used(), and ll_create_named_struct_type().
ll_create_value_from_type()
LL_Value * ll_create_value_from_type (LLVMModuleRef module, LL_Type * type, const char * data)
...
Definition at line 1031 of file ll_structure.cpp.
References ll_create_blank_value(), type, and LL_Value::type_struct.
Referenced by add_global_define(), addDebugForGlobalVar(), gen_ptr_offset_val(), intern_constant(), ll_create_named_struct_type(), and lldbg_function_end().
ll_destroy_function()
void ll_destroy_function (LL_Function * function)
Deallocate all memory used by function.
Note that this function is called automatically by ll_destroy_module(), so it should only be called explicitly for functions that are not in the module's linked list.
Definition at line 108 of file ll_structure.cpp.
References LL_Function_::arguments, current, LL_Function_::first, free_iterator(), hashset_free(), hashset_iterate(), ll_destroy_basic_block(), next, NULL, and LL_Function_::used_local_names.
Referenced by ll_destroy_module(), and schedule().
ll_destroy_mem()
void ll_destroy_mem (struct LL_ManagedMallocs_ * current)
...
Definition at line 134 of file ll_structure.cpp.
References current.
Referenced by ll_destroy_module().
ll_destroy_module()
void ll_destroy_module (LLVMModuleRef module)
...
Definition at line 482 of file ll_structure.cpp.
References LL_Module::anon_types, LL_Module::common_debug_map, LL_Module::constants, LL_Module::constants_map, current, LL_Module::debug_info, LL_Module::first, LL_Module::first_malloc, LL_Module::global_debug_map, hashmap_free(), hashset_free(), i, ll_destroy_function(), ll_destroy_mem(), lldbg_free(), MD_NUM_NAMES, LL_Module::mdnodes, LL_Module::mdnodes_count, LL_Module::mdnodes_map, LL_Module::mdstrings, LL_Module::mdstrings_count, LL_Module::mdstrings_map, LL_Module::module_debug_map, LL_Module::module_vars, LL_Module::modvar_debug_map, LL_Module::named_mdnodes, next, LL_ManagedMallocs_::next, NULL, LL_Module::used_global_names, LL_Module::used_type_names, LL_Module::user_structs, LL_Module::user_structs_byid, and LL_Symbols_::values.
ll_dw_op_ok()
static INLINE bool ll_dw_op_ok (LL_DW_OP_t op) static
Definition at line 721 of file ll_structure.h.
References LL_DW_OP_MAX, and LL_DW_OP_NONE.
Referenced by lldbg_encode_expression_arg().
ll_extend_md_node()
void ll_extend_md_node (LLVMModuleRef module, LL_MDRef flexnode, LL_MDRef elem)
...
...
The node must have been created by ll_create_flexible_md_node()
Definition at line 2275 of file ll_structure.cpp.
References assert, ERR_Fatal, LL_MDREF_kind, LL_MDREF_value, mdnode_append(), LL_Module::mdnodes, MDRef_Node, LL_Type_::module, and slot.
Referenced by cons_loop_id_md(), cons_vec_always_metadata(), construct_vectorlength_metadata(), lldbg_create_aggregate_members_type(), lldbg_create_global_variable_mdnode(), lldbg_create_imported_entity(), lldbg_create_subprogram_mdnode(), lldbg_emit_lv_list(), lldbg_emit_outlined_parameter_list(), lldbg_emit_subprogram(), and schedule().
ll_extend_named_md_node()
void ll_extend_named_md_node (LLVMModuleRef module, enum LL_MDName name, LL_MDRef elem)
...
...
Creates the named metadata node if needed.
Definition at line 2326 of file ll_structure.cpp.
References alloc_flexible_mdnode(), assert, ERR_Fatal, MD_NUM_NAMES, mdnode_append(), LL_Type_::module, name, and LL_Module::named_mdnodes.
Referenced by add_linker_directives(), lldbg_create_compile_unit_mdnode(), and lldbg_init().
ll_feature_dwarf_version()
unsigned ll_feature_dwarf_version (const LL_IRFeatures * feature)
...
...
The DWARF version is either the default or specified from the command-line.
Definition at line 434 of file ll_structure.cpp.
References feature, LL_DWARF_Version_2, LL_DWARF_Version_3, LL_DWARF_Version_4, and LL_DWARF_Version_5.
Referenced by lldbg_init().
ll_get_addrspace_type()
LL_Type * ll_get_addrspace_type (LL_Type * type, int addrspace)
...
...
Note: In LLVM IR only pointer types have an address space.
Definition at line 1203 of file ll_structure.cpp.
References LL_Type_::addrspace, type, and unique_type().
Referenced by create_global(), ll_create_pointer_value_from_type(), and ll_get_const_gep().
ll_get_array_type()
LL_Type * ll_get_array_type (LL_Type * type, BIGUINT64 num_elements, int addrspace)
...
Definition at line 1261 of file ll_structure.cpp.
References LL_Type_::addrspace, BIGIPFSZ, LL_Type_::data_type, LL_Type_::flags, LL_ARRAY, ll_manage_malloc(), LL_Type_::module, NULL, prefix, LL_Type_::str, strlen(), LL_Type_::sub_elements, LL_Type_::sub_offsets, LL_Type_::sub_padding, LL_Type_::sub_types, suffix, type, and unique_type().
Referenced by check_vector_registers(), check_vfp(), classify_common(), layout_struct_body(), ll_abi_classify_arg_dtype(), ll_coercion_type(), ll_convert_array_dtype(), ll_create_array_value_from_type(), make_array_lltype(), make_lltype_from_sptr(), process_symlinked_sptr(), and set_vect3_to_size4().
ll_get_calling_conv_str()
const char * ll_get_calling_conv_str (enum LL_CallConv cc)
...
...
Definition at line 1636 of file ll_structure.cpp.
References ERR_Fatal, interr(), LL_CallConv_AAPCS, LL_CallConv_AAPCS_VFP, LL_CallConv_APCS, LL_CallConv_C, LL_CallConv_Cold, LL_CallConv_Fast, LL_CallConv_PTX_Device, LL_CallConv_PTX_Kernel, LL_CallConv_SPIR_FUNC, LL_CallConv_SPIR_KERNEL, LL_CallConv_X86_FastCall, LL_CallConv_X86_StdCall, LL_CallConv_X86_ThisCall, and LL_CallConv_X86_VectorCall.
Referenced by print_function_signature(), and write_I_CALL().
ll_get_const_addrspacecast()
LL_Value * ll_get_const_addrspacecast (LLVMModuleRef module, LL_Value * value, LL_Type * type)
...
...
When targeting LLVM version that don't have the addrspacecast instruction, this will use ptrtoint/inttoptr instead.
Definition at line 1911 of file ll_structure.cpp.
References assert, LL_Module::constants, ERR_Fatal, intern_constant(), LL_Module::ir, ll_feature_use_addrspacecast, ll_get_pointer_addrspace(), ll_type_bytes(), malloc(), LL_Type_::module, name, slot, strlen(), type, and value().
Referenced by ll_append_llvm_used().
ll_get_const_bitcast()
LL_Value * ll_get_const_bitcast (LLVMModuleRef module, LL_Value * value, LL_Type * type)
...
...
This creates a bitcast expression that may be used to initialize globals and metadata. It does not create an LL_BITCAST instruction.
Definition at line 1883 of file ll_structure.cpp.
References LL_Module::constants, intern_constant(), malloc(), LL_Type_::module, name, slot, strlen(), type, and value().
Referenced by gen_ptr_offset_val(), and ll_append_llvm_used().
ll_get_const_gep()
LL_Value * ll_get_const_gep (LLVMModuleRef module, LL_Value * ptr, unsigned num_idx, ...)
...
...
This creates a gep-expression that may be used to initialize globals and metadata. It does not create an LL_GEP instruction.
The num_idx argument is the number of index operands on the gep expression. It should be at least 1.
The gep indices following num_idx should be ints.
Note: element type is the exected element type, this does not get elements of any different type.
Definition at line 1820 of file ll_structure.cpp.
References apply_gep_index(), assert, LL_Module::constants, LL_Value::data, ERR_Fatal, idx, intern_constant(), LL_Module::ir, ll_feature_explicit_gep_load_type, ll_get_addrspace_type(), ll_get_pointer_addrspace(), ll_get_pointer_type(), LL_PTR, malloc(), LL_Type_::module, name, p, slot, LL_Type_::str, strlen(), LL_Type_::sub_types, type, and LL_Value::type_struct.
Referenced by gen_ptr_offset_val().
ll_get_const_int()
LL_Value * ll_get_const_int (LLVMModuleRef module, unsigned bits, long long value)
...
...
Definition at line 1729 of file ll_structure.cpp.
References bits, LL_Module::constants, intern_const_int(), LL_Type_::module, slot, and value().
ll_get_function_pointer()
LL_Value * ll_get_function_pointer (LLVMModuleRef module, LL_Function * function)
...
...
Note that the type of this function pointer depends on the added function arguments.
Definition at line 1762 of file ll_structure.cpp.
References args, LL_Function_::arguments, i, ll_create_function_type(), ll_get_global_pointer(), malloc(), LL_Type_::module, LL_Function_::name, LL_Function_::num_args, LL_Function_::return_type, and LL_Value::type_struct.
ll_get_global_debug()
LL_MDRef ll_get_global_debug (LLVMModuleRef module, int sptr)
...
Definition at line 2235 of file ll_structure.cpp.
References LL_Module::global_debug_map, hashmap_lookup(), HKEY2INT, INT2HKEY, LL_MDREF_ctor, LL_Type_::module, and sptr.
Referenced by lldbg_create_cmblk_mem_mdnode_list(), lldbg_create_ftn_subrange_via_sdsc(), and lldbg_emit_global_variable().
ll_get_global_pointer()
LL_Value * ll_get_global_pointer (const char * name, LL_Type * type)
...
...
This will prepend @ to the name and add one level of indirection to the type.
Definition at line 1742 of file ll_structure.cpp.
References intern_constant(), ll_get_pointer_type(), malloc(), name, slot, strlen(), and type.
Referenced by ll_get_function_pointer().
ll_get_md_i1()
LL_MDRef ll_get_md_i1 (int value)
...
...
Definition at line 1951 of file ll_structure.cpp.
References assert, ERR_Fatal, LL_MDREF_INITIALIZER, MDRef_SmallInt1, and value().
Referenced by cons_novectorize_metadata(), cons_vectorize_metadata(), cons_vectorlength_scalable_metadata(), and llmd_add_i1().
ll_get_md_i32()
LL_MDRef ll_get_md_i32 (LLVMModuleRef module, int value)
...
...
Definition at line 1961 of file ll_structure.cpp.
References intern_const_int(), LL_MDREF_ctor, MDRef_Constant, MDRef_SmallInt32, LL_Type_::module, and value().
Referenced by cons_unroll_count_metadata(), construct_vectorlength_metadata(), and llmd_add_i32().
ll_get_md_i64()
LL_MDRef ll_get_md_i64 (LLVMModuleRef module, long long value)
...
...
Definition at line 1973 of file ll_structure.cpp.
References intern_const_int(), LL_MDREF_ctor, LL_MDREF_INITIALIZER, MDRef_Constant, MDRef_SmallInt64, LL_Type_::module, and value().
Referenced by get_omnipotent_pointer(), get_tbaa_metadata(), init_subrange_bound(), lldbg_emit_type(), llmd_add_i64(), and locset_to_tbaa_info().
ll_get_md_node()
LL_MDRef ll_get_md_node (LLVMModuleRef module, enum LL_MDClass mdclass, const LL_MDRef * elems, unsigned nelems)
...
...
Definition at line 2194 of file ll_structure.cpp.
References alloc_mdnode(), hashmap_insert(), hashmap_lookup(), HKEY2INT, insert_mdnode(), INT2HKEY, LL_MDREF_ctor, LL_MDREF_INITIALIZER, LL_Module::mdnodes_map, MDRef_Node, and LL_Type_::module.
Referenced by cons_loop_parallel_accesses_metadata(), cons_nounroll_metadata(), cons_novectorize_metadata(), cons_unroll_count_metadata(), cons_unroll_metadata(), cons_vectorize_metadata(), cons_vectorlength_scalable_metadata(), construct_vectorlength_metadata(), get_omnipotent_pointer(), get_tbaa_metadata(), ll_finish_variable(), lldbg_create_compile_unit_mdnode(), lldbg_create_subprogram_mdnode(), llmd_finish(), and locset_to_tbaa_info().
ll_get_md_rawstring()
LL_MDRef ll_get_md_rawstring (LLVMModuleRef module, const void * rawstr, size_t length)
...
...
The string can contain arbitrary bytes, including nuls; appropriate escaping will be added.
Definition at line 1993 of file ll_structure.cpp.
References i, NEEDS_ESC, and p.
Referenced by ll_get_md_string().
ll_get_md_string()
LL_MDRef ll_get_md_string (LLVMModuleRef module, const char * str)
...
...
The string can contain arbitrary bytes, except for nul; appropriate escaping will be added.
Definition at line 2054 of file ll_structure.cpp.
References ll_get_md_rawstring(), LL_Type_::module, str, and strlen().
Referenced by cons_loop_parallel_accesses_metadata(), cons_nounroll_metadata(), cons_novectorize_metadata(), cons_unroll_count_metadata(), cons_unroll_metadata(), cons_vectorize_metadata(), cons_vectorlength_scalable_metadata(), construct_vectorlength_metadata(), get_omnipotent_pointer(), llmd_add_string(), and locset_to_tbaa_info().
ll_get_md_value()
LL_MDRef ll_get_md_value (LLVMModuleRef module, LL_Value * value)
...
...
Definition at line 2063 of file ll_structure.cpp.
References intern_constant(), LL_MDREF_ctor, MDRef_Constant, LL_Type_::module, and value().
Referenced by lldbg_create_global_variable_mdnode(), lldbg_set_func_ptr(), and llmd_add_value().
ll_get_module_debug()
LL_MDRef ll_get_module_debug (hashmap_t map, const char * module_name)
Definition at line 2787 of file ll_structure.cpp.
References hashmap_lookup(), HKEY2INT, and LL_MDREF_ctor.
Referenced by lldbg_create_imported_entity(), lldbg_emit_common_block_mdnode(), lldbg_emit_module_mdnode(), and process_cmnblk_data().
ll_get_pointer_addrspace()
int ll_get_pointer_addrspace (LL_Type * ptr)
...
...
Parameters
ptr A pointer type
Given a pointer type, return the address space that is being pointed into.
Definition at line 1064 of file ll_structure.cpp.
References LL_Type_::addrspace, assert, LL_Type_::data_type, ERR_Fatal, LL_PTR, and LL_Type_::sub_types.
Referenced by ll_append_llvm_used(), ll_create_global_alias(), ll_get_const_addrspacecast(), ll_get_const_gep(), and ll_write_global_objects().
ll_get_pointer_type()
LL_Type * ll_get_pointer_type (LL_Type * type)
...
...
Definition at line 1220 of file ll_structure.cpp.
References LL_Type_::addrspace, LL_Type_::data_type, LL_Type_::flags, ll_manage_malloc(), LL_PTR, LL_Type_::module, NULL, size, LL_Type_::str, strlen(), LL_Type_::sub_elements, LL_Type_::sub_offsets, LL_Type_::sub_padding, LL_Type_::sub_types, type, and unique_type().
Referenced by add_external_function_declaration(), addDebugForGlobalVar(), convert_dtype(), create_global(), gen_ptr_offset_val(), layout_struct_body(), ll_abi_classify_arg_dtype(), ll_abi_complete_arg_info(), ll_append_llvm_used(), ll_create_local_object(), ll_create_pointer_value(), ll_create_pointer_value_from_type(), ll_get_const_gep(), ll_get_global_pointer(), lldbg_function_end(), make_lltype_from_sptr(), make_ptr_lltype(), maybe_do_gep_folding(), maybe_fixup_x86_abi_return(), process_formal_arguments(), put_addr(), set_vect3_to_size4(), and write_operand().
ll_get_str_type_for_basic_type()
const char * ll_get_str_type_for_basic_type (enum LL_BaseDataType type)
...
Definition at line 767 of file ll_structure.cpp.
References LL_DOUBLE, LL_FLOAT, LL_FP128, LL_HALF, LL_I1, LL_I128, LL_I16, LL_I24, LL_I256, LL_I32, LL_I40, LL_I48, LL_I56, LL_I64, LL_I8, LL_LABEL, LL_METADATA, LL_NOTYPE, LL_PPC_FP128, LL_VOID, LL_X86_FP80, LL_X86_MMX, and type.
Referenced by ll_create_basic_type().
ll_get_struct_type()
LL_Type * ll_get_struct_type (LLVMModuleRef module, int struct_id, int required)
...
...
The id must be positive.
If no named struct type has been created with that id, NULL is returned. If required is true, an internal compiler error is signaled instead of returning NULL.
Definition at line 1494 of file ll_structure.cpp.
References assert, ERR_Fatal, hashmap_lookup(), INT2HKEY, LL_Type_::module, NULL, LL_Value::type_struct, and LL_Module::user_structs_byid.
Referenced by ll_abi_classify_arg_dtype(), and ll_convert_struct_dtype().
ll_get_vector_type()
LL_Type * ll_get_vector_type (LL_Type * type, unsigned num_elements)
...
...
Definition at line 1301 of file ll_structure.cpp.
References LL_Type_::addrspace, LL_Type_::data_type, LL_Type_::flags, ll_manage_malloc(), LL_VECTOR, LL_Type_::module, NULL, prefix, LL_Type_::str, strlen(), LL_Type_::sub_elements, LL_Type_::sub_offsets, LL_Type_::sub_padding, LL_Type_::sub_types, type, and unique_type().
Referenced by amd64_coerce(), convert_dtype(), gen_binary_expr(), gen_llvm_expr(), gen_resized_vect(), gen_vect_compare_operand(), make_vector_lltype(), maybe_generate_fma(), and set_vect3_to_size4().
ll_named_struct_type_exists()
LL_Value * ll_named_struct_type_exists (LLVMModuleRef module, int id, const char * format, ...)
...
Definition at line 1383 of file ll_structure.cpp.
References hashmap_lookup(), hashset_lookup(), INT2HKEY, LL_Type_::module, NULL, LL_Module::used_type_names, and LL_Module::user_structs_byid.
Referenced by ll_create_named_struct_type().
ll_proto_add()
LL_FnProto * ll_proto_add (const char * fnname, struct LL_ABI_Info_ * abi)
...
...
Definition at line 2570 of file ll_structure.cpp.
References _ll_proto_head, _ll_proto_map, LL_FnProto_::abi, ERR_Fatal, LL_FnProto_::fn_name, hashmap_insert(), hashmap_lookup(), interr(), and LL_FnProto_::next.
Referenced by add_ctor(), add_external_function_declaration(), ll_add_func_proto(), and ll_proto_add_sptr().
ll_proto_add_sptr()
LL_FnProto * ll_proto_add_sptr (SPTR func_sptr, struct LL_ABI_Info_ * abi)
...
...
Also sets the proper name to use when defining/declaring the function.
Definition at line 2611 of file ll_structure.cpp.
References get_llvm_name(), ll_proto_add(), ll_proto_key(), and ll_proto_update_name().
Referenced by add_external_function_declaration(), ll_process_routine_parameters(), print_entry_subroutine(), and schedule().
ll_proto_dump()
void ll_proto_dump (void)
...
...
Definition at line 2758 of file ll_structure.cpp.
References _ll_proto_head, dump_proto(), FILE, gbl, and LL_FnProto_::next.
ll_proto_get_abi()
struct LL_ABI_Info_ * ll_proto_get_abi (const char * fnname)
...
Definition at line 2632 of file ll_structure.cpp.
References _ll_proto_map, LL_FnProto_::abi, hashmap_lookup(), and NULL.
Referenced by ll_make_kmpc_proto(), ll_process_routine_parameters(), process_ll_abi_func_ftn_mod(), write_final_table(), and write_vft().
ll_proto_has_defined_body()
bool ll_proto_has_defined_body (const char * fnname)
...
Definition at line 2665 of file ll_structure.cpp.
References _ll_proto_map, ERR_Fatal, LL_FnProto_::has_defined_body, hashmap_lookup(), interr(), and NULL.
ll_proto_init()
void ll_proto_init (void)
...
...
Should only ever be called once for the entire compilation
Definition at line 2549 of file ll_structure.cpp.
References _ll_proto_map, ERR_Fatal, hash_functions_strings, hashmap_alloc(), and interr().
Referenced by cg_llvm_init(), and ll_add_func_proto().
ll_proto_is_weak()
bool ll_proto_is_weak (const char * fnname)
...
Definition at line 2701 of file ll_structure.cpp.
References _ll_proto_map, ERR_Fatal, hashmap_lookup(), interr(), LL_FnProto_::is_weak, and NULL.
ll_proto_iterate()
void ll_proto_iterate (LL_FnProto_Handler callback)
...
Definition at line 2736 of file ll_structure.cpp.
References _ll_proto_head, and LL_FnProto_::next.
Referenced by write_external_function_declarations().
ll_proto_key()
const char * ll_proto_key (SPTR func_sptr)
...
...
Parameters
func_sptr An sptr to a function symbol
Given a function sptr return the function name (or interface name) to be used as a key for the rest of the fnname arguments for the ll_proto_* API.
Definition at line 2519 of file ll_structure.cpp.
References assert, find_ag(), get_llvm_ifacenm(), get_llvm_name(), and NULL.
Referenced by add_external_function_declaration(), build_routine_and_parameter_entries(), ll_process_routine_parameters(), ll_proto_add_sptr(), print_entry_subroutine(), process_ll_abi_func_ftn_mod(), write_final_table(), and write_vft().
ll_proto_set_abi()
void ll_proto_set_abi (const char * fnname, struct LL_ABI_Info_ * abi)
...
Definition at line 2619 of file ll_structure.cpp.
References _ll_proto_map, LL_FnProto_::abi, hashmap_lookup(), and NULL.
Referenced by process_ll_abi_func_ftn_mod().
ll_proto_set_defined_body()
void ll_proto_set_defined_body (const char * fnname, bool has_defined)
...
...
Parameters
fnname a key (function name)
has_defined true iff fnname is a definition
Sets the bit representing the information that the body of the function represented by fnname is defined.
Definition at line 2651 of file ll_structure.cpp.
References _ll_proto_map, ERR_Fatal, LL_FnProto_::has_defined_body, hashmap_lookup(), interr(), and NULL.
Referenced by build_routine_and_parameter_entries(), print_entry_subroutine(), and write_module_as_subroutine().
ll_proto_set_intrinsic()
void ll_proto_set_intrinsic (const char * fnname, const char * intrinsic_decl_str)
...
...
Parameters
fnname The key to lookup the prototype
intrinsic_decl_str The LLVM declare statement text
The prototype of fnname must already have been added to the map.
Definition at line 2722 of file ll_structure.cpp.
References _ll_proto_map, ERR_Fatal, hashmap_lookup(), interr(), LL_FnProto_::intrinsic_decl_str, and NULL.
Referenced by add_ctor(), and add_external_function_declaration().
ll_proto_set_weak()
void ll_proto_set_weak (const char * fnname, bool is_weak)
...
...
Parameters
fnname a key (function name)
is_weak true iff fnname is weak
Sets the bit representing the information that the function represented by fnname is weak.
Definition at line 2687 of file ll_structure.cpp.
References _ll_proto_map, ERR_Fatal, hashmap_lookup(), interr(), LL_FnProto_::is_weak, and NULL.
Referenced by add_external_function_declaration(), and build_routine_and_parameter_entries().
ll_remove_struct_type()
void ll_remove_struct_type (LLVMModuleRef module, int struct_id)
...
...
This is required whenever a struct has a same dtype but in different modules defined in same file
Definition at line 1479 of file ll_structure.cpp.
References hashmap_erase(), INT2HKEY, LL_Type_::module, NULL, and LL_Module::user_structs_byid.
Referenced by ll_create_named_struct_type().
ll_reserve_md_node()
unsigned ll_reserve_md_node (LLVMModuleRef module)
...
...
Parameters
module the LL_Module
Returns
the reserved slot plus 1
Definition at line 2153 of file ll_structure.cpp.
References LL_Module::mdnodes, LL_Module::mdnodes_alloc, LL_Module::mdnodes_count, LL_Type_::module, NULL, and slot.
Referenced by insert_mdnode(), and lldbg_fwd_local_variable().
ll_reset_module_types()
void ll_reset_module_types (LLVMModuleRef module)
...
...
This means that ll_get_struct_type() will not return any of the struct types created so far, and previously used type ids can be reused.
Reset the id -> type mapping, but deliberately keep the used_type_names set. We still want to guarantee globally unique type names in the module.
Definition at line 378 of file ll_structure.cpp.
References hashmap_clear(), LL_Type_::module, and LL_Module::user_structs_byid.
Referenced by cg_llvm_fnend().
ll_set_function_argument()
void ll_set_function_argument (LL_Function * function, int index, LL_Value * argument)
...
Definition at line 760 of file ll_structure.cpp.
References LL_Function_::arguments, and index.
ll_set_function_num_arguments()
void ll_set_function_num_arguments (LL_Function * function, int num_args)
...
Definition at line 753 of file ll_structure.cpp.
References LL_Function_::arguments, and LL_Function_::num_args.
Referenced by add_prototype(), ll_create_device_function_from_type(), and ll_create_function_from_type().
ll_set_md_node()
void ll_set_md_node (LLVMModuleRef module, unsigned mdNum, LL_MDNode * node)
...
Definition at line 2182 of file ll_structure.cpp.
References assert, ERR_Fatal, LL_Module::mdnodes, and LL_Type_::module.
Referenced by ll_finish_variable().
ll_set_named_md_node()
void ll_set_named_md_node (LLVMModuleRef module, enum LL_MDName name, const LL_MDRef * elems, unsigned nelems)
...
...
Definition at line 2312 of file ll_structure.cpp.
References alloc_flexible_mdnode(), assert, ERR_Fatal, MD_NUM_NAMES, LL_Type_::module, name, and LL_Module::named_mdnodes.
ll_set_struct_body()
void ll_set_struct_body (LL_Type * ctype, LL_Type *const * elements, unsigned *const offsets, char *const pads, unsigned num_elements, int is_packed)
...
...
It is not possible to change the body of an anonymous struct type.
The struct type is identified by the LL_Value returned from ll_create_named_struct_type().
Definition at line 1347 of file ll_structure.cpp.
References assert, ERR_Fatal, LL_STRUCT, LL_TYPE_IS_NAMED_STRUCT, LL_TYPE_IS_PACKED_STRUCT, NULL, and type.
Referenced by layout_struct_body().
ll_type_array_elety()
LL_Type * ll_type_array_elety (LL_Type * ty)
...
Definition at line 962 of file ll_structure.cpp.
References LL_Type_::data_type, LL_ARRAY, and LL_Type_::sub_types.
Referenced by match_types().
ll_type_bytes()
ISZ_T ll_type_bytes (LL_Type * type)
...
...
Parameters
type The type to be examined
Returns
size of an object of type type or 0
Definition at line 896 of file ll_structure.cpp.
References ERR_Fatal, interr(), ISZ_T, LLTypeGetBytesUnchecked(), size, and type.
Referenced by convert_int_size(), convert_mismatched_types(), convert_operand(), gen_base_addr_operand(), gen_llvm_expr(), gen_resized_vect(), layout_struct_body(), ll_create_anon_struct_type(), ll_get_const_addrspacecast(), ll_write_local_objects(), LLTypeGetBytesUnchecked(), make_bitcast(), make_conststring_op(), make_stmt(), match_types(), print_llsize(), print_llsize_tobuf(), process_formal_arguments(), and write_constant_value().
ll_type_bytes_unchecked()
ISZ_T ll_type_bytes_unchecked (LL_Type * type)
...
...
Parameters
type The type to be examined
Returns
size of object of type type or 0
Definition at line 912 of file ll_structure.cpp.
References LLTypeGetBytesUnchecked(), NULL, and type.
Referenced by gen_address_operand().
ll_type_int_bits()
unsigned ll_type_int_bits (LL_Type * type)
...
...
Parameters
type The LL_Type to inspect
Returns
0 iff type is not an integer type
Definition at line 923 of file ll_structure.cpp.
References LL_I1, LL_I128, LL_I16, LL_I24, LL_I256, LL_I32, LL_I40, LL_I48, LL_I56, LL_I64, LL_I8, and type.
Referenced by convert_int_size(), convert_int_to_ptr(), convert_mismatched_types(), gen_base_addr_operand(), gen_const_expr(), gen_llvm_expr(), make_load(), make_stmt(), match_types(), process_formal_arguments(), sign_extend_int(), write_ftn_type(), write_operand(), and zero_extend_int().
ll_type_is_fp()
int ll_type_is_fp (LL_Type * ty)
...
Definition at line 968 of file ll_structure.cpp.
References LL_Type_::data_type, LL_DOUBLE, LL_FLOAT, LL_FP128, LL_HALF, LL_PPC_FP128, and LL_X86_FP80.
Referenced by convert_mismatched_types(), gen_llvm_expr(), process_formal_arguments(), and write_operand().
ll_type_is_mem_seq()
int ll_type_is_mem_seq (LL_Type * ty)
...
Definition at line 985 of file ll_structure.cpp.
References LL_Type_::data_type, LL_ARRAY, and LL_PTR.
Referenced by gen_llvm_expr().
ll_type_is_pointer_to_function()
int ll_type_is_pointer_to_function (LL_Type * ty)
...
Definition at line 955 of file ll_structure.cpp.
References LL_Type_::data_type, LL_FUNCTION, LL_PTR, and LL_Type_::sub_types.
Referenced by write_I_CALL().
ll_update_md_node()
void ll_update_md_node (LLVMModuleRef module, LL_MDRef node_to_update, unsigned elem_index, LL_MDRef elem)
...
...
The node being updated must be either distinct or flexible, it is not allowed to update nodes that may be shared.
Definition at line 2290 of file ll_structure.cpp.
References assert, LL_MDNode::elem, ERR_Fatal, LL_MDNode::is_distinct, LL_MDNode::is_flexible, LL_MDREF_kind, LL_MDREF_value, LL_Module::mdnodes, MDRef_Node, LL_Type_::module, and slot.
Referenced by lldbg_set_func_ptr().
llObjtodbgAtEnd()
static INLINE bool llObjtodbgAtEnd (LL_ObjToDbgListIter * iter) static
Definition at line 1052 of file ll_structure.h.
References LL_ObjToDbgListIter::list, LL_ObjToDbgList::next, LL_ObjToDbgListIter::pos, and LL_ObjToDbgList::used.
Referenced by assemble_end(), ll_write_object_dbg_references(), and llObjtodbgAddUnique().
llObjtodbgCreate()
static INLINE LL_ObjToDbgList * llObjtodbgCreate (void) static
Definition at line 1039 of file ll_structure.h.
Referenced by lldbg_create_cmblk_mem_mdnode_list(), lldbg_emit_global_variable(), and llObjtodbgPush().
llObjtodbgFirst()
static INLINE void llObjtodbgFirst (LL_ObjToDbgList * ods, LL_ObjToDbgListIter * iter) static
Definition at line 1045 of file ll_structure.h.
References LL_ObjToDbgListIter::list, and LL_ObjToDbgListIter::pos.
Referenced by assemble_end(), ll_write_object_dbg_references(), and llObjtodbgAddUnique().
llObjtodbgFree()
void llObjtodbgFree (LL_ObjToDbgList * ods)
...
Definition at line 359 of file ll_structure.cpp.
References n, and LL_ObjToDbgList::next.
Referenced by assemble_end(), and ll_write_object_dbg_references().
llObjtodbgGet()
static INLINE LL_MDRef llObjtodbgGet (LL_ObjToDbgListIter * iter) static
Definition at line 1069 of file ll_structure.h.
References LL_ObjToDbgListIter::list, LL_ObjToDbgListIter::pos, and LL_ObjToDbgList::refs.
Referenced by assemble_end(), ll_write_object_dbg_references(), and llObjtodbgAddUnique().
llObjtodbgNext()
static INLINE void llObjtodbgNext (LL_ObjToDbgListIter * iter) static
Definition at line 1059 of file ll_structure.h.
References LL_ObjToDbgListIter::list, LL_ObjToDbgBucketSize, LL_ObjToDbgList::next, and LL_ObjToDbgListIter::pos.
Referenced by assemble_end(), ll_write_object_dbg_references(), and llObjtodbgAddUnique().
llObjtodbgPush()
void llObjtodbgPush (LL_ObjToDbgList * odl, LL_MDRef md)
...
Definition at line 346 of file ll_structure.cpp.
References LL_ObjToDbgBucketSize, llObjtodbgCreate(), and p.
Referenced by llObjtodbgAddUnique().
write_mdref()
void write_mdref (FILE * out, LLVMModuleRef module, LL_MDRef rmdref, int omit_metadata_type)
Referenced by write_tbaa_metadata().