flang: ll_abi.h File Reference
ll_abi.h File Reference
#include "gbldefs.h"
#include "global.h"
#include "symtab.h"
#include "llutil.h"
#include "ll_structure.h"
Functions
unsigned ll_abi_classify_va_arg_dtype (LL_Module *module, DTYPE dtype, unsigned *num_gp, unsigned *num_fp)
...
void ll_abi_classify_arg_dtype (LL_ABI_Info *abi, LL_ABI_ArgInfo *arg, DTYPE dtype)
...
void ll_abi_classify_return_dtype (LL_ABI_Info *abi, DTYPE dtype)
...
void ll_abi_compute_call_conv (LL_ABI_Info *abi, int func_sptr, int jsra_flags)
...
Function Documentation
ll_abi_classify_arg_dtype()
void ll_abi_classify_arg_dtype (LL_ABI_Info * abi, LL_ABI_ArgInfo * arg, DTYPE dtype)
...
Definition at line 278 of file aarch64/ll_abi.cpp.
References alignment(), amd64_classify(), amd64_coerce(), AMD64_INTEGER, AMD64_SSE, arg, assert, classify_common(), classify_int(), DT_BASETYPE, DT_ISCMPLX, DT_ISINT, DT_ISSCALAR, DT_ISVECT, DTY, ERR_Fatal, ISZ_T, LL_ARG_BYVAL, LL_ARG_COERCE, LL_ARG_DIRECT, LL_ARG_UNKNOWN, ll_coercion_type(), ll_convert_dtype(), ll_create_basic_type(), ll_get_array_type(), ll_get_pointer_type(), ll_get_struct_type(), LL_I32, LL_I64, LL_ABI_Info_::module, NULL, size, size_of(), update_arg_info(), LL_ABI_Info_::used_fregs, LL_ABI_Info_::used_iregs, and zsize_of().
Referenced by gen_arg_operand(), ll_process_routine_parameters(), and process_ll_abi_func_ftn_mod().
ll_abi_classify_return_dtype()
void ll_abi_classify_return_dtype (LL_ABI_Info * abi, DTYPE dtype)
...
Definition at line 238 of file aarch64/ll_abi.cpp.
References amd64_classify(), amd64_coerce(), LL_ABI_Info_::arg, classify_common(), classify_int(), DT_BASETYPE, DT_ISCMPLX, DT_ISINT, DT_ISSCALAR, DT_ISVECT, DT_VOIDNONE, ISZ_T, LL_ABI_ArgInfo_::kind, LL_ARG_COERCE, LL_ARG_DIRECT, LL_ARG_INDIRECT, LL_ARG_UNKNOWN, ll_coercion_type(), ll_create_basic_type(), LL_I16, LL_I32, LL_I64, LL_I8, LL_NOTYPE, LL_ABI_Info_::module, NULL, size, size_of(), LL_ABI_ArgInfo_::type, update_arg_info(), LL_ABI_Info_::used_iregs, and zsize_of().
Referenced by ll_abi_for_missing_prototype(), ll_check_struct_return(), and process_ll_abi_func_ftn_mod().
ll_abi_classify_va_arg_dtype()
unsigned ll_abi_classify_va_arg_dtype (LL_Module * module, DTYPE dtype, unsigned * num_gp, unsigned * num_fp)
...
Definition at line 307 of file aarch64/ll_abi.cpp.
References amd64_classify(), AMD64_INTEGER, AMD64_SSE, arm_homogeneous_aggr::base_bytes, check_vfp(), DT_ISINT, DTY, GP_XM, ISZ_T, ll_abi_num_regs(), arm_homogeneous_aggr::module, NULL, size, size_of(), XM_GP, and XM_XM.
ll_abi_compute_call_conv()
void ll_abi_compute_call_conv (LL_ABI_Info * abi, int func_sptr, int jsra_flags)
...
Definition at line 26 of file aarch64/ll_abi.cpp.
References LL_ABI_Info_::call_as_varargs, LL_ABI_Info_::call_conv, LL_CallConv_C, and LL_ABI_Info_::missing_prototype.
Referenced by ll_abi_for_missing_prototype(), and process_ll_abi_func_ftn_mod().