flang: llassem_common.h File Reference
llassem_common.h File Reference
#include "gbldefs.h"
#include "global.h"
#include "symtab.h"
#include "ll_structure.h"
Functions
ISZ_T put_skip (ISZ_T old, ISZ_T New, bool is_char)
...
char * put_next_member (char *ptr)
...
int add_member_for_llvm (SPTR sym, int prev, DTYPE dtype, ISZ_T size)
...
DTYPE mk_struct_for_llvm_init (const char *name, int size)
...
LL_Value * gen_ptr_offset_val (int offset, LL_Type *ret_type, const char *ptr_nm)
...
void add_init_routine (char *initroutine)
...
void emit_init (DTYPE tdtype, ISZ_T tconval, ISZ_T *addr, ISZ_T *repeat_cnt, ISZ_T loc_base, ISZ_T *i8cnt, int *ptrcnt, char **cptr, bool is_char)
...
void init_daz (void)
...
void init_flushz (void)
...
void init_huge_tlb (void)
...
void init_ktrap (void)
...
void init_Mcuda_compiled (void)
...
void put_addr (SPTR sptr, ISZ_T off, DTYPE dtype)
...
void put_i32 (int val)
...
void put_int4 (int val)
...
void put_short (int val)
...
void put_string_n (const char *p, ISZ_T len, int size)
...
Function Documentation
add_init_routine()
void add_init_routine (char * initroutine)
...
...
Definition at line 1081 of file llassem_common.cpp.
add_member_for_llvm()
int add_member_for_llvm (SPTR sym, int prev, DTYPE dtype, ISZ_T size)
...
Definition at line 1061 of file llassem_common.cpp.
References insert_sym_first(), mem(), NOSYM, prev, and size.
emit_init()
void emit_init (DTYPE tdtype, ISZ_T tconval, ISZ_T * addr, ISZ_T * repeat_cnt, ISZ_T loc_base, ISZ_T * i8cnt, int * ptrcnt, char ** cptr, bool is_char)
...
Definition at line 157 of file llassem_common.cpp.
References addr, ALIGN, alignment(), area, ASMFIL, assert, CONVAL2G, DBGBIT, STB::dbl0, DINIT_DATASECT, DINIT_FUNCCOUNT, DINIT_LABEL, DINIT_OFFSET, DINIT_PROC, dinit_read_string(), DINIT_REPEAT, DINIT_SECT, DINIT_STRING, DINIT_ZEROES, DT_CPTR, DTY, ERR_Severe, first_data, flg, gbl, interr(), is_empty_typedef(), ISZ_T, LLVM_LONGTERM_AREA, STB::n_base, FLG::omptarget, put_addr(), put_cmplx_n(), put_dcmplx_n(), put_i16(), put_i32(), put_i8(), put_ncharstring_n(), put_next_member(), put_r4(), put_r8(), put_skip(), put_string_n(), put_zeroes(), putval(), STB::quad0, repeat_cnt, size_of(), SPTR_NULL, stb, str, SymConval1, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, TY_SLOG, TY_WORD, write_proc_pointer(), and XBIT.
Referenced by process_dsrt().
gen_ptr_offset_val()
LL_Value * gen_ptr_offset_val (int offset, LL_Type * ret_type, const char * ptr_nm)
...
...
Parameters
offset the addend
ret_type the type of the pointer (LL_Type)
ptr_nm the identifier for the pointer
For example,
  getelementptr(i8* bitcast(<ret_type> <ptr_nm> to i8*), i32 <offset>)
The caller expects a string that is an i8*.
Definition at line 945 of file llassem_common.cpp.
Referenced by put_addr().
init_daz()
void init_daz (void)
...
...
Definition at line 1109 of file llassem_common.cpp.
init_flushz()
void init_flushz (void)
...
...
Definition at line 1102 of file llassem_common.cpp.
init_huge_tlb()
void init_huge_tlb (void)
...
Definition at line 1095 of file llassem_common.cpp.
init_ktrap()
void init_ktrap (void)
...
...
Definition at line 1116 of file llassem_common.cpp.
init_Mcuda_compiled()
void init_Mcuda_compiled (void)
...
mk_struct_for_llvm_init()
DTYPE mk_struct_for_llvm_init (const char * name, int size)
...
Definition at line 1041 of file llassem_common.cpp.
References cg_get_type(), DTY, getsymbol(), MXIDLN, name, NOSYM, process_ftn_dtype_struct(), and size.
Referenced by generate_struct_dtype(), get_ftn_static_lltype(), get_ftn_typedesc_dtype(), make_uplevel_arg_struct(), write_extern_inits(), and write_typedescs().
put_addr()
void put_addr (SPTR sptr, ISZ_T off, DTYPE dtype)
...
...
Print something along the lines of (LLVM version dependent):
  getelementptr (i8* bitcast (%struct$name* @getsname(sptr)
                 to i8*), i32 0) to i8*)
Definition at line 972 of file llassem_common.cpp.
References ASMFIL, cpu_llvm_module, LL_Value::data, LL_Type_::data_type, gen_ptr_offset_val(), getsname(), LL_Module::ir, ll_feature_explicit_gep_load_type, ll_get_pointer_type(), LL_PTR, LLTYPE, name, need_ptr(), off, process_sptr(), SNAME, and sptr.
Referenced by emit_init().
put_i32()
void put_i32 (int val)
...
Definition at line 829 of file llassem_common.cpp.
Referenced by emit_init().
put_int4()
void put_int4 (int val)
...
put_next_member()
char * put_next_member (char * ptr)
...
Definition at line 94 of file llassem_common.cpp.
Referenced by emit_init().
put_short()
void put_short (int val)
...
Definition at line 841 of file llassem_common.cpp.
put_skip()
ISZ_T put_skip (ISZ_T old, ISZ_T New, bool is_char)
...
Definition at line 109 of file llassem_common.cpp.
Referenced by emit_init().
put_string_n()
void put_string_n (const char * p, ISZ_T len, int size)
...
Definition at line 725 of file llassem_common.cpp.
Referenced by emit_init().