flang: llassem.h File Reference
llassem.h File Reference
#include "gbldefs.h"
#include "global.h"
#include "symtab.h"
#include "llutil.h"
Classes
struct DTLIST
struct uplevelpair
struct DSRT
struct AG
llassem global symbol table entries
struct AGB_t
storage allocation structure for assem's symtab
struct FPTRSYM
struct fptr_local_t
struct sec_t
Macros
#define STACK_CAN_BE_32_BYTE_ALIGNED (aux.curr_entry->flags & 0x200)
#define ENFORCE_32_BYTE_STACK_ALIGNMENT (aux.curr_entry->flags |= 0x400)
#define IS_STABS (XBIT(120, 0x20))
#define ASMFIL gbl.asmfil
#define MXIDLN (3 * MAXIDLEN + 10)
#define DSRTG(s) ((DSRT *)get_getitem_p(XREFLKG(s)))
#define DSRTP(s, v) XREFLKP(s, put_getitem_p(v))
#define GET_DSRT (DSRT *)getitem(2, sizeof(DSRT))
#define AG_HASHSZ 19
#define AG_SIZE(s) agb.s_base[s].size
#define AG_ALIGN(s) agb.s_base[s].align
#define AG_DSIZE(s) agb.s_base[s].dsize
#define AG_SYMLK(s) agb.s_base[s].symlk
#define AG_HASHLK(s) agb.s_base[s].hashlk
#define AG_NMPTR(s) agb.s_base[s].nmptr
#define AG_TYPENMPTR(s) agb.s_base[s].type_nmptr
#define AG_OLDNMPTR(s) agb.s_base[s].old_nmptr
#define AG_TYPEDESC(s) agb.s_base[s].typedesc /* Boolean */
#define AG_STYPE(s) agb.s_base[s].stype
#define AG_RET_LLTYPE(s) agb.s_base[s].ret_lltype
#define AG_LLTYPE(s) agb.s_base[s].lltype
#define AG_DTYPE(s) agb.s_base[s].dtype
#define AG_DTYPESC(s) agb.s_base[s].dtypesc
#define AG_SC(s) agb.s_base[s].sc /* Storage class */
#define AG_ALLOC(s) agb.s_base[s].alloc
#define AG_REF(s) agb.s_base[s].ref
#define AG_DEFD(s) agb.s_base[s].defd
#define AG_DEVICE(s) agb.s_base[s].device
#define AG_ISMOD(s) agb.s_base[s].ismod
#define AG_ISTLS(s) agb.s_base[s].istls
#define AG_NEEDMOD(s) agb.s_base[s].needmod
#define AG_ISCTOR(s) agb.s_base[s].ctor
#define AG_ISIFACE(s) agb.s_base[s].iface
#define AG_FINAL(s) agb.s_base[s].final
#define AG_UPLEVEL_AVL(s) agb.s_base[s].uplevel_avl
#define AG_UPLEVEL_SZ(s) agb.s_base[s].uplevel_sz
#define AG_UPLEVELPTR(s) agb.s_base[s].uplist
#define AG_UPLEVEL_OLD(s, i) agb.s_base[s].uplist[i].oldsptr
#define AG_UPLEVEL_NEW(s, i) agb.s_base[s].uplist[i].newsptr
#define AG_UPLEVEL_MEM(s, i) agb.s_base[s].uplist[i].newmem
#define AG_DLL(s) agb.s_base[s].dll
#define AG_NAME(s) agb.n_base + agb.s_base[s].nmptr
#define AG_TYPENAME(s) agb.n_base + agb.s_base[s].type_nmptr
#define AG_OLDNAME(s) agb.n_base + agb.s_base[s].old_nmptr
#define AG_ARGDTLIST(s) agb.s_base[s].argdtlist
#define AG_ARGDTLIST_LENGTH(s) agb.s_base[s].n_argdtlist
#define AG_ARGDTLIST_IS_VALID(s) agb.s_base[s].argdtlist_is_set
#define AG_OBJTODBGLIST(s) agb.s_base[s].cmblk_mem_mdnode_list
#define AG_CMBLKINITDATA(s) agb.s_base[s].cmblk_init_data
#define FPTR_HASHLK(s) fptr_local.s_base[s].hashlk
#define FPTR_IFACENMPTR(s) fptr_local.s_base[s].ifacenmptr
#define FPTR_IFACENM(s) fptr_local.n_base + fptr_local.s_base[s].ifacenmptr
#define FPTR_NMPTR(s) fptr_local.s_base[s].nmptr
#define FPTR_NAME(s) fptr_local.n_base + fptr_local.s_base[s].nmptr
#define FPTR_SYMLK(s) fptr_local.s_base[s].symlk
#define DIR_LONG_SIZE 32
#define MAXARGLEN 256
#define llassem_end_func(arg1, arg2) lldbg_function_end(arg1, arg2)
Typedefs
typedef struct DTLIST DTLIST
typedef struct uplevelpair UPLEVEL_PAIR
typedef struct DSRT DSRT
typedef struct AGB_t AGB_t
storage allocation structure for assem's symtab
typedef struct fptr_local_t fptr_local_t
Functions
char * get_local_overlap_var (void)
...
char * put_next_member (char *ptr)
ISZ_T put_skip (ISZ_T old, ISZ_T New, bool is_char)
LL_Value * gen_ptr_offset_val (int, LL_Type *, const char *)
Generate an expression to add an offset to a ptr.
void put_i32 (int)
void put_string_n (const char *, ISZ_T, int)
void put_short (int)
void put_int4 (INT)
void ll_override_type_string (LL_Type *llt, const char *str)
int alignment (DTYPE)
...
int add_member_for_llvm (int, int, DTYPE, ISZ_T)
LL_Type * update_llvm_typedef (DTYPE dtype, int sptr, int rank)
int llvm_get_unique_sym (void)
void align_func (void)
void put_global (char *name)
void put_func_name (int sptr)
void put_type (int sptr)
void init_huge_tlb (void)
void init_flushz (void)
Add the constructor responsible for -Mflushz.
void init_daz (void)
Add the constructor responsible for -Mdaz.
void init_ktrap (void)
Add the constructor responsible for -Ktrap.
ISZ_T get_socptr_offset (int)
...
LL_Type * make_generic_dummy_lltype (void)
...
LL_Type * get_local_overlap_vartype (void)
...
bool get_byval_from_argdtlist (DTLIST *argdtlist)
...
bool has_typedef_ag (int gblsym)
...
bool is_llvmag_entry (int gblsym)
...
bool is_llvmag_iface (int gblsym)
...
bool is_typedesc_defd (SPTR sptr)
...
char * getaddrdebug (SPTR sptr)
...
char * get_ag_name (int gblsym)
...
char * get_ag_typename (int gblsym)
...
DTLIST * get_argdtlist (int gblsym)
...
char * getextfuncname (SPTR sptr)
return external name for procedure
char * get_llvm_name (SPTR sptr)
...
char * get_main_progname (void)
...
DTLIST * get_next_argdtlist (DTLIST *argdtlist)
...
char * getsname (SPTR sptr)
...
char * get_string_constant (int sptr)
...
DTYPE get_ftn_typedesc_dtype (SPTR sptr)
...
int add_ag_typename (int gblsym, const char *typeName)
...
SPTR find_ag (const char *ag_name)
...
int find_funcptr_name (SPTR sptr)
...
int get_ag_argdtlist_length (int gblsym)
...
SPTR get_ag (SPTR sptr)
...
int get_bss_addr (void)
...
SPTR get_dummy_ag (SPTR sptr)
...
int get_hollerith_size (int sptr)
...
SPTR get_intrin_ag (char *ag_name, DTYPE dtype)
...
SPTR get_llvm_funcptr_ag (SPTR sptr, const char *ag_name)
...
int get_private_size (void)
...
SPTR get_sptr_from_argdtlist (DTLIST *argdtlist)
...
int get_sptr_uplevel_address (int sptr)
...
int get_stack_size (void)
...
SPTR get_typedef_ag (const char *ag_name, const char *typeName)
...
int get_uplevel_address_size (void)
...
int has_valid_ag_argdtlist (int gblsym)
...
int is_cache_aligned (SPTR syma)
determine if the address represented by syma, an address constant, is cache aligned.
int ll_shallow_copy_uplevel (SPTR hostsptr, SPTR olsptr)
...
SPTR local_funcptr_sptr_to_gblsym (SPTR sptr)
DTYPE make_uplevel_arg_struct (void)
...
int runtime_32_byte_alignment (SPTR acon_sptr)
the 32-byte alignment of the address constant acon_sptr
int runtime_alignment (SPTR syma)
determine the alignment of the address represented by syma, an address constant, within a cache-aligned container
LL_ObjToDbgList ** llassem_get_objtodbg_list (SPTR sptr)
...
LL_Type * get_ag_lltype (int gblsym)
...
LL_Type * get_ag_return_lltype (int gblsym)
...
LL_Type * get_lltype_from_argdtlist (DTLIST *argdtlist)
...
unsigned align_of_var (SPTR sptr)
...
void addag_llvm_argdtlist (SPTR gblsym, int arg_num, SPTR arg_sptr, LL_Type *lltype)
void add_aguplevel_oldsptr (void)
...
void _add_llvm_uplevel_symbol (int oldsptr)
...
void add_uplevel_to_host (int *ptr, int cnt)
...
void arg_is_refd (int sptr)
...
void assem_begin_func (SPTR sptr)
...
void assemble_end (void)
...
void assemble_init (int argc, char *argv[], const char *cmdline)
...
void assemble (void)
...
void assem_data (void)
...
void assem_dinit (void)
...
void assem_emit_align (int n)
...
void assem_emit_file_line (int findex, int lineno)
...
void assem_emit_line (int findex, int lineno)
...
void assem_end (void)
...
void assem_init (void)
...
void assem_put_linux_trace (int sptr)
...
void create_static_base (int num)
...
void create_static_name (char *name, int usestatic, int num)
...
void deleteag_llvm_argdtlist (int gblsym)
...
void fix_equiv_locals (SPTR loc_list, ISZ_T loc_addr)
...
void fix_equiv_statics (SPTR loc_list, ISZ_T loc_addr, bool dinitflg)
...
void fix_private_sym (int sptr)
...
void _fixup_llvm_uplevel_symbol (void)
...
void hostsym_is_refd (SPTR sptr)
...
void llvm_funcptr_store (SPTR sptr, char *ag_name)
...
void load_uplevel_addresses (SPTR display_temp)
...
void put_fstr (SPTR sptr, int add_null)
...
void put_section (int sect)
...
void set_ag_argdtlist_is_valid (int gblsym)
...
void set_ag_lltype (int gblsym, LL_Type *llt)
...
void set_ag_return_lltype (int gblsym, LL_Type *llt)
...
void set_bss_addr (int size)
...
void set_llvmag_entry (int gblsym)
...
void set_llvm_iface_oldname (int gblsym, char *nm)
...
void set_private_size (ISZ_T sz)
...
void sym_is_refd (SPTR sptr)
...
void write_libomtparget (void)
Writes libomptarget related initialization.
Variables
AGB_t agb
fptr_local_t fptr_local
DSRT * lcl_inits
DSRT * section_inits
DSRT * extern_inits
char static_name [MXIDLN]
int first_data
int ag_cmblks
int ag_procs
int ag_other
int ag_global
int ag_typedef
int ag_static
int ag_intrin
int ag_local
int ag_funcptr
Macro Definition Documentation
AG_ALIGN
#define AG_ALIGN (s) agb.s_base[s].align
Definition at line 81 of file llassem.h.
AG_ALLOC
#define AG_ALLOC (s) agb.s_base[s].alloc
Definition at line 95 of file llassem.h.
AG_ARGDTLIST
#define AG_ARGDTLIST (s) agb.s_base[s].argdtlist
Definition at line 115 of file llassem.h.
AG_ARGDTLIST_IS_VALID
#define AG_ARGDTLIST_IS_VALID (s) agb.s_base[s].argdtlist_is_set
Definition at line 117 of file llassem.h.
AG_ARGDTLIST_LENGTH
#define AG_ARGDTLIST_LENGTH (s) agb.s_base[s].n_argdtlist
Definition at line 116 of file llassem.h.
AG_CMBLKINITDATA
#define AG_CMBLKINITDATA (s) agb.s_base[s].cmblk_init_data
Definition at line 119 of file llassem.h.
AG_DEFD
#define AG_DEFD (s) agb.s_base[s].defd
Definition at line 97 of file llassem.h.
AG_DEVICE
#define AG_DEVICE (s) agb.s_base[s].device
Definition at line 98 of file llassem.h.
AG_DLL
#define AG_DLL (s) agb.s_base[s].dll
Definition at line 111 of file llassem.h.
AG_DSIZE
#define AG_DSIZE (s) agb.s_base[s].dsize
Definition at line 82 of file llassem.h.
AG_DTYPE
#define AG_DTYPE (s) agb.s_base[s].dtype
Definition at line 92 of file llassem.h.
AG_DTYPESC
#define AG_DTYPESC (s) agb.s_base[s].dtypesc
Definition at line 93 of file llassem.h.
AG_FINAL
#define AG_FINAL (s) agb.s_base[s].final
Definition at line 104 of file llassem.h.
AG_HASHLK
#define AG_HASHLK (s) agb.s_base[s].hashlk
Definition at line 84 of file llassem.h.
AG_HASHSZ
#define AG_HASHSZ 19
Definition at line 79 of file llassem.h.
AG_ISCTOR
#define AG_ISCTOR (s) agb.s_base[s].ctor
Definition at line 102 of file llassem.h.
AG_ISIFACE
#define AG_ISIFACE (s) agb.s_base[s].iface
Definition at line 103 of file llassem.h.
AG_ISMOD
#define AG_ISMOD (s) agb.s_base[s].ismod
Definition at line 99 of file llassem.h.
AG_ISTLS
#define AG_ISTLS (s) agb.s_base[s].istls
Definition at line 100 of file llassem.h.
AG_LLTYPE
#define AG_LLTYPE (s) agb.s_base[s].lltype
Definition at line 91 of file llassem.h.
AG_NAME
#define AG_NAME (s) agb.n_base + agb.s_base[s].nmptr
Definition at line 112 of file llassem.h.
AG_NEEDMOD
#define AG_NEEDMOD (s) agb.s_base[s].needmod
Definition at line 101 of file llassem.h.
AG_NMPTR
#define AG_NMPTR (s) agb.s_base[s].nmptr
Definition at line 85 of file llassem.h.
AG_OBJTODBGLIST
#define AG_OBJTODBGLIST (s) agb.s_base[s].cmblk_mem_mdnode_list
Definition at line 118 of file llassem.h.
AG_OLDNAME
#define AG_OLDNAME (s) agb.n_base + agb.s_base[s].old_nmptr
Definition at line 114 of file llassem.h.
AG_OLDNMPTR
#define AG_OLDNMPTR (s) agb.s_base[s].old_nmptr
Definition at line 87 of file llassem.h.
AG_REF
#define AG_REF (s) agb.s_base[s].ref
Definition at line 96 of file llassem.h.
AG_RET_LLTYPE
#define AG_RET_LLTYPE (s) agb.s_base[s].ret_lltype
Definition at line 90 of file llassem.h.
AG_SC
#define AG_SC (s) agb.s_base[s].sc /* Storage class */
Definition at line 94 of file llassem.h.
AG_SIZE
#define AG_SIZE (s) agb.s_base[s].size
Definition at line 80 of file llassem.h.
AG_STYPE
#define AG_STYPE (s) agb.s_base[s].stype
Definition at line 89 of file llassem.h.
AG_SYMLK
#define AG_SYMLK (s) agb.s_base[s].symlk
Definition at line 83 of file llassem.h.
AG_TYPEDESC
#define AG_TYPEDESC (s) agb.s_base[s].typedesc /* Boolean */
Definition at line 88 of file llassem.h.
AG_TYPENAME
#define AG_TYPENAME (s) agb.n_base + agb.s_base[s].type_nmptr
Definition at line 113 of file llassem.h.
AG_TYPENMPTR
#define AG_TYPENMPTR (s) agb.s_base[s].type_nmptr
Definition at line 86 of file llassem.h.
AG_UPLEVEL_AVL
#define AG_UPLEVEL_AVL (s) agb.s_base[s].uplevel_avl
Definition at line 105 of file llassem.h.
AG_UPLEVEL_MEM
#define AG_UPLEVEL_MEM (s, i) agb.s_base[s].uplist[i].newmem
Definition at line 110 of file llassem.h.
AG_UPLEVEL_NEW
#define AG_UPLEVEL_NEW (s, i) agb.s_base[s].uplist[i].newsptr
Definition at line 109 of file llassem.h.
AG_UPLEVEL_OLD
#define AG_UPLEVEL_OLD (s, i) agb.s_base[s].uplist[i].oldsptr
Definition at line 108 of file llassem.h.
AG_UPLEVEL_SZ
#define AG_UPLEVEL_SZ (s) agb.s_base[s].uplevel_sz
Definition at line 106 of file llassem.h.
AG_UPLEVELPTR
#define AG_UPLEVELPTR (s) agb.s_base[s].uplist
Definition at line 107 of file llassem.h.
ASMFIL
#define ASMFIL gbl.asmfil
Definition at line 40 of file llassem.h.
DIR_LONG_SIZE
#define DIR_LONG_SIZE 32
Definition at line 248 of file llassem.h.
DSRTG
#define DSRTG (s) ((DSRT *)get_getitem_p(XREFLKG(s)))
Definition at line 72 of file llassem.h.
DSRTP
#define DSRTP (s, v) XREFLKP(s, put_getitem_p(v))
Definition at line 73 of file llassem.h.
ENFORCE_32_BYTE_STACK_ALIGNMENT
#define ENFORCE_32_BYTE_STACK_ALIGNMENT (aux.curr_entry->flags |= 0x400)
Definition at line 37 of file llassem.h.
FPTR_HASHLK
#define FPTR_HASHLK (s) fptr_local.s_base[s].hashlk
Definition at line 121 of file llassem.h.
FPTR_IFACENM
#define FPTR_IFACENM (s) fptr_local.n_base + fptr_local.s_base[s].ifacenmptr
Definition at line 123 of file llassem.h.
FPTR_IFACENMPTR
#define FPTR_IFACENMPTR (s) fptr_local.s_base[s].ifacenmptr
Definition at line 122 of file llassem.h.
FPTR_NAME
#define FPTR_NAME (s) fptr_local.n_base + fptr_local.s_base[s].nmptr
Definition at line 125 of file llassem.h.
FPTR_NMPTR
#define FPTR_NMPTR (s) fptr_local.s_base[s].nmptr
Definition at line 124 of file llassem.h.
FPTR_SYMLK
#define FPTR_SYMLK (s) fptr_local.s_base[s].symlk
Definition at line 126 of file llassem.h.
GET_DSRT
#define GET_DSRT (DSRT *)getitem(2, sizeof(DSRT))
Definition at line 75 of file llassem.h.
IS_STABS
#define IS_STABS (XBIT(120, 0x20))
Definition at line 39 of file llassem.h.
llassem_end_func
#define llassem_end_func (arg1, arg2) lldbg_function_end(arg1, arg2)
Definition at line 270 of file llassem.h.
MAXARGLEN
#define MAXARGLEN 256
Definition at line 251 of file llassem.h.
MXIDLN
#define MXIDLN (3 * MAXIDLEN + 10)
general length suitable for creating names from a symbol name during assembly, e.g., 1 for null, 3 for extra '_' , * 4 for ### with mscall
Definition at line 44 of file llassem.h.
STACK_CAN_BE_32_BYTE_ALIGNED
#define STACK_CAN_BE_32_BYTE_ALIGNED (aux.curr_entry->flags & 0x200)
Definition at line 36 of file llassem.h.
Typedef Documentation
AGB_t
typedef struct AGB_t AGB_t
storage allocation structure for assem's symtab
DSRT
typedef struct DSRT DSRT
structure to represent items being dinit'd – used to generate a sorted list of dinit items for a given common block or local variable.
DTLIST
typedef struct DTLIST DTLIST
fptr_local_t
typedef struct fptr_local_t fptr_local_t
storage for function pointer
UPLEVEL_PAIR
typedef struct uplevelpair UPLEVEL_PAIR
Function Documentation
_add_llvm_uplevel_symbol()
void _add_llvm_uplevel_symbol (int oldsptr)
...
Definition at line 5879 of file llassem.cpp.
References gbl, NEED, NEW, size, uplevelcnt, and upptr.
Referenced by add_llvm_uplevel_symbol().
_fixup_llvm_uplevel_symbol()
void _fixup_llvm_uplevel_symbol (void)
...
Definition at line 5757 of file llassem.cpp.
References AG_UPLEVEL_AVL, AG_UPLEVEL_NEW, AG_UPLEVEL_OLD, AG_UPLEVEL_SZ, AG_UPLEVELPTR, cnt, DTYG, find_ag(), FREE, gbl, get_ag_searchnm(), get_llvm_name(), getdumlen(), gethost_dumlen(), i, j, llvm_get_uplevel_newsptr(), NEED, NEW, uplevelpair::newsptr, NULL, uplevelpair::oldsptr, sptr, SPTR_NULL, ThisIsAnAccessBug(), TY_CHAR, and TY_NCHAR.
Referenced by fixup_llvm_uplevel_symbol().
add_ag_typename()
int add_ag_typename (int gblsym, const char * typeName)
...
Definition at line 5259 of file llassem.cpp.
References add_ag_name(), and AG_TYPENMPTR.
Referenced by assemble_init(), get_ag(), ll_process_routine_parameters(), and write_comm().
add_aguplevel_oldsptr()
void add_aguplevel_oldsptr (void)
...
Definition at line 5896 of file llassem.cpp.
References add_uplevel_to_host(), FREE, gbl, NULL, uplevelcnt, and upptr.
Referenced by process_stb_file().
add_member_for_llvm()
int add_member_for_llvm (int , int , DTYPE , ISZ_T)
Referenced by make_uplevel_arg_struct().
add_uplevel_to_host()
void add_uplevel_to_host (int * ptr, int cnt)
...
Definition at line 5667 of file llassem.cpp.
References AG_UPLEVEL_AVL, AG_UPLEVEL_SZ, AG_UPLEVELPTR, cnt, find_ag(), FREE, gbl, get_llvm_name(), i, j, NEW, and uplevelpair::oldsptr.
Referenced by add_aguplevel_oldsptr().
addag_llvm_argdtlist()
void addag_llvm_argdtlist (SPTR gblsym, int arg_num, SPTR arg_sptr, LL_Type * lltype)
If arg_num in [1-n] where 1 is the first argument passed and the function contains n arguments. If arg_num is 0, the function's return value.
Called by build_routine_parameters()
Definition at line 5383 of file llassem.cpp.
References AG_ARGDTLIST, AG_ARGDTLIST_IS_VALID, AG_ARGDTLIST_LENGTH, arg_num, assert, DTLIST::byval, ERR_Fatal, get_argdt(), DTLIST::lltype, NEW, NULL, DTLIST::sptr, and t.
Referenced by gen_ref_arg(), and ll_process_routine_parameters().
align_func()
void align_func (void)
align_of_var()
unsigned align_of_var (SPTR sptr)
...
...
Definition at line 4222 of file llassem.cpp.
References align_of(), DATA_ALIGN, DT_INT, flg, MIN_ALIGN_SIZE, PDALN_IS_DEFAULT, PDALNG, FLG::quad, sptr, and zsize_of().
Referenced by gen_name_private_sptr(), process_auto_sptr(), process_extern_variable_sptr(), and process_local_sptr().
alignment()
int alignment (DTYPE dtype)
...
Definition at line 1213 of file dtypeutl.c.
References alignment(), constrained, FLG::dalign, DTY, DTyAlgTyAlign, DTySeqTyElement, ERR_Severe, FLANG_FALLTHROUGH, flg, get_ty_kind(), interr(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, and XBIT.
Referenced by align_of(), align_struct_tmp(), align_unconstrained(), alignment(), alignment_of_var(), alignment_sym(), amd64_update_class(), do_equiv(), emit_init(), fix_equiv_locals(), fix_equiv_statics(), gen_va_arg(), get_hollerith_size(), get_struct_from_dsrt2(), handle_bindC_func_ret(), layout_struct_body(), ldst_instr_flags_from_dtype(), ll_abi_classify_arg_dtype(), lldbg_create_aggregate_members_type(), lldbg_create_aggregate_type_mdnode(), lldbg_create_array_type_mdnode(), lldbg_create_assumed_len_string_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_ftn_array_type_mdnode(), lldbg_create_member_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_create_string_type_mdnode(), lldbg_create_structure_type_mdnode(), lldbg_create_union_type_mdnode(), lldbg_create_vector_type_mdnode(), lldbg_emit_local_variable(), lldbg_emit_ptr_param_variable(), lldbg_emit_type(), llmp_task_add_loopvar(), llmp_task_add_private(), make_stmt(), make_uplevel_arg_struct(), read_init(), ref_pd(), and sym_is_refd().
arg_is_refd()
void arg_is_refd (int sptr)
...
...
It's assumed that the alignment and size requirements for each argument are those that are required for pointer-sized integer.
Definition at line 4186 of file llassem.cpp.
References arg, size, size_of(), and sptr.
Referenced by cp_memarg(), and sym_is_refd().
assem_begin_func()
void assem_begin_func (SPTR sptr)
...
...
Definition at line 958 of file llassem.cpp.
References gbl, get_ag(), and sptr.
assem_data()
void assem_data (void)
...
Definition at line 972 of file llassem.cpp.
Referenced by assemble().
assem_dinit()
void assem_dinit (void)
...
Definition at line 6005 of file llassem.cpp.
assem_emit_align()
void assem_emit_align (int n)
...
Definition at line 3009 of file llassem.cpp.
References align_dir_value(), ASMFIL, i, and n.
assem_emit_file_line()
void assem_emit_file_line (int findex, int lineno)
...
Definition at line 4440 of file llassem.cpp.
assem_emit_line()
void assem_emit_line (int findex, int lineno)
...
Definition at line 4435 of file llassem.cpp.
assem_end()
void assem_end (void)
...
Definition at line 1002 of file llassem.cpp.
Referenced by assemble().
assem_init()
void assem_init (void)
...
...
Called once per function. This init is called immediately before any processing is performed for a function.
Definition at line 858 of file llassem.cpp.
Referenced by assem_data(), and assemble().
assem_put_linux_trace()
void assem_put_linux_trace (int sptr)
...
Definition at line 967 of file llassem.cpp.
assemble()
void assemble (void)
...
Definition at line 27 of file assem.c.
References AG_STYPE, assem_data(), assem_end(), assem_init(), cg_llvm_init(), DBGBIT, find_ag(), gbl, get_ag(), get_ag_searchnm(), has_init, RU_BDATA, and write_module_as_subroutine().
Referenced by process_input().
assemble_end()
void assemble_end (void)
...
...
Guaranteed to be called only once per compilation
Definition at line 37 of file assem.c.
References AG_ALLOC, AG_CMBLKINITDATA, ag_cmblks, AG_DEFD, AG_DSIZE, AG_FINAL, ag_global, ag_intrin, AG_ISMOD, AG_ISTLS, AG_NAME, AG_OBJTODBGLIST, ag_other, AG_SC, AG_SIZE, AG_SYMLK, ag_typedef, AG_TYPEDESC, AG_TYPENAME, agb, ASMFIL, CACHE_ALIGN, cpu_llvm_module, MACHTYPE::feature, FEATURE_DAZ, find_ag(), FREE, gbl, get_typedef_ag(), i, init_daz(), init_flushz(), init_huge_tlb(), init_ktrap(), ISZ_T, llObjtodbgAtEnd(), llObjtodbgFirst(), llObjtodbgFree(), llObjtodbgGet(), llObjtodbgNext(), llvm_write_ctors(), mach, MXIDLN, AGB_t::n_base, name, NULL, print_dbg_line(), print_line(), AGB_t::s_base, sz, LL_Module::target_triple, tname, write_external_function_declarations(), and XBIT.
Referenced by fini(), and finish().
assemble_init()
void assemble_init (int argc, char * argv[], const char * cmdline)
...
...
Guaranteed to be called only once per compilation
Definition at line 443 of file llassem.cpp.
References add_ag_typename(), ag_cmblks, ag_ctors_cnt, ag_funcptr, ag_global, ag_other, ag_procs, ag_static, ag_typedef, agb, gbl, AGB_t::n_avl, AGB_t::n_base, AGB_t::n_size, NEW, AGB_t::s_avl, AGB_t::s_base, and AGB_t::s_size.
create_static_base()
void create_static_base (int num)
...
Definition at line 1563 of file lowersym.c.
References addnewsym(), bss_base, bss_name, bss_name_global, bss_name_initialized, create_static_name(), gbl, NOSYM, num, outer_bss_name, outer_static_name, sptr, SPTR_NULL, static_base, static_name, static_name_global, and static_name_initialized.
create_static_name()
void create_static_name (char * name, int usestatic, int num)
...
Definition at line 4678 of file llassem.cpp.
Referenced by create_static_base().
deleteag_llvm_argdtlist()
void deleteag_llvm_argdtlist (int gblsym)
...
Definition at line 5337 of file llassem.cpp.
References AG_ARGDTLIST, NULL, and t.
find_ag()
SPTR find_ag (const char * ag_name)
...
Definition at line 385 of file llassem.cpp.
References AG_HASHLK, AG_NAME, agb, AGB_t::hashtb, name_to_hash(), SPTR_NULL, and strlen().
Referenced by _fixup_llvm_uplevel_symbol(), add_uplevel_to_host(), assemble(), assemble_end(), begin_layout_desc(), generate_struct_dtype(), get_ag(), get_ftn_cbind_lltype(), get_ftn_cmblk_lltype(), get_ftn_typedesc_lltype(), get_intrin_ag(), get_llvm_funcptr_ag(), get_sptr_uplevel_address(), get_typedef_ag(), get_uplevel_address_size(), is_typedesc_defd(), ll_abi_from_call_site(), ll_convert_iface_sptr(), ll_process_routine_parameters(), ll_proto_key(), ll_shallow_copy_uplevel(), load_uplevel_addresses(), local_funcptr_sptr_to_gblsym(), make_uplevel_arg_struct(), process_ll_abi_func_ftn_mod(), put_ll_table_addr(), set_ag_ref(), write_comm(), write_extern_inits(), write_externs(), write_final_table(), write_parent_pointers(), write_statics(), write_typedescs(), and write_vft().
find_funcptr_name()
int find_funcptr_name (SPTR sptr)
...
Definition at line 5523 of file llassem.cpp.
References ERR_Fatal, FPTR_HASHLK, fptr_local, FPTR_NAME, get_llvm_name(), fptr_local_t::hashtb, interr(), len, MXIDLN, name_to_hash(), sptr, and strlen().
Referenced by llvm_funcptr_store(), and local_funcptr_sptr_to_gblsym().
fix_equiv_locals()
void fix_equiv_locals (SPTR loc_list, ISZ_T loc_addr)
...
...
Parameters
loc_list list of local symbols linked by SYMLK
loc_addr total size of the equivalenced locals
The equivalence processor assigns positive offsets to the local variables which appear in equivalence statements. Target addresses must be assigned using the offsets provided by the equivalence processor.
Definition at line 4348 of file llassem.cpp.
References ALIGN, alignment(), DT_DBLE, gbl, ISZ_T, and NOSYM.
fix_equiv_statics()
void fix_equiv_statics (SPTR loc_list, ISZ_T loc_addr, bool dinitflg)
...
Definition at line 4378 of file llassem.cpp.
References addr, ALIGN, alignment(), assert, bss_base, bss_name_global, DT_DBLE, ERR_Severe, gbl, ISZ_T, NOSYM, static_base, and static_name_global.
fix_private_sym()
void fix_private_sym (int sptr)
...
Definition at line 402 of file llassem.cpp.
References assert, ERR_Severe, and sptr.
Referenced by read_symbol().
gen_ptr_offset_val()
LL_Value * gen_ptr_offset_val (int offset, LL_Type * ret_type, const char * ptr_nm)
Generate an expression to add an offset to a ptr.
Parameters
offset the addend
ret_type the type of the pointer (LL_Type)
ptr_nm the identifier for the pointer
For example,
  getelementptr(i8* bitcast(<ret_type> <ptr_nm> to i8*), i32 <offset>)
The caller expects a string that is an i8*.
Definition at line 945 of file llassem_common.cpp.
References cpu_llvm_module, ll_create_int_type(), ll_create_value_from_type(), ll_get_const_bitcast(), ll_get_const_gep(), ll_get_pointer_type(), and offset.
get_ag()
SPTR get_ag (SPTR sptr)
...
Definition at line 3160 of file llassem.cpp.
References add_ag_typename(), AG_ALIGN, AG_ALLOC, ag_cmblks, AG_DEFD, AG_DEVICE, AG_DLL, AG_DSIZE, ag_global, AG_ISIFACE, AG_ISMOD, AG_NEEDMOD, ag_other, ag_procs, AG_REF, AG_SIZE, AG_STYPE, AG_SYMLK, AG_TYPEDESC, CNULL, CUDA_BUILTIN, CUDA_DEVICE, CUDA_GLOBAL, CUDAG, FLG::debug, DLLG, DTY, DTyInterface, ERR_Severe, error(), find_ag(), FLANG_FALLTHROUGH, flg, gbl, get_llvm_name(), get_main_progname(), global_sptr, interr(), ISZ_T, lldbg_create_cmblk_mem_mdnode_list(), llvm_set_unique_sym(), make_gblsym(), max_align(), max_cm_align, MXIDLN, PDALNG, RU_PROG, size, size_of(), size_of_sym(), sptr, SPTR_NULL, SYMNAME, and XBIT.
Referenced by assem_begin_func(), assemble(), get_ftn_typedesc_lltype(), is_typedesc_defd(), ll_process_routine_parameters(), write_comm(), write_extern_inits(), write_externs(), write_final_table(), and write_typedescs().
get_ag_argdtlist_length()
int get_ag_argdtlist_length (int gblsym)
...
Definition at line 5235 of file llassem.cpp.
References AG_ARGDTLIST_LENGTH.
Referenced by ll_convert_iface_sptr(), and process_ll_abi_func_ftn_mod().
get_ag_lltype()
LL_Type * get_ag_lltype (int gblsym)
...
Definition at line 3408 of file llassem.cpp.
References AG_LLTYPE, AG_NAME, ERR_Fatal, and interr().
Referenced by get_ftn_cbind_lltype(), get_ftn_cmblk_lltype(), get_ftn_static_lltype(), get_ftn_typedesc_lltype(), and ll_convert_iface_sptr().
get_ag_name()
char * get_ag_name (int gblsym)
...
Definition at line 5999 of file llassem.cpp.
References AG_NAME.
get_ag_return_lltype()
LL_Type * get_ag_return_lltype (int gblsym)
...
Definition at line 3428 of file llassem.cpp.
References AG_RET_LLTYPE, assert, and ERR_Fatal.
Referenced by process_ll_abi_func_ftn_mod().
get_ag_typename()
char * get_ag_typename (int gblsym)
...
Definition at line 5253 of file llassem.cpp.
References AG_TYPENAME.
get_argdtlist()
DTLIST * get_argdtlist (int gblsym)
...
Definition at line 5350 of file llassem.cpp.
References AG_ARGDTLIST, and NULL.
Referenced by ll_convert_iface_sptr(), and process_ll_abi_func_ftn_mod().
get_bss_addr()
int get_bss_addr (void)
...
Definition at line 304 of file assem.c.
References bss_addr, and gbl.
Referenced by lower_sym_header(), parser(), and stb_lower_sym_header().
get_byval_from_argdtlist()
bool get_byval_from_argdtlist (DTLIST * argdtlist)
...
Definition at line 5432 of file llassem.cpp.
References DTLIST::byval.
Referenced by process_ll_abi_func_ftn_mod().
get_dummy_ag()
SPTR get_dummy_ag (SPTR sptr)
...
Definition at line 5283 of file llassem.cpp.
References add_ag_local_name(), ag_local, agb_local, AGL_DTYPE, AGL_HASHLK, AGL_NMPTR, AGL_SYMLK, BZERO, find_local_ag(), get_llvm_name(), AGB_t::hashtb, name_to_hash(), NEED, AGB_t::s_avl, AGB_t::s_base, AGB_t::s_size, sptr, and strlen().
get_ftn_typedesc_dtype()
DTYPE get_ftn_typedesc_dtype (SPTR sptr)
...
Definition at line 507 of file llassem.cpp.
References getsname(), mk_struct_for_llvm_init(), and sptr.
Referenced by get_ftn_typedesc_lltype(), and make_gblsym().
get_hollerith_size()
int get_hollerith_size (int sptr)
...
Definition at line 3022 of file llassem.cpp.
References ALIGN, alignment(), DATA_ALIGN, DT_INT, DTyCharLength, flg, len, MIN_ALIGN_SIZE, FLG::quad, and sptr.
Referenced by get_ftn_hollerith_type(), and put_fstr().
get_intrin_ag()
SPTR get_intrin_ag (char * ag_name, DTYPE dtype)
...
Definition at line 5268 of file llassem.cpp.
References ag_intrin, AG_SYMLK, find_ag(), make_gblsym(), and SPTR_NULL.
get_lltype_from_argdtlist()
LL_Type * get_lltype_from_argdtlist (DTLIST * argdtlist)
...
Definition at line 5424 of file llassem.cpp.
References DTLIST::lltype, and NULL.
Referenced by ll_convert_iface_sptr(), and process_ll_abi_func_ftn_mod().
get_llvm_funcptr_ag()
SPTR get_llvm_funcptr_ag (SPTR sptr, const char * ag_name)
...
Definition at line 5317 of file llassem.cpp.
References AG_DEVICE, ag_funcptr, AG_ISIFACE, AG_SIZE, AG_SYMLK, find_ag(), make_gblsym(), and sptr.
Referenced by ll_abi_from_call_site(), ll_process_routine_parameters(), and process_ll_abi_func_ftn_mod().
get_llvm_name()
char * get_llvm_name (SPTR sptr)
...
...
Parameters
sptr The symbol
Returns
a name (as a possibly transient string)
NB: This may return a pointer to a global buffer, so a subsequent call can silently clobber the string returned.
Definition at line 4821 of file llassem.cpp.
References AG_NAME, bss_base, bss_name, bss_name_global, contained_bss_name, contained_static_name, CUDAG, FLG::dollar, DTY, ERR_Severe, extent_of(), FLANG_FALLTHROUGH, flg, gbl, get_altname(), getfuncname(), getsname(), global_sptr, interr(), m, MXIDLN, name, outer_bss_name, outer_static_name, p, q, RU_PROG, FLG::smp, sptr, static_base, static_name, static_name_global, SYMNAME, ULABPFX, upcase_name(), and XBIT.
Referenced by _fixup_llvm_uplevel_symbol(), add_uplevel_to_host(), assem_init(), build_routine_and_parameter_entries(), DeclareSPtrAsLocal(), dump_uplevel_sptr(), find_funcptr_name(), follow_sptr_hashlk(), gen_name_private_sptr(), get_ag(), get_ag_searchnm(), get_dummy_ag(), get_entret_arg_name(), get_ftn_cmblk_lltype(), get_ftn_func_name(), get_ftn_static_lltype(), get_llvm_ifacenm(), get_local_overlap_size(), get_master_entry_name(), get_uplevel_address_size(), ll_abi_from_call_site(), ll_convert_iface_sptr(), ll_process_routine_parameters(), ll_proto_add_sptr(), ll_proto_key(), ll_shallow_copy_uplevel(), lldbg_function_end(), llvm_funcptr_store(), make_arg_op(), make_uplevel_arg_struct(), print_entry_subroutine(), process_extern_function_sptr(), process_extern_variable_sptr(), process_formal_arguments(), process_label_sptr_c(), process_ll_abi_func_ftn_mod(), process_local_sptr(), process_sptr_offset(), process_static_sptr(), put_fstr(), put_kstr(), set_ag_ref(), write_comm(), write_externs(), write_final_table(), write_instructions(), write_module_as_subroutine(), write_parent_pointers(), write_profile_enter(), write_typedescs(), and write_vft().
get_local_overlap_var()
char * get_local_overlap_var (void)
...
Definition at line 790 of file ll_ftn.cpp.
References equiv_var.
Referenced by process_local_sptr().
get_local_overlap_vartype()
LL_Type * get_local_overlap_vartype (void)
...
Definition at line 796 of file ll_ftn.cpp.
References equiv_type.
Referenced by make_lltype_from_sptr().
get_main_progname()
char * get_main_progname (void)
...
Definition at line 3898 of file llassem.cpp.
References gbl, MXIDLN, name, SYMNAME, and XBIT.
Referenced by get_ag(), get_ag_searchnm(), and get_ftn_func_name().
get_next_argdtlist()
DTLIST * get_next_argdtlist (DTLIST * argdtlist)
...
Definition at line 5358 of file llassem.cpp.
References DTLIST::next, and NULL.
Referenced by get_argdt(), ll_convert_iface_sptr(), and process_ll_abi_func_ftn_mod().
get_private_size()
int get_private_size (void)
...
Definition at line 4553 of file llassem.cpp.
get_socptr_offset()
ISZ_T get_socptr_offset (int sptr)
...
Definition at line 834 of file ll_ftn.cpp.
References f90_equiv_sz, and sptr.
Referenced by variable_offset_in_aggregate().
get_sptr_from_argdtlist()
SPTR get_sptr_from_argdtlist (DTLIST * argdtlist)
...
Definition at line 5440 of file llassem.cpp.
References DTLIST::sptr, and SPTR_NULL.
Referenced by process_ll_abi_func_ftn_mod().
get_sptr_uplevel_address()
int get_sptr_uplevel_address (int sptr)
...
Definition at line 5972 of file llassem.cpp.
References AG_UPLEVEL_AVL, AG_UPLEVEL_MEM, AG_UPLEVEL_NEW, find_ag(), gbl, get_ag_searchnm(), i, and sptr.
Referenced by mk_charlen_address().
get_stack_size()
int get_stack_size (void)
...
Definition at line 4569 of file llassem.cpp.
References gbl, getsymbol(), and name.
get_string_constant()
char * get_string_constant (int sptr)
...
Definition at line 5155 of file llassem.cpp.
References c, getitem(), len, LLVM_LONGTERM_AREA, STB::n_base, name, NULL, size_of(), sptr, and stb.
get_typedef_ag()
SPTR get_typedef_ag (const char * ag_name, const char * typeName)
...
Definition at line 363 of file llassem.cpp.
References add_ag_name(), AG_STYPE, AG_SYMLK, ag_typedef, AG_TYPENMPTR, find_ag(), make_gblsym(), and SPTR_NULL.
Referenced by assemble_end(), begin_layout_desc(), generate_struct_dtype(), get_ftn_cbind_lltype(), get_ftn_cmblk_lltype(), get_ftn_static_lltype(), get_ftn_typedesc_lltype(), write_comm(), write_extern_inits(), write_final_table(), write_ftn_typedefs(), write_parent_pointers(), write_statics(), write_typedescs(), and write_vft().
get_uplevel_address_size()
int get_uplevel_address_size (void)
...
Definition at line 5734 of file llassem.cpp.
References AG_UPLEVEL_AVL, find_ag(), gbl, and get_llvm_name().
getaddrdebug()
char * getaddrdebug (SPTR sptr)
...
Definition at line 4462 of file llassem.cpp.
References bss_base, bss_name, bss_name_global, gbl, getsname(), outer_bss_name, outer_static_name, sptr, static_base, static_name, static_name_global, straddr(), straddrp(), and SYMNAME.
getextfuncname()
char * getextfuncname (SPTR sptr)
return external name for procedure
Definition at line 3474 of file llassem.cpp.
References FLG::dollar, flg, gbl, get_altname(), m, MXIDLN, name, p, q, RU_PROG, sptr, SYMNAME, and XBIT.
Referenced by getfuncname().
getsname()
char * getsname (SPTR sptr)
...
Definition at line 3589 of file llassem.cpp.
Referenced by begin_layout_desc(), get_ftn_typedesc_dtype(), get_llvm_name(), getaddrdebug(), getsname(), is_typedesc_defd(), write_consts(), write_extern_inits(), write_final_table(), write_layout_desc_entry(), write_statics(), write_typedescs(), and write_vft().
has_typedef_ag()
bool has_typedef_ag (int gblsym)
...
Definition at line 3395 of file llassem.cpp.
References AG_TYPENMPTR.
has_valid_ag_argdtlist()
int has_valid_ag_argdtlist (int gblsym)
...
Definition at line 5241 of file llassem.cpp.
References AG_ARGDTLIST_IS_VALID.
hostsym_is_refd()
void hostsym_is_refd (SPTR sptr)
...
For f90, the locals of a subprogram (the host) which contains internal procedures must be allocated before generating code for the contained procedures. At this time, the compiler does not know what and how host local variables are referenced by the contained procedures. If we don't allocate locals now, the cg may place local variables on the stack, and at least two problems occur when the only reference is from the internal procedure:
a host local is initialized.
a host local appears in a namelist group.
Definition at line 4094 of file llassem.cpp.
References assn_static_off(), assn_stkoff(), DT_PTR, ERR_Severe, ERR_Warning, flg, interr(), ISZ_T, FLG::recursive, size, size_of(), FLG::smp, sptr, and XBIT.
Referenced by upper_assign_addresses().
init_daz()
void init_daz (void)
Add the constructor responsible for -Mdaz.
Definition at line 1109 of file llassem_common.cpp.
References add_ctor().
Referenced by assemble_end().
init_flushz()
void init_flushz (void)
Add the constructor responsible for -Mflushz.
Definition at line 1102 of file llassem_common.cpp.
References add_ctor().
Referenced by assemble_end().
init_huge_tlb()
void init_huge_tlb (void)
Definition at line 1095 of file llassem_common.cpp.
References add_ctor().
Referenced by assemble_end().
init_ktrap()
void init_ktrap (void)
Add the constructor responsible for -Ktrap.
Definition at line 1116 of file llassem_common.cpp.
References add_ctor(), ASMFIL, flg, and FLG::x.
Referenced by assemble_end().
is_cache_aligned()
int is_cache_aligned (SPTR syma)
determine if the address represented by syma, an address constant, is cache aligned.
Definition at line 4670 of file llassem.cpp.
References runtime_alignment().
is_llvmag_entry()
bool is_llvmag_entry (int gblsym)
...
Definition at line 5448 of file llassem.cpp.
References AG_STYPE.
Referenced by ll_process_routine_parameters().
is_llvmag_iface()
bool is_llvmag_iface (int gblsym)
...
Definition at line 5464 of file llassem.cpp.
References AG_ISIFACE.
is_typedesc_defd()
bool is_typedesc_defd (SPTR sptr)
...
Definition at line 2648 of file llassem.cpp.
References AG_DEFD, find_ag(), get_ag(), getsname(), and sptr.
ll_override_type_string()
void ll_override_type_string (LL_Type * llt, const char * str)
Definition at line 3974 of file llutil.cpp.
References llutil_alloc(), str, and strlen().
Referenced by generate_struct_dtype().
ll_shallow_copy_uplevel()
int ll_shallow_copy_uplevel (SPTR hostsptr, SPTR olsptr)
...
Definition at line 5985 of file llassem.cpp.
References AG_UPLEVEL_AVL, AG_UPLEVELPTR, find_ag(), and get_llvm_name().
Referenced by ll_process_routine_parameters().
llassem_get_objtodbg_list()
LL_ObjToDbgList ** llassem_get_objtodbg_list (SPTR sptr)
...
...
Parameters
sptr the symbol (of an object)
Definition at line 4763 of file llassem.cpp.
References bss_dbg_list, DTY, extent_of(), gbl, NULL, sptr, and static_dbg_list.
Referenced by lldbg_emit_global_variable().
llvm_funcptr_store()
void llvm_funcptr_store (SPTR sptr, char * ag_name)
...
Definition at line 5582 of file llassem.cpp.
References add_ag_fptr_name(), BZERO, find_funcptr_name(), FPTR_HASHLK, FPTR_IFACENMPTR, fptr_local, FPTR_NMPTR, FPTR_SYMLK, get_llvm_name(), fptr_local_t::hashtb, MXIDLN, name_to_hash(), NEED, ptr_local, fptr_local_t::s_avl, fptr_local_t::s_base, fptr_local_t::s_size, sptr, and strlen().
Referenced by fix_llvm_fptriface().
llvm_get_unique_sym()
int llvm_get_unique_sym (void)
This symbol is used only for its name, if none is found, a unique name is generated.
Definition at line 292 of file outliner.cpp.
References llvmUniqueSym.
load_uplevel_addresses()
void load_uplevel_addresses (SPTR display_temp)
...
Definition at line 5907 of file llassem.cpp.
References ad3ili(), ad4ili(), ad_acon(), addnme(), AG_UPLEVEL_AVL, AG_UPLEVEL_NEW, AG_UPLEVEL_OLD, basenm, chk_block(), DTY, DTyAlgTyMember, find_ag(), gbl, get_ag_searchnm(), i, is_llvm_local_private(), make_uplevel_arg_struct(), mem(), mk_address(), MSZ_I8, NOSYM, NT_MEM, and NT_VAR.
Referenced by create_llvm_display_temp().
local_funcptr_sptr_to_gblsym()
SPTR local_funcptr_sptr_to_gblsym (SPTR sptr)
Return the AG number associated to the local sptr value: 1) Search local-fnptr-table of function pointers 2) Get the ag name from (1) 3) Get the gblsym using the ag name from (2) 4) Return the AG gblsym from (3)
Definition at line 5555 of file llassem.cpp.
References assert, ERR_Fatal, find_ag(), find_funcptr_name(), FPTR_IFACENM, and sptr.
Referenced by ll_convert_iface_sptr().
make_generic_dummy_lltype()
LL_Type * make_generic_dummy_lltype (void)
...
Definition at line 910 of file llutil.cpp.
References generic_dummy_dtype(), make_lltype_from_dtype(), and make_ptr_lltype().
Referenced by ll_process_routine_parameters(), print_entry_subroutine(), and process_formal_arguments().
make_uplevel_arg_struct()
DTYPE make_uplevel_arg_struct (void)
...
Definition at line 5612 of file llassem.cpp.
References add_member_for_llvm(), AG_UPLEVEL_AVL, AG_UPLEVEL_MEM, AG_UPLEVEL_NEW, AG_UPLEVEL_OLD, alignment(), DTyAlgTyTag, DTySetAlgTyAlign, DTySetAlgTySize, DTySetFst, find_ag(), gbl, get_ag_searchnm(), get_llvm_name(), i, ISZ_T, make_lltype_from_dtype(), mk_struct_for_llvm_init(), MXIDLN, name, NOSYM, size, size_of(), and tname.
Referenced by create_llvm_display_temp(), and load_uplevel_addresses().
put_fstr()
void put_fstr (SPTR sptr, int add_null)
...
Parameters
sptr is a Fortran character constant or Hollerith constant.
add_null is 1 if null character is added, otherwise 0.
Definition at line 3042 of file llassem.cpp.
References ASMFIL, char_type(), DTyCharLength, get_hollerith_size(), get_llvm_name(), len, STB::n_base, put_string_n(), sptr, and stb.
Referenced by write_consts().
put_func_name()
void put_func_name (int sptr)
put_global()
void put_global (char * name)
put_i32()
void put_i32 (int val)
Definition at line 829 of file llassem_common.cpp.
References ASMFIL, i, i32bit, and val.
put_int4()
void put_int4 (INT)
put_next_member()
char * put_next_member (char * ptr)
Definition at line 94 of file llassem_common.cpp.
References ASMFIL, and NULL.
Referenced by process_dsrt().
put_section()
void put_section (int sect)
...
Definition at line 3017 of file llassem.cpp.
put_short()
void put_short (int val)
Definition at line 841 of file llassem_common.cpp.
References ASMFIL, and val.
put_skip()
ISZ_T put_skip (ISZ_T old, ISZ_T New, bool is_char)
Definition at line 109 of file llassem_common.cpp.
References ASMFIL, assert, ERR_Severe, i, ISZ_T, s, and str.
Referenced by process_dsrt().
put_string_n()
void put_string_n (const char * p, ISZ_T len, int size)
Definition at line 725 of file llassem_common.cpp.
References ASMFIL, len, n, p, and size.
Referenced by put_fstr().
put_type()
void put_type (int sptr)
runtime_32_byte_alignment()
int runtime_32_byte_alignment (SPTR acon_sptr)
the 32-byte alignment of the address constant acon_sptr
Parameters
acon_sptr
Returns
the alignment or -1 if it's unknown.
Definition at line 4649 of file llassem.cpp.
References ALN, CONVAL2G, ENFORCE_32_BYTE_STACK_ALIGNMENT, STACK_CAN_BE_32_BYTE_ALIGNED, sym_is_refd(), and SymConval1.
runtime_alignment()
int runtime_alignment (SPTR syma)
determine the alignment of the address represented by syma, an address constant, within a cache-aligned container
Returns
-1 if unknown or the byte boundary of the address
For example, given a single precision quantity and a container which is 16-byte aligned the following values are possible:
0 aligned with the beginning of the container.
4 multiple of 4 bytes from the beginning of the container.
8 multiple of 8 bytes from the beginning of the container.
12 multiple of 12 bytes from the beginning of the container.
Definition at line 4608 of file llassem.cpp.
References ALN, CONVAL2G, DATA_ALIGN, offset, sptr, sym_is_refd(), and SymConval1.
Referenced by is_cache_aligned().
set_ag_argdtlist_is_valid()
void set_ag_argdtlist_is_valid (int gblsym)
...
Definition at line 5247 of file llassem.cpp.
References AG_ARGDTLIST_IS_VALID.
Referenced by ll_process_routine_parameters().
set_ag_lltype()
void set_ag_lltype (int gblsym, LL_Type * llt)
...
Definition at line 3401 of file llassem.cpp.
References AG_LLTYPE, assert, and ERR_Fatal.
Referenced by generate_struct_dtype(), get_ftn_cbind_lltype(), get_ftn_cmblk_lltype(), get_ftn_static_lltype(), get_ftn_typedesc_lltype(), ll_process_routine_parameters(), write_extern_inits(), and write_typedescs().
set_ag_return_lltype()
void set_ag_return_lltype (int gblsym, LL_Type * llt)
...
Definition at line 3421 of file llassem.cpp.
References AG_RET_LLTYPE, assert, and ERR_Fatal.
Referenced by ll_process_routine_parameters().
set_bss_addr()
void set_bss_addr (int size)
...
Definition at line 4596 of file llassem.cpp.
References gbl, and size.
set_llvm_iface_oldname()
void set_llvm_iface_oldname (int gblsym, char * nm)
...
Definition at line 5565 of file llassem.cpp.
References add_ag_name(), and AG_OLDNMPTR.
Referenced by ll_process_routine_parameters().
set_llvmag_entry()
void set_llvmag_entry (int gblsym)
...
Definition at line 5456 of file llassem.cpp.
References AG_STYPE.
Referenced by ll_process_routine_parameters().
set_private_size()
void set_private_size (ISZ_T sz)
...
...
Definition at line 4590 of file llassem.cpp.
References prvt, and sz.
Referenced by upper().
sym_is_refd()
void sym_is_refd (SPTR sptr)
...
Definition at line 3925 of file llassem.cpp.
Referenced by runtime_32_byte_alignment(), runtime_alignment(), and sym_is_refd().
update_llvm_typedef()
LL_Type * update_llvm_typedef (DTYPE dtype, int sptr, int rank)
write_libomtparget()
void write_libomtparget (void)
Writes libomptarget related initialization.
Referenced by schedule().
Variable Documentation
ag_cmblks
int ag_cmblks extern
Definition at line 51 of file llassem_common.cpp.
Referenced by assemble_end(), assemble_init(), and get_ag().
ag_funcptr
int ag_funcptr extern
Definition at line 59 of file llassem_common.cpp.
Referenced by assemble_init(), and get_llvm_funcptr_ag().
ag_global
int ag_global extern
Definition at line 54 of file llassem_common.cpp.
Referenced by assemble_end(), assemble_init(), and get_ag().
ag_intrin
int ag_intrin extern
Definition at line 57 of file llassem_common.cpp.
Referenced by assemble_end(), and get_intrin_ag().
ag_local
int ag_local extern
Definition at line 58 of file llassem_common.cpp.
Referenced by assem_end(), assem_init(), and get_dummy_ag().
ag_other
int ag_other extern
Definition at line 53 of file llassem_common.cpp.
Referenced by assemble_end(), assemble_init(), get_ag(), and write_comm().
ag_procs
int ag_procs extern
Definition at line 52 of file llassem_common.cpp.
Referenced by assemble_init(), and get_ag().
ag_static
int ag_static extern
Definition at line 56 of file llassem_common.cpp.
Referenced by assemble_init().
ag_typedef
int ag_typedef extern
Definition at line 55 of file llassem_common.cpp.
Referenced by assemble_end(), assemble_init(), and get_typedef_ag().
agb
AGB_t agb extern
Definition at line 44 of file llassem_common.cpp.
Referenced by add_ag_name(), assemble_end(), assemble_init(), dump_ag(), dump_allag(), find_ag(), and make_gblsym().
extern_inits
DSRT* extern_inits extern
Definition at line 48 of file llassem_common.cpp.
Referenced by dinits(), dump_all_dinits(), write_extern_inits(), and write_statics().
first_data
int first_data extern
Definition at line 50 of file llassem_common.cpp.
Referenced by emit_init(), get_struct_from_dsrt2(), process_dsrt(), and write_comm().
fptr_local
fptr_local_t fptr_local extern
Definition at line 43 of file llassem.cpp.
Referenced by add_ag_fptr_name(), assem_end(), assem_init(), find_funcptr_name(), and llvm_funcptr_store().
lcl_inits
DSRT* lcl_inits extern
Definition at line 46 of file llassem_common.cpp.
Referenced by dinits(), dump_all_dinits(), and write_statics().
section_inits
DSRT* section_inits extern
Definition at line 47 of file llassem_common.cpp.
Referenced by dinits(), dump_all_dinits(), and write_statics().
static_name
char static_name[MXIDLN] extern
Definition at line 49 of file llassem_common.cpp.
Referenced by assem_init(), create_static_base(), get_llvm_name(), getaddrdebug(), getsname(), and write_statics().