flang: llassem.cpp File Reference
llassem.cpp File Reference
#include "llassem.h"
#include "dinit.h"
#include "dtypeutl.h"
#include "dinitutl.h"
#include "exp_rte.h"
#include "exputil.h"
#include "syms.h"
#include "version.h"
#include "machreg.h"
#include "dbg_out.h"
#include "assem.h"
#include "fih.h"
#include "mach.h"
#include "ili.h"
#include "llutil.h"
#include "cgllvm.h"
#include "cgmain.h"
#include "cg.h"
#include "ll_write.h"
#include "ll_structure.h"
#include "lldebug.h"
#include "expand.h"
#include "outliner.h"
#include "upper.h"
#include "llassem_common.h"
#include "flang/ADT/hash.h"
#include "symfun.h"
Macros
#define AGL_SYMLK(s) agb_local.s_base[s].symlk
#define AGL_HASHLK(s) agb_local.s_base[s].hashlk
#define AGL_NMPTR(s) agb_local.s_base[s].nmptr
#define AGL_TYPENMPTR(s) agb_local.s_base[s].type_nmptr
#define AGL_ARGNMPTR(s) agb_local.s_base[s].farg_nmptr
#define AGL_DTYPE(s) agb_local.s_base[s].dtype
#define AGL_REF(s) agb_local.s_base[s].ref
#define AGL_NEEDMOD(s) agb_local.s_base[s].needmod
#define AGL_NAME(s) agb_local.n_base + agb_local.s_base[s].nmptr
#define AGL_TYPENAME(s) agb_local.n_base + agb_local.s_base[s].type_nmptr
#define AGL_ARGNAME(s) agb_local.n_base + agb_local.s_base[s].farg_nmptr
#define AGL_ARGDTLIST(s) agb_local.s_base.argdtlist
#define LAST_SEC 28
#define is_stabs() XBIT(120, 0x20)
#define ASMFIL gbl.asmfil
#define PRVT_FIRST 32 /* run-time needs 32 bytes for storage */
#define DATA_ALIGN 15
#define MIN_ALIGN_SIZE (DATA_ALIGN + 1) /* flg.quad mininum size */
#define CACHE_ALIGN 63
#define ALN_UNIT 64
#define ALN_MINSZ 128000
#define ALN_MAXADJ 4096
#define ALN_THRESH (ALN_MAXADJ / ALN_UNIT)
#define CHK_REALLOC(_buf, _total, _csz, _pad)
#define FINAL_TABLE_SZ 9
#define ALN(x, a) ((x)&a)
Functions
static void assn_stkoff (SPTR sptr, DTYPE dtype, ISZ_T size)
static void assn_static_off (SPTR sptr, DTYPE dtype, ISZ_T size)
static void write_consts (void)
static void write_comm (void)
static void write_statics (void)
static void write_bss (void)
static void write_externs (void)
static void write_typedescs (void)
static void write_extern_inits (void)
static void dinits (void)
Read thru Data Initialization File and ...
static bool llassem_struct_needs_cast (int sptr)
static void put_kstr (SPTR sptr, int add_null)
static void upcase_name (char *)
static char * write_ftn_type (LL_Type *, char *, int)
static void write_module_as_subroutine (void)
static DSRT * process_dsrt (DSRT *dsrtp, ISZ_T size, char *cptr, bool stop_at_sect, ISZ_T addr)
static char * get_struct_from_dsrt2 (SPTR sptr, DSRT *dsrtp, ISZ_T size, int *align8, bool stop_at_sect, ISZ_T addr, bool type_only)
Create a struct type from the DSRT list.
static char * get_struct_from_dsrt (SPTR sptr, DSRT *dsrtp, ISZ_T size, int *align8, bool stop_at_sect, ISZ_T addr)
void dump_all_dinits (void)
static INLINE bool is_BIGOBJ ()
static int name_to_hash (const char *ag_name, int len)
static int add_ag_name (const char *ag_name)
static int add_ag_local_name (char *ag_name)
static INLINE ISZ_T count_skip (ISZ_T old, ISZ_T New)
static SPTR make_gblsym (SPTR sptr, const char *ag_name)
static char * get_ag_searchnm (SPTR sptr)
SPTR get_typedef_ag (const char *ag_name, const char *typeName)
...
SPTR find_ag (const char *ag_name)
...
void fix_private_sym (int sptr)
...
void assemble (void)
...
void assemble_init (int argc, char *argv[], const char *cmdline)
Initialize assem for the source file.
static int generate_struct_dtype (int size, char *name, char *typed)
Creates a dtype struct and adds it to the AG table.
DTYPE get_ftn_typedesc_dtype (SPTR sptr)
...
void assem_init (void)
Initialize assem for a function.
void assem_begin_func (SPTR sptr)
Print directives and label for beginning of function.
void assem_put_linux_trace (int sptr)
...
void assem_data (void)
...
void assem_end (void)
...
void assemble_end (void)
Complete assem for the source file.
static char * get_altname (SPTR sptr)
get the altname string for the given sptr
static int has_final_members (int sptr, int visit_flag)
static int count_members (DTYPE dtype)
static void begin_layout_desc (SPTR sptr, DTYPE dtype)
static bool end_layout_desc (void)
If there were any entries in the layout descriptor, terminate with all-0 entry and return true.
static void write_layout_desc_entry (char tag, int offset, SPTR member, int length, SPTR sdsc)
Write an entry in the layout desc for this member.
static void write_layout_desc (DTYPE dtype, int offset)
static int count_parent_pointers (int parent, int level)
static void write_parent_pointers (int parent, int level)
static int build_final_table (DTYPE dtype, SPTR ft[FINAL_TABLE_SZ])
static int write_final_table (SPTR sptr, DTYPE dtype)
static int has_final_procedures (int sptr)
static int has_pending_final_procedures (SPTR sptr)
static int build_vft (DTYPE dtype, SPTR **vft)
static int write_vft (int sptr, DTYPE dtype)
static void put_ll_table_addr (const char *name, const char *suffix, bool is_struct, int n_elts, bool explicit_gep_type)
bool is_typedesc_defd (SPTR sptr)
...
static void dump_dinit_structure (DSRT *p)
static void dump_dinit_chain (const char *name, DSRT *p)
static void dump_common_chain (hash_key_t key, void *_)
static int align_dir_value (int b)
void assem_emit_align (int n)
...
void put_section (int sect)
...
int get_hollerith_size (int sptr)
...
void put_fstr (SPTR sptr, int add_null)
...
static int max_align (SPTR sptr)
static void dump_gblsym (int gblsym)
void dump_ag (void)
void dump_allag (void)
SPTR get_ag (SPTR sptr)
...
bool has_typedef_ag (int gblsym)
...
void set_ag_lltype (int gblsym, LL_Type *llt)
...
LL_Type * get_ag_lltype (int gblsym)
...
void set_ag_return_lltype (int gblsym, LL_Type *llt)
...
LL_Type * get_ag_return_lltype (int gblsym)
...
static SPTR find_local_ag (char *ag_name)
static int add_ag_fptr_name (char *ag_name)
char * getextfuncname (SPTR sptr)
return external name for procedure
static const char * getfuncname (SPTR sptr)
char * getsname (SPTR sptr)
...
char * get_main_progname (void)
...
static void set_ag_ref (SPTR sptr)
void sym_is_refd (SPTR sptr)
...
void hostsym_is_refd (SPTR sptr)
...
void arg_is_refd (int sptr)
Assign an address to a dummy argument which is allocated in the local area.
unsigned align_of_var (SPTR sptr)
Get the alignment in bytes of a symbol representing a variable.
void fix_equiv_locals (SPTR loc_list, ISZ_T loc_addr)
Makes adjustments to the list loc_list.
void fix_equiv_statics (SPTR loc_list, ISZ_T loc_addr, bool dinitflg)
...
void assem_emit_line (int findex, int lineno)
...
void assem_emit_file_line (int findex, int lineno)
...
static char * straddr (int sptr)
static char * straddrp (int sptr, char *bufptr)
char * getaddrdebug (SPTR sptr)
...
int get_private_size ()
...
int get_stack_size ()
...
void set_private_size (ISZ_T sz)
The F90 front-end may have allocated private variables - need to adjust the initial size of the private area.
void set_bss_addr (int size)
...
int get_bss_addr ()
...
int runtime_alignment (SPTR syma)
determine the alignment of the address represented by syma, an address constant, within a cache-aligned container
int runtime_32_byte_alignment (SPTR acon_sptr)
the 32-byte alignment of the address constant acon_sptr
int is_cache_aligned (SPTR syma)
determine if the address represented by syma, an address constant, is cache aligned.
void create_static_name (char *name, int usestatic, int num)
...
void create_static_base (int num)
...
LL_ObjToDbgList ** llassem_get_objtodbg_list (SPTR sptr)
Get the list to attach !dbg for the symbol sptr.
char * get_llvm_name (SPTR sptr)
Get the LLVM name of the symbol sptr.
char * get_string_constant (int sptr)
...
int get_ag_argdtlist_length (int gblsym)
...
int has_valid_ag_argdtlist (int gblsym)
...
void set_ag_argdtlist_is_valid (int gblsym)
...
char * get_ag_typename (int gblsym)
...
int add_ag_typename (int gblsym, const char *typeName)
...
SPTR get_intrin_ag (char *ag_name, DTYPE dtype)
...
SPTR get_dummy_ag (SPTR sptr)
...
SPTR get_llvm_funcptr_ag (SPTR sptr, const char *ag_name)
...
void deleteag_llvm_argdtlist (int gblsym)
...
DTLIST * get_argdtlist (int gblsym)
...
DTLIST * get_next_argdtlist (DTLIST *argdtlist)
...
static DTLIST * get_argdt (SPTR gblsym, int arg_num)
void addag_llvm_argdtlist (SPTR gblsym, int arg_num, SPTR arg_sptr, LL_Type *lltype)
LL_Type * get_lltype_from_argdtlist (DTLIST *argdtlist)
...
bool get_byval_from_argdtlist (DTLIST *argdtlist)
...
SPTR get_sptr_from_argdtlist (DTLIST *argdtlist)
...
bool is_llvmag_entry (int gblsym)
...
void set_llvmag_entry (int gblsym)
...
bool is_llvmag_iface (int gblsym)
...
int find_funcptr_name (SPTR sptr)
...
SPTR local_funcptr_sptr_to_gblsym (SPTR sptr)
void set_llvm_iface_oldname (int gblsym, char *nm)
...
void llvm_funcptr_store (SPTR sptr, char *ag_name)
...
DTYPE make_uplevel_arg_struct (void)
...
void add_uplevel_to_host (int *ptr, int cnt)
...
int get_uplevel_address_size ()
...
static INLINE TY_KIND ThisIsAnAccessBug (DTYPE dtype)
void _fixup_llvm_uplevel_symbol (void)
...
void dump_uplevel_sptr (int gblsym)
void _add_llvm_uplevel_symbol (int oldsptr)
...
void add_aguplevel_oldsptr (void)
...
void load_uplevel_addresses (SPTR display_temp)
...
int get_sptr_uplevel_address (int sptr)
...
int ll_shallow_copy_uplevel (SPTR hostsptr, SPTR olsptr)
...
char * get_ag_name (int gblsym)
...
void assem_dinit (void)
...
Variables
fptr_local_t fptr_local
static AGB_t agb_local
static const struct sec_t sections [LAST_SEC]
static hashset_t CommonBlockInits
char * comment_char
DINIT_REC * dsrtbase
DINIT_REC * dsrtend
DINIT_REC * dsrtfree
char * current_module
int current_debug_area
static int static_name_initialized = 0
static int static_name_global = 0
static SPTR static_base
static LL_ObjToDbgList * static_dbg_list
static int bss_name_initialized = 0
static int bss_name_global = 0
static SPTR bss_base
static char bss_name [MXIDLN]
static LL_ObjToDbgList * bss_dbg_list
static int ag_ctors_cnt = 0
static char outer_static_name [MXIDLN]
static char contained_static_name [MXIDLN]
static char outer_bss_name [MXIDLN]
static char contained_bss_name [MXIDLN]
int print_stab_lines = false
struct {
int addr
int sym_sz
} prvt = {PRVT_FIRST, 0}
static int max_cm_align = 15
static int ptr_local = 0
static int has_init = 0
static int global_sptr
static int stk_aln_n = 1
static int bss_aln_n = 1
struct {
SPTR sptr
int entries
int expected_entries
bool wrote_tname
const char * tname
} layout_desc = {SPTR_NULL, 0, 0, false, "%struct.ld.memtype"}
static char straddrbuf [20]
static char straddrpbuf [sizeof(bss_name)+11+2]
static int uplevelcnt = 0
static int * upptr = NULL
Detailed Description
LLVM backend routines. This backend is Fortran-specific.
Definition in file llassem.cpp.
Macro Definition Documentation
AGL_ARGDTLIST
#define AGL_ARGDTLIST (s) agb_local.s_base.argdtlist
Definition at line 58 of file llassem.cpp.
AGL_ARGNAME
#define AGL_ARGNAME (s) agb_local.n_base + agb_local.s_base[s].farg_nmptr
Definition at line 57 of file llassem.cpp.
AGL_ARGNMPTR
#define AGL_ARGNMPTR (s) agb_local.s_base[s].farg_nmptr
Definition at line 51 of file llassem.cpp.
AGL_DTYPE
#define AGL_DTYPE (s) agb_local.s_base[s].dtype
Definition at line 52 of file llassem.cpp.
AGL_HASHLK
#define AGL_HASHLK (s) agb_local.s_base[s].hashlk
Definition at line 48 of file llassem.cpp.
AGL_NAME
#define AGL_NAME (s) agb_local.n_base + agb_local.s_base[s].nmptr
Definition at line 55 of file llassem.cpp.
AGL_NEEDMOD
#define AGL_NEEDMOD (s) agb_local.s_base[s].needmod
Definition at line 54 of file llassem.cpp.
AGL_NMPTR
#define AGL_NMPTR (s) agb_local.s_base[s].nmptr
Definition at line 49 of file llassem.cpp.
AGL_REF
#define AGL_REF (s) agb_local.s_base[s].ref
Definition at line 53 of file llassem.cpp.
AGL_SYMLK
#define AGL_SYMLK (s) agb_local.s_base[s].symlk
Definition at line 47 of file llassem.cpp.
AGL_TYPENAME
#define AGL_TYPENAME (s) agb_local.n_base + agb_local.s_base[s].type_nmptr
Definition at line 56 of file llassem.cpp.
AGL_TYPENMPTR
#define AGL_TYPENMPTR (s) agb_local.s_base[s].type_nmptr
Definition at line 50 of file llassem.cpp.
ALN
#define ALN (x, a) ((x)&a)
ALN_MAXADJ
#define ALN_MAXADJ 4096
Definition at line 230 of file llassem.cpp.
ALN_MINSZ
#define ALN_MINSZ 128000
Definition at line 229 of file llassem.cpp.
ALN_THRESH
#define ALN_THRESH (ALN_MAXADJ / ALN_UNIT)
Definition at line 231 of file llassem.cpp.
ALN_UNIT
#define ALN_UNIT 64
Definition at line 227 of file llassem.cpp.
ASMFIL
#define ASMFIL gbl.asmfil
Definition at line 160 of file llassem.cpp.
CACHE_ALIGN
#define CACHE_ALIGN 63
Definition at line 226 of file llassem.cpp.
CHK_REALLOC
#define CHK_REALLOC (_buf, _total, _csz, _pad)
Value:
  do {                                             \
    if (strlen(_buf) >= _total) {                  \
      _total += (strlen(_buf) - _total) + _csz;    \
      asrt(strlen(_buf) < _total + _pad);          \
      _buf = (char *)realloc(_buf, _total + _pad); \
    }                                              \
  } while (0)
Definition at line 518 of file llassem.cpp.
DATA_ALIGN
#define DATA_ALIGN 15
Definition at line 198 of file llassem.cpp.
FINAL_TABLE_SZ
#define FINAL_TABLE_SZ 9
Definition at line 2098 of file llassem.cpp.
is_stabs
#define is_stabs () XBIT(120, 0x20)
Definition at line 158 of file llassem.cpp.
LAST_SEC
#define LAST_SEC 28
Definition at line 85 of file llassem.cpp.
MIN_ALIGN_SIZE
#define MIN_ALIGN_SIZE (DATA_ALIGN + 1) /* flg.quad mininum size */
Definition at line 199 of file llassem.cpp.
PRVT_FIRST
#define PRVT_FIRST 32 /* run-time needs 32 bytes for storage */
Definition at line 192 of file llassem.cpp.
Function Documentation
_add_llvm_uplevel_symbol()
void _add_llvm_uplevel_symbol (int oldsptr)
...
Definition at line 5879 of file llassem.cpp.
References gbl, NEED, NEW, size, uplevelcnt, and upptr.
Referenced by add_llvm_uplevel_symbol().
_fixup_llvm_uplevel_symbol()
void _fixup_llvm_uplevel_symbol (void)
...
Definition at line 5757 of file llassem.cpp.
References AG_UPLEVEL_AVL, AG_UPLEVEL_NEW, AG_UPLEVEL_OLD, AG_UPLEVEL_SZ, AG_UPLEVELPTR, cnt, DTYG, find_ag(), FREE, gbl, get_ag_searchnm(), get_llvm_name(), getdumlen(), gethost_dumlen(), i, j, llvm_get_uplevel_newsptr(), NEED, NEW, uplevelpair::newsptr, NULL, uplevelpair::oldsptr, sptr, SPTR_NULL, ThisIsAnAccessBug(), TY_CHAR, and TY_NCHAR.
Referenced by fixup_llvm_uplevel_symbol().
add_ag_fptr_name()
static int add_ag_fptr_name (char * ag_name) static
Definition at line 3447 of file llassem.cpp.
References fptr_local, i, len, fptr_local_t::n_avl, fptr_local_t::n_base, fptr_local_t::n_size, NEED, and strlen().
Referenced by llvm_funcptr_store().
add_ag_local_name()
static int add_ag_local_name (char * ag_name) static
Definition at line 284 of file llassem.cpp.
References agb_local, i, len, AGB_t::n_avl, AGB_t::n_base, AGB_t::n_size, NEED, and strlen().
Referenced by get_dummy_ag().
add_ag_name()
static int add_ag_name (const char * ag_name) static
Definition at line 260 of file llassem.cpp.
References agb, i, len, AGB_t::n_avl, AGB_t::n_base, AGB_t::n_size, NEED, and strlen().
Referenced by add_ag_typename(), assem_init(), get_typedef_ag(), make_gblsym(), set_llvm_iface_oldname(), and write_externs().
add_ag_typename()
int add_ag_typename (int gblsym, const char * typeName)
...
Definition at line 5259 of file llassem.cpp.
References add_ag_name(), and AG_TYPENMPTR.
Referenced by assemble_init(), get_ag(), ll_process_routine_parameters(), and write_comm().
add_aguplevel_oldsptr()
void add_aguplevel_oldsptr (void)
...
Definition at line 5896 of file llassem.cpp.
References add_uplevel_to_host(), FREE, gbl, NULL, uplevelcnt, and upptr.
Referenced by process_stb_file().
add_uplevel_to_host()
void add_uplevel_to_host (int * ptr, int cnt)
...
Definition at line 5667 of file llassem.cpp.
References AG_UPLEVEL_AVL, AG_UPLEVEL_SZ, AG_UPLEVELPTR, cnt, find_ag(), FREE, gbl, get_llvm_name(), i, j, NEW, and uplevelpair::oldsptr.
Referenced by add_aguplevel_oldsptr().
addag_llvm_argdtlist()
void addag_llvm_argdtlist (SPTR gblsym, int arg_num, SPTR arg_sptr, LL_Type * lltype)
If arg_num in [1-n] where 1 is the first argument passed and the function contains n arguments. If arg_num is 0, the function's return value.
Called by build_routine_parameters()
Definition at line 5383 of file llassem.cpp.
References AG_ARGDTLIST, AG_ARGDTLIST_IS_VALID, AG_ARGDTLIST_LENGTH, arg_num, assert, DTLIST::byval, ERR_Fatal, get_argdt(), DTLIST::lltype, NEW, NULL, DTLIST::sptr, and t.
Referenced by gen_ref_arg(), and ll_process_routine_parameters().
align_dir_value()
static int align_dir_value (int b) static
Definition at line 2996 of file llassem.cpp.
References b, i, j, and XBIT.
Referenced by assem_emit_align().
align_of_var()
unsigned align_of_var (SPTR sptr)
Get the alignment in bytes of a symbol representing a variable.
...
Definition at line 4222 of file llassem.cpp.
References align_of(), DATA_ALIGN, DT_INT, flg, MIN_ALIGN_SIZE, PDALN_IS_DEFAULT, PDALNG, FLG::quad, sptr, and zsize_of().
Referenced by gen_name_private_sptr(), process_auto_sptr(), process_extern_variable_sptr(), and process_local_sptr().
arg_is_refd()
void arg_is_refd (int sptr)
Assign an address to a dummy argument which is allocated in the local area.
...
It's assumed that the alignment and size requirements for each argument are those that are required for pointer-sized integer.
Definition at line 4186 of file llassem.cpp.
References arg, size, size_of(), and sptr.
Referenced by cp_memarg(), and sym_is_refd().
assem_begin_func()
void assem_begin_func (SPTR sptr)
Print directives and label for beginning of function.
...
Definition at line 958 of file llassem.cpp.
References gbl, get_ag(), and sptr.
assem_data()
void assem_data (void)
...
Definition at line 972 of file llassem.cpp.
References assem_init(), dinits(), write_bss(), write_comm(), write_consts(), write_extern_inits(), write_externs(), write_statics(), and write_typedescs().
Referenced by assemble(), and schedule().
assem_dinit()
void assem_dinit (void)
...
Definition at line 6005 of file llassem.cpp.
assem_emit_align()
void assem_emit_align (int n)
...
Definition at line 3009 of file llassem.cpp.
References align_dir_value(), ASMFIL, i, and n.
assem_emit_file_line()
void assem_emit_file_line (int findex, int lineno)
...
Definition at line 4440 of file llassem.cpp.
assem_emit_line()
void assem_emit_line (int findex, int lineno)
...
Definition at line 4435 of file llassem.cpp.
assem_end()
void assem_end (void)
...
Definition at line 1002 of file llassem.cpp.
References ag_local, agb_local, bss_aln_n, bss_base, bss_name_global, bss_name_initialized, dinit_end(), fptr_local, FREE, freearea(), has_init, AGB_t::n_avl, fptr_local_t::n_avl, AGB_t::n_base, fptr_local_t::n_base, AGB_t::n_size, fptr_local_t::n_size, NULL, ptr_local, reset_equiv_var(), reset_master_sptr(), AGB_t::s_avl, fptr_local_t::s_avl, AGB_t::s_base, fptr_local_t::s_base, AGB_t::s_size, fptr_local_t::s_size, SPTR_NULL, static_base, static_name_global, static_name_initialized, and stk_aln_n.
Referenced by assemble(), cg_llvm_fnend(), and schedule().
assem_init()
void assem_init (void)
Initialize assem for a function.
...
Called once per function. This init is called immediately before any processing is performed for a function.
Definition at line 858 of file llassem.cpp.
References add_ag_name(), AG_HASHSZ, ag_local, AG_SIZE, AG_TYPENMPTR, agb_local, bss_base, bss_name, bss_name_global, bss_name_initialized, BZERO, contained_bss_name, contained_static_name, DSRTG, fptr_local, gbl, generate_struct_dtype(), get_llvm_name(), get_struct_from_dsrt(), has_init, AGB_t::hashtb, fptr_local_t::hashtb, AGB_t::n_avl, fptr_local_t::n_avl, AGB_t::n_base, fptr_local_t::n_base, AGB_t::n_size, fptr_local_t::n_size, NEW, NOSYM, NULL, outer_bss_name, outer_static_name, ptr_local, AGB_t::s_avl, fptr_local_t::s_avl, AGB_t::s_base, fptr_local_t::s_base, AGB_t::s_size, fptr_local_t::s_size, sptr, SPTR_NULL, static_base, static_name, static_name_global, and static_name_initialized.
Referenced by assem_data(), assemble(), and cg_llvm_init().
assem_put_linux_trace()
void assem_put_linux_trace (int sptr)
...
Definition at line 967 of file llassem.cpp.
assemble()
void assemble (void)
...
Definition at line 412 of file llassem.cpp.
References AG_STYPE, assem_data(), assem_end(), assem_init(), cg_llvm_init(), DBGBIT, find_ag(), gbl, get_ag(), get_ag_searchnm(), has_init, RU_BDATA, and write_module_as_subroutine().
assemble_end()
void assemble_end (void)
Complete assem for the source file.
...
Guaranteed to be called only once per compilation
Definition at line 1120 of file llassem.cpp.
References AG_ALLOC, AG_CMBLKINITDATA, ag_cmblks, AG_DEFD, AG_DSIZE, AG_FINAL, ag_global, ag_intrin, AG_ISMOD, AG_ISTLS, AG_NAME, AG_OBJTODBGLIST, ag_other, AG_SC, AG_SIZE, AG_SYMLK, ag_typedef, AG_TYPEDESC, AG_TYPENAME, agb, ASMFIL, CACHE_ALIGN, cpu_llvm_module, MACHTYPE::feature, FEATURE_DAZ, find_ag(), FREE, gbl, get_typedef_ag(), i, init_daz(), init_flushz(), init_huge_tlb(), init_ktrap(), ISZ_T, llObjtodbgAtEnd(), llObjtodbgFirst(), llObjtodbgFree(), llObjtodbgGet(), llObjtodbgNext(), llvm_write_ctors(), mach, MXIDLN, AGB_t::n_base, name, NULL, print_dbg_line(), print_line(), AGB_t::s_base, sz, LL_Module::target_triple, tname, write_external_function_declarations(), and XBIT.
assemble_init()
void assemble_init (int argc, char * argv[], const char * cmdline)
Initialize assem for the source file.
...
Guaranteed to be called only once per compilation
Definition at line 443 of file llassem.cpp.
References add_ag_typename(), ag_cmblks, ag_ctors_cnt, ag_funcptr, ag_global, ag_other, ag_procs, ag_static, ag_typedef, agb, gbl, AGB_t::n_avl, AGB_t::n_base, AGB_t::n_size, NEW, AGB_t::s_avl, AGB_t::s_base, and AGB_t::s_size.
assn_static_off()
static void assn_static_off (SPTR sptr, DTYPE dtype, ISZ_T size) static
Definition at line 4282 of file llassem.cpp.
References a, addr, ALIGN, align_unconstrained(), ALN_MINSZ, ALN_THRESH, ALN_UNIT, bss_aln_n, bss_base, bss_name_global, CACHE_ALIGN, DATA_ALIGN, DBGBIT, DTY, flg, gbl, getprint(), ISZ_T, MIN_ALIGN_SIZE, FLG::quad, size, sptr, static_base, static_name_global, TY_CHAR, and XBIT.
Referenced by hostsym_is_refd(), and sym_is_refd().
assn_stkoff()
static void assn_stkoff (SPTR sptr, DTYPE dtype, ISZ_T size) static
Definition at line 4241 of file llassem.cpp.
References a, addr, ALIGN, ALIGN_AUTO, align_unconstrained(), ALN_MINSZ, ALN_THRESH, ALN_UNIT, CACHE_ALIGN, DATA_ALIGN, DBGBIT, flg, gbl, getprint(), ISZ_T, MIN_ALIGN_SIZE, FLG::quad, size, sptr, STACK_CAN_BE_32_BYTE_ALIGNED, stk_aln_n, and XBIT.
Referenced by hostsym_is_refd(), and sym_is_refd().
begin_layout_desc()
static void begin_layout_desc (SPTR sptr, DTYPE dtype) static
Definition at line 1879 of file llassem.cpp.
References AG_DEFD, ASMFIL, buf, count_members(), find_ag(), get_typedef_ag(), getsname(), is_BIGOBJ(), name, sptr, and SYMNAME.
Referenced by write_typedescs().
build_final_table()
static int build_final_table (DTYPE dtype, SPTR ft[FINAL_TABLE_SZ]) static
Definition at line 2101 of file llassem.cpp.
References DTyAlgTyMember, FINAL_TABLE_SZ, i, j, mem(), NOSYM, and SPTR_NULL.
Referenced by write_final_table().
build_vft()
static int build_vft (DTYPE dtype, SPTR ** vft) static
Definition at line 2230 of file llassem.cpp.
References buf, build_vft(), DTyAlgTyMember, FREE, NEW, NOSYM, offset, parent, sz, and tmp.
Referenced by build_vft(), and write_vft().
count_members()
static int count_members (DTYPE dtype) static
Definition at line 1856 of file llassem.cpp.
References count, count_members(), DTY, DTyAlgTyMember, has_final_members(), and NOSYM.
Referenced by begin_layout_desc(), and count_members().
count_parent_pointers()
static int count_parent_pointers (int parent, int level) static
Definition at line 2043 of file llassem.cpp.
References count_parent_pointers(), DTY, DTyAlgTyMember, level(), and parent.
Referenced by count_parent_pointers(), and write_typedescs().
count_skip()
static INLINE ISZ_T count_skip (ISZ_T old, ISZ_T New) static
Definition at line 309 of file llassem.cpp.
Referenced by get_struct_from_dsrt2().
create_static_base()
void create_static_base (int num)
...
Definition at line 4696 of file llassem.cpp.
References addnewsym(), bss_base, bss_name, bss_name_global, bss_name_initialized, create_static_name(), gbl, NOSYM, num, outer_bss_name, outer_static_name, saveblockname, sptr, SPTR_NULL, static_base, static_name, static_name_global, and static_name_initialized.
Referenced by upper().
create_static_name()
void create_static_name (char * name, int usestatic, int num)
...
Definition at line 4678 of file llassem.cpp.
References name, and num.
Referenced by create_static_base().
deleteag_llvm_argdtlist()
void deleteag_llvm_argdtlist (int gblsym)
...
Definition at line 5337 of file llassem.cpp.
References AG_ARGDTLIST, NULL, and t.
dinits()
static void dinits (void) static
Read thru Data Initialization File and ...
Definition at line 2727 of file llassem.cpp.
References assert, CNULL, CommonBlockInits, DATA_SEC, DDTG, DINIT_DATASECT, dinit_fskip(), dinit_ftell(), DINIT_FUNCCOUNT, DINIT_LOC, DINIT_OFFSET, dinit_read(), DINIT_SECT, DINIT_SLOC, DINIT_STRING, DSRTG, DSRTP, DTY, ERR_Severe, ERR_Warning, error(), extent_of(), extern_inits, DSRT::filepos, DSRT::func_count, gbl, GET_DSRT, hash_functions_direct, hashset_alloc(), hashset_clear(), hashset_replace(), INT2HKEY, is_zero_size_typedef(), ISZ_T, DSRT::ladd, lcl_inits, DSRT::next, NULL, DSRT::offset, p, prev, section_inits, DSRT::sectionindex, size_of(), sptr, DSRT::sptr, and SYMNAME.
Referenced by assem_data().
dump_ag()
void dump_ag (void)
Definition at line 3138 of file llassem.cpp.
References AG_HASHLK, agb, dump_gblsym(), i, and AGB_t::s_avl.
dump_all_dinits()
void dump_all_dinits (void)
Definition at line 2983 of file llassem.cpp.
References CommonBlockInits, dump_common_chain(), dump_dinit_chain(), extern_inits, gbl, hashset_iterate(), lcl_inits, NULL, and section_inits.
dump_allag()
void dump_allag (void)
Definition at line 3147 of file llassem.cpp.
References agb, dump_gblsym(), i, and AGB_t::s_avl.
dump_common_chain()
static void dump_common_chain (hash_key_t key, void * _) static
Definition at line 2973 of file llassem.cpp.
References DSRTG, dump_dinit_chain(), HKEY2INT, and sptr.
Referenced by dump_all_dinits().
dump_dinit_chain()
static void dump_dinit_chain (const char * name, DSRT * p) static
Definition at line 2962 of file llassem.cpp.
References dump_dinit_structure(), gbl, name, and p.
Referenced by dump_all_dinits(), and dump_common_chain().
dump_dinit_structure()
static void dump_dinit_structure (DSRT * p) static
Definition at line 2951 of file llassem.cpp.
References gbl, and p.
Referenced by dump_dinit_chain().
dump_gblsym()
static void dump_gblsym (int gblsym) static
Definition at line 3129 of file llassem.cpp.
References AG_NAME, AG_TYPEDESC, AG_TYPENAME, and AG_TYPENMPTR.
Referenced by dump_ag(), and dump_allag().
dump_uplevel_sptr()
void dump_uplevel_sptr (int gblsym)
Definition at line 5865 of file llassem.cpp.
References AG_UPLEVEL_AVL, AG_UPLEVEL_NEW, AG_UPLEVEL_OLD, get_llvm_name(), and i.
end_layout_desc()
static bool end_layout_desc (void) static
If there were any entries in the layout descriptor, terminate with all-0 entry and return true.
Definition at line 1920 of file llassem.cpp.
References ASMFIL, assert, ERR_Fatal, is_BIGOBJ(), and SPTR_NULL.
Referenced by write_typedescs().
find_ag()
SPTR find_ag (const char * ag_name)
...
Definition at line 385 of file llassem.cpp.
References AG_HASHLK, AG_NAME, agb, AGB_t::hashtb, name_to_hash(), SPTR_NULL, and strlen().
Referenced by _fixup_llvm_uplevel_symbol(), add_uplevel_to_host(), assemble(), assemble_end(), begin_layout_desc(), generate_struct_dtype(), get_ag(), get_ftn_cbind_lltype(), get_ftn_cmblk_lltype(), get_ftn_typedesc_lltype(), get_intrin_ag(), get_llvm_funcptr_ag(), get_sptr_uplevel_address(), get_typedef_ag(), get_uplevel_address_size(), is_typedesc_defd(), ll_abi_from_call_site(), ll_convert_iface_sptr(), ll_process_routine_parameters(), ll_proto_key(), ll_shallow_copy_uplevel(), load_uplevel_addresses(), local_funcptr_sptr_to_gblsym(), make_uplevel_arg_struct(), process_ll_abi_func_ftn_mod(), put_ll_table_addr(), set_ag_ref(), write_comm(), write_extern_inits(), write_externs(), write_final_table(), write_parent_pointers(), write_statics(), write_typedescs(), and write_vft().
find_funcptr_name()
int find_funcptr_name (SPTR sptr)
...
Definition at line 5523 of file llassem.cpp.
References ERR_Fatal, FPTR_HASHLK, fptr_local, FPTR_NAME, get_llvm_name(), fptr_local_t::hashtb, interr(), len, MXIDLN, name_to_hash(), sptr, and strlen().
Referenced by llvm_funcptr_store(), and local_funcptr_sptr_to_gblsym().
find_local_ag()
static SPTR find_local_ag (char * ag_name) static
Definition at line 3435 of file llassem.cpp.
References agb_local, AGL_HASHLK, AGL_NAME, AGB_t::hashtb, name_to_hash(), SPTR_NULL, and strlen().
Referenced by get_dummy_ag().
fix_equiv_locals()
void fix_equiv_locals (SPTR loc_list, ISZ_T loc_addr)
Makes adjustments to the list loc_list.
...
Parameters
loc_list list of local symbols linked by SYMLK
loc_addr total size of the equivalenced locals
The equivalence processor assigns positive offsets to the local variables which appear in equivalence statements. Target addresses must be assigned using the offsets provided by the equivalence processor.
Definition at line 4348 of file llassem.cpp.
References ALIGN, alignment(), DT_DBLE, gbl, ISZ_T, and NOSYM.
fix_equiv_statics()
void fix_equiv_statics (SPTR loc_list, ISZ_T loc_addr, bool dinitflg)
...
Definition at line 4378 of file llassem.cpp.
References addr, ALIGN, alignment(), assert, bss_base, bss_name_global, DT_DBLE, ERR_Severe, gbl, ISZ_T, NOSYM, static_base, and static_name_global.
fix_private_sym()
void fix_private_sym (int sptr)
...
Definition at line 402 of file llassem.cpp.
References assert, ERR_Severe, and sptr.
Referenced by read_symbol().
generate_struct_dtype()
static int generate_struct_dtype (int size, char * name, char * typed) static
Creates a dtype struct and adds it to the AG table.
Definition at line 471 of file llassem.cpp.
References AG_DTYPESC, find_ag(), gbl, get_ag_searchnm(), get_typedef_ag(), ll_override_type_string(), make_lltype_from_dtype(), mk_struct_for_llvm_init(), MXIDLN, name, set_ag_lltype(), and size.
Referenced by assem_init().
get_ag()
SPTR get_ag (SPTR sptr)
...
Definition at line 3160 of file llassem.cpp.
References add_ag_typename(), AG_ALIGN, AG_ALLOC, ag_cmblks, AG_DEFD, AG_DEVICE, AG_DLL, AG_DSIZE, ag_global, AG_ISIFACE, AG_ISMOD, AG_NEEDMOD, ag_other, ag_procs, AG_REF, AG_SIZE, AG_STYPE, AG_SYMLK, AG_TYPEDESC, CNULL, CUDA_BUILTIN, CUDA_DEVICE, CUDA_GLOBAL, CUDAG, FLG::debug, DLLG, DTY, DTyInterface, ERR_Severe, error(), find_ag(), FLANG_FALLTHROUGH, flg, gbl, get_llvm_name(), get_main_progname(), global_sptr, interr(), ISZ_T, lldbg_create_cmblk_mem_mdnode_list(), llvm_set_unique_sym(), make_gblsym(), max_align(), max_cm_align, MXIDLN, PDALNG, RU_PROG, size, size_of(), size_of_sym(), sptr, SPTR_NULL, SYMNAME, and XBIT.
Referenced by assem_begin_func(), assemble(), get_ftn_typedesc_lltype(), is_typedesc_defd(), ll_process_routine_parameters(), write_comm(), write_extern_inits(), write_externs(), write_final_table(), and write_typedescs().
get_ag_argdtlist_length()
int get_ag_argdtlist_length (int gblsym)
...
Definition at line 5235 of file llassem.cpp.
References AG_ARGDTLIST_LENGTH.
Referenced by ll_convert_iface_sptr(), and process_ll_abi_func_ftn_mod().
get_ag_lltype()
LL_Type * get_ag_lltype (int gblsym)
...
Definition at line 3408 of file llassem.cpp.
References AG_LLTYPE, AG_NAME, ERR_Fatal, and interr().
Referenced by get_ftn_cbind_lltype(), get_ftn_cmblk_lltype(), get_ftn_static_lltype(), get_ftn_typedesc_lltype(), and ll_convert_iface_sptr().
get_ag_name()
char * get_ag_name (int gblsym)
...
Definition at line 5999 of file llassem.cpp.
References AG_NAME.
get_ag_return_lltype()
LL_Type * get_ag_return_lltype (int gblsym)
...
Definition at line 3428 of file llassem.cpp.
References AG_RET_LLTYPE, assert, and ERR_Fatal.
Referenced by process_ll_abi_func_ftn_mod().
get_ag_searchnm()
static char * get_ag_searchnm (SPTR sptr) static
Definition at line 355 of file llassem.cpp.
References gbl, get_llvm_name(), get_main_progname(), RU_PROG, and sptr.
Referenced by _fixup_llvm_uplevel_symbol(), assemble(), generate_struct_dtype(), get_sptr_uplevel_address(), load_uplevel_addresses(), make_uplevel_arg_struct(), and write_typedescs().
get_ag_typename()
char * get_ag_typename (int gblsym)
...
Definition at line 5253 of file llassem.cpp.
References AG_TYPENAME.
get_altname()
static char * get_altname (SPTR sptr) static
get the altname string for the given sptr
Parameters
sptr the symbol
Definition at line 1532 of file llassem.cpp.
References DTyCharLength, len, MXIDLN, STB::n_base, name, sptr, ss, and stb.
Referenced by get_llvm_name(), getextfuncname(), and getsname().
get_argdt()
static DTLIST * get_argdt (SPTR gblsym, int arg_num) static
Definition at line 5369 of file llassem.cpp.
References AG_ARGDTLIST, arg, arg_num, get_next_argdtlist(), i, and NULL.
Referenced by addag_llvm_argdtlist().
get_argdtlist()
DTLIST * get_argdtlist (int gblsym)
...
Definition at line 5350 of file llassem.cpp.
References AG_ARGDTLIST, and NULL.
Referenced by ll_convert_iface_sptr(), and process_ll_abi_func_ftn_mod().
get_bss_addr()
int get_bss_addr (void)
...
Definition at line 4602 of file llassem.cpp.
References gbl.
get_byval_from_argdtlist()
bool get_byval_from_argdtlist (DTLIST * argdtlist)
...
Definition at line 5432 of file llassem.cpp.
References DTLIST::byval.
Referenced by process_ll_abi_func_ftn_mod().
get_dummy_ag()
SPTR get_dummy_ag (SPTR sptr)
...
Definition at line 5283 of file llassem.cpp.
References add_ag_local_name(), ag_local, agb_local, AGL_DTYPE, AGL_HASHLK, AGL_NMPTR, AGL_SYMLK, BZERO, find_local_ag(), get_llvm_name(), AGB_t::hashtb, name_to_hash(), NEED, AGB_t::s_avl, AGB_t::s_base, AGB_t::s_size, sptr, and strlen().
get_ftn_typedesc_dtype()
DTYPE get_ftn_typedesc_dtype (SPTR sptr)
...
Definition at line 507 of file llassem.cpp.
References getsname(), mk_struct_for_llvm_init(), and sptr.
Referenced by get_ftn_typedesc_lltype(), and make_gblsym().
get_hollerith_size()
int get_hollerith_size (int sptr)
...
Definition at line 3022 of file llassem.cpp.
References ALIGN, alignment(), DATA_ALIGN, DT_INT, DTyCharLength, flg, len, MIN_ALIGN_SIZE, FLG::quad, and sptr.
Referenced by get_ftn_hollerith_type(), and put_fstr().
get_intrin_ag()
SPTR get_intrin_ag (char * ag_name, DTYPE dtype)
...
Definition at line 5268 of file llassem.cpp.
References ag_intrin, AG_SYMLK, find_ag(), make_gblsym(), and SPTR_NULL.
get_lltype_from_argdtlist()
LL_Type * get_lltype_from_argdtlist (DTLIST * argdtlist)
...
Definition at line 5424 of file llassem.cpp.
References DTLIST::lltype, and NULL.
Referenced by ll_convert_iface_sptr(), and process_ll_abi_func_ftn_mod().
get_llvm_funcptr_ag()
SPTR get_llvm_funcptr_ag (SPTR sptr, const char * ag_name)
...
Definition at line 5317 of file llassem.cpp.
References AG_DEVICE, ag_funcptr, AG_ISIFACE, AG_SIZE, AG_SYMLK, find_ag(), make_gblsym(), and sptr.
Referenced by ll_abi_from_call_site(), ll_process_routine_parameters(), and process_ll_abi_func_ftn_mod().
get_llvm_name()
char * get_llvm_name (SPTR sptr)
Get the LLVM name of the symbol sptr.
...
Parameters
sptr The symbol
Returns
a name (as a possibly transient string)
NB: This may return a pointer to a global buffer, so a subsequent call can silently clobber the string returned.
Definition at line 4821 of file llassem.cpp.
References AG_NAME, bss_base, bss_name, bss_name_global, contained_bss_name, contained_static_name, CUDAG, FLG::dollar, DTY, ERR_Severe, extent_of(), FLANG_FALLTHROUGH, flg, gbl, get_altname(), getfuncname(), getsname(), global_sptr, interr(), m, MXIDLN, name, outer_bss_name, outer_static_name, p, q, RU_PROG, FLG::smp, sptr, static_base, static_name, static_name_global, SYMNAME, ULABPFX, upcase_name(), and XBIT.
Referenced by _fixup_llvm_uplevel_symbol(), add_uplevel_to_host(), assem_init(), build_routine_and_parameter_entries(), DeclareSPtrAsLocal(), dump_uplevel_sptr(), find_funcptr_name(), follow_sptr_hashlk(), gen_name_private_sptr(), get_ag(), get_ag_searchnm(), get_dummy_ag(), get_entret_arg_name(), get_ftn_cmblk_lltype(), get_ftn_func_name(), get_ftn_static_lltype(), get_llvm_ifacenm(), get_local_overlap_size(), get_master_entry_name(), get_uplevel_address_size(), ll_abi_from_call_site(), ll_convert_iface_sptr(), ll_process_routine_parameters(), ll_proto_add_sptr(), ll_proto_key(), ll_shallow_copy_uplevel(), lldbg_function_end(), llvm_funcptr_store(), make_arg_op(), make_uplevel_arg_struct(), print_entry_subroutine(), process_extern_function_sptr(), process_extern_variable_sptr(), process_formal_arguments(), process_label_sptr_c(), process_ll_abi_func_ftn_mod(), process_local_sptr(), process_sptr_offset(), process_static_sptr(), put_fstr(), put_kstr(), set_ag_ref(), write_comm(), write_externs(), write_final_table(), write_instructions(), write_module_as_subroutine(), write_parent_pointers(), write_profile_enter(), write_typedescs(), and write_vft().
get_main_progname()
char * get_main_progname (void)
...
Definition at line 3898 of file llassem.cpp.
References gbl, MXIDLN, name, SYMNAME, and XBIT.
Referenced by get_ag(), get_ag_searchnm(), and get_ftn_func_name().
get_next_argdtlist()
DTLIST * get_next_argdtlist (DTLIST * argdtlist)
...
Definition at line 5358 of file llassem.cpp.
References DTLIST::next, and NULL.
Referenced by get_argdt(), ll_convert_iface_sptr(), and process_ll_abi_func_ftn_mod().
get_private_size()
int get_private_size (void)
...
Definition at line 4553 of file llassem.cpp.
References gbl, getsymbol(), and name.
get_sptr_from_argdtlist()
SPTR get_sptr_from_argdtlist (DTLIST * argdtlist)
...
Definition at line 5440 of file llassem.cpp.
References DTLIST::sptr, and SPTR_NULL.
Referenced by process_ll_abi_func_ftn_mod().
get_sptr_uplevel_address()
int get_sptr_uplevel_address (int sptr)
...
Definition at line 5972 of file llassem.cpp.
References AG_UPLEVEL_AVL, AG_UPLEVEL_MEM, AG_UPLEVEL_NEW, find_ag(), gbl, get_ag_searchnm(), i, and sptr.
Referenced by mk_charlen_address().
get_stack_size()
int get_stack_size (void)
...
Definition at line 4569 of file llassem.cpp.
References gbl, getsymbol(), and name.
get_string_constant()
char * get_string_constant (int sptr)
...
Definition at line 5155 of file llassem.cpp.
References c, getitem(), len, LLVM_LONGTERM_AREA, STB::n_base, name, NULL, size_of(), sptr, and stb.
get_struct_from_dsrt()
static char * get_struct_from_dsrt (SPTR sptr, DSRT * dsrtp, ISZ_T size, int * align8, bool stop_at_sect, ISZ_T addr) static
Definition at line 844 of file llassem.cpp.
References addr, get_struct_from_dsrt2(), size, and sptr.
Referenced by assem_init(), write_comm(), write_extern_inits(), and write_statics().
get_struct_from_dsrt2()
static char * get_struct_from_dsrt2 (SPTR sptr, DSRT * dsrtp, ISZ_T size, int * align8, bool stop_at_sect, ISZ_T addr, bool type_only) static
Create a struct type from the DSRT list.
Parameters
sptr symbol
dsrtp head of DSRT list
size ?
align8 ? [output]
stop_at_sect When true then return immediately when a new section type is encountered on the list. This flag is only useful for processing a list of named sections (specifically 'section_inits').
addr ?
Returns
a string of the constructed type
The struct type is built as follows:
Combine all non-pointer together as an array of bytes,
Each pointer type emitted as ptr
All callers must call free() on the returned string.
Definition at line 546 of file llassem.cpp.
References addr, ALIGN, alignment(), assert, buf, CHK_REALLOC, CNULL, count_skip(), DATA_SEC, LL_Type_::data_type, DDTG, DINIT_DATASECT, dinit_fseek(), dinit_fskip(), DINIT_FUNCCOUNT, DINIT_LABEL, DINIT_LOC, DINIT_OFFSET, DINIT_PROC, dinit_read(), DINIT_REPEAT, DINIT_SECT, DINIT_SLOC, DINIT_STRING, DINIT_ZEROES, DT_CPTR, DTY, ERR_Fatal, ERR_Severe, ERR_Warning, error(), DSRT::filepos, first_data, DSRT::func_count, gbl, get_struct_from_dsrt2(), is_zero_size_typedef(), ISZ_T, LL_PTR, llassem_struct_needs_cast(), make_lltype_from_sptr(), malloc(), DSRT::next, NVIDIA_FATBIN_SEC, NVIDIA_OLDFATBIN_SEC, NVIDIA_RELFATBIN_SEC, offset, DSRT::offset, p, repeat_cnt, DSRT::sectionindex, size, size_of(), sptr, DSRT::sptr, SPTR_NULL, LL_Type_::str, LL_Type_::sub_types, and SYMNAME.
Referenced by get_struct_from_dsrt(), get_struct_from_dsrt2(), write_comm(), and write_statics().
get_typedef_ag()
SPTR get_typedef_ag (const char * ag_name, const char * typeName)
...
Definition at line 363 of file llassem.cpp.
References add_ag_name(), AG_STYPE, AG_SYMLK, ag_typedef, AG_TYPENMPTR, find_ag(), make_gblsym(), and SPTR_NULL.
Referenced by assemble_end(), begin_layout_desc(), generate_struct_dtype(), get_ftn_cbind_lltype(), get_ftn_cmblk_lltype(), get_ftn_static_lltype(), get_ftn_typedesc_lltype(), write_comm(), write_extern_inits(), write_final_table(), write_ftn_typedefs(), write_parent_pointers(), write_statics(), write_typedescs(), and write_vft().
get_uplevel_address_size()
int get_uplevel_address_size (void)
...
Definition at line 5734 of file llassem.cpp.
References AG_UPLEVEL_AVL, find_ag(), gbl, and get_llvm_name().
getaddrdebug()
char * getaddrdebug (SPTR sptr)
...
Definition at line 4462 of file llassem.cpp.
References bss_base, bss_name, bss_name_global, gbl, getsname(), outer_bss_name, outer_static_name, sptr, static_base, static_name, static_name_global, straddr(), straddrp(), and SYMNAME.
getextfuncname()
char * getextfuncname (SPTR sptr)
return external name for procedure
Definition at line 3474 of file llassem.cpp.
References FLG::dollar, flg, gbl, get_altname(), m, MXIDLN, name, p, q, RU_PROG, sptr, SYMNAME, and XBIT.
Referenced by getfuncname().
getfuncname()
static const char * getfuncname (SPTR sptr) static
Definition at line 3570 of file llassem.cpp.
References gbl, GBL_CURRFUNC, getextfuncname(), sptr, and SYMNAME.
Referenced by get_llvm_name(), and getsname().
getsname()
char * getsname (SPTR sptr)
...
Definition at line 3589 of file llassem.cpp.
References AG_NAME, bss_base, bss_name, bss_name_global, CUDAG, FLG::dollar, DTY, ERR_Severe, extent_of(), FLANG_FALLTHROUGH, flg, gbl, get_altname(), getfuncname(), getsname(), global_sptr, interr(), m, MXIDLN, name, outer_bss_name, outer_static_name, p, q, RU_PROG, FLG::smp, sptr, static_base, static_name, static_name_global, SYMNAME, ULABPFX, upcase_name(), and XBIT.
Referenced by begin_layout_desc(), get_ftn_typedesc_dtype(), get_llvm_name(), getaddrdebug(), getsname(), is_typedesc_defd(), write_consts(), write_extern_inits(), write_final_table(), write_layout_desc_entry(), write_statics(), write_typedescs(), and write_vft().
has_final_members()
static int has_final_members (int sptr, int visit_flag) static
Definition at line 1794 of file llassem.cpp.
References DTY, DTyAlgTyMember, DTySeqTyElement, FREE, has_final_members(), NEW, next, visit_list::next, NOSYM, prev, sptr, and visit_list.
Referenced by count_members(), has_final_members(), and write_layout_desc().
has_final_procedures()
static int has_final_procedures (int sptr) static
Definition at line 2181 of file llassem.cpp.
References DTyAlgTyMember, DTyArgType, len, mem(), name, NOSYM, sptr, strlen(), and SYMNAME.
Referenced by write_typedescs().
has_pending_final_procedures()
static int has_pending_final_procedures (SPTR sptr) static
Definition at line 2209 of file llassem.cpp.
References DTyAlgTyMember, DTyArgType, mem(), NOSYM, and sptr.
Referenced by write_typedescs().
has_typedef_ag()
bool has_typedef_ag (int gblsym)
...
Definition at line 3395 of file llassem.cpp.
References AG_TYPENMPTR.
has_valid_ag_argdtlist()
int has_valid_ag_argdtlist (int gblsym)
...
Definition at line 5241 of file llassem.cpp.
References AG_ARGDTLIST_IS_VALID.
hostsym_is_refd()
void hostsym_is_refd (SPTR sptr)
...
For f90, the locals of a subprogram (the host) which contains internal procedures must be allocated before generating code for the contained procedures. At this time, the compiler does not know what and how host local variables are referenced by the contained procedures. If we don't allocate locals now, the cg may place local variables on the stack, and at least two problems occur when the only reference is from the internal procedure:
a host local is initialized.
a host local appears in a namelist group.
Definition at line 4094 of file llassem.cpp.
References assn_static_off(), assn_stkoff(), DT_PTR, ERR_Severe, ERR_Warning, flg, interr(), ISZ_T, FLG::recursive, size, size_of(), FLG::smp, sptr, and XBIT.
Referenced by upper_assign_addresses().
is_BIGOBJ()
static INLINE bool is_BIGOBJ () static
Definition at line 247 of file llassem.cpp.
References XBIT.
Referenced by begin_layout_desc(), end_layout_desc(), and write_layout_desc_entry().
is_cache_aligned()
int is_cache_aligned (SPTR syma)
determine if the address represented by syma, an address constant, is cache aligned.
Definition at line 4670 of file llassem.cpp.
References runtime_alignment().
is_llvmag_entry()
bool is_llvmag_entry (int gblsym)
...
Definition at line 5448 of file llassem.cpp.
References AG_STYPE.
Referenced by ll_process_routine_parameters().
is_llvmag_iface()
bool is_llvmag_iface (int gblsym)
...
Definition at line 5464 of file llassem.cpp.
References AG_ISIFACE.
is_typedesc_defd()
bool is_typedesc_defd (SPTR sptr)
...
Definition at line 2648 of file llassem.cpp.
References AG_DEFD, find_ag(), get_ag(), getsname(), and sptr.
ll_shallow_copy_uplevel()
int ll_shallow_copy_uplevel (SPTR hostsptr, SPTR olsptr)
...
Definition at line 5985 of file llassem.cpp.
References AG_UPLEVEL_AVL, AG_UPLEVELPTR, find_ag(), and get_llvm_name().
Referenced by ll_process_routine_parameters().
llassem_get_objtodbg_list()
LL_ObjToDbgList ** llassem_get_objtodbg_list (SPTR sptr)
Get the list to attach !dbg for the symbol sptr.
...
Parameters
sptr the symbol (of an object)
Definition at line 4763 of file llassem.cpp.
References bss_dbg_list, DTY, extent_of(), gbl, NULL, sptr, and static_dbg_list.
Referenced by lldbg_emit_global_variable().
llassem_struct_needs_cast()
static bool llassem_struct_needs_cast (int sptr) static
Definition at line 513 of file llassem.cpp.
References sptr.
Referenced by get_struct_from_dsrt2(), and write_extern_inits().
llvm_funcptr_store()
void llvm_funcptr_store (SPTR sptr, char * ag_name)
...
Definition at line 5582 of file llassem.cpp.
References add_ag_fptr_name(), BZERO, find_funcptr_name(), FPTR_HASHLK, FPTR_IFACENMPTR, fptr_local, FPTR_NMPTR, FPTR_SYMLK, get_llvm_name(), fptr_local_t::hashtb, MXIDLN, name_to_hash(), NEED, ptr_local, fptr_local_t::s_avl, fptr_local_t::s_base, fptr_local_t::s_size, sptr, and strlen().
Referenced by fix_llvm_fptriface().
load_uplevel_addresses()
void load_uplevel_addresses (SPTR display_temp)
...
Definition at line 5907 of file llassem.cpp.
References ad3ili(), ad4ili(), ad_acon(), addnme(), AG_UPLEVEL_AVL, AG_UPLEVEL_NEW, AG_UPLEVEL_OLD, basenm, chk_block(), DTY, DTyAlgTyMember, find_ag(), gbl, get_ag_searchnm(), i, is_llvm_local_private(), make_uplevel_arg_struct(), mem(), mk_address(), MSZ_I8, NOSYM, NT_MEM, and NT_VAR.
Referenced by create_llvm_display_temp().
local_funcptr_sptr_to_gblsym()
SPTR local_funcptr_sptr_to_gblsym (SPTR sptr)
Return the AG number associated to the local sptr value: 1) Search local-fnptr-table of function pointers 2) Get the ag name from (1) 3) Get the gblsym using the ag name from (2) 4) Return the AG gblsym from (3)
Definition at line 5555 of file llassem.cpp.
References assert, ERR_Fatal, find_ag(), find_funcptr_name(), FPTR_IFACENM, and sptr.
Referenced by ll_convert_iface_sptr().
make_gblsym()
static SPTR make_gblsym (SPTR sptr, const char * ag_name) static
Definition at line 315 of file llassem.cpp.
References add_ag_name(), AG_DLL, AG_HASHLK, AG_LLTYPE, AG_NMPTR, AG_SC, AG_STYPE, agb, BZERO, FLG::debug, DLL_NONE, flg, get_ftn_typedesc_dtype(), get_return_type(), AGB_t::hashtb, lldbg_create_cmblk_mem_mdnode_list(), make_lltype_from_dtype(), make_lltype_from_sptr(), name_to_hash(), NEED, AGB_t::s_avl, AGB_t::s_base, AGB_t::s_size, sptr, and strlen().
Referenced by get_ag(), get_intrin_ag(), get_llvm_funcptr_ag(), get_typedef_ag(), and write_comm().
make_uplevel_arg_struct()
DTYPE make_uplevel_arg_struct (void)
...
Definition at line 5612 of file llassem.cpp.
References add_member_for_llvm(), AG_UPLEVEL_AVL, AG_UPLEVEL_MEM, AG_UPLEVEL_NEW, AG_UPLEVEL_OLD, alignment(), DTyAlgTyTag, DTySetAlgTyAlign, DTySetAlgTySize, DTySetFst, find_ag(), gbl, get_ag_searchnm(), get_llvm_name(), i, ISZ_T, make_lltype_from_dtype(), mk_struct_for_llvm_init(), MXIDLN, name, NOSYM, size, size_of(), and tname.
Referenced by create_llvm_display_temp(), and load_uplevel_addresses().
max_align()
static int max_align (SPTR sptr) static
Definition at line 3106 of file llassem.cpp.
References align_unconstrained(), DATA_ALIGN, ISZ_T, max_cm_align, MIN_ALIGN_SIZE, PDALN_IS_DEFAULT, PDALNG, size_of_sym(), sptr, and sz.
Referenced by get_ag().
name_to_hash()
static int name_to_hash (const char * ag_name, int len) static
Definition at line 253 of file llassem.cpp.
References AG_HASHSZ, and len.
Referenced by find_ag(), find_funcptr_name(), find_local_ag(), get_dummy_ag(), llvm_funcptr_store(), and make_gblsym().
process_dsrt()
static DSRT * process_dsrt (DSRT * dsrtp, ISZ_T size, char * cptr, bool stop_at_sect, ISZ_T addr) static
Definition at line 1280 of file llassem.cpp.
References addr, ASMFIL, CNULL, DATA_SEC, DBGBIT, DDTG, DINIT_DATASECT, dinit_fseek(), DINIT_LOC, dinit_read(), DINIT_SECT, DINIT_SLOC, DTY, DTyAlgTyTag, emit_init(), ERR_Warning, error(), DSRT::filepos, first_data, DSRT::func_count, gbl, is_zero_size_typedef(), ISZ_T, DSRT::next, offset, DSRT::offset, p, put_next_member(), put_skip(), repeat_cnt, DSRT::sectionindex, size, DSRT::sptr, SYMNAME, and TY_CHAR.
Referenced by write_comm(), write_extern_inits(), and write_statics().
put_fstr()
void put_fstr (SPTR sptr, int add_null)
...
Parameters
sptr is a Fortran character constant or Hollerith constant.
add_null is 1 if null character is added, otherwise 0.
Definition at line 3042 of file llassem.cpp.
References ASMFIL, char_type(), DTyCharLength, get_hollerith_size(), get_llvm_name(), len, STB::n_base, put_string_n(), sptr, and stb.
Referenced by write_consts().
put_kstr()
static void put_kstr (SPTR sptr, int add_null) static
Definition at line 3068 of file llassem.cpp.
References ASMFIL, assert, char_type(), DTY, DTyCharLength, ERR_Severe, get_llvm_name(), kanji_char(), len, STB::n_base, p, sptr, stb, SymConval1, TY_CHAR, and val.
Referenced by write_consts().
put_ll_table_addr()
static void put_ll_table_addr (const char * name, const char * suffix, bool is_struct, int n_elts, bool explicit_gep_type) static
Definition at line 2359 of file llassem.cpp.
References AG_NAME, ASMFIL, asrt, buf, find_ag(), name, and suffix.
Referenced by write_typedescs().
put_section()
void put_section (int sect)
...
Definition at line 3017 of file llassem.cpp.
runtime_32_byte_alignment()
int runtime_32_byte_alignment (SPTR acon_sptr)
the 32-byte alignment of the address constant acon_sptr
Parameters
acon_sptr
Returns
the alignment or -1 if it's unknown.
Definition at line 4649 of file llassem.cpp.
References ALN, CONVAL2G, ENFORCE_32_BYTE_STACK_ALIGNMENT, STACK_CAN_BE_32_BYTE_ALIGNED, sym_is_refd(), and SymConval1.
runtime_alignment()
int runtime_alignment (SPTR syma)
determine the alignment of the address represented by syma, an address constant, within a cache-aligned container
Returns
-1 if unknown or the byte boundary of the address
For example, given a single precision quantity and a container which is 16-byte aligned the following values are possible:
0 aligned with the beginning of the container.
4 multiple of 4 bytes from the beginning of the container.
8 multiple of 8 bytes from the beginning of the container.
12 multiple of 12 bytes from the beginning of the container.
Definition at line 4608 of file llassem.cpp.
References ALN, CONVAL2G, DATA_ALIGN, offset, sptr, sym_is_refd(), and SymConval1.
Referenced by is_cache_aligned().
set_ag_argdtlist_is_valid()
void set_ag_argdtlist_is_valid (int gblsym)
...
Definition at line 5247 of file llassem.cpp.
References AG_ARGDTLIST_IS_VALID.
Referenced by ll_process_routine_parameters().
set_ag_lltype()
void set_ag_lltype (int gblsym, LL_Type * llt)
...
Definition at line 3401 of file llassem.cpp.
References AG_LLTYPE, assert, and ERR_Fatal.
Referenced by generate_struct_dtype(), get_ftn_cbind_lltype(), get_ftn_cmblk_lltype(), get_ftn_static_lltype(), get_ftn_typedesc_lltype(), ll_process_routine_parameters(), write_extern_inits(), and write_typedescs().
set_ag_ref()
static void set_ag_ref (SPTR sptr) static
Definition at line 3910 of file llassem.cpp.
References AG_REF, find_ag(), gbl, get_llvm_ifacenm(), get_llvm_name(), and sptr.
Referenced by sym_is_refd().
set_ag_return_lltype()
void set_ag_return_lltype (int gblsym, LL_Type * llt)
...
Definition at line 3421 of file llassem.cpp.
References AG_RET_LLTYPE, assert, and ERR_Fatal.
Referenced by ll_process_routine_parameters().
set_bss_addr()
void set_bss_addr (int size)
...
Definition at line 4596 of file llassem.cpp.
References gbl, and size.
set_llvm_iface_oldname()
void set_llvm_iface_oldname (int gblsym, char * nm)
...
Definition at line 5565 of file llassem.cpp.
References add_ag_name(), and AG_OLDNMPTR.
Referenced by ll_process_routine_parameters().
set_llvmag_entry()
void set_llvmag_entry (int gblsym)
...
Definition at line 5456 of file llassem.cpp.
References AG_STYPE.
Referenced by ll_process_routine_parameters().
set_private_size()
void set_private_size (ISZ_T sz)
The F90 front-end may have allocated private variables - need to adjust the initial size of the private area.
...
Definition at line 4590 of file llassem.cpp.
References prvt, and sz.
Referenced by upper().
straddr()
static char * straddr (int sptr) static
Definition at line 4448 of file llassem.cpp.
References sptr, and straddrbuf.
Referenced by getaddrdebug().
straddrp()
static char * straddrp (int sptr, char * bufptr) static
Definition at line 4455 of file llassem.cpp.
References sptr, and straddrpbuf.
Referenced by getaddrdebug().
sym_is_refd()
void sym_is_refd (SPTR sptr)
...
Definition at line 3925 of file llassem.cpp.
References align_unconstrained(), arg_is_refd(), assn_static_off(), assn_stkoff(), flg, gbl, is_passbyval_dummy(), ISZ_T, MIN_ALIGN_SIZE, FLG::quad, FLG::recursive, RU_PROG, set_ag_ref(), size, size_of(), FLG::smp, sptr, sym_is_refd(), SymConval1, and XBIT.
Referenced by runtime_32_byte_alignment(), runtime_alignment(), and sym_is_refd().
ThisIsAnAccessBug()
static INLINE TY_KIND ThisIsAnAccessBug (DTYPE dtype) static
Definition at line 5746 of file llassem.cpp.
References DTySeqTyElement.
Referenced by _fixup_llvm_uplevel_symbol().
upcase_name()
static void upcase_name (char * name) static
Definition at line 3888 of file llassem.cpp.
References name, and p.
Referenced by get_llvm_name(), getexnamestring(), and getsname().
write_bss()
static void write_bss (void) static
Definition at line 1499 of file llassem.cpp.
References ASMFIL, bss_dbg_list, bss_name, cpu_llvm_module, gbl, ISZ_PF, ll_write_object_dbg_references(), and NULL.
Referenced by assem_data().
write_comm()
static void write_comm (void) static
Definition at line 1682 of file llassem.cpp.
References add_ag_typename(), AG_CMBLKINITDATA, AG_DSIZE, AG_ISTLS, ag_other, AG_SIZE, AG_SYMLK, ASMFIL, CACHE_ALIGN, char_type(), DSRTG, DSRTP, errfatal(), fclose(), FILE, find_ag(), first_data, gbl, get_ag(), get_llvm_name(), get_struct_from_dsrt(), get_struct_from_dsrt2(), get_typedef_ag(), make_gblsym(), malloc(), MXIDLN, name, NOSYM, NULL, process_dsrt(), process_sptr(), size_of(), sptr, SPTR_NULL, tmpfile(), and XBIT.
Referenced by assem_data().
write_consts()
static void write_consts (void) static
Definition at line 1235 of file llassem.cpp.
References ASMFIL, char_type(), CONVAL2G, DTY, flg, gbl, getsname(), NOSYM, put_fstr(), put_kstr(), FLG::smp, sptr, SPTR_NULL, TY_CHAR, TY_NCHAR, write_constant_value(), and XBIT.
Referenced by assem_data().
write_extern_inits()
static void write_extern_inits (void) static
Definition at line 1405 of file llassem.cpp.
References AG_DSIZE, ASMFIL, CUDAG, DBGBIT, DT_ISBASIC, dummy, extern_inits, find_ag(), gbl, get_ag(), get_llvm_version(), get_struct_from_dsrt(), get_typedef_ag(), getsname(), LL_Version_3_8, llassem_struct_needs_cast(), make_lltype_from_dtype(), mk_struct_for_llvm_init(), DSRT::next, DSRT::offset, prefix, process_dsrt(), set_ag_lltype(), sptr, DSRT::sptr, SPTR_NULL, and str.
Referenced by assem_data().
write_externs()
static void write_externs (void) static
Definition at line 2658 of file llassem.cpp.
References add_ag_name(), AG_TYPENMPTR, char_type(), find_ag(), gbl, get_ag(), get_ftn_extern_lltype(), get_llvm_ifacenm(), get_llvm_name(), get_return_dtype(), get_return_type(), LL_VOID, LLTYPE, NOSYM, NULL, sptr, SPTR_NULL, LL_Type_::str, and write_ftn_type().
Referenced by assem_data().
write_final_table()
static int write_final_table (SPTR sptr, DTYPE dtype) static
Definition at line 2121 of file llassem.cpp.
References AG_DEFD, ASMFIL, build_final_table(), DT_INT, FINAL_TABLE_SZ, find_ag(), get_ag(), get_llvm_name(), get_typedef_ag(), getsname(), i, ll_abi_function_type(), ll_proto_get_abi(), ll_proto_key(), LLTYPE, make_array_lltype(), make_lltype_from_dtype(), make_ptr_lltype(), NULL, sptr, LL_Type_::str, and tname.
Referenced by write_typedescs().
write_ftn_type()
static char * write_ftn_type (LL_Type * ll_type, char * argptr, int byval) static
Definition at line 5203 of file llassem.cpp.
References LL_Type_::data_type, LL_ARRAY, LL_FUNCTION, LL_I1, LL_I128, LL_I16, LL_I24, LL_I256, LL_I32, LL_I40, LL_I48, LL_I56, LL_I64, LL_I8, LL_PTR, LL_STRUCT, ll_type_int_bits(), LL_VOID, LL_Type_::str, and strlen().
Referenced by write_externs().
write_layout_desc()
static void write_layout_desc (DTYPE dtype, int offset) static
Definition at line 1993 of file llassem.cpp.
References DDTG, DTY, DTyAlgTyMember, DTyAlgTyTag, has_final_members(), length(), NOSYM, offset, size_of(), SPTR_NULL, unknown, write_layout_desc(), and write_layout_desc_entry().
Referenced by write_layout_desc(), and write_typedescs().
write_layout_desc_entry()
static void write_layout_desc_entry (char tag, int offset, SPTR member, int length, SPTR sdsc) static
Write an entry in the layout desc for this member.
Definition at line 1948 of file llassem.cpp.
References ASMFIL, assert, ERR_Severe, getsname(), is_BIGOBJ(), length(), offset, process_sptr(), and SYMNAME.
Referenced by write_layout_desc().
write_module_as_subroutine()
static void write_module_as_subroutine (void) static
Definition at line 5472 of file llassem.cpp.
References dttypes, FLANG_FALLTHROUGH, FTN_HAS_INIT, gbl, get_llvm_name(), init_output_file(), ll_proto_set_defined_body(), make_lltype_from_dtype(), name, print_line(), print_nl(), print_space(), print_token(), and write_type().
Referenced by assemble().
write_parent_pointers()
static void write_parent_pointers (int parent, int level) static
Definition at line 2057 of file llassem.cpp.
References AG_TYPEDESC, ASMFIL, DTY, DTyAlgTyMember, DTyAlgTyTag, find_ag(), get_llvm_name(), get_typedef_ag(), level(), MAXIDLEN, parent, and write_parent_pointers().
Referenced by write_parent_pointers(), and write_typedescs().
write_statics()
static void write_statics (void) static
Definition at line 1556 of file llassem.cpp.
References AG_TYPENAME, sec_t::align, ASMFIL, count, cpu_llvm_module, DBGBIT, extern_inits, find_ag(), gbl, get_struct_from_dsrt(), get_struct_from_dsrt2(), get_typedef_ag(), getsname(), lcl_inits, ll_write_object_dbg_references(), MXIDLN, sec_t::name, DSRT::next, NULL, process_dsrt(), section_inits, DSRT::sectionindex, sections, sptr, DSRT::sptr, SPTR_NULL, static_dbg_list, and static_name.
Referenced by assem_data().
write_typedescs()
static void write_typedescs (void) static
Definition at line 2392 of file llassem.cpp.
References AG_DEFD, AG_DTYPESC, AG_FINAL, AG_SIZE, AG_TYPEDESC, ASMFIL, begin_layout_desc(), count_parent_pointers(), cpu_llvm_module, DTyAlgTyMember, DTyAlgTyTag, DTyArgType, end_layout_desc(), FINAL_TABLE_SZ, find_ag(), FREE, gbl, get_ag(), get_ag_searchnm(), get_llvm_name(), get_typedef_ag(), getsname(), has_final_procedures(), has_layout_desc(), has_pending_final_procedures(), if(), LL_Module::ir, last, len, level(), ll_feature_explicit_gep_load_type, make_lltype_from_dtype(), mk_struct_for_llvm_init(), MXIDLN, name, NEW, NOSYM, NULL, process_sptr(), put_ll_table_addr(), set_ag_lltype(), size, size_of(), sptr, strlen(), suffix, SYMNAME, write_final_table(), write_layout_desc(), write_parent_pointers(), write_vft(), and XBIT.
Referenced by assem_data().
write_vft()
static int write_vft (int sptr, DTYPE dtype) static
Definition at line 2284 of file llassem.cpp.
References AG_DEFD, AG_NAME, ASMFIL, assert, build_vft(), ERR_Fatal, find_ag(), FREE, get_llvm_name(), get_typedef_ag(), getsname(), i, ll_abi_function_type(), ll_proto_get_abi(), ll_proto_key(), MXIDLN, name, NULL, sptr, LL_Type_::str, SYMNAME, and tname.
Referenced by write_typedescs().
Variable Documentation
addr
int addr
Definition at line 194 of file llassem.cpp.
Referenced by _mp_get_threadprivate(), add_def(), add_socs(), add_to_common(), add_use(), assign1(), assn_static_off(), assn_stkoff(), attempt_gep_folding(), begin_entry(), charaddr(), charlen(), cmplx_to_mem(), consLoadDebug(), cp_byval_mem_arg(), do_common_blocks(), do_equiv(), emit_init(), exp_call(), exp_end(), exp_fstring(), exp_load(), exp_restore_mxcsr(), exp_smp(), exp_store(), exp_szero(), exp_type_bound_proc_call(), find_pointer_to_function(), fix_equiv_statics(), fix_module_common(), gen_call_expr(), gen_funcret(), gen_load(), get_address(), get_call_sptr(), get_chain_pointer_closure(), get_struct_from_dsrt(), get_struct_from_dsrt2(), handle_nested_threadprivate(), llGetThreadprivateAddr(), loadUplevelArgsForRegion(), mk_store_instr(), print_back_trace_line(), process_dsrt(), ref_threadprivate(), ref_threadprivate_var(), set_bss_addr(), set_common_size(), stackcheck(), store_aret(), storedums(), sym_is_refd(), toUplevelAddr(), trav_struct(), and void().
ag_ctors_cnt
int ag_ctors_cnt = 0 static
Definition at line 177 of file llassem.cpp.
Referenced by assemble_init().
agb_local
AGB_t agb_local static
Definition at line 46 of file llassem.cpp.
Referenced by add_ag_local_name(), assem_end(), assem_init(), find_local_ag(), and get_dummy_ag().
bss_aln_n
int bss_aln_n = 1 static
Definition at line 233 of file llassem.cpp.
Referenced by assem_end(), and assn_static_off().
bss_base
SPTR bss_base static
Definition at line 174 of file llassem.cpp.
Referenced by assem_end(), assem_init(), assn_static_off(), create_static_base(), fix_equiv_statics(), get_llvm_name(), getaddrdebug(), and getsname().
bss_dbg_list
LL_ObjToDbgList* bss_dbg_list static
Definition at line 176 of file llassem.cpp.
Referenced by llassem_get_objtodbg_list(), and write_bss().
bss_name
char bss_name[MXIDLN] static
Definition at line 175 of file llassem.cpp.
Referenced by assem_init(), create_static_base(), get_llvm_name(), getaddrdebug(), getsname(), and write_bss().
bss_name_global
int bss_name_global = 0 static
Definition at line 173 of file llassem.cpp.
Referenced by assem_end(), assem_init(), assn_static_off(), create_static_base(), fix_equiv_statics(), get_llvm_name(), getaddrdebug(), and getsname().
bss_name_initialized
int bss_name_initialized = 0 static
Definition at line 172 of file llassem.cpp.
Referenced by assem_end(), assem_init(), and create_static_base().
comment_char
char* comment_char
Definition at line 162 of file llassem.cpp.
Referenced by anno_blkcnt(), and put_anno_line().
CommonBlockInits
hashset_t CommonBlockInits static
Definition at line 121 of file llassem.cpp.
Referenced by dinits(), and dump_all_dinits().
contained_bss_name
char contained_bss_name[MXIDLN] static
Definition at line 189 of file llassem.cpp.
Referenced by assem_init(), and get_llvm_name().
contained_static_name
char contained_static_name[MXIDLN] static
Definition at line 186 of file llassem.cpp.
Referenced by assem_init(), and get_llvm_name().
current_debug_area
int current_debug_area extern
current_module
char* current_module extern
Definition at line 169 of file cgmain.cpp.
Referenced by formalsAddDebug(), llvm_write_ctor_dtor_list(), and schedule().
dsrtbase
DINIT_REC* dsrtbase extern
dsrtend
DINIT_REC * dsrtend
Definition at line 164 of file llassem.cpp.
dsrtfree
DINIT_REC * dsrtfree
Definition at line 164 of file llassem.cpp.
entries
int entries
Definition at line 238 of file llassem.cpp.
Referenced by find_entry().
expected_entries
int expected_entries
Definition at line 239 of file llassem.cpp.
fptr_local
fptr_local_t fptr_local
Definition at line 43 of file llassem.cpp.
Referenced by add_ag_fptr_name(), assem_end(), assem_init(), find_funcptr_name(), and llvm_funcptr_store().
global_sptr
int global_sptr static
Definition at line 212 of file llassem.cpp.
Referenced by get_ag(), get_llvm_name(), and getsname().
has_init
int has_init = 0 static
Definition at line 211 of file llassem.cpp.
Referenced by assem_end(), assem_init(), and assemble().
struct { ... } layout_desc
max_cm_align
int max_cm_align = 15 static
Definition at line 209 of file llassem.cpp.
Referenced by get_ag(), and max_align().
outer_bss_name
char outer_bss_name[MXIDLN] static
Definition at line 188 of file llassem.cpp.
Referenced by assem_init(), create_static_base(), get_llvm_name(), getaddrdebug(), and getsname().
outer_static_name
char outer_static_name[MXIDLN] static
Definition at line 184 of file llassem.cpp.
Referenced by assem_init(), create_static_base(), get_llvm_name(), getaddrdebug(), and getsname().
print_stab_lines
int print_stab_lines = false
Definition at line 190 of file llassem.cpp.
struct { ... } prvt
Referenced by set_private_size().
ptr_local
int ptr_local = 0 static
Definition at line 210 of file llassem.cpp.
Referenced by assem_end(), assem_init(), and llvm_funcptr_store().
sections
const struct sec_t sections[LAST_SEC] static
Initial value:
= {
    [NVIDIA_FATBIN_SEC] = {".nvFatBinSegment", 8},
    [NVIDIA_MODULEID_SEC] = {"__nv_module_id", 8},
    [NVIDIA_RELFATBIN_SEC] = {"__nv_relfatbin", 8},
    [NVIDIA_OLDFATBIN_SEC] = {".nv_fatbin", 8},
    [OMP_OFFLOAD_SEC] = {".omp_offloading.entries", 1}}
Definition at line 86 of file llassem.cpp.
Referenced by write_statics().
sptr
SPTR sptr
Definition at line 237 of file llassem.cpp.
Referenced by _fixup_llvm_uplevel_symbol(), align_of_var(), arg_is_refd(), assem_begin_func(), assem_init(), assn_static_off(), assn_stkoff(), begin_layout_desc(), create_static_base(), dinits(), dump_common_chain(), find_funcptr_name(), fix_private_sym(), get_ag(), get_ag_searchnm(), get_altname(), get_dummy_ag(), get_ftn_typedesc_dtype(), get_hollerith_size(), get_llvm_funcptr_ag(), get_llvm_name(), get_sptr_uplevel_address(), get_string_constant(), get_struct_from_dsrt(), get_struct_from_dsrt2(), getaddrdebug(), getextfuncname(), getfuncname(), getsname(), has_final_members(), has_final_procedures(), has_pending_final_procedures(), hostsym_is_refd(), is_typedesc_defd(), llassem_get_objtodbg_list(), llassem_struct_needs_cast(), llvm_funcptr_store(), local_funcptr_sptr_to_gblsym(), make_gblsym(), max_align(), put_fstr(), put_kstr(), runtime_alignment(), set_ag_ref(), straddr(), straddrp(), sym_is_refd(), write_comm(), write_consts(), write_extern_inits(), write_externs(), write_final_table(), write_statics(), write_typedescs(), and write_vft().
static_base
SPTR static_base static
Definition at line 170 of file llassem.cpp.
Referenced by assem_end(), assem_init(), assn_static_off(), create_static_base(), fix_equiv_statics(), get_llvm_name(), getaddrdebug(), and getsname().
static_dbg_list
LL_ObjToDbgList* static_dbg_list static
Definition at line 171 of file llassem.cpp.
Referenced by llassem_get_objtodbg_list(), and write_statics().
static_name_global
int static_name_global = 0 static
Definition at line 169 of file llassem.cpp.
Referenced by assem_end(), assem_init(), assn_static_off(), create_static_base(), fix_equiv_statics(), get_llvm_name(), getaddrdebug(), and getsname().
static_name_initialized
int static_name_initialized = 0 static
Definition at line 168 of file llassem.cpp.
Referenced by assem_end(), assem_init(), and create_static_base().
stk_aln_n
int stk_aln_n = 1 static
Definition at line 232 of file llassem.cpp.
Referenced by assem_end(), and assn_stkoff().
straddrbuf
char straddrbuf[20] static
Definition at line 4444 of file llassem.cpp.
Referenced by straddr().
straddrpbuf
char straddrpbuf[sizeof(bss_name)+11+2] static
Definition at line 4445 of file llassem.cpp.
Referenced by straddrp().
sym_sz
int sym_sz
Definition at line 195 of file llassem.cpp.
tname
const char* tname
Definition at line 241 of file llassem.cpp.
Referenced by assemble_end(), dummy_program(), get_ftn_cbind_lltype(), get_ftn_cmblk_lltype(), get_ftn_static_lltype(), get_ftn_typedesc_lltype(), make_uplevel_arg_struct(), process_ftn_dtype_struct(), write_final_table(), and write_vft().
uplevelcnt
int uplevelcnt = 0 static
Definition at line 5875 of file llassem.cpp.
Referenced by _add_llvm_uplevel_symbol(), and add_aguplevel_oldsptr().
upptr
int* upptr = NULL static
Definition at line 5876 of file llassem.cpp.
Referenced by _add_llvm_uplevel_symbol(), and add_aguplevel_oldsptr().
wrote_tname
bool wrote_tname
Definition at line 240 of file llassem.cpp.