flang: llassem_common.cpp File Reference
llassem_common.cpp File Reference
#include "llassem_common.h"
#include "dinit.h"
#include "dinitutl.h"
#include "version.h"
#include "machreg.h"
#include "assem.h"
#include "mach.h"
#include "llutil.h"
#include "cgllvm.h"
#include "cgmain.h"
#include "cg.h"
#include "llassem.h"
#include "dtypeutl.h"
Functions
static void put_ncharstring_n (char *, ISZ_T, int)
static void put_zeroes (ISZ_T)
static void put_cmplx_n (int, int)
static void put_dcmplx_n (int, int)
static void put_i8 (int)
static void put_i16 (int)
static void put_r4 (INT)
static void put_r8 (int, int)
static void add_ctor (const char *)
static void write_proc_pointer (SPTR sptr)
char * put_next_member (char *ptr)
...
ISZ_T put_skip (ISZ_T old, ISZ_T New, bool is_char)
...
void emit_init (DTYPE tdtype, ISZ_T tconval, ISZ_T *addr, ISZ_T *repeat_cnt, ISZ_T loc_base, ISZ_T *i8cnt, int *ptrcnt, char **cptr, bool is_char)
...
void put_string_n (const char *p, ISZ_T len, int size)
...
void put_i32 (int val)
...
void put_short (int val)
...
LL_Value * gen_ptr_offset_val (int offset, LL_Type *ret_type, const char *ptr_nm)
Generate an expression to add an offset to a ptr.
void put_addr (SPTR sptr, ISZ_T off, DTYPE dtype)
Produce a getelementptr that would fetch a value out of one of the global structs.
DTYPE mk_struct_for_llvm_init (const char *name, int size)
...
int add_member_for_llvm (SPTR sym, int prev, DTYPE dtype, ISZ_T size)
...
void add_init_routine (char *initroutine)
Add initilizer routine 'initroutine' to the llvm global ctor array.
void init_huge_tlb (void)
...
void init_flushz (void)
Add the constructor responsible for -Mflushz.
void init_daz (void)
Add the constructor responsible for -Mdaz.
void init_ktrap (void)
Add the constructor responsible for -Ktrap.
Variables
union {
unsigned short i8
unsigned char byte [2]
} i8bit
union {
unsigned short i16
unsigned char byte [2]
} i16bit
union {
unsigned int i32
float r4
unsigned char byte [4]
} i32bit
AGB_t agb
DSRT * lcl_inits
DSRT * section_inits
DSRT * extern_inits
char static_name [MXIDLN]
int first_data
int ag_cmblks
int ag_procs
int ag_other
int ag_global
int ag_typedef
int ag_static
int ag_intrin
int ag_local
int ag_funcptr
Function Documentation
add_ctor()
static void add_ctor (const char * constructor) static
Definition at line 80 of file llassem_common.cpp.
References buff, cpu_llvm_module, fn, ll_create_basic_type(), ll_create_function(), LL_NO_LINKAGE, ll_proto_add(), ll_proto_set_intrinsic(), LL_VOID, llvm_ctor_add(), and NULL.
Referenced by init_daz(), init_flushz(), init_huge_tlb(), and init_ktrap().
add_init_routine()
void add_init_routine (char * initroutine)
Add initilizer routine 'initroutine' to the llvm global ctor array.
...
Definition at line 1081 of file llassem_common.cpp.
References llvm_ctor_add().
add_member_for_llvm()
int add_member_for_llvm (SPTR sym, int prev, DTYPE dtype, ISZ_T size)
...
Definition at line 1061 of file llassem_common.cpp.
References insert_sym_first(), mem(), NOSYM, prev, and size.
emit_init()
void emit_init (DTYPE tdtype, ISZ_T tconval, ISZ_T * addr, ISZ_T * repeat_cnt, ISZ_T loc_base, ISZ_T * i8cnt, int * ptrcnt, char ** cptr, bool is_char)
...
Definition at line 157 of file llassem_common.cpp.
References addr, ALIGN, alignment(), area, ASMFIL, assert, CONVAL2G, DBGBIT, STB::dbl0, DINIT_DATASECT, DINIT_FUNCCOUNT, DINIT_LABEL, DINIT_OFFSET, DINIT_PROC, dinit_read_string(), DINIT_REPEAT, DINIT_SECT, DINIT_STRING, DINIT_ZEROES, DT_CPTR, DTY, ERR_Severe, first_data, flg, gbl, interr(), is_empty_typedef(), ISZ_T, LLVM_LONGTERM_AREA, STB::n_base, FLG::omptarget, put_addr(), put_cmplx_n(), put_dcmplx_n(), put_i16(), put_i32(), put_i8(), put_ncharstring_n(), put_next_member(), put_r4(), put_r8(), put_skip(), put_string_n(), put_zeroes(), putval(), STB::quad0, repeat_cnt, size_of(), SPTR_NULL, stb, str, SymConval1, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, TY_SLOG, TY_WORD, write_proc_pointer(), and XBIT.
Referenced by process_dsrt().
gen_ptr_offset_val()
LL_Value * gen_ptr_offset_val (int offset, LL_Type * ret_type, const char * ptr_nm)
Generate an expression to add an offset to a ptr.
...
Parameters
offset the addend
ret_type the type of the pointer (LL_Type)
ptr_nm the identifier for the pointer
For example,
  getelementptr(i8* bitcast(<ret_type> <ptr_nm> to i8*), i32 <offset>)
The caller expects a string that is an i8*.
Definition at line 945 of file llassem_common.cpp.
References cpu_llvm_module, ll_create_int_type(), ll_create_value_from_type(), ll_get_const_bitcast(), ll_get_const_gep(), ll_get_pointer_type(), and offset.
Referenced by put_addr().
init_daz()
void init_daz (void)
Add the constructor responsible for -Mdaz.
...
Definition at line 1109 of file llassem_common.cpp.
References add_ctor().
Referenced by assemble_end().
init_flushz()
void init_flushz (void)
Add the constructor responsible for -Mflushz.
...
Definition at line 1102 of file llassem_common.cpp.
References add_ctor().
Referenced by assemble_end().
init_huge_tlb()
void init_huge_tlb (void)
...
Definition at line 1095 of file llassem_common.cpp.
References add_ctor().
Referenced by assemble_end().
init_ktrap()
void init_ktrap (void)
Add the constructor responsible for -Ktrap.
...
Definition at line 1116 of file llassem_common.cpp.
References add_ctor(), ASMFIL, flg, and FLG::x.
Referenced by assemble_end().
mk_struct_for_llvm_init()
DTYPE mk_struct_for_llvm_init (const char * name, int size)
...
Definition at line 1041 of file llassem_common.cpp.
References cg_get_type(), DTY, getsymbol(), MXIDLN, name, NOSYM, process_ftn_dtype_struct(), and size.
Referenced by generate_struct_dtype(), get_ftn_static_lltype(), get_ftn_typedesc_dtype(), make_uplevel_arg_struct(), write_extern_inits(), and write_typedescs().
put_addr()
void put_addr (SPTR sptr, ISZ_T off, DTYPE dtype)
Produce a getelementptr that would fetch a value out of one of the global structs.
...
Print something along the lines of (LLVM version dependent):
  getelementptr (i8* bitcast (%struct$name* @getsname(sptr)
                 to i8*), i32 0) to i8*)
Definition at line 972 of file llassem_common.cpp.
References ASMFIL, cpu_llvm_module, LL_Value::data, LL_Type_::data_type, gen_ptr_offset_val(), getsname(), LL_Module::ir, ll_feature_explicit_gep_load_type, ll_get_pointer_type(), LL_PTR, LLTYPE, name, need_ptr(), off, process_sptr(), SNAME, and sptr.
Referenced by emit_init().
put_cmplx_n()
static void put_cmplx_n (int sptr, int putval) static
Definition at line 907 of file llassem_common.cpp.
References ASMFIL, CONVAL2G, put_r4(), and sptr.
Referenced by emit_init().
put_dcmplx_n()
static void put_dcmplx_n (int sptr, int putval) static
Definition at line 915 of file llassem_common.cpp.
References ASMFIL, CONVAL2G, put_r8(), putval(), and sptr.
Referenced by emit_init().
put_i16()
static void put_i16 (int val) static
Definition at line 816 of file llassem_common.cpp.
References ASMFIL, i, i16bit, and val.
Referenced by emit_init().
put_i32()
void put_i32 (int val)
...
Definition at line 829 of file llassem_common.cpp.
References ASMFIL, i, i32bit, and val.
Referenced by emit_init().
put_i8()
static void put_i8 (int val) static
Definition at line 808 of file llassem_common.cpp.
References ASMFIL, i8bit, and val.
Referenced by emit_init().
put_ncharstring_n()
static void put_ncharstring_n (char * p, ISZ_T len, int size_of_char) static
Definition at line 754 of file llassem_common.cpp.
References a, ASMFIL, i, kanji_char(), len, n, p, and val.
Referenced by emit_init().
put_next_member()
char * put_next_member (char * ptr)
...
Definition at line 94 of file llassem_common.cpp.
References ASMFIL, and NULL.
Referenced by emit_init(), and process_dsrt().
put_r4()
static void put_r4 (INT val) static
Definition at line 848 of file llassem_common.cpp.
References ASMFIL, i, i32bit, and val.
Referenced by emit_init(), put_cmplx_n(), and put_r8().
put_r8()
static void put_r8 (int sptr, int putval) static
Definition at line 860 of file llassem_common.cpp.
References ASMFIL, CONVAL2G, FLG::endian, flg, num, put_r4(), and sptr.
Referenced by emit_init(), and put_dcmplx_n().
put_short()
void put_short (int val)
...
Definition at line 841 of file llassem_common.cpp.
References ASMFIL, and val.
put_skip()
ISZ_T put_skip (ISZ_T old, ISZ_T New, bool is_char)
...
Definition at line 109 of file llassem_common.cpp.
References ASMFIL, assert, ERR_Severe, i, ISZ_T, s, and str.
Referenced by emit_init(), and process_dsrt().
put_string_n()
void put_string_n (const char * p, ISZ_T len, int size)
...
Definition at line 725 of file llassem_common.cpp.
References ASMFIL, len, n, p, and size.
Referenced by emit_init(), and put_fstr().
put_zeroes()
static void put_zeroes (ISZ_T len) static
Definition at line 784 of file llassem_common.cpp.
References ASMFIL, i, ISZ_T, and len.
Referenced by emit_init().
write_proc_pointer()
static void write_proc_pointer (SPTR sptr) static
Definition at line 148 of file llassem_common.cpp.
References ASMFIL, getsname(), and sptr.
Referenced by emit_init().
Variable Documentation
ag_cmblks
int ag_cmblks
Definition at line 51 of file llassem_common.cpp.
Referenced by assemble_end(), assemble_init(), and get_ag().
ag_funcptr
int ag_funcptr
Definition at line 59 of file llassem_common.cpp.
Referenced by assemble_init(), and get_llvm_funcptr_ag().
ag_global
int ag_global
Definition at line 54 of file llassem_common.cpp.
Referenced by assemble_end(), assemble_init(), and get_ag().
ag_intrin
int ag_intrin
Definition at line 57 of file llassem_common.cpp.
Referenced by assemble_end(), and get_intrin_ag().
ag_local
int ag_local
Definition at line 58 of file llassem_common.cpp.
Referenced by assem_end(), assem_init(), and get_dummy_ag().
ag_other
int ag_other
Definition at line 53 of file llassem_common.cpp.
Referenced by assemble_end(), assemble_init(), get_ag(), and write_comm().
ag_procs
int ag_procs
Definition at line 52 of file llassem_common.cpp.
Referenced by assemble_init(), and get_ag().
ag_static
int ag_static
Definition at line 56 of file llassem_common.cpp.
Referenced by assemble_init().
ag_typedef
int ag_typedef
Definition at line 55 of file llassem_common.cpp.
Referenced by assemble_end(), assemble_init(), and get_typedef_ag().
agb
AGB_t agb
Definition at line 44 of file llassem_common.cpp.
Referenced by add_ag_name(), assemble_end(), assemble_init(), dump_ag(), dump_allag(), find_ag(), and make_gblsym().
byte
unsigned char byte[4]
Definition at line 28 of file llassem_common.cpp.
extern_inits
DSRT* extern_inits
Definition at line 48 of file llassem_common.cpp.
Referenced by dinits(), dump_all_dinits(), write_extern_inits(), and write_statics().
first_data
int first_data
Definition at line 50 of file llassem_common.cpp.
Referenced by emit_init(), get_struct_from_dsrt2(), process_dsrt(), and write_comm().
i16
unsigned short i16
Definition at line 32 of file llassem_common.cpp.
union { ... } i16bit
Referenced by put_i16().
i32
unsigned int i32
Definition at line 37 of file llassem_common.cpp.
union { ... } i32bit
Referenced by put_i32(), and put_r4().
i8
unsigned short i8
Definition at line 27 of file llassem_common.cpp.
Referenced by __pmth_i_dpowk(), __pmth_i_qpowk(), __pmth_i_rpowk(), _sect(), _template(), fw_writenum(), print_row(), and process_symlinked_sptr().
union { ... } i8bit
Referenced by put_i8().
lcl_inits
DSRT* lcl_inits
Definition at line 46 of file llassem_common.cpp.
Referenced by dinits(), dump_all_dinits(), and write_statics().
r4
float r4
Definition at line 38 of file llassem_common.cpp.
Referenced by fw_writenum(), gen_cmplx_mul(), print_row(), and widenPushdown().
section_inits
DSRT* section_inits
Definition at line 47 of file llassem_common.cpp.
Referenced by dinits(), dump_all_dinits(), and write_statics().
static_name
char static_name[MXIDLN]
Definition at line 49 of file llassem_common.cpp.
Referenced by assem_init(), create_static_base(), get_llvm_name(), getaddrdebug(), getsname(), and write_statics().