flang: llcrit.c File Reference
llcrit.c File Reference
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include "komp.h"
#include <stdioInterf.h>
Typedefs
typedef void(* assign_func_ptr) (void *, void *)
Functions
void _mp_p (kmp_critical_name *sem)
void _mp_v (kmp_critical_name *sem)
void _mp_ptest (omp_lock_t *sem)
void _mp_bcs (void)
void _mp_ecs (void)
void _mp_bcs_stdio (void)
void _mp_ecs_stdio (void)
static void __llcrit_atfork (void)
void _mp_bcs_nest (void)
void _mp_ecs_nest (void)
void _mp_bcs_nest_red (void)
void _mp_ecs_nest_red (void)
void _mp_cdeclp (void *blk, void ***blk_tp, int size)
void _mp_cdecli (void *blk, void ***blk_tp, int size)
void _mp_cdecl (void *blk, void ***blk_tp, int size)
void _mp_copypriv (char *adr, long len, int thread)
void _mp_copypriv_al (char **adr, long len, int thread)
void _mp_copypriv_move (void *blk_tp, int off, int size, int single_thread)
void _mp_copypriv_move_tls (void **blk_tp, int off, int size, int single_thread)
void _mp_copyin_move (void *blk_tp, int off, int size)
void _mp_copyin_move_tls (void *blk_tp, int off, int size)
void _mp_copyin_move_cpp (void *blk_tp, int off, int class_size, int vector_size, assign_func_ptr assign_op)
void _mp_copyin_move_cpp_new (void *blk_tp, int off, int class_size, int vector_size, assign_func_ptr assign_op, char *fr)
void _mp_copyin_move_cpp_tls (void *master, void *slave, int class_size, int vector_size, assign_func_ptr assign_op)
void _mp_copyin_move_multiple (int n_entries, void *data)
void _mp_copyin_move_al (void *blk_tp, int off, long size)
void _mp_copypriv_kmpc (void *dest, void *src)
void * _mp_get_threadprivate (ident_t *ident, kmp_int32 gtid, void *tpv, size_t size, void **addr)
Variables
static kmp_critical_name sem_cs
static kmp_critical_name sem_stdio
static kmp_critical_name nest_sem
static omp_nest_lock_t nest_lock
static int is_init_nest = 0
static int is_init_nest_red = 0
static int is_atfork_registered = 0
static kmp_critical_name nest_sem_red
static omp_nest_lock_t nest_lock_red
static char * singadr
static long singlen
Typedef Documentation
assign_func_ptr
typedef void(* assign_func_ptr) (void *, void *)
Definition at line 311 of file llcrit.c.
Function Documentation
__llcrit_atfork()
static void __llcrit_atfork (void) static
Definition at line 75 of file llcrit.c.
References __io_stderr(), is_atfork_registered, is_init_nest, and is_init_nest_red.
Referenced by _mp_bcs_nest(), and _mp_bcs_nest_red().
_mp_bcs()
void _mp_bcs (void)
Definition at line 42 of file llcrit.c.
References __kmpc_critical(), __kmpc_global_thread_num(), and sem_cs.
_mp_bcs_nest()
void _mp_bcs_nest (void)
Definition at line 87 of file llcrit.c.
References __io_stderr(), __llcrit_atfork(), _mp_p(), _mp_v(), is_atfork_registered, is_init_nest, nest_lock, nest_sem, NULL, omp_init_nest_lock(), and omp_set_nest_lock().
_mp_bcs_nest_red()
void _mp_bcs_nest_red (void)
Definition at line 124 of file llcrit.c.
References __io_stderr(), __llcrit_atfork(), _mp_p(), _mp_v(), is_atfork_registered, is_init_nest_red, nest_lock_red, nest_sem_red, NULL, omp_init_nest_lock(), and omp_set_nest_lock().
_mp_bcs_stdio()
void _mp_bcs_stdio (void)
Definition at line 56 of file llcrit.c.
References __kmpc_critical(), __kmpc_global_thread_num(), and sem_stdio.
_mp_cdecl()
void _mp_cdecl (void * blk, void *** blk_tp, int size)
Definition at line 169 of file llcrit.c.
References __kmpc_global_thread_num(), __kmpc_threadprivate_cached(), and size.
_mp_cdecli()
void _mp_cdecli (void * blk, void *** blk_tp, int size)
Definition at line 162 of file llcrit.c.
References __kmpc_global_thread_num(), __kmpc_threadprivate_cached(), and size.
_mp_cdeclp()
void _mp_cdeclp (void * blk, void *** blk_tp, int size)
Definition at line 155 of file llcrit.c.
References __kmpc_global_thread_num(), __kmpc_threadprivate_cached(), and size.
_mp_copyin_move()
void _mp_copyin_move (void * blk_tp, int off, int size)
Definition at line 272 of file llcrit.c.
References __kmpc_barrier(), __kmpc_global_thread_num(), __kmpc_threadprivate_cached(), and size.
_mp_copyin_move_al()
void _mp_copyin_move_al (void * blk_tp, int off, long size)
Definition at line 433 of file llcrit.c.
References __kmpc_barrier(), __kmpc_global_thread_num(), __kmpc_threadprivate_cached(), and size.
_mp_copyin_move_cpp()
void _mp_copyin_move_cpp (void * blk_tp, int off, int class_size, int vector_size, assign_func_ptr assign_op)
Definition at line 321 of file llcrit.c.
References __kmpc_barrier(), __kmpc_global_thread_num(), __kmpc_threadprivate_cached(), and i.
_mp_copyin_move_cpp_new()
void _mp_copyin_move_cpp_new (void * blk_tp, int off, int class_size, int vector_size, assign_func_ptr assign_op, char * fr)
Definition at line 354 of file llcrit.c.
References __kmpc_global_thread_num(), __kmpc_threadprivate_cached(), and i.
_mp_copyin_move_cpp_tls()
void _mp_copyin_move_cpp_tls (void * master, void * slave, int class_size, int vector_size, assign_func_ptr assign_op)
Definition at line 382 of file llcrit.c.
References i.
_mp_copyin_move_multiple()
void _mp_copyin_move_multiple (int n_entries, void * data)
Definition at line 403 of file llcrit.c.
References __kmpc_barrier(), __kmpc_global_thread_num(), __kmpc_threadprivate_cached(), i, NULL, size, and tid.
_mp_copyin_move_tls()
void _mp_copyin_move_tls (void * blk_tp, int off, int size)
Definition at line 294 of file llcrit.c.
References __kmpc_barrier(), __kmpc_global_thread_num(), __kmpc_threadprivate(), and size.
_mp_copypriv()
void _mp_copypriv (char * adr, long len, int thread)
Definition at line 180 of file llcrit.c.
References __kmpc_barrier(), __kmpc_global_thread_num(), len, singadr, and singlen.
_mp_copypriv_al()
void _mp_copypriv_al (char ** adr, long len, int thread)
Definition at line 195 of file llcrit.c.
References __kmpc_barrier(), __kmpc_global_thread_num(), len, singadr, and singlen.
_mp_copypriv_kmpc()
void _mp_copypriv_kmpc (void * dest, void * src)
Definition at line 454 of file llcrit.c.
References dest, size, and src.
_mp_copypriv_move()
void _mp_copypriv_move (void * blk_tp, int off, int size, int single_thread)
Definition at line 216 of file llcrit.c.
References __kmpc_barrier(), __kmpc_global_thread_num(), __kmpc_threadprivate_cached(), singadr, singlen, and size.
_mp_copypriv_move_tls()
void _mp_copypriv_move_tls (void ** blk_tp, int off, int size, int single_thread)
Definition at line 241 of file llcrit.c.
References __kmpc_barrier(), __kmpc_global_thread_num(), __kmpc_threadprivate(), singadr, singlen, and size.
_mp_ecs()
void _mp_ecs (void)
Definition at line 48 of file llcrit.c.
References __kmpc_end_critical(), __kmpc_global_thread_num(), and sem_cs.
_mp_ecs_nest()
void _mp_ecs_nest (void)
Definition at line 109 of file llcrit.c.
References nest_lock, and omp_unset_nest_lock().
_mp_ecs_nest_red()
void _mp_ecs_nest_red (void)
Definition at line 146 of file llcrit.c.
References nest_lock_red, and omp_unset_nest_lock().
_mp_ecs_stdio()
void _mp_ecs_stdio (void)
Definition at line 62 of file llcrit.c.
References __kmpc_end_critical(), __kmpc_global_thread_num(), and sem_stdio.
_mp_get_threadprivate()
void * _mp_get_threadprivate (ident_t * ident, kmp_int32 gtid, void * tpv, size_t size, void ** addr)
Definition at line 474 of file llcrit.c.
References __kmpc_threadprivate(), addr, gtid, NULL, and size.
_mp_p()
void _mp_p (kmp_critical_name * sem)
Definition at line 23 of file llcrit.c.
References __kmpc_critical(), __kmpc_global_thread_num(), and sem.
Referenced by _mp_bcs_nest(), _mp_bcs_nest_red(), _mp_calloc(), _mp_free(), _mp_malloc(), and _mp_realloc().
_mp_ptest()
void _mp_ptest (omp_lock_t * sem)
Definition at line 35 of file llcrit.c.
_mp_v()
void _mp_v (kmp_critical_name * sem)
Definition at line 29 of file llcrit.c.
References __kmpc_end_critical(), __kmpc_global_thread_num(), and sem.
Referenced by _mp_bcs_nest(), _mp_bcs_nest_red(), _mp_calloc(), _mp_free(), _mp_malloc(), and _mp_realloc().
Variable Documentation
is_atfork_registered
int is_atfork_registered = 0 static
Definition at line 72 of file llcrit.c.
Referenced by __llcrit_atfork(), _mp_bcs_nest(), and _mp_bcs_nest_red().
is_init_nest
int is_init_nest = 0 static
Definition at line 70 of file llcrit.c.
Referenced by __llcrit_atfork(), and _mp_bcs_nest().
is_init_nest_red
int is_init_nest_red = 0 static
Definition at line 71 of file llcrit.c.
Referenced by __llcrit_atfork(), and _mp_bcs_nest_red().
nest_lock
omp_nest_lock_t nest_lock static
Definition at line 68 of file llcrit.c.
Referenced by _mp_bcs_nest(), and _mp_ecs_nest().
nest_lock_red
omp_nest_lock_t nest_lock_red static
Definition at line 121 of file llcrit.c.
Referenced by _mp_bcs_nest_red(), and _mp_ecs_nest_red().
nest_sem
kmp_critical_name nest_sem static
Definition at line 67 of file llcrit.c.
Referenced by _mp_bcs_nest().
nest_sem_red
kmp_critical_name nest_sem_red static
Definition at line 120 of file llcrit.c.
Referenced by _mp_bcs_nest_red().
sem_cs
kmp_critical_name sem_cs static
Definition at line 39 of file llcrit.c.
Referenced by _mp_bcs(), and _mp_ecs().
sem_stdio
kmp_critical_name sem_stdio static
Definition at line 53 of file llcrit.c.
Referenced by _mp_bcs_stdio(), and _mp_ecs_stdio().
singadr
char* singadr static
Definition at line 175 of file llcrit.c.
Referenced by _mp_copypriv(), _mp_copypriv_al(), _mp_copypriv_move(), and _mp_copypriv_move_tls().
singlen
long singlen static
Definition at line 176 of file llcrit.c.
Referenced by _mp_copypriv(), _mp_copypriv_al(), _mp_copypriv_move(), and _mp_copypriv_move_tls().