flang: llcrit.h File Reference
llcrit.h File Reference
#include "komp.h"
Macros
#define MP_P(sem) _mp_p(&sem)
#define MP_V(sem) _mp_v(&sem)
#define MP_PTEST(sem) _mp_ptest(sem)
#define MP_BCS _mp_bcs()
#define MP_ECS _mp_ecs()
#define MP_P_STDIO _mp_bcs_stdio()
#define MP_V_STDIO _mp_ecs_stdio()
#define MP_BCS_NEST _mp_bcs_nest()
#define MP_ECS_NEST _mp_ecs_nest()
#define MP_CDECLP(blk, blk_tp, size) _mp_cdeclp(blk, blk_tp, size)
#define MP_CDECLI(blk, blk_tp, size) _mp_cdecli(blk, blk_tp, size)
#define MP_CDECL(blk, blk_tp, size) _mp_cdecl(blk, blk_tp, size)
#define MP_COPYIN_INIT _mp_copyin_init()
#define MP_COPYPRIV_INIT _mp_copypriv_init()
#define MP_COPYIN_TERM _mp_copyin_term()
#define MP_COPYPRIV_TERM _mp_copypriv_term()
#define MP_COPYPRIV(adr, len, thread) _mp_copypriv(adr, len, thread)
#define MP_COPYPRIV_AL(adr, len, thread) _mp_copypriv_al(adr, len, thread)
#define MP_COPYPRIV_MOVE(blk_tp, off, size, single_thread) _mp_copypriv_move(blk_tp, off, size, single_thread)
#define MP_COPYIN_MOVE(blk_tp, off, size) _mp_copyin_move(blk_tp, off, size)
#define MP_COPYIN_MOVE_AL(blk_tp, off, size) _mp_copyin_move_al(blk_tp, off, size)
#define MP_SEMAPHORE(sc, sem) sc kmp_critical_name sem;
Functions
void _mp_p (kmp_critical_name *sem)
void _mp_v (kmp_critical_name *sem)
void _mp_ptest (omp_lock_t *sem)
void _mp_bcs (void)
void _mp_ecs (void)
void _mp_bcs_stdio (void)
void _mp_ecs_stdio (void)
void _mp_bcs_nest (void)
void _mp_ecs_nest (void)
void _mp_cdeclp (void *blk, void ***blk_tp, int size)
void _mp_cdecli (void *blk, void ***blk_tp, int size)
void _mp_cdecl (void *blk, void ***blk_tp, int size)
void _mp_copyin_init (void)
void _mp_copypriv_init (void)
void _mp_copyin_term (void)
void _mp_copypriv_term (void)
void _mp_copypriv (char *adr, long len, int thread)
void _mp_copypriv_al (char **adr, long len, int thread)
void _mp_copypriv_move (void *blk_tp, int off, int size, int single_thread)
void _mp_copyin_move (void *blk_tp, int off, int size)
void _mp_copyin_move_al (void *blk_tp, int off, long size)
Detailed Description
external declarations for libpgc routines defined in llcrit.c
Definition in file llcrit.h.
Macro Definition Documentation
MP_BCS
#define MP_BCS _mp_bcs()
Definition at line 40 of file llcrit.h.
MP_BCS_NEST
#define MP_BCS_NEST _mp_bcs_nest()
Definition at line 44 of file llcrit.h.
MP_CDECL
#define MP_CDECL (blk, blk_tp, size) _mp_cdecl(blk, blk_tp, size)
Definition at line 48 of file llcrit.h.
MP_CDECLI
#define MP_CDECLI (blk, blk_tp, size) _mp_cdecli(blk, blk_tp, size)
Definition at line 47 of file llcrit.h.
MP_CDECLP
#define MP_CDECLP (blk, blk_tp, size) _mp_cdeclp(blk, blk_tp, size)
Definition at line 46 of file llcrit.h.
MP_COPYIN_INIT
#define MP_COPYIN_INIT _mp_copyin_init()
Definition at line 49 of file llcrit.h.
MP_COPYIN_MOVE
#define MP_COPYIN_MOVE (blk_tp, off, size) _mp_copyin_move(blk_tp, off, size)
Definition at line 57 of file llcrit.h.
MP_COPYIN_MOVE_AL
#define MP_COPYIN_MOVE_AL (blk_tp, off, size) _mp_copyin_move_al(blk_tp, off, size)
Definition at line 58 of file llcrit.h.
MP_COPYIN_TERM
#define MP_COPYIN_TERM _mp_copyin_term()
Definition at line 51 of file llcrit.h.
MP_COPYPRIV
#define MP_COPYPRIV (adr, len, thread) _mp_copypriv(adr, len, thread)
Definition at line 53 of file llcrit.h.
MP_COPYPRIV_AL
#define MP_COPYPRIV_AL (adr, len, thread) _mp_copypriv_al(adr, len, thread)
Definition at line 54 of file llcrit.h.
MP_COPYPRIV_INIT
#define MP_COPYPRIV_INIT _mp_copypriv_init()
Definition at line 50 of file llcrit.h.
MP_COPYPRIV_MOVE
#define MP_COPYPRIV_MOVE (blk_tp, off, size, single_thread) _mp_copypriv_move(blk_tp, off, size, single_thread)
Definition at line 55 of file llcrit.h.
MP_COPYPRIV_TERM
#define MP_COPYPRIV_TERM _mp_copypriv_term()
Definition at line 52 of file llcrit.h.
MP_ECS
#define MP_ECS _mp_ecs()
Definition at line 41 of file llcrit.h.
MP_ECS_NEST
#define MP_ECS_NEST _mp_ecs_nest()
Definition at line 45 of file llcrit.h.
MP_P
#define MP_P (sem) _mp_p(&sem)
Definition at line 37 of file llcrit.h.
MP_P_STDIO
#define MP_P_STDIO _mp_bcs_stdio()
Definition at line 42 of file llcrit.h.
MP_PTEST
#define MP_PTEST (sem) _mp_ptest(sem)
Definition at line 39 of file llcrit.h.
MP_SEMAPHORE
#define MP_SEMAPHORE (sc, sem) sc kmp_critical_name sem;
Definition at line 60 of file llcrit.h.
MP_V
#define MP_V (sem) _mp_v(&sem)
Definition at line 38 of file llcrit.h.
MP_V_STDIO
#define MP_V_STDIO _mp_ecs_stdio()
Definition at line 43 of file llcrit.h.
Function Documentation
_mp_bcs()
void _mp_bcs (void)
Definition at line 42 of file llcrit.c.
References __kmpc_critical(), __kmpc_global_thread_num(), and sem_cs.
_mp_bcs_nest()
void _mp_bcs_nest (void)
Definition at line 87 of file llcrit.c.
References __io_stderr(), __llcrit_atfork(), _mp_p(), _mp_v(), is_atfork_registered, is_init_nest, nest_lock, nest_sem, NULL, omp_init_nest_lock(), and omp_set_nest_lock().
_mp_bcs_stdio()
void _mp_bcs_stdio (void)
Definition at line 56 of file llcrit.c.
References __kmpc_critical(), __kmpc_global_thread_num(), and sem_stdio.
_mp_cdecl()
void _mp_cdecl (void * blk, void *** blk_tp, int size)
Definition at line 169 of file llcrit.c.
References __kmpc_global_thread_num(), __kmpc_threadprivate_cached(), and size.
_mp_cdecli()
void _mp_cdecli (void * blk, void *** blk_tp, int size)
Definition at line 162 of file llcrit.c.
References __kmpc_global_thread_num(), __kmpc_threadprivate_cached(), and size.
_mp_cdeclp()
void _mp_cdeclp (void * blk, void *** blk_tp, int size)
Definition at line 155 of file llcrit.c.
References __kmpc_global_thread_num(), __kmpc_threadprivate_cached(), and size.
_mp_copyin_init()
void _mp_copyin_init (void)
_mp_copyin_move()
void _mp_copyin_move (void * blk_tp, int off, int size)
Definition at line 272 of file llcrit.c.
References __kmpc_barrier(), __kmpc_global_thread_num(), __kmpc_threadprivate_cached(), and size.
_mp_copyin_move_al()
void _mp_copyin_move_al (void * blk_tp, int off, long size)
Definition at line 433 of file llcrit.c.
References __kmpc_barrier(), __kmpc_global_thread_num(), __kmpc_threadprivate_cached(), and size.
_mp_copyin_term()
void _mp_copyin_term (void)
_mp_copypriv()
void _mp_copypriv (char * adr, long len, int thread)
Definition at line 180 of file llcrit.c.
References __kmpc_barrier(), __kmpc_global_thread_num(), len, singadr, and singlen.
_mp_copypriv_al()
void _mp_copypriv_al (char ** adr, long len, int thread)
Definition at line 195 of file llcrit.c.
References __kmpc_barrier(), __kmpc_global_thread_num(), len, singadr, and singlen.
_mp_copypriv_init()
void _mp_copypriv_init (void)
_mp_copypriv_move()
void _mp_copypriv_move (void * blk_tp, int off, int size, int single_thread)
Definition at line 216 of file llcrit.c.
References __kmpc_barrier(), __kmpc_global_thread_num(), __kmpc_threadprivate_cached(), singadr, singlen, and size.
_mp_copypriv_term()
void _mp_copypriv_term (void)
_mp_ecs()
void _mp_ecs (void)
Definition at line 48 of file llcrit.c.
References __kmpc_end_critical(), __kmpc_global_thread_num(), and sem_cs.
_mp_ecs_nest()
void _mp_ecs_nest (void)
Definition at line 109 of file llcrit.c.
References nest_lock, and omp_unset_nest_lock().
_mp_ecs_stdio()
void _mp_ecs_stdio (void)
Definition at line 62 of file llcrit.c.
References __kmpc_end_critical(), __kmpc_global_thread_num(), and sem_stdio.
_mp_p()
void _mp_p (kmp_critical_name * sem)
Definition at line 23 of file llcrit.c.
References __kmpc_critical(), __kmpc_global_thread_num(), and sem.
Referenced by _mp_bcs_nest(), _mp_bcs_nest_red(), _mp_calloc(), _mp_free(), _mp_malloc(), and _mp_realloc().
_mp_ptest()
void _mp_ptest (omp_lock_t * sem)
Definition at line 35 of file llcrit.c.
_mp_v()
void _mp_v (kmp_critical_name * sem)
Definition at line 29 of file llcrit.c.
References __kmpc_end_critical(), __kmpc_global_thread_num(), and sem.
Referenced by _mp_bcs_nest(), _mp_bcs_nest_red(), _mp_calloc(), _mp_free(), _mp_malloc(), and _mp_realloc().