flang: lldebug.cpp File Reference
lldebug.cpp File Reference
Main module to generate LLVM debug informations using metadata.
#include "lldebug.h"
#include "dtypeutl.h"
#include "global.h"
#include "symtab.h"
#include "ll_structure.h"
#include "ll_builder.h"
#include "dwarf2.h"
#include "error.h"
#include "version.h"
#include "fih.h"
#include "llassem.h"
#include "cgllvm.h"
#include "cgmain.h"
#include "flang/ADT/hash.h"
#include "symfun.h"
#include "rte.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include "upper.h"
Classes
struct BLKINFO
struct PARAMINFO
struct sptr_to_mdnode_map
struct import_entity
struct LL_DebugInfo
struct CleanupBounds_t
Macros
#define RTE_C
#define GetParamSptr(dpdsc, i) (aux.dpdsc_base[dpdsc + i])
#define DECLLINEG(sptr) 0
#define DW_TAG_return_variable 0x102
#define DW_TAG_vector_type 0x103
#define BLK_STACK_SIZE 1024
#define PARAM_STACK_SIZE 1024
#define F90_DESC_SIZE 10 /* num of fields of Struct F90_Desc */
#define F90_DESCDIM_SIZE 6 /* num of fields of Struct F90_DescDim */
#define MAX_FNAME 1024
Typedefs
typedef struct import_entity import_entity
Functions
static LL_MDRef lldbg_emit_modified_type (LL_DebugInfo *, DTYPE, SPTR, int)
static LL_MDRef lldbg_create_outlined_parameters_node (LL_DebugInfo *db)
static LL_MDRef lldbg_create_file_mdnode (LL_DebugInfo *db, const char *filename, char *sourcedir, LL_MDRef context, int index)
static LL_MDRef lldbg_emit_type (LL_DebugInfo *db, DTYPE dtype, SPTR sptr, int findex, bool is_reference, bool skip_first_dim, bool skipDataDependentTypes, SPTR data_sptr=SPTR_NULL)
static LL_MDRef lldbg_fwd_local_variable (LL_DebugInfo *db, int sptr, int findex, int emit_dummy_as_local)
static LL_MDRef lldbg_create_imported_entity (LL_DebugInfo *db, SPTR entity_sptr, SPTR func_sptr, IMPORT_TYPE entity_type, LL_MDRef elements_mdnode)
static void lldbg_emit_imported_entity (LL_DebugInfo *db, SPTR entity_sptr, SPTR func_sptr, IMPORT_TYPE entity_type, LL_MDRef elements)
static LL_MDRef lldbg_create_subrange_mdnode (LL_DebugInfo *db, LL_MDRef count, LL_MDRef lb, LL_MDRef ub, LL_MDRef st)
static LL_MDRef lldbg_create_generic_subrange_mdnode (LL_DebugInfo *db, LL_MDRef lb, LL_MDRef ub, LL_MDRef st)
static LL_MDRef lldbg_create_subrange_via_sdsc (LL_DebugInfo *db, int findex, SPTR sptr, int rank)
static void lldbg_get_bounds_for_sdsc (LL_DebugInfo *db, int findex, SPTR sptr, int rank, LL_MDRef *count_expr_mdnode, LL_MDRef *lbnd_expr_mdnode, LL_MDRef *ubnd_expr_mdnode, LL_MDRef *stride_expr_mdnode)
static void lldbg_get_bounds_for_assumed_rank_sdsc (LL_DebugInfo *db, SPTR sptr, LL_MDRef *lbnd_expr_mdnode, LL_MDRef *ubnd_expr_mdnode, LL_MDRef *stride_expr_mdnode)
static void lldbg_register_param_mdnode (LL_DebugInfo *db, LL_MDRef mdnode, int sptr)
static INLINE int set_dilocalvariable_flags (int sptr)
Construct the flag set that corresponds with LLVM metadata.
void InitializeDIFlags (const LL_IRFeatures *feature)
char * lldbg_alloc (INT size)
...
int lldbg_get_di_routine_idx (const LL_DebugInfo *db)
Return debuginfo routine index.
static ISZ_T lldbg_get_sizeof (int element)
static int make_dwtag (LL_DebugInfo *db, int tag)
Make an i32 operand with a DWARF tag and possibly a version number.
static LL_MDRef lldbg_create_module_flag_mdnode (LL_DebugInfo *db, int severity, const char *name, int value)
static LL_MDRef get_file_mdnode (LL_DebugInfo *db, int index)
static LL_MDRef get_filedesc_mdnode (LL_DebugInfo *db, int index)
static LL_MDRef lldbg_create_compile_unit_mdnode (LL_DebugInfo *db, int lang_tag, const char *filename, char *sourcedir, char *producer, int main, bool optimized, const char *compflags, int vruntime, LL_MDRef *enum_types_list, LL_MDRef *retained_types_list, LL_MDRef *subprograms_list, LL_MDRef *gv_list, LL_MDRef *imported_entity_list)
static LL_MDRef lldbg_create_module_mdnode (LL_DebugInfo *db, LL_MDRef _, char *name, LL_MDRef scope, LL_MDRef file, int lineno)
static void lldbg_create_subprogram_mdnode (LL_DebugInfo *db, LL_MDRef context, const char *routine, const char *mips_linkage_name, LL_MDRef def_context, int line, LL_MDRef type_mdnode, int is_local, int is_definition, int virtuality, int vindex, int spFlags, int flags, bool is_optimized, LL_MDRef template_param_mdnode, LL_MDRef decl_desc_mdnode, LL_MDRef lv_list_mdnode, int scope)
Create a sub-program mdnode and store it in db->cur_subprogram_mdnode.
void lldbg_set_func_ptr (LL_DebugInfo *db, LL_Value *func_ptr)
LL_MDRef lldbg_subprogram (LL_DebugInfo *db)
void lldbg_reset_module (LL_DebugInfo *db)
static LL_MDRef lldbg_create_global_variable_mdnode (LL_DebugInfo *db, LL_MDRef context, const char *display_name, const char *name, const char *mips_linkage_name, LL_MDRef def_context, int line, LL_MDRef type_mdnode, int is_local, int is_definition, LL_Value *var_ptr, int addrspace, int flags, ISZ_T off, SPTR sptr, LL_MDRef fwd)
static LL_MDRef lldbg_create_block_mdnode (LL_DebugInfo *db, LL_MDRef routine_context, int line, int column, int findex, int ID)
static INLINE LL_MDRef lldbg_create_string_type_mdnode (LL_DebugInfo *db, ISZ_T sz, DBLINT64 alignment, const char *name, int encoding)
static LL_MDRef lldbg_create_basic_type_mdnode (LL_DebugInfo *db, LL_MDRef context, const char *name, LL_MDRef fileref, int line, ISZ_T sz, DBLINT64 alignment, DBLINT64 offset, int flags, int dwarf_encoding)
static LL_MDRef lldbg_create_pointer_type_mdnode (LL_DebugInfo *db, LL_MDRef context, const char *name, LL_MDRef fileref, int line, ISZ_T sz, DBLINT64 alignment, DBLINT64 offset, int flags, LL_MDRef pts_to)
static LL_MDRef lldbg_create_ftn_array_type_mdnode (LL_DebugInfo *db, LL_MDRef context, int line, ISZ_T sz, DBLINT64 alignment, LL_MDRef eleTy, LL_MDRef subscripts)
static LL_MDRef lldbg_create_array_type_mdnode (LL_DebugInfo *db, LL_MDRef context, int line, ISZ_T sz, DBLINT64 alignment, LL_MDRef pts_to, LL_MDRef subscripts, LL_MDRef data_location, LL_MDRef associated, LL_MDRef allocated, LL_MDRef rank)
Create an array type, DW_TAG_array_type.
static LL_MDRef lldbg_create_aggregate_type_mdnode (LL_DebugInfo *db, int dw_tag, LL_MDRef context, const char *name, LL_MDRef fileref, int line, ISZ_T sz, DBLINT64 alignment, int flags, LL_MDRef members, int runtime)
static LL_MDRef lldbg_create_structure_type_mdnode (LL_DebugInfo *db, LL_MDRef context, const char *name, LL_MDRef fileref, int line, ISZ_T sz, DBLINT64 alignment, int flags, LL_MDRef members, int runtime)
static LL_MDRef lldbg_create_union_type_mdnode (LL_DebugInfo *db, LL_MDRef context, const char *name, LL_MDRef fileref, int line, ISZ_T sz, DBLINT64 alignment, int flags, LL_MDRef members, int runtime)
static LL_MDRef lldbg_create_member_mdnode (LL_DebugInfo *db, LL_MDRef fileref, LL_MDRef parent_mdnode, const char *name, int line, ISZ_T sz, DBLINT64 alignment, DBLINT64 offset, int flags, LL_MDRef type_mdnode, LL_MDRef fwd)
static void lldbg_create_aggregate_members_type (LL_DebugInfo *db, SPTR first, int findex, LL_MDRef file_mdnode, LL_MDRef members_mdnode, LL_MDRef parent_mdnode)
static void get_extra_info_for_sptr (const char **display_name, LL_MDRef *scope_mdnode, LL_MDRef *type_mdnode, LL_DebugInfo *db, int sptr)
Fill in extra data about a symbol.
static LL_MDRef lldbg_create_vector_type_mdnode (LL_DebugInfo *db, LL_MDRef context, ISZ_T sz, DBLINT64 alignment, LL_MDRef type, LL_MDRef subscripts)
static LL_MDRef lldbg_create_subroutine_type_mdnode (LL_DebugInfo *db, LL_MDRef context, LL_MDRef fileref, LL_MDRef params, const int cc)
static LL_MDRef emit_deref_expression_mdnode (LL_DebugInfo *db)
static LL_MDRef lldbg_create_ftn_subrange_mdnode (LL_DebugInfo *db, ISZ_T clb, LL_MDRef lbv, ISZ_T cub, LL_MDRef ubv)
static LL_MDRef lldbg_create_ftn_subrange_via_sdsc (LL_DebugInfo *db, int findex, SPTR sptr, int rank)
static LL_MDRef lldbg_create_subrange_mdnode_pre11 (LL_DebugInfo *db, ISZ_T lb, ISZ_T ub)
static LL_MDRef lldbg_create_unspecified_mdnode (LL_DebugInfo *db, int dw_tag)
static LL_MDRef lldbg_create_unspecified_type_mdnode (LL_DebugInfo *db)
static LL_MDRef lldbg_create_unspecified_parameters_mdnode (LL_DebugInfo *db)
LL_MDRef lldbg_emit_empty_expression_mdnode (LL_DebugInfo *db)
int lldbg_encode_expression_arg (LL_DW_OP_t op, int value)
Encode an argument to lldbg_emit_expression_mdnode()
LL_MDRef lldbg_emit_expression_mdnode (LL_DebugInfo *db, unsigned cnt,...)
static LL_MDRef lldbg_create_local_variable_mdnode (LL_DebugInfo *db, int dw_tag, LL_MDRef context, char *name, LL_MDRef fileref, int line, int argnum, LL_MDRef type_mdnode, int flags, LL_MDRef fwd, int sptr=0)
static LL_MDRef lldbg_create_location_mdnode (LL_DebugInfo *db, int line, int column, LL_MDRef scope)
void lldbg_reset_dtype_array (LL_DebugInfo *db, const int off)
void lldbg_update_arrays (LL_DebugInfo *db, int lastDType, int newSz)
void lldbg_init_arrays (LL_DebugInfo *db)
void lldbg_init (LL_Module *module)
void lldbg_free_import_entity_list (import_entity *import_entity_list)
void lldbg_free (LL_DebugInfo *db)
static char * double_backslash (char *name)
Double any backslash characters in name.
static char * get_filename (int findex)
Get the filename associated with file index, findex.
static char * get_currentdir (void)
LL_MDRef lldbg_emit_compile_unit (LL_DebugInfo *db)
Create a metadata node for the current compile unit.
static LL_MDRef lldbg_emit_file (LL_DebugInfo *db, int findex)
static LOGICAL is_procedure_dtype (DTYPE dtype)
static LOGICAL is_procedure_ptr_dtype (DTYPE dtype)
LOGICAL is_procedure_ptr (SPTR sptr)
static LL_MDRef lldbg_emit_parameter_list (LL_DebugInfo *db, DTYPE dtype, DTYPE ret_dtype, SPTR sptr, int findex)
static INLINE LL_MDRef lldbg_emit_subroutine_type (LL_DebugInfo *db, SPTR sptr, DTYPE ret_dtype, int findex, LL_MDRef file_mdnode)
static LL_MDRef lldbg_emit_outlined_subroutine (LL_DebugInfo *db, int sptr, int ret_dtype, int findex, LL_MDRef file_mdnode)
static void lldbg_reserve_lexical_block (LL_DebugInfo *db, int sptr, int lineno, int findex)
static BLKINFO * lldbg_limit_lexical_blocks (LL_DebugInfo *db, int startline)
static void lldbg_assign_lexical_block (LL_DebugInfo *db, int idx, int findex, bool targetNVVM)
static void lldbg_emit_lexical_block (LL_DebugInfo *db, int sptr, int lineno, int findex, bool targetNVVM)
static void lldbg_emit_lexical_blocks (LL_DebugInfo *db, int sptr, int findex, bool targetNVVM)
static void lldbg_reserve_lexical_blocks (LL_DebugInfo *db, int sptr, int findex)
static void lldbg_assign_lexical_blocks (LL_DebugInfo *db, int findex, BLKINFO *parent_blk, bool targetNVVM)
static INLINE int set_disubprogram_flags (LL_DebugInfo *db, int sptr)
Construct the flag set that corresponds with LLVM metadata.
static INLINE int set_disubprogram_spflags (LL_DebugInfo *db, int sptr, bool is_def, bool is_local, bool is_optimized)
void lldbg_emit_outlined_subprogram (LL_DebugInfo *db, int sptr, int findex, const char *func_name, int startlineno, bool targetNVVM)
Create a metadata node for the outlined subprogram sptr.
LL_MDRef lldbg_emit_module_mdnode (LL_DebugInfo *db, int sptr)
void lldbg_emit_subprogram (LL_DebugInfo *db, SPTR sptr, DTYPE ret_dtype, int findex, bool targetNVVM)
Create a metadata node for the current subprogram.
static INLINE bool getLexBlock_notCurrentFunc (const int fn)
Is fn a function, but not the current function?
LL_MDRef lldbg_get_var_line (LL_DebugInfo *db, int sptr)
static BLKINFO * get_lexical_block_info (LL_DebugInfo *db, int sptr, bool unchecked)
void lldbg_emit_line (LL_DebugInfo *db, int lineno)
LL_MDRef lldbg_get_line (LL_DebugInfo *db)
LL_MDRef lldbg_cons_line (LL_DebugInfo *db)
Always produce !dbg metadata for current location.
static int dwarf_encoding (DTYPE dtype)
void lldbg_emit_outlined_parameter_list (LL_DebugInfo *db, int findex, DTYPE *param_dtypes, int num_args)
static INLINE void dtype_array_check_set (LL_DebugInfo *db, DTYPE at, LL_MDRef md)
static INLINE bool is_assumed_char (DTYPE dtype)
static INLINE bool is_deferred_char (DTYPE dtype)
static INLINE char * next_assumed_len_character_name (void)
static INLINE LL_MDRef lldbg_create_assumed_len_string_type_mdnode (LL_DebugInfo *db, SPTR sptr, int findex)
static INLINE LL_MDRef lldbg_create_deferred_len_string_type_mdnode (LL_DebugInfo *db, SPTR sptr, int findex)
static INLINE void init_subrange_bound_pre11 (LL_DebugInfo *db, ISZ_T *cb, LL_MDRef *bound_sptr, SPTR sptr, ISZ_T defVal, int findex)
Initialize the subrange bound variables.
static INLINE void init_subrange_bound (LL_DebugInfo *db, LL_MDRef *bound_sptr, SPTR sptr, ISZ_T defVal, int findex)
static void llObjtodbgAddUnique (LL_ObjToDbgList *odl, LL_MDRef mdadd)
void lldbg_emit_global_variable (LL_DebugInfo *db, SPTR sptr, ISZ_T off, int findex, LL_Value *value)
static void lldbg_cancel_value_call (LL_DebugInfo *db, SPTR sptr)
void lldbg_register_value_call (LL_DebugInfo *db, INSTR_LIST *instr, int sptr)
LL_MDRef get_param_mdnode (LL_DebugInfo *db, int sptr)
void lldbg_emit_lv_list (LL_DebugInfo *db)
LL_MDRef lldbg_emit_local_variable (LL_DebugInfo *db, SPTR sptr, int findex, int emit_dummy_as_local)
static void cleanup_bounds (hash_key_t ksptr, hash_data_t dmdnode, void *ctxt)
void lldbg_cleanup_missing_bounds (LL_DebugInfo *db, int findex)
LL_MDRef lldbg_emit_param_variable (LL_DebugInfo *db, SPTR sptr, int findex, int parnum, bool unnamed)
LL_MDRef lldbg_emit_ptr_param_variable (LL_DebugInfo *db, SPTR sptr, int findex, int parnum)
void lldbg_function_end (LL_DebugInfo *db, int func)
void lldbg_create_cmblk_mem_mdnode_list (SPTR sptr, SPTR gblsym)
static LL_MDRef lldbg_create_common_block_mdnode (LL_DebugInfo *db, LL_MDRef scope, char *name)
LL_MDRef lldbg_emit_common_block_mdnode (LL_DebugInfo *db, SPTR sptr)
void lldbg_add_pending_import_entity_to_child (LL_DebugInfo *db, SPTR entity, IMPORT_TYPE entity_type)
void lldbg_add_pending_import_entity (LL_DebugInfo *db, SPTR entity, IMPORT_TYPE entity_type)
const char * new_debug_name (const char *str1, const char *str2, const char *str3)
LL_MDRef lldbg_get_subprogram_line (LL_DebugInfo *db)
Variables
const int DIFLAG_ARTIFICIAL = 1 << 6
const int DIFLAG_ISMAINPGM = 1 << 21
static int DIFLAG_PURE
static int DIFLAG_ELEMENTAL
static int DIFLAG_RECURSIVE
const int DISPFLAG_LOCALTOUNIT = 1 << 2
const int DISPFLAG_DEFINITION = 1 << 3
const int DISPFLAG_OPTIMIZED = 1 << 4
const int DISPFLAG_PURE = 1 << 5
const int DISPFLAG_ELEMENTAL = 1 << 6
const int DISPFLAG_RECURSIVE = 1 << 7
const int DISPFLAG_MAINSUBPROGRAM = 1 << 8
Detailed Description
Main module to generate LLVM debug informations using metadata.
Definition in file lldebug.cpp.
Macro Definition Documentation
BLK_STACK_SIZE
#define BLK_STACK_SIZE 1024
Definition at line 121 of file lldebug.cpp.
DECLLINEG
#define DECLLINEG (sptr) 0
Definition at line 58 of file lldebug.cpp.
DW_TAG_return_variable
#define DW_TAG_return_variable 0x102
Definition at line 70 of file lldebug.cpp.
DW_TAG_vector_type
#define DW_TAG_vector_type 0x103
Definition at line 74 of file lldebug.cpp.
F90_DESC_SIZE
#define F90_DESC_SIZE 10 /* num of fields of Struct F90_Desc */
Definition at line 1264 of file lldebug.cpp.
F90_DESCDIM_SIZE
#define F90_DESCDIM_SIZE 6 /* num of fields of Struct F90_DescDim */
Definition at line 1265 of file lldebug.cpp.
GetParamSptr
#define GetParamSptr (dpdsc, i) (aux.dpdsc_base[dpdsc + i])
Definition at line 54 of file lldebug.cpp.
MAX_FNAME
#define MAX_FNAME 1024
Definition at line 1832 of file lldebug.cpp.
PARAM_STACK_SIZE
#define PARAM_STACK_SIZE 1024
Definition at line 122 of file lldebug.cpp.
RTE_C
#define RTE_C
Definition at line 28 of file lldebug.cpp.
Typedef Documentation
import_entity
typedef struct import_entity import_entity
Function Documentation
cleanup_bounds()
static void cleanup_bounds (hash_key_t ksptr, hash_data_t dmdnode, void * ctxt) static
Definition at line 3928 of file lldebug.cpp.
References db(), HKEY2INT, lldbg_emit_local_variable(), s, and sptr.
Referenced by lldbg_cleanup_missing_bounds().
double_backslash()
static char * double_backslash (char * name) static
Double any backslash characters in name.
Parameters
name A filename
Precondition: name must be allocated on the heap, as it may be deallocated.
Definition at line 1772 of file lldebug.cpp.
References FREE, len, name, and NEW.
Referenced by get_filename().
dtype_array_check_set()
static INLINE void dtype_array_check_set (LL_DebugInfo * db, DTYPE at, LL_MDRef md) static
Definition at line 2797 of file lldebug.cpp.
References db().
Referenced by lldbg_emit_global_variable(), and lldbg_emit_type().
dwarf_encoding()
static int dwarf_encoding (DTYPE dtype) static
Definition at line 2667 of file lldebug.cpp.
References DTY, DW_ATE_address, DW_ATE_boolean, DW_ATE_complex_float, DW_ATE_float, DW_ATE_signed, DW_ATE_unsigned, TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_ISUNSIGNED, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by lldbg_create_basic_type_mdnode(), and lldbg_emit_type().
emit_deref_expression_mdnode()
static LL_MDRef emit_deref_expression_mdnode (LL_DebugInfo * db) static
Definition at line 1217 of file lldebug.cpp.
References db(), deref, LL_DW_OP_deref, lldbg_emit_expression_mdnode(), and lldbg_encode_expression_arg().
Referenced by lldbg_create_ftn_subrange_mdnode().
get_currentdir()
static char * get_currentdir (void) static
Definition at line 1835 of file lldebug.cpp.
References malloc().
Referenced by lldbg_emit_compile_unit(), and lldbg_emit_file().
get_extra_info_for_sptr()
static void get_extra_info_for_sptr (const char ** display_name, LL_MDRef * scope_mdnode, LL_MDRef * type_mdnode, LL_DebugInfo * db, int sptr) static
Fill in extra data about a symbol.
Probes any debug symbol information that may have been saved by the front-end in order to generate a good display name and proper namespace or class scope for a symbol. Falls back to the symbol table name and the compile unit's outermost scope if better symbolic information cannot be found.
Definition at line 1051 of file lldebug.cpp.
References db(), ll_get_md_null, lldbg_emit_compile_unit(), NULL, sptr, and SYMNAME.
Referenced by lldbg_emit_global_variable(), and lldbg_emit_subprogram().
get_file_mdnode()
static LL_MDRef get_file_mdnode (LL_DebugInfo * db, int index) static
Definition at line 293 of file lldebug.cpp.
References db(), index, and ll_get_md_null.
Referenced by lldbg_create_block_mdnode(), and lldbg_emit_file().
get_filedesc_mdnode()
static LL_MDRef get_filedesc_mdnode (LL_DebugInfo * db, int index) static
Definition at line 301 of file lldebug.cpp.
References db(), index, and ll_get_md_null.
Referenced by lldbg_create_aggregate_members_type(), lldbg_create_block_mdnode(), lldbg_create_compile_unit_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_imported_entity(), lldbg_emit_file(), lldbg_emit_global_variable(), lldbg_emit_local_variable(), lldbg_emit_outlined_subprogram(), lldbg_emit_param_variable(), lldbg_emit_ptr_param_variable(), lldbg_emit_subprogram(), and lldbg_emit_type().
get_filename()
static char * get_filename (int findex) static
Get the filename associated with file index, findex.
Parameters
findex The file's index
Returns
a heap allocated string; caller must deallocate.
Definition at line 1810 of file lldebug.cpp.
References dirname, double_backslash(), FIH_DIRNAME, FIH_FILENAME, filename, NEW, and strlen().
Referenced by lldbg_emit_compile_unit(), and lldbg_emit_file().
get_lexical_block_info()
static BLKINFO * get_lexical_block_info (LL_DebugInfo * db, int sptr, bool unchecked) static
Definition at line 2551 of file lldebug.cpp.
References assert, db(), ERR_Fatal, flg, fn, getLexBlock_notCurrentFunc(), idx, NULL, FLG::smp, and sptr.
Referenced by lldbg_create_deferred_len_string_type_mdnode(), lldbg_emit_local_variable(), and lldbg_emit_type().
get_param_mdnode()
LL_MDRef get_param_mdnode (LL_DebugInfo * db, int sptr)
Definition at line 3755 of file lldebug.cpp.
References db(), i, ll_get_md_null, and sptr.
Referenced by formalsAddDebug(), and lldbg_emit_local_variable().
getLexBlock_notCurrentFunc()
static INLINE bool getLexBlock_notCurrentFunc (const int fn) static
Is fn a function, but not the current function?
Parameters
fn The symbol to test
Helper to hide the differences between compilers.
Definition at line 2508 of file lldebug.cpp.
References fn, and gbl.
Referenced by get_lexical_block_info(), and lldbg_get_var_line().
init_subrange_bound()
static INLINE void init_subrange_bound (LL_DebugInfo * db, LL_MDRef * bound_sptr, SPTR sptr, ISZ_T defVal, int findex) static
Definition at line 3032 of file lldebug.cpp.
References ad_val_of(), db(), ll_get_md_i64(), lldbg_fwd_local_variable(), and sptr.
Referenced by lldbg_emit_type().
init_subrange_bound_pre11()
static INLINE void init_subrange_bound_pre11 (LL_DebugInfo * db, ISZ_T * cb, LL_MDRef * bound_sptr, SPTR sptr, ISZ_T defVal, int findex) static
Initialize the subrange bound variables.
Parameters
cb The value of a constant bound (or 0) [output]
bound_sptr A forward metadata reference for sptr [output]
sptr The symbol corresponding to the bound
defVal The default value for cb, the constant bound
findex Pass through argument for creating forward reference
db The debug info
Definition at line 3007 of file lldebug.cpp.
References ad_val_of(), db(), ll_get_md_null, lldbg_fwd_local_variable(), and sptr.
Referenced by lldbg_emit_type().
InitializeDIFlags()
void InitializeDIFlags (const LL_IRFeatures * feature)
Definition at line 218 of file lldebug.cpp.
References DIFLAG_ELEMENTAL, DIFLAG_PURE, DIFLAG_RECURSIVE, feature, and ll_feature_debug_info_ver70.
Referenced by compute_ir_feature_vector().
is_assumed_char()
static INLINE bool is_assumed_char (DTYPE dtype) static
Definition at line 2804 of file lldebug.cpp.
References DTY, and TY_CHAR.
Referenced by lldbg_emit_type().
is_deferred_char()
static INLINE bool is_deferred_char (DTYPE dtype) static
Definition at line 2810 of file lldebug.cpp.
References DTY, and TY_CHAR.
Referenced by lldbg_emit_type().
is_procedure_dtype()
static LOGICAL is_procedure_dtype (DTYPE dtype) static
Definition at line 1874 of file lldebug.cpp.
References DTY.
Referenced by is_procedure_ptr_dtype().
is_procedure_ptr()
LOGICAL is_procedure_ptr (SPTR sptr)
Definition at line 1885 of file lldebug.cpp.
References FALSE, is_procedure_ptr_dtype(), NOSYM, and sptr.
Referenced by lldbg_emit_global_variable(), lldbg_emit_local_variable(), and lldbg_emit_type().
is_procedure_ptr_dtype()
static LOGICAL is_procedure_ptr_dtype (DTYPE dtype) static
Definition at line 1879 of file lldebug.cpp.
References DTY, DTySeqTyElement, and is_procedure_dtype().
Referenced by is_procedure_ptr().
lldbg_add_pending_import_entity()
void lldbg_add_pending_import_entity (LL_DebugInfo * db, SPTR entity, IMPORT_TYPE entity_type)
Definition at line 4276 of file lldebug.cpp.
References db(), import_entity::entity, gbl, lldbg_alloc(), new_node(), import_entity::next, and NULL.
Referenced by add_debug_cmnblk_variables().
lldbg_add_pending_import_entity_to_child()
void lldbg_add_pending_import_entity_to_child (LL_DebugInfo * db, SPTR entity, IMPORT_TYPE entity_type)
Definition at line 4261 of file lldebug.cpp.
References db(), gbl, lldbg_alloc(), new_node(), and NULL.
Referenced by add_debug_cmnblk_variables().
lldbg_alloc()
char * lldbg_alloc (INT size)
...
Definition at line 236 of file lldebug.cpp.
References assert, ERR_Fatal, getitem(), LLVM_LONGTERM_AREA, p, and size.
Referenced by lldbg_add_pending_import_entity(), lldbg_add_pending_import_entity_to_child(), lldbg_create_common_block_mdnode(), lldbg_create_module_mdnode(), lldbg_emit_local_variable(), lldbg_emit_param_variable(), lldbg_emit_ptr_param_variable(), and new_debug_name().
lldbg_assign_lexical_block()
static void lldbg_assign_lexical_block (LL_DebugInfo * db, int idx, int findex, bool targetNVVM) static
Definition at line 2059 of file lldebug.cpp.
References assert, db(), BLKINFO::endline, ERR_Severe, i, idx, lineno, lldbg_create_block_mdnode(), lldbg_create_location_mdnode(), BLKINFO::mdnode, NULL, startline, and BLKINFO::startline.
Referenced by lldbg_assign_lexical_blocks().
lldbg_assign_lexical_blocks()
static void lldbg_assign_lexical_blocks (LL_DebugInfo * db, int findex, BLKINFO * parent_blk, bool targetNVVM) static
Definition at line 2266 of file lldebug.cpp.
References db(), idx, lldbg_assign_lexical_block(), BLKINFO::mdnode, and NULL.
Referenced by lldbg_emit_outlined_subprogram().
lldbg_cancel_value_call()
static void lldbg_cancel_value_call (LL_DebugInfo * db, SPTR sptr) static
Definition at line 3725 of file lldebug.cpp.
References CANCEL_CALL_DBG_VALUE, db(), i, and sptr.
Referenced by lldbg_emit_local_variable().
lldbg_cleanup_missing_bounds()
void lldbg_cleanup_missing_bounds (LL_DebugInfo * db, int findex)
Definition at line 3938 of file lldebug.cpp.
References cleanup_bounds(), db(), hashmap_clear(), hashmap_iterate(), hashmap_size(), and s.
Referenced by schedule().
lldbg_cons_line()
LL_MDRef lldbg_cons_line (LL_DebugInfo * db)
Always produce !dbg metadata for current location.
This produces location info even when none exists.
Definition at line 2659 of file lldebug.cpp.
References db(), LL_MDREF_IS_NULL, and lldbg_get_line().
Referenced by emit_dbg_from_module().
lldbg_create_aggregate_members_type()
static void lldbg_create_aggregate_members_type (LL_DebugInfo * db, SPTR first, int findex, LL_MDRef file_mdnode, LL_MDRef members_mdnode, LL_MDRef parent_mdnode) static
Definition at line 944 of file lldebug.cpp.
References alignment(), assert, db(), ERR_Fatal, first, fwd, get_filedesc_mdnode(), hashmap_erase(), hashmap_lookup(), INT2HKEY, ISZ_T, ll_extend_md_node(), ll_feature_debug_info_pre34, ll_feature_debug_info_ver90, ll_get_md_null, lldbg_create_member_mdnode(), lldbg_emit_type(), lldbg_get_sizeof(), NOSYM, NULL, offset, SPTR_NULL, SYMNAME, sz, and val.
Referenced by lldbg_emit_type().
lldbg_create_aggregate_type_mdnode()
static LL_MDRef lldbg_create_aggregate_type_mdnode (LL_DebugInfo * db, int dw_tag, LL_MDRef context, const char * name, LL_MDRef fileref, int line, ISZ_T sz, DBLINT64 alignment, int flags, LL_MDRef members, int runtime) static
Definition at line 845 of file lldebug.cpp.
References alignment(), db(), flags, ISZ_2_INT64, line, LL_DICompositeType, ll_feature_debug_info_pre34, llmd_add_i32(), llmd_add_INT64(), llmd_add_md(), llmd_add_null(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), make_dwtag(), name, size, and sz.
Referenced by lldbg_create_structure_type_mdnode(), and lldbg_create_union_type_mdnode().
lldbg_create_array_type_mdnode()
static LL_MDRef lldbg_create_array_type_mdnode (LL_DebugInfo * db, LL_MDRef context, int line, ISZ_T sz, DBLINT64 alignment, LL_MDRef pts_to, LL_MDRef subscripts, LL_MDRef data_location, LL_MDRef associated, LL_MDRef allocated, LL_MDRef rank) static
Create an array type, DW_TAG_array_type.
Parameters
db
context
line line number
sz size of array, must be in bits
alignment alignment of array
pts_to
subscripts
data_location
associated
allocated
rank
Definition at line 783 of file lldebug.cpp.
References alignment(), db(), DW_TAG_array_type, ISZ_2_INT64, line, LL_DICompositeType, ll_feature_debug_info_pre34, ll_feature_debug_info_ver90, LL_MDREF_IS_NULL, llmd_add_i32(), llmd_add_INT64(), llmd_add_md(), llmd_add_null(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), make_dwtag(), rank, size, and sz.
Referenced by lldbg_emit_type().
lldbg_create_assumed_len_string_type_mdnode()
static INLINE LL_MDRef lldbg_create_assumed_len_string_type_mdnode (LL_DebugInfo * db, SPTR sptr, int findex) static
Definition at line 2825 of file lldebug.cpp.
References alignment(), cg_fetch_clen_parampos(), db(), DW_TAG_string_type, LL_DIStringType, ll_get_md_null, lldbg_emit_empty_expression_mdnode(), lldbg_emit_param_variable(), llmd_add_i32(), llmd_add_i64(), llmd_add_md(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), make_dwtag(), name, next_assumed_len_character_name(), size, and sptr.
Referenced by lldbg_emit_type().
lldbg_create_basic_type_mdnode()
static LL_MDRef lldbg_create_basic_type_mdnode (LL_DebugInfo * db, LL_MDRef context, const char * name, LL_MDRef fileref, int line, ISZ_T sz, DBLINT64 alignment, DBLINT64 offset, int flags, int dwarf_encoding) static
Definition at line 686 of file lldebug.cpp.
References alignment(), db(), DW_TAG_base_type, dwarf_encoding(), flags, ISZ_2_INT64, line, LL_DIBasicType, ll_feature_debug_info_pre34, llmd_add_i32(), llmd_add_INT64(), llmd_add_md(), llmd_add_null(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), make_dwtag(), name, offset, size, and sz.
Referenced by lldbg_emit_type().
lldbg_create_block_mdnode()
static LL_MDRef lldbg_create_block_mdnode (LL_DebugInfo * db, LL_MDRef routine_context, int line, int column, int findex, int ID) static
Definition at line 642 of file lldebug.cpp.
References db(), DW_TAG_lexical_block, get_file_mdnode(), get_filedesc_mdnode(), line, LL_DILexicalBlock, ll_feature_debug_info_pre34, llmd_add_i32(), llmd_add_md(), llmd_finish(), llmd_init(), llmd_set_class(), and make_dwtag().
Referenced by lldbg_assign_lexical_block(), and lldbg_emit_lexical_block().
lldbg_create_cmblk_mem_mdnode_list()
void lldbg_create_cmblk_mem_mdnode_list (SPTR sptr, SPTR gblsym)
Definition at line 4192 of file lldebug.cpp.
References AG_OBJTODBGLIST, cpu_llvm_module, ll_get_global_debug(), LL_MDREF_IS_NULL, llObjtodbgAddUnique(), llObjtodbgCreate(), NOSYM, and sptr.
Referenced by get_ag(), and make_gblsym().
lldbg_create_common_block_mdnode()
static LL_MDRef lldbg_create_common_block_mdnode (LL_DebugInfo * db, LL_MDRef scope, char * name) static
Definition at line 4211 of file lldebug.cpp.
References db(), LL_DICommonBlock, ll_get_md_null, lldbg_alloc(), llmd_add_md(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), llmd_set_distinct(), name, scope, and strlen().
Referenced by lldbg_emit_common_block_mdnode().
lldbg_create_compile_unit_mdnode()
static LL_MDRef lldbg_create_compile_unit_mdnode (LL_DebugInfo * db, int lang_tag, const char * filename, char * sourcedir, char * producer, int main, bool optimized, const char * compflags, int vruntime, LL_MDRef * enum_types_list, LL_MDRef * retained_types_list, LL_MDRef * subprograms_list, LL_MDRef * gv_list, LL_MDRef * imported_entity_list) static
Definition at line 309 of file lldebug.cpp.
References db(), DW_TAG_compile_unit, filename, get_filedesc_mdnode(), ll_create_flexible_md_node(), LL_DICompileUnit, ll_extend_named_md_node(), ll_feature_debug_info_pre34, ll_feature_subprogram_not_in_cu, ll_get_md_node(), ll_get_md_null, LL_MDREF_IS_NULL, LL_PlainMDNode, lldbg_create_file_mdnode(), llmd_add_i1(), llmd_add_i32(), llmd_add_md(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), llmd_set_distinct(), main(), make_dwtag(), MD_llvm_dbg_cu, and XBIT.
Referenced by lldbg_emit_compile_unit().
lldbg_create_deferred_len_string_type_mdnode()
static INLINE LL_MDRef lldbg_create_deferred_len_string_type_mdnode (LL_DebugInfo * db, SPTR sptr, int findex) static
Definition at line 2857 of file lldebug.cpp.
References add(), alignment(), CMEMLG, CMEMLP, db(), DIFLAG_ARTIFICIAL, DT_INT, DTY, DW_TAG_auto_variable, DW_TAG_string_type, LL_MDNode::elem, get_filedesc_mdnode(), get_lexical_block_info(), getsymbol(), insert_llvm_dbg_declare(), ll_add_global_debug(), LL_DIStringType, LL_DW_OP_int, LL_DW_OP_plus_uconst, ll_feature_debug_info_need_file_descriptions, ll_get_md_null, LL_MDREF_value, lldbg_create_global_variable_mdnode(), lldbg_create_local_variable_mdnode(), lldbg_emit_empty_expression_mdnode(), lldbg_emit_expression_mdnode(), lldbg_emit_file(), lldbg_emit_type(), lldbg_encode_expression_arg(), llmd_add_i32(), llmd_add_i64(), llmd_add_md(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), llmd_set_distinct(), make_dwtag(), make_mdref_op(), MAXIDLEN, BLKINFO::mdnode, name, NULL, OPF_NONE, size, sptr, and SYMNAME.
Referenced by lldbg_emit_type().
lldbg_create_file_mdnode()
static LL_MDRef lldbg_create_file_mdnode (LL_DebugInfo * db, const char * filename, char * sourcedir, LL_MDRef context, int index) static
Definition at line 433 of file lldebug.cpp.
References db(), DW_TAG_file_type, fihb, filename, index, LL_DIFile, ll_feature_debug_info_pre34, ll_get_md_null, llmd_add_i32(), llmd_add_md(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), make_dwtag(), NEEDB, and FIHB::stg_avail.
Referenced by lldbg_create_compile_unit_mdnode(), and lldbg_emit_file().
lldbg_create_ftn_array_type_mdnode()
static LL_MDRef lldbg_create_ftn_array_type_mdnode (LL_DebugInfo * db, LL_MDRef context, int line, ISZ_T sz, DBLINT64 alignment, LL_MDRef eleTy, LL_MDRef subscripts) static
Definition at line 750 of file lldebug.cpp.
References alignment(), db(), DW_TAG_array_type, line, LL_DIFortranArrayType, llmd_add_i32(), llmd_add_i64(), llmd_add_INT64(), llmd_add_md(), llmd_finish(), llmd_init(), llmd_set_class(), make_dwtag(), and sz.
Referenced by lldbg_emit_type().
lldbg_create_ftn_subrange_mdnode()
static LL_MDRef lldbg_create_ftn_subrange_mdnode (LL_DebugInfo * db, ISZ_T clb, LL_MDRef lbv, ISZ_T cub, LL_MDRef ubv) static
Definition at line 1224 of file lldebug.cpp.
References db(), DW_TAG_subrange_type, emit_deref_expression_mdnode(), LL_DIFortranSubrange, LL_MDREF_IS_NULL, llmd_add_i32(), llmd_add_i64(), llmd_add_md(), llmd_add_null(), llmd_finish(), llmd_init(), llmd_set_class(), and make_dwtag().
Referenced by lldbg_emit_type().
lldbg_create_ftn_subrange_via_sdsc()
static LL_MDRef lldbg_create_ftn_subrange_via_sdsc (LL_DebugInfo * db, int findex, SPTR sptr, int rank) static
Definition at line 1268 of file lldebug.cpp.
References add(), db(), deref, DW_TAG_subrange_type, F90_DESC_SIZE, F90_DESCDIM_SIZE, hashmap_erase(), INT2HKEY, LL_DIFortranSubrange, LL_DW_OP_constu, LL_DW_OP_deref, LL_DW_OP_dup, LL_DW_OP_int, LL_DW_OP_minus, LL_DW_OP_plus, LL_DW_OP_plus_uconst, LL_DW_OP_swap, ll_get_global_debug(), LL_MDREF_IS_NULL, lldbg_emit_expression_mdnode(), lldbg_encode_expression_arg(), lldbg_fwd_local_variable(), llmd_add_i32(), llmd_add_i64(), llmd_add_md(), llmd_finish(), llmd_init(), llmd_set_class(), make_dwtag(), NULL, one, rank, and sptr.
Referenced by lldbg_emit_type().
lldbg_create_generic_subrange_mdnode()
static LL_MDRef lldbg_create_generic_subrange_mdnode (LL_DebugInfo * db, LL_MDRef lb, LL_MDRef ub, LL_MDRef st) static
Definition at line 1521 of file lldebug.cpp.
References db(), DW_TAG_subrange_type, lb, LL_DIGenericSubRange, ll_get_md_null, llmd_add_i32(), llmd_add_md(), llmd_add_null(), llmd_finish(), llmd_init(), llmd_set_class(), make_dwtag(), st, and ub.
Referenced by lldbg_emit_type().
lldbg_create_global_variable_mdnode()
static LL_MDRef lldbg_create_global_variable_mdnode (LL_DebugInfo * db, LL_MDRef context, const char * display_name, const char * name, const char * mips_linkage_name, LL_MDRef def_context, int line, LL_MDRef type_mdnode, int is_local, int is_definition, LL_Value * var_ptr, int addrspace, int flags, ISZ_T off, SPTR sptr, LL_MDRef fwd) static
Definition at line 566 of file lldebug.cpp.
References add(), cnt, cpu_llvm_module, db(), deref, DIFLAG_ARTIFICIAL, DW_TAG_variable, flags, ftn_array_need_debug_info(), fwd, LL_Module::ir, ISZ_T, line, LL_DIGlobalVariable, LL_DIGlobalVariableExpression, LL_DW_OP_deref, LL_DW_OP_int, LL_DW_OP_plus, LL_DW_OP_plus_uconst, ll_extend_md_node(), ll_feature_debug_info_ver70, ll_feature_debug_info_ver90, ll_feature_from_global_to_md, ll_feature_use_5_diexpression, ll_finish_variable(), ll_get_md_value(), lldbg_emit_expression_mdnode(), lldbg_encode_expression_arg(), llmd_add_i32(), llmd_add_md(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), llmd_set_distinct(), make_dwtag(), name, off, sptr, and XBIT.
Referenced by lldbg_create_deferred_len_string_type_mdnode(), and lldbg_emit_global_variable().
lldbg_create_imported_entity()
static LL_MDRef lldbg_create_imported_entity (LL_DebugInfo * db, SPTR entity_sptr, SPTR func_sptr, IMPORT_TYPE entity_type, LL_MDRef elements_mdnode) static
Definition at line 4109 of file lldebug.cpp.
References db(), DW_TAG_imported_declaration, DW_TAG_imported_module, FUNCLINEG, gbl, get_filedesc_mdnode(), if(), LL_DIImportedEntity, ll_extend_md_node(), ll_feature_debug_info_need_file_descriptions, ll_get_md_null, ll_get_module_debug(), lldbg_emit_file(), llmd_add_i32(), llmd_add_md(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), lookup_modvar_alias(), make_dwtag(), new_debug_name(), NULL, and SYMNAME.
Referenced by lldbg_emit_imported_entity(), and lldbg_emit_subprogram().
lldbg_create_local_variable_mdnode()
static LL_MDRef lldbg_create_local_variable_mdnode (LL_DebugInfo * db, int dw_tag, LL_MDRef context, char * name, LL_MDRef fileref, int line, int argnum, LL_MDRef type_mdnode, int flags, LL_MDRef fwd, int sptr = 0) static
Definition at line 1597 of file lldebug.cpp.
References db(), DIFLAG_ARTIFICIAL, flags, fwd, line, LL_DILocalVariable, ll_feature_dbg_local_variable_embeds_argnum, ll_feature_debug_info_ver38, ll_finish_variable(), llmd_add_i32(), llmd_add_md(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), llmd_set_distinct(), make_dwtag(), name, and sptr.
Referenced by lldbg_create_deferred_len_string_type_mdnode(), lldbg_emit_local_variable(), lldbg_emit_param_variable(), lldbg_emit_ptr_param_variable(), and lldbg_emit_type().
lldbg_create_location_mdnode()
static LL_MDRef lldbg_create_location_mdnode (LL_DebugInfo * db, int line, int column, LL_MDRef scope) static
Definition at line 1634 of file lldebug.cpp.
References db(), line, LL_DILocation, llmd_add_i32(), llmd_add_md(), llmd_add_null(), llmd_finish(), llmd_init(), llmd_set_class(), and scope.
Referenced by lldbg_assign_lexical_block(), lldbg_emit_lexical_block(), lldbg_emit_line(), lldbg_emit_outlined_subprogram(), and lldbg_emit_subprogram().
lldbg_create_member_mdnode()
static LL_MDRef lldbg_create_member_mdnode (LL_DebugInfo * db, LL_MDRef fileref, LL_MDRef parent_mdnode, const char * name, int line, ISZ_T sz, DBLINT64 alignment, DBLINT64 offset, int flags, LL_MDRef type_mdnode, LL_MDRef fwd) static
Definition at line 914 of file lldebug.cpp.
References alignment(), db(), DW_TAG_member, flags, fwd, ISZ_2_INT64, line, LL_DIDerivedType, ll_feature_debug_info_pre34, ll_finish_variable(), llmd_add_i32(), llmd_add_INT64(), llmd_add_md(), llmd_add_string(), llmd_init(), llmd_set_class(), make_dwtag(), name, offset, size, and sz.
Referenced by lldbg_create_aggregate_members_type().
lldbg_create_module_flag_mdnode()
static LL_MDRef lldbg_create_module_flag_mdnode (LL_DebugInfo * db, int severity, const char * name, int value) static
Definition at line 280 of file lldebug.cpp.
References db(), llmd_add_i32(), llmd_add_string(), llmd_finish(), llmd_init(), name, and value().
Referenced by lldbg_init().
lldbg_create_module_mdnode()
static LL_MDRef lldbg_create_module_mdnode (LL_DebugInfo * db, LL_MDRef _, char * name, LL_MDRef scope, LL_MDRef file, int lineno) static
Definition at line 381 of file lldebug.cpp.
References cpu_llvm_module, db(), FLG::debug, DW_TAG_module, DW_TAG_namespace, flg, lineno, ll_add_module_debug(), LL_DIModule, LL_DINamespace, ll_feature_debug_info_pre34, ll_feature_debug_info_ver11, ll_feature_no_file_in_namespace, lldbg_alloc(), llmd_add_i32(), llmd_add_md(), llmd_add_null(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), make_dwtag(), LL_Module::module_debug_map, name, scope, and strlen().
Referenced by lldbg_emit_module_mdnode().
lldbg_create_outlined_parameters_node()
static LL_MDRef lldbg_create_outlined_parameters_node (LL_DebugInfo * db) static
Definition at line 2700 of file lldebug.cpp.
References db(), and ll_create_flexible_md_node().
Referenced by lldbg_emit_outlined_subroutine().
lldbg_create_pointer_type_mdnode()
static LL_MDRef lldbg_create_pointer_type_mdnode (LL_DebugInfo * db, LL_MDRef context, const char * name, LL_MDRef fileref, int line, ISZ_T sz, DBLINT64 alignment, DBLINT64 offset, int flags, LL_MDRef pts_to) static
Definition at line 718 of file lldebug.cpp.
References alignment(), db(), DW_TAG_pointer_type, flags, ISZ_2_INT64, line, LL_DIDerivedType, ll_feature_debug_info_pre34, llmd_add_i32(), llmd_add_INT64(), llmd_add_md(), llmd_add_null(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), make_dwtag(), name, offset, size, and sz.
Referenced by lldbg_emit_local_variable(), lldbg_emit_ptr_param_variable(), and lldbg_emit_type().
lldbg_create_string_type_mdnode()
static INLINE LL_MDRef lldbg_create_string_type_mdnode (LL_DebugInfo * db, ISZ_T sz, DBLINT64 alignment, const char * name, int encoding) static
Definition at line 665 of file lldebug.cpp.
References alignment(), db(), DW_TAG_string_type, LL_DIBasicType_string, LL_DIStringType, ll_feature_has_diextensions, llmd_add_i32(), llmd_add_i64(), llmd_add_INT64(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), make_dwtag(), name, and sz.
Referenced by lldbg_emit_type().
lldbg_create_structure_type_mdnode()
static LL_MDRef lldbg_create_structure_type_mdnode (LL_DebugInfo * db, LL_MDRef context, const char * name, LL_MDRef fileref, int line, ISZ_T sz, DBLINT64 alignment, int flags, LL_MDRef members, int runtime) static
Definition at line 892 of file lldebug.cpp.
References alignment(), db(), DW_TAG_structure_type, flags, line, lldbg_create_aggregate_type_mdnode(), name, and sz.
Referenced by lldbg_emit_type().
lldbg_create_subprogram_mdnode()
static void lldbg_create_subprogram_mdnode (LL_DebugInfo * db, LL_MDRef context, const char * routine, const char * mips_linkage_name, LL_MDRef def_context, int line, LL_MDRef type_mdnode, int is_local, int is_definition, int virtuality, int vindex, int spFlags, int flags, bool is_optimized, LL_MDRef template_param_mdnode, LL_MDRef decl_desc_mdnode, LL_MDRef lv_list_mdnode, int scope) static
Create a sub-program mdnode and store it in db->cur_subprogram_mdnode.
Don't set the function pointer field, but remember where it goes in cur_subprogram_func_ptr_offset.
Definition at line 475 of file lldebug.cpp.
References db(), DW_TAG_subprogram, flags, line, LL_DISubprogram, ll_extend_md_node(), ll_feature_debug_info_pre34, ll_feature_debug_info_ver13, ll_feature_debug_info_ver70, ll_feature_debug_info_ver90, ll_feature_subprogram_not_in_cu, ll_get_md_node(), LL_PlainMDNode, llmd_add_i1(), llmd_add_i32(), llmd_add_md(), llmd_add_null(), llmd_add_string(), llmd_finish(), llmd_get_nelems(), llmd_init(), llmd_set_class(), llmd_set_distinct(), make_dwtag(), and scope.
Referenced by lldbg_emit_outlined_subprogram(), and lldbg_emit_subprogram().
lldbg_create_subrange_mdnode()
static LL_MDRef lldbg_create_subrange_mdnode (LL_DebugInfo * db, LL_MDRef count, LL_MDRef lb, LL_MDRef ub, LL_MDRef st) static
Definition at line 1495 of file lldebug.cpp.
References count, db(), DW_TAG_subrange_type, lb, LL_DISubRange, ll_get_md_null, llmd_add_i32(), llmd_add_md(), llmd_add_null(), llmd_finish(), llmd_init(), llmd_set_class(), make_dwtag(), st, and ub.
Referenced by lldbg_create_subrange_via_sdsc(), and lldbg_emit_type().
lldbg_create_subrange_mdnode_pre11()
static LL_MDRef lldbg_create_subrange_mdnode_pre11 (LL_DebugInfo * db, ISZ_T lb, ISZ_T ub) static
Definition at line 1465 of file lldebug.cpp.
References add64(), count, db(), DW_TAG_subrange_type, ISZ_2_INT64, lb, LL_DISubRange, ll_feature_debug_info_pre34, ll_feature_debug_info_subrange_needs_count, llmd_add_i32(), llmd_add_INT64(), llmd_finish(), llmd_init(), llmd_set_class(), make_dwtag(), one, sub64(), and ub.
Referenced by lldbg_emit_type().
lldbg_create_subrange_via_sdsc()
static LL_MDRef lldbg_create_subrange_via_sdsc (LL_DebugInfo * db, int findex, SPTR sptr, int rank) static
Definition at line 1401 of file lldebug.cpp.
References db(), ll_get_md_null, lldbg_create_subrange_mdnode(), lldbg_get_bounds_for_sdsc(), NULL, rank, and sptr.
Referenced by lldbg_emit_type().
lldbg_create_subroutine_type_mdnode()
static LL_MDRef lldbg_create_subroutine_type_mdnode (LL_DebugInfo * db, LL_MDRef context, LL_MDRef fileref, LL_MDRef params, const int cc) static
Definition at line 1189 of file lldebug.cpp.
References db(), DW_TAG_subroutine_type, LL_DISubroutineType, ll_feature_subprogram_not_in_cu, llmd_add_i32(), llmd_add_i64(), llmd_add_md(), llmd_add_null(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), make_dwtag(), and params.
Referenced by lldbg_emit_outlined_subroutine(), lldbg_emit_subroutine_type(), and lldbg_emit_type().
lldbg_create_union_type_mdnode()
static LL_MDRef lldbg_create_union_type_mdnode (LL_DebugInfo * db, LL_MDRef context, const char * name, LL_MDRef fileref, int line, ISZ_T sz, DBLINT64 alignment, int flags, LL_MDRef members, int runtime) static
Definition at line 903 of file lldebug.cpp.
References alignment(), db(), DW_TAG_union_type, flags, line, lldbg_create_aggregate_type_mdnode(), name, and sz.
Referenced by lldbg_emit_type().
lldbg_create_unspecified_mdnode()
static LL_MDRef lldbg_create_unspecified_mdnode (LL_DebugInfo * db, int dw_tag) static
Definition at line 1542 of file lldebug.cpp.
References db(), llmd_add_i32(), llmd_finish(), llmd_init(), and make_dwtag().
Referenced by lldbg_create_unspecified_parameters_mdnode().
lldbg_create_unspecified_parameters_mdnode()
static LL_MDRef lldbg_create_unspecified_parameters_mdnode (LL_DebugInfo * db) static
Definition at line 1558 of file lldebug.cpp.
References db(), DW_TAG_unspecified_parameters, and lldbg_create_unspecified_mdnode().
Referenced by lldbg_emit_outlined_parameter_list(), and lldbg_emit_parameter_list().
lldbg_create_unspecified_type_mdnode()
static LL_MDRef lldbg_create_unspecified_type_mdnode (LL_DebugInfo * db) static
Definition at line 1552 of file lldebug.cpp.
References ll_get_md_null.
Referenced by lldbg_emit_outlined_parameter_list(), and lldbg_emit_parameter_list().
lldbg_create_vector_type_mdnode()
static LL_MDRef lldbg_create_vector_type_mdnode (LL_DebugInfo * db, LL_MDRef context, ISZ_T sz, DBLINT64 alignment, LL_MDRef type, LL_MDRef subscripts) static
Definition at line 1128 of file lldebug.cpp.
References alignment(), db(), DW_TAG_array_type, ISZ_2_INT64, LL_DICompositeType, llmd_add_i32(), llmd_add_INT64(), llmd_add_md(), llmd_add_null(), llmd_add_string(), llmd_finish(), llmd_init(), llmd_set_class(), make_dwtag(), size, sz, and type.
Referenced by lldbg_emit_type().
lldbg_emit_common_block_mdnode()
LL_MDRef lldbg_emit_common_block_mdnode (LL_DebugInfo * db, SPTR sptr)
Definition at line 4238 of file lldebug.cpp.
References add_debug_cmnblk_variables(), db(), ll_add_module_debug(), ll_get_module_debug(), LL_MDREF_IS_NULL, lldbg_create_common_block_mdnode(), lldbg_emit_module_mdnode(), new_debug_name(), NULL, scope, sptr, and SYMNAME.
Referenced by process_cmnblk_data(), and process_global_lifetime_debug().
lldbg_emit_compile_unit()
LL_MDRef lldbg_emit_compile_unit (LL_DebugInfo * db)
Create a metadata node for the current compile unit.
Parameters
db
This function is idempotent.
Definition at line 1843 of file lldebug.cpp.
References assert, FLG::cmdline, db(), DW_LANG_Fortran90, ERR_Fatal, flg, get_currentdir(), get_filename(), LL_MDREF_IS_NULL, lldbg_create_compile_unit_mdnode(), and FLG::opt.
Referenced by get_extra_info_for_sptr(), lldbg_emit_file(), lldbg_emit_local_variable(), lldbg_emit_module_mdnode(), lldbg_emit_outlined_subprogram(), lldbg_emit_ptr_param_variable(), and lldbg_emit_type().
lldbg_emit_empty_expression_mdnode()
LL_MDRef lldbg_emit_empty_expression_mdnode (LL_DebugInfo * db)
Definition at line 1564 of file lldebug.cpp.
References db(), LL_DIExpression, llmd_finish(), llmd_init(), and llmd_set_class().
Referenced by insert_llvm_dbg_declare(), insert_llvm_dbg_value(), lldbg_create_assumed_len_string_type_mdnode(), and lldbg_create_deferred_len_string_type_mdnode().
lldbg_emit_expression_mdnode()
LL_MDRef lldbg_emit_expression_mdnode (LL_DebugInfo * db, unsigned cnt, ...)
Definition at line 1579 of file lldebug.cpp.
References arg, cnt, db(), DEBUG_ASSERT, i, LL_DIExpression, llmd_add_i32(), llmd_finish(), llmd_init(), and llmd_set_class().
Referenced by cons_expression_metadata_operand(), emit_deref_expression_mdnode(), insert_llvm_dbg_declare(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_create_global_variable_mdnode(), lldbg_emit_type(), lldbg_get_bounds_for_assumed_rank_sdsc(), and lldbg_get_bounds_for_sdsc().
lldbg_emit_file()
static LL_MDRef lldbg_emit_file (LL_DebugInfo * db, int findex) static
Definition at line 1859 of file lldebug.cpp.
References db(), get_currentdir(), get_file_mdnode(), get_filedesc_mdnode(), get_filename(), ll_feature_debug_info_need_file_descriptions, ll_get_md_null, LL_MDREF_IS_NULL, lldbg_create_file_mdnode(), and lldbg_emit_compile_unit().
Referenced by lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_imported_entity(), lldbg_emit_global_variable(), lldbg_emit_local_variable(), lldbg_emit_module_mdnode(), lldbg_emit_outlined_subprogram(), lldbg_emit_param_variable(), lldbg_emit_ptr_param_variable(), lldbg_emit_subprogram(), and lldbg_emit_type().
lldbg_emit_global_variable()
void lldbg_emit_global_variable (LL_DebugInfo * db, SPTR sptr, ISZ_T off, int findex, LL_Value * value)
Definition at line 3578 of file lldebug.cpp.
References assert, cpu_llvm_module, db(), DECLLINEG, DIFLAG_ARTIFICIAL, dtype_array_check_set(), LL_MDNode::elem, ERR_Fatal, flags, ftn_array_need_debug_info(), FUNCLINEG, fwd, get_extra_info_for_sptr(), get_filedesc_mdnode(), hashmap_erase(), hashmap_lookup(), INT2HKEY, LL_Module::ir, is_procedure_ptr(), ll_add_global_debug(), ll_add_module_debug(), ll_feature_debug_info_need_file_descriptions, ll_feature_debug_info_ver90, ll_feature_from_global_to_md, ll_get_global_debug(), ll_get_md_null, LL_MDREF_IS_NULL, LL_MDREF_value, llassem_get_objtodbg_list(), lldbg_create_global_variable_mdnode(), lldbg_emit_file(), lldbg_emit_type(), llObjtodbgAddUnique(), llObjtodbgCreate(), new_debug_name(), NULL, off, pointer_scalar_need_debug_info(), sptr, SPTR_NULL, SYMNAME, val, and value().
Referenced by add_global_define(), addDebugForGlobalVar(), and lldbg_function_end().
lldbg_emit_imported_entity()
static void lldbg_emit_imported_entity (LL_DebugInfo * db, SPTR entity_sptr, SPTR func_sptr, IMPORT_TYPE entity_type, LL_MDRef elements) static
Definition at line 4172 of file lldebug.cpp.
References db(), hash_functions_strings, hashset_alloc(), hashset_insert(), hashset_lookup(), lldbg_create_imported_entity(), new_debug_name(), NULL, and SYMNAME.
Referenced by lldbg_emit_subprogram().
lldbg_emit_lexical_block()
static void lldbg_emit_lexical_block (LL_DebugInfo * db, int sptr, int lineno, int findex, bool targetNVVM) static
Definition at line 2100 of file lldebug.cpp.
References db(), BLKINFO::endline, ENDLINEG, i, lineno, lldbg_create_block_mdnode(), lldbg_create_location_mdnode(), BLKINFO::mdnode, NEEDB, NULL, sptr, startline, and BLKINFO::startline.
Referenced by lldbg_emit_lexical_blocks().
lldbg_emit_lexical_blocks()
static void lldbg_emit_lexical_blocks (LL_DebugInfo * db, int sptr, int findex, bool targetNVVM) static
Definition at line 2149 of file lldebug.cpp.
References db(), FUNCLINEG, idx, lineno, lldbg_emit_lexical_block(), NULL, sptr, and stb.
Referenced by lldbg_emit_subprogram().
lldbg_emit_line()
void lldbg_emit_line (LL_DebugInfo * db, int lineno)
Definition at line 2585 of file lldebug.cpp.
References assert, db(), ERR_Fatal, i, idx, j, lineno, ll_get_md_null, LL_MDREF_IS_NULL, lldbg_create_location_mdnode(), and startline.
Referenced by schedule().
lldbg_emit_local_variable()
LL_MDRef lldbg_emit_local_variable (LL_DebugInfo * db, SPTR sptr, int findex, int emit_dummy_as_local)
Definition at line 3827 of file lldebug.cpp.
References alignment(), assert, db(), DIFLAG_ARTIFICIAL, DT_CPTR, DTyInterface, DTySeqTyElement, DW_TAG_auto_variable, ERR_Fatal, flags, ftn_array_need_debug_info(), fwd, get_filedesc_mdnode(), get_lexical_block_info(), get_param_mdnode(), hashmap_erase(), hashmap_lookup(), INT2HKEY, is_procedure_ptr(), ll_feature_debug_info_need_file_descriptions, ll_feature_debug_info_ver90, ll_get_md_null, LL_MDREF_IS_NULL, lldbg_alloc(), lldbg_cancel_value_call(), lldbg_create_local_variable_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_emit_compile_unit(), lldbg_emit_file(), lldbg_emit_type(), BLKINFO::mdnode, NULL, offset, pointer_scalar_need_debug_info(), set_dilocalvariable_flags(), sptr, strlen(), SYMNAME, val, and ZSIZEOF.
Referenced by addDebugForLocalVar(), cleanup_bounds(), consLoadDebug(), lldbg_emit_type(), and process_params().
lldbg_emit_lv_list()
void lldbg_emit_lv_list (LL_DebugInfo * db)
Definition at line 3785 of file lldebug.cpp.
References assert, CANCEL_CALL_DBG_VALUE, db(), ERR_Fatal, i, ll_extend_md_node(), LL_MDREF_IS_NULL, and NULL.
Referenced by schedule().
lldbg_emit_modified_type()
static LL_MDRef lldbg_emit_modified_type (LL_DebugInfo * db, DTYPE dtype, SPTR sptr, int findex) static
Definition at line 2737 of file lldebug.cpp.
References db(), DT_CPTR, DTY, lldbg_emit_type(), and sptr.
Referenced by lldbg_emit_parameter_list().
lldbg_emit_module_mdnode()
LL_MDRef lldbg_emit_module_mdnode (LL_DebugInfo * db, int sptr)
Definition at line 2396 of file lldebug.cpp.
References db(), FUNCLINEG, ll_get_md_null, ll_get_module_debug(), LL_MDREF_IS_NULL, lldbg_create_module_mdnode(), lldbg_emit_compile_unit(), lldbg_emit_file(), sptr, and SYMNAME.
Referenced by lldbg_emit_common_block_mdnode(), lldbg_emit_subprogram(), and process_global_lifetime_debug().
lldbg_emit_outlined_parameter_list()
void lldbg_emit_outlined_parameter_list (LL_DebugInfo * db, int findex, DTYPE * param_dtypes, int num_args)
Definition at line 2707 of file lldebug.cpp.
References assert, db(), ERR_Fatal, i, ll_extend_md_node(), ll_feature_debug_info_pre34, ll_feature_debug_info_ver38, ll_get_md_null, lldbg_create_unspecified_parameters_mdnode(), lldbg_create_unspecified_type_mdnode(), lldbg_emit_type(), and SPTR_NULL.
lldbg_emit_outlined_subprogram()
void lldbg_emit_outlined_subprogram (LL_DebugInfo * db, int sptr, int findex, const char * func_name, int startlineno, bool targetNVVM)
Create a metadata node for the outlined subprogram sptr.
Parameters
db
sptr
findex
func_name
startlineno
Side-effect: store the metadata in the LL_DebugInfo struct.
A function pointer to the corresponding LLVM function must be set later by lldbg_set_func_ptr().
Definition at line 2325 of file lldebug.cpp.
References assert, db(), DTyReturnType, ERR_Fatal, flags, get_filedesc_mdnode(), lineno, ll_create_flexible_md_node(), ll_feature_debug_info_pre34, ll_feature_debug_info_ver38, ll_feature_has_diextensions, ll_get_md_null, lldbg_assign_lexical_blocks(), lldbg_create_location_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_emit_compile_unit(), lldbg_emit_file(), lldbg_emit_outlined_subroutine(), lldbg_limit_lexical_blocks(), lldbg_reserve_lexical_blocks(), NULL, PARAM_STACK_SIZE, set_disubprogram_flags(), set_disubprogram_spflags(), sptr, and BLKINFO::startline.
lldbg_emit_outlined_subroutine()
static LL_MDRef lldbg_emit_outlined_subroutine (LL_DebugInfo * db, int sptr, int ret_dtype, int findex, LL_MDRef file_mdnode) static
Definition at line 1989 of file lldebug.cpp.
References db(), gbl, ll_get_md_null, lldbg_create_outlined_parameters_node(), lldbg_create_subroutine_type_mdnode(), and RU_PROG.
Referenced by lldbg_emit_outlined_subprogram().
lldbg_emit_param_variable()
LL_MDRef lldbg_emit_param_variable (LL_DebugInfo * db, SPTR sptr, int findex, int parnum, bool unnamed)
Definition at line 3948 of file lldebug.cpp.
References assert, db(), DW_TAG_arg_variable, ERR_Fatal, flags, get_filedesc_mdnode(), get_parnum(), ll_feature_debug_info_need_file_descriptions, ll_feature_debug_info_ver90, ll_get_md_null, LL_MDREF_IS_NULL, lldbg_alloc(), lldbg_create_local_variable_mdnode(), lldbg_emit_file(), lldbg_emit_type(), lldbg_register_param_mdnode(), NULL, set_dilocalvariable_flags(), sptr, strlen(), and SYMNAME.
Referenced by formalsAddDebug(), and lldbg_create_assumed_len_string_type_mdnode().
lldbg_emit_parameter_list()
static LL_MDRef lldbg_emit_parameter_list (LL_DebugInfo * db, DTYPE dtype, DTYPE ret_dtype, SPTR sptr, int findex) static
Definition at line 1900 of file lldebug.cpp.
References assert, CUDA_DEVICE, CUDAG, db(), DT_ISBASIC, DTY, DTySeqTyElement, ERR_Fatal, GetParamSptr, i, ll_feature_debug_info_pre34, ll_get_md_null, lldbg_create_unspecified_parameters_mdnode(), lldbg_create_unspecified_type_mdnode(), lldbg_emit_modified_type(), lldbg_emit_type(), llmd_add_md(), llmd_finish(), llmd_init(), sptr, and SPTR_NULL.
Referenced by lldbg_emit_subroutine_type(), and lldbg_emit_type().
lldbg_emit_ptr_param_variable()
LL_MDRef lldbg_emit_ptr_param_variable (LL_DebugInfo * db, SPTR sptr, int findex, int parnum)
Definition at line 4016 of file lldebug.cpp.
References alignment(), assert, db(), DT_CPTR, DW_TAG_arg_variable, ERR_Fatal, flags, get_filedesc_mdnode(), ISZ_T, ll_feature_debug_info_need_file_descriptions, ll_get_md_null, lldbg_alloc(), lldbg_create_local_variable_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_emit_compile_unit(), lldbg_emit_file(), lldbg_emit_type(), lldbg_register_param_mdnode(), offset, set_dilocalvariable_flags(), sptr, strlen(), SYMNAME, sz, and ZSIZEOF.
lldbg_emit_subprogram()
void lldbg_emit_subprogram (LL_DebugInfo * db, SPTR sptr, DTYPE ret_dtype, int findex, bool targetNVVM)
Create a metadata node for the current subprogram.
Parameters
db
sptr
ret_dtype
findex
Side-effect: stores the metadata node in the LL_DebugInfo struct.
A function pointer to the corresponding LLVM function must be set later by lldbg_set_func_ptr().
Definition at line 2412 of file lldebug.cpp.
References assert, db(), import_entity::entity, import_entity::entity_type, ERR_Fatal, flags, flg, FUNCLINEG, gbl, get_extra_info_for_sptr(), get_filedesc_mdnode(), hash_functions_direct, hashmap_alloc(), hashmap_lookup(), hashmap_replace(), INT2HKEY, lineno, ll_create_flexible_md_node(), ll_extend_md_node(), ll_feature_create_dimodule, ll_feature_debug_info_need_file_descriptions, ll_feature_debug_info_pre34, ll_feature_has_diextensions, ll_get_md_null, lldbg_create_imported_entity(), lldbg_create_location_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_emit_file(), lldbg_emit_imported_entity(), lldbg_emit_lexical_blocks(), lldbg_emit_module_mdnode(), lldbg_emit_subroutine_type(), import_entity::next, NULL, FLG::opt, PARAM_STACK_SIZE, scope, set_disubprogram_flags(), set_disubprogram_spflags(), and sptr.
Referenced by schedule().
lldbg_emit_subroutine_type()
static INLINE LL_MDRef lldbg_emit_subroutine_type (LL_DebugInfo * db, SPTR sptr, DTYPE ret_dtype, int findex, LL_MDRef file_mdnode) static
Definition at line 1974 of file lldebug.cpp.
References db(), gbl, ll_get_md_null, lldbg_create_subroutine_type_mdnode(), lldbg_emit_parameter_list(), RU_PROG, and sptr.
Referenced by lldbg_emit_subprogram().
lldbg_emit_type()
static LL_MDRef lldbg_emit_type (LL_DebugInfo * db, DTYPE dtype, SPTR sptr, int findex, bool is_reference, bool skip_first_dim, bool skipDataDependentTypes, SPTR data_sptr = SPTR_NULL) static
Definition at line 3054 of file lldebug.cpp.
References AD_DPTR, AD_LWBD, AD_NUMDIM, AD_UPBD, ad_val_of(), add(), alignment(), assert, count, cpu_llvm_module, LL_Type_::data_type, db(), deref, DIFLAG_ARTIFICIAL, DT_CPTR, DT_ISBASIC, DT_LOG, DTY, DTyAlgTyMember, DTyAlgTyTag, DTyInterface, dtype_array_check_set(), DTyReturnType, DTySeqTyElement, DTyVecLength, DW_TAG_arg_variable, DW_TAG_auto_variable, dwarf_encoding(), ERR_Fatal, FLANG_FALLTHROUGH, ftn_array_need_debug_info(), get_filedesc_mdnode(), get_lexical_block_info(), get_parnum(), i, init_subrange_bound(), init_subrange_bound_pre11(), insert_llvm_dbg_declare(), insert_llvm_dbg_value(), LL_Module::ir, is_assumed_char(), is_deferred_char(), is_procedure_ptr(), ISZ_T, lb, ld, ll_create_flexible_md_node(), LL_DW_OP_and, LL_DW_OP_constu, LL_DW_OP_deref, LL_DW_OP_int, LL_DW_OP_plus_uconst, LL_DW_OP_push_object_address, LL_DWARF_Version_5, ll_feature_debug_info_need_file_descriptions, ll_feature_debug_info_pre34, ll_feature_debug_info_ver11, ll_feature_debug_info_ver90, ll_feature_from_global_to_md, ll_feature_has_diextensions, ll_get_md_i64(), ll_get_md_null, LL_MDREF_IS_NULL, LL_PTR, lldbg_create_aggregate_members_type(), lldbg_create_array_type_mdnode(), lldbg_create_assumed_len_string_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_ftn_array_type_mdnode(), lldbg_create_ftn_subrange_mdnode(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_create_generic_subrange_mdnode(), lldbg_create_local_variable_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_create_string_type_mdnode(), lldbg_create_structure_type_mdnode(), lldbg_create_subrange_mdnode(), lldbg_create_subrange_mdnode_pre11(), lldbg_create_subrange_via_sdsc(), lldbg_create_subroutine_type_mdnode(), lldbg_create_union_type_mdnode(), lldbg_create_vector_type_mdnode(), lldbg_emit_compile_unit(), lldbg_emit_expression_mdnode(), lldbg_emit_file(), lldbg_emit_local_variable(), lldbg_emit_parameter_list(), lldbg_emit_type(), lldbg_encode_expression_arg(), lldbg_get_bounds_for_assumed_rank_sdsc(), lldbg_get_bounds_for_sdsc(), lldbg_register_param_mdnode(), llmd_add_md(), llmd_finish(), llmd_init(), LLTYPE, M, make_lltype_from_sptr(), make_operand(), BLKINFO::mdnode, NOSYM, NULL, offset, OPF_NONE, OT_MDNODE, rank, set_dilocalvariable_flags(), sptr, SPTR_NULL, st, stb, LL_Type_::sub_types, SYMNAME, sz, TY_CHAR, STB::tynames, ub, zero, zsize_of(), and ZSIZEOF.
Referenced by lldbg_create_aggregate_members_type(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_emit_global_variable(), lldbg_emit_local_variable(), lldbg_emit_modified_type(), lldbg_emit_outlined_parameter_list(), lldbg_emit_param_variable(), lldbg_emit_parameter_list(), lldbg_emit_ptr_param_variable(), and lldbg_emit_type().
lldbg_encode_expression_arg()
int lldbg_encode_expression_arg (LL_DW_OP_t op, int value)
Encode an argument to lldbg_emit_expression_mdnode()
Definition at line 1572 of file lldebug.cpp.
References DEBUG_ASSERT, LL_DW_OP_int, ll_dw_op_ok(), and value().
Referenced by cons_expression_metadata_operand(), emit_deref_expression_mdnode(), insert_llvm_dbg_declare(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_create_global_variable_mdnode(), lldbg_emit_type(), lldbg_get_bounds_for_assumed_rank_sdsc(), and lldbg_get_bounds_for_sdsc().
lldbg_free()
void lldbg_free (LL_DebugInfo * db)
Definition at line 1746 of file lldebug.cpp.
References db(), FREE, lldbg_free_import_entity_list(), sptr_to_mdnode_map::next, and NULL.
Referenced by ll_destroy_module().
lldbg_free_import_entity_list()
void lldbg_free_import_entity_list (import_entity * import_entity_list)
Definition at line 1734 of file lldebug.cpp.
References import_entity::child, lldbg_free_import_entity_list(), import_entity::next, and NULL.
Referenced by lldbg_free(), and lldbg_free_import_entity_list().
lldbg_function_end()
void lldbg_function_end (LL_DebugInfo * db, int func)
Definition at line 4061 of file lldebug.cpp.
References buff, db(), FLG::debug, STB::firstusym, flg, get_llvm_name(), getitem(), i, ll_create_value_from_type(), ll_get_pointer_type(), lldbg_emit_global_variable(), LLTYPE, LLVM_LONGTERM_AREA, make_lltype_from_dtype(), name, process_dtype_struct(), SNAME, st, stb, strlen(), type, and value().
lldbg_fwd_local_variable()
static LL_MDRef lldbg_fwd_local_variable (LL_DebugInfo * db, int sptr, int findex, int emit_dummy_as_local) static
Definition at line 2981 of file lldebug.cpp.
References db(), hashmap_insert(), hashmap_lookup(), INT2HKEY, LL_MDREF_INITIALIZER, ll_reserve_md_node(), sptr_to_mdnode_map::mdnode, MDRef_Node, and sptr.
Referenced by init_subrange_bound(), init_subrange_bound_pre11(), and lldbg_create_ftn_subrange_via_sdsc().
lldbg_get_bounds_for_assumed_rank_sdsc()
static void lldbg_get_bounds_for_assumed_rank_sdsc (LL_DebugInfo * db, SPTR sptr, LL_MDRef * lbnd_expr_mdnode, LL_MDRef * ubnd_expr_mdnode, LL_MDRef * stride_expr_mdnode) static
Definition at line 1413 of file lldebug.cpp.
References add(), db(), deref, LL_DW_OP_constu, LL_DW_OP_deref, LL_DW_OP_int, LL_DW_OP_mul, LL_DW_OP_over, LL_DW_OP_plus, LL_DW_OP_plus_uconst, LL_DW_OP_push_object_address, ll_get_md_null, lldbg_emit_expression_mdnode(), lldbg_encode_expression_arg(), sptr, and zsize_of().
Referenced by lldbg_emit_type().
lldbg_get_bounds_for_sdsc()
static void lldbg_get_bounds_for_sdsc (LL_DebugInfo * db, int findex, SPTR sptr, int rank, LL_MDRef * count_expr_mdnode, LL_MDRef * lbnd_expr_mdnode, LL_MDRef * ubnd_expr_mdnode, LL_MDRef * stride_expr_mdnode) static
Definition at line 1323 of file lldebug.cpp.
References add(), db(), deref, LL_DW_OP_deref, LL_DW_OP_int, LL_DW_OP_mul, LL_DW_OP_plus_uconst, LL_DW_OP_push_object_address, ll_get_md_null, lldbg_emit_expression_mdnode(), lldbg_encode_expression_arg(), rank, sptr, and zsize_of().
Referenced by lldbg_create_subrange_via_sdsc(), and lldbg_emit_type().
lldbg_get_di_routine_idx()
int lldbg_get_di_routine_idx (const LL_DebugInfo * db)
Return debuginfo routine index.
Definition at line 245 of file lldebug.cpp.
References db().
Referenced by schedule().
lldbg_get_line()
LL_MDRef lldbg_get_line (LL_DebugInfo * db)
Definition at line 2652 of file lldebug.cpp.
References assert, db(), and ERR_Fatal.
Referenced by lldbg_cons_line(), make_instr(), and schedule().
lldbg_get_sizeof()
static ISZ_T lldbg_get_sizeof (int element) static
Definition at line 251 of file lldebug.cpp.
References ISZ_T, sz, and zsize_of().
Referenced by lldbg_create_aggregate_members_type().
lldbg_get_subprogram_line()
LL_MDRef lldbg_get_subprogram_line (LL_DebugInfo * db)
Definition at line 4328 of file lldebug.cpp.
References db().
Referenced by write_instructions().
lldbg_get_var_line()
LL_MDRef lldbg_get_var_line (LL_DebugInfo * db, int sptr)
Definition at line 2514 of file lldebug.cpp.
References assert, db(), ERR_Fatal, flg, fn, getLexBlock_notCurrentFunc(), idx, ll_get_md_null, FLG::smp, and sptr.
Referenced by insert_llvm_dbg_declare(), and insert_llvm_dbg_value().
lldbg_init()
void lldbg_init (LL_Module * module)
Definition at line 1676 of file lldebug.cpp.
References BZERO, db(), LL_Module::debug_info, LL_IRFeatures_::debug_info_version, STB::dt, fihb, gbl, LL_Module::ir, ll_extend_named_md_node(), ll_feature_debug_info_pre34, ll_feature_dwarf_version(), ll_feature_versioned_dw_tag, ll_get_md_null, lldbg_create_module_flag_mdnode(), MD_llvm_module_flags, LL_Module::named_mdnodes, NEEDB, NEW, NOSYM, NULL, sptr, SPTR_NULL, stb, FIHB::stg_avail, and version.
Referenced by cg_llvm_init().
lldbg_init_arrays()
void lldbg_init_arrays (LL_DebugInfo * db)
Definition at line 1665 of file lldebug.cpp.
References assert, BZERO, db(), STB::dt, ERR_Fatal, NEED, and stb.
lldbg_limit_lexical_blocks()
static BLKINFO * lldbg_limit_lexical_blocks (LL_DebugInfo * db, int startline) static
Definition at line 2021 of file lldebug.cpp.
References db(), BLKINFO::endline, for(), i, BLKINFO::keep, NULL, startline, and BLKINFO::startline.
Referenced by lldbg_emit_outlined_subprogram().
lldbg_register_param_mdnode()
static void lldbg_register_param_mdnode (LL_DebugInfo * db, LL_MDRef mdnode, int sptr) static
Definition at line 3765 of file lldebug.cpp.
References assert, db(), ERR_Fatal, i, sptr_to_mdnode_map::mdnode, NULL, PARAM_STACK_SIZE, and sptr.
Referenced by lldbg_emit_param_variable(), lldbg_emit_ptr_param_variable(), and lldbg_emit_type().
lldbg_register_value_call()
void lldbg_register_value_call (LL_DebugInfo * db, INSTR_LIST * instr, int sptr)
Definition at line 3734 of file lldebug.cpp.
References assert, db(), ERR_Fatal, i, ll_get_md_null, PARAM_STACK_SIZE, and sptr.
lldbg_reserve_lexical_block()
static void lldbg_reserve_lexical_block (LL_DebugInfo * db, int sptr, int lineno, int findex) static
Definition at line 2002 of file lldebug.cpp.
References db(), ENDLINEG, lineno, ll_get_md_null, NEEDB, NULL, sptr, and startline.
Referenced by lldbg_reserve_lexical_blocks().
lldbg_reserve_lexical_blocks()
static void lldbg_reserve_lexical_blocks (LL_DebugInfo * db, int sptr, int findex) static
Definition at line 2215 of file lldebug.cpp.
References db(), FUNCLINEG, idx, lldbg_reserve_lexical_block(), NULL, sptr, and stb.
Referenced by lldbg_emit_outlined_subprogram().
lldbg_reset_dtype_array()
void lldbg_reset_dtype_array (LL_DebugInfo * db, const int off)
Definition at line 1648 of file lldebug.cpp.
References BZERO, db(), and off.
Referenced by schedule().
lldbg_reset_module()
void lldbg_reset_module (LL_DebugInfo * db)
Definition at line 559 of file lldebug.cpp.
References db(), ll_get_md_null, and NULL.
Referenced by process_global_lifetime_debug().
lldbg_set_func_ptr()
void lldbg_set_func_ptr (LL_DebugInfo * db, LL_Value * func_ptr)
Definition at line 543 of file lldebug.cpp.
References db(), ll_get_md_value(), and ll_update_md_node().
Referenced by schedule().
lldbg_subprogram()
LL_MDRef lldbg_subprogram (LL_DebugInfo * db)
Definition at line 551 of file lldebug.cpp.
References db().
Referenced by build_routine_and_parameter_entries().
lldbg_update_arrays()
void lldbg_update_arrays (LL_DebugInfo * db, int lastDType, int newSz)
Definition at line 1654 of file lldebug.cpp.
References assert, BZERO, db(), ERR_Fatal, and NEED.
Referenced by update_llvm_sym_arrays().
llObjtodbgAddUnique()
static void llObjtodbgAddUnique (LL_ObjToDbgList * odl, LL_MDRef mdadd) static
Definition at line 3566 of file lldebug.cpp.
References i, llObjtodbgAtEnd(), llObjtodbgFirst(), llObjtodbgGet(), llObjtodbgNext(), and llObjtodbgPush().
Referenced by lldbg_create_cmblk_mem_mdnode_list(), and lldbg_emit_global_variable().
make_dwtag()
static int make_dwtag (LL_DebugInfo * db, int tag) static
Make an i32 operand with a DWARF tag and possibly a version number.
LLVM 3.6 onwards do not encode the debug info version in the tag field.
Definition at line 272 of file lldebug.cpp.
References db(), and ll_feature_versioned_dw_tag.
Referenced by lldbg_create_aggregate_type_mdnode(), lldbg_create_array_type_mdnode(), lldbg_create_assumed_len_string_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_block_mdnode(), lldbg_create_compile_unit_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_file_mdnode(), lldbg_create_ftn_array_type_mdnode(), lldbg_create_ftn_subrange_mdnode(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_create_generic_subrange_mdnode(), lldbg_create_global_variable_mdnode(), lldbg_create_imported_entity(), lldbg_create_local_variable_mdnode(), lldbg_create_member_mdnode(), lldbg_create_module_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_create_string_type_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_create_subrange_mdnode(), lldbg_create_subrange_mdnode_pre11(), lldbg_create_subroutine_type_mdnode(), lldbg_create_unspecified_mdnode(), and lldbg_create_vector_type_mdnode().
new_debug_name()
const char * new_debug_name (const char * str1, const char * str2, const char * str3)
Definition at line 4303 of file lldebug.cpp.
References lldbg_alloc(), NULL, size, and strlen().
Referenced by add_debug_cmnblk_variables(), lldbg_create_imported_entity(), lldbg_emit_common_block_mdnode(), lldbg_emit_global_variable(), lldbg_emit_imported_entity(), and process_cmnblk_data().
next_assumed_len_character_name()
static INLINE char * next_assumed_len_character_name (void) static
Definition at line 2816 of file lldebug.cpp.
References name.
Referenced by lldbg_create_assumed_len_string_type_mdnode().
set_dilocalvariable_flags()
static INLINE int set_dilocalvariable_flags (int sptr) static
Construct the flag set that corresponds with LLVM metadata.
Definition at line 3806 of file lldebug.cpp.
References DIFLAG_ARTIFICIAL, GBL_CURRFUNC, and sptr.
Referenced by lldbg_emit_local_variable(), lldbg_emit_param_variable(), lldbg_emit_ptr_param_variable(), and lldbg_emit_type().
set_disubprogram_flags()
static INLINE int set_disubprogram_flags (LL_DebugInfo * db, int sptr) static
Construct the flag set that corresponds with LLVM metadata.
Definition at line 2287 of file lldebug.cpp.
References db(), DIFLAG_ARTIFICIAL, DIFLAG_ISMAINPGM, DIFLAG_PURE, flags, gbl, ll_feature_debug_info_ver80, ll_feature_debug_info_ver90, RU_PROG, and sptr.
Referenced by lldbg_emit_outlined_subprogram(), and lldbg_emit_subprogram().
set_disubprogram_spflags()
static INLINE int set_disubprogram_spflags (LL_DebugInfo * db, int sptr, bool is_def, bool is_local, bool is_optimized) static
Definition at line 2302 of file lldebug.cpp.
References db(), DISPFLAG_DEFINITION, DISPFLAG_ELEMENTAL, DISPFLAG_LOCALTOUNIT, DISPFLAG_MAINSUBPROGRAM, DISPFLAG_OPTIMIZED, DISPFLAG_PURE, DISPFLAG_RECURSIVE, gbl, ll_feature_debug_info_ver90, RU_PROG, and sptr.
Referenced by lldbg_emit_outlined_subprogram(), and lldbg_emit_subprogram().
Variable Documentation
DIFLAG_ARTIFICIAL
const int DIFLAG_ARTIFICIAL = 1 << 6
Definition at line 77 of file lldebug.cpp.
Referenced by lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_global_variable_mdnode(), lldbg_create_local_variable_mdnode(), lldbg_emit_global_variable(), lldbg_emit_local_variable(), lldbg_emit_type(), set_dilocalvariable_flags(), and set_disubprogram_flags().
DIFLAG_ELEMENTAL
int DIFLAG_ELEMENTAL static
Definition at line 80 of file lldebug.cpp.
Referenced by InitializeDIFlags().
DIFLAG_ISMAINPGM
const int DIFLAG_ISMAINPGM = 1 << 21
Definition at line 78 of file lldebug.cpp.
Referenced by set_disubprogram_flags().
DIFLAG_PURE
int DIFLAG_PURE static
Definition at line 79 of file lldebug.cpp.
Referenced by InitializeDIFlags(), and set_disubprogram_flags().
DIFLAG_RECURSIVE
int DIFLAG_RECURSIVE static
Definition at line 81 of file lldebug.cpp.
Referenced by InitializeDIFlags().
DISPFLAG_DEFINITION
const int DISPFLAG_DEFINITION = 1 << 3
Definition at line 84 of file lldebug.cpp.
Referenced by set_disubprogram_spflags().
DISPFLAG_ELEMENTAL
const int DISPFLAG_ELEMENTAL = 1 << 6
Definition at line 87 of file lldebug.cpp.
Referenced by set_disubprogram_spflags().
DISPFLAG_LOCALTOUNIT
const int DISPFLAG_LOCALTOUNIT = 1 << 2
Definition at line 83 of file lldebug.cpp.
Referenced by set_disubprogram_spflags().
DISPFLAG_MAINSUBPROGRAM
const int DISPFLAG_MAINSUBPROGRAM = 1 << 8
Definition at line 89 of file lldebug.cpp.
Referenced by set_disubprogram_spflags().
DISPFLAG_OPTIMIZED
const int DISPFLAG_OPTIMIZED = 1 << 4
Definition at line 85 of file lldebug.cpp.
Referenced by set_disubprogram_spflags().
DISPFLAG_PURE
const int DISPFLAG_PURE = 1 << 5
Definition at line 86 of file lldebug.cpp.
Referenced by set_disubprogram_spflags().
DISPFLAG_RECURSIVE
const int DISPFLAG_RECURSIVE = 1 << 7
Definition at line 88 of file lldebug.cpp.
Referenced by set_disubprogram_spflags().