flang: lldebug.h File Reference
lldebug.h File Reference
Debug info generation for LLVM IR.
#include "gbldefs.h"
#include "ll_structure.h"
#include "llutil.h"
Functions
void lldbg_emit_subprogram (LL_DebugInfo *db, SPTR sptr, DTYPE ret_dtype, int findex, bool targetNVVM)
Create a metadata node for the current subprogram.
void lldbg_emit_outlined_subprogram (LL_DebugInfo *db, int sptr, int findex, const char *func_name, int startlineno, bool targetNVVM)
Create a metadata node for the outlined subprogram sptr.
void lldbg_emit_cmblk_variables (LL_DebugInfo *, int, int, char *, int)
void write_metadata_defs (LL_DebugInfo *db)
Write out metadata definitions to the current LLVM file.
char * lldbg_alloc (INT size)
...
int lldbg_get_di_routine_idx (const LL_DebugInfo *db)
Return debuginfo routine index.
int lldbg_encode_expression_arg (LL_DW_OP_t op, int value)
Encode an argument to lldbg_emit_expression_mdnode()
LL_MDRef lldbg_cons_line (LL_DebugInfo *db)
Always produce !dbg metadata for current location.
LL_MDRef lldbg_emit_compile_unit (LL_DebugInfo *db)
Create a metadata node for the current compile unit.
Detailed Description
Debug info generation for LLVM IR.
Definition in file lldebug.h.
Function Documentation
lldbg_alloc()
char * lldbg_alloc (INT size)
...
Definition at line 236 of file lldebug.cpp.
References assert, ERR_Fatal, getitem(), LLVM_LONGTERM_AREA, p, and size.
Referenced by lldbg_add_pending_import_entity(), lldbg_add_pending_import_entity_to_child(), lldbg_create_common_block_mdnode(), lldbg_create_module_mdnode(), lldbg_emit_local_variable(), lldbg_emit_param_variable(), lldbg_emit_ptr_param_variable(), and new_debug_name().
lldbg_cons_line()
LL_MDRef lldbg_cons_line (LL_DebugInfo * db)
Always produce !dbg metadata for current location.
This produces location info even when none exists.
Definition at line 2659 of file lldebug.cpp.
References db(), LL_MDREF_IS_NULL, and lldbg_get_line().
Referenced by emit_dbg_from_module().
lldbg_emit_cmblk_variables()
void lldbg_emit_cmblk_variables (LL_DebugInfo * , int , int , char * , int)
lldbg_emit_compile_unit()
LL_MDRef lldbg_emit_compile_unit (LL_DebugInfo * db)
Create a metadata node for the current compile unit.
Parameters
db
This function is idempotent.
Definition at line 1843 of file lldebug.cpp.
References assert, FLG::cmdline, db(), DW_LANG_Fortran90, ERR_Fatal, flg, get_currentdir(), get_filename(), LL_MDREF_IS_NULL, lldbg_create_compile_unit_mdnode(), and FLG::opt.
Referenced by get_extra_info_for_sptr(), lldbg_emit_file(), lldbg_emit_local_variable(), lldbg_emit_module_mdnode(), lldbg_emit_outlined_subprogram(), lldbg_emit_ptr_param_variable(), and lldbg_emit_type().
lldbg_emit_outlined_subprogram()
void lldbg_emit_outlined_subprogram (LL_DebugInfo * db, int sptr, int findex, const char * func_name, int startlineno, bool targetNVVM)
Create a metadata node for the outlined subprogram sptr.
Parameters
db
sptr
findex
func_name
startlineno
Side-effect: store the metadata in the LL_DebugInfo struct.
A function pointer to the corresponding LLVM function must be set later by lldbg_set_func_ptr().
Definition at line 2325 of file lldebug.cpp.
References assert, db(), DTyReturnType, ERR_Fatal, flags, get_filedesc_mdnode(), lineno, ll_create_flexible_md_node(), ll_feature_debug_info_pre34, ll_feature_debug_info_ver38, ll_feature_has_diextensions, ll_get_md_null, lldbg_assign_lexical_blocks(), lldbg_create_location_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_emit_compile_unit(), lldbg_emit_file(), lldbg_emit_outlined_subroutine(), lldbg_limit_lexical_blocks(), lldbg_reserve_lexical_blocks(), NULL, PARAM_STACK_SIZE, set_disubprogram_flags(), set_disubprogram_spflags(), sptr, and BLKINFO::startline.
lldbg_emit_subprogram()
void lldbg_emit_subprogram (LL_DebugInfo * db, SPTR sptr, DTYPE ret_dtype, int findex, bool targetNVVM)
Create a metadata node for the current subprogram.
Parameters
db
sptr
ret_dtype
findex
Side-effect: stores the metadata node in the LL_DebugInfo struct.
A function pointer to the corresponding LLVM function must be set later by lldbg_set_func_ptr().
Definition at line 2412 of file lldebug.cpp.
References assert, db(), import_entity::entity, import_entity::entity_type, ERR_Fatal, flags, flg, FUNCLINEG, gbl, get_extra_info_for_sptr(), get_filedesc_mdnode(), hash_functions_direct, hashmap_alloc(), hashmap_lookup(), hashmap_replace(), INT2HKEY, lineno, ll_create_flexible_md_node(), ll_extend_md_node(), ll_feature_create_dimodule, ll_feature_debug_info_need_file_descriptions, ll_feature_debug_info_pre34, ll_feature_has_diextensions, ll_get_md_null, lldbg_create_imported_entity(), lldbg_create_location_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_emit_file(), lldbg_emit_imported_entity(), lldbg_emit_lexical_blocks(), lldbg_emit_module_mdnode(), lldbg_emit_subroutine_type(), import_entity::next, NULL, FLG::opt, PARAM_STACK_SIZE, scope, set_disubprogram_flags(), set_disubprogram_spflags(), and sptr.
Referenced by schedule().
lldbg_encode_expression_arg()
int lldbg_encode_expression_arg (LL_DW_OP_t op, int value)
Encode an argument to lldbg_emit_expression_mdnode()
Definition at line 1572 of file lldebug.cpp.
References DEBUG_ASSERT, LL_DW_OP_int, ll_dw_op_ok(), and value().
Referenced by cons_expression_metadata_operand(), emit_deref_expression_mdnode(), insert_llvm_dbg_declare(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_create_global_variable_mdnode(), lldbg_emit_type(), lldbg_get_bounds_for_assumed_rank_sdsc(), and lldbg_get_bounds_for_sdsc().
lldbg_get_di_routine_idx()
int lldbg_get_di_routine_idx (const LL_DebugInfo * db)
Return debuginfo routine index.
Definition at line 245 of file lldebug.cpp.
References db().
Referenced by schedule().
write_metadata_defs()
void write_metadata_defs (LL_DebugInfo * db)
Write out metadata definitions to the current LLVM file.