flang: llmputil.h File Reference
llmputil.h File Reference
OpenMP utility routines for LLVM compilers.
#include "gbldefs.h"
#include "global.h"
#include "symtab.h"
Classes
struct LLUplevel
struct _llprivate_t
struct LLTask
Task data structure containing a list of private variables for the task.
Typedefs
typedef struct _llprivate_t LLFirstPrivate
Enumerations
enum tgt_map_type {
OMP_TGT_MAPTYPE_NONE = 0x000 , OMP_TGT_MAPTYPE_TO = 0x001 , OMP_TGT_MAPTYPE_FROM = 0x002 , OMP_TGT_MAPTYPE_ALWAYS = 0x004 ,
OMP_TGT_MAPTYPE_DELETE = 0x008 , OMP_TGT_MAPTYPE_PTR_AND_OBJ = 0x010 , OMP_TGT_MAPTYPE_TARGET_PARAM = 0x020 , OMP_TGT_MAPTYPE_RETURN_PARAM = 0x040 ,
OMP_TGT_MAPTYPE_PRIVATE = 0x080 , OMP_TGT_MAPTYPE_LITERAL = 0x100 , OMP_TGT_MAPTYPE_IMPLICIT = 0x200 , OMP_TGT_MAPTYPE_MEMBER_OF = 0xffff000000000000
}
Data attributes for each data reference used in an OpenMP target region.
enum OMP_TARGET_MODE {
mode_none_target , mode_target , mode_target_teams , mode_target_teams_distribute ,
mode_target_teams_distribute_simd , mode_target_teams_distribute_parallel_for , mode_target_teams_distribute_parallel_for_simd , mode_target_parallel ,
mode_target_parallel_for , mode_target_parallel_for_simd , mode_target_simd , mode_target_data_enter_region ,
mode_target_data_exit_region , mode_target_data_region , mode_outlinedfunc_teams , mode_outlinedfunc_parallel ,
mode_targetupdate_begin , mode_targetupdate_end
}
Functions
bool is_omp_mode_target (OMP_TARGET_MODE mode)
LLTask * llmp_get_task (int scope_sptr)
...
int llmp_task_get_base_task_size (void)
...
int llmp_task_get_size (LLTask *task)
...
void llmp_task_set_fnsptr (LLTask *task, int task_sptr)
...
LLTask * llmp_task_get_by_fnsptr (int task_sptr)
...
int llmp_task_get_private (const LLTask *task, int sptr, int encl)
...
int llmp_add_shared_var (LLUplevel *up, int shared_sptr)
Uniquely add a shared variable.
int llmp_get_next_key (void)
Return a new key (index) into our table of all uplevels.
int llmp_task_add_loopvar (LLTask *task, int num, DTYPE dtype)
...
int llmp_task_add_private (LLTask *task, int shared_sptr, SPTR private_sptr)
Add a private sptr to the task object. priv: sptr to the private copy of the private variable. ADDRESSP is called to set the offset to the kmpc task object where this private data will live during program execution. /.
INT llmp_task_get_privoff (int sptr, const LLTask *task)
...
int llmp_uplevel_has_parent (int uplevel)
...
LLTask * llmp_create_task (int scope_sptr)
Create task object that can be searched for later using scope_sptr.
LLUplevel * llmp_create_uplevel_bykey (int key)
Retrieve an LLUplevel instance by key.
LLUplevel * llmp_create_uplevel (int uplevel_sptr)
Create an LLUplevel instance.
LLUplevel * llmp_get_uplevel (int uplevel_sptr)
Obtain a previously created uplevel.
LLUplevel * llmp_has_uplevel (int uplevel_sptr)
void dump_all_uplevel (void)
...
void dump_uplevel (LLUplevel *up)
...
void llmp_add_shared_var_charlen (LLUplevel *up, int shared_sptr)
...
void llmp_append_uplevel (int from_sptr, int to_sptr)
...
void llmp_concur_add_shared_var (int uplevel_sptr, int shared_sptr)
...
void llmp_reset_uplevel (void)
...
SPTR llmp_get_parent_sptr (SPTR)
Return symbol pointer of its parent.
void llmp_task_add (int scope_sptr, int shared_sptr, SPTR private_sptr)
Create a task object if it does not already exist for scope_sptr Add a private sptr to the task object. shared, priv: See llmp_task_add_private.
void llmp_uplevel_set_dtype (LLUplevel *up, DTYPE dtype)
Set the dtype (actual struct of member pointers)
void llmp_uplevel_set_parent (SPTR uplevel_sptr, SPTR parent_sptr)
Set uplevel parent field.
LLUplevel * llmp_outermost_uplevel (SPTR child)
Return outermost uplevel of current region.
LLUplevel * llmp_parent_uplevel (SPTR child)
Return uplevel pointer of current uplevel's parent.
Variables
static const char * omp_target_mode_names []
Detailed Description
OpenMP utility routines for LLVM compilers.
Definition in file llmputil.h.
Typedef Documentation
LLFirstPrivate
typedef struct _llprivate_t LLFirstPrivate
First private variable: This information is necessary to generate code that allows a particular task to know which variables are stored in its allocated memory (task memory). First privates for the task have to be stored in that memory.
Enumeration Type Documentation
OMP_TARGET_MODE
enum OMP_TARGET_MODE
Enumerator
mode_none_target
mode_target
mode_target_teams
mode_target_teams_distribute
mode_target_teams_distribute_simd
mode_target_teams_distribute_parallel_for
mode_target_teams_distribute_parallel_for_simd
mode_target_parallel
mode_target_parallel_for
mode_target_parallel_for_simd
mode_target_simd
mode_target_data_enter_region
mode_target_data_exit_region
mode_target_data_region
mode_outlinedfunc_teams
mode_outlinedfunc_parallel
mode_targetupdate_begin
mode_targetupdate_end
Definition at line 82 of file llmputil.h.
tgt_map_type
enum tgt_map_type
Data attributes for each data reference used in an OpenMP target region.
Enumerator
OMP_TGT_MAPTYPE_NONE
OMP_TGT_MAPTYPE_TO
OMP_TGT_MAPTYPE_FROM
OMP_TGT_MAPTYPE_ALWAYS
OMP_TGT_MAPTYPE_DELETE
OMP_TGT_MAPTYPE_PTR_AND_OBJ
OMP_TGT_MAPTYPE_TARGET_PARAM
OMP_TGT_MAPTYPE_RETURN_PARAM
OMP_TGT_MAPTYPE_PRIVATE
OMP_TGT_MAPTYPE_LITERAL
OMP_TGT_MAPTYPE_IMPLICIT
OMP_TGT_MAPTYPE_MEMBER_OF
Definition at line 53 of file llmputil.h.
Function Documentation
dump_all_uplevel()
void dump_all_uplevel (void)
...
dump_uplevel()
void dump_uplevel (LLUplevel * up)
...
is_omp_mode_target()
bool is_omp_mode_target (OMP_TARGET_MODE mode)
Definition at line 432 of file llmputil.c.
References mode, mode_target, mode_target_parallel, mode_target_parallel_for, mode_target_parallel_for_simd, mode_target_simd, mode_target_teams, mode_target_teams_distribute, mode_target_teams_distribute_parallel_for, mode_target_teams_distribute_parallel_for_simd, and mode_target_teams_distribute_simd.
llmp_add_shared_var()
int llmp_add_shared_var (LLUplevel * up, int shared_sptr)
Uniquely add a shared variable.
Definition at line 129 of file llmputil.c.
References i, idx, NEED, LLUplevel::vals, LLUplevel::vals_count, and LLUplevel::vals_size.
Referenced by llmp_concur_add_shared_var(), mp_add_shared_var(), and read_symbol().
llmp_add_shared_var_charlen()
void llmp_add_shared_var_charlen (LLUplevel * up, int shared_sptr)
...
Definition at line 150 of file llmputil.c.
References i, idx, NEED, LLUplevel::vals, LLUplevel::vals_count, and LLUplevel::vals_size.
Referenced by mp_add_shared_var().
llmp_append_uplevel()
void llmp_append_uplevel (int from_sptr, int to_sptr)
...
llmp_concur_add_shared_var()
void llmp_concur_add_shared_var (int uplevel_sptr, int shared_sptr)
...
Definition at line 426 of file llmputil.c.
References llmp_add_shared_var(), llmp_create_uplevel(), and void().
llmp_create_task()
LLTask * llmp_create_task (int scope_sptr)
Create task object that can be searched for later using scope_sptr.
Parameters
scope_sptr ...
Definition at line 262 of file llmputil.c.
References llmp_all_tasks, llmp_task_get_base_task_size(), NEED, and task.
Referenced by llGetTask(), and llmp_task_add().
llmp_create_uplevel()
LLUplevel * llmp_create_uplevel (int uplevel_sptr)
Create an LLUplevel instance.
Parameters
stblock_sptr Block where this region nest begins. This is used as a key into the global list of all uplevels.
Definition at line 74 of file llmputil.c.
References assert, ERR_Fatal, get_uplevel(), llmp_all_uplevels, and NEED.
Referenced by get_stblk_uplevel_sptr(), llmp_concur_add_shared_var(), llmp_uplevel_set_parent(), and mp_create_bscope().
llmp_create_uplevel_bykey()
LLUplevel * llmp_create_uplevel_bykey (int key)
Retrieve an LLUplevel instance by key.
Definition at line 183 of file llmputil.c.
References assert, ERR_Fatal, and llmp_all_uplevels.
Referenced by fix_symbol(), ll_load_outlined_args(), and read_symbol().
llmp_get_next_key()
int llmp_get_next_key (void)
Return a new key (index) into our table of all uplevels.
Definition at line 166 of file llmputil.c.
References llmp_all_uplevels, and NEED.
Referenced by fix_symbol(), ll_load_outlined_args(), and read_symbol().
llmp_get_parent_sptr()
SPTR llmp_get_parent_sptr (SPTR child)
Return symbol pointer of its parent.
Definition at line 244 of file llmputil.c.
References get_uplevel(), and LLUplevel::parent.
Referenced by findUplevelForSharedVar().
llmp_get_task()
LLTask * llmp_get_task (int scope_sptr)
...
Definition at line 251 of file llmputil.c.
References i, if(), llmp_all_tasks, NULL, and task.
Referenced by ll_make_kmpc_task_arg(), llGetTask(), and llmp_task_add().
llmp_get_uplevel()
LLUplevel * llmp_get_uplevel (int uplevel_sptr)
Obtain a previously created uplevel.
Definition at line 107 of file llmputil.c.
References get_uplevel().
Referenced by createUplevelSptr(), dump_parsyms(), findUplevelForSharedVar(), fix_symbol(), getTaskSharedSize(), ll_get_uplevel_offset(), ll_load_outlined_args(), ll_make_uplevel_type(), ll_parent_vals_count(), llmp_outermost_uplevel(), llmp_parent_uplevel(), loadUplevelArgsForRegion(), lower_symbol(), and set_parref_flag2().
llmp_has_uplevel()
LLUplevel * llmp_has_uplevel (int uplevel_sptr)
Return an uplevel pointer if it has an entry in uplevel table or NULL if there is no entry.
Definition at line 55 of file llmputil.c.
References assert, ERR_Fatal, llmp_all_uplevels, and NULL.
Referenced by do_firstprivate(), fix_symbol(), getTaskSharedSize(), llmp_uplevel_set_parent(), loadUplevelArgsForRegion(), and lower_symbol().
llmp_outermost_uplevel()
LLUplevel * llmp_outermost_uplevel (SPTR child)
Return outermost uplevel of current region.
Definition at line 222 of file llmputil.c.
References get_uplevel(), llmp_get_uplevel(), and LLUplevel::parent.
Referenced by findUplevelForSharedVar(), and loadUplevelArgsForRegion().
llmp_parent_uplevel()
LLUplevel * llmp_parent_uplevel (SPTR child)
Return uplevel pointer of current uplevel's parent.
Definition at line 232 of file llmputil.c.
References get_uplevel(), llmp_get_uplevel(), NULL, and LLUplevel::parent.
Referenced by findUplevelForSharedVar().
llmp_reset_uplevel()
void llmp_reset_uplevel (void)
...
Definition at line 196 of file llmputil.c.
References FREE, i, llmp_all_tasks, llmp_all_uplevels, task, LLUplevel::vals, and LLUplevel::vals_count.
Referenced by sym_init().
llmp_task_add()
void llmp_task_add (int scope_sptr, int shared_sptr, SPTR private_sptr)
Create a task object if it does not already exist for scope_sptr Add a private sptr to the task object. shared, priv: See llmp_task_add_private.
Definition at line 385 of file llmputil.c.
References assert, ERR_Fatal, llmp_create_task(), llmp_get_task(), llmp_task_add_private(), and task.
llmp_task_add_loopvar()
int llmp_task_add_loopvar (LLTask * task, int num, DTYPE dtype)
...
Definition at line 359 of file llmputil.c.
References ALIGN, alignment(), num, offset, size, task, and zsize_of().
Referenced by exp_smp().
llmp_task_add_private()
int llmp_task_add_private (LLTask * task, int shared_sptr, SPTR private_sptr)
Add a private sptr to the task object. priv: sptr to the private copy of the private variable. ADDRESSP is called to set the offset to the kmpc task object where this private data will live during program execution. /.
Definition at line 321 of file llmputil.c.
References ALIGN, alignment(), fp, idx, NEED, offset, size, size_of_sym(), size_of_var(), task, and zsize_of().
Referenced by exp_smp(), and llmp_task_add().
llmp_task_get_base_task_size()
int llmp_task_get_base_task_size (void)
...
Definition at line 281 of file llmputil.c.
Referenced by llmp_create_task().
llmp_task_get_by_fnsptr()
LLTask * llmp_task_get_by_fnsptr (int task_sptr)
...
Definition at line 309 of file llmputil.c.
References i, if(), llmp_all_tasks, NULL, and task.
llmp_task_get_private()
int llmp_task_get_private (const LLTask * task, int sptr, int incl)
...
Definition at line 398 of file llmputil.c.
References FE90, i, is_llvm_local_private(), sptr, and task.
llmp_task_get_privoff()
INT llmp_task_get_privoff (int sptr, const LLTask * task)
...
Definition at line 415 of file llmputil.c.
References i, sptr, and task.
llmp_task_get_size()
int llmp_task_get_size (LLTask * task)
...
Definition at line 295 of file llmputil.c.
References task.
Referenced by ll_make_kmpc_task_arg().
llmp_task_set_fnsptr()
void llmp_task_set_fnsptr (LLTask * task, int task_sptr)
...
Definition at line 302 of file llmputil.c.
References task.
Referenced by exp_smp().
llmp_uplevel_has_parent()
int llmp_uplevel_has_parent (int uplevel)
...
llmp_uplevel_set_dtype()
void llmp_uplevel_set_dtype (LLUplevel * up, DTYPE dtype)
Set the dtype (actual struct of member pointers)
Definition at line 113 of file llmputil.c.
References LLUplevel::dtype.
Referenced by createUplevelSptr().
llmp_uplevel_set_parent()
void llmp_uplevel_set_parent (SPTR uplevel_sptr, SPTR parent_sptr)
Set uplevel parent field.
Definition at line 119 of file llmputil.c.
References llmp_create_uplevel(), llmp_has_uplevel(), NULL, and LLUplevel::parent.
Referenced by mp_create_bscope().
Variable Documentation
omp_target_mode_names
const char* omp_target_mode_names[] static
Initial value:
= {
                                    "None target",
                                    "target",
                                    "target teams",
                                    "target teams distribute",
                                    "target teams distribute simd",
                                    "target teams distribute parallel for",
                                    "target teams distribute parallel for simd",
                                    "target parallel",
                                    "target parallel for",
                                    "target parallel for simd",
                                    "target simd",
                                    "target data enter",
                                    "target data exit",
                                    "target data",
                                    "outlined teams region",
                                    "outlined parallel region",
                                    "target update begin",
                                    "target update end" }
Definition at line 106 of file llmputil.h.