flang: llopt.cpp File Reference
llopt.cpp File Reference
optimization/peephole/inst simplification routines for LLVM Code Generator
#include "llopt.h"
#include "dtypeutl.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "llutil.h"
#include "cgllvm.h"
#include "ili.h"
#include "mwd.h"
#include <stdlib.h>
Classes
struct AconSets
Macros
#define DEC_UCOUNT(i) ((i)->tmps->use_count--)
Functions
void optimize_block (INSTR_LIST *last_block_instr)
...
static bool is_recip (OPERAND *cand)
Determine if cand has the form 1.0 / y
static void fixup_recip_div (OPERAND *x, OPERAND *recip)
Helper function.
static ILI_OP convert_mul_to_div (ILI_OP opc)
Translate a fp mul to a fp div ILI opcode.
void maybe_undo_recip_div (INSTR_LIST *mul)
Translate x * 1.0 / y to x / y.
static INLINE DTYPE getWideDType (bool isUnsigned)
Return a wide integer dtype, either signed or unsigned.
static SPTR getNewWideSym (DTYPE dty)
Create a new temp that is a wide integer type.
static int widenPushdown (ILI_OP opc, int ilix)
Push a cast of opc down the tree ilix.
static bool widenAddressArithmetic (int ilix)
Perform widening on address arithmetic.
static bool widenAnyAddressing (int ilix)
Find address arithmetic and widen it.
static void widenAddNarrowVars (int ilix, hashset_t widenVar_set)
Add widen targets in ilix to the var map.
static bool widenAconIsPrivate (int ilix)
Test if this load is from a private variable.
static INLINE int widenInsertWideStore (int ilt, int lhsIli, int rhsIli, int nme)
Add a new wider store.
static INLINE void widenProcessDirectLoad (int ldIli, hashmap_t map)
static INLINE bool hasExactlyOneStore (int aconIli, int *cilt)
static INLINE void widenProcessIndirectLoad (int ldIli, int aconIli, hashmap_t map)
static void widenCreateWideLocal (hash_key_t key, void *map)
Create a wide load from the given narrow load.
static INLINE void widenApplyFree (int ilix, hashmap_t map)
static void widenApplyVarMap (int ilix, hashmap_t map)
static void widenApplyCse (int ilix, hashmap_t map)
static void dumpWidenVars (hash_key_t key, hash_data_t data, void *_)
static void gatherLocals (hash_key_t key, hash_data_t data, void *map_)
If {key -> data} maps to an ACON, place ACON in map_.
static INLINE void widenApplyStore (int ilix, hashmap_t map)
bool funcHasNoDepChk (void)
Does the current procedure have blocks marked no dep check?
static void widenElimAddrTaken (int ilix, hashset_t zt)
static void widenGatherAcon (hash_key_t key, void *zet_)
static INLINE void hashset_swap (hashset_t *s1, hashset_t *s2)
static void pruneAcon (hash_key_t key, void *p)
Populate inSet with key if acon is in aconSet.
static INLINE void widenPruneAcon (hashset_t *loadSt, hashset_t aconSt)
Prune loadSt to only those loads that reference acon in aconSt.
void widenAddressArith (void)
Widen address arithmetic.
bool block_branches_to (int bih, int target)
Does block bih branch to block target?
static INLINE void rlleMakeSet (hash_key_t key, hash_data_t data, void *set_)
static void rlleFindLL (int ilix, hashset_t zt, hashmap_t mp)
Search the omp simd block for load-load patterns.
static INLINE bool rlleInitializerFound (hash_data_t data)
Was an initializer for this load pair created? If a candidate's initializer cannot be found, the map will be 0.
static void rlleReplace (int ilix, hashmap_t map)
Rewrite the ILIs with substitutions for load-load patterns.
void redundantLdLdElim (void)
Eliminate load-load operations from the uplevel structure.
Detailed Description
optimization/peephole/inst simplification routines for LLVM Code Generator
Definition in file llopt.cpp.
Macro Definition Documentation
DEC_UCOUNT
#define DEC_UCOUNT (i) ((i)->tmps->use_count--)
Definition at line 25 of file llopt.cpp.
Function Documentation
block_branches_to()
bool block_branches_to (int bih, int target)
Does block bih branch to block target?
...
Definition at line 884 of file llopt.cpp.
References BIH_ILTLAST, IL_TYPE, ili, ILI_OPC, ILI_OPND, ilis, ilt, ILT_ILIP, and ILTY_BRANCH.
Referenced by fix_nodepchk_flag(), and redundantLdLdElim().
convert_mul_to_div()
static ILI_OP convert_mul_to_div (ILI_OP opc) static
Translate a fp mul to a fp div ILI opcode.
Parameters
opc The opcode to translate
Returns
The DIV form if opc is a FP MUL, otherwise opc itself
NB: Used to overwrite the opcode in the ILI. Any subsequent passes (FMA) that examine the ILI must not conclude that this is still a multiply operation.
Definition at line 244 of file llopt.cpp.
Referenced by maybe_undo_recip_div().
dumpWidenVars()
static void dumpWidenVars (hash_key_t key, hash_data_t data, void * _) static
Definition at line 658 of file llopt.cpp.
References dilitre(), f, FILE, gbl, and HKEY2INT.
Referenced by widenAddressArith().
fixup_recip_div()
static void fixup_recip_div (OPERAND * x, OPERAND * recip) static
Helper function.
Parameters
x This is the x operand in a (/ x) insn [precondition]
recip The (/ 1.0 y) term for splicing
Peephole rewrite of the bridge IR. The C compiler will DCE the unused div operation. The C++ compiler will not, but instead leans on LLVM to DCE the (/ 1.0 undef) operation.
Definition at line 226 of file llopt.cpp.
References TMP_TAG::idef, TMP_TAG::info, OPERAND::ll_type, make_undef_op(), OPERAND::next, INSTR_TAG::operands, OPERAND::tmps, TMP_TAG::use_count, and x.
Referenced by maybe_undo_recip_div().
funcHasNoDepChk()
bool funcHasNoDepChk (void)
Does the current procedure have blocks marked no dep check?
...
Definition at line 707 of file llopt.cpp.
References BIH_NEXT, and BIH_NODEPCHK.
Referenced by schedule(), and widenAddressArith().
gatherLocals()
static void gatherLocals (hash_key_t key, hash_data_t data, void * map_) static
If {key -> data} maps to an ACON, place ACON in map_.
Parameters
key A hashmap key
data A hashmap value
map_ A hashmap to be populated Called by hashmap_iterate().
Definition at line 678 of file llopt.cpp.
References hashmap_replace(), HKEY2INT, ILI_OPC, ILI_OPND, and INT2HKEY.
Referenced by widenAddressArith().
getNewWideSym()
static SPTR getNewWideSym (DTYPE dty) static
Create a new temp that is a wide integer type.
Parameters
dty The wide integer dtype
Definition at line 313 of file llopt.cpp.
References getccsym(), and SC_AUTO.
Referenced by redundantLdLdElim(), widenProcessDirectLoad(), and widenProcessIndirectLoad().
getWideDType()
static INLINE DTYPE getWideDType (bool isUnsigned) static
Return a wide integer dtype, either signed or unsigned.
Definition at line 303 of file llopt.cpp.
Referenced by widenProcessDirectLoad(), and widenProcessIndirectLoad().
hasExactlyOneStore()
static INLINE bool hasExactlyOneStore (int aconIli, int * cilt) static
Definition at line 506 of file llopt.cpp.
References BIH_ILTFIRST, BIH_NEXT, count, IL_TYPE, ILI_OPC, ILI_OPND, ilt, ILT_DELETE, ILT_ILIP, ILT_NEXT, and ILTY_STORE.
Referenced by widenProcessIndirectLoad().
hashset_swap()
static INLINE void hashset_swap (hashset_t * s1, hashset_t * s2) static
Definition at line 756 of file llopt.cpp.
Referenced by widenPruneAcon().
is_recip()
static bool is_recip (OPERAND * cand) static
Determine if cand has the form 1.0 / y
Definition at line 190 of file llopt.cpp.
References STB::dbl1, STB::flt1, I_FDIV, INSTR_TAG::i_name, TMP_TAG::idef, ILI_OPC, ILI_OPND, INSTR_TAG::ilix, TMP_TAG::info, NULL, INSTR_TAG::operands, OT_CONSTSPTR, OPERAND::ot_type, sptr, OPERAND::sptr, stb, OPERAND::tmps, TMP_TAG::use_count, and OPERAND::val.
Referenced by maybe_undo_recip_div().
maybe_undo_recip_div()
void maybe_undo_recip_div (INSTR_LIST * mul)
Translate x * 1.0 / y to x / y.
...
Parameters
mul A FP multiply instruction
Preconditions: mul is a well-formed I_FMUL, has a positive use count
Definition at line 268 of file llopt.cpp.
References convert_mul_to_div(), fixup_recip_div(), I_FDIV, INSTR_TAG::i_name, ILI_OPC, ILI_OPCP, INSTR_TAG::ilix, is_recip(), OPERAND::next, and INSTR_TAG::operands.
Referenced by undo_recip_div().
optimize_block()
void optimize_block (INSTR_LIST * last_block_instr)
...
Definition at line 145 of file llopt.cpp.
References INSTR_TAG::flags, INSTR_TAG::i_name, I_NONE, INST_VISITED, last_instr, NULL, INSTR_TAG::prev, and STARTEBB.
Referenced by schedule().
pruneAcon()
static void pruneAcon (hash_key_t key, void * p) static
Populate inSet with key if acon is in aconSet.
Definition at line 769 of file llopt.cpp.
References AconSets::aconSet, hashset_lookup(), hashset_replace(), HKEY2INT, ILI_OPND, AconSets::inSet, INT2HKEY, and p.
Referenced by widenPruneAcon().
redundantLdLdElim()
void redundantLdLdElim (void)
Eliminate load-load operations from the uplevel structure.
...
Precondition
The current procedure is an outlined function with no dep check blocks
Definition at line 988 of file llopt.cpp.
References ad1ili(), ad3ili(), ad4ili(), addilt(), assert, BIH_ILTFIRST, BIH_NEXT, BIH_NODEPCHK, block_branches_to(), DT_CPTR, ERR_Fatal, get_acon3(), getNewWideSym(), hash_functions_direct, hashmap_alloc(), hashmap_clear(), hashmap_free(), hashmap_insert(), hashmap_iterate(), hashmap_lookup(), hashmap_replace(), hashmap_size(), hashset_alloc(), hashset_free(), HKEY2INT, IL_TYPE, ILI_OPC, ILI_OPND, ilt, ILT_DELETE, ILT_ILIP, ILT_NEXT, ILTY_STORE, INT2HKEY, lda, MSZ_PTR, rlleFindLL(), rlleMakeSet(), rlleReplace(), and widenAconIsPrivate().
Referenced by schedule().
rlleFindLL()
static void rlleFindLL (int ilix, hashset_t zt, hashmap_t mp) static
Search the omp simd block for load-load patterns.
Parameters
ilix the root of the ILI tree
zt set of candidates (ACON)
mp {ACON -> 0} (output map)
Definition at line 915 of file llopt.cpp.
References hashmap_replace(), hashset_lookup(), i, IL_ISLINK, IL_TYPE, ILI_OPC, ILI_OPND, ilis, ILTY_LOAD, INT2HKEY, ILIINFO::oprs, and rlleFindLL().
Referenced by redundantLdLdElim(), and rlleFindLL().
rlleInitializerFound()
static INLINE bool rlleInitializerFound (hash_data_t data) static
Was an initializer for this load pair created? If a candidate's initializer cannot be found, the map will be 0.
Definition at line 946 of file llopt.cpp.
References INT2HKEY.
Referenced by rlleReplace().
rlleMakeSet()
static INLINE void rlleMakeSet (hash_key_t key, hash_data_t data, void * set_) static
Definition at line 900 of file llopt.cpp.
References hashset_insert(), and HKEY2INT.
Referenced by redundantLdLdElim().
rlleReplace()
static void rlleReplace (int ilix, hashmap_t map) static
Rewrite the ILIs with substitutions for load-load patterns.
Definition at line 955 of file llopt.cpp.
References hashmap_lookup(), HKEY2INT, i, IL_ISLINK, IL_TYPE, ILI_OPC, ILI_OPND, ilis, ILTY_LOAD, INT2HKEY, ILIINFO::oprs, rlleInitializerFound(), and rlleReplace().
Referenced by redundantLdLdElim(), and rlleReplace().
widenAconIsPrivate()
static bool widenAconIsPrivate (int ilix) static
Test if this load is from a private variable.
Definition at line 465 of file llopt.cpp.
References assert, DT_ISINT, DTY, ERR_Fatal, ILI_OPC, ILI_SymOPND, and SymConval1.
Referenced by redundantLdLdElim(), and widenCreateWideLocal().
widenAddNarrowVars()
static void widenAddNarrowVars (int ilix, hashset_t widenVar_set) static
Add widen targets in ilix to the var map.
Definition at line 443 of file llopt.cpp.
References hashset_replace(), i, IL_ISLINK, IL_TYPE, ILI_OPC, ILI_OPND, ilis, ILTY_LOAD, INT2HKEY, ILIINFO::oprs, and widenAddNarrowVars().
Referenced by widenAddNarrowVars(), and widenAddressArith().
widenAddressArith()
void widenAddressArith (void)
Widen address arithmetic.
...
Definition at line 796 of file llopt.cpp.
References BIH_ILTFIRST, BIH_NEXT, DBGBIT, dumpblocks(), dumpWidenVars(), funcHasNoDepChk(), gatherLocals(), hash_functions_direct, hashmap_alloc(), hashmap_free(), hashmap_iterate(), hashset_alloc(), hashset_free(), hashset_iterate(), hashset_size(), ILI_OPC, ilt, ILT_DELETE, ILT_ILIP, ILT_NEXT, NULL, widenAddNarrowVars(), widenAnyAddressing(), widenApplyCse(), widenApplyFree(), widenApplyStore(), widenApplyVarMap(), widenCreateWideLocal(), widenElimAddrTaken(), widenGatherAcon(), widenPruneAcon(), widenPushdown(), and x.
Referenced by schedule().
widenAddressArithmetic()
static bool widenAddressArithmetic (int ilix) static
Perform widening on address arithmetic.
Parameters
ilix The root of the tree to be widened
The root of the tree will already be wide because of large arrays. However, we want to force any sign- or zero-extension operations down towards the leaves of the tree and promote the arithmetic operations to 64 bits.
Definition at line 392 of file llopt.cpp.
References i, IL_ISLINK, ILI_OPC, ILI_OPND, ilis, ILIINFO::oprs, widenAddressArithmetic(), widenPushdown(), and x.
Referenced by widenAddressArithmetic(), and widenAnyAddressing().
widenAnyAddressing()
static bool widenAnyAddressing (int ilix) static
Find address arithmetic and widen it.
Parameters
ilix The root of the ILI tree to be examined
We traverse the tree and look for any address arithmetic. If any is found, call widenAddressArithmetic().
Definition at line 422 of file llopt.cpp.
References i, IL_ISLINK, ILI_OPC, ILI_OPND, ilis, ILIINFO::oprs, widenAddressArithmetic(), and widenAnyAddressing().
Referenced by widenAddressArith(), and widenAnyAddressing().
widenApplyCse()
static void widenApplyCse (int ilix, hashmap_t map) static
Definition at line 628 of file llopt.cpp.
References ad1ili(), hashmap_lookup(), HKEY2INT, i, IL_ISLINK, ILI_OPC, ILI_OPND, ilis, INT2HKEY, ILIINFO::oprs, and widenApplyCse().
Referenced by widenAddressArith(), and widenApplyCse().
widenApplyFree()
static INLINE void widenApplyFree (int ilix, hashmap_t map) static
Definition at line 576 of file llopt.cpp.
References hashmap_lookup(), HKEY2INT, ILI_OPC, ILI_OPCP, ILI_OPND, and INT2HKEY.
Referenced by widenAddressArith().
widenApplyStore()
static INLINE void widenApplyStore (int ilix, hashmap_t map) static
Definition at line 690 of file llopt.cpp.
References ad1ili(), hashmap_lookup(), HKEY2INT, IL_TYPE, ILI_OPC, ILI_OPND, ILTY_STORE, INT2HKEY, and MSZ_I8.
Referenced by widenAddressArith().
widenApplyVarMap()
static void widenApplyVarMap (int ilix, hashmap_t map) static
Definition at line 591 of file llopt.cpp.
References hashmap_lookup(), HKEY2INT, i, IL_ISLINK, ILI_ALT, ILI_OPC, ILI_OPND, ilis, INT2HKEY, ILIINFO::oprs, and widenApplyVarMap().
Referenced by widenAddressArith(), and widenApplyVarMap().
widenCreateWideLocal()
static void widenCreateWideLocal (hash_key_t key, void * map) static
Create a wide load from the given narrow load.
Parameters
key The narrow load (as a key)
map A hashmap to add the (narrow -> wide) mapping
Definition at line 554 of file llopt.cpp.
References assert, ERR_Fatal, HKEY2INT, ILI_OPC, ILI_OPND, widenAconIsPrivate(), widenProcessDirectLoad(), and widenProcessIndirectLoad().
Referenced by widenAddressArith().
widenElimAddrTaken()
static void widenElimAddrTaken (int ilix, hashset_t zt) static
Definition at line 717 of file llopt.cpp.
References hashset_erase(), hashset_lookup(), i, IL_ISLINK, IL_TYPE, ILI_ALT, ILI_OPC, ILI_OPND, ilis, ILTY_LOAD, ILTY_STORE, INT2HKEY, ILIINFO::oprs, and widenElimAddrTaken().
Referenced by widenAddressArith(), and widenElimAddrTaken().
widenGatherAcon()
static void widenGatherAcon (hash_key_t key, void * zet_) static
Definition at line 746 of file llopt.cpp.
References assert, ERR_Fatal, hashset_replace(), HKEY2INT, IL_TYPE, ILI_OPC, ILI_OPND, ILTY_LOAD, and INT2HKEY.
Referenced by widenAddressArith().
widenInsertWideStore()
static INLINE int widenInsertWideStore (int ilt, int lhsIli, int rhsIli, int nme) static
Add a new wider store.
Generate a new tree and insert it after ilt.
Definition at line 485 of file llopt.cpp.
References ad4ili(), addilt(), ilt, and MSZ_I8.
Referenced by widenProcessIndirectLoad().
widenProcessDirectLoad()
static INLINE void widenProcessDirectLoad (int ldIli, hashmap_t map) static
Definition at line 493 of file llopt.cpp.
References ad1ili(), ad3ili(), get_acon3(), get_type(), getNewWideSym(), getWideDType(), hashmap_replace(), ILI_OPND, INT2HKEY, and MSZ_I8.
Referenced by widenCreateWideLocal().
widenProcessIndirectLoad()
static INLINE void widenProcessIndirectLoad (int ldIli, int aconIli, hashmap_t map) static
Definition at line 528 of file llopt.cpp.
References ad1ili(), ad3ili(), get_acon3(), get_type(), getNewWideSym(), getWideDType(), hasExactlyOneStore(), hashmap_replace(), ILI_OPND, INT2HKEY, MSZ_I8, st, and widenInsertWideStore().
Referenced by widenCreateWideLocal().
widenPruneAcon()
static INLINE void widenPruneAcon (hashset_t * loadSt, hashset_t aconSt) static
Prune loadSt to only those loads that reference acon in aconSt.
Parameters
loadSt The set of loads to be pruned
aconSt The set of legal ACON nodes
Definition at line 783 of file llopt.cpp.
References hash_functions_direct, hashset_alloc(), hashset_free(), hashset_iterate(), hashset_swap(), and pruneAcon().
Referenced by widenAddressArith().
widenPushdown()
static int widenPushdown (ILI_OP opc, int ilix) static
Push a cast of opc down the tree ilix.
Definition at line 328 of file llopt.cpp.
References ad1ili(), ad2ili(), ad4ili(), IL_IADD, IL_IMUL, IL_ISUB, ILI_OPC, ILI_OPND, r, r4, and widenPushdown().
Referenced by widenAddressArith(), widenAddressArithmetic(), and widenPushdown().