flang: llsched.cpp File Reference
llsched.cpp File Reference
scheduling routines for LLVM Code Generator
#include "llsched.h"
Functions
static bool init_sched_graph (int size, int srank)
static void add_successor (INSTR_LIST *instr, INSTR_LIST *succ)
static bool build_same_base_nme (int nme1, int nme2, int *res_nme)
int enhanced_conflict (int nme1, int nme2)
...
static void build_idep_graph (INSTR_LIST *iroot, INSTR_LIST *cur_instr)
static bool is_lltype_interesting (LL_Type *llt)
static INSTR_LIST * build_block_idep_graph (INSTR_LIST *istart, bool *success)
void sched_block_breadth_first (INSTR_LIST *istart, int level)
...
void check_circular_dep (INSTR_LIST *istart)
...
void sched_block (INSTR_LIST *istart, INSTR_LIST *iend)
...
void sched_instructions (INSTR_LIST *istart)
...
Variables
static INSTR_LIST ** matrix_dg
static INSTR_LIST * last_instr
static int irank
static int size_dg
static int srank_dg
Detailed Description
scheduling routines for LLVM Code Generator
Definition in file llsched.cpp.
Function Documentation
add_successor()
static void add_successor (INSTR_LIST * instr, INSTR_LIST * succ) static
Definition at line 40 of file llsched.cpp.
References INSTR_TAG::flags, i, j, matrix_dg, INSTR_TAG::rank, ROOTDG, size_dg, and srank_dg.
Referenced by build_idep_graph().
build_block_idep_graph()
static INSTR_LIST * build_block_idep_graph (INSTR_LIST * istart, bool * success) static
Definition at line 226 of file llsched.cpp.
References BINOP, BITOP, build_idep_graph(), CONVERT, INSTR_TAG::flags, I_BR, I_CALL, I_FDIV, I_FPEXT, I_FPTRUNC, I_LOAD, INSTR_TAG::i_name, I_NONE, I_RET, I_STORE, I_SW, init_sched_graph(), irank, is_lltype_interesting(), OPERAND::ll_type, INSTR_TAG::ll_type, INSTR_TAG::next, INSTR_TAG::operands, PICALL, INSTR_TAG::rank, ROOTDG, and XBIT.
Referenced by sched_instructions().
build_idep_graph()
static void build_idep_graph (INSTR_LIST * iroot, INSTR_LIST * cur_instr) static
Definition at line 102 of file llsched.cpp.
References add_successor(), assert, c, FLG::depchk, enhanced_conflict(), ERR_Fatal, flg, I_LOAD, INSTR_TAG::i_name, I_STORE, IL_TYPE, ILI_OPC, ILI_OPND, INSTR_TAG::ilix, ILTY_STORE, NOCONFLICT, operand, INSTR_TAG::operands, OT_TMP, INSTR_TAG::prev, SAME, and INSTR_TAG::tmps.
Referenced by build_block_idep_graph().
build_same_base_nme()
static bool build_same_base_nme (int nme1, int nme2, int * res_nme) static
Definition at line 55 of file llsched.cpp.
References add_arrnme(), addnme(), build_same_base_nme(), DTY, NME_CNST, NME_INLARR, NME_NM, NME_SUB, NME_SYM, NME_TYPE, NT_ARR, NT_IND, NT_MEM, and NT_VAR.
Referenced by build_same_base_nme(), and enhanced_conflict().
check_circular_dep()
void check_circular_dep (INSTR_LIST * istart)
...
Definition at line 371 of file llsched.cpp.
References check_circular_dep(), INSTR_TAG::flags, i, INST_VISITED, j, matrix_dg, INSTR_TAG::rank, size_dg, and srank_dg.
Referenced by check_circular_dep().
enhanced_conflict()
int enhanced_conflict (int nme1, int nme2)
...
/**
Definition at line 88 of file llsched.cpp.
References build_same_base_nme(), c, conflict(), NOCONFLICT, SAME, and XBIT.
Referenced by build_idep_graph(), and find_load_cse().
init_sched_graph()
static bool init_sched_graph (int size, int srank) static
Definition at line 28 of file llsched.cpp.
References matrix_dg, NULL, size, size_dg, and srank_dg.
Referenced by build_block_idep_graph().
is_lltype_interesting()
static bool is_lltype_interesting (LL_Type * llt) static
Definition at line 210 of file llsched.cpp.
References LL_Type_::data_type, LL_DOUBLE, LL_FLOAT, and LL_VECTOR.
Referenced by build_block_idep_graph().
sched_block()
void sched_block (INSTR_LIST * istart, INSTR_LIST * iend)
...
Definition at line 394 of file llsched.cpp.
References last_instr, INSTR_TAG::next, NULL, INSTR_TAG::prev, and sched_block_breadth_first().
Referenced by sched_instructions().
sched_block_breadth_first()
void sched_block_breadth_first (INSTR_LIST * istart, int level)
...
Definition at line 283 of file llsched.cpp.
References i, I_BITCAST, I_GEP, I_LOAD, INSTR_TAG::i_name, I_STORE, j, k, last_instr, level(), matrix_dg, INSTR_TAG::next, NULL, pred, INSTR_TAG::prev, INSTR_TAG::rank, sched_block_breadth_first(), size_dg, and srank_dg.
Referenced by sched_block(), and sched_block_breadth_first().
sched_instructions()
void sched_instructions (INSTR_LIST * istart)
...
Definition at line 407 of file llsched.cpp.
References build_block_idep_graph(), INSTR_TAG::flags, irank, ROOTDG, and sched_block().
Referenced by schedule().
Variable Documentation
irank
int irank static
Definition at line 23 of file llsched.cpp.
Referenced by build_block_idep_graph(), and sched_instructions().
last_instr
INSTR_LIST* last_instr static
Definition at line 22 of file llsched.cpp.
Referenced by find_load_cse(), optimize_block(), sched_block(), and sched_block_breadth_first().
matrix_dg
INSTR_LIST** matrix_dg static
Definition at line 21 of file llsched.cpp.
Referenced by add_successor(), check_circular_dep(), init_sched_graph(), and sched_block_breadth_first().
size_dg
int size_dg static
Definition at line 24 of file llsched.cpp.
Referenced by add_successor(), check_circular_dep(), init_sched_graph(), and sched_block_breadth_first().
srank_dg
int srank_dg static
Definition at line 25 of file llsched.cpp.
Referenced by add_successor(), check_circular_dep(), init_sched_graph(), and sched_block_breadth_first().