flang: llsched.h File Reference
llsched.h File Reference
#include "gbldefs.h"
#include "llutil.h"
Functions
int enhanced_conflict (int nme1, int nme2)
...
void check_circular_dep (INSTR_LIST *istart)
...
void sched_block_breadth_first (INSTR_LIST *istart, int level)
...
void sched_block (INSTR_LIST *istart, INSTR_LIST *iend)
...
void sched_instructions (INSTR_LIST *istart)
...
Function Documentation
check_circular_dep()
void check_circular_dep (INSTR_LIST * istart)
...
Definition at line 371 of file llsched.cpp.
References check_circular_dep(), INSTR_TAG::flags, i, INST_VISITED, j, matrix_dg, INSTR_TAG::rank, size_dg, and srank_dg.
Referenced by check_circular_dep().
enhanced_conflict()
int enhanced_conflict (int nme1, int nme2)
...
/**
Definition at line 88 of file llsched.cpp.
sched_block()
void sched_block (INSTR_LIST * istart, INSTR_LIST * iend)
...
Definition at line 394 of file llsched.cpp.
References last_instr, INSTR_TAG::next, NULL, INSTR_TAG::prev, and sched_block_breadth_first().
Referenced by sched_instructions().
sched_block_breadth_first()
void sched_block_breadth_first (INSTR_LIST * istart, int level)
...
Definition at line 283 of file llsched.cpp.
References i, I_BITCAST, I_GEP, I_LOAD, INSTR_TAG::i_name, I_STORE, j, k, last_instr, level(), matrix_dg, INSTR_TAG::next, NULL, pred, INSTR_TAG::prev, INSTR_TAG::rank, sched_block_breadth_first(), size_dg, and srank_dg.
Referenced by sched_block(), and sched_block_breadth_first().
sched_instructions()
void sched_instructions (INSTR_LIST * istart)
...
Definition at line 407 of file llsched.cpp.