flang: llutil.cpp File Reference
llutil.cpp File Reference
#include "llutil.h"
#include "dinitutl.h"
#include "dinit.h"
#include "ll_write.h"
#include "lldebug.h"
#include "dtypeutl.h"
#include "llassem.h"
#include "llassem_common.h"
#include "cgllvm.h"
#include "cgmain.h"
#include "mach.h"
#include "symfun.h"
Classes
struct LLDEF
Macros
#define DBGTRACEIN(str) DBGXTRACEIN(DBGBIT(12, 0x20), 1, str)
#define DBGTRACEIN1(str, p1) DBGXTRACEIN1(DBGBIT(12, 0x20), 1, str, p1)
#define DBGTRACEIN2(str, p1, p2) DBGXTRACEIN2(DBGBIT(12, 0x20), 1, str, p1, p2)
#define DBGTRACEIN3(str, p1, p2, p3) DBGXTRACEIN3(DBGBIT(12, 0x20), 1, str, p1, p2, p3)
#define DBGTRACEIN4(str, p1, p2, p3, p4) DBGXTRACEIN4(DBGBIT(12, 0x20), 1, str, p1, p2, p3, p4)
#define DBGTRACEIN7(str, p1, p2, p3, p4, p5, p6, p7) DBGXTRACEIN7(DBGBIT(12, 0x20), 1, str, p1, p2, p3, p4, p5, p6, p7)
#define DBGTRACEOUT(str) DBGXTRACEOUT(DBGBIT(12, 0x20), 1, str)
#define DBGTRACEOUT1(str, p1) DBGXTRACEOUT1(DBGBIT(12, 0x20), 1, str, p1)
#define DBGTRACEOUT2(str, p1, p2) DBGXTRACEOUT2(DBGBIT(12, 0x20), 1, str, p1, p2)
#define DBGTRACEOUT3(str, p1, p2, p3) DBGXTRACEOUT3(DBGBIT(12, 0x20), 1, str, p1, p2, p3)
#define DBGTRACEOUT4(str, p1, p2, p3, p4) DBGXTRACEOUT4(DBGBIT(12, 0x20), 1, str, p1, p2, p3, p4)
#define DBGDUMPLLTYPE(str, llt) DBGXDUMPLLTYPE(DBGBIT(12, 0x20), 1, str, llt)
#define DBGTRACE(str) DBGXTRACE(DBGBIT(12, 0x20), 1, str)
#define DBGTRACE1(str, p1) DBGXTRACE1(DBGBIT(12, 0x20), 1, str, p1)
#define DBGTRACE2(str, p1, p2) DBGXTRACE2(DBGBIT(12, 0x20), 1, str, p1, p2)
#define DBGTRACE3(str, p1, p2, p3) DBGXTRACE3(DBGBIT(12, 0x20), 1, str, p1, p2, p3)
#define DBGTRACE4(str, p1, p2, p3, p4) DBGXTRACE4(DBGBIT(12, 0x20), 1, str, p1, p2, p3, p4)
#define DBGTRACE5(str, p1, p2, p3, p4, p5) DBGXTRACE5(DBGBIT(12, 0x20), 1, str, p1, p2, p3, p4, p5)
#define DT_VOID_NONE DT_NONE
#define DT_SBYTE DT_BINT
#define IS_FTN_PROC_PTR(sptr)
Typedefs
typedef struct LLDEF LLDEF
Functions
const char * get_ot_name (unsigned ot)
...
static LL_ABI_Info * ll_abi_for_missing_prototype (LL_Module *module, DTYPE return_dtype, int func_sptr, int jsra_flags)
static bool LLTYPE_equiv (LL_Type *ty1, LL_Type *ty2)
Compare two types to make sure something isn't already sideways.
void llvm_set_acc_module (void)
set the module as gpu/cpu module
void llvm_set_cpu_module (void)
LL_Module * llvm_get_current_module (void)
void llutil_struct_def_reset (void)
...
void llutil_gblvar_def_reset (void)
...
void llutil_def_reset (void)
...
void llutil_dfile_init (void)
...
static char * llutil_alloc (INT size)
const char * llutil_strdup (const char *str)
...
TMPS * make_tmps (void)
allocate a new TMPS structure
void ll_add_func_proto (int sptr, unsigned flags, int nargs, DTYPE *args)
Add a function prototype declaration to the LLVM module.
LL_InstrListFlags ldst_instr_flags_from_dtype (DTYPE dtype)
Compute load/store instruction flag bits corresponding to dtype.
LL_InstrListFlags ldst_instr_flags_from_dtype_nme (DTYPE dtype, int nme)
Compute load/store instruction flag bits corresponding to dtype/nme.
static LL_Type * ll_convert_basic_dtype_with_addrspace (LL_Module *module, DTYPE dtype, int addrspace)
static LL_Type * ll_convert_iface_sptr (LL_Module *module, SPTR iface_sptr)
void layout_struct_body (LL_Module *module, LL_Type *struct_type, int member_sptr, ISZ_T size_bytes)
Layout the body of a struct type by scanning the member symbol table entries starting at member_sptr, and call ll_set_struct_body(struct_type).
static LL_Type * ll_convert_struct_dtype (LL_Module *module, DTYPE dtype)
LL_Type * ll_convert_array_dtype (LL_Module *module, DTYPE dtype, int addrspace)
Convert a Fortran-style TY_ARRAY dtype to an LLVM array.
static LL_Type * convert_dtype (LL_Module *module, DTYPE dtype, int addrspace)
LL_Type * ll_convert_dtype (LL_Module *module, DTYPE dtype)
Convert any kind of dtype to an LLVM type.
LL_Type * ll_convert_dtype_with_addrspace (LL_Module *module, DTYPE dtype, int addrspace)
Convert any kind of dtype to an LLVM type with address space.
bool llis_integral_kind (DTYPE dtype)
bool llis_pointer_kind (DTYPE dtype)
bool llis_array_kind (DTYPE dtype)
bool llis_dummied_arg (SPTR sptr)
...
bool llis_vector_kind (DTYPE dtype)
bool llis_struct_kind (DTYPE dtype)
bool llis_function_kind (DTYPE dtype)
int is_struct_kind (DTYPE dtype, bool check_return, bool return_vector_as_struct)
...
LL_Type * make_ptr_lltype (LL_Type *pts_to)
...
LL_Type * make_int_lltype (unsigned bits)
...
LL_Type * make_void_lltype (void)
...
LL_Type * make_vector_lltype (int size, LL_Type *pts_to)
...
LL_Type * make_array_lltype (int size, LL_Type *pts_to)
...
int get_dim_size (ADSC *ad, int dim)
...
static LL_Type * lltype_from_dtype (DTYPE dtype, int addrspace)
LL_Type * make_lltype_from_dtype (DTYPE dtype)
...
LL_Type * make_lltype_from_dtype_with_addrspace (DTYPE dtype, int addrspace)
...
DTYPE generic_dummy_dtype (void)
...
LL_Type * make_generic_dummy_lltype (void)
...
LL_Type * make_lltype_from_arg (int arg)
...
LL_Type * make_lltype_from_arg_noproto (int arg)
...
DTYPE get_dtype_from_arg_opc (ILI_OP opc)
Get a function argument dtype from an IL_ARG* instruction opcode.
DTYPE get_dtype_from_tytype (TY_KIND ty)
Convert a TY_* to a DT_* value.
DTYPE get_dtype_for_vect_type_nme (int nme)
Convert a nme* to a DT_* value.
DTYPE dtype_from_return_type (ILI_OP ret_opc)
Get the function return type coprresponding to an IL_DFR* opcode.
LL_Type * make_lltype_from_iface (SPTR sptr)
...
bool is_function (int sptr)
...
static void add_def (LLDEF *new_def, LLDEF **def_list)
LL_Type * make_lltype_from_sptr (SPTR sptr)
Make an LL_Type from symbol sptr.
OPERAND * make_constsptr_op (SPTR sptr)
...
static char * ll_get_string_buf (int string_len, char *base, int skip_quotes)
static OPERAND * make_conststring_op (int sptr)
OPERAND * make_constval_op (LL_Type *ll_type, INT conval0, INT conval1)
...
OPERAND * make_constval_opL (LL_Type *ll_type, INT conval0, INT conval1, INT conval2, INT conval3)
...
OPERAND * make_constval32_op (int idx)
...
static LL_Type * set_vect3_to_size4 (LL_Type *ll_type)
LL_Type * make_lltype_sz4v3_from_sptr (SPTR sptr)
...
LL_Type * make_lltype_sz4v3_from_dtype (DTYPE dtype)
...
OPERAND * make_var_op (SPTR sptr)
...
static INLINE OPERAND * make_arg_op (SPTR sptr)
OPERAND * make_def_op (char *str)
...
static OPERAND * make_member_op_with_lltype (int address, LL_Type *llTy)
static INLINE OPERAND * make_member_op (int address, DTYPE dtype)
OPERAND * make_tmp_op (LL_Type *llt, TMPS *tmps)
...
OPERAND * make_undef_op (LL_Type *llt)
...
OPERAND * make_null_op (LL_Type *llt)
...
OPERAND * make_mdref_op (LL_MDRef mdref)
...
OPERAND * make_metadata_wrapper_op (SPTR sptr, LL_Type *llTy)
Create metadata operand that wraps an LLVM value.
OPERAND * make_target_op (SPTR sptr)
...
OPERAND * make_label_op (SPTR sptr)
...
OPERAND * make_operand (void)
...
static void set_llasm_output_file (FILE *fd)
void init_output_file (void)
...
void init_gpu_output_file (void)
void print_llsize (LL_Type *llt)
Write size of LL_Type to llvm file.
void print_llsize_tobuf (LL_Type *llt, char *buf)
...
void print_space (int num)
Write num spaces to llvm file num The number of spaces to write.
void print_space_tobuf (int num, char *buf)
...
void print_line (const char *ln)
Write any line which does not need a tab.
void print_line_tobuf (char *ln, char *buf)
Print any line which does not need a tab.
FILE * llvm_file (void)
...
void print_token (const char *tk)
Write a token at the current location with no nl.
void print_token_tobuf (char *tk, char *buf)
print a token at the current location with no nl
void print_nl (void)
Write a new line in the output llvm file.
void print_nl_tobuf (char *buf)
...
void print_dbg_line_no_comma (LL_MDRef md)
Emit line info debug information.
void print_dbg_line (LL_MDRef md)
static void write_vconstant_value (int sptr, LL_Type *type, unsigned long long undef_bitmask)
void write_constant_value (int sptr, LL_Type *type, INT conval0, INT conval1, bool uns)
Write a constant value to the output llvm file.
void write_type (LL_Type *ll_type)
Write LL_Type to llvm file.
static INLINE bool metadata_args_need_struct (void)
bool should_preserve_param (const DTYPE dtype)
return whether param debug info should be preserved
OPERAND * make_param_op (SPTR sptr)
void write_operand (OPERAND *p, const char *punc_string, int flags)
Write a single operand.
void write_operands (OPERAND *operand, int flags)
Write operand list.
void set_metadata_string (TMPS *t, char *string)
Set name for named metadata.
void init_metadata_index (TMPS *t)
Init metadata index, for anonymous metadata.
void print_metadata_name (TMPS *t)
Print metadata name.
void indent (int change)
...
bool small_aggr_return (DTYPE dtype)
...
DTYPE get_return_dtype (DTYPE dtype, unsigned *flags, unsigned new_flag)
...
DTYPE get_param_equiv_dtype (DTYPE dtype)
...
const char * llvm_fc_type (DTYPE dtype)
return string for a first class type
OPERAND * gen_copy_op (OPERAND *op)
...
OPERAND * gen_copy_list_op (OPERAND *operands)
...
static LLDEF * make_def (DTYPE dtype, int sptr, int rank, const char *name, int flags)
static LLDEF * get_def (DTYPE dtype, int sptr, int rank, LLDEF *def_list)
static OPERAND * write_def_values (OPERAND *def_op, LL_Type *type)
static void write_alt_field_types (LL_Type *llty)
static void write_def (LLDEF *def, int check_type_in_struct_def_type)
static void write_defs (LLDEF *def_list, int check_type_in_struct_def_type)
static bool defs_to_write (LLDEF *def_list)
void write_struct_defs (void)
...
void write_ftn_typedefs (void)
...
DTYPE get_int_dtype_from_size (int size)
...
int struct_typedef_name (DTYPE dtype)
OPERAND * process_symlinked_sptr (int sptr, int total_init_sz, int is_union, int max_field_sz)
...
const char * process_dtype_struct (DTYPE dtype)
...
const char * process_ftn_dtype_struct (DTYPE dtype, char *tname, bool printed)
Make a fake struct for static/common block.
LL_ABI_Info * ll_abi_alloc (LL_Module *module, unsigned nargs)
...
LL_ABI_Info * ll_abi_free (LL_ABI_Info *abi)
...
LL_Type * ll_abi_return_type (LL_ABI_Info *abi)
...
bool ll_abi_use_llvm_varargs (LL_ABI_Info *abi)
Should this function be represented as a varags LLVM function type?
LL_Type * ll_abi_function_type (LL_ABI_Info *abi)
...
void ll_abi_complete_arg_info (LL_ABI_Info *abi, LL_ABI_ArgInfo *arg, DTYPE dtype)
...
LL_ABI_Info * process_ll_abi_func_ftn_mod (LL_Module *mod, SPTR func_sptr, bool update)
Process the return type and arguments for func_sptr.
LL_ABI_Info * process_ll_abi_func_ftn (SPTR func_sptr, bool use_sptrs)
Wrapper to process_ll_abi_func_ftn_mod() passing the default module.
LL_ABI_Info * ll_abi_for_func_sptr (LL_Module *module, SPTR func_sptr, DTYPE dtype)
Get ABI lowering info for a function given its symbol table entry.
LL_ABI_Info * ll_abi_from_call_site (LL_Module *module, int ilix, DTYPE ret_dtype)
Get ABI lowering info for a specific call site.
LL_Type * make_lltype_from_abi_arg (LL_ABI_ArgInfo *arg)
...
int visit_flattened_dtype (dtype_visitor visitor, void *context, DTYPE dtype, unsigned address, unsigned member_sptr)
...
void ll_override_type_string (LL_Type *llt, const char *str)
...
static LLDEF * LLABI_find_su_type_def (DTYPE dtype)
Scan the list of struct types and find the corresponding LLDEF.
static LLDEF * LLABI_find_array_type_def (DTYPE dtype)
Scan the list of array types and find the corresponding LLDEF.
LL_Type * llfind_su_type_def (DTYPE dtype)
LL_Type * llfind_array_type_def (DTYPE dtype)
LL_Type * get_ftn_static_lltype (SPTR sptr)
...
LL_Type * get_ftn_cmblk_lltype (SPTR sptr)
...
LL_Type * get_ftn_typedesc_lltype (SPTR sptr)
...
LL_Type * get_ftn_extern_lltype (SPTR sptr)
...
LL_Type * get_ftn_cbind_lltype (SPTR sptr)
...
LL_Type * get_ftn_func_lltype (SPTR sptr)
...
LL_Type * get_ftn_dummy_lltype (int sptr)
...
LL_Type * get_ftn_hollerith_type (int sptr)
...
LL_InstrListFlags ll_instr_flags_from_aop (ATOMIC_RMW_OP aop)
Compute the LL_InstrListFlag set from an ATOMIC_RMW_OP.
LL_Type * ll_coercion_type (LL_Module *module, DTYPE dtype, ISZ_T size, ISZ_T reg_size)
Variables
static const char * ot_names [OT_LAST]
static const char * llvm_cc_names [LLCC_LAST]
static const char * llvm_ccfp_names [LLCCF_LAST]
static LLDEF * struct_def_list = NULL
static LLDEF * llarray_def_list = NULL
static LLDEF * gblvar_def_list = NULL
FTN_LLVM_ST ftn_llvm_st
FILE * LLVMFIL = NULL
static int is_gpu_module = false
static int metadata_id = 0
static int indentlev = 0
FILE * ll_dfile
Macro Definition Documentation
DBGDUMPLLTYPE
#define DBGDUMPLLTYPE (str, llt) DBGXDUMPLLTYPE(DBGBIT(12, 0x20), 1, str, llt)
Definition at line 71 of file llutil.cpp.
DBGTRACE
#define DBGTRACE (str) DBGXTRACE(DBGBIT(12, 0x20), 1, str)
Definition at line 73 of file llutil.cpp.
DBGTRACE1
#define DBGTRACE1 (str, p1) DBGXTRACE1(DBGBIT(12, 0x20), 1, str, p1)
Definition at line 74 of file llutil.cpp.
DBGTRACE2
#define DBGTRACE2 (str, p1, p2) DBGXTRACE2(DBGBIT(12, 0x20), 1, str, p1, p2)
Definition at line 75 of file llutil.cpp.
DBGTRACE3
#define DBGTRACE3 (str, p1, p2, p3) DBGXTRACE3(DBGBIT(12, 0x20), 1, str, p1, p2, p3)
Definition at line 76 of file llutil.cpp.
DBGTRACE4
#define DBGTRACE4 (str, p1, p2, p3, p4) DBGXTRACE4(DBGBIT(12, 0x20), 1, str, p1, p2, p3, p4)
Definition at line 78 of file llutil.cpp.
DBGTRACE5
#define DBGTRACE5 (str, p1, p2, p3, p4, p5) DBGXTRACE5(DBGBIT(12, 0x20), 1, str, p1, p2, p3, p4, p5)
Definition at line 80 of file llutil.cpp.
DBGTRACEIN
#define DBGTRACEIN (str) DBGXTRACEIN(DBGBIT(12, 0x20), 1, str)
Definition at line 52 of file llutil.cpp.
DBGTRACEIN1
#define DBGTRACEIN1 (str, p1) DBGXTRACEIN1(DBGBIT(12, 0x20), 1, str, p1)
Definition at line 53 of file llutil.cpp.
DBGTRACEIN2
#define DBGTRACEIN2 (str, p1, p2) DBGXTRACEIN2(DBGBIT(12, 0x20), 1, str, p1, p2)
Definition at line 54 of file llutil.cpp.
DBGTRACEIN3
#define DBGTRACEIN3 (str, p1, p2, p3) DBGXTRACEIN3(DBGBIT(12, 0x20), 1, str, p1, p2, p3)
Definition at line 55 of file llutil.cpp.
DBGTRACEIN4
#define DBGTRACEIN4 (str, p1, p2, p3, p4) DBGXTRACEIN4(DBGBIT(12, 0x20), 1, str, p1, p2, p3, p4)
Definition at line 57 of file llutil.cpp.
DBGTRACEIN7
#define DBGTRACEIN7 (str, p1, p2, p3, p4, p5, p6, p7) DBGXTRACEIN7(DBGBIT(12, 0x20), 1, str, p1, p2, p3, p4, p5, p6, p7)
Definition at line 59 of file llutil.cpp.
DBGTRACEOUT
#define DBGTRACEOUT (str) DBGXTRACEOUT(DBGBIT(12, 0x20), 1, str)
Definition at line 62 of file llutil.cpp.
DBGTRACEOUT1
#define DBGTRACEOUT1 (str, p1) DBGXTRACEOUT1(DBGBIT(12, 0x20), 1, str, p1)
Definition at line 63 of file llutil.cpp.
DBGTRACEOUT2
#define DBGTRACEOUT2 (str, p1, p2) DBGXTRACEOUT2(DBGBIT(12, 0x20), 1, str, p1, p2)
Definition at line 64 of file llutil.cpp.
DBGTRACEOUT3
#define DBGTRACEOUT3 (str, p1, p2, p3) DBGXTRACEOUT3(DBGBIT(12, 0x20), 1, str, p1, p2, p3)
Definition at line 66 of file llutil.cpp.
DBGTRACEOUT4
#define DBGTRACEOUT4 (str, p1, p2, p3, p4) DBGXTRACEOUT4(DBGBIT(12, 0x20), 1, str, p1, p2, p3, p4)
Definition at line 68 of file llutil.cpp.
DT_SBYTE
#define DT_SBYTE DT_BINT
Definition at line 85 of file llutil.cpp.
DT_VOID_NONE
#define DT_VOID_NONE DT_NONE
Definition at line 83 of file llutil.cpp.
IS_FTN_PROC_PTR
#define IS_FTN_PROC_PTR (sptr)
Value:
  ((DTY(DTYPEG(sptr)) == TY_PTR) && \
   (DTY(DTySeqTyElement(DTYPEG(sptr))) == TY_PROC))
Definition at line 1194 of file llutil.cpp.
Typedef Documentation
LLDEF
typedef struct LLDEF LLDEF
Function Documentation
add_def()
static void add_def (LLDEF * new_def, LLDEF ** def_list) static
Definition at line 1206 of file llutil.cpp.
References LLDEF::dtype, LLDEF::ll_type, make_lltype_from_dtype(), LLDEF::next, and NULL.
Referenced by make_lltype_from_sptr(), process_dtype_struct(), and process_ftn_dtype_struct().
convert_dtype()
static LL_Type * convert_dtype (LL_Module * module, DTYPE dtype, int addrspace) static
Definition at line 641 of file llutil.cpp.
References LLDEF::addrspace, LL_Type_::data_type, dt, DT_ISBASIC, DT_ISINT, DTY, DTySeqTyElement, DTyVecLength, ERR_Fatal, interr(), ll_convert_array_dtype(), ll_convert_basic_dtype_with_addrspace(), ll_convert_dtype_with_addrspace(), ll_convert_struct_dtype(), ll_create_basic_type(), ll_create_int_type_with_addrspace(), ll_get_pointer_type(), ll_get_vector_type(), LL_I8, LL_VOID, NULL, size_of(), TY_CHAR, and TY_NCHAR.
Referenced by ll_convert_dtype(), and ll_convert_dtype_with_addrspace().
defs_to_write()
static bool defs_to_write (LLDEF * def_list) static
Definition at line 3043 of file llutil.cpp.
References LLDEF::next, and LLDEF::printed.
Referenced by write_struct_defs().
dtype_from_return_type()
DTYPE dtype_from_return_type (ILI_OP ret_opc)
Get the function return type coprresponding to an IL_DFR* opcode.
...
Definition at line 1148 of file llutil.cpp.
References DT_CMPLX, DT_CPTR, DT_DBLE, DT_FLOAT, DT_INT, ERR_Fatal, and interr().
Referenced by gen_llvm_expr().
gen_copy_list_op()
OPERAND * gen_copy_list_op (OPERAND * operands)
...
Definition at line 2727 of file llutil.cpp.
References gen_copy_op(), OPERAND::next, and NULL.
gen_copy_op()
OPERAND * gen_copy_op (OPERAND * op)
...
Definition at line 2716 of file llutil.cpp.
References make_operand(), OPERAND::next, and NULL.
Referenced by find_load_cse(), gen_abs_expr(), gen_call_expr(), gen_copy_list_op(), gen_copy_operand(), gen_llvm_expr(), gen_minmax_expr(), gen_va_arg(), make_bitcast(), and x86_promote_to_vector().
generic_dummy_dtype()
DTYPE generic_dummy_dtype (void)
...
Definition at line 901 of file llutil.cpp.
References TARGET_PTRSIZE.
Referenced by DeclareSPtrAsLocal(), ll_process_routine_parameters(), and make_generic_dummy_lltype().
get_def()
static LLDEF * get_def (DTYPE dtype, int sptr, int rank, LLDEF * def_list) static
Definition at line 2764 of file llutil.cpp.
References LLDEF::dtype, LLDEF::next, NULL, rank, LLDEF::rank, sptr, and LLDEF::sptr.
Referenced by process_dtype_struct(), process_ftn_dtype_struct(), and write_def().
get_dim_size()
int get_dim_size (ADSC * ad, int dim)
...
Definition at line 868 of file llutil.cpp.
References AD_LWBD, AD_UPBD, ad_val_of(), and dim.
Referenced by ll_convert_array_dtype().
get_dtype_for_vect_type_nme()
DTYPE get_dtype_for_vect_type_nme (int nme)
Convert a nme* to a DT_* value.
...
If the DT_ value can't be determined, returns DT_NONE.
Definition at line 1080 of file llutil.cpp.
References assert, basesym_of(), DT_DBLE, DT_FLOAT, DT_INT, DTY, DTySeqTyElement, ERR_Fatal, size_of(), and SPTR_NULL.
get_dtype_from_arg_opc()
DTYPE get_dtype_from_arg_opc (ILI_OP opc)
Get a function argument dtype from an IL_ARG* instruction opcode.
...
Definition at line 965 of file llutil.cpp.
References DT_CPTR, DT_DBLE, DT_FLOAT, and DT_INT.
Referenced by gen_arg_operand().
get_dtype_from_tytype()
DTYPE get_dtype_from_tytype (TY_KIND ty)
Convert a TY_* to a DT_* value.
...
If the TY type isn't a basic type, returns DT_NONE.
Definition at line 1003 of file llutil.cpp.
References assert, DT_CMPLX, DT_CPTR, DT_DBLE, DT_DCMPLX, DT_INT, DT_LOG, DT_REAL, ERR_Fatal, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
get_ftn_cbind_lltype()
LL_Type * get_ftn_cbind_lltype (SPTR sptr)
...
Definition at line 4190 of file llutil.cpp.
References AD_DPTR, AD_NUMDIM, AD_NUMELM, ad_val_of(), assert, d, DTY, DTyAlgTyTag, DTySeqTyElement, ERR_Fatal, find_ag(), get_ag_lltype(), get_ftn_func_lltype(), get_ftn_static_lltype(), get_typedef_ag(), STB::i1, is_function(), ISZ_T, STB::k1, make_array_lltype(), make_lltype_from_dtype(), MXIDLN, name, NULL, process_dtype_struct(), set_ag_lltype(), sptr, stb, SYMNAME, tname, and XBIT.
Referenced by get_ftn_extern_lltype(), and make_lltype_from_sptr().
get_ftn_cmblk_lltype()
LL_Type * get_ftn_cmblk_lltype (SPTR sptr)
...
Definition at line 4099 of file llutil.cpp.
References assert, ERR_Fatal, find_ag(), get_ag_lltype(), get_llvm_name(), get_typedef_ag(), LLTYPE, make_lltype_from_dtype(), MXIDLN, name, NULL, set_ag_lltype(), SNAME, sptr, and tname.
Referenced by get_ftn_lltype(), and make_lltype_from_sptr().
get_ftn_dummy_lltype()
LL_Type * get_ftn_dummy_lltype (int sptr)
...
Definition at line 4277 of file llutil.cpp.
References currsub_is_sret(), gbl, GBL_CURRFUNC, LLTYPE, make_generic_dummy_lltype(), make_lltype_from_dtype(), make_ptr_lltype(), and sptr.
Referenced by make_lltype_from_sptr().
get_ftn_extern_lltype()
LL_Type * get_ftn_extern_lltype (SPTR sptr)
...
Definition at line 4176 of file llutil.cpp.
References assert, ERR_Fatal, get_ftn_cbind_lltype(), get_ftn_func_lltype(), get_ftn_typedesc_lltype(), is_function(), make_lltype_from_dtype(), and sptr.
Referenced by get_ftn_lltype(), and write_externs().
get_ftn_func_lltype()
LL_Type * get_ftn_func_lltype (SPTR sptr)
...
Definition at line 4259 of file llutil.cpp.
References assert, DT_CPTR, ERR_Fatal, get_iface_sptr(), IS_FTN_PROC_PTR, is_function(), ll_abi_for_func_sptr(), ll_abi_function_type(), llvm_get_current_module(), make_lltype_from_dtype(), make_lltype_from_iface(), NULL, and sptr.
Referenced by get_ftn_cbind_lltype(), get_ftn_extern_lltype(), and get_ftn_static_lltype().
get_ftn_hollerith_type()
LL_Type * get_ftn_hollerith_type (int sptr)
...
Definition at line 4309 of file llutil.cpp.
References DTY, DTyCharLength, get_hollerith_size(), get_type(), len, LLTYPE, make_lltype_from_dtype(), NULL, sptr, TY_CHAR, and TY_NCHAR.
Referenced by make_lltype_from_sptr().
get_ftn_static_lltype()
LL_Type * get_ftn_static_lltype (SPTR sptr)
...
Definition at line 4041 of file llutil.cpp.
References AG_LLTYPE, AG_STYPE, assert, CUDAG, DDTG, ERR_Fatal, gbl, get_ag_lltype(), get_ftn_func_lltype(), get_ftn_typedesc_lltype(), get_llvm_name(), get_typedef_ag(), getsname(), IS_FTN_PROC_PTR, is_function(), make_lltype_from_dtype(), make_ptr_lltype(), mk_struct_for_llvm_init(), MXIDLN, name, NULL, set_ag_lltype(), sptr, tname, and TY_CHAR.
Referenced by get_ftn_cbind_lltype(), get_ftn_lltype(), and make_lltype_from_sptr().
get_ftn_typedesc_lltype()
LL_Type * get_ftn_typedesc_lltype (SPTR sptr)
...
Definition at line 4143 of file llutil.cpp.
References AG_DEFD, assert, ERR_Fatal, find_ag(), get_ag(), get_ag_lltype(), get_ftn_typedesc_dtype(), get_typedef_ag(), getsname(), make_lltype_from_dtype(), MXIDLN, name, NULL, set_ag_lltype(), sptr, and tname.
Referenced by get_ftn_extern_lltype(), get_ftn_static_lltype(), and make_lltype_from_sptr().
get_int_dtype_from_size()
DTYPE get_int_dtype_from_size (int size)
...
Definition at line 3092 of file llutil.cpp.
References DT_INT, and size.
Referenced by process_symlinked_sptr().
get_ot_name()
const char * get_ot_name (unsigned ot)
...
Definition at line 46 of file llutil.cpp.
References OT_LAST, and ot_names.
get_param_equiv_dtype()
DTYPE get_param_equiv_dtype (DTYPE dtype)
...
Definition at line 2601 of file llutil.cpp.
References DT_INT, DTY, and ZSIZEOF.
get_return_dtype()
DTYPE get_return_dtype (DTYPE dtype, unsigned * flags, unsigned new_flag)
...
Definition at line 2563 of file llutil.cpp.
References assert, DT_INT, DT_ISCMPLX, DT_SBYTE, DT_VOID_NONE, DTY, ERR_Fatal, flags, is_struct_kind(), small_aggr_return(), TY_CMPLX, XBIT, and ZSIZEOF.
Referenced by process_extern_function_sptr(), and write_externs().
indent()
void indent (int change)
...
Definition at line 2537 of file llutil.cpp.
References i, indentlev, and ll_dfile.
init_gpu_output_file()
void init_gpu_output_file (void)
Definition at line 1700 of file llutil.cpp.
References flg, FTN_GPU_INIT, gbl, gpu_llvm_module, ll_write_module_header(), and FLG::omptarget.
Referenced by cg_llvm_init().
init_metadata_index()
void init_metadata_index (TMPS * t)
Init metadata index, for anonymous metadata.
...
Definition at line 2501 of file llutil.cpp.
References DBGTRACEIN1, DBGTRACEOUT1, metadata_id, and t.
init_output_file()
void init_output_file (void)
...
Definition at line 1690 of file llutil.cpp.
References FTN_HAS_INIT, gbl, ll_write_module_header(), llvm_get_current_module(), and set_llasm_output_file().
Referenced by cg_llvm_init(), and write_module_as_subroutine().
is_function()
bool is_function (int sptr)
...
Definition at line 1199 of file llutil.cpp.
References IS_FTN_PROC_PTR, and sptr.
Referenced by get_ftn_cbind_lltype(), get_ftn_extern_lltype(), get_ftn_func_lltype(), get_ftn_static_lltype(), and make_lltype_from_sptr().
is_struct_kind()
int is_struct_kind (DTYPE dtype, bool check_return, bool return_vector_as_struct)
...
Definition at line 815 of file llutil.cpp.
References check_return(), DTY, TY_CMPLX, and TY_DCMPLX.
Referenced by get_return_dtype(), and ll_process_routine_parameters().
layout_struct_body()
void layout_struct_body (LL_Module * module, LL_Type * struct_type, int member_sptr, ISZ_T size_bytes)
Layout the body of a struct type by scanning the member symbol table entries starting at member_sptr, and call ll_set_struct_body(struct_type).
...
This code can layout both struct/union dtypes and common blocks.
The provided struct_type should be created with ll_create_named_struct_type().
Padding will be added to make the size of the new struct size_bytes, unless size_bytes is -1 which is ignored.
Definition at line 406 of file llutil.cpp.
References alignment(), assert, cp, DDTG, DTY, ERR_Fatal, extent_of(), ISZ_T, ll_convert_dtype(), ll_create_basic_type(), ll_get_array_type(), ll_get_pointer_type(), LL_I8, ll_set_struct_body(), ll_type_bytes(), malloc(), NOSYM, NULL, sptr, and ZSIZEOF.
Referenced by ll_convert_struct_dtype().
ldst_instr_flags_from_dtype()
LL_InstrListFlags ldst_instr_flags_from_dtype (DTYPE dtype)
Compute load/store instruction flag bits corresponding to dtype.
...
Parameters
dtype The DTYPE
The flags encode alignment in the LDST_LOGALIGN_MASK bits and volatile types have the VOLATILE_FLAG bit set.
The returned flags are pre-shifted so they can be or'ed onto the instruction flags.
Definition at line 223 of file llutil.cpp.
References alignment(), DTY, flags, LDST_LOGALIGN_SHIFT, and VOLATILE_FLAG.
Referenced by gen_arg_operand(), gen_call_expr(), gen_llvm_expr(), gen_return_operand(), gen_va_arg(), insert_jump_entry_instr(), ldst_instr_flags_from_dtype_nme(), make_stmt(), and process_formal_arguments().
ldst_instr_flags_from_dtype_nme()
LL_InstrListFlags ldst_instr_flags_from_dtype_nme (DTYPE dtype, int nme)
Compute load/store instruction flag bits corresponding to dtype/nme.
...
Parameters
dtype The DTYPE
nme The NME
The flags encode alignment in the LDST_LOGALIGN_MASK bits and the nme NME_VOL has the VOLATILE_FLAG bit set.
The returned flags are pre-shifted so they can be or'ed onto the instruction flags.
Definition at line 261 of file llutil.cpp.
References flags, ldst_instr_flags_from_dtype(), NME_VOL, and VOLATILE_FLAG.
Referenced by gen_llvm_expr().
ll_abi_alloc()
LL_ABI_Info * ll_abi_alloc (LL_Module * module, unsigned nargs)
...
Definition at line 3605 of file llutil.cpp.
References LL_ABI_Info_::module, nargs, and LL_ABI_Info_::nargs.
Referenced by add_external_function_declaration(), ll_abi_for_missing_prototype(), ll_add_func_proto(), ll_process_routine_parameters(), and process_ll_abi_func_ftn_mod().
ll_abi_complete_arg_info()
void ll_abi_complete_arg_info (LL_ABI_Info * abi, LL_ABI_ArgInfo * arg, DTYPE dtype)
...
Definition at line 3675 of file llutil.cpp.
References arg, assert, ERR_Fatal, kind, LL_ARG_BYVAL, LL_ARG_COERCE, LL_ARG_INDIRECT, LL_ARG_INDIRECT_BUFFERED, ll_convert_dtype(), ll_get_pointer_type(), LL_VOID, LL_ABI_Info_::module, and type.
Referenced by gen_arg_operand(), ll_abi_for_missing_prototype(), ll_process_routine_parameters(), and process_ll_abi_func_ftn_mod().
ll_abi_for_func_sptr()
LL_ABI_Info * ll_abi_for_func_sptr (LL_Module * module, SPTR func_sptr, DTYPE dtype)
Get ABI lowering info for a function given its symbol table entry.
Since IPA can change the dtype of functions between calls to schedule(), use the passed dtype instead of DTYPEG(func_sptr).
Definition at line 3879 of file llutil.cpp.
References process_ll_abi_func_ftn_mod().
Referenced by add_external_function_declaration(), get_ftn_func_lltype(), ll_abi_from_call_site(), ll_check_struct_return(), make_lltype_from_sptr(), and schedule().
ll_abi_for_missing_prototype()
static LL_ABI_Info * ll_abi_for_missing_prototype (LL_Module * module, DTYPE return_dtype, int func_sptr, int jsra_flags) static
Definition at line 3857 of file llutil.cpp.
References LL_ABI_Info_::arg, assert, ERR_Fatal, LL_ABI_Info_::is_fortran, LL_ABI_Info_::is_varargs, LL_ABI_ArgInfo_::kind, ll_abi_alloc(), ll_abi_classify_return_dtype(), ll_abi_complete_arg_info(), ll_abi_compute_call_conv(), LL_ARG_BYVAL, and LL_ABI_Info_::missing_prototype.
Referenced by ll_abi_from_call_site().
ll_abi_free()
LL_ABI_Info * ll_abi_free (LL_ABI_Info * abi)
...
Definition at line 3616 of file llutil.cpp.
References assert, ERR_Fatal, LL_ABI_Info_::nargs, and NULL.
Referenced by ll_process_routine_parameters(), and process_ll_abi_func_ftn_mod().
ll_abi_from_call_site()
LL_ABI_Info * ll_abi_from_call_site (LL_Module * module, int ilix, DTYPE ret_dtype)
Get ABI lowering info for a specific call site.
ilix is the IL_JSR or IL_JSRA instruction representing the call.
ret_ili is the IL_DFRx instruction extracting the return value for the call, or 0 if the return value is unused.
This may not provide lowering information for all function arguments if the callee is varargs or if a prototype is not available.
Definition at line 3885 of file llutil.cpp.
References ERR_Fatal, find_ag(), get_llvm_funcptr_ag(), get_llvm_ifacenm(), get_llvm_name(), ILI_DTyOPND, ILI_OPC, ILI_OPND, ILI_SymOPND, interr(), ll_abi_for_func_sptr(), and ll_abi_for_missing_prototype().
Referenced by gen_call_expr().
ll_abi_function_type()
LL_Type * ll_abi_function_type (LL_ABI_Info * abi)
...
Definition at line 3648 of file llutil.cpp.
References LL_ABI_Info_::arg, i, LL_ABI_HAS_SRET, ll_abi_use_llvm_varargs(), ll_create_basic_type(), ll_create_function_type(), LL_VOID, LL_ABI_Info_::module, LL_ABI_Info_::nargs, and LL_ABI_ArgInfo_::type.
Referenced by gen_call_expr(), get_ftn_func_lltype(), make_lltype_from_sptr(), schedule(), write_final_table(), and write_vft().
ll_abi_return_type()
LL_Type * ll_abi_return_type (LL_ABI_Info * abi)
...
Definition at line 3627 of file llutil.cpp.
References LL_ABI_Info_::arg, LL_ABI_HAS_SRET, ll_create_basic_type(), LL_VOID, LL_ABI_Info_::module, and LL_ABI_ArgInfo_::type.
Referenced by gen_call_expr().
ll_abi_use_llvm_varargs()
bool ll_abi_use_llvm_varargs (LL_ABI_Info * abi)
Should this function be represented as a varags LLVM function type?
Definition at line 3636 of file llutil.cpp.
References LL_ABI_Info_::call_as_varargs, LL_ABI_Info_::is_varargs, and LL_ABI_Info_::missing_prototype.
Referenced by ll_abi_function_type(), and print_function_signature().
ll_add_func_proto()
void ll_add_func_proto (int sptr, unsigned flags, int nargs, DTYPE * args)
Add a function prototype declaration to the LLVM module.
Parameters
sptr The symbol of the function
nargs Number of arguments to the function
args An array of DTYPEs for the arguments
Definition at line 187 of file llutil.cpp.
References LL_ABI_Info_::arg, args, LL_ABI_Info_::fast_math, FAST_MATH_FLAG, flags, i, LL_ABI_Info_::is_fortran, LL_ABI_Info_::is_iso_c, LL_ABI_Info_::is_pure, LL_ABI_ArgInfo_::kind, ll_abi_alloc(), LL_ARG_DIRECT, ll_create_function_type(), ll_proto_add(), ll_proto_init(), llvm_get_current_module(), make_lltype_from_dtype(), malloc(), nargs, sptr, SYMNAME, and LL_ABI_ArgInfo_::type.
Referenced by vmk_prototype().
ll_coercion_type()
LL_Type * ll_coercion_type (LL_Module * module, DTYPE dtype, ISZ_T size, ISZ_T reg_size)
Definition at line 4361 of file llutil.cpp.
References BITS_IN_BYTE, LL_AddrSp_Default, ll_create_anon_struct_type(), ll_create_int_type(), ll_get_array_type(), LL_Type_::module, NULL, and size.
Referenced by classify_common(), ll_abi_classify_arg_dtype(), and ll_abi_classify_return_dtype().
ll_convert_array_dtype()
LL_Type * ll_convert_array_dtype (LL_Module * module, DTYPE dtype, int addrspace)
Convert a Fortran-style TY_ARRAY dtype to an LLVM array.
...
This routine obtains the length information via the array descriptor.
Definition at line 591 of file llutil.cpp.
References AD_DPTR, AD_NUMDIM, AD_NUMELM, LLDEF::addrspace, assert, ddtype(), DTY, DTyCharLength, DTySeqTyElement, ERR_Fatal, ERR_unused, get_bnd_cval(), get_dim_size(), i, interr(), len, ll_convert_dtype(), ll_get_array_type(), NULL, TY_CHAR, TY_NCHAR, and type.
Referenced by convert_dtype().
ll_convert_basic_dtype_with_addrspace()
static LL_Type * ll_convert_basic_dtype_with_addrspace (LL_Module * module, DTYPE dtype, int addrspace) static
Definition at line 273 of file llutil.cpp.
References LLDEF::addrspace, DT_ISCMPLX, DTY, ERR_Fatal, interr(), ll_create_anon_struct_type(), ll_create_basic_type(), LL_DOUBLE, LL_FLOAT, LL_FP128, LL_NOTYPE, LL_VOID, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_FLOAT, TY_QUAD, and type.
Referenced by convert_dtype().
ll_convert_dtype()
LL_Type * ll_convert_dtype (LL_Module * module, DTYPE dtype)
Convert any kind of dtype to an LLVM type.
...
Definition at line 700 of file llutil.cpp.
References convert_dtype().
Referenced by add_external_function_declaration(), layout_struct_body(), ll_abi_classify_arg_dtype(), ll_abi_complete_arg_info(), ll_convert_array_dtype(), ll_convert_iface_sptr(), and update_homogeneous().
ll_convert_dtype_with_addrspace()
LL_Type * ll_convert_dtype_with_addrspace (LL_Module * module, DTYPE dtype, int addrspace)
Convert any kind of dtype to an LLVM type with address space.
Definition at line 709 of file llutil.cpp.
References LLDEF::addrspace, and convert_dtype().
Referenced by convert_dtype(), lltype_from_dtype(), and make_lltype_from_sptr().
ll_convert_iface_sptr()
static LL_Type * ll_convert_iface_sptr (LL_Module * module, SPTR iface_sptr) static
This routine is for use with fortran interfaces, specified by sptr
Definition at line 359 of file llutil.cpp.
References args, assert, ERR_Fatal, find_ag(), get_ag_argdtlist_length(), get_ag_lltype(), get_argdtlist(), get_lltype_from_argdtlist(), get_llvm_ifacenm(), get_llvm_name(), get_next_argdtlist(), i, ll_convert_dtype(), ll_create_function_type(), local_funcptr_sptr_to_gblsym(), and res.
Referenced by make_lltype_from_iface().
ll_convert_struct_dtype()
static LL_Type * ll_convert_struct_dtype (LL_Module * module, DTYPE dtype) static
Definition at line 534 of file llutil.cpp.
References cpu_llvm_module, DTY, DTyAlgTyMember, DTyAlgTySize, DTyAlgTyTag, layout_struct_body(), ll_create_named_struct_type(), ll_get_struct_type(), prefix, process_dtype_struct(), and SYMNAME.
Referenced by convert_dtype(), and process_dtype_struct().
ll_get_string_buf()
static char * ll_get_string_buf (int string_len, char * base, int skip_quotes) static
Definition at line 1411 of file llutil.cpp.
References base, len, llutil_alloc(), and name.
Referenced by make_conststring_op().
ll_instr_flags_from_aop()
LL_InstrListFlags ll_instr_flags_from_aop (ATOMIC_RMW_OP aop)
Compute the LL_InstrListFlag set from an ATOMIC_RMW_OP.
Parameters
aop an ATOMIC_RMW_OP value
Definition at line 4334 of file llutil.cpp.
References AOP_ADD, AOP_AND, AOP_MAX, AOP_MIN, AOP_OR, AOP_SUB, AOP_XCHG, AOP_XOR, assert, ATOMIC_ADD_FLAG, ATOMIC_AND_FLAG, ATOMIC_MAX_FLAG, ATOMIC_MIN_FLAG, ATOMIC_OR_FLAG, ATOMIC_SUB_FLAG, ATOMIC_XCHG_FLAG, ATOMIC_XOR_FLAG, ERR_Fatal, and InstrListFlagsNull.
Referenced by gen_llvm_atomicrmw_expr().
ll_override_type_string()
void ll_override_type_string (LL_Type * llt, const char * str)
...
Definition at line 3974 of file llutil.cpp.
References llutil_alloc(), str, and strlen().
Referenced by generate_struct_dtype(), and process_ftn_dtype_struct().
LLABI_find_array_type_def()
static LLDEF * LLABI_find_array_type_def (DTYPE dtype) static
Scan the list of array types and find the corresponding LLDEF.
dtype The dtype to search for
Returns
null iff the array type is not found
This is an O(n) operation, where n is the number of array types.
Definition at line 4015 of file llutil.cpp.
References llarray_def_list, NULL, and p.
Referenced by llfind_array_type_def().
LLABI_find_su_type_def()
static LLDEF * LLABI_find_su_type_def (DTYPE dtype) static
Scan the list of struct types and find the corresponding LLDEF.
dtype The dtype to search for
Returns
null iff the struct type is not found
This is an O(n) operation, where n is the number of struct types.
Definition at line 3996 of file llutil.cpp.
References NULL, p, and struct_def_list.
Referenced by llfind_su_type_def().
llfind_array_type_def()
LL_Type * llfind_array_type_def (DTYPE dtype)
Definition at line 4033 of file llutil.cpp.
References def, LLABI_find_array_type_def(), and NULL.
llfind_su_type_def()
LL_Type * llfind_su_type_def (DTYPE dtype)
Definition at line 4026 of file llutil.cpp.
References def, LLABI_find_su_type_def(), and NULL.
llis_array_kind()
bool llis_array_kind (DTYPE dtype)
Definition at line 757 of file llutil.cpp.
References DTY, TY_CHAR, and TY_NCHAR.
Referenced by llis_dummied_arg(), and make_lltype_from_sptr().
llis_dummied_arg()
bool llis_dummied_arg (SPTR sptr)
...
Definition at line 771 of file llutil.cpp.
References llis_array_kind(), llis_pointer_kind(), and sptr.
Referenced by process_formal_arguments().
llis_function_kind()
bool llis_function_kind (DTYPE dtype)
Definition at line 803 of file llutil.cpp.
References DTY.
Referenced by make_lltype_from_sptr().
llis_integral_kind()
bool llis_integral_kind (DTYPE dtype)
Definition at line 715 of file llutil.cpp.
References DTY, TY_BINT, TY_BLOG, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by make_lltype_from_sptr().
llis_pointer_kind()
bool llis_pointer_kind (DTYPE dtype)
Definition at line 751 of file llutil.cpp.
References DTY.
Referenced by llis_dummied_arg(), and make_lltype_from_sptr().
llis_struct_kind()
bool llis_struct_kind (DTYPE dtype)
Definition at line 784 of file llutil.cpp.
References DTY, TY_CMPLX, and TY_DCMPLX.
Referenced by make_lltype_from_sptr().
llis_vector_kind()
bool llis_vector_kind (DTYPE dtype)
Definition at line 778 of file llutil.cpp.
References DTY.
Referenced by make_lltype_from_sptr().
LLTYPE_equiv()
static bool LLTYPE_equiv (LL_Type * ty1, LL_Type * ty2) static
Compare two types to make sure something isn't already sideways.
This is for use in sanity assertions. FIXME: i32 and i64 types are conflated in many f90_correct tests.
Definition at line 1854 of file llutil.cpp.
Referenced by write_operand().
lltype_from_dtype()
static LL_Type * lltype_from_dtype (DTYPE dtype, int addrspace) static
Definition at line 880 of file llutil.cpp.
References LLDEF::addrspace, ll_convert_dtype_with_addrspace(), and llvm_get_current_module().
Referenced by make_lltype_from_dtype(), and make_lltype_from_dtype_with_addrspace().
llutil_alloc()
static char * llutil_alloc (INT size) static
Definition at line 163 of file llutil.cpp.
References getitem(), LLVM_LONGTERM_AREA, p, and size.
Referenced by ll_get_string_buf(), ll_override_type_string(), llutil_strdup(), make_arg_op(), make_def(), make_lltype_from_sptr(), make_operand(), make_tmps(), and process_ftn_dtype_struct().
llutil_def_reset()
void llutil_def_reset (void)
...
Definition at line 148 of file llutil.cpp.
References llutil_gblvar_def_reset(), and llutil_struct_def_reset().
llutil_dfile_init()
void llutil_dfile_init (void)
...
Definition at line 155 of file llutil.cpp.
References gbl, and ll_dfile.
llutil_gblvar_def_reset()
void llutil_gblvar_def_reset (void)
...
Definition at line 141 of file llutil.cpp.
References gblvar_def_list, and NULL.
Referenced by llutil_def_reset().
llutil_strdup()
const char * llutil_strdup (const char * str)
...
Definition at line 171 of file llutil.cpp.
References llutil_alloc(), p, str, and strlen().
Referenced by llvm_add_to_init_list().
llutil_struct_def_reset()
void llutil_struct_def_reset (void)
...
Definition at line 134 of file llutil.cpp.
References NULL, and struct_def_list.
Referenced by cg_llvm_fnend(), and llutil_def_reset().
llvm_fc_type()
const char * llvm_fc_type (DTYPE dtype)
return string for a first class type
...
Definition at line 2623 of file llutil.cpp.
References assert, DBGTRACE2, DTY, ERR_Fatal, ISZ_T, size_of(), stb, sz, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, TY_SLOG, TY_WORD, and STB::tynames.
Referenced by gen_constant(), and write_constant_value().
llvm_file()
FILE * llvm_file (void)
...
Definition at line 1787 of file llutil.cpp.
References LLVMFIL.
Referenced by cg_llvm_end(), and schedule().
llvm_get_current_module()
LL_Module * llvm_get_current_module (void)
Definition at line 125 of file llutil.cpp.
References cpu_llvm_module.
Referenced by get_ftn_func_lltype(), init_output_file(), ll_add_func_proto(), lltype_from_dtype(), make_int_lltype(), make_lltype_from_iface(), make_lltype_from_sptr(), make_void_lltype(), metadata_args_need_struct(), process_dtype_struct(), process_ll_abi_func_ftn(), and process_symlinked_sptr().
llvm_set_acc_module()
void llvm_set_acc_module (void)
set the module as gpu/cpu module
Definition at line 113 of file llutil.cpp.
References is_gpu_module.
llvm_set_cpu_module()
void llvm_set_cpu_module (void)
Definition at line 119 of file llutil.cpp.
References is_gpu_module.
make_arg_op()
static INLINE OPERAND * make_arg_op (SPTR sptr) static
Definition at line 1531 of file llutil.cpp.
References get_llvm_name(), OPERAND::ll_type, llutil_alloc(), make_lltype_from_sptr(), make_operand(), OPERAND::ot_type, OT_VAR, process_sptr(), size, sptr, OPERAND::sptr, OPERAND::string, strlen(), and OPERAND::val.
Referenced by write_operand().
make_array_lltype()
LL_Type * make_array_lltype (int size, LL_Type * pts_to)
...
Definition at line 862 of file llutil.cpp.
References LL_AddrSp_Default, ll_get_array_type(), and size.
Referenced by assign_array_lltype(), get_ftn_cbind_lltype(), get_local_overlap_size(), and write_final_table().
make_constsptr_op()
OPERAND * make_constsptr_op (SPTR sptr)
...
Definition at line 1397 of file llutil.cpp.
References assert, ERR_Fatal, OPERAND::ll_type, make_lltype_from_dtype(), make_operand(), OT_CONSTSPTR, OPERAND::ot_type, sptr, OPERAND::sptr, and OPERAND::val.
Referenced by gen_switch(), and make_param_op().
make_conststring_op()
static OPERAND * make_conststring_op (int sptr) static
Definition at line 1428 of file llutil.cpp.
References assert, DTY, ERR_Fatal, length(), ll_get_string_buf(), OPERAND::ll_type, ll_type_bytes(), make_lltype_from_dtype(), make_operand(), STB::n_base, NULL, OT_CONSTSTRING, OPERAND::ot_type, sptr, stb, OPERAND::string, and TY_CHAR.
Referenced by make_param_op().
make_constval32_op()
OPERAND * make_constval32_op (int idx)
...
Definition at line 1475 of file llutil.cpp.
References DT_INT, idx, make_constval_op(), and make_lltype_from_dtype().
Referenced by gen_extract_value_ll(), gen_extract_vector(), gen_gep_index(), gen_insert_value(), gen_insert_vector(), gen_llvm_cmpxchg_component(), gen_switch(), insert_llvm_memcpy(), and insert_llvm_memset().
make_constval_op()
OPERAND * make_constval_op (LL_Type * ll_type, INT conval0, INT conval1)
...
Definition at line 1444 of file llutil.cpp.
References OPERAND::conval, LLDEF::ll_type, OPERAND::ll_type, make_operand(), OT_CONSTVAL, OPERAND::ot_type, and OPERAND::val.
Referenced by gen_acon_expr(), gen_base_addr_operand(), gen_llvm_expr(), gen_mulh_expr(), gen_va_arg(), insert_llvm_dbg_value(), insert_llvm_memcpy(), insert_llvm_memset(), insert_llvm_prefetch(), make_constval32_op(), and make_param_op().
make_constval_opL()
OPERAND * make_constval_opL (LL_Type * ll_type, INT conval0, INT conval1, INT conval2, INT conval3)
...
Definition at line 1458 of file llutil.cpp.
References OPERAND::conval, LLDEF::ll_type, OPERAND::ll_type, make_operand(), OT_CONSTVAL, OPERAND::ot_type, and OPERAND::val.
Referenced by gen_llvm_expr().
make_def()
static LLDEF * make_def (DTYPE dtype, int sptr, int rank, const char * name, int flags) static
Definition at line 2745 of file llutil.cpp.
References LLDEF::addrspace, LLDEF::dtype, flags, LLDEF::flags, LLDEF::ll_type, llutil_alloc(), name, LLDEF::name, LLDEF::next, NULL, LLDEF::printed, rank, LLDEF::rank, sptr, LLDEF::sptr, and LLDEF::values.
Referenced by process_dtype_struct(), and process_ftn_dtype_struct().
make_def_op()
OPERAND * make_def_op (char * str)
...
Definition at line 1552 of file llutil.cpp.
References make_operand(), OT_DEF, OPERAND::ot_type, str, and OPERAND::string.
make_generic_dummy_lltype()
LL_Type * make_generic_dummy_lltype (void)
...
Definition at line 910 of file llutil.cpp.
References generic_dummy_dtype(), make_lltype_from_dtype(), and make_ptr_lltype().
Referenced by get_ftn_dummy_lltype(), ll_process_routine_parameters(), make_lltype_from_sptr(), print_entry_subroutine(), and process_formal_arguments().
make_int_lltype()
LL_Type * make_int_lltype (unsigned bits)
...
Definition at line 844 of file llutil.cpp.
References bits, ll_create_int_type(), and llvm_get_current_module().
Referenced by attempt_gep_folding(), gen_abs_expr(), gen_acon_expr(), gen_base_addr_operand(), gen_binary_expr(), gen_llvm_expr(), gen_minmax_expr(), gen_mulh_expr(), gen_optext_comp_operand(), gen_select_expr(), gen_switch(), gen_va_arg(), gen_vect_compare_operand(), insert_jump_entry_instr(), insert_llvm_memcpy(), insert_llvm_memset(), insert_llvm_prefetch(), make_stmt(), sign_extend_int(), and zero_extend_int().
make_label_op()
OPERAND * make_label_op (SPTR sptr)
...
Definition at line 1662 of file llutil.cpp.
References get_label_name(), make_operand(), OT_LABEL, OPERAND::ot_type, process_sptr(), sptr, OPERAND::sptr, OPERAND::string, and OPERAND::val.
Referenced by gen_call_expr(), insert_entry_label(), insert_jump_entry_instr(), make_stmt(), and schedule().
make_lltype_from_abi_arg()
LL_Type * make_lltype_from_abi_arg (LL_ABI_ArgInfo * arg)
...
Definition at line 3935 of file llutil.cpp.
References arg.
Referenced by analyze_ret_info(), gen_arg_operand(), gen_call_expr(), ll_process_routine_parameters(), print_entry_subroutine(), and process_formal_arguments().
make_lltype_from_arg()
LL_Type * make_lltype_from_arg (int arg)
...
Definition at line 926 of file llutil.cpp.
References assert, and ERR_Fatal.
make_lltype_from_arg_noproto()
LL_Type * make_lltype_from_arg_noproto (int arg)
...
Definition at line 937 of file llutil.cpp.
References arg, DBGTRACEOUT2, DTY, IL_RES, ILI_DTyOPND, ILI_OPC, ILI_OPND, ILIA_AR, make_lltype_from_dtype(), make_ptr_lltype(), and LL_Type_::str.
make_lltype_from_dtype()
LL_Type * make_lltype_from_dtype (DTYPE dtype)
...
Definition at line 889 of file llutil.cpp.
References lltype_from_dtype().
Referenced by add_def(), addDebugForGlobalVar(), analyze_ret_info(), assign_array_lltype(), char_type(), cleanup_unneeded_sincos_calls(), complex_result_type(), DeclareSPtrAsLocal(), fixup_x86_abi_return(), gen_acon_expr(), gen_address_operand(), gen_alloca_call_if_necessary(), gen_arg_operand(), gen_base_addr_operand(), gen_binary_expr(), gen_bitcast_vector(), gen_call_vminmax_intrinsic(), gen_call_vminmax_neon_intrinsic(), gen_call_vminmax_power_intrinsic(), gen_cmplx_math(), gen_cmplx_mul(), gen_const_expr(), gen_convert_vector(), gen_eval_cmplx_value(), gen_extract_insert(), gen_extract_value(), gen_llvm_atomic_intrinsic_for_builtin(), gen_llvm_expr(), gen_llvm_sincos_call(), gen_llvm_vsincos_call(), gen_minmax_expr(), gen_optext_comp_operand(), gen_ref_arg(), gen_return_operand(), gen_sret_expr(), gen_unary_expr(), gen_va_arg(), gen_va_end(), gen_va_start(), gen_vect_compare_operand(), generate_struct_dtype(), get_ftn_cbind_lltype(), get_ftn_cmblk_lltype(), get_ftn_dummy_lltype(), get_ftn_extern_lltype(), get_ftn_func_lltype(), get_ftn_hollerith_type(), get_ftn_static_lltype(), get_ftn_typedesc_lltype(), get_local_overlap_size(), insert_entry_label(), insert_jump_entry_instr(), ll_add_func_proto(), ll_process_routine_parameters(), lldbg_function_end(), make_constsptr_op(), make_conststring_op(), make_constval32_op(), make_gblsym(), make_generic_dummy_lltype(), make_lltype_from_arg_noproto(), make_lltype_from_sptr(), make_lltype_sz4v3_from_dtype(), make_load(), make_member_op(), make_param_op(), make_stmt(), make_type_from_opc(), make_uplevel_arg_struct(), make_vtype(), maybe_do_gep_folding(), maybe_generate_fma(), print_entry_subroutine(), print_function_signature(), process_extern_function_sptr(), process_params(), process_sptr_offset(), schedule(), write_constant_value(), write_def(), write_extern_inits(), write_final_table(), write_I_CALL(), write_instructions(), write_module_as_subroutine(), write_operand(), and write_typedescs().
make_lltype_from_dtype_with_addrspace()
LL_Type * make_lltype_from_dtype_with_addrspace (DTYPE dtype, int addrspace)
...
Definition at line 895 of file llutil.cpp.
References LLDEF::addrspace, and lltype_from_dtype().
Referenced by make_lltype_from_sptr(), and make_type_from_msz_with_addrspace().
make_lltype_from_iface()
LL_Type * make_lltype_from_iface (SPTR sptr)
...
Definition at line 1188 of file llutil.cpp.
References ll_convert_iface_sptr(), llvm_get_current_module(), and sptr.
Referenced by get_ftn_func_lltype(), and make_lltype_from_sptr().
make_lltype_from_sptr()
LL_Type * make_lltype_from_sptr (SPTR sptr)
Make an LL_Type from symbol sptr.
...
Parameters
sptr a symbol
Definition at line 1219 of file llutil.cpp.
References AD_DPTR, AD_NUMELM, ad_val_of(), add_def(), LLDEF::addrspace, assert, CUDA_DEVICE, CUDA_GLOBAL, CUDAG, d, LL_Type_::data_type, DBGDUMPLLTYPE, DBGTRACE1, DBGTRACEIN7, DBGTRACEOUT1, DDTG, def, DT_CPTR, DTY, DTySeqTyElement, ERR_Fatal, gbl, get_ftn_cbind_lltype(), get_ftn_cmblk_lltype(), get_ftn_dummy_lltype(), get_ftn_hollerith_type(), get_ftn_static_lltype(), get_ftn_typedesc_lltype(), get_iface_sptr(), get_local_overlap_vartype(), STB::i1, IS_FTN_PROC_PTR, is_function(), STB::k1, ll_abi_for_func_sptr(), ll_abi_function_type(), LL_AddrSp_Default, LL_AddrSp_NVVM_Generic, LL_AddrSp_NVVM_Shared, LL_ARRAY, ll_convert_dtype_with_addrspace(), ll_create_basic_type(), ll_create_int_type(), ll_get_array_type(), ll_get_pointer_type(), LL_LABEL, LL_PTR, LL_VOID, llarray_def_list, llis_array_kind(), llis_function_kind(), llis_integral_kind(), llis_pointer_kind(), llis_struct_kind(), llis_vector_kind(), llutil_alloc(), llvm_get_current_module(), make_generic_dummy_lltype(), make_lltype_from_dtype(), make_lltype_from_dtype_with_addrspace(), make_lltype_from_iface(), make_ptr_lltype(), need_ptr(), process_dtype_struct(), sptr, stb, STB::stypes, LL_Type_::sub_types, SYMNAME, TY_CHAR, TY_NCHAR, STB::tynames, XBIT, and ZSIZEOF.
Referenced by add_global_define(), addDebugForGlobalVar(), char_type(), gen_address_operand(), gen_const_expr(), get_struct_from_dsrt2(), ll_write_local_objects(), lldbg_emit_type(), make_arg_op(), make_gblsym(), make_lltype_sz4v3_from_sptr(), and make_var_op().
make_lltype_sz4v3_from_dtype()
LL_Type * make_lltype_sz4v3_from_dtype (DTYPE dtype)
...
Definition at line 1509 of file llutil.cpp.
References make_lltype_from_dtype(), and set_vect3_to_size4().
Referenced by make_stmt().
make_lltype_sz4v3_from_sptr()
LL_Type * make_lltype_sz4v3_from_sptr (SPTR sptr)
...
Definition at line 1502 of file llutil.cpp.
References make_lltype_from_sptr(), set_vect3_to_size4(), and sptr.
Referenced by process_blockaddr_sptr(), and process_sptr_offset().
make_mdref_op()
OPERAND * make_mdref_op (LL_MDRef mdref)
...
Definition at line 1618 of file llutil.cpp.
References assert, ERR_Fatal, TMP_TAG::id, LL_MDREF_kind, LL_MDREF_value, make_operand(), make_tmps(), MDRef_Node, OT_MDNODE, OPERAND::ot_type, and OPERAND::tmps.
Referenced by cons_expression_metadata_operand(), insert_llvm_dbg_declare(), insert_llvm_dbg_value(), and lldbg_create_deferred_len_string_type_mdnode().
make_member_op()
static INLINE OPERAND * make_member_op (int address, DTYPE dtype) static
Definition at line 1574 of file llutil.cpp.
References make_lltype_from_dtype(), and make_member_op_with_lltype().
Referenced by process_symlinked_sptr().
make_member_op_with_lltype()
static OPERAND * make_member_op_with_lltype (int address, LL_Type * llTy) static
Definition at line 1564 of file llutil.cpp.
References OPERAND::ll_type, make_operand(), OPERAND::next, NULL, OT_MEMBER, and OPERAND::ot_type.
Referenced by make_member_op(), and process_symlinked_sptr().
make_metadata_wrapper_op()
OPERAND * make_metadata_wrapper_op (SPTR sptr, LL_Type * llTy)
Create metadata operand that wraps an LLVM value.
For example, metadata !{i32 x}. Used by llvm.dbg.declare intrinsic.
Definition at line 1633 of file llutil.cpp.
References OPERAND::ll_type, make_operand(), OT_MDNODE, OPERAND::ot_type, process_sptr(), sptr, OPERAND::sptr, and OPERAND::val.
Referenced by insert_llvm_dbg_declare().
make_null_op()
OPERAND * make_null_op (LL_Type * llt)
...
Definition at line 1603 of file llutil.cpp.
References assert, LL_Type_::data_type, ERR_Fatal, OPERAND::flags, LL_PTR, OPERAND::ll_type, make_operand(), OPF_NULL_TYPE, OT_CONSTVAL, and OPERAND::ot_type.
Referenced by gen_const_expr().
make_operand()
OPERAND * make_operand (void)
...
Definition at line 1677 of file llutil.cpp.
References llutil_alloc().
Referenced by gen_abs_expr(), gen_call_expr(), gen_const_expr(), gen_copy_op(), gen_extract_insert(), gen_imask(), gen_llvm_expr(), gen_minmax_expr(), gen_optext_comp_operand(), gen_resized_vect(), gen_return_operand(), gen_sptr(), gen_sret_expr(), gen_va_end(), gen_va_start(), gen_vect_compare_operand(), get_intrinsic(), insert_jump_entry_instr(), insert_llvm_dbg_declare(), insert_llvm_dbg_value(), insert_llvm_memcpy(), insert_llvm_memset(), insert_llvm_prefetch(), lldbg_emit_type(), make_arg_op(), make_constsptr_op(), make_conststring_op(), make_constval_op(), make_constval_opL(), make_def_op(), make_label_op(), make_mdref_op(), make_member_op_with_lltype(), make_metadata_wrapper_op(), make_null_op(), make_target_op(), make_tmp_op(), make_undef_op(), make_var_op(), process_formal_arguments(), and process_params().
make_param_op()
OPERAND * make_param_op (SPTR sptr)
Definition at line 2194 of file llutil.cpp.
References CONVAL2G, DTY, make_constsptr_op(), make_conststring_op(), make_constval_op(), make_lltype_from_dtype(), sptr, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, and TY_SLOG.
Referenced by write_operand().
make_ptr_lltype()
LL_Type * make_ptr_lltype (LL_Type * pts_to)
...
Definition at line 838 of file llutil.cpp.
References ll_get_pointer_type().
Referenced by gen_acon_expr(), gen_address_operand(), gen_arg_operand(), gen_base_addr_operand(), gen_call_expr(), gen_llvm_atomicrmw_expr(), gen_llvm_cmpxchg(), gen_llvm_expr(), gen_ref_arg(), gen_return_operand(), gen_va_arg(), get_ftn_dummy_lltype(), get_ftn_static_lltype(), get_intrinsic(), make_generic_dummy_lltype(), make_lltype_from_arg_noproto(), make_lltype_from_sptr(), make_stmt(), print_entry_subroutine(), process_extern_function_sptr(), process_sptr_offset(), store_return_value_for_entry(), write_final_table(), and write_operand().
make_target_op()
OPERAND * make_target_op (SPTR sptr)
...
Definition at line 1647 of file llutil.cpp.
References get_label_name(), make_operand(), OT_TARGET, OPERAND::ot_type, process_sptr(), sptr, OPERAND::sptr, OPERAND::string, and OPERAND::val.
Referenced by gen_switch(), insert_jump_entry_instr(), and make_stmt().
make_tmp_op()
OPERAND * make_tmp_op (LL_Type * llt, TMPS * tmps)
...
Definition at line 1580 of file llutil.cpp.
References OPERAND::ll_type, make_operand(), OT_TMP, OPERAND::ot_type, and OPERAND::tmps.
Referenced by ad_csed_instr(), convert_float_size(), convert_operand(), find_load_cse(), fused_multiply_add_canonical_form(), gen_abs_expr(), gen_call_expr(), gen_call_to_builtin(), gen_extract_insert(), gen_extract_value_ll(), gen_extract_vector(), gen_insert_vector(), gen_llvm_expr(), gen_llvm_instr(), gen_minmax_expr(), gen_resized_vect(), gen_scalar_to_vector_helper(), gen_select_expr(), insert_jump_entry_instr(), make_bitcast(), make_load(), make_stmt(), mk_alloca_instr(), and set_csed_operand().
make_tmps()
TMPS * make_tmps (void)
allocate a new TMPS structure
...
Definition at line 181 of file llutil.cpp.
References llutil_alloc().
Referenced by ad_csed_instr(), convert_float_size(), convert_int_size(), convert_operand(), fused_multiply_add_canonical_form(), gen_abs_expr(), gen_call_expr(), gen_call_to_builtin(), gen_extract_insert(), gen_extract_value_ll(), gen_extract_vector(), gen_insert_vector(), gen_llvm_expr(), gen_llvm_instr(), gen_minmax_expr(), gen_optext_comp_operand(), gen_resized_vect(), gen_scalar_to_vector_helper(), gen_select_expr(), gen_vect_compare_operand(), insert_jump_entry_instr(), make_bitcast(), make_load(), make_mdref_op(), make_stmt(), mk_alloca_instr(), print_entry_subroutine(), and store_return_value_for_entry().
make_undef_op()
OPERAND * make_undef_op (LL_Type * llt)
...
Definition at line 1592 of file llutil.cpp.
References OPERAND::ll_type, make_operand(), OPERAND::ot_type, and OT_UNDEF.
Referenced by fixup_recip_div(), gen_cmplx_math(), gen_cmplx_mul(), gen_extract_insert(), gen_llvm_expr(), gen_return_operand(), gen_scalar_to_vector_helper(), gen_scalar_to_vector_no_shuffle(), gen_unreachable_if_necessary(), and x86_promote_to_vector().
make_var_op()
OPERAND * make_var_op (SPTR sptr)
...
Definition at line 1516 of file llutil.cpp.
References OPERAND::ll_type, make_lltype_from_sptr(), make_operand(), OPERAND::ot_type, OT_VAR, process_sptr(), set_llvm_sptr_name(), sptr, OPERAND::sptr, and OPERAND::val.
Referenced by gen_arg_operand(), gen_call_expr(), gen_llvm_expr(), gen_va_arg(), insert_jump_entry_instr(), process_formal_arguments(), and write_operand().
make_vector_lltype()
LL_Type * make_vector_lltype (int size, LL_Type * pts_to)
...
Definition at line 856 of file llutil.cpp.
References ll_get_vector_type(), and size.
Referenced by gen_optext_comp_operand().
make_void_lltype()
LL_Type * make_void_lltype (void)
...
Definition at line 850 of file llutil.cpp.
References LL_AddrSp_Default, ll_create_basic_type(), LL_VOID, and llvm_get_current_module().
Referenced by analyze_ret_info(), gen_call_expr(), gen_llvm_expr(), gen_unreachable_if_necessary(), gen_va_end(), gen_va_start(), insert_llvm_dbg_declare(), insert_llvm_dbg_value(), insert_llvm_memcpy(), insert_llvm_memset(), and insert_llvm_prefetch().
metadata_args_need_struct()
static INLINE bool metadata_args_need_struct (void) static
Definition at line 2137 of file llutil.cpp.
References ll_feature_metadata_args_struct, and llvm_get_current_module().
Referenced by write_operand().
print_dbg_line()
void print_dbg_line (LL_MDRef md)
Definition at line 1841 of file llutil.cpp.
References print_dbg_line_no_comma(), and print_token().
Referenced by assemble_end(), emit_dbg_from_module(), write_I_CALL(), and write_instructions().
print_dbg_line_no_comma()
void print_dbg_line_no_comma (LL_MDRef md)
Emit line info debug information.
Output the string " !dbg !<i>n</i>", where n is a metadata ref.
Definition at line 1833 of file llutil.cpp.
References buf, LL_MDREF_value, and print_token().
Referenced by build_routine_and_parameter_entries(), and print_dbg_line().
print_line()
void print_line (const char * ln)
Write any line which does not need a tab.
...
Definition at line 1766 of file llutil.cpp.
References LLVMFIL, and NULL.
Referenced by assemble_end(), build_routine_and_parameter_entries(), finish_routine(), write_global_and_static_defines(), and write_module_as_subroutine().
print_line_tobuf()
void print_line_tobuf (char * ln, char * buf)
Print any line which does not need a tab.
...
Definition at line 1778 of file llutil.cpp.
References buf, and NULL.
print_llsize()
void print_llsize (LL_Type * llt)
Write size of LL_Type to llvm file.
...
Definition at line 1727 of file llutil.cpp.
References assert, BIGIPFSZ, ERR_Fatal, ll_type_bytes(), and LLVMFIL.
print_llsize_tobuf()
void print_llsize_tobuf (LL_Type * llt, char * buf)
...
Definition at line 1734 of file llutil.cpp.
References assert, BIGIPFSZ, buf, ERR_Fatal, and ll_type_bytes().
print_metadata_name()
void print_metadata_name (TMPS * t)
Print metadata name.
...
Definition at line 2515 of file llutil.cpp.
References DBGTRACEIN1, DBGTRACEOUT, metadata_id, print_token(), t, and tmp.
Referenced by write_operand().
print_nl()
void print_nl (void)
Write a new line in the output llvm file.
...
Definition at line 1816 of file llutil.cpp.
References LLVMFIL.
Referenced by DeclareSPtrAsLocal(), llvm_write_ctor_dtor_list(), print_entry_subroutine(), write_def(), write_defs(), write_extern_fndecl(), write_external_function_declarations(), write_instructions(), and write_module_as_subroutine().
print_nl_tobuf()
void print_nl_tobuf (char * buf)
...
Definition at line 1822 of file llutil.cpp.
References buf.
print_space()
void print_space (int num)
Write num spaces to llvm file num The number of spaces to write.
...
Definition at line 1745 of file llutil.cpp.
References i, LLVMFIL, and num.
Referenced by print_entry_subroutine(), print_function_signature(), store_return_value_for_entry(), write_I_CALL(), write_instructions(), write_memory_order(), write_module_as_subroutine(), and write_operand().
print_space_tobuf()
void print_space_tobuf (int num, char * buf)
...
Definition at line 1754 of file llutil.cpp.
References buf, i, and num.
print_token()
void print_token (const char * tk)
Write a token at the current location with no nl.
...
Definition at line 1796 of file llutil.cpp.
References assert, ERR_Fatal, and LLVMFIL.
Referenced by add_property_struct(), build_routine_and_parameter_entries(), DeclareSPtrAsLocal(), llvm_write_ctor_dtor_list(), print_arg_attributes(), print_dbg_line(), print_dbg_line_no_comma(), print_entry_subroutine(), print_function_signature(), print_metadata_name(), print_personality(), print_tmp_name(), store_return_value_for_entry(), write_alt_field_types(), write_def(), write_def_values(), write_extern_fndecl(), write_function_attributes(), write_I_CALL(), write_instructions(), write_llaccgroup_metadata(), write_local_overlap(), write_memory_order(), write_memory_order_and_alignment(), write_module_as_subroutine(), write_operand(), write_target_features(), write_tbaa_metadata(), write_type(), write_vconstant_value(), write_verbose_type(), and write_vscale_range().
print_token_tobuf()
void print_token_tobuf (char * tk, char * buf)
print a token at the current location with no nl
...
Definition at line 1806 of file llutil.cpp.
References assert, buf, and ERR_Fatal.
process_dtype_struct()
const char * process_dtype_struct (DTYPE dtype)
...
Definition at line 3235 of file llutil.cpp.
References add_def(), DBGTRACEIN1, DBGTRACEOUT1, def, DTY, DTyAlgTyAlign, DTyAlgTyMember, DTyAlgTyTag, DTyArgNext, get_def(), is_empty_typedef(), ll_convert_struct_dtype(), LLDEF_IS_EMPTY, LLDEF_IS_STRUCT, LLDEF_IS_TYPE, LLDEF_IS_UNPACKED_STRUCT, llvm_get_current_module(), make_def(), NULL, process_symlinked_sptr(), LL_Type_::str, struct_def_list, and ZSIZEOF.
Referenced by dtype_struct_name(), get_ftn_cbind_lltype(), ll_convert_struct_dtype(), lldbg_function_end(), make_lltype_from_sptr(), and write_ftn_typedefs().
process_ftn_dtype_struct()
const char * process_ftn_dtype_struct (DTYPE dtype, char * tname, bool printed)
Make a fake struct for static/common block.
...
This differs from process_dtype_struct and that it overrides the unique name generated by ll_convert_struct_dtype().
The printed flag tells write_ftn_typedefs that this type has already been printed out to the .ll output file. If true, write_ftn_typedefs() will not print the type out (assuming that it has already been 'printed').
Definition at line 3292 of file llutil.cpp.
References add_def(), DBGTRACEIN1, DBGTRACEOUT1, def, DTY, DTyAlgTyAlign, DTyAlgTyMember, DTyAlgTyTag, get_def(), ll_override_type_string(), LLDEF_IS_EMPTY, LLDEF_IS_STRUCT, LLDEF_IS_TYPE, llutil_alloc(), make_def(), NULL, process_symlinked_sptr(), strlen(), struct_def_list, tname, and ZSIZEOF.
Referenced by mk_struct_for_llvm_init().
process_ll_abi_func_ftn()
LL_ABI_Info * process_ll_abi_func_ftn (SPTR func_sptr, bool use_sptrs)
Wrapper to process_ll_abi_func_ftn_mod() passing the default module.
...
Definition at line 3849 of file llutil.cpp.
References llvm_get_current_module(), and process_ll_abi_func_ftn_mod().
Referenced by ll_process_routine_parameters(), print_entry_subroutine(), and write_master_entry_routine().
process_ll_abi_func_ftn_mod()
LL_ABI_Info * process_ll_abi_func_ftn_mod (LL_Module * mod, SPTR func_sptr, bool update)
Process the return type and arguments for func_sptr.
...
Parameters
mod
func_sptr
update flag for special handling
If the update flag is true, then the ABI is reconstructed from the AG table, taking into account any changes added to the AG table. Update also will set the sptrs which means that this routine should only be called with true when the sptrs are valid: (i.e., if this routine exists in the current module).
TODO: Rename this function since process_sptr is not called in here.
Definition at line 3712 of file llutil.cpp.
References LL_ABI_Info_::arg, assert, LL_ABI_Info_::call_as_varargs, CMPLXFUNC_C, DTY, ERR_Fatal, LL_ABI_Info_::extend_abi_return, find_ag(), LL_ABI_ArgInfo_::ftn_pass_by_val, gbl, get_ag_argdtlist_length(), get_ag_return_lltype(), get_argdtlist(), get_byval_from_argdtlist(), get_lltype_from_argdtlist(), get_llvm_funcptr_ag(), get_llvm_ifacenm(), get_llvm_name(), get_master_sptr(), get_next_argdtlist(), get_return_type(), get_sptr_from_argdtlist(), i, LL_ABI_Info_::is_fortran, IS_FTN_PROC_PTR, LL_ABI_Info_::is_iso_c, is_iso_cptr(), LL_ABI_ArgInfo_::kind, ll_abi_alloc(), ll_abi_classify_arg_dtype(), ll_abi_classify_return_dtype(), ll_abi_complete_arg_info(), ll_abi_compute_call_conv(), ll_abi_free(), LL_ARG_DIRECT, LL_ARG_INDIRECT, LL_ARG_SIGNEXT, ll_proto_get_abi(), ll_proto_key(), ll_proto_set_abi(), LL_ABI_Info_::missing_prototype, nargs, sptr, LL_ABI_ArgInfo_::sptr, TY_CHAR, TY_ISCMPLX, TY_NCHAR, TY_SINT, TY_SLOG, LL_ABI_ArgInfo_::type, and XBIT.
Referenced by ll_abi_for_func_sptr(), process_ll_abi_func_ftn(), and schedule().
process_symlinked_sptr()
OPERAND * process_symlinked_sptr (int sptr, int total_init_sz, int is_union, int max_field_sz)
...
Definition at line 3159 of file llutil.cpp.
References DDTG, get_int_dtype_from_size(), i8, ll_create_int_type(), ll_get_array_type(), llvm_get_current_module(), make_member_op(), make_member_op_with_lltype(), OPERAND::next, NOSYM, NULL, sptr, and ZSIZEOF.
Referenced by process_dtype_struct(), and process_ftn_dtype_struct().
set_llasm_output_file()
static void set_llasm_output_file (FILE * fd) static
Definition at line 1684 of file llutil.cpp.
References fd, and LLVMFIL.
Referenced by init_output_file().
set_metadata_string()
void set_metadata_string (TMPS * t, char * string)
Set name for named metadata.
...
Definition at line 2487 of file llutil.cpp.
References DBGTRACEIN2, DBGTRACEOUT, and t.
set_vect3_to_size4()
static LL_Type * set_vect3_to_size4 (LL_Type * ll_type) static
Definition at line 1481 of file llutil.cpp.
References LL_Type_::addrspace, LL_Type_::data_type, LL_ARRAY, ll_get_array_type(), ll_get_pointer_type(), ll_get_vector_type(), LL_PTR, LLDEF::ll_type, LL_VECTOR, set_vect3_to_size4(), LL_Type_::sub_elements, and LL_Type_::sub_types.
Referenced by make_lltype_sz4v3_from_dtype(), make_lltype_sz4v3_from_sptr(), and set_vect3_to_size4().
should_preserve_param()
bool should_preserve_param (const DTYPE dtype)
return whether param debug info should be preserved
This function returns true for the types supported in function make_param_op
Definition at line 2147 of file llutil.cpp.
References AD_DPTR, AD_NUMELM, ad_val_of(), assert, DTY, ERR_Fatal, ISZ_T, size, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by process_params().
small_aggr_return()
bool small_aggr_return (DTYPE dtype)
...
Definition at line 2551 of file llutil.cpp.
Referenced by get_return_dtype().
struct_typedef_name()
int struct_typedef_name (DTYPE dtype)
Definition at line 3110 of file llutil.cpp.
References STB::firstusym, sptr, and stb.
visit_flattened_dtype()
int visit_flattened_dtype (dtype_visitor visitor, void * context, DTYPE dtype, unsigned address, unsigned member_sptr)
...
Definition at line 3941 of file llutil.cpp.
References assert, DTY, DTyAlgTyMember, ERR_Fatal, NOSYM, sptr, and visit_flattened_dtype().
Referenced by amd64_classify(), check_vector_registers(), check_vfp(), and visit_flattened_dtype().
write_alt_field_types()
static void write_alt_field_types (LL_Type * llty) static
Definition at line 2934 of file llutil.cpp.
References i, print_token(), LL_Type_::str, LL_Type_::sub_elements, and LL_Type_::sub_types.
Referenced by write_def().
write_constant_value()
void write_constant_value (int sptr, LL_Type * type, INT conval0, INT conval1, bool uns)
Write a constant value to the output llvm file.
...
Definition at line 1911 of file llutil.cpp.
References assert, b, CONVAL2G, cprintf(), d, DT_FLOAT, DT_ISCMPLX, DTY, ERR_Fatal, len, LL_ARRAY, LL_DOUBLE, LL_FLOAT, LL_FP128, LL_I1, LL_I128, LL_I16, LL_I24, LL_I256, LL_I32, LL_I40, LL_I48, LL_I56, LL_I64, LL_I8, LL_PPC_FP128, LL_PTR, LL_STRUCT, ll_type_bytes(), LL_VECTOR, LL_X86_FP80, llvm_fc_type(), LLVMFIL, make_lltype_from_dtype(), STB::n_base, num, p, sptr, stb, tmp, TY_CHAR, TY_CMPLX, TY_NCHAR, type, ui64toax(), write_constant_value(), write_vconstant_value(), xx_u::ww, xdble(), and xdtomd().
Referenced by write_constant_value(), write_consts(), write_operand(), and write_vconstant_value().
write_def()
static void write_def (LLDEF * def, int check_type_in_struct_def_type) static
Definition at line 2949 of file llutil.cpp.
References buf, def, get_def(), LLDEF_IS_ACCSTRING, LLDEF_IS_CONST, LLDEF_IS_EMPTY, LLDEF_IS_EXTERNAL, LLDEF_IS_INITIALIZED, LLDEF_IS_STATIC, LLDEF_IS_TYPE, LLDEF_IS_UNPACKED_STRUCT, make_lltype_from_dtype(), LLDEF::name, NULL, print_nl(), print_token(), struct_def_list, write_alt_field_types(), write_def_values(), and write_type().
Referenced by write_defs(), and write_ftn_typedefs().
write_def_values()
static OPERAND * write_def_values (OPERAND * def_op, LL_Type * type) static
Definition at line 2821 of file llutil.cpp.
References assert, OPERAND::conval, LL_Type_::data_type, ERR_Fatal, FLG_OMIT_OP_TYPE, i, interr(), LL_ARRAY, LL_DOUBLE, LL_FLOAT, LL_FP128, LL_HALF, LL_I1, LL_I128, LL_I16, LL_I24, LL_I256, LL_I32, LL_I40, LL_I48, LL_I56, LL_I64, LL_I8, LL_PPC_FP128, LL_PTR, LL_STRUCT, OPERAND::ll_type, LL_TYPE_IS_PACKED_STRUCT, LL_VECTOR, LL_X86_FP80, OPERAND::next, NULL, OT_CONSTSTRING, OT_CONSTVAL, OPERAND::ot_type, print_token(), type, OPERAND::val, write_def_values(), and write_operand().
Referenced by write_def(), and write_def_values().
write_defs()
static void write_defs (LLDEF * def_list, int check_type_in_struct_def_type) static
Definition at line 3021 of file llutil.cpp.
References LLDEF::next, print_nl(), LLDEF::printed, and write_def().
Referenced by write_struct_defs().
write_ftn_typedefs()
void write_ftn_typedefs (void)
...
Definition at line 3072 of file llutil.cpp.
References LLDEF::dtype, get_typedef_ag(), LLDEF::name, LLDEF::next, LLDEF::printed, process_dtype_struct(), struct_def_list, and write_def().
Referenced by cg_llvm_fnend(), cg_llvm_init(), and schedule().
write_operand()
void write_operand (OPERAND * p, const char * punc_string, int flags)
Write a single operand.
...
Definition at line 2242 of file llutil.cpp.
References assert, LL_Type_::data_type, DBGDUMPLLTYPE, DBGTRACE1, DBGTRACEIN2, DBGTRACEOUT, ERR_Fatal, flags, OPERAND::flags, FLG_AS_UNSIGNED, FLG_FIXUP_RETURN_TYPE, FLG_OMIT_OP_TYPE, getcon(), i, LL_FP128, LL_FUNCTION, ll_get_pointer_type(), LL_I16, LL_PTR, OPERAND::ll_type, ll_type_int_bits(), ll_type_is_fp(), LL_VECTOR, LLTYPE_equiv(), llvm_cc_names, llvm_ccfp_names, make_arg_op(), make_lltype_from_dtype(), make_param_op(), make_ptr_lltype(), make_var_op(), maybe_fixup_x86_abi_return(), metadata_args_need_struct(), NULL, OPF_CONTAINS_UNDEF, OPF_HIDDEN, OPF_NULL_TYPE, OPF_SRARG_TYPE, OPF_SRET_TYPE, OPF_WRAPPED_MD, OT_CALL, OT_CC, OT_CONSTSPTR, OT_CONSTSTRING, OT_CONSTVAL, OT_DEF, OT_LABEL, OT_MDNODE, OT_MEMBER, ot_names, OT_NONE, OT_TARGET, OT_TMP, OT_UNDEF, OT_VAR, OTNAMEG, p, print_metadata_name(), print_space(), print_tmp_name(), print_token(), sptr, write_constant_value(), write_operand(), write_type(), and write_vconstant_value().
Referenced by store_return_value_for_entry(), write_def_values(), write_I_CALL(), write_instructions(), write_operand(), and write_operands().
write_operands()
void write_operands (OPERAND * operand, int flags)
Write operand list.
...
Parameters
operand The head of the list
flags
Write out the operands in order. Not always possible, depends on instruction format. Assumes the separator is a comma.
Definition at line 2468 of file llutil.cpp.
References DBGTRACEIN1, DBGTRACEOUT, flags, operand, p, and write_operand().
Referenced by write_I_CALL(), and write_instructions().
write_struct_defs()
void write_struct_defs (void)
...
Definition at line 3061 of file llutil.cpp.
References defs_to_write(), struct_def_list, and write_defs().
write_type()
void write_type (LL_Type * ll_type)
Write LL_Type to llvm file.
...
Definition at line 2131 of file llutil.cpp.
References print_token(), and LL_Type_::str.
Referenced by DeclareSPtrAsLocal(), print_entry_subroutine(), store_return_value_for_entry(), write_def(), write_I_CALL(), write_instructions(), write_llvm_lltype(), write_local_overlap(), write_module_as_subroutine(), write_operand(), and write_vconstant_value().
write_vconstant_value()
static void write_vconstant_value (int sptr, LL_Type * type, unsigned long long undef_bitmask) static
Definition at line 1862 of file llutil.cpp.
References LL_Type_::data_type, i, LL_DOUBLE, LL_I128, LL_I256, LL_I40, LL_I48, LL_I56, LL_I64, LLVMFIL, print_token(), sptr, type, VCON_CONVAL, write_constant_value(), and write_type().
Referenced by write_constant_value(), and write_operand().
Variable Documentation
ftn_llvm_st
FTN_LLVM_ST ftn_llvm_st
Definition at line 102 of file llutil.cpp.
gblvar_def_list
LLDEF* gblvar_def_list = NULL static
Definition at line 100 of file llutil.cpp.
Referenced by llutil_gblvar_def_reset().
indentlev
int indentlev = 0 static
Definition at line 2533 of file llutil.cpp.
Referenced by indent().
is_gpu_module
int is_gpu_module = false static
Definition at line 110 of file llutil.cpp.
Referenced by llvm_set_acc_module(), and llvm_set_cpu_module().
ll_dfile
FILE* ll_dfile
Definition at line 2534 of file llutil.cpp.
Referenced by cg_llvm_init(), dump_type_for_debug(), indent(), llutil_dfile_init(), and schedule().
llarray_def_list
LLDEF* llarray_def_list = NULL static
Definition at line 97 of file llutil.cpp.
Referenced by LLABI_find_array_type_def(), and make_lltype_from_sptr().
llvm_cc_names
const char* llvm_cc_names[LLCC_LAST] static
Initial value:
= {
    "none", "eq", "ne", "ugt", "uge", "ult", "ule", "sgt", "sge", "slt", "sle"}
Definition at line 87 of file llutil.cpp.
Referenced by write_operand().
llvm_ccfp_names
const char* llvm_ccfp_names[LLCCF_LAST] static
Initial value:
= {
    "none", "false", "oeq", "ogt", "oge", "olt", "ole", "one", "ord",
    "ueq",  "ugt",   "uge", "ult", "ule", "une", "uno", "true"}
Definition at line 90 of file llutil.cpp.
Referenced by write_operand().
LLVMFIL
FILE* LLVMFIL = NULL
Definition at line 103 of file llutil.cpp.
Referenced by llvm_file(), print_line(), print_llsize(), print_nl(), print_space(), print_token(), set_llasm_output_file(), write_constant_value(), and write_vconstant_value().
metadata_id
int metadata_id = 0 static
Definition at line 2481 of file llutil.cpp.
Referenced by init_metadata_index(), and print_metadata_name().
ot_names
const char* ot_names[OT_LAST] static
Initial value:
= {
    "OT_NONE",   "OT_CONSTSPTR", "OT_VAR",  "OT_TMP",        "OT_LABEL",
    "OT_CC",     "OT_TARGET",    "OT_CALL", "OT_CONSTVAL",   "OT_UNDEF",
    "OT_MDNODE", "OT_MEMBER",    "OT_DEF",  "OT_CONSTSTRING"}
Definition at line 40 of file llutil.cpp.
Referenced by get_ot_name(), and write_operand().
struct_def_list
LLDEF* struct_def_list = NULL static
Definition at line 96 of file llutil.cpp.
Referenced by LLABI_find_su_type_def(), llutil_struct_def_reset(), process_dtype_struct(), process_ftn_dtype_struct(), write_def(), write_ftn_typedefs(), and write_struct_defs().