flang: llutil.h File Reference
llutil.h File Reference
#include "gbldefs.h"
#include "global.h"
#include "symtab.h"
#include "ll_structure.h"
#include "ili.h"
Classes
struct LLDimInfo
Dimension information.
struct DINIT_REC
Data initialization record.
struct SPTR_DREC
Symbol pointer drec.
struct GBL_TAG
Node type in a list of globals.
struct EXFUNC_LIST
Extern function list node.
struct TMP_TAG
struct OPERAND
struct INSTR_TAG
struct EXPR_STK_TAG
struct STRUCT_UNION_TAG
struct CSED_TAG
union xx_u
struct LL_ABI_ArgInfo_
Information about how a single argument should be lowered to LLVM IR.
struct LL_ABI_Info_
Information about LLVM lowering the return value and all arguments of a function.
struct FTN_LLVM_ST
Macros
#define LLVM_LONGTERM_AREA 25
need a getitem() area that can persist across routine compilation
#define BITS_IN_BYTE 8
#define LLTNAMEG(llt) llvm_type_names[(llt)->kind]
#define OTNAMEG(p) get_ot_name((p)->ot_type)
#define TO_CMPXCHG_MEMORDER_FAIL(flags) ((LL_InstrListFlags)((flags)<<3))
#define FROM_CMPXCHG_MEMORDER_FAIL(flags)
#define LDST_LOGALIGN_SHIFT 5
#define LDST_LOGALIGN_MASK (7 << LDST_LOGALIGN_SHIFT)
#define LDST_BYTEALIGN(flags) (1U << (((flags) & LDST_LOGALIGN_MASK) >> LDST_LOGALIGN_SHIFT))
#define CALLCONV_SHIFT 14
#define CALLCONV_MASK (0xff << CALLCONV_SHIFT)
#define OLD_STYLE_FUNC -99
#define INSTR_PREV(i) ((i)->prev)
#define INSTR_NEXT(i) ((i)->next)
#define INSTR_IS_TERMINAL(i)
#define DBGXTRACEIN(xsw, in, str)
#define DBGXTRACEIN1(xsw, in, str, p1)
#define DBGXTRACEIN2(xsw, in, str, p1, p2)
#define DBGXTRACEIN3(xsw, in, str, p1, p2, p3)
#define DBGXTRACEIN4(xsw, in, str, p1, p2, p3, p4)
#define DBGXTRACEIN7(xsw, in, str, p1, p2, p3, p4, p5, p6, p7)
#define DBGXTRACEOUT(xsw, in, str)
#define DBGXTRACEOUT1(xsw, in, str, p1)
#define DBGXTRACEOUT2(xsw, in, str, p1, p2)
#define DBGXTRACEOUT3(xsw, in, str, p1, p2, p3)
#define DBGXTRACEOUT4(xsw, in, str, p1, p2, p3, p4)
#define DBGXDUMPLLTYPE(xsw, in, str, llt)
#define DBGXTRACE(xsw, in, str)
#define DBGXTRACE1(xsw, in, str, p1)
#define DBGXTRACE2(xsw, in, str, p1, p2)
#define DBGXTRACE3(xsw, in, str, p1, p2, p3)
#define DBGXTRACE4(xsw, in, str, p1, p2, p3, p4)
#define DBGXTRACE5(xsw, in, str, p1, p2, p3, p4, p5)
#define PASS_STRUCT_BY_REF
#define IS_SMALLT_STRUCT(dtype) (XBIT(121, 0x400000) && DTY(dtype) == TY_CMPLX)
#define ZSIZEOF(dtype) size_of(dtype)
#define LL_ABI_HAS_SRET(abi) ((abi)->arg[0].kind == LL_ARG_INDIRECT)
#define FTN_HOST_REG() ftn_llvm_st.flags.bits.host_reg
#define FTN_HAS_INIT() ftn_llvm_st.flags.bits.has_init
#define FTN_GPU_INIT() ftn_llvm_st.flags.bits.gpu_init
Typedefs
typedef enum OperandFlag_t OperandFlag_t
OPERAND flag values.
typedef enum OperandOutputFlag_t OperandOutputFlag_t
typedef enum OperandType_t OperandType_t
OPERAND types.
typedef enum LLIntegerConditionCodes LLIntegerConditionCodes
LLVM integer condition codes.
typedef enum LLFloatingPointConditionCodes LLFloatingPointConditionCodes
LLVM fp condition codes.
typedef struct LLDimInfo DIM_INFO
Dimension information.
typedef struct DINIT_REC DINIT_REC
Data initialization record.
typedef struct GBL_TAG GBL_LIST
Node type in a list of globals.
typedef struct EXFUNC_LIST EXFUNC_LIST
Extern function list node.
typedef struct TMP_TAG TMPS
typedef struct OPERAND OPERAND
typedef enum LL_InstrName LL_InstrName
LLVM instructions.
typedef enum LL_InstrListFlags LL_InstrListFlags
INSTR_LIST flag values.
typedef struct INSTR_TAG INSTR_LIST
typedef struct EXPR_STK_TAG EXPR_STK
typedef struct STRUCT_UNION_TAG SU_STK
typedef struct CSED_TAG CSED_ITEM
typedef enum LLDEF_Flags LLDEF_Flags
typedef struct LL_ABI_ArgInfo_ LL_ABI_ArgInfo
Information about how a single argument should be lowered to LLVM IR.
typedef struct LL_ABI_Info_ LL_ABI_Info
Information about LLVM lowering the return value and all arguments of a function.
typedef struct FTN_LLVM_ST FTN_LLVM_ST
Enumerations
enum OperandFlag_t {
OPF_NONE , OPF_WRAPPED_MD = (1 << 0) , OPF_NULL_TYPE = (1 << 1) , OPF_SRET_TYPE = (1 << 2) ,
OPF_SRARG_TYPE = (1 << 3) , OPF_SEXT = (1 << 4) , OPF_ZEXT = (1 << 5) , OPF_VOLATILE = (1 << 6) ,
OPF_HIDDEN = (1 << 7) , OPF_CONTAINS_UNDEF = (1 << 8)
}
OPERAND flag values.
enum OperandOutputFlag_t { FLG_OMIT_OP_TYPE = (1 << 0) , FLG_AS_UNSIGNED = (1 << 1) , FLG_FIXUP_RETURN_TYPE = (1 << 2) , FLG_INNER_TYPED_COMPLEX = (1 << 3) }
enum OperandType_t {
OT_NONE , OT_CONSTSPTR , OT_VAR , OT_TMP ,
OT_LABEL , OT_CC , OT_TARGET , OT_CALL ,
OT_CONSTVAL , OT_UNDEF , OT_MDNODE , OT_MEMBER ,
OT_DEF , OT_CONSTSTRING , OT_LAST
}
OPERAND types.
enum LLIntegerConditionCodes {
LLCC_NONE , LLCC_EQ , LLCC_NE , LLCC_UGT ,
LLCC_UGE , LLCC_ULT , LLCC_ULE , LLCC_SGT ,
LLCC_SGE , LLCC_SLT , LLCC_SLE , LLCC_LAST
}
LLVM integer condition codes.
enum LLFloatingPointConditionCodes {
LLCCF_NONE , LLCCF_FALSE , LLCCF_OEQ , LLCCF_OGT ,
LLCCF_OGE , LLCCF_OLT , LLCCF_OLE , LLCCF_ONE ,
LLCCF_ORD , LLCCF_UEQ , LLCCF_UGT , LLCCF_UGE ,
LLCCF_ULT , LLCCF_ULE , LLCCF_UNE , LLCCF_UNO ,
LLCCF_TRUE , LLCCF_LAST
}
LLVM fp condition codes.
enum LL_InstrName {
I_NONE , I_RET , I_BR , I_SW ,
I_INVOKE , I_UNWIND , I_UNREACH , I_ADD ,
I_FADD , I_SUB , I_FSUB , I_MUL ,
I_FMUL , I_UDIV , I_SDIV , I_FDIV ,
I_UREM , I_SREM , I_FREM , I_SHL ,
I_LSHR , I_ASHR , I_AND , I_OR ,
I_XOR , I_EXTELE , I_INSELE , I_SHUFFVEC ,
I_EXTRACTVAL , I_INSERTVAL , I_MALLOC , I_FREE ,
I_ALLOCA , I_LOAD , I_STORE , I_GEP ,
I_TRUNC , I_ZEXT , I_SEXT , I_FPTRUNC ,
I_FPEXT , I_FPTOUI , I_FPTOSI , I_UITOFP ,
I_SITOFP , I_PTRTOINT , I_INTTOPTR , I_BITCAST ,
I_ICMP , I_FCMP , I_VICMP , I_VFCMP ,
I_PHI , I_SELECT , I_CALL , I_VA_ARG ,
I_DECL , I_LANDINGPAD , I_RESUME , I_CLEANUP ,
I_CATCH , I_BARRIER , I_ATOMICRMW , I_CMPXCHG ,
I_FENCE , I_PICALL , I_INDBR , I_FILTER ,
I_LAST
}
LLVM instructions.
enum LL_InstrListFlags {
InstrListFlagsNull , VAR_ARGS_FLAG = (1 << 0) , CALL_FUNC_PTR_FLAG = (1 << 1) , CALL_INTRINSIC_FLAG = (1 << 2) ,
HIDDEN_ARG_FLAG = (1 << 3) , LOOP_BACKEDGE_FLAG = (1 << 4) , FAST_MATH_FLAG = (1 << 4) , VOLATILE_FLAG = (1 << 4) ,
NSZ_MATH_FLAG = (1 << 5) , REASSOC_MATH_FLAG = (1 << 6) , FAST_CALL = (1 << 7) , ARM_AAPCS = (1 << 8) ,
ARM_AAPCS_VFP = (1 << 9) , CANCEL_CALL_DBG_VALUE = (1 << 10) , NOSIGNEDWRAP = (1 << 11) , NOUNSIGNEDWRAP = (1 << 12) ,
FUNC_RETURN_IS_FUNC_PTR = (1 << 13) , LDST_HAS_ACCESSGRP_METADATA = (1 << 14) , ATOMIC_RMW_OP_FLAGS = (0xF << 13) , ATOMIC_XCHG_FLAG = (1 << 13) ,
ATOMIC_ADD_FLAG = (2 << 13) , ATOMIC_SUB_FLAG = (3 << 13) , ATOMIC_AND_FLAG = (4 << 13) , ATOMIC_NAND_FLAG = (5 << 13) ,
ATOMIC_OR_FLAG = (6 << 13) , ATOMIC_XOR_FLAG = (7 << 13) , ATOMIC_MAX_FLAG = (8 << 13) , ATOMIC_MIN_FLAG = (9 << 13) ,
ATOMIC_UMAX_FLAG = (10 << 13) , ATOMIC_UMIN_FLAG = (11 << 13) , ATOMIC_SINGLETHREAD_FLAG = (1 << 17) , ATOMIC_MEM_ORD_FLAGS = (0x7 << 18) ,
ATOMIC_MONOTONIC_FLAG = (1 << 18) , ATOMIC_ACQUIRE_FLAG = (3 << 18) , ATOMIC_RELEASE_FLAG = (4 << 18) , ATOMIC_ACQ_REL_FLAG = (5 << 18) ,
ATOMIC_SEQ_CST_FLAG = (6 << 18) , ATOMIC_MEM_ORD_FAIL_FLAGS = (0x7 << 21) , CMPXCHG_WEAK_FLAG = (1 << 24) , DELETABLE = (1 << 25) ,
STARTEBB = (1 << 26) , ROOTDG = (1 << 27) , INST_ADDED = (1 << 28) , INST_VISITED = (1 << 29) ,
NOUNWIND_CALL_FLAG = (1 << 30) , INST_LIST_FLAGS_MAX = NOUNWIND_CALL_FLAG + (NOUNWIND_CALL_FLAG - 1)
}
INSTR_LIST flag values.
enum LLDEF_Flags {
LLDEF_NONE = 0 , LLDEF_IS_TYPE = (1 << 0) , LLDEF_IS_INITIALIZED = (1 << 1) , LLDEF_IS_STATIC = (1 << 2) ,
LLDEF_IS_EMPTY = (1 << 3) , LLDEF_IS_EXTERNAL = (1 << 4) , LLDEF_IS_STRUCT = (1 << 5) , LLDEF_IS_ARRAY = (1 << 6) ,
LLDEF_IS_ACCSTRING = (1 << 7) , LLDEF_IS_CONST = (1 << 8) , LLDEF_IS_UNPACKED_STRUCT = (1 << 9)
}
enum LL_ABI_ArgKind {
LL_ARG_UNKNOWN , LL_ARG_DIRECT , LL_ARG_ZEROEXT , LL_ARG_SIGNEXT ,
LL_ARG_COERCE , LL_ARG_INDIRECT , LL_ARG_INDIRECT_BUFFERED , LL_ARG_BYVAL
}
Functions
const char * get_ot_name (unsigned ot)
...
LL_Type * get_struct_def_type (char *def_name, LL_Module *module)
...
void write_struct_defs (void)
...
void append_llvm_used (OPERAND *op)
void print_dbg_line_no_comma (LL_MDRef md)
Emit line info debug information.
void print_dbg_line (LL_MDRef md)
void indent (int change)
...
LL_ABI_Info * ll_abi_alloc (LL_Module *module, unsigned nargs)
...
LL_ABI_Info * ll_abi_free (LL_ABI_Info *abi)
...
const struct LL_Type_ * ll_abi_return_type (LL_ABI_Info *abi)
...
const struct LL_Type_ * ll_abi_function_type (LL_ABI_Info *abi)
...
LL_Type * make_lltype_from_abi_arg (LL_ABI_ArgInfo *arg)
...
void ll_abi_compute_call_conv (LL_ABI_Info *abi, int func_sptr, int jsra_flags)
LL_Type * ll_coercion_type (LL_Module *module, DTYPE dtype, ISZ_T size, ISZ_T reg_size)
void optimize_block (INSTR_LIST *last_block_instr)
...
void maybe_undo_recip_div (INSTR_LIST *isns)
Translate x * 1.0 / y to x / y.
void widenAddressArith (void)
Widen address arithmetic.
bool funcHasNoDepChk (void)
Does the current procedure have blocks marked no dep check?
void redundantLdLdElim (void)
Eliminate load-load operations from the uplevel structure.
bool block_branches_to (int bih, int target)
Does block bih branch to block target?
int enhanced_conflict (int nme1, int nme2)
...
void sched_instructions (INSTR_LIST *)
...
void llvm_set_acc_module (void)
set the module as gpu/cpu module
void llvm_set_cpu_module (void)
LL_Module * get_current_module (void)
LL_Module * llvm_get_current_module (void)
void reset_equiv_var (void)
...
void reset_master_sptr (void)
...
void process_cmblk_sptr (int sptr)
void write_ftn_typedefs (void)
...
void write_local_overlap (void)
...
void print_entry_subroutine (LL_Module *module)
Write out all Entry's as a separate routine.
LL_Type * make_generic_dummy_lltype (void)
...
bool llis_dummied_arg (SPTR sptr)
...
bool currsub_is_sret (void)
...
void write_gblvar_defs (FILE *target_file, LL_Module *module)
...
bool is_function (int sptr)
...
bool ll_abi_use_llvm_varargs (LL_ABI_Info *abi)
Should this function be represented as a varags LLVM function type?
bool small_aggr_return (DTYPE dtype)
...
const char * llvm_fc_type (DTYPE dtype)
...
const char * process_dtype_struct (DTYPE dtype)
...
const char * process_ftn_dtype_struct (DTYPE dtype, char *tname, bool printed)
...
const char * llutil_strdup (const char *str)
...
DTYPE dtype_from_return_type (ILI_OP ret_opc)
...
DTYPE get_dtype_from_arg_opc (ILI_OP opc)
...
DTYPE get_dtype_from_tytype (TY_KIND ty)
...
DTYPE get_dtype_for_vect_type_nme (int nme)
...
DTYPE get_param_equiv_dtype (DTYPE dtype)
...
FILE * llvm_file (void)
...
DTYPE generic_dummy_dtype (void)
...
int get_dim_size (ADSC *ad, int dim)
...
DTYPE get_int_dtype_from_size (int size)
...
DTYPE get_return_dtype (DTYPE dtype, unsigned *flags, unsigned new_flag)
...
int is_struct_kind (DTYPE dtype, bool check_return, bool return_vector_as_struct)
...
int visit_flattened_dtype (dtype_visitor visitor, void *context, DTYPE dtype, unsigned address, unsigned member_sptr)
...
LL_ABI_Info * ll_abi_for_func_sptr (LL_Module *module, SPTR func_sptr, DTYPE dtype)
Get ABI lowering info for a function given its symbol table entry.
LL_ABI_Info * ll_abi_from_call_site (LL_Module *module, int ilix, DTYPE ret_dtype)
Get ABI lowering info for a specific call site.
LL_ABI_Info * process_ll_abi_func_ftn (SPTR func_sptr, bool use_sptrs)
...
LL_ABI_Info * process_ll_abi_func_ftn_mod (LL_Module *mod, SPTR func_sptr, bool update)
...
LL_InstrListFlags ldst_instr_flags_from_dtype (DTYPE dtype)
...
LL_InstrListFlags ldst_instr_flags_from_dtype_nme (DTYPE dtype, int nme)
...
LL_Type * get_ftn_cbind_lltype (SPTR sptr)
...
LL_Type * get_ftn_cmblk_lltype (SPTR sptr)
...
LL_Type * get_ftn_dummy_lltype (int sptr)
...
LL_Type * get_ftn_extern_lltype (SPTR sptr)
...
LL_Type * get_ftn_func_lltype (SPTR sptr)
...
LL_Type * get_ftn_hollerith_type (int sptr)
...
LL_Type * get_ftn_static_lltype (SPTR sptr)
...
LL_Type * get_ftn_typedesc_lltype (SPTR sptr)
...
LL_Type * ll_convert_array_dtype (LL_Module *module, DTYPE dtype, int addrspace)
...
LL_Type * ll_convert_dtype (LL_Module *module, DTYPE dtype)
...
LL_Type * make_array_lltype (int size, LL_Type *pts_to)
...
LL_Type * make_int_lltype (unsigned bits)
...
LL_Type * make_lltype_from_arg (int arg)
...
LL_Type * make_lltype_from_arg_noproto (int arg)
...
LL_Type * make_lltype_from_dtype (DTYPE dtype)
...
LL_Type * make_lltype_from_dtype_with_addrspace (DTYPE dtype, int addrspace)
...
LL_Type * make_lltype_from_iface (SPTR sptr)
...
LL_Type * make_lltype_from_sptr (SPTR sptr)
...
LL_Type * make_lltype_sz4v3_from_dtype (DTYPE dtype)
...
LL_Type * make_lltype_sz4v3_from_sptr (SPTR sptr)
...
LL_Type * make_ptr_lltype (LL_Type *pts_to)
...
LL_Type * make_vector_lltype (int size, LL_Type *pts_to)
...
LL_Type * make_void_lltype (void)
...
void layout_struct_body (LL_Module *module, LL_Type *struct_type, int member_sptr, ISZ_T size_bytes)
...
LL_Type * process_acc_decl_common (LL_Module *module, int first, BIGINT size, int is_constant, char *d_name, int externcommon)
...
LL_Type * process_acc_decl_gblvar (LL_Module *module, LL_Type *lltype, SPTR sptr, char *name)
it defines a global variable, used by lili2llvm_decl_globalvar.
LL_Type * process_acc_decl_statics (LL_Module *module, int first, char *d_name, int init, int addrspace)
...
LL_Type * process_acc_string (LL_Module *module, char *name, int sptr, bool initialize)
...
OPERAND * gen_copy_list_op (OPERAND *operands)
...
OPERAND * gen_copy_op (OPERAND *op)
...
OPERAND * make_constsptr_op (SPTR sptr)
...
OPERAND * make_constval32_op (int idx)
...
OPERAND * make_constval_opL (LL_Type *ll_type, INT conval0, INT conval1, INT conval2, INT conval3)
...
OPERAND * make_constval_op (LL_Type *ll_type, INT conval0, INT conval1)
...
OPERAND * make_def_op (char *str)
...
OPERAND * make_label_op (SPTR sptr)
...
OPERAND * make_mdref_op (LL_MDRef mdref)
...
OPERAND * make_metadata_wrapper_op (SPTR sptr, LL_Type *llTy)
Create metadata operand that wraps an LLVM value.
OPERAND * make_null_op (LL_Type *llt)
...
OPERAND * make_operand (void)
...
OPERAND * make_target_op (SPTR sptr)
...
OPERAND * make_tmp_op (LL_Type *llt, TMPS *tmps)
...
OPERAND * make_undef_op (LL_Type *llt)
...
OPERAND * make_var_op (SPTR sptr)
...
OPERAND * process_symlinked_sptr (int sptr, int total_init_sz, int is_union, int max_field_sz)
...
TMPS * make_tmps (void)
...
void init_metadata_index (TMPS *t)
...
void init_output_file (void)
...
void ll_abi_complete_arg_info (LL_ABI_Info *abi, LL_ABI_ArgInfo *arg, DTYPE dtype)
...
void ll_add_func_proto (int sptr, unsigned flags, int nargs, DTYPE *args)
Add a function prototype declaration to the LLVM module.
void ll_override_type_string (LL_Type *llt, const char *str)
...
void llutil_def_reset (void)
...
void llutil_dfile_init (void)
...
void llutil_gblvar_def_reset (void)
...
void llutil_struct_def_reset (void)
...
void print_line (const char *ln)
...
void print_line_tobuf (char *ln, char *buf)
...
void print_llsize (LL_Type *llt)
...
void print_llsize_tobuf (LL_Type *llt, char *buf)
...
void print_metadata_name (TMPS *t)
...
void print_nl_tobuf (char *buf)
...
void print_nl (void)
...
void print_space (int num)
...
void print_space_tobuf (int num, char *buf)
...
void print_token (const char *tk)
...
void print_token_tobuf (char *tk, char *buf)
...
void process_acc_decl_const_param (LL_Module *module, char *name, int sptr)
...
void process_acc_put_dinit (int cmem, int x, bool loop)
...
void set_metadata_string (TMPS *t, char *string)
...
void write_constant_value (int sptr, LL_Type *type, INT conval0, INT conval1, bool uns)
...
void write_operand (OPERAND *p, const char *punc_string, int flags)
...
void write_operands (OPERAND *operand, int flags)
...
void write_type (LL_Type *ll_type)
...
LL_InstrListFlags ll_instr_flags_from_aop (ATOMIC_RMW_OP aop)
Compute the LL_InstrListFlag set from an ATOMIC_RMW_OP.
bool llis_integral_kind (DTYPE dtype)
bool llis_pointer_kind (DTYPE dtype)
bool llis_array_kind (DTYPE dtype)
bool llis_vector_kind (DTYPE dtype)
bool llis_struct_kind (DTYPE dtype)
bool llis_function_kind (DTYPE dtype)
bool should_preserve_param (const DTYPE dtype)
return whether param debug info should be preserved
Variables
FILE * ll_dfile
SPTR_DREC * sptr_dinit_array
FTN_LLVM_ST ftn_llvm_st
Macro Definition Documentation
BITS_IN_BYTE
#define BITS_IN_BYTE 8
Definition at line 19 of file llutil.h.
CALLCONV_MASK
#define CALLCONV_MASK (0xff << CALLCONV_SHIFT)
Definition at line 383 of file llutil.h.
CALLCONV_SHIFT
#define CALLCONV_SHIFT 14
Definition at line 380 of file llutil.h.
DBGXDUMPLLTYPE
#define DBGXDUMPLLTYPE (xsw, in, str, llt)
Value:
  if (xsw) {                              \
    if (in) {                             \
      indent(0);                          \
    }                                     \
    fprintf(ll_dfile, str);               \
    if (llt)                              \
      dump_type_for_debug(llt);           \
    fprintf(ll_dfile, "\n");              \
  }
Definition at line 549 of file llutil.h.
DBGXTRACE
#define DBGXTRACE (xsw, in, str)
Value:
  if (xsw) {                     \
    if (in) {                    \
      indent(0);                 \
    }                            \
    fprintf(ll_dfile, str "\n"); \
  }
Definition at line 559 of file llutil.h.
DBGXTRACE1
#define DBGXTRACE1 (xsw, in, str, p1)
Value:
  if (xsw) {                         \
    if (in) {                        \
      indent(0);                     \
    }                                \
    fprintf(ll_dfile, str "\n", p1); \
  }
Definition at line 566 of file llutil.h.
DBGXTRACE2
#define DBGXTRACE2 (xsw, in, str, p1, p2)
Value:
  if (xsw) {                             \
    if (in) {                            \
      indent(0);                         \
    }                                    \
    fprintf(ll_dfile, str "\n", p1, p2); \
  }
Definition at line 573 of file llutil.h.
DBGXTRACE3
#define DBGXTRACE3 (xsw, in, str, p1, p2, p3)
Value:
  if (xsw) {                                 \
    if (in) {                                \
      indent(0);                             \
    }                                        \
    fprintf(ll_dfile, str "\n", p1, p2, p3); \
  }
Definition at line 580 of file llutil.h.
DBGXTRACE4
#define DBGXTRACE4 (xsw, in, str, p1, p2, p3, p4)
Value:
  if (xsw) {                                     \
    if (in) {                                    \
      indent(0);                                 \
    }                                            \
    fprintf(ll_dfile, str "\n", p1, p2, p3, p4); \
  }
Definition at line 587 of file llutil.h.
DBGXTRACE5
#define DBGXTRACE5 (xsw, in, str, p1, p2, p3, p4, p5)
Value:
  if (xsw) {                                         \
    if (in) {                                        \
      indent(0);                                     \
    }                                                \
    fprintf(ll_dfile, str "\n", p1, p2, p3, p4, p5); \
  }
Definition at line 594 of file llutil.h.
DBGXTRACEIN
#define DBGXTRACEIN (xsw, in, str)
Value:
  if (xsw) {                                         \
    if (in) {                                        \
      indent(1);                                     \
    }                                                \
    fprintf(ll_dfile, "<%s" str "\n", __FUNCTION__); \
  }
Definition at line 471 of file llutil.h.
DBGXTRACEIN1
#define DBGXTRACEIN1 (xsw, in, str, p1)
Value:
  if (xsw) {                                             \
    if (in) {                                            \
      indent(1);                                         \
    }                                                    \
    fprintf(ll_dfile, "<%s" str "\n", __FUNCTION__, p1); \
  }
Definition at line 478 of file llutil.h.
DBGXTRACEIN2
#define DBGXTRACEIN2 (xsw, in, str, p1, p2)
Value:
  if (xsw) {                                                 \
    if (in) {                                                \
      indent(1);                                             \
    }                                                        \
    fprintf(ll_dfile, "<%s" str "\n", __FUNCTION__, p1, p2); \
  }
Definition at line 485 of file llutil.h.
DBGXTRACEIN3
#define DBGXTRACEIN3 (xsw, in, str, p1, p2, p3)
Value:
  if (xsw) {                                                     \
    if (in) {                                                    \
      indent(1);                                                 \
    }                                                            \
    fprintf(ll_dfile, "<%s" str "\n", __FUNCTION__, p1, p2, p3); \
  }
Definition at line 492 of file llutil.h.
DBGXTRACEIN4
#define DBGXTRACEIN4 (xsw, in, str, p1, p2, p3, p4)
Value:
  if (xsw) {                                                         \
    if (in) {                                                        \
      indent(1);                                                     \
    }                                                                \
    fprintf(ll_dfile, "<%s" str "\n", __FUNCTION__, p1, p2, p3, p4); \
  }
Definition at line 499 of file llutil.h.
DBGXTRACEIN7
#define DBGXTRACEIN7 (xsw, in, str, p1, p2, p3, p4, p5, p6, p7)
Value:
  if (xsw) {                                                                \
    if (in) {                                                               \
      indent(1);                                                            \
    }                                                                       \
    fprintf(ll_dfile, "<%s" str "\n", __FUNCTION__, p1, p2, p3, p4, p5, p6, \
            p7);                                                            \
  }
Definition at line 506 of file llutil.h.
DBGXTRACEOUT
#define DBGXTRACEOUT (xsw, in, str)
Value:
  if (xsw) {                                         \
    if (in) {                                        \
      indent(-1);                                    \
    }                                                \
    fprintf(ll_dfile, ">%s" str "\n", __FUNCTION__); \
  }
Definition at line 514 of file llutil.h.
DBGXTRACEOUT1
#define DBGXTRACEOUT1 (xsw, in, str, p1)
Value:
  if (xsw) {                                             \
    if (in) {                                            \
      indent(-1);                                        \
    }                                                    \
    fprintf(ll_dfile, ">%s" str "\n", __FUNCTION__, p1); \
  }
Definition at line 521 of file llutil.h.
DBGXTRACEOUT2
#define DBGXTRACEOUT2 (xsw, in, str, p1, p2)
Value:
  if (xsw) {                                                 \
    if (in) {                                                \
      indent(-1);                                            \
    }                                                        \
    fprintf(ll_dfile, ">%s" str "\n", __FUNCTION__, p1, p2); \
  }
Definition at line 528 of file llutil.h.
DBGXTRACEOUT3
#define DBGXTRACEOUT3 (xsw, in, str, p1, p2, p3)
Value:
  if (xsw) {                                                     \
    if (in) {                                                    \
      indent(-1);                                                \
    }                                                            \
    fprintf(ll_dfile, ">%s" str "\n", __FUNCTION__, p1, p2, p3); \
  }
Definition at line 535 of file llutil.h.
DBGXTRACEOUT4
#define DBGXTRACEOUT4 (xsw, in, str, p1, p2, p3, p4)
Value:
  if (xsw) {                                                         \
    if (in) {                                                        \
      indent(-1);                                                    \
    }                                                                \
    fprintf(ll_dfile, ">%s" str "\n", __FUNCTION__, p1, p2, p3, p4); \
  }
Definition at line 542 of file llutil.h.
FROM_CMPXCHG_MEMORDER_FAIL
#define FROM_CMPXCHG_MEMORDER_FAIL (flags)
Value:
                                           ((LL_InstrListFlags) \
                                           ((flags)>>3 & ATOMIC_MEM_ORD_FLAGS))
Definition at line 368 of file llutil.h.
FTN_GPU_INIT
#define FTN_GPU_INIT () ftn_llvm_st.flags.bits.gpu_init
Definition at line 978 of file llutil.h.
FTN_HAS_INIT
#define FTN_HAS_INIT () ftn_llvm_st.flags.bits.has_init
Definition at line 977 of file llutil.h.
FTN_HOST_REG
#define FTN_HOST_REG () ftn_llvm_st.flags.bits.host_reg
Definition at line 976 of file llutil.h.
INSTR_IS_TERMINAL
#define INSTR_IS_TERMINAL (i)
Value:
    ((i)->i_name == I_BR || (i)->i_name == I_SW || (i)->i_name == I_RET || \
     (i)->i_name == I_RESUME || (i)->i_name == I_UNREACH)
Definition at line 409 of file llutil.h.
INSTR_NEXT
#define INSTR_NEXT (i) ((i)->next)
Definition at line 408 of file llutil.h.
INSTR_PREV
#define INSTR_PREV (i) ((i)->prev)
Definition at line 407 of file llutil.h.
IS_SMALLT_STRUCT
#define IS_SMALLT_STRUCT (dtype) (XBIT(121, 0x400000) && DTY(dtype) == TY_CMPLX)
Definition at line 634 of file llutil.h.
LDST_BYTEALIGN
#define LDST_BYTEALIGN (flags) (1U << (((flags) & LDST_LOGALIGN_MASK) >> LDST_LOGALIGN_SHIFT))
Definition at line 377 of file llutil.h.
LDST_LOGALIGN_MASK
#define LDST_LOGALIGN_MASK (7 << LDST_LOGALIGN_SHIFT)
Definition at line 374 of file llutil.h.
LDST_LOGALIGN_SHIFT
#define LDST_LOGALIGN_SHIFT 5
Definition at line 371 of file llutil.h.
LL_ABI_HAS_SRET
#define LL_ABI_HAS_SRET (abi) ((abi)->arg[0].kind == LL_ARG_INDIRECT)
Definition at line 828 of file llutil.h.
LLTNAMEG
#define LLTNAMEG (llt) llvm_type_names[(llt)->kind]
Definition at line 42 of file llutil.h.
LLVM_LONGTERM_AREA
#define LLVM_LONGTERM_AREA 25
need a getitem() area that can persist across routine compilation
Definition at line 18 of file llutil.h.
OLD_STYLE_FUNC
#define OLD_STYLE_FUNC -99
Definition at line 405 of file llutil.h.
OTNAMEG
#define OTNAMEG (p) get_ot_name((p)->ot_type)
Definition at line 65 of file llutil.h.
PASS_STRUCT_BY_REF
#define PASS_STRUCT_BY_REF
Definition at line 633 of file llutil.h.
TO_CMPXCHG_MEMORDER_FAIL
#define TO_CMPXCHG_MEMORDER_FAIL (flags) ((LL_InstrListFlags)((flags)<<3))
Definition at line 367 of file llutil.h.
ZSIZEOF
#define ZSIZEOF (dtype) size_of(dtype)
Definition at line 637 of file llutil.h.
Typedef Documentation
CSED_ITEM
typedef struct CSED_TAG CSED_ITEM
DIM_INFO
typedef struct LLDimInfo DIM_INFO
Dimension information.
DINIT_REC
typedef struct DINIT_REC DINIT_REC
Data initialization record.
EXFUNC_LIST
typedef struct EXFUNC_LIST EXFUNC_LIST
Extern function list node.
EXPR_STK
typedef struct EXPR_STK_TAG EXPR_STK
FTN_LLVM_ST
typedef struct FTN_LLVM_ST FTN_LLVM_ST
GBL_LIST
typedef struct GBL_TAG GBL_LIST
Node type in a list of globals.
INSTR_LIST
typedef struct INSTR_TAG INSTR_LIST
LL_ABI_ArgInfo
typedef struct LL_ABI_ArgInfo_ LL_ABI_ArgInfo
Information about how a single argument should be lowered to LLVM IR.
LL_ABI_Info
typedef struct LL_ABI_Info_ LL_ABI_Info
Information about LLVM lowering the return value and all arguments of a function.
LL_InstrListFlags
typedef enum LL_InstrListFlags LL_InstrListFlags
INSTR_LIST flag values.
LL_InstrName
typedef enum LL_InstrName LL_InstrName
LLVM instructions.
LLDEF_Flags
typedef enum LLDEF_Flags LLDEF_Flags
LLFloatingPointConditionCodes
typedef enum LLFloatingPointConditionCodes LLFloatingPointConditionCodes
LLVM fp condition codes.
LLIntegerConditionCodes
typedef enum LLIntegerConditionCodes LLIntegerConditionCodes
LLVM integer condition codes.
OPERAND
typedef struct OPERAND OPERAND
OperandFlag_t
typedef enum OperandFlag_t OperandFlag_t
OPERAND flag values.
OperandOutputFlag_t
typedef enum OperandOutputFlag_t OperandOutputFlag_t
OperandType_t
typedef enum OperandType_t OperandType_t
OPERAND types.
SU_STK
typedef struct STRUCT_UNION_TAG SU_STK
TMPS
typedef struct TMP_TAG TMPS
Enumeration Type Documentation
LL_ABI_ArgKind
enum LL_ABI_ArgKind
These are the possible ways of lowering a single function argument (or return value) to LLVM IR.
Enumerator
LL_ARG_UNKNOWN
LL_ARG_DIRECT
LL_ARG_ZEROEXT
LL_ARG_SIGNEXT
LL_ARG_COERCE
LL_ARG_INDIRECT
LL_ARG_INDIRECT_BUFFERED
LL_ARG_BYVAL
Definition at line 679 of file llutil.h.
LL_InstrListFlags
enum LL_InstrListFlags
INSTR_LIST flag values.
Enumerator
InstrListFlagsNull
VAR_ARGS_FLAG
CALL_FUNC_PTR_FLAG
CALL_INTRINSIC_FLAG
HIDDEN_ARG_FLAG
LOOP_BACKEDGE_FLAG
I_BR only
FAST_MATH_FLAG
I_CALL only
VOLATILE_FLAG
I_LOAD, I_STORE, I_ATOMICRMW, I_CMPXCHG only
NSZ_MATH_FLAG
REASSOC_MATH_FLAG
FAST_CALL
ARM_AAPCS
ARM_AAPCS_VFP
CANCEL_CALL_DBG_VALUE
NOSIGNEDWRAP
NOUNSIGNEDWRAP
FUNC_RETURN_IS_FUNC_PTR
LDST_HAS_ACCESSGRP_METADATA
I_LOAD, I_STORE only, for llvm.loop.parallel_accesses
ATOMIC_RMW_OP_FLAGS
ATOMIC_XCHG_FLAG
ATOMIC_ADD_FLAG
ATOMIC_SUB_FLAG
ATOMIC_AND_FLAG
ATOMIC_NAND_FLAG
ATOMIC_OR_FLAG
ATOMIC_XOR_FLAG
ATOMIC_MAX_FLAG
ATOMIC_MIN_FLAG
ATOMIC_UMAX_FLAG
ATOMIC_UMIN_FLAG
ATOMIC_SINGLETHREAD_FLAG
ATOMIC_MEM_ORD_FLAGS
ATOMIC_MONOTONIC_FLAG
ATOMIC_ACQUIRE_FLAG
ATOMIC_RELEASE_FLAG
ATOMIC_ACQ_REL_FLAG
ATOMIC_SEQ_CST_FLAG
ATOMIC_MEM_ORD_FAIL_FLAGS
CMPXCHG_WEAK_FLAG
DELETABLE
STARTEBB
ROOTDG
INST_ADDED
INST_VISITED
NOUNWIND_CALL_FLAG
INST_LIST_FLAGS_MAX
Definition at line 262 of file llutil.h.
LL_InstrName
enum LL_InstrName
LLVM instructions.
Enumerator
I_NONE
must be 0
I_RET
I_BR
I_SW
I_INVOKE
I_UNWIND
I_UNREACH
I_ADD
I_FADD
I_SUB
I_FSUB
I_MUL
I_FMUL
I_UDIV
I_SDIV
I_FDIV
I_UREM
I_SREM
I_FREM
I_SHL
I_LSHR
I_ASHR
I_AND
I_OR
I_XOR
I_EXTELE
I_INSELE
I_SHUFFVEC
I_EXTRACTVAL
I_INSERTVAL
I_MALLOC
I_FREE
I_ALLOCA
I_LOAD
I_STORE
I_GEP
I_TRUNC
I_ZEXT
I_SEXT
I_FPTRUNC
I_FPEXT
I_FPTOUI
I_FPTOSI
I_UITOFP
I_SITOFP
I_PTRTOINT
I_INTTOPTR
I_BITCAST
I_ICMP
I_FCMP
I_VICMP
I_VFCMP
I_PHI
I_SELECT
I_CALL
I_VA_ARG
I_DECL
I_LANDINGPAD
I_RESUME
I_CLEANUP
I_CATCH
I_BARRIER
I_ATOMICRMW
I_CMPXCHG
I_FENCE
I_PICALL
I_INDBR
I_FILTER
I_LAST
must be last in enum
Definition at line 185 of file llutil.h.
LLDEF_Flags
enum LLDEF_Flags
Enumerator
LLDEF_NONE
LLDEF_IS_TYPE
LLDEF_IS_INITIALIZED
LLDEF_IS_STATIC
LLDEF_IS_EMPTY
LLDEF_IS_EXTERNAL
LLDEF_IS_STRUCT
LLDEF_IS_ARRAY
LLDEF_IS_ACCSTRING
LLDEF_IS_CONST
LLDEF_IS_UNPACKED_STRUCT
Definition at line 443 of file llutil.h.
LLFloatingPointConditionCodes
enum LLFloatingPointConditionCodes
LLVM fp condition codes.
Enumerator
LLCCF_NONE
LLCCF_FALSE
always false
LLCCF_OEQ
ordered and equal
LLCCF_OGT
ordered and greater than
LLCCF_OGE
ordered and greater than or equal
LLCCF_OLT
ordered and less than
LLCCF_OLE
ordered and less than or equal
LLCCF_ONE
ordered and not equal
LLCCF_ORD
ordered (no nans)
LLCCF_UEQ
unordered or equal
LLCCF_UGT
unordered or greater than
LLCCF_UGE
unordered or greater than or equal
LLCCF_ULT
unordered or less than
LLCCF_ULE
unordered or less than or equal
LLCCF_UNE
unordered or not equal
LLCCF_UNO
unordered (either nans)
LLCCF_TRUE
always true
LLCCF_LAST
Definition at line 85 of file llutil.h.
LLIntegerConditionCodes
enum LLIntegerConditionCodes
LLVM integer condition codes.
Enumerator
LLCC_NONE
LLCC_EQ
equal
LLCC_NE
not equal
LLCC_UGT
usigned greater than
LLCC_UGE
unsigned greater or equal
LLCC_ULT
unsigned less than
LLCC_ULE
unsigned less or equal
LLCC_SGT
signed greater than
LLCC_SGE
signed greater or equal
LLCC_SLT
signed less than
LLCC_SLE
signed less or equal
LLCC_LAST
Definition at line 69 of file llutil.h.
OperandFlag_t
enum OperandFlag_t
OPERAND flag values.
Enumerator
OPF_NONE
OPF_WRAPPED_MD
OPF_NULL_TYPE
OPF_SRET_TYPE
OPF_SRARG_TYPE
OPF_SEXT
OPF_ZEXT
OPF_VOLATILE
OPF_HIDDEN
OPF_CONTAINS_UNDEF
Definition at line 22 of file llutil.h.
OperandOutputFlag_t
enum OperandOutputFlag_t
Enumerator
FLG_OMIT_OP_TYPE
FLG_AS_UNSIGNED
FLG_FIXUP_RETURN_TYPE
FLG_INNER_TYPED_COMPLEX
Definition at line 35 of file llutil.h.
OperandType_t
enum OperandType_t
OPERAND types.
Enumerator
OT_NONE
must be first (0) member
OT_CONSTSPTR
OT_VAR
OT_TMP
OT_LABEL
OT_CC
OT_TARGET
OT_CALL
OT_CONSTVAL
OT_UNDEF
OT_MDNODE
OT_MEMBER
OT_DEF
OT_CONSTSTRING
OT_LAST
must be last member
Definition at line 45 of file llutil.h.
Function Documentation
append_llvm_used()
void append_llvm_used (OPERAND * op)
block_branches_to()
bool block_branches_to (int bih, int target)
Does block bih branch to block target?
...
Definition at line 884 of file llopt.cpp.
References BIH_ILTLAST, IL_TYPE, ili, ILI_OPC, ILI_OPND, ilis, ilt, ILT_ILIP, and ILTY_BRANCH.
Referenced by fix_nodepchk_flag(), and redundantLdLdElim().
currsub_is_sret()
bool currsub_is_sret (void)
...
Definition at line 817 of file cgmain.cpp.
References llvm_tag::abi_info, LL_ABI_HAS_SRET, and llvm_info.
Referenced by get_ftn_dummy_lltype(), and make_stmt().
dtype_from_return_type()
DTYPE dtype_from_return_type (ILI_OP ret_opc)
...
...
Definition at line 1148 of file llutil.cpp.
References DT_CMPLX, DT_CPTR, DT_DBLE, DT_FLOAT, DT_INT, ERR_Fatal, and interr().
Referenced by gen_llvm_expr().
enhanced_conflict()
int enhanced_conflict (int nme1, int nme2)
...
/**
Definition at line 88 of file llsched.cpp.
References build_same_base_nme(), c, conflict(), NOCONFLICT, SAME, and XBIT.
Referenced by build_idep_graph(), and find_load_cse().
funcHasNoDepChk()
bool funcHasNoDepChk (void)
Does the current procedure have blocks marked no dep check?
...
Definition at line 707 of file llopt.cpp.
References BIH_NEXT, and BIH_NODEPCHK.
Referenced by schedule(), and widenAddressArith().
gen_copy_list_op()
OPERAND * gen_copy_list_op (OPERAND * operands)
...
Definition at line 2727 of file llutil.cpp.
References gen_copy_op(), OPERAND::next, and NULL.
gen_copy_op()
OPERAND * gen_copy_op (OPERAND * op)
...
Definition at line 2716 of file llutil.cpp.
References make_operand(), OPERAND::next, and NULL.
Referenced by find_load_cse(), gen_abs_expr(), gen_call_expr(), gen_copy_list_op(), gen_copy_operand(), gen_llvm_expr(), gen_minmax_expr(), gen_va_arg(), make_bitcast(), and x86_promote_to_vector().
generic_dummy_dtype()
DTYPE generic_dummy_dtype (void)
...
Definition at line 901 of file llutil.cpp.
References TARGET_PTRSIZE.
Referenced by DeclareSPtrAsLocal(), ll_process_routine_parameters(), and make_generic_dummy_lltype().
get_current_module()
LL_Module * get_current_module (void)
get_dim_size()
int get_dim_size (ADSC * ad, int dim)
...
Definition at line 868 of file llutil.cpp.
References AD_LWBD, AD_UPBD, ad_val_of(), and dim.
Referenced by ll_convert_array_dtype().
get_dtype_for_vect_type_nme()
DTYPE get_dtype_for_vect_type_nme (int nme)
...
...
If the DT_ value can't be determined, returns DT_NONE.
Definition at line 1080 of file llutil.cpp.
References assert, basesym_of(), DT_DBLE, DT_FLOAT, DT_INT, DTY, DTySeqTyElement, ERR_Fatal, size_of(), and SPTR_NULL.
get_dtype_from_arg_opc()
DTYPE get_dtype_from_arg_opc (ILI_OP opc)
...
...
Definition at line 965 of file llutil.cpp.
References DT_CPTR, DT_DBLE, DT_FLOAT, and DT_INT.
Referenced by gen_arg_operand().
get_dtype_from_tytype()
DTYPE get_dtype_from_tytype (TY_KIND ty)
...
...
If the TY type isn't a basic type, returns DT_NONE.
Definition at line 1003 of file llutil.cpp.
References assert, DT_CMPLX, DT_CPTR, DT_DBLE, DT_DCMPLX, DT_INT, DT_LOG, DT_REAL, ERR_Fatal, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
get_ftn_cbind_lltype()
LL_Type * get_ftn_cbind_lltype (SPTR sptr)
...
Definition at line 4190 of file llutil.cpp.
References AD_DPTR, AD_NUMDIM, AD_NUMELM, ad_val_of(), assert, d, DTY, DTyAlgTyTag, DTySeqTyElement, ERR_Fatal, find_ag(), get_ag_lltype(), get_ftn_func_lltype(), get_ftn_static_lltype(), get_typedef_ag(), STB::i1, is_function(), ISZ_T, STB::k1, make_array_lltype(), make_lltype_from_dtype(), MXIDLN, name, NULL, process_dtype_struct(), set_ag_lltype(), sptr, stb, SYMNAME, tname, and XBIT.
Referenced by get_ftn_extern_lltype(), and make_lltype_from_sptr().
get_ftn_cmblk_lltype()
LL_Type * get_ftn_cmblk_lltype (SPTR sptr)
...
Definition at line 4099 of file llutil.cpp.
References assert, ERR_Fatal, find_ag(), get_ag_lltype(), get_llvm_name(), get_typedef_ag(), LLTYPE, make_lltype_from_dtype(), MXIDLN, name, NULL, set_ag_lltype(), SNAME, sptr, and tname.
Referenced by get_ftn_lltype(), and make_lltype_from_sptr().
get_ftn_dummy_lltype()
LL_Type * get_ftn_dummy_lltype (int sptr)
...
Definition at line 4277 of file llutil.cpp.
References currsub_is_sret(), gbl, GBL_CURRFUNC, LLTYPE, make_generic_dummy_lltype(), make_lltype_from_dtype(), make_ptr_lltype(), and sptr.
Referenced by make_lltype_from_sptr().
get_ftn_extern_lltype()
LL_Type * get_ftn_extern_lltype (SPTR sptr)
...
Definition at line 4176 of file llutil.cpp.
References assert, ERR_Fatal, get_ftn_cbind_lltype(), get_ftn_func_lltype(), get_ftn_typedesc_lltype(), is_function(), make_lltype_from_dtype(), and sptr.
Referenced by get_ftn_lltype(), and write_externs().
get_ftn_func_lltype()
LL_Type * get_ftn_func_lltype (SPTR sptr)
...
Definition at line 4259 of file llutil.cpp.
References assert, DT_CPTR, ERR_Fatal, get_iface_sptr(), IS_FTN_PROC_PTR, is_function(), ll_abi_for_func_sptr(), ll_abi_function_type(), llvm_get_current_module(), make_lltype_from_dtype(), make_lltype_from_iface(), NULL, and sptr.
Referenced by get_ftn_cbind_lltype(), get_ftn_extern_lltype(), and get_ftn_static_lltype().
get_ftn_hollerith_type()
LL_Type * get_ftn_hollerith_type (int sptr)
...
Definition at line 4309 of file llutil.cpp.
References DTY, DTyCharLength, get_hollerith_size(), get_type(), len, LLTYPE, make_lltype_from_dtype(), NULL, sptr, TY_CHAR, and TY_NCHAR.
Referenced by make_lltype_from_sptr().
get_ftn_static_lltype()
LL_Type * get_ftn_static_lltype (SPTR sptr)
...
Definition at line 4041 of file llutil.cpp.
References AG_LLTYPE, AG_STYPE, assert, CUDAG, DDTG, ERR_Fatal, gbl, get_ag_lltype(), get_ftn_func_lltype(), get_ftn_typedesc_lltype(), get_llvm_name(), get_typedef_ag(), getsname(), IS_FTN_PROC_PTR, is_function(), make_lltype_from_dtype(), make_ptr_lltype(), mk_struct_for_llvm_init(), MXIDLN, name, NULL, set_ag_lltype(), sptr, tname, and TY_CHAR.
Referenced by get_ftn_cbind_lltype(), get_ftn_lltype(), and make_lltype_from_sptr().
get_ftn_typedesc_lltype()
LL_Type * get_ftn_typedesc_lltype (SPTR sptr)
...
Definition at line 4143 of file llutil.cpp.
References AG_DEFD, assert, ERR_Fatal, find_ag(), get_ag(), get_ag_lltype(), get_ftn_typedesc_dtype(), get_typedef_ag(), getsname(), make_lltype_from_dtype(), MXIDLN, name, NULL, set_ag_lltype(), sptr, and tname.
Referenced by get_ftn_extern_lltype(), get_ftn_static_lltype(), and make_lltype_from_sptr().
get_int_dtype_from_size()
DTYPE get_int_dtype_from_size (int size)
...
Definition at line 3092 of file llutil.cpp.
References DT_INT, and size.
Referenced by process_symlinked_sptr().
get_ot_name()
const char * get_ot_name (unsigned ot)
...
Definition at line 46 of file llutil.cpp.
References OT_LAST, and ot_names.
get_param_equiv_dtype()
DTYPE get_param_equiv_dtype (DTYPE dtype)
...
Definition at line 2601 of file llutil.cpp.
References DT_INT, DTY, and ZSIZEOF.
get_return_dtype()
DTYPE get_return_dtype (DTYPE dtype, unsigned * flags, unsigned new_flag)
...
Definition at line 2563 of file llutil.cpp.
References assert, DT_INT, DT_ISCMPLX, DT_SBYTE, DT_VOID_NONE, DTY, ERR_Fatal, flags, is_struct_kind(), small_aggr_return(), TY_CMPLX, XBIT, and ZSIZEOF.
Referenced by process_extern_function_sptr(), and write_externs().
get_struct_def_type()
LL_Type * get_struct_def_type (char * def_name, LL_Module * module)
...
indent()
void indent (int change)
...
Definition at line 2537 of file llutil.cpp.
References i, indentlev, and ll_dfile.
init_metadata_index()
void init_metadata_index (TMPS * t)
...
...
Definition at line 2501 of file llutil.cpp.
References DBGTRACEIN1, DBGTRACEOUT1, metadata_id, and t.
init_output_file()
void init_output_file (void)
...
Definition at line 1690 of file llutil.cpp.
References FTN_HAS_INIT, gbl, ll_write_module_header(), llvm_get_current_module(), and set_llasm_output_file().
Referenced by cg_llvm_init(), and write_module_as_subroutine().
is_function()
bool is_function (int sptr)
...
Definition at line 1199 of file llutil.cpp.
References IS_FTN_PROC_PTR, and sptr.
Referenced by get_ftn_cbind_lltype(), get_ftn_extern_lltype(), get_ftn_func_lltype(), get_ftn_static_lltype(), and make_lltype_from_sptr().
is_struct_kind()
int is_struct_kind (DTYPE dtype, bool check_return, bool return_vector_as_struct)
...
Definition at line 815 of file llutil.cpp.
References check_return(), DTY, TY_CMPLX, and TY_DCMPLX.
Referenced by get_return_dtype(), and ll_process_routine_parameters().
layout_struct_body()
void layout_struct_body (LL_Module * module, LL_Type * struct_type, int member_sptr, ISZ_T size_bytes)
...
...
This code can layout both struct/union dtypes and common blocks.
The provided struct_type should be created with ll_create_named_struct_type().
Padding will be added to make the size of the new struct size_bytes, unless size_bytes is -1 which is ignored.
Definition at line 406 of file llutil.cpp.
References alignment(), assert, cp, DDTG, DTY, ERR_Fatal, extent_of(), ISZ_T, ll_convert_dtype(), ll_create_basic_type(), ll_get_array_type(), ll_get_pointer_type(), LL_I8, ll_set_struct_body(), ll_type_bytes(), malloc(), NOSYM, NULL, sptr, and ZSIZEOF.
Referenced by ll_convert_struct_dtype().
ldst_instr_flags_from_dtype()
LL_InstrListFlags ldst_instr_flags_from_dtype (DTYPE dtype)
...
...
Parameters
dtype The DTYPE
The flags encode alignment in the LDST_LOGALIGN_MASK bits and volatile types have the VOLATILE_FLAG bit set.
The returned flags are pre-shifted so they can be or'ed onto the instruction flags.
Definition at line 223 of file llutil.cpp.
References alignment(), DTY, flags, LDST_LOGALIGN_SHIFT, and VOLATILE_FLAG.
Referenced by gen_arg_operand(), gen_call_expr(), gen_llvm_expr(), gen_return_operand(), gen_va_arg(), insert_jump_entry_instr(), ldst_instr_flags_from_dtype_nme(), make_stmt(), and process_formal_arguments().
ldst_instr_flags_from_dtype_nme()
LL_InstrListFlags ldst_instr_flags_from_dtype_nme (DTYPE dtype, int nme)
...
...
Parameters
dtype The DTYPE
nme The NME
The flags encode alignment in the LDST_LOGALIGN_MASK bits and the nme NME_VOL has the VOLATILE_FLAG bit set.
The returned flags are pre-shifted so they can be or'ed onto the instruction flags.
Definition at line 261 of file llutil.cpp.
References flags, ldst_instr_flags_from_dtype(), NME_VOL, and VOLATILE_FLAG.
Referenced by gen_llvm_expr().
ll_abi_alloc()
LL_ABI_Info * ll_abi_alloc (struct LL_Module * module, unsigned nargs)
...
Definition at line 3605 of file llutil.cpp.
References LL_ABI_Info_::module, nargs, and LL_ABI_Info_::nargs.
Referenced by add_external_function_declaration(), ll_abi_for_missing_prototype(), ll_add_func_proto(), ll_process_routine_parameters(), and process_ll_abi_func_ftn_mod().
ll_abi_complete_arg_info()
void ll_abi_complete_arg_info (LL_ABI_Info * abi, LL_ABI_ArgInfo * arg, DTYPE dtype)
...
Definition at line 3675 of file llutil.cpp.
References arg, assert, ERR_Fatal, kind, LL_ARG_BYVAL, LL_ARG_COERCE, LL_ARG_INDIRECT, LL_ARG_INDIRECT_BUFFERED, ll_convert_dtype(), ll_get_pointer_type(), LL_VOID, LL_ABI_Info_::module, and type.
Referenced by gen_arg_operand(), ll_abi_for_missing_prototype(), ll_process_routine_parameters(), and process_ll_abi_func_ftn_mod().
ll_abi_compute_call_conv()
void ll_abi_compute_call_conv (LL_ABI_Info * abi, int func_sptr, int jsra_flags)
Definition at line 26 of file aarch64/ll_abi.cpp.
ll_abi_for_func_sptr()
LL_ABI_Info * ll_abi_for_func_sptr (LL_Module * module, SPTR func_sptr, DTYPE dtype)
Get ABI lowering info for a function given its symbol table entry.
Since IPA can change the dtype of functions between calls to schedule(), use the passed dtype instead of DTYPEG(func_sptr).
Definition at line 3879 of file llutil.cpp.
References process_ll_abi_func_ftn_mod().
Referenced by add_external_function_declaration(), get_ftn_func_lltype(), ll_abi_from_call_site(), ll_check_struct_return(), make_lltype_from_sptr(), and schedule().
ll_abi_free()
LL_ABI_Info * ll_abi_free (LL_ABI_Info * abi)
...
Definition at line 3616 of file llutil.cpp.
References assert, ERR_Fatal, LL_ABI_Info_::nargs, and NULL.
Referenced by ll_process_routine_parameters(), and process_ll_abi_func_ftn_mod().
ll_abi_from_call_site()
LL_ABI_Info * ll_abi_from_call_site (LL_Module * module, int ilix, DTYPE ret_dtype)
Get ABI lowering info for a specific call site.
ilix is the IL_JSR or IL_JSRA instruction representing the call.
ret_ili is the IL_DFRx instruction extracting the return value for the call, or 0 if the return value is unused.
This may not provide lowering information for all function arguments if the callee is varargs or if a prototype is not available.
Definition at line 3885 of file llutil.cpp.
References ERR_Fatal, find_ag(), get_llvm_funcptr_ag(), get_llvm_ifacenm(), get_llvm_name(), ILI_DTyOPND, ILI_OPC, ILI_OPND, ILI_SymOPND, interr(), ll_abi_for_func_sptr(), and ll_abi_for_missing_prototype().
Referenced by gen_call_expr().
ll_abi_function_type()
const struct LL_Type_ * ll_abi_function_type (LL_ABI_Info * abi)
...
Definition at line 3648 of file llutil.cpp.
References LL_ABI_Info_::arg, i, LL_ABI_HAS_SRET, ll_abi_use_llvm_varargs(), ll_create_basic_type(), ll_create_function_type(), LL_VOID, LL_ABI_Info_::module, LL_ABI_Info_::nargs, and LL_ABI_ArgInfo_::type.
Referenced by gen_call_expr(), get_ftn_func_lltype(), make_lltype_from_sptr(), schedule(), write_final_table(), and write_vft().
ll_abi_return_type()
const struct LL_Type_ * ll_abi_return_type (LL_ABI_Info * abi)
...
Definition at line 3627 of file llutil.cpp.
References LL_ABI_Info_::arg, LL_ABI_HAS_SRET, ll_create_basic_type(), LL_VOID, LL_ABI_Info_::module, and LL_ABI_ArgInfo_::type.
Referenced by gen_call_expr().
ll_abi_use_llvm_varargs()
bool ll_abi_use_llvm_varargs (LL_ABI_Info * abi)
Should this function be represented as a varags LLVM function type?
Definition at line 3636 of file llutil.cpp.
References LL_ABI_Info_::call_as_varargs, LL_ABI_Info_::is_varargs, and LL_ABI_Info_::missing_prototype.
Referenced by ll_abi_function_type(), and print_function_signature().
ll_add_func_proto()
void ll_add_func_proto (int sptr, unsigned flags, int nargs, DTYPE * args)
Add a function prototype declaration to the LLVM module.
Parameters
sptr The symbol of the function
nargs Number of arguments to the function
args An array of DTYPEs for the arguments
Definition at line 187 of file llutil.cpp.
References LL_ABI_Info_::arg, args, LL_ABI_Info_::fast_math, FAST_MATH_FLAG, flags, i, LL_ABI_Info_::is_fortran, LL_ABI_Info_::is_iso_c, LL_ABI_Info_::is_pure, LL_ABI_ArgInfo_::kind, ll_abi_alloc(), LL_ARG_DIRECT, ll_create_function_type(), ll_proto_add(), ll_proto_init(), llvm_get_current_module(), make_lltype_from_dtype(), malloc(), nargs, sptr, SYMNAME, and LL_ABI_ArgInfo_::type.
Referenced by vmk_prototype().
ll_coercion_type()
LL_Type * ll_coercion_type (LL_Module * module, DTYPE dtype, ISZ_T size, ISZ_T reg_size)
Definition at line 4361 of file llutil.cpp.
References BITS_IN_BYTE, LL_AddrSp_Default, ll_create_anon_struct_type(), ll_create_int_type(), ll_get_array_type(), LL_Type_::module, NULL, and size.
Referenced by classify_common(), ll_abi_classify_arg_dtype(), and ll_abi_classify_return_dtype().
ll_convert_array_dtype()
LL_Type * ll_convert_array_dtype (LL_Module * module, DTYPE dtype, int addrspace)
...
...
This routine obtains the length information via the array descriptor.
Definition at line 591 of file llutil.cpp.
References AD_DPTR, AD_NUMDIM, AD_NUMELM, LLDEF::addrspace, assert, ddtype(), DTY, DTyCharLength, DTySeqTyElement, ERR_Fatal, ERR_unused, get_bnd_cval(), get_dim_size(), i, interr(), len, ll_convert_dtype(), ll_get_array_type(), NULL, TY_CHAR, TY_NCHAR, and type.
Referenced by convert_dtype().
ll_convert_dtype()
LL_Type * ll_convert_dtype (LL_Module * module, DTYPE dtype)
...
...
Definition at line 700 of file llutil.cpp.
References convert_dtype().
Referenced by add_external_function_declaration(), layout_struct_body(), ll_abi_classify_arg_dtype(), ll_abi_complete_arg_info(), ll_convert_array_dtype(), ll_convert_iface_sptr(), and update_homogeneous().
ll_instr_flags_from_aop()
LL_InstrListFlags ll_instr_flags_from_aop (ATOMIC_RMW_OP aop)
Compute the LL_InstrListFlag set from an ATOMIC_RMW_OP.
Parameters
aop an ATOMIC_RMW_OP value
Definition at line 4334 of file llutil.cpp.
References AOP_ADD, AOP_AND, AOP_MAX, AOP_MIN, AOP_OR, AOP_SUB, AOP_XCHG, AOP_XOR, assert, ATOMIC_ADD_FLAG, ATOMIC_AND_FLAG, ATOMIC_MAX_FLAG, ATOMIC_MIN_FLAG, ATOMIC_OR_FLAG, ATOMIC_SUB_FLAG, ATOMIC_XCHG_FLAG, ATOMIC_XOR_FLAG, ERR_Fatal, and InstrListFlagsNull.
Referenced by gen_llvm_atomicrmw_expr().
ll_override_type_string()
void ll_override_type_string (LL_Type * llt, const char * str)
...
Definition at line 3974 of file llutil.cpp.
Referenced by process_ftn_dtype_struct().
llis_array_kind()
bool llis_array_kind (DTYPE dtype)
Definition at line 757 of file llutil.cpp.
References DTY, TY_CHAR, and TY_NCHAR.
Referenced by llis_dummied_arg(), and make_lltype_from_sptr().
llis_dummied_arg()
bool llis_dummied_arg (SPTR sptr)
...
Definition at line 771 of file llutil.cpp.
References llis_array_kind(), llis_pointer_kind(), and sptr.
Referenced by process_formal_arguments().
llis_function_kind()
bool llis_function_kind (DTYPE dtype)
Definition at line 803 of file llutil.cpp.
References DTY.
Referenced by make_lltype_from_sptr().
llis_integral_kind()
bool llis_integral_kind (DTYPE dtype)
Definition at line 715 of file llutil.cpp.
References DTY, TY_BINT, TY_BLOG, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by make_lltype_from_sptr().
llis_pointer_kind()
bool llis_pointer_kind (DTYPE dtype)
Definition at line 751 of file llutil.cpp.
References DTY.
Referenced by llis_dummied_arg(), and make_lltype_from_sptr().
llis_struct_kind()
bool llis_struct_kind (DTYPE dtype)
Definition at line 784 of file llutil.cpp.
References DTY, TY_CMPLX, and TY_DCMPLX.
Referenced by make_lltype_from_sptr().
llis_vector_kind()
bool llis_vector_kind (DTYPE dtype)
Definition at line 778 of file llutil.cpp.
References DTY.
Referenced by make_lltype_from_sptr().
llutil_def_reset()
void llutil_def_reset (void)
...
Definition at line 148 of file llutil.cpp.
References llutil_gblvar_def_reset(), and llutil_struct_def_reset().
llutil_dfile_init()
void llutil_dfile_init (void)
...
Definition at line 155 of file llutil.cpp.
References gbl, and ll_dfile.
llutil_gblvar_def_reset()
void llutil_gblvar_def_reset (void)
...
Definition at line 141 of file llutil.cpp.
References gblvar_def_list, and NULL.
Referenced by llutil_def_reset().
llutil_strdup()
const char * llutil_strdup (const char * str)
...
Definition at line 171 of file llutil.cpp.
References llutil_alloc(), p, str, and strlen().
Referenced by llvm_add_to_init_list().
llutil_struct_def_reset()
void llutil_struct_def_reset (void)
...
Definition at line 134 of file llutil.cpp.
References NULL, and struct_def_list.
Referenced by cg_llvm_fnend(), and llutil_def_reset().
llvm_fc_type()
const char * llvm_fc_type (DTYPE dtype)
...
...
Definition at line 2623 of file llutil.cpp.
References assert, DBGTRACE2, DTY, ERR_Fatal, ISZ_T, size_of(), stb, sz, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, TY_SLOG, TY_WORD, and STB::tynames.
Referenced by gen_constant(), and write_constant_value().
llvm_file()
FILE * llvm_file (void)
...
Definition at line 1787 of file llutil.cpp.
References LLVMFIL.
Referenced by cg_llvm_end(), and schedule().
llvm_get_current_module()
LL_Module * llvm_get_current_module (void)
Definition at line 125 of file llutil.cpp.
References cpu_llvm_module.
Referenced by get_ftn_func_lltype(), init_output_file(), ll_add_func_proto(), lltype_from_dtype(), make_int_lltype(), make_lltype_from_iface(), make_lltype_from_sptr(), make_void_lltype(), metadata_args_need_struct(), process_dtype_struct(), process_ll_abi_func_ftn(), and process_symlinked_sptr().
llvm_set_acc_module()
void llvm_set_acc_module (void)
set the module as gpu/cpu module
Definition at line 113 of file llutil.cpp.
References is_gpu_module.
llvm_set_cpu_module()
void llvm_set_cpu_module (void)
Definition at line 119 of file llutil.cpp.
References is_gpu_module.
make_array_lltype()
LL_Type * make_array_lltype (int size, LL_Type * pts_to)
...
Definition at line 862 of file llutil.cpp.
References LL_AddrSp_Default, ll_get_array_type(), and size.
Referenced by assign_array_lltype(), get_ftn_cbind_lltype(), get_local_overlap_size(), and write_final_table().
make_constsptr_op()
OPERAND * make_constsptr_op (SPTR sptr)
...
Definition at line 1397 of file llutil.cpp.
References assert, ERR_Fatal, OPERAND::ll_type, make_lltype_from_dtype(), make_operand(), OT_CONSTSPTR, OPERAND::ot_type, sptr, OPERAND::sptr, and OPERAND::val.
Referenced by gen_switch(), and make_param_op().
make_constval32_op()
OPERAND * make_constval32_op (int idx)
...
Definition at line 1475 of file llutil.cpp.
References DT_INT, idx, make_constval_op(), and make_lltype_from_dtype().
Referenced by gen_extract_value_ll(), gen_extract_vector(), gen_gep_index(), gen_insert_value(), gen_insert_vector(), gen_llvm_cmpxchg_component(), gen_switch(), insert_llvm_memcpy(), and insert_llvm_memset().
make_constval_op()
OPERAND * make_constval_op (LL_Type * ll_type, INT conval0, INT conval1)
...
Definition at line 1444 of file llutil.cpp.
References OPERAND::conval, LLDEF::ll_type, OPERAND::ll_type, make_operand(), OT_CONSTVAL, OPERAND::ot_type, and OPERAND::val.
Referenced by gen_acon_expr(), gen_base_addr_operand(), gen_llvm_expr(), gen_mulh_expr(), gen_va_arg(), insert_llvm_dbg_value(), insert_llvm_memcpy(), insert_llvm_memset(), insert_llvm_prefetch(), make_constval32_op(), and make_param_op().
make_constval_opL()
OPERAND * make_constval_opL (LL_Type * ll_type, INT conval0, INT conval1, INT conval2, INT conval3)
...
Definition at line 1458 of file llutil.cpp.
References OPERAND::conval, LLDEF::ll_type, OPERAND::ll_type, make_operand(), OT_CONSTVAL, OPERAND::ot_type, and OPERAND::val.
Referenced by gen_llvm_expr().
make_def_op()
OPERAND * make_def_op (char * str)
...
Definition at line 1552 of file llutil.cpp.
References make_operand(), OT_DEF, OPERAND::ot_type, str, and OPERAND::string.
make_generic_dummy_lltype()
LL_Type * make_generic_dummy_lltype (void)
...
Definition at line 910 of file llutil.cpp.
Referenced by get_ftn_dummy_lltype(), and make_lltype_from_sptr().
make_int_lltype()
LL_Type * make_int_lltype (unsigned bits)
...
Definition at line 844 of file llutil.cpp.
References bits, ll_create_int_type(), and llvm_get_current_module().
Referenced by attempt_gep_folding(), gen_abs_expr(), gen_acon_expr(), gen_base_addr_operand(), gen_binary_expr(), gen_llvm_expr(), gen_minmax_expr(), gen_mulh_expr(), gen_optext_comp_operand(), gen_select_expr(), gen_switch(), gen_va_arg(), gen_vect_compare_operand(), insert_jump_entry_instr(), insert_llvm_memcpy(), insert_llvm_memset(), insert_llvm_prefetch(), make_stmt(), sign_extend_int(), and zero_extend_int().
make_label_op()
OPERAND * make_label_op (SPTR sptr)
...
Definition at line 1662 of file llutil.cpp.
References get_label_name(), make_operand(), OT_LABEL, OPERAND::ot_type, process_sptr(), sptr, OPERAND::sptr, OPERAND::string, and OPERAND::val.
Referenced by gen_call_expr(), insert_entry_label(), insert_jump_entry_instr(), make_stmt(), and schedule().
make_lltype_from_abi_arg()
LL_Type * make_lltype_from_abi_arg (LL_ABI_ArgInfo * arg)
...
Definition at line 3935 of file llutil.cpp.
References arg.
Referenced by analyze_ret_info(), gen_arg_operand(), gen_call_expr(), ll_process_routine_parameters(), print_entry_subroutine(), and process_formal_arguments().
make_lltype_from_arg()
LL_Type * make_lltype_from_arg (int arg)
...
Definition at line 926 of file llutil.cpp.
References assert, and ERR_Fatal.
make_lltype_from_arg_noproto()
LL_Type * make_lltype_from_arg_noproto (int arg)
...
Definition at line 937 of file llutil.cpp.
References arg, DBGTRACEOUT2, DTY, IL_RES, ILI_DTyOPND, ILI_OPC, ILI_OPND, ILIA_AR, make_lltype_from_dtype(), make_ptr_lltype(), and LL_Type_::str.
make_lltype_from_dtype()
LL_Type * make_lltype_from_dtype (DTYPE dtype)
...
Definition at line 889 of file llutil.cpp.
References lltype_from_dtype().
Referenced by add_def(), addDebugForGlobalVar(), analyze_ret_info(), assign_array_lltype(), char_type(), cleanup_unneeded_sincos_calls(), complex_result_type(), DeclareSPtrAsLocal(), fixup_x86_abi_return(), gen_acon_expr(), gen_address_operand(), gen_alloca_call_if_necessary(), gen_arg_operand(), gen_base_addr_operand(), gen_binary_expr(), gen_bitcast_vector(), gen_call_vminmax_intrinsic(), gen_call_vminmax_neon_intrinsic(), gen_call_vminmax_power_intrinsic(), gen_cmplx_math(), gen_cmplx_mul(), gen_const_expr(), gen_convert_vector(), gen_eval_cmplx_value(), gen_extract_insert(), gen_extract_value(), gen_llvm_atomic_intrinsic_for_builtin(), gen_llvm_expr(), gen_llvm_sincos_call(), gen_llvm_vsincos_call(), gen_minmax_expr(), gen_optext_comp_operand(), gen_ref_arg(), gen_return_operand(), gen_sret_expr(), gen_unary_expr(), gen_va_arg(), gen_va_end(), gen_va_start(), gen_vect_compare_operand(), generate_struct_dtype(), get_ftn_cbind_lltype(), get_ftn_cmblk_lltype(), get_ftn_dummy_lltype(), get_ftn_extern_lltype(), get_ftn_func_lltype(), get_ftn_hollerith_type(), get_ftn_static_lltype(), get_ftn_typedesc_lltype(), get_local_overlap_size(), insert_entry_label(), insert_jump_entry_instr(), ll_add_func_proto(), ll_process_routine_parameters(), lldbg_function_end(), make_constsptr_op(), make_conststring_op(), make_constval32_op(), make_gblsym(), make_generic_dummy_lltype(), make_lltype_from_arg_noproto(), make_lltype_from_sptr(), make_lltype_sz4v3_from_dtype(), make_load(), make_member_op(), make_param_op(), make_stmt(), make_type_from_opc(), make_uplevel_arg_struct(), make_vtype(), maybe_do_gep_folding(), maybe_generate_fma(), print_entry_subroutine(), print_function_signature(), process_extern_function_sptr(), process_params(), process_sptr_offset(), schedule(), write_constant_value(), write_def(), write_extern_inits(), write_final_table(), write_I_CALL(), write_instructions(), write_module_as_subroutine(), write_operand(), and write_typedescs().
make_lltype_from_dtype_with_addrspace()
LL_Type * make_lltype_from_dtype_with_addrspace (DTYPE dtype, int addrspace)
...
Definition at line 895 of file llutil.cpp.
References LLDEF::addrspace, and lltype_from_dtype().
Referenced by make_lltype_from_sptr(), and make_type_from_msz_with_addrspace().
make_lltype_from_iface()
LL_Type * make_lltype_from_iface (SPTR sptr)
...
Definition at line 1188 of file llutil.cpp.
References ll_convert_iface_sptr(), llvm_get_current_module(), and sptr.
Referenced by get_ftn_func_lltype(), and make_lltype_from_sptr().
make_lltype_from_sptr()
LL_Type * make_lltype_from_sptr (SPTR sptr)
...
...
Parameters
sptr a symbol
Definition at line 1219 of file llutil.cpp.
References AD_DPTR, AD_NUMELM, ad_val_of(), add_def(), LLDEF::addrspace, assert, CUDA_DEVICE, CUDA_GLOBAL, CUDAG, d, LL_Type_::data_type, DBGDUMPLLTYPE, DBGTRACE1, DBGTRACEIN7, DBGTRACEOUT1, DDTG, def, DT_CPTR, DTY, DTySeqTyElement, ERR_Fatal, gbl, get_ftn_cbind_lltype(), get_ftn_cmblk_lltype(), get_ftn_dummy_lltype(), get_ftn_hollerith_type(), get_ftn_static_lltype(), get_ftn_typedesc_lltype(), get_iface_sptr(), get_local_overlap_vartype(), STB::i1, IS_FTN_PROC_PTR, is_function(), STB::k1, ll_abi_for_func_sptr(), ll_abi_function_type(), LL_AddrSp_Default, LL_AddrSp_NVVM_Generic, LL_AddrSp_NVVM_Shared, LL_ARRAY, ll_convert_dtype_with_addrspace(), ll_create_basic_type(), ll_create_int_type(), ll_get_array_type(), ll_get_pointer_type(), LL_LABEL, LL_PTR, LL_VOID, llarray_def_list, llis_array_kind(), llis_function_kind(), llis_integral_kind(), llis_pointer_kind(), llis_struct_kind(), llis_vector_kind(), llutil_alloc(), llvm_get_current_module(), make_generic_dummy_lltype(), make_lltype_from_dtype(), make_lltype_from_dtype_with_addrspace(), make_lltype_from_iface(), make_ptr_lltype(), need_ptr(), process_dtype_struct(), sptr, stb, STB::stypes, LL_Type_::sub_types, SYMNAME, TY_CHAR, TY_NCHAR, STB::tynames, XBIT, and ZSIZEOF.
Referenced by add_global_define(), addDebugForGlobalVar(), char_type(), gen_address_operand(), gen_const_expr(), get_struct_from_dsrt2(), ll_write_local_objects(), lldbg_emit_type(), make_arg_op(), make_gblsym(), make_lltype_sz4v3_from_sptr(), and make_var_op().
make_lltype_sz4v3_from_dtype()
LL_Type * make_lltype_sz4v3_from_dtype (DTYPE dtype)
...
Definition at line 1509 of file llutil.cpp.
References make_lltype_from_dtype(), and set_vect3_to_size4().
Referenced by make_stmt().
make_lltype_sz4v3_from_sptr()
LL_Type * make_lltype_sz4v3_from_sptr (SPTR sptr)
...
Definition at line 1502 of file llutil.cpp.
References make_lltype_from_sptr(), set_vect3_to_size4(), and sptr.
Referenced by process_blockaddr_sptr(), and process_sptr_offset().
make_mdref_op()
OPERAND * make_mdref_op (LL_MDRef mdref)
...
Definition at line 1618 of file llutil.cpp.
References assert, ERR_Fatal, TMP_TAG::id, LL_MDREF_kind, LL_MDREF_value, make_operand(), make_tmps(), MDRef_Node, OT_MDNODE, OPERAND::ot_type, and OPERAND::tmps.
Referenced by cons_expression_metadata_operand(), insert_llvm_dbg_declare(), insert_llvm_dbg_value(), and lldbg_create_deferred_len_string_type_mdnode().
make_metadata_wrapper_op()
OPERAND * make_metadata_wrapper_op (SPTR sptr, LL_Type * llTy)
Create metadata operand that wraps an LLVM value.
For example, metadata !{i32 x}. Used by llvm.dbg.declare intrinsic.
Definition at line 1633 of file llutil.cpp.
References OPERAND::ll_type, make_operand(), OT_MDNODE, OPERAND::ot_type, process_sptr(), sptr, OPERAND::sptr, and OPERAND::val.
Referenced by insert_llvm_dbg_declare().
make_null_op()
OPERAND * make_null_op (LL_Type * llt)
...
Definition at line 1603 of file llutil.cpp.
References assert, LL_Type_::data_type, ERR_Fatal, OPERAND::flags, LL_PTR, OPERAND::ll_type, make_operand(), OPF_NULL_TYPE, OT_CONSTVAL, and OPERAND::ot_type.
Referenced by gen_const_expr().
make_operand()
OPERAND * make_operand (void)
...
Definition at line 1677 of file llutil.cpp.
References llutil_alloc().
Referenced by gen_abs_expr(), gen_call_expr(), gen_const_expr(), gen_copy_op(), gen_extract_insert(), gen_imask(), gen_llvm_expr(), gen_minmax_expr(), gen_optext_comp_operand(), gen_resized_vect(), gen_return_operand(), gen_sptr(), gen_sret_expr(), gen_va_end(), gen_va_start(), gen_vect_compare_operand(), get_intrinsic(), insert_jump_entry_instr(), insert_llvm_dbg_declare(), insert_llvm_dbg_value(), insert_llvm_memcpy(), insert_llvm_memset(), insert_llvm_prefetch(), lldbg_emit_type(), make_arg_op(), make_constsptr_op(), make_conststring_op(), make_constval_op(), make_constval_opL(), make_def_op(), make_label_op(), make_mdref_op(), make_member_op_with_lltype(), make_metadata_wrapper_op(), make_null_op(), make_target_op(), make_tmp_op(), make_undef_op(), make_var_op(), process_formal_arguments(), and process_params().
make_ptr_lltype()
LL_Type * make_ptr_lltype (LL_Type * pts_to)
...
Definition at line 838 of file llutil.cpp.
References ll_get_pointer_type().
Referenced by gen_acon_expr(), gen_address_operand(), gen_arg_operand(), gen_base_addr_operand(), gen_call_expr(), gen_llvm_atomicrmw_expr(), gen_llvm_cmpxchg(), gen_llvm_expr(), gen_ref_arg(), gen_return_operand(), gen_va_arg(), get_ftn_dummy_lltype(), get_ftn_static_lltype(), get_intrinsic(), make_generic_dummy_lltype(), make_lltype_from_arg_noproto(), make_lltype_from_sptr(), make_stmt(), print_entry_subroutine(), process_extern_function_sptr(), process_sptr_offset(), store_return_value_for_entry(), write_final_table(), and write_operand().
make_target_op()
OPERAND * make_target_op (SPTR sptr)
...
Definition at line 1647 of file llutil.cpp.
References get_label_name(), make_operand(), OT_TARGET, OPERAND::ot_type, process_sptr(), sptr, OPERAND::sptr, OPERAND::string, and OPERAND::val.
Referenced by gen_switch(), insert_jump_entry_instr(), and make_stmt().
make_tmp_op()
OPERAND * make_tmp_op (LL_Type * llt, TMPS * tmps)
...
Definition at line 1580 of file llutil.cpp.
References OPERAND::ll_type, make_operand(), OT_TMP, OPERAND::ot_type, and OPERAND::tmps.
Referenced by ad_csed_instr(), convert_float_size(), convert_operand(), find_load_cse(), fused_multiply_add_canonical_form(), gen_abs_expr(), gen_call_expr(), gen_call_to_builtin(), gen_extract_insert(), gen_extract_value_ll(), gen_extract_vector(), gen_insert_vector(), gen_llvm_expr(), gen_llvm_instr(), gen_minmax_expr(), gen_resized_vect(), gen_scalar_to_vector_helper(), gen_select_expr(), insert_jump_entry_instr(), make_bitcast(), make_load(), make_stmt(), mk_alloca_instr(), and set_csed_operand().
make_tmps()
TMPS * make_tmps (void)
...
...
Definition at line 181 of file llutil.cpp.
References llutil_alloc().
Referenced by ad_csed_instr(), convert_float_size(), convert_int_size(), convert_operand(), fused_multiply_add_canonical_form(), gen_abs_expr(), gen_call_expr(), gen_call_to_builtin(), gen_extract_insert(), gen_extract_value_ll(), gen_extract_vector(), gen_insert_vector(), gen_llvm_expr(), gen_llvm_instr(), gen_minmax_expr(), gen_optext_comp_operand(), gen_resized_vect(), gen_scalar_to_vector_helper(), gen_select_expr(), gen_vect_compare_operand(), insert_jump_entry_instr(), make_bitcast(), make_load(), make_mdref_op(), make_stmt(), mk_alloca_instr(), print_entry_subroutine(), and store_return_value_for_entry().
make_undef_op()
OPERAND * make_undef_op (LL_Type * llt)
...
Definition at line 1592 of file llutil.cpp.
References OPERAND::ll_type, make_operand(), OPERAND::ot_type, and OT_UNDEF.
Referenced by fixup_recip_div(), gen_cmplx_math(), gen_cmplx_mul(), gen_extract_insert(), gen_llvm_expr(), gen_return_operand(), gen_scalar_to_vector_helper(), gen_scalar_to_vector_no_shuffle(), gen_unreachable_if_necessary(), and x86_promote_to_vector().
make_var_op()
OPERAND * make_var_op (SPTR sptr)
...
Definition at line 1516 of file llutil.cpp.
References OPERAND::ll_type, make_lltype_from_sptr(), make_operand(), OPERAND::ot_type, OT_VAR, process_sptr(), set_llvm_sptr_name(), sptr, OPERAND::sptr, and OPERAND::val.
Referenced by gen_arg_operand(), gen_call_expr(), gen_llvm_expr(), gen_va_arg(), insert_jump_entry_instr(), process_formal_arguments(), and write_operand().
make_vector_lltype()
LL_Type * make_vector_lltype (int size, LL_Type * pts_to)
...
Definition at line 856 of file llutil.cpp.
References ll_get_vector_type(), and size.
Referenced by gen_optext_comp_operand().
make_void_lltype()
LL_Type * make_void_lltype (void)
...
Definition at line 850 of file llutil.cpp.
References LL_AddrSp_Default, ll_create_basic_type(), LL_VOID, and llvm_get_current_module().
Referenced by analyze_ret_info(), gen_call_expr(), gen_llvm_expr(), gen_unreachable_if_necessary(), gen_va_end(), gen_va_start(), insert_llvm_dbg_declare(), insert_llvm_dbg_value(), insert_llvm_memcpy(), insert_llvm_memset(), and insert_llvm_prefetch().
maybe_undo_recip_div()
void maybe_undo_recip_div (INSTR_LIST * mul)
Translate x * 1.0 / y to x / y.
...
Parameters
mul A FP multiply instruction
Preconditions: mul is a well-formed I_FMUL, has a positive use count
Definition at line 268 of file llopt.cpp.
References convert_mul_to_div(), fixup_recip_div(), I_FDIV, INSTR_TAG::i_name, ILI_OPC, ILI_OPCP, INSTR_TAG::ilix, is_recip(), OPERAND::next, and INSTR_TAG::operands.
Referenced by undo_recip_div().
optimize_block()
void optimize_block (INSTR_LIST * last_block_instr)
...
Definition at line 145 of file llopt.cpp.
References INSTR_TAG::flags, INSTR_TAG::i_name, I_NONE, INST_VISITED, last_instr, NULL, INSTR_TAG::prev, and STARTEBB.
Referenced by schedule().
print_dbg_line()
void print_dbg_line (LL_MDRef md)
Definition at line 1841 of file llutil.cpp.
References print_dbg_line_no_comma(), and print_token().
Referenced by assemble_end(), emit_dbg_from_module(), write_I_CALL(), and write_instructions().
print_dbg_line_no_comma()
void print_dbg_line_no_comma (LL_MDRef md)
Emit line info debug information.
Output the string " !dbg !<i>n</i>", where n is a metadata ref.
Definition at line 1833 of file llutil.cpp.
References buf, LL_MDREF_value, and print_token().
Referenced by build_routine_and_parameter_entries(), and print_dbg_line().
print_entry_subroutine()
void print_entry_subroutine (LL_Module * module)
Write out all Entry's as a separate routine.
Each entry will call a master/common routine (MCR). The first argument to the MCR will determine which label(Entry) control will jump to upon entry into the MCR. If the MCR is a function, the next argument will be the function's return value. The next argument(s) will be all non-duplicate aggregate arguments for all entries. The MCR will always effectively be a subroutine.
Definition at line 1067 of file ll_ftn.cpp.
References arg, LL_ABI_Info_::arg, aux, build_routine_and_parameter_entries(), CMPLXFUNC_C, AUX::dpdsc_base, DT_INT, DT_ISCMPLX, DTY, DTYG, DTySeqTyElement, LL_ABI_Info_::extend_abi_return, func_has_char_args(), gbl, get_llvm_name(), getdumlen(), getitem(), hash_functions_direct, hashset_alloc(), hashset_clear(), hashset_free(), hashset_insert(), hashset_lookup(), i, INT2HKEY, LL_Module::ir, ll_feature_explicit_gep_load_type, ll_proto_add_sptr(), ll_proto_key(), ll_proto_set_defined_body(), LLTYPE, LLVM_SHORTTERM_AREA, make_generic_dummy_lltype(), make_lltype_from_abi_arg(), make_lltype_from_dtype(), make_ptr_lltype(), make_tmps(), master_sptr, LL_ABI_Info_::nargs, char_len::next, NOSYM, NULL, num, print_nl(), print_space(), print_tmp_name(), print_token(), process_ll_abi_func_ftn(), process_sptr(), reset_expr_id(), SNAME, sptr, char_len::sptr, LL_ABI_ArgInfo_::sptr, tmp, TY_CHAR, TY_NCHAR, write_dummy_as_local_in_entry(), and write_type().
Referenced by schedule().
print_line()
void print_line (const char * ln)
...
...
Definition at line 1766 of file llutil.cpp.
References LLVMFIL, and NULL.
Referenced by assemble_end(), build_routine_and_parameter_entries(), finish_routine(), write_global_and_static_defines(), and write_module_as_subroutine().
print_line_tobuf()
void print_line_tobuf (char * ln, char * buf)
...
...
Definition at line 1778 of file llutil.cpp.
References buf, and NULL.
print_llsize()
void print_llsize (LL_Type * llt)
...
...
Definition at line 1727 of file llutil.cpp.
References assert, BIGIPFSZ, ERR_Fatal, ll_type_bytes(), and LLVMFIL.
print_llsize_tobuf()
void print_llsize_tobuf (LL_Type * llt, char * buf)
...
Definition at line 1734 of file llutil.cpp.
References assert, BIGIPFSZ, buf, ERR_Fatal, and ll_type_bytes().
print_metadata_name()
void print_metadata_name (TMPS * t)
...
...
Definition at line 2515 of file llutil.cpp.
References DBGTRACEIN1, DBGTRACEOUT, metadata_id, print_token(), t, and tmp.
Referenced by write_operand().
print_nl()
void print_nl (void)
...
...
Definition at line 1816 of file llutil.cpp.
References LLVMFIL.
Referenced by DeclareSPtrAsLocal(), llvm_write_ctor_dtor_list(), print_entry_subroutine(), write_def(), write_defs(), write_extern_fndecl(), write_external_function_declarations(), write_instructions(), and write_module_as_subroutine().
print_nl_tobuf()
void print_nl_tobuf (char * buf)
...
Definition at line 1822 of file llutil.cpp.
References buf.
print_space()
void print_space (int num)
...
...
Definition at line 1745 of file llutil.cpp.
References i, LLVMFIL, and num.
Referenced by print_entry_subroutine(), print_function_signature(), store_return_value_for_entry(), write_I_CALL(), write_instructions(), write_memory_order(), write_module_as_subroutine(), and write_operand().
print_space_tobuf()
void print_space_tobuf (int num, char * buf)
...
Definition at line 1754 of file llutil.cpp.
References buf, i, and num.
print_token()
void print_token (const char * tk)
...
...
Definition at line 1796 of file llutil.cpp.
References assert, ERR_Fatal, and LLVMFIL.
Referenced by add_property_struct(), build_routine_and_parameter_entries(), DeclareSPtrAsLocal(), llvm_write_ctor_dtor_list(), print_arg_attributes(), print_dbg_line(), print_dbg_line_no_comma(), print_entry_subroutine(), print_function_signature(), print_metadata_name(), print_personality(), print_tmp_name(), store_return_value_for_entry(), write_alt_field_types(), write_def(), write_def_values(), write_extern_fndecl(), write_function_attributes(), write_I_CALL(), write_instructions(), write_llaccgroup_metadata(), write_local_overlap(), write_memory_order(), write_memory_order_and_alignment(), write_module_as_subroutine(), write_operand(), write_target_features(), write_tbaa_metadata(), write_type(), write_vconstant_value(), write_verbose_type(), and write_vscale_range().
print_token_tobuf()
void print_token_tobuf (char * tk, char * buf)
...
...
Definition at line 1806 of file llutil.cpp.
References assert, buf, and ERR_Fatal.
process_acc_decl_common()
LL_Type * process_acc_decl_common (LL_Module * module, int first, BIGINT size, int is_constant, char * d_name, int externcommon)
...
process_acc_decl_const_param()
void process_acc_decl_const_param (LL_Module * module, char * name, int sptr)
...
process_acc_decl_gblvar()
LL_Type * process_acc_decl_gblvar (LL_Module * module, LL_Type * lltype, SPTR sptr, char * name)
it defines a global variable, used by lili2llvm_decl_globalvar.
process_acc_decl_statics()
LL_Type * process_acc_decl_statics (LL_Module * module, int first, char * d_name, int init, int addrspace)
...
process_acc_put_dinit()
void process_acc_put_dinit (int cmem, int x, bool loop)
...
process_acc_string()
LL_Type * process_acc_string (LL_Module * module, char * name, int sptr, bool initialize)
...
process_cmblk_sptr()
void process_cmblk_sptr (int sptr)
process_dtype_struct()
const char * process_dtype_struct (DTYPE dtype)
...
Definition at line 3235 of file llutil.cpp.
References add_def(), DBGTRACEIN1, DBGTRACEOUT1, def, DTY, DTyAlgTyAlign, DTyAlgTyMember, DTyAlgTyTag, DTyArgNext, get_def(), is_empty_typedef(), ll_convert_struct_dtype(), LLDEF_IS_EMPTY, LLDEF_IS_STRUCT, LLDEF_IS_TYPE, LLDEF_IS_UNPACKED_STRUCT, llvm_get_current_module(), make_def(), NULL, process_symlinked_sptr(), LL_Type_::str, struct_def_list, and ZSIZEOF.
Referenced by dtype_struct_name(), get_ftn_cbind_lltype(), ll_convert_struct_dtype(), lldbg_function_end(), make_lltype_from_sptr(), and write_ftn_typedefs().
process_ftn_dtype_struct()
const char * process_ftn_dtype_struct (DTYPE dtype, char * tname, bool printed)
...
...
This differs from process_dtype_struct and that it overrides the unique name generated by ll_convert_struct_dtype().
The printed flag tells write_ftn_typedefs that this type has already been printed out to the .ll output file. If true, write_ftn_typedefs() will not print the type out (assuming that it has already been 'printed').
Definition at line 3292 of file llutil.cpp.
References add_def(), DBGTRACEIN1, DBGTRACEOUT1, def, DTY, DTyAlgTyAlign, DTyAlgTyMember, DTyAlgTyTag, get_def(), ll_override_type_string(), LLDEF_IS_EMPTY, LLDEF_IS_STRUCT, LLDEF_IS_TYPE, llutil_alloc(), make_def(), NULL, process_symlinked_sptr(), strlen(), struct_def_list, tname, and ZSIZEOF.
Referenced by mk_struct_for_llvm_init().
process_ll_abi_func_ftn()
LL_ABI_Info * process_ll_abi_func_ftn (SPTR func_sptr, bool use_sptrs)
...
...
Definition at line 3849 of file llutil.cpp.
References llvm_get_current_module(), and process_ll_abi_func_ftn_mod().
Referenced by ll_process_routine_parameters(), print_entry_subroutine(), and write_master_entry_routine().
process_ll_abi_func_ftn_mod()
LL_ABI_Info * process_ll_abi_func_ftn_mod (LL_Module * mod, SPTR func_sptr, bool update)
...
...
Parameters
mod
func_sptr
update flag for special handling
If the update flag is true, then the ABI is reconstructed from the AG table, taking into account any changes added to the AG table. Update also will set the sptrs which means that this routine should only be called with true when the sptrs are valid: (i.e., if this routine exists in the current module).
TODO: Rename this function since process_sptr is not called in here.
Definition at line 3712 of file llutil.cpp.
References LL_ABI_Info_::arg, assert, LL_ABI_Info_::call_as_varargs, CMPLXFUNC_C, DTY, ERR_Fatal, LL_ABI_Info_::extend_abi_return, find_ag(), LL_ABI_ArgInfo_::ftn_pass_by_val, gbl, get_ag_argdtlist_length(), get_ag_return_lltype(), get_argdtlist(), get_byval_from_argdtlist(), get_lltype_from_argdtlist(), get_llvm_funcptr_ag(), get_llvm_ifacenm(), get_llvm_name(), get_master_sptr(), get_next_argdtlist(), get_return_type(), get_sptr_from_argdtlist(), i, LL_ABI_Info_::is_fortran, IS_FTN_PROC_PTR, LL_ABI_Info_::is_iso_c, is_iso_cptr(), LL_ABI_ArgInfo_::kind, ll_abi_alloc(), ll_abi_classify_arg_dtype(), ll_abi_classify_return_dtype(), ll_abi_complete_arg_info(), ll_abi_compute_call_conv(), ll_abi_free(), LL_ARG_DIRECT, LL_ARG_INDIRECT, LL_ARG_SIGNEXT, ll_proto_get_abi(), ll_proto_key(), ll_proto_set_abi(), LL_ABI_Info_::missing_prototype, nargs, sptr, LL_ABI_ArgInfo_::sptr, TY_CHAR, TY_ISCMPLX, TY_NCHAR, TY_SINT, TY_SLOG, LL_ABI_ArgInfo_::type, and XBIT.
Referenced by ll_abi_for_func_sptr(), process_ll_abi_func_ftn(), and schedule().
process_symlinked_sptr()
OPERAND * process_symlinked_sptr (int sptr, int total_init_sz, int is_union, int max_field_sz)
...
Definition at line 3159 of file llutil.cpp.
References DDTG, get_int_dtype_from_size(), i8, ll_create_int_type(), ll_get_array_type(), llvm_get_current_module(), make_member_op(), make_member_op_with_lltype(), OPERAND::next, NOSYM, NULL, sptr, and ZSIZEOF.
Referenced by process_dtype_struct(), and process_ftn_dtype_struct().
redundantLdLdElim()
void redundantLdLdElim (void)
Eliminate load-load operations from the uplevel structure.
...
Precondition
The current procedure is an outlined function with no dep check blocks
Definition at line 988 of file llopt.cpp.
References ad1ili(), ad3ili(), ad4ili(), addilt(), assert, BIH_ILTFIRST, BIH_NEXT, BIH_NODEPCHK, block_branches_to(), DT_CPTR, ERR_Fatal, get_acon3(), getNewWideSym(), hash_functions_direct, hashmap_alloc(), hashmap_clear(), hashmap_free(), hashmap_insert(), hashmap_iterate(), hashmap_lookup(), hashmap_replace(), hashmap_size(), hashset_alloc(), hashset_free(), HKEY2INT, IL_TYPE, ILI_OPC, ILI_OPND, ilt, ILT_DELETE, ILT_ILIP, ILT_NEXT, ILTY_STORE, INT2HKEY, lda, MSZ_PTR, rlleFindLL(), rlleMakeSet(), rlleReplace(), and widenAconIsPrivate().
Referenced by schedule().
reset_equiv_var()
void reset_equiv_var (void)
...
Definition at line 815 of file ll_ftn.cpp.
References equiv_type, and NULL.
Referenced by assem_end().
reset_master_sptr()
void reset_master_sptr (void)
...
Definition at line 822 of file ll_ftn.cpp.
References master_sptr, and SPTR_NULL.
Referenced by assem_end().
sched_instructions()
void sched_instructions (INSTR_LIST * istart)
...
Definition at line 407 of file llsched.cpp.
References build_block_idep_graph(), INSTR_TAG::flags, irank, ROOTDG, and sched_block().
Referenced by schedule().
set_metadata_string()
void set_metadata_string (TMPS * t, char * string)
...
...
Definition at line 2487 of file llutil.cpp.
References DBGTRACEIN2, DBGTRACEOUT, and t.
should_preserve_param()
bool should_preserve_param (const DTYPE dtype)
return whether param debug info should be preserved
This function returns true for the types supported in function make_param_op
Definition at line 2147 of file llutil.cpp.
References AD_DPTR, AD_NUMELM, ad_val_of(), assert, DTY, ERR_Fatal, ISZ_T, size, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by process_params().
small_aggr_return()
bool small_aggr_return (DTYPE dtype)
...
Definition at line 2551 of file llutil.cpp.
Referenced by get_return_dtype().
visit_flattened_dtype()
int visit_flattened_dtype (dtype_visitor visitor, void * context, DTYPE dtype, unsigned address, unsigned member_sptr)
...
Definition at line 3941 of file llutil.cpp.
References assert, DTY, DTyAlgTyMember, ERR_Fatal, NOSYM, sptr, and visit_flattened_dtype().
Referenced by amd64_classify(), check_vector_registers(), check_vfp(), and visit_flattened_dtype().
widenAddressArith()
void widenAddressArith (void)
Widen address arithmetic.
...
Definition at line 796 of file llopt.cpp.
References BIH_ILTFIRST, BIH_NEXT, DBGBIT, dumpblocks(), dumpWidenVars(), funcHasNoDepChk(), gatherLocals(), hash_functions_direct, hashmap_alloc(), hashmap_free(), hashmap_iterate(), hashset_alloc(), hashset_free(), hashset_iterate(), hashset_size(), ILI_OPC, ilt, ILT_DELETE, ILT_ILIP, ILT_NEXT, NULL, widenAddNarrowVars(), widenAnyAddressing(), widenApplyCse(), widenApplyFree(), widenApplyStore(), widenApplyVarMap(), widenCreateWideLocal(), widenElimAddrTaken(), widenGatherAcon(), widenPruneAcon(), widenPushdown(), and x.
Referenced by schedule().
write_constant_value()
void write_constant_value (int sptr, LL_Type * type, INT conval0, INT conval1, bool uns)
...
...
Definition at line 1911 of file llutil.cpp.
References assert, b, CONVAL2G, cprintf(), d, DT_FLOAT, DT_ISCMPLX, DTY, ERR_Fatal, len, LL_ARRAY, LL_DOUBLE, LL_FLOAT, LL_FP128, LL_I1, LL_I128, LL_I16, LL_I24, LL_I256, LL_I32, LL_I40, LL_I48, LL_I56, LL_I64, LL_I8, LL_PPC_FP128, LL_PTR, LL_STRUCT, ll_type_bytes(), LL_VECTOR, LL_X86_FP80, llvm_fc_type(), LLVMFIL, make_lltype_from_dtype(), STB::n_base, num, p, sptr, stb, tmp, TY_CHAR, TY_CMPLX, TY_NCHAR, type, ui64toax(), write_constant_value(), write_vconstant_value(), xx_u::ww, xdble(), and xdtomd().
Referenced by write_constant_value(), write_consts(), write_operand(), and write_vconstant_value().
write_ftn_typedefs()
void write_ftn_typedefs (void)
...
Definition at line 3072 of file llutil.cpp.
References LLDEF::dtype, get_typedef_ag(), LLDEF::name, LLDEF::next, LLDEF::printed, process_dtype_struct(), struct_def_list, and write_def().
Referenced by cg_llvm_fnend(), cg_llvm_init(), and schedule().
write_gblvar_defs()
void write_gblvar_defs (FILE * target_file, LL_Module * module)
...
write_local_overlap()
void write_local_overlap (void)
...
Definition at line 802 of file ll_ftn.cpp.
References equiv_type, print_token(), and write_type().
Referenced by schedule().
write_operand()
void write_operand (OPERAND * p, const char * punc_string, int flags)
...
...
Definition at line 2242 of file llutil.cpp.
References assert, LL_Type_::data_type, DBGDUMPLLTYPE, DBGTRACE1, DBGTRACEIN2, DBGTRACEOUT, ERR_Fatal, flags, OPERAND::flags, FLG_AS_UNSIGNED, FLG_FIXUP_RETURN_TYPE, FLG_OMIT_OP_TYPE, getcon(), i, LL_FP128, LL_FUNCTION, ll_get_pointer_type(), LL_I16, LL_PTR, OPERAND::ll_type, ll_type_int_bits(), ll_type_is_fp(), LL_VECTOR, LLTYPE_equiv(), llvm_cc_names, llvm_ccfp_names, make_arg_op(), make_lltype_from_dtype(), make_param_op(), make_ptr_lltype(), make_var_op(), maybe_fixup_x86_abi_return(), metadata_args_need_struct(), NULL, OPF_CONTAINS_UNDEF, OPF_HIDDEN, OPF_NULL_TYPE, OPF_SRARG_TYPE, OPF_SRET_TYPE, OPF_WRAPPED_MD, OT_CALL, OT_CC, OT_CONSTSPTR, OT_CONSTSTRING, OT_CONSTVAL, OT_DEF, OT_LABEL, OT_MDNODE, OT_MEMBER, ot_names, OT_NONE, OT_TARGET, OT_TMP, OT_UNDEF, OT_VAR, OTNAMEG, p, print_metadata_name(), print_space(), print_tmp_name(), print_token(), sptr, write_constant_value(), write_operand(), write_type(), and write_vconstant_value().
Referenced by store_return_value_for_entry(), write_def_values(), write_I_CALL(), write_instructions(), write_operand(), and write_operands().
write_operands()
void write_operands (OPERAND * operand, int flags)
...
...
Parameters
operand The head of the list
flags
Write out the operands in order. Not always possible, depends on instruction format. Assumes the separator is a comma.
Definition at line 2468 of file llutil.cpp.
References DBGTRACEIN1, DBGTRACEOUT, flags, operand, p, and write_operand().
Referenced by write_I_CALL(), and write_instructions().
write_struct_defs()
void write_struct_defs (void)
...
Definition at line 3061 of file llutil.cpp.
References defs_to_write(), struct_def_list, and write_defs().
write_type()
void write_type (LL_Type * ll_type)
...
...
Definition at line 2131 of file llutil.cpp.
References print_token(), and LL_Type_::str.
Referenced by DeclareSPtrAsLocal(), print_entry_subroutine(), store_return_value_for_entry(), write_def(), write_I_CALL(), write_instructions(), write_llvm_lltype(), write_local_overlap(), write_module_as_subroutine(), write_operand(), and write_vconstant_value().
Variable Documentation
ftn_llvm_st
FTN_LLVM_ST ftn_llvm_st extern
Definition at line 102 of file llutil.cpp.
ll_dfile
FILE* ll_dfile extern
Definition at line 2534 of file llutil.cpp.
Referenced by cg_llvm_init(), dump_type_for_debug(), indent(), llutil_dfile_init(), and schedule().
sptr_dinit_array
SPTR_DREC* sptr_dinit_array extern