flang: lockfile.h File Reference
lockfile.h File Reference
Functions
int __pg_make_lock_file (char *dir)
Creates a uniquely-named file in the current directory.
void __pg_get_lock (char *lname)
The argument is the name of the lock.
void __pg_release_lock (char *lname)
The argument is the same name for the lock.
void __pg_delete_lock_file (void)
Clean up by deleting the uniquely named file we had created earlier.
Detailed Description
Four routines to be able to lock access to a file in the Linux approved manner. This seems to be the only method that works over NFS.
Definition in file lockfile.h.
Function Documentation
__pg_delete_lock_file()
void __pg_delete_lock_file (void)
Clean up by deleting the uniquely named file we had created earlier.
These routines only allow one lock to be managed at a time. They dynamically allocate and free memory.
Definition at line 179 of file lockfile.c.
References NULL, r, udir, and uname.
__pg_get_lock()
void __pg_get_lock (char * lname)
The argument is the name of the lock.
Each process tries to create a hard link with this name to its own uniquely-named file from __pg_make_lock_file(). The one that succeeds is the new lock owner. The others fail and try again. There is a fail-over to handle the case where the process with the lock dies, which is inherently unsafe, but we haven't come up with a better solution.
Definition at line 99 of file lockfile.c.
References count, malloc(), NULL, r, ss, stat, strlen(), udir, uname, and uwaiting.
__pg_make_lock_file()
int __pg_make_lock_file (char * dir)
Creates a uniquely-named file in the current directory.
To work, this must be created on the same filesystem as the file which we are attempting to lock. If there are multiple processes running each competing for the same lock, each gets a unique file here.
Definition at line 67 of file lockfile.c.
References fclose(), FILE, malloc(), NULL, pid, r, strlen(), udir, uname, and uwaiting.
__pg_release_lock()
void __pg_release_lock (char * lname)
The argument is the same name for the lock.
The lock is released by deleting (calling unlink) for the hard link we had just created.
Definition at line 159 of file lockfile.c.
References malloc(), NULL, r, strlen(), udir, and uname.