flang: log10_d_vec.h File Reference
log10_d_vec.h File Reference
#include <common.h>
Functions
static __attribute__ ((always_inline)) vdouble __log10_d_kernel(vdouble m
vdouble __attribute__ ((noinline)) log10_d_vec(vdouble const a_input)
Variables
static vdouble e
m = vsub_vd_vd_vd(m, *(vdouble*)ONE_D)
vdouble m2 = vmul_vd_vd_vd(m, m)
vdouble m4 = vmul_vd_vd_vd(m2, m2)
vdouble m5 = vmul_vd_vd_vd(m4, m)
vdouble m8 = vmul_vd_vd_vd(m4, m4)
vdouble t0 = vfma_vd_vd_vd_vd(*(vdouble*)c0, m, *(vdouble*)c1)
vdouble t1 = vfma_vd_vd_vd_vd(*(vdouble*)c2, m, *(vdouble*)c3)
vdouble t2 = vfma_vd_vd_vd_vd(*(vdouble*)c4, m, *(vdouble*)c5)
vdouble t3 = vfma_vd_vd_vd_vd(*(vdouble*)c6, m, *(vdouble*)c7)
vdouble t4 = vfma_vd_vd_vd_vd(*(vdouble*)c8, m, *(vdouble*)c9)
vdouble t5 = vfma_vd_vd_vd_vd(*(vdouble*)c10, m, *(vdouble*)c11)
vdouble t6 = vfma_vd_vd_vd_vd(*(vdouble*)c12, m, *(vdouble*)c13)
vdouble t7 = vfma_vd_vd_vd_vd(*(vdouble*)c14, m, *(vdouble*)c15)
vdouble t = *(vdouble*)c16
Function Documentation
__attribute__() [1/2]
static __attribute__ ((always_inline)) inline static
__attribute__() [2/2]
vdouble __attribute__ ((noinline)) const
Definition at line 51 of file log10_d_vec.h.
References b, CANONICAL_NAN, e, m, MANTISSA_MASK, nan_mask, NINF, PINF, t, THRESHOLD, TWO_TO_53, vadd64_vi2_vi2_vi2(), vadd_vd_vd_vd(), vand_vi2_vi2_vi2(), vcast_vd_d(), vcast_vd_vi(), vcast_vi2_i(), vcast_vi_i(), vcast_vm_i_i(), veq64_vo_vi2_vi2(), veq_vo_vd_vd(), vgetexp_vd_vd(), vgetmant_vd_vd(), vgt64_vo_vi2_vi2(), vhi64_vi_vi2(), vmul_vd_vd_vd(), vneq_vo_vd_vd(), vsel_vd_vo_vd_vd(), vsll64_vi2_vi2_i(), vsra_vi_vi_i(), vsub64_vi2_vi2_vi2(), vsub_vd_vd_vd(), vsub_vi_vi_vi(), and vtestz_i_vo().
Variable Documentation
e
vdouble e
Initial value:
{
    e = vmul_vd_vd_vd(e, *(vdouble*)LOG10_2)
Definition at line 13 of file log10_d_vec.h.
Referenced by __attribute__().
m
m = vsub_vd_vd_vd(m, *(vdouble*)ONE_D)
Definition at line 16 of file log10_d_vec.h.
Referenced by __attribute__().
m2
vdouble m2 = vmul_vd_vd_vd(m, m)
Definition at line 18 of file log10_d_vec.h.
m4
vdouble m4 = vmul_vd_vd_vd(m2, m2)
Definition at line 19 of file log10_d_vec.h.
m5
vdouble m5 = vmul_vd_vd_vd(m4, m)
Definition at line 20 of file log10_d_vec.h.
m8
vdouble m8 = vmul_vd_vd_vd(m4, m4)
Definition at line 21 of file log10_d_vec.h.
t
return t = *(vdouble*)c16
Definition at line 32 of file log10_d_vec.h.
Referenced by __attribute__().
t0
t0 = vfma_vd_vd_vd_vd(*(vdouble*)c0, m, *(vdouble*)c1)
Definition at line 23 of file log10_d_vec.h.
t1
vdouble t1 = vfma_vd_vd_vd_vd(*(vdouble*)c2, m, *(vdouble*)c3)
Definition at line 24 of file log10_d_vec.h.
t2
t2 = vfma_vd_vd_vd_vd(*(vdouble*)c4, m, *(vdouble*)c5)
Definition at line 25 of file log10_d_vec.h.
t3
vdouble t3 = vfma_vd_vd_vd_vd(*(vdouble*)c6, m, *(vdouble*)c7)
Definition at line 26 of file log10_d_vec.h.
t4
t4 = vfma_vd_vd_vd_vd(*(vdouble*)c8, m, *(vdouble*)c9)
Definition at line 27 of file log10_d_vec.h.
t5
vdouble t5 = vfma_vd_vd_vd_vd(*(vdouble*)c10, m, *(vdouble*)c11)
Definition at line 28 of file log10_d_vec.h.
t6
t6 = vfma_vd_vd_vd_vd(*(vdouble*)c12, m, *(vdouble*)c13)
Definition at line 29 of file log10_d_vec.h.
t7
vdouble t7 = vfma_vd_vd_vd_vd(*(vdouble*)c14, m, *(vdouble*)c15)
Definition at line 30 of file log10_d_vec.h.