flang: log10_vec_legacy.h File Reference
log10_vec_legacy.h File Reference
#include <common.h>
Functions
vfloat __attribute__ ((noinline)) log10_vec(vfloat const a_input)
Function Documentation
__attribute__()
vfloat __attribute__ ((noinline)) const
Definition at line 12 of file log10_vec_legacy.h.
References CANONICAL_NAN, e, m, MANTISSA_MASK, nan_mask, NINF, ONE_F, PINF, t, TWO_TO_24_F, vadd_vf_vf_vf(), vadd_vi2_vi2_vi2(), vand_vi2_vi2_vi2(), vcast_vf_f(), vcast_vf_vi2(), vcast_vi2_i(), veq_vo_vf_vf(), veq_vo_vi2_vi2(), vfma_vf_vf_vf_vf(), vgt_vo_vi2_vi2(), vmul_vf_vf_vf(), vneq_vo_vf_vf(), vsel_vf_vo_vf_vf(), vsra_vi2_vi2_i(), vsub_vf_vf_vf(), vsub_vi2_vi2_vi2(), and vtestz_i_vo().