flang: common.h File Reference
log10f/common.h File Reference
#include <math.h>
Functions
static float int_as_float (int a)
static int float_as_int (float a)
const float ONE_F[] __attribute__ ((aligned(64)))
const float coeffs[] __attribute__ ((aligned(16)))
Variables
static float const TWO_TO_24_F = 16777216.0f
static float const PINF = +INFINITY
static float const NINF = -INFINITY
static float const CANONICAL_NAN = -NAN
Function Documentation
__attribute__() [1/2]
const float coeffs[] __attribute__ ((aligned(16)))
__attribute__() [2/2]
const float ONE_F[] __attribute__ ((aligned(64)))
float_as_int()
static int float_as_int (float a) inline static
Definition at line 16 of file log10f/common.h.
References a.
Referenced by __attribute__(), __reduction_slowpath(), and reduction_slowpath().
int_as_float()
static float int_as_float (int a) inline static
Definition at line 15 of file log10f/common.h.
References a.
Referenced by __attribute__(), and reduction_slowpath().
Variable Documentation
CANONICAL_NAN
float const CANONICAL_NAN = -NAN static
Definition at line 21 of file log10f/common.h.
NINF
float const NINF = -INFINITY static
Definition at line 20 of file log10f/common.h.
Referenced by __attribute__().
PINF
float const PINF = +INFINITY static
Definition at line 19 of file log10f/common.h.
Referenced by __attribute__().
TWO_TO_24_F
float const TWO_TO_24_F = 16777216.0f static
Definition at line 18 of file log10f/common.h.