flang: lower.c File Reference
lower.c File Reference
lower STD/AST to back-end ILM structure
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "dtypeutl.h"
#include "ast.h"
#include "fdirect.h"
#include "rtlRtns.h"
#include "lower.h"
Macros
#define INSIDE_LOWER
#define STB_LOWER() ((gbl.outfil == lowersym.lowerfile) && gbl.stbfil)
#define LOWERBUFSIZ 10000
#define MAX_PASS_STRUCT_SIZE 16
#define PACK(i, j) (((j) << 8) | ((i)&0xFF))
#define UNPACKLOW(i) ((i)&0xFF)
#define UNPACKHIGH(i) ((i) >> 8)
#define REGSIZE 8
#define CLASS_INT(t) (t >= CLASS_INT1 && t <= CLASS_INT8)
#define CLASS_SSESP(t) (t == CLASS_SSESP4 || t == CLASS_SSESP8)
#define CLASS_SSE(t)
Functions
static void lower_start_subroutine (int)
static void lower_end_subroutine (void)
static void lower_program (int)
static void save_contained (void)
static void init_contained (void)
static void lower_directives (void)
void LowerTraceOutput (const char *fmt,...)
void lerror (const char *fmt,...)
int lower_ndtypeg (int ast)
void lower (int staticinit)
Lower the STDs and ASTs to something that the back end can use.
void lower_clear_opt (int ast, int *unused)
Clear the A_OPT1 and A_OPT2 fields for a single ast, using ast_traverse.
void lower_debug_label (void)
static void save_contained_name (char *name)
static void markid (int astx, int *unused)
void lower_end_contains (void)
void lower_constructor (void)
Notify back end of the end of a module.
static int addclasses (int a, int b)
static void trav_struct (int dtype, int off)
static int pass_struct (int dtype)
static int check_struct (int dtype)
int check_return (int retdtype)
Variables
static int errors
static int last_contained = 0
static int size_contained = 0
static int * contained = NULL
static int last_contained_char = 0
static int size_contained_char = 0
static char * contained_char = NULL
static int * outerflags = NULL
static int regclass [2]
Detailed Description
lower STD/AST to back-end ILM structure
Definition in file lower.c.
Macro Definition Documentation
CLASS_INT
#define CLASS_INT (t) (t >= CLASS_INT1 && t <= CLASS_INT8)
Definition at line 665 of file lower.c.
CLASS_SSE
#define CLASS_SSE (t)
Value:
  (t == CLASS_SSESP4 || t == CLASS_SSESP8 || t == CLASS_SSEDP || \
   t == CLASS_SSEQ)
Definition at line 667 of file lower.c.
CLASS_SSESP
#define CLASS_SSESP (t) (t == CLASS_SSESP4 || t == CLASS_SSESP8)
Definition at line 666 of file lower.c.
INSIDE_LOWER
#define INSIDE_LOWER
Definition at line 22 of file lower.c.
LOWERBUFSIZ
#define LOWERBUFSIZ 10000
MAX_PASS_STRUCT_SIZE
#define MAX_PASS_STRUCT_SIZE 16
Definition at line 657 of file lower.c.
PACK
#define PACK (i, j) (((j) << 8) | ((i)&0xFF))
Definition at line 660 of file lower.c.
REGSIZE
#define REGSIZE 8
Definition at line 663 of file lower.c.
STB_LOWER
#define STB_LOWER () ((gbl.outfil == lowersym.lowerfile) && gbl.stbfil)
Definition at line 42 of file lower.c.
UNPACKHIGH
#define UNPACKHIGH (i) ((i) >> 8)
Definition at line 662 of file lower.c.
UNPACKLOW
#define UNPACKLOW (i) ((i)&0xFF)
Definition at line 661 of file lower.c.
Function Documentation
addclasses()
static int addclasses (int a, int b) static
Definition at line 675 of file lower.c.
References a, b, CLASS_INT, CLASS_INT4, CLASS_INT8, CLASS_MEM, and CLASS_NONE.
Referenced by trav_struct().
check_return()
int check_return (int retdtype)
Definition at line 909 of file lower.c.
References check_struct(), CLASS_INT4, DT_ISCMPLX, and DTY.
Referenced by is_struct_kind(), lower_function(), and lower_symbol().
check_struct()
static int check_struct (int dtype) static
Definition at line 881 of file lower.c.
References CLASS_INT4, CLASS_INT8, CLASS_MEM, MAX_PASS_STRUCT_SIZE, pass_struct(), size, and size_of().
Referenced by check_return().
init_contained()
static void init_contained (void) static
Definition at line 358 of file lower.c.
References BZERO, contained, contained_char, STB::firstusym, last_contained, last_contained_char, lowersym, NEW, outerflags, size_contained, size_contained_char, stb, and sz.
Referenced by lower().
lerror()
void lerror (const char * fmt, ...)
Definition at line 68 of file lower.c.
References errors, and gbl.
Referenced by ast_error(), export_data_consts(), fill_fixed_array_dtype(), fill_pointer_array_dtype(), lower_ast(), lower_conv(), lower_conv_ilm(), lower_data_stmts(), lower_do_stmt(), lower_fill_member_parent(), lower_intrinsic(), lower_numelm(), lower_omp_target_tripcount(), lower_put_datatype(), lower_sptr(), lower_stmt(), lower_symbol(), lower_visit_symbol(), ltyped(), plower(), putsclass(), putstype(), and styped().
lower()
void lower (int staticinit)
Lower the STDs and ASTs to something that the back end can use.
Essentially, lower to ILMs, save them to a file. In the mean time, save the symbol table to the same file, as well as anything else needed to compile the program.
Definition at line 106 of file lower.c.
References a, astb, contained, DBGBIT, dmp_dtype(), DTY, dump_std(), error(), errors, FILE, fill_entry_bounds(), FUNCLINEG, gbl, init_contained(), interr(), lower_add_pghpf_commons(), lower_check_generics(), lower_clear_visit_fields(), lower_common_sizes(), lower_data_stmts(), lower_data_types(), lower_debug_label(), lower_directives(), lower_end_subroutine(), lower_exp_finish(), lower_fileinfo(), lower_fill_member_parent(), lower_finish_sym(), lower_ilm_finish(), lower_ilm_header(), lower_init_sym(), lower_line, lower_linearized(), lower_mark_entries(), lower_namelist_plists(), lower_outer_symbols(), lower_program(), lower_set_craypointer(), lower_set_symbols(), lower_start_subroutine(), lower_stmt(), lower_sym_header(), lower_symbols(), lower_unset_symbols(), lowersym, NULL, RU_BDATA, RU_FUNC, RU_SUBR, save_contained(), stb, stb_fixup_llvmiface(), std, STD_AST, STD_LABEL, STD_LINENO, STD_NEXT, STD_ORIG, symdmp(), tmpfile(), and XBIT.
Referenced by build_array_list(), check_loop_bound(), constructf90(), conv_allocate(), ENTF90(), ENTFTN(), exp_smp(), fix_datatype(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), lower_check_subscript(), and read_datatype().
lower_clear_opt()
void lower_clear_opt (int ast, int * unused)
Clear the A_OPT1 and A_OPT2 fields for a single ast, using ast_traverse.
Definition at line 295 of file lower.c.
References ast.
Referenced by lower_end_stmt(), and lower_reinit().
lower_constructor()
void lower_constructor (void)
Notify back end of the end of a module.
Definition at line 643 of file lower.c.
References gbl.
lower_debug_label()
void lower_debug_label (void)
Definition at line 302 of file lower.c.
References gbl, and plower().
Referenced by lower(), and lower_stmt().
lower_directives()
static void lower_directives (void) static
Definition at line 629 of file lower.c.
References direct_export(), lowersym, VersionMajor, and VersionMinor.
Referenced by lower().
lower_end_contains()
void lower_end_contains (void)
Definition at line 461 of file lower.c.
References c, contained, contained_char, DBGBIT, FALSE, fclose(), FREE, gbl, getprint(), last_contained, LOWERBUFSIZ, lowersym, NULL, outerflags, sptr, strlen(), Trace, TRUE, and XBIT.
Referenced by end_contained().
lower_end_subroutine()
static void lower_end_subroutine (void) static
Definition at line 347 of file lower.c.
References gbl, lowersym, STB_LOWER, and uncouple_callee_args().
Referenced by lower().
lower_ndtypeg()
int lower_ndtypeg (int ast)
Definition at line 87 of file lower.c.
References ast, ast_error(), and astb.
lower_program()
static void lower_program (int rutype) static
Definition at line 605 of file lower.c.
References gbl, lowersym, RU_BDATA, RU_FUNC, RU_PROG, RU_SUBR, s, and STB_LOWER.
Referenced by lower().
lower_start_subroutine()
static void lower_start_subroutine (int rutype) static
Definition at line 310 of file lower.c.
References FALSE, gbl, lower_end_stmt(), lower_makefunc(), lower_pointer_init(), lower_start_stmt(), lowersym, mkRteRtnNm(), plower(), RTE_init, RU_BDATA, RU_FUNC, RU_PROG, RU_SUBR, and TRUE.
Referenced by lower().
LowerTraceOutput()
void LowerTraceOutput (const char * fmt, ...)
Definition at line 49 of file lower.c.
References DBGBIT, and gbl.
markid()
static void markid (int astx, int * unused) static
Definition at line 396 of file lower.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_NUMDIM, ADD_NUMELM, ADD_UPAST, ADD_UPBD, ADD_ZBASE, ast_traverse_more(), DTY, i, lowersym, outerflags, and sptr.
Referenced by save_contained().
pass_struct()
static int pass_struct (int dtype) static
Definition at line 847 of file lower.c.
References assert, CLASS_MEM, CLASS_NONE, DT_ISCMPLX, DTY, PACK, regclass, and trav_struct().
Referenced by check_struct().
save_contained()
static void save_contained (void) static
Definition at line 445 of file lower.c.
References ast_traverse(), ast_unvisit_norepl(), ast_visit(), STB::firstusym, markid(), NULL, save_contained_name(), sptr, stb, STD_AST, STD_NEXT, stdx, and SYMNAME.
Referenced by lower().
save_contained_name()
static void save_contained_name (char * name) static
Definition at line 379 of file lower.c.
References contained, contained_char, last_contained, last_contained_char, len, name, NEED, size_contained, size_contained_char, and strlen().
Referenced by save_contained().
trav_struct()
static void trav_struct (int dtype, int off) static
Definition at line 715 of file lower.c.
References AD_DPTR, AD_NUMELM, ad_val_of(), addclasses(), addr, assert, CLASS_INT4, CLASS_INT8, CLASS_NONE, d, DTY, FALSE, FLANG_FALLTHROUGH, i, interr(), mem(), NOSYM, off, regclass, REGSIZE, size_of(), trav_struct(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_SINT, and TY_SLOG.
Referenced by pass_struct(), and trav_struct().
Variable Documentation
contained
int* contained = NULL static
Definition at line 35 of file lower.c.
Referenced by init_contained(), lower(), lower_end_contains(), and save_contained_name().
contained_char
char* contained_char = NULL static
Definition at line 38 of file lower.c.
Referenced by init_contained(), lower_end_contains(), and save_contained_name().
errors
int errors static
Definition at line 25 of file lower.c.
Referenced by lerror(), and lower().
last_contained
int last_contained = 0 static
Definition at line 34 of file lower.c.
Referenced by init_contained(), lower_end_contains(), and save_contained_name().
last_contained_char
int last_contained_char = 0 static
Definition at line 37 of file lower.c.
Referenced by init_contained(), and save_contained_name().
outerflags
int* outerflags = NULL static
Definition at line 40 of file lower.c.
Referenced by init_contained(), lower_end_contains(), and markid().
regclass
int regclass[2] static
Definition at line 671 of file lower.c.
Referenced by pass_struct(), and trav_struct().
size_contained
int size_contained = 0 static
Definition at line 34 of file lower.c.
Referenced by init_contained(), and save_contained_name().
size_contained_char
int size_contained_char = 0 static
Definition at line 37 of file lower.c.
Referenced by init_contained(), and save_contained_name().