flang: lowerilm.c File Reference
lowerilm.c File Reference
Routines used by lower.c for lowering to ILMs.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "ast.h"
#include "semant.h"
#include "dinit.h"
#include "soc.h"
#include "gramtk.h"
#include "pragma.h"
#include "mp.h"
#include "rte.h"
#include "rtlRtns.h"
#include "lower.h"
#include "mach.h"
Macros
#define INSIDE_LOWER
#define VarBase 0
#define SourceBase 1
#define TargetBase 2
#define ArgumentBase 3
#define ALIGNED_ALLOC
#define USE_LARGE_SIZE
#define LOWERBUFSIZ 10000
#define ORDERED_MASK 0x10000
#define DTIO_RSPTR 1
#define DTIO_WSPTR 2
#define DTIO_DTVSPTR 3
#define DTIO_DTV_SDSC 4
#define DTIO_VLIST_SPTR 5
#define DTIO_VLIST_SDSC 6
#define DTIO_END 7
Functions
int get_byval (int, int)
Return true if param is pass by value.
void setrefsymbol (int symbol)
void lower_ilm_header (void)
void lower_ilm_finish (void)
static int plower_pdo (int, int)
int plower (const char *fmt,...)
Print out the ILM line.
int plower_arg (const char *fmt, int arg, int dtype, int unlpoly)
static int plabel (int label, int value, int first)
void lower_start_stmt (int lineno, int label, int exec, int std)
Start a new block.
void lower_end_stmt (int std)
static void put_adjarr_bounds (int dtype, int subscripts, int *pcomputednumelm)
void fill_entry_bounds (int sptr, int lineno)
Look at the formal arguments; for array arguments, get the actual argument, call put_adjarr_bounds to fill in the .A variables.
static void fill_midnum (int sptr)
static int intermediate_members (int base, int parent, int sptr)
static int lower_numelm (int, int, int, int)
static int lower_sptr (int sptr, int)
static int lower_base_address (int ast, int pointerval)
int lower_replacement (int ast, int sym)
static void add_nullify (int ast)
static void lower_finish_subprogram (int rutype)
static void fix_array_fields (int dtype)
static void handle_arguments (int ast, int symfunc, int via_ptr)
static int compute_dotrip (int std, int initincsame, int doinitilm, int doendilm, int doinc, int doincilm, int dtype, int dotrip)
static int dotemp (char letter, int dtype, int std)
static void set_mp_loop_var (int var, int rilm, int dtype)
static void set_loop_bound (int newupper, int oilm, int nilm, int dtype, int labo, int increment)
static void check_loop_bound (int lower, int upper, int oupper, int stride, int label, int setbound, int incr_loop)
static void llvm_omp_sched (int std, int ast, int dtype, int dotop, int dobottom, int dovar, int plast, int dotrip, int doinitilm, int doinc, int doincilm, int doendilm, int schedtype, int lineno)
static void lower_do_stmt (int std, int ast, int lineno, int label)
static void llvm_lower_enddo_stmt (int lineno, int label, int std, int ispdo)
static void lower_enddo_stmt (int lineno, int label, int std, int ispdo)
static void lower_omp_atomic_write (int ast, int lineno)
static void lower_omp_atomic_update (int ast, int lineno)
static void lower_omp_atomic_capture (int ast, int lineno)
static void lower_omp_target_tripcount (int ast, int std)
void lower_stmt (int std, int ast, int lineno, int label)
int lower_base (int ast)
Get base address for LHS.
int lower_base_sptr (int sptr)
Get base address for LHS for a symbol.
int lower_address (int ast)
Get source address for pointer assignment.
int lower_target (int ast)
Get target address for pointer assignment.
int lower_typeload (int dtype, int base)
int lower_typestore (int dtype, int base, int rhs)
int lower_ilm (int ast)
Get the ilm for this expression ast.
static VAR * export_data_varlist_asts (VAR *ivl)
static void export_data_const_asts (ACL *ict)
static void export_data_asts (VAR *ivl, ACL *ict)
static VAR * export_data_varlist (VAR *ivl)
static void export_data_consts (ACL *ict, int spoof)
static void export_data_stmt (VAR *ivl, ACL *ict)
void lower_data_stmts (void)
Variables
static FILE * lower_ilm_file = NULL
int lower_line
int lower_disable_ptr_chk = 0
int lower_disable_subscr_chk = 0
struct lsymlists_s lsymlists
static char saveoperation [50]
static int numelm_constant
static int symone
Detailed Description
Routines used by lower.c for lowering to ILMs.
Definition in file lowerilm.c.
Macro Definition Documentation
ALIGNED_ALLOC
#define ALIGNED_ALLOC
Definition at line 53 of file lowerilm.c.
ArgumentBase
#define ArgumentBase 3
Definition at line 42 of file lowerilm.c.
DTIO_DTV_SDSC
#define DTIO_DTV_SDSC 4
Definition at line 6354 of file lowerilm.c.
DTIO_DTVSPTR
#define DTIO_DTVSPTR 3
Definition at line 6353 of file lowerilm.c.
DTIO_END
#define DTIO_END 7
Definition at line 6357 of file lowerilm.c.
DTIO_RSPTR
#define DTIO_RSPTR 1
Definition at line 6351 of file lowerilm.c.
DTIO_VLIST_SDSC
#define DTIO_VLIST_SDSC 6
Definition at line 6356 of file lowerilm.c.
DTIO_VLIST_SPTR
#define DTIO_VLIST_SPTR 5
Definition at line 6355 of file lowerilm.c.
DTIO_WSPTR
#define DTIO_WSPTR 2
Definition at line 6352 of file lowerilm.c.
INSIDE_LOWER
#define INSIDE_LOWER
Definition at line 29 of file lowerilm.c.
LOWERBUFSIZ
#define LOWERBUFSIZ 10000
ORDERED_MASK
#define ORDERED_MASK 0x10000
SourceBase
#define SourceBase 1
Definition at line 40 of file lowerilm.c.
TargetBase
#define TargetBase 2
Definition at line 41 of file lowerilm.c.
USE_LARGE_SIZE
#define USE_LARGE_SIZE
Definition at line 60 of file lowerilm.c.
VarBase
#define VarBase 0
Definition at line 39 of file lowerilm.c.
Function Documentation
add_nullify()
static void add_nullify (int ast) static
Definition at line 845 of file lowerilm.c.
References ast, DTY, find_pointer_variable(), lower_base(), lower_disable_ptr_chk, lower_expression(), lower_null(), lower_replacement(), lower_target(), lower_typestore(), lowersym, and plower().
Referenced by lower_stmt().
check_loop_bound()
static void check_loop_bound (int lower, int upper, int oupper, int stride, int label, int setbound, int incr_loop) static
Definition at line 1614 of file lowerilm.c.
References label, lower(), lower_lab(), lower_typeload(), lowersym, plower(), set_loop_bound(), stride, and upper().
Referenced by llvm_omp_sched().
compute_dotrip()
static int compute_dotrip (int std, int initincsame, int doinitilm, int doendilm, int doinc, int doincilm, int dtype, int dotrip) static
Definition at line 1474 of file lowerilm.c.
References STB::dbl1, STB::flt1, STB::i1, lower_conv_ilm(), lower_typestore(), ltyped(), plower(), stb, and XBIT.
Referenced by llvm_omp_sched(), lower_do_stmt(), and lower_omp_target_tripcount().
dotemp()
static int dotemp (char letter, int dtype, int std) static
Definition at line 1547 of file lowerilm.c.
References DTY, getccssym_sc(), lowersym, std, STD_PAR, and STD_TASK.
Referenced by llvm_omp_sched(), lower_do_stmt(), and lower_omp_target_tripcount().
export_data_asts()
static void export_data_asts (VAR * ivl, ACL * ict) static
Definition at line 6094 of file lowerilm.c.
References Doend, Dostart, VAR::dostart, export_data_const_asts(), export_data_varlist_asts(), VAR::id, VAR::indvar, VAR::lowbd, lower_expression(), lower_ilm(), lower_visit_symbol(), lowersym, next, VAR::next, NULL, plower(), _acl::sptr, VAR::step, _acl::subc, symone, VAR::u, VAR::upbd, and Varref.
Referenced by lower_data_stmts().
export_data_const_asts()
static void export_data_const_asts (ACL * ict) static
Definition at line 6062 of file lowerilm.c.
References AC_IEXPR, ast, _acl::ast, astb, DTY, _acl::dtype, export_data_const_asts(), _acl::expr, ASTB::i1, _acl::id, AEXPR::lop, lower_visit_symbol(), _acl::next, NULL, AEXPR::rop, _acl::subc, TY_INT, TY_REAL, and _acl::u1.
Referenced by export_data_asts(), and export_data_const_asts().
export_data_consts()
static void export_data_consts (ACL * ict, int spoof) static
Definition at line 6155 of file lowerilm.c.
References AC_ACONST, AC_AST, AC_ICONST, AC_IDO, AC_IEXPR, AC_SCONST, ast, _acl::ast, astb, ASTB::bnd, construct_acl_from_ast(), CONVAL2G, _acl::doinfo, DTY, _acl::dtype, ASTB::dtype, export_data_consts(), _acl::expr, _acl::i, ASTB::i1, _acl::id, DOINFO::index_var, DOINFO::init_expr, lerror(), DOINFO::limit_expr, AEXPR::lop, lower_ilm_file, lower_use_datatype(), lower_visit_symbol(), _acl::next, _acl::no_dinitp, NULL, AEXPR::op, plower(), _acl::ptrdtype, _acl::repeatc, AEXPR::rop, sptr, _acl::sptr, DOINFO::step_expr, _acl::subc, TY_BINT, TY_BLOG, TY_HOLL, TY_INT, TY_LOG, TY_NCHAR, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, and _acl::u1.
Referenced by export_data_consts(), and export_data_stmt().
export_data_stmt()
static void export_data_stmt (VAR * ivl, ACL * ict) static
Definition at line 6318 of file lowerilm.c.
References Doend, Dostart, VAR::dostart, export_data_consts(), export_data_varlist(), VAR::id, VAR::indvar, VAR::lowbd, lower_ilm_file, next, VAR::next, NULL, VAR::step, symone, VAR::u, VAR::upbd, and Varref.
Referenced by lower_data_stmts().
export_data_varlist()
static VAR * export_data_varlist (VAR * ivl) static
Definition at line 6132 of file lowerilm.c.
References ast, export_data_varlist(), VAR::id, lower_ilm_file, lower_use_datatype(), VAR::next, NULL, VAR::ptr, VAR::u, Varref, and VAR::varref.
Referenced by export_data_stmt(), and export_data_varlist().
export_data_varlist_asts()
static VAR * export_data_varlist_asts (VAR * ivl) static
Definition at line 6047 of file lowerilm.c.
References export_data_varlist_asts(), VAR::id, lower_base(), lower_expression(), VAR::next, NULL, VAR::ptr, VAR::u, Varref, and VAR::varref.
Referenced by export_data_asts(), and export_data_varlist_asts().
fill_entry_bounds()
void fill_entry_bounds (int sptr, int lineno)
Look at the formal arguments; for array arguments, get the actual argument, call put_adjarr_bounds to fill in the .A variables.
Definition at line 746 of file lowerilm.c.
References aux, AUX::dpdsc_base, DTY, FALSE, i, lineno, lower_end_stmt(), lower_start_stmt(), NULL, put_adjarr_bounds(), and sptr.
Referenced by lower(), and lower_stmt().
fill_midnum()
static void fill_midnum (int sptr) static
Definition at line 773 of file lowerilm.c.
References get_type(), getccsym(), sptr, and XBIT.
Referenced by lower_sptr().
fix_array_fields()
static void fix_array_fields (int dtype) static
Definition at line 907 of file lowerilm.c.
References A_OPTYPEG, ADD_EXTNTAST, ADD_LWAST, ADD_NUMDIM, ADD_UPAST, DTY, find_array(), i, mk_shared_bnd_ast(), NULL, OP_ADD, OP_SUB, and r.
Referenced by handle_arguments().
get_byval()
int get_byval (int func_sptr, int param_sptr)
Return true if param is pass by value.
Definition at line 457 of file semfunc.c.
Referenced by func_call2(), handle_arguments(), ptrfunc_call(), and subr_call2().
handle_arguments()
static void handle_arguments (int ast, int symfunc, int via_ptr) static
Definition at line 962 of file lowerilm.c.
References a, A_ARGCNTG, A_OPTYPEG, args, ARGT_ARG, assert, ast, astb, aux, count, AUX::dpdsc_base, dt, STB::dt_int, DTY, find_dummy_position(), fix_array_fields(), FLANG_FALLTHROUGH, gbl, get_byval(), get_tbp_argno(), get_type_descr_arg(), i, is_arg_in_entry(), is_iso_cloc(), is_procedure_ptr(), is_unl_poly(), lower_argument, lower_argument_size, lower_base(), lower_disable_ptr_chk, lower_expression(), lower_ilm(), lower_lab(), lower_parenthesize_expression(), lower_replacement(), lower_target(), max_binding_invobj(), memsym_of_ast(), NEED, OP_REF, params, pass_sym_of_ast(), plabel(), plower(), plower_arg(), proc_arg_needs_proc_desc(), ASTB::ptr0, sptr, stb, sym_of_ast(), TY_CHAR, TY_INT8, TY_NCHAR, STB::user, and XBIT.
Referenced by lower_stmt().
intermediate_members()
static int intermediate_members (int base, int parent, int sptr) static
Definition at line 794 of file lowerilm.c.
References a, base, intermediate_members(), p, parent, plower(), and sptr.
Referenced by intermediate_members(), lower_base_address(), and lower_replacement().
llvm_lower_enddo_stmt()
static void llvm_lower_enddo_stmt (int lineno, int label, int std, int ispdo) static
Definition at line 2495 of file lowerilm.c.
References DT_INT, DTY, label, lineno, lower_check_stack(), lower_end_stmt(), lower_pop(), lower_sptr(), lower_start_stmt(), lower_typeload(), lower_typestore(), ltyped(), MP_SCH_ATTR_ORDERED, MP_SCH_AUTO, MP_SCH_BLK_CYC, MP_SCH_CHUNK_1, MP_SCH_DIST_STATIC, MP_SCH_DYNAMIC, MP_SCH_GUIDED, MP_SCH_RUNTIME, MP_SCH_TYPE_MASK, plower(), std, STD_ZTRIP, TRUE, TY_BLOG, TY_LOG, TY_LOG8, TY_SLOG, VarBase, and XBIT.
Referenced by lower_enddo_stmt().
llvm_omp_sched()
static void llvm_omp_sched (int std, int ast, int dtype, int dotop, int dobottom, int dovar, int plast, int dotrip, int doinitilm, int doinc, int doincilm, int doendilm, int schedtype, int lineno) static
Definition at line 1701 of file lowerilm.c.
References _i4_cmp(), _i8_cmp(), assert, ast, astb, check_loop_bound(), compute_dotrip(), dotemp(), DT_INT, STB::i0, STB::i1, ASTB::i1, STB::k0, STB::k1, ASTB::k1, lower_conv(), lower_end_stmt(), lower_expression(), lower_lab(), lower_push(), lower_sptr(), lower_typeload(), lower_typestore(), lowersym, ltyped(), MP_SCH_ATTR_CHUNKED, MP_SCH_ATTR_ORDERED, MP_SCH_AUTO, MP_SCH_DYNAMIC, MP_SCH_GUIDED, MP_SCH_RUNTIME, MP_SCH_TYPE_MASK, plower(), plower_pdo(), set_mp_loop_var(), stb, std, ub, and VarBase.
Referenced by lower_do_stmt().
lower_address()
int lower_address (int ast)
Get source address for pointer assignment.
Definition at line 5829 of file lowerilm.c.
References ast, lower_base_address(), and SourceBase.
Referenced by lower_intrinsic(), and lower_stmt().
lower_base()
int lower_base (int ast)
Get base address for LHS.
Definition at line 5801 of file lowerilm.c.
References ast, base, lower_base_address(), and VarBase.
Referenced by add_nullify(), export_data_varlist_asts(), f90_function(), handle_arguments(), intrinsic_arg_dtype(), lower_ast(), lower_base_address(), lower_bin_comparison(), lower_function(), lower_ilm(), lower_intrinsic(), lower_omp_atomic_capture(), lower_omp_atomic_update(), lower_omp_atomic_write(), lower_stmt(), put_adjarr_bounds(), and set_mp_loop_var().
lower_base_address()
static int lower_base_address (int ast, int pointerval) static
Definition at line 5674 of file lowerilm.c.
References ArgumentBase, ast, ast_error(), base, DTY, DTYG, FLANG_FALLTHROUGH, intermediate_members(), lbase, len, lower_base(), lower_check_pointer(), lower_disable_ptr_chk, lower_ilm(), lower_sptr(), lower_typeload(), lower_visit_symbol(), lowersym, plower(), SourceBase, sptr, TargetBase, TY_HOLL, TY_NCHAR, VarBase, and XBIT.
Referenced by lower_address(), lower_base(), lower_stmt(), and lower_target().
lower_base_sptr()
int lower_base_sptr (int sptr)
Get base address for LHS for a symbol.
Definition at line 5820 of file lowerilm.c.
References base, lower_sptr(), sptr, and VarBase.
Referenced by lower_intrinsic().
lower_data_stmts()
void lower_data_stmts (void)
Definition at line 6360 of file lowerilm.c.
References add_stmt_after(), assert, ast, ast_unvisit_norepl(), astb, charlen(), cnt, DREC::conval, dest, ASTB::df, DINIT_END, DINIT_ENDARY, DINIT_ENDTYPE, DINIT_FMT, dinit_fseek(), dinit_fseek_end(), DINIT_LABEL, DINIT_LOC, DINIT_NML, DINIT_OFFSET, dinit_read(), DINIT_REPEAT, DINIT_STARTARY, DINIT_STR, DINIT_TYPEDEF, DINIT_ZEROES, DT_INT, DT_PTR, DTIO_DTV_SDSC, DTIO_DTVSPTR, DTIO_RSPTR, DTIO_VLIST_SDSC, DTIO_VLIST_SPTR, DTIO_WSPTR, DTY, DREC::dtype, error(), export_data_asts(), export_data_stmt(), FALSE, flg, gbl, get_type_descr_arg(), getcon(), VAR::id, FLG::ipa, is_arg_in_entry(), is_argp_in_entry(), is_procedure_ptr(), lerror(), lineno, lower_ilm_file, lower_start_stmt(), lower_use_datatype(), lower_visit_symbol(), mk_assn_stmt(), mk_cval(), mk_id(), mk_subscr(), mk_unop(), NOSYM, NULL, OP_LOC, VAR::ptr, S_IDENT, size_of(), sptr, src, std, string_length(), symone, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_SINT, TY_SLOG, VAR::u, VAR::varref, FLG::x, and XBIT.
Referenced by lower().
lower_do_stmt()
static void lower_do_stmt (int std, int ast, int lineno, int label) static
Definition at line 1992 of file lowerilm.c.
References A_ORDEREDG, A_SCHED_TYPEG, ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_NUMELM, ADD_UPAST, ADD_UPBD, ADD_ZBASE, ast, ast_error(), astb, ASTB::bnd, compute_dotrip(), STB::dbl1, DI_SCH_AUTO, DI_SCH_DYNAMIC, DI_SCH_GUIDED, DI_SCH_RUNTIME, DI_SCH_STATIC, dotemp(), dt, DT_INT, DTY, FALSE, STB::flt1, get_array_dtype(), getccssym_sc(), STB::i0, ASTB::i0, STB::i1, ASTB::i1, ASTB::k1, label, lerror(), lineno, llvm_omp_sched(), lower_conv(), lower_conv_ilm(), lower_end_stmt(), lower_expression(), lower_getiszcon(), lower_ilm(), lower_lab(), lower_makefunc(), lower_push(), lower_reinit(), lower_sptr(), lower_start_stmt(), lower_typeload(), lower_typestore(), lower_use_datatype(), lowersym, ltyped(), MAXCPUS, mk_cnst(), MP_SCH_ATTR_CHUNKED, MP_SCH_ATTR_ORDERED, MP_SCH_BLK_CYC, MP_SCH_CHUNK_1, MP_SCH_DIST_STATIC, ASTB::one, ORDERED_MASK, plower(), plower_pdo(), set_mp_loop_var(), size_of(), stb, std, STD_BLKSYM, STD_ZTRIP, TRUE, TY_BINT, TY_BLOG, TY_DBLE, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_REAL, TY_SINT, TY_SLOG, ub, VarBase, and XBIT.
Referenced by lower_stmt().
lower_end_stmt()
void lower_end_stmt (int std)
Definition at line 450 of file lowerilm.c.
References ast, ast_revisit(), ast_unvisit_norepl(), lower_clear_opt(), next, plower(), std, STD_AST, and STD_NEXT.
Referenced by fill_entry_bounds(), llvm_lower_enddo_stmt(), llvm_omp_sched(), lower_do_stmt(), lower_enddo_stmt(), lower_start_subroutine(), and lower_stmt().
lower_enddo_stmt()
static void lower_enddo_stmt (int lineno, int label, int std, int ispdo) static
Definition at line 2635 of file lowerilm.c.
References DI_SCH_AUTO, DI_SCH_DYNAMIC, DI_SCH_GUIDED, DI_SCH_RUNTIME, DT_INT, DTY, label, lineno, llvm_lower_enddo_stmt(), lower_check_stack(), lower_end_stmt(), lower_enddo_stmt(), lower_pop(), lower_sptr(), lower_start_stmt(), lower_typeload(), lower_typestore(), lowersym, ltyped(), MP_SCH_ATTR_ORDERED, ORDERED_MASK, plower(), std, STD_ZTRIP, TRUE, TY_BLOG, TY_LOG, TY_LOG8, TY_SLOG, VarBase, and XBIT.
Referenced by lower_enddo_stmt(), and lower_stmt().
lower_finish_subprogram()
static void lower_finish_subprogram (int rutype) static
Definition at line 884 of file lowerilm.c.
References RU_BDATA, RU_FUNC, RU_PROG, and RU_SUBR.
Referenced by lower_stmt().
lower_ilm()
int lower_ilm (int ast)
Get the ilm for this expression ast.
Definition at line 5994 of file lowerilm.c.
References ast, base, FLANG_FALLTHROUGH, lower_base(), lower_ilm(), lower_typeload(), sptr, and XBIT.
Referenced by conv_bint(), conv_blog(), conv_cmplx(), conv_dble(), conv_dcmplx(), conv_dword(), conv_int(), conv_int8(), conv_log(), conv_log8(), conv_real(), conv_sint(), conv_slog(), conv_word(), export_data_asts(), f90_value_function(), f90_value_function_I2(), handle_arguments(), lower_ast(), lower_base_address(), lower_bin_comparison(), lower_conv(), lower_do_stmt(), lower_function(), lower_ilm(), lower_intrinsic(), lower_logical_expr(), lower_numelm(), lower_omp_target_tripcount(), lower_replacement(), lower_stmt(), and put_adjarr_bounds().
lower_ilm_finish()
void lower_ilm_finish (void)
Definition at line 76 of file lowerilm.c.
References fclose(), lower_ilm_file, LOWERBUFSIZ, lowersym, and NULL.
Referenced by lower().
lower_ilm_header()
void lower_ilm_header (void)
Definition at line 63 of file lowerilm.c.
References error(), lower_ilm_file, NULL, tmpfile(), VersionMajor, and VersionMinor.
Referenced by lower().
lower_numelm()
static int lower_numelm (int dtype, int ast, int src, int loadit) static
Definition at line 5515 of file lowerilm.c.
References ADD_NUMELM, ast, ast_error(), check_member(), lerror(), lower_expression(), lower_ilm(), lower_typeload(), lowersym, mk_convert(), numelm_constant, plower(), size_of(), src, and SYMNAME.
Referenced by lower_stmt().
lower_omp_atomic_capture()
static void lower_omp_atomic_capture (int ast, int lineno) static
Definition at line 2832 of file lowerilm.c.
References A_MEM_ORDERG, A_OPTYPEG, ast, lower_base(), lower_conv(), lower_expression(), and plower().
Referenced by lower_stmt().
lower_omp_atomic_update()
static void lower_omp_atomic_update (int ast, int lineno) static
Definition at line 2809 of file lowerilm.c.
References A_MEM_ORDERG, A_OPTYPEG, ast, lower_base(), lower_conv(), lower_expression(), and plower().
Referenced by lower_stmt().
lower_omp_atomic_write()
static void lower_omp_atomic_write (int ast, int lineno) static
Definition at line 2789 of file lowerilm.c.
References A_MEM_ORDERG, ast, lower_base(), lower_conv(), lower_expression(), and plower().
Referenced by lower_stmt().
lower_omp_target_tripcount()
static void lower_omp_target_tripcount (int ast, int std) static
Definition at line 2856 of file lowerilm.c.
References ast, compute_dotrip(), dotemp(), DT_INT, FALSE, lerror(), lower_expression(), lower_ilm(), plower(), size_of(), std, and XBIT.
Referenced by lower_stmt().
lower_replacement()
int lower_replacement (int ast, int sym)
Definition at line 825 of file lowerilm.c.
References ast, base, intermediate_members(), lbase, lower_expression(), lower_ilm(), lower_sptr(), lower_visit_symbol(), plower(), and VarBase.
Referenced by add_nullify(), handle_arguments(), lower_ast(), and lower_stmt().
lower_sptr()
static int lower_sptr (int sptr, int pointerval) static
Definition at line 5562 of file lowerilm.c.
References ArgumentBase, assert, base, DTY, ERR_Severe, fill_midnum(), lerror(), lower_check_pointer(), lower_disable_ptr_chk, lower_typeload(), lower_visit_symbol(), mk_id(), NOSYM, plower(), SourceBase, sptr, SYMNAME, TargetBase, VarBase, and XBIT.
Referenced by llvm_lower_enddo_stmt(), llvm_omp_sched(), lower_base_address(), lower_base_sptr(), lower_do_stmt(), lower_enddo_stmt(), lower_replacement(), and set_loop_bound().
lower_start_stmt()
void lower_start_stmt (int lineno, int label, int exec, int std)
Start a new block.
Definition at line 408 of file lowerilm.c.
References ast, ast_visit(), FLANG_FALLTHROUGH, gbl, label, lineno, plower(), prev, std, STD_AST, STD_FINDEX, STD_LABEL, and STD_PREV.
Referenced by fill_entry_bounds(), llvm_lower_enddo_stmt(), lower_data_stmts(), lower_do_stmt(), lower_enddo_stmt(), lower_start_subroutine(), and lower_stmt().
lower_stmt()
void lower_stmt (int std, int ast, int lineno, int label)
Definition at line 2918 of file lowerilm.c.
References A_ARGCNTG, A_CANCELKINDG, A_OPTYPEG, A_TKNG, ADD_LWAST, add_nullify(), ADD_NUMDIM, ALIGNG, args, ARGT_ARG, ArgumentBase, ASD_NDIM, ASD_SUBS, assert, ast, ast_error(), ast_is_sym(), astb, ASTLI_AST, ASTLI_NEXT, base, ASTB::bnd, bnds_remap_list(), bounds, check_member(), count, DDTG, dest, DISTG, DT_INT, DT_PTR, DTY, DTYG, dtype_to_arg(), FALSE, fill_entry_bounds(), find_pointer_variable(), first_element(), FLANG_FALLTHROUGH, flg, gbl, get_int_cval(), get_lsize_index(), get_static_type_descriptor(), get_type_descr_arg(), handle_arguments(), has_finalized_component(), has_layout_desc(), i, interr(), is_array_dtype(), is_or_has_derived_allo(), is_or_has_poly(), is_procedure_ptr(), ASTB::k0, ASTB::k1, label, lb, lerror(), lineno, lower_address(), lower_base(), lower_base_address(), lower_check_stack(), lower_conv(), lower_conv_ilm(), lower_debug_label(), lower_disable_ptr_chk, lower_disable_subscr_chk, lower_do_stmt(), lower_end_stmt(), lower_enddo_stmt(), lower_expression(), lower_finish_subprogram(), lower_getintcon(), lower_getiszcon(), lower_ilm(), lower_lab(), lower_line, lower_logical(), lower_makefunc(), lower_null(), lower_null_arg(), lower_nullc_arg(), lower_numelm(), lower_omp_atomic_capture(), lower_omp_atomic_update(), lower_omp_atomic_write(), lower_omp_target_tripcount(), lower_pointer_init(), lower_pop(), lower_push(), lower_reinit(), lower_replacement(), lower_reset_temps(), lower_start_stmt(), lower_stmt(), lower_target(), lower_typeload(), lower_typestore(), lower_visit_symbol(), lowersym, ltyped(), memsym_of_ast(), mk_bnd_int(), mk_id(), mk_member(), mkRteRtnNm(), MP_TASK_FINAL, MP_TASK_GRAINSIZE, MP_TASK_IMMEDIATE, MP_TASK_MERGEABLE, MP_TASK_NOGROUP, MP_TASK_NUM_TASKS, MP_TGT_IFTARGET, ndim, NOSYM, NULL, num, numelm_constant, FLG::omptarget, ASTB::one, OP_LOC, plabel(), plower(), prev, procsym_of_ast(), put_adjarr_bounds(), rank, rank_of_sym(), RTE_alloc04_chka, RTE_alloc04a, RTE_auto_alloc04, RTE_auto_calloc04, RTE_auto_dealloc, RTE_barrier, RTE_calloc04a, RTE_copy_f77_argl, RTE_copy_f77_argsl, RTE_copy_f90_argl, RTE_copy_out, RTE_dealloc03a, RTE_dealloc_mbr03a, RTE_dealloc_poly03, RTE_dealloc_poly_mbr03a, RTE_mvbits, RTE_ptr_alloc04a, RTE_ptr_assn, RTE_ptr_assn_assumeshp, RTE_ptr_assn_char_assumeshp, RTE_ptr_assn_chara, RTE_ptr_assn_charxa, RTE_ptr_assn_dchar_assumeshp, RTE_ptr_assn_dchara, RTE_ptr_assn_dcharxa, RTE_ptr_assnx, RTE_ptr_calloc04a, RTE_ptr_fix_assumeshp, RTE_ptr_fix_assumeshp1, RTE_ptr_fix_assumeshp2, RTE_ptr_fix_assumeshp3, RTE_ptr_in_chara, RTE_ptr_ina, RTE_ptr_out, RTE_ptr_out_chara, RTE_ptr_shape_assn, RTE_ptr_shape_assnx, RTE_ptr_src_alloc04a, RTE_ptr_src_calloc04a, RTE_qopy_in, RU_FUNC, size, size_ast(), size_of(), sptr, src, ss, st, start, std, STD_AST, STD_LINENO, STD_NEXT, STD_PREV, string_expr_length(), sym_of_ast(), SYMNAME, TRUE, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, ub, XBIT, and ASTB::zero.
Referenced by lower(), and lower_stmt().
lower_target()
int lower_target (int ast)
Get target address for pointer assignment.
Definition at line 5836 of file lowerilm.c.
References ast, lower_base_address(), and TargetBase.
Referenced by add_nullify(), handle_arguments(), lower_function(), lower_intrinsic(), and lower_stmt().
lower_typeload()
int lower_typeload (int dtype, int base)
Definition at line 5842 of file lowerilm.c.
References ast_error(), base, DTY, plower(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and XBIT.
Referenced by check_loop_bound(), llvm_lower_enddo_stmt(), llvm_omp_sched(), lower_ast(), lower_base_address(), lower_check_pointer(), lower_do_stmt(), lower_enddo_stmt(), lower_ilm(), lower_intrinsic(), lower_numelm(), lower_sptr(), and lower_stmt().
lower_typestore()
int lower_typestore (int dtype, int base, int rhs)
Definition at line 5917 of file lowerilm.c.
References ast_error(), base, DTY, plower(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and XBIT.
Referenced by add_nullify(), compute_dotrip(), llvm_lower_enddo_stmt(), llvm_omp_sched(), lower_do_stmt(), lower_enddo_stmt(), lower_parenthesize_expression(), lower_stmt(), put_adjarr_bounds(), and set_loop_bound().
plabel()
static int plabel (int label, int value, int first) static
Definition at line 394 of file lowerilm.c.
References first, label, lower_ilm_file, lower_visit_symbol(), lowersym, NULL, RFCNTI, and value().
Referenced by handle_arguments(), and lower_stmt().
plower()
int plower (const char * fmt, ...)
Print out the ILM line.
Parameters
fmt is a character string with the following values:
o - operation, must be first
O - same operation as most recent, must be first
i - ilm number
r - symbol number, may be zero
s - symbol number
S - symbol number, with comment containing symbol name
L - label symbol number, defining the label
C - symbol name in comment only
l - line number
d - datatype
n - number
a - argument: ilm and datatype pair, but only counts for one
A - argument: like 'a', but for missing optional argument
m - 'more', meaning don't end the ilm line here, wait for more; must be last, at least, anything following the m is ignored.
Definition at line 116 of file lowerilm.c.
References allocate_refsymbol(), d, DBGBIT, FLG::debug, DT_INT, DTY, f, flg, getprint(), lerror(), lower_ilm_file, lower_use_datatype(), lower_visit_symbol(), NULL, RFCNTI, saveoperation, setrefsymbol(), stb, and XBIT.
Referenced by _xtoi(), add_lnop(), add_nullify(), check_loop_bound(), compute_dotrip(), conv_bint_ilm(), conv_blog_ilm(), conv_cmplx_ilm(), conv_dble_ilm(), conv_dcmplx_ilm(), conv_dword_ilm(), conv_int8_ilm(), conv_int_ilm(), conv_log8_ilm(), conv_log_ilm(), conv_real_ilm(), conv_sint_ilm(), conv_slog_ilm(), conv_word_ilm(), export_data_asts(), export_data_consts(), f90_function(), f90_value_function(), f90_value_function_I2(), handle_arguments(), intermediate_members(), intrin_name(), intrin_name_bsik(), llvm_lower_enddo_stmt(), llvm_omp_sched(), lower_ast(), lower_base_address(), lower_bin_arith(), lower_bin_comparison(), lower_bin_logical(), lower_check_pointer(), lower_check_subscript(), lower_debug_label(), lower_do_stmt(), lower_end_stmt(), lower_enddo_stmt(), lower_function(), lower_intrinsic(), lower_logical(), lower_null(), lower_null_arg(), lower_nullc_arg(), lower_numelm(), lower_omp_atomic_capture(), lower_omp_atomic_update(), lower_omp_atomic_write(), lower_omp_target_tripcount(), lower_parenthesize_expression(), lower_pointer_init(), lower_replacement(), lower_sptr(), lower_start_stmt(), lower_start_subroutine(), lower_stmt(), lower_typeload(), lower_typestore(), lower_un_arith(), lower_un_logical(), lowersym_pghpf_cmem(), plower_arg(), plower_pdo(), put_adjarr_bounds(), set_loop_bound(), and set_mp_loop_var().
plower_arg()
int plower_arg (const char * fmt, int arg, int dtype, int unlpoly)
Definition at line 362 of file lowerilm.c.
References arg, and plower().
Referenced by handle_arguments(), and lower_function().
plower_pdo()
static int plower_pdo (int dotop, int schedtype) static
Definition at line 376 of file lowerilm.c.
References plower(), and RFCNTD.
Referenced by llvm_omp_sched(), and lower_do_stmt().
put_adjarr_bounds()
static void put_adjarr_bounds (int dtype, int subscripts, int * pcomputednumelm) static
Definition at line 486 of file lowerilm.c.
References ad_val_of(), ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_NUMDIM, ADD_UPAST, ADD_UPBD, ADD_ZBASE, ASD_SUBS, assert, astb, ASTB::bnd, i, ISZ_T, lower_base(), lower_conv_ilm(), lower_expression(), lower_getiszcon(), lower_ilm(), lower_typestore(), lowersym, m, mk_convert(), ndim, nelem, NULL, ASTB::one, plower(), size_of(), stride, Trace, and zbase.
Referenced by fill_entry_bounds(), and lower_stmt().
set_loop_bound()
static void set_loop_bound (int newupper, int oilm, int nilm, int dtype, int labo, int increment) static
Definition at line 1587 of file lowerilm.c.
References lower_sptr(), lower_typestore(), ltyped(), plower(), and VarBase.
Referenced by check_loop_bound().
set_mp_loop_var()
static void set_mp_loop_var (int var, int rilm, int dtype) static
Definition at line 1571 of file lowerilm.c.
References dest, DTYG, lower_base(), lower_conv_ilm(), lower_expression(), mk_id(), and plower().
Referenced by llvm_omp_sched(), and lower_do_stmt().
setrefsymbol()
void setrefsymbol (int symbol)
Definition at line 1439 of file main.c.
Referenced by plower().
Variable Documentation
lower_disable_ptr_chk
int lower_disable_ptr_chk = 0
Definition at line 35 of file lowerilm.c.
Referenced by add_nullify(), handle_arguments(), lower_base_address(), lower_function(), lower_intrinsic(), lower_sptr(), and lower_stmt().
lower_disable_subscr_chk
int lower_disable_subscr_chk = 0
Definition at line 36 of file lowerilm.c.
Referenced by lower_ast(), lower_no_subscr_chk(), and lower_stmt().
lower_ilm_file
FILE* lower_ilm_file = NULL static
Definition at line 33 of file lowerilm.c.
Referenced by export_data_consts(), export_data_stmt(), export_data_varlist(), lower_data_stmts(), lower_ilm_finish(), lower_ilm_header(), plabel(), and plower().
lower_line
int lower_line
Definition at line 34 of file lowerilm.c.
Referenced by lower(), lower_check_pointer(), lower_check_subscript(), and lower_stmt().
lsymlists
struct lsymlists_s lsymlists
Definition at line 37 of file lowerilm.c.
Referenced by lower_finish_sym(), and lower_init_sym().
numelm_constant
int numelm_constant static
Definition at line 819 of file lowerilm.c.
Referenced by lower_numelm(), and lower_stmt().
saveoperation
char saveoperation[50] static
Definition at line 93 of file lowerilm.c.
Referenced by plower().
symone
int symone static
Definition at line 6044 of file lowerilm.c.
Referenced by export_data_asts(), export_data_stmt(), and lower_data_stmts().