flang: lowerchk.c File Reference
lowerchk.c File Reference
Add array bounds and null pointer checks.
#include "gbldefs.h"
#include "global.h"
#include "symtab.h"
#include "symutl.h"
#include "ast.h"
#include "lower.h"
Macros
#define INSIDE_LOWER
#define LEN 128
Functions
static int fill_name (int ast)
static void fill_recurse (int ast)
void lower_check_pointer (int ast, int ilm)
Generate a pointer check.
void lower_check_subscript (int sym, int ast, int ndim, int *ilm, int *lower, int *upper)
Generate a subscript check.
Variables
static char Name [LEN+2]
static int Len
Detailed Description
Add array bounds and null pointer checks.
Definition in file lowerchk.c.
Macro Definition Documentation
INSIDE_LOWER
#define INSIDE_LOWER
Definition at line 19 of file lowerchk.c.
LEN
#define LEN 128
Definition at line 22 of file lowerchk.c.
Function Documentation
fill_name()
static int fill_name (int ast) static
Definition at line 65 of file lowerchk.c.
References ast, fill_recurse(), getstring(), Len, and Name.
Referenced by fill_recurse(), lower_check_pointer(), and lower_check_subscript().
fill_recurse()
static void fill_recurse (int ast) static
Definition at line 29 of file lowerchk.c.
References ast, ast_error(), fill_name(), Len, Name, s, strlen(), and SYMNAME.
Referenced by fill_name().
lower_check_pointer()
void lower_check_pointer (int ast, int ilm)
Generate a pointer check.
Generate a call:
    ftn_ptrchk(val(pointer),val(lineno),ref("varname"),ref("filename"))
Definition at line 85 of file lowerchk.c.
References ast, fill_name(), ilmname, lower_getintcon(), lower_line, lower_typeload(), lowersym, and plower().
Referenced by lower_base_address(), and lower_sptr().
lower_check_subscript()
void lower_check_subscript (int sym, int ast, int ndim, int * ilm, int * lower, int * upper)
Generate a subscript check.
Generate a call for each subscript
    ftn_ptrchk(val(subscript),val(lower),val(upper),val(dimension),
               val(lineno),ref("varname"),ref("filename"))
ast is a subscript ast
If sym is zero, derive the name of the array from the subscript ast; otherwise, use the name of sym.
Definition at line 118 of file lowerchk.c.
References ast, fill_name(), getstring(), i, ilmname, LEN, Len, lower(), lower_getintcon(), lower_line, lowersym, Name, ndim, plower(), s, strlen(), SYMNAME, and upper().
Referenced by lower_ast().
Variable Documentation
Len
int Len static
Definition at line 24 of file lowerchk.c.
Referenced by fill_name(), fill_recurse(), and lower_check_subscript().
Name
char Name[LEN+2] static
Definition at line 23 of file lowerchk.c.
Referenced by fill_name(), fill_recurse(), and lower_check_subscript().