flang: lowerexp.c File Reference
lowerexp.c File Reference
Routines used by lower.c for lowering to ILMs.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "comm.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "ast.h"
#include "semant.h"
#include "dinit.h"
#include "soc.h"
#include "gramtk.h"
#include "rte.h"
#include "extern.h"
#include "rtlRtns.h"
#include "lower.h"
Macros
#define INSIDE_LOWER
#define in_I_K_r_D_C_CD 0x0331333
#define in_I_K_R_D_C_CD 0x0333333
#define in_Il_K_R_D_C_CD 0x0b33333
#define in_I_K_R_D 0x0333300
#define in_Il_K_R_D 0x0b33300
#define in_I_K_r_D 0x0331300
#define in_I_K_r_D_Q 0x03313c0
#define in_i_K_A_D 0x0135300
#define in_i_K_A_D_Q 0x01353c0
#define in_i_K 0x0130000
#define in_il_K 0x0930000
#define in_I_K 0x0330000
#define in_i_64 0x0150000
#define in_i_k 0x0110000
#define in_i 0x0100000
#define in_J_K 0x0530000
#define in_R_D 0x0003300
#define in_R_D_Q 0x00033c0
#define in_r_D 0x0001300
#define in_r_D_Q 0x00013c0
#define in_R_D_C_CD 0x0001333
#define in_r_D_C_CD 0x0001333
#define in_R_D_Q_C_CD_CQ 0xc0033f3
#define in_r_D_Q_C_CD_CQ 0xc0013f3
#define in_c_cD 0x0000015
#define in_A_D 0x0005300
#define in_A_D_Q 0x00053c0
#define in_d 0x0000100
#define in_c 0x1000000
#define in_nc 0x2000000
#define in_c_nc 0x3000000
#define in_c_cD_cQ 0x400001d
#define IARGS 100
#define allowI 0x0100000
#define prefixI 0x0200000
#define prefixJ 0x0400000
#define allowL 0x0800000
#define allowK 0x0010000
#define prefixK 0x0020000
#define suffix64 0x0040000
#define allowR 0x0001000
#define prefixR 0x0002000
#define prefixA 0x0004000
#define allowD 0x0000100
#define prefixD 0x0000200
#define allowQ 0x0000040
#define prefixQ 0x0000080
#define allowC 0x0000010
#define prefixC 0x0000020
#define allowCD 0x0000001
#define prefixCD 0x0000002
#define prefixcD 0x0000004
#define allowchar 0x1000000
#define allownchar 0x2000000
#define allowCQ 0x4000000
#define prefixCQ 0x8000000
#define prefixcQ 0x0000008
#define __MAXPOW 10
Functions
static LOGICAL lower_check_ast (int ast, int *unused)
void ast_error (const char *s, int ast)
static int conv_bint_ilm (int ast, int ilm, int dtype)
static int conv_bint (int ast)
static int conv_sint_ilm (int ast, int ilm, int dtype)
static int conv_sint (int ast)
static int conv_int_ilm (int ast, int ilm, int dtype)
static int conv_int (int ast)
static int conv_int8_ilm (int ast, int ilm, int dtype)
static int conv_int8 (int ast)
static int conv_word_ilm (int ast, int ilm, int dtype)
static int conv_word (int ast)
static int conv_dword_ilm (int ast, int ilm, int dtype)
static int conv_dword (int ast)
static int conv_blog_ilm (int ast, int ilm, int dtype)
static int conv_blog (int ast)
static int conv_slog_ilm (int ast, int ilm, int dtype)
static int conv_slog (int ast)
static int conv_log_ilm (int ast, int ilm, int dtype)
static int conv_log (int ast)
static int conv_log8_ilm (int ast, int ilm, int dtype)
static int conv_log8 (int ast)
static int conv_real_ilm (int ast, int ilm, int dtype)
static int conv_real (int ast)
static int conv_dble_ilm (int ast, int ilm, int dtype)
static int conv_dble (int ast)
static int conv_cmplx_ilm (int ast, int ilm, int dtype)
static int conv_cmplx (int ast)
static int conv_dcmplx_ilm (int ast, int ilm, int dtype)
static int conv_dcmplx (int ast)
int lower_conv_ilm (int ast, int ilm, int fromdtype, int todtype)
int lower_conv (int ast, int dtype)
char * ltyped (const char *opname, int dtype)
static char * styped (const char *opname, int dtype)
static int lower_bin_arith (int ast, const char *opname, int ldtype, int rdtype)
static int lower_un_arith (int ast, const char *opname, int ldtype)
static int lower_bin_comparison (int ast, const char *op)
static int add_lnop (int ilm, int ast, int dtype)
static int lower_bin_logical (int ast, const char *op)
static int lower_un_logical (int ast, const char *op)
int lower_parenthesize_expression (int ast)
static bool function_null_allowed (SPTR sptr)
int get_byval (int, int)
Return true if param is pass by value.
static int lower_function (int ast)
static int * need_intr_argbf (int nargs)
static int intrin_name (const char *name, int ast, int options)
static int intrin_name_bsik (const char *name, int ast)
static int nearest_real_type (int dtype)
static int intrinsic_null_allowed (int intr)
static int intrinsic_arg_dtype (int intr, int ast, int args, int nargs)
static int f90_function (const char *name, int dtype, int args, int nargs)
static int f90_value_function (const char *name, int dtype, int args, int nargs)
static int f90_value_function_I2 (const char *name, int dtype, int args, int nargs)
static int new_intrin_sym (int ast)
static int lower_intrinsic (int ast)
static int _xtoi (int, int, char *)
static void lower_ast (int ast, int *unused)
int lower_null (void)
int lower_null_arg (void)
int lower_nullc_arg (void)
static int lower_logical_expr (int ast)
void lower_logical (int ast, iflabeltype *iflabp)
static void lower_no_subscr_chk (int ast, int *unused)
void lower_expression (int ast)
Use ast_traverse to lower the expression asts.
void lower_reinit (void)
void lower_exp_finish (void)
Variables
static int intr_argbf [IARGS]
static int * intrinsic_args = intr_argbf
static int intr_argsz = IARGS
Detailed Description
Routines used by lower.c for lowering to ILMs.
Definition in file lowerexp.c.
Macro Definition Documentation
__MAXPOW
#define __MAXPOW 10
allowC
#define allowC 0x0000010
allowCD
#define allowCD 0x0000001
allowchar
#define allowchar 0x1000000
allowCQ
#define allowCQ 0x4000000
allowD
#define allowD 0x0000100
allowI
#define allowI 0x0100000
allowK
#define allowK 0x0010000
allowL
#define allowL 0x0800000
allownchar
#define allownchar 0x2000000
allowQ
#define allowQ 0x0000040
allowR
#define allowR 0x0001000
IARGS
#define IARGS 100
Definition at line 2703 of file lowerexp.c.
in_A_D
#define in_A_D 0x0005300
Definition at line 2692 of file lowerexp.c.
in_A_D_Q
#define in_A_D_Q 0x00053c0
Definition at line 2694 of file lowerexp.c.
in_c
#define in_c 0x1000000
Definition at line 2698 of file lowerexp.c.
in_c_cD
#define in_c_cD 0x0000015
Definition at line 2690 of file lowerexp.c.
in_c_cD_cQ
#define in_c_cD_cQ 0x400001d
Definition at line 2701 of file lowerexp.c.
in_c_nc
#define in_c_nc 0x3000000
Definition at line 2700 of file lowerexp.c.
in_d
#define in_d 0x0000100
Definition at line 2696 of file lowerexp.c.
in_i
#define in_i 0x0100000
Definition at line 2670 of file lowerexp.c.
in_i_64
#define in_i_64 0x0150000
Definition at line 2666 of file lowerexp.c.
in_i_K
#define in_i_K 0x0130000
Definition at line 2660 of file lowerexp.c.
in_I_K
#define in_I_K 0x0330000
Definition at line 2664 of file lowerexp.c.
in_i_k
#define in_i_k 0x0110000
Definition at line 2668 of file lowerexp.c.
in_i_K_A_D
#define in_i_K_A_D 0x0135300
Definition at line 2656 of file lowerexp.c.
in_i_K_A_D_Q
#define in_i_K_A_D_Q 0x01353c0
Definition at line 2658 of file lowerexp.c.
in_I_K_R_D
#define in_I_K_R_D 0x0333300
Definition at line 2647 of file lowerexp.c.
in_I_K_r_D
#define in_I_K_r_D 0x0331300
Definition at line 2652 of file lowerexp.c.
in_I_K_r_D_C_CD
#define in_I_K_r_D_C_CD 0x0331333
Definition at line 2640 of file lowerexp.c.
in_I_K_R_D_C_CD
#define in_I_K_R_D_C_CD 0x0333333
Definition at line 2642 of file lowerexp.c.
in_I_K_r_D_Q
#define in_I_K_r_D_Q 0x03313c0
Definition at line 2654 of file lowerexp.c.
in_il_K
#define in_il_K 0x0930000
Definition at line 2662 of file lowerexp.c.
in_Il_K_R_D
#define in_Il_K_R_D 0x0b33300
Definition at line 2649 of file lowerexp.c.
in_Il_K_R_D_C_CD
#define in_Il_K_R_D_C_CD 0x0b33333
Definition at line 2644 of file lowerexp.c.
in_J_K
#define in_J_K 0x0530000
Definition at line 2672 of file lowerexp.c.
in_nc
#define in_nc 0x2000000
Definition at line 2699 of file lowerexp.c.
in_R_D
#define in_R_D 0x0003300
Definition at line 2674 of file lowerexp.c.
in_r_D
#define in_r_D 0x0001300
Definition at line 2678 of file lowerexp.c.
in_R_D_C_CD
#define in_R_D_C_CD 0x0001333
Definition at line 2682 of file lowerexp.c.
in_r_D_C_CD
#define in_r_D_C_CD 0x0001333
Definition at line 2684 of file lowerexp.c.
in_R_D_Q
#define in_R_D_Q 0x00033c0
Definition at line 2676 of file lowerexp.c.
in_r_D_Q
#define in_r_D_Q 0x00013c0
Definition at line 2680 of file lowerexp.c.
in_R_D_Q_C_CD_CQ
#define in_R_D_Q_C_CD_CQ 0xc0033f3
Definition at line 2686 of file lowerexp.c.
in_r_D_Q_C_CD_CQ
#define in_r_D_Q_C_CD_CQ 0xc0013f3
Definition at line 2688 of file lowerexp.c.
INSIDE_LOWER
#define INSIDE_LOWER
Definition at line 29 of file lowerexp.c.
prefixA
#define prefixA 0x0004000
prefixC
#define prefixC 0x0000020
prefixCD
#define prefixCD 0x0000002
prefixcD
#define prefixcD 0x0000004
prefixCQ
#define prefixCQ 0x8000000
prefixcQ
#define prefixcQ 0x0000008
prefixD
#define prefixD 0x0000200
prefixI
#define prefixI 0x0200000
prefixJ
#define prefixJ 0x0400000
prefixK
#define prefixK 0x0020000
prefixQ
#define prefixQ 0x0000080
prefixR
#define prefixR 0x0002000
suffix64
#define suffix64 0x0040000
Function Documentation
_xtoi()
static int _xtoi (int opn, int pwr, char * opc) static
Definition at line 6277 of file lowerexp.c.
References _xtoi(), n, opn, plower(), and res.
Referenced by _xtoi(), and lower_ast().
add_lnop()
static int add_lnop (int ilm, int ast, int dtype) static
Definition at line 1953 of file lowerexp.c.
References A_OPTYPEG, ast, DTYG, OP_LAND, OP_LEQV, OP_LNEQV, OP_LNOT, OP_LOR, OP_SCAND, plower(), TY_DWORD, TY_INT8, and TY_LOG8.
Referenced by lower_bin_logical(), and lower_un_logical().
ast_error()
void ast_error (const char * s, int ast)
Definition at line 35 of file lowerexp.c.
References ast, dbg_print_ast(), dump_one_ast(), gbl, lerror(), and s.
Referenced by conv_bint_ilm(), conv_blog_ilm(), conv_cmplx_ilm(), conv_dble_ilm(), conv_dcmplx_ilm(), conv_dword_ilm(), conv_int8_ilm(), conv_int_ilm(), conv_log8_ilm(), conv_log_ilm(), conv_real_ilm(), conv_sint_ilm(), conv_slog_ilm(), conv_word_ilm(), fill_recurse(), intrin_name(), intrin_name_bsik(), lower_ast(), lower_base_address(), lower_bin_arith(), lower_bin_comparison(), lower_bin_logical(), lower_conv(), lower_conv_ilm(), lower_do_stmt(), lower_intrinsic(), lower_logical(), lower_ndtypeg(), lower_numelm(), lower_stmt(), lower_typeload(), lower_typestore(), lower_un_arith(), and lower_un_logical().
conv_bint()
static int conv_bint (int ast) static
Definition at line 158 of file lowerexp.c.
References ast, conv_bint_ilm(), and lower_ilm().
Referenced by lower_ast(), and lower_conv().
conv_bint_ilm()
static int conv_bint_ilm (int ast, int ilm, int dtype) static
Definition at line 55 of file lowerexp.c.
References ast, ast_error(), cngcon(), CONVAL2G, cp, DTYG, holtonum(), lower_getintcon(), n, STB::n_base, plower(), s, sptr, stb, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by conv_bint(), and lower_conv_ilm().
conv_blog()
static int conv_blog (int ast) static
Definition at line 704 of file lowerexp.c.
References ast, conv_blog_ilm(), and lower_ilm().
Referenced by lower_ast(), and lower_conv().
conv_blog_ilm()
static int conv_blog_ilm (int ast, int ilm, int dtype) static
Definition at line 648 of file lowerexp.c.
References ast, ast_error(), cngcon(), CONVAL2G, DTYG, FLANG_FALLTHROUGH, lower_getintcon(), plower(), s, TY_BINT, TY_BLOG, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by conv_blog(), and lower_conv_ilm().
conv_cmplx()
static int conv_cmplx (int ast) static
Definition at line 1287 of file lowerexp.c.
References ast, conv_cmplx_ilm(), and lower_ilm().
Referenced by lower_ast(), and lower_conv().
conv_cmplx_ilm()
static int conv_cmplx_ilm (int ast, int ilm, int dtype) static
Definition at line 1200 of file lowerexp.c.
References ast, ast_error(), cngcon(), conv_int_ilm(), CONVAL2G, DTYG, FLANG_FALLTHROUGH, lower_getrealcon(), lowersym, plower(), s, TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by conv_cmplx(), and lower_conv_ilm().
conv_dble()
static int conv_dble (int ast) static
Definition at line 1108 of file lowerexp.c.
References ast, conv_dble_ilm(), and lower_ilm().
Referenced by lower_ast(), lower_conv(), and lower_intrinsic().
conv_dble_ilm()
static int conv_dble_ilm (int ast, int ilm, int dtype) static
Definition at line 1031 of file lowerexp.c.
References ast, ast_error(), cngcon(), conv_int_ilm(), CONVAL2G, DTYG, FLANG_FALLTHROUGH, plower(), s, TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by conv_dble(), and lower_conv_ilm().
conv_dcmplx()
static int conv_dcmplx (int ast) static
Definition at line 1388 of file lowerexp.c.
References ast, conv_dcmplx_ilm(), and lower_ilm().
Referenced by lower_ast(), and lower_conv().
conv_dcmplx_ilm()
static int conv_dcmplx_ilm (int ast, int ilm, int dtype) static
Definition at line 1294 of file lowerexp.c.
References ast, ast_error(), cngcon(), conv_int_ilm(), CONVAL2G, DTYG, FLANG_FALLTHROUGH, lowersym, plower(), s, TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by conv_dcmplx(), and lower_conv_ilm().
conv_dword()
static int conv_dword (int ast) static
Definition at line 641 of file lowerexp.c.
References ast, conv_dword_ilm(), and lower_ilm().
Referenced by lower_ast(), and lower_conv().
conv_dword_ilm()
static int conv_dword_ilm (int ast, int ilm, int dtype) static
Definition at line 568 of file lowerexp.c.
References ast, ast_error(), cngcon(), DTYG, plower(), s, TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by conv_dword(), and lower_conv_ilm().
conv_int()
static int conv_int (int ast) static
Definition at line 374 of file lowerexp.c.
References ast, conv_int_ilm(), and lower_ilm().
Referenced by lower_ast(), lower_conv(), lower_intrinsic(), and lower_logical_expr().
conv_int8()
static int conv_int8 (int ast) static
Definition at line 485 of file lowerexp.c.
References ast, conv_int8_ilm(), and lower_ilm().
Referenced by lower_ast(), lower_conv(), and lower_intrinsic().
conv_int8_ilm()
static int conv_int8_ilm (int ast, int ilm, int dtype) static
Definition at line 381 of file lowerexp.c.
References ast, ast_error(), cngcon(), conv_int_ilm(), CONVAL2G, cp, DTYG, FLG::endian, flg, getcon(), holtonum(), lower_use_datatype(), n, STB::n_base, plower(), s, sptr, stb, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, and XBIT.
Referenced by conv_int8(), conv_log8_ilm(), and lower_conv_ilm().
conv_int_ilm()
static int conv_int_ilm (int ast, int ilm, int dtype) static
Definition at line 277 of file lowerexp.c.
References ast, ast_error(), cngcon(), CONVAL2G, cp, DTYG, holtonum(), lower_getintcon(), n, STB::n_base, plower(), s, sptr, stb, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, and XBIT.
Referenced by conv_cmplx_ilm(), conv_dble_ilm(), conv_dcmplx_ilm(), conv_int(), conv_int8_ilm(), conv_log_ilm(), conv_real_ilm(), and lower_conv_ilm().
conv_log()
static int conv_log (int ast) static
Definition at line 855 of file lowerexp.c.
References ast, conv_log_ilm(), and lower_ilm().
Referenced by lower_ast(), and lower_conv().
conv_log8()
static int conv_log8 (int ast) static
Definition at line 937 of file lowerexp.c.
References ast, conv_log8_ilm(), and lower_ilm().
Referenced by lower_ast(), and lower_conv().
conv_log8_ilm()
static int conv_log8_ilm (int ast, int ilm, int dtype) static
Definition at line 862 of file lowerexp.c.
References ast, ast_error(), astb, cngcon(), conv_int8_ilm(), conv_log_ilm(), CONVAL2G, DTY, DTYG, ASTB::i1, lower_getintcon(), STB::n_base, plower(), s, sptr, stb, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by conv_log8().
conv_log_ilm()
static int conv_log_ilm (int ast, int ilm, int dtype) static
Definition at line 774 of file lowerexp.c.
References ast, ast_error(), astb, cngcon(), conv_int_ilm(), CONVAL2G, DTY, DTYG, ASTB::i1, lower_getintcon(), lower_getlogcon(), STB::n_base, plower(), s, sptr, stb, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by conv_log(), conv_log8_ilm(), and lower_conv_ilm().
conv_real()
static int conv_real (int ast) static
Definition at line 1024 of file lowerexp.c.
References ast, conv_real_ilm(), and lower_ilm().
Referenced by lower_ast(), lower_conv(), and lower_intrinsic().
conv_real_ilm()
static int conv_real_ilm (int ast, int ilm, int dtype) static
Definition at line 944 of file lowerexp.c.
References ast, ast_error(), cngcon(), conv_int_ilm(), conv_real_ilm(), CONVAL2G, DTY, DTYG, lower_getrealcon(), plower(), s, TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by conv_real(), conv_real_ilm(), and lower_conv_ilm().
conv_sint()
static int conv_sint (int ast) static
Definition at line 270 of file lowerexp.c.
References ast, conv_sint_ilm(), and lower_ilm().
Referenced by lower_ast(), and lower_conv().
conv_sint_ilm()
static int conv_sint_ilm (int ast, int ilm, int dtype) static
Definition at line 165 of file lowerexp.c.
References ast, ast_error(), cngcon(), CONVAL2G, cp, DTYG, holtonum(), lower_getintcon(), n, STB::n_base, plower(), s, sptr, stb, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by conv_sint(), and lower_conv_ilm().
conv_slog()
static int conv_slog (int ast) static
Definition at line 767 of file lowerexp.c.
References ast, conv_slog_ilm(), and lower_ilm().
Referenced by lower_ast(), and lower_conv().
conv_slog_ilm()
static int conv_slog_ilm (int ast, int ilm, int dtype) static
Definition at line 711 of file lowerexp.c.
References ast, ast_error(), cngcon(), CONVAL2G, DTYG, lower_getintcon(), plower(), s, TY_BINT, TY_BLOG, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by conv_slog(), and lower_conv_ilm().
conv_word()
static int conv_word (int ast) static
Definition at line 561 of file lowerexp.c.
References ast, conv_word_ilm(), and lower_ilm().
Referenced by lower_ast(), and lower_conv().
conv_word_ilm()
static int conv_word_ilm (int ast, int ilm, int dtype) static
Definition at line 492 of file lowerexp.c.
References ast, ast_error(), cngcon(), DTYG, lower_getintcon(), plower(), s, TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by conv_word(), and lower_conv_ilm().
f90_function()
static int f90_function (const char * name, int dtype, int args, int nargs) static
Definition at line 3510 of file lowerexp.c.
References args, ARGT_ARG, FALSE, i, intrinsic_args, lower_base(), lower_makefunc(), ltyped(), name, nargs, need_intr_argbf(), and plower().
Referenced by lower_intrinsic().
f90_value_function()
static int f90_value_function (const char * name, int dtype, int args, int nargs) static
Definition at line 3523 of file lowerexp.c.
References args, ARGT_ARG, FALSE, i, intrinsic_args, lower_ilm(), lower_makefunc(), ltyped(), name, nargs, need_intr_argbf(), and plower().
Referenced by lower_intrinsic().
f90_value_function_I2()
static int f90_value_function_I2 (const char * name, int dtype, int args, int nargs) static
Definition at line 3539 of file lowerexp.c.
References args, ARGT_ARG, ast, DT_INT, FALSE, i, intrinsic_args, lower_conv_ilm(), lower_ilm(), lower_makefunc(), ltyped(), name, nargs, need_intr_argbf(), and plower().
Referenced by lower_intrinsic().
function_null_allowed()
static bool function_null_allowed (SPTR sptr) static
Definition at line 2121 of file lowerexp.c.
References i, mkRteRtnNm(), RTE_associated, RTE_associated_chara, RTE_associated_t, RTE_associated_tchara, RTE_conformable_11v, RTE_conformable_1dv, RTE_conformable_22v, RTE_conformable_2dv, RTE_conformable_33v, RTE_conformable_3dv, RTE_conformable_d1v, RTE_conformable_d2v, RTE_conformable_d3v, RTE_conformable_dd, RTE_conformable_dnv, RTE_conformable_ndv, RTE_conformable_nnv, RTE_extends_type_of, RTE_lena, RTE_lentrima, RTE_no_rtn, RTE_same_type_as, sptr, and SYMNAME.
Referenced by lower_function().
get_byval()
int get_byval (int func_sptr, int param_sptr)
Return true if param is pass by value.
Definition at line 457 of file semfunc.c.
References find_byval_ref(), and PASS_BYVAL.
intrin_name()
static int intrin_name (const char * name, int ast, int options) static
Definition at line 2723 of file lowerexp.c.
References allowC, allowCD, allowchar, allowCQ, allowD, allowI, allowK, allowL, allownchar, allowQ, allowR, ast, ast_error(), DTYG, name, plower(), prefix, prefixA, prefixC, prefixCD, prefixcD, prefixCQ, prefixcQ, prefixD, prefixI, prefixJ, prefixK, prefixQ, prefixR, suffix, suffix64, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by lower_intrinsic().
intrin_name_bsik()
static int intrin_name_bsik (const char * name, int ast) static
Definition at line 2857 of file lowerexp.c.
References ast, ast_error(), DTYG, name, plower(), prefix, TY_BINT, TY_BLOG, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by lower_intrinsic().
intrinsic_arg_dtype()
static int intrinsic_arg_dtype (int intr, int ast, int args, int nargs) static
Definition at line 2942 of file lowerexp.c.
References args, ARGT_ARG, ast, I_AND, I_OR, I_XOR, I_ZEXT, intrinsic_args, lower_base(), lower_conv(), nearest_real_type(), and NEW_INTRIN.
Referenced by lower_intrinsic().
intrinsic_null_allowed()
static int intrinsic_null_allowed (int intr) static
Definition at line 2926 of file lowerexp.c.
References FALSE, and TRUE.
Referenced by lower_intrinsic().
lower_ast()
static void lower_ast (int ast, int * unused) static
Definition at line 5227 of file lowerexp.c.
References __MAXPOW, _xtoi(), A_MEM_ORDERG, A_OPTYPEG, ADD_LWAST, ADD_LWBD, ADD_UPAST, ASD_NDIM, ASD_SUBS, ast, ast_error(), astb, base, ASTB::bnd, check_member(), cngcon(), conv_bint(), conv_blog(), conv_cmplx(), conv_dble(), conv_dcmplx(), conv_dword(), conv_int(), conv_int8(), conv_log(), conv_log8(), conv_real(), conv_sint(), conv_slog(), conv_word(), CONVAL2G, CUDA_DEVICE, CUDA_GLOBAL, CUDAG, DDTG, DT_PTR, DTY, DTYG, eq_dtype(), FALSE, FLANG_FALLTHROUGH, flg, GBL_CURRFUNC, get_global_extent_index(), get_global_lower_index(), get_multiplier_index(), get_section_offset_index(), get_section_stride_index(), get_xbase_index(), i, ASTB::i1, FLG::ieee, is_iso_cptr(), len, lerror(), lower_ast(), lower_base(), lower_bin_arith(), lower_bin_comparison(), lower_bin_logical(), lower_check_subscript(), lower_conv(), lower_conv_ilm(), lower_disable_subscr_chk, lower_expression(), lower_function(), lower_getintcon(), lower_getiszcon(), lower_ilm(), lower_intrinsic(), lower_makefunc(), lower_null(), lower_null_arg(), lower_nullc_arg(), lower_replacement(), lower_typeload(), lower_un_arith(), lower_un_logical(), lower_visit_symbol(), lowersym, ltyped(), mkRteRtnNm(), ndim, normalize_bounds(), ASTB::one, OP_ADD, OP_AIF, OP_BYVAL, OP_CAT, OP_CMP, OP_CON, OP_DIV, OP_EQ, OP_FUNC, OP_GE, OP_GT, OP_LAND, OP_LD, OP_LE, OP_LEQV, OP_LNEQV, OP_LNOT, OP_LOC, OP_LOG, OP_LOR, OP_LT, OP_MUL, OP_NE, OP_NEG, OP_REF, OP_SCAND, OP_ST, OP_SUB, OP_VAL, OP_XTOI, OP_XTOX, PARAMVALG, plower(), ASTB::ptr0, ASTB::ptr0c, RTE_loc, sptr, ss, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, XBIT, and ASTB::zero.
Referenced by lower_ast(), lower_check_ast(), lower_expression(), and lower_no_subscr_chk().
lower_bin_arith()
static int lower_bin_arith (int ast, const char * opname, int ldtype, int rdtype) static
Definition at line 1752 of file lowerexp.c.
References ast, ast_error(), DTYG, lower_conv(), ltyped(), plower(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by lower_ast().
lower_bin_comparison()
static int lower_bin_comparison (int ast, const char * op) static
Definition at line 1848 of file lowerexp.c.
References ast, ast_error(), base, DTYG, lower_base(), lower_conv(), lower_ilm(), plower(), styped(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by lower_ast().
lower_bin_logical()
static int lower_bin_logical (int ast, const char * op) static
Definition at line 1993 of file lowerexp.c.
References add_lnop(), ast, ast_error(), DTYG, lower_conv(), plower(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by lower_ast(), and lower_logical().
lower_check_ast()
static LOGICAL lower_check_ast (int ast, int * unused) static
Definition at line 6629 of file lowerexp.c.
References A_OPTYPEG, argt, ARGT_ARG, ast, ast_traverse(), FALSE, i, lower_ast(), lower_check_ast(), lower_no_subscr_chk(), memsym_of_ast(), mkRteRtnNm(), ndim, NULL, RTE_lena, SHD_LWB, SHD_NDIM, SHD_UPB, SYMNAME, and TRUE.
Referenced by lower_check_ast(), lower_expression(), and lower_no_subscr_chk().
lower_conv()
int lower_conv (int ast, int dtype)
Definition at line 1555 of file lowerexp.c.
References ast, ast_error(), conv_bint(), conv_blog(), conv_cmplx(), conv_dble(), conv_dcmplx(), conv_dword(), conv_int(), conv_int8(), conv_log(), conv_log8(), conv_real(), conv_sint(), conv_slog(), conv_word(), DTY, DTYG, eq_dtype(), lerror(), lower_conv(), lower_ilm(), TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by intrinsic_arg_dtype(), llvm_omp_sched(), lower_ast(), lower_bin_arith(), lower_bin_comparison(), lower_bin_logical(), lower_conv(), lower_do_stmt(), lower_intrinsic(), lower_omp_atomic_capture(), lower_omp_atomic_update(), lower_omp_atomic_write(), lower_stmt(), lower_un_arith(), and lower_un_logical().
lower_conv_ilm()
int lower_conv_ilm (int ast, int ilm, int fromdtype, int todtype)
Definition at line 1491 of file lowerexp.c.
References ast, ast_error(), conv_bint_ilm(), conv_blog_ilm(), conv_cmplx_ilm(), conv_dble_ilm(), conv_dcmplx_ilm(), conv_dword_ilm(), conv_int8_ilm(), conv_int_ilm(), conv_log_ilm(), conv_real_ilm(), conv_sint_ilm(), conv_slog_ilm(), conv_word_ilm(), DTYG, lerror(), TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by compute_dotrip(), f90_value_function_I2(), lower_ast(), lower_do_stmt(), lower_intrinsic(), lower_logical(), lower_stmt(), put_adjarr_bounds(), and set_mp_loop_var().
lower_exp_finish()
void lower_exp_finish (void)
Definition at line 6694 of file lowerexp.c.
References FREE, IARGS, intr_argbf, intr_argsz, and intrinsic_args.
Referenced by lower().
lower_expression()
void lower_expression (int ast)
Use ast_traverse to lower the expression asts.
Definition at line 6680 of file lowerexp.c.
References ast, ast_traverse(), lower_ast(), lower_check_ast(), and NULL.
Referenced by add_nullify(), export_data_asts(), export_data_varlist_asts(), handle_arguments(), llvm_omp_sched(), lower_ast(), lower_do_stmt(), lower_function(), lower_intrinsic(), lower_logical(), lower_numelm(), lower_omp_atomic_capture(), lower_omp_atomic_update(), lower_omp_atomic_write(), lower_omp_target_tripcount(), lower_replacement(), lower_stmt(), put_adjarr_bounds(), and set_mp_loop_var().
lower_function()
static int lower_function (int ast) static
Definition at line 2160 of file lowerexp.c.
References a, A_ARGCNTG, A_OPTYPEG, args, ARGT_ARG, assert, ast, aux, check_return(), CLASS_MEM, count, AUX::dpdsc_base, dt, STB::dt_int, DTY, DTYG, find_dummy_position(), FLANG_FALLTHROUGH, function_null_allowed(), gbl, get_implementation(), get_specific_member(), get_static_type_descriptor(), get_tbp_argno(), get_type_descr_arg(), i, is_iso_cloc(), is_procedure_ptr(), IS_TBP, is_tbp(), is_unl_poly(), lower_argument, lower_argument_size, lower_base(), lower_disable_ptr_chk, lower_expression(), lower_ilm(), lower_parenthesize_expression(), lower_scalar_temp(), lower_target(), ltyped(), max_binding_invobj(), memsym_of_ast(), NEED, NOSYM, OP_BYVAL, params, pass_sym_of_ast(), plower(), plower_arg(), proc_arg_needs_proc_desc(), procsym_of_ast(), sptr, stb, sym_of_ast(), TY_CHAR, TY_CMPLX, TY_DCMPLX, TY_INT8, TY_NCHAR, STB::user, and XBIT.
Referenced by lower_ast(), and lower_intrinsic().
lower_intrinsic()
static int lower_intrinsic (int ast) static
Definition at line 3575 of file lowerexp.c.
References A_ARGCNTG, A_OPTYPEG, ADD_LWAST, ADD_LWBD, arg, args, ARGT_ARG, ast, ast_error(), astb, ASTB::bnd, check_member(), cnt, conv_dble(), conv_int(), conv_int8(), conv_real(), CONVAL2G, DDTG, DT_INT, STB::dt_log, DT_LOG, DT_PTR, DTY, DTYG, f90_function(), f90_value_function(), f90_value_function_I2(), FALSE, find_array(), FLANG_FALLTHROUGH, i, I_AND, I_OR, I_XOR, I_ZEXT, in_A_D, in_A_D_Q, in_c, in_c_cD_cQ, in_d, in_i, in_i_K, in_I_K, in_i_k, in_i_K_A_D_Q, in_I_K_R_D, in_I_K_r_D_C_CD, in_I_K_r_D_Q, in_il_K, in_Il_K_R_D_C_CD, in_J_K, in_nc, in_r_D, in_r_D_C_CD, in_R_D_Q, in_r_D_Q, in_R_D_Q_C_CD_CQ, in_r_D_Q_C_CD_CQ, intast_sym, intrin_name(), intrin_name_bsik(), intrinsic_arg_dtype(), intrinsic_args, intrinsic_null_allowed(), is_iso_cloc(), lb, lerror(), lower_address(), lower_base(), lower_base_sptr(), lower_conv(), lower_conv_ilm(), lower_disable_ptr_chk, lower_expression(), lower_function(), lower_getintcon(), lower_getiszcon(), lower_getlogcon(), lower_ilm(), lower_makefunc(), lower_null_arg(), lower_target(), lower_typeload(), lowersym, ltyped(), mk_coercion_func_name(), mkRteRtnNm(), nargs, need_intr_argbf(), NEW_INTRIN, new_intrin_sym(), num, ASTB::one, plower(), RTE_allocated, RTE_expondx, RTE_exponqx, RTE_exponx, RTE_fracdx, RTE_fracqx, RTE_fracx, RTE_indexa, RTE_is_contiguous, RTE_lb, RTE_lentrima, RTE_nearestdx, RTE_nearestqx, RTE_nearestx, RTE_no_rtn, RTE_nverify, RTE_present, RTE_present_ptr, RTE_presentc, RTE_rrspacingdx, RTE_rrspacingqx, RTE_rrspacingx, RTE_scaledx, RTE_scaleqx, RTE_scalex, RTE_scana, RTE_setexpdx, RTE_setexpqx, RTE_setexpx, RTE_size, RTE_spacingdx, RTE_spacingqx, RTE_spacingx, RTE_ub, RTE_verifya, SCFTN_TRUE, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, sptr, stb, styped(), SYMNAME, TRUE, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, ty_to_lib, STB::user, and XBIT.
Referenced by lower_ast().
lower_logical()
void lower_logical (int ast, iflabeltype * iflabp)
Definition at line 6331 of file lowerexp.c.
References A_OPTYPEG, ast, ast_error(), CONVAL2G, DTYG, lower_bin_logical(), lower_conv_ilm(), lower_expression(), lower_lab(), lower_logical(), lower_logical_expr(), lower_reinit(), lower_visit_symbol(), lowersym, ltyped(), OP_EQ, OP_GE, OP_GT, OP_LAND, OP_LE, OP_LEQV, OP_LNEQV, OP_LNOT, OP_LOR, OP_LT, OP_NE, OP_SCAND, plower(), sptr, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_REAL, TY_SINT, TY_SLOG, and XBIT.
Referenced by lower_logical(), and lower_stmt().
lower_logical_expr()
static int lower_logical_expr (int ast) static
Definition at line 6309 of file lowerexp.c.
References ast, conv_int(), lower_ilm(), TY_BINT, TY_BLOG, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_SINT, and TY_SLOG.
Referenced by lower_logical().
lower_no_subscr_chk()
static void lower_no_subscr_chk (int ast, int * unused) static
Definition at line 6610 of file lowerexp.c.
References A_ARGCNTG, argt, ARGT_ARG, ast, ast_traverse(), cnt, i, lower_ast(), lower_check_ast(), lower_disable_subscr_chk, and NULL.
Referenced by lower_check_ast().
lower_null()
int lower_null (void)
Definition at line 6235 of file lowerexp.c.
References lowersym, plower(), and XBIT.
Referenced by add_nullify(), lower_ast(), lower_pointer_init(), and lower_stmt().
lower_null_arg()
int lower_null_arg (void)
Definition at line 6250 of file lowerexp.c.
References lowersym, lowersym_pghpf_cmem(), plower(), and XBIT.
Referenced by lower_ast(), lower_intrinsic(), and lower_stmt().
lower_nullc_arg()
int lower_nullc_arg (void)
Definition at line 6260 of file lowerexp.c.
References lowersym, lowersym_pghpf_cmem(), plower(), and XBIT.
Referenced by lower_ast(), and lower_stmt().
lower_parenthesize_expression()
int lower_parenthesize_expression (int ast)
Definition at line 2096 of file lowerexp.c.
References a, ast, astb, DT_ISLOG, DT_ISNUMERIC, lower_scalar_temp(), lower_typestore(), plower(), ASTB::ptr0, ASTB::ptr0c, and ASTB::ptr1.
Referenced by handle_arguments(), and lower_function().
lower_reinit()
void lower_reinit (void)
Definition at line 6686 of file lowerexp.c.
References ast_revisit(), ast_unvisit_norepl(), ast_visit(), and lower_clear_opt().
Referenced by lower_do_stmt(), lower_logical(), and lower_stmt().
lower_un_arith()
static int lower_un_arith (int ast, const char * opname, int ldtype) static
Definition at line 1802 of file lowerexp.c.
References ast, ast_error(), DTYG, lower_conv(), ltyped(), plower(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by lower_ast().
lower_un_logical()
static int lower_un_logical (int ast, const char * op) static
Definition at line 2045 of file lowerexp.c.
References add_lnop(), ast, ast_error(), DTYG, lower_conv(), plower(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by lower_ast().
ltyped()
char * ltyped (const char * opname, int dtype)
Definition at line 1629 of file lowerexp.c.
References DTYG, lerror(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, and XBIT.
Referenced by compute_dotrip(), f90_function(), f90_value_function(), f90_value_function_I2(), llvm_lower_enddo_stmt(), llvm_omp_sched(), lower_ast(), lower_bin_arith(), lower_do_stmt(), lower_enddo_stmt(), lower_function(), lower_intrinsic(), lower_logical(), lower_stmt(), lower_un_arith(), and set_loop_bound().
nearest_real_type()
static int nearest_real_type (int dtype) static
Definition at line 2896 of file lowerexp.c.
References DT_DBLE, DT_REAL, DTY, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT8, TY_LOG8, and TY_QUAD.
Referenced by intrinsic_arg_dtype().
need_intr_argbf()
static int * need_intr_argbf (int nargs) static
Definition at line 2709 of file lowerexp.c.
References IARGS, intr_argsz, intrinsic_args, nargs, NEED, and NEW.
Referenced by f90_function(), f90_value_function(), f90_value_function_I2(), and lower_intrinsic().
new_intrin_sym()
static int new_intrin_sym (int ast) static
Definition at line 3558 of file lowerexp.c.
References ast, DTY, sptr, TY_CMPLX, and TY_DCMPLX.
Referenced by lower_intrinsic().
styped()
static char * styped (const char * opname, int dtype) static
Definition at line 1694 of file lowerexp.c.
References DTYG, lerror(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, and TY_SLOG.
Referenced by lower_bin_comparison(), and lower_intrinsic().
Variable Documentation
intr_argbf
int intr_argbf[IARGS] static
Definition at line 2704 of file lowerexp.c.
Referenced by lower_exp_finish().
intr_argsz
int intr_argsz = IARGS static
Definition at line 2706 of file lowerexp.c.
Referenced by lower_exp_finish(), and need_intr_argbf().
intrinsic_args
int* intrinsic_args = intr_argbf static
Definition at line 2705 of file lowerexp.c.
Referenced by f90_function(), f90_value_function(), f90_value_function_I2(), intrinsic_arg_dtype(), lower_exp_finish(), lower_intrinsic(), and need_intr_argbf().