flang: lowersym.c File Reference
lowersym.c File Reference
Routines used by lower.c for lowering symbols.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "ast.h"
#include "semant.h"
#include "dinit.h"
#include "soc.h"
#include "pragma.h"
#include "rte.h"
#include "fih.h"
#include "dpm_out.h"
#include "rtlRtns.h"
#include "sharedefs.h"
#include "llmputil.h"
#include "lower.h"
#include "dbg_out.h"
Classes
struct initem
struct old_dscp
Macros
#define INSIDE_LOWER
#define STB_LOWER() ((gbl.outfil == lowersym.lowerfile) && gbl.stbfil)
#define IS_STB_FILE() (gbl.stbfil == lowersym.lowerfile)
#define PERM_AREA 8
#define STASH(p) strcpy(getitem(PERM_AREA, strlen(p) + 1), p);
Typedefs
typedef struct initem INITEM
typedef struct old_dscp OLD_DPDSC
Enumerations
enum LEN { ASSCHAR = -1 , ADJCHAR = -2 , DEFERCHAR = -3 }
ASSCHAR = -1 assumed size character ADJCHAR = -2 backend maps to DT_ASSCHAR DEFERCHAR = -3 deferred-length character.
Functions
void scan_for_dwarf_module ()
int print_file (int fihx)
static int valid_kind_parm_expr (int ast)
static int is_descr_expression (int ast)
static int lower_getnull (void)
static void _stb_fixup_ifacearg (int)
static void lower_put_datatype (int, int)
static bool has_opt_args (SPTR sptr)
Returns true if the procedure (sptr) has optional arguments.
static void lower_fileinfo_llvm ()
static void stb_lower_sym_header ()
static void check_debug_alias (SPTR sptr)
Inspect a common block variable symbol to see if it has a alias name, if YES, write to ilm file with attribute "has_alias" be 1 and followed by the length and name of the alias; if NO, put 0 to "has_alias".
void lower_set_symbols (void)
Set 'EXTRA' bit for arrays, descriptors, array members that have IPA no conflict information, or that are compiler temps, or that can't conflict because they aren't targets and aren't pointers.
void lower_set_craypointer (void)
Set datatype of 'cray pointers' to derived types.
void lower_unset_symbols (void)
Reset data types of derived type pointers to DT_PTR.
static void lower_make_all_descriptors (void)
static int remove_list (int list, int sym)
static void push_lower_refd_list (int sym)
static void fill_fixed_array_dtype (int dtype)
static void fill_pointer_array_dtype (int dtype, int sptr)
static int adjarr_class (int sptr)
static int get_atmp (int tempsc, int dt, int saveg)
static void fill_adjustable_array_dtype (int dtype, int assumedshape, int stride1, int tempsc, int alltemp, int keeptemp, int saveg, int sptr)
static void lower_prepare_symbols ()
static void lower_finish_symbols (void)
void lower_pointer_init (void)
static void replace_fval_in_params (SPTR entry, SPTR entrysame)
static void replace_sptr_in_ast (SPTR sptr)
static void add_replace_map (SPTR sptr, SPTR newsptr)
static void replace_fval_in_ast (SPTR fval, SPTR fvalsame)
void lower_init_sym (void)
void lower_finish_sym (void)
void lower_add_func_call (int level, long objoffset, long offset, char *name, char *cname, char *filename, char which, int staticbase, int size)
void create_static_base (int blockname)
...
static void putvline (const char *n, ISZ_T v)
static void putbit (const char *bitname, int bit)
static void putsym (const char *valname, int sym)
static void putval (const char *valname, ISZ_T val)
static void putival (const char *valname, int val)
static void putlval (const char *valname, long val)
static void putpair (int first, int second)
static void puthex (int hex)
static void putstring (const char *s)
static void putwhich (const char *s, const char *ss)
void lower_fileinfo (void)
Print file table information.
void lower_sym_header (void)
static void set_common_size (int common)
void lower_common_sizes (void)
Mark all commons to be exported, and fill in sizes for compiler commons that are unfinished.
static void check_additional_common (int newcom)
static int makefvallocal (int rutype, int fval)
void lower_visit_symbol (int sptr)
static LOGICAL notimplicit (int sptr)
void lower_check_generics (void)
void lower_outer_symbols (void)
For contained subprograms, mark all the regular symbols of the host subprogram.
void lower_use_datatype (int dtype, int usage)
static int eval_con_expr (int ast, int *val, int *dtyp)
static void lower_put_datatype_stb (int dtype)
void lower_data_types (void)
Lower all of the data types.
void lower_push (int value)
int lower_pop (void)
void lower_check_stack (int check)
int lower_getintcon (int val)
int lower_getiszcon (ISZ_T val)
int lower_getlogcon (int val)
int lower_getrealcon (int val)
void lower_namelist_plists (void)
void lower_linearized (void)
Convert the datatype for linearized arrays to assumed-size array.
static int find_nmptr (const char *symname, int len)
static int lower_newsymbol (const char *name, int stype, int dtype, int sclass)
int lower_newfunc (const char *name, int stype, int dtype, int sclass)
int lower_makefunc (const char *name, int dtype, LOGICAL isDscSafe)
void lower_clear_visit_fields (void)
static int lower_cmptrvar (const char *, int, int, int *)
void lower_add_pghpf_commons (void)
Add common blocks to hold various zeros.
static const char * putstype (int stype, int sptr)
static const char * putsclass (int sclass, int sptr)
static void lower_symbol (int sptr)
static void lower_symbol_stb (int sptr)
static void propagate_byval_visit (int sptr)
void lower_symbols (void)
void lower_reset_temps (void)
Reset temps for next statement.
int lower_scalar_temp (int dtype)
Return a symbol which is a temp scalar of DTYPE 'dtype'.
void lower_fill_member_parent (void)
For an ST_MEMBER of an anonymous structure/union, fill member_parent[sptr] with the symbol name of its parent structure.
void lower_mark_entries (void)
int lower_lab (void)
int lowersym_pghpf_cmem (int *whichmem)
static void llvm_check_retval_inargs (int sptr)
void stb_fixup_llvmiface ()
void uncouple_callee_args ()
Variables
static char * datatype_used
static char * datatype_output
static int last_datatype_used
static LOGICAL lower_linearized_dtypes = FALSE
static int stack_top
static int stack_size
static int * stack
static int curr_findex
int * lower_argument
List of ILMs for function/subroutine arguments.
int lower_argument_size
static int lower_pointer_list_head
static int lower_refd_list_head
static ISZ_T private_addr
struct lower_syms lowersym
static int first_avail_scalarptr_temp
static int first_used_scalarptr_temp
static int first_temp
static int first_avail_scalar_temp
static int first_used_scalar_temp
static LOGICAL llvm_iface_flag = FALSE
int pghpf_type_sptr
int pghpf_local_mode_sptr
static INITEM * inlist = NULL
static INITEM * inlistend = NULL
static int saveblockname = 0
static OLD_DPDSC * save_dpdsc = NULL
static int save_dpdsc_cnt = 0
Detailed Description
Routines used by lower.c for lowering symbols.
Definition in file lowersym.c.
Macro Definition Documentation
INSIDE_LOWER
#define INSIDE_LOWER
Definition at line 32 of file lowersym.c.
IS_STB_FILE
#define IS_STB_FILE () (gbl.stbfil == lowersym.lowerfile)
Definition at line 49 of file lowersym.c.
PERM_AREA
#define PERM_AREA 8
Definition at line 1532 of file lowersym.c.
STASH
#define STASH (p) strcpy(getitem(PERM_AREA, strlen(p) + 1), p);
Definition at line 1533 of file lowersym.c.
STB_LOWER
#define STB_LOWER () ((gbl.outfil == lowersym.lowerfile) && gbl.stbfil)
Definition at line 48 of file lowersym.c.
Typedef Documentation
INITEM
typedef struct initem INITEM
OLD_DPDSC
typedef struct old_dscp OLD_DPDSC
Enumeration Type Documentation
LEN
enum LEN
ASSCHAR = -1 assumed size character ADJCHAR = -2 backend maps to DT_ASSCHAR DEFERCHAR = -3 deferred-length character.
Enumerator
ASSCHAR
ADJCHAR
DEFERCHAR
Definition at line 92 of file lowersym.c.
Function Documentation
_stb_fixup_ifacearg()
static void _stb_fixup_ifacearg (int sptr) static
Definition at line 5625 of file lowersym.c.
References aux, old_dscp::dpdsc, AUX::dpdsc_base, FALSE, fix_class_args(), old_dscp::fval, i, interface_for_llvmiface(), llvm_check_retval_inargs(), llvm_iface_flag, lower_visit_symbol(), NEED, NEW, newargs_for_llvmiface(), old_dscp::paramct, params, save_dpdsc, save_dpdsc_cnt, sptr, old_dscp::sptr, TRUE, and undouble_callee_args_llvmf90().
Referenced by stb_fixup_llvmiface().
add_replace_map()
static void add_replace_map (SPTR sptr, SPTR newsptr) inline static
Definition at line 1292 of file lowersym.c.
References NOSYM, and sptr.
Referenced by replace_fval_in_ast().
adjarr_class()
static int adjarr_class (int sptr) static
Definition at line 611 of file lowersym.c.
References sptr, and XBIT.
Referenced by lower_prepare_symbols().
check_additional_common()
static void check_additional_common (int newcom) static
Definition at line 1924 of file lowersym.c.
References CMEMLG, CMEMLP, HASH_ID, STB::hashtb, lower_use_datatype(), lower_visit_symbol(), NOSYM, s, set_common_size(), stb, strlen(), and SYMNAME.
Referenced by lower_visit_symbol().
check_debug_alias()
static void check_debug_alias (SPTR sptr) static
Inspect a common block variable symbol to see if it has a alias name, if YES, write to ilm file with attribute "has_alias" be 1 and followed by the length and name of the alias; if NO, put 0 to "has_alias".
Definition at line 5719 of file lowersym.c.
References ref_symbol::altname, dbgref_symbol, gbl, lowersym, putbit(), RU_BDATA, sptr, module_altname::sptr, strlen(), and SYMNAME.
Referenced by lower_symbol().
create_static_base()
void create_static_base (int blockname)
...
Definition at line 1563 of file lowersym.c.
eval_con_expr()
static int eval_con_expr (int ast, int * val, int * dtyp) static
Definition at line 2482 of file lowersym.c.
References A_OPTYPEG, ast, complex_alias(), const_fold(), CONVAL2G, eval_con_expr(), negate_const(), OP_LNOT, OP_SUB, and val.
Referenced by eval_con_expr(), and lower_put_datatype().
fill_adjustable_array_dtype()
static void fill_adjustable_array_dtype (int dtype, int assumedshape, int stride1, int tempsc, int alltemp, int keeptemp, int saveg, int sptr) static
Definition at line 653 of file lowersym.c.
References ad_val_of(), ADD_EXTNTAST, ADD_LWAST, ADD_MLPYR, ADD_NUMDIM, ADD_UPAST, ADD_ZBASE, astb, ASTB::bnd, CONVAL2G, get_atmp(), i, ISZ_T, lower_getiszcon(), lower_visit_symbol(), lowersym, mk_cnst(), mk_id(), ndim, ASTB::one, sptr, XBIT, and zbase.
Referenced by lower_prepare_symbols().
fill_fixed_array_dtype()
static void fill_fixed_array_dtype (int dtype) static
Definition at line 474 of file lowersym.c.
References ad_val_of(), ADD_LWAST, ADD_MLPYR, ADD_NUMDIM, ADD_NUMELM, ADD_UPAST, ADD_ZBASE, astb, ASTB::bnd, i, ISZ_T, lerror(), lower_getiszcon(), lower_visit_symbol(), m, mk_cnst(), ndim, valid_kind_parm_expr(), zbase, and ASTB::zero.
Referenced by lower_prepare_symbols().
fill_pointer_array_dtype()
static void fill_pointer_array_dtype (int dtype, int sptr) static
Definition at line 564 of file lowersym.c.
References a, ADD_EXTNTAST, ADD_LWAST, ADD_MLPYR, ADD_NUMDIM, ADD_NUMELM, ADD_UPAST, ADD_ZBASE, astb, get_desc_gsize(), get_extent(), get_global_lower(), get_local_multiplier(), get_xbase(), i, ASTB::i1, lerror(), mk_binop(), ndim, OP_ADD, OP_SUB, sptr, and SYMNAME.
Referenced by lower_prepare_symbols().
find_nmptr()
static int find_nmptr (const char * symname, int len) static
Definition at line 3286 of file lowersym.c.
References HASH_ID, STB::hashtb, len, putsname(), stb, and SYMNAME.
Referenced by lower_newsymbol().
get_atmp()
static int get_atmp (int tempsc, int dt, int saveg) static
Definition at line 640 of file lowersym.c.
References dt, getccsym(), lowersym, and s.
Referenced by fill_adjustable_array_dtype().
has_opt_args()
static bool has_opt_args (SPTR sptr) static
Returns true if the procedure (sptr) has optional arguments.
Definition at line 97 of file lowersym.c.
References aux, AUX::dpdsc_base, i, nargs, and sptr.
Referenced by lower_symbol().
is_descr_expression()
static int is_descr_expression (int ast) static
Definition at line 5380 of file lowersym.c.
References A_OPTYPEG, ARGT_ARG, ast, i, is_descr_expression(), memsym_of_ast(), and sptr.
Referenced by is_descr_expression(), and lower_put_datatype().
llvm_check_retval_inargs()
static void llvm_check_retval_inargs (int sptr) static
Definition at line 5542 of file lowersym.c.
References aux, AUX::dpdsc_base, DT_CPTR, DTY, fix_class_args(), FLANG_FALLTHROUGH, is_iso_cptr(), llvm_fix_args(), makefvallocal(), RU_FUNC, sptr, TY_CHAR, TY_DCMPLX, and TY_NCHAR.
Referenced by _stb_fixup_ifacearg().
lower_add_func_call()
void lower_add_func_call (int level, long objoffset, long offset, char * name, char * cname, char * filename, char which, int staticbase, int size)
Definition at line 1536 of file lowersym.c.
References initem::cname, filename, getitem(), inlist, inlistend, level(), name, initem::next, NULL, initem::objoffset, offset, p, PERM_AREA, size, STASH, initem::staticbase, and initem::which.
lower_add_pghpf_commons()
void lower_add_pghpf_commons (void)
Add common blocks to hold various zeros.
common/pghpf_0/ pghpf_01, pghpf_02, pghpf_03, pghpf_04
integer pghpf_01, pghpf_02, pghpf_03, pghpf_04
common/pghpf_0c/ pghpf_0c
character*1 pghpf_0c
common /pghpf_lineno/ pghpf_lineno
common /pghpf_np/ hpf_np$
common /pghpf_me/ hpf_me$
Definition at line 3376 of file lowersym.c.
References astb, CMEMLP, DLL_IMPORT, DLLP, DT_PTR, gbl, get_type(), getstring(), ASTB::i1, lower_cmptrvar(), lower_newsymbol(), lower_use_datatype(), lowersym, NOSYM, size_of(), strlen(), TY_CHAR, and XBIT.
Referenced by lower(), and lowersym_pghpf_cmem().
lower_check_generics()
void lower_check_generics (void)
Definition at line 2260 of file lowersym.c.
References STB::firstosym, lower_use_datatype(), lower_visit_symbol(), notimplicit(), s, sptr, stb, SYMI_NEXT, SYMI_SPTR, and XBIT.
Referenced by lower().
lower_check_stack()
void lower_check_stack (int check)
Definition at line 3130 of file lowersym.c.
References check(), interr(), stack, and stack_top.
Referenced by llvm_lower_enddo_stmt(), lower_enddo_stmt(), and lower_stmt().
lower_clear_visit_fields()
void lower_clear_visit_fields (void)
Definition at line 3349 of file lowersym.c.
References sptr, and stb.
Referenced by lower().
lower_cmptrvar()
static int lower_cmptrvar (const char * name, int stype, int dtype, int * bsym) static
Definition at line 3459 of file lowersym.c.
References assert, DT_PTR, len, lower_newsymbol(), name, strlen(), and XBIT.
Referenced by lower_add_pghpf_commons().
lower_common_sizes()
void lower_common_sizes (void)
Mark all commons to be exported, and fill in sizes for compiler commons that are unfinished.
Definition at line 1899 of file lowersym.c.
References gbl, lower_visit_symbol(), NOSYM, s, set_common_size(), and sptr.
Referenced by lower().
lower_data_types()
void lower_data_types (void)
Lower all of the data types.
Definition at line 3100 of file lowersym.c.
References datatype_used, dlen(), STB::dt, DTY, last_datatype_used, lower_put_datatype_stb(), and stb.
Referenced by lower().
lower_fileinfo()
void lower_fileinfo (void)
Print file table information.
Definition at line 1687 of file lowersym.c.
References curr_findex, dirname, FIH_DIRNAME, FIH_FILENAME, FIH_FLAGS, FIH_FULLNAME, FIH_FUNCNAME, FIH_FUNCTAG, FIH_LEVEL, FIH_LINENO, FIH_NEXT, FIH_PARENT, FIH_SRCLINE, fihb, filename, GBL_SIZE_T_FORMAT, lower_fileinfo_llvm(), lowersym, NULL, FIHB::stg_avail, and strlen().
Referenced by lower().
lower_fileinfo_llvm()
static void lower_fileinfo_llvm () static
Definition at line 5429 of file lowersym.c.
References curr_findex, dirname, FIH_DIRNAME, FIH_FILENAME, FIH_FLAGS, FIH_FULLNAME, FIH_FUNCNAME, FIH_FUNCTAG, FIH_LEVEL, FIH_LINENO, FIH_NEXT, FIH_PARENT, FIH_SRCLINE, fihb, filename, gbl, GBL_SIZE_T_FORMAT, NULL, STB_LOWER, FIHB::stg_avail, and strlen().
Referenced by lower_fileinfo().
lower_fill_member_parent()
void lower_fill_member_parent (void)
For an ST_MEMBER of an anonymous structure/union, fill member_parent[sptr] with the symbol name of its parent structure.
Definition at line 5224 of file lowersym.c.
References DTY, STB::firstosym, lerror(), NOSYM, s, sptr, stb, and SYMNAME.
Referenced by lower().
lower_finish_sym()
void lower_finish_sym (void)
Definition at line 1510 of file lowersym.c.
References datatype_output, datatype_used, FREE, lower_argument, lower_argument_size, lsymlists, NULL, stack, stb, and STG_DELETE_SIDECAR.
Referenced by lower().
lower_finish_symbols()
static void lower_finish_symbols (void) static
Definition at line 1098 of file lowersym.c.
References FLG::debug, STB::firstusym, flg, gbl, lower_visit_symbol(), sptr, stb, and XBIT.
Referenced by lower_sym_header().
lower_getintcon()
int lower_getintcon (int val)
Definition at line 3142 of file lowersym.c.
References getcon(), lower_use_datatype(), sptr, and val.
Referenced by conv_bint_ilm(), conv_blog_ilm(), conv_int_ilm(), conv_log8_ilm(), conv_log_ilm(), conv_sint_ilm(), conv_slog_ilm(), conv_word_ilm(), lower_ast(), lower_check_pointer(), lower_check_subscript(), lower_getiszcon(), lower_init_sym(), lower_intrinsic(), and lower_stmt().
lower_getiszcon()
int lower_getiszcon (ISZ_T val)
Definition at line 3165 of file lowersym.c.
References getcon(), ISZ_2_INT64, lower_getintcon(), lower_use_datatype(), num, sptr, val, and XBIT.
Referenced by fill_adjustable_array_dtype(), fill_fixed_array_dtype(), lower_ast(), lower_do_stmt(), lower_init_sym(), lower_intrinsic(), lower_namelist_plists(), lower_stmt(), and put_adjarr_bounds().
lower_getlogcon()
int lower_getlogcon (int val)
Definition at line 3180 of file lowersym.c.
References getcon(), lower_use_datatype(), sptr, and val.
Referenced by conv_log_ilm(), and lower_intrinsic().
lower_getnull()
static int lower_getnull (void) static
Definition at line 3155 of file lowersym.c.
References getcon(), and sptr.
Referenced by lower_init_sym().
lower_getrealcon()
int lower_getrealcon (int val)
Definition at line 3193 of file lowersym.c.
References getcon(), lower_use_datatype(), sptr, and val.
Referenced by conv_cmplx_ilm(), and conv_real_ilm().
lower_init_sym()
void lower_init_sym (void)
Definition at line 1340 of file lowersym.c.
References BZERO, chkstruct(), datatype_output, datatype_used, STB::dbl0, dlen(), STB::dt, DT_INT, DTY, FALSE, STB::flt0, gbl, STB::i0, STB::i1, STB::k0, STB::k1, last_datatype_used, lower_argument, lower_argument_size, lower_getintcon(), lower_getiszcon(), lower_getnull(), lower_linearized_dtypes, lower_make_all_descriptors(), lower_makefunc(), lower_pointer_list_head, lower_prepare_symbols(), lower_refd_list_head, lower_visit_symbol(), lowersym, lsymlists, mkRteRtnNm(), NEW, NOSYM, pghpf_local_mode_sptr, pghpf_type_sptr, private_addr, STB::quad0, replace_fval_in_ast(), replace_fval_in_params(), RTE_ptrchk, RTE_subchk, RTE_subchk64, RU_FUNC, RU_SUBR, same_dtype(), size_of(), stack, stack_size, stack_top, stb, STG_ALLOC_SIDECAR, sym_is_refd(), TRUE, and XBIT.
Referenced by lower().
lower_lab()
int lower_lab (void)
Definition at line 5295 of file lowersym.c.
References getlab().
Referenced by check_loop_bound(), handle_arguments(), llvm_omp_sched(), lower_do_stmt(), lower_logical(), and lower_stmt().
lower_linearized()
void lower_linearized (void)
Convert the datatype for linearized arrays to assumed-size array.
Definition at line 3243 of file lowersym.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_NUMELM, ADD_UPAST, ADD_UPBD, ADD_ZBASE, astb, ASTB::bnd, DTY, STB::firstosym, get_array_dtype(), get_type(), lower_linearized_dtypes, lower_use_datatype(), lower_visit_symbol(), lowersym, ASTB::one, sptr, stb, TRUE, and XBIT.
Referenced by lower().
lower_make_all_descriptors()
static void lower_make_all_descriptors (void) static
Definition at line 229 of file lowersym.c.
References ALIGNG, DISTG, DTY, STB::firstusym, flg, is_procedure_ptr(), off, RUNTIMEG, FLG::smp, sptr, stb, sym_get_offset(), sym_get_ptr(), and XBIT.
Referenced by lower_init_sym().
lower_makefunc()
int lower_makefunc (const char * name, int dtype, LOGICAL isDscSafe)
Definition at line 3338 of file lowersym.c.
References lower_newfunc(), and name.
Referenced by f90_function(), f90_value_function(), f90_value_function_I2(), lower_ast(), lower_do_stmt(), lower_init_sym(), lower_intrinsic(), lower_start_subroutine(), and lower_stmt().
lower_mark_entries()
void lower_mark_entries (void)
Definition at line 5254 of file lowersym.c.
References aux, AUX::dpdsc_base, gbl, i, lower_visit_symbol(), lowersym, NOSYM, and params.
Referenced by lower().
lower_namelist_plists()
void lower_namelist_plists (void)
Definition at line 3206 of file lowersym.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_NUMELM, ADD_UPAST, ADD_UPBD, ADD_ZBASE, astb, ASTB::bnd, DT_INT, DT_PTR, STB::firstusym, get_array_dtype(), lower_getiszcon(), lower_use_datatype(), lower_visit_symbol(), mk_cnst(), NML_NEXT, NML_SPTR, ASTB::one, plist(), sptr, and stb.
Referenced by lower().
lower_newfunc()
int lower_newfunc (const char * name, int stype, int dtype, int sclass)
Definition at line 3327 of file lowersym.c.
References lookupsym(), lower_newsymbol(), name, NOSYM, sptr, and strlen().
Referenced by lower_makefunc().
lower_newsymbol()
static int lower_newsymbol (const char * name, int stype, int dtype, int sclass) static
Definition at line 3299 of file lowersym.c.
References ADDSYM, STB::curr_scope, find_nmptr(), HASH_ID, lower_use_datatype(), name, NOSYM, sptr, stb, and strlen().
Referenced by lower_add_pghpf_commons(), lower_cmptrvar(), and lower_newfunc().
lower_outer_symbols()
void lower_outer_symbols (void)
For contained subprograms, mark all the regular symbols of the host subprogram.
Definition at line 2298 of file lowersym.c.
References lower_visit_symbol(), lowersym, and sptr.
Referenced by lower().
lower_pointer_init()
void lower_pointer_init (void)
Definition at line 1162 of file lowersym.c.
References lower_null(), lower_pointer_list_head, lowersym, off, plower(), sptr, and XBIT.
Referenced by lower_start_subroutine(), and lower_stmt().
lower_pop()
int lower_pop (void)
Definition at line 3120 of file lowersym.c.
References error(), stack, and stack_top.
Referenced by llvm_lower_enddo_stmt(), lower_enddo_stmt(), and lower_stmt().
lower_prepare_symbols()
static void lower_prepare_symbols () static
Definition at line 820 of file lowersym.c.
References ADD_ADJARR, ADD_DEFER, adjarr_class(), ALIGNG, DISTG, DTY, fill_adjustable_array_dtype(), fill_fixed_array_dtype(), fill_pointer_array_dtype(), first_avail_scalar_temp, first_avail_scalarptr_temp, first_temp, first_used_scalar_temp, first_used_scalarptr_temp, STB::firstosym, STB::firstusym, fixup_reqgs_ident(), FLANG_FALLTHROUGH, flg, gbl, get_array_dtype(), insert_sym(), lower_pointer_list_head, lower_use_datatype(), NOSYM, off, push_lower_refd_list(), rank_of_sym(), remove_list(), FLG::smp, sptr, stb, TY_CHAR, TY_NCHAR, and XBIT.
Referenced by lower_init_sym().
lower_push()
void lower_push (int value)
Definition at line 3112 of file lowersym.c.
References NEED, stack, stack_size, stack_top, and value().
Referenced by llvm_omp_sched(), lower_do_stmt(), and lower_stmt().
lower_put_datatype()
static void lower_put_datatype (int dtype, int usage) static
Definition at line 2535 of file lowersym.c.
References A_OPTYPEG, AD_DPTR, AD_UPAST, ADD_EXTNTAST, ADD_LWAST, ADD_MLPYR, ADD_NUMDIM, ADD_NUMELM, ADD_UPAST, ADD_ZBASE, ADJCHAR, ARGT_ARG, array_element_dtype(), ASSCHAR, aux, CONVAL2G, datatype_output, datatype_used, DEFERCHAR, AUX::dpdsc_base, DTY, eval_con_expr(), FALSE, gbl, SEM::gcvlen, i, STB::i1, is_array_dtype(), is_deferlenchar_dtype(), is_descr_expression(), IS_STB_FILE, last_datatype_used, lb, lerror(), llvm_iface_flag, lower_put_datatype(), lower_visit_symbol(), lowersym, memsym_of_ast(), n, ndim, OP_ADD, OP_SUB, params, putival(), putpair(), putsym(), putval(), putwhich(), r, sem, stb, TRUE, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, ub, val, valid_kind_parm_expr(), XBIT, z, and zbase.
Referenced by lower_put_datatype(), and lower_put_datatype_stb().
lower_put_datatype_stb()
static void lower_put_datatype_stb (int dtype) static
Definition at line 3086 of file lowersym.c.
References datatype_used, FILE, gbl, last_datatype_used, lower_put_datatype(), lowersym, STB_LOWER, and tmpfile().
Referenced by lower_data_types(), and lower_symbols().
lower_reset_temps()
void lower_reset_temps (void)
Reset temps for next statement.
Definition at line 5171 of file lowersym.c.
References first_avail_scalar_temp, first_avail_scalarptr_temp, first_used_scalar_temp, first_used_scalarptr_temp, NOSYM, and sptr.
Referenced by lower_stmt().
lower_scalar_temp()
int lower_scalar_temp (int dtype)
Return a symbol which is a temp scalar of DTYPE 'dtype'.
Definition at line 5190 of file lowersym.c.
References first_avail_scalar_temp, first_used_scalar_temp, gbl, getccsym_sc(), lowersym, NOSYM, and sptr.
Referenced by lower_function(), and lower_parenthesize_expression().
lower_set_craypointer()
void lower_set_craypointer (void)
Set datatype of 'cray pointers' to derived types.
Definition at line 168 of file lowersym.c.
References DT_PTR, DTY, STB::firstosym, get_type(), last_datatype_used, lower_use_datatype(), sptr, and stb.
Referenced by lower().
lower_set_symbols()
void lower_set_symbols (void)
Set 'EXTRA' bit for arrays, descriptors, array members that have IPA no conflict information, or that are compiler temps, or that can't conflict because they aren't targets and aren't pointers.
Definition at line 119 of file lowersym.c.
References d, DTY, STB::firstosym, FLANG_FALLTHROUGH, IPA_isnoconflict(), p, sptr, and stb.
Referenced by lower().
lower_sym_header()
void lower_sym_header (void)
Definition at line 1728 of file lowersym.c.
References bss_addr, STB::dt, STB::firstusym, gbl, GBL_SIZE_T_FORMAT, get_bss_addr(), inlist, ISZ_T, lower_finish_symbols(), lowersym, p, private_addr, putival(), putlval(), putval(), putvline(), saveblockname, stb, stb_lower_sym_header(), strlen(), VersionMajor, and VersionMinor.
Referenced by lower().
lower_symbol()
static void lower_symbol (int sptr) static
Definition at line 3648 of file lowersym.c.
References a, ADD_NUMDIM, all_default_init(), aux, check_debug_alias(), check_return(), CLASS_MEM, CLASS_NONE, CMPLXFUNC_C, CONVAL2G, count, cudaemu, CUDAG, STB::curr_scope, DBGBIT, FLG::debug, DLL_EXPORT, DLLG, AUX::dpdsc_base, DT_INT, DT_ISCMPLX, DTY, ENDLINEG, first_temp, flg, FUNCLINEG, gbl, get_specific_member(), getprint(), GSAMEG, has_opt_args(), i, INTENT_IN, INTENTG, lerror(), llmp_get_uplevel(), llmp_has_uplevel(), lowersym, MAXDIMS, mem(), STB::n_base, name, needs_descriptor(), NEWDSCG, NML_LINENO, NML_NEXT, NML_SPTR, NULL, params, LLUplevel::parent, PDALN_EXPLICIT_0, PDALN_IS_DEFAULT, PDALNG, putbit(), puthex(), putival(), putsclass(), putstring(), putstype(), putsym(), putval(), s, sptr, stb, string_length(), strlen(), symdentry(), SYMI_NEXT, SYMI_SPTR, SYMNAME, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_ISWORD, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, LLUplevel::vals, LLUplevel::vals_count, and XBIT.
Referenced by lower_symbol_stb(), and lower_symbols().
lower_symbol_stb()
static void lower_symbol_stb (int sptr) static
Definition at line 4811 of file lowersym.c.
References FILE, gbl, lower_symbol(), lowersym, sptr, STB_LOWER, and tmpfile().
Referenced by lower_symbols().
lower_symbols()
void lower_symbols (void)
VISITG(sptr) &&
Definition at line 4846 of file lowersym.c.
References CMPLXFUNC_C, CONVAL2G, DBGBIT, FLG::debug, DT_ISCMPLX, DTY, FILE, STB::firstosym, flg, gbl, getprint(), has_tbp_or_final(), IS_INTRINSIC, is_procedure_ptr(), lower_pstride_info(), lower_put_datatype_stb(), lower_symbol(), lower_symbol_stb(), lowersym, mem(), n, NOSYM, OUTPUT_DWARF, propagate_byval_visit(), putival(), putval(), s, scan_for_dwarf_module(), scope, SOC_NEXT, SOC_SPTR, sptr, stb, STB_LOWER, sym_of_ast(), and XBIT.
Referenced by lower().
lower_unset_symbols()
void lower_unset_symbols (void)
Reset data types of derived type pointers to DT_PTR.
Definition at line 204 of file lowersym.c.
References DT_PTR, STB::firstosym, sptr, and stb.
Referenced by lower().
lower_use_datatype()
void lower_use_datatype (int dtype, int usage)
Definition at line 2321 of file lowersym.c.
References ADD_DEFER, ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_NUMDIM, ADD_NUMELM, ADD_UPAST, ADD_UPBD, ADD_ZBASE, array_element_dtype(), aux, datatype_used, AUX::dpdsc_base, DT_INT, DTY, FALSE, gbl, i, is_array_dtype(), last_datatype_used, lb, llvm_iface_flag, lower_use_datatype(), lower_visit_symbol(), lowersym, ndim, NOSYM, params, sptr, TRUE, ub, XBIT, and zbase.
Referenced by check_additional_common(), conv_int8_ilm(), export_data_consts(), export_data_varlist(), lower_add_pghpf_commons(), lower_check_generics(), lower_data_stmts(), lower_do_stmt(), lower_getintcon(), lower_getiszcon(), lower_getlogcon(), lower_getrealcon(), lower_linearized(), lower_namelist_plists(), lower_newsymbol(), lower_prepare_symbols(), lower_set_craypointer(), lower_use_datatype(), lower_visit_symbol(), and plower().
lower_visit_symbol()
void lower_visit_symbol (int sptr)
Definition at line 2011 of file lowersym.c.
References aux, check_additional_common(), common, CONVAL2G, AUX::dpdsc_base, DT_CPTR, DTY, FLANG_FALLTHROUGH, gbl, i, is_iso_cptr(), lerror(), lower_linearized_dtypes, lower_use_datatype(), lower_visit_symbol(), makefvallocal(), params, SOC_NEXT, SOC_SPTR, sptr, SYMNAME, TY_DCMPLX, TY_HOLL, TY_ISWORD, and XBIT.
Referenced by _stb_fixup_ifacearg(), check_additional_common(), export_data_asts(), export_data_const_asts(), export_data_consts(), fill_adjustable_array_dtype(), fill_fixed_array_dtype(), lower_ast(), lower_base_address(), lower_check_generics(), lower_common_sizes(), lower_data_stmts(), lower_finish_symbols(), lower_init_sym(), lower_linearized(), lower_logical(), lower_mark_entries(), lower_namelist_plists(), lower_outer_symbols(), lower_put_datatype(), lower_replacement(), lower_sptr(), lower_stmt(), lower_use_datatype(), lower_visit_symbol(), plabel(), and plower().
lowersym_pghpf_cmem()
int lowersym_pghpf_cmem (int * whichmem)
Definition at line 5304 of file lowersym.c.
References base, lower_add_pghpf_commons(), lowersym, plower(), and XBIT.
Referenced by lower_null_arg(), and lower_nullc_arg().
makefvallocal()
static int makefvallocal (int rutype, int fval) static
Definition at line 1985 of file lowersym.c.
References DTY, RU_FUNC, TY_CHAR, TY_CMPLX, TY_DCMPLX, and TY_NCHAR.
Referenced by llvm_check_retval_inargs(), and lower_visit_symbol().
notimplicit()
static LOGICAL notimplicit (int sptr) static
Definition at line 2242 of file lowersym.c.
References FALSE, s, sptr, SYMNAME, and TRUE.
Referenced by lower_check_generics().
print_file()
int print_file (int fihx)
propagate_byval_visit()
static void propagate_byval_visit (int sptr) static
Definition at line 4827 of file lowersym.c.
References gbl, name, sptr, and SYMNAME.
Referenced by lower_symbols().
push_lower_refd_list()
static void push_lower_refd_list (int sym) static
Definition at line 451 of file lowersym.c.
References lower_refd_list_head, NOSYM, and prev.
Referenced by lower_prepare_symbols().
putbit()
static void putbit (const char * bitname, int bit) static
Definition at line 1580 of file lowersym.c.
References DBGBIT, lowersym, and XBIT.
Referenced by check_debug_alias(), and lower_symbol().
puthex()
static void puthex (int hex) static
Definition at line 1657 of file lowersym.c.
References hex(), and lowersym.
Referenced by lower_symbol().
putival()
static void putival (const char * valname, int val) static
Definition at line 1623 of file lowersym.c.
References DBGBIT, lowersym, val, and XBIT.
Referenced by lower_put_datatype(), lower_sym_header(), lower_symbol(), lower_symbols(), and stb_lower_sym_header().
putlval()
static void putlval (const char * valname, long val) static
Definition at line 1634 of file lowersym.c.
References DBGBIT, lowersym, val, and XBIT.
Referenced by lower_sym_header(), and stb_lower_sym_header().
putpair()
static void putpair (int first, int second) static
Definition at line 1645 of file lowersym.c.
References DBGBIT, first, getprint(), and lowersym.
Referenced by lower_put_datatype().
putsclass()
static const char * putsclass (int sclass, int sptr) static
Definition at line 3615 of file lowersym.c.
References gbl, lerror(), STB::scnames, sptr, stb, and symdentry().
Referenced by lower_symbol().
putstring()
static void putstring (const char * s) static
Definition at line 1663 of file lowersym.c.
References DBGBIT, lowersym, s, and XBIT.
Referenced by lower_symbol().
putstype()
static const char * putstype (int stype, int sptr) static
Definition at line 3531 of file lowersym.c.
References gbl, lerror(), sptr, stb, STB::stypes, and symdentry().
Referenced by lower_symbol().
putsym()
static void putsym (const char * valname, int sym) static
Definition at line 1591 of file lowersym.c.
References DBGBIT, getprint(), lowersym, NOSYM, and XBIT.
Referenced by lower_put_datatype(), and lower_symbol().
putval()
static void putval (const char * valname, ISZ_T val) static
Definition at line 1612 of file lowersym.c.
References DBGBIT, ISZ_PF, lowersym, val, and XBIT.
Referenced by lower_put_datatype(), lower_sym_header(), lower_symbol(), lower_symbols(), and stb_lower_sym_header().
putvline()
static void putvline (const char * n, ISZ_T v) static
Definition at line 1569 of file lowersym.c.
References DBGBIT, ISZ_PF, lowersym, n, and XBIT.
Referenced by lower_sym_header(), and stb_lower_sym_header().
putwhich()
static void putwhich (const char * s, const char * ss) static
Definition at line 1674 of file lowersym.c.
References DBGBIT, lowersym, s, ss, and XBIT.
Referenced by lower_put_datatype().
remove_list()
static int remove_list (int list, int sym) static
Definition at line 431 of file lowersym.c.
References list, NOSYM, and prev.
Referenced by lower_prepare_symbols().
replace_fval_in_ast()
static void replace_fval_in_ast (SPTR fval, SPTR fvalsame) static
Definition at line 1304 of file lowersym.c.
References add_replace_map(), and replace_sptr_in_ast().
Referenced by lower_init_sym().
replace_fval_in_params()
static void replace_fval_in_params (SPTR entry, SPTR entrysame) static
Definition at line 1234 of file lowersym.c.
References arg, aux, AUX::dpdsc_base, i, NEWDSCG, params, and SPTR_NULL.
Referenced by lower_init_sym().
replace_sptr_in_ast()
static void replace_sptr_in_ast (SPTR sptr) static
Definition at line 1275 of file lowersym.c.
References ast, mk_id(), NOSYM, and sptr.
Referenced by replace_fval_in_ast().
scan_for_dwarf_module()
void scan_for_dwarf_module ()
Definition at line 1440 of file main.c.
Referenced by lower_symbols().
set_common_size()
static void set_common_size (int common) static
Definition at line 1786 of file lowersym.c.
References addr, ALIGN, alignment_of_var(), CMEMLP, common, STB::curr_scope, DT_INT, DTY, ISZ_T, msz, NEWSYM, NOSYM, offset, pad_cmn_mem(), size, size_of(), size_of_var(), SOC_NEXT, SOC_SPTR, and stb.
Referenced by check_additional_common(), and lower_common_sizes().
stb_fixup_llvmiface()
void stb_fixup_llvmiface ()
Definition at line 5675 of file lowersym.c.
References _stb_fixup_ifacearg(), gbl, sptr, and stb.
Referenced by lower().
stb_lower_sym_header()
static void stb_lower_sym_header () static
Definition at line 5467 of file lowersym.c.
References bss_addr, STB::dt, FILE, STB::firstusym, gbl, GBL_SIZE_T_FORMAT, get_bss_addr(), inlist, ISZ_T, lowersym, p, private_addr, putival(), putlval(), putval(), putvline(), saveblockname, stb, STB_LOWER, strlen(), tmpfile(), VersionMajor, and VersionMinor.
Referenced by lower_sym_header().
uncouple_callee_args()
void uncouple_callee_args ()
Definition at line 5696 of file lowersym.c.
References FREE, i, NULL, save_dpdsc, save_dpdsc_cnt, sptr, and old_dscp::sptr.
Referenced by lower_end_subroutine().
valid_kind_parm_expr()
static int valid_kind_parm_expr (int ast) static
Definition at line 5333 of file lowersym.c.
References A_OPTYPEG, ARGT_ARG, ast, i, memsym_of_ast(), sptr, and valid_kind_parm_expr().
Referenced by fill_fixed_array_dtype(), lower_put_datatype(), and valid_kind_parm_expr().
Variable Documentation
curr_findex
int curr_findex static
Definition at line 57 of file lowersym.c.
Referenced by lower_fileinfo(), and lower_fileinfo_llvm().
datatype_output
char* datatype_output static
Definition at line 43 of file lowersym.c.
Referenced by lower_finish_sym(), lower_init_sym(), and lower_put_datatype().
datatype_used
char* datatype_used static
Definition at line 42 of file lowersym.c.
Referenced by lower_data_types(), lower_finish_sym(), lower_init_sym(), lower_put_datatype(), lower_put_datatype_stb(), and lower_use_datatype().
first_avail_scalar_temp
int first_avail_scalar_temp static
Definition at line 79 of file lowersym.c.
Referenced by lower_prepare_symbols(), lower_reset_temps(), and lower_scalar_temp().
first_avail_scalarptr_temp
int first_avail_scalarptr_temp static
Definition at line 78 of file lowersym.c.
Referenced by lower_prepare_symbols(), and lower_reset_temps().
first_temp
int first_temp static
Definition at line 78 of file lowersym.c.
Referenced by lower_prepare_symbols(), and lower_symbol().
first_used_scalar_temp
int first_used_scalar_temp static
Definition at line 79 of file lowersym.c.
Referenced by lower_prepare_symbols(), lower_reset_temps(), and lower_scalar_temp().
first_used_scalarptr_temp
int first_used_scalarptr_temp static
Definition at line 78 of file lowersym.c.
Referenced by lower_prepare_symbols(), and lower_reset_temps().
inlist
INITEM* inlist = NULL static
Definition at line 1531 of file lowersym.c.
Referenced by lower_add_func_call(), lower_sym_header(), and stb_lower_sym_header().
inlistend
INITEM * inlistend = NULL static
Definition at line 1531 of file lowersym.c.
Referenced by lower_add_func_call().
last_datatype_used
int last_datatype_used static
Definition at line 44 of file lowersym.c.
Referenced by lower_data_types(), lower_init_sym(), lower_put_datatype(), lower_put_datatype_stb(), lower_set_craypointer(), and lower_use_datatype().
llvm_iface_flag
LOGICAL llvm_iface_flag = FALSE static
Definition at line 84 of file lowersym.c.
Referenced by _stb_fixup_ifacearg(), lower_put_datatype(), and lower_use_datatype().
lower_argument
int* lower_argument
List of ILMs for function/subroutine arguments.
Definition at line 60 of file lowersym.c.
Referenced by handle_arguments(), lower_finish_sym(), lower_function(), and lower_init_sym().
lower_argument_size
int lower_argument_size
Definition at line 61 of file lowersym.c.
Referenced by handle_arguments(), lower_finish_sym(), lower_function(), and lower_init_sym().
lower_linearized_dtypes
LOGICAL lower_linearized_dtypes = FALSE static
Definition at line 46 of file lowersym.c.
Referenced by lower_init_sym(), lower_linearized(), and lower_visit_symbol().
lower_pointer_list_head
int lower_pointer_list_head static
Definition at line 65 of file lowersym.c.
Referenced by lower_init_sym(), lower_pointer_init(), and lower_prepare_symbols().
lower_refd_list_head
int lower_refd_list_head static
Definition at line 69 of file lowersym.c.
Referenced by lower_init_sym(), and push_lower_refd_list().
lowersym
struct lower_syms lowersym
Definition at line 76 of file lowersym.c.
Referenced by add_nullify(), check_debug_alias(), check_loop_bound(), conv_cmplx_ilm(), conv_dcmplx_ilm(), dotemp(), export_data_asts(), fill_adjustable_array_dtype(), get_atmp(), init_contained(), llvm_omp_sched(), lower(), lower_add_pghpf_commons(), lower_ast(), lower_base_address(), lower_check_pointer(), lower_check_subscript(), lower_directives(), lower_do_stmt(), lower_end_contains(), lower_end_subroutine(), lower_enddo_stmt(), lower_fileinfo(), lower_ilm_finish(), lower_init_sym(), lower_intrinsic(), lower_linearized(), lower_logical(), lower_mark_entries(), lower_null(), lower_null_arg(), lower_nullc_arg(), lower_numelm(), lower_outer_symbols(), lower_pointer_init(), lower_program(), lower_put_datatype(), lower_put_datatype_stb(), lower_scalar_temp(), lower_start_subroutine(), lower_stmt(), lower_sym_header(), lower_symbol(), lower_symbol_stb(), lower_symbols(), lower_use_datatype(), lowersym_pghpf_cmem(), markid(), plabel(), put_adjarr_bounds(), putbit(), puthex(), putival(), putlval(), putpair(), putstring(), putsym(), putval(), putvline(), putwhich(), and stb_lower_sym_header().
pghpf_local_mode_sptr
int pghpf_local_mode_sptr extern
Definition at line 76 of file transfrm.c.
Referenced by lower_init_sym(), transform(), and transform_init().
pghpf_type_sptr
int pghpf_type_sptr extern
Definition at line 577 of file rest.c.
Referenced by lower_init_sym().
private_addr
ISZ_T private_addr static
Definition at line 74 of file lowersym.c.
Referenced by lower_init_sym(), lower_sym_header(), and stb_lower_sym_header().
save_dpdsc
OLD_DPDSC* save_dpdsc = NULL static
Definition at line 5538 of file lowersym.c.
Referenced by _stb_fixup_ifacearg(), and uncouple_callee_args().
save_dpdsc_cnt
int save_dpdsc_cnt = 0 static
Definition at line 5539 of file lowersym.c.
Referenced by _stb_fixup_ifacearg(), and uncouple_callee_args().
saveblockname
int saveblockname = 0 static
Definition at line 1560 of file lowersym.c.
Referenced by create_static_base(), lower_sym_header(), and stb_lower_sym_header().
stack
int* stack static
Definition at line 54 of file lowersym.c.
Referenced by lower_check_stack(), lower_finish_sym(), lower_init_sym(), lower_pop(), and lower_push().
stack_size
int stack_size static
Definition at line 53 of file lowersym.c.
Referenced by lower_init_sym(), and lower_push().
stack_top
int stack_top static
Definition at line 53 of file lowersym.c.
Referenced by lower_check_stack(), lower_init_sym(), lower_pop(), and lower_push().