flang: lower.h File Reference
lower.h File Reference
definitions for Fortran front-end's lower module
Macros
#define VersionMajor 1
#define VersionMinor 55
Functions
void lower (int)
Lower the STDs and ASTs to something that the back end can use.
void lower_end_contains (void)
void create_static_base (int blockname)
Detailed Description
definitions for Fortran front-end's lower module
Definition in file lower.h.
Macro Definition Documentation
VersionMajor
#define VersionMajor 1
Definition at line 136 of file lower.h.
VersionMinor
#define VersionMinor 55
Definition at line 137 of file lower.h.
Function Documentation
create_static_base()
void create_static_base (int blockname)
Definition at line 1563 of file lowersym.c.
References saveblockname.
Referenced by upper().
lower()
void lower (int staticinit)
Lower the STDs and ASTs to something that the back end can use.
Essentially, lower to ILMs, save them to a file. In the mean time, save the symbol table to the same file, as well as anything else needed to compile the program.
Definition at line 106 of file lower.c.
References a, astb, contained, DBGBIT, dmp_dtype(), DTY, dump_std(), error(), errors, FILE, fill_entry_bounds(), FUNCLINEG, gbl, init_contained(), interr(), lower_add_pghpf_commons(), lower_check_generics(), lower_clear_visit_fields(), lower_common_sizes(), lower_data_stmts(), lower_data_types(), lower_debug_label(), lower_directives(), lower_end_subroutine(), lower_exp_finish(), lower_fileinfo(), lower_fill_member_parent(), lower_finish_sym(), lower_ilm_finish(), lower_ilm_header(), lower_init_sym(), lower_line, lower_linearized(), lower_mark_entries(), lower_namelist_plists(), lower_outer_symbols(), lower_program(), lower_set_craypointer(), lower_set_symbols(), lower_start_subroutine(), lower_stmt(), lower_sym_header(), lower_symbols(), lower_unset_symbols(), lowersym, NULL, RU_BDATA, RU_FUNC, RU_SUBR, save_contained(), stb, stb_fixup_llvmiface(), std, STD_AST, STD_LABEL, STD_LINENO, STD_NEXT, STD_ORIG, symdmp(), tmpfile(), and XBIT.
Referenced by build_array_list(), check_loop_bound(), constructf90(), conv_allocate(), ENTF90(), ENTFTN(), exp_smp(), fix_datatype(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), lower_check_subscript(), and read_datatype().
lower_end_contains()
void lower_end_contains (void)
Definition at line 461 of file lower.c.
References c, contained, contained_char, DBGBIT, FALSE, fclose(), FREE, gbl, getprint(), last_contained, LOWERBUFSIZ, lowersym, NULL, outerflags, sptr, strlen(), Trace, TRUE, and XBIT.
Referenced by end_contained().