flang: lrutils.h File Reference
lrutils.h File Reference
LR utility header files.
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <setjmp.h>
#include <signal.h>
#include <ctype.h>
Macros
#define ABORT 1
#define CONTINUE 0
#define FALSE 0
#define FPS_ERR 0
#define MAX_LINE_LEN 1024
#define SYS_ERR 1
#define TRUE 1
#define ARG_TABLE_COLS 65
#define ARG_TABLE_ROWS 256
#define END_OF_TABLE_MARK 0
#define OVERFLOW_MARK -3
#define UNSWITCHED_ARG_MARK -1
#define UNEXPECTED_ARG_MARK -2
#define BINARY_FILES 0x3a0e50
#define ERR_FCLOSE EOF
#define ERR_FILE_DOESNT_EXIST 2
#define EXT_READ_WRITE_ACCESS 3
#define EXT_SIZE 7
#define FILNAM_LEN 128
#define FSEEK_OK 0
#define MAX_FILTYP 22
#define MAX_PREFIXES 2
#define NFILE 10
#define NO_OP 0
#define PREFIX_SIZE 29
#define STANDARD_INPUT_OUTPUT 1
#define INSET(set, number) (((set) >> (number)) & 1)
#define INT int
#define UINT unsigned int
Functions
void a1tos1 (INT *from, INT *to, INT count)
void a4tos1 (const char *from, INT *to, INT count)
void i32tos (INT *from, INT *to, INT count, INT sign, INT radix, INT format)
Convert an AP 32-bit integer to unpacked right-justified ASCII character data (S1).
void s1toa1 (INT *from, INT *to, INT *count)
void s1toa4 (INT *from, INT *to, INT *count)
INT find (INT *swtab, INT arg_table[ARG_TABLE_ROWS][ARG_TABLE_COLS], INT cur_arg)
Find specified argument in switch table.
INT rdline (FILE *fp, INT *buffer, INT count)
Read a line from a file.
void wtline (FILE *fp, INT *buffer, INT count)
INT wtpage (FILE *fp)
Write a page mark to a file.
void add_arg_entry (INT *argtab, INT arglen, INT *argtab_end_ptr, INT arg_table[ARG_TABLE_ROWS][ARG_TABLE_COLS], INT type, INT first_lbl, INT lbl_cnt)
Add command line argument(s) (switch) into 'argtab'.
void cli (INT *swtab, INT *argtab, INT arglen, INT caller)
void exitf (INT errcnd)
void getarg (INT *n, char *s, INT ls)
INT iargc (void)
void lower_to_upper (INT cur_arg, INT arg_table[ARG_TABLE_ROWS][ARG_TABLE_COLS])
Convert the specified argument in the argument table from lower case to upper case.
INT upper_to_lower (INT *name, INT col)
This function converts the charactets of a file name from upper to lower case.
void util_error (const char *, INT, INT)
Detailed Description
LR utility header files.
Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions. See https://llvm.org/LICENSE.txt for license information. SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
  This file declares all constants and varaiables global to all
  LR utils routines, also contains all the routine declarations.
Definition in file lrutils.h.
Macro Definition Documentation
ABORT
#define ABORT 1
Definition at line 28 of file lrutils.h.
ARG_TABLE_COLS
#define ARG_TABLE_COLS 65
Definition at line 37 of file lrutils.h.
ARG_TABLE_ROWS
#define ARG_TABLE_ROWS 256
Definition at line 38 of file lrutils.h.
BINARY_FILES
#define BINARY_FILES 0x3a0e50
Definition at line 45 of file lrutils.h.
CONTINUE
#define CONTINUE 0
Definition at line 29 of file lrutils.h.
END_OF_TABLE_MARK
#define END_OF_TABLE_MARK 0
Definition at line 39 of file lrutils.h.
ERR_FCLOSE
#define ERR_FCLOSE EOF
Definition at line 46 of file lrutils.h.
ERR_FILE_DOESNT_EXIST
#define ERR_FILE_DOESNT_EXIST 2
Definition at line 47 of file lrutils.h.
EXT_READ_WRITE_ACCESS
#define EXT_READ_WRITE_ACCESS 3
Definition at line 48 of file lrutils.h.
EXT_SIZE
#define EXT_SIZE 7
Definition at line 49 of file lrutils.h.
FALSE
#define FALSE 0
Definition at line 30 of file lrutils.h.
FILNAM_LEN
#define FILNAM_LEN 128
Definition at line 50 of file lrutils.h.
FPS_ERR
#define FPS_ERR 0
Definition at line 31 of file lrutils.h.
FSEEK_OK
#define FSEEK_OK 0
Definition at line 51 of file lrutils.h.
INSET
#define INSET (set, number) (((set) >> (number)) & 1)
INSET In Set Macro
 INSET receives two (2) numeric parameters. The first (set)
 is a bit map for a set, with each bit being a flag which
 indicates if the number corresponding to the bit's position
 in the word is in the set. The second parameter (number)
 is a number which must be in the range 0 to 31. The macro
 returns 1 if 'number' is in 'set', 0 otherwise.
Definition at line 70 of file lrutils.h.
INT
#define INT int
Definition at line 72 of file lrutils.h.
MAX_FILTYP
#define MAX_FILTYP 22
Definition at line 52 of file lrutils.h.
MAX_LINE_LEN
#define MAX_LINE_LEN 1024
Definition at line 32 of file lrutils.h.
MAX_PREFIXES
#define MAX_PREFIXES 2
Definition at line 53 of file lrutils.h.
NFILE
#define NFILE 10
Definition at line 54 of file lrutils.h.
NO_OP
#define NO_OP 0
Definition at line 55 of file lrutils.h.
OVERFLOW_MARK
#define OVERFLOW_MARK -3
Definition at line 40 of file lrutils.h.
PREFIX_SIZE
#define PREFIX_SIZE 29
Definition at line 56 of file lrutils.h.
STANDARD_INPUT_OUTPUT
#define STANDARD_INPUT_OUTPUT 1
Definition at line 57 of file lrutils.h.
SYS_ERR
#define SYS_ERR 1
Definition at line 33 of file lrutils.h.
TRUE
#define TRUE 1
Definition at line 34 of file lrutils.h.
UINT
#define UINT unsigned int
Definition at line 73 of file lrutils.h.
UNEXPECTED_ARG_MARK
#define UNEXPECTED_ARG_MARK -2
Definition at line 42 of file lrutils.h.
UNSWITCHED_ARG_MARK
#define UNSWITCHED_ARG_MARK -1
Definition at line 41 of file lrutils.h.
Function Documentation
a1tos1()
void a1tos1 (INT * from, INT * to, INT count)
Definition at line 18 of file lrutils.c.
References ABORT, count, FPS_ERR, i, n, trace(), util_error(), and void().
Referenced by error(), output(), and putsem().
a4tos1()
void a4tos1 (const char * from, INT * to, INT count)
Definition at line 42 of file lrutils.c.
References ABORT, count, FPS_ERR, n, trace(), util_error(), and void().
Referenced by cli(), error(), i32tos(), init(), prntgm(), putsem(), rdline(), tablea(), tokmac(), xref(), and zprntk().
add_arg_entry()
void add_arg_entry (INT * argtab, INT arglen, INT * argtab_end_ptr, INT arg_table[ARG_TABLE_ROWS][ARG_TABLE_COLS], INT type, INT first_lbl, INT lbl_cnt)
Add command line argument(s) (switch) into 'argtab'.
CALLING SEQUENCE: add_arg_entry (argtab, arglen, argtab_end_ptr, arg_table, type, first_lbl, lbl_cnt);
INPUT PARAMETERS: argtab long array (output parameter) Table in which command line arguments are returned.
arglen long scalar (input parameter) Length of 'argtab'.
argtab_end_ptr pointer to long (input/output parameter) Pointer to the last element in 'argtab'.
arg_table long array (input parameter) Table of argruments on the command line.
type long scalar (input parameter) Type of the switch being added to 'argtab'.
first_lbl long scalar (input parameter) Pointer the first element in 'arg_table' to be added to 'argtab'.
lbl_cnt long scalar (input parameter) Count of the number of switches to be added to 'argtab'.
RETURN VALUE: NONE.
SIDE EFFECTS: This function modifies the contents of the array specified by 'argtab'. This function also modifies the contents of the long specified by 'argtab_len_ptr'.
DESCRIPTION: 'lbl_cnt' command line arguments stored in 'arg_table', starting with the switch pointed to by 'first_lbl', are added to 'arg_tab'. 'argtab_end_ptr' is set to point to the last element in 'argtab'. If table overflow occurs 'argtab_end_ptr' is set to -3.
Definition at line 683 of file lrutils.c.
References OVERFLOW_MARK, and type.
Referenced by cli().
cli()
void cli (INT * swtab, INT * argtab, INT arglen, INT caller)
Table of arguments on the command line. Each row contains a single argument. The first elemement of each row is equal to the number of characters in the argument. The remaining row elements contain the characters of the argument in S1 format
processing loop which fills argtab with the command line arguments
Definition at line 741 of file lrutils.c.
References a4tos1(), add_arg_entry(), ARG_TABLE_COLS, ARG_TABLE_ROWS, argbuf, END_OF_TABLE_MARK, find(), i, iargc(), lower_to_upper(), OVERFLOW_MARK, strlen(), swtab, type, UNEXPECTED_ARG_MARK, UNSWITCHED_ARG_MARK, and xargvar().
Referenced by init().
exitf()
void exitf (INT errcnd)
Definition at line 838 of file lrutils.c.
Referenced by finish().
find()
INT find (INT * swtab, INT arg_table[ARG_TABLE_ROWS][ARG_TABLE_COLS], INT cur_arg)
Find specified argument in switch table.
CALLING SEQUENCE: ret_arg = find (swtab, arg_table, cur_arg);
INPUT PARAMETERS: swtab INT array (input parameter) Switch Table.
arg_table INT array (input parameter) Argument table.
cur_arg INT scalar (input parameter) Specifies argument to search for in switch table.
RETURN VALUE: type INT Number specifying the type of the argrment.
> 0 argument type from 'swtab' = 0 argument not found in 'swtab'
DESCRIPTION: 'swtab' is searched for the argument in 'arg_table' pointed to by 'cur_arg'. If the argument is found, the switch type of the argument is returned. If the argument isn't found 0 is returned.
Definition at line 373 of file lrutils.c.
References END_OF_TABLE_MARK, FALSE, match(), offset, swtab, and TRUE.
Referenced by cli().
getarg()
void getarg (INT * n, char * s, INT ls)
subroutine getarg(k, c) returns the kth unix command argument in fortran character variable argument c
Definition at line 950 of file lrutils.c.
References i, n, s, t, xargc, and xargv.
Referenced by xargvar().
i32tos()
void i32tos (INT * from, INT * to, INT count, INT sign, INT radix, INT format)
Convert an AP 32-bit integer to unpacked right-justified ASCII character data (S1).
CALLING SEQUENCE: i32tos (from, to, count, sign, radix, format);
INPUT PARAMETERS: from pointer to INT (input parameter) Specifies 32-bit integer quantity to be converted.
to INT array (output parameter) Specifies array containing converted S1 character data.
count pointer to INT (input parameter) Specifies non-negative output field width for conversion.
sign pointer to INT (input parameter) Specifies whether signed conversion is used:
0 = signed conversion. 1 = unsigned conversion.
radix pointer to INT (input parameter) Specifies conversion radix:
2 = binary radix. 8 = octal radix. 10 = decimal radix. 16 = hexadecimal radix.
format pointer to INT (input parameter) Specifies conversion format:
0 = left justified, blank filled. 1 = right justified, blank filled. 2 = right justified, zero filled.
SIDE EFFECTS: The function modifies the contents of the array specified by 'to'.
DESCRIPTION: Convert an AP 32-bit integer contained in the 'from' parameter to unpacked right-justified ASCII character data (S1) contained in the 'to' parameter. The 'count' parameter specifies the number of characters of the to parameter that are filled with the converted result. The 'sign' parameter indicates whether signed or unsigned conversion is to take place, negative numbers are preceded by a minus sign. The 'radix' parameter refers to the radix to be used in conversion. The 'format' parameter indicates where the conversion results will be placed in the output field and how unused space will be filled. If the output field is too small for the result, the first character of the field is filled with an asterisk, and the low-order digits of the result fill the rest of the output field.
ERROR CONDITIONS: Illegal parameter value specified: user is notified and the program is aborted.
Definition at line 138 of file lrutils.c.
References a4tos1(), ABORT, ASCII_OFFSET, ASTERISK, BLANK, count, FPS_ERR, HEX_OFFSET, idx, INSET, LEGAL_FORMAT_SET, LEGAL_RADIX_SET, LEGAL_SIGN_SET, MINUS, sign, strlen(), trace(), util_error(), void(), and ZERO.
Referenced by error(), putsem(), tablea(), tokmac(), and zprntk().
iargc()
INT iargc (void)
Definition at line 969 of file lrutils.c.
References xargc.
Referenced by cli().
lower_to_upper()
void lower_to_upper (INT cur_arg, INT arg_table[ARG_TABLE_ROWS][ARG_TABLE_COLS])
Convert the specified argument in the argument table from lower case to upper case.
CALLING SEQUENCE: lower_to_upper(cur_arg, arg_table);
INPUT PARAMETERS: cur_arg long scalar (input parameter) Index into the argument table, indicating the argument to be converted from lower case to upper case.
arg_table long array (output parameter) Argument table, containing the argument to be converted from lower case to upper case.
RETURN VALUE: NONE.
SIDE EFFECTS: NONE.
DESCRIPTION: Convert the specified entry in the argument table from lower case to upper case.
ERROR CONDITIONS: NONE.
If the character is in lower case, then convert it to upper case.
Definition at line 1011 of file lrutils.c.
References col, and OFFSET.
Referenced by cli().
rdline()
INT rdline (FILE * fp, INT * buffer, INT count)
Read a line from a file.
CALLING SEQUENCE: status = rdlinf (fp, buffer, count)
INPUT PARAMETERS: fp pointer to long (input parameter) Specifies file descriptor.
count pointer to long (input parameter) Specifies maximum count of characters to read (must be non-negative)
buffer long array (output parameter) Specifies characters read in S1 format.
RETURN VALUE: status long Specifies completion status of read operation:
-1 = end-of-file, no line read >=0 = count of characters read
SIDE EFFECTS: This function modifies the contents of the array specified by 'buffer'.
DESCRIPTION: Read a line from file indicated by 'fp'. Characters are read up to end-of-line or end-of-file, whichever comes first. If the line is longer that the maximum specified by 'count', the extra characters are discarded without error. All trailing blanks on a line are removed, so the value of status is the number of characters read, discarding trailing blanks (and trailing tabs if applicable).
ERROR CONDITIONS: Illegal parameter value specified or error in making a sytem call: user is notified and the program is aborted.
Definition at line 494 of file lrutils.c.
References a4tos1(), ABORT, count, fp, FPS_ERR, MAX_LINE_LEN, NULL, strlen(), SYS_ERR, trace(), util_error(), and void().
Referenced by readln().
s1toa1()
void s1toa1 (INT * from, INT * to, INT * count)
Definition at line 282 of file lrutils.c.
References ABORT, count, FPS_ERR, i, and util_error().
Referenced by enter().
s1toa4()
void s1toa4 (INT * from, INT * to, INT * count)
pad with blanks to the end of the word - switch value is the number of bytes written in the last word
Definition at line 296 of file lrutils.c.
References ABORT, count, FLANG_FALLTHROUGH, FPS_ERR, n, trace(), util_error(), and void().
Referenced by wtline().
upper_to_lower()
INT upper_to_lower (INT * name, INT col)
This function converts the charactets of a file name from upper to lower case.
This function recieves two parameters: name - a file name in S1 format; col - the column in name that is to be converted to lower case. The conversion is performed by adding the ascii offset to the letter in name[col] if it is an upper case letter.
Definition at line 1054 of file lrutils.c.
References col, name, and OFFSET.
util_error()
void util_error (const char * p, INT err, INT flag)
Definition at line 1030 of file lrutils.c.
References p.
Referenced by a1tos1(), a4tos1(), i32tos(), rdline(), s1toa1(), s1toa4(), wtline(), and wtpage().
wtline()
void wtline (FILE * fp, INT * buffer, INT count)
Definition at line 534 of file lrutils.c.
References ABORT, count, fp, FPS_ERR, MAX_LINE_LEN, n, s1toa4(), SYS_ERR, trace(), util_error(), and void().
Referenced by enter(), error(), output(), prntgm(), putsem(), tablea(), tokmac(), xref(), and zprntk().
wtpage()
INT wtpage (FILE * fp)
Write a page mark to a file.
CALLING SEQUENCE: wtpage (fd)
INPUT PARAMETERS: fd pointer to long (input parameter) Specifies file descriptor.
RETURN VALUE: NONE.
SIDE EFFECTS: NONE.
DESCRIPTION: Write a page marker to file indicated by 'fd'. A page marker is a host-dependent indication in a text file which causes a skip to the top of the next page when the file is printed.
ERROR CONDITIONS: Illegal parameter value, illegal file type, illegal open access, or error in making a system call: the user is notified and the program is aborted.
Definition at line 599 of file lrutils.c.
References ABORT, FORM_FEED, fp, FPS_ERR, FSEEK_OK, SYS_ERR, trace(), util_error(), and void().
Referenced by prntgm(), and xref().