flang: lrutils.c File Reference
lrutils.c File Reference
LR utility functions.
#include "universal.h"
#include "lrutils.h"
Macros
#define ASCII_OFFSET 48
#define ASTERISK 42
#define BLANK 32
#define HEX_OFFSET 7
#define LEGAL_FORMAT_SET 0x7
#define LEGAL_RADIX_SET 0x10504
#define LEGAL_SIGN_SET 0x3
#define MINUS 45
#define ZERO 48
#define FORM_FEED "\f\n"
#define OFFSET 0x20
#define OFFSET 0x20
Functions
void a1tos1 (INT *from, INT *to, INT count)
void a4tos1 (const char *from, INT *to, INT count)
void i32tos (INT *from, INT *to, INT count, INT sign, INT radix, INT format)
Convert an AP 32-bit integer to unpacked right-justified ASCII character data (S1).
void s1toa1 (INT *from, INT *to, INT *count)
void s1toa4 (INT *from, INT *to, INT *count)
INT find (INT *swtab, INT arg_table[ARG_TABLE_ROWS][ARG_TABLE_COLS], INT cur_arg)
Find specified argument in switch table.
INT rdline (FILE *fp, INT *buffer, INT count)
Read a line from a file.
void wtline (FILE *fp, INT *buffer, INT count)
INT wtpage (FILE *fp)
Write a page mark to a file.
void add_arg_entry (INT *argtab, INT arglen, INT *argtab_end_ptr, INT arg_table[ARG_TABLE_ROWS][ARG_TABLE_COLS], INT type, INT first_lbl, INT lbl_cnt)
Add command line argument(s) (switch) into 'argtab'.
void xargvar (INT num)
void cli (INT *swtab, INT *argtab, INT arglen, INT caller)
void exitf (INT errcnd)
void getarg (INT *n, char *s, INT ls)
INT iargc (void)
void lower_to_upper (INT cur_arg, INT arg_table[ARG_TABLE_ROWS][ARG_TABLE_COLS])
Convert the specified argument in the argument table from lower case to upper case.
void util_error (const char *p, INT err, INT flag)
void trace (char *p)
INT upper_to_lower (INT *name, INT col)
This function converts the charactets of a file name from upper to lower case.
Variables
static char argbuf [100]
Detailed Description
LR utility functions.
Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions. See https://llvm.org/LICENSE.txt for license information. SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
char conversion
file operations
miscellaneous
Definition in file lrutils.c.
Macro Definition Documentation
ASCII_OFFSET
#define ASCII_OFFSET 48
ASTERISK
#define ASTERISK 42
BLANK
#define BLANK 32
FORM_FEED
#define FORM_FEED "\f\n"
HEX_OFFSET
#define HEX_OFFSET 7
LEGAL_FORMAT_SET
#define LEGAL_FORMAT_SET 0x7
LEGAL_RADIX_SET
#define LEGAL_RADIX_SET 0x10504
LEGAL_SIGN_SET
#define LEGAL_SIGN_SET 0x3
MINUS
#define MINUS 45
OFFSET [1/2]
#define OFFSET 0x20
OFFSET [2/2]
#define OFFSET 0x20
ZERO
#define ZERO 48
Function Documentation
a1tos1()
void a1tos1 (INT * from, INT * to, INT count)
Definition at line 18 of file lrutils.c.
References ABORT, count, FPS_ERR, i, n, trace(), util_error(), and void().
Referenced by error(), output(), and putsem().
a4tos1()
void a4tos1 (const char * from, INT * to, INT count)
Definition at line 42 of file lrutils.c.
References ABORT, count, FPS_ERR, n, trace(), util_error(), and void().
Referenced by cli(), error(), i32tos(), init(), prntgm(), putsem(), rdline(), tablea(), tokmac(), xref(), and zprntk().
add_arg_entry()
void add_arg_entry (INT * argtab, INT arglen, INT * argtab_end_ptr, INT arg_table[ARG_TABLE_ROWS][ARG_TABLE_COLS], INT type, INT first_lbl, INT lbl_cnt)
Add command line argument(s) (switch) into 'argtab'.
CALLING SEQUENCE: add_arg_entry (argtab, arglen, argtab_end_ptr, arg_table, type, first_lbl, lbl_cnt);
INPUT PARAMETERS: argtab long array (output parameter) Table in which command line arguments are returned.
arglen long scalar (input parameter) Length of 'argtab'.
argtab_end_ptr pointer to long (input/output parameter) Pointer to the last element in 'argtab'.
arg_table long array (input parameter) Table of argruments on the command line.
type long scalar (input parameter) Type of the switch being added to 'argtab'.
first_lbl long scalar (input parameter) Pointer the first element in 'arg_table' to be added to 'argtab'.
lbl_cnt long scalar (input parameter) Count of the number of switches to be added to 'argtab'.
RETURN VALUE: NONE.
SIDE EFFECTS: This function modifies the contents of the array specified by 'argtab'. This function also modifies the contents of the long specified by 'argtab_len_ptr'.
DESCRIPTION: 'lbl_cnt' command line arguments stored in 'arg_table', starting with the switch pointed to by 'first_lbl', are added to 'arg_tab'. 'argtab_end_ptr' is set to point to the last element in 'argtab'. If table overflow occurs 'argtab_end_ptr' is set to -3.
Definition at line 683 of file lrutils.c.
References OVERFLOW_MARK, and type.
Referenced by cli().
cli()
void cli (INT * swtab, INT * argtab, INT arglen, INT caller)
Table of arguments on the command line. Each row contains a single argument. The first elemement of each row is equal to the number of characters in the argument. The remaining row elements contain the characters of the argument in S1 format
processing loop which fills argtab with the command line arguments
Definition at line 741 of file lrutils.c.
References a4tos1(), add_arg_entry(), ARG_TABLE_COLS, ARG_TABLE_ROWS, argbuf, END_OF_TABLE_MARK, find(), i, iargc(), lower_to_upper(), OVERFLOW_MARK, strlen(), swtab, type, UNEXPECTED_ARG_MARK, UNSWITCHED_ARG_MARK, and xargvar().
Referenced by init().
exitf()
void exitf (INT errcnd)
Definition at line 838 of file lrutils.c.
Referenced by finish().
find()
INT find (INT * swtab, INT arg_table[ARG_TABLE_ROWS][ARG_TABLE_COLS], INT cur_arg)
Find specified argument in switch table.
CALLING SEQUENCE: ret_arg = find (swtab, arg_table, cur_arg);
INPUT PARAMETERS: swtab INT array (input parameter) Switch Table.
arg_table INT array (input parameter) Argument table.
cur_arg INT scalar (input parameter) Specifies argument to search for in switch table.
RETURN VALUE: type INT Number specifying the type of the argrment.
> 0 argument type from 'swtab' = 0 argument not found in 'swtab'
DESCRIPTION: 'swtab' is searched for the argument in 'arg_table' pointed to by 'cur_arg'. If the argument is found, the switch type of the argument is returned. If the argument isn't found 0 is returned.
Definition at line 373 of file lrutils.c.
References END_OF_TABLE_MARK, FALSE, match(), offset, swtab, and TRUE.
Referenced by cli().
getarg()
void getarg (INT * n, char * s, INT ls)
subroutine getarg(k, c) returns the kth unix command argument in fortran character variable argument c
Definition at line 950 of file lrutils.c.
References i, n, s, t, xargc, and xargv.
Referenced by xargvar().
i32tos()
void i32tos (INT * from, INT * to, INT count, INT sign, INT radix, INT format)
Convert an AP 32-bit integer to unpacked right-justified ASCII character data (S1).
CALLING SEQUENCE: i32tos (from, to, count, sign, radix, format);
INPUT PARAMETERS: from pointer to INT (input parameter) Specifies 32-bit integer quantity to be converted.
to INT array (output parameter) Specifies array containing converted S1 character data.
count pointer to INT (input parameter) Specifies non-negative output field width for conversion.
sign pointer to INT (input parameter) Specifies whether signed conversion is used:
0 = signed conversion. 1 = unsigned conversion.
radix pointer to INT (input parameter) Specifies conversion radix:
2 = binary radix. 8 = octal radix. 10 = decimal radix. 16 = hexadecimal radix.
format pointer to INT (input parameter) Specifies conversion format:
0 = left justified, blank filled. 1 = right justified, blank filled. 2 = right justified, zero filled.
SIDE EFFECTS: The function modifies the contents of the array specified by 'to'.
DESCRIPTION: Convert an AP 32-bit integer contained in the 'from' parameter to unpacked right-justified ASCII character data (S1) contained in the 'to' parameter. The 'count' parameter specifies the number of characters of the to parameter that are filled with the converted result. The 'sign' parameter indicates whether signed or unsigned conversion is to take place, negative numbers are preceded by a minus sign. The 'radix' parameter refers to the radix to be used in conversion. The 'format' parameter indicates where the conversion results will be placed in the output field and how unused space will be filled. If the output field is too small for the result, the first character of the field is filled with an asterisk, and the low-order digits of the result fill the rest of the output field.
ERROR CONDITIONS: Illegal parameter value specified: user is notified and the program is aborted.
Definition at line 138 of file lrutils.c.
References a4tos1(), ABORT, ASCII_OFFSET, ASTERISK, BLANK, count, FPS_ERR, HEX_OFFSET, idx, INSET, LEGAL_FORMAT_SET, LEGAL_RADIX_SET, LEGAL_SIGN_SET, MINUS, sign, strlen(), trace(), util_error(), void(), and ZERO.
Referenced by error(), putsem(), tablea(), tokmac(), and zprntk().
iargc()
INT iargc (void)
Definition at line 969 of file lrutils.c.
References xargc.
Referenced by cli().
lower_to_upper()
void lower_to_upper (INT cur_arg, INT arg_table[ARG_TABLE_ROWS][ARG_TABLE_COLS])
Convert the specified argument in the argument table from lower case to upper case.
CALLING SEQUENCE: lower_to_upper(cur_arg, arg_table);
INPUT PARAMETERS: cur_arg long scalar (input parameter) Index into the argument table, indicating the argument to be converted from lower case to upper case.
arg_table long array (output parameter) Argument table, containing the argument to be converted from lower case to upper case.
RETURN VALUE: NONE.
SIDE EFFECTS: NONE.
DESCRIPTION: Convert the specified entry in the argument table from lower case to upper case.
ERROR CONDITIONS: NONE.
If the character is in lower case, then convert it to upper case.
Definition at line 1011 of file lrutils.c.
References col, and OFFSET.
Referenced by cli().
rdline()
INT rdline (FILE * fp, INT * buffer, INT count)
Read a line from a file.
CALLING SEQUENCE: status = rdlinf (fp, buffer, count)
INPUT PARAMETERS: fp pointer to long (input parameter) Specifies file descriptor.
count pointer to long (input parameter) Specifies maximum count of characters to read (must be non-negative)
buffer long array (output parameter) Specifies characters read in S1 format.
RETURN VALUE: status long Specifies completion status of read operation:
-1 = end-of-file, no line read >=0 = count of characters read
SIDE EFFECTS: This function modifies the contents of the array specified by 'buffer'.
DESCRIPTION: Read a line from file indicated by 'fp'. Characters are read up to end-of-line or end-of-file, whichever comes first. If the line is longer that the maximum specified by 'count', the extra characters are discarded without error. All trailing blanks on a line are removed, so the value of status is the number of characters read, discarding trailing blanks (and trailing tabs if applicable).
ERROR CONDITIONS: Illegal parameter value specified or error in making a sytem call: user is notified and the program is aborted.
Definition at line 494 of file lrutils.c.
References a4tos1(), ABORT, count, fp, FPS_ERR, MAX_LINE_LEN, NULL, strlen(), SYS_ERR, trace(), util_error(), and void().
Referenced by readln().
s1toa1()
void s1toa1 (INT * from, INT * to, INT * count)
Definition at line 282 of file lrutils.c.
References ABORT, count, FPS_ERR, i, and util_error().
Referenced by enter().
s1toa4()
void s1toa4 (INT * from, INT * to, INT * count)
pad with blanks to the end of the word - switch value is the number of bytes written in the last word
Definition at line 296 of file lrutils.c.
References ABORT, count, FLANG_FALLTHROUGH, FPS_ERR, n, trace(), util_error(), and void().
Referenced by wtline().
trace()
void trace (char * p)
Definition at line 1037 of file lrutils.c.
References p.
Referenced by a1tos1(), a4tos1(), i32tos(), rdline(), s1toa4(), wtline(), and wtpage().
upper_to_lower()
INT upper_to_lower (INT * name, INT col)
This function converts the charactets of a file name from upper to lower case.
This function recieves two parameters: name - a file name in S1 format; col - the column in name that is to be converted to lower case. The conversion is performed by adding the ascii offset to the letter in name[col] if it is an upper case letter.
Definition at line 1054 of file lrutils.c.
References col, name, and OFFSET.
util_error()
void util_error (const char * p, INT err, INT flag)
Definition at line 1030 of file lrutils.c.
References p.
Referenced by a1tos1(), a4tos1(), i32tos(), rdline(), s1toa1(), s1toa4(), wtline(), and wtpage().
wtline()
void wtline (FILE * fp, INT * buffer, INT count)
Definition at line 534 of file lrutils.c.
References ABORT, count, fp, FPS_ERR, MAX_LINE_LEN, n, s1toa4(), SYS_ERR, trace(), util_error(), and void().
Referenced by enter(), error(), output(), prntgm(), putsem(), tablea(), tokmac(), xref(), and zprntk().
wtpage()
INT wtpage (FILE * fp)
Write a page mark to a file.
CALLING SEQUENCE: wtpage (fd)
INPUT PARAMETERS: fd pointer to long (input parameter) Specifies file descriptor.
RETURN VALUE: NONE.
SIDE EFFECTS: NONE.
DESCRIPTION: Write a page marker to file indicated by 'fd'. A page marker is a host-dependent indication in a text file which causes a skip to the top of the next page when the file is printed.
ERROR CONDITIONS: Illegal parameter value, illegal file type, illegal open access, or error in making a system call: the user is notified and the program is aborted.
Definition at line 599 of file lrutils.c.
References ABORT, FORM_FEED, fp, FPS_ERR, FSEEK_OK, SYS_ERR, trace(), util_error(), and void().
Referenced by prntgm(), and xref().
xargvar()
void xargvar (INT num)
getarg fills n positions in argbuf (n = sizeof argbuf - 1). the trailing blanks are deleted (the first blank after the argument is replaced with a null char
Definition at line 721 of file lrutils.c.
References argbuf, getarg(), k, num, and p.
Referenced by cli().
Variable Documentation
argbuf
char argbuf[100] static
Definition at line 718 of file lrutils.c.
Referenced by cli(), and xargvar().