flang: lz.h File Reference
lz.h File Reference
definitions for LZ compression used with IPA
#include <stdarg.h>
Classes
struct lzhandle
Macros
#define NOLZ 1
#define LZNOCOMPRESS 0
#define LZCOMPRESS 1
#define LZIPKINFO 2
#define LZIPMINFO 3
#define LZIPOINFO 4
#define LZIPPINFO 5
#define LZIPNINFO 6
#define LZIPXINFO 7
#define LZZLIB 8
#define LZMAX 9
Typedefs
typedef struct lzhandle lzhandle
Functions
char ulzgetc (lzhandle *lzh)
read one char from 'in'
char * ulz (lzhandle *lzh)
read from 'in', return an uncompressed line
lzhandle * lzinitfile (FILE *out, int compress)
call this to set the output file before calling lzprintf
lzhandle * ulzinit (FILE *in, int compress)
call before calling ulz at all
void lzfinifile (lzhandle *lzh)
call this after the last write with lzprintf lsfinifile calls lzfini
void lz (lzhandle *lzh, char *line, int linelen)
encode a single text line, wrote to out
void lzprintf (lzhandle *lzh, const char *fmt,...)
call lzprintf like printf(fmt,arg,arg,...); lzprintf calls lz
void lzreinit (lzhandle *lzh)
call this to reset the compression tables between sections
void lzreset (lzhandle *lzh)
...
void lzrestore (lzhandle *lzh)
call lzwriterestore to restore position in file and state of dictionary
void lzsave (lzhandle *lzh)
call lzwritesave to save position in file and state of dictionary
void ulzfini (lzhandle *lzh)
call when done calling ulz
Detailed Description
definitions for LZ compression used with IPA
Definition in file lz.h.
Macro Definition Documentation
LZCOMPRESS
#define LZCOMPRESS 1
Definition at line 34 of file lz.h.
LZIPKINFO
#define LZIPKINFO 2
Definition at line 35 of file lz.h.
LZIPMINFO
#define LZIPMINFO 3
Definition at line 36 of file lz.h.
LZIPNINFO
#define LZIPNINFO 6
Definition at line 39 of file lz.h.
LZIPOINFO
#define LZIPOINFO 4
Definition at line 37 of file lz.h.
LZIPPINFO
#define LZIPPINFO 5
Definition at line 38 of file lz.h.
LZIPXINFO
#define LZIPXINFO 7
Definition at line 40 of file lz.h.
LZMAX
#define LZMAX 9
Definition at line 42 of file lz.h.
LZNOCOMPRESS
#define LZNOCOMPRESS 0
Definition at line 33 of file lz.h.
LZZLIB
#define LZZLIB 8
Definition at line 41 of file lz.h.
NOLZ
#define NOLZ 1
Definition at line 19 of file lz.h.
Typedef Documentation
lzhandle
typedef struct lzhandle lzhandle
Function Documentation
lz()
void lz (lzhandle * lzh, char * line, int linelen)
encode a single text line, wrote to out
Definition at line 46 of file lz.c.
References lzhandle::file, and line.
Referenced by __reduction_slowpath_pio2(), export_header(), LZMPLXFUNC_LZ_I(), LZMPLXFUNC_LZ_K(), and reduction_slowpath().
lzfinifile()
void lzfinifile (lzhandle * lzh)
call this after the last write with lzprintf lsfinifile calls lzfini
Definition at line 72 of file lz.c.
References fflush(), lzhandle::file, and lzfini().
Referenced by export(), export_host_subprogram(), and export_module_subprogram().
lzinitfile()
lzhandle * lzinitfile (FILE * out, int compress)
call this to set the output file before calling lzprintf
Definition at line 55 of file lz.c.
References lzhandle::file, lzhandle::inout, malloc(), and NULL.
Referenced by export_header().
lzprintf()
void lzprintf (lzhandle * lzh, const char * fmt, ...)
call lzprintf like printf(fmt,arg,arg,...); lzprintf calls lz
Definition at line 82 of file lz.c.
References lzhandle::file.
Referenced by export(), export_derived_dt(), export_dt(), export_equiv_item(), export_header(), export_ict(), export_ieee_arith_libraries(), export_iso_c_libraries(), export_iso_fortran_env_libraries(), export_ivl(), export_ivl_ict(), export_one_ast(), export_one_std(), export_some_fini(), and export_symbol().
lzreinit()
void lzreinit (lzhandle * lzh)
call this to reset the compression tables between sections
Definition at line 24 of file lz.c.
Referenced by lzreset().
lzreset()
void lzreset (lzhandle * lzh)
...
Definition at line 29 of file lz.c.
References lzreinit().
lzrestore()
void lzrestore (lzhandle * lzh)
call lzwriterestore to restore position in file and state of dictionary
Definition at line 186 of file lz.c.
References lzhandle::file, lzhandle::inout, and lzhandle::savefile.
lzsave()
void lzsave (lzhandle * lzh)
call lzwritesave to save position in file and state of dictionary
Definition at line 176 of file lz.c.
References lzhandle::file, and lzhandle::savefile.
ulz()
char * ulz (lzhandle * lzh)
read from 'in', return an uncompressed line
Definition at line 129 of file lz.c.
References lzhandle::buff, lzhandle::bufflen, lzhandle::buffsize, lzhandle::file, getline(), NULL, and res.
ulzfini()
void ulzfini (lzhandle * lzh)
call when done calling ulz
Definition at line 120 of file lz.c.
References lzfini().
Referenced by import_done(), import_header(), and import_header_only().
ulzgetc()
char ulzgetc (lzhandle * lzh)
read one char from 'in'
Definition at line 167 of file lz.c.
References lzhandle::file.
ulzinit()
lzhandle * ulzinit (FILE * in, int compress)
call before calling ulz at all
Definition at line 95 of file lz.c.
References lzhandle::buff, lzhandle::bufflen, lzhandle::buffsize, lzhandle::file, lzhandle::inout, malloc(), and NULL.
Referenced by import_header_only().