flang: mach.h File Reference
mach.h File Reference
Structures to describe the x86 CPU type and CPU features.
Classes
struct MACHTYPE
Macros
#define MACH_GENERIC 1
#define MACH_INTEL 2
#define MACH_INTEL_PENTIUM4 3
#define MACH_INTEL_CORE2 4
#define MACH_INTEL_PENRYN 5
#define MACH_INTEL_NEHALEM 6
#define MACH_INTEL_SANDYBRIDGE 7
#define MACH_INTEL_HASWELL 8
#define MACH_INTEL_KNIGHTS_LANDING 9
#define MACH_INTEL_SKYLAKE 10
#define MACH_INTEL_LARRABEE 11 /* delete this when possible! */
#define MACH_AMD 12
#define MACH_AMD_ATHLON 13
#define MACH_AMD_ATHLON_XP 14
#define MACH_AMD_HAMMER 15
#define MACH_AMD_GH 16
#define MACH_AMD_SHANGHAI 17
#define MACH_AMD_ISTANBUL 18
#define MACH_AMD_BULLDOZER 19
#define MACH_AMD_PILEDRIVER 20
#define MACH_AMD_ZEN 21
#define MACH_NUMBER 22
#define FEATURE_SCALAR_SSE 0 /* -Mscalarsse flag */
#define FEATURE_SSE 1 /* supports SSE */
#define FEATURE_SSE2 2 /* supports SSE2 */
#define FEATURE_SSE3 3 /* supports SSE3 */
#define FEATURE_SSE41 4 /* " SSE4.1 (>= Intel penryn, AMD bulldozer) */
#define FEATURE_SSE42 5 /* " SSE4.2 (>= Intel nehalem, AMD bulldozer)*/
#define FEATURE_SSE4A 6 /* " SSE4a (>= AMD barcelona) */
#define FEATURE_SSE5 7 /* " SSE5 (AMD) */
#define FEATURE_MNI 8 /* " Meron New Instructions, SSSE3 Intel */
#define FEATURE_DAZ 9 /* -Mdaz flag, denorm as zero */
#define FEATURE_PREFER_MOVLPD 10 /* prefer movlpd over movsd, used in CG */
#define FEATURE_USE_INC 11 /* prefer incl over addl $1 */
#define FEATURE_USE_MOVAPD 12 /* use movapd instead of movsd */
#define FEATURE_MERGE_DEPENDENT 13 /* different CG decisions */
#define FEATURE_SCALAR_NONTEMP 14 /* in llvect */
#define FEATURE_SSEIMAX 15 /* use SSE code sequence for IMAX/IMIN */
#define FEATURE_MISALIGNEDSSE 16 /* allow misaligned SSE ops from memory */
#define FEATURE_LD_MOVUPD 17 /* use movupd for unaligned packed loads */
#define FEATURE_ST_MOVUPD 18 /* use movupd for unaligned packed stores */
#define FEATURE_UNROLL_16
#define FEATURE_DOUBLE_UNROLL 20 /* double unroll factor (initially for GH) */
#define FEATURE_PEEL_SHUFFLE 21 /* allow peel-shuffle */
#define FEATURE_PREFETCHNTA 22 /* allow prefetchnta */
#define FEATURE_PDSHUF 23 /* prefer PDSHUF over UNPCK[LH]PD etc. */
#define FEATURE_SSEPMAX 24 /* use PMAX/PMIN for IMAX/IMIN in SSE (SSE4.1) */
#define FEATURE_GHLIBS 25 /* use _gh library routines */
#define FEATURE_SSEMISALN 26 /* allow misaligned SSE memory operands */
#define FEATURE_ABM 27 /* allow advanced bit manipulation */
#define FEATURE_AVX 28 /* supports AVX - Advanced Vector Extensions */
#define FEATURE_LRBNI 29 /* supports LRBni - Larrabee new instructions */
#define FEATURE_FMA4 30 /* supports 4-operand FMA */
#define FEATURE_XOP 31 /* supports eXtended OPerations */
#define FEATURE_FMA3 32 /* supports 3-operand FMA */
#define FEATURE_MULTI_ACCUM 33 /* multiple accumulators for reductions */
#define FEATURE_SIMD128 34 /* Use SIMD:128, even with AVX */
#define FEATURE_NOPREFETCH 35 /* Disable prefetches */
#define FEATURE_ALIGNLOOP4 36 /* Align loops at 4 */
#define FEATURE_ALIGNLOOP8 37 /* Align loops at 8 */
#define FEATURE_ALIGNLOOP16 38 /* Align loops at 16 */
#define FEATURE_ALIGNLOOP32 39 /* Align loops at 32 */
#define FEATURE_ALIGNJMP8 40 /* Align after jump at 8 */
#define FEATURE_ALIGNJMP16 41 /* after after jump at 16 */
#define FEATURE_LD_VMOVUPD 42 /* use vmovupd for 32-byte unaligned loads */
#define FEATURE_ST_VMOVUPD 43 /* use vmovupd for 32-byte unaligned stores */
#define FEATURE_AVX2 44 /* supports AVX2 */
#define FEATURE_AVX512F 45 /* supports AVX-512F */
#define FEATURE_AVX512VL 46 /* supports AVX-512VL */
#define FEATURE_NUMBER 47
#define TP_PY 1
#define TP_PX 2
#define TP_P5 3
#define TP_ATHLON 4
#define TP_P6 5
#define TP_ATHLON_XP 6
#define TP_PIII 7
#define TP_K8 8
#define TP_P7 9
#define TP_K8E 10
#define TP_PIV 11
#define TP_GH 12
#define TP_CORE2 13
#define TP_PENRYN 14
#define TP_SHANGHAI 15
#define TP_ISTANBUL 16
#define TP_NEHALEM 17
#define TP_BULLDOZER 18
#define TP_SANDYBRIDGE 19
#define TP_IVYBRIDGE 20
#define TP_HASWELL 21
#define TP_LARRABEE 22 /* delete this when possible! */
#define TP_PILEDRIVER 23
#define TP_ZEN 24
#define TP_KNIGHTS_LANDING 25
#define TP_SKYLAKE 26
#define TEST_MACH(M) (mach.type[M])
#define TEST_MACH2(M1, M2) (mach.type[M1] || mach.type[M2])
#define TEST_MACHN(M, N) (mach.type[M])
#define TEST_FEATURE(M) (mach.feature[M])
#define TEST_FEATURE2(M1, M2) (mach.feature[M1] || mach.feature[M2])
#define TEST_FEATUREN(M, N) (mach.feature[M])
#define TEST_CACHE (mach.cachesize)
#define TEST_ACCEL mach.accel
Functions
bool any_gpu_device (void)
return true if any accelerator is not the host device
bool have_mach_accel (int v)
Is this accel type specified on the command line?
char * sxaccel (int a)
...
char * sxacceltype (int a)
...
char * sxaccfeature (int a)
...
const char * sxfeature (int f)
...
const char * sxtp (int tp)
...
const char * sxtype (int m)
...
int acctype (int accval)
return ACC_TYPE value from accelerator value
int accvalue (char *accname)
return ACC_ value given the accelerator name
int machvalue (const char *thistpname)
...
void check_no_acc (void)
make sure the first accelerator is ACC_MULTICORE or ACC_HOST
void check_tp (bool skip)
...
void copy_mach_intersect (MACHTYPE *mach)
...
void dumpmach (void)
...
void _dumpmach (MACHTYPE *mach)
...
void init_mach_intersect (void)
...
void intersect_mach_intersect (MACHTYPE *mach)
...
void set_acc (char *accname)
...
void set_mach_accel (MACHTYPE *mach, int accelvalue)
set mach.accel
void set_mach (MACHTYPE *mach, int machtype)
...
void set_tp (const char *thistpname)
...
Variables
MACHTYPE mach
Detailed Description
Structures to describe the x86 CPU type and CPU features.
Definition in file mach.h.
Macro Definition Documentation
FEATURE_ABM
#define FEATURE_ABM 27 /* allow advanced bit manipulation */
Definition at line 67 of file mach.h.
FEATURE_ALIGNJMP16
#define FEATURE_ALIGNJMP16 41 /* after after jump at 16 */
Definition at line 81 of file mach.h.
FEATURE_ALIGNJMP8
#define FEATURE_ALIGNJMP8 40 /* Align after jump at 8 */
Definition at line 80 of file mach.h.
FEATURE_ALIGNLOOP16
#define FEATURE_ALIGNLOOP16 38 /* Align loops at 16 */
Definition at line 78 of file mach.h.
FEATURE_ALIGNLOOP32
#define FEATURE_ALIGNLOOP32 39 /* Align loops at 32 */
Definition at line 79 of file mach.h.
FEATURE_ALIGNLOOP4
#define FEATURE_ALIGNLOOP4 36 /* Align loops at 4 */
Definition at line 76 of file mach.h.
FEATURE_ALIGNLOOP8
#define FEATURE_ALIGNLOOP8 37 /* Align loops at 8 */
Definition at line 77 of file mach.h.
FEATURE_AVX
#define FEATURE_AVX 28 /* supports AVX - Advanced Vector Extensions */
Definition at line 68 of file mach.h.
FEATURE_AVX2
#define FEATURE_AVX2 44 /* supports AVX2 */
Definition at line 84 of file mach.h.
FEATURE_AVX512F
#define FEATURE_AVX512F 45 /* supports AVX-512F */
Definition at line 85 of file mach.h.
FEATURE_AVX512VL
#define FEATURE_AVX512VL 46 /* supports AVX-512VL */
Definition at line 86 of file mach.h.
FEATURE_DAZ
#define FEATURE_DAZ 9 /* -Mdaz flag, denorm as zero */
Definition at line 49 of file mach.h.
FEATURE_DOUBLE_UNROLL
#define FEATURE_DOUBLE_UNROLL 20 /* double unroll factor (initially for GH) */
Definition at line 60 of file mach.h.
FEATURE_FMA3
#define FEATURE_FMA3 32 /* supports 3-operand FMA */
Definition at line 72 of file mach.h.
FEATURE_FMA4
#define FEATURE_FMA4 30 /* supports 4-operand FMA */
Definition at line 70 of file mach.h.
FEATURE_GHLIBS
#define FEATURE_GHLIBS 25 /* use _gh library routines */
Definition at line 65 of file mach.h.
FEATURE_LD_MOVUPD
#define FEATURE_LD_MOVUPD 17 /* use movupd for unaligned packed loads */
Definition at line 57 of file mach.h.
FEATURE_LD_VMOVUPD
#define FEATURE_LD_VMOVUPD 42 /* use vmovupd for 32-byte unaligned loads */
Definition at line 82 of file mach.h.
FEATURE_LRBNI
#define FEATURE_LRBNI 29 /* supports LRBni - Larrabee new instructions */
Definition at line 69 of file mach.h.
FEATURE_MERGE_DEPENDENT
#define FEATURE_MERGE_DEPENDENT 13 /* different CG decisions */
Definition at line 53 of file mach.h.
FEATURE_MISALIGNEDSSE
#define FEATURE_MISALIGNEDSSE 16 /* allow misaligned SSE ops from memory */
Definition at line 56 of file mach.h.
FEATURE_MNI
#define FEATURE_MNI 8 /* " Meron New Instructions, SSSE3 Intel */
Definition at line 48 of file mach.h.
FEATURE_MULTI_ACCUM
#define FEATURE_MULTI_ACCUM 33 /* multiple accumulators for reductions */
Definition at line 73 of file mach.h.
FEATURE_NOPREFETCH
#define FEATURE_NOPREFETCH 35 /* Disable prefetches */
Definition at line 75 of file mach.h.
FEATURE_NUMBER
#define FEATURE_NUMBER 47
Definition at line 88 of file mach.h.
FEATURE_PDSHUF
#define FEATURE_PDSHUF 23 /* prefer PDSHUF over UNPCK[LH]PD etc. */
Definition at line 63 of file mach.h.
FEATURE_PEEL_SHUFFLE
#define FEATURE_PEEL_SHUFFLE 21 /* allow peel-shuffle */
Definition at line 61 of file mach.h.
FEATURE_PREFER_MOVLPD
#define FEATURE_PREFER_MOVLPD 10 /* prefer movlpd over movsd, used in CG */
Definition at line 50 of file mach.h.
FEATURE_PREFETCHNTA
#define FEATURE_PREFETCHNTA 22 /* allow prefetchnta */
Definition at line 62 of file mach.h.
FEATURE_SCALAR_NONTEMP
#define FEATURE_SCALAR_NONTEMP 14 /* in llvect */
Definition at line 54 of file mach.h.
FEATURE_SCALAR_SSE
#define FEATURE_SCALAR_SSE 0 /* -Mscalarsse flag */
Definition at line 40 of file mach.h.
FEATURE_SIMD128
#define FEATURE_SIMD128 34 /* Use SIMD:128, even with AVX */
Definition at line 74 of file mach.h.
FEATURE_SSE
#define FEATURE_SSE 1 /* supports SSE */
Definition at line 41 of file mach.h.
FEATURE_SSE2
#define FEATURE_SSE2 2 /* supports SSE2 */
Definition at line 42 of file mach.h.
FEATURE_SSE3
#define FEATURE_SSE3 3 /* supports SSE3 */
Definition at line 43 of file mach.h.
FEATURE_SSE41
#define FEATURE_SSE41 4 /* " SSE4.1 (>= Intel penryn, AMD bulldozer) */
Definition at line 44 of file mach.h.
FEATURE_SSE42
#define FEATURE_SSE42 5 /* " SSE4.2 (>= Intel nehalem, AMD bulldozer)*/
Definition at line 45 of file mach.h.
FEATURE_SSE4A
#define FEATURE_SSE4A 6 /* " SSE4a (>= AMD barcelona) */
Definition at line 46 of file mach.h.
FEATURE_SSE5
#define FEATURE_SSE5 7 /* " SSE5 (AMD) */
Definition at line 47 of file mach.h.
FEATURE_SSEIMAX
#define FEATURE_SSEIMAX 15 /* use SSE code sequence for IMAX/IMIN */
Definition at line 55 of file mach.h.
FEATURE_SSEMISALN
#define FEATURE_SSEMISALN 26 /* allow misaligned SSE memory operands */
Definition at line 66 of file mach.h.
FEATURE_SSEPMAX
#define FEATURE_SSEPMAX 24 /* use PMAX/PMIN for IMAX/IMIN in SSE (SSE4.1) */
Definition at line 64 of file mach.h.
FEATURE_ST_MOVUPD
#define FEATURE_ST_MOVUPD 18 /* use movupd for unaligned packed stores */
Definition at line 58 of file mach.h.
FEATURE_ST_VMOVUPD
#define FEATURE_ST_VMOVUPD 43 /* use vmovupd for 32-byte unaligned stores */
Definition at line 83 of file mach.h.
FEATURE_UNROLL_16
#define FEATURE_UNROLL_16
Value:
                                  19     /* extra unrolling, unroll factor is 16 \
                                  *   (initially for GH) */
Definition at line 59 of file mach.h.
FEATURE_USE_INC
#define FEATURE_USE_INC 11 /* prefer incl over addl $1 */
Definition at line 51 of file mach.h.
FEATURE_USE_MOVAPD
#define FEATURE_USE_MOVAPD 12 /* use movapd instead of movsd */
Definition at line 52 of file mach.h.
FEATURE_XOP
#define FEATURE_XOP 31 /* supports eXtended OPerations */
Definition at line 71 of file mach.h.
MACH_AMD
#define MACH_AMD 12
Definition at line 27 of file mach.h.
MACH_AMD_ATHLON
#define MACH_AMD_ATHLON 13
Definition at line 28 of file mach.h.
MACH_AMD_ATHLON_XP
#define MACH_AMD_ATHLON_XP 14
Definition at line 29 of file mach.h.
MACH_AMD_BULLDOZER
#define MACH_AMD_BULLDOZER 19
Definition at line 34 of file mach.h.
MACH_AMD_GH
#define MACH_AMD_GH 16
Definition at line 31 of file mach.h.
MACH_AMD_HAMMER
#define MACH_AMD_HAMMER 15
Definition at line 30 of file mach.h.
MACH_AMD_ISTANBUL
#define MACH_AMD_ISTANBUL 18
Definition at line 33 of file mach.h.
MACH_AMD_PILEDRIVER
#define MACH_AMD_PILEDRIVER 20
Definition at line 35 of file mach.h.
MACH_AMD_SHANGHAI
#define MACH_AMD_SHANGHAI 17
Definition at line 32 of file mach.h.
MACH_AMD_ZEN
#define MACH_AMD_ZEN 21
Definition at line 36 of file mach.h.
MACH_GENERIC
#define MACH_GENERIC 1
Definition at line 16 of file mach.h.
MACH_INTEL
#define MACH_INTEL 2
Definition at line 17 of file mach.h.
MACH_INTEL_CORE2
#define MACH_INTEL_CORE2 4
Definition at line 19 of file mach.h.
MACH_INTEL_HASWELL
#define MACH_INTEL_HASWELL 8
Definition at line 23 of file mach.h.
MACH_INTEL_KNIGHTS_LANDING
#define MACH_INTEL_KNIGHTS_LANDING 9
Definition at line 24 of file mach.h.
MACH_INTEL_LARRABEE
#define MACH_INTEL_LARRABEE 11 /* delete this when possible! */
Definition at line 26 of file mach.h.
MACH_INTEL_NEHALEM
#define MACH_INTEL_NEHALEM 6
Definition at line 21 of file mach.h.
MACH_INTEL_PENRYN
#define MACH_INTEL_PENRYN 5
Definition at line 20 of file mach.h.
MACH_INTEL_PENTIUM4
#define MACH_INTEL_PENTIUM4 3
Definition at line 18 of file mach.h.
MACH_INTEL_SANDYBRIDGE
#define MACH_INTEL_SANDYBRIDGE 7
Definition at line 22 of file mach.h.
MACH_INTEL_SKYLAKE
#define MACH_INTEL_SKYLAKE 10
Definition at line 25 of file mach.h.
MACH_NUMBER
#define MACH_NUMBER 22
Definition at line 38 of file mach.h.
TEST_ACCEL
#define TEST_ACCEL mach.accel
Definition at line 152 of file mach.h.
TEST_CACHE
#define TEST_CACHE (mach.cachesize)
Definition at line 151 of file mach.h.
TEST_FEATURE
#define TEST_FEATURE (M) (mach.feature[M])
Definition at line 148 of file mach.h.
TEST_FEATURE2
#define TEST_FEATURE2 (M1, M2) (mach.feature[M1] || mach.feature[M2])
Definition at line 149 of file mach.h.
TEST_FEATUREN
#define TEST_FEATUREN (M, N) (mach.feature[M])
Definition at line 150 of file mach.h.
TEST_MACH
#define TEST_MACH (M) (mach.type[M])
Definition at line 145 of file mach.h.
TEST_MACH2
#define TEST_MACH2 (M1, M2) (mach.type[M1] || mach.type[M2])
Definition at line 146 of file mach.h.
TEST_MACHN
#define TEST_MACHN (M, N) (mach.type[M])
Definition at line 147 of file mach.h.
TP_ATHLON
#define TP_ATHLON 4
Definition at line 121 of file mach.h.
TP_ATHLON_XP
#define TP_ATHLON_XP 6
Definition at line 123 of file mach.h.
TP_BULLDOZER
#define TP_BULLDOZER 18
Definition at line 135 of file mach.h.
TP_CORE2
#define TP_CORE2 13
Definition at line 130 of file mach.h.
TP_GH
#define TP_GH 12
Definition at line 129 of file mach.h.
TP_HASWELL
#define TP_HASWELL 21
Definition at line 138 of file mach.h.
TP_ISTANBUL
#define TP_ISTANBUL 16
Definition at line 133 of file mach.h.
TP_IVYBRIDGE
#define TP_IVYBRIDGE 20
Definition at line 137 of file mach.h.
TP_K8
#define TP_K8 8
Definition at line 125 of file mach.h.
TP_K8E
#define TP_K8E 10
Definition at line 127 of file mach.h.
TP_KNIGHTS_LANDING
#define TP_KNIGHTS_LANDING 25
Definition at line 142 of file mach.h.
TP_LARRABEE
#define TP_LARRABEE 22 /* delete this when possible! */
Definition at line 139 of file mach.h.
TP_NEHALEM
#define TP_NEHALEM 17
Definition at line 134 of file mach.h.
TP_P5
#define TP_P5 3
Definition at line 120 of file mach.h.
TP_P6
#define TP_P6 5
Definition at line 122 of file mach.h.
TP_P7
#define TP_P7 9
Definition at line 126 of file mach.h.
TP_PENRYN
#define TP_PENRYN 14
Definition at line 131 of file mach.h.
TP_PIII
#define TP_PIII 7
Definition at line 124 of file mach.h.
TP_PILEDRIVER
#define TP_PILEDRIVER 23
Definition at line 140 of file mach.h.
TP_PIV
#define TP_PIV 11
Definition at line 128 of file mach.h.
TP_PX
#define TP_PX 2
Definition at line 119 of file mach.h.
TP_PY
#define TP_PY 1
Definition at line 118 of file mach.h.
TP_SANDYBRIDGE
#define TP_SANDYBRIDGE 19
Definition at line 136 of file mach.h.
TP_SHANGHAI
#define TP_SHANGHAI 15
Definition at line 132 of file mach.h.
TP_SKYLAKE
#define TP_SKYLAKE 26
Definition at line 143 of file mach.h.
TP_ZEN
#define TP_ZEN 24
Definition at line 141 of file mach.h.
Function Documentation
_dumpmach()
void _dumpmach (MACHTYPE * mach)
...
acctype()
int acctype (int accval)
return ACC_TYPE value from accelerator value
accvalue()
int accvalue (char * accname)
return ACC_ value given the accelerator name
any_gpu_device()
bool any_gpu_device (void)
return true if any accelerator is not the host device
check_no_acc()
void check_no_acc (void)
make sure the first accelerator is ACC_MULTICORE or ACC_HOST
If there are more than one TP value also fill in flg.acctypeindex.
check_tp()
void check_tp (bool skip)
...
Definition at line 677 of file mach.c.
copy_mach_intersect()
void copy_mach_intersect (MACHTYPE * mach)
...
Definition at line 589 of file mach.c.
References MACHTYPE::cachesize, MACHTYPE::feature, FEATURE_NUMBER, for(), i, mach, mach_intersect, MACH_NUMBER, and MACHTYPE::type.
dumpmach()
void dumpmach (void)
...
have_mach_accel()
bool have_mach_accel (int v)
Is this accel type specified on the command line?
init_mach_intersect()
void init_mach_intersect (void)
...
Definition at line 559 of file mach.c.
References MACHTYPE::cachesize, MACHTYPE::feature, FEATURE_NUMBER, for(), i, mach_intersect, MACH_NUMBER, MACHTYPE::tpval, and MACHTYPE::type.
intersect_mach_intersect()
void intersect_mach_intersect (MACHTYPE * mach)
...
Definition at line 572 of file mach.c.
References MACHTYPE::cachesize, MACHTYPE::feature, FEATURE_NUMBER, i, mach, mach_intersect, MACH_NUMBER, and MACHTYPE::type.
machvalue()
int machvalue (const char * thistpname)
...
Definition at line 600 of file mach.c.
References strlen(), TP_BULLDOZER, TP_CORE2, TP_GH, TP_HASWELL, TP_ISTANBUL, TP_IVYBRIDGE, TP_K8, TP_K8E, TP_KNIGHTS_LANDING, TP_NEHALEM, TP_P7, TP_PENRYN, TP_PILEDRIVER, TP_PX, TP_PY, TP_SANDYBRIDGE, TP_SHANGHAI, TP_SKYLAKE, and TP_ZEN.
Referenced by set_tp().
set_acc()
void set_acc (char * accname)
...
set_mach()
void set_mach (MACHTYPE * mach, int machtype)
...
Definition at line 27 of file mach.c.
References MACHTYPE::cachesize, DONT_GENERATE_AVX512, MACHTYPE::feature, FEATURE_ABM, FEATURE_ALIGNJMP16, FEATURE_ALIGNJMP8, FEATURE_ALIGNLOOP16, FEATURE_ALIGNLOOP32, FEATURE_ALIGNLOOP4, FEATURE_ALIGNLOOP8, FEATURE_AVX, FEATURE_AVX2, FEATURE_AVX512F, FEATURE_AVX512VL, FEATURE_DAZ, FEATURE_DOUBLE_UNROLL, FEATURE_FMA3, FEATURE_FMA4, FEATURE_GHLIBS, FEATURE_LD_MOVUPD, FEATURE_LD_VMOVUPD, FEATURE_LRBNI, FEATURE_MERGE_DEPENDENT, FEATURE_MISALIGNEDSSE, FEATURE_MNI, FEATURE_MULTI_ACCUM, FEATURE_NOPREFETCH, FEATURE_PDSHUF, FEATURE_PEEL_SHUFFLE, FEATURE_PREFER_MOVLPD, FEATURE_PREFETCHNTA, FEATURE_SCALAR_NONTEMP, FEATURE_SCALAR_SSE, FEATURE_SIMD128, FEATURE_SSE, FEATURE_SSE2, FEATURE_SSE3, FEATURE_SSE41, FEATURE_SSE42, FEATURE_SSE4A, FEATURE_SSE5, FEATURE_SSEIMAX, FEATURE_SSEMISALN, FEATURE_SSEPMAX, FEATURE_ST_MOVUPD, FEATURE_ST_VMOVUPD, FEATURE_UNROLL_16, FEATURE_USE_INC, FEATURE_USE_MOVAPD, FEATURE_XOP, FLANG_FALLTHROUGH, flg, if(), mach, MACH_AMD, MACH_AMD_BULLDOZER, MACH_AMD_GH, MACH_AMD_HAMMER, MACH_AMD_ISTANBUL, MACH_AMD_PILEDRIVER, MACH_AMD_SHANGHAI, MACH_AMD_ZEN, MACH_GENERIC, MACH_INTEL, MACH_INTEL_CORE2, MACH_INTEL_HASWELL, MACH_INTEL_KNIGHTS_LANDING, MACH_INTEL_LARRABEE, MACH_INTEL_NEHALEM, MACH_INTEL_PENRYN, MACH_INTEL_PENTIUM4, MACH_INTEL_SANDYBRIDGE, MACH_INTEL_SKYLAKE, TP_BULLDOZER, TP_CORE2, TP_GH, TP_HASWELL, TP_ISTANBUL, TP_IVYBRIDGE, TP_K8, TP_K8E, TP_KNIGHTS_LANDING, TP_LARRABEE, TP_NEHALEM, TP_P7, TP_PENRYN, TP_PILEDRIVER, TP_PX, TP_PY, TP_SANDYBRIDGE, TP_SHANGHAI, TP_SKYLAKE, TP_ZEN, MACHTYPE::tpval, MACHTYPE::type, FLG::x, and XBIT.
Referenced by direct_rou_load(), and init().
set_mach_accel()
void set_mach_accel (MACHTYPE * mach, int accelvalue)
set mach.accel
set_tp()
void set_tp (const char * thistpname)
...
Definition at line 657 of file mach.c.
References ERR_Fatal, flg, interr(), machvalue(), n, FLG::tpcount, TPNVERSION, and FLG::tpvalue.
Referenced by do_set_tp(), and init().
sxaccel()
char * sxaccel (int a)
...
sxacceltype()
char * sxacceltype (int a)
...
sxaccfeature()
char * sxaccfeature (int a)
...
sxfeature()
const char * sxfeature (int f)
...
sxtp()
const char * sxtp (int tp)
...
sxtype()
const char * sxtype (int m)
...
Variable Documentation
mach
MACHTYPE mach extern
Definition at line 18 of file mach.c.
Referenced by addbran(), assemble_end(), copy_mach_intersect(), direct_rou_load(), init(), intersect_mach_intersect(), and set_mach().