flang: mach.c File Reference
mach.c File Reference
Structures to describe the x86 CPU type and CPU features.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "mach.h"
Macros
#define DONT_GENERATE_AVX512 false
Functions
void set_mach (MACHTYPE *mach, int machtype)
...
void init_mach_intersect ()
...
void intersect_mach_intersect (MACHTYPE *mach)
...
void copy_mach_intersect (MACHTYPE *mach)
...
int machvalue (const char *thistpname)
...
void set_tp (const char *thistpname)
...
void check_tp (bool skip)
...
Variables
MACHTYPE mach
static MACHTYPE mach_intersect
Detailed Description
Structures to describe the x86 CPU type and CPU features.
Definition in file mach.c.
Macro Definition Documentation
DONT_GENERATE_AVX512
#define DONT_GENERATE_AVX512 false
Definition at line 23 of file mach.c.
Function Documentation
check_tp()
void check_tp (bool skip)
...
Definition at line 677 of file mach.c.
copy_mach_intersect()
void copy_mach_intersect (MACHTYPE * mach)
...
Definition at line 589 of file mach.c.
References MACHTYPE::cachesize, MACHTYPE::feature, FEATURE_NUMBER, for(), i, mach, mach_intersect, MACH_NUMBER, and MACHTYPE::type.
init_mach_intersect()
void init_mach_intersect (void)
...
Definition at line 559 of file mach.c.
References MACHTYPE::cachesize, MACHTYPE::feature, FEATURE_NUMBER, for(), i, mach_intersect, MACH_NUMBER, MACHTYPE::tpval, and MACHTYPE::type.
intersect_mach_intersect()
void intersect_mach_intersect (MACHTYPE * mach)
...
Definition at line 572 of file mach.c.
References MACHTYPE::cachesize, MACHTYPE::feature, FEATURE_NUMBER, i, mach, mach_intersect, MACH_NUMBER, and MACHTYPE::type.
machvalue()
int machvalue (const char * thistpname)
...
Definition at line 600 of file mach.c.
References strlen(), TP_BULLDOZER, TP_CORE2, TP_GH, TP_HASWELL, TP_ISTANBUL, TP_IVYBRIDGE, TP_K8, TP_K8E, TP_KNIGHTS_LANDING, TP_NEHALEM, TP_P7, TP_PENRYN, TP_PILEDRIVER, TP_PX, TP_PY, TP_SANDYBRIDGE, TP_SHANGHAI, TP_SKYLAKE, and TP_ZEN.
Referenced by set_tp().
set_mach()
void set_mach (MACHTYPE * mach, int machtype)
...
Definition at line 27 of file mach.c.
References MACHTYPE::cachesize, DONT_GENERATE_AVX512, MACHTYPE::feature, FEATURE_ABM, FEATURE_ALIGNJMP16, FEATURE_ALIGNJMP8, FEATURE_ALIGNLOOP16, FEATURE_ALIGNLOOP32, FEATURE_ALIGNLOOP4, FEATURE_ALIGNLOOP8, FEATURE_AVX, FEATURE_AVX2, FEATURE_AVX512F, FEATURE_AVX512VL, FEATURE_DAZ, FEATURE_DOUBLE_UNROLL, FEATURE_FMA3, FEATURE_FMA4, FEATURE_GHLIBS, FEATURE_LD_MOVUPD, FEATURE_LD_VMOVUPD, FEATURE_LRBNI, FEATURE_MERGE_DEPENDENT, FEATURE_MISALIGNEDSSE, FEATURE_MNI, FEATURE_MULTI_ACCUM, FEATURE_NOPREFETCH, FEATURE_PDSHUF, FEATURE_PEEL_SHUFFLE, FEATURE_PREFER_MOVLPD, FEATURE_PREFETCHNTA, FEATURE_SCALAR_NONTEMP, FEATURE_SCALAR_SSE, FEATURE_SIMD128, FEATURE_SSE, FEATURE_SSE2, FEATURE_SSE3, FEATURE_SSE41, FEATURE_SSE42, FEATURE_SSE4A, FEATURE_SSE5, FEATURE_SSEIMAX, FEATURE_SSEMISALN, FEATURE_SSEPMAX, FEATURE_ST_MOVUPD, FEATURE_ST_VMOVUPD, FEATURE_UNROLL_16, FEATURE_USE_INC, FEATURE_USE_MOVAPD, FEATURE_XOP, FLANG_FALLTHROUGH, flg, if(), mach, MACH_AMD, MACH_AMD_BULLDOZER, MACH_AMD_GH, MACH_AMD_HAMMER, MACH_AMD_ISTANBUL, MACH_AMD_PILEDRIVER, MACH_AMD_SHANGHAI, MACH_AMD_ZEN, MACH_GENERIC, MACH_INTEL, MACH_INTEL_CORE2, MACH_INTEL_HASWELL, MACH_INTEL_KNIGHTS_LANDING, MACH_INTEL_LARRABEE, MACH_INTEL_NEHALEM, MACH_INTEL_PENRYN, MACH_INTEL_PENTIUM4, MACH_INTEL_SANDYBRIDGE, MACH_INTEL_SKYLAKE, TP_BULLDOZER, TP_CORE2, TP_GH, TP_HASWELL, TP_ISTANBUL, TP_IVYBRIDGE, TP_K8, TP_K8E, TP_KNIGHTS_LANDING, TP_LARRABEE, TP_NEHALEM, TP_P7, TP_PENRYN, TP_PILEDRIVER, TP_PX, TP_PY, TP_SANDYBRIDGE, TP_SHANGHAI, TP_SKYLAKE, TP_ZEN, MACHTYPE::tpval, MACHTYPE::type, FLG::x, and XBIT.
Referenced by direct_rou_load(), and init().
set_tp()
void set_tp (const char * thistpname)
...
Definition at line 657 of file mach.c.
References ERR_Fatal, flg, interr(), machvalue(), n, FLG::tpcount, TPNVERSION, and FLG::tpvalue.
Referenced by do_set_tp(), and init().
Variable Documentation
mach
MACHTYPE mach
Definition at line 18 of file mach.c.
Referenced by addbran(), assemble_end(), copy_mach_intersect(), direct_rou_load(), init(), intersect_mach_intersect(), and set_mach().
mach_intersect
MACHTYPE mach_intersect static
Definition at line 557 of file mach.c.
Referenced by copy_mach_intersect(), init_mach_intersect(), and intersect_mach_intersect().