flang: main.c File Reference
main.c File Reference
main program and initialization routines for fortran front-end
#include "gbldefs.h"
#include <stdbool.h>
#include "flang/ArgParser/arg_parser.h"
#include "error.h"
#include <unistd.h>
#include <time.h>
#include "global.h"
#include "symtab.h"
#include "dtypeutl.h"
#include "version.h"
#include "inliner.h"
#include "interf.h"
#include "semant.h"
#include "dinit.h"
#include "ast.h"
#include "lower.h"
#include "dbg_out.h"
#include "ccffinfo.h"
#include "mach.h"
#include "fdirect.h"
#include "optimize.h"
#include "transfrm.h"
#include "extern.h"
#include "commopt.h"
#include "scan.h"
#include "hlvect.h"
#include "ilidir.h"
Macros
#define IPA_ENABLED 0
#define IPA_NO_ASM 0
#define IPA_COLLECTION_ENABLED 0
#define IPA_INHERIT_ENABLED 0
#define IPA_FUTURE_INHERIT_DISABLED 0
#define IPA_REPORT_ENABLED 0
#define _N_WHO (sizeof(who) / sizeof(char *))
#define DNAME "F90"
#define TR(str)
#define TR1(str)
#define DUMP(a) do_debug(a)
#define NO_FLEXLM
#define __ATOI(s, p, l, r) _atoi(s, p, l)
Functions
static void reptime (void)
static void do_debug (const char *phase)
static void cleanup (void)
static void init (int argc, char *argv[])
Initialize Fortran frontend at the beginning of compilation.
static void datastructure_reinit (void)
static void do_set_tp (const char *tp)
static void fini (void)
static void mkDwfInfoFilename (void)
This function creates a dwarf debug info filename from source file.
int main (int argc, char *argv[])
Fortran front-end main entry.
static void dump_stds (void)
static void dump_sstds (void)
static void dump_stdps (void)
static void dump_symbols (void)
Dump symbols.
static void dump_all_symbols (void)
Dump all symbols.
static void dump_current_symbols (void)
Dump symbols from current source file.
static void dump_old_symbols (void)
Yet another symbol table dumper.
static void report_area (void)
Dump memory area.
static void dump_stg_stats (void)
Dump stg statistics.
void reinit (void)
perform initializations for new user subprogram unit.
void set_exitcode (int ec)
set exit code for compiler (see finish() function)
void finish (void)
Write summary line to terminal, and exit compiler.
void dwarf_set_fn (void)
void setrefsymbol (int symbol)
void scan_for_dwarf_module (void)
void end_contained (void)
called at end of processing contains subprograms
void ipa_closefile ()
void ipa_export ()
void ipa_export_close ()
void ipa_export_endcontained ()
void ipa_export_endmodule ()
void ipa_export_highpoint ()
void ipa_export_open (char *export_filename)
void ipa_header1 (int currfunc)
void ipa_header2 (int currfunc)
void ipa_import_highpoint (void)
void ipa_import_open (char *import_file, BIGUINT offset)
void ipa_import (void)
void ipa_init ()
void ipa_report ()
void ipasave_closefile ()
void ipasave_compname (char *name, int argc, char *argv[])
void ipasave_endfunc ()
void ipasave_fini (void)
void ipasave (void)
void ipa_startfunc (int currfunc)
void ipa_fini ()
void fill_ipasym ()
void ipa ()
void ipa_set_vestigial_host ()
int IPA_isnoconflict (int sptr)
Variables
static int saveoptflag
static int savevectflag
static int savex8flag
static int saverecursive
static LOGICAL has_accel_code = FALSE
static action_map_t * phase_dump_map
static int debugfunconly = -1
static LOGICAL ipa_import_mode = FALSE
static char * ipa_export_file = NULL
static BIGUINT ipa_import_offset = 0
static const char * who []
static INT xtimes [_N_WHO]
static LOGICAL postprocessing = TRUE
static const char * feature = "flang"
static int dodebug = 0
static char * objectfile = NULL
static const char * outfile_name = NULL
LOGICAL fpp_ = FALSE
static int preproc = -1
static const char * current_phase
moddir_list * module_directory_list = NULL
static int exitcode
FILE * dbg_file = NULL
char * dbg_file_name = NULL
int IPA_Vestigial = 0
Detailed Description
main program and initialization routines for fortran front-end
Definition in file main.c.
Macro Definition Documentation
__ATOI
#define __ATOI (s, p, l, r) _atoi(s, p, l)
Definition at line 513 of file main.c.
_N_WHO
#define _N_WHO (sizeof(who) / sizeof(char *))
Definition at line 78 of file main.c.
DNAME
#define DNAME "F90"
Product name in debug output
Definition at line 97 of file main.c.
DUMP
#define DUMP (a) do_debug(a)
Definition at line 109 of file main.c.
IPA_COLLECTION_ENABLED
#define IPA_COLLECTION_ENABLED 0
Definition at line 44 of file main.c.
IPA_ENABLED
#define IPA_ENABLED 0
Definition at line 42 of file main.c.
IPA_FUTURE_INHERIT_DISABLED
#define IPA_FUTURE_INHERIT_DISABLED 0
Definition at line 46 of file main.c.
IPA_INHERIT_ENABLED
#define IPA_INHERIT_ENABLED 0
Definition at line 45 of file main.c.
IPA_NO_ASM
#define IPA_NO_ASM 0
Definition at line 43 of file main.c.
IPA_REPORT_ENABLED
#define IPA_REPORT_ENABLED 0
Definition at line 47 of file main.c.
NO_FLEXLM
#define NO_FLEXLM
Definition at line 116 of file main.c.
TR
#define TR (str)
Value:
  if (dodebug) {              \
    fprintf(gbl.dbgfil, str); \
    fflush(gbl.dbgfil);       \
  }
Definition at line 101 of file main.c.
TR1
#define TR1 (str)
Value:
  if (DBGBIT(0, 512)) \
  dump_stg_stat(str)
Definition at line 106 of file main.c.
Function Documentation
cleanup()
static void cleanup (void) static
Definition at line 1166 of file main.c.
References df_dinit_end(), dinit_end(), direct_rou_end(), FALSE, freearea(), and postprocessing.
Referenced by export(), export_component_init(), and export_module().
datastructure_reinit()
static void datastructure_reinit (void) static
Definition at line 1234 of file main.c.
References astb, astout_init(), ASTB::df, dinit_end(), dinit_init(), FALSE, fclose(), flg, gbl, NOSYM, NULL, FLG::opt, FLG::recursive, RU_PROG, saveoptflag, saverecursive, savevectflag, savex8flag, set_bss_addr(), sym_init(), FLG::vect, and FLG::x.
Referenced by reinit().
do_debug()
static void do_debug (const char * phase) static
Definition at line 1148 of file main.c.
References current_phase, debugfunconly, dodebug, execute_actions_for_keyword(), feature, gbl, and phase_dump_map.
do_set_tp()
static void do_set_tp (const char * tp) static
Definition at line 1443 of file main.c.
References set_tp().
Referenced by init().
dump_all_symbols()
static void dump_all_symbols (void) static
Dump all symbols.
Definition at line 554 of file main.c.
References dsyms().
Referenced by init().
dump_current_symbols()
static void dump_current_symbols (void) static
Dump symbols from current source file.
Definition at line 562 of file main.c.
References dsyms(), STB::firstosym, and stb.
Referenced by init().
dump_old_symbols()
static void dump_old_symbols (void) static
Yet another symbol table dumper.
Definition at line 570 of file main.c.
References gbl, and symdmp().
Referenced by init().
dump_sstds()
static void dump_sstds (void) static
Definition at line 532 of file main.c.
References dsstds().
Referenced by init().
dump_stdps()
static void dump_stdps (void) static
Definition at line 538 of file main.c.
References dstdps().
Referenced by init().
dump_stds()
static void dump_stds (void) static
Definition at line 526 of file main.c.
References dstds().
Referenced by init().
dump_stg_stats()
static void dump_stg_stats (void) static
Dump stg statistics.
Definition at line 588 of file main.c.
References current_phase, and dump_stg_stat().
Referenced by init().
dump_symbols()
static void dump_symbols (void) static
Dump symbols.
Definition at line 546 of file main.c.
References dsyms().
Referenced by init().
dwarf_set_fn()
void dwarf_set_fn (void)
Definition at line 1438 of file main.c.
Referenced by init().
end_contained()
void end_contained (void)
called at end of processing contains subprograms
Definition at line 1472 of file main.c.
References ipa_export_endcontained(), ipa_export_file, ipa_import_mode, and lower_end_contains().
Referenced by check_end_subprogram().
fill_ipasym()
void fill_ipasym (void)
Definition at line 1511 of file main.c.
fini()
static void fini (void) static
Definition at line 1481 of file main.c.
References assemble_end().
Referenced by finish().
finish()
void finish (void)
Write summary line to terminal, and exit compiler.
...
Definition at line 1320 of file main.c.
Referenced by init().
init()
static void init (int argc, char * argv[]) static
Initialize Fortran frontend at the beginning of compilation.
Definition at line 597 of file main.c.
References add_action(), FLG::asmcode, ASMFILE, assemble_init(), assert, basenam(), BZERO, FLG::cmdline, CNULL, FLG::code, create_action_map(), create_arg_parser(), FLG::dbg, dbg_file, dbg_file_name, dcommons(), FLG::debug, FLG::def, FLG::defaulthpf, FLG::defaultsequence, destroy_action_map(), destroy_arg_parser(), direct_init(), dmp_dtype(), do_set_tp(), dodebug, FLG::doprelink, dump_all_symbols(), dump_ast(), dump_current_symbols(), dump_old_symbols(), dump_sstds(), dump_stdps(), dump_stds(), dump_stg_stats(), dump_symbols(), dumpasts(), dumpdts(), dumplists(), dumpshapes(), dumpstdtrees(), dwarf_set_fn(), errfatal(), errini(), error(), FLG::es, FLG::extend_source, FALSE, fd, FILE, finish(), flg, fpp(), fpp_, FLG::freeform, gbl, FLG::genilm, getitem(), FLG::hpf, i, FLG::idir, FLG::ieee, FLG::inform, interf_init(), FLG::ipa, ipa_import_mode, FLG::list, list_init(), FLG::list_macros, list_page(), LISTFILE, localtime(), LV_Inform, mach, malloc(), mkDwfInfoFilename(), mkfname(), mod_combined_index(), mod_combined_name(), moddir_list::module_directory, module_directory_list, NEW, moddir_list::next, NULL, FLG::omptarget, FLG::opt, outfile_name, FLG::output, OUTPUT_DWARF, FLG::p, parse_arguments(), phase_dump_map, preproc, FLG::qp, FLG::quad, FLG::recursive, register_action_map_arg(), register_boolean_arg(), register_combined_bool_string_arg(), register_filename_arg(), register_inform_level_arg(), register_integer_arg(), register_qflag_arg(), register_string_arg(), register_string_list_arg(), register_xflag_arg(), register_yflag_arg(), report_area(), s, FLG::save, scan_init(), sem, FLG::sequence, set_mach(), set_xflag(), set_yflag(), FLG::smp, FLG::standard, FLG::stdinc, strlen(), sym_init(), FLG::terse, time(), tmpfile(), FLG::tpvalue, TRUE, FLG::undef, FLG::vect, version, was_value_set(), FLG::x, XBIT, and FLG::xref.
Referenced by add_iolptrs(), convert_ctmp_array_to_param(), fixup_param_vars(), main(), read_symbol(), and semantio().
ipa()
void ipa (void)
Definition at line 1512 of file main.c.
Referenced by get_component_init(), getict(), getivl(), and put_data_statement().
ipa_closefile()
void ipa_closefile (void)
Definition at line 1490 of file main.c.
Referenced by finish().
ipa_export()
void ipa_export (void)
Definition at line 1491 of file main.c.
ipa_export_close()
void ipa_export_close (void)
Definition at line 1492 of file main.c.
Referenced by finish().
ipa_export_endcontained()
void ipa_export_endcontained (void)
Definition at line 1493 of file main.c.
Referenced by end_contained().
ipa_export_endmodule()
void ipa_export_endmodule (void)
Definition at line 1494 of file main.c.
ipa_export_highpoint()
void ipa_export_highpoint (void)
Definition at line 1495 of file main.c.
ipa_export_open()
void ipa_export_open (char * export_filename)
Definition at line 1496 of file main.c.
ipa_fini()
void ipa_fini (void)
Definition at line 1510 of file main.c.
Referenced by finish().
ipa_header1()
void ipa_header1 (int currfunc)
Definition at line 1497 of file main.c.
ipa_header2()
void ipa_header2 (int currfunc)
Definition at line 1498 of file main.c.
ipa_import()
void ipa_import (void)
Definition at line 1501 of file main.c.
ipa_import_highpoint()
void ipa_import_highpoint (void)
Definition at line 1499 of file main.c.
ipa_import_open()
void ipa_import_open (char * import_file, BIGUINT offset)
Definition at line 1500 of file main.c.
ipa_init()
void ipa_init (void)
Definition at line 1502 of file main.c.
Referenced by main().
IPA_isnoconflict()
int IPA_isnoconflict (int sptr)
Definition at line 1514 of file main.c.
Referenced by lower_set_symbols().
ipa_report()
void ipa_report (void)
Definition at line 1503 of file main.c.
ipa_set_vestigial_host()
void ipa_set_vestigial_host (void)
Definition at line 1513 of file main.c.
ipa_startfunc()
void ipa_startfunc (int currfunc)
Definition at line 1509 of file main.c.
ipasave()
void ipasave (void)
Definition at line 1508 of file main.c.
ipasave_closefile()
void ipasave_closefile (void)
Definition at line 1504 of file main.c.
Referenced by finish().
ipasave_compname()
void ipasave_compname (char * name, int argc, char * argv[])
Definition at line 1505 of file main.c.
ipasave_endfunc()
void ipasave_endfunc (void)
Definition at line 1506 of file main.c.
ipasave_fini()
void ipasave_fini (void)
Definition at line 1507 of file main.c.
Referenced by finish().
main()
int main (int argc, char * argv[])
Fortran front-end main entry.
...
Parameters
argc number of command-line arguments \pram argv array of command-line argument strings
Definition at line 123 of file main.c.
References debugfunconly, dodebug, flg, gbl, get_rutime(), init(), IPA_COLLECTION_ENABLED, IPA_INHERIT_ENABLED, ipa_init(), NULL, FLG::opt, FLG::recursive, saveoptflag, saverecursive, savevectflag, savex8flag, FLG::vect, and FLG::x.
mkDwfInfoFilename()
static void mkDwfInfoFilename (void) static
This function creates a dwarf debug info filename from source file.
Definition at line 1458 of file main.c.
References dbg_file_name, i, mkfname(), outfile_name, and strlen().
Referenced by init().
reinit()
void reinit (void)
perform initializations for new user subprogram unit.
Perform initializations for new user subprogram unit:
Definition at line 1278 of file main.c.
References datastructure_reinit(), dinit_init(), dpm_out_init(), errini(), flg, gbl, ipa_export_file, ipa_import_mode, IS_PARFILE, NOSYM, FLG::opt, queue_tbp(), FLG::recursive, RU_PROG, saveoptflag, saverecursive, savevectflag, savex8flag, scan_opt_restore(), semant_init(), SPTR_NULL, sym_init(), TBP_CLEAR_STALE_RECORDS, FLG::vect, FLG::x, FLG::xref, and xrefinit().
Referenced by parser().
report_area()
static void report_area (void) static
Dump memory area.
Definition at line 578 of file main.c.
References reportarea().
Referenced by init().
reptime()
static void reptime (void) static
Definition at line 1176 of file main.c.
References _N_WHO, buf, FLG::code, DBGBIT, flg, gbl, i, FLG::list, list_line(), tmp, who, XBIT, FLG::xref, and xtimes.
Referenced by finish().
scan_for_dwarf_module()
void scan_for_dwarf_module (void)
Definition at line 1440 of file main.c.
Referenced by lower_symbols().
set_exitcode()
void set_exitcode (int ec)
set exit code for compiler (see finish() function)
Parameters
ec - the exit code to set
Definition at line 1312 of file main.c.
References exitcode.
Referenced by apply_use(), and open_module().
setrefsymbol()
void setrefsymbol (int symbol)
Definition at line 1439 of file main.c.
Referenced by plower().
Variable Documentation
current_phase
const char* current_phase static
Definition at line 583 of file main.c.
Referenced by do_debug(), and dump_stg_stats().
dbg_file
FILE* dbg_file = NULL
Definition at line 1436 of file main.c.
Referenced by init().
dbg_file_name
char* dbg_file_name = NULL
Definition at line 1437 of file main.c.
Referenced by init(), and mkDwfInfoFilename().
debugfunconly
int debugfunconly = -1 static
Definition at line 70 of file main.c.
Referenced by do_debug(), and main().
dodebug
int dodebug = 0 static
Definition at line 100 of file main.c.
Referenced by do_debug(), init(), and main().
exitcode
int exitcode static
Definition at line 1306 of file main.c.
Referenced by finish(), and set_exitcode().
feature
const char* feature = "flang" static
Definition at line 92 of file main.c.
Referenced by do_debug(), InitializeDIFlags(), and ll_feature_dwarf_version().
fpp_
LOGICAL fpp_ = FALSE
Definition at line 516 of file main.c.
Referenced by ff_read_card(), init(), and read_card().
has_accel_code
LOGICAL has_accel_code = FALSE static
Definition at line 67 of file main.c.
ipa_export_file
char* ipa_export_file = NULL static
Definition at line 73 of file main.c.
Referenced by end_contained(), finish(), and reinit().
ipa_import_mode
LOGICAL ipa_import_mode = FALSE static
Definition at line 72 of file main.c.
Referenced by end_contained(), finish(), init(), and reinit().
ipa_import_offset
BIGUINT ipa_import_offset = 0 static
Definition at line 74 of file main.c.
IPA_Vestigial
int IPA_Vestigial = 0
Definition at line 1488 of file main.c.
module_directory_list
moddir_list* module_directory_list = NULL
Definition at line 1143 of file main.c.
Referenced by export_all(), get_module_file_name(), and init().
objectfile
char* objectfile = NULL static
Definition at line 514 of file main.c.
Referenced by finish().
outfile_name
const char* outfile_name = NULL static
Definition at line 515 of file main.c.
Referenced by init(), and mkDwfInfoFilename().
phase_dump_map
action_map_t* phase_dump_map static
Definition at line 68 of file main.c.
Referenced by do_debug(), finish(), and init().
postprocessing
LOGICAL postprocessing = TRUE static
Definition at line 80 of file main.c.
Referenced by cleanup().
preproc
int preproc = -1 static
Definition at line 517 of file main.c.
Referenced by init().
saveoptflag
int saveoptflag static
Definition at line 63 of file main.c.
Referenced by datastructure_reinit(), and main().
saverecursive
int saverecursive static
Definition at line 66 of file main.c.
Referenced by datastructure_reinit(), and main().
savevectflag
int savevectflag static
Definition at line 64 of file main.c.
Referenced by datastructure_reinit(), and main().
savex8flag
int savex8flag static
Definition at line 65 of file main.c.
Referenced by datastructure_reinit(), and main().
who
const char* who[] static
Initial value:
= {"init",      "parser",   "bblock",
                            "vectorize", "optimize", "schedule",
                            "assemble",  "xref",     "unroll"}
Definition at line 75 of file main.c.
Referenced by reptime().
xtimes
INT xtimes[_N_WHO] static
Definition at line 79 of file main.c.
Referenced by reptime().