flang: main.cpp File Reference
main.cpp File Reference
Fortran backend main program and initialization routines.
#include "main.h"
#include "dinit.h"
#include "dinitutl.h"
#include "global.h"
#include "version.h"
#include "machar.h"
#include "upper.h"
#include "fih.h"
#include "ccffinfo.h"
#include "cgraph.h"
#include "mach.h"
#include "dbg_out.h"
#include "xref.h"
#include "exp_rte.h"
#include "rmsmove.h"
#include "mwd.h"
#include "llassem.h"
#include "cgllvm.h"
#include "outliner.h"
#include <unistd.h>
#include <time.h>
#include "ilm.h"
#include "ili.h"
#include "semant.h"
#include "dwarf2.h"
#include "fdirect.h"
#include "expand.h"
#include "scope.h"
#include <stdbool.h>
#include "flang/ArgParser/arg_parser.h"
#include "dtypeutl.h"
#include "miscutil.h"
#include "bih.h"
#include "ilt.h"
Macros
#define IS_COFF (flg.astype == 1)
#define IS_ELF (flg.astype == 0)
#define IS_STABS (XBIT(120, 0x20))
#define IS_DWARF (IS_ELF || XBIT(120, 0x80) || XBIT(120, 0x200))
#define IS_COFFDBG (IS_COFF && !XBIT(120, 0x80) && !XBIT(120, 0x200))
#define STB_UPPER() (gbl.stbfil != NULL)
#define IS_PARFILE (gbl.ilmfil == par_file1 || gbl.ilmfil == par_file2)
#define _N_WHO (int)(sizeof(who) / sizeof(char *))
#define TR(str)
#define DEBUGQQ 0
#define DUMP(a)
#define NO_FLEXLM
Functions
static bool process_input (char *argv0, bool *need_cuda_constructor)
Process one input file.
static void reptime (void)
static void init (int argc, char *argv[])
Initialize Fortran backend at the begining of compilation.
static void reinit (void)
Perform initializations for new user subprogram unit:
static void process_stb_file (void)
static void check_lineno (const char *phase)
Check line number, findex after each various stages to make sure they don't contain 0 as a line number, so that ccff_info don't get linenumber as 0.
int main (int argc, char *argv[])
Fortran backend main entry.
static void dump_symbols (void)
Dump symbols.
static void report_area (void)
void finish ()
Write summary line to terminal, and exit compiler.
void add_llvm_uplevel_symbol (int sptr)
FIXME Comments say this belongs in upper.c.
void fixup_llvm_uplevel_symbol ()
FIXME Comments say this belongs in upper.c.
Variables
static int saveoptflag
static int savevectflag
static int savex8flag
static int saverecursive
static char * objectfile = NULL
static action_map_t * phase_dump_map
static const char * who []
static INT xtimes [_N_WHO]
static char * ccff_filename = NULL
static int dodebug = 0
Detailed Description
Fortran backend main program and initialization routines.
Definition in file main.cpp.
Macro Definition Documentation
_N_WHO
#define _N_WHO (int)(sizeof(who) / sizeof(char *))
Definition at line 93 of file main.cpp.
DEBUGQQ
#define DEBUGQQ 0
Definition at line 112 of file main.cpp.
DUMP
#define DUMP (a)
Definition at line 115 of file main.cpp.
IS_COFF
#define IS_COFF (flg.astype == 1)
Definition at line 60 of file main.cpp.
IS_COFFDBG
#define IS_COFFDBG (IS_COFF && !XBIT(120, 0x80) && !XBIT(120, 0x200))
Definition at line 64 of file main.cpp.
IS_DWARF
#define IS_DWARF (IS_ELF || XBIT(120, 0x80) || XBIT(120, 0x200))
Definition at line 63 of file main.cpp.
IS_ELF
#define IS_ELF (flg.astype == 0)
Definition at line 61 of file main.cpp.
IS_PARFILE
#define IS_PARFILE (gbl.ilmfil == par_file1 || gbl.ilmfil == par_file2)
Definition at line 84 of file main.cpp.
IS_STABS
#define IS_STABS (XBIT(120, 0x20))
Definition at line 62 of file main.cpp.
NO_FLEXLM
#define NO_FLEXLM
Definition at line 117 of file main.cpp.
STB_UPPER
#define STB_UPPER () (gbl.stbfil != NULL)
Definition at line 83 of file main.cpp.
TR
#define TR (str)
Value:
  if (dodebug) {              \
    fprintf(gbl.dbgfil, str); \
    fflush(gbl.dbgfil);       \
  }
Definition at line 100 of file main.cpp.
Function Documentation
add_llvm_uplevel_symbol()
void add_llvm_uplevel_symbol (int sptr)
FIXME Comments say this belongs in upper.c.
Definition at line 1039 of file main.cpp.
References _add_llvm_uplevel_symbol(), and sptr.
Referenced by read_symbol().
check_lineno()
static void check_lineno (const char * phase) static
Check line number, findex after each various stages to make sure they don't contain 0 as a line number, so that ccff_info don't get linenumber as 0.
Definition at line 127 of file main.cpp.
References BIH_FINDEX, BIH_ILTFIRST, BIH_LINENO, BIH_NEXT, DBGBIT, FLG::debug, first, flg, ilt, ILT_FINDEX, ILT_LINENO, ILT_NEXT, and XBIT.
Referenced by process_input().
dump_symbols()
static void dump_symbols (void) static
Dump symbols.
Wrapper that takes no arguments
Definition at line 511 of file main.cpp.
References dsyms().
Referenced by init().
finish()
void finish (void)
Write summary line to terminal, and exit compiler.
...
\Brief Write summary line to terminal, and exit.
Definition at line 925 of file main.cpp.
References assemble_end(), ast_fini(), c, called, ccff_close(), ccff_filename, DBGBIT, destroy_action_map(), direct_fini(), DUMP, errfatal(), FLG::es, exitcode, FALSE, fclose(), fih_fini(), FILE, fini(), flg, fp, free_getitem_p(), freearea(), FTN_HAS_INIT, gbl, import_module_print(), ipa_closefile(), IPA_COLLECTION_ENABLED, IPA_ENABLED, ipa_export_close(), ipa_export_file, ipa_fini(), ipa_import_mode, IPA_INHERIT_ENABLED, ipasave_closefile(), ipasave_fini(), ll_unlink_parfiles(), maxfilsev, mkfname(), mod_fini(), NULL, FLG::object, objectfile, OBJFILE, FLG::opt, phase_dump_map, reptime(), scan_fini(), sem_fini(), FLG::smp, summary(), symtab_fini(), TRUE, and XBIT.
Referenced by accpp(), display_error(), ff_get_stmt(), fpp(), get_stmt(), init(), and main().
fixup_llvm_uplevel_symbol()
void fixup_llvm_uplevel_symbol (void)
FIXME Comments say this belongs in upper.c.
Definition at line 1047 of file main.cpp.
References _fixup_llvm_uplevel_symbol().
Referenced by upper().
init()
static void init (int argc, char * argv[]) static
Initialize Fortran backend at the begining of compilation.
Definition at line 529 of file main.cpp.
References add_action(), FLG::asmcode, ASMFILE, assemble_init(), assert, FLG::astype, basenam(), ccff_build(), ccff_filename, ccff_open(), FLG::cmdline, FLG::code, create_action_map(), create_arg_parser(), FLG::dbg, dbih(), dbihonly(), FLG::debug, destroy_action_map(), destroy_arg_parser(), dflg(), dgbl(), direct_init(), dodebug, dump_symbols(), dumpdiff(), dumpdtypes(), dumpdvls(), dumpilts(), dumpnmes(), FLG::endian, ERR_Fatal, ERR_unused, errfatal(), errini(), error(), FLG::es, fd, FILE, finish(), flg, FTNFILE, gbl, getitem(), FLG::ieee, FLG::inform, FLG::linker_directives, FLG::list, list_init(), LISTFILE, ll_open_parfiles(), FLG::llvm_target_triple, localtime(), LV_Inform, malloc(), mkfname(), NULL, FLG::object, ompaccel_set_targetriple(), FLG::omptarget, FLG::opt, parse_arguments(), phase_dump_map, printblocks(), FLG::qp, FLG::quad, FLG::recursive, register_action_map_arg(), register_boolean_arg(), register_combined_bool_string_arg(), register_filename_arg(), register_inform_level_arg(), register_integer_arg(), register_qflag_arg(), register_string_arg(), register_string_list_arg(), register_xflag_arg(), register_yflag_arg(), report_area(), s, FLG::save, set_tp(), set_yflag(), FLG::smp, ss, stackcheck(), stackvars(), strlen(), sym_init(), t, FLG::target_features, FLG::terse, time(), tmpfile(), FLG::vect, version, FLG::vscale_range_max, FLG::vscale_range_min, was_value_set(), FLG::x, XBIT, and FLG::xref.
Referenced by main().
main()
int main (int argc, char * argv[])
Fortran backend main entry.
...
Definition at line 372 of file main.cpp.
References addfile(), cg_llvm_end(), DBGBIT, errwarn(), finish(), flg, FTN_HAS_INIT, gbl, get_rutime(), init(), init_global_ilm_mode(), init_test(), ll_unlink_parfiles(), NULL, ompaccel_init(), FLG::omptarget, FLG::opt, process_input(), process_stb_file(), FLG::recursive, saveoptflag, saverecursive, savevectflag, savex8flag, FLG::smp, STB_UPPER, stb_upper_init(), upper_init(), FLG::vect, FLG::x, and XBIT.
process_input()
static bool process_input (char * argv0, bool * need_cuda_constructor) static
Process one input file.
Parameters
argv0 path to initalize accelerator compilation
need_cuda_constructor indicates that need to add a CUDA construction, this parameter is also written to
Returns
false to indicated end of processing, true otherwise
Definition at line 168 of file main.cpp.
References ALLOW_NODEPCHK_SIMD, assemble(), AssignAddresses(), ccff_close_unit(), cg_llvm_fnend(), check_lineno(), FLG::code, cuda_emu_end(), cuda_emu_start(), DBGBIT, FLG::debug, direct_rou_end(), direct_rou_load(), dmp_dtype(), DUMP, dumpomptargets(), ERR_Fatal, expand(), flg, gbl, get_rutime(), init_test(), FLG::inliner, interr(), IS_PARFILE, ll_has_more_outlined(), ll_reset_parfile(), ll_set_outlined_currsub(), llProcessNextTmpfile(), FLG::object, ompaccel_initsyms(), ompaccel_tinfo_has(), FLG::omptarget, FLG::opt, process_global_lifetime_debug(), rdgilms(), reinit(), remove_scope_labels(), rm_smove(), RU_BDATA, schedule(), FLG::smp, summary(), symdmp(), TR, unsplit(), upper(), upper_assign_addresses(), upper_save_syminfo(), void(), XBIT, XBIT_USE_SCOPE_LABELS, FLG::xref, xref(), and xtimes.
Referenced by main().
process_stb_file()
static void process_stb_file (void) static
Definition at line 977 of file main.cpp.
References add_aguplevel_oldsptr(), cg_llvm_fnend(), cg_llvm_init(), errwarn(), fclose(), fix_llvm_fptriface(), gbl, NULL, reinit(), stb_process_routine_parameters(), STB_UPPER, TR, upper(), upper_assign_addresses(), and upper_save_syminfo().
Referenced by main().
reinit()
static void reinit (void) static
Perform initializations for new user subprogram unit:
Definition at line 872 of file main.cpp.
Referenced by process_input(), and process_stb_file().
report_area()
static void report_area (void) static
Dump memory area
Wrapper that takes not arguments
Definition at line 521 of file main.cpp.
References reportarea().
Referenced by init().
reptime()
static void reptime (void) static
Definition at line 449 of file main.cpp.
References _N_WHO, buf, FLG::code, DBGBIT, flg, gbl, i, FLG::list, list_line(), tmp, who, XBIT, FLG::xref, and xtimes.
Referenced by finish().
Variable Documentation
ccff_filename
char* ccff_filename = NULL static
Definition at line 95 of file main.cpp.
Referenced by ccff_open(), finish(), and init().
dodebug
int dodebug = 0 static
Definition at line 99 of file main.cpp.
Referenced by init().
objectfile
char* objectfile = NULL static
Definition at line 81 of file main.cpp.
Referenced by finish().
phase_dump_map
action_map_t* phase_dump_map static
Definition at line 86 of file main.cpp.
Referenced by finish(), and init().
saveoptflag
int saveoptflag static
Definition at line 77 of file main.cpp.
Referenced by main(), and reinit().
saverecursive
int saverecursive static
Definition at line 80 of file main.cpp.
Referenced by main(), and reinit().
savevectflag
int savevectflag static
Definition at line 78 of file main.cpp.
Referenced by main(), and reinit().
savex8flag
int savex8flag static
Definition at line 79 of file main.cpp.
Referenced by main(), and reinit().
who
const char* who[] static
Initial value:
= {"init", "import",   "expand", "", "",
                            "",     "assemble", "xref",   ""}
Definition at line 91 of file main.cpp.
Referenced by reptime().
xtimes
INT xtimes[_N_WHO] static
Definition at line 94 of file main.cpp.
Referenced by process_input(), and reptime().