flang: mall.c File Reference
mall.c File Reference
customized storage allocation routines for compiler.
#include "mall.h"
#include "global.h"
#include "error.h"
Macros
#define TRACE(a, b)
#define TOO_LARGE F_0007_Subprogram_too_large_to_compile_at_this_optimization_level_OP1
Functions
char * sccalloc (BIGUINT64 nbytes)
...
void sccfree (char *ap)
...
char * sccrelal (char *pp, BIGUINT64 nbytes)
...
Detailed Description
customized storage allocation routines for compiler.
Definition in file mall.c.
Macro Definition Documentation
TOO_LARGE
#define TOO_LARGE F_0007_Subprogram_too_large_to_compile_at_this_optimization_level_OP1
Definition at line 31 of file mall.c.
TRACE
#define TRACE (a, b)
Definition at line 28 of file mall.c.
Function Documentation
sccalloc()
char * sccalloc (BIGUINT64 nbytes)
...
Definition at line 35 of file mall.c.
References DBGBIT, errfatal(), malloc(), NULL, p, q, s, TOO_LARGE, and TRACE.
Referenced by addmodfile(), fpp(), import_module_print(), rb_new(), scan_init(), and stg_alloc_base().
sccfree()
void sccfree (char * ap)
...
Definition at line 62 of file mall.c.
References TRACE.
Referenced by rb_free(), and stg_delete().
sccrelal()
char * sccrelal (char * pp, BIGUINT64 nbytes)
...
Definition at line 71 of file mall.c.
References errfatal(), NULL, pp, q, TOO_LARGE, and TRACE.
Referenced by _parser(), _rd_tkline(), read_line(), realloc_stmtb(), stg_need(), and subst().