flang: malloc.c File Reference
malloc.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include <memory.h>
#include "fort_vars.h"
Macros
#define ZIP ((char *)15L)
Functions
void * shmalloc (size_t)
void * __fort_malloc_without_abort (size_t n)
void * __fort_malloc (size_t n)
void * __fort_realloc (void *ptr, size_t n)
void * __fort_calloc_without_abort (size_t n)
void * __fort_calloc (size_t n, size_t s)
void __fort_free (void *ptr)
void * __fort_gmalloc_without_abort (size_t n)
void * __fort_gmalloc (size_t n)
void * __fort_grealloc (void *ptr, size_t n)
void * __fort_gcalloc_without_abort (size_t n)
void * __fort_gcalloc (size_t n, size_t s)
void __fort_gfree (void *ptr)
Macro Definition Documentation
ZIP
#define ZIP ((char *)15L)
Definition at line 19 of file malloc.c.
Function Documentation
__fort_calloc()
void * __fort_calloc (size_t n, size_t s)
Definition at line 89 of file malloc.c.
References __fort_abort(), n, p, s, and ZIP.
Referenced by __fort_allchn(), __fort_copy(), and __fort_gcalloc().
__fort_calloc_without_abort()
void * __fort_calloc_without_abort (size_t n)
Definition at line 76 of file malloc.c.
References malloc(), n, NULL, p, and ZIP.
Referenced by __fort_gcalloc_without_abort(), ENTF90(), and void().
__fort_free()
void __fort_free (void * ptr)
Definition at line 105 of file malloc.c.
References ZIP.
Referenced by __f90_allo_term(), __fort_chn_1to1(), __fort_chn_1toN(), __fort_comm_merge(), __fort_copy(), __fort_frechn(), __fort_gen_block_bounds(), __fort_getmap(), __fort_gfree(), __fort_initopt(), __fort_local_deallocate(), __fort_map(), __INT_T(), comm_sked_free(), copy_loop(), ENTF90(), ENTF90IO(), ENTFTN(), ftn_dealloc(), ftn_deallocate(), gathscat_free(), if(), merge_ent(), olap_free(), olap_recv(), olap_send(), olap_shift(), and use_alloc().
__fort_gcalloc()
void * __fort_gcalloc (size_t n, size_t s)
Definition at line 141 of file malloc.c.
References __fort_calloc(), n, and s.
__fort_gcalloc_without_abort()
void * __fort_gcalloc_without_abort (size_t n)
Definition at line 135 of file malloc.c.
References __fort_calloc_without_abort(), and n.
Referenced by ENTF90(), and void().
__fort_gfree()
void __fort_gfree (void * ptr)
Definition at line 147 of file malloc.c.
References __fort_free().
Referenced by __fort_deallocate(), __fort_getgbuf(), __fort_global_reduce(), __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), __fort_reduce_section(), __fort_stat_term(), ENTF90(), ENTFTN(), ftn_dealloc(), ftn_deallocate(), gathscat_free(), gathscat_start(), kmaxloc_common(), kmaxlocs_common(), kminloc_common(), kminlocs_common(), maxloc_common(), maxlocs_common(), minloc_common(), minlocs_common(), and void().
__fort_gmalloc()
void * __fort_gmalloc (size_t n)
Definition at line 123 of file malloc.c.
References __fort_malloc(), and n.
Referenced by __chk_str_val(), __fort_adjust_index_array(), __fort_create_conforming_index_array(), __fort_create_conforming_mask_array(), __fort_exchange_counts(), __fort_getgbuf(), __fort_global_reduce(), __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), __fort_reduce_section(), __fort_stat_term(), __fort_zopen(), ENTFTN(), gathscat_start(), kmaxlocs_common(), kminlocs_common(), maxlocs_common(), and minlocs_common().
__fort_gmalloc_without_abort()
void * __fort_gmalloc_without_abort (size_t n)
Definition at line 117 of file malloc.c.
References __fort_malloc_without_abort(), and n.
Referenced by __fort_allocate(), __fort_kallocate(), ENTF90(), ftn_alloc(), and ftn_allocate().
__fort_grealloc()
void * __fort_grealloc (void * ptr, size_t n)
Definition at line 129 of file malloc.c.
References __fort_realloc(), and n.
__fort_malloc()
void * __fort_malloc (size_t n)
Definition at line 37 of file malloc.c.
References __fort_abort(), __fort_malloc_without_abort(), n, and p.
Referenced by __fort_chn_1toN(), __fort_comm_sked(), __fort_defaultproc(), __fort_entry_init(), __fort_genlist(), __fort_getmap(), __fort_gmalloc(), __fort_initopt(), __fort_localproc(), __fort_map(), __fort_passarg(), __fort_passargs(), __fort_recvl(), __fort_sendl(), __INT_T(), ENTF90IO(), ENTFTN(), and if().
__fort_malloc_without_abort()
void * __fort_malloc_without_abort (size_t n)
Definition at line 24 of file malloc.c.
References __fort_zmem, malloc(), n, NULL, p, and ZIP.
Referenced by __fort_gmalloc_without_abort(), __fort_local_allocate(), __fort_local_kallocate(), __fort_malloc(), ENTF90(), ftn_alloc(), ftn_allocate(), and void().
__fort_realloc()
void * __fort_realloc (void * ptr, size_t n)
Definition at line 50 of file malloc.c.
References __fort_abort(), __fort_zmem, malloc(), n, NULL, p, and ZIP.
Referenced by __fort_grealloc(), __fort_recvl(), __fort_sendl(), ENTFTN(), and merge_ent().
shmalloc()
void * shmalloc (size_t)