flang: map.c File Reference
map.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include <string.h>
#include <memory.h>
#include <sys/time.h>
Functions
static int compar_tids (const void *a, const void *b)
static void __fort_check_map (int *processormap)
static void __fort_getmap (int *processormap)
void __fort_map ()
void __fort_getarg ()
Function Documentation
__fort_check_map()
static void __fort_check_map (int * processormap) static
Definition at line 27 of file map.c.
References __abort(), __io_stderr(), GET_DIST_TCPUS, i, j, and NULL.
Referenced by __fort_getmap().
__fort_getarg()
void __fort_getarg ()
Definition at line 165 of file map.c.
References __fort_abort().
__fort_getmap()
static void __fort_getmap (int * processormap) static
Definition at line 56 of file map.c.
References __abort(), __fort_check_map(), __fort_free(), __fort_getopt(), __fort_malloc(), __io_stderr(), GET_DIST_TCPUS, j, k, m, n, and NULL.
Referenced by __fort_map().
__fort_map()
void __fort_map ()
Definition at line 138 of file map.c.
References __fort_bcopy(), __fort_free(), __fort_getmap(), __fort_malloc(), compar_tids(), GET_DIST_TCPUS, GET_DIST_TIDS, i, and SET_DIST_TIDS_ELEM.
compar_tids()
static int compar_tids (const void * a, const void * b) static
Definition at line 19 of file map.c.
References a, and b.
Referenced by __fort_map().