flang: math_common.h File Reference
math_common.h File Reference
#include <math.h>
#include <complex.h>
#include "debug_prn.h"
#include <assert.h>
Macros
#define INLINE __attribute__((always_inline)) inline
#define GLUE(a, b) a ## b
#define JOIN(a, b) GLUE(a,b)
#define JOIN3(a, b, c) JOIN(JOIN(a,b),c)
#define JOIN4(a, b, c, d) JOIN(JOIN3(a,b,c),d)
#define FL_ABS_MASK 0x7fffffff
#define FL_EXP_MASK 0x7f800000
#define FL_PINF FL_EXP_MASK
#define FL_NINF 0xff800000
#define FL_EXP_BIAS 127
#define FL_EXP_MIN -149
#define FL_EXP_MAX FL_EXP_BIAS
#define FL_SIGN_BIT 0x80000000
#define FL_PREC_BITS 24
#define FL_ONE 0x3f800000
#define FL_MONE 0xbf800000
#define FL_PZERO 0x0
#define FL_NZERO FL_SIGN_BIT
#define DB_ABS_MASK 0x7fffffffffffffffULL
#define DB_EXP_MASK 0x7ff0000000000000ULL
#define DB_PINF DB_EXP_MASK
#define DB_NINF 0xfff0000000000000ULL
#define DB_EXP_BIAS 1023
#define DB_EXP_MIN -1074
#define DB_EXP_MAX DB_EXP_BIAS
#define DB_SIGN_BIT 0x8000000000000000ULL
#define DB_PREC_BITS 53
#define DB_ONE 0x3ff0000000000000ULL
#define DB_MONE 0xBff0000000000000ULL
#define DB_PZERO 0x0ULL
#define DB_NZERO DB_SIGN_BIT
#define fmaf my_fmaf
#define isinff(x) my_isinff(x)
#define copysignf(x, y) my_copysignf(x, y)
#define copysign(x, y) my_copysign(x, y)
#define isnanf(x) my_isnanf(x)
#define creal my_creal
#define cimag my_cimag
#define crealf my_crealf
#define cimagf my_cimagf
Functions
static INLINE float _Complex set_cmplx (float x, float y)
static INLINE double _Complex set_cmplxd (double x, double y)
static INLINE double set_dcmplx (float x, float y)
static INLINE float my_fmaf (float a, float b, float c)
static INLINE unsigned F2I (float x)
static INLINE float I2F (unsigned x)
static INLINE unsigned long long int D2L (double x)
static INLINE double L2D (unsigned long long int x)
static INLINE unsigned long long int II2L (unsigned hi, unsigned lo)
static INLINE int my_isinff (float x)
static INLINE float my_copysignf (float x, float y)
static INLINE double my_copysign (double x, double y)
static INLINE int my_isnanf (float x)
static INLINE void fast2mul (float x, float y, float *r1, float *r2)
static INLINE void fast2sum (float x, float y, float *r1, float *r2)
static INLINE void fast2mul_dp (double x, double y, double *r1, double *r2)
static INLINE void fast2sum_dp (double x, double y, double *r1, double *r2)
static INLINE double my_creal (double _Complex x)
static INLINE double my_cimag (double _Complex x)
static INLINE float my_crealf (float _Complex x)
static INLINE float my_cimagf (float _Complex x)
Macro Definition Documentation
cimag
#define cimag my_cimag
Definition at line 258 of file math_common.h.
cimagf
#define cimagf my_cimagf
Definition at line 274 of file math_common.h.
copysign
#define copysign (x, y) my_copysign(x, y)
Definition at line 189 of file math_common.h.
copysignf
#define copysignf (x, y) my_copysignf(x, y)
Definition at line 181 of file math_common.h.
creal
#define creal my_creal
Definition at line 250 of file math_common.h.
crealf
#define crealf my_crealf
Definition at line 266 of file math_common.h.
DB_ABS_MASK
#define DB_ABS_MASK 0x7fffffffffffffffULL
Definition at line 41 of file math_common.h.
DB_EXP_BIAS
#define DB_EXP_BIAS 1023
Definition at line 45 of file math_common.h.
DB_EXP_MASK
#define DB_EXP_MASK 0x7ff0000000000000ULL
Definition at line 42 of file math_common.h.
DB_EXP_MAX
#define DB_EXP_MAX DB_EXP_BIAS
Definition at line 47 of file math_common.h.
DB_EXP_MIN
#define DB_EXP_MIN -1074
Definition at line 46 of file math_common.h.
DB_MONE
#define DB_MONE 0xBff0000000000000ULL
Definition at line 51 of file math_common.h.
DB_NINF
#define DB_NINF 0xfff0000000000000ULL
Definition at line 44 of file math_common.h.
DB_NZERO
#define DB_NZERO DB_SIGN_BIT
Definition at line 53 of file math_common.h.
DB_ONE
#define DB_ONE 0x3ff0000000000000ULL
Definition at line 50 of file math_common.h.
DB_PINF
#define DB_PINF DB_EXP_MASK
Definition at line 43 of file math_common.h.
DB_PREC_BITS
#define DB_PREC_BITS 53
Definition at line 49 of file math_common.h.
DB_PZERO
#define DB_PZERO 0x0ULL
Definition at line 52 of file math_common.h.
DB_SIGN_BIT
#define DB_SIGN_BIT 0x8000000000000000ULL
Definition at line 48 of file math_common.h.
FL_ABS_MASK
#define FL_ABS_MASK 0x7fffffff
Definition at line 27 of file math_common.h.
FL_EXP_BIAS
#define FL_EXP_BIAS 127
Definition at line 31 of file math_common.h.
FL_EXP_MASK
#define FL_EXP_MASK 0x7f800000
Definition at line 28 of file math_common.h.
FL_EXP_MAX
#define FL_EXP_MAX FL_EXP_BIAS
Definition at line 33 of file math_common.h.
FL_EXP_MIN
#define FL_EXP_MIN -149
Definition at line 32 of file math_common.h.
FL_MONE
#define FL_MONE 0xbf800000
Definition at line 37 of file math_common.h.
FL_NINF
#define FL_NINF 0xff800000
Definition at line 30 of file math_common.h.
FL_NZERO
#define FL_NZERO FL_SIGN_BIT
Definition at line 39 of file math_common.h.
FL_ONE
#define FL_ONE 0x3f800000
Definition at line 36 of file math_common.h.
FL_PINF
#define FL_PINF FL_EXP_MASK
Definition at line 29 of file math_common.h.
FL_PREC_BITS
#define FL_PREC_BITS 24
Definition at line 35 of file math_common.h.
FL_PZERO
#define FL_PZERO 0x0
Definition at line 38 of file math_common.h.
FL_SIGN_BIT
#define FL_SIGN_BIT 0x80000000
Definition at line 34 of file math_common.h.
fmaf
#define fmaf my_fmaf
Definition at line 94 of file math_common.h.
GLUE
#define GLUE (a, b) a ## b
Definition at line 19 of file math_common.h.
INLINE
#define INLINE __attribute__((always_inline)) inline
Definition at line 16 of file math_common.h.
isinff
#define isinff (x) my_isinff(x)
Definition at line 173 of file math_common.h.
isnanf
#define isnanf (x) my_isnanf(x)
Definition at line 197 of file math_common.h.
JOIN
#define JOIN (a, b) GLUE(a,b)
Definition at line 20 of file math_common.h.
JOIN3
#define JOIN3 (a, b, c) JOIN(JOIN(a,b),c)
Definition at line 21 of file math_common.h.
JOIN4
#define JOIN4 (a, b, c, d) JOIN(JOIN3(a,b,c),d)
Definition at line 22 of file math_common.h.
Function Documentation
D2L()
static INLINE unsigned long long int D2L (double x) static
Definition at line 148 of file math_common.h.
References x.
Referenced by __attribute__(), __exp_d_scalar_kernel(), __ldexp_d_scalar_kernel(), __reduction_slowpath_pio2(), __vcis_d_kernel(), for(), and my_copysign().
F2I()
static INLINE unsigned F2I (float x) static
Definition at line 128 of file math_common.h.
References x.
Referenced by __attribute__(), __exp_scalar_kernel(), __ldexpf_scalar_kernel(), __vcis_kernel(), my_copysignf(), my_isinff(), and my_isnanf().
fast2mul()
static INLINE void fast2mul (float x, float y, float * r1, float * r2) static
Definition at line 205 of file math_common.h.
References fmaf, x, and y.
Referenced by __attribute__().
fast2mul_dp()
static INLINE void fast2mul_dp (double x, double y, double * r1, double * r2) static
Definition at line 227 of file math_common.h.
References fma(), PRINT, x, and y.
Referenced by __attribute__().
fast2sum()
static INLINE void fast2sum (float x, float y, float * r1, float * r2) static
Definition at line 215 of file math_common.h.
References hi, lo, tmp, x, and y.
Referenced by __attribute__().
fast2sum_dp()
static INLINE void fast2sum_dp (double x, double y, double * r1, double * r2) static
Definition at line 238 of file math_common.h.
References hi, lo, tmp, x, and y.
Referenced by __attribute__().
I2F()
static INLINE float I2F (unsigned x) static
Definition at line 138 of file math_common.h.
References x.
Referenced by __attribute__(), __exp_scalar_kernel(), __ldexpf_scalar_kernel(), and my_copysignf().
II2L()
static INLINE unsigned long long int II2L (unsigned hi, unsigned lo) static
Definition at line 167 of file math_common.h.
References hi, and lo.
L2D()
static INLINE double L2D (unsigned long long int x) static
Definition at line 157 of file math_common.h.
References x.
Referenced by __attribute__(), __ldexp_d_scalar_kernel(), __reduction_slowpath_pio2(), cexp_scalar_default_abi(), for(), and my_copysign().
my_cimag()
static INLINE double my_cimag (double _Complex x) static
Definition at line 260 of file math_common.h.
References x.
my_cimagf()
static INLINE float my_cimagf (float _Complex x) static
Definition at line 276 of file math_common.h.
References x.
my_copysign()
static INLINE double my_copysign (double x, double y) static
Definition at line 191 of file math_common.h.
References D2L(), DB_ABS_MASK, DB_SIGN_BIT, L2D(), x, and y.
my_copysignf()
static INLINE float my_copysignf (float x, float y) static
Definition at line 183 of file math_common.h.
References F2I(), FL_ABS_MASK, FL_SIGN_BIT, I2F(), x, and y.
my_creal()
static INLINE double my_creal (double _Complex x) static
Definition at line 252 of file math_common.h.
References x.
my_crealf()
static INLINE float my_crealf (float _Complex x) static
Definition at line 268 of file math_common.h.
References x.
my_fmaf()
static INLINE float my_fmaf (float a, float b, float c) static
Definition at line 96 of file math_common.h.
References _mm_cvtss_f32(), a, b, and c.
my_isinff()
static INLINE int my_isinff (float x) static
Definition at line 175 of file math_common.h.
References F2I(), and x.
my_isnanf()
static INLINE int my_isnanf (float x) static
Definition at line 199 of file math_common.h.
References F2I(), and x.
set_cmplx()
static INLINE float _Complex set_cmplx (float x, float y) static
Definition at line 56 of file math_common.h.
References PRINT, result, x, and y.
Referenced by __attribute__().
set_cmplxd()
static INLINE double _Complex set_cmplxd (double x, double y) static
Definition at line 70 of file math_common.h.
References PRINT, result, x, and y.
Referenced by __attribute__(), and cexp_scalar_default_abi().
set_dcmplx()
static INLINE double set_dcmplx (float x, float y) static
Definition at line 80 of file math_common.h.
References PRINT, result, x, and y.