flang: memops.h File Reference
memops.h File Reference
Various memory operations.
Functions
void __c_mcopy1 (char *dest, char *src, long cnt)
void __c_mcopy2 (short *dest, short *src, long cnt)
void __c_mcopy4 (int *dest, int *src, long cnt)
void __c_mcopy8 (long long *dest, long long *src, long cnt)
void __c_mcopy16 (float128_t *dest, float128_t *src, long cnt)
void __c_mset1 (char *dest, int value, long cnt)
void __c_mset2 (short *dest, int value, long cnt)
void __c_mset4 (int *dest, int value, long cnt)
void __c_mset8 (long long *dest, long long value, long cnt)
void __c_mset16 (float128_t *dest, float128_t value, long cnt)
void __c_mzero1 (char *dest, long cnt)
void __c_mzero2 (short *dest, long cnt)
void __c_mzero4 (int *dest, long cnt)
void __c_mzero8 (long long *dest, long cnt)
void __c_mzero16 (float128_t *dest, long cnt)
Detailed Description
Various memory operations.
Definition in file memops.h.
Function Documentation
__c_mcopy1()
void __c_mcopy1 (char * dest, char * src, long cnt)
Definition at line 12 of file mcopy1.c.
References cnt, dest, i, and src.
__c_mcopy16()
void __c_mcopy16 (float128_t * dest, float128_t * src, long cnt)
Definition at line 13 of file mcopy16.c.
References cnt, dest, i, and src.
__c_mcopy2()
void __c_mcopy2 (short * dest, short * src, long cnt)
Definition at line 12 of file mcopy2.c.
References cnt, dest, i, and src.
__c_mcopy4()
void __c_mcopy4 (int * dest, int * src, long cnt)
Definition at line 12 of file mcopy4.c.
References cnt, dest, i, and src.
Referenced by ENTF90().
__c_mcopy8()
void __c_mcopy8 (long long * dest, long long * src, long cnt)
Definition at line 12 of file mcopy8.c.
References cnt, dest, i, and src.
Referenced by ENTF90().
__c_mset1()
void __c_mset1 (char * dest, int value, long cnt)
Definition at line 12 of file mset1.c.
References cnt, dest, i, and value().
__c_mset16()
void __c_mset16 (float128_t * dest, float128_t value, long cnt)
Definition at line 13 of file mset16.c.
References cnt, dest, i, and value().
__c_mset2()
void __c_mset2 (short * dest, int value, long cnt)
Definition at line 12 of file mset2.c.
References cnt, dest, i, and value().
__c_mset4()
void __c_mset4 (int * dest, int value, long cnt)
Definition at line 12 of file mset4.c.
References cnt, dest, i, and value().
__c_mset8()
void __c_mset8 (long long * dest, long long value, long cnt)
Definition at line 12 of file mset8.c.
References cnt, dest, i, and value().
__c_mzero1()
void __c_mzero1 (char * dest, long cnt)
Definition at line 12 of file mzero1.c.
References cnt, dest, and i.
__c_mzero16()
void __c_mzero16 (float128_t * dest, long cnt)
Definition at line 12 of file mzero16.c.
References cnt, dest, and i.
__c_mzero2()
void __c_mzero2 (short * dest, long cnt)
Definition at line 12 of file mzero2.c.
References cnt, dest, and i.
__c_mzero4()
void __c_mzero4 (int * dest, long cnt)
Definition at line 12 of file mzero4.c.
References cnt, dest, and i.
Referenced by ENTF90().
__c_mzero8()
void __c_mzero8 (long long * dest, long cnt)
Definition at line 12 of file mzero8.c.
References cnt, dest, and i.
Referenced by ENTF90().