flang: mget.c File Reference
mget.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "fort_vars.h"
Macros
#define QTREE
Functions
static void mget_send (chdr **ch, int to, int me, char *rb, dtype kind, int size)
static void mget_recv (chdr **ch, int me, int from, char *rb, dtype kind, int size)
void ENTFTN (MGET_SCALAR, mget_scalar)
Variables
void(* __fort_scalar_copy [__NTYPES])(void *rp, void *sp, int size)
static int _1 = 1
Macro Definition Documentation
QTREE
#define QTREE
Definition at line 15 of file mget.c.
Function Documentation
ENTFTN()
void ENTFTN (MGET_SCALAR , mget_scalar)
Definition at line 56 of file mget.c.
References __DESC, __fort_abort(), __fort_chn_prune(), __fort_doit(), __fort_frechn(), __fort_local_address(), __fort_owner, __fort_scalar_copy, __fort_show_index(), __fort_show_scalar(), __fort_test, DEBUG_SCAL, DECL_HDR_PTRS, DIST_ALIGN_TARGET_G, DIST_MAPPED_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_LCPU, GET_DIST_TCPUS, i, I8, idx, MAXDIMS, mget_recv(), mget_send(), n, NULL, rb, and va.
mget_recv()
static void mget_recv (chdr ** ch, int me, int from, char * rb, dtype kind, int size) static
Definition at line 40 of file mget.c.
References _1, __fort_chn_1to1(), __fort_recvl(), __fort_test, DEBUG_SCAL, GET_DIST_TCPUS_ADDR, kind, NULL, rb, and size.
Referenced by ENTFTN().
mget_send()
static void mget_send (chdr ** ch, int to, int me, char * rb, dtype kind, int size) static
Definition at line 23 of file mget.c.
References _1, __fort_chn_1to1(), __fort_sendl(), __fort_test, DEBUG_SCAL, GET_DIST_TCPUS_ADDR, kind, NULL, rb, and size.
Referenced by ENTFTN().
Variable Documentation
_1
int _1 = 1 static
Definition at line 20 of file mget.c.
Referenced by mget_recv(), and mget_send().
__fort_scalar_copy
void(* __fort_scalar_copy[__NTYPES])(void *rp, void *sp, int size) (void * rp, void * sp, int size) extern
Referenced by ENTFTN().