flang: miscutil.c File Reference
miscutil.c File Reference
Compiler miscellaneous utility programs.
#include "miscutil.h"
#include "global.h"
#include "error.h"
#include "main.h"
#include <stdbool.h>
#include "flang/ArgParser/xflag.h"
Functions
char * mkfname (const char *oldname, const char *oldsuf, const char *newsuf)
Allocate space for and make new filename using mkperm.
char * literal_string (char *oldstr, int userlen, bool isStringW)
Create literal string for STATIC STRING.
bool is_xflag_bit (int indx)
...
void set_xflag (int indx, INT val)
Called only from main()
void set_yflag (int indx, INT val)
Called only from main()
void fprintf_str_esc_backslash (FILE *f, char *str)
...
static void invalid_size (const char *funcname, int dtsize, int size, const char *stgname)
static void stg_alloc_base (STG *stg, int dtsize, BIGUINT64 size, const char *name)
void stg_clear_force (STG *stg, BIGUINT64 r, BIGUINT64 n, bool force)
...
void stg_clear (STG *stg, int r, int n)
...
void stg_clear_all (STG *stg)
...
void stg_alloc (STG *stg, int dtsize, int size, const char *name)
...
void stg_delete (STG *stg)
...
void stg_reset (STG *stg)
void stg_need (STG *stg)
...
void stg_alloc_sidecar (STG *basestg, STG *stg, int dtsize, const char *name)
...
static void sidecar_not_found (const char *funcname, STG *basestg, STG *stg)
void stg_delete_sidecar (STG *basestg, STG *stg)
...
int stg_next (STG *stg, int n)
...
static void too_small_for_freelist (const char *funcname, STG *stg)
static char * freefield (STG *stg, BIGUINT64 r)
int stg_next_freelist (STG *stg)
...
void stg_return (STG *stg)
void stg_add_freelist (STG *stg, int r)
...
void stg_set_freelink (STG *stg, int offset)
...
Detailed Description
Compiler miscellaneous utility programs.
Definition in file miscutil.c.
Function Documentation
fprintf_str_esc_backslash()
void fprintf_str_esc_backslash (FILE * f, char * str)
...
Definition at line 108 of file miscutil.c.
References f, and str.
freefield()
static char * freefield (STG * stg, BIGUINT64 r) static
Definition at line 376 of file miscutil.c.
References base, and r.
Referenced by stg_add_freelist(), and stg_next_freelist().
invalid_size()
static void invalid_size (const char * funcname, int dtsize, int size, const char * stgname) static
Definition at line 124 of file miscutil.c.
References ERR_Fatal, interrf(), and size.
Referenced by stg_alloc_base().
is_xflag_bit()
bool is_xflag_bit (int indx)
...
Definition at line 85 of file miscutil.c.
References is_xflag_bitvector().
Referenced by rd_dir().
literal_string()
char * literal_string (char * oldstr, int userlen, bool isStringW)
Create literal string for STATIC STRING.
...
If isStringW is TRUE(1), oldstr is passed in as a wide string literal and a letter "L" needs to be prepended to the target string.
Definition at line 40 of file miscutil.c.
References c, end, len, MAX_FILENAME_LEN, skip, and start.
mkfname()
char * mkfname (const char * oldname, const char * oldsuf, const char * newsuf)
Allocate space for and make new filename using mkperm.
...
Definition at line 24 of file miscutil.c.
References getitem(), mkperm(), p, and strlen().
Referenced by finish(), init(), and mkDwfInfoFilename().
set_xflag()
void set_xflag (int indx, INT val)
Called only from main()
...
Definition at line 92 of file miscutil.c.
References flg, FLG::opt, set_xflag_value(), val, and FLG::x.
Referenced by direct_rou_load(), and init().
set_yflag()
void set_yflag (int indx, INT val)
Called only from main()
...
Definition at line 102 of file miscutil.c.
References flg, unset_xflag_value(), val, and FLG::x.
Referenced by direct_rou_load(), and init().
sidecar_not_found()
static void sidecar_not_found (const char * funcname, STG * basestg, STG * stg) static
Definition at line 296 of file miscutil.c.
References ERR_Fatal, and interrf().
Referenced by stg_delete_sidecar().
stg_add_freelist()
void stg_add_freelist (STG * stg, int r)
...
Definition at line 438 of file miscutil.c.
References base, freefield(), r, stg_clear(), and too_small_for_freelist().
stg_alloc()
void stg_alloc (STG * stg, int dtsize, int size, const char * name)
...
Definition at line 198 of file miscutil.c.
References name, size, stg_alloc_base(), and stg_clear_force().
stg_alloc_base()
static void stg_alloc_base (STG * stg, int dtsize, BIGUINT64 size, const char * name) static
Definition at line 137 of file miscutil.c.
References DBGBIT, gbl, invalid_size(), name, sccalloc(), and size.
Referenced by stg_alloc(), and stg_alloc_sidecar().
stg_alloc_sidecar()
void stg_alloc_sidecar (STG * basestg, STG * stg, int dtsize, const char * name)
...
Definition at line 274 of file miscutil.c.
References DBGBIT, ERR_Fatal, gbl, interrf(), name, stg_alloc_base(), and stg_clear_force().
stg_clear()
void stg_clear (STG * stg, int r, int n)
...
Definition at line 179 of file miscutil.c.
References n, r, and stg_clear_force().
Referenced by stg_add_freelist(), stg_clear_all(), stg_next(), and stg_next_freelist().
stg_clear_all()
void stg_clear_all (STG * stg)
...
Definition at line 189 of file miscutil.c.
References stg_clear().
stg_clear_force()
void stg_clear_force (STG * stg, BIGUINT64 r, BIGUINT64 n, bool force)
...
Definition at line 160 of file miscutil.c.
References n, r, STG_CHECKFLAG, and STG_FLAG_NOCLEAR.
Referenced by stg_alloc(), stg_alloc_sidecar(), stg_clear(), and stg_need().
stg_delete()
void stg_delete (STG * stg)
...
Definition at line 208 of file miscutil.c.
References DBGBIT, gbl, and sccfree().
Referenced by stg_delete_sidecar().
stg_delete_sidecar()
void stg_delete_sidecar (STG * basestg, STG * stg)
...
Definition at line 307 of file miscutil.c.
References DBGBIT, gbl, sidecar_not_found(), and stg_delete().
stg_need()
void stg_need (STG * stg)
...
Definition at line 240 of file miscutil.c.
References DBGBIT, gbl, sccrelal(), and stg_clear_force().
Referenced by stg_next().
stg_next()
int stg_next (STG * stg, int n)
...
Definition at line 337 of file miscutil.c.
References ERR_Fatal, interrf(), n, r, stg_clear(), and stg_need().
Referenced by stg_next_freelist().
stg_next_freelist()
int stg_next_freelist (STG * stg)
...
Definition at line 395 of file miscutil.c.
References base, freefield(), r, stg_clear(), stg_next(), and too_small_for_freelist().
stg_reset()
void stg_reset (STG * stg)
Definition at line 222 of file miscutil.c.
References DBGBIT, and gbl.
stg_return()
void stg_return (STG * stg)
Definition at line 419 of file miscutil.c.
References r.
stg_set_freelink()
void stg_set_freelink (STG * stg, int offset)
...
Definition at line 456 of file miscutil.c.
References offset.
too_small_for_freelist()
static void too_small_for_freelist (const char * funcname, STG * stg) static
Definition at line 369 of file miscutil.c.
References ERR_Fatal, and interrf().
Referenced by stg_add_freelist(), and stg_next_freelist().