flang: miscsup_com.c File Reference
miscsup_com.c File Reference
Collection of misc Fortran intrinsics (present, min, max, ajustl, adjustl, ...).
#include <time.h>
#include <string.h>
#include <sys/time.h>
#include <unistd.h>
#include "stdioInterf.h"
#include "fioMacros.h"
#include "llcrit.h"
#include "global.h"
#include "memops.h"
#include "math.h"
#include "type.h"
Macros
#define time(x) __fort_time(x)
#define TIME_THRESHOLD2 1.033944E+09
#define TIME_THRESHOLD1 1.003944E+09
#define MVBIT_OVFL(w) ((fp + ln) > (w) || (tp + ln) > (w))
#define BITS_PER_BYTE 8
#define _MZERO(n, t)
#define _MSET(n, t)
#define _MCOPY(n, t)
Typedefs
typedef __INT8_T MXINT_T
typedef __INT8_T SZ_T
Functions
MP_SEMAPHORE (static, sem)
double __fort_second ()
static void store_mxint_t (void *b, F90_Desc *bd, MXINT_T v)
helper function to store the MXINT_T value into a simple numerical type
static MXINT_T mxint (F90_Desc *bd)
helper function to store the STAT_T value into a varying int
__INT_T ENTFTN (ILEN, ilen)
__LOG_T ENTF90 (PRESENT, present)
__LOG_T ENTF90 (PRESENT_PTR, present_ptr)
__LOG_T ENTF90 (PRESENTCA, presentca)
__LOG_T ENTF90 (PRESENTC, presentc)
__LOG8_T ENTF90 (KPRESENT, kpresent)
-i8 variant of present
__LOG8_T ENTF90 (KPRESENT_PTR, kpresent_ptr)
__LOG8_T ENTF90 (KPRESENTCA, kpresentca)
__LOG8_T ENTF90 (KPRESENTC, kpresentc)
__LOG_T ENTF90 (IS_IOSTAT_END, is_iostat_end)
__LOG8_T ENTF90 (KIS_IOSTAT_END, kis_iostat_end)
__LOG_T ENTF90 (IS_IOSTAT_EOR, is_iostat_eor)
__LOG8_T ENTF90 (KIS_IOSTAT_EOR, kis_iostat_eor)
void * ENTF90 (LOC, loc)
__INT_T ENTF90 (IMAX, imax)
void ENTF90 (MIN, min)
void ENTF90 (MAX, max)
__INT8_T (DCHAR(c) DCLEN64(c))
__INT8_T (DCHAR(c) DCLEN(c))
__INT_T ENTF90 (LENA, lena)
__INT_T ENTF90 (LEN, len)
__INT8_T ENTF90 (KLENA, klena)
__INT8_T ENTF90 (KLEN, klen)
__INT_T ENTF90 (NLENA, nlena)
__INT_T ENTF90 (NLEN, nlen)
__CLEN_T (DCHAR(res), DCHAR(expr) DCLEN64(res) DCLEN64(expr))
__INT_T (DCHAR(res), DCHAR(expr) DCLEN(res) DCLEN(expr))
static void fstrcpy (char *s1, char *s2, __CLEN_T len1, __CLEN_T len2)
static int yr2 (int yr)
void ENTFTN (DATEA, datea)
void ENTFTN (DATE, date)
void ENTFTN (DATEW, datew)
void ENTFTN (JDATE, jdate)
void ENTFTN (IDATE, idate)
void ENTFTN (CPU_TIME, cpu_time)
void ENTFTN (CPU_TIMED, cpu_timed)
__REAL4_T ENTFTN (SECNDS, secnds)
__REAL8_T ENTFTN (SECNDSD, secndsd)
void ENTFTN (FTIMEA, ftimea)
void ENTFTN (FTIME, ftime)
void ENTFTN (FTIMEW, ftimew)
static int I8() next_index (__INT_T *index, F90_Desc *s)
void ENTFTN (DANDTA, dandta)
void ENTFTN (DANDT, dandt)
void ENTFTN (SYSCLK, sysclk)
void ENTF90 (MVBITS, mvbits)
__INT_T ENTF90 (LB, lb)
Varargs: __INT_T *lb1, __INT_T *ub1, ... __INT_T *lb<rank>, __INT_T *ub<rank>
__INT1_T ENTF90 (LB1, lb1)
__INT2_T ENTF90 (LB2, lb2)
__INT4_T ENTF90 (LB4, lb4)
__INT8_T ENTF90 (LB8, lb8)
__INT8_T ENTF90 (KLB, klb)
__INT_T ENTF90 (UB, ub)
__INT1_T ENTF90 (UB1, ub1)
__INT2_T ENTF90 (UB2, ub2)
__INT4_T ENTF90 (UB4, ub4)
__INT8_T ENTF90 (UB8, ub8)
__INT8_T ENTF90 (KUB, kub)
void ENTF90 (LBA, lba)
void ENTF90 (LBA1, lba1)
void ENTF90 (LBA2, lba2)
void ENTF90 (LBA4, lba4)
void ENTF90 (LBA8, lba8)
void ENTF90 (KLBA, klba)
void ENTF90 (UBA, uba)
void ENTF90 (UBA1, uba1)
void ENTF90 (UBA2, uba2)
void ENTF90 (UBA4, uba4)
void ENTF90 (UBA8, uba8)
void ENTF90 (KUBA, kuba)
void ENTF90 (LBAZ, lbaz)
void ENTF90 (LBAZ1, lbaz1)
void ENTF90 (LBAZ2, lbaz2)
void ENTF90 (LBAZ4, lbaz4)
void ENTF90 (LBAZ8, lbaz8)
void ENTF90 (KLBAZ, klbaz)
void ENTF90 (UBAZ, ubaz)
void ENTF90 (UBAZ1, ubaz1)
void ENTF90 (UBAZ2, ubaz2)
void ENTF90 (UBAZ4, ubaz4)
void ENTF90 (UBAZ8, ubaz8)
void ENTF90 (KUBAZ, kubaz)
__INT_T ENTF90 (LBOUND, lbound)
__INT1_T ENTF90 (LBOUND1, lbound1)
__INT2_T ENTF90 (LBOUND2, lbound2)
__INT4_T ENTF90 (LBOUND4, lbound4)
__INT8_T ENTF90 (LBOUND8, lbound8)
__INT8_T ENTF90 (KLBOUND, klbound)
__INT_T ENTF90 (UBOUND, ubound)
__INT1_T ENTF90 (UBOUND1, ubound1)
__INT2_T ENTF90 (UBOUND2, ubound2)
__INT4_T ENTF90 (UBOUND4, ubound4)
__INT8_T ENTF90 (UBOUND8, ubound8)
__INT8_T ENTF90 (KUBOUND, kubound)
void ENTF90 (LBOUNDA, lbounda)
void ENTF90 (LBOUNDA1, lbounda1)
void ENTF90 (LBOUNDA2, lbounda2)
void ENTF90 (LBOUNDA4, lbounda4)
void ENTF90 (LBOUNDA8, lbounda8)
void ENTF90 (KLBOUNDA, klbounda)
void ENTF90 (UBOUNDA, ubounda)
void ENTF90 (UBOUNDA1, ubounda1)
void ENTF90 (UBOUNDA2, ubounda2)
void ENTF90 (UBOUNDA4, ubounda4)
void ENTF90 (UBOUNDA8, ubounda8)
void ENTF90 (KUBOUNDA, kubounda)
void ENTF90 (LBOUNDAZ, lboundaz)
void ENTF90 (LBOUNDAZ1, lboundaz1)
void ENTF90 (LBOUNDAZ2, lboundaz2)
void ENTF90 (LBOUNDAZ4, lboundaz4)
void ENTF90 (LBOUNDAZ8, lboundaz8)
void ENTF90 (KLBOUNDAZ, klboundaz)
void ENTF90 (UBOUNDAZ, uboundaz)
void ENTF90 (UBOUNDAZ1, uboundaz1)
void ENTF90 (UBOUNDAZ2, uboundaz2)
void ENTF90 (UBOUNDAZ4, uboundaz4)
void ENTF90 (UBOUNDAZ8, uboundaz8)
void ENTF90 (KUBOUNDAZ, kuboundaz)
__INT_T ENTF90 (SIZE, size)
__INT8_T ENTF90 (KSIZE, ksize)
__INT8_T ENTF90 (CLASS_OBJ_SIZE, class_obj_size)
void ENTF90 (SHAPE, shape)
void ENTF90 (SHAPE1, shape1)
void ENTF90 (SHAPE2, shape2)
void ENTF90 (SHAPE4, shape4)
void ENTF90 (SHAPE8, shape8)
void ENTF90 (KSHAPE, kshape)
Vargs: { lwb, *upb, *stride }
__INT_T (DCHAR(res), void *i, __INT_T *size DCLEN64(res))
ACHAR function returns LEN;.
__CLEN_T (DCHAR(res), DCHAR(expr), void *ncopies, __INT_T *size DCLEN64(res) DCLEN64(expr))
__INT_T (DCHAR(res), DCHAR(expr), void *ncopies, __INT_T *size DCLEN(res) DCLEN(expr))
__INT_T (DCHAR(res), DCHAR(expr) DCLEN64(res) DCLEN64(expr))
__INT_T ENTF90 (IACHARA, iachara)
__INT_T ENTF90 (IACHAR, iachar)
__INT8_T ENTF90 (KIACHARA, kiachara)
-i8 variant of iachar
__INT8_T ENTF90 (KIACHAR, kiachar)
void ENTF90 (MERGECHA, mergecha)
void ENTF90 (MERGECH, mergech)
void ENTF90 (MERGEDT, mergedt)
__INT1_T (__INT1_T *tsource, __INT1_T *fsource, void *mask, __INT_T *size)
__INT2_T (__INT2_T *tsource, __INT2_T *fsource, void *mask, __INT_T *size)
__INT4_T (__INT4_T *tsource, __INT4_T *fsource, void *mask, __INT_T *size)
__INT8_T (__INT8_T *tsource, __INT8_T *fsource, void *mask, __INT_T *size)
__LOG1_T (__LOG1_T *tsource, __LOG1_T *fsource, void *mask, __INT_T *size)
__LOG2_T (__LOG2_T *tsource, __LOG2_T *fsource, void *mask, __INT_T *size)
__LOG4_T (__LOG4_T *tsource, __LOG4_T *fsource, void *mask, __INT_T *size)
__LOG8_T (__LOG8_T *tsource, __LOG8_T *fsource, void *mask, __INT_T *size)
__REAL4_T (__REAL4_T *tsource, __REAL4_T *fsource, void *mask, __INT_T *size)
__REAL8_T (__REAL8_T *tsource, __REAL8_T *fsource, void *mask, __INT_T *size)
__REAL16_T (__REAL16_T *tsource, __REAL16_T *fsource, void *mask, __INT_T *size)
__INT_T ENTF90 (LENTRIMA, lentrima)
__INT_T ENTF90 (LENTRIM, lentrim)
__INT8_T ENTF90 (KLENTRIMA, klentrima)
__INT8_T ENTF90 (KLENTRIM, klentrim)
__INT_T (DCHAR(str), DCHAR(set), void *back, __INT_T *size DCLEN64(str) DCLEN64(set))
__INT_T (DCHAR(str), DCHAR(set), void *back, __INT_T *size DCLEN(str) DCLEN(set))
__INT8_T (DCHAR(str), DCHAR(set), void *back, __INT_T *size DCLEN64(str) DCLEN64(set))
-i8 variant of SCAN
__INT8_T (DCHAR(str), DCHAR(set), void *back, __INT_T *size DCLEN(str) DCLEN(set))
__INT8_T (DCHAR(string), DCHAR(substring), void *back, __INT_T *size DCLEN64(string) DCLEN64(substring))
-i8 variant of INDEX
__INT8_T (DCHAR(string), DCHAR(substring), void *back, __INT_T *size DCLEN(string) DCLEN(substring))
__INT_T (DCHAR(string), DCHAR(substring), void *back, __INT_T *size DCLEN64(string) DCLEN64(substring))
__INT_T (DCHAR(string), DCHAR(substring), void *back, __INT_T *size DCLEN(string) DCLEN(substring))
__INT_T ENTFTN (LEADZ, leadz)
__INT_T ENTFTN (TRAILZ, trailz)
__INT_T ENTFTN (POPCNT, popcnt)
__INT_T ENTFTN (POPPAR, poppar)
__INT4_T ENTF90 (JMAX0, jmax0)
__INT4_T ENTF90 (MAX0, max0)
__INT8_T ENTF90 (KMAX, kmax)
__INT4_T ENTF90 (MIN0, min0)
__INT4_T ENTF90 (MOD, mod)
__INT_T ENTF90 (INT, int)
__INT1_T ENTF90 (INT1, int1)
__INT2_T ENTF90 (INT2, int2)
__INT4_T ENTF90 (INT4, int4)
__INT8_T ENTF90 (INT8, int8)
__LOG1_T ENTF90 (LOG1, log1)
__LOG2_T ENTF90 (LOG2, log2)
__LOG4_T ENTF90 (LOG4, log4)
__LOG8_T ENTF90 (LOG8, log8)
__REAL_T ENTF90 (REAL, real)
__DBLE_T ENTF90 (DBLE, dble)
__REAL4_T ENTF90 (REAL4, real4)
__REAL8_T ENTF90 (REAL8, real8)
__REAL_T ENTF90 (AMAX1, amax1)
__DBLE_T ENTF90 (DMAX1, dmax1)
__REAL_T ENTF90 (AMIN1, amin1)
__DBLE_T ENTF90 (DMIN1, dmin1)
__REAL_T ENTF90 (AMOD, amod)
__DBLE_T ENTF90 (DMOD, dmod)
__INT4_T ENTF90 (MODULO, modulo)
__INT8_T ENTF90 (I8MODULO, i8modulo)
__INT2_T ENTF90 (IMODULO, imodulo)
__REAL_T ENTF90 (AMODULO, amodulo)
__DBLE_T ENTF90 (DMODULO, dmodulo)
__INT4_T ENTF90 (MODULOv, modulov)
__INT8_T ENTF90 (I8MODULOv, i8modulov)
__INT2_T ENTF90 (IMODULOv, imodulov)
__REAL_T ENTF90 (AMODULOv, amodulov)
__DBLE_T ENTF90 (DMODULOv, dmodulov)
__INT_T ENTF90 (CEILING, ceiling)
__INT8_T ENTF90 (KCEILING, kceiling)
__INT_T ENTF90 (DCEILING, dceiling)
__INT8_T ENTF90 (KDCEILING, kdceiling)
__INT_T ENTF90 (CEILINGv, ceilingv)
__INT8_T ENTF90 (KCEILINGv, kceilingv)
__INT_T ENTF90 (DCEILINGv, dceilingv)
__INT8_T ENTF90 (KDCEILINGv, kdceilingv)
__INT_T ENTF90 (FLOOR, floor)
__INT_T ENTF90 (KFLOOR, kfloor)
__INT_T ENTF90 (DFLOOR, dfloor)
__INT8_T ENTF90 (KDFLOOR, kdfloor)
__INT_T ENTF90 (FLOORv, floorv)
__INT_T ENTF90 (KFLOORv, kfloorv)
__INT_T ENTF90 (DFLOORv, dfloorv)
__INT8_T ENTF90 (KDFLOORv, kdfloorv)
__INT_T (char *rb, F90_Desc *rd)
selected_int_kind(r)
__INT8_T (char *rb, F90_Desc *rd)
-i8 variant of SEL_INT_KIND
static int _selected_char_kind (char *p, __CLEN_T len)
Check charset.
__INT_T (DCHAR(p), F90_Desc *rd DCLEN64(p))
__INT8_T (DCHAR(p), F90_Desc *rd DCLEN(p))
__INT8_T (char *pb, char *rb, char *radixb, F90_Desc *pd, F90_Desc *rd, F90_Desc *radixd)
selected_real_kind(p,r,radix),add radix argument for f2008
__INT_T (char *pb, char *rb, char *radixb, F90_Desc *pd, F90_Desc *rd, F90_Desc *radixd)
__INT_T ENTF90 (EXPONX, exponx)
__INT_T ENTF90 (EXPON, expon)
__INT_T ENTF90 (EXPONDX, expondx)
__INT_T ENTF90 (EXPOND, expond)
__INT8_T ENTF90 (KEXPONX, kexponx)
__INT8_T ENTF90 (KEXPON, kexpon)
__INT8_T ENTF90 (KEXPONDX, kexpondx)
__INT8_T ENTF90 (KEXPOND, kexpond)
__REAL4_T ENTF90 (FRACX, fracx)
__REAL4_T ENTF90 (FRAC, frac)
__REAL8_T ENTF90 (FRACDX, fracdx)
__REAL8_T ENTF90 (FRACD, fracd)
__REAL4_T ENTF90 (NEARESTX, nearestx)
NEAREST(X,S) has a value equal to the machine representable number distinct from X and nearest to it in the direction of the infinity with the same sign as S.
__REAL4_T ENTF90 (NEAREST, nearest)
__REAL8_T ENTF90 (NEARESTDX, nearestdx)
__REAL8_T ENTF90 (NEARESTD, nearestd)
__REAL4_T ENTF90 (RRSPACINGX, rrspacingx)
__REAL4_T ENTF90 (RRSPACING, rrspacing)
__REAL8_T ENTF90 (RRSPACINGDX, rrspacingdx)
__REAL8_T ENTF90 (RRSPACINGD, rrspacingd)
__REAL4_T ENTF90 (SCALEX, scalex)
__REAL4_T ENTF90 (SCALE, scale)
__REAL8_T ENTF90 (SCALEDX, scaledx)
__REAL8_T ENTF90 (SCALED, scaled)
__REAL4_T ENTF90 (SETEXPX, setexpx)
__REAL4_T ENTF90 (SETEXP, setexp)
__REAL8_T ENTF90 (SETEXPDX, setexpdx)
__REAL8_T ENTF90 (SETEXPD, setexpd)
__REAL4_T ENTF90 (SPACINGX, spacingx)
__REAL4_T ENTF90 (SPACING, spacing)
__REAL8_T ENTF90 (SPACINGDX, spacingdx)
__REAL8_T ENTF90 (SPACINGD, spacingd)
void ENTF90 (MZEROZ8, mzeroz8)
void ENTF90 (MZEROZ16, mzeroz16)
void ENTF90 (MSETZ8, msetz8)
void ENTF90 (MSETZ16, msetz16)
void ENTF90 (MSETZ32, msetz32)
void ENTF90 (MCOPYZ8, mcopyz8)
void ENTF90 (MCOPYZ16, mcopyz16)
Variables
static const char * month [12]
Detailed Description
Collection of misc Fortran intrinsics (present, min, max, ajustl, adjustl, ...).
Definition in file miscsup_com.c.
Macro Definition Documentation
_MCOPY
#define _MCOPY (n, t)
Value:
  void ENTF90(MCOPY##n, mcopy##n)(void *d, void *v, SZ_T size)                 \
  {                                                                            \
    if (d && v && size > 0)                                                    \
      __c_mcopy##n(d, v, size);                                                \
  }
Definition at line 5289 of file miscsup_com.c.
_MSET
#define _MSET (n, t)
Value:
  void ENTF90(MSET##n, mset##n)(void *d, void *v, SZ_T size)                   \
  {                                                                            \
    if (d && size > 0)                                                         \
      __c_mset##n(d, *((t *)v), size);                                         \
  }
Definition at line 5215 of file miscsup_com.c.
_MZERO
#define _MZERO (n, t)
Value:
void                                    \
ENTF90(MZEROERO##n, mzero##n)(void *d, SZ_T size)                       \
{                                                                       \
  if (d && size > 0)                                                    \
    __c_mzero##n(d, size);                                              \
}
Definition at line 5168 of file miscsup_com.c.
BITS_PER_BYTE
#define BITS_PER_BYTE 8
Definition at line 2669 of file miscsup_com.c.
MVBIT_OVFL
#define MVBIT_OVFL (w) ((fp + ln) > (w) || (tp + ln) > (w))
time
#define time (x) __fort_time(x)
Definition at line 36 of file miscsup_com.c.
TIME_THRESHOLD1
#define TIME_THRESHOLD1 1.003944E+09
Definition at line 537 of file miscsup_com.c.
TIME_THRESHOLD2
#define TIME_THRESHOLD2 1.033944E+09
Definition at line 536 of file miscsup_com.c.
Typedef Documentation
MXINT_T
typedef __INT8_T MXINT_T
Definition at line 38 of file miscsup_com.c.
SZ_T
typedef __INT8_T SZ_T
Definition at line 5165 of file miscsup_com.c.
Function Documentation
__CLEN_T() [1/2]
__CLEN_T (DCHAR(res) , DCHAR(expr) DCLEN64(res) DCLEN64(expr))
Definition at line 382 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, i, j, and res.
Referenced by __CLEN_T(), __INT8_T(), __INT_T(), ENTF90(), ENTFTN(), and fstrcpy().
__CLEN_T() [2/2]
__CLEN_T (DCHAR(res) , DCHAR(expr) , void * ncopies, __INT_T *size DCLEN64res) DCLEN64(expr)
Definition at line 2851 of file miscsup_com.c.
References __CLEN_T(), __fort_varying_int(), CADR, CLEN, i, I8, len, res, and size.
__fort_second()
double __fort_second ()
Definition at line 104 of file stat_linux.c.
References __fort_abortp(), d, first, s, t, and timezone.
Referenced by ENTFTN().
__INT1_T()
__INT1_T (__INT1_T * tsource, __INT1_T * fsource, void * mask, __INT_T * size)
Definition at line 3005 of file miscsup_com.c.
References __fort_varying_log(), I8, and size.
Referenced by mxint().
__INT2_T()
__INT2_T (__INT2_T * tsource, __INT2_T * fsource, void * mask, __INT_T * size)
Definition at line 3012 of file miscsup_com.c.
References __fort_varying_log(), I8, and size.
Referenced by mxint().
__INT4_T()
__INT4_T (__INT4_T * tsource, __INT4_T * fsource, void * mask, __INT_T * size)
Definition at line 3019 of file miscsup_com.c.
References __fort_varying_log(), I8, and size.
Referenced by mxint().
__INT8_T() [1/10]
__INT8_T (__INT8_T * tsource, __INT8_T * fsource, void * mask, __INT_T * size)
Definition at line 3026 of file miscsup_com.c.
References __fort_varying_log(), I8, and size.
__INT8_T() [2/10]
__INT8_T (char * pb, char * rb, char * radixb, F90_Desc * pd, F90_Desc * rd, F90_Desc * radixd)
selected_real_kind(p,r,radix),add radix argument for f2008
Definition at line 4398 of file miscsup_com.c.
References __fort_fetch_int(), e, I8, ISPRESENT, k, p, pb, pd, r, and rb.
__INT8_T() [3/10]
__INT8_T (char * rb, F90_Desc * rd)
-i8 variant of SEL_INT_KIND
Definition at line 4325 of file miscsup_com.c.
References __fort_fetch_int(), I8, r, and rb.
__INT8_T() [4/10]
__INT8_T (DCHAR(c) DCLEN(c))
Definition at line 339 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, and ENTF90().
__INT8_T() [5/10]
__INT8_T (DCHAR(c) DCLEN64(c))
Definition at line 332 of file miscsup_com.c.
References CADR.
Referenced by __INT8_T(), ENTF90(), and mxint().
__INT8_T() [6/10]
__INT8_T (DCHAR(p) , F90_Desc *rd DCLENp)
Definition at line 4377 of file miscsup_com.c.
References _selected_char_kind(), CADR, CLEN, p, and r.
__INT8_T() [7/10]
__INT8_T (DCHAR(str) , DCHAR(set) , void * back, __INT_T *size DCLENstr) DCLEN(set)
Definition at line 3173 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, ENTF90(), set, size, and str.
__INT8_T() [8/10]
__INT8_T (DCHAR(str) , DCHAR(set) , void * back, __INT_T *size DCLEN64str) DCLEN64(set)
-i8 variant of SCAN
-i8 variant of VERIFY
Definition at line 3152 of file miscsup_com.c.
References __fort_varying_log(), __INT8_T(), CADR, CLEN, i, I8, ISPRESENT, j, set, size, and str.
__INT8_T() [9/10]
__INT8_T (DCHAR(string) , DCHAR(substring) , void * back, __INT_T *size DCLENstring) DCLEN(substring)
Definition at line 3287 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, ENTF90(), size, and substring.
__INT8_T() [10/10]
__INT8_T (DCHAR(string) , DCHAR(substring) , void * back, __INT_T *size DCLEN64string) DCLEN64(substring)
-i8 variant of INDEX
Definition at line 3257 of file miscsup_com.c.
References __fort_varying_log(), __INT8_T(), CADR, CLEN, i, I8, ISPRESENT, n, size, and substring.
__INT_T() [1/11]
__INT_T (char * pb, char * rb, char * radixb, F90_Desc * pd, F90_Desc * rd, F90_Desc * radixd)
Definition at line 4452 of file miscsup_com.c.
References __fort_fetch_int(), e, I8, ISPRESENT, k, p, pb, pd, r, and rb.
__INT_T() [2/11]
__INT_T (char * rb, F90_Desc * rd)
selected_int_kind(r)
Definition at line 4304 of file miscsup_com.c.
References __fort_fetch_int(), I8, r, and rb.
__INT_T() [3/11]
__INT_T (DCHAR(p) , F90_Desc *rd DCLEN64p)
Definition at line 4361 of file miscsup_com.c.
References _selected_char_kind(), CADR, CLEN, p, and r.
__INT_T() [4/11]
__INT_T (DCHAR(res) , DCHAR(expr) DCLEN(res) DCLEN(expr))
Definition at line 399 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, ENTF90(), and res.
Referenced by __INT_T().
__INT_T() [5/11]
__INT_T (DCHAR(res) , DCHAR(expr) DCLEN64(res) DCLEN64(expr))
Definition at line 2875 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, DCHAR, DCLEN(), ENTF90(), i, j, and res.
__INT_T() [6/11]
__INT_T (DCHAR(res) , DCHAR(expr) , void * ncopies, __INT_T *size DCLENres) DCLEN(expr)
Definition at line 2867 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, ENTF90(), res, and size.
__INT_T() [7/11]
__INT_T (DCHAR(res) , void * i, __INT_T *size DCLEN64res)
ACHAR function returns LEN;.
avoid confusion on returning character result
Definition at line 2836 of file miscsup_com.c.
References __fort_varying_int(), CADR, i, I8, res, and size.
__INT_T() [8/11]
__INT_T (DCHAR(str) , DCHAR(set) , void * back, __INT_T *size DCLENstr) DCLEN(set)
Definition at line 3141 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, ENTF90(), set, size, and str.
__INT_T() [9/11]
__INT_T (DCHAR(str) , DCHAR(set) , void * back, __INT_T *size DCLEN64str) DCLEN64(set)
Definition at line 3120 of file miscsup_com.c.
References __fort_varying_log(), __INT_T(), CADR, CLEN, i, I8, ISPRESENT, j, set, size, and str.
__INT_T() [10/11]
__INT_T (DCHAR(string) , DCHAR(substring) , void * back, __INT_T *size DCLENstring) DCLEN(substring)
Definition at line 3326 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, ENTF90(), size, and substring.
__INT_T() [11/11]
__INT_T (DCHAR(string) , DCHAR(substring) , void * back, __INT_T *size DCLEN64string) DCLEN64(substring)
Definition at line 3296 of file miscsup_com.c.
References __fort_varying_log(), __INT_T(), CADR, CLEN, i, I8, ISPRESENT, n, size, and substring.
__LOG1_T()
__LOG1_T (__LOG1_T * tsource, __LOG1_T * fsource, void * mask, __INT_T * size)
Definition at line 3033 of file miscsup_com.c.
References __fort_varying_log(), I8, and size.
__LOG2_T()
__LOG2_T (__LOG2_T * tsource, __LOG2_T * fsource, void * mask, __INT_T * size)
Definition at line 3040 of file miscsup_com.c.
References __fort_varying_log(), I8, and size.
__LOG4_T()
__LOG4_T (__LOG4_T * tsource, __LOG4_T * fsource, void * mask, __INT_T * size)
Definition at line 3047 of file miscsup_com.c.
References __fort_varying_log(), I8, and size.
__LOG8_T()
__LOG8_T (__LOG8_T * tsource, __LOG8_T * fsource, void * mask, __INT_T * size)
Definition at line 3054 of file miscsup_com.c.
References __fort_varying_log(), I8, and size.
__REAL16_T()
__REAL16_T (__REAL16_T * tsource, __REAL16_T * fsource, void * mask, __INT_T * size)
Definition at line 3075 of file miscsup_com.c.
References __fort_varying_log(), I8, and size.
__REAL4_T()
__REAL4_T (__REAL4_T * tsource, __REAL4_T * fsource, void * mask, __INT_T * size)
Definition at line 3061 of file miscsup_com.c.
References __fort_varying_log(), I8, and size.
Referenced by ENTFTN().
__REAL8_T()
__REAL8_T (__REAL8_T * tsource, __REAL8_T * fsource, void * mask, __INT_T * size)
Definition at line 3068 of file miscsup_com.c.
References __fort_varying_log(), I8, and size.
Referenced by ENTFTN().
_selected_char_kind()
static int _selected_char_kind (char * p, __CLEN_T len) static
Check charset.
Make sure this routine is consistent with
fe90: semfunc.c:_selected_char_kind()
f90: dinit.c:_selected_char_kind()
Definition at line 4352 of file miscsup_com.c.
References __fortio_eq_str(), len, and p.
Referenced by __INT8_T(), __INT_T(), and dinit_acl_val2().
ENTF90() [1/204]
__REAL_T ENTF90 (AMAX1 , amax1)
Definition at line 3902 of file miscsup_com.c.
References a, and b.
ENTF90() [2/204]
__REAL_T ENTF90 (AMIN1 , amin1)
Definition at line 3908 of file miscsup_com.c.
References a, and b.
ENTF90() [3/204]
__REAL_T ENTF90 (AMOD , amod)
Definition at line 3914 of file miscsup_com.c.
References a, b, and fmod().
ENTF90() [4/204]
__REAL_T ENTF90 (AMODULO , amodulo)
Definition at line 3962 of file miscsup_com.c.
References d, fmod(), x, and y.
ENTF90() [5/204]
__REAL_T ENTF90 (AMODULOv , amodulov)
Definition at line 4033 of file miscsup_com.c.
References d, fmod(), x, and y.
ENTF90() [6/204]
__INT_T ENTF90 (CEILING , ceiling)
Definition at line 4064 of file miscsup_com.c.
References a, r, and x.
ENTF90() [7/204]
__INT_T ENTF90 (CEILINGv , ceilingv)
Definition at line 4124 of file miscsup_com.c.
References a, r, and x.
ENTF90() [8/204]
__INT8_T ENTF90 (CLASS_OBJ_SIZE , class_obj_size)
Definition at line 2671 of file miscsup_com.c.
References d, and ENTF90().
ENTF90() [9/204]
__DBLE_T ENTF90 (DBLE , dble)
Definition at line 3800 of file miscsup_com.c.
References __CPLX16, __CPLX8, __fort_abort(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL4, __REAL8, a, and r.
ENTF90() [10/204]
__INT_T ENTF90 (DCEILING , dceiling)
Definition at line 4094 of file miscsup_com.c.
References a, r, and x.
ENTF90() [11/204]
__INT_T ENTF90 (DCEILINGv , dceilingv)
Definition at line 4154 of file miscsup_com.c.
References a, r, and x.
ENTF90() [12/204]
__INT_T ENTF90 (DFLOOR , dfloor)
Definition at line 4214 of file miscsup_com.c.
References a, r, and x.
ENTF90() [13/204]
__INT_T ENTF90 (DFLOORv , dfloorv)
Definition at line 4274 of file miscsup_com.c.
References a, r, and x.
ENTF90() [14/204]
__DBLE_T ENTF90 (DMAX1 , dmax1)
Definition at line 3905 of file miscsup_com.c.
References a, and b.
ENTF90() [15/204]
__DBLE_T ENTF90 (DMIN1 , dmin1)
Definition at line 3911 of file miscsup_com.c.
References a, and b.
ENTF90() [16/204]
__DBLE_T ENTF90 (DMOD , dmod)
Definition at line 3917 of file miscsup_com.c.
References a, b, and fmod().
ENTF90() [17/204]
__DBLE_T ENTF90 (DMODULO , dmodulo)
Definition at line 3972 of file miscsup_com.c.
References d, fmod(), x, and y.
ENTF90() [18/204]
__DBLE_T ENTF90 (DMODULOv , dmodulov)
Definition at line 4043 of file miscsup_com.c.
References d, fmod(), x, and y.
ENTF90() [19/204]
__INT_T ENTF90 (EXPON , expon)
Definition at line 4517 of file miscsup_com.c.
References ENTF90().
ENTF90() [20/204]
__INT_T ENTF90 (EXPOND , expond)
Definition at line 4537 of file miscsup_com.c.
References ENTF90().
ENTF90() [21/204]
__INT_T ENTF90 (EXPONDX , expondx)
Definition at line 4523 of file miscsup_com.c.
References d, i, and r.
ENTF90() [22/204]
__INT_T ENTF90 (EXPONX , exponx)
Definition at line 4503 of file miscsup_com.c.
References f, i, and r.
ENTF90() [23/204]
__INT_T ENTF90 (FLOOR , floor)
Definition at line 4184 of file miscsup_com.c.
References a, r, and x.
ENTF90() [24/204]
__INT_T ENTF90 (FLOORv , floorv)
Definition at line 4244 of file miscsup_com.c.
References a, r, and x.
ENTF90() [25/204]
__REAL4_T ENTF90 (FRAC , frac)
Definition at line 4602 of file miscsup_com.c.
References ENTF90().
ENTF90() [26/204]
__REAL8_T ENTF90 (FRACD , fracd)
Definition at line 4618 of file miscsup_com.c.
References ENTF90().
ENTF90() [27/204]
__REAL8_T ENTF90 (FRACDX , fracdx)
Definition at line 4605 of file miscsup_com.c.
References d, and x.
ENTF90() [28/204]
__REAL4_T ENTF90 (FRACX , fracx)
Definition at line 4586 of file miscsup_com.c.
References f, i, and x.
ENTF90() [29/204]
__INT8_T ENTF90 (I8MODULO , i8modulo)
Definition at line 3936 of file miscsup_com.c.
References a, p, q, and r.
ENTF90() [30/204]
__INT8_T ENTF90 (I8MODULOv , i8modulov)
Definition at line 4007 of file miscsup_com.c.
References a, p, q, and r.
ENTF90() [31/204]
__INT_T ENTF90 (IACHAR , iachar)
Definition at line 2956 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, and ENTF90().
ENTF90() [32/204]
__INT_T ENTF90 (IACHARA , iachara)
Definition at line 2953 of file miscsup_com.c.
References CADR.
ENTF90() [33/204]
__INT_T ENTF90 (IMAX , imax)
Definition at line 238 of file miscsup_com.c.
References i, and j.
ENTF90() [34/204]
__INT2_T ENTF90 (IMODULO , imodulo)
Definition at line 3949 of file miscsup_com.c.
References a, p, q, and r.
ENTF90() [35/204]
__INT2_T ENTF90 (IMODULOv , imodulov)
Definition at line 4020 of file miscsup_com.c.
References a, p, q, and r.
ENTF90() [36/204]
__INT_T ENTF90 (INT , int)
Definition at line 3472 of file miscsup_com.c.
References __CPLX16, __CPLX32, __CPLX8, __fort_abort(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL16, __REAL4, __REAL8, a, and r.
ENTF90() [37/204]
__INT1_T ENTF90 (INT1 , int1)
Definition at line 3510 of file miscsup_com.c.
References __CPLX16, __CPLX32, __CPLX8, __fort_abort(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL16, __REAL4, __REAL8, a, and r.
ENTF90() [38/204]
__INT2_T ENTF90 (INT2 , int2)
Definition at line 3548 of file miscsup_com.c.
References __CPLX16, __CPLX32, __CPLX8, __fort_abort(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL16, __REAL4, __REAL8, a, and r.
ENTF90() [39/204]
__INT4_T ENTF90 (INT4 , int4)
Definition at line 3586 of file miscsup_com.c.
References __CPLX16, __CPLX32, __CPLX8, __fort_abort(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL16, __REAL4, __REAL8, a, and r.
ENTF90() [40/204]
__INT8_T ENTF90 (INT8 , int8)
Definition at line 3624 of file miscsup_com.c.
References __CPLX16, __CPLX32, __CPLX8, __fort_abort(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL16, __REAL4, __REAL8, a, and r.
ENTF90() [41/204]
__LOG_T ENTF90 (IS_IOSTAT_END , is_iostat_end)
Definition at line 204 of file miscsup_com.c.
References GET_DIST_TRUE_LOG, and i.
ENTF90() [42/204]
__LOG_T ENTF90 (IS_IOSTAT_EOR , is_iostat_eor)
Definition at line 218 of file miscsup_com.c.
References GET_DIST_TRUE_LOG, and i.
ENTF90() [43/204]
__INT4_T ENTF90 (JMAX0 , jmax0)
Definition at line 3457 of file miscsup_com.c.
References a, and b.
ENTF90() [44/204]
__INT8_T ENTF90 (KCEILING , kceiling)
Definition at line 4079 of file miscsup_com.c.
References a, r, and x.
ENTF90() [45/204]
__INT8_T ENTF90 (KCEILINGv , kceilingv)
Definition at line 4139 of file miscsup_com.c.
References a, r, and x.
ENTF90() [46/204]
__INT8_T ENTF90 (KDCEILING , kdceiling)
Definition at line 4109 of file miscsup_com.c.
References a, r, and x.
ENTF90() [47/204]
__INT8_T ENTF90 (KDCEILINGv , kdceilingv)
Definition at line 4169 of file miscsup_com.c.
References a, r, and x.
ENTF90() [48/204]
__INT8_T ENTF90 (KDFLOOR , kdfloor)
Definition at line 4229 of file miscsup_com.c.
References a, r, and x.
ENTF90() [49/204]
__INT8_T ENTF90 (KDFLOORv , kdfloorv)
Definition at line 4289 of file miscsup_com.c.
References a, r, and x.
ENTF90() [50/204]
__INT8_T ENTF90 (KEXPON , kexpon)
Definition at line 4569 of file miscsup_com.c.
References ENTF90().
ENTF90() [51/204]
__INT8_T ENTF90 (KEXPOND , kexpond)
Definition at line 4581 of file miscsup_com.c.
References ENTF90().
ENTF90() [52/204]
__INT8_T ENTF90 (KEXPONDX , kexpondx)
Definition at line 4575 of file miscsup_com.c.
References d, and ENTF90().
ENTF90() [53/204]
__INT8_T ENTF90 (KEXPONX , kexponx)
Definition at line 4563 of file miscsup_com.c.
References ENTF90(), and f.
ENTF90() [54/204]
__INT_T ENTF90 (KFLOOR , kfloor)
Definition at line 4199 of file miscsup_com.c.
References a, r, and x.
ENTF90() [55/204]
__INT_T ENTF90 (KFLOORv , kfloorv)
Definition at line 4259 of file miscsup_com.c.
References a, r, and x.
ENTF90() [56/204]
__INT8_T ENTF90 (KIACHAR , kiachar)
Definition at line 2971 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, and ENTF90().
ENTF90() [57/204]
__INT8_T ENTF90 (KIACHARA , kiachara)
-i8 variant of iachar
Definition at line 2965 of file miscsup_com.c.
References CADR.
ENTF90() [58/204]
__LOG8_T ENTF90 (KIS_IOSTAT_END , kis_iostat_end)
Definition at line 211 of file miscsup_com.c.
References GET_DIST_TRUE_LOG, and i.
ENTF90() [59/204]
__LOG8_T ENTF90 (KIS_IOSTAT_EOR , kis_iostat_eor)
Definition at line 225 of file miscsup_com.c.
References GET_DIST_TRUE_LOG, and i.
ENTF90() [60/204]
__INT8_T ENTF90 (KLB , klb)
Definition at line 1094 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, lb, rank, ub, and va.
ENTF90() [61/204]
void ENTF90 (KLBA , klba)
Definition at line 1393 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [62/204]
void ENTF90 (KLBAZ , klbaz)
Definition at line 1679 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [63/204]
__INT8_T ENTF90 (KLBOUND , klbound)
Definition at line 1939 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, rank, and va.
ENTF90() [64/204]
void ENTF90 (KLBOUNDA , klbounda)
Definition at line 2185 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [65/204]
void ENTF90 (KLBOUNDAZ , klboundaz)
Definition at line 2423 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [66/204]
__INT8_T ENTF90 (KLEN , klen)
Definition at line 365 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, ENTF90(), and s.
ENTF90() [67/204]
__INT8_T ENTF90 (KLENA , klena)
Definition at line 359 of file miscsup_com.c.
References CLEN, and s.
ENTF90() [68/204]
__INT8_T ENTF90 (KLENTRIM , klentrim)
Definition at line 3115 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, ENTF90(), and str.
ENTF90() [69/204]
__INT8_T ENTF90 (KLENTRIMA , klentrima)
Definition at line 3100 of file miscsup_com.c.
References CADR, CLEN, i, and str.
ENTF90() [70/204]
__INT8_T ENTF90 (KMAX , kmax)
Definition at line 3463 of file miscsup_com.c.
References a, and b.
ENTF90() [71/204]
__LOG8_T ENTF90 (KPRESENT , kpresent)
-i8 variant of present
Definition at line 149 of file miscsup_com.c.
References GET_DIST_TRUE_LOG, ISPRESENT, and p.
ENTF90() [72/204]
__LOG8_T ENTF90 (KPRESENT_PTR , kpresent_ptr)
Definition at line 157 of file miscsup_com.c.
References ENTCOMN, GET_DIST_TRUE_LOG, NULL, and p.
ENTF90() [73/204]
__LOG8_T ENTF90 (KPRESENTC , kpresentc)
Definition at line 198 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, ENTF90(), and p.
ENTF90() [74/204]
__LOG8_T ENTF90 (KPRESENTCA , kpresentca)
Definition at line 186 of file miscsup_com.c.
References GET_DIST_TRUE_LOG, ISPRESENTC, and p.
ENTF90() [75/204]
void ENTF90 (KSHAPE , kshape)
Vargs: { lwb, *upb, *stride }
Definition at line 2809 of file miscsup_com.c.
References __fort_abort(), d, extent(), ISPRESENT, lwb, rank, stride, upb, and va.
ENTF90() [76/204]
__INT8_T ENTF90 (KSIZE , ksize)
Definition at line 2616 of file miscsup_com.c.
References __fort_abort(), d, dim, extent(), ISPRESENT, lwb, rank, stride, upb, and va.
ENTF90() [77/204]
__INT8_T ENTF90 (KUB , kub)
Definition at line 1240 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, lb, rank, ub, and va.
ENTF90() [78/204]
void ENTF90 (KUBA , kuba)
Definition at line 1528 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [79/204]
void ENTF90 (KUBAZ , kubaz)
Definition at line 1813 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [80/204]
__INT8_T ENTF90 (KUBOUND , kubound)
Definition at line 2065 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, rank, and va.
ENTF90() [81/204]
void ENTF90 (KUBOUNDA , kubounda)
Definition at line 2304 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [82/204]
void ENTF90 (KUBOUNDAZ , kuboundaz)
Definition at line 2542 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [83/204]
__INT_T ENTF90 (LB , lb)
Varargs: __INT_T *lb1, __INT_T *ub1, ... __INT_T *lb<rank>, __INT_T *ub<rank>
Definition at line 960 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, lb, rank, ub, and va.
ENTF90() [84/204]
__INT1_T ENTF90 (LB1 , lb1)
Definition at line 988 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, lb, rank, ub, and va.
ENTF90() [85/204]
__INT2_T ENTF90 (LB2 , lb2)
Definition at line 1016 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, lb, rank, ub, and va.
ENTF90() [86/204]
__INT4_T ENTF90 (LB4 , lb4)
Definition at line 1042 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, lb, rank, ub, and va.
ENTF90() [87/204]
__INT8_T ENTF90 (LB8 , lb8)
Definition at line 1068 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, lb, rank, ub, and va.
ENTF90() [88/204]
void ENTF90 (LBA , lba)
Definition at line 1268 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [89/204]
void ENTF90 (LBA1 , lba1)
Definition at line 1293 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [90/204]
void ENTF90 (LBA2 , lba2)
Definition at line 1318 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [91/204]
void ENTF90 (LBA4 , lba4)
Definition at line 1343 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [92/204]
void ENTF90 (LBA8 , lba8)
Definition at line 1368 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [93/204]
void ENTF90 (LBAZ , lbaz)
Definition at line 1554 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [94/204]
void ENTF90 (LBAZ1 , lbaz1)
Definition at line 1579 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [95/204]
void ENTF90 (LBAZ2 , lbaz2)
Definition at line 1604 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [96/204]
void ENTF90 (LBAZ4 , lbaz4)
Definition at line 1629 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [97/204]
void ENTF90 (LBAZ8 , lbaz8)
Definition at line 1654 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [98/204]
__INT_T ENTF90 (LBOUND , lbound)
Definition at line 1839 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, rank, and va.
ENTF90() [99/204]
__INT1_T ENTF90 (LBOUND1 , lbound1)
Definition at line 1859 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, rank, and va.
ENTF90() [100/204]
__INT2_T ENTF90 (LBOUND2 , lbound2)
Definition at line 1879 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, rank, and va.
ENTF90() [101/204]
__INT4_T ENTF90 (LBOUND4 , lbound4)
Definition at line 1899 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, rank, and va.
ENTF90() [102/204]
__INT8_T ENTF90 (LBOUND8 , lbound8)
Definition at line 1919 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, rank, and va.
ENTF90() [103/204]
void ENTF90 (LBOUNDA , lbounda)
Definition at line 2090 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [104/204]
void ENTF90 (LBOUNDA1 , lbounda1)
Definition at line 2109 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [105/204]
void ENTF90 (LBOUNDA2 , lbounda2)
Definition at line 2128 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [106/204]
void ENTF90 (LBOUNDA4 , lbounda4)
Definition at line 2147 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [107/204]
void ENTF90 (LBOUNDA8 , lbounda8)
Definition at line 2166 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [108/204]
void ENTF90 (LBOUNDAZ , lboundaz)
Definition at line 2328 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [109/204]
void ENTF90 (LBOUNDAZ1 , lboundaz1)
Definition at line 2347 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [110/204]
void ENTF90 (LBOUNDAZ2 , lboundaz2)
Definition at line 2366 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [111/204]
void ENTF90 (LBOUNDAZ4 , lboundaz4)
Definition at line 2385 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [112/204]
void ENTF90 (LBOUNDAZ8 , lboundaz8)
Definition at line 2404 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [113/204]
__INT_T ENTF90 (LEN , len)
Definition at line 353 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, ENTF90(), and s.
ENTF90() [114/204]
__INT_T ENTF90 (LENA , lena)
Definition at line 347 of file miscsup_com.c.
References CLEN, and s.
ENTF90() [115/204]
__INT_T ENTF90 (LENTRIM , lentrim)
Definition at line 3094 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, ENTF90(), and str.
ENTF90() [116/204]
__INT_T ENTF90 (LENTRIMA , lentrima)
Definition at line 3083 of file miscsup_com.c.
References CADR, CLEN, i, and str.
ENTF90() [117/204]
void * ENTF90 (LOC , loc)
Definition at line 232 of file miscsup_com.c.
References p.
ENTF90() [118/204]
__LOG1_T ENTF90 (LOG1 , log1)
Definition at line 3662 of file miscsup_com.c.
References __fort_abort(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, a, GET_DIST_MASK_LOG1, GET_DIST_MASK_LOG2, GET_DIST_MASK_LOG4, GET_DIST_MASK_LOG8, and GET_DIST_TRUE_LOG1.
ENTF90() [119/204]
__LOG2_T ENTF90 (LOG2 , log2)
Definition at line 3688 of file miscsup_com.c.
References __fort_abort(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, a, GET_DIST_MASK_LOG1, GET_DIST_MASK_LOG2, GET_DIST_MASK_LOG4, GET_DIST_MASK_LOG8, and GET_DIST_TRUE_LOG2.
ENTF90() [120/204]
__LOG4_T ENTF90 (LOG4 , log4)
Definition at line 3714 of file miscsup_com.c.
References __fort_abort(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, a, GET_DIST_MASK_LOG1, GET_DIST_MASK_LOG2, GET_DIST_MASK_LOG4, GET_DIST_MASK_LOG8, and GET_DIST_TRUE_LOG4.
ENTF90() [121/204]
__LOG8_T ENTF90 (LOG8 , log8)
Definition at line 3740 of file miscsup_com.c.
References __fort_abort(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, a, GET_DIST_MASK_LOG1, GET_DIST_MASK_LOG2, GET_DIST_MASK_LOG4, GET_DIST_MASK_LOG8, and GET_DIST_TRUE_LOG8.
ENTF90() [122/204]
void ENTF90 (MAX , max)
Definition at line 288 of file miscsup_com.c.
References __CLEN_T(), i, j, nargs, NULL, and result.
ENTF90() [123/204]
__INT4_T ENTF90 (MAX0 , max0)
Definition at line 3460 of file miscsup_com.c.
References a, and b.
ENTF90() [124/204]
void ENTF90 (MCOPYZ16 , mcopyz16)
Definition at line 5317 of file miscsup_com.c.
References __c_mcopy8(), d, and size.
ENTF90() [125/204]
void ENTF90 (MCOPYZ8 , mcopyz8)
Definition at line 5309 of file miscsup_com.c.
References __c_mcopy4(), d, and size.
ENTF90() [126/204]
void ENTF90 (MERGECH , mergech)
Definition at line 2988 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, ENTF90(), and result.
ENTF90() [127/204]
void ENTF90 (MERGECHA , mergecha)
Definition at line 2977 of file miscsup_com.c.
References __fort_varying_log(), CADR, CLEN, fstrcpy(), I8, and result.
ENTF90() [128/204]
void ENTF90 (MERGEDT , mergedt)
Definition at line 2998 of file miscsup_com.c.
References __fort_bcopy(), __fort_varying_log(), I8, result, and size.
ENTF90() [129/204]
void ENTF90 (MIN , min)
Definition at line 245 of file miscsup_com.c.
References __CLEN_T(), i, j, nargs, NULL, and result.
ENTF90() [130/204]
__INT4_T ENTF90 (MIN0 , min0)
Definition at line 3466 of file miscsup_com.c.
References a, and b.
ENTF90() [131/204]
__INT4_T ENTF90 (MOD , mod)
Definition at line 3469 of file miscsup_com.c.
References a, and b.
ENTF90() [132/204]
__INT4_T ENTF90 (MODULO , modulo)
Definition at line 3923 of file miscsup_com.c.
References a, p, q, and r.
ENTF90() [133/204]
__INT4_T ENTF90 (MODULOv , modulov)
Definition at line 3994 of file miscsup_com.c.
References a, p, q, and r.
ENTF90() [134/204]
void ENTF90 (MSETZ16 , msetz16)
Definition at line 5253 of file miscsup_com.c.
References d, i, pd, and size.
ENTF90() [135/204]
void ENTF90 (MSETZ32 , msetz32)
Definition at line 5271 of file miscsup_com.c.
References d, i, pd, and size.
ENTF90() [136/204]
void ENTF90 (MSETZ8 , msetz8)
Definition at line 5235 of file miscsup_com.c.
References d, i, pd, and size.
ENTF90() [137/204]
void ENTF90 (MVBITS , mvbits)
Definition at line 885 of file miscsup_com.c.
References __fort_abort(), __fort_varying_int(), __INT8_T(), f2, fp, I8, len, m2, m4, m8, MVBIT_OVFL, t1, t2, t4, and t8.
ENTF90() [138/204]
void ENTF90 (MZEROZ16 , mzeroz16)
Definition at line 5197 of file miscsup_com.c.
References __c_mzero8(), d, and size.
ENTF90() [139/204]
void ENTF90 (MZEROZ8 , mzeroz8)
Definition at line 5189 of file miscsup_com.c.
References __c_mzero4(), d, and size.
ENTF90() [140/204]
__REAL4_T ENTF90 (NEAREST , nearest)
Definition at line 4672 of file miscsup_com.c.
References ENTF90(), f, and sign.
ENTF90() [141/204]
__REAL8_T ENTF90 (NEARESTD , nearestd)
Definition at line 4700 of file miscsup_com.c.
References d, ENTF90(), and sign.
ENTF90() [142/204]
__REAL8_T ENTF90 (NEARESTDX , nearestdx)
Definition at line 4678 of file miscsup_com.c.
References d, GET_DIST_MASK_LOG, sign, and x.
ENTF90() [143/204]
__REAL4_T ENTF90 (NEARESTX , nearestx)
NEAREST(X,S) has a value equal to the machine representable number distinct from X and nearest to it in the direction of the infinity with the same sign as S.
The 'sign' argument is equal to the fortran logical expression (S .ge. 0.0).
Definition at line 4648 of file miscsup_com.c.
References f, GET_DIST_MASK_LOG, i, sign, and x.
ENTF90() [144/204]
__INT_T ENTF90 (NLEN , nlen)
Definition at line 377 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, ENTF90(), and s.
ENTF90() [145/204]
__INT_T ENTF90 (NLENA , nlena)
Definition at line 371 of file miscsup_com.c.
References CLEN, and s.
ENTF90() [146/204]
__LOG_T ENTF90 (PRESENT , present)
Definition at line 83 of file miscsup_com.c.
References ENTCOMN, GET_DIST_TRUE_LOG, NULL, and p.
Referenced by __INT8_T(), __INT_T(), and ENTF90().
ENTF90() [147/204]
__LOG_T ENTF90 (PRESENT_PTR , present_ptr)
Definition at line 102 of file miscsup_com.c.
References ENTCOMN, GET_DIST_TRUE_LOG, NULL, and p.
ENTF90() [148/204]
__LOG_T ENTF90 (PRESENTC , presentc)
Definition at line 140 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, ENTF90(), and p.
ENTF90() [149/204]
__LOG_T ENTF90 (PRESENTCA , presentca)
Definition at line 126 of file miscsup_com.c.
References ABSENTC, CADR, GET_DIST_TRUE_LOG, NULL, and p.
ENTF90() [150/204]
__REAL_T ENTF90 (REAL , real)
Definition at line 3766 of file miscsup_com.c.
References __CPLX16, __CPLX8, __fort_abort(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL4, __REAL8, a, and r.
ENTF90() [151/204]
__REAL4_T ENTF90 (REAL4 , real4)
Definition at line 3834 of file miscsup_com.c.
References __CPLX16, __CPLX8, __fort_abort(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL4, __REAL8, a, and r.
ENTF90() [152/204]
__REAL8_T ENTF90 (REAL8 , real8)
Definition at line 3868 of file miscsup_com.c.
References __CPLX16, __CPLX8, __fort_abort(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL4, __REAL8, a, and r.
ENTF90() [153/204]
__REAL4_T ENTF90 (RRSPACING , rrspacing)
Definition at line 4766 of file miscsup_com.c.
References ENTF90().
ENTF90() [154/204]
__REAL8_T ENTF90 (RRSPACINGD , rrspacingd)
Definition at line 4791 of file miscsup_com.c.
References ENTF90().
ENTF90() [155/204]
__REAL8_T ENTF90 (RRSPACINGDX , rrspacingdx)
Definition at line 4772 of file miscsup_com.c.
References d, x, and y.
ENTF90() [156/204]
__REAL4_T ENTF90 (RRSPACINGX , rrspacingx)
Definition at line 4746 of file miscsup_com.c.
References f, i, x, and y.
ENTF90() [157/204]
__REAL4_T ENTF90 (SCALE , scale)
Definition at line 4846 of file miscsup_com.c.
References __fort_varying_int(), e, f, i, I8, size, and x.
ENTF90() [158/204]
__REAL8_T ENTF90 (SCALED , scaled)
Definition at line 4880 of file miscsup_com.c.
References __fort_varying_int(), d, e, i, I8, size, and x.
ENTF90() [159/204]
__REAL8_T ENTF90 (SCALEDX , scaledx)
Definition at line 4864 of file miscsup_com.c.
References d, e, i, and x.
ENTF90() [160/204]
__REAL4_T ENTF90 (SCALEX , scalex)
Definition at line 4828 of file miscsup_com.c.
References e, f, i, and x.
ENTF90() [161/204]
__REAL4_T ENTF90 (SETEXP , setexp)
Definition at line 4961 of file miscsup_com.c.
References __fort_varying_int(), e, f, i, I8, size, x, and y.
ENTF90() [162/204]
__REAL8_T ENTF90 (SETEXPD , setexpd)
Definition at line 5013 of file miscsup_com.c.
References __fort_varying_int(), d, e, i, I8, size, x, and y.
ENTF90() [163/204]
__REAL8_T ENTF90 (SETEXPDX , setexpdx)
Definition at line 4988 of file miscsup_com.c.
References d, e, i, x, and y.
ENTF90() [164/204]
__REAL4_T ENTF90 (SETEXPX , setexpx)
Definition at line 4934 of file miscsup_com.c.
References e, f, i, x, and y.
ENTF90() [165/204]
void ENTF90 (SHAPE , shape)
Definition at line 2684 of file miscsup_com.c.
References __fort_abort(), d, extent(), ISPRESENT, lwb, rank, stride, upb, and va.
ENTF90() [166/204]
void ENTF90 (SHAPE1 , shape1)
Definition at line 2709 of file miscsup_com.c.
References __fort_abort(), d, extent(), ISPRESENT, lwb, rank, stride, upb, and va.
ENTF90() [167/204]
void ENTF90 (SHAPE2 , shape2)
Definition at line 2734 of file miscsup_com.c.
References __fort_abort(), d, extent(), ISPRESENT, lwb, rank, stride, upb, and va.
ENTF90() [168/204]
void ENTF90 (SHAPE4 , shape4)
Definition at line 2759 of file miscsup_com.c.
References __fort_abort(), d, extent(), ISPRESENT, lwb, rank, stride, upb, and va.
ENTF90() [169/204]
void ENTF90 (SHAPE8 , shape8)
Definition at line 2784 of file miscsup_com.c.
References __fort_abort(), d, extent(), ISPRESENT, lwb, rank, stride, upb, and va.
ENTF90() [170/204]
__INT_T ENTF90 (SIZE , size)
Definition at line 2566 of file miscsup_com.c.
References __fort_abort(), d, dim, extent(), ISPRESENT, lwb, rank, stride, upb, and va.
ENTF90() [171/204]
__REAL4_T ENTF90 (SPACING , spacing)
Definition at line 5113 of file miscsup_com.c.
References ENTF90().
ENTF90() [172/204]
__REAL8_T ENTF90 (SPACINGD , spacingd)
Definition at line 5134 of file miscsup_com.c.
References ENTF90().
ENTF90() [173/204]
__REAL8_T ENTF90 (SPACINGDX , spacingdx)
Definition at line 5119 of file miscsup_com.c.
References d, e, and x.
ENTF90() [174/204]
__REAL4_T ENTF90 (SPACINGX , spacingx)
Definition at line 5096 of file miscsup_com.c.
References e, f, i, and x.
ENTF90() [175/204]
__INT_T ENTF90 (UB , ub)
Definition at line 1125 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, lb, rank, ub, and va.
ENTF90() [176/204]
__INT1_T ENTF90 (UB1 , ub1)
Definition at line 1148 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, lb, rank, ub, and va.
ENTF90() [177/204]
__INT2_T ENTF90 (UB2 , ub2)
Definition at line 1171 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, lb, rank, ub, and va.
ENTF90() [178/204]
__INT4_T ENTF90 (UB4 , ub4)
Definition at line 1194 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, lb, rank, ub, and va.
ENTF90() [179/204]
__INT8_T ENTF90 (UB8 , ub8)
Definition at line 1217 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, lb, rank, ub, and va.
ENTF90() [180/204]
void ENTF90 (UBA , uba)
Definition at line 1423 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [181/204]
void ENTF90 (UBA1 , uba1)
Definition at line 1444 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [182/204]
void ENTF90 (UBA2 , uba2)
Definition at line 1465 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [183/204]
void ENTF90 (UBA4 , uba4)
Definition at line 1486 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [184/204]
void ENTF90 (UBA8 , uba8)
Definition at line 1507 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [185/204]
void ENTF90 (UBAZ , ubaz)
Definition at line 1708 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [186/204]
void ENTF90 (UBAZ1 , ubaz1)
Definition at line 1729 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [187/204]
void ENTF90 (UBAZ2 , ubaz2)
Definition at line 1750 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [188/204]
void ENTF90 (UBAZ4 , ubaz4)
Definition at line 1771 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [189/204]
void ENTF90 (UBAZ8 , ubaz8)
Definition at line 1792 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, lb, s, size, ub, and va.
ENTF90() [190/204]
__INT_T ENTF90 (UBOUND , ubound)
Definition at line 1965 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, rank, and va.
ENTF90() [191/204]
__INT1_T ENTF90 (UBOUND1 , ubound1)
Definition at line 1985 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, rank, and va.
ENTF90() [192/204]
__INT2_T ENTF90 (UBOUND2 , ubound2)
Definition at line 2005 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, rank, and va.
ENTF90() [193/204]
__INT4_T ENTF90 (UBOUND4 , ubound4)
Definition at line 2025 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, rank, and va.
ENTF90() [194/204]
__INT8_T ENTF90 (UBOUND8 , ubound8)
Definition at line 2045 of file miscsup_com.c.
References __fort_abort(), d, dim, ISPRESENT, rank, and va.
ENTF90() [195/204]
void ENTF90 (UBOUNDA , ubounda)
Definition at line 2209 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [196/204]
void ENTF90 (UBOUNDA1 , ubounda1)
Definition at line 2228 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [197/204]
void ENTF90 (UBOUNDA2 , ubounda2)
Definition at line 2247 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [198/204]
void ENTF90 (UBOUNDA4 , ubounda4)
Definition at line 2266 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [199/204]
void ENTF90 (UBOUNDA8 , ubounda8)
Definition at line 2285 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [200/204]
void ENTF90 (UBOUNDAZ , uboundaz)
Definition at line 2447 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [201/204]
void ENTF90 (UBOUNDAZ1 , uboundaz1)
Definition at line 2466 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [202/204]
void ENTF90 (UBOUNDAZ2 , uboundaz2)
Definition at line 2485 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [203/204]
void ENTF90 (UBOUNDAZ4 , uboundaz4)
Definition at line 2504 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTF90() [204/204]
void ENTF90 (UBOUNDAZ8 , uboundaz8)
Definition at line 2523 of file miscsup_com.c.
References __fort_abort(), ISPRESENT, s, size, and va.
ENTFTN() [1/20]
void ENTFTN (CPU_TIME , cpu_time)
Definition at line 540 of file miscsup_com.c.
References __fort_second(), res, TIME_THRESHOLD1, TIME_THRESHOLD2, and x.
ENTFTN() [2/20]
void ENTFTN (CPU_TIMED , cpu_timed)
Definition at line 557 of file miscsup_com.c.
References __fort_second(), res, TIME_THRESHOLD1, TIME_THRESHOLD2, and x.
ENTFTN() [3/20]
void ENTFTN (DANDT , dandt)
Definition at line 812 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, and ENTFTN().
ENTFTN() [4/20]
void ENTFTN (DANDTA , dandta)
Definition at line 707 of file miscsup_com.c.
References __DESC, __fort_local_address(), __io_stderr(), __io_timezone(), c, CADR, CLEN, DIM_UBOUND_G, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, fstrcpy(), i, I8, index, ISPRESENT, ISPRESENTC, localtime(), MP_P, MP_V, next_index(), NULL, sem, store_mxint_t(), t, and timezone.
ENTFTN() [5/20]
void ENTFTN (DATE , date)
Definition at line 477 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, and ENTFTN().
ENTFTN() [6/20]
void ENTFTN (DATEA , datea)
Definition at line 460 of file miscsup_com.c.
References CADR, CLEN, fstrcpy(), localtime(), lt, month, MP_P, MP_V, sem, time, and yr2().
ENTFTN() [7/20]
void ENTFTN (DATEW , datew)
Definition at line 483 of file miscsup_com.c.
References fstrcpy(), localtime(), lt, month, MP_P, MP_V, sem, time, and yr2().
ENTFTN() [8/20]
void ENTFTN (FTIME , ftime)
Definition at line 669 of file miscsup_com.c.
References __CLEN_T(), CADR, CLEN, and ENTFTN().
ENTFTN() [9/20]
void ENTFTN (FTIMEA , ftimea)
Definition at line 652 of file miscsup_com.c.
References CADR, CLEN, fstrcpy(), localtime(), MP_P, MP_V, sem, and time.
ENTFTN() [10/20]
void ENTFTN (FTIMEW , ftimew)
Definition at line 675 of file miscsup_com.c.
References fstrcpy(), localtime(), MP_P, MP_V, sem, and time.
ENTFTN() [11/20]
void ENTFTN (IDATE , idate)
Definition at line 517 of file miscsup_com.c.
References i, j, k, localtime(), MP_P, MP_V, sem, time, and yr2().
ENTFTN() [12/20]
__INT_T ENTFTN (ILEN , ilen)
Definition at line 43 of file miscsup_com.c.
References __fort_varying_int(), i, I8, k, and size.
Referenced by ENTFTN().
ENTFTN() [13/20]
void ENTFTN (JDATE , jdate)
Definition at line 500 of file miscsup_com.c.
References i, j, k, localtime(), MP_P, MP_V, sem, time, and yr2().
ENTFTN() [14/20]
__INT_T ENTFTN (LEADZ , leadz)
Definition at line 3336 of file miscsup_com.c.
References __fort_varying_int(), i, I8, k, and size.
ENTFTN() [15/20]
__INT_T ENTFTN (POPCNT , popcnt)
Definition at line 3366 of file miscsup_com.c.
References __fort_abort(), i, and size.
ENTFTN() [16/20]
__INT_T ENTFTN (POPPAR , poppar)
Definition at line 3417 of file miscsup_com.c.
References __fort_abort(), i, and size.
ENTFTN() [17/20]
__REAL4_T ENTFTN (SECNDS , secnds)
Definition at line 596 of file miscsup_com.c.
References __REAL4_T(), called, f, i, localtime(), lt, MP_P, MP_V, sem, time, and x.
ENTFTN() [18/20]
__REAL8_T ENTFTN (SECNDSD , secndsd)
Definition at line 624 of file miscsup_com.c.
References __REAL8_T(), called, f, i, localtime(), lt, MP_P, MP_V, sem, time, and x.
ENTFTN() [19/20]
void ENTFTN (SYSCLK , sysclk)
Definition at line 823 of file miscsup_com.c.
References __fort_abort(), __fort_getoptn(), __fort_second(), __fort_set_second(), count, def, GET_DIST_SIZE_OF, ISPRESENT, mxint(), store_mxint_t(), sz, t, and TYPEKIND.
ENTFTN() [20/20]
__INT_T ENTFTN (TRAILZ , trailz)
Definition at line 3358 of file miscsup_com.c.
References __fort_varying_int(), i, I8, and size.
fstrcpy()
static void fstrcpy (char * s1, char * s2, __CLEN_T len1, __CLEN_T len2) static
Definition at line 432 of file miscsup_com.c.
References __CLEN_T(), and i.
Referenced by ENTF90(), and ENTFTN().
MP_SEMAPHORE()
MP_SEMAPHORE (static , sem)
mxint()
static MXINT_T mxint (F90_Desc * bd) static
helper function to store the STAT_T value into a varying int
Definition at line 5377 of file miscsup_com.c.
References __INT1, __INT1_T(), __INT2, __INT2_T(), __INT4, __INT4_T(), __INT8, __INT8_T(), __LOG1, __LOG2, __LOG4, __LOG8, and TYPEKIND.
Referenced by ENTFTN().
next_index()
static int I8() next_index (__INT_T * index, F90_Desc * s) static
Definition at line 692 of file miscsup_com.c.
References DIM_UBOUND_G, F90_DIM_LBOUND_G, F90_RANK_G, i, index, and s.
Referenced by ENTFTN().
store_mxint_t()
static void store_mxint_t (void * b, F90_Desc * bd, MXINT_T v) static
helper function to store the MXINT_T value into a simple numerical type
Definition at line 5340 of file miscsup_com.c.
References __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __REAL16, __REAL4, __REAL8, b, and TYPEKIND.
Referenced by ENTFTN().
yr2()
static int yr2 (int yr) static
Definition at line 451 of file miscsup_com.c.
References y.
Referenced by ENTFTN().
Variable Documentation
month
const char* month[12] static
Initial value:
= {"Jan", "Feb", "Mar", "Apr", "May", "Jun",
                                "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"}
Definition at line 447 of file miscsup_com.c.
Referenced by ENTFTN(), and Ftn_date().