flang: mmcmplx16.c File Reference
mmcmplx16.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "complex.h"
#include "mthdecls.h"
Macros
#define SMALL_ROWSA 10
#define SMALL_ROWSB 10
#define SMALL_COLSB 10
Functions
void ftn_mvmul_cmplx16_ (int *, int *, __POINT_T *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, DOUBLE_COMPLEX_TYPE *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, DOUBLE_COMPLEX_TYPE *, DOUBLE_COMPLEX_TYPE *)
void ftn_vmmul_cmplx16_ (int *, int *, __POINT_T *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, DOUBLE_COMPLEX_TYPE *, DOUBLE_COMPLEX_TYPE *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, DOUBLE_COMPLEX_TYPE *)
void ftn_mnaxnb_cmplx16_ (__POINT_T *, __POINT_T *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, DOUBLE_COMPLEX_TYPE *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, DOUBLE_COMPLEX_TYPE *, __POINT_T *)
void ftn_mnaxtb_cmplx16_ (__POINT_T *, __POINT_T *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, DOUBLE_COMPLEX_TYPE *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, DOUBLE_COMPLEX_TYPE *, __POINT_T *)
void ftn_mtaxnb_cmplx16_ (__POINT_T *, __POINT_T *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, DOUBLE_COMPLEX_TYPE *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, DOUBLE_COMPLEX_TYPE *, __POINT_T *)
void ftn_mtaxtb_cmplx16_ (__POINT_T *, __POINT_T *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, DOUBLE_COMPLEX_TYPE *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, __POINT_T *, DOUBLE_COMPLEX_TYPE *, DOUBLE_COMPLEX_TYPE *, __POINT_T *)
void ENTF90 (MMUL_CMPLX16, mmul_cmplx16)
Macro Definition Documentation
SMALL_COLSB
#define SMALL_COLSB 10
Definition at line 17 of file mmcmplx16.c.
SMALL_ROWSA
#define SMALL_ROWSA 10
Definition at line 15 of file mmcmplx16.c.
SMALL_ROWSB
#define SMALL_ROWSB 10
Definition at line 16 of file mmcmplx16.c.
Function Documentation
ENTF90()
void ENTF90 (MMUL_CMPLX16 , mmul_cmplx16)
Definition at line 49 of file mmcmplx16.c.
References a, alpha(), b, DOUBLE_COMPLEX_ADD_CC, DOUBLE_COMPLEX_CREATE, DOUBLE_COMPLEX_EQ_CC, DOUBLE_COMPLEX_MUL_CC, DOUBLE_COMPLEX_TYPE, ftn_mnaxnb_cmplx16_(), ftn_mnaxtb_cmplx16_(), ftn_mtaxnb_cmplx16_(), ftn_mtaxtb_cmplx16_(), ftn_mvmul_cmplx16_(), ftn_vmmul_cmplx16_(), i, j, k, kab, lda, ldb, ncb, SMALL_COLSB, SMALL_ROWSA, and SMALL_ROWSB.
ftn_mnaxnb_cmplx16_()
void ftn_mnaxnb_cmplx16_ (__POINT_T * , __POINT_T * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , DOUBLE_COMPLEX_TYPE * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , DOUBLE_COMPLEX_TYPE * , __POINT_T *)
Referenced by ENTF90().
ftn_mnaxtb_cmplx16_()
void ftn_mnaxtb_cmplx16_ (__POINT_T * , __POINT_T * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , DOUBLE_COMPLEX_TYPE * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , DOUBLE_COMPLEX_TYPE * , __POINT_T *)
Referenced by ENTF90().
ftn_mtaxnb_cmplx16_()
void ftn_mtaxnb_cmplx16_ (__POINT_T * , __POINT_T * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , DOUBLE_COMPLEX_TYPE * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , DOUBLE_COMPLEX_TYPE * , __POINT_T *)
Referenced by ENTF90().
ftn_mtaxtb_cmplx16_()
void ftn_mtaxtb_cmplx16_ (__POINT_T * , __POINT_T * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , DOUBLE_COMPLEX_TYPE * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , DOUBLE_COMPLEX_TYPE * , __POINT_T *)
Referenced by ENTF90().
ftn_mvmul_cmplx16_()
void ftn_mvmul_cmplx16_ (int * , int * , __POINT_T * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , DOUBLE_COMPLEX_TYPE * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , DOUBLE_COMPLEX_TYPE * , DOUBLE_COMPLEX_TYPE *)
Referenced by ENTF90().
ftn_vmmul_cmplx16_()
void ftn_vmmul_cmplx16_ (int * , int * , __POINT_T * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , DOUBLE_COMPLEX_TYPE * , DOUBLE_COMPLEX_TYPE * , __POINT_T * , DOUBLE_COMPLEX_TYPE * , DOUBLE_COMPLEX_TYPE *)
Referenced by ENTF90().