flang: mmreal8.c File Reference
mmreal8.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
Macros
#define SMALL_ROWSA 10
#define SMALL_ROWSB 10
#define SMALL_COLSB 10
Functions
void ftn_mvmul_real8_ (int *, __POINT_T *, __POINT_T *, double *, double *, __POINT_T *, double *, double *, double *)
void ftn_vmmul_real8_ (int *, __POINT_T *, __POINT_T *, double *, double *, double *, __POINT_T *, double *, double *)
void ftn_mnaxnb_real8_ (__POINT_T *, __POINT_T *, __POINT_T *, double *, double *, __POINT_T *, double *, __POINT_T *, double *, double *, __POINT_T *)
void ftn_mnaxtb_real8_ (__POINT_T *, __POINT_T *, __POINT_T *, double *, double *, __POINT_T *, double *, __POINT_T *, double *, double *, __POINT_T *)
void ftn_mtaxnb_real8_ (__POINT_T *, __POINT_T *, __POINT_T *, double *, double *, __POINT_T *, double *, __POINT_T *, double *, double *, __POINT_T *)
void ftn_mtaxtb_real8_ (__POINT_T *, __POINT_T *, __POINT_T *, double *, double *, __POINT_T *, double *, __POINT_T *, double *, double *, __POINT_T *)
void ENTF90 (MMUL_REAL8, mmul_real8)
Macro Definition Documentation
SMALL_COLSB
#define SMALL_COLSB 10
Definition at line 17 of file mmreal8.c.
SMALL_ROWSA
#define SMALL_ROWSA 10
Definition at line 15 of file mmreal8.c.
SMALL_ROWSB
#define SMALL_ROWSB 10
Definition at line 16 of file mmreal8.c.
Function Documentation
ENTF90()
void ENTF90 (MMUL_REAL8 , mmul_real8)
Definition at line 37 of file mmreal8.c.
References a, alpha(), b, ftn_mnaxnb_real8_(), ftn_mnaxtb_real8_(), ftn_mtaxnb_real8_(), ftn_mtaxtb_real8_(), ftn_mvmul_real8_(), ftn_vmmul_real8_(), i, j, k, kab, lda, ldb, ncb, SMALL_COLSB, SMALL_ROWSA, and SMALL_ROWSB.
ftn_mnaxnb_real8_()
void ftn_mnaxnb_real8_ (__POINT_T * , __POINT_T * , __POINT_T * , double * , double * , __POINT_T * , double * , __POINT_T * , double * , double * , __POINT_T *)
Referenced by ENTF90().
ftn_mnaxtb_real8_()
void ftn_mnaxtb_real8_ (__POINT_T * , __POINT_T * , __POINT_T * , double * , double * , __POINT_T * , double * , __POINT_T * , double * , double * , __POINT_T *)
Referenced by ENTF90().
ftn_mtaxnb_real8_()
void ftn_mtaxnb_real8_ (__POINT_T * , __POINT_T * , __POINT_T * , double * , double * , __POINT_T * , double * , __POINT_T * , double * , double * , __POINT_T *)
Referenced by ENTF90().
ftn_mtaxtb_real8_()
void ftn_mtaxtb_real8_ (__POINT_T * , __POINT_T * , __POINT_T * , double * , double * , __POINT_T * , double * , __POINT_T * , double * , double * , __POINT_T *)
Referenced by ENTF90().
ftn_mvmul_real8_()
void ftn_mvmul_real8_ (int * , __POINT_T * , __POINT_T * , double * , double * , __POINT_T * , double * , double * , double *)
Referenced by ENTF90().
ftn_vmmul_real8_()
void ftn_vmmul_real8_ (int * , __POINT_T * , __POINT_T * , double * , double * , double * , __POINT_T * , double * , double *)
Referenced by ENTF90().