flang: mmreal4.c File Reference
mmreal4.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
Macros
#define SMALL_ROWSA 10
#define SMALL_ROWSB 10
#define SMALL_COLSB 10
Functions
void ftn_mvmul_real4_ (int *, __POINT_T *, __POINT_T *, float *, float *, __POINT_T *, float *, float *, float *)
void ftn_vmmul_real4_ (int *, __POINT_T *, __POINT_T *, float *, float *, float *, __POINT_T *, float *, float *)
void ftn_mnaxnb_real4_ (__POINT_T *, __POINT_T *, __POINT_T *, float *, float *, __POINT_T *, float *, __POINT_T *, float *, float *, __POINT_T *)
void ftn_mnaxtb_real4_ (__POINT_T *, __POINT_T *, __POINT_T *, float *, float *, __POINT_T *, float *, __POINT_T *, float *, float *, __POINT_T *)
void ftn_mtaxnb_real4_ (__POINT_T *, __POINT_T *, __POINT_T *, float *, float *, __POINT_T *, float *, __POINT_T *, float *, float *, __POINT_T *)
void ftn_mtaxtb_real4_ (__POINT_T *, __POINT_T *, __POINT_T *, float *, float *, __POINT_T *, float *, __POINT_T *, float *, float *, __POINT_T *)
void ENTF90 (MMUL_REAL4, mmul_real4)
Macro Definition Documentation
SMALL_COLSB
#define SMALL_COLSB 10
Definition at line 17 of file mmreal4.c.
SMALL_ROWSA
#define SMALL_ROWSA 10
Definition at line 15 of file mmreal4.c.
SMALL_ROWSB
#define SMALL_ROWSB 10
Definition at line 16 of file mmreal4.c.
Function Documentation
ENTF90()
void ENTF90 (MMUL_REAL4 , mmul_real4)
Definition at line 37 of file mmreal4.c.
References a, alpha(), b, ftn_mnaxnb_real4_(), ftn_mnaxtb_real4_(), ftn_mtaxnb_real4_(), ftn_mtaxtb_real4_(), ftn_mvmul_real4_(), ftn_vmmul_real4_(), i, j, k, kab, lda, ldb, ncb, SMALL_COLSB, SMALL_ROWSA, and SMALL_ROWSB.
ftn_mnaxnb_real4_()
void ftn_mnaxnb_real4_ (__POINT_T * , __POINT_T * , __POINT_T * , float * , float * , __POINT_T * , float * , __POINT_T * , float * , float * , __POINT_T *)
Referenced by ENTF90().
ftn_mnaxtb_real4_()
void ftn_mnaxtb_real4_ (__POINT_T * , __POINT_T * , __POINT_T * , float * , float * , __POINT_T * , float * , __POINT_T * , float * , float * , __POINT_T *)
Referenced by ENTF90().
ftn_mtaxnb_real4_()
void ftn_mtaxnb_real4_ (__POINT_T * , __POINT_T * , __POINT_T * , float * , float * , __POINT_T * , float * , __POINT_T * , float * , float * , __POINT_T *)
Referenced by ENTF90().
ftn_mtaxtb_real4_()
void ftn_mtaxtb_real4_ (__POINT_T * , __POINT_T * , __POINT_T * , float * , float * , __POINT_T * , float * , __POINT_T * , float * , float * , __POINT_T *)
Referenced by ENTF90().
ftn_mvmul_real4_()
void ftn_mvmul_real4_ (int * , __POINT_T * , __POINT_T * , float * , float * , __POINT_T * , float * , float * , float *)
Referenced by ENTF90().
ftn_vmmul_real4_()
void ftn_vmmul_real4_ (int * , __POINT_T * , __POINT_T * , float * , float * , float * , __POINT_T * , float * , float *)
Referenced by ENTF90().