flang: mmreal16.c File Reference
mmreal16.c File Reference
#include "fioMacros.h"
Macros
#define SMALL_ROWSA 10
#define SMALL_ROWSB 10
#define SMALL_COLSB 10
Functions
void ftn_mvmul_real16_ (int *, __POINT_T *, __POINT_T *, float128_t *, float128_t *, __POINT_T *, float128_t *, float128_t *, float128_t *)
void ftn_vmmul_real16_ (int *, __POINT_T *, __POINT_T *, float128_t *, float128_t *, float128_t *, __POINT_T *, float128_t *, float128_t *)
void ftn_mnaxnb_real16_ (__POINT_T *, __POINT_T *, __POINT_T *, float128_t *, float128_t *, __POINT_T *, float128_t *, __POINT_T *, float128_t *, float128_t *, __POINT_T *)
void ftn_mnaxtb_real16_ (__POINT_T *, __POINT_T *, __POINT_T *, float128_t *, float128_t *, __POINT_T *, float128_t *, __POINT_T *, float128_t *, float128_t *, __POINT_T *)
void ftn_mtaxnb_real16_ (__POINT_T *, __POINT_T *, __POINT_T *, float128_t *, float128_t *, __POINT_T *, float128_t *, __POINT_T *, float128_t *, float128_t *, __POINT_T *)
void ftn_mtaxtb_real16_ (__POINT_T *, __POINT_T *, __POINT_T *, float128_t *, float128_t *, __POINT_T *, float128_t *, __POINT_T *, float128_t *, float128_t *, __POINT_T *)
void ENTF90 (MMUL_REAL16, mmul_real16)
Macro Definition Documentation
SMALL_COLSB
#define SMALL_COLSB 10
Definition at line 16 of file mmreal16.c.
SMALL_ROWSA
#define SMALL_ROWSA 10
Definition at line 14 of file mmreal16.c.
SMALL_ROWSB
#define SMALL_ROWSB 10
Definition at line 15 of file mmreal16.c.
Function Documentation
ENTF90()
void ENTF90 (MMUL_REAL16 , mmul_real16)
Definition at line 48 of file mmreal16.c.
References a, alpha(), b, ftn_mnaxnb_real16_(), ftn_mnaxtb_real16_(), ftn_mtaxnb_real16_(), ftn_mtaxtb_real16_(), ftn_mvmul_real16_(), ftn_vmmul_real16_(), i, j, k, kab, lda, ldb, ncb, SMALL_COLSB, SMALL_ROWSA, and SMALL_ROWSB.
ftn_mnaxnb_real16_()
void ftn_mnaxnb_real16_ (__POINT_T * , __POINT_T * , __POINT_T * , float128_t * , float128_t * , __POINT_T * , float128_t * , __POINT_T * , float128_t * , float128_t * , __POINT_T *)
Referenced by ENTF90().
ftn_mnaxtb_real16_()
void ftn_mnaxtb_real16_ (__POINT_T * , __POINT_T * , __POINT_T * , float128_t * , float128_t * , __POINT_T * , float128_t * , __POINT_T * , float128_t * , float128_t * , __POINT_T *)
Referenced by ENTF90().
ftn_mtaxnb_real16_()
void ftn_mtaxnb_real16_ (__POINT_T * , __POINT_T * , __POINT_T * , float128_t * , float128_t * , __POINT_T * , float128_t * , __POINT_T * , float128_t * , float128_t * , __POINT_T *)
Referenced by ENTF90().
ftn_mtaxtb_real16_()
void ftn_mtaxtb_real16_ (__POINT_T * , __POINT_T * , __POINT_T * , float128_t * , float128_t * , __POINT_T * , float128_t * , __POINT_T * , float128_t * , float128_t * , __POINT_T *)
Referenced by ENTF90().
ftn_mvmul_real16_()
void ftn_mvmul_real16_ (int * , __POINT_T * , __POINT_T * , float128_t * , float128_t * , __POINT_T * , float128_t * , float128_t * , float128_t *)
Referenced by ENTF90().
ftn_vmmul_real16_()
void ftn_vmmul_real16_ (int * , __POINT_T * , __POINT_T * , float128_t * , float128_t * , float128_t * , __POINT_T * , float128_t * , float128_t *)
Referenced by ENTF90().