flang: mmul.c File Reference
mmul.c File Reference
#include <memory.h>
#include "stdioInterf.h"
#include "fioMacros.h"
#include "fort_vars.h"
Typedefs
typedef void(* mmul_fn) (void *, int, void *, int, int, void *, int, int)
Functions
void ENTFTN (QOPY_IN, qopy_in)
static void dotp_real8 (__REAL8_T *c, int nj, __REAL8_T *a, int ai, int ais, __REAL8_T *b, int bk, int bks)
static void dotp_cplx8 (__CPLX8_T *c, int nj, __CPLX8_T *a, int ai, int ais, __CPLX8_T *b, int bk, int bks)
static void mmul_cplx8 (__CPLX8_T *c, int nj, __CPLX8_T *a, int ai, int ais, __CPLX8_T *b, int bk, int bks)
static void dotp_cplx16 (__CPLX16_T *c, int nj, __CPLX16_T *a, int ai, int ais, __CPLX16_T *b, int bk, int bks)
static void mmul_cplx16 (__CPLX16_T *c, int nj, __CPLX16_T *a, int ai, int ais, __CPLX16_T *b, int bk, int bks)
static void dotp_int1 (__INT1_T *c, int nj, __INT1_T *a, int ai, int ais, __INT1_T *b, int bk, int bks)
static void dotp_int2 (__INT2_T *c, int nj, __INT2_T *a, int ai, int ais, __INT2_T *b, int bk, int bks)
static void dotp_int4 (__INT4_T *c, int nj, __INT4_T *a, int ai, int ais, __INT4_T *b, int bk, int bks)
static void dotp_log1 (__LOG1_T *c, int nj, __LOG1_T *a, int ai, int ais, __LOG1_T *b, int bk, int bks)
static void dotp_log2 (__LOG2_T *c, int nj, __LOG2_T *a, int ai, int ais, __LOG2_T *b, int bk, int bks)
static void dotp_log4 (__LOG4_T *c, int nj, __LOG4_T *a, int ai, int ais, __LOG4_T *b, int bk, int bks)
static void dotp_int8 (__INT8_T *c, int nj, __INT8_T *a, int ai, int ais, __INT8_T *b, int bk, int bks)
static void dotp_log8 (__LOG8_T *c, int nj, __LOG8_T *a, int ai, int ais, __LOG8_T *b, int bk, int bks)
void ENTFTN (DOTPR, dotpr)
static void I8() mmul_mxm (char *cb0, char *ab0, char *bb0, F90_Desc *cs0, F90_Desc *as0, F90_Desc *bs0)
static void I8() mmul_vxm (char *cb0, char *ab0, char *bb0, F90_Desc *cs0, F90_Desc *as0, F90_Desc *bs0)
static void I8() mmul_mxv (char *cb0, char *ab0, char *bb0, F90_Desc *cs0, F90_Desc *as0, F90_Desc *bs0)
void ENTFTN (MATMUL, matmul)
Variables
void(*)() I8 (__fort_g_sum)[__NTYPES]
Recursively compute the index space given a set of subscripts for n dimensions.
void(* __fort_scalar_copy [__NTYPES])(void *rp, void *sp, int len)
static __INT_T _0 = 0
static __INT_T _1 = 1
static __INT_T _2 = 2
Typedef Documentation
mmul_fn
typedef void(* mmul_fn) (void *, int, void *, int, int, void *, int, int)
Definition at line 19 of file mmul.c.
Function Documentation
dotp_cplx16()
static void dotp_cplx16 (__CPLX16_T * c, int nj, __CPLX16_T * a, int ai, int ais, __CPLX16_T * b, int bk, int bks) static
Definition at line 82 of file mmul.c.
References a, and b.
Referenced by ENTFTN().
dotp_cplx8()
static void dotp_cplx8 (__CPLX8_T * c, int nj, __CPLX8_T * a, int ai, int ais, __CPLX8_T * b, int bk, int bks) static
Definition at line 52 of file mmul.c.
References a, and b.
Referenced by ENTFTN().
dotp_int1()
static void dotp_int1 (__INT1_T * c, int nj, __INT1_T * a, int ai, int ais, __INT1_T * b, int bk, int bks) static
Definition at line 112 of file mmul.c.
References a, b, and c.
Referenced by ENTFTN(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
dotp_int2()
static void dotp_int2 (__INT2_T * c, int nj, __INT2_T * a, int ai, int ais, __INT2_T * b, int bk, int bks) static
Definition at line 123 of file mmul.c.
References a, b, and c.
Referenced by ENTFTN(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
dotp_int4()
static void dotp_int4 (__INT4_T * c, int nj, __INT4_T * a, int ai, int ais, __INT4_T * b, int bk, int bks) static
Definition at line 134 of file mmul.c.
References a, b, and c.
Referenced by ENTFTN(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
dotp_int8()
static void dotp_int8 (__INT8_T * c, int nj, __INT8_T * a, int ai, int ais, __INT8_T * b, int bk, int bks) static
Definition at line 190 of file mmul.c.
References a, b, and c.
Referenced by ENTFTN(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
dotp_log1()
static void dotp_log1 (__LOG1_T * c, int nj, __LOG1_T * a, int ai, int ais, __LOG1_T * b, int bk, int bks) static
Definition at line 145 of file mmul.c.
References a, b, GET_DIST_MASK_LOG1, and GET_DIST_TRUE_LOG1.
Referenced by ENTFTN(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
dotp_log2()
static void dotp_log2 (__LOG2_T * c, int nj, __LOG2_T * a, int ai, int ais, __LOG2_T * b, int bk, int bks) static
Definition at line 160 of file mmul.c.
References a, b, GET_DIST_MASK_LOG2, and GET_DIST_TRUE_LOG2.
Referenced by ENTFTN(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
dotp_log4()
static void dotp_log4 (__LOG4_T * c, int nj, __LOG4_T * a, int ai, int ais, __LOG4_T * b, int bk, int bks) static
Definition at line 175 of file mmul.c.
References a, b, GET_DIST_MASK_LOG4, and GET_DIST_TRUE_LOG4.
Referenced by ENTFTN(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
dotp_log8()
static void dotp_log8 (__LOG8_T * c, int nj, __LOG8_T * a, int ai, int ais, __LOG8_T * b, int bk, int bks) static
Definition at line 201 of file mmul.c.
References a, b, GET_DIST_MASK_LOG8, and GET_DIST_TRUE_LOG8.
Referenced by ENTFTN(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
dotp_real8()
static void dotp_real8 (__REAL8_T * c, int nj, __REAL8_T * a, int ai, int ais, __REAL8_T * b, int bk, int bks) static
Definition at line 41 of file mmul.c.
References a, b, and c.
Referenced by ENTFTN(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
ENTFTN() [1/3]
void ENTFTN (DOTPR , dotpr)
Definition at line 217 of file mmul.c.
References _1, __ASSUMED_OVERLAPS, __ASSUMED_SHAPE, __CPLX16, __CPLX8, __DESC, __fort_abort(), __fort_block_bounds(), __fort_copy_out(), __fort_cycle_bounds(), __fort_reduce_section(), __fort_replicate_result(), __fort_scalar_copy, __fort_show_scalar(), __fort_show_section(), __fort_test, __IDENTITY_MAP, __INHERIT, __INT1, __INT2, __INT4, __INT8, __INTENT_IN, __LOG1, __LOG2, __LOG4, __LOG8, __OFF_TEMPLATE, __PRESCRIPTIVE_ALIGN_TARGET, __REAL4, __REAL8, __TRANSCRIPTIVE_DIST_FORMAT, __TRANSCRIPTIVE_DIST_TARGET, ABSENT, cs, DEBUG_MMUL, DECL_DIM_PTRS, DECL_HDR_PTRS, DECL_HDR_VARS, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, dotp_cplx16(), dotp_cplx8(), dotp_int1(), dotp_int2(), dotp_int4(), dotp_int8(), dotp_log1(), dotp_log2(), dotp_log4(), dotp_log8(), dotp_real8(), ENTFTN(), F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, flags, GET_DIST_LCPU, GET_DIST_ZED, I8, is_nonsequential_section(), kind, len, NULL, and SET_DIM_PTRS.
ENTFTN() [2/3]
void ENTFTN (MATMUL , matmul)
Definition at line 1094 of file mmul.c.
References __fort_abort(), cs, F90_RANK_G, I8, mmul_mxm(), mmul_mxv(), and mmul_vxm().
ENTFTN() [3/3]
void ENTFTN (QOPY_IN , qopy_in)
Definition at line 24 of file mmul.c.
References a, b, and c.
Referenced by ENTFTN(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
mmul_cplx16()
static void mmul_cplx16 (__CPLX16_T * c, int nj, __CPLX16_T * a, int ai, int ais, __CPLX16_T * b, int bk, int bks) static
Definition at line 97 of file mmul.c.
References a, and b.
Referenced by mmul_mxm(), mmul_mxv(), and mmul_vxm().
mmul_cplx8()
static void mmul_cplx8 (__CPLX8_T * c, int nj, __CPLX8_T * a, int ai, int ais, __CPLX8_T * b, int bk, int bks) static
Definition at line 67 of file mmul.c.
References a, and b.
Referenced by mmul_mxm(), mmul_mxv(), and mmul_vxm().
mmul_mxm()
static void I8() mmul_mxm (char * cb0, char * ab0, char * bb0, F90_Desc * cs0, F90_Desc * as0, F90_Desc * bs0) static
Definition at line 382 of file mmul.c.
References _0, _1, _2, __ASSUMED_OVERLAPS, __ASSUMED_SHAPE, __CPLX16, __CPLX8, __fort_abort(), __fort_block_bounds(), __fort_copy_out(), __fort_cycle_bounds(), __fort_fills(), __fort_print_local(), __fort_test, __INHERIT, __INT1, __INT2, __INT4, __INT8, __INTENT_IN, __INTENT_OUT, __LOG1, __LOG2, __LOG4, __LOG8, __OFF_TEMPLATE, __PRESCRIPTIVE_ALIGN_TARGET, __REAL4, __REAL8, __TRANSCRIPTIVE_DIST_FORMAT, __TRANSCRIPTIVE_DIST_TARGET, ABSENT, cs, DEBUG_MMUL, DECL_DIM_PTRS, DECL_HDR_PTRS, DECL_HDR_VARS, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, dotp_int1(), dotp_int2(), dotp_int4(), dotp_int8(), dotp_log1(), dotp_log2(), dotp_log4(), dotp_log8(), dotp_real8(), ENTFTN(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, flags, GET_DIST_LCPU, GET_DIST_ZED, I8, is_nonsequential_section(), jn(), kind, len, mmul(), mmul_cplx16(), mmul_cplx8(), and SET_DIM_PTRS.
Referenced by ENTFTN().
mmul_mxv()
static void I8() mmul_mxv (char * cb0, char * ab0, char * bb0, F90_Desc * cs0, F90_Desc * as0, F90_Desc * bs0) static
Definition at line 846 of file mmul.c.
References _0, _1, _2, __ASSUMED_OVERLAPS, __ASSUMED_SHAPE, __CPLX16, __CPLX8, __fort_abort(), __fort_block_bounds(), __fort_copy_out(), __fort_cycle_bounds(), __fort_cyclic_loop(), __fort_describe(), __fort_fills(), __fort_reduce_section(), __fort_replicate_result(), __fort_test, __INHERIT, __INT1, __INT2, __INT4, __INT8, __INTENT_IN, __INTENT_OUT, __LOG1, __LOG2, __LOG4, __LOG8, __OFF_TEMPLATE, __PRESCRIPTIVE_ALIGN_TARGET, __REAL4, __REAL8, __TRANSCRIPTIVE_DIST_FORMAT, __TRANSCRIPTIVE_DIST_TARGET, ABSENT, cs, DEBUG_MMUL, DECL_DIM_PTRS, DECL_HDR_PTRS, DECL_HDR_VARS, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, dotp_int1(), dotp_int2(), dotp_int4(), dotp_int8(), dotp_log1(), dotp_log2(), dotp_log4(), dotp_log8(), dotp_real8(), ENTFTN(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_LSIZE_G, F90_RANK_G, flags, GET_DIST_LCPU, GET_DIST_ZED, I8, is_nonsequential_section(), kind, len, mmul(), mmul_cplx16(), mmul_cplx8(), NULL, and SET_DIM_PTRS.
Referenced by ENTFTN().
mmul_vxm()
static void I8() mmul_vxm (char * cb0, char * ab0, char * bb0, F90_Desc * cs0, F90_Desc * as0, F90_Desc * bs0) static
Definition at line 610 of file mmul.c.
References _0, _1, _2, __ASSUMED_OVERLAPS, __ASSUMED_SHAPE, __CPLX16, __CPLX8, __fort_abort(), __fort_block_bounds(), __fort_copy_out(), __fort_cycle_bounds(), __fort_cyclic_loop(), __fort_fills(), __fort_reduce_section(), __fort_replicate_result(), __INHERIT, __INT1, __INT2, __INT4, __INT8, __INTENT_IN, __INTENT_OUT, __LOG1, __LOG2, __LOG4, __LOG8, __OFF_TEMPLATE, __PRESCRIPTIVE_ALIGN_TARGET, __REAL4, __REAL8, __TRANSCRIPTIVE_DIST_FORMAT, __TRANSCRIPTIVE_DIST_TARGET, ABSENT, cs, DECL_DIM_PTRS, DECL_HDR_PTRS, DECL_HDR_VARS, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, dotp_int1(), dotp_int2(), dotp_int4(), dotp_int8(), dotp_log1(), dotp_log2(), dotp_log4(), dotp_log8(), dotp_real8(), ENTFTN(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_LSIZE_G, F90_RANK_G, flags, GET_DIST_ZED, I8, is_nonsequential_section(), kind, len, mmul(), mmul_cplx16(), mmul_cplx8(), NULL, and SET_DIM_PTRS.
Referenced by ENTFTN().
Variable Documentation
_0
__INT_T _0 = 0 static
Definition at line 215 of file mmul.c.
Referenced by __fort_reverse_array(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
_1
__INT_T _1 = 1 static
Definition at line 215 of file mmul.c.
Referenced by ENTFTN(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
_2
__INT_T _2 = 2 static
Definition at line 215 of file mmul.c.
Referenced by mmul_mxm(), mmul_mxv(), and mmul_vxm().
__fort_scalar_copy
void(* __fort_scalar_copy[__NTYPES])(void *rp, void *sp, int len) (void * rp, void * sp, int len) extern
Referenced by ENTFTN().
I8
static struct type_desc * I8 (__fort_g_sum descp) extern
Recursively compute the index space given a set of subscripts for n dimensions.
Recursively compute the index space given a set of subscripts for n dimensions. The evaluation begins by iterating over the last dimension, recursively evaluating the subscripts of the next (to the left) for each iteration. For a given dimension d's index, subscripts to the left are recursively computed. When the first dimension is reached, the address of the element represented by the current subscript values is passed to the 'eval' function.
The evaluation begins by iterating over the last dimension, recursively evaluating the subscripts of the next (to the left) for each iteration. For a given dimension d's index, subscripts to the left are recursively computed. When the first dimension is reached, the address of the element represented by the current subscript values is passed to the 'eval' function.
Definition at line 1272 of file nmlread.c.
Referenced by __alloc04(), __CLEN_T(), __fort_allocate(), __fort_block_bounds(), __fort_block_loop(), __fort_comm_sked(), __fort_copy(), __fort_copy_out(), __fort_cycle_bounds(), __fort_cyclic_loop(), __fort_deallocate(), __fort_fetch_int_element(), __fort_fetch_int_vector(), __fort_fills(), __fort_gathscat(), __fort_gen_block_bounds(), __fort_get_scalar(), __fort_global_reduce(), __fort_inherit_template(), __fort_kallocate(), __fort_kred_arraylk(), __fort_kred_scalarlk(), __fort_local_allocate(), __fort_local_deallocate(), __fort_local_kallocate(), __fort_print_local(), __fort_print_vector(), __fort_red_array(), __fort_red_arraylk(), __fort_red_scalar(), __fort_red_scalarlk(), __fort_reduce_section(), __fort_replicate_result(), __fort_store_int_element(), __fort_store_int_vector(), __fortio_loop(), __fortio_main(), __INT1_T(), __INT2_T(), __INT4_T(), __INT8_T(), __INT_T(), __io_read(), __io_write(), __LOG1_T(), __LOG2_T(), __LOG4_T(), __LOG8_T(), __LOG_T(), __REAL16_T(), __REAL4_T(), __REAL8_T(), _f90io_nml_write(), assign(), broadcast(), copy_loop(), copy_setup(), copy_xfer(), copy_xfer_loop(), cshift_loop(), DCLEN64(), do_parse(), dtio_assign(), ENTCRF90IO(), ENTF90(), ENTF90COMN(), ENTF90IO(), ENTFTN(), eoshift_loop(), eoshift_scalar(), eval(), eval_dtio(), eval_dtio_sb(), eval_sb(), fetch_vector(), fills_loop(), fillup_sb(), ftn_alloc(), ftn_allocate(), ftn_allocated(), ftn_dealloc(), ftn_deallocate(), gathscat_element(), gathscat_loop(), gathscat_mask_loop(), kmaxloc_common(), kmaxlocs_common(), kminloc_common(), kminlocs_common(), kred_array_loop(), local_copy(), maxloc_common(), maxlocs_common(), minloc_common(), minlocs_common(), mmul_mxm(), mmul_mxv(), mmul_vxm(), nullify(), olap_loop(), olap_recv(), olap_send(), olap_shift(), parse_ref(), print_loop(), prng_loop_d_lf(), prng_loop_d_npb(), prng_loop_r_lf(), prng_loop_r_npb(), ptr_asgn(), ptr_in(), ptr_out(), recopy(), red_array_loop(), red_scalar_loop(), set_fibonacci(), set_npb(), store_element(), store_vector(), store_vector_int(), use_alloc(), and void().