flang: module.c File Reference
module.c File Reference
Fortran module support.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "dtypeutl.h"
#include "semant.h"
#include "symutl.h"
#include "dinit.h"
#include "interf.h"
#include "ast.h"
#include "rte.h"
#include "soc.h"
#include "state.h"
#include "lz.h"
#include "dbg_out.h"
Classes
struct _rename
struct USED
struct mod_index
struct IMPL
struct itemx
Macros
#define MOD_SUFFIX ".mod"
#define VALID_RENAME_SYM(sptr)
#define MAX_FNAME_LEN 2050
#define long_t long
#define LLF "%ld"
#define FIRST_DEV_COMMON 16
#define LAST_DEV_COMMON 28
#define N_MOD_CMN sizeof(mod_cmn) / sizeof(int)
#define NO_PTR XBIT(49, 0x8000)
#define NO_CHARPTR XBIT(58, 0x1)
#define NO_DERIVEDPTR XBIT(58, 0x40000)
Typedefs
typedef struct _rename RENAME
typedef struct mod_index mod_index
typedef struct itemx ITEMX
Enumerations
enum MODULE_ID {
NO_MODULE = 0 , FIRST_MODULE = 3 , ISO_C_MOD = FIRST_MODULE , IEEE_ARITH_MOD ,
IEEE_FEATURES_MOD , ISO_FORTRAN_ENV , NML_MOD , FIRST_USER_MODULE ,
MODULE_ID_MAX = 0x7fffffff
}
Functions
static SPTR get_iso_c_entry (const char *name)
static SPTR get_iso_fortran_entry (const char *name)
static void add_predefined_isoc_module (void)
static void add_predefined_iso_fortran_env_module (void)
static void add_predefined_ieeearith_module (void)
static void apply_use (MODULE_ID)
static int basedtype (int sym)
static void fix_module_common (void)
static void export_public_used_modules (int scopelevel)
static void add_to_common (int cmidx, int mem, int atstart)
static void export_all (void)
static void make_rte_descriptor (int obj, const char *suffix)
static SPTR get_submod_sym (SPTR ancestor_module, SPTR submodule)
static void dbg_dump (const char *, int)
void allocate_refsymbol (int symavl)
static void reinit_refsymbol (int symavl)
void set_modusename (int local, int global)
void use_init (void)
void init_use_stmts (void)
void add_use_stmt ()
Process a "USE module" statement. The module is specified in module_id.
void add_submodule_use (void)
SPTR add_use_rename (SPTR local, SPTR global, LOGICAL is_operator)
Process a USE ONLY statement, optionally renaming 'global' as 'local'. The module is specified in 'module_id'.
static int add_only (int listitem, int save_sem_scope_level)
void apply_use_stmts (void)
static int find_def_in_most_recent_scope (int sptr, LOGICAL is_operator, int save_sem_scope_level)
void add_isoc_intrinsics (void)
void open_module (SPTR use)
Begin processing a USE statement. use - sym ptr of module identifer in use statement Find or create an entry in usedb for it and set 'module_id' to the index.
static SPTR find_entry (const SPTR *entries, const char *name)
void close_module (void)
void mod_combined_name (const char *name)
void mod_combined_index (const char *name)
SPTR begin_module (SPTR id)
SPTR begin_submodule (SPTR id, SPTR ancestor_mod, SPTR parent_submod, SPTR *parent)
LOGICAL get_seen_contains (void)
void mod_implicit (int firstc, int lastc, int dtype)
static void handle_mod_syms_dllexport (void)
void begin_contains (void)
void end_module (void)
static int make_module_common (int idx, int private, int threadprivate, int device, int isconstant, int iscopyin, int islink)
static int add_padding (int sptr, int dtype, ISZ_T padsize, int cmidx)
static int MOD_CMN_IDX (int xpriv, int xchar, int xlong, int xinitd, int thrd_priv, int xdev, int xconst, int xcopyin, int xlink)
static void check_sc (int sptr)
static ISZ_T get_address (int sptr)
LOGICAL has_cuda_data (void)
void mod_fini (void)
void mod_init ()
int mod_add_subprogram (int subp)
void mod_end_subprogram (void)
void mod_end_subprogram_two (void)
void rw_mod_state (RW_ROUTINE, RW_FILE)
void dusedb ()
Variables
static MODULE_ID module_id = NO_MODULE
static LOGICAL seen_contains
struct {
SPTR * iso_c
SPTR * iso_fortran
} pd_mod_entries
struct {
USED * base
MODULE_ID avl
int sz
int * ipasave_modname
int ipasave_avl
int ipasave_sz
} usedb = {NULL, 0, 0, NULL, 0, 0}
static int limitsptr
ref_symbol dbgref_symbol = {NULL, 0, NULL}
static int modu_sym = 0
static FILE * outfile
static FILE * single_outfile = NULL
static const char * single_outfile_name = NULL
static const char * single_outfile_index_name = NULL
static char modu_name [MAXIDLEN+1]
static int mod_lineno
static mod_index * mod_index_list = NULL
struct {
IMPL * base
int avl
int sz
} impl
static int mod_cmn [32]
static int mod_cmn_naln [N_MOD_CMN]
static ITEMX * mdalloc_list
static ITEMX * pointer_list
Detailed Description
Fortran module support.
Definition in file module.c.
Macro Definition Documentation
FIRST_DEV_COMMON
#define FIRST_DEV_COMMON 16
Definition at line 1439 of file module.c.
LAST_DEV_COMMON
#define LAST_DEV_COMMON 28
Definition at line 1440 of file module.c.
LLF
#define LLF "%ld"
Definition at line 1013 of file module.c.
long_t
#define long_t long
Definition at line 1012 of file module.c.
MAX_FNAME_LEN
#define MAX_FNAME_LEN 2050
MOD_SUFFIX
#define MOD_SUFFIX ".mod"
Definition at line 28 of file module.c.
N_MOD_CMN
#define N_MOD_CMN sizeof(mod_cmn) / sizeof(int)
Definition at line 1459 of file module.c.
NO_CHARPTR
#define NO_CHARPTR XBIT(58, 0x1)
Definition at line 2038 of file module.c.
NO_DERIVEDPTR
#define NO_DERIVEDPTR XBIT(58, 0x40000)
Definition at line 2039 of file module.c.
NO_PTR
#define NO_PTR XBIT(49, 0x8000)
Definition at line 2037 of file module.c.
VALID_RENAME_SYM
#define VALID_RENAME_SYM (sptr)
Value:
  (sptr > stb.firstusym &&                                \
   (ST_ISVAR(STYPEG(sptr)) || STYPEG(sptr) == ST_ALIAS || \
    STYPEG(sptr) == ST_PROC || STYPEG(sptr) == ST_MODPROC))
Definition at line 250 of file module.c.
Typedef Documentation
ITEMX
typedef struct itemx ITEMX
mod_index
typedef struct mod_index mod_index
RENAME
typedef struct _rename RENAME
Enumeration Type Documentation
MODULE_ID
enum MODULE_ID
Enumerator
NO_MODULE
FIRST_MODULE
ISO_C_MOD
IEEE_ARITH_MOD
IEEE_FEATURES_MOD
ISO_FORTRAN_ENV
NML_MOD
FIRST_USER_MODULE
MODULE_ID_MAX
Definition at line 31 of file module.c.
Function Documentation
add_isoc_intrinsics()
void add_isoc_intrinsics (void)
Definition at line 805 of file module.c.
References first, i, iso_c_lib_stat(), last, size, and sptr.
Referenced by add_to_be_used_list().
add_only()
static int add_only (int listitem, int save_sem_scope_level) static
Definition at line 297 of file module.c.
References add_symitem(), curr_scope(), get_scope_level(), GSAMEG, is_except_in_scope(), next_scope_sptr(), scope, sptr, and SYMI_SPTR.
Referenced by apply_use().
add_padding()
static int add_padding (int sptr, int dtype, ISZ_T padsize, int cmidx) static
Definition at line 1340 of file module.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_NUMELM, add_to_common(), ADD_UPAST, ADD_UPBD, DT_INT, DTY, get_array_dtype(), get_next_sym(), get_type(), mk_cval(), sptr, SYMNAME, TY_CHAR, and TY_NCHAR.
Referenced by check_sc().
add_predefined_ieeearith_module()
static void add_predefined_ieeearith_module (void) static
Definition at line 822 of file module.c.
References assert, _rename::complete, declsym(), gbl, get_ieee_arith_intrin(), _rename::global, IEEE_ARITH_MOD, _rename::lineno, _rename::local, _rename::next, NULL, pop_sym(), sptr, SYMNAME, TRUE, and usedb.
Referenced by apply_use_stmts().
add_predefined_iso_fortran_env_module()
static void add_predefined_iso_fortran_env_module (void) static
Definition at line 768 of file module.c.
References _rename::complete, declsym(), gbl, get_iso_fortran_entry(), _rename::global, i, ISO_FORTRAN_ENV, _rename::lineno, _rename::local, _rename::next, NULL, pd_mod_entries, pop_sym(), sptr, SYMNAME, TRUE, and usedb.
Referenced by apply_use_stmts().
add_predefined_isoc_module()
static void add_predefined_isoc_module (void) static
Definition at line 722 of file module.c.
References _rename::complete, declsym(), gbl, get_iso_c_entry(), _rename::global, i, ISO_C_MOD, _rename::lineno, _rename::local, _rename::next, NULL, pd_mod_entries, pop_sym(), sptr, SYMNAME, TRUE, and usedb.
Referenced by apply_use_stmts().
add_submodule_use()
void add_submodule_use (void)
Definition at line 243 of file module.c.
References assert, ERR_Fatal, module_id, NO_MODULE, TRUE, and usedb.
Referenced by semant1().
add_to_common()
static void add_to_common (int cmidx, int mem, int atstart) static
Definition at line 2178 of file module.c.
References addr, ALIGN, alignment_of_var(), SOC::avail, SOC::base, CMEMLG, CMEMLP, ISZ_T, mem(), mod_cmn, mod_cmn_naln, modu_sym, msz, NEED, NOSYM, p, pad_cmn_mem(), PDALNG, PDALNP, s, size, SOC::size, size_of_var(), soc, SOC_NEXT, SOC_SPTR, sptr, and XBIT.
Referenced by add_padding(), check_sc(), fix_module_common(), and make_rte_descriptor().
add_use_rename()
SPTR add_use_rename (SPTR local, SPTR global, LOGICAL is_operator)
Process a USE ONLY statement, optionally renaming 'global' as 'local'. The module is specified in 'module_id'.
Returns
The updated global symbol.
The USE statement can be any of these forms: USE module, ONLY: global USE module, ONLY: local => global USE module, ONLY: OPERATOR(.xx.) USE module, ONLY: ASSIGNMENT(=) is_operator is set for the last two.
Definition at line 267 of file module.c.
References assert, _rename::complete, FLG::debug, ERR_Fatal, flg, gbl, getitem(), _rename::global, _rename::is_operator, _rename::lineno, _rename::local, module_id, _rename::next, NO_MODULE, NOSYM, set_modusename(), SPTR_NULL, SYMNAME, USE_AREA, and usedb.
Referenced by semant1().
add_use_stmt()
void add_use_stmt (void)
Process a "USE module" statement. The module is specified in module_id.
Definition at line 235 of file module.c.
References assert, ERR_Fatal, module_id, NO_MODULE, TRUE, and usedb.
Referenced by semant1().
allocate_refsymbol()
void allocate_refsymbol (int symavl)
Definition at line 110 of file module.c.
References ref_symbol::altname, BZERO, dbgref_symbol, malloc(), NULL, ref_symbol::size, and ref_symbol::symnum.
Referenced by plower(), and set_modusename().
apply_use()
static void apply_use (MODULE_ID m_id) static
Definition at line 516 of file module.c.
References add_only(), add_symitem(), adjust_symbol_accessibility(), _rename::complete, copy_specifics(), curr_scope(), STB::curr_scope, dbg_dump(), DBGBIT, e, erremit(), errfatal(), error(), fclose(), FILE, find_def_in_most_recent_scope(), first_hash(), STB::firstosym, STB::firstusym, USED::fullname, gbl, get_scope_level(), _rename::global, GSAMEG, import_module(), INCLUDE_PRIVATES, insert_sym(), SEM::interface, _rename::is_operator, _rename::lineno, _rename::local, SEM::mod_cnt, USED::module, name, _rename::next, next_scope(), next_scope_sptr(), NOSYM, NULL, USED::rename, s, scope, SEM::scope_level, seen_contains, sem, set_exitcode(), sptr, stb, SYMI_NEXT, SYMI_SPTR, SYMNAME, tmpfile(), TRUE, USED::unrestricted, update_use_tree_exceptions(), usedb, SEM::which_pass, and XBIT.
Referenced by apply_use_stmts().
apply_use_stmts()
void apply_use_stmts (void)
Definition at line 352 of file module.c.
References add_predefined_ieeearith_module(), add_predefined_iso_fortran_env_module(), add_predefined_isoc_module(), apply_use(), CNULL, ERR_Severe, error(), exportb, FIRST_USER_MODULE, FREE, freearea(), gbl, EXPORTB::ieee_arith_library, IEEE_ARITH_MOD, SEM::ieee_features, IEEE_FEATURES_MOD, IN_MODULE, SEM::interface, EXPORTB::iso_c_library, ISO_C_MOD, ISO_FORTRAN_ENV, EXPORTB::iso_fortran_env_library, module_id, NEED, NEW, NO_MODULE, NOSYM, NULL, pd_mod_entries, remove_from_use_tree(), SEM::scope_level, sem, SYMNAME, TRUE, USE_AREA, usedb, and XBIT.
Referenced by semant1().
basedtype()
static int basedtype (int sym) static
Definition at line 2168 of file module.c.
References DTY.
Referenced by check_sc(), and component_init_allocd_auto().
begin_contains()
void begin_contains (void)
Definition at line 1174 of file module.c.
References errsev(), FALSE, fix_module_common(), handle_mod_syms_dllexport(), SEM::mod_cnt, save_implicit(), save_module_state1(), save_module_state2(), seen_contains, sem, and TRUE.
Referenced by semant1().
begin_module()
SPTR begin_module (SPTR id)
Definition at line 1056 of file module.c.
References declsym(), FALSE, FUNCLINEP, gbl, impl, init_use_tree(), SEM::mod_dllexport, mod_lineno, modu_name, modu_sym, NEW, NULL, outfile, seen_contains, sem, SYMNAME, and TRUE.
Referenced by begin_submodule(), and semant1().
begin_submodule()
SPTR begin_submodule (SPTR id, SPTR ancestor_mod, SPTR parent_submod, SPTR * parent)
Definition at line 1082 of file module.c.
References begin_module(), ERR_Severe, error(), STB::firstusym, gbl, get_submod_sym(), insert_sym(), NOSYM, parent, stb, and SYMNAME.
Referenced by semant1().
check_sc()
static void check_sc (int sptr) static
Definition at line 1470 of file module.c.
References add_padding(), add_to_common(), SOC::avail, SOC::base, basedtype(), DTY, DTYG, FLANG_FALLTHROUGH, getitem(), idx, ISZ_T, make_module_common(), mdalloc_list, mod_cmn, MOD_CMN_IDX(), NEED, itemx::next, offset, p, PDALNP, pointer_list, SOC::size, size_of(), soc, SOC_NEXT, SOC_SPTR, sptr, TY_CHAR, TY_NCHAR, itemx::val, and XBIT.
Referenced by fix_module_common().
close_module()
void close_module (void)
Definition at line 993 of file module.c.
Referenced by semant1().
dbg_dump()
static void dbg_dump (const char * name, int dbgbit) static
Definition at line 2521 of file module.c.
References DBGBIT, dmp_dtype(), dump_ast(), gbl, name, and symdmp().
Referenced by apply_use(), export_all(), and mod_init().
dusedb()
void dusedb ()
Definition at line 2539 of file module.c.
References FIRST_USER_MODULE, USED::module, USED::rename, USED::submodule, SYMNAME, USED::unrestricted, and usedb.
end_module()
void end_module (void)
Definition at line 1192 of file module.c.
References SEM::accl, astb, ASTB::df, dinit_ftell(), errfatal(), error(), export_all(), export_public_used_modules(), exportb, FALSE, fclose(), STB::firstusym, fix_module_common(), FREE, gbl, handle_mod_syms_dllexport(), EXPORTB::hpf_library, EXPORTB::hpf_local_library, EXPORTB::ieee_arith_library, impl, init_use_tree(), EXPORTB::iso_c_library, EXPORTB::iso_fortran_env_library, SEM::mod_cnt, SEM::mod_public_flag, MOD_SUFFIX, modu_name, modu_sym, NULL, outfile, SEM::scope_level, seen_contains, sem, sptr, stb, SYMNAME, tmpfile(), _accl::type, SEM::which_pass, and XBIT.
Referenced by alpha(), parser(), and semant1().
export_all()
static void export_all (void) static
Definition at line 1929 of file module.c.
References convert_2dollar_signs_to_hyphen(), dbg_dump(), DLL_EXPORT, DLLP, error(), export_module(), gbl, getitem(), SEM::mod_dllexport, mod_index_list, MOD_SUFFIX, modu_name, modu_sym, moddir_list::module_directory, module_directory_list, mod_index::module_name, NULL, mod_index::offset, outfile, p, sem, single_outfile, single_outfile_name, and strlen().
Referenced by end_module().
export_public_used_modules()
static void export_public_used_modules (int scopelevel) static
Definition at line 2412 of file module.c.
References export_public_module(), get_scope(), SEM::mod_public_flag, next_scope(), scope, SEM::scope_stack, SCOPE_USE, and sem.
Referenced by end_module(), and mod_end_subprogram().
find_def_in_most_recent_scope()
static int find_def_in_most_recent_scope (int sptr, LOGICAL is_operator, int save_sem_scope_level) static
Definition at line 449 of file module.c.
References aliased_sym_visible(), curr_scope(), first_hash(), get_scope_level(), is_except_in_scope(), is_private_in_scope(), next_scope_sptr(), NOSYM, scope, and sptr.
Referenced by apply_use().
find_entry()
static SPTR find_entry (const SPTR * entries, const char * name) static
Definition at line 956 of file module.c.
References entries, name, sptr, and SYMNAME.
Referenced by get_iso_c_entry(), and get_iso_fortran_entry().
fix_module_common()
static void fix_module_common (void) static
Definition at line 1718 of file module.c.
References add_to_common(), addr, BZERO, check_sc(), STB::curr_scope, DTY, DTYG, EQV, SEM::eqvlist, error(), STB::firstusym, gbl, get_address(), i, init_named_array_constant(), ISZ_T, make_module_common(), make_rte_descriptor(), mdalloc_list, mod_cmn, mod_cmn_naln, modu_sym, N_MOD_CMN, next, itemx::next, NML_MOD, NOSYM, NULL, p, pointer_list, RU_BDATA, RU_SUBR, s, sem, semfin(), SOC_NEXT, SOC_SPTR, sptr, stb, SYMNAME, TY_CHAR, TY_NCHAR, and itemx::val.
Referenced by begin_contains(), and end_module().
get_address()
static ISZ_T get_address (int sptr) static
Definition at line 1705 of file module.c.
References addr, STB::curr_scope, get_address(), ISZ_T, sptr, and stb.
Referenced by fix_module_common(), and get_address().
get_iso_c_entry()
static SPTR get_iso_c_entry (const char * name) static
Definition at line 970 of file module.c.
References find_entry(), name, pd_mod_entries, and sptr.
Referenced by add_predefined_isoc_module().
get_iso_fortran_entry()
static SPTR get_iso_fortran_entry (const char * name) static
Definition at line 984 of file module.c.
References find_entry(), name, pd_mod_entries, and sptr.
Referenced by add_predefined_iso_fortran_env_module().
get_seen_contains()
LOGICAL get_seen_contains (void)
Definition at line 1114 of file module.c.
References seen_contains.
Referenced by dinit_data(), do_iface_module(), and semant1().
get_submod_sym()
static SPTR get_submod_sym (SPTR ancestor_module, SPTR submodule) static
Definition at line 1108 of file module.c.
References getsymf(), and SYMNAME.
Referenced by begin_submodule().
handle_mod_syms_dllexport()
static void handle_mod_syms_dllexport (void) static
Definition at line 1135 of file module.c.
References DLL_EXPORT, DLLP, STB::firstusym, gbl, SEM::mod_dllexport, sem, sptr, and stb.
Referenced by begin_contains(), and end_module().
has_cuda_data()
LOGICAL has_cuda_data (void)
Definition at line 1912 of file module.c.
References FALSE, FIRST_DEV_COMMON, gbl, LAST_DEV_COMMON, mod_cmn, NOSYM, and TRUE.
init_use_stmts()
void init_use_stmts (void)
Definition at line 221 of file module.c.
References BZERO, FIRST_USER_MODULE, NEW, NULL, and usedb.
Referenced by semant1().
make_module_common()
static int make_module_common (int idx, int private, int threadprivate, int device, int isconstant, int iscopyin, int islink) static
Definition at line 1285 of file module.c.
References CMEMLP, DLL_EXPORT, DLLP, flg, gbl, get_next_sym(), idx, MAXIDLEN, SEM::mod_dllexport, modu_name, NOSYM, sem, FLG::sequence, and XBIT.
Referenced by check_sc(), fix_module_common(), and make_rte_descriptor().
make_rte_descriptor()
static void make_rte_descriptor (int obj, const char * suffix) static
Definition at line 2056 of file module.c.
References add_to_common(), DT_INT, DTYG, F77OUTPUT, get_all_descriptors(), get_static_descriptor(), idx, make_module_common(), mod_cmn, MOD_CMN_IDX(), NO_CHARPTR, NO_DERIVEDPTR, NO_PTR, s, TY_CHAR, TY_NCHAR, and XBIT.
Referenced by fix_module_common().
mod_add_subprogram()
int mod_add_subprogram (int subp)
Definition at line 2298 of file module.c.
References arg, ast_implicit(), aux, count, DLL_EXPORT, DLLP, AUX::dpdsc_base, IMPL::dtype, export_append_sym(), FALSE, IMPL::firstc, FUNCLINEP, gbl, getstring(), i, impl, insert_dup_sym(), IMPL::lastc, SEM::mod_dllexport, modu_name, RU_FUNC, s, sem, setimplicit(), strlen(), SYMNAME, TRUE, and XBIT.
Referenced by semant1().
MOD_CMN_IDX()
static int MOD_CMN_IDX (int xpriv, int xchar, int xlong, int xinitd, int thrd_priv, int xdev, int xconst, int xcopyin, int xlink) static
Definition at line 1442 of file module.c.
Referenced by check_sc(), and make_rte_descriptor().
mod_combined_index()
void mod_combined_index (const char * name)
Definition at line 1047 of file module.c.
References name, and single_outfile_index_name.
Referenced by init().
mod_combined_name()
void mod_combined_name (const char * name)
Definition at line 1038 of file module.c.
References name, and single_outfile_name.
Referenced by init().
mod_end_subprogram()
void mod_end_subprogram (void)
Definition at line 2404 of file module.c.
References export_public_used_modules(), SEM::mod_cnt, SEM::mod_public_level, and sem.
Referenced by do_end_subprogram(), and semant1().
mod_end_subprogram_two()
void mod_end_subprogram_two (void)
Definition at line 2425 of file module.c.
References SEM::accl, arg, aux, AUX::dpdsc_base, STB::firstusym, gbl, i, limitsptr, SEM::mod_cnt, SEM::mod_public_flag, _accl::next, NOSYM, NULL, reset_module_state(), RU_FUNC, sem, sptr, _accl::sptr, stb, and _accl::type.
Referenced by semant1().
mod_fini()
void mod_fini (void)
Definition at line 1994 of file module.c.
References error(), fclose(), gbl, GBL_SIZE_T_FORMAT, LLF, mod_index_list, NULL, p, q, single_outfile, single_outfile_index_name, single_outfile_name, and strlen().
Referenced by finish().
mod_implicit()
void mod_implicit (int firstc, int lastc, int dtype)
Definition at line 1123 of file module.c.
References i, impl, and NEED.
Referenced by semant1().
mod_init()
void mod_init (void)
Definition at line 2277 of file module.c.
References astb, dbg_dump(), exportb, EXPORTB::hmark, i, init_use_tree(), limitsptr, EXPORTB::maxast, SEM::mod_public_level, new_node(), restore_module_state(), SEM::scope_level, sem, stb, and void().
Referenced by semant_init().
open_module()
void open_module (SPTR use)
Begin processing a USE statement. use - sym ptr of module identifer in use statement Find or create an entry in usedb for it and set 'module_id' to the index.
Definition at line 863 of file module.c.
References convert_2dollar_signs_to_hyphen(), erremit(), error(), FALSE, first, FIRST_MODULE, STB::firstusym, gbl, get_module_file_name(), getitem(), i, IEEE_ARITH_MOD, IEEE_FEATURES_MOD, insert_sym(), iso_c_lib_stat(), ISO_C_MOD, ISO_FORTRAN_ENV, last, lookupsymbol(), MAX_FNAME_LEN, MOD_SUFFIX, module_id, name, NEED, NEW, NEWSYM, NOSYM, NULL, pd_mod_entries, SEM::scope_level, sem, set_exitcode(), sptr, stb, strlen(), SYMNAME, use, usedb, and XBIT.
Referenced by semant1().
reinit_refsymbol()
static void reinit_refsymbol (int symavl) static
Definition at line 137 of file module.c.
References ref_symbol::altname, BZERO, dbgref_symbol, FREE, i, module_altname::next, NULL, ref_symbol::size, and ref_symbol::symnum.
Referenced by use_init().
rw_mod_state()
void rw_mod_state (RW_ROUTINE , RW_FILE)
Definition at line 2502 of file module.c.
References BZERO, ISREAD, NEED, NEW, RW_FD, RW_SCALAR, and usedb.
Referenced by rw_host_state().
set_modusename()
void set_modusename (int local, int global)
Definition at line 160 of file module.c.
References allocate_refsymbol(), ref_symbol::altname, dbgref_symbol, malloc(), module_altname::next, NULL, ref_symbol::size, module_altname::sptr, stb, SYMNAME, and ref_symbol::symnum.
Referenced by add_use_rename(), and import_symbol().
use_init()
void use_init (void)
Definition at line 213 of file module.c.
References reinit_refsymbol(), stb, and usedb.
Referenced by semant_init().
Variable Documentation
avl
int avl
Definition at line 81 of file module.c.
base
IMPL* base
Definition at line 80 of file module.c.
dbgref_symbol
ref_symbol dbgref_symbol = {NULL, 0, NULL}
Definition at line 106 of file module.c.
Referenced by allocate_refsymbol(), check_debug_alias(), reinit_refsymbol(), and set_modusename().
struct { ... } impl
Referenced by begin_module(), end_module(), mod_add_subprogram(), and mod_implicit().
ipasave_avl
int ipasave_avl
Definition at line 84 of file module.c.
ipasave_modname
int* ipasave_modname
Definition at line 83 of file module.c.
ipasave_sz
int ipasave_sz
Definition at line 84 of file module.c.
iso_c
SPTR* iso_c
Definition at line 74 of file module.c.
iso_fortran
SPTR* iso_fortran
Definition at line 75 of file module.c.
limitsptr
int limitsptr static
Definition at line 87 of file module.c.
Referenced by export_host_subprogram(), export_module_subprogram(), export_some_args(), export_some_fini(), mod_end_subprogram_two(), and mod_init().
mdalloc_list
ITEMX* mdalloc_list static
Definition at line 1466 of file module.c.
Referenced by check_sc(), and fix_module_common().
mod_cmn
int mod_cmn[32] static
Definition at line 1438 of file module.c.
Referenced by add_to_common(), check_sc(), fix_module_common(), has_cuda_data(), and make_rte_descriptor().
mod_cmn_naln
int mod_cmn_naln[N_MOD_CMN] static
Definition at line 1460 of file module.c.
Referenced by add_to_common(), and fix_module_common().
mod_index_list
mod_index* mod_index_list = NULL static
Definition at line 1020 of file module.c.
Referenced by export_all(), and mod_fini().
mod_lineno
int mod_lineno static
Definition at line 1006 of file module.c.
Referenced by begin_module().
modu_name
char modu_name[MAXIDLEN+1] static
Definition at line 1005 of file module.c.
Referenced by begin_module(), end_module(), export_all(), make_module_common(), and mod_add_subprogram().
modu_sym
int modu_sym = 0 static
Definition at line 1000 of file module.c.
Referenced by add_to_common(), begin_module(), end_module(), export_all(), and fix_module_common().
module_id
MODULE_ID module_id = NO_MODULE static
Definition at line 47 of file module.c.
Referenced by add_submodule_use(), add_use_rename(), add_use_stmt(), apply_use_stmts(), and open_module().
outfile
FILE* outfile static
Definition at line 1001 of file module.c.
Referenced by begin_module(), end_module(), and export_all().
struct { ... } pd_mod_entries
Referenced by add_predefined_iso_fortran_env_module(), add_predefined_isoc_module(), apply_use_stmts(), get_iso_c_entry(), get_iso_fortran_entry(), and open_module().
pointer_list
ITEMX* pointer_list static
Definition at line 1467 of file module.c.
Referenced by check_sc(), and fix_module_common().
seen_contains
LOGICAL seen_contains static
Definition at line 49 of file module.c.
Referenced by apply_use(), begin_contains(), begin_module(), end_module(), and get_seen_contains().
single_outfile
FILE* single_outfile = NULL static
Definition at line 1002 of file module.c.
Referenced by export_all(), and mod_fini().
single_outfile_index_name
const char* single_outfile_index_name = NULL static
Definition at line 1004 of file module.c.
Referenced by mod_combined_index(), and mod_fini().
single_outfile_name
const char* single_outfile_name = NULL static
Definition at line 1003 of file module.c.
Referenced by export_all(), mod_combined_name(), and mod_fini().
sz
int sz
Definition at line 82 of file module.c.
struct { ... } usedb
Referenced by add_predefined_ieeearith_module(), add_predefined_iso_fortran_env_module(), add_predefined_isoc_module(), add_submodule_use(), add_use_rename(), add_use_stmt(), apply_use(), apply_use_stmts(), dusedb(), init_use_stmts(), open_module(), rw_mod_state(), and use_init().