flang: mpalloc.h File Reference
mpalloc.h File Reference
External declarations for libpgc routines defined in mpalloc.c.
#include <stdlib.h>
Functions
void * _mp_malloc (size_t n)
void * _mp_calloc (size_t n, size_t)
void * _mp_realloc (void *p, size_t n)
void _mp_free (void *p)
Detailed Description
External declarations for libpgc routines defined in mpalloc.c.
Definition in file mpalloc.h.
Function Documentation
_mp_calloc()
void * _mp_calloc (size_t n, size_t t)
Definition at line 36 of file mpmalloc.c.
References _mp_p(), _mp_v(), n, p, sem, and t.
_mp_free()
void _mp_free (void * p)
Definition at line 66 of file mpmalloc.c.
References _mp_p(), _mp_v(), p, and sem.
Referenced by __cstr_free(), ENT3F(), Ftn_str_copy(), Ftn_str_copy_klen(), and Ftn_str_free().
_mp_malloc()
void * _mp_malloc (size_t n)
Definition at line 21 of file mpmalloc.c.
References _mp_p(), _mp_v(), malloc(), n, p, and sem.
Referenced by __fstr2cstr(), ENT3F(), Ftn_str_copy(), Ftn_str_copy_klen(), Ftn_str_malloc(), and Ftn_str_malloc_klen().
_mp_realloc()
void * _mp_realloc (void * p, size_t n)
Definition at line 51 of file mpmalloc.c.
References _mp_p(), _mp_v(), n, p, q, and sem.