flang: mth_intrinsics.h File Reference
mth_intrinsics.h File Reference
#include <stdint.h>
#include <complex.h>
#include "float128.h"
#include "mthdecls.h"
Typedefs
typedef float128_t vrq1_t
typedef double vrd1_t
typedef double vrd2_t __attribute__((vector_size(2 *sizeof(double))))
typedef float vrs1_t
typedef int32_t vis1_t
typedef int64_t vid1_t
Functions
vrs4_t __ZGVxN4v__mth_i_vr4 (vrs4_t, float(*)(float))
vrs4_t __ZGVxM4v__mth_i_vr4 (vrs4_t, vis4_t, float(*)(float))
vrs4_t __ZGVxN4vv__mth_i_vr4vr4 (vrs4_t, vrs4_t, float(*)(float, float))
vrs4_t __ZGVxM4vv__mth_i_vr4vr4 (vrs4_t, vrs4_t, vis4_t, float(*)(float, float))
vrd2_t __ZGVxN2v__mth_i_vr8 (vrd2_t, double(*)(double))
vrd2_t __ZGVxM2v__mth_i_vr8 (vrd2_t, vid2_t, double(*)(double))
vrd2_t __ZGVxN2vv__mth_i_vr8vr8 (vrd2_t, vrd2_t, double(*)(double, double))
vrd2_t __ZGVxM2vv__mth_i_vr8vr8 (vrd2_t, vrd2_t, vid2_t, double(*)(double, double))
vrs8_t __ZGVyN8v__mth_i_vr4 (vrs8_t, float(*)(float))
vrs8_t __ZGVyM8v__mth_i_vr4 (vrs8_t, vis8_t, float(*)(float))
vrs8_t __ZGVyN8vv__mth_i_vr4vr4 (vrs8_t, vrs8_t, float(*)(float, float))
vrs8_t __ZGVyM8vv__mth_i_vr4vr4 (vrs8_t, vrs8_t, vis8_t, float(*)(float, float))
vrd4_t __ZGVyN4v__mth_i_vr8 (vrd4_t, double(*)(double))
vrd4_t __ZGVyM4v__mth_i_vr8 (vrd4_t, vid4_t, double(*)(double))
vrd4_t __ZGVyN4vv__mth_i_vr8vr8 (vrd4_t, vrd4_t, double(*)(double, double))
vrd4_t __ZGVyM4vv__mth_i_vr8vr8 (vrd4_t, vrd4_t, vid4_t, double(*)(double, double))
vrs16_t __ZGVzN16v__mth_i_vr4 (vrs16_t, float(*)(float))
vrs16_t __ZGVzM16v__mth_i_vr4 (vrs16_t, vis16_t, float(*)(float))
vrs16_t __ZGVzN16vv__mth_i_vr4vr4 (vrs16_t, vrs16_t, float(*)(float, float))
vrs16_t __ZGVzM16vv__mth_i_vr4vr4 (vrs16_t, vrs16_t, vis16_t, float(*)(float, float))
vrd8_t __ZGVzN8v__mth_i_vr8 (vrd8_t, double(*)(double))
vrd8_t __ZGVzM8v__mth_i_vr8 (vrd8_t, vid8_t, double(*)(double))
vrd8_t __ZGVzN8vv__mth_i_vr8vr8 (vrd8_t, vrd8_t, double(*)(double, double))
vrd8_t __ZGVzM8vv__mth_i_vr8vr8 (vrd8_t, vrd8_t, vid8_t, double(*)(double, double))
vcs1_t __ZGVxN1v__mth_i_vc4 (vcs1_t, _Complex float func(_Complex float))
vcs1_t __ZGVxN1vv__mth_i_vc4vc4 (vcs1_t, vcs1_t, _Complex float func(_Complex float, _Complex float))
vcs2_t __ZGVxN2v__mth_i_vc4 (vcs2_t, _Complex float func(_Complex float))
vcs2_t __ZGVxN2vv__mth_i_vc4vc4 (vcs2_t, vcs2_t, _Complex float func(_Complex float, _Complex float))
vcd1_t __ZGVxN1v__mth_i_vc8 (vcd1_t, _Complex double func(_Complex double))
vcd1_t __ZGVxN1vv__mth_i_vc8vc8 (vcd1_t, vcd1_t, _Complex double func(_Complex double, _Complex double))
vcs4_t __ZGVyN4v__mth_i_vc4 (vcs4_t, _Complex float func(_Complex float))
vcs4_t __ZGVyN4vv__mth_i_vc4vc4 (vcs4_t, vcs4_t, _Complex float func(_Complex float, _Complex float))
vcd2_t __ZGVyN2v__mth_i_vc8 (vcd2_t, _Complex double func(_Complex double))
vcd2_t __ZGVyN2vv__mth_i_vc8vc8 (vcd2_t, vcd2_t, _Complex double func(_Complex double, _Complex double))
vcs8_t __ZGVzN8v__mth_i_vc4 (vcs8_t, _Complex float func(_Complex float))
vcs8_t __ZGVzN8vv__mth_i_vc4vc4 (vcs8_t, vcs8_t, _Complex float func(_Complex float, _Complex float))
vcd4_t __ZGVzN4v__mth_i_vc8 (vcd4_t, _Complex double func(_Complex double))
vcd4_t __ZGVzN4vv__mth_i_vc8vc8 (vcd4_t, vcd4_t, _Complex double func(_Complex double, _Complex double))
vrs4_t __ZGVxN4v__mth_i_vr4si4 (vrs4_t, int32_t, float(*)(float, int32_t))
vrs4_t __ZGVxM4v__mth_i_vr4si4 (vrs4_t, int32_t, vis4_t, float(*)(float, int32_t))
vrs4_t __ZGVxN4vv__mth_i_vr4vi4 (vrs4_t, vis4_t, float(*)(float, int32_t))
vrs4_t __ZGVxM4vv__mth_i_vr4vi4 (vrs4_t, vis4_t, vis4_t, float(*)(float, int32_t))
vrs4_t __ZGVxN4v__mth_i_vr4si8 (vrs4_t, long long, float(*)(float, long long))
vrs4_t __ZGVxM4v__mth_i_vr4si8 (vrs4_t, long long, vis4_t, float(*)(float, long long))
vrs4_t __ZGVxN4vv__mth_i_vr4vi8 (vrs4_t, vid2_t, vid2_t, float(*)(float, long long))
vrs4_t __ZGVxM4vv__mth_i_vr4vi8 (vrs4_t, vid2_t, vid2_t, vis4_t, float(*)(float, long long))
vrd2_t __ZGVxN2v__mth_i_vr8si4 (vrd2_t, int32_t, double(*)(double, int32_t))
vrd2_t __ZGVxM2v__mth_i_vr8si4 (vrd2_t, int32_t, vid2_t, double(*)(double, int32_t))
vrd2_t __ZGVxN2vv__mth_i_vr8vi4 (vrd2_t, vis4_t, double(*)(double, int32_t))
vrd2_t __ZGVxM2vv__mth_i_vr8vi4 (vrd2_t, vis4_t, vid2_t, double(*)(double, int32_t))
vrd2_t __ZGVxN2v__mth_i_vr8si8 (vrd2_t, long long, double(*)(double, long long))
vrd2_t __ZGVxM2v__mth_i_vr8si8 (vrd2_t, long long, vid2_t, double(*)(double, long long))
vrd2_t __ZGVxN2vv__mth_i_vr8vi8 (vrd2_t, vid2_t, double(*)(double, long long))
vrd2_t __ZGVxM2vv__mth_i_vr8vi8 (vrd2_t, vid2_t, vid2_t, double(*)(double, long long))
vrs8_t __ZGVyN8v__mth_i_vr4si4 (vrs8_t, int32_t, float(*)(float, int32_t))
vrs8_t __ZGVyM8v__mth_i_vr4si4 (vrs8_t, int32_t, vis8_t, float(*)(float, int32_t))
vrs8_t __ZGVyN8vv__mth_i_vr4vi4 (vrs8_t, vis8_t, float(*)(float, int32_t))
vrs8_t __ZGVyM8vv__mth_i_vr4vi4 (vrs8_t, vis8_t, vis8_t, float(*)(float, int32_t))
vrs8_t __ZGVyN8v__mth_i_vr4si8 (vrs8_t, long long, float(*)(float, long long))
vrs8_t __ZGVyM8v__mth_i_vr4si8 (vrs8_t, long long, vis8_t, float(*)(float, long long))
vrs8_t __ZGVyN8vv__mth_i_vr4vi8 (vrs8_t, vid4_t, vid4_t, float(*)(float, long long))
vrs8_t __ZGVyM8vv__mth_i_vr4vi8 (vrs8_t, vid4_t, vid4_t, vis8_t, float(*)(float, long long))
vrd4_t __ZGVyN4v__mth_i_vr8si4 (vrd4_t, int32_t, double(*)(double, int32_t))
vrd4_t __ZGVyM4v__mth_i_vr8si4 (vrd4_t, int32_t, vid4_t, double(*)(double, int32_t))
vrd4_t __ZGVyN4vv__mth_i_vr8vi4 (vrd4_t, vis4_t, double(*)(double, int32_t))
vrd4_t __ZGVyM4vv__mth_i_vr8vi4 (vrd4_t, vis4_t, vid4_t, double(*)(double, int32_t))
vrd4_t __ZGVyN4v__mth_i_vr8si8 (vrd4_t, long long, double(*)(double, long long))
vrd4_t __ZGVyM4v__mth_i_vr8si8 (vrd4_t, long long, vid4_t, double(*)(double, long long))
vrd4_t __ZGVyN4vv__mth_i_vr8vi8 (vrd4_t, vid4_t, double(*)(double, long long))
vrd4_t __ZGVyM4vv__mth_i_vr8vi8 (vrd4_t, vid4_t, vid4_t, double(*)(double, long long))
vrs16_t __ZGVzN16v__mth_i_vr4si4 (vrs16_t, int32_t, float(*)(float, int32_t))
vrs16_t __ZGVzM16v__mth_i_vr4si4 (vrs16_t, int32_t, vis16_t, float(*)(float, int32_t))
vrs16_t __ZGVzN16vv__mth_i_vr4vi4 (vrs16_t, vis16_t, float(*)(float, int32_t))
vrs16_t __ZGVzM16vv__mth_i_vr4vi4 (vrs16_t, vis16_t, vis16_t, float(*)(float, int32_t))
vrs16_t __ZGVzN16v__mth_i_vr4si8 (vrs16_t, long long, float(*)(float, long long))
vrs16_t __ZGVzM16v__mth_i_vr4si8 (vrs16_t, long long, vis16_t, float(*)(float, long long))
vrs16_t __ZGVzN16vv__mth_i_vr4vi8 (vrs16_t, vid8_t, vid8_t, float(*)(float, long long))
vrs16_t __ZGVzM16vv__mth_i_vr4vi8 (vrs16_t, vid8_t, vid8_t, vis16_t, float(*)(float, long long))
vrd8_t __ZGVzN8v__mth_i_vr8si4 (vrd8_t, int32_t, double(*)(double, int32_t))
vrd8_t __ZGVzM8v__mth_i_vr8si4 (vrd8_t, int32_t, vid8_t, double(*)(double, int32_t))
vrd8_t __ZGVzN8vv__mth_i_vr8vi4 (vrd8_t, vis8_t, double(*)(double, int32_t))
vrd8_t __ZGVzM8vv__mth_i_vr8vi4 (vrd8_t, vis8_t, vid8_t, double(*)(double, int32_t))
vrd8_t __ZGVzN8v__mth_i_vr8si8 (vrd8_t, long long, double(*)(double, long long))
vrd8_t __ZGVzM8v__mth_i_vr8si8 (vrd8_t, long long, vid8_t, double(*)(double, long long))
vrd8_t __ZGVzN8vv__mth_i_vr8vi8 (vrd8_t, vid8_t, double(*)(double, long long))
vrd8_t __ZGVzM8vv__mth_i_vr8vi8 (vrd8_t, vid8_t, vid8_t, double(*)(double, long long))
vcs1_t __ZGVxN1v__mth_i_vc4si4 (vcs1_t, int32_t, _Complex float func(_Complex float, int32_t))
vcs1_t __ZGVxN1v__mth_i_vc4si8 (vcs1_t, long long, _Complex float func(_Complex float, long long))
vcd1_t __ZGVxN1v__mth_i_vc8si4 (vcd1_t, int32_t, _Complex double func(_Complex double, int32_t))
vcd1_t __ZGVxN1v__mth_i_vc8si8 (vcd1_t, long long, _Complex double func(_Complex double, long long))
Typedef Documentation
__attribute__
typedef int64_t vid8_t __attribute__((vector_size(8 *sizeof(int64_t)))) inline
Definition at line 26 of file mth_intrinsics.h.
vid1_t
typedef int64_t vid1_t
Definition at line 62 of file mth_intrinsics.h.
vis1_t
typedef int32_t vis1_t
Definition at line 57 of file mth_intrinsics.h.
vrd1_t
typedef double vrd1_t
Definition at line 25 of file mth_intrinsics.h.
vrq1_t
typedef float128_t vrq1_t
Definition at line 24 of file mth_intrinsics.h.
vrs1_t
typedef float vrs1_t
Definition at line 29 of file mth_intrinsics.h.
Function Documentation
__ZGVxM2v__mth_i_vr8()
vrd2_t __ZGVxM2v__mth_i_vr8 (vrd2_t , vid2_t , double(*)(double))
__ZGVxM2v__mth_i_vr8si4()
vrd2_t __ZGVxM2v__mth_i_vr8si4 (vrd2_t , int32_t , vid2_t , double(*)(double, int32_t))
Referenced by __px_powi1_2m().
__ZGVxM2v__mth_i_vr8si8()
vrd2_t __ZGVxM2v__mth_i_vr8si8 (vrd2_t , long long , vid2_t , double(*)(double, long long))
Referenced by __px_powk1_2m().
__ZGVxM2vv__mth_i_vr8vi4()
vrd2_t __ZGVxM2vv__mth_i_vr8vi4 (vrd2_t , vis4_t , vid2_t , double(*)(double, int32_t))
Referenced by __px_powi_2m().
__ZGVxM2vv__mth_i_vr8vi8()
vrd2_t __ZGVxM2vv__mth_i_vr8vi8 (vrd2_t , vid2_t , vid2_t , double(*)(double, long long))
Referenced by __px_powk_2m().
__ZGVxM2vv__mth_i_vr8vr8()
vrd2_t __ZGVxM2vv__mth_i_vr8vr8 (vrd2_t , vrd2_t , vid2_t , double(*)(double, double))
Referenced by __gd_atan2_2m().
__ZGVxM4v__mth_i_vr4()
vrs4_t __ZGVxM4v__mth_i_vr4 (vrs4_t , vis4_t , float(*)(float))
Referenced by __gs_atan_4m(), and __gs_cos_4m().
__ZGVxM4v__mth_i_vr4si4()
vrs4_t __ZGVxM4v__mth_i_vr4si4 (vrs4_t , int32_t , vis4_t , float(*)(float, int32_t))
Referenced by __px_powi1_4m().
__ZGVxM4v__mth_i_vr4si8()
vrs4_t __ZGVxM4v__mth_i_vr4si8 (vrs4_t , long long , vis4_t , float(*)(float, long long))
Referenced by __px_powk1_4m().
__ZGVxM4vv__mth_i_vr4vi4()
vrs4_t __ZGVxM4vv__mth_i_vr4vi4 (vrs4_t , vis4_t , vis4_t , float(*)(float, int32_t))
Referenced by __px_powi_4m().
__ZGVxM4vv__mth_i_vr4vi8()
vrs4_t __ZGVxM4vv__mth_i_vr4vi8 (vrs4_t , vid2_t , vid2_t , vis4_t , float(*)(float, long long))
Referenced by __px_powk_4m().
__ZGVxM4vv__mth_i_vr4vr4()
vrs4_t __ZGVxM4vv__mth_i_vr4vr4 (vrs4_t , vrs4_t , vis4_t , float(*)(float, float))
Referenced by __gs_atan2_4m().
__ZGVxN1v__mth_i_vc4()
vcs1_t __ZGVxN1v__mth_i_vc4 (vcs1_t , _Complex float func_Complex float)
Referenced by __gc_atan_1(), __gc_cos_1(), and __gc_sqrt_1().
__ZGVxN1v__mth_i_vc4si4()
vcs1_t __ZGVxN1v__mth_i_vc4si4 (vcs1_t , int32_t , _Complex float func_Complex float, int32_t)
__ZGVxN1v__mth_i_vc4si8()
vcs1_t __ZGVxN1v__mth_i_vc4si8 (vcs1_t , long long , _Complex float func_Complex float, long long)
__ZGVxN1v__mth_i_vc8()
vcd1_t __ZGVxN1v__mth_i_vc8 (vcd1_t , _Complex double func_Complex double)
Referenced by __gz_sqrt_1v().
__ZGVxN1v__mth_i_vc8si4()
vcd1_t __ZGVxN1v__mth_i_vc8si4 (vcd1_t , int32_t , _Complex double func_Complex double, int32_t)
__ZGVxN1v__mth_i_vc8si8()
vcd1_t __ZGVxN1v__mth_i_vc8si8 (vcd1_t , long long , _Complex double func_Complex double, long long)
__ZGVxN1vv__mth_i_vc4vc4()
vcs1_t __ZGVxN1vv__mth_i_vc4vc4 (vcs1_t , vcs1_t , _Complex float func_Complex float, _Complex float)
Referenced by __gc_div_1().
__ZGVxN1vv__mth_i_vc8vc8()
vcd1_t __ZGVxN1vv__mth_i_vc8vc8 (vcd1_t , vcd1_t , _Complex double func_Complex double, _Complex double)
Referenced by __gz_div_1v().
__ZGVxN2v__mth_i_vc4()
vcs2_t __ZGVxN2v__mth_i_vc4 (vcs2_t , _Complex float func_Complex float)
Referenced by __gc_atan_2(), __gc_cos_2(), and __gc_sqrt_2().
__ZGVxN2v__mth_i_vr8()
vrd2_t __ZGVxN2v__mth_i_vr8 (vrd2_t , double(*)(double))
__ZGVxN2v__mth_i_vr8si4()
vrd2_t __ZGVxN2v__mth_i_vr8si4 (vrd2_t , int32_t , double(*)(double, int32_t))
Referenced by __px_powi1_2().
__ZGVxN2v__mth_i_vr8si8()
vrd2_t __ZGVxN2v__mth_i_vr8si8 (vrd2_t , long long , double(*)(double, long long))
Referenced by __px_powk1_2().
__ZGVxN2vv__mth_i_vc4vc4()
vcs2_t __ZGVxN2vv__mth_i_vc4vc4 (vcs2_t , vcs2_t , _Complex float func_Complex float, _Complex float)
Referenced by __gc_div_2().
__ZGVxN2vv__mth_i_vr8vi4()
vrd2_t __ZGVxN2vv__mth_i_vr8vi4 (vrd2_t , vis4_t , double(*)(double, int32_t))
Referenced by __px_powi_2().
__ZGVxN2vv__mth_i_vr8vi8()
vrd2_t __ZGVxN2vv__mth_i_vr8vi8 (vrd2_t , vid2_t , double(*)(double, long long))
Referenced by __px_powk_2().
__ZGVxN2vv__mth_i_vr8vr8()
vrd2_t __ZGVxN2vv__mth_i_vr8vr8 (vrd2_t , vrd2_t , double(*)(double, double))
Referenced by __gd_atan2_2().
__ZGVxN4v__mth_i_vr4()
vrs4_t __ZGVxN4v__mth_i_vr4 (vrs4_t , float(*)(float))
Referenced by __gs_atan_4(), and __gs_cos_4().
__ZGVxN4v__mth_i_vr4si4()
vrs4_t __ZGVxN4v__mth_i_vr4si4 (vrs4_t , int32_t , float(*)(float, int32_t))
Referenced by __px_powi1_4().
__ZGVxN4v__mth_i_vr4si8()
vrs4_t __ZGVxN4v__mth_i_vr4si8 (vrs4_t , long long , float(*)(float, long long))
Referenced by __px_powk1_4().
__ZGVxN4vv__mth_i_vr4vi4()
vrs4_t __ZGVxN4vv__mth_i_vr4vi4 (vrs4_t , vis4_t , float(*)(float, int32_t))
Referenced by __px_powi_4().
__ZGVxN4vv__mth_i_vr4vi8()
vrs4_t __ZGVxN4vv__mth_i_vr4vi8 (vrs4_t , vid2_t , vid2_t , float(*)(float, long long))
Referenced by __px_powk_4().
__ZGVxN4vv__mth_i_vr4vr4()
vrs4_t __ZGVxN4vv__mth_i_vr4vr4 (vrs4_t , vrs4_t , float(*)(float, float))
Referenced by __gs_atan2_4().
__ZGVyM4v__mth_i_vr8()
vrd4_t __ZGVyM4v__mth_i_vr8 (vrd4_t , vid4_t , double(*)(double))
__ZGVyM4v__mth_i_vr8si4()
vrd4_t __ZGVyM4v__mth_i_vr8si4 (vrd4_t , int32_t , vid4_t , double(*)(double, int32_t))
Referenced by __py_powi1_4m().
__ZGVyM4v__mth_i_vr8si8()
vrd4_t __ZGVyM4v__mth_i_vr8si8 (vrd4_t , long long , vid4_t , double(*)(double, long long))
Referenced by __py_powk1_4m().
__ZGVyM4vv__mth_i_vr8vi4()
vrd4_t __ZGVyM4vv__mth_i_vr8vi4 (vrd4_t , vis4_t , vid4_t , double(*)(double, int32_t))
Referenced by __py_powi_4m().
__ZGVyM4vv__mth_i_vr8vi8()
vrd4_t __ZGVyM4vv__mth_i_vr8vi8 (vrd4_t , vid4_t , vid4_t , double(*)(double, long long))
Referenced by __py_powk_4m().
__ZGVyM4vv__mth_i_vr8vr8()
vrd4_t __ZGVyM4vv__mth_i_vr8vr8 (vrd4_t , vrd4_t , vid4_t , double(*)(double, double))
__ZGVyM8v__mth_i_vr4()
vrs8_t __ZGVyM8v__mth_i_vr4 (vrs8_t , vis8_t , float(*)(float))
__ZGVyM8v__mth_i_vr4si4()
vrs8_t __ZGVyM8v__mth_i_vr4si4 (vrs8_t , int32_t , vis8_t , float(*)(float, int32_t))
Referenced by __py_powi1_8m().
__ZGVyM8v__mth_i_vr4si8()
vrs8_t __ZGVyM8v__mth_i_vr4si8 (vrs8_t , long long , vis8_t , float(*)(float, long long))
Referenced by __py_powk1_8m().
__ZGVyM8vv__mth_i_vr4vi4()
vrs8_t __ZGVyM8vv__mth_i_vr4vi4 (vrs8_t , vis8_t , vis8_t , float(*)(float, int32_t))
Referenced by __py_powi_8m().
__ZGVyM8vv__mth_i_vr4vi8()
vrs8_t __ZGVyM8vv__mth_i_vr4vi8 (vrs8_t , vid4_t , vid4_t , vis8_t , float(*)(float, long long))
Referenced by __py_powk_8m().
__ZGVyM8vv__mth_i_vr4vr4()
vrs8_t __ZGVyM8vv__mth_i_vr4vr4 (vrs8_t , vrs8_t , vis8_t , float(*)(float, float))
__ZGVyN2v__mth_i_vc8()
vcd2_t __ZGVyN2v__mth_i_vc8 (vcd2_t , _Complex double func_Complex double)
Referenced by __gz_sqrt_2().
__ZGVyN2vv__mth_i_vc8vc8()
vcd2_t __ZGVyN2vv__mth_i_vc8vc8 (vcd2_t , vcd2_t , _Complex double func_Complex double, _Complex double)
Referenced by __gz_div_2().
__ZGVyN4v__mth_i_vc4()
vcs4_t __ZGVyN4v__mth_i_vc4 (vcs4_t , _Complex float func_Complex float)
Referenced by __gc_sqrt_4().
__ZGVyN4v__mth_i_vr8()
vrd4_t __ZGVyN4v__mth_i_vr8 (vrd4_t , double(*)(double))
__ZGVyN4v__mth_i_vr8si4()
vrd4_t __ZGVyN4v__mth_i_vr8si4 (vrd4_t , int32_t , double(*)(double, int32_t))
Referenced by __py_powi1_4().
__ZGVyN4v__mth_i_vr8si8()
vrd4_t __ZGVyN4v__mth_i_vr8si8 (vrd4_t , long long , double(*)(double, long long))
Referenced by __py_powk1_4().
__ZGVyN4vv__mth_i_vc4vc4()
vcs4_t __ZGVyN4vv__mth_i_vc4vc4 (vcs4_t , vcs4_t , _Complex float func_Complex float, _Complex float)
Referenced by __gc_div_4().
__ZGVyN4vv__mth_i_vr8vi4()
vrd4_t __ZGVyN4vv__mth_i_vr8vi4 (vrd4_t , vis4_t , double(*)(double, int32_t))
Referenced by __py_powi_4().
__ZGVyN4vv__mth_i_vr8vi8()
vrd4_t __ZGVyN4vv__mth_i_vr8vi8 (vrd4_t , vid4_t , double(*)(double, long long))
Referenced by __py_powk_4().
__ZGVyN4vv__mth_i_vr8vr8()
vrd4_t __ZGVyN4vv__mth_i_vr8vr8 (vrd4_t , vrd4_t , double(*)(double, double))
__ZGVyN8v__mth_i_vr4()
vrs8_t __ZGVyN8v__mth_i_vr4 (vrs8_t , float(*)(float))
__ZGVyN8v__mth_i_vr4si4()
vrs8_t __ZGVyN8v__mth_i_vr4si4 (vrs8_t , int32_t , float(*)(float, int32_t))
Referenced by __py_powi1_8().
__ZGVyN8v__mth_i_vr4si8()
vrs8_t __ZGVyN8v__mth_i_vr4si8 (vrs8_t , long long , float(*)(float, long long))
Referenced by __py_powk1_8().
__ZGVyN8vv__mth_i_vr4vi4()
vrs8_t __ZGVyN8vv__mth_i_vr4vi4 (vrs8_t , vis8_t , float(*)(float, int32_t))
Referenced by __py_powi_8().
__ZGVyN8vv__mth_i_vr4vi8()
vrs8_t __ZGVyN8vv__mth_i_vr4vi8 (vrs8_t , vid4_t , vid4_t , float(*)(float, long long))
Referenced by __py_powk_8().
__ZGVyN8vv__mth_i_vr4vr4()
vrs8_t __ZGVyN8vv__mth_i_vr4vr4 (vrs8_t , vrs8_t , float(*)(float, float))
__ZGVzM16v__mth_i_vr4()
vrs16_t __ZGVzM16v__mth_i_vr4 (vrs16_t , vis16_t , float(*)(float))
__ZGVzM16v__mth_i_vr4si4()
vrs16_t __ZGVzM16v__mth_i_vr4si4 (vrs16_t , int32_t , vis16_t , float(*)(float, int32_t))
Referenced by __pz_powi1_16m().
__ZGVzM16v__mth_i_vr4si8()
vrs16_t __ZGVzM16v__mth_i_vr4si8 (vrs16_t , long long , vis16_t , float(*)(float, long long))
Referenced by __pz_powk1_16m().
__ZGVzM16vv__mth_i_vr4vi4()
vrs16_t __ZGVzM16vv__mth_i_vr4vi4 (vrs16_t , vis16_t , vis16_t , float(*)(float, int32_t))
Referenced by __pz_powi_16m().
__ZGVzM16vv__mth_i_vr4vi8()
vrs16_t __ZGVzM16vv__mth_i_vr4vi8 (vrs16_t , vid8_t , vid8_t , vis16_t , float(*)(float, long long))
Referenced by __pz_powk_16m().
__ZGVzM16vv__mth_i_vr4vr4()
vrs16_t __ZGVzM16vv__mth_i_vr4vr4 (vrs16_t , vrs16_t , vis16_t , float(*)(float, float))
__ZGVzM8v__mth_i_vr8()
vrd8_t __ZGVzM8v__mth_i_vr8 (vrd8_t , vid8_t , double(*)(double))
__ZGVzM8v__mth_i_vr8si4()
vrd8_t __ZGVzM8v__mth_i_vr8si4 (vrd8_t , int32_t , vid8_t , double(*)(double, int32_t))
Referenced by __pz_powi1_8m().
__ZGVzM8v__mth_i_vr8si8()
vrd8_t __ZGVzM8v__mth_i_vr8si8 (vrd8_t , long long , vid8_t , double(*)(double, long long))
Referenced by __pz_powk1_8m().
__ZGVzM8vv__mth_i_vr8vi4()
vrd8_t __ZGVzM8vv__mth_i_vr8vi4 (vrd8_t , vis8_t , vid8_t , double(*)(double, int32_t))
Referenced by __pz_powi_8m().
__ZGVzM8vv__mth_i_vr8vi8()
vrd8_t __ZGVzM8vv__mth_i_vr8vi8 (vrd8_t , vid8_t , vid8_t , double(*)(double, long long))
Referenced by __pz_powk_8m().
__ZGVzM8vv__mth_i_vr8vr8()
vrd8_t __ZGVzM8vv__mth_i_vr8vr8 (vrd8_t , vrd8_t , vid8_t , double(*)(double, double))
__ZGVzN16v__mth_i_vr4()
vrs16_t __ZGVzN16v__mth_i_vr4 (vrs16_t , float(*)(float))
__ZGVzN16v__mth_i_vr4si4()
vrs16_t __ZGVzN16v__mth_i_vr4si4 (vrs16_t , int32_t , float(*)(float, int32_t))
Referenced by __pz_powi1_16().
__ZGVzN16v__mth_i_vr4si8()
vrs16_t __ZGVzN16v__mth_i_vr4si8 (vrs16_t , long long , float(*)(float, long long))
Referenced by __pz_powk1_16().
__ZGVzN16vv__mth_i_vr4vi4()
vrs16_t __ZGVzN16vv__mth_i_vr4vi4 (vrs16_t , vis16_t , float(*)(float, int32_t))
Referenced by __pz_powi_16().
__ZGVzN16vv__mth_i_vr4vi8()
vrs16_t __ZGVzN16vv__mth_i_vr4vi8 (vrs16_t , vid8_t , vid8_t , float(*)(float, long long))
Referenced by __pz_powk_16().
__ZGVzN16vv__mth_i_vr4vr4()
vrs16_t __ZGVzN16vv__mth_i_vr4vr4 (vrs16_t , vrs16_t , float(*)(float, float))
__ZGVzN4v__mth_i_vc8()
vcd4_t __ZGVzN4v__mth_i_vc8 (vcd4_t , _Complex double func_Complex double)
Referenced by __gz_sqrt_4().
__ZGVzN4vv__mth_i_vc8vc8()
vcd4_t __ZGVzN4vv__mth_i_vc8vc8 (vcd4_t , vcd4_t , _Complex double func_Complex double, _Complex double)
Referenced by __gz_div_4().
__ZGVzN8v__mth_i_vc4()
vcs8_t __ZGVzN8v__mth_i_vc4 (vcs8_t , _Complex float func_Complex float)
Referenced by __gc_sqrt_8().
__ZGVzN8v__mth_i_vr8()
vrd8_t __ZGVzN8v__mth_i_vr8 (vrd8_t , double(*)(double))
__ZGVzN8v__mth_i_vr8si4()
vrd8_t __ZGVzN8v__mth_i_vr8si4 (vrd8_t , int32_t , double(*)(double, int32_t))
Referenced by __pz_powi1_8().
__ZGVzN8v__mth_i_vr8si8()
vrd8_t __ZGVzN8v__mth_i_vr8si8 (vrd8_t , long long , double(*)(double, long long))
Referenced by __pz_powk1_8().
__ZGVzN8vv__mth_i_vc4vc4()
vcs8_t __ZGVzN8vv__mth_i_vc4vc4 (vcs8_t , vcs8_t , _Complex float func_Complex float, _Complex float)
Referenced by __gc_div_8().
__ZGVzN8vv__mth_i_vr8vi4()
vrd8_t __ZGVzN8vv__mth_i_vr8vi4 (vrd8_t , vis8_t , double(*)(double, int32_t))
Referenced by __pz_powi_8().
__ZGVzN8vv__mth_i_vr8vi8()
vrd8_t __ZGVzN8vv__mth_i_vr8vi8 (vrd8_t , vid8_t , double(*)(double, long long))
Referenced by __pz_powk_8().
__ZGVzN8vv__mth_i_vr8vr8()
vrd8_t __ZGVzN8vv__mth_i_vr8vr8 (vrd8_t , vrd8_t , double(*)(double, double))