flang: mthi64.c File Reference
mthi64.c File Reference
#include "dblint64.h"
Classes
union LL_SHAPE
struct UFP
Macros
#define FL(s) s.value
#define UFL(s) s.uvalue
#define LSW(s) s.hf[0]
#define MSW(s) s.hf[1]
#define ULSW(s) s.uhf[0]
#define UMSW(s) s.uhf[1]
#define VOID void
#define UTL_I_I64RET(m, l) return (__utl_i_i64ret(m, l))
#define __mth_i_kmul(a, b) (a) * (b)
#define bitmask(w) ((UINT)(1UL << (w)) - 1)
#define extract(i, a, b) (((INT)(i) >> (b)) & bitmask((a) - (b) + 1))
#define bit_fld(i, a, b) (((INT)(i)&bitmask((a) - (b) + 1)) << (b))
#define bit_insrt(x, i, a, b) x = (((INT)(x) & ~bit_fld(~0L,(a),(b)))
#define IEEE32_sign(f) extract(f, 31, 31)
#define IEEE32_exp(f) (extract(f, 30, 23) - 127)
#define IEEE32_man(f) (bit_fld(1, 23, 23) | extract(f, 22, 0))
#define IEEE32_zero(f) (extract(f, 30, 0) == 0)
#define IEEE32_infin(f) (extract(f, 30, 0) == bit_fld(255, 30, 23))
#define IEEE32_nan(f) (!IEEE32_infin(f) && IEEE32_exp(f) == 128)
#define IEEE32_pack(f, sign, exp, man)
#define IEEE64_sign(d) extract(d[1], 31, 31)
#define IEEE64_exp(d) (extract(d[1], 30, 20) - 1023)
#define IEEE64_manhi(d) (bit_fld(1, 20, 20) | extract(d[1], 19, 0))
#define IEEE64_manlo(d) (d[0])
#define IEEE64_zero(d) (extract(d[1], 30, 0) == 0L && IEEE64_manlo(d) == 0L)
#define IEEE64_infin(d) (extract(d[1], 30, 0) == bit_fld(255, 30, 23) && d[0] == 0)
#define IEEE64_nan(d) (!IEEE64_infin(d) && IEEE64_exp(d) == 1024)
#define IEEE64_pack(d, sign, exp, man)
#define POS 0
#define NEG 1
Typedefs
typedef int INT
typedef unsigned int UINT
typedef int IEEE32
typedef int IEEE64[2]
Enumerations
enum VAL {
ZERO , NIL , NORMAL , BIG ,
INFIN , NAN , DIVZ , SUBNORMAL ,
ZERO , NIL , NORMAL , BIG ,
INFIN , NAN , DIVZ , SUBNORMAL ,
ZERO , NIL , NORMAL , BIG ,
INFIN , NAN , DIVZ
}
Functions
long long __utl_i_i64ret (int msw, int lsw)
INT __mth_i_kcmp ()
INT __mth_i_kucmp ()
INT __mth_i_kcmpz ()
INT __mth_i_kucmpz ()
VOID __mth_i_krshift ()
VOID __mth_i_klshift ()
VOID __mth_i_kurshift ()
VOID __utl_i_add64 ()
VOID __utl_i_div64 ()
VOID __utl_i_sub64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Subtract two 64-bit integers.
VOID __utl_i_mul64 ()
VOID __utl_i_udiv64 ()
static VOID neg64 ()
static VOID shf64 ()
static VOID shf128by1 ()
VOID __utl_i_add64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
VOID __utl_i_mul64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
long long __mth_i_kdiv (long long x, long long y)
unsigned long long __mth_i_ukdiv (unsigned long long x, unsigned long long y)
VOID __utl_i_div64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
static VOID neg64 (DBLINT64 arg, DBLINT64 result)
VOID __utl_i_udiv64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
Divide two 64-bit unsigned integers to produce a 64-bit unsigned integer quotient.
long long __mth_i_kicshft (UINT op1, UINT op2, INT count, INT direct)
long long __mth_i_ukicshft (UINT op1, UINT op2, INT count, INT direct)
long long __mth_i_kishft (INT op1, INT op2, INT arg2)
static VOID shf64 (DBLINT64 arg, int count, DBLINT64 result)
static VOID shf128by1 (arg, result)
INT __mth_i_kucmpz (UINT op1, UINT op2)
INT __mth_i_kucmp (UINT op1, UINT op2, UINT op3, UINT op4)
INT __mth_i_kcmpz (INT op1, INT op2)
INT __mth_i_kcmp (INT op1, INT op2, INT op3, INT op4)
static VOID manadd (m1, m2)
static VOID manshftl (m, int n)
static VOID manshftr (m, int n)
static VOID manrnd (m, int bits)
static VOID ufpnorm (UFP *u)
static VOID ufprnd (UFP *u, int bits)
static VOID dtoufp (IEEE64 d, register UFP *u)
Floating point double unpack.
static VOID ftoufp (IEEE32 *f, UFP *u)
static VOID i64toufp (DBLINT64 i, UFP *u)
static VOID ufptod (UFP *u, IEEE64 r)
static VOID ufptof (UFP *u, IEEE32 *r)
static VOID ufptoi64 (UFP *u, DBLINT64 i)
VOID __utl_i_dfix64 (double d, DBLINT64 i)
double __utl_i_dflt64 (DBLINT64 i)
VOID __utl_i_fix64 (float ff, DBLINT64 i)
float __utl_i_flt64 (DBLINT64 i)
Macro Definition Documentation
__mth_i_kmul
#define __mth_i_kmul (a, b) (a) * (b)
Definition at line 52 of file mthi64.c.
bit_fld
#define bit_fld (i, a, b) (((INT)(i)&bitmask((a) - (b) + 1)) << (b))
Definition at line 581 of file mthi64.c.
bit_insrt
#define bit_insrt (x, i, a, b) x = (((INT)(x) & ~bit_fld(~0L,(a),(b)))
Definition at line 582 of file mthi64.c.
bitmask
#define bitmask (w) ((UINT)(1UL << (w)) - 1)
Definition at line 579 of file mthi64.c.
extract
#define extract (i, a, b) (((INT)(i) >> (b)) & bitmask((a) - (b) + 1))
Definition at line 580 of file mthi64.c.
FL
#define FL (s) s.value
Definition at line 24 of file mthi64.c.
IEEE32_exp
#define IEEE32_exp (f) (extract(f, 30, 23) - 127)
Definition at line 588 of file mthi64.c.
IEEE32_infin
#define IEEE32_infin (f) (extract(f, 30, 0) == bit_fld(255, 30, 23))
Definition at line 591 of file mthi64.c.
IEEE32_man
#define IEEE32_man (f) (bit_fld(1, 23, 23) | extract(f, 22, 0))
Definition at line 589 of file mthi64.c.
IEEE32_nan
#define IEEE32_nan (f) (!IEEE32_infin(f) && IEEE32_exp(f) == 128)
Definition at line 592 of file mthi64.c.
IEEE32_pack
#define IEEE32_pack (f, sign, exp, man)
Value:
  f = bit_fld(sign, 31, 31) | bit_fld(exp + 127, 30, 23) |                     \
      bit_fld(man[0], 22, 0)
Definition at line 593 of file mthi64.c.
IEEE32_sign
#define IEEE32_sign (f) extract(f, 31, 31)
Definition at line 587 of file mthi64.c.
IEEE32_zero
#define IEEE32_zero (f) (extract(f, 30, 0) == 0)
Definition at line 590 of file mthi64.c.
IEEE64_exp
#define IEEE64_exp (d) (extract(d[1], 30, 20) - 1023)
Definition at line 598 of file mthi64.c.
IEEE64_infin
#define IEEE64_infin (d) (extract(d[1], 30, 0) == bit_fld(255, 30, 23) && d[0] == 0)
Definition at line 602 of file mthi64.c.
IEEE64_manhi
#define IEEE64_manhi (d) (bit_fld(1, 20, 20) | extract(d[1], 19, 0))
Definition at line 599 of file mthi64.c.
IEEE64_manlo
#define IEEE64_manlo (d) (d[0])
Definition at line 600 of file mthi64.c.
IEEE64_nan
#define IEEE64_nan (d) (!IEEE64_infin(d) && IEEE64_exp(d) == 1024)
Definition at line 604 of file mthi64.c.
IEEE64_pack
#define IEEE64_pack (d, sign, exp, man)
Value:
  d[1] = bit_fld(sign, 31, 31) | bit_fld(exp + 1023, 30, 20) |                 \
         bit_fld(man[0], 19, 0);                                               \
  d[0] = man[1]
Definition at line 605 of file mthi64.c.
IEEE64_sign
#define IEEE64_sign (d) extract(d[1], 31, 31)
Definition at line 597 of file mthi64.c.
IEEE64_zero
#define IEEE64_zero (d) (extract(d[1], 30, 0) == 0L && IEEE64_manlo(d) == 0L)
Definition at line 601 of file mthi64.c.
LSW
#define LSW (s) s.hf[0]
Definition at line 27 of file mthi64.c.
MSW
#define MSW (s) s.hf[1]
Definition at line 28 of file mthi64.c.
NEG
#define NEG 1
Definition at line 639 of file mthi64.c.
POS
#define POS 0
Definition at line 638 of file mthi64.c.
UFL
#define UFL (s) s.uvalue
Definition at line 25 of file mthi64.c.
ULSW
#define ULSW (s) s.uhf[0]
Definition at line 29 of file mthi64.c.
UMSW
#define UMSW (s) s.uhf[1]
Definition at line 30 of file mthi64.c.
UTL_I_I64RET
#define UTL_I_I64RET (m, l) return (__utl_i_i64ret(m, l))
Definition at line 34 of file mthi64.c.
VOID
#define VOID void
Definition at line 32 of file mthi64.c.
Typedef Documentation
IEEE32
typedef int IEEE32
Definition at line 584 of file mthi64.c.
IEEE64
typedef int IEEE64[2]
Definition at line 585 of file mthi64.c.
INT
typedef int INT
Definition at line 49 of file mthi64.c.
UINT
typedef unsigned int UINT
Definition at line 50 of file mthi64.c.
Enumeration Type Documentation
VAL
enum VAL
Enumerator
ZERO
NIL
NORMAL
BIG
INFIN
NAN
DIVZ
SUBNORMAL
ZERO
NIL
NORMAL
BIG
INFIN
NAN
DIVZ
SUBNORMAL
ZERO
NIL
NORMAL
BIG
INFIN
NAN
DIVZ
Definition at line 636 of file mthi64.c.
Function Documentation
__mth_i_kcmp() [1/2]
INT __mth_i_kcmp ()
__mth_i_kcmp() [2/2]
INT __mth_i_kcmp (INT op1, INT op2, INT op3, INT op4)
Definition at line 532 of file mthi64.c.
__mth_i_kcmpz() [1/2]
INT __mth_i_kcmpz ()
__mth_i_kcmpz() [2/2]
INT __mth_i_kcmpz (INT op1, INT op2)
Definition at line 520 of file mthi64.c.
__mth_i_kdiv()
long long __mth_i_kdiv (long long x, long long y)
Definition at line 144 of file mthi64.c.
References __utl_i_div64(), a, b, FL, LSW, MSW, r, result, x, and y.
__mth_i_kicshft()
long long __mth_i_kicshft (UINT op1, UINT op2, INT count, INT direct)
Definition at line 346 of file mthi64.c.
References count, direct, result, and UTL_I_I64RET.
__mth_i_kishft()
long long __mth_i_kishft (INT op1, INT op2, INT arg2)
Definition at line 412 of file mthi64.c.
References result, shf64(), and UTL_I_I64RET.
__mth_i_klshift()
VOID __mth_i_klshift ()
__mth_i_krshift()
VOID __mth_i_krshift ()
__mth_i_kucmp() [1/2]
INT __mth_i_kucmp ()
Referenced by __utl_i_div64(), and __utl_i_udiv64().
__mth_i_kucmp() [2/2]
INT __mth_i_kucmp (UINT op1, UINT op2, UINT op3, UINT op4)
Definition at line 503 of file mthi64.c.
__mth_i_kucmpz() [1/2]
INT __mth_i_kucmpz ()
__mth_i_kucmpz() [2/2]
INT __mth_i_kucmpz (UINT op1, UINT op2)
Definition at line 484 of file mthi64.c.
__mth_i_kurshift()
VOID __mth_i_kurshift ()
__mth_i_ukdiv()
unsigned long long __mth_i_ukdiv (unsigned long long x, unsigned long long y)
Definition at line 188 of file mthi64.c.
References __utl_i_udiv64(), a, b, r, result, UFL, ULSW, UMSW, x, and y.
__mth_i_ukicshft()
long long __mth_i_ukicshft (UINT op1, UINT op2, INT count, INT direct)
Definition at line 380 of file mthi64.c.
References count, direct, result, and UTL_I_I64RET.
__utl_i_add64() [1/2]
VOID __utl_i_add64 ()
__utl_i_add64() [2/2]
VOID __utl_i_add64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 73 of file mthi64.c.
References carry(), and result.
__utl_i_dfix64()
VOID __utl_i_dfix64 (double d, DBLINT64 i)
Definition at line 1032 of file mthi64.c.
References d, dtoufp(), i, and ufptoi64().
__utl_i_dflt64()
double __utl_i_dflt64 (DBLINT64 i)
Definition at line 1043 of file mthi64.c.
References d, i, i64toufp(), and ufptod().
__utl_i_div64() [1/2]
VOID __utl_i_div64 ()
Referenced by __mth_i_kdiv().
__utl_i_div64() [2/2]
VOID __utl_i_div64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 216 of file mthi64.c.
References __mth_i_kucmp(), __utl_i_sub64(), i, neg64(), result, and shf128by1().
__utl_i_fix64()
VOID __utl_i_fix64 (float ff, DBLINT64 i)
Definition at line 1055 of file mthi64.c.
References f, ftoufp(), i, and ufptoi64().
__utl_i_flt64()
float __utl_i_flt64 (DBLINT64 i)
Definition at line 1066 of file mthi64.c.
References f, i, i64toufp(), and ufptof().
__utl_i_i64ret()
long long __utl_i_i64ret (int msw, int lsw)
Definition at line 38 of file mthi64.c.
References i, and z.
__utl_i_mul64() [1/2]
VOID __utl_i_mul64 ()
__utl_i_mul64() [2/2]
VOID __utl_i_mul64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Definition at line 122 of file mthi64.c.
References __mth_i_kmul, r, result, LL_SHAPE::value, and LL_SHAPE::wd.
__utl_i_sub64()
VOID __utl_i_sub64 (DBLINT64 arg1, DBLINT64 arg2, DBLINT64 result)
Subtract two 64-bit integers.
Parameters
arg1 minuend
arg2 subtrahend
result arg1 - arg2
Definition at line 98 of file mthi64.c.
References result.
Referenced by __utl_i_div64(), and __utl_i_udiv64().
__utl_i_udiv64() [1/2]
VOID __utl_i_udiv64 ()
Referenced by __mth_i_ukdiv().
__utl_i_udiv64() [2/2]
VOID __utl_i_udiv64 (DBLUINT64 arg1, DBLUINT64 arg2, DBLUINT64 result)
Divide two 64-bit unsigned integers to produce a 64-bit unsigned integer quotient.
Definition at line 296 of file mthi64.c.
References __mth_i_kucmp(), __utl_i_sub64(), i, result, and shf128by1().
dtoufp()
static VOID dtoufp (IEEE64 d, register UFP * u) static
Floating point double unpack.
Parameters
d double precision number
u pointer to area for unpack
Definition at line 815 of file mthi64.c.
References d, IEEE64_exp, IEEE64_infin, IEEE64_manhi, IEEE64_manlo, IEEE64_nan, IEEE64_sign, IEEE64_zero, INFIN, NAN, NORMAL, and ZERO.
Referenced by __utl_i_dfix64().
ftoufp()
static VOID ftoufp (IEEE32 * f, UFP * u) static
Definition at line 840 of file mthi64.c.
References f, IEEE32_exp, IEEE32_infin, IEEE32_man, IEEE32_nan, IEEE32_sign, IEEE32_zero, INFIN, manshftr(), NAN, NORMAL, and ZERO.
Referenced by __utl_i_fix64().
i64toufp()
static VOID i64toufp (DBLINT64 i, UFP * u) static
Definition at line 869 of file mthi64.c.
References i, NEG, neg64(), NORMAL, POS, tmp, and ZERO.
Referenced by __utl_i_dflt64(), and __utl_i_flt64().
manadd()
static VOID manadd (m1 , m2) static
Definition at line 648 of file mthi64.c.
References carry(), hi, i, lo, m2, t1, and t2.
Referenced by manrnd().
manrnd()
static VOID manrnd (m , int bits) static
Definition at line 733 of file mthi64.c.
References bits, extract, m, manadd(), manshftl(), manshftr(), one, and round().
Referenced by ufprnd().
manshftl()
static VOID manshftl (m , int n) static
Definition at line 681 of file mthi64.c.
References bitmask, i, j, m, and n.
Referenced by manrnd(), ufpnorm(), ufptof(), and ufptoi64().
manshftr()
static VOID manshftr (m , int n) static
Definition at line 707 of file mthi64.c.
References bitmask, i, j, m, and n.
Referenced by ftoufp(), manrnd(), ufpnorm(), and ufptoi64().
neg64() [1/2]
static VOID neg64 () static
Referenced by __utl_i_div64(), i64toufp(), and ufptoi64().
neg64() [2/2]
static VOID neg64 (DBLINT64 arg, DBLINT64 result) static
Definition at line 279 of file mthi64.c.
References arg, result, and sign.
shf128by1() [1/2]
static VOID shf128by1 ()
Referenced by __utl_i_div64(), and __utl_i_udiv64().
shf128by1() [2/2]
static VOID shf128by1 (arg , result) static
Definition at line 457 of file mthi64.c.
References arg, i, and result.
shf64() [1/2]
static VOID shf64 ()
Referenced by __mth_i_kishft().
shf64() [2/2]
static VOID shf64 (DBLINT64 arg, int count, DBLINT64 result) static
Definition at line 422 of file mthi64.c.
References arg, count, and result.
ufpnorm()
static VOID ufpnorm (UFP * u) static
Definition at line 773 of file mthi64.c.
References extract, manshftl(), and manshftr().
Referenced by ufprnd(), and ufptoi64().
ufprnd()
static VOID ufprnd (UFP * u, int bits) static
Definition at line 796 of file mthi64.c.
References bits, manrnd(), and ufpnorm().
Referenced by ufptod(), and ufptof().
ufptod()
static VOID ufptod (UFP * u, IEEE64 r) static
Definition at line 899 of file mthi64.c.
References BIG, DIVZ, IEEE64_pack, INFIN, NAN, NIL, NORMAL, r, ufprnd(), and ZERO.
Referenced by __utl_i_dflt64().
ufptof()
static VOID ufptof (UFP * u, IEEE32 * r) static
Definition at line 943 of file mthi64.c.
References BIG, DIVZ, IEEE32_pack, INFIN, manshftl(), NAN, NIL, NORMAL, r, ufprnd(), and ZERO.
Referenced by __utl_i_flt64().
ufptoi64()
static VOID ufptoi64 (UFP * u, DBLINT64 i) static
Definition at line 988 of file mthi64.c.
References BIG, i, INFIN, manshftl(), manshftr(), NAN, NEG, neg64(), NIL, ufpnorm(), and ZERO.
Referenced by __utl_i_dfix64(), and __utl_i_fix64().