flang: mwd.h File Reference
mwd.h File Reference
Header for mw's dump routines.
#include "gbldefs.h"
#include <stdio.h>
#include "symtab.h"
Functions
char * getprintnme (int n)
...
char * printname (int sptr)
...
int putdty (TY_KIND dty)
...
void checkfgraph (const char *s)
...
void checktags (const char *phase)
...
void dbihonly (void)
...
void dbih (void)
...
void db (int block)
...
void ddtype (DTYPE dtype)
...
void ddtypes (void)
...
void dfih (int f)
...
void dflg (void)
...
void dgbl (void)
...
void dili (int ilix)
...
void dilitre (int ilix)
...
void dilt (int ilt)
...
void dsa (void)
...
void ds (int sptr)
...
void dss (int l, int u)
...
void dsym (int sptr)
...
void dsyms (int l, int u)
...
void dumpabnd (int abx)
...
void dumpabnds (void)
...
void dumpacacheinfo (int cx)
...
void dumpacexprs (void)
...
void dumpacivs (void)
...
void dumpacsymt (int first, int last)
...
void dumpadef (int def)
...
void _dumpadef (int def, int dumpuses)
...
void dumpallloops (void)
...
void dumpallploops (void)
...
void _dumpaloop (int lpx, bool dumpprivate)
...
void dumpalooponly (int lpx)
...
void dumpanmelist (int nmelist)
...
void dumpanmetree (int nmex)
...
void dumparef (int arefx)
...
void dumparefs (void)
...
void dumparefxlist (int arefxlist)
...
void dumpause (int use)
...
void _dumpause (int use, int dumpdefs)
...
void dumpauselist (int use)
...
void dumpauses (void)
...
void dumpblock (int block)
...
void dumpblocks (const char *title)
...
void dumpblocksonly (void)
...
void _dumpchildaloopsclist (int lpx)
...
void _dumpchildaloops (int lpx)
...
void dumpddiff (int v)
...
void dumpdef (int def)
...
void _dumpdef (int def, int dumpuses)
...
void dumpdeflist (int deflist)
...
void dumpdefnmes (void)
...
void dumpdefs (void)
...
void dumpdfs (void)
...
void dumpdiff (void)
...
void dumpdtype (DTYPE dtype)
...
void dumpdtypes (void)
...
void dumpdvl (int d)
...
void dumpdvls (void)
...
void dumpfgraph (void)
...
void dumpfgraph2file (void)
...
void dumpfg (void)
...
void dumpfile (int f)
...
void dumpfiles (void)
...
void dumpfnodehead (int v)
...
void dumpfnode (int v)
...
void dumpiltdeflist (int iltx)
...
void dumpilt (int ilt)
...
void dumpiltmrlist (int iltx)
...
void dumpilts (void)
...
void dumpiltuselist (int iltx)
...
void dumpind (int i)
...
void dumpinds (void)
...
void dumpiv (int ivx)
...
void dumpivlist (void)
...
void dumpliveinuses (void)
...
void dumpliveoutdefs (void)
...
void dumplong (void)
...
void dumploop (int l)
...
void _dumploop (int l, bool dumpldst, bool dumpbits, int nest)
...
void dumploopsbv (int bvlen)
...
void dumploops (void)
...
void _dumplooptree (int l, int nest)
...
void dumplooptree (void)
...
void dumpmemref (int m)
...
void dumpmemrefs (void)
...
void _dumpmode2 (int mode2)
...
void _dumpmode3 (int mode3)
...
void _dumpmode (int mode)
...
void dumpmr (int m)
...
void dumpnatural (void)
...
void dumpnewdtypes (int olddtavail)
...
void dumpnme (int n)
...
void _dumpnme (int n, bool dumpdefsuses)
...
void dumpnmes (void)
...
void dumpnmetree (int n)
...
void dumpnnme (int n)
...
void dumpnst2 (int n)
...
void dumpnst (int n)
...
void _dumpparentaloopsclist (int lpx)
...
void _dumpparentaloops (int lpx)
...
void dumpploop (int plpx)
...
void _dumpplooptree (int plpx)
...
void dumpprivatelist (void)
...
void dumpreddeflist (int deflist)
...
void dumpred (int r)
...
void dumpredlist (int r)
...
void dumpreducdeflist (int defx)
...
void dumpreducdefs (void)
...
void dumpregion (int r)
...
void dumpregionnest (int r)
...
void dumpregions (void)
...
void dumprnest (void)
...
void dumpscalar (int s)
...
void dumpscalarlist (int ss)
...
void dumpscalars (void)
...
void dumpshort (void)
...
void dumpsizes (void)
...
void dumpstmt (int s)
...
void dumpstmts (void)
...
void dumpstore (int s)
...
void dumpstorelist (int s)
...
void dumpsub (int s)
...
void dumpsubs (void)
...
void dumptblock (const char *title, int block)
...
void dumpuseddefs (void)
...
void dumpuseduses (void)
...
void dumpuse (int use)
...
void _dumpuse (int use, int dumpdefs)
...
void dumpuses (void)
...
void dumpvdef (int def)
...
void _dumpvdef (int def, int dumpuses)
...
void dumpvilt (int iltx)
...
void dumpvind (int i)
...
void dumpvindl (int i1, int n)
...
void dumpvinds (void)
...
void dumpvloop (int l)
...
void dumpvlooplist (int list)
...
void dumpvloops (void)
...
void dumpvuse (int use)
...
void _dumpvuse (int use, int dumpdefs)
...
void pprintnme (int n)
...
void printblock (int block)
...
void printblockline (int block)
...
void printblocksline (void)
...
void printblocks (void)
...
void dumpdpshape (int shapeid)
...
void dumpdppolicy (int policyid)
...
void dumpdpshapes ()
...
void dumpdppolicies ()
...
void printblockt (int firstblock, int lastblock)
...
void printblocktt (int firstblock, int lastblock)
...
void printfgraph (void)
...
void printfnode (int v)
...
void printili (int i)
...
void printilt (int i)
...
void printloop (int lpx)
...
void printnme (int n)
...
void printregion (int r)
...
void printregionnest (const char *msg, int r)
...
void _printregionnest (int r)
...
void printregions (void)
...
void putarefherelists (int lpx)
...
void putareflists (int lpx)
...
void putasub (int asubx, int nest)
...
void putcoeff (int coefx, int nest)
...
void putdtype (DTYPE dtype)
...
void _putdtype (DTYPE dtype, int structdepth)
...
void putili (const char *name, int ilix)
...
void putint1 (int d)
...
void putlpxareflist (int lpx, const char *listname, int list, int nest)
...
void putmode (int mode)
...
void putmwline (void)
...
void putnestarefherelists (int lpx)
...
void _putnestareflists (int lpx, int nest, int flags)
...
void putnme (const char *s, int nme)
...
void putnnaref (int arefx, int nest)
...
void putptelist (int pte)
...
void putredtype (int rt)
...
void putsclist (const char *name, int list)
...
void putsoc (int socptr)
...
void _putsubs (const char *name, int s1, int n1)
...
void putsubs (int s1, int n1)
...
void simpledumpregion (int r)
...
void simpledumpstmt (int s)
...
void simpleprintregion (int r)
...
void simpleprintregionnest (const char *msg, int r)
...
void _simpleprintregionnest (int r)
...
void stackcheck (void)
...
void stackvars (void)
...
Detailed Description
Header for mw's dump routines.
Definition in file mwd.h.
Function Documentation
_dumpadef()
void _dumpadef (int def, int dumpuses)
...
_dumpaloop()
void _dumpaloop (int lpx, bool dumpprivate)
...
_dumpause()
void _dumpause (int use, int dumpdefs)
...
_dumpchildaloops()
void _dumpchildaloops (int lpx)
...
_dumpchildaloopsclist()
void _dumpchildaloopsclist (int lpx)
...
_dumpdef()
void _dumpdef (int def, int dumpuses)
...
_dumploop()
void _dumploop (int l, bool dumpldst, bool dumpbits, int nest)
...
_dumplooptree()
void _dumplooptree (int l, int nest)
...
_dumpmode()
void _dumpmode (int mode)
...
_dumpmode2()
void _dumpmode2 (int mode2)
...
_dumpmode3()
void _dumpmode3 (int mode3)
...
_dumpnme()
void _dumpnme (int n, bool dumpdefsuses)
...
Definition at line 4784 of file mwd.cpp.
References dfile, full, gbl, n, NME_BASE, NME_CNST, NME_CNT, NME_HSHLNK, NME_INLARR, NME_MASK, NME_NM, NME_NULL, NME_PTE, NME_RAT, NME_STL, NME_SUB, NME_SYM, NME_TYPE, nmeb, nmetypes, NT_ARR, NT_IND, NT_MEM, NT_UNK, NT_VAR, NULL, pprintnme(), putint(), putline(), putnzint(), putptelist(), putstring1(), putsym(), putval1(), SIZEOF, and stb.
Referenced by dumpnme(), and dumpnnme().
_dumpparentaloops()
void _dumpparentaloops (int lpx)
...
_dumpparentaloopsclist()
void _dumpparentaloopsclist (int lpx)
...
_dumpplooptree()
void _dumpplooptree (int plpx)
...
_dumpuse()
void _dumpuse (int use, int dumpdefs)
...
_dumpvdef()
void _dumpvdef (int def, int dumpuses)
...
_dumpvuse()
void _dumpvuse (int use, int dumpdefs)
...
_printregionnest()
void _printregionnest (int r)
...
_putdtype()
void _putdtype (DTYPE dtype, int structdepth)
...
Definition at line 2531 of file mwd.cpp.
References _putdtype(), AD_DPTR, AD_LWBD, AD_NUMDIM, AD_UPBD, appendint1(), appendstring1(), appendsym1(), dfile, STB::dt, DTY, DTyAlgTyMember, DTyAlgTyTag, DTyAlgTyTagNeg, DTyArgNext, DTyArgSym, DTyArgType, DTyCharLength, DTySeqTyElement, DTySet, gbl, i, NOSYM, putdty(), simpledtype(), SPTR_NULL, stb, and TY_CHAR.
Referenced by _putdtype(), and putdtype().
_putnestareflists()
void _putnestareflists (int lpx, int nest, int flags)
...
_putsubs()
void _putsubs (const char * name, int s1, int n1)
...
_simpleprintregionnest()
void _simpleprintregionnest (int r)
...
checkfgraph()
void checkfgraph (const char * s)
...
checktags()
void checktags (const char * phase)
...
db()
void db (int block)
...
Definition at line 4387 of file mwd.cpp.
References BIH_ACCDATA, BIH_ACCEL, BIH_ASM, BIH_ASSN, BIH_BLKCNT, BIH_COMBST, BIH_CS, BIH_DELETABLE, BIH_DOCONC, BIH_EN, BIH_ENDACCDATA, BIH_ENDACCEL, BIH_ENDKERNEL, BIH_ENLAB, BIH_EX, BIH_EXSDSCUNSAFE, BIH_FINDEX, BIH_FT, BIH_FTAG, BIH_GUARDEE, BIH_GUARDER, BIH_HEAD, BIH_ILTFIRST, BIH_ILTLAST, BIH_INNERMOST, BIH_INVIF, BIH_KERNEL, BIH_LABEL, BIH_LAST, BIH_LDVOL, BIH_LINENO, BIH_MARK, BIH_MARK2, BIH_MARK3, BIH_MEXITS, BIH_MIDIOM, BIH_NEXT, BIH_NOBLA, BIH_NODEPCHK, BIH_NOINVIF, BIH_NOMERGE, BIH_NOSIMD, BIH_NOUNROLL, BIH_OZCR, BIH_PAR, BIH_PARALN, BIH_PARLOOP, BIH_PARSECT, BIH_PL, BIH_PREV, BIH_QJSR, BIH_RD, BIH_RESID, BIH_RGSET, BIH_SIMD, BIH_SMOVE, BIH_STREG, BIH_STVOL, BIH_TAIL, BIH_TASK, BIH_UJRES, BIH_UNROLL, BIH_UNROLL_COUNT, BIH_VCAND, BIH_VPAR, BIH_XT, BIH_ZTRP, bihb, dfile, FIH_DIRNAME, FIH_FILENAME, FIH_FUNCNAME, fihb, full, gbl, NULL, putbit(), putdouble(), puterr(), putint(), putline(), putnsym(), putnzint(), putstring1(), putstring1t(), and FIHB::stg_avail.
Referenced by __fort_copy(), __fort_copy_out(), __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), __fort_reverse_array(), add_debug_cmnblk_variables(), cleanup_bounds(), dbihonly(), dtype_array_check_set(), dumpblock(), dumpilts(), emit_deref_expression_mdnode(), ENTF90(), ENTFTN(), formalsAddDebug(), get_extra_info_for_sptr(), get_file_mdnode(), get_filedesc_mdnode(), get_lexical_block_info(), get_param_mdnode(), init_subrange_bound(), init_subrange_bound_pre11(), kmaxloc_common(), kminloc_common(), lldbg_add_pending_import_entity(), lldbg_add_pending_import_entity_to_child(), lldbg_assign_lexical_block(), lldbg_assign_lexical_blocks(), lldbg_cancel_value_call(), lldbg_cleanup_missing_bounds(), lldbg_cons_line(), lldbg_create_aggregate_members_type(), lldbg_create_aggregate_type_mdnode(), lldbg_create_array_type_mdnode(), lldbg_create_assumed_len_string_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_block_mdnode(), lldbg_create_common_block_mdnode(), lldbg_create_compile_unit_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_file_mdnode(), lldbg_create_ftn_array_type_mdnode(), lldbg_create_ftn_subrange_mdnode(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_create_generic_subrange_mdnode(), lldbg_create_global_variable_mdnode(), lldbg_create_imported_entity(), lldbg_create_local_variable_mdnode(), lldbg_create_location_mdnode(), lldbg_create_member_mdnode(), lldbg_create_module_flag_mdnode(), lldbg_create_module_mdnode(), lldbg_create_outlined_parameters_node(), lldbg_create_pointer_type_mdnode(), lldbg_create_string_type_mdnode(), lldbg_create_structure_type_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_create_subrange_mdnode(), lldbg_create_subrange_mdnode_pre11(), lldbg_create_subrange_via_sdsc(), lldbg_create_subroutine_type_mdnode(), lldbg_create_union_type_mdnode(), lldbg_create_unspecified_mdnode(), lldbg_create_unspecified_parameters_mdnode(), lldbg_create_vector_type_mdnode(), lldbg_emit_common_block_mdnode(), lldbg_emit_compile_unit(), lldbg_emit_empty_expression_mdnode(), lldbg_emit_expression_mdnode(), lldbg_emit_file(), lldbg_emit_global_variable(), lldbg_emit_imported_entity(), lldbg_emit_lexical_block(), lldbg_emit_lexical_blocks(), lldbg_emit_line(), lldbg_emit_local_variable(), lldbg_emit_lv_list(), lldbg_emit_modified_type(), lldbg_emit_module_mdnode(), lldbg_emit_outlined_parameter_list(), lldbg_emit_outlined_subprogram(), lldbg_emit_outlined_subroutine(), lldbg_emit_param_variable(), lldbg_emit_parameter_list(), lldbg_emit_ptr_param_variable(), lldbg_emit_subprogram(), lldbg_emit_subroutine_type(), lldbg_emit_type(), lldbg_free(), lldbg_function_end(), lldbg_fwd_local_variable(), lldbg_get_bounds_for_assumed_rank_sdsc(), lldbg_get_bounds_for_sdsc(), lldbg_get_di_routine_idx(), lldbg_get_line(), lldbg_get_subprogram_line(), lldbg_get_var_line(), lldbg_init(), lldbg_init_arrays(), lldbg_limit_lexical_blocks(), lldbg_register_param_mdnode(), lldbg_register_value_call(), lldbg_reserve_lexical_block(), lldbg_reserve_lexical_blocks(), lldbg_reset_dtype_array(), lldbg_reset_module(), lldbg_set_func_ptr(), lldbg_subprogram(), lldbg_update_arrays(), local_copy(), make_dwtag(), maxloc_common(), minloc_common(), printblock(), printblockline(), process_global_lifetime_debug(), ptr_in(), recopy(), set_disubprogram_flags(), set_disubprogram_spflags(), sourced_alloc_and_assign(), and void().
dbih()
void dbih (void)
...
Definition at line 4534 of file mwd.cpp.
References BIH_LAST, BIH_NEXT, bihb, dfile, dumpblock(), gbl, and NULL.
Referenced by dumpblocks(), and init().
dbihonly()
void dbihonly (void)
...
Definition at line 4552 of file mwd.cpp.
References BIH_LAST, BIH_NEXT, bihb, db(), dfile, gbl, and NULL.
Referenced by dumpblocksonly(), and init().
ddtype()
void ddtype (DTYPE dtype)
...
Definition at line 2817 of file mwd.cpp.
References dumpdtype().
Referenced by _linearize(), amd64_update_class(), ll_convert_array_dtype(), mkvarref(), and name_dependent_check().
ddtypes()
void ddtypes (void)
...
Definition at line 2848 of file mwd.cpp.
References dumpdtypes().
dfih()
void dfih (int f)
...
dflg()
void dflg (void)
...
Definition at line 2252 of file mwd.cpp.
References FLG::anno, FLG::asmcode, FLG::astype, FLG::autoinline, FLG::code, FLG::dalign, FLG::dbg, FLG::dclchk, FLG::debug, FLG::def, FLG::depchk, FLG::depwarn, dfile, FLG::dlines, FLG::dollar, FLG::endian, FLG::errorlimit, FLG::es, FLG::extend_source, flg, gbl, i, FLG::i4, FLG::idir, FLG::ieee, FLG::include, FLG::inform, FLG::inliner, FLG::line, FLG::list, FLG::locchk, NULL, FLG::object, FLG::onetrip, FLG::opt, FLG::p, FLG::profile, putdefarray(), putint(), putintarray(), putline(), putnzint(), putnzINT(), putstring(), putstringarray(), FLG::qa, FLG::quad, FLG::recursive, FLG::save, FLG::smp, FLG::standard, FLG::stdinc, FLG::symbol, FLG::terse, FLG::tpcount, FLG::tpvalue, FLG::trans_inv, FLG::ucase, FLG::vect, FLG::x, FLG::xoff, FLG::xon, and FLG::xref.
Referenced by init().
dgbl()
void dgbl (void)
...
Definition at line 2128 of file mwd.cpp.
References GBL::asgnlbls, GBL::asmfil, GBL::autobj, GBL::basevars, GBL::bss_addr, GBL::bssvars, GBL::caddr, GBL::cmblks, GBL::consts, GBL::cppfil, GBL::cuda_constructor, GBL::cudaemu, GBL::curr_file, GBL::currsub, GBL::datetime, GBL::dbgfil, GBL::denorm, dfile, GBL::ec_avail, GBL::entbih, GBL::entries, GBL::externs, GBL::file_name, GBL::findex, GBL::fperror_status, GBL::ftn_true, GBL::func_count, GBL::funcline, gbl, i, GBL::ilmfil, GBL::in_include, GBL::internal, GBL::lineno, GBL::locaddr, GBL::locals, GBL::maxsev, GBL::module, GBL::multi_func_count, GBL::multiversion, GBL::nofperror, GBL::nowarn, NULL, GBL::numversions, GBL::objfil, GBL::outersub, GBL::paddr, GBL::pgfi_avail, GBL::prvt_sym_sz, putline(), putnstring(), putnsym(), putnzint(), putnzisz(), putsym(), putsymlk(), GBL::rutype, GBL::saddr, SPTR_NULL, GBL::src_file, GBL::srcfil, GBL::statics, GBL::stk_sym_sz, GBL::threadprivate, and GBL::vfrets.
Referenced by init().
dili()
void dili (int ilix)
...
Definition at line 3991 of file mwd.cpp.
References ACONOFFG, dfile, full, gbl, IL_NAME, IL_OPRFLAG, IL_OPRS, IL_TYPE, ILI_ALT, ILI_COUNT, ILI_HSHLNK, ILI_OPC, ILI_OPND, ILI_VISIT, ILI_VLIST, ilib, ILIO_128LNK, ILIO_256LNK, ILIO_512LNK, ILIO_AR, ILIO_ARLNK, ILIO_CDLNK, ILIO_CQLNK, ILIO_CSLNK, ILIO_DP, ILIO_DPLNK, ILIO_FLOAT128LNK, ILIO_IR, ILIO_IRLNK, ILIO_KR, ILIO_KRLNK, ILIO_LNK, ILIO_NME, ILIO_OFF, ILIO_QP, ILIO_QPLNK, ILIO_SP, ILIO_SPLNK, ILIO_STC, ILIO_SYM, j, put2int(), putint(), putline(), putnme(), putnsym(), putnzbigint(), putnzint(), putpint(), putstc(), putstring(), putstring1(), putsym(), putval1(), SIZEOF, and SymConval1.
Referenced by dilitreex().
dilitre()
void dilitre (int ilix)
...
Definition at line 4291 of file mwd.cpp.
References dilitreex(), and prefix.
Referenced by dumpblock(), dumpilt(), dumpWidenVars(), and inlarr().
dilt()
void dilt (int ilt)
...
Definition at line 4303 of file mwd.cpp.
References dfile, full, gbl, ilt, ILT_BR, ILT_CAN_THROW, ILT_CPLX, ILT_DBGLINE, ILT_DELEBB, ILT_DELETE, ILT_EQASRT, ILT_EX, ILT_FINDEX, ILT_FREE, ILT_IGNORE, ILT_ILIP, ILT_KEEP, ILT_LINENO, ILT_MCACHE, ILT_NEXT, ILT_NODEL, ILT_PREDC, ILT_PREV, ILT_SPLIT, ILT_ST, iltb, NULL, putbit(), putint(), putline(), putnzint(), and putstring1().
Referenced by dumpblock(), dumpilt(), and dumpilts().
ds()
void ds (int sptr)
...
Definition at line 4204 of file dump.c.
References dsym(), and sptr.
Referenced by __fort_copy(), __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), ENTFTN(), export_symbol(), kmaxloc_common(), kminloc_common(), maxloc_common(), minloc_common(), msg(), queue_symbol(), scale_bytes(), and scale_kbytes().
dsa()
void dsa (void)
...
Definition at line 4210 of file dump.c.
References dsyms().
dss()
void dss (int l, int u)
...
Definition at line 4216 of file dump.c.
References dfile, dsyms(), and gbl.
dsym()
void dsym (int sptr)
...
Definition at line 2684 of file dump.c.
References ACONOFFG, ACONOFFP, BCOPY, check(), CMEMLG, CMEMLP, CONVAL2G, CONVAL2P, CUDAG, CUDAP, DECLLINEG, DEFLABG, DEFLABP, dfile, dsecd(), dsocptr(), DTY, ENDLINEG, ENDLINEP, FORALLNDXG, FORALLNDXP, full, FUNCLINEG, FUNCLINEP, gbl, getdtype(), getprint(), GREALG, GREALP, GSAMEG, GSAMEP, i, ILMG, ILMP, INHERITG, INTENTG, INTENTP, linelen, STB::n_base, STB::namavl, NEWDSCG, NEWDSCP, NML_NEXT, NML_SPTR, ORIGDUMMYG, ORIGDUMMYP, PARAMVALG, PARAMVALP, PDALNG, PDALNP, printname(), put_inkwd(), putbigint(), putbit(), putcuda(), putddtype(), putdtype(), putdtypex(), putinkind(), putint(), putintent(), putline(), putnname(), putnsc(), putnsym(), putnzbigint(), putnzint(), putparam(), putsc(), putsoc(), putstring(), putstype(), putsym(), putsym1(), putsymilist(), putsymlk(), RUNTIMEG, scope, SFDSCG, SFDSCP, sptr, SPTR_NULL, stb, STGetPointee, strlen(), XREFLKG, and XREFLKP.
Referenced by _linearize(), ds(), dsyms(), gen_allocate(), gen_bnd_assn(), print_ast(), pstride_analysis(), and stackvars().
dsyms()
void dsyms (int l, int u)
...
Definition at line 4189 of file dump.c.
References dfile, dsym(), STB::firstusym, i, and stb.
Referenced by dsa(), dss(), dump_all_symbols(), dump_current_symbols(), and dump_symbols().
dumpabnd()
void dumpabnd (int abx)
...
dumpabnds()
void dumpabnds (void)
...
dumpacacheinfo()
void dumpacacheinfo (int cx)
...
dumpacexprs()
void dumpacexprs (void)
...
dumpacivs()
void dumpacivs (void)
...
dumpacsymt()
void dumpacsymt (int first, int last)
...
dumpadef()
void dumpadef (int def)
...
dumpallloops()
void dumpallloops (void)
...
dumpallploops()
void dumpallploops (void)
...
dumpalooponly()
void dumpalooponly (int lpx)
...
dumpanmelist()
void dumpanmelist (int nmelist)
...
dumpanmetree()
void dumpanmetree (int nmex)
...
dumparef()
void dumparef (int arefx)
...
dumparefs()
void dumparefs (void)
...
dumparefxlist()
void dumparefxlist (int arefxlist)
...
dumpause()
void dumpause (int use)
...
dumpauselist()
void dumpauselist (int use)
...
dumpauses()
void dumpauses (void)
...
dumpblock()
void dumpblock (int block)
...
Definition at line 4510 of file mwd.cpp.
References BIH_ILTFIRST, bihb, db(), dfile, dilitre(), dilt(), ilt, ILT_ILIP, ILT_NEXT, iltb, and NULL.
Referenced by dbih(), and dumptblock().
dumpblocks()
void dumpblocks (const char * title)
...
Definition at line 4576 of file mwd.cpp.
References dbih(), dfile, and gbl.
Referenced by schedule(), and widenAddressArith().
dumpblocksonly()
void dumpblocksonly (void)
...
Definition at line 4570 of file mwd.cpp.
References dbihonly().
dumpddiff()
void dumpddiff (int v)
...
Definition at line 84 of file mwd.cpp.
References full.
dumpdef()
void dumpdef (int def)
...
Definition at line 4723 of file dump.c.
References def, DEF_ADDR, DEF_ARG, DEF_CONFL, DEF_CONST, DEF_CSEL, DEF_DELETE, DEF_DOEND, DEF_DOINIT, DEF_DU, DEF_FG, DEF_GEN, DEF_LHS, DEF_LNEXT, DEF_LOOPENTRY, DEF_NEXT, DEF_NM, DEF_OTHER, DEF_PRECISE, DEF_RHS, DEF_SELF, DEF_STD, dfile, gbl, OPT::ndefs, DU_TAG::next, NULL, opt, printnme(), putbit(), putint(), putint1(), putline(), putnzint(), putstring1(), and DU_TAG::use.
Referenced by dumpdeflist(), and dumpdefs().
dumpdeflist()
void dumpdeflist (int deflist)
...
Definition at line 4787 of file dump.c.
References d, def, DEF_NEXT, dfile, dumpdef(), gbl, OPT::ndefs, and opt.
dumpdefnmes()
void dumpdefnmes (void)
...
dumpdefs()
void dumpdefs (void)
...
Definition at line 4774 of file dump.c.
References def, dfile, dumpdef(), FIRST_DEF, gbl, OPT::ndefs, and opt.
Referenced by sectfloat().
dumpdfs()
void dumpdfs (void)
...
dumpdiff()
void dumpdiff (void)
...
Definition at line 78 of file mwd.cpp.
References full.
Referenced by init().
dumpdppolicies()
void dumpdppolicies ()
...
dumpdppolicy()
void dumpdppolicy (int policyid)
...
dumpdpshape()
void dumpdpshape (int shapeid)
...
dumpdpshapes()
void dumpdpshapes ()
...
dumpdtype()
void dumpdtype (DTYPE dtype)
...
Definition at line 2943 of file dtypeutl.c.
References AD_DPTR, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_SCHECK, AD_SDSC, AD_UPBD, AD_ZBASE, appendstring1(), dfile, dmp_dent(), STB::dt, DTY, DTyAlgTyAlign, DTyAlgTyMember, DTyAlgTySize, DTyAlgTyTag, DTyArgNext, DTyArgSym, DTyArgType, DTyCharLength, DTySeqTyElement, DTyVecLength, FLANG_FALLTHROUGH, gbl, i, putdty(), putdtype(), putint(), putline(), putnsym(), putnzint(), putsym(), stb, and TY_CHAR.
Referenced by ddtype(), dumpdtypes(), dumpnewdtypes(), and inlarr().
dumpdtypes()
void dumpdtypes (void)
...
Definition at line 4376 of file dump.c.
References dfile, dlen(), STB::dt, DTY, dumpdts(), dumpdtype(), gbl, and stb.
Referenced by ddtypes(), and init().
dumpdvl()
void dumpdvl (int d)
...
Definition at line 5081 of file mwd.cpp.
References aux, d, dfile, AUX::dvl_avl, AUX::dvl_base, DVL_CONVAL, DVL_SPTR, gbl, NULL, putint(), putINT(), putline(), and putsym().
Referenced by dumpdvls().
dumpdvls()
void dumpdvls (void)
...
Definition at line 5099 of file mwd.cpp.
References aux, d, dfile, dumpdvl(), AUX::dvl_avl, AUX::dvl_base, gbl, and NULL.
Referenced by init().
dumpfg()
void dumpfg (void)
...
dumpfgraph()
void dumpfgraph (void)
...
Definition at line 1820 of file dump.c.
References dfile, OPT::dfn, dumpfnode(), EDGE_PRED, EDGE_SUCC, gbl, NULL, OPT::num_nodes, opt, putedge(), putint1(), putline(), and VTX_NODE.
Referenced by redundss(), and sectfloat().
dumpfgraph2file()
void dumpfgraph2file (void)
...
dumpfile()
void dumpfile (int f)
...
dumpfiles()
void dumpfiles (void)
...
dumpfnode()
void dumpfnode (int v)
...
Definition at line 1740 of file dump.c.
References dfile, FG_ATOMIC, FG_CS, FG_CTLEQUIV, FG_DFN, FG_DOM, FG_EN, FG_EX, FG_FT, FG_HEAD, FG_INNERMOST, FG_JMP_TBL, FG_LABEL, FG_LINENO, FG_LNEXT, FG_LOOP, FG_LPREV, FG_MASTER, FG_MEXITS, FG_NATNXT, FG_NEXT, FG_PAR, FG_PARLOOP, FG_PARSECT, FG_PDOM, FG_PRED, FG_PTR_STORE, FG_STDFIRST, FG_STDLAST, FG_SUCC, FG_TAIL, FG_TASK, FG_XT, FG_ZTRP, gbl, NULL, OPT::num_nodes, opt, pred, PSI_FT, PSI_NEXT, PSI_NODE, PSI_P_NULL, putbit(), putint(), putint1star(), putline(), putnsym(), putnzint(), putstring(), and putstring1().
Referenced by dfg(), dumpfg(), and dumpfgraph().
dumpfnodehead()
void dumpfnodehead (int v)
...
dumpilt()
void dumpilt (int ilt)
...
Definition at line 4358 of file mwd.cpp.
References dilitre(), dilt(), ilt, ILT_ILIP, and iltb.
dumpiltdeflist()
void dumpiltdeflist (int iltx)
...
dumpiltmrlist()
void dumpiltmrlist (int iltx)
...
dumpilts()
void dumpilts (void)
...
Definition at line 4366 of file mwd.cpp.
References BIH_ILTFIRST, BIH_LAST, BIH_NEXT, bihb, db(), dfile, dilt(), gbl, ILT_NEXT, and NULL.
Referenced by init().
dumpiltuselist()
void dumpiltuselist (int iltx)
...
dumpind()
void dumpind (int i)
...
dumpinds()
void dumpinds (void)
...
dumpiv()
void dumpiv (int ivx)
...
dumpivlist()
void dumpivlist (void)
...
dumpliveinuses()
void dumpliveinuses (void)
...
dumpliveoutdefs()
void dumpliveoutdefs (void)
...
dumplong()
void dumplong (void)
...
Definition at line 66 of file mwd.cpp.
References longlines.
dumploop()
void dumploop (int l)
...
Definition at line 2140 of file dump.c.
References BIH_LINENO, dfile, FG_NEXT, FG_TO_BIH, gbl, LP_CALLFG, LP_CALLINTERNAL, LP_CHILD, LP_CNCALL, LP_CS, LP_CSECT, LP_EXITS, LP_EXT_STORE, LP_FG, LP_FORALL, LP_HEAD, LP_INNERMOST, LP_INVARIF, LP_JMP_TBL, LP_LEVEL, LP_MARK, LP_MASTER, LP_MEXITS, LP_NOBLA, LP_PARENT, LP_PARLOOP, LP_PARREGN, LP_PARSECT, LP_PTR_LOAD, LP_PTR_STORE, LP_QJSR, LP_SIBLING, LP_STL_PAR, LP_TAIL, LP_XTNDRNG, LP_ZEROTRIP, OPT::nloops, NULL, opt, p, PSI_NEXT, PSI_NODE, PSI_P_NULL, put2int(), putbit(), putint(), putint1(), putline(), putnme(), putnzint(), putstring(), putstring1(), and q.
Referenced by dumploops(), and dumpvnest2().
dumploops()
void dumploops (void)
...
Definition at line 2231 of file dump.c.
References dfile, dumploop(), gbl, LP_LOOP, OPT::nloops, NULL, and opt.
Referenced by redundss(), and sectfloat().
dumploopsbv()
void dumploopsbv (int bvlen)
...
dumplooptree()
void dumplooptree (void)
...
dumpmemref()
void dumpmemref (int m)
...
Definition at line 4557 of file dump.c.
References dumpmr().
dumpmemrefs()
void dumpmemrefs (void)
...
dumpmr()
void dumpmr (int m)
...
Definition at line 4503 of file dump.c.
References dfile, gbl, hlv, MR_ARRAY, MR_BASED, MR_CSEILI, MR_EXP, MR_EXPARR, MR_FG, MR_FSUBS, MR_ILI, MR_ILT, MR_INDIR, MR_INDUC, MR_INIT, MR_INVAL, MR_INVAR, MR_INVEC, MR_IV, MR_IVUSE, MR_LOOP, MR_NEST, MR_NEXT, MR_NME, MR_PREV, MR_REWR, MR_RG, MR_SCALR, MR_SCLR, MR_STMT, MR_SUBCNT, MR_SUBST, MR_SUCC, MR_TYPE, HLVECT::mravail, HLVECT::mrbase, NULL, putast(), putbit(), putcharacter(), putddlist(), putint(), putline(), putnme(), and putnzint().
Referenced by dumpmemref(), and dumpmemrefs().
dumpnatural()
void dumpnatural (void)
...
dumpnewdtypes()
void dumpnewdtypes (int olddtavail)
...
Definition at line 2836 of file mwd.cpp.
References dfile, dlen(), STB::dt, DTY, dumpdtype(), gbl, and stb.
dumpnme()
void dumpnme (int n)
...
Definition at line 2090 of file dump.c.
References _dumpnme(), d, DEF_NEXT, dfile, gbl, linelen, n, NME_CNST, NME_CNT, NME_DEF, NME_HSHLNK, NME_INLARR, NME_NM, NME_RFPTR, NME_STL, NME_SUB, NME_SYM, NME_TYPE, nmeb, NULL, putint(), putint1(), putline(), putnmetype(), putnsym(), putnzint(), and putstring1().
Referenced by dumpnmes().
dumpnmes()
void dumpnmes (void)
...
Definition at line 2124 of file dump.c.
References dfile, dumpnme(), gbl, n, nmeb, and NULL.
Referenced by init(), and sectfloat().
dumpnmetree()
void dumpnmetree (int n)
...
dumpnnme()
void dumpnnme (int n)
...
Definition at line 4866 of file mwd.cpp.
References _dumpnme(), linelen, n, and putline().
dumpnst()
void dumpnst (int n)
...
dumpnst2()
void dumpnst2 (int n)
...
dumpploop()
void dumpploop (int plpx)
...
dumpprivatelist()
void dumpprivatelist (void)
...
dumpred()
void dumpred (int r)
...
dumpreddeflist()
void dumpreddeflist (int deflist)
...
dumpredlist()
void dumpredlist (int r)
...
dumpreducdeflist()
void dumpreducdeflist (int defx)
...
dumpreducdefs()
void dumpreducdefs (void)
...
dumpregion()
void dumpregion (int r)
...
dumpregionnest()
void dumpregionnest (int r)
...
dumpregions()
void dumpregions (void)
...
dumprnest()
void dumprnest (void)
...
dumpscalar()
void dumpscalar (int s)
...
dumpscalarlist()
void dumpscalarlist (int ss)
...
dumpscalars()
void dumpscalars (void)
...
dumpshort()
void dumpshort (void)
...
Definition at line 72 of file mwd.cpp.
References longlines.
dumpsizes()
void dumpsizes (void)
...
dumpstmt()
void dumpstmt (int s)
...
dumpstmts()
void dumpstmts (void)
...
dumpstore()
void dumpstore (int s)
...
dumpstorelist()
void dumpstorelist (int s)
...
dumpsub()
void dumpsub (int s)
...
dumpsubs()
void dumpsubs (void)
...
dumptblock()
void dumptblock (const char * title, int block)
...
Definition at line 4526 of file mwd.cpp.
References dfile, dumpblock(), and gbl.
dumpuse()
void dumpuse (int use)
...
Definition at line 4799 of file dump.c.
References UD_TAG::def, dfile, gbl, UD_TAG::next, NULL, opt, printnme(), putbit(), putint(), putint1(), putline(), putnzint(), putstring1(), use, USE_ADDR, USE_ARG, USE_AST, USE_CSE, USE_DOINIT, USE_EXPOSED, USE_FG, USE_LOOPENTRY, USE_MARK1, USE_MARK2, USE_NM, USE_PRECISE, USE_STD, and USE_UD.
Referenced by dumpuses().
dumpuseddefs()
void dumpuseddefs (void)
...
dumpuseduses()
void dumpuseduses (void)
...
dumpuses()
void dumpuses (void)
...
Definition at line 4840 of file dump.c.
References dfile, dumpuse(), gbl, opt, and use.
Referenced by sectfloat().
dumpvdef()
void dumpvdef (int def)
...
dumpvilt()
void dumpvilt (int iltx)
...
dumpvind()
void dumpvind (int i)
...
Definition at line 4454 of file dump.c.
References dfile, gbl, hlv, i, HLVECT::indavail, HLVECT::indbase, NULL, putast(), putasttype(), putbit(), putint(), putline(), putnme(), VIND_ALAST, VIND_ALIAS, VIND_DELETE, VIND_INIT, VIND_LOAD, VIND_MIDF, VIND_NIU, VIND_NM, VIND_NOINV, VIND_OMIT, VIND_OPC, VIND_ORIGINIT, VIND_PTR, VIND_SAVE, VIND_SKIP, VIND_TOTSKIP, and VIND_VISIT.
Referenced by dumpvinds().
dumpvindl()
void dumpvindl (int i1, int n)
...
dumpvinds()
void dumpvinds (void)
...
dumpvloop()
void dumpvloop (int l)
...
Definition at line 4603 of file dump.c.
References dfile, dumpmemrefs(), dumpvinds(), gbl, hlv, HLVECT::lpavail, HLVECT::lpbase, NULL, putast(), putbit(), putint(), putline(), putmrlist(), putnzint(), putsclist(), VL_ALBND, VL_AUBND, VL_CAND, VL_DEL, VL_EALIST, VL_ICNT, VL_ILBND, VL_ISTART, VL_IUBND, VL_IVLIST, VL_LBND, VL_LPCNT, VL_MRCNT, VL_MRECNT, VL_MRSTART, VL_NEST, VL_PERF, VL_PREBIH, VL_SCLIST, VL_SIBLING, VL_UBND, VL_ZTRIP, VLP_ASSOC, VLP_DEPCHK, VLP_EQVCHK, VLP_LDSTSPLIT, VLP_LSTVAL, VLP_MINCNT, VLP_OPSPLIT, VLP_RECOG, VLP_SAFECALL, VLP_SHORTLP, and VLP_TRANS.
Referenced by dumpvnest(), and dumpvnest2().
dumpvlooplist()
void dumpvlooplist (int list)
...
dumpvloops()
void dumpvloops (void)
...
Definition at line 4672 of file dump.c.
References dfile, dumpvnest(), hlv, HLVECT::looplist, HLVECT::lpbase, NULL, and VL_SIBLING.
dumpvuse()
void dumpvuse (int use)
...
getprintnme()
char * getprintnme (int n)
...
pprintnme()
void pprintnme (int n)
...
Definition at line 4765 of file mwd.cpp.
References _printnme(), dfile, gbl, n, and putstring1().
Referenced by _dumpnme().
printblock()
void printblock (int block)
...
Definition at line 3833 of file mwd.cpp.
References BIH_ILTFIRST, bihb, BUF, BUFSIZE, db(), dfile, full, ilt, ILT_ILIP, ILT_LINENO, ILT_NEXT, iltb, NULL, putili(), putint(), putit(), and putline().
Referenced by printblocks(), printblockt(), and printblocktt().
printblockline()
void printblockline (int block)
...
Definition at line 3855 of file mwd.cpp.
References BIH_ILTFIRST, bihb, BUF, BUFSIZE, db(), dfile, full, ilt, ILT_FINDEX, ILT_ILIP, ILT_LINENO, ILT_NEXT, iltb, NULL, putili(), putint(), putit(), and putline().
Referenced by printblocksline().
printblocks()
void printblocks (void)
...
Definition at line 3878 of file mwd.cpp.
References BIH_LAST, BIH_NEXT, bihb, CUDAG, dfile, full, gbl, GBL_CURRFUNC, NULL, printblock(), putcuda(), and SYMNAME.
Referenced by init().
printblocksline()
void printblocksline (void)
...
Definition at line 3971 of file mwd.cpp.
References BIH_LAST, BIH_NEXT, bihb, dfile, gbl, GBL_CURRFUNC, NULL, printblockline(), and SYMNAME.
printblockt()
void printblockt (int firstblock, int lastblock)
...
Definition at line 3908 of file mwd.cpp.
References b, BIH_LAST, BIH_NEXT, bihb, dfile, gbl, GBL_CURRFUNC, NULL, printblock(), and SYMNAME.
printblocktt()
void printblocktt (int firstblock, int lastblock)
...
Definition at line 3948 of file mwd.cpp.
References BIH_LAST, BIH_NEXT, bihb, dfile, gbl, GBL_CURRFUNC, NULL, printblock(), and SYMNAME.
printfgraph()
void printfgraph (void)
...
printfnode()
void printfnode (int v)
...
printili()
void printili (int i)
...
Definition at line 3791 of file mwd.cpp.
References _printili(), i, and linelen.
printilt()
void printilt (int i)
...
call _printilt with linelen = 0, so no prefix blanks are added
Definition at line 3802 of file mwd.cpp.
References _printili(), BUF, BUFSIZE, dfile, gbl, i, ILT_ILIP, ILT_LINENO, iltb, linelen, putit(), and putline().
printloop()
void printloop (int lpx)
...
printname()
char * printname (int sptr)
...
Definition at line 1910 of file dump.c.
References ACONOFFG, b, CONVAL2G, cprintf(), DTY, ISZ_PF, ISZ_T, len, STB::n_base, num, s, sptr, stb, SYMNAME, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_SLOG, TY_WORD, ui64toax(), and val.
Referenced by _printili(), _printnme(), appendsym1(), dsym(), putsym(), and putsym1().
printnme()
void printnme (int n)
...
Definition at line 2082 of file dump.c.
References _printnme(), dfile, gbl, linelen, n, and putstring1().
Referenced by dumpdef(), and dumpuse().
printregion()
void printregion (int r)
...
printregionnest()
void printregionnest (const char * msg, int r)
...
printregions()
void printregions (void)
...
putarefherelists()
void putarefherelists (int lpx)
...
putareflists()
void putareflists (int lpx)
...
putasub()
void putasub (int asubx, int nest)
...
putcoeff()
void putcoeff (int coefx, int nest)
...
putdty()
int putdty (TY_KIND dty)
...
Definition at line 2392 of file mwd.cpp.
References appendint1(), appendstring1(), r, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by _putdtype(), dumpdtype(), and putdtypex().
putdtype()
void putdtype (DTYPE dtype)
...
Definition at line 2636 of file mwd.cpp.
References _putdtype().
Referenced by dumpdtype().
putili()
void putili (const char * name, int ilix)
...
Definition at line 3819 of file mwd.cpp.
References _printili(), BUF, BUFSIZE, full, name, and putit().
Referenced by printblock(), and printblockline().
putint1()
void putint1 (int d)
...
Definition at line 260 of file mwd.cpp.
References BUF, BUFSIZE, d, and putit().
putlpxareflist()
void putlpxareflist (int lpx, const char * listname, int list, int nest)
...
putmode()
void putmode (int mode)
...
putmwline()
void putmwline (void)
...
Definition at line 132 of file mwd.cpp.
References putline().
putnestarefherelists()
void putnestarefherelists (int lpx)
...
putnme()
void putnme (const char * s, int nme)
...
Definition at line 546 of file mwd.cpp.
References _printnme(), BUF, BUFSIZE, full, nmeb, putit(), and s.
Referenced by dili().
putnnaref()
void putnnaref (int arefx, int nest)
...
putptelist()
void putptelist (int pte)
...
Referenced by _dumpnme().
putredtype()
void putredtype (int rt)
...
putsclist()
void putsclist (const char * name, int list)
...
Definition at line 4585 of file dump.c.
References putbit(), putint(), putline(), putnme(), putnsym(), putstring1(), s, SCLR_ARRSYM, SCLR_FLAG, SCLR_MASKSYM, SCLR_NEXT, SCLR_NME, and SCLR_SPAN.
Referenced by dumpvloop().
putsoc()
void putsoc (int socptr)
...
Referenced by dsym().
putsubs()
void putsubs (int s1, int n1)
...
simpledumpregion()
void simpledumpregion (int r)
...
simpledumpstmt()
void simpledumpstmt (int s)
...
simpleprintregion()
void simpleprintregion (int r)
...
simpleprintregionnest()
void simpleprintregionnest (const char * msg, int r)
...
stackcheck()
void stackcheck (void)
...
Definition at line 5131 of file mwd.cpp.
References addr, dfile, gbl, i, j, malloc(), NOSYM, putdtypex(), size, size_of(), sptr, stack, and SYMNAME.
Referenced by init().
stackvars()
void stackvars (void)
...
Definition at line 5117 of file mwd.cpp.
References dfile, dsym(), gbl, NOSYM, and sptr.
Referenced by init().