flang: mwd.cpp File Reference
mwd.cpp File Reference
mw's dump routines
#include "mwd.h"
#include "error.h"
#include "machar.h"
#include "global.h"
#include "symtab.h"
#include "ilm.h"
#include "fih.h"
#include "ili.h"
#include "iliutil.h"
#include "dtypeutl.h"
#include "machreg.h"
#include "llutil.h"
#include "symfun.h"
#include <stdarg.h>
Macros
#define BUFSIZE 10000
#define SIZEOF(array) (sizeof(array) / sizeof(char *))
#define OT_UNARY 1
#define OT_BINARY 2
#define OT_LEAF 3
#define NONE 0
#define UNOP 1
#define postUNOP 2
#define BINOP 3
#define INTRINSIC 4
#define MVREG 5
#define DFREG 6
#define PSCOMM 7
#define ENC_N_OP 8
Functions
static int putdtypex (DTYPE dtype, int len)
static void _printnme (int n)
int testcurrfunc (const char *func)
void dumplong (void)
...
void dumpshort (void)
...
void dumpdiff (void)
...
void dumpddiff (int v)
...
static void putit (void)
static void puttight (void)
static void putline (void)
void putmwline ()
...
static void puterr (const char *fmt,...)
static void appendit (void)
static void putint (const char *s, int d)
static void putdouble (const char *s, double d)
static void putbigint (const char *s, ISZ_T d)
static void putINT (const char *s, INT d)
static void putintarray (const char *s, int *x, int size)
static void putnzint (const char *s, int d)
static void putnzbigint (const char *s, ISZ_T d)
static void putnzINT (const char *s, INT d)
static void putnzisz (const char *s, ISZ_T d)
static void put2int (const char *s, int d1, int d2)
static void putpint (const char *s, int d)
void putint1 (int d)
...
static int appendint1 (int d)
static int appendbigint (ISZ_T d)
static void appendhex1 (int d)
static void putbit (const char *s, int b)
static void putstring (const char *s, const char *t)
static void putnstring (const char *s, const char *t)
static void putstringarray (const char *s, char **arr)
static void putdefarray (const char *s, char **arr)
static void putstring1 (const char *t)
static void putstring1t (const char *t)
static int appendstring1 (const char *t)
static void putsym (const char *s, SPTR sptr)
static void putnsym (const char *s, SPTR sptr)
static void putsym1 (int sptr)
static int appendsym1 (int sptr)
static void putsc (const char *s, int sc)
static void putnsc (const char *s, int sc)
static void putstype (const char *s, int stype)
static void putddtype (const char *s, DTYPE d)
static void putnname (const char *s, int off)
static void putsymlk (const char *name, int list)
void putnme (const char *s, int nme)
...
static void putval1 (int val, const char *values[], int sizeofvalues)
static void check (const char *s, int v)
void dsym (int sptr)
...
void dsyms (int l, int u)
...
void ds (int sptr)
...
void dsa (void)
...
void dss (int l, int u)
...
void dgbl (void)
...
void dflg (void)
...
static bool simpledtype (DTYPE dtype)
int putdty (TY_KIND dty)
...
void _putdtype (DTYPE dtype, int structdepth)
...
void putdtype (DTYPE dtype)
...
void dumpdtype (DTYPE dtype)
...
void ddtype (DTYPE dtype)
...
void dumpdtypes (void)
...
void dumpnewdtypes (int olddtavail)
...
void ddtypes (void)
...
static char * smsz (int m)
static void putstc (ILI_OP opc, int opnum, int opnd)
static int optype (int opc)
static void _printili (int i)
static void appendtarget (int sptr)
void printili (int i)
...
void printilt (int i)
...
void putili (const char *name, int ilix)
...
void printblock (int block)
...
void printblockline (int block)
...
void printblocks (void)
...
void printblockt (int firstblock, int lastblock)
...
void printblocktt (int firstblock, int lastblock)
...
void printblocksline (void)
...
void dili (int ilix)
...
static void dilitreex (int ilix, int l, int notlast)
void dilitre (int ilix)
...
void dilt (int ilt)
...
void dumpilt (int ilt)
...
void dumpilts ()
...
void db (int block)
...
void dumpblock (int block)
...
void dumptblock (const char *title, int block)
...
void dbih (void)
...
void dbihonly (void)
...
void dumpblocksonly (void)
...
void dumpblocks (const char *title)
...
void pprintnme (int n)
...
void printnme (int n)
...
void _dumpnme (int n, bool dumpdefsuses)
...
void dumpnnme (int n)
...
void dumpnme (int n)
...
void dumpnmes (void)
...
char * printname (int sptr)
...
void dumpdvl (int d)
...
void dumpdvls ()
...
void stackvars ()
...
void stackcheck ()
...
Variables
static bool g_dout = true
static FILE * dfile
static int linelen = 0
static char BUF [BUFSIZE]
static int longlines = 1
static int tight = 0
static int nexttight = 0
static int full = 1
static char prefix [1500]
static const char * nmetypes []
Detailed Description
mw's dump routines
Definition in file mwd.cpp.
Macro Definition Documentation
BINOP
#define BINOP 3
BUFSIZE
#define BUFSIZE 10000
Definition at line 41 of file mwd.cpp.
DFREG
#define DFREG 6
ENC_N_OP
#define ENC_N_OP 8
INTRINSIC
#define INTRINSIC 4
MVREG
#define MVREG 5
NONE
#define NONE 0
OT_BINARY
#define OT_BINARY 2
Definition at line 2929 of file mwd.cpp.
OT_LEAF
#define OT_LEAF 3
Definition at line 2930 of file mwd.cpp.
OT_UNARY
#define OT_UNARY 1
Definition at line 2928 of file mwd.cpp.
postUNOP
#define postUNOP 2
PSCOMM
#define PSCOMM 7
SIZEOF
#define SIZEOF (array) (sizeof(array) / sizeof(char *))
Definition at line 588 of file mwd.cpp.
UNOP
#define UNOP 1
Function Documentation
_dumpnme()
void _dumpnme (int n, bool dumpdefsuses)
...
Definition at line 4784 of file mwd.cpp.
References dfile, full, gbl, n, NME_BASE, NME_CNST, NME_CNT, NME_HSHLNK, NME_INLARR, NME_MASK, NME_NM, NME_NULL, NME_PTE, NME_RAT, NME_STL, NME_SUB, NME_SYM, NME_TYPE, nmeb, nmetypes, NT_ARR, NT_IND, NT_MEM, NT_UNK, NT_VAR, NULL, pprintnme(), putint(), putline(), putnzint(), putptelist(), putstring1(), putsym(), putval1(), SIZEOF, and stb.
Referenced by dumpnme(), and dumpnnme().
_printili()
static void _printili (int i) static
Definition at line 2974 of file mwd.cpp.
References _printili(), _printnme(), ACONOFFG, appendbigint(), appendhex1(), appendint1(), appendstring1(), appendsym1(), appendtarget(), BINOP, DBGBIT, dfile, DFREG, ENC_N_OP, FLANG_FALLTHROUGH, full, g_dout, gbl, i, IL_AADD, IL_ASUB, IL_IADD, IL_IDIV, IL_IMUL, IL_INEG, IL_ISUB, IL_MOD, IL_OPRFLAG, ILI_OPC, ILI_OPND, ilib, ILIO_128LNK, ILIO_256LNK, ILIO_512LNK, ILIO_AR, ILIO_ARLNK, ILIO_CDLNK, ILIO_CQLNK, ILIO_CSLNK, ILIO_DOUBLEDOUBLELNK, ILIO_DPLNK, ILIO_IR, ILIO_IRLNK, ILIO_KR, ILIO_KRLNK, ILIO_LNK, ILIO_NME, ILIO_NULL, ILIO_OFF, ILIO_QPLNK, ILIO_SP, ILIO_SPLNK, ILIO_SYM, ILIO_X87LNK, ILIO_XMM, ilis, INTRINSIC, j, k, KR_LSH, KR_MSH, label, MVREG, n, name, NONE, NOSYM, ILIINFO::oprs, optype(), OT_LEAF, OT_UNARY, postUNOP, printname(), PSCOMM, stb, and UNOP.
Referenced by _printili(), _printnme(), printili(), printilt(), and putili().
_printnme()
static void _printnme (int n) static
Definition at line 4674 of file mwd.cpp.
References _printili(), _printnme(), appendint1(), appendstring1(), dfile, gbl, n, NME_CNST, NME_NM, NME_NULL, NME_SUB, NME_SYM, NME_TYPE, nmeb, NOSYM, NT_ARR, NT_IND, NT_MEM, NT_UNK, NT_VAR, printname(), putint(), and stb.
Referenced by _printili(), _printnme(), pprintnme(), printnme(), and putnme().
_putdtype()
void _putdtype (DTYPE dtype, int structdepth)
...
Definition at line 2531 of file mwd.cpp.
References _putdtype(), AD_DPTR, AD_LWBD, AD_NUMDIM, AD_UPBD, appendint1(), appendstring1(), appendsym1(), dfile, STB::dt, DTY, DTyAlgTyMember, DTyAlgTyTag, DTyAlgTyTagNeg, DTyArgNext, DTyArgSym, DTyArgType, DTyCharLength, DTySeqTyElement, DTySet, gbl, i, NOSYM, putdty(), simpledtype(), SPTR_NULL, stb, and TY_CHAR.
Referenced by _putdtype(), and putdtype().
appendbigint()
static int appendbigint (ISZ_T d) static
Definition at line 282 of file mwd.cpp.
References appendit(), BUF, BUFSIZE, d, g_dout, ISZ_PF, and r.
Referenced by _printili().
appendhex1()
static void appendhex1 (int d) static
Definition at line 297 of file mwd.cpp.
References appendit(), BUF, BUFSIZE, and d.
Referenced by _printili().
appendint1()
static int appendint1 (int d) static
Definition at line 267 of file mwd.cpp.
References appendit(), BUF, BUFSIZE, d, g_dout, and r.
Referenced by _printili(), _printnme(), _putdtype(), appendtarget(), putdty(), and putdtypex().
appendit()
static void appendit (void) static
Definition at line 153 of file mwd.cpp.
References BUF, dfile, g_dout, linelen, nexttight, and strlen().
Referenced by appendbigint(), appendhex1(), appendint1(), appendstring1(), and appendsym1().
appendstring1()
static int appendstring1 (const char * t) static
Definition at line 385 of file mwd.cpp.
References appendit(), BUF, BUFSIZE, g_dout, r, and t.
Referenced by _printili(), _printnme(), _putdtype(), appendtarget(), dumpdtype(), putdty(), and putdtypex().
appendsym1()
static int appendsym1 (int sptr) static
Definition at line 455 of file mwd.cpp.
References appendit(), BUF, BUFSIZE, NOSYM, printname(), r, sptr, and stb.
Referenced by _printili(), _putdtype(), and putdtypex().
appendtarget()
static void appendtarget (int sptr) static
Definition at line 2964 of file mwd.cpp.
References appendint1(), appendstring1(), sptr, and stb.
Referenced by _printili().
check()
static void check (const char * s, int v) static
Definition at line 680 of file mwd.cpp.
References dfile, and s.
Referenced by dsym().
db()
void db (int block)
...
Definition at line 4387 of file mwd.cpp.
References BIH_ACCDATA, BIH_ACCEL, BIH_ASM, BIH_ASSN, BIH_BLKCNT, BIH_COMBST, BIH_CS, BIH_DELETABLE, BIH_DOCONC, BIH_EN, BIH_ENDACCDATA, BIH_ENDACCEL, BIH_ENDKERNEL, BIH_ENLAB, BIH_EX, BIH_EXSDSCUNSAFE, BIH_FINDEX, BIH_FT, BIH_FTAG, BIH_GUARDEE, BIH_GUARDER, BIH_HEAD, BIH_ILTFIRST, BIH_ILTLAST, BIH_INNERMOST, BIH_INVIF, BIH_KERNEL, BIH_LABEL, BIH_LAST, BIH_LDVOL, BIH_LINENO, BIH_MARK, BIH_MARK2, BIH_MARK3, BIH_MEXITS, BIH_MIDIOM, BIH_NEXT, BIH_NOBLA, BIH_NODEPCHK, BIH_NOINVIF, BIH_NOMERGE, BIH_NOSIMD, BIH_NOUNROLL, BIH_OZCR, BIH_PAR, BIH_PARALN, BIH_PARLOOP, BIH_PARSECT, BIH_PL, BIH_PREV, BIH_QJSR, BIH_RD, BIH_RESID, BIH_RGSET, BIH_SIMD, BIH_SMOVE, BIH_STREG, BIH_STVOL, BIH_TAIL, BIH_TASK, BIH_UJRES, BIH_UNROLL, BIH_UNROLL_COUNT, BIH_VCAND, BIH_VPAR, BIH_XT, BIH_ZTRP, bihb, dfile, FIH_DIRNAME, FIH_FILENAME, FIH_FUNCNAME, fihb, full, gbl, NULL, putbit(), putdouble(), puterr(), putint(), putline(), putnsym(), putnzint(), putstring1(), putstring1t(), and FIHB::stg_avail.
Referenced by __fort_copy(), __fort_copy_out(), __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), __fort_reverse_array(), add_debug_cmnblk_variables(), cleanup_bounds(), dbihonly(), dtype_array_check_set(), dumpblock(), dumpilts(), emit_deref_expression_mdnode(), ENTF90(), ENTFTN(), formalsAddDebug(), get_extra_info_for_sptr(), get_file_mdnode(), get_filedesc_mdnode(), get_lexical_block_info(), get_param_mdnode(), init_subrange_bound(), init_subrange_bound_pre11(), kmaxloc_common(), kminloc_common(), lldbg_add_pending_import_entity(), lldbg_add_pending_import_entity_to_child(), lldbg_assign_lexical_block(), lldbg_assign_lexical_blocks(), lldbg_cancel_value_call(), lldbg_cleanup_missing_bounds(), lldbg_cons_line(), lldbg_create_aggregate_members_type(), lldbg_create_aggregate_type_mdnode(), lldbg_create_array_type_mdnode(), lldbg_create_assumed_len_string_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_block_mdnode(), lldbg_create_common_block_mdnode(), lldbg_create_compile_unit_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_file_mdnode(), lldbg_create_ftn_array_type_mdnode(), lldbg_create_ftn_subrange_mdnode(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_create_generic_subrange_mdnode(), lldbg_create_global_variable_mdnode(), lldbg_create_imported_entity(), lldbg_create_local_variable_mdnode(), lldbg_create_location_mdnode(), lldbg_create_member_mdnode(), lldbg_create_module_flag_mdnode(), lldbg_create_module_mdnode(), lldbg_create_outlined_parameters_node(), lldbg_create_pointer_type_mdnode(), lldbg_create_string_type_mdnode(), lldbg_create_structure_type_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_create_subrange_mdnode(), lldbg_create_subrange_mdnode_pre11(), lldbg_create_subrange_via_sdsc(), lldbg_create_subroutine_type_mdnode(), lldbg_create_union_type_mdnode(), lldbg_create_unspecified_mdnode(), lldbg_create_unspecified_parameters_mdnode(), lldbg_create_vector_type_mdnode(), lldbg_emit_common_block_mdnode(), lldbg_emit_compile_unit(), lldbg_emit_empty_expression_mdnode(), lldbg_emit_expression_mdnode(), lldbg_emit_file(), lldbg_emit_global_variable(), lldbg_emit_imported_entity(), lldbg_emit_lexical_block(), lldbg_emit_lexical_blocks(), lldbg_emit_line(), lldbg_emit_local_variable(), lldbg_emit_lv_list(), lldbg_emit_modified_type(), lldbg_emit_module_mdnode(), lldbg_emit_outlined_parameter_list(), lldbg_emit_outlined_subprogram(), lldbg_emit_outlined_subroutine(), lldbg_emit_param_variable(), lldbg_emit_parameter_list(), lldbg_emit_ptr_param_variable(), lldbg_emit_subprogram(), lldbg_emit_subroutine_type(), lldbg_emit_type(), lldbg_free(), lldbg_function_end(), lldbg_fwd_local_variable(), lldbg_get_bounds_for_assumed_rank_sdsc(), lldbg_get_bounds_for_sdsc(), lldbg_get_di_routine_idx(), lldbg_get_line(), lldbg_get_subprogram_line(), lldbg_get_var_line(), lldbg_init(), lldbg_init_arrays(), lldbg_limit_lexical_blocks(), lldbg_register_param_mdnode(), lldbg_register_value_call(), lldbg_reserve_lexical_block(), lldbg_reserve_lexical_blocks(), lldbg_reset_dtype_array(), lldbg_reset_module(), lldbg_set_func_ptr(), lldbg_subprogram(), lldbg_update_arrays(), local_copy(), make_dwtag(), maxloc_common(), minloc_common(), printblock(), printblockline(), process_global_lifetime_debug(), ptr_in(), recopy(), set_disubprogram_flags(), set_disubprogram_spflags(), sourced_alloc_and_assign(), and void().
dbih()
void dbih (void)
...
Definition at line 4534 of file mwd.cpp.
References BIH_LAST, BIH_NEXT, bihb, dfile, dumpblock(), gbl, and NULL.
Referenced by dumpblocks(), and init().
dbihonly()
void dbihonly (void)
...
Definition at line 4552 of file mwd.cpp.
References BIH_LAST, BIH_NEXT, bihb, db(), dfile, gbl, and NULL.
Referenced by dumpblocksonly(), and init().
ddtype()
void ddtype (DTYPE dtype)
...
Definition at line 2817 of file mwd.cpp.
References dumpdtype().
Referenced by _linearize(), amd64_update_class(), ll_convert_array_dtype(), mkvarref(), and name_dependent_check().
ddtypes()
void ddtypes (void)
...
Definition at line 2848 of file mwd.cpp.
References dumpdtypes().
dflg()
void dflg (void)
...
Definition at line 2252 of file mwd.cpp.
References FLG::anno, FLG::asmcode, FLG::astype, FLG::autoinline, FLG::code, FLG::dalign, FLG::dbg, FLG::dclchk, FLG::debug, FLG::def, FLG::depchk, FLG::depwarn, dfile, FLG::dlines, FLG::dollar, FLG::endian, FLG::errorlimit, FLG::es, FLG::extend_source, flg, gbl, i, FLG::i4, FLG::idir, FLG::ieee, FLG::include, FLG::inform, FLG::inliner, FLG::line, FLG::list, FLG::locchk, NULL, FLG::object, FLG::onetrip, FLG::opt, FLG::p, FLG::profile, putdefarray(), putint(), putintarray(), putline(), putnzint(), putnzINT(), putstring(), putstringarray(), FLG::qa, FLG::quad, FLG::recursive, FLG::save, FLG::smp, FLG::standard, FLG::stdinc, FLG::symbol, FLG::terse, FLG::tpcount, FLG::tpvalue, FLG::trans_inv, FLG::ucase, FLG::vect, FLG::x, FLG::xoff, FLG::xon, and FLG::xref.
Referenced by init().
dgbl()
void dgbl (void)
...
Definition at line 2128 of file mwd.cpp.
References GBL::asgnlbls, GBL::asmfil, GBL::autobj, GBL::basevars, GBL::bss_addr, GBL::bssvars, GBL::caddr, GBL::cmblks, GBL::consts, GBL::cppfil, GBL::cuda_constructor, GBL::cudaemu, GBL::curr_file, GBL::currsub, GBL::datetime, GBL::dbgfil, GBL::denorm, dfile, GBL::ec_avail, GBL::entbih, GBL::entries, GBL::externs, GBL::file_name, GBL::findex, GBL::fperror_status, GBL::ftn_true, GBL::func_count, GBL::funcline, gbl, i, GBL::ilmfil, GBL::in_include, GBL::internal, GBL::lineno, GBL::locaddr, GBL::locals, GBL::maxsev, GBL::module, GBL::multi_func_count, GBL::multiversion, GBL::nofperror, GBL::nowarn, NULL, GBL::numversions, GBL::objfil, GBL::outersub, GBL::paddr, GBL::pgfi_avail, GBL::prvt_sym_sz, putline(), putnstring(), putnsym(), putnzint(), putnzisz(), putsym(), putsymlk(), GBL::rutype, GBL::saddr, SPTR_NULL, GBL::src_file, GBL::srcfil, GBL::statics, GBL::stk_sym_sz, GBL::threadprivate, and GBL::vfrets.
Referenced by init().
dili()
void dili (int ilix)
...
Definition at line 3991 of file mwd.cpp.
References ACONOFFG, dfile, full, gbl, IL_NAME, IL_OPRFLAG, IL_OPRS, IL_TYPE, ILI_ALT, ILI_COUNT, ILI_HSHLNK, ILI_OPC, ILI_OPND, ILI_VISIT, ILI_VLIST, ilib, ILIO_128LNK, ILIO_256LNK, ILIO_512LNK, ILIO_AR, ILIO_ARLNK, ILIO_CDLNK, ILIO_CQLNK, ILIO_CSLNK, ILIO_DP, ILIO_DPLNK, ILIO_FLOAT128LNK, ILIO_IR, ILIO_IRLNK, ILIO_KR, ILIO_KRLNK, ILIO_LNK, ILIO_NME, ILIO_OFF, ILIO_QP, ILIO_QPLNK, ILIO_SP, ILIO_SPLNK, ILIO_STC, ILIO_SYM, j, put2int(), putint(), putline(), putnme(), putnsym(), putnzbigint(), putnzint(), putpint(), putstc(), putstring(), putstring1(), putsym(), putval1(), SIZEOF, and SymConval1.
Referenced by dilitreex().
dilitre()
void dilitre (int ilix)
...
Definition at line 4291 of file mwd.cpp.
References dilitreex(), and prefix.
Referenced by dumpblock(), dumpilt(), dumpWidenVars(), and inlarr().
dilitreex()
static void dilitreex (int ilix, int l, int notlast) static
Definition at line 4192 of file mwd.cpp.
References dfile, dili(), dilitreex(), gbl, IL_ISLINK, IL_OPRS, ILI_ALT, ILI_OPC, ILI_OPND, ilib, j, and prefix.
Referenced by dilitre(), and dilitreex().
dilt()
void dilt (int ilt)
...
Definition at line 4303 of file mwd.cpp.
References dfile, full, gbl, ilt, ILT_BR, ILT_CAN_THROW, ILT_CPLX, ILT_DBGLINE, ILT_DELEBB, ILT_DELETE, ILT_EQASRT, ILT_EX, ILT_FINDEX, ILT_FREE, ILT_IGNORE, ILT_ILIP, ILT_KEEP, ILT_LINENO, ILT_MCACHE, ILT_NEXT, ILT_NODEL, ILT_PREDC, ILT_PREV, ILT_SPLIT, ILT_ST, iltb, NULL, putbit(), putint(), putline(), putnzint(), and putstring1().
Referenced by dumpblock(), dumpilt(), and dumpilts().
ds()
void ds (int sptr)
...
Definition at line 2108 of file mwd.cpp.
References dsym(), and sptr.
dsa()
void dsa (void)
...
Definition at line 2114 of file mwd.cpp.
References dsyms().
dss()
void dss (int l, int u)
...
Definition at line 2120 of file mwd.cpp.
References dfile, dsyms(), and gbl.
dsym()
void dsym (int sptr)
...
Definition at line 689 of file mwd.cpp.
References ACONOFFG, ACONOFFP, BCOPY, check(), CMEMLG, CMEMLP, CONVAL2G, CONVAL2P, CUDAG, CUDAP, DECLLINEG, DEFLABG, DEFLABP, dfile, DTY, ENDLINEG, ENDLINEP, full, FUNCLINEG, FUNCLINEP, gbl, GREALG, GREALP, GSAMEG, GSAMEP, i, ILMG, ILMP, linelen, STB::n_base, STB::namavl, NML_NEXT, NML_SPTR, ORIGDUMMYG, ORIGDUMMYP, PARAMVALG, PARAMVALP, PDALNG, PDALNP, printname(), putbigint(), putbit(), putcuda(), putddtype(), putdtypex(), putint(), putline(), putnname(), putnsc(), putnsym(), putnzbigint(), putnzint(), putparam(), putsoc(), putstring(), putstype(), putsym(), putsym1(), putsymlk(), SFDSCG, SFDSCP, sptr, SPTR_NULL, stb, STGetPointee, strlen(), XREFLKG, and XREFLKP.
Referenced by ds(), dsyms(), and stackvars().
dsyms()
void dsyms (int l, int u)
...
Definition at line 2092 of file mwd.cpp.
References dfile, dsym(), STB::firstusym, i, and stb.
Referenced by dsa(), and dss().
dumpblock()
void dumpblock (int block)
...
Definition at line 4510 of file mwd.cpp.
References BIH_ILTFIRST, bihb, db(), dfile, dilitre(), dilt(), ilt, ILT_ILIP, ILT_NEXT, iltb, and NULL.
Referenced by dbih(), and dumptblock().
dumpblocks()
void dumpblocks (const char * title)
...
Definition at line 4576 of file mwd.cpp.
References dbih(), dfile, and gbl.
Referenced by schedule(), and widenAddressArith().
dumpblocksonly()
void dumpblocksonly (void)
...
Definition at line 4570 of file mwd.cpp.
References dbihonly().
dumpddiff()
void dumpddiff (int v)
...
Definition at line 84 of file mwd.cpp.
References full.
dumpdiff()
void dumpdiff (void)
...
Definition at line 78 of file mwd.cpp.
References full.
Referenced by init().
dumpdtype()
void dumpdtype (DTYPE dtype)
...
Definition at line 2749 of file mwd.cpp.
References AD_DPTR, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_SCHECK, AD_SDSC, AD_UPBD, AD_ZBASE, appendstring1(), dfile, STB::dt, DTY, DTyAlgTyAlign, DTyAlgTyMember, DTyAlgTySize, DTyAlgTyTag, DTyArgNext, DTyArgSym, DTyArgType, DTyCharLength, DTySeqTyElement, DTyVecLength, FLANG_FALLTHROUGH, gbl, i, putdty(), putdtype(), putint(), putline(), putnsym(), putnzint(), putsym(), stb, and TY_CHAR.
Referenced by ddtype(), dumpdtypes(), and dumpnewdtypes().
dumpdtypes()
void dumpdtypes (void)
...
Definition at line 2823 of file mwd.cpp.
References dfile, dlen(), STB::dt, DTY, dumpdtype(), gbl, and stb.
Referenced by ddtypes().
dumpdvl()
void dumpdvl (int d)
...
Definition at line 5081 of file mwd.cpp.
References aux, d, dfile, AUX::dvl_avl, AUX::dvl_base, DVL_CONVAL, DVL_SPTR, gbl, NULL, putint(), putINT(), putline(), and putsym().
Referenced by dumpdvls().
dumpdvls()
void dumpdvls (void)
...
Definition at line 5099 of file mwd.cpp.
References aux, d, dfile, dumpdvl(), AUX::dvl_avl, AUX::dvl_base, gbl, and NULL.
Referenced by init().
dumpilt()
void dumpilt (int ilt)
...
Definition at line 4358 of file mwd.cpp.
References dilitre(), dilt(), ilt, ILT_ILIP, and iltb.
dumpilts()
void dumpilts (void)
...
Definition at line 4366 of file mwd.cpp.
References BIH_ILTFIRST, BIH_LAST, BIH_NEXT, bihb, db(), dfile, dilt(), gbl, ILT_NEXT, and NULL.
Referenced by init().
dumplong()
void dumplong (void)
...
Definition at line 66 of file mwd.cpp.
References longlines.
dumpnewdtypes()
void dumpnewdtypes (int olddtavail)
...
Definition at line 2836 of file mwd.cpp.
References dfile, dlen(), STB::dt, DTY, dumpdtype(), gbl, and stb.
dumpnme()
void dumpnme (int n)
...
Definition at line 4874 of file mwd.cpp.
References _dumpnme(), linelen, n, and putline().
Referenced by dumpnmes().
dumpnmes()
void dumpnmes (void)
...
Definition at line 4882 of file mwd.cpp.
References dfile, dumpnme(), gbl, n, nmeb, and NULL.
dumpnnme()
void dumpnnme (int n)
...
Definition at line 4866 of file mwd.cpp.
References _dumpnme(), linelen, n, and putline().
dumpshort()
void dumpshort (void)
...
Definition at line 72 of file mwd.cpp.
References longlines.
dumptblock()
void dumptblock (const char * title, int block)
...
Definition at line 4526 of file mwd.cpp.
References dfile, dumpblock(), and gbl.
optype()
static int optype (int opc) static
Definition at line 2933 of file mwd.cpp.
References IL_INEG, OT_BINARY, OT_LEAF, and OT_UNARY.
Referenced by _printili().
pprintnme()
void pprintnme (int n)
...
Definition at line 4765 of file mwd.cpp.
References _printnme(), dfile, gbl, n, and putstring1().
Referenced by _dumpnme().
printblock()
void printblock (int block)
...
Definition at line 3833 of file mwd.cpp.
References BIH_ILTFIRST, bihb, BUF, BUFSIZE, db(), dfile, full, ilt, ILT_ILIP, ILT_LINENO, ILT_NEXT, iltb, NULL, putili(), putint(), putit(), and putline().
Referenced by printblocks(), printblockt(), and printblocktt().
printblockline()
void printblockline (int block)
...
Definition at line 3855 of file mwd.cpp.
References BIH_ILTFIRST, bihb, BUF, BUFSIZE, db(), dfile, full, ilt, ILT_FINDEX, ILT_ILIP, ILT_LINENO, ILT_NEXT, iltb, NULL, putili(), putint(), putit(), and putline().
Referenced by printblocksline().
printblocks()
void printblocks (void)
...
Definition at line 3878 of file mwd.cpp.
References BIH_LAST, BIH_NEXT, bihb, CUDAG, dfile, full, gbl, GBL_CURRFUNC, NULL, printblock(), putcuda(), and SYMNAME.
Referenced by init().
printblocksline()
void printblocksline (void)
...
Definition at line 3971 of file mwd.cpp.
References BIH_LAST, BIH_NEXT, bihb, dfile, gbl, GBL_CURRFUNC, NULL, printblockline(), and SYMNAME.
printblockt()
void printblockt (int firstblock, int lastblock)
...
Definition at line 3908 of file mwd.cpp.
References b, BIH_LAST, BIH_NEXT, bihb, dfile, gbl, GBL_CURRFUNC, NULL, printblock(), and SYMNAME.
printblocktt()
void printblocktt (int firstblock, int lastblock)
...
Definition at line 3948 of file mwd.cpp.
References BIH_LAST, BIH_NEXT, bihb, dfile, gbl, GBL_CURRFUNC, NULL, printblock(), and SYMNAME.
printili()
void printili (int i)
...
Definition at line 3791 of file mwd.cpp.
References _printili(), i, and linelen.
printilt()
void printilt (int i)
...
call _printilt with linelen = 0, so no prefix blanks are added
Definition at line 3802 of file mwd.cpp.
References _printili(), BUF, BUFSIZE, dfile, gbl, i, ILT_ILIP, ILT_LINENO, iltb, linelen, putit(), and putline().
printname()
char * printname (int sptr)
...
Definition at line 4901 of file mwd.cpp.
References ACONOFFG, b, CONVAL2G, cprintf(), DTY, ISZ_PF, ISZ_T, len, STB::n_base, num, s, sptr, stb, SYMNAME, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_FLOAT, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_SLOG, TY_WORD, ui64toax(), and val.
Referenced by _printili(), _printnme(), appendsym1(), dsym(), putsym(), and putsym1().
printnme()
void printnme (int n)
...
Definition at line 4773 of file mwd.cpp.
References _printnme(), dfile, gbl, linelen, and n.
put2int()
static void put2int (const char * s, int d1, int d2) static
Definition at line 247 of file mwd.cpp.
References BUF, BUFSIZE, putit(), and s.
Referenced by dili(), and putpint().
putbigint()
static void putbigint (const char * s, ISZ_T d) static
Definition at line 181 of file mwd.cpp.
References BUF, BUFSIZE, d, ISZ_PF, putit(), and s.
Referenced by dsym().
putbit()
static void putbit (const char * s, int b) static
Definition at line 304 of file mwd.cpp.
References b, dfile, linelen, longlines, s, and strlen().
Referenced by db(), dilt(), and dsym().
putddtype()
static void putddtype (const char * s, DTYPE d) static
Definition at line 515 of file mwd.cpp.
References BUF, BUFSIZE, d, putdtypex(), putit(), and s.
Referenced by dsym().
putdefarray()
static void putdefarray (const char * s, char ** arr) static
Definition at line 351 of file mwd.cpp.
References BUF, BUFSIZE, i, NULL, putit(), putline(), and s.
Referenced by dflg().
putdouble()
static void putdouble (const char * s, double d) static
Definition at line 172 of file mwd.cpp.
References BUF, BUFSIZE, d, g_dout, putit(), and s.
Referenced by db().
putdty()
int putdty (TY_KIND dty)
...
Definition at line 2392 of file mwd.cpp.
References appendint1(), appendstring1(), r, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_FLOAT, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by _putdtype(), dumpdtype(), and putdtypex().
putdtype()
void putdtype (DTYPE dtype)
...
Definition at line 2636 of file mwd.cpp.
References _putdtype().
Referenced by dumpdtype().
putdtypex()
static int putdtypex (DTYPE dtype, int len) static
Definition at line 2642 of file mwd.cpp.
References AD_DPTR, AD_LWBD, AD_NUMDIM, AD_UPBD, appendint1(), appendstring1(), appendsym1(), dfile, STB::dt, DTY, DTyAlgTyMember, DTyAlgTyTag, DTyAlgTyTagNeg, DTyArgNext, DTyArgSym, DTyArgType, DTyCharLength, DTySeqTyElement, DTySet, gbl, i, len, NOSYM, putdty(), putdtypex(), r, simpledtype(), stb, and TY_CHAR.
Referenced by dsym(), putddtype(), putdtypex(), and stackcheck().
puterr()
static void puterr (const char * fmt, ...) static
Definition at line 140 of file mwd.cpp.
References BUF, BUFSIZE, putit(), and putline().
Referenced by db().
putili()
void putili (const char * name, int ilix)
...
Definition at line 3819 of file mwd.cpp.
References _printili(), BUF, BUFSIZE, full, name, and putit().
Referenced by printblock(), and printblockline().
putint()
static void putint (const char * s, int d) static
Definition at line 163 of file mwd.cpp.
References BUF, BUFSIZE, d, g_dout, putit(), and s.
Referenced by _dumpnme(), _printnme(), db(), dflg(), dili(), dilt(), dsym(), dumpdtype(), dumpdvl(), printblock(), printblockline(), and putstc().
putINT()
static void putINT (const char * s, INT d) static
Definition at line 188 of file mwd.cpp.
References BUF, BUFSIZE, d, putit(), and s.
Referenced by dumpdvl().
putint1()
void putint1 (int d)
...
Definition at line 260 of file mwd.cpp.
References BUF, BUFSIZE, d, and putit().
putintarray()
static void putintarray (const char * s, int * x, int size) static
Definition at line 195 of file mwd.cpp.
References BUF, BUFSIZE, i, NULL, putit(), putline(), s, size, and x.
Referenced by dflg().
putit()
static void putit (void) static
Definition at line 90 of file mwd.cpp.
References BUF, dfile, gbl, linelen, longlines, nexttight, strlen(), and tight.
Referenced by printblock(), printblockline(), printilt(), put2int(), putbigint(), putddtype(), putdefarray(), putdouble(), puterr(), putili(), putint(), putINT(), putint1(), putintarray(), putnme(), putnstring(), putnzbigint(), putnzint(), putnzINT(), putnzisz(), putsc(), putstring(), putstring1(), putstringarray(), putstype(), putsym(), putsym1(), and putval1().
putline()
static void putline (void) static
Definition at line 123 of file mwd.cpp.
References dfile, gbl, and linelen.
Referenced by _dumpnme(), db(), dflg(), dgbl(), dili(), dilt(), dsym(), dumpdtype(), dumpdvl(), dumpnme(), dumpnnme(), printblock(), printblockline(), printilt(), putdefarray(), puterr(), putintarray(), putmwline(), and putsymlk().
putmwline()
void putmwline (void)
...
Definition at line 132 of file mwd.cpp.
References putline().
putnme()
void putnme (const char * s, int nme)
...
Definition at line 546 of file mwd.cpp.
References _printnme(), BUF, BUFSIZE, full, nmeb, putit(), and s.
Referenced by dili().
putnname()
static void putnname (const char * s, int off) static
Definition at line 525 of file mwd.cpp.
References STB::n_base, off, putstring(), s, and stb.
Referenced by dsym().
putnsc()
static void putnsc (const char * s, int sc) static
Definition at line 489 of file mwd.cpp.
References putsc(), and s.
Referenced by dsym().
putnstring()
static void putnstring (const char * s, const char * t) static
Definition at line 330 of file mwd.cpp.
References BUF, BUFSIZE, NULL, putit(), s, and t.
Referenced by dgbl().
putnsym()
static void putnsym (const char * s, SPTR sptr) static
Definition at line 425 of file mwd.cpp.
References putsym(), s, and sptr.
Referenced by db(), dgbl(), dili(), dsym(), and dumpdtype().
putnzbigint()
static void putnzbigint (const char * s, ISZ_T d) static
Definition at line 220 of file mwd.cpp.
References BUF, BUFSIZE, d, ISZ_PF, putit(), and s.
Referenced by dili(), and dsym().
putnzint()
static void putnzint (const char * s, int d) static
Definition at line 211 of file mwd.cpp.
References BUF, BUFSIZE, d, putit(), and s.
Referenced by _dumpnme(), db(), dflg(), dgbl(), dili(), dilt(), dsym(), and dumpdtype().
putnzINT()
static void putnzINT (const char * s, INT d) static
Definition at line 229 of file mwd.cpp.
References BUF, BUFSIZE, d, putit(), and s.
Referenced by dflg().
putnzisz()
static void putnzisz (const char * s, ISZ_T d) static
Definition at line 238 of file mwd.cpp.
References BUF, BUFSIZE, d, ISZ_PF, putit(), and s.
Referenced by dgbl().
putpint()
static void putpint (const char * s, int d) static
Definition at line 254 of file mwd.cpp.
References d, put2int(), and s.
Referenced by dili().
putsc()
static void putsc (const char * s, int sc) static
Definition at line 470 of file mwd.cpp.
References BUF, BUFSIZE, full, putit(), s, STB::scnames, and stb.
Referenced by putnsc().
putstc()
static void putstc (ILI_OP opc, int opnum, int opnd) static
Definition at line 2913 of file mwd.cpp.
References ilstckind(), putint(), putstring(), scond(), and smsz().
Referenced by dili().
putstring()
static void putstring (const char * s, const char * t) static
Definition at line 323 of file mwd.cpp.
References BUF, BUFSIZE, putit(), s, and t.
Referenced by dflg(), dili(), dsym(), putnname(), and putstc().
putstring1()
static void putstring1 (const char * t) static
Definition at line 370 of file mwd.cpp.
References BUF, BUFSIZE, putit(), and t.
Referenced by _dumpnme(), db(), dili(), dilt(), pprintnme(), putsymlk(), and putval1().
putstring1t()
static void putstring1t (const char * t) static
Definition at line 377 of file mwd.cpp.
References BUF, BUFSIZE, nexttight, puttight(), and t.
Referenced by db().
putstringarray()
static void putstringarray (const char * s, char ** arr) static
Definition at line 339 of file mwd.cpp.
References BUF, BUFSIZE, i, NULL, putit(), and s.
Referenced by dflg().
putstype()
static void putstype (const char * s, int stype) static
Definition at line 496 of file mwd.cpp.
References BUF, BUFSIZE, full, putit(), s, stb, and STB::stypes.
Referenced by dsym().
putsym()
static void putsym (const char * s, SPTR sptr) static
Definition at line 399 of file mwd.cpp.
References BUF, BUFSIZE, full, NOSYM, printname(), putit(), s, sptr, and stb.
Referenced by _dumpnme(), dgbl(), dili(), dsym(), dumpdtype(), dumpdvl(), and putnsym().
putsym1()
static void putsym1 (int sptr) static
Definition at line 432 of file mwd.cpp.
References BUF, BUFSIZE, full, NOSYM, printname(), putit(), sptr, and stb.
Referenced by dsym(), and putsymlk().
putsymlk()
static void putsymlk (const char * name, int list) static
Definition at line 533 of file mwd.cpp.
References c, list, name, NOSYM, putline(), putstring1(), and putsym1().
Referenced by dgbl(), and dsym().
puttight()
static void puttight (void) static
Definition at line 114 of file mwd.cpp.
References BUF, dfile, gbl, linelen, and strlen().
Referenced by putstring1t().
putval1()
static void putval1 (int val, const char * values[], int sizeofvalues) static
Definition at line 591 of file mwd.cpp.
References BUF, BUFSIZE, putit(), putstring1(), and val.
Referenced by _dumpnme(), and dili().
simpledtype()
static bool simpledtype (DTYPE dtype) static
Definition at line 2378 of file mwd.cpp.
References dlen(), STB::dt, DTY, and stb.
Referenced by _putdtype(), and putdtypex().
smsz()
static char * smsz (int m) static
Definition at line 2856 of file mwd.cpp.
References m, msz, MSZ_BYTE, MSZ_F10, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_PTR, MSZ_SBYTE, MSZ_SHWORD, MSZ_SLWORD, MSZ_UHWORD, MSZ_ULWORD, MSZ_WORD, and NULL.
Referenced by putstc().
stackcheck()
void stackcheck (void)
...
Definition at line 5131 of file mwd.cpp.
References addr, dfile, gbl, i, j, malloc(), NOSYM, putdtypex(), size, size_of(), sptr, stack, and SYMNAME.
Referenced by init().
stackvars()
void stackvars (void)
...
Definition at line 5117 of file mwd.cpp.
References dfile, dsym(), gbl, NOSYM, and sptr.
Referenced by init().
testcurrfunc()
int testcurrfunc (const char * func)
Definition at line 48 of file mwd.cpp.
References func, GBL_CURRFUNC, and SYMNAME.
Variable Documentation
BUF
char BUF[BUFSIZE] static
Definition at line 42 of file mwd.cpp.
Referenced by appendbigint(), appendhex1(), appendint1(), appendit(), appendstring1(), appendsym1(), printblock(), printblockline(), printilt(), put2int(), putbigint(), putddtype(), putdefarray(), putdouble(), puterr(), putili(), putint(), putINT(), putint1(), putintarray(), putit(), putnme(), putnstring(), putnzbigint(), putnzint(), putnzINT(), putnzisz(), putsc(), putstring(), putstring1(), putstring1t(), putstringarray(), putstype(), putsym(), putsym1(), puttight(), and putval1().
dfile
FILE* dfile static
Definition at line 39 of file mwd.cpp.
Referenced by _dumpnme(), _printili(), _printnme(), _putdtype(), appendit(), check(), db(), dbih(), dbihonly(), dflg(), dgbl(), dili(), dilitreex(), dilt(), dss(), dsym(), dsyms(), dumpblock(), dumpblocks(), dumpdtype(), dumpdtypes(), dumpdvl(), dumpdvls(), dumpilts(), dumpnewdtypes(), dumpnmes(), dumptblock(), pprintnme(), printblock(), printblockline(), printblocks(), printblocksline(), printblockt(), printblocktt(), printilt(), printnme(), putbit(), putdtypex(), putit(), putline(), puttight(), stackcheck(), and stackvars().
full
int full = 1 static
Definition at line 63 of file mwd.cpp.
Referenced by _dumpnme(), _printili(), db(), dili(), dilt(), dsym(), dumpddiff(), dumpdiff(), printblock(), printblockline(), printblocks(), putili(), putnme(), putsc(), putstype(), putsym(), putsym1(), and symdmp().
g_dout
bool g_dout = true static
Definition at line 31 of file mwd.cpp.
Referenced by _printili(), appendbigint(), appendint1(), appendit(), appendstring1(), putdouble(), and putint().
linelen
int linelen = 0 static
Definition at line 40 of file mwd.cpp.
Referenced by appendit(), dsym(), dumpnme(), dumpnnme(), printili(), printilt(), printnme(), putbit(), putit(), putline(), and puttight().
longlines
int longlines = 1 static
Definition at line 43 of file mwd.cpp.
Referenced by dumplong(), dumpshort(), putbit(), and putit().
nexttight
int nexttight = 0 static
Definition at line 43 of file mwd.cpp.
Referenced by appendit(), putit(), and putstring1t().
nmetypes
const char* nmetypes[] static
Initial value:
= {"unknown ", "indirect", "variable",
                           "member  ", "element ", "safe    "}
Definition at line 4780 of file mwd.cpp.
Referenced by _dumpnme().
prefix
char prefix[1500] static
Definition at line 2853 of file mwd.cpp.
Referenced by dilitre(), and dilitreex().
tight
int tight = 0 static
Definition at line 43 of file mwd.cpp.
Referenced by putit().