flang: nmeutil.c File Reference
nmeutil.c File Reference
names table utility module
#include "nmeutil.h"
#include "error.h"
#include "expand.h"
#include "dtypeutl.h"
#include "ili.h"
#include "soc.h"
#include "symfun.h"
Macros
#define asrt(c)
#define NMEHSZ 1217
#define MAXNME 67108864
#define SPTR_ONE ((SPTR) 1)
Functions
bool is_presym (int nme)
Query whether the given nme is a PRE temp.
void nme_init (void)
Initialize names module.
void nme_end (void)
...
static int find_parent_member (int nmex, DTYPE dt, int sym)
int add_arrnme (NT_KIND type, SPTR insym, int nm, ISZ_T cnst, int sub, bool inlarr)
Main add NME routine.
int lookupnme (NT_KIND type, int insym, int nm, ISZ_T cnst)
...
int add_nme_with_pte (int nm, int ptex)
Add a new nme based on this nme with a new PTE list; otherwise all fields the same.
int add_rpct_nme (int orig_nme, int rpct_loop)
...
SPTR addnme (NT_KIND type, SPTR insym, int nm, ISZ_T cnst)
Add NME routine with no subscripts.
int build_sym_nme (SPTR sym, int offset, bool ptr_mem_op)
Build an nme entry using a sym and an offset relative to base address of this symbol.
DTYPE dt_nme (int nm)
Get data type of a names entry.
void loc_of (int nme)
Location of a names entry.
void loc_of_vol (int nme)
Location of a name entry when a reference is volatile.
bool basenme_is_static (int nme)
...
SPTR basesym_of (int nme)
Return the base st index of the names entry.
int basenme_of (int nme)
Return the base nme of a reference given its names entry; return 0 if unknown.
int zbasenme_of (int nme)
Return the base nme of a reference given its names entry, return 0 if unknown.
int addpte (int type, SPTR sptr, int val, int next)
Add pointer target entry.
void add_rpct (int rpct_nme1, int rpct_nme2)
Add a "runtime pointer conflict test" record.
int conflict (int nm1, int nm2)
Determine if the two names table entries, nm1 and nm2, conflict.
bool is_smove_member (int nme)
...
int hlconflict (int nm1, int nm2)
Determine if the two names table entries, nm1 and nm2, conflict.
int usersym_of (int nme)
Return the base symbol of a reference given its names entry; return 0 if unknown or compiler-created.
static void prsym (int sym, FILE *ff)
int __print_nme (FILE *ff, int nme)
...
int print_nme (int nme)
Print the symbol reference associated with a names entry.
static void DumpnameHelper (FILE *f, int opn)
void __dumpname (FILE *f, int opn)
...
void dumpname (int opn)
Pretty print a nme.
Variables
static int nmehsh [NMEHSZ]
static int ptehsh [NMEHSZ]
static int rpcthsh [NMEHSZ]
static int hlcf = 0
Detailed Description
names table utility module
Definition in file nmeutil.c.
Macro Definition Documentation
asrt
#define asrt (c)
Definition at line 40 of file nmeutil.c.
MAXNME
#define MAXNME 67108864
Definition at line 44 of file nmeutil.c.
NMEHSZ
#define NMEHSZ 1217
Definition at line 43 of file nmeutil.c.
SPTR_ONE
#define SPTR_ONE ((SPTR) 1)
Definition at line 45 of file nmeutil.c.
Function Documentation
__dumpname()
void __dumpname (FILE * f, int opn)
...
Definition at line 1632 of file nmeutil.c.
References DumpnameHelper(), f, and opn.
__print_nme()
int __print_nme (FILE * ff, int nme)
...
Prints the symbol reference represented by a names entry and returns the base symbol of a reference given its names entry – this is for scalar and structure references only
Definition at line 1402 of file nmeutil.c.
References ERR_Severe, getprint(), i, interr(), NME_NM, NME_SYM, NME_TYPE, NT_MEM, NT_VAR, NULL, print_nme(), and prsym().
Referenced by __dump_loop(), and print_nme().
add_arrnme()
int add_arrnme (NT_KIND type, SPTR insym, int nm, ISZ_T cnst, int sub, bool inlarr)
Main add NME routine.
Enter nme into the NME area.
  the type NT_INDARR is used to distinguish the cases:
    typedef float* fp;
    typedef float f10[10];
    fp* ppf;    // pointer to pointer to float
    fp a10pf[10]; // array of 10 pointers to float
    f10* pa10f; // pointer to array of 10 floats
   ppf[i][j]    // appears as IM_ELEMENT -> IM_PLD -> IM_ELEMENT ->
  IM_PLD -> ppf
   a10pf[i][j]    // appears as IM_ELEMENT -> IM_PLD -> IM_ELEMENT ->
  a10pf
   pa10f[i][j]    // appears as IM_ELEMENT -> IM_ELEMENT -> IM_PLD ->
  pa10f
  NT_INDARR is used when an IM_ELEMENT -> IM_PLD appears in the ILM file.
Definition at line 151 of file nmeutil.c.
References CNULL, DEBUG_ASSERT, dt, dt_nme(), DTY, DTyAlgTyMember, ERR_Fatal, error(), EXPDBG, find_parent_member(), gbl, i, ili_subscript(), inlarr(), ISZ_PF, loc_of(), MAXNME, NME_CNST, NME_HSHLNK, NME_INLARR, NME_NM, NME_NULL, NME_PTE, NME_RPCT_LOOP, NME_SUB, NME_SYM, NME_TYPE, NME_UNK, NME_VOL, nmeb, nmehsh, NMEHSZ, NOSYM, NT_ADD, NT_ARR, NT_IND, NT_INDARR, NT_MEM, NT_SAFE, NT_UNK, NT_VAR, SPTR_MAX, SPTR_NULL, STG_NEXT, sub, SYMNAME, type, and val.
Referenced by _cr_nme(), addnme(), build_same_base_nme(), build_sym_nme(), compute_nme(), create_array_ref(), exp_load(), exp_store(), find_parent_member(), finish_array(), makeCopyprivArray(), optimize(), sfloat(), and visit_nme_subscript().
add_nme_with_pte()
int add_nme_with_pte (int nm, int ptex)
Add a new nme based on this nme with a new PTE list; otherwise all fields the same.
...
Definition at line 379 of file nmeutil.c.
References BCOPY, CNULL, ERR_Fatal, error(), EXPDBG, gbl, i, MAXNME, NME_BASE, NME_CNST, NME_HSHLNK, NME_INLARR, NME_NM, NME_PTE, NME_RPCT_LOOP, NME_SUB, NME_SYM, NME_TYPE, nmeb, nmehsh, NMEHSZ, STG_NEXT, and val.
add_rpct()
void add_rpct (int rpct_nme1, int rpct_nme2)
Add a "runtime pointer conflict test" record.
...
This creates and returns a new RPCT (runtime pointer conflict test) record containing the pair of NMEs (rpct_nme1, rpct_nme2). These NMEs are 'RPCT NMEs' that were created by 'add_rpct_nme()'. The existence of this RPCT record indicates that a pointer conflict test has been generated which proves at runtime that this pair of references do not conflict, so 'conflict(rpct_nme1, rpct_nme2)' will return NOCONFLICT.
Definition at line 789 of file nmeutil.c.
References asrt, NME_RPCT_LOOP, nmeb, NMEHSZ, RPCT_HSHLNK, RPCT_NME1, RPCT_NME2, rpcthsh, STG_NEXT, and tmp.
add_rpct_nme()
int add_rpct_nme (int orig_nme, int rpct_loop)
...
This creates and returns a new NME, 'rpct_nme', whose fields are the same as those of 'orig_nme' except that it has NME_RPCT_LOOP(rpct_nme) == rpct_loop (> 0), whereas NME_RPCT_LOOP(orig_nme) == 0. 'rpct_nme' will replace all occurrences of 'orig_nme' within the loop denoted by 'rpct_loop', whereas 'orig_nme' will continue to be used elsewhere. This loop is guarded by runtime pointer conflict tests ('RPCT's) which prove at runtime that the 'rpct_nme' references don't conflict with various other references in the loop that they could potentially conflict with, as indicated in the 'RPCT table', and 'conflict()' will use this information to return NOCONFLICT for pairs of such references.
Definition at line 426 of file nmeutil.c.
References asrt, BCOPY, CNULL, ERR_Fatal, error(), EXPDBG, gbl, MAXNME, NME_CNST, NME_HSHLNK, NME_INLARR, NME_NM, NME_PTE, NME_RPCT_LOOP, NME_SUB, NME_SYM, NME_TYPE, nmeb, nmehsh, NMEHSZ, and STG_NEXT.
addnme()
SPTR addnme (NT_KIND type, SPTR insym, int nm, ISZ_T cnst)
Add NME routine with no subscripts.
enter nme into the NME area; use add_arrnme but add a subscript field of 0 and an inlarr field of false.
Definition at line 488 of file nmeutil.c.
References add_arrnme(), and type.
Referenced by _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_mp_atomic_write(), add_ptr_subscript(), addCopyinInplace(), allochartmp(), allocThreadprivate(), build_same_base_nme(), build_sym_nme(), charaddr(), charlen(), check_ilm(), cloneUplevel(), cmplx_to_mem(), compute_nme(), compute_sdsc_subscr(), const_prop(), cp_byval_mem_arg(), create_ref(), create_sdsc_subscr(), exp_add_copy(), exp_bran(), exp_call(), exp_end(), exp_header(), exp_load(), exp_misc(), exp_mp_atomic_capture(), exp_mp_atomic_update(), exp_qjsr(), exp_restore_mxcsr(), exp_smp(), exp_store(), exp_type_bound_proc_call(), exp_zqjsr(), fixup_nme(), gen_bindC_retval(), gen_funcret(), genIntLoad(), genIntStore(), genload(), genSizeAcon(), genswitch(), get_chain_pointer_closure(), get_complex_update_operand(), get_sdsc_element(), is_blockaddr_store(), is_safe_copy(), ld_sptr(), ll_get_gtid_val_ili(), ll_load_outlined_args(), ll_make_kmpc_task(), ll_make_kmpc_task_arg(), ll_make_outlined_task_call(), llGetThreadprivateAddr(), llLoadGtid(), llvmAddConcurEntryBlk(), load_uplevel_addresses(), loadCharLen(), loadUplevelArgsForRegion(), makeCopyprivArray(), makeCopyprivArray_tls(), mk_charlen_address(), pp_params(), propagate_bound(), ref_threadprivate(), ref_threadprivate_var(), sectionCreateBlock(), setTaskloopVars(), store_aret(), storechartmp(), toUplevelAddr(), update_local_nme(), and visit_nme_subscript().
addpte()
int addpte (int type, SPTR sptr, int val, int next)
Add pointer target entry.
...
Definition at line 757 of file nmeutil.c.
References next, nmeb, NMEHSZ, p, PTE_HSHLNK, PTE_NEXT, PTE_SPTR, PTE_TYPE, PTE_VAL, ptehsh, sptr, STG_NEXT, type, and val.
basenme_is_static()
bool basenme_is_static (int nme)
...
Walk through the given nme and its chains of base nmes, query whether all of them are static, i.e., a struct, array, var other than an object dereferenced by a pointer.
Definition at line 662 of file nmeutil.c.
References NME_NM, NME_TYPE, NT_ARR, NT_IND, NT_MEM, and NT_SAFE.
basenme_of()
int basenme_of (int nme)
Return the base nme of a reference given its names entry; return 0 if unknown.
...
Definition at line 709 of file nmeutil.c.
References NME_NM, NME_TYPE, NT_ARR, NT_IND, NT_MEM, and NT_SAFE.
Referenced by is_ptrdef_in_path(), locset_to_tbaa_info(), and nme_of_ast().
basesym_of()
SPTR basesym_of (int nme)
Return the base st index of the names entry.
...
Returns the base symbol of a reference given its names entry – returns 0 if unknown.
Definition at line 685 of file nmeutil.c.
References NME_NM, NME_SYM, NME_TYPE, NT_ARR, NT_IND, NT_MEM, NT_SAFE, NT_VAR, and SPTR_NULL.
Referenced by _find_lhs_on_rhs_conflict(), _find_rhs_def_conflict(), can_copy_def(), can_prop_def(), dd_compute(), def_ok(), dump_global(), dump_vinduc(), exp_ac(), gen_address_operand(), gen_llvm_expr(), get_dtype_for_vect_type_nme(), get_lhs_first_defs(), is_blockaddr_store(), is_ptr_safe(), only_one_ud(), set_assn(), single_ud(), storedums(), use_before_def(), and usersym_of().
build_sym_nme()
int build_sym_nme (SPTR sym, int offset, bool ptr_mem_op)
Build an nme entry using a sym and an offset relative to base address of this symbol.
...
Definition at line 496 of file nmeutil.c.
References add_arrnme(), addnme(), dt, DTY, DTySeqTyElement, i, ili_isdeleted(), inlarr(), NME_CNST, NME_INLARR, NME_NM, NME_SUB, NME_SYM, NME_TYPE, nmeb, NT_IND, NT_VAR, SPTR_NULL, and sub.
conflict()
int conflict (int nm1, int nm2)
Determine if the two names table entries, nm1 and nm2, conflict.
...
Return SAME, CONFLICT, NOCONFLICT or UNKCONFLICT
Definition at line 952 of file nmeutil.c.
References assert, aux, c, CONFLICT, conflict(), AUX::curr_entry, FLG::depchk, ENTRY::display, DTY, ERR_Informational, ERR_Severe, F90_nme_conflict(), flg, gbl, hlcf, is_overlap_cmblk_var(), m2, n1, n2, NME_CNST, NME_NM, NME_NULL, NME_SYM, NME_TYPE, NME_VOL, NOCONFLICT, NOSYM, NT_ARR, NT_IND, NT_MEM, NT_UNK, NT_VAR, SAME, SOC_NEXT, SOC_SPTR, t1, t2, UNKCONFLICT, and XBIT.
Referenced by conflict(), enhanced_conflict(), expand(), and hlconflict().
dt_nme()
DTYPE dt_nme (int nm)
Get data type of a names entry.
...
Definition at line 540 of file nmeutil.c.
References DT_DBLE, DT_DCMPLX, dt_nme(), DT_REAL, DTY, DTySeqTyElement, i, NME_CNST, NME_NM, NME_SYM, NME_TYPE, NT_ADD, NT_ARR, NT_IND, NT_INDARR, NT_MEM, NT_SAFE, NT_UNK, and NT_VAR.
Referenced by add_arrnme(), dt_nme(), exp_load(), exp_mp_atomic_capture(), exp_mp_atomic_read(), exp_mp_atomic_update(), exp_mp_atomic_write(), exp_store(), and make_stmt().
dumpname()
void dumpname (int opn)
Pretty print a nme.
Definition at line 1638 of file nmeutil.c.
References DumpnameHelper(), gbl, and opn.
Referenced by dump_global(), dump_one_memref(), and prntstl().
DumpnameHelper()
static void DumpnameHelper (FILE * f, int opn) static
Definition at line 1552 of file nmeutil.c.
References DumpnameHelper(), ERR_Severe, f, FILE, getprint(), interr(), ISZ_PF, level(), NME_CNST, NME_NM, NME_SYM, NME_TYPE, nmeb, NT_ADD, NT_ARR, NT_IND, NT_INDARR, NT_MEM, NT_SAFE, NT_UNK, NT_VAR, NULL, opn, and prsym().
Referenced by __dumpname(), dumpname(), and DumpnameHelper().
find_parent_member()
static int find_parent_member (int nmex, DTYPE dt, int sym) static
Definition at line 130 of file nmeutil.c.
References add_arrnme(), dt, DTyAlgTyMember, find_parent_member(), mem(), NOSYM, NT_MEM, and sptr.
Referenced by add_arrnme(), and find_parent_member().
hlconflict()
int hlconflict (int nm1, int nm2)
Determine if the two names table entries, nm1 and nm2, conflict.
...
Return SAME, CONFLICT, NOCONFLICT or UNKCONFLICT
Definition at line 1357 of file nmeutil.c.
References conflict(), and hlcf.
is_presym()
bool is_presym (int nme)
Query whether the given nme is a PRE temp.
...
Definition at line 53 of file nmeutil.c.
References NME_SYM, NME_TYPE, NT_VAR, sptr, and SYMNAME.
Referenced by loc_of().
is_smove_member()
bool is_smove_member (int nme)
...
Definition at line 1337 of file nmeutil.c.
References NME_SYM, NME_TYPE, NT_MEM, and SYMNAME.
loc_of()
void loc_of (int nme)
Location of a names entry.
...
LOC (explicit or implicit) has been performed. The names entry for the lvalue is scanned to determine if a symbol's ADDRTKN flag must be set
Definition at line 593 of file nmeutil.c.
References is_presym(), NME_NM, NME_SYM, NME_TYPE, NT_ARR, NT_MEM, NT_VAR, and type.
Referenced by _exp_mp_atomic_read(), _exp_mp_atomic_update(), _exp_mp_atomic_write(), add_arrnme(), bld_lhs(), bld_use(), cmplx_to_mem(), exp_ac(), exp_call(), exp_mp_atomic_capture(), exp_mp_atomic_update(), exp_store(), exp_szero(), and expand_smove().
loc_of_vol()
void loc_of_vol (int nme)
Location of a name entry when a reference is volatile.
...
LOC (explicit or implicit) has been performed. The names entry for the lvalue is scanned to determine if a symbol's ADDRTKN flag must be set. This function is called when the reference is volatile; consequently, pointer loads must be traversed.
Definition at line 618 of file nmeutil.c.
References NME_NM, NME_SYM, NME_TYPE, NT_ARR, NT_IND, NT_MEM, NT_VAR, and type.
lookupnme()
int lookupnme (NT_KIND type, int insym, int nm, ISZ_T cnst)
...
Definition at line 355 of file nmeutil.c.
References i, inlarr(), NME_CNST, NME_HSHLNK, NME_INLARR, NME_NM, NME_NULL, NME_PTE, NME_RPCT_LOOP, NME_SUB, NME_SYM, NME_TYPE, nmehsh, NMEHSZ, sub, type, and val.
nme_end()
void nme_end (void)
...
Definition at line 103 of file nmeutil.c.
References nmeb, and STG_DELETE.
Referenced by optshrd_end().
nme_init()
void nme_init (void)
Initialize names module.
...
Definition at line 69 of file nmeutil.c.
References i, NME_SYM, NME_TYPE, NME_UNK, NME_VOL, nmeb, nmehsh, NMEHSZ, NT_UNK, PT_UNK, PTE_END, PTE_NEXT, PTE_TYPE, PTE_UNK, PTE_VAL, ptehsh, rpcthsh, SPTR_ONE, STG_ALLOC, and STG_CLEAR_ALL.
Referenced by ds_init(), and optshrd_init().
print_nme()
int print_nme (int nme)
Print the symbol reference associated with a names entry.
prints the symbol reference represented by a names entry and returns the base symbol of a reference given its names entry – this is for scalar and structure references only
Definition at line 1435 of file nmeutil.c.
References __print_nme(), FILE, and gbl.
Referenced by __print_nme(), dmp_rat(), dump_cand(), and lv_print().
prsym()
static void prsym (int sym, FILE * ff) static
Definition at line 1385 of file nmeutil.c.
References getprint(), and p.
Referenced by __print_nme(), and DumpnameHelper().
usersym_of()
int usersym_of (int nme)
Return the base symbol of a reference given its names entry; return 0 if unknown or compiler-created.
...
Definition at line 1374 of file nmeutil.c.
References basesym_of().
zbasenme_of()
int zbasenme_of (int nme)
Return the base nme of a reference given its names entry, return 0 if unknown.
...
WARNING - zbasenme_of() cannot traverse NT_IND
SOMEDAY, replace with basenme_of() when flow's def/use can distinguish between a 'base' which is static (a struct, array, var) or an object located by a pointer.
Definition at line 737 of file nmeutil.c.
References NME_NM, NME_TYPE, NT_ARR, NT_MEM, and NT_SAFE.
Variable Documentation
hlcf
int hlcf = 0 static
Definition at line 884 of file nmeutil.c.
Referenced by conflict(), and hlconflict().
nmehsh
int nmehsh[NMEHSZ] static
Definition at line 47 of file nmeutil.c.
Referenced by add_arrnme(), add_nme_with_pte(), add_rpct_nme(), lookupnme(), and nme_init().
ptehsh
int ptehsh[NMEHSZ] static
Definition at line 48 of file nmeutil.c.
Referenced by addpte(), and nme_init().
rpcthsh
int rpcthsh[NMEHSZ] static
Definition at line 49 of file nmeutil.c.
Referenced by add_rpct(), and nme_init().