flang: nml.h File Reference
nml.h File Reference
Extern decls, definitions and structs common to nmlread.c and nmlwrite.c.
Classes
struct NML_GROUP
struct NML_DESC
struct TRIPLE
struct SB
struct TRI
Macros
#define GBL_SIZE 5
#define MAX_DIM 30
#define ACTUAL_NDIMS(adims) adims = (descp->ndims >= MAX_DIM) ? (descp->ndims - MAX_DIM) : (descp->ndims)
Functions
__BIGINT_T I8() siz_of (NML_DESC *descp)
Return the size of a name list item.
int nelems_of (NML_DESC *descp)
Return the number of elements in a name list item.
F90_Desc * get_descriptor (NML_DESC *descp)
If a descriptor exists for a data item return a pointer to it. Otherwise return NULL.
Detailed Description
Extern decls, definitions and structs common to nmlread.c and nmlwrite.c.
Definition in file nml.h.
Macro Definition Documentation
ACTUAL_NDIMS
#define ACTUAL_NDIMS (adims) adims = (descp->ndims >= MAX_DIM) ? (descp->ndims - MAX_DIM) : (descp->ndims)
Definition at line 16 of file nml.h.
GBL_SIZE
#define GBL_SIZE 5
Definition at line 13 of file nml.h.
MAX_DIM
#define MAX_DIM 30
Definition at line 14 of file nml.h.
Function Documentation
get_descriptor()
F90_Desc * get_descriptor (NML_DESC * descp)
If a descriptor exists for a data item return a pointer to it. Otherwise return NULL.
Definition at line 84 of file nmlutil.c.
References MAX_DIM, NML_DESC::ndims, and NULL.
Referenced by eval_dtio_sb(), eval_sb(), fillup_sb(), parse_substring(), and siz_of().
nelems_of()
int nelems_of (NML_DESC * descp)
Return the number of elements in a name list item.
Definition at line 50 of file nmlutil.c.
References ACTUAL_NDIMS, k, MAX_DIM, and NML_DESC::ndims.
Referenced by assign(), dtio_assign(), dtio_read_scalar(), dtio_write_scalar(), write_nml_val(), and xfer().
siz_of()
__BIGINT_T I8() siz_of (NML_DESC * descp)
Return the size of a name list item.
Definition at line 19 of file nmlutil.c.
References __DERIVED, __NCHAR, __STR, F90_LEN_G, FIO_TYPE_SIZE, get_descriptor(), NULL, and sz.
Referenced by assign(), dtio_assign(), eval(), and fillup_sb().