flang: nmlutil.c File Reference
nmlutil.c File Reference
Utility routines for namelist IO.
#include "global.h"
#include "nml.h"
Functions
__BIGINT_T I8() siz_of (NML_DESC *descp)
Return the size of a name list item.
int nelems_of (NML_DESC *descp)
Return the number of elements in a name list item.
F90_Desc * get_descriptor (NML_DESC *descp)
If a descriptor exists for a data item return a pointer to it. Otherwise return NULL.
Detailed Description
Utility routines for namelist IO.
Definition in file nmlutil.c.
Function Documentation
get_descriptor()
F90_Desc * get_descriptor (NML_DESC * descp)
If a descriptor exists for a data item return a pointer to it. Otherwise return NULL.
Definition at line 84 of file nmlutil.c.
References MAX_DIM, NML_DESC::ndims, and NULL.
Referenced by eval_dtio_sb(), eval_sb(), fillup_sb(), parse_substring(), and siz_of().
nelems_of()
int nelems_of (NML_DESC * descp)
Return the number of elements in a name list item.
Definition at line 50 of file nmlutil.c.
References ACTUAL_NDIMS, k, MAX_DIM, and NML_DESC::ndims.
Referenced by assign(), dtio_assign(), dtio_read_scalar(), dtio_write_scalar(), write_nml_val(), and xfer().
siz_of()
__BIGINT_T I8() siz_of (NML_DESC * descp)
Return the size of a name list item.
Definition at line 19 of file nmlutil.c.
References __DERIVED, __NCHAR, __STR, F90_LEN_G, FIO_TYPE_SIZE, get_descriptor(), NULL, and sz.
Referenced by assign(), dtio_assign(), eval(), and fillup_sb().