flang: nmlwrite.c File Reference
nmlwrite.c File Reference
Support for namelist write statements.
#include <ctype.h>
#include <string.h>
#include "global.h"
#include "format.h"
#include "nml.h"
Classes
struct G
Macros
#define DBGBIT(v) (LOCAL_DEBUG && (dbgflag & v))
Functions
static int emit_eol (void)
static int write_nml_val (NML_DESC **, NML_DESC *, char *)
static int write_item (const char *, int)
static int write_char (int)
static int eval (int, char *, NML_DESC *, NML_DESC **)
static int eval_dtio (int, char *, NML_DESC *, NML_DESC **)
static int I8() eval_sb (NML_DESC **NextDescp, NML_DESC *descp, char *loc_addr, int d)
Recursively compute the index space given a set of subscripts for n dimensions. The evaluation begins by iterating over the last dimension, recursively evaluating the subscripts of the next (to the left) for each iteration. For a given dimension d's index, subscripts to the left are recursively computed. When the first dimension is reached, the address of the element represented by the current subscript values is passed to the 'eval' function.
static int I8() eval_dtio_sb (NML_DESC **NextDescp, NML_DESC *descp, char *loc_addr, int d)
Recursively compute the index space given a set of subscripts for n dimensions. The evaluation begins by iterating over the last dimension, recursively evaluating the subscripts of the next (to the left) for each iteration. For a given dimension d's index, subscripts to the left are recursively computed. When the first dimension is reached, the address of the element represented by the current subscript values is passed to the 'eval' function.
static int dtio_write_scalar (NML_DESC **, NML_DESC *, char *, int)
static int _f90io_nmlw_init (__INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat)
int ENTF90IO (NMLW_INIT, nmlw_init)
Initialize for namelist write to an external file.
int ENTF90IO (NMLW_INIT03A, nmlw_init03a)
int ENTF90IO (NMLW_INIT03, nmlw_init03)
int ENTCRF90IO (NMLW_INIT, nmlw_init)
static int _f90io_nmlw_intern_init (char *cunit, __INT_T *rec_num, __INT_T *bitv, __INT_T *iostat, __CLEN_T cunit_len)
int ENTF90IO (NMLW_INTERN_INITA, nmlw_intern_inita)
Internal file namelist write initialization.
int ENTF90IO (NMLW_INTERN_INIT, nmlw_intern_init)
int ENTCRF90IO (NMLW_INTERN_INITA, nmlw_intern_inita)
int ENTCRF90IO (NMLW_INTERN_INIT, nmlw_intern_init)
static void I8() fillup_sb (int v, NML_DESC *descp, char *loc_addr)
static int _f90io_nml_write (NML_GROUP *nmldesc)
int ENTF90IO (NML_WRITE, nml_write)
int ENTCRF90IO (NML_WRITE, nml_write)
int ENTF90IO (NMLW, nmlw)
Write a namelist group.
int ENTCRF90IO (NMLW, nmlw)
static int _f90io_nmlw_end ()
int ENTF90IO (NMLW_END, nmlw_end)()
Terminates a WRITE statement.
int ENTCRF90IO (NMLW_END, nmlw_end)()
Variables
static int dbgflag
static FIO_FCB * f
static char * in_recp
static char * in_curp
static int byte_cnt
static int rec_len
static int n_irecs
static bool internal_file
static char * internal_unit
static char delim
static bool need_comma
static int skip
static G static_gbl [GBL_SIZE]
static G * gbl = &static_gbl[0]
static SB sb
Detailed Description
Support for namelist write statements.
Definition in file nmlwrite.c.
Macro Definition Documentation
DBGBIT
#define DBGBIT (v) (LOCAL_DEBUG && (dbgflag & v))
Definition at line 23 of file nmlwrite.c.
Function Documentation
_f90io_nml_write()
static int _f90io_nml_write (NML_GROUP * nmldesc) static
Definition at line 710 of file nmlwrite.c.
References __fortio_error(), G::decimal, dtio_write_scalar(), emit_eol(), ERR_FLAG, FIO_TBL::error, eval(), eval_dtio(), f, FALSE, fillup_sb(), FIO_COMMA, fioFcbTbls, gbl, i, I8, NML_DESC::len, MAX_DIM, n, NML_GROUP::ndesc, NML_DESC::ndims, need_comma, fcb::nextrec, NML_GROUP::nlen, NML_DESC::nlen, skip, write_char(), write_item(), and write_nml_val().
Referenced by ENTCRF90IO(), and ENTF90IO().
_f90io_nmlw_end()
static int _f90io_nmlw_end () static
Definition at line 866 of file nmlwrite.c.
References G::decimal, ERR_FLAG, FIO_TBL::error, fioFcbTbls, gbl, G::iostat, G::round, G::same_fcb_idx, G::sign, and G::unit.
Referenced by ENTCRF90IO(), and ENTF90IO().
_f90io_nmlw_init()
static int _f90io_nmlw_init (__INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat) static
Definition at line 83 of file nmlwrite.c.
References __fortio_errinit03(), __fortio_rwinit(), bitv, fcb::decimal, G::decimal, fcb::delim, delim, ERR_FLAG, f, FIO_APOSTROPHE, FIO_FORMATTED, FIO_QUOTE, gbl, G::iostat, NULL, fcb::round, G::round, fcb::sign, G::sign, fcb::skip, and G::unit.
Referenced by ENTCRF90IO(), and ENTF90IO().
_f90io_nmlw_intern_init()
static int _f90io_nmlw_intern_init (char * cunit, __INT_T * rec_num, __INT_T * bitv, __INT_T * iostat, __CLEN_T cunit_len) static
Definition at line 209 of file nmlwrite.c.
References __fortio_errinit03(), bitv, byte_cnt, delim, f, in_curp, in_recp, n_irecs, and rec_len.
Referenced by ENTCRF90IO(), and ENTF90IO().
dtio_write_scalar()
static int dtio_write_scalar (NML_DESC ** NextDescp, NML_DESC * descp, char * loc_addr, int dtvsize) static
Definition at line 915 of file nmlwrite.c.
References __CLEN_T, __DERIVED, __fortio_error(), ACTUAL_NDIMS, G::decimal, emit_eol(), ERR_FLAG, f, FIO_COMMA, gbl, internal_unit, iomsg, G::iostat, j, k, NML_DESC::len, MAX_DIM, NML_DESC::ndims, need_comma, nelems_of(), fcb::nextrec, skip, TRUE, NML_DESC::type, G::unit, void(), and write_char().
Referenced by _f90io_nml_write(), and eval_dtio_sb().
emit_eol()
static int emit_eol (void) static
Definition at line 307 of file nmlwrite.c.
References __io_binary_mode(), byte_cnt, f, FIO_ETOOFAR, fcb::fp, in_curp, in_recp, internal_file, n_irecs, rec_len, and write_char().
Referenced by _f90io_nml_write(), dtio_write_scalar(), and write_nml_val().
ENTCRF90IO() [1/6]
int ENTCRF90IO (NML_WRITE , nml_write)
Definition at line 827 of file nmlwrite.c.
References _f90io_nml_write(), _f90io_nmlw_init(), bitv, FALSE, internal_file, and s.
ENTCRF90IO() [2/6]
int ENTCRF90IO (NMLW , nmlw)
Definition at line 856 of file nmlwrite.c.
References _f90io_nml_write(), and s.
ENTCRF90IO() [3/6]
int ENTCRF90IO (NMLW_END , nmlw_end)
Definition at line 905 of file nmlwrite.c.
References __fortio_errend03(), _f90io_nmlw_end(), and s.
ENTCRF90IO() [4/6]
int ENTCRF90IO (NMLW_INIT , nmlw_init)
Definition at line 197 of file nmlwrite.c.
References _f90io_nmlw_init(), and bitv.
Referenced by ENTCRF90IO().
ENTCRF90IO() [5/6]
int ENTCRF90IO (NMLW_INTERN_INIT , nmlw_intern_init)
Definition at line 292 of file nmlwrite.c.
References __CLEN_T, bitv, CADR, CLEN, and ENTCRF90IO().
ENTCRF90IO() [6/6]
int ENTCRF90IO (NMLW_INTERN_INITA , nmlw_intern_inita)
Definition at line 275 of file nmlwrite.c.
References _f90io_nmlw_intern_init(), bitv, CADR, CLEN, internal_file, internal_unit, and TRUE.
ENTF90IO() [1/8]
int ENTF90IO (NML_WRITE , nml_write)
Definition at line 809 of file nmlwrite.c.
References __fort_status_init(), _f90io_nml_write(), _f90io_nmlw_init(), bitv, DIST_STATUS_BCST, FALSE, GET_DIST_IOPROC, GET_DIST_LCPU, internal_file, LOCAL_MODE, and s.
ENTF90IO() [2/8]
int ENTF90IO (NMLW , nmlw)
Write a namelist group.
Parameters
nmldesc - namelist group descriptor
Definition at line 845 of file nmlwrite.c.
References _f90io_nml_write(), DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, and s.
ENTF90IO() [3/8]
int ENTF90IO (NMLW_END , nmlw_end)
Terminates a WRITE statement.
Definition at line 885 of file nmlwrite.c.
References __CHAR, __CINT, __fortio_errend03(), _f90io_nmlw_end(), DIST_RBCSTL, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, in_recp, internal_file, internal_unit, len, LOCAL_MODE, and s.
ENTF90IO() [4/8]
int ENTF90IO (NMLW_INIT , nmlw_init)
Initialize for namelist write to an external file.
Parameters
unit - unit number
rec - record number for direct access I/O; rec not used, but JUST IN CASE
bitv - same as for ENTF90IO(open_)
iostat - same as for ENTF90IO(open_)
Definition at line 121 of file nmlwrite.c.
References __fort_status_init(), _f90io_nmlw_init(), bitv, DIST_STATUS_BCST, FALSE, GET_DIST_IOPROC, GET_DIST_LCPU, internal_file, LOCAL_MODE, and s.
Referenced by ENTF90IO().
ENTF90IO() [5/8]
int ENTF90IO (NMLW_INIT03 , nmlw_init03)
Definition at line 183 of file nmlwrite.c.
References __CLEN_T, CADR, CLEN, delim, ENTF90IO(), and sign.
ENTF90IO() [6/8]
int ENTF90IO (NMLW_INIT03A , nmlw_init03a)
Definition at line 136 of file nmlwrite.c.
References __fortio_eq_str(), __fortio_error(), CADR, CLEN, G::decimal, delim, DIST_STATUS_BCST, FIO_COMMA, FIO_ESPEC, FIO_PLUS, FIO_POINT, FIO_PROCESSOR_DEFINED, FIO_SUPPRESS, gbl, GET_DIST_IOPROC, GET_DIST_LCPU, ISPRESENTC, LOCAL_MODE, s, sign, and G::sign.
ENTF90IO() [7/8]
int ENTF90IO (NMLW_INTERN_INIT , nmlw_intern_init)
Definition at line 260 of file nmlwrite.c.
References __CLEN_T, bitv, CADR, CLEN, and ENTF90IO().
ENTF90IO() [8/8]
int ENTF90IO (NMLW_INTERN_INITA , nmlw_intern_inita)
Internal file namelist write initialization.
Parameters
rec_num - number of records in internal file; 0 if the file is an assumed size character array
bitv - same as for ENTF90IO(open_)
iostat - same as for ENTF90IO(open_)
Definition at line 239 of file nmlwrite.c.
References __fort_status_init(), _f90io_nmlw_intern_init(), bitv, CADR, CLEN, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, internal_file, internal_unit, LOCAL_MODE, s, and TRUE.
eval()
static int eval (int v, char * loc_addr, NML_DESC * descp, NML_DESC ** nextdescp) static
Definition at line 694 of file nmlwrite.c.
References eval_sb(), I8, SB::ndims, and sb.
Referenced by _f90io_nml_write().
eval_dtio()
static int eval_dtio (int v, char * loc_addr, NML_DESC * descp, NML_DESC ** nextdescp) static
Definition at line 702 of file nmlwrite.c.
References eval_dtio_sb(), I8, SB::ndims, and sb.
Referenced by _f90io_nml_write().
eval_dtio_sb()
static int I8() eval_dtio_sb (NML_DESC ** NextDescp, NML_DESC * descp, char * loc_addr, int d) static
Recursively compute the index space given a set of subscripts for n dimensions. The evaluation begins by iterating over the last dimension, recursively evaluating the subscripts of the next (to the left) for each iteration. For a given dimension d's index, subscripts to the left are recursively computed. When the first dimension is reached, the address of the element represented by the current subscript values is passed to the 'eval' function.
Definition at line 624 of file nmlwrite.c.
References __fort_local_address(), ACTUAL_NDIMS, d, dtio_write_scalar(), ERR_FLAG, eval_dtio_sb(), get_descriptor(), I8, SB::idx, k, NML_DESC::len, SB::loc_addr, TRIPLE::lwb, MAX_DIM, NULL, sb, SB::sect, TRIPLE::stride, and TRIPLE::upb.
Referenced by eval_dtio(), and eval_dtio_sb().
eval_sb()
static int I8() eval_sb (NML_DESC ** NextDescp, NML_DESC * descp, char * loc_addr, int d) static
Recursively compute the index space given a set of subscripts for n dimensions. The evaluation begins by iterating over the last dimension, recursively evaluating the subscripts of the next (to the left) for each iteration. For a given dimension d's index, subscripts to the left are recursively computed. When the first dimension is reached, the address of the element represented by the current subscript values is passed to the 'eval' function.
Definition at line 551 of file nmlwrite.c.
References __fort_local_address(), ACTUAL_NDIMS, d, eval_sb(), get_descriptor(), I8, SB::idx, k, SB::loc_addr, TRIPLE::lwb, NULL, sb, SB::sect, TRIPLE::stride, TRIPLE::upb, and write_nml_val().
Referenced by eval(), and eval_sb().
fillup_sb()
static void I8() fillup_sb (int v, NML_DESC * descp, char * loc_addr) static
Definition at line 338 of file nmlwrite.c.
References DECL_DIM_PTRS, SB::elemsz, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, get_descriptor(), i, I8, SB::idx, SB::loc_addr, TRIPLE::lwb, SB::lwb, SB::mult, SB::ndims, sb, SB::sect, SET_DIM_PTRS, siz_of(), TRIPLE::stride, TRIPLE::upb, and SB::v.
Referenced by _f90io_nml_write().
write_char()
static int write_char (int ch) static
Definition at line 534 of file nmlwrite.c.
References write_item().
Referenced by _f90io_nml_write(), dtio_write_scalar(), emit_eol(), and write_nml_val().
write_item()
static int write_item (const char * p, int len) static
for internal i/o in_recp/in_curp is a pointer to user's space
Definition at line 491 of file nmlwrite.c.
References __io_errno(), __io_printf, byte_cnt, DBGBIT, f, FIO_ETOOBIG, FIO_ETOOFAR, fcb::fp, FWRITE, in_curp, in_recp, internal_file, len, n_irecs, p, rec_len, and void().
Referenced by _f90io_nml_write(), write_char(), and write_nml_val().
write_nml_val()
static int write_nml_val (NML_DESC ** NextDescp, NML_DESC * descp, char * loc_addr) static
Definition at line 360 of file nmlwrite.c.
References __DERIVED, __fortio_default_convert(), __fortio_error(), __STR, ACTUAL_NDIMS, c, G::decimal, delim, emit_eol(), f, FALSE, FIO_COMMA, FIO_PLUS, FIO_TYPE_SIZE, gbl, j, k, len, NML_DESC::len, NML_DESC::ndims, need_comma, nelems_of(), fcb::nextrec, NML_DESC::nlen, p, G::round, G::sign, skip, TRUE, NML_DESC::type, write_char(), write_item(), and write_nml_val().
Referenced by _f90io_nml_write(), eval_sb(), and write_nml_val().
Variable Documentation
byte_cnt
int byte_cnt static
Definition at line 30 of file nmlwrite.c.
Referenced by _f90io_nmlw_intern_init(), emit_eol(), and write_item().
dbgflag
int dbgflag static
Definition at line 21 of file nmlwrite.c.
delim
char delim static
Definition at line 35 of file nmlwrite.c.
Referenced by _f90io_nmlw_init(), _f90io_nmlw_intern_init(), ENTF90IO(), and write_nml_val().
f
FIO_FCB* f static
Definition at line 25 of file nmlwrite.c.
Referenced by _f90io_nml_write(), _f90io_nmlw_init(), _f90io_nmlw_intern_init(), dtio_write_scalar(), emit_eol(), write_item(), and write_nml_val().
gbl
G* gbl = &static_gbl[0] static
Definition at line 66 of file nmlwrite.c.
Referenced by _f90io_nml_write(), _f90io_nmlw_end(), _f90io_nmlw_init(), dtio_write_scalar(), ENTF90IO(), and write_nml_val().
in_curp
char* in_curp static
Definition at line 28 of file nmlwrite.c.
Referenced by _f90io_nmlw_intern_init(), emit_eol(), and write_item().
in_recp
char* in_recp static
Definition at line 27 of file nmlwrite.c.
Referenced by _f90io_nmlw_intern_init(), emit_eol(), ENTF90IO(), and write_item().
internal_file
bool internal_file static
Definition at line 33 of file nmlwrite.c.
Referenced by emit_eol(), ENTCRF90IO(), ENTF90IO(), and write_item().
internal_unit
char* internal_unit static
Definition at line 34 of file nmlwrite.c.
Referenced by dtio_write_scalar(), ENTCRF90IO(), and ENTF90IO().
n_irecs
int n_irecs static
Definition at line 32 of file nmlwrite.c.
Referenced by _f90io_nmlw_intern_init(), emit_eol(), and write_item().
need_comma
bool need_comma static
Definition at line 36 of file nmlwrite.c.
Referenced by _f90io_nml_write(), dtio_write_scalar(), print_function_signature(), and write_nml_val().
rec_len
int rec_len static
Definition at line 31 of file nmlwrite.c.
Referenced by _f90io_nmlw_intern_init(), emit_eol(), and write_item().
sb
SB sb static
Definition at line 78 of file nmlwrite.c.
Referenced by eval(), eval_dtio(), eval_dtio_sb(), eval_sb(), and fillup_sb().
skip
int skip static
Definition at line 37 of file nmlwrite.c.
Referenced by __abort_trace(), _exp_smove(), _f90io_nml_write(), check_skip(), dd_edge(), dirv_permute(), do_subscript(), dtio_write_scalar(), ENTFTN(), exp_call(), literal_string(), and write_nml_val().
static_gbl
G static_gbl[GBL_SIZE] static
Definition at line 65 of file nmlwrite.c.