flang: olap.c File Reference
olap.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "fort_vars.h"
Classes
struct olap_sked
Functions
static void I8() olap_start (void *op, char *rb, char *sb, F90_Desc *rs, F90_Desc *ss)
static void olap_free (void *op)
static void I8() olap_send (char *src, F90_Desc *as, olap_sked *o, int len)
static void I8() olap_recv (char *dst, F90_Desc *as, olap_sked *o, int len)
static void I8() olap_copy (char *adr0, F90_Desc *as, olap_sked *o, int len)
static void I8() olap_loop (char *adr0, F90_Desc *as, olap_sked *o, int len, int dim)
static sked *I8() olap_shift (char *ab, F90_Desc *as, olap_sked *o)
sked * ENTFTN (OLAP_SHIFT, olap_shift)
sked * ENTFTN (OLAP_CSHIFT, olap_cshift)
sked * ENTFTN (OLAP_EOSHIFT, olap_eoshift)
sked * ENTFTN (COMM_SHIFT, comm_shift)
Variables
void(* __fort_scalar_copy [__NTYPES])(void *rp, void *sp, int size)
Function Documentation
ENTFTN() [1/4]
sked * ENTFTN (COMM_SHIFT , comm_shift)
Definition at line 859 of file olap.c.
References __DESC, __fort_abort(), __fort_malloc(), F90_RANK_G, F90_TAG_G, i, I8, ISPRESENT, olap_sked::nsh, NULL, olap_shift(), olap_sked::psh, olap_sked::style, and va.
ENTFTN() [2/4]
sked * ENTFTN (OLAP_CSHIFT , olap_cshift)
Definition at line 803 of file olap.c.
References __DESC, __fort_abort(), __fort_malloc(), F90_RANK_G, F90_TAG_G, i, I8, ISPRESENT, olap_sked::nsh, NULL, olap_shift(), olap_sked::psh, olap_sked::style, and va.
ENTFTN() [3/4]
sked * ENTFTN (OLAP_EOSHIFT , olap_eoshift)
Definition at line 829 of file olap.c.
References __DESC, __fort_abort(), __fort_malloc(), __fort_scalar_copy, olap_sked::boundary, boundary, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_ZED, i, I8, ISPRESENT, olap_sked::nsh, NULL, olap_shift(), olap_sked::psh, olap_sked::style, and va.
ENTFTN() [4/4]
sked * ENTFTN (OLAP_SHIFT , olap_shift)
Definition at line 777 of file olap.c.
References __DESC, __fort_abort(), __fort_malloc(), F90_RANK_G, F90_TAG_G, i, I8, ISPRESENT, olap_sked::nsh, NULL, olap_shift(), olap_sked::psh, olap_sked::style, and va.
olap_copy()
static void I8() olap_copy (char * adr0, F90_Desc * as, olap_sked * o, int len) static
Definition at line 465 of file olap.c.
References __fort_abort(), __fort_recvl(), __fort_sendl(), __fort_show_scalar(), __fort_test, base, DEBUG_OLAP, DECL_DIM_PTRS, DIST_DPTR_LAB_G, DIST_DPTR_NO_G, DIST_DPTR_OLB_G, DIST_DPTR_OUB_G, DIST_DPTR_PO_G, DIST_DPTR_UAB_G, F90_DPTR_LSTRIDE_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, GET_DIST_LCPU, i, len, m, Min, n, and SET_DIM_PTRS.
Referenced by olap_loop().
olap_free()
static void olap_free (void * op) static
Definition at line 76 of file olap.c.
References __fort_frechn(), __fort_free(), olap_sked::ch1, olap_sked::ch2, olap_sked::ch3, i, and olap_sked::rank.
Referenced by olap_shift().
olap_loop()
static void I8() olap_loop (char * adr0, F90_Desc * as, olap_sked * o, int len, int dim) static
Definition at line 533 of file olap.c.
References __fort_block_bounds(), cl, DECL_DIM_PTRS, dim, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, DIST_DPTR_LAB_G, DIST_DPTR_NO_G, DIST_DPTR_PO_G, DIST_DPTR_UAB_G, F90_DPTR_LSTRIDE_G, F90_LEN_G, I8, len, olap_copy(), olap_loop(), olap_recv(), olap_send(), and SET_DIM_PTRS.
Referenced by olap_loop(), and olap_shift().
olap_recv()
static void I8() olap_recv (char * dst, F90_Desc * as, olap_sked * o, int len) static
Definition at line 273 of file olap.c.
References __fort_abort(), __fort_block_bounds(), __fort_free(), __fort_new_gen_block(), __fort_recvl(), __fort_sendl(), __fort_show_scalar(), __fort_test, base, cl, cnt, DEBUG_OLAP, DECL_DIM_PTRS, DIST_DPTR_BLOCK_G, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, DIST_DPTR_GEN_BLOCK_G, DIST_DPTR_LAB_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_TLB_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, DIST_DPTR_TUB_G, DPTR_UBOUND_G, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, GET_DIST_LCPU, i, I8, len, n, pc, SET_DIM_PTRS, and str.
Referenced by olap_loop().
olap_send()
static void I8() olap_send (char * src, F90_Desc * as, olap_sked * o, int len) static
Definition at line 91 of file olap.c.
References __fort_abort(), __fort_block_bounds(), __fort_free(), __fort_new_gen_block(), __fort_sendl(), __fort_show_scalar(), __fort_test, base, cl, cnt, DEBUG_OLAP, DECL_DIM_PTRS, DIST_DPTR_BLOCK_G, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, DIST_DPTR_GEN_BLOCK_G, DIST_DPTR_LAB_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_TLB_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, DIST_DPTR_TUB_G, DPTR_UBOUND_G, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, GET_DIST_LCPU, i, I8, len, n, pc, SET_DIM_PTRS, src, and str.
Referenced by olap_loop().
olap_shift()
static sked *I8() olap_shift (char * ab, F90_Desc * as, olap_sked * o) static
Definition at line 603 of file olap.c.
References __fort_abort(), __fort_chn_1to1(), __fort_chn_prune(), __fort_cycle_bounds(), __fort_free(), __fort_new_gen_block(), __fort_setbase(), __fort_test, __OFF_TEMPLATE, __SKED, Abs, DEBUG_OLAP, DECL_DIM_PTRS, DIST_DPTR_BLOCK_G, DIST_DPTR_COFSTR_G, DIST_DPTR_CYCLE_G, DIST_DPTR_GEN_BLOCK_G, DIST_DPTR_NO_G, DIST_DPTR_PAXIS_G, DIST_DPTR_PCOORD_G, DIST_DPTR_PO_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_PSTRIDE_G, DIST_DPTR_TLB_G, DIST_DPTR_TSTRIDE_G, DIST_DPTR_TUB_G, F90_DPTR_EXTENT_G, F90_FLAGS_G, F90_KIND_G, F90_LEN_G, F90_LSIZE_G, F90_RANK_G, GET_DIST_LCPU, GET_DIST_TRANSNAM, i, I8, NULL, olap_free(), olap_loop(), olap_start(), and SET_DIM_PTRS.
Referenced by ENTFTN().
olap_start()
static void I8() olap_start (void * op, char * rb, char * sb, F90_Desc * rs, F90_Desc * ss) static
Definition at line 46 of file olap.c.
References __fort_abort(), __fort_adjbase(), __fort_doit(), olap_sked::boundary, olap_sked::ch1, olap_sked::ch2, olap_sked::ch3, F90_KIND_G, F90_LEN_G, i, NULL, olap_sked::rank, rb, sb, and ss.
Referenced by olap_shift().
Variable Documentation
__fort_scalar_copy
void(* __fort_scalar_copy[__NTYPES])(void *rp, void *sp, int size) (void * rp, void * sp, int size) extern
Referenced by ENTFTN().