flang: ompaccel.h File Reference
ompaccel.h File Reference
ompaccel.c - OpenMP GPU Offload for NVVM Targets. It uses libomptarget
#include "llmputil.h"
#include "expand.h"
Classes
struct OMPACCEL_RED_SYM
struct OMPACCEL_RED_FUNCS
struct OMPACCEL_SYM
struct _OMPACCEL_TARGET
Macros
#define IS_OMP_DEVICE_KERNEL(func_sptr) (OMPACCFUNCKERNELG(func_sptr))
#define IS_OMP_DEVICE_FUNC(func_sptr) (OMPACCFUNCDEVG(func_sptr))
#define IS_OMP_DEVICE_CG
#define OMPACCEL_DATA_FUNCTION NOSYM
#define OMPACCEL_DATA_MAX_SYM 50
#define NVVM_WARPSIZE 32
#define ompaccelInternalFail(message)
#define ompaccelInternalFailures(format, ...)
#define OMPACCELMESSAGE "OpenMP Accelerator Model:"
Typedefs
typedef struct _OMPACCEL_TARGET OMPACCEL_TINFO
typedef enum NVVM_SREG_ENUM nvvm_sregs
typedef enum NVVM_INTRINSICS_ENUM nvvm_intrinsics
typedef enum NVVM_BARRIERS nvvm_barriers
Enumerations
enum NVVM_SREG_ENUM {
threadIdX , threadIdY , threadIdZ , blockIdX ,
blockIdY , blockIdZ , blockDimX , blockDimY ,
blockDimZ , gridDimX , gridDimY , gridDimZ ,
warpSize
}
enum NVVM_INTRINSICS_ENUM { barrier0 , barrier }
enum NVVM_BARRIERS { CTA_BARRIER , PARTIAL_BARRIER }
Functions
void ompaccel_set_targetriple (const char *)
Set LLVM's target-triple which is passed with -fopenmp-target=<target-triple>
const char * ompaccel_get_targetriple (void)
Return fopenmp-targets triple.
bool ompaccel_is_tgt_registered (void)
return whether tgt runtime is registered or not
void ompaccel_register_tgt (void)
Set tgt runtime as registered.
void ompaccel_emit_tgt_register (void)
Emit a ctor function which register tgt runtime.
void ompaccel_initsyms (void)
Create NVVM special symbols and intrinsics.
int ompaccel_nvvm_get (nvvm_sregs sreg)
Get special register. (nvvm device only)
int ompaccel_nvvm_get_gbl_tid (void)
Get global thread id. It does not take into account master-warp. (nvvm device only)
SPTR ompaccel_nvvm_emit_shuffle_reduce (OMPACCEL_RED_SYM *, int, SPTR)
Emit shuffle reduce for reduction. (nvvm device only)
SPTR ompaccel_nvvm_emit_reduce (OMPACCEL_RED_SYM *, int)
Emit reduce for reduction. (nvvm device only)
SPTR ompaccel_nvvm_emit_inter_warp_copy (OMPACCEL_RED_SYM *, int)
Emit inter warp copy for reduction. (nvvm device only)
void ompaccel_init (void)
Initialize ompaccel, which keeps target region and data information structures.
OMPACCEL_TINFO * ompaccel_tinfo_create (SPTR, int)
Create target info with data. Target info is designed to keep all the symbols which occur in the OpenMP construct's region along with their map-types. It also keeps the hierarchy.
OMPACCEL_TINFO * ompaccel_tinfo_get (int)
Get target and data info of function.
bool ompaccel_tinfo_has (int)
Return whether parameter function sptr has target info or not.
OMPACCEL_TINFO * ompaccel_tinfo_current_get (void)
Return current target info.
OMPACCEL_TINFO * ompaccel_tinfo_current_get_targetdata (void)
Return current target data info.
OMP_TARGET_MODE ompaccel_tinfo_current_target_mode (void)
Return current target region mode.
void ompaccel_tinfo_current_set_mode (OMP_TARGET_MODE)
Set the target region mode if it is combined construct.
void ompaccel_tinfo_set_mode_next_target (OMP_TARGET_MODE)
Set the target region mode if it is combined construct.
void ompaccel_tinfo_current_add_sym (SPTR, SPTR, int)
Add a host symbol to the current target info.
void ompaccel_tinfo_current_addupdate_mapitem (SPTR, int)
Update map-type of the host symbol of the current target info.
void ompaccel_tinfo_current_add_reductionitem (SPTR, SPTR, int)
Add reduction symbols to the current target info.
bool ompaccel_tinfo_current_is_registered (SPTR)
Return whether is the the symbol is current tinfo or not.
SPTR ompaccel_tinfo_current_get_devsptr (SPTR)
Return device symbol of passed host symbol of current target info. It is designed to replace host symbols of outlined function code with device symbols.
DTYPE ompaccel_tinfo_current_get_dev_dtype (DTYPE)
Return device symbol's datatype of the passed host symbol's datatype of current target info.
SPTR ompaccel_tinfo_parent_get_devsptr (SPTR)
Return device symbol of parent target info of the passed host symbol. It is used when there nested outlining in the device code.
SPTR ompaccel_create_device_symbol (SPTR sptr, int count)
Create device symbol from the host symbol. Parameter count can be anything.
void dumpomptarget (OMPACCEL_TINFO *)
Dump single target region.
void dumpomptargets (void)
Dump all target regions.
void ompaccel_msg_interr (const char *, const char *)
void ompaccel_msg_err (const char *, const char *)
void ompaccel_msg_warn (const char *, const char *)
void ompaccel_msg_info (const char *, const char *)
void exp_ompaccel_mploop (ILM *ilmp, int)
Expand ILM and emit code for mploop.
void exp_ompaccel_mploopfini (ILM *ilmp, int, int)
Expand ILM and emit code for mploopfini.
void exp_ompaccel_bpar (ILM *ilmp, int, SPTR, SPTR, int(incrOutlinedCnt()))
Expand ILM and emit code for bpar.
void exp_ompaccel_epar (ILM *, int, int, int(decrOutlinedCnt()))
Expand ILM and emit code for epar.
void exp_ompaccel_bteams (ILM *ilmp, int, int, SPTR, SPTR, int(incrOutlinedCnt()))
Expand ILM and emit code for bteams.
void exp_ompaccel_eteams (ILM *ilmp, int, int, int(decrOutlinedCnt()))
Expand ILM and emit code for eteams.
void exp_ompaccel_btarget (ILM *, int, SPTR, SPTR, int(incrOutlinedCnt()), SPTR *, int *)
Expand ILM and emit code for btarget.
void exp_ompaccel_etarget (ILM *, int, SPTR, int, SPTR, int(decrOutlinedCnt()))
Expand ILM and emit code for etarget.
void exp_ompaccel_reduction (ILM *, int)
Expand ILM and emit code for reduction.
void exp_ompaccel_map (ILM *, int, int)
Expand ILM and emit code for map.
void exp_ompaccel_emap (ILM *, int)
Expand ILM and emit code for emap.
void exp_ompaccel_looptripcount (ILM *, int)
Expand ILM and emit code for looptripcount.
void exp_ompaccel_reductionitem (ILM *, int)
Expand ILM and emit code for reductionitem.
void exp_ompaccel_targetdata (ILM *, int, ILM_OP)
Expand ILM and emit code for targetdata.
void exp_ompaccel_etargetdata (ILM *, int)
Expand ILM and emit code for etargetdata.
int mk_ompaccel_store (int ili_value, DTYPE dtype, int nme, int ili_address)
int mk_ompaccel_mul (int ili1, DTYPE dtype1, int ili2, DTYPE dtype2)
int mk_ompaccel_add (int ili1, DTYPE dtype1, int ili2, DTYPE dtype2)
int mk_ompaccel_ldsptr (SPTR sptr)
void init_test ()
Variables
static bool isOmpaccelRegistered = false
OMPACCEL_TINFO ** tinfos
static const char * NVVM_SREG []
static const char * NVVM_INTRINSICS []
static SPTR init_nvvm_syms = NOSYM
static SPTR init_nvvm_intrinsics = NOSYM
Detailed Description
ompaccel.c - OpenMP GPU Offload for NVVM Targets. It uses libomptarget
Definition in file ompaccel.h.
Macro Definition Documentation
IS_OMP_DEVICE_CG
#define IS_OMP_DEVICE_CG
Value:
  (flg.omptarget && gbl.ompaccel_isdevice && \
   (IS_OMP_DEVICE_FUNC(GBL_CURRFUNC) | IS_OMP_DEVICE_KERNEL(GBL_CURRFUNC)))
Definition at line 25 of file ompaccel.h.
IS_OMP_DEVICE_FUNC
#define IS_OMP_DEVICE_FUNC (func_sptr) (OMPACCFUNCDEVG(func_sptr))
Definition at line 23 of file ompaccel.h.
IS_OMP_DEVICE_KERNEL
#define IS_OMP_DEVICE_KERNEL (func_sptr) (OMPACCFUNCKERNELG(func_sptr))
Definition at line 21 of file ompaccel.h.
NVVM_WARPSIZE
#define NVVM_WARPSIZE 32
Definition at line 81 of file ompaccel.h.
OMPACCEL_DATA_FUNCTION
#define OMPACCEL_DATA_FUNCTION NOSYM
Definition at line 29 of file ompaccel.h.
OMPACCEL_DATA_MAX_SYM
#define OMPACCEL_DATA_MAX_SYM 50
Definition at line 30 of file ompaccel.h.
ompaccelInternalFail
#define ompaccelInternalFail (message)
Definition at line 166 of file ompaccel.h.
ompaccelInternalFailures
#define ompaccelInternalFailures (format, ...)
Definition at line 167 of file ompaccel.h.
OMPACCELMESSAGE
#define OMPACCELMESSAGE "OpenMP Accelerator Model:"
Definition at line 308 of file ompaccel.h.
Typedef Documentation
nvvm_barriers
typedef enum NVVM_BARRIERS nvvm_barriers
nvvm_intrinsics
typedef enum NVVM_INTRINSICS_ENUM nvvm_intrinsics
nvvm_sregs
typedef enum NVVM_SREG_ENUM nvvm_sregs
OMPACCEL_TINFO
typedef struct _OMPACCEL_TARGET OMPACCEL_TINFO
Definition at line 59 of file ompaccel.h.
Enumeration Type Documentation
NVVM_BARRIERS
enum NVVM_BARRIERS
Enumerator
CTA_BARRIER
PARTIAL_BARRIER
Definition at line 113 of file ompaccel.h.
NVVM_INTRINSICS_ENUM
enum NVVM_INTRINSICS_ENUM
Enumerator
barrier0
barrier
Definition at line 108 of file ompaccel.h.
NVVM_SREG_ENUM
enum NVVM_SREG_ENUM
Enumerator
threadIdX
threadIdY
threadIdZ
blockIdX
blockIdY
blockIdZ
blockDimX
blockDimY
blockDimZ
gridDimX
gridDimY
gridDimZ
warpSize
Definition at line 83 of file ompaccel.h.
Function Documentation
dumpomptarget()
void dumpomptarget (OMPACCEL_TINFO *)
Dump single target region.
dumpomptargets()
void dumpomptargets (void)
Dump all target regions.
Referenced by process_input().
exp_ompaccel_bpar()
void exp_ompaccel_bpar (ILM * ilmp, int , SPTR , SPTR , int(incrOutlinedCnt()))
Expand ILM and emit code for bpar.
Referenced by exp_smp().
exp_ompaccel_btarget()
void exp_ompaccel_btarget (ILM * , int , SPTR , SPTR , int(incrOutlinedCnt()) , SPTR * , int *)
Expand ILM and emit code for btarget.
Referenced by exp_smp().
exp_ompaccel_bteams()
void exp_ompaccel_bteams (ILM * ilmp, int , int , SPTR , SPTR , int(incrOutlinedCnt()))
Expand ILM and emit code for bteams.
Referenced by exp_smp().
exp_ompaccel_emap()
void exp_ompaccel_emap (ILM * , int)
Expand ILM and emit code for emap.
Referenced by exp_smp().
exp_ompaccel_epar()
void exp_ompaccel_epar (ILM * , int , int , int(decrOutlinedCnt()))
Expand ILM and emit code for epar.
Referenced by exp_smp().
exp_ompaccel_etarget()
void exp_ompaccel_etarget (ILM * , int , SPTR , int , SPTR , int(decrOutlinedCnt()))
Expand ILM and emit code for etarget.
Referenced by exp_smp().
exp_ompaccel_etargetdata()
void exp_ompaccel_etargetdata (ILM * , int)
Expand ILM and emit code for etargetdata.
exp_ompaccel_eteams()
void exp_ompaccel_eteams (ILM * ilmp, int , int , int(decrOutlinedCnt()))
Expand ILM and emit code for eteams.
Referenced by exp_smp().
exp_ompaccel_looptripcount()
void exp_ompaccel_looptripcount (ILM * , int)
Expand ILM and emit code for looptripcount.
Referenced by exp_smp().
exp_ompaccel_map()
void exp_ompaccel_map (ILM * , int , int)
Expand ILM and emit code for map.
Referenced by exp_smp().
exp_ompaccel_mploop()
void exp_ompaccel_mploop (ILM * ilmp, int)
Expand ILM and emit code for mploop.
Referenced by exp_smp().
exp_ompaccel_mploopfini()
void exp_ompaccel_mploopfini (ILM * ilmp, int , int)
Expand ILM and emit code for mploopfini.
Referenced by exp_smp().
exp_ompaccel_reduction()
void exp_ompaccel_reduction (ILM * , int)
Expand ILM and emit code for reduction.
Referenced by eval_ilm().
exp_ompaccel_reductionitem()
void exp_ompaccel_reductionitem (ILM * , int)
Expand ILM and emit code for reductionitem.
Referenced by exp_smp().
exp_ompaccel_targetdata()
void exp_ompaccel_targetdata (ILM * , int , ILM_OP)
Expand ILM and emit code for targetdata.
Referenced by exp_smp().
init_test()
void init_test ()
Referenced by main(), and process_input().
mk_ompaccel_add()
int mk_ompaccel_add (int ili1, DTYPE dtype1, int ili2, DTYPE dtype2)
mk_ompaccel_ldsptr()
int mk_ompaccel_ldsptr (SPTR sptr)
mk_ompaccel_mul()
int mk_ompaccel_mul (int ili1, DTYPE dtype1, int ili2, DTYPE dtype2)
mk_ompaccel_store()
int mk_ompaccel_store (int ili_value, DTYPE dtype, int nme, int ili_address)
ompaccel_create_device_symbol()
SPTR ompaccel_create_device_symbol (SPTR sptr, int count)
Create device symbol from the host symbol. Parameter count can be anything.
ompaccel_emit_tgt_register()
void ompaccel_emit_tgt_register (void)
Emit a ctor function which register tgt runtime.
ompaccel_get_targetriple()
const char * ompaccel_get_targetriple (void)
Return fopenmp-targets triple.
Referenced by cg_llvm_init().
ompaccel_init()
void ompaccel_init (void)
Initialize ompaccel, which keeps target region and data information structures.
Referenced by main().
ompaccel_initsyms()
void ompaccel_initsyms (void)
Create NVVM special symbols and intrinsics.
Referenced by process_input().
ompaccel_is_tgt_registered()
bool ompaccel_is_tgt_registered (void)
return whether tgt runtime is registered or not
Referenced by eval_ilm().
ompaccel_msg_err()
void ompaccel_msg_err (const char * , const char *)
ompaccel_msg_info()
void ompaccel_msg_info (const char * , const char *)
ompaccel_msg_interr()
void ompaccel_msg_interr (const char * , const char *)
ompaccel_msg_warn()
void ompaccel_msg_warn (const char * , const char *)
ompaccel_nvvm_emit_inter_warp_copy()
SPTR ompaccel_nvvm_emit_inter_warp_copy (OMPACCEL_RED_SYM * , int)
Emit inter warp copy for reduction. (nvvm device only)
ompaccel_nvvm_emit_reduce()
SPTR ompaccel_nvvm_emit_reduce (OMPACCEL_RED_SYM * , int)
Emit reduce for reduction. (nvvm device only)
ompaccel_nvvm_emit_shuffle_reduce()
SPTR ompaccel_nvvm_emit_shuffle_reduce (OMPACCEL_RED_SYM * , int , SPTR)
Emit shuffle reduce for reduction. (nvvm device only)
ompaccel_nvvm_get()
int ompaccel_nvvm_get (nvvm_sregs sreg)
Get special register. (nvvm device only)
Referenced by eval_ilm().
ompaccel_nvvm_get_gbl_tid()
int ompaccel_nvvm_get_gbl_tid (void)
Get global thread id. It does not take into account master-warp. (nvvm device only)
Referenced by ll_make_kmpc_generic_ptr_2int(), and ll_make_kmpc_generic_ptr_int().
ompaccel_register_tgt()
void ompaccel_register_tgt (void)
Set tgt runtime as registered.
Referenced by eval_ilm().
ompaccel_set_targetriple()
void ompaccel_set_targetriple (const char *)
Set LLVM's target-triple which is passed with -fopenmp-target=<target-triple>
Referenced by init().
ompaccel_tinfo_create()
OMPACCEL_TINFO * ompaccel_tinfo_create (SPTR , int)
Create target info with data. Target info is designed to keep all the symbols which occur in the OpenMP construct's region along with their map-types. It also keeps the hierarchy.
ompaccel_tinfo_current_add_reductionitem()
void ompaccel_tinfo_current_add_reductionitem (SPTR , SPTR , int)
Add reduction symbols to the current target info.
ompaccel_tinfo_current_add_sym()
void ompaccel_tinfo_current_add_sym (SPTR , SPTR , int)
Add a host symbol to the current target info.
ompaccel_tinfo_current_addupdate_mapitem()
void ompaccel_tinfo_current_addupdate_mapitem (SPTR , int)
Update map-type of the host symbol of the current target info.
ompaccel_tinfo_current_get()
OMPACCEL_TINFO * ompaccel_tinfo_current_get (void)
Return current target info.
ompaccel_tinfo_current_get_dev_dtype()
DTYPE ompaccel_tinfo_current_get_dev_dtype (DTYPE)
Return device symbol's datatype of the passed host symbol's datatype of current target info.
Referenced by ll_rewrite_ilms().
ompaccel_tinfo_current_get_devsptr()
SPTR ompaccel_tinfo_current_get_devsptr (SPTR)
Return device symbol of passed host symbol of current target info. It is designed to replace host symbols of outlined function code with device symbols.
Referenced by ll_rewrite_ilms().
ompaccel_tinfo_current_get_targetdata()
OMPACCEL_TINFO * ompaccel_tinfo_current_get_targetdata (void)
Return current target data info.
Referenced by exp_smp().
ompaccel_tinfo_current_is_registered()
bool ompaccel_tinfo_current_is_registered (SPTR)
Return whether is the the symbol is current tinfo or not.
ompaccel_tinfo_current_set_mode()
void ompaccel_tinfo_current_set_mode (OMP_TARGET_MODE)
Set the target region mode if it is combined construct.
ompaccel_tinfo_current_target_mode()
OMP_TARGET_MODE ompaccel_tinfo_current_target_mode (void)
Return current target region mode.
ompaccel_tinfo_get()
OMPACCEL_TINFO * ompaccel_tinfo_get (int)
Get target and data info of function.
Referenced by build_routine_and_parameter_entries().
ompaccel_tinfo_has()
bool ompaccel_tinfo_has (int)
Return whether parameter function sptr has target info or not.
Referenced by process_input().
ompaccel_tinfo_parent_get_devsptr()
SPTR ompaccel_tinfo_parent_get_devsptr (SPTR)
Return device symbol of parent target info of the passed host symbol. It is used when there nested outlining in the device code.
ompaccel_tinfo_set_mode_next_target()
void ompaccel_tinfo_set_mode_next_target (OMP_TARGET_MODE)
Set the target region mode if it is combined construct.
Referenced by exp_smp().
Variable Documentation
init_nvvm_intrinsics
SPTR init_nvvm_intrinsics = NOSYM static
Definition at line 117 of file ompaccel.h.
init_nvvm_syms
SPTR init_nvvm_syms = NOSYM static
Definition at line 116 of file ompaccel.h.
isOmpaccelRegistered
bool isOmpaccelRegistered = false static
Definition at line 77 of file ompaccel.h.
NVVM_INTRINSICS
const char* NVVM_INTRINSICS[] static
Initial value:
= {"llvm.nvvm.barrier0",
                                        "llvm.nvvm.barrier"}
Definition at line 110 of file ompaccel.h.
NVVM_SREG
const char* NVVM_SREG[] static
Initial value:
= {
    "llvm.nvvm.read.ptx.sreg.tid.x",    "llvm.nvvm.read.ptx.sreg.tid.y",
    "llvm.nvvm.read.ptx.sreg.tid.z",    "llvm.nvvm.read.ptx.sreg.ctaid.x",
    "llvm.nvvm.read.ptx.sreg.ctaid.y",  "llvm.nvvm.read.ptx.sreg.ctaid.z",
    "llvm.nvvm.read.ptx.sreg.ntid.x",   "llvm.nvvm.read.ptx.sreg.ntid.y",
    "llvm.nvvm.read.ptx.sreg.ntid.z",   "llvm.nvvm.read.ptx.sreg.nctaid.x",
    "llvm.nvvm.read.ptx.sreg.nctaid.y", "llvm.nvvm.read.ptx.sreg.nctaid.z",
    "llvm.nvvm.read.ptx.sreg.warpsize"}
Definition at line 99 of file ompaccel.h.
tinfos
OMPACCEL_TINFO** tinfos extern