flang: ompstubs.c File Reference
ompstubs.c File Reference
#include <stdio.h>
#include "komp.h"
Functions
int omp_get_thread_limit (void)
int omp_get_thread_limit_ (void)
int omp_in_parallel (void)
int omp_in_parallel_ (void)
void omp_set_num_threads (int num_threads)
void omp_set_num_threads_ (int *num_threads)
void omp_set_lock (omp_lock_t *sem)
void omp_set_lock_ (omp_lock_t *sem)
void omp_unset_lock (omp_lock_t *sem)
void omp_unset_lock_ (omp_lock_t *sem)
int omp_get_num_procs (void)
int omp_get_num_procs_ (void)
int omp_get_num_threads (void)
int omp_get_num_threads_ (void)
int omp_get_max_threads (void)
int omp_get_max_threads_ (void)
int omp_get_thread_num (void)
int omp_get_thread_num_ (void)
void omp_set_dynamic (int dynamic_threads)
void omp_set_dynamic_ (int *dynamic_threads)
int omp_get_dynamic (void)
int omp_get_dynamic_ (void)
void omp_set_nested (int nested)
void omp_set_nested_ (int *nested)
int omp_get_nested (void)
int omp_get_nested_ (void)
void omp_set_schedule (omp_sched_t kind, int modifier)
void omp_set_schedule_ (omp_sched_t *kind, int *modifier)
void omp_get_schedule (omp_sched_t *kind, int *modifier)
void omp_get_schedule_ (omp_sched_t *kind, int *modifier)
void omp_set_max_active_levels (int max_active_levels)
void omp_set_max_active_levels_ (int *max_active_levels)
int omp_get_max_active_levels (void)
int omp_get_max_active_levels_ (void)
int omp_get_level (void)
int omp_get_level_ (void)
int omp_get_ancestor_thread_num (int level)
int omp_get_ancestor_thread_num_ (int *level)
int omp_get_team_size (int level)
int omp_get_team_size_ (int *level)
int omp_get_active_level (void)
int omp_get_active_level_ (void)
void omp_init_lock (omp_lock_t *s)
void omp_init_lock_ (omp_lock_t *s)
void omp_destroy_lock (omp_lock_t *arg)
void omp_destroy_lock_ (omp_lock_t *arg)
int omp_test_lock (omp_lock_t *arg)
int omp_test_lock_ (omp_lock_t *arg)
void omp_init_nest_lock (omp_nest_lock_t *arg)
void omp_init_nest_lock_ (omp_nest_lock_t *arg)
void omp_destroy_nest_lock (omp_nest_lock_t *arg)
void omp_destroy_nest_lock_ (omp_nest_lock_t *arg)
void omp_set_nest_lock (omp_nest_lock_t *arg)
void omp_set_nest_lock_ (omp_nest_lock_t *arg)
void omp_unset_nest_lock (omp_nest_lock_t *arg)
void omp_unset_nest_lock_ (omp_nest_lock_t *arg)
int omp_test_nest_lock (omp_nest_lock_t *arg)
int omp_test_nest_lock_ (omp_nest_lock_t *arg)
int omp_get_cancellation ()
int omp_get_cancellation_ ()
omp_proc_bind_t omp_get_proc_bind_ ()
omp_proc_bind_t omp_get_proc_bind ()
int omp_get_num_places ()
int omp_get_num_places_ ()
int omp_get_place_num_procs (int placenum)
int omp_get_place_num_procs_ (int placenum)
void omp_get_place_proc_ids (int place_num, int *ids)
void omp_get_place_proc_ids_ (int place_num, int *ids)
int omp_get_place_num ()
int omp_get_place_num_ ()
int omp_get_partition_num_places ()
int omp_get_partition_num_places_ ()
void omp_get_partition_place_nums (int *place_nums)
void omp_get_partition_place_nums_ (int *place_nums)
void omp_set_default_device (int device_num)
void omp_set_default_device_ (int device_num)
int omp_get_default_device (void)
int omp_get_default_device_ (void)
int omp_get_num_devices (void)
int omp_get_num_devices_ (void)
int omp_get_num_teams (void)
int omp_get_num_teams_ (void)
int omp_get_team_num (void)
int omp_get_team_num_ (void)
int omp_is_initial_device (void)
int omp_is_initial_device_ (void)
int omp_get_initial_device (void)
int omp_get_initial_device_ (void)
int omp_get_max_task_priority (void)
int omp_get_max_task_priority_ (void)
void omp_init_nest_lock_with_hint (omp_nest_lock_t *arg, omp_lock_hint_t hint)
void omp_init_nest_lock_with_hint_ (omp_nest_lock_t *arg, omp_lock_hint_t hint)
double omp_get_wtime (void)
double omp_get_wtime_ (void)
double omp_get_wtick (void)
double omp_get_wtick_ (void)
int omp_in_final (void)
kmp_int32 __kmpc_global_thread_num (void *id)
kmp_int32 __kmpc_global_thread_num_ (void *id)
void __kmpc_critical (ident_t *id, kmp_int32 tn, kmp_critical_name *sem)
void __kmpc_critical_ (ident_t *id, kmp_int32 *tn, kmp_critical_name *sem)
void __kmpc_end_critical (ident_t *id, kmp_int32 tn, kmp_critical_name *sem)
void __kmpc_end_critical_ (ident_t *id, kmp_int32 *tn, kmp_critical_name *sem)
void * __kmpc_threadprivate_cached (ident_t *id, kmp_int32 tn, void *data, size_t size, void ***cache)
void * __kmpc_threadprivate_cached_ (ident_t *id, kmp_int32 *tn, void *data, size_t *size, void ***cache)
void __kmpc_barrier (ident_t *id, kmp_int32 tn)
void __kmpc_barrier_ (ident_t *id, kmp_int32 *tn)
void * __kmpc_threadprivate (ident_t *id, kmp_int32 tn, void *data, size_t size)
void * __kmpc_threadprivate_ (ident_t *id, kmp_int32 tn, void *data, size_t size)
void __kmpc_fork_call (ident_t *loc, kmp_int32 argc, void *microtask,...)
void __kmpc_for_static_init_8 (ident_t *loc, kmp_int32 gtid, kmp_int32 schedtype, kmp_int32 *plastiter, kmp_int64 *plower, kmp_int64 *pupper, kmp_int64 *pstride, kmp_int64 incr, kmp_int64 chunk)
void __kmpc_push_num_threads (ident_t *loc, kmp_int32 global_tid, kmp_int32 num_threads)
Function Documentation
__kmpc_barrier()
void __kmpc_barrier (ident_t * id, kmp_int32 tn)
Definition at line 646 of file ompstubs.c.
Referenced by _mp_copyin_move(), _mp_copyin_move_al(), _mp_copyin_move_cpp(), _mp_copyin_move_multiple(), _mp_copyin_move_tls(), _mp_copypriv(), _mp_copypriv_al(), _mp_copypriv_move(), and _mp_copypriv_move_tls().
__kmpc_barrier_()
void __kmpc_barrier_ (ident_t * id, kmp_int32 * tn)
Definition at line 651 of file ompstubs.c.
__kmpc_critical()
void __kmpc_critical (ident_t * id, kmp_int32 tn, kmp_critical_name * sem)
Definition at line 612 of file ompstubs.c.
Referenced by _mp_bcs(), _mp_bcs_stdio(), and _mp_p().
__kmpc_critical_()
void __kmpc_critical_ (ident_t * id, kmp_int32 * tn, kmp_critical_name * sem)
Definition at line 617 of file ompstubs.c.
__kmpc_end_critical()
void __kmpc_end_critical (ident_t * id, kmp_int32 tn, kmp_critical_name * sem)
Definition at line 622 of file ompstubs.c.
Referenced by _mp_ecs(), _mp_ecs_stdio(), and _mp_v().
__kmpc_end_critical_()
void __kmpc_end_critical_ (ident_t * id, kmp_int32 * tn, kmp_critical_name * sem)
Definition at line 627 of file ompstubs.c.
__kmpc_for_static_init_8()
void __kmpc_for_static_init_8 (ident_t * loc, kmp_int32 gtid, kmp_int32 schedtype, kmp_int32 * plastiter, kmp_int64 * plower, kmp_int64 * pupper, kmp_int64 * pstride, kmp_int64 incr, kmp_int64 chunk)
Definition at line 673 of file ompstubs.c.
__kmpc_fork_call()
void __kmpc_fork_call (ident_t * loc, kmp_int32 argc, void * microtask, ...)
Definition at line 668 of file ompstubs.c.
__kmpc_global_thread_num()
kmp_int32 __kmpc_global_thread_num (void * id)
Definition at line 600 of file ompstubs.c.
Referenced by _mp_bcs(), _mp_bcs_stdio(), _mp_cdecl(), _mp_cdecli(), _mp_cdeclp(), _mp_copyin_move(), _mp_copyin_move_al(), _mp_copyin_move_cpp(), _mp_copyin_move_cpp_new(), _mp_copyin_move_multiple(), _mp_copyin_move_tls(), _mp_copypriv(), _mp_copypriv_al(), _mp_copypriv_move(), _mp_copypriv_move_tls(), _mp_ecs(), _mp_ecs_stdio(), _mp_p(), and _mp_v().
__kmpc_global_thread_num_()
kmp_int32 __kmpc_global_thread_num_ (void * id)
Definition at line 606 of file ompstubs.c.
__kmpc_push_num_threads()
void __kmpc_push_num_threads (ident_t * loc, kmp_int32 global_tid, kmp_int32 num_threads)
Definition at line 680 of file ompstubs.c.
__kmpc_threadprivate()
void * __kmpc_threadprivate (ident_t * id, kmp_int32 tn, void * data, size_t size)
Definition at line 656 of file ompstubs.c.
Referenced by _mp_copyin_move_tls(), _mp_copypriv_move_tls(), and _mp_get_threadprivate().
__kmpc_threadprivate_()
void * __kmpc_threadprivate_ (ident_t * id, kmp_int32 tn, void * data, size_t size)
Definition at line 662 of file ompstubs.c.
__kmpc_threadprivate_cached()
void * __kmpc_threadprivate_cached (ident_t * id, kmp_int32 tn, void * data, size_t size, void *** cache)
Definition at line 632 of file ompstubs.c.
Referenced by _mp_cdecl(), _mp_cdecli(), _mp_cdeclp(), _mp_copyin_move(), _mp_copyin_move_al(), _mp_copyin_move_cpp(), _mp_copyin_move_cpp_new(), _mp_copyin_move_multiple(), and _mp_copypriv_move().
__kmpc_threadprivate_cached_()
void * __kmpc_threadprivate_cached_ (ident_t * id, kmp_int32 * tn, void * data, size_t * size, void *** cache)
Definition at line 639 of file ompstubs.c.
omp_destroy_lock()
void omp_destroy_lock (omp_lock_t * arg)
Definition at line 280 of file ompstubs.c.
omp_destroy_lock_()
void omp_destroy_lock_ (omp_lock_t * arg)
Definition at line 285 of file ompstubs.c.
omp_destroy_nest_lock()
void omp_destroy_nest_lock (omp_nest_lock_t * arg)
Definition at line 312 of file ompstubs.c.
omp_destroy_nest_lock_()
void omp_destroy_nest_lock_ (omp_nest_lock_t * arg)
Definition at line 317 of file ompstubs.c.
omp_get_active_level()
int omp_get_active_level (void)
Definition at line 258 of file ompstubs.c.
omp_get_active_level_()
int omp_get_active_level_ (void)
Definition at line 264 of file ompstubs.c.
omp_get_ancestor_thread_num()
int omp_get_ancestor_thread_num (int level)
Definition at line 222 of file ompstubs.c.
References level().
omp_get_ancestor_thread_num_()
int omp_get_ancestor_thread_num_ (int * level)
Definition at line 231 of file ompstubs.c.
References level().
omp_get_cancellation()
int omp_get_cancellation (void)
Definition at line 354 of file ompstubs.c.
omp_get_cancellation_()
int omp_get_cancellation_ ()
Definition at line 360 of file ompstubs.c.
omp_get_default_device()
int omp_get_default_device (void)
Definition at line 457 of file ompstubs.c.
omp_get_default_device_()
int omp_get_default_device_ (void)
Definition at line 463 of file ompstubs.c.
omp_get_dynamic()
int omp_get_dynamic (void)
Definition at line 130 of file ompstubs.c.
omp_get_dynamic_()
int omp_get_dynamic_ (void)
Definition at line 136 of file ompstubs.c.
omp_get_initial_device()
int omp_get_initial_device (void)
Definition at line 517 of file ompstubs.c.
omp_get_initial_device_()
int omp_get_initial_device_ (void)
Definition at line 523 of file ompstubs.c.
omp_get_level()
int omp_get_level (void)
Definition at line 210 of file ompstubs.c.
omp_get_level_()
int omp_get_level_ (void)
Definition at line 216 of file ompstubs.c.
omp_get_max_active_levels()
int omp_get_max_active_levels (void)
Definition at line 198 of file ompstubs.c.
omp_get_max_active_levels_()
int omp_get_max_active_levels_ (void)
Definition at line 204 of file ompstubs.c.
omp_get_max_task_priority()
int omp_get_max_task_priority (void)
Definition at line 529 of file ompstubs.c.
omp_get_max_task_priority_()
int omp_get_max_task_priority_ (void)
Definition at line 535 of file ompstubs.c.
omp_get_max_threads()
int omp_get_max_threads (void)
Definition at line 98 of file ompstubs.c.
omp_get_max_threads_()
int omp_get_max_threads_ (void)
Definition at line 104 of file ompstubs.c.
omp_get_nested()
int omp_get_nested (void)
Definition at line 152 of file ompstubs.c.
omp_get_nested_()
int omp_get_nested_ (void)
Definition at line 158 of file ompstubs.c.
omp_get_num_devices()
int omp_get_num_devices (void)
Definition at line 469 of file ompstubs.c.
omp_get_num_devices_()
int omp_get_num_devices_ (void)
Definition at line 475 of file ompstubs.c.
omp_get_num_places()
int omp_get_num_places ()
Definition at line 378 of file ompstubs.c.
omp_get_num_places_()
int omp_get_num_places_ ()
Definition at line 384 of file ompstubs.c.
omp_get_num_procs()
int omp_get_num_procs (void)
Definition at line 74 of file ompstubs.c.
omp_get_num_procs_()
int omp_get_num_procs_ (void)
Definition at line 80 of file ompstubs.c.
omp_get_num_teams()
int omp_get_num_teams (void)
Definition at line 481 of file ompstubs.c.
omp_get_num_teams_()
int omp_get_num_teams_ (void)
Definition at line 487 of file ompstubs.c.
omp_get_num_threads()
int omp_get_num_threads (void)
Definition at line 86 of file ompstubs.c.
omp_get_num_threads_()
int omp_get_num_threads_ (void)
Definition at line 92 of file ompstubs.c.
omp_get_partition_num_places()
int omp_get_partition_num_places (void)
Definition at line 425 of file ompstubs.c.
omp_get_partition_num_places_()
int omp_get_partition_num_places_ ()
Definition at line 431 of file ompstubs.c.
omp_get_partition_place_nums()
void omp_get_partition_place_nums (int * place_nums)
Definition at line 437 of file ompstubs.c.
omp_get_partition_place_nums_()
void omp_get_partition_place_nums_ (int * place_nums)
Definition at line 442 of file ompstubs.c.
omp_get_place_num()
int omp_get_place_num (void)
Definition at line 413 of file ompstubs.c.
omp_get_place_num_()
int omp_get_place_num_ ()
Definition at line 419 of file ompstubs.c.
omp_get_place_num_procs()
int omp_get_place_num_procs (int placenum)
Definition at line 390 of file ompstubs.c.
omp_get_place_num_procs_()
int omp_get_place_num_procs_ (int placenum)
Definition at line 396 of file ompstubs.c.
omp_get_place_proc_ids()
void omp_get_place_proc_ids (int place_num, int * ids)
Definition at line 401 of file ompstubs.c.
omp_get_place_proc_ids_()
void omp_get_place_proc_ids_ (int place_num, int * ids)
Definition at line 407 of file ompstubs.c.
omp_get_proc_bind()
omp_proc_bind_t omp_get_proc_bind (void)
Definition at line 372 of file ompstubs.c.
omp_get_proc_bind_()
omp_proc_bind_t omp_get_proc_bind_ ()
Definition at line 366 of file ompstubs.c.
omp_get_schedule()
void omp_get_schedule (omp_sched_t * kind, int * modifier)
Definition at line 174 of file ompstubs.c.
References kind, and omp_sched_static.
omp_get_schedule_()
void omp_get_schedule_ (omp_sched_t * kind, int * modifier)
Definition at line 181 of file ompstubs.c.
References kind, and omp_sched_static.
omp_get_team_num()
int omp_get_team_num (void)
Definition at line 493 of file ompstubs.c.
omp_get_team_num_()
int omp_get_team_num_ (void)
Definition at line 499 of file ompstubs.c.
omp_get_team_size()
int omp_get_team_size (int level)
Definition at line 240 of file ompstubs.c.
References level().
omp_get_team_size_()
int omp_get_team_size_ (int * level)
Definition at line 249 of file ompstubs.c.
References level().
omp_get_thread_limit()
int omp_get_thread_limit (void)
Definition at line 20 of file ompstubs.c.
omp_get_thread_limit_()
int omp_get_thread_limit_ (void)
Definition at line 26 of file ompstubs.c.
omp_get_thread_num()
int omp_get_thread_num (void)
Definition at line 110 of file ompstubs.c.
omp_get_thread_num_()
int omp_get_thread_num_ (void)
Definition at line 115 of file ompstubs.c.
omp_get_wtick()
double omp_get_wtick (void)
Definition at line 574 of file ompstubs.c.
omp_get_wtick_()
double omp_get_wtick_ (void)
Definition at line 584 of file ompstubs.c.
omp_get_wtime()
double omp_get_wtime (void)
Definition at line 554 of file ompstubs.c.
omp_get_wtime_()
double omp_get_wtime_ (void)
Definition at line 564 of file ompstubs.c.
omp_in_final()
int omp_in_final (void)
Definition at line 594 of file ompstubs.c.
omp_in_parallel()
int omp_in_parallel (void)
Definition at line 32 of file ompstubs.c.
omp_in_parallel_()
int omp_in_parallel_ (void)
Definition at line 38 of file ompstubs.c.
omp_init_lock()
void omp_init_lock (omp_lock_t * s)
Definition at line 270 of file ompstubs.c.
omp_init_lock_()
void omp_init_lock_ (omp_lock_t * s)
Definition at line 275 of file ompstubs.c.
omp_init_nest_lock()
void omp_init_nest_lock (omp_nest_lock_t * arg)
Definition at line 302 of file ompstubs.c.
Referenced by _mp_bcs_nest(), _mp_bcs_nest_red(), omp_init_nest_lock_with_hint(), and omp_init_nest_lock_with_hint_().
omp_init_nest_lock_()
void omp_init_nest_lock_ (omp_nest_lock_t * arg)
Definition at line 307 of file ompstubs.c.
omp_init_nest_lock_with_hint()
void omp_init_nest_lock_with_hint (omp_nest_lock_t * arg, omp_lock_hint_t hint)
Definition at line 541 of file ompstubs.c.
References arg, and omp_init_nest_lock().
omp_init_nest_lock_with_hint_()
void omp_init_nest_lock_with_hint_ (omp_nest_lock_t * arg, omp_lock_hint_t hint)
Definition at line 547 of file ompstubs.c.
References arg, and omp_init_nest_lock().
omp_is_initial_device()
int omp_is_initial_device (void)
Definition at line 505 of file ompstubs.c.
omp_is_initial_device_()
int omp_is_initial_device_ (void)
Definition at line 511 of file ompstubs.c.
omp_set_default_device()
void omp_set_default_device (int device_num)
Definition at line 447 of file ompstubs.c.
omp_set_default_device_()
void omp_set_default_device_ (int device_num)
Definition at line 452 of file ompstubs.c.
omp_set_dynamic()
void omp_set_dynamic (int dynamic_threads)
Definition at line 120 of file ompstubs.c.
omp_set_dynamic_()
void omp_set_dynamic_ (int * dynamic_threads)
Definition at line 125 of file ompstubs.c.
omp_set_lock()
void omp_set_lock (omp_lock_t * sem)
Definition at line 54 of file ompstubs.c.
omp_set_lock_()
void omp_set_lock_ (omp_lock_t * sem)
Definition at line 59 of file ompstubs.c.
omp_set_max_active_levels()
void omp_set_max_active_levels (int max_active_levels)
Definition at line 188 of file ompstubs.c.
omp_set_max_active_levels_()
void omp_set_max_active_levels_ (int * max_active_levels)
Definition at line 193 of file ompstubs.c.
omp_set_nest_lock()
void omp_set_nest_lock (omp_nest_lock_t * arg)
Definition at line 322 of file ompstubs.c.
Referenced by _mp_bcs_nest(), and _mp_bcs_nest_red().
omp_set_nest_lock_()
void omp_set_nest_lock_ (omp_nest_lock_t * arg)
Definition at line 327 of file ompstubs.c.
omp_set_nested()
void omp_set_nested (int nested)
Definition at line 142 of file ompstubs.c.
omp_set_nested_()
void omp_set_nested_ (int * nested)
Definition at line 147 of file ompstubs.c.
omp_set_num_threads()
void omp_set_num_threads (int num_threads)
Definition at line 44 of file ompstubs.c.
omp_set_num_threads_()
void omp_set_num_threads_ (int * num_threads)
Definition at line 49 of file ompstubs.c.
omp_set_schedule()
void omp_set_schedule (omp_sched_t kind, int modifier)
Definition at line 164 of file ompstubs.c.
omp_set_schedule_()
void omp_set_schedule_ (omp_sched_t * kind, int * modifier)
Definition at line 169 of file ompstubs.c.
omp_test_lock()
int omp_test_lock (omp_lock_t * arg)
Definition at line 290 of file ompstubs.c.
omp_test_lock_()
int omp_test_lock_ (omp_lock_t * arg)
Definition at line 296 of file ompstubs.c.
omp_test_nest_lock()
int omp_test_nest_lock (omp_nest_lock_t * arg)
Definition at line 342 of file ompstubs.c.
omp_test_nest_lock_()
int omp_test_nest_lock_ (omp_nest_lock_t * arg)
Definition at line 348 of file ompstubs.c.
omp_unset_lock()
void omp_unset_lock (omp_lock_t * sem)
Definition at line 64 of file ompstubs.c.
omp_unset_lock_()
void omp_unset_lock_ (omp_lock_t * sem)
Definition at line 69 of file ompstubs.c.
omp_unset_nest_lock()
void omp_unset_nest_lock (omp_nest_lock_t * arg)
Definition at line 332 of file ompstubs.c.
Referenced by _mp_ecs_nest(), and _mp_ecs_nest_red().
omp_unset_nest_lock_()
void omp_unset_nest_lock_ (omp_nest_lock_t * arg)
Definition at line 337 of file ompstubs.c.