flang: open_close.h File Reference
open_close.h File Reference
Declaration of open.c and close.c functions visible to other runtime library routines.
#include "fortDt.h"
Functions
int __fortio_open (int unit, int action_flag, int status_flag, int dispose_flag, int acc_flag, int blank_flag, int form_flag, int delim_flag, int pos_flag, int pad_flag, __INT8_T reclen, char *name, __CLEN_T namelen)
Low level open routine; called from within fiolib to open a file.
int __fortio_close (struct fcb *, int)
void __fortio_cleanup (void)
Runtime library IO cleanup routine; do whatever in neccessary to clean up open files.
Detailed Description
Declaration of open.c and close.c functions visible to other runtime library routines.
Definition in file open_close.h.
Function Documentation
__fortio_cleanup()
void __fortio_cleanup (void)
Runtime library IO cleanup routine; do whatever in neccessary to clean up open files.
Runtime library IO cleanup routine; do whatever in neccessary to clean up open files.
Definition at line 180 of file close.c.
References __fort_access, __fort_barrier(), __fort_unlink, __fortio_cleanup_fcb(), __fortio_close(), __io_fflush, fcb::dispose, f, FIO_TBL::fcbs, FIO_DELETE, FIO_SCRATCH, fioFcbTbls, fcb::fp, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, fcb::name, fcb::next, NULL, fcb::status, and fcb::stdunit.
Referenced by term().
__fortio_close()
int __fortio_close (FIO_FCB * f, int flag)
brief Fortran file close
Parameters
f 0 (use default stream)
flag FIO_KEEP, FIO_DELETE
Definition at line 35 of file close.c.
References __fort_access, __fort_unlink, __fortio_error(), __fortio_free_fcb(), __io_binary_mode(), __io_errno(), __io_fclose, __io_ferror(), __io_fflush, __io_fputc(), fcb::dispose, f, FALSE, FIO_DELETE, FIO_EREADONLY, FIO_SCRATCH, fcb::fp, fcb::name, fcb::nonadvance, fcb::status, fcb::stdunit, and fcb::unit.
Referenced by __fortio_cleanup(), __fortio_open(), and _f90io_close().
__fortio_open()
int __fortio_open (int unit, int action_flag, int status_flag, int dispose_flag, int acc_flag, int blank_flag, int form_flag, int delim_flag, int pos_flag, int pad_flag, __INT8_T reclen, char * name, __CLEN_T namelen)
Low level open routine; called from within fiolib to open a file.
Low level open routine; called from within fiolib to open a file.
Definition at line 45 of file open.c.
References __CLEN_T, __fort_access, __fort_getenv(), __fort_unlink, __fortio_alloc_fcb(), __fortio_close(), __fortio_error(), __fortio_find_unit(), __fortio_free_fcb(), __fortio_ispipe, __fortio_scratch_name(), __io_errno(), __io_fopen, __io_fseek, __io_fseekx, __io_ftellx, fcb::acc, fcb::action, assert, fcb::asy_rw, fcb::asyptr, fcb::binary, fcb::blank, fcb::byte_swap, fcb::coherent, fcb::decimal, fcb::delim, fcb::dispose, fcb::encoding, envar_fortranopt, fcb::eof_flag, fcb::eor_flag, ERR_FLAG, EXIT_OPEN, f, FALSE, Fcb, FIO_TBL::fcbs, fd, FILE, filename, FIO_APPEND, FIO_COMPATIBLE, FIO_DEFAULT, FIO_DIRECT, FIO_ECOMPAT, FIO_EEXIST, FIO_ENAME, FIO_ENOEXIST, FIO_EOPENED, FIO_EUNIT, FIO_NEW, FIO_OLD, FIO_POINT, FIO_PROCESSOR_DEFINED, FIO_READ, FIO_REPLACE, FIO_REWIND, FIO_SCRATCH, FIO_SEQUENTIAL, FIO_STREAM, FIO_UNFORMATTED, FIO_UNKNOWN, fioFcbTbls, fcb::form, fcb::fp, GET_FIO_CNFG_DEFAULT_NAME, i, ILLEGAL_UNIT, fcb::ispipe, len, malloc(), MAX_NAMELEN, fcb::maxrec, fcb::name, name, fcb::named, fcb::native, fcb::next, fcb::nextrec, fcb::nonadvance, NULL, fcb::pad, fcb::pback, fcb::pos, fcb::pread, q, fcb::reclen, fcb::round, fcb::sign, fcb::skip, STASH, fcb::status, fcb::stdunit, strlen(), TRUE, fcb::truncflag, fcb::unit, and fcb::wordlen.
Referenced by __fortio_rwinit(), and f90_open().