flang: open.c File Reference
open.c File Reference
Implements the Fortran OPEN statment.
#include <stdarg.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include "global.h"
#include "open_close.h"
#include "async.h"
#include <fcntl.h>
Macros
#define EXIT_OPEN(ec)
Functions
int ENTF90IO (GET_NEWUNIT, get_newunit)()
int __fortio_open (int unit, int action_flag, int status_flag, int dispose_flag, int acc_flag, int blank_flag, int form_flag, int delim_flag, int pos_flag, int pad_flag, __INT8_T reclen, char *name, __CLEN_T namelen)
Function called from within fiolib to open a file.
static int f90_open (__INT_T *unit, __INT_T *bitv, char *acc_ptr, char *action_ptr, char *blank_ptr, char *delim_ptr, char *name_ptr, char *form_ptr, __INT_T *iostat, char *pad_ptr, char *pos_ptr, __INT8_T *reclen, char *status_ptr, char *dispose_ptr, __CLEN_T acc_siz, __CLEN_T action_siz, __CLEN_T blank_siz, __CLEN_T delim_siz, __CLEN_T name_siz, __CLEN_T form_siz, __CLEN_T pad_siz, __CLEN_T pos_siz, __CLEN_T status_siz, __CLEN_T dispose_siz)
__INT_T ENTF90IO (OPENA, opena)
Called from user program; implements Fortran OPEN statement.
__INT_T ENTF90IO (OPEN, open)
__INT_T ENTF90IO (OPEN2003A, open2003a)
__INT_T ENTF90IO (OPEN2003, open2003)
__INT_T (__INT_T *istat, DCHAR(endian) DCLEN64(endian))
Called from user program; augments the OPEN with CONVERT specifier.
__INT_T (__INT_T *istat, DCHAR(endian) DCLEN(endian))
__INT_T (__INT_T *istat, DCHAR(shv) DCLEN64(shv))
__INT_T (__INT_T *istat, DCHAR(shv) DCLEN(shv))
__INT_T ENTCRF90IO (OPENA, opena)
__INT_T ENTCRF90IO (OPEN, open)
__INT_T ENTCRF90IO (OPEN_CVTA, open_cvta)
__INT_T ENTCRF90IO (OPEN_CVT, open_cvt)
__INT_T ENTCRF90IO (OPEN_SHAREA, open_sharea)
__INT_T ENTCRF90IO (OPEN_SHARE, open_share)
int ENTF90IO (OPEN_ASYNCA, open_asynca)
int ENTF90IO (OPEN_ASYNC, open_async)
__INT_T ENTF90IO (OPEN03A, open03a)
__INT_T ENTF90IO (OPEN03, open03)
Variables
static FIO_FCB * Fcb
int next_newunit = -13
Detailed Description
Implements the Fortran OPEN statment.
Definition in file open.c.
Macro Definition Documentation
EXIT_OPEN
#define EXIT_OPEN (ec)
Value:
  {                                                                            \
    if (long_name)                                                             \
      free(filename);                                                          \
    return ec;                                                                 \
  }
Function Documentation
__fortio_open()
int __fortio_open (int unit, int action_flag, int status_flag, int dispose_flag, int acc_flag, int blank_flag, int form_flag, int delim_flag, int pos_flag, int pad_flag, __INT8_T reclen, char * name, __CLEN_T namelen)
Function called from within fiolib to open a file.
Low level open routine; called from within fiolib to open a file.
Definition at line 45 of file open.c.
References __CLEN_T, __fort_access, __fort_getenv(), __fort_unlink, __fortio_alloc_fcb(), __fortio_close(), __fortio_error(), __fortio_find_unit(), __fortio_free_fcb(), __fortio_ispipe, __fortio_scratch_name(), __io_errno(), __io_fopen, __io_fseek, __io_fseekx, __io_ftellx, fcb::acc, fcb::action, assert, fcb::asy_rw, fcb::asyptr, fcb::binary, fcb::blank, fcb::byte_swap, fcb::coherent, fcb::decimal, fcb::delim, fcb::dispose, fcb::encoding, envar_fortranopt, fcb::eof_flag, fcb::eor_flag, ERR_FLAG, EXIT_OPEN, f, FALSE, Fcb, FIO_TBL::fcbs, fd, FILE, filename, FIO_APPEND, FIO_COMPATIBLE, FIO_DEFAULT, FIO_DIRECT, FIO_ECOMPAT, FIO_EEXIST, FIO_ENAME, FIO_ENOEXIST, FIO_EOPENED, FIO_EUNIT, FIO_NEW, FIO_OLD, FIO_POINT, FIO_PROCESSOR_DEFINED, FIO_READ, FIO_REPLACE, FIO_REWIND, FIO_SCRATCH, FIO_SEQUENTIAL, FIO_STREAM, FIO_UNFORMATTED, FIO_UNKNOWN, fioFcbTbls, fcb::form, fcb::fp, GET_FIO_CNFG_DEFAULT_NAME, i, ILLEGAL_UNIT, fcb::ispipe, len, malloc(), MAX_NAMELEN, fcb::maxrec, fcb::name, name, fcb::named, fcb::native, fcb::next, fcb::nextrec, fcb::nonadvance, NULL, fcb::pad, fcb::pback, fcb::pos, fcb::pread, q, fcb::reclen, fcb::round, fcb::sign, fcb::skip, STASH, fcb::status, fcb::stdunit, strlen(), TRUE, fcb::truncflag, fcb::unit, and fcb::wordlen.
Referenced by __fortio_rwinit(), and f90_open().
__INT_T() [1/4]
__INT_T (__INT_T * istat, DCHAR(endian) DCLEN(endian))
Definition at line 829 of file open.c.
References __CLEN_T, CADR, CLEN, and ENTF90IO().
__INT_T() [2/4]
__INT_T (__INT_T * istat, DCHAR(endian) DCLEN64(endian))
Called from user program; augments the OPEN with CONVERT specifier.
Definition at line 801 of file open.c.
References __fortio_eq_str(), __fortio_errend03(), __fortio_error(), fcb::byte_swap, CADR, CLEN, DIST_STATUS_BCST, Fcb, FIO_ECOMPAT, FIO_ESPEC, FIO_UNFORMATTED, fcb::form, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, fcb::native, s, and TRUE.
__INT_T() [3/4]
__INT_T (__INT_T * istat, DCHAR(shv) DCLEN(shv))
Definition at line 857 of file open.c.
References __CLEN_T, CADR, CLEN, and ENTF90IO().
__INT_T() [4/4]
__INT_T (__INT_T * istat, DCHAR(shv) DCLEN64(shv))
Definition at line 838 of file open.c.
References __fortio_eq_str(), CADR, CLEN, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, and s.
ENTCRF90IO() [1/6]
__INT_T ENTCRF90IO (OPEN , open)
Definition at line 948 of file open.c.
References __CLEN_T, bitv, CADR, CLEN, delim, ENTCRF90IO(), name, and pos.
ENTCRF90IO() [2/6]
__INT_T ENTCRF90IO (OPEN_CVT , open_cvt)
Definition at line 1009 of file open.c.
References __CLEN_T, CADR, CLEN, and ENTCRF90IO().
ENTCRF90IO() [3/6]
__INT_T ENTCRF90IO (OPEN_CVTA , open_cvta)
Definition at line 985 of file open.c.
References __fortio_eq_str(), __fortio_error(), fcb::byte_swap, CADR, CLEN, Fcb, FIO_ECOMPAT, FIO_ESPEC, FIO_UNFORMATTED, fcb::form, fcb::native, and TRUE.
ENTCRF90IO() [4/6]
__INT_T ENTCRF90IO (OPEN_SHARE , open_share)
Definition at line 1037 of file open.c.
References __CLEN_T, CADR, CLEN, and ENTCRF90IO().
ENTCRF90IO() [5/6]
__INT_T ENTCRF90IO (OPEN_SHAREA , open_sharea)
Definition at line 1018 of file open.c.
References __fortio_eq_str(), CADR, CLEN, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, and s.
ENTCRF90IO() [6/6]
__INT_T ENTCRF90IO (OPENA , opena)
Definition at line 867 of file open.c.
References __CLEN_T, __fortio_errend03(), bitv, CADR, CLEN, delim, f90_open(), ISPRESENTC, name, NULL, pos, and s.
Referenced by ENTCRF90IO().
ENTF90IO() [1/9]
int ENTF90IO (GET_NEWUNIT , get_newunit)
Definition at line 34 of file open.c.
References next_newunit, set_gbl_newunit(), and TRUE.
Referenced by __INT_T(), and ENTF90IO().
ENTF90IO() [2/9]
__INT_T ENTF90IO (OPEN , open)
Definition at line 639 of file open.c.
References __CLEN_T, bitv, CADR, CLEN, delim, ENTF90IO(), name, and pos.
ENTF90IO() [3/9]
__INT_T ENTF90IO (OPEN03 , open03)
Definition at line 1168 of file open.c.
References __CLEN_T, CADR, CLEN, ENTF90IO(), round(), and sign.
ENTF90IO() [4/9]
__INT_T ENTF90IO (OPEN03A , open03a)
Definition at line 1089 of file open.c.
References __fortio_eq_str(), __fortio_error(), CADR, CLEN, fcb::decimal, fcb::encoding, Fcb, FIO_COMMA, FIO_COMPATIBLE, FIO_DEFAULT, FIO_DOWN, FIO_ECOMPAT, FIO_ESPEC, FIO_FORMATTED, FIO_NEAREST, FIO_PLUS, FIO_POINT, FIO_PROCESSOR_DEFINED, FIO_SUPPRESS, FIO_UP, FIO_UTF_8, FIO_ZERO, fcb::form, ISPRESENTC, fcb::round, round(), sign, and fcb::sign.
ENTF90IO() [5/9]
__INT_T ENTF90IO (OPEN2003 , open2003)
Definition at line 763 of file open.c.
References __CLEN_T, bitv, CADR, CLEN, delim, ENTF90IO(), name, and pos.
ENTF90IO() [6/9]
__INT_T ENTF90IO (OPEN2003A , open2003a)
Definition at line 678 of file open.c.
References __CLEN_T, __fort_status_init(), __fortio_errend03(), bitv, CADR, CLEN, delim, DIST_STATUS_BCST, f90_open(), GET_DIST_IOPROC, GET_DIST_LCPU, ISPRESENT, ISPRESENTC, LOCAL_MODE, name, NULL, pos, and s.
ENTF90IO() [7/9]
int ENTF90IO (OPEN_ASYNC , open_async)
Definition at line 1083 of file open.c.
References __CLEN_T, CADR, CLEN, and ENTF90IO().
ENTF90IO() [8/9]
int ENTF90IO (OPEN_ASYNCA , open_asynca)
Definition at line 1048 of file open.c.
References __fortio_eq_str(), __fortio_error(), __io_errno(), fcb::acc, fcb::asyptr, fcb::byte_swap, CADR, CLEN, Fcb, Fio_asy_open(), FIO_DIRECT, FIO_ESPEC, FIO_SEQUENTIAL, FIO_STREAM, fcb::fp, and ISPRESENTC.
ENTF90IO() [9/9]
__INT_T ENTF90IO (OPENA , opena)
Called from user program; implements Fortran OPEN statement.
Definition at line 554 of file open.c.
References __CLEN_T, __fort_status_init(), __fortio_errend03(), bitv, CADR, CLEN, delim, DIST_STATUS_BCST, f90_open(), GET_DIST_IOPROC, GET_DIST_LCPU, ISPRESENTC, LOCAL_MODE, name, NULL, pos, and s.
f90_open()
static int f90_open (__INT_T * unit, __INT_T * bitv, char * acc_ptr, char * action_ptr, char * blank_ptr, char * delim_ptr, char * name_ptr, char * form_ptr, __INT_T * iostat, char * pad_ptr, char * pos_ptr, __INT8_T * reclen, char * status_ptr, char * dispose_ptr, __CLEN_T acc_siz, __CLEN_T action_siz, __CLEN_T blank_siz, __CLEN_T delim_siz, __CLEN_T name_siz, __CLEN_T form_siz, __CLEN_T pad_siz, __CLEN_T pos_siz, __CLEN_T status_siz, __CLEN_T dispose_siz) static
Definition at line 323 of file open.c.
References __fortio_eq_str(), __fortio_errinit03(), __fortio_error(), __fortio_open(), fcb::binary, bitv, FALSE, Fcb, FIO_APOSTROPHE, FIO_APPEND, FIO_ASIS, FIO_DELETE, FIO_DIRECT, FIO_ECOMPAT, FIO_EDISPOSE, FIO_ENEWUNIT, FIO_EREADONLY, FIO_ERECL, FIO_ERECLEN, FIO_ESCRATCH, FIO_ESPEC, FIO_FORMATTED, FIO_KEEP, FIO_NEW, FIO_NO, FIO_NONE, FIO_NULL, FIO_OLD, FIO_QUOTE, FIO_READ, FIO_READWRITE, FIO_REPLACE, FIO_REWIND, FIO_SCRATCH, FIO_SEQUENTIAL, FIO_STREAM, FIO_UNFORMATTED, FIO_UNKNOWN, FIO_WRITE, FIO_YES, FIO_ZERO, fioFcbTbls, FIO_TBL::fname, FIO_TBL::fnamelen, get_gbl_newunit(), NULL, and TRUE.
Referenced by ENTCRF90IO(), and ENTF90IO().
Variable Documentation
Fcb
FIO_FCB* Fcb static
Definition at line 28 of file open.c.
Referenced by __fortio_open(), __INT_T(), ENTCRF90IO(), ENTF90IO(), and f90_open().
next_newunit
int next_newunit = -13
Definition at line 30 of file open.c.
Referenced by ENTF90IO().