flang: optimize.c File Reference
optimize.c File Reference
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "ast.h"
#include "nme.h"
#include "optimize.h"
#include "machar.h"
Functions
void dmpnme (void)
void open_pragma (int)
Find and open the set of loop pragmas associated with a line number.
void close_pragma (void)
Close the current pragmas => load the pragmas which have routine scope.
static void br_to_br (void)
static void merge_blocks (void)
static void loop_init (int lp)
static void replace_label (int bihx, int label, int newlab)
void optshrd_init (void)
void optshrd_finit (void)
void optshrd_fend (void)
void optshrd_end (void)
void hlopt_init (int hlopt_bv)
void hlopt_end (int hlopt_bv, int gbc)
static void optimize_init (void)
static void optimize_end (void)
static void function_init (void)
static void function_end (void)
static PSI_P remove_flow_list (PSI_P link, int r)
static void remove_loop (int lpx)
static int no_functions (int ast)
void optimize (int whichpass)
void add_loop_preheader (int lp)
void add_loop_exit (int lp)
void add_single_loop_exit (int lp)
static void remove_block (int std1, int std2, LOGICAL convert_elseif, LOGICAL save_endif)
void unconditional_branches (void)
Function Documentation
add_loop_exit()
void add_loop_exit (int lp)
Definition at line 784 of file optimize.c.
Referenced by optimize().
add_loop_preheader()
void add_loop_preheader (int lp)
Definition at line 620 of file optimize.c.
References add_pred(), add_succ(), assert, dump_node(), dump_region(), FG_DOM, FG_LNEXT, FG_LOOP, FG_LPREV, FG_NEXT, FG_PRED, FG_STDFIRST, FG_STDLAST, FG_SUCC, FG_TO_BIH, gbl, getlab(), i, label, lp, LP_FG, LP_HEAD, LP_PARENT, opt, OPTDBG, p, OPT::pre_fg, prev, PSI_FT, PSI_NEXT, PSI_NODE, PSI_P_NULL, q, replace_label(), STD_LABEL, STD_NEXT, STD_PREV, and void().
Referenced by add_loop_hd(), mk_loop_hdtl(), optimize(), and reassociate().
add_single_loop_exit()
void add_single_loop_exit (int lp)
Definition at line 790 of file optimize.c.
References add_fg(), add_pred(), add_stmt_after(), add_succ(), add_to_parent(), assert, ast, fg, FG_FT, FG_LABEL, FG_LINENO, FG_LOOP, FG_NEXT, FG_SUCC, FG_TO_BIH, getlab(), lp, LP_FG, LP_MEXITS, LP_PARENT, LP_TAIL, mk_label(), mk_stmt(), PSI_FT, PSI_NEXT, PSI_NODE, rdilts(), replace_label(), RFCNTI, rm_edge(), std, STD_LINENO, and wrilts().
Referenced by mk_loop_hdtl().
br_to_br()
static void br_to_br (void) static
Definition at line 545 of file optimize.c.
References OPT::num_nodes, opt, and XBIT.
Referenced by optimize().
close_pragma()
void close_pragma (void)
Close the current pragmas => load the pragmas which have routine scope.
Definition at line 105 of file ilidir.c.
References direct, load_dirset(), NULL, opened, and DIRECT::rou_begin.
Referenced by eliminate_redundant(), emit_copy_section(), emit_gatherx(), emit_scatterx_gatherx(), forall_dependency(), forall_dependency_scalarize(), hoist_loop(), lflow_of_block(), optimize(), resolve_pp(), resolve_pv(), rewrite_calls(), and schedule().
dmpnme()
void dmpnme (void)
Referenced by create_nmes(), expand(), and optimize().
function_end()
static void function_end (void) static
Definition at line 239 of file optimize.c.
References optshrd_fend().
Referenced by optimize().
function_init()
static void function_init (void) static
Definition at line 224 of file optimize.c.
References OPT::cnt_sym, OPT::cntlp, DBGBIT, gbl, getprint(), opt, and optshrd_finit().
Referenced by optimize().
hlopt_end()
void hlopt_end (int hlopt_bv, int gbc)
Definition at line 187 of file optimize.c.
References HLOPT_INDUC, induction_end(), optshrd_end(), and optshrd_fend().
Referenced by collapse_arrays(), and comm_invar().
hlopt_init()
void hlopt_init (int hlopt_bv)
Definition at line 159 of file optimize.c.
References DBGBIT, dump_flowgraph(), dump_loops(), findloop(), flow(), flowgraph(), HLOPT_INDUC, induction_init(), optshrd_finit(), and optshrd_init().
Referenced by collapse_arrays(), and comm_invar().
loop_init()
static void loop_init (int lp) static
Definition at line 581 of file optimize.c.
References OPT::exit_fg, FG_FT, FG_LPREV, FG_PAR, gbl, lp, LP_HEAD, LP_PARLOOP, LP_TAIL, NEW_NODE, opt, OPTDBG, and OPT::pre_fg.
Referenced by optimize().
merge_blocks()
static void merge_blocks (void) static
Definition at line 557 of file optimize.c.
References ast, OPT::num_nodes, opt, std, STD_AST, STD_LABEL, STD_NEXT, TRUE, unlnkilt(), and XBIT.
Referenced by optimize().
no_functions()
static int no_functions (int ast) static
Definition at line 320 of file optimize.c.
Referenced by optimize().
open_pragma()
void open_pragma (int line)
Find and open the set of loop pragmas associated with a line number.
SHOULD have a matching close_pragma().
Definition at line 81 of file ilidir.c.
References lpprg_::beg_line, direct, lpprg_::dirset, lpprg_::end_line, find_lpprg(), line, load_dirset(), DIRECT::lpg, match(), opened, DIRECT::stgb, and TR2.
Referenced by eliminate_redundant(), forall_dependency(), forall_dependency_scalarize(), hoist_loop(), lflow_of_block(), optimize(), resolve_pp(), resolve_pv(), rewrite_calls(), and schedule().
optimize()
void optimize (int whichpass)
Definition at line 327 of file optimize.c.
References add_arrnme(), add_loop_exit(), add_loop_preheader(), ast, br_to_br(), close_pragma(), DBGBIT, delete_stores(), dmpnme(), dump_flowgraph(), dump_loops(), dump_std(), OPT::exit_fg, OPT::exitfg, FALSE, fg, FG_HEAD, FG_INNERMOST, FG_LINENO, FG_LPREV, FG_MEXITS, FG_NEXT, FG_STDFIRST, FG_STDLAST, FG_TAIL, findloop(), flg, flow(), flow_end(), flowgraph(), function_end(), function_init(), gbl, HLOPT_ALL, i, induction(), invariant(), is_live_out(), loop_init(), LP_FG, LP_HEAD, LP_INNERMOST, LP_LOOP, LP_MEXITS, LP_PARLOOP, LP_TAIL, lpx, merge_blocks(), NEW_NODE, OPT::nloops, no_functions(), NT_VAR, open_pragma(), opt, OPTDBG, optimize_end(), optimize_init(), OPT::pre_fg, remove_loop(), OPT::sc, SC_AUTO, std, STD_AST, STD_NEXT, use_before_def(), FLG::x, and XBIT.
optimize_end()
static void optimize_end (void) static
Definition at line 211 of file optimize.c.
References induction_end(), and optshrd_end().
Referenced by optimize().
optimize_init()
static void optimize_init (void) static
Definition at line 199 of file optimize.c.
References induction_init(), and optshrd_init().
Referenced by optimize().
optshrd_end()
void optshrd_end (void)
Definition at line 137 of file optimize.c.
References astb, nme_end(), opt, STG_DELETE, and STG_DELETE_SIDECAR.
Referenced by comm_optimize_end(), Done(), early_flow_fini(), fini_points_to_prop(), hlopt_end(), optimize_end(), and sectfloat().
optshrd_fend()
void optshrd_fend (void)
Definition at line 126 of file optimize.c.
References DU_AREA, flow_end(), freearea(), PSI_AREA, and STL_AREA.
Referenced by comm_optimize_end(), early_flow_fini(), function_end(), hlopt_end(), and sectfloat().
optshrd_finit()
void optshrd_finit (void)
Definition at line 120 of file optimize.c.
Referenced by comm_optimize_init(), function_init(), hlopt_init(), and sectfloat().
optshrd_init()
void optshrd_init (void)
Definition at line 92 of file optimize.c.
References astb, gbl, LP_PARENT, nme_init(), opt, OPT::sc, SC_AUTO, STG_ALLOC, and STG_ALLOC_SIDECAR.
Referenced by comm_optimize_init(), early_flow_init(), hlopt_init(), init_points_to_prop(), optimize_init(), redundss(), and sectfloat().
remove_block()
static void remove_block (int std1, int std2, LOGICAL convert_elseif, LOGICAL save_endif) static
Definition at line 909 of file optimize.c.
References delete_stmt(), STD_AST, STD_LABEL, STD_NEXT, and stdx.
Referenced by unconditional_branches().
remove_flow_list()
static PSI_P remove_flow_list (PSI_P link, int r) static
Definition at line 250 of file optimize.c.
References next, NULL, PSI_NEXT, PSI_NODE, and r.
Referenced by remove_loop().
remove_loop()
static void remove_loop (int lpx) static
Definition at line 277 of file optimize.c.
References fg, FG_LOOP, FG_LPREV, FG_NEXT, FG_PRED, FG_SUCC, LP_CHILD, LP_FG, LP_HEAD, LP_INNERMOST, LP_PARENT, LP_SIBLING, LP_TAIL, lpx, next, parent, prev, and remove_flow_list().
Referenced by optimize().
replace_label()
static void replace_label (int bihx, int label, int newlab) static
Definition at line 887 of file optimize.c.
References A_STDP, ast, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), BIH_ILTLAST, label, mk_label(), std, and STD_AST.
Referenced by add_loop_preheader(), and add_single_loop_exit().
unconditional_branches()
void unconditional_branches (void)
Definition at line 941 of file optimize.c.
References CONVAL2G, DT_ISLOG, FALSE, FREE, NEED, NEW, remove_block(), sptr, STD_AST, STD_FG, STD_NEXT, stdx, and TRUE.