flang: optimize.h File Reference
optimize.h File Reference
arious definitions for the optimizer module
#include "findloop.h"
Classes
struct Q_TAG
struct PSI_TAG
struct SET_BASE
struct OAST
struct FG
struct EDGE
struct STORE
struct STL_TAG
struct LP
struct UD_TAG
struct USE
struct DU_TAG
struct DEF
struct OPT
Macros
#define OPTDBG(x, y) (DEBUG && DBGBIT(x, y))
#define ISSCALAR(s) TY_ISSCALAR(DTY(DTYPEG(s)))
#define IS_LCL(s) (SCG(s) == SC_LOCAL || SCG(s) == SC_PRIVATE)
#define IS_EXTERN(s) (SC_ISCMBLK(SCG(s)) || SCG(s) == SC_EXTERN)
#define IS_STATIC(s) (SCG(s) == SC_STATIC)
#define IS_CMNBLK(s) (SC_ISCMBLK(SCG(s)))
#define IS_DUM(s) (SCG(s) == SC_DUMMY)
#define IS_LCL_OR_DUM(s) (IS_LCL(s) || IS_DUM(s))
#define IS_REGARG(s) (REGARGG(s) && REDUCG(s))
#define IS_PRIVATE(s) (SCG(s) == SC_PRIVATE)
#define OPT_ALLOC(stgb, dt, sz)
#define OPT_NEXT(stb) stb.stg_avail++
#define OPT_NEED(stb, dt, sz)
#define OPT_FREE(stb)
#define PSI_AREA 0 /* pred/succ area */
#define BUCKET_AREA 1 /* item area for dominators */
#define IUSE_AREA 1 /* induction use area */
#define TOPI_AREA 2 /* item area for topological sort */
#define Q_AREA 2 /* queue area (used local to a routine */
#define DU_AREA 3 /* definition use and use def area */
#define STL_AREA 5 /* store list area */
#define DLT_AREA
#define Q_NULL NULL
#define GET_Q_ITEM(q) q = (Q_ITEM *)getitem(Q_AREA, sizeof(Q_ITEM))
#define PSI_P_NULL NULL
#define PSI_NODE(i) ((i)->node)
#define PSI_ALL(i) ((i)->flags.all)
#define PSI_FT(i) ((i)->flags.bits.f1)
#define PSI_ZTRP(i) ((i)->flags.bits.f2)
#define PSI_EXIT(i) ((i)->flags.bits.f4)
#define PSI_NEXT(i) ((i)->next)
#define GET_PSI(i) i = (PSI *)getitem(PSI_AREA, sizeof(PSI))
#define BITS_PER_BYTE 8
#define BV_BITS (sizeof(BV) * BITS_PER_BYTE)
#define FG_LINENO(i) opt.fgb.stg_base[i].lineno
#define FG_STDFIRST(i) opt.fgb.stg_base[i].first
#define FG_STDLAST(i) opt.fgb.stg_base[i].last
#define FG_LABEL(i) STD_LABEL(FG_STDFIRST(i))
#define FG_LNEXT(i) opt.fgb.stg_base[i].lnext
#define FG_LPREV(i) opt.fgb.stg_base[i].lprev
#define FG_DFN(i) opt.fgb.stg_base[i].dfn
#define FG_DOM(i) opt.fgb.stg_base[i].dom
#define FG_RDFN(i) opt.fgb.stg_base[i].rdfn
#define FG_RDFO(i) opt.fgb.stg_base[i].rdfo
#define FG_PDOM(i) opt.fgb.stg_base[i].pdom
#define FG_PRED(i) opt.fgb.stg_base[i].pred
#define FG_SUCC(i) opt.fgb.stg_base[i].succ
#define FG_LOOP(i) opt.fgb.stg_base[i].loop
#define FG_NEXT(i) opt.fgb.stg_base[i].next
#define FG_NATNXT(i) opt.fgb.stg_base[i].natnxt
#define FG_FDEF(i) opt.fgb.stg_base[i].fdef
#define FG_IN(i) opt.fgb.stg_base[i].in
#define FG_OUT(i) opt.fgb.stg_base[i].out
#define FG_UNINITED(i) opt.fgb.stg_base[i].uninited
#define FG_ATOMIC(i) opt.fgb.stg_base[i].atomic
#define FG_FT(i) opt.fgb.stg_base[i].flags.bits.ft
#define FG_HEAD(i) opt.fgb.stg_base[i].flags.bits.head
#define FG_TAIL(i) opt.fgb.stg_base[i].flags.bits.tail
#define FG_EX(i) opt.fgb.stg_base[i].flags.bits.ex
#define FG_EXSDSCUNSAFE(i) opt.fgb.stg_base[i].flags.bits.sdscunsafe
#define FG_EN(i) opt.fgb.stg_base[i].flags.bits.en
#define FG_XT(i) opt.fgb.stg_base[i].flags.bits.xt
#define FG_QJSR(i) opt.fgb.stg_base[i].flags.bits.qjsr
#define FG_MEXITS(i) opt.fgb.stg_base[i].flags.bits.mexits
#define FG_INNERMOST(i) opt.fgb.stg_base[i].flags.bits.innermost
#define FG_ZTRP(i) opt.fgb.stg_base[i].flags.bits.ztrp
#define FG_DONE(i) opt.fgb.stg_base[i].flags.bits.done
#define FG_INQ(i) opt.fgb.stg_base[i].flags.bits.inq
#define FG_VISITED(i) opt.fgb.stg_base[i].flags.bits.visited
#define FG_PTR_STORE(i) opt.fgb.stg_base[i].flags.bits.ptr_store
#define FG_JMP_TBL(i) opt.fgb.stg_base[i].flags.bits.jmp_tbl
#define FG_PAR(i) opt.fgb.stg_base[i].par
#define FG_CS(i) opt.fgb.stg_base[i].flags.bits.cs
#define FG_MASTER(i) opt.fgb.stg_base[i].flags.bits.master
#define FG_PARLOOP(i) opt.fgb.stg_base[i].parloop
#define FG_PARSECT(i) opt.fgb.stg_base[i].flags.bits.parsect
#define FG_TASK(i) opt.fgb.stg_base[i].flags.bits.task
#define FG_CTLEQUIV(i) opt.fgb.stg_base[i].flags.bits.ctlequiv
#define FG_MARK(i) opt.fgb.stg_base[i].flags.bits.mark
#define FG_MALF_LP(i) opt.fgb.stg_base[i].flags.bits.malf_lp
#define FG_ALL(i) opt.fgb.stg_base[i].flags.all
#define VTX_NODE(i) opt.fgb.stg_base[i].vtx
#define RVTX_NODE(i) opt.fgb.stg_base[i].rvtx
#define RDFOVTX_NODE(i) opt.fgb.stg_base[i].rdfovtx
#define FG_BIH(i) (i)
#define FG_TO_BIH(i) FG_BIH(i)
#define BIH_TO_FG(i) (i)
#define BIH_LINENO(i) FG_LINENO(i)
#define BIH_LABEL(i) FG_LABEL(i)
#define BIH_ILTFIRST(i) FG_STDFIRST(i)
#define BIH_ILTLAST(i) FG_STDLAST(i)
#define BIH_NEXT(i) FG_LNEXT(i)
#define BIH_PREV(i) FG_LPREV(i)
#define BIH_ASSN(i) opt.fgb.stg_base[i].scr
#define BIH_RGSET(i) opt.fgb.stg_base[i].scr2
#define BIH_FLAGS(i) FG_FLAGS(i)
#define BIH_FT(i) FG_FT(i)
#define BIH_EN(i) FG_EN(i)
#define BIH_EX(i) FG_EX(i)
#define BIH_EXSDSCUNSAFE(i) FG_EXSDSCUNSAFE(i)
#define BIH_XT(i) FG_XT(i)
#define BIH_ZTRP(i) FG_ZTRP(i)
#define BIH_HEAD(i) FG_HEAD(i)
#define BIH_TAIL(i) FG_TAIL(i)
#define BIH_INNERMOST(i) FG_INNERMOST(i)
#define BIH_QJSR(i) FG_QJSR(i)
#define BIH_MEXITS(i) FG_MEXITS(i)
#define BIH_PAR(i) FG_PAR(i)
#define BIH_CS(i) FG_CS(i)
#define BIH_MASTER(i) FG_MASTER(i)
#define BIH_PARLOOP(i) FG_PARLOOP(i)
#define BIH_PARSECT(i) FG_PARSECT(i)
#define BIH_TASK(i) FG_TASK(i)
#define NEW_NODE(after) add_fg(after)
#define EDGE_PRED(i) opt.rteb.stg_base[i].pred
#define EDGE_SUCC(i) opt.rteb.stg_base[i].succ
#define EDGE_NEXT(i) opt.rteb.stg_base[i].next
#define NUM_RTE (opt.rteb.stg_avail)
#define STORE_NM(i) opt.storeb.stg_base[i].nm
#define STORE_TYPE(i) opt.storeb.stg_base[i].type
#define STORE_NEXT(i) opt.storeb.stg_base[i].next
#define LP_LEVEL(i) opt.lpb.stg_base[i].level
#define LP_PARENT(i) opt.lpb.stg_base[i].parent
#define LP_HEAD(i) opt.lpb.stg_base[i].head
#define LP_TAIL(i) opt.lpb.stg_base[i].tail
#define LP_FG(i) opt.lpb.stg_base[i].fg
#define LP_LOOP(i) opt.lpb.stg_base[i].loop
#define LP_EDGE(i) opt.lpb.stg_base[i].edge
#define LP_CHILD(i) opt.lpb.stg_base[i].child
#define LP_SIBLING(i) opt.lpb.stg_base[i].sibling
#define LP_RGSET(i) opt.lpb.stg_base[i].rgset
#define LP_INNERMOST(i) opt.lpb.stg_base[i].flags.bits.innermost
#define LP_CALLFG(i) opt.lpb.stg_base[i].flags.bits.callfg
#define LP_CALLSDSCUNSAFE(i) opt.lpb.stg_base[i].flags.bits.sdscunsafe
#define LP_CALLINTERNAL(i) opt.lpb.stg_base[i].flags.bits.callinternal
#define LP_EXT_STORE(i) opt.lpb.stg_base[i].flags.bits.ext_store
#define LP_PTR_STORE(i) opt.lpb.stg_base[i].flags.bits.ptr_store
#define LP_PTR_LOAD(i) opt.lpb.stg_base[i].flags.bits.ptr_load
#define LP_ZEROTRIP(i) opt.lpb.stg_base[i].flags.bits.zerotrip
#define LP_NOBLA(i) opt.lpb.stg_base[i].flags.bits.nobla
#define LP_QJSR(i) opt.lpb.stg_base[i].flags.bits.qjsr
#define LP_MEXITS(i) opt.lpb.stg_base[i].flags.bits.mexits
#define LP_JMP_TBL(i) opt.lpb.stg_base[i].flags.bits.jmp_tbl
#define LP_INVARIF(i) opt.lpb.stg_base[i].flags.bits.invarif
#define LP_PARLOOP(i) opt.lpb.stg_base[i].parloop
#define LP_CS(i) opt.lpb.stg_base[i].flags.bits.cs
#define LP_CSECT(i) opt.lpb.stg_base[i].flags.bits.csect
#define LP_MARK(i) opt.lpb.stg_base[i].flags.bits.mark
#define LP_FORALL(i) opt.lpb.stg_base[i].flags.bits.forall
#define LP_MASTER(i) opt.lpb.stg_base[i].flags.bits.master
#define LP_PARREGN(i) opt.lpb.stg_base[i].flags.bits.parregn
#define LP_PARSECT(i) opt.lpb.stg_base[i].flags.bits.parsect
#define LP_XTNDRNG(i) opt.lpb.stg_base[i].flags.bits.xtndrng
#define LP_CNCALL(i) opt.lpb.stg_base[i].flags.bits.cncall
#define LP_VOLLAB(i) opt.lpb.stg_base[i].flags.bits.vollab
#define LP_TASK(i) opt.lpb.stg_base[i].flags.bits.task
#define LP_TAIL_AEXE(i) opt.lpb.stg_base[i].flags.bits.tail_aexe
#define LP_ALL(i) opt.lpb.stg_base[i].flags.all
#define LP_STL(i) opt.lpb.stg_base[i].stl
#define LP_LIN(i) opt.lpb.stg_base[i].lin
#define LP_LOUT(i) opt.lpb.stg_base[i].lout
#define LP_EXITS(i) opt.lpb.stg_base[i].exits
#define LP_STL_PAR(i) opt.lpb.stg_base[i].stl_par
#define LP_COUNT(i) opt.lpb.stg_base[i].count
#define LP_HSTDF(i) opt.lpb.stg_base[i].hstdf
#define LP_DSTDF(i) opt.lpb.stg_base[i].dstdf
#define USE_NM(i) opt.useb.stg_base[i].nm
#define USE_FG(i) opt.useb.stg_base[i].fg
#define USE_STD(i) opt.useb.stg_base[i].std
#define USE_AST(i) opt.useb.stg_base[i].ast
#define USE_ADDR(i) opt.useb.stg_base[i].addr
#define USE_EXPOSED(i) opt.useb.stg_base[i].flags.bits.exposed
#define USE_CSE(i) opt.useb.stg_base[i].flags.bits.cse
#define USE_PRECISE(i) opt.useb.stg_base[i].flags.bits.precise
#define USE_ARG(i) opt.useb.stg_base[i].flags.bits.arg
#define USE_DOINIT(i) opt.useb.stg_base[i].flags.bits.doinit
#define USE_MARK1(i) opt.useb.stg_base[i].flags.bits.mark1
#define USE_MARK2(i) opt.useb.stg_base[i].flags.bits.mark2
#define USE_LOOPENTRY(i) opt.useb.stg_base[i].flags.bits.loop
#define USE_AGGR(i) opt.useb.stg_base[i].flags.bits.aggr
#define USE_UD(i) opt.useb.stg_base[i].ud
#define DEF_FG(i) opt.defb.stg_base[i].fg
#define DEF_STD(i) opt.defb.stg_base[i].std
#define DEF_NM(i) opt.defb.stg_base[i].nm
#define DEF_LHS(i) opt.defb.stg_base[i].lhs
#define DEF_ADDR(i) opt.defb.stg_base[i].addr
#define DEF_RHS(i) opt.defb.stg_base[i].rhs
#define DEF_NEXT(i) opt.defb.stg_base[i].next
#define DEF_LNEXT(i) opt.defb.stg_base[i].lnext
#define DEF_ALL(i) opt.defb.stg_base[i].flags.all
#define DEF_GEN(i) opt.defb.stg_base[i].flags.bits.gen
#define DEF_CONST(i) opt.defb.stg_base[i].flags.bits.cnst
#define DEF_DELETE(i) opt.defb.stg_base[i].flags.bits.delete
#define DEF_SELF(i) opt.defb.stg_base[i].flags.bits.self
#define DEF_CONFL(i) opt.defb.stg_base[i].flags.bits.confl
#define DEF_DOINIT(i) opt.defb.stg_base[i].flags.bits.doinit
#define DEF_DOEND(i) opt.defb.stg_base[i].flags.bits.doend
#define DEF_ARG(i) opt.defb.stg_base[i].flags.bits.arg
#define DEF_OTHER(i) opt.defb.stg_base[i].flags.bits.other
#define DEF_PRECISE(i) opt.defb.stg_base[i].flags.bits.precise
#define DEF_MARK1(i) opt.defb.stg_base[i].flags.bits.mark1
#define DEF_MARK2(i) opt.defb.stg_base[i].flags.bits.mark2
#define DEF_LOOPENTRY(i) opt.defb.stg_base[i].flags.bits.loop
#define DEF_AGGR(i) opt.defb.stg_base[i].flags.bits.aggr
#define DEF_DU(i) opt.defb.stg_base[i].du
#define DEF_CSEL(i) opt.defb.stg_base[i].csel
#define CALL_DEF 1
#define PTR_STORE_DEF 2
#define QJSR_DEF 3
#define FIRST_DEF 4
#define NOT_INV -1
#define INV -2
#define T_INV -3 /* probably not used */
#define AST_INVG(i) opt.astb.stg_base[i].invar
#define AST_INVP(i, j) opt.astb.stg_base[i].invar = (j)
#define AST_ISINV(i) (AST_INVG(i) < -1)
#define AST_ISINV_TEMP(i) (AST_INVG(i) < -1)
#define IS_INVARIANT(i) (AST_ISINV(i) || AST_ISINV_TEMP(i))
#define ILI_ISINV(i) AST_ISINV(i)
#define HLOPT_INDUC 0x1
#define HLOPT_ENDTEST 0x2
#define HLOPT_ALL 0x3 /* 'or' of all HLOPT_... bits */
Typedefs
typedef unsigned short US
typedef struct Q_TAG Q_ITEM
typedef struct PSI_TAG * PSI_P
typedef struct PSI_TAG PSI
typedef int BV
typedef struct STL_TAG STL
typedef struct UD_TAG UD
typedef struct DU_TAG DU
Functions
void optshrd_init (void)
void optshrd_finit (void)
void optshrd_fend (void)
void optshrd_end (void)
void hlopt_init (int)
void hlopt_end (int, int)
void optimize (int)
void add_loop_preheader (int)
void add_loop_exit (int)
void add_single_loop_exit (int)
void flowgraph (void)
int add_fg (int)
Create an FG and insert it after FG after.
void delete_fg (int)
PSI_P add_succ (int, int)
PSI_P add_pred (int, int)
void rm_edge (int, int)
Remove the edge fg1 -> fg2 from the flowgraph.
int add_to_parent (int, int)
void dump_node (int)
void rdilts (int)
'read' a flowgraph node.
void wrilts (int)
'write' the flowgraph node.
void unlnkilt (int, int, int)
void delilt (int)
Delete an ilt from a block which is "read" and reuse it.
void dmpilt (int)
Dump ILT to global debug file.
void dump_flowgraph (void)
void flow (void)
void flow_end (void)
Cleanup up structures created by flow analysis and after a function has been optimized.
int update_stl (int, int)
Utility function to add a store item to a loop's store list.
LOGICAL is_live_in (int, int)
Utility functions to determine if a variable is live-in to a loop and live-out of a loop.
LOGICAL is_live_out (int, int)
void delete_stores (void)
Mark stores as deletable only if its uses follow the definition in the same block.
void use_before_def (void)
void add_new_uses (int, int, int, int)
Add use items for optimizable variables which occur in the ili expression which is a new expression being added to a flowgraph node (where) such as the preheader of the loop.
void invariant (int)
void invariant_nomotion (int)
void invariant_mark (int, int)
void invariant_unmark (void)
void invariant_unmarkv (void)
LOGICAL is_invariant (int)
LOGICAL is_sym_invariant_safe (int, int)
void induction_init (void)
void induction_end (void)
void induction (int)
int get_loop_count (int)
void compute_last_values (int, int)
void end_loop_count (void)
void bv_zero (int *, int)
void bv_copy (int *, int *, int)
void bv_union (int *, int *, int)
void bv_sub (int *, int *, int)
void bv_set (int *, int)
void bv_off (int *, int)
LOGICAL bv_notequal (int *, int *, int)
LOGICAL bv_mem (int *, int)
void bv_print (int *, int)
int get_otemp (void)
LOGICAL is_optsym (int)
LOGICAL is_sym_optsafe (int, int)
LOGICAL is_sym_live_safe (int, int)
LOGICAL is_call_safe (int)
LOGICAL is_ptr_safe (int)
LOGICAL is_sym_ptrsafe (int)
int pred_of_loop (int)
int find_rdef (int, int, LOGICAL)
LOGICAL is_sym_exit_live (int)
LOGICAL is_sym_imp_live (int)
LOGICAL is_sym_entry_live (int)
LOGICAL is_store_via_ptr (int)
LOGICAL can_copy_def (int, int, LOGICAL)
LOGICAL def_ok (int, int, int)
LOGICAL is_avail_expr (int, int, int, int, int)
LOGICAL is_call_in_path (int, int, int, int)
LOGICAL is_ptr_in_path (int, int, int, int)
LOGICAL single_ud (int)
LOGICAL only_one_ud (int)
LOGICAL is_def_imp_live (int)
void rm_def_rloop (int, int)
int copy_to_loop (int, int)
void points_to (void)
Do dataflow analysis to determine pointer target information store pointer target information at loads and stores.
void f90_fini_pointsto (void)
LOGICAL lhs_needtmp (int, int, int)
void postdominators (void)
void findlooptopsort (void)
findlooptopsort builds loops and adds the FG nodes to the loop in topological order, top-down.
void reorderloops ()
...
void putstdpta (int)
void putstdassigns (int)
void unconditional_branches (void)
void bv_intersect (BV *a, BV *b, UINT len)
void bv_intersect3 (BV *a, BV *b, BV *c, UINT len)
void optimize_alloc (void)
Try to optimize allocate statements.
void points_to_anal (void)
void fini_points_to_all (void)
bool pta_stride1 (int ptrstdx, int ptrsptr)
void pstride_analysis (void)
void fini_pstride_analysis (void)
void call_analyze (void)
void convert_output (void)
void sectfloat (void)
void sectinline (void)
void linearize_arrays (void)
void hoist_stmt (int std, int fg, int l)
void redundss (void)
int IPA_isnoconflict (int sptr)
int IPA_noconflict (int sptr)
void ipa_fini (void)
void ipa_closefile (void)
int IPA_arg_alloc (int funcsptr, int argnum)
int IPA_func_argalloc_safe (int sptr)
int IPA_func_globalalloc_safe (int sptr)
int IPA_safe (int sptr)
void ipa_restore_all (void)
void ipa_restore_back (void)
long IPA_sstride (int sptr)
long IPA_pstride (int sptr)
void ipa_mfilename (char *name)
void ipasave_fini (void)
void ipasave_closefile (void)
void ipasave (void)
int ipa_return_in_argument (int func)
int idsym (int cls, int id)
void ipasave_compname (char *, int, char **)
void ipasave_compsw (char *)
void ipasave_mfilename (char *)
void dstdp (int stdx)
void dumpdtypes (void)
void dastree (int astx)
void dsa (void)
void dast (int astx)
void past (int astx)
void dstda (void)
void dsym (int sptr)
void dstdpa (void)
Variables
OPT opt
int IPA_Vestigial
Detailed Description
arious definitions for the optimizer module
Definition in file optimize.h.
Macro Definition Documentation
AST_INVG
#define AST_INVG (i) opt.astb.stg_base[i].invar
Definition at line 624 of file optimize.h.
AST_INVP
#define AST_INVP (i, j) opt.astb.stg_base[i].invar = (j)
Definition at line 625 of file optimize.h.
AST_ISINV
#define AST_ISINV (i) (AST_INVG(i) < -1)
Definition at line 626 of file optimize.h.
AST_ISINV_TEMP
#define AST_ISINV_TEMP (i) (AST_INVG(i) < -1)
Definition at line 627 of file optimize.h.
BIH_ASSN
#define BIH_ASSN (i) opt.fgb.stg_base[i].scr
Definition at line 260 of file optimize.h.
BIH_CS
#define BIH_CS (i) FG_CS(i)
Definition at line 275 of file optimize.h.
BIH_EN
#define BIH_EN (i) FG_EN(i)
Definition at line 264 of file optimize.h.
BIH_EX
#define BIH_EX (i) FG_EX(i)
Definition at line 265 of file optimize.h.
BIH_EXSDSCUNSAFE
#define BIH_EXSDSCUNSAFE (i) FG_EXSDSCUNSAFE(i)
Definition at line 266 of file optimize.h.
BIH_FLAGS
#define BIH_FLAGS (i) FG_FLAGS(i)
Definition at line 262 of file optimize.h.
BIH_FT
#define BIH_FT (i) FG_FT(i)
Definition at line 263 of file optimize.h.
BIH_HEAD
#define BIH_HEAD (i) FG_HEAD(i)
Definition at line 269 of file optimize.h.
BIH_ILTFIRST
#define BIH_ILTFIRST (i) FG_STDFIRST(i)
Definition at line 256 of file optimize.h.
BIH_ILTLAST
#define BIH_ILTLAST (i) FG_STDLAST(i)
Definition at line 257 of file optimize.h.
BIH_INNERMOST
#define BIH_INNERMOST (i) FG_INNERMOST(i)
Definition at line 271 of file optimize.h.
BIH_LABEL
#define BIH_LABEL (i) FG_LABEL(i)
Definition at line 255 of file optimize.h.
BIH_LINENO
#define BIH_LINENO (i) FG_LINENO(i)
Definition at line 254 of file optimize.h.
BIH_MASTER
#define BIH_MASTER (i) FG_MASTER(i)
Definition at line 276 of file optimize.h.
BIH_MEXITS
#define BIH_MEXITS (i) FG_MEXITS(i)
Definition at line 273 of file optimize.h.
BIH_NEXT
#define BIH_NEXT (i) FG_LNEXT(i)
Definition at line 258 of file optimize.h.
BIH_PAR
#define BIH_PAR (i) FG_PAR(i)
Definition at line 274 of file optimize.h.
BIH_PARLOOP
#define BIH_PARLOOP (i) FG_PARLOOP(i)
Definition at line 277 of file optimize.h.
BIH_PARSECT
#define BIH_PARSECT (i) FG_PARSECT(i)
Definition at line 278 of file optimize.h.
BIH_PREV
#define BIH_PREV (i) FG_LPREV(i)
Definition at line 259 of file optimize.h.
BIH_QJSR
#define BIH_QJSR (i) FG_QJSR(i)
Definition at line 272 of file optimize.h.
BIH_RGSET
#define BIH_RGSET (i) opt.fgb.stg_base[i].scr2
Definition at line 261 of file optimize.h.
BIH_TAIL
#define BIH_TAIL (i) FG_TAIL(i)
Definition at line 270 of file optimize.h.
BIH_TASK
#define BIH_TASK (i) FG_TASK(i)
Definition at line 279 of file optimize.h.
BIH_TO_FG
#define BIH_TO_FG (i) (i)
Definition at line 253 of file optimize.h.
BIH_XT
#define BIH_XT (i) FG_XT(i)
Definition at line 267 of file optimize.h.
BIH_ZTRP
#define BIH_ZTRP (i) FG_ZTRP(i)
Definition at line 268 of file optimize.h.
BITS_PER_BYTE
#define BITS_PER_BYTE 8
Definition at line 118 of file optimize.h.
BUCKET_AREA
#define BUCKET_AREA 1 /* item area for dominators */
Definition at line 58 of file optimize.h.
BV_BITS
#define BV_BITS (sizeof(BV) * BITS_PER_BYTE)
Definition at line 128 of file optimize.h.
CALL_DEF
#define CALL_DEF 1
Definition at line 613 of file optimize.h.
DEF_ADDR
#define DEF_ADDR (i) opt.defb.stg_base[i].addr
Definition at line 587 of file optimize.h.
DEF_AGGR
#define DEF_AGGR (i) opt.defb.stg_base[i].flags.bits.aggr
Definition at line 605 of file optimize.h.
DEF_ALL
#define DEF_ALL (i) opt.defb.stg_base[i].flags.all
Definition at line 591 of file optimize.h.
DEF_ARG
#define DEF_ARG (i) opt.defb.stg_base[i].flags.bits.arg
Definition at line 599 of file optimize.h.
DEF_CONFL
#define DEF_CONFL (i) opt.defb.stg_base[i].flags.bits.confl
Definition at line 596 of file optimize.h.
DEF_CONST
#define DEF_CONST (i) opt.defb.stg_base[i].flags.bits.cnst
Definition at line 593 of file optimize.h.
DEF_CSEL
#define DEF_CSEL (i) opt.defb.stg_base[i].csel
Definition at line 607 of file optimize.h.
DEF_DELETE
#define DEF_DELETE (i) opt.defb.stg_base[i].flags.bits.delete
Definition at line 594 of file optimize.h.
DEF_DOEND
#define DEF_DOEND (i) opt.defb.stg_base[i].flags.bits.doend
Definition at line 598 of file optimize.h.
DEF_DOINIT
#define DEF_DOINIT (i) opt.defb.stg_base[i].flags.bits.doinit
Definition at line 597 of file optimize.h.
DEF_DU
#define DEF_DU (i) opt.defb.stg_base[i].du
Definition at line 606 of file optimize.h.
DEF_FG
#define DEF_FG (i) opt.defb.stg_base[i].fg
Definition at line 583 of file optimize.h.
DEF_GEN
#define DEF_GEN (i) opt.defb.stg_base[i].flags.bits.gen
Definition at line 592 of file optimize.h.
DEF_LHS
#define DEF_LHS (i) opt.defb.stg_base[i].lhs
Definition at line 586 of file optimize.h.
DEF_LNEXT
#define DEF_LNEXT (i) opt.defb.stg_base[i].lnext
Definition at line 590 of file optimize.h.
DEF_LOOPENTRY
#define DEF_LOOPENTRY (i) opt.defb.stg_base[i].flags.bits.loop
Definition at line 604 of file optimize.h.
DEF_MARK1
#define DEF_MARK1 (i) opt.defb.stg_base[i].flags.bits.mark1
Definition at line 602 of file optimize.h.
DEF_MARK2
#define DEF_MARK2 (i) opt.defb.stg_base[i].flags.bits.mark2
Definition at line 603 of file optimize.h.
DEF_NEXT
#define DEF_NEXT (i) opt.defb.stg_base[i].next
Definition at line 589 of file optimize.h.
DEF_NM
#define DEF_NM (i) opt.defb.stg_base[i].nm
Definition at line 585 of file optimize.h.
DEF_OTHER
#define DEF_OTHER (i) opt.defb.stg_base[i].flags.bits.other
Definition at line 600 of file optimize.h.
DEF_PRECISE
#define DEF_PRECISE (i) opt.defb.stg_base[i].flags.bits.precise
Definition at line 601 of file optimize.h.
DEF_RHS
#define DEF_RHS (i) opt.defb.stg_base[i].rhs
Definition at line 588 of file optimize.h.
DEF_SELF
#define DEF_SELF (i) opt.defb.stg_base[i].flags.bits.self
Definition at line 595 of file optimize.h.
DEF_STD
#define DEF_STD (i) opt.defb.stg_base[i].std
Definition at line 584 of file optimize.h.
DLT_AREA
#define DLT_AREA
Value:
  9 /* list of stds to be deleted in flow(); can't \
     * be shared with flowgraph() and findloops(). \
     */
Definition at line 64 of file optimize.h.
DU_AREA
#define DU_AREA 3 /* definition use and use def area */
Definition at line 62 of file optimize.h.
EDGE_NEXT
#define EDGE_NEXT (i) opt.rteb.stg_base[i].next
Definition at line 296 of file optimize.h.
EDGE_PRED
#define EDGE_PRED (i) opt.rteb.stg_base[i].pred
Definition at line 294 of file optimize.h.
EDGE_SUCC
#define EDGE_SUCC (i) opt.rteb.stg_base[i].succ
Definition at line 295 of file optimize.h.
FG_ALL
#define FG_ALL (i) opt.fgb.stg_base[i].flags.all
Definition at line 244 of file optimize.h.
FG_ATOMIC
#define FG_ATOMIC (i) opt.fgb.stg_base[i].atomic
Definition at line 218 of file optimize.h.
FG_BIH
#define FG_BIH (i) (i)
Definition at line 251 of file optimize.h.
FG_CS
#define FG_CS (i) opt.fgb.stg_base[i].flags.bits.cs
Definition at line 236 of file optimize.h.
FG_CTLEQUIV
#define FG_CTLEQUIV (i) opt.fgb.stg_base[i].flags.bits.ctlequiv
Definition at line 241 of file optimize.h.
FG_DFN
#define FG_DFN (i) opt.fgb.stg_base[i].dfn
Definition at line 204 of file optimize.h.
FG_DOM
#define FG_DOM (i) opt.fgb.stg_base[i].dom
Definition at line 205 of file optimize.h.
FG_DONE
#define FG_DONE (i) opt.fgb.stg_base[i].flags.bits.done
Definition at line 230 of file optimize.h.
FG_EN
#define FG_EN (i) opt.fgb.stg_base[i].flags.bits.en
Definition at line 224 of file optimize.h.
FG_EX
#define FG_EX (i) opt.fgb.stg_base[i].flags.bits.ex
Definition at line 222 of file optimize.h.
FG_EXSDSCUNSAFE
#define FG_EXSDSCUNSAFE (i) opt.fgb.stg_base[i].flags.bits.sdscunsafe
Definition at line 223 of file optimize.h.
FG_FDEF
#define FG_FDEF (i) opt.fgb.stg_base[i].fdef
Definition at line 214 of file optimize.h.
FG_FT
#define FG_FT (i) opt.fgb.stg_base[i].flags.bits.ft
Definition at line 219 of file optimize.h.
FG_HEAD
#define FG_HEAD (i) opt.fgb.stg_base[i].flags.bits.head
Definition at line 220 of file optimize.h.
FG_IN
#define FG_IN (i) opt.fgb.stg_base[i].in
Definition at line 215 of file optimize.h.
FG_INNERMOST
#define FG_INNERMOST (i) opt.fgb.stg_base[i].flags.bits.innermost
Definition at line 228 of file optimize.h.
FG_INQ
#define FG_INQ (i) opt.fgb.stg_base[i].flags.bits.inq
Definition at line 231 of file optimize.h.
FG_JMP_TBL
#define FG_JMP_TBL (i) opt.fgb.stg_base[i].flags.bits.jmp_tbl
Definition at line 234 of file optimize.h.
FG_LABEL
#define FG_LABEL (i) STD_LABEL(FG_STDFIRST(i))
Definition at line 201 of file optimize.h.
FG_LINENO
#define FG_LINENO (i) opt.fgb.stg_base[i].lineno
Definition at line 198 of file optimize.h.
FG_LNEXT
#define FG_LNEXT (i) opt.fgb.stg_base[i].lnext
Definition at line 202 of file optimize.h.
FG_LOOP
#define FG_LOOP (i) opt.fgb.stg_base[i].loop
Definition at line 211 of file optimize.h.
FG_LPREV
#define FG_LPREV (i) opt.fgb.stg_base[i].lprev
Definition at line 203 of file optimize.h.
FG_MALF_LP
#define FG_MALF_LP (i) opt.fgb.stg_base[i].flags.bits.malf_lp
Definition at line 243 of file optimize.h.
FG_MARK
#define FG_MARK (i) opt.fgb.stg_base[i].flags.bits.mark
Definition at line 242 of file optimize.h.
FG_MASTER
#define FG_MASTER (i) opt.fgb.stg_base[i].flags.bits.master
Definition at line 237 of file optimize.h.
FG_MEXITS
#define FG_MEXITS (i) opt.fgb.stg_base[i].flags.bits.mexits
Definition at line 227 of file optimize.h.
FG_NATNXT
#define FG_NATNXT (i) opt.fgb.stg_base[i].natnxt
Definition at line 213 of file optimize.h.
FG_NEXT
#define FG_NEXT (i) opt.fgb.stg_base[i].next
Definition at line 212 of file optimize.h.
FG_OUT
#define FG_OUT (i) opt.fgb.stg_base[i].out
Definition at line 216 of file optimize.h.
FG_PAR
#define FG_PAR (i) opt.fgb.stg_base[i].par
Definition at line 235 of file optimize.h.
FG_PARLOOP
#define FG_PARLOOP (i) opt.fgb.stg_base[i].parloop
Definition at line 238 of file optimize.h.
FG_PARSECT
#define FG_PARSECT (i) opt.fgb.stg_base[i].flags.bits.parsect
Definition at line 239 of file optimize.h.
FG_PDOM
#define FG_PDOM (i) opt.fgb.stg_base[i].pdom
Definition at line 208 of file optimize.h.
FG_PRED
#define FG_PRED (i) opt.fgb.stg_base[i].pred
Definition at line 209 of file optimize.h.
FG_PTR_STORE
#define FG_PTR_STORE (i) opt.fgb.stg_base[i].flags.bits.ptr_store
Definition at line 233 of file optimize.h.
FG_QJSR
#define FG_QJSR (i) opt.fgb.stg_base[i].flags.bits.qjsr
Definition at line 226 of file optimize.h.
FG_RDFN
#define FG_RDFN (i) opt.fgb.stg_base[i].rdfn
Definition at line 206 of file optimize.h.
FG_RDFO
#define FG_RDFO (i) opt.fgb.stg_base[i].rdfo
Definition at line 207 of file optimize.h.
FG_STDFIRST
#define FG_STDFIRST (i) opt.fgb.stg_base[i].first
Definition at line 199 of file optimize.h.
FG_STDLAST
#define FG_STDLAST (i) opt.fgb.stg_base[i].last
Definition at line 200 of file optimize.h.
FG_SUCC
#define FG_SUCC (i) opt.fgb.stg_base[i].succ
Definition at line 210 of file optimize.h.
FG_TAIL
#define FG_TAIL (i) opt.fgb.stg_base[i].flags.bits.tail
Definition at line 221 of file optimize.h.
FG_TASK
#define FG_TASK (i) opt.fgb.stg_base[i].flags.bits.task
Definition at line 240 of file optimize.h.
FG_TO_BIH
#define FG_TO_BIH (i) FG_BIH(i)
Definition at line 252 of file optimize.h.
FG_UNINITED
#define FG_UNINITED (i) opt.fgb.stg_base[i].uninited
Definition at line 217 of file optimize.h.
FG_VISITED
#define FG_VISITED (i) opt.fgb.stg_base[i].flags.bits.visited
Definition at line 232 of file optimize.h.
FG_XT
#define FG_XT (i) opt.fgb.stg_base[i].flags.bits.xt
Definition at line 225 of file optimize.h.
FG_ZTRP
#define FG_ZTRP (i) opt.fgb.stg_base[i].flags.bits.ztrp
Definition at line 229 of file optimize.h.
FIRST_DEF
#define FIRST_DEF 4
Definition at line 616 of file optimize.h.
GET_PSI
#define GET_PSI (i) i = (PSI *)getitem(PSI_AREA, sizeof(PSI))
Definition at line 114 of file optimize.h.
GET_Q_ITEM
#define GET_Q_ITEM (q) q = (Q_ITEM *)getitem(Q_AREA, sizeof(Q_ITEM))
Definition at line 75 of file optimize.h.
HLOPT_ALL
#define HLOPT_ALL 0x3 /* 'or' of all HLOPT_... bits */
Definition at line 684 of file optimize.h.
HLOPT_ENDTEST
#define HLOPT_ENDTEST 0x2
Definition at line 683 of file optimize.h.
HLOPT_INDUC
#define HLOPT_INDUC 0x1
Definition at line 682 of file optimize.h.
ILI_ISINV
#define ILI_ISINV (i) AST_ISINV(i)
Definition at line 630 of file optimize.h.
INV
#define INV -2
Definition at line 621 of file optimize.h.
IS_CMNBLK
#define IS_CMNBLK (s) (SC_ISCMBLK(SCG(s)))
Definition at line 23 of file optimize.h.
IS_DUM
#define IS_DUM (s) (SCG(s) == SC_DUMMY)
Definition at line 24 of file optimize.h.
IS_EXTERN
#define IS_EXTERN (s) (SC_ISCMBLK(SCG(s)) || SCG(s) == SC_EXTERN)
Definition at line 21 of file optimize.h.
IS_INVARIANT
#define IS_INVARIANT (i) (AST_ISINV(i) || AST_ISINV_TEMP(i))
Definition at line 628 of file optimize.h.
IS_LCL
#define IS_LCL (s) (SCG(s) == SC_LOCAL || SCG(s) == SC_PRIVATE)
Definition at line 20 of file optimize.h.
IS_LCL_OR_DUM
#define IS_LCL_OR_DUM (s) (IS_LCL(s) || IS_DUM(s))
Definition at line 25 of file optimize.h.
IS_PRIVATE
#define IS_PRIVATE (s) (SCG(s) == SC_PRIVATE)
Definition at line 28 of file optimize.h.
IS_REGARG
#define IS_REGARG (s) (REGARGG(s) && REDUCG(s))
Definition at line 26 of file optimize.h.
IS_STATIC
#define IS_STATIC (s) (SCG(s) == SC_STATIC)
Definition at line 22 of file optimize.h.
ISSCALAR
#define ISSCALAR (s) TY_ISSCALAR(DTY(DTYPEG(s)))
Definition at line 18 of file optimize.h.
IUSE_AREA
#define IUSE_AREA 1 /* induction use area */
Definition at line 59 of file optimize.h.
LP_ALL
#define LP_ALL (i) opt.lpb.stg_base[i].flags.all
Definition at line 464 of file optimize.h.
LP_CALLFG
#define LP_CALLFG (i) opt.lpb.stg_base[i].flags.bits.callfg
Definition at line 439 of file optimize.h.
LP_CALLINTERNAL
#define LP_CALLINTERNAL (i) opt.lpb.stg_base[i].flags.bits.callinternal
Definition at line 441 of file optimize.h.
LP_CALLSDSCUNSAFE
#define LP_CALLSDSCUNSAFE (i) opt.lpb.stg_base[i].flags.bits.sdscunsafe
Definition at line 440 of file optimize.h.
LP_CHILD
#define LP_CHILD (i) opt.lpb.stg_base[i].child
Definition at line 435 of file optimize.h.
LP_CNCALL
#define LP_CNCALL (i) opt.lpb.stg_base[i].flags.bits.cncall
Definition at line 460 of file optimize.h.
LP_COUNT
#define LP_COUNT (i) opt.lpb.stg_base[i].count
Definition at line 470 of file optimize.h.
LP_CS
#define LP_CS (i) opt.lpb.stg_base[i].flags.bits.cs
Definition at line 452 of file optimize.h.
LP_CSECT
#define LP_CSECT (i) opt.lpb.stg_base[i].flags.bits.csect
Definition at line 453 of file optimize.h.
LP_DSTDF
#define LP_DSTDF (i) opt.lpb.stg_base[i].dstdf
Definition at line 472 of file optimize.h.
LP_EDGE
#define LP_EDGE (i) opt.lpb.stg_base[i].edge
Definition at line 434 of file optimize.h.
LP_EXITS
#define LP_EXITS (i) opt.lpb.stg_base[i].exits
Definition at line 468 of file optimize.h.
LP_EXT_STORE
#define LP_EXT_STORE (i) opt.lpb.stg_base[i].flags.bits.ext_store
Definition at line 442 of file optimize.h.
LP_FG
#define LP_FG (i) opt.lpb.stg_base[i].fg
Definition at line 432 of file optimize.h.
LP_FORALL
#define LP_FORALL (i) opt.lpb.stg_base[i].flags.bits.forall
Definition at line 455 of file optimize.h.
LP_HEAD
#define LP_HEAD (i) opt.lpb.stg_base[i].head
Definition at line 430 of file optimize.h.
LP_HSTDF
#define LP_HSTDF (i) opt.lpb.stg_base[i].hstdf
Definition at line 471 of file optimize.h.
LP_INNERMOST
#define LP_INNERMOST (i) opt.lpb.stg_base[i].flags.bits.innermost
Definition at line 438 of file optimize.h.
LP_INVARIF
#define LP_INVARIF (i) opt.lpb.stg_base[i].flags.bits.invarif
Definition at line 450 of file optimize.h.
LP_JMP_TBL
#define LP_JMP_TBL (i) opt.lpb.stg_base[i].flags.bits.jmp_tbl
Definition at line 449 of file optimize.h.
LP_LEVEL
#define LP_LEVEL (i) opt.lpb.stg_base[i].level
Definition at line 428 of file optimize.h.
LP_LIN
#define LP_LIN (i) opt.lpb.stg_base[i].lin
Definition at line 466 of file optimize.h.
LP_LOOP
#define LP_LOOP (i) opt.lpb.stg_base[i].loop
Definition at line 433 of file optimize.h.
LP_LOUT
#define LP_LOUT (i) opt.lpb.stg_base[i].lout
Definition at line 467 of file optimize.h.
LP_MARK
#define LP_MARK (i) opt.lpb.stg_base[i].flags.bits.mark
Definition at line 454 of file optimize.h.
LP_MASTER
#define LP_MASTER (i) opt.lpb.stg_base[i].flags.bits.master
Definition at line 456 of file optimize.h.
LP_MEXITS
#define LP_MEXITS (i) opt.lpb.stg_base[i].flags.bits.mexits
Definition at line 448 of file optimize.h.
LP_NOBLA
#define LP_NOBLA (i) opt.lpb.stg_base[i].flags.bits.nobla
Definition at line 446 of file optimize.h.
LP_PARENT
#define LP_PARENT (i) opt.lpb.stg_base[i].parent
Definition at line 429 of file optimize.h.
LP_PARLOOP
#define LP_PARLOOP (i) opt.lpb.stg_base[i].parloop
Definition at line 451 of file optimize.h.
LP_PARREGN
#define LP_PARREGN (i) opt.lpb.stg_base[i].flags.bits.parregn
Definition at line 457 of file optimize.h.
LP_PARSECT
#define LP_PARSECT (i) opt.lpb.stg_base[i].flags.bits.parsect
Definition at line 458 of file optimize.h.
LP_PTR_LOAD
#define LP_PTR_LOAD (i) opt.lpb.stg_base[i].flags.bits.ptr_load
Definition at line 444 of file optimize.h.
LP_PTR_STORE
#define LP_PTR_STORE (i) opt.lpb.stg_base[i].flags.bits.ptr_store
Definition at line 443 of file optimize.h.
LP_QJSR
#define LP_QJSR (i) opt.lpb.stg_base[i].flags.bits.qjsr
Definition at line 447 of file optimize.h.
LP_RGSET
#define LP_RGSET (i) opt.lpb.stg_base[i].rgset
Definition at line 437 of file optimize.h.
LP_SIBLING
#define LP_SIBLING (i) opt.lpb.stg_base[i].sibling
Definition at line 436 of file optimize.h.
LP_STL
#define LP_STL (i) opt.lpb.stg_base[i].stl
Definition at line 465 of file optimize.h.
LP_STL_PAR
#define LP_STL_PAR (i) opt.lpb.stg_base[i].stl_par
Definition at line 469 of file optimize.h.
LP_TAIL
#define LP_TAIL (i) opt.lpb.stg_base[i].tail
Definition at line 431 of file optimize.h.
LP_TAIL_AEXE
#define LP_TAIL_AEXE (i) opt.lpb.stg_base[i].flags.bits.tail_aexe
Definition at line 463 of file optimize.h.
LP_TASK
#define LP_TASK (i) opt.lpb.stg_base[i].flags.bits.task
Definition at line 462 of file optimize.h.
LP_VOLLAB
#define LP_VOLLAB (i) opt.lpb.stg_base[i].flags.bits.vollab
Definition at line 461 of file optimize.h.
LP_XTNDRNG
#define LP_XTNDRNG (i) opt.lpb.stg_base[i].flags.bits.xtndrng
Definition at line 459 of file optimize.h.
LP_ZEROTRIP
#define LP_ZEROTRIP (i) opt.lpb.stg_base[i].flags.bits.zerotrip
Definition at line 445 of file optimize.h.
NEW_NODE
#define NEW_NODE (after) add_fg(after)
Definition at line 284 of file optimize.h.
NOT_INV
#define NOT_INV -1
Definition at line 620 of file optimize.h.
NUM_RTE
#define NUM_RTE (opt.rteb.stg_avail)
Definition at line 297 of file optimize.h.
OPT_ALLOC
#define OPT_ALLOC (stgb, dt, sz)
Value:
  {                             \
    NEW(stgb.stg_base, dt, sz); \
    stgb.stg_size = sz;         \
  }
Definition at line 32 of file optimize.h.
OPT_FREE
#define OPT_FREE (stb)
Value:
  {                      \
    FREE(stb.stg_base);  \
    stb.stg_base = NULL; \
    stb.stg_size = 0;    \
    stb.stg_avail = 0;   \
  }
Definition at line 45 of file optimize.h.
OPT_NEED
#define OPT_NEED (stb, dt, sz)
Value:
  {                                                                         \
    NEED(stb.stg_avail, stb.stg_base, dt, stb.stg_size, stb.stg_size + sz); \
  }
Definition at line 40 of file optimize.h.
OPT_NEXT
#define OPT_NEXT (stb) stb.stg_avail++
Definition at line 38 of file optimize.h.
OPTDBG
#define OPTDBG (x, y) (DEBUG && DBGBIT(x, y))
Definition at line 14 of file optimize.h.
PSI_ALL
#define PSI_ALL (i) ((i)->flags.all)
Definition at line 109 of file optimize.h.
PSI_AREA
#define PSI_AREA 0 /* pred/succ area */
Definition at line 57 of file optimize.h.
PSI_EXIT
#define PSI_EXIT (i) ((i)->flags.bits.f4)
Definition at line 112 of file optimize.h.
PSI_FT
#define PSI_FT (i) ((i)->flags.bits.f1)
Definition at line 110 of file optimize.h.
PSI_NEXT
#define PSI_NEXT (i) ((i)->next)
Definition at line 113 of file optimize.h.
PSI_NODE
#define PSI_NODE (i) ((i)->node)
Definition at line 108 of file optimize.h.
PSI_P_NULL
#define PSI_P_NULL NULL
Definition at line 80 of file optimize.h.
PSI_ZTRP
#define PSI_ZTRP (i) ((i)->flags.bits.f2)
Definition at line 111 of file optimize.h.
PTR_STORE_DEF
#define PTR_STORE_DEF 2
Definition at line 614 of file optimize.h.
Q_AREA
#define Q_AREA 2 /* queue area (used local to a routine */
Definition at line 61 of file optimize.h.
Q_NULL
#define Q_NULL NULL
Definition at line 74 of file optimize.h.
QJSR_DEF
#define QJSR_DEF 3
Definition at line 615 of file optimize.h.
RDFOVTX_NODE
#define RDFOVTX_NODE (i) opt.fgb.stg_base[i].rdfovtx
Definition at line 247 of file optimize.h.
RVTX_NODE
#define RVTX_NODE (i) opt.fgb.stg_base[i].rvtx
Definition at line 246 of file optimize.h.
STL_AREA
#define STL_AREA 5 /* store list area */
Definition at line 63 of file optimize.h.
STORE_NEXT
#define STORE_NEXT (i) opt.storeb.stg_base[i].next
Definition at line 312 of file optimize.h.
STORE_NM
#define STORE_NM (i) opt.storeb.stg_base[i].nm
Definition at line 310 of file optimize.h.
STORE_TYPE
#define STORE_TYPE (i) opt.storeb.stg_base[i].type
Definition at line 311 of file optimize.h.
T_INV
#define T_INV -3 /* probably not used */
Definition at line 622 of file optimize.h.
TOPI_AREA
#define TOPI_AREA 2 /* item area for topological sort */
Definition at line 60 of file optimize.h.
USE_ADDR
#define USE_ADDR (i) opt.useb.stg_base[i].addr
Definition at line 512 of file optimize.h.
USE_AGGR
#define USE_AGGR (i) opt.useb.stg_base[i].flags.bits.aggr
Definition at line 521 of file optimize.h.
USE_ARG
#define USE_ARG (i) opt.useb.stg_base[i].flags.bits.arg
Definition at line 516 of file optimize.h.
USE_AST
#define USE_AST (i) opt.useb.stg_base[i].ast
Definition at line 511 of file optimize.h.
USE_CSE
#define USE_CSE (i) opt.useb.stg_base[i].flags.bits.cse
Definition at line 514 of file optimize.h.
USE_DOINIT
#define USE_DOINIT (i) opt.useb.stg_base[i].flags.bits.doinit
Definition at line 517 of file optimize.h.
USE_EXPOSED
#define USE_EXPOSED (i) opt.useb.stg_base[i].flags.bits.exposed
Definition at line 513 of file optimize.h.
USE_FG
#define USE_FG (i) opt.useb.stg_base[i].fg
Definition at line 509 of file optimize.h.
USE_LOOPENTRY
#define USE_LOOPENTRY (i) opt.useb.stg_base[i].flags.bits.loop
Definition at line 520 of file optimize.h.
USE_MARK1
#define USE_MARK1 (i) opt.useb.stg_base[i].flags.bits.mark1
Definition at line 518 of file optimize.h.
USE_MARK2
#define USE_MARK2 (i) opt.useb.stg_base[i].flags.bits.mark2
Definition at line 519 of file optimize.h.
USE_NM
#define USE_NM (i) opt.useb.stg_base[i].nm
Definition at line 508 of file optimize.h.
USE_PRECISE
#define USE_PRECISE (i) opt.useb.stg_base[i].flags.bits.precise
Definition at line 515 of file optimize.h.
USE_STD
#define USE_STD (i) opt.useb.stg_base[i].std
Definition at line 510 of file optimize.h.
USE_UD
#define USE_UD (i) opt.useb.stg_base[i].ud
Definition at line 522 of file optimize.h.
VTX_NODE
#define VTX_NODE (i) opt.fgb.stg_base[i].vtx
Definition at line 245 of file optimize.h.
Typedef Documentation
BV
typedef int BV
Definition at line 120 of file optimize.h.
DU
typedef struct DU_TAG DU
PSI
typedef struct PSI_TAG PSI
PSI_P
typedef struct PSI_TAG* PSI_P
Definition at line 79 of file optimize.h.
Q_ITEM
typedef struct Q_TAG Q_ITEM
STL
typedef struct STL_TAG STL
UD
typedef struct UD_TAG UD
US
typedef unsigned short US
Definition at line 53 of file optimize.h.
Function Documentation
add_fg()
int add_fg (int after)
Create an FG and insert it after FG after.
Definition at line 1276 of file fgraph.c.
References a, after, BZERO, fg, FG_LNEXT, FG_LPREV, i, OPT::num_nodes, opt, and OPT_NEED.
Referenced by add_loop_hd(), add_single_loop_exit(), cr_block(), forall_dependency(), mk_loop_hdtl(), partition_blocks(), and reassociate().
add_loop_exit()
void add_loop_exit (int lp)
Definition at line 784 of file optimize.c.
Referenced by optimize().
add_loop_preheader()
void add_loop_preheader (int lp)
Definition at line 620 of file optimize.c.
References add_pred(), add_succ(), assert, dump_node(), dump_region(), FG_DOM, FG_LNEXT, FG_LOOP, FG_LPREV, FG_NEXT, FG_PRED, FG_STDFIRST, FG_STDLAST, FG_SUCC, FG_TO_BIH, gbl, getlab(), i, label, lp, LP_FG, LP_HEAD, LP_PARENT, opt, OPTDBG, p, OPT::pre_fg, prev, PSI_FT, PSI_NEXT, PSI_NODE, PSI_P_NULL, q, replace_label(), STD_LABEL, STD_NEXT, STD_PREV, and void().
Referenced by add_loop_hd(), mk_loop_hdtl(), optimize(), and reassociate().
add_new_uses()
void add_new_uses (int loop, int where, int newilt, int expr)
Add use items for optimizable variables which occur in the ili expression which is a new expression being added to a flowgraph node (where) such as the preheader of the loop.
This is necessary to track new uses of a variable added after the flow information has been created. For example, it's important that the induction process adds uses in the loop count value used by a bla instruction since this expression was not seen by the flow analysis; a later call to induction will not find all of an induction variable's uses if it was used in the bla count of a contained loop.
Along with creating new uses, the du's of the defs reaching the uses are updated.
WARNING: this will only work when the expression is stored into an optimizer created temporary; to be more general (i.e., when adding stores of user-variables), new def information will have to be added which is impossible since the size of each bit vector cannot be increased.
Definition at line 3452 of file flow.c.
References cur_fg, cur_lp, cur_std, first_use, gbl, new_du_ud(), new_ud(), num_uses, opt, OPTDBG, and use_hash_reset().
add_pred()
PSI_P add_pred (int fgx, int i)
Definition at line 1387 of file fgraph.c.
References assert, fg, fgx, GET_PSI, i, opt, p, PSI_ALL, PSI_NEXT, PSI_NODE, and PSI_P_NULL.
Referenced by add_loop_preheader(), add_single_loop_exit(), and dfs().
add_single_loop_exit()
void add_single_loop_exit (int lp)
Definition at line 790 of file optimize.c.
References add_fg(), add_pred(), add_stmt_after(), add_succ(), add_to_parent(), assert, ast, fg, FG_FT, FG_LABEL, FG_LINENO, FG_LOOP, FG_NEXT, FG_SUCC, FG_TO_BIH, getlab(), lp, LP_FG, LP_MEXITS, LP_PARENT, LP_TAIL, mk_label(), mk_stmt(), PSI_FT, PSI_NEXT, PSI_NODE, rdilts(), replace_label(), RFCNTI, rm_edge(), std, STD_LINENO, and wrilts().
Referenced by mk_loop_hdtl().
add_succ()
PSI_P add_succ (int fgx, int i)
Definition at line 1312 of file fgraph.c.
References add_empty_succ(), assert, fg, fgx, i, opt, p, PSI_NEXT, PSI_NODE, and PSI_P_NULL.
Referenced by add_loop_preheader(), add_single_loop_exit(), and flowgraph().
add_to_parent()
int add_to_parent (int newfg, int lp)
Parameters
newfg block to be added
lp descendant of the loop to which block is added
Definition at line 1495 of file fgraph.c.
References assert, FG_DOM, FG_LOOP, FG_NEXT, lp, LP_FG, LP_HEAD, LP_PARENT, and parent.
Referenced by add_single_loop_exit().
bv_copy()
void bv_copy (int * a, int * b, int len)
Definition at line 100 of file optutil.c.
References a, b, and len.
Referenced by dd_succ(), live_var(), live_var_end(), reaching_defs(), and uninit_var().
bv_intersect()
void bv_intersect (BV * a, BV * b, UINT len)
Definition at line 121 of file optutil.c.
References a, b, and len.
Referenced by uninit_var().
bv_intersect3()
void bv_intersect3 (BV * a, BV * b, BV * c, UINT len)
Definition at line 128 of file optutil.c.
References a, b, and len.
bv_mem()
LOGICAL bv_mem (int * a, int elem)
Definition at line 164 of file optutil.c.
References a, assert, BV_BITS, FALSE, NULL, r, TRUE, and w.
Referenced by _avail(), chkref(), def_in_out(), du_ud(), find_next_reaching_def(), find_rdef(), is_def_imp_live(), is_initialized(), is_live_in(), is_live_out(), iscall_in_path(), isptr_in_path(), new_du_ud(), and use_before_def().
bv_notequal()
LOGICAL bv_notequal (int * a, int * b, int len)
Definition at line 155 of file optutil.c.
References a, b, FALSE, len, and TRUE.
Referenced by dd_succ(), live_var(), reaching_defs(), and uninit_var().
bv_off()
void bv_off (int * a, int elem)
Definition at line 145 of file optutil.c.
References a, BV_BITS, r, and w.
Referenced by reaching_defs().
bv_print()
void bv_print (int * bv, int maxlen)
Definition at line 179 of file optutil.c.
References BV_BITS, gbl, i, j, and w.
Referenced by dd_succ(), dump_global(), new_du_ud(), and reaching_defs().
bv_set()
void bv_set (int * a, int elem)
Definition at line 135 of file optutil.c.
References a, BV_BITS, r, and w.
Referenced by add_def(), add_use(), dd_succ(), live_var_init(), reaching_defs(), and uninit_var_init().
bv_sub()
void bv_sub (int * a, int * b, int len)
Definition at line 114 of file optutil.c.
References a, b, and len.
Referenced by live_var().
bv_union()
void bv_union (int * a, int * b, int len)
Definition at line 107 of file optutil.c.
References a, b, and len.
Referenced by dd_succ(), live_var(), live_var_end(), new_du_ud(), reaching_defs(), and uninit_var().
bv_zero()
void bv_zero (int * a, int len)
Definition at line 93 of file optutil.c.
References a, and len.
Referenced by live_var(), live_var_end(), live_var_init(), new_du_ud(), reaching_defs(), uninit_var(), and uninit_var_init().
call_analyze()
void call_analyze (void)
Definition at line 3865 of file rest.c.
References ast, check_region(), f90_fini_pointsto(), flg, freearea(), gbl, init_region(), pure_gbl::local_mode, NULL, FLG::opt, points_to(), set_descriptor_sc(), std, STD_AST, STD_LINENO, STD_LOCAL, STD_NEXT, STD_PURE, TEMP_AREA, templist, transform_all_call(), and XBIT.
can_copy_def()
LOGICAL can_copy_def (int def, int fgx, LOGICAL begin)
Definition at line 699 of file optutil.c.
References assert, avail_expr(), basesym_of(), BIH_ILTFIRST, BIH_ILTLAST, def, DEF_CONST, DEF_DOINIT, DEF_FG, DEF_NM, def_ok(), DEF_RHS, DEF_STD, FALSE, FG_STDLAST, FG_TO_BIH, fgx, gbl, getprint(), OPTDBG, srch_ae, TRUE, and XBIT.
Referenced by cp_loop(), and find_bivs().
compute_last_values()
void compute_last_values (int exit, int prehdr)
Definition at line 1460 of file induc.c.
convert_output()
void convert_output (void)
Definition at line 91 of file outconv.c.
References FTB::base, collapse_allocates(), collapse_arrays(), comm_fini(), convert_simple(), convert_statements(), convert_template_instance(), eliminate_barrier(), end_collapse(), flg, FORALL_AREA, FREE, free_brtbl(), freearea(), ftb, init_collapse(), FLG::opt, transform_wrapup(), TRUE, and XBIT.
copy_to_loop()
int copy_to_loop (int tree, int lp)
Definition at line 1702 of file optutil.c.
References ast_traverse(), ast_unvisit(), ast_visit(), collect_loads(), copyb, cp_loop(), dbg_print_ast(), FALSE, gbl, i, lp, NULL, OPT_ALLOC, OPT_FREE, OPTDBG, and TRUE.
dast()
void dast (int astx)
Definition at line 717 of file dump.c.
References A_ARGCNTG, A_ARGCNTP, A_MEM_ORDERG, A_MEM_ORDERP, A_OPTYPEG, A_OPTYPEP, A_ORDEREDG, A_ORDEREDP, A_SCHED_TYPEG, A_SCHED_TYPEP, A_TKNG, A_TKNP, args, ARGT_ARG, ASD_NDIM, ASD_SUBS, astb, BCOPY, COMSTR, dastli(), dfile, gbl, j, ASTB::ptr0, ASTB::ptr0c, ASTB::ptr1, put2int1(), putasttype(), putbit(), putdtype(), putint(), putline(), putnzint(), putoptype(), putstring1(), and putsym().
Referenced by dastreex(), do_distbegin(), dumpasts(), semant3(), set_descr_tag(), and temp_type_descriptor().
dastree()
void dastree (int astx)
Definition at line 1706 of file dump.c.
References dastreex(), dfile, gbl, longlines, and prefix.
Referenced by dstdtree().
def_ok()
LOGICAL def_ok (int def, int fgx, int stmt)
Definition at line 748 of file optutil.c.
References assert, basesym_of(), BIH_CS, def, DEF_DOINIT, DEF_FG, DEF_NM, DEF_SELF, DEF_STD, FALSE, FG_IN, FG_TO_BIH, fgx, gbl, getprint(), is_call_in_path(), is_call_safe(), is_dominator(), is_ptr_in_path(), is_sym_entry_live(), is_sym_ptrsafe(), NME_SYM, NULL, OPTDBG, STD_EX, STD_PREV, stmt, TRUE, and XBIT.
Referenced by can_copy_def(), only_one_ud(), and single_ud().
delete_fg()
void delete_fg (int fgx)
Definition at line 1301 of file fgraph.c.
References FG_LNEXT, FG_LPREV, and fgx.
delete_stores()
void delete_stores (void)
Mark stores as deletable only if its uses follow the definition in the same block.
In the future, we'll get rid of defs for which there are no uses – but before we do this, we need to determine the side effects of eliminating a def (and ilt) from a block.
Definition at line 3091 of file flow.c.
References def, DEF_DELETE, DEF_DU, DEF_FG, DEF_NM, DEF_STD, FALSE, FG_CS, FG_LABEL, FIRST_DEF, flg, gbl, getprint(), i, IS_PRIVATE, is_sym_imp_live(), OPT::ndefs, NME_SYM, NME_TYPE, NT_VAR, NULL, opt, OPTDBG, FLG::smp, STD_AST, STD_EX, STD_LINENO, unlnkilt(), and XBIT.
Referenced by optimize().
delilt()
void delilt (int stdx)
Delete an ilt from a block which is "read" and reuse it.
Definition at line 1769 of file fgraph.c.
dmpilt()
void dmpilt (int bihx)
Dump ILT to global debug file.
Synonym to dump_ilt() with gbl.dbgfil as the file argument
Parameters
bihx - BIH number
Definition at line 1775 of file fgraph.c.
dsa()
void dsa (void)
Definition at line 4210 of file dump.c.
dstda()
void dstda (void)
Definition at line 2417 of file dump.c.
References dstds().
Referenced by reassociate(), and transform().
dstdp()
void dstdp (int stdx)
Definition at line 2318 of file dump.c.
References dstd(), putstdassigns(), putstdpta(), and stdx.
Referenced by dstdps(), and points_to().
dstdpa()
void dstdpa (void)
Definition at line 2423 of file dump.c.
References dstdps(), putstdassigns(), and putstdpta().
Referenced by pstride_analysis(), and transform().
dsym()
void dsym (int sptr)
Definition at line 2684 of file dump.c.
dump_flowgraph()
void dump_flowgraph (void)
Definition at line 1781 of file fgraph.c.
References OPT::dfn, dump_node(), EDGE_PRED, EDGE_SUCC, FG_DFN, FG_STDFIRST, gbl, getprint(), i, OPT::num_nodes, opt, STD_LABEL, and VTX_NODE.
Referenced by collapse_arrays(), comm_optimize_post(), comm_optimize_pre(), flow(), hlopt_init(), optimize(), and optimize_alloc().
dump_node()
void dump_node (int v)
Definition at line 1604 of file fgraph.c.
References _dump_node(), and gbl.
Referenced by add_loop_preheader(), dmpilt(), dump_flowgraph(), and rm_edge().
dumpdtypes()
void dumpdtypes (void)
Definition at line 4376 of file dump.c.
end_loop_count()
void end_loop_count (void)
Definition at line 1469 of file induc.c.
References OPT::cnt, OPT::cntlp, DEF_NM, freearea(), i, IND_NM, INDUC::indb, induc, IUSE_AREA, mark_defb, mark_useb, NME_DEF, NME_RFPTR, opt, Q_AREA, and INDUC::stg_avail.
Referenced by get_loopcounts(), and induction().
f90_fini_pointsto()
void f90_fini_pointsto (void)
Definition at line 2962 of file pointsto.c.
References NULL, STD_NEXT, stdx, and STG_DELETE.
Referenced by call_analyze(), convert_forall(), pstride_analysis(), and transform().
find_rdef()
int find_rdef (int nme, int fgx, LOGICAL begin)
Definition at line 481 of file optutil.c.
References bv_mem(), def, DEF_NEXT, FG_IN, FG_OUT, fgx, is_optsym(), NME_DEF, and NULL.
Referenced by cp_loop(), and find_bivs().
findlooptopsort()
void findlooptopsort (void)
findlooptopsort builds loops and adds the FG nodes to the loop in topological order, top-down.
...
Definition at line 428 of file findloop.c.
References findloop(), HLOPT_ALL, and lp_topsort.
Referenced by sectfloat().
fini_points_to_all()
void fini_points_to_all (void)
Definition at line 4121 of file pointsto.c.
References gdyn, gpsd, gpte, and STG_DELETE.
fini_pstride_analysis()
void fini_pstride_analysis (void)
Definition at line 497 of file pstride.c.
References fist, fistlist, and OPT_FREE.
flow()
void flow (void)
Definition at line 256 of file flow.c.
References dilttg::bih, const_prop(), create_nmes(), FLG::dbg, DBGBIT, dilt_l, DLT_AREA, dmpilt(), do_lv, do_unv, DU_AREA, du_ud(), dump_flowgraph(), dump_global(), dump_loops(), FALSE, FG_ALL, FG_FDEF, FG_IN, FG_LABEL, FG_LNEXT, FG_OUT, FG_XT, findloop(), flg, flow_end(), flow_init(), flowgraph(), freearea(), gbl, getprint(), HLOPT_ALL, i, dilttg::ilt, interr(), jumps_deleted, live_var(), live_var_end(), live_var_init(), local_again, localflow(), LP_CS, LP_CSECT, LP_EXT_STORE, LP_MASTER, LP_PARREGN, LP_PARSECT, LP_PTR_LOAD, LP_PTR_STORE, LP_QJSR, LP_STL, LP_STL_PAR, dilttg::next, OPT::nloops, NME_STL, nmeb, NULL, OPT::num_nodes, FLG::opt, opt, OPTDBG, PSI_AREA, reaching_defs(), STL_AREA, TRUE, uninit_var(), uninit_var_end(), uninit_var_init(), unlnkilt(), and XBIT.
Referenced by comm_optimize_post(), comm_optimize_pre(), early_flow_init(), hlopt_init(), optimize(), optimize_alloc(), and sectfloat().
flow_end()
void flow_end (void)
Cleanup up structures created by flow analysis and after a function has been optimized.
Definition at line 427 of file flow.c.
References DEF_NM, OPT::def_setb, do_lv, FIRST_DEF, FREE, interr(), lv, OPT::ndefs, SET_BASE::nme_base, NME_DEF, nmeb, opt, SET_BASE::stg_base, and use_hash_free().
Referenced by flow(), optimize(), and optshrd_fend().
flowgraph()
void flowgraph (void)
Definition at line 62 of file fgraph.c.
References A_ARGCNTG, add_empty_succ(), add_succ(), append_succ(), argt, ARGT_ARG, assert, assigned_labels, ast, ASTLI_AST, ASTLI_NEXT, cmp64(), cnt, CNTL_AST, CNTL_ENDL, CNTL_TOPFG, CONVAL2G, dominators(), DTY, FALSE, FG_EN, FG_FT, FG_LABEL, FG_LINENO, FG_LNEXT, FG_LPREV, FG_STDFIRST, FG_STDLAST, FG_XT, fgx, fillin_succ(), FLANG_FALLTHROUGH, freearea(), gbl, getitem(), getprint(), i, Q_TAG::info, m2, Q_TAG::next, NOSYM, NULL, OPT::num_nodes, opt, OPT_ALLOC, OPT_FREE, OPTDBG, partition_blocks(), POP_CNTL, PSI_FT, PSI_ZTRP, PUSH_CNTL, q, Q_AREA, set_std_fg(), STD_AST, STD_BR, STD_LABEL, stdx, stg_avail, stg_base, stg_size, top, TRUE, TY_BINT, TY_BLOG, TY_DBLE, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_REAL, TY_SINT, TY_SLOG, and void().
Referenced by comm_optimize_post(), comm_optimize_pre(), early_flow_init(), flow(), hlopt_init(), init_points_to_prop(), optimize(), optimize_alloc(), redundss(), and sectfloat().
get_loop_count()
int get_loop_count (int lp)
Definition at line 1420 of file induc.c.
References BIH_LABEL, call_in_loop, FALSE, find_bivs(), gbl, getprint(), ind_loop_init(), loop_cnt, lp, LP_CALLFG, LP_XTNDRNG, lpx, new_ivs(), OPTDBG, and XBIT.
Referenced by get_loopcounts(), and induction().
get_otemp()
int get_otemp (void)
hlopt_end()
void hlopt_end (int hlopt_bv, int gbc)
Definition at line 187 of file optimize.c.
References HLOPT_INDUC, induction_end(), optshrd_end(), and optshrd_fend().
Referenced by collapse_arrays(), and comm_invar().
hlopt_init()
void hlopt_init (int hlopt_bv)
Definition at line 159 of file optimize.c.
References DBGBIT, dump_flowgraph(), dump_loops(), findloop(), flow(), flowgraph(), HLOPT_INDUC, induction_init(), optshrd_finit(), and optshrd_init().
Referenced by collapse_arrays(), and comm_invar().
hoist_stmt()
void hoist_stmt (int std, int fg, int l)
Definition at line 5794 of file outconv.c.
References is_dealloc_std(), LP_MEXITS, sdrop_stmt(), sfloat_stmt2(), std, and STD_FG.
Referenced by invar_motion(), and is_hoistable().
idsym()
int idsym (int cls, int id)
induction()
void induction (int lp)
Definition at line 183 of file induc.c.
References dbg_print_ast(), end_loop_count(), gbl, get_loop_count(), loop_cnt, lp, OPTDBG, and void().
Referenced by optimize().
induction_end()
void induction_end (void)
Definition at line 166 of file induc.c.
References INDUC::indb, induc, and OPT_FREE.
Referenced by comm_optimize_end(), hlopt_end(), optimize_end(), and sectfloat().
induction_init()
void induction_init (void)
Definition at line 157 of file induc.c.
References INDUC::indb, induc, INDUC::mark_du, NULL, and OPT_ALLOC.
Referenced by comm_optimize_init(), hlopt_init(), optimize_init(), and sectfloat().
invariant()
void invariant (int lp)
Definition at line 77 of file invar.c.
References FG_LNEXT, FG_STDFIRST, FG_STDLAST, fgx, flg, invar_end(), invar_init(), invar_mark(), invar_motion(), lp, LP_CS, LP_DSTDF, LP_HEAD, LP_HSTDF, LP_MEXITS, LP_PARLOOP, LP_TAIL, FLG::opt, STD_ACCEL, STD_KERNEL, STD_NEXT, stdx, and XBIT.
Referenced by optimize().
invariant_mark()
void invariant_mark (int ilix, int mark)
Definition at line 127 of file invar.c.
References AST_INVP, i, mark(), opt, and OPT_NEED.
Referenced by compute_invariant(), and hoist_std().
invariant_nomotion()
void invariant_nomotion (int lp)
Definition at line 116 of file invar.c.
References invar_end(), invar_init(), invar_mark(), and lp.
Referenced by get_loopcounts(), and hoist_loop().
invariant_unmark()
void invariant_unmark (void)
Definition at line 143 of file invar.c.
References AST_INVP, AST_ISINV_TEMP, cleannames(), i, LP_STL, lpx, and opt.
invariant_unmarkv()
void invariant_unmarkv (void)
Definition at line 165 of file invar.c.
References AST_INVP, cleannames(), i, LP_STL, lpx, and opt.
Referenced by get_loopcounts(), and hoist_loop().
IPA_arg_alloc()
int IPA_arg_alloc (int funcsptr, int argnum)
ipa_closefile()
void ipa_closefile (void)
Definition at line 1490 of file main.c.
Referenced by finish().
ipa_fini()
void ipa_fini (void)
Definition at line 1510 of file main.c.
Referenced by finish().
IPA_func_argalloc_safe()
int IPA_func_argalloc_safe (int sptr)
IPA_func_globalalloc_safe()
int IPA_func_globalalloc_safe (int sptr)
IPA_isnoconflict()
int IPA_isnoconflict (int sptr)
Definition at line 1514 of file main.c.
ipa_mfilename()
void ipa_mfilename (char * name)
IPA_noconflict()
int IPA_noconflict (int sptr)
IPA_pstride()
long IPA_pstride (int sptr)
Definition at line 6230 of file upper.cpp.
ipa_restore_all()
void ipa_restore_all (void)
ipa_restore_back()
void ipa_restore_back (void)
ipa_return_in_argument()
int ipa_return_in_argument (int func)
IPA_safe()
int IPA_safe (int sptr)
Definition at line 6282 of file upper.cpp.
References findindex(), i, INFO_SAFE, IPA_Safe_Globals_Confirmed, IPNDX_INFO, IPNFO_NEXT, IPNFO_TYPE, n, sptr, and XBIT.
IPA_sstride()
long IPA_sstride (int sptr)
Definition at line 6251 of file upper.cpp.
ipasave()
void ipasave (void)
Definition at line 1508 of file main.c.
ipasave_closefile()
void ipasave_closefile (void)
Definition at line 1504 of file main.c.
Referenced by finish().
ipasave_compname()
void ipasave_compname (char * , int , char **)
ipasave_compsw()
void ipasave_compsw (char *)
ipasave_fini()
void ipasave_fini (void)
Definition at line 1507 of file main.c.
Referenced by finish().
ipasave_mfilename()
void ipasave_mfilename (char *)
is_avail_expr()
LOGICAL is_avail_expr (int expr, int start_ilt, int start_fg, int end_ilt, int end_fg)
Definition at line 883 of file optutil.c.
References avail_expr(), FALSE, gbl, OPTDBG, srch_ae, and TRUE.
Referenced by eliminate_bnds(), eliminate_gather(), eliminate_get_scalar(), eliminate_shift(), eliminate_start(), is_avail_expr_with_list(), is_same_array_bounds(), is_same_def(), only_one_ud(), same_forall_bnds(), same_forall_size(), and single_ud().
is_call_in_path()
LOGICAL is_call_in_path (int start_ilt, int start_fg, int end_ilt, int end_fg)
Definition at line 1362 of file optutil.c.
References iscall_in_path(), and srch_ae.
Referenced by def_ok().
is_call_safe()
LOGICAL is_call_safe (int nme)
Definition at line 358 of file optutil.c.
References FALSE, gbl, IS_CMNBLK, NME_SYM, and TRUE.
Referenced by _avail(), and def_ok().
is_def_imp_live()
LOGICAL is_def_imp_live (int def)
Definition at line 1560 of file optutil.c.
References assert, bv_mem(), def, DEF_NM, OPT::exitfg, FALSE, FG_IN, gbl, is_sym_exit_live(), NME_SYM, NULL, opt, OPTDBG, TRUE, and XBIT.
Referenced by rm_def_rloop().
is_invariant()
LOGICAL is_invariant (int ilix)
Definition at line 331 of file invar.c.
References gbl, invar_src(), and OPTDBG.
Referenced by has_invar_subs(), hoist_std(), is_invariant_base(), and is_invariant_list().
is_live_in()
LOGICAL is_live_in (int nme, int lp)
Utility functions to determine if a variable is live-in to a loop and live-out of a loop.
NOTE: conservative estimates currently in place for a variable which is unsafe (e.g., addrtkn, equivalenced, etc.); for addrtkn, more precise information involves checking arguments in bld_ud() and analyzing right- hand sides of assignments for acons. Similarly, conservative estimates for a static or external variable with respect to calls in the function.
Definition at line 2152 of file flow.c.
References bv_mem(), is_optsym(), is_sym_live_safe(), lp, LP_LIN, lv, TRUE, and XBIT.
Referenced by sfloat().
is_live_out()
LOGICAL is_live_out (int nme, int lp)
Definition at line 2164 of file flow.c.
References bv_mem(), is_optsym(), is_sym_live_safe(), lp, LP_LOUT, lv, TRUE, and XBIT.
Referenced by optimize(), and sfloat().
is_optsym()
LOGICAL is_optsym (int nme)
Definition at line 206 of file optutil.c.
References FALSE, NME_TYPE, NT_VAR, and TRUE.
Referenced by _avail(), collect_loads(), copy_const(), find_rdef(), is_initialized(), is_live_in(), is_live_out(), live_var_init(), and uninit_var_init().
is_ptr_in_path()
LOGICAL is_ptr_in_path (int start_ilt, int start_fg, int end_ilt, int end_fg)
Definition at line 1464 of file optutil.c.
References isptr_in_path(), and srch_ae.
Referenced by def_ok().
is_ptr_safe()
LOGICAL is_ptr_safe (int nme)
Definition at line 399 of file optutil.c.
References assert, basesym_of(), FALSE, NME_TYPE, NT_IND, NT_MEM, NT_VAR, TRUE, and XBIT.
Referenced by add_store(), bld_lhs(), chk_ptr_load(), is_store_via_ptr(), resolve_pp(), and resolve_pv().
is_store_via_ptr()
LOGICAL is_store_via_ptr (int astx)
Definition at line 638 of file optutil.c.
References FALSE, is_ptr_safe(), NME_NM, NME_SYM, NME_TYPE, NT_ARR, NT_IND, NT_MEM, NT_VAR, and TRUE.
Referenced by isptr_in_path().
is_sym_entry_live()
LOGICAL is_sym_entry_live (int nme)
Definition at line 607 of file optutil.c.
References assert, FALSE, INTENT_OUT, INTENTG, IS_DUM, IS_EXTERN, IS_STATIC, NME_SYM, nmeb, s, stb, and TRUE.
Referenced by def_ok(), live_var_init(), and uninit_var_init().
is_sym_exit_live()
LOGICAL is_sym_exit_live (int nme)
Definition at line 522 of file optutil.c.
References assert, FALSE, gbl, INTENT_IN, INTENTG, IS_DUM, IS_EXTERN, IS_STATIC, NME_SYM, nmeb, RU_PROG, s, stb, and TRUE.
Referenced by check_alias(), is_def_imp_live(), is_sym_imp_live(), live_var_init(), and uninit_var_init().
is_sym_imp_live()
LOGICAL is_sym_imp_live (int nme)
Definition at line 572 of file optutil.c.
References assert, FALSE, is_sym_exit_live(), NME_SYM, nmeb, TRUE, and XBIT.
Referenced by const_prop(), delete_stores(), and ind_loop_init().
is_sym_invariant_safe()
LOGICAL is_sym_invariant_safe (int nme, int lpx)
Definition at line 959 of file invar.c.
References FALSE, IS_LCL_OR_DUM, IS_PRIVATE, is_sym_ptrsafe(), LP_CALLFG, LP_CALLINTERNAL, LP_CSECT, LP_PARREGN, LP_PARSECT, LP_PTR_STORE, LP_STL_PAR, lpx, NME_SYM, NULL, q, and TRUE.
Referenced by compute_invariant(), and hoist_std().
is_sym_live_safe()
LOGICAL is_sym_live_safe (int nme, int lpx)
Definition at line 281 of file optutil.c.
References FALSE, IS_LCL_OR_DUM, IS_PRIVATE, is_sym_ptrsafe(), LP_CALLFG, LP_CSECT, LP_PARLOOP, LP_PARREGN, LP_PARSECT, LP_PTR_LOAD, LP_PTR_STORE, LP_STL_PAR, lpx, LPZ, NME_SYM, NULL, q, TRUE, and XBIT.
Referenced by is_live_in(), and is_live_out().
is_sym_optsafe()
LOGICAL is_sym_optsafe (int nme, int lpx)
Definition at line 214 of file optutil.c.
References FALSE, IS_LCL_OR_DUM, IS_PRIVATE, is_sym_ptrsafe(), LP_CALLFG, LP_CSECT, LP_PARLOOP, LP_PARREGN, LP_PARSECT, LP_PTR_LOAD, LP_PTR_STORE, LP_STL_PAR, lpx, NME_SYM, NULL, q, TRUE, and XBIT.
Referenced by check_alias(), ind_loop_init(), and resolve_pv().
is_sym_ptrsafe()
LOGICAL is_sym_ptrsafe (int sym)
Definition at line 435 of file optutil.c.
References FLG::depchk, FALSE, flg, TRUE, and XBIT.
Referenced by def_ok(), get_lhs_first_defs(), is_sym_invariant_safe(), is_sym_live_safe(), and is_sym_optsafe().
lhs_needtmp()
LOGICAL lhs_needtmp (int lhs, int rhs, int stmt)
Definition at line 2847 of file optutil.c.
References alldefs_allocsafe(), def, DEF_STD, FALSE, fgx, find_lhs_on_rhs_conflict(), find_next_reaching_def(), find_rhs_conflict(), get_lhs_first_defs(), lhs, lhscount, nme_of_ast(), result, std, STD_FG, stmt, and TRUE.
Referenced by forall_dependency().
linearize_arrays()
void linearize_arrays (void)
Definition at line 5484 of file outconv.c.
References _linearize_all(), _linearize_func(), _linearize_sub(), ast, ast_rewrite(), ast_traverse(), ast_unvisit(), ast_visit(), deferred_to_pointer(), dummy, FALSE, linearize_any, NULL, std, STD_AST, and STD_NEXT.
only_one_ud()
LOGICAL only_one_ud (int use)
Definition at line 1517 of file optutil.c.
References assert, basesym_of(), def, UD_TAG::def, DEF_DU, DEF_FG, def_ok(), DEF_SELF, DEF_STD, FALSE, gbl, getprint(), is_avail_expr(), UD_TAG::next, DU_TAG::next, NULL, opt, OPTDBG, t, use, DU_TAG::use, USE_AST, USE_FG, USE_NM, USE_STD, and USE_UD.
optimize()
void optimize (int whichpass)
Definition at line 327 of file optimize.c.
References add_arrnme(), add_loop_exit(), add_loop_preheader(), ast, br_to_br(), close_pragma(), DBGBIT, delete_stores(), dmpnme(), dump_flowgraph(), dump_loops(), dump_std(), OPT::exit_fg, OPT::exitfg, FALSE, fg, FG_HEAD, FG_INNERMOST, FG_LINENO, FG_LPREV, FG_MEXITS, FG_NEXT, FG_STDFIRST, FG_STDLAST, FG_TAIL, findloop(), flg, flow(), flow_end(), flowgraph(), function_end(), function_init(), gbl, HLOPT_ALL, i, induction(), invariant(), is_live_out(), loop_init(), LP_FG, LP_HEAD, LP_INNERMOST, LP_LOOP, LP_MEXITS, LP_PARLOOP, LP_TAIL, lpx, merge_blocks(), NEW_NODE, OPT::nloops, no_functions(), NT_VAR, open_pragma(), opt, OPTDBG, optimize_end(), optimize_init(), OPT::pre_fg, remove_loop(), OPT::sc, SC_AUTO, std, STD_AST, STD_NEXT, use_before_def(), FLG::x, and XBIT.
optimize_alloc()
void optimize_alloc (void)
Try to optimize allocate statements.
If they have same bounds, give them the same bound variable. This will help the compiler to reduce # of communication for allocatable variables.
Definition at line 2877 of file commopt.c.
References comm_optimize_end(), comm_optimize_init(), DBGBIT, dump_flowgraph(), dump_loops(), findloop(), flow(), flowgraph(), HLOPT_ALL, opt_allocate(), and postdominators().
optshrd_end()
void optshrd_end (void)
Definition at line 137 of file optimize.c.
References astb, nme_end(), opt, STG_DELETE, and STG_DELETE_SIDECAR.
Referenced by comm_optimize_end(), Done(), early_flow_fini(), fini_points_to_prop(), hlopt_end(), optimize_end(), and sectfloat().
optshrd_fend()
void optshrd_fend (void)
Definition at line 126 of file optimize.c.
References DU_AREA, flow_end(), freearea(), PSI_AREA, and STL_AREA.
Referenced by comm_optimize_end(), early_flow_fini(), function_end(), hlopt_end(), and sectfloat().
optshrd_finit()
void optshrd_finit (void)
Definition at line 120 of file optimize.c.
Referenced by comm_optimize_init(), function_init(), hlopt_init(), and sectfloat().
optshrd_init()
void optshrd_init (void)
Definition at line 92 of file optimize.c.
References astb, gbl, LP_PARENT, nme_init(), opt, OPT::sc, SC_AUTO, STG_ALLOC, and STG_ALLOC_SIDECAR.
Referenced by comm_optimize_init(), early_flow_init(), hlopt_init(), init_points_to_prop(), optimize_init(), redundss(), and sectfloat().
past()
void past (int astx)
Definition at line 1723 of file dump.c.
References dfile, gbl, and printast().
Referenced by build_array_list(), canonical_conversion(), check_alloc_ptr_type(), check_pointer_type(), do_distbegin(), forall_make_same_idx(), and put_forall_pcalls().
points_to()
void points_to (void)
Do dataflow analysis to determine pointer target information store pointer target information at loads and stores.
build flow graph
build reverse depth-first ordering
build pseudo-assignments to represent pointer modifications
use data-flow analysis to propagate pointer information around flow graph
modify the ILI/NME to represent the propagated information
For F90.
Definition at line 4199 of file pointsto.c.
References AS_INIT, ASNEXT, ASTYPE, BZERO, check_pte(), copy_list(), DBGBIT, dstdp(), dstdps(), ERR_Fatal, f90_init(), FG_STDFIRST, FG_STDLAST, FG_SUCC, FG_TO_BIH, fini_points_to_prop(), FIRSTAS, free_list_slot(), gbl, gcount, get_pte(), gpsd, HEAD, init_points_to_prop(), interpret(), interr(), is_source_nonlocal(), iteration, LHEAD, localhead, NEW, nmeb, nodeoffset, OPT::num_nodes, offset, opt, PSD_SLOT, PSI_NEXT, PSI_NODE, PSI_P_NULL, pte_changed(), putstdpta(), puttargets(), r, RDFO, rdfocount, RDFONUM, s, set_std_pta(), SLOT, STD_NEXT, STD_PREV, stdx, STG_ALLOC, TPTE_NULL, TPTE_UNINIT, Trace, TRACEBIT, TRACEFLAG, TT_NLOC, and TTE_NULL.
Referenced by call_analyze(), convert_forall(), pstride_analysis(), and transform().
points_to_anal()
void points_to_anal (void)
Definition at line 4137 of file pointsto.c.
References a, add_psd(), ASNEXT, DBGBIT, find_pointer_assignments_f90(), fini_points_to_anal(), FIRSTAS, gbl, gpsd, init_points_to_anal(), nmeb, NULL, OPT::num_nodes, opt, putassign(), STD_NEXT, stdx, Trace, TRACEBIT, TRACEFLAG, and TT_GLOB.
postdominators()
void postdominators (void)
Definition at line 1082 of file fgraph.c.
References BUCKET, dom, dom_link, DOM_NEW, eval(), FG_DFN, FG_PDOM, FG_SUCC, FG_XT, FREE, FREE_BUCKET_AREA, GET_BUCKET, i, OPT::num_nodes, opt, p, PARENT, PSI_NEXT, PSI_NODE, PSI_P_NULL, rdfn, rdfs(), RVTX_NODE, SEMI, and w.
Referenced by optimize_alloc(), and sectfloat().
pred_of_loop()
int pred_of_loop (int lpx)
Definition at line 453 of file optutil.c.
References FG_LOOP, FG_PRED, fgx, LP_HEAD, lpx, pred, PSI_NEXT, PSI_NODE, and PSI_P_NULL.
Referenced by find_bivs().
pstride_analysis()
void pstride_analysis (void)
Definition at line 348 of file pstride.c.
References _findrefs(), ast_traverse(), ast_unvisit(), ast_visit(), count, DBGBIT, dfile, dstdpa(), dsym(), f90_fini_pointsto(), first, STB::firstosym, fist, FIST_GDYN, FIST_ID, FIST_ISYM, FIST_LDYN, FIST_NEXT, FIST_NLOC, FIST_PSYM, FIST_TYPE, FIST_UNK, fistlist, INFO::fistptr, FLIST_PTR, FLIST_SPTR, FREE, gbl, info, NEW, INFO::next, NULL, OPT_ALLOC, points_to(), SEEN_NON_QALN, SEEN_NON_STRIDE1, SEEN_QALN, SEEN_STRIDE1, SEEN_TARGET, SEEN_UNK_TARGET, sptr, stb, STD_AST, STD_NEXT, stdx, SYMNAME, t, and XBIT.
pta_stride1()
bool pta_stride1 (int ptrstdx, int ptrsptr)
Definition at line 3847 of file pointsto.c.
putstdassigns()
void putstdassigns (int stdx)
Definition at line 689 of file pointsto.c.
References a, ASNEXT, FIRSTAS, putassign(), and stdx.
Referenced by dstdp(), and dstdpa().
putstdpta()
void putstdpta (int stdx)
Definition at line 3150 of file pointsto.c.
References dfile, FPSRC_NEXT, FPSRC_PTELIST, FPTE_NEXT, gbl, putfpte(), putsrc(), and stdx.
Referenced by analyze(), dstdp(), dstdpa(), and points_to().
rdilts()
void rdilts (int bihx)
'read' a flowgraph node.
This defines the 0th STD entry to locate the beginning and end STDs of the node. The STD state (values of the STDs in the 0th entry and the beginning and last STDs of the flowgraph node) is saved. After a node has been read, its STD list has the following properties:
the list is terminated by 0.
STD_NEXT(0) locates the first STD in the list.
STD_PREV(0) locates the last STD in the list.
'read' a flowgraph node.
"Read" in the block specified by bihx. the 0th entry in the ILT area (next and prev) are set to the first and last ilts respectively
Definition at line 1636 of file fgraph.c.
redundss()
void redundss (void)
Definition at line 1677 of file redundss.c.
References basic_block_redundant(), DBGBIT, Done(), dumpfgraph(), dumploops(), findloop(), flowgraph(), gany, gbl, HLOPT_ALL, Init(), NULL, optshrd_init(), reassociate(), reorder_dfn_loops(), Trace, and XBIT.
reorderloops()
void reorderloops ()
...
Definition at line 1227 of file findloop.c.
References addloop(), ERR_Severe, interr(), LP_CHILD, LP_SIBLING, n, OPT::nloops, and opt.
Referenced by sectfloat().
rm_def_rloop()
void rm_def_rloop (int def, int lpx)
Definition at line 1619 of file optutil.c.
References assert, count, def, DEF_DELETE, DEF_DU, DEF_FG, DEF_STD, FALSE, FG_LOOP, FG_TO_BIH, gbl, i, is_def_imp_live(), lpx, DU_TAG::next, NULL, opt, OPTDBG, STD_DELETE, STD_PREV, unlnkilt(), use, DU_TAG::use, USE_FG, and USE_STD.
rm_edge()
void rm_edge (int fg1, int fg2)
Remove the edge fg1 -> fg2 from the flowgraph.
remove fg2 from succ(fg1)
remove fg1 from pred(fg2)
Definition at line 1413 of file fgraph.c.
References assert, dump_node(), FG_LNEXT, FG_LOOP, FG_LPREV, FG_NEXT, FG_PRED, FG_SUCC, FG_XT, gbl, i, j, lp, LP_FG, OPTDBG, p, prev, PSI_NEXT, PSI_NODE, PSI_P_NULL, and rm_edge().
Referenced by add_single_loop_exit(), and rm_edge().
sectfloat()
void sectfloat (void)
Definition at line 6147 of file outconv.c.
References astb, BZERO, d, DBGBIT, DEF_NEXT, DEF_STD, dom, dumpdefs(), dumpfgraph(), dumploops(), dumpnmes(), dumpuses(), fg, FG_CTLEQUIV, FG_DOM, FG_LOOP, FG_PDOM, findlooptopsort(), STB::firstusym, flg, flow(), flowgraph(), FREE, induction_end(), induction_init(), is_dominator(), is_post_dominator(), loopdeflist, LP_CHILD, LP_HEAD, LP_SIBLING, NEW, OPT::nloops, NME_DEF, nmeb, OPT::num_nodes, opt, optshrd_end(), optshrd_fend(), optshrd_finit(), optshrd_init(), postdominators(), reorderloops(), s, sfloat(), stb, std, stddeflist, syminfo, and FLG::x.
sectinline()
void sectinline (void)
Definition at line 2503 of file outconv.c.
References _ptrassign(), _sect(), _template(), A_OPTYPEG, ast, ast_to_comment(), beforestd, FALSE, FTYPE_I8, FTYPE_MASK, FTYPE_SECT, FTYPE_TEMPLATE, FTYPE_TEMPLATE1, FTYPE_TEMPLATE1V, FTYPE_TEMPLATE2, FTYPE_TEMPLATE2V, FTYPE_TEMPLATE3, FTYPE_TEMPLATE3V, getF90TmplSectRtn(), i, std, STD_AST, STD_NEXT, SYMNAME, and TRUE.
single_ud()
LOGICAL single_ud (int use)
Definition at line 1479 of file optutil.c.
References assert, basesym_of(), def, UD_TAG::def, DEF_FG, def_ok(), DEF_RHS, DEF_STD, FALSE, gbl, getprint(), is_avail_expr(), UD_TAG::next, NULL, opt, OPTDBG, use, USE_FG, USE_NM, USE_STD, and USE_UD.
Referenced by check_alias(), and const_prop().
unconditional_branches()
void unconditional_branches (void)
Definition at line 941 of file optimize.c.
References CONVAL2G, DT_ISLOG, FALSE, FREE, NEED, NEW, remove_block(), sptr, STD_AST, STD_FG, STD_NEXT, stdx, and TRUE.
unlnkilt()
void unlnkilt (int stdx, int fgx, LOGICAL reuse)
Parameters
stdx std to be deleted
fgx fg of block from which std is deleted (0 => read)
reuse TRUE if ilt is to be reused
Definition at line 1731 of file fgraph.c.
References add_stmt_after(), assert, FG_STDFIRST, FG_STDLAST, fgx, i, j, mk_stmt(), STD_DELETE, STD_LABEL, STD_NEXT, STD_PREV, stdx, and TRUE.
Referenced by delete_stores(), delilt(), flow(), merge_blocks(), and rm_def_rloop().
update_stl()
int update_stl (int lpx, int nme)
Utility function to add a store item to a loop's store list.
The store is added after flow analysis has taken place; this is needed if we care about considering these stores for later analysis (e.g., the store could affect later invariancy tests). The store item is returned to the caller (could be an existing one). If one is created, its type is set to zero; the caller is responsible for setting it to 1 (variable address).
Definition at line 1799 of file flow.c.
References CNULL, error(), LP_STL, lpx, opt, OPT_NEED, STL_TAG::store, STORE_NEXT, STORE_NM, and STORE_TYPE.
use_before_def()
void use_before_def (void)
Definition at line 3170 of file flow.c.
References basesym_of(), bv_mem(), UD_TAG::def, DEF_ARG, DEF_FG, DEF_NEXT, DEF_OTHER, DEF_PRECISE, df, error(), FALSE, fg, FG_IN, FG_LABEL, FG_LINENO, FG_LOOP, FG_OUT, FG_PRED, gbl, INTENT_OUT, INTENTG, LP_HEAD, UD_TAG::next, NME_DEF, NULL, opt, p, PSI_NEXT, PSI_NODE, PSI_P_NULL, SYMNAME, TRUE, use, USE_ARG, USE_EXPOSED, USE_FG, USE_NM, and USE_UD.
Referenced by optimize().
wrilts()
void wrilts (int bihx)
'write' the flowgraph node.
This restores the STD list to be a single list of all of the STDs in the function. The STD state is restored.
'write' the flowgraph node.
Write out ilts for the block denoted by bih. Various flags have already been set in bih. This routine buffers up the ilt block in the bih area.
Definition at line 1679 of file fgraph.c.
Variable Documentation
IPA_Vestigial
int IPA_Vestigial extern
Definition at line 1488 of file main.c.
opt
OPT opt extern
Definition at line 14 of file optdf.c.
Referenced by __fort_getopt(), __fort_getoptb(), __fort_getoptn(), add_def(), add_empty_succ(), add_fg(), add_loop_hd(), add_loop_preheader(), add_new_uses(), add_pred(), add_succ(), add_use(), append_succ(), bld_lhs(), br_to_br(), build_do_init(), build_rdfo(), bv_count(), check_pte(), const_prop(), dd_succ(), delete_stores(), dfs(), direct_rou_setopt(), do_branch(), dominators(), Done(), du_ud(), dump_flowgraph(), dump_global(), dump_loops(), dumpdef(), dumpdeflist(), dumpdefs(), dumpfgraph(), dumpfnode(), dumploop(), dumploops(), dumpuse(), dumpuses(), dumpvloops2(), dumpvnest2(), eliminate_rt(), end_loop_count(), fillin_succ(), find_lp(), findloop(), flow(), flow_end(), flow_init(), flowgraph(), function_init(), fuse_forall(), get_entries_argnum(), get_loopcounts(), getopt_abort(), ind_loop_init(), init_points_to_prop(), invar_init(), invariant_mark(), invariant_unmark(), invariant_unmarkv(), is_def_imp_live(), lflow_of_block(), live_var(), live_var_end(), live_var_init(), localflow(), loop_init(), merge_blocks(), mk_loop_hdtl(), mk_ztrips(), new_du_ud(), new_storeitem(), only_one_ud(), optimize(), optshrd_end(), optshrd_init(), parseargs(), partition_blocks(), points_to(), points_to_anal(), postdominators(), put_forall_fg(), putoptype(), rd_dir(), reaching_defs(), reassociate(), reorder_dfn_loops(), reorderloops(), rm_def_rloop(), sectfloat(), selection_sort(), set_std_fg(), single_ud(), sortloops(), top_sort(), uninit_var(), uninit_var_end(), uninit_var_init(), update_stl(), and use_before_def().