flang: optutil.c File Reference
optutil.c File Reference
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "semant.h"
#include "nme.h"
#include "ast.h"
#include "optimize.h"
Classes
struct ptrnmestr
Macros
#define LPZ 0
#define MAX_DEF 10
Typedefs
typedef struct ptrnmestr ptrdefstr
Functions
int basesym_of (int)
Return the base st index of the names entry.
void bv_zero (BV *a, int len)
void bv_copy (BV *a, BV *b, int len)
void bv_union (BV *a, BV *b, int len)
void bv_sub (BV *a, BV *b, int len)
void bv_intersect (BV *a, BV *b, UINT len)
void bv_intersect3 (BV *a, BV *b, BV *c, UINT len)
void bv_set (BV *a, int elem)
void bv_off (BV *a, int elem)
LOGICAL bv_notequal (BV *a, BV *b, int len)
LOGICAL bv_mem (BV *a, int elem)
void bv_print (BV *bv, int maxlen)
LOGICAL is_optsym (int nme)
LOGICAL is_sym_optsafe (int nme, int lpx)
LOGICAL is_sym_live_safe (int nme, int lpx)
LOGICAL is_call_safe (int nme)
LOGICAL is_ptr_safe (int nme)
LOGICAL is_sym_ptrsafe (int sym)
int pred_of_loop (int lpx)
int find_rdef (int nme, int fgx, LOGICAL begin)
LOGICAL is_sym_exit_live (int nme)
LOGICAL is_sym_imp_live (int nme)
LOGICAL is_sym_entry_live (int nme)
LOGICAL is_store_via_ptr (int astx)
LOGICAL def_ok (int def, int fgx, int stmt)
LOGICAL is_avail_expr (int expr, int start_ilt, int start_fg, int end_ilt, int end_fg)
static LOGICAL avail_expr (int expr)
static LOGICAL is_in_path (int fg)
static LOGICAL in_path (int cur, int fg)
static LOGICAL iscall_in_path (void)
static LOGICAL isptr_in_path (void)
static LOGICAL call_in_path (int cur)
LOGICAL can_copy_def (int def, int fgx, LOGICAL begin)
static LOGICAL _avail (int expr, LOGICAL *av_p)
LOGICAL is_call_in_path (int start_ilt, int start_fg, int end_ilt, int end_fg)
LOGICAL is_ptr_in_path (int start_ilt, int start_fg, int end_ilt, int end_fg)
LOGICAL single_ud (int use)
LOGICAL only_one_ud (int use)
LOGICAL is_def_imp_live (int def)
void rm_def_rloop (int def, int lpx)
static LOGICAL collect_loads (int, int *)
static LOGICAL cp_loop (int)
int copy_to_loop (int tree, int lp)
int find_next_reaching_def (int nme, int fgx, int def)
static int ast_grandparent (int astptr)
static int get_next_parent (int astptr, int myparent)
static LOGICAL is_parentof_ast (int astp, int astc)
int nme_of_ast (int ast)
static LOGICAL is_ptrast_arg (int ptrast, int ast)
static LOGICAL isptrdef_in_path (int nme, int ptrast)
LOGICAL is_ptrdef_in_path (int start_ilt, int start_fg, int end_ilt, int end_fg, int nme, int ast)
LOGICAL alldefs_allocsafe (int ast, int stmt)
static LOGICAL ptrdefs_has_lhsconflict (int nme, int std, int def)
static void _find_rhs_def_conflict (int ast, int *args)
static void _find_lhs_on_rhs_conflict (int ast, int *args)
static void find_rhs_conflict (int lhs, int rhs, int stmt, int allochk, int *result)
static void find_lhs_on_rhs_conflict (int lhs, int rhs, int stmt, int allochk, int *result)
int add_lhs_nme (int nme, int std, int isdummy)
static void get_lhs_first_defs (int stmt, int lhs)
LOGICAL lhs_needtmp (int lhs, int rhs, int stmt)
Variables
struct {
struct {
int stmt
int fg
} start
struct {
int stmt
int fg
} end
int eob
} srch_ae
static int visit_list
struct {
int lp
int new
int * stg_base
int stg_size
int stg_avail
} copyb
static ptrdefstr lhsdefs [MAX_DEF]
static int lhscount = 0
Macro Definition Documentation
LPZ
#define LPZ 0
MAX_DEF
#define MAX_DEF 10
Definition at line 1877 of file optutil.c.
Typedef Documentation
ptrdefstr
typedef struct ptrnmestr ptrdefstr
Function Documentation
_avail()
static LOGICAL _avail (int expr, LOGICAL * av_p) static
Definition at line 929 of file optutil.c.
References bv_mem(), d, def, DEF_DOINIT, DEF_FG, DEF_LNEXT, DEF_NEXT, DEF_NM, DEF_SELF, DEF_STD, FALSE, FG_FDEF, FG_IN, FG_OUT, FG_TO_BIH, FLANG_FALLTHROUGH, gbl, i, interr(), is_call_safe(), is_dominator(), is_in_path(), is_optsym(), iscall_in_path(), isptr_in_path(), next_def, NME_DEF, NME_SYM, NME_TYPE, NT_ARR, NT_IND, NT_MEM, NT_UNK, NT_VAR, OPTDBG, rdilts(), srch_ae, ST_ISVAR, STD_NEXT, STD_PREV, TRUE, and wrilts().
Referenced by avail_expr().
_find_lhs_on_rhs_conflict()
static void _find_lhs_on_rhs_conflict (int ast, int * args) static
Definition at line 2610 of file optutil.c.
References args, ast, basesym_of(), DDTG, DTY, is_parentof_ast(), lhs, lhscount, MAX_DEF, nme_of_ast(), and sptr.
Referenced by find_lhs_on_rhs_conflict().
_find_rhs_def_conflict()
static void _find_rhs_def_conflict (int ast, int * args) static
Definition at line 2540 of file optutil.c.
References alldefs_allocsafe(), args, ast, basesym_of(), i, lhs, lhscount, lhsdefs, MAX_DEF, nme_of_ast(), ptrdefs_has_lhsconflict(), sptr, and std.
Referenced by find_rhs_conflict().
add_lhs_nme()
int add_lhs_nme (int nme, int std, int isdummy)
Definition at line 2720 of file optutil.c.
References ptrnmestr::isdummy, lhscount, lhsdefs, MAX_DEF, ptrnmestr::nme, ptrnmestr::std, and std.
Referenced by get_lhs_first_defs().
alldefs_allocsafe()
LOGICAL alldefs_allocsafe (int ast, int stmt)
Definition at line 2393 of file optutil.c.
References A_OPTYPEG, ast, def, DEF_STD, FALSE, FG_UNINITED, fgx, find_next_reaching_def(), is_alloc_std(), is_initialized(), is_parentof_ast(), is_ptrdef_in_path(), nme_of_ast(), NULL, std, STD_AST, STD_FG, stmt, and TRUE.
Referenced by _find_rhs_def_conflict(), and lhs_needtmp().
ast_grandparent()
static int ast_grandparent (int astptr) static
Definition at line 1908 of file optutil.c.
Referenced by is_parentof_ast().
avail_expr()
static LOGICAL avail_expr (int expr) static
Definition at line 916 of file optutil.c.
References _avail(), ast_traverse(), ast_unvisit(), ast_visit(), gbl, NULL, OPTDBG, and TRUE.
Referenced by can_copy_def(), and is_avail_expr().
basesym_of()
int basesym_of (int nme)
Return the base st index of the names entry.
Returns the base symbol of a reference given its names entry – returns 0 if unknown.
Definition at line 685 of file nmeutil.c.
References NME_NM, NME_SYM, NME_TYPE, NT_ARR, NT_IND, NT_MEM, NT_SAFE, NT_VAR, and SPTR_NULL.
Referenced by _find_lhs_on_rhs_conflict(), _find_rhs_def_conflict(), can_copy_def(), can_prop_def(), dd_compute(), def_ok(), dump_global(), dump_vinduc(), exp_ac(), gen_address_operand(), gen_llvm_expr(), get_dtype_for_vect_type_nme(), get_lhs_first_defs(), is_blockaddr_store(), is_ptr_safe(), only_one_ud(), set_assn(), single_ud(), storedums(), and use_before_def().
bv_copy()
void bv_copy (BV * a, BV * b, int len)
Definition at line 100 of file optutil.c.
References a, b, and len.
Referenced by dd_succ(), live_var(), live_var_end(), reaching_defs(), and uninit_var().
bv_intersect()
void bv_intersect (BV * a, BV * b, UINT len)
Definition at line 121 of file optutil.c.
References a, b, and len.
Referenced by uninit_var().
bv_intersect3()
void bv_intersect3 (BV * a, BV * b, BV * c, UINT len)
Definition at line 128 of file optutil.c.
References a, b, and len.
bv_mem()
LOGICAL bv_mem (BV * a, int elem)
Definition at line 164 of file optutil.c.
References a, assert, BV_BITS, FALSE, NULL, r, TRUE, and w.
Referenced by _avail(), chkref(), def_in_out(), du_ud(), find_next_reaching_def(), find_rdef(), is_def_imp_live(), is_initialized(), is_live_in(), is_live_out(), iscall_in_path(), isptr_in_path(), new_du_ud(), and use_before_def().
bv_notequal()
LOGICAL bv_notequal (BV * a, BV * b, int len)
Definition at line 155 of file optutil.c.
References a, b, FALSE, len, and TRUE.
Referenced by dd_succ(), live_var(), reaching_defs(), and uninit_var().
bv_off()
void bv_off (BV * a, int elem)
Definition at line 145 of file optutil.c.
References a, BV_BITS, r, and w.
Referenced by reaching_defs().
bv_print()
void bv_print (BV * bv, int maxlen)
Definition at line 179 of file optutil.c.
References BV_BITS, gbl, i, j, and w.
Referenced by dd_succ(), dump_global(), new_du_ud(), and reaching_defs().
bv_set()
void bv_set (BV * a, int elem)
Definition at line 135 of file optutil.c.
References a, BV_BITS, r, and w.
Referenced by add_def(), add_use(), dd_succ(), live_var_init(), reaching_defs(), and uninit_var_init().
bv_sub()
void bv_sub (BV * a, BV * b, int len)
Definition at line 114 of file optutil.c.
References a, b, and len.
Referenced by live_var().
bv_union()
void bv_union (BV * a, BV * b, int len)
Definition at line 107 of file optutil.c.
References a, b, and len.
Referenced by dd_succ(), live_var(), live_var_end(), new_du_ud(), reaching_defs(), and uninit_var().
bv_zero()
void bv_zero (BV * a, int len)
Definition at line 93 of file optutil.c.
References a, and len.
Referenced by live_var(), live_var_end(), live_var_init(), new_du_ud(), reaching_defs(), uninit_var(), and uninit_var_init().
call_in_path()
static LOGICAL call_in_path (int cur) static
Definition at line 1332 of file optutil.c.
References BIH_EX, call_in_path(), FALSE, FG_NATNXT, FG_PRED, FG_TO_BIH, FG_VISITED, gbl, OPTDBG, pred, PSI_NEXT, PSI_NODE, PSI_P_NULL, TRUE, and visit_list.
Referenced by call_in_path(), and iscall_in_path().
can_copy_def()
LOGICAL can_copy_def (int def, int fgx, LOGICAL begin)
Definition at line 699 of file optutil.c.
References assert, avail_expr(), basesym_of(), BIH_ILTFIRST, BIH_ILTLAST, def, DEF_CONST, DEF_DOINIT, DEF_FG, DEF_NM, def_ok(), DEF_RHS, DEF_STD, FALSE, FG_STDLAST, FG_TO_BIH, fgx, gbl, getprint(), OPTDBG, srch_ae, TRUE, and XBIT.
Referenced by cp_loop(), and find_bivs().
collect_loads()
static LOGICAL collect_loads (int expr, int * dummy) static
Definition at line 1747 of file optutil.c.
References copyb, FALSE, gbl, i, is_optsym(), OPT_NEED, OPTDBG, and TRUE.
Referenced by copy_to_loop().
copy_to_loop()
int copy_to_loop (int tree, int lp)
Definition at line 1702 of file optutil.c.
References ast_traverse(), ast_unvisit(), ast_visit(), collect_loads(), copyb, cp_loop(), dbg_print_ast(), FALSE, gbl, i, lp, NULL, OPT_ALLOC, OPT_FREE, OPTDBG, and TRUE.
cp_loop()
static LOGICAL cp_loop (int expr) static
Definition at line 1776 of file optutil.c.
References ast_intr(), ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), can_copy_def(), copyb, DEF_RHS, DT_DBLE, DT_INT, DTY, FALSE, FG_LOOP, FG_PRED, find_rdef(), gbl, i, LP_HEAD, OPTDBG, pred, PSI_NEXT, PSI_NODE, PSI_P_NULL, TRUE, TY_BINT, TY_DBLE, TY_INT, TY_REAL, and TY_SINT.
Referenced by copy_to_loop().
def_ok()
LOGICAL def_ok (int def, int fgx, int stmt)
Definition at line 748 of file optutil.c.
References assert, basesym_of(), BIH_CS, def, DEF_DOINIT, DEF_FG, DEF_NM, DEF_SELF, DEF_STD, FALSE, FG_IN, FG_TO_BIH, fgx, gbl, getprint(), is_call_in_path(), is_call_safe(), is_dominator(), is_ptr_in_path(), is_sym_entry_live(), is_sym_ptrsafe(), NME_SYM, NULL, OPTDBG, STD_EX, STD_PREV, stmt, TRUE, and XBIT.
Referenced by can_copy_def(), only_one_ud(), and single_ud().
find_lhs_on_rhs_conflict()
static void find_lhs_on_rhs_conflict (int lhs, int rhs, int stmt, int allochk, int * result) static
Definition at line 2702 of file optutil.c.
References _find_lhs_on_rhs_conflict(), args, ast_traverse(), ast_unvisit(), ast_visit(), lhs, lhscount, MAX_DEF, NULL, result, and stmt.
Referenced by lhs_needtmp().
find_next_reaching_def()
int find_next_reaching_def (int nme, int fgx, int def)
Definition at line 1885 of file optutil.c.
References bv_mem(), def, DEF_NEXT, FG_IN, fgx, and NME_DEF.
Referenced by alldefs_allocsafe(), get_lhs_first_defs(), lhs_needtmp(), and ptrdefs_has_lhsconflict().
find_rdef()
int find_rdef (int nme, int fgx, LOGICAL begin)
Definition at line 481 of file optutil.c.
References bv_mem(), def, DEF_NEXT, FG_IN, FG_OUT, fgx, is_optsym(), NME_DEF, and NULL.
Referenced by cp_loop(), and find_bivs().
find_rhs_conflict()
static void find_rhs_conflict (int lhs, int rhs, int stmt, int allochk, int * result) static
Definition at line 2684 of file optutil.c.
References _find_rhs_def_conflict(), args, ast_traverse(), ast_unvisit(), ast_visit(), lhs, lhscount, MAX_DEF, NULL, result, and stmt.
Referenced by lhs_needtmp().
get_lhs_first_defs()
static void get_lhs_first_defs (int stmt, int lhs) static
Definition at line 2749 of file optutil.c.
References a, A_OPTYPEG, add_lhs_nme(), args, ARGT_ARG, basesym_of(), def, DEF_STD, FALSE, fgx, find_next_reaching_def(), get_lhs_first_defs(), is_parentof_ast(), is_sym_ptrsafe(), lhs, lhscount, MAX_DEF, nme_of_ast(), std, STD_AST, STD_FG, stmt, and TRUE.
Referenced by get_lhs_first_defs(), and lhs_needtmp().
get_next_parent()
static int get_next_parent (int astptr, int myparent) static
Definition at line 1928 of file optutil.c.
Referenced by is_parentof_ast().
in_path()
static LOGICAL in_path (int cur, int fg) static
Definition at line 1188 of file optutil.c.
References FALSE, fg, FG_NATNXT, FG_PRED, FG_VISITED, in_path(), pred, PSI_NEXT, PSI_NODE, PSI_P_NULL, TRUE, and visit_list.
Referenced by in_path(), and is_in_path().
is_avail_expr()
LOGICAL is_avail_expr (int expr, int start_ilt, int start_fg, int end_ilt, int end_fg)
Definition at line 883 of file optutil.c.
References avail_expr(), FALSE, gbl, OPTDBG, srch_ae, and TRUE.
Referenced by eliminate_bnds(), eliminate_gather(), eliminate_get_scalar(), eliminate_shift(), eliminate_start(), is_avail_expr_with_list(), is_same_array_bounds(), is_same_def(), only_one_ud(), same_forall_bnds(), same_forall_size(), and single_ud().
is_call_in_path()
LOGICAL is_call_in_path (int start_ilt, int start_fg, int end_ilt, int end_fg)
Definition at line 1362 of file optutil.c.
References iscall_in_path(), and srch_ae.
Referenced by def_ok().
is_call_safe()
LOGICAL is_call_safe (int nme)
Definition at line 358 of file optutil.c.
References FALSE, gbl, IS_CMNBLK, NME_SYM, and TRUE.
Referenced by _avail(), and def_ok().
is_def_imp_live()
LOGICAL is_def_imp_live (int def)
Definition at line 1560 of file optutil.c.
References assert, bv_mem(), def, DEF_NM, OPT::exitfg, FALSE, FG_IN, gbl, is_sym_exit_live(), NME_SYM, NULL, opt, OPTDBG, TRUE, and XBIT.
Referenced by rm_def_rloop().
is_in_path()
static LOGICAL is_in_path (int fg) static
Definition at line 1164 of file optutil.c.
References fg, FG_NATNXT, FG_VISITED, in_path(), srch_ae, and TRUE.
Referenced by _avail().
is_optsym()
LOGICAL is_optsym (int nme)
Definition at line 206 of file optutil.c.
References FALSE, NME_TYPE, NT_VAR, and TRUE.
Referenced by _avail(), collect_loads(), copy_const(), find_rdef(), is_initialized(), is_live_in(), is_live_out(), live_var_init(), and uninit_var_init().
is_parentof_ast()
static LOGICAL is_parentof_ast (int astp, int astc) static
Definition at line 2019 of file optutil.c.
References ast_grandparent(), FALSE, get_next_parent(), i, interr(), and TRUE.
Referenced by _find_lhs_on_rhs_conflict(), alldefs_allocsafe(), get_lhs_first_defs(), and is_ptrast_arg().
is_ptr_in_path()
LOGICAL is_ptr_in_path (int start_ilt, int start_fg, int end_ilt, int end_fg)
Definition at line 1464 of file optutil.c.
References isptr_in_path(), and srch_ae.
Referenced by def_ok().
is_ptr_safe()
LOGICAL is_ptr_safe (int nme)
Definition at line 399 of file optutil.c.
References assert, basesym_of(), FALSE, NME_TYPE, NT_IND, NT_MEM, NT_VAR, TRUE, and XBIT.
Referenced by add_store(), bld_lhs(), chk_ptr_load(), is_store_via_ptr(), resolve_pp(), and resolve_pv().
is_ptrast_arg()
static LOGICAL is_ptrast_arg (int ptrast, int ast) static
Definition at line 2119 of file optutil.c.
References A_ARGCNTG, argt, ARGT_ARG, ast, aux, DDTG, AUX::dpdsc_base, DTY, FALSE, FLANG_FALLTHROUGH, i, interr(), is_parentof_ast(), memsym_of_ast(), nargs, NULL, pass_sym_of_ast(), proc_arginfo(), procsym_of_ast(), sptr, and TRUE.
Referenced by isptrdef_in_path().
is_ptrdef_in_path()
LOGICAL is_ptrdef_in_path (int start_ilt, int start_fg, int end_ilt, int end_fg, int nme, int ast)
Definition at line 2379 of file optutil.c.
References ast, basenme_of(), isptrdef_in_path(), and srch_ae.
Referenced by alldefs_allocsafe().
is_store_via_ptr()
LOGICAL is_store_via_ptr (int astx)
Definition at line 638 of file optutil.c.
References FALSE, is_ptr_safe(), NME_NM, NME_SYM, NME_TYPE, NT_ARR, NT_IND, NT_MEM, NT_VAR, and TRUE.
Referenced by isptr_in_path().
is_sym_entry_live()
LOGICAL is_sym_entry_live (int nme)
Definition at line 607 of file optutil.c.
References assert, FALSE, INTENT_OUT, INTENTG, IS_DUM, IS_EXTERN, IS_STATIC, NME_SYM, nmeb, s, stb, and TRUE.
Referenced by def_ok(), live_var_init(), and uninit_var_init().
is_sym_exit_live()
LOGICAL is_sym_exit_live (int nme)
Definition at line 522 of file optutil.c.
References assert, FALSE, gbl, INTENT_IN, INTENTG, IS_DUM, IS_EXTERN, IS_STATIC, NME_SYM, nmeb, RU_PROG, s, stb, and TRUE.
Referenced by check_alias(), is_def_imp_live(), is_sym_imp_live(), live_var_init(), and uninit_var_init().
is_sym_imp_live()
LOGICAL is_sym_imp_live (int nme)
Definition at line 572 of file optutil.c.
References assert, FALSE, is_sym_exit_live(), NME_SYM, nmeb, TRUE, and XBIT.
Referenced by const_prop(), delete_stores(), and ind_loop_init().
is_sym_live_safe()
LOGICAL is_sym_live_safe (int nme, int lpx)
Definition at line 281 of file optutil.c.
References FALSE, IS_LCL_OR_DUM, IS_PRIVATE, is_sym_ptrsafe(), LP_CALLFG, LP_CSECT, LP_PARLOOP, LP_PARREGN, LP_PARSECT, LP_PTR_LOAD, LP_PTR_STORE, LP_STL_PAR, lpx, LPZ, NME_SYM, NULL, q, TRUE, and XBIT.
Referenced by is_live_in(), and is_live_out().
is_sym_optsafe()
LOGICAL is_sym_optsafe (int nme, int lpx)
Definition at line 214 of file optutil.c.
References FALSE, IS_LCL_OR_DUM, IS_PRIVATE, is_sym_ptrsafe(), LP_CALLFG, LP_CSECT, LP_PARLOOP, LP_PARREGN, LP_PARSECT, LP_PTR_LOAD, LP_PTR_STORE, LP_STL_PAR, lpx, NME_SYM, NULL, q, TRUE, and XBIT.
Referenced by check_alias(), ind_loop_init(), and resolve_pv().
is_sym_ptrsafe()
LOGICAL is_sym_ptrsafe (int sym)
Definition at line 435 of file optutil.c.
References FLG::depchk, FALSE, flg, TRUE, and XBIT.
Referenced by def_ok(), get_lhs_first_defs(), is_sym_invariant_safe(), is_sym_live_safe(), and is_sym_optsafe().
iscall_in_path()
static LOGICAL iscall_in_path (void) static
Definition at line 1215 of file optutil.c.
References BIH_EX, bv_mem(), CALL_DEF, call_in_path(), FALSE, FG_IN, FG_LOOP, FG_NATNXT, FG_STDFIRST, FG_STDLAST, FG_TO_BIH, FG_VISITED, gbl, is_dominator(), OPTDBG, srch_ae, STD_EX, STD_NEXT, STD_PREV, and TRUE.
Referenced by _avail(), and is_call_in_path().
isptr_in_path()
static LOGICAL isptr_in_path (void) static
Definition at line 1378 of file optutil.c.
References bv_mem(), FALSE, FG_IN, FG_PTR_STORE, FG_STDFIRST, FG_STDLAST, gbl, is_store_via_ptr(), OPTDBG, PTR_STORE_DEF, srch_ae, STD_AST, STD_NEXT, STD_PREV, and TRUE.
Referenced by _avail(), and is_ptr_in_path().
isptrdef_in_path()
static LOGICAL isptrdef_in_path (int nme, int ptrast) static
Definition at line 2240 of file optutil.c.
References A_OPTYPEG, args, ARGT_ARG, FALSE, FG_STDFIRST, FG_STDLAST, gbl, is_ptrast_arg(), nme_of_ast(), OPTDBG, srch_ae, STD_AST, STD_NEXT, STD_PREV, and TRUE.
Referenced by is_ptrdef_in_path().
lhs_needtmp()
LOGICAL lhs_needtmp (int lhs, int rhs, int stmt)
Definition at line 2847 of file optutil.c.
References alldefs_allocsafe(), def, DEF_STD, FALSE, fgx, find_lhs_on_rhs_conflict(), find_next_reaching_def(), find_rhs_conflict(), get_lhs_first_defs(), lhs, lhscount, nme_of_ast(), result, std, STD_FG, stmt, and TRUE.
Referenced by forall_dependency().
nme_of_ast()
int nme_of_ast (int ast)
Definition at line 2094 of file optutil.c.
References ast, and basenme_of().
Referenced by _find_lhs_on_rhs_conflict(), _find_rhs_def_conflict(), alldefs_allocsafe(), get_lhs_first_defs(), isptrdef_in_path(), lhs_needtmp(), and ptrdefs_has_lhsconflict().
only_one_ud()
LOGICAL only_one_ud (int use)
Definition at line 1517 of file optutil.c.
References assert, basesym_of(), def, UD_TAG::def, DEF_DU, DEF_FG, def_ok(), DEF_SELF, DEF_STD, FALSE, gbl, getprint(), is_avail_expr(), UD_TAG::next, DU_TAG::next, NULL, opt, OPTDBG, t, use, DU_TAG::use, USE_AST, USE_FG, USE_NM, USE_STD, and USE_UD.
pred_of_loop()
int pred_of_loop (int lpx)
Definition at line 453 of file optutil.c.
References FG_LOOP, FG_PRED, fgx, LP_HEAD, lpx, pred, PSI_NEXT, PSI_NODE, and PSI_P_NULL.
Referenced by find_bivs().
ptrdefs_has_lhsconflict()
static LOGICAL ptrdefs_has_lhsconflict (int nme, int std, int def) static
Definition at line 2462 of file optutil.c.
References A_OPTYPEG, args, ARGT_ARG, def, DEF_STD, FALSE, FG_UNINITED, find_next_reaching_def(), i, is_initialized(), lhscount, lhsdefs, nme_of_ast(), ptrdefs_has_lhsconflict(), std, STD_AST, STD_FG, and TRUE.
Referenced by _find_rhs_def_conflict(), and ptrdefs_has_lhsconflict().
rm_def_rloop()
void rm_def_rloop (int def, int lpx)
Definition at line 1619 of file optutil.c.
References assert, count, def, DEF_DELETE, DEF_DU, DEF_FG, DEF_STD, FALSE, FG_LOOP, FG_TO_BIH, gbl, i, is_def_imp_live(), lpx, DU_TAG::next, NULL, opt, OPTDBG, STD_DELETE, STD_PREV, unlnkilt(), use, DU_TAG::use, USE_FG, and USE_STD.
single_ud()
LOGICAL single_ud (int use)
Definition at line 1479 of file optutil.c.
References assert, basesym_of(), def, UD_TAG::def, DEF_FG, def_ok(), DEF_RHS, DEF_STD, FALSE, gbl, getprint(), is_avail_expr(), UD_TAG::next, NULL, opt, OPTDBG, use, USE_FG, USE_NM, USE_STD, and USE_UD.
Referenced by check_alias(), and const_prop().
Variable Documentation
struct { ... } copyb
Referenced by collect_loads(), copy_to_loop(), and cp_loop().
struct { ... } end
eob
int eob
Definition at line 677 of file optutil.c.
fg
int fg
Definition at line 671 of file optutil.c.
Referenced by add_empty_succ(), add_fg(), add_pred(), add_single_loop_exit(), add_succ(), append_succ(), basic_block_redundant(), can_prop_fg(), contains_alloc(), eliminate_alloc(), eliminate_bnds(), eliminate_copy(), eliminate_gather(), eliminate_get_scalar(), eliminate_sect(), eliminate_shift(), eliminate_start(), fillin_succ(), findssexprs(), findssexprsfg(), forall_dependency(), fuse_forall(), get_temp_forall2(), hoist_comms(), hoist_std(), in_path(), is_avail_expr_with_list(), is_branch_between(), is_contains_ast_between(), is_fusable(), is_in_path(), is_safe_copy(), is_same_array_bounds(), is_same_def(), is_tail_aexe(), markmodifiedexprs(), markmodifiedexprsfg(), mk_ztrips(), move_invar_std(), must_follow(), optimize(), reassociate(), remove_loop(), rewritefg(), sdrop_stmt(), sectfloat(), set_std_fg(), sfloat(), sfloat_stmt(), sfloat_stmt2(), smp_conflict(), unique_allo(), and use_before_def().
lhscount
int lhscount = 0 static
Definition at line 1879 of file optutil.c.
Referenced by _find_lhs_on_rhs_conflict(), _find_rhs_def_conflict(), add_lhs_nme(), find_lhs_on_rhs_conflict(), find_rhs_conflict(), get_lhs_first_defs(), lhs_needtmp(), and ptrdefs_has_lhsconflict().
lhsdefs
ptrdefstr lhsdefs[MAX_DEF] static
Definition at line 1878 of file optutil.c.
Referenced by _find_rhs_def_conflict(), add_lhs_nme(), and ptrdefs_has_lhsconflict().
lp
int lp
Definition at line 1687 of file optutil.c.
Referenced by __dump_loop(), __dump_region(), __fortio_assign(), add_loop_hd(), add_loop_preheader(), add_single_loop_exit(), add_to_parent(), check_inner_uses(), check_outer_defs(), comm_invar(), contains_alloc(), copy_to_loop(), dd_array_conflict(), dd_edge(), def_in_innerlp(), do_subscript(), dump_region(), eliminate_alloc(), eliminate_bnds(), eliminate_copy(), eliminate_gather(), eliminate_sect(), eliminate_shift(), eliminate_start(), findloop(), get_loop_count(), get_loopcounts(), getast(), has_def_inlp(), hoist_comms(), hoist_loop(), hoist_std(), induction(), invar_end(), invar_init(), invar_mark(), invariant(), invariant_nomotion(), is_branch_between(), is_contains_ast_between(), is_fusable(), is_hoistable(), is_live_in(), is_live_out(), is_tail_aexe(), kred_array_loop(), loop_init(), mk_loop_hdtl(), mk_ztrips(), red_array_loop(), rm_edge(), top_sort(), and unique_allo().
new
int new
Definition at line 1688 of file optutil.c.
Referenced by __abort_sig_hand(), and __abort_sig_init().
struct { ... } srch_ae
Referenced by _avail(), can_copy_def(), is_avail_expr(), is_call_in_path(), is_in_path(), is_ptr_in_path(), is_ptrdef_in_path(), iscall_in_path(), isptr_in_path(), and isptrdef_in_path().
struct { ... } start
stg_avail
int stg_avail
Definition at line 1691 of file optutil.c.
stg_base
int* stg_base
Definition at line 1689 of file optutil.c.
stg_size
int stg_size
Definition at line 1690 of file optutil.c.
stmt
int stmt
Definition at line 670 of file optutil.c.
Referenced by _constructf90(), add_stmt_after(), add_stmt_before(), alldefs_allocsafe(), check_alloc_ptr_type(), check_pointer_type(), conv_allocate(), conv_forall(), conv_fused_forall(), def_ok(), find_lhs_on_rhs_conflict(), find_rhs_conflict(), gen_alloc_dealloc(), get_lhs_first_defs(), inline_RTE_set_type(), lhs_needtmp(), and rewrite_block_forall().
visit_list
int visit_list static
Definition at line 680 of file optutil.c.
Referenced by call_in_path(), and in_path().