flang: outconv.c File Reference
outconv.c File Reference
Routines for descriptor optimizatons and forall transformations.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "soc.h"
#include "semant.h"
#include "ast.h"
#include "pragma.h"
#include "gramtk.h"
#include "extern.h"
#include "commopt.h"
#include "dpm_out.h"
#include "nme.h"
#include "optimize.h"
#include "pd.h"
#include "ccffinfo.h"
#include "rte.h"
#include "comm.h"
#include "fdirect.h"
#include "rtlRtns.h"
#include "ilidir.h"
Classes
struct T_LIST
struct COLLAPSE
struct syminfostruct
Macros
#define RTE_C
#define NO_PTR XBIT(49, 0x8000)
#define NO_CHARPTR XBIT(58, 0x1)
#define NO_DERIVEDPTR XBIT(58, 0x40000)
#define MKASSN(d, s) mk_assn_stmt(d, s, 0)
#define TEMP_AREA 6
#define GET_T_LIST(q) q = (T_LIST *)getitem(TEMP_AREA, sizeof(T_LIST))
#define NO_WRKSHR 0
#define IN_WRKSHR 1
#define IN_PDO 2
#define IN_SINGLE 3
#define IN_PARALLEL 4
#define IN_CRITICAL 5
#define VALUE_ARGT_ARG(a, b) value(ARGT_ARG(a, b))
#define TAGDESC 35
#define SECTZBASE 0x00400000
#define SEQSECTION 0x20000000
#define TEMPLATE 0x00010000
#define COLLAPSE_ASTARR(i) collapse.base[i].astArr
#define COLLAPSE_STDALLOC(i) collapse.base[i].stdAlloc
#define COLLAPSE_STDDEALLOC(i) collapse.base[i].stdDealloc
#define COLLAPSE_LP(i) collapse.base[i].lp
#define COLLAPSE_ASTSCLR(i) collapse.base[i].astSclr
#define COLLAPSE_DESCR(i) collapse.base[i].flags.bits.descr
#define COLLAPSE_DELETE(i) collapse.base[i].flags.bits.delete
Typedefs
typedef struct T_LIST T_LIST
typedef struct syminfostruct syminfostruct
Functions
static void convert_statements (void)
static void convert_simple (void)
static int conv_allocate (int std)
static int conv_deallocate (int std)
static LOGICAL is_same_mask (int expr, int expr1)
static LOGICAL no_effect_forall (int std)
static void init_collapse (void)
static void collapse_arrays (void)
static void end_collapse (void)
static void find_collapse_allocs (void)
static void find_collapse_defs (void)
static void delete_collapse (int ci)
static void find_collapse_uses (void)
static LOGICAL is_parent_loop (int lpParent, int lp)
static void collapse_loops (void)
static void find_descrs (void)
static void collapse_allocates (LOGICAL bDescr)
static void report_collapse (int lp)
static int position_finder (int forall, int ast)
static void find_calls_pos (int std, int forall, int must_pos)
static void find_mask_calls_pos (int forall)
static void find_stmt_calls_pos (int forall, int mask_pos)
static int find_max_of_mask_calls_pos (int forall)
static void add_mask_calls (int pos, int forall, int stdnext)
static void add_stmt_calls (int pos, int forall, int stdnext)
static void forall_dependency (int std)
static void put_calls (int pos, int std, int stdnext)
static void search_pure_function (int stdfirst, int stdlast)
static int transform_pure_function (int expr, int std)
static void eliminate_barrier (void)
static void remove_mask_calls (int forall)
static void remove_stmt_calls (int forall)
static void move_mask_calls (int forall)
static LOGICAL is_stmt_call_dependent (int forall, int lhs)
static LOGICAL is_mask_call_dependent (int forall, int lhs)
static LOGICAL is_call_dependent (int std, int forall, int lhs)
static void convert_omp_workshare (void)
static void insert_assign (int lhs, int rhs, int beforestd)
static void convert_template_instance (void)
void convert_output (void)
static void early_flow_init (void)
static void early_flow_fini (void)
void forall_dependency_analyze (void)
void convert_forall (void)
static int gen_pdo (int do_ast)
static void gen_endsingle (int std, int single, int presinglebarrier)
static int _pghpf_bound (int lbound, int ast)
static int _pghpf_size (int size, int ast)
static int _RTE_size (int ast)
static int _pgi_element_size (int ast)
static int _pgi_kind (int ast)
static int size_shape (int shape, int i)
static int _PDsize (int ast)
static int _PDbound (int lbound, int ast)
Used to simplify PD_lbound or PD_ubound call ast nodes to the value from shape descriptor of adjustable array.
static int _RTE_bound (int lbound, int ast)
static int _RTE_xb (int lbound, int ast, int rdt, int dolong)
static int _RTE_ba (int lbound, int ast)
static int value (int ast)
static int symvalue (int ast, char c, int num, int *ptemp, int var, int sdsc)
static void _simple_replacements (int ast, int *pany)
static int check_subscript (int ast, int value)
static int check_value (int ast, int value)
static int full_dimension (int astlower, int astupper, int aststride, int dim)
static int _sect (int ast, int i8)
static int _template (int ast, int rank, LOGICAL usevalue, int i8)
static int _sd_member (int subscript, int sdx, int sdtype)
int gen_set_len_ast (int ast, SPTR ddesc, int sz)
This routine assigns a size to a descriptor's length field.
LOGICAL inline_RTE_set_type (int ddesc, int sdesc, int stmt, int after, DTYPE src_dtype, int astmem)
static void _ptrassign_copy (int subscript, int ptrsdx, int tgtsdx, int sdtype)
static void _ptrassign_set (int subscript, int ptrsdx, int value, int sdtype)
static void _ptrassign_set_ast (int subscript, int ptrsdx, int valastx, int sdtype)
static int _ptrassign (int astx)
void sectinline (void)
static void _mark_descr (int ast, int *dummy)
LOGICAL want_descriptor_anyway (int sptr)
Return TRUE if we need to initialize the descriptor for this symbol because perhaps this is a host subroutine, and the internal subprograms will need the descriptor, or perhaps -g is set.
static int lhs_dim (int forall, int astli)
static void conv_fused_forall (int std, int ast, int *stdnextp)
static LOGICAL is_same_mask_in_fused (int std, int *pos)
int conv_forall (int std)
static void replace_loop_on_fuse_list (int oldloop, int maskloop)
static int get_temp_forall2 (int forall_ast, int subscr_ast, int alloc_stmt, int dealloc_stmt, int dty, int ast_dty)
static LOGICAL is_pointer (int ast)
LOGICAL is_pointer_dependent (int sptr, int sptr1)
static void look_for_descriptor (int ast, int *unused)
void enter_local_mode (int std)
void exit_local_mode (int std)
static LOGICAL at_local_mode (int ast)
static LOGICAL use_offset (int sptr)
static LOGICAL needs_linearization (int sptr)
static void _linearize (int ast, int *dummy)
static void _linearize_all (int ast)
static void _linearize_sub (int ast)
static void _linearize_func (int ast, int *dummy)
void linearize_arrays (void)
static LOGICAL _check_clean (int ast, int *pl)
static void sfloat_stmt (int std, int fg, int l)
static void sdrop_stmt (int std, int fg, int l)
static void sfloat_stmt2 (int std, int fg, int l)
void hoist_stmt (int std, int fg, int l)
void restore_hoist_stmt (int lp)
static void add_def_syminfo (int sptr, int l)
static LOGICAL have_preheader (int l)
static void sfloat (int l)
void sectfloat (void)
Variables
static T_LIST * templist
static int beforestd
static int newsymnum
struct {
COLLAPSE * base
int size
int avail
int lp
int std
} collapse
static int global_astArrdsc
static int global_flag
static LOGICAL linearize_any
static int * stddeflist
static int * loopdeflist
static syminfostruct * syminfo
static int clean
static int always_executed
static int chk_assign
static int chk_subscr
Detailed Description
Routines for descriptor optimizatons and forall transformations.
Definition in file outconv.c.
Macro Definition Documentation
COLLAPSE_ASTARR
#define COLLAPSE_ASTARR (i) collapse.base[i].astArr
Definition at line 4270 of file outconv.c.
COLLAPSE_ASTSCLR
#define COLLAPSE_ASTSCLR (i) collapse.base[i].astSclr
Definition at line 4274 of file outconv.c.
COLLAPSE_DELETE
#define COLLAPSE_DELETE (i) collapse.base[i].flags.bits.delete
Definition at line 4276 of file outconv.c.
COLLAPSE_DESCR
#define COLLAPSE_DESCR (i) collapse.base[i].flags.bits.descr
Definition at line 4275 of file outconv.c.
COLLAPSE_LP
#define COLLAPSE_LP (i) collapse.base[i].lp
Definition at line 4273 of file outconv.c.
COLLAPSE_STDALLOC
#define COLLAPSE_STDALLOC (i) collapse.base[i].stdAlloc
Definition at line 4271 of file outconv.c.
COLLAPSE_STDDEALLOC
#define COLLAPSE_STDDEALLOC (i) collapse.base[i].stdDealloc
Definition at line 4272 of file outconv.c.
GET_T_LIST
#define GET_T_LIST (q) q = (T_LIST *)getitem(TEMP_AREA, sizeof(T_LIST))
Definition at line 127 of file outconv.c.
IN_CRITICAL
#define IN_CRITICAL 5
Definition at line 256 of file outconv.c.
IN_PARALLEL
#define IN_PARALLEL 4
Definition at line 255 of file outconv.c.
IN_PDO
#define IN_PDO 2
Definition at line 253 of file outconv.c.
IN_SINGLE
#define IN_SINGLE 3
Definition at line 254 of file outconv.c.
IN_WRKSHR
#define IN_WRKSHR 1
Definition at line 252 of file outconv.c.
MKASSN
#define MKASSN (d, s) mk_assn_stmt(d, s, 0)
Definition at line 88 of file outconv.c.
NO_CHARPTR
#define NO_CHARPTR XBIT(58, 0x1)
Definition at line 84 of file outconv.c.
NO_DERIVEDPTR
#define NO_DERIVEDPTR XBIT(58, 0x40000)
Definition at line 85 of file outconv.c.
NO_PTR
#define NO_PTR XBIT(49, 0x8000)
Definition at line 83 of file outconv.c.
NO_WRKSHR
#define NO_WRKSHR 0
Definition at line 251 of file outconv.c.
RTE_C
#define RTE_C
Definition at line 30 of file outconv.c.
SECTZBASE
#define SECTZBASE 0x00400000
SEQSECTION
#define SEQSECTION 0x20000000
TAGDESC
#define TAGDESC 35
TEMP_AREA
#define TEMP_AREA 6
Definition at line 120 of file outconv.c.
TEMPLATE
#define TEMPLATE 0x00010000
VALUE_ARGT_ARG
#define VALUE_ARGT_ARG (a, b) value(ARGT_ARG(a, b))
Definition at line 1433 of file outconv.c.
Typedef Documentation
syminfostruct
typedef struct syminfostruct syminfostruct
T_LIST
typedef struct T_LIST T_LIST
Function Documentation
_check_clean()
static LOGICAL _check_clean (int ast, int * pl) static
Definition at line 5559 of file outconv.c.
References _check_clean(), A_OPTYPEG, always_executed, ASD_NDIM, ASD_SUBS, ast, ast_traverse(), chk_assign, chk_subscr, clean, d, DT_ISINT, FALSE, i, LP_CALLFG, NULL, OP_DIV, OP_MUL, sptr, syminfo, and TRUE.
Referenced by _check_clean(), and sfloat().
_linearize()
static void _linearize (int ast, int * dummy) static
Definition at line 5169 of file outconv.c.
References A_ARGCNTG, A_OPTYPEG, A_OPTYPEP, ADD_LWAST, ADD_UPAST, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, ast, ast_replace(), ast_rewrite(), astb, check_member(), DDTG, ddtype(), dsym(), DT_INT, DTY, get_local_multiplier(), get_xbase(), i, ASTB::i0, ASTB::i1, linearize_any, mk_argt(), mk_binop(), mk_func_node(), mk_id(), mk_member(), mk_subscr(), ndim, needs_linearization(), off, OP_ADD, OP_MUL, OP_SUB, parent, s, sptr, ss, stride, subscr, TRUE, unmk_argt(), use_offset(), and XBIT.
Referenced by _linearize_all().
_linearize_all()
static void _linearize_all (int ast) static
Definition at line 5336 of file outconv.c.
References _linearize(), ast, ast_traverse(), dummy, and NULL.
Referenced by _linearize_sub(), and linearize_arrays().
_linearize_func()
static void _linearize_func (int ast, int * dummy) static
Definition at line 5370 of file outconv.c.
References A_ARGCNTG, A_OPTYPEG, ALIGNG, arg, args, ARGT_ARG, ast, astb, aux, check_member(), DDTG, AUX::dpdsc_base, DTY, i, ASTB::i1, mk_id(), mk_subscr(), needs_linearization(), sptr, subscr, use_offset(), and XBIT.
Referenced by linearize_arrays().
_linearize_sub()
static void _linearize_sub (int ast) static
Definition at line 5343 of file outconv.c.
References _linearize_all(), ASD_NDIM, ASD_SUBS, ast, and i.
Referenced by linearize_arrays().
_mark_descr()
static void _mark_descr (int ast, int * dummy) static
Definition at line 2630 of file outconv.c.
References ast, and sptr.
Referenced by convert_template_instance().
_PDbound()
static int _PDbound (int lbound, int ast) static
Used to simplify PD_lbound or PD_ubound call ast nodes to the value from shape descriptor of adjustable array.
Parameters
lbound Flag which represents whether this is a call to lbound routine. When set to zero, it means call is to ubound.
ast The AST node representing the call to lbound/ubound.
Returns
AST node representing value extracted from shape.
Definition at line 863 of file outconv.c.
References arg, argt, ARGT_ARG, ast, bound, dim, DTY, get_int_cval(), rank, SHD_LWB, SHD_NDIM, and SHD_UPB.
Referenced by _simple_replacements().
_PDsize()
static int _PDsize (int ast) static
Definition at line 773 of file outconv.c.
References a, arg, args, argt, ARGT_ARG, ast, astb, base, ASTB::bnd, check_member(), dim, DT_INT, DTY, get_desc_gsize_index(), get_global_extent_index(), get_int_cval(), i, ASTB::i1, mk_binop(), mk_cval(), mk_id(), mk_subscr(), offset, ASTB::one, OP_ADD, OP_MUL, ASTB::ptr0, rank, SHD_NDIM, SHD_STRIDE, size_shape(), and ss.
Referenced by _simple_replacements().
_pghpf_bound()
static int _pghpf_bound (int lbound, int ast) static
Definition at line 552 of file outconv.c.
References a, argt, ARGT_ARG, ast, astb, b, base, ASTB::bnd, DDTG, dim, DT_INT, ASTB::dtype, get_global_extent_index(), get_global_lower_index(), get_int_cval(), ASTB::i1, mk_binop(), mk_cval(), mk_subscr(), offset, OP_ADD, OP_MUL, OP_SUB, and ss.
Referenced by _simple_replacements().
_pghpf_size()
static int _pghpf_size (int size, int ast) static
Definition at line 610 of file outconv.c.
References argt, ARGT_ARG, ast, astb, base, DDTG, dim, DT_INT, get_desc_gsize_index(), get_global_extent_index(), get_int_cval(), ASTB::i1, mk_binop(), mk_cval(), mk_subscr(), offset, OP_ADD, OP_MUL, OP_SUB, ASTB::ptr0, size, and ss.
Referenced by _simple_replacements().
_pgi_element_size()
static int _pgi_element_size (int ast) static
Definition at line 710 of file outconv.c.
References argt, ARGT_ARG, ast, astb, DDTG, DT_INT, ASTB::i0, memsym_of_ast(), mk_cval(), NOSYM, size_of(), and sptr.
Referenced by _simple_replacements().
_pgi_kind()
static int _pgi_kind (int ast) static
Definition at line 728 of file outconv.c.
References argt, ARGT_ARG, ast, astb, DDTG, DT_INT, dtype_to_arg(), ASTB::i0, memsym_of_ast(), mk_cval(), NOSYM, and sptr.
Referenced by _simple_replacements().
_ptrassign()
static int _ptrassign (int astx) static
Definition at line 2346 of file outconv.c.
References _ptrassign_copy(), _ptrassign_set(), _ptrassign_set_ast(), _sd_member(), a, ADD_LWAST, ADD_NUMDIM, add_stmt_before(), argt, ARGT_ARG, astb, beforestd, check_member(), DDTG, DT_PTR, get_global_extent_index(), get_global_lower_index(), get_multiplier_index(), get_section_offset_index(), get_section_stride_index(), i, ASTB::i0, ASTB::k0, lb, mk_binop(), mk_id(), mk_member(), mk_unop(), MKASSN, OP_LOC, OP_MUL, OP_SUB, rank, stdx, TAGDESC, and XBIT.
Referenced by sectinline().
_ptrassign_copy()
static void _ptrassign_copy (int subscript, int ptrsdx, int tgtsdx, int sdtype) static
Definition at line 2305 of file outconv.c.
References _sd_member(), add_stmt_before(), beforestd, MKASSN, and stdx.
Referenced by _ptrassign().
_ptrassign_set()
static void _ptrassign_set (int subscript, int ptrsdx, int value, int sdtype) static
Definition at line 2317 of file outconv.c.
References _sd_member(), add_stmt_before(), beforestd, mk_isz_cval(), MKASSN, stdx, and value().
Referenced by _ptrassign().
_ptrassign_set_ast()
static void _ptrassign_set_ast (int subscript, int ptrsdx, int valastx, int sdtype) static
Definition at line 2329 of file outconv.c.
References _sd_member(), add_stmt_before(), beforestd, MKASSN, and stdx.
Referenced by _ptrassign().
_RTE_ba()
static int _RTE_ba (int lbound, int ast) static
Definition at line 966 of file outconv.c.
References A_ARGCNTG, add_stmt_before(), argt, ARGT_ARG, ast, ast_to_comment(), astb, beforestd, ASTB::bnd, cmp(), dim, DT_INT, DT_LOG, get_int_cval(), ASTB::i1, insert_assign(), lb, lhs, mk_binop(), mk_cval(), mk_stmt(), mk_subscr(), ASTB::one, OP_LE, ASTB::ptr0, rank, ss, STD_ACCEL, STD_KERNEL, STD_PAR, STD_TASK, ub, and ASTB::zero.
Referenced by _simple_replacements().
_RTE_bound()
static int _RTE_bound (int lbound, int ast) static
Definition at line 897 of file outconv.c.
References A_ARGCNTG, argt, ARGT_ARG, ast, dim, get_int_cval(), and rank.
Referenced by _simple_replacements().
_RTE_size()
static int _RTE_size (int ast) static
Definition at line 656 of file outconv.c.
References a, A_ARGCNTG, args, argt, ARGT_ARG, ast, astb, ASTB::bnd, dim, get_int_cval(), i, ASTB::i1, mk_binop(), ASTB::one, OP_ADD, OP_DIV, OP_MUL, OP_SUB, ASTB::ptr0, and rank.
Referenced by _simple_replacements().
_RTE_xb()
static int _RTE_xb (int lbound, int ast, int rdt, int dolong) static
Definition at line 924 of file outconv.c.
References A_ARGCNTG, argt, ARGT_ARG, ast, astb, ASTB::bnd, dim, DT_INT, DT_LOG, get_int_cval(), lb, mk_binop(), mk_convert(), mk_merge(), ASTB::one, OP_LE, rank, ub, and ASTB::zero.
Referenced by _simple_replacements().
_sd_member()
static int _sd_member (int subscript, int sdx, int sdtype) static
Definition at line 2200 of file outconv.c.
References mk_isz_cval(), mk_subscr(), and subscr.
Referenced by _ptrassign(), _ptrassign_copy(), _ptrassign_set(), _ptrassign_set_ast(), gen_set_len_ast(), and inline_RTE_set_type().
_sect()
static int _sect (int ast, int i8) static
Definition at line 1436 of file outconv.c.
References A_ARGCNTG, A_OPTYPEP, add_stmt_before(), argt, ARGT_ARG, ast, astb, beforestd, ASTB::bnd, check_value(), cmp(), CONVAL2G, d, DT_INT, DT_LOG, ASTB::dtype, extent(), f, flags, full_dimension(), gbl, get_byte_len(), get_desc_flags(), get_desc_gsize(), get_desc_lsize(), get_desc_rank(), get_desc_tag(), get_extent(), get_gbase(), get_gbase2(), get_global_lower(), get_global_upper(), get_kind(), get_local_multiplier(), get_section_offset(), get_section_stride(), get_xbase(), getnewccsym(), getnewccsymf(), i8, I_AND, I_OR, insert_assign(), intast_sym, ISZ_T, mk_argt(), mk_binop(), mk_func_node(), mk_id(), mk_isz_cval(), mk_stmt(), mk_unop(), newsymnum, NOREINDEX, ASTB::one, OP_ADD, OP_DIV, OP_EQ, OP_LE, OP_MUL, OP_NE, OP_NEG, OP_SUB, r, rank, SECTZBASE, SEQSECTION, STD_ACCEL, STD_KERNEL, STD_PAR, STD_TASK, stride, sym_mkfunc(), symvalue(), TAGDESC, VALUE_ARGT_ARG, XBIT, and ASTB::zero.
Referenced by sectinline().
_simple_replacements()
static void _simple_replacements (int ast, int * pany) static
Definition at line 1092 of file outconv.c.
References _PDbound(), _PDsize(), _pghpf_bound(), _pghpf_size(), _pgi_element_size(), _pgi_kind(), _RTE_ba(), _RTE_bound(), _RTE_size(), _RTE_xb(), ARGT_ARG, ast, ast_replace(), fname, in_device_code(), mk_convert(), mkRteRtnNm(), RTE_extent, RTE_lb, RTE_lba, RTE_lbound, RTE_lboundDsc, RTE_size, RTE_sizeDsc, RTE_ub, RTE_uba, RTE_ubound, RTE_uboundDsc, SYMNAME, and XBIT.
Referenced by convert_simple().
_template()
static int _template (int ast, int rank, LOGICAL usevalue, int i8) static
Definition at line 2029 of file outconv.c.
References A_ARGCNTG, add_stmt_before(), argt, ARGT_ARG, ast, astb, beforestd, ASTB::bnd, cmp(), CONVAL2G, DT_INT, DT_LOG, ASTB::dtype, extent(), flags, get_byte_len(), get_desc_flags(), get_desc_gsize(), get_desc_lsize(), get_desc_rank(), get_desc_tag(), get_extent(), get_gbase(), get_gbase2(), get_global_lower(), get_global_upper(), get_kind(), get_local_multiplier(), get_section_offset(), get_section_stride(), get_xbase(), i8, insert_assign(), ISZ_T, mk_binop(), mk_isz_cval(), mk_stmt(), ASTB::one, OP_ADD, OP_LT, OP_MUL, OP_SUB, r, rank, SEQSECTION, STD_ACCEL, STD_KERNEL, STD_PAR, STD_TASK, symvalue(), TAGDESC, TEMPLATE, VALUE_ARGT_ARG, XBIT, and ASTB::zero.
Referenced by sectinline().
add_def_syminfo()
static void add_def_syminfo (int sptr, int l) static
Definition at line 5880 of file outconv.c.
References syminfostruct::defs, syminfostruct::loop, SOC_NEXT, SOC_SPTR, sptr, ss, and syminfo.
Referenced by sfloat().
add_mask_calls()
static void add_mask_calls (int pos, int forall, int stdnext) static
Definition at line 4856 of file outconv.c.
References FT_MCALL, FT_NMCALL, glist(), i, pos, and put_calls().
Referenced by conv_forall().
add_stmt_calls()
static void add_stmt_calls (int pos, int forall, int stdnext) static
Definition at line 4870 of file outconv.c.
References FT_NSCALL, FT_SCALL, glist(), i, pos, and put_calls().
Referenced by conv_forall().
at_local_mode()
static LOGICAL at_local_mode (int ast) static
Definition at line 5055 of file outconv.c.
References ast, astb, getsymbol(), ASTB::i1, mk_id(), sptr, and src.
Referenced by eliminate_barrier().
check_subscript()
static int check_subscript (int ast, int value) static
Definition at line 1247 of file outconv.c.
References T_LIST::asd, ASD_NDIM, ASD_SUBS, ast, get_int_cval(), ss, val, and value().
Referenced by full_dimension().
check_value()
static int check_value (int ast, int value) static
Definition at line 1266 of file outconv.c.
References ast, get_int_cval(), val, and value().
Referenced by _sect(), and full_dimension().
collapse_allocates()
static void collapse_allocates (LOGICAL bDescr) static
Definition at line 4649 of file outconv.c.
References collapse, COLLAPSE_DELETE, COLLAPSE_DESCR, COLLAPSE_STDALLOC, COLLAPSE_STDDEALLOC, and delete_stmt().
Referenced by collapse_arrays(), and convert_output().
collapse_arrays()
static void collapse_arrays (void) static
Definition at line 4299 of file outconv.c.
References ast, astb, collapse, collapse_allocates(), COLLAPSE_ASTARR, COLLAPSE_ASTSCLR, COLLAPSE_DELETE, collapse_loops(), DBGBIT, DDTG, delete_collapse(), dump_flowgraph(), dump_loops(), dump_std(), FALSE, find_collapse_allocs(), find_collapse_defs(), find_collapse_uses(), find_descrs(), gbl, hlopt_end(), hlopt_init(), memsym_of_ast(), mk_id(), report_collapse(), sym_get_scalar(), and SYMNAME.
Referenced by convert_output().
collapse_loops()
static void collapse_loops (void) static
Definition at line 4533 of file outconv.c.
References A_STDP, assert, ast, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), collapse, COLLAPSE_ASTARR, COLLAPSE_ASTSCLR, COLLAPSE_DELETE, COLLAPSE_STDALLOC, COLLAPSE_STDDEALLOC, def, DEF_DU, DEF_NEXT, DEF_STD, DU_TAG::next, NME_DEF, std, STD_AST, use, DU_TAG::use, and USE_STD.
Referenced by collapse_arrays().
conv_allocate()
static int conv_allocate (int std) static
Definition at line 3009 of file outconv.c.
References add_arg(), ADD_LWBD, add_stmt_after(), ALIGNG, T_LIST::asd, ASD_SUBS, FL::avl, FL::base, tbl::base, begin_call(), check_member(), clist(), FLG::debug, delete_stmt(), dest, DTY, emit_alnd_secd(), TABLE::f1, TABLE::f3, fl, flg, FREE, gbl, get_gbase(), get_tbl(), i, init_fl(), interr(), list, lower(), mk_id(), mk_member(), mkRteRtnNm(), plist(), RTE_ptrcp, set_typed_alloc(), sptr, sptr_of_subscript(), src, std, STD_AST, STD_IGNORE, STD_NEXT, STD_PREV, stmt, sym_mkfunc_nodesc(), TRUE, want_descriptor_anyway(), and XBIT.
Referenced by convert_statements().
conv_deallocate()
static int conv_deallocate (int std) static
Definition at line 2919 of file outconv.c.
References add_stmt_before(), argt, ARGT_ARG, ast, tbl::avl, tbl::base, check_member(), delete_stmt(), DT_INT, TABLE::f1, TABLE::f3, glist(), i, interr(), list, mk_argt(), mk_cval(), mk_func_node(), mk_id(), mkRteRtnNm(), nargs, RTE_freen, sptr, std, STD_AST, STD_IGNORE, STD_NEXT, STD_PREV, sym_mkfunc(), and SYMNAME.
Referenced by convert_statements().
conv_forall()
int conv_forall (int std)
Definition at line 3428 of file outconv.c.
References A_ARGCNTG, A_OPTYPEG, add_arg(), add_lbnd(), add_mask_calls(), add_stmt_after(), add_stmt_before(), add_stmt_calls(), argt, ARGT_ARG, assert, ast, ast_to_comment(), astb, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, begin_call(), ASTB::bnd, CTYPE::c_inc, CTYPE::c_init, CTYPE::cb_block, CTYPE::cb_do, CTYPE::cb_enddo, CTYPE::cb_inc, CTYPE::cb_init, cnt, conv_forall(), conv_fused_forall(), delete_stmt(), dim, dt, DT_INT, DT_LOG, DTY, CTYPE::endifast, FALSE, find_mask_calls_pos(), find_stmt_calls_pos(), FT_CYCLIC, get_int_cval(), get_temp(), glist(), i, ASTB::i0, ASTB::i1, CTYPE::ifast, index_var, CTYPE::inner_cyclic, insert_endmask(), insert_mask(), is_same_mask_in_fused(), left_subscript_ast(), CTYPE::lhs, lhs, lhs_dim(), pure_gbl::local_mode, MAXSUBS, memsym_of_ast(), mk_argt(), mk_assn_stmt(), mk_binop(), mk_func_node(), mk_id(), mk_stmt(), n, itemlist::nitem, no_effect_forall(), normalize_bounds(), OP_ADD, OP_DIV, OP_LE, OP_LOR, OP_SUB, pos, rewrite_asn(), search_pure_function(), arg_gbl::std, std, STD_ACCEL, STD_AST, STD_KERNEL, STD_LINENO, STD_NEXT, STD_PAR, STD_PREV, STD_TASK, STD_ZTRIP, stmt, stride, sub_lbnd(), sym_of_ast(), TRUE, TY_INT8, XBIT, zero, and ASTB::zero.
Referenced by conv_forall(), and convert_forall().
conv_fused_forall()
static void conv_fused_forall (int std, int ast, int * stdnextp) static
Definition at line 3175 of file outconv.c.
References add_stmt_before(), ast, ccff_info(), delete_stmt(), FALSE, FT_FUSEDSTD, FT_NFUSE, gbl, i, insert_endmask(), insert_mask(), is_same_mask(), MAXSUBS, MSGFUSE, NULL, rewrite_asn(), std, STD_AST, STD_LINENO, STD_NEXT, STD_PREV, and stmt.
Referenced by conv_forall().
convert_forall()
void convert_forall (void)
Definition at line 200 of file outconv.c.
References ast, check_region(), conv_forall(), convert_omp_workshare(), early_flow_fini(), early_flow_init(), f90_fini_pointsto(), FALSE, flg, forall_dependency_analyze(), arg_gbl::inforall, init_region(), FLG::opt, points_to(), FLG::smp, std, STD_AST, STD_NEXT, TRUE, and XBIT.
convert_omp_workshare()
static void convert_omp_workshare (void) static
Definition at line 302 of file outconv.c.
References A_TKNG, add_stmt_after(), add_stmt_before(), ast, ast_to_comment(), FLANG_FALLTHROUGH, gen_endsingle(), gen_pdo(), IN_CRITICAL, IN_PARALLEL, IN_PDO, IN_SINGLE, IN_WRKSHR, mk_stmt(), NO_WRKSHR, sptr, std, STD_AST, STD_NEXT, STD_PAR, STD_PREV, and sym_of_ast().
Referenced by convert_forall().
convert_output()
void convert_output (void)
Definition at line 91 of file outconv.c.
References FTB::base, collapse_allocates(), collapse_arrays(), comm_fini(), convert_simple(), convert_statements(), convert_template_instance(), eliminate_barrier(), end_collapse(), flg, FORALL_AREA, FREE, free_brtbl(), freearea(), ftb, init_collapse(), FLG::opt, transform_wrapup(), TRUE, and XBIT.
convert_simple()
static void convert_simple (void) static
Definition at line 1222 of file outconv.c.
References _simple_replacements(), A_STDP, ast, ast_rewrite(), ast_traverse(), ast_unvisit(), ast_visit(), beforestd, NULL, std, STD_AST, and STD_NEXT.
Referenced by convert_output().
convert_statements()
static void convert_statements (void) static
Definition at line 2573 of file outconv.c.
References A_TKNG, assert, ast, conv_allocate(), conv_deallocate(), free_tbl(), init_tbl(), set_descriptor_sc(), std, STD_AST, STD_NEXT, and unvisit_every_sptr().
Referenced by convert_output().
convert_template_instance()
static void convert_template_instance (void) static
Definition at line 2645 of file outconv.c.
References _mark_descr(), a, A_ARGCNTG, A_ARGCNTP, add_stmt_before(), args, ARGT_ARG, ARGT_CNT, ast, ast_traverse(), ast_unvisit(), ast_visit(), astb, collapse, delete_stmt(), DT_INT, DT_PTR, dummy, STB::firstosym, FLANG_FALLTHROUGH, get_byte_len(), get_int_cval(), get_kind(), ASTB::i0, ASTB::k0, kind, len, lhs, memsym_of_ast(), mk_id(), mk_stmt(), mk_unop(), mkRteRtnNm(), NULL, OP_VAL, rank, RTE_instance, RTE_set_intrin_type, RTE_template, RTE_template1, RTE_template1v, RTE_template2, RTE_template2v, RTE_template3, RTE_template3v, size_of(), sptr, stb, std, STD_AST, STD_NEXT, STD_PREV, sym_mkfunc(), sym_of_ast(), and SYMNAME.
Referenced by convert_output().
delete_collapse()
static void delete_collapse (int ci) static
Definition at line 4434 of file outconv.c.
References COLLAPSE_DELETE, and TRUE.
Referenced by collapse_arrays(), find_collapse_allocs(), find_collapse_defs(), and find_collapse_uses().
early_flow_fini()
static void early_flow_fini (void) static
Definition at line 142 of file outconv.c.
References optshrd_end(), and optshrd_fend().
Referenced by convert_forall().
early_flow_init()
static void early_flow_init (void) static
Definition at line 133 of file outconv.c.
References findloop(), flow(), flowgraph(), and optshrd_init().
Referenced by convert_forall().
eliminate_barrier()
static void eliminate_barrier (void) static
Definition at line 5076 of file outconv.c.
References ast, at_local_mode(), delete_stmt(), FALSE, FLANG_FALLTHROUGH, std, STD_AST, STD_LABEL, STD_LAST, STD_PREV, and TRUE.
Referenced by convert_output().
end_collapse()
static void end_collapse (void) static
Definition at line 4373 of file outconv.c.
References collapse, and FREE.
Referenced by convert_output().
enter_local_mode()
void enter_local_mode (int std)
Definition at line 4888 of file outconv.c.
References add_stmt_before(), ast, astb, dest, DT_INT, getsymbol(), ASTB::i1, mk_id(), mk_stmt(), sptr, src, and std.
exit_local_mode()
void exit_local_mode (int std)
Definition at line 4916 of file outconv.c.
References add_stmt_before(), ast, dest, DT_INT, getsymbol(), mk_id(), mk_stmt(), sptr, src, and std.
find_calls_pos()
static void find_calls_pos (int std, int forall, int must_pos) static
Definition at line 4746 of file outconv.c.
References assert, ast, find_calls_pos(), FT_CALL_CALL, FT_CALL_NCALL, FT_CALL_POS, glist(), i, pos, position_finder(), std, and STD_AST.
Referenced by find_calls_pos(), find_mask_calls_pos(), and find_stmt_calls_pos().
find_collapse_allocs()
static void find_collapse_allocs (void) static
Definition at line 4382 of file outconv.c.
References A_TKNG, ast, BZERO, collapse, COLLAPSE_ASTARR, COLLAPSE_DELETE, COLLAPSE_STDALLOC, COLLAPSE_STDDEALLOC, delete_collapse(), NEED, std, STD_AST, and STD_NEXT.
Referenced by collapse_arrays().
find_collapse_defs()
static void find_collapse_defs (void) static
Definition at line 4442 of file outconv.c.
References collapse, COLLAPSE_ASTARR, COLLAPSE_DELETE, COLLAPSE_LP, COLLAPSE_STDALLOC, COLLAPSE_STDDEALLOC, def, DEF_ADDR, DEF_FG, DEF_LHS, DEF_NEXT, DEF_STD, delete_collapse(), FG_LOOP, LP_CALLFG, and NME_DEF.
Referenced by collapse_arrays().
find_collapse_uses()
static void find_collapse_uses (void) static
Definition at line 4484 of file outconv.c.
References assert, collapse, COLLAPSE_ASTARR, COLLAPSE_DELETE, COLLAPSE_LP, COLLAPSE_STDALLOC, COLLAPSE_STDDEALLOC, def, DEF_DU, DEF_NEXT, DEF_STD, delete_collapse(), FG_LOOP, is_parent_loop(), DU_TAG::next, NME_DEF, use, DU_TAG::use, USE_ADDR, and USE_FG.
Referenced by collapse_arrays().
find_descrs()
static void find_descrs (void) static
Definition at line 4589 of file outconv.c.
References A_ARGCNTG, arg, args, ARGT_ARG, ast, ast_traverse(), ast_unvisit(), ast_visit(), collapse, COLLAPSE_ASTARR, COLLAPSE_DELETE, COLLAPSE_DESCR, COLLAPSE_STDALLOC, COLLAPSE_STDDEALLOC, global_astArrdsc, global_flag, look_for_descriptor(), mk_id(), nargs, NULL, src, std, STD_AST, STD_NEXT, and TRUE.
Referenced by collapse_arrays().
find_mask_calls_pos()
static void find_mask_calls_pos (int forall) static
Definition at line 4774 of file outconv.c.
References find_calls_pos(), FT_MCALL, FT_NMCALL, glist(), and i.
Referenced by conv_forall().
find_max_of_mask_calls_pos()
static int find_max_of_mask_calls_pos (int forall) static
Definition at line 4802 of file outconv.c.
References assert, ast, FT_CALL_POS, FT_MCALL, FT_NMCALL, glist(), i, max, pos, and STD_AST.
Referenced by is_same_mask_in_fused().
find_stmt_calls_pos()
static void find_stmt_calls_pos (int forall, int mask_pos) static
Definition at line 4788 of file outconv.c.
References find_calls_pos(), FT_NSCALL, FT_SCALL, glist(), and i.
Referenced by conv_forall().
forall_dependency()
static void forall_dependency (int std) static
Definition at line 3975 of file outconv.c.
References add_fg(), add_stmt_after(), add_stmt_before(), close_pragma(), DEPENDENCY_CAUSE, DT_LOG, fg, FG_LPREV, FG_STDFIRST, FG_STDLAST, flg, FT_CYCLIC, FT_HEADER, get_temp_forall(), get_temp_forall2(), header(), is_dependent(), is_mask_call_dependent(), is_pointer(), is_stmt_call_dependent(), CTYPE::lhs, lhs, lhs_needtmp(), lineno, mk_stmt(), move_mask_calls(), open_pragma(), FLG::opt, par, reference_for_temp(), remove_mask_calls(), remove_stmt_calls(), replace_loop_on_fuse_list(), report_comm(), sptr, std, STD_AST, STD_FG, STD_LINENO, STD_PAR, STD_TASK, sym_of_ast(), task, un_fuse(), and XBIT.
Referenced by forall_dependency_analyze().
forall_dependency_analyze()
void forall_dependency_analyze (void)
Definition at line 149 of file outconv.c.
References ast, ast_to_comment(), forall_dependency(), freearea(), NULL, set_descriptor_sc(), std, STD_AST, STD_DELETE, STD_NEXT, TEMP_AREA, and templist.
Referenced by convert_forall().
full_dimension()
static int full_dimension (int astlower, int astupper, int aststride, int dim) static
Definition at line 1286 of file outconv.c.
References A_OPTYPEG, check_subscript(), check_value(), dim, get_global_extent_index(), get_global_lower_index(), get_global_upper_index(), OP_ADD, and OP_SUB.
Referenced by _sect().
gen_endsingle()
static void gen_endsingle (int std, int single, int presinglebarrier) static
Definition at line 283 of file outconv.c.
References A_STDG, add_stmt_after(), add_stmt_before(), mk_stmt(), std, STD_AST, and STD_PREV.
Referenced by convert_omp_workshare().
gen_pdo()
static int gen_pdo (int do_ast) static
Definition at line 259 of file outconv.c.
References A_ORDEREDP, A_SCHED_TYPEP, ast, and mk_stmt().
Referenced by convert_omp_workshare().
gen_set_len_ast()
int gen_set_len_ast (int ast, SPTR ddesc, int sz)
This routine assigns a size to a descriptor's length field.
Parameters
ast is the expression that has the descriptor (e.g., an A_ID, A_MEM, etc.).
ddesc is the symbol table pointer of the descriptor.
sz is the AST representing the size.
Returns
the resulting assignment AST.
Definition at line 2217 of file outconv.c.
References _sd_member(), ast, astb, ASTB::bnd, check_member(), ASTB::dtype, mk_assn_stmt(), mk_id(), and sz.
Referenced by rewrite_allocatable_assignment(), and rewrite_calls().
get_temp_forall2()
static int get_temp_forall2 (int forall_ast, int subscr_ast, int alloc_stmt, int dealloc_stmt, int dty, int ast_dty) static
Definition at line 3803 of file outconv.c.
References add_loop_hd(), T_LIST::asd, ASD_NDIM, ast_to_comment(), T_LIST::astd, T_LIST::cvlen, DBGBIT, DDTG, dstd(), DTY, fg, FG_LOOP, FG_STDLAST, gbl, get_forall_subscr(), GET_T_LIST, lp, LP_MEXITS, LP_PARENT, MAXSUBS, mk_forall_sptr(), mk_id(), mk_mem_allocate(), mk_mem_deallocate(), ndim, par, q, rdilts(), same_forall_size(), SYMUTL::sc, set_descriptor_sc(), sptr, std, STD_ACCEL, STD_AST, STD_FG, STD_PAR, STD_PREV, STD_RESCOPE, STD_TASK, subscr, symutl, templist, TY_CHAR, and wrilts().
Referenced by forall_dependency().
have_preheader()
static LOGICAL have_preheader (int l) static
Definition at line 5907 of file outconv.c.
References FALSE, FG_LOOP, FG_PRED, FG_SUCC, h, LP_HEAD, n, pred, PSI_NEXT, PSI_NODE, PSI_P_NULL, and TRUE.
Referenced by sfloat().
hoist_stmt()
void hoist_stmt (int std, int fg, int l)
Definition at line 5794 of file outconv.c.
References is_dealloc_std(), LP_MEXITS, sdrop_stmt(), sfloat_stmt2(), std, and STD_FG.
Referenced by invar_motion(), and is_hoistable().
init_collapse()
static void init_collapse (void) static
Definition at line 4288 of file outconv.c.
References collapse, and NEW.
Referenced by convert_output().
inline_RTE_set_type()
LOGICAL inline_RTE_set_type (int ddesc, int sdesc, int stmt, int after, DTYPE src_dtype, int astmem)
Definition at line 2238 of file outconv.c.
References _sd_member(), add_stmt_after(), add_stmt_before(), after, array_element_dtype(), astb, ASTB::bnd, check_member(), ASTB::dtype, FALSE, is_array_dtype(), mk_assn_stmt(), mk_id(), mk_unop(), OP_LOC, stdx, stmt, TRUE, and XBIT.
Referenced by check_alloc_ptr_type(), check_pointer_type(), and transform_call().
insert_assign()
static void insert_assign (int lhs, int rhs, int beforestd) static
Definition at line 1351 of file outconv.c.
References add_stmt_before(), beforestd, lhs, MKASSN, STD_ACCEL, STD_KERNEL, STD_PAR, and STD_TASK.
Referenced by _RTE_ba(), _sect(), and _template().
is_call_dependent()
static LOGICAL is_call_dependent (int std, int forall, int lhs) static
Definition at line 4150 of file outconv.c.
References A_ARGCNTG, argt, ARGT_ARG, assert, ast, FALSE, FT_CALL_CALL, FT_CALL_NCALL, glist(), i, is_call_dependent(), is_dependent(), lhs, nargs, std, STD_AST, and TRUE.
Referenced by is_call_dependent(), is_mask_call_dependent(), and is_stmt_call_dependent().
is_mask_call_dependent()
static LOGICAL is_mask_call_dependent (int forall, int lhs) static
Definition at line 4132 of file outconv.c.
References FALSE, FT_MCALL, FT_NMCALL, glist(), i, is_call_dependent(), lhs, and TRUE.
Referenced by forall_dependency().
is_parent_loop()
static LOGICAL is_parent_loop (int lpParent, int lp) static
Definition at line 4521 of file outconv.c.
Referenced by find_collapse_uses().
is_pointer()
static LOGICAL is_pointer (int ast) static
Definition at line 3948 of file outconv.c.
References ast, FALSE, and TRUE.
Referenced by forall_dependency(), and handle_seq_section().
is_pointer_dependent()
LOGICAL is_pointer_dependent (int sptr, int sptr1)
Definition at line 4237 of file outconv.c.
References DTY, FALSE, sptr, and TRUE.
is_same_mask()
static LOGICAL is_same_mask (int expr, int expr1) static
Definition at line 3238 of file outconv.c.
References A_OPTYPEG, argt, ARGT_ARG, T_LIST::asd, ASD_NDIM, ASD_SUBS, assert, ast, dim, FALSE, get_int_cval(), interr(), is_same_array_alignment(), is_same_mask(), memsym_of_ast(), mkRteRtnNm(), ndim, r, RTE_islocal_idx, sptr, sym_of_ast(), SYMNAME, and TRUE.
Referenced by conv_fused_forall(), is_same_mask(), and is_same_mask_in_fused().
is_same_mask_in_fused()
static LOGICAL is_same_mask_in_fused (int std, int * pos) static
Definition at line 3345 of file outconv.c.
References assert, ast, FALSE, find_max_of_mask_calls_pos(), FT_CYCLIC, FT_FUSEDSTD, FT_MGET, FT_NFUSE, FT_NMGET, glist(), i, is_same_mask(), max, pos, position_finder(), src, std, STD_AST, and TRUE.
Referenced by conv_forall().
is_stmt_call_dependent()
static LOGICAL is_stmt_call_dependent (int forall, int lhs) static
Definition at line 4114 of file outconv.c.
References FALSE, FT_NSCALL, FT_SCALL, glist(), i, is_call_dependent(), lhs, and TRUE.
Referenced by forall_dependency().
lhs_dim()
static int lhs_dim (int forall, int astli) static
Definition at line 3152 of file outconv.c.
References T_LIST::asd, ASD_NDIM, ASTLI_SPTR, FT_CYCLIC, i, CTYPE::idx, left_subscript_ast(), CTYPE::lhs, lhs, and ndim.
Referenced by conv_forall().
linearize_arrays()
void linearize_arrays (void)
Definition at line 5484 of file outconv.c.
References _linearize_all(), _linearize_func(), _linearize_sub(), ast, ast_rewrite(), ast_traverse(), ast_unvisit(), ast_visit(), deferred_to_pointer(), dummy, FALSE, linearize_any, NULL, std, STD_AST, and STD_NEXT.
look_for_descriptor()
static void look_for_descriptor (int ast, int * unused) static
Definition at line 4580 of file outconv.c.
References ast, global_astArrdsc, and global_flag.
Referenced by find_descrs().
move_mask_calls()
static void move_mask_calls (int forall) static
Definition at line 4184 of file outconv.c.
References FTB::base, BCOPY, FT_MCALL, FT_MGET, FT_NMCALL, FT_NMGET, FT_NSCALL, FT_NSGET, FT_SCALL, FT_SGET, ftb, and mk_ftb().
Referenced by forall_dependency().
needs_linearization()
static LOGICAL needs_linearization (int sptr) static
Definition at line 5136 of file outconv.c.
References ADD_DEFER, ADD_NOBOUNDS, ALIGNG, DTY, F77OUTPUT, FALSE, sptr, TRUE, and use_offset().
Referenced by _linearize(), and _linearize_func().
no_effect_forall()
static LOGICAL no_effect_forall (int std) static
Definition at line 518 of file outconv.c.
References count, delete_stmt(), FALSE, FT_FUSEDSTD, FT_NFUSE, i, std, STD_AST, and TRUE.
Referenced by conv_forall().
position_finder()
static int position_finder (int forall, int ast) static
Definition at line 4717 of file outconv.c.
References ast, ASTLI_NEXT, ASTLI_SPTR, contains_ast(), i, mk_id(), n, and pos.
Referenced by find_calls_pos(), and is_same_mask_in_fused().
put_calls()
static void put_calls (int pos, int std, int stdnext) static
Definition at line 4827 of file outconv.c.
References add_stmt_before(), assert, ast, delete_stmt(), FT_CALL_CALL, FT_CALL_NCALL, FT_CALL_POS, glist(), i, pure_gbl::local_mode, pos, put_calls(), std, STD_AST, and transform_call().
Referenced by add_mask_calls(), add_stmt_calls(), and put_calls().
remove_mask_calls()
static void remove_mask_calls (int forall) static
Definition at line 4199 of file outconv.c.
References FTB::base, BCOPY, clist(), FT_MCALL, FT_MGET, FT_NMCALL, FT_NMGET, ftb, and mk_ftb().
Referenced by forall_dependency().
remove_stmt_calls()
static void remove_stmt_calls (int forall) static
Definition at line 4215 of file outconv.c.
References FTB::base, BCOPY, clist(), FT_NSCALL, FT_NSGET, FT_SCALL, FT_SGET, ftb, and mk_ftb().
Referenced by forall_dependency().
replace_loop_on_fuse_list()
static void replace_loop_on_fuse_list (int oldloop, int maskloop) static
Definition at line 3780 of file outconv.c.
References FT_FUSEDSTD, FT_HEADER, FT_NFUSE, i, and STD_AST.
Referenced by forall_dependency().
report_collapse()
static void report_collapse (int lp) static
Definition at line 4662 of file outconv.c.
References ccff_info(), collapse, COLLAPSE_DELETE, COLLAPSE_LP, FG_STDFIRST, gbl, lineno, lp, LP_CHILD, LP_HEAD, LP_SIBLING, MSGOPT, NULL, report_collapse(), std, STD_LINENO, and STD_PREV.
Referenced by collapse_arrays(), and report_collapse().
restore_hoist_stmt()
void restore_hoist_stmt (int lp)
Definition at line 5811 of file outconv.c.
References FG_LNEXT, FG_LPREV, FG_STDFIRST, FG_STDLAST, lp, LP_DSTDF, LP_HEAD, LP_HSTDF, LP_TAIL, next, prev, std, STD_FG, STD_NEXT, and STD_PREV.
Referenced by invar_end().
sdrop_stmt()
static void sdrop_stmt (int std, int fg, int l) static
Definition at line 5701 of file outconv.c.
References DBGBIT, fg, FG_STDFIRST, FG_STDLAST, gbl, LP_DSTDF, next, prev, std, STD_NEXT, and STD_PREV.
Referenced by hoist_stmt().
search_pure_function()
static void search_pure_function (int stdfirst, int stdlast) static
Definition at line 4936 of file outconv.c.
References ast, cnt, lhs, std, STD_AST, STD_NEXT, and transform_pure_function().
Referenced by conv_forall().
sectfloat()
void sectfloat (void)
Definition at line 6147 of file outconv.c.
References astb, BZERO, d, DBGBIT, DEF_NEXT, DEF_STD, dom, dumpdefs(), dumpfgraph(), dumploops(), dumpnmes(), dumpuses(), fg, FG_CTLEQUIV, FG_DOM, FG_LOOP, FG_PDOM, findlooptopsort(), STB::firstusym, flg, flow(), flowgraph(), FREE, induction_end(), induction_init(), is_dominator(), is_post_dominator(), loopdeflist, LP_CHILD, LP_HEAD, LP_SIBLING, NEW, OPT::nloops, NME_DEF, nmeb, OPT::num_nodes, opt, optshrd_end(), optshrd_fend(), optshrd_finit(), optshrd_init(), postdominators(), reorderloops(), s, sfloat(), stb, std, stddeflist, syminfo, and FLG::x.
sectinline()
void sectinline (void)
Definition at line 2503 of file outconv.c.
References _ptrassign(), _sect(), _template(), A_OPTYPEG, ast, ast_to_comment(), beforestd, FALSE, FTYPE_I8, FTYPE_MASK, FTYPE_SECT, FTYPE_TEMPLATE, FTYPE_TEMPLATE1, FTYPE_TEMPLATE1V, FTYPE_TEMPLATE2, FTYPE_TEMPLATE2V, FTYPE_TEMPLATE3, FTYPE_TEMPLATE3V, getF90TmplSectRtn(), i, std, STD_AST, STD_NEXT, SYMNAME, and TRUE.
sfloat()
static void sfloat (int l) static
Definition at line 5946 of file outconv.c.
References _check_clean(), A_ARGCNTG, add_arrnme(), add_def_syminfo(), always_executed, args, ARGT_ARG, ast, ast_traverse(), ast_unvisit(), ast_visit(), chk_assign, clean, d, DEF_NEXT, DEF_NM, FALSE, fg, FG_CTLEQUIV, FG_NEXT, FG_STDFIRST, FG_STDLAST, gbl, getF90TmplSectRtn(), have_preheader(), i, is_live_in(), is_live_out(), lhs, loopdeflist, LP_CALLFG, LP_CHILD, LP_FG, LP_HEAD, LP_SIBLING, NME_NM, NME_SYM, NOSYM, NT_VAR, NULL, sfloat(), sfloat_stmt(), sptr, std, STD_AST, STD_NEXT, stddeflist, syminfo, SYMNAME, and XBIT.
Referenced by sectfloat(), and sfloat().
sfloat_stmt()
static void sfloat_stmt (int std, int fg, int l) static
Definition at line 5643 of file outconv.c.
References DBGBIT, fg, FG_LNEXT, FG_LPREV, FG_STDFIRST, FG_STDLAST, gbl, LP_HEAD, next, prev, std, STD_FG, STD_NEXT, and STD_PREV.
Referenced by sfloat().
sfloat_stmt2()
static void sfloat_stmt2 (int std, int fg, int l) static
Definition at line 5749 of file outconv.c.
References DBGBIT, fg, FG_STDFIRST, FG_STDLAST, gbl, LP_HSTDF, next, prev, std, STD_NEXT, and STD_PREV.
Referenced by hoist_stmt().
size_shape()
static int size_shape (int shape, int i) static
Definition at line 747 of file outconv.c.
References a, args, astb, ASTB::bnd, STB::dt_int, DT_LOG, ASTB::dtype, i, mk_binop(), mk_convert(), mk_merge(), OP_ADD, OP_DIV, OP_GE, OP_SUB, SHD_LWB, SHD_STRIDE, SHD_UPB, stb, STB::user, and ASTB::zero.
Referenced by _PDsize().
symvalue()
static int symvalue (int ast, char c, int num, int * ptemp, int var, int sdsc) static
Definition at line 1057 of file outconv.c.
References a, add_stmt_before(), ast, astb, beforestd, ASTB::bnd, ASTB::dtype, getnewccsymf(), mk_id(), mk_stmt(), newsymnum, num, STD_ACCEL, STD_KERNEL, STD_PAR, STD_TASK, T_LIST::temp, and value().
Referenced by _sect(), and _template().
transform_pure_function()
static int transform_pure_function (int expr, int std) static
Definition at line 4979 of file outconv.c.
References A_ARGCNTG, A_OPTYPEG, A_OPTYPEP, argt, ARGT_ARG, d, i, interr(), mk_binop(), mk_convert(), mk_func_node(), mk_member(), mk_paren(), mk_unop(), nargs, r, std, transform_call(), and transform_pure_function().
Referenced by search_pure_function(), and transform_pure_function().
use_offset()
static LOGICAL use_offset (int sptr) static
Definition at line 5118 of file outconv.c.
References DTYG, FALSE, NO_CHARPTR, NO_DERIVEDPTR, NO_PTR, sptr, TRUE, and TY_CHAR.
Referenced by _linearize(), _linearize_func(), and needs_linearization().
value()
static int value (int ast) static
Definition at line 1043 of file outconv.c.
References A_OPTYPEG, ast, OP_BYVAL, and OP_VAL.
Referenced by __c_mset1(), __c_mset16(), __c_mset2(), __c_mset4(), __c_mset8(), __ecvt(), __fort_atoxi32(), __fortio_ecvt(), __fortio_set_asy_rw(), __io_set_errno(), _ptrassign_set(), acc_display_macros(), add_generic_argument(), add_global_define(), ast_cval(), atoxi(), check_skip(), check_subscript(), check_value(), constant_stride(), conv_int8(), decode_expression_op(), defer_put_kind_type_param(), dwarf_attr_name(), dwarf_emission_name(), dwarf_encoding_name(), dwarf_form_name(), dwarf_lang_name(), dwarf_stack_op_name(), dwarf_table_name(), dwarf_tag_name(), dwarf_virtuality_name(), ENTF90(), eval_transfer(), fpp_display_macros(), gen_sret_expr(), gen_switch(), get_acon3(), get_vcon(), get_vconi(), getcon(), getntstring(), getstring(), hashcon(), inlist(), insert_llvm_memset(), intern_const_int(), is_set(), ll_add_global_debug(), ll_get_const_addrspacecast(), ll_get_const_bitcast(), ll_get_const_int(), ll_get_md_i1(), ll_get_md_i32(), ll_get_md_i64(), ll_get_md_value(), lldbg_create_module_flag_mdnode(), lldbg_emit_global_variable(), lldbg_encode_expression_arg(), lldbg_function_end(), llmd_add_i1(), llmd_add_i32(), llmd_add_i64(), llmd_add_i64_lsb_msb(), llmd_add_INT64(), llmd_add_string(), llmd_add_value(), lower_push(), parse_arguments(), pgio_ecvt(), plabel(), process_string(), push(), put_kind_type_param(), read_label(), reference_for_temp(), register_action_map_arg(), rewrite_func_ast(), set_distance_to(), set_xflag_value(), symvalue(), tobinary(), tobinary64(), write_mdfield(), xmlintentity(), and xmlintout().
want_descriptor_anyway()
LOGICAL want_descriptor_anyway (int sptr)
Return TRUE if we need to initialize the descriptor for this symbol because perhaps this is a host subroutine, and the internal subprograms will need the descriptor, or perhaps -g is set.
Definition at line 932 of file dpm_out.c.
References ADD_ASSUMSHP, ADD_DEFER, ALIGNG, FLG::debug, DISTG, DTY, FALSE, flg, gbl, sptr, TRUE, and XBIT.
Referenced by conv_allocate(), desc_need_arrays(), prepare_for_astout(), and wrap_symbol().
Variable Documentation
always_executed
int always_executed static
Definition at line 5545 of file outconv.c.
Referenced by _check_clean(), and sfloat().
avail
int avail
Definition at line 4282 of file outconv.c.
Referenced by eval_transfer().
base
COLLAPSE* base
Definition at line 4280 of file outconv.c.
Referenced by _PDsize(), _pghpf_bound(), and _pghpf_size().
beforestd
int beforestd static
Definition at line 129 of file outconv.c.
Referenced by _ptrassign(), _ptrassign_copy(), _ptrassign_set(), _ptrassign_set_ast(), _RTE_ba(), _sect(), _template(), convert_simple(), insert_assign(), sectinline(), and symvalue().
chk_assign
int chk_assign static
Definition at line 5546 of file outconv.c.
Referenced by _check_clean(), and sfloat().
chk_subscr
int chk_subscr static
Definition at line 5547 of file outconv.c.
Referenced by _check_clean().
clean
int clean static
Definition at line 5544 of file outconv.c.
Referenced by _check_clean(), and sfloat().
struct { ... } collapse
Referenced by _dmp_doif(), collapse_allocates(), collapse_arrays(), collapse_loops(), convert_template_instance(), emit_kopy_in(), emit_secd(), end_collapse(), ENTFTN(), find_collapse_allocs(), find_collapse_defs(), find_collapse_uses(), find_descrs(), init_collapse(), report_collapse(), and void().
global_astArrdsc
int global_astArrdsc static
Definition at line 4577 of file outconv.c.
Referenced by find_descrs(), and look_for_descriptor().
global_flag
int global_flag static
Definition at line 4577 of file outconv.c.
Referenced by find_descrs(), and look_for_descriptor().
linearize_any
LOGICAL linearize_any static
Definition at line 5166 of file outconv.c.
Referenced by _linearize(), and linearize_arrays().
loopdeflist
int* loopdeflist static
Definition at line 5536 of file outconv.c.
Referenced by sectfloat(), and sfloat().
lp
int lp
Definition at line 4283 of file outconv.c.
Referenced by get_temp_forall2(), is_parent_loop(), report_collapse(), and restore_hoist_stmt().
newsymnum
int newsymnum static
Definition at line 130 of file outconv.c.
Referenced by _sect(), and symvalue().
size
int size
Definition at line 4281 of file outconv.c.
Referenced by _pghpf_size().
std
int std
Definition at line 4284 of file outconv.c.
Referenced by __gen_conditional_dealloc(), _constructf90(), _dump_std(), _find_rhs_def_conflict(), _rewrite_scalar_fuctions(), _transform_func(), add_assignment_before(), add_bound_assignments(), add_end_presence(), add_firstprivate_assn(), add_lhs_nme(), add_loop_hd(), add_presence(), add_ptr_assign(), add_single_loop_exit(), add_stmt(), add_stmt_after(), add_stmt_before(), addssassignments(), all_stds(), alldefs_allocsafe(), alloc2ast(), alloc_char_temp(), allocate_lhs_if_needed(), assign_bounds(), ast_to_comment(), bblock(), call_analyze(), check_dependence_ido(), check_do_term(), check_doconcurrent(), check_inner_uses(), check_moved(), check_outer_defs(), check_region(), check_subprogram(), chk_block(), clean_flags(), collapse_add(), collapse_loops(), comm_analyze(), comm_generator(), component_init_allocd_auto(), compute_invariant(), contains_alloc(), conv_allocate(), conv_deallocate(), conv_forall(), conv_fused_forall(), convert_forall(), convert_omp_workshare(), convert_simple(), convert_statements(), convert_template_instance(), copy_arg_to_seq_tmp(), copy_desc_to_bnds_vars(), copy_scalar_intent_in(), copy_surrogate_to_bnds_vars(), copy_to_scalar(), cr_block(), create_nmes(), dbg_print_stmts(), delete_stmt(), do_end(), dotemp(), dump_std(), eliminate_alloc(), eliminate_barrier(), eliminate_bnds(), eliminate_copy(), eliminate_gather(), eliminate_redundant(), eliminate_rt(), eliminate_sect(), eliminate_shift(), eliminate_start(), eliminate_unused_variables(), emit_alnd_secd(), emit_copy_section(), emit_gatherx(), emit_get_scalar(), emit_get_scalar_sub(), emit_overlap(), emit_permute_section(), emit_scatterx(), emit_scatterx_gatherx(), emit_sum_scatterx(), end_workshare(), enter_lexical_block(), enter_local_mode(), exit_lexical_block(), exit_local_mode(), export_one_std(), extractor_possible(), fill_ast(), find_allocatable_assignment(), find_calls_pos(), find_collapse_allocs(), find_descrs(), find_get_scalar(), find_lp(), findssexprsfg(), fix_guard_forall(), forall_dependency(), forall_dependency_analyze(), forall_dependency_scalarize(), forall_init(), forall_make_same_idx(), forall_opt1(), fuse_forall(), gen_alloc_mbr(), gen_alloc_mem_initialize_for_sym(), gen_alloc_mem_initialize_for_sym2(), gen_allocated_check(), gen_and_assoc_tmp_ptr(), gen_automatic_reallocation(), gen_bounds_assignments(), gen_conditional_dealloc_for_sym(), gen_contig_check(), gen_dealloc_for_sym(), gen_dealloc_if_allocated(), gen_dealloc_mbr(), gen_defer_shape(), gen_derived_arr_init(), gen_do_ends(), gen_dos_over_shape(), gen_early_bnd_dependencies(), gen_endsingle(), gen_finalization_for_sym(), gen_finalized_result(), gen_init_unl_poly_desc(), gen_kind_parm_assignments(), gen_poly_element_arg(), gen_set_type(), gen_type_initialize_for_sym(), generate_copy(), generate_gather(), generate_get_scalar(), generate_hallobnds(), generate_hcycliclp(), generate_hlocalizebnds(), generate_sect(), genPolyAsn(), get_descr_arg(), get_descr_or_placeholder_arg(), get_invoking_proc_desc(), get_lhs_first_defs(), get_scalar_in_expr(), get_temp_forall2(), handle_allocatable_members(), handle_dependence_ido(), handle_seq_section(), has_def_inlp(), hoist_comms(), hoist_std(), hoist_stmt(), init_derived_type(), init_intrin_type_desc(), init_sdsc(), init_sdsc_bounds(), init_sptr_w_acl(), inline_ast(), inline_contig_check(), inline_func(), inline_hlocalizebnds(), inline_reduction_f90(), inline_small_matmul(), inline_stds(), insert_assign(), insert_call_comm(), insert_comm(), insert_comm_before(), insert_endmask(), insert_forall_comm(), insert_mask(), insert_stmt_after(), insert_stmt_before(), invar_motion(), is_alloc_std(), is_array_element_in_forall(), is_avail_expr_with_list(), is_branch_between(), is_call_dependent(), is_contains_ast_between(), is_dealloc_std(), is_dominator_fg(), is_fusable(), is_hoistable(), is_in_block(), is_pcalls(), is_safe_copy(), is_same_array_bounds(), is_same_def(), is_same_idx(), is_same_mask_in_fused(), is_scatter(), is_std_hoistable(), is_use_lhs(), is_use_lhs_final(), lhs_needtmp(), linearize_arrays(), llvm_lower_enddo_stmt(), llvm_omp_sched(), lower(), lower_data_stmts(), lower_do_stmt(), lower_end_stmt(), lower_enddo_stmt(), lower_omp_target_tripcount(), lower_start_stmt(), lower_stmt(), make_sec_ast(), make_sec_from_ast(), make_sec_from_ast_chk(), make_seq_temp_array(), make_simple_template_from_ast(), markmodifiedexprsfg(), merge_blocks(), mk_dealloc_stub(), mk_descr_from_section(), mk_firstprivate(), mk_loop_hdtl(), mk_ptr_subscr(), mk_std(), mk_ztrips(), move_invar_std(), move_labels(), move_stmts_after(), move_stmts_before(), must_follow(), new_stds(), no_effect_forall(), normalize_forall_triplet(), nullify_member(), nullify_member_after(), opt_allocate(), optimize(), partition_blocks(), pointer_changer(), printstdref(), process_lhs_sub(), propagate_bound(), ptrdefs_has_lhsconflict(), put_calls(), put_forall_fg(), queue_one_std(), reassociate(), record_barrier(), ref_array(), ref_pd(), remove_alias(), remove_from_scalar_subscript(), remove_function_common_from_scalar_subscript(), remove_returns(), remove_stmt(), remove_subscript_expressions(), renumber_lines(), replace_label(), report_collapse(), report_comm(), restore_hoist_stmt(), rewrite_all_asts(), rewrite_allocatable_assignment(), rewrite_asn(), rewrite_block_forall(), rewrite_block_where(), rewrite_calls(), rewrite_deallocate(), rewrite_inlined_args(), rewrite_into_forall(), rewrite_scalar_functions(), rewrite_sub_args(), rewritefg(), rt_outvalue(), scalar_communication(), scalarize(), sdrop_stmt(), search_pure_function(), sectfloat(), sectinline(), selection_sort(), self_use(), semant1(), semant3(), semsmp(), sequentialize(), set_assumed_bounds(), set_assumsz_bound(), set_descr_tag(), set_par(), set_parref_flag2(), set_std_parflags(), set_tag(), sfloat(), sfloat_stmt(), sfloat_stmt2(), shape_comm_in_expr(), shape_communication(), smp_conflict(), stride_1_section(), tag_call_comm(), tag_forall_comm(), temp_copy_section(), temp_gatherx(), temp_type_descriptor(), tmp_assign(), transform_all_call(), transform_associated(), transform_ast(), transform_c_f_pointer(), transform_c_f_procpointer(), transform_call(), transform_elemental(), transform_forall(), transform_merge(), transform_move_alloc(), transform_mvbits(), transform_ptr(), transform_pure_function(), transform_section_arg(), unique_allo(), and update_shape_info().
stddeflist
int* stddeflist static
Definition at line 5532 of file outconv.c.
Referenced by sectfloat(), and sfloat().
syminfo
syminfostruct* syminfo static
Definition at line 5542 of file outconv.c.
Referenced by _check_clean(), add_def_syminfo(), sectfloat(), and sfloat().
templist
T_LIST* templist static
Definition at line 128 of file outconv.c.
Referenced by forall_dependency_analyze(), and get_temp_forall2().