flang: outliner.h File Reference
outliner.h File Reference
Various definitions for the outliner module.
#include "gbldefs.h"
#include "global.h"
#include "symtab.h"
#include "ili.h"
#include <stdio.h>
Enumerations
enum outliner_states_t {
outliner_not_active = 0 , outliner_active_host_par1 = 1 , outliner_active_host_par2 = 2 , outliner_active_switchfile = 3 ,
outliner_reset = 4 , outliner_error = 5
}
Functions
int ll_has_cuda_constructor (void)
void ll_save_cuda_constructor (void)
bool ll_ilm_is_rewriting (void)
...
int ll_ad_outlined_func2 (ILI_OP result_opc, ILI_OP call_opc, int sptr, int nargs, int *args)
...
SPTR ll_create_task_sptr (void)
...
int ll_get_gtid_addr_ili (void)
...
int ll_get_gtid_val_ili (void)
...
SPTR ll_get_gtid (void)
...
SPTR ll_get_hostprog_arg (int func_sptr, int whicharg)
...
SPTR ll_get_shared_arg (SPTR func_sptr)
...
int ll_get_uplevel_arg (void)
...
int ll_get_uplevel_offset (int sptr)
...
SPTR ll_get_uplevel_sym (void)
...
int ll_has_more_outlined (void)
...
int ll_load_outlined_args (int scope_blk_sptr, SPTR callee_sptr, bool clone)
...
int ll_make_outlined_call2 (int func_sptr, int uplevel_ili)
...
int ll_make_outlined_call (int func_sptr, int arg1, int arg2, int arg3)
...
SPTR ll_make_outlined_func_wopc (SPTR stblk_sptr, SPTR scope_sptr, ILM_OP opc)
Create function and parameter list for an outlined function.
SPTR ll_make_outlined_func (SPTR stblk_sptr, SPTR scope_sptr)
Create function and parameter list for an outlined function.
SPTR ll_make_outlined_func_target_device (SPTR stblk_sptr, SPTR scope_sptr, ILM_OP opc)
Create function and parameter list for an outlined function.
SPTR ll_make_outlined_omptarget_func (SPTR stblk_sptr, SPTR scope_sptr, ILM_OP opc)
Create function for OpenMP target and parameter list for an outlined function.
int ll_make_outlined_garg (int nargs, int *argili, DTYPE *arg_dtypes)
...
int ll_make_outlined_gjsr (int func_sptr, int nargs, int arg1, int arg2, int arg3)
...
int ll_make_outlined_task_call (int func_sptr, SPTR task_sptr)
...
SPTR ll_make_outlined_task (SPTR stblk_sptr, SPTR scope_sptr)
Create function and parameter list for an outlined task.
int * ll_make_sections_args (SPTR lbSym, SPTR ubSym, SPTR stSym, SPTR lastSym)
...
DTYPE ll_make_uplevel_type (SPTR stblk_sptr)
...
int llProcessNextTmpfile (void)
...
int ll_reset_parfile (void)
...
int ll_rewrite_ilms (int lineno, int ilmx, int len)
...
int ll_save_gtid_val (int bih)
...
SPTR llvmAddConcurEntryBlk (int bih)
...
int llvmGetExpbCurIlt (void)
...
int llvm_get_unique_sym (void)
...
int llvm_ilms_rewrite_mode (void)
...
void dump_parsyms (int sptr, int isTeams)
Dump the list of variables for the parallel regions specified by 'sptr'.
void finish_taskdup_routine (int curilm, int fnsptr, INT offset)
...
void ilm_outlined_pad_ilm (int curilm)
...
void ll_make_ftn_outlined_params (int func_sptr, int paramct, DTYPE *argtype)
...
void ll_open_parfiles (void)
...
void ll_reset_gtid (void)
...
void ll_reset_outlined_func (void)
...
void ll_set_outlined_currsub (bool)
...
void ll_unlink_parfiles (void)
...
void llvmAddConcurExitBlk (int bih)
...
void llvmSetExpbCurIlt (void)
...
void llvm_set_unique_sym (int sptr)
...
void ll_write_ilm_end (void)
...
void ll_write_ilm_header (int outlined_sptr, int curilm)
...
void llWriteNopILM (int lineno, int ilmx, int len)
...
void restartRewritingILM (int curilm)
...
void setOutlinedPragma (int func_sptr, int saved)
...
void setRewritingILM (void)
...
void start_taskdup (int task_fnsptr, int curilm)
...
void stop_taskdup (int task_fnsptr, int curilm)
...
void unsetRewritingILM (void)
...
void update_acc_with_fn (int fnsptr)
...
ISZ_T getTaskSharedSize (SPTR scope_sptr)
Return size of shared variable for task.
bool outlined_is_eliminated (ILM_OP opc)
test whether do outlining elision for the current opc or not.
bool outlined_need_recompile ()
test whether recompile the ILMs or not.
void ll_set_ompaccel_currfunc (bool isILMrecompile)
Variables
FILE * par_file1
FILE * par_file2
FILE * par_curfile
Detailed Description
Various definitions for the outliner module.
Definition in file outliner.h.
Enumeration Type Documentation
outliner_states_t
enum outliner_states_t
Enumerator
outliner_not_active
outliner_active_host_par1
outliner_active_host_par2
outliner_active_switchfile
outliner_reset
outliner_error
Definition at line 28 of file outliner.h.
Function Documentation
dump_parsyms()
void dump_parsyms (int sptr, int isTeams)
Dump the list of variables for the parallel regions specified by 'sptr'.
These variables should be used to make the uplevel struct when making a call to this outlined region.
Definition at line 110 of file outliner.cpp.
References assert, ERR_Fatal, FILE, fp, gbl, i, llmp_get_uplevel(), sptr, SYMNAME, LLUplevel::vals, and LLUplevel::vals_count.
Referenced by makeOutlinedFunc().
finish_taskdup_routine()
void finish_taskdup_routine (int curilm, int fnsptr, INT offset)
...
Definition at line 2171 of file outliner.cpp.
References allocTaskdup(), clearTaskdup(), copyLastItr(), gbl, hasILMRewrite, offset, par_curfile, pos, t, TASKDUP_AVL, TASKDUP_FILE, and writeTaskdup.
Referenced by exp_smp().
getTaskSharedSize()
ISZ_T getTaskSharedSize (SPTR scope_sptr)
Return size of shared variable for task.
Definition at line 216 of file outliner.cpp.
References DT_CPTR, gbl, ISZ_T, ll_parent_vals_count(), llmp_get_uplevel(), llmp_has_uplevel(), size_of(), sz, and LLUplevel::vals_count.
Referenced by ll_make_kmpc_task_arg().
ilm_outlined_pad_ilm()
void ilm_outlined_pad_ilm (int curilm)
...
Definition at line 1253 of file outliner.cpp.
References ILMB::ilmavl, ilmb, len, llGetILMLen(), and llWriteNopILM().
Referenced by exp_smp(), and stop_taskdup().
ll_ad_outlined_func2()
int ll_ad_outlined_func2 (ILI_OP result_opc, ILI_OP call_opc, int sptr, int nargs, int * args)
...
Definition at line 395 of file outliner.cpp.
References ad1ili(), ad2ili(), ad3ili(), arg, args, ERR_Severe, genretvalue(), i, IL_RES, ILI_OPC, ILIA_AR, ILIA_DP, ILIA_IR, ILIA_KR, ILIA_SP, interr(), nargs, and sptr.
Referenced by ll_make_outlined_call2(), ll_make_outlined_task_call(), mk_function_call(), and mk_kmpc_api_call().
ll_create_task_sptr()
SPTR ll_create_task_sptr (void)
...
Definition at line 677 of file outliner.cpp.
References base, DT_CPTR, GBL_CURRFUNC, getnewccsym(), and SC_AUTO.
ll_get_gtid()
SPTR ll_get_gtid (void)
...
Definition at line 1880 of file outliner.cpp.
References gtid.
Referenced by ll_save_gtid_val(), llLoadGtid(), and processOutlinedByConcur().
ll_get_gtid_addr_ili()
int ll_get_gtid_addr_ili (void)
...
Definition at line 590 of file outliner.cpp.
References ad_acon(), DT_INT, flg, GBL_CURRFUNC, getsname(), gtid, ili, llGetSym(), malloc(), name, FLG::omptarget, PDALNP, strlen(), and sym_is_refd().
Referenced by ll_make_outlined_call2().
ll_get_gtid_val_ili()
int ll_get_gtid_val_ili (void)
...
Definition at line 569 of file outliner.cpp.
References ad3ili(), ad_acon(), addnme(), DT_INT, flg, GBL_CURRFUNC, getsname(), gtid, ili, llGetSym(), malloc(), MSZ_WORD, name, NT_VAR, FLG::omptarget, PDALNP, strlen(), and sym_is_refd().
Referenced by _make_mp_get_threadprivate(), exp_smp(), ll_make_kmpc_atomic_read(), ll_make_kmpc_atomic_write(), ll_make_kmpc_copyprivate(), ll_make_kmpc_critical(), ll_make_kmpc_dispatch_fini(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_end_critical(), ll_make_kmpc_end_serialized_parallel(), ll_make_kmpc_for_static_init(), ll_make_kmpc_for_static_init_args(), ll_make_kmpc_generic_ptr_2int(), ll_make_kmpc_generic_ptr_int(), ll_make_kmpc_push_num_teams(), ll_make_kmpc_serialized_parallel(), ll_make_kmpc_task(), ll_make_kmpc_task_arg(), ll_make_kmpc_task_begin_if0(), ll_make_kmpc_task_complete_if0(), ll_make_kmpc_task_yield(), ll_make_kmpc_taskloop(), ll_make_kmpc_threadprivate(), ll_make_kmpc_threadprivate_cached(), ll_make_outlined_task_call(), and ll_make_sections_args().
ll_get_hostprog_arg()
SPTR ll_get_hostprog_arg (int func_sptr, int whicharg)
...
Definition at line 1776 of file outliner.cpp.
References aux, and AUX::dpdsc_base.
Referenced by exp_header(), exp_smp(), ll_make_outlined_call2(), llLoadGtid(), and setTaskloopVars().
ll_get_shared_arg()
SPTR ll_get_shared_arg (SPTR func_sptr)
...
Definition at line 443 of file outliner.cpp.
References aux, AUX::dpdsc_base, and if().
Referenced by exp_header(), gen_address_operand(), ll_get_uplevel_arg(), llvmAddConcurEntryBlk(), and process_sptr_offset().
ll_get_uplevel_arg()
int ll_get_uplevel_arg (void)
...
Definition at line 665 of file outliner.cpp.
References gbl, GBL_CURRFUNC, and ll_get_shared_arg().
ll_get_uplevel_offset()
int ll_get_uplevel_offset (int sptr)
...
Definition at line 1725 of file outliner.cpp.
References DTyAlgTyMember, LLUplevel::dtype, gbl, GBL_CURRFUNC, llmp_get_uplevel(), mem(), LLUplevel::parent, and sptr.
Referenced by handle_nested_threadprivate().
ll_get_uplevel_sym()
SPTR ll_get_uplevel_sym (void)
...
Definition at line 1898 of file outliner.cpp.
References uplevelSym.
Referenced by ll_make_kmpc_task_arg().
ll_has_cuda_constructor()
int ll_has_cuda_constructor (void)
ll_has_more_outlined()
int ll_has_more_outlined (void)
...
Definition at line 2231 of file outliner.cpp.
References hasILMRewrite.
Referenced by process_input().
ll_ilm_is_rewriting()
bool ll_ilm_is_rewriting (void)
...
Definition at line 2225 of file outliner.cpp.
References isRewritingILM.
Referenced by eval_ilm(), and exp_smp().
ll_load_outlined_args()
int ll_load_outlined_args (int scope_blk_sptr, SPTR callee_sptr, bool clone)
...
Definition at line 1642 of file outliner.cpp.
References ad2ili(), ad3ili(), ad_acon(), ad_aconi(), addnme(), aux, base, cloneUplevel(), count, createUplevelSptr(), AUX::curr_entry, DBGBIT, DTY, DTySetAlgTyAlign, dumpUplevel(), gbl, GBL_CURRFUNC, ll_parent_vals_count(), ll_process_routine_parameters(), llmp_create_uplevel_bykey(), llmp_get_next_key(), llmp_get_uplevel(), llTaskAllocSptr(), loadUplevelArgsForRegion(), MSZ_PTR, NT_VAR, SPTR_NULL, sym_is_refd(), taskAllocSptr, true, ENTRY::uplevel, uplevelSym, and LLUplevel::vals_count.
Referenced by exp_smp(), and ll_make_outlined_func_target_device().
ll_make_ftn_outlined_params()
void ll_make_ftn_outlined_params (int func_sptr, int paramct, DTYPE * argtype)
...
Definition at line 460 of file outliner.cpp.
References aux, count, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, DT_CPTR, getsymbol(), MXIDLEN, name, NEED, and SYMNAME.
Referenced by ll_make_kmpc_proto().
ll_make_outlined_call()
int ll_make_outlined_call (int func_sptr, int arg1, int arg2, int arg3)
...
Definition at line 1758 of file outliner.cpp.
References ad_aconi(), ILI_ALT, ll_ad_outlined_func(), ll_make_outlined_gjsr(), nargs, and SYMNAME.
ll_make_outlined_call2()
int ll_make_outlined_call2 (int func_sptr, int uplevel_ili)
...
Definition at line 1789 of file outliner.cpp.
References args, gbl, GBL_CURRFUNC, genNullArg(), ILI_ALT, ll_ad_outlined_func2(), ll_get_gtid_addr_ili(), ll_get_hostprog_arg(), ll_make_outlined_gjsr(), mk_address(), and nargs.
Referenced by exp_smp().
ll_make_outlined_func()
SPTR ll_make_outlined_func (SPTR stblk_sptr, SPTR scope_sptr)
Create function and parameter list for an outlined function.
Parameters
stblk_sptr references the arguments for the function to be outlined
scope_sptr references the scope
Definition at line 812 of file outliner.cpp.
References makeOutlinedFunc().
Referenced by exp_smp().
ll_make_outlined_func_target_device()
SPTR ll_make_outlined_func_target_device (SPTR stblk_sptr, SPTR scope_sptr, ILM_OP opc)
Create function and parameter list for an outlined function.
Parameters
stblk_sptr references the arguments for the function to be outlined
scope_sptr references the scope
Definition at line 788 of file outliner.cpp.
References eliminate_outlining(), gbl, ll_load_outlined_args(), ll_make_outlined_omptarget_func(), sptr, and SPTR_NULL.
ll_make_outlined_func_wopc()
SPTR ll_make_outlined_func_wopc (SPTR stblk_sptr, SPTR scope_sptr, ILM_OP opc)
Create function and parameter list for an outlined function.
Parameters
stblk_sptr references the arguments for the function to be outlined
scope_sptr references the scope
opc current opc
Definition at line 806 of file outliner.cpp.
References makeOutlinedFunc().
Referenced by exp_smp().
ll_make_outlined_garg()
int ll_make_outlined_garg (int nargs, int * argili, DTYPE * arg_dtypes)
...
argili is in order
Definition at line 357 of file outliner.cpp.
References ad1ili(), ad4ili(), DT_CPTR, i, nargs, and NULL.
Referenced by ll_make_outlined_gjsr(), mk_function_call(), and mk_kmpc_api_call().
ll_make_outlined_gjsr()
int ll_make_outlined_gjsr (int func_sptr, int nargs, int arg1, int arg2, int arg3)
...
Definition at line 378 of file outliner.cpp.
References ad3ili(), ll_make_outlined_garg(), and NULL.
Referenced by ll_make_outlined_call(), ll_make_outlined_call2(), and ll_make_outlined_task_call().
ll_make_outlined_omptarget_func()
SPTR ll_make_outlined_omptarget_func (SPTR stblk_sptr, SPTR scope_sptr, ILM_OP opc)
Create function for OpenMP target and parameter list for an outlined function.
Parameters
stblk_sptr references the arguments for the function to be outlined
scope_sptr references the scope
Definition at line 800 of file outliner.cpp.
References makeOutlinedFunc().
Referenced by ll_make_outlined_func_target_device().
ll_make_outlined_task()
SPTR ll_make_outlined_task (SPTR stblk_sptr, SPTR scope_sptr)
Create function and parameter list for an outlined task.
Parameters
stblk_sptr references the arguments for the task to be outlined
Definition at line 818 of file outliner.cpp.
References makeOutlinedFunc().
Referenced by exp_smp().
ll_make_outlined_task_call()
int ll_make_outlined_task_call (int func_sptr, SPTR task_sptr)
...
Definition at line 1821 of file outliner.cpp.
References ad2ili(), ad_acon(), addnme(), args, ILI_ALT, ll_ad_outlined_func2(), ll_get_gtid_val_ili(), ll_make_outlined_gjsr(), and NT_VAR.
Referenced by exp_smp().
ll_make_sections_args()
int * ll_make_sections_args (SPTR lbSym, SPTR ubSym, SPTR stSym, SPTR lastSym)
...
Definition at line 686 of file outliner.cpp.
References ad_acon(), ad_icon, args, genNullArg(), KMP_SCH_STATIC, and ll_get_gtid_val_ili().
Referenced by exp_smp().
ll_make_uplevel_type()
DTYPE ll_make_uplevel_type (SPTR stblk_sptr)
...
Definition at line 237 of file outliner.cpp.
References aux, any_kmpc_struct::byval, count, AUX::curr_entry, ENTRY::display, DT_CPTR, any_kmpc_struct::dtype, gbl, i, ISZ_T, j, ll_make_kmpc_struct_type(), ll_parent_vals_count(), llmp_get_uplevel(), name, any_kmpc_struct::name, NULL, any_kmpc_struct::psptr, size_of(), sptr, SYMNAME, sz, LLUplevel::vals, and LLUplevel::vals_count.
Referenced by createUplevelSptr().
ll_open_parfiles()
void ll_open_parfiles (void)
...
Definition at line 1911 of file outliner.cpp.
References errfatal(), NULL, par_file1, par_file2, parFileNm1, and parFileNm2.
Referenced by init().
ll_reset_gtid()
void ll_reset_gtid (void)
...
Definition at line 1886 of file outliner.cpp.
References gtid, and SPTR_NULL.
Referenced by schedule().
ll_reset_outlined_func()
void ll_reset_outlined_func (void)
...
Definition at line 1892 of file outliner.cpp.
References SPTR_NULL, and uplevelSym.
Referenced by finish_routine().
ll_reset_parfile()
int ll_reset_parfile (void)
...
Definition at line 854 of file outliner.cpp.
References assert, ERR_Fatal, gbl, hasILMRewrite, orig_ilmfil, outl_state, outliner_active_host_par1, outliner_active_host_par2, outliner_active_switchfile, outliner_nextstate(), outliner_not_active, outliner_reset, par_curfile, par_file1, par_file2, reset_kmpc_ident_dtype(), resetThreadprivate(), savedILMFil, set_ilmfile(), and void().
Referenced by process_input().
ll_rewrite_ilms()
int ll_rewrite_ilms (int lineno, int ilmx, int len)
...
Definition at line 1026 of file outliner.cpp.
References allocTaskdup(), assert, ERR_Fatal, flg, gbl, i, ILMB::ilm_base, ILM_OPC, ILM_OPND, ILM_SymOPND, ilmb, isRewritingILM, len, llCollectSymbolInfo(), llGetILMLen(), ompaccel_tinfo_current_get_dev_dtype(), ompaccel_tinfo_current_get_devsptr(), FLG::omptarget, par_curfile, pos, TASKDUP_AVL, TASKDUP_FILE, and writeTaskdup.
Referenced by eval_ilm(), exp_smp(), and expand().
ll_save_cuda_constructor()
void ll_save_cuda_constructor (void)
ll_save_gtid_val()
int ll_save_gtid_val (int bih)
...
Definition at line 640 of file outliner.cpp.
References BIH_NEXT, ILTB::callfg, chk_block(), CUDA_DEVICE, CUDA_GLOBAL, CUDAG, EXP::curbih, EXP::curilt, expb, GBL_CURRFUNC, ili, iltb, ll_get_gtid(), llLoadGtid(), rdilts(), and wrilts().
Referenced by exp_mp_func_prologue(), and processOutlinedByConcur().
ll_set_ompaccel_currfunc()
void ll_set_ompaccel_currfunc (bool isILMrecompile)
ll_set_outlined_currsub()
void ll_set_outlined_currsub (bool isILMrecompile)
...
Definition at line 1846 of file outliner.cpp.
References DBGBIT, FILE, fp, gbl, gilmpos, llReadILMHeader(), RU_SUBR, and SYMNAME.
Referenced by process_input().
ll_unlink_parfiles()
void ll_unlink_parfiles (void)
...
Definition at line 1936 of file outliner.cpp.
References llRestoreSavedILFil(), NULL, par_file1, par_file2, parFileNm1, and parFileNm2.
Referenced by finish(), and main().
ll_write_ilm_end()
void ll_write_ilm_end (void)
...
Definition at line 1205 of file outliner.cpp.
References gbl, par_curfile, and t.
Referenced by decrOutlinedCnt().
ll_write_ilm_header()
void ll_write_ilm_header (int outlined_sptr, int curilm)
...
Definition at line 1133 of file outliner.cpp.
References gbl, hasILMRewrite, ILMB::ilmavl, ilmb, len, llGetILMLen(), llWriteNopILM(), par_curfile, par_file1, setRewritingILM(), t, t2, and t3.
Referenced by exp_smp().
llProcessNextTmpfile()
int llProcessNextTmpfile (void)
...
Definition at line 2251 of file outliner.cpp.
References gbl, hasILMRewrite, par_file1, and par_file2.
Referenced by process_input().
llvm_get_unique_sym()
int llvm_get_unique_sym (void)
...
This symbol is used only for its name, if none is found, a unique name is generated.
Definition at line 292 of file outliner.cpp.
llvm_ilms_rewrite_mode()
int llvm_ilms_rewrite_mode (void)
...
Definition at line 2237 of file outliner.cpp.
References gbl, par_file1, and par_file2.
Referenced by rdgilms(), and semant_reinit().
llvm_set_unique_sym()
void llvm_set_unique_sym (int sptr)
...
Definition at line 1838 of file outliner.cpp.
References llvmUniqueSym, and sptr.
Referenced by build_routine_and_parameter_entries(), and get_ag().
llvmAddConcurEntryBlk()
SPTR llvmAddConcurEntryBlk (int bih)
...
Definition at line 1961 of file outliner.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad_acon(), addilt(), addnewbih(), addnme(), aux, BIH_EN, BIH_LABEL, EXP::curbih, EXP::curilt, AUX::curr_entry, expb, flg, gbl, GBL_CURRFUNC, getccsym(), ili, ILT_PREV, ll_get_shared_arg(), mk_address(), mk_argasym(), NT_IND, NT_VAR, rdilts(), FLG::recursive, reg_init(), reset_kmpc_ident_dtype(), SPTR_NULL, sym_is_refd(), ENTRY::uplevel, and wrilts().
Referenced by processOutlinedByConcur().
llvmAddConcurExitBlk()
void llvmAddConcurExitBlk (int bih)
...
Definition at line 2021 of file outliner.cpp.
References ad1ili(), addilt(), addnewbih(), EXP::arglist, BIH_FT, BIH_LAST, BIH_PREV, BIH_XT, EXP::bits, EXP::callfg, EXP::curbih, EXP::curilt, expb, EXP::flags, GBL_CURRFUNC, ILT_PREV, mkrtemp_end(), rdilts(), and wrilts().
Referenced by processOutlinedByConcur().
llvmGetExpbCurIlt()
int llvmGetExpbCurIlt (void)
...
Definition at line 1955 of file outliner.cpp.
References EXP::curilt, and expb.
llvmSetExpbCurIlt()
void llvmSetExpbCurIlt (void)
...
Definition at line 1949 of file outliner.cpp.
References EXP::curilt, expb, and ILT_PREV.
llWriteNopILM()
void llWriteNopILM (int lineno, int ilmx, int len)
...
Definition at line 1219 of file outliner.cpp.
References allocTaskdup(), assert, ERR_Fatal, i, isRewritingILM, len, llGetILMLen(), par_curfile, TASKDUP_AVL, TASKDUP_FILE, and writeTaskdup.
Referenced by exp_smp(), ilm_outlined_pad_ilm(), ll_write_ilm_header(), restartRewritingILM(), and start_taskdup().
outlined_is_eliminated()
bool outlined_is_eliminated (ILM_OP opc)
test whether do outlining elision for the current opc or not.
Definition at line 2302 of file outliner.cpp.
outlined_need_recompile()
bool outlined_need_recompile ()
test whether recompile the ILMs or not.
Definition at line 2308 of file outliner.cpp.
restartRewritingILM()
void restartRewritingILM (int curilm)
...
Definition at line 2103 of file outliner.cpp.
References gbl, ILMB::ilmavl, ilmb, len, llGetILMLen(), llWriteNopILM(), par_curfile, pos, setRewritingILM(), and t.
Referenced by exp_smp().
setOutlinedPragma()
void setOutlinedPragma (int func_sptr, int saved)
...
Definition at line 732 of file outliner.cpp.
setRewritingILM()
void setRewritingILM (void)
...
Definition at line 2219 of file outliner.cpp.
References isRewritingILM.
Referenced by ll_write_ilm_header(), and restartRewritingILM().
start_taskdup()
void start_taskdup (int task_fnsptr, int curilm)
...
Definition at line 2054 of file outliner.cpp.
References allocTaskdup(), gbl, ILMB::ilmavl, ilmb, len, llGetILMLen(), llMakeTaskdupRoutine(), llWriteNopILM(), pos, t, t2, t3, TASKDUP_AVL, TASKDUP_FILE, and writeTaskdup.
Referenced by exp_smp().
stop_taskdup()
void stop_taskdup (int task_fnsptr, int curilm)
...
Definition at line 2126 of file outliner.cpp.
References ilm_outlined_pad_ilm(), pos, and writeTaskdup.
Referenced by exp_smp().
unsetRewritingILM()
void unsetRewritingILM (void)
...
Definition at line 2213 of file outliner.cpp.
References isRewritingILM.
Referenced by decrOutlinedCnt(), and exp_smp().
update_acc_with_fn()
void update_acc_with_fn (int fnsptr)
...
Definition at line 537 of file outliner.cpp.
Referenced by makeOutlinedFunc(), and mk_kmpc_api_call().
Variable Documentation
par_curfile
FILE* par_curfile extern
Definition at line 57 of file outliner.cpp.
Referenced by finish_taskdup_routine(), ll_reset_parfile(), ll_reset_parfile_(), ll_rewrite_ilms(), ll_write_ilm_end(), ll_write_ilm_header(), llWriteNopILM(), and restartRewritingILM().
par_file1
FILE* par_file1 extern
Definition at line 55 of file outliner.cpp.
Referenced by get_file_state(), ll_open_parfiles(), ll_reset_parfile(), ll_reset_parfile_(), ll_unlink_parfiles(), ll_write_ilm_header(), llProcessNextTmpfile(), llvm_ilms_rewrite_mode(), and outliner_nextstate().
par_file2
FILE* par_file2 extern
Definition at line 56 of file outliner.cpp.
Referenced by get_file_state(), ll_open_parfiles(), ll_reset_parfile(), ll_reset_parfile_(), ll_unlink_parfiles(), llProcessNextTmpfile(), llvm_ilms_rewrite_mode(), and outliner_nextstate().