flang: outliner.cpp File Reference
outliner.cpp File Reference
extract regions into subroutines; add uplevel references as arguments
#include "outliner.h"
#include "error.h"
#include "semant.h"
#include "llassem.h"
#include "exputil.h"
#include "ilmtp.h"
#include "ilm.h"
#include "expand.h"
#include "kmpcutil.h"
#include "machreg.h"
#include "mp.h"
#include "ll_structure.h"
#include "llmputil.h"
#include "llutil.h"
#include "expsmp.h"
#include "dtypeutl.h"
#include "ll_ftn.h"
#include "cgllvm.h"
#include "regutil.h"
#include "symfun.h"
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include "asprintf.h"
#include <unistd.h>
Classes
struct taskdupSt
Macros
#define MAX_PARFILE_LEN 15
#define TASKDUP_FILE taskdup.file
#define TASKDUP_SZ taskdup.sz
#define TASKDUP_AVL taskdup.avl
#define DT_VOID_NONE DT_NONE
#define MXIDLEN 250
Functions
static void allocTaskdup (int)
static void resetThreadprivate (void)
static bool eliminate_outlining (ILM_OP opc)
static char * ll_get_outlined_funcname (int fileno, int lineno, bool isompaccel, ILM_OP opc)
static void dumpUplevel (int uplevel_sptr)
void dump_parsyms (int sptr, int isTeams)
Dump the list of variables for the parallel regions specified by 'sptr'.
static const char * get_file_state (FILE *ilmfile)
void set_outliner_state (outliner_states_t next)
static void dump_ilmfile_state (FILE *previous_file)
void dump_outliner ()
static void set_ilmfile (FILE *file)
static int genNullArg ()
static ISZ_T ll_parent_vals_count (int stblk_sptr)
ISZ_T getTaskSharedSize (SPTR scope_sptr)
Return size of shared variable for task.
DTYPE ll_make_uplevel_type (SPTR stblk_sptr)
...
int llvm_get_unique_sym (void)
...
static const char * get_opc_name (ILM_OP opc)
int ll_make_outlined_garg (int nargs, int *argili, DTYPE *arg_dtypes)
...
int ll_make_outlined_gjsr (int func_sptr, int nargs, int arg1, int arg2, int arg3)
...
int ll_ad_outlined_func2 (ILI_OP result_opc, ILI_OP call_opc, int sptr, int nargs, int *args)
...
SPTR ll_get_shared_arg (SPTR func_sptr)
...
void ll_make_ftn_outlined_params (int func_sptr, int paramct, DTYPE *argtype)
...
static void llMakeFtnOutlinedSignature (int func_sptr, int n_params, const KMPC_ST_TYPE *params)
void update_acc_with_fn_flags (int fnsptr, int flags)
void update_acc_with_fn (int fnsptr)
...
static SPTR llGetSym (char *name, DTYPE dtype)
int ll_get_gtid_val_ili (void)
...
int ll_get_gtid_addr_ili (void)
...
static int llLoadGtid (void)
int ll_save_gtid_val (int bih)
...
int ll_get_uplevel_arg (void)
...
SPTR ll_create_task_sptr (void)
...
int * ll_make_sections_args (SPTR lbSym, SPTR ubSym, SPTR stSym, SPTR lastSym)
...
void setOutlinedPragma (int func_sptr, int saved)
...
static SPTR makeOutlinedFunc (int stblk_sptr, int scope_sptr, bool is_task, bool istaskdup, bool isompaccel, ILM_OP opc)
SPTR ll_make_outlined_func_target_device (SPTR stblk_sptr, SPTR scope_sptr, ILM_OP opc)
Create function and parameter list for an outlined function.
SPTR ll_make_outlined_omptarget_func (SPTR stblk_sptr, SPTR scope_sptr, ILM_OP opc)
Create function for OpenMP target and parameter list for an outlined function.
SPTR ll_make_outlined_func_wopc (SPTR stblk_sptr, SPTR scope_sptr, ILM_OP opc)
Create function and parameter list for an outlined function.
SPTR ll_make_outlined_func (SPTR stblk_sptr, SPTR scope_sptr)
Create function and parameter list for an outlined function.
SPTR ll_make_outlined_task (SPTR stblk_sptr, SPTR scope_sptr)
Create function and parameter list for an outlined task.
static int llMakeTaskdupRoutine (int task_sptr)
static outliner_states_t outliner_nextstate ()
int ll_reset_parfile (void)
...
int ll_reset_parfile_ (void)
static int llGetILMLen (int ilmx)
static void llCollectSymbolInfo (ILM *ilmpx)
int ll_rewrite_ilms (int lineno, int ilmx, int len)
...
void ll_write_ilm_header (int outlined_sptr, int curilm)
...
static int llReadILMHeader ()
void ll_write_ilm_end (void)
...
void llWriteNopILM (int lineno, int ilmx, int len)
...
void ilm_outlined_pad_ilm (int curilm)
...
static SPTR createUplevelSptr (SPTR uplevel_sptr)
static SPTR cloneUplevel (SPTR fr_uplevel_sptr, SPTR to_uplevel_sptr, bool is_task)
static int loadCharLen (SPTR lensym)
static int toUplevelAddr (SPTR taskAllocSptr, SPTR uplevel, int offset)
static void handle_nested_threadprivate (LLUplevel *parent, SPTR uplevel, SPTR taskAllocSptr, int nme)
static SPTR member_with_offset (SPTR member, int offset)
static int loadUplevelArgsForRegion (SPTR uplevel, SPTR taskAllocSptr, int count, int uplevel_stblk_sptr)
int ll_load_outlined_args (int scope_blk_sptr, SPTR callee_sptr, bool clone)
...
int ll_get_uplevel_offset (int sptr)
...
int ll_make_outlined_call (int func_sptr, int arg1, int arg2, int arg3)
...
SPTR ll_get_hostprog_arg (int func_sptr, int whicharg)
...
int ll_make_outlined_call2 (int func_sptr, int uplevel_ili)
...
int ll_make_outlined_task_call (int func_sptr, SPTR task_sptr)
...
void llvm_set_unique_sym (int sptr)
...
void ll_set_outlined_currsub (bool isILMrecompile)
...
SPTR ll_get_gtid (void)
...
void ll_reset_gtid (void)
...
void ll_reset_outlined_func (void)
...
SPTR ll_get_uplevel_sym (void)
...
static void llRestoreSavedILFil ()
void ll_open_parfiles ()
...
void ll_unlink_parfiles ()
...
void llvmSetExpbCurIlt (void)
...
int llvmGetExpbCurIlt (void)
...
SPTR llvmAddConcurEntryBlk (int bih)
...
void llvmAddConcurExitBlk (int bih)
...
void start_taskdup (int task_fnsptr, int curilm)
...
void restartRewritingILM (int curilm)
...
void stop_taskdup (int task_fnsptr, int curilm)
...
static void clearTaskdup ()
static void copyLastItr (int fnsptr, INT offset)
void finish_taskdup_routine (int curilm, int fnsptr, INT offset)
...
void unsetRewritingILM ()
...
void setRewritingILM ()
...
bool ll_ilm_is_rewriting (void)
...
int ll_has_more_outlined ()
...
int llvm_ilms_rewrite_mode (void)
...
int llProcessNextTmpfile ()
...
int mk_function_call (DTYPE ret_dtype, int n_args, DTYPE *arg_dtypes, int *arg_ilis, SPTR func_sptr)
bool outlined_is_eliminated (ILM_OP opc)
test whether do outlining elision for the current opc or not.
bool outlined_need_recompile ()
test whether recompile the ILMs or not.
Variables
FILE * orig_ilmfil
FILE * par_file1 = NULL
FILE * par_file2 = NULL
FILE * par_curfile = NULL
static FILE * savedILMFil = NULL
static char parFileNm1 [MAX_PARFILE_LEN]
static char parFileNm2 [MAX_PARFILE_LEN]
static bool hasILMRewrite
static bool isRewritingILM
static int funcCnt = 0
static int llvmUniqueSym
static SPTR uplevelSym
static SPTR gtid
static bool writeTaskdup
static int pos
static struct taskdupSt taskdup
const char * ilmfile_states [] = {"ORIGINAL", "PARFILE1", "PARFILE2" }
const char * outliner_state_names [] = {"Inactive", "Parfile1", "ParFile2", "SwitchParFiles", "Reset", "Error"}
static outliner_states_t outl_state = outliner_not_active
static const KMPC_ST_TYPE funcSig [3]
static const KMPC_ST_TYPE taskSig [2]
static const KMPC_ST_TYPE taskdupSig [3]
Detailed Description
extract regions into subroutines; add uplevel references as arguments
Definition in file outliner.cpp.
Macro Definition Documentation
DT_VOID_NONE
#define DT_VOID_NONE DT_NONE
Definition at line 92 of file outliner.cpp.
MAX_PARFILE_LEN
#define MAX_PARFILE_LEN 15
Definition at line 52 of file outliner.cpp.
MXIDLEN
#define MXIDLEN 250
Definition at line 94 of file outliner.cpp.
TASKDUP_AVL
#define TASKDUP_AVL taskdup.avl
Definition at line 80 of file outliner.cpp.
TASKDUP_FILE
#define TASKDUP_FILE taskdup.file
Definition at line 78 of file outliner.cpp.
TASKDUP_SZ
#define TASKDUP_SZ taskdup.sz
Definition at line 79 of file outliner.cpp.
Function Documentation
allocTaskdup()
static void allocTaskdup (int len) static
Definition at line 2204 of file outliner.cpp.
References len, NEED, TASKDUP_AVL, TASKDUP_FILE, and TASKDUP_SZ.
Referenced by copyLastItr(), finish_taskdup_routine(), ll_rewrite_ilms(), llWriteNopILM(), and start_taskdup().
clearTaskdup()
static void clearTaskdup () static
Definition at line 2135 of file outliner.cpp.
References FREE, NULL, TASKDUP_AVL, TASKDUP_FILE, and TASKDUP_SZ.
Referenced by finish_taskdup_routine().
cloneUplevel()
static SPTR cloneUplevel (SPTR fr_uplevel_sptr, SPTR to_uplevel_sptr, bool is_task) static
Definition at line 1293 of file outliner.cpp.
References ad2ili(), ad5ili(), ad_acon(), addnme(), arg, chk_block(), count, createUplevelSptr(), gbl, GBL_CURRFUNC, ili, ISZ_T, ll_parent_vals_count(), llTaskAllocSptr(), mk_address(), mk_argasym(), NT_IND, NT_VAR, SPTR_NULL, TARGET_PTRSIZE, and taskAllocSptr.
Referenced by ll_load_outlined_args().
copyLastItr()
static void copyLastItr (int fnsptr, INT offset) static
Definition at line 2144 of file outliner.cpp.
References allocTaskdup(), DT_INT, gbl, getcon(), offset, TASKDUP_AVL, TASKDUP_FILE, and tmp.
Referenced by finish_taskdup_routine().
createUplevelSptr()
static SPTR createUplevelSptr (SPTR uplevel_sptr) static
Definition at line 1265 of file outliner.cpp.
References DTY, DTySetAlgTyAlign, gbl, getccssym(), ll_make_uplevel_type(), llmp_get_uplevel(), llmp_uplevel_set_dtype(), n, SC_AUTO, and uplevelSym.
Referenced by cloneUplevel(), and ll_load_outlined_args().
dump_ilmfile_state()
static void dump_ilmfile_state (FILE * previous_file) static
Definition at line 159 of file outliner.cpp.
References DBGBIT, dfile, FILE, gbl, and get_file_state().
Referenced by set_ilmfile().
dump_outliner()
void dump_outliner ()
Definition at line 166 of file outliner.cpp.
References dfile, FILE, gbl, get_file_state(), isRewritingILM, outl_state, and outliner_state_names.
dump_parsyms()
void dump_parsyms (int sptr, int isTeams)
Dump the list of variables for the parallel regions specified by 'sptr'.
These variables should be used to make the uplevel struct when making a call to this outlined region.
Definition at line 110 of file outliner.cpp.
References assert, ERR_Fatal, FILE, fp, gbl, i, llmp_get_uplevel(), sptr, SYMNAME, LLUplevel::vals, and LLUplevel::vals_count.
Referenced by makeOutlinedFunc().
dumpUplevel()
static void dumpUplevel (int uplevel_sptr) static
Definition at line 98 of file outliner.cpp.
References DTY, DTyAlgTyMember, FILE, fp, gbl, i, NOSYM, stb, SYMNAME, and STB::tynames.
Referenced by ll_load_outlined_args().
eliminate_outlining()
static bool eliminate_outlining (ILM_OP opc) static
Definition at line 2296 of file outliner.cpp.
Referenced by ll_make_outlined_func_target_device().
finish_taskdup_routine()
void finish_taskdup_routine (int curilm, int fnsptr, INT offset)
...
Definition at line 2171 of file outliner.cpp.
References allocTaskdup(), clearTaskdup(), copyLastItr(), gbl, hasILMRewrite, offset, par_curfile, pos, t, TASKDUP_AVL, TASKDUP_FILE, and writeTaskdup.
Referenced by exp_smp().
genNullArg()
static int genNullArg () static
Definition at line 182 of file outliner.cpp.
References ad1ili(), DT_INT, getcon(), ili, and tmp.
Referenced by ll_make_outlined_call2(), and ll_make_sections_args().
get_file_state()
static const char * get_file_state (FILE * ilmfile) static
Definition at line 136 of file outliner.cpp.
References ilmfile_states, orig_ilmfil, par_file1, and par_file2.
Referenced by dump_ilmfile_state(), and dump_outliner().
get_opc_name()
static const char * get_opc_name (ILM_OP opc) static
Definition at line 298 of file outliner.cpp.
Referenced by makeOutlinedFunc().
getTaskSharedSize()
ISZ_T getTaskSharedSize (SPTR scope_sptr)
Return size of shared variable for task.
Definition at line 216 of file outliner.cpp.
References DT_CPTR, gbl, ISZ_T, ll_parent_vals_count(), llmp_get_uplevel(), llmp_has_uplevel(), size_of(), sz, and LLUplevel::vals_count.
Referenced by ll_make_kmpc_task_arg().
handle_nested_threadprivate()
static void handle_nested_threadprivate (LLUplevel * parent, SPTR uplevel, SPTR taskAllocSptr, int nme) static
Definition at line 1382 of file outliner.cpp.
References ad4ili(), addr, chk_block(), getThreadPrivateTp(), i, if(), ll_get_uplevel_offset(), llGetThreadprivateAddr(), MSZ_PTR, offset, parent, sptr, taskAllocSptr, toUplevelAddr(), and val.
Referenced by loadUplevelArgsForRegion().
ilm_outlined_pad_ilm()
void ilm_outlined_pad_ilm (int curilm)
...
Definition at line 1253 of file outliner.cpp.
References ILMB::ilmavl, ilmb, len, llGetILMLen(), and llWriteNopILM().
Referenced by exp_smp(), and stop_taskdup().
ll_ad_outlined_func2()
int ll_ad_outlined_func2 (ILI_OP result_opc, ILI_OP call_opc, int sptr, int nargs, int * args)
...
Definition at line 395 of file outliner.cpp.
References ad1ili(), ad2ili(), ad3ili(), arg, args, ERR_Severe, genretvalue(), i, IL_RES, ILI_OPC, ILIA_AR, ILIA_DP, ILIA_IR, ILIA_KR, ILIA_SP, interr(), nargs, and sptr.
Referenced by ll_make_outlined_call2(), ll_make_outlined_task_call(), mk_function_call(), and mk_kmpc_api_call().
ll_create_task_sptr()
SPTR ll_create_task_sptr (void)
...
Definition at line 677 of file outliner.cpp.
References base, DT_CPTR, GBL_CURRFUNC, getnewccsym(), and SC_AUTO.
ll_get_gtid()
SPTR ll_get_gtid (void)
...
Definition at line 1880 of file outliner.cpp.
References gtid.
Referenced by ll_save_gtid_val(), llLoadGtid(), and processOutlinedByConcur().
ll_get_gtid_addr_ili()
int ll_get_gtid_addr_ili (void)
...
Definition at line 590 of file outliner.cpp.
References ad_acon(), DT_INT, flg, GBL_CURRFUNC, getsname(), gtid, ili, llGetSym(), malloc(), name, FLG::omptarget, PDALNP, strlen(), and sym_is_refd().
Referenced by ll_make_outlined_call2().
ll_get_gtid_val_ili()
int ll_get_gtid_val_ili (void)
...
Definition at line 569 of file outliner.cpp.
References ad3ili(), ad_acon(), addnme(), DT_INT, flg, GBL_CURRFUNC, getsname(), gtid, ili, llGetSym(), malloc(), MSZ_WORD, name, NT_VAR, FLG::omptarget, PDALNP, strlen(), and sym_is_refd().
Referenced by _make_mp_get_threadprivate(), exp_smp(), ll_make_kmpc_atomic_read(), ll_make_kmpc_atomic_write(), ll_make_kmpc_copyprivate(), ll_make_kmpc_critical(), ll_make_kmpc_dispatch_fini(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_end_critical(), ll_make_kmpc_end_serialized_parallel(), ll_make_kmpc_for_static_init(), ll_make_kmpc_for_static_init_args(), ll_make_kmpc_generic_ptr_2int(), ll_make_kmpc_generic_ptr_int(), ll_make_kmpc_push_num_teams(), ll_make_kmpc_serialized_parallel(), ll_make_kmpc_task(), ll_make_kmpc_task_arg(), ll_make_kmpc_task_begin_if0(), ll_make_kmpc_task_complete_if0(), ll_make_kmpc_task_yield(), ll_make_kmpc_taskloop(), ll_make_kmpc_threadprivate(), ll_make_kmpc_threadprivate_cached(), ll_make_outlined_task_call(), and ll_make_sections_args().
ll_get_hostprog_arg()
SPTR ll_get_hostprog_arg (int func_sptr, int whicharg)
...
Definition at line 1776 of file outliner.cpp.
References aux, and AUX::dpdsc_base.
Referenced by exp_header(), exp_smp(), ll_make_outlined_call2(), llLoadGtid(), and setTaskloopVars().
ll_get_outlined_funcname()
static char * ll_get_outlined_funcname (int fileno, int lineno, bool isompaccel, ILM_OP opc) static
Definition at line 324 of file outliner.cpp.
References assert, ERR_Fatal, funcCnt, gbl, GBL_CURRFUNC, getsname(), lineno, malloc(), name, prefix, r, and strlen().
Referenced by makeOutlinedFunc().
ll_get_shared_arg()
SPTR ll_get_shared_arg (SPTR func_sptr)
...
Definition at line 443 of file outliner.cpp.
References aux, AUX::dpdsc_base, and if().
Referenced by exp_header(), gen_address_operand(), ll_get_uplevel_arg(), llvmAddConcurEntryBlk(), and process_sptr_offset().
ll_get_uplevel_arg()
int ll_get_uplevel_arg (void)
...
Definition at line 665 of file outliner.cpp.
References gbl, GBL_CURRFUNC, and ll_get_shared_arg().
ll_get_uplevel_offset()
int ll_get_uplevel_offset (int sptr)
...
Definition at line 1725 of file outliner.cpp.
References DTyAlgTyMember, LLUplevel::dtype, gbl, GBL_CURRFUNC, llmp_get_uplevel(), mem(), LLUplevel::parent, and sptr.
Referenced by handle_nested_threadprivate().
ll_get_uplevel_sym()
SPTR ll_get_uplevel_sym (void)
...
Definition at line 1898 of file outliner.cpp.
References uplevelSym.
Referenced by ll_make_kmpc_task_arg().
ll_has_more_outlined()
int ll_has_more_outlined (void)
...
Definition at line 2231 of file outliner.cpp.
References hasILMRewrite.
Referenced by process_input().
ll_ilm_is_rewriting()
bool ll_ilm_is_rewriting (void)
...
Definition at line 2225 of file outliner.cpp.
References isRewritingILM.
Referenced by eval_ilm(), and exp_smp().
ll_load_outlined_args()
int ll_load_outlined_args (int scope_blk_sptr, SPTR callee_sptr, bool clone)
...
Definition at line 1642 of file outliner.cpp.
References ad2ili(), ad3ili(), ad_acon(), ad_aconi(), addnme(), aux, base, cloneUplevel(), count, createUplevelSptr(), AUX::curr_entry, DBGBIT, DTY, DTySetAlgTyAlign, dumpUplevel(), gbl, GBL_CURRFUNC, ll_parent_vals_count(), ll_process_routine_parameters(), llmp_create_uplevel_bykey(), llmp_get_next_key(), llmp_get_uplevel(), llTaskAllocSptr(), loadUplevelArgsForRegion(), MSZ_PTR, NT_VAR, SPTR_NULL, sym_is_refd(), taskAllocSptr, true, ENTRY::uplevel, uplevelSym, and LLUplevel::vals_count.
Referenced by exp_smp(), and ll_make_outlined_func_target_device().
ll_make_ftn_outlined_params()
void ll_make_ftn_outlined_params (int func_sptr, int paramct, DTYPE * argtype)
...
Definition at line 460 of file outliner.cpp.
References aux, count, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, DT_CPTR, getsymbol(), MXIDLEN, name, NEED, and SYMNAME.
Referenced by ll_make_kmpc_proto().
ll_make_outlined_call()
int ll_make_outlined_call (int func_sptr, int arg1, int arg2, int arg3)
...
Definition at line 1758 of file outliner.cpp.
References ad_aconi(), ILI_ALT, ll_ad_outlined_func(), ll_make_outlined_gjsr(), nargs, and SYMNAME.
ll_make_outlined_call2()
int ll_make_outlined_call2 (int func_sptr, int uplevel_ili)
...
Definition at line 1789 of file outliner.cpp.
References args, gbl, GBL_CURRFUNC, genNullArg(), ILI_ALT, ll_ad_outlined_func2(), ll_get_gtid_addr_ili(), ll_get_hostprog_arg(), ll_make_outlined_gjsr(), mk_address(), and nargs.
Referenced by exp_smp().
ll_make_outlined_func()
SPTR ll_make_outlined_func (SPTR stblk_sptr, SPTR scope_sptr)
Create function and parameter list for an outlined function.
Parameters
stblk_sptr references the arguments for the function to be outlined
scope_sptr references the scope
Definition at line 812 of file outliner.cpp.
References makeOutlinedFunc().
Referenced by exp_smp().
ll_make_outlined_func_target_device()
SPTR ll_make_outlined_func_target_device (SPTR stblk_sptr, SPTR scope_sptr, ILM_OP opc)
Create function and parameter list for an outlined function.
Parameters
stblk_sptr references the arguments for the function to be outlined
scope_sptr references the scope
Definition at line 788 of file outliner.cpp.
References eliminate_outlining(), gbl, ll_load_outlined_args(), ll_make_outlined_omptarget_func(), sptr, and SPTR_NULL.
ll_make_outlined_func_wopc()
SPTR ll_make_outlined_func_wopc (SPTR stblk_sptr, SPTR scope_sptr, ILM_OP opc)
Create function and parameter list for an outlined function.
Parameters
stblk_sptr references the arguments for the function to be outlined
scope_sptr references the scope
opc current opc
Definition at line 806 of file outliner.cpp.
References makeOutlinedFunc().
Referenced by exp_smp().
ll_make_outlined_garg()
int ll_make_outlined_garg (int nargs, int * argili, DTYPE * arg_dtypes)
...
argili is in order
Definition at line 357 of file outliner.cpp.
References ad1ili(), ad4ili(), DT_CPTR, i, nargs, and NULL.
Referenced by ll_make_outlined_gjsr(), mk_function_call(), and mk_kmpc_api_call().
ll_make_outlined_gjsr()
int ll_make_outlined_gjsr (int func_sptr, int nargs, int arg1, int arg2, int arg3)
...
Definition at line 378 of file outliner.cpp.
References ad3ili(), ll_make_outlined_garg(), and NULL.
Referenced by ll_make_outlined_call(), ll_make_outlined_call2(), and ll_make_outlined_task_call().
ll_make_outlined_omptarget_func()
SPTR ll_make_outlined_omptarget_func (SPTR stblk_sptr, SPTR scope_sptr, ILM_OP opc)
Create function for OpenMP target and parameter list for an outlined function.
Parameters
stblk_sptr references the arguments for the function to be outlined
scope_sptr references the scope
Definition at line 800 of file outliner.cpp.
References makeOutlinedFunc().
Referenced by ll_make_outlined_func_target_device().
ll_make_outlined_task()
SPTR ll_make_outlined_task (SPTR stblk_sptr, SPTR scope_sptr)
Create function and parameter list for an outlined task.
Parameters
stblk_sptr references the arguments for the task to be outlined
Definition at line 818 of file outliner.cpp.
References makeOutlinedFunc().
Referenced by exp_smp().
ll_make_outlined_task_call()
int ll_make_outlined_task_call (int func_sptr, SPTR task_sptr)
...
Definition at line 1821 of file outliner.cpp.
References ad2ili(), ad_acon(), addnme(), args, ILI_ALT, ll_ad_outlined_func2(), ll_get_gtid_val_ili(), ll_make_outlined_gjsr(), and NT_VAR.
Referenced by exp_smp().
ll_make_sections_args()
int * ll_make_sections_args (SPTR lbSym, SPTR ubSym, SPTR stSym, SPTR lastSym)
...
Definition at line 686 of file outliner.cpp.
References ad_acon(), ad_icon, args, genNullArg(), KMP_SCH_STATIC, and ll_get_gtid_val_ili().
Referenced by exp_smp().
ll_make_uplevel_type()
DTYPE ll_make_uplevel_type (SPTR stblk_sptr)
...
Definition at line 237 of file outliner.cpp.
References aux, any_kmpc_struct::byval, count, AUX::curr_entry, ENTRY::display, DT_CPTR, any_kmpc_struct::dtype, gbl, i, ISZ_T, j, ll_make_kmpc_struct_type(), ll_parent_vals_count(), llmp_get_uplevel(), name, any_kmpc_struct::name, NULL, any_kmpc_struct::psptr, size_of(), sptr, SYMNAME, sz, LLUplevel::vals, and LLUplevel::vals_count.
Referenced by createUplevelSptr().
ll_open_parfiles()
void ll_open_parfiles (void)
...
Definition at line 1911 of file outliner.cpp.
References errfatal(), NULL, par_file1, par_file2, parFileNm1, and parFileNm2.
Referenced by init().
ll_parent_vals_count()
static ISZ_T ll_parent_vals_count (int stblk_sptr) static
Definition at line 195 of file outliner.cpp.
References ISZ_T, llmp_get_uplevel(), LLUplevel::parent, sz, and LLUplevel::vals_count.
Referenced by cloneUplevel(), getTaskSharedSize(), ll_load_outlined_args(), ll_make_uplevel_type(), and loadUplevelArgsForRegion().
ll_reset_gtid()
void ll_reset_gtid (void)
...
Definition at line 1886 of file outliner.cpp.
References gtid, and SPTR_NULL.
Referenced by schedule().
ll_reset_outlined_func()
void ll_reset_outlined_func (void)
...
Definition at line 1892 of file outliner.cpp.
References SPTR_NULL, and uplevelSym.
Referenced by finish_routine().
ll_reset_parfile()
int ll_reset_parfile (void)
...
Definition at line 854 of file outliner.cpp.
References assert, ERR_Fatal, gbl, hasILMRewrite, orig_ilmfil, outl_state, outliner_active_host_par1, outliner_active_host_par2, outliner_active_switchfile, outliner_nextstate(), outliner_not_active, outliner_reset, par_curfile, par_file1, par_file2, reset_kmpc_ident_dtype(), resetThreadprivate(), savedILMFil, set_ilmfile(), and void().
Referenced by process_input().
ll_reset_parfile_()
int ll_reset_parfile_ (void)
Definition at line 916 of file outliner.cpp.
References FILE, gbl, hasILMRewrite, orig_ilmfil, par_curfile, par_file1, par_file2, reset_kmpc_ident_dtype(), resetThreadprivate(), savedILMFil, and void().
ll_rewrite_ilms()
int ll_rewrite_ilms (int lineno, int ilmx, int len)
...
Definition at line 1026 of file outliner.cpp.
References allocTaskdup(), assert, ERR_Fatal, flg, gbl, i, ILMB::ilm_base, ILM_OPC, ILM_OPND, ILM_SymOPND, ilmb, isRewritingILM, len, llCollectSymbolInfo(), llGetILMLen(), ompaccel_tinfo_current_get_dev_dtype(), ompaccel_tinfo_current_get_devsptr(), FLG::omptarget, par_curfile, pos, TASKDUP_AVL, TASKDUP_FILE, and writeTaskdup.
Referenced by eval_ilm(), exp_smp(), and expand().
ll_save_gtid_val()
int ll_save_gtid_val (int bih)
...
Definition at line 640 of file outliner.cpp.
References BIH_NEXT, ILTB::callfg, chk_block(), CUDA_DEVICE, CUDA_GLOBAL, CUDAG, EXP::curbih, EXP::curilt, expb, GBL_CURRFUNC, ili, iltb, ll_get_gtid(), llLoadGtid(), rdilts(), and wrilts().
Referenced by exp_mp_func_prologue(), and processOutlinedByConcur().
ll_set_outlined_currsub()
void ll_set_outlined_currsub (bool isILMrecompile)
...
Definition at line 1846 of file outliner.cpp.
References DBGBIT, FILE, fp, gbl, gilmpos, llReadILMHeader(), RU_SUBR, and SYMNAME.
Referenced by process_input().
ll_unlink_parfiles()
void ll_unlink_parfiles (void)
...
Definition at line 1936 of file outliner.cpp.
References llRestoreSavedILFil(), NULL, par_file1, par_file2, parFileNm1, and parFileNm2.
Referenced by finish(), and main().
ll_write_ilm_end()
void ll_write_ilm_end (void)
...
Definition at line 1205 of file outliner.cpp.
References gbl, par_curfile, and t.
Referenced by decrOutlinedCnt().
ll_write_ilm_header()
void ll_write_ilm_header (int outlined_sptr, int curilm)
...
Definition at line 1133 of file outliner.cpp.
References gbl, hasILMRewrite, ILMB::ilmavl, ilmb, len, llGetILMLen(), llWriteNopILM(), par_curfile, par_file1, setRewritingILM(), t, t2, and t3.
Referenced by exp_smp().
llCollectSymbolInfo()
static void llCollectSymbolInfo (ILM * ilmpx) static
Definition at line 982 of file outliner.cpp.
References ILM_OPC, ILM_OPND, ILM_SymOPND, ilms, IM_OPRFLAG, IM_VAR, len, OPR_SYM, ILMINFO::oprs, SC_AUTO, sptr, stb, and sym_is_refd().
Referenced by ll_rewrite_ilms().
llGetILMLen()
static int llGetILMLen (int ilmx) static
Definition at line 966 of file outliner.cpp.
References ILMB::ilm_base, ILM_OPC, ILM_OPND, ilmb, ilms, IM_VAR, len, and ILMINFO::oprs.
Referenced by ilm_outlined_pad_ilm(), ll_rewrite_ilms(), ll_write_ilm_header(), llWriteNopILM(), restartRewritingILM(), and start_taskdup().
llGetSym()
static SPTR llGetSym (char * name, DTYPE dtype) static
Definition at line 542 of file outliner.cpp.
References GBL_CURRFUNC, getsymbol(), gtid, name, SC_AUTO, and SPTR_NULL.
Referenced by ll_get_gtid_addr_ili(), and ll_get_gtid_val_ili().
llLoadGtid()
static int llLoadGtid (void) static
Definition at line 609 of file outliner.cpp.
References ad2ili(), ad3ili(), ad4ili(), ad_acon(), addnme(), arg, gbl, GBL_CURRFUNC, gtid, ili, ll_get_gtid(), ll_get_hostprog_arg(), ll_make_kmpc_global_thread_num(), mk_address(), mk_argasym(), MSZ_WORD, and NT_VAR.
Referenced by ll_save_gtid_val().
llMakeFtnOutlinedSignature()
static void llMakeFtnOutlinedSignature (int func_sptr, int n_params, const KMPC_ST_TYPE * params) static
This is a near duplicate of ll_make_ftn_outlined_params but handles by value for fortran.
Definition at line 494 of file outliner.cpp.
References aux, count, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, DT_CPTR, getsymbol(), i, MXIDLEN, name, NEED, params, and SYMNAME.
Referenced by makeOutlinedFunc().
llMakeTaskdupRoutine()
static int llMakeTaskdupRoutine (int task_sptr) static
Definition at line 824 of file outliner.cpp.
References makeOutlinedFunc().
Referenced by start_taskdup().
llProcessNextTmpfile()
int llProcessNextTmpfile (void)
...
Definition at line 2251 of file outliner.cpp.
References gbl, hasILMRewrite, par_file1, and par_file2.
Referenced by process_input().
llReadILMHeader()
static int llReadILMHeader () static
Definition at line 1184 of file outliner.cpp.
References gbl, and t.
Referenced by ll_set_outlined_currsub().
llRestoreSavedILFil()
static void llRestoreSavedILFil () static
Definition at line 1904 of file outliner.cpp.
References gbl, and savedILMFil.
Referenced by ll_unlink_parfiles().
llvm_get_unique_sym()
int llvm_get_unique_sym (void)
...
This symbol is used only for its name, if none is found, a unique name is generated.
Definition at line 292 of file outliner.cpp.
References llvmUniqueSym.
llvm_ilms_rewrite_mode()
int llvm_ilms_rewrite_mode (void)
...
Definition at line 2237 of file outliner.cpp.
References gbl, par_file1, and par_file2.
Referenced by rdgilms(), and semant_reinit().
llvm_set_unique_sym()
void llvm_set_unique_sym (int sptr)
...
Definition at line 1838 of file outliner.cpp.
References llvmUniqueSym, and sptr.
Referenced by build_routine_and_parameter_entries(), and get_ag().
llvmAddConcurEntryBlk()
SPTR llvmAddConcurEntryBlk (int bih)
...
Definition at line 1961 of file outliner.cpp.
References ad1ili(), ad2ili(), ad3ili(), ad_acon(), addilt(), addnewbih(), addnme(), aux, BIH_EN, BIH_LABEL, EXP::curbih, EXP::curilt, AUX::curr_entry, expb, flg, gbl, GBL_CURRFUNC, getccsym(), ili, ILT_PREV, ll_get_shared_arg(), mk_address(), mk_argasym(), NT_IND, NT_VAR, rdilts(), FLG::recursive, reg_init(), reset_kmpc_ident_dtype(), SPTR_NULL, sym_is_refd(), ENTRY::uplevel, and wrilts().
Referenced by processOutlinedByConcur().
llvmAddConcurExitBlk()
void llvmAddConcurExitBlk (int bih)
...
Definition at line 2021 of file outliner.cpp.
References ad1ili(), addilt(), addnewbih(), EXP::arglist, BIH_FT, BIH_LAST, BIH_PREV, BIH_XT, EXP::bits, EXP::callfg, EXP::curbih, EXP::curilt, expb, EXP::flags, GBL_CURRFUNC, ILT_PREV, mkrtemp_end(), rdilts(), and wrilts().
Referenced by processOutlinedByConcur().
llvmGetExpbCurIlt()
int llvmGetExpbCurIlt (void)
...
Definition at line 1955 of file outliner.cpp.
References EXP::curilt, and expb.
llvmSetExpbCurIlt()
void llvmSetExpbCurIlt (void)
...
Definition at line 1949 of file outliner.cpp.
References EXP::curilt, expb, and ILT_PREV.
llWriteNopILM()
void llWriteNopILM (int lineno, int ilmx, int len)
...
Definition at line 1219 of file outliner.cpp.
References allocTaskdup(), assert, ERR_Fatal, i, isRewritingILM, len, llGetILMLen(), par_curfile, TASKDUP_AVL, TASKDUP_FILE, and writeTaskdup.
Referenced by exp_smp(), ilm_outlined_pad_ilm(), ll_write_ilm_header(), restartRewritingILM(), and start_taskdup().
loadCharLen()
static int loadCharLen (SPTR lensym) static
Definition at line 1349 of file outliner.cpp.
References ad3ili(), addnme(), mk_address(), MSZ_I8, MSZ_WORD, and NT_VAR.
Referenced by loadUplevelArgsForRegion().
loadUplevelArgsForRegion()
static int loadUplevelArgsForRegion (SPTR uplevel, SPTR taskAllocSptr, int count, int uplevel_stblk_sptr) static
Definition at line 1428 of file outliner.cpp.
References ad2ili(), ad4ili(), ad_acon(), addnme(), addr, aux, CHARLEN_64BIT, chk_block(), count, AUX::curr_entry, ENTRY::display, DT_CPTR, DTyAlgTyMember, gbl, getThreadPrivateTp(), handle_nested_threadprivate(), i, if(), is_llvm_local_private(), ISZ_T, ll_parent_vals_count(), llGetThreadprivateAddr(), llmp_get_uplevel(), llmp_has_uplevel(), llmp_outermost_uplevel(), loadCharLen(), member_with_offset(), mk_address(), mk_argasym(), MSZ_I8, MSZ_PTR, MSZ_WORD, need_charlen(), NT_IND, NT_MEM, NT_VAR, NULL, offset, sel_iconv(), size_of(), sptr, SPTR_NULL, sym_is_refd(), taskAllocSptr, toUplevelAddr(), val, LLUplevel::vals, LLUplevel::vals_count, and XBIT.
Referenced by ll_load_outlined_args().
makeOutlinedFunc()
static SPTR makeOutlinedFunc (int stblk_sptr, int scope_sptr, bool is_task, bool istaskdup, bool isompaccel, ILM_OP opc) static
Definition at line 737 of file outliner.cpp.
References args, DBGBIT, DT_VOID_NONE, dump_parsyms(), FALSE, FUNCLINEP, funcSig, gbl, GBL_CURRFUNC, get_opc_name(), getsymbol(), ll_get_outlined_funcname(), llMakeFtnOutlinedSignature(), SYMNAME, taskdupSig, taskSig, and update_acc_with_fn().
Referenced by ll_make_outlined_func(), ll_make_outlined_func_wopc(), ll_make_outlined_omptarget_func(), ll_make_outlined_task(), and llMakeTaskdupRoutine().
member_with_offset()
static SPTR member_with_offset (SPTR member, int offset) static
Definition at line 1410 of file outliner.cpp.
References m, NOSYM, offset, and SPTR_NULL.
Referenced by loadUplevelArgsForRegion().
mk_function_call()
int mk_function_call (DTYPE ret_dtype, int n_args, DTYPE * arg_dtypes, int * arg_ilis, SPTR func_sptr)
Definition at line 2259 of file outliner.cpp.
References ad3ili(), ALLOCA, i, ILI_ALT, ILI_OPND, ll_ad_outlined_func2(), ll_make_outlined_garg(), and ll_process_routine_parameters().
outlined_is_eliminated()
bool outlined_is_eliminated (ILM_OP opc)
test whether do outlining elision for the current opc or not.
Definition at line 2302 of file outliner.cpp.
outlined_need_recompile()
bool outlined_need_recompile ()
test whether recompile the ILMs or not.
Definition at line 2308 of file outliner.cpp.
outliner_nextstate()
static outliner_states_t outliner_nextstate () static
Definition at line 836 of file outliner.cpp.
References gbl, hasILMRewrite, outl_state, outliner_active_host_par1, outliner_active_host_par2, outliner_active_switchfile, outliner_not_active, outliner_reset, par_file1, par_file2, and set_outliner_state().
Referenced by ll_reset_parfile().
resetThreadprivate()
static void resetThreadprivate (void) static
Definition at line 1869 of file outliner.cpp.
References gbl, and NOSYM.
Referenced by ll_reset_parfile(), and ll_reset_parfile_().
restartRewritingILM()
void restartRewritingILM (int curilm)
...
Definition at line 2103 of file outliner.cpp.
References gbl, ILMB::ilmavl, ilmb, len, llGetILMLen(), llWriteNopILM(), par_curfile, pos, setRewritingILM(), and t.
Referenced by exp_smp().
set_ilmfile()
static void set_ilmfile (FILE * file) static
Definition at line 174 of file outliner.cpp.
References dump_ilmfile_state(), FILE, gbl, and prev.
Referenced by ll_reset_parfile().
set_outliner_state()
void set_outliner_state (outliner_states_t next)
Definition at line 152 of file outliner.cpp.
References DBGBIT, gbl, GBL_CURRFUNC, next, outl_state, outliner_state_names, and SYMNAME.
Referenced by outliner_nextstate().
setOutlinedPragma()
void setOutlinedPragma (int func_sptr, int saved)
...
Definition at line 732 of file outliner.cpp.
setRewritingILM()
void setRewritingILM (void)
...
Definition at line 2219 of file outliner.cpp.
References isRewritingILM.
Referenced by ll_write_ilm_header(), and restartRewritingILM().
start_taskdup()
void start_taskdup (int task_fnsptr, int curilm)
...
Definition at line 2054 of file outliner.cpp.
References allocTaskdup(), gbl, ILMB::ilmavl, ilmb, len, llGetILMLen(), llMakeTaskdupRoutine(), llWriteNopILM(), pos, t, t2, t3, TASKDUP_AVL, TASKDUP_FILE, and writeTaskdup.
Referenced by exp_smp().
stop_taskdup()
void stop_taskdup (int task_fnsptr, int curilm)
...
Definition at line 2126 of file outliner.cpp.
References ilm_outlined_pad_ilm(), pos, and writeTaskdup.
Referenced by exp_smp().
toUplevelAddr()
static int toUplevelAddr (SPTR taskAllocSptr, SPTR uplevel, int offset) static
Definition at line 1360 of file outliner.cpp.
References ad2ili(), ad3ili(), ad_acon(), ad_aconi(), addnme(), addr, GBL_CURRFUNC, IL_AADD, NT_IND, NT_VAR, offset, SPTR_NULL, and taskAllocSptr.
Referenced by handle_nested_threadprivate(), and loadUplevelArgsForRegion().
unsetRewritingILM()
void unsetRewritingILM (void)
...
Definition at line 2213 of file outliner.cpp.
References isRewritingILM.
Referenced by decrOutlinedCnt(), and exp_smp().
update_acc_with_fn()
void update_acc_with_fn (int fnsptr)
...
Definition at line 537 of file outliner.cpp.
Referenced by makeOutlinedFunc(), and mk_kmpc_api_call().
update_acc_with_fn_flags()
void update_acc_with_fn_flags (int fnsptr, int flags)
Definition at line 533 of file outliner.cpp.
Variable Documentation
funcCnt
int funcCnt = 0 static
Definition at line 64 of file outliner.cpp.
Referenced by ll_get_outlined_funcname().
funcSig
const KMPC_ST_TYPE funcSig[3] static
Initial value:
= {
    {NULL, DT_INT,  false, 0},
    {NULL, DT_CPTR, false, 0},
    {NULL, DT_CPTR, false, 0}
}
Definition at line 714 of file outliner.cpp.
Referenced by makeOutlinedFunc().
gtid
SPTR gtid static
Definition at line 67 of file outliner.cpp.
Referenced by _mp_get_threadprivate(), ll_get_gtid(), ll_get_gtid_addr_ili(), ll_get_gtid_val_ili(), ll_reset_gtid(), llGetSym(), llLoadGtid(), and processOutlinedByConcur().
hasILMRewrite
bool hasILMRewrite static
Definition at line 62 of file outliner.cpp.
Referenced by finish_taskdup_routine(), ll_has_more_outlined(), ll_reset_parfile(), ll_reset_parfile_(), ll_write_ilm_header(), llProcessNextTmpfile(), and outliner_nextstate().
ilmfile_states
const char* ilmfile_states[] = {"ORIGINAL", "PARFILE1", "PARFILE2" }
Definition at line 132 of file outliner.cpp.
Referenced by get_file_state().
isRewritingILM
bool isRewritingILM static
Definition at line 63 of file outliner.cpp.
Referenced by dump_outliner(), ll_ilm_is_rewriting(), ll_rewrite_ilms(), llWriteNopILM(), setRewritingILM(), and unsetRewritingILM().
llvmUniqueSym
int llvmUniqueSym static
Definition at line 65 of file outliner.cpp.
Referenced by llvm_get_unique_sym(), and llvm_set_unique_sym().
orig_ilmfil
FILE* orig_ilmfil
Definition at line 54 of file outliner.cpp.
Referenced by get_file_state(), ll_reset_parfile(), and ll_reset_parfile_().
outl_state
outliner_states_t outl_state = outliner_not_active static
Definition at line 149 of file outliner.cpp.
Referenced by dump_outliner(), ll_reset_parfile(), outliner_nextstate(), and set_outliner_state().
outliner_state_names
const char* outliner_state_names[] = {"Inactive", "Parfile1", "ParFile2", "SwitchParFiles", "Reset", "Error"}
Definition at line 133 of file outliner.cpp.
Referenced by dump_outliner(), and set_outliner_state().
par_curfile
FILE* par_curfile = NULL
Definition at line 57 of file outliner.cpp.
Referenced by finish_taskdup_routine(), ll_reset_parfile(), ll_reset_parfile_(), ll_rewrite_ilms(), ll_write_ilm_end(), ll_write_ilm_header(), llWriteNopILM(), and restartRewritingILM().
par_file1
FILE* par_file1 = NULL
Definition at line 55 of file outliner.cpp.
Referenced by get_file_state(), ll_open_parfiles(), ll_reset_parfile(), ll_reset_parfile_(), ll_unlink_parfiles(), ll_write_ilm_header(), llProcessNextTmpfile(), llvm_ilms_rewrite_mode(), and outliner_nextstate().
par_file2
FILE* par_file2 = NULL
Definition at line 56 of file outliner.cpp.
Referenced by get_file_state(), ll_open_parfiles(), ll_reset_parfile(), ll_reset_parfile_(), ll_unlink_parfiles(), llProcessNextTmpfile(), llvm_ilms_rewrite_mode(), and outliner_nextstate().
parFileNm1
char parFileNm1[MAX_PARFILE_LEN] static
Definition at line 60 of file outliner.cpp.
Referenced by ll_open_parfiles(), and ll_unlink_parfiles().
parFileNm2
char parFileNm2[MAX_PARFILE_LEN] static
Definition at line 61 of file outliner.cpp.
Referenced by ll_open_parfiles(), and ll_unlink_parfiles().
pos
int pos static
Definition at line 69 of file outliner.cpp.
Referenced by __fortio_rwinit(), __INT_T(), _f90io_backspace(), add_mask_calls(), add_stmt_calls(), call_format_double(), check_desc(), collectIncludePaths(), conv_forall(), crunch(), dovec(), e74_arg(), ENT3F(), ENTCRF90IO(), ENTF90IO(), find_calls_pos(), find_max_of_mask_calls_pos(), finish_taskdup_routine(), fmt_putchar(), Ftn_imvbits(), Ftn_jmvbits(), Ftn_kmvbits(), get_exttype_default(), get_keyword_args(), get_keyword_components(), inquire(), is_optional_char_dummy(), is_same_mask_in_fused(), kwd_match(), ll_create_anon_struct_type(), ll_create_function_type(), ll_rewrite_ilms(), make_equiv_ss(), need_copyout(), position_finder(), pp_entries(), pp_entries_mixedstrlen(), put_calls(), rdgilms(), restartRewritingILM(), semant3(), set_ilmpos(), set_pass_objects(), start_taskdup(), stop_taskdup(), stride_1_dummy(), stride_1_section(), and sum_scatter_args().
savedILMFil
FILE* savedILMFil = NULL static
Definition at line 59 of file outliner.cpp.
Referenced by ll_reset_parfile(), ll_reset_parfile_(), and llRestoreSavedILFil().
taskdup
struct taskdupSt taskdup static
taskdupSig
const KMPC_ST_TYPE taskdupSig[3] static
Initial value:
= {
    {NULL, DT_CPTR, false, 0},
    {NULL, DT_CPTR, false, 0},
    {NULL, DT_INT,  true,  0}
}
Definition at line 725 of file outliner.cpp.
Referenced by makeOutlinedFunc().
taskSig
const KMPC_ST_TYPE taskSig[2] static
Initial value:
= {
    {NULL, DT_INT,  true,  0},
    {NULL, DT_CPTR, false, 0}
}
Definition at line 720 of file outliner.cpp.
Referenced by makeOutlinedFunc().
uplevelSym
SPTR uplevelSym static
Definition at line 66 of file outliner.cpp.
Referenced by createUplevelSptr(), ll_get_uplevel_sym(), ll_load_outlined_args(), and ll_reset_outlined_func().
writeTaskdup
bool writeTaskdup static
Definition at line 68 of file outliner.cpp.
Referenced by finish_taskdup_routine(), ll_rewrite_ilms(), llWriteNopILM(), start_taskdup(), and stop_taskdup().