flang: p_rpowi.c File Reference
p_rpowi.c File Reference
#include "mthdecls.h"
Functions
float __pmth_i_rpowk (float x4, long long i8)
float __pmth_i_rpowi (float x4, int i4)
Function Documentation
__pmth_i_rpowi()
float __pmth_i_rpowi (float x4, int i4)
Definition at line 52 of file p_rpowi.c.
References __pmth_i_rpowk(), i4, and x4.
Referenced by __px_powi1_4(), __px_powi1_4m(), __px_powi_4(), __px_powi_4m(), __py_powi1_8(), __py_powi1_8m(), __py_powi_8(), __py_powi_8m(), __pz_powi1_16(), __pz_powi1_16m(), __pz_powi_16(), and __pz_powi_16m().
__pmth_i_rpowk()
float __pmth_i_rpowk (float x4, long long i8)
Definition at line 20 of file p_rpowi.c.
References i8, k, r8, x4, and x8.
Referenced by __pmth_i_rpowi(), __px_powk1_4(), __px_powk1_4m(), __px_powk_4(), __px_powk_4m(), __py_powk1_8(), __py_powk1_8m(), __py_powk_8(), __py_powk_8m(), __pz_powk1_16(), __pz_powk1_16m(), __pz_powk_16(), and __pz_powk_16m().