flang: pack.c File Reference
pack.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
Functions
static int I8() next_index (__INT_T *index, F90_Desc *s)
void ENTFTN (PACK, pack)
void ENTFTN (PACKCA, packca)
void ENTFTN (PACKC, packc)
void ENTFTN (PACKZ, packz)
void ENTFTN (PACKZCA, packzca)
void ENTFTN (PACKZC, packzc)
void ENTFTN (UNPACK, unpack)
void ENTFTN (UNPACKCA, unpackca)
void ENTFTN (UNPACKC, unpackc)
Variables
void(* __fort_scalar_copy [__NTYPES])(void *rp, void *sp, int len)
Function Documentation
ENTFTN() [1/9]
void ENTFTN (PACK , pack)
Definition at line 34 of file pack.c.
References __DESC, __fort_abort(), __fort_get_scalar(), __fort_local_address(), __fort_varying_log(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, DIST_SCOFF_G, F90_DIM_LBOUND_G, F90_GSIZE_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_MASK_INT1, GET_DIST_MASK_INT2, GET_DIST_MASK_INT4, GET_DIST_MASK_INT8, GET_DIST_MASK_LOG1, GET_DIST_MASK_LOG2, GET_DIST_MASK_LOG4, GET_DIST_MASK_LOG8, GET_DIST_SIZE_OF, i, I8, ISSCALAR, MAXDIMS, next_index(), NULL, rb, result, tmp, and TYPEKIND.
Referenced by ENTFTN().
ENTFTN() [2/9]
void ENTFTN (PACKC , packc)
Definition at line 164 of file pack.c.
References __CLEN_T, CADR, CLEN, ENTFTN(), rb, and result.
ENTFTN() [3/9]
void ENTFTN (PACKCA , packca)
Definition at line 148 of file pack.c.
References CADR, ENTFTN(), PACK, rb, and result.
ENTFTN() [4/9]
void ENTFTN (PACKZ , packz)
Definition at line 183 of file pack.c.
References __DESC, __fort_abort(), __fort_get_scalar(), __fort_local_address(), __fort_varying_log(), __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, DIST_SCOFF_G, F90_DIM_LBOUND_G, F90_GSIZE_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_MASK_INT1, GET_DIST_MASK_INT2, GET_DIST_MASK_INT4, GET_DIST_MASK_INT8, GET_DIST_MASK_LOG1, GET_DIST_MASK_LOG2, GET_DIST_MASK_LOG4, GET_DIST_MASK_LOG8, GET_DIST_SIZE_OF, i, I8, ISSCALAR, MAXDIMS, next_index(), NULL, rb, result, tmp, and TYPEKIND.
ENTFTN() [5/9]
void ENTFTN (PACKZC , packzc)
Definition at line 289 of file pack.c.
References __CLEN_T, CADR, CLEN, ENTFTN(), rb, and result.
ENTFTN() [6/9]
void ENTFTN (PACKZCA , packzca)
Definition at line 276 of file pack.c.
References CADR, ENTFTN(), rb, and result.
ENTFTN() [7/9]
void ENTFTN (UNPACK , unpack)
Definition at line 305 of file pack.c.
References __DESC, __fort_abort(), __fort_get_scalar(), __fort_local_address(), __fort_scalar_copy, __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, DIST_SCOFF_G, F90_DIM_LBOUND_G, F90_GSIZE_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_MASK_INT1, GET_DIST_MASK_INT2, GET_DIST_MASK_INT4, GET_DIST_MASK_INT8, GET_DIST_MASK_LOG1, GET_DIST_MASK_LOG2, GET_DIST_MASK_LOG4, GET_DIST_MASK_LOG8, i, I8, ISSCALAR, MAXDIMS, next_index(), NULL, rb, result, and tmp.
ENTFTN() [8/9]
void ENTFTN (UNPACKC , unpackc)
Definition at line 424 of file pack.c.
References __CLEN_T, CADR, CLEN, ENTFTN(), rb, and result.
ENTFTN() [9/9]
void ENTFTN (UNPACKCA , unpackca)
Definition at line 408 of file pack.c.
References CADR, ENTFTN(), rb, and result.
next_index()
static int I8() next_index (__INT_T * index, F90_Desc * s) static
Definition at line 17 of file pack.c.
References DIM_UBOUND_G, F90_DIM_LBOUND_G, F90_RANK_G, i, index, and s.
Referenced by ENTFTN().
Variable Documentation
__fort_scalar_copy
void(* __fort_scalar_copy[__NTYPES])(void *rp, void *sp, int len) (void * rp, void * sp, int len) extern
Referenced by ENTFTN().