flang: parser.c File Reference
parser.c File Reference
Fortran parser module.
#include "ccffinfo.h"
#include "gbldefs.h"
#include "gramtk.h"
#include "gramsm.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "semant.h"
#include "semstk.h"
#include "gramdf.h"
#include "proddf.h"
#include "tokdf.h"
#include "scan.h"
Macros
#define LOOP while (TRUE)
#define NOSTATE ((int)(-1))
Typedefs
typedef short int PSTACK
Functions
static int next_state (int, int)
static LOGICAL is_declaration (int)
static void _parser (void)
static char * prettytoken (int, INT)
void parser (void)
void parse_init (void)
LOGICAL is_executable (int tkntyp)
void dumpsst (SST *stk)
void dumppstack (void)
Variables
static PSTACK * pstack
static int sst_size = 0
static int cstate
static int stktop
static INT ctknval
static void(* p_semant1 [])(int, SST *) = {semant1, semant1}
static void(* p_semant2 [])(int, SST *) = {NULL, semant2}
static void(* p_semant3 [])(int, SST *) = {psemant3, semant3}
static void(* p_semantio [])(int, SST *) = {psemantio, semantio}
static void(* p_semsmp [])(int, SST *) = {psemsmp, semsmp}
static FILE * dfile = NULL
Detailed Description
Fortran parser module.
contents:
parser() - parse and semantically analyze one user subprogram unit. parse_init() - initialize parsing of new statement. next_state(state, tkntyp) - look up next state in parse tables. prettytoken(tkntyp, tknval) - returns string of token
Definition in file parser.c.
Macro Definition Documentation
LOOP
#define LOOP while (TRUE)
Definition at line 37 of file parser.c.
NOSTATE
#define NOSTATE ((int)(-1))
Definition at line 38 of file parser.c.
Typedef Documentation
PSTACK
typedef short int PSTACK
Definition at line 40 of file parser.c.
Function Documentation
_parser()
static void _parser (void) static
Definition at line 175 of file parser.c.
References assert, CNULL, cstate, ctknval, DBGBIT, DEBUG, end, SCN::end_program_unit, error(), errsev(), FALSE, FREE, gbl, get_token(), getCurrColumn(), i, SCN::id, SEM::ignore_stmt, interr(), is_declaration(), len, lhs, LOOP, SEM::mod_cnt, SEM::mod_sym, SCN::multiple_stmts, SCN::name, NEW, next_state(), NOSTATE, NULL, p_semant1, p_semant2, p_semant3, p_semantio, p_semsmp, parse_init(), prettytoken(), psemant2(), SEM::psfunc, pstack, sccrelal(), scn, sem, semant1(), semant2(), sst, SST_COLUMNP, SST_LINENOP, sst_size, SST_SIZE, SST_SYMP, start, stktop, SEM::submod_sym, t, TK_COMMA, TK_IDENT, tkntyp, SEM::tkntyp, TRUE, SEM::type_mode, and SEM::which_pass.
Referenced by parser().
dumppstack()
void dumppstack (void)
Definition at line 977 of file parser.c.
References dfile, dumpsst(), gbl, i, and stktop.
dumpsst()
void dumpsst (SST * stk)
Definition at line 900 of file parser.c.
References ast, dfile, dump_ast_tree(), gbl, S_ACONST, S_CONST, S_DERIVED, S_EXPR, S_IDENT, S_KEYWORD, S_LABEL, S_LOGEXPR, S_LVALUE, S_NULL, S_REF, S_SCONST, S_STAR, S_STFUNC, S_TRIPLE, S_VAL, sptr, SST_ALIASG, SST_ASTG, SST_IDG, SST_PARENG, SST_SYMG, stb, stk, and SYMNAME.
Referenced by dumppstack().
is_declaration()
static LOGICAL is_declaration (int tkntyp) static
Definition at line 776 of file parser.c.
References FALSE, tkntyp, and TRUE.
Referenced by _parser(), and is_executable().
is_executable()
LOGICAL is_executable (int tkntyp)
Definition at line 891 of file parser.c.
References is_declaration(), and tkntyp.
Referenced by semant1().
next_state()
static int next_state (int state, int tkntyp) static
Definition at line 426 of file parser.c.
References end, NOSTATE, start, t, and tkntyp.
Referenced by _parser().
parse_init()
void parse_init (void)
Definition at line 411 of file parser.c.
References cstate, pstack, scan_reset(), and stktop.
Referenced by _get_token(), and _parser().
parser()
void parser (void)
Definition at line 60 of file parser.c.
References _parser(), DBGBIT, end_module(), errini(), FALSE, fe_init(), fe_restart(), gbl, get_bss_addr(), ISZ_T, SEM::mod_cnt, SEM::mod_sym, p_semant1, p_semant2, reinit(), reset_internal_subprograms(), resolve_fwd_refs(), RU_BDATA, sem, semant1(), semant2(), set_allfiles(), set_bss_addr(), SEM::submod_sym, summary(), TRUE, SEM::which_pass, and XBIT.
Referenced by add_generic_argument(), create_arg_parser(), destroy_arg_parser(), parse_arguments(), register_action_map_arg(), register_boolean_arg(), register_combined_bool_string_arg(), register_filename_arg(), register_inform_level_arg(), register_integer_arg(), register_qflag_arg(), register_string_arg(), register_string_list_arg(), register_xflag_arg(), register_yflag_arg(), and was_value_set().
prettytoken()
static char * prettytoken (int tkntyp, INT tknval) static
Definition at line 447 of file parser.c.
References cprintf(), getprint(), SCN::id, STB::n_base, SCN::name, SCFTN_TRUE, scn, stb, TK_IDENT, tkntyp, and tknval.
Referenced by _parser().
Variable Documentation
cstate
int cstate static
Definition at line 43 of file parser.c.
Referenced by _parser(), and parse_init().
ctknval
INT ctknval static
Definition at line 45 of file parser.c.
Referenced by _parser().
dfile
FILE* dfile = NULL static
Definition at line 897 of file parser.c.
Referenced by dumppstack(), and dumpsst().
p_semant1
void(* p_semant1[])(int, SST *) (int , SST *) = {semant1, semant1} static
Definition at line 50 of file parser.c.
Referenced by _parser(), and parser().
p_semant2
void(* p_semant2[])(int, SST *) (int , SST *) = {NULL, semant2} static
Definition at line 51 of file parser.c.
Referenced by _parser(), and parser().
p_semant3
void(* p_semant3[])(int, SST *) (int , SST *) = {psemant3, semant3} static
Definition at line 52 of file parser.c.
Referenced by _parser().
p_semantio
void(* p_semantio[])(int, SST *) (int , SST *) = {psemantio, semantio} static
Definition at line 53 of file parser.c.
Referenced by _parser().
p_semsmp
void(* p_semsmp[])(int, SST *) (int , SST *) = {psemsmp, semsmp} static
Definition at line 54 of file parser.c.
Referenced by _parser().
pstack
PSTACK* pstack static
Definition at line 41 of file parser.c.
Referenced by _parser(), and parse_init().
sst_size
int sst_size = 0 static
Definition at line 42 of file parser.c.
Referenced by _parser().
stktop
int stktop static
Definition at line 44 of file parser.c.
Referenced by _parser(), assign(), assign_intrinsic_to_pointer(), assign_pointer(), ch_substring(), chksubstr(), defined_operator(), dumppstack(), fix_proc_pointer_call(), fix_term(), func_call(), func_call2(), generic_call(), generic_func(), generic_tbp_call(), generic_tbp_func(), is_intrinsic_opr(), mkvarref(), parse_init(), ptrfunc_call(), ptrsubr_call(), ref_array(), ref_intrin(), ref_intrin_subr(), ref_pd(), ref_pd_subr(), ref_stfunc(), resolve_defined_io(), resolve_generic(), subr_call(), subr_call2(), and valid_assign_pointer_types().