flang: path-utils.c File Reference
path-utils.c File Reference
Path name manipulation utilities.
#include "legacy-util-api.h"
#include <stddef.h>
#include <string.h>
#include <unistd.h>
Functions
void basenam (const char *orig_path, const char *optional_suffix, char *basename)
void dirnam (const char *orig_path, char *dirname)
int fndpath (const char *target, char *path, size_t max_length, const char *dirlist)
char * mkperm (char *pattern, const char *oldext, const char *newext)
Detailed Description
Path name manipulation utilities.
Implement the legacy path name utility functions.
Definition in file path-utils.c.
Function Documentation
basenam()
void basenam (const char * orig_path, const char * optional_suffix, char * basename)
Definition at line 21 of file path-utils.c.
References fn, length(), NULL, and strlen().
Referenced by import_module_print(), and init().
dirnam()
void dirnam (const char * orig_path, char * dirname)
Definition at line 44 of file path-utils.c.
References dirname, length(), and NULL.
Referenced by _doincl(), accpp(), doincl(), fpp(), and scan_include().
fndpath()
int fndpath (const char * target, char * path, size_t max_length, const char * dirlist)
Definition at line 59 of file path-utils.c.
References access, end, NULL, p, path, and strlen().
Referenced by _doincl(), doincl(), extractor_end(), get_module_file_name(), get_module_file_name_from_user(), load_inline_file(), load_TOC(), push_include(), and scan_include().
mkperm()
char * mkperm (char * pattern, const char * oldext, const char * newext)
Definition at line 99 of file path-utils.c.
References length(), and strlen().
Referenced by mkfname().