flang: pgcpuid.c File Reference
pgcpuid.c File Reference
#include <stdint.h>
#include "pgcpuid.h"
Functions
int __pgi_cpuid_getmax (uint32_t f)
returns false/true if CPUID supports eax function. __pgi_cpuid_getma (uint32_t cpuid_func)
int __pgi_cpuid_ecx (uint32_t f, uint32_t *r, uint32_t c)
returns results of executing CPUID with function cpuid_func and sub function ecx. __pgi_cpuid_ecx(uint32_t cpuid_func, uint32_t *res, uint32_t ecx)
int __pgi_cpuid (uint32_t f, uint32_t *r)
returns results of executing CPUID with function cpuid_func. __pgi_cpuid(uint32_t cpuid_func, uint32_t *res)
int __pgcpuid (uint32_t f, uint32_t *r)
returns results of executing CPUID with function cpuid_func. __pgcpuid(uint32_t cpuid_func, uint32_t *res)
int __pgi_getbv (uint32_t f, uint64_t *r)
read extended control register. __pgi_getbv(uint32_t xcr_num, uint64_t *xcr_res)
Function Documentation
__pgcpuid()
int __pgcpuid (uint32_t f, uint32_t * r)
returns results of executing CPUID with function cpuid_func. __pgcpuid(uint32_t cpuid_func, uint32_t *res)
Parameters
cpuid_func (I1) function to execute CPUID with
res (I2) pointer to buffer to store eax, ebx, ecx, edx
Returns false(0): if cpuid_func not supported true(1): CPUID successfully executed with cpuid_func and: res[0]=eax, res[1]=ebx, res[2]=ecx, res[3]=edx
Definition at line 96 of file pgcpuid.c.
References __pgi_cpuid_ecx(), f, and r.
__pgi_cpuid()
int __pgi_cpuid (uint32_t f, uint32_t * r)
returns results of executing CPUID with function cpuid_func. __pgi_cpuid(uint32_t cpuid_func, uint32_t *res)
Parameters
cpuid_func (I1) function to execute CPUID with
res (I2) pointer to buffer to store eax, ebx, ecx, edx
Returns false(0): if cpuid_func not supported true(1): CPUID successfully executed with cpuid_func and: res[0]=eax, res[1]=ebx, res[2]=ecx, res[3]=edx
Definition at line 79 of file pgcpuid.c.
References __pgi_cpuid_ecx(), f, and r.
Referenced by idcache().
__pgi_cpuid_ecx()
int __pgi_cpuid_ecx (uint32_t f, uint32_t * r, uint32_t c)
returns results of executing CPUID with function cpuid_func and sub function ecx. __pgi_cpuid_ecx(uint32_t cpuid_func, uint32_t *res, uint32_t ecx)
Parameters
cpuid_func (I1) function to execute CPUID with
res (I2) pointer to buffer to store eax, ebx, ecx, edx
ecx (I3) value of ecx to execute CPUID with
Returns false(0): if cpuid_func not supported true(1): CPUID successfully executed with cpuid_func+ecx and: res[0]=eax, res[1]=ebx, res[2]=ecx, res[3]=edx
Definition at line 56 of file pgcpuid.c.
References __pgi_cpuid_getmax(), f, and r.
Referenced by __pgcpuid(), __pgi_cpuid(), ia_cores(), ia_unifiedcache(), is_avx2(), is_avx512f(), and is_avx512vl().
__pgi_cpuid_getmax()
int __pgi_cpuid_getmax (uint32_t f)
returns false/true if CPUID supports eax function. __pgi_cpuid_getma (uint32_t cpuid_func)
Parameters
cpuid_func (I1) function to execute CPUID with
Returns false(0)/true(1)
Definition at line 27 of file pgcpuid.c.
References f.
Referenced by __pgi_cpuid_ecx().
__pgi_getbv()
int __pgi_getbv (uint32_t f, uint64_t * r)
read extended control register. __pgi_getbv(uint32_t xcr_num, uint64_t *xcr_res)
Parameters
xcr_num (I1) extended control register number to read
xcr_res (I2) pointer to buffer to store xcr[xcr_num]
Returns true(1) with: xcr_res[31: 0]=eax xcr_res[63:32]=edx
Definition at line 112 of file pgcpuid.c.
References f, and r.
Referenced by is_xcr_set().