flang: pgcpuid.h File Reference
pgcpuid.h File Reference
#include <stdint.h>
Classes
union CPU0
union CPU80
union Xname
union ICPU1
union ICPU2
struct ICPU2::Int_Cache
union ICPU4
union ICPU5
union ICPU6
union ICPU7
union ICPU81
union ICPU86
union ICPU88
union ACPU1
union ACPU7
union ACPU81
union ACPU85
union ACPU86
union ACPU87
union ACPU88
union ACPU81e
Macros
#define x80 0x80000000U
Typedefs
typedef union CPU0 CPU0
typedef union CPU80 CPU80
typedef union Xname Xname
typedef union ICPU1 ICPU1
typedef union ICPU2 ICPU2
typedef union ICPU4 ICPU4
typedef union ICPU5 ICPU5
typedef union ICPU6 ICPU6
typedef union ICPU7 ICPU7
typedef union ICPU81 ICPU81
typedef union ICPU86 ICPU86
typedef union ICPU88 ICPU88
typedef union ACPU1 ACPU1
typedef union ACPU7 ACPU7
typedef union ACPU81 ACPU81
typedef union ACPU85 ACPU85
typedef union ACPU86 ACPU86
typedef union ACPU87 ACPU87
typedef union ACPU88 ACPU88
typedef union ACPU81e ACPU81e
Enumerations
enum RES4_E { RES4_EAX = 0 , RES4_EBX = 1 , RES4_ECX = 2 , RES4_EDX = 3 }
Functions
int __pgi_cpuid_getmax (uint32_t)
returns false/true if CPUID supports eax function. __pgi_cpuid_getma (uint32_t cpuid_func)
int __pgi_cpuid (uint32_t, uint32_t *)
returns results of executing CPUID with function cpuid_func. __pgi_cpuid(uint32_t cpuid_func, uint32_t *res)
int __pgcpuid (uint32_t, uint32_t *)
returns results of executing CPUID with function cpuid_func. __pgcpuid(uint32_t cpuid_func, uint32_t *res)
int __pgi_cpuid_ecx (uint32_t, uint32_t *, uint32_t)
returns results of executing CPUID with function cpuid_func and sub function ecx. __pgi_cpuid_ecx(uint32_t cpuid_func, uint32_t *res, uint32_t ecx)
int __pgi_getbv (uint32_t, uint64_t *)
read extended control register. __pgi_getbv(uint32_t xcr_num, uint64_t *xcr_res)
Macro Definition Documentation
x80
#define x80 0x80000000U
Definition at line 1010 of file pgcpuid.h.
Typedef Documentation
ACPU1
typedef union ACPU1 ACPU1
ACPU7
typedef union ACPU7 ACPU7
ACPU81
typedef union ACPU81 ACPU81
ACPU81e
typedef union ACPU81e ACPU81e
ACPU85
typedef union ACPU85 ACPU85
ACPU86
typedef union ACPU86 ACPU86
ACPU87
typedef union ACPU87 ACPU87
ACPU88
typedef union ACPU88 ACPU88
CPU0
typedef union CPU0 CPU0
CPU80
typedef union CPU80 CPU80
ICPU1
typedef union ICPU1 ICPU1
ICPU2
typedef union ICPU2 ICPU2
ICPU4
typedef union ICPU4 ICPU4
ICPU5
typedef union ICPU5 ICPU5
ICPU6
typedef union ICPU6 ICPU6
ICPU7
typedef union ICPU7 ICPU7
ICPU81
typedef union ICPU81 ICPU81
ICPU86
typedef union ICPU86 ICPU86
ICPU88
typedef union ICPU88 ICPU88
Xname
typedef union Xname Xname
Enumeration Type Documentation
RES4_E
enum RES4_E
Enumerator
RES4_EAX
RES4_EBX
RES4_ECX
RES4_EDX
Definition at line 10 of file pgcpuid.h.
Function Documentation
__pgcpuid()
int __pgcpuid (uint32_t f, uint32_t * r)
returns results of executing CPUID with function cpuid_func. __pgcpuid(uint32_t cpuid_func, uint32_t *res)
Parameters
cpuid_func (I1) function to execute CPUID with
res (I2) pointer to buffer to store eax, ebx, ecx, edx
Returns false(0): if cpuid_func not supported true(1): CPUID successfully executed with cpuid_func and: res[0]=eax, res[1]=ebx, res[2]=ecx, res[3]=edx
Definition at line 96 of file pgcpuid.c.
References __pgi_cpuid_ecx(), f, and r.
__pgi_cpuid()
int __pgi_cpuid (uint32_t f, uint32_t * r)
returns results of executing CPUID with function cpuid_func. __pgi_cpuid(uint32_t cpuid_func, uint32_t *res)
Parameters
cpuid_func (I1) function to execute CPUID with
res (I2) pointer to buffer to store eax, ebx, ecx, edx
Returns false(0): if cpuid_func not supported true(1): CPUID successfully executed with cpuid_func and: res[0]=eax, res[1]=ebx, res[2]=ecx, res[3]=edx
Definition at line 79 of file pgcpuid.c.
References __pgi_cpuid_ecx(), f, and r.
Referenced by idcache().
__pgi_cpuid_ecx()
int __pgi_cpuid_ecx (uint32_t f, uint32_t * r, uint32_t c)
returns results of executing CPUID with function cpuid_func and sub function ecx. __pgi_cpuid_ecx(uint32_t cpuid_func, uint32_t *res, uint32_t ecx)
Parameters
cpuid_func (I1) function to execute CPUID with
res (I2) pointer to buffer to store eax, ebx, ecx, edx
ecx (I3) value of ecx to execute CPUID with
Returns false(0): if cpuid_func not supported true(1): CPUID successfully executed with cpuid_func+ecx and: res[0]=eax, res[1]=ebx, res[2]=ecx, res[3]=edx
Definition at line 56 of file pgcpuid.c.
References __pgi_cpuid_getmax(), f, and r.
Referenced by __pgcpuid(), __pgi_cpuid(), ia_cores(), ia_unifiedcache(), is_avx2(), is_avx512f(), and is_avx512vl().
__pgi_cpuid_getmax()
int __pgi_cpuid_getmax (uint32_t f)
returns false/true if CPUID supports eax function. __pgi_cpuid_getma (uint32_t cpuid_func)
Parameters
cpuid_func (I1) function to execute CPUID with
Returns false(0)/true(1)
Definition at line 27 of file pgcpuid.c.
References f.
Referenced by __pgi_cpuid_ecx().
__pgi_getbv()
int __pgi_getbv (uint32_t f, uint64_t * r)
read extended control register. __pgi_getbv(uint32_t xcr_num, uint64_t *xcr_res)
Parameters
xcr_num (I1) extended control register number to read
xcr_res (I2) pointer to buffer to store xcr[xcr_num]
Returns true(1) with: xcr_res[31: 0]=eax xcr_res[63:32]=edx
Definition at line 112 of file pgcpuid.c.
References f, and r.
Referenced by is_xcr_set().