flang: pgerror.h File Reference
pgerror.h File Reference
Error handling and reporting.
#include "universal.h"
Macros
#define assert(cond, txt, val, sev)
#define DEBUG_ASSERT(cond, txt) ((void)0)
If DEBUG!=0 and cond is false, emit an internal compiler error.
Typedefs
typedef BEGIN_DECL_WITH_C_LINKAGE enum error_severity error_severity
Severity of an error message.
typedef enum error_code error_code_t
Error code type.
Enumerations
enum error_severity {
ERR_unused = 0 , ERR_Informational = 1 , ERR_Warning = 2 , ERR_Severe = 3 ,
ERR_Fatal = 4 , ERR_SEVERITY_SIZE
}
Severity of an error message.
Functions
void interr (const char *txt, int val, enum error_severity sev)
Assert that cond is true, and emit an internal compiler error otherwise.
Detailed Description
Error handling and reporting.
Definition in file pgerror.h.
Macro Definition Documentation
assert
#define assert (cond, txt, val, sev)
Value:
  if (cond)                         \
    ;                               \
  else                              \
  interr((txt), (val), (sev))
Definition at line 59 of file pgerror.h.
DEBUG_ASSERT
#define DEBUG_ASSERT (cond, txt) ((void)0)
If DEBUG!=0 and cond is false, emit an internal compiler error.
Like the C standard <assert.h> assert macro, this version expands to an expression and is active only in debug builds. Severity of an error is implicitly maximal.
Parameters
cond is the condition to be checked
txt is an additional info string, which may be NULL.
Definition at line 79 of file pgerror.h.
Typedef Documentation
error_code_t
typedef enum error_code error_code_t
Error code type.
Definition at line 38 of file pgerror.h.
error_severity
typedef BEGIN_DECL_WITH_C_LINKAGE enum error_severity error_severity
Severity of an error message.
Enumeration Type Documentation
error_severity
enum error_severity
Severity of an error message.
Enumerator
ERR_unused
ERR_Informational
ERR_Warning
ERR_Severe
ERR_Fatal
ERR_SEVERITY_SIZE
Definition at line 23 of file pgerror.h.
Function Documentation
interr()
void interr (const char * txt, int val, enum error_severity sev)
Assert that cond is true, and emit an internal compiler error otherwise.
Note that unlike the C standard <assert.h> assert() macro, this version is active in both debug and release builds, and expands to a statement, not an expression.
Definition at line 266 of file tools/shared/error.c.
References interrf(), and val.
Referenced by __print_nme(), _assn_rtemp(), _avail(), _ccff_info(), _compute_width(), _constructf90(), _dinit_acl(), _dmp_dent(), _makezero(), _olap_conflict(), _parser(), _printacl(), _rdfo(), _size_of(), _transform_func(), acl_rewrite_asts(), ad1ili(), ad2func_cmplx(), ad2func_cmplx_abi(), ad2ili(), ad_cse(), ad_free(), ad_func(), add_arg(), add_arg_ili(), add_assign_firstprivate(), add_dt_subscr(), add_iolptrs(), add_parent_to_bounds(), add_private_allocatable(), addarth(), addili(), align_struct_tmp(), alignment(), alpha(), annomod_asm(), annomod_initx(), apply_gep_index(), arrayref_size(), assign_array_w_forall(), ast_clear_repl(), ast_replace(), ast_rewrite(), ast_trav_recurse(), ast_unvisit(), ast_unvisit_norepl(), ast_visit(), begin_call(), binop(), binop_init_list(), bits_in(), bld_lhs(), bld_use(), build_array_list(), build_dlist(), build_do_init(), build_rdfo(), canonical_conversion(), check_ccon(), check_ilm(), check_pte(), chk_and_rewrite_cmplxpart_assn(), chksubstr(), cmp_acl(), cmp_to_log(), cngshape(), compose_and_throw(), compute_size(), compute_size_expr(), Conflict_(), const_fold(), construct_acl_for_sst(), construct_acl_from_ast(), constructf90(), contains_alloc(), contiguous_array_section(), conv_allocate(), conv_deallocate(), convert_dtype(), convert_subscript_in_expr(), copy_initconst_to_array(), count_allocatable_members(), cp_memarg(), create_atomic_capture_seq(), create_atomic_seq(), create_atomic_write_seq(), crunch(), dd_array_conflict(), dd_edge(), decompose_expression(), dinit_acl_val2(), dinit_subs(), dinit_varref(), dist_ast(), dmp_var(), do_reduction(), do_subscript(), dtype_from_return_type(), dump_one_scope(), DumpnameHelper(), effective_rhs(), efunc(), emit_init(), endrcand(), eval_const_array_section(), eval_const_array_triple_section(), eval_do(), eval_fvec(), eval_ilm(), eval_init_op(), eval_sb(), exp_ac(), exp_add_copy(), exp_call(), exp_fstring(), exp_load(), exp_mac(), exp_misc(), exp_qjsr(), exp_smp(), exp_store(), exp_zqjsr(), export_dt(), export_host_subprogram(), export_ict(), export_module_subprogram(), export_symbol(), expr_dependent_check(), extent_of(), ff_get_stmt(), fill_ast(), fill_links_symbol(), fill_subscripts(), fillin_succ(), find_funcptr_name(), find_presence(), find_reduc_intrinsic(), first_element_from_section(), fix_dtype(), fix_term(), flow(), flow_end(), flow_init(), forall_semantic(), gen_abs_expr(), gen_arg_operand(), gen_bindC_retval(), gen_call_expr(), gen_const_expr(), gen_contig_check(), gen_derived_io(), gen_funcret(), gen_llvm_expr(), gen_minmax_expr(), gen_mulh_expr(), gen_newer_intrin(), gen_reduction(), gen_switch(), get_ac_op(), get_ag(), get_ag_lltype(), get_ast_op(), get_atomic_function(), get_atomic_memory_order_name(), get_atomic_update_opcode(), get_atomicrmw_opname(), get_const_from_ast(), get_dtype_from_ilm(), get_forall_subscr(), get_header_member(), get_header_member_with_parent(), get_keyword_args(), get_kind_value(), get_llvm_name(), get_metadata_name(), get_msize(), get_next_arg(), get_number(), get_prefixed_int(), get_scalar_in_expr(), get_scope(), get_sdsc_element(), get_src_line(), get_stmt(), get_subscr(), get_type(), getdtype(), getitem(), getMergeSym(), getprint(), getsname(), handle_seq_section(), has_adjustable_expr(), has_allocatable_expr(), has_assumshp_expr(), has_invar_subs(), has_pointer_expr(), hostsym_is_refd(), hpf_library_stat(), ILI_OPC(), ILI_OPND(), ilm_return_slot_index(), import(), import_constant(), imprecise_match(), init_fold_const(), init_negate_const(), init_sptr_w_acl(), inlarr(), inline_shifts(), insert_comm_before(), insert_forall_comm(), install_dtype(), interpret(), is_array_in_expr(), is_dist_array_in_expr(), is_duplicate(), is_indirection_in_it(), is_legal_lhs(), is_legal_lhs_for_mask(), is_lonely_idx(), is_name_in_expr(), is_nonscalar_array_in_expr(), is_nonscalar_indirection_in_it(), is_one_idx_for_dim(), is_parentof_ast(), is_ptrast_arg(), is_same_array_bounds(), is_same_mask(), is_source_global(), is_source_nonlocal(), is_vector_indirection_in_it(), is_whole_array(), iso_c_lib_stat(), left_array_symbol(), left_nonscalar_subscript_ast(), left_subscript_ast(), ll_abi_from_call_site(), ll_ad_outlined_func2(), ll_convert_array_dtype(), ll_convert_basic_dtype_with_addrspace(), ll_create_int_type_with_addrspace(), ll_get_atomic_memorder(), ll_get_calling_conv_str(), ll_proto_add(), ll_proto_has_defined_body(), ll_proto_init(), ll_proto_is_weak(), ll_proto_set_defined_body(), ll_proto_set_intrinsic(), ll_proto_set_weak(), ll_type_bytes(), ll_write_global_objects(), localflow(), lower(), lower_check_stack(), lower_stmt(), mac_push(), make_equiv_ss(), make_forall(), make_sec_from_ast_chk(), map_initsym(), mark(), mark_apte_targets(), memsym_of_ast(), might_target(), mk_binop(), mk_coercion_func_name(), mk_component_ast(), mk_cval1(), mk_descr_id(), mk_forall_sptr(), mk_id_noshape(), mk_mem_ptr_shape(), mk_offset(), mk_result_sptr(), mk_storage(), mk_swtab(), mk_swtab_ll(), mk_unop(), mkarg(), mkexpr1(), mkfunc_sflags(), mklabelvar(), mklvalue(), mkrtemp_arg1_sc(), mkrtemp_cpx_sc(), mkshape(), mkvarref(), mod_type(), modify_inlined_stds(), move_labels(), name_dependent_check(), negate_const(), negate_const_be(), new_ast(), new_astli(), new_dtype(), new_installed_dtype(), new_symbol(), new_symbol_and_link(), normalize_forall(), normalize_forall_array(), par_xref(), par_xref_put(), parse_arguments(), pass_sym_of_ast(), pointer_squeezer(), points_to(), pop_indent(), pop_pragma(), pop_scope_level(), print_arg_attributes(), priority(), process_input(), procsym_of_ast(), push_elsewhere(), push_pragma(), push_scope_level(), put_a_init_tree(), put_arg_ili(), put_ffield(), put_length_type_param(), put_memsym_of_ast(), put_vlist(), queue_symbol(), rank_of(), read_symbol(), redimension(), ref_array(), ref_intrin(), ref_pd(), reference_for_temp(), remove_inlined_symbols(), remove_parent_from_ast(), remove_stmt(), reorder_dfn_loops(), reorderloops(), replace_ast_subtree(), replace_by_one(), replace_by_zero(), replace_memsym_of_ast(), replace_parms(), replace_vector_subscript(), reset_module_state(), restore_host_state(), restore_implicit(), restore_internal_subprograms(), restore_scope_level(), rewrite_acl(), rewrite_allocatable_assignment(), rewrite_ast_with_new_dtype(), rewrite_block_forall(), rewrite_block_where(), rewrite_calls(), rewrite_cmplxpart_rval(), rewrite_into_forall(), rewrite_sub_ast(), rw_dinit_state(), save_acl(), save_init(), save_scope_level(), save_uname(), scalar_communication(), scale_of(), Scale_Of(), search_basearr(), select_rtemp(), sem_err104(), semant1(), semant2(), semant3(), semantio(), semsmp(), set_ilmpos(), set_tp(), shape_comm_in_expr(), simple_reference_for_temp(), size_ast(), size_ast_of(), size_of(), size_of_array(), string_expr_length(), string_length(), subscr_dependent_check(), subscript_allocmem(), subst(), sym_is_refd(), sym_of_ast(), symdentry(), tag_forall_comm(), target_kind(), target_name(), test_really_an_entry(), tkn_alias_sym(), transfer_load(), transfer_store(), transform(), transform_all_call(), transform_c_f_pointer(), transform_c_f_procpointer(), transform_call(), transform_pure_function(), trav_struct(), ubound_of(), unop_init_list(), upper(), vect_math(), verify_failure(), vmk_prototype(), write_def_values(), write_mdfield(), write_mdref(), xref(), and xrefput().