flang: pgmath_test.h File Reference
pgmath_test.h File Reference
Macros
#define _CONCAT2(a, b) a##b
#define CONCAT2(a, b) _CONCAT(a,b)
#define _CONCAT3(a, b, c) a##b##c
#define CONCAT3(a, b, c) _CONCAT3(a,b,c)
#define _CONCAT4(a, b, c, d) a##b##c##d
#define CONCAT4(a, b, c, d) _CONCAT4(a,b,c,d)
#define _CONCAT5(a, b, c, d, e) a##b##c##d##e
#define CONCAT5(a, b, c, d, e) _CONCAT5(a,b,c,d,e)
#define _CONCAT6(a, b, c, d, e, f) a##b##c##d##e##f
#define CONCAT6(a, b, c, d, e, f) _CONCAT6(a,b,c,d,e,f)
#define _CONCAT7(a, b, c, d, e, f, g) a##b##c##d##e##f##g
#define CONCAT7(a, b, c, d, e, f, g) _CONCAT7(a,b,c,d,e,f,g)
#define _CONCAT8(a, b, c, d, e, f, g, h) a##b##c##d##e##f##g##h
#define CONCAT8(a, b, c, d, e, f, g, h) _CONCAT8(a,b,c,d,e,f,g,h)
#define _STRINGIFY(_n) #_n
#define STRINGIFY(_n) _STRINGIFY(_n)
#define FCONST1 0.0f
#define FCONST2 31.0f
#define DCONST1 0.0d
#define DCONST2 31.0d
#define EXTERN_EFUNC(name)
#define EXTERN_EFUNC2(name)
#define EXTERN_EFUNC2i(name)
#define EXTERN_EFUNC2i1(name)
#define EXTERN_EFUNC2k(name)
#define EXTERN_EFUNC2k1(name)
Typedefs
typedef double vrd1_t
typedef double vrd2_t __attribute__((vector_size(2 *sizeof(double))))
typedef float vrs1_t
typedef int32_t vis1_t
typedef int64_t vid1_t
Functions
EXTERN_EFUNC (acos)
EXTERN_EFUNC (asin)
EXTERN_EFUNC (atan)
EXTERN_EFUNC (cos)
EXTERN_EFUNC (cosh)
EXTERN_EFUNC (exp)
EXTERN_EFUNC (log10)
EXTERN_EFUNC (log)
EXTERN_EFUNC (sin)
EXTERN_EFUNC (sinh)
EXTERN_EFUNC (tan)
EXTERN_EFUNC (tanh)
EXTERN_EFUNC2 (atan2)
EXTERN_EFUNC2 (mod)
EXTERN_EFUNC2 (pow)
EXTERN_EFUNC2i (powi)
EXTERN_EFUNC2i1 (powi1)
EXTERN_EFUNC2k (powk)
EXTERN_EFUNC2k1 (powk1)
int32_t mask_sp[1<< VLS][VLS] __attribute__ ((aligned(64)))
static void parseargs (int argc, char *argv[])
static VRS_T vrs_set_arg (float fmin, float fconst)
static VRD_T vrd_set_arg (double dmin, double dconst)
static void build_masks (bool gray_code)
static int checkfltol1 (float res, float exp, float ltol)
static int checkfltol (VRS_T res, VRS_T exp, VIS_T vvmask, int n, float ltol)
Variables
int32_t verbose = 0
Macro Definition Documentation
_CONCAT2
#define _CONCAT2 (a, b) a##b
Definition at line 58 of file pgmath_test.h.
_CONCAT3
#define _CONCAT3 (a, b, c) a##b##c
Definition at line 60 of file pgmath_test.h.
_CONCAT4
#define _CONCAT4 (a, b, c, d) a##b##c##d
Definition at line 62 of file pgmath_test.h.
_CONCAT5
#define _CONCAT5 (a, b, c, d, e) a##b##c##d##e
Definition at line 64 of file pgmath_test.h.
_CONCAT6
#define _CONCAT6 (a, b, c, d, e, f) a##b##c##d##e##f
Definition at line 66 of file pgmath_test.h.
_CONCAT7
#define _CONCAT7 (a, b, c, d, e, f, g) a##b##c##d##e##f##g
Definition at line 68 of file pgmath_test.h.
_CONCAT8
#define _CONCAT8 (a, b, c, d, e, f, g, h) a##b##c##d##e##f##g##h
Definition at line 70 of file pgmath_test.h.
_STRINGIFY
#define _STRINGIFY (_n) #_n
Definition at line 73 of file pgmath_test.h.
CONCAT2
#define CONCAT2 (a, b) _CONCAT(a,b)
Definition at line 59 of file pgmath_test.h.
CONCAT3
#define CONCAT3 (a, b, c) _CONCAT3(a,b,c)
Definition at line 61 of file pgmath_test.h.
CONCAT4
#define CONCAT4 (a, b, c, d) _CONCAT4(a,b,c,d)
Definition at line 63 of file pgmath_test.h.
CONCAT5
#define CONCAT5 (a, b, c, d, e) _CONCAT5(a,b,c,d,e)
Definition at line 65 of file pgmath_test.h.
CONCAT6
#define CONCAT6 (a, b, c, d, e, f) _CONCAT6(a,b,c,d,e,f)
Definition at line 67 of file pgmath_test.h.
CONCAT7
#define CONCAT7 (a, b, c, d, e, f, g) _CONCAT7(a,b,c,d,e,f,g)
Definition at line 69 of file pgmath_test.h.
CONCAT8
#define CONCAT8 (a, b, c, d, e, f, g, h) _CONCAT8(a,b,c,d,e,f,g,h)
Definition at line 71 of file pgmath_test.h.
DCONST1
#define DCONST1 0.0d
Definition at line 148 of file pgmath_test.h.
DCONST2
#define DCONST2 31.0d
Definition at line 149 of file pgmath_test.h.
EXTERN_EFUNC
#define EXTERN_EFUNC (name)
Value:
    extern VRS_T \
    CONCAT5(__fs_,name,_,VLS,)(VRS_T), CONCAT5(__fs_,name,_,VLS,m)(VRS_T,VIS_T), \
    CONCAT5(__rs_,name,_,VLS,)(VRS_T), CONCAT5(__rs_,name,_,VLS,m)(VRS_T,VIS_T), \
    CONCAT5(__ps_,name,_,VLS,)(VRS_T), CONCAT5(__ps_,name,_,VLS,m)(VRS_T,VIS_T); \
    extern VRD_T \
    CONCAT5(__fd_,name,_,VLD,)(VRD_T), CONCAT5(__fd_,name,_,VLD,m)(VRD_T,VID_T), \
    CONCAT5(__rd_,name,_,VLD,)(VRD_T), CONCAT5(__rd_,name,_,VLD,m)(VRD_T,VID_T), \
    CONCAT5(__pd_,name,_,VLD,)(VRD_T), CONCAT5(__pd_,name,_,VLD,m)(VRD_T,VID_T)
Definition at line 151 of file pgmath_test.h.
EXTERN_EFUNC2
#define EXTERN_EFUNC2 (name)
Value:
    extern VRS_T \
    CONCAT5(__fs_,name,_,VLS,)(VRS_T,VRS_T), CONCAT5(__fs_,name,_,VLS,m)(VRS_T,VRS_T,VIS_T), \
    CONCAT5(__rs_,name,_,VLS,)(VRS_T,VRS_T), CONCAT5(__rs_,name,_,VLS,m)(VRS_T,VRS_T,VIS_T), \
    CONCAT5(__ps_,name,_,VLS,)(VRS_T,VRS_T), CONCAT5(__ps_,name,_,VLS,m)(VRS_T,VRS_T,VIS_T); \
    extern VRD_T \
    CONCAT5(__fd_,name,_,VLD,)(VRD_T,VRD_T), CONCAT5(__fd_,name,_,VLD,m)(VRD_T,VRD_T,VID_T), \
    CONCAT5(__rd_,name,_,VLD,)(VRD_T,VRD_T), CONCAT5(__rd_,name,_,VLD,m)(VRD_T,VRD_T,VID_T), \
    CONCAT5(__pd_,name,_,VLD,)(VRD_T,VRD_T), CONCAT5(__pd_,name,_,VLD,m)(VRD_T,VRD_T,VID_T)
Definition at line 161 of file pgmath_test.h.
EXTERN_EFUNC2i
#define EXTERN_EFUNC2i (name)
Value:
    extern VRS_T \
    CONCAT5(__fs_,name,_,VLS,)(VRS_T,VIS_T), CONCAT5(__fs_,name,_,VLS,m)(VRS_T,VIS_T,VIS_T), \
    CONCAT5(__rs_,name,_,VLS,)(VRS_T,VIS_T), CONCAT5(__rs_,name,_,VLS,m)(VRS_T,VIS_T,VIS_T), \
    CONCAT5(__ps_,name,_,VLS,)(VRS_T,VIS_T), CONCAT5(__ps_,name,_,VLS,m)(VRS_T,VIS_T,VIS_T); \
    extern VRD_T \
    CONCAT5(__fd_,name,_,VLD,)(VRD_T,VIS_T), CONCAT5(__fd_,name,_,VLD,m)(VRD_T,VIS_T,VID_T), \
    CONCAT5(__rd_,name,_,VLD,)(VRD_T,VIS_T), CONCAT5(__rd_,name,_,VLD,m)(VRD_T,VIS_T,VID_T), \
    CONCAT5(__pd_,name,_,VLD,)(VRD_T,VIS_T), CONCAT5(__pd_,name,_,VLD,m)(VRD_T,VIS_T,VID_T)
Definition at line 172 of file pgmath_test.h.
EXTERN_EFUNC2i1
#define EXTERN_EFUNC2i1 (name)
Value:
    extern VRS_T \
    CONCAT5(__fs_,name,_,VLS,)(VRS_T,int32_t), CONCAT5(__fs_,name,_,VLS,m)(VRS_T,int32_t,VIS_T), \
    CONCAT5(__rs_,name,_,VLS,)(VRS_T,int32_t), CONCAT5(__rs_,name,_,VLS,m)(VRS_T,int32_t,VIS_T), \
    CONCAT5(__ps_,name,_,VLS,)(VRS_T,int32_t), CONCAT5(__ps_,name,_,VLS,m)(VRS_T,int32_t,VIS_T); \
    extern VRD_T \
    CONCAT5(__fd_,name,_,VLD,)(VRD_T,int32_t), CONCAT5(__fd_,name,_,VLD,m)(VRD_T,int32_t,VID_T), \
    CONCAT5(__rd_,name,_,VLD,)(VRD_T,int32_t), CONCAT5(__rd_,name,_,VLD,m)(VRD_T,int32_t,VID_T), \
    CONCAT5(__pd_,name,_,VLD,)(VRD_T,int32_t), CONCAT5(__pd_,name,_,VLD,m)(VRD_T,int32_t,VID_T)
Definition at line 183 of file pgmath_test.h.
EXTERN_EFUNC2k
#define EXTERN_EFUNC2k (name)
Value:
    extern VRS_T \
    CONCAT5(__fs_,name,_,VLS,)(VRS_T,VID_T), CONCAT5(__fs_,name,_,VLS,m)(VRS_T,VID_T,VIS_T), \
    CONCAT5(__rs_,name,_,VLS,)(VRS_T,VID_T), CONCAT5(__rs_,name,_,VLS,m)(VRS_T,VID_T,VIS_T), \
    CONCAT5(__ps_,name,_,VLS,)(VRS_T,VID_T), CONCAT5(__ps_,name,_,VLS,m)(VRS_T,VID_T,VIS_T); \
    extern VRD_T \
    CONCAT5(__fd_,name,_,VLD,)(VRD_T,VID_T), CONCAT5(__fd_,name,_,VLD,m)(VRD_T,VID_T,VID_T), \
    CONCAT5(__rd_,name,_,VLD,)(VRD_T,VID_T), CONCAT5(__rd_,name,_,VLD,m)(VRD_T,VID_T,VID_T), \
    CONCAT5(__pd_,name,_,VLD,)(VRD_T,VID_T), CONCAT5(__pd_,name,_,VLD,m)(VRD_T,VID_T,VID_T)
Definition at line 194 of file pgmath_test.h.
EXTERN_EFUNC2k1
#define EXTERN_EFUNC2k1 (name)
Value:
    extern VRS_T \
    CONCAT5(__fs_,name,_,VLS,)(VRS_T,int64_t), CONCAT5(__fs_,name,_,VLS,m)(VRS_T,int64_t,VIS_T), \
    CONCAT5(__rs_,name,_,VLS,)(VRS_T,int64_t), CONCAT5(__rs_,name,_,VLS,m)(VRS_T,int64_t,VIS_T), \
    CONCAT5(__ps_,name,_,VLS,)(VRS_T,int64_t), CONCAT5(__ps_,name,_,VLS,m)(VRS_T,int64_t,VIS_T); \
    extern VRD_T \
    CONCAT5(__fd_,name,_,VLD,)(VRD_T,int64_t), CONCAT5(__fd_,name,_,VLD,m)(VRD_T,int64_t,VID_T), \
    CONCAT5(__rd_,name,_,VLD,)(VRD_T,int64_t), CONCAT5(__rd_,name,_,VLD,m)(VRD_T,int64_t,VID_T), \
    CONCAT5(__pd_,name,_,VLD,)(VRD_T,int64_t), CONCAT5(__pd_,name,_,VLD,m)(VRD_T,int64_t,VID_T)
Definition at line 205 of file pgmath_test.h.
FCONST1
#define FCONST1 0.0f
Definition at line 146 of file pgmath_test.h.
FCONST2
#define FCONST2 31.0f
Definition at line 147 of file pgmath_test.h.
STRINGIFY
#define STRINGIFY (_n) _STRINGIFY(_n)
Definition at line 74 of file pgmath_test.h.
Typedef Documentation
__attribute__
typedef int64_t vid8_t __attribute__((vector_size(8 *sizeof(int64_t))))
Definition at line 15 of file pgmath_test.h.
vid1_t
typedef int64_t vid1_t
Definition at line 53 of file pgmath_test.h.
vis1_t
typedef int32_t vis1_t
Definition at line 48 of file pgmath_test.h.
vrd1_t
typedef double vrd1_t
Definition at line 14 of file pgmath_test.h.
vrs1_t
typedef float vrs1_t
Definition at line 18 of file pgmath_test.h.
Function Documentation
__attribute__()
int32_t mask_sp[1<< VLS][VLS] __attribute__ ((aligned(64)))
build_masks()
static void build_masks (bool gray_code) static
Definition at line 305 of file pgmath_test.h.
References i, j, k, and verbose.
Referenced by for().
checkfltol()
static int checkfltol (VRS_T res, VRS_T exp, VIS_T vvmask, int n, float ltol) static
Definition at line 390 of file pgmath_test.h.
References checkfltol1(), i, and n.
Referenced by for().
checkfltol1()
static int checkfltol1 (float res, float exp, float ltol) static
Definition at line 357 of file pgmath_test.h.
References exp, res, and verbose.
Referenced by checkfltol().
EXTERN_EFUNC() [1/12]
EXTERN_EFUNC (acos)
EXTERN_EFUNC() [2/12]
EXTERN_EFUNC (asin)
EXTERN_EFUNC() [3/12]
EXTERN_EFUNC (atan)
EXTERN_EFUNC() [4/12]
EXTERN_EFUNC (cos)
EXTERN_EFUNC() [5/12]
EXTERN_EFUNC (cosh)
EXTERN_EFUNC() [6/12]
EXTERN_EFUNC (exp)
EXTERN_EFUNC() [7/12]
EXTERN_EFUNC (log)
EXTERN_EFUNC() [8/12]
EXTERN_EFUNC (log10)
EXTERN_EFUNC() [9/12]
EXTERN_EFUNC (sin)
EXTERN_EFUNC() [10/12]
EXTERN_EFUNC (sinh)
EXTERN_EFUNC() [11/12]
EXTERN_EFUNC (tan)
EXTERN_EFUNC() [12/12]
EXTERN_EFUNC (tanh)
EXTERN_EFUNC2() [1/3]
EXTERN_EFUNC2 (atan2)
EXTERN_EFUNC2() [2/3]
EXTERN_EFUNC2 (mod)
EXTERN_EFUNC2() [3/3]
EXTERN_EFUNC2 (pow)
EXTERN_EFUNC2i()
EXTERN_EFUNC2i (powi)
EXTERN_EFUNC2i1()
EXTERN_EFUNC2i1 (powi1)
EXTERN_EFUNC2k()
EXTERN_EFUNC2k (powk)
EXTERN_EFUNC2k1()
EXTERN_EFUNC2k1 (powk1)
parseargs()
static void parseargs (int argc, char * argv[]) static
Definition at line 256 of file pgmath_test.h.
References opt, and verbose.
Referenced by main().
vrd_set_arg()
static VRD_T vrd_set_arg (double dmin, double dconst) static
Definition at line 289 of file pgmath_test.h.
References i.
vrs_set_arg()
static VRS_T vrs_set_arg (float fmin, float fconst) static
Definition at line 274 of file pgmath_test.h.
References fmin(), and i.
Variable Documentation
verbose
int32_t verbose = 0
Definition at line 244 of file pgmath_test.h.
Referenced by build_masks(), checkfltol1(), N2Rst::N2Rst(), parseargs(), and N2Rst::run().