flang: pgnewfil.c File Reference
pgnewfil.c File Reference
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
Macros
#define S_ISDIR(mode) (((mode) & S_IFMT) == S_IFDIR)
#define LONG long
#define P_tmpdir "/tmp"
Functions
size_t strlen ()
static char * add (char *p, const char *q)
static char * addn (char *p, unsigned long val, int n)
long time (long *)
static char * gentmp (char *pfx, char *sfx)
char * pg_newfile (char *pfx, char *sfx)
char * pg_makenewfile (char *pfx, char *sfx, int make)
char * pg_makenewdir (char *pfx, char *sfx, int make)
Variables
static char chars []
static LONG pgrand = 0
static unsigned long pid = 0
Macro Definition Documentation
LONG
#define LONG long
Definition at line 80 of file pgnewfil.c.
P_tmpdir
#define P_tmpdir "/tmp"
Definition at line 166 of file pgnewfil.c.
S_ISDIR
#define S_ISDIR (mode) (((mode) & S_IFMT) == S_IFDIR)
Definition at line 37 of file pgnewfil.c.
Function Documentation
add()
static char * add (char * p, const char * q) static
Definition at line 44 of file pgnewfil.c.
References p, and q.
Referenced by __fort_reverse_array(), add_firstprivate_assn(), ENTF90(), ENTFTN(), gentmp(), is_biv(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_create_global_variable_mdnode(), lldbg_emit_type(), lldbg_get_bounds_for_assumed_rank_sdsc(), lldbg_get_bounds_for_sdsc(), local_copy(), make_assignment(), mk_component_ast(), and void().
addn()
static char * addn (char * p, unsigned long val, int n) static
Definition at line 60 of file pgnewfil.c.
References chars, d, i, n, p, and val.
Referenced by gentmp().
gentmp()
static char * gentmp (char * pfx, char * sfx) static
Definition at line 176 of file pgnewfil.c.
References add(), addn(), buf, chars, filename, getenv(), malloc(), n, NULL, p, P_tmpdir, pgrand, pid, q, S_ISDIR, stat, strlen(), and time().
Referenced by pg_makenewdir(), pg_makenewfile(), and pg_newfile().
pg_makenewdir()
char * pg_makenewdir (char * pfx, char * sfx, int make)
Definition at line 343 of file pgnewfil.c.
References access, filename, gentmp(), NULL, and r.
pg_makenewfile()
char * pg_makenewfile (char * pfx, char * sfx, int make)
Definition at line 296 of file pgnewfil.c.
References access, fd, filename, gentmp(), NULL, r, and write.
pg_newfile()
char * pg_newfile (char * pfx, char * sfx)
Definition at line 266 of file pgnewfil.c.
References access, filename, gentmp(), NULL, and r.
strlen()
size_t strlen ()
Referenced by __abort_init(), __fort_abort(), __fort_fixmnt(), __fort_getenv(), __fort_i64toax(), __fort_initcom(), __fort_initopt(), __fort_passarg(), __fort_passargs(), __fort_psignal(), __fort_traceback(), __fort_tracecall(), __fortio_default_convert(), __fortio_fmt_d(), __fortio_fmt_e(), __fortio_fmt_f(), __fortio_fmt_g(), __fortio_open(), __pg_get_lock(), __pg_make_lock_file(), __pg_release_lock(), _do_iface(), _doincl(), _get_token(), _huge(), _repeat(), _trim(), _write_token(), accpp(), add_ag_fptr_name(), add_ag_local_name(), add_ag_name(), add_imported(), add_to_be_used_list(), addcombination(), addDeferredTbp(), addfile(), addFinalSubroutine(), addinlfile(), addmodfile(), addnewsym(), addNonOverridableTbp(), addNoPassArg(), addPassArg(), addPrivateAttribute(), addPublicAttribute(), addTbpInterface(), alpha(), appendit(), basenam(), build_name_buffer(), call_sym_is(), ccff_open(), ch_substring(), check_additional_common(), check_debug_alias(), check_doconcurrent_ast(), cli(), cmp_interfaces(), cng_generic(), cng_inttyp(), cng_specific(), cntl_name(), collectIncludePaths(), compose_and_throw(), compute_datalayout(), contIndex(), conv_int8(), cpu(), create_global_initializer(), create_thread_private_vector(), decr_ident_use(), defer_arg_chk(), defer_ident_list(), defer_iface(), defined_io_error(), delete(), dinit_name(), do_nested_uses(), do_parse(), dodef(), doident(), doincl(), doline(), dsym(), e74_arg(), enqueueTbp(), ENT3F(), ENTF90(), errfill(), eval_trim(), exp_mac(), exp_misc(), export_all(), export_header(), fill_recurse(), find_ag(), find_argasym(), find_best_generic(), find_by_name_stype_arg(), find_funcptr_name(), find_local_ag(), find_member_name(), find_nmptr(), find_non_tbp(), fix_iface(), fix_proc_ptr_dummy_args(), fixup_nme(), fndpath(), fpp(), frte_func(), func_call2(), gen_call_to_builtin(), gen_constant(), gen_contig_check(), gen_dtio_arglist(), gen_kind_parm_assignments(), gen_va_end(), gen_va_start(), gen_vconstant(), gentmp(), get_anno_line(), get_byval_local(), get_csect_pfxlen(), get_dummy_ag(), get_filename(), get_implementation(), get_intrinsic(), get_keyword_args(), get_keyword_components(), get_llvm_ifacenm(), get_llvm_sname(), get_local_overlap_size(), get_src_line(), get_tbp(), get_tbp_argno(), getccssym(), getccssym_sc(), getccsym(), getccsym_copy(), getcctemp_sc(), getdtype(), getexnamestring(), getindex(), getline(), getnewccsym(), getnewccsym2(), getntstring(), getsymbol(), handle_parsing_errors(), has_final_procedures(), i32tos(), ic_strncmp(), import(), import_constant(), import_module_print(), inheritTbps(), init(), inquire(), insert_llvm_memcpy(), insert_llvm_memset(), insert_llvm_prefetch(), insert_node_into_use_tree(), insert_sym(), insert_sym_first(), internal_proc_has_ident(), is_keyword(), kwd_match(), ll_create_anon_struct_type(), ll_create_function_type(), ll_get_array_type(), ll_get_const_addrspacecast(), ll_get_const_bitcast(), ll_get_const_gep(), ll_get_global_pointer(), ll_get_gtid_addr_ili(), ll_get_gtid_val_ili(), ll_get_md_string(), ll_get_outlined_funcname(), ll_get_pointer_type(), ll_get_vector_type(), ll_override_type_string(), lldbg_create_common_block_mdnode(), lldbg_create_module_mdnode(), lldbg_emit_local_variable(), lldbg_emit_param_variable(), lldbg_emit_ptr_param_variable(), lldbg_function_end(), llutil_strdup(), llvm_funcptr_store(), local_sname(), lookupsymbol(), lower_add_pghpf_commons(), lower_check_subscript(), lower_cmptrvar(), lower_end_contains(), lower_fileinfo(), lower_fileinfo_llvm(), lower_newfunc(), lower_newsymbol(), lower_sym_header(), lower_symbol(), machvalue(), make_arg_op(), make_arg_tmp(), make_gblsym(), make_keyword_str(), make_new_funcsptr(), make_structkwd_str(), mangle_name(), mangle_name_dt(), mangleUnderscores(), mem(), mergeDebugTypesForGlobal(), mk_comstr(), mkDwfInfoFilename(), mkfname(), mkfunc(), mkperm(), mkRteRtnNm(), mod_add_subprogram(), mod_fini(), msg(), mth_i_override(), nan_or_infinite(), new_debug_name(), newbuff(), newprintfs(), newsym(), open_files(), open_module(), par_body(), parse_ref(), pbstr(), pop_indent(), pop_sym(), predarg(), predicate(), print_ast(), print_back_trace_line(), process_bind(), process_blockaddr_sptr(), process_extern_function_sptr(), process_ftn_dtype_struct(), process_label_sptr_c(), process_string(), push_sym(), put_double(), put_float(), put_fstring(), put_int8(), put_intkind(), put_name(), put_string(), put_u_to_l(), putbit(), putentry(), putit(), putnzbits(), puttight(), puttmplflag(), queue_type_param(), rdline(), read_symbol(), readln(), ref_pd(), register_boolean_arg(), remove_inlined_symbols(), report_too_long_identifier(), resolve_generic(), resolveGeneric(), resolvePass(), resolveTbps(), restore_host_state(), restore_internal_subprograms(), save_contained_name(), semant1(), semantio(), semCheckTbp(), semsmp(), set_global_sname(), set_local_sname(), set_numbered_global_sname(), setfile(), should_suppress_debug_loc(), sourced_alloc_and_assign(), stb_lower_sym_header(), stripI8DescrSuffix(), strstore(), subr_call2(), subst(), sum_scatter_args(), sym_get_sdescr(), sym_strsave(), symdentry(), tobinary(), tobinary64(), trimContIdx(), ufptosci(), unique_name(), update_external_function_declarations(), vmk_prototype(), write_ast(), write_ftn_type(), and write_typedescs().
time()
long time (long *)
Referenced by __fort_time(), ccff_build(), ENT3F(), ENTFTN(), Ftn_date(), Ftn_dsecnds(), Ftn_jdate(), Ftn_secnds(), Ftn_time(), gentmp(), and init().
Variable Documentation
chars
char chars[] static
Initial value:
= {
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-+"}
Definition at line 53 of file pgnewfil.c.
Referenced by addn(), and gentmp().
pgrand
LONG pgrand = 0 static
Definition at line 82 of file pgnewfil.c.
Referenced by gentmp().
pid
unsigned long pid = 0 static
Definition at line 83 of file pgnewfil.c.
Referenced by __pg_make_lock_file(), ENT3F(), ENTF90(), gentmp(), and pta_target().