flang: pointsto.c File Reference
pointsto.c File Reference
Do "points to" analysis; save information in NME and PTE structures.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "nme.h"
#include "ast.h"
#include "gramtk.h"
#include "pd.h"
#include "optimize.h"
#include "trace.h"
Classes
struct TPD
struct PSD
struct APTE
struct TPTE
struct AS
struct FPTE
struct FPSRC
Macros
#define TRACEFLAG 10
#define TRACEBIT 0x100000
#define TRACESTRING "pte-"
#define TTYPE(tpdx)
#define TSYM(tpdx)
#define TVAL(tpdx)
#define TLINK(tpdx)
#define TT_UNINIT 0x100
#define TT_UNK 0x110
#define TT_GLOB 0x120
#define TT_PSYM 0x130
#define TT_ISYM 0x140
#define TT_ANON 0x150
#define TT_GDYN 0x160
#define TT_IGDYN 0x170
#define TT_LDYN 0x180
#define TT_ILDYN 0x190
#define TT_CON 0x1a0
#define TT_IND 0x1b0
#define TT_IIND 0x1c0
#define TT_MEM 0x1d0
#define TT_NLOC 0x1e0
#define TTE_NULL -1
#define TTMUSTFLAG 1
#define TTIMPFLAG 2
#define TTMASKMUST(typ) ((typ)&0xfffe)
#define TTMASK(typ) ((typ)&0xfffd)
#define TTMUST(typ) ((typ)&TTMUSTFLAG)
#define TTIMP(typ) ((typ)&TTIMPFLAG)
#define PSD_TYPE(psdx)
#define PSD_PARENT(psdx)
#define PSD_SYM(psdx)
#define PSD_CHILD(psdx)
#define PSD_NEXT(psdx)
#define PSD_HASHLK(psdx)
#define PSD_SLOT(psdx)
#define SLOT(sl)
#define PSDHSZ 127
#define APTEHSZ 521
#define APTE_HASHLK(aptex)
#define APTE_TYPE(aptex)
#define APTE_SPTR(aptex)
#define APTE_VAL(aptex)
#define APTE_STRIDE(aptex)
#define APTE_MARK(aptex)
#define TPTE_UNK 0
#define TPTE_UNINIT 1
#define TPTE_NULL -1
#define TPTE_NEXT(ptex)
#define TPTE_APTEX(ptex)
#define TPTE_TYPE(ptex)
#define TPTE_SPTR(ptex)
#define TPTE_VAL(ptex)
#define TPTE_STRIDE(ptex)
#define TPTE_FLAG(ptex)
#define ASTYPE(asx)
#define ASLHS(asx)
#define ASRHS(asx)
#define ASNODE(asx)
#define ASILT(asx)
#define ASSTRIDE(asx)
#define ASNEXT(asx)
#define AS_DIRECT 1
#define AS_INDIRECT 2
#define AS_CLEAR 3
#define AS_UNK 4
#define AS_UNINIT 5
#define AS_INIT 6
#define AS_ADD_DIRECT 7
#define AS_ADD_INDIRECT 8
#define FIRSTAS(std) STD_PTASGN(std)
#define HEAD(v, sl)
#define LHEAD(psdx)
#define RDFO(r) rdfo[r >= 0 && r <= opt.num_nodes ? r : (interr("bad RDFO index", r, 4), 0)]
#define RDFONUM(r)
#define FPTE_NEXT(n)
#define FPTE_TYPE(n)
#define FPTE_SPTR(n)
#define FPTE_VAL(n)
#define FPTE_STRIDE(n)
#define FPSRC_NEXT(n)
#define FPSRC_TYPE(n)
#define FPSRC_SPTR(n)
#define FPSRC_PTELIST(n)
#define TRACEFLAG 10
#define TRACEBIT 0x1000000
#define TRACEFLAG 10
#define TRACEBIT 0x100000
Functions
static STG_DECLARE (gtpd, TPD)
static STG_DECLARE (apte, APTE)
static STG_DECLARE (as, AS)
static STG_DECLARE (head, int)
static STG_DECLARE (ganon, int)
static void puttds (int tdsx)
static void putpsd (int psdx)
static void putpte (int ptex)
static void putassign (int asx)
void putstdassigns (int stdx)
static void putptelist (int ptelistx)
static void puttarget (int sl)
static void puttargets (void)
static void putnodetarget (const char *ch, int v, int sl)
static void putnodetargets (const char *ch, int v)
static int is_source_global (int psdx)
static int safe_symbol (int psdx)
static int is_source_nonlocal (int psdx)
static void add_psd (int tpdx, int type, int parent, int sym, bool lhs)
static void build_psd (int tdsx, bool lhs)
static int find_psd (int type, int parent, int sym)
static int get_apte (int type, int sptr, int val, int stride)
static int find_apte (int type, int sptr, int val)
static int get_pte (int type, int sptr, int val, int stride)
static int imprecise_ptetype (int ptetype)
static int copy_pte (int ptex, int imprecise, int mstride)
static void free_pte (int ptex)
static void free_list (int ptelistx)
static void free_list_slot (int sl)
static void buildrdfo (int v)
static int make_address (int astx, int pt, int sym, int offset)
static int make_address_for_ast (int astx, int parentast)
static void make_assignment (int v, int iltx, int lhstds, int rhstds, int add, int stride)
static int find_stride (int astx)
static void _find_pointer_assignments_f90 (int astx, int *pstdx)
static void find_pointer_assignments_f90 (int stdx)
static void add_list (int ptex, int psdx, int imprecise, int mstride)
static int copy_list (int ptelistx)
static void unk_all (void)
static void unk_globals (void)
static void mark_apte_targets (int psdx)
static int might_target (int psdx)
static void _addtpte (int lhspsdx, int ptex, int imprecise, int mstride)
static void addtpte (int lhspsdx, int ptex)
static void inittpte (int lhspsdx, int ptex)
static void replacepte (int lhspsdx, int ptex)
static void add_tptelist (int lhspsdx, int ptelistx)
static void replace_tptelist (int lhspsdx, int ptelistx)
static void add_target_tptelist (int lhspsdx, int ptelistx)
static int effective_rhs (int psdx)
static void interpret (int asx)
static int imprecise_match (int lptex, int ptex)
static int find_imprecise_match (int lptex, int ptelistx)
static int pte_changed (int v)
static int check_this_assignment (int asx, int v)
static void check_pte (const char *ch)
static STG_DECLARE (fpte, FPTE)
static STG_DECLARE (fpsrc, FPSRC)
static void f90_init (void)
void f90_fini_pointsto (void)
static int add_fpsrc (int psdx, int fpsrcx)
static void add_fpte (int ptex, int fpsrcx)
static void putsrc (int fpsrcx)
static void putfpte (int fptex)
void putstdpta (int stdx)
static bool different_pta (int pta1, int pta2)
static void set_std_pta (int stdx, int change)
bool pta_conflict (int ptrstdx, int ptrsptr, int targetstdx, int targetsptr, int targetpointer, int targettarget)
bool pta_aligned (int ptrstdx, int ptrsptr)
bool pta_stride1 (int ptrstdx, int ptrsptr)
int pta_target (int ptrstdx, int ptrsptr, int *ptag, int *pid)
static void init_points_to_anal (void)
static void init_points_to_prop (void)
static void fini_points_to_anal (void)
static void fini_points_to_prop (void)
void fini_points_to_all (void)
void points_to_anal (void)
void points_to (void)
Do dataflow analysis to determine pointer target information store pointer target information at loads and stores.
Variables
struct {
int * slot
int nslots
} gpsd = {STG_INIT, NULL, 0}
static int psdhsh [PSDHSZ]
static int aptehsh [APTEHSZ]
struct {
int xstg_free
int save_stg_avail
int save_stg_free
} gpte = {STG_INIT, -1, 0, 0}
static int prevasx
static int * nodeoffset = NULL
static int * localhead = NULL
struct {
int local_dyn
} gdyn = {STG_INIT, 0}
struct {
int tot
int ntot
} gcount = {0, 0}
static int rdfocount
static int * rdfo
static int * rdfonum
static int globalv
static unsigned int marker = 0
static unsigned int unknown_mark = 0
static unsigned int nonlocal_mark = 0
static unsigned int some_nonlocal_mark = 0
static int CHANGES
static int last_pta = 0
static FILE * dfile
Detailed Description
Do "points to" analysis; save information in NME and PTE structures.
Definition in file pointsto.c.
Macro Definition Documentation
APTE_HASHLK
#define APTE_HASHLK (aptex)
Value:
  apte.stg_base[aptex >= 0 && aptex < apte.stg_avail                  \
                    ? aptex                                           \
                    : (interr("bad APTE_HASHLK index", aptex, 4), 0)] \
      .hashlk
Definition at line 240 of file pointsto.c.
APTE_MARK
#define APTE_MARK (aptex)
Value:
  apte.stg_base[aptex >= 0 && aptex < apte.stg_avail                \
                    ? aptex                                         \
                    : (interr("bad APTE_MARK index", aptex, 4), 0)] \
      .mark
Definition at line 265 of file pointsto.c.
APTE_SPTR
#define APTE_SPTR (aptex)
Value:
  apte.stg_base[aptex >= 0 && aptex < apte.stg_avail                \
                    ? aptex                                         \
                    : (interr("bad APTE_SPTR index", aptex, 4), 0)] \
      .sym
Definition at line 250 of file pointsto.c.
APTE_STRIDE
#define APTE_STRIDE (aptex)
Value:
  apte.stg_base[aptex >= 0 && aptex < apte.stg_avail                  \
                    ? aptex                                           \
                    : (interr("bad APTE_STRIDE index", aptex, 4), 0)] \
      .stride
Definition at line 260 of file pointsto.c.
APTE_TYPE
#define APTE_TYPE (aptex)
Value:
  apte.stg_base[aptex >= 0 && aptex < apte.stg_avail                \
                    ? aptex                                         \
                    : (interr("bad APTE_TYPE index", aptex, 4), 0)] \
      .type
Definition at line 245 of file pointsto.c.
APTE_VAL
#define APTE_VAL (aptex)
Value:
  apte.stg_base[aptex >= 0 && aptex < apte.stg_avail               \
                    ? aptex                                        \
                    : (interr("bad APTE_VAL index", aptex, 4), 0)] \
      .val
Definition at line 255 of file pointsto.c.
APTEHSZ
#define APTEHSZ 521
Definition at line 235 of file pointsto.c.
AS_ADD_DIRECT
#define AS_ADD_DIRECT 7
Definition at line 414 of file pointsto.c.
AS_ADD_INDIRECT
#define AS_ADD_INDIRECT 8
Definition at line 415 of file pointsto.c.
AS_CLEAR
#define AS_CLEAR 3
Definition at line 410 of file pointsto.c.
AS_DIRECT
#define AS_DIRECT 1
Definition at line 408 of file pointsto.c.
AS_INDIRECT
#define AS_INDIRECT 2
Definition at line 409 of file pointsto.c.
AS_INIT
#define AS_INIT 6
Definition at line 413 of file pointsto.c.
AS_UNINIT
#define AS_UNINIT 5
Definition at line 412 of file pointsto.c.
AS_UNK
#define AS_UNK 4
Definition at line 411 of file pointsto.c.
ASILT
#define ASILT (asx)
Value:
  as.stg_base[asx >= 0 && asx < as.stg_avail                \
                  ? asx                                     \
                  : (interr("bad ASILT index", asx, 4), 0)] \
      .iltx
Definition at line 383 of file pointsto.c.
ASLHS
#define ASLHS (asx)
Value:
  as.stg_base[asx >= 0 && asx < as.stg_avail                \
                  ? asx                                     \
                  : (interr("bad ASLHS index", asx, 4), 0)] \
      .lhs
Definition at line 368 of file pointsto.c.
ASNEXT
#define ASNEXT (asx)
Value:
  as.stg_base[asx >= 0 && asx < as.stg_avail                 \
                  ? asx                                      \
                  : (interr("bad ASNEXT index", asx, 4), 0)] \
      .next
Definition at line 393 of file pointsto.c.
ASNODE
#define ASNODE (asx)
Value:
  as.stg_base[asx >= 0 && asx < as.stg_avail                 \
                  ? asx                                      \
                  : (interr("bad ASNODE index", asx, 4), 0)] \
      .node
Definition at line 378 of file pointsto.c.
ASRHS
#define ASRHS (asx)
Value:
  as.stg_base[asx >= 0 && asx < as.stg_avail                \
                  ? asx                                     \
                  : (interr("bad ASRHS index", asx, 4), 0)] \
      .rhs
Definition at line 373 of file pointsto.c.
ASSTRIDE
#define ASSTRIDE (asx)
Value:
  as.stg_base[asx >= 0 && asx < as.stg_avail                   \
                  ? asx                                        \
                  : (interr("bad ASSTRIDE index", asx, 4), 0)] \
      .stride
Definition at line 388 of file pointsto.c.
ASTYPE
#define ASTYPE (asx)
Value:
  as.stg_base[asx >= 0 && asx < as.stg_avail                 \
                  ? asx                                      \
                  : (interr("bad ASTYPE index", asx, 4), 0)] \
      .type
Definition at line 363 of file pointsto.c.
FIRSTAS
#define FIRSTAS (std) STD_PTASGN(std)
Definition at line 417 of file pointsto.c.
FPSRC_NEXT
#define FPSRC_NEXT (n)
Value:
  fpsrc.stg_base[n >= 0 && n < fpsrc.stg_avail                    \
                     ? n                                          \
                     : (interr("bad FPSRC_NEXT index", n, 4), 0)] \
      .next
Definition at line 2904 of file pointsto.c.
FPSRC_PTELIST
#define FPSRC_PTELIST (n)
Value:
  fpsrc.stg_base[n >= 0 && n < fpsrc.stg_avail                       \
                     ? n                                             \
                     : (interr("bad FPSRC_PTELIST index", n, 4), 0)] \
      .ptelist
Definition at line 2919 of file pointsto.c.
FPSRC_SPTR
#define FPSRC_SPTR (n)
Value:
  fpsrc.stg_base[n >= 0 && n < fpsrc.stg_avail                    \
                     ? n                                          \
                     : (interr("bad FPSRC_SPTR index", n, 4), 0)] \
      .sptr
Definition at line 2914 of file pointsto.c.
FPSRC_TYPE
#define FPSRC_TYPE (n)
Value:
  fpsrc.stg_base[n >= 0 && n < fpsrc.stg_avail                    \
                     ? n                                          \
                     : (interr("bad FPSRC_TYPE index", n, 4), 0)] \
      .type
Definition at line 2909 of file pointsto.c.
FPTE_NEXT
#define FPTE_NEXT (n)
Value:
  fpte.stg_base[n >= 0 && n < fpte.stg_avail                    \
                    ? n                                         \
                    : (interr("bad FPTE_NEXT index", n, 4), 0)] \
      .next
Definition at line 2878 of file pointsto.c.
FPTE_SPTR
#define FPTE_SPTR (n)
Value:
  fpte.stg_base[n >= 0 && n < fpte.stg_avail                    \
                    ? n                                         \
                    : (interr("bad FPTE_SPTR index", n, 4), 0)] \
      .sptr
Definition at line 2888 of file pointsto.c.
FPTE_STRIDE
#define FPTE_STRIDE (n)
Value:
  fpte.stg_base[n >= 0 && n < fpte.stg_avail                      \
                    ? n                                           \
                    : (interr("bad FPTE_STRIDE index", n, 4), 0)] \
      .stride
Definition at line 2898 of file pointsto.c.
FPTE_TYPE
#define FPTE_TYPE (n)
Value:
  fpte.stg_base[n >= 0 && n < fpte.stg_avail                    \
                    ? n                                         \
                    : (interr("bad FPTE_TYPE index", n, 4), 0)] \
      .type
Definition at line 2883 of file pointsto.c.
FPTE_VAL
#define FPTE_VAL (n)
Value:
  fpte.stg_base[n >= 0 && n < fpte.stg_avail                   \
                    ? n                                        \
                    : (interr("bad FPTE_VAL index", n, 4), 0)] \
      .val
Definition at line 2893 of file pointsto.c.
HEAD
#define HEAD (v, sl)
Value:
  head.stg_base[nodeoffset[v >= 0 && v <= opt.num_nodes                      \
                               ? v                                           \
                               : (interr("bad HEAD node index", v, 4), 0)] + \
                (sl >= 0 && sl <= gpsd.nslots                                \
                     ? sl                                                    \
                     : (interr("bad HEAD slot index", sl, 4), 0))]
Definition at line 425 of file pointsto.c.
LHEAD
#define LHEAD (psdx)
Value:
  localhead[psdx >= 0 && psdx <= gpsd.nslots \
                ? psdx                       \
                : (interr("bad LHEAD index", psdx, 4), 0)]
Definition at line 438 of file pointsto.c.
PSD_CHILD
#define PSD_CHILD (psdx)
Value:
  gpsd.stg_base[psdx >= 0 && psdx < gpsd.stg_avail                 \
                    ? psdx                                         \
                    : (interr("bad PSD_CHILD index", psdx, 4), 0)] \
      .child
Definition at line 184 of file pointsto.c.
PSD_HASHLK
#define PSD_HASHLK (psdx)
Value:
  gpsd.stg_base[psdx >= 0 && psdx < gpsd.stg_avail                  \
                    ? psdx                                          \
                    : (interr("bad PSD_HASHLK index", psdx, 4), 0)] \
      .hashlk
Definition at line 194 of file pointsto.c.
PSD_NEXT
#define PSD_NEXT (psdx)
Value:
  gpsd.stg_base[psdx >= 0 && psdx < gpsd.stg_avail                \
                    ? psdx                                        \
                    : (interr("bad PSD_NEXT index", psdx, 4), 0)] \
      .next
Definition at line 189 of file pointsto.c.
PSD_PARENT
#define PSD_PARENT (psdx)
Value:
  gpsd.stg_base[psdx >= 0 && psdx < gpsd.stg_avail                  \
                    ? psdx                                          \
                    : (interr("bad PSD_PARENT index", psdx, 4), 0)] \
      .parent
Definition at line 174 of file pointsto.c.
PSD_SLOT
#define PSD_SLOT (psdx)
Value:
  gpsd.stg_base[psdx >= 0 && psdx < gpsd.stg_avail                \
                    ? psdx                                        \
                    : (interr("bad PSD_SLOT index", psdx, 4), 0)] \
      .slot
Definition at line 199 of file pointsto.c.
PSD_SYM
#define PSD_SYM (psdx)
Value:
  gpsd.stg_base[psdx >= 0 && psdx < gpsd.stg_avail               \
                    ? psdx                                       \
                    : (interr("bad PSD_SYM index", psdx, 4), 0)] \
      .sym
Definition at line 179 of file pointsto.c.
PSD_TYPE
#define PSD_TYPE (psdx)
Value:
  gpsd.stg_base[psdx >= 0 && psdx < gpsd.stg_avail                \
                    ? psdx                                        \
                    : (interr("bad PSD_TYPE index", psdx, 4), 0)] \
      .type
Definition at line 169 of file pointsto.c.
PSDHSZ
#define PSDHSZ 127
Definition at line 220 of file pointsto.c.
RDFO
#define RDFO (r) rdfo[r >= 0 && r <= opt.num_nodes ? r : (interr("bad RDFO index", r, 4), 0)]
Definition at line 1207 of file pointsto.c.
RDFONUM
#define RDFONUM (r)
Value:
  rdfonum[r >= 0 && r <= opt.num_nodes \
              ? r                      \
              : (interr("bad RDFONUM index", r, 4), 0)]
Definition at line 1209 of file pointsto.c.
SLOT
#define SLOT (sl)
Value:
  gpsd.slot[sl >= 0 && sl <= gpsd.nslots \
                ? sl                     \
                : (interr("bad SLOT index", sl, 4), 0)]
Definition at line 204 of file pointsto.c.
TLINK
#define TLINK (tpdx)
Value:
  gtpd.stg_base[tpdx >= 0 && tpdx < gtpd.stg_avail             \
                    ? tpdx                                     \
                    : (interr("bad TLINK index", tpdx, 4), 0)] \
      .link
Definition at line 92 of file pointsto.c.
TPTE_APTEX
#define TPTE_APTEX (ptex)
Value:
  gpte.stg_base[ptex >= 0 && ptex < gpte.stg_avail                  \
                    ? ptex                                          \
                    : (interr("bad TPTE_APTEX index", ptex, 4), 0)] \
      .aptex
Definition at line 304 of file pointsto.c.
TPTE_FLAG
#define TPTE_FLAG (ptex)
Value:
  gpte.stg_base[ptex >= 0 && ptex < gpte.stg_avail                 \
                    ? ptex                                         \
                    : (interr("bad TPTE_FLAG index", ptex, 4), 0)] \
      .flag
Definition at line 330 of file pointsto.c.
TPTE_NEXT
#define TPTE_NEXT (ptex)
Value:
  gpte.stg_base[ptex >= 0 && ptex < gpte.stg_avail                 \
                    ? ptex                                         \
                    : (interr("bad TPTE_NEXT index", ptex, 4), 0)] \
      .next
Definition at line 299 of file pointsto.c.
TPTE_NULL
#define TPTE_NULL -1
Definition at line 296 of file pointsto.c.
TPTE_SPTR
#define TPTE_SPTR (ptex)
Value:
  APTE_SPTR(gpte.stg_base[ptex >= 0 && ptex < gpte.stg_avail                 \
                              ? ptex                                         \
                              : (interr("bad TPTE_SPTR index", ptex, 4), 0)] \
                .aptex)
Definition at line 314 of file pointsto.c.
TPTE_STRIDE
#define TPTE_STRIDE (ptex)
Value:
  APTE_STRIDE(                                                           \
      gpte.stg_base[ptex >= 0 && ptex < gpte.stg_avail                   \
                        ? ptex                                           \
                        : (interr("bad TPTE_STRIDE index", ptex, 4), 0)] \
          .aptex)
Definition at line 324 of file pointsto.c.
TPTE_TYPE
#define TPTE_TYPE (ptex)
Value:
  APTE_TYPE(gpte.stg_base[ptex >= 0 && ptex < gpte.stg_avail                 \
                              ? ptex                                         \
                              : (interr("bad TPTE_TYPE index", ptex, 4), 0)] \
                .aptex)
Definition at line 309 of file pointsto.c.
TPTE_UNINIT
#define TPTE_UNINIT 1
Definition at line 295 of file pointsto.c.
TPTE_UNK
#define TPTE_UNK 0
Definition at line 294 of file pointsto.c.
TPTE_VAL
#define TPTE_VAL (ptex)
Value:
  APTE_VAL(gpte.stg_base[ptex >= 0 && ptex < gpte.stg_avail                \
                             ? ptex                                        \
                             : (interr("bad TPTE_VAL index", ptex, 4), 0)] \
               .aptex)
Definition at line 319 of file pointsto.c.
TRACEBIT [1/3]
#define TRACEBIT 0x100000
Definition at line 3996 of file pointsto.c.
TRACEBIT [2/3]
#define TRACEBIT 0x1000000
Definition at line 3996 of file pointsto.c.
TRACEBIT [3/3]
#define TRACEBIT 0x100000
Definition at line 3996 of file pointsto.c.
TRACEFLAG [1/3]
#define TRACEFLAG 10
Definition at line 3995 of file pointsto.c.
TRACEFLAG [2/3]
#define TRACEFLAG 10
Definition at line 3995 of file pointsto.c.
TRACEFLAG [3/3]
#define TRACEFLAG 10
Definition at line 3995 of file pointsto.c.
TRACESTRING
#define TRACESTRING "pte-"
Definition at line 33 of file pointsto.c.
TSYM
#define TSYM (tpdx)
Value:
  gtpd.stg_base[tpdx >= 0 && tpdx < gtpd.stg_avail            \
                    ? tpdx                                    \
                    : (interr("bad TSYM index", tpdx, 4), 0)] \
      .sym
Definition at line 82 of file pointsto.c.
TT_ANON
#define TT_ANON 0x150
Definition at line 115 of file pointsto.c.
TT_CON
#define TT_CON 0x1a0
Definition at line 125 of file pointsto.c.
TT_GDYN
#define TT_GDYN 0x160
Definition at line 117 of file pointsto.c.
TT_GLOB
#define TT_GLOB 0x120
Definition at line 109 of file pointsto.c.
TT_IGDYN
#define TT_IGDYN 0x170
Definition at line 119 of file pointsto.c.
TT_IIND
#define TT_IIND 0x1c0
Definition at line 129 of file pointsto.c.
TT_ILDYN
#define TT_ILDYN 0x190
Definition at line 123 of file pointsto.c.
TT_IND
#define TT_IND 0x1b0
Definition at line 127 of file pointsto.c.
TT_ISYM
#define TT_ISYM 0x140
Definition at line 113 of file pointsto.c.
TT_LDYN
#define TT_LDYN 0x180
Definition at line 121 of file pointsto.c.
TT_MEM
#define TT_MEM 0x1d0
Definition at line 131 of file pointsto.c.
TT_NLOC
#define TT_NLOC 0x1e0
Definition at line 133 of file pointsto.c.
TT_PSYM
#define TT_PSYM 0x130
Definition at line 111 of file pointsto.c.
TT_UNINIT
#define TT_UNINIT 0x100
Definition at line 105 of file pointsto.c.
TT_UNK
#define TT_UNK 0x110
Definition at line 107 of file pointsto.c.
TTE_NULL
#define TTE_NULL -1
Definition at line 135 of file pointsto.c.
TTIMP
#define TTIMP (typ) ((typ)&TTIMPFLAG)
Definition at line 146 of file pointsto.c.
TTIMPFLAG
#define TTIMPFLAG 2
Definition at line 140 of file pointsto.c.
TTMASK
#define TTMASK (typ) ((typ)&0xfffd)
Definition at line 144 of file pointsto.c.
TTMASKMUST
#define TTMASKMUST (typ) ((typ)&0xfffe)
Definition at line 142 of file pointsto.c.
TTMUST
#define TTMUST (typ) ((typ)&TTMUSTFLAG)
Definition at line 145 of file pointsto.c.
TTMUSTFLAG
#define TTMUSTFLAG 1
Definition at line 139 of file pointsto.c.
TTYPE
#define TTYPE (tpdx)
Value:
  gtpd.stg_base[tpdx >= 0 && tpdx < gtpd.stg_avail             \
                    ? tpdx                                     \
                    : (interr("bad TTYPE index", tpdx, 4), 0)] \
      .type
Definition at line 77 of file pointsto.c.
TVAL
#define TVAL (tpdx)
Value:
  gtpd.stg_base[tpdx >= 0 && tpdx < gtpd.stg_avail            \
                    ? tpdx                                    \
                    : (interr("bad TVAL index", tpdx, 4), 0)] \
      .val
Definition at line 87 of file pointsto.c.
Function Documentation
_addtpte()
static void _addtpte (int lhspsdx, int ptex, int imprecise, int mstride) static
Definition at line 1898 of file pointsto.c.
References _addtpte(), add_list(), CHANGES, find_psd(), free_list_slot(), get_apte(), imprecise_ptetype(), LHEAD, match(), PSD_SLOT, TPTE_APTEX, TPTE_NEXT, TPTE_SPTR, TPTE_STRIDE, TPTE_TYPE, TPTE_UNK, TPTE_VAL, TT_GDYN, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_PSYM, and TTMASK.
Referenced by _addtpte(), add_tptelist(), addtpte(), and inittpte().
_find_pointer_assignments_f90()
static void _find_pointer_assignments_f90 (int astx, int * pstdx) static
Definition at line 1459 of file pointsto.c.
References a, A_ARGCNTG, A_OPTYPEG, A_TKNG, arg, args, ARGT_ARG, aux, AUX::dpdsc_base, dummy, find_stride(), gdyn, globalv, make_address(), make_address_for_ast(), make_assignment(), stride, TT_CON, TT_LDYN, and TT_UNK.
Referenced by find_pointer_assignments_f90().
add_fpsrc()
static int add_fpsrc (int psdx, int fpsrcx) static
Definition at line 2982 of file pointsto.c.
References FPSRC_NEXT, FPSRC_PTELIST, FPSRC_SPTR, FPSRC_TYPE, n, PSD_PARENT, PSD_SYM, PSD_TYPE, STG_NEXT, TT_GLOB, TT_ISYM, TT_MEM, and TT_PSYM.
Referenced by set_std_pta().
add_fpte()
static void add_fpte (int ptex, int fpsrcx) static
Definition at line 3017 of file pointsto.c.
References FPSRC_PTELIST, FPTE_NEXT, FPTE_SPTR, FPTE_STRIDE, FPTE_TYPE, FPTE_VAL, n, STG_NEXT, TPTE_SPTR, TPTE_STRIDE, TPTE_TYPE, TPTE_VAL, TT_ANON, TT_CON, TT_GDYN, TT_IGDYN, TT_ILDYN, TT_ISYM, TT_LDYN, TT_NLOC, TT_PSYM, and TTMASK.
Referenced by set_std_pta().
add_list()
static void add_list (int ptex, int psdx, int imprecise, int mstride) static
Definition at line 1672 of file pointsto.c.
References copy_pte(), LHEAD, PSD_SLOT, and TPTE_NEXT.
Referenced by _addtpte().
add_psd()
static void add_psd (int tpdx, int type, int parent, int sym, bool lhs) static
Definition at line 950 of file pointsto.c.
References gpsd, is_source_nonlocal(), lhs, parent, PSD_CHILD, PSD_HASHLK, PSD_NEXT, PSD_PARENT, PSD_SLOT, PSD_SYM, PSD_TYPE, psdhsh, PSDHSZ, STG_NEXT, t, TLINK, TT_ISYM, TT_PSYM, TTIMP, TTIMPFLAG, TTMASK, type, and val.
Referenced by build_psd(), and points_to_anal().
add_target_tptelist()
static void add_target_tptelist (int lhspsdx, int ptelistx) static
Definition at line 2169 of file pointsto.c.
References add_tptelist(), LHEAD, PSD_SLOT, TPTE_UNK, and unk_all().
Referenced by interpret().
add_tptelist()
static void add_tptelist (int lhspsdx, int ptelistx) static
Definition at line 2102 of file pointsto.c.
References _addtpte(), gpsd, mark_apte_targets(), might_target(), SLOT, TPTE_NEXT, and TPTE_UNK.
Referenced by add_target_tptelist(), interpret(), and replace_tptelist().
addtpte()
static void addtpte (int lhspsdx, int ptex) static
Definition at line 2069 of file pointsto.c.
References _addtpte(), gpsd, mark_apte_targets(), might_target(), and SLOT.
Referenced by interpret(), and replacepte().
build_psd()
static void build_psd (int tdsx, bool lhs) static
Definition at line 999 of file pointsto.c.
References add_psd(), build_psd(), lhs, TLINK, TSYM, TT_GLOB, TT_IIND, TT_IND, TT_ISYM, TT_MEM, TT_PSYM, TTYPE, and TVAL.
Referenced by build_psd(), and make_assignment().
buildrdfo()
static void buildrdfo (int v) static
Definition at line 1223 of file pointsto.c.
References buildrdfo(), FG_SUCC, PSI_NEXT, PSI_NODE, PSI_P_NULL, RDFO, rdfocount, RDFONUM, and s.
Referenced by buildrdfo(), and init_points_to_prop().
check_pte()
static void check_pte (const char * ch) static
Definition at line 2765 of file pointsto.c.
References ASNEXT, check_this_assignment(), ERR_Fatal, FG_STDFIRST, FG_STDLAST, FIRSTAS, gbl, gpsd, gpte, HEAD, interr(), nodeoffset, OPT::num_nodes, opt, STD_FG, STD_NEXT, stdx, TPTE_FLAG, TPTE_NEXT, and TPTE_UNINIT.
Referenced by points_to().
check_this_assignment()
static int check_this_assignment (int asx, int v) static
Definition at line 2728 of file pointsto.c.
References AS_ADD_DIRECT, AS_DIRECT, AS_INIT, ASRHS, ASTYPE, gbl, gpte, and TPTE_FLAG.
Referenced by check_pte().
copy_list()
static int copy_list (int ptelistx) static
Definition at line 1684 of file pointsto.c.
References copy_pte(), TPTE_NEXT, TPTE_UNK, and TTE_NULL.
Referenced by effective_rhs(), points_to(), and pte_changed().
copy_pte()
static int copy_pte (int ptex, int imprecise, int mstride) static
Definition at line 1140 of file pointsto.c.
References copy_pte(), get_pte(), imprecise_ptetype(), TPTE_SPTR, TPTE_STRIDE, TPTE_TYPE, TPTE_VAL, TT_IIND, TT_IND, TT_MEM, and TTMASK.
Referenced by add_list(), copy_list(), copy_pte(), and pte_changed().
different_pta()
static bool different_pta (int pta1, int pta2) static
Definition at line 3171 of file pointsto.c.
References FALSE, FPSRC_NEXT, FPSRC_PTELIST, FPSRC_SPTR, FPSRC_TYPE, FPTE_NEXT, FPTE_SPTR, FPTE_STRIDE, FPTE_TYPE, FPTE_VAL, and TRUE.
Referenced by set_std_pta().
effective_rhs()
static int effective_rhs (int psdx) static
Definition at line 2184 of file pointsto.c.
References copy_list(), ERR_Fatal, free_list(), get_apte(), interr(), LHEAD, PSD_PARENT, PSD_SLOT, PSD_TYPE, TPTE_APTEX, TPTE_NEXT, TPTE_SPTR, TPTE_STRIDE, TPTE_TYPE, TPTE_UNINIT, TPTE_UNK, TPTE_VAL, TT_CON, TT_IIND, TT_IND, TT_ISYM, TT_PSYM, TT_UNINIT, TT_UNK, and TTMASK.
Referenced by interpret().
f90_fini_pointsto()
void f90_fini_pointsto (void)
Definition at line 2962 of file pointsto.c.
References NULL, STD_NEXT, stdx, and STG_DELETE.
Referenced by call_analyze(), convert_forall(), pstride_analysis(), and transform().
f90_init()
static void f90_init (void) static
Definition at line 2943 of file pointsto.c.
References A_OPTYPEG, gpsd, last_pta, STD_AST, STD_NEXT, stdx, and STG_ALLOC.
Referenced by points_to().
find_apte()
static int find_apte (int type, int sptr, int val) static
Definition at line 1086 of file pointsto.c.
References APTE_HASHLK, APTE_SPTR, APTE_TYPE, APTE_VAL, aptehsh, APTEHSZ, h, sptr, type, and val.
Referenced by mark_apte_targets(), and might_target().
find_imprecise_match()
static int find_imprecise_match (int lptex, int ptelistx) static
Definition at line 2651 of file pointsto.c.
References imprecise_match(), m, and TPTE_NEXT.
Referenced by pte_changed().
find_pointer_assignments_f90()
static void find_pointer_assignments_f90 (int stdx) static
Definition at line 1555 of file pointsto.c.
References _find_pointer_assignments_f90(), ast_traverse(), ast_unvisit(), ast_visit(), globalv, NULL, prevasx, STD_AST, and stdx.
Referenced by points_to_anal().
find_psd()
static int find_psd (int type, int parent, int sym) static
Definition at line 1039 of file pointsto.c.
References parent, PSD_HASHLK, PSD_PARENT, PSD_SYM, PSD_TYPE, psdhsh, PSDHSZ, TTE_NULL, type, and val.
Referenced by _addtpte().
find_stride()
static int find_stride (int astx) static
Definition at line 1411 of file pointsto.c.
References ASD_SUBS, CONVAL2G, DTY, sptr, TY_BINT, TY_INT, TY_INT8, and TY_SINT.
Referenced by _find_pointer_assignments_f90().
fini_points_to_all()
void fini_points_to_all (void)
Definition at line 4121 of file pointsto.c.
References gdyn, gpsd, gpte, and STG_DELETE.
fini_points_to_anal()
static void fini_points_to_anal (void) static
Definition at line 4083 of file pointsto.c.
References STG_DELETE.
Referenced by points_to_anal().
fini_points_to_prop()
static void fini_points_to_prop (void) static
Definition at line 4092 of file pointsto.c.
References FREE, gpsd, gpte, localhead, nodeoffset, NULL, optshrd_end(), rdfo, rdfonum, and STG_DELETE.
Referenced by points_to().
free_list()
static void free_list (int ptelistx) static
Definition at line 1182 of file pointsto.c.
References free_pte(), and TPTE_NEXT.
Referenced by effective_rhs(), free_list_slot(), interpret(), and pte_changed().
free_list_slot()
static void free_list_slot (int sl) static
Definition at line 1196 of file pointsto.c.
References free_list(), LHEAD, and TTE_NULL.
Referenced by _addtpte(), interpret(), points_to(), replace_tptelist(), replacepte(), unk_all(), and unk_globals().
free_pte()
static void free_pte (int ptex) static
Definition at line 1163 of file pointsto.c.
References free_pte(), gpte, TPTE_APTEX, TPTE_NEXT, TPTE_TYPE, TPTE_VAL, TT_IIND, TT_IND, TT_MEM, and TTMASK.
Referenced by free_list(), and free_pte().
get_apte()
static int get_apte (int type, int sptr, int val, int stride) static
Definition at line 1057 of file pointsto.c.
References APTE_HASHLK, APTE_MARK, APTE_SPTR, APTE_STRIDE, APTE_TYPE, APTE_VAL, aptehsh, APTEHSZ, h, sptr, STG_NEXT, stride, type, and val.
Referenced by _addtpte(), effective_rhs(), get_pte(), imprecise_match(), and init_points_to_anal().
get_pte()
static int get_pte (int type, int sptr, int val, int stride) static
Definition at line 1105 of file pointsto.c.
References get_apte(), gpte, sptr, STG_NEXT, stride, TPTE_APTEX, TPTE_NEXT, TTE_NULL, type, and val.
Referenced by copy_pte(), make_assignment(), and points_to().
imprecise_match()
static int imprecise_match (int lptex, int ptex) static
Definition at line 2557 of file pointsto.c.
References ERR_Fatal, get_apte(), imprecise_match(), interr(), m, TPTE_APTEX, TPTE_SPTR, TPTE_STRIDE, TPTE_TYPE, TPTE_VAL, TT_ANON, TT_CON, TT_GDYN, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_NLOC, TT_PSYM, TT_UNINIT, TT_UNK, and TTMASK.
Referenced by find_imprecise_match(), and imprecise_match().
imprecise_ptetype()
static int imprecise_ptetype (int ptetype) static
Definition at line 1123 of file pointsto.c.
References TT_GDYN, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, and TT_PSYM.
Referenced by _addtpte(), and copy_pte().
init_points_to_anal()
static void init_points_to_anal (void) static
Definition at line 4006 of file pointsto.c.
References a, aptehsh, APTEHSZ, BZERO, FIRSTAS, gdyn, get_apte(), gpsd, gpte, nmeb, NULL, PSD_TYPE, psdhsh, PSDHSZ, STG_ALLOC, STG_CLEAR_ALL, TLINK, TPTE_APTEX, TPTE_NEXT, TPTE_NULL, TPTE_UNINIT, TPTE_UNK, TT_GLOB, TT_UNINIT, TT_UNK, TTE_NULL, and TTYPE.
Referenced by points_to_anal().
init_points_to_prop()
static void init_points_to_prop (void) static
Definition at line 4061 of file pointsto.c.
References buildrdfo(), BZERO, flg, flowgraph(), gpte, NEW, OPT::num_nodes, opt, optshrd_init(), rdfo, rdfocount, rdfonum, VTX_NODE, and FLG::x.
Referenced by points_to().
inittpte()
static void inittpte (int lhspsdx, int ptex) static
Definition at line 2083 of file pointsto.c.
References _addtpte().
Referenced by interpret().
interpret()
static void interpret (int asx) static
Definition at line 2254 of file pointsto.c.
References add_target_tptelist(), add_tptelist(), addtpte(), AS_ADD_DIRECT, AS_ADD_INDIRECT, AS_CLEAR, AS_DIRECT, AS_INDIRECT, AS_INIT, AS_UNK, ASLHS, ASRHS, ASSTRIDE, ASTYPE, DBGBIT, effective_rhs(), ERR_Fatal, ERR_Warning, free_list(), free_list_slot(), gbl, gpsd, inittpte(), interr(), is_source_global(), LHEAD, PSD_SLOT, PSD_TYPE, putassign(), putptelist(), puttarget(), puttargets(), replace_tptelist(), replacepte(), SLOT, stride, TPTE_UNK, Trace, TRACEBIT, TRACEFLAG, TT_GLOB, TT_IIND, TT_IND, TT_ISYM, TT_MEM, TT_PSYM, TT_UNINIT, TT_UNK, unk_all(), and unk_globals().
Referenced by points_to().
is_source_global()
static int is_source_global (int psdx) static
Definition at line 772 of file pointsto.c.
References ERR_Fatal, FALSE, interr(), is_source_global(), LHEAD, PSD_PARENT, PSD_SLOT, PSD_SYM, PSD_TYPE, sptr, TPTE_NEXT, TPTE_SPTR, TPTE_TYPE, TPTE_UNK, TRUE, TT_ANON, TT_CON, TT_GDYN, TT_GLOB, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_NLOC, TT_PSYM, TT_UNINIT, TT_UNK, and TTMASK.
Referenced by interpret(), is_source_global(), and unk_globals().
is_source_nonlocal()
static int is_source_nonlocal (int psdx) static
Definition at line 869 of file pointsto.c.
References ERR_Warning, FALSE, gbl, interr(), is_source_nonlocal(), LHEAD, PSD_PARENT, PSD_SLOT, PSD_SYM, PSD_TYPE, sptr, TPTE_NEXT, TPTE_SPTR, TPTE_TYPE, TPTE_UNK, TRUE, TT_ANON, TT_CON, TT_GDYN, TT_GLOB, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_NLOC, TT_PSYM, TT_UNINIT, TT_UNK, and TTMASK.
Referenced by add_psd(), is_source_nonlocal(), and points_to().
make_address()
static int make_address (int astx, int pt, int sym, int offset) static
Definition at line 1240 of file pointsto.c.
References offset, pt, STG_NEXT, TSYM, TT_UNK, TTYPE, and TVAL.
Referenced by _find_pointer_assignments_f90(), and make_address_for_ast().
make_address_for_ast()
static int make_address_for_ast (int astx, int parentast) static
Definition at line 1256 of file pointsto.c.
References a, A_TKNG, DTY, make_address(), sptr, TT_ISYM, TT_PSYM, and TT_UNK.
Referenced by _find_pointer_assignments_f90().
make_assignment()
static void make_assignment (int v, int iltx, int lhstds, int rhstds, int add, int stride) static
Definition at line 1300 of file pointsto.c.
References add(), AS_ADD_DIRECT, AS_ADD_INDIRECT, AS_DIRECT, AS_INDIRECT, AS_UNINIT, AS_UNK, ASILT, ASLHS, ASNEXT, ASNODE, ASRHS, ASSTRIDE, ASTYPE, build_psd(), DBGBIT, FG_TO_BIH, FIRSTAS, gbl, get_pte(), prevasx, printast(), putassign(), puttds(), STG_NEXT, stride, TLINK, TRACEBIT, TRACEFLAG, TSYM, TT_CON, TT_GDYN, TT_IGDYN, TT_ILDYN, TT_ISYM, TT_LDYN, TT_PSYM, TT_UNINIT, TT_UNK, TTYPE, and TVAL.
Referenced by _find_pointer_assignments_f90().
mark_apte_targets()
static void mark_apte_targets (int psdx) static
Definition at line 1739 of file pointsto.c.
References APTE_MARK, ERR_Fatal, ERR_Warning, find_apte(), interr(), LHEAD, marker, nonlocal_mark, PSD_PARENT, PSD_SLOT, PSD_SYM, PSD_TYPE, some_nonlocal_mark, sptr, TPTE_NEXT, TPTE_SPTR, TPTE_TYPE, TPTE_UNK, TPTE_VAL, TT_ANON, TT_CON, TT_GDYN, TT_GLOB, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_MEM, TT_NLOC, TT_PSYM, TT_UNINIT, TT_UNK, TTMASK, and unknown_mark.
Referenced by add_tptelist(), and addtpte().
might_target()
static int might_target (int psdx) static
Definition at line 1822 of file pointsto.c.
References APTE_MARK, ERR_Warning, FALSE, find_apte(), interr(), LHEAD, marker, PSD_PARENT, PSD_SLOT, PSD_SYM, PSD_TYPE, some_nonlocal_mark, sptr, TPTE_APTEX, TPTE_NEXT, TPTE_TYPE, TPTE_UNK, TRUE, TT_ANON, TT_CON, TT_GDYN, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_NLOC, TT_PSYM, TT_UNINIT, TT_UNK, TTMASK, and unknown_mark.
Referenced by add_tptelist(), and addtpte().
points_to()
void points_to (void)
Do dataflow analysis to determine pointer target information store pointer target information at loads and stores.
build flow graph
build reverse depth-first ordering
build pseudo-assignments to represent pointer modifications
use data-flow analysis to propagate pointer information around flow graph
modify the ILI/NME to represent the propagated information
For F90.
Definition at line 4199 of file pointsto.c.
References AS_INIT, ASNEXT, ASTYPE, BZERO, check_pte(), copy_list(), DBGBIT, dstdp(), dstdps(), ERR_Fatal, f90_init(), FG_STDFIRST, FG_STDLAST, FG_SUCC, FG_TO_BIH, fini_points_to_prop(), FIRSTAS, free_list_slot(), gbl, gcount, get_pte(), gpsd, HEAD, init_points_to_prop(), interpret(), interr(), is_source_nonlocal(), iteration, LHEAD, localhead, NEW, nmeb, nodeoffset, OPT::num_nodes, offset, opt, PSD_SLOT, PSI_NEXT, PSI_NODE, PSI_P_NULL, pte_changed(), putstdpta(), puttargets(), r, RDFO, rdfocount, RDFONUM, s, set_std_pta(), SLOT, STD_NEXT, STD_PREV, stdx, STG_ALLOC, TPTE_NULL, TPTE_UNINIT, Trace, TRACEBIT, TRACEFLAG, TT_NLOC, and TTE_NULL.
Referenced by call_analyze(), convert_forall(), pstride_analysis(), and transform().
points_to_anal()
void points_to_anal (void)
Definition at line 4137 of file pointsto.c.
References a, add_psd(), ASNEXT, DBGBIT, find_pointer_assignments_f90(), fini_points_to_anal(), FIRSTAS, gbl, gpsd, init_points_to_anal(), nmeb, NULL, OPT::num_nodes, opt, putassign(), STD_NEXT, stdx, Trace, TRACEBIT, TRACEFLAG, and TT_GLOB.
pta_aligned()
bool pta_aligned (int ptrstdx, int ptrsptr)
Definition at line 3781 of file pointsto.c.
References FALSE, FPSRC_NEXT, FPSRC_PTELIST, FPSRC_SPTR, FPTE_NEXT, FPTE_SPTR, FPTE_STRIDE, FPTE_TYPE, NULL, sptr, TRUE, TT_ANON, TT_CON, TT_GDYN, TT_GLOB, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_MEM, TT_NLOC, TT_PSYM, TT_UNINIT, and TT_UNK.
Referenced by analyze().
pta_conflict()
bool pta_conflict (int ptrstdx, int ptrsptr, int targetstdx, int targetsptr, int targetpointer, int targettarget)
Definition at line 3318 of file pointsto.c.
References DBGBIT, FALSE, FPSRC_NEXT, FPSRC_PTELIST, FPSRC_SPTR, FPTE_NEXT, FPTE_SPTR, FPTE_TYPE, FPTE_VAL, gbl, NULL, SYMNAME, TRACEBIT, TRACEFLAG, TRUE, TT_ANON, TT_CON, TT_GDYN, TT_GLOB, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_MEM, TT_NLOC, TT_PSYM, TT_UNINIT, and TT_UNK.
Referenced by name_dependent_check().
pta_stride1()
bool pta_stride1 (int ptrstdx, int ptrsptr)
Definition at line 3847 of file pointsto.c.
References FALSE, FPSRC_NEXT, FPSRC_PTELIST, FPSRC_SPTR, FPTE_NEXT, FPTE_STRIDE, FPTE_TYPE, NULL, TRUE, TT_ANON, TT_CON, TT_GDYN, TT_GLOB, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_MEM, TT_NLOC, TT_PSYM, TT_UNINIT, and TT_UNK.
Referenced by analyze(), and stride_1_section().
pta_target()
int pta_target (int ptrstdx, int ptrsptr, int * ptag, int * pid)
Definition at line 3916 of file pointsto.c.
References FPSRC_NEXT, FPSRC_PTELIST, FPSRC_SPTR, FPTE_NEXT, FPTE_SPTR, FPTE_TYPE, FPTE_VAL, gbl, NULL, pid, TT_ANON, TT_CON, TT_GDYN, TT_GLOB, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_MEM, TT_NLOC, TT_PSYM, TT_UNINIT, and TT_UNK.
Referenced by do_targets().
pte_changed()
static int pte_changed (int v) static
Definition at line 2668 of file pointsto.c.
References copy_list(), copy_pte(), DBGBIT, FG_TO_BIH, find_imprecise_match(), free_list(), gpsd, HEAD, LHEAD, putnodetargets(), TPTE_NEXT, TPTE_UNINIT, TPTE_UNK, Trace, TRACEBIT, TRACEFLAG, and TTE_NULL.
Referenced by points_to().
putassign()
static void putassign (int asx) static
Definition at line 647 of file pointsto.c.
References AS_ADD_DIRECT, AS_ADD_INDIRECT, AS_CLEAR, AS_DIRECT, AS_INDIRECT, AS_INIT, AS_UNK, ASILT, ASLHS, ASNODE, ASRHS, ASSTRIDE, ASTYPE, gbl, putpsd(), and putpte().
Referenced by interpret(), make_assignment(), points_to_anal(), and putstdassigns().
putfpte()
static void putfpte (int fptex) static
Definition at line 3086 of file pointsto.c.
References dfile, FPTE_SPTR, FPTE_STRIDE, FPTE_TYPE, FPTE_VAL, gbl, SYMNAME, TT_ANON, TT_CON, TT_GDYN, TT_GLOB, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_MEM, TT_NLOC, TT_PSYM, TT_UNINIT, and TT_UNK.
Referenced by putstdpta().
putnodetarget()
static void putnodetarget (const char * ch, int v, int sl) static
Definition at line 739 of file pointsto.c.
References gbl, HEAD, putpsd(), putptelist(), SLOT, TPTE_UNK, and TTE_NULL.
Referenced by putnodetargets().
putnodetargets()
static void putnodetargets (const char * ch, int v) static
Definition at line 757 of file pointsto.c.
References gpsd, and putnodetarget().
Referenced by pte_changed().
putpsd()
static void putpsd (int psdx) static
Definition at line 533 of file pointsto.c.
References gbl, PSD_PARENT, PSD_SYM, PSD_TYPE, putpsd(), SYMNAME, TT_GLOB, TT_IIND, TT_IND, TT_ISYM, TT_MEM, TT_NLOC, TT_PSYM, TT_UNINIT, and TT_UNK.
Referenced by putassign(), putnodetarget(), putpsd(), and puttarget().
putpte()
static void putpte (int ptex) static
Definition at line 575 of file pointsto.c.
References gbl, putpte(), SYMNAME, TPTE_APTEX, TPTE_SPTR, TPTE_STRIDE, TPTE_TYPE, TPTE_VAL, TT_ANON, TT_CON, TT_GDYN, TT_GLOB, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_MEM, TT_NLOC, TT_PSYM, TT_UNINIT, TT_UNK, TTMASK, and TTMUST.
Referenced by putassign(), putpte(), and putptelist().
putptelist()
static void putptelist (int ptelistx) static
Definition at line 700 of file pointsto.c.
References gbl, putpte(), and TPTE_NEXT.
Referenced by interpret(), putnodetarget(), and puttarget().
putsrc()
static void putsrc (int fpsrcx) static
Definition at line 3048 of file pointsto.c.
References dfile, FPSRC_SPTR, FPSRC_TYPE, SYMNAME, TT_GLOB, TT_IIND, TT_IND, TT_ISYM, TT_MEM, TT_NLOC, TT_PSYM, TT_UNINIT, and TT_UNK.
Referenced by putstdpta().
putstdassigns()
void putstdassigns (int stdx)
Definition at line 689 of file pointsto.c.
References a, ASNEXT, FIRSTAS, putassign(), and stdx.
Referenced by dstdp(), and dstdpa().
putstdpta()
void putstdpta (int stdx)
Definition at line 3150 of file pointsto.c.
References dfile, FPSRC_NEXT, FPSRC_PTELIST, FPTE_NEXT, gbl, putfpte(), putsrc(), and stdx.
Referenced by analyze(), dstdp(), dstdpa(), and points_to().
puttarget()
static void puttarget (int sl) static
Definition at line 712 of file pointsto.c.
References gbl, LHEAD, putpsd(), putptelist(), SLOT, TPTE_UNK, and TTE_NULL.
Referenced by interpret(), and puttargets().
puttargets()
static void puttargets (void) static
Definition at line 730 of file pointsto.c.
References gpsd, and puttarget().
Referenced by interpret(), and points_to().
puttds()
static void puttds (int tdsx) static
Definition at line 468 of file pointsto.c.
References gbl, puttds(), SYMNAME, TSYM, TT_ANON, TT_CON, TT_GDYN, TT_GLOB, TT_IGDYN, TT_IIND, TT_ILDYN, TT_IND, TT_ISYM, TT_LDYN, TT_MEM, TT_NLOC, TT_PSYM, TT_UNINIT, TT_UNK, TTYPE, and TVAL.
Referenced by make_assignment(), and puttds().
replace_tptelist()
static void replace_tptelist (int lhspsdx, int ptelistx) static
Definition at line 2158 of file pointsto.c.
References add_tptelist(), free_list_slot(), and PSD_SLOT.
Referenced by interpret().
replacepte()
static void replacepte (int lhspsdx, int ptex) static
Definition at line 2095 of file pointsto.c.
References addtpte(), free_list_slot(), and PSD_SLOT.
Referenced by interpret().
safe_symbol()
static int safe_symbol (int psdx) static
Definition at line 848 of file pointsto.c.
References FALSE, PSD_SYM, PSD_TYPE, sptr, TT_ISYM, and TT_PSYM.
Referenced by unk_globals().
set_std_pta()
static void set_std_pta (int stdx, int change) static
Definition at line 3205 of file pointsto.c.
References add_fpsrc(), add_fpte(), different_pta(), gpsd, last_pta, LHEAD, SLOT, stdx, TPTE_NEXT, TPTE_UNK, and TTE_NULL.
Referenced by points_to().
STG_DECLARE() [1/7]
static STG_DECLARE (apte , APTE) static
References STG_INIT.
STG_DECLARE() [2/7]
static STG_DECLARE (as , AS) static
References STG_INIT.
STG_DECLARE() [3/7]
static STG_DECLARE (fpsrc , FPSRC) static
STG_DECLARE() [4/7]
static STG_DECLARE (fpte , FPTE) static
STG_DECLARE() [5/7]
static STG_DECLARE (ganon , int) static
References STG_INIT.
STG_DECLARE() [6/7]
static STG_DECLARE (gtpd , TPD) static
References STG_INIT.
STG_DECLARE() [7/7]
static STG_DECLARE (head , int) static
References STG_INIT.
unk_all()
static void unk_all (void) static
Definition at line 1704 of file pointsto.c.
References free_list_slot(), gpsd, LHEAD, and TPTE_UNK.
Referenced by add_target_tptelist(), and interpret().
unk_globals()
static void unk_globals (void) static
Definition at line 1717 of file pointsto.c.
References free_list_slot(), gpsd, is_source_global(), LHEAD, safe_symbol(), SLOT, and TPTE_UNK.
Referenced by interpret().
Variable Documentation
aptehsh
int aptehsh[APTEHSZ] static
Definition at line 237 of file pointsto.c.
Referenced by find_apte(), get_apte(), and init_points_to_anal().
CHANGES
int CHANGES static
Definition at line 1883 of file pointsto.c.
Referenced by _addtpte().
dfile
FILE* dfile static
Definition at line 3045 of file pointsto.c.
Referenced by putfpte(), putsrc(), and putstdpta().
struct { ... } gcount
Referenced by points_to().
struct { ... } gdyn
Referenced by _find_pointer_assignments_f90(), fini_points_to_all(), and init_points_to_anal().
globalv
int globalv static
Definition at line 1456 of file pointsto.c.
Referenced by _find_pointer_assignments_f90(), and find_pointer_assignments_f90().
struct { ... } gpsd
Referenced by add_psd(), add_tptelist(), addtpte(), check_pte(), f90_init(), fini_points_to_all(), fini_points_to_prop(), init_points_to_anal(), interpret(), points_to(), points_to_anal(), pte_changed(), putnodetargets(), puttargets(), set_std_pta(), unk_all(), and unk_globals().
struct { ... } gpte
Referenced by check_pte(), check_this_assignment(), fini_points_to_all(), fini_points_to_prop(), free_pte(), get_pte(), init_points_to_anal(), and init_points_to_prop().
last_pta
int last_pta = 0 static
Definition at line 2940 of file pointsto.c.
Referenced by f90_init(), and set_std_pta().
local_dyn
int local_dyn
Definition at line 454 of file pointsto.c.
localhead
int* localhead = NULL static
Definition at line 436 of file pointsto.c.
Referenced by fini_points_to_prop(), and points_to().
marker
unsigned int marker = 0 static
Definition at line 1736 of file pointsto.c.
Referenced by mark_apte_targets(), and might_target().
nodeoffset
int* nodeoffset = NULL static
Definition at line 421 of file pointsto.c.
Referenced by check_pte(), fini_points_to_prop(), and points_to().
nonlocal_mark
unsigned int nonlocal_mark = 0 static
Definition at line 1737 of file pointsto.c.
Referenced by mark_apte_targets().
nslots
int nslots
Definition at line 165 of file pointsto.c.
ntot
int ntot
Definition at line 458 of file pointsto.c.
prevasx
int prevasx static
Definition at line 418 of file pointsto.c.
Referenced by find_pointer_assignments_f90(), and make_assignment().
psdhsh
int psdhsh[PSDHSZ] static
Definition at line 222 of file pointsto.c.
Referenced by add_psd(), find_psd(), and init_points_to_anal().
rdfo
int * rdfo static
Definition at line 1205 of file pointsto.c.
Referenced by fini_points_to_prop(), and init_points_to_prop().
rdfocount
int rdfocount static
Definition at line 1205 of file pointsto.c.
Referenced by buildrdfo(), init_points_to_prop(), and points_to().
rdfonum
int * rdfonum static
Definition at line 1205 of file pointsto.c.
Referenced by fini_points_to_prop(), and init_points_to_prop().
save_stg_avail
int save_stg_avail
Definition at line 291 of file pointsto.c.
save_stg_free
int save_stg_free
Definition at line 291 of file pointsto.c.
slot
int* slot
Definition at line 164 of file pointsto.c.
Referenced by intern_constant(), ll_extend_md_node(), ll_finish_variable(), ll_get_const_addrspacecast(), ll_get_const_bitcast(), ll_get_const_gep(), ll_get_const_int(), ll_get_global_pointer(), ll_reserve_md_node(), and ll_update_md_node().
some_nonlocal_mark
unsigned int some_nonlocal_mark = 0 static
Definition at line 1737 of file pointsto.c.
Referenced by mark_apte_targets(), and might_target().
tot
int tot
Definition at line 458 of file pointsto.c.
unknown_mark
unsigned int unknown_mark = 0 static
Definition at line 1737 of file pointsto.c.
Referenced by mark_apte_targets(), and might_target().
xstg_free
int xstg_free
Definition at line 291 of file pointsto.c.