flang: powi_256.c File Reference
powi_256.c File Reference
#include <immintrin.h>
#include "mth_intrinsics.h"
Functions
vrs8_t __fs_powi_8_avx2 (vrs8_t _vx, vis8_t _vi)
Compute R4(:)**I4(:)
vrs8_t __fs_powi_8m_avx2 (vrs8_t _vx, vis8_t _vi, vis8_t _vm)
Compute R4(:)**I4(:) under mask.
vrd4_t __fd_powk_4_avx2 (vrd4_t _vx, vid4_t _vi)
Compute R8(:)**I8(:)
vrd4_t __fd_powk_4m_avx2 (vrd4_t _vx, vid4_t _vi, vid4_t _vm)
Compute R8(:)**I8(:) under mask.
vrd4_t __fd_powi_4_avx2 (vrd4_t _vx, vis4_t _vi)
Compute R8(:)**I4(:)
vrd4_t __fd_powi_4m_avx2 (vrd4_t _vx, vis4_t _vi, vid4_t _vm)
Compute R8(:)**I8(:) under mask.
vrs8_t __fs_powk_2x4_avx2 (vrs8_t _vx, vid4_t _vl, vid4_t _vu)
(internal) Kernel to compute R4(0:3)**I8_lower(:), Compute R4(4:7)**I8_upper(:)
vrs8_t __fs_powk_8_avx2 (vrs8_t _vx, vid4_t _vl, vid4_t _vu)
(external) Compute R4(0:3)**I8_lower(:), Compute R4(4:7)**I8_upper(:)
vrs8_t __fs_powk_8m_avx2 (vrs8_t _vx, vid4_t _vl, vid4_t _vu, vis8_t _vm)
(external) Compute R4(0:3)**I8_lower(:), Compute R4(4:7)**I8_upper(:)
Function Documentation
__fd_powi_4_avx2()
vrd4_t __fd_powi_4_avx2 (vrd4_t _vx, vis4_t _vi)
Compute R8(:)**I4(:)
Parameters
[in] _vx (__m256d) R8(:)
[in] _vi (__m256i) I4(:)
Returns
(__m256d) R8(:)**I4(:)
Definition at line 165 of file powi_256.c.
References __fd_powk_4_avx2().
__fd_powi_4m_avx2()
vrd4_t __fd_powi_4m_avx2 (vrd4_t _vx, vis4_t _vi, vid4_t _vm)
Compute R8(:)**I8(:) under mask.
Parameters
[in] _vx (__m256d) R8(:)
[in] _vi (__m256i) I4(:)
[in] _vm (__m256i) I8(:)
Returns
(__m256d) WHERE(_vm(:) != 0) R8(:)**I8(:)
Definition at line 178 of file powi_256.c.
References __fd_powk_4m_avx2().
__fd_powk_4_avx2()
vrd4_t __fd_powk_4_avx2 (vrd4_t _vx, vid4_t _vi)
Compute R8(:)**I8(:)
Parameters
[in] _vx (__m256d) R8(:)
[in] _vi (__m256i) I8(:)
Returns
(__m256d) R4(:)**I8(:)
Definition at line 93 of file powi_256.c.
Referenced by __fd_powi_4_avx2(), and __fd_powk_4m_avx2().
__fd_powk_4m_avx2()
vrd4_t __fd_powk_4m_avx2 (vrd4_t _vx, vid4_t _vi, vid4_t _vm)
Compute R8(:)**I8(:) under mask.
Parameters
[in] _vx (__m256d) R8(:)
[in] _vi (__m256i) I8(:)
[in] _vm (__m256i) I8(:)
Returns
(__m256d) WHERE(_vm(:) != 0) R8(:)**I8(:)
Definition at line 142 of file powi_256.c.
References __fd_powk_4_avx2().
Referenced by __fd_powi_4m_avx2().
__fs_powi_8_avx2()
vrs8_t __fs_powi_8_avx2 (vrs8_t _vx, vis8_t _vi)
Compute R4(:)**I4(:)
Parameters
[in] _vx (__m256) R4(:)
[in] _vi (__m256i) I4(:)
Returns
(__m256) R4(:)**I4(:)
Definition at line 23 of file powi_256.c.
Referenced by __fs_powi_8m_avx2(), and __fs_powk_8_avx2().
__fs_powi_8m_avx2()
vrs8_t __fs_powi_8m_avx2 (vrs8_t _vx, vis8_t _vi, vis8_t _vm)
Compute R4(:)**I4(:) under mask.
Parameters
[in] _vx (__m256) R4(:)
[in] _vi (__m256i) I4(:)
[in] _vm (__m256i) I4(:)
Returns
(__m256) WHERE(_vm(:) != 0) R4(:)**I4(:)
Definition at line 70 of file powi_256.c.
References __fs_powi_8_avx2().
__fs_powk_2x4_avx2()
vrs8_t __fs_powk_2x4_avx2 (vrs8_t _vx, vid4_t _vl, vid4_t _vu)
(internal) Kernel to compute R4(0:3)**I8_lower(:), Compute R4(4:7)**I8_upper(:)
Parameters
[in] _vx (__m256d) R4(:)
[in] _vl (__m256i) I8(:)
[in] _vu (__m256i) I8(:)
Returns
(__m256d) (R4(4:7)**I8_upper(:))<<128 | R4(0:3)**I8_lower(:)
Definition at line 191 of file powi_256.c.
References i.
Referenced by __fs_powk_8_avx2().
__fs_powk_8_avx2()
vrs8_t __fs_powk_8_avx2 (vrs8_t _vx, vid4_t _vl, vid4_t _vu)
(external) Compute R4(0:3)**I8_lower(:), Compute R4(4:7)**I8_upper(:)
Parameters
[in] _vx (__m256d) R4(:)
[in] _vl (__m256i) I8(:)
[in] _vu (__m256i) I8(:)
Returns
(__m256d) (R4(4:7)**I8_upper(:))<<128 | R4(0:3)**I8_lower(:)
Definition at line 254 of file powi_256.c.
References __fs_powi_8_avx2(), and __fs_powk_2x4_avx2().
Referenced by __fs_powk_8m_avx2().
__fs_powk_8m_avx2()
vrs8_t __fs_powk_8m_avx2 (vrs8_t _vx, vid4_t _vl, vid4_t _vu, vis8_t _vm)
(external) Compute R4(0:3)**I8_lower(:), Compute R4(4:7)**I8_upper(:)
Parameters
[in] _vx (__m256d) R4(:)
[in] _vl (__m256i) I8(:)
[in] _vu (__m256i) I8(:)
[in] _vm (__m256i) I8(:)
Returns
(__m256d) (R4(4:7)**I8_upper(:))<<128 | R4(0:3)**I8_lower(:)
Definition at line 295 of file powi_256.c.
References __fs_powk_8_avx2().