flang: powi_128.c File Reference
powi_128.c File Reference
#include <immintrin.h>
#include "mth_intrinsics.h"
Functions
vrs4_t __fs_powi_4_sse4 (vrs4_t _vx, vis4_t _vi)
Compute R4(:)**I4(:)
vrs4_t __fs_powi_4m_sse4 (vrs4_t _vx, vis4_t _vi, vis4_t _vm)
Compute R4(:)**I4(:) under mask.
vrd2_t __fd_powk_2_sse4 (vrd2_t _vx, vid2_t _vi)
Compute R8(:)**I8(:)
vrd2_t __fd_powk_2m_sse4 (vrd2_t _vx, vid2_t _vi, vid2_t _vm)
Compute R8(:)**I8(:) under mask.
vrd2_t __fd_powi_2_sse4 (vrd2_t _vx, vis4_t _vi)
Compute R8(:)**I4(:)
vrd2_t __fd_powi_2m_sse4 (vrd2_t _vx, vis4_t _vi, vid2_t _vm)
Compute R8(:)**I8(:) under mask.
vrs4_t __fs_powk_2x2_sse4 (vrs4_t _vx, vid2_t _vl, vid2_t _vu)
(internal) Kernel to compute R4(0:3)**I8_lower(:), Compute R4(4:7)**I8_upper(:)
vrs4_t __fs_powk_4_sse4 (vrs4_t _vx, vid2_t _vl, vid2_t _vu)
(external) Compute R4(0:3)**I8_lower(:), Compute R4(4:7)**I8_upper(:)
vrs4_t __fs_powk_4m_sse4 (vrs4_t _vx, vid2_t _vl, vid2_t _vu, vis4_t _vm)
(external) Compute R4(0:3)**I8_lower(:), Compute R4(4:7)**I8_upper(:)
Function Documentation
__fd_powi_2_sse4()
vrd2_t __fd_powi_2_sse4 (vrd2_t _vx, vis4_t _vi)
Compute R8(:)**I4(:)
Parameters
[in] _vx (__m128d) R8(:)
[in] _vi (__m128i) I4(:)
Returns
(__m128d) R8(:)**I4(:)
Definition at line 165 of file powi_128.c.
References __fd_powk_2_sse4().
__fd_powi_2m_sse4()
vrd2_t __fd_powi_2m_sse4 (vrd2_t _vx, vis4_t _vi, vid2_t _vm)
Compute R8(:)**I8(:) under mask.
Parameters
[in] _vx (__m128d) R8(:)
[in] _vi (__m128i) I4(:)
[in] _vm (__m128i) I8(:)
Returns
(__m128d) WHERE(_vm(:) != 0) R8(:)**I8(:)
Definition at line 178 of file powi_128.c.
References __fd_powk_2m_sse4().
__fd_powk_2_sse4()
vrd2_t __fd_powk_2_sse4 (vrd2_t _vx, vid2_t _vi)
Compute R8(:)**I8(:)
Parameters
[in] _vx (__m128d) R8(:)
[in] _vi (__m128i) I8(:)
Returns
(__m128d) R4(:)**I8(:)
Definition at line 93 of file powi_128.c.
Referenced by __fd_powi_2_sse4(), and __fd_powk_2m_sse4().
__fd_powk_2m_sse4()
vrd2_t __fd_powk_2m_sse4 (vrd2_t _vx, vid2_t _vi, vid2_t _vm)
Compute R8(:)**I8(:) under mask.
Parameters
[in] _vx (__m128d) R8(:)
[in] _vi (__m128i) I8(:)
[in] _vm (__m128i) I8(:)
Returns
(__m128d) WHERE(_vm(:) != 0) R8(:)**I8(:)
Definition at line 142 of file powi_128.c.
References __fd_powk_2_sse4().
Referenced by __fd_powi_2m_sse4().
__fs_powi_4_sse4()
vrs4_t __fs_powi_4_sse4 (vrs4_t _vx, vis4_t _vi)
Compute R4(:)**I4(:)
Parameters
[in] _vx (__m128) R4(:)
[in] _vi (__m128i) I4(:)
Returns
(__m128) R4(:)**I4(:)
Definition at line 23 of file powi_128.c.
Referenced by __fs_powi_4m_sse4(), and __fs_powk_4_sse4().
__fs_powi_4m_sse4()
vrs4_t __fs_powi_4m_sse4 (vrs4_t _vx, vis4_t _vi, vis4_t _vm)
Compute R4(:)**I4(:) under mask.
Parameters
[in] _vx (__m128) R4(:)
[in] _vi (__m128i) I4(:)
[in] _vm (__m128i) I4(:)
Returns
(__m128) WHERE(_vm(:) != 0) R4(:)**I4(:)
Definition at line 70 of file powi_128.c.
References __fs_powi_4_sse4().
__fs_powk_2x2_sse4()
vrs4_t __fs_powk_2x2_sse4 (vrs4_t _vx, vid2_t _vl, vid2_t _vu)
(internal) Kernel to compute R4(0:3)**I8_lower(:), Compute R4(4:7)**I8_upper(:)
Parameters
[in] _vx (__m128d) R4(:)
[in] _vl (__m128i) I8(:)
[in] _vu (__m128i) I8(:)
Returns
(__m128d) (R4(4:7)**I8_upper(:))<<128 | R4(0:3)**I8_lower(:)
Definition at line 191 of file powi_128.c.
References i.
Referenced by __fs_powk_4_sse4().
__fs_powk_4_sse4()
vrs4_t __fs_powk_4_sse4 (vrs4_t _vx, vid2_t _vl, vid2_t _vu)
(external) Compute R4(0:3)**I8_lower(:), Compute R4(4:7)**I8_upper(:)
Parameters
[in] _vx (__m128d) R4(:)
[in] _vl (__m128i) I8(:)
[in] _vu (__m128i) I8(:)
Returns
(__m128d) (R4(4:7)**I8_upper(:))<<128 | R4(0:3)**I8_lower(:)
Definition at line 247 of file powi_128.c.
References __fs_powi_4_sse4(), and __fs_powk_2x2_sse4().
Referenced by __fs_powk_4m_sse4().
__fs_powk_4m_sse4()
vrs4_t __fs_powk_4m_sse4 (vrs4_t _vx, vid2_t _vl, vid2_t _vu, vis4_t _vm)
(external) Compute R4(0:3)**I8_lower(:), Compute R4(4:7)**I8_upper(:)
Parameters
[in] _vx (__m128d) R4(:)
[in] _vl (__m128i) I8(:)
[in] _vu (__m128i) I8(:)
[in] _vm (__m128i) I8(:)
Returns
(__m128d) (R4(4:7)**I8_upper(:))<<128 | R4(0:3)**I8_lower(:)
Definition at line 288 of file powi_128.c.
References __fs_powk_4_sse4().