flang: ll_abi.cpp File Reference
ppc64le/ll_abi.cpp File Reference
#include "gbldefs.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "llutil.h"
#include "ll_structure.h"
#include "dtypeutl.h"
Classes
struct pwr_homogeneous_aggr
Macros
#define DT_VOIDNONE DT_NONE
#define DT_BASETYPE(dt) (dt)
Functions
void ll_abi_compute_call_conv (LL_ABI_Info *abi, int func_sptr, int jsra_flags)
...
static int update_homogeneous (void *context, DTYPE dtype, unsigned address, int member_sptr)
static LL_Type * check_vector_registers (LL_Module *module, DTYPE dtype)
static enum LL_ABI_ArgKind classify_int (DTYPE dtype)
static bool classify_common (LL_ABI_Info *abi, LL_ABI_ArgInfo *arg, DTYPE dtype)
void ll_abi_classify_return_dtype (LL_ABI_Info *abi, DTYPE dtype)
...
void ll_abi_classify_arg_dtype (LL_ABI_Info *abi, LL_ABI_ArgInfo *arg, DTYPE dtype)
...
Macro Definition Documentation
DT_BASETYPE
#define DT_BASETYPE (dt) (dt)
Definition at line 26 of file ppc64le/ll_abi.cpp.
DT_VOIDNONE
#define DT_VOIDNONE DT_NONE
Definition at line 24 of file ppc64le/ll_abi.cpp.
Function Documentation
check_vector_registers()
static LL_Type * check_vector_registers (LL_Module * module, DTYPE dtype) static
Definition at line 112 of file ppc64le/ll_abi.cpp.
References pwr_homogeneous_aggr::base_bytes, pwr_homogeneous_aggr::base_type, LL_Type_::data_type, ISZ_T, LL_DOUBLE, LL_FLOAT, ll_get_array_type(), LL_VECTOR, pwr_homogeneous_aggr::module, NULL, size, update_homogeneous(), visit_flattened_dtype(), and zsize_of().
Referenced by classify_common().
classify_common()
static bool classify_common (LL_ABI_Info * abi, LL_ABI_ArgInfo * arg, DTYPE dtype) static
Definition at line 166 of file ppc64le/ll_abi.cpp.
References arg, check_vector_registers(), classify_int(), DT_ISINT, DT_ISSCALAR, DT_VOIDNONE, LL_ARG_DIRECT, and LL_ABI_Info_::module.
Referenced by ll_abi_classify_arg_dtype(), and ll_abi_classify_return_dtype().
classify_int()
static enum LL_ABI_ArgKind classify_int (DTYPE dtype) static
Definition at line 155 of file ppc64le/ll_abi.cpp.
References DT_ISUNSIGNED, LL_ARG_DIRECT, LL_ARG_SIGNEXT, LL_ARG_ZEROEXT, and zsize_of().
Referenced by classify_common().
ll_abi_classify_arg_dtype()
void ll_abi_classify_arg_dtype (LL_ABI_Info * abi, LL_ABI_ArgInfo * arg, DTYPE dtype)
...
Definition at line 215 of file ppc64le/ll_abi.cpp.
References arg, assert, classify_common(), DT_BASETYPE, DT_ISCMPLX, DTY, ERR_Fatal, LL_ARG_BYVAL, LL_ARG_COERCE, ll_coercion_type(), ll_convert_dtype(), ll_get_pointer_type(), ll_get_struct_type(), LL_ABI_Info_::module, and zsize_of().
ll_abi_classify_return_dtype()
void ll_abi_classify_return_dtype (LL_ABI_Info * abi, DTYPE dtype)
...
Definition at line 192 of file ppc64le/ll_abi.cpp.
References LL_ABI_Info_::arg, classify_common(), DT_BASETYPE, ISZ_T, LL_ABI_ArgInfo_::kind, LL_ARG_COERCE, LL_ARG_INDIRECT, ll_coercion_type(), LL_NOTYPE, LL_ABI_Info_::module, size, LL_ABI_ArgInfo_::type, and zsize_of().
ll_abi_compute_call_conv()
void ll_abi_compute_call_conv (LL_ABI_Info * abi, int func_sptr, int jsra_flags)
...
Definition at line 29 of file ppc64le/ll_abi.cpp.
update_homogeneous()
static int update_homogeneous (void * context, DTYPE dtype, unsigned address, int member_sptr) static
Definition at line 47 of file ppc64le/ll_abi.cpp.
References pwr_homogeneous_aggr::base_bytes, pwr_homogeneous_aggr::base_type, LL_Type_::data_type, DT_BASETYPE, DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_FLOAT, DTY, ISZ_T, ll_convert_dtype(), LL_DOUBLE, LL_FLOAT, LL_VECTOR, pwr_homogeneous_aggr::module, size, and zsize_of().
Referenced by check_vector_registers().