flang: pragma.h File Reference
pragma.h File Reference
Macros
#define ACC_DATAMOVEMENT_DISABLED XBIT(195, 0x400)
Enumerations
enum PR_SCOPE {
PR_NOSCOPE = 0 , PR_GLOBAL = 1 , PR_ROUTINE = 2 , PR_LOOP = 3 ,
PR_LINE = 4
}
enum PR_ACCREDUCT_OP {
PR_ACCREDUCT_OP_ADD = 0 , PR_ACCREDUCT_OP_MUL = 1 , PR_ACCREDUCT_OP_MAX = 2 , PR_ACCREDUCT_OP_MIN = 3 ,
PR_ACCREDUCT_OP_BITAND = 4 , PR_ACCREDUCT_OP_BITIOR = 5 , PR_ACCREDUCT_OP_BITEOR = 6 , PR_ACCREDUCT_OP_LOGAND = 7 ,
PR_ACCREDUCT_OP_LOGOR = 8 , PR_ACCREDUCT_OP_EQV = 9 , PR_ACCREDUCT_OP_NEQV = 10
}
enum PR_PRAGMA {
PR_NONE = 0 , PR_INLININGON = 1 , PR_INLININGOFF = 2 , PR_ALWAYSINLINE = 3 ,
PR_MAYINLINE = 4 , PR_NEVERINLINE = 5 , PR_ACCEL = 6 , PR_ENDACCEL = 7 ,
PR_INLINEONLY = 8 , PR_INLINETYPE = 9 , PR_INLINEAS = 10 , PR_INLINEALIGN = 11 ,
PR_ACCCOPYIN = 12 , PR_ACCCOPYOUT = 13 , PR_ACCLOCAL = 14 , PR_ACCELLP = 15 ,
PR_ACCVECTOR = 16 , PR_ACCPARALLEL = 17 , PR_ACCSEQ = 18 , PR_ACCHOST = 19 ,
PR_ACCPRIVATE = 20 , PR_ACCCACHE = 21 , PR_ACCSHORTLOOP = 22 , PR_ACCBEGINDIR = 23 ,
PR_ACCIF = 24 , PR_ACCUNROLL = 25 , PR_ACCKERNEL = 26 , PR_ACCCOPY = 27 ,
PR_ACCDATAREG = 28 , PR_ACCENDDATAREG = 29 , PR_ACCUPDATEHOST = 30 , PR_ACCUPDATEDEVICE = 31 ,
PR_ACCUPDATE = 32 , PR_ACCINDEPENDENT = 33 , PR_ACCWAIT = 34 , PR_ACCNOWAIT = 35 ,
PR_ACCIMPDATAREG = 36 , PR_ACCENDIMPDATAREG = 37 , PR_ACCMIRROR = 38 , PR_ACCREFLECT = 39 ,
PR_KERNELBEGIN = 40 , PR_KERNEL = 41 , PR_ENDKERNEL = 42 , PR_KERNELTILE = 43 ,
PR_ACCDEVSYM = 44 , PR_ACCIMPDATAREGX = 45 , PR_KERNEL_NEST = 46 , PR_KERNEL_GRID = 47 ,
PR_KERNEL_BLOCK = 48 , PR_ACCDEVICEPTR = 49 , PR_ACCPARUNROLL = 50 , PR_ACCVECUNROLL = 51 ,
PR_ACCSEQUNROLL = 52 , PR_ACCCUDACALL = 53 , PR_ACCSCALARREG = 54 , PR_ACCENDSCALARREG = 55 ,
PR_ACCPARCONSTRUCT = 56 , PR_ACCENDPARCONSTRUCT = 57 , PR_ACCKERNELS = 58 , PR_ACCENDKERNELS = 59 ,
PR_ACCCREATE = 60 , PR_ACCPRESENT = 61 , PR_ACCPCOPY = 62 , PR_ACCPCOPYIN = 63 ,
PR_ACCPCOPYOUT = 64 , PR_ACCPCREATE = 65 , PR_ACCASYNC = 66 , PR_KERNEL_STREAM = 67 ,
PR_KERNEL_DEVICE = 68 , PR_ACCWAITDIR = 69 , PR_ACCKLOOP = 70 , PR_ACCPLOOP = 71 ,
PR_ACCGANG = 72 , PR_ACCWORKER = 73 , PR_ACCFIRSTPRIVATE = 74 , PR_ACCNUMGANGS = 75 ,
PR_ACCNUMWORKERS = 76 , PR_ACCVLENGTH = 77 , PR_ACCWAITARG = 78 , PR_ACCREDUCTION = 79 ,
PR_ACCREDUCTOP = 80 , PR_ACCCACHEDIR = 81 , PR_ACCCACHEARG = 82 , PR_ACCHOSTDATA = 83 ,
PR_ACCENDHOSTDATA = 84 , PR_ACCUSEDEVICE = 85 , PR_ACCCOLLAPSE = 86 , PR_ACCDEVICERES = 87 ,
PR_ACCDEVICEID = 88 , PR_ACCDELETE = 89 , PR_ACCPDELETE = 90 , PR_ACCENTERDATA = 91 ,
PR_ACCEXITDATA = 92 , PR_ACCLOOPPRIVATE = 93 , PR_ACCUPDATESELF = 94 , PR_ACCLINK = 95 ,
PR_ACCTILE = 96 , PR_ACCAUTO = 97 , PR_ACCGANGCHUNK = 98 , PR_ACCDEFNONE = 99 ,
PR_ACCPNOT = 100 , PR_ACCNUMGANGS2 = 101 , PR_ACCNUMGANGS3 = 102 , PR_ACCGANGDIM = 103 ,
PR_ACCDEFPRESENT = 104 , PR_ACCFORCECOLLAPSE = 105 , PR_CUFLOOPPRIVATE = 106 , PR_ACCCACHEREADONLY = 107 ,
PR_ACCFINALEXITDATA = 108 , PR_ACCUPDATEHOSTIFP = 109 , PR_ACCUPDATEDEVICEIFP = 110 , PR_ACCUPDATESELFIFP = 111 ,
PR_ACCINITDIR = 112 , PR_ACCSHUTDOWNDIR = 113 , PR_ACCDEFAULT_ASYNC = 114 , PR_ACCDEVICE_NUM = 115 ,
PR_ACCSETDIR = 116 , PR_ACCUSEDEVICEIFP = 117 , PR_ACCNO_CREATE = 118 , PR_ACCSERIAL = 119 ,
PR_ACCENDSERIAL = 120 , PR_ACCSLOOP = 121 , PR_ACCATTACH = 122 , PR_ACCDETACH = 123 ,
PR_ACCTKLOOP = 124 , PR_ACCTPLOOP = 125 , PR_ACCTSLOOP = 126 , PR_ACCCOMPARE = 127 ,
PR_PGICOMPARE = 128 , PR_PCASTCOMPARE = 129 , PR_MAPALLOC = 130 , PR_MAPDELETE = 131 ,
PR_MAPFROM = 132 , PR_MAPRELEASE = 133 , PR_MAPTO = 134 , PR_MAPTOFROM = 135 ,
PR_UPDATEFROM = 136 , PR_UPDATETO = 137
}
Functions
void apply_nodepchk (int dir_lineno, int dir_scope)
...
void p_pragma (char *pg, int pline)
...
void push_lpprg (int beg_line)
...
void rouprg_enter (void)
...
Macro Definition Documentation
ACC_DATAMOVEMENT_DISABLED
#define ACC_DATAMOVEMENT_DISABLED XBIT(195, 0x400)
Definition at line 184 of file pragma.h.
Enumeration Type Documentation
PR_ACCREDUCT_OP
enum PR_ACCREDUCT_OP
Enumerator
PR_ACCREDUCT_OP_ADD
PR_ACCREDUCT_OP_MUL
PR_ACCREDUCT_OP_MAX
PR_ACCREDUCT_OP_MIN
PR_ACCREDUCT_OP_BITAND
PR_ACCREDUCT_OP_BITIOR
PR_ACCREDUCT_OP_BITEOR
PR_ACCREDUCT_OP_LOGAND
PR_ACCREDUCT_OP_LOGOR
PR_ACCREDUCT_OP_EQV
PR_ACCREDUCT_OP_NEQV
Definition at line 25 of file pragma.h.
PR_PRAGMA
enum PR_PRAGMA
Enumerator
PR_NONE
PR_INLININGON
PR_INLININGOFF
PR_ALWAYSINLINE
PR_MAYINLINE
PR_NEVERINLINE
PR_ACCEL
PR_ENDACCEL
PR_INLINEONLY
PR_INLINETYPE
PR_INLINEAS
PR_INLINEALIGN
PR_ACCCOPYIN
PR_ACCCOPYOUT
PR_ACCLOCAL
PR_ACCELLP
PR_ACCVECTOR
PR_ACCPARALLEL
PR_ACCSEQ
PR_ACCHOST
PR_ACCPRIVATE
PR_ACCCACHE
PR_ACCSHORTLOOP
PR_ACCBEGINDIR
PR_ACCIF
PR_ACCUNROLL
PR_ACCKERNEL
PR_ACCCOPY
PR_ACCDATAREG
PR_ACCENDDATAREG
PR_ACCUPDATEHOST
PR_ACCUPDATEDEVICE
PR_ACCUPDATE
PR_ACCINDEPENDENT
PR_ACCWAIT
PR_ACCNOWAIT
PR_ACCIMPDATAREG
PR_ACCENDIMPDATAREG
PR_ACCMIRROR
PR_ACCREFLECT
PR_KERNELBEGIN
PR_KERNEL
PR_ENDKERNEL
PR_KERNELTILE
PR_ACCDEVSYM
PR_ACCIMPDATAREGX
PR_KERNEL_NEST
PR_KERNEL_GRID
PR_KERNEL_BLOCK
PR_ACCDEVICEPTR
PR_ACCPARUNROLL
PR_ACCVECUNROLL
PR_ACCSEQUNROLL
PR_ACCCUDACALL
PR_ACCSCALARREG
PR_ACCENDSCALARREG
PR_ACCPARCONSTRUCT
PR_ACCENDPARCONSTRUCT
PR_ACCKERNELS
PR_ACCENDKERNELS
PR_ACCCREATE
PR_ACCPRESENT
PR_ACCPCOPY
PR_ACCPCOPYIN
PR_ACCPCOPYOUT
PR_ACCPCREATE
PR_ACCASYNC
PR_KERNEL_STREAM
PR_KERNEL_DEVICE
PR_ACCWAITDIR
PR_ACCKLOOP
PR_ACCPLOOP
PR_ACCGANG
PR_ACCWORKER
PR_ACCFIRSTPRIVATE
PR_ACCNUMGANGS
PR_ACCNUMWORKERS
PR_ACCVLENGTH
PR_ACCWAITARG
PR_ACCREDUCTION
PR_ACCREDUCTOP
PR_ACCCACHEDIR
PR_ACCCACHEARG
PR_ACCHOSTDATA
PR_ACCENDHOSTDATA
PR_ACCUSEDEVICE
PR_ACCCOLLAPSE
PR_ACCDEVICERES
PR_ACCDEVICEID
PR_ACCDELETE
PR_ACCPDELETE
PR_ACCENTERDATA
PR_ACCEXITDATA
PR_ACCLOOPPRIVATE
PR_ACCUPDATESELF
PR_ACCLINK
PR_ACCTILE
PR_ACCAUTO
PR_ACCGANGCHUNK
PR_ACCDEFNONE
PR_ACCPNOT
PR_ACCNUMGANGS2
PR_ACCNUMGANGS3
PR_ACCGANGDIM
PR_ACCDEFPRESENT
PR_ACCFORCECOLLAPSE
PR_CUFLOOPPRIVATE
PR_ACCCACHEREADONLY
PR_ACCFINALEXITDATA
PR_ACCUPDATEHOSTIFP
PR_ACCUPDATEDEVICEIFP
PR_ACCUPDATESELFIFP
PR_ACCINITDIR
PR_ACCSHUTDOWNDIR
PR_ACCDEFAULT_ASYNC
PR_ACCDEVICE_NUM
PR_ACCSETDIR
PR_ACCUSEDEVICEIFP
PR_ACCNO_CREATE
PR_ACCSERIAL
PR_ACCENDSERIAL
PR_ACCSLOOP
PR_ACCATTACH
PR_ACCDETACH
PR_ACCTKLOOP
PR_ACCTPLOOP
PR_ACCTSLOOP
PR_ACCCOMPARE
PR_PGICOMPARE
PR_PCASTCOMPARE
PR_MAPALLOC
PR_MAPDELETE
PR_MAPFROM
PR_MAPRELEASE
PR_MAPTO
PR_MAPTOFROM
PR_UPDATEFROM
PR_UPDATETO
Definition at line 42 of file pragma.h.
PR_SCOPE
enum PR_SCOPE
Enumerator
PR_NOSCOPE
PR_GLOBAL
PR_ROUTINE
PR_LOOP
PR_LINE
Definition at line 14 of file pragma.h.
Function Documentation
apply_nodepchk()
void apply_nodepchk (int dir_lineno, int dir_scope)
...
Definition at line 1564 of file pragma.c.
Referenced by begin_combine_constructs(), and semsmp().
p_pragma()
void p_pragma (char * pg, int pline)
...
Definition at line 336 of file pragma.c.
push_lpprg()
void push_lpprg (int beg_line)
...
...
Definition at line 1522 of file pragma.c.
Referenced by direct_loop_enter().
rouprg_enter()
void rouprg_enter (void)
...
Definition at line 1553 of file pragma.c.