flang: pragma.c File Reference
pragma.c File Reference
PGC & PGFTN directive scan & semantic module.
#include "pragma.h"
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "semant.h"
#include "miscutil.h"
#include "semsym.h"
#include "fdirect.h"
#include "mach.h"
Classes
struct svstg
struct c
Macros
#define TR0(s)
#define TR1(s, a)
#define TR2(s, a, b)
#define TR3(s, a, b, c)
#define S_NONE 0
#define S_LOOP 1
#define S_ROUTINE 2
#define S_GLOBAL 4
#define DIR_OFFSET(x, y) (&(x->y) - (int *)x)
#define GET_SVS (SVS *) getitem(12, sizeof(SVS))
#define _CS 1 /* c symbol */
#define _DI 2 /* digit */
#define _BL 4 /* c's blank */
#define _HD 8 /* hex digit */
#define _WS 16 /* white space (' ' or '\t') */
#define _MASK(c) ((int)c & 0xFF)
#define isident(c) (ctable[_MASK(c)] & (_CS | _DI))
#define iswhite(c) (ctable[_MASK(c)] & _WS)
#define ishex(c) (ctable[_MASK(c)] & (_HD | _DI))
#define isdig(c) (ctable[_MASK(c)] & _DI)
#define T_END 0
#define T_ERR -1
#define T_NULL -2
#define T_MINUS '-'
#define T_LP '('
#define T_RP ')'
#define T_IDENT 'a'
#define T_INT '1'
#define T_EQUAL '='
#define T_COMMA ','
#define T_STR '"'
#define T_COLON ':'
#define T_PCENT '%'
#define T_QUEST '?'
#define T_LSB '['
#define T_RSB ']'
#define T_STAR '*'
#define TOKMAX 2048
#define LCASE(x) lcase(x)
#define SW_ASSOC 0
#define SW_DEPCHK 1
#define SW_EQVCHK 2
#define SW_LSTVAL 3
#define SW_PERMUTE 4
#define SW_SMALLVECT 5
#define SW_SPLIT 6
#define SW_VECTOR 7
#define SW_VINTR 8
#define SW_RELATION 9
#define SW_RECOG 10
#define SW_TRANSFORM 11
#define SW_IVDEP 12
#define SW_SWPIPE 13
#define SW_OPT 14
#define SW_DUAL 15
#define SW_ALTCODE 16
#define SW_SAFEPTR 17
#define SW_SAFE 18
#define SW_STREAM 19
#define SW_BOUNDS 20
#define SW_FCON 21
#define SW_SINGLE 22
#define SW_FUNC32 23
#define SW_FRAME 24
#define SW_INFO 25
#define SW_STRIPSZ 26
#define SW_X 27
#define SW_Y 28
#define SW_C 29
#define SW_FINI 30
#define SW_INIT 31
#define SW_IDENT 32
#define SW_WEAK 33
#define SW_INVARIF 34
#define SW_CONCUR 35
#define SW_UNROLL 36
#define SW_CNCALL 37
#define SW_DIST 38
#define SW_INDEP 39
#define SW_LASTDIM 40
#define SW_SAFELASTVAL 41
#define SW_PARANDSER 42
#define SW_PARALLEL 43
#define SW_SERIAL 44
#define SW_L3F 45
#define SW_CACHE_ALIGN 46
#define SW_SSE 47
#define SW_GP16 48
#define SW_GP32 49
#define SW_SUJ 50
#define SW_INDEX_REUSE 51
#define SW_ZEROTRIP 52
#define SW_LAI 53
#define SW_UNROLLFACTOR 54
#define SW_PRECOND 55
#define SW_TRIPCOUNT 56
#define SW_MSCHED 57
#define SW_NOINLINE 58
#define SW_LPTEST1 59
#define SW_LPTEST2 60
#define SW_ALIGN 61
#define SW_LOOPCOUNT 62
#define SW_CB10WA 63
#define SW_ESCTYALIAS 64
#define SW_TP 65
#define SW_SAVE_ALL_GP 66
#define SW_SAVE_ALL 67
#define SW_SAVE_USED_GP 68
#define SW_SAVE_USED 69
#define SW_LIBM 70
#define SW_SIMD 71
#define SW_FORCEINLINE 73
#define NTAB (sizeof(table) / sizeof(struct c))
Typedefs
typedef struct svstg SVS
Functions
static bool do_sw (void)
void rouprg_enter (void)
...
static int gtok (void)
static int g_id (const char *)
static void lcase (char *)
static void scan_vectorlength (int *toSet, int *num, int typ)
void p_pragma (char *pg, int pline)
...
static void set_flg (int, int)
static void assn (int, int)
static void bset (int, int)
static void bclr (int, int)
static int getindex (struct c table[], int, char *)
void push_lpprg (int beg_line)
Entering a loop. Apply the loop pragmas which occurred before the loop.
void apply_nodepchk (int dir_lineno, int dir_scope)
...
Variables
static int scope
static bool do_now = false
static char * currp
static int lineno
static DIRSET * currdir
static char ctable [256]
static char ctok [TOKMAX]
static INT itok
static int upper_to_lower = 0
static bool craydir
static bool sundir
static struct c table []
static bool no_specified
static int allowextended = 0
Detailed Description
PGC & PGFTN directive scan & semantic module.
Definition in file pragma.c.
Macro Definition Documentation
_BL
#define _BL 4 /* c's blank */
Definition at line 97 of file pragma.c.
_CS
#define _CS 1 /* c symbol */
Definition at line 95 of file pragma.c.
_DI
#define _DI 2 /* digit */
Definition at line 96 of file pragma.c.
_HD
#define _HD 8 /* hex digit */
Definition at line 98 of file pragma.c.
_MASK
#define _MASK (c) ((int)c & 0xFF)
Definition at line 101 of file pragma.c.
_WS
#define _WS 16 /* white space (' ' or '\t') */
Definition at line 99 of file pragma.c.
DIR_OFFSET
#define DIR_OFFSET (x, y) (&(x->y) - (int *)x)
Definition at line 73 of file pragma.c.
GET_SVS
#define GET_SVS (SVS *) getitem(12, sizeof(SVS))
Definition at line 82 of file pragma.c.
isdig
#define isdig (c) (ctable[_MASK(c)] & _DI)
Definition at line 109 of file pragma.c.
ishex
#define ishex (c) (ctable[_MASK(c)] & (_HD | _DI))
Definition at line 108 of file pragma.c.
isident
#define isident (c) (ctable[_MASK(c)] & (_CS | _DI))
Definition at line 103 of file pragma.c.
iswhite
#define iswhite (c) (ctable[_MASK(c)] & _WS)
Definition at line 106 of file pragma.c.
LCASE
#define LCASE (x) lcase(x)
Definition at line 270 of file pragma.c.
NTAB
#define NTAB (sizeof(table) / sizeof(struct c))
Definition at line 562 of file pragma.c.
S_GLOBAL
#define S_GLOBAL 4
Definition at line 60 of file pragma.c.
S_LOOP
#define S_LOOP 1
Definition at line 58 of file pragma.c.
S_NONE
#define S_NONE 0
Definition at line 57 of file pragma.c.
S_ROUTINE
#define S_ROUTINE 2
Definition at line 59 of file pragma.c.
SW_ALIGN
#define SW_ALIGN 61
Definition at line 457 of file pragma.c.
SW_ALTCODE
#define SW_ALTCODE 16
Definition at line 412 of file pragma.c.
SW_ASSOC
#define SW_ASSOC 0
Definition at line 396 of file pragma.c.
SW_BOUNDS
#define SW_BOUNDS 20
Definition at line 416 of file pragma.c.
SW_C
#define SW_C 29
Definition at line 425 of file pragma.c.
SW_CACHE_ALIGN
#define SW_CACHE_ALIGN 46
Definition at line 442 of file pragma.c.
SW_CB10WA
#define SW_CB10WA 63
Definition at line 459 of file pragma.c.
SW_CNCALL
#define SW_CNCALL 37
Definition at line 433 of file pragma.c.
SW_CONCUR
#define SW_CONCUR 35
Definition at line 431 of file pragma.c.
SW_DEPCHK
#define SW_DEPCHK 1
Definition at line 397 of file pragma.c.
SW_DIST
#define SW_DIST 38
Definition at line 434 of file pragma.c.
SW_DUAL
#define SW_DUAL 15
Definition at line 411 of file pragma.c.
SW_EQVCHK
#define SW_EQVCHK 2
Definition at line 398 of file pragma.c.
SW_ESCTYALIAS
#define SW_ESCTYALIAS 64
Definition at line 460 of file pragma.c.
SW_FCON
#define SW_FCON 21
Definition at line 417 of file pragma.c.
SW_FINI
#define SW_FINI 30
Definition at line 426 of file pragma.c.
SW_FORCEINLINE
#define SW_FORCEINLINE 73
Definition at line 468 of file pragma.c.
SW_FRAME
#define SW_FRAME 24
Definition at line 420 of file pragma.c.
SW_FUNC32
#define SW_FUNC32 23
Definition at line 419 of file pragma.c.
SW_GP16
#define SW_GP16 48
Definition at line 444 of file pragma.c.
SW_GP32
#define SW_GP32 49
Definition at line 445 of file pragma.c.
SW_IDENT
#define SW_IDENT 32
Definition at line 428 of file pragma.c.
SW_INDEP
#define SW_INDEP 39
Definition at line 435 of file pragma.c.
SW_INDEX_REUSE
#define SW_INDEX_REUSE 51
Definition at line 447 of file pragma.c.
SW_INFO
#define SW_INFO 25
Definition at line 421 of file pragma.c.
SW_INIT
#define SW_INIT 31
Definition at line 427 of file pragma.c.
SW_INVARIF
#define SW_INVARIF 34
Definition at line 430 of file pragma.c.
SW_IVDEP
#define SW_IVDEP 12
Definition at line 408 of file pragma.c.
SW_L3F
#define SW_L3F 45
Definition at line 441 of file pragma.c.
SW_LAI
#define SW_LAI 53
Definition at line 449 of file pragma.c.
SW_LASTDIM
#define SW_LASTDIM 40
Definition at line 436 of file pragma.c.
SW_LIBM
#define SW_LIBM 70
Definition at line 466 of file pragma.c.
SW_LOOPCOUNT
#define SW_LOOPCOUNT 62
Definition at line 458 of file pragma.c.
SW_LPTEST1
#define SW_LPTEST1 59
Definition at line 455 of file pragma.c.
SW_LPTEST2
#define SW_LPTEST2 60
Definition at line 456 of file pragma.c.
SW_LSTVAL
#define SW_LSTVAL 3
Definition at line 399 of file pragma.c.
SW_MSCHED
#define SW_MSCHED 57
Definition at line 453 of file pragma.c.
SW_NOINLINE
#define SW_NOINLINE 58
Definition at line 454 of file pragma.c.
SW_OPT
#define SW_OPT 14
Definition at line 410 of file pragma.c.
SW_PARALLEL
#define SW_PARALLEL 43
Definition at line 439 of file pragma.c.
SW_PARANDSER
#define SW_PARANDSER 42
Definition at line 438 of file pragma.c.
SW_PERMUTE
#define SW_PERMUTE 4
Definition at line 400 of file pragma.c.
SW_PRECOND
#define SW_PRECOND 55
Definition at line 451 of file pragma.c.
SW_RECOG
#define SW_RECOG 10
Definition at line 406 of file pragma.c.
SW_RELATION
#define SW_RELATION 9
Definition at line 405 of file pragma.c.
SW_SAFE
#define SW_SAFE 18
Definition at line 414 of file pragma.c.
SW_SAFELASTVAL
#define SW_SAFELASTVAL 41
Definition at line 437 of file pragma.c.
SW_SAFEPTR
#define SW_SAFEPTR 17
Definition at line 413 of file pragma.c.
SW_SAVE_ALL
#define SW_SAVE_ALL 67
Definition at line 463 of file pragma.c.
SW_SAVE_ALL_GP
#define SW_SAVE_ALL_GP 66
Definition at line 462 of file pragma.c.
SW_SAVE_USED
#define SW_SAVE_USED 69
Definition at line 465 of file pragma.c.
SW_SAVE_USED_GP
#define SW_SAVE_USED_GP 68
Definition at line 464 of file pragma.c.
SW_SERIAL
#define SW_SERIAL 44
Definition at line 440 of file pragma.c.
SW_SIMD
#define SW_SIMD 71
Definition at line 467 of file pragma.c.
SW_SINGLE
#define SW_SINGLE 22
Definition at line 418 of file pragma.c.
SW_SMALLVECT
#define SW_SMALLVECT 5
Definition at line 401 of file pragma.c.
SW_SPLIT
#define SW_SPLIT 6
Definition at line 402 of file pragma.c.
SW_SSE
#define SW_SSE 47
Definition at line 443 of file pragma.c.
SW_STREAM
#define SW_STREAM 19
Definition at line 415 of file pragma.c.
SW_STRIPSZ
#define SW_STRIPSZ 26
Definition at line 422 of file pragma.c.
SW_SUJ
#define SW_SUJ 50
Definition at line 446 of file pragma.c.
SW_SWPIPE
#define SW_SWPIPE 13
Definition at line 409 of file pragma.c.
SW_TP
#define SW_TP 65
Definition at line 461 of file pragma.c.
SW_TRANSFORM
#define SW_TRANSFORM 11
Definition at line 407 of file pragma.c.
SW_TRIPCOUNT
#define SW_TRIPCOUNT 56
Definition at line 452 of file pragma.c.
SW_UNROLL
#define SW_UNROLL 36
Definition at line 432 of file pragma.c.
SW_UNROLLFACTOR
#define SW_UNROLLFACTOR 54
Definition at line 450 of file pragma.c.
SW_VECTOR
#define SW_VECTOR 7
Definition at line 403 of file pragma.c.
SW_VINTR
#define SW_VINTR 8
Definition at line 404 of file pragma.c.
SW_WEAK
#define SW_WEAK 33
Definition at line 429 of file pragma.c.
SW_X
#define SW_X 27
Definition at line 423 of file pragma.c.
SW_Y
#define SW_Y 28
Definition at line 424 of file pragma.c.
SW_ZEROTRIP
#define SW_ZEROTRIP 52
Definition at line 448 of file pragma.c.
T_COLON
#define T_COLON ':'
Definition at line 253 of file pragma.c.
T_COMMA
#define T_COMMA ','
Definition at line 251 of file pragma.c.
T_END
#define T_END 0
Definition at line 242 of file pragma.c.
T_EQUAL
#define T_EQUAL '='
Definition at line 250 of file pragma.c.
T_ERR
#define T_ERR -1
Definition at line 243 of file pragma.c.
T_IDENT
#define T_IDENT 'a'
Definition at line 248 of file pragma.c.
T_INT
#define T_INT '1'
Definition at line 249 of file pragma.c.
T_LP
#define T_LP '('
Definition at line 246 of file pragma.c.
T_LSB
#define T_LSB '['
Definition at line 256 of file pragma.c.
T_MINUS
#define T_MINUS '-'
Definition at line 245 of file pragma.c.
T_NULL
#define T_NULL -2
Definition at line 244 of file pragma.c.
T_PCENT
#define T_PCENT '%'
Definition at line 254 of file pragma.c.
T_QUEST
#define T_QUEST '?'
Definition at line 255 of file pragma.c.
T_RP
#define T_RP ')'
Definition at line 247 of file pragma.c.
T_RSB
#define T_RSB ']'
Definition at line 257 of file pragma.c.
T_STAR
#define T_STAR '*'
Definition at line 258 of file pragma.c.
T_STR
#define T_STR '"'
Definition at line 252 of file pragma.c.
TOKMAX
#define TOKMAX 2048
Definition at line 259 of file pragma.c.
TR0
#define TR0 (s)
Definition at line 48 of file pragma.c.
TR1
#define TR1 (s, a)
Definition at line 49 of file pragma.c.
TR2
#define TR2 (s, a, b)
Definition at line 50 of file pragma.c.
TR3
#define TR3 (s, a, b, c)
Definition at line 51 of file pragma.c.
Typedef Documentation
SVS
typedef struct svstg SVS
Function Documentation
apply_nodepchk()
void apply_nodepchk (int dir_lineno, int dir_scope)
...
Definition at line 1564 of file pragma.c.
Referenced by begin_combine_constructs(), and semsmp().
assn()
static void assn (int diroff, int v) static
Definition at line 1442 of file pragma.c.
Referenced by func_call2(), handle_allocatable_members(), precompute_arg_intrin(), precompute_args(), ptrfunc_call(), semant3(), set_descr_tag(), subr_call2(), and temp_type_descriptor().
bclr()
static void bclr (int diroff, int v) static
Definition at line 1495 of file pragma.c.
bset()
static void bset (int diroff, int v) static
Definition at line 1471 of file pragma.c.
do_sw()
static bool do_sw (void) static
Definition at line 572 of file pragma.c.
g_id()
static int g_id (const char * errstr) static
Definition at line 1833 of file pragma.c.
getindex()
static int getindex (struct c table[], int num_elem, char * string) static
Definition at line 1594 of file pragma.c.
gtok()
static int gtok (void) static
Definition at line 1656 of file pragma.c.
lcase()
static void lcase (char * str) static
Definition at line 1897 of file pragma.c.
p_pragma()
void p_pragma (char * pg, int pline)
...
Definition at line 336 of file pragma.c.
Referenced by _read_token(), crunch(), and ff_chk_pragma().
push_lpprg()
void push_lpprg (int beg_line)
Entering a loop. Apply the loop pragmas which occurred before the loop.
...
Definition at line 1522 of file pragma.c.
Referenced by direct_loop_enter().
rouprg_enter()
void rouprg_enter (void)
...
Definition at line 1553 of file pragma.c.
scan_vectorlength()
static void scan_vectorlength (int * toSet, int * num, int typ) static
Definition at line 277 of file pragma.c.
set_flg()
static void set_flg (int diroff, int v) static
Definition at line 1431 of file pragma.c.
Variable Documentation
allowextended
int allowextended = 0 static
Definition at line 1653 of file pragma.c.
craydir
bool craydir static
Definition at line 271 of file pragma.c.
ctable
char ctable[256] static
Definition at line 111 of file pragma.c.
ctok
char ctok[TOKMAX] static
Definition at line 261 of file pragma.c.
currdir
DIRSET* currdir static
Definition at line 71 of file pragma.c.
Referenced by direct_rou_load(), direct_rou_setopt(), load_dirset(), and store_dirset().
currp
char* currp static
Definition at line 69 of file pragma.c.
do_now
bool do_now = false static
Definition at line 63 of file pragma.c.
itok
INT itok static
Definition at line 262 of file pragma.c.
lineno
int lineno static
Definition at line 70 of file pragma.c.
no_specified
bool no_specified static
Definition at line 564 of file pragma.c.
scope
int scope static
Definition at line 62 of file pragma.c.
sundir
bool sundir static
Definition at line 272 of file pragma.c.
table
struct c table[] static
Definition at line 484 of file pragma.c.
upper_to_lower
int upper_to_lower = 0 static
Definition at line 263 of file pragma.c.
Referenced by crunch().