flang: prodstr.c File Reference
prodstr.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
Macros
#define TOK_ID 0
#define TOK_EQUAL 1
#define TOK_OR 2
#define TOK_EOLN 3
#define TOK_EOF 4
#define TOK_BREAK 5
#define TOK_OTHER 6
Functions
static void readln ()
static void header ()
static void footer ()
static int scan ()
static void error (char *)
static void init ()
static void output ()
int main ()
Variables
static char linbuf [121]
static char savelin [121]
static char name [60]
static char case_name [60]
static FILE * infile
static FILE * outfile
static FILE * prodfile
static int curchr
static int fstchr
static int lineno
static int current
static int bcnt = 2
static const char * tok_name []
Macro Definition Documentation
TOK_BREAK
#define TOK_BREAK 5
Definition at line 37 of file prodstr.c.
TOK_EOF
#define TOK_EOF 4
Definition at line 36 of file prodstr.c.
TOK_EOLN
#define TOK_EOLN 3
Definition at line 35 of file prodstr.c.
TOK_EQUAL
#define TOK_EQUAL 1
Definition at line 33 of file prodstr.c.
TOK_ID
#define TOK_ID 0
Definition at line 32 of file prodstr.c.
TOK_OR
#define TOK_OR 2
Definition at line 34 of file prodstr.c.
TOK_OTHER
#define TOK_OTHER 6
Definition at line 38 of file prodstr.c.
Function Documentation
error()
static void error (char * p) static
Definition at line 193 of file prodstr.c.
References lineno, and p.
Referenced by _constructf90(), _do_iface(), _doincl(), _get_token(), _ilis_are_matched(), _mk_arrdsc(), _parser(), _rd_tkline(), _readln(), _write_token(), _xtok(), acl_rewrite_asts(), add_arrnme(), add_clause(), add_iolptrs(), add_nme_with_pte(), add_ptr_assign(), add_rpct_nme(), add_to_be_used_list(), addFinalSubroutine(), alpha(), annomod_initx(), apply_use(), apply_use_stmts(), assign_intrinsic_to_pointer(), assign_pointer(), begin_combine_constructs(), begin_submodule(), cancel_type(), check_alloc_clauses(), check_barrier(), check_cancel(), check_continuation(), check_crit(), check_dealloc_clauses(), check_defined_io2(), check_derived_type_array_section(), check_derived_type_in_comm(), check_dim_error(), check_doconcurrent_ast(), check_duplicate(), check_end_subprogram(), check_kind_type_param(), check_module_prefix(), check_no_scope_sptr(), check_pure_interface(), check_targetdata(), check_valid_data_sharing(), CheckDecl(), chk_arguments(), chk_evar(), chk_fmtid(), chk_initialization_with_kind_parm(), chk_intrinsic(), chk_new_param_dt(), chk_pointer_intent(), chk_pointer_target(), chk_scalar_inttyp(), chk_struct_constructor(), chk_unitid(), chksubscr(), chksubstr(), classify_dec(), classify_kernel_pragma(), classify_pgi_dir(), classify_pgi_pragma(), classify_pragma(), classify_smp(), clause_errchk(), cmp_interfaces_strict(), cngcon(), cngshape(), cngtyp2(), collapse_assignment(), collapse_begin(), compatible_characteristics(), const_eval(), const_fold(), construct_intrinsic_acl(), conversion_warning(), copy_inargs(), copy_loop(), cray_pointer_check(), create_func_entry(), create_var(), crunch(), ctte(), decl_private_sym(), decl_procedure_sym(), declobject(), declref(), declsym(), defer_arg_chk(), defer_put_kind_type_param(), define_stfunc(), defined_io_error(), dinit(), dinit_eval(), dinit_ok(), dinit_put(), dinit_put_string(), dinit_val(), dinits(), direct_rou_load(), do_access(), do_common_blocks(), do_copyin(), do_copyprivate(), do_distbegin(), do_equiv(), do_lastprivate(), do_nested_uses(), do_openmp_atomics(), do_parbegin(), do_save(), do_schedule(), do_sequence(), do_simdbegin(), dodef(), doerror(), doincl(), dowarning(), e74_arg(), e74_cnt(), emit_bpar(), emit_btarget(), end_module(), end_subprogram_checks(), end_workshare(), enqueueTbp(), enter_dir(), equivalence(), err307(), err_protected(), eval(), eval_init_op(), eval_ishft(), eval_mod(), eval_scale(), eval_sqrt(), eval_ul_bound(), exp_end_atomic(), exp_misc(), exp_mp_atomic_capture(), exp_mp_atomic_update(), export_all(), extract_shape_from_args(), extractor(), extractor_end(), ff_check_stmtb(), ff_get_label(), ff_get_noncomment(), ff_get_stmt(), ff_prescan(), ff_read_card(), find_base(), find_pointer_variable_assign(), find_reduc_intrinsic(), fix_args(), fix_module_common(), fixup_function_return_type(), fixup_param_vars(), forall_semantic(), fpp(), func_call2(), gen_alloc_dealloc(), gen_dinit(), gen_kind_parm_assignments(), generate_type_mismatch_errors(), get_ag(), get_atomic_function_ex(), get_atomic_update_opcode(), get_derived_type(), get_exttype_struct_constructor(), get_iftype(), get_implementation(), get_keyword_args(), get_keyword_components(), get_kind_id(), get_kind_value(), get_mp_bind_type(), get_number(), get_prefixed_int(), get_retval_derived_type(), get_stmt(), get_struct_from_dsrt2(), get_tbp_argno(), getict(), getivl(), ground(), ill_char(), import(), import_header_only(), import_module_print(), import_skip_use_stmts(), import_use_stmts(), increase_shape(), inheritTbps(), init(), init_newargs(), initFinalSub(), inline_func(), inline_shifts(), is_atomic_update_intr(), is_intrinsic_opr(), is_pcalls(), is_valid_atomic_capture(), is_valid_atomic_update(), leave_dir(), line_directive(), link_members(), live_var_end(), live_var_init(), lower(), lower_data_stmts(), lower_ilm_header(), lower_pop(), main(), matmul(), misc_checks(), mk_array_type(), mk_atomic_update_binop(), mk_atomic_update_intr(), mk_reshape_intrin(), mk_size_intrin(), mk_ulbound_intrin(), mkarg(), mkeffadr(), mkexpr1(), mklvalue(), mkvarref(), mod_fini(), mod_type(), move_alloc_arg(), mp_sched_to_kmpc_sched(), mr_get_rgset(), new(), new_ast(), new_storeitem(), newbas(), newimplicit(), newsym(), nml_check_item(), non_private_check(), open_module(), pntset(), private_check(), process_dsrt(), ptrfunc_call(), ptrsubr_call(), push_include(), put_astfil(), put_data_statement(), put_include(), put_kind_type_param(), put_lineno(), queue_type_param(), rdgram(), read_card(), readln(), realloc_stmtb(), record_func_result(), reduc_rank_dtype(), reduc_shape(), ref_array(), ref_int_scalar(), ref_intrin(), ref_intrin_subr(), ref_pd(), ref_pd_subr(), ref_stfunc(), refsym_inscope(), reloc_byvalue_parameters(), reorder_args(), resolve_defined_io(), resolve_generic(), resolveGeneric(), resolveImp(), resolvePass(), Restore_Chartab(), RestoreGilms(), rewrite_block_where(), rewrite_func_ast(), rewrite_into_forall(), Save_Chartab(), SaveGilms(), scan(), scan_include(), scan_init(), scan_options(), sched_type(), select_kind(), sem_err104(), sem_import_sym(), sem_set_storage_class(), semant1(), semant2(), semant3(), semantio(), semCheckTbp(), semfin(), semsmp(), set_iftype(), setConval(), setup_procedure_sym(), size_of_sym(), size_of_var(), subr_call2(), subst(), sum_scatter_args(), sym_in_scope(), symatterr(), symini_error(), tokmac(), transform_associated(), transform_call(), transform_ptr(), truncation_warning(), uninit_var_init(), update_stl(), use_before_def(), valid_assign_pointer_types(), validate_atomic_expr(), validate_omp_atomic(), wrilms(), and zprntk().
footer()
static void footer () static
Definition at line 216 of file prodstr.c.
References outfile, and prodfile.
Referenced by main().
header()
static void header () static
Definition at line 200 of file prodstr.c.
References outfile, and prodfile.
Referenced by eliminate_rt(), emit_copy_section(), emit_gatherx(), emit_overlap(), emit_permute_section(), emit_scatterx_gatherx(), forall_dependency(), insert_forall_comm(), is_in_block(), is_use_lhs_final(), main(), make_sec_ast(), scalar_communication(), temp_copy_section(), and temp_gatherx().
init()
static void init (void) static
Definition at line 226 of file prodstr.c.
References c, case_name, current, i, name, outfile, p, and q.
Referenced by main().
main()
int main ()
Definition at line 44 of file prodstr.c.
References bcnt, curchr, current, error(), fclose(), footer(), fstchr, header(), i, infile, init(), linbuf, lineno, name, NULL, outfile, output(), prodfile, readln(), scan(), tok, TOK_BREAK, TOK_EOF, TOK_EOLN, TOK_EQUAL, TOK_ID, tok_name, and TOK_OR.
output()
static void output () static
Definition at line 283 of file prodstr.c.
References case_name, current, i, name, outfile, prodfile, and savelin.
Referenced by flushsym(), fndnul(), main(), tablea(), tableu(), and xref().
readln()
static void readln (void) static
Definition at line 116 of file prodstr.c.
References curchr, infile, linbuf, lineno, NULL, savelin, and strlen().
Referenced by main(), and scan().
scan()
static int scan () static
Definition at line 132 of file prodstr.c.
References c, curchr, error(), fstchr, linbuf, readln(), TOK_BREAK, TOK_EOF, TOK_EOLN, TOK_EQUAL, TOK_ID, TOK_OR, TOK_OTHER, and token.
Referenced by main().
Variable Documentation
bcnt
int bcnt = 2 static
Definition at line 22 of file prodstr.c.
Referenced by main().
case_name
char case_name[60] static
Definition at line 16 of file prodstr.c.
Referenced by init(), and output().
curchr
int curchr static
Definition at line 19 of file prodstr.c.
Referenced by main(), readln(), and scan().
current
int current static
Definition at line 20 of file prodstr.c.
Referenced by init(), main(), and output().
fstchr
int fstchr static
Definition at line 19 of file prodstr.c.
Referenced by main(), and scan().
infile
FILE* infile static
Definition at line 17 of file prodstr.c.
Referenced by main(), and readln().
linbuf
char linbuf[121] static
Definition at line 13 of file prodstr.c.
Referenced by main(), readln(), and scan().
lineno
int lineno static
Definition at line 19 of file prodstr.c.
Referenced by error(), main(), and readln().
name
char name[60] static
Definition at line 15 of file prodstr.c.
Referenced by init(), main(), and output().
outfile
FILE * outfile static
Definition at line 17 of file prodstr.c.
Referenced by footer(), header(), init(), main(), and output().
prodfile
FILE * prodfile static
Definition at line 17 of file prodstr.c.
Referenced by footer(), header(), main(), and output().
savelin
char savelin[121] static
Definition at line 14 of file prodstr.c.
Referenced by output(), and readln().
tok_name
const char* tok_name[] static
Initial value:
= {"id",  "equal", "or",   "eoln",
                                 "eof", "break", "other"}
Definition at line 40 of file prodstr.c.
Referenced by main().