flang: prstab1.c File Reference
prstab1.c File Reference
LR parser (part 1)
#include "lrutils.h"
#include "prstab.h"
Macros
#define stack (scrtch)
#define cnectd (scrtch + MAXSHDP1)
#define FILES_CLOSE(f)
#define hdg ((INT *)&equiv_128)
Functions
int main (INT argc, char **argv)
INT addbas (INT iptr, INT npr, INT ndot, INT nset)
INT additl (INT *iarg, INT *lptr, INT *ichnge)
INT addltl (INT *lptr1, INT *lptr2, INT *ichnge)
INT addred (INT *ibasis, INT *iprod, INT *icntxt, INT *maxr)
INT addtrn (INT *ibasis, INT *itran, INT *imax)
INT analyz (void)
INT bildhp (void)
INT chncsl (void)
INT chrcmp (INT *iptr1, INT *iptr2, INT *irslt)
INT complt (INT *istate, INT *maxset)
INT condec (INT number, INT *line, INT istart, INT iend)
INT conect (void)
INT copyl (INT *lptr1, INT *lptr2)
INT csun (INT *iptr1, INT *iptr2, INT *ich)
INT delcs (INT *iptr)
INT deque (INT *iptr)
INT endbas (INT *iptr)
INT endred (INT *ibasis)
INT endtrn (INT *ibasis)
INT enque (INT *iptr)
INT enter (INT *buff, INT *len)
void intArrayToCharArray (INT *intarr, CHAR *charr, INT count)
INT error (const char *msg, INT msglen, INT ibad, INT sym, INT alias)
INT finish (void)
Write summary line to terminal, and exit compiler.
INT fndgol (void)
INT fndnul (void)
Variables
INT xargc
char ** xargv
struct files_s files
INT * scrtch
INT * hashpt
CHAR * linech
char * filnambuf
struct s4_s s4
struct s1_1_s s1_1
struct lstcom_s lstcom
struct qcom_s qcom
struct switches_s switches
struct adqcom_s adqcom
struct g_1_s g_1
struct s_1_s s_1
struct string_1_s string_1
struct readcm_s readcm
struct ptsem_s ptsem
Detailed Description
LR parser (part 1)
Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions. See https://llvm.org/LICENSE.txt for license information. SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
Definition in file prstab1.c.
Macro Definition Documentation
cnectd
#define cnectd (scrtch + MAXSHDP1)
FILES_CLOSE
#define FILES_CLOSE (f)
Value:
  if (files.f)         \
  (void) fclose(files.f)
hdg
#define hdg ((INT *)&equiv_128)
stack
#define stack (scrtch)
Function Documentation
addbas()
INT addbas (INT iptr, INT npr, INT ndot, INT nset)
Definition at line 106 of file prstab1.c.
References s_1_s::basis, error(), s_1_s::indbas, s4_s::item, MAXBAS, s4, and s_1.
Referenced by analyz(), and trnred().
additl()
INT additl (INT * iarg, INT * lptr, INT * ichnge)
Definition at line 121 of file prstab1.c.
References i, s4_s::item, last, s4_s::nextt, and s4.
Referenced by addltl(), and genthd().
addltl()
INT addltl (INT * lptr1, INT * lptr2, INT * ichnge)
Definition at line 156 of file prstab1.c.
References additl(), i, s4_s::item, s4_s::nextt, and s4.
Referenced by csun(), genthd(), and imtrcs().
addred()
INT addred (INT * ibasis, INT * iprod, INT * icntxt, INT * maxr)
Definition at line 178 of file prstab1.c.
References s_1_s::basis, error(), s4_s::item, j, s_1_s::red, s4, and s_1.
Referenced by trnred().
addtrn()
INT addtrn (INT * ibasis, INT * itran, INT * imax)
Definition at line 195 of file prstab1.c.
References s_1_s::basis, error(), i, s_1, and s_1_s::tran.
Referenced by trnred().
analyz()
INT analyz (void)
Definition at line 210 of file prstab1.c.
References addbas(), complt(), deque(), endbas(), fndnul(), g_1, genthd(), i, s4_s::item, n, newbas(), newcs(), g_1_s::nterms, g_1_s::prdind, g_1_s::prodcn, g_1_s::rgtuse, s4, sortcg(), and trnred().
Referenced by main().
bildhp()
INT bildhp (void)
Definition at line 240 of file prstab1.c.
References g_1, hepify(), i, j, and g_1_s::nvoc.
chncsl()
INT chncsl (void)
Definition at line 255 of file prstab1.c.
References error(), g_1, i, s4_s::item, last, s_1_s::lencsl, lenlst(), s_1_s::listcs, s_1_s::lsets, s_1_s::ncsets, s4_s::nextt, g_1_s::nterms, rel(), g_1_s::rgtuse, s4, and s_1.
Referenced by main().
chrcmp()
INT chrcmp (INT * iptr1, INT * iptr2, INT * irslt)
Definition at line 313 of file prstab1.c.
References s1_1, and s1_1_s::sstore.
Referenced by strcomp().
complt()
INT complt (INT * istate, INT * maxset)
Definition at line 332 of file prstab1.c.
References s_1_s::basis, csun(), delcs(), error(), g_1_s::frsprd, g_1, i, imtrcs(), s4_s::item, j, k, lhs, mark(), MAXPROD, g_1_s::nprods, g_1_s::nterms, g_1_s::numprd, g_1_s::prdind, g_1_s::prodcn, s4, s_1, and scrtch.
Referenced by analyz().
condec()
INT condec (INT number, INT * line, INT istart, INT iend)
Definition at line 445 of file prstab1.c.
References i, j, line, m, and n.
Referenced by gentab(), hlddmp(), pntbas(), pntset(), prntgm(), tablea(), tableu(), and xref().
conect()
INT conect (void)
Definition at line 499 of file prstab1.c.
References cnectd, error(), g_1_s::frsprd, g_1, i, j, g_1_s::nprods, g_1_s::nterms, g_1_s::nvoc, g_1_s::prdind, g_1_s::prodcn, stack, and g_1_s::vocab.
Referenced by main().
copyl()
INT copyl (INT * lptr1, INT * lptr2)
Definition at line 561 of file prstab1.c.
References i, s4_s::item, last, s4_s::nextt, and s4.
Referenced by csun(), and imtrcs().
csun()
INT csun (INT * iptr1, INT * iptr2, INT * ich)
Definition at line 588 of file prstab1.c.
References addltl(), copyl(), delcs(), newcs(), s4_s::nextt, and s4.
Referenced by complt(), and merge().
delcs()
INT delcs (INT * iptr)
Definition at line 605 of file prstab1.c.
References g_1, i, s4_s::item, last, s4_s::nextt, rel(), g_1_s::rgtuse, and s4.
Referenced by complt(), csun(), merge(), pntset(), and trnred().
deque()
INT deque (INT * iptr)
Definition at line 646 of file prstab1.c.
References s_1_s::basis, qcom, qcom_s::qhead, and s_1.
Referenced by analyz().
endbas()
INT endbas (INT * iptr)
Definition at line 659 of file prstab1.c.
References s_1_s::basis, error(), i, s_1_s::indbas, MAXBAS, and s_1.
Referenced by analyz(), and trnred().
endred()
INT endred (INT * ibasis)
Definition at line 674 of file prstab1.c.
References s_1_s::basis, i, if(), j, s_1_s::nxtred, and s_1.
Referenced by trnred().
endtrn()
INT endtrn (INT * ibasis)
Definition at line 687 of file prstab1.c.
References s_1_s::basis, i, j, s_1_s::nxttrn, and s_1.
Referenced by trnred().
enque()
INT enque (INT * iptr)
Definition at line 700 of file prstab1.c.
References s_1_s::basis, qcom, qcom_s::qhead, qcom_s::qtail, and s_1.
enter()
INT enter (INT * buff, INT * len)
Definition at line 717 of file prstab1.c.
References buff, switches_s::dbgesw, files_s::dbgfil, error(), files, g_1, hashof(), hashpt, i, j, k, len, MAXHASH, MAXSHD, MAXSST, s1_1, s1toa1(), string_1_s::shdptr, s1_1_s::sstore, string_1_s::sstptr, s1_1_s::sthead, strcomp(), string_1, switches, g_1_s::vocab, and wtline().
Referenced by scan().
error()
INT error (const char * msg, INT msglen, INT ibad, INT sym, INT alias)
Definition at line 793 of file prstab1.c.
References a1tos1(), a4tos1(), files_s::dbgfil, switches_s::dbgsw, DECL_LINE, files, finish(), readcm_s::fstchr, i32tos(), intArrayToCharArray(), line, linech, readcm_s::lineno, switches_s::listsw, files_s::lstfil, min, movstr(), msg(), readcm, switches, and wtline().
Referenced by addbas(), addred(), addtrn(), chncsl(), complt(), conect(), endbas(), enter(), and fndgol().
finish()
INT finish (void)
Write summary line to terminal, and exit compiler.
...
Definition at line 856 of file prstab1.c.
References s_1_s::basis, exitf(), FILES_CLOSE, g_1_s::frsprd, g_1, hashpt, s4_s::item, g_1_s::lftuse, s4_s::nextt, g_1_s::nprods, s_1_s::nullnt, g_1_s::prdind, g_1_s::prodcn, s_1_s::red, g_1_s::rgtuse, s1_1, s4, s_1, scrtch, s1_1_s::sstore, s1_1_s::sthead, s_1_s::thedpt, s_1_s::tran, and g_1_s::vocab.
Referenced by error(), and main().
fndgol()
INT fndgol (void)
Definition at line 893 of file prstab1.c.
References error(), g_1, g_1_s::goal, i, g_1_s::lftuse, g_1_s::nvoc, g_1_s::prdind, g_1_s::prodcn, and g_1_s::rgtuse.
Referenced by main().
fndnul()
INT fndnul (void)
Definition at line 922 of file prstab1.c.
References switches_s::dbgcsw, files_s::dbgfil, DECL_LINE, files, g_1_s::frsprd, g_1, hdg, i, j, k, length(), line, MAXSHD, movstr(), g_1_s::nprods, g_1_s::nterms, s_1_s::nullnt, g_1_s::nvoc, output(), g_1_s::prdind, g_1_s::prodcn, s_1, switches, and g_1_s::vocab.
Referenced by analyz().
intArrayToCharArray()
void intArrayToCharArray (INT * intarr, CHAR * charr, INT count)
Definition at line 783 of file prstab1.c.
References count, and i.
Referenced by error(), and formatFilename().
main()
int main (INT argc, char ** argv)
Definition at line 50 of file prstab1.c.
References analyz(), chncsl(), conect(), switches_s::datasw, switches_s::dbgdsw, finish(), fndgol(), gentab(), ground(), init(), switches_s::listsw, switches_s::lrltsw, pntset(), prntgm(), rdgram(), sortgm(), switches, tablea(), tableu(), tokmac(), switches_s::toksw, xargc, xargv, xref(), switches_s::xrefsw, and zprntk().
Variable Documentation
adqcom
struct adqcom_s adqcom
Definition at line 37 of file prstab1.c.
Referenced by init(), and pntset().
files
struct files_s files
Definition at line 20 of file prstab1.c.
Referenced by enter(), error(), fndnul(), gentab(), genthd(), hlddmp(), init(), pntbas(), pntset(), prntgm(), putsem(), readln(), tablea(), tableu(), tokmac(), and xref().
filnambuf
char* filnambuf
Definition at line 25 of file prstab1.c.
Referenced by formatFilename(), and init().
g_1
struct g_1_s g_1
Definition at line 39 of file prstab1.c.
Referenced by analyz(), bildhp(), chncsl(), complt(), conect(), delcs(), enter(), finish(), fndgol(), fndnul(), gentab(), genthd(), ground(), hepify(), imtrcs(), init(), less(), merge(), newcs(), pntbas(), pntset(), prntgm(), putsem(), rdgram(), sortcg(), sortgm(), tablea(), tableu(), tokmac(), trnred(), xref(), and zprntk().
hashpt
INT* hashpt
Definition at line 23 of file prstab1.c.
Referenced by enter(), finish(), and init().
linech
CHAR* linech
Definition at line 24 of file prstab1.c.
Referenced by error(), formatFilename(), and init().
lstcom
struct lstcom_s lstcom
Definition at line 31 of file prstab1.c.
Referenced by init(), new(), rel(), and tableu().
ptsem
struct ptsem_s ptsem
Definition at line 47 of file prstab1.c.
Referenced by init(), putsem(), and readln().
qcom
struct qcom_s qcom
Definition at line 33 of file prstab1.c.
Referenced by deque(), enque(), and init().
readcm
struct readcm_s readcm
Definition at line 45 of file prstab1.c.
Referenced by error(), init(), readln(), scan(), and tokmac().
s1_1
struct s1_1_s s1_1
Definition at line 29 of file prstab1.c.
Referenced by chrcmp(), enter(), finish(), hashof(), init(), length(), movstr(), strcomp(), and zprntk().
s4
struct s4_s s4
Definition at line 27 of file prstab1.c.
Referenced by __erf(), __erfc(), addbas(), additl(), addltl(), addred(), analyz(), chncsl(), complt(), copyl(), csun(), delcs(), finish(), gentab(), genthd(), imtrcs(), init(), lcompr(), lenlst(), lint(), merge(), new(), newcs(), pntbas(), pntset(), rel(), tablea(), tableu(), and xref().
s_1
struct s_1_s s_1
Definition at line 41 of file prstab1.c.
Referenced by addbas(), addred(), addtrn(), chncsl(), complt(), deque(), endbas(), endred(), endtrn(), enque(), finish(), fndnul(), gentab(), genthd(), imtrcs(), init(), merge(), newbas(), newred(), newtrn(), pntset(), tablea(), and tableu().
scrtch
INT* scrtch
Definition at line 22 of file prstab1.c.
Referenced by complt(), finish(), imtrcs(), init(), sortcg(), and trnred().
string_1
struct string_1_s string_1
Definition at line 43 of file prstab1.c.
Referenced by enter(), init(), and rdgram().
switches
struct switches_s switches
Definition at line 35 of file prstab1.c.
Referenced by enter(), error(), fndnul(), genthd(), init(), main(), pntset(), prntgm(), rdgram(), and xref().
xargc
INT xargc
Definition at line 15 of file prstab1.c.
Referenced by getarg(), iargc(), and main().
xargv
char** xargv
Definition at line 16 of file prstab1.c.
Referenced by getarg(), and main().