flang: prstab4.c File Reference
prstab4.c File Reference
LR parser (part 4)
#include "lrutils.h"
#include "prstab.h"
Functions
INT zprntk (void)
Detailed Description
LR parser (part 4)
Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions. See https://llvm.org/LICENSE.txt for license information. SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
Definition in file prstab4.c.
Function Documentation
zprntk()
INT zprntk (void)
Definition at line 16 of file prstab4.c.
References a4tos1(), DECL_LINE, error(), fclose(), FILE, g_1, i, i32tos(), j, line, g_1_s::nterms, g_1_s::nvoc, s1_1, s1_1_s::sstore, s1_1_s::sthead, g_1_s::vocab, and wtline().
Referenced by main().