flang: prstab3.c File Reference
prstab3.c File Reference
LR parser (part 3)
#include "lrutils.h"
#include "prstab.h"
Macros
#define moved (scrtch + 2000)
#define xlate (scrtch)
#define xlate (scrtch)
#define TK_LINESZ 50
#define lsthed (scrtch)
Functions
INT rdgram (void)
INT readln (void)
INT rel (INT *iptr)
INT scan (INT *token)
INT sortcg (INT *nsets)
INT sortgm (void)
INT strcomp (INT *iptr1, INT *iptr2, INT *irslt)
INT tablea (void)
INT tableu (void)
INT tokmac (void)
INT trnred (INT *ibasis, INT *jmax)
INT xref (void)
...
Detailed Description
LR parser (part 3)
Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions. See https://llvm.org/LICENSE.txt for license information. SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
Definition in file prstab3.c.
Macro Definition Documentation
lsthed
#define lsthed (scrtch)
moved
#define moved (scrtch + 2000)
TK_LINESZ
#define TK_LINESZ 50
xlate [1/2]
#define xlate (scrtch)
xlate [2/2]
#define xlate (scrtch)
Function Documentation
rdgram()
INT rdgram (void)
Definition at line 16 of file prstab3.c.
References error(), g_1_s::frsprd, g_1, i, k, g_1_s::lftuse, MAXPRDC, MAXPROD, g_1_s::nprods, g_1_s::nterms, g_1_s::numprd, g_1_s::nvoc, g_1_s::prdind, g_1_s::prodcn, putsem(), g_1_s::rgtuse, scan(), switches_s::semsw, string_1_s::shdptr, string_1, switches, and token.
readln()
INT readln (void)
Definition at line 114 of file prstab3.c.
References ptsem_s::brkflg, readcm_s::curchr, error(), files, files_s::infile, readcm_s::linbuf, readcm_s::lineno, ptsem, rdline(), and readcm.
Referenced by scan(), and tokmac().
rel()
INT rel (INT * iptr)
Definition at line 169 of file prstab3.c.
References lstcom_s::garbag, s4_s::item, lstcom, s4_s::nextt, and s4.
Referenced by chncsl(), cmp_to_log(), delcs(), genthd(), newcs(), pntset(), and xref().
scan()
INT scan (INT * token)
Definition at line 178 of file prstab3.c.
References c, readcm_s::curchr, enter(), error(), readcm_s::fstchr, readcm_s::linbuf, readcm, readln(), and token.
Referenced by rdgram(), and tokmac().
sortcg()
INT sortcg (INT * nsets)
Definition at line 282 of file prstab3.c.
References g_1, i, itemp, j, k, g_1_s::prdind, g_1_s::prodcn, and scrtch.
Referenced by analyz().
sortgm()
INT sortgm (void)
Definition at line 334 of file prstab3.c.
References bildhp(), g_1_s::frsprd, g_1, g_1_s::goal, hepify(), i, itemp, j, k, m2, moved, n1, n2, g_1_s::nprods, g_1_s::numprd, g_1_s::nvoc, g_1_s::prodcn, g_1_s::vocab, and xlate.
strcomp()
INT strcomp (INT * iptr1, INT * iptr2, INT * irslt)
Definition at line 417 of file prstab3.c.
References chrcmp(), i, s1_1, and s1_1_s::sthead.
Referenced by enter(), and less().
tablea()
INT tablea (void)
Definition at line 459 of file prstab3.c.
References a4tos1(), s_1_s::basis, condec(), files_s::datfil, DECL_LINE, files, g_1, i, i32tos(), i4, s_1_s::ifinal, s4_s::item, j, k, last, s_1_s::lencsl, length(), line, s_1_s::listcs, s_1_s::lsets, max, s_1_s::ncsets, s4_s::nextt, s_1_s::nstate, g_1_s::nterms, g_1_s::numprd, g_1_s::nvoc, s_1_s::nxtred, s_1_s::nxttrn, output(), g_1_s::prdind, g_1_s::prodcn, s_1_s::red, s4, s_1, s_1_s::tran, g_1_s::vocab, and wtline().
tableu()
INT tableu (void)
Definition at line 988 of file prstab3.c.
References s_1_s::basis, condec(), files_s::dbgfil, DECL_LINE, files, g_1, hlddmp(), i, s_1_s::ifinal, s4_s::item, j, k, s_1_s::lencsl, length(), line, s_1_s::listcs, lstcom, lstcom_s::lstptr, max, min, movstr(), s_1_s::ncsets, s4_s::nextt, s_1_s::nstate, g_1_s::nterms, g_1_s::numprd, g_1_s::nvoc, s_1_s::nxtred, s_1_s::nxttrn, output(), g_1_s::prdind, g_1_s::prodcn, s_1_s::red, s4, s_1, s_1_s::tran, and g_1_s::vocab.
tokmac()
INT tokmac (void)
Definition at line 1282 of file prstab3.c.
References a4tos1(), readcm_s::curchr, DECL_LINE, error(), files, g_1, i, i32tos(), files_s::infile, g_1_s::lftuse, readcm_s::linbuf, line, readcm_s::lineno, g_1_s::nterms, g_1_s::nvoc, readcm, readln(), scan(), TK_LINESZ, files_s::tokin, files_s::tokout, wtline(), and xlate.
trnred()
INT trnred (INT * ibasis, INT * jmax)
Definition at line 1364 of file prstab3.c.
References addbas(), addred(), addtrn(), delcs(), endbas(), endred(), endtrn(), enque(), g_1, i, lhs, merge(), newbas(), newred(), newtrn(), g_1_s::prdind, g_1_s::prodcn, and scrtch.
Referenced by analyz().
xref()
INT xref (void)
...
Definition at line 1423 of file prstab3.c.
References a4tos1(), condec(), DECL_LINE, files, g_1, i, s4_s::item, j, k, line, files_s::lstfil, lsthed, movstr(), n, s4_s::nextt, g_1_s::numprd, g_1_s::nvoc, output(), g_1_s::prdind, g_1_s::prodcn, rel(), switches_s::runosw, s4, switches, g_1_s::vocab, wtline(), and wtpage().