flang: prstab.h File Reference
prstab.h File Reference
LR header files.
Classes
struct files_s
struct s4_s
struct s1_1_s
struct lstcom_s
struct qcom_s
struct switches_s
struct adqcom_s
struct g_1_s
struct s_1_s
struct string_1_s
struct readcm_s
struct ptsem_s
Macros
#define INT int
#define LOGICAL int
#define UINT unsigned int
#define FLOAT float
#define CHAR unsigned char
#define VOID void
#define min(a, b) ((a) <= (b) ? (a) : (b))
#define max(a, b) ((a) >= (b) ? (a) : (b))
#define SNPRINTF snprintf
#define MAXSHD 2000
#define MAXSHDP1 2001
#define MAXSHD2P1 4001
#define MAXSST 16000
#define MAXPRDC 10000
#define MAXPROD 4000
#define MAXLST 24000
#define MAXBAS 44000
#define MAXTRN 40000
#define MAXRED 10000
#define MAXSCR 6000
#define MAXHASH 2048
#define MAXLEN 1024
#define DECL_LINE(n) INT line[n]
Functions
INT enter (INT *buff, INT *len)
INT error (const char *msg, INT msglen, INT ibad, INT sym, INT alias)
INT fndnul (void)
INT bildhp (void)
INT finish (void)
Write summary line to terminal, and exit compiler.
INT endbas (INT *iptr)
INT complt (INT *istate, INT *maxset)
INT enque (INT *iptr)
INT deque (INT *iptr)
INT csun (INT *iptr1, INT *iptr2, INT *ich)
INT delcs (INT *iptr)
INT condec (INT number, INT *line, INT istart, INT iend)
INT additl (INT *iarg, INT *lptr, INT *ichnge)
INT addltl (INT *lptr1, INT *lptr2, INT *ichnge)
INT copyl (INT *lptr1, INT *lptr2)
INT chrcmp (INT *iptr1, INT *iptr2, INT *irslt)
INT addbas (INT iptr, INT npr, INT ndot, INT nset)
INT addtrn (INT *ibasis, INT *itran, INT *imax)
INT endtrn (INT *ibasis)
INT addred (INT *ibasis, INT *iprod, INT *icntxt, INT *maxr)
INT endred (INT *ibasis)
INT hashof (INT *i)
INT lenlst (INT *ihead)
INT length (INT *iptr)
INT log76 (INT *iarg)
INT lcompr (INT *iptr1, INT *iptr2)
INT movstr (INT iptr, INT *line, INT *istart, INT iend)
INT output (FILE *unit, INT *line, INT nchars)
INT new (INT *iptr)
INT newbas (INT *index)
INT newcs (INT *is, INT *iptr)
INT genthd (void)
INT hepify (INT iptr, INT imax)
INT imtrcs (INT *ibasis, INT *iptr)
INT putsem (INT curlhs, INT *curprd)
INT hlddmp (INT *hold, INT *hldidx)
INT newtrn (INT *ibasis, INT *imax)
INT merge (INT *ibasis, INT *ires, INT *ichng)
INT newred (INT *ibasis, INT *imax)
INT less (INT *iptr1, INT *iptr2)
INT strcomp (INT *iptr1, INT *iptr2, INT *irslt)
INT sortcg (INT *nsets)
INT trnred (INT *ibasis, INT *jmax)
INT rel (INT *iptr)
INT scan (INT *token)
INT init (void)
INT xref (void)
...
INT tablea (void)
INT gentab (void)
INT rdgram (void)
INT fndgol (void)
INT tokmac (void)
INT conect (void)
INT chncsl (void)
INT tableu (void)
INT ground (void)
INT analyz (void)
INT prntgm (void)
INT sortgm (void)
INT pntset (void)
INT zprntk (void)
void intArrayToCharArray (INT *intarr, CHAR *charr, INT count)
Variables
struct files_s files
INT * scrtch
INT * hashpt
CHAR * linech
char * filnambuf
struct s4_s s4
struct s1_1_s s1_1
struct lstcom_s lstcom
struct qcom_s qcom
struct switches_s switches
struct adqcom_s adqcom
struct g_1_s g_1
struct s_1_s s_1
struct string_1_s string_1
struct readcm_s readcm
struct ptsem_s ptsem
Detailed Description
LR header files.
Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions. See https://llvm.org/LICENSE.txt for license information. SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
  This file declares all constants and varaiables global to all
  LR (prstab) routines, also contains all the routine declarations.
Definition in file prstab.h.
Macro Definition Documentation
CHAR
#define CHAR unsigned char
Definition at line 22 of file prstab.h.
DECL_LINE
#define DECL_LINE (n) INT line[n]
Definition at line 176 of file prstab.h.
FLOAT
#define FLOAT float
Definition at line 21 of file prstab.h.
INT
#define INT int
Definition at line 18 of file prstab.h.
LOGICAL
#define LOGICAL int
Definition at line 19 of file prstab.h.
max
#define max (a, b) ((a) >= (b) ? (a) : (b))
Definition at line 29 of file prstab.h.
MAXBAS
#define MAXBAS 44000
Definition at line 44 of file prstab.h.
MAXHASH
#define MAXHASH 2048
Definition at line 48 of file prstab.h.
MAXLEN
#define MAXLEN 1024
Definition at line 49 of file prstab.h.
MAXLST
#define MAXLST 24000
Definition at line 43 of file prstab.h.
MAXPRDC
#define MAXPRDC 10000
Definition at line 41 of file prstab.h.
MAXPROD
#define MAXPROD 4000
Definition at line 42 of file prstab.h.
MAXRED
#define MAXRED 10000
Definition at line 46 of file prstab.h.
MAXSCR
#define MAXSCR 6000
Definition at line 47 of file prstab.h.
MAXSHD
#define MAXSHD 2000
Definition at line 37 of file prstab.h.
MAXSHD2P1
#define MAXSHD2P1 4001
Definition at line 39 of file prstab.h.
MAXSHDP1
#define MAXSHDP1 2001
Definition at line 38 of file prstab.h.
MAXSST
#define MAXSST 16000
Definition at line 40 of file prstab.h.
MAXTRN
#define MAXTRN 40000
Definition at line 45 of file prstab.h.
min
#define min (a, b) ((a) <= (b) ? (a) : (b))
Definition at line 28 of file prstab.h.
SNPRINTF
#define SNPRINTF snprintf
Definition at line 34 of file prstab.h.
UINT
#define UINT unsigned int
Definition at line 20 of file prstab.h.
VOID
#define VOID void
Definition at line 24 of file prstab.h.
Function Documentation
addbas()
INT addbas (INT iptr, INT npr, INT ndot, INT nset)
Definition at line 106 of file prstab1.c.
References s_1_s::basis, error(), s_1_s::indbas, s4_s::item, MAXBAS, s4, and s_1.
Referenced by analyz(), and trnred().
additl()
INT additl (INT * iarg, INT * lptr, INT * ichnge)
Definition at line 121 of file prstab1.c.
References i, s4_s::item, last, s4_s::nextt, and s4.
Referenced by addltl(), and genthd().
addltl()
INT addltl (INT * lptr1, INT * lptr2, INT * ichnge)
Definition at line 156 of file prstab1.c.
References additl(), i, s4_s::item, s4_s::nextt, and s4.
Referenced by csun(), genthd(), and imtrcs().
addred()
INT addred (INT * ibasis, INT * iprod, INT * icntxt, INT * maxr)
Definition at line 178 of file prstab1.c.
References s_1_s::basis, error(), s4_s::item, j, s_1_s::red, s4, and s_1.
Referenced by trnred().
addtrn()
INT addtrn (INT * ibasis, INT * itran, INT * imax)
Definition at line 195 of file prstab1.c.
References s_1_s::basis, error(), i, s_1, and s_1_s::tran.
Referenced by trnred().
analyz()
INT analyz (void)
bildhp()
INT bildhp (void)
Referenced by sortgm().
chncsl()
INT chncsl (void)
chrcmp()
INT chrcmp (INT * iptr1, INT * iptr2, INT * irslt)
Definition at line 313 of file prstab1.c.
References s1_1, and s1_1_s::sstore.
Referenced by strcomp().
complt()
INT complt (INT * istate, INT * maxset)
Definition at line 332 of file prstab1.c.
References s_1_s::basis, csun(), delcs(), error(), g_1_s::frsprd, g_1, i, imtrcs(), s4_s::item, j, k, lhs, mark(), MAXPROD, g_1_s::nprods, g_1_s::nterms, g_1_s::numprd, g_1_s::prdind, g_1_s::prodcn, s4, s_1, and scrtch.
Referenced by analyz().
condec()
INT condec (INT number, INT * line, INT istart, INT iend)
Definition at line 445 of file prstab1.c.
References i, j, line, m, and n.
Referenced by gentab(), hlddmp(), pntbas(), pntset(), prntgm(), tablea(), tableu(), and xref().
conect()
INT conect (void)
copyl()
INT copyl (INT * lptr1, INT * lptr2)
Definition at line 561 of file prstab1.c.
References i, s4_s::item, last, s4_s::nextt, and s4.
Referenced by csun(), and imtrcs().
csun()
INT csun (INT * iptr1, INT * iptr2, INT * ich)
Definition at line 588 of file prstab1.c.
References addltl(), copyl(), delcs(), newcs(), s4_s::nextt, and s4.
Referenced by complt(), and merge().
delcs()
INT delcs (INT * iptr)
Definition at line 605 of file prstab1.c.
References g_1, i, s4_s::item, last, s4_s::nextt, rel(), g_1_s::rgtuse, and s4.
Referenced by complt(), csun(), merge(), pntset(), and trnred().
deque()
INT deque (INT * iptr)
Definition at line 646 of file prstab1.c.
References s_1_s::basis, qcom, qcom_s::qhead, and s_1.
Referenced by analyz().
endbas()
INT endbas (INT * iptr)
Definition at line 659 of file prstab1.c.
References s_1_s::basis, error(), i, s_1_s::indbas, MAXBAS, and s_1.
Referenced by analyz(), and trnred().
endred()
INT endred (INT * ibasis)
Definition at line 674 of file prstab1.c.
References s_1_s::basis, i, if(), j, s_1_s::nxtred, and s_1.
Referenced by trnred().
endtrn()
INT endtrn (INT * ibasis)
Definition at line 687 of file prstab1.c.
References s_1_s::basis, i, j, s_1_s::nxttrn, and s_1.
Referenced by trnred().
enque()
INT enque (INT * iptr)
Referenced by trnred().
enter()
INT enter (INT * buff, INT * len)
Definition at line 717 of file prstab1.c.
References buff, switches_s::dbgesw, files_s::dbgfil, error(), files, g_1, hashof(), hashpt, i, j, k, len, MAXHASH, MAXSHD, MAXSST, s1_1, s1toa1(), string_1_s::shdptr, s1_1_s::sstore, string_1_s::sstptr, s1_1_s::sthead, strcomp(), string_1, switches, g_1_s::vocab, and wtline().
Referenced by scan().
error()
INT error (const char * msg, INT msglen, INT ibad, INT sym, INT alias)
Definition at line 793 of file prstab1.c.
References a1tos1(), a4tos1(), files_s::dbgfil, switches_s::dbgsw, DECL_LINE, files, finish(), readcm_s::fstchr, i32tos(), intArrayToCharArray(), line, linech, readcm_s::lineno, switches_s::listsw, files_s::lstfil, min, movstr(), msg(), readcm, switches, and wtline().
Referenced by addbas(), addred(), addtrn(), chncsl(), complt(), conect(), endbas(), enter(), and fndgol().
finish()
INT finish (void)
Write summary line to terminal, and exit compiler.
...
Definition at line 144 of file main.c.
fndgol()
INT fndgol (void)
fndnul()
INT fndnul (void)
gentab()
INT gentab (void)
Referenced by main().
genthd()
INT genthd (void)
Definition at line 545 of file prstab2.c.
References additl(), addltl(), switches_s::dbgcsw, files_s::dbgfil, DECL_LINE, files, g_1, hdg, i, s4_s::item, j, k, lcompr(), length(), line, MAXSHD, movstr(), s4_s::nextt, g_1_s::nterms, s_1_s::nullnt, g_1_s::numprd, g_1_s::nvoc, output(), g_1_s::prdind, g_1_s::prodcn, rel(), reset, s4, s_1, switches, s_1_s::thedpt, and g_1_s::vocab.
Referenced by analyz().
ground()
INT ground (void)
Referenced by main().
hashof()
INT hashof (INT * i)
Definition at line 746 of file prstab2.c.
References itemp, MAXHASH, s1_1, s1_1_s::sstore, and s1_1_s::sthead.
Referenced by enter().
hepify()
INT hepify (INT iptr, INT imax)
Definition at line 764 of file prstab2.c.
References g_1, i, itemp, j, less(), and g_1_s::vocab.
Referenced by bildhp(), and sortgm().
hlddmp()
INT hlddmp (INT * hold, INT * hldidx)
Definition at line 797 of file prstab2.c.
References condec(), files_s::dbgfil, files, i, line, and output().
Referenced by tableu().
imtrcs()
INT imtrcs (INT * ibasis, INT * iptr)
Definition at line 818 of file prstab2.c.
References addltl(), copyl(), g_1, i, s4_s::item, newcs(), s4_s::nextt, s_1_s::nullnt, g_1_s::prdind, g_1_s::prodcn, s4, s_1, scrtch, and s_1_s::thedpt.
Referenced by complt().
init()
INT init (void)
intArrayToCharArray()
void intArrayToCharArray (INT * intarr, CHAR * charr, INT count)
Definition at line 783 of file prstab1.c.
References count, and i.
Referenced by error(), and formatFilename().
lcompr()
INT lcompr (INT * iptr1, INT * iptr2)
Definition at line 1183 of file prstab2.c.
References s4_s::item, s4_s::nextt, and s4.
Referenced by genthd(), and newcs().
length()
INT length (INT * iptr)
Definition at line 1211 of file prstab2.c.
References s1_1, and s1_1_s::sthead.
Referenced by __f90io_fmt_read(), __f90io_fmt_write(), __f90io_ldr(), __f90io_ldw(), __f90io_unf_read(), __fortio_trunc(), __INT_T(), assign(), basenam(), clen_parent_is_param(), dirnam(), ENTF90(), fndnul(), gentab(), genthd(), get_literal(), getstring(), installsym_ex(), local_sname(), lookupsym(), make_conststring_op(), mangle_name(), mangle_name_dt(), mkperm(), pntbas(), pntset(), prntgm(), putsname(), tablea(), tableu(), write_layout_desc(), and write_layout_desc_entry().
lenlst()
INT lenlst (INT * ihead)
Definition at line 1220 of file prstab2.c.
References s4_s::nextt, and s4.
Referenced by chncsl().
less()
INT less (INT * iptr1, INT * iptr2)
Definition at line 1239 of file prstab2.c.
References g_1, g_1_s::lftuse, and strcomp().
Referenced by hepify().
log76()
INT log76 (INT * iarg)
Definition at line 1287 of file prstab2.c.
Referenced by gentab().
merge()
INT merge (INT * ibasis, INT * ires, INT * ichng)
Definition at line 1311 of file prstab2.c.
References s_1_s::basis, csun(), delcs(), g_1, i, s_1_s::indbas, j, g_1_s::lftuse, lint(), s4_s::nextt, s_1_s::nstate, g_1_s::prdind, g_1_s::prodcn, s4, and s_1.
movstr()
INT movstr (INT iptr, INT * line, INT * istart, INT iend)
Definition at line 1418 of file prstab2.c.
References i, j, line, s1_1, s1_1_s::sstore, and s1_1_s::sthead.
Referenced by error(), fndnul(), gentab(), genthd(), pntbas(), pntset(), prntgm(), putsem(), tableu(), and xref().
new()
INT new (INT * iptr)
newbas()
INT newbas (INT * index)
Referenced by analyz(), and trnred().
newcs()
INT newcs (INT * is, INT * iptr)
Definition at line 1489 of file prstab2.c.
References g_1, i, s4_s::item, lcompr(), s4_s::nextt, rel(), g_1_s::rgtuse, and s4.
Referenced by analyz(), csun(), and imtrcs().
newred()
INT newred (INT * ibasis, INT * imax)
Definition at line 1520 of file prstab2.c.
References s_1_s::basis, i, MAXRED, s_1_s::nxtred, and s_1.
Referenced by trnred().
newtrn()
INT newtrn (INT * ibasis, INT * imax)
Definition at line 1541 of file prstab2.c.
References s_1_s::basis, i, MAXTRN, s_1_s::nxttrn, and s_1.
Referenced by trnred().
output()
INT output (FILE * unit, INT * line, INT nchars)
Definition at line 1562 of file prstab2.c.
References a1tos1(), i, line, and wtline().
Referenced by gentab(), genthd(), hlddmp(), pntbas(), pntset(), and prntgm().
pntset()
INT pntset (void)
Referenced by main().
prntgm()
INT prntgm (void)
Referenced by main().
putsem()
INT putsem (INT curlhs, INT * curprd)
Definition at line 1997 of file prstab2.c.
References a1tos1(), a4tos1(), ptsem_s::brkflg, c, DECL_LINE, files, g_1, i, i32tos(), line, movstr(), g_1_s::nprods, ptsem_s::pnum, ptsem, files_s::semfil, ptsem_s::semnum, SM_LINESZ, and wtline().
Referenced by rdgram().
rdgram()
INT rdgram (void)
Referenced by main().
rel()
INT rel (INT * iptr)
Definition at line 169 of file prstab3.c.
References lstcom_s::garbag, s4_s::item, lstcom, s4_s::nextt, and s4.
Referenced by chncsl(), cmp_to_log(), delcs(), genthd(), newcs(), pntset(), and xref().
scan()
INT scan (INT * token)
Definition at line 178 of file prstab3.c.
References c, readcm_s::curchr, enter(), error(), readcm_s::fstchr, readcm_s::linbuf, readcm, readln(), and token.
Referenced by rdgram(), and tokmac().
sortcg()
INT sortcg (INT * nsets)
Definition at line 282 of file prstab3.c.
References g_1, i, itemp, j, k, g_1_s::prdind, g_1_s::prodcn, and scrtch.
Referenced by analyz().
sortgm()
INT sortgm (void)
Referenced by main().
strcomp()
INT strcomp (INT * iptr1, INT * iptr2, INT * irslt)
Definition at line 417 of file prstab3.c.
References chrcmp(), i, s1_1, and s1_1_s::sthead.
Referenced by enter(), and less().
tablea()
INT tablea (void)
Referenced by main().
tableu()
INT tableu (void)
Referenced by main().
tokmac()
INT tokmac (void)
Referenced by main().
trnred()
INT trnred (INT * ibasis, INT * jmax)
Definition at line 1364 of file prstab3.c.
References addbas(), addred(), addtrn(), delcs(), endbas(), endred(), endtrn(), enque(), g_1, i, lhs, merge(), newbas(), newred(), newtrn(), g_1_s::prdind, g_1_s::prodcn, and scrtch.
Referenced by analyz().
xref()
INT xref (void)
...
Definition at line 1638 of file xref.c.
zprntk()
INT zprntk (void)
Definition at line 16 of file prstab4.c.
References a4tos1(), DECL_LINE, error(), fclose(), FILE, g_1, i, i32tos(), j, line, g_1_s::nterms, g_1_s::nvoc, s1_1, s1_1_s::sstore, s1_1_s::sthead, g_1_s::vocab, and wtline().
Referenced by main().
Variable Documentation
adqcom
struct adqcom_s adqcom extern
Definition at line 37 of file prstab1.c.
Referenced by init(), and pntset().
files
struct files_s files extern
Definition at line 20 of file prstab1.c.
Referenced by enter(), error(), fndnul(), gentab(), genthd(), hlddmp(), init(), pntbas(), pntset(), prntgm(), putsem(), readln(), tablea(), tableu(), tokmac(), and xref().
filnambuf
char* filnambuf extern
Definition at line 25 of file prstab1.c.
Referenced by formatFilename(), and init().
g_1
struct g_1_s g_1 extern
Definition at line 39 of file prstab1.c.
Referenced by analyz(), bildhp(), chncsl(), complt(), conect(), delcs(), enter(), finish(), fndgol(), fndnul(), gentab(), genthd(), ground(), hepify(), imtrcs(), init(), less(), merge(), newcs(), pntbas(), pntset(), prntgm(), putsem(), rdgram(), sortcg(), sortgm(), tablea(), tableu(), tokmac(), trnred(), xref(), and zprntk().
hashpt
INT* hashpt extern
Definition at line 23 of file prstab1.c.
Referenced by enter(), finish(), and init().
linech
CHAR* linech extern
Definition at line 24 of file prstab1.c.
Referenced by error(), formatFilename(), and init().
lstcom
struct lstcom_s lstcom extern
Definition at line 31 of file prstab1.c.
Referenced by init(), new(), rel(), and tableu().
ptsem
struct ptsem_s ptsem extern
Definition at line 47 of file prstab1.c.
Referenced by init(), putsem(), and readln().
qcom
struct qcom_s qcom extern
Definition at line 33 of file prstab1.c.
Referenced by deque(), enque(), and init().
readcm
struct readcm_s readcm extern
Definition at line 45 of file prstab1.c.
Referenced by error(), init(), readln(), scan(), and tokmac().
s1_1
struct s1_1_s s1_1 extern
Definition at line 29 of file prstab1.c.
Referenced by chrcmp(), enter(), finish(), hashof(), init(), length(), movstr(), strcomp(), and zprntk().
s4
struct s4_s s4 extern
Definition at line 27 of file prstab1.c.
Referenced by __erf(), __erfc(), addbas(), additl(), addltl(), addred(), analyz(), chncsl(), complt(), copyl(), csun(), delcs(), finish(), gentab(), genthd(), imtrcs(), init(), lcompr(), lenlst(), lint(), merge(), new(), newcs(), pntbas(), pntset(), rel(), tablea(), tableu(), and xref().
s_1
struct s_1_s s_1 extern
Definition at line 41 of file prstab1.c.
Referenced by addbas(), addred(), addtrn(), chncsl(), complt(), deque(), endbas(), endred(), endtrn(), enque(), finish(), fndnul(), gentab(), genthd(), imtrcs(), init(), merge(), newbas(), newred(), newtrn(), pntset(), tablea(), and tableu().
scrtch
INT* scrtch extern
Definition at line 22 of file prstab1.c.
Referenced by complt(), finish(), imtrcs(), init(), sortcg(), and trnred().
string_1
struct string_1_s string_1 extern
Definition at line 43 of file prstab1.c.
Referenced by enter(), init(), and rdgram().
switches
struct switches_s switches extern
Definition at line 35 of file prstab1.c.
Referenced by enter(), error(), fndnul(), genthd(), init(), main(), pntset(), prntgm(), rdgram(), and xref().