flang: prstab2.c File Reference
prstab2.c File Reference
LR parser (part 2)
#include "lrutils.h"
#include "prstab.h"
Macros
#define reset (scrtch + 199)
#define grnded scrtch
#define swtab scrtch
#define SM_LINESZ 50
Functions
INT gentab (void)
INT genthd (void)
INT ground (void)
INT hashof (INT *i__)
INT hepify (INT iptr, INT imax)
INT hlddmp (INT *hold, INT *hldidx)
INT imtrcs (INT *ibasis, INT *iptr)
void lowerFilename (CHAR *filename, INT len)
void formatFilename (INT *filename, INT len)
INT init (void)
INT lcompr (INT *iptr1, INT *iptr2)
INT length (INT *iptr)
INT lenlst (INT *ihead)
INT less (INT *iptr1, INT *iptr2)
INT lint (INT *iptr1, INT *iptr2)
INT log76 (INT *iarg)
INT merge (INT *ibasis, INT *ires, INT *ichng)
INT movstr (INT iptr, INT *line, INT *istart, INT iend)
INT new (INT *iptr)
INT newbas (INT *index)
INT newcs (INT *is, INT *iptr)
INT newred (INT *ibasis, INT *imax)
INT newtrn (INT *ibasis, INT *imax)
INT output (FILE *unit, INT *line, INT nchars)
INT pntbas (INT iprod, INT idot, INT iptr)
INT pntset (void)
INT prntgm (void)
INT putsem (INT curlhs, INT *curprd)
Detailed Description
LR parser (part 2)
Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions. See https://llvm.org/LICENSE.txt for license information. SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
Definition in file prstab2.c.
Macro Definition Documentation
grnded
#define grnded scrtch
reset
#define reset (scrtch + 199)
SM_LINESZ
#define SM_LINESZ 50
swtab
#define swtab scrtch
Function Documentation
formatFilename()
void formatFilename (INT * filename, INT len)
Definition at line 875 of file prstab2.c.
References CHAR, filename, filnambuf, intArrayToCharArray(), len, linech, lowerFilename(), and SNPRINTF.
Referenced by init().
gentab()
INT gentab (void)
Definition at line 16 of file prstab2.c.
References s_1_s::basis, condec(), files_s::dbgfil, DECL_LINE, files, g_1, i, s_1_s::ifinal, s4_s::item, itemp, j, k, length(), line, s_1_s::listcs, log76(), lv, movstr(), s_1_s::ncsets, s4_s::nextt, s_1_s::nstate, g_1_s::nterms, g_1_s::numprd, g_1_s::nvoc, s_1_s::nxtred, s_1_s::nxttrn, output(), g_1_s::prdind, g_1_s::prodcn, s_1_s::red, s4, s_1, s_1_s::tran, and g_1_s::vocab.
genthd()
INT genthd (void)
Definition at line 545 of file prstab2.c.
References additl(), addltl(), switches_s::dbgcsw, files_s::dbgfil, DECL_LINE, files, g_1, hdg, i, s4_s::item, j, k, lcompr(), length(), line, MAXSHD, movstr(), s4_s::nextt, g_1_s::nterms, s_1_s::nullnt, g_1_s::numprd, g_1_s::nvoc, output(), g_1_s::prdind, g_1_s::prodcn, rel(), reset, s4, s_1, switches, s_1_s::thedpt, and g_1_s::vocab.
Referenced by analyz().
ground()
INT ground (void)
Definition at line 668 of file prstab2.c.
References error(), g_1_s::frsprd, g_1, grnded, i, j, k, g_1_s::nprods, g_1_s::nterms, g_1_s::nvoc, g_1_s::prdind, g_1_s::prodcn, and g_1_s::vocab.
hashof()
INT hashof (INT * i__)
Definition at line 746 of file prstab2.c.
References itemp, MAXHASH, s1_1, s1_1_s::sstore, and s1_1_s::sthead.
Referenced by enter().
hepify()
INT hepify (INT iptr, INT imax)
Definition at line 764 of file prstab2.c.
References g_1, i, itemp, j, less(), and g_1_s::vocab.
Referenced by bildhp(), and sortgm().
hlddmp()
INT hlddmp (INT * hold, INT * hldidx)
Definition at line 797 of file prstab2.c.
References condec(), files_s::dbgfil, files, i, line, and output().
Referenced by tableu().
imtrcs()
INT imtrcs (INT * ibasis, INT * iptr)
Definition at line 818 of file prstab2.c.
References addltl(), copyl(), g_1, i, s4_s::item, newcs(), s4_s::nextt, s_1_s::nullnt, g_1_s::prdind, g_1_s::prodcn, s4, s_1, scrtch, and s_1_s::thedpt.
Referenced by complt().
init()
INT init (void)
Definition at line 884 of file prstab2.c.
References a4tos1(), adqcom_s::adequt, adqcom, s_1_s::basis, ptsem_s::brkflg, CHAR, cli(), readcm_s::curchr, switches_s::datasw, files_s::datfil, switches_s::dbgasw, switches_s::dbgbsw, switches_s::dbgcsw, switches_s::dbgdsw, switches_s::dbgesw, files_s::dbgfil, switches_s::dbgsw, error(), FALSE, files, filnambuf, formatFilename(), g_1_s::frsprd, g_1, lstcom_s::garbag, files_s::gramin, hashpt, i, s_1_s::indbas, files_s::infile, s4_s::item, len, g_1_s::lftuse, readcm_s::linbuf, linech, readcm_s::lineno, switches_s::listsw, switches_s::lrltsw, lstcom, files_s::lstfil, lstcom_s::lstptr, malloc(), MAXBAS, MAXHASH, MAXLEN, MAXLST, MAXPRDC, MAXPROD, MAXRED, MAXSCR, MAXSHD, MAXSHDP1, MAXSST, MAXTRN, s_1_s::ncsets, s4_s::nextt, g_1_s::nprods, s_1_s::nstate, s_1_s::nullnt, s_1_s::nxtred, s_1_s::nxttrn, ptsem_s::pnum, g_1_s::prdind, g_1_s::prodcn, ptsem, qcom, qcom_s::qhead, qcom_s::qtail, readcm, s_1_s::red, g_1_s::rgtuse, switches_s::runosw, s, s1_1, s4, s_1, scrtch, files_s::semfil, ptsem_s::semnum, switches_s::semsw, string_1_s::shdptr, s1_1_s::sstore, string_1_s::sstptr, s1_1_s::sthead, string_1, switches, swtab, s_1_s::thedpt, files_s::tokin, files_s::tokout, switches_s::toksw, s_1_s::tran, TRUE, g_1_s::vocab, and switches_s::xrefsw.
lcompr()
INT lcompr (INT * iptr1, INT * iptr2)
Definition at line 1183 of file prstab2.c.
References s4_s::item, s4_s::nextt, and s4.
Referenced by genthd(), and newcs().
length()
INT length (INT * iptr)
Definition at line 1211 of file prstab2.c.
References s1_1, and s1_1_s::sthead.
Referenced by __f90io_fmt_read(), __f90io_fmt_write(), __f90io_ldr(), __f90io_ldw(), __f90io_unf_read(), __fortio_trunc(), __INT_T(), assign(), basenam(), clen_parent_is_param(), dirnam(), ENTF90(), fndnul(), gentab(), genthd(), get_literal(), getstring(), installsym_ex(), local_sname(), lookupsym(), make_conststring_op(), mangle_name(), mangle_name_dt(), mkperm(), pntbas(), pntset(), prntgm(), putsname(), tablea(), tableu(), write_layout_desc(), and write_layout_desc_entry().
lenlst()
INT lenlst (INT * ihead)
Definition at line 1220 of file prstab2.c.
References s4_s::nextt, and s4.
Referenced by chncsl().
less()
INT less (INT * iptr1, INT * iptr2)
Definition at line 1239 of file prstab2.c.
References g_1, g_1_s::lftuse, and strcomp().
Referenced by hepify().
lint()
INT lint (INT * iptr1, INT * iptr2)
Definition at line 1260 of file prstab2.c.
References s4_s::item, s4_s::nextt, and s4.
Referenced by merge(), and pntset().
log76()
INT log76 (INT * iarg)
Definition at line 1287 of file prstab2.c.
Referenced by gentab().
lowerFilename()
void lowerFilename (CHAR * filename, INT len)
Definition at line 866 of file prstab2.c.
References filename, i, and len.
Referenced by formatFilename().
merge()
INT merge (INT * ibasis, INT * ires, INT * ichng)
Definition at line 1311 of file prstab2.c.
References s_1_s::basis, csun(), delcs(), g_1, i, s_1_s::indbas, j, g_1_s::lftuse, lint(), s4_s::nextt, s_1_s::nstate, g_1_s::prdind, g_1_s::prodcn, s4, and s_1.
movstr()
INT movstr (INT iptr, INT * line, INT * istart, INT iend)
Definition at line 1418 of file prstab2.c.
References i, j, line, s1_1, s1_1_s::sstore, and s1_1_s::sthead.
Referenced by error(), fndnul(), gentab(), genthd(), pntbas(), pntset(), prntgm(), putsem(), tableu(), and xref().
new()
INT new (INT * iptr)
Definition at line 1440 of file prstab2.c.
References error(), lstcom_s::garbag, s4_s::item, lstcom, lstcom_s::lstptr, MAXLST, s4_s::nextt, and s4.
newbas()
INT newbas (INT * index)
Definition at line 1473 of file prstab2.c.
References s_1_s::basis, error(), s_1_s::indbas, index, MAXBAS, s_1_s::nstate, and s_1.
newcs()
INT newcs (INT * is, INT * iptr)
Definition at line 1489 of file prstab2.c.
References g_1, i, s4_s::item, lcompr(), s4_s::nextt, rel(), g_1_s::rgtuse, and s4.
Referenced by analyz(), csun(), and imtrcs().
newred()
INT newred (INT * ibasis, INT * imax)
Definition at line 1520 of file prstab2.c.
References s_1_s::basis, i, MAXRED, s_1_s::nxtred, and s_1.
Referenced by trnred().
newtrn()
INT newtrn (INT * ibasis, INT * imax)
Definition at line 1541 of file prstab2.c.
References s_1_s::basis, i, MAXTRN, s_1_s::nxttrn, and s_1.
Referenced by trnred().
output()
INT output (FILE * unit, INT * line, INT nchars)
Definition at line 1562 of file prstab2.c.
References a1tos1(), i, line, and wtline().
Referenced by gentab(), genthd(), hlddmp(), pntbas(), pntset(), and prntgm().
pntbas()
INT pntbas (INT iprod, INT idot, INT iptr)
Definition at line 1581 of file prstab2.c.
References condec(), files_s::dbgfil, DECL_LINE, files, g_1, i, s4_s::item, j, length(), line, movstr(), s4_s::nextt, output(), g_1_s::prdind, g_1_s::prodcn, s4, and g_1_s::vocab.
Referenced by pntset().
pntset()
INT pntset (void)
Definition at line 1655 of file prstab2.c.
References adqcom_s::adequt, adqcom, s_1_s::basis, condec(), switches_s::dbgasw, files_s::dbgfil, DECL_LINE, delcs(), error(), files, g_1, i, s_1_s::ifinal, s4_s::item, itemp, j, k, length(), line, lint(), movstr(), n, s4_s::nextt, s_1_s::nstate, output(), pntbas(), g_1_s::prdind, g_1_s::prodcn, s_1_s::red, rel(), s4, s_1, switches, s_1_s::tran, and g_1_s::vocab.
prntgm()
INT prntgm (void)
Definition at line 1855 of file prstab2.c.
References a4tos1(), condec(), DECL_LINE, files, g_1, i, j, k, length(), lhs, line, files_s::lstfil, m, max, movstr(), g_1_s::nprods, g_1_s::nterms, g_1_s::numprd, g_1_s::nvoc, output(), g_1_s::prdind, g_1_s::prodcn, switches_s::runosw, switches, g_1_s::vocab, wtline(), and wtpage().
putsem()
INT putsem (INT curlhs, INT * curprd)
Definition at line 1997 of file prstab2.c.
References a1tos1(), a4tos1(), ptsem_s::brkflg, c, DECL_LINE, files, g_1, i, i32tos(), line, movstr(), g_1_s::nprods, ptsem_s::pnum, ptsem, files_s::semfil, ptsem_s::semnum, SM_LINESZ, and wtline().
Referenced by rdgram().