flang: pxpowi.c File Reference
pxpowi.c File Reference
#include "mth_intrinsics.h"
Functions
vrs4_t __px_powi1_4 (vrs4_t x, int32_t iy)
vrs4_t __px_powi1_4m (vrs4_t x, int32_t iy, vis4_t mask)
vrs4_t __px_powi_4 (vrs4_t x, vis4_t iy)
vrs4_t __px_powi_4m (vrs4_t x, vis4_t iy, vis4_t mask)
vrs4_t __px_powk1_4 (vrs4_t x, long long iy)
vrs4_t __px_powk1_4m (vrs4_t x, long long iy, vis4_t mask)
vrs4_t __px_powk_4 (vrs4_t x, vid2_t iyu, vid2_t iyl)
vrs4_t __px_powk_4m (vrs4_t x, vid2_t iyu, vid2_t iyl, vis4_t mask)
vrd2_t __px_powi1_2 (vrd2_t x, int32_t iy)
vrd2_t __px_powi1_2m (vrd2_t x, int32_t iy, vid2_t mask)
vrd2_t __px_powi_2 (vrd2_t x, vis4_t iy)
vrd2_t __px_powi_2m (vrd2_t x, vis4_t iy, vid2_t mask)
vrd2_t __px_powk1_2 (vrd2_t x, long long iy)
vrd2_t __px_powk1_2m (vrd2_t x, long long iy, vid2_t mask)
vrd2_t __px_powk_2 (vrd2_t x, vid2_t iy)
vrd2_t __px_powk_2m (vrd2_t x, vid2_t iy, vid2_t mask)
Function Documentation
__px_powi1_2()
vrd2_t __px_powi1_2 (vrd2_t x, int32_t iy)
Definition at line 59 of file pxpowi.c.
References __pmth_i_dpowi(), __ZGVxN2v__mth_i_vr8si4(), iy, and x.
__px_powi1_2m()
vrd2_t __px_powi1_2m (vrd2_t x, int32_t iy, vid2_t mask)
Definition at line 65 of file pxpowi.c.
References __pmth_i_dpowi(), __ZGVxM2v__mth_i_vr8si4(), iy, and x.
__px_powi1_4()
vrs4_t __px_powi1_4 (vrs4_t x, int32_t iy)
Definition at line 11 of file pxpowi.c.
References __pmth_i_rpowi(), __ZGVxN4v__mth_i_vr4si4(), iy, and x.
__px_powi1_4m()
vrs4_t __px_powi1_4m (vrs4_t x, int32_t iy, vis4_t mask)
Definition at line 17 of file pxpowi.c.
References __pmth_i_rpowi(), __ZGVxM4v__mth_i_vr4si4(), iy, and x.
__px_powi_2()
vrd2_t __px_powi_2 (vrd2_t x, vis4_t iy)
Definition at line 80 of file pxpowi.c.
References __pmth_i_dpowi(), __ZGVxN2vv__mth_i_vr8vi4(), iy, and x.
__px_powi_2m()
vrd2_t __px_powi_2m (vrd2_t x, vis4_t iy, vid2_t mask)
Definition at line 86 of file pxpowi.c.
References __pmth_i_dpowi(), __ZGVxM2vv__mth_i_vr8vi4(), iy, and x.
__px_powi_4()
vrs4_t __px_powi_4 (vrs4_t x, vis4_t iy)
Definition at line 23 of file pxpowi.c.
References __pmth_i_rpowi(), __ZGVxN4vv__mth_i_vr4vi4(), iy, and x.
__px_powi_4m()
vrs4_t __px_powi_4m (vrs4_t x, vis4_t iy, vis4_t mask)
Definition at line 29 of file pxpowi.c.
References __pmth_i_rpowi(), __ZGVxM4vv__mth_i_vr4vi4(), iy, and x.
__px_powk1_2()
vrd2_t __px_powk1_2 (vrd2_t x, long long iy)
Definition at line 92 of file pxpowi.c.
References __pmth_i_dpowk(), __ZGVxN2v__mth_i_vr8si8(), iy, and x.
__px_powk1_2m()
vrd2_t __px_powk1_2m (vrd2_t x, long long iy, vid2_t mask)
Definition at line 98 of file pxpowi.c.
References __pmth_i_dpowk(), __ZGVxM2v__mth_i_vr8si8(), iy, and x.
__px_powk1_4()
vrs4_t __px_powk1_4 (vrs4_t x, long long iy)
Definition at line 35 of file pxpowi.c.
References __pmth_i_rpowk(), __ZGVxN4v__mth_i_vr4si8(), iy, and x.
__px_powk1_4m()
vrs4_t __px_powk1_4m (vrs4_t x, long long iy, vis4_t mask)
Definition at line 41 of file pxpowi.c.
References __pmth_i_rpowk(), __ZGVxM4v__mth_i_vr4si8(), iy, and x.
__px_powk_2()
vrd2_t __px_powk_2 (vrd2_t x, vid2_t iy)
Definition at line 104 of file pxpowi.c.
References __pmth_i_dpowk(), __ZGVxN2vv__mth_i_vr8vi8(), iy, and x.
__px_powk_2m()
vrd2_t __px_powk_2m (vrd2_t x, vid2_t iy, vid2_t mask)
Definition at line 110 of file pxpowi.c.
References __pmth_i_dpowk(), __ZGVxM2vv__mth_i_vr8vi8(), iy, and x.
__px_powk_4()
vrs4_t __px_powk_4 (vrs4_t x, vid2_t iyu, vid2_t iyl)
Definition at line 47 of file pxpowi.c.
References __pmth_i_rpowk(), __ZGVxN4vv__mth_i_vr4vi8(), iyl, iyu, and x.
__px_powk_4m()
vrs4_t __px_powk_4m (vrs4_t x, vid2_t iyu, vid2_t iyl, vis4_t mask)
Definition at line 53 of file pxpowi.c.
References __pmth_i_rpowk(), __ZGVxM4vv__mth_i_vr4vi8(), iyl, iyu, and x.