flang: pypowi.c File Reference
pypowi.c File Reference
#include "mth_intrinsics.h"
Functions
vrs8_t __py_powi1_8 (vrs8_t x, int32_t iy)
vrs8_t __py_powi1_8m (vrs8_t x, int32_t iy, vis8_t mask)
vrs8_t __py_powi_8 (vrs8_t x, vis8_t iy)
vrs8_t __py_powi_8m (vrs8_t x, vis8_t iy, vis8_t mask)
vrs8_t __py_powk1_8 (vrs8_t x, long long iy)
vrs8_t __py_powk1_8m (vrs8_t x, long long iy, vis8_t mask)
vrs8_t __py_powk_8 (vrs8_t x, vid4_t iyu, vid4_t iyl)
vrs8_t __py_powk_8m (vrs8_t x, vid4_t iyu, vid4_t iyl, vis8_t mask)
vrd4_t __py_powi1_4 (vrd4_t x, int32_t iy)
vrd4_t __py_powi1_4m (vrd4_t x, int32_t iy, vid4_t mask)
vrd4_t __py_powi_4 (vrd4_t x, vis4_t iy)
vrd4_t __py_powi_4m (vrd4_t x, vis4_t iy, vid4_t mask)
vrd4_t __py_powk1_4 (vrd4_t x, long long iy)
vrd4_t __py_powk1_4m (vrd4_t x, long long iy, vid4_t mask)
vrd4_t __py_powk_4 (vrd4_t x, vid4_t iy)
vrd4_t __py_powk_4m (vrd4_t x, vid4_t iy, vid4_t mask)
Function Documentation
__py_powi1_4()
vrd4_t __py_powi1_4 (vrd4_t x, int32_t iy)
Definition at line 60 of file pypowi.c.
References __pmth_i_dpowi(), __ZGVyN4v__mth_i_vr8si4(), iy, and x.
__py_powi1_4m()
vrd4_t __py_powi1_4m (vrd4_t x, int32_t iy, vid4_t mask)
Definition at line 66 of file pypowi.c.
References __pmth_i_dpowi(), __ZGVyM4v__mth_i_vr8si4(), iy, and x.
__py_powi1_8()
vrs8_t __py_powi1_8 (vrs8_t x, int32_t iy)
Definition at line 12 of file pypowi.c.
References __pmth_i_rpowi(), __ZGVyN8v__mth_i_vr4si4(), iy, and x.
__py_powi1_8m()
vrs8_t __py_powi1_8m (vrs8_t x, int32_t iy, vis8_t mask)
Definition at line 18 of file pypowi.c.
References __pmth_i_rpowi(), __ZGVyM8v__mth_i_vr4si4(), iy, and x.
__py_powi_4()
vrd4_t __py_powi_4 (vrd4_t x, vis4_t iy)
Definition at line 72 of file pypowi.c.
References __pmth_i_dpowi(), __ZGVyN4vv__mth_i_vr8vi4(), iy, and x.
__py_powi_4m()
vrd4_t __py_powi_4m (vrd4_t x, vis4_t iy, vid4_t mask)
Definition at line 78 of file pypowi.c.
References __pmth_i_dpowi(), __ZGVyM4vv__mth_i_vr8vi4(), iy, and x.
__py_powi_8()
vrs8_t __py_powi_8 (vrs8_t x, vis8_t iy)
Definition at line 24 of file pypowi.c.
References __pmth_i_rpowi(), __ZGVyN8vv__mth_i_vr4vi4(), iy, and x.
__py_powi_8m()
vrs8_t __py_powi_8m (vrs8_t x, vis8_t iy, vis8_t mask)
Definition at line 30 of file pypowi.c.
References __pmth_i_rpowi(), __ZGVyM8vv__mth_i_vr4vi4(), iy, and x.
__py_powk1_4()
vrd4_t __py_powk1_4 (vrd4_t x, long long iy)
Definition at line 84 of file pypowi.c.
References __pmth_i_dpowk(), __ZGVyN4v__mth_i_vr8si8(), iy, and x.
__py_powk1_4m()
vrd4_t __py_powk1_4m (vrd4_t x, long long iy, vid4_t mask)
Definition at line 90 of file pypowi.c.
References __pmth_i_dpowk(), __ZGVyM4v__mth_i_vr8si8(), iy, and x.
__py_powk1_8()
vrs8_t __py_powk1_8 (vrs8_t x, long long iy)
Definition at line 36 of file pypowi.c.
References __pmth_i_rpowk(), __ZGVyN8v__mth_i_vr4si8(), iy, and x.
__py_powk1_8m()
vrs8_t __py_powk1_8m (vrs8_t x, long long iy, vis8_t mask)
Definition at line 42 of file pypowi.c.
References __pmth_i_rpowk(), __ZGVyM8v__mth_i_vr4si8(), iy, and x.
__py_powk_4()
vrd4_t __py_powk_4 (vrd4_t x, vid4_t iy)
Definition at line 96 of file pypowi.c.
References __pmth_i_dpowk(), __ZGVyN4vv__mth_i_vr8vi8(), iy, and x.
__py_powk_4m()
vrd4_t __py_powk_4m (vrd4_t x, vid4_t iy, vid4_t mask)
Definition at line 102 of file pypowi.c.
References __pmth_i_dpowk(), __ZGVyM4vv__mth_i_vr8vi8(), iy, and x.
__py_powk_8()
vrs8_t __py_powk_8 (vrs8_t x, vid4_t iyu, vid4_t iyl)
Definition at line 48 of file pypowi.c.
References __pmth_i_rpowk(), __ZGVyN8vv__mth_i_vr4vi8(), iyl, iyu, and x.
__py_powk_8m()
vrs8_t __py_powk_8m (vrs8_t x, vid4_t iyu, vid4_t iyl, vis8_t mask)
Definition at line 54 of file pypowi.c.
References __pmth_i_rpowk(), __ZGVyM8vv__mth_i_vr4vi8(), iyl, iyu, and x.