flang: pzpowi.c File Reference
pzpowi.c File Reference
#include "mth_intrinsics.h"
Functions
vrs16_t __pz_powi1_16 (vrs16_t x, int32_t iy)
vrs16_t __pz_powi1_16m (vrs16_t x, int32_t iy, vis16_t mask)
vrs16_t __pz_powi_16 (vrs16_t x, vis16_t iy)
vrs16_t __pz_powi_16m (vrs16_t x, vis16_t iy, vis16_t mask)
vrs16_t __pz_powk1_16 (vrs16_t x, long long iy)
vrs16_t __pz_powk1_16m (vrs16_t x, long long iy, vis16_t mask)
vrs16_t __pz_powk_16 (vrs16_t x, vid8_t iyu, vid8_t iyl)
vrs16_t __pz_powk_16m (vrs16_t x, vid8_t iyu, vid8_t iyl, vis16_t mask)
vrd8_t __pz_powi1_8 (vrd8_t x, int32_t iy)
vrd8_t __pz_powi1_8m (vrd8_t x, int32_t iy, vid8_t mask)
vrd8_t __pz_powi_8 (vrd8_t x, vis8_t iy)
vrd8_t __pz_powi_8m (vrd8_t x, vis8_t iy, vid8_t mask)
vrd8_t __pz_powk1_8 (vrd8_t x, long long iy)
vrd8_t __pz_powk1_8m (vrd8_t x, long long iy, vid8_t mask)
vrd8_t __pz_powk_8 (vrd8_t x, vid8_t iy)
vrd8_t __pz_powk_8m (vrd8_t x, vid8_t iy, vid8_t mask)
Function Documentation
__pz_powi1_16()
vrs16_t __pz_powi1_16 (vrs16_t x, int32_t iy)
Definition at line 11 of file pzpowi.c.
References __pmth_i_rpowi(), __ZGVzN16v__mth_i_vr4si4(), iy, and x.
__pz_powi1_16m()
vrs16_t __pz_powi1_16m (vrs16_t x, int32_t iy, vis16_t mask)
Definition at line 17 of file pzpowi.c.
References __pmth_i_rpowi(), __ZGVzM16v__mth_i_vr4si4(), iy, and x.
__pz_powi1_8()
vrd8_t __pz_powi1_8 (vrd8_t x, int32_t iy)
Definition at line 59 of file pzpowi.c.
References __pmth_i_dpowi(), __ZGVzN8v__mth_i_vr8si4(), iy, and x.
__pz_powi1_8m()
vrd8_t __pz_powi1_8m (vrd8_t x, int32_t iy, vid8_t mask)
Definition at line 65 of file pzpowi.c.
References __pmth_i_dpowi(), __ZGVzM8v__mth_i_vr8si4(), iy, and x.
__pz_powi_16()
vrs16_t __pz_powi_16 (vrs16_t x, vis16_t iy)
Definition at line 23 of file pzpowi.c.
References __pmth_i_rpowi(), __ZGVzN16vv__mth_i_vr4vi4(), iy, and x.
__pz_powi_16m()
vrs16_t __pz_powi_16m (vrs16_t x, vis16_t iy, vis16_t mask)
Definition at line 29 of file pzpowi.c.
References __pmth_i_rpowi(), __ZGVzM16vv__mth_i_vr4vi4(), iy, and x.
__pz_powi_8()
vrd8_t __pz_powi_8 (vrd8_t x, vis8_t iy)
Definition at line 71 of file pzpowi.c.
References __pmth_i_dpowi(), __ZGVzN8vv__mth_i_vr8vi4(), iy, and x.
__pz_powi_8m()
vrd8_t __pz_powi_8m (vrd8_t x, vis8_t iy, vid8_t mask)
Definition at line 77 of file pzpowi.c.
References __pmth_i_dpowi(), __ZGVzM8vv__mth_i_vr8vi4(), iy, and x.
__pz_powk1_16()
vrs16_t __pz_powk1_16 (vrs16_t x, long long iy)
Definition at line 35 of file pzpowi.c.
References __pmth_i_rpowk(), __ZGVzN16v__mth_i_vr4si8(), iy, and x.
__pz_powk1_16m()
vrs16_t __pz_powk1_16m (vrs16_t x, long long iy, vis16_t mask)
Definition at line 41 of file pzpowi.c.
References __pmth_i_rpowk(), __ZGVzM16v__mth_i_vr4si8(), iy, and x.
__pz_powk1_8()
vrd8_t __pz_powk1_8 (vrd8_t x, long long iy)
Definition at line 83 of file pzpowi.c.
References __pmth_i_dpowk(), __ZGVzN8v__mth_i_vr8si8(), iy, and x.
__pz_powk1_8m()
vrd8_t __pz_powk1_8m (vrd8_t x, long long iy, vid8_t mask)
Definition at line 89 of file pzpowi.c.
References __pmth_i_dpowk(), __ZGVzM8v__mth_i_vr8si8(), iy, and x.
__pz_powk_16()
vrs16_t __pz_powk_16 (vrs16_t x, vid8_t iyu, vid8_t iyl)
Definition at line 47 of file pzpowi.c.
References __pmth_i_rpowk(), __ZGVzN16vv__mth_i_vr4vi8(), iyl, iyu, and x.
__pz_powk_16m()
vrs16_t __pz_powk_16m (vrs16_t x, vid8_t iyu, vid8_t iyl, vis16_t mask)
Definition at line 53 of file pzpowi.c.
References __pmth_i_rpowk(), __ZGVzM16vv__mth_i_vr4vi8(), iyl, iyu, and x.
__pz_powk_8()
vrd8_t __pz_powk_8 (vrd8_t x, vid8_t iy)
Definition at line 95 of file pzpowi.c.
References __pmth_i_dpowk(), __ZGVzN8vv__mth_i_vr8vi8(), iy, and x.
__pz_powk_8m()
vrd8_t __pz_powk_8m (vrd8_t x, vid8_t iy, vid8_t mask)
Definition at line 101 of file pzpowi.c.
References __pmth_i_dpowk(), __ZGVzM8vv__mth_i_vr8vi8(), iy, and x.