flang: query.c File Reference
query.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
Functions
static int I8() fetch_int (void *b, F90_Desc *s)
static void I8() fetch_vector (void *ab, F90_Desc *as, __INT_T *vector, int veclen)
static void I8() store_int (void *b, F90_Desc *s, __INT_T val)
static void I8() store_log (void *b, F90_Desc *s, int val)
static void I8() store_element (void *ab, F90_Desc *as, int index, int val)
static void I8() store_vector (void *ab, F90_Desc *as, __INT_T *vector, __INT_T veclen)
static void I8() store_vector_int (void *ab, F90_Desc *as, int *vector, __INT_T veclen)
static void ftnstrcpy (char *dst, size_t len, const char *src)
void ENTFTN (DIST_ALIGNMENT, dist_alignment)
void ENTFTN (DIST_DISTRIBUTIONA, dist_distributiona)
void ENTFTN (DIST_DISTRIBUTION, dist_distribution)
void ENTFTN (DIST_TEMPLATEA, dist_templatea)
void ENTFTN (DIST_TEMPLATE, dist_template)
void ENTFTN (GLOBAL_ALIGNMENT, global_alignment)
void ENTFTN (GLOBAL_DISTRIBUTIONA, global_distributiona)
void ENTFTN (GLOBAL_DISTRIBUTION, global_distribution)
void ENTFTN (GLOBAL_TEMPLATEA, global_templatea)
void ENTFTN (GLOBAL_TEMPLATE, global_template)
void ENTFTN (GLOBAL_LBOUND, global_lbound)
void ENTFTN (GLOBAL_SHAPE, global_shape)
void ENTFTN (GLOBAL_SIZE, global_size)
void ENTFTN (GLOBAL_UBOUND, global_ubound)
void ENTFTN (ABSTRACT_TO_PHYSICAL, abstract_to_physical)
void ENTFTN (PHYSICAL_TO_ABSTRACT, physical_to_abstract)
void ENTFTN (LOCAL_TO_GLOBAL, local_to_global)
void ENTFTN (GLOBAL_TO_LOCAL, global_to_local)
void ENTFTN (LOCAL_BLKCNT, local_blkcnt)
void ENTFTN (LOCAL_LINDEX, local_lindex)
void ENTFTN (LOCAL_UINDEX, local_uindex)
void ENTFTN (PROCESSORS_SHAPE, processors_shape)
__INT_T ENTFTN (MY_PROCESSOR, my_processor)()
__INT_T ENTFTN (MYPROCNUM, myprocnum)()
int __fort_nprocs ()
__INT_T ENTFTN (NPROCS, nprocs)()
__INT_T (__INT_T *dim, __INT_T *szdim)
__INT8_T (__INT_T *dim, __INT_T *szdim)
__INT_T ENTFTN (PROCESSORS_RANK, processors_rank)()
__INT8_T ENTFTN (KPROCESSORS_RANK, kprocessors_rank)()
void __fort_procnum_to_coord (int procnum, int rank, __INT_T *shape, __INT_T *coord)
void ENTFTN (PROCNUM_TO_COORD, procnum_to_coord)
int __fort_coord_to_procnum (__INT_T rank, __INT_T *shape, __INT_T *coord)
__INT_T (__INT_T *rank, __INT_T *shape, __INT_T *coord)
Function Documentation
__fort_coord_to_procnum()
int __fort_coord_to_procnum (__INT_T rank, __INT_T * shape, __INT_T * coord)
Definition at line 1647 of file query.c.
References __fort_abort(), i, m, p, and rank.
Referenced by __INT_T().
__fort_nprocs()
int __fort_nprocs ()
Definition at line 1548 of file query.c.
References GET_DIST_TCPUS.
__fort_procnum_to_coord()
void __fort_procnum_to_coord (int procnum, int rank, __INT_T * shape, __INT_T * coord)
Definition at line 1614 of file query.c.
References __fort_abort(), i, m, and rank.
Referenced by ENTFTN().
__INT8_T()
__INT8_T (__INT_T * dim, __INT_T * szdim)
Definition at line 1571 of file query.c.
References __fort_varying_int(), d, dim, GET_DIST_TCPUS, and ISPRESENT.
__INT_T() [1/2]
__INT_T (__INT_T * dim, __INT_T * szdim)
Definition at line 1556 of file query.c.
References __fort_varying_int(), d, dim, GET_DIST_TCPUS, and ISPRESENT.
__INT_T() [2/2]
__INT_T (__INT_T * rank, __INT_T * shape, __INT_T * coord)
Definition at line 1664 of file query.c.
References __fort_coord_to_procnum(), and rank.
ENTFTN() [1/28]
void ENTFTN (ABSTRACT_TO_PHYSICAL , abstract_to_physical)
Definition at line 929 of file query.c.
References __DESC, __fort_abort(), DECL_HDR_PTRS, DIST_ACTUAL_ARG_G, DIST_DIST_TARGET_G, F90_TAG_G, fetch_vector(), i, I8, index, MAXDIMS, NULL, p, pd, and store_int().
ENTFTN() [2/28]
void ENTFTN (DIST_ALIGNMENT , dist_alignment)
Definition at line 175 of file query.c.
References __DESC, __DYNAMIC, DECL_DIM_PTRS, DFMT, DFMT_COLLAPSED, DIST_ALIGN_TARGET_G, DIST_DIST_TARGET_G, DIST_DPTR_TAXIS_G, DIST_DPTR_TLB_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, DIST_DPTR_TUB_G, DIST_REPLICATED_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_FLAGS_G, F90_RANK_G, F90_TAG_G, GET_DIST_TCPUS, i, I8, identity_map, ISPRESENT, lb, MAXDIMS, p, pd, rank, SET_DIM_PTRS, store_int(), store_log(), store_vector(), stride, and ub.
Referenced by ENTFTN().
ENTFTN() [3/28]
void ENTFTN (DIST_DISTRIBUTION , dist_distribution)
Definition at line 369 of file query.c.
References __CLEN_T, CADR, CLEN, and ENTFTN().
ENTFTN() [4/28]
void ENTFTN (DIST_DISTRIBUTIONA , dist_distributiona)
Definition at line 254 of file query.c.
References __CLEN_T, __DESC, __fort_abort(), CADR, CLEN, DECL_DIM_PTRS, DECL_HDR_PTRS, DFMT, DFMT_BLOCK, DFMT_BLOCK_K, DFMT_COLLAPSED, DFMT_CYCLIC, DFMT_CYCLIC_K, DFMT_GEN_BLOCK, DFMT_INDIRECT, DIST_ALIGN_TARGET_G, DIST_DIST_TARGET_G, DIST_DPTR_BLOCK_G, DIST_DPTR_NO_G, DIST_DPTR_PO_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_PSTRIDE_G, F90_RANK_G, F90_TAG_G, ftnstrcpy(), i, I8, ISPRESENT, ISPRESENTC, len, MAXDIMS, NULL, p, pd, rank, SET_DIM_PTRS, src, store_int(), and store_vector().
ENTFTN() [5/28]
void ENTFTN (DIST_TEMPLATE , dist_template)
Definition at line 479 of file query.c.
References __CLEN_T, CADR, CLEN, ENTFTN(), lb, and ub.
ENTFTN() [6/28]
void ENTFTN (DIST_TEMPLATEA , dist_templatea)
Definition at line 385 of file query.c.
References __CLEN_T, __DESC, __DYNAMIC, __fort_abort(), a, CADR, CLEN, DECL_DIM_PTRS, DECL_HDR_PTRS, DIST_ALIGN_TARGET_G, DIST_DIM_TAXIS_G, DIST_DIST_TARGET_G, DIST_DPTR_PAXIS_G, DIST_DPTR_PSHAPE_G, DIST_INFO_G, DIST_NEXT_ALIGNEE_G, DIST_SINGLE_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_FLAGS_G, F90_RANK_G, F90_TAG_G, ftnstrcpy(), i, I8, ISPRESENT, ISPRESENTC, lb, len, MAXDIMS, NULL, p, rank, SET_DIM_PTRS, src, store_int(), store_log(), store_vector(), and ub.
ENTFTN() [7/28]
void ENTFTN (GLOBAL_ALIGNMENT , global_alignment)
Definition at line 494 of file query.c.
References __DESC, __DYNAMIC, __fort_abort(), DECL_DIM_PTRS, DECL_HDR_PTRS, DIST_ACTUAL_ARG_G, DIST_ALIGN_TARGET_G, DIST_DIST_TARGET_G, DIST_DPTR_TAXIS_G, DIST_DPTR_TLB_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, DIST_DPTR_TUB_G, DIST_REPLICATED_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_FLAGS_G, F90_RANK_G, F90_TAG_G, GET_DIST_TCPUS, i, I8, identity_map, ISPRESENT, lb, MAXDIMS, n, NULL, p, rank, SET_DIM_PTRS, store_int(), store_log(), store_vector(), stride, and ub.
ENTFTN() [8/28]
void ENTFTN (GLOBAL_DISTRIBUTION , global_distribution)
Definition at line 696 of file query.c.
References __CLEN_T, CADR, CLEN, and ENTFTN().
ENTFTN() [9/28]
void ENTFTN (GLOBAL_DISTRIBUTIONA , global_distributiona)
Definition at line 573 of file query.c.
References __CLEN_T, __DESC, __fort_abort(), CADR, CLEN, DECL_DIM_PTRS, DECL_HDR_PTRS, DFMT, DFMT_BLOCK, DFMT_BLOCK_K, DFMT_COLLAPSED, DFMT_CYCLIC, DFMT_CYCLIC_K, DFMT_GEN_BLOCK, DFMT_INDIRECT, DIST_ACTUAL_ARG_G, DIST_ALIGN_TARGET_G, DIST_DIST_TARGET_G, DIST_DPTR_BLOCK_G, DIST_DPTR_NO_G, DIST_DPTR_PO_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_PSTRIDE_G, F90_RANK_G, F90_TAG_G, ftnstrcpy(), i, I8, ISPRESENT, ISPRESENTC, len, MAXDIMS, NULL, p, pd, rank, SET_DIM_PTRS, src, store_int(), and store_vector().
ENTFTN() [10/28]
void ENTFTN (GLOBAL_LBOUND , global_lbound)
Definition at line 814 of file query.c.
References __DESC, __fort_abort(), DECL_HDR_PTRS, dim, DIST_ACTUAL_ARG_G, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, fetch_int(), i, I8, ISPRESENT, MAXDIMS, NULL, rank, store_int(), and store_vector().
ENTFTN() [11/28]
void ENTFTN (GLOBAL_SHAPE , global_shape)
Definition at line 842 of file query.c.
References __DESC, __fort_abort(), DECL_DIM_PTRS, DECL_HDR_PTRS, DIST_ACTUAL_ARG_G, extent(), F90_DPTR_EXTENT_G, F90_RANK_G, F90_TAG_G, i, I8, MAXDIMS, NULL, rank, SET_DIM_PTRS, and store_vector().
ENTFTN() [12/28]
void ENTFTN (GLOBAL_SIZE , global_size)
Definition at line 868 of file query.c.
References __DESC, __fort_abort(), DECL_DIM_PTRS, DECL_HDR_PTRS, dim, DIST_ACTUAL_ARG_G, F90_DPTR_EXTENT_G, F90_GSIZE_G, F90_RANK_G, F90_TAG_G, fetch_int(), I8, ISPRESENT, NULL, rank, SET_DIM_PTRS, size, and store_int().
ENTFTN() [13/28]
void ENTFTN (GLOBAL_TEMPLATE , global_template)
Definition at line 801 of file query.c.
References __CLEN_T, CADR, CLEN, ENTFTN(), lb, and ub.
ENTFTN() [14/28]
void ENTFTN (GLOBAL_TEMPLATEA , global_templatea)
Definition at line 711 of file query.c.
References __CLEN_T, __DESC, __DYNAMIC, __fort_abort(), a, CADR, CLEN, DECL_DIM_PTRS, DECL_HDR_PTRS, DIST_ACTUAL_ARG_G, DIST_ALIGN_TARGET_G, DIST_DIM_TAXIS_G, DIST_DIST_TARGET_G, DIST_DPTR_PAXIS_G, DIST_DPTR_PSHAPE_G, DIST_INFO_G, DIST_NEXT_ALIGNEE_G, DIST_SINGLE_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_FLAGS_G, F90_RANK_G, F90_TAG_G, ftnstrcpy(), i, I8, ISPRESENT, ISPRESENTC, lb, len, MAXDIMS, NULL, p, rank, SET_DIM_PTRS, src, store_int(), store_log(), store_vector(), and ub.
ENTFTN() [15/28]
void ENTFTN (GLOBAL_TO_LOCAL , global_to_local)
Definition at line 1157 of file query.c.
References __DESC, __fort_abort(), __fort_describe_replication(), __fort_free(), __fort_islocal(), __fort_malloc(), __fort_owner, Abs, DECL_DIM_PTRS, DECL_HDR_PTRS, DFMT, DFMT_CYCLIC, DFMT_CYCLIC_K, DIST_ACTUAL_ARG_G, DIST_DPTR_BLOCK_G, DIST_DPTR_CLB_G, DIST_DPTR_COFSTR_G, DIST_DPTR_CYCLE_G, DIST_DPTR_OLB_G, DIST_DPTR_OUB_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_RANK_G, F90_TAG_G, fetch_vector(), i, I8, ISPRESENT, j, MAXDIMS, repl_t::ncopies, repl_t::ndim, NULL, repl_t::pcnt, repl_t::pstr, RECIP_DIV, SET_DIM_PTRS, store_int(), store_log(), and store_vector().
ENTFTN() [16/28]
void ENTFTN (GLOBAL_UBOUND , global_ubound)
Definition at line 901 of file query.c.
References __DESC, __fort_abort(), DECL_HDR_PTRS, dim, DIM_UBOUND_G, DIST_ACTUAL_ARG_G, F90_RANK_G, F90_TAG_G, fetch_int(), i, I8, ISPRESENT, MAXDIMS, NULL, rank, store_int(), and store_vector().
ENTFTN() [17/28]
__INT8_T ENTFTN (KPROCESSORS_RANK , kprocessors_rank)
Definition at line 1595 of file query.c.
ENTFTN() [18/28]
void ENTFTN (LOCAL_BLKCNT , local_blkcnt)
Definition at line 1280 of file query.c.
References __DESC, __fort_abort(), __fort_block_bounds(), __fort_cycle_bounds(), __OFF_TEMPLATE, cl, DECL_DIM_PTRS, DECL_HDR_PTRS, dim, DIST_ACTUAL_ARG_G, DIST_DPTR_CL_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, F90_FLAGS_G, F90_RANK_G, F90_TAG_G, fetch_int(), GET_DIST_LCPU, GET_DIST_TCPUS, I8, ISPRESENT, MAXDIMS, NULL, SET_DIM_PTRS, store_int(), and store_vector().
ENTFTN() [19/28]
void ENTFTN (LOCAL_LINDEX , local_lindex)
Definition at line 1348 of file query.c.
References __DESC, __fort_abort(), __fort_block_bounds(), __fort_cycle_bounds(), __OFF_TEMPLATE, Abs, cl, DECL_DIM_PTRS, DECL_HDR_PTRS, DFMT, DFMT_CYCLIC, DFMT_CYCLIC_K, dim, DIST_ACTUAL_ARG_G, DIST_DPTR_BLOCK_G, DIST_DPTR_CL_G, DIST_DPTR_CLB_G, DIST_DPTR_CN_G, DIST_DPTR_COFSTR_G, DIST_DPTR_CS_G, DIST_DPTR_CYCLE_G, DIST_DPTR_OLB_G, DIST_DPTR_OUB_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_RANK_G, F90_TAG_G, fetch_int(), GET_DIST_LCPU, GET_DIST_TCPUS, I8, ISPRESENT, j, NULL, RECIP_DIV, SET_DIM_PTRS, and store_element().
ENTFTN() [20/28]
void ENTFTN (LOCAL_TO_GLOBAL , local_to_global)
Definition at line 997 of file query.c.
References __DESC, __fort_abort(), Abs, Ceil, DECL_DIM_PTRS, DECL_HDR_PTRS, DFMT, DFMT_CYCLIC, DFMT_CYCLIC_K, DIST_ACTUAL_ARG_G, DIST_DPTR_BLOCK_G, DIST_DPTR_CYCLE_G, DIST_DPTR_OLB_G, DIST_DPTR_PCOORD_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_TLB_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, DIST_DPTR_TUB_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_RANK_G, F90_TAG_G, fetch_vector(), first, i, I8, index, MAXDIMS, Min, NULL, off, RECIP_DIV, RECIP_DIVMOD, SET_DIM_PTRS, store_vector(), and tstride.
ENTFTN() [21/28]
void ENTFTN (LOCAL_UINDEX , local_uindex)
Definition at line 1441 of file query.c.
References __DESC, __fort_abort(), __fort_block_bounds(), __fort_cycle_bounds(), __OFF_TEMPLATE, Abs, cl, DECL_DIM_PTRS, DECL_HDR_PTRS, DFMT, DFMT_CYCLIC, DFMT_CYCLIC_K, dim, DIST_ACTUAL_ARG_G, DIST_DPTR_BLOCK_G, DIST_DPTR_CL_G, DIST_DPTR_CLB_G, DIST_DPTR_CN_G, DIST_DPTR_COFSTR_G, DIST_DPTR_CS_G, DIST_DPTR_CYCLE_G, DIST_DPTR_OLB_G, DIST_DPTR_OUB_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_RANK_G, F90_TAG_G, fetch_int(), GET_DIST_LCPU, GET_DIST_TCPUS, I8, ISPRESENT, j, NULL, RECIP_DIV, SET_DIM_PTRS, and store_element().
ENTFTN() [22/28]
__INT_T ENTFTN (MY_PROCESSOR , my_processor)
Definition at line 1542 of file query.c.
References GET_DIST_LCPU.
ENTFTN() [23/28]
__INT_T ENTFTN (MYPROCNUM , myprocnum)
Definition at line 1545 of file query.c.
References GET_DIST_LCPU.
ENTFTN() [24/28]
__INT_T ENTFTN (NPROCS , nprocs)
Definition at line 1554 of file query.c.
References GET_DIST_TCPUS.
ENTFTN() [25/28]
void ENTFTN (PHYSICAL_TO_ABSTRACT , physical_to_abstract)
Definition at line 961 of file query.c.
References __DESC, __fort_abort(), DECL_HDR_PTRS, DIST_ACTUAL_ARG_G, DIST_DIST_TARGET_G, F90_TAG_G, fetch_int(), i, I8, index, MAXDIMS, NULL, p, pd, RECIP_DIVMOD, and store_vector().
ENTFTN() [26/28]
__INT_T ENTFTN (PROCESSORS_RANK , processors_rank)
Definition at line 1592 of file query.c.
ENTFTN() [27/28]
void ENTFTN (PROCESSORS_SHAPE , processors_shape)
Definition at line 1533 of file query.c.
References GET_DIST_TCPUS_ADDR, I8, and store_vector_int().
ENTFTN() [28/28]
void ENTFTN (PROCNUM_TO_COORD , procnum_to_coord)
Definition at line 1633 of file query.c.
References __fort_procnum_to_coord(), and rank.
fetch_int()
static int I8() fetch_int (void * b, F90_Desc * s) static
Definition at line 17 of file query.c.
References __fort_abort(), __INT1, __INT2, __INT4, __INT8, b, kind, s, and TYPEKIND.
Referenced by ENTFTN(), and fetch_vector().
fetch_vector()
static void I8() fetch_vector (void * ab, F90_Desc * as, __INT_T * vector, int veclen) static
Definition at line 55 of file query.c.
References __fort_abort(), __fort_local_address(), F90_DIM_LBOUND_G, F90_RANK_G, fetch_int(), i, I8, and NULL.
Referenced by ENTFTN().
ftnstrcpy()
static void ftnstrcpy (char * dst, size_t len, const char * src) static
Definition at line 162 of file query.c.
References end, len, and src.
Referenced by ENTFTN().
store_element()
static void I8() store_element (void * ab, F90_Desc * as, int index, int val) static
Definition at line 114 of file query.c.
References __fort_abort(), __fort_local_address(), F90_DIM_LBOUND_G, F90_RANK_G, i, I8, index, NULL, store_int(), and val.
Referenced by ENTFTN().
store_int()
static void I8() store_int (void * b, F90_Desc * s, __INT_T val) static
Definition at line 72 of file query.c.
References __fort_abort(), __INT1, __INT2, __INT4, __INT8, b, kind, s, TYPEKIND, and val.
Referenced by ENTFTN(), store_element(), store_vector(), and store_vector_int().
store_log()
static void I8() store_log (void * b, F90_Desc * s, int val) static
Definition at line 93 of file query.c.
References __fort_abort(), __LOG1, __LOG2, __LOG4, __LOG8, b, GET_DIST_TRUE_LOG1, GET_DIST_TRUE_LOG2, GET_DIST_TRUE_LOG4, GET_DIST_TRUE_LOG8, kind, s, TYPEKIND, and val.
Referenced by ENTFTN().
store_vector()
static void I8() store_vector (void * ab, F90_Desc * as, __INT_T * vector, __INT_T veclen) static
Definition at line 128 of file query.c.
References __fort_abort(), __fort_local_address(), F90_DIM_LBOUND_G, F90_RANK_G, i, I8, NULL, and store_int().
Referenced by ENTFTN().
store_vector_int()
static void I8() store_vector_int (void * ab, F90_Desc * as, int * vector, __INT_T veclen) static
Definition at line 145 of file query.c.
References __fort_abort(), __fort_local_address(), F90_DIM_LBOUND_G, F90_RANK_G, i, I8, NULL, and store_int().
Referenced by ENTFTN().