flang: rbtree.h File Reference
rbtree.h File Reference
Classes
struct rbtree_root_struct
struct rbtree_struct
Macros
#define RBRED 1
#define RBBLK 2
#define RBCOLOR 3
#define ISBLACK(rb) (rb == NULL || (rb->color == RBBLK))
#define ISRED(rb) (rb != NULL && (rb->color == RBRED))
#define SETBLACK(rb)
#define SETRED(rb)
#define COPYCOLOR(rb, fb) rb->color = fb->color
#define ALN(b, aln) ((((b) + (aln)-1)) & (~((aln)-1)))
Typedefs
typedef struct rbtree_root_struct rbroot
typedef struct rbtree_struct * rbtree
typedef int(* rb_compare) (void *, void *)
typedef int(* rb_walk_proc) (rbtree, void *userdata)
Functions
int rb_walk (rbroot *T, rb_walk_proc proc, void *userdata)
...
rbtree rb_find (rbroot *T, void *data, rb_compare compare)
...
rbtree rb_insert (rbroot *T, size_t datasize, void *data, rb_compare compare)
...
void rb_free (rbroot *T)
...
Macro Definition Documentation
ALN
#define ALN (b, aln) ((((b) + (aln)-1)) & (~((aln)-1)))
Definition at line 42 of file rbtree.h.
COPYCOLOR
#define COPYCOLOR (rb, fb) rb->color = fb->color
Definition at line 40 of file rbtree.h.
ISBLACK
#define ISBLACK (rb) (rb == NULL || (rb->color == RBBLK))
Definition at line 30 of file rbtree.h.
ISRED
#define ISRED (rb) (rb != NULL && (rb->color == RBRED))
Definition at line 31 of file rbtree.h.
RBBLK
#define RBBLK 2
Definition at line 27 of file rbtree.h.
RBCOLOR
#define RBCOLOR 3
Definition at line 28 of file rbtree.h.
RBRED
#define RBRED 1
Definition at line 26 of file rbtree.h.
SETBLACK
#define SETBLACK (rb)
Value:
  if (rb) {            \
    rb->color = RBBLK; \
  }
Definition at line 32 of file rbtree.h.
SETRED
#define SETRED (rb)
Value:
  if (rb) {            \
    rb->color = RBRED; \
  }
Definition at line 36 of file rbtree.h.
Typedef Documentation
rb_compare
typedef int(* rb_compare) (void *, void *)
Definition at line 44 of file rbtree.h.
rb_walk_proc
typedef int(* rb_walk_proc) (rbtree, void *userdata)
Definition at line 45 of file rbtree.h.
rbroot
typedef struct rbtree_root_struct rbroot
Definition at line 11 of file rbtree.h.
rbtree
typedef struct rbtree_struct* rbtree
Definition at line 12 of file rbtree.h.
Function Documentation
rb_find()
rbtree rb_find (rbroot * T, void * data, rb_compare compare)
...
Definition at line 187 of file rbtree.cpp.
References rbtree_struct::data, r, T, and x.
rb_free()
void rb_free (rbroot * T)
...
Definition at line 241 of file rbtree.cpp.
References NULL, p, q, sccfree(), and T.
rb_insert()
rbtree rb_insert (rbroot * T, size_t datasize, void * data, rb_compare compare)
...
Definition at line 137 of file rbtree.cpp.
References _rbtree_insert(), rbtree_struct::data, ISRED, rb_left_rotate(), rb_right_rotate(), SETBLACK, SETRED, T, x, and y.
rb_walk()
int rb_walk (rbroot * T, rb_walk_proc proc, void * userdata)
...
Definition at line 229 of file rbtree.cpp.
References _rb_walk(), r, and T.