flang: rbtree.cpp File Reference
rbtree.cpp File Reference
#include "gbldefs.h"
#include "rbtree.h"
Functions
static void rb_left_rotate (rbroot *T, rbtree x)
static void rb_right_rotate (rbroot *T, rbtree x)
static rbtree rb_new (rbroot *T, size_t datasize, void *data)
static rbtree _rbtree_insert (rbroot *T, size_t datasize, void *data, rb_compare compare)
rbtree rb_insert (rbroot *T, size_t datasize, void *data, rb_compare compare)
...
rbtree rb_find (rbroot *T, void *data, rb_compare compare)
...
static int _rb_walk (rbtree x, rb_walk_proc proc, void *userdata)
int rb_walk (rbroot *T, rb_walk_proc proc, void *userdata)
...
void rb_free (rbroot *T)
...
Function Documentation
_rb_walk()
static int _rb_walk (rbtree x, rb_walk_proc proc, void * userdata) static
Definition at line 209 of file rbtree.cpp.
References _rb_walk(), r, and x.
Referenced by _rb_walk(), and rb_walk().
_rbtree_insert()
static rbtree _rbtree_insert (rbroot * T, size_t datasize, void * data, rb_compare compare) static
Definition at line 106 of file rbtree.cpp.
References rbtree_struct::data, NULL, rb_new(), T, x, y, and z.
Referenced by rb_insert().
rb_find()
rbtree rb_find (rbroot * T, void * data, rb_compare compare)
...
Definition at line 187 of file rbtree.cpp.
References rbtree_struct::data, r, T, and x.
rb_free()
void rb_free (rbroot * T)
...
Definition at line 241 of file rbtree.cpp.
References NULL, p, q, sccfree(), and T.
rb_insert()
rbtree rb_insert (rbroot * T, size_t datasize, void * data, rb_compare compare)
...
Definition at line 137 of file rbtree.cpp.
References _rbtree_insert(), rbtree_struct::data, ISRED, rb_left_rotate(), rb_right_rotate(), SETBLACK, SETRED, T, x, and y.
rb_left_rotate()
static void rb_left_rotate (rbroot * T, rbtree x) static
Definition at line 21 of file rbtree.cpp.
References rbtree_struct::left, NULL, rbtree_struct::parent, rbtree_struct::right, T, x, and y.
Referenced by rb_insert().
rb_new()
static rbtree rb_new (rbroot * T, size_t datasize, void * data) static
Definition at line 68 of file rbtree.cpp.
References ALN, rbtree_struct::data, if(), NULL, sccalloc(), T, and x.
Referenced by _rbtree_insert().
rb_right_rotate()
static void rb_right_rotate (rbroot * T, rbtree x) static
Definition at line 43 of file rbtree.cpp.
References rbtree_struct::left, NULL, rbtree_struct::parent, rbtree_struct::right, T, x, and y.
Referenced by rb_insert().
rb_walk()
int rb_walk (rbroot * T, rb_walk_proc proc, void * userdata)
...
Definition at line 229 of file rbtree.cpp.
References _rb_walk(), r, and T.