flang: rdst.c File Reference
rdst.c File Reference
Data redistribution routines.
#include "stdioInterf.h"
#include "fioMacros.h"
#include "utils3f.h"
#include <string.h>
#include "fort_vars.h"
Macros
#define REDESCRIBE 0x001
#define RETARGET 0x002
#define REFORMAT 0x004
#define REALIGN 0x008
#define RELOCATE 0x010
#define SQUEEZE 0x020
#define SHRINK 0x040
#define EXPAND 0x080
#define RECOPY 0x100
#define TEMPLATE(dd, i, lb, ub, lbase, gsize)
Enumerations
enum copy_dir { __COPY_IN , __COPY_OUT }
Functions
void ENTFTN (TEMPLATE, template)
static void I8() local_copy (char *db, F90_Desc *dd, __INT_T doffset, char *ab, F90_Desc *ad, __INT_T aoffset, __INT_T dim, copy_dir dir)
copy local data between global actual array and local dummy array
__INT_T I8() is_nonsequential_section (F90_Desc *a, __INT_T dim)
check if a descriptor is associated with a non-contiguous section.
static void copy_in_abort (const char *msg)
void ENTFTN (QOPY_IN, qopy_in)
void I8() __fort_copy_out (void *ab, void *db, F90_Desc *ad, F90_Desc *dd, __INT_T flags)
void ENTFTN (COPY_OUT, copy_out)
void ENTFTN (CHECK_BLOCK_SIZE, check_block_size)
void (F90_Desc *dd, __INT_T *p_rank, __INT_T *p_flags,...)
General routine to create a template (alignment or distribution) descriptor.
void ENTF90 (TEMPLATE, template)
Optimized routine to create a template.
void ENTF90 (TEMPLATE1, template1)
Optimized routine to create a template for 1 dimension array.
void ENTF90 (TEMPLATE2, template2)
Optimized routine to create a template for 2 dimesion array.
void ENTF90 (TEMPLATE3, template3)
Optimized routine to create a template for 3 dimesion array.
void ENTF90 (TEMPLATE1V, template1v)
Optimized routine to create a template from value arguments.
void ENTF90 (TEMPLATE2V, template2v)
Optimized routine to create a template for 2 dim array from value arguments.
void ENTF90 (TEMPLATE3V, template3v)
Optimized routine to create a template for 3 dim array from value arguments.
void ENTFTN (INSTANCE, instance)
void ENTFTN (FREE, free)
void ENTFTN (FREEN, freen)
void (char *ab, char *ad, char **addr)
void ENTF90 (COPY_F77_ARG, copy_f77_arg)
void ENTF90 (COPY_F77_ARGW, copy_f77_argw)
Copy argument if necessary.
void ENTF90 (COPY_F77_ARGL, copy_f77_argl)
Copy argument if necessary.
void (char *ab, F90_Desc *ad, char *afirst, char **db_ptr, int *copy_in, int *len)
Copy argument if necessary.
static void init_unassociated_pointer_desc (F90_Desc *d)
void (char **ab, F90_Desc *ad, char **db, F90_Desc *dd, int *copy_in)
Copy argument if necessary.
void ENTF90 (COPY_F90_ARGL, copy_f90_argl)
Copy argument if necessary.
int ENTF90 (CONFORMABLE_DD, conformable_dd)
int ENTF90 (CONFORMABLE_DN, conformable_dn)
int ENTF90 (CONFORMABLE_D1V, conformable_d1v)
int ENTF90 (CONFORMABLE_D2V, conformable_d2v)
int ENTF90 (CONFORMABLE_D3V, conformable_d3v)
int ENTF90 (CONFORMABLE_DNV, conformable_dnv)
int ENTF90 (CONFORMABLE_ND, conformable_nd)
int ENTF90 (CONFORMABLE_1DV, conformable_1dv)
int ENTF90 (CONFORMABLE_2DV, conformable_2dv)
int ENTF90 (CONFORMABLE_3DV, conformable_3dv)
int ENTF90 (CONFORMABLE_NDV, conformable_ndv)
int ENTF90 (CONFORMABLE_NN, conformable_nn)
int ENTF90 (CONFORMABLE_11V, conformable_11v)
int ENTF90 (CONFORMABLE_22V, conformable_22v)
int ENTF90 (CONFORMABLE_33V, conformable_33v)
int ENTF90 (CONFORMABLE_NNV, conformable_nnv)
__INT_T ENTF90 (IS_CONTIGUOUS, is_contiguous)
void ENTF90 (CONTIGERROR, contigerror)
Print a contiguous error message and abort.
void ENTF90 (CONTIGCHK, contigchk)
Check whether a pointer is associated with a contiguous array object.
void ENTF90 (EXECCMDLINE, execcmdline)
Execute a command line.
static void store_int_kind (void *b, __INT_T *int_kind, int v)
static void ftn_msgcpy (char *statmsg, const char *msg, int len)
Copy msg string to statmsg and padding with blank space at the end.
Detailed Description
Data redistribution routines.
Definition in file rdst.c.
Macro Definition Documentation
EXPAND
#define EXPAND 0x080
Definition at line 262 of file rdst.c.
REALIGN
#define REALIGN 0x008
Definition at line 258 of file rdst.c.
RECOPY
#define RECOPY 0x100
Definition at line 263 of file rdst.c.
REDESCRIBE
#define REDESCRIBE 0x001
Definition at line 255 of file rdst.c.
REFORMAT
#define REFORMAT 0x004
Definition at line 257 of file rdst.c.
RELOCATE
#define RELOCATE 0x010
Definition at line 259 of file rdst.c.
RETARGET
#define RETARGET 0x002
Definition at line 256 of file rdst.c.
SHRINK
#define SHRINK 0x040
Definition at line 261 of file rdst.c.
SQUEEZE
#define SQUEEZE 0x020
Definition at line 260 of file rdst.c.
TEMPLATE
#define TEMPLATE (dd, i, lb, ub, lbase, gsize)
Value:
  {                                                                            \
    __INT_T __extent, u, l;                                                    \
    DECL_DIM_PTRS(_dd);                                                        \
    SET_DIM_PTRS(_dd, dd, i - 1);                                              \
    l = lb;                                                                    \
    u = ub;                                                                    \
    if (u >= l) {                                                              \
      __extent = u - l + 1;                                                    \
    } else {                                                                   \
      __extent = 0;                                                            \
      u = l - 1;                                                               \
    }                                                                          \
    F90_DPTR_LBOUND_P(_dd, l);                                                 \
    DPTR_UBOUND_P(_dd, u);                                                     \
    F90_DPTR_SSTRIDE_P(_dd, 1);                                                \
    F90_DPTR_SOFFSET_P(_dd, 0);                                                \
    lbase -= gsize * l;                                                        \
    F90_DPTR_LSTRIDE_P(_dd, gsize);                                            \
    gsize *= __extent;                                                         \
  }
Definition at line 1269 of file rdst.c.
Enumeration Type Documentation
copy_dir
enum copy_dir
Enumerator
__COPY_IN
__COPY_OUT
Definition at line 150 of file rdst.c.
Function Documentation
__fort_copy_out()
void I8() __fort_copy_out (void * ab, void * db, F90_Desc * ad, F90_Desc * dd, __INT_T flags)
Parameters
ab actual base address
db dummy base address
ad actual descriptor
dd dummy descriptor
Definition at line 787 of file rdst.c.
References __COPY_OUT, __DESC, __DIST_INIT_DESCRIPTOR, __DIST_SET_DISTRIBUTION, __fort_cycle_bounds(), __fort_finish_descriptor(), __fort_local_deallocate(), __fort_test, __IN, __INTENT_MASK, __INTENT_SHIFT, __NO_OVERLAPS, __NOT_COPIED, __SEQUENCE, __TEMPLATE, c, db(), DEBUG_RDST, DECL_HDR_PTRS, DECL_HDR_VARS, DIST_ALIGN_TARGET_G, DIST_DIST_TARGET_G, F90_DIM_EXTENT_G, F90_FLAGS_G, F90_FLAGS_P, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, flags, GET_DIST_LCPU, i, I8, intent, ISPRESENT, local_copy(), MAXDIMS, and NULL.
Referenced by __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), ENTFTN(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
copy_in_abort()
static void copy_in_abort (const char * msg) static
Definition at line 278 of file rdst.c.
References __fort_abort(), msg(), and str.
Referenced by ENTFTN().
ENTF90() [1/31]
int ENTF90 (CONFORMABLE_11V , conformable_11v)
Definition at line 2598 of file rdst.c.
References __fort_allocated(), conformable(), db(), and I8.
ENTF90() [2/31]
int ENTF90 (CONFORMABLE_1DV , conformable_1dv)
Definition at line 2446 of file rdst.c.
References __fort_allocated(), conformable(), db(), F90_DIM_EXTENT_G, F90_GSIZE_G, and I8.
ENTF90() [3/31]
int ENTF90 (CONFORMABLE_22V , conformable_22v)
Definition at line 2619 of file rdst.c.
References __fort_allocated(), conformable(), db(), and I8.
ENTF90() [4/31]
int ENTF90 (CONFORMABLE_2DV , conformable_2dv)
Definition at line 2467 of file rdst.c.
References __fort_allocated(), conformable(), db(), F90_DIM_EXTENT_G, F90_GSIZE_G, and I8.
ENTF90() [5/31]
int ENTF90 (CONFORMABLE_33V , conformable_33v)
Definition at line 2649 of file rdst.c.
References __fort_allocated(), conformable(), db(), and I8.
ENTF90() [6/31]
int ENTF90 (CONFORMABLE_3DV , conformable_3dv)
Definition at line 2493 of file rdst.c.
References __fort_allocated(), conformable(), db(), F90_DIM_EXTENT_G, F90_GSIZE_G, and I8.
ENTF90() [7/31]
int ENTF90 (CONFORMABLE_D1V , conformable_d1v)
Definition at line 2298 of file rdst.c.
References __fort_allocated(), conformable(), db(), F90_DIM_EXTENT_G, F90_GSIZE_G, and I8.
ENTF90() [8/31]
int ENTF90 (CONFORMABLE_D2V , conformable_d2v)
Definition at line 2321 of file rdst.c.
References __fort_allocated(), conformable(), db(), F90_DIM_EXTENT_G, F90_GSIZE_G, and I8.
ENTF90() [9/31]
int ENTF90 (CONFORMABLE_D3V , conformable_d3v)
Definition at line 2347 of file rdst.c.
References __fort_allocated(), conformable(), db(), F90_DIM_EXTENT_G, F90_GSIZE_G, and I8.
ENTF90() [10/31]
int ENTF90 (CONFORMABLE_DD , conformable_dd)
Definition at line 2234 of file rdst.c.
References __fort_allocated(), conformable(), db(), F90_DIM_EXTENT_G, F90_GSIZE_G, F90_RANK_G, i, I8, and ndim.
ENTF90() [11/31]
int ENTF90 (CONFORMABLE_DN , conformable_dn)
Definition at line 2263 of file rdst.c.
References __fort_allocated(), conformable(), db(), F90_DIM_EXTENT_G, F90_GSIZE_G, i, I8, ndim, and va.
ENTF90() [12/31]
int ENTF90 (CONFORMABLE_DNV , conformable_dnv)
Definition at line 2375 of file rdst.c.
References __fort_allocated(), conformable(), db(), F90_DIM_EXTENT_G, F90_GSIZE_G, i, I8, ndim, and va.
ENTF90() [13/31]
int ENTF90 (CONFORMABLE_ND , conformable_nd)
Definition at line 2411 of file rdst.c.
References __fort_allocated(), conformable(), db(), F90_DIM_EXTENT_G, F90_GSIZE_G, i, I8, ndim, and va.
ENTF90() [14/31]
int ENTF90 (CONFORMABLE_NDV , conformable_ndv)
Definition at line 2521 of file rdst.c.
References __fort_allocated(), conformable(), db(), F90_DIM_EXTENT_G, F90_GSIZE_G, i, I8, ndim, and va.
ENTF90() [15/31]
int ENTF90 (CONFORMABLE_NN , conformable_nn)
Definition at line 2557 of file rdst.c.
References __fort_allocated(), conformable(), db(), i, I8, ndim, and va.
ENTF90() [16/31]
int ENTF90 (CONFORMABLE_NNV , conformable_nnv)
Definition at line 2682 of file rdst.c.
References __fort_allocated(), conformable(), db(), i, I8, ndim, and va.
ENTF90() [17/31]
void ENTF90 (CONTIGCHK , contigchk)
Check whether a pointer is associated with a contiguous array object.
If the pointer is not associated with a contiguous array object, then a message is printed to stderr and the user program aborts.
Parameters
ptr is the pointer we are checking.
pd is the descriptor we are checking.
lineno is the source line number we are checking.
ptrnam is the name of pointer, null-terminated string.
srcfil is the name of source file, null-terminated string.
flags is currently 1 when ptr is an optional argument, else 0.
Definition at line 2774 of file rdst.c.
References ENTF90(), flags, lineno, NULL, and pd.
ENTF90() [18/31]
void ENTF90 (CONTIGERROR , contigerror)
Print a contiguous error message and abort.
This function will also call is_nonsequential_section() to get the first dimension of the array that is non-contiguous and include it in the error message.
Parameters
ptr is the pointer we are checking.
pd is the descriptor we are checking.
lineno is the source line number we are checking.
ptrnam is the name of pointer, null-terminated string.
srcfil is the name of source file, null-terminated string.
flags is currently 1 when ptr is an optional argument, else 0.
Definition at line 2744 of file rdst.c.
References __fort_abort(), dim, F90_RANK_G, flags, I8, is_nonsequential_section(), lineno, NULL, pd, and str.
ENTF90() [19/31]
void ENTF90 (COPY_F77_ARG , copy_f77_arg)
Definition at line 1717 of file rdst.c.
References __COPY_IN, __COPY_OUT, __DIST_INIT_DESCRIPTOR, __fort_alloc(), __fort_dealloc(), __fort_finish_descriptor(), __fort_gfree(), __fort_malloc_without_abort(), __SEQUENTIAL_SECTION, add(), c, DECL_DIM_PTRS, DECL_HDR_PTRS, DECL_HDR_VARS, DPTR_UBOUND_P, extent(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_P, F90_DPTR_SOFFSET_P, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_GBASE_G, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, i, I8, local_copy(), NULL, SET_DIM_PTRS, and void().
ENTF90() [20/31]
void ENTF90 (COPY_F77_ARGL , copy_f77_argl)
Copy argument if necessary.
when passing a pointer array section to F77 dummy, if we don't know whether it is sequential (contiguous), call this routine; this is the same as the one above, but this one works the previous routine should vanish in the next release copy_in == 1 means copy-in copy_in == 0 means copy-out intent(inout) copy_in == 2 means copy-out intent(out), no need to copy values
Definition at line 1862 of file rdst.c.
References __COPY_IN, __COPY_OUT, __DIST_INIT_DESCRIPTOR, __fort_alloc(), __fort_dealloc(), __fort_finish_descriptor(), __fort_gfree(), __fort_malloc_without_abort(), __SEQUENTIAL_SECTION, add(), c, DECL_DIM_PTRS, DECL_HDR_PTRS, DECL_HDR_VARS, DPTR_UBOUND_P, extent(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_P, F90_DPTR_SOFFSET_P, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, i, I8, len, local_copy(), NULL, SET_DIM_PTRS, and void().
ENTF90() [21/31]
void ENTF90 (COPY_F77_ARGW , copy_f77_argw)
Copy argument if necessary.
when passing a pointer array section to F77 dummy, if we don't know whether it is sequential (contiguous), call this routine; this is the same as the one above, but this one works the previous routine should vanish in the next release copy_in == 1 means copy-in copy_in == 0 means copy-out intent(inout) copy_in == 2 means copy-out intent(out), no need to copy values
Definition at line 1789 of file rdst.c.
References __COPY_IN, __COPY_OUT, __DIST_INIT_DESCRIPTOR, __fort_alloc(), __fort_dealloc(), __fort_finish_descriptor(), __fort_gfree(), __fort_malloc_without_abort(), __SEQUENTIAL_SECTION, add(), c, DECL_DIM_PTRS, DECL_HDR_PTRS, DECL_HDR_VARS, DPTR_UBOUND_P, extent(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_P, F90_DPTR_SOFFSET_P, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, i, I8, local_copy(), NULL, SET_DIM_PTRS, and void().
ENTF90() [22/31]
void ENTF90 (COPY_F90_ARGL , copy_f90_argl)
Copy argument if necessary.
When passing an array section to an assumed-shape dummy argument, if we don't know the actual strides (such as with a pointer), if the leftmost dimension stride is actually one, we don't have to do a copy copy_in == 1 means copy-in copy_in == 0 means copy-out intent(inout) copy_in == 2 means copy-out intent(out), no need to copy values the len argument is to assure the 'len' matches the datatype length
Definition at line 2128 of file rdst.c.
References __COPY_IN, __COPY_OUT, __DIST_INIT_DESCRIPTOR, __fort_alloc(), __fort_dealloc(), __fort_finish_descriptor(), __fort_gfree(), __fort_malloc_without_abort(), __SEQUENTIAL_SECTION, add(), db(), DECL_DIM_PTRS, DPTR_UBOUND_P, extent(), F90_DIM_LSTRIDE_G, F90_DIM_SSTRIDE_G, F90_DIST_DESC_G, F90_DIST_DESC_P, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_G, F90_DPTR_LSTRIDE_P, F90_DPTR_SOFFSET_G, F90_DPTR_SOFFSET_P, F90_DPTR_SSTRIDE_G, F90_DPTR_SSTRIDE_P, F90_DPTR_UBOUND_G, F90_FLAGS_G, F90_FLAGS_P, F90_GBASE_G, F90_GBASE_P, F90_GSIZE_G, F90_GSIZE_P, F90_KIND_G, F90_LBASE_G, F90_LBASE_P, F90_LEN_G, F90_LSIZE_G, F90_LSIZE_P, F90_RANK_G, GET_DIST_SIZE_OF, i, I8, init_unassociated_pointer_desc(), len, local_copy(), NULL, SET_DIM_PTRS, and void().
ENTF90() [23/31]
void ENTF90 (EXECCMDLINE , execcmdline)
Execute a command line.
Parameters
command is the command to be executed.
wait controls to execute command synchronously or asynchronously.
exitstatus is the value of exit status.
cmdstat shows the status of command execution.
cmdmsg is the assigned explanatory message.
exitstat_int_kind is the integer kind for the exitstat.
cmdstat_int_kind is the integer kind for the cmdstat.
DCLEN64(command) is generated by compiler which contains the length of the command string.
DCLEN64(cmdmsg) is generated by compiler which contains the length of the cmdmsg string.
Definition at line 2802 of file rdst.c.
References __cstr_free(), __fort_abort(), __fstr2cstr(), __io_stderr(), CADR, CLEN, ftn_msgcpy(), NULL, pid, stat, store_int_kind(), and w.
ENTF90() [24/31]
__INT_T ENTF90 (IS_CONTIGUOUS , is_contiguous)
Definition at line 2723 of file rdst.c.
References F90_RANK_G, GET_DIST_TRUE_LOG, I8, and is_nonsequential_section().
ENTF90() [25/31]
void ENTF90 (TEMPLATE , template)
Optimized routine to create a template.
Varargs: { __INT_T lbound, __INT_T *ubound, }
Definition at line 1195 of file rdst.c.
References __ASSUMED_SHAPE, __ASSUMED_SIZE, __DIST_INIT_DESCRIPTOR, __fort_abort(), __fort_show_flags(), __fort_test, __NONE, DEBUG_RDST, DECL_DIM_PTRS, DIST_ALIGN_TARGET_G, DIST_DIST_TARGET_G, DPTR_UBOUND_P, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_P, F90_DPTR_SOFFSET_P, F90_DPTR_SSTRIDE_P, F90_GSIZE_P, F90_KIND_P(), F90_LBASE_P, F90_LEN_P, F90_LSIZE_P, flags, GET_DIST_LCPU, i, kind, lbase, len, NULL, p_flags, p_kind, p_len, p_rank, rank, SET_DIM_PTRS, and va.
Referenced by ENTF90().
ENTF90() [26/31]
void ENTF90 (TEMPLATE1 , template1)
Optimized routine to create a template for 1 dimension array.
Definition at line 1293 of file rdst.c.
References __ASSUMED_SHAPE, __DIST_INIT_DESCRIPTOR, __fort_abort(), __fort_show_flags(), __fort_test, __NONE, DEBUG_RDST, DIST_ALIGN_TARGET_G, DIST_DIST_TARGET_G, F90_GSIZE_P, F90_KIND_P(), F90_LBASE_P, F90_LEN_P, F90_LSIZE_P, flags, GET_DIST_LCPU, kind, lbase, len, NULL, p_flags, p_kind, p_l1, p_len, p_u1, rank, and TEMPLATE.
ENTF90() [27/31]
void ENTF90 (TEMPLATE1V , template1v)
Optimized routine to create a template from value arguments.
Definition at line 1446 of file rdst.c.
References __ASSUMED_SHAPE, __DIST_INIT_DESCRIPTOR, __fort_abort(), __fort_show_flags(), __fort_test, __NONE, DEBUG_RDST, DIST_ALIGN_TARGET_G, DIST_DIST_TARGET_G, F90_GSIZE_P, F90_KIND_P(), F90_LBASE_P, F90_LEN_P, F90_LSIZE_P, flags, GET_DIST_LCPU, kind, lbase, len, NULL, rank, and TEMPLATE.
ENTF90() [28/31]
void ENTF90 (TEMPLATE2 , template2)
Optimized routine to create a template for 2 dimesion array.
Definition at line 1342 of file rdst.c.
References __ASSUMED_SHAPE, __DIST_INIT_DESCRIPTOR, __fort_abort(), __fort_show_flags(), __fort_test, __NONE, DEBUG_RDST, DIST_ALIGN_TARGET_G, DIST_DIST_TARGET_G, F90_GSIZE_P, F90_KIND_P(), F90_LBASE_P, F90_LEN_P, F90_LSIZE_P, flags, GET_DIST_LCPU, kind, lbase, len, NULL, p_flags, p_kind, p_l1, p_l2, p_len, p_u1, p_u2, rank, and TEMPLATE.
ENTF90() [29/31]
void ENTF90 (TEMPLATE2V , template2v)
Optimized routine to create a template for 2 dim array from value arguments.
Definition at line 1493 of file rdst.c.
References __ASSUMED_SHAPE, __DIST_INIT_DESCRIPTOR, __fort_abort(), __fort_show_flags(), __fort_test, __NONE, DEBUG_RDST, DIST_ALIGN_TARGET_G, DIST_DIST_TARGET_G, F90_GSIZE_P, F90_KIND_P(), F90_LBASE_P, F90_LEN_P, F90_LSIZE_P, flags, GET_DIST_LCPU, kind, lbase, len, NULL, rank, and TEMPLATE.
ENTF90() [30/31]
void ENTF90 (TEMPLATE3 , template3)
Optimized routine to create a template for 3 dimesion array.
Definition at line 1394 of file rdst.c.
References __ASSUMED_SHAPE, __DIST_INIT_DESCRIPTOR, __fort_abort(), __fort_show_flags(), __fort_test, __NONE, DEBUG_RDST, DIST_ALIGN_TARGET_G, DIST_DIST_TARGET_G, F90_GSIZE_P, F90_KIND_P(), F90_LBASE_P, F90_LEN_P, F90_LSIZE_P, flags, GET_DIST_LCPU, kind, lbase, len, NULL, p_flags, p_kind, p_l1, p_l2, p_l3, p_len, p_u1, p_u2, p_u3, rank, and TEMPLATE.
ENTF90() [31/31]
void ENTF90 (TEMPLATE3V , template3v)
Optimized routine to create a template for 3 dim array from value arguments.
Definition at line 1542 of file rdst.c.
References __ASSUMED_SHAPE, __DIST_INIT_DESCRIPTOR, __fort_abort(), __fort_show_flags(), __fort_test, __NONE, DEBUG_RDST, DIST_ALIGN_TARGET_G, DIST_DIST_TARGET_G, F90_GSIZE_P, F90_KIND_P(), F90_LBASE_P, F90_LEN_P, F90_LSIZE_P, flags, GET_DIST_LCPU, kind, lbase, len, NULL, rank, and TEMPLATE.
ENTFTN() [1/7]
void ENTFTN (CHECK_BLOCK_SIZE , check_block_size)
Definition at line 878 of file rdst.c.
References __fort_abort(), __INT1, __INT2, __INT4, __INT8, ISSCALAR, and kind.
ENTFTN() [2/7]
void ENTFTN (COPY_OUT , copy_out)
Definition at line 868 of file rdst.c.
References __F77_LOCAL_DUMMY, __fort_copy_out(), __INTENT_SHIFT, db(), F90_FLAGS_G, F90_FLAGS_P, I8, and intent.
ENTFTN() [3/7]
void ENTFTN (FREE , free)
Definition at line 1644 of file rdst.c.
References __DESC, __DYNAMIC, __fort_abort(), __NONE, d, DECL_HDR_PTRS, DIST_ALIGN_TARGET_G, DIST_ALIGN_TARGET_P, DIST_NEXT_ALIGNEE_G, DIST_NEXT_ALIGNEE_P, F90_FLAGS_G, F90_TAG_G, F90_TAG_P, n, NULL, p, and t.
ENTFTN() [4/7]
void ENTFTN (FREEN , freen)
Definition at line 1697 of file rdst.c.
References cnt, ENTFTN(), FREE, n, and va.
ENTFTN() [5/7]
void ENTFTN (INSTANCE , instance)
Definition at line 1592 of file rdst.c.
References __DESC, __DIST_INIT_DESCRIPTOR, __fort_abort(), __fort_finish_descriptor(), __fort_set_alignment(), __fort_test, __TEMPLATE, DEBUG_RDST, DECL_DIM_PTRS, DECL_HDR_PTRS, DIST_ALIGN_TARGET_G, DIST_DIST_TARGET_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_FLAGS_G, F90_FLAGS_P, F90_KIND_P(), F90_LEN_P, F90_RANK_G, F90_TAG_G, GET_DIST_LCPU, i, I8, kind, len, NULL, p_kind, p_len, SET_DIM_PTRS, and td.
ENTFTN() [6/7]
void ENTFTN (QOPY_IN , qopy_in)
Definition at line 298 of file rdst.c.
References __ALIGN_TARGET_MASK, __ALIGN_TARGET_SHIFT, __ASSUMED_GB_EXTENT, __ASSUMED_SHAPE, __ASSUMED_SIZE, __COPY_IN, __DESC, __DESCRIPTIVE, __DIST_FORMAT_MASK, __DIST_FORMAT_SHIFT, __DIST_INIT_DESCRIPTOR, __DIST_TARGET_AXIS, __DIST_TARGET_MASK, __DIST_TARGET_SHIFT, __DUMMY_COLLAPSE_PAXIS, __fort_copy_descriptor(), __fort_describe(), __fort_finish_descriptor(), __fort_local_allocate(), __fort_local_offset(), __fort_ptr_aligned(), __fort_ptr_offset(), __fort_show_flags(), __fort_test, __fort_tracecall(), __IDENTITY_MAP, __INTENT_MASK, __INTENT_SHIFT, __LOCAL, __NO_OVERLAPS, __NOT_COPIED, __OFF_TEMPLATE, __OUT, __PRESCRIPTIVE, __SEQUENCE, __TEMPLATE, add(), c, collapse, copy_in_abort(), db(), DEBUG_COPYIN_LOCAL, DEBUG_RDST, DECL_DIM_PTRS, DECL_HDR_PTRS, DECL_HDR_VARS, df, DPTR_UBOUND_P, EXPAND, EXTENSION_BLOCK_MASK, F90_DIM_EXTENT_G, F90_DIM_LBOUND_G, F90_DIM_SOFFSET_G, F90_DIM_SOFFSET_P, F90_DPTR_LBOUND_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_G, F90_DPTR_LSTRIDE_P, F90_DPTR_SOFFSET_P, F90_DPTR_SSTRIDE_G, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_FLAGS_P, F90_GSIZE_G, F90_KIND_G, F90_LBASE_G, F90_LBASE_P, F90_LEN_G, F90_LSIZE_G, F90_RANK_G, F90_TAG_G, flags, GET_DIST_LCPU, GET_DIST_TYPENAMES, i, I8, idx, intent, is_nonsequential_section(), ISPRESENT, ISSCALAR, ISSEQUENCE, kind, len, local_copy(), LOCAL_MODE, m, MAXDIMS, n, NULL, p_flags, p_kind, p_len, p_rank, rank, REALIGN, RECOPY, REDESCRIBE, REFORMAT, RELOCATE, RETARGET, SET_DIM_PTRS, SHRINK, SQUEEZE, va, and void().
ENTFTN() [7/7]
void ENTFTN (TEMPLATE , template)
Definition at line 19 of file rdst.c.
Referenced by ENTFTN().
ftn_msgcpy()
static void ftn_msgcpy (char * statmsg, const char * msg, int len) static
Copy msg string to statmsg and padding with blank space at the end.
Parameters
statmsg is the Fortran string we want to assign values.
msg is the string contains error message.
len is the length of statmsg.
Definition at line 2943 of file rdst.c.
References i, len, and msg().
Referenced by ENTF90().
init_unassociated_pointer_desc()
static void init_unassociated_pointer_desc (F90_Desc * d) static
Definition at line 2000 of file rdst.c.
References __DIST_INIT_DESCRIPTOR, d, F90_DIM_EXTENT_P, F90_DIM_LBOUND_P, F90_DIM_LSTRIDE_P, F90_DIM_SOFFSET_P, and F90_DIM_SSTRIDE_P.
Referenced by ENTF90(), and void().
is_nonsequential_section()
__INT_T I8() is_nonsequential_section (F90_Desc * a, __INT_T dim)
check if a descriptor is associated with a non-contiguous section.
Parameters
a is the descriptor we are checking.
dim is the rank of the array we are checking.
Returns
0 if contiguous, else the dimension that is non-contiguous.
Definition at line 231 of file rdst.c.
References a, DECL_DIM_PTRS, dim, F90_DPTR_EXTENT_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, i, and SET_DIM_PTRS.
Referenced by __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), ENTF90(), ENTFTN(), mmul_mxm(), mmul_mxv(), and mmul_vxm().
local_copy()
static void I8() local_copy (char * db, F90_Desc * dd, __INT_T doffset, char * ab, F90_Desc * ad, __INT_T aoffset, __INT_T dim, copy_dir dir) static
copy local data between global actual array and local dummy array
Definition at line 154 of file rdst.c.
References __COPY_IN, __fort_bcopysl(), __fort_block_bounds(), add(), cl, db(), DECL_DIM_PTRS, dim, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, dlen(), F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_LEN_G, I8, local_copy(), n, and SET_DIM_PTRS.
Referenced by __fort_copy_out(), ENTF90(), ENTFTN(), local_copy(), and void().
store_int_kind()
static void store_int_kind (void * b, __INT_T * int_kind, int v) static
Definition at line 2915 of file rdst.c.
References __fort_abort(), and b.
Referenced by ENTF90().
void() [1/4]
void (char ** ab, F90_Desc * ad, char ** db, F90_Desc * dd, int * copy_in)
Copy argument if necessary.
when passing an array section to an assumed-shape dummy argument, if we don't know the actual strides (such as with a pointer), if the leftmost dimension stride is actually one, we don't have to do a copy copy_in == 1 means copy-in copy_in == 0 means copy-out intent(inout) copy_in == 2 means copy-out intent(out), no need to copy values
Definition at line 2019 of file rdst.c.
References __COPY_IN, __COPY_OUT, __DIST_INIT_DESCRIPTOR, __fort_alloc(), __fort_dealloc(), __fort_finish_descriptor(), __fort_gfree(), __fort_malloc_without_abort(), __SEQUENTIAL_SECTION, add(), db(), DECL_DIM_PTRS, DPTR_UBOUND_P, extent(), F90_DIM_LSTRIDE_G, F90_DIM_SSTRIDE_G, F90_DIST_DESC_G, F90_DIST_DESC_P, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_G, F90_DPTR_LSTRIDE_P, F90_DPTR_SOFFSET_G, F90_DPTR_SOFFSET_P, F90_DPTR_SSTRIDE_G, F90_DPTR_SSTRIDE_P, F90_DPTR_UBOUND_G, F90_FLAGS_G, F90_FLAGS_P, F90_GBASE_G, F90_GBASE_P, F90_GSIZE_G, F90_GSIZE_P, F90_KIND_G, F90_LBASE_G, F90_LBASE_P, F90_LEN_G, F90_LSIZE_G, F90_LSIZE_P, F90_RANK_G, GET_DIST_SIZE_OF, i, I8, init_unassociated_pointer_desc(), local_copy(), NULL, SET_DIM_PTRS, and void().
void() [2/4]
void (char * ab, char * ad, char ** addr)
Definition at line 1708 of file rdst.c.
References addr.
void() [3/4]
void (char * ab, F90_Desc * ad, char * afirst, char ** db_ptr, int * copy_in, int * len)
Copy argument if necessary.
when passing an assumed-shape array section to F77 dummy, we don't know whether it is sequential (contiguous) (we only know leftmost dimension is stride-1), call this routine; this is almost the same as the one above copy_in == 1 means copy-in copy_in == 0 means copy-out intent(inout) copy_in == 2 means copy-out intent(out), no need to copy values
Definition at line 1934 of file rdst.c.
References __COPY_IN, __COPY_OUT, __DIST_INIT_DESCRIPTOR, __fort_alloc(), __fort_dealloc(), __fort_finish_descriptor(), __fort_gfree(), __fort_malloc_without_abort(), __SEQUENTIAL_SECTION, add(), c, DECL_DIM_PTRS, DECL_HDR_PTRS, DECL_HDR_VARS, DPTR_UBOUND_P, extent(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_P, F90_DPTR_SOFFSET_P, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_KIND_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, i, I8, len, local_copy(), NULL, SET_DIM_PTRS, and void().
void() [4/4]
void (F90_Desc * dd, __INT_T * p_rank, __INT_T * p_flags, ...)
General routine to create a template (alignment or distribution) descriptor.
  Varargs: [ [ proc *dist_target, ]
             __INT_T *isstar,
             { [__INT_T paxis, ] ( __INT_T *dstfmt, | __INT_T * genBlockArray,
               __INT_T * genBlockArrayExtent,) }* ]
           [ F90_Desc *align_target, __INT_T *conform,
             [ __INT_T *collapse,
               { __INT_T *taxis, __INT_T *tstride, __INT_T *toffset, }*
               __INT_T *single,
               { __INT_T *coordinate, }* ] ]
           { __INT_T *lbound, __INT_T *ubound, }*
*
Definition at line 942 of file rdst.c.
References __ALIGN_TARGET_MASK, __ALIGN_TARGET_SHIFT, __ASSUMED_GB_EXTENT, __ASSUMED_SHAPE, __ASSUMED_SIZE, __DESC, __DESCRIPTIVE, __DIST_FORMAT_MASK, __DIST_FORMAT_SHIFT, __DIST_INIT_DESCRIPTOR, __DIST_SET_DISTRIBUTION, __DIST_TARGET_AXIS, __DIST_TARGET_MASK, __DIST_TARGET_SHIFT, __DUMMY_COLLAPSE_PAXIS, __fort_abort(), __fort_localproc(), __fort_set_alignment(), __fort_show_flags(), __fort_test, __IDENTITY_MAP, __INHERIT, __LOCAL, __NONE, __OMITTED, __PRESCRIPTIVE, __PROC, __TRANSCRIPTIVE, collapse, DEBUG_RDST, DECL_DIM_PTRS, DECL_HDR_PTRS, DIST_ALIGN_TARGET_G, DIST_DIST_TARGET_G, EXTENSION_BLOCK_MASK, F90_DPTR_EXTENT_G, F90_RANK_G, F90_TAG_G, flags, GET_DIST_LCPU, i, I8, LOCAL_MODE, m, MAXDIMS, NULL, p_flags, p_rank, rank, SET_DIM_PTRS, proc::tag, td, and va.
Referenced by ENTF90(), ENTFTN(), and void().