flang: red_sum.c File Reference
red_sum.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "red.h"
Macros
#define CSUMFNL(NAME, RTYP, ATYP)
#define CSUMFNG(NAME, RTYP, ATYP)
#define CSUMFNLKN(NAME, RTYP, ATYP, N)
Functions
void ENTFTN (SUMS, sums)
void ENTFTN (SUM, sum)
void ENTFTN (REDUCE_SUM, reduce_sum)
void ENTFTN (GLOBAL_SUM, global_sum)
Variables
static void(* l_sum [4][__NTYPES])() = TYPELIST1LK(l_sum_)
void(*)() I8 (__fort_g_sum)[__NTYPES] (g_sum_)
Macro Definition Documentation
CSUMFNG
#define CSUMFNG (NAME, RTYP, ATYP)
Value:
  static void g_##NAME(__INT_T n, RTYP *lr, RTYP *rr, void *lv, void *rv)      \
  {                                                                            \
    __INT_T i;                                                                 \
    for (i = 0; i < n; i++) {                                                  \
      lr[i].r += rr[i].r;                                                      \
      lr[i].i += rr[i].i;                                                      \
    }                                                                          \
  }
Definition at line 40 of file red_sum.c.
CSUMFNL
#define CSUMFNL (NAME, RTYP, ATYP)
Value:
  static void l_##NAME(RTYP *r, __INT_T n, RTYP *v, __INT_T vs, __LOG_T *m,    \
                       __INT_T ms, __INT_T *loc, __INT_T li, __INT_T ls)       \
  {                                                                            \
    __INT_T i, j;                                                              \
    ATYP xr = r->r, xi = r->i;                                                 \
    __LOG_T mask_log;                                                          \
    if (ms == 0)                                                               \
      for (i = 0; n > 0; n--, i += vs) {                                       \
        xr += v[i].r;                                                          \
        xi += v[i].i;                                                          \
      }                                                                        \
    else {                                                                     \
      mask_log = GET_DIST_MASK_LOG;                                           \
      for (i = j = 0; n > 0; n--, i += vs, j += ms)                            \
        if (m[j] & mask_log) {                                                 \
          xr += v[i].r;                                                        \
          xi += v[i].i;                                                        \
        }                                                                      \
    }                                                                          \
    r->r = xr;                                                                 \
    r->i = xi;                                                                 \
  }
Definition at line 16 of file red_sum.c.
CSUMFNLKN
#define CSUMFNLKN (NAME, RTYP, ATYP, N)
Value:
  static void l_##NAME##l##N(RTYP *r, __INT_T n, RTYP *v, __INT_T vs,          \
                             __LOG##N##_T *m, __INT_T ms, __INT_T *loc,        \
                             __INT_T li, __INT_T ls)                           \
  {                                                                            \
    __INT_T i, j;                                                              \
    ATYP xr = r->r, xi = r->i;                                                 \
    __LOG##N##_T mask_log;                                                     \
    if (ms == 0)                                                               \
      for (i = 0; n > 0; n--, i += vs) {                                       \
        xr += v[i].r;                                                          \
        xi += v[i].i;                                                          \
      }                                                                        \
    else {                                                                     \
      mask_log = GET_DIST_MASK_LOG##N;                                        \
      for (i = j = 0; n > 0; n--, i += vs, j += ms)                            \
        if (m[j] & mask_log) {                                                 \
          xr += v[i].r;                                                        \
          xi += v[i].i;                                                        \
        }                                                                      \
    }                                                                          \
    r->r = xr;                                                                 \
    r->i = xi;                                                                 \
  }
Definition at line 50 of file red_sum.c.
Function Documentation
ENTFTN() [1/4]
void ENTFTN (GLOBAL_SUM , global_sum)
Definition at line 208 of file red_sum.c.
References __fort_global_reduce(), I8, and rb.
ENTFTN() [2/4]
void ENTFTN (REDUCE_SUM , reduce_sum)
Definition at line 192 of file red_sum.c.
References __fort_abort(), __fort_global_reduce(), __INT, I8, NULL, and rb.
ENTFTN() [3/4]
void ENTFTN (SUM , sum)
Definition at line 159 of file red_sum.c.
References __DESC, __fort_create_conforming_mask_array(), __fort_gfree(), __fort_red_array(), __fort_red_what, __LOG, __SUM, db(), DECL_HDR_VARS, ds(), F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_SHIFTS, GET_DIST_ZED, I8, INIT_RED_PARM, ISSCALAR, l_sum, rb, and z.
ENTFTN() [4/4]
void ENTFTN (SUMS , sums)
Definition at line 135 of file red_sum.c.
References __DESC, __fort_red_scalar(), __fort_red_what, __LOG, __SUM, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_SHIFTS, GET_DIST_ZED, I8, INIT_RED_PARM, l_sum, NULL, rb, and z.
Variable Documentation
(__fort_g_sum)[__NTYPES]
void(*)() I8 (__fort_g_sum)[__NTYPES](g_sum_) (__fort_g_sum)
Definition at line 131 of file red_sum.c.
l_sum
void(* l_sum[4][__NTYPES])() () = TYPELIST1LK(l_sum_) static
Definition at line 130 of file red_sum.c.
Referenced by ENTFTN().