flang: red_maxloc.c File Reference
red_maxloc.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "red.h"
Functions
static void maxlocs_common (red_parm *z, __INT_T *rb, char *ab, char *mb, F90_Desc *rs, F90_Desc *as, F90_Desc *ms)
void ENTFTN (MAXLOCS, maxlocs)
void ENTFTN (MAXLOCS_B, maxlocs_b)
static void maxloc_common (red_parm *z, char *rb, char *ab, char *mb, char *db, F90_Desc *rs, F90_Desc *as, F90_Desc *ms, F90_Desc *ds)
void ENTFTN (MAXLOC, maxloc)
void ENTFTN (MAXLOC_B, maxloc_b)
static void kmaxlocs_common (red_parm *z, __INT8_T *rb, char *ab, char *mb, F90_Desc *rs, F90_Desc *as, F90_Desc *ms)
void ENTFTN (KMAXLOCS, kmaxlocs)
void ENTFTN (KMAXLOCS_B, kmaxlocs_b)
static void kmaxloc_common (red_parm *z, char *rb, char *ab, char *mb, char *db, F90_Desc *rs, F90_Desc *as, F90_Desc *ms, F90_Desc *ds)
void ENTFTN (KMAXLOC, kmaxloc)
void ENTFTN (KMAXLOC_B, kmaxloc_b)
Variables
static void(* l_maxloc_b [4][__NTYPES])() = TYPELIST3LK(l_maxloc_)
static void(* g_maxloc [__NTYPES])() = TYPELIST3(g_maxloc_)
static void(* l_kmaxloc_b [4][__NTYPES])() = TYPELIST3LK(l_kmaxloc_)
static void(* g_kmaxloc [__NTYPES])() = TYPELIST3(g_kmaxloc_)
Function Documentation
ENTFTN() [1/8]
void ENTFTN (KMAXLOC , kmaxloc)
Definition at line 306 of file red_maxloc.c.
References db(), ds(), INIT_RED_PARM, kmaxloc_common(), rb, and z.
ENTFTN() [2/8]
void ENTFTN (KMAXLOC_B , kmaxloc_b)
Definition at line 317 of file red_maxloc.c.
References db(), ds(), INIT_RED_PARM, kmaxloc_common(), rb, and z.
ENTFTN() [3/8]
void ENTFTN (KMAXLOCS , kmaxlocs)
Definition at line 249 of file red_maxloc.c.
References __fort_red_what, INIT_RED_PARM, kmaxlocs_common(), rb, and z.
ENTFTN() [4/8]
void ENTFTN (KMAXLOCS_B , kmaxlocs_b)
Definition at line 260 of file red_maxloc.c.
References __fort_red_what, INIT_RED_PARM, kmaxlocs_common(), rb, and z.
ENTFTN() [5/8]
void ENTFTN (MAXLOC , maxloc)
Definition at line 199 of file red_maxloc.c.
References db(), ds(), INIT_RED_PARM, maxloc_common(), rb, and z.
ENTFTN() [6/8]
void ENTFTN (MAXLOC_B , maxloc_b)
Definition at line 209 of file red_maxloc.c.
References db(), ds(), INIT_RED_PARM, maxloc_common(), rb, and z.
ENTFTN() [7/8]
void ENTFTN (MAXLOCS , maxlocs)
Definition at line 145 of file red_maxloc.c.
References INIT_RED_PARM, maxlocs_common(), rb, and z.
ENTFTN() [8/8]
void ENTFTN (MAXLOCS_B , maxlocs_b)
Definition at line 156 of file red_maxloc.c.
References INIT_RED_PARM, maxlocs_common(), rb, and z.
kmaxloc_common()
static void kmaxloc_common (red_parm * z, char * rb, char * ab, char * mb, char * db, F90_Desc * rs, F90_Desc * as, F90_Desc * ms, F90_Desc * ds) static
Definition at line 274 of file red_maxloc.c.
References __DESC, __fort_create_conforming_mask_array(), __fort_gfree(), __fort_kred_arraylk(), __fort_red_array(), __fort_red_what, __LOG, __MAXLOC, __STR, db(), DECL_HDR_VARS, ds(), F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_kmaxloc, GET_DIST_MINS, GET_DIST_SHIFTS, I8, ISSCALAR, l_kmaxloc_b, rb, and z.
Referenced by ENTFTN().
kmaxlocs_common()
static void kmaxlocs_common (red_parm * z, __INT8_T * rb, char * ab, char * mb, F90_Desc * rs, F90_Desc * as, F90_Desc * ms) static
Definition at line 221 of file red_maxloc.c.
References __DESC, __fort_gfree(), __fort_gmalloc(), __fort_kred_scalarlk(), __LOG, __MAXLOC, __STR, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_kmaxloc, GET_DIST_MINS, GET_DIST_SHIFTS, I8, l_kmaxloc_b, rb, and z.
Referenced by ENTFTN().
maxloc_common()
static void maxloc_common (red_parm * z, char * rb, char * ab, char * mb, char * db, F90_Desc * rs, F90_Desc * as, F90_Desc * ms, F90_Desc * ds) static
Definition at line 169 of file red_maxloc.c.
References __DESC, __fort_create_conforming_mask_array(), __fort_gfree(), __fort_red_array(), __fort_red_arraylk(), __fort_red_what, __LOG, __MAXLOC, __STR, db(), DECL_HDR_VARS, ds(), F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_maxloc, GET_DIST_MINS, GET_DIST_SHIFTS, I8, ISSCALAR, l_maxloc_b, rb, and z.
Referenced by ENTFTN().
maxlocs_common()
static void maxlocs_common (red_parm * z, __INT_T * rb, char * ab, char * mb, F90_Desc * rs, F90_Desc * as, F90_Desc * ms) static
Definition at line 115 of file red_maxloc.c.
References __DESC, __fort_gfree(), __fort_gmalloc(), __fort_red_scalarlk(), __fort_red_what, __LOG, __MAXLOC, __STR, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_maxloc, GET_DIST_MINS, GET_DIST_SHIFTS, I8, l_maxloc_b, rb, and z.
Referenced by ENTFTN().
Variable Documentation
g_kmaxloc
void(* g_kmaxloc[__NTYPES])() () = TYPELIST3(g_kmaxloc_) static
Definition at line 110 of file red_maxloc.c.
Referenced by kmaxloc_common(), and kmaxlocs_common().
g_maxloc
void(* g_maxloc[__NTYPES])() () = TYPELIST3(g_maxloc_) static
Definition at line 62 of file red_maxloc.c.
Referenced by maxloc_common(), and maxlocs_common().
l_kmaxloc_b
void(* l_kmaxloc_b[4][__NTYPES])() () = TYPELIST3LK(l_kmaxloc_) static
Definition at line 109 of file red_maxloc.c.
Referenced by kmaxloc_common(), and kmaxlocs_common().
l_maxloc_b
void(* l_maxloc_b[4][__NTYPES])() () = TYPELIST3LK(l_maxloc_) static
Definition at line 61 of file red_maxloc.c.
Referenced by maxloc_common(), and maxlocs_common().