flang: red_minloc.c File Reference
red_minloc.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "red.h"
#include <string.h>
Functions
static void minlocs_common (red_parm *z, __INT_T *rb, char *ab, char *mb, F90_Desc *rs, F90_Desc *as, F90_Desc *ms)
void ENTFTN (MINLOCS, minlocs)
void ENTFTN (MINLOCS_B, minlocs_b)
static void minloc_common (red_parm *z, char *rb, char *ab, char *mb, char *db, F90_Desc *rs, F90_Desc *as, F90_Desc *ms, F90_Desc *ds)
void ENTFTN (MINLOC, minloc)
void ENTFTN (MINLOC_B, minloc_b)
static void kminlocs_common (red_parm *z, __INT8_T *rb, char *ab, char *mb, F90_Desc *rs, F90_Desc *as, F90_Desc *ms)
void ENTFTN (KMINLOCS, kminlocs)
void ENTFTN (KMINLOCS_B, kminlocs_b)
static void kminloc_common (red_parm *z, char *rb, char *ab, char *mb, char *db, F90_Desc *rs, F90_Desc *as, F90_Desc *ms, F90_Desc *ds)
void ENTFTN (KMINLOC, kminloc)
void ENTFTN (KMINLOC_B, kminloc_b)
Variables
static void(* l_minloc_b [4][__NTYPES])() = TYPELIST3LK(l_minloc_)
static void(* g_minloc [__NTYPES])() = TYPELIST3(g_minloc_)
static void(* l_kminloc_b [4][__NTYPES])() = TYPELIST3LK(l_kminloc_)
static void(* g_kminloc [__NTYPES])() = TYPELIST3(g_kminloc_)
Function Documentation
ENTFTN() [1/8]
void ENTFTN (KMINLOC , kminloc)
Definition at line 304 of file red_minloc.c.
References db(), ds(), INIT_RED_PARM, kminloc_common(), rb, and z.
ENTFTN() [2/8]
void ENTFTN (KMINLOC_B , kminloc_b)
Definition at line 314 of file red_minloc.c.
References db(), ds(), INIT_RED_PARM, kminloc_common(), rb, and z.
ENTFTN() [3/8]
void ENTFTN (KMINLOCS , kminlocs)
Definition at line 251 of file red_minloc.c.
References INIT_RED_PARM, kminlocs_common(), rb, and z.
ENTFTN() [4/8]
void ENTFTN (KMINLOCS_B , kminlocs_b)
Definition at line 260 of file red_minloc.c.
References INIT_RED_PARM, kminlocs_common(), rb, and z.
ENTFTN() [5/8]
void ENTFTN (MINLOC , minloc)
Definition at line 199 of file red_minloc.c.
References db(), ds(), INIT_RED_PARM, minloc_common(), rb, and z.
ENTFTN() [6/8]
void ENTFTN (MINLOC_B , minloc_b)
Definition at line 209 of file red_minloc.c.
References db(), ds(), INIT_RED_PARM, minloc_common(), rb, and z.
ENTFTN() [7/8]
void ENTFTN (MINLOCS , minlocs)
Definition at line 144 of file red_minloc.c.
References INIT_RED_PARM, minlocs_common(), rb, and z.
ENTFTN() [8/8]
void ENTFTN (MINLOCS_B , minlocs_b)
Definition at line 154 of file red_minloc.c.
References INIT_RED_PARM, minlocs_common(), rb, and z.
kminloc_common()
static void kminloc_common (red_parm * z, char * rb, char * ab, char * mb, char * db, F90_Desc * rs, F90_Desc * as, F90_Desc * ms, F90_Desc * ds) static
Definition at line 272 of file red_minloc.c.
References __DESC, __fort_create_conforming_mask_array(), __fort_gfree(), __fort_kred_arraylk(), __fort_red_array(), __fort_red_what, __LOG, __MINLOC, __STR, db(), DECL_HDR_VARS, ds(), F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_kminloc, GET_DIST_MAXS, GET_DIST_SHIFTS, I8, ISSCALAR, l_kminloc_b, rb, and z.
Referenced by ENTFTN().
kminlocs_common()
static void kminlocs_common (red_parm * z, __INT8_T * rb, char * ab, char * mb, F90_Desc * rs, F90_Desc * as, F90_Desc * ms) static
Definition at line 221 of file red_minloc.c.
References __DESC, __fort_gfree(), __fort_gmalloc(), __fort_kred_scalarlk(), __fort_red_what, __LOG, __MINLOC, __STR, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_kminloc, GET_DIST_MAXS, GET_DIST_SHIFTS, I8, l_kminloc_b, rb, and z.
Referenced by ENTFTN().
minloc_common()
static void minloc_common (red_parm * z, char * rb, char * ab, char * mb, char * db, F90_Desc * rs, F90_Desc * as, F90_Desc * ms, F90_Desc * ds) static
Definition at line 167 of file red_minloc.c.
References __DESC, __fort_create_conforming_mask_array(), __fort_gfree(), __fort_red_array(), __fort_red_arraylk(), __fort_red_what, __LOG, __MINLOC, __STR, db(), DECL_HDR_VARS, ds(), F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_minloc, GET_DIST_MAXS, GET_DIST_SHIFTS, I8, ISSCALAR, l_minloc_b, rb, and z.
Referenced by ENTFTN().
minlocs_common()
static void minlocs_common (red_parm * z, __INT_T * rb, char * ab, char * mb, F90_Desc * rs, F90_Desc * as, F90_Desc * ms) static
Definition at line 114 of file red_minloc.c.
References __DESC, __fort_gfree(), __fort_gmalloc(), __fort_red_scalarlk(), __fort_red_what, __LOG, __MINLOC, __STR, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_minloc, GET_DIST_MAXS, GET_DIST_SHIFTS, I8, l_minloc_b, rb, and z.
Referenced by ENTFTN().
Variable Documentation
g_kminloc
void(* g_kminloc[__NTYPES])() () = TYPELIST3(g_kminloc_) static
Definition at line 111 of file red_minloc.c.
Referenced by kminloc_common(), and kminlocs_common().
g_minloc
void(* g_minloc[__NTYPES])() () = TYPELIST3(g_minloc_) static
Definition at line 63 of file red_minloc.c.
Referenced by minloc_common(), and minlocs_common().
l_kminloc_b
void(* l_kminloc_b[4][__NTYPES])() () = TYPELIST3LK(l_kminloc_) static
Definition at line 110 of file red_minloc.c.
Referenced by kminloc_common(), and kminlocs_common().
l_minloc_b
void(* l_minloc_b[4][__NTYPES])() () = TYPELIST3LK(l_minloc_) static
Definition at line 62 of file red_minloc.c.
Referenced by minloc_common(), and minlocs_common().