flang: red_norm2.c File Reference
red_norm2.c File Reference
#include "norm2.h"
Functions
void F90_I8() norm2_real4 (__POINT_T *, __INT_T *, __REAL4_T *)
void F90_I8() norm2_real8 (__POINT_T *, __INT_T *, __REAL8_T *)
void F90_NORM2() nodim_1_real8 (__POINT_T *, __POINT_T *, __INT4_T *, F90_Desc *)
void F90_NORM2() nodim_2_real8 (__POINT_T *, __POINT_T *, __INT4_T *, F90_Desc *)
void F90_NORM2() nodim_3_real8 (__POINT_T *, __POINT_T *, __INT4_T *, F90_Desc *)
void F90_NORM2() nodim_4_real8 (__POINT_T *, __POINT_T *, __INT4_T *, F90_Desc *)
void F90_NORM2() nodim_5_real8 (__POINT_T *, __POINT_T *, __INT4_T *, F90_Desc *)
void F90_NORM2() nodim_6_real8 (__POINT_T *, __POINT_T *, __INT4_T *, F90_Desc *)
void F90_NORM2() nodim_7_real8 (__POINT_T *, __POINT_T *, __INT4_T *, F90_Desc *)
void F90_NORM2() nodim_1_real4 (__POINT_T *, __POINT_T *, F90_Desc *)
void F90_NORM2() nodim_2_real4 (__POINT_T *, __POINT_T *, F90_Desc *)
void F90_NORM2() nodim_3_real4 (__POINT_T *, __POINT_T *, F90_Desc *)
void F90_NORM2() nodim_4_real4 (__POINT_T *, __POINT_T *, F90_Desc *)
void F90_NORM2() nodim_5_real4 (__POINT_T *, __POINT_T *, F90_Desc *)
void F90_NORM2() nodim_6_real4 (__POINT_T *, __POINT_T *, F90_Desc *)
void F90_NORM2() nodim_7_real4 (__POINT_T *, __POINT_T *, F90_Desc *)
void F90_NORM2() dim_2_real8 (__POINT_T *, __POINT_T *, __INT4_T *, __INT4_T *, F90_Desc *, F90_Desc *)
void F90_NORM2() dim_3_real8 (__POINT_T *, __POINT_T *, __INT4_T *, __INT4_T *, F90_Desc *, F90_Desc *)
void F90_NORM2() dim_4_real8 (__POINT_T *, __POINT_T *, __INT4_T *, __INT4_T *, F90_Desc *, F90_Desc *)
void F90_NORM2() dim_5_real8 (__POINT_T *, __POINT_T *, __INT4_T *, __INT4_T *, F90_Desc *, F90_Desc *)
void F90_NORM2() dim_6_real8 (__POINT_T *, __POINT_T *, __INT4_T *, __INT4_T *, F90_Desc *, F90_Desc *)
void F90_NORM2() dim_7_real8 (__POINT_T *, __POINT_T *, __INT4_T *, __INT4_T *, F90_Desc *, F90_Desc *)
void F90_NORM2() dim_2_real4 (__POINT_T *, __POINT_T *, __INT4_T *, F90_Desc *, F90_Desc *)
void F90_NORM2() dim_3_real4 (__POINT_T *, __POINT_T *, __INT4_T *, F90_Desc *, F90_Desc *)
void F90_NORM2() dim_4_real4 (__POINT_T *, __POINT_T *, __INT4_T *, F90_Desc *, F90_Desc *)
void F90_NORM2() dim_5_real4 (__POINT_T *, __POINT_T *, __INT4_T *, F90_Desc *, F90_Desc *)
void F90_NORM2() dim_6_real4 (__POINT_T *, __POINT_T *, __INT4_T *, F90_Desc *, F90_Desc *)
void F90_NORM2() dim_7_real4 (__POINT_T *, __POINT_T *, __INT4_T *, F90_Desc *, F90_Desc *)
void F90_I8() stride_1_norm2_real4 (__POINT_T *src_pointer, __INT_T *size, __REAL4_T *result)
void F90_I8() stride_1_norm2_real8 (__POINT_T *src_pointer, __INT_T *size, __REAL8_T *result)
void ENTFTN (NORM2_NODIM, norm2_nodim)
void ENTFTN (NORM2, norm2)
Function Documentation
dim_2_real4()
void F90_NORM2() dim_2_real4 (__POINT_T * , __POINT_T * , __INT4_T * , F90_Desc * , F90_Desc *)
Referenced by ENTFTN().
dim_2_real8()
void F90_NORM2() dim_2_real8 (__POINT_T * , __POINT_T * , __INT4_T * , __INT4_T * , F90_Desc * , F90_Desc *)
Referenced by ENTFTN().
dim_3_real4()
void F90_NORM2() dim_3_real4 (__POINT_T * , __POINT_T * , __INT4_T * , F90_Desc * , F90_Desc *)
Referenced by ENTFTN().
dim_3_real8()
void F90_NORM2() dim_3_real8 (__POINT_T * , __POINT_T * , __INT4_T * , __INT4_T * , F90_Desc * , F90_Desc *)
Referenced by ENTFTN().
dim_4_real4()
void F90_NORM2() dim_4_real4 (__POINT_T * , __POINT_T * , __INT4_T * , F90_Desc * , F90_Desc *)
Referenced by ENTFTN().
dim_4_real8()
void F90_NORM2() dim_4_real8 (__POINT_T * , __POINT_T * , __INT4_T * , __INT4_T * , F90_Desc * , F90_Desc *)
Referenced by ENTFTN().
dim_5_real4()
void F90_NORM2() dim_5_real4 (__POINT_T * , __POINT_T * , __INT4_T * , F90_Desc * , F90_Desc *)
Referenced by ENTFTN().
dim_5_real8()
void F90_NORM2() dim_5_real8 (__POINT_T * , __POINT_T * , __INT4_T * , __INT4_T * , F90_Desc * , F90_Desc *)
Referenced by ENTFTN().
dim_6_real4()
void F90_NORM2() dim_6_real4 (__POINT_T * , __POINT_T * , __INT4_T * , F90_Desc * , F90_Desc *)
Referenced by ENTFTN().
dim_6_real8()
void F90_NORM2() dim_6_real8 (__POINT_T * , __POINT_T * , __INT4_T * , __INT4_T * , F90_Desc * , F90_Desc *)
Referenced by ENTFTN().
dim_7_real4()
void F90_NORM2() dim_7_real4 (__POINT_T * , __POINT_T * , __INT4_T * , F90_Desc * , F90_Desc *)
Referenced by ENTFTN().
dim_7_real8()
void F90_NORM2() dim_7_real8 (__POINT_T * , __POINT_T * , __INT4_T * , __INT4_T * , F90_Desc * , F90_Desc *)
Referenced by ENTFTN().
ENTFTN() [1/2]
void ENTFTN (NORM2 , norm2)
Definition at line 131 of file red_norm2.c.
References __fort_abort(), __REAL4, __REAL8, dim, dim_2_real4(), dim_2_real8(), dim_3_real4(), dim_3_real8(), dim_4_real4(), dim_4_real8(), dim_5_real4(), dim_5_real8(), dim_6_real4(), dim_6_real8(), dim_7_real4(), dim_7_real8(), F90_NORM2, nodim_1_real4(), nodim_1_real8(), result, and src.
ENTFTN() [2/2]
void ENTFTN (NORM2_NODIM , norm2_nodim)
Definition at line 65 of file red_norm2.c.
References __fort_abort(), __REAL4, __REAL8, F90_NORM2, nodim_1_real4(), nodim_1_real8(), nodim_2_real4(), nodim_2_real8(), nodim_3_real4(), nodim_3_real8(), nodim_4_real4(), nodim_4_real8(), nodim_5_real4(), nodim_5_real8(), nodim_6_real4(), nodim_6_real8(), nodim_7_real4(), nodim_7_real8(), result, and src.
nodim_1_real4()
void F90_NORM2() nodim_1_real4 (__POINT_T * , __POINT_T * , F90_Desc *)
Referenced by ENTFTN().
nodim_1_real8()
void F90_NORM2() nodim_1_real8 (__POINT_T * , __POINT_T * , __INT4_T * , F90_Desc *)
Referenced by ENTFTN().
nodim_2_real4()
void F90_NORM2() nodim_2_real4 (__POINT_T * , __POINT_T * , F90_Desc *)
Referenced by ENTFTN().
nodim_2_real8()
void F90_NORM2() nodim_2_real8 (__POINT_T * , __POINT_T * , __INT4_T * , F90_Desc *)
Referenced by ENTFTN().
nodim_3_real4()
void F90_NORM2() nodim_3_real4 (__POINT_T * , __POINT_T * , F90_Desc *)
Referenced by ENTFTN().
nodim_3_real8()
void F90_NORM2() nodim_3_real8 (__POINT_T * , __POINT_T * , __INT4_T * , F90_Desc *)
Referenced by ENTFTN().
nodim_4_real4()
void F90_NORM2() nodim_4_real4 (__POINT_T * , __POINT_T * , F90_Desc *)
Referenced by ENTFTN().
nodim_4_real8()
void F90_NORM2() nodim_4_real8 (__POINT_T * , __POINT_T * , __INT4_T * , F90_Desc *)
Referenced by ENTFTN().
nodim_5_real4()
void F90_NORM2() nodim_5_real4 (__POINT_T * , __POINT_T * , F90_Desc *)
Referenced by ENTFTN().
nodim_5_real8()
void F90_NORM2() nodim_5_real8 (__POINT_T * , __POINT_T * , __INT4_T * , F90_Desc *)
Referenced by ENTFTN().
nodim_6_real4()
void F90_NORM2() nodim_6_real4 (__POINT_T * , __POINT_T * , F90_Desc *)
Referenced by ENTFTN().
nodim_6_real8()
void F90_NORM2() nodim_6_real8 (__POINT_T * , __POINT_T * , __INT4_T * , F90_Desc *)
Referenced by ENTFTN().
nodim_7_real4()
void F90_NORM2() nodim_7_real4 (__POINT_T * , __POINT_T * , F90_Desc *)
Referenced by ENTFTN().
nodim_7_real8()
void F90_NORM2() nodim_7_real8 (__POINT_T * , __POINT_T * , __INT4_T * , F90_Desc *)
Referenced by ENTFTN().
norm2_real4()
void F90_I8() norm2_real4 (__POINT_T * , __INT_T * , __REAL4_T *)
Referenced by stride_1_norm2_real4().
norm2_real8()
void F90_I8() norm2_real8 (__POINT_T * , __INT_T * , __REAL8_T *)
Referenced by stride_1_norm2_real8().
stride_1_norm2_real4()
void F90_I8() stride_1_norm2_real4 (__POINT_T * src_pointer, __INT_T * size, __REAL4_T * result)
Definition at line 57 of file red_norm2.c.
References F90_I8, norm2_real4(), result, and size.
stride_1_norm2_real8()
void F90_I8() stride_1_norm2_real8 (__POINT_T * src_pointer, __INT_T * size, __REAL8_T * result)
Definition at line 61 of file red_norm2.c.
References F90_I8, norm2_real8(), result, and size.