flang: red_norm2_stride1.c File Reference
red_norm2_stride1.c File Reference
#include "norm2.h"
#include <math.h>
Functions
void NORM2_REAL4 (__POINT_T *src_pointer, __INT_T *size, __REAL4_T *result)
void NORM2_REAL8 (__POINT_T *src_pointer, __INT_T *size, __REAL8_T *result)
Function Documentation
NORM2_REAL4()
void NORM2_REAL4 (__POINT_T * src_pointer, __INT_T * size, __REAL4_T * result)
Definition at line 13 of file red_norm2_stride1.c.
References i, result, size, sqrt(), src, sum(), and val.
NORM2_REAL8()
void NORM2_REAL8 (__POINT_T * src_pointer, __INT_T * size, __REAL8_T * result)
Definition at line 27 of file red_norm2_stride1.c.
References i, result, size, sqrt(), src, and sum().