flang: red_findloc.c File Reference
red_findloc.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "red.h"
Functions
void ENTFTN (FINDLOCS, findlocs)
void ENTFTN (FINDLOC, findloc)
void ENTFTN (KFINDLOCS, kfindlocs)
void ENTFTN (KFINDLOC, kfindloc)
static char * __chk_str_val (char *s, __INT8_T slen, __INT8_T tlen)
void ENTFTN (FINDLOCSTRS, findlocstrs)
void ENTFTN (FINDLOCSTR, findlocstr)
void ENTFTN (KFINDLOCSTRS, kfindlocstrs)
void ENTFTN (KFINDLOCSTR, kfindlocstr)
Variables
static void(* l_findloc_b [4][__NTYPES])() = TYPELIST3LK(l_findloc_)
static void(* g_findloc [__NTYPES])() = TYPELIST3(g_findloc_)
static void(* l_kfindloc [4][__NTYPES])() = TYPELIST3LK(l_kfindloc_)
static void(* g_kfindloc [__NTYPES])() = TYPELIST3(g_kfindloc_)
Function Documentation
__chk_str_val()
static char * __chk_str_val (char * s, __INT8_T slen, __INT8_T tlen) static
Definition at line 258 of file red_findloc.c.
References __fort_gmalloc(), and s.
Referenced by ENTFTN().
ENTFTN() [1/8]
void ENTFTN (FINDLOC , findloc)
Definition at line 150 of file red_findloc.c.
References __DESC, __FINDLOC, __fort_create_conforming_mask_array(), __fort_gfree(), __fort_red_array(), __fort_red_arraylk(), __fort_red_what, __LOG, db(), DECL_HDR_VARS, ds(), F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_findloc, GET_DIST_SHIFTS, I8, INIT_RED_PARM, ISSCALAR, l_findloc_b, rb, val, and z.
ENTFTN() [2/8]
void ENTFTN (FINDLOCS , findlocs)
Definition at line 114 of file red_findloc.c.
References __DESC, __FINDLOC, __fort_gfree(), __fort_gmalloc(), __fort_red_scalarlk(), __fort_red_what, __LOG, __STR, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_findloc, GET_DIST_SHIFTS, I8, INIT_RED_PARM, l_findloc_b, rb, val, and z.
Referenced by ENTFTN().
ENTFTN() [3/8]
void ENTFTN (FINDLOCSTR , findlocstr)
Definition at line 280 of file red_findloc.c.
References __chk_str_val(), db(), ds(), ENTFTN(), rb, val, and vlen.
ENTFTN() [4/8]
void ENTFTN (FINDLOCSTRS , findlocstrs)
Definition at line 270 of file red_findloc.c.
References __chk_str_val(), ENTFTN(), rb, val, and vlen.
ENTFTN() [5/8]
void ENTFTN (KFINDLOC , kfindloc)
Definition at line 223 of file red_findloc.c.
References __DESC, __FINDLOC, __fort_create_conforming_mask_array(), __fort_gfree(), __fort_kred_arraylk(), __fort_red_array(), __fort_red_what, __LOG, db(), DECL_HDR_VARS, ds(), F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_kfindloc, GET_DIST_SHIFTS, I8, INIT_RED_PARM, ISSCALAR, l_kfindloc, rb, val, and z.
ENTFTN() [6/8]
void ENTFTN (KFINDLOCS , kfindlocs)
Definition at line 186 of file red_findloc.c.
References __DESC, __FINDLOC, __fort_gfree(), __fort_gmalloc(), __fort_kred_scalarlk(), __fort_red_what, __LOG, __STR, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_kfindloc, GET_DIST_SHIFTS, I8, INIT_RED_PARM, l_kfindloc, rb, val, and z.
ENTFTN() [7/8]
void ENTFTN (KFINDLOCSTR , kfindlocstr)
Definition at line 302 of file red_findloc.c.
References __chk_str_val(), db(), ds(), ENTFTN(), rb, val, and vlen.
ENTFTN() [8/8]
void ENTFTN (KFINDLOCSTRS , kfindlocstrs)
Definition at line 291 of file red_findloc.c.
References __chk_str_val(), ENTFTN(), rb, val, and vlen.
Variable Documentation
g_findloc
void(* g_findloc[__NTYPES])() () = TYPELIST3(g_findloc_) static
Definition at line 62 of file red_findloc.c.
Referenced by ENTFTN().
g_kfindloc
void(* g_kfindloc[__NTYPES])() () = TYPELIST3(g_kfindloc_) static
Definition at line 110 of file red_findloc.c.
Referenced by ENTFTN().
l_findloc_b
void(* l_findloc_b[4][__NTYPES])() () = TYPELIST3LK(l_findloc_) static
Definition at line 61 of file red_findloc.c.
Referenced by ENTFTN().
l_kfindloc
void(* l_kfindloc[4][__NTYPES])() () = TYPELIST3LK(l_kfindloc_) static
Definition at line 109 of file red_findloc.c.
Referenced by ENTFTN().