flang: red_iany.c File Reference
red_iany.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "red.h"
Functions
void ENTFTN (IANYS, ianys)
void ENTFTN (IANY, iany)
void ENTFTN (REDUCE_IANY, reduce_iany)
void ENTFTN (GLOBAL_IANY, global_iany)
Variables
static void(* l_iany [4][__NTYPES])() = TYPELIST2LK(l_iany_)
static void(* g_iany [__NTYPES])() = TYPELIST2(g_iany_)
Function Documentation
ENTFTN() [1/4]
void ENTFTN (GLOBAL_IANY , global_iany)
Definition at line 140 of file red_iany.c.
References __fort_global_reduce(), g_iany, I8, and rb.
ENTFTN() [2/4]
void ENTFTN (IANY , iany)
Definition at line 90 of file red_iany.c.
References __DESC, __fort_create_conforming_mask_array(), __fort_gfree(), __fort_red_array(), __fort_red_what, __IANY, __LOG, db(), DECL_HDR_VARS, ds(), F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_iany, GET_DIST_SHIFTS, GET_DIST_ZED, I8, INIT_RED_PARM, ISSCALAR, l_iany, rb, and z.
ENTFTN() [3/4]
void ENTFTN (IANYS , ianys)
Definition at line 67 of file red_iany.c.
References __fort_red_scalar(), __fort_red_what, __IANY, __LOG, F90_KIND_G, F90_LEN_G, g_iany, GET_DIST_SHIFTS, GET_DIST_ZED, I8, INIT_RED_PARM, l_iany, NULL, rb, and z.
ENTFTN() [4/4]
void ENTFTN (REDUCE_IANY , reduce_iany)
Definition at line 124 of file red_iany.c.
References __fort_abort(), __fort_global_reduce(), __INT, F90_TAG_G, g_iany, I8, NULL, and rb.
Variable Documentation
g_iany
void(* g_iany[__NTYPES])() () = TYPELIST2(g_iany_) static
Definition at line 63 of file red_iany.c.
Referenced by ENTFTN().
l_iany
void(* l_iany[4][__NTYPES])() () = TYPELIST2LK(l_iany_) static
Definition at line 62 of file red_iany.c.
Referenced by ENTFTN().