flang: red.h File Reference
red.h File Reference
#include "fort_vars.h"
Classes
struct red_parm
Macros
#define INIT_RED_PARM(z) memset(&z, '\0', sizeof(red_parm))
#define ARITHFNL(OP, NAME, RTYP, ATYP)
#define ARITHFNG(OP, NAME, RTYP, ATYP)
#define ARITHFNLKN(OP, NAME, RTYP, ATYP, N)
#define LOGFNL(OP, NAME, RTYP)
#define LOGFNG(OP, NAME, RTYP)
#define LOGFNLKN(OP, NAME, RTYP, N)
#define CONDFN(COND, NAME, RTYP)
#define CONDFNG(COND, NAME, RTYP)
#define CONDSTRFNG(COND, NAME, RTYP)
#define CONDFNLKN(COND, NAME, RTYP, N)
#define CONDSTRFNLKN(COND, NAME, RTYP, N)
#define MLOCFN(COND, NAME, RTYP)
#define MLOCSTRFN(COND, NAME, RTYP)
#define MLOCFNG(COND, NAME, RTYP)
#define MLOCSTRFNG(COND, NAME, RTYP)
#define MLOCFNLKN(COND, NAME, RTYP, N)
#define MLOCSTRFNLKN(COND, NAME, RTYP, N)
#define KMLOCFNG(COND, NAME, RTYP)
#define KMLOCSTRFNG(COND, NAME, RTYP)
#define KMLOCFNLKN(COND, NAME, RTYP, N)
#define KMLOCSTRFNLKN(COND, NAME, RTYP, N)
#define FLOCFN(COND, NAME, RTYP)
#define FLOCSTRFN(COND, NAME, RTYP)
#define FLOCFNG(COND, NAME, RTYP)
#define FLOCSTRFNG(COND, NAME, RTYP)
#define FLOCFNLKN(COND, NAME, RTYP, N)
#define FLOCSTRFNLKN(COND, NAME, RTYP, N)
#define KFLOCFNG(COND, NAME, RTYP)
#define KFLOCSTRFNG(COND, NAME, RTYP)
#define KFLOCFNLKN(COND, NAME, RTYP, N)
#define KFLOCSTRFNLKN(COND, NAME, RTYP, N)
#define TYPELIST1(NAME)
#define TYPELIST1LKN(NAME, N)
#define TYPELIST1LK(NAME)
#define TYPELIST2(NAME)
#define TYPELIST2LKN(NAME, N)
#define TYPELIST2LK(NAME)
#define TYPELIST3(NAME)
#define TYPELIST3LKN(NAME, N)
#define TYPELIST3LK(NAME)
Enumerations
enum red_enum {
__ALL , __ANY , __COUNT , __IALL ,
__IANY , __IPARITY , __MAXLOC , __MAXVAL ,
__MINLOC , __MINVAL , __PARITY , __PRODUCT ,
__SUM , __FINDLOC , __NREDS
}
Functions
void __fort_red_unimplemented ()
void __fort_red_abort (const char *msg)
void I8() __fort_red_scalar (red_parm *z, char *rb, char *ab, char *mb, F90_Desc *rs, F90_Desc *as, F90_Desc *ms, __INT_T *xb, red_enum op)
void I8() __fort_red_scalarlk (red_parm *z, char *rb, char *ab, char *mb, F90_Desc *rs, F90_Desc *as, F90_Desc *ms, __INT_T *xb, red_enum op)
SAME as previous, but allow any logical kind for the mask.
void I8() __fort_kred_scalarlk (red_parm *z, char *rb, char *ab, char *mb, F90_Desc *rs, F90_Desc *as, F90_Desc *ms, __INT8_T *xb, red_enum op)
void I8() __fort_red_array (red_parm *z, char *rb0, char *ab, char *mb, char *db, F90_Desc *rs0, F90_Desc *as, F90_Desc *ms, F90_Desc *ds, red_enum op)
void I8() __fort_red_arraylk (red_parm *z, char *rb0, char *ab, char *mb, char *db, F90_Desc *rs0, F90_Desc *as, F90_Desc *ms, F90_Desc *ds, red_enum op)
SAME as previous, but allow any logical kind for the mask.
void I8() __fort_kred_arraylk (red_parm *z, char *rb0, char *ab, char *mb, char *db, F90_Desc *rs0, F90_Desc *as, F90_Desc *ms, F90_Desc *ds, red_enum op)
void I8() __fort_global_reduce (char *rb, char *hb, int dims, F90_Desc *rd, F90_Desc *hd, const char *what, void(*fn[__NTYPES])())
Macro Definition Documentation
ARITHFNG
#define ARITHFNG (OP, NAME, RTYP, ATYP)
Value:
  static void g_##NAME(__INT_T n, RTYP *lr, RTYP *rr, void *lv, void *rv,      \
                       __INT_T len)                                            \
  {                                                                            \
    __INT_T i;                                                                 \
    for (i = 0; i < n; i++) {                                                  \
      lr[i] = lr[i] OP rr[i];                                                  \
    }                                                                          \
  }
Definition at line 149 of file red.h.
ARITHFNL
#define ARITHFNL (OP, NAME, RTYP, ATYP)
Value:
  static void l_##NAME(RTYP *r, __INT_T n, RTYP *v, __INT_T vs, __LOG_T *m,    \
                       __INT_T ms, __INT_T *loc, __INT_T li, __INT_T ls,       \
                       __INT_T len)                                            \
  {                                                                            \
    __INT_T i, j;                                                              \
    ATYP x = *r;                                                               \
    __LOG_T mask_log;                                                          \
    if (ms == 0)                                                               \
      for (i = 0; n > 0; n--, i += vs) {                                       \
        x = x OP v[i];                                                         \
      }                                                                        \
    else {                                                                     \
      mask_log = GET_DIST_MASK_LOG;                                           \
      for (i = j = 0; n > 0; n--, i += vs, j += ms) {                          \
        if (m[j] & mask_log)                                                   \
          x = x OP v[i];                                                       \
      }                                                                        \
    }                                                                          \
    *r = x;                                                                    \
  }
Definition at line 127 of file red.h.
ARITHFNLKN
#define ARITHFNLKN (OP, NAME, RTYP, ATYP, N)
Value:
  static void l_##NAME##l##N(RTYP *r, __INT_T n, RTYP *v, __INT_T vs,          \
                             __LOG##N##_T *m, __INT_T ms, __INT_T *loc,        \
                             __INT_T li, __INT_T ls, __INT_T len)              \
  {                                                                            \
    __INT_T i, j;                                                              \
    ATYP x = *r;                                                               \
    __LOG##N##_T mask_log;                                                     \
    if (ms == 0)                                                               \
      for (i = 0; n > 0; n--, i += vs) {                                       \
        x = x OP v[i];                                                         \
      }                                                                        \
    else {                                                                     \
      mask_log = GET_DIST_MASK_LOG##N;                                        \
      for (i = j = 0; n > 0; n--, i += vs, j += ms) {                          \
        if (m[j] & mask_log)                                                   \
          x = x OP v[i];                                                       \
      }                                                                        \
    }                                                                          \
    *r = x;                                                                    \
  }
Definition at line 159 of file red.h.
CONDFN
#define CONDFN (COND, NAME, RTYP)
Value:
  static void l_##NAME(RTYP *r, __INT_T n, RTYP *v, __INT_T vs, __LOG_T *m,    \
                       __INT_T ms, __INT_T *loc, __INT_T li, __INT_T ls,       \
                       __INT_T len)                                            \
  {                                                                            \
    __INT_T i, j;                                                              \
    RTYP x = *r;                                                               \
    __LOG_T mask_log;                                                          \
    if (ms == 0)                                                               \
      for (i = 0; n > 0; n--, i += vs) {                                       \
        if (v[i] COND x)                                                       \
          x = v[i];                                                            \
      }                                                                        \
    else {                                                                     \
      mask_log = GET_DIST_MASK_LOG;                                           \
      for (i = j = 0; n > 0; n--, i += vs, j += ms) {                          \
        if (m[j] & mask_log && v[i] COND x)                                    \
          x = v[i];                                                            \
      }                                                                        \
    }                                                                          \
    *r = x;                                                                    \
  }                                                                            \
  static void g_##NAME(__INT_T n, RTYP *lr, RTYP *rr, void *lv, void *rv,      \
                       __INT_T len)                                            \
  {                                                                            \
    __INT_T i;                                                                 \
    for (i = 0; i < n; i++) {                                                  \
      if (rr[i] COND lr[i])                                                    \
        lr[i] = rr[i];                                                         \
    }                                                                          \
  }
Definition at line 223 of file red.h.
CONDFNG
#define CONDFNG (COND, NAME, RTYP)
Value:
  static void g_##NAME(__INT_T n, RTYP *lr, RTYP *rr, void *lv, void *rv,      \
                       __INT_T len)                                            \
  {                                                                            \
    __INT_T i;                                                                 \
    for (i = 0; i < n; i++) {                                                  \
      if (rr[i] COND lr[i])                                                    \
        lr[i] = rr[i];                                                         \
    }                                                                          \
  }
Definition at line 255 of file red.h.
CONDFNLKN
#define CONDFNLKN (COND, NAME, RTYP, N)
Value:
  static void l_##NAME##l##N(RTYP *r, __INT_T n, RTYP *v, __INT_T vs,          \
                             __LOG##N##_T *m, __INT_T ms, __INT_T *loc,        \
                             __INT_T li, __INT_T ls, __INT_T len)              \
  {                                                                            \
    __INT_T i, j;                                                              \
    RTYP x = *r;                                                               \
    __LOG##N##_T mask_log;                                                     \
    if (ms == 0)                                                               \
      for (i = 0; n > 0; n--, i += vs) {                                       \
        if (v[i] COND x)                                                       \
          x = v[i];                                                            \
      }                                                                        \
    else {                                                                     \
      mask_log = GET_DIST_MASK_LOG##N;                                        \
      for (i = j = 0; n > 0; n--, i += vs, j += ms) {                          \
        if (m[j] & mask_log && v[i] COND x)                                    \
          x = v[i];                                                            \
      }                                                                        \
    }                                                                          \
    *r = x;                                                                    \
  }
Definition at line 277 of file red.h.
CONDSTRFNG
#define CONDSTRFNG (COND, NAME, RTYP)
Value:
  static void g_##NAME(__INT_T n, RTYP *lr, RTYP *rr, void *lv, void *rv,      \
                       __INT_T len)                                            \
  {                                                                            \
    __INT_T i;                                                                 \
    for (i = 0; i < n; i++, lr += len, rr += len) {                            \
      if (strncmp(rr, lr, len) COND 0)                                         \
        strncpy(lr, rr, len);                                                  \
    }                                                                          \
  }
Definition at line 266 of file red.h.
CONDSTRFNLKN
#define CONDSTRFNLKN (COND, NAME, RTYP, N)
Value:
  static void l_##NAME##l##N(RTYP *r, __INT_T n, RTYP *v, __INT_T vs,          \
                             __LOG##N##_T *m, __INT_T ms, __INT_T *loc,        \
                             __INT_T li, __INT_T ls, __INT_T len)              \
  {                                                                            \
    __INT_T i, j, ahop;                                                        \
    RTYP *x = r;                                                               \
    __LOG##N##_T mask_log;                                                     \
    ahop = len * vs;                                                           \
    if (ms == 0)                                                               \
      for (i = 0; n > 0; n--, i += vs, v += (ahop)) {                          \
        if (strncmp(v, x, len) COND 0)                                         \
          x = v;                                                               \
      }                                                                        \
    else {                                                                     \
      mask_log = GET_DIST_MASK_LOG##N;                                        \
      for (i = j = 0; n > 0; n--, i += vs, j += ms, v += (ahop)) {             \
        if (m[j] & mask_log && strncmp(v, x, len) COND 0)                      \
          x = v;                                                               \
      }                                                                        \
    }                                                                          \
    strncpy(r, x, len);                                                        \
  }
Definition at line 300 of file red.h.
FLOCFN
#define FLOCFN (COND, NAME, RTYP)
Definition at line 629 of file red.h.
FLOCFNG
#define FLOCFNG (COND, NAME, RTYP)
Value:
  static void g_##NAME(__INT_T n, RTYP *lval, RTYP *rval, __INT4_T *lloc,      \
                       __INT_T *rloc, __INT_T len, __LOG_T back)               \
  {                                                                            \
    __INT4_T i;                                                                \
    for (i = 0; i < n; i++) {                                                  \
      if (rval[i] COND lval[i]) {                                              \
        lloc[i] = rloc[i];                                                     \
      } else if (rval[i] == lval[i] && rloc[i] < lloc[i]) {                    \
        lloc[i] = rloc[i];                                                     \
      }                                                                        \
    }                                                                          \
  }
Definition at line 728 of file red.h.
FLOCFNLKN
#define FLOCFNLKN (COND, NAME, RTYP, N)
Definition at line 754 of file red.h.
FLOCSTRFN
#define FLOCSTRFN (COND, NAME, RTYP)
Definition at line 676 of file red.h.
FLOCSTRFNG
#define FLOCSTRFNG (COND, NAME, RTYP)
Value:
  static void g_##NAME(__INT_T n, RTYP *lval, RTYP *rval, __INT4_T *lloc,      \
                       __INT_T *rloc, __INT_T len, __LOG_T back)               \
  {                                                                            \
    __INT4_T i;                                                                \
    for (i = 0; i < n; i++, rval += len, lval += len) {                        \
      if (strncmp(rval, lval, len) COND 0) {                                   \
        lloc[i] = rloc[i];                                                     \
      }                                                                        \
    }                                                                          \
  }
Definition at line 742 of file red.h.
FLOCSTRFNLKN
#define FLOCSTRFNLKN (COND, NAME, RTYP, N)
Definition at line 788 of file red.h.
INIT_RED_PARM
#define INIT_RED_PARM (z) memset(&z, '\0', sizeof(red_parm))
Definition at line 59 of file red.h.
KFLOCFNG
#define KFLOCFNG (COND, NAME, RTYP)
Value:
  static void g_##NAME(__INT_T n, RTYP *lval, RTYP *rval, __INT8_T *lloc,      \
                       __INT8_T *rloc, __INT_T len, __LOG_T back)              \
  {                                                                            \
    __INT_T i;                                                                 \
    for (i = 0; i < n; i++) {                                                  \
      if (rval[i] COND lval[i]) {                                              \
        lloc[i] = rloc[i];                                                     \
        if (!back)                                                             \
          break;                                                               \
      } else if (rval[i] == lval[i] && rloc[i] < lloc[i]) {                    \
        lloc[i] = rloc[i];                                                     \
        if (!back)                                                             \
          break;                                                               \
      }                                                                        \
    }                                                                          \
  }
Definition at line 822 of file red.h.
KFLOCFNLKN
#define KFLOCFNLKN (COND, NAME, RTYP, N)
Definition at line 858 of file red.h.
KFLOCSTRFNG
#define KFLOCSTRFNG (COND, NAME, RTYP)
Value:
  static void g_##NAME(__INT_T n, RTYP *lval, RTYP *rval, __INT8_T *lloc,      \
                       __INT8_T *rloc, __INT_T len, __LOG_T back)              \
  {                                                                            \
    __INT_T i;                                                                 \
    for (i = 0; i < n; i++, lval += len, rval += len) {                        \
      if (strncmp(rval, lval, len) COND 0) {                                   \
        lloc[i] = rloc[i];                                                     \
        if (!back)                                                             \
          break;                                                               \
      } else if (strncmp(rval, lval, len) == 0 && rloc[i] < lloc[i]) {         \
        lloc[i] = rloc[i];                                                     \
        if (!back)                                                             \
          break;                                                               \
      }                                                                        \
    }                                                                          \
  }
Definition at line 840 of file red.h.
KFLOCSTRFNLKN
#define KFLOCSTRFNLKN (COND, NAME, RTYP, N)
Definition at line 892 of file red.h.
KMLOCFNG
#define KMLOCFNG (COND, NAME, RTYP)
Value:
  static void g_##NAME(__INT_T n, RTYP *lval, RTYP *rval, __INT8_T *lloc,      \
                       __INT8_T *rloc, __INT_T len)                            \
  {                                                                            \
    __INT_T i;                                                                 \
    for (i = 0; i < n; i++) {                                                  \
      if (rval[i] COND lval[i]) {                                              \
        lloc[i] = rloc[i];                                                     \
        lval[i] = rval[i];                                                     \
      } else if (rval[i] == lval[i] && rloc[i] < lloc[i]) {                    \
        lloc[i] = rloc[i];                                                     \
      }                                                                        \
    }                                                                          \
  }
Definition at line 526 of file red.h.
KMLOCFNLKN
#define KMLOCFNLKN (COND, NAME, RTYP, N)
Definition at line 556 of file red.h.
KMLOCSTRFNG
#define KMLOCSTRFNG (COND, NAME, RTYP)
Value:
  static void g_##NAME(__INT_T n, RTYP *lval, RTYP *rval, __INT8_T *lloc,      \
                       __INT8_T *rloc, __INT_T len)                            \
  {                                                                            \
    __INT_T i;                                                                 \
    for (i = 0; i < n; i++, lval += len, rval += len) {                        \
      if (strncmp(rval, lval, len) COND 0) {                                   \
        lloc[i] = rloc[i];                                                     \
        strncpy(lval, rval, len);                                              \
      } else if (strncmp(rval, lval, len) == 0 && rloc[i] < lloc[i]) {         \
        lloc[i] = rloc[i];                                                     \
      }                                                                        \
    }                                                                          \
  }
Definition at line 541 of file red.h.
KMLOCSTRFNLKN
#define KMLOCSTRFNLKN (COND, NAME, RTYP, N)
Definition at line 591 of file red.h.
LOGFNG
#define LOGFNG (OP, NAME, RTYP)
Value:
  static void g_##NAME(__INT_T n, RTYP *lr, RTYP *rr, void *lv, void *rv,      \
                       __INT_T len)                                            \
  {                                                                            \
    __INT_T i;                                                                 \
    for (i = 0; i < n; i++) {                                                  \
      lr[i] = lr[i] OP rr[i];                                                  \
    }                                                                          \
  }
Definition at line 198 of file red.h.
LOGFNL
#define LOGFNL (OP, NAME, RTYP)
Value:
  static void l_##NAME(RTYP *r, __INT_T n, RTYP *v, __INT_T vs, __LOG_T *m,    \
                       __INT_T ms, __INT_T *loc, __INT_T li, __INT_T ls,       \
                       __INT_T len)                                            \
  {                                                                            \
    int x;                                                                     \
    __INT_T i;                                                                 \
    __LOG_T mask_log = GET_DIST_MASK_LOG;                                     \
    x = ((*r & mask_log) != 0);                                                \
    for (i = 0; n > 0; n--, i += vs) {                                         \
      x = x OP((v[i] & mask_log) != 0);                                        \
    }                                                                          \
    *r = (RTYP)(x ? GET_DIST_TRUE_LOG : 0);                                   \
  }
Definition at line 183 of file red.h.
LOGFNLKN
#define LOGFNLKN (OP, NAME, RTYP, N)
Value:
  static void l_##NAME##l##N(RTYP *r, __INT_T n, RTYP *v, __INT_T vs,          \
                             __LOG##N##_T *m, __INT_T ms, __INT_T *loc,        \
                             __INT_T li, __INT_T ls, __INT_T len)              \
  {                                                                            \
    int x;                                                                     \
    __INT_T i;                                                                 \
    __LOG##N##_T mask_log = GET_DIST_MASK_LOG##N;                             \
    x = ((*r & mask_log) != 0);                                                \
    for (i = 0; n > 0; n--, i += vs) {                                         \
      x = x OP((v[i] & mask_log) != 0);                                        \
    }                                                                          \
    *r = (RTYP)(x ? GET_DIST_TRUE_LOG : 0);                                   \
  }
Definition at line 208 of file red.h.
MLOCFN
#define MLOCFN (COND, NAME, RTYP)
Definition at line 324 of file red.h.
MLOCFNG
#define MLOCFNG (COND, NAME, RTYP)
Value:
  static void g_##NAME(__INT_T n, RTYP *lval, RTYP *rval, __INT4_T *lloc,      \
                       __INT_T *rloc, __INT_T len)                             \
  {                                                                            \
    __INT4_T i;                                                                \
    for (i = 0; i < n; i++) {                                                  \
      if (rval[i] COND lval[i]) {                                              \
        lloc[i] = rloc[i];                                                     \
        lval[i] = rval[i];                                                     \
      } else if (rval[i] == lval[i] && rloc[i] < lloc[i]) {                    \
        lloc[i] = rloc[i];                                                     \
      }                                                                        \
    }                                                                          \
  }
Definition at line 423 of file red.h.
MLOCFNLKN
#define MLOCFNLKN (COND, NAME, RTYP, N)
Definition at line 453 of file red.h.
MLOCSTRFN
#define MLOCSTRFN (COND, NAME, RTYP)
Definition at line 373 of file red.h.
MLOCSTRFNG
#define MLOCSTRFNG (COND, NAME, RTYP)
Value:
  static void g_##NAME(__INT_T n, RTYP *lval, RTYP *rval, __INT4_T *lloc,      \
                       __INT_T *rloc, __INT_T len)                             \
  {                                                                            \
    __INT4_T i;                                                                \
    for (i = 0; i < n; i++, rval += len, lval += len) {                        \
      if (strncmp(rval, lval, len) COND 0) {                                   \
        lloc[i] = rloc[i];                                                     \
        strncpy(lval, rval, len);                                              \
      } else if (strncmp(rval, lval, len) == 0 && rloc[i] < lloc[i]) {         \
        lloc[i] = rloc[i];                                                     \
      }                                                                        \
    }                                                                          \
  }
Definition at line 438 of file red.h.
MLOCSTRFNLKN
#define MLOCSTRFNLKN (COND, NAME, RTYP, N)
Definition at line 488 of file red.h.
TYPELIST1
#define TYPELIST1 (NAME)
Definition at line 928 of file red.h.
TYPELIST1LK
#define TYPELIST1LK (NAME)
Value:
  {                                                                                                              \
    TYPELIST1LKN(NAME, 1), \
    TYPELIST1LKN(NAME, 2), \
    TYPELIST1LKN(NAME, 4), \
    TYPELIST1LKN(NAME, 8) \
  }
Definition at line 1008 of file red.h.
TYPELIST1LKN
#define TYPELIST1LKN (NAME, N)
Definition at line 968 of file red.h.
TYPELIST2
#define TYPELIST2 (NAME)
Definition at line 1018 of file red.h.
TYPELIST2LK
#define TYPELIST2LK (NAME)
Value:
  {                                                                                                              \
    TYPELIST2LKN(NAME, 1), \
    TYPELIST2LKN(NAME, 2), \
    TYPELIST2LKN(NAME, 4), \
    TYPELIST2LKN(NAME, 8) \
  }
Definition at line 1099 of file red.h.
TYPELIST2LKN
#define TYPELIST2LKN (NAME, N)
Definition at line 1059 of file red.h.
TYPELIST3
#define TYPELIST3 (NAME)
Definition at line 1109 of file red.h.
TYPELIST3LK
#define TYPELIST3LK (NAME)
Value:
  {                                                                                                              \
    TYPELIST3LKN(NAME, 1), \
    TYPELIST3LKN(NAME, 2), \
    TYPELIST3LKN(NAME, 4), \
    TYPELIST3LKN(NAME, 8) \
  }
Definition at line 1189 of file red.h.
TYPELIST3LKN
#define TYPELIST3LKN (NAME, N)
Definition at line 1149 of file red.h.
Enumeration Type Documentation
red_enum
enum red_enum
Enumerator
__ALL
__ANY
__COUNT
__IALL
__IANY
__IPARITY
__MAXLOC
__MAXVAL
__MINLOC
__MINVAL
__PARITY
__PRODUCT
__SUM
__FINDLOC
__NREDS
Definition at line 15 of file red.h.
Function Documentation
__fort_global_reduce()
void I8() __fort_global_reduce (char * rb, char * hb, int dims, F90_Desc * rd, F90_Desc * hd, const char * what, void(*[])() __NTYPES)
Referenced by ENTFTN().
__fort_kred_arraylk()
void I8() __fort_kred_arraylk (red_parm * z, char * rb0, char * ab, char * mb, char * db, F90_Desc * rs0, F90_Desc * as, F90_Desc * ms, F90_Desc * ds, red_enum op)
Definition at line 1042 of file red.c.
References _1, __ASSUMED_OVERLAPS, __ASSUMED_SHAPE, __CPLX16, __CPLX32, __CPLX8, __DESC, __FINDLOC, __fort_copy_out(), __fort_cycle_bounds(), __fort_fetch_int(), __fort_fetch_log(), __fort_gfree(), __fort_gmalloc(), __fort_red_abort(), __fort_red_what, __fort_reduce_section(), __fort_replicate_result(), __fort_show_section(), __fort_stored_alike(), __fort_test, __INHERIT, __INT, __INT1, __INT2, __INT4, __INT8, __INTENT_OUT, __LOG1, __LOG2, __LOG4, __LOG8, __MAXLOC, __MINLOC, __OFF_TEMPLATE, __REAL16, __REAL4, __REAL8, __STR, __TRANSCRIPTIVE_DIST_FORMAT, __TRANSCRIPTIVE_DIST_TARGET, ABSENT, db(), DEBUG_REDU, DECL_HDR_PTRS, DECL_HDR_VARS, DIST_MAPPED_G, ds(), ENTFTN(), F90_DIM_LBOUND_G, F90_FLAGS_G, F90_LBASE_G, F90_LEN_G, F90_LSIZE_G, F90_RANK_G, F90_TAG_G, flags, GET_DIST_LCPU, GET_DIST_SIZE_OF, GET_DIST_TRUE_LOG_ADDR, GET_DIST_ZED, i, I8, is_nonsequential_section(), ISPRESENT, kind, kred_array_loop(), len, NULL, rank, rb, rc, and z.
Referenced by ENTFTN(), kmaxloc_common(), and kminloc_common().
__fort_kred_scalarlk()
void I8() __fort_kred_scalarlk (red_parm * z, char * rb, char * ab, char * mb, F90_Desc * rs, F90_Desc * as, F90_Desc * ms, __INT8_T * xb, red_enum op)
Definition at line 436 of file red.c.
References __DESC, __fort_cycle_bounds(), __fort_fetch_log(), __fort_reduce_section(), __fort_replicate_result(), __fort_scalar_copy, __fort_stored_alike(), __INT, __OFF_TEMPLATE, DECL_DIM_PTRS, F90_DIM_LBOUND_G, F90_DPTR_EXTENT_G, F90_FLAGS_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_TRUE_LOG_ADDR, i, I8, ISPRESENT, m, NULL, p, q, rb, red_scalar_loop(), SET_DIM_PTRS, and z.
Referenced by ENTFTN(), kmaxlocs_common(), and kminlocs_common().
__fort_red_abort()
void __fort_red_abort (const char * msg)
Definition at line 36 of file red.c.
References __fort_abort(), __fort_red_what, msg(), and str.
Referenced by __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), kred_array_loop(), red_array_loop(), and red_scalar_loop().
__fort_red_array()
void I8() __fort_red_array (red_parm * z, char * rb0, char * ab, char * mb, char * db, F90_Desc * rs0, F90_Desc * as, F90_Desc * ms, F90_Desc * ds, red_enum op)
Definition at line 659 of file red.c.
References _1, __ASSUMED_OVERLAPS, __ASSUMED_SHAPE, __CPLX16, __CPLX32, __CPLX8, __DESC, __FINDLOC, __fort_copy_out(), __fort_cycle_bounds(), __fort_fetch_int(), __fort_fetch_log(), __fort_gfree(), __fort_gmalloc(), __fort_red_abort(), __fort_red_what, __fort_reduce_section(), __fort_replicate_result(), __fort_show_section(), __fort_stored_alike(), __fort_test, __INHERIT, __INT, __INT1, __INT2, __INT4, __INT8, __INTENT_OUT, __LOG1, __LOG2, __LOG4, __LOG8, __MAXLOC, __MINLOC, __OFF_TEMPLATE, __REAL16, __REAL4, __REAL8, __STR, __TRANSCRIPTIVE_DIST_FORMAT, __TRANSCRIPTIVE_DIST_TARGET, ABSENT, db(), DEBUG_REDU, DECL_HDR_PTRS, DECL_HDR_VARS, DIST_MAPPED_G, ds(), ENTFTN(), F90_DIM_LBOUND_G, F90_FLAGS_G, F90_LBASE_G, F90_LEN_G, F90_LSIZE_G, F90_RANK_G, F90_TAG_G, flags, GET_DIST_LCPU, GET_DIST_SIZE_OF, GET_DIST_TRUE_LOG_ADDR, GET_DIST_ZED, i, I8, is_nonsequential_section(), ISPRESENT, kind, len, NULL, rank, rb, rc, red_array_loop(), and z.
Referenced by ENTFTN(), kmaxloc_common(), kminloc_common(), maxloc_common(), and minloc_common().
__fort_red_arraylk()
void I8() __fort_red_arraylk (red_parm * z, char * rb0, char * ab, char * mb, char * db, F90_Desc * rs0, F90_Desc * as, F90_Desc * ms, F90_Desc * ds, red_enum op)
SAME as previous, but allow any logical kind for the mask.
Definition at line 851 of file red.c.
References _1, __ASSUMED_OVERLAPS, __ASSUMED_SHAPE, __CPLX16, __CPLX32, __CPLX8, __DESC, __FINDLOC, __fort_copy_out(), __fort_cycle_bounds(), __fort_fetch_int(), __fort_fetch_log(), __fort_gfree(), __fort_gmalloc(), __fort_red_abort(), __fort_red_what, __fort_reduce_section(), __fort_replicate_result(), __fort_show_section(), __fort_stored_alike(), __fort_test, __INHERIT, __INT, __INT1, __INT2, __INT4, __INT8, __INTENT_OUT, __LOG1, __LOG2, __LOG4, __LOG8, __MAXLOC, __MINLOC, __OFF_TEMPLATE, __REAL16, __REAL4, __REAL8, __STR, __TRANSCRIPTIVE_DIST_FORMAT, __TRANSCRIPTIVE_DIST_TARGET, ABSENT, db(), DEBUG_REDU, DECL_HDR_PTRS, DECL_HDR_VARS, DIST_MAPPED_G, ds(), ENTFTN(), F90_DIM_LBOUND_G, F90_FLAGS_G, F90_LBASE_G, F90_LEN_G, F90_LSIZE_G, F90_RANK_G, F90_TAG_G, flags, GET_DIST_LCPU, GET_DIST_SIZE_OF, GET_DIST_TRUE_LOG_ADDR, GET_DIST_ZED, i, I8, is_nonsequential_section(), ISPRESENT, kind, len, NULL, rank, rb, rc, red_array_loop(), and z.
Referenced by ENTFTN(), maxloc_common(), and minloc_common().
__fort_red_scalar()
void I8() __fort_red_scalar (red_parm * z, char * rb, char * ab, char * mb, F90_Desc * rs, F90_Desc * as, F90_Desc * ms, __INT_T * xb, red_enum op)
Definition at line 150 of file red.c.
References __DESC, __fort_cycle_bounds(), __fort_fetch_log(), __fort_reduce_section(), __fort_replicate_result(), __fort_scalar_copy, __fort_stored_alike(), __INT, __OFF_TEMPLATE, DECL_DIM_PTRS, F90_DIM_LBOUND_G, F90_DPTR_EXTENT_G, F90_FLAGS_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_TRUE_LOG_ADDR, i, I8, ISPRESENT, m, NULL, p, q, rb, red_scalar_loop(), SET_DIM_PTRS, and z.
Referenced by ENTFTN().
__fort_red_scalarlk()
void I8() __fort_red_scalarlk (red_parm * z, char * rb, char * ab, char * mb, F90_Desc * rs, F90_Desc * as, F90_Desc * ms, __INT_T * xb, red_enum op)
SAME as previous, but allow any logical kind for the mask.
Definition at line 212 of file red.c.
References __DESC, __fort_cycle_bounds(), __fort_fetch_log(), __fort_reduce_section(), __fort_replicate_result(), __fort_scalar_copy, __fort_stored_alike(), __INT, __OFF_TEMPLATE, DECL_DIM_PTRS, F90_DIM_LBOUND_G, F90_DPTR_EXTENT_G, F90_FLAGS_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_TRUE_LOG_ADDR, i, I8, ISPRESENT, m, NULL, p, q, rb, red_scalar_loop(), SET_DIM_PTRS, and z.
Referenced by ENTFTN(), maxlocs_common(), and minlocs_common().
__fort_red_unimplemented()
void __fort_red_unimplemented ()