flang: red_any.c File Reference
red_any.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "red.h"
Functions
void ENTFTN (ANYS, anys)
void ENTFTN (ANY, any)
void ENTFTN (REDUCE_ANY, reduce_any)
void ENTFTN (GLOBAL_ANY, global_any)
Variables
static __INT_T mask_desc = __LOG
static void(* l_any [4][__NTYPES])() = TYPELIST2LK(l_any_)
static void(* g_any [__NTYPES])() = TYPELIST2(g_any_)
Function Documentation
ENTFTN() [1/4]
void ENTFTN (ANY , any)
Definition at line 92 of file red_any.c.
References __ANY, __DESC, __fort_red_array(), __fort_red_what, __LOG, db(), ds(), F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_any, GET_DIST_SHIFTS, GET_DIST_TRUE_LOG_ADDR, GET_DIST_ZED, I8, INIT_RED_PARM, l_any, mask_desc, rb, and z.
ENTFTN() [2/4]
void ENTFTN (ANYS , anys)
Definition at line 68 of file red_any.c.
References __ANY, __DESC, __fort_red_scalar(), __fort_red_what, __LOG, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_any, GET_DIST_SHIFTS, GET_DIST_TRUE_LOG_ADDR, GET_DIST_ZED, I8, INIT_RED_PARM, l_any, mask_desc, NULL, rb, and z.
ENTFTN() [3/4]
void ENTFTN (GLOBAL_ANY , global_any)
Definition at line 133 of file red_any.c.
References __fort_global_reduce(), g_any, I8, and rb.
ENTFTN() [4/4]
void ENTFTN (REDUCE_ANY , reduce_any)
Definition at line 117 of file red_any.c.
References __fort_abort(), __fort_global_reduce(), __INT, F90_TAG_G, g_any, I8, NULL, and rb.
Variable Documentation
g_any
void(* g_any[__NTYPES])() () = TYPELIST2(g_any_) static
Definition at line 64 of file red_any.c.
Referenced by ENTFTN().
l_any
void(* l_any[4][__NTYPES])() () = TYPELIST2LK(l_any_) static
Definition at line 63 of file red_any.c.
Referenced by ENTFTN().
mask_desc
__INT_T mask_desc = __LOG static
Definition at line 16 of file red_any.c.
Referenced by ENTFTN().