flang: red_all.c File Reference
red_all.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "red.h"
Functions
void ENTFTN (ALLS, alls)
void ENTFTN (ALL, all)
void ENTFTN (REDUCE_ALL, reduce_all)
void ENTFTN (GLOBAL_ALL, global_all)
Variables
static __INT_T mask_desc = __LOG
static void(* l_all [4][__NTYPES])() = TYPELIST2LK(l_all_)
static void(* g_all [__NTYPES])() = TYPELIST2(g_all_)
Function Documentation
ENTFTN() [1/4]
void ENTFTN (ALL , all)
Definition at line 92 of file red_all.c.
References __ALL, __DESC, __fort_red_array(), __fort_red_what, __LOG, db(), ds(), F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_all, GET_DIST_SHIFTS, GET_DIST_TRUE_LOG_ADDR, GET_DIST_TRUES, I8, INIT_RED_PARM, l_all, mask_desc, rb, and z.
ENTFTN() [2/4]
void ENTFTN (ALLS , alls)
Definition at line 68 of file red_all.c.
References __ALL, __DESC, __fort_red_scalar(), __fort_red_what, __LOG, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_all, GET_DIST_SHIFTS, GET_DIST_TRUE_LOG_ADDR, GET_DIST_TRUES, I8, INIT_RED_PARM, l_all, mask_desc, NULL, rb, and z.
ENTFTN() [3/4]
void ENTFTN (GLOBAL_ALL , global_all)
Definition at line 133 of file red_all.c.
References __fort_global_reduce(), g_all, I8, and rb.
ENTFTN() [4/4]
void ENTFTN (REDUCE_ALL , reduce_all)
Definition at line 117 of file red_all.c.
References __fort_abort(), __fort_global_reduce(), __INT, F90_TAG_G, g_all, I8, NULL, and rb.
Variable Documentation
g_all
void(* g_all[__NTYPES])() () = TYPELIST2(g_all_) static
Definition at line 64 of file red_all.c.
Referenced by ENTFTN().
l_all
void(* l_all[4][__NTYPES])() () = TYPELIST2LK(l_all_) static
Definition at line 63 of file red_all.c.
Referenced by ENTFTN().
mask_desc
__INT_T mask_desc = __LOG static
Definition at line 16 of file red_all.c.
Referenced by ENTFTN().