flang: red_minval.c File Reference
red_minval.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "red.h"
Functions
void ENTFTN (MINVALS, minvals)
void ENTFTN (MINVAL, minval)
void ENTFTN (REDUCE_MINVAL, reduce_minval)
void ENTFTN (GLOBAL_MINVAL, global_minval)
Variables
static void(* l_minval [4][__NTYPES])() = TYPELIST3LK(l_minval_)
static void(* g_minval [__NTYPES])() = TYPELIST3(g_minval_)
Function Documentation
ENTFTN() [1/4]
void ENTFTN (GLOBAL_MINVAL , global_minval)
Definition at line 145 of file red_minval.c.
References __fort_global_reduce(), g_minval, I8, and rb.
ENTFTN() [2/4]
void ENTFTN (MINVAL , minval)
Definition at line 92 of file red_minval.c.
References __DESC, __fort_create_conforming_mask_array(), __fort_gfree(), __fort_red_array(), __fort_red_arraylk(), __fort_red_what, __LOG, __MINVAL, __STR, db(), DECL_HDR_VARS, ds(), F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_minval, GET_DIST_MAXS, GET_DIST_SHIFTS, I8, INIT_RED_PARM, ISSCALAR, l_minval, rb, and z.
ENTFTN() [3/4]
void ENTFTN (MINVALS , minvals)
Definition at line 66 of file red_minval.c.
References __DESC, __fort_red_scalarlk(), __fort_red_what, __LOG, __MINVAL, __STR, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, g_minval, GET_DIST_MAXS, GET_DIST_SHIFTS, I8, INIT_RED_PARM, l_minval, NULL, rb, and z.
ENTFTN() [4/4]
void ENTFTN (REDUCE_MINVAL , reduce_minval)
Definition at line 129 of file red_minval.c.
References __fort_abort(), __fort_global_reduce(), __INT, F90_TAG_G, g_minval, I8, NULL, and rb.
Variable Documentation
g_minval
void(* g_minval[__NTYPES])() () = TYPELIST3(g_minval_) static
Definition at line 62 of file red_minval.c.
Referenced by ENTFTN().
l_minval
void(* l_minval[4][__NTYPES])() () = TYPELIST3LK(l_minval_) static
Definition at line 61 of file red_minval.c.
Referenced by ENTFTN().