flang: red_count.c File Reference
red_count.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "red.h"
Macros
#define COUNTFN(NAME, RTYP)
#define COUNTFNLKN(NAME, RTYP, N)
Functions
static void I8() g_count (__INT_T n, __INT_T *lr, __INT_T *rr, void *lv, void *rv)
void ENTFTN (COUNTS, counts)
void ENTFTN (COUNT, count)
Variables
static __INT_T mask_desc = __LOG
static void(* l_count [4][__NTYPES])() = TYPELIST2LK(l_count_)
Macro Definition Documentation
COUNTFN
#define COUNTFN (NAME, RTYP)
Value:
  static void l_##NAME(int *r, __INT_T n, RTYP *v, __INT_T vs, __LOG_T *m,     \
                       __INT_T ms, __INT_T *loc, __INT_T li, __INT_T ls)       \
  {                                                                            \
    __INT_T i;                                                                 \
    int x = *r;                                                                \
    __LOG_T mask_log = GET_DIST_MASK_LOG;                                     \
    for (i = 0; n > 0; n--, i += vs) {                                         \
      if (v[i] & mask_log) {                                                   \
        x++;                                                                   \
      }                                                                        \
    }                                                                          \
    *r = x;                                                                    \
  }
Definition at line 18 of file red_count.c.
COUNTFNLKN
#define COUNTFNLKN (NAME, RTYP, N)
Value:
  static void l_##NAME##l##N(int *r, __INT_T n, RTYP *v, __INT_T vs,           \
                             __LOG##N##_T *m, __INT_T ms, __INT_T *loc,        \
                             __INT_T li, __INT_T ls)                           \
  {                                                                            \
    __INT_T i;                                                                 \
    int x = *r;                                                                \
    __LOG##N##_T mask_log = GET_DIST_MASK_LOG##N;                             \
    for (i = 0; n > 0; n--, i += vs) {                                         \
      if (v[i] & mask_log) {                                                   \
        x++;                                                                   \
      }                                                                        \
    }                                                                          \
    *r = x;                                                                    \
  }
Definition at line 33 of file red_count.c.
Function Documentation
ENTFTN() [1/2]
void ENTFTN (COUNT , count)
Definition at line 123 of file red_count.c.
References __COUNT, __DESC, __fort_red_array(), __fort_red_what, __INT, __LOG, db(), ds(), F90_KIND_G, F90_RANK_G, F90_TAG_G, g_count(), GET_DIST_SHIFTS, GET_DIST_TRUE_LOG_ADDR, GET_DIST_ZED, I8, INIT_RED_PARM, l_count, mask_desc, rb, void(), and z.
ENTFTN() [2/2]
void ENTFTN (COUNTS , counts)
Definition at line 97 of file red_count.c.
References __COUNT, __DESC, __fort_red_scalar(), __fort_red_what, __INT, __LOG, F90_KIND_G, F90_RANK_G, F90_TAG_G, g_count(), GET_DIST_SHIFTS, GET_DIST_TRUE_LOG_ADDR, GET_DIST_ZED, I8, INIT_RED_PARM, l_count, mask_desc, NULL, rb, void(), and z.
g_count()
static void I8() g_count (__INT_T n, __INT_T * lr, __INT_T * rr, void * lv, void * rv) static
Definition at line 87 of file red_count.c.
References i, and n.
Referenced by ENTFTN().
Variable Documentation
l_count
void(* l_count[4][__NTYPES])() () = TYPELIST2LK(l_count_) static
Definition at line 85 of file red_count.c.
Referenced by ENTFTN().
mask_desc
__INT_T mask_desc = __LOG static
Definition at line 16 of file red_count.c.
Referenced by ENTFTN().