flang: red.c File Reference
red.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "red.h"
Functions
void ENTFTN (QOPY_IN, qopy_in)
void __fort_red_abort (const char *msg)
static void I8() red_scalar_loop (red_parm *z, __INT_T aof, __INT_T ll, int dim)
reduction, dim argument absent
void I8() __fort_red_scalar (red_parm *z, char *rb, char *ab, char *mb, F90_Desc *rs, F90_Desc *as, F90_Desc *ms, __INT_T *xb, red_enum op)
void I8() __fort_red_scalarlk (red_parm *z, char *rb, char *ab, char *mb, F90_Desc *rs, F90_Desc *as, F90_Desc *ms, __INT_T *xb, red_enum op)
SAME as previous, but allow any logical kind for the mask.
static void I8() red_array_loop (red_parm *z, __INT_T rof, __INT_T aof, int rdim, int adim)
reduction, dim argument present
void I8() __fort_kred_scalarlk (red_parm *z, char *rb, char *ab, char *mb, F90_Desc *rs, F90_Desc *as, F90_Desc *ms, __INT8_T *xb, red_enum op)
static void I8() kred_array_loop (red_parm *z, __INT_T rof, __INT_T aof, int rdim, int adim)
void I8() __fort_red_array (red_parm *z, char *rb0, char *ab, char *mb, char *db, F90_Desc *rs0, F90_Desc *as, F90_Desc *ms, F90_Desc *ds, red_enum op)
void I8() __fort_red_arraylk (red_parm *z, char *rb0, char *ab, char *mb, char *db, F90_Desc *rs0, F90_Desc *as, F90_Desc *ms, F90_Desc *ds, red_enum op)
SAME as previous, but allow any logical kind for the mask.
void I8() __fort_kred_arraylk (red_parm *z, char *rb0, char *ab, char *mb, char *db, F90_Desc *rs0, F90_Desc *as, F90_Desc *ms, F90_Desc *ds, red_enum op)
void ENTFTN (REDUCE_DESCRIPTOR, reduce_descriptor)
set up result descriptor for reduction intrinsic – used when the dim arg is variable. result dimensions are aligned with the corresponding source dimensions and the result array becomes replicated over the reduced dimension. lbounds are set to 1 and overlap allowances are set to 0.
void *I8() __fort_create_conforming_mask_array (const char *what, char *ab, char *mb, F90_Desc *as, F90_Desc *ms, F90_Desc *new_ms)
Variables
void(* __fort_scalar_copy [__NTYPES])(void *rp, void *sp, int len)
Detailed Description
Intrinsic reduction functions
Definition in file red.c.
Function Documentation
__fort_create_conforming_mask_array()
void *I8() __fort_create_conforming_mask_array (const char * what, char * ab, char * mb, F90_Desc * as, F90_Desc * ms, F90_Desc * new_ms)
Definition at line 1291 of file red.c.
References __fort_abort(), __fort_gmalloc(), __LOG1, __LOG2, __LOG4, __LOG8, ENTFTN(), F90_GSIZE_G, F90_LSIZE_G, F90_TAG_G, GET_DIST_LCPU, i, and ISSCALAR.
Referenced by ENTFTN(), kmaxloc_common(), kminloc_common(), maxloc_common(), and minloc_common().
__fort_kred_arraylk()
void I8() __fort_kred_arraylk (red_parm * z, char * rb0, char * ab, char * mb, char * db, F90_Desc * rs0, F90_Desc * as, F90_Desc * ms, F90_Desc * ds, red_enum op)
Definition at line 1042 of file red.c.
References _1, __ASSUMED_OVERLAPS, __ASSUMED_SHAPE, __CPLX16, __CPLX32, __CPLX8, __DESC, __FINDLOC, __fort_copy_out(), __fort_cycle_bounds(), __fort_fetch_int(), __fort_fetch_log(), __fort_gfree(), __fort_gmalloc(), __fort_red_abort(), __fort_red_what, __fort_reduce_section(), __fort_replicate_result(), __fort_show_section(), __fort_stored_alike(), __fort_test, __INHERIT, __INT, __INT1, __INT2, __INT4, __INT8, __INTENT_OUT, __LOG1, __LOG2, __LOG4, __LOG8, __MAXLOC, __MINLOC, __OFF_TEMPLATE, __REAL16, __REAL4, __REAL8, __STR, __TRANSCRIPTIVE_DIST_FORMAT, __TRANSCRIPTIVE_DIST_TARGET, ABSENT, db(), DEBUG_REDU, DECL_HDR_PTRS, DECL_HDR_VARS, DIST_MAPPED_G, ds(), ENTFTN(), F90_DIM_LBOUND_G, F90_FLAGS_G, F90_LBASE_G, F90_LEN_G, F90_LSIZE_G, F90_RANK_G, F90_TAG_G, flags, GET_DIST_LCPU, GET_DIST_SIZE_OF, GET_DIST_TRUE_LOG_ADDR, GET_DIST_ZED, i, I8, is_nonsequential_section(), ISPRESENT, kind, kred_array_loop(), len, NULL, rank, rb, rc, and z.
Referenced by ENTFTN(), kmaxloc_common(), and kminloc_common().
__fort_kred_scalarlk()
void I8() __fort_kred_scalarlk (red_parm * z, char * rb, char * ab, char * mb, F90_Desc * rs, F90_Desc * as, F90_Desc * ms, __INT8_T * xb, red_enum op)
Definition at line 436 of file red.c.
References __DESC, __fort_cycle_bounds(), __fort_fetch_log(), __fort_reduce_section(), __fort_replicate_result(), __fort_scalar_copy, __fort_stored_alike(), __INT, __OFF_TEMPLATE, DECL_DIM_PTRS, F90_DIM_LBOUND_G, F90_DPTR_EXTENT_G, F90_FLAGS_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_TRUE_LOG_ADDR, i, I8, ISPRESENT, m, NULL, p, q, rb, red_scalar_loop(), SET_DIM_PTRS, and z.
Referenced by ENTFTN(), kmaxlocs_common(), and kminlocs_common().
__fort_red_abort()
void __fort_red_abort (const char * msg)
Definition at line 36 of file red.c.
References __fort_abort(), __fort_red_what, msg(), and str.
Referenced by __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), kred_array_loop(), red_array_loop(), and red_scalar_loop().
__fort_red_array()
void I8() __fort_red_array (red_parm * z, char * rb0, char * ab, char * mb, char * db, F90_Desc * rs0, F90_Desc * as, F90_Desc * ms, F90_Desc * ds, red_enum op)
Definition at line 659 of file red.c.
References _1, __ASSUMED_OVERLAPS, __ASSUMED_SHAPE, __CPLX16, __CPLX32, __CPLX8, __DESC, __FINDLOC, __fort_copy_out(), __fort_cycle_bounds(), __fort_fetch_int(), __fort_fetch_log(), __fort_gfree(), __fort_gmalloc(), __fort_red_abort(), __fort_red_what, __fort_reduce_section(), __fort_replicate_result(), __fort_show_section(), __fort_stored_alike(), __fort_test, __INHERIT, __INT, __INT1, __INT2, __INT4, __INT8, __INTENT_OUT, __LOG1, __LOG2, __LOG4, __LOG8, __MAXLOC, __MINLOC, __OFF_TEMPLATE, __REAL16, __REAL4, __REAL8, __STR, __TRANSCRIPTIVE_DIST_FORMAT, __TRANSCRIPTIVE_DIST_TARGET, ABSENT, db(), DEBUG_REDU, DECL_HDR_PTRS, DECL_HDR_VARS, DIST_MAPPED_G, ds(), ENTFTN(), F90_DIM_LBOUND_G, F90_FLAGS_G, F90_LBASE_G, F90_LEN_G, F90_LSIZE_G, F90_RANK_G, F90_TAG_G, flags, GET_DIST_LCPU, GET_DIST_SIZE_OF, GET_DIST_TRUE_LOG_ADDR, GET_DIST_ZED, i, I8, is_nonsequential_section(), ISPRESENT, kind, len, NULL, rank, rb, rc, red_array_loop(), and z.
Referenced by ENTFTN(), kmaxloc_common(), kminloc_common(), maxloc_common(), and minloc_common().
__fort_red_arraylk()
void I8() __fort_red_arraylk (red_parm * z, char * rb0, char * ab, char * mb, char * db, F90_Desc * rs0, F90_Desc * as, F90_Desc * ms, F90_Desc * ds, red_enum op)
SAME as previous, but allow any logical kind for the mask.
Definition at line 851 of file red.c.
References _1, __ASSUMED_OVERLAPS, __ASSUMED_SHAPE, __CPLX16, __CPLX32, __CPLX8, __DESC, __FINDLOC, __fort_copy_out(), __fort_cycle_bounds(), __fort_fetch_int(), __fort_fetch_log(), __fort_gfree(), __fort_gmalloc(), __fort_red_abort(), __fort_red_what, __fort_reduce_section(), __fort_replicate_result(), __fort_show_section(), __fort_stored_alike(), __fort_test, __INHERIT, __INT, __INT1, __INT2, __INT4, __INT8, __INTENT_OUT, __LOG1, __LOG2, __LOG4, __LOG8, __MAXLOC, __MINLOC, __OFF_TEMPLATE, __REAL16, __REAL4, __REAL8, __STR, __TRANSCRIPTIVE_DIST_FORMAT, __TRANSCRIPTIVE_DIST_TARGET, ABSENT, db(), DEBUG_REDU, DECL_HDR_PTRS, DECL_HDR_VARS, DIST_MAPPED_G, ds(), ENTFTN(), F90_DIM_LBOUND_G, F90_FLAGS_G, F90_LBASE_G, F90_LEN_G, F90_LSIZE_G, F90_RANK_G, F90_TAG_G, flags, GET_DIST_LCPU, GET_DIST_SIZE_OF, GET_DIST_TRUE_LOG_ADDR, GET_DIST_ZED, i, I8, is_nonsequential_section(), ISPRESENT, kind, len, NULL, rank, rb, rc, red_array_loop(), and z.
Referenced by ENTFTN(), maxloc_common(), and minloc_common().
__fort_red_scalar()
void I8() __fort_red_scalar (red_parm * z, char * rb, char * ab, char * mb, F90_Desc * rs, F90_Desc * as, F90_Desc * ms, __INT_T * xb, red_enum op)
Definition at line 150 of file red.c.
References __DESC, __fort_cycle_bounds(), __fort_fetch_log(), __fort_reduce_section(), __fort_replicate_result(), __fort_scalar_copy, __fort_stored_alike(), __INT, __OFF_TEMPLATE, DECL_DIM_PTRS, F90_DIM_LBOUND_G, F90_DPTR_EXTENT_G, F90_FLAGS_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_TRUE_LOG_ADDR, i, I8, ISPRESENT, m, NULL, p, q, rb, red_scalar_loop(), SET_DIM_PTRS, and z.
Referenced by ENTFTN().
__fort_red_scalarlk()
void I8() __fort_red_scalarlk (red_parm * z, char * rb, char * ab, char * mb, F90_Desc * rs, F90_Desc * as, F90_Desc * ms, __INT_T * xb, red_enum op)
SAME as previous, but allow any logical kind for the mask.
Definition at line 212 of file red.c.
References __DESC, __fort_cycle_bounds(), __fort_fetch_log(), __fort_reduce_section(), __fort_replicate_result(), __fort_scalar_copy, __fort_stored_alike(), __INT, __OFF_TEMPLATE, DECL_DIM_PTRS, F90_DIM_LBOUND_G, F90_DPTR_EXTENT_G, F90_FLAGS_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_TRUE_LOG_ADDR, i, I8, ISPRESENT, m, NULL, p, q, rb, red_scalar_loop(), SET_DIM_PTRS, and z.
Referenced by ENTFTN(), maxlocs_common(), and minlocs_common().
ENTFTN() [1/2]
void ENTFTN (QOPY_IN , qopy_in)
Definition at line 20 of file red.c.
References __fort_abort(), __fort_red_what, and str.
Referenced by __fort_create_conforming_mask_array(), __fort_kred_arraylk(), __fort_red_array(), and __fort_red_arraylk().
ENTFTN() [2/2]
void ENTFTN (REDUCE_DESCRIPTOR , reduce_descriptor)
set up result descriptor for reduction intrinsic – used when the dim arg is variable. result dimensions are aligned with the corresponding source dimensions and the result array becomes replicated over the reduced dimension. lbounds are set to 1 and overlap allowances are set to 0.
Definition at line 1239 of file red.c.
References __DESC, __DIST_INIT_DESCRIPTOR, __DIST_SET_ALLOCATION, __fort_abort(), __fort_finish_descriptor(), __fort_set_alignment(), __fort_set_single(), __SINGLE, add(), DECL_DIM_PTRS, DECL_HDR_PTRS, dim, DIST_ALIGN_TARGET_G, DIST_DIM_GEN_BLOCK_G, DIST_DPTR_TAXIS_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, DIST_INFO_G, DIST_SINGLE_G, extent(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_FLAGS_G, F90_RANK_G, F90_TAG_G, I8, kind, len, m, offset, SET_DIM_PTRS, and td.
kred_array_loop()
static void I8() kred_array_loop (red_parm * z, __INT_T rof, __INT_T aof, int rdim, int adim) static
Definition at line 497 of file red.c.
References __fort_block_bounds(), __fort_local_address(), __fort_print_scalar(), __fort_red_abort(), __fort_test, DEBUG_REDU, DECL_DIM_PTRS, DECL_HDR_PTRS, DIST_DPTR_BLOCK_G, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_LEN_G, GET_DIST_LCPU, i, I8, kred_array_loop(), lp, NULL, SET_DIM_PTRS, and z.
Referenced by __fort_kred_arraylk(), and kred_array_loop().
red_array_loop()
static void I8() red_array_loop (red_parm * z, __INT_T rof, __INT_T aof, int rdim, int adim) static
reduction, dim argument present
Definition at line 274 of file red.c.
References __fort_block_bounds(), __fort_local_address(), __fort_print_scalar(), __fort_red_abort(), __fort_test, DEBUG_REDU, DECL_DIM_PTRS, DECL_HDR_PTRS, DIST_DPTR_BLOCK_G, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_LEN_G, GET_DIST_LCPU, i, I8, lp, NULL, red_array_loop(), SET_DIM_PTRS, and z.
Referenced by __fort_red_array(), __fort_red_arraylk(), and red_array_loop().
red_scalar_loop()
static void I8() red_scalar_loop (red_parm * z, __INT_T aof, __INT_T ll, int dim) static
reduction, dim argument absent
Definition at line 46 of file red.c.
References __fort_block_bounds(), __fort_local_address(), __fort_red_abort(), DECL_DIM_PTRS, DECL_HDR_PTRS, dim, DIST_DPTR_BLOCK_G, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, extent(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_LEN_G, i, I8, NULL, red_scalar_loop(), SET_DIM_PTRS, and z.
Referenced by __fort_kred_scalarlk(), __fort_red_scalar(), __fort_red_scalarlk(), and red_scalar_loop().
Variable Documentation
__fort_scalar_copy
void(* __fort_scalar_copy[__NTYPES])(void *rp, void *sp, int len) (void * rp, void * sp, int len) extern
Referenced by __fort_kred_scalarlk(), __fort_red_scalar(), and __fort_red_scalarlk().