flang: reduct.c File Reference
reduct.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "red.h"
Functions
static __INT_T I8() map_to_processor (int c, __INT_T p0, __INT_T pr, __INT_T *pe, __INT_T *ps)
static void I8() broadcast (__INT_T from, __INT_T me, __INT_T np, __INT_T p0, __INT_T pr, __INT_T *pe, __INT_T *ps, void *adr, __INT_T cnt, __INT_T str, dtype typ, __INT_T len)
static void global_reduce_abort (const char *what, const char *msg)
void I8() __fort_global_reduce (char *rb, char *hb, int dims, F90_Desc *rd, F90_Desc *hd, const char *what, global_reduc_fn fn[__NTYPES])
void I8() __fort_reduce_section (void *vec1, dtype typ1, int len1, void *vec2, dtype typ2, int len2, int cnt, global_reduc_fn fn_g, int dim, F90_Desc *a)
void I8() __fort_replicate_result (void *vec1, dtype typ1, int len1, void *vec2, dtype typ2, int len2, int cnt, F90_Desc *a)
Variables
static __INT_T _1 = 1
Function Documentation
__fort_global_reduce()
void I8() __fort_global_reduce (char * rb, char * hb, int dims, F90_Desc * rd, F90_Desc * hd, const char * what, global_reduc_fn fn[__NTYPES])
Definition at line 102 of file reduct.c.
References _1, __DESC, __fort_abort(), __fort_gfree(), __fort_gmalloc(), __fort_rrecvl(), __fort_rsendl(), __fort_show_index(), __fort_test, ALIGNR, broadcast(), buf, cnt, cpu(), DEBUG_REDU, DECL_DIM_PTRS, DECL_HDR_PTRS, DFMT, DFMT_GEN_BLOCK, DIST_ALIGN_TARGET_G, DIST_DPTR_BLOCK_G, DIST_DPTR_GEN_BLOCK_G, DIST_DPTR_PCOORD_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_PSTRIDE_G, DIST_DPTR_TLB_G, DIST_INFO_G, DIST_MAPPED_G, DIST_SINGLE_G, F90_KIND_G, F90_LEN_G, F90_LSIZE_G, F90_RANK_G, F90_TAG_G, fn, GET_DIST_LCPU, GET_DIST_SIZE_OF, GET_DIST_TCPUS, global_reduce_abort(), i, I8, idx, ISSCALAR, ISSEQUENCE, j, kind, len, LOCAL_MODE, map_to_processor(), MAXDIMS, NULL, pc, rb, RECIP_DIV, RECIP_MOD, SET_DIM_PTRS, SUBGROUP_MODE, tmp, and TYPEKIND.
__fort_reduce_section()
void I8() __fort_reduce_section (void * vec1, dtype typ1, int len1, void * vec2, dtype typ2, int len2, int cnt, global_reduc_fn fn_g, int dim, F90_Desc * a)
Definition at line 340 of file reduct.c.
References __fort_gfree(), __fort_gmalloc(), __fort_rrecvl(), __fort_rsendl(), __fort_show_index(), __fort_test, a, cnt, cpu(), DEBUG_REDU, DECL_DIM_PTRS, dim, DIST_DPTR_PCOORD_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_PSTRIDE_G, DIST_MAPPED_G, F90_RANK_G, GET_DIST_LCPU, i, I8, LOCAL_MODE, map_to_processor(), MAXDIMS, n, NULL, pc, and SET_DIM_PTRS.
Referenced by __fort_kred_arraylk(), __fort_kred_scalarlk(), __fort_red_array(), __fort_red_arraylk(), __fort_red_scalar(), __fort_red_scalarlk(), ENTFTN(), mmul_mxv(), and mmul_vxm().
__fort_replicate_result()
void I8() __fort_replicate_result (void * vec1, dtype typ1, int len1, void * vec2, dtype typ2, int len2, int cnt, F90_Desc * a)
Definition at line 470 of file reduct.c.
References __fort_show_index(), __fort_test, a, broadcast(), cnt, DEBUG_REDU, DECL_DIM_PTRS, DECL_HDR_PTRS, DIST_ALIGN_TARGET_G, DIST_DPTR_BLOCK_G, DIST_DPTR_PCOORD_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_PSTRIDE_G, DIST_DPTR_TLB_G, DIST_INFO_G, DIST_MAPPED_G, DIST_SINGLE_G, F90_RANK_G, GET_DIST_LCPU, i, I8, LOCAL_MODE, MAXDIMS, NULL, pc, RECIP_DIV, RECIP_MOD, SET_DIM_PTRS, t, and td.
Referenced by __fort_kred_arraylk(), __fort_kred_scalarlk(), __fort_red_array(), __fort_red_arraylk(), __fort_red_scalar(), __fort_red_scalarlk(), ENTFTN(), mmul_mxv(), and mmul_vxm().
broadcast()
static void I8() broadcast (__INT_T from, __INT_T me, __INT_T np, __INT_T p0, __INT_T pr, __INT_T * pe, __INT_T * ps, void * adr, __INT_T cnt, __INT_T str, dtype typ, __INT_T len) static
Definition at line 42 of file reduct.c.
References __fort_rrecvl(), __fort_rsendl(), cnt, cpu(), I8, len, map_to_processor(), src, and str.
Referenced by __fort_global_reduce(), and __fort_replicate_result().
global_reduce_abort()
static void global_reduce_abort (const char * what, const char * msg) static
Definition at line 95 of file reduct.c.
References __fort_abort(), msg(), and str.
Referenced by __fort_global_reduce().
map_to_processor()
static __INT_T I8() map_to_processor (int c, __INT_T p0, __INT_T pr, __INT_T * pe, __INT_T * ps) static
Definition at line 18 of file reduct.c.
References c, i, and k.
Referenced by __fort_global_reduce(), __fort_reduce_section(), and broadcast().
Variable Documentation
_1
__INT_T _1 = 1 static
Definition at line 12 of file reduct.c.
Referenced by __fort_global_reduce().