flang: redundss.c File Reference
redundss.c File Reference
Optimize redundant subscript computations.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "ast.h"
#include "optimize.h"
#include "rtlRtns.h"
#include <stdarg.h>
Classes
struct lpinfo_t
Macros
#define Trace(a) TraceOutput a
#define LP_DFN(l) lpinfo.stg_base[l].dfn
#define LP_CHILDDFN(l) lpinfo.stg_base[l].childdfn
#define A_MOREG(s) astb.stg_base[s].f6
#define A_MOREP(s, v) (astb.stg_base[s].f6 = (v))
#define DtypeAssigned(dt) DT_Assigned.stg_base[dt]
#define SS_ALL 1
#define SS_MULTIPLE 2
#define SS_ROOT 4
#define SS_INV 8
#define SS_ALL_MULTIPLE 3
#define SS_INV_ROOT 12
#define SS_INV_ROOT_MULTIPLE 14
Functions
static void TraceOutput (const char *fmt,...)
STG_DECLARE (lpinfo, lpinfo_t)
static void InitAST (void)
static int modified (int ast, int l)
STG_DECLARE (DT_Assigned, int)
static void InitSSlist (void)
static void clearSSlist (void)
static void addSS (int ss, int type, int l)
static int markss (int ast, int type, int l)
static int markrootss (int root, int type, int l)
static LOGICAL count_nest (int ast, int *dummy)
static void findss (int ast, int *dummy)
static void findssexprsfg (int l, int fg, int newstmts, int type)
static void dumpSSlist (void)
static void findssexprs (int l, int newstmts, int type, int onlyfg, int parlevel)
static void mark (int ast, int l)
static void markmodified (int ast, int *pl)
static int inloop (int m, int l)
static void markmodifiedexprsfg (int l, int fg)
static void markmodifiedexprs (int l, int onlyfg)
static void propagatemodified (int l)
static int addcomponents (int lop, int optype, int rop, int l)
static int negatecomponent (int lop, int l)
static int mulcomponents (int lop, int rop, int l)
static void findmulcomponents (int ast, int l, int *pinv, int *pvar)
static void findcomponents (int ast, int l, int *pinv, int *pvar)
static LOGICAL mixedsum (int ast, int l)
static int distribute (int factor, int sum, int l)
static int MakeReplacement (int ast, int l)
static int addssassignments (int before, int beforefg, int rewrite, int par, int task)
static void rewritefg (int fg)
static void reassociate (void)
static void basic_block_redundant (void)
static void Init (void)
static void Done (void)
static void add_dfn_loop (int l, int *pn)
Reorder the loops in the LP_LOOP order.
void reorder_dfn_loops ()
void redundss (void)
Variables
static int OnlyFG = 0
static int SSlisthead
static int SSlisttail
static int findsstype
static int findssl
static int subscrnest = 0
static int CallAppears = 0
static int gany = 0
Detailed Description
Optimize redundant subscript computations.
Definition in file redundss.c.
Macro Definition Documentation
A_MOREG
#define A_MOREG (s) astb.stg_base[s].f6
Definition at line 80 of file redundss.c.
A_MOREP
#define A_MOREP (s, v) (astb.stg_base[s].f6 = (v))
Definition at line 81 of file redundss.c.
DtypeAssigned
#define DtypeAssigned (dt) DT_Assigned.stg_base[dt]
Definition at line 128 of file redundss.c.
LP_CHILDDFN
#define LP_CHILDDFN (l) lpinfo.stg_base[l].childdfn
Definition at line 77 of file redundss.c.
LP_DFN
#define LP_DFN (l) lpinfo.stg_base[l].dfn
Definition at line 76 of file redundss.c.
SS_ALL
#define SS_ALL 1
Definition at line 147 of file redundss.c.
SS_ALL_MULTIPLE
#define SS_ALL_MULTIPLE 3
Definition at line 151 of file redundss.c.
SS_INV
#define SS_INV 8
Definition at line 150 of file redundss.c.
SS_INV_ROOT
#define SS_INV_ROOT 12
Definition at line 152 of file redundss.c.
SS_INV_ROOT_MULTIPLE
#define SS_INV_ROOT_MULTIPLE 14
Definition at line 153 of file redundss.c.
SS_MULTIPLE
#define SS_MULTIPLE 2
Definition at line 148 of file redundss.c.
SS_ROOT
#define SS_ROOT 4
Definition at line 149 of file redundss.c.
Trace
#define Trace (a) TraceOutput a
Definition at line 21 of file redundss.c.
Function Documentation
add_dfn_loop()
static void add_dfn_loop (int l, int * pn) static
Reorder the loops in the LP_LOOP order.
Right now they are top-sorted according to the parent relationship, but otherwise unordered. Here we use a more constructive sort, so a loops children are contiguous to the loop. fill LP_DFN with DFN of loop, and LP_CHILDDFN with DFN of last child.
Definition at line 1647 of file redundss.c.
References add_dfn_loop(), LP_CHILD, LP_CHILDDFN, LP_DFN, LP_LOOP, and LP_SIBLING.
Referenced by add_dfn_loop(), and reorder_dfn_loops().
addcomponents()
static int addcomponents (int lop, int optype, int rop, int l) static
Definition at line 880 of file redundss.c.
References A_OPTYPEG, ast, mk_binop(), mk_unop(), modified(), OP_ADD, OP_SUB, optype(), and tmp.
Referenced by distribute(), findcomponents(), and MakeReplacement().
addSS()
static void addSS (int ss, int type, int l) static
Definition at line 173 of file redundss.c.
References A_MOREP, DBGBIT, gbl, printast(), ss, SS_ALL, SS_ALL_MULTIPLE, SSlisthead, SSlisttail, and type.
Referenced by markrootss(), and markss().
addssassignments()
static int addssassignments (int before, int beforefg, int rewrite, int par, int task) static
Definition at line 1377 of file redundss.c.
References add_stmt_before(), ast, ast_replace(), ast_rewrite(), DBGBIT, dt, gany, getcctmp_sc(), lhs, mk_id(), mk_stmt(), par, printast(), SSlisthead, std, STD_FG, STD_PAR, STD_TASK, task, and Trace.
Referenced by basic_block_redundant(), and reassociate().
basic_block_redundant()
static void basic_block_redundant (void) static
Definition at line 1579 of file redundss.c.
References addssassignments(), ast_unvisit(), ast_visit(), astb, ASTB::atypes, fg, FG_LNEXT, FG_STDFIRST, findssexprs(), markmodifiedexprs(), OnlyFG, propagatemodified(), rewritefg(), SS_ALL_MULTIPLE, SS_INV_ROOT_MULTIPLE, STD_AST, STD_NEXT, STD_PAR, STD_TASK, and Trace.
Referenced by redundss().
clearSSlist()
static void clearSSlist (void) static
Definition at line 137 of file redundss.c.
References InitSSlist(), ss, and SSlisthead.
Referenced by findssexprs().
count_nest()
static LOGICAL count_nest (int ast, int * dummy) static
Definition at line 370 of file redundss.c.
References ast, FALSE, sptr, sptr_of_subscript(), subscrnest, and XBIT.
Referenced by findssexprsfg().
distribute()
static int distribute (int factor, int sum, int l) static
Definition at line 1256 of file redundss.c.
References addcomponents(), ast, findcomponents(), findmulcomponents(), mulcomponents(), OP_ADD, and sum().
Referenced by MakeReplacement().
Done()
static void Done (void) static
Definition at line 1631 of file redundss.c.
References STB::dt, freearea(), opt, optshrd_end(), PSI_AREA, stb, and STG_DELETE_SIDECAR.
Referenced by redundss().
dumpSSlist()
static void dumpSSlist (void) static
Definition at line 439 of file redundss.c.
References ast, gbl, printast(), and SSlisthead.
Referenced by findssexprs(), and propagatemodified().
findcomponents()
static void findcomponents (int ast, int l, int * pinv, int * pvar) static
Definition at line 1139 of file redundss.c.
References A_OPTYPEG, addcomponents(), ast, findcomponents(), findmulcomponents(), modified(), mulcomponents(), negatecomponent(), OP_ADD, OP_MUL, OP_SUB, and optype().
Referenced by distribute(), findcomponents(), and MakeReplacement().
findmulcomponents()
static void findmulcomponents (int ast, int l, int * pinv, int * pvar) static
Definition at line 1087 of file redundss.c.
References A_OPTYPEG, ast, astb, findmulcomponents(), ASTB::i1, modified(), mulcomponents(), negatecomponent(), OP_ADD, OP_MUL, and OP_SUB.
Referenced by distribute(), findcomponents(), findmulcomponents(), and MakeReplacement().
findss()
static void findss (int ast, int * dummy) static
Definition at line 389 of file redundss.c.
References ASD_NDIM, ASD_SUBS, ast, findssl, findsstype, markrootss(), s, ss, and subscrnest.
Referenced by findssexprsfg().
findssexprs()
static void findssexprs (int l, int newstmts, int type, int onlyfg, int parlevel) static
Definition at line 455 of file redundss.c.
References ast_unvisit(), ast_visit(), clearSSlist(), DBGBIT, dumpSSlist(), fg, FG_NEXT, FG_PAR, findssexprsfg(), findssl, findsstype, LP_FG, Trace, and type.
Referenced by basic_block_redundant(), and reassociate().
findssexprsfg()
static void findssexprsfg (int l, int fg, int newstmts, int type) static
Definition at line 418 of file redundss.c.
References ast, ast_traverse(), count_nest(), fg, FG_STDFIRST, FG_STDLAST, findss(), markrootss(), NULL, std, STD_AST, STD_NEXT, Trace, and type.
Referenced by findssexprs().
Init()
static void Init (void) static
Definition at line 1615 of file redundss.c.
References CallAppears, STB::dt, InitAST(), InitSSlist(), NULL, OnlyFG, stb, STG_ALLOC_SIDECAR, and STG_CLEAR_ALL.
Referenced by redundss().
InitAST()
static void InitAST (void) static
Definition at line 88 of file redundss.c.
References A_MOREP, ast, and astb.
Referenced by Init().
InitSSlist()
static void InitSSlist (void) static
Definition at line 131 of file redundss.c.
References SSlisthead, and SSlisttail.
Referenced by clearSSlist(), and Init().
inloop()
static int inloop (int m, int l) static
Definition at line 710 of file redundss.c.
References LP_CHILDDFN, LP_DFN, m, and OnlyFG.
Referenced by dd_edge(), and propagatemodified().
MakeReplacement()
static int MakeReplacement (int ast, int l) static
Definition at line 1276 of file redundss.c.
References A_OPTYPEG, addcomponents(), ASD_NDIM, ASD_SUBS, ast, distribute(), findcomponents(), findmulcomponents(), MakeReplacement(), MAXSUBS, mixedsum(), mk_convert(), mk_subscr(), modified(), mulcomponents(), negatecomponent(), OP_ADD, OP_MUL, OP_SUB, optype(), s, sptr, sptr_of_subscript(), subscr, and XBIT.
Referenced by MakeReplacement(), and reassociate().
mark()
static void mark (int ast, int l) static
Definition at line 491 of file redundss.c.
References a, ast, DBGBIT, DDTG, DtypeAssigned, gbl, interr(), mark(), printast(), and sptr.
Referenced by mark(), and markmodified().
markmodified()
static void markmodified (int ast, int * pl) static
Definition at line 554 of file redundss.c.
References a, A_ARGCNTG, A_OPTYPEG, arg, argt, ARGT_ARG, ast, ASTLI_NEXT, ASTLI_SPTR, aux, CallAppears, AUX::dpdsc_base, DtypeAssigned, getF90TmplSectRtn(), mark(), memsym_of_ast(), mk_id(), NOSYM, sptr, sym_of_ast(), and SYMNAME.
Referenced by markmodifiedexprsfg().
markmodifiedexprs()
static void markmodifiedexprs (int l, int onlyfg) static
Definition at line 743 of file redundss.c.
References ast_unvisit_norepl(), ast_visit(), fg, FG_NEXT, LP_FG, and markmodifiedexprsfg().
Referenced by basic_block_redundant(), and reassociate().
markmodifiedexprsfg()
static void markmodifiedexprsfg (int l, int fg) static
Definition at line 728 of file redundss.c.
References ast_traverse(), fg, FG_STDFIRST, FG_STDLAST, markmodified(), NULL, std, STD_AST, and STD_NEXT.
Referenced by markmodifiedexprs().
markrootss()
static int markrootss (int root, int type, int l) static
Definition at line 331 of file redundss.c.
References addSS(), markss(), root, SS_INV_ROOT_MULTIPLE, and type.
Referenced by findss(), and findssexprsfg().
markss()
static int markss (int ast, int type, int l) static
Definition at line 222 of file redundss.c.
References A_MOREG, addSS(), ASD_NDIM, ASD_SUBS, ast, markss(), modified(), s, sptr, sptr_of_subscript(), ss, SS_ALL, SS_INV_ROOT, SS_INV_ROOT_MULTIPLE, type, and XBIT.
Referenced by markrootss(), and markss().
mixedsum()
static LOGICAL mixedsum (int ast, int l) static
Definition at line 1212 of file redundss.c.
References A_OPTYPEG, ast, FALSE, mixedsum(), modified(), OP_ADD, OP_SUB, and TRUE.
Referenced by MakeReplacement(), and mixedsum().
modified()
static int modified (int ast, int l) static
Definition at line 107 of file redundss.c.
References ast, LP_CHILDDFN, LP_DFN, m, and OnlyFG.
Referenced by addcomponents(), findcomponents(), findmulcomponents(), MakeReplacement(), markss(), mixedsum(), mulcomponents(), and propagatemodified().
mulcomponents()
static int mulcomponents (int lop, int rop, int l) static
Definition at line 1040 of file redundss.c.
References A_OPTYPEG, ast, astb, ASTB::i1, mk_binop(), mk_unop(), modified(), OP_MUL, and OP_SUB.
Referenced by distribute(), findcomponents(), findmulcomponents(), and MakeReplacement().
negatecomponent()
static int negatecomponent (int lop, int l) static
Definition at line 1016 of file redundss.c.
References A_OPTYPEG, ast, mk_binop(), mk_unop(), and OP_SUB.
Referenced by findcomponents(), findmulcomponents(), and MakeReplacement().
propagatemodified()
static void propagatemodified (int l) static
Definition at line 768 of file redundss.c.
References ASD_NDIM, ASD_SUBS, ast, CallAppears, DBGBIT, DDTG, DtypeAssigned, dumpSSlist(), inloop(), mem(), mk_id(), modified(), s, sptr, and SSlisthead.
Referenced by basic_block_redundant(), and reassociate().
reassociate()
static void reassociate (void) static
Definition at line 1467 of file redundss.c.
References add_fg(), add_loop_preheader(), addssassignments(), ast, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), astb, DBGBIT, dstda(), fg, FG_LPREV, FG_NEXT, FG_PAR, FG_STDFIRST, FG_STDLAST, findssexprs(), gany, gbl, LP_FG, LP_HEAD, LP_LOOP, LP_PARLOOP, MakeReplacement(), markmodifiedexprs(), OPT::nloops, opt, OPT::pre_fg, printast(), propagatemodified(), rdilts(), rewritefg(), SS_ALL, SS_INV_ROOT, SS_ROOT, SSlisthead, std, STD_AST, STD_NEXT, STD_PAR, STD_TASK, Trace, and wrilts().
Referenced by redundss().
redundss()
void redundss (void)
Definition at line 1677 of file redundss.c.
References basic_block_redundant(), DBGBIT, Done(), dumpfgraph(), dumploops(), findloop(), flowgraph(), gany, gbl, HLOPT_ALL, Init(), NULL, optshrd_init(), reassociate(), reorder_dfn_loops(), Trace, and XBIT.
reorder_dfn_loops()
void reorder_dfn_loops ()
Definition at line 1660 of file redundss.c.
References add_dfn_loop(), ERR_Severe, interr(), LP_CHILD, LP_DFN, LP_SIBLING, n, OPT::nloops, opt, and STG_ALLOC_SIDECAR.
Referenced by redundss().
rewritefg()
static void rewritefg (int fg) static
Definition at line 1416 of file redundss.c.
References ast, ast_rewrite(), fg, FG_STDFIRST, FG_STDLAST, mk_stmt(), std, STD_AST, STD_DELETE, STD_LABEL, STD_NEXT, STD_PREV, and Trace.
Referenced by basic_block_redundant(), and reassociate().
STG_DECLARE() [1/2]
STG_DECLARE (DT_Assigned , int)
STG_DECLARE() [2/2]
STG_DECLARE (lpinfo , lpinfo_t)
TraceOutput()
static void TraceOutput (const char * fmt, ...) static
Definition at line 25 of file redundss.c.
References DBGBIT, and gbl.
Variable Documentation
CallAppears
int CallAppears = 0 static
Definition at line 485 of file redundss.c.
Referenced by Init(), markmodified(), and propagatemodified().
findssl
int findssl static
Definition at line 366 of file redundss.c.
Referenced by findss(), and findssexprs().
findsstype
int findsstype static
Definition at line 366 of file redundss.c.
Referenced by findss(), and findssexprs().
gany
int gany = 0 static
Definition at line 1371 of file redundss.c.
Referenced by addssassignments(), reassociate(), and redundss().
OnlyFG
int OnlyFG = 0 static
Definition at line 99 of file redundss.c.
Referenced by basic_block_redundant(), Init(), inloop(), and modified().
SSlisthead
int SSlisthead static
Definition at line 126 of file redundss.c.
Referenced by addSS(), addssassignments(), clearSSlist(), dumpSSlist(), InitSSlist(), propagatemodified(), and reassociate().
SSlisttail
int SSlisttail static
Definition at line 126 of file redundss.c.
Referenced by addSS(), and InitSSlist().
subscrnest
int subscrnest = 0 static
Definition at line 368 of file redundss.c.
Referenced by count_nest(), and findss().