flang: regutil.cpp File Reference
regutil.cpp File Reference
Register allocation module used by the expander and the optimizer.
#include "gbldefs.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "ili.h"
#include "expand.h"
#include "regutil.h"
#include "machreg.h"
#include "machar.h"
Macros
#define RATA_ALL RATA_KR
Functions
static const char * get_msize (int)
void reg_init (int entr)
...
void addrcand (int ilix)
Add a potential candidate, an ILI, to the appropriate candidate list.
static void dump_cand (int candl)
void dmprcand (void)
...
void dmp_rat (int rat)
void dmprat (int rat)
int getrcand (int candl)
Get a candidate from the candidate list, candl.
void endrcand (void)
Go through all of the candidate lists to reinitialize the back pointers of the names entries and ILI.
void storedums (int exitbih, int first_rat)
For ftn, all dummies which are assigned to registers and are stored into must have their values stored back into memory. These stores are added to the beginning of the exit block.
static int select_rtemp (int)
void mkrtemp_init (void)
This routine initializes for temporaries created during an ILM block. This guarantees that the temps used will be unique for a given block.
SPTR mkrtemp (int ilix)
This routine makes a temporary and returns its symbol table index. The rtemp entry which is used is determined by the type of the ILI which needs a temporary to store its value.
SPTR mkrtemp_sc (int ilix, SC_KIND sc)
This routine makes a temporary and returns its symbol table index. The rtemp entry which is used is determined by the type of the ILI which needs a temporary to store its value.
SPTR mkrtemp_cpx (DTYPE dtype)
This routine makes a complex temporary and returns its symbol table index. The rtemp entry which is used is determined by the dtype.
SPTR mkrtemp_cpx_sc (DTYPE dtype, SC_KIND sc)
...
SPTR mkrtemp_arg1_sc (DTYPE dtype, SC_KIND sc)
...
void mkrtemp_end (void)
This routine ends the temp processing for a function. Values are updated so that temps created for the next function are unique from the temps created during the current function.
void mkrtemp_copy (int *rt)
This routine copies the maximum values of the temporaries currently allocated – this is typically used at the start of optimizing a function.
void mkrtemp_update (int *rt)
This routine keeps track of the maximum values of rtemps in rt.
void mkrtemp_reinit (int *rt)
This routine resets the rtemps values from rt.
int assn_rtemp (int ili)
...
static int _assn_rtemp (int ili, int temp)
void assn_input_rtemp (int ili, int temp)
...
int assn_rtemp_sc (int ili, SC_KIND sc)
...
int assn_sclrtemp (int ili, SC_KIND sc)
...
Variables
static const char * atype_names []
int il_rtype_df [RATA_RTYPES_TOTAL]
int il_mv_rtype [RATA_RTYPES_TOTAL]
struct {
const char prefix
const char * arg1pfx
DTYPE dt
int current
int start
int max
} rtemps []
Detailed Description
Register allocation module used by the expander and the optimizer.
Contains:
void reg_init(int) - initializes the register information for a function
void addrcand(int) - adds an ILI to the appropriate candidate list
void static dump_cand(int) - dumps a candidate list for debug purposes
void dmprcand() - dumps the register candidate lists for debug purposes
void dmprat(int) - dumps the register assign table for a block
int getrcand(int) - gets a candidate for register assignment from a candidate list
void endrcand() - clean up the register candidate lists
void storedums(int, int) - store back dummies assigned registers (SCFTN only)
void mkrtemp_init() - initialize for register temporaries created for a function
int mkrtemp(int) - create a register temporary (based on ili)
int mkrtemp_sc(int, int) - same as mkrtemp(), but storage class is passed
int mkrtemp_cpx(int)- create a complex register temporary (base on dtype)
int mkrtemp_cpx_sc(int, int)- same as mkrtemp_cpx(), but storage class is passed
void mkrtemp_end() - end the register temporaries for the current function
void mkrtemp_update(int[]) - record maximum values of register temporaries
void mkrtemp_reinit(int[]) - initialize for register temporaries from the recorded set of values
void mkrtemp_copy(int[]) - copy maximum values of register temporaries
int assn_rtemp(int) - assign a register temporary for an ili and make a candidate.
int assn_rtemp_sc(int, int) - same as assn_rtemp, but storage class is passed
Definition in file regutil.cpp.
Macro Definition Documentation
RATA_ALL
#define RATA_ALL RATA_KR
Definition at line 51 of file regutil.cpp.
Function Documentation
_assn_rtemp()
static int _assn_rtemp (int ili, int temp) static
Definition at line 1110 of file regutil.cpp.
References ERR_Severe, FLANG_FALLTHROUGH, GET_RCAND, IL_RES, IL_VECT, ili, ili_get_vect_dtype(), ILI_OPC, ILI_RAT, ILIA_AR, ILIA_CD, ILIA_CS, ILIA_DP, ILIA_IR, ILIA_KR, ILIA_LNK, ILIA_SP, interr(), MSZ_F16, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_PTR, MSZ_WORD, RATA_AR, RATA_CDP, RATA_CSP, RATA_DP, RATA_IR, RATA_KR, RATA_SP, RATA_TEMP, RATA_VECT, REG::rcand, RCAND_ATYPE, RCAND_CONFL, RCAND_COUNT, RCAND_MSIZE, RCAND_NEXT, RCAND_RTYPE, RCAND_TEMP, RCAND_VAL, and reg.
Referenced by assn_input_rtemp(), assn_rtemp_sc(), and assn_sclrtemp().
addrcand()
void addrcand (int ilix)
Add a potential candidate, an ILI, to the appropriate candidate list.
...
Definition at line 87 of file regutil.cpp.
References assert, ERR_Severe, GET_RCAND, ILI_OPC, ILI_OPND, ILI_RAT, msize, MSZ_F16, MSZ_F32, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_PTR, MSZ_WORD, NME_RAT, RATA_AR, RATA_CDP, RATA_CONST, RATA_CSP, RATA_DP, RATA_ILI, RATA_IR, RATA_KR, RATA_NME, RATA_SP, REG::rcand, RCAND_ATYPE, RCAND_CONFL, RCAND_COUNT, RCAND_MSIZE, RCAND_NEXT, RCAND_OLOAD, RCAND_RTYPE, RCAND_STORE, RCAND_VAL, rcandb, reg, and RCANDB::weight.
Referenced by exp_rcand().
assn_input_rtemp()
void assn_input_rtemp (int ili, int temp)
...
Definition at line 1204 of file regutil.cpp.
References _assn_rtemp(), and ili.
assn_rtemp()
int assn_rtemp (int ili)
...
Definition at line 1101 of file regutil.cpp.
References assn_rtemp_sc(), ili, and SC_AUTO.
assn_rtemp_sc()
int assn_rtemp_sc (int ili, SC_KIND sc)
...
Definition at line 1210 of file regutil.cpp.
References _assn_rtemp(), ili, and mkrtemp_sc().
Referenced by assn_rtemp().
assn_sclrtemp()
int assn_sclrtemp (int ili, SC_KIND sc)
...
Definition at line 1218 of file regutil.cpp.
References _assn_rtemp(), getsymbol(), ili, name, rtemps, select_rtemp(), and type.
dmp_rat()
void dmp_rat (int rat)
Definition at line 489 of file regutil.cpp.
References atype_names, gbl, get_msize(), ILI_OPC, ILI_OPND, ilis, KR_LSH, KR_MSH, name, print_nme(), RAT_ADDR, RAT_ATYPE, RAT_CONFL, RAT_MSIZE, RAT_REG, RAT_RTYPE, RAT_STORE, RAT_VAL, RATA_AR, RATA_CDP, RATA_CQP, RATA_CSP, RATA_DP, RATA_ILI, RATA_IR, RATA_KR, RATA_NME, RATA_RPL, RATA_SP, RATA_TEMP, RATA_VECT, val, and void().
Referenced by dmprat().
dmprat()
void dmprat (int rat)
Definition at line 607 of file regutil.cpp.
References dmp_rat(), gbl, and RAT_VAL.
Referenced by reg_assign1().
dmprcand()
void dmprcand (void)
...
Definition at line 442 of file regutil.cpp.
References dump_cand(), gbl, RATA_AR, RATA_CDP, RATA_CSP, RATA_DP, RATA_IR, RATA_KR, RATA_SP, RATA_VECT, REG::rcand, and reg.
Referenced by reg_assign1().
dump_cand()
static void dump_cand (int candl) static
Definition at line 351 of file regutil.cpp.
References ACONOFFG, atype_names, fflush(), gbl, get_msize(), getprint(), i, IL_TYPE, ILI_OPC, ILI_OPND, ilis, ILTY_LOAD, ILTY_STORE, ISZ_PF, name, print_nme(), RATA_ARR, RATA_CONST, RATA_ILI, RATA_IND, RATA_NME, RATA_RPL, RATA_TEMP, RATA_VECT, RCAND_ATYPE, RCAND_CONFL, RCAND_COUNT, RCAND_CSE, RCAND_IGNORE, RCAND_INV, RCAND_MSIZE, RCAND_NEXT, RCAND_NOREG, RCAND_OK, RCAND_RTYPE, RCAND_STORE, RCAND_TEMP, RCAND_VAL, and val.
Referenced by dmprcand().
endrcand()
void endrcand (void)
Go through all of the candidate lists to reinitialize the back pointers of the names entries and ILI.
...
The regs' rcand fields are set to null, and the register candidate list is reset.
Definition at line 672 of file regutil.cpp.
References ERR_Severe, FLANG_FALLTHROUGH, i, ILI_OPND, ILI_RAT, interr(), NME_RAT, RATA_ALL, RATA_ARR, RATA_CDP, RATA_CONST, RATA_CSP, RATA_ILI, RATA_IND, RATA_NME, RATA_RPL, RATA_TEMP, RATA_UPLV, RATA_VECT, REG::rcand, RCAND_ATYPE, RCAND_NEXT, RCAND_OLOAD, RCAND_TEMP, RCAND_VAL, rcandb, reg, RCANDB::stg_avail, and val.
Referenced by reg_assign1().
get_msize()
static const char * get_msize (int msz) static
Definition at line 558 of file regutil.cpp.
References ERR_Warning, interr(), msz, MSZ_F16, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_PTR, MSZ_SBYTE, MSZ_SHWORD, MSZ_SLWORD, MSZ_SWORD, MSZ_UBYTE, MSZ_UHWORD, MSZ_ULWORD, and p.
Referenced by dmp_rat(), and dump_cand().
getrcand()
int getrcand (int candl)
Get a candidate from the candidate list, candl.
...
Definition at line 628 of file regutil.cpp.
References count, RCANDB::count, GR_THRESHOLD, RCAND_CONFL, RCAND_COUNT, RCAND_NEXT, and rcandb.
Referenced by assign1().
mkrtemp()
SPTR mkrtemp (int ilix)
This routine makes a temporary and returns its symbol table index. The rtemp entry which is used is determined by the type of the ILI which needs a temporary to store its value.
...
Definition at line 904 of file regutil.cpp.
References mkrtemp_sc(), and SC_AUTO.
mkrtemp_arg1_sc()
SPTR mkrtemp_arg1_sc (DTYPE dtype, SC_KIND sc)
...
Definition at line 999 of file regutil.cpp.
References arg1pfx, current, dt, DT_CMPLX, DT_DCMPLX, ERR_Severe, getccssym_sc(), index, interr(), max, mkrtemp_cpx_sc(), rtemps, and type.
Referenced by exp_qjsr().
mkrtemp_copy()
void mkrtemp_copy (int * rt)
This routine copies the maximum values of the temporaries currently allocated – this is typically used at the start of optimizing a function.
...
Definition at line 1063 of file regutil.cpp.
References i, rtemps, and RTEMPS.
mkrtemp_cpx()
SPTR mkrtemp_cpx (DTYPE dtype)
This routine makes a complex temporary and returns its symbol table index. The rtemp entry which is used is determined by the dtype.
...
Also used for INTEGER*8 support to allocate 64-bit temporaries for 64-bit int argument expressions.
Definition at line 944 of file regutil.cpp.
References mkrtemp_cpx_sc(), and SC_AUTO.
mkrtemp_cpx_sc()
SPTR mkrtemp_cpx_sc (DTYPE dtype, SC_KIND sc)
...
Definition at line 958 of file regutil.cpp.
References current, dt, DT_CMPLX, DT_DCMPLX, ERR_Severe, getccsym_sc(), index, interr(), max, prefix, rtemps, and type.
Referenced by cmplx_to_mem(), exp_call(), exp_zqjsr(), mkrtemp_arg1_sc(), and mkrtemp_cpx().
mkrtemp_end()
void mkrtemp_end (void)
This routine ends the temp processing for a function. Values are updated so that temps created for the next function are unique from the temps created during the current function.
...
Definition at line 1049 of file regutil.cpp.
References i, rtemps, and RTEMPS.
Referenced by exp_end(), and llvmAddConcurExitBlk().
mkrtemp_init()
void mkrtemp_init (void)
This routine initializes for temporaries created during an ILM block. This guarantees that the temps used will be unique for a given block.
...
Definition at line 883 of file regutil.cpp.
References assert, ERR_Severe, i, rtemps, and RTEMPS.
Referenced by exp_header(), and exp_misc().
mkrtemp_reinit()
void mkrtemp_reinit (int * rt)
This routine resets the rtemps values from rt.
...
Definition at line 1090 of file regutil.cpp.
References i, rtemps, and RTEMPS.
mkrtemp_sc()
SPTR mkrtemp_sc (int ilix, SC_KIND sc)
This routine makes a temporary and returns its symbol table index. The rtemp entry which is used is determined by the type of the ILI which needs a temporary to store its value.
...
Definition at line 915 of file regutil.cpp.
References current, dt, getccsym_sc(), index, max, prefix, rtemps, select_rtemp(), and type.
Referenced by assn_rtemp_sc(), check_ilm(), exp_bran(), exp_call(), genswitch(), and mkrtemp().
mkrtemp_update()
void mkrtemp_update (int * rt)
This routine keeps track of the maximum values of rtemps in rt.
...
Definition at line 1076 of file regutil.cpp.
References i, max, rtemps, and RTEMPS.
reg_init()
void reg_init (int entr)
...
Definition at line 76 of file regutil.cpp.
References ENTRY::arasgn, aux, RCANDB::const_cnt, AUX::curr_entry, mr_init(), NULL, rcandb, and RCANDB::static_cnt.
Referenced by exp_header(), and llvmAddConcurEntryBlk().
select_rtemp()
static int select_rtemp (int ili) static
Definition at line 1261 of file regutil.cpp.
References dt, ERR_Severe, FLANG_FALLTHROUGH, IL_RES, IL_VECT, ili, ili_get_vect_dtype(), ILI_OPC, ILIA_AR, ILIA_CD, ILIA_CQ, ILIA_CS, ILIA_DP, ILIA_FLOAT128, ILIA_IR, ILIA_KR, ILIA_LNK, ILIA_QP, ILIA_SP, interr(), rtemps, and type.
Referenced by assn_sclrtemp(), and mkrtemp_sc().
storedums()
void storedums (int exitbih, int first_rat)
For ftn, all dummies which are assigned to registers and are stored into must have their values stored back into memory. These stores are added to the beginning of the exit block.
...
Definition at line 773 of file regutil.cpp.
References ad3ili(), ad4ili(), addilt(), addr, basesym_of(), BIH_SMOVE, cnt, i, IS_DUM, MSZ_F16, MSZ_F4, MSZ_F8, MSZ_I8, RAT_ADDR, RAT_MSIZE, RAT_REG, RAT_RTYPE, RAT_STORE, RAT_VAL, RATA_AR, RATA_CDP, RATA_CSP, RATA_DP, RATA_IR, RATA_KR, RATA_SP, rdilts(), void(), and wrilts().
Referenced by reg_assign1().
Variable Documentation
arg1pfx
const char* arg1pfx
Definition at line 849 of file regutil.cpp.
Referenced by mkrtemp_arg1_sc().
atype_names
const char* atype_names[] static
Initial value:
= {"nme ", "cons", "ili ", "temp",
                                    "ind ", "arr ", "rpl "}
Definition at line 53 of file regutil.cpp.
Referenced by dmp_rat(), and dump_cand().
current
int current
Definition at line 851 of file regutil.cpp.
Referenced by ENT3F(), eval_transfer(), ll_destroy_basic_block(), ll_destroy_function(), ll_destroy_mem(), ll_destroy_module(), mkrtemp_arg1_sc(), mkrtemp_cpx_sc(), mkrtemp_sc(), prng_loop_d_lf(), prng_loop_d_npb(), prng_loop_r_lf(), and prng_loop_r_npb().
dt
DTYPE dt
Definition at line 850 of file regutil.cpp.
Referenced by _do_iface(), add_arrnme(), add_private_allocatable(), add_typroc(), addssassignments(), build_sym_nme(), chk_expr(), chk_var(), cng_inttyp(), combine_fdiv(), compute_size_expr(), conv_forall(), convert_dtype(), copy_desc_to_bnds_vars(), create_threadprivate_dtype(), ddt(), decl_private_sym(), dumpdt(), dumpdts(), eval_init_op(), exp_call(), exp_load(), exp_store(), fill_argt_with_alnd(), find_parent_member(), fix_dtype(), Ftn_izext(), Ftn_jzext(), func_call2(), gen_allocatable_result(), gen_array_result(), gen_char_result(), gen_defer_shape(), gen_llvm_expr(), gen_pointer_result(), gen_sincos(), gen_spec_item_tmp(), get_atmp(), get_semaphore(), get_static_type_descriptor(), getMergeSym(), handle_arguments(), iface_arg(), intrinsic_as_arg(), is_deferlenchar_ast(), is_deferlenchar_dtype(), lower_do_stmt(), lower_function(), mk_assumed_shape(), mk_cmp(), mk_component_ast(), mk_defer_shape(), mk_int(), mkarg(), mkarglist(), mkexpr2(), mkrtemp_arg1_sc(), mkrtemp_cpx_sc(), mkrtemp_sc(), nml_emit_desc(), pp_entries(), pp_entries_mixedstrlen(), pr_dent(), ptrfunc_call(), read_datatype(), read_init(), read_symbol(), select_rtemp(), semant3(), set_kind_result(), and transform_c_f_pointer().
il_mv_rtype
int il_mv_rtype[RATA_RTYPES_TOTAL]
Initial value:
= {
    IL_MVIR, IL_MVSP,
    IL_MVDP, IL_MVAR,
    IL_MVKR, 0,
    0,       0,
    0,       0,
    0,       0,
}
Definition at line 66 of file regutil.cpp.
il_rtype_df
int il_rtype_df[RATA_RTYPES_TOTAL]
Initial value:
= {
    IL_IRDF, IL_SPDF,
    IL_DPDF, IL_ARDF,
    IL_KRDF, 0,
    0,       0,
    0,       0,
    0,       0,
}
Definition at line 58 of file regutil.cpp.
max
int max
Definition at line 853 of file regutil.cpp.
Referenced by _mr_getreg(), const_eval(), find_max_of_mask_calls_pos(), inline_hlocalizebnds(), is_same_mask_in_fused(), mkrtemp_arg1_sc(), mkrtemp_cpx_sc(), mkrtemp_sc(), mkrtemp_update(), prntgm(), tablea(), and tableu().
prefix
const char prefix
Definition at line 848 of file regutil.cpp.
Referenced by get_dtype_init_template(), intrin_name(), intrin_name_bsik(), ll_convert_struct_dtype(), ll_get_array_type(), ll_get_outlined_funcname(), ll_get_vector_type(), ll_write_function(), mkrtemp_cpx_sc(), mkrtemp_sc(), unique_name(), write_extern_inits(), and write_mdfield().
struct { ... } rtemps[]
Initial value:
= {
    {'D', "Da", DT_INT, 0, 0, -1},
    {'G', "Ga", DT_CPTR, 0, 0, -1},
    {'H', "Ha", DT_FLOAT, 0, 0, -1},
    {'K', "Ka", DT_DBLE, 0, 0, -1},
    {'g', "ga", DT_INT8, 0, 0, -1},
    {'h', "ha", DT_CMPLX, 0, 0, -1},
    {'k', "ka", DT_DCMPLX, 0, 0, -1},
    {'h', "ha", DT_NONE, 0, 0, -1},
    {'v', "va", DT_NONE, 0, 0, -1},
    {'X', "Xa", DT_NONE, 0, 0, -1},
    {'x', "xa", DT_NONE, 0, 0, -1},
}
Referenced by assn_sclrtemp(), mkrtemp_arg1_sc(), mkrtemp_copy(), mkrtemp_cpx_sc(), mkrtemp_end(), mkrtemp_init(), mkrtemp_reinit(), mkrtemp_sc(), mkrtemp_update(), and select_rtemp().
start
int start
Definition at line 852 of file regutil.cpp.