flang: regutil.h File Reference
regutil.h File Reference
Machine independent register utilities.
#include <stdint.h>
Classes
struct LST_TAG
struct arasgntag
struct RAT
struct RATB
struct RCAND
struct RCANDB
Macros
#define RTEMPS 11
#define LST_AREA 6
#define AR_AREA 7
#define ADDNODE(l, entry)
#define RATA_IR 0
#define RATA_SP 1
#define RATA_DP 2
#define RATA_AR 3
#define RATA_KR 4
#define RATA_VECT 5
#define RATA_QP 6
#define RATA_CSP 7
#define RATA_CDP 8
#define RATA_CQP 9
#define RATA_X87 10
#define RATA_CX87 11
#define RATA_RTYPES_ACTIVE RATA_X87
#define RATA_SPXM 12
#define RATA_DPXM 13
#define RATA_RTYPES_TOTAL RATA_DPXM + 1
#define RATA_NME 0
#define RATA_CONST 1
#define RATA_ILI 2
#define RATA_TEMP 3
#define RATA_IND 4
#define RATA_ARR 5
#define RATA_RPL 6
#define RATA_UPLV 7
#define RAT_REG(i) ratb.stg_base[i].reg
#define RAT_ADDR(i) ratb.stg_base[i].addr
#define RAT_RTYPE(i) ratb.stg_base[i].rtype
#define RAT_ATYPE(i) ratb.stg_base[i].atype
#define RAT_FLAGS(i) ratb.stg_base[i].flags.all
#define RAT_CONFL(i) ratb.stg_base[i].flags.bits.confl
#define RAT_STORE(i) ratb.stg_base[i].flags.bits.store
#define RAT_EINT(i) ratb.stg_base[i].flags.bits.eint
#define RAT_VINT(i) ratb.stg_base[i].flags.bits.vint
#define RAT_MSIZE(i) ratb.stg_base[i].msize
#define RAT_VAL(i) ratb.stg_base[i].val
#define RAT_ISIR(i) (RAT_RTYPE(i) == RATA_IR)
#define RAT_ISAR(i) (RAT_RTYPE(i) == RATA_AR)
#define RAT_ISSP(i) (RAT_RTYPE(i) == RATA_SP)
#define RAT_ISDP(i) (RAT_RTYPE(i) == RATA_DP)
#define RAT_ISCSP(i) (RAT_RTYPE(i) == RATA_CSP)
#define RAT_ISCDP(i) (RAT_RTYPE(i) == RATA_CDP)
#define RAT_ISCQP(i) (RAT_RTYPE(i) == RATA_CQP)
#define RAT_ISKR(i) (RAT_RTYPE(i) == RATA_KR)
#define RAT_ISNME(i) (RAT_ATYPE(i) == RATA_NME)
#define RAT_ISCONST(i) (RAT_ATYPE(i) == RATA_CONST)
#define RAT_ISILI(i) (RAT_ATYPE(i) == RATA_ILI)
#define RAT_ISTEMP(i) (RAT_ATYPE(i) == RATA_TEMP)
#define RAT_ISUPLV(i) (RAT_ATYPE(i) == RATA_UPLV)
#define MAXRAT 67108864
#define GET_RAT(i)
#define RCAND_RTYPE(i) rcandb.stg_base[i].rtype
#define RCAND_ATYPE(i) rcandb.stg_base[i].atype
#define RCAND_FLAGS(i) rcandb.stg_base[i].flags.all
#define RCAND_CONFL(i) rcandb.stg_base[i].flags.bits.confl
#define RCAND_STORE(i) rcandb.stg_base[i].flags.bits.store
#define RCAND_CSE(i) rcandb.stg_base[i].flags.bits.cse
#define RCAND_OK(i) rcandb.stg_base[i].flags.bits.ok
#define RCAND_NOREG(i) rcandb.stg_base[i].flags.bits.noreg
#define RCAND_IGNORE(i) rcandb.stg_base[i].flags.bits.ignore
#define RCAND_EINT(i) rcandb.stg_base[i].flags.bits.eint
#define RCAND_VINT(i) rcandb.stg_base[i].flags.bits.vint
#define RCAND_INV(i) rcandb.stg_base[i].flags.bits.inv
#define RCAND_TINV(i) rcandb.stg_base[i].flags.bits.tinv
#define RCAND_MSIZE(i) rcandb.stg_base[i].msize
#define RCAND_VAL(i) rcandb.stg_base[i].val
#define RCAND_TEMP(i) rcandb.stg_base[i].temp
#define RCAND_NEXT(i) rcandb.stg_base[i].next
#define RCAND_COUNT(i) rcandb.stg_base[i].count
#define RCAND_OLOAD(i) rcandb.stg_base[i].oload
#define RCAND_OCAND(i) rcandb.stg_base[i].ocand
#define RCAND_RAT(i) rcandb.stg_base[i].rat
#define RCAND_ISNME(i) (RCAND_ATYPE(i) == RATA_NME)
#define RCAND_ISCONST(i) (RCAND_ATYPE(i) == RATA_CONST)
#define RCAND_ISILI(i) (RCAND_ATYPE(i) == RATA_ILI)
#define RCAND_ISTEMP(i) (RCAND_ATYPE(i) == RATA_TEMP)
#define RCAND_ISUPLV(i) (RCAND_ATYPE(i) == RATA_UPLV)
#define MAXRCAND 131072
#define GET_RCAND(i)
#define IS_LCL(s) (SCG(s) == SC_LOCAL || SCG(s) == SC_PRIVATE)
#define IS_EXTERN(s) (SC_ISCMBLK(SCG(s)) || SCG(s) == SC_EXTERN)
#define IS_STATIC(s) (SCG(s) == SC_STATIC)
#define IS_CMNBLK(s) (SC_ISCMBLK(SCG(s)))
#define IS_DUM(s) (SCG(s) == SC_DUMMY)
#define IS_LCL_OR_DUM(s) (IS_LCL(s) || IS_DUM(s))
#define IS_REGARG(s) (REGARGG(s) && REDUCG(s))
#define IS_PRIVATE(s) (SCG(s) == SC_PRIVATE)
#define RTYPE_DF(rtype) ((ILI_OP)il_rtype_df[rtype])
#define MV_RTYPE(rtype) ((ILI_OP)il_mv_rtype[rtype])
Typedefs
typedef struct LST_TAG LST
typedef struct arasgntag ARASGN
typedef enum RegConstFlags_t RegrConstFlags_t
For restricting the assignment of registers to constants per RTYPE. Used in machreg.c to init reg[...].const_flag; checked where assignments occur (i.e., globalreg.c).
Enumerations
enum RegConstFlags_t {
RCF_NONE = 0 , RCF_ALL = 1 , RCF_NOT0 = 2 , RCF_NOT32K = 4 ,
RCF_NOTL16 = 8 , RCF_NOTH16 = 0x10 , RCF_NOTA8B = 0x20 , RCF_NOTA9B = 0x40
}
For restricting the assignment of registers to constants per RTYPE. Used in machreg.c to init reg[...].const_flag; checked where assignments occur (i.e., globalreg.c).
Functions
int assn_rtemp (int ili)
...
int assn_rtemp_sc (int ili, SC_KIND sc)
...
int assn_sclrtemp (int ili, SC_KIND sc)
...
int getrcand (int candl)
...
SPTR mkrtemp_arg1_sc (DTYPE dtype, SC_KIND sc)
...
SPTR mkrtemp_cpx (DTYPE dtype)
...
SPTR mkrtemp_cpx_sc (DTYPE dtype, SC_KIND sc)
...
SPTR mkrtemp (int ilix)
...
SPTR mkrtemp_sc (int ilix, SC_KIND sc)
...
void addrcand (int ilix)
...
void assn_input_rtemp (int ili, int temp)
...
void dmprcand (void)
...
void endrcand (void)
...
void mkrtemp_copy (int *rt)
...
void mkrtemp_end (void)
...
void mkrtemp_init (void)
...
void mkrtemp_reinit (int *rt)
...
void mkrtemp_update (int *rt)
...
void reg_init (int entr)
...
void storedums (int exitbih, int first_rat)
...
Variables
RATB ratb
RCANDB rcandb
int il_rtype_df [RATA_RTYPES_TOTAL]
int il_mv_rtype [RATA_RTYPES_TOTAL]
Detailed Description
Machine independent register utilities.
C/FTN macros, typedefs, and data declarations used to access the register candidate table, the register assigned table, and the register temporaries. This information is machine independent. The machine dependent stuff is in machreg.h.
Definition in file regutil.h.
Macro Definition Documentation
ADDNODE
#define ADDNODE (l, entry)
Value:
  {                                                                \
    LST *node;                                                     \
    node = (LST *)getitem(LST_AREA, sizeof(struct LST_TAG));       \
    assert(node != 0, "no space allocated for linked-list", 0, ERR_Severe); \
    node->item = entry;                                            \
    node->next = l;                                                \
    l = node;                                                      \
  }
Definition at line 34 of file regutil.h.
AR_AREA
#define AR_AREA 7
Definition at line 26 of file regutil.h.
GET_RAT
#define GET_RAT (i)
Value:
  {                                                         \
    i = ratb.stg_avail++;                                   \
    if (ratb.stg_avail > MAXRAT)                            \
      error((error_code_t)7, ERR_Severe, 0, CNULL, CNULL); \
    NEED(ratb.stg_avail, ratb.stg_base, RAT, ratb.stg_size, \
         ratb.stg_size + 100);                              \
    if (ratb.stg_base == NULL)                              \
      error((error_code_t)7, ERR_Severe, 0, CNULL, CNULL); \
  }
Definition at line 183 of file regutil.h.
GET_RCAND
#define GET_RCAND (i)
Value:
  {                                                                 \
    i = rcandb.stg_avail++;                                         \
    if (rcandb.stg_avail > MAXRCAND)                                \
      error((error_code_t)7, ERR_Fatal, 0, CNULL, CNULL);           \
    NEED(rcandb.stg_avail, rcandb.stg_base, RCAND, rcandb.stg_size, \
         rcandb.stg_size + 100);                                    \
    if (rcandb.stg_base == NULL)                                    \
      error((error_code_t)7, ERR_Fatal, 0, CNULL, CNULL);           \
    RCAND_FLAGS(i) = 0;                                             \
    RCAND_OCAND(i) = 0;                                             \
    RCAND_RAT(i) = 0;                                               \
  }
Definition at line 281 of file regutil.h.
IS_CMNBLK
#define IS_CMNBLK (s) (SC_ISCMBLK(SCG(s)))
Definition at line 302 of file regutil.h.
IS_DUM
#define IS_DUM (s) (SCG(s) == SC_DUMMY)
Definition at line 303 of file regutil.h.
IS_EXTERN
#define IS_EXTERN (s) (SC_ISCMBLK(SCG(s)) || SCG(s) == SC_EXTERN)
Definition at line 300 of file regutil.h.
IS_LCL
#define IS_LCL (s) (SCG(s) == SC_LOCAL || SCG(s) == SC_PRIVATE)
Definition at line 299 of file regutil.h.
IS_LCL_OR_DUM
#define IS_LCL_OR_DUM (s) (IS_LCL(s) || IS_DUM(s))
Definition at line 304 of file regutil.h.
IS_PRIVATE
#define IS_PRIVATE (s) (SCG(s) == SC_PRIVATE)
Definition at line 307 of file regutil.h.
IS_REGARG
#define IS_REGARG (s) (REGARGG(s) && REDUCG(s))
Definition at line 305 of file regutil.h.
IS_STATIC
#define IS_STATIC (s) (SCG(s) == SC_STATIC)
Definition at line 301 of file regutil.h.
LST_AREA
#define LST_AREA 6
Definition at line 25 of file regutil.h.
MAXRAT
#define MAXRAT 67108864
Definition at line 181 of file regutil.h.
MAXRCAND
#define MAXRCAND 131072
Definition at line 280 of file regutil.h.
MV_RTYPE
#define MV_RTYPE (rtype) ((ILI_OP)il_mv_rtype[rtype])
Definition at line 311 of file regutil.h.
RAT_ADDR
#define RAT_ADDR (i) ratb.stg_base[i].addr
Definition at line 158 of file regutil.h.
RAT_ATYPE
#define RAT_ATYPE (i) ratb.stg_base[i].atype
Definition at line 160 of file regutil.h.
RAT_CONFL
#define RAT_CONFL (i) ratb.stg_base[i].flags.bits.confl
Definition at line 162 of file regutil.h.
RAT_EINT
#define RAT_EINT (i) ratb.stg_base[i].flags.bits.eint
Definition at line 164 of file regutil.h.
RAT_FLAGS
#define RAT_FLAGS (i) ratb.stg_base[i].flags.all
Definition at line 161 of file regutil.h.
RAT_ISAR
#define RAT_ISAR (i) (RAT_RTYPE(i) == RATA_AR)
Definition at line 169 of file regutil.h.
RAT_ISCDP
#define RAT_ISCDP (i) (RAT_RTYPE(i) == RATA_CDP)
Definition at line 173 of file regutil.h.
RAT_ISCONST
#define RAT_ISCONST (i) (RAT_ATYPE(i) == RATA_CONST)
Definition at line 177 of file regutil.h.
RAT_ISCQP
#define RAT_ISCQP (i) (RAT_RTYPE(i) == RATA_CQP)
Definition at line 174 of file regutil.h.
RAT_ISCSP
#define RAT_ISCSP (i) (RAT_RTYPE(i) == RATA_CSP)
Definition at line 172 of file regutil.h.
RAT_ISDP
#define RAT_ISDP (i) (RAT_RTYPE(i) == RATA_DP)
Definition at line 171 of file regutil.h.
RAT_ISILI
#define RAT_ISILI (i) (RAT_ATYPE(i) == RATA_ILI)
Definition at line 178 of file regutil.h.
RAT_ISIR
#define RAT_ISIR (i) (RAT_RTYPE(i) == RATA_IR)
Definition at line 168 of file regutil.h.
RAT_ISKR
#define RAT_ISKR (i) (RAT_RTYPE(i) == RATA_KR)
Definition at line 175 of file regutil.h.
RAT_ISNME
#define RAT_ISNME (i) (RAT_ATYPE(i) == RATA_NME)
Definition at line 176 of file regutil.h.
RAT_ISSP
#define RAT_ISSP (i) (RAT_RTYPE(i) == RATA_SP)
Definition at line 170 of file regutil.h.
RAT_ISTEMP
#define RAT_ISTEMP (i) (RAT_ATYPE(i) == RATA_TEMP)
Definition at line 179 of file regutil.h.
RAT_ISUPLV
#define RAT_ISUPLV (i) (RAT_ATYPE(i) == RATA_UPLV)
Definition at line 180 of file regutil.h.
RAT_MSIZE
#define RAT_MSIZE (i) ratb.stg_base[i].msize
Definition at line 166 of file regutil.h.
RAT_REG
#define RAT_REG (i) ratb.stg_base[i].reg
Definition at line 157 of file regutil.h.
RAT_RTYPE
#define RAT_RTYPE (i) ratb.stg_base[i].rtype
Definition at line 159 of file regutil.h.
RAT_STORE
#define RAT_STORE (i) ratb.stg_base[i].flags.bits.store
Definition at line 163 of file regutil.h.
RAT_VAL
#define RAT_VAL (i) ratb.stg_base[i].val
Definition at line 167 of file regutil.h.
RAT_VINT
#define RAT_VINT (i) ratb.stg_base[i].flags.bits.vint
Definition at line 165 of file regutil.h.
RATA_AR
#define RATA_AR 3
Definition at line 128 of file regutil.h.
RATA_ARR
#define RATA_ARR 5
Definition at line 153 of file regutil.h.
RATA_CDP
#define RATA_CDP 8
Definition at line 133 of file regutil.h.
RATA_CONST
#define RATA_CONST 1
Definition at line 149 of file regutil.h.
RATA_CQP
#define RATA_CQP 9
Definition at line 134 of file regutil.h.
RATA_CSP
#define RATA_CSP 7
Definition at line 132 of file regutil.h.
RATA_CX87
#define RATA_CX87 11
Definition at line 136 of file regutil.h.
RATA_DP
#define RATA_DP 2
Definition at line 127 of file regutil.h.
RATA_DPXM
#define RATA_DPXM 13
Definition at line 145 of file regutil.h.
RATA_ILI
#define RATA_ILI 2
Definition at line 150 of file regutil.h.
RATA_IND
#define RATA_IND 4
Definition at line 152 of file regutil.h.
RATA_IR
#define RATA_IR 0
Definition at line 125 of file regutil.h.
RATA_KR
#define RATA_KR 4
Definition at line 129 of file regutil.h.
RATA_NME
#define RATA_NME 0
Definition at line 148 of file regutil.h.
RATA_QP
#define RATA_QP 6
Definition at line 131 of file regutil.h.
RATA_RPL
#define RATA_RPL 6
Definition at line 154 of file regutil.h.
RATA_RTYPES_ACTIVE
#define RATA_RTYPES_ACTIVE RATA_X87
Definition at line 138 of file regutil.h.
RATA_RTYPES_TOTAL
#define RATA_RTYPES_TOTAL RATA_DPXM + 1
Definition at line 146 of file regutil.h.
RATA_SP
#define RATA_SP 1
Definition at line 126 of file regutil.h.
RATA_SPXM
#define RATA_SPXM 12
Definition at line 144 of file regutil.h.
RATA_TEMP
#define RATA_TEMP 3
Definition at line 151 of file regutil.h.
RATA_UPLV
#define RATA_UPLV 7
Definition at line 155 of file regutil.h.
RATA_VECT
#define RATA_VECT 5
Definition at line 130 of file regutil.h.
RATA_X87
#define RATA_X87 10
Definition at line 135 of file regutil.h.
RCAND_ATYPE
#define RCAND_ATYPE (i) rcandb.stg_base[i].atype
Definition at line 254 of file regutil.h.
RCAND_CONFL
#define RCAND_CONFL (i) rcandb.stg_base[i].flags.bits.confl
Definition at line 256 of file regutil.h.
RCAND_COUNT
#define RCAND_COUNT (i) rcandb.stg_base[i].count
Definition at line 270 of file regutil.h.
RCAND_CSE
#define RCAND_CSE (i) rcandb.stg_base[i].flags.bits.cse
Definition at line 258 of file regutil.h.
RCAND_EINT
#define RCAND_EINT (i) rcandb.stg_base[i].flags.bits.eint
Definition at line 262 of file regutil.h.
RCAND_FLAGS
#define RCAND_FLAGS (i) rcandb.stg_base[i].flags.all
Definition at line 255 of file regutil.h.
RCAND_IGNORE
#define RCAND_IGNORE (i) rcandb.stg_base[i].flags.bits.ignore
Definition at line 261 of file regutil.h.
RCAND_INV
#define RCAND_INV (i) rcandb.stg_base[i].flags.bits.inv
Definition at line 264 of file regutil.h.
RCAND_ISCONST
#define RCAND_ISCONST (i) (RCAND_ATYPE(i) == RATA_CONST)
Definition at line 275 of file regutil.h.
RCAND_ISILI
#define RCAND_ISILI (i) (RCAND_ATYPE(i) == RATA_ILI)
Definition at line 276 of file regutil.h.
RCAND_ISNME
#define RCAND_ISNME (i) (RCAND_ATYPE(i) == RATA_NME)
Definition at line 274 of file regutil.h.
RCAND_ISTEMP
#define RCAND_ISTEMP (i) (RCAND_ATYPE(i) == RATA_TEMP)
Definition at line 277 of file regutil.h.
RCAND_ISUPLV
#define RCAND_ISUPLV (i) (RCAND_ATYPE(i) == RATA_UPLV)
Definition at line 278 of file regutil.h.
RCAND_MSIZE
#define RCAND_MSIZE (i) rcandb.stg_base[i].msize
Definition at line 266 of file regutil.h.
RCAND_NEXT
#define RCAND_NEXT (i) rcandb.stg_base[i].next
Definition at line 269 of file regutil.h.
RCAND_NOREG
#define RCAND_NOREG (i) rcandb.stg_base[i].flags.bits.noreg
Definition at line 260 of file regutil.h.
RCAND_OCAND
#define RCAND_OCAND (i) rcandb.stg_base[i].ocand
Definition at line 272 of file regutil.h.
RCAND_OK
#define RCAND_OK (i) rcandb.stg_base[i].flags.bits.ok
Definition at line 259 of file regutil.h.
RCAND_OLOAD
#define RCAND_OLOAD (i) rcandb.stg_base[i].oload
Definition at line 271 of file regutil.h.
RCAND_RAT
#define RCAND_RAT (i) rcandb.stg_base[i].rat
Definition at line 273 of file regutil.h.
RCAND_RTYPE
#define RCAND_RTYPE (i) rcandb.stg_base[i].rtype
Definition at line 253 of file regutil.h.
RCAND_STORE
#define RCAND_STORE (i) rcandb.stg_base[i].flags.bits.store
Definition at line 257 of file regutil.h.
RCAND_TEMP
#define RCAND_TEMP (i) rcandb.stg_base[i].temp
Definition at line 268 of file regutil.h.
RCAND_TINV
#define RCAND_TINV (i) rcandb.stg_base[i].flags.bits.tinv
Definition at line 265 of file regutil.h.
RCAND_VAL
#define RCAND_VAL (i) rcandb.stg_base[i].val
Definition at line 267 of file regutil.h.
RCAND_VINT
#define RCAND_VINT (i) rcandb.stg_base[i].flags.bits.vint
Definition at line 263 of file regutil.h.
RTEMPS
#define RTEMPS 11
Definition at line 23 of file regutil.h.
RTYPE_DF
#define RTYPE_DF (rtype) ((ILI_OP)il_rtype_df[rtype])
Definition at line 310 of file regutil.h.
Typedef Documentation
ARASGN
typedef struct arasgntag ARASGN
LST
typedef struct LST_TAG LST
RegrConstFlags_t
typedef enum RegConstFlags_t RegrConstFlags_t
For restricting the assignment of registers to constants per RTYPE. Used in machreg.c to init reg[...].const_flag; checked where assignments occur (i.e., globalreg.c).
Enumeration Type Documentation
RegConstFlags_t
enum RegConstFlags_t
For restricting the assignment of registers to constants per RTYPE. Used in machreg.c to init reg[...].const_flag; checked where assignments occur (i.e., globalreg.c).
Enumerator
RCF_NONE
constants not assigned
RCF_ALL
no restriction on value
RCF_NOT0
not if value is 0
RCF_NOT32K
not if int value in [-32768, 32767]
RCF_NOTL16
not if high 16 bits of mask value == 0
RCF_NOTH16
not if low 16 bits of mask value == 0
RCF_NOTA8B
not if abs(v) <= 255 (8 bits)
RCF_NOTA9B
not if abs(v) <= 511 (9 bits)
Definition at line 62 of file regutil.h.
Function Documentation
addrcand()
void addrcand (int ilix)
...
...
Definition at line 87 of file regutil.cpp.
References assert, ERR_Severe, GET_RCAND, ILI_OPC, ILI_OPND, ILI_RAT, msize, MSZ_F16, MSZ_F32, MSZ_F4, MSZ_F8, MSZ_I8, MSZ_PTR, MSZ_WORD, NME_RAT, RATA_AR, RATA_CDP, RATA_CONST, RATA_CSP, RATA_DP, RATA_ILI, RATA_IR, RATA_KR, RATA_NME, RATA_SP, REG::rcand, RCAND_ATYPE, RCAND_CONFL, RCAND_COUNT, RCAND_MSIZE, RCAND_NEXT, RCAND_OLOAD, RCAND_RTYPE, RCAND_STORE, RCAND_VAL, rcandb, reg, and RCANDB::weight.
Referenced by exp_rcand().
assn_input_rtemp()
void assn_input_rtemp (int ili, int temp)
...
Definition at line 1204 of file regutil.cpp.
References _assn_rtemp(), and ili.
assn_rtemp()
int assn_rtemp (int ili)
...
Definition at line 1101 of file regutil.cpp.
References assn_rtemp_sc(), ili, and SC_AUTO.
assn_rtemp_sc()
int assn_rtemp_sc (int ili, SC_KIND sc)
...
Definition at line 1210 of file regutil.cpp.
References _assn_rtemp(), ili, and mkrtemp_sc().
Referenced by assn_rtemp().
assn_sclrtemp()
int assn_sclrtemp (int ili, SC_KIND sc)
...
Definition at line 1218 of file regutil.cpp.
References _assn_rtemp(), getsymbol(), ili, name, rtemps, select_rtemp(), and type.
dmprcand()
void dmprcand (void)
...
Definition at line 442 of file regutil.cpp.
References dump_cand(), gbl, RATA_AR, RATA_CDP, RATA_CSP, RATA_DP, RATA_IR, RATA_KR, RATA_SP, RATA_VECT, REG::rcand, and reg.
Referenced by reg_assign1().
endrcand()
void endrcand (void)
...
...
The regs' rcand fields are set to null, and the register candidate list is reset.
Definition at line 672 of file regutil.cpp.
References ERR_Severe, FLANG_FALLTHROUGH, i, ILI_OPND, ILI_RAT, interr(), NME_RAT, RATA_ALL, RATA_ARR, RATA_CDP, RATA_CONST, RATA_CSP, RATA_ILI, RATA_IND, RATA_NME, RATA_RPL, RATA_TEMP, RATA_UPLV, RATA_VECT, REG::rcand, RCAND_ATYPE, RCAND_NEXT, RCAND_OLOAD, RCAND_TEMP, RCAND_VAL, rcandb, reg, RCANDB::stg_avail, and val.
Referenced by reg_assign1().
getrcand()
int getrcand (int candl)
...
...
Definition at line 628 of file regutil.cpp.
References count, RCANDB::count, GR_THRESHOLD, RCAND_CONFL, RCAND_COUNT, RCAND_NEXT, and rcandb.
Referenced by assign1().
mkrtemp()
SPTR mkrtemp (int ilix)
...
...
Definition at line 904 of file regutil.cpp.
References mkrtemp_sc(), and SC_AUTO.
mkrtemp_arg1_sc()
SPTR mkrtemp_arg1_sc (DTYPE dtype, SC_KIND sc)
...
Definition at line 999 of file regutil.cpp.
References arg1pfx, current, dt, DT_CMPLX, DT_DCMPLX, ERR_Severe, getccssym_sc(), index, interr(), max, mkrtemp_cpx_sc(), rtemps, and type.
Referenced by exp_qjsr().
mkrtemp_copy()
void mkrtemp_copy (int * rt)
...
...
Definition at line 1063 of file regutil.cpp.
References i, rtemps, and RTEMPS.
mkrtemp_cpx()
SPTR mkrtemp_cpx (DTYPE dtype)
...
...
Also used for INTEGER*8 support to allocate 64-bit temporaries for 64-bit int argument expressions.
Definition at line 944 of file regutil.cpp.
References mkrtemp_cpx_sc(), and SC_AUTO.
mkrtemp_cpx_sc()
SPTR mkrtemp_cpx_sc (DTYPE dtype, SC_KIND sc)
...
Definition at line 958 of file regutil.cpp.
References current, dt, DT_CMPLX, DT_DCMPLX, ERR_Severe, getccsym_sc(), index, interr(), max, prefix, rtemps, and type.
Referenced by cmplx_to_mem(), exp_call(), exp_zqjsr(), mkrtemp_arg1_sc(), and mkrtemp_cpx().
mkrtemp_end()
void mkrtemp_end (void)
...
...
Definition at line 1049 of file regutil.cpp.
References i, rtemps, and RTEMPS.
Referenced by exp_end(), and llvmAddConcurExitBlk().
mkrtemp_init()
void mkrtemp_init (void)
...
...
Definition at line 883 of file regutil.cpp.
References assert, ERR_Severe, i, rtemps, and RTEMPS.
Referenced by exp_header(), and exp_misc().
mkrtemp_reinit()
void mkrtemp_reinit (int * rt)
...
...
Definition at line 1090 of file regutil.cpp.
References i, rtemps, and RTEMPS.
mkrtemp_sc()
SPTR mkrtemp_sc (int ilix, SC_KIND sc)
...
...
Definition at line 915 of file regutil.cpp.
References current, dt, getccsym_sc(), index, max, prefix, rtemps, select_rtemp(), and type.
Referenced by assn_rtemp_sc(), check_ilm(), exp_bran(), exp_call(), genswitch(), and mkrtemp().
mkrtemp_update()
void mkrtemp_update (int * rt)
...
...
Definition at line 1076 of file regutil.cpp.
References i, max, rtemps, and RTEMPS.
reg_init()
void reg_init (int entr)
...
Definition at line 76 of file regutil.cpp.
References ENTRY::arasgn, aux, RCANDB::const_cnt, AUX::curr_entry, mr_init(), NULL, rcandb, and RCANDB::static_cnt.
Referenced by exp_header(), and llvmAddConcurEntryBlk().
storedums()
void storedums (int exitbih, int first_rat)
...
...
Definition at line 773 of file regutil.cpp.
References ad3ili(), ad4ili(), addilt(), addr, basesym_of(), BIH_SMOVE, cnt, i, IS_DUM, MSZ_F16, MSZ_F4, MSZ_F8, MSZ_I8, RAT_ADDR, RAT_MSIZE, RAT_REG, RAT_RTYPE, RAT_STORE, RAT_VAL, RATA_AR, RATA_CDP, RATA_CSP, RATA_DP, RATA_IR, RATA_KR, RATA_SP, rdilts(), void(), and wrilts().
Referenced by reg_assign1().
Variable Documentation
il_mv_rtype
int il_mv_rtype[RATA_RTYPES_TOTAL] extern
Definition at line 66 of file regutil.cpp.
il_rtype_df
int il_rtype_df[RATA_RTYPES_TOTAL] extern
Definition at line 58 of file regutil.cpp.
ratb
RATB ratb extern
Definition at line 31 of file expdf.cpp.
Referenced by _mr_getnext(), _mr_getreg(), ds_init(), exp_cleanup(), and reg_assign1().
rcandb
RCANDB rcandb extern
Definition at line 29 of file expdf.cpp.
Referenced by addrcand(), create_ref(), ds_init(), endrcand(), exp_ac(), exp_cleanup(), exp_load(), exp_store(), expand(), getrcand(), and reg_init().