flang: reshape.c File Reference
reshape.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
Functions
static int I8() advance (F90_Desc *d, __INT_T *index, __INT_T n)
static int I8() advance_permuted (F90_Desc *d, __INT_T *index, int *order, __INT_T n)
void ENTFTN (RESHAPE, reshape)
void ENTFTN (RESHAPECA, reshapeca)
void ENTFTN (RESHAPEC, reshapec)
Variables
void(* __fort_scalar_copy [__NTYPES])(void *rp, void *sp, int len)
Function Documentation
advance()
static int I8() advance (F90_Desc * d, __INT_T * index, __INT_T n) static
Definition at line 19 of file reshape.c.
References __fort_abort(), d, DIM_UBOUND_G, F90_DIM_LBOUND_G, F90_RANK_G, i, index, n, and r.
Referenced by __INT_T(), ENTFTN(), fr_init(), and fw_init().
advance_permuted()
static int I8() advance_permuted (F90_Desc * d, __INT_T * index, int * order, __INT_T n) static
Definition at line 43 of file reshape.c.
References __fort_abort(), d, DIM_UBOUND_G, F90_DIM_LBOUND_G, F90_RANK_G, i, index, j, k, n, order, and r.
Referenced by ENTFTN().
ENTFTN() [1/3]
void ENTFTN (RESHAPE , reshape)
Definition at line 71 of file reshape.c.
References __DESC, __DIST_INIT_SECTION, __fort_abort(), __fort_copy(), __fort_doit(), __fort_fetch_int_vector(), __fort_finish_section(), __fort_frechn(), __fort_set_section(), __fort_set_single(), __NONE, __SCALAR, advance(), advance_permuted(), DECL_HDR_VARS, DIM_UBOUND_G, DIST_SCOFF_G, F90_DIM_LBOUND_G, F90_GSIZE_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, i, I8, j, k, m, MAXDIMS, Min, n, NULL, order, and r.
Referenced by ENTFTN().
ENTFTN() [2/3]
void ENTFTN (RESHAPEC , reshapec)
Definition at line 241 of file reshape.c.
References __CLEN_T, CADR, CLEN, and ENTFTN().
ENTFTN() [3/3]
void ENTFTN (RESHAPECA , reshapeca)
Definition at line 222 of file reshape.c.
References CADR, ENTFTN(), and reshape.
Variable Documentation
__fort_scalar_copy
void(* __fort_scalar_copy[__NTYPES])(void *rp, void *sp, int len) (void * rp, void * sp, int len) extern