flang: rest.c File Reference
rest.c File Reference
various ast transformations
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "soc.h"
#include "semant.h"
#include "ast.h"
#include "gramtk.h"
#include "comm.h"
#include "extern.h"
#include "ccffinfo.h"
#include "pragma.h"
#include "dpm_out.h"
#include "optimize.h"
#include "rte.h"
#include "rtlRtns.h"
Classes
struct T_LIST
Macros
#define RTE_C
#define SECTZBASE 0x00400000
#define TEMP_AREA 6
#define GET_T_LIST(q) q = (T_LIST *)getitem(TEMP_AREA, sizeof(T_LIST))
Typedefs
typedef struct T_LIST T_LIST
Functions
static int _transform_func (int, int)
static LOGICAL stride_1_dummy (int, int, int)
static LOGICAL stride_1_section (int, int, int, int)
void remove_alias (int, int)
static int first_element_from_section (int)
static void copy_arg_to_seq_tmp (int, int, int, int, int, int, int *, int *, LOGICAL, LOGICAL, LOGICAL)
static int temp_type_descriptor (int ast, int std)
Create a temporary type descriptor for a procedure argument.
static LOGICAL is_seq_dummy (int, int, int)
static LOGICAL needs_type_in_descr (SPTR, int)
static LOGICAL is_optional_char_dummy (int, int, int)
static void check_pure_interface (int, int, int)
static void handle_seq_section (int, int, int, int, int *, int *, LOGICAL, int)
static int mk_descr_from_section (int, DTYPE, int)
static int need_copyout (int entry, int loc)
static LOGICAL is_desc_needed (int, int, int)
static LOGICAL continuous_section (int, int, int, int)
static int transform_all_call (int std, int ast)
static int remove_subscript_expressions (int ast, int std, int sym)
static void set_descr_tag (int descr, int tag, int std)
Set the tag field in a descriptor expression.
static int get_descr_arg (int ele, SPTR sptr, int std)
Generate an ast that represents a descriptor actual argument for a polymorphic or monomorphic actual argument.
static int get_descr_or_placeholder_arg (SPTR inface_arg, int ele, int std)
Called by transform_call() to get either the descriptor argument or a placeholder descriptor argument for a procedure call.
int insert_comm_before (int std, int ast, LOGICAL *rhs_is_dist, LOGICAL is_subscript)
static void insert_comm (int std, int ast, LOGICAL lhs_is_dist)
void transform_ast (int std, int ast)
static void declare_type (void)
static int pghpf_type (int ss)
static int copy_to_scalar (int ast, int std, int sym)
static int find_section_subscript (int ast)
static int transform_section_arg (int ele, int std, int callast, int entry, int *descr, int argnbr)
void copy_surrogate_to_bnds_vars (DTYPE dt_dest, int parent_dest, DTYPE dt_src, int parent_src, int std)
void copy_desc_to_bnds_vars (int sptrdest, int desc, int memdesc, int std)
static void get_invoking_proc_desc (int sptr, int ast, int std)
void transform_call (int std, int ast)
The following code takes a function or subroutine call and adds section descriptors for the array arguments at the end of the argument list, if the callee has an explicit interface.
static int pure_procedure (int ast)
static int small_shape (int shd)
static int new_seq_temp_array (int shd, int small, int dtype, int cvlen, int oldsptr, int mustallocate)
static int make_seq_temp_array (int shd, int dtype, int oldsptr, int mustallocate, int std)
static LOGICAL leading_section (int ast)
int rename_forall_list (int forall)
static int tmp_assign (int ast, int std)
static void remove_from_scalar_subscript (int ast, int argt, int nargs, int std)
static void is_function_common (int ast, LOGICAL *any)
static LOGICAL any_functions (int ast)
static void remove_function_common_from_scalar_subscript (int argt, int nargs, int std)
void call_analyze (void)
Variables
int pghpf_type_sptr = 0
static short __pghpf_type []
static T_LIST * templist
Detailed Description
various ast transformations
Definition in file rest.c.
Macro Definition Documentation
GET_T_LIST
#define GET_T_LIST (q) q = (T_LIST *)getitem(TEMP_AREA, sizeof(T_LIST))
Definition at line 2888 of file rest.c.
RTE_C
#define RTE_C
Definition at line 28 of file rest.c.
SECTZBASE
#define SECTZBASE 0x00400000
TEMP_AREA
#define TEMP_AREA 6
Definition at line 2881 of file rest.c.
Typedef Documentation
T_LIST
typedef struct T_LIST T_LIST
Function Documentation
_transform_func()
static int _transform_func (int std, int ast) static
Definition at line 356 of file rest.c.
References _transform_func(), a, A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, d, i, interr(), MAXDIMS, mk_binop(), mk_convert(), mk_member(), mk_paren(), mk_subscr(), mk_substr(), mk_triple(), mk_unop(), nargs, ndim, r, std, and transform_call().
Referenced by _transform_func(), and transform_all_call().
any_functions()
static LOGICAL any_functions (int ast) static
Definition at line 3606 of file rest.c.
References ast, ast_traverse(), ast_unvisit(), ast_visit(), FALSE, is_function_common(), and NULL.
Referenced by remove_function_common_from_scalar_subscript().
call_analyze()
void call_analyze (void)
Definition at line 3865 of file rest.c.
References ast, check_region(), f90_fini_pointsto(), flg, freearea(), gbl, init_region(), pure_gbl::local_mode, NULL, FLG::opt, points_to(), set_descriptor_sc(), std, STD_AST, STD_LINENO, STD_LOCAL, STD_NEXT, STD_PURE, TEMP_AREA, templist, transform_all_call(), and XBIT.
check_pure_interface()
static void check_pure_interface (int entry, int std, int ast) static
Definition at line 2500 of file rest.c.
References ast, CNULL, error(), gbl, is_impure(), pure_procedure(), and SYMNAME.
Referenced by transform_call().
continuous_section()
static LOGICAL continuous_section (int entry, int arr_ast, int loc, int onlyfirst) static
Definition at line 3772 of file rest.c.
References T_LIST::asd, ASD_NDIM, ASD_SUBS, astb, ASTB::bnd, dim, FALSE, ASTB::i1, is_whole_dim(), ndims, ASTB::one, sptr, sym_of_ast(), and TRUE.
Referenced by handle_seq_section(), and transform_section_arg().
copy_arg_to_seq_tmp()
static void copy_arg_to_seq_tmp (int entry, int loc, int eledtype, int arraysptr, int arr_ast, int std, int * retval, int * descr, LOGICAL actual_is_contiguous, LOGICAL stride1, LOGICAL wholearray) static
Definition at line 2981 of file rest.c.
References ADD_NUMDIM, add_stmt_after(), add_stmt_before(), ALIGNG, ARGT_ARG, ast, ast_intr(), astb, ASTB::bnd, ccff_info(), check_member(), DBGBIT, DDTG, DT_INT, STB::dt_log, DT_LOG, DT_PTR, DTY, ASTB::dtype, find_dummy(), find_section_subscript(), first_element_from_section(), forall_opt1(), gbl, i, ASTB::i0, ASTB::i1, IGNORE_C, ignore_tkr(), leading_section(), pure_gbl::local_mode, make_forall(), make_sec_from_ast(), make_seq_temp_array(), MAXDIMS, mk_argt(), mk_assn_stmt(), mk_binop(), mk_cval(), mk_func_node(), mk_id(), mk_mem_allocate(), mk_mem_deallocate(), mk_stmt(), mk_subscr(), mk_triple(), mk_unop(), mkRteRtnNm(), MSGFTN, ndim, need_copyout(), normalize_forall(), NULL, ASTB::one, OP_ADD, OP_DIV, OP_LOC, OP_NE, OP_SUB, present, process_forall(), ASTB::ptr0, rename_forall_list(), RTE_addr_1_dim_1st_elem, RTE_copy_f77_argl, RTE_copy_f77_argsl, RTE_copy_f90_argl, scalarize(), SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, size, size_ast(), stb, std, subscr, sym_mkfunc(), SYMNAME, tmp, transform_forall(), TRUE, STB::user, and XBIT.
Referenced by handle_seq_section().
copy_desc_to_bnds_vars()
void copy_desc_to_bnds_vars (int sptrdest, int desc, int memdesc, int std)
Definition at line 978 of file rest.c.
References a, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_NUMDIM, AD_UPAST, add_stmt_before(), astb, ASTB::bnd, check_member(), dt, DTY, ASTB::dtype, get_extent(), get_global_lower(), i, mk_assn_stmt(), mk_binop(), mk_extent_expr(), mk_isz_cval(), ndim, ASTB::one, OP_ADD, OP_SUB, and std.
Referenced by transform_call().
copy_surrogate_to_bnds_vars()
void copy_surrogate_to_bnds_vars (DTYPE dt_dest, int parent_dest, DTYPE dt_src, int parent_src, int std)
Definition at line 927 of file rest.c.
References AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_MLPYR, AD_NUMDIM, AD_UPAST, AD_ZBASE, add_parent_to_bounds(), add_stmt_before(), astb, ASTB::bnd, DTY, ASTB::dtype, extent(), i, mk_assn_stmt(), mk_binop(), mk_extent_expr(), ndim, ASTB::one, OP_ADD, OP_MUL, OP_SUB, std, and zbase.
Referenced by transform_call(), and transform_move_alloc().
copy_to_scalar()
static int copy_to_scalar (int ast, int std, int sym) static
Definition at line 696 of file rest.c.
References add_stmt_before(), ast, astb, ASTB::bnd, ASTB::dtype, FALSE, FLANG_FALLTHROUGH, insert_comm_before(), pure_gbl::local_mode, mk_id(), mk_stmt(), sptr, std, sym_get_scalar(), and SYMNAME.
Referenced by remove_subscript_expressions().
declare_type()
static void declare_type (void) static
Definition at line 580 of file rest.c.
References ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_NUMELM, ADD_UPAST, ADD_UPBD, ADD_ZBASE, astb, ASTB::bnd, CMEMLP, STB::curr_scope, DLL_IMPORT, DLLP, DT_INT, DT_PTR, ASTB::dtype, gbl, get_array_dtype(), getsymbol(), insert_sym(), mk_isz_cval(), NOSYM, ASTB::one, pghpf_type_sptr, sptr, stb, and XBIT.
Referenced by pghpf_type().
find_section_subscript()
static int find_section_subscript (int ast) static
Definition at line 803 of file rest.c.
References a, ast, and parent.
Referenced by copy_arg_to_seq_tmp(), handle_seq_section(), and transform_section_arg().
first_element_from_section()
static int first_element_from_section (int arr) static
Definition at line 3439 of file rest.c.
References AD_DPTR, AD_LWAST, T_LIST::asd, ASD_NDIM, ASD_SUBS, assert, astb, ASTB::bnd, DTY, ASTB::dtype, first_element_from_section(), i, interr(), is_array_type(), MAXDIMS, mk_isz_cval(), mk_member(), mk_subscr(), ndim, parent, rank_of(), sptr, and sptr_of_subscript().
Referenced by copy_arg_to_seq_tmp(), first_element_from_section(), handle_seq_section(), and transform_section_arg().
get_descr_arg()
static int get_descr_arg (int ele, SPTR sptr, int std) static
Generate an ast that represents a descriptor actual argument for a polymorphic or monomorphic actual argument.
Parameters
ele is the ast of the symbol expression
sptr is the symbol table pointer of the symbol (could differ from ele).
std is where to insert the assignment statements.
Returns
an ast representing the descriptor actual argument
Definition at line 2263 of file rest.c.
References __TAGDESC, __TAGPOLY, check_member(), gbl, get_member_descriptor(), get_type_descr_arg(), mk_id(), set_descr_tag(), sptr, and std.
Referenced by get_descr_or_placeholder_arg().
get_descr_or_placeholder_arg()
static int get_descr_or_placeholder_arg (SPTR inface_arg, int ele, int std) static
Called by transform_call() to get either the descriptor argument or a placeholder descriptor argument for a procedure call.
Parameters
inface_arg is the symbol table pointer of the interface's argument.
ele is an ast representing the actual argument.
std is where to insert the assignment statements.
Returns
an ast represting the descriptor/placeholder argument.
Definition at line 2297 of file rest.c.
References ast, ast_is_sym(), dtype_to_arg(), get_descr_arg(), memsym_of_ast(), needs_descriptor(), NOSYM, pghpf_type(), and std.
Referenced by transform_call().
get_invoking_proc_desc()
static void get_invoking_proc_desc (int sptr, int ast, int std) static
Definition at line 1029 of file rest.c.
References add_stmt_before(), ARGT_ARG, ast, check_member(), SEM::dtemps, func, get_member_descriptor(), get_static_descriptor(), getcctmp_sc(), is_procedure_ptr(), mk_argt(), mk_func_node(), mk_id(), mkRteRtnNm(), NOSYM, RTE_copy_proc_desc, SEM::sc, sem, sptr, std, sym_mkfunc_nodesc(), and tmp.
Referenced by transform_call().
handle_seq_section()
static void handle_seq_section (int entry, int arr, int loc, int std, int * retval, int * descr, LOGICAL stride1, int dummysptr) static
Definition at line 2524 of file rest.c.
References ALIGNG, assert, check_member(), continuous_section(), convert_subscript(), copy_arg_to_seq_tmp(), DTY, FALSE, find_dummy(), find_section_subscript(), first_element(), first_element_from_section(), IGNORE_C, ignore_tkr(), interr(), is_array_type(), is_desc_needed(), is_pointer(), is_procedure_ptr(), make_sec_from_ast(), make_sec_from_ast_chk(), mk_descr_from_section(), mk_id(), NOSYM, NULL, pghpf_type(), proc_arginfo(), replace_ast_subtree(), SECTZBASE, sptr_of_subscript(), std, TRUE, and XBIT.
Referenced by transform_call(), and transform_section_arg().
insert_comm()
static void insert_comm (int std, int ast, LOGICAL lhs_is_dist) static
Definition at line 450 of file rest.c.
References A_STDP, ast, FALSE, insert_comm_before(), std, and STD_AST.
Referenced by transform_ast().
insert_comm_before()
int insert_comm_before (int std, int ast, LOGICAL * rhs_is_dist, LOGICAL is_subscript)
Definition at line 65 of file rest.c.
References a, A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, astb, d, dest, ASTB::firstuast, i, insert_comm_before(), interr(), MAXDIMS, mk_binop(), mk_convert(), mk_member(), mk_paren(), mk_subscr(), mk_substr(), mk_triple(), mk_unop(), nargs, ndim, r, replace_ast_subtree(), std, and TRUE.
Referenced by copy_to_scalar(), insert_comm(), insert_comm_before(), insert_forall_comm(), normalize_forall_triplet(), scalar_communication(), and tmp_assign().
is_desc_needed()
static LOGICAL is_desc_needed (int entry, int arr_ast, int loc) static
Definition at line 3718 of file rest.c.
References aux, AUX::dpdsc_base, DTY, FALSE, is_kopy_in_needed(), is_procedure_ptr(), NULL, proc_arginfo(), and TRUE.
Referenced by handle_seq_section().
is_function_common()
static void is_function_common (int ast, LOGICAL * any) static
Definition at line 3583 of file rest.c.
References ast, sptr, and TRUE.
Referenced by any_functions().
is_optional_char_dummy()
static LOGICAL is_optional_char_dummy (int entry, int arr, int pos) static
Definition at line 2446 of file rest.c.
References astb, DTYG, FALSE, find_dummy(), pos, ASTB::ptr0, TRUE, and TY_CHAR.
Referenced by transform_call().
is_seq_dummy()
static LOGICAL is_seq_dummy (int entry, int arr, int loc) static
Definition at line 2373 of file rest.c.
References aux, AUX::dpdsc_base, FALSE, NULL, proc_arginfo(), and TRUE.
Referenced by transform_call(), and transform_section_arg().
leading_section()
static LOGICAL leading_section (int ast) static
Definition at line 2953 of file rest.c.
References T_LIST::asd, ASD_NDIM, ASD_SUBS, ast, FALSE, i, ss, and TRUE.
Referenced by copy_arg_to_seq_tmp().
make_seq_temp_array()
static int make_seq_temp_array (int shd, int dtype, int oldsptr, int mustallocate, int std) static
Definition at line 2897 of file rest.c.
References T_LIST::cvlen, DTY, GET_T_LIST, i, ndim, new_seq_temp_array(), q, SYMUTL::sc, T_LIST::shd, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, small_shape(), sptr, std, symutl, templist, and TY_CHAR.
Referenced by copy_arg_to_seq_tmp().
mk_descr_from_section()
static int mk_descr_from_section (int section, DTYPE topdtype, int std) static
Definition at line 2772 of file rest.c.
References emit_alnd_secd(), INS_DESCR, MAXDIMS, mk_id(), mk_shape_sptr(), std, subscr, tmp, and TRUE.
Referenced by handle_seq_section().
need_copyout()
static int need_copyout (int entry, int loc) static
Definition at line 3751 of file rest.c.
References find_dummy(), INTENT_IN, INTENTG, pos, and sptr.
Referenced by copy_arg_to_seq_tmp().
needs_type_in_descr()
static LOGICAL needs_type_in_descr (SPTR entry, int loc) static
Definition at line 2394 of file rest.c.
References array_element_dtype(), aux, AUX::dpdsc_base, DTY, FALSE, is_array_dtype(), NOSYM, NULL, and proc_arginfo().
Referenced by transform_section_arg().
new_seq_temp_array()
static int new_seq_temp_array (int shd, int small, int dtype, int cvlen, int oldsptr, int mustallocate) static
Definition at line 2821 of file rest.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_MLPYR, ADD_UPAST, ADD_UPBD, assert, astb, ASTB::bnd, DT_PTR, ASTB::dtype, get_next_sym(), i, ASTB::i1, MAXDIMS, mk_binop(), mk_extent(), ndim, ASTB::one, OP_ADD, OP_DIV, OP_MUL, OP_SUB, SYMUTL::sc, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, sptr, sym_get_array(), SYMNAME, symutl, and trans_mkdescr().
Referenced by make_seq_temp_array().
pghpf_type()
static int pghpf_type (int ss) static
Definition at line 675 of file rest.c.
References __pghpf_type, ast, astb, ASTB::bnd, declare_type(), ASTB::dtype, MAXDIMS, mk_id(), mk_isz_cval(), mk_subscr(), pghpf_type_sptr, ss, and XBIT.
Referenced by get_descr_or_placeholder_arg(), handle_seq_section(), and transform_call().
pure_procedure()
static int pure_procedure (int ast) static
Definition at line 2483 of file rest.c.
References A_OPTYPEG, ARGT_ARG, ast, elemental_func_call(), FALSE, pure_func_call(), and TRUE.
Referenced by check_pure_interface().
remove_alias()
void remove_alias (int std, int ast)
Definition at line 3687 of file rest.c.
References A_ARGCNTG, argt, ARGT_ARG, ast, i, pure_gbl::local_mode, nargs, remove_from_scalar_subscript(), remove_function_common_from_scalar_subscript(), and std.
Referenced by inline_func().
remove_from_scalar_subscript()
static void remove_from_scalar_subscript (int ast, int argt, int nargs, int std) static
Definition at line 3522 of file rest.c.
References argt, ARGT_ARG, T_LIST::asd, ASD_NDIM, ASD_SUBS, ast, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), d, expr_dependent(), i, mk_id(), nargs, ndim, std, sub, t, tmp, and tmp_assign().
Referenced by remove_alias().
remove_function_common_from_scalar_subscript()
static void remove_function_common_from_scalar_subscript (int argt, int nargs, int std) static
Definition at line 3622 of file rest.c.
References any_functions(), argt, ARGT_ARG, T_LIST::asd, ASD_NDIM, ASD_SUBS, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), d, i, mk_id(), nargs, ndim, std, sub, t, tmp, and tmp_assign().
Referenced by remove_alias().
remove_subscript_expressions()
static int remove_subscript_expressions (int ast, int std, int sym) static
Definition at line 745 of file rest.c.
References ASD_NDIM, ASD_SUBS, ast, copy_to_scalar(), i, lb, MAXDIMS, mk_member(), mk_subscr(), mk_triple(), ndim, parent, remove_subscript_expressions(), ss, st, std, and ub.
Referenced by remove_subscript_expressions(), transform_call(), and transform_section_arg().
rename_forall_list()
int rename_forall_list (int forall)
Definition at line 3406 of file rest.c.
References A_NCOUNTG, A_NCOUNTP, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), astb, ASTLI_NEXT, ASTLI_SPTR, ASTB::bnd, ASTB::dtype, list, mk_id(), sym_get_scalar(), and SYMNAME.
Referenced by copy_arg_to_seq_tmp().
set_descr_tag()
static void set_descr_tag (int descr, int tag, int std) static
Set the tag field in a descriptor expression.
Parameters
descr is an ast representing the descriptor expression.
tag is the tag field value (typically __TAGDESC or __TAGPOLY).
std is where we want to insert the assignment.
Definition at line 2232 of file rest.c.
References add_stmt_before(), assn(), ast_is_sym(), check_member(), dast(), DT_INT, get_desc_tag(), memsym_of_ast(), mk_assn_stmt(), mk_cval1(), std, and val.
Referenced by get_descr_arg(), and temp_type_descriptor().
small_shape()
static int small_shape (int shd) static
Definition at line 2787 of file rest.c.
References ad_val_of(), i, ISZ_T, ndim, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, size, and stride.
Referenced by make_seq_temp_array().
stride_1_dummy()
static LOGICAL stride_1_dummy (int entry, int arr, int pos) static
Definition at line 2421 of file rest.c.
References FALSE, find_dummy(), memsym_of_ast(), pos, sptr, TRUE, and XBIT.
Referenced by transform_call(), and transform_section_arg().
stride_1_section()
static LOGICAL stride_1_section (int entry, int arr_ast, int pos, int std) static
Definition at line 3811 of file rest.c.
References T_LIST::asd, ASD_NDIM, ASD_SUBS, astb, dim, FALSE, find_dummy(), ASTB::i1, ASTB::k1, memsym_of_ast(), ndims, pos, pta_stride1(), sptr, std, TRUE, and XBIT.
Referenced by transform_call(), and transform_section_arg().
temp_type_descriptor()
static int temp_type_descriptor (int ast, int std) static
Create a temporary type descriptor for a procedure argument.
Parameters
ast is the ast that represents a procedure argument.
std is where to insert the assignment statements.
Returns
an ast representing the temporary type descriptor.
Definition at line 2324 of file rest.c.
References __TAGDESC, __TAGPOLY, add_stmt_before(), assert, assn(), ast, check_alloc_ptr_type(), check_member(), dast(), DT_INT, SEM::dtemps, DTY, ERR_Fatal, get_byte_len(), get_desc_gsize(), get_desc_lsize(), get_desc_rank(), get_kind(), getcctmp_sc(), mk_assn_stmt(), mk_cval1(), mk_id(), NOSYM, SEM::sc, sem, set_descr_tag(), std, string_length(), tmp, TY_CHAR, and val.
Referenced by transform_call().
tmp_assign()
static int tmp_assign (int ast, int std) static
Definition at line 3496 of file rest.c.
References A_STDP, add_stmt_before(), ast, DT_INT, FALSE, insert_comm_before(), mk_id(), mk_stmt(), std, STD_AST, sym_get_scalar(), and tmp.
Referenced by remove_from_scalar_subscript(), and remove_function_common_from_scalar_subscript().
transform_all_call()
static int transform_all_call (int std, int ast) static
Definition at line 3937 of file rest.c.
References _transform_func(), a, A_ARGCNTG, A_OPTYPEG, add_stmt_before(), argt, ARGT_ARG, T_LIST::asd, ASD_NDIM, ASD_SUBS, assert, ast, astb, d, dest, DT_LOG, i, interr(), MAXDIMS, mk_binop(), mk_convert(), mk_id(), mk_member(), mk_paren(), mk_stmt(), mk_subscr(), mk_substr(), mk_triple(), mk_unop(), nargs, ndim, r, sptr, std, STD_NEXT, STD_PREV, STG_RETURN, sym_get_scalar(), transform_all_call(), and transform_call().
Referenced by call_analyze(), and transform_all_call().
transform_ast()
void transform_ast (int std, int ast)
Definition at line 464 of file rest.c.
References ast, FALSE, insert_comm(), and std.
Referenced by comm_analyze(), sequentialize(), and sequentialize_call().
transform_call()
void transform_call (int std, int ast)
The following code takes a function or subroutine call and adds section descriptors for the array arguments at the end of the argument list, if the callee has an explicit interface.
For example, call foo(a1,a2,a3) will be transformed call foo(a1,a2,a3, sec_a1, sec_a2, sec_a3).
It does not accept array expressions as argument nor array funcs. For accelerator routines, it also adds arguments to match the device-reflected copies
Rule:
 Argument Type           Address         Descriptor
 ___________________     ___________     ___________________
 scalar                  &scalar         --
 array elem              &array_elem     --
 array expression        &temp           section descriptor (if
assumed-shape)
 array expression        &temp           -- (else)
 array section           &array          section descriptor (if assumed-shape
                                         and stride-1)
 array section           &temp           section descriptor (if assumed-shape
                                         and not-stride-1)
 array section           &array          -- (else if contiguous)
 array section           &temp           -- (else)
 ptr array section       &ptr            static descriptor (if pointer dummy)
 ptr array section       &temp           section descriptor (if
assumed-shape,
                                         call added)
 ptr array section       &temp           -- (else, call added)
 func/subroutine dummy   &function       --
If there is an explicit interface, and the dummy argument has the REFLECTED attribute, then the actual argument must have a device resident copy, either from a region, data region, implicit data region, or must be itself reflected. In that case, the address of the reflected copy is passed just after the dummy, and if there is a section descriptor, the address of the section descriptor for the reflected copy is passed just after the section descriptor.
Definition at line 1111 of file rest.c.
References A_ARGCNTG, A_ARGCNTP, A_OPTYPEG, add_ptr_assign(), add_stmt_before(), arg, argt, ARGT_ARG, array_element_dtype(), assert, ast, ast_is_sym(), astb, aux, ASTB::bnd, check_alloc_ptr_type(), check_member(), check_pure_interface(), cmp_interfaces_strict(), copy_desc_to_bnds_vars(), copy_surrogate_to_bnds_vars(), DDTG, DEBUG, FLG::debug, AUX::dpdsc_base, DT_ISBASIC, SEM::dtemps, DTY, ASTB::dtype, dtype_to_arg(), ERR_Fatal, ERR_Severe, error(), FALSE, find_dummy_position(), fix_class_args(), FLANG_FALLTHROUGH, flg, func, gbl, gen_contig_check(), gen_poly_element_arg(), gen_set_type(), get_all_descriptors(), get_descr_or_placeholder_arg(), get_invoking_proc_desc(), get_member_descriptor(), get_proc_ptr(), get_static_descriptor(), get_static_type_descriptor(), get_tmp_descr(), get_type_descr_arg(), get_type_descr_arg2(), get_value_length_ast(), getccsym_sc(), getcctmp_sc(), handle_seq_section(), i, IGNORE_ARG_NAMES, init_sdsc_from_dtype(), inline_RTE_set_type(), INTENT_OUT, INTENTG, interr(), is_array_dtype(), is_bad_dtype(), is_optional_char_dummy(), IS_PROC, is_procedure_ptr(), is_seq_dummy(), is_unl_poly(), STB::k0, make_temp_descriptor(), max_binding_invobj(), memsym_of_ast(), mk_argt(), mk_assn_stmt(), mk_cnst(), mk_func_node(), mk_id(), mkRteRtnNm(), nargs, needs_descriptor(), NOSYM, NULL, OP_LOC, OP_REF, OP_VAL, pass_sym_of_ast(), pghpf_type(), proc_arginfo(), procsym_of_ast(), ASTB::ptr0, ASTB::ptr0c, RELAX_INTENT_CHK, RELAX_PURE_CHK_1, RELAX_STYPE_CHK, remove_subscript_expressions(), RTE_show, RTE_test_and_set_type, s, SEM::sc, scope, sem, set_parref_flag2(), set_type_in_descriptor(), SHD_NDIM, FLG::smp, sptr, sptr_of_subscript(), stb, std, STD_NEXT, stride_1_dummy(), stride_1_section(), sym_get_array(), sym_mkfunc_nodesc(), sym_of_ast(), symbol_descriptor_length_ast(), SYMNAME, temp_type_descriptor(), tmp, transform_section_arg(), TRUE, TY_HOLL, SEM::which_pass, and XBIT.
Referenced by _transform_func(), put_calls(), transform_all_call(), and transform_pure_function().
transform_section_arg()
static int transform_section_arg (int ele, int std, int callast, int entry, int * descr, int argnbr) static
Definition at line 842 of file rest.c.
References check_member(), continuous_section(), convert_subscript(), find_section_subscript(), first_element_from_section(), gen_poly_element_arg(), handle_seq_section(), is_seq_dummy(), is_whole_array(), make_sec_from_ast(), make_simple_template_from_ast(), mk_id(), needs_type_in_descr(), remove_subscript_expressions(), replace_ast_subtree(), SECTZBASE, sptr, sptr_of_subscript(), std, stride_1_dummy(), stride_1_section(), sym_of_ast(), and XBIT.
Referenced by transform_call().
Variable Documentation
__pghpf_type
short __pghpf_type[] static
Initial value:
= {
    -43, -42, -41, -40, -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29,
    -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14,
    -13, -12, -11, -10, -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,  0,   1,
    2,   3,   4,   5,   6,   7,   8,   9,   10,  11,  12,  13,  14,  15,  16,
    17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,
    32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43}
Definition at line 659 of file rest.c.
Referenced by pghpf_type().
pghpf_type_sptr
int pghpf_type_sptr = 0
Definition at line 577 of file rest.c.
Referenced by declare_type(), lower_init_sym(), pghpf_type(), transform(), and transform_init().
templist
T_LIST* templist static
Definition at line 2889 of file rest.c.
Referenced by call_analyze(), and make_seq_temp_array().