flang: rewind.c File Reference
rewind.c File Reference
Implements Fortran REWIND statement.
#include "global.h"
#include "async.h"
#include "stdioInterf.h"
Functions
static int _f90io_rewind (__INT_T *unit, __INT_T *bitv, __INT_T *iostat)
__INT_T ENTF90IO (REWIND, rewind)
int ENTCRF90IO (REWIND, rewind)
Detailed Description
Implements Fortran REWIND statement.
Definition in file rewind.c.
Function Documentation
_f90io_rewind()
static int _f90io_rewind (__INT_T * unit, __INT_T * bitv, __INT_T * iostat) static
Definition at line 19 of file rewind.c.
References __fortio_errinit03(), __fortio_error(), __fortio_find_unit(), __io_binary_mode(), __io_errno(), __io_ferror(), __io_fputc(), __io_fseek, fcb::acc, fcb::asy_rw, fcb::asyptr, bitv, fcb::coherent, fcb::eof_flag, f, FALSE, Fio_asy_disable(), FIO_DIRECT, FIO_EUNIT, fcb::fp, ILLEGAL_UNIT, fcb::nextrec, fcb::nonadvance, fcb::skip, TRUE, and fcb::truncflag.
Referenced by ENTCRF90IO(), and ENTF90IO().
ENTCRF90IO()
int ENTCRF90IO (REWIND , rewind)
Definition at line 81 of file rewind.c.
References __fortio_errend03(), _f90io_rewind(), bitv, and s.
ENTF90IO()
__INT_T ENTF90IO (REWIND , rewind)
Definition at line 70 of file rewind.c.
References __fort_status_init(), __fortio_errend03(), _f90io_rewind(), bitv, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, and s.