flang: rmsmove.h File Reference
rmsmove.h File Reference
Functions
void rm_smove (void)
...
Function Documentation
rm_smove()
void rm_smove (void)
...
Definition at line 92 of file rmsmove.cpp.
References ad1ili(), ad3ili(), ad4ili(), ad_aconi(), addilt(), BIH_ILTFIRST, BIH_NEXT, BIH_SMOVE, exp_remove_gsmove(), fixup_nme(), gbl, i, IL_AADD, ILI_OPC, ILI_OPCP, ILI_OPND, ILT_ILIP, ILT_NEXT, ILT_ST, info, INFO1, ld, len, msize, msz, n, NME_UNK, offset, rdilts(), SMOVE_CHUNK, SMOVE_MIN, st, USE_GSMOVE, wrilts(), and XBIT.
Referenced by process_input().