flang: rnum.c File Reference
rnum.c File Reference
#include <time.h>
#include "stdioInterf.h"
#include "fioMacros.h"
#include "llcrit.h"
Classes
struct Seed
Macros
#define T23 (8388608.0)
#define T46 (T23 * T23)
#define R23 (1.0 / T23)
#define R46 (1.0 / T46)
#define MASK23 ((unsigned)0x7fffff)
#define DEFAULT_SEED_HI (R23 * 32.0)
#define DEFAULT_SEED_LO (R46 * 3392727.0)
#define NBITS 2
#define DIGIT ((1 << NBITS) - 1)
#define NDIGITS ((32 + NBITS - 1) / NBITS)
#define LONG_LAG 17
#define SHORT_LAG 5
#define L2CYCLE 6
#define L2CUTOFF 8
#define CYCLE (1 << L2CYCLE)
#define MASK (CYCLE - 1)
#define TOGGLE (CYCLE >> 1)
#define CUTOFF (1 << L2CUTOFF)
#define CUTMASK (CUTOFF - 1)
#define SEED(x, y)
Functions
MP_SEMAPHORE (static, sem)
static __BIGREAL_T advance_seed_npb (__INT_T n)
static void I8() prng_loop_d_npb (__REAL8_T *hb, F90_Desc *harvest, __INT_T li, int dim, __INT_T section_offset, __INT_T limit)
static void I8() prng_loop_r_npb (__REAL4_T *hb, F90_Desc *harvest, __INT_T li, int dim, __INT_T section_offset, __INT_T limit)
static __BIGREAL_T mul46 (const Seed *xp, __BIGREAL_T ylo, __BIGREAL_T yhi)
static __BIGREAL_T advance_seed_lf (__INT_T n)
static void I8() prng_loop_d_lf (__REAL8_T *hb, F90_Desc *harvest, __INT_T li, int dim, __INT_T section_offset, __INT_T limit)
static void I8() prng_loop_r_lf (__REAL4_T *hb, F90_Desc *harvest, __INT_T li, int dim, __INT_T section_offset, __INT_T limit)
static void set_fibonacci (void)
static void set_npb (void)
static int I8() level (F90_Desc *harvest)
void ENTFTN (RNUM, rnum)
void ENTFTN (RNUMD, rnumd)
static void put_int (void *b, F90_Desc *d, __INT_T val)
void ENTFTN (RSEED, rseed)
Variables
static __INT_T last_i = 0
static __BIGREAL_T seed_hi = DEFAULT_SEED_HI
static __BIGREAL_T seed_lo = DEFAULT_SEED_LO
static __BIGREAL_T table [32][2]
static int start_time_is_set = 0
static time_t start_time
static const __BIGREAL_T default_seed_lf [LONG_LAG]
static __BIGREAL_T seed_lf [CYCLE]
static int offset = LONG_LAG - 1
static const Seed table_lf [NDIGITS][DIGIT][LONG_LAG][LONG_LAG]
static int fibonacci = 1
static __BIGREAL_T(* advance_seed)(__INT_T) = advance_seed_lf
static void(* prng_loop_d)(__REAL8_T *, F90_Desc *, __INT_T, int, __INT_T, __INT_T) = I8(prng_loop_d_lf)
static void(* prng_loop_r)(__REAL4_T *, F90_Desc *, __INT_T, int, __INT_T, __INT_T) = I8(prng_loop_r_lf)
Macro Definition Documentation
CUTMASK
#define CUTMASK (CUTOFF - 1)
Definition at line 466 of file rnum.c.
CUTOFF
#define CUTOFF (1 << L2CUTOFF)
Definition at line 465 of file rnum.c.
CYCLE
#define CYCLE (1 << L2CYCLE)
Definition at line 461 of file rnum.c.
DEFAULT_SEED_HI
#define DEFAULT_SEED_HI (R23 * 32.0)
Definition at line 61 of file rnum.c.
DEFAULT_SEED_LO
#define DEFAULT_SEED_LO (R46 * 3392727.0)
Definition at line 62 of file rnum.c.
DIGIT
#define DIGIT ((1 << NBITS) - 1)
Definition at line 453 of file rnum.c.
L2CUTOFF
#define L2CUTOFF 8
Definition at line 459 of file rnum.c.
L2CYCLE
#define L2CYCLE 6
Definition at line 458 of file rnum.c.
LONG_LAG
#define LONG_LAG 17
Definition at line 456 of file rnum.c.
MASK
#define MASK (CYCLE - 1)
Definition at line 462 of file rnum.c.
MASK23
#define MASK23 ((unsigned)0x7fffff)
Definition at line 36 of file rnum.c.
NBITS
#define NBITS 2
Definition at line 452 of file rnum.c.
NDIGITS
#define NDIGITS ((32 + NBITS - 1) / NBITS)
Definition at line 454 of file rnum.c.
R23
#define R23 (1.0 / T23)
Definition at line 29 of file rnum.c.
R46
#define R46 (1.0 / T46)
Definition at line 30 of file rnum.c.
SEED
#define SEED (x, y)
Value:
  {                                                                            \
    (__BIGREAL_T)x, T23 * (__BIGREAL_T)y                                         \
  }
Definition at line 515 of file rnum.c.
SHORT_LAG
#define SHORT_LAG 5
Definition at line 457 of file rnum.c.
T23
#define T23 (8388608.0)
Definition at line 25 of file rnum.c.
T46
#define T46 (T23 * T23)
Definition at line 27 of file rnum.c.
TOGGLE
#define TOGGLE (CYCLE >> 1)
Definition at line 463 of file rnum.c.
Function Documentation
advance_seed_lf()
static __BIGREAL_T advance_seed_lf (__INT_T n) static
Definition at line 5921 of file rnum.c.
References CUTMASK, DIGIT, i, j, LONG_LAG, m, MASK, mul46(), n, NBITS, offset, R23, seed_lf, SHORT_LAG, t0, t1, T23, table_lf, and TOGGLE.
Referenced by ENTFTN(), prng_loop_d_lf(), prng_loop_r_lf(), and set_fibonacci().
advance_seed_npb()
static __BIGREAL_T advance_seed_npb (__INT_T n) static
Definition at line 88 of file rnum.c.
References n, R23, seed_hi, seed_lo, T23, and table.
Referenced by prng_loop_d_npb(), prng_loop_r_npb(), and set_npb().
ENTFTN() [1/3]
void ENTFTN (RNUM , rnum)
Definition at line 6395 of file rnum.c.
References __DESC, __fort_cycle_bounds(), __OFF_TEMPLATE, advance_seed, F90_FLAGS_G, F90_GSIZE_G, F90_LBASE_G, F90_RANK_G, F90_TAG_G, fibonacci, i, I8, last_i, level(), LONG_LAG, MASK, MP_P, MP_V, offset, prng_loop_r, R23, seed_hi, seed_lf, seed_lo, sem, SHORT_LAG, T23, table, and void().
ENTFTN() [2/3]
void ENTFTN (RNUMD , rnumd)
Definition at line 6452 of file rnum.c.
References __DESC, __fort_cycle_bounds(), __OFF_TEMPLATE, advance_seed, F90_FLAGS_G, F90_GSIZE_G, F90_LBASE_G, F90_RANK_G, F90_TAG_G, fibonacci, i, I8, last_i, level(), LONG_LAG, MASK, MP_P, MP_V, offset, prng_loop_d, R23, seed_hi, seed_lf, seed_lo, sem, SHORT_LAG, T23, table, and void().
ENTFTN() [3/3]
void ENTFTN (RSEED , rseed)
Definition at line 6611 of file rnum.c.
References __DESC, __fort_abort(), __fort_get_scalar(), __fort_getenv(), __fort_store_int_element(), advance_seed_lf(), CYCLE, DEFAULT_SEED_HI, default_seed_lf, DEFAULT_SEED_LO, extent(), F90_DIM_EXTENT_G, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, fibonacci, i, I8, index, ISPRESENT, j, list, LONG_LAG, MASK, MASK23, MP_P, MP_V, NULL, offset, put_int(), R23, R46, seed_hi, seed_lf, seed_lo, sem, set_fibonacci(), set_npb(), size, start_time, start_time_is_set, T23, T46, and time().
level()
static int I8() level (F90_Desc * harvest) static
Definition at line 6373 of file rnum.c.
References DECL_DIM_PTRS, DIST_DPTR_LAB_G, DIST_DPTR_UAB_G, DIST_MAPPED_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_RANK_G, i, and SET_DIM_PTRS.
Referenced by __fort_dump_type(), addfile(), addinlfile(), begin_walk(), check_dependence_ido(), count_parent_pointers(), declsym(), dirv_exo(), dirv_fulldep(), dmp_ict(), dump_one_vloop(), DumpnameHelper(), end_walk(), ENTFTN(), get_parent_pointer(), get_scope(), get_scope_level(), inline_ast(), inline_func(), inline_stds(), lower_add_func_call(), omp_get_ancestor_thread_num(), omp_get_ancestor_thread_num_(), omp_get_team_size(), omp_get_team_size_(), read_fileentries(), refsym_inscope(), sched_block_breadth_first(), skip_to_next(), stb_upper_init(), upper_init(), verify_block(), verify_function_ili(), verify_ili(), verify_ili_aux(), verify_ilt(), write_parent_pointers(), and write_typedescs().
MP_SEMAPHORE()
MP_SEMAPHORE (static , sem)
mul46()
static __BIGREAL_T mul46 (const Seed * xp, __BIGREAL_T ylo, __BIGREAL_T yhi) static
Definition at line 473 of file rnum.c.
References Seed::hi, i, Seed::lo, and z.
Referenced by advance_seed_lf().
prng_loop_d_lf()
static void I8() prng_loop_d_lf (__REAL8_T * hb, F90_Desc * harvest, __INT_T li, int dim, __INT_T section_offset, __INT_T limit) static
Definition at line 6013 of file rnum.c.
References __fort_block_bounds(), advance_seed_lf(), cl, current, DECL_DIM_PTRS, dim, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, hi, i, I8, last_i, lo, LONG_LAG, MASK, n, offset, prng_loop_d_lf(), seed_lf, SET_DIM_PTRS, SHORT_LAG, and void().
Referenced by prng_loop_d_lf(), and set_fibonacci().
prng_loop_d_npb()
static void I8() prng_loop_d_npb (__REAL8_T * hb, F90_Desc * harvest, __INT_T li, int dim, __INT_T section_offset, __INT_T limit) static
Definition at line 119 of file rnum.c.
References __fort_block_bounds(), advance_seed_npb(), cl, current, DECL_DIM_PTRS, dim, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, hi, i, I8, last_i, lo, n, prng_loop_d_npb(), R23, seed_hi, seed_lo, SET_DIM_PTRS, T23, table, and void().
Referenced by prng_loop_d_npb(), and set_npb().
prng_loop_r_lf()
static void I8() prng_loop_r_lf (__REAL4_T * hb, F90_Desc * harvest, __INT_T li, int dim, __INT_T section_offset, __INT_T limit) static
Definition at line 6222 of file rnum.c.
References __fort_block_bounds(), advance_seed_lf(), cl, current, DECL_DIM_PTRS, dim, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, hi, i, I8, last_i, lo, LONG_LAG, MASK, n, offset, prng_loop_r_lf(), seed_lf, SET_DIM_PTRS, SHORT_LAG, and void().
Referenced by prng_loop_r_lf(), and set_fibonacci().
prng_loop_r_npb()
static void I8() prng_loop_r_npb (__REAL4_T * hb, F90_Desc * harvest, __INT_T li, int dim, __INT_T section_offset, __INT_T limit) static
Definition at line 335 of file rnum.c.
References __fort_block_bounds(), advance_seed_npb(), cl, current, DECL_DIM_PTRS, dim, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, hi, i, I8, last_i, lo, n, prng_loop_r_npb(), R23, seed_hi, seed_lo, SET_DIM_PTRS, T23, table, and void().
Referenced by prng_loop_r_npb(), and set_npb().
put_int()
static void put_int (void * b, F90_Desc * d, __INT_T val) static
Definition at line 6575 of file rnum.c.
References __DESC, __fort_abort(), __INT1, __INT2, __INT4, __INT8, __OFF_TEMPLATE, Abs, b, d, DIST_SCOFF_G, F90_FLAGS_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, kind, and val.
Referenced by ENTFTN().
set_fibonacci()
static void set_fibonacci (void) static
Definition at line 6342 of file rnum.c.
References advance_seed, advance_seed_lf(), fibonacci, I8, prng_loop_d, prng_loop_d_lf(), prng_loop_r, and prng_loop_r_lf().
Referenced by ENTFTN().
set_npb()
static void set_npb (void) static
Definition at line 6354 of file rnum.c.
References advance_seed, advance_seed_npb(), fibonacci, I8, prng_loop_d, prng_loop_d_npb(), prng_loop_r, and prng_loop_r_npb().
Referenced by ENTFTN().
Variable Documentation
advance_seed
__BIGREAL_T(* advance_seed) (__INT_T) (__INT_T) = advance_seed_lf static
Definition at line 6331 of file rnum.c.
Referenced by ENTFTN(), set_fibonacci(), and set_npb().
default_seed_lf
const __BIGREAL_T default_seed_lf[LONG_LAG] static
Initial value:
= {
    21443106311501.0, 5197437683097.0,  3622043880426.0,  53312694480426.0,
    54665542338115.0, 51292272760733.0, 28013141389639.0, 6466909594288.0,
    36631377956900.0, 45800305729322.0, 1486199964658.0,  1320339397524.0,
    42446291962239.0, 8221323655096.0,  1104293620992.0,  2988247604277.0,
    1440485417884.0,
}
Definition at line 496 of file rnum.c.
Referenced by ENTFTN().
fibonacci
int fibonacci = 1 static
Definition at line 6329 of file rnum.c.
Referenced by ENTFTN(), set_fibonacci(), and set_npb().
last_i
__INT_T last_i = 0 static
Definition at line 38 of file rnum.c.
Referenced by ENTFTN(), prng_loop_d_lf(), prng_loop_d_npb(), prng_loop_r_lf(), and prng_loop_r_npb().
offset
int offset = LONG_LAG - 1 static
Definition at line 513 of file rnum.c.
Referenced by advance_seed_lf(), ENTFTN(), prng_loop_d_lf(), and prng_loop_r_lf().
prng_loop_d
void(* prng_loop_d) (__REAL8_T *, F90_Desc *, __INT_T, int, __INT_T, __INT_T) (__REAL8_T * , F90_Desc * , __INT_T , int , __INT_T , __INT_T) = I8(prng_loop_d_lf) static
Definition at line 6336 of file rnum.c.
Referenced by ENTFTN(), set_fibonacci(), and set_npb().
prng_loop_r
void(* prng_loop_r) (__REAL4_T *, F90_Desc *, __INT_T, int, __INT_T, __INT_T) (__REAL4_T * , F90_Desc * , __INT_T , int , __INT_T , __INT_T) = I8(prng_loop_r_lf) static
Definition at line 6338 of file rnum.c.
Referenced by ENTFTN(), set_fibonacci(), and set_npb().
seed_hi
__BIGREAL_T seed_hi = DEFAULT_SEED_HI static
Definition at line 64 of file rnum.c.
Referenced by advance_seed_npb(), ENTFTN(), prng_loop_d_npb(), and prng_loop_r_npb().
seed_lf
__BIGREAL_T seed_lf[CYCLE] static
Initial value:
= {
    21443106311501.0 / T46, 5197437683097.0 / T46,  3622043880426.0 / T46,
    53312694480426.0 / T46, 54665542338115.0 / T46, 51292272760733.0 / T46,
    28013141389639.0 / T46, 6466909594288.0 / T46,  36631377956900.0 / T46,
    45800305729322.0 / T46, 1486199964658.0 / T46,  1320339397524.0 / T46,
    42446291962239.0 / T46, 8221323655096.0 / T46,  1104293620992.0 / T46,
    2988247604277.0 / T46,  1440485417884.0 / T46,
}
Definition at line 504 of file rnum.c.
Referenced by advance_seed_lf(), ENTFTN(), prng_loop_d_lf(), and prng_loop_r_lf().
seed_lo
__BIGREAL_T seed_lo = DEFAULT_SEED_LO static
Definition at line 65 of file rnum.c.
Referenced by advance_seed_npb(), ENTFTN(), prng_loop_d_npb(), and prng_loop_r_npb().
start_time
time_t start_time static
Definition at line 489 of file rnum.c.
Referenced by ENTFTN().
start_time_is_set
int start_time_is_set = 0 static
Definition at line 488 of file rnum.c.
Referenced by ENTFTN().
table
__BIGREAL_T table[32][2] static
Initial value:
= {
    {4354965.0, T23 * 145.0},     {210105.0, T23 * 6909540.0},
    {3255729.0, T23 * 1196310.0}, {1750113.0, T23 * 3474515.0},
    {5016769.0, T23 * 2330923.0}, {8104321.0, T23 * 1946261.0},
    {3248897.0, T23 * 6040782.0}, {4990465.0, T23 * 1843409.0},
    {3951617.0, T23 * 3906254.0}, {563201.0, T23 * 912650.0},
    {5320705.0, T23 * 3689928.0}, {2252801.0, T23 * 6232675.0},
    {4505601.0, T23 * 6139918.0}, {622593.0, T23 * 6638909.0},
    {1245185.0, T23 * 5394170.0}, {2490369.0, T23 * 4419572.0},
    {4980737.0, T23 * 141288.0},  {1572865.0, T23 * 7434193.0},
    {3145729.0, T23 * 1531810.0}, {6291457.0, T23 * 48964.0},
    {4194305.0, T23 * 4816521.0}, {1.0, T23 * 3341587.0},
    {1.0, T23 * 6683174.0},       {1.0, T23 * 4977740.0},
    {1.0, T23 * 1566872.0},       {1.0, T23 * 3133744.0},
    {1.0, T23 * 6267488.0},       {1.0, T23 * 4146368.0},
    {1.0, T23 * 8292736.0},       {1.0, T23 * 8196864.0},
    {1.0, T23 * 8005120.0},       {1.0, T23 * 7621632.0}}
Definition at line 67 of file rnum.c.
Referenced by advance_seed_npb(), CONCAT(), ENTFTN(), getindex(), hashmap_sort(), prng_loop_d_npb(), and prng_loop_r_npb().
table_lf
const Seed table_lf[NDIGITS][DIGIT][LONG_LAG][LONG_LAG] static
Definition at line 520 of file rnum.c.
Referenced by advance_seed_lf().