flang: rpow.c File Reference
rpow.c File Reference
#include "libm_amd.h"
#include "libm_util_amd.h"
#include "libm_inlines_amd.h"
#include "libm_errno_amd.h"
Macros
#define USE_ZEROF_WITH_FLAGS
#define USE_INFINITYF_WITH_FLAGS
#define USE_NANF_WITH_FLAGS
#define USE_HANDLE_ERRORF
Functions
static float retval_errno_erange_overflow (float x __attribute__((unused)), float y __attribute__((unused)), int sign)
static float retval_errno_erange_underflow (float x __attribute__((unused)), float y __attribute__((unused)), int sign)
static float retval_errno_edom (float x __attribute__((unused)), float y __attribute__((unused)), int type)
float FN_PROTOTYPE() mth_i_rpowr (float x, float y)
Variables
static volatile int dummy
Macro Definition Documentation
USE_HANDLE_ERRORF
#define USE_HANDLE_ERRORF
Definition at line 48 of file rpow.c.
USE_INFINITYF_WITH_FLAGS
#define USE_INFINITYF_WITH_FLAGS
Definition at line 46 of file rpow.c.
USE_NANF_WITH_FLAGS
#define USE_NANF_WITH_FLAGS
Definition at line 47 of file rpow.c.
USE_ZEROF_WITH_FLAGS
#define USE_ZEROF_WITH_FLAGS
Definition at line 45 of file rpow.c.
Function Documentation
mth_i_rpowr()
float FN_PROTOTYPE() mth_i_rpowr (float x, float y)
Definition at line 90 of file rpow.c.
References dummy, EXPBIAS_SP32, EXPBITS_SP32, EXPSHIFTBITS_SP32, FN_PROTOTYPE, GET_BITS_SP32, MANTBITS_SP32, mth_i_dexp2(), mth_i_dlog2(), PUT_BITS_SP32, retval_errno_edom(), retval_errno_erange_overflow(), retval_errno_erange_underflow(), sqrt(), tiny, x, and y.
retval_errno_edom()
static float retval_errno_edom (float x __attribute__(unused), float y __attribute__(unused), int type) inline static
Definition at line 78 of file rpow.c.
References AMD_F_DIVBYZERO, AMD_F_INVALID, and type.
Referenced by mth_i_rpowr().
retval_errno_erange_overflow()
static float retval_errno_erange_overflow (float x __attribute__(unused), float y __attribute__(unused), int sign) inline static
Definition at line 59 of file rpow.c.
References AMD_F_OVERFLOW, and sign.
Referenced by mth_i_rpowr().
retval_errno_erange_underflow()
static float retval_errno_erange_underflow (float x __attribute__(unused), float y __attribute__(unused), int sign) inline static
Definition at line 68 of file rpow.c.
References AMD_F_INEXACT, AMD_F_UNDERFLOW, and sign.
Referenced by mth_i_rpowr().
Variable Documentation
dummy
volatile int dummy static
Definition at line 88 of file rpow.c.
Referenced by _cr_nme(), _find_pointer_assignments_f90(), _linearize_all(), convert_template_instance(), linearize_arrays(), mth_i_rpowr(), visit_ili_operands(), and write_extern_inits().