flang: rte.h File Reference
rte.h File Reference
Macros
#define __TAGPOLY 43
#define __TAGDESC 35
#define __TAGDERIVED 33
Functions
int sym_get_proc_sdescr (char *basename, int rank)
int sym_get_place_holder (char *basename, int dtype)
int sym_get_sdescr (int sptr, int rank)
int sym_get_sdescr_inherit (int)
void get_static_descriptor (int)
void get_all_descriptors (int)
int get_multiplier_index (int)
int get_global_lower_index (int)
int get_global_upper_index (int)
int get_global_extent_index (int)
int get_section_stride_index (int)
int get_section_offset_index (int)
int get_local_multiplier (int, int)
int get_xbase_index (void)
int get_xbase (int)
int get_global_lower (int, int)
int get_global_upper (int, int)
int get_extent (int, int)
int get_section_stride (int, int)
int get_section_offset (int, int)
int get_local_lower (int, int)
int get_local_upper (int, int)
int get_smp_p2 (int)
int get_desc_len (void)
int get_desc_flags (int)
int get_desc_gsize (int)
int get_desc_gsize_index (void)
int get_desc_lsize (int)
int get_lsize_index (void)
int get_proc_base (int)
int get_proc_stride (int, int)
int get_proc_shape (int, int)
int get_block_size (int, int)
int get_neg_ovlp (int, int)
int get_pos_ovlp (int, int)
int get_template_offset (int, int)
int get_descriptor_len (int rank)
int get_owner_lower (int sdsc, int dim)
int get_owner_upper (int sdsc, int dim)
int get_genblock (int sdsc, int dim)
int get_byte_len (int sdsc)
int get_byte_len_indx (void)
void set_descriptor_sc (int sc)
int get_desc_rank (int)
int get_kind (int)
int get_gbase (int)
int get_gbase2 (int)
int get_desc_tag (int)
void rewrite_asn (int, int, bool, int)
int get_descriptor_sc (void)
void set_descriptor_rank (int)
void set_preserve_descriptor (int)
void set_descriptor_class (int)
void set_final_descriptor (int)
int get_header_member_with_parent (int parent, int sdsc, int info)
Generate an AST for accessing a particular field in a descriptor header.
Detailed Description
Run-time data structures
Definition in file rte.h.
Macro Definition Documentation
__TAGDERIVED
#define __TAGDERIVED 33
Definition at line 143 of file rte.h.
__TAGDESC
#define __TAGDESC 35
Definition at line 140 of file rte.h.
__TAGPOLY
#define __TAGPOLY 43
Definition at line 137 of file rte.h.
Function Documentation
get_all_descriptors()
void get_all_descriptors (int sptr)
Definition at line 435 of file rte.c.
References a, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_MLPYR, AD_NUMELM, AD_UPAST, AD_UPBD, AD_ZBASE, assert, ast, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), astb, ASTB::bnd, DTY, ASTB::dtype, get_desc_gsize(), get_extent(), get_global_lower(), get_local_multiplier(), get_xbase(), i, mem(), mk_binop(), mk_isz_cval(), ndim, next, NOSYM, OP_ADD, OP_SUB, rank_of_sym(), sptr, sym_get_offset(), sym_get_ptr(), and trans_mkdescr().
Referenced by chk_struct_constructor(), construct_association(), decl_private_sym(), expand_common_pointers(), fix_args(), func_call2(), gen_allocatable_result(), gen_allocate_array(), gen_and_assoc_tmp_ptr(), gen_dtsfmt_args(), gen_pointer_result(), gen_vlist(), get_fval_array(), init_sptr_w_acl(), instantiate_interface(), make_rte_descriptor(), misc_checks(), mkarg(), mkexpr1(), mklvalue(), nml_emit_desc(), ptrfunc_call(), put_length_type_param(), ref_based_object_sc(), ref_entry(), reorder_common_pointers(), replace_arguments(), semant1(), semant3(), and transform_call().
get_block_size()
int get_block_size (int sdsc, int dim)
Definition at line 780 of file rte.c.
References astb, and ASTB::i0.
get_byte_len()
int get_byte_len (int sdsc)
Definition at line 642 of file rte.c.
References get_header_member().
Referenced by _sect(), _template(), convert_template_instance(), get_len_of_deferchar_ast(), semant3(), and temp_type_descriptor().
get_byte_len_indx()
int get_byte_len_indx (void)
Definition at line 648 of file rte.c.
Referenced by gen_kind_parm_assignments(), and get_len_of_deferchar_ast().
get_desc_flags()
int get_desc_flags (int sdsc)
Definition at line 732 of file rte.c.
References get_header_member().
Referenced by _sect(), and _template().
get_desc_gsize()
int get_desc_gsize (int sdsc)
Definition at line 744 of file rte.c.
References get_header_member().
Referenced by _sect(), _template(), fill_pointer_array_dtype(), get_all_descriptors(), semant3(), and temp_type_descriptor().
get_desc_gsize_index()
int get_desc_gsize_index (void)
Definition at line 738 of file rte.c.
Referenced by _PDsize(), and _pghpf_size().
get_desc_len()
int get_desc_len (void)
get_desc_lsize()
int get_desc_lsize (int sdsc)
Definition at line 750 of file rte.c.
References get_header_member().
Referenced by _sect(), _template(), semant3(), and temp_type_descriptor().
get_desc_rank()
int get_desc_rank (int sdsc)
Definition at line 720 of file rte.c.
References get_header_member().
Referenced by _sect(), _template(), semant3(), and temp_type_descriptor().
get_desc_tag()
int get_desc_tag (int sdsc)
Definition at line 726 of file rte.c.
References get_header_member().
Referenced by _sect(), _template(), check_alloc_ptr_type(), semant3(), and set_descr_tag().
get_descriptor_len()
int get_descriptor_len (int rank)
Definition at line 804 of file rte.c.
References rank.
Referenced by add_class_arg_descr_arg(), and size_of_var().
get_descriptor_sc()
int get_descriptor_sc (void)
Definition at line 90 of file rte.c.
References rte_sc.
Referenced by get_type_descr_arg2(), and semant1().
get_extent()
int get_extent (int sdsc, int dim)
Definition at line 672 of file rte.c.
References dim, and get_per_dim_member().
Referenced by _sect(), _template(), copy_desc_to_bnds_vars(), fill_pointer_array_dtype(), get_all_descriptors(), mk_extent(), mk_shared_extent(), and put_length_type_param().
get_gbase()
int get_gbase (int sdsc)
Definition at line 624 of file rte.c.
References get_header_member().
Referenced by _sect(), _template(), and conv_allocate().
get_gbase2()
int get_gbase2 (int sdsc)
Definition at line 630 of file rte.c.
References get_header_member().
Referenced by _sect(), and _template().
get_genblock()
int get_genblock (int sdsc, int dim)
get_global_extent_index()
int get_global_extent_index (int dim)
Definition at line 594 of file rte.c.
References dim.
Referenced by _PDsize(), _pghpf_bound(), _pghpf_size(), _ptrassign(), extent(), full_dimension(), gen_bounds_assignments(), and lower_ast().
get_global_lower()
int get_global_lower (int sdsc, int dim)
Definition at line 660 of file rte.c.
References dim, and get_per_dim_member().
Referenced by _sect(), _template(), copy_desc_to_bnds_vars(), diff_lbnd(), fill_pointer_array_dtype(), get_all_descriptors(), get_local_lower(), get_owner_lower(), and set_assumed_bounds().
get_global_lower_index()
int get_global_lower_index (int dim)
Definition at line 582 of file rte.c.
References dim.
Referenced by _pghpf_bound(), _ptrassign(), build_allocation_item(), full_dimension(), gen_bounds_assignments(), and lower_ast().
get_global_upper()
int get_global_upper (int sdsc, int dim)
Definition at line 666 of file rte.c.
References dim, and get_per_dim_member().
Referenced by _sect(), _template(), get_local_upper(), and get_owner_upper().
get_global_upper_index()
int get_global_upper_index (int dim)
Definition at line 588 of file rte.c.
References dim.
Referenced by build_allocation_item(), full_dimension(), and gen_bounds_assignments().
get_header_member_with_parent()
int get_header_member_with_parent (int parent, int sdsc, int info)
Generate an AST for accessing a particular field in a descriptor header.
Note: This is similar to get_header_member() above except it also operates on descriptors that are embedded in derived type objects.
Parameters
parent is the ast of the expression with the descriptor that we want to access. This is needed if the descriptor is embedded in a derived type object.
sdsc is the symbol table pointer of the descriptor we want to access.
info is the field we want to access in the descriptor.
Returns
an ast expression of the descriptor access.
Definition at line 844 of file rte.c.
References ast, astb, ASTB::bnd, check_member(), DTY, ASTB::dtype, info, interr(), mk_id(), mk_isz_cval(), mk_subscr(), and parent.
Referenced by inline_contig_check().
get_kind()
int get_kind (int sdsc)
Definition at line 636 of file rte.c.
References get_header_member().
Referenced by _sect(), _template(), construct_association(), convert_template_instance(), semant3(), and temp_type_descriptor().
get_local_lower()
int get_local_lower (int sdsc, int dim)
Definition at line 690 of file rte.c.
References dim, and get_global_lower().
Referenced by get_allobnds().
get_local_multiplier()
int get_local_multiplier (int sdsc, int dim)
Definition at line 654 of file rte.c.
References dim, and get_per_dim_member().
Referenced by _linearize(), _sect(), _template(), fill_pointer_array_dtype(), get_all_descriptors(), print_ast(), put_length_type_param(), and set_assumed_bounds().
get_local_upper()
int get_local_upper (int sdsc, int dim)
Definition at line 696 of file rte.c.
References dim, and get_global_upper().
Referenced by get_allobnds().
get_lsize_index()
int get_lsize_index (void)
Definition at line 756 of file rte.c.
Referenced by lower_stmt().
get_multiplier_index()
int get_multiplier_index (int dim)
Definition at line 576 of file rte.c.
References dim.
Referenced by _ptrassign(), and lower_ast().
get_neg_ovlp()
int get_neg_ovlp (int sdsc, int dim)
Definition at line 786 of file rte.c.
References astb, and ASTB::i0.
get_owner_lower()
int get_owner_lower (int sdsc, int dim)
Definition at line 702 of file rte.c.
References dim, and get_global_lower().
Referenced by gen_islocal_index(), and inline_hlocalizebnds().
get_owner_upper()
int get_owner_upper (int sdsc, int dim)
Definition at line 708 of file rte.c.
References dim, and get_global_upper().
Referenced by gen_islocal_index(), and inline_hlocalizebnds().
get_pos_ovlp()
int get_pos_ovlp (int sdsc, int dim)
Definition at line 792 of file rte.c.
References astb, and ASTB::i0.
get_proc_base()
int get_proc_base (int sdsc)
Definition at line 762 of file rte.c.
References astb, and ASTB::i0.
get_proc_shape()
int get_proc_shape (int sdsc, int dim)
Definition at line 768 of file rte.c.
References astb, and ASTB::i1.
get_proc_stride()
int get_proc_stride (int sdsc, int dim)
Definition at line 774 of file rte.c.
References dim, and get_section_stride().
get_section_offset()
int get_section_offset (int sym, int dim)
Definition at line 684 of file rte.c.
References dim, and get_per_dim_member().
Referenced by _sect(), _template(), cyclic_section(), get_template_offset(), print_ast(), and set_assumed_bounds().
get_section_offset_index()
int get_section_offset_index (int dim)
Definition at line 606 of file rte.c.
References dim.
Referenced by _ptrassign(), and lower_ast().
get_section_stride()
int get_section_stride (int sym, int dim)
Definition at line 678 of file rte.c.
References dim, and get_per_dim_member().
Referenced by _sect(), _template(), cyclic_section(), get_proc_stride(), and set_assumed_bounds().
get_section_stride_index()
int get_section_stride_index (int dim)
Definition at line 600 of file rte.c.
References dim.
Referenced by _ptrassign(), and lower_ast().
get_smp_p2()
int get_smp_p2 (int)
get_static_descriptor()
void get_static_descriptor (int sptr)
Definition at line 413 of file rte.c.
References is_procedure_ptr(), sptr, and sym_get_sdescr().
Referenced by _constructf90(), add_ptr_assign(), check_alloc_ptr_type(), chk_struct_constructor(), construct_association(), decl_private_sym(), expand_common_pointers(), fix_args(), func_call2(), gen_allocatable_result(), gen_allocate_array(), gen_and_assoc_tmp_ptr(), gen_contig_check(), gen_dtsfmt_args(), gen_finalization_for_sym(), gen_pointer_result(), gen_poly_element_arg(), gen_vlist(), genPolyAsn(), get_fval_array(), get_invoking_proc_desc(), get_sdsc_ast(), get_static_type_descriptor(), get_type_descr_arg(), get_type_descr_arg2(), init_sptr_w_acl(), initFinalSub(), instantiate_interface(), make_rte_descriptor(), misc_checks(), mkarg(), mkexpr1(), mklvalue(), nml_emit_desc(), ptrfunc_call(), put_length_type_param(), ref_based_object_sc(), ref_entry(), ref_pd(), reorder_common_pointers(), replace_arguments(), rewrite_allocatable_assignment(), semant1(), semant3(), set_parref_flag(), and transform_call().
get_template_offset()
int get_template_offset (int sdsc, int dim)
Definition at line 798 of file rte.c.
References dim, and get_section_offset().
get_xbase()
int get_xbase (int sdsc)
Definition at line 618 of file rte.c.
References get_header_member().
Referenced by _linearize(), _sect(), _template(), fill_pointer_array_dtype(), get_all_descriptors(), print_ast(), and set_assumed_bounds().
get_xbase_index()
int get_xbase_index (void)
Definition at line 612 of file rte.c.
Referenced by lower_ast().
rewrite_asn()
void rewrite_asn (int ast, int std, bool flag, int lc)
Definition at line 3776 of file func.c.
References allocate_lhs_if_needed(), args, ASD_NDIM, ASD_SUBS, ast, delete_stmt(), inline_reduction_f90(), j, arg_gbl::lhs, lhs, n, rewrite_func_ast(), rewrite_sub_args(), rewrite_sub_ast(), std, STD_NEXT, and STD_PREV.
Referenced by conv_forall(), conv_fused_forall(), and rewrite_calls().
set_descriptor_class()
void set_descriptor_class (int class)
Definition at line 47 of file rte.c.
References rte_class.
Referenced by get_static_type_descriptor(), and initFinalSub().
set_descriptor_rank()
void set_descriptor_rank (int r)
Definition at line 56 of file rte.c.
References r, and rte_rank.
Referenced by check_alloc_ptr_type(), construct_association(), gen_poly_element_arg(), semant1(), and semant3().
set_descriptor_sc()
void set_descriptor_sc (int sc)
Definition at line 83 of file rte.c.
References rte_sc, and set_symutl_sc().
Referenced by call_analyze(), comm_analyze(), convert_statements(), decl_private_sym(), forall_dependency_analyze(), forall_init(), func_call2(), gen_allocatable_result(), get_temp_forall2(), get_type_descr_arg2(), ptrfunc_call(), rewrite_block_where(), rewrite_calls(), rewrite_forall(), rewrite_into_forall(), and semant1().
set_final_descriptor()
void set_final_descriptor (int d)
Definition at line 76 of file rte.c.
References d, and rte_final_desc.
Referenced by initFinalSub().
set_preserve_descriptor()
void set_preserve_descriptor (int d)
Definition at line 65 of file rte.c.
References d, and rte_preserve_desc.
Referenced by newargs_for_entry(), and semant1().
sym_get_place_holder()
int sym_get_place_holder (char * basename, int dtype)
Definition at line 404 of file rte.c.
References sptr, and sym_get_scalar().
sym_get_proc_sdescr()
int sym_get_proc_sdescr (char * basename, int rank)
sym_get_sdescr()
int sym_get_sdescr (int sptr, int rank)
Definition at line 171 of file rte.c.
References ADD_ADJARR, ADD_DEFER, ADD_LWAST, ADD_LWBD, ADD_NOBOUNDS, ADD_NUMDIM, ADD_NUMELM, ADD_UPAST, ADD_UPBD, ALIGNG, assert, astb, ASTB::bnd, CUDA_DEVICE, CUDA_GLOBAL, CUDAG, STB::curr_scope, DISTG, DTY, ASTB::dtype, FALSE, gbl, get_array_dtype(), get_dtype_init_template(), get_next_sym(), get_next_sym_dt(), get_struct_initialization_tree(), getitem(), getsymf(), len, lenWithUnderscores(), mangleUnderscores(), MAXIDLEN, mem(), mk_isz_cval(), NOSYM, ASTB::one, rank, rte_class, rte_final_desc, rte_preserve_desc, rte_rank, rte_sc, sptr, stb, strlen(), SYMNAME, TRUE, TY_CHAR, TY_NCHAR, ub, and void().
Referenced by emit_alnd_secd(), get_static_descriptor(), make_sec_ast(), make_sec_from_ast_chk(), make_secd_for_members(), make_simple_template_from_ast(), prepare_for_astout(), put_length_type_param(), share_alnd(), share_secd(), and sym_get_arg_sec().
sym_get_sdescr_inherit()
int sym_get_sdescr_inherit (int)