flang: rtlRtns.c File Reference
rtlRtns.c File Reference
#include <string.h>
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "rtlRtnsDesc.h"
#include "rtlRtns.h"
Classes
struct F90TmplSectRtns
Functions
const char * mkRteRtnNm (FtnRtlEnum rteRtn)
given a FtnRtlEnum, return the RTL routine name
static void stripI8DescrSuffix (const char *inNm, char *outNm)
static int setTmplSectRtnFtype (int i)
int getF90TmplSectRtn (char *rtnNm)
Returns an integer bitfield contain information about a RTL routine that creates or modifies an array descriptor. If the routine does not create or modify an array descriptor, zero is returned.
Variables
FtnRteRtn ftnRtlRtns []
static F90TmplSectRtns f90TmplSectRtns []
Function Documentation
getF90TmplSectRtn()
int getF90TmplSectRtn (char * rtnNm)
Returns an integer bitfield contain information about a RTL routine that creates or modifies an array descriptor. If the routine does not create or modify an array descriptor, zero is returned.
Definition at line 904 of file rtlRtns.c.
References f90TmplSectRtns, h, m, MAXIDLEN, mkRteRtnNm(), r, setTmplSectRtnFtype(), and stripI8DescrSuffix().
Referenced by bld_ud(), markmodified(), sectinline(), and sfloat().
mkRteRtnNm()
const char * mkRteRtnNm (FtnRtlEnum rteRtn)
given a FtnRtlEnum, return the RTL routine name
...
Definition at line 809 of file rtlRtns.c.
References assert, END_OF_FTNIO, END_OF_IO, END_OF_PFX_F90, END_OF_PFX_FTN, ERR_Severe, ftnRtlRtns, FtnRteRtn::fullNm, RTE_no_rtn, strlen(), and XBIT.
Referenced by _constructf90(), _simple_replacements(), add_cgoto(), add_ptr_assign(), add_reduce_descriptor(), add_spread_descriptor(), allochartmp(), ast_intr(), build_conformable_func_node(), build_poly_func_node(), check_doconcurrent_ast(), check_pointer_type(), collapse_assignment(), conv_allocate(), conv_deallocate(), convert_template_instance(), copy_arg_to_seq_tmp(), do_nml(), elem_size_of_ast(), emit_alnd(), emit_alnd_secd(), emit_fl(), emit_get_scalar_sub(), emit_kopy_in(), emit_permute_section(), emit_redim(), emit_scalar_kopy_in(), emit_scatterx_gatherx(), emit_secd(), emit_sum_scatterx(), exp_ac(), exp_call(), exp_end(), exp_strcpy(), exp_strx(), extent(), fill_ast(), fill_cyclic_k(), find_member_base(), function_null_allowed(), gen_allocate(), gen_call_class_obj_size(), gen_contig_check(), gen_deallocate(), gen_finalization_for_sym(), gen_init_unl_poly_desc(), gen_islocal_index(), gen_localize_index(), gen_nullify(), gen_poly_element_arg(), generate_copy(), generate_gather(), generate_get_scalar(), generate_hcycliclp(), generate_hlocalizebnds(), genPolyAsn(), get_invoking_proc_desc(), getF90TmplSectRtn(), getMergeSym(), init_derived_type(), init_sdsc(), init_sdsc_bounds(), intrinsic_as_arg(), is_asn_closure_call(), is_same_mask(), lower_ast(), lower_check_ast(), lower_init_sym(), lower_intrinsic(), lower_start_subroutine(), lower_stmt(), make_sec_from_ast_chk(), make_simple_template_from_ast(), make_temp_descriptor(), matmul(), mk_coercion_func_name(), mk_hpfiofunc(), mk_iofunc(), mk_merge(), mk_set_type_call(), mmul(), pghpf_entry(), presence_test(), print_ast(), print_loc(), print_loc_of_sym(), ref_intrin(), ref_pd(), ref_pd_subr(), reshape(), rewrite_allocatable_assignment(), rewrite_func_ast(), semant2(), semant3(), semantio(), semfin(), set_assumed_bounds(), set_assumsz_bound(), set_type_in_descriptor(), size_of_dtype(), trans_mkproc(), transform_associated(), transform_c_f_pointer(), transform_c_f_procpointer(), transform_call(), and transform_move_alloc().
setTmplSectRtnFtype()
static int setTmplSectRtnFtype (int i) static
Definition at line 891 of file rtlRtns.c.
References f90TmplSectRtns, F90TmplSectRtns::ftype, FTYPE_I8, i, and XBIT.
Referenced by getF90TmplSectRtn().
stripI8DescrSuffix()
static void stripI8DescrSuffix (const char * inNm, char * outNm) static
Definition at line 856 of file rtlRtns.c.
References assert, ERR_Severe, MAXIDLEN, strlen(), and XBIT.
Referenced by getF90TmplSectRtn().
Variable Documentation
f90TmplSectRtns
F90TmplSectRtns f90TmplSectRtns[] static
Initial value:
= {
    {RTE_sect, FTYPE_SECT},           {RTE_sect1, FTYPE_SECT},
    {RTE_sect1v, FTYPE_SECT},         {RTE_sect2, FTYPE_SECT},
    {RTE_sect2v, FTYPE_SECT},         {RTE_sect3, FTYPE_SECT},
    {RTE_sect3v, FTYPE_SECT},         {RTE_template, FTYPE_TEMPLATE},
    {RTE_template1, FTYPE_TEMPLATE1}, {RTE_template1v, FTYPE_TEMPLATE1V},
    {RTE_template2, FTYPE_TEMPLATE2}, {RTE_template2v, FTYPE_TEMPLATE2V},
    {RTE_template3, FTYPE_TEMPLATE3}, {RTE_template3v, FTYPE_TEMPLATE3V},
}
Definition at line 880 of file rtlRtns.c.
Referenced by getF90TmplSectRtn(), and setTmplSectRtnFtype().
ftnRtlRtns
FtnRteRtn ftnRtlRtns[]
Definition at line 23 of file rtlRtns.c.
Referenced by mkRteRtnNm().