flang: dist.c File Reference
runtime/flang/dist.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "scatter.h"
#include "fort_vars.h"
Macros
#define NPRIMES 31
#define BOGUSFLAG 0x100
#define ASECTION(d, dx, a, ax, lb, ub, st, gsize, flags)
#define TSECTION(d, dx, a, ax, lb, ub, st, gsize, flags)
#define BSECTION(d, dx, a, ax, lb, ub, st, gsize, flags)
Functions
void * ENTFTN (COMM_START, comm_start)
void I8() __fort_gen_block_bounds (F90_Desc *d, int dim, __INT_T *the_olb, __INT_T *the_oub, __INT_T pcoord)
static int div_shift (int n)
__INT_T (__INT_T *x, __INT_T *y)
unsigned long _int_mult_upper (int x, int y)
int __fort_gcd (int u, int v)
int __fort_lcm (int u, int v)
int I8() __fort_owner (F90_Desc *d, __INT_T *idxv)
__INT_T (F90_Desc *d,...)
void I8() __fort_describe_replication (F90_Desc *d, repl_t *r)
int I8() __fort_next_owner (F90_Desc *d, repl_t *r, int *pcoord, int owner)
__LOG_T (F90_Desc *d, __INT_T *dimb, __INT_T *idxb)
int I8() __fort_islocal (F90_Desc *d, __INT_T *idxv)
__LOG_T (F90_Desc *d,...)
void I8() __fort_localize (F90_Desc *d, __INT_T *idxv, int *cpu, __INT_T *off)
void ENTFTN (LOCALIZE_DIM, localize_dim)
__INT_T I8() __fort_local_offset (F90_Desc *d, __INT_T *idxv)
void *I8() __fort_local_address (void *base, F90_Desc *d, __INT_T *idxv)
__INT_T (F90_Desc *d, __INT_T *dimb, __INT_T *idxb)
static int I8() cyclic_setup (F90_Desc *d, __INT_T dim, __INT_T l, __INT_T u, __INT_T s, __INT_T *pcl, __INT_T *pcs, __INT_T *plof, __INT_T *plos)
void I8() __fort_cycle_bounds (F90_Desc *d)
__INT_T I8() __fort_cyclic_loop (F90_Desc *d, __INT_T dim, __INT_T l, __INT_T u, __INT_T s, __INT_T *cl, __INT_T *cu, __INT_T *cs, __INT_T *clof, __INT_T *clos)
void ENTFTN (CYCLIC_LOOP, cyclic_loop)
void I8() block_setup (F90_Desc *d, int dim, __INT_T l, __INT_T u, int s, int ci, __INT_T *bl, __INT_T *bu)
void ENTFTN (BLOCK_LOOP, block_loop)
int I8() __fort_block_loop (F90_Desc *d, int dim, __INT_T l, __INT_T u, int s, __INT_T ci, __INT_T *bl, __INT_T *bu)
__INT_T I8() __fort_block_bounds (F90_Desc *d, __INT_T dim, __INT_T ci, __INT_T *bl, __INT_T *bu)
void ENTFTN (LOCALIZE_BOUNDS, localize_bounds)
static void proc_setup (proc *p)
void ENTFTN (PROCESSORS, processors)
proc * __fort_defaultproc (int rank)
proc * __fort_localproc ()
void I8() __fort_set_alignment (F90_Desc *d, __INT_T dim, __INT_T lbound, __INT_T ubound, __INT_T taxis, __INT_T tstride, __INT_T toffset,...)
void I8() __fort_use_allocation (F90_Desc *d, __INT_T dim, __INT_T no, __INT_T po, F90_Desc *a)
void I8() __fort_set_single (F90_Desc *d, F90_Desc *a, __INT_T dim, __INT_T idx, _set_single_enum what)
void I8() __fort_finish_descriptor (F90_Desc *d)
void I8() __fort_set_sectionx (F90_Desc *d, __INT_T ddim, F90_Desc *a, __INT_T adim, __INT_T l, __INT_T u, __INT_T s, __INT_T noreindex)
void I8() __fort_set_section (F90_Desc *d, __INT_T ddim, F90_Desc *a, __INT_T adim, __INT_T l, __INT_T u, __INT_T s)
void I8() __fort_finish_section (F90_Desc *d)
void ENTFTN (SECT, sect)
void ENTF90 (SECT, sect)
void ENTF90 (SECT1, sect1)
void ENTF90 (SECT1v, sect1v)
void ENTF90 (SECT2, sect2)
void ENTF90 (SECT2v, sect2v)
void ENTF90 (SECT3, sect3)
void ENTF90 (SECT3v, sect3v)
void ENTFTN (SECT3, sect3)
void ENTFTN (SECT3v, sect3v)
void I8() __fort_copy_descriptor (F90_Desc *d, F90_Desc *d0)
F90_Desc *I8() __fort_inherit_template (F90_Desc *d, __INT_T rank, F90_Desc *target)
__INT_T (F90_Desc *d, __INT_T *gdim)
__INT_T ENTFTN (LBOUND, lbound)
__INT8_T ENTFTN (KLBOUND, klbound)
__INT_T ENTFTN (UBOUND, ubound)
__INT8_T ENTFTN (KUBOUND, kubound)
void ENTFTN (LBOUNDA, lbounda)
void ENTFTN (LBOUNDA1, lbounda1)
void ENTFTN (LBOUNDA2, lbounda2)
void ENTFTN (LBOUNDA4, lbounda4)
void ENTFTN (LBOUNDA8, lbounda8)
void ENTFTN (LBOUNDAZ, lboundaz)
void ENTFTN (LBOUNDAZ1, lboundaz1)
void ENTFTN (LBOUNDAZ2, lboundaz2)
void ENTFTN (LBOUNDAZ4, lboundaz4)
void ENTFTN (LBOUNDAZ8, lboundaz8)
void ENTFTN (KLBOUNDA, klbounda)
void ENTFTN (KLBOUNDAZ, klboundaz)
void ENTFTN (UBOUNDA, ubounda)
void ENTFTN (UBOUNDA1, ubounda1)
void ENTFTN (UBOUNDA2, ubounda2)
void ENTFTN (UBOUNDA4, ubounda4)
void ENTFTN (UBOUNDA8, ubounda8)
void ENTFTN (UBOUNDAZ, uboundaz)
void ENTFTN (UBOUNDAZ1, uboundaz1)
void ENTFTN (UBOUNDAZ2, uboundaz2)
void ENTFTN (UBOUNDAZ4, uboundaz4)
void ENTFTN (UBOUNDAZ8, uboundaz8)
void ENTFTN (KUBOUNDA, kubounda)
void ENTFTN (KUBOUNDAZ, kuboundaz)
__INT_T ENTFTN (SIZE, size)
__INT8_T ENTFTN (KSIZE, ksize)
void ENTFTN (SHAPE, shape)
void ENTFTN (KSHAPE, kshape)
void I8() __fort_reverse_array (char *db, char *ab, F90_Desc *dd, F90_Desc *ad)
Variables
static proc * default_proc_list [MAXDIMS+1] = {NULL}
static int prime [NPRIMES]
static proc * local_proc
Macro Definition Documentation
ASECTION
#define ASECTION (d, dx, a, ax, lb, ub, st, gsize, flags)
Value:
  if (flags & (1 << (ax - 1))) {                                               \
    dx++;                                                                      \
    __DIST_SET_SECTIONXX(d, dx, a, ax, lb, ub, st, (flags & __NOREINDEX),       \
                        gsize);                                                \
  } else                                                                       \
    I8(__fort_set_single)(d, a, ax, lb, __SCALAR);
Definition at line 1598 of file runtime/flang/dist.c.
BOGUSFLAG
#define BOGUSFLAG 0x100
Definition at line 1505 of file runtime/flang/dist.c.
BSECTION
#define BSECTION (d, dx, a, ax, lb, ub, st, gsize, flags)
Value:
  if (flags & (1 << (ax - 1))) {                                               \
    dx++;                                                                      \
    __DIST_SET_SECTIONXX(d, dx, a, ax, lb, ub, st, (flags & __NOREINDEX),       \
                        gsize);                                                \
  } else                                                                       \
    I8(__fort_set_single)(d, a, ax, lb, __SCALAR);
Definition at line 2237 of file runtime/flang/dist.c.
NPRIMES
#define NPRIMES 31
Definition at line 1107 of file runtime/flang/dist.c.
TSECTION
#define TSECTION (d, dx, a, ax, lb, ub, st, gsize, flags)
Definition at line 1608 of file runtime/flang/dist.c.
Function Documentation
__fort_block_bounds()
__INT_T I8() __fort_block_bounds (F90_Desc * d, __INT_T dim, __INT_T ci, __INT_T * bl, __INT_T * bu)
Definition at line 960 of file runtime/flang/dist.c.
References block_setup(), d, DECL_DIM_PTRS, dim, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, I8, and SET_DIM_PTRS.
Referenced by copy_loop(), ENTFTN(), fills_loop(), gathscat_loop(), gathscat_mask_loop(), kred_array_loop(), local_copy(), mmul_mxm(), mmul_mxv(), mmul_vxm(), olap_loop(), olap_recv(), olap_send(), print_loop(), prng_loop_d_lf(), prng_loop_d_npb(), prng_loop_r_lf(), prng_loop_r_npb(), red_array_loop(), and red_scalar_loop().
__fort_block_loop()
int I8() __fort_block_loop (F90_Desc * d, int dim, __INT_T l, __INT_T u, int s, __INT_T ci, __INT_T * bl, __INT_T * bu)
Definition at line 943 of file runtime/flang/dist.c.
References block_setup(), d, dim, I8, and s.
Referenced by gathscat_loop(), and gathscat_mask_loop().
__fort_copy_descriptor()
void I8() __fort_copy_descriptor (F90_Desc * d, F90_Desc * d0)
Definition at line 2409 of file runtime/flang/dist.c.
References __DESC, __fort_bcopy(), d, F90_RANK_G, F90_TAG_G, F90_TAG_P, SET_F90_DIST_DESC_PTR, and SIZE_OF_RANK_n_ARRAY_DESC.
Referenced by __fort_inherit_template(), and ENTFTN().
__fort_cycle_bounds()
void I8() __fort_cycle_bounds (F90_Desc * d)
Definition at line 743 of file runtime/flang/dist.c.
References cyclic_setup(), d, DECL_DIM_PTRS, dim, DIST_CACHED_G, DIST_CACHED_P, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_P, DIST_DPTR_CS_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_RANK_G, I8, and SET_DIM_PTRS.
Referenced by __fort_copy_out(), __fort_fills(), __fort_gathscat(), __fort_kred_arraylk(), __fort_kred_scalarlk(), __fort_print_local(), __fort_red_array(), __fort_red_arraylk(), __fort_red_scalar(), __fort_red_scalarlk(), copy_setup(), ENTFTN(), mmul_mxm(), mmul_mxv(), mmul_vxm(), and olap_shift().
__fort_cyclic_loop()
__INT_T I8() __fort_cyclic_loop (F90_Desc * d, __INT_T dim, __INT_T l, __INT_T u, __INT_T s, __INT_T * cl, __INT_T * cu, __INT_T * cs, __INT_T * clof, __INT_T * clos)
Definition at line 768 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), cl, cs, cyclic_setup(), d, DECL_DIM_PTRS, dim, DIST_CACHED_G, DIST_CACHED_P, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CN_P, DIST_DPTR_CS_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_RANK_G, F90_TAG_G, I8, m, NULL, s, and SET_DIM_PTRS.
Referenced by ENTFTN(), gathscat_loop(), gathscat_mask_loop(), mmul_mxv(), and mmul_vxm().
__fort_defaultproc()
proc * __fort_defaultproc (int rank)
Definition at line 1113 of file runtime/flang/dist.c.
References __fort_abort(), __fort_malloc(), __PROC, default_proc_list, GET_DIST_TCPUS, i, k, MAXDIMS, NPRIMES, NULL, p, prime, proc_setup(), rank, and t.
Referenced by ENTFTN().
__fort_describe_replication()
void I8() __fort_describe_replication (F90_Desc * d, repl_t * r)
Definition at line 280 of file runtime/flang/dist.c.
References d, DECL_DIM_PTRS, DIST_DIST_TARGET_G, DIST_DPTR_PCOORD_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_PSTRIDE_G, DIST_MAPPED_G, DIST_PBASE_G, DIST_REPLICATED_G, F90_RANK_G, m, ndim, p, pd, r, and SET_DIM_PTRS.
Referenced by __fort_copy(), __fort_gathscat(), __fortio_main(), and ENTFTN().
__fort_finish_descriptor()
void I8() __fort_finish_descriptor (F90_Desc * d)
Definition at line 1367 of file runtime/flang/dist.c.
References __DERIVED, __fort_abort(), __fort_heap_block, __NONE, __STR, d, DECL_DIM_PTRS, DIST_DPTR_LAB_G, DIST_DPTR_LOFFSET_P, DIST_HEAPB_G, DIST_HEAPB_P, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_P, F90_GSIZE_P, F90_KIND_G, F90_LBASE_P, F90_LEN_G, F90_LSIZE_P, F90_RANK_G, GET_DIST_SHIFTS, i, lbase, rank, and SET_DIM_PTRS.
Referenced by __fort_copy_out(), ENTF90(), ENTFTN(), ptr_asgn(), and void().
__fort_finish_section()
void I8() __fort_finish_section (F90_Desc * d)
Definition at line 1485 of file runtime/flang/dist.c.
References __SEQUENCE, d, DIST_NONSEQUENCE_G, F90_DIM_EXTENT_G, F90_FLAGS_G, F90_FLAGS_P, F90_GSIZE_P, F90_RANK_G, i, and rank.
Referenced by __fort_copy(), cshift_loop(), ENTFTN(), and eoshift_scalar().
__fort_gcd()
int __fort_gcd (int u, int v)
Definition at line 165 of file runtime/flang/dist.c.
References k, m, n, and t.
Referenced by __fort_lcm().
__fort_gen_block_bounds()
void I8() __fort_gen_block_bounds (F90_Desc * d, int dim, __INT_T * the_olb, __INT_T * the_oub, __INT_T pcoord)
Definition at line 28 of file runtime/flang/dist.c.
References __fort_abort(), __fort_free(), __fort_new_gen_block(), d, DECL_DIM_PTRS, dim, DIST_DPTR_GEN_BLOCK_G, DIST_DPTR_PSHAPE_G, DIST_DPTR_TLB_G, DIST_DPTR_TSTRIDE_G, DIST_DPTR_TUB_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, i, I8, and SET_DIM_PTRS.
__fort_inherit_template()
F90_Desc *I8() __fort_inherit_template (F90_Desc * d, __INT_T rank, F90_Desc * target)
Definition at line 2423 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), __fort_copy_descriptor(), __NOT_COPIED, __TEMPLATE, ALIGNR, d, DECL_HDR_PTRS, DIST_ACTUAL_ARG_P, DIST_ALIGN_TARGET_P, DIST_NEXT_ALIGNEE_P, F90_FLAGS_G, F90_FLAGS_P, F90_LSIZE_P, F90_TAG_G, I8, MAXDIMS, NULL, rank, SIZE_OF_RANK_n_ARRAY_DESC, and t.
__fort_islocal()
int I8() __fort_islocal (F90_Desc * d, __INT_T * idxv)
Definition at line 372 of file runtime/flang/dist.c.
References __OFF_TEMPLATE, d, DECL_DIM_PTRS, DFMT__WIDTH, DIST_DFMT_G, F90_FLAGS_G, and SET_DIM_PTRS.
Referenced by __LOG_T(), and ENTFTN().
__fort_lcm()
int __fort_lcm (int u, int v)
Definition at line 218 of file runtime/flang/dist.c.
References __fort_gcd(), and p.
__fort_local_address()
void *I8() __fort_local_address (void * base, F90_Desc * d, __INT_T * idxv)
Definition at line 597 of file runtime/flang/dist.c.
References __fort_abort(), __OFF_TEMPLATE, __SEQUENCE, base, d, DECL_DIM_PTRS, DFMT__MASK, DFMT__WIDTH, DFMT_BLOCK, DFMT_BLOCK_K, DFMT_COLLAPSED, DFMT_GEN_BLOCK, DIST_DFMT_G, DIST_DPTR_OLB_G, DIST_DPTR_OUB_G, DIST_SCOFF_G, DPTR_UBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_LBASE_G, F90_LEN_G, F90_RANK_G, idx, NULL, offset, and SET_DIM_PTRS.
Referenced by __fort_get_scalar(), __fort_store_int_element(), __fort_store_int_vector(), __io_read(), __io_write(), ENTFTN(), eval_dtio_sb(), eval_sb(), fetch_vector(), kred_array_loop(), red_array_loop(), red_scalar_loop(), store_element(), store_vector(), and store_vector_int().
__fort_local_offset()
__INT_T I8() __fort_local_offset (F90_Desc * d, __INT_T * idxv)
Definition at line 555 of file runtime/flang/dist.c.
References __fort_abort(), __fort_test, __OFF_TEMPLATE, __SEQUENCE, d, DEBUG_DIST, DECL_DIM_PTRS, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_LBASE_G, F90_RANK_G, GET_DIST_LCPU, idx, offset, and SET_DIM_PTRS.
Referenced by ENTFTN(), and gathscat_element().
__fort_localize()
void I8() __fort_localize (F90_Desc * d, __INT_T * idxv, int * cpu, __INT_T * off)
Definition at line 410 of file runtime/flang/dist.c.
References __fort_abort(), __fort_test, Ceil, cpu(), d, DEBUG_DIST, DECL_DIM_PTRS, DFMT__MASK, DFMT__WIDTH, DFMT_COLLAPSED, DIST_DFMT_G, DIST_DIST_TARGET_G, DIST_DPTR_AOFFSET_G, DIST_DPTR_ASTRIDE_G, DIST_DPTR_BLOCK_G, DIST_DPTR_CLB_G, DIST_DPTR_CYCLE_G, DIST_DPTR_GEN_BLOCK_G, DIST_DPTR_LAB_G, DIST_DPTR_NO_G, DIST_DPTR_PSTRIDE_G, DIST_PBASE_G, DIST_REPLICATED_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_RANK_G, GET_DIST_LCPU, off, offset, p, pd, and SET_DIM_PTRS.
Referenced by gathscat_element().
__fort_localproc()
proc * __fort_localproc (void)
Definition at line 1187 of file runtime/flang/dist.c.
References __fort_malloc(), __LOCAL, __PROC, proc::base, proc::flags, GET_DIST_LCPU, local_proc, MAXDIMS, NULL, proc_setup(), proc::rank, and proc::tag.
Referenced by void().
__fort_next_owner()
int I8() __fort_next_owner (F90_Desc * d, repl_t * r, int * pcoord, int owner)
Definition at line 332 of file runtime/flang/dist.c.
References i, and r.
__fort_owner()
int I8() __fort_owner (F90_Desc * d, __INT_T * idxv)
Definition at line 227 of file runtime/flang/dist.c.
Referenced by __INT_T().
__fort_reverse_array()
void I8() __fort_reverse_array (char * db, char * ab, F90_Desc * dd, F90_Desc * ad)
Definition at line 2920 of file runtime/flang/dist.c.
References _0, __ASSUMED_GB_EXTENT, __DIST_TARGET_AXIS, __DUMMY_COLLAPSE_PAXIS, __fort_abort(), __PRESCRIPTIVE_DIST_FORMAT, __PRESCRIPTIVE_DIST_TARGET, add(), db(), DECL_DIM_PTRS, DECL_HDR_VARS, DFMT, DFMT_BLOCK, DFMT_BLOCK_K, DFMT_COLLAPSED, DFMT_CYCLIC, DFMT_CYCLIC_K, DFMT_GEN_BLOCK, DIST_DIST_TARGET_G, DIST_DPTR_BLOCK_G, DIST_DPTR_GEN_BLOCK_G, DIST_DPTR_NO_G, DIST_DPTR_PAXIS_G, DIST_DPTR_PO_G, DIST_DPTR_TLB_G, DIST_DPTR_TSTRIDE_G, DIST_DPTR_TUB_G, ENTFTN(), F90_KIND_G, F90_LEN_G, F90_RANK_G, flags, i, kind, len, MAXDIMS, no, rank, s, SET_DIM_PTRS, SET_F90_DIST_DESC_PTR, stride, t, TEMPLATE, and xfer().
__fort_set_alignment()
void I8() __fort_set_alignment (F90_Desc * d, __INT_T dim, __INT_T lbound, __INT_T ubound, __INT_T taxis, __INT_T tstride, __INT_T toffset, ...)
Definition at line 1202 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), __fort_test, d, DEBUG_DIST, DECL_DIM_PTRS, dim, DIST_DPTR_CLB_G, DIST_DPTR_CNO_G, DIST_DPTR_OLB_G, DIST_DPTR_OUB_G, DIST_DPTR_TAXIS_G, DIST_DPTR_TLB_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, DIST_DPTR_TUB_G, DPTR_UBOUND_G, DPTR_UBOUND_P, extent(), F90_DPTR_LBOUND_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_P, F90_DPTR_SOFFSET_P, F90_DPTR_SSTRIDE_P, F90_RANK_G, F90_TAG_G, GET_DIST_LCPU, NULL, and SET_DIM_PTRS.
Referenced by ENTFTN(), ptr_asgn(), and void().
__fort_set_section()
void I8() __fort_set_section (F90_Desc * d, __INT_T ddim, F90_Desc * a, __INT_T adim, __INT_T l, __INT_T u, __INT_T s)
Definition at line 1475 of file runtime/flang/dist.c.
References __DIST_SET_SECTIONX, a, d, and s.
Referenced by __fort_copy(), cshift_loop(), ENTFTN(), and eoshift_scalar().
__fort_set_sectionx()
void I8() __fort_set_sectionx (F90_Desc * d, __INT_T ddim, F90_Desc * a, __INT_T adim, __INT_T l, __INT_T u, __INT_T s, __INT_T noreindex)
Definition at line 1410 of file runtime/flang/dist.c.
References __ASSUMED_SIZE, __BOGUSBOUNDS, __DESC, __fort_abort(), __fort_test, __SEQUENCE, a, d, DEBUG_DIST, DECL_DIM_PTRS, DIST_DPTR_LAB_G, DIST_DPTR_LOFFSET_G, DIST_DPTR_OLB_G, DIST_DPTR_OUB_G, DIST_DPTR_UAB_G, DIST_SCOFF_G, DPTR_UBOUND_G, DPTR_UBOUND_P, extent(), F90_DPTR_LBOUND_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_G, F90_DPTR_LSTRIDE_P, F90_DPTR_SOFFSET_G, F90_DPTR_SOFFSET_P, F90_DPTR_SSTRIDE_G, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_LBASE_G, F90_RANK_G, F90_TAG_G, GET_DIST_LCPU, NULL, s, and SET_DIM_PTRS.
__fort_set_single()
void I8() __fort_set_single (F90_Desc * d, F90_Desc * a, __INT_T dim, __INT_T idx, _set_single_enum what)
Definition at line 1331 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), __fort_test, __OFF_TEMPLATE, __SINGLE, a, d, DEBUG_DIST, DECL_DIM_PTRS, dim, DIST_DPTR_LOFFSET_G, DIST_PBASE_G, DIST_SCOFF_G, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_LBASE_G, F90_LBASE_P, F90_RANK_G, F90_TAG_G, GET_DIST_LCPU, idx, k, NULL, and SET_DIM_PTRS.
Referenced by cshift_loop(), ENTF90(), ENTFTN(), and eoshift_loop().
__fort_use_allocation()
void I8() __fort_use_allocation (F90_Desc * d, __INT_T dim, __INT_T no, __INT_T po, F90_Desc * a)
Definition at line 1245 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), __fort_test, __LOCAL, __TEMPLATE, a, d, DEBUG_DIST, DECL_DIM_PTRS, dim, DIST_DPTR_COFSTR_G, DIST_DPTR_COFSTR_P, DIST_DPTR_LAB_G, DIST_DPTR_LAB_P, DIST_DPTR_NO_G, DIST_DPTR_NO_P, DIST_DPTR_OLB_G, DIST_DPTR_OUB_G, DIST_DPTR_PO_G, DIST_DPTR_PO_P, DIST_DPTR_UAB_G, DIST_DPTR_UAB_P, DIST_NONSEQUENCE_G, DIST_NONSEQUENCE_P, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_FLAGS_P, F90_RANK_G, F90_TAG_G, GET_DIST_LCPU, k, no, NULL, and SET_DIM_PTRS.
Referenced by ptr_asgn().
__INT_T() [1/4]
__INT_T (__INT_T * x, __INT_T * y)
Definition at line 140 of file runtime/flang/dist.c.
References a, b, RECIP_FRACBITS, x, and y.
__INT_T() [2/4]
__INT_T (F90_Desc * d, __INT_T * dimb, __INT_T * idxb)
Definition at line 649 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), d, DECL_DIM_PTRS, dim, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_RANK_G, F90_TAG_G, idx, NULL, and SET_DIM_PTRS.
__INT_T() [3/4]
__INT_T (F90_Desc * d, __INT_T * gdim)
Definition at line 2456 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), d, dim, F90_DIM_EXTENT_G, F90_RANK_G, F90_TAG_G, and NULL.
__INT_T() [4/4]
__INT_T (F90_Desc * d, ...)
Definition at line 237 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), __fort_owner(), d, DIST_DIST_TARGET_G, DIST_REPLICATED_G, F90_RANK_G, F90_TAG_G, I8, MAXDIMS, NULL, p, pd, and va.
__LOG_T() [1/2]
__LOG_T (F90_Desc * d, __INT_T * dimb, __INT_T * idxb)
Definition at line 350 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), d, DECL_DIM_PTRS, dim, F90_RANK_G, F90_TAG_G, GET_DIST_TRUE_LOG, idx, NULL, and SET_DIM_PTRS.
__LOG_T() [2/2]
__LOG_T (F90_Desc * d, ...)
Definition at line 388 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), __fort_islocal(), d, F90_RANK_G, F90_TAG_G, GET_DIST_TRUE_LOG, I8, MAXDIMS, NULL, and va.
_int_mult_upper()
unsigned long _int_mult_upper (int x, int y)
Definition at line 151 of file runtime/flang/dist.c.
References a, b, RECIP_FRACBITS, x, and y.
block_setup()
void I8() block_setup (F90_Desc * d, int dim, __INT_T l, __INT_T u, int s, int ci, __INT_T * bl, __INT_T * bu)
Definition at line 843 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), __fort_test, Ceil, d, DEBUG_DIST, DECL_DIM_PTRS, DFMT, DFMT_BLOCK, DFMT_BLOCK_K, DFMT_COLLAPSED, DFMT_CYCLIC, DFMT_CYCLIC_K, DFMT_GEN_BLOCK, dim, DIST_DPTR_BLOCK_G, DIST_DPTR_OLB_G, DIST_DPTR_OUB_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_RANK_G, F90_TAG_G, Floor, GET_DIST_LCPU, m, n, NULL, s, and SET_DIM_PTRS.
Referenced by __fort_block_bounds(), __fort_block_loop(), and ENTFTN().
cyclic_setup()
static int I8() cyclic_setup (F90_Desc * d, __INT_T dim, __INT_T l, __INT_T u, __INT_T s, __INT_T * pcl, __INT_T * pcs, __INT_T * plof, __INT_T * plos) static
Definition at line 678 of file runtime/flang/dist.c.
References __fort_abort(), __fort_test, cl, cs, d, DEBUG_DIST, DECL_DIM_PTRS, DFMT, dim, DIST_DPTR_CLB_G, DIST_DPTR_CYCLE_G, DIST_DPTR_OLB_G, DIST_DPTR_OUB_G, DIST_DPTR_TSTRIDE_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, GET_DIST_LCPU, n, s, SET_DIM_PTRS, and ts.
Referenced by __fort_cycle_bounds(), and __fort_cyclic_loop().
div_shift()
static int div_shift (int n) static
Definition at line 117 of file runtime/flang/dist.c.
References k, m, n, and z.
Referenced by proc_setup().
ENTF90() [1/7]
void ENTF90 (SECT , sect)
Definition at line 1642 of file runtime/flang/dist.c.
References __BOGUSBOUNDS, __DESC, __DIST_INIT_SECTION, __fort_abort(), __fort_set_single(), __SCALAR, __SECTZBASE, __SEQUENTIAL_SECTION, a, ASECTION, BOGUSFLAG, d, DECL_DIM_PTRS, DPTR_UBOUND_P, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_FLAGS_P, F90_GSIZE_P, F90_KIND_G, F90_LBASE_P, F90_LEN_G, F90_LSIZE_P, F90_RANK_G, F90_TAG_G, flags, GET_DIST_SIZE_OF, I8, lower(), MAXDIMS, NULL, rank, SET_DIM_PTRS, SET_F90_DIST_DESC_PTR, stride, TSECTION, upper(), and va.
ENTF90() [2/7]
void ENTF90 (SECT1 , sect1)
Definition at line 1736 of file runtime/flang/dist.c.
References __BOGUSBOUNDS, __DESC, __DIST_INIT_SECTION, __fort_abort(), __fort_set_single(), __SCALAR, __SECTZBASE, __SEQUENTIAL_SECTION, a, ASECTION, BOGUSFLAG, d, DECL_DIM_PTRS, DPTR_UBOUND_P, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_FLAGS_P, F90_GSIZE_P, F90_LBASE_P, F90_LSIZE_P, F90_RANK_G, F90_TAG_G, flags, I8, lower(), NULL, rank, SET_DIM_PTRS, SET_F90_DIST_DESC_PTR, stride, TSECTION, and upper().
ENTF90() [3/7]
void ENTF90 (SECT1v , sect1v)
Definition at line 1815 of file runtime/flang/dist.c.
References __BOGUSBOUNDS, __DESC, __DIST_INIT_SECTION, __fort_abort(), __fort_set_single(), __SCALAR, __SECTZBASE, __SEQUENTIAL_SECTION, a, ASECTION, BOGUSFLAG, d, DECL_DIM_PTRS, DPTR_UBOUND_P, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_FLAGS_P, F90_GSIZE_P, F90_LBASE_P, F90_LSIZE_P, F90_RANK_G, F90_TAG_G, flags, I8, lower(), NULL, rank, SET_DIM_PTRS, SET_F90_DIST_DESC_PTR, stride, TSECTION, and upper().
ENTF90() [4/7]
void ENTF90 (SECT2 , sect2)
Definition at line 1890 of file runtime/flang/dist.c.
References __BOGUSBOUNDS, __DESC, __DIST_INIT_SECTION, __fort_abort(), __fort_set_single(), __SCALAR, __SECTZBASE, __SEQUENTIAL_SECTION, a, ASECTION, BOGUSFLAG, d, DECL_DIM_PTRS, DPTR_UBOUND_P, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_FLAGS_P, F90_GSIZE_P, F90_LBASE_P, F90_LSIZE_P, F90_RANK_G, F90_TAG_G, flags, I8, lower(), NULL, rank, SET_DIM_PTRS, SET_F90_DIST_DESC_PTR, stride, TSECTION, and upper().
ENTF90() [5/7]
void ENTF90 (SECT2v , sect2v)
Definition at line 1975 of file runtime/flang/dist.c.
References __BOGUSBOUNDS, __DESC, __DIST_INIT_SECTION, __fort_abort(), __fort_set_single(), __SCALAR, __SECTZBASE, __SEQUENTIAL_SECTION, a, ASECTION, BOGUSFLAG, d, DECL_DIM_PTRS, DPTR_UBOUND_P, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_FLAGS_P, F90_GSIZE_P, F90_LBASE_P, F90_LSIZE_P, F90_RANK_G, F90_TAG_G, flags, I8, lower(), NULL, rank, SET_DIM_PTRS, SET_F90_DIST_DESC_PTR, stride, TSECTION, and upper().
ENTF90() [6/7]
void ENTF90 (SECT3 , sect3)
Definition at line 2055 of file runtime/flang/dist.c.
References __BOGUSBOUNDS, __DESC, __DIST_INIT_SECTION, __fort_abort(), __fort_set_single(), __SCALAR, __SECTZBASE, __SEQUENTIAL_SECTION, a, ASECTION, BOGUSFLAG, d, DECL_DIM_PTRS, DPTR_UBOUND_P, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_FLAGS_P, F90_GSIZE_P, F90_LBASE_P, F90_LSIZE_P, F90_RANK_G, F90_TAG_G, flags, I8, lower(), MAXDIMS, NULL, rank, SET_DIM_PTRS, SET_F90_DIST_DESC_PTR, stride, TSECTION, and upper().
ENTF90() [7/7]
void ENTF90 (SECT3v , sect3v)
Definition at line 2147 of file runtime/flang/dist.c.
References __BOGUSBOUNDS, __DESC, __DIST_INIT_SECTION, __fort_abort(), __fort_set_single(), __SCALAR, __SECTZBASE, __SEQUENTIAL_SECTION, a, ASECTION, BOGUSFLAG, d, DECL_DIM_PTRS, DPTR_UBOUND_P, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_FLAGS_P, F90_GSIZE_P, F90_LBASE_P, F90_LSIZE_P, F90_RANK_G, F90_TAG_G, flags, I8, lower(), NULL, rank, SET_DIM_PTRS, SET_F90_DIST_DESC_PTR, stride, TSECTION, and upper().
ENTFTN() [1/41]
void ENTFTN (BLOCK_LOOP , block_loop)
Definition at line 930 of file runtime/flang/dist.c.
References block_setup(), d, dim, I8, and s.
ENTFTN() [2/41]
void * ENTFTN (COMM_START , comm_start)
Definition at line 17 of file runtime/flang/dist.c.
References f90DummyGenBlock.
Referenced by __fort_reverse_array().
ENTFTN() [3/41]
void ENTFTN (CYCLIC_LOOP , cyclic_loop)
Definition at line 821 of file runtime/flang/dist.c.
References __fort_cyclic_loop(), cl, cs, d, dim, I8, s, and void().
ENTFTN() [4/41]
__INT8_T ENTFTN (KLBOUND , klbound)
Definition at line 2544 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, ISPRESENT, and pd.
ENTFTN() [5/41]
void ENTFTN (KLBOUNDA , klbounda)
Definition at line 2687 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [6/41]
void ENTFTN (KLBOUNDAZ , klboundaz)
Definition at line 2698 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [7/41]
void ENTFTN (KSHAPE , kshape)
Definition at line 2903 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_EXTENT_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [8/41]
__INT8_T ENTFTN (KSIZE , ksize)
Definition at line 2866 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_EXTENT_G, F90_GSIZE_G, F90_RANK_G, F90_TAG_G, ISPRESENT, pd, and size.
ENTFTN() [9/41]
__INT8_T ENTFTN (KUBOUND , kubound)
Definition at line 2566 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, DIM_UBOUND_G, F90_RANK_G, F90_TAG_G, ISPRESENT, and pd.
ENTFTN() [10/41]
void ENTFTN (KUBOUNDA , kubounda)
Definition at line 2821 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, DIM_UBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [11/41]
void ENTFTN (KUBOUNDAZ , kuboundaz)
Definition at line 2832 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, DIM_UBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [12/41]
__INT_T ENTFTN (LBOUND , lbound)
Definition at line 2534 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, ISPRESENT, and pd.
ENTFTN() [13/41]
void ENTFTN (LBOUNDA , lbounda)
Definition at line 2577 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [14/41]
void ENTFTN (LBOUNDA1 , lbounda1)
Definition at line 2588 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [15/41]
void ENTFTN (LBOUNDA2 , lbounda2)
Definition at line 2599 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [16/41]
void ENTFTN (LBOUNDA4 , lbounda4)
Definition at line 2610 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [17/41]
void ENTFTN (LBOUNDA8 , lbounda8)
Definition at line 2621 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [18/41]
void ENTFTN (LBOUNDAZ , lboundaz)
Definition at line 2632 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [19/41]
void ENTFTN (LBOUNDAZ1 , lboundaz1)
Definition at line 2643 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [20/41]
void ENTFTN (LBOUNDAZ2 , lboundaz2)
Definition at line 2654 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [21/41]
void ENTFTN (LBOUNDAZ4 , lboundaz4)
Definition at line 2665 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [22/41]
void ENTFTN (LBOUNDAZ8 , lboundaz8)
Definition at line 2676 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [23/41]
void ENTFTN (LOCALIZE_BOUNDS , localize_bounds)
Definition at line 975 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), d, DECL_DIM_PTRS, dim, DIST_DPTR_OLB_G, DIST_DPTR_OUB_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_RANK_G, F90_TAG_G, m, n, NULL, s, and SET_DIM_PTRS.
ENTFTN() [24/41]
void ENTFTN (LOCALIZE_DIM , localize_dim)
Definition at line 496 of file runtime/flang/dist.c.
References __fort_abort(), Ceil, d, DECL_DIM_PTRS, DFMT, DFMT_COLLAPSED, dim, DIST_DPTR_AOFFSET_G, DIST_DPTR_ASTRIDE_G, DIST_DPTR_BLOCK_G, DIST_DPTR_CLB_G, DIST_DPTR_CYCLE_G, DIST_DPTR_GEN_BLOCK_G, DIST_DPTR_LAB_G, DIST_DPTR_NO_G, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, idx, and SET_DIM_PTRS.
ENTFTN() [25/41]
void ENTFTN (PROCESSORS , processors)
Definition at line 1072 of file runtime/flang/dist.c.
References __fort_abort(), __PROC, i, MAXDIMS, p, pd, proc_setup(), rank, and va.
ENTFTN() [26/41]
void ENTFTN (SECT , sect)
Definition at line 1508 of file runtime/flang/dist.c.
References __BOGUSBOUNDS, __DESC, __DIST_INIT_SECTION, __DIST_SET_SECTIONXX, __fort_abort(), __fort_set_single(), __NOREINDEX, __SCALAR, __SEQUENTIAL_SECTION, a, BOGUSFLAG, d, DECL_DIM_PTRS, DPTR_UBOUND_P, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_FLAGS_P, F90_GSIZE_P, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, flags, GET_DIST_SIZE_OF, I8, lower(), MAXDIMS, NULL, rank, SET_DIM_PTRS, SET_F90_DIST_DESC_PTR, stride, upper(), and va.
ENTFTN() [27/41]
void ENTFTN (SECT3 , sect3)
Definition at line 2246 of file runtime/flang/dist.c.
References __BOGUSBOUNDS, __DESC, __DIST_INIT_SECTION, __fort_abort(), __fort_set_single(), __SCALAR, __SEQUENTIAL_SECTION, a, BOGUSFLAG, BSECTION, d, DECL_DIM_PTRS, DPTR_UBOUND_P, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_FLAGS_P, F90_GSIZE_P, F90_RANK_G, F90_TAG_G, flags, I8, lower(), MAXDIMS, NULL, rank, SET_DIM_PTRS, SET_F90_DIST_DESC_PTR, stride, and upper().
ENTFTN() [28/41]
void ENTFTN (SECT3v , sect3v)
Definition at line 2329 of file runtime/flang/dist.c.
References __BOGUSBOUNDS, __DESC, __DIST_INIT_SECTION, __fort_abort(), __fort_set_single(), __SCALAR, __SEQUENTIAL_SECTION, a, BOGUSFLAG, BSECTION, d, DECL_DIM_PTRS, DPTR_UBOUND_P, F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_P, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, F90_DPTR_SSTRIDE_P, F90_FLAGS_G, F90_FLAGS_P, F90_GSIZE_P, F90_RANK_G, F90_TAG_G, flags, I8, lower(), NULL, rank, SET_DIM_PTRS, SET_F90_DIST_DESC_PTR, stride, and upper().
ENTFTN() [29/41]
void ENTFTN (SHAPE , shape)
Definition at line 2889 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), DECL_DIM_PTRS, dim, F90_DIM_EXTENT_G, F90_RANK_G, F90_TAG_G, pd, rank, and SET_DIM_PTRS.
ENTFTN() [30/41]
__INT_T ENTFTN (SIZE , size)
Definition at line 2848 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_EXTENT_G, F90_GSIZE_G, F90_RANK_G, F90_TAG_G, ISPRESENT, pd, and size.
ENTFTN() [31/41]
__INT_T ENTFTN (UBOUND , ubound)
Definition at line 2556 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, DIM_UBOUND_G, F90_RANK_G, F90_TAG_G, ISPRESENT, and pd.
ENTFTN() [32/41]
void ENTFTN (UBOUNDA , ubounda)
Definition at line 2711 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, DIM_UBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [33/41]
void ENTFTN (UBOUNDA1 , ubounda1)
Definition at line 2722 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_UBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [34/41]
void ENTFTN (UBOUNDA2 , ubounda2)
Definition at line 2733 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_UBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [35/41]
void ENTFTN (UBOUNDA4 , ubounda4)
Definition at line 2744 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_UBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [36/41]
void ENTFTN (UBOUNDA8 , ubounda8)
Definition at line 2755 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_UBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [37/41]
void ENTFTN (UBOUNDAZ , uboundaz)
Definition at line 2766 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, DIM_UBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [38/41]
void ENTFTN (UBOUNDAZ1 , uboundaz1)
Definition at line 2777 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_UBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [39/41]
void ENTFTN (UBOUNDAZ2 , uboundaz2)
Definition at line 2788 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_UBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [40/41]
void ENTFTN (UBOUNDAZ4 , uboundaz4)
Definition at line 2799 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_UBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
ENTFTN() [41/41]
void ENTFTN (UBOUNDAZ8 , uboundaz8)
Definition at line 2810 of file runtime/flang/dist.c.
References __DESC, __fort_abort(), dim, F90_DIM_UBOUND_G, F90_RANK_G, F90_TAG_G, pd, and rank.
proc_setup()
static void proc_setup (proc * p) static
Definition at line 1037 of file runtime/flang/dist.c.
References __fort_abort(), __OFF_TEMPLATE, div_shift(), GET_DIST_LCPU, GET_DIST_TCPUS, i, m, msg(), p, pd, RECIP, RECIP_DIVMOD, and size.
Referenced by __fort_defaultproc(), __fort_localproc(), and ENTFTN().
Variable Documentation
default_proc_list
proc* default_proc_list[MAXDIMS+1] = {NULL} static
Definition at line 1105 of file runtime/flang/dist.c.
Referenced by __fort_defaultproc().
local_proc
proc* local_proc static
Definition at line 1184 of file runtime/flang/dist.c.
Referenced by __fort_localproc().
prime
int prime[NPRIMES] static
Initial value:
= {2,  3,  5,  7,   11,  13,  17,  19,  23, 29, 31,
                             37, 41, 43, 47,  53,  59,  61,  67,  71, 73, 79,
                             83, 89, 97, 101, 103, 107, 109, 113, 127}
Definition at line 1108 of file runtime/flang/dist.c.
Referenced by __fort_defaultproc().