flang: feddesc.h File Reference
runtime/flang/feddesc.h File Reference
Definitions for FORTRAN edit descriptor symbolics.
Macros
#define FED_END -1
#define FED_LPAREN -2
#define FED_RPAREN -3
#define FED_P -4
#define FED_STR -5
#define FED_T -6
#define FED_TL -7
#define FED_TR -8
#define FED_X -9
#define FED_S -10
#define FED_SP -11
#define FED_SS -12
#define FED_BN -13
#define FED_BZ -14
#define FED_SLASH -15
#define FED_COLON -16
#define FED_Q -17
#define FED_DOLLAR -18
#define FED_Aw -19
#define FED_Lw -20
#define FED_Iw_m -21
#define FED_Fw_d -22
#define FED_Ee -23
#define FED_Ew_d -24
#define FED_ENw_d -25
#define FED_ESw_d -26
#define FED_Gw_d -27
#define FED_Dw_d -28
#define FED_Ow_m -29
#define FED_Zw_m -30
#define FED_A -31
#define FED_L -32
#define FED_I -33
#define FED_F -34
#define FED_E -35
#define FED_G -36
#define FED_D -37
#define FED_O -38
#define FED_Z -39
#define FED_KANJI_STRING -40
#define FED_Nw -41
#define FED_N -42
#define FED_Bw_m -43
#define FED_ERROR -44
#define FED_DC -45
#define FED_DP -46
#define FED_RU -47
#define FED_RD -48
#define FED_RZ -49
#define FED_RN -50
#define FED_RC -51
#define FED_RP -52
#define FED_DT -53
#define FED_G0 -54
#define FED_G0_d -55
Functions
void get_vlist_desc (F90_Desc *sd, __INT_T ubnd)
void get_vlist_desc_i8 (F90_Desc *sd, __INT_T ubnd)
Detailed Description
Definitions for FORTRAN edit descriptor symbolics.
If contents are changed, changes must also be applied to the run-time document file (fio.n) and this file must copied to the io source rte directory.
Definition in file runtime/flang/feddesc.h.
Macro Definition Documentation
FED_A
#define FED_A -31
Definition at line 46 of file runtime/flang/feddesc.h.
FED_Aw
#define FED_Aw -19
Definition at line 34 of file runtime/flang/feddesc.h.
FED_BN
#define FED_BN -13
Definition at line 28 of file runtime/flang/feddesc.h.
FED_Bw_m
#define FED_Bw_m -43
Definition at line 58 of file runtime/flang/feddesc.h.
FED_BZ
#define FED_BZ -14
Definition at line 29 of file runtime/flang/feddesc.h.
FED_COLON
#define FED_COLON -16
Definition at line 31 of file runtime/flang/feddesc.h.
FED_D
#define FED_D -37
Definition at line 52 of file runtime/flang/feddesc.h.
FED_DC
#define FED_DC -45
Definition at line 60 of file runtime/flang/feddesc.h.
FED_DOLLAR
#define FED_DOLLAR -18
Definition at line 33 of file runtime/flang/feddesc.h.
FED_DP
#define FED_DP -46
Definition at line 61 of file runtime/flang/feddesc.h.
FED_DT
#define FED_DT -53
Definition at line 68 of file runtime/flang/feddesc.h.
FED_Dw_d
#define FED_Dw_d -28
Definition at line 43 of file runtime/flang/feddesc.h.
FED_E
#define FED_E -35
Definition at line 50 of file runtime/flang/feddesc.h.
FED_Ee
#define FED_Ee -23
Definition at line 38 of file runtime/flang/feddesc.h.
FED_END
#define FED_END -1
Definition at line 16 of file runtime/flang/feddesc.h.
FED_ENw_d
#define FED_ENw_d -25
Definition at line 40 of file runtime/flang/feddesc.h.
FED_ERROR
#define FED_ERROR -44
Definition at line 59 of file runtime/flang/feddesc.h.
FED_ESw_d
#define FED_ESw_d -26
Definition at line 41 of file runtime/flang/feddesc.h.
FED_Ew_d
#define FED_Ew_d -24
Definition at line 39 of file runtime/flang/feddesc.h.
FED_F
#define FED_F -34
Definition at line 49 of file runtime/flang/feddesc.h.
FED_Fw_d
#define FED_Fw_d -22
Definition at line 37 of file runtime/flang/feddesc.h.
FED_G
#define FED_G -36
Definition at line 51 of file runtime/flang/feddesc.h.
FED_G0
#define FED_G0 -54
Definition at line 69 of file runtime/flang/feddesc.h.
FED_G0_d
#define FED_G0_d -55
Definition at line 70 of file runtime/flang/feddesc.h.
FED_Gw_d
#define FED_Gw_d -27
Definition at line 42 of file runtime/flang/feddesc.h.
FED_I
#define FED_I -33
Definition at line 48 of file runtime/flang/feddesc.h.
FED_Iw_m
#define FED_Iw_m -21
Definition at line 36 of file runtime/flang/feddesc.h.
FED_KANJI_STRING
#define FED_KANJI_STRING -40
Definition at line 55 of file runtime/flang/feddesc.h.
FED_L
#define FED_L -32
Definition at line 47 of file runtime/flang/feddesc.h.
FED_LPAREN
#define FED_LPAREN -2
Definition at line 17 of file runtime/flang/feddesc.h.
FED_Lw
#define FED_Lw -20
Definition at line 35 of file runtime/flang/feddesc.h.
FED_N
#define FED_N -42
Definition at line 57 of file runtime/flang/feddesc.h.
FED_Nw
#define FED_Nw -41
Definition at line 56 of file runtime/flang/feddesc.h.
FED_O
#define FED_O -38
Definition at line 53 of file runtime/flang/feddesc.h.
FED_Ow_m
#define FED_Ow_m -29
Definition at line 44 of file runtime/flang/feddesc.h.
FED_P
#define FED_P -4
Definition at line 19 of file runtime/flang/feddesc.h.
FED_Q
#define FED_Q -17
Definition at line 32 of file runtime/flang/feddesc.h.
FED_RC
#define FED_RC -51
Definition at line 66 of file runtime/flang/feddesc.h.
FED_RD
#define FED_RD -48
Definition at line 63 of file runtime/flang/feddesc.h.
FED_RN
#define FED_RN -50
Definition at line 65 of file runtime/flang/feddesc.h.
FED_RP
#define FED_RP -52
Definition at line 67 of file runtime/flang/feddesc.h.
FED_RPAREN
#define FED_RPAREN -3
Definition at line 18 of file runtime/flang/feddesc.h.
FED_RU
#define FED_RU -47
Definition at line 62 of file runtime/flang/feddesc.h.
FED_RZ
#define FED_RZ -49
Definition at line 64 of file runtime/flang/feddesc.h.
FED_S
#define FED_S -10
Definition at line 25 of file runtime/flang/feddesc.h.
FED_SLASH
#define FED_SLASH -15
Definition at line 30 of file runtime/flang/feddesc.h.
FED_SP
#define FED_SP -11
Definition at line 26 of file runtime/flang/feddesc.h.
FED_SS
#define FED_SS -12
Definition at line 27 of file runtime/flang/feddesc.h.
FED_STR
#define FED_STR -5
Definition at line 20 of file runtime/flang/feddesc.h.
FED_T
#define FED_T -6
Definition at line 21 of file runtime/flang/feddesc.h.
FED_TL
#define FED_TL -7
Definition at line 22 of file runtime/flang/feddesc.h.
FED_TR
#define FED_TR -8
Definition at line 23 of file runtime/flang/feddesc.h.
FED_X
#define FED_X -9
Definition at line 24 of file runtime/flang/feddesc.h.
FED_Z
#define FED_Z -39
Definition at line 54 of file runtime/flang/feddesc.h.
FED_Zw_m
#define FED_Zw_m -30
Definition at line 45 of file runtime/flang/feddesc.h.
Function Documentation
get_vlist_desc()
void get_vlist_desc (F90_Desc * sd, __INT_T ubnd)
Definition at line 105 of file desc.c.
References __DIST_INIT_DESCRIPTOR, __INT4, __INT8, __NONE, F90_GSIZE_P, F90_KIND_P(), F90_LBASE_P, F90_LEN_P, F90_LSIZE_P, flags, lbase, NULL, rank, TEMPLATE, and type.
Referenced by ENTF90IO().
get_vlist_desc_i8()
void get_vlist_desc_i8 (F90_Desc * sd, __INT_T ubnd)
Referenced by ENTF90IO().