flang: comm.c File Reference
runtime/flang/comm.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "fort_vars.h"
Classes
struct comm_sked
Functions
static void I8() comm_sked_start (comm_sked *sk, char *rb, char *sb, F90_Desc *rd, F90_Desc *sd)
static void comm_sked_free (comm_sked *sk)
sked *I8() __fort_comm_sked (chdr *ch, char *rb, char *sb, dtype kind, int len)
void * ENTFTN (COMM_START, comm_start)
void ENTFTN (COMM_FINISH, comm_finish)
void ENTFTN (COMM_EXECUTE, comm_execute)
void ENTFTN (COMM_FREE, comm_free)
Function Documentation
__fort_comm_sked()
sked *I8() __fort_comm_sked (chdr * ch, char * rb, char * sb, dtype kind, int len)
Definition at line 50 of file runtime/flang/comm.c.
References __fort_malloc(), __fort_setbase(), __SKED, sked::arg, comm_sked::channel, comm_sked_free(), comm_sked_start(), sked::free, I8, kind, len, rb, sb, comm_sked::sked, sked::start, and sked::tag.
Referenced by ENTFTN().
comm_sked_free()
static void comm_sked_free (comm_sked * sk) static
Definition at line 42 of file runtime/flang/comm.c.
References __fort_frechn(), __fort_free(), and comm_sked::channel.
Referenced by __fort_comm_sked().
comm_sked_start()
static void I8() comm_sked_start (comm_sked * sk, char * rb, char * sb, F90_Desc * rd, F90_Desc * sd) static
Definition at line 26 of file runtime/flang/comm.c.
References __fort_abort(), __fort_adjbase(), __fort_doit(), DIST_SCOFF_G, F90_KIND_G, F90_LEN_G, rb, and sb.
Referenced by __fort_comm_sked().
ENTFTN() [1/4]
void ENTFTN (COMM_EXECUTE , comm_execute)
Definition at line 83 of file runtime/flang/comm.c.
References __fort_abort(), __SKED, sked::arg, F90_TAG_G, GET_DIST_SIZE_OF, ISSCALAR, NULL, rb, sb, sked::start, and sked::tag.
ENTFTN() [2/4]
void ENTFTN (COMM_FINISH , comm_finish)
Definition at line 79 of file runtime/flang/comm.c.
ENTFTN() [3/4]
void ENTFTN (COMM_FREE , comm_free)
Definition at line 101 of file runtime/flang/comm.c.
References __fort_abort(), __SKED, sked::arg, sked::free, n, NULL, sked::tag, and va.
ENTFTN() [4/4]
void * ENTFTN (COMM_START , comm_start)
Definition at line 64 of file runtime/flang/comm.c.
References __fort_abort(), __SKED, sked::arg, NULL, rb, sb, sked::start, and sked::tag.