flang: global.h File Reference
runtime/flang/global.h File Reference
Global definitions and declarations for Fortran I/O library.
#include "universal.h"
#include "fioMacros.h"
#include "stdioInterf.h"
#include "cnfg.h"
#include <stdint.h>
#include "fio_fcb_flags.h"
#include <errno.h>
Classes
struct fcb
struct atag
struct FIO_TBL
Macros
#define GBL_SIZE_T_FORMAT "zu"
#define I64_MSH(t) t[1]
#define I64_LSH(t) t[0]
#define LOCAL_DEBUG 0
#define VOID void
#define ISDIGIT(c) ((c) >= '0' && (c) <= '9')
#define FWRITE __io_fwrite
#define TRUE 1
#define FALSE 0
#define FTN_TRUE GET_FIO_CNFG_FTN_TRUE
#define FTN_FALSE 0
#define assert(ex)
#define STASH(str) (strcpy((char *)malloc(strlen(str) + 1), str))
#define ERR_FLAG 1
#define EOF_FLAG 2
#define EOR_FLAG 3
#define FIO_BITV_NONE 0x00
#define FIO_BITV_IOSTAT 0x01
#define FIO_BITV_ERR 0x02
#define FIO_BITV_EOF 0x04
#define FIO_BITV_EOR 0x08
#define FIO_BITV_IOMSG 0x10
#define FIO_STAT_INTERNAL_UNIT
#define MAX_NAMELEN 255
#define FIO_ERROR_OFFSET 200 /* smallest error value */
#define FIO_ESPEC 201
#define FIO_ECOMPAT 202
#define FIO_ERECLEN 203
#define FIO_EREADONLY 204
#define FIO_EDISPOSE 205
#define FIO_ESCRATCH 206
#define FIO_EOPENED 207
#define FIO_EEXIST 208
#define FIO_ENOEXIST 209
#define FIO_ENOMEM 210
#define FIO_ENAME 211
#define FIO_EUNIT 212
#define FIO_ERECL 213
#define FIO_EWRITEONLY 214
#define FIO_EFORM 215
#define FIO_EEOF 217
#define FIO_EEOR 218
#define FIO_ETOOBIG 219
#define FIO_ETOOFAR 220
#define FIO_EFSYNTAX 221
#define FIO_EPAREN 222
#define FIO_EPT 223
#define FIO_ESTRING 224
#define FIO_ELEX 225
#define FIO_ELETTER 226
#define FIO_ENOGROUP 228
#define FIO_ENMLEOF 229
#define FIO_ESCALEF 230
#define FIO_EERR_DATA_CONVERSION 231
#define FIO_ETOOM 233
#define FIO_EEDITDSCR 234
#define FIO_EMISMATCH 235
#define FIO_EBIGREC 236
#define FIO_EQUAD 237
#define FIO_ETAB_VALUE_OUT_OF_RANGE 238
#define FIO_ENOTMEM 239
#define FIO_ELPAREN 240
#define FIO_EENDFMT 241
#define FIO_EDIRECT 242
#define FIO_EPNEST 243
#define FIO_ENONAME 244
#define FIO_ESYNTAX 245
#define FIO_EINFINITE_REVERSION 246
#define FIO_ESUBSC 248
#define FIO_EFGD 249
#define FIO_EDOT 250
#define FIO_ECHAR 251
#define FIO_EEOFERR 252
#define FIO_EDREAD 253
#define FIO_EREPCNT 254
#define FIO_EASYNC 255
#define FIO_EPOS 256
#define FIO_EPOSV 257
#define FIO_ENEWUNIT 258
#define FIRST_NEWUNIT -13 /* newunits are less than or equal to this */
#define ILLEGAL_UNIT(u) ((u) < 0 && ((u) > FIRST_NEWUNIT || (u) <= next_newunit))
#define GET_FIO_FCBS fioFcbTbls.fcbs
#define FIO_TYPE_SIZE(i) (1 << GET_DIST_SHIFTS(i))
#define __fortio_strtod(x, y) strtod(x, y)
#define __fortio_strtold(x, y) strtold(x, y)
#define EOR_CRLF __fortio_eor_crlf()
#define DIST_STATUS_BCST(s) (s)
#define DIST_RBCSTL(a1, a2, a3, a4, a5, a6)
#define DIST_RBCST(a1, a2, a3, a4, a5)
Typedefs
typedef int DBLINT64[2]
typedef unsigned int DBLUINT64[2]
typedef unsigned short WCHAR
typedef int32_t INT
typedef uint32_t UINT
typedef int bool
typedef char sbool
typedef struct fcb FIO_FCB
typedef struct atag AVAL
Functions
int __fort_getpid ()
__INT_T __fort_time (void)
int __fortio_assign (char *, int, __CLEN_T, AVAL *)
__fortio_assign - store a value found during list-directed or namelist read. return 0 if successful, otherwise an error code (typically, a conversion error).
char * __fortio_ecvt (__BIGREAL_T, int, int, int *, int *, int, int)
char * __fortio_fcvt (__BIGREAL_T, int, int, int, int *, int *, int, int)
WIN_MSVCRT_IMP double WIN_CDECL strtod (const char *, char **)
WIN_MSVCRT_IMP long double WIN_CDECL strtold (const char *, char **)
VOID set_gbl_newunit (bool newunit)
bool get_gbl_newunit ()
VOID __fortio_errinit (__INT_T, __INT_T, __INT_T *, const char *)
VOID __fortio_errinit03 (__INT_T unit, __INT_T bitv, __INT_T *iostat, const char *str)
VOID __fortio_errend (void)
VOID __fortio_errend03 (void)
int f90_old_huge_rec_fmt (void)
int __fortio_error (int)
int __fortio_eoferr (int)
int __fortio_eorerr (int)
end-of-record error when a nonadvancing read
const char * __fortio_errmsg (int)
int __fortio_check_format (void)
int __fortio_eor_crlf (void)
VOID __fortio_fmtinit (void)
VOID __fortio_fmtend (void)
int __fortio_no_minus_zero (void)
int __fortio_new_fp_formatter (void)
VOID __fort_status_init (__INT_T *, __INT_T *)
void __fortio_stat_init (__INT_T *bitv, __INT_T *iostat)
int __fortio_stat_bcst (int *stat)
FIO_FCB * __fortio_alloc_fcb (void)
VOID __fortio_free_fcb (FIO_FCB *)
VOID __fortio_cleanup_fcb (void)
FIO_FCB * __fortio_rwinit (int, int, __INT_T *, int)
FIO_FCB * __fortio_find_unit (int)
int __fortio_zeropad (FILE *, long)
bool __fortio_eq_str (char *, __CLEN_T, const char *)
void * __fortio_fiofcb_asyptr (FIO_FCB *)
bool __fortio_fiofcb_asy_rw (FIO_FCB *)
void __fortio_set_asy_rw (FIO_FCB *, bool)
bool __fortio_fiofcb_stdunit (FIO_FCB *)
FILE * __fortio_fiofcb_fp (FIO_FCB *)
short __fortio_fiofcb_form (FIO_FCB *)
const char * __fortio_fiofcb_name (FIO_FCB *)
void * __fortio_fiofcb_next (FIO_FCB *)
bool __fio_eq_str (char *str, int len, char *pattern)
VOID __fortio_swap_bytes (char *, int, long)
Variables
int __ftn_32in64_
FIO_TBL fioFcbTbls
int next_newunit
char * envar_fortranopt
Detailed Description
Global definitions and declarations for Fortran I/O library.
Definition in file runtime/flang/global.h.
Macro Definition Documentation
__fortio_strtod
#define __fortio_strtod (x, y) strtod(x, y)
Definition at line 349 of file runtime/flang/global.h.
__fortio_strtold
#define __fortio_strtold (x, y) strtold(x, y)
Definition at line 350 of file runtime/flang/global.h.
assert
#define assert (ex)
Definition at line 83 of file runtime/flang/global.h.
DIST_RBCST
#define DIST_RBCST (a1, a2, a3, a4, a5)
Definition at line 379 of file runtime/flang/global.h.
DIST_RBCSTL
#define DIST_RBCSTL (a1, a2, a3, a4, a5, a6)
Definition at line 378 of file runtime/flang/global.h.
DIST_STATUS_BCST
#define DIST_STATUS_BCST (s) (s)
Definition at line 377 of file runtime/flang/global.h.
EOF_FLAG
#define EOF_FLAG 2
Definition at line 91 of file runtime/flang/global.h.
EOR_CRLF
#define EOR_CRLF __fortio_eor_crlf()
Definition at line 369 of file runtime/flang/global.h.
EOR_FLAG
#define EOR_FLAG 3
Definition at line 92 of file runtime/flang/global.h.
ERR_FLAG
#define ERR_FLAG 1
Definition at line 90 of file runtime/flang/global.h.
FALSE
#define FALSE 0
Definition at line 65 of file runtime/flang/global.h.
FIO_BITV_EOF
#define FIO_BITV_EOF 0x04
Definition at line 97 of file runtime/flang/global.h.
FIO_BITV_EOR
#define FIO_BITV_EOR 0x08
Definition at line 98 of file runtime/flang/global.h.
FIO_BITV_ERR
#define FIO_BITV_ERR 0x02
Definition at line 96 of file runtime/flang/global.h.
FIO_BITV_IOMSG
#define FIO_BITV_IOMSG 0x10
Definition at line 99 of file runtime/flang/global.h.
FIO_BITV_IOSTAT
#define FIO_BITV_IOSTAT 0x01
Definition at line 95 of file runtime/flang/global.h.
FIO_BITV_NONE
#define FIO_BITV_NONE 0x00
Definition at line 94 of file runtime/flang/global.h.
FIO_EASYNC
#define FIO_EASYNC 255
Definition at line 170 of file runtime/flang/global.h.
FIO_EBIGREC
#define FIO_EBIGREC 236
Definition at line 151 of file runtime/flang/global.h.
FIO_ECHAR
#define FIO_ECHAR 251
Definition at line 166 of file runtime/flang/global.h.
FIO_ECOMPAT
#define FIO_ECOMPAT 202
Definition at line 117 of file runtime/flang/global.h.
FIO_EDIRECT
#define FIO_EDIRECT 242
Definition at line 157 of file runtime/flang/global.h.
FIO_EDISPOSE
#define FIO_EDISPOSE 205
Definition at line 120 of file runtime/flang/global.h.
FIO_EDOT
#define FIO_EDOT 250
Definition at line 165 of file runtime/flang/global.h.
FIO_EDREAD
#define FIO_EDREAD 253
Definition at line 168 of file runtime/flang/global.h.
FIO_EEDITDSCR
#define FIO_EEDITDSCR 234
Definition at line 149 of file runtime/flang/global.h.
FIO_EENDFMT
#define FIO_EENDFMT 241
Definition at line 156 of file runtime/flang/global.h.
FIO_EEOF
#define FIO_EEOF 217
Definition at line 132 of file runtime/flang/global.h.
FIO_EEOFERR
#define FIO_EEOFERR 252
Definition at line 167 of file runtime/flang/global.h.
FIO_EEOR
#define FIO_EEOR 218
Definition at line 133 of file runtime/flang/global.h.
FIO_EERR_DATA_CONVERSION
#define FIO_EERR_DATA_CONVERSION 231
Definition at line 146 of file runtime/flang/global.h.
FIO_EEXIST
#define FIO_EEXIST 208
Definition at line 123 of file runtime/flang/global.h.
FIO_EFGD
#define FIO_EFGD 249
Definition at line 164 of file runtime/flang/global.h.
FIO_EFORM
#define FIO_EFORM 215
Definition at line 130 of file runtime/flang/global.h.
FIO_EFSYNTAX
#define FIO_EFSYNTAX 221
Definition at line 136 of file runtime/flang/global.h.
FIO_EINFINITE_REVERSION
#define FIO_EINFINITE_REVERSION 246
Definition at line 161 of file runtime/flang/global.h.
FIO_ELETTER
#define FIO_ELETTER 226
Definition at line 141 of file runtime/flang/global.h.
FIO_ELEX
#define FIO_ELEX 225
Definition at line 140 of file runtime/flang/global.h.
FIO_ELPAREN
#define FIO_ELPAREN 240
Definition at line 155 of file runtime/flang/global.h.
FIO_EMISMATCH
#define FIO_EMISMATCH 235
Definition at line 150 of file runtime/flang/global.h.
FIO_ENAME
#define FIO_ENAME 211
Definition at line 126 of file runtime/flang/global.h.
FIO_ENEWUNIT
#define FIO_ENEWUNIT 258
Definition at line 173 of file runtime/flang/global.h.
FIO_ENMLEOF
#define FIO_ENMLEOF 229
Definition at line 144 of file runtime/flang/global.h.
FIO_ENOEXIST
#define FIO_ENOEXIST 209
Definition at line 124 of file runtime/flang/global.h.
FIO_ENOGROUP
#define FIO_ENOGROUP 228
Definition at line 143 of file runtime/flang/global.h.
FIO_ENOMEM
#define FIO_ENOMEM 210
Definition at line 125 of file runtime/flang/global.h.
FIO_ENONAME
#define FIO_ENONAME 244
Definition at line 159 of file runtime/flang/global.h.
FIO_ENOTMEM
#define FIO_ENOTMEM 239
Definition at line 154 of file runtime/flang/global.h.
FIO_EOPENED
#define FIO_EOPENED 207
Definition at line 122 of file runtime/flang/global.h.
FIO_EPAREN
#define FIO_EPAREN 222
Definition at line 137 of file runtime/flang/global.h.
FIO_EPNEST
#define FIO_EPNEST 243
Definition at line 158 of file runtime/flang/global.h.
FIO_EPOS
#define FIO_EPOS 256
Definition at line 171 of file runtime/flang/global.h.
FIO_EPOSV
#define FIO_EPOSV 257
Definition at line 172 of file runtime/flang/global.h.
FIO_EPT
#define FIO_EPT 223
Definition at line 138 of file runtime/flang/global.h.
FIO_EQUAD
#define FIO_EQUAD 237
Definition at line 152 of file runtime/flang/global.h.
FIO_EREADONLY
#define FIO_EREADONLY 204
Definition at line 119 of file runtime/flang/global.h.
FIO_ERECL
#define FIO_ERECL 213
Definition at line 128 of file runtime/flang/global.h.
FIO_ERECLEN
#define FIO_ERECLEN 203
Definition at line 118 of file runtime/flang/global.h.
FIO_EREPCNT
#define FIO_EREPCNT 254
Definition at line 169 of file runtime/flang/global.h.
FIO_ERROR_OFFSET
#define FIO_ERROR_OFFSET 200 /* smallest error value */
Definition at line 114 of file runtime/flang/global.h.
FIO_ESCALEF
#define FIO_ESCALEF 230
Definition at line 145 of file runtime/flang/global.h.
FIO_ESCRATCH
#define FIO_ESCRATCH 206
Definition at line 121 of file runtime/flang/global.h.
FIO_ESPEC
#define FIO_ESPEC 201
Definition at line 116 of file runtime/flang/global.h.
FIO_ESTRING
#define FIO_ESTRING 224
Definition at line 139 of file runtime/flang/global.h.
FIO_ESUBSC
#define FIO_ESUBSC 248
Definition at line 163 of file runtime/flang/global.h.
FIO_ESYNTAX
#define FIO_ESYNTAX 245
Definition at line 160 of file runtime/flang/global.h.
FIO_ETAB_VALUE_OUT_OF_RANGE
#define FIO_ETAB_VALUE_OUT_OF_RANGE 238
Definition at line 153 of file runtime/flang/global.h.
FIO_ETOOBIG
#define FIO_ETOOBIG 219
Definition at line 134 of file runtime/flang/global.h.
FIO_ETOOFAR
#define FIO_ETOOFAR 220
Definition at line 135 of file runtime/flang/global.h.
FIO_ETOOM
#define FIO_ETOOM 233
Definition at line 148 of file runtime/flang/global.h.
FIO_EUNIT
#define FIO_EUNIT 212
Definition at line 127 of file runtime/flang/global.h.
FIO_EWRITEONLY
#define FIO_EWRITEONLY 214
Definition at line 129 of file runtime/flang/global.h.
FIO_STAT_INTERNAL_UNIT
#define FIO_STAT_INTERNAL_UNIT
Value:
  99 /* must be kept in sync with \
      * iso_fortran_env.f90:IOSTAT_INQUIRE_INTERNAL_UNIT */
Definition at line 101 of file runtime/flang/global.h.
FIO_TYPE_SIZE
#define FIO_TYPE_SIZE (i) (1 << GET_DIST_SHIFTS(i))
Definition at line 332 of file runtime/flang/global.h.
FIRST_NEWUNIT
#define FIRST_NEWUNIT -13 /* newunits are less than or equal to this */
Definition at line 175 of file runtime/flang/global.h.
FTN_FALSE
#define FTN_FALSE 0
Definition at line 71 of file runtime/flang/global.h.
FTN_TRUE
#define FTN_TRUE GET_FIO_CNFG_FTN_TRUE
Definition at line 70 of file runtime/flang/global.h.
FWRITE
#define FWRITE __io_fwrite
Definition at line 62 of file runtime/flang/global.h.
GBL_SIZE_T_FORMAT
#define GBL_SIZE_T_FORMAT "zu"
Definition at line 21 of file runtime/flang/global.h.
GET_FIO_FCBS
#define GET_FIO_FCBS fioFcbTbls.fcbs
Definition at line 325 of file runtime/flang/global.h.
I64_LSH
#define I64_LSH (t) t[0]
Definition at line 31 of file runtime/flang/global.h.
I64_MSH
#define I64_MSH (t) t[1]
Definition at line 30 of file runtime/flang/global.h.
ILLEGAL_UNIT
#define ILLEGAL_UNIT (u) ((u) < 0 && ((u) > FIRST_NEWUNIT || (u) <= next_newunit))
Definition at line 176 of file runtime/flang/global.h.
ISDIGIT
#define ISDIGIT (c) ((c) >= '0' && (c) <= '9')
Definition at line 54 of file runtime/flang/global.h.
LOCAL_DEBUG
#define LOCAL_DEBUG 0
Definition at line 36 of file runtime/flang/global.h.
MAX_NAMELEN
#define MAX_NAMELEN 255
Definition at line 110 of file runtime/flang/global.h.
STASH
#define STASH (str) (strcpy((char *)malloc(strlen(str) + 1), str))
Definition at line 86 of file runtime/flang/global.h.
TRUE
#define TRUE 1
Definition at line 64 of file runtime/flang/global.h.
VOID
#define VOID void
Definition at line 43 of file runtime/flang/global.h.
Typedef Documentation
AVAL
typedef struct atag AVAL
bool
typedef int bool
Definition at line 66 of file runtime/flang/global.h.
DBLINT64
typedef int DBLINT64[2]
Definition at line 23 of file runtime/flang/global.h.
DBLUINT64
typedef unsigned int DBLUINT64[2]
Definition at line 24 of file runtime/flang/global.h.
FIO_FCB
typedef struct fcb FIO_FCB
INT
typedef int32_t INT
Definition at line 52 of file runtime/flang/global.h.
sbool
typedef char sbool
Definition at line 67 of file runtime/flang/global.h.
UINT
typedef uint32_t UINT
Definition at line 53 of file runtime/flang/global.h.
WCHAR
typedef unsigned short WCHAR
Definition at line 39 of file runtime/flang/global.h.
Function Documentation
__fio_eq_str()
bool __fio_eq_str (char * str, int len, char * pattern)
__fort_getpid()
int __fort_getpid ()
__fort_status_init()
VOID __fort_status_init (__INT_T * bitv, __INT_T * iostat)
Definition at line 59 of file descFioUtil.c.
References bitv, fio_bitv, and fio_iostat.
Referenced by __INT_T(), and ENTF90IO().
__fort_time()
__INT_T __fort_time (void)
Definition at line 17 of file misc.c.
References __CINT, __fort_rbcst(), GET_DIST_IOPROC, LOCAL_MODE, NULL, s, and time().
__fortio_alloc_fcb()
FIO_FCB * __fortio_alloc_fcb (void)
Definition at line 89 of file utils.c.
References assert, CHUNKSZ, fcb_avail, fcb_chunks, FIO_TBL::fcbs, fioFcbTbls, i, malloc(), next, NULL, and p.
Referenced by __fortio_init(), and __fortio_open().
__fortio_assign()
int __fortio_assign (char * item, int type, __CLEN_T item_length, AVAL * valp)
__fortio_assign - store a value found during list-directed or namelist read. return 0 if successful, otherwise an error code (typically, a conversion error).
Definition at line 39 of file assign.c.
References __BIGCPLX, __BIGINT, __BIGLOG, __BIGREAL, __CLEN_T, __CPLX16, __CPLX32, __CPLX8, __ftn_32in64_, __INT1, __INT2, __INT4, __INT8, __LOG1, __LOG2, __LOG4, __LOG8, __NCHAR, __REAL16, __REAL4, __REAL8, __STR, __WORD16, assert, atag::c, atag::cmplx, atag::dtype, FIO_EERR_DATA_CONVERSION, FIO_EQUAD, FLANG_FALLTHROUGH, atag::i, I64_LSH, I64_MSH, atag::i8, len, atag::len, lp, PP_INT1, PP_INT2, PP_INT4, PP_INT8, PP_LOG1, PP_LOG2, PP_LOG4, PP_LOG8, PP_REAL16, PP_REAL4, PP_REAL8, atag::str, to_bigint(), to_bigreal(), to_int8(), to_log8(), type, atag::val, and void().
Referenced by __f90io_ldr(), and assign().
__fortio_check_format()
int __fortio_check_format (void)
Definition at line 1030 of file runtime/flang/error.c.
References check_format.
Referenced by fr_readnum(), and fw_writenum().
__fortio_cleanup_fcb()
VOID __fortio_cleanup_fcb (void)
Definition at line 146 of file utils.c.
References fcb_avail, fcb_chunks, NULL, and p.
Referenced by __fortio_cleanup().
__fortio_ecvt()
char * __fortio_ecvt (__BIGREAL_T lvalue, int width, int ndigit, int * decpt, int * sign, int round, int is_quad)
Definition at line 796 of file flang/fpcvt.c.
References __fenv_fegetround(), ieee::d, ieee::e, EXPONENT_BIAS_D, EXPONENT_BIAS_Q, FIO_COMPATIBLE, FIO_DOWN, FIO_NEAREST, FIO_PROCESSOR_DEFINED, FIO_UP, FIO_ZERO, FP_UNDEFINED_ERROR, ieee::hm, i, idx, INFINITY_STR_LEN, j, ieee::lm, mtherr(), NULL, round(), ieee::s, sign, SUBSCRIPT_2, tmp, ieee::v, value(), and writefmt().
__fortio_eoferr()
int __fortio_eoferr (int errval)
Definition at line 488 of file runtime/flang/error.c.
References __fort_abort(), __fortio_errmsg(), __fortio_find_unit(), __io_fprintf, __io_stderr(), fcb::acc, assert, current_unit, FIO_TBL::eof, EOF_FLAG, fcb::eof_flag, err_str, FIO_BITV_EOF, FIO_BITV_IOMSG, FIO_BITV_IOSTAT, FIO_BITV_NONE, FIO_DIRECT, FIO_ERROR_OFFSET, fioFcbTbls, iobitv, ioerrinfo(), iomsg, iomsgl, iostat_ptr, NULL, and TRUE.
Referenced by __fortio_error(), find_group(), and get_token().
__fortio_eor_crlf()
int __fortio_eor_crlf (void)
Definition at line 1036 of file runtime/flang/error.c.
References crlf.
__fortio_eorerr()
int __fortio_eorerr (int errval)
end-of-record error when a nonadvancing read
Definition at line 537 of file runtime/flang/error.c.
References __fort_abort(), __fortio_errmsg(), __fortio_find_unit(), __io_fprintf, __io_stderr(), fcb::acc, assert, current_unit, EOR_FLAG, err_str, FIO_TBL::error, FIO_BITV_EOR, FIO_BITV_IOSTAT, FIO_BITV_NONE, FIO_DIRECT, FIO_ERROR_OFFSET, fioFcbTbls, iobitv, ioerrinfo(), iostat_ptr, NULL, and TRUE.
Referenced by __fortio_error().
__fortio_eq_str()
bool __fortio_eq_str (char * str, __CLEN_T len, const char * pattern)
Definition at line 474 of file utils.c.
References FALSE, len, NULL, str, and TRUE.
Referenced by __INT_T(), _f90io_close(), _selected_char_kind(), ENTCRF90IO(), ENTF90IO(), f90_open(), fr_init(), and fw_init().
__fortio_errend()
VOID __fortio_errend (void)
__fortio_errend03()
VOID __fortio_errend03 (void)
Definition at line 276 of file runtime/flang/error.c.
References free_gbl(), and restore_gbl().
Referenced by __f90io_fmt_read(), __f90io_ldr(), __f90io_ldw(), __f90io_unf_read(), __f90io_unf_write(), __f90io_usw_read(), __f90io_usw_write(), __INT_T(), ENTCRF90IO(), and ENTF90IO().
__fortio_errinit()
VOID __fortio_errinit (__INT_T unit, __INT_T bitv, __INT_T * iostat, const char * str)
Definition at line 228 of file runtime/flang/error.c.
References __fortio_init(), bitv, current_unit, FIO_TBL::eof, err_str, FIO_TBL::error, FALSE, FIO_TBL::fcbs, FIO_BITV_IOSTAT, fioFcbTbls, FIO_TBL::fname, iobitv, iostat_ptr, NULL, and str.
Referenced by __f90io_usw_init(), and _f90io_ldw_intern_init().
__fortio_errinit03()
VOID __fortio_errinit03 (__INT_T unit, __INT_T bitv, __INT_T * iostat, const char * str)
Definition at line 252 of file runtime/flang/error.c.
References __fortio_init(), bitv, current_unit, FIO_TBL::eof, err_str, FIO_TBL::error, FALSE, FIO_TBL::fcbs, FIO_BITV_IOSTAT, fioFcbTbls, FIO_TBL::fname, iobitv, iostat_ptr, NULL, save_gbl(), and str.
Referenced by __f90io_unf_init(), _f90io_backspace(), _f90io_close(), _f90io_encode_fmt(), _f90io_endfile(), _f90io_ldr_init(), _f90io_ldr_intern_init(), _f90io_ldw_init(), _f90io_nmlr_init(), _f90io_nmlr_intern_init(), _f90io_nmlw_init(), _f90io_nmlw_intern_init(), _f90io_rewind(), ENTF90IO(), f90_open(), fr_init(), fr_intern_init(), fw_init(), fw_intern_init(), and inquire().
__fortio_errmsg()
const char * __fortio_errmsg (int errval)
Definition at line 454 of file runtime/flang/error.c.
References buf, errtxt, FIO_ERROR_OFFSET, getenv(), and kanjitxt.
Referenced by __fortio_eoferr(), __fortio_eorerr(), and __fortio_error().
__fortio_error()
int __fortio_error (int errval)
Definition at line 378 of file runtime/flang/error.c.
References __fort_abort(), __fortio_eoferr(), __fortio_eorerr(), __fortio_errmsg(), __fortio_find_unit(), __io_fprintf, __io_fseek, __io_perror, __io_stderr(), fcb::acc, assert, current_unit, EOR_FLAG, ERR_FLAG, err_str, FIO_TBL::error, FIO_BITV_EOF, FIO_BITV_EOR, FIO_BITV_ERR, FIO_BITV_IOMSG, FIO_BITV_IOSTAT, FIO_BITV_NONE, FIO_DIRECT, FIO_EEOF, FIO_EEOFERR, FIO_EEOR, FIO_ERROR_OFFSET, FIO_ETOOBIG, fioFcbTbls, fcb::fp, iobitv, ioerrinfo(), iomsg, iomsgl, iostat_ptr, fcb::nextrec, and TRUE.
Referenced by __f90io_ldr(), __f90io_ldw(), __f90io_unf_read(), __f90io_unf_write(), __f90io_usw_read(), __f90io_usw_write(), __fortio_close(), __fortio_open(), __fortio_trunc(), __INT_T(), _f90io_backspace(), _f90io_close(), _f90io_endfile(), _f90io_fmtr_end(), _f90io_fmtw_end(), _f90io_ldr_end(), _f90io_ldw_end(), _f90io_nml_write(), _f90io_rewind(), call_format_double(), do_parse(), dtio_write_scalar(), ENTCRF90IO(), ENTF90IO(), f90_open(), find_group(), fr_Breadnum(), fr_get_fmtcode(), fr_init(), fr_intern_init(), fr_move_fwd(), fr_OZreadnum(), fr_read(), fr_readnum(), fw_check_size(), fw_end_nonadvance(), fw_get_fmtcode(), fw_init(), fw_intern_init(), fw_write(), fw_writenum(), get_token(), inquire(), malloc_obuff(), realloc_obuff(), and write_nml_val().
__fortio_fcvt()
char * __fortio_fcvt (__BIGREAL_T lv, int width, int prec, int sf, int * decpt, int * sign, int round, int is_quad)
Definition at line 1186 of file flang/fpcvt.c.
References __fenv_fegetround(), ieee::d, ieee::e, EXPONENT_BIAS_D, EXPONENT_BIAS_Q, FIO_COMPATIBLE, FIO_DOWN, FIO_NEAREST, FIO_PROCESSOR_DEFINED, FIO_UP, FIO_ZERO, ieee::hm, ieee::i, i, idx, INFINITY_STR_LEN, j, ieee::lm, lv, NULL, round(), ieee::s, sign, SUBSCRIPT_2, SUBSCRIPT_3, tmp, ieee::v, and writefmt().
__fortio_find_unit()
FIO_FCB * __fortio_find_unit (int unit)
Definition at line 434 of file utils.c.
References FIO_TBL::fcbs, fioFcbTbls, NULL, and p.
Referenced by __fortio_eoferr(), __fortio_eorerr(), __fortio_error(), __fortio_open(), __fortio_rwinit(), _f90io_backspace(), _f90io_close(), _f90io_rewind(), ENTF90IO(), and inquire().
__fortio_fiofcb_asy_rw()
bool __fortio_fiofcb_asy_rw (FIO_FCB * f)
Definition at line 47 of file utils.c.
References fcb::asy_rw, and f.
__fortio_fiofcb_asyptr()
void * __fortio_fiofcb_asyptr (FIO_FCB * f)
Definition at line 41 of file utils.c.
References fcb::asyptr, and f.
__fortio_fiofcb_form()
short __fortio_fiofcb_form (FIO_FCB * f)
Definition at line 71 of file utils.c.
References f, and fcb::form.
__fortio_fiofcb_fp()
FILE * __fortio_fiofcb_fp (FIO_FCB * f)
Definition at line 65 of file utils.c.
References f, and fcb::fp.
__fortio_fiofcb_name()
const char * __fortio_fiofcb_name (FIO_FCB * f)
Definition at line 77 of file utils.c.
References f, and fcb::name.
__fortio_fiofcb_next()
void * __fortio_fiofcb_next (FIO_FCB * f)
Definition at line 83 of file utils.c.
References f, and fcb::next.
__fortio_fiofcb_stdunit()
bool __fortio_fiofcb_stdunit (FIO_FCB * f)
Definition at line 59 of file utils.c.
References f, and fcb::stdunit.
__fortio_fmtend()
VOID __fortio_fmtend (void)
Definition at line 292 of file runtime/flang/error.c.
References free_fmtgbl(), and restore_fmtgbl().
Referenced by ENTCRF90IO(), and ENTF90IO().
__fortio_fmtinit()
VOID __fortio_fmtinit (void)
Definition at line 284 of file runtime/flang/error.c.
References allocate_new_fmtgbl(), and save_fmtgbl().
Referenced by _f90io_encode_fmt().
__fortio_free_fcb()
VOID __fortio_free_fcb (FIO_FCB * p)
Definition at line 123 of file utils.c.
References assert, fcb_avail, FIO_TBL::fcbs, fioFcbTbls, NULL, p, and q.
Referenced by __fortio_close(), and __fortio_open().
__fortio_new_fp_formatter()
int __fortio_new_fp_formatter (void)
Definition at line 1054 of file runtime/flang/error.c.
References new_fp_formatter.
Referenced by call_format_double().
__fortio_no_minus_zero()
int __fortio_no_minus_zero (void)
Definition at line 1048 of file runtime/flang/error.c.
References no_minus_zero.
Referenced by call_format_double(), conv_e(), conv_en(), conv_es(), and conv_f().
__fortio_rwinit()
FIO_FCB * __fortio_rwinit (int unit, int form, __INT_T * recptr, int optype)
Definition at line 159 of file utils.c.
References __fortio_find_unit(), __fortio_open(), __fortio_trunc(), __fortio_zeropad(), __io_errno(), __io_fseek, __io_ftell, fcb::acc, fcb::action, assert, fcb::asy_rw, fcb::asyptr, fcb::binary, fcb::coherent, fcb::eof_flag, ERR, f, FALSE, fflush(), FIO_ASIS, Fio_asy_disable(), FIO_DIRECT, FIO_ECOMPAT, FIO_EDIRECT, FIO_EDREAD, FIO_EEOFERR, FIO_EFORM, FIO_EPOS, FIO_EPOSV, FIO_EREADONLY, FIO_EWRITEONLY, FIO_FORMATTED, FIO_KEEP, FIO_NONE, FIO_NULL, FIO_OLD, FIO_READ, FIO_READWRITE, FIO_SEQUENTIAL, FIO_STREAM, FIO_UNFORMATTED, FIO_UNKNOWN, FIO_WRITE, FIO_YES, fioFcbTbls, fcb::form, fcb::fp, if(), fcb::ispipe, ISPRESENT, len, fcb::maxrec, fcb::nextrec, NULL, optype(), fcb::partial, FIO_TBL::pos, pos, FIO_TBL::pos_present, fcb::reclen, fcb::skip, TRUE, fcb::truncflag, and void().
Referenced by __f90io_unf_init(), __f90io_usw_init(), _f90io_endfile(), _f90io_ldr_init(), _f90io_ldw_init(), _f90io_nmlr_init(), _f90io_nmlw_init(), fr_init(), and fw_init().
__fortio_set_asy_rw()
void __fortio_set_asy_rw (FIO_FCB * f, bool value)
Definition at line 53 of file utils.c.
References fcb::asy_rw, f, and value().
__fortio_stat_bcst()
int __fortio_stat_bcst (int * stat)
Definition at line 110 of file descFioUtil.c.
References __fort_rbcstl(), __INT, fio_bitv, FIO_BITV_EOF, FIO_BITV_EOR, FIO_BITV_ERR, FIO_BITV_IOSTAT, fio_iostat, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, msg(), and stat.
__fortio_stat_init()
void __fortio_stat_init (__INT_T * bitv, __INT_T * iostat)
Definition at line 101 of file descFioUtil.c.
References bitv, fio_bitv, and fio_iostat.
__fortio_swap_bytes()
VOID __fortio_swap_bytes (char * p, int type, long cnt)
Definition at line 525 of file utils.c.
References __CPLX16, __CPLX32, __CPLX8, __REAL16, __REAL4, __REAL8, __STR, assert, cnt, FIO_TYPE_SIZE, p, SWAPB, and type.
Referenced by __f90io_usw_read(), __f90io_usw_write(), __unf_init(), __usw_end(), and _f90io_backspace().
__fortio_zeropad()
int __fortio_zeropad (FILE * fp, long len)
Definition at line 450 of file utils.c.
References __io_errno(), b, BFSZ, fp, FWRITE, and len.
Referenced by __fortio_rwinit(), __unf_end(), and __usw_end().
f90_old_huge_rec_fmt()
int f90_old_huge_rec_fmt (void)
Definition at line 1042 of file runtime/flang/error.c.
References legacy_large_rec_fmt.
Referenced by __unf_end(), __unf_init(), and __usw_end().
get_gbl_newunit()
bool get_gbl_newunit ()
Definition at line 89 of file runtime/flang/error.c.
References gbl, and fioerror::newunit.
Referenced by f90_open().
set_gbl_newunit()
VOID set_gbl_newunit (bool newunit)
Definition at line 83 of file runtime/flang/error.c.
References gbl, and fioerror::newunit.
Referenced by ENTF90IO().
strtod()
WIN_MSVCRT_IMP double WIN_CDECL strtod (const char * , char **)
Referenced by parse_d().
strtold()
WIN_MSVCRT_IMP long double WIN_CDECL strtold (const char * , char **)
Referenced by parse_q().
Variable Documentation
__ftn_32in64_
int __ftn_32in64_ extern
Definition at line 17 of file utilsi64.c.
envar_fortranopt
char* envar_fortranopt extern
Definition at line 30 of file runtime/flang/error.c.
Referenced by __fortio_init(), __fortio_open(), _f90io_encode_fmt(), check_outer_parens(), fw_write(), restore_gbl(), and save_gbl().
fioFcbTbls
FIO_TBL fioFcbTbls extern
Definition at line 14 of file fiodf.c.
Referenced by __f90io_fmt_read(), __f90io_fmt_write(), __f90io_ldr(), __f90io_ldw(), __f90io_unf_end(), __f90io_unf_init(), __f90io_unf_read(), __f90io_unf_write(), __f90io_usw_end(), __f90io_usw_init(), __f90io_usw_read(), __f90io_usw_write(), __fortio_alloc_fcb(), __fortio_cleanup(), __fortio_eoferr(), __fortio_eorerr(), __fortio_errinit(), __fortio_errinit03(), __fortio_error(), __fortio_find_unit(), __fortio_free_fcb(), __fortio_init(), __fortio_open(), __fortio_rwinit(), _f90io_fmtr_end(), _f90io_fmtw_end(), _f90io_ldr_end(), _f90io_ldr_init(), _f90io_ldw_end(), _f90io_nml_read(), _f90io_nml_write(), _f90io_nmlr_end(), _f90io_nmlr_init(), _f90io_nmlw_end(), ef_alloc(), ENTF90IO(), f90_open(), fr_init(), fr_intern_init(), fw_init(), fw_intern_init(), inquire(), ioerrinfo(), restore_fmtgbl(), restore_gbl(), save_fmtgbl(), save_gbl(), set_pos(), set_src_info(), and write_record().
next_newunit
int next_newunit extern
Definition at line 30 of file open.c.
Referenced by ENTF90IO().