flang: rw.c File Reference
rw.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
Functions
void __fort_rrecvl (int cpu, void *adr, long cnt, long str, int typ, long ilen)
void __fort_rsendl (int cpu, void *adr, long cnt, long str, int typ, long ilen)
void __fort_rrecv (int cpu, void *adr, long cnt, long str, int typ)
void __fort_rsend (int cpu, void *adr, long cnt, long str, int typ)
void __fort_rbcstl (int src, void *adr, long cnt, long str, int typ, long ilen)
void __fort_rbcst (int src, void *adr, long cnt, long str, int typ)
Function Documentation
__fort_rbcst()
void __fort_rbcst (int src, void * adr, long cnt, long str, int typ)
Definition at line 130 of file rw.c.
References __fort_rbcstl(), ent::adr, cnt, GET_DIST_SIZE_OF, src, str, and ent::typ.
Referenced by __fort_status_bcst(), and __fort_time().
__fort_rbcstl()
void __fort_rbcstl (int src, void * adr, long cnt, long str, int typ, long ilen)
Definition at line 76 of file rw.c.
References __fort_erecv(), __fort_esend(), ent::adr, cnt, cp, e, GET_DIST_LCPU, GET_DIST_TCPUS, ent::ilen, s, src, str, and ent::typ.
Referenced by __fort_get_scalar(), __fort_rbcst(), __fortio_main(), __fortio_stat_bcst(), and ENTFTN().
__fort_rrecv()
void __fort_rrecv (int cpu, void * adr, long cnt, long str, int typ)
Definition at line 60 of file rw.c.
References __fort_rrecvl(), ent::adr, cnt, cpu(), GET_DIST_SIZE_OF, str, and ent::typ.
Referenced by __fort_crecv(), __fort_pull_them_in(), __fort_stat_term(), __fort_zclose(), __fort_zopen(), and ENTFTN().
__fort_rrecvl()
void __fort_rrecvl (int cpu, void * adr, long cnt, long str, int typ, long ilen)
Definition at line 14 of file rw.c.
References __fort_erecv(), ent::adr, cnt, cpu(), e, ent::ilen, s, str, and ent::typ.
Referenced by __fort_global_reduce(), __fort_passarg(), __fort_passargs(), __fort_reduce_section(), __fort_rrecv(), __io_read(), broadcast(), and gathscat_start().
__fort_rsend()
void __fort_rsend (int cpu, void * adr, long cnt, long str, int typ)
Definition at line 68 of file rw.c.
References __fort_rsendl(), ent::adr, cnt, cpu(), GET_DIST_SIZE_OF, str, and ent::typ.
Referenced by __fort_csend(), __fort_pull_them_in(), __fort_stat_term(), __fort_zclose(), __fort_zopen(), __fort_zwrite(), and ENTFTN().
__fort_rsendl()
void __fort_rsendl (int cpu, void * adr, long cnt, long str, int typ, long ilen)
Definition at line 37 of file rw.c.
References __fort_esend(), ent::adr, cnt, cpu(), e, ent::ilen, s, str, and ent::typ.
Referenced by __fort_global_reduce(), __fort_passarg(), __fort_passargs(), __fort_reduce_section(), __fort_rsend(), __io_read(), broadcast(), and gathscat_start().