flang: salloc.c File Reference
salloc.c File Reference
compiler storage allocation utility routines.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
Macros
#define SIZE
#define ANUM 30 /* number of different areas supported, 0...ANUM-1 */
#define PTRSZ sizeof(PTR)
#define ALIGN(o) (((o) + (PTRSZ - 1)) & (~(PTRSZ - 1)))
Typedefs
typedef char * PTR
Functions
char * getitem (int area, int size)
void freearea (int area)
int put_getitem_p (void *p)
stores the pointer in the pointer table and returns its index.
void * get_getitem_p (int i)
returns the pointer stored at index i.
void free_getitem_p (void)
frees the table of pointers. NOTE: it's safer to just call this function at the end of compilation to allow a mix of pointers which are only live during a phase and those which are live during the entire compile such as the pointers locating items in area 8.
Variables
static char * areap [ANUM]
static int avail [ANUM]
struct {
void ** base
int size
int avail
} tbl = {0, 0, 0}
Detailed Description
compiler storage allocation utility routines.
Definition in file salloc.c.
Macro Definition Documentation
ALIGN
#define ALIGN (o) (((o) + (PTRSZ - 1)) & (~(PTRSZ - 1)))
Definition at line 25 of file salloc.c.
ANUM
#define ANUM 30 /* number of different areas supported, 0...ANUM-1 */
Definition at line 19 of file salloc.c.
PTRSZ
#define PTRSZ sizeof(PTR)
Definition at line 24 of file salloc.c.
SIZE
#define SIZE
Value:
  2000          /* size in bytes of each block of memory \
                 * obtained from malloc (NEW). */
Definition at line 17 of file salloc.c.
Typedef Documentation
PTR
typedef char* PTR
Definition at line 21 of file salloc.c.
Function Documentation
free_getitem_p()
void free_getitem_p (void)
frees the table of pointers. NOTE: it's safer to just call this function at the end of compilation to allow a mix of pointers which are only live during a phase and those which are live during the entire compile such as the pointers locating items in area 8.
Definition at line 177 of file salloc.c.
References tbl::base, and tbl::size.
Referenced by finish().
freearea()
void freearea (int area)
Definition at line 83 of file salloc.c.
References ANUM, area, areap, assert, ERR_Fatal, FREE, NULL, p, and q.
Referenced by apply_use_stmts(), assem_end(), call_analyze(), ccff_cleanup_children(), ccff_cleanup_children_deferred(), cg_llvm_fnend(), chkref(), cleanup(), const_prop(), convert_output(), dd_array_conflict(), do_dinit(), Done(), end_loop_count(), exp_end(), expand(), export(), export_some_fini(), exterf_init(), extractor_end(), finish(), flow(), flowgraph(), forall_dependency_analyze(), import_done(), live_var(), ll_process_routine_parameters(), opt_allocate(), opt_binop(), optshrd_fend(), reaching_defs(), reg_assign1(), schedule(), semant1(), semfin_free_memory(), top_sort(), trans_freeidx(), uninit_var(), and upper().
get_getitem_p()
void * get_getitem_p (int i)
returns the pointer stored at index i.
Definition at line 158 of file salloc.c.
References assert, tbl::base, ERR_unused, i, NULL, and tbl::size.
Referenced by _dmp_dent(), build_typedef_init_tree(), construct_acl_for_sst(), dump_stfunc(), eval_init_expr_item(), eval_init_op(), export_component_init(), export_component_init_asts(), gen_derived_type_alloc_init(), get_dtype_init_template(), get_parameterized_dt(), init_allocatable_typedef_components(), init_named_array_constant(), ref_stfunc(), and semant1().
getitem()
char * getitem (int area, int size)
Parameters
area is an area
size is the size in bytes of item to be allocated.
Definition at line 37 of file salloc.c.
References ALIGN, ANUM, area, areap, assert, avail, DBGBIT, ERR_Fatal, interr(), NEW, NULL, p, PTRSZ, q, s, SIZE, size, and sz.
Referenced by __fih_message(), _adjustl(), _adjustr(), _repeat(), _trim(), add_alloc_mem_initialize(), add_auto_dealloc(), add_auto_finalize(), add_biv_def(), add_dep(), add_du_ud(), add_etmp(), add_imported(), add_iolptrs(), add_p_dealloc_item(), add_private_allocatable(), add_profile_decl(), add_tmp_buf_list_item(), add_to_be_used_list(), add_to_cselist(), add_to_private_mod_list(), add_to_use_tree(), add_type_param_initialize(), add_use_edge(), add_use_rename(), add_use_tree_uses(), add_wheresym(), addfile(), addinlfile(), binop(), bld_lhs(), ccff_set_children(), ccff_set_children_deferred(), ch_substring(), check_alias(), check_global_define(), check_sc(), chk_struct_constructor(), clist(), clone_init_const(), cngcon(), compare_one_bound(), compute_size(), construct_acl_from_ast(), convert_to_block_forall(), create_global_initializer(), dataConstant(), dataDo(), dataEnddo(), dataReference(), dataStructure(), dataVariable(), dd_edge(), define_stfunc(), defined_io_error(), dinit_constructor(), direct_xf(), direct_yf(), distrib(), do_default_clause(), do_dinit(), do_eval_minval_or_maxval(), do_nested_uses(), enqueueTbp(), eval_adjustl(), eval_adjustr(), eval_do(), eval_index(), eval_init_op(), eval_max(), eval_min(), eval_minval_or_maxval(), eval_repeat(), eval_scale(), eval_scan(), eval_selected_char_kind(), eval_selected_real_kind(), eval_transfer(), eval_trim(), eval_verify(), export_all(), export_append_host_sym(), export_append_sym(), export_public_module(), extractor(), find_best_generic(), findloop(), fix_proc_pointer_call(), flowgraph(), func_call2(), gen_call_to_builtin(), gen_cmplxpart_intr(), gen_constant(), gen_defer_shape(), gen_dtio_arglist(), gen_dtio_args(), gen_fcn_sst(), gen_kind_parm_assignments(), gen_reduction(), gen_va_end(), gen_va_start(), gen_vconstant(), get_acl(), get_dobegin(), get_doend(), get_doinfo(), get_fn(), get_intrinsic(), get_keyword_args(), get_keyword_components(), get_llvm_ifacenm(), get_llvm_sname(), get_local_overlap_size(), get_minmax_val(), get_string_constant(), get_tbp_argno(), getcyclic(), getict(), getivl(), getstr(), getstrconst(), import(), import_header_only(), inheritTbps(), init(), insert_llvm_dbg_declare(), insert_llvm_dbg_value(), insert_llvm_memcpy(), insert_llvm_memset(), insert_llvm_prefetch(), insert_node_into_use_tree(), kwd_match(), ll_process_routine_parameters(), lldbg_alloc(), lldbg_function_end(), llutil_alloc(), load_TOC(), localflow(), lower_add_func_call(), make_instr(), make_list(), mangleUnderscores(), match_names(), mergeDebugTypesForGlobal(), mk_ido_std_range(), mk_init_intrinsic(), mk_lastprivate_list(), mk_reduction_list(), mk_shared_list(), mkfname(), mkitem(), new_ivs(), open_module(), partition_blocks(), plist(), pp_entries(), pp_entries_mixedstrlen(), print_entry_subroutine(), process_blockaddr_sptr(), process_extern_function_sptr(), process_extern_variable_sptr(), process_label_sptr_c(), process_local_sptr(), process_string(), push_include(), push_tbp_arg(), ref_stfunc(), replace_variable(), resolve_generic(), resolveGeneric(), resolvePass(), resolveTbps(), rewrite_cmplxpart_rhs(), rewrite_cmplxpart_rval(), save_firstprivate_list(), save_ilms(), save_private_list(), save_shared_list(), scan_include(), selection_sort(), semant1(), semant2(), semant3(), semantio(), semCheckTbp(), semsmp(), set_global_sname(), set_local_sname(), set_numbered_global_sname(), setfile(), store_funcname(), storechartmp(), subr_call2(), sum_scatter_args(), sym_get_sdescr(), top_sort(), update_external_function_declarations(), var_ref_list(), vect_llvm_intrinsic_name(), and write_profile_enter().
put_getitem_p()
int put_getitem_p (void * p)
stores the pointer in the pointer table and returns its index.
Definition at line 134 of file salloc.c.
References tbl::base, NEED, NEW, NULL, p, r, and tbl::size.
Referenced by convert_ctmp_array_to_param(), define_stfunc(), get_component_init(), get_parameterized_dt(), init_allocatable_typedef_components(), put_data_statement(), save_typedef_init(), and semant1().
Variable Documentation
areap
char* areap[ANUM] static
Initial value:
= {NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                            NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                            NULL, NULL, NULL, NULL, NULL, NULL, NULL}
Definition at line 27 of file salloc.c.
Referenced by freearea(), and getitem().
avail
int avail static
Definition at line 30 of file salloc.c.
Referenced by getitem().
base
void** base
Definition at line 124 of file salloc.c.
size
int size
Definition at line 125 of file salloc.c.
Referenced by getitem().
struct { ... } tbl