flang: scal.c File Reference
scal.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "fort_vars.h"
Functions
void I8() __fort_get_scalar (void *dst, void *ab, F90_Desc *ad, __INT_T *idx)
void ENTFTN (GET_SCALAR, get_scalar)
void ENTFTN (BCST_SCALAR, bcst_scalar)
Variables
void(* __fort_scalar_copy [__NTYPES])(void *rp, void *sp, int size)
Function Documentation
__fort_get_scalar()
void I8() __fort_get_scalar (void * dst, void * ab, F90_Desc * ad, __INT_T * idx)
Definition at line 20 of file scal.c.
References __fort_abort(), __fort_local_address(), __fort_owner, __fort_rbcstl(), __fort_scalar_copy, __fort_show_scalar(), __fort_test, __io_putchar(), __LOCAL, DEBUG_SCAL, DFMT, DFMT_GEN_BLOCK, DIM_UBOUND_G, DIST_ALIGN_TARGET_G, DIST_DIM_GEN_BLOCK_G, DIST_DIM_OLB_G, DIST_DIM_OUB_G, DIST_DIM_PSHAPE_G, DIST_DIM_TLB_G, DIST_DIM_TOFFSET_G, DIST_DIM_TSTRIDE_G, DIST_DIM_TUB_G, DIST_MAPPED_G, DIST_SCOFF_G, F90_DIM_LBOUND_G, F90_FLAGS_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, GET_DIST_LCPU, i, I8, idx, j, NULL, and src.
Referenced by __fort_fetch_int_element(), __fort_fetch_int_vector(), and ENTFTN().
ENTFTN() [1/2]
void ENTFTN (BCST_SCALAR , bcst_scalar)
Definition at line 116 of file scal.c.
References __fort_rbcstl(), __fort_scalar_copy, cpu(), GET_DIST_LCPU, GET_DIST_TCPUS, kind, len, and src.
ENTFTN() [2/2]
void ENTFTN (GET_SCALAR , get_scalar)
Definition at line 93 of file scal.c.
References __DESC, __fort_abort(), __fort_get_scalar(), F90_RANK_G, F90_TAG_G, i, I8, idx, MAXDIMS, NULL, and va.
Variable Documentation
__fort_scalar_copy
void(* __fort_scalar_copy[__NTYPES])(void *rp, void *sp, int size) (void * rp, void * sp, int size) extern
Referenced by __fort_get_scalar(), and ENTFTN().