flang: scan.c File Reference
scan.c File Reference
This file contains the compiler's scanner (lexical analyzer) module.
#include "gbldefs.h"
#include "global.h"
#include "symtab.h"
#include "dtypeutl.h"
#include "gramtk.h"
#include "error.h"
#include "semant.h"
#include "semstk.h"
#include "scan.h"
#include "ast.h"
#include "ccffinfo.h"
#include "fih.h"
#include "dinit.h"
#include "kwddf.h"
#include "tokdf.h"
Classes
struct ISTACK
struct HDRSTACK
struct c
Macros
#define OPENMP (flg.smp && !XBIT(69, 1))
#define SGIMP (flg.smp && !XBIT(69, 2))
#define MAX_COLS 1000
#define CARDB_SIZE (MAX_COLS + 6)
#define INIT_LPS 21
#define MAX_IDEPTH 20
#define MAX_PATHNAME_LEN 4096
#define CH_STRING 31
#define CH_HOLLERITH 30
#define CH_O 29
#define CH_X 28
#define CH_IMPLP 27
#define CH_NULLSTR 26
#define CH_KSTRING 25 /* kanji string - NC'...' */
#define CH_PRAGMA 24
#define CH_IOLP 23
#define CH_B 22
#define CH_IMPRP 21
#define CH_UNDERSCORE 20
#define CH_FMTSTR 19
#define CT_NONE 0
#define CT_INITIAL 1
#define CT_END 2
#define CT_CONTINUATION 3
#define CT_SMP 4
#define CT_DEC 5
#define CT_COMMENT 6
#define CT_EOF 7
#define CT_DIRECTIVE 8
#define CT_LINE 9
#define CT_PRAGMA 10
#define CT_FIXED 11
#define CT_FREE 12
#define CT_MEM 13
#define CT_PPRAGMA 14
#define CT_ACC 15
#define CT_KERNEL 16
#define CT_PGI 17
#define SL_NONE 0
#define SL_HPF 1
#define SL_OMP 2
#define SL_SGI 3
#define SL_MEM 4
#define SL_PGI 6
#define SL_KERNEL 7
#define B_NONE 0
#define B_FUNC_FOUND 1
#define B_RPAREN_FOUND 2
#define B_RESULT_FOUND 3
#define B_RESULT_RPAREN_FOUND 4
#define ERROR_STOP()
#define SCM_FIRST 1
#define SCM_IDENT 2
#define SCM_FORMAT 3
#define SCM_IMPLICIT 4
#define SCM_FUNCTION 5
#define SCM_IO 6
#define SCM_TO 7
#define SCM_IF 8
#define SCM_DOLAB 9
#define SCM_GOTO 10
#define SCM_DONEXT 11
#define SCM_LOCALITY 12
#define SCM_ALLOC 13
#define SCM_ID_ATTR 14
#define SCM_NEXTIDENT 15 /* next exposed id is as if it begins a statement */
#define SCM_INTERFACE 16
#define SCM_OPERATOR
#define SCM_LOOKFOR_OPERATOR 18 /* next id may be word 'operator' */
#define SCM_PAR 19
#define SCM_ACCEL 20
#define SCM_BIND 21 /* next id is keyword bind */
#define SCM_PROCEDURE 22
#define SCM_KERNEL 23
#define SCM_GENERIC 24
#define SCM_TYPEIS 25
#define SCM_DEFINED_IO 26
#define SCM_CHEVRON 27
#define CERROR(a, b, c, d, e, f)
#define MKC(cp) ((*(cp)) & 0xFF)
#define MERGE(cp) ((MKC(cp) << 24) | (MKC(cp + 1) << 16) | (MKC(cp + 2) << 8) | (MKC(cp + 3)))
#define MAX_DIRLEN 4
#define SW_CHECK 1
#define SW_NOCHECK 2
#define SW_EXTEND 3
#define SW_NOEXTEND 4
#define SW_GFLOAT 5
#define SW_NOGFLOAT 6
#define SW_I4 8
#define SW_NOI4 9
#define SW_RECURS 10
#define SW_NORECURS 11
#define SW_STANDARD 12
#define SW_NOSTANDARD 13
#define SW_REENTR 14
#define SW_NOREENTR 15
#define NSWDS (sizeof(swtchtab) / sizeof(struct c))
#define MAX_DIRLEN 4
Functions
void fe_restore_state (void)
static void set_input_form (LOGICAL)
static void get_stmt (void)
static void line_directive (void)
static void get_fn (void)
static int otodi (char *, int, INT *)
static int htodi (char *, int, INT *)
static int hex_to_i (int)
static int btodi (char *, int, INT *)
static int read_card (void)
static void write_card (void)
static int check_pgi_pragma (char *)
static int check_pragma (char *)
static int ic_strncmp (const char *, const char *)
static LOGICAL is_lineblank (char *)
static void crunch (void)
static int classify_smp (void)
static int classify_dec (void)
static int classify_pragma (void)
static int classify_pgi_pragma (void)
static int classify_ac_type (void)
static int classify_pgi_dir (void)
static int classify_kernel_pragma (void)
static void alpha (void)
static int get_id_name (char *, int)
static LOGICAL is_keyword (char *, int, const char *)
static int cmp (const char *, const char *, int *)
static int is_ident (char *)
static int is_digit_string (char *)
static int get_kind_id (char *)
static INT get_kind_value (int)
static int get_cstring (char *, int *)
static int get_fmtstr (char *)
static void get_number (int)
static void get_nondec (int)
static int get_prefixed_int (int)
static void check_ccon (void)
static void do_dot (void)
static void push_include (char *)
static void put_astfil (int, char *, LOGICAL)
static void put_lineno (int)
static void put_include (int, int)
static void realloc_stmtb (void)
static void ff_check_stmtb (void)
static void check_continuation (int)
static LOGICAL is_next_char (char *, int)
static int double_type (char *, int *)
void add_headerfile (const char *, int, int)
void parse_init (void)
void p_pragma (char *, int)
static void ff_get_stmt (void)
static void ff_prescan (void)
static void ff_chk_pragma (char *)
static void ff_get_noncomment (char *)
static int ff_read_card (void)
static int ff_get_label (char *)
static int _get_token (INT *)
static void ill_char (int)
static void _write_token (int, INT)
static int _read_token (INT *)
static void init_ktable (KTABLE *)
static int keyword (char *, KTABLE *, int *, LOGICAL)
void scan_init (FILE *fd)
Initialize Scanner. This routine is called once at the beginning of execution.
void scan_reset (void)
Lexical or syntactical error found, so re-initialize the Scanner so that next Fortran statement will be processed.
void scan_fini (void)
Compilation is finished - deallocate storage, close files, etc.
int get_token (INT *tknv)
static char * _readln (int mx_len, LOGICAL len_err)
static void fmt_putchar (int)
static void fmt_putstr (const char *)
static void char_to_text (int)
void scan_include (char *str)
static int getindex (struct c *, int, char *)
void scan_opt_restore (void)
void scan_options (void)
void fe_init (void)
void fe_save_state (void)
void fe_restart (void)
static void _restore_state (void)
static void _rd_tkline (char **tkbuf, int *tkbuf_sz)
static int _rd_token (INT *)
static INT get_num (int)
static int trimContIdx (char *line)
trim white space of source line that has continuations and return the index of the last character in the source line.
static int numLeadingSpaces (char *line)
static int contIndex (char *line)
Parse a source line with comments/continuations/string literals and return the index of the last non-white space character of the source line.
char * get_src_line (int line, char **src_file, int col, int *srcCol, int *contNo)
get the post-processed source line in the current source file.
int getCurrColumn (void)
int get_named_stmtyp (void)
Variables
LOGICAL fpp_
static int bind_state = B_NONE
static FILE * curr_fd
static int incl_level
static int incl_stacksz
static ISTACK * incl_stack = NULL
static int hdr_level
static int hdr_stacksz
static HDRSTACK * hdr_stack = NULL
static int curr_line
static LOGICAL first_line
static char cardb [CARDB_SIZE]
static char save_extend_ch
static LOGICAL list_now
static char printbuff [CARDB_SIZE]
static char * first_char
static int card_type
static int sentinel
static char * stmtb
static char * stmtbefore = NULL
static char * stmtbafter = NULL
static short * last_char = NULL
static int card_count
static int max_card
static char * currc
static char * eos
static int leadCount
static int currCol
static char * tkbuf = NULL
static int tkbuf_sz
static int directive_sz
static int options_sz
static LOGICAL scnerrfg
static LOGICAL exp_comma
static LOGICAL exp_equal
static LOGICAL exp_ptr_assign
static LOGICAL exp_attr
static LOGICAL follow_attr
static LOGICAL exp_ac
static LOGICAL exp_dtvlist
static LOGICAL integer_only
static LOGICAL par1_attr
static LOGICAL is_smp
static LOGICAL is_sgi
static LOGICAL is_dec
static LOGICAL is_mem
static LOGICAL is_ppragma
static LOGICAL is_pgi
static bool is_doconcurrent
static LOGICAL is_kernel
static LOGICAL long_pragma_candidate
static int scmode
static int par_depth
static LOGICAL past_equal
static LOGICAL reset_past_equal
static int acb_depth
static int tkntyp
static INT tknval
static int body_len
static LOGICAL no_crunch
static LOGICAL in_include
static int kind_id
static LOGICAL seen_implp
static LOGICAL is_freeform
static LOGICAL sig_blanks
struct {
char * cavail
char * outptr
char * amper_ptr
int last_char
} ff_state
static void(* p_get_stmt)(void) = get_stmt
static int(* p_read_card)(void) = read_card
static int(* p_get_token [])(INT *) = {_get_token, _read_token}
static int keyword_idx
struct {
char * str
int len
int sz
} fmtstr
static int options_seen = FALSE
static struct c swtchtab []
struct {
int extend_source
LOGICAL i4
LOGICAL standard
LOGICAL recursive
int x7
int x70
} save_flg
struct {
long file_pos
} fe_state
static char * tkp
Detailed Description
This file contains the compiler's scanner (lexical analyzer) module.
Definition in file scan.c.
Macro Definition Documentation
B_FUNC_FOUND
#define B_FUNC_FOUND 1
Definition at line 160 of file scan.c.
B_NONE
#define B_NONE 0
Definition at line 159 of file scan.c.
B_RESULT_FOUND
#define B_RESULT_FOUND 3
Definition at line 162 of file scan.c.
B_RESULT_RPAREN_FOUND
#define B_RESULT_RPAREN_FOUND 4
Definition at line 163 of file scan.c.
B_RPAREN_FOUND
#define B_RPAREN_FOUND 2
Definition at line 161 of file scan.c.
CARDB_SIZE
#define CARDB_SIZE (MAX_COLS + 6)
Definition at line 101 of file scan.c.
CERROR
#define CERROR (a, b, c, d, e, f)
Value:
  {                              \
    char tmp;                    \
    tmp = *e;                    \
    *e = 0;                      \
    error(a, b, c, d, f);        \
    *e = tmp;                    \
  }
Definition at line 360 of file scan.c.
CH_B
#define CH_B 22
Definition at line 119 of file scan.c.
CH_FMTSTR
#define CH_FMTSTR 19
Definition at line 122 of file scan.c.
CH_HOLLERITH
#define CH_HOLLERITH 30
Definition at line 111 of file scan.c.
CH_IMPLP
#define CH_IMPLP 27
Definition at line 114 of file scan.c.
CH_IMPRP
#define CH_IMPRP 21
Definition at line 120 of file scan.c.
CH_IOLP
#define CH_IOLP 23
Definition at line 118 of file scan.c.
CH_KSTRING
#define CH_KSTRING 25 /* kanji string - NC'...' */
Definition at line 116 of file scan.c.
CH_NULLSTR
#define CH_NULLSTR 26
Definition at line 115 of file scan.c.
CH_O
#define CH_O 29
Definition at line 112 of file scan.c.
CH_PRAGMA
#define CH_PRAGMA 24
Definition at line 117 of file scan.c.
CH_STRING
#define CH_STRING 31
Definition at line 110 of file scan.c.
CH_UNDERSCORE
#define CH_UNDERSCORE 20
Definition at line 121 of file scan.c.
CH_X
#define CH_X 28
Definition at line 113 of file scan.c.
CT_ACC
#define CT_ACC 15
Definition at line 142 of file scan.c.
CT_COMMENT
#define CT_COMMENT 6
Definition at line 132 of file scan.c.
CT_CONTINUATION
#define CT_CONTINUATION 3
Definition at line 129 of file scan.c.
CT_DEC
#define CT_DEC 5
Definition at line 131 of file scan.c.
CT_DIRECTIVE
#define CT_DIRECTIVE 8
Definition at line 134 of file scan.c.
CT_END
#define CT_END 2
Definition at line 128 of file scan.c.
CT_EOF
#define CT_EOF 7
Definition at line 133 of file scan.c.
CT_FIXED
#define CT_FIXED 11
Definition at line 137 of file scan.c.
CT_FREE
#define CT_FREE 12
Definition at line 138 of file scan.c.
CT_INITIAL
#define CT_INITIAL 1
Definition at line 127 of file scan.c.
CT_KERNEL
#define CT_KERNEL 16
Definition at line 143 of file scan.c.
CT_LINE
#define CT_LINE 9
Definition at line 135 of file scan.c.
CT_MEM
#define CT_MEM 13
Definition at line 139 of file scan.c.
CT_NONE
#define CT_NONE 0
Definition at line 126 of file scan.c.
CT_PGI
#define CT_PGI 17
Definition at line 144 of file scan.c.
CT_PPRAGMA
#define CT_PPRAGMA 14
Definition at line 141 of file scan.c.
CT_PRAGMA
#define CT_PRAGMA 10
Definition at line 136 of file scan.c.
CT_SMP
#define CT_SMP 4
Definition at line 130 of file scan.c.
ERROR_STOP
#define ERROR_STOP ()
Value:
  {                        \
    tkntyp = TK_ERRORSTOP; \
    idlen += 5;            \
  }
Definition at line 165 of file scan.c.
INIT_LPS
#define INIT_LPS 21
Definition at line 103 of file scan.c.
MAX_COLS
#define MAX_COLS 1000
Definition at line 100 of file scan.c.
MAX_DIRLEN [1/2]
#define MAX_DIRLEN 4
MAX_DIRLEN [2/2]
#define MAX_DIRLEN 4
MAX_IDEPTH
#define MAX_IDEPTH 20
Definition at line 104 of file scan.c.
MAX_PATHNAME_LEN
#define MAX_PATHNAME_LEN 4096
Definition at line 105 of file scan.c.
MERGE
#define MERGE (cp) ((MKC(cp) << 24) | (MKC(cp + 1) << 16) | (MKC(cp + 2) << 8) | (MKC(cp + 3)))
MKC
#define MKC (cp) ((*(cp)) & 0xFF)
NSWDS
#define NSWDS (sizeof(swtchtab) / sizeof(struct c))
Definition at line 7549 of file scan.c.
OPENMP
#define OPENMP (flg.smp && !XBIT(69, 1))
Definition at line 88 of file scan.c.
SCM_ACCEL
#define SCM_ACCEL 20
Definition at line 291 of file scan.c.
SCM_ALLOC
#define SCM_ALLOC 13
Definition at line 284 of file scan.c.
SCM_BIND
#define SCM_BIND 21 /* next id is keyword bind */
Definition at line 292 of file scan.c.
SCM_CHEVRON
#define SCM_CHEVRON 27
Definition at line 298 of file scan.c.
SCM_DEFINED_IO
#define SCM_DEFINED_IO 26
Definition at line 297 of file scan.c.
SCM_DOLAB
#define SCM_DOLAB 9
Definition at line 280 of file scan.c.
SCM_DONEXT
#define SCM_DONEXT 11
Definition at line 282 of file scan.c.
SCM_FIRST
#define SCM_FIRST 1
Definition at line 272 of file scan.c.
SCM_FORMAT
#define SCM_FORMAT 3
Definition at line 274 of file scan.c.
SCM_FUNCTION
#define SCM_FUNCTION 5
Definition at line 276 of file scan.c.
SCM_GENERIC
#define SCM_GENERIC 24
Definition at line 295 of file scan.c.
SCM_GOTO
#define SCM_GOTO 10
Definition at line 281 of file scan.c.
SCM_ID_ATTR
#define SCM_ID_ATTR 14
Definition at line 285 of file scan.c.
SCM_IDENT
#define SCM_IDENT 2
Definition at line 273 of file scan.c.
SCM_IF
#define SCM_IF 8
Definition at line 279 of file scan.c.
SCM_IMPLICIT
#define SCM_IMPLICIT 4
Definition at line 275 of file scan.c.
SCM_INTERFACE
#define SCM_INTERFACE 16
Definition at line 287 of file scan.c.
SCM_IO
#define SCM_IO 6
Definition at line 277 of file scan.c.
SCM_KERNEL
#define SCM_KERNEL 23
Definition at line 294 of file scan.c.
SCM_LOCALITY
#define SCM_LOCALITY 12
Definition at line 283 of file scan.c.
SCM_LOOKFOR_OPERATOR
#define SCM_LOOKFOR_OPERATOR 18 /* next id may be word 'operator' */
Definition at line 289 of file scan.c.
SCM_NEXTIDENT
#define SCM_NEXTIDENT 15 /* next exposed id is as if it begins a statement */
Definition at line 286 of file scan.c.
SCM_OPERATOR
#define SCM_OPERATOR
Value:
                         17 /* next id (presumably enclosed in '.'s) is a
                         * user-defined or named intrinsic operator */
Definition at line 288 of file scan.c.
SCM_PAR
#define SCM_PAR 19
Definition at line 290 of file scan.c.
SCM_PROCEDURE
#define SCM_PROCEDURE 22
Definition at line 293 of file scan.c.
SCM_TO
#define SCM_TO 7
Definition at line 278 of file scan.c.
SCM_TYPEIS
#define SCM_TYPEIS 25
Definition at line 296 of file scan.c.
SGIMP
#define SGIMP (flg.smp && !XBIT(69, 2))
Definition at line 89 of file scan.c.
SL_HPF
#define SL_HPF 1
Definition at line 149 of file scan.c.
SL_KERNEL
#define SL_KERNEL 7
Definition at line 154 of file scan.c.
SL_MEM
#define SL_MEM 4
Definition at line 152 of file scan.c.
SL_NONE
#define SL_NONE 0
Definition at line 148 of file scan.c.
SL_OMP
#define SL_OMP 2
Definition at line 150 of file scan.c.
SL_PGI
#define SL_PGI 6
Definition at line 153 of file scan.c.
SL_SGI
#define SL_SGI 3
Definition at line 151 of file scan.c.
SW_CHECK
#define SW_CHECK 1
Definition at line 7515 of file scan.c.
SW_EXTEND
#define SW_EXTEND 3
Definition at line 7517 of file scan.c.
SW_GFLOAT
#define SW_GFLOAT 5
Definition at line 7519 of file scan.c.
SW_I4
#define SW_I4 8
Definition at line 7521 of file scan.c.
SW_NOCHECK
#define SW_NOCHECK 2
Definition at line 7516 of file scan.c.
SW_NOEXTEND
#define SW_NOEXTEND 4
Definition at line 7518 of file scan.c.
SW_NOGFLOAT
#define SW_NOGFLOAT 6
Definition at line 7520 of file scan.c.
SW_NOI4
#define SW_NOI4 9
Definition at line 7522 of file scan.c.
SW_NORECURS
#define SW_NORECURS 11
Definition at line 7524 of file scan.c.
SW_NOREENTR
#define SW_NOREENTR 15
Definition at line 7528 of file scan.c.
SW_NOSTANDARD
#define SW_NOSTANDARD 13
Definition at line 7526 of file scan.c.
SW_RECURS
#define SW_RECURS 10
Definition at line 7523 of file scan.c.
SW_REENTR
#define SW_REENTR 14
Definition at line 7527 of file scan.c.
SW_STANDARD
#define SW_STANDARD 12
Definition at line 7525 of file scan.c.
Function Documentation
_get_token()
static int _get_token (INT * tknv) static
Definition at line 534 of file scan.c.
References _write_token(), acb_depth, alpha(), SCN::avl, B_FUNC_FOUND, B_NONE, B_RESULT_FOUND, B_RESULT_RPAREN_FOUND, B_RPAREN_FOUND, bind_state, CARDB_SIZE, CH_B, CH_FMTSTR, CH_HOLLERITH, CH_IMPLP, CH_IMPRP, CH_IOLP, CH_KSTRING, CH_NULLSTR, CH_O, CH_PRAGMA, CH_STRING, CH_UNDERSCORE, CH_X, check_ccon(), classify_ac_type(), classify_dec(), classify_kernel_pragma(), classify_pgi_dir(), classify_pgi_pragma(), classify_pragma(), classify_smp(), CNULL, crunch(), currc, SCN::directive, directive_sz, do_dot(), error(), exp_ac, exp_attr, exp_dtvlist, FALSE, FLANG_FALLTHROUGH, flg, follow_attr, FR_PRAGMA, FR_STMT, gbl, get_nondec(), get_number(), get_prefixed_int(), getstring(), SCN::id, ill_char(), INSIDE_STRUCT, integer_only, is_dec, is_doconcurrent, is_ident(), is_kernel, is_mem, is_pgi, is_ppragma, is_smp, len, MERGE, SCN::multiple_stmts, NEED, no_crunch, NULL, p, par1_attr, par_depth, parse_init(), past_equal, put_astfil(), reset_past_equal, SCM_ALLOC, SCM_FIRST, SCM_FORMAT, SCM_GENERIC, SCM_ID_ATTR, SCM_IDENT, SCM_IO, SCM_LOCALITY, SCM_LOOKFOR_OPERATOR, SCM_NEXTIDENT, SCM_OPERATOR, SCM_PAR, scmode, scn, scnerrfg, seen_implp, sig_blanks, FLG::standard, stmtb, stmtbafter, stmtbefore, SCN::stmtyp, strlen(), TK_COLON, TK_COMMA, TK_EQUALS, TK_PERCENT, TK_RPAREN, TK_SLASH, tkntyp, tknval, TRUE, and XBIT.
_rd_tkline()
static void _rd_tkline (char ** tkbuf, int * tkbuf_sz) static
Definition at line 9233 of file scan.c.
References astb, ASTB::astfil, CARDB_SIZE, CNULL, curr_line, error(), HDRSTACK::fname, gbl, hdr_level, hdr_stack, i, isblank, isdig, p, sccrelal(), tkbuf, tkbuf_sz, tkp, and TRUE.
Referenced by _rd_token(), _read_token(), get_named_stmtyp(), and get_src_line().
_rd_token()
static int _rd_token (INT * tknv) static
Definition at line 9286 of file scan.c.
References _rd_tkline(), _restore_state(), B_FUNC_FOUND, B_RPAREN_FOUND, bind_state, currCol, DBGBIT, SCN::directive, SCN::end_program_unit, FLANG_FALLTHROUGH, gbl, get_num(), getcon(), gethollerith(), getstring(), getsym(), hex_to_i(), i, SCN::id, SEM::interface, kind, len, SCN::name, num, SCN::options, p, par_depth, q, SCM_FIRST, SCM_IDENT, SCM_IF, scmode, scn, sem, SCN::stmtyp, TK_IDENT, TK_LPAREN, TK_RPAREN, tkbuf, tkbuf_sz, tkntyp, tknval, tkp, TRUE, and val.
Referenced by _read_token().
_read_token()
static int _read_token (INT * tknv) static
HACK – don't check for multiple defs if the label was moved from a host's end statement to its CONTAINS statement. SEE semant.c:/sem.end_host_labno/
Definition at line 9087 of file scan.c.
References _rd_tkline(), _rd_token(), astb, ASTB::astfil, CNULL, curr_line, SCN::currlab, DBGBIT, declref(), errlabel(), FALSE, fe_restore_state(), FIH_FULLNAME, SEM::flabels, FR_B_HDR, FR_B_INCL, FR_E_HDR, FR_E_INCL, FR_END, FR_LABEL, FR_LINENO, FR_PRAGMA, FR_SRC, FR_STMT, FR_TOKEN, gbl, get_num(), get_token(), getsymf(), hdr_level, i, incl_level, SCN::is_hpf, lineno, NOSYM, p_pragma(), par_depth, read_line(), SCM_FIRST, scmode, scn, sem, SCN::stmtyp, SYMNAME, tkbuf, tkbuf_sz, tkp, TRUE, void(), and SEM::which_pass.
_readln()
static char * _readln (int mx_len, LOGICAL len_err) static
Definition at line 1549 of file scan.c.
References c, cardb, CNULL, curr_fd, curr_line, error(), FALSE, fclose(), flg, gbl, i, incl_level, isblank, long_pragma_candidate, NULL, p, q, FLG::standard, and TRUE.
Referenced by ff_read_card(), and read_card().
_restore_state()
static void _restore_state (void) static
Definition at line 8739 of file scan.c.
Referenced by _rd_token(), and fe_restore_state().
_write_token()
static void _write_token (int tk, INT ctkv) static
Definition at line 8762 of file scan.c.
References astb, ASTB::astfil, CNULL, CONVAL2G, currc, currCol, SCN::directive, error(), FLANG_FALLTHROUGH, FR_TOKEN, gbl, SCN::id, leadCount, len, STB::n_base, SCN::name, SCN::options, p, scn, stb, stmtb, string_length(), strlen(), SYMNAME, TK_IDENT, and type.
Referenced by _get_token().
add_headerfile()
void add_headerfile (const char * fname_buff, int cl, int includedir)
Definition at line 1383 of file scan.c.
References addfile(), cl, curr_line, FIHB::currfindex, FIH_FULLNAME, FIH_PARENT, fihb, HDRSTACK::findex, fname, HDRSTACK::fname, FR_B_HDR, FR_E_HDR, gbl, hdr_level, hdr_stack, hdr_stacksz, in_include, HDRSTACK::lineno, NEED, put_include(), and XBIT.
Referenced by ff_get_stmt(), get_stmt(), line_directive(), push_include(), and scan_include().
alpha()
static void alpha (void) static
Definition at line 4381 of file scan.c.
References acb_depth, B_FUNC_FOUND, B_NONE, B_RESULT_FOUND, B_RPAREN_FOUND, bind_state, SEM::block_scope, c, CARDB_SIZE, CH_FMTSTR, CH_HOLLERITH, CH_IMPLP, CH_IMPRP, CH_IOLP, CH_STRING, CNULL, count, cp, currc, double_type(), end_module(), SCN::end_program_unit, eos, error(), ERROR_STOP, exp_ac, exp_attr, exp_comma, exp_equal, exp_ptr_assign, FALSE, FLANG_FALLTHROUGH, flg, follow_attr, formatkw, gbl, get_fmtstr(), get_id_name(), SCN::id, SEM::in_enum, integer_only, SEM::interface, interr(), iokw, is_doconcurrent, is_freeform, is_ident(), is_keyword(), is_next_char(), iscsym, isdig, isident, k, kernel_kw, keyword(), MAXIDLEN, SEM::mod_cnt, SCN::name, NEED, normalkw, NOSYM, SCN::options, options_sz, par1_attr, par_depth, parallelkw, past_equal, SEM::pgphase, PHASE_EXEC, PHASE_INIT, PHASE_SPEC, reset_past_equal, SCM_ALLOC, SCM_BIND, SCM_DEFINED_IO, SCM_DOLAB, SCM_DONEXT, SCM_FIRST, SCM_FORMAT, SCM_FUNCTION, SCM_GENERIC, SCM_GOTO, SCM_ID_ATTR, SCM_IDENT, SCM_IF, SCM_IMPLICIT, SCM_INTERFACE, SCM_IO, SCM_KERNEL, SCM_LOCALITY, SCM_LOOKFOR_OPERATOR, SCM_NEXTIDENT, SCM_OPERATOR, SCM_PAR, SCM_PROCEDURE, SCM_TO, SCM_TYPEIS, scmode, scn, seen_implp, sem, sig_blanks, FLG::standard, SCN::stmtyp, strlen(), TK_IDENT, TKF_ARRAY, TKF_DOCONCURRENT, TKF_DOUBLE, TKF_DOWHILE, TKF_GO, TKF_NO, TKF_SELECT, tkntyp, tknval, TRUE, SEM::type_mode, and XBIT.
Referenced by _get_token(), ENTF90(), and mmul().
btodi()
static int btodi (char * s, int l, INT * num) static
Definition at line 6966 of file scan.c.
References c, end, i, j, k, num, and s.
Referenced by get_nondec(), and get_prefixed_int().
char_to_text()
static void char_to_text (int ch) static
Definition at line 6352 of file scan.c.
References b, c, flg, fmt_putchar(), fmt_putstr(), FLG::standard, and XBIT.
Referenced by get_fmtstr().
check_ccon()
static void check_ccon (void) static
NOTE: "name" includes parens
Definition at line 7002 of file scan.c.
References assert, c, cngcon(), CONVAL2G, currc, DT_CMPLX, DT_DBLE, STB::dt_real, DTY, get_number(), getcon(), idx, interr(), is_freeform, SCN::is_hpf, isdig, isident, num, p, par_depth, putsname(), rdx, SCM_CHEVRON, SCM_IDENT, SCM_IF, SCM_LOOKFOR_OPERATOR, scmode, scn, scnerrfg, stb, stmtb, TK_LPAREN, tkntyp, tknval, TY_DBLE, STB::user, val, xdble(), xdtoq(), and xftoq().
Referenced by _get_token().
check_continuation()
static void check_continuation (int lineno) static
Definition at line 9579 of file scan.c.
References CNULL, error(), SCN::is_hpf, is_kernel, is_mem, is_pgi, is_ppragma, is_sgi, is_smp, lineno, scn, sentinel, SL_KERNEL, SL_MEM, SL_OMP, SL_PGI, and SL_SGI.
Referenced by ff_get_noncomment(), and get_stmt().
check_pgi_pragma()
static int check_pgi_pragma (char * beg) static
Definition at line 1938 of file scan.c.
References c, CT_PPRAGMA, CT_PRAGMA, is_ident(), iswhite, keyword(), len, ppragma_kw, SCM_IDENT, scmode, scn, SCN::stmtyp, tkntyp, and TRUE.
Referenced by ff_read_card(), and read_card().
check_pragma()
static int check_pragma (char * beg) static
Definition at line 1972 of file scan.c.
References c, CT_DEC, CT_FIXED, CT_FREE, CT_PPRAGMA, CT_PRAGMA, ic_strncmp(), is_ident(), is_lineblank(), iswhite, len, and TRUE.
Referenced by ff_read_card(), and read_card().
classify_ac_type()
static int classify_ac_type (void) static
Definition at line 4313 of file scan.c.
References c, cp, currc, is_digit_string(), is_ident(), and iswhite.
Referenced by _get_token().
classify_dec()
static int classify_dec (void) static
Definition at line 4029 of file scan.c.
References c, CNULL, cp, currc, deckw, error(), FLANG_FALLTHROUGH, gbl, is_ident(), iswhite, k, keyword(), SCM_IDENT, scmode, scn, SCN::stmtyp, tkntyp, and TRUE.
Referenced by _get_token().
classify_kernel_pragma()
static int classify_kernel_pragma (void) static
Definition at line 4259 of file scan.c.
References c, CNULL, cp, currc, error(), gbl, is_ident(), iswhite, kernel_kw, keyword(), SCM_IDENT, SCM_KERNEL, scmode, scn, SCN::stmtyp, tkntyp, and TRUE.
Referenced by _get_token().
classify_pgi_dir()
static int classify_pgi_dir (void) static
Definition at line 4204 of file scan.c.
References c, CNULL, cp, currc, error(), gbl, is_ident(), iswhite, keyword(), pgi_kw, SCM_ACCEL, SCM_IDENT, scmode, scn, SCN::stmtyp, tkntyp, and TRUE.
Referenced by _get_token().
classify_pgi_pragma()
static int classify_pgi_pragma (void) static
Definition at line 4155 of file scan.c.
References c, CNULL, cp, currc, error(), gbl, is_ident(), iswhite, keyword(), ppragma_kw, SCM_IDENT, scmode, scn, SCN::stmtyp, tkntyp, and TRUE.
Referenced by _get_token().
classify_pragma()
static int classify_pragma (void) static
Definition at line 4097 of file scan.c.
References c, CNULL, cp, currc, error(), gbl, is_ident(), iswhite, keyword(), pragma_kw, SCM_IDENT, scmode, scn, SCN::stmtyp, tkntyp, and TRUE.
Referenced by _get_token().
classify_smp()
static int classify_smp (void) static
Definition at line 2517 of file scan.c.
References c, CNULL, cp, currc, error(), FLANG_FALLTHROUGH, gbl, is_freeform, is_ident(), iswhite, k, keyword(), parbegkw, SCM_IDENT, SCM_PAR, scmode, scn, SCN::stmtyp, TKF_CANCELLATION, TKF_DISTPAR, TKF_ENDDISTPAR, TKF_TARGETENTER, TKF_TARGETEXIT, tkntyp, and TRUE.
Referenced by _get_token().
cmp()
static int cmp (const char * id, const char * kw, int * keylen) static
Definition at line 6118 of file scan.c.
References c, and first.
Referenced by __attribute__(), __fvd_acos_fma3(), __fvd_acos_fma3_256(), __fvd_asin_fma3(), __fvd_asin_fma3_256(), __rvs_log_fma3(), __rvs_log_fma3_256(), __tan_kernel(), _RTE_ba(), _sect(), _template(), cmp_acl(), inline_contig_check(), keyword(), mk_conformable_test(), and mk_poly_test().
contIndex()
static int contIndex (char * line) static
Parse a source line with comments/continuations/string literals and return the index of the last non-white space character of the source line.
Parameters
line is the source line that we are processing.
Returns
the index (an integer) of the last character in source line.
Definition at line 8934 of file scan.c.
References i, len, line, NULL, strlen(), trimContIdx(), and TRUE.
Referenced by get_src_line().
crunch()
static void crunch (void) static
Definition at line 2092 of file scan.c.
References c, card_count, CH_B, CH_HOLLERITH, CH_KSTRING, CH_NULLSTR, CH_O, CH_STRING, CH_UNDERSCORE, CH_X, CNULL, curr_line, delim, eos, error(), errwarn(), exp_attr, exp_comma, exp_equal, exp_ptr_assign, FALSE, ff_get_label(), FLANG_FALLTHROUGH, flg, follow_attr, gbl, get_cstring(), gethollerith(), getstring(), i, interr(), is_freeform, SCN::is_hpf, iscsym, isdig, isholl, isident, iswhite, kanji_prefix(), last_char, len, SCN::multiple_stmts, outptr, p, p_pragma(), par1_attr, pos, scn, scnerrfg, sig_blanks, sptr, FLG::standard, stmtb, stmtbafter, TRUE, FLG::ucase, upper_to_lower, and XBIT.
Referenced by _get_token().
do_dot()
static void do_dot (void) static
Definition at line 7219 of file scan.c.
References cp, currc, DT_LOG, gbl, get_kind_id(), get_kind_value(), get_number(), getcon(), is_ident(), isdig, keyword(), keyword_idx, kind_id, len, logicalkw, lookupsym(), refocsym(), SCFTN_FALSE, SCFTN_TRUE, SCM_FORMAT, SCM_OPERATOR, scmode, select_kind(), sptr, t2, tkntyp, tknval, TRUE, TY_LOG, and val.
Referenced by _get_token().
double_type()
static int double_type (char * ip, int * p_idlen) static
Definition at line 9628 of file scan.c.
References is_freeform, is_ident(), and k.
Referenced by alpha().
fe_init()
void fe_init (void)
Definition at line 8693 of file scan.c.
References assert, astb, ASTB::astfil, and fe_state.
Referenced by parser().
fe_restart()
void fe_restart (void)
Definition at line 8715 of file scan.c.
References assert, astb, ASTB::astfil, DBGBIT, dinit_end(), FALSE, fe_state, gbl, and TRUE.
Referenced by parser().
fe_restore_state()
void fe_restore_state (void)
Definition at line 8747 of file scan.c.
References _restore_state(), assert, astb, ASTB::astfil, SCM_FIRST, scmode, sem, and SEM::which_pass.
Referenced by _read_token().
fe_save_state()
void fe_save_state (void)
Definition at line 8709 of file scan.c.
References astb, ASTB::astfil, and fe_state.
Referenced by semant1().
ff_check_stmtb()
static void ff_check_stmtb (void) static
Definition at line 9560 of file scan.c.
References card_count, CNULL, curr_line, error(), ff_state, flg, max_card, NULL, realloc_stmtb(), FLG::standard, and stmtb.
Referenced by ff_get_noncomment(), and ff_get_stmt().
ff_chk_pragma()
static void ff_chk_pragma (char * ppp) static
Definition at line 8527 of file scan.c.
References gbl, and p_pragma().
Referenced by ff_get_noncomment(), and ff_prescan().
ff_get_label()
static int ff_get_label (char * inp) static
Definition at line 8635 of file scan.c.
References atoxi(), c, cnt, CNULL, curr_line, SCN::currlab, declref(), errlabel(), error(), FALSE, SEM::flabels, FR_LABEL, gbl, getsymf(), isdig, iswhite, SCN::labno, NOSYM, NULL, put_astfil(), scn, sem, SYMNAME, and SEM::which_pass.
Referenced by crunch().
ff_get_noncomment()
static void ff_get_noncomment (char * inptr) static
Definition at line 8555 of file scan.c.
References c, card_count, card_type, cardb, check_continuation(), CNULL, CT_COMMENT, CT_CONTINUATION, CT_DIRECTIVE, CT_INITIAL, CT_KERNEL, CT_LINE, CT_MEM, CT_NONE, CT_PGI, CT_SMP, curr_line, DBGBIT, error(), ff_check_stmtb(), ff_chk_pragma(), ff_read_card(), FLANG_FALLTHROUGH, flg, gbl, iswhite, line_directive(), FLG::list, list_line(), list_now, p, printbuff, put_astfil(), and TRUE.
Referenced by ff_prescan().
ff_get_stmt()
static void ff_get_stmt (void) static
Definition at line 7819 of file scan.c.
References add_headerfile(), BCOPY, c, card_count, ISTACK::card_type, card_type, cardb, CARDB_SIZE, CH_PRAGMA, CNULL, CT_COMMENT, CT_CONTINUATION, CT_DEC, CT_DIRECTIVE, CT_EOF, CT_FIXED, CT_FREE, CT_INITIAL, CT_KERNEL, CT_LINE, CT_MEM, CT_NONE, CT_PGI, CT_PPRAGMA, CT_PRAGMA, CT_SMP, curr_fd, curr_line, FIHB::currfindex, DBGBIT, ISTACK::eof_flag, error(), errsev(), FALSE, ISTACK::fd, ff_check_stmtb(), ff_prescan(), ff_read_card(), ff_state, FIH_FULLNAME, fihb, ISTACK::findex, HDRSTACK::findex, finish(), ISTACK::first_char, first_char, FLANG_FALLTHROUGH, flg, ISTACK::fname, FR_E_INCL, gbl, get_stmt(), hdr_level, hdr_stack, in_include, incl_level, incl_stack, interr(), is_dec, is_doconcurrent, is_freeform, SCN::is_hpf, is_kernel, is_mem, is_pgi, is_ppragma, is_sgi, is_smp, isblank, leadCount, line_directive(), ISTACK::lineno, FLG::list, list_line(), ISTACK::list_now, list_now, list_page(), SEM::mod_cnt, SEM::mod_sym, no_crunch, p, printbuff, push_include(), put_astfil(), put_include(), put_lineno(), scn, sem, ISTACK::sentinel, sentinel, set_input_form(), SL_SGI, stmtb, SEM::submod_sym, TRUE, and write_card().
Referenced by get_stmt(), and set_input_form().
ff_prescan()
static void ff_prescan (void) static
Definition at line 8290 of file scan.c.
References assert, c, card_count, card_type, cardb, CNULL, CT_NONE, curr_line, error(), ff_chk_pragma(), ff_get_noncomment(), ff_state, first_char, flg, isdig, isholl, isident, kanji_prefix(), last_char, len, NULL, p, quote, FLG::standard, stmtb, TRUE, and XBIT.
Referenced by ff_get_stmt().
ff_read_card()
static int ff_read_card (void) static
Definition at line 8042 of file scan.c.
References _readln(), assert, b, c, cardb, check_pgi_pragma(), check_pragma(), CNULL, CT_COMMENT, CT_CONTINUATION, CT_DEC, CT_DIRECTIVE, CT_EOF, CT_INITIAL, CT_KERNEL, CT_LINE, CT_MEM, CT_PGI, CT_PPRAGMA, CT_PRAGMA, CT_SMP, curr_line, error(), FALSE, ff_state, first_char, first_line, fpp_, gbl, get_fn(), i, is_sgi, isblank, iswhite, long_pragma_candidate, MAX_COLS, MAX_DIRLEN, NULL, OPENMP, p, sentinel, SGIMP, SL_KERNEL, SL_MEM, SL_NONE, SL_OMP, SL_PGI, SL_SGI, TRUE, write_card(), XBIT, and XBIT_PCAST.
Referenced by ff_get_noncomment(), ff_get_stmt(), and set_input_form().
fmt_putchar()
static void fmt_putchar (int ch) static
Definition at line 6329 of file scan.c.
References fmtstr, NEED, and pos.
Referenced by char_to_text(), fmt_putstr(), and get_fmtstr().
fmt_putstr()
static void fmt_putstr (const char * str) static
Definition at line 6339 of file scan.c.
References fmt_putchar(), and str.
Referenced by char_to_text(), and get_fmtstr().
get_cstring()
static int get_cstring (char * p, int * len) static
Definition at line 6136 of file scan.c.
References c, errsev(), flg, getstring(), isodigit, len, n, p, scnerrfg, FLG::standard, TRUE, and XBIT.
Referenced by crunch().
get_fmtstr()
static int get_fmtstr (char * p) static
Definition at line 6210 of file scan.c.
References avl, b, c, CH_B, CH_HOLLERITH, CH_KSTRING, CH_NULLSTR, CH_O, CH_STRING, CH_UNDERSCORE, CH_X, char_to_text(), CONVAL2G, fmt_putchar(), fmt_putstr(), fmtstr, FREE, getstring(), is_freeform, iswhite, len, MERGE, STB::n_base, NEW, p, q, sptr, stb, string_length(), TRUE, and XBIT.
Referenced by alpha().
get_fn()
static void get_fn (void) static
Definition at line 1509 of file scan.c.
References cardb, gbl, getitem(), len, p, and XBIT.
Referenced by ff_read_card(), and read_card().
get_id_name()
static int get_id_name (char * id, int idlen) static
Definition at line 5898 of file scan.c.
References SCN::avl, SCN::id, SCN::name, NEED, p, scn, and SCN::size.
Referenced by alpha().
get_kind_id()
static int get_kind_id (char * ip) static
Definition at line 5992 of file scan.c.
References atoxi(), DT_ISINT, error(), gbl, getcon(), getsym(), is_digit_string(), is_ident(), kind_id, num, STB::ovclass, stb, SYMNAME, and void().
Referenced by do_dot(), and get_number().
get_kind_value()
static INT get_kind_value (int knd) static
Definition at line 6040 of file scan.c.
References assert, cngcon(), CNULL, CONVAL2G, DT_ISINT, error(), gbl, interr(), and SYMNAME.
Referenced by do_dot(), and get_number().
get_named_stmtyp()
int get_named_stmtyp (void)
Definition at line 9459 of file scan.c.
References _rd_tkline(), assert, astb, ASTB::astfil, file_pos, FR_TOKEN, get_num(), i, TK_COLON, tkbuf, and tkbuf_sz.
Referenced by semant1().
get_nondec()
static void get_nondec (int radix) static
Definition at line 6704 of file scan.c.
References atoxi(), btodi(), CERROR, cp, currc, gbl, getcon(), htodi(), otodi(), RADIX16_FMT_ERR, RADIX2_FMT_ERR, RADIX8_FMT_ERR, tkntyp, tknval, and val.
Referenced by _get_token(), and get_number().
get_num()
static int get_num (int radix) static
Definition at line 9504 of file scan.c.
References atoxi(), p, tkp, val, and void().
Referenced by _rd_token(), _read_token(), and get_named_stmtyp().
get_number()
static void get_number (int cplxno) static
Definition at line 6398 of file scan.c.
References assert, atosi32(), atoxd(), atoxf(), atoxi64(), atoxq(), c, CERROR, CNULL, cp, currc, DT_DBLE, DT_INT, STB::dt_real, DT_REAL, DTY, error(), errsev(), FALSE, flg, gbl, get_kind_id(), get_kind_value(), get_nondec(), get_prefixed_int(), getcon(), integer_only, interr(), isdig, kind, kind_id, len, num, p, putsname(), SCM_DOLAB, SCM_FORMAT, scmode, scnerrfg, select_kind(), sptr, FLG::standard, stb, SYMNAME, tkntyp, tknval, TRUE, TY_DBLE, TY_INT, TY_QUAD, TY_REAL, STB::user, and XBIT.
Referenced by _get_token(), check_ccon(), and do_dot().
get_prefixed_int()
static int get_prefixed_int (int radix) static
Definition at line 6793 of file scan.c.
References atosi32(), atoxi(), atoxi64(), btodi(), CERROR, CNULL, cp, currc, error(), flg, gbl, getcon(), htodi(), interr(), isdig, ishex, isodigit, otodi(), FLG::standard, tkntyp, tknval, val, and XBIT.
Referenced by _get_token(), and get_number().
get_src_line()
char * get_src_line (int line, char ** src_file, int col, int * srcCol, int * contNo)
get the post-processed source line in the current source file.
Parameters
line is the desired source line number.
src_file is used to store a copy of the source filename that the line number is associated with. It could be different from gbl.curr_file. If src_file is NULL, then this parameter is ignored. Caller is responsible to free the memory that src_file points to.
col is the column number associated with the token in the source line. It is usually needed if line has continuators.
srcCol is the adjusted column number for the current source line. It may be different than col when the column is associated with a continued source line. This parameter is ignored if it is 0.
contNo is greater than zero when source line is a continuation of the source line specified in line.
Returns
the source line associated with line. Result is NULL if line not found in source file. Caller is responsible to free the memory allocated for the result.
Definition at line 8994 of file scan.c.
References _rd_tkline(), astb, ASTB::astfil, col, contIndex(), curr_line, currCol, FR_LINENO, FR_SRC, FR_STMT, FREE, i, interr(), len, line, NULL, numLeadingSpaces(), offset, strlen(), and TRUE.
get_stmt()
static void get_stmt (void) static
Definition at line 1071 of file scan.c.
References add_headerfile(), atoxi(), BCOPY, body_len, c, card_count, ISTACK::card_type, card_type, cardb, CARDB_SIZE, cavail, CH_PRAGMA, check_continuation(), CNULL, CT_COMMENT, CT_CONTINUATION, CT_DEC, CT_DIRECTIVE, CT_END, CT_EOF, CT_FIXED, CT_FREE, CT_INITIAL, CT_KERNEL, CT_LINE, CT_MEM, CT_NONE, CT_PGI, CT_PPRAGMA, CT_PRAGMA, CT_SMP, curr_fd, curr_line, FIHB::currfindex, SCN::currlab, DBGBIT, declref(), ISTACK::eof_flag, errlabel(), error(), errsev(), FALSE, ISTACK::fd, ff_get_stmt(), FIH_FULLNAME, fihb, ISTACK::findex, HDRSTACK::findex, finish(), ISTACK::first_char, first_char, SEM::flabels, FLANG_FALLTHROUGH, flg, ISTACK::fname, FR_E_INCL, FR_LABEL, gbl, getsymf(), hdr_level, hdr_stack, in_include, incl_level, incl_stack, interr(), is_dec, is_doconcurrent, is_freeform, SCN::is_hpf, is_kernel, is_mem, is_pgi, is_ppragma, is_sgi, is_smp, isblank, isdig, kanji_len(), SCN::labno, last_char, lbuff, line_directive(), lineno, ISTACK::lineno, FLG::list, list_line(), ISTACK::list_now, list_now, list_page(), max_card, SEM::mod_cnt, SEM::mod_sym, no_crunch, NOSYM, NULL, p, printbuff, push_include(), put_astfil(), put_include(), put_lineno(), read_card(), realloc_stmtb(), scn, sem, ISTACK::sentinel, sentinel, set_input_form(), SL_SGI, FLG::standard, stmtb, SEM::submod_sym, SYMNAME, TRUE, SEM::which_pass, write_card(), and XBIT.
Referenced by ff_get_stmt(), and set_input_form().
get_token()
int get_token (INT * tknv)
Definition at line 523 of file scan.c.
References p_get_token, sem, and SEM::which_pass.
Referenced by _read_token().
getCurrColumn()
int getCurrColumn (void)
Definition at line 9280 of file scan.c.
References currCol.
Referenced by _parser().
getindex()
static int getindex (struct c * table, int num_elem, char * string) static
Definition at line 7745 of file scan.c.
References i, len, strlen(), and table.
Referenced by scan_options().
hex_to_i()
static int hex_to_i (int c) static
Definition at line 6894 of file scan.c.
Referenced by _rd_token(), and htodi().
htodi()
static int htodi (char * s, int l, INT * num) static
Definition at line 6864 of file scan.c.
References end, hex_to_i(), i, j, k, num, and s.
Referenced by get_nondec(), and get_prefixed_int().
ic_strncmp()
static int ic_strncmp (const char * str, const char * pattern) static
Definition at line 2039 of file scan.c.
References i, n, str, and strlen().
Referenced by check_pragma().
ill_char()
static void ill_char (int ch) static
Definition at line 1051 of file scan.c.
References c, CNULL, error(), and gbl.
Referenced by _get_token().
init_ktable()
static void init_ktable (KTABLE * ktable) static
Definition at line 5864 of file scan.c.
References base, ERR_Fatal, KTABLE::first, i, interrf(), KTABLE::kcount, KTABLE::kwds, and KTABLE::last.
Referenced by scan_init().
is_digit_string()
static int is_digit_string (char * ip) static
Definition at line 5966 of file scan.c.
References c, count, isdig, and TRUE.
Referenced by classify_ac_type(), and get_kind_id().
is_ident()
static int is_ident (char * ip) static
Definition at line 5939 of file scan.c.
References c, count, iscsym, isident, and TRUE.
Referenced by _get_token(), alpha(), check_pgi_pragma(), check_pragma(), classify_ac_type(), classify_dec(), classify_kernel_pragma(), classify_pgi_dir(), classify_pgi_pragma(), classify_pragma(), classify_smp(), do_dot(), double_type(), and get_kind_id().
is_keyword()
static LOGICAL is_keyword (char * id, int idlen, const char * kwd) static
Definition at line 5920 of file scan.c.
References FALSE, is_freeform, len, strlen(), and TRUE.
Referenced by alpha().
is_lineblank()
static LOGICAL is_lineblank (char * start) static
Definition at line 2057 of file scan.c.
References c, FALSE, iswhite, p, start, and TRUE.
Referenced by check_pragma().
is_next_char()
static LOGICAL is_next_char (char * s, int ch) static
Definition at line 9615 of file scan.c.
References FALSE, s, and TRUE.
Referenced by alpha().
keyword()
static int keyword (char * id, KTABLE * ktable, int * keylen, LOGICAL exact) static
Definition at line 6078 of file scan.c.
References base, cmp(), KTABLE::first, keyword_idx, KTABLE::kwds, KTABLE::last, and p.
Referenced by add_action(), alpha(), check_pgi_pragma(), chk_struct_constructor(), classify_dec(), classify_kernel_pragma(), classify_pgi_dir(), classify_pgi_pragma(), classify_pragma(), classify_smp(), do_dot(), execute_actions_for_keyword(), and getkeyword().
line_directive()
static void line_directive (void) static
Definition at line 1441 of file scan.c.
References add_headerfile(), cardb, CARDB_SIZE, cl, CNULL, curr_line, error(), FALSE, HDRSTACK::fname, gbl, hdr_level, hdr_stack, in_include, isblank, isdig, p, printbuff, put_astfil(), TRUE, and write_card().
Referenced by ff_get_noncomment(), ff_get_stmt(), and get_stmt().
numLeadingSpaces()
static int numLeadingSpaces (char * line) static
Definition at line 8910 of file scan.c.
References i, line, and NULL.
Referenced by get_src_line().
otodi()
static int otodi (char * s, int l, INT * num) static
Definition at line 6914 of file scan.c.
References end, i, num, and s.
Referenced by get_nondec(), and get_prefixed_int().
p_pragma()
void p_pragma (char * pg, int pline)
Definition at line 336 of file pragma.c.
Referenced by _read_token(), crunch(), and ff_chk_pragma().
parse_init()
void parse_init (void)
Definition at line 411 of file parser.c.
Referenced by _get_token(), and _parser().
push_include()
static void push_include (char * p) static
Definition at line 7307 of file scan.c.
References add_headerfile(), c, ISTACK::card_type, CNULL, CT_NONE, curr_fd, curr_line, DIRSINCS, DIRWORK, ISTACK::eof_flag, errfatal(), error(), FALSE, ISTACK::fd, FILE, ISTACK::findex, HDRSTACK::findex, flg, ISTACK::fname, HDRSTACK::fname, fndpath(), FR_B_INCL, gbl, getitem(), hdr_level, hdr_stack, FLG::idir, in_include, incl_level, incl_stack, incl_stacksz, ISTACK::is_freeform, is_freeform, ISTACK::lineno, FLG::list, list_line(), ISTACK::list_now, list_now, MAX_IDEPTH, MAX_PATHNAME_LEN, NEED, NULL, p, put_include(), ISTACK::sentinel, SL_NONE, FLG::stdinc, tmpfile(), TRUE, and XBIT.
Referenced by ff_get_stmt(), and get_stmt().
put_astfil()
static void put_astfil (int type, char * line, LOGICAL newline) static
Definition at line 7774 of file scan.c.
References astb, ASTB::astfil, CNULL, error(), line, NULL, and type.
Referenced by _get_token(), ff_get_label(), ff_get_noncomment(), ff_get_stmt(), get_stmt(), line_directive(), and scan_init().
put_include()
static void put_include (int type, int findex) static
Definition at line 7801 of file scan.c.
References astb, ASTB::astfil, CNULL, error(), and type.
Referenced by add_headerfile(), ff_get_stmt(), get_stmt(), push_include(), and scan_include().
put_lineno()
static void put_lineno (int lineno) static
Definition at line 7788 of file scan.c.
References astb, ASTB::astfil, CNULL, error(), FR_LINENO, gbl, lineno, and type.
Referenced by ff_get_stmt(), and get_stmt().
read_card()
static int read_card (void) static
Definition at line 1606 of file scan.c.
References _readln(), assert, b, c, cardb, CARDB_SIZE, check_pgi_pragma(), check_pragma(), CNULL, CT_COMMENT, CT_CONTINUATION, CT_DEC, CT_DIRECTIVE, CT_END, CT_EOF, CT_INITIAL, CT_KERNEL, CT_LINE, CT_MEM, CT_PGI, CT_PPRAGMA, CT_PRAGMA, CT_SMP, curr_line, FLG::dlines, error(), FLG::extend_source, FALSE, first_char, first_line, flg, HDRSTACK::fname, fpp_, gbl, get_fn(), hdr_level, hdr_stack, i, is_sgi, isblank, iswhite, MAX_DIRLEN, NULL, OPENMP, p, save_extend_ch, sentinel, SGIMP, SL_KERNEL, SL_MEM, SL_NONE, SL_OMP, SL_PGI, SL_SGI, TRUE, write_card(), XBIT, and XBIT_PCAST.
Referenced by get_stmt(), and set_input_form().
realloc_stmtb()
static void realloc_stmtb (void) static
Definition at line 9537 of file scan.c.
References CNULL, error(), last_char, max_card, MAX_COLS, NULL, sccrelal(), stmtb, stmtbafter, and stmtbefore.
Referenced by ff_check_stmtb(), and get_stmt().
scan_fini()
void scan_fini (void)
Compilation is finished - deallocate storage, close files, etc.
Definition at line 484 of file scan.c.
References astb, ASTB::astfil, SCN::directive, fclose(), FREE, SCN::id, incl_stack, last_char, SCN::name, SCN::options, scn, stmtbafter, stmtbefore, and tkbuf.
Referenced by finish().
scan_include()
void scan_include (char * str)
Definition at line 7395 of file scan.c.
References add_headerfile(), BCOPY, c, ISTACK::card_type, card_type, cardb, CARDB_SIZE, CNULL, curr_fd, curr_line, dirnam(), dirname, DIRSINCS, DIRWORK, ISTACK::eof_flag, errfatal(), error(), FALSE, ISTACK::fd, FILE, ISTACK::findex, HDRSTACK::findex, ISTACK::first_char, first_char, flg, ISTACK::fname, HDRSTACK::fname, fndpath(), FR_B_INCL, gbl, getitem(), hdr_level, hdr_stack, FLG::idir, in_include, incl_level, incl_stack, incl_stacksz, ISTACK::is_freeform, is_freeform, ISTACK::lineno, FLG::list, list_line(), ISTACK::list_now, list_now, MAX_IDEPTH, MAX_PATHNAME_LEN, SEM::mod_cnt, NEED, NULL, p, put_include(), q, sem, ISTACK::sentinel, sentinel, FLG::stdinc, str, tmpfile(), TRUE, SEM::which_pass, and XBIT.
Referenced by semant1().
scan_init()
void scan_init (FILE * fd)
Initialize Scanner. This routine is called once at the beginning of execution.
Parameters
fd file descriptor for main input source file
Definition at line 374 of file scan.c.
References _CS, _HO, astb, ASTB::astfil, SCN::avl, body_len, card_type, CARDB_SIZE, CNULL, ctable, curr_fd, curr_line, currc, currCol, DBGBIT, deckw, SCN::directive, directive_sz, errfatal(), error(), FLG::extend_source, FALSE, fd, first_line, flg, formatkw, FR_SRC, FLG::freeform, gbl, hdr_level, hdr_stack, hdr_stacksz, SCN::id, in_include, incl_level, incl_stack, incl_stacksz, init_ktable(), INIT_LPS, iokw, kernel_kw, last_char, leadCount, FLG::list, list_now, logicalkw, max_card, MAX_COLS, SCN::name, NEW, normalkw, NULL, SCN::options, options_sz, parallelkw, parbegkw, pgi_kw, ppragma_kw, pragma_kw, put_astfil(), sccalloc(), scn, set_input_form(), SCN::size, stmtb, stmtbafter, stmtbefore, tkbuf, tkbuf_sz, tmpfile(), TRUE, and XBIT.
Referenced by init().
scan_opt_restore()
void scan_opt_restore (void)
Definition at line 7561 of file scan.c.
References body_len, FLG::extend_source, FALSE, flg, FLG::i4, options_seen, FLG::recursive, save_flg, FLG::standard, and FLG::x.
Referenced by reinit().
scan_options()
void scan_options (void)
Definition at line 7577 of file scan.c.
References body_len, card_type, cardb, CNULL, CT_DIRECTIVE, DBGBIT, DT_INT, error(), FLG::extend_source, FALSE, flg, gbl, getindex(), FLG::i4, implicit_int(), NSWDS, SCN::options, options_seen, p, FLG::recursive, save_extend_ch, save_flg, scn, FLG::standard, SW_CHECK, SW_EXTEND, SW_GFLOAT, SW_I4, SW_NOCHECK, SW_NOEXTEND, SW_NOGFLOAT, SW_NOI4, SW_NORECURS, SW_NOREENTR, SW_NOSTANDARD, SW_RECURS, SW_REENTR, SW_STANDARD, swtchtab, symtab_nostandard(), symtab_standard(), TRUE, write_card(), and FLG::x.
Referenced by semant1().
scan_reset()
void scan_reset (void)
Lexical or syntactical error found, so re-initialize the Scanner so that next Fortran statement will be processed.
Definition at line 473 of file scan.c.
References currc, currCol, SCN::end_program_unit, FALSE, leadCount, NULL, and scn.
Referenced by parse_init().
set_input_form()
static void set_input_form (LOGICAL free) static
Definition at line 507 of file scan.c.
References FALSE, ff_get_stmt(), ff_read_card(), get_stmt(), is_freeform, p_get_stmt, p_read_card, read_card(), and TRUE.
Referenced by ff_get_stmt(), get_stmt(), and scan_init().
trimContIdx()
static int trimContIdx (char * line) static
trim white space of source line that has continuations and return the index of the last character in the source line.
This function is called by contIndex().
Parameters
line is the source line we are processing.
Returns
the index (an integer) of the last character in the source line.
Definition at line 8891 of file scan.c.
References len, line, NULL, p, and strlen().
Referenced by contIndex().
write_card()
static void write_card (void) static
Definition at line 1912 of file scan.c.
References cardb, curr_line, incl_level, len, and printbuff.
Referenced by ff_get_stmt(), ff_read_card(), get_stmt(), line_directive(), read_card(), and scan_options().
Variable Documentation
acb_depth
int acb_depth static
Definition at line 303 of file scan.c.
Referenced by _get_token(), and alpha().
amper_ptr
char* amper_ptr
Definition at line 335 of file scan.c.
bind_state
int bind_state = B_NONE static
Definition at line 171 of file scan.c.
Referenced by _get_token(), _rd_token(), and alpha().
body_len
int body_len static
Definition at line 309 of file scan.c.
Referenced by get_stmt(), scan_init(), scan_opt_restore(), and scan_options().
card_count
int card_count static
Definition at line 231 of file scan.c.
Referenced by crunch(), ff_check_stmtb(), ff_get_noncomment(), ff_get_stmt(), ff_prescan(), and get_stmt().
card_type
int card_type static
Definition at line 221 of file scan.c.
Referenced by ff_get_noncomment(), ff_get_stmt(), ff_prescan(), get_stmt(), scan_include(), scan_init(), and scan_options().
cardb
char cardb[CARDB_SIZE] static
Definition at line 210 of file scan.c.
Referenced by _readln(), ff_get_noncomment(), ff_get_stmt(), ff_prescan(), ff_read_card(), get_fn(), get_stmt(), line_directive(), read_card(), scan_include(), scan_options(), and write_card().
cavail
char* cavail
Definition at line 333 of file scan.c.
Referenced by get_stmt().
curr_fd
FILE* curr_fd static
Definition at line 175 of file scan.c.
Referenced by _readln(), ff_get_stmt(), get_stmt(), push_include(), scan_include(), and scan_init().
curr_line
int curr_line static
Definition at line 208 of file scan.c.
Referenced by _rd_tkline(), _read_token(), _readln(), add_headerfile(), crunch(), ff_check_stmtb(), ff_get_label(), ff_get_noncomment(), ff_get_stmt(), ff_prescan(), ff_read_card(), get_src_line(), get_stmt(), line_directive(), push_include(), read_card(), scan_include(), scan_init(), and write_card().
currc
char* currc static
Definition at line 234 of file scan.c.
Referenced by _get_token(), _write_token(), alpha(), check_ccon(), classify_ac_type(), classify_dec(), classify_kernel_pragma(), classify_pgi_dir(), classify_pgi_pragma(), classify_pragma(), classify_smp(), do_dot(), get_nondec(), get_number(), get_prefixed_int(), scan_init(), and scan_reset().
currCol
int currCol static
Definition at line 237 of file scan.c.
Referenced by _rd_token(), _write_token(), get_src_line(), getCurrColumn(), scan_init(), and scan_reset().
directive_sz
int directive_sz static
Definition at line 243 of file scan.c.
Referenced by _get_token(), and scan_init().
eos
char* eos static
Definition at line 235 of file scan.c.
Referenced by alpha(), and crunch().
exp_ac
LOGICAL exp_ac static
Definition at line 252 of file scan.c.
Referenced by _get_token(), alpha(), and eval_ilm().
exp_attr
LOGICAL exp_attr static
Definition at line 250 of file scan.c.
Referenced by _get_token(), alpha(), and crunch().
exp_comma
LOGICAL exp_comma static
Definition at line 247 of file scan.c.
Referenced by alpha(), and crunch().
exp_dtvlist
LOGICAL exp_dtvlist static
Definition at line 253 of file scan.c.
Referenced by _get_token().
exp_equal
LOGICAL exp_equal static
Definition at line 248 of file scan.c.
Referenced by alpha(), and crunch().
exp_ptr_assign
LOGICAL exp_ptr_assign static
Definition at line 249 of file scan.c.
Referenced by alpha(), and crunch().
extend_source
int extend_source
Definition at line 7552 of file scan.c.
struct { ... } fe_state
Referenced by fe_init(), fe_restart(), and fe_save_state().
struct { ... } ff_state
Referenced by ff_check_stmtb(), ff_get_stmt(), ff_prescan(), and ff_read_card().
file_pos
long file_pos
Definition at line 8689 of file scan.c.
Referenced by annomod_initx(), get_named_stmtyp(), and rw_dinit_state().
first_char
char* first_char static
Definition at line 217 of file scan.c.
Referenced by ff_get_stmt(), ff_prescan(), ff_read_card(), get_stmt(), read_card(), and scan_include().
first_line
LOGICAL first_line static
Definition at line 209 of file scan.c.
Referenced by ff_read_card(), read_card(), and scan_init().
struct { ... } fmtstr
Referenced by fmt_putchar(), and get_fmtstr().
follow_attr
LOGICAL follow_attr static
Definition at line 251 of file scan.c.
Referenced by _get_token(), alpha(), and crunch().
fpp_
LOGICAL fpp_ extern
Definition at line 516 of file main.c.
Referenced by ff_read_card(), init(), and read_card().
hdr_level
int hdr_level static
Definition at line 197 of file scan.c.
Referenced by _rd_tkline(), _read_token(), add_headerfile(), ff_get_stmt(), get_stmt(), line_directive(), push_include(), read_card(), scan_include(), and scan_init().
hdr_stack
HDRSTACK* hdr_stack = NULL static
Definition at line 206 of file scan.c.
Referenced by _rd_tkline(), add_headerfile(), ff_get_stmt(), get_stmt(), line_directive(), push_include(), read_card(), scan_include(), and scan_init().
hdr_stacksz
int hdr_stacksz static
Definition at line 198 of file scan.c.
Referenced by add_headerfile(), and scan_init().
i4
LOGICAL i4
Definition at line 7553 of file scan.c.
Referenced by __pmth_i_dpowi(), __pmth_i_qpowi(), __pmth_i_rpowi(), fw_writenum(), print_row(), and tablea().
in_include
LOGICAL in_include static
Definition at line 314 of file scan.c.
Referenced by add_headerfile(), ff_get_stmt(), get_stmt(), line_directive(), push_include(), scan_include(), and scan_init().
incl_level
int incl_level static
Definition at line 177 of file scan.c.
Referenced by _read_token(), _readln(), ff_get_stmt(), get_stmt(), push_include(), scan_include(), scan_init(), and write_card().
incl_stack
ISTACK* incl_stack = NULL static
Definition at line 195 of file scan.c.
Referenced by ff_get_stmt(), get_stmt(), push_include(), scan_fini(), scan_include(), and scan_init().
incl_stacksz
int incl_stacksz static
Definition at line 178 of file scan.c.
Referenced by push_include(), scan_include(), and scan_init().
integer_only
LOGICAL integer_only static
Definition at line 254 of file scan.c.
Referenced by _get_token(), alpha(), and get_number().
is_dec
LOGICAL is_dec static
Definition at line 262 of file scan.c.
Referenced by _get_token(), ff_get_stmt(), and get_stmt().
is_doconcurrent
bool is_doconcurrent static
Definition at line 266 of file scan.c.
Referenced by _get_token(), alpha(), ff_get_stmt(), and get_stmt().
is_freeform
LOGICAL is_freeform static
Definition at line 320 of file scan.c.
Referenced by alpha(), check_ccon(), classify_smp(), crunch(), double_type(), ff_get_stmt(), get_fmtstr(), get_stmt(), is_keyword(), push_include(), scan_include(), and set_input_form().
is_kernel
LOGICAL is_kernel static
Definition at line 267 of file scan.c.
Referenced by _get_token(), check_continuation(), ff_get_stmt(), get_stmt(), ll_create_device_function_from_type(), and ll_create_function().
is_mem
LOGICAL is_mem static
Definition at line 263 of file scan.c.
Referenced by _get_token(), check_continuation(), ff_get_stmt(), and get_stmt().
is_pgi
LOGICAL is_pgi static
Definition at line 265 of file scan.c.
Referenced by _get_token(), check_continuation(), ff_get_stmt(), and get_stmt().
is_ppragma
LOGICAL is_ppragma static
Definition at line 264 of file scan.c.
Referenced by _get_token(), check_continuation(), ff_get_stmt(), and get_stmt().
is_sgi
LOGICAL is_sgi static
Definition at line 259 of file scan.c.
Referenced by check_continuation(), ff_get_stmt(), ff_read_card(), get_stmt(), and read_card().
is_smp
LOGICAL is_smp static
Definition at line 258 of file scan.c.
Referenced by _get_token(), check_continuation(), ff_get_stmt(), and get_stmt().
keyword_idx
int keyword_idx static
Definition at line 356 of file scan.c.
Referenced by do_dot(), and keyword().
kind_id
int kind_id static
Definition at line 316 of file scan.c.
Referenced by do_dot(), get_kind_id(), and get_number().
last_char
int last_char = NULL static
Definition at line 229 of file scan.c.
Referenced by crunch(), ff_prescan(), get_stmt(), realloc_stmtb(), scan_fini(), and scan_init().
leadCount
int leadCount static
Definition at line 236 of file scan.c.
Referenced by _write_token(), ff_get_stmt(), scan_init(), and scan_reset().
len
int len
Definition at line 6205 of file scan.c.
Referenced by _get_token(), _rd_token(), _write_token(), check_pgi_pragma(), check_pragma(), contIndex(), crunch(), do_dot(), ff_prescan(), get_cstring(), get_fmtstr(), get_fn(), get_number(), get_src_line(), getindex(), is_keyword(), trimContIdx(), and write_card().
list_now
LOGICAL list_now static
Definition at line 214 of file scan.c.
Referenced by ff_get_noncomment(), ff_get_stmt(), get_stmt(), push_include(), scan_include(), and scan_init().
long_pragma_candidate
LOGICAL long_pragma_candidate static
Definition at line 268 of file scan.c.
Referenced by _readln(), and ff_read_card().
max_card
int max_card static
Definition at line 232 of file scan.c.
Referenced by ff_check_stmtb(), get_stmt(), realloc_stmtb(), and scan_init().
no_crunch
LOGICAL no_crunch static
Definition at line 312 of file scan.c.
Referenced by _get_token(), ff_get_stmt(), and get_stmt().
options_seen
int options_seen = FALSE static
Definition at line 7508 of file scan.c.
Referenced by scan_opt_restore(), and scan_options().
options_sz
int options_sz static
Definition at line 244 of file scan.c.
Referenced by alpha(), and scan_init().
outptr
char* outptr
Definition at line 334 of file scan.c.
Referenced by crunch().
p_get_stmt
void(* p_get_stmt) (void) (void) = get_stmt static
Definition at line 341 of file scan.c.
Referenced by set_input_form().
p_get_token
int(* p_get_token[])(INT *) (INT *) = {_get_token, _read_token} static
Definition at line 350 of file scan.c.
Referenced by get_token().
p_read_card
int(* p_read_card) (void) (void) = read_card static
Definition at line 342 of file scan.c.
Referenced by set_input_form().
par1_attr
LOGICAL par1_attr static
Definition at line 256 of file scan.c.
Referenced by _get_token(), alpha(), and crunch().
par_depth
int par_depth static
Definition at line 300 of file scan.c.
Referenced by _get_token(), _rd_token(), _read_token(), alpha(), and check_ccon().
past_equal
LOGICAL past_equal static
Definition at line 301 of file scan.c.
Referenced by _get_token(), and alpha().
printbuff
char printbuff[CARDB_SIZE] static
Definition at line 216 of file scan.c.
Referenced by ff_get_noncomment(), ff_get_stmt(), get_stmt(), line_directive(), and write_card().
recursive
LOGICAL recursive
Definition at line 7555 of file scan.c.
reset_past_equal
LOGICAL reset_past_equal static
Definition at line 302 of file scan.c.
Referenced by _get_token(), and alpha().
save_extend_ch
char save_extend_ch static
Definition at line 213 of file scan.c.
Referenced by read_card(), and scan_options().
struct { ... } save_flg
Referenced by scan_opt_restore(), and scan_options().
scmode
int scmode static
Definition at line 270 of file scan.c.
Referenced by _get_token(), _rd_token(), _read_token(), alpha(), check_ccon(), check_pgi_pragma(), classify_dec(), classify_kernel_pragma(), classify_pgi_dir(), classify_pgi_pragma(), classify_pragma(), classify_smp(), do_dot(), fe_restore_state(), and get_number().
scnerrfg
LOGICAL scnerrfg static
Definition at line 246 of file scan.c.
Referenced by _get_token(), check_ccon(), crunch(), get_cstring(), and get_number().
seen_implp
LOGICAL seen_implp static
Definition at line 318 of file scan.c.
Referenced by _get_token(), and alpha().
sentinel
int sentinel static
Definition at line 223 of file scan.c.
Referenced by check_continuation(), ff_get_stmt(), ff_read_card(), get_stmt(), read_card(), and scan_include().
sig_blanks
LOGICAL sig_blanks static
Definition at line 321 of file scan.c.
Referenced by _get_token(), alpha(), and crunch().
standard
LOGICAL standard
Definition at line 7554 of file scan.c.
stmtb
char* stmtb static
Definition at line 225 of file scan.c.
Referenced by _get_token(), _write_token(), check_ccon(), crunch(), ff_check_stmtb(), ff_get_stmt(), ff_prescan(), get_stmt(), realloc_stmtb(), and scan_init().
stmtbafter
char* stmtbafter = NULL static
Definition at line 228 of file scan.c.
Referenced by _get_token(), crunch(), realloc_stmtb(), scan_fini(), and scan_init().
stmtbefore
char* stmtbefore = NULL static
Definition at line 227 of file scan.c.
Referenced by _get_token(), realloc_stmtb(), scan_fini(), and scan_init().
str
char* str
Definition at line 6204 of file scan.c.
Referenced by __abort_sig_hand(), __fort_crecv(), __fort_csend(), __fort_print_vector(), __fort_psignal(), __fort_rbcst(), __fort_rbcstl(), __fort_recvl(), __fort_red_abort(), __fort_rrecv(), __fort_rrecvl(), __fort_rsend(), __fort_rsendl(), __fort_sendl(), __fort_strtol(), __fortio_eq_str(), __fortio_errinit(), __fortio_errinit03(), __fstr2cstr(), __INT8_T(), __INT_T(), __io_read(), __io_write(), _adjustl(), _adjustr(), _f90io_encode_fmt(), _f90io_pause(), _f90io_stop(), _makezero(), _repeat(), _trim(), arg_length(), broadcast(), ch_substring(), copy(), copy_in_abort(), copy_xfer_loop(), dinit_put_string(), dinit_read_string(), dump_buff(), emit_init(), ENT3F(), ENTCRF90(), ENTF90(), ENTFTN(), eval_adjustl(), eval_adjustr(), eval_repeat(), eval_trim(), exp_strcpy(), find_group(), fmt_putstr(), fprintf_str_esc_backslash(), Ftn_str_copy(), Ftn_str_copy_klen(), gathscat_abort(), get_line(), get_line1(), getcharconst(), getstraddr(), getstrconst(), getstrlen(), getstrlen64(), global_reduce_abort(), ic_strcmp(), ic_strncmp(), lenWithUnderscores(), ll_create_anon_struct_type(), ll_create_function_type(), ll_get_md_string(), ll_manage_strdup(), ll_override_type_string(), llutil_strdup(), make_def_op(), mangleUnderscores(), mk_comstr(), nan_or_infinite(), olap_recv(), olap_send(), print_and_check(), print_ast(), print_function_signature(), print_row(), put_fstring(), put_mem_string(), put_prefix(), put_skip(), put_string(), scan_include(), sem_err104(), semantio(), storechartmp(), strislen0(), strislen1(), sum_scatter_args(), and write_extern_inits().
swtchtab
struct c swtchtab[] static
Initial value:
= {
    {"check", SW_CHECK},
    {"extend_source", SW_EXTEND},
    {"f77", SW_STANDARD},
    {"g_floating", SW_GFLOAT},
    {"i4", SW_I4},
    {"nocheck", SW_NOCHECK},
    {"noextend_source", SW_NOEXTEND},
    {"nof77", SW_NOSTANDARD},
    {"nog_floating", SW_NOGFLOAT},
    {"noi4", SW_NOI4},
    {"norecursive", SW_NORECURS},
    {"noreentrant", SW_NOREENTR},
    {"nostandard", SW_NOSTANDARD},
    {"recursive", SW_RECURS},
    {"reentrant", SW_REENTR},
    {"standard", SW_STANDARD},
}
Definition at line 7531 of file scan.c.
Referenced by scan_options().
sz
int sz
Definition at line 6206 of file scan.c.
tkbuf
char* tkbuf = NULL static
Definition at line 239 of file scan.c.
Referenced by _rd_tkline(), _rd_token(), _read_token(), get_named_stmtyp(), scan_fini(), and scan_init().
tkbuf_sz
int tkbuf_sz static
Definition at line 241 of file scan.c.
Referenced by _rd_tkline(), _rd_token(), _read_token(), get_named_stmtyp(), and scan_init().
tkntyp
int tkntyp static
Definition at line 304 of file scan.c.
Referenced by _get_token(), _rd_token(), alpha(), check_ccon(), check_pgi_pragma(), classify_dec(), classify_kernel_pragma(), classify_pgi_dir(), classify_pgi_pragma(), classify_pragma(), classify_smp(), do_dot(), get_nondec(), get_number(), and get_prefixed_int().
tknval
INT tknval static
Definition at line 307 of file scan.c.
Referenced by _get_token(), _rd_token(), alpha(), check_ccon(), do_dot(), get_nondec(), get_number(), and get_prefixed_int().
tkp
char* tkp static
Definition at line 8873 of file scan.c.
Referenced by _rd_tkline(), _rd_token(), _read_token(), and get_num().
x7
int x7
Definition at line 7556 of file scan.c.
x70
int x70
Definition at line 7557 of file scan.c.