flang: scan.h File Reference
scan.h File Reference
data declarations for those items which are set by the scanner for use by the parser or semantic analyzer.
Classes
struct SCN
Macros
#define RADIX2_FMT_ERR(r, n) (r == 2 && (n > 64))
#define RADIX8_FMT_ERR(r, n, cp) (r == 8 && (n > 22 || (n == 22 && (*cp - '0' > 1))))
#define RADIX16_FMT_ERR(r, n) (r == 16 && (n > 16))
Enumerations
enum FR_TYPE {
FR_SRC = -1 , FR_B_INCL = -2 , FR_E_INCL = -3 , FR_END = -4 ,
FR_LINENO = -5 , FR_PRAGMA = -6 , FR_STMT = -7 , FR_B_HDR = -8 ,
FR_E_HDR = -9 , FR_LABEL = -98 , FR_TOKEN = -99
}
Functions
void scan_init (FILE *)
Initialize Scanner. This routine is called once at the beginning of execution.
void scan_reset (void)
Lexical or syntactical error found, so re-initialize the Scanner so that next Fortran statement will be processed.
void scan_fini (void)
Compilation is finished - deallocate storage, close files, etc.
int get_token (INT *)
void scan_include (char *)
void scan_opt_restore (void)
int get_named_stmtyp (void)
int getCurrColumn (void)
void scan_options (void)
void fe_save_state (void)
void fe_init (void)
void fe_restart (void)
char * get_src_line (int line, char **src_file, int col, int *srcCol, int *contNo)
get the post-processed source line in the current source file.
LOGICAL is_executable (int)
void parser (void)
Variables
SCN scn
Detailed Description
data declarations for those items which are set by the scanner for use by the parser or semantic analyzer.
Definition in file scan.h.
Macro Definition Documentation
RADIX16_FMT_ERR
#define RADIX16_FMT_ERR (r, n) (r == 16 && (n > 16))
Definition at line 15 of file scan.h.
RADIX2_FMT_ERR
#define RADIX2_FMT_ERR (r, n) (r == 2 && (n > 64))
Definition at line 13 of file scan.h.
RADIX8_FMT_ERR
#define RADIX8_FMT_ERR (r, n, cp) (r == 8 && (n > 22 || (n == 22 && (*cp - '0' > 1))))
Definition at line 14 of file scan.h.
Enumeration Type Documentation
FR_TYPE
enum FR_TYPE
Enumerator
FR_SRC
FR_B_INCL
FR_E_INCL
FR_END
FR_LINENO
FR_PRAGMA
FR_STMT
FR_B_HDR
FR_E_HDR
FR_LABEL
FR_TOKEN
Definition at line 47 of file scan.h.
Function Documentation
fe_init()
void fe_init (void)
Definition at line 8693 of file scan.c.
References assert, astb, ASTB::astfil, and fe_state.
Referenced by parser().
fe_restart()
void fe_restart (void)
Definition at line 8715 of file scan.c.
References assert, astb, ASTB::astfil, DBGBIT, dinit_end(), FALSE, fe_state, gbl, and TRUE.
Referenced by parser().
fe_save_state()
void fe_save_state (void)
Definition at line 8709 of file scan.c.
References astb, ASTB::astfil, and fe_state.
Referenced by semant1().
get_named_stmtyp()
int get_named_stmtyp (void)
Definition at line 9459 of file scan.c.
References _rd_tkline(), assert, astb, ASTB::astfil, file_pos, FR_TOKEN, get_num(), i, TK_COLON, tkbuf, and tkbuf_sz.
Referenced by semant1().
get_src_line()
char * get_src_line (int line, char ** src_file, int col, int * srcCol, int * contNo)
get the post-processed source line in the current source file.
Parameters
line is the desired source line number.
src_file is used to store a copy of the source filename that the line number is associated with. It could be different from gbl.curr_file. If src_file is NULL, then this parameter is ignored. Caller is responsible to free the memory that src_file points to.
col is the column number associated with the token in the source line. It is usually needed if line has continuators.
srcCol is the adjusted column number for the current source line. It may be different than col when the column is associated with a continued source line. This parameter is ignored if it is 0.
contNo is greater than zero when source line is a continuation of the source line specified in line.
Returns
the source line associated with line. Result is NULL if line not found in source file. Caller is responsible to free the memory allocated for the result.
Definition at line 8994 of file scan.c.
References _rd_tkline(), astb, ASTB::astfil, col, contIndex(), curr_line, currCol, FR_LINENO, FR_SRC, FR_STMT, FREE, i, interr(), len, line, NULL, numLeadingSpaces(), offset, strlen(), and TRUE.
get_token()
int get_token (INT * tknv)
Definition at line 523 of file scan.c.
References p_get_token, sem, and SEM::which_pass.
Referenced by _read_token().
getCurrColumn()
int getCurrColumn (void)
Definition at line 9280 of file scan.c.
References currCol.
Referenced by _parser().
is_executable()
LOGICAL is_executable (int tkntyp)
Definition at line 891 of file parser.c.
References is_declaration(), and tkntyp.
Referenced by semant1().
parser()
void parser (void)
Definition at line 60 of file parser.c.
References _parser(), DBGBIT, end_module(), errini(), FALSE, fe_init(), fe_restart(), gbl, get_bss_addr(), ISZ_T, SEM::mod_cnt, SEM::mod_sym, p_semant1, p_semant2, reinit(), reset_internal_subprograms(), resolve_fwd_refs(), RU_BDATA, sem, semant1(), semant2(), set_allfiles(), set_bss_addr(), SEM::submod_sym, summary(), TRUE, SEM::which_pass, and XBIT.
Referenced by add_generic_argument(), create_arg_parser(), destroy_arg_parser(), parse_arguments(), register_action_map_arg(), register_boolean_arg(), register_combined_bool_string_arg(), register_filename_arg(), register_inform_level_arg(), register_integer_arg(), register_qflag_arg(), register_string_arg(), register_string_list_arg(), register_xflag_arg(), register_yflag_arg(), and was_value_set().
scan_fini()
void scan_fini (void)
Compilation is finished - deallocate storage, close files, etc.
Definition at line 484 of file scan.c.
References astb, ASTB::astfil, SCN::directive, fclose(), FREE, SCN::id, incl_stack, last_char, SCN::name, SCN::options, scn, stmtbafter, stmtbefore, and tkbuf.
Referenced by finish().
scan_include()
void scan_include (char * str)
Definition at line 7395 of file scan.c.
References add_headerfile(), BCOPY, c, ISTACK::card_type, card_type, cardb, CARDB_SIZE, CNULL, curr_fd, curr_line, dirnam(), dirname, DIRSINCS, DIRWORK, ISTACK::eof_flag, errfatal(), error(), FALSE, ISTACK::fd, FILE, ISTACK::findex, HDRSTACK::findex, ISTACK::first_char, first_char, flg, ISTACK::fname, HDRSTACK::fname, fndpath(), FR_B_INCL, gbl, getitem(), hdr_level, hdr_stack, FLG::idir, in_include, incl_level, incl_stack, incl_stacksz, ISTACK::is_freeform, is_freeform, ISTACK::lineno, FLG::list, list_line(), ISTACK::list_now, list_now, MAX_IDEPTH, MAX_PATHNAME_LEN, SEM::mod_cnt, NEED, NULL, p, put_include(), q, sem, ISTACK::sentinel, sentinel, FLG::stdinc, str, tmpfile(), TRUE, SEM::which_pass, and XBIT.
Referenced by semant1().
scan_init()
void scan_init (FILE * fd)
Initialize Scanner. This routine is called once at the beginning of execution.
Parameters
fd file descriptor for main input source file
Definition at line 374 of file scan.c.
References _CS, _HO, astb, ASTB::astfil, SCN::avl, body_len, card_type, CARDB_SIZE, CNULL, ctable, curr_fd, curr_line, currc, currCol, DBGBIT, deckw, SCN::directive, directive_sz, errfatal(), error(), FLG::extend_source, FALSE, fd, first_line, flg, formatkw, FR_SRC, FLG::freeform, gbl, hdr_level, hdr_stack, hdr_stacksz, SCN::id, in_include, incl_level, incl_stack, incl_stacksz, init_ktable(), INIT_LPS, iokw, kernel_kw, last_char, leadCount, FLG::list, list_now, logicalkw, max_card, MAX_COLS, SCN::name, NEW, normalkw, NULL, SCN::options, options_sz, parallelkw, parbegkw, pgi_kw, ppragma_kw, pragma_kw, put_astfil(), sccalloc(), scn, set_input_form(), SCN::size, stmtb, stmtbafter, stmtbefore, tkbuf, tkbuf_sz, tmpfile(), TRUE, and XBIT.
Referenced by init().
scan_opt_restore()
void scan_opt_restore (void)
Definition at line 7561 of file scan.c.
References body_len, FLG::extend_source, FALSE, flg, FLG::i4, options_seen, FLG::recursive, save_flg, FLG::standard, and FLG::x.
Referenced by reinit().
scan_options()
void scan_options (void)
Definition at line 7577 of file scan.c.
References body_len, card_type, cardb, CNULL, CT_DIRECTIVE, DBGBIT, DT_INT, error(), FLG::extend_source, FALSE, flg, gbl, getindex(), FLG::i4, implicit_int(), NSWDS, SCN::options, options_seen, p, FLG::recursive, save_extend_ch, save_flg, scn, FLG::standard, SW_CHECK, SW_EXTEND, SW_GFLOAT, SW_I4, SW_NOCHECK, SW_NOEXTEND, SW_NOGFLOAT, SW_NOI4, SW_NORECURS, SW_NOREENTR, SW_NOSTANDARD, SW_RECURS, SW_REENTR, SW_STANDARD, swtchtab, symtab_nostandard(), symtab_standard(), TRUE, write_card(), and FLG::x.
Referenced by semant1().
scan_reset()
void scan_reset (void)
Lexical or syntactical error found, so re-initialize the Scanner so that next Fortran statement will be processed.
Definition at line 473 of file scan.c.
References currc, currCol, SCN::end_program_unit, FALSE, leadCount, NULL, and scn.
Referenced by parse_init().
Variable Documentation
scn
SCN scn extern
Definition at line 27 of file fenddf.c.
Referenced by _get_token(), _parser(), _rd_token(), _read_token(), _write_token(), add_stmt(), alpha(), check_ccon(), check_continuation(), check_do_term(), check_doconcurrent(), check_end_subprogram(), check_pgi_pragma(), classify_dec(), classify_kernel_pragma(), classify_pgi_dir(), classify_pgi_pragma(), classify_pragma(), classify_smp(), crunch(), do_end(), dummy_program(), ff_get_label(), ff_get_stmt(), func_call2(), get_derived_type(), get_id_name(), get_keyword_args(), get_keyword_components(), get_stmt(), kwd_match(), prettytoken(), ptrfunc_call(), ptrsubr_call(), ref_stfunc(), scan_fini(), scan_init(), scan_options(), scan_reset(), semant1(), semant2(), semant3(), semantio(), semsmp(), setup_procedure_sym(), subr_call2(), and sum_scatter_args().