flang: scatter_minval.c File Reference
scatter_minval.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "scatter.h"
Functions
static void scatter_minval_int1 (int n, __INT1_T *r, int *sv, __INT1_T *a)
static void scatter_minval_int2 (int n, __INT2_T *r, int *sv, __INT2_T *a)
static void scatter_minval_int4 (int n, __INT4_T *r, int *sv, __INT4_T *a)
static void scatter_minval_int8 (int n, __INT8_T *r, int *sv, __INT8_T *a)
static void scatter_minval_real4 (int n, __REAL4_T *r, int *sv, __REAL4_T *a)
static void scatter_minval_real8 (int n, __REAL8_T *r, int *sv, __REAL8_T *a)
static void scatter_minval_real16 (int n, __REAL16_T *r, int *sv, __REAL16_T *a)
static void gathscat_minval_int1 (int n, __INT1_T *r, int *sv, __INT1_T *a, int *gv)
static void gathscat_minval_int2 (int n, __INT2_T *r, int *sv, __INT2_T *a, int *gv)
static void gathscat_minval_int4 (int n, __INT4_T *r, int *sv, __INT4_T *a, int *gv)
static void gathscat_minval_int8 (int n, __INT8_T *r, int *sv, __INT8_T *a, int *gv)
static void gathscat_minval_real4 (int n, __REAL4_T *r, int *sv, __REAL4_T *a, int *gv)
static void gathscat_minval_real8 (int n, __REAL8_T *r, int *sv, __REAL8_T *a, int *gv)
static void gathscat_minval_real16 (int n, __REAL16_T *r, int *sv, __REAL16_T *a, int *gv)
void ENTFTN (MINVAL_SCATTER, minval_scatter)
void ENTFTN (MINVAL_SCATTERX, minval_scatterx)
sked * ENTFTN (COMM_MINVAL_SCATTER, comm_minval_scatter)
sked * ENTFTN (COMM_MINVAL_SCATTER_1, comm_minval_scatter_1)
sked * ENTFTN (COMM_MINVAL_SCATTER_2, comm_minval_scatter_2)
sked * ENTFTN (COMM_MINVAL_SCATTER_3, comm_minval_scatter_3)
sked * ENTFTN (COMM_MINVAL_SCATTER_4, comm_minval_scatter_4)
sked * ENTFTN (COMM_MINVAL_SCATTER_5, comm_minval_scatter_5)
sked * ENTFTN (COMM_MINVAL_SCATTER_6, comm_minval_scatter_6)
sked * ENTFTN (COMM_MINVAL_SCATTER_7, comm_minval_scatter_7)
Variables
static __INT_T _1 = 1
static void(* scatter_minval [__NTYPES])()
static void(* gathscat_minval [__NTYPES])()
Function Documentation
ENTFTN() [1/10]
sked * ENTFTN (COMM_MINVAL_SCATTER , comm_minval_scatter)
Definition at line 369 of file scatter_minval.c.
References __fort_gathscat(), __fort_recvl(), __fort_sendl(), __SCATTER, F90_KIND_G, gathscat_minval, i, I8, rb, scatter_minval, va, and z.
ENTFTN() [2/10]
sked * ENTFTN (COMM_MINVAL_SCATTER_1 , comm_minval_scatter_1)
Definition at line 411 of file scatter_minval.c.
References ENTFTN(), and rb.
ENTFTN() [3/10]
sked * ENTFTN (COMM_MINVAL_SCATTER_2 , comm_minval_scatter_2)
Definition at line 422 of file scatter_minval.c.
References ENTFTN(), and rb.
ENTFTN() [4/10]
sked * ENTFTN (COMM_MINVAL_SCATTER_3 , comm_minval_scatter_3)
Definition at line 433 of file scatter_minval.c.
References ENTFTN(), and rb.
ENTFTN() [5/10]
sked * ENTFTN (COMM_MINVAL_SCATTER_4 , comm_minval_scatter_4)
Definition at line 446 of file scatter_minval.c.
References ENTFTN(), and rb.
ENTFTN() [6/10]
sked * ENTFTN (COMM_MINVAL_SCATTER_5 , comm_minval_scatter_5)
Definition at line 460 of file scatter_minval.c.
References ENTFTN(), and rb.
ENTFTN() [7/10]
sked * ENTFTN (COMM_MINVAL_SCATTER_6 , comm_minval_scatter_6)
Definition at line 474 of file scatter_minval.c.
References ENTFTN(), and rb.
ENTFTN() [8/10]
sked * ENTFTN (COMM_MINVAL_SCATTER_7 , comm_minval_scatter_7)
Definition at line 489 of file scatter_minval.c.
References ENTFTN(), and rb.
ENTFTN() [9/10]
void ENTFTN (MINVAL_SCATTER , minval_scatter)
Definition at line 204 of file scatter_minval.c.
References _1, __fort_adjust_index_array(), __fort_copy(), __fort_create_conforming_index_array(), __fort_doit(), __fort_frechn(), __fort_free(), __fort_gathscat(), __fort_gfree(), __fort_malloc(), __fort_recvl(), __fort_sendl(), __fort_stored_alike(), __SCATTER, DECL_HDR_PTRS, DIST_SCOFF_G, ENTFTN(), F90_DIM_LBOUND_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, gathscat_minval, i, I8, ISSCALAR, MAXDIMS, NULL, rb, scatter_minval, SIZE_OF_RANK_n_ARRAY_DESC, td, va, and z.
Referenced by ENTFTN().
ENTFTN() [10/10]
void ENTFTN (MINVAL_SCATTERX , minval_scatterx)
Definition at line 301 of file scatter_minval.c.
References _1, __fort_copy(), __fort_doit(), __fort_frechn(), __fort_gathscat(), __fort_recvl(), __fort_sendl(), __fort_stored_alike(), __SCATTER, DIST_SCOFF_G, ENTFTN(), F90_KIND_G, F90_LEN_G, gathscat_minval, i, I8, NULL, rb, scatter_minval, va, and z.
gathscat_minval_int1()
static void gathscat_minval_int1 (int n, __INT1_T * r, int * sv, __INT1_T * a, int * gv) static
Definition at line 111 of file scatter_minval.c.
References a, i, n, and r.
gathscat_minval_int2()
static void gathscat_minval_int2 (int n, __INT2_T * r, int * sv, __INT2_T * a, int * gv) static
Definition at line 119 of file scatter_minval.c.
References a, i, n, and r.
gathscat_minval_int4()
static void gathscat_minval_int4 (int n, __INT4_T * r, int * sv, __INT4_T * a, int * gv) static
Definition at line 127 of file scatter_minval.c.
References a, i, n, and r.
gathscat_minval_int8()
static void gathscat_minval_int8 (int n, __INT8_T * r, int * sv, __INT8_T * a, int * gv) static
Definition at line 135 of file scatter_minval.c.
References a, i, n, and r.
gathscat_minval_real16()
static void gathscat_minval_real16 (int n, __REAL16_T * r, int * sv, __REAL16_T * a, int * gv) static
Definition at line 159 of file scatter_minval.c.
References a, i, n, and r.
gathscat_minval_real4()
static void gathscat_minval_real4 (int n, __REAL4_T * r, int * sv, __REAL4_T * a, int * gv) static
Definition at line 143 of file scatter_minval.c.
References a, i, n, and r.
gathscat_minval_real8()
static void gathscat_minval_real8 (int n, __REAL8_T * r, int * sv, __REAL8_T * a, int * gv) static
Definition at line 151 of file scatter_minval.c.
References a, i, n, and r.
scatter_minval_int1()
static void scatter_minval_int1 (int n, __INT1_T * r, int * sv, __INT1_T * a) static
Definition at line 17 of file scatter_minval.c.
References a, i, n, and r.
scatter_minval_int2()
static void scatter_minval_int2 (int n, __INT2_T * r, int * sv, __INT2_T * a) static
Definition at line 25 of file scatter_minval.c.
References a, i, n, and r.
scatter_minval_int4()
static void scatter_minval_int4 (int n, __INT4_T * r, int * sv, __INT4_T * a) static
Definition at line 33 of file scatter_minval.c.
References a, i, n, and r.
scatter_minval_int8()
static void scatter_minval_int8 (int n, __INT8_T * r, int * sv, __INT8_T * a) static
Definition at line 41 of file scatter_minval.c.
References a, i, n, and r.
scatter_minval_real16()
static void scatter_minval_real16 (int n, __REAL16_T * r, int * sv, __REAL16_T * a) static
Definition at line 65 of file scatter_minval.c.
References a, i, n, and r.
scatter_minval_real4()
static void scatter_minval_real4 (int n, __REAL4_T * r, int * sv, __REAL4_T * a) static
Definition at line 49 of file scatter_minval.c.
References a, i, n, and r.
scatter_minval_real8()
static void scatter_minval_real8 (int n, __REAL8_T * r, int * sv, __REAL8_T * a) static
Definition at line 57 of file scatter_minval.c.
References a, i, n, and r.
Variable Documentation
_1
__INT_T _1 = 1 static
Definition at line 14 of file scatter_minval.c.
Referenced by ENTFTN().
gathscat_minval
void(* gathscat_minval[__NTYPES])() () static
Definition at line 167 of file scatter_minval.c.
Referenced by ENTFTN().
scatter_minval
void(* scatter_minval[__NTYPES])() () static
Definition at line 73 of file scatter_minval.c.
Referenced by ENTFTN().