flang: scatter.h File Reference
scatter.h File Reference
Classes
struct xstuff
struct gathscat_dim
struct gathscat_parm
Typedefs
typedef struct xstuff xstuff
typedef struct gathscat_dim gathscat_dim
typedef struct gathscat_parm gathscat_parm
typedef void(* gatherfn_t) (int, void *, void *, int *)
typedef void(* gathscatfn_t) (int, void *, int *, void *, int *)
typedef void(* scatterfn_t) (int, void *, int *, void *)
Enumerations
enum gathscat_dir { __SCATTER , __GATHER }
Functions
void __fort_gathscat_abort (char *what, char *msg)
sked *I8() __fort_gathscat (gathscat_parm *z)
void * ENTFTN (COMM_START, comm_start)(sked **
void void F90_Desc void F90_Desc *void ENTFTN (COMM_FINISH, comm_finish)(void *)
void ENTFTN (COMM_FREE, comm_free)(__INT_T *ns
void void *I8() __fort_adjust_index_array (const char *what, char *idx_array, char *src, int dim, F90_Desc *is, F90_Desc *bs)
void *I8() __fort_create_conforming_index_array (const char *what, char *ab, void *ib, F90_Desc *as, F90_Desc *is, F90_Desc *new_is)
void local_gathscat_WRAPPER (int n, void *dst, int *sv, void *src, int *gv, __INT_T kind)
void local_gather_WRAPPER (int n, void *dst, void *src, int *gv, __INT_T kind)
void local_scatter_WRAPPER (int n, void *dst, int *sv, void *src, __INT_T kind)
Typedef Documentation
gatherfn_t
typedef void(* gatherfn_t) (int, void *, void *, int *)
Definition at line 45 of file scatter.h.
gathscat_dim
typedef struct gathscat_dim gathscat_dim
Definition at line 19 of file scatter.h.
gathscat_parm
typedef struct gathscat_parm gathscat_parm
Definition at line 20 of file scatter.h.
gathscatfn_t
typedef void(* gathscatfn_t) (int, void *, int *, void *, int *)
Definition at line 46 of file scatter.h.
scatterfn_t
typedef void(* scatterfn_t) (int, void *, int *, void *)
Definition at line 47 of file scatter.h.
xstuff
typedef struct xstuff xstuff
Definition at line 18 of file scatter.h.
Enumeration Type Documentation
gathscat_dir
enum gathscat_dir
Enumerator
__SCATTER
__GATHER
Definition at line 14 of file scatter.h.
Function Documentation
__fort_adjust_index_array()
void void *I8() __fort_adjust_index_array (const char * what, char * idx_array, char * src, int dim, F90_Desc * is, F90_Desc * bs)
Definition at line 1174 of file scatter.c.
References __fort_abort(), __fort_gmalloc(), __INT1, __INT2, __INT4, __INT8, dim, F90_DIM_LBOUND_G, F90_GSIZE_G, F90_KIND_G, F90_LEN_G, F90_LSIZE_G, GET_DIST_LCPU, i, ISSCALAR, NULL, and src.
Referenced by ENTFTN().
__fort_create_conforming_index_array()
void *I8() __fort_create_conforming_index_array (const char * what, char * ab, void * ib, F90_Desc * as, F90_Desc * is, F90_Desc * new_is)
Definition at line 1255 of file scatter.c.
References __fort_abort(), __fort_gmalloc(), __INT1, __INT2, __INT4, __INT8, ENTFTN, F90_GSIZE_G, F90_LSIZE_G, GET_DIST_LCPU, i, and ISSCALAR.
Referenced by ENTFTN().
__fort_gathscat()
sked *I8() __fort_gathscat (gathscat_parm * z)
Definition at line 524 of file scatter.c.
References __DESC, __fort_aligned(), __fort_aligned_axes(), __fort_conform(), __fort_covers_procs(), __fort_cycle_bounds(), __fort_describe(), __fort_describe_replication(), __fort_fetch_log(), __fort_second(), __fort_test, __INT, __LOCAL, __LOG, cpu(), DEBUG_SCAT, DEBUG_TIME, DECL_DIM_PTRS, DECL_DIST_DIM_PTR, DECL_F90_DIM_PTR, DECL_HDR_PTRS, DIST_ALIGN_TARGET_G, DIST_DIM_NAME, DIST_DIST_TARGET_G, DIST_MAPPED_G, DIST_REPLICATED_G, DIST_SINGLE_G, F90_DIM_NAME, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_KIND_G, F90_LBASE_G, F90_RANK_G, F90_TAG_G, gathscat_abort(), GET_DIST_LCPU, i, I8, id_map, j, k, LOCAL_MODE, m, MAXDIMS, n, next, NULL, SET_DIM_PTRS, t, x, gathscat_dim::xb, gathscat_dim::xmap, and z.
Referenced by ENTFTN().
__fort_gathscat_abort()
void __fort_gathscat_abort (char * what, char * msg)
ENTFTN() [1/3]
void void F90_Desc void F90_Desc *void ENTFTN (COMM_FINISH , comm_finish)
Definition at line 79 of file runtime/flang/comm.c.
ENTFTN() [2/3]
void ENTFTN (COMM_FREE , comm_free)
ENTFTN() [3/3]
void * ENTFTN (COMM_START , comm_start)
local_gather_WRAPPER()
void local_gather_WRAPPER (int n, void * dst, void * src, int * gv, __INT_T kind)
Definition at line 192 of file gather.c.
References __fort_local_gather, kind, n, and src.
Referenced by gathscat_start().
local_gathscat_WRAPPER()
void local_gathscat_WRAPPER (int n, void * dst, int * sv, void * src, int * gv, __INT_T kind)
Definition at line 377 of file gathscat.c.
References __fort_local_gathscat, kind, n, and src.
Referenced by gathscat_start().
local_scatter_WRAPPER()
void local_scatter_WRAPPER (int n, void * dst, int * sv, void * src, __INT_T kind)
Definition at line 192 of file gathscat.c.
References __fort_local_scatter, kind, n, and src.
Referenced by gathscat_start().