flang: scatter.c File Reference
scatter.c File Reference
Scatter reduction routines.
#include "stdioInterf.h"
#include "fioMacros.h"
#include "fort_vars.h"
#include "scatter.h"
Classes
struct gathscat_sked
Functions
double __fort_second ()
static void gathscat_abort (const char *what, const char *msg)
static void I8() gathscat_start (void *skp, char *rb, char *sb, F90_Desc *rd, F90_Desc *sd)
static void gathscat_free (void *skp)
static void I8() gathscat_element (gathscat_parm *z, __INT_T uoff, __INT_T xoff[])
static void I8() gathscat_mask_loop (gathscat_parm *z, int uoff0, __INT_T xoff[], int dim)
static void I8() gathscat_loop (gathscat_parm *z, int uoff0, __INT_T xoff[], int dim)
sked *I8() __fort_gathscat (gathscat_parm *z)
void *I8() __fort_adjust_index_array (const char *what, char *idx_array, char *src, int dim, F90_Desc *is, F90_Desc *bs)
void *I8() __fort_create_conforming_index_array (const char *what, char *ab, void *ib, F90_Desc *as, F90_Desc *is, F90_Desc *new_is)
Variables
static __INT_T id_map [MAXDIMS] = {1, 2, 3, 4, 5, 6, 7}
Detailed Description
Scatter reduction routines.
call ENTFTN(xxx_scatter)(rb, rs, mb, ms, bb, bs, ...) where xxx = all, any, count, parity
call ENTFTN(yyy_scatter)(rb, rs, ab, as, bb, bs, mb, ms, ...) where yyy = copy, iall, iany, iparity, maxval, minval, product, sum
rb = result base address rs = result descriptor ab = array base address as = array descriptor bb = base base address bs = base descriptor mb = mask base address ms = mask descriptor
... = { xb, xs, }* = base address and descriptors for the indexes, one pair for each result dimension.
indexes must not be scalar, instead the result section may have a scalar subscript. Index values must be within the bounds of the corresponding result dimension.
indexes must conform with array. Each dimension of every index must be either 1) replicated or 2) aligned with the corresponding dimension of array.
mask must conform with array, may be scalar, and is assumed to be of type logical*4. Each dimension of mask must be either replicated or aligned with the corresponding dimension of array.
Definition in file scatter.c.
Function Documentation
__fort_adjust_index_array()
void *I8() __fort_adjust_index_array (const char * what, char * idx_array, char * src, int dim, F90_Desc * is, F90_Desc * bs)
Definition at line 1174 of file scatter.c.
References __fort_abort(), __fort_gmalloc(), __INT1, __INT2, __INT4, __INT8, dim, F90_DIM_LBOUND_G, F90_GSIZE_G, F90_KIND_G, F90_LEN_G, F90_LSIZE_G, GET_DIST_LCPU, i, ISSCALAR, NULL, and src.
Referenced by ENTFTN().
__fort_create_conforming_index_array()
void *I8() __fort_create_conforming_index_array (const char * what, char * ab, void * ib, F90_Desc * as, F90_Desc * is, F90_Desc * new_is)
Definition at line 1255 of file scatter.c.
References __fort_abort(), __fort_gmalloc(), __INT1, __INT2, __INT4, __INT8, ENTFTN, F90_GSIZE_G, F90_LSIZE_G, GET_DIST_LCPU, i, and ISSCALAR.
Referenced by ENTFTN().
__fort_gathscat()
sked *I8() __fort_gathscat (gathscat_parm * z)
Definition at line 524 of file scatter.c.
References __DESC, __fort_aligned(), __fort_aligned_axes(), __fort_conform(), __fort_covers_procs(), __fort_cycle_bounds(), __fort_describe(), __fort_describe_replication(), __fort_fetch_log(), __fort_second(), __fort_test, __INT, __LOCAL, __LOG, cpu(), DEBUG_SCAT, DEBUG_TIME, DECL_DIM_PTRS, DECL_DIST_DIM_PTR, DECL_F90_DIM_PTR, DECL_HDR_PTRS, DIST_ALIGN_TARGET_G, DIST_DIM_NAME, DIST_DIST_TARGET_G, DIST_MAPPED_G, DIST_REPLICATED_G, DIST_SINGLE_G, F90_DIM_NAME, F90_DPTR_LSTRIDE_G, F90_DPTR_SOFFSET_G, F90_DPTR_SSTRIDE_G, F90_FLAGS_G, F90_KIND_G, F90_LBASE_G, F90_RANK_G, F90_TAG_G, gathscat_abort(), GET_DIST_LCPU, i, I8, id_map, j, k, LOCAL_MODE, m, MAXDIMS, n, next, NULL, SET_DIM_PTRS, t, x, gathscat_dim::xb, gathscat_dim::xmap, and z.
Referenced by ENTFTN().
__fort_second()
double __fort_second ()
Definition at line 104 of file stat_linux.c.
Referenced by __fort_gathscat(), and gathscat_start().
gathscat_abort()
static void gathscat_abort (const char * what, const char * msg) static
Definition at line 58 of file scatter.c.
References __fort_abort(), msg(), and str.
Referenced by __fort_gathscat(), gathscat_loop(), and gathscat_mask_loop().
gathscat_element()
static void I8() gathscat_element (gathscat_parm * z, __INT_T uoff, __INT_T xoff[]) static
Definition at line 216 of file scatter.c.
References __fort_local_offset(), __fort_localize(), __fort_print_scalar(), __fort_show_index(), __fort_test, __GATHER, __SCATTER, cpu(), DEBUG_SCAT, DECL_HDR_PTRS, DIST_SCOFF_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, GET_DIST_LCPU, I8, k, MAXDIMS, gathscat_dim::xb, gathscat_dim::xmap, and z.
Referenced by gathscat_loop(), and gathscat_mask_loop().
gathscat_free()
static void gathscat_free (void * skp) static
Definition at line 202 of file scatter.c.
References __fort_frechn(), __fort_free(), __fort_gfree(), gathscat_sked::countbuf, gathscat_sked::offsetbuf, and gathscat_sked::repchn.
gathscat_loop()
static void I8() gathscat_loop (gathscat_parm * z, int uoff0, __INT_T xoff[], int dim) static
Definition at line 416 of file scatter.c.
References __fort_block_bounds(), __fort_block_loop(), __fort_cyclic_loop(), DECL_DIM_PTRS, DECL_DIST_DIM_PTR, DECL_F90_DIM_PTR, DECL_HDR_PTRS, dim, DIST_DIM_NAME, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, F90_DIM_NAME, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, gathscat_abort(), gathscat_element(), gathscat_loop(), I8, n, SET_DIM_PTRS, x, and z.
Referenced by gathscat_loop().
gathscat_mask_loop()
static void I8() gathscat_mask_loop (gathscat_parm * z, int uoff0, __INT_T xoff[], int dim) static
Definition at line 303 of file scatter.c.
References __fort_block_bounds(), __fort_block_loop(), __fort_cyclic_loop(), DECL_DIM_PTRS, DECL_DIST_DIM_PTR, DECL_F90_DIM_PTR, DECL_HDR_PTRS, dim, DIST_DIM_NAME, DIST_DPTR_CL_G, DIST_DPTR_CLOF_G, DIST_DPTR_CLOS_G, DIST_DPTR_CN_G, DIST_DPTR_CS_G, F90_DIM_NAME, F90_DPTR_LBOUND_G, F90_DPTR_LSTRIDE_G, F90_DPTR_SSTRIDE_G, for(), gathscat_abort(), gathscat_element(), gathscat_mask_loop(), GET_DIST_MASK_LOG, I8, MAXDIMS, n, SET_DIM_PTRS, x, and z.
Referenced by gathscat_mask_loop().
gathscat_start()
static void I8() gathscat_start (void * skp, char * rb, char * sb, F90_Desc * rd, F90_Desc * sd) static
Definition at line 84 of file scatter.c.
References __fort_adjbase(), __fort_doit(), __fort_gfree(), __fort_gmalloc(), __fort_np2, __fort_rrecvl(), __fort_rsendl(), __fort_second(), __fort_test, gathscat_sked::countr, gathscat_sked::counts, cpu(), DEBUG_TIME, DIST_SCOFF_G, F90_KIND_G, F90_LEN_G, gathscat_sked::gathscatfn, GET_DIST_LCPU, GET_DIST_TCPUS, gathscat_sked::goff, j, k, gathscat_sked::lclcnt, local_gather_WRAPPER(), local_gathscat_WRAPPER(), local_scatter_WRAPPER(), m, gathscat_sked::maxcnt, rb, gathscat_sked::repchn, sb, gathscat_sked::scatterfn, gathscat_sked::soff, t, and gathscat_sked::what.
Variable Documentation
id_map
__INT_T id_map[MAXDIMS] = {1, 2, 3, 4, 5, 6, 7} static
Definition at line 55 of file scatter.c.
Referenced by __fort_gathscat().