flang: scopestack.c File Reference
scopestack.c File Reference
Manage the scope stack.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "ccffinfo.h"
#include "semant.h"
Functions
static SCOPESTACK * push_scope (void)
static void pop_scope (void)
static const char * kind_to_string (SCOPEKIND kind)
void scopestack_init ()
Initialize the scope stack.
SCOPESTACK * curr_scope ()
Return the scope at the top of the scope stack.
SCOPESTACK * get_scope (int level)
Get an entry in the scope stack.
int get_scope_level (SCOPESTACK *scope)
Return the level of this entry in the scope stack or -1 if scope is null.
SCOPESTACK * next_scope (SCOPESTACK *scope)
Return the next entry below this one in the scope stack; 0 if none. If scope is 0, return the top of the stack.
SCOPESTACK * next_scope_sptr (SCOPESTACK *scope, int sptr)
Return the next entry below scope that has this sptr assocated with it. If scope is 0, search from the top of the stack.
SCOPESTACK * next_scope_kind (SCOPESTACK *scope, SCOPEKIND kind)
Return the next entry below scope that has this kind. If scope is 0, search from the top of the stack.
SCOPESTACK * next_scope_kind_sptr (SCOPESTACK *scope, SCOPEKIND kind, int sptr)
Return the next entry below scope that has this kind and sptr. If scope is 0, search from the top of the stack.
SCOPESTACK * next_scope_kind_symname (SCOPESTACK *scope, SCOPEKIND kind, const char *symname)
Return the next entry below scope that has this kind and symbol name. If scope is 0, search from the top of the stack.
int have_use_scope (int sptr)
Return the USE module scope for the module associated with this symbol, or -1 if none.
LOGICAL is_except_in_scope (SCOPESTACK *scope, int sptr)
Return TRUE if sptr is in the exception list for this scope at this level.
LOGICAL is_private_in_scope (SCOPESTACK *scope, int sptr)
Return TRUE if scope is private and has sptr in its 'only' list.
void push_scope_level (int sptr, SCOPEKIND kind)
Push a slot on the scope stack.
void pop_scope_level (SCOPEKIND kind)
void save_scope_level (void)
Pop the current scope into a save area; restore with restore_scope_level()
void restore_scope_level (void)
Restore the scope that was saved by save_scope_level()
void par_push_scope (LOGICAL bind_to_outer)
void par_pop_scope (void)
void dumpscope (FILE *f)
void dump_one_scope (int sl, FILE *f)
Variables
static SCOPESTACK saved_scope_stack [1]
static int count_scope_saved = 0
Detailed Description
Manage the scope stack.
Definition in file scopestack.c.
Function Documentation
curr_scope()
SCOPESTACK * curr_scope (void)
Return the scope at the top of the scope stack.
Definition at line 49 of file scopestack.c.
References get_scope().
Referenced by add_only(), apply_use(), do_lastprivate(), do_nested_uses(), find_def_in_most_recent_scope(), import(), next_scope(), par_pop_scope(), par_push_scope(), pop_scope_level(), push_scope(), restore_scope_level(), save_scope_level(), scope_in_scope_stack(), and scopestack_init().
dump_one_scope()
void dump_one_scope (int sl, FILE * f)
Definition at line 468 of file scopestack.c.
References ERR_Warning, f, STB::firstosym, im, interr(), kind_to_string(), NULL, scope, SEM::scope_size, SEM::scope_stack, sem, sptr, stb, SYMI_NEXT, SYMI_SPTR, SYMNAME, and SEM::which_pass.
Referenced by dumpscope().
dumpscope()
void dumpscope (FILE * f)
Definition at line 452 of file scopestack.c.
References dump_one_scope(), f, NULL, SEM::scope_level, SEM::scope_stack, and sem.
Referenced by get_scope(), pop_scope_level(), push_scope_level(), restore_scope_level(), and save_scope_level().
get_scope()
SCOPESTACK * get_scope (int level)
Get an entry in the scope stack.
Parameters
level Level of the entry to return: 0 means top and negative is relative to the top.
Definition at line 59 of file scopestack.c.
References dumpscope(), ERR_Fatal, gbl, interr(), level(), SEM::scope_level, SEM::scope_size, SEM::scope_stack, and sem.
Referenced by curr_scope(), declsym(), export_public_used_modules(), find_in_host(), par_push_scope(), pop_scope_level(), sym_visible_in_scope(), test_scope(), and update_list_exceptions().
get_scope_level()
int get_scope_level (SCOPESTACK * scope)
Return the level of this entry in the scope stack or -1 if scope is null.
Definition at line 77 of file scopestack.c.
References assert, ERR_Fatal, level(), scope, SEM::scope_level, SEM::scope_stack, and sem.
Referenced by add_only(), apply_use(), declsym(), find_def_in_most_recent_scope(), find_in_host(), have_use_scope(), import_use_stmts(), next_scope(), and sym_in_scope().
have_use_scope()
int have_use_scope (int sptr)
Return the USE module scope for the module associated with this symbol, or -1 if none.
Definition at line 166 of file scopestack.c.
References get_scope_level(), next_scope(), NULL, scope, SEM::scope_stack, SCOPE_USE, sem, and sptr.
Referenced by do_nested_uses().
is_except_in_scope()
LOGICAL is_except_in_scope (SCOPESTACK * scope, int sptr)
Return TRUE if sptr is in the exception list for this scope at this level.
Definition at line 184 of file scopestack.c.
References scope, sptr, and sym_in_sym_list().
Referenced by add_only(), find_def_in_most_recent_scope(), find_in_host(), sym_in_scope(), sym_visible_in_scope(), and test_scope().
is_private_in_scope()
LOGICAL is_private_in_scope (SCOPESTACK * scope, int sptr)
Return TRUE if scope is private and has sptr in its 'only' list.
Definition at line 192 of file scopestack.c.
References scope, sptr, and sym_in_sym_list().
Referenced by find_def_in_most_recent_scope(), and sym_visible_in_scope().
kind_to_string()
static const char * kind_to_string (SCOPEKIND kind) static
Definition at line 506 of file scopestack.c.
References kind, SCOPE_BLOCK, SCOPE_INTERFACE, SCOPE_MODULE, SCOPE_NORMAL, SCOPE_OUTER, SCOPE_PAR, SCOPE_SUBPROGRAM, and SCOPE_USE.
Referenced by dump_one_scope(), pop_scope_level(), and push_scope_level().
next_scope()
SCOPESTACK * next_scope (SCOPESTACK * scope)
Return the next entry below this one in the scope stack; 0 if none. If scope is 0, return the top of the stack.
Definition at line 93 of file scopestack.c.
References curr_scope(), get_scope_level(), and scope.
Referenced by apply_use(), do_lastprivate(), export_public_used_modules(), find_in_host(), have_use_scope(), next_scope_kind(), next_scope_sptr(), par_push_scope(), and sym_in_scope().
next_scope_kind()
SCOPESTACK * next_scope_kind (SCOPESTACK * scope, SCOPEKIND kind)
Return the next entry below scope that has this kind. If scope is 0, search from the top of the stack.
Definition at line 124 of file scopestack.c.
References kind, next_scope(), and scope.
Referenced by declsym(), find_in_host(), next_scope_kind_sptr(), next_scope_kind_symname(), scope_in_scope_stack(), and sem_import_sym().
next_scope_kind_sptr()
SCOPESTACK * next_scope_kind_sptr (SCOPESTACK * scope, SCOPEKIND kind, int sptr)
Return the next entry below scope that has this kind and sptr. If scope is 0, search from the top of the stack.
Definition at line 138 of file scopestack.c.
References kind, next_scope_kind(), scope, and sptr.
Referenced by sym_in_scope().
next_scope_kind_symname()
SCOPESTACK * next_scope_kind_symname (SCOPESTACK * scope, SCOPEKIND kind, const char * symname)
Return the next entry below scope that has this kind and symbol name. If scope is 0, search from the top of the stack.
Definition at line 152 of file scopestack.c.
References kind, next_scope_kind(), scope, and SYMNAME.
Referenced by import_use_stmts().
next_scope_sptr()
SCOPESTACK * next_scope_sptr (SCOPESTACK * scope, int sptr)
Return the next entry below scope that has this sptr assocated with it. If scope is 0, search from the top of the stack.
Definition at line 110 of file scopestack.c.
References next_scope(), scope, and sptr.
Referenced by add_only(), apply_use(), find_def_in_most_recent_scope(), and scope_in_scope_stack().
par_pop_scope()
void par_pop_scope (void)
Definition at line 411 of file scopestack.c.
References BLK_SYM, curr_scope(), FLG::debug, exit_lexical_block(), flg, kind, scope_sym_tag::next, NULL, pop_scope_level(), SCOPESTACK::prev_sc, SEM::sc, scope_sym_tag::scope, SEM::scope_level, SCOPE_PAR, sem, scope_sym_tag::sptr, and XBIT.
Referenced by do_end(), end_target(), end_teams(), semant1(), and semsmp().
par_push_scope()
void par_push_scope (LOGICAL bind_to_outer)
Definition at line 379 of file scopestack.c.
References curr_scope(), FLG::debug, SEM::doif_depth, SCOPESTACK::end_prologue, enter_lexical_block(), flg, get_scope(), kind, SCOPESTACK::kind, next_scope(), SEM::next_unnamed_scope, NULL, SCOPESTACK::par_scope, PAR_SCOPE_SHARED, SEM::parallel, push_scope_level(), SCOPESTACK::rgn_scope, SEM::sc, scope, SEM::scope_level, SCOPE_PAR, sem, SEM::target, SEM::task, SEM::teams, and XBIT.
Referenced by begin_combine_constructs(), do_bdistribute(), do_btarget(), do_bteams(), do_distbegin(), and semsmp().
pop_scope()
static void pop_scope (void) static
Definition at line 443 of file scopestack.c.
References assert, ERR_Fatal, SEM::scope_level, and sem.
Referenced by pop_scope_level(), and save_scope_level().
pop_scope_level()
void pop_scope_level (SCOPEKIND kind)
Definition at line 250 of file scopestack.c.
References curr_scope(), STB::curr_scope, DBGBIT, dumpscope(), ERR_Severe, gbl, get_scope(), SEM::interface, interr(), kind, SCOPESTACK::kind, kind_to_string(), NULL, parent, pop_scope(), pop_sym(), scope, SCOPE_BLOCK, SCOPE_INTERFACE, SEM::scope_level, SCOPE_PAR, SEM::scope_stack, sem, sptr, SCOPESTACK::sptr, ST_ISVAR, stb, top, and SEM::which_pass.
Referenced by do_end_subprogram(), do_nested_uses(), par_pop_scope(), semant1(), and semfin().
push_scope()
static SCOPESTACK * push_scope (void) static
Definition at line 433 of file scopestack.c.
References BZERO, curr_scope(), NEED, SEM::scope_level, SEM::scope_size, SEM::scope_stack, and sem.
Referenced by push_scope_level(), and restore_scope_level().
push_scope_level()
void push_scope_level (int sptr, SCOPEKIND kind)
Push a slot on the scope stack.
Parameters
sptr For most scopes, scope symbol. For interface and parallel scopes, a small (unnamed) numeric index.
kind Scope kind.
Definition at line 203 of file scopestack.c.
References STB::curr_scope, DBGBIT, dumpscope(), ERR_Warning, gbl, interr(), kind, kind_to_string(), NULL, push_scope(), scope, SCOPE_BLOCK, SCOPE_INTERFACE, SCOPE_MODULE, SCOPE_NORMAL, SCOPE_PAR, SEM::scope_stack, SCOPE_SUBPROGRAM, SCOPE_USE, sem, setfile(), sptr, stb, SYMNAME, TRUE, and SEM::which_pass.
Referenced by do_nested_uses(), dummy_program(), import_module(), par_push_scope(), semant1(), and semfin().
restore_scope_level()
void restore_scope_level (void)
Restore the scope that was saved by save_scope_level()
Definition at line 361 of file scopestack.c.
References count_scope_saved, curr_scope(), STB::curr_scope, DBGBIT, dumpscope(), gbl, interr(), push_scope(), saved_scope_stack, sem, SCOPESTACK::sptr, stb, and SEM::which_pass.
Referenced by do_nested_uses(), and import_module().
save_scope_level()
void save_scope_level (void)
Pop the current scope into a save area; restore with restore_scope_level()
Definition at line 341 of file scopestack.c.
References count_scope_saved, curr_scope(), STB::curr_scope, DBGBIT, dumpscope(), gbl, interr(), pop_scope(), saved_scope_stack, sem, SCOPESTACK::sptr, stb, and SEM::which_pass.
Referenced by do_nested_uses(), and import_module().
scopestack_init()
void scopestack_init (void)
Initialize the scope stack.
It starts with one frame representing the outer scope, with no associated symbol.
Definition at line 31 of file scopestack.c.
References BZERO, curr_scope(), NEW, SEM::next_unnamed_scope, NULL, scope, SEM::scope_level, SCOPE_OUTER, SEM::scope_size, SEM::scope_stack, sem, and stb.
Referenced by semant_init().
Variable Documentation
count_scope_saved
int count_scope_saved = 0 static
Definition at line 336 of file scopestack.c.
Referenced by restore_scope_level(), and save_scope_level().
saved_scope_stack
SCOPESTACK saved_scope_stack[1] static
Definition at line 335 of file scopestack.c.
Referenced by restore_scope_level(), and save_scope_level().