flang: scope.h File Reference
scope.h File Reference
#include "gbldefs.h"
#include "symtab.h"
Macros
#define ICHECK(x)
Functions
bool scope_contains (SPTR outer, SPTR inner)
...
int insert_begin_scope_label (int block_sptr)
...
int insert_end_scope_label (int block_sptr)
...
bool is_scope_label_ili (int ilix)
...
bool is_scope_label (int label_sptr)
...
bool is_scope_labels_only_bih (int bihx)
...
void scope_verify (void)
...
void begin_inlined_scope (int func_sptr)
...
void cancel_inlined_scope (void)
...
void create_inlined_scope (int callee_sptr)
...
void end_inlined_scopes (int new_open_count)
...
void end_inlined_scope (void)
...
void find_scope_labels (int numilms)
...
void remove_scope_labels (void)
...
void reset_new_callee_scope (void)
...
void track_scope_label (int label)
...
void track_scope_reset (void)
...
Variables
int current_scope
int new_callee_scope
Detailed Description
Functions for dealing with lexical scopes and the lifetimes of scoped variables.
Definition in file scope.h.
Macro Definition Documentation
ICHECK
#define ICHECK (x)
Value:
  assert((x), "CHECK(" #x "): false at " __FILE__ ":",  \
         __LINE__, ERR_Informational)
Definition at line 22 of file scope.h.
Function Documentation
begin_inlined_scope()
void begin_inlined_scope (int func_sptr)
...
...
Insert an IM_LABEL ILM to open the new scope, update the new_callee_scope and current_scope variables to refer to the newly created scope.
Definition at line 741 of file scope.cpp.
References assert, create_inlined_scope(), dbgprintf, ERR_Severe, insert_begin_scope_label(), label, NEED, new_callee_scope, NEW_CALLEE_SCOPE_IS_STACK_TOP, open_callee_scope, open_callee_scope_capacity, open_callee_scope_count, SYMNAME, track_scope_label(), and XBIT_USE_SCOPE_LABELS.
cancel_inlined_scope()
void cancel_inlined_scope (void)
...
...
Definition at line 821 of file scope.cpp.
References current_scope, dbgprintf, new_callee_scope, NEW_CALLEE_SCOPE_IS_STACK_TOP, open_callee_scope, open_callee_scope_count, SYMNAME, and XBIT_USE_SCOPE_LABELS.
create_inlined_scope()
void create_inlined_scope (int callee_sptr)
...
...
Call create_inlined_scope() to create new_callee_scope as a subscope of the currently tracked scope. Then call begin_inlined_scope() and end_inlined_scope() to insert the begin/end labels.
Definition at line 699 of file scope.cpp.
References assert, current_scope, dbgprintf, ERR_Fatal, ERR_Severe, flg, GBL_CURRFUNC, FLG::inliner, new_callee_scope, NEW_CALLEE_SCOPE_IS_STACK_TOP, NEWSYM, SYMNAME, XBIT, and XBIT_USE_SCOPE_LABELS.
Referenced by begin_inlined_scope().
end_inlined_scope()
void end_inlined_scope (void)
...
...
Definition at line 774 of file scope.cpp.
References assert, dbgprintf, ERR_Fatal, ERR_Severe, insert_end_scope_label(), label, new_callee_scope, NEW_CALLEE_SCOPE_IS_STACK_TOP, open_callee_scope, open_callee_scope_count, SYMNAME, track_scope_label(), and XBIT_USE_SCOPE_LABELS.
Referenced by end_inlined_scopes().
end_inlined_scopes()
void end_inlined_scopes (int new_open_count)
...
...
Definition at line 807 of file scope.cpp.
References end_inlined_scope(), new_callee_scope, open_callee_scope, and open_callee_scope_count.
find_scope_labels()
void find_scope_labels (int numilms)
...
...
This function is looking at numilms ILMs in the ilmb.ilm_base array. We don't have any ILM_* macros defined to access that area.
Compare find_bpar() in inliner.c
Definition at line 640 of file scope.cpp.
References BOS_SIZE, ILMB::ilm_base, ilmb, ilms, IM_VAR, label, len, ILMINFO::oprs, track_scope_label(), and XBIT_USE_SCOPE_LABELS.
insert_begin_scope_label()
int insert_begin_scope_label (int block_sptr)
...
...
Returns
the new ST_LABEL symbol table entry.
Definition at line 507 of file scope.cpp.
References addlabel(), getlab(), ICHECK, VALIDSYM, and XBIT_USE_SCOPE_LABELS.
Referenced by begin_inlined_scope().
insert_end_scope_label()
int insert_end_scope_label (int block_sptr)
...
...
Returns
the new ST_LABEL symbol table entry.
Definition at line 533 of file scope.cpp.
References addlabel(), getlab(), ICHECK, VALIDSYM, and XBIT_USE_SCOPE_LABELS.
Referenced by end_inlined_scope().
is_scope_label()
bool is_scope_label (int label_sptr)
...
...
Definition at line 92 of file scope.cpp.
References VALIDSYM.
Referenced by exp_label(), expand(), and is_scope_label_ili().
is_scope_label_ili()
bool is_scope_label_ili (int ilix)
...
...
Definition at line 105 of file scope.cpp.
References ILI_OPC, ILI_OPND, and is_scope_label().
Referenced by is_scope_labels_only_bih(), and remove_scope_labels().
is_scope_labels_only_bih()
bool is_scope_labels_only_bih (int bihx)
...
...
Definition at line 115 of file scope.cpp.
References BIH_ILTFIRST, ILT_ILIP, ILT_NEXT, and is_scope_label_ili().
remove_scope_labels()
void remove_scope_labels (void)
...
...
Definition at line 858 of file scope.cpp.
References BIH_ILTFIRST, BIH_LAST, BIH_NEXT, delilt(), gbl, ILT_ILIP, ILT_NEXT, is_scope_label_ili(), rdilts(), and wrilts().
Referenced by process_input().
reset_new_callee_scope()
void reset_new_callee_scope (void)
...
Definition at line 847 of file scope.cpp.
References new_callee_scope.
scope_contains()
bool scope_contains (SPTR outer, SPTR inner)
...
...
Both outer and inner must be valid ST_BLOCK or ST_FUNC symbol table entries.
Definition at line 72 of file scope.cpp.
References ICHECK, is_scope_root(), and VALIDSYM.
Referenced by verify_beginscopes(), and verify_local().
scope_verify()
void scope_verify (void)
...
...
Definition at line 491 of file scope.cpp.
References verify_all_blocks(), and XBIT_USE_SCOPE_LABELS.
track_scope_label()
void track_scope_label (int label)
...
...
Definition at line 579 of file scope.cpp.
References assert, current_scope, dbgprintf, ERR_Severe, flg, GBL_CURRFUNC, FLG::inliner, label, SYMNAME, XBIT, and XBIT_USE_SCOPE_LABELS.
Referenced by begin_inlined_scope(), end_inlined_scope(), and find_scope_labels().
track_scope_reset()
void track_scope_reset (void)
...
...
Definition at line 567 of file scope.cpp.
References current_scope, dbgprintf, GBL_CURRFUNC, and SYMNAME.
Variable Documentation
current_scope
int current_scope extern
Definition at line 561 of file scope.cpp.
Referenced by cancel_inlined_scope(), create_inlined_scope(), track_scope_label(), and track_scope_reset().
new_callee_scope
int new_callee_scope extern
Definition at line 667 of file scope.cpp.
Referenced by begin_inlined_scope(), cancel_inlined_scope(), create_inlined_scope(), end_inlined_scope(), end_inlined_scopes(), expand(), and reset_new_callee_scope().