flang: scope.cpp File Reference
scope.cpp File Reference
Functions for dealing with lexical scopes and the lifetimes of scoped variables.
#include "scope.h"
#include "error.h"
#include "global.h"
#include "ilm.h"
#include "ilmtp.h"
#include "ili.h"
#include "go.h"
#include "flang/ADT/hash.h"
#include "symfun.h"
#include "semant.h"
Classes
struct scope_info
struct scope_stack
Macros
#define VALIDSYM(sptr) ((sptr) > NOSYM && (sptr) < stb.stg_avail)
#define NEW_CALLEE_SCOPE_IS_STACK_TOP
Functions
static bool is_scope_root (SPTR sptr)
Is sptr a symbol table entry that can be the root of a scope tree? For C, this is functions. For Fortran, this includes entries and procedures.
bool scope_contains (SPTR outer, SPTR inner)
Return true if the scope 'outer' contains the scope 'inner'.
bool is_scope_label (int label_sptr)
Return true if label_sptr is a scope label.
bool is_scope_label_ili (int ilix)
Check if ilix is an IL_LABEL instruction referring to a scope label.
bool is_scope_labels_only_bih (int bihx)
Check if the bihx basic block contains nothing but scope labels (or is empty).
static void verify_block (int block_sptr)
Verify the integrity of an ST_BLOCK symbol table entry and its associated labels.
static bool is_local_variable (int sptr)
static void collect_referenced_locals (hashset_t symbs, int ilix)
Collect the set of locals referenced by the ILI tree starting at ilix.
static void init_scope_stack (struct scope_stack *ss, SPTR func)
Initialize a scope stack with func as the outermost scope.
static void push_block (struct scope_stack *ss, SPTR block)
static void pop_block (struct scope_stack *ss)
static void verify_beginscopes (int bih, hashset_t locals, struct scope_stack *ss)
Check labels opening scopes in bih, and collect all symbols referenced in this block.
static void verify_local (hash_key_t key, void *context)
Verify a local that was referenced in the current function.
static void verify_endscopes (int bih, struct scope_stack *ss)
Process all the scope closing labels in bih.
static void verify_all_blocks (void)
Verify all of the locals referenced in the current function and check the scope labels.
void scope_verify (void)
Verify the integrity of data structures relating to variable scopes in the current function. Terminate compilation with a fatal error if anything is inconsistent.
int insert_begin_scope_label (int block_sptr)
Insert a begin-scope label ILM for the scope blksym which much be an ST_BLOCK symbol table entry.
int insert_end_scope_label (int block_sptr)
Insert an end-scope label ILM for the scope blksym which much be an ST_BLOCK symbol table entry.
void track_scope_reset ()
Reset scope tracking, start from the outer function scope.
void track_scope_label (int label)
Update curent_scope after scanning over an IM_LABEL ilmx. The label sptr is the first and only ILM operand on IM_LABEL.
void find_scope_labels (int numilms)
Find all the scope labels in the current ILM block and pass them to track_scope_label. This is used for blocks that don't contain any calls.
void create_inlined_scope (int callee_sptr)
The original function scope of the callee being inlined is represented as a new ST_BLOCK scope, stored in new_callee_scope.
void begin_inlined_scope (int func_sptr)
Immediately before inlining a function, create a new ST_BLOCK to represent the callee's function scope in the current function.
void end_inlined_scope (void)
After inlining a function, emit a scope-ending label.
void end_inlined_scopes (int new_open_count)
End currently open callee scopes until open_callee_scope_count is new_open_count.
void cancel_inlined_scope (void)
If create_inlined_scope() was called, but the inlining was abandoned before any labels were inserted, call cancel_inlined_scope() to clean up.
void reset_new_callee_scope ()
...
void remove_scope_labels (void)
Remove any scope labels from all blocks. This is done as a workaround until all the phases of the compiler accept (or ignore) scope labels.
Variables
int current_scope = 0
int new_callee_scope = 0
static int * open_callee_scope = NULL
static int open_callee_scope_count = 0
static int open_callee_scope_capacity = 0
Detailed Description
Functions for dealing with lexical scopes and the lifetimes of scoped variables.
A lexical scope is represented by an ST_BLOCK symbol table entry. The scope's ENCLFUNC field points to either the enclosing scope or the containing function. Scopes have two pairs of start/end labels:
STARTLAB / ENDLAB: These labels are only inserted when generating debug info. The are tagged as volatile so they won't be removed, and they can be used to generate complete DWARF lexical scope information.
BEGINSCOPELAB / ENDSCOPELAB: These labels are inserted in-stream as ilts with an IL_LABEL instruction. The corresponding ST_LABEL symbol table entries are tagged with the corresponding BEGINSCOPE / ENDSCOPE flags, and the ENCLFUNC field points back to the ST_BLOCK entry.
Every local variable has a scope indicated by its ENCLFUNC field. Variables with function scope point to the function's symbol table entry instead of an ST_BLOCK entry.
Definition in file scope.cpp.
Macro Definition Documentation
NEW_CALLEE_SCOPE_IS_STACK_TOP
#define NEW_CALLEE_SCOPE_IS_STACK_TOP
Value:
  (open_callee_scope_count > 0 &&     \
   new_callee_scope == open_callee_scope[open_callee_scope_count - 1])
Definition at line 686 of file scope.cpp.
VALIDSYM
#define VALIDSYM (sptr) ((sptr) > NOSYM && (sptr) < stb.stg_avail)
Definition at line 46 of file scope.cpp.
Function Documentation
begin_inlined_scope()
void begin_inlined_scope (int func_sptr)
Immediately before inlining a function, create a new ST_BLOCK to represent the callee's function scope in the current function.
...
Insert an IM_LABEL ILM to open the new scope, update the new_callee_scope and current_scope variables to refer to the newly created scope.
Definition at line 741 of file scope.cpp.
References assert, create_inlined_scope(), dbgprintf, ERR_Severe, insert_begin_scope_label(), label, NEED, new_callee_scope, NEW_CALLEE_SCOPE_IS_STACK_TOP, open_callee_scope, open_callee_scope_capacity, open_callee_scope_count, SYMNAME, track_scope_label(), and XBIT_USE_SCOPE_LABELS.
cancel_inlined_scope()
void cancel_inlined_scope (void)
If create_inlined_scope() was called, but the inlining was abandoned before any labels were inserted, call cancel_inlined_scope() to clean up.
...
Definition at line 821 of file scope.cpp.
References current_scope, dbgprintf, new_callee_scope, NEW_CALLEE_SCOPE_IS_STACK_TOP, open_callee_scope, open_callee_scope_count, SYMNAME, and XBIT_USE_SCOPE_LABELS.
collect_referenced_locals()
static void collect_referenced_locals (hashset_t symbs, int ilix) static
Collect the set of locals referenced by the ILI tree starting at ilix.
Loads and stores to local variables are always going to use an ACON to compute the address, so just find all the symbols referenced by ACONs.
Definition at line 211 of file scope.cpp.
References collect_referenced_locals(), hashset_replace(), i, IL_ISLINK, IL_OPRS, ILI_OPC, ILI_OPND, INT2HKEY, is_local_variable(), and sptr.
Referenced by collect_referenced_locals(), and verify_beginscopes().
create_inlined_scope()
void create_inlined_scope (int callee_sptr)
The original function scope of the callee being inlined is represented as a new ST_BLOCK scope, stored in new_callee_scope.
...
Call create_inlined_scope() to create new_callee_scope as a subscope of the currently tracked scope. Then call begin_inlined_scope() and end_inlined_scope() to insert the begin/end labels.
Definition at line 699 of file scope.cpp.
References assert, current_scope, dbgprintf, ERR_Fatal, ERR_Severe, flg, GBL_CURRFUNC, FLG::inliner, new_callee_scope, NEW_CALLEE_SCOPE_IS_STACK_TOP, NEWSYM, SYMNAME, XBIT, and XBIT_USE_SCOPE_LABELS.
Referenced by begin_inlined_scope().
end_inlined_scope()
void end_inlined_scope (void)
After inlining a function, emit a scope-ending label.
...
Definition at line 774 of file scope.cpp.
References assert, dbgprintf, ERR_Fatal, ERR_Severe, insert_end_scope_label(), label, new_callee_scope, NEW_CALLEE_SCOPE_IS_STACK_TOP, open_callee_scope, open_callee_scope_count, SYMNAME, track_scope_label(), and XBIT_USE_SCOPE_LABELS.
Referenced by end_inlined_scopes().
end_inlined_scopes()
void end_inlined_scopes (int new_open_count)
End currently open callee scopes until open_callee_scope_count is new_open_count.
...
Definition at line 807 of file scope.cpp.
References end_inlined_scope(), new_callee_scope, open_callee_scope, and open_callee_scope_count.
find_scope_labels()
void find_scope_labels (int numilms)
Find all the scope labels in the current ILM block and pass them to track_scope_label. This is used for blocks that don't contain any calls.
...
This function is looking at numilms ILMs in the ilmb.ilm_base array. We don't have any ILM_* macros defined to access that area.
Compare find_bpar() in inliner.c
Definition at line 640 of file scope.cpp.
References BOS_SIZE, ILMB::ilm_base, ilmb, ilms, IM_VAR, label, len, ILMINFO::oprs, track_scope_label(), and XBIT_USE_SCOPE_LABELS.
init_scope_stack()
static void init_scope_stack (struct scope_stack * ss, SPTR func) static
Initialize a scope stack with func as the outermost scope.
Definition at line 254 of file scope.cpp.
References func, NEW, SPTR_NULL, and ss.
Referenced by verify_all_blocks().
insert_begin_scope_label()
int insert_begin_scope_label (int block_sptr)
Insert a begin-scope label ILM for the scope blksym which much be an ST_BLOCK symbol table entry.
...
Returns
the new ST_LABEL symbol table entry.
Definition at line 507 of file scope.cpp.
References addlabel(), getlab(), ICHECK, VALIDSYM, and XBIT_USE_SCOPE_LABELS.
Referenced by begin_inlined_scope().
insert_end_scope_label()
int insert_end_scope_label (int block_sptr)
Insert an end-scope label ILM for the scope blksym which much be an ST_BLOCK symbol table entry.
...
Returns
the new ST_LABEL symbol table entry.
Definition at line 533 of file scope.cpp.
References addlabel(), getlab(), ICHECK, VALIDSYM, and XBIT_USE_SCOPE_LABELS.
Referenced by end_inlined_scope().
is_local_variable()
static bool is_local_variable (int sptr) static
Definition at line 181 of file scope.cpp.
References sptr.
Referenced by collect_referenced_locals().
is_scope_label()
bool is_scope_label (int label_sptr)
Return true if label_sptr is a scope label.
...
Definition at line 92 of file scope.cpp.
References VALIDSYM.
Referenced by exp_label(), expand(), and is_scope_label_ili().
is_scope_label_ili()
bool is_scope_label_ili (int ilix)
Check if ilix is an IL_LABEL instruction referring to a scope label.
...
Definition at line 105 of file scope.cpp.
References ILI_OPC, ILI_OPND, and is_scope_label().
Referenced by is_scope_labels_only_bih(), and remove_scope_labels().
is_scope_labels_only_bih()
bool is_scope_labels_only_bih (int bihx)
Check if the bihx basic block contains nothing but scope labels (or is empty).
...
Definition at line 115 of file scope.cpp.
References BIH_ILTFIRST, ILT_ILIP, ILT_NEXT, and is_scope_label_ili().
is_scope_root()
static bool is_scope_root (SPTR sptr) static
Is sptr a symbol table entry that can be the root of a scope tree? For C, this is functions. For Fortran, this includes entries and procedures.
Definition at line 54 of file scope.cpp.
References sptr.
Referenced by scope_contains().
pop_block()
static void pop_block (struct scope_stack * ss) static
Definition at line 278 of file scope.cpp.
References dbgprintf, ICHECK, ss, and SYMNAME.
Referenced by verify_endscopes().
push_block()
static void push_block (struct scope_stack * ss, SPTR block) static
Definition at line 265 of file scope.cpp.
References scope_info::block, dbgprintf, NEED, ss, and SYMNAME.
Referenced by verify_beginscopes().
remove_scope_labels()
void remove_scope_labels (void)
Remove any scope labels from all blocks. This is done as a workaround until all the phases of the compiler accept (or ignore) scope labels.
...
Definition at line 858 of file scope.cpp.
References BIH_ILTFIRST, BIH_LAST, BIH_NEXT, delilt(), gbl, ILT_ILIP, ILT_NEXT, is_scope_label_ili(), rdilts(), and wrilts().
Referenced by process_input().
reset_new_callee_scope()
void reset_new_callee_scope (void)
...
Definition at line 847 of file scope.cpp.
References new_callee_scope.
scope_contains()
bool scope_contains (SPTR outer, SPTR inner)
Return true if the scope 'outer' contains the scope 'inner'.
...
Both outer and inner must be valid ST_BLOCK or ST_FUNC symbol table entries.
Definition at line 72 of file scope.cpp.
References ICHECK, is_scope_root(), and VALIDSYM.
Referenced by verify_beginscopes(), and verify_local().
scope_verify()
void scope_verify (void)
Verify the integrity of data structures relating to variable scopes in the current function. Terminate compilation with a fatal error if anything is inconsistent.
...
Definition at line 491 of file scope.cpp.
References verify_all_blocks(), and XBIT_USE_SCOPE_LABELS.
track_scope_label()
void track_scope_label (int label)
Update curent_scope after scanning over an IM_LABEL ilmx. The label sptr is the first and only ILM operand on IM_LABEL.
...
Definition at line 579 of file scope.cpp.
References assert, current_scope, dbgprintf, ERR_Severe, flg, GBL_CURRFUNC, FLG::inliner, label, SYMNAME, XBIT, and XBIT_USE_SCOPE_LABELS.
Referenced by begin_inlined_scope(), end_inlined_scope(), and find_scope_labels().
track_scope_reset()
void track_scope_reset (void)
Reset scope tracking, start from the outer function scope.
...
Definition at line 567 of file scope.cpp.
References current_scope, dbgprintf, GBL_CURRFUNC, and SYMNAME.
verify_all_blocks()
static void verify_all_blocks (void) static
Verify all of the locals referenced in the current function and check the scope labels.
Definition at line 436 of file scope.cpp.
References BIH_NEXT, dbgprintf, FREE, gbl, GBL_CURRFUNC, hash_functions_direct, hashset_alloc(), hashset_clear(), hashset_free(), hashset_iterate(), i, ICHECK, init_scope_stack(), j, NULL, SPTR_NULL, ss, SYMNAME, verify_beginscopes(), verify_endscopes(), and verify_local().
Referenced by scope_verify().
verify_beginscopes()
static void verify_beginscopes (int bih, hashset_t locals, struct scope_stack * ss) static
Check labels opening scopes in bih, and collect all symbols referenced in this block.
Add opened scopes to ss.
Definition at line 294 of file scope.cpp.
References BIH_ILTFIRST, collect_referenced_locals(), ICHECK, ILI_OPC, ILI_SymOPND, ilt, ILT_ILIP, ILT_NEXT, push_block(), scope_contains(), ss, VALIDSYM, and verify_block().
Referenced by verify_all_blocks().
verify_block()
static void verify_block (int block_sptr) static
Verify the integrity of an ST_BLOCK symbol table entry and its associated labels.
Definition at line 131 of file scope.cpp.
References ICHECK, and VALIDSYM.
Referenced by verify_beginscopes(), and verify_endscopes().
verify_endscopes()
static void verify_endscopes (int bih, struct scope_stack * ss) static
Process all the scope closing labels in bih.
Pop the closed scopes off the stack.
Definition at line 395 of file scope.cpp.
References BIH_ILTFIRST, i, ICHECK, ILI_OPC, ILI_OPND, ilt, ILT_ILIP, ILT_NEXT, pop_block(), ss, and verify_block().
Referenced by verify_all_blocks().
verify_local()
static void verify_local (hash_key_t key, void * context) static
Verify a local that was referenced in the current function.
This function conforms to the prototype expected by hashset_iterate.
Definition at line 338 of file scope.cpp.
References scope_stack::curr, dbgprintf, HKEY2INT, i, ICHECK, scope_contains(), sptr, ss, SYMNAME, and VALIDSYM.
Referenced by verify_all_blocks().
Variable Documentation
current_scope
int current_scope = 0
Definition at line 561 of file scope.cpp.
Referenced by cancel_inlined_scope(), create_inlined_scope(), track_scope_label(), and track_scope_reset().
new_callee_scope
int new_callee_scope = 0
Definition at line 667 of file scope.cpp.
Referenced by begin_inlined_scope(), cancel_inlined_scope(), create_inlined_scope(), end_inlined_scope(), end_inlined_scopes(), expand(), and reset_new_callee_scope().
open_callee_scope
int* open_callee_scope = NULL static
Definition at line 677 of file scope.cpp.
Referenced by begin_inlined_scope(), cancel_inlined_scope(), end_inlined_scope(), and end_inlined_scopes().
open_callee_scope_capacity
int open_callee_scope_capacity = 0 static
Definition at line 679 of file scope.cpp.
Referenced by begin_inlined_scope().
open_callee_scope_count
int open_callee_scope_count = 0 static
Definition at line 678 of file scope.cpp.
Referenced by begin_inlined_scope(), cancel_inlined_scope(), end_inlined_scope(), and end_inlined_scopes().