flang: sdasin.cpp File Reference
sdasin.cpp File Reference
#include <immintrin.h>
#include <math.h>
#include "dasin_defs.h"
Macros
#define FMA __builtin_fma
Functions
double __fsd_asin_fma3 (double)
static long long __double_as_ll (double const a)
static double __ll_as_double (long long const a)
Macro Definition Documentation
FMA
#define FMA __builtin_fma
Definition at line 20 of file sdasin.cpp.
Function Documentation
__double_as_ll()
static long long __double_as_ll (double const a) static
Definition at line 24 of file sdasin.cpp.
References a.
Referenced by __fsd_asin_fma3().
__fsd_asin_fma3()
double __fsd_asin_fma3 (double a)
Definition at line 33 of file sdasin.cpp.
References __double_as_ll(), __ll_as_double(), a, A0_D, A1_D, ABS_MASK_LL, B0_D, B1_D, C0_D, C1_D, D0_D, D1_D, E0_D, E1_D, F0_D, F1_D, FMA, G0_D, G1_D, H0_D, H1_D, I0_D, I1_D, J0_D, J1_D, K0_D, K1_D, L0_D, L1_D, M0_D, PIO2_HI_D, PIO2_LO_D, res, SGN_MASK_LL, sign, sqrt(), THRESHOLD_LL, x, and x2.
__ll_as_double()
static double __ll_as_double (long long const a) static
Definition at line 28 of file sdasin.cpp.
References a.
Referenced by __fsd_asin_fma3().