flang: sdpow.cpp File Reference
sdpow.cpp File Reference
#include <immintrin.h>
#include "dpow_defs.h"
Classes
struct __m128d_2
Functions
double __fsd_pow_fma3 (double, double)
__m128d neg (__m128d a)
__m128d_2 __internal_ddfma (__m128d_2 x, __m128d_2 y, __m128d_2 z)
__m128d_2 __internal_ddadd_yisdouble (__m128d_2 x, __m128d_2 y)
__m128d __internal_fast_int2dbl (__m128i a)
__m128d __attribute__ ((noinline)) __pgm_exp_d_scalar_slowpath(__m128i const i
if (a_is_neg_flag &&(!b_is_integer_flag))
if (a_is_any_zero_flag &&b_is_lt_zero_flag)
Variables
__m128d __m128d const t
__m128d __m128d const __m128d const bloga
__m128d __m128d const __m128d const __m128d z = _mm_blendv_pd(slowpath_blend, z, slowpath_mask)
__m128d __m128d const __m128d const __m128d __m128d prodx
__m128d const UPPERBOUND_2 = (__m128d)_mm_set1_epi64x(UPPERBOUND_2_D)
__m128d const ZERO = _mm_set1_pd(ZERO_D)
__m128d const INF = (__m128d)_mm_set1_epi64x(INF_D)
__m128i const HI_ABS_MASK = _mm_set1_epi64x(HI_ABS_MASK_D)
__m128i const ABS_MASK = _mm_set1_epi64x(ABS_MASK_D)
__m128i const MULT_CONST = _mm_set1_epi64x(MULT_CONST_D)
__m128i abs_bloga = _mm_and_si128((__m128i)bloga, ABS_MASK)
__m128d abs_lt = (__m128d)_mm_and_si128((__m128i)abs_bloga, HI_ABS_MASK)
__m128d lt_zero_mask = _mm_cmp_sd(bloga, ZERO, _CMP_LT_OS)
__m128d slowpath_mask = _mm_cmp_sd(abs_lt, UPPERBOUND_1, _CMP_LT_OS)
__m128d a_plus_inf = _mm_add_sd(bloga, INF)
__m128d zero_inf_blend = _mm_blendv_pd(a_plus_inf, ZERO, lt_zero_mask)
__m128d accurate_scale_mask = (__m128d)_mm_cmp_sd(abs_lt, UPPERBOUND_2, _CMP_LT_OS)
__m128i k = _mm_srli_epi64(i, 1)
__m128i i_scale_acc = _mm_slli_epi64(k, D52_D)
__m128i i_scale_acc_2 = _mm_slli_epi64(k, D52_D)
__m128d multiplier = (__m128d)_mm_add_epi64(i_scale_acc_2, MULT_CONST)
__m128d res = (__m128d)_mm_add_epi32(i_scale_acc, (__m128i)t)
__m128d slowpath_blend = _mm_blendv_pd(zero_inf_blend, res, accurate_scale_mask)
__m128i isinf_mask = _mm_cmpeq_epi64((__m128i)INF, (__m128i)z)
__m128d z_fixed = _mm_fmadd_sd(z, prodx, z)
__m128d __m128d const b
__m128d const SGN_EXP_MASK = (__m128d)_mm_set1_epi64x(SGN_EXP_MASK_D)
__m128d const NEG_ONE = _mm_set1_pd(NEG_ONE_D)
__m128d const ONE = _mm_set1_pd(ONE_D)
__m128d const HALF = _mm_set1_pd(HALF_D)
__m128d const SGN_MASK = (__m128d)_mm_set1_epi64x(SGN_MASK_D)
__m128i const INF_FAKE = _mm_set1_epi64x(INF_FAKE_D)
__m128d const NAN_MASK = (__m128d)_mm_set1_epi64x(NAN_MASK_D)
__m128d const NEG_ONE_CONST = (__m128d)_mm_set1_epi64x(NEG_ONE_CONST_D)
__m128i const TEN_23 = _mm_set1_epi64x(TEN_23_D)
__m128i const ELEVEN = _mm_set1_epi64x(ELEVEN_D)
__m128i a_sign = (__m128i)_mm_and_pd(a, SGN_MASK)
__m128i b_sign = (__m128i)_mm_and_pd(b, SGN_MASK)
__m128i bIsOddInteger = _mm_sllv_epi64((__m128i)b, shiftb)
__m128d abs_a = _mm_and_pd(a, (__m128d)ABS_MASK)
__m128d abs_b = _mm_and_pd(b, (__m128d)ABS_MASK)
__m128i shiftb = (__m128i)_mm_and_pd (b, SGN_EXP_MASK)
__m128i b_is_half = _mm_cmpeq_epi64((__m128i)abs_b, (__m128i)HALF)
__m128d ahi_lt_0 = (__m128d)_mm_cmpeq_epi64(a_sign, (__m128i)ZERO)
__m128d ahilt0_and_boddint_mask = _mm_andnot_pd(ahi_lt_0, (__m128d)bIsOddInteger)
__m128d b_ne_trunc = _mm_cmp_sd(b, _mm_round_pd(b, _MM_FROUND_TO_ZERO), _CMP_NEQ_UQ)
__m128d nan_mask = _mm_andnot_pd(ahi_lt_0, b_ne_trunc)
__m128d a_is_0_mask = (__m128d)_mm_cmpeq_epi64((__m128i)abs_a, (__m128i)ZERO)
__m128d thi_when_ais0 = ZERO
__m128d bhi_lt_0 = (__m128d)_mm_cmpeq_epi64(b_sign, (__m128i)ZERO)
__m128d thi_or_INF = _mm_or_pd(thi_when_ais0, INF)
__m128d t_when_ais0 = _mm_and_pd(thi_when_ais0, (__m128d)HI_MASK)
__m128d a_inf_mask = (__m128d)_mm_cmpeq_epi64((__m128i)abs_a, (__m128i)INF)
__m128d thi_when_aisinf = _mm_blendv_pd(thi_when_aisinf, INF, bhi_lt_0)
__m128d thi_xor_sgn = _mm_xor_pd(thi_when_aisinf, SGN_MASK)
__m128d b_inf_mask = (__m128d)_mm_cmpeq_epi64((__m128i)abs_b, (__m128i)INF)
__m128d thi_when_bisinf = ZERO
__m128d absa_gt_one = _mm_cmp_sd(abs_a, ONE, _CMP_GT_OS)
__m128d thi_xor_inf = _mm_xor_pd(thi_when_bisinf, INF)
__m128d a_is_negone = (__m128d)_mm_cmpeq_epi64((__m128i)a, (__m128i)NEG_ONE)
__m128i a_nan_mask = _mm_cmpeq_epi64(_mm_max_epu32((__m128i)abs_a, INF_FAKE), INF_FAKE)
__m128i b_nan_mask = _mm_cmpeq_epi64(_mm_max_epu32((__m128i)abs_b, INF_FAKE), INF_FAKE)
__m128i aorb_nan_mask = _mm_and_si128(a_nan_mask, b_nan_mask)
__m128d a_is_one_mask = (__m128d)_mm_cmpeq_epi64((__m128i)a, (__m128i)ONE)
__m128d b_is_zero_mask = (__m128d)_mm_cmpeq_epi64((__m128i)abs_b, (__m128i)ZERO)
__m128d ans_equals_one_mask = _mm_or_pd(a_is_one_mask, b_is_zero_mask)
__m128i a_is_neg = (__m128i)_mm_cmp_pd(a, ZERO, _CMP_LT_OS)
int a_is_neg_flag = _mm_movemask_epi8((__m128i)a_is_neg)
__m128i b_is_integer = (__m128i)_mm_cmp_pd(b, _mm_floor_pd(b), _CMP_EQ_OQ)
int b_is_integer_flag = _mm_movemask_epi8((__m128i)b_is_integer)
__m128i b_is_lt_zero = (__m128i)_mm_cmp_pd(b, ZERO, _CMP_LT_OS)
int b_is_lt_zero_flag = _mm_movemask_epi8((__m128i)b_is_lt_zero)
__m128d const MINUS_ZERO = _mm_set1_pd((double)-0.0)
__m128i a_is_pos_zero = _mm_cmpeq_epi64((__m128i)a, (__m128i)ZERO)
__m128i a_is_neg_zero = _mm_cmpeq_epi64((__m128i)a, (__m128i)MINUS_ZERO)
__m128i a_is_any_zero = _mm_or_si128(a_is_pos_zero, a_is_neg_zero)
int a_is_any_zero_flag = _mm_movemask_epi8((__m128i)a_is_any_zero)
Function Documentation
__attribute__()
__m128d __attribute__ ((noinline)) const
References UPPERBOUND_1_D.
__fsd_pow_fma3()
double __fsd_pow_fma3 (double a_in, double b_in)
Definition at line 267 of file sdpow.cpp.
References __internal_ddadd_yisdouble(), __internal_ddfma(), __internal_fast_int2dbl(), a, abs_a, abs_bloga, ABS_MASK, ABS_MASK_D, ALL_ONES_EXPONENT, ALL_ONES_EXPONENT_D, b, bloga, CC_CONST_X_D, CC_CONST_Y_D, D52_D, DBL2INT_CVT, DBL2INT_CVT_D, detect_inf_nan, e, EXP_POLY_0, EXP_POLY_0_D, EXP_POLY_1, EXP_POLY_1_D, EXP_POLY_2, EXP_POLY_2_D, EXP_POLY_3, EXP_POLY_3_D, EXP_POLY_4, EXP_POLY_4_D, EXP_POLY_5, EXP_POLY_5_D, EXP_POLY_6, EXP_POLY_6_D, EXP_POLY_7, EXP_POLY_7_D, EXP_POLY_8, EXP_POLY_8_D, EXP_POLY_9, EXP_POLY_9_D, EXP_POLY_A_D, EXP_POLY_B_D, EXPO_MASK_D, f, HALFIFIER_D, HI_ABS_MASK, HI_ABS_MASK_D, HI_CONST_1_D, HI_CONST_2_D, HI_MASK_D, HI_THRESH_D, i, L2E, L2E_D, LN2_HI, LN2_HI_D, LN2_LO, LN2_LO_D, LOG_POLY_0_D, LOG_POLY_1_D, LOG_POLY_2_D, LOG_POLY_3_D, LOG_POLY_4_D, LOG_POLY_5_D, LOG_POLY_6_D, m, neg(), NEG_LN2_HI_D, NEG_LN2_LO_D, ONE, ONE_D, ONE_F, ONE_F_D, prodx, q, qq, SGN_EXP_MASK, SGN_EXP_MASK_D, t, t4, t6, t8, TEN_23, TEN_23_D, tmp, TWO_D, UPPERBOUND_1_D, __m128d_2::x, __m128d_2::y, z, ZERO, and ZERO_D.
__internal_ddadd_yisdouble()
__m128d_2 __internal_ddadd_yisdouble (__m128d_2 x, __m128d_2 y) inline
Definition at line 56 of file sdpow.cpp.
References e, x, y, and z.
Referenced by __fsd_pow_fma3().
__internal_ddfma()
__m128d_2 __internal_ddfma (__m128d_2 x, __m128d_2 y, __m128d_2 z) inline
Definition at line 38 of file sdpow.cpp.
References e, m, t, x, y, and z.
Referenced by __fsd_pow_fma3().
__internal_fast_int2dbl()
__m128d __internal_fast_int2dbl (__m128i a) inline
Definition at line 69 of file sdpow.cpp.
References a, INT2DBL_D, INT2DBL_HI_D, INT2DBL_LO_D, and t.
Referenced by __fsd_pow_fma3().
if() [1/2]
if (a_is_any_zero_flag && b_is_lt_zero_flag)
Definition at line 260 of file sdpow.cpp.
References ONE, and ZERO.
if() [2/2]
if (a_is_neg_flag && !b_is_integer_flag)
Definition at line 256 of file sdpow.cpp.
References a.
neg()
__m128d neg (__m128d a) inline
Definition at line 30 of file sdpow.cpp.
References a, SGN_MASK, and SGN_MASK_D.
Referenced by __abort_init(), __fortio_fmt_i(), __fortio_fmt_i8(), __fsd_pow_fma3(), __rvs_log_fma3(), __rvs_log_fma3_256(), conv_e(), conv_en(), conv_es(), conv_int(), fused_multiply_add_canonical_form(), getlval(), getoperand(), getpair(), and getval().
Variable Documentation
a_inf_mask
__m128d a_inf_mask = (__m128d)_mm_cmpeq_epi64((__m128i)abs_a, (__m128i)INF)
Definition at line 191 of file sdpow.cpp.
a_is_0_mask
__m128d a_is_0_mask = (__m128d)_mm_cmpeq_epi64((__m128i)abs_a, (__m128i)ZERO)
Definition at line 176 of file sdpow.cpp.
a_is_any_zero
__m128i a_is_any_zero = _mm_or_si128(a_is_pos_zero, a_is_neg_zero)
Definition at line 241 of file sdpow.cpp.
a_is_any_zero_flag
int a_is_any_zero_flag = _mm_movemask_epi8((__m128i)a_is_any_zero)
Definition at line 242 of file sdpow.cpp.
a_is_neg
__m128i a_is_neg = (__m128i)_mm_cmp_pd(a, ZERO, _CMP_LT_OS)
Definition at line 229 of file sdpow.cpp.
a_is_neg_flag
int a_is_neg_flag = _mm_movemask_epi8((__m128i)a_is_neg)
Definition at line 230 of file sdpow.cpp.
a_is_neg_zero
__m128i a_is_neg_zero = _mm_cmpeq_epi64((__m128i)a, (__m128i)MINUS_ZERO)
Definition at line 240 of file sdpow.cpp.
a_is_negone
__m128d a_is_negone = (__m128d)_mm_cmpeq_epi64((__m128i)a, (__m128i)NEG_ONE)
Definition at line 210 of file sdpow.cpp.
a_is_one_mask
__m128d a_is_one_mask = (__m128d)_mm_cmpeq_epi64((__m128i)a, (__m128i)ONE)
Definition at line 222 of file sdpow.cpp.
a_is_pos_zero
__m128i a_is_pos_zero = _mm_cmpeq_epi64((__m128i)a, (__m128i)ZERO)
Definition at line 239 of file sdpow.cpp.
a_nan_mask
__m128i a_nan_mask = _mm_cmpeq_epi64(_mm_max_epu32((__m128i)abs_a, INF_FAKE), INF_FAKE)
Definition at line 216 of file sdpow.cpp.
a_plus_inf
__m128d a_plus_inf = _mm_add_sd(bloga, INF)
Definition at line 96 of file sdpow.cpp.
Referenced by __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), and __pgm_exp_d_vec512_slowpath().
a_sign
a_sign = (__m128i)_mm_and_pd(a, SGN_MASK)
Definition at line 142 of file sdpow.cpp.
abs_a
abs_a = _mm_and_pd(a, (__m128d)ABS_MASK)
Definition at line 143 of file sdpow.cpp.
Referenced by __fsd_exp_fma3(), __fsd_pow_fma3(), __fvd_exp_fma3(), and __fvd_exp_fma3_256().
abs_b
abs_b = _mm_and_pd(b, (__m128d)ABS_MASK)
Definition at line 143 of file sdpow.cpp.
abs_bloga
__m128i abs_bloga = _mm_and_si128((__m128i)bloga, ABS_MASK)
Definition at line 91 of file sdpow.cpp.
Referenced by __fsd_pow_fma3().
abs_lt
__m128d abs_lt = (__m128d)_mm_and_si128((__m128i)abs_bloga, HI_ABS_MASK)
Definition at line 92 of file sdpow.cpp.
Referenced by __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), and __pgm_exp_d_vec512_slowpath().
ABS_MASK
__m512i const ABS_MASK = _mm_set1_epi64x(ABS_MASK_D)
Definition at line 88 of file sdpow.cpp.
Referenced by __fsd_pow_fma3(), __fvd_acos_fma3(), __fvd_acos_fma3_256(), __fvd_asin_fma3(), __fvd_asin_fma3_256(), __fvs_acos_fma3(), __fvs_acos_fma3_256(), __fvs_asin_fma3(), and __fvs_asin_fma3_256().
absa_gt_one
__m128d absa_gt_one = _mm_cmp_sd(abs_a, ONE, _CMP_GT_OS)
Definition at line 204 of file sdpow.cpp.
accurate_scale_mask
__m128d accurate_scale_mask = (__m128d)_mm_cmp_sd(abs_lt, UPPERBOUND_2, _CMP_LT_OS)
Definition at line 99 of file sdpow.cpp.
Referenced by __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), and __pgm_exp_d_vec512_slowpath().
ahi_lt_0
__m128d ahi_lt_0 = (__m128d)_mm_cmpeq_epi64(a_sign, (__m128i)ZERO)
Definition at line 165 of file sdpow.cpp.
ahilt0_and_boddint_mask
__m128d ahilt0_and_boddint_mask = _mm_andnot_pd(ahi_lt_0, (__m128d)bIsOddInteger)
Definition at line 166 of file sdpow.cpp.
ans_equals_one_mask
__m128d ans_equals_one_mask = _mm_or_pd(a_is_one_mask, b_is_zero_mask)
Definition at line 224 of file sdpow.cpp.
aorb_nan_mask
__m128i aorb_nan_mask = _mm_and_si128(a_nan_mask, b_nan_mask)
Definition at line 218 of file sdpow.cpp.
b
__m128d __m128d const b
Definition at line 124 of file sdpow.cpp.
Referenced by __fsd_pow_fma3().
b_inf_mask
__m128d b_inf_mask = (__m128d)_mm_cmpeq_epi64((__m128i)abs_b, (__m128i)INF)
Definition at line 202 of file sdpow.cpp.
b_is_half
__m128i b_is_half = _mm_cmpeq_epi64((__m128i)abs_b, (__m128i)HALF)
Definition at line 157 of file sdpow.cpp.
b_is_integer
__m128i b_is_integer = (__m128i)_mm_cmp_pd(b, _mm_floor_pd(b), _CMP_EQ_OQ)
Definition at line 232 of file sdpow.cpp.
b_is_integer_flag
int b_is_integer_flag = _mm_movemask_epi8((__m128i)b_is_integer)
Definition at line 233 of file sdpow.cpp.
b_is_lt_zero
__m128i b_is_lt_zero = (__m128i)_mm_cmp_pd(b, ZERO, _CMP_LT_OS)
Definition at line 235 of file sdpow.cpp.
b_is_lt_zero_flag
int b_is_lt_zero_flag = _mm_movemask_epi8((__m128i)b_is_lt_zero)
Definition at line 236 of file sdpow.cpp.
b_is_zero_mask
__m128d b_is_zero_mask = (__m128d)_mm_cmpeq_epi64((__m128i)abs_b, (__m128i)ZERO)
Definition at line 223 of file sdpow.cpp.
b_nan_mask
__m128i b_nan_mask = _mm_cmpeq_epi64(_mm_max_epu32((__m128i)abs_b, INF_FAKE), INF_FAKE)
Definition at line 217 of file sdpow.cpp.
b_ne_trunc
__m128d b_ne_trunc = _mm_cmp_sd(b, _mm_round_pd(b, _MM_FROUND_TO_ZERO), _CMP_NEQ_UQ)
Definition at line 171 of file sdpow.cpp.
b_sign
b_sign = (__m128i)_mm_and_pd(b, SGN_MASK)
Definition at line 142 of file sdpow.cpp.
bhi_lt_0
__m128d bhi_lt_0 = (__m128d)_mm_cmpeq_epi64(b_sign, (__m128i)ZERO)
Definition at line 183 of file sdpow.cpp.
bIsOddInteger
bIsOddInteger = _mm_sllv_epi64((__m128i)b, shiftb)
Definition at line 142 of file sdpow.cpp.
bloga
__m128d __m128d const __m128d const bloga
Definition at line 81 of file sdpow.cpp.
Referenced by __fsd_pow_fma3().
ELEVEN
__m128i const ELEVEN = _mm_set1_epi64x(ELEVEN_D)
Definition at line 140 of file sdpow.cpp.
HALF
__m128d const HALF = _mm_set1_pd(HALF_D)
Definition at line 132 of file sdpow.cpp.
HI_ABS_MASK
__m128i const HI_ABS_MASK = _mm_set1_epi64x(HI_ABS_MASK_D)
Definition at line 87 of file sdpow.cpp.
Referenced by __fsd_exp_fma3(), __fsd_pow_fma3(), __fvd_exp_fma3(), __fvd_exp_fma3_256(), __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), and __pgm_exp_d_vec512_slowpath().
i_scale_acc
__m128i i_scale_acc = _mm_slli_epi64(k, D52_D)
Definition at line 103 of file sdpow.cpp.
Referenced by __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), and __pgm_exp_d_vec512_slowpath().
i_scale_acc_2
__m128i i_scale_acc_2 = _mm_slli_epi64(k, D52_D)
Definition at line 105 of file sdpow.cpp.
Referenced by __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), and __pgm_exp_d_vec512_slowpath().
INF
__m128d const INF = (__m128d)_mm_set1_epi64x(INF_D)
Definition at line 86 of file sdpow.cpp.
INF_FAKE
__m128i const INF_FAKE = _mm_set1_epi64x(INF_FAKE_D)
Definition at line 135 of file sdpow.cpp.
isinf_mask
__m128i isinf_mask = _mm_cmpeq_epi64((__m128i)INF, (__m128i)z)
Definition at line 115 of file sdpow.cpp.
k
k = _mm_srli_epi64(i, 1)
Definition at line 102 of file sdpow.cpp.
Referenced by __attribute__(), __fort_bcopysl(), __fort_defaultproc(), __fort_exchange_counts(), __fort_gathscat(), __fort_gcd(), __fort_getmap(), __fort_init_consts(), __fort_initcom(), __fort_set_single(), __fort_use_allocation(), __INT8_T(), __INT_T(), __mth_i_dpowi(), __mth_i_dpowk(), __mth_i_ileadz(), __mth_i_ileadzi(), __mth_i_kleadz(), __mth_i_kpowi(), __mth_i_kpowk(), __mth_i_qpowi(), __mth_i_qpowk(), __mth_i_rpowi(), __mth_i_rpowk(), __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), __pgm_exp_d_vec512_slowpath(), __pmth_i_dpowk(), __pmth_i_qpowk(), __pmth_i_rpowk(), __tan_f_vec(), __vcis_d_kernel(), __vcis_kernel(), _dump_one_ast(), _dumponeilm(), _f90io_encode_fmt(), _printili(), addfieldtosym(), advance_permuted(), alpha(), assign(), bnd_ge(), bnd_le(), bound_add(), btodi(), build_masks(), canonical_conversion(), check_bounds(), check_new_bound(), classify_dec(), classify_smp(), CMPLXFUNC_C_I(), CMPLXFUNC_C_K(), complt(), copy_section_temp_before(), deallocate_arg_value(), direct_hash(), dirv_permute(), div_shift(), do_IL_line(), do_subscript(), double_type(), dtio_read_scalar(), dtio_write_scalar(), dump_ast_tree(), dump_one_bound(), dump_two_bound(), eadd1(), eliminate_extra_idx(), eliminate_redundant(), eliminate_rt(), enter(), ENTF90(), ENTF90IO(), ENTFTN(), etoasc(), eval(), eval_dtio_sb(), eval_sb(), fastset_unit_tests(), find_cc_symbols(), flushsym(), fndnul(), fr_Breadnum(), fr_get_fmtcode(), fr_OZbyte(), fr_OZreadnum(), Ftn_idate(), Ftn_jdate(), Ftn_nstr_copy(), Ftn_nstr_copy_klen(), Ftn_nstrcmp(), Ftn_nstrcmp_klen(), fw_Bwritenum(), fw_get_fmtcode(), fw_OZwritenum(), gatherx_temp_before(), gathscat_element(), gathscat_start(), gentab(), genthd(), get_forall_subscr(), get_token(), get_type(), getline(), ground(), hashmap_lookup(), htodi(), int128_count_leading_zeros(), int128_unsigned_multiply(), is_fusable(), is_in_block(), kind_of(), LZMPLXFUNC_LZ_I(), LZMPLXFUNC_LZ_K(), manmul(), map_to_processor(), merge(), mk_forall_sptr(), nelems_of(), parse_ref(), pntset(), print_loop(), prntgm(), put_inkwd(), putinkind(), rdgram(), reference_for_temp(), same_forall_bnds(), sched_block_breadth_first(), simple_reference_for_temp(), skip_to_next(), sortcg(), sortgm(), tablea(), tableu(), top_sort(), write_ast(), write_nml_val(), xargvar(), xdisint(), xfisint(), xref(), ZMPLXFUNC_Z_I(), and ZMPLXFUNC_Z_K().
lt_zero_mask
__m128d lt_zero_mask = _mm_cmp_sd(bloga, ZERO, _CMP_LT_OS)
Definition at line 93 of file sdpow.cpp.
Referenced by __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), and __pgm_exp_d_vec512_slowpath().
MINUS_ZERO
__m128d const MINUS_ZERO = _mm_set1_pd((double)-0.0)
Definition at line 238 of file sdpow.cpp.
MULT_CONST
__m128i const MULT_CONST = _mm_set1_epi64x(MULT_CONST_D)
Definition at line 89 of file sdpow.cpp.
Referenced by __fsd_exp_fma3(), __fvd_exp_fma3(), __fvd_exp_fma3_256(), __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), and __pgm_exp_d_vec512_slowpath().
multiplier
multiplier = (__m128d)_mm_add_epi64(i_scale_acc_2, MULT_CONST)
Definition at line 106 of file sdpow.cpp.
Referenced by __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), and __pgm_exp_d_vec512_slowpath().
NAN_MASK
__m128d const NAN_MASK = (__m128d)_mm_set1_epi64x(NAN_MASK_D)
Definition at line 136 of file sdpow.cpp.
nan_mask
__m128d nan_mask = _mm_andnot_pd(ahi_lt_0, b_ne_trunc)
Definition at line 172 of file sdpow.cpp.
Referenced by __attribute__(), __pgm_exp_vec128_slowpath(), __pgm_exp_vec256_slowpath(), and __pgm_exp_vec512_slowpath().
NEG_ONE
__m128d const NEG_ONE = _mm_set1_pd(NEG_ONE_D)
Definition at line 129 of file sdpow.cpp.
NEG_ONE_CONST
__m128d const NEG_ONE_CONST = (__m128d)_mm_set1_epi64x(NEG_ONE_CONST_D)
Definition at line 137 of file sdpow.cpp.
ONE
__m128d const ONE = _mm_set1_pd(ONE_D)
Definition at line 131 of file sdpow.cpp.
Referenced by __fsd_log_fma3(), __fsd_pow_fma3(), __fvd_acos_fma3(), __fvd_acos_fma3_256(), __fvd_asin_fma3(), __fvd_asin_fma3_256(), __fvd_log_fma3(), __fvd_log_fma3_256(), __fvs_acos_fma3(), __fvs_acos_fma3_256(), __fvs_asin_fma3(), __fvs_asin_fma3_256(), __rvs_log_fma3(), __rvs_log_fma3_256(), and if().
prodx
__m128d __m128d const __m128d const __m128d __m128d prodx
Initial value:
{
    __m128d const UPPERBOUND_1 = (__m128d)_mm_set1_epi64x(UPPERBOUND_1_D)
Definition at line 81 of file sdpow.cpp.
Referenced by __fsd_pow_fma3().
res
res = (__m128d)_mm_add_epi32(i_scale_acc, (__m128i)t)
Definition at line 109 of file sdpow.cpp.
SGN_EXP_MASK
__m128d const SGN_EXP_MASK = (__m128d)_mm_set1_epi64x(SGN_EXP_MASK_D)
Definition at line 127 of file sdpow.cpp.
Referenced by __fsd_pow_fma3().
SGN_MASK
__m128d const SGN_MASK = (__m128d)_mm_set1_epi64x(SGN_MASK_D)
Definition at line 133 of file sdpow.cpp.
Referenced by __fvd_acos_fma3(), __fvd_acos_fma3_256(), __fvd_asin_fma3(), __fvd_asin_fma3_256(), __fvs_acos_fma3(), __fvs_acos_fma3_256(), __fvs_asin_fma3(), __fvs_asin_fma3_256(), and neg().
shiftb
shiftb = (__m128i)_mm_and_pd (b, SGN_EXP_MASK)
Definition at line 144 of file sdpow.cpp.
slowpath_blend
__m128d slowpath_blend = _mm_blendv_pd(zero_inf_blend, res, accurate_scale_mask)
Definition at line 112 of file sdpow.cpp.
Referenced by __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), and __pgm_exp_d_vec512_slowpath().
slowpath_mask
__m128d slowpath_mask = _mm_cmp_sd(abs_lt, UPPERBOUND_1, _CMP_LT_OS)
Definition at line 94 of file sdpow.cpp.
Referenced by __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), and __pgm_exp_d_vec512_slowpath().
t
return t
Initial value:
{
   __m128i const HI_MASK       = _mm_set1_epi64x(HI_MASK_D)
Definition at line 81 of file sdpow.cpp.
Referenced by __fsd_pow_fma3(), __internal_ddfma(), and __internal_fast_int2dbl().
t_when_ais0
__m128d t_when_ais0 = _mm_and_pd(thi_when_ais0, (__m128d)HI_MASK)
Definition at line 186 of file sdpow.cpp.
TEN_23
__m128i const TEN_23 = _mm_set1_epi64x(TEN_23_D)
Definition at line 139 of file sdpow.cpp.
Referenced by __fsd_log_fma3(), __fsd_pow_fma3(), __fvd_log_fma3(), and __fvd_log_fma3_256().
thi_or_INF
__m128d thi_or_INF = _mm_or_pd(thi_when_ais0, INF)
Definition at line 184 of file sdpow.cpp.
thi_when_ais0
thi_when_ais0 = ZERO
Definition at line 177 of file sdpow.cpp.
thi_when_aisinf
thi_when_aisinf = _mm_blendv_pd(thi_when_aisinf, INF, bhi_lt_0)
Definition at line 193 of file sdpow.cpp.
thi_when_bisinf
thi_when_bisinf = ZERO
Definition at line 203 of file sdpow.cpp.
thi_xor_inf
__m128d thi_xor_inf = _mm_xor_pd(thi_when_bisinf, INF)
Definition at line 207 of file sdpow.cpp.
thi_xor_sgn
__m128d thi_xor_sgn = _mm_xor_pd(thi_when_aisinf, SGN_MASK)
Definition at line 196 of file sdpow.cpp.
UPPERBOUND_2
__m128d const UPPERBOUND_2 = (__m128d)_mm_set1_epi64x(UPPERBOUND_2_D)
Definition at line 84 of file sdpow.cpp.
Referenced by __fsd_exp_fma3(), __fvd_exp_fma3(), __fvd_exp_fma3_256(), __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), and __pgm_exp_d_vec512_slowpath().
z
return z = _mm_blendv_pd(slowpath_blend, z, slowpath_mask)
Definition at line 81 of file sdpow.cpp.
Referenced by __fsd_pow_fma3(), __internal_ddadd_yisdouble(), and __internal_ddfma().
z_fixed
__m128d z_fixed = _mm_fmadd_sd(z, prodx, z)
Definition at line 116 of file sdpow.cpp.
ZERO
__m128d const ZERO = _mm_set1_pd(ZERO_D)
Definition at line 85 of file sdpow.cpp.
Referenced by __fsd_pow_fma3(), and if().
zero_inf_blend
__m128d zero_inf_blend = _mm_blendv_pd(a_plus_inf, ZERO, lt_zero_mask)
Definition at line 97 of file sdpow.cpp.
Referenced by __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), and __pgm_exp_d_vec512_slowpath().