flang: secnds3f.c File Reference
secnds3f.c File Reference
#include "ent3f.h"
#include "enames.h"
Functions
float Ftn_secnds (float)
Returns the number of seconds since midnight minus the supplied value.
float ENT3F (SECNDS, secnds)
Function Documentation
ENT3F()
float ENT3F (SECNDS , secnds)
Definition at line 18 of file secnds3f.c.
References Ftn_secnds(), and x.
Ftn_secnds()
float Ftn_secnds (float x)
Returns the number of seconds since midnight minus the supplied value.
Definition at line 127 of file ftnmiscsup.c.
References called, f, i, localtime(), lt, time(), and x.
Referenced by ENT3F().