flang: semantio.c File Reference
semantio.c File Reference
Semantic analyzer routines which process IO statements.
#include "gbldefs.h"
#include "global.h"
#include "gramsm.h"
#include "gramtk.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "semant.h"
#include "scan.h"
#include "dinit.h"
#include "semstk.h"
#include "ast.h"
#include "feddesc.h"
#include "rte.h"
#include "rtlRtns.h"
Classes
struct iol
struct pt_tag
struct UnformattedRtns
Macros
#define PT_UNIT 0
#define PT_FILE 1
#define PT_IOSTAT 2
#define PT_EXIST 3
#define PT_OPENED 4
#define PT_NUMBER 5
#define PT_NAMED 6
#define PT_NAME 7
#define PT_ACCESS 8
#define PT_SEQUENTIAL 9
#define PT_DIRECT 10
#define PT_FORM 11
#define PT_FORMATTED 12
#define PT_UNFORMATTED 13
#define PT_RECL 14
#define PT_NEXTREC 15
#define PT_BLANK 16
#define PT_POSITION 17
#define PT_ACTION 18
#define PT_READ 19
#define PT_WRITE 20
#define PT_READWRITE 21
#define PT_DELIM 22
#define PT_PAD 23
#define PT_ID 24
#define PT_PENDING 25
#define PT_POS 26
#define PT_SIZE 27
#define PT_ASYNCHRONOUS 28
#define PT_DECIMAL 29
#define PT_ENCODING 30
#define PT_SIGN 31
#define PT_STREAM 32
#define PT_ROUND 33
#define PT_DISPOSE 34
#define PT_END 35
#define PT_ERR 36
#define PT_FMT 37
#define PT_NML 38
#define PT_REC 39
#define PT_STATUS 40
#define PT_ADVANCE 41
#define PT_EOR 42
#define PT_IOLENGTH 43
#define PT_CONVERT 44
#define PT_SHARED 45
#define PT_IOMSG 46
#define PT_NEWUNIT 47
#define PT_LAST_INQUIRE_VALf95 PT_PAD
#define PT_LAST_INQUIRE_VAL 33
#define PT_MAXV 47
#define BT_ACCEPT 0x00001
#define BT_BKSPACE 0x00002
#define BT_CLOSE 0x00004
#define BT_DECODE 0x00008
#define BT_ENCODE 0x00010
#define BT_ENDFILE 0x00020
#define BT_INQUIRE 0x00040
#define BT_OPEN 0x00080
#define BT_PRINT 0x00100
#define BT_READ 0x00200
#define BT_REWIND 0x00400
#define BT_WRITE 0x00800
#define BT_WAIT 0x01000
#define BT_FLUSH 0x02000
#define PUT(n) (_put((INT)(n), DT_INT))
#define DEFAULT_UNIT (is_read ? 5 : 6)
#define IOERR(n) errsev(n)
#define IOERR2(n, s) error(n, 3, gbl.lineno, s, CNULL)
#define ERR170(s) error(170, 2, gbl.lineno, s, CNULL)
#define ERR204(s1, s2) error(204, 3, gbl.lineno, s1, s2)
#define PTV(d) pt[d].val
#define PT_CHECK(a, b)
#define PTS(a) pt[a].set
#define PT_SET(a) PTS(a) = 1
#define PTVARREF(a) pt[a].varref
#define PT_VARREF(a, v) PTVARREF(a) = (v)
#define PTTMPUSED(a) pt[a].tmp_in_use
#define PT_TMPUSED(a, v) (pt[a].tmp_in_use = (v))
#define PTARG(a) (PTVARREF(a) && PTVARREF(a) != 1 ? PT_TMPUSED(a, 1), PTV(a) : PTV(a))
#define PTNAME(a) pt[a].name
#define PTSTMT(a) pt[a].stmt
#define UNIT_CHECK
#define IE_EXPR 0
#define IE_DOBEGIN 1
#define IE_DOEND 2
#define IE_OPTDO 3
#define BITV_IOSTAT 0x01
#define BITV_ERR 0x02
#define BITV_END 0x04
#define BITV_EOR 0x08
#define BITV_IOMSG 0x10
#define BITV_SIZE 0x020
#define BITV_ADVANCE 0x040
#define BYTE_SWAPPED_IO (XBIT(125, 0x2) != 0)
#define LARGE_ARRAY (XBIT(68, 1) != 0)
#define BYTE_SWAPPED_IO_IDX ((BYTE_SWAPPED_IO) ? 1 : 0)
#define LARGE_ARRAY_IDX ((LARGE_ARRAY) ? 1 : 0)
#define BYTE_RW_IDX 2
Typedefs
typedef struct iol IOL
Enumerations
enum FormatType {
FT_UNFORMATTED = 1 , FT_LIST_DIRECTED = 2 , FT_ENCODED = 3 , FT_CHARACTER = 4 ,
FT_NML = 5 , FT_FMTSTR = 6 , FT_LAST = 7
}
Functions
static int set_io_sc (void)
static int copy_replic_sect_to_tmp (int)
static void copy_back_to_replic_sect (int, int)
static void fix_iostat (void)
static int add_cgoto (int)
static int end_or_err (int, int, int)
static int fio_end_err (int, int)
static void chk_expr (SST *, int, int)
static void chk_var (SST *, int, int)
static void gen_spec_item_tmp (SST *, int, int)
static void chk_unitid (SST *)
static void chk_fmtid (SST *)
static void chk_iospec (void)
static void put_edit (int)
static void put_ffield (SST *)
static void kwd_errchk (int)
static int get_fmt_array (int, int)
static int ast_ioret (void)
static int mk_iofunc (FtnRtlEnum, int, int)
static int mk_hpfiofunc (FtnRtlEnum, int, int)
static LOGICAL need_descriptor_ast (int)
static void rw_array (int, int, int, FtnRtlEnum)
static void get_derived_iolptrs (SST *, int, SST *)
static void gen_derived_io (int, FtnRtlEnum, int)
static void gen_lastval (DOINFO *)
static int misc_io_checks (const char *)
static void iomsg_check (void)
static void newunit_check (void)
static void put_vlist (SST *)
static FtnRtlEnum getBasicScalarRWRtn (LOGICAL, FormatType)
static FtnRtlEnum getAggrRWRtn (LOGICAL)
static FtnRtlEnum getWriteByDtypeRtn (int, FormatType)
static FtnRtlEnum getArrayRWRtn (LOGICAL, FormatType, int, LOGICAL)
static ITEM * gen_dtio_args (SST *, int, int, int)
static int gen_dtsfmt_args (int *, int *)
static int call_dtsfmt (int, int)
static int get_defined_io_call (int, int, ITEM *)
static int begin_io_call (int, int, int)
static void add_io_arg (int)
static int end_io_call (void)
static void _put (INT, int)
void semantio (int rednum, SST *top)
Semantic analysis of IO statements.
static int chk_SIZE_var ()
char * cntl_name (int p)
const char * ed_name (int ed)
int get_nml_array (int nml)
Create the array (ST_PLIST) representing the namelist.
static IOL * find_end_iollist (IOL *in_iolptr)
static IOL * link_iollist (IOL *first, IOL *last)
static IOL * get_dobegin (int ast1, int ast2, int ast3)
static IOL * get_doend (DOINFO *doinfo)
static int replace_vector_subscript (int ast, int indexast)
static IOL * add_iolptrs (int dtype, SST *in_stkptr, int *mndscp)
Variables
struct {
int ast
int ast_type
int std
} io_call
static int functype [2][FT_LAST]
static struct pt_tag pt [PT_MAXV+1]
static FormatType fmttyp
static int nml_group
static int intern_array
static int intern_tmp
static LOGICAL intern
static LOGICAL external_io
static LOGICAL nondevice_io
static LOGICAL is_read
static LOGICAL no_rw
static LOGICAL print_star
static LOGICAL unit_star
static int fmt_is_var
static int fasize
static int rescan
static int lastrpt
static int edit_state
static int last_edit
static int fmt_length
static int filename_type = 0
static int iolist
static LOGICAL noparens
static LOGICAL open03
static LOGICAL rw03
static INT bitv
UnformattedRtns unf_nm [][3]
UnformattedRtns array_unf_nm [][3]
struct {
FtnRtlEnum read [2]
FtnRtlEnum write [2]
} fmt_init []
struct {
FtnRtlEnum read [2]
FtnRtlEnum write [2]
} fmt_inite
static int io_sc
Detailed Description
Semantic analyzer routines which process IO statements.
Definition in file semantio.c.
Macro Definition Documentation
BITV_ADVANCE
#define BITV_ADVANCE 0x040
Definition at line 325 of file semantio.c.
BITV_END
#define BITV_END 0x04
Definition at line 317 of file semantio.c.
BITV_EOR
#define BITV_EOR 0x08
Definition at line 318 of file semantio.c.
BITV_ERR
#define BITV_ERR 0x02
Definition at line 316 of file semantio.c.
BITV_IOMSG
#define BITV_IOMSG 0x10
Definition at line 319 of file semantio.c.
BITV_IOSTAT
#define BITV_IOSTAT 0x01
Definition at line 315 of file semantio.c.
BITV_SIZE
#define BITV_SIZE 0x020
Definition at line 324 of file semantio.c.
BT_ACCEPT
#define BT_ACCEPT 0x00001
Definition at line 122 of file semantio.c.
BT_BKSPACE
#define BT_BKSPACE 0x00002
Definition at line 123 of file semantio.c.
BT_CLOSE
#define BT_CLOSE 0x00004
Definition at line 124 of file semantio.c.
BT_DECODE
#define BT_DECODE 0x00008
Definition at line 125 of file semantio.c.
BT_ENCODE
#define BT_ENCODE 0x00010
Definition at line 126 of file semantio.c.
BT_ENDFILE
#define BT_ENDFILE 0x00020
Definition at line 127 of file semantio.c.
BT_FLUSH
#define BT_FLUSH 0x02000
Definition at line 135 of file semantio.c.
BT_INQUIRE
#define BT_INQUIRE 0x00040
Definition at line 128 of file semantio.c.
BT_OPEN
#define BT_OPEN 0x00080
Definition at line 129 of file semantio.c.
BT_PRINT
#define BT_PRINT 0x00100
Definition at line 130 of file semantio.c.
BT_READ
#define BT_READ 0x00200
Definition at line 131 of file semantio.c.
BT_REWIND
#define BT_REWIND 0x00400
Definition at line 132 of file semantio.c.
BT_WAIT
#define BT_WAIT 0x01000
Definition at line 134 of file semantio.c.
BT_WRITE
#define BT_WRITE 0x00800
Definition at line 133 of file semantio.c.
BYTE_RW_IDX
#define BYTE_RW_IDX 2
Definition at line 344 of file semantio.c.
BYTE_SWAPPED_IO
#define BYTE_SWAPPED_IO (XBIT(125, 0x2) != 0)
Definition at line 327 of file semantio.c.
BYTE_SWAPPED_IO_IDX
#define BYTE_SWAPPED_IO_IDX ((BYTE_SWAPPED_IO) ? 1 : 0)
Definition at line 342 of file semantio.c.
DEFAULT_UNIT
#define DEFAULT_UNIT (is_read ? 5 : 6)
Definition at line 160 of file semantio.c.
ERR170
#define ERR170 (s) error(170, 2, gbl.lineno, s, CNULL)
Definition at line 163 of file semantio.c.
ERR204
#define ERR204 (s1, s2) error(204, 3, gbl.lineno, s1, s2)
Definition at line 164 of file semantio.c.
IE_DOBEGIN
#define IE_DOBEGIN 1
Definition at line 195 of file semantio.c.
IE_DOEND
#define IE_DOEND 2
Definition at line 196 of file semantio.c.
IE_EXPR
#define IE_EXPR 0
Definition at line 194 of file semantio.c.
IE_OPTDO
#define IE_OPTDO 3
Definition at line 197 of file semantio.c.
IOERR
#define IOERR (n) errsev(n)
Definition at line 161 of file semantio.c.
IOERR2
#define IOERR2 (n, s) error(n, 3, gbl.lineno, s, CNULL)
Definition at line 162 of file semantio.c.
LARGE_ARRAY
#define LARGE_ARRAY (XBIT(68, 1) != 0)
Definition at line 328 of file semantio.c.
LARGE_ARRAY_IDX
#define LARGE_ARRAY_IDX ((LARGE_ARRAY) ? 1 : 0)
Definition at line 343 of file semantio.c.
PT_ACCESS
#define PT_ACCESS 8
Definition at line 63 of file semantio.c.
PT_ACTION
#define PT_ACTION 18
Definition at line 73 of file semantio.c.
PT_ADVANCE
#define PT_ADVANCE 41
Definition at line 106 of file semantio.c.
PT_ASYNCHRONOUS
#define PT_ASYNCHRONOUS 28
Definition at line 83 of file semantio.c.
PT_BLANK
#define PT_BLANK 16
Definition at line 71 of file semantio.c.
PT_CHECK
#define PT_CHECK (a, b)
Value:
  if (PTV(a) == 0)     \
  PTV(a) = b
Definition at line 167 of file semantio.c.
PT_CONVERT
#define PT_CONVERT 44
Definition at line 109 of file semantio.c.
PT_DECIMAL
#define PT_DECIMAL 29
Definition at line 84 of file semantio.c.
PT_DELIM
#define PT_DELIM 22
Definition at line 77 of file semantio.c.
PT_DIRECT
#define PT_DIRECT 10
Definition at line 65 of file semantio.c.
PT_DISPOSE
#define PT_DISPOSE 34
Definition at line 99 of file semantio.c.
PT_ENCODING
#define PT_ENCODING 30
Definition at line 85 of file semantio.c.
PT_END
#define PT_END 35
Definition at line 100 of file semantio.c.
PT_EOR
#define PT_EOR 42
Definition at line 107 of file semantio.c.
PT_ERR
#define PT_ERR 36
Definition at line 101 of file semantio.c.
PT_EXIST
#define PT_EXIST 3
Definition at line 58 of file semantio.c.
PT_FILE
#define PT_FILE 1
Definition at line 56 of file semantio.c.
PT_FMT
#define PT_FMT 37
Definition at line 102 of file semantio.c.
PT_FORM
#define PT_FORM 11
Definition at line 66 of file semantio.c.
PT_FORMATTED
#define PT_FORMATTED 12
Definition at line 67 of file semantio.c.
PT_ID
#define PT_ID 24
Definition at line 79 of file semantio.c.
PT_IOLENGTH
#define PT_IOLENGTH 43
Definition at line 108 of file semantio.c.
PT_IOMSG
#define PT_IOMSG 46
Definition at line 111 of file semantio.c.
PT_IOSTAT
#define PT_IOSTAT 2
Definition at line 57 of file semantio.c.
PT_LAST_INQUIRE_VAL
#define PT_LAST_INQUIRE_VAL 33
Definition at line 115 of file semantio.c.
PT_LAST_INQUIRE_VALf95
#define PT_LAST_INQUIRE_VALf95 PT_PAD
Definition at line 114 of file semantio.c.
PT_MAXV
#define PT_MAXV 47
Definition at line 116 of file semantio.c.
PT_NAME
#define PT_NAME 7
Definition at line 62 of file semantio.c.
PT_NAMED
#define PT_NAMED 6
Definition at line 61 of file semantio.c.
PT_NEWUNIT
#define PT_NEWUNIT 47
Definition at line 112 of file semantio.c.
PT_NEXTREC
#define PT_NEXTREC 15
Definition at line 70 of file semantio.c.
PT_NML
#define PT_NML 38
Definition at line 103 of file semantio.c.
PT_NUMBER
#define PT_NUMBER 5
Definition at line 60 of file semantio.c.
PT_OPENED
#define PT_OPENED 4
Definition at line 59 of file semantio.c.
PT_PAD
#define PT_PAD 23
Definition at line 78 of file semantio.c.
PT_PENDING
#define PT_PENDING 25
Definition at line 80 of file semantio.c.
PT_POS
#define PT_POS 26
Definition at line 81 of file semantio.c.
PT_POSITION
#define PT_POSITION 17
Definition at line 72 of file semantio.c.
PT_READ
#define PT_READ 19
Definition at line 74 of file semantio.c.
PT_READWRITE
#define PT_READWRITE 21
Definition at line 76 of file semantio.c.
PT_REC
#define PT_REC 39
Definition at line 104 of file semantio.c.
PT_RECL
#define PT_RECL 14
Definition at line 69 of file semantio.c.
PT_ROUND
#define PT_ROUND 33
Definition at line 88 of file semantio.c.
PT_SEQUENTIAL
#define PT_SEQUENTIAL 9
Definition at line 64 of file semantio.c.
PT_SET
#define PT_SET (a) PTS(a) = 1
Definition at line 171 of file semantio.c.
PT_SHARED
#define PT_SHARED 45
Definition at line 110 of file semantio.c.
PT_SIGN
#define PT_SIGN 31
Definition at line 86 of file semantio.c.
PT_SIZE
#define PT_SIZE 27
Definition at line 82 of file semantio.c.
PT_STATUS
#define PT_STATUS 40
Definition at line 105 of file semantio.c.
PT_STREAM
#define PT_STREAM 32
Definition at line 87 of file semantio.c.
PT_TMPUSED
#define PT_TMPUSED (a, v) (pt[a].tmp_in_use = (v))
Definition at line 175 of file semantio.c.
PT_UNFORMATTED
#define PT_UNFORMATTED 13
Definition at line 68 of file semantio.c.
PT_UNIT
#define PT_UNIT 0
Definition at line 55 of file semantio.c.
PT_VARREF
#define PT_VARREF (a, v) PTVARREF(a) = (v)
Definition at line 173 of file semantio.c.
PT_WRITE
#define PT_WRITE 20
Definition at line 75 of file semantio.c.
PTARG
#define PTARG (a) (PTVARREF(a) && PTVARREF(a) != 1 ? PT_TMPUSED(a, 1), PTV(a) : PTV(a))
Definition at line 176 of file semantio.c.
PTNAME
#define PTNAME (a) pt[a].name
Definition at line 178 of file semantio.c.
PTS
#define PTS (a) pt[a].set
Definition at line 170 of file semantio.c.
PTSTMT
#define PTSTMT (a) pt[a].stmt
Definition at line 179 of file semantio.c.
PTTMPUSED
#define PTTMPUSED (a) pt[a].tmp_in_use
Definition at line 174 of file semantio.c.
PTV
#define PTV (d) pt[d].val
Definition at line 166 of file semantio.c.
PTVARREF
#define PTVARREF (a) pt[a].varref
Definition at line 172 of file semantio.c.
PUT
#define PUT (n) (_put((INT)(n), DT_INT))
Definition at line 138 of file semantio.c.
UNIT_CHECK
#define UNIT_CHECK
Value:
  if (PTV(PT_UNIT) == 0) \
  IOERR(200)
Definition at line 180 of file semantio.c.
Typedef Documentation
IOL
typedef struct iol IOL
Enumeration Type Documentation
FormatType
enum FormatType
Enumerator
FT_UNFORMATTED
FT_LIST_DIRECTED
FT_ENCODED
FT_CHARACTER
FT_NML
FT_FMTSTR
FT_LAST
Definition at line 141 of file semantio.c.
Function Documentation
_put()
static void _put (INT n, int dtype) static
Definition at line 4881 of file semantio.c.
References cngcon(), DBGBIT, dinit_put(), DTY, fasize, gbl, n, and TY_INT8.
add_cgoto()
static int add_cgoto (int ast) static
Definition at line 4333 of file semantio.c.
References add_stmt_after(), ast, astb, chk_SIZE_var(), DT_INT, end_or_err(), ASTB::i1, io_call, mk_cval(), mkRteRtnNm(), PT_END, PT_EOR, PT_ERR, PT_SIZE, PT_TMPUSED, PTV, RTE_f90io_fmtr_end, RTE_f90io_inquirea, STD_PREV, and SYMNAME.
Referenced by semantio().
add_io_arg()
static void add_io_arg (int arg) static
Definition at line 5058 of file semantio.c.
References add_arg(), and arg.
Referenced by gen_derived_io(), iomsg_check(), rw_array(), and semantio().
add_iolptrs()
static IOL * add_iolptrs (int dtype, SST * in_stkptr, int * mndscp) static
Definition at line 5395 of file semantio.c.
References add_iolptrs(), ADD_LWAST, ADD_NUMDIM, ADD_UPAST, ASD_NDIM, ASD_SUBS, assert, ast, astb, CNULL, DDTG, SEM::defined_io_seen, DT_INT, DTY, DTYG, iol::element, error(), find_end_iollist(), gbl, get_dobegin(), get_doend(), getitem(), i, ASTB::i0, ASTB::i1, iol::id, IE_EXPR, init(), interr(), is_tbp_or_final(), j, iol::l_std, link_iollist(), mk_binop(), mk_id(), mk_subscr(), mkmember(), iol::next, NOSYM, NULL, OP_DIV, OP_SUB, replace_ast_subtree(), replace_vector_subscript(), S_DERIVED, S_EXPR, S_IDENT, S_LVALUE, sem, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, SST_ASTG, SST_ASTP, SST_CVLENP, SST_DTYPEP, SST_IDG, SST_IDP, SST_SHAPEP, SST_SYMG, stride, sym_of_ast(), SYMNAME, test_private_dtype(), and tmp.
Referenced by add_iolptrs(), and get_derived_iolptrs().
ast_ioret()
static int ast_ioret (void) static
Definition at line 5009 of file semantio.c.
References ast, STB::curr_scope, declsym_newscope(), DT_INT, getsymbol(), io_sc, mk_id(), sptr, and stb.
Referenced by call_dtsfmt(), end_io_call(), and semantio().
begin_io_call()
static int begin_io_call (int ast_type, int func, int count) static
Definition at line 5049 of file semantio.c.
References ast_type, begin_call(), count, func, and io_call.
Referenced by fio_end_err(), iomsg_check(), rw_array(), and semantio().
call_dtsfmt()
static int call_dtsfmt (int iotype_ast, int vlist_ast) static
Definition at line 5843 of file semantio.c.
References add_arg(), add_stmt(), ast_ioret(), begin_call(), DT_INT, getcon(), is_read, mk_assn_stmt(), mk_id(), mk_iofunc(), RTE_f90io_dts_fmtr, RTE_f90io_dts_fmtw, sptr, val, void(), and XBIT.
Referenced by semantio().
chk_expr()
static void chk_expr (SST * stk, int p, int dtype) static
Definition at line 4448 of file semantio.c.
References chktyp(), dt, DT_ISINT, DTY, FALSE, IOERR2, is_varref(), mkarg(), mkexpr(), p, PT_VARREF, PTNAME, PTV, SST_ASTG, SST_DTYPEG, stk, TY_CHAR, TY_NCHAR, and void().
Referenced by semantio().
chk_fmtid()
static void chk_fmtid (SST * stk) static
Definition at line 4588 of file semantio.c.
References AD_ASSUMSZ, AD_DPTR, AD_NUMELM, astb, CNULL, CONVAL2G, declref(), DTY, DTYG, error(), SEM::flabels, flg, fmt_is_var, fmt_length, fmttyp, FT_CHARACTER, FT_ENCODED, FT_FMTSTR, FT_LIST_DIRECTED, FT_UNFORMATTED, gbl, get_fmt_array(), getsymf(), ASTB::i0, ASTB::i1, IOERR, IOERR2, is_read, legal_labelvar(), mk_id(), mkarg(), mklabelvar(), NOSYM, NULL, print_star, PT_FMT, PTV, RFCNTI, S_CONST, S_IDENT, S_LVALUE, sem, sptr, SST_ASTG, SST_CVALG, SST_DTYPEG, SST_IDG, FLG::standard, stk, TRUE, TY_CHAR, TY_INT8, unit_star, void(), XBIT, FLG::xref, and xrefput().
Referenced by semantio().
chk_iospec()
static void chk_iospec (void) static
Definition at line 4702 of file semantio.c.
References bitv, BITV_ADVANCE, BITV_EOR, BITV_SIZE, DTY, FALSE, flg, intern, IOERR2, STB::n_base, PT_ADVANCE, PTV, FLG::standard, stb, TRUE, and TY_CHAR.
Referenced by semantio().
chk_SIZE_var()
static int chk_SIZE_var () static
Definition at line 4318 of file semantio.c.
References mk_assn_stmt(), mk_convert(), PT_SIZE, PTS, PTTMPUSED, PTV, and PTVARREF.
Referenced by add_cgoto(), and end_or_err().
chk_unitid()
static void chk_unitid (SST * stk) static
Definition at line 4536 of file semantio.c.
References chktyp(), DEFAULT_UNIT, DT_INT, DT_ISINT, DTYG, error(), FALSE, gbl, intern, IOERR, IOERR2, is_read, mk_cval(), mkarg(), no_rw, NULL, PT_NEWUNIT, PT_UNIT, PTS, PTV, S_IDENT, S_LVALUE, sptr, SST_ASTG, SST_DTYPEG, SST_IDG, stk, sym_of_ast(), SYMNAME, TRUE, TY_CHAR, void(), and XBIT.
Referenced by semantio().
chk_var()
static void chk_var (SST * stk, int p, int dtype) static
Definition at line 4496 of file semantio.c.
References astb, DOCHK, dt, DT_ISINT, DT_ISLOG, SEM::dtemps, DTY, getcctmp_sc(), i, ASTB::i0, io_sc, IOERR2, is_varref(), mkarg(), p, PT_VARREF, PTNAME, PTV, PTVARREF, S_IDENT, sem, sptr, SST_ASTG, SST_ASTP, SST_DTYPEG, SST_DTYPEP, SST_IDP, SST_SYMP, stk, and void().
Referenced by semantio().
cntl_name()
char * cntl_name (int p)
Definition at line 4908 of file semantio.c.
References buf, len, p, PTNAME, and strlen().
copy_back_to_replic_sect()
static void copy_back_to_replic_sect (int array_ast, int tmp_ast) static
Definition at line 4284 of file semantio.c.
References add_stmt_after(), DDTG, mk_assn_stmt(), mk_mem_deallocate(), sptr_of_subscript(), std, and STD_LAST.
Referenced by semantio().
copy_replic_sect_to_tmp()
static int copy_replic_sect_to_tmp (int array_ast) static
Definition at line 4247 of file semantio.c.
References add_stmt(), DDTG, mk_assn_stmt(), mk_id(), mk_mem_allocate(), mk_shape_sptr(), sptr_of_subscript(), std, and subscr.
Referenced by semantio().
ed_name()
const char * ed_name (int ed)
Definition at line 4922 of file semantio.c.
end_io_call()
static int end_io_call (void) static
Definition at line 5071 of file semantio.c.
References add_stmt_after(), ast_ioret(), DT_INT, i, io_call, mk_assn_stmt(), mk_convert(), PT_IOSTAT, PT_MAXV, PT_SIZE, PT_TMPUSED, PTS, PTTMPUSED, PTV, PTVARREF, and STD_PREV.
Referenced by fio_end_err(), and semantio().
end_or_err()
static int end_or_err (int src, int elab, int eqval) static
Definition at line 4376 of file semantio.c.
References add_stmt_after(), ast, chk_SIZE_var(), DT_LOG, fio_end_err(), getlab(), mk_binop(), mk_label(), mk_stmt(), mk_unop(), OP_EQ, OP_LNOT, RFCNTI, src, std, STD_LABEL, STD_PREV, and tmp.
Referenced by add_cgoto().
find_end_iollist()
static IOL * find_end_iollist (IOL * in_iolptr) static
Definition at line 5170 of file semantio.c.
References iol::next, and NULL.
Referenced by add_iolptrs(), get_derived_iolptrs(), and link_iollist().
fio_end_err()
static int fio_end_err (int lab, int elab) static
Definition at line 4426 of file semantio.c.
References A_STDG, FLG::accmp, add_stmt_after(), ast, begin_io_call(), end_io_call(), flg, mk_iofunc(), mk_label(), mk_stmt(), RTE_f90io_end, FLG::smp, STD_LABEL, STD_PREV, sym_mkfunc_nodesc(), void(), and XBIT.
Referenced by end_or_err().
fix_iostat()
static void fix_iostat (void) static
Definition at line 4311 of file semantio.c.
References astb, ASTB::i0, PT_IOSTAT, and PTV.
Referenced by semantio().
gen_derived_io()
static void gen_derived_io (int sptr, FtnRtlEnum rtlRtn, int read) static
Definition at line 5675 of file semantio.c.
References add_io_arg(), astb, DT_INT, i, ASTB::i0, ASTB::i1, INTENT_IN, interr(), mk_cval(), mk_id(), mk_iofunc(), read, size_of(), sptr, and void().
Referenced by semantio().
gen_dtio_args()
static ITEM * gen_dtio_args (SST * stkptr, int arg1, int iotype_ast, int vlist_ast) static
Definition at line 5888 of file semantio.c.
References AD_DPTR, AD_LWAST, AD_LWBD, AD_MLPYR, AD_UPAST, AD_UPBD, add_nullify_ast(), add_stmt(), ast_type, astb, CONVAL2G, DT_INT, SEM::dtemps, fmttyp, FT_UNFORMATTED, get_array_dtype(), getcctmp_sc(), getcon(), getitem(), ASTB::i0, ASTB::i1, intern, io_sc, ITEM_END, mk_assn_stmt(), mk_cnst(), mk_convert(), mk_id(), mkexpr(), mkident(), NULL, p, PT_IOMSG, PT_IOSTAT, PT_UNIT, PTARG, S_CONST, S_EXPR, S_IDENT, sem, sptr, SST_ASTP, SST_CVALP, SST_DTYPEP, SST_IDP, SST_LSYMP, SST_PARENP, SST_SHAPEP, SST_SYMP, TRUE, void(), and XBIT.
Referenced by semantio().
gen_dtsfmt_args()
static int gen_dtsfmt_args (int * iotype_ast, int * vlist_ast) static
Definition at line 5780 of file semantio.c.
References AD_DPTR, ADD_DEFER, add_nullify_ast(), add_stmt(), DT_INT, DT_PTR, SEM::dtemps, get_all_descriptors(), get_array_dtype(), get_next_sym(), get_static_descriptor(), getcctmp_sc(), io_sc, mk_id(), sem, sptr, SYMNAME, and XBIT.
Referenced by semantio().
gen_lastval()
static void gen_lastval (DOINFO * doinfo) static
Definition at line 5704 of file semantio.c.
References add_stmt(), ast, ast_intr(), astb, DOINFO::count, ASTB::i0, DOINFO::index_var, DOINFO::init_expr, mk_assn_stmt(), mk_binop(), mk_convert(), mk_id(), OP_ADD, OP_MUL, DOINFO::step_expr, and void().
Referenced by semantio().
gen_spec_item_tmp()
static void gen_spec_item_tmp (SST * stk, int p, int dtype) static
Definition at line 4473 of file semantio.c.
References DOCHK, dt, SEM::dtemps, DTY, getcctmp_sc(), i, io_sc, mkarg(), p, PT_VARREF, PTV, PTVARREF, S_IDENT, sem, sptr, SST_ASTG, SST_DTYPEP, SST_IDP, SST_SYMP, stk, and void().
Referenced by semantio().
get_defined_io_call()
static int get_defined_io_call (int fsptr, int argcnt, ITEM * arglist) static
Definition at line 6037 of file semantio.c.
References add_arg(), xyyz::ast, ast, begin_call(), get_implementation(), i, ITEM_END, mem(), memsym_of_ast(), mk_id(), mk_member(), and p.
Referenced by semantio().
get_derived_iolptrs()
static void get_derived_iolptrs (SST * result, int sptr1, SST * instkptr) static
Definition at line 5663 of file semantio.c.
References add_iolptrs(), find_end_iollist(), NULL, result, SST_BEGP, SST_DTYPEG, SST_ENDP, and start.
Referenced by semantio().
get_dobegin()
static IOL * get_dobegin (int ast1, int ast2, int ast3) static
Definition at line 5201 of file semantio.c.
References astb, ASTB::bnd, count, DOINFO::count, iol::doinfo, ASTB::dtype, get_doinfo(), get_temp(), getitem(), iol::id, IE_DOBEGIN, DOINFO::index_var, DOINFO::init_expr, iol::l_std, DOINFO::limit_expr, mk_binop(), iol::next, NULL, ASTB::one, OP_ADD, OP_DIV, OP_SUB, sptr, DOINFO::step_expr, and ASTB::zero.
Referenced by add_iolptrs().
get_doend()
static IOL * get_doend (DOINFO * doinfo) static
Definition at line 5240 of file semantio.c.
References iol::doinfo, getitem(), iol::id, IE_DOEND, iol::l_std, iol::next, and NULL.
Referenced by add_iolptrs().
get_fmt_array()
static int get_fmt_array (int lab, int stype) static
Definition at line 4938 of file semantio.c.
References BLK_UPLEVEL_SPTR, STB::curr_scope, declsym_newscope(), gbl, getsymbol(), insert_sym(), name, SEM::orph, p, SEM::parallel, SEM::scope_level, sem, set_parref_flag(), sptr, stb, SYMNAME, SEM::target, and SEM::teams.
Referenced by chk_fmtid(), and semantio().
get_nml_array()
int get_nml_array (int nml)
Create the array (ST_PLIST) representing the namelist.
The name is derived from the namelist group name.
Definition at line 4990 of file semantio.c.
References DT_PTR, get_next_sym(), nml, sptr, and SYMNAME.
Referenced by semant1(), and semantio().
getAggrRWRtn()
static FtnRtlEnum getAggrRWRtn (LOGICAL is_read) static
Definition at line 6098 of file semantio.c.
References BYTE_RW_IDX, is_read, LARGE_ARRAY_IDX, UnformattedRtns::read, RTE_no_rtn, unf_nm, and UnformattedRtns::write.
Referenced by semantio().
getArrayRWRtn()
static FtnRtlEnum getArrayRWRtn (LOGICAL is_read, FormatType fmtTyp, int dtype, LOGICAL needDescr) static
Definition at line 6185 of file semantio.c.
References array_unf_nm, BYTE_SWAPPED_IO, BYTE_SWAPPED_IO_IDX, FT_LIST_DIRECTED, FT_UNFORMATTED, is_read, LARGE_ARRAY, LARGE_ARRAY_IDX, UnformattedRtns::read, RTE_f90io_fmt_read64_aa, RTE_f90io_fmt_read_aa, RTE_f90io_fmt_write64_aa, RTE_f90io_fmt_write_aa, RTE_f90io_ldr64_aa, RTE_f90io_ldr_aa, RTE_f90io_ldw64_aa, RTE_f90io_ldw_aa, RTE_io_fmt_read, RTE_io_fmt_read64, RTE_io_fmt_write, RTE_io_fmt_write64, RTE_io_ldr, RTE_io_ldr64, RTE_io_ldw, RTE_io_ldw64, RTE_io_unf_read, RTE_io_unf_read64, RTE_io_unf_write, RTE_io_unf_write64, RTE_io_usw_read, RTE_io_usw_read64, RTE_io_usw_write, RTE_io_usw_write64, RTE_no_rtn, and UnformattedRtns::write.
Referenced by semantio().
getBasicScalarRWRtn()
static FtnRtlEnum getBasicScalarRWRtn (LOGICAL is_read, FormatType fmttyp) static
Definition at line 6074 of file semantio.c.
References BYTE_SWAPPED_IO_IDX, fmttyp, FT_LIST_DIRECTED, FT_UNFORMATTED, is_read, LARGE_ARRAY_IDX, UnformattedRtns::read, RTE_f90io_fmt_reada, RTE_f90io_fmt_writea, RTE_f90io_ldra, RTE_f90io_ldwa, RTE_no_rtn, unf_nm, and UnformattedRtns::write.
Referenced by semantio().
getWriteByDtypeRtn()
static FtnRtlEnum getWriteByDtypeRtn (int dtype, FormatType fmttyp) static
Definition at line 6119 of file semantio.c.
References DTY, fmttyp, FT_LIST_DIRECTED, RTE_f90io_sc_cd_fmt_write, RTE_f90io_sc_cd_ldw, RTE_f90io_sc_cf_fmt_write, RTE_f90io_sc_cf_ldw, RTE_f90io_sc_ch_fmt_write, RTE_f90io_sc_ch_ldw, RTE_f90io_sc_cq_fmt_write, RTE_f90io_sc_cq_ldw, RTE_f90io_sc_d_fmt_write, RTE_f90io_sc_d_ldw, RTE_f90io_sc_f_fmt_write, RTE_f90io_sc_f_ldw, RTE_f90io_sc_fmt_write, RTE_f90io_sc_i_fmt_write, RTE_f90io_sc_i_ldw, RTE_f90io_sc_l_fmt_write, RTE_f90io_sc_l_ldw, RTE_f90io_sc_ldw, RTE_f90io_sc_q_fmt_write, RTE_f90io_sc_q_ldw, RTE_no_rtn, and TY_CHAR.
Referenced by semantio().
iomsg_check()
static void iomsg_check (void) static
Definition at line 5761 of file semantio.c.
References add_io_arg(), add_stmt_after(), begin_io_call(), io_call, mk_iofunc(), PT_IOMSG, PTV, RTE_f90io_iomsga, sptr, STD_PREV, and void().
Referenced by semantio().
kwd_errchk()
static void kwd_errchk (int bt) static
Definition at line 4869 of file semantio.c.
References BT_INQUIRE, i, IOERR2, PT_END, PT_ERR, PT_MAXV, PTNAME, PTS, PTSTMT, and PTVARREF.
Referenced by semantio().
link_iollist()
static IOL * link_iollist (IOL * first, IOL * last) static
Definition at line 5186 of file semantio.c.
References end, find_end_iollist(), first, last, and NULL.
Referenced by add_iolptrs().
misc_io_checks()
static int misc_io_checks (const char * iostmt) static
Definition at line 5744 of file semantio.c.
References not_in_forall(), and void().
Referenced by semantio().
mk_hpfiofunc()
static int mk_hpfiofunc (FtnRtlEnum rtlRtn, int dtype, int intent) static
Definition at line 5119 of file semantio.c.
References intent, INTENTP, mkRteRtnNm(), sptr, and sym_mkfunc().
Referenced by semantio().
mk_iofunc()
static int mk_iofunc (FtnRtlEnum rtlRtn, int dtype, int intent) static
Definition at line 5102 of file semantio.c.
References intent, INTENTP, mkRteRtnNm(), sptr, and sym_mkfunc().
Referenced by call_dtsfmt(), fio_end_err(), gen_derived_io(), iomsg_check(), rw_array(), and semantio().
need_descriptor_ast()
static LOGICAL need_descriptor_ast (int refast) static
Definition at line 5136 of file semantio.c.
References NOSYM, ss, TRUE, and XBIT.
Referenced by semantio().
newunit_check()
static void newunit_check (void) static
Definition at line 5773 of file semantio.c.
References IOERR2, PT_FILE, PT_NEWUNIT, PT_STATUS, and PTV.
Referenced by semantio().
put_edit()
static void put_edit (int code) static
Definition at line 4739 of file semantio.c.
References edit_state, ERR170, FED_COLON, FED_D, FED_DOLLAR, FED_Dw_d, FED_E, FED_Ee, FED_END, FED_Ew_d, FED_F, FED_Fw_d, FED_G, FED_Gw_d, FED_I, FED_L, FED_LPAREN, FED_O, FED_P, FED_Q, FED_RPAREN, FED_SLASH, FED_Z, FLANG_FALLTHROUGH, flg, last_edit, PUT, and FLG::standard.
Referenced by semantio().
put_ffield()
static void put_ffield (SST * stk) static
Definition at line 4833 of file semantio.c.
References interr(), PUT, S_CONST, SST_CVALG, SST_IDG, and stk.
Referenced by semantio().
put_vlist()
static void put_vlist (SST * stk) static
Definition at line 4843 of file semantio.c.
References i, interr(), ITEM_END, xyyz::next, PUT, SST_BEGG, SST_CVALG, stk, xyyz::stkp, and xyyz::t.
Referenced by semantio().
replace_vector_subscript()
static int replace_vector_subscript (int ast, int indexast) static
Definition at line 5257 of file semantio.c.
References A_ARGCNTG, A_OPTYPEG, ADD_NUMDIM, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, ast, astb, DT_INT, DTY, FALSE, i, ASTB::i0, interr(), lb, mk_argt(), mk_binop(), mk_convert(), mk_func_node(), mk_member(), mk_paren(), mk_subscr(), mk_substr(), mk_unop(), nargs, nsubs, OP_ADD, replace_vector_subscript(), sptr, TRUE, and unmk_argt().
Referenced by add_iolptrs(), and replace_vector_subscript().
rw_array()
static void rw_array (int refast, int stride, int eldtype, FtnRtlEnum rtlRtn) static
Definition at line 5150 of file semantio.c.
References add_io_arg(), begin_io_call(), DT_INT, dtype_to_arg(), INTENT_IN, is_read, mk_cval(), mk_iofunc(), size_of_ast(), stride, and void().
Referenced by semantio().
semantio()
void semantio (int rednum, SST * top)
Semantic analysis of IO statements.
Parameters
rednum reduction number
top top of stack after reduction
Definition at line 473 of file semantio.c.
References FLG::accmp, AD_ASSUMSZ, AD_DPTR, AD_NUMELM, AD_PTR, add_arg(), add_astli(), add_cgoto(), add_io_arg(), add_stmt(), add_stmt_after(), ASD_NDIM, ASD_SUBS, assert, xyyz::ast, ast, ast_ioret(), astb, ASTLI_HEAD, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, begin_call(), begin_io_call(), bitv, BITV_ADVANCE, BITV_END, BITV_EOR, BITV_ERR, BITV_IOMSG, BITV_IOSTAT, BITV_SIZE, ASTB::bnd, BT_ACCEPT, BT_BKSPACE, BT_CLOSE, BT_DECODE, BT_ENCODE, BT_ENDFILE, BT_FLUSH, BT_INQUIRE, BT_OPEN, BT_PRINT, BT_READ, BT_REWIND, BT_WAIT, BT_WRITE, BYTE_SWAPPED_IO, BYTE_SWAPPED_IO_IDX, call_dtsfmt(), check_member(), chk_expr(), chk_fmtid(), chk_iospec(), chk_scalartyp(), chk_unitid(), chk_var(), CNULL, copy_back_to_replic_sect(), copy_replic_sect_to_tmp(), count, DOINFO::count, SCN::currlab, DBGBIT, DDTG, SEM::defined_io_seen, DI_DO, DI_DOCONCURRENT, DI_IN_NEST, dim, DINIT_END, DINIT_FMT, DINIT_LOC, dinit_put(), DINIT_STR, do_begin(), do_end(), DOCHK, SEM::doif_depth, iol::doinfo, DT_INT, DT_IO_FREAD, DT_IO_FWRITE, DT_IO_UREAD, DT_IO_UWRITE, DT_ISBASIC, DT_ISINT, DT_LOG, DT_PTR, SEM::dtemps, DTY, DTYG, ASTB::dtype, dtype_has_defined_io(), dtype_to_arg(), edit_state, iol::element, UnformattedRtns::end, end_io_call(), ERR170, ERR_Severe, ERR_Warning, error(), external_io, FALSE, fasize, FED_A, FED_Aw, FED_BN, FED_Bw_m, FED_BZ, FED_COLON, FED_D, FED_DC, FED_DOLLAR, FED_DP, FED_DT, FED_Dw_d, FED_E, FED_Ee, FED_END, FED_ENw_d, FED_ESw_d, FED_Ew_d, FED_F, FED_Fw_d, FED_G, FED_G0, FED_G0_d, FED_Gw_d, FED_I, FED_Iw_m, FED_KANJI_STRING, FED_L, FED_LPAREN, FED_Lw, FED_N, FED_Nw, FED_O, FED_Ow_m, FED_P, FED_Q, FED_RC, FED_RD, FED_RN, FED_RP, FED_RPAREN, FED_RU, FED_RZ, FED_S, FED_SLASH, FED_SP, FED_SS, FED_STR, FED_T, FED_TL, FED_TR, FED_X, FED_Z, FED_Zw_m, filename_type, fix_iostat(), flg, fmt_init, fmt_inite, fmt_is_var, fmt_length, fmttyp, FT_CHARACTER, FT_ENCODED, FT_FMTSTR, FT_LIST_DIRECTED, FT_NML, FT_UNFORMATTED, functype, gbl, gen_derived_io(), gen_dtio_args(), gen_dtsfmt_args(), gen_lastval(), gen_spec_item_tmp(), get_defined_io_call(), get_derived_iolptrs(), get_doinfo(), get_fmt_array(), get_nml_array(), get_temp(), getAggrRWRtn(), getArrayRWRtn(), getBasicScalarRWRtn(), getcctmp_sc(), getitem(), getprint(), getstring(), getWriteByDtypeRtn(), i, ASTB::i0, ASTB::i1, iol::id, IE_DOBEGIN, IE_DOEND, IE_EXPR, IE_OPTDO, DOINFO::index_var, index_var, init(), init_derived_w_acl(), DOINFO::init_expr, INTENT_IN, intern, intern_array, intern_tmp, interr(), io_call, io_sc, SEM::io_stmt, IOERR, IOERR2, iolist, iomsg_check(), is_dovar_sptr(), is_iso_cptr(), is_read, is_varref(), ITEM_END, itemp, ASTB::k1, kwd_errchk(), iol::l_std, LARGE_ARRAY_IDX, last_edit, lastrpt, lb, len, LHS, DOINFO::limit_expr, list, malloc(), misc_io_checks(), mk_assn_stmt(), mk_binop(), mk_cnst(), mk_convert(), mk_cval(), mk_fake_iostat(), mk_func_node(), mk_hpfiofunc(), mk_id(), mk_iofunc(), mk_isz_cval(), mk_stmt(), mk_subscr(), mk_substr(), mk_triple(), mk_unop(), mkarg(), mkexpr(), mkRteRtnNm(), n, STB::n_base, ndim, need_descriptor_ast(), NEED_DOIF, newunit_check(), next, xyyz::next, iol::next, nml_group, NML_NEXT, NML_SPTR, no_data_components(), no_rw, nondevice_io, noparens, NULL, OP_ADD, OP_DIV, OP_LOC, OP_MUL, OP_SUB, OP_VAL, open03, print_star, PT_ACCESS, PT_ACTION, PT_ADVANCE, PT_ASYNCHRONOUS, PT_BLANK, PT_CHECK, PT_CONVERT, PT_DECIMAL, PT_DELIM, PT_DIRECT, PT_DISPOSE, PT_ENCODING, PT_END, PT_EOR, PT_ERR, PT_EXIST, PT_FILE, PT_FMT, PT_FORM, PT_FORMATTED, PT_ID, PT_IOLENGTH, PT_IOMSG, PT_IOSTAT, PT_LAST_INQUIRE_VAL, PT_LAST_INQUIRE_VALf95, PT_MAXV, PT_NAME, PT_NAMED, PT_NEWUNIT, PT_NEXTREC, PT_NML, PT_NUMBER, PT_OPENED, PT_PAD, PT_PENDING, PT_POS, PT_POSITION, PT_READ, PT_READWRITE, PT_REC, PT_RECL, PT_ROUND, PT_SEQUENTIAL, PT_SET, PT_SHARED, PT_SIGN, PT_SIZE, PT_STATUS, PT_STREAM, PT_TMPUSED, PT_UNFORMATTED, PT_UNIT, PT_VARREF, PT_WRITE, PTARG, PTNAME, ASTB::ptr0, ASTB::ptr0c, PTS, PTV, PTVARREF, PUT, put_edit(), put_ffield(), put_vlist(), refsym(), rescan, resolve_defined_io(), RHS, RTE_f90io_aux_init, RTE_f90io_backspace, RTE_f90io_begin, RTE_f90io_closea, RTE_f90io_dts_stat, RTE_f90io_encode_fmta, RTE_f90io_encode_fmtv, RTE_f90io_endfile, RTE_f90io_flush, RTE_f90io_fmtr_end, RTE_f90io_fmtr_init03a, RTE_f90io_fmtw_end, RTE_f90io_fmtw_init03a, RTE_f90io_get_newunit, RTE_f90io_inquire03_2a, RTE_f90io_inquire2003a, RTE_f90io_ldr_end, RTE_f90io_ldr_init, RTE_f90io_ldr_init03a, RTE_f90io_ldr_intern_inita, RTE_f90io_ldr_intern_inite, RTE_f90io_ldw_end, RTE_f90io_ldw_init, RTE_f90io_ldw_init03a, RTE_f90io_ldw_intern_inita, RTE_f90io_ldw_intern_inite, RTE_f90io_nmlr, RTE_f90io_nmlr_end, RTE_f90io_nmlr_init, RTE_f90io_nmlr_init03a, RTE_f90io_nmlr_intern_inita, RTE_f90io_nmlw, RTE_f90io_nmlw_end, RTE_f90io_nmlw_init, RTE_f90io_nmlw_init03a, RTE_f90io_nmlw_intern_inita, RTE_f90io_open03a, RTE_f90io_open2003a, RTE_f90io_open_asynca, RTE_f90io_open_cvta, RTE_f90io_open_sharea, RTE_f90io_print_init, RTE_f90io_rewind, RTE_f90io_src_info03a, RTE_f90io_swbackspace, RTE_f90io_unf_asynca, RTE_f90io_wait, RTE_lena, RTE_loc, RTE_nlena, rw03, rw_array(), s, S_ACONST, S_CONST, S_DERIVED, S_EXPR, S_IDENT, S_LVALUE, S_SCONST, scn, sem, sem_set_storage_class(), sem_tempify(), set_assn(), set_io_sc(), SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, size_of(), size_of_ast(), FLG::smp, sptr, ss, SST_ACLG, SST_ALIASP, SST_ASTG, SST_ASTP, SST_BEGG, SST_BEGP, SST_CVALG, SST_CVALP, SST_CVLENG, SST_CVLENP, SST_DTYPEG, SST_DTYPEP, SST_ENDG, SST_ENDP, SST_IDG, SST_IDP, SST_LENG, SST_LENP, SST_LSYMG, SST_OPTYPEG, SST_RNG1G, SST_RNG1P, SST_RNG2G, SST_RNG2P, SST_SHAPEG, SST_SHAPEP, SST_SYMG, SST_SYMP, SST_UNITG, SST_UNITP, st, FLG::standard, start_astli(), stb, std, STD_LABEL, STD_LINENO, STD_NEXT, STD_PREV, DOINFO::step_expr, xyyz::stkp, SCN::stmtyp, str, string_expr_length(), string_length(), strlen(), sym_get_scalar(), sym_is_refd(), sym_mkfunc(), sym_mkfunc_nodesc(), sym_of_ast(), SYMNAME, t, xyyz::t, TRUE, TY_CHAR, TY_INT8, TY_NCHAR, ty_to_lib, ub, unf_nm, UNIT_CHECK, unit_star, void(), and XBIT.
set_io_sc()
static int set_io_sc (void) static
Definition at line 4229 of file semantio.c.
References io_sc, sem, and SEM::task.
Referenced by semantio().
Variable Documentation
array_unf_nm
UnformattedRtns array_unf_nm[][3]
Initial value:
= {
    {
        {RTE_f90io_unf_init, RTE_f90io_unf_read_aa, RTE_f90io_unf_write_aa,
         RTE_f90io_unf_end},
        {RTE_f90io_usw_init, RTE_f90io_usw_read_aa, RTE_f90io_usw_write_aa,
         RTE_f90io_usw_end},
        {RTE_f90io_unf_init, RTE_f90io_byte_reada, RTE_f90io_byte_writea,
         RTE_f90io_unf_end},
    },
    {
        {RTE_f90io_unf_init, RTE_f90io_unf_read64_aa, RTE_f90io_unf_write64_aa,
         RTE_f90io_unf_end},
        {RTE_f90io_usw_init, RTE_f90io_usw_read64_aa, RTE_f90io_usw_write64_aa,
         RTE_f90io_usw_end},
        {RTE_f90io_unf_init, RTE_f90io_byte_read64a, RTE_f90io_byte_write64a,
         RTE_f90io_unf_end},
    }}
Definition at line 370 of file semantio.c.
Referenced by getArrayRWRtn().
ast
int ast
Definition at line 37 of file semantio.c.
Referenced by add_cgoto(), add_iolptrs(), ast_ioret(), end_or_err(), fio_end_err(), gen_lastval(), get_defined_io_call(), replace_vector_subscript(), and semantio().
ast_type
int ast_type
Definition at line 38 of file semantio.c.
Referenced by begin_io_call(), and gen_dtio_args().
bitv
INT bitv static
Definition at line 314 of file semantio.c.
Referenced by __f90io_unf_init(), __f90io_usw_init(), __fort_status_init(), __fortio_errinit(), __fortio_errinit03(), __fortio_stat_init(), __INT_T(), _f90io_backspace(), _f90io_close(), _f90io_endfile(), _f90io_ldr_init(), _f90io_ldr_intern_init(), _f90io_ldw_init(), _f90io_ldw_intern_init(), _f90io_nmlr_init(), _f90io_nmlr_intern_init(), _f90io_nmlw_init(), _f90io_nmlw_intern_init(), _f90io_rewind(), chk_iospec(), ENTCRF90IO(), ENTF90IO(), f90_open(), fr_init(), fr_intern_init(), fw_init(), fw_intern_init(), inquire(), and semantio().
edit_state
int edit_state static
Definition at line 302 of file semantio.c.
Referenced by put_edit(), and semantio().
external_io
LOGICAL external_io static
Definition at line 286 of file semantio.c.
Referenced by semantio().
fasize
int fasize static
Definition at line 294 of file semantio.c.
Referenced by _put(), and semantio().
filename_type
int filename_type = 0 static
Definition at line 309 of file semantio.c.
Referenced by semantio().
struct { ... } fmt_init[]
Initial value:
= {{
                    {RTE_f90io_fmtr_init2003a, RTE_f90io_fmtr_initv2003a},
                    {RTE_f90io_fmtw_inita, RTE_f90io_fmtw_initva},
                },
                {
                    {RTE_f90io_fmtr_intern_inita, RTE_f90io_fmtr_intern_initva},
                    {RTE_f90io_fmtw_intern_inita, RTE_f90io_fmtw_intern_initva},
                }}
Referenced by semantio().
struct { ... } fmt_inite
Initial value:
= {
    {RTE_f90io_fmtr_intern_inite, RTE_f90io_fmtr_intern_initev},
    {RTE_f90io_fmtw_intern_inite, RTE_f90io_fmtw_intern_initev},
}
Referenced by semantio().
fmt_is_var
int fmt_is_var static
Definition at line 293 of file semantio.c.
Referenced by chk_fmtid(), and semantio().
fmt_length
int fmt_length static
Definition at line 306 of file semantio.c.
Referenced by chk_fmtid(), and semantio().
fmttyp
FormatType fmttyp static
Definition at line 281 of file semantio.c.
Referenced by chk_fmtid(), gen_dtio_args(), getBasicScalarRWRtn(), getWriteByDtypeRtn(), and semantio().
functype
int functype[2][FT_LAST] static
Initial value:
= {
    {DT_IO_FWRITE, DT_IO_UWRITE, DT_IO_FWRITE, DT_IO_FWRITE, DT_IO_FWRITE,
     DT_IO_FWRITE, DT_IO_FWRITE},
    {DT_IO_FREAD, DT_IO_UREAD, DT_IO_FREAD, DT_IO_FREAD, DT_IO_FREAD,
     DT_IO_FREAD, DT_IO_FREAD}}
Definition at line 152 of file semantio.c.
Referenced by semantio().
intern
LOGICAL intern static
Definition at line 285 of file semantio.c.
Referenced by chk_iospec(), chk_unitid(), gen_dtio_args(), and semantio().
intern_array
int intern_array static
Definition at line 283 of file semantio.c.
Referenced by semantio().
intern_tmp
int intern_tmp static
Definition at line 284 of file semantio.c.
Referenced by semantio().
struct { ... } io_call
Referenced by add_cgoto(), begin_io_call(), end_io_call(), iomsg_check(), and semantio().
io_sc
int io_sc static
Definition at line 420 of file semantio.c.
Referenced by ast_ioret(), chk_var(), gen_dtio_args(), gen_dtsfmt_args(), gen_spec_item_tmp(), semantio(), and set_io_sc().
iolist
int iolist static
Definition at line 310 of file semantio.c.
Referenced by semantio().
is_read
LOGICAL is_read static
Definition at line 289 of file semantio.c.
Referenced by call_dtsfmt(), chk_fmtid(), chk_unitid(), getAggrRWRtn(), getArrayRWRtn(), getBasicScalarRWRtn(), rw_array(), and semantio().
last_edit
int last_edit static
Definition at line 305 of file semantio.c.
Referenced by put_edit(), and semantio().
lastrpt
int lastrpt static
Definition at line 299 of file semantio.c.
Referenced by semantio().
nml_group
int nml_group static
Definition at line 282 of file semantio.c.
Referenced by semantio().
no_rw
LOGICAL no_rw static
Definition at line 290 of file semantio.c.
Referenced by chk_unitid(), and semantio().
nondevice_io
LOGICAL nondevice_io static
Definition at line 287 of file semantio.c.
Referenced by semantio().
noparens
LOGICAL noparens static
Definition at line 311 of file semantio.c.
Referenced by semantio().
open03
LOGICAL open03 static
Definition at line 312 of file semantio.c.
Referenced by semantio().
print_star
LOGICAL print_star static
Definition at line 291 of file semantio.c.
Referenced by chk_fmtid(), and semantio().
pt
struct pt_tag pt[PT_MAXV + 1] static
Referenced by findloop(), make_address(), and maybe_fixup_x86_abi_return().
read
FtnRtlEnum read[2]
Definition at line 397 of file semantio.c.
Referenced by __f90io_unf_init(), __f90io_usw_init(), __fort_par_read(), __INT_T(), __unf_init(), ENTCRF90IO(), ENTF90IO(), and gen_derived_io().
rescan
int rescan static
Definition at line 296 of file semantio.c.
Referenced by semantio().
rw03
LOGICAL rw03 static
Definition at line 313 of file semantio.c.
Referenced by semantio().
std
int std
Definition at line 39 of file semantio.c.
Referenced by copy_back_to_replic_sect(), copy_replic_sect_to_tmp(), end_or_err(), and semantio().
unf_nm
UnformattedRtns unf_nm[][3]
Initial value:
= {{
                                   {RTE_f90io_unf_init, RTE_f90io_unf_reada,
                                    RTE_f90io_unf_writea, RTE_f90io_unf_end},
                                   {RTE_f90io_usw_init, RTE_f90io_usw_reada,
                                    RTE_f90io_usw_writea, RTE_f90io_usw_end},
                                   {RTE_f90io_unf_init, RTE_f90io_byte_reada,
                                    RTE_f90io_byte_writea, RTE_f90io_unf_end},
                               },
{
                                   {RTE_f90io_unf_init, RTE_f90io_unf_reada,
                                    RTE_f90io_unf_writea, RTE_f90io_unf_end},
                                   {RTE_f90io_usw_init, RTE_f90io_usw_reada,
                                    RTE_f90io_usw_writea, RTE_f90io_usw_end},
                                   {RTE_f90io_unf_init, RTE_f90io_byte_read64a,
                                    RTE_f90io_byte_write64a, RTE_f90io_unf_end},
                               }}
Definition at line 353 of file semantio.c.
Referenced by getAggrRWRtn(), getBasicScalarRWRtn(), and semantio().
unit_star
LOGICAL unit_star static
Definition at line 292 of file semantio.c.
Referenced by chk_fmtid(), and semantio().
write
FtnRtlEnum write[2]
Definition at line 398 of file semantio.c.
Referenced by __fort_abort(), __fort_par_write(), __fort_psignal(), __fort_traceback(), __fort_tracecall(), __fort_zclose(), __fort_zopen(), __fort_zwrite(), cpu(), mem(), msg(), and pg_makenewfile().