flang: semant.c File Reference
semant.c File Reference
This file contains part 1 of the compiler's semantic actions (also known as the semant1 phase).
#include "gbldefs.h"
#include "gramsm.h"
#include "gramtk.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "semant.h"
#include "scan.h"
#include "dinit.h"
#include "semstk.h"
#include "ast.h"
#include "pragma.h"
#include "rte.h"
#include "pd.h"
#include "interf.h"
#include "fdirect.h"
#include "fih.h"
#include "ccffinfo.h"
#include "atomic_common.h"
Classes
struct subp_prefix_t
Subprogram prefix struct defintions for RECURESIVE, PURE, IMPURE, ELEMENTAL, and MODULE.
struct dec_attr_t
Macros
#define _LEN_CONST 1
#define _LEN_ASSUM 2
#define _LEN_ZERO 3
#define _LEN_ADJ 4
#define _LEN_DEFER 5
#define BYVALDEFAULT(ffunc)
#define ERR310(s1, s2) error(310, 3, gbl.lineno, s1, s2)
#define ET_ACCESS 0
#define ET_ALLOCATABLE 1
#define ET_DIMENSION 2
#define ET_EXTERNAL 3
#define ET_INTENT 4
#define ET_INTRINSIC 5
#define ET_OPTIONAL 6
#define ET_PARAMETER 7
#define ET_POINTER 8
#define ET_SAVE 9
#define ET_TARGET 10
#define ET_AUTOMATIC 11
#define ET_STATIC 12
#define ET_BIND 13
#define ET_VALUE 14
#define ET_VOLATILE 15
#define ET_PASS 16
#define ET_NOPASS 17
#define ET_DEVICE 18
#define ET_PINNED 19
#define ET_SHARED 20
#define ET_CONSTANT 21
#define ET_PROTECTED 22
#define ET_ASYNCHRONOUS 23
#define ET_TEXTURE 24
#define ET_KIND 25
#define ET_LEN 26
#define ET_CONTIGUOUS 27
#define ET_MANAGED 28
#define ET_IMPL_MANAGED 29
#define ET_MAX 30
#define ET_B(e) (1 << e)
#define SYMI_SPTR(i) aux.symi_base[i].sptr
#define SYMI_NEXT(i) aux.symi_base[i].next
#define DA_ALIAS 0
#define DA_C 1
#define DA_STDCALL 2
#define DA_DLLEXPORT 3
#define DA_DLLIMPORT 4
#define DA_VALUE 5
#define DA_REFERENCE 6
#define DA_DECORATE 7
#define DA_NOMIXEDSLA 8
#define DA_MAX 9
#define DA_B(e) (1 << e)
Functions
static void gen_dinit (int, SST *)
static void pop_subprogram (void)
static void fix_proc_ptr_dummy_args ()
static void set_len_attributes (SST *, int)
static void set_char_attributes (int, int *)
static void set_aclen (SST *, int, int)
static void copy_type_to_entry (int)
static void save_host (INTERF *)
static void restore_host (INTERF *, LOGICAL)
static void do_end_subprogram (SST *, RU_TYPE)
static void check_end_subprogram (RU_TYPE, int)
static const char * name_of_rutype (RU_TYPE)
static void convert_intrinsics_to_idents (void)
static int chk_intrinsic (int, LOGICAL, LOGICAL)
static int create_func_entry (int)
static int create_func_entry_result (int)
static int create_var (int)
static int chk_func_entry_result (int)
static void get_param_alias_const (SST *, int, int)
static void set_string_type_from_init (int, ACL *)
static void fixup_param_vars (SST *, SST *)
static void save_typedef_init (int, int)
static void symatterr (int, int, const char *)
static void fixup_function_return_type (int, int)
static void get_retval_KIND_value ()
static void get_retval_LEN_value ()
static void get_retval_derived_type ()
static void init_allocatable_typedef_components (int)
static int chk_kind_parm (SST *)
static int get_kind_parm (int, int)
static int get_kind_parm_strict (int, int)
static int get_len_parm (int, int)
static int has_kind_parm_expr (int, int, int)
static void chk_initialization_with_kind_parm (int)
static void check_kind_type_param (int dtype)
static void defer_put_kind_type_param (int, int, char *, int, int, int)
static void replace_sdsc_in_bounds (int sdsc, ADSC *ad, int i)
static int replace_sdsc_in_ast (int sdsc, int ast)
static void chk_new_param_dt (int, int)
static int get_vtoff (int, DTYPE)
static int get_highest_param_offset (int)
static ACL * dup_acl (ACL *src, int sptr)
static int match_memname (int sptr, int list)
static LOGICAL is_pdt_dtype (DTYPE dtype)
static int chk_asz_deferlen (int, int)
static void defer_ident_list (int ident, int proc)
static void clear_ident_list ()
static void decr_ident_use (int ident, int proc)
static void check_duplicate (bool checker, const char *op)
Emit a warning if a duplicate subproblem prefix is used.
static int decl_procedure_sym (int sptr, int proc_interf_sptr, int attr)
Declare a procedure symbol.
static int setup_procedure_sym (int sptr, int proc_interf_sptr, int attr, char access)
Process procedure declaration.
static LOGICAL ignore_common_decl (void)
static void record_func_result (int func_sptr, int func_result_sptr, LOGICAL in_ENTRY)
static bool bindingNameRequiresOverloading (SPTR sptr)
Determine if a type bound procedure (tbp) binding name requires overloading.
static void clear_iface (int i, SPTR iface)
static bool do_fixup_param_vars_for_derived_arrays (bool inited, SPTR sptr, int sst_idg)
To re-initialize an array of derived types when found the following conditions are satisfied:
static void gen_unique_func_ast (int ast, SPTR sptr, SST *stkptr)
static void clear_subp_prefix_settings (struct subp_prefix_t *subp)
Reset subprogram prefixes to zeroes.
static void check_module_prefix ()
MODULE prefix checking for subprograms C1547: cannot be inside a an abstract interface.
static void process_bind (int)
static void defer_iface (int, int, int, int)
static void do_iface (int)
static void do_iface_module (void)
static void _do_iface (int, int)
static void fix_iface (int)
static void fix_iface0 ()
This routine sets the PASS field in a procedure pointer for semantic pass 0 prior to call to end_module().
void semant_init (int noparse)
Initialize semantic analyzer for new user subprogram unit.
static void reloc_byvalue_parameters ()
static void end_subprogram_checks ()
void semant1 (int rednum, SST *top)
Semantic actions - part 1.
static void ctte (int entry, int sptr)
static LOGICAL wrong_name (SPTR endname)
void build_typedef_init_tree (int sptr, int dtype)
static void init_allocatable_typedef_components (SPTR td_sptr)
static int fixup_KIND_expr (int ast)
static int eval_KIND_expr (int ast, int *val, int *dtyp)
int internal_proc_has_ident (int ident, int proc)
int queue_type_param (int sptr, int dtype, int offset, int flag)
Sets up type parameters used in parameterized derived types (PDTs)
static void search_kind (int ast, int *offset)
int get_kind_parm_by_name (char *np, int dtype)
search a derived type for a kind type parameter with a specified name.
int get_parm_by_number (int offset, int dtype)
search derived type for a type parameter in the same position as specified by offset.
int get_parm_by_name (char *np, int dtype)
search a derived type for a kind or length type parameter with a specified name.
int chk_kind_parm_expr (int ast, int dtype, int flag, int strict_flag)
int chk_len_parm_expr (int ast, int dtype, int flag)
int get_len_set_parm_by_name (char *np, int dtype, int *val)
int cmp_len_parms (int ast1, int ast2)
int defer_pt_decl (int dtype, int flag)
Store dtypes of parameterized derived types in which a parameter was explicitly declared (as opposed to using just the default values).
void put_default_kind_type_param (int dtype, int flag, int flag2)
void put_length_type_param (DTYPE dtype, int flag)
int get_len_parm_by_number (int num, int dtype, int flag)
int all_len_parms_assumed (int dtype)
Return 0 if there's at least one length type parameter that is not assumed. Otherwise return 1.
LOGICAL put_kind_type_param (DTYPE dtype, int offset, int value, int expr, int flag)
int get_unl_poly_sym (int mem_dtype)
static int has_type_parameter2 (int dtype, int visit_flag)
Returns true if dtype is a derived type that has a type parameter or if it has a component that has a type parameter.
int has_type_parameter (int dtype)
checks to see if derived type record, dtype, has any type parameters (kind or length type parameters).
int has_length_type_parameter_use (int dtype)
DTYPE create_parameterized_dt (DTYPE dtype, LOGICAL force)
Create a parameterized derived type based on dtype. If force is not set and dtype is already a PDT, return DT_NONE.
DTYPE get_parameterized_dt (DTYPE dtype)
Duplicate dtype by creating a new derived type with a $pt suffix. For use with processing parameterized derived type.
int is_parameter_context ()
allow other source files to check whether we're processing a parameter construct.
bool in_intrinsic_decl (void)
Return the predicate: current entity has the INTRINSIC attribute.
int get_entity_access ()
provide the current entity's access to other source files.
int getMscall ()
provide mscall variable state to other source files.
int getCref ()
provide cref variable state to other source files.
static int get_procedure_stype (int attr)
Determine procedure symbol type for a set of attributes.
const char * sem_pgphase_name ()
Variables
static int ident_host_sub = 0
static IFACE * iface_base
static int iface_avail
static int iface_size
static IDENT_LIST * ident_base [HASHSIZE]
static LOGICAL dirty_ident_base = FALSE
static STSK * stsk
static LOGICAL seen_implicit
static LOGICAL seen_parameter
static LOGICAL craft_intrinsics
static LOGICAL is_entry
static LOGICAL is_exe_stmt
static LOGICAL entry_seen
static LOGICAL seen_options
struct {
int kind
INT len
int propagated
} lenspec [2]
static struct subp_prefix_t subp_prefix
static int mscall
static int cref
static int nomixedstrlen
static int next_enum
static int host_present
static INTERF host_state
static int end_of_host
static LOGICAL in_entity_typdcl
struct {
int exist
int dimension
char access
char intent
char bounds [sizeof(sem.bounds)]
char arrdim [sizeof(sem.arrdim)]
int pass_arg
} entity_attr
struct {
const char * name
int no
} et [ET_MAX]
static struct dec_attr_t dec_attr
static struct dec_attr_t bind_attr
struct {
const char * name
int no
} da [DA_MAX]
static int restored = 0
Detailed Description
This file contains part 1 of the compiler's semantic actions (also known as the semant1 phase).
Definition in file semant.c.
Macro Definition Documentation
_LEN_ADJ
#define _LEN_ADJ 4
Definition at line 133 of file semant.c.
_LEN_ASSUM
#define _LEN_ASSUM 2
Definition at line 131 of file semant.c.
_LEN_CONST
#define _LEN_CONST 1
Definition at line 130 of file semant.c.
_LEN_DEFER
#define _LEN_DEFER 5
Definition at line 134 of file semant.c.
_LEN_ZERO
#define _LEN_ZERO 3
Definition at line 132 of file semant.c.
BYVALDEFAULT
#define BYVALDEFAULT (ffunc)
Value:
  (!(PASSBYREFG(ffunc)) &&  \
   (PASSBYVALG(ffunc) | STDCALLG(ffunc) | CFUNCG(ffunc)))
Definition at line 157 of file semant.c.
DA_ALIAS
#define DA_ALIAS 0
Definition at line 369 of file semant.c.
DA_B
#define DA_B (e) (1 << e)
Definition at line 382 of file semant.c.
DA_C
#define DA_C 1
Definition at line 370 of file semant.c.
DA_DECORATE
#define DA_DECORATE 7
Definition at line 376 of file semant.c.
DA_DLLEXPORT
#define DA_DLLEXPORT 3
Definition at line 372 of file semant.c.
DA_DLLIMPORT
#define DA_DLLIMPORT 4
Definition at line 373 of file semant.c.
DA_MAX
#define DA_MAX 9
Definition at line 378 of file semant.c.
DA_NOMIXEDSLA
#define DA_NOMIXEDSLA 8
Definition at line 377 of file semant.c.
DA_REFERENCE
#define DA_REFERENCE 6
Definition at line 375 of file semant.c.
DA_STDCALL
#define DA_STDCALL 2
Definition at line 371 of file semant.c.
DA_VALUE
#define DA_VALUE 5
Definition at line 374 of file semant.c.
ERR310
#define ERR310 (s1, s2) error(310, 3, gbl.lineno, s1, s2)
Definition at line 173 of file semant.c.
ET_ACCESS
#define ET_ACCESS 0
Definition at line 181 of file semant.c.
ET_ALLOCATABLE
#define ET_ALLOCATABLE 1
Definition at line 182 of file semant.c.
ET_ASYNCHRONOUS
#define ET_ASYNCHRONOUS 23
Definition at line 204 of file semant.c.
ET_AUTOMATIC
#define ET_AUTOMATIC 11
Definition at line 192 of file semant.c.
ET_B
#define ET_B (e) (1 << e)
Definition at line 215 of file semant.c.
ET_BIND
#define ET_BIND 13
Definition at line 194 of file semant.c.
ET_CONSTANT
#define ET_CONSTANT 21
Definition at line 202 of file semant.c.
ET_CONTIGUOUS
#define ET_CONTIGUOUS 27
Definition at line 208 of file semant.c.
ET_DEVICE
#define ET_DEVICE 18
Definition at line 199 of file semant.c.
ET_DIMENSION
#define ET_DIMENSION 2
Definition at line 183 of file semant.c.
ET_EXTERNAL
#define ET_EXTERNAL 3
Definition at line 184 of file semant.c.
ET_IMPL_MANAGED
#define ET_IMPL_MANAGED 29
Definition at line 210 of file semant.c.
ET_INTENT
#define ET_INTENT 4
Definition at line 185 of file semant.c.
ET_INTRINSIC
#define ET_INTRINSIC 5
Definition at line 186 of file semant.c.
ET_KIND
#define ET_KIND 25
Definition at line 206 of file semant.c.
ET_LEN
#define ET_LEN 26
Definition at line 207 of file semant.c.
ET_MANAGED
#define ET_MANAGED 28
Definition at line 209 of file semant.c.
ET_MAX
#define ET_MAX 30
Definition at line 211 of file semant.c.
ET_NOPASS
#define ET_NOPASS 17
Definition at line 198 of file semant.c.
ET_OPTIONAL
#define ET_OPTIONAL 6
Definition at line 187 of file semant.c.
ET_PARAMETER
#define ET_PARAMETER 7
Definition at line 188 of file semant.c.
ET_PASS
#define ET_PASS 16
Definition at line 197 of file semant.c.
ET_PINNED
#define ET_PINNED 19
Definition at line 200 of file semant.c.
ET_POINTER
#define ET_POINTER 8
Definition at line 189 of file semant.c.
ET_PROTECTED
#define ET_PROTECTED 22
Definition at line 203 of file semant.c.
ET_SAVE
#define ET_SAVE 9
Definition at line 190 of file semant.c.
ET_SHARED
#define ET_SHARED 20
Definition at line 201 of file semant.c.
ET_STATIC
#define ET_STATIC 12
Definition at line 193 of file semant.c.
ET_TARGET
#define ET_TARGET 10
Definition at line 191 of file semant.c.
ET_TEXTURE
#define ET_TEXTURE 24
Definition at line 205 of file semant.c.
ET_VALUE
#define ET_VALUE 14
Definition at line 195 of file semant.c.
ET_VOLATILE
#define ET_VOLATILE 15
Definition at line 196 of file semant.c.
SYMI_NEXT
#define SYMI_NEXT (i) aux.symi_base[i].next
Definition at line 218 of file semant.c.
SYMI_SPTR
#define SYMI_SPTR (i) aux.symi_base[i].sptr
Definition at line 217 of file semant.c.
Function Documentation
_do_iface()
static void _do_iface (int iface_state, int i) static
Definition at line 14405 of file semant.c.
References arg, aux, clear_iface(), CNULL, STB::curr_scope, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, dt, DTY, IFACE::dtype, ERR_Severe, error(), FALSE, FLANG_FALLTHROUGH, gbl, getsymbol(), GSAMEG, HASH_ID, STB::hashtb, i, IFACE::iface, iface_avail, iface_base, iface_intrinsic(), IFACE::iface_name, IN_MODULE, SEM::interface, IFACE::internal, IS_INTRINSIC, j, len, lineno, IFACE::lineno, IFACE::mem, mem(), name, NEED, NOSYM, IFACE::proc, IFACE::proc_var, refsym(), refsym_inscope(), scope, IFACE::scope, SEM::seen_end_module, sem, sem_strcmp(), sptr, stb, strlen(), SYMNAME, IFACE::tag_name, test_scope(), TRUE, and SEM::which_pass.
Referenced by do_iface(), and do_iface_module().
all_len_parms_assumed()
int all_len_parms_assumed (int dtype)
Return 0 if there's at least one length type parameter that is not assumed. Otherwise return 1.
Definition at line 15883 of file semant.c.
References all_len_parms_assumed(), DTY, i, mem(), and NOSYM.
Referenced by all_len_parms_assumed(), and check_defined_io2().
bindingNameRequiresOverloading()
static bool bindingNameRequiresOverloading (SPTR sptr) static
Determine if a type bound procedure (tbp) binding name requires overloading.
This is called by the <binding name> ::= <id> '=>' <id> production above. After the tbp is set up, we perform additional overloading checks in resolveBind() of semtbp.c.
\pararm sptr is the binding name that we are checking.
Returns
true if it is an overloaded binding name, else false.
Definition at line 16764 of file semant.c.
References STB::curr_scope, IN_MODULE_SPEC, sptr, and stb.
Referenced by semant1().
build_typedef_init_tree()
void build_typedef_init_tree (int sptr, int dtype)
Definition at line 13468 of file semant.c.
References AD_NUMELM, AD_PTR, astb, DDTG, dinit_no_dinitp(), DTY, GET_ACL, get_getitem_p(), ASTB::i1, STSK::ict_beg, STSK::ict_end, INSIDE_STRUCT, _acl::next, NULL, _acl::repeatc, save_struct_init(), sptr, _acl::sptr, and stsk.
Referenced by misc_checks(), and semant1().
check_duplicate()
static void check_duplicate (bool checker, const char * op) static
Emit a warning if a duplicate subproblem prefix is used.
Definition at line 13946 of file semant.c.
References ERR_Warning, error(), gbl, and NULL.
Referenced by semant1().
check_end_subprogram()
static void check_end_subprogram (RU_TYPE rutype, int sym) static
Definition at line 12929 of file semant.c.
References check_end_subprogram(), CNULL, SCN::currlab, end_contained(), SEM::end_host_labno, end_of_host, enforce_denorm(), error(), gbl, host_state, SCN::labno, name_of_rutype(), SEM::pgphase, PHASE_END, PHASE_INIT, restore_host(), scn, sem, SYMNAME, TRUE, SEM::which_pass, and wrong_name().
Referenced by check_end_subprogram(), do_end_subprogram(), and semant1().
check_kind_type_param()
static void check_kind_type_param (int dtype) static
Definition at line 15904 of file semant.c.
References check_kind_type_param(), DTY, error(), gbl, mem(), NOSYM, and SYMNAME.
Referenced by check_kind_type_param(), and defer_put_kind_type_param().
check_module_prefix()
static void check_module_prefix () static
MODULE prefix checking for subprograms C1547: cannot be inside a an abstract interface.
Definition at line 13964 of file semant.c.
References INTERF::abstract, ERR_Severe, error(), gbl, SEM::interf_base, SEM::interface, subp_prefix_t::module, NULL, sem, and subp_prefix.
Referenced by semant1().
chk_asz_deferlen()
static int chk_asz_deferlen (int ast, int dtype) static
Definition at line 15168 of file semant.c.
References ast, chk_asz_deferlen(), DTY, mem(), NOSYM, sptr, and SYMNAME.
Referenced by chk_asz_deferlen(), and put_length_type_param().
chk_func_entry_result()
static int chk_func_entry_result (int sptr) static
Definition at line 13172 of file semant.c.
References gbl, refsym(), and sptr.
Referenced by create_func_entry(), and create_func_entry_result().
chk_initialization_with_kind_parm()
static void chk_initialization_with_kind_parm (int dtype) static
Should be called when we parse ENDTYPE. This function goes through a derived type's members and makes sure there are no length type parameters in the initialization part of a member.
Definition at line 15038 of file semant.c.
References chk_initialization_with_kind_parm(), chk_kind_parm_expr(), DTY, error(), gbl, mem(), NOSYM, and SYMNAME.
Referenced by chk_initialization_with_kind_parm(), and semant1().
chk_intrinsic()
static int chk_intrinsic (int first, LOGICAL now, LOGICAL settype) static
Definition at line 13017 of file semant.c.
References CNULL, error(), FALSE, first, gbl, getocsym(), insert_sym(), SEM::interface, IS_INTRINSIC, sem, sptr, SYMNAME, and TRUE.
Referenced by semant1().
chk_kind_parm()
static int chk_kind_parm (SST * stkp) static
Definition at line 14867 of file semant.c.
References ast, ast_traverse(), ast_unvisit(), ast_visit(), STSK::dtype, get_kind_parm(), INSIDE_STRUCT, NULL, offset, queue_type_param(), S_EXPR, S_IDENT, S_LVALUE, search_kind(), sptr, SST_ASTG, SST_IDG, SST_LSYMG, SST_SYMG, stsk, STSK_ENT, TRUE, and STSK::type.
Referenced by semant1().
chk_kind_parm_expr()
int chk_kind_parm_expr (int ast, int dtype, int flag, int strict_flag)
Definition at line 15062 of file semant.c.
References A_OPTYPEG, ARGT_ARG, ast, chk_kind_parm_expr(), get_kind_parm(), get_kind_parm_strict(), i, offset, queue_type_param(), sptr, and TRUE.
Referenced by _mk_arrdsc(), chk_initialization_with_kind_parm(), chk_kind_parm_expr(), gen_kind_parm_assignments(), put_kind_type_param(), and semant1().
chk_len_parm_expr()
int chk_len_parm_expr (int ast, int dtype, int flag)
Definition at line 15235 of file semant.c.
References ast, chk_len_parm_expr(), get_len_parm(), offset, queue_type_param(), sptr, ST_ISVAR, and TRUE.
Referenced by _mk_arrdsc(), chk_len_parm_expr(), and semant1().
chk_new_param_dt()
static void chk_new_param_dt (int sptr, int dtype) static
Definition at line 16056 of file semant.c.
References DTY, error(), gbl, mem(), NOSYM, sptr, and SYMNAME.
Referenced by semant1().
clear_ident_list()
static void clear_ident_list () static
Definition at line 13915 of file semant.c.
References dirty_ident_base, FALSE, FREE, gbl, HASHSIZE, ident_base, ident_proc_list::next, ident_list::next, ident_list::proc_list, sem, and SEM::which_pass.
Referenced by do_end_subprogram(), and semant1().
clear_iface()
static void clear_iface (int i, SPTR iface) static
Called by _do_iface() as part of error clean-up. We need to clear the next attempt to use an erroneous interface specified in the iface argument starting at the "i + 1" element in iface_base.
Definition at line 14391 of file semant.c.
References i, IFACE::iface, iface_avail, iface_base, j, sem_strcmp(), and SYMNAME.
Referenced by _do_iface().
clear_subp_prefix_settings()
static void clear_subp_prefix_settings (struct subp_prefix_t * subp) static
Reset subprogram prefixes to zeroes.
Definition at line 13955 of file semant.c.
References BZERO.
Referenced by semant1(), and semant_init().
cmp_len_parms()
int cmp_len_parms (int ast1, int ast2)
Definition at line 15335 of file semant.c.
References A_OPTYPEG, cmp_len_parms(), and CONVAL2G.
Referenced by cmp_len_parms(), and semant3().
convert_intrinsics_to_idents()
static void convert_intrinsics_to_idents (void) static
Definition at line 12988 of file semant.c.
References assert, ERR_Severe, STB::firstusym, gbl, IS_INTRINSIC, newsym(), NOSYM, sptr, and stb.
Referenced by semant1().
copy_type_to_entry()
static void copy_type_to_entry (int sptr) static
Definition at line 12807 of file semant.c.
References ctte(), e, gbl, SEM::interface, SCOPESTACK::kind, NOSYM, SCOPE_INTERFACE, SEM::scope_level, SEM::scope_stack, sem, sptr, SCOPESTACK::sptr, stb, and SCOPESTACK::symavl.
Referenced by semant1().
create_func_entry()
static int create_func_entry (int sptr) static
Definition at line 13042 of file semant.c.
References chk_func_entry_result(), CNULL, declsym(), error(), first_hash(), gbl, IN_MODULE, insert_sym(), NOSYM, pop_sym(), sem, sptr, SYMNAME, TRUE, and SEM::which_pass.
Referenced by semant1().
create_func_entry_result()
static int create_func_entry_result (int sptr) static
Definition at line 13107 of file semant.c.
References chk_func_entry_result(), declsym(), NOSYM, sptr, and TRUE.
Referenced by semant1().
create_parameterized_dt()
DTYPE create_parameterized_dt (DTYPE dtype, LOGICAL force)
Create a parameterized derived type based on dtype. If force is not set and dtype is already a PDT, return DT_NONE.
Definition at line 16298 of file semant.c.
References create_parameterized_dt(), DTY, get_parameterized_dt(), has_type_parameter(), insert_dup_sym(), is_pdt_dtype(), mem(), new_dtype(), and NOSYM.
Referenced by add_ptr_assign(), create_parameterized_dt(), defer_put_kind_type_param(), put_length_type_param(), semant1(), and semant3().
create_var()
static int create_var (int sym) static
Definition at line 13131 of file semant.c.
References error(), gbl, insert_sym(), refsym_inscope(), RU_FUNC, sptr, and SYMNAME.
Referenced by semant1().
ctte()
static void ctte (int entry, int sptr) static
Definition at line 12768 of file semant.c.
References DTY, error(), FALSE, gbl, sptr, and SYMNAME.
Referenced by copy_type_to_entry().
decl_procedure_sym()
static int decl_procedure_sym (int sptr, int proc_interf_sptr, int attr) static
Declare a procedure symbol.
Perform check nesessary for a declaration or procedure and produce a new symbol that matches procedure interface and attributes
Parameters
sptr symbol table index for the symbol
proc_interf_sptr symbol table entry for procedure interface
attr attributes (bit vector), same as entity_attr.exist
Returns
symbol table index for created symbol
Definition at line 16543 of file semant.c.
References declsym(), entity_attr, error(), ET_B, ET_NOPASS, ET_PASS, FALSE, gbl, get_procedure_stype(), IN_MODULE_SPEC, insert_sym(), NOSYM, pop_sym(), sptr, and SYMNAME.
Referenced by semant1().
decr_ident_use()
static void decr_ident_use (int ident, int proc) static
Definition at line 13972 of file semant.c.
References dirty_ident_base, gbl, HASH_STR, ident_list::ident, ident_base, ident_proc_list::next, ident_list::next, ident_list::proc_list, ident_proc_list::proc_name, sem, strlen(), SYMNAME, ident_proc_list::usecnt, and SEM::which_pass.
Referenced by semant1().
defer_ident_list()
static void defer_ident_list (int ident, int proc) static
Definition at line 13995 of file semant.c.
References dirty_ident_base, gbl, HASH_STR, ident_list::ident, ident_base, NEW, ident_proc_list::next, ident_list::next, ident_list::proc_list, ident_proc_list::proc_name, strlen(), SYMNAME, TRUE, and ident_proc_list::usecnt.
Referenced by semant1().
defer_iface()
static void defer_iface (int iface, int dtype, int proc, int mem) static
Definition at line 14134 of file semant.c.
References STSK::dtype, IFACE::dtype, gbl, IFACE::iface, iface_avail, iface_base, iface_size, IFACE::internal, len, IFACE::lineno, IFACE::mem, mem(), NEED, NEW, IFACE::pass_class, IFACE::proc, IFACE::proc_var, IFACE::scope, sem, IFACE::sem_pass, strlen(), stsk, SYMNAME, IFACE::tag_name, and SEM::which_pass.
Referenced by setup_procedure_sym().
defer_pt_decl()
int defer_pt_decl (int dtype, int flag)
Store dtypes of parameterized derived types in which a parameter was explicitly declared (as opposed to using just the default values).
Definition at line 15377 of file semant.c.
References FREE, SEM::interface, NEW, next, NULL, prev, sem, and SEM::which_pass.
Referenced by do_end_subprogram(), semant1(), and semant2().
defer_put_kind_type_param()
static void defer_put_kind_type_param (int offset, int value, char * name, int dtype, int ast, int flag) static
Definition at line 15414 of file semant.c.
References ast, check_kind_type_param(), create_parameterized_dt(), DTY, error(), FREE, gbl, get_kind_parm_by_name(), i, name, NEW, SEM::new_param_dt, next, NULL, offset, SEM::param_assume_sz, SEM::param_defer_len, prev, put_kind_type_param(), sem, and value().
Referenced by semant1().
do_end_subprogram()
static void do_end_subprogram (SST * top, RU_TYPE rutype) static
Reset scopes and related set ups after processing and subroutine
IN_MODULE
Definition at line 12900 of file semant.c.
References check_defined_io(), check_end_subprogram(), clear_ident_list(), defer_pt_decl(), do_iface_module(), dummy_program(), FALSE, fix_class_args(), fix_iface(), fix_proc_ptr_dummy_args(), gbl, IN_MODULE, SEM::interface, LHS, SEM::mod_cnt, mod_end_subprogram(), pop_scope_level(), queue_tbp(), RHS, SCOPE_NORMAL, SEM::seen_import, sem, SST_IDP, SST_SYMG, TBP_CLEAR, TBP_COMPLETE_END, and SEM::which_pass.
Referenced by semant1().
do_fixup_param_vars_for_derived_arrays()
static bool do_fixup_param_vars_for_derived_arrays (bool inited, SPTR sptr, int sst_idg) static
To re-initialize an array of derived types when found the following conditions are satisfied:
the element of the array is a derived type.
the array has been initialized before and needs to be re-initialized.
none of any entity attributes used for array definition.
Definition at line 16827 of file semant.c.
References SEM::dinit_count, DTY, DTYG, entity_attr, inited, S_ACONST, sem, and sptr.
Referenced by semant1().
do_iface()
static void do_iface (int iface_state) static
Definition at line 14288 of file semant.c.
References _do_iface(), i, and iface_avail.
Referenced by semant1().
do_iface_module()
static void do_iface_module (void) static
Definition at line 14300 of file semant.c.
References _do_iface(), assert, ERR_Fatal, gbl, get_seen_contains(), i, IFACE::iface, iface_avail, iface_base, IN_MODULE, SEM::interface, sem, and SEM::which_pass.
Referenced by do_end_subprogram(), and semant1().
dup_acl()
static ACL * dup_acl (ACL * src, int sptr) static
Definition at line 16416 of file semant.c.
References DTY, _acl::dtype, dup_acl(), GET_ACL, match_memname(), next, _acl::next, sptr, _acl::sptr, src, and _acl::subc.
Referenced by dup_acl(), and get_parameterized_dt().
end_subprogram_checks()
static void end_subprogram_checks () static
Definition at line 766 of file semant.c.
References SEM::cnt, CNULL, SEM::critical, DI_LINENO, SEM::doif_depth, error(), SEM::lineno, SEM::master, sem, and sem_err104().
Referenced by semant1().
eval_KIND_expr()
static int eval_KIND_expr (int ast, int * val, int * dtyp) static
Definition at line 13682 of file semant.c.
References A_OPTYPEG, ast, complex_alias(), const_fold(), CONVAL2G, eval_KIND_expr(), negate_const(), OP_LNOT, OP_SUB, and val.
Referenced by eval_KIND_expr(), and get_retval_KIND_value().
fix_iface()
static void fix_iface (int sptr) static
Definition at line 14206 of file semant.c.
References aux, AUX::dpdsc_base, DTY, IFACE::dtype, find_dummy_position(), i, IFACE::iface, iface_avail, iface_base, IFACE::iface_name, j, len, IFACE::mem, mem(), name, NEW, IFACE::pass_class, IFACE::proc, sptr, strlen(), and SYMNAME.
Referenced by do_end_subprogram(), and semant1().
fix_iface0()
static void fix_iface0 () static
This routine sets the PASS field in a procedure pointer for semantic pass 0 prior to call to end_module().
This is needed, otherwise we may incorrectly write the procedure pointer module info without PASS set.
Definition at line 14182 of file semant.c.
References aux, AUX::dpdsc_base, findByNameStypeScope(), i, iface_avail, iface_base, IFACE::iface_name, IFACE::mem, mem(), name, sem, IFACE::stype, and SEM::which_pass.
Referenced by semant1().
fix_proc_ptr_dummy_args()
static void fix_proc_ptr_dummy_args () static
Definition at line 14256 of file semant.c.
References aux, cmp_interfaces(), AUX::dpdsc_base, DTY, gbl, HASH_ID, STB::hashtb, i, is_procedure_ptr(), len, NULL, proc_arginfo(), sem, sptr, stb, strlen(), SYMNAME, test_scope(), TRUE, and SEM::which_pass.
Referenced by do_end_subprogram(), and semant1().
fixup_function_return_type()
static void fixup_function_return_type (int retdtype, int dtsptr) static
Definition at line 13574 of file semant.c.
References CNULL, DTY, error(), FUNCLINEG, gbl, lookupsymbol(), SEM::pgphase, PHASE_SPEC, sem, and SYMNAME.
Referenced by semant1().
fixup_KIND_expr()
static int fixup_KIND_expr (int ast) static
Definition at line 13589 of file semant.c.
References A_ARGCNTG, A_OPTYPEG, ADD_NUMDIM, argt, ARGT_ARG, ast, CONVAL2G, DT_INT, DT_ISREAL, DTY, findByNameStypeScope(), fixup_KIND_expr(), i, MAXRANK, mk_binop(), mk_cnst(), mk_convert(), mk_id(), mk_member(), mk_subscr(), mk_unop(), ndim, SEM::pgphase, PHASE_USE, sem, sptr, and SYMNAME.
Referenced by fixup_KIND_expr(), get_retval_KIND_value(), and get_retval_LEN_value().
fixup_param_vars()
static void fixup_param_vars (SST * var, SST * init) static
Definition at line 13266 of file semant.c.
References AD_ADJARR, AD_ASSUMSZ, AD_DEFER, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_MLPYR, AD_NOBOUNDS, AD_NUMDIM, AD_UPAST, AD_UPBD, ad_val_of(), AD_ZBASE, ADD_LWAST, astb, ASTB::bnd, construct_acl_for_sst(), construct_acl_from_ast(), STB::curr_scope, DDTG, declsym(), dinit_struct_param(), DTY, ASTB::dtype, error(), flg, gbl, get_param_alias_const(), get_param_alias_var(), i, init(), init_named_array_constant(), SEM::interface, mk_bnd_int(), mk_isz_cval(), mk_shared_extent(), ndim, ASTB::one, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_SCONST, sem, set_string_type_from_init(), sptr, SST_ACLG, SST_ASTG, SST_DTYPEG, SST_IDG, SST_SYMG, stb, sym_of_ast(), SYMNAME, TRUE, FLG::xref, xrefput(), zbase, and ASTB::zero.
Referenced by semant1().
gen_dinit()
static void gen_dinit (int sptr, SST * stkptr) static
Definition at line 12526 of file semant.c.
References CNULL, dinit(), SEM::dinit_count, SEM::dinit_error, dinit_ok(), dinit_varref(), error(), errsev(), FALSE, FLANG_FALLTHROUGH, flg, gbl, STSK::ict_beg, STSK::ict_end, INSIDE_STRUCT, mk_id(), mkident(), newsym(), next, sem, sptr, SST_ASTG, SST_ASTP, SST_CLBEGG, SST_CLENDG, SST_DTYPEP, SST_SHAPEP, SST_SYMP, stsk, STSK_ENT, SYMNAME, TRUE, FLG::xref, and xrefput().
Referenced by semant1().
gen_unique_func_ast()
static void gen_unique_func_ast (int ast, SPTR sptr, SST * stkptr) static
Make a unique func ast with a unique sptr (and name) so we can set its associated pointer field. The unique sptr is a placeholder for the pointer target so it does not conflict with the original ST_PROC symbol. We hold the original pointer target in the PTR_TARGET field.
Definition at line 12505 of file semant.c.
References ast, get_next_sym(), replace_memsym_of_ast(), sptr, SST_ASTP, sym_of_ast(), and SYMNAME.
Referenced by semant1().
get_entity_access()
int get_entity_access ()
provide the current entity's access to other source files.
Definition at line 16488 of file semant.c.
References entity_attr.
Referenced by link_members().
get_highest_param_offset()
static int get_highest_param_offset (int dtype) static
Definition at line 16274 of file semant.c.
References DTY, get_highest_param_offset(), mem(), NOSYM, p, and start.
Referenced by get_highest_param_offset(), and semant1().
get_kind_parm()
static int get_kind_parm (int sptr, int dtype) static
Definition at line 14902 of file semant.c.
References DTY, get_kind_parm(), mem(), NOSYM, sptr, and SYMNAME.
Referenced by chk_kind_parm(), chk_kind_parm_expr(), get_kind_parm(), get_kind_parm_strict(), and search_kind().
get_kind_parm_by_name()
int get_kind_parm_by_name (char * np, int dtype)
search a derived type for a kind type parameter with a specified name.
Parameters
np is the name we're search for
dtype is the derived type record that we are searching
Returns
integer > 0 for the parameter number, else 0 if not found.
Definition at line 14955 of file semant.c.
References DTY, get_kind_parm_by_name(), mem(), NOSYM, and SYMNAME.
Referenced by defer_put_kind_type_param(), get_keyword_components(), get_kind_parm_by_name(), and semant2().
get_kind_parm_strict()
static int get_kind_parm_strict (int sptr, int dtype) static
Definition at line 14924 of file semant.c.
References DTY, get_kind_parm(), mem(), NOSYM, sptr, and SYMNAME.
Referenced by chk_kind_parm_expr(), and has_kind_parm_expr().
get_len_parm()
static int get_len_parm (int sptr, int dtype) static
Definition at line 15213 of file semant.c.
References DTY, get_len_parm(), mem(), NOSYM, sptr, and SYMNAME.
Referenced by chk_len_parm_expr(), get_len_parm(), and put_kind_type_param().
get_len_parm_by_number()
int get_len_parm_by_number (int num, int dtype, int flag)
Definition at line 15851 of file semant.c.
References DT_INT, DTY, get_len_parm_by_number(), getcon(), i, mem(), mk_cnst(), mk_id(), NOSYM, num, and val.
Referenced by get_len_parm_by_number(), put_kind_type_param(), and ref_pd().
get_len_set_parm_by_name()
int get_len_set_parm_by_name (char * np, int dtype, int * val)
Definition at line 15311 of file semant.c.
References DTY, get_len_set_parm_by_name(), mem(), NOSYM, SYMNAME, and val.
Referenced by get_keyword_components(), and get_len_set_parm_by_name().
get_param_alias_const()
static void get_param_alias_const (SST * stkp, int param_sptr, int dtype) static
Definition at line 13207 of file semant.c.
References sst::acl, add_param(), ast, chkcon(), cngcon(), sst::cnval, construct_acl_for_sst(), construct_acl_from_ast(), _acl::conval, CONVAL2P, SEM::dinit_error, _acl::dtype, eval_init_expr(), FALSE, SEM::interface, mk_cval1(), mk_id(), S_EXPR, S_LVALUE, sem, SST_ACLG, SST_ASTG, SST_IDG, and sst::value.
Referenced by fixup_param_vars().
get_parameterized_dt()
DTYPE get_parameterized_dt (DTYPE dtype)
Duplicate dtype by creating a new derived type with a $pt suffix. For use with processing parameterized derived type.
Definition at line 16335 of file semant.c.
References assert, chkstruct(), declsym(), DTY, dup_acl(), dup_array_dtype(), ERR_Fatal, get_getitem_p(), get_member_descriptor(), get_next_sym(), get_type(), insert_dup_sym(), match_memname(), mem(), new_dtype(), NOSYM, put_getitem_p(), sptr, SYMNAME, and TRUE.
Referenced by create_parameterized_dt(), and semant2().
get_parm_by_name()
int get_parm_by_name (char * np, int dtype)
search a derived type for a kind or length type parameter with a specified name.
Parameters
np is the name we're search for
dtype is the derived type record that we are searching
Returns
integer > 0 for the parameter number, else 0 if not found.
Definition at line 15013 of file semant.c.
References DTY, get_parm_by_name(), mem(), NOSYM, and SYMNAME.
Referenced by get_parm_by_name(), and semant3().
get_parm_by_number()
int get_parm_by_number (int offset, int dtype)
search derived type for a type parameter in the same position as specified by offset.
Parameters
offset is the desired parameter position
dtype is the derived type record to search in
Returns
symbol table pointer of the parameter component in the derived type; else 0 if not found.
Definition at line 14985 of file semant.c.
References DTY, get_parm_by_number(), mem(), NOSYM, and offset.
Referenced by get_parm_by_number(), and semant3().
get_procedure_stype()
static int get_procedure_stype (int attr) static
Determine procedure symbol type for a set of attributes.
Parameters
attr attribute mask
Returns
symbol type index, zero on error
Definition at line 16514 of file semant.c.
References ET_B, ET_POINTER, and INSIDE_STRUCT.
Referenced by decl_procedure_sym(), and setup_procedure_sym().
get_retval_derived_type()
static void get_retval_derived_type () static
Definition at line 13824 of file semant.c.
References SEM::deferred_dertype, SEM::deferred_kind_len_lineno, error(), FALSE, first_hash(), gbl, NOSYM, pop_sym(), RU_FUNC, sem, sptr, SYMNAME, and TRUE.
Referenced by semant1().
get_retval_KIND_value()
static void get_retval_KIND_value () static
Definition at line 13735 of file semant.c.
References A_ISEXPR, SEM::deferred_func_kind, SEM::deferred_func_len, SEM::deferred_kind_len_lineno, DTY, errsev(), errwarn(), eval_KIND_expr(), findByNameStypeScope(), fixup_KIND_expr(), gbl, select_kind(), sem, sptr, SYMNAME, TRUE, and val.
Referenced by semant1().
get_retval_LEN_value()
static void get_retval_LEN_value () static
Definition at line 13791 of file semant.c.
References CONVAL2G, SEM::deferred_func_len, SEM::deferred_kind_len_lineno, DTY, fixup_KIND_expr(), gbl, mod_type(), SEM::ogdtype, and sem.
Referenced by semant1().
get_unl_poly_sym()
int get_unl_poly_sym (int mem_dtype)
Definition at line 16118 of file semant.c.
References declsym(), SEM::dtemps, DTY, get_static_type_descriptor(), get_type(), getccsym_sc(), getsymf(), SEM::interface, mem(), NOSYM, sem, sptr, and TRUE.
Referenced by semant1(), and semant3().
get_vtoff()
static int get_vtoff (int vtoff, DTYPE dtype) static
Definition at line 16096 of file semant.c.
References get_struct_members(), get_struct_tag_sptr(), get_vtoff(), is_tbp(), and NOSYM.
Referenced by get_vtoff(), and semant1().
getCref()
int getCref (void)
provide cref variable state to other source files.
Definition at line 16502 of file semant.c.
References cref.
Referenced by fixupImp(), and resolveImp().
getMscall()
int getMscall (void)
provide mscall variable state to other source files.
Definition at line 16495 of file semant.c.
References mscall.
Referenced by fixupImp(), and resolveImp().
has_kind_parm_expr()
static int has_kind_parm_expr (int ast, int dtype, int flag) static
Definition at line 15116 of file semant.c.
References A_OPTYPEG, ARGT_ARG, ast, get_kind_parm_strict(), has_kind_parm_expr(), i, offset, queue_type_param(), sptr, and TRUE.
Referenced by has_kind_parm_expr(), and semant1().
has_length_type_parameter_use()
int has_length_type_parameter_use (int dtype)
Definition at line 16254 of file semant.c.
References DTY, has_length_type_parameter_use(), mem(), and NOSYM.
Referenced by has_length_type_parameter_use(), and rewrite_calls().
has_type_parameter()
int has_type_parameter (int dtype)
checks to see if derived type record, dtype, has any type parameters (kind or length type parameters).
Parameters
dtype is the derived type record we're searching
Returns
integer > 0 if dtype has type parameters; else 0.
Definition at line 16227 of file semant.c.
References has_type_parameter2().
Referenced by add_ptr_assign(), add_type_param_initialize(), construct_acl_for_sst(), create_parameterized_dt(), gen_derived_type_alloc_init(), gen_kind_parm_assignments(), put_default_kind_type_param(), put_length_type_param(), semant1(), semant2(), and semant3().
has_type_parameter2()
static int has_type_parameter2 (int dtype, int visit_flag) static
Returns true if dtype is a derived type that has a type parameter or if it has a component that has a type parameter.
This function also takes into account recursive components.
Definition at line 16160 of file semant.c.
References DTY, FREE, has_type_parameter2(), NEW, next, visit_list::next, NOSYM, prev, and visit_list.
Referenced by has_type_parameter(), and has_type_parameter2().
ignore_common_decl()
static LOGICAL ignore_common_decl (void) static
Definition at line 16466 of file semant.c.
References FALSE, gbl, SEM::mod_cnt, sem, TRUE, and SEM::which_pass.
Referenced by semant1().
in_intrinsic_decl()
bool in_intrinsic_decl (void)
Return the predicate: current entity has the INTRINSIC attribute.
Definition at line 16481 of file semant.c.
References entity_attr, ET_B, and ET_INTRINSIC.
init_allocatable_typedef_components() [1/2]
static void init_allocatable_typedef_components (int) static
Referenced by init_allocatable_typedef_components(), and semant1().
init_allocatable_typedef_components() [2/2]
static void init_allocatable_typedef_components (SPTR td_sptr) static
Definition at line 13505 of file semant.c.
References AC_I_null, AC_TYPEINIT, array_element_dtype(), df_dinit(), DTY, _acl::dtype, GET_ACL, get_getitem_p(), get_struct_initialization_tree(), _acl::id, init_allocatable_typedef_components(), is_array_dtype(), mk_init_intrinsic(), _acl::next, NOSYM, NULL, put_getitem_p(), sptr, _acl::sptr, and _acl::subc.
internal_proc_has_ident()
int internal_proc_has_ident (int ident, int proc)
Definition at line 14042 of file semant.c.
References dirty_ident_base, HASH_STR, ident_list::ident, ident_base, ident_proc_list::next, ident_list::next, ident_list::proc_list, ident_proc_list::proc_name, strlen(), SYMNAME, and ident_proc_list::usecnt.
Referenced by declsym(), and semant1().
is_parameter_context()
int is_parameter_context ()
allow other source files to check whether we're processing a parameter construct.
Definition at line 16460 of file semant.c.
References entity_attr, ET_B, and ET_PARAMETER.
Referenced by _mk_arrdsc(), and semant2().
is_pdt_dtype()
static LOGICAL is_pdt_dtype (DTYPE dtype) static
Definition at line 16450 of file semant.c.
References DTY, and SYMNAME.
Referenced by create_parameterized_dt(), and put_kind_type_param().
match_memname()
static int match_memname (int sptr, int list) static
Definition at line 16438 of file semant.c.
References mem(), NOSYM, and sptr.
Referenced by dup_acl(), and get_parameterized_dt().
name_of_rutype()
static const char * name_of_rutype (RU_TYPE rutype) static
Definition at line 12967 of file semant.c.
References RU_BDATA, RU_FUNC, RU_PROC, RU_PROG, and RU_SUBR.
Referenced by check_end_subprogram(), and semant1().
pop_subprogram()
static void pop_subprogram (void) static
Definition at line 12604 of file semant.c.
References arg, aux, FLG::dclchk, DCLCHK, AUX::dpdsc_base, FALSE, flg, gbl, i, SEM::interface, SEM::module_procedure, SEM::none_implicit, SYMUTL::none_implicit, SEM::pgphase, PHASE_INIT, pop_sym(), RU_FUNC, scope, seen_implicit, seen_parameter, sem, symutl, and TRUE.
Referenced by semant1().
process_bind()
static void process_bind (int sptr) static
Definition at line 13856 of file semant.c.
References dec_attr_t::altname, bind_attr, DA_ALIAS, DA_B, DA_C, dec_attr_t::exist, getstring(), STB::n_base, sptr, stb, strlen(), SYMNAME, and XBIT.
Referenced by semant1(), and setup_procedure_sym().
put_default_kind_type_param()
void put_default_kind_type_param (int dtype, int flag, int flag2)
Definition at line 15492 of file semant.c.
References BZERO, chkstruct(), DTY, FREE, has_type_parameter(), mem(), NEW, next, NOSYM, NULL, offset, prev, put_default_kind_type_param(), put_kind_type_param(), and val.
Referenced by get_keyword_components(), put_default_kind_type_param(), and semant1().
put_kind_type_param()
LOGICAL put_kind_type_param (DTYPE dtype, int offset, int value, int expr, int flag)
Definition at line 15922 of file semant.c.
References ast, chk_kind_parm_expr(), chk_kind_parm_set_expr(), CONVAL2G, DT_ISCMPLX, DT_ISINT, DT_ISREAL, DTY, ERR_Severe, error(), FALSE, gbl, get_len_parm(), get_len_parm_by_number(), get_type(), is_pdt_dtype(), mem(), SEM::new_param_dt, NOSYM, offset, put_kind_type_param(), select_kind(), sem, sym_of_ast(), SYMNAME, TRUE, TY_CHAR, TY_CMPLX, TY_INT, TY_NCHAR, TY_REAL, SEM::type_mode, and value().
Referenced by defer_put_kind_type_param(), put_default_kind_type_param(), put_kind_type_param(), and semant2().
put_length_type_param()
void put_length_type_param (DTYPE dtype, int flag)
Definition at line 15536 of file semant.c.
References A_OPTYPEG, A_OPTYPEP, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_MLPYR, AD_NUMDIM, AD_UPAST, ADD_NUMELM, ast, astb, ASTB::bnd, BZERO, chk_asz_deferlen(), chk_kind_parm_set_expr(), chkstruct(), cl, CONVAL2G, create_parameterized_dt(), DT_INT, DTY, ASTB::dtype, dup_array_dtype(), FREE, get_all_descriptors(), get_extent(), get_local_multiplier(), get_static_descriptor(), has_type_parameter(), i, ASTB::i0, interr(), lb, mem(), mk_binop(), mk_bnd_int(), mk_id(), mk_isz_cval(), mk_stmt(), NEW, SEM::new_param_dt, next, NOSYM, NULL, OP_ADD, OP_MUL, OP_SUB, prev, put_length_type_param(), replace_sdsc_in_bounds(), sem, sym_get_scalar(), sym_get_sdescr(), SYMNAME, TRUE, TY_CHAR, TY_NCHAR, and ub.
Referenced by get_keyword_components(), put_length_type_param(), semant1(), and semant3().
queue_type_param()
int queue_type_param (int sptr, int dtype, int offset, int flag)
Sets up type parameters used in parameterized derived types (PDTs)
Definition at line 14647 of file semant.c.
References BZERO, c, DTY, error(), FREE, gbl, i, mem(), name, NEW, next, NOSYM, offset, parent, prev, queue_type_param(), sptr, strlen(), and SYMNAME.
Referenced by chk_kind_parm(), chk_kind_parm_expr(), chk_len_parm_expr(), has_kind_parm_expr(), queue_type_param(), search_kind(), semant1(), and semant2().
record_func_result()
static void record_func_result (int func_sptr, int func_result_sptr, LOGICAL in_ENTRY) static
Definition at line 16706 of file semant.c.
References STB::curr_scope, error(), gbl, insert_sym(), SEM::interface, pop_sym(), RU_FUNC, sem, stb, SYMNAME, and TRUE.
Referenced by semant1().
reloc_byvalue_parameters()
static void reloc_byvalue_parameters () static
Definition at line 662 of file semant.c.
References aux, BYVALDEFAULT, AUX::dpdsc_base, DTY, dup_sym(), error(), gbl, getsymf(), SEM::intent_list, itemp, lookupsymf(), NOSYM, NULL, sem, stb, sym_is_refd(), SYMNAME, TRUE, and SEM::which_pass.
Referenced by semant1().
replace_sdsc_in_ast()
static int replace_sdsc_in_ast (int sdsc, int ast) static
Definition at line 15821 of file semant.c.
References A_OPTYPEG, ast, mk_binop(), mk_id(), mk_subscr_copy(), replace_sdsc_in_ast(), sptr, and SYMNAME.
Referenced by replace_sdsc_in_ast(), and replace_sdsc_in_bounds().
replace_sdsc_in_bounds()
static void replace_sdsc_in_bounds (int sdsc, ADSC * ad, int i) static
Definition at line 15796 of file semant.c.
References AD_LWAST, AD_LWBD, AD_UPAST, AD_UPBD, ast, i, and replace_sdsc_in_ast().
Referenced by put_length_type_param().
restore_host()
static void restore_host (INTERF * state, LOGICAL keep_implicit) static
Definition at line 12863 of file semant.c.
References INTERF::currsub, FALSE, gbl, INTERF::module_procedure, SEM::module_procedure, INTERF::nml, SEM::nml, INTERF::none_implicit, SEM::none_implicit, SYMUTL::none_implicit, INTERF::pgphase, SEM::pgphase, restore_implicit(), INTERF::rutype, save_implicit(), seen_implicit, INTERF::seen_implicit, seen_parameter, INTERF::seen_parameter, sem, symutl, and TRUE.
Referenced by check_end_subprogram(), and semant1().
save_host()
static void save_host (INTERF * state) static
Definition at line 12840 of file semant.c.
References INTERF::currsub, FLG::dclchk, FALSE, flg, gbl, INTERF::gnr_rutype, INTERF::module_procedure, SEM::module_procedure, INTERF::nml, SEM::nml, INTERF::none_implicit, SEM::none_implicit, SYMUTL::none_implicit, INTERF::pgphase, SEM::pgphase, PHASE_INIT, INTERF::rutype, save_implicit(), seen_implicit, INTERF::seen_implicit, seen_parameter, INTERF::seen_parameter, sem, and symutl.
Referenced by semant1().
save_typedef_init()
static void save_typedef_init (int sptr, int dtype) static
Definition at line 13433 of file semant.c.
References AC_TYPEINIT, astb, df_dinit(), DTY, _acl::dtype, GET_ACL, ASTB::i1, STSK::ict_beg, _acl::id, _acl::next, NULL, put_getitem_p(), _acl::repeatc, sem, sptr, _acl::sptr, stsk, SEM::stsk_depth, STSK_ENT, _acl::subc, and TRUE.
Referenced by semant1().
search_kind()
static void search_kind (int ast, int * offset) static
Definition at line 14844 of file semant.c.
References ast, STSK::dtype, get_kind_parm(), offset, queue_type_param(), sem, sptr, stsk, SEM::stsk_depth, and STSK_ENT.
Referenced by chk_kind_parm().
sem_pgphase_name()
const char * sem_pgphase_name ()
Definition at line 16791 of file semant.c.
References SEM::pgphase, PHASE_CONTAIN, PHASE_END, PHASE_END_MODULE, PHASE_EXEC, PHASE_HEADER, PHASE_IMPLICIT, PHASE_IMPORT, PHASE_INIT, PHASE_INTERNAL, PHASE_SPEC, PHASE_USE, and sem.
semant1()
void semant1 (int rednum, SST * top)
Semantic actions - part 1.
Parameters
rednum reduction number
top top of stack after reduction
IN_MODULE
IN_MODULE
Definition at line 782 of file semant.c.
References _INF_CLEN, INTERF::abstract, AC_AST, AC_SCONST, SEM::ac_std_range, AC_VMSSTRUCT, AC_VMSUNION, SEM::accl, SEM::action_type, AD_ADJARR, AD_ASSUMSHP, AD_ASSUMSZ, AD_DEFER, AD_DPTR, AD_LWAST, AD_LWBD, AD_NUMDIM, AD_NUMELM, AD_PTR, AD_UPAST, AD_UPBD, ad_val_of(), add_auto_finalize(), ADD_DEFER, ADD_NOBOUNDS, add_overload(), add_param(), add_stmt(), add_submodule_use(), add_symitem(), add_type_param_initialize(), add_use_rename(), add_use_stmt(), SEM::alloc_std, dec_attr_t::altname, SEM::apply, apply_use_stmts(), SEM::array_const_level, SEM::arrdim, assert, ast, xyyz::ast, _acl::ast, SEM::ast, ast_implicit(), ast_isparam(), ast_to_comment(), astb, SEM::atomic, ATOMIC_CAPTURE, ASTB::atypes, SEM::autoloc, aux, BCOPY, begin_contains(), begin_module(), begin_submodule(), bind_attr, bindingNameRequiresOverloading(), SEM::blksymnum, block_local_sym(), SEM::block_scope, ASTB::bnd, SEM::bounds, buf, build_typedef_init_tree(), ch_substring(), check_defined_io(), check_duplicate(), check_end_subprogram(), check_generic(), check_module_prefix(), check_no_scope_sptr(), chk_adjarr(), chk_arr_extent(), chk_initialization_with_kind_parm(), chk_intrinsic(), chk_kind_parm(), chk_kind_parm_expr(), chk_len_parm_expr(), chk_new_param_dt(), chk_scalartyp(), chk_struct_constructor(), chkcon(), chkcon_to_isz(), chkstruct(), chktyp(), SEM::class, clear_ident_list(), clear_subp_prefix_settings(), close_module(), SEM::close_pdo, SCOPESTACK::closed, CMEMLG, CMEMLP, CMP_IFACE_NAMES, cmp_interfaces_strict(), CMP_SUBMOD_IFACE, cngcon(), CNULL, SEM::collapse, SEM::collapse_depth, SEM::collapsed_acc_do, constant_lvalue(), construct_acl_for_sst(), construct_acl_from_ast(), construct_name, SEM::construct_sptr, SEM::contiguous, _acl::conval, CONVAL2G, CONVAL2P, convert_intrinsics_to_idents(), copy_specifics(), copy_sym_flags(), copy_type_to_entry(), count, create_func_entry(), create_func_entry_result(), create_parameterized_dt(), create_var(), cref, cuda_enabled(), CUDA_HOST, CUDAG, STB::curr_scope, SCN::currlab, d, da, DA_ALIAS, DA_B, DA_C, DA_DECORATE, DA_DLLEXPORT, DA_DLLIMPORT, DA_NOMIXEDSLA, DA_REFERENCE, DA_STDCALL, DA_VALUE, DDTG, FLG::debug, dec_attr, decl_procedure_sym(), declref(), declsym(), decr_ident_use(), def, defer_arg_chk(), defer_ident_list(), defer_pt_decl(), defer_put_kind_type_param(), SEM::deferred_dertype, SEM::deferred_func_kind, SEM::deferred_func_len, SEM::deferred_kind_len_lineno, SEM::defined_io_type, DI_ACCDO, DI_ACCKERNELSDO, DI_ACCKERNELSLOOP, DI_ACCLOOP, DI_ACCPARALLELDO, DI_ACCPARALLELLOOP, DI_ACCREGDO, DI_ACCREGLOOP, DI_ACCSERIALLOOP, DI_B, DI_BLOCK, DI_CUFKERNEL, DI_DISTPARDO, DI_DISTRIBUTE, DI_DO, DI_DO_LABEL, DI_DOACROSS, DI_DOCONCURRENT, DI_DOINFO, DI_DOWHILE, DI_ENCL_BLOCK_SCOPE, DI_EXIT_LABEL, DI_FIRST_DIRECTIVE, DI_ID, DI_ISSIMD, DI_LINENO, DI_NAME, DI_NEST, DI_PARDO, DI_PDO, DI_SELECT_TYPE, DI_SIMD, DI_TARGETSIMD, DI_TARGPARDO, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TASKLOOP, DI_TEAMS, DI_TEAMSDIST, DI_TEAMSDISTPARDO, dim, dinit(), SEM::dinit_count, SEM::dinit_data, SEM::dinit_error, dinit_struct_vals(), dinit_varref(), direct_loop_end(), SCN::directive, DLL_EXPORT, DLL_IMPORT, DLLP, do_end(), do_end_subprogram(), do_fixup_param_vars_for_derived_arrays(), do_iface(), do_iface_module(), Doend, VAR::doend, SEM::doif_base, SEM::doif_depth, Dostart, VAR::dostart, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, STB::dt_cmplx, DT_CMPLX, DT_DBLE, DT_DCMPLX, STB::dt_int, DT_INT, DT_ISINT, DT_ISWORD, STB::dt_log, DT_LOG, DT_PTR, STB::dt_real, DT_REAL, DTY, DTYG, _acl::dtype, STSK::dtype, ASTB::dtype, dummy_program(), subp_prefix_t::elemental, SEM::elp_stack, emit_bcs_ecs(), end, SEM::end_host_labno, end_module(), end_of_host, end_param(), end_subprogram_checks(), end_target(), end_teams(), ENDLINEP, enforce_denorm(), entity_attr, entry_seen, eq_dtype2(), SEM::equal_initializer, EQV, SEM::eqv_avail, SEM::eqv_base, EQV_NUMSS, SEM::eqv_size, EQV_SS, SEM::eqv_ss_avail, SEM::eqv_ss_base, SEM::eqv_ss_size, SEM::eqvlist, err307(), ERR310, ERR_Severe, errlabel(), error(), errsev(), errwarn(), et, ET_ACCESS, ET_ALLOCATABLE, ET_ASYNCHRONOUS, ET_AUTOMATIC, ET_B, ET_BIND, ET_CONSTANT, ET_CONTIGUOUS, ET_DEVICE, ET_DIMENSION, ET_EXTERNAL, ET_INTENT, ET_INTRINSIC, ET_KIND, ET_LEN, ET_MANAGED, ET_NOPASS, ET_OPTIONAL, ET_PARAMETER, ET_PASS, ET_PINNED, ET_POINTER, ET_PROTECTED, ET_SAVE, ET_SHARED, ET_STATIC, ET_TARGET, ET_TEXTURE, ET_VALUE, ET_VOLATILE, eval_init_expr(), dec_attr_t::exist, SEM::expect_acc_do, SEM::expect_cuf_do, SEM::expect_dist_do, SEM::expect_do, SEM::expect_simd_do, SEM::extends, FALSE, fe_save_state(), find_explicit_interface(), findByNameStypeScope(), first_hash(), STB::firstusym, fix_class_args(), fix_iface(), fix_iface0(), fix_proc_ptr_dummy_args(), fix_type_param_members(), fixup_function_return_type(), fixup_param_vars(), FLANG_FALLTHROUGH, flg, freearea(), FUNCLINEG, FUNCLINEP, gbl, SEM::gcvlen, SEM::gdtype, gen_deallocate_arrays(), gen_dinit(), gen_unique_func_ast(), INTERF::generic, SEM::generic_tbp, GET_ACL, get_all_descriptors(), get_construct_name(), get_descriptor_sc(), get_getitem_p(), get_highest_param_offset(), get_int_cval(), get_intrinsic_opr(), get_intrinsic_oprsym(), get_isz_cval(), get_named_stmtyp(), get_next_hash_link(), get_next_sym(), get_nml_array(), get_retval_derived_type(), get_retval_KIND_value(), get_retval_LEN_value(), get_seen_contains(), get_static_descriptor(), get_static_type_descriptor(), get_struct_members(), get_type(), get_unl_poly_sym(), get_vtoff(), getccsym(), getcon(), getitem(), getlab(), getocsym(), getstring(), getsym(), getsymbol(), getsymf(), INTERF::gnr_rutype, SEM::gty, has_finalized_component(), has_kind_parm_expr(), has_tbp_or_final(), has_type_parameter(), have_module_state(), host_present, host_state, INTERF::hpfdcl, SEM::hpfdcl, i, STB::i0, ASTB::i1, STSK::ict_beg, STSK::ict_end, SCN::id, _acl::id, VAR::id, ident_host_sub, idx, IGNORE_C, ignore_common_decl(), IGNORE_D, IGNORE_K, IGNORE_M, IGNORE_R, SEM::ignore_stmt, IGNORE_T, IGNORE_TKR_ALL, subp_prefix_t::impure, SEM::in_dim, in_entity_typdcl, SEM::in_enum, IN_MODULE, IN_MODULE_SPEC, in_save_scope(), SEM::in_struct_constr, VAR::indvar, init_allocatable_typedef_components(), init_implicit(), init_use_stmts(), inited, insert_sym(), INSIDE_STRUCT, instantiate_interface(), INTENT_DFLT, INTENT_IN, INTENT_INOUT, SEM::intent_list, INTENT_OUT, INTENTP, SEM::interf_base, SEM::interf_size, SEM::interface, internal_proc_has_ident(), interr(), SEM::is_acc, is_empty_typedef(), is_entry, is_exe_stmt, is_executable(), SCN::is_hpf, SEM::is_hpf, is_impure(), IS_INTRINSIC, is_procedure_dtype(), is_procedure_ptr(), is_procedure_ptr_dtype(), IS_TBP, is_tbp(), ISZ_T, ITEM_END, itemp, j, kind, SCOPESTACK::kind, SEM::kind_candidate, SEM::kind_type_param, STSK::last, SEM::last_std, lb, len, SEM::len_candidate, SEM::len_type_param, lenspec, LHS, link_members(), link_parents(), LOCAL_SYMNAME, VAR::lowbd, MAXDIMS, STSK::mem_access, mk_alias(), mk_arrdsc(), mk_assumed_shape(), mk_bnd_int(), mk_cnst(), mk_comstr(), mk_cval(), mk_cval1(), mk_defer_shape(), mk_id(), mk_isz_cval(), mk_set_type_call(), mk_stmt(), mk_unop(), mkexpr(), mkident(), mklvalue(), mkvarref(), mod_add_subprogram(), SEM::mod_cnt, SEM::mod_dllexport, mod_end_subprogram(), mod_end_subprogram_two(), mod_implicit(), SEM::mod_sym, mod_type(), subp_prefix_t::module, SEM::module_procedure, SEM::mpaccatomic, mscall, STB::n_base, SCN::name, name, name_of_rutype(), ndim, NEED, NEED_DOIF, negate_const(), SEM::new_param_dt, newimplicit(), newimplicitnone(), newsym(), next, xyyz::next, _acl::next, _accl::next, VAR::next, next_enum, SEM::next_unnamed_scope, SEM::nml, AUX::nml_avl, AUX::nml_base, NML_LINENO, NML_NEXT, AUX::nml_size, NML_SPTR, nomixedstrlen, SEM::none_implicit, SYMUTL::none_implicit, NOSYM, NULL, offset, SEM::ogdtype, FLG::omptarget, OP_CAT, OP_LAND, OP_LEQV, OP_LNEQV, OP_LNOT, OP_LOR, OP_ST, OP_SUB, OP_XTOI, open_module(), _accl::oper, INTERF::operator, FLG::opt, INTERF::opval, STB::ovclass, p, SEM::p_dealloc_delete, par_pop_scope(), SEM::param_assume_sz, SEM::param_defer_len, SEM::param_offset, SEM::param_struct_constr, parent, SEM::parsing_operator, parstuff_init(), SEM::pending, SEM::pgphase, PHASE_CONTAIN, PHASE_END, PHASE_END_MODULE, PHASE_EXEC, PHASE_HEADER, PHASE_IMPLICIT, PHASE_IMPORT, PHASE_INIT, PHASE_SPEC, PHASE_USE, pop_scope_level(), pop_subprogram(), pop_sym(), proc_arginfo(), SEM::proc_initializer, process_bind(), subp_prefix_t::pure, push_scope_level(), put_default_kind_type_param(), put_getitem_p(), put_length_type_param(), queue_tbp(), queue_type_param(), record_func_result(), subp_prefix_t::recursive, ref_ident(), ref_ident_inscope(), refsym(), refsym_inscope(), reinit_sym(), reloc_byvalue_parameters(), _acl::repeatc, resolve_sym_aliases(), restore_host(), restore_host_state(), restore_internal_subprograms(), restored, rewrite_acl(), RFCNTI, RHS, RU_BDATA, RU_FUNC, RU_PROG, RU_SUBR, RUNTIMEG, INTERF::rutype, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_KEYWORD, S_LVALUE, S_NULL, S_SCONST, S_STAR, S_TRIPLE, SEM::savall, save_acl(), SEM::save_aconst, save_host(), save_host_state(), save_struct_init(), save_typedef_init(), SEM::savloc, scan_include(), scan_options(), SCFTN_FALSE, SCFTN_TRUE, scn, SCOPE_BLOCK, SCOPE_INTERFACE, SEM::scope_level, SCOPE_MODULE, SCOPE_NORMAL, SEM::scope_stack, SCOPE_SUBPROGRAM, SEM::seen, SEM::seen_end_module, seen_implicit, SEM::seen_import, seen_options, seen_parameter, select_gsame(), select_kind(), SEM::select_type_seen, sem, sem_import_sym(), sem_strcmp(), semfin(), semfin_free_memory(), SEM::seq_acc_do, set_aclen(), set_char_attributes(), set_construct_name(), set_descriptor_rank(), set_descriptor_sc(), set_len_attributes(), set_preserve_descriptor(), set_proc_ptr_param_count_dtype(), set_proc_ptr_result_dtype(), set_proc_result_dtype(), setfile(), setimplicit(), setup_procedure_sym(), size_of(), size_of_array(), FLG::smp, sptr, xyyz::sptr, _acl::sptr, STSK::sptr, _accl::sptr, SCOPESTACK::sptr, SPTR_NULL, ss, SEM::ssa_area, SST_ACLG, SST_ACLP, SST_ALIASP, SST_ASTG, SST_ASTP, SST_BEGG, SST_BEGP, SST_CLBEGG, SST_CLBEGP, SST_CLENDG, SST_CLENDP, SST_COLUMNG, SST_CVALG, SST_CVALP, SST_DTYPEG, SST_DTYPEP, SST_E1G, SST_E1P, SST_E2G, SST_E2P, SST_E3G, SST_E3P, SST_ENDG, SST_ENDP, SST_ERRSYMP, SST_FIRSTG, SST_FIRSTP, SST_FLAGG, SST_FLAGP, SST_GDTYPEG, SST_GDTYPEP, SST_GTYG, SST_GTYP, SST_IDG, SST_IDP, SST_LINENOG, SST_LSYMG, SST_LSYMP, SST_NMLBEGG, SST_NMLBEGP, SST_NMLENDG, SST_NMLENDP, SST_OFFSETG, SST_OFFSETP, SST_OPTYPEG, SST_OPTYPEP, SST_PARENP, SST_RNG1G, SST_RNG2G, SST_RNG2P, SST_SHAPEP, SST_SUBSCRIPTG, SST_SUBSCRIPTP, SST_SUBSTRINGG, SST_SUBSTRINGP, SST_SYMG, SST_SYMP, SST_TMPG, SST_TMPP, SST_VLBEGG, SST_VLBEGP, SST_VLENDG, SST_VLENDP, ST_ISVAR, SEM::stag_dtype, FLG::standard, stb, std, STD_AST, STD_LABEL, STD_PREV, VAR::step, xyyz::stkp, SCN::stmtyp, string_length(), strlen(), stsk, SEM::stsk_base, SEM::stsk_depth, STSK_ENT, SEM::stsk_size, _acl::subc, SEM::submod_sym, subp_prefix, sym_in_scope(), sym_is_refd(), sym_of_ast(), symatterr(), SCOPESTACK::symavl, SYMI_NEXT, SYMI_SPTR, SYMNAME, symutl, xyyz::t, SEM::tbp_access_stmt, TBP_ADD_FINAL, TBP_ADD_IMPL, TBP_ADD_INTERFACE, TBP_ADD_SIMPLE, TBP_ADD_TO_DTYPE, SEM::tbp_arg, SEM::tbp_arg_cnt, TBP_CHECK_CHILD, TBP_CHECK_PRIVATE, TBP_CHECK_PUBLIC, TBP_CLEAR, TBP_COMPLETE_END, TBP_COMPLETE_ENDMODULE, TBP_COMPLETE_ENDTYPE, TBP_DEFERRED, TBP_IFACE, TBP_INHERIT, SEM::tbp_interface, TBP_NONOVERRIDABLE, TBP_NOPASS, TBP_PASS, TBP_PRIVATE, TBP_PUBLIC, TBP_STATUS, SEM::temps_reset, test_scope(), SEM::tkntyp, top, TRUE, TY_BINT, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, type, STSK::type, _accl::type, SEM::type_mode, SEM::type_param_candidate, SEM::type_param_sptr, VAR::u, _acl::u1, ub, uf, VAR::upbd, use_opt_atomic(), SEM::use_seen, STB::user, val, VAR::varref, void(), SEM::which_pass, XBIT, FLG::xref, and xrefput().
Referenced by _parser(), and parser().
semant_init()
void semant_init (int noparse)
Initialize semantic analyzer for new user subprogram unit.
Definition at line 427 of file semant.c.
References SEM::ac_std_range, SEM::accassignc, SEM::accl, SEM::action_type, SEM::alloc_mem_initialize, SEM::alloc_std, SEM::allocs, AOP_UNDEF, SEM::apply, SEM::array_const_level, SEM::ast, ast_init(), SEM::atemps, SEM::atomic, ATOMIC_UNDEF, SEM::auto_dealloc, SEM::auto_finalize, SEM::autoloc, bblock_init(), SEM::blksymnum, SEM::block_scope, change_predefineds(), clean_struct_default_init(), clear_subp_prefix_settings(), SEM::close_pdo, SEM::cnt, SEM::collapse, SEM::collapse_depth, SEM::collapsed_acc_do, SEM::contiguous, craft_intrinsics, cref, SEM::critical, STB::curr_scope, FLG::dclchk, SEM::defined_io_seen, SEM::defined_io_type, DI_ID, DI_LINENO, DI_NEST, SEM::dinit_data, SEM::dinit_error, SEM::dinit_nbr_inits, SEM::doconcurrent_dtype, SEM::doconcurrent_symavl, SEM::doif_base, SEM::doif_depth, SEM::doif_size, SEM::dtemps, SEM::elp_stack, end_of_host, SEM::equal_initializer, SEM::eqv_avail, SEM::eqv_base, EQV_NUMSS, SEM::eqv_size, SEM::eqv_ss_avail, SEM::eqv_ss_base, SEM::eqv_ss_size, SEM::eqvlist, SEM::etmp_list, SEM::expect_acc_do, SEM::expect_cuf_do, SEM::expect_dist_do, SEM::expect_do, SEM::expect_simd_do, SEM::extends, FALSE, SEM::flabels, flg, gbl, SEM::gdtype, SEM::generic_tbp, host_present, FLG::hpf, SEM::hpfdcl, SEM::ieee_features, SEM::iface_avail, SEM::iface_base, SEM::iface_size, SEM::ignore_default_none, SEM::ignore_stmt, import_init(), SEM::in_enum, IN_MODULE, SEM::in_stfunc, SEM::in_struct_constr, init_intrinsic_opr(), SEM::intent_list, SEM::interf_base, SEM::interf_size, SEM::interface, SEM::is_acc, SEM::is_hpf, SEM::itemps, SEM::kind_candidate, SEM::kind_type_param, SEM::len_candidate, SEM::len_type_param, lenspec, SEM::master, SEM::mem_order, MO_UNDEF, mod_init(), SEM::modhost_entry, SEM::modhost_proc, SEM::mpaccatomic, mscall, NEW, SEM::new_param_dt, _seql::next, _accl::next, SEM::nml, SEM::nodes, nomixedstrlen, SEM::non_private_avail, SEM::non_private_base, SEM::non_private_size, SEM::none_implicit, SYMUTL::none_implicit, NOSYM, NULL, SEM::orph, SEM::p_dealloc, SEM::p_dealloc_delete, SEM::parallel, SEM::param_assume_sz, SEM::param_defer_len, SEM::param_offset, SEM::param_struct_constr, SEM::parsing_operator, SEM::pending, SEM::pgphase, PHASE_INIT, SEM::proc_initializer, SEM::psfunc, SEM::ptemps, restore_host_state(), restore_implicit(), SEM::rmw_op, SEM::savall, FLG::save, SEM::save_aconst, save_implicit(), SEM::savloc, SEM::sc, scopestack_init(), SEM::seen, SEM::seen_end_module, seen_implicit, SEM::seen_import, seen_options, seen_parameter, SEM::select_type_seen, sem, SEM::seq_acc_do, SEM::seql, FLG::sequence, SPTR_NULL, SEM::ssa_area, SEM::stats, stb, SEM::stsk_base, SEM::stsk_depth, SEM::stsk_size, subp_prefix, SEM::switch_avl, switch_base, SEM::switch_size, SEM::symmetric, symutl, SEM::target, SEM::task, SEM::tbp_access_stmt, SEM::tbp_arg, SEM::tbp_arg_cnt, SEM::teams, SEM::temps_reset, TRUE, _seql::type, _accl::type, SEM::type_initialize, SEM::type_mode, SEM::type_param_candidate, SEM::type_param_sptr, SEM::typroc_avail, SEM::typroc_base, SEM::typroc_size, SEM::use_etmps, use_init(), SEM::use_seen, SEM::which_pass, WINNT_CALL, WINNT_CREF, WINNT_NOMIXEDSTRLEN, and XBIT.
Referenced by reinit().
set_aclen()
static void set_aclen (SST * stkptr, int ivl, int flag) static
Definition at line 12727 of file semant.c.
References lenspec, and set_len_attributes().
Referenced by semant1().
set_char_attributes()
static void set_char_attributes (int sptr, int * pdtype) static
Definition at line 12712 of file semant.c.
References _LEN_ADJ, _LEN_ASSUM, DTY, kind, lenspec, pdtype, sptr, TY_CHAR, and TY_NCHAR.
Referenced by semant1().
set_len_attributes()
static void set_len_attributes (SST * stkptr, int lvl) static
Definition at line 12661 of file semant.c.
References _LEN_ADJ, _LEN_ASSUM, _LEN_CONST, _LEN_DEFER, _LEN_ZERO, kind, len, lenspec, SST_ASTG, SST_IDG, and SST_SYMG.
Referenced by semant1(), and set_aclen().
set_string_type_from_init()
static void set_string_type_from_init (int sptr, ACL * init_acl) static
Definition at line 13249 of file semant.c.
References DTY, _acl::dtype, get_type(), and sptr.
Referenced by fixup_param_vars().
setup_procedure_sym()
static int setup_procedure_sym (int sptr, int proc_interf_sptr, int attr, char access) static
Process procedure declaration.
Modify symbol table entry for a procedure declaration, producing the right datatype for procedure pointers or members.
Parameters
sptr symbol table index for the symbol
proc_interf_sptr symbol table entry for procedure interface
attr attributes (bit vector), same as entity_attr.exist
access access level, same as entity_attr.access
Returns
index of produced symbol table entry, 0 if error
Definition at line 16608 of file semant.c.
References access, SEM::accl, defer_iface(), DTY, error(), ET_B, ET_BIND, ET_INTENT, ET_OPTIONAL, ET_POINTER, ET_PROTECTED, ET_SAVE, gbl, SEM::gdtype, get_procedure_stype(), get_type(), link_members(), process_bind(), scn, sem, sptr, SCN::stmtyp, stsk, STSK_ENT, SYMNAME, TRUE, and _accl::type.
Referenced by semant1().
symatterr()
static void symatterr (int sev, int sptr, const char * att) static
Definition at line 13565 of file semant.c.
References buf, error(), gbl, sptr, and SYMNAME.
Referenced by semant1().
wrong_name()
static LOGICAL wrong_name (SPTR endname) static
Definition at line 12885 of file semant.c.
References FALSE, gbl, STB::n_base, stb, SYMNAME, and uname.
Referenced by check_end_subprogram().
Variable Documentation
access
char access
Definition at line 228 of file semant.c.
Referenced by __io_tempnam(), ENT3F(), fndpath(), pg_makenewdir(), pg_makenewfile(), pg_newfile(), and setup_procedure_sym().
arrdim
char arrdim[sizeof(sem.arrdim)]
Definition at line 231 of file semant.c.
bind_attr
struct dec_attr_t bind_attr static
Definition at line 394 of file semant.c.
Referenced by process_bind(), and semant1().
bounds
char bounds[sizeof(sem.bounds)]
Definition at line 230 of file semant.c.
Referenced by lower_stmt().
craft_intrinsics
LOGICAL craft_intrinsics static
Definition at line 119 of file semant.c.
Referenced by semant_init().
cref
int cref static
Definition at line 151 of file semant.c.
Referenced by getCref(), read_symbol(), semant1(), and semant_init().
struct { ... } da[DA_MAX]
Initial value:
= {
    {"alias", 0},
    {"c", (DA_B(DA_STDCALL))},
    {"stdcall", (DA_B(DA_C))},
    {"dllexport", (0)},
    {"dllimport", (0)},
    {"value", (DA_B(DA_REFERENCE))},
    {"reference", (DA_B(DA_VALUE))},
    {"decorate", 0},
    {"nomixed_str_len_arg", 0},
}
Referenced by semant1().
dec_attr
struct dec_attr_t dec_attr static
Definition at line 393 of file semant.c.
Referenced by semant1().
dimension
int dimension
Definition at line 227 of file semant.c.
Referenced by extent().
dirty_ident_base
LOGICAL dirty_ident_base = FALSE static
Definition at line 114 of file semant.c.
Referenced by clear_ident_list(), decr_ident_use(), defer_ident_list(), and internal_proc_has_ident().
end_of_host
int end_of_host static
Definition at line 171 of file semant.c.
Referenced by check_end_subprogram(), semant1(), and semant_init().
struct { ... } entity_attr
Referenced by decl_procedure_sym(), do_fixup_param_vars_for_derived_arrays(), get_entity_access(), in_intrinsic_decl(), is_parameter_context(), and semant1().
entry_seen
LOGICAL entry_seen static
Definition at line 122 of file semant.c.
Referenced by semant1().
struct { ... } et[ET_MAX]
Referenced by gen_llvm_expr(), and semant1().
exist
int exist
Definition at line 226 of file semant.c.
Referenced by __INT_T(), ENTCRF90IO(), ENTF90IO(), and inquire().
host_present
int host_present static
Definition at line 169 of file semant.c.
Referenced by semant1(), and semant_init().
host_state
INTERF host_state static
Definition at line 170 of file semant.c.
Referenced by check_end_subprogram(), and semant1().
ident_base
IDENT_LIST* ident_base[HASHSIZE] static
Definition at line 113 of file semant.c.
Referenced by clear_ident_list(), decr_ident_use(), defer_ident_list(), and internal_proc_has_ident().
ident_host_sub
int ident_host_sub = 0 static
Definition at line 89 of file semant.c.
Referenced by semant1().
iface_avail
int iface_avail static
Definition at line 110 of file semant.c.
Referenced by _do_iface(), clear_iface(), defer_iface(), do_iface(), do_iface_module(), fix_iface(), and fix_iface0().
iface_base
IFACE* iface_base static
Definition at line 109 of file semant.c.
Referenced by _do_iface(), clear_iface(), defer_iface(), do_iface_module(), fix_iface(), and fix_iface0().
iface_size
int iface_size static
Definition at line 111 of file semant.c.
Referenced by defer_iface().
in_entity_typdcl
LOGICAL in_entity_typdcl static
Definition at line 224 of file semant.c.
Referenced by semant1().
intent
char intent
Definition at line 229 of file semant.c.
Referenced by __fort_copy_out(), __fort_show_flags(), bld_ud(), ENTFTN(), mk_hpfiofunc(), mk_iofunc(), and putintent().
is_entry
LOGICAL is_entry static
Definition at line 120 of file semant.c.
Referenced by semant1().
is_exe_stmt
LOGICAL is_exe_stmt static
Definition at line 121 of file semant.c.
Referenced by semant1().
kind
int kind
Definition at line 125 of file semant.c.
Referenced by semant1(), set_char_attributes(), and set_len_attributes().
len
INT len
Definition at line 126 of file semant.c.
Referenced by _do_iface(), defer_iface(), fix_iface(), fix_proc_ptr_dummy_args(), semant1(), and set_len_attributes().
struct { ... } lenspec[2]
Referenced by semant1(), semant_init(), set_aclen(), set_char_attributes(), and set_len_attributes().
mscall
int mscall static
Definition at line 150 of file semant.c.
Referenced by getMscall(), read_symbol(), semant1(), and semant_init().
name
const char* name
Definition at line 236 of file semant.c.
Referenced by __fortio_open(), __INT_T(), _do_iface(), _doincl(), _dumpilmtree(), _printili(), acc_display_macros(), ad1func_cmplx(), ad1func_cmplx_abi(), ad2func_cmplx(), ad2func_cmplx_abi(), ad2func_int(), ad2func_kint(), addfield(), addFinalSubroutine(), addnewsym(), addTbpInterface(), apply_use(), assemble_end(), assn_sclrtemp(), begin_layout_desc(), check_doconcurrent_ast(), checkbitname(), checkname(), cleanup_unneeded_sincos_calls(), convert_2dollar_signs_to_hyphen(), create_static_name(), dbg_dump(), decl_private_sym(), defer_put_kind_type_param(), delete(), dinit_name(), dlookup(), dmp_rat(), do_CG_line(), do_IL_line(), double_backslash(), dump_cand(), dump_dinit_chain(), emit_sum_scatterx(), enqueueTbp(), ENTCRF90IO(), ENTF90(), ENTF90IO(), f90_function(), f90_value_function(), f90_value_function_I2(), find_argasym(), find_best_generic(), find_entry(), find_modname_in_list(), find_next_modname_in_list(), find_use_node_in_list(), fix_iface(), fix_iface0(), fixup_nme(), flushsym(), follow_sptr_hashlk(), fpp_display_macros(), func_call2(), gen_llvm_expr(), generate_struct_dtype(), get_altname(), get_entries_argnum(), get_fmt_array(), get_ftn_cbind_lltype(), get_ftn_cmblk_lltype(), get_ftn_static_lltype(), get_ftn_typedesc_lltype(), get_intrinsic(), get_intrinsic_call_ops(), get_intrinsic_oprsym(), get_iso_c_entry(), get_iso_fortran_entry(), get_iso_ptrtype(), get_llvm_name(), get_local_overlap_size(), get_main_progname(), get_mem_sptr_by_name(), get_metadata_name(), get_private_size(), get_semaphore(), get_stack_size(), get_string_constant(), get_tbp(), get_tbp_argno(), getccssym(), getccssym_sc(), getccsym(), getccsym_copy(), getccsym_sc(), getcctemp_sc(), getextfuncname(), getname(), getnewccsym(), getnewccsym2(), getoperation(), getsname(), getsym(), getsymbol(), has_final_procedures(), import_mk_newsym(), imported_directly(), inheritTbps(), installsym_ex(), intrin_name(), intrin_name_bsik(), is_intrinsic_opr(), lcpu_temp(), ll_create_device_function_from_type(), ll_create_function(), ll_create_function_from_type(), ll_create_local_name(), ll_extend_named_md_node(), ll_get_const_addrspacecast(), ll_get_const_bitcast(), ll_get_const_gep(), ll_get_global_pointer(), ll_get_gtid_addr_ili(), ll_get_gtid_val_ili(), ll_get_outlined_funcname(), ll_get_string_buf(), ll_make_ftn_outlined_params(), ll_make_kmpc_struct_type(), ll_make_uplevel_type(), ll_set_named_md_node(), ll_write_local_objects(), lldbg_create_aggregate_type_mdnode(), lldbg_create_assumed_len_string_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_common_block_mdnode(), lldbg_create_deferred_len_string_type_mdnode(), lldbg_create_global_variable_mdnode(), lldbg_create_local_variable_mdnode(), lldbg_create_member_mdnode(), lldbg_create_module_flag_mdnode(), lldbg_create_module_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_create_string_type_mdnode(), lldbg_create_structure_type_mdnode(), lldbg_create_union_type_mdnode(), lldbg_function_end(), llGetSym(), llMakeFtnOutlinedSignature(), llvm_add_to_init_list(), llvm_ctor_add(), llvm_ctor_add_with_priority(), llvm_dtor_add(), llvm_dtor_add_with_priority(), local_sname(), locset_to_tbaa_info(), lookup(), lookup_ili(), lookupsym(), lookupsymbol(), lower_add_func_call(), lower_cmptrvar(), lower_makefunc(), lower_newfunc(), lower_newsymbol(), lower_symbol(), macro_recur_check(), main(), make_def(), make_keyword_str(), make_structkwd_str(), make_uplevel_arg_struct(), mangle_name(), mangle_name_dt(), matmul(), mk_external_var(), mk_prototype(), mk_prototype_llvm(), mk_struct_for_llvm_init(), mod_combined_index(), mod_combined_name(), mth_i_override(), ncpus_temp(), newintrinsic(), next_assumed_len_character_name(), open_module(), pop_sym(), pr_line(), process_cmnblk_data(), process_extern_function_sptr(), process_extern_variable_sptr(), process_label_sptr_c(), process_local_sptr(), process_string(), propagate_byval_visit(), push_sym(), put_addr(), put_call(), put_l_to_u(), put_ll_table_addr(), put_name(), put_u_to_l(), putili(), putsname(), putsymlk(), qscmp(), queue_type_param(), read_ilm(), read_symbol(), ref_entry(), ref_pd(), report_too_long_identifier(), resolve_generic(), resolveGeneric(), resolveTbps(), ILMTPApp::run(), save_contained_name(), semant1(), semant2(), semant3(), set_construct_name(), set_global_sname(), set_local_sname(), set_numbered_global_sname(), stb_upper_init(), stg_alloc(), stg_alloc_base(), stg_alloc_sidecar(), strstore(), subr_call2(), upcase_name(), update_external_function_declarations(), upper_init(), upper_to_lower(), vmk_prototype(), write_ast(), write_comm(), write_module_as_subroutine(), write_typedescs(), and write_vft().
next_enum
int next_enum static
Definition at line 153 of file semant.c.
Referenced by semant1().
no
int no
Definition at line 237 of file semant.c.
Referenced by __fort_reverse_array(), __fort_use_allocation(), emit_copy_section(), emit_permute_section(), put_data(), and same_forall_bnds().
nomixedstrlen
int nomixedstrlen static
Definition at line 152 of file semant.c.
Referenced by read_symbol(), semant1(), and semant_init().
pass_arg
int pass_arg
Definition at line 232 of file semant.c.
Referenced by get_generic_member2().
propagated
int propagated
Definition at line 127 of file semant.c.
Referenced by mod_type().
restored
int restored = 0 static
Definition at line 775 of file semant.c.
Referenced by semant1().
seen_implicit
LOGICAL seen_implicit static
Definition at line 117 of file semant.c.
Referenced by pop_subprogram(), restore_host(), save_host(), semant1(), and semant_init().
seen_options
LOGICAL seen_options static
Definition at line 123 of file semant.c.
Referenced by semant1(), and semant_init().
seen_parameter
LOGICAL seen_parameter static
Definition at line 118 of file semant.c.
Referenced by pop_subprogram(), restore_host(), save_host(), semant1(), and semant_init().
stsk
STSK* stsk static
Definition at line 116 of file semant.c.
Referenced by build_typedef_init_tree(), chk_kind_parm(), defer_iface(), gen_dinit(), link_members(), link_parents(), save_typedef_init(), search_kind(), semant1(), and setup_procedure_sym().
subp_prefix
struct subp_prefix_t subp_prefix static
Referenced by check_module_prefix(), semant1(), and semant_init().