flang: semant3.c File Reference
semant3.c File Reference
This file contains part 3 of the compiler's semantic actions (also known as the semant3 phase).
#include "gbldefs.h"
#include "gramsm.h"
#include "gramtk.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "semant.h"
#include "scan.h"
#include "semstk.h"
#include "ast.h"
#include "dinit.h"
#include "pragma.h"
#include "fdirect.h"
#include "rte.h"
#include "hpfutl.h"
#include "lower.h"
#include "rtlRtns.h"
#include "pd.h"
Macros
#define IN_OPENMP_ATOMIC (sem.mpaccatomic.ast && !(sem.mpaccatomic.is_acc))
Enumerations
enum { DC_HEADER = 1 , DC_MASK , DC_BODY }
Functions
static void check_do_term ()
static int gen_logical_if_expr (SST *)
static int dealloc_tmp (int)
static void chk_and_rewrite_cmplxpart_assn (SST *rhs, SST *lhs)
static LOGICAL init_exprs_idx_dependent (int, int)
static int gen_derived_arr_init (int arr_dtype, int strt_std, int end_std)
static int convert_to_block_forall (int old_forall_ast)
static int find_non_tbp (char *)
static int construct_association (int lhs_sptr, SST *rhs, int stmt_dtype, LOGICAL is_class)
static void end_association (int sptr)
static int get_sst_named_whole_variable (SST *rhs)
static int get_derived_type (SST *, LOGICAL)
void semant3 (int rednum, SST *top)
semantic actions - part 3.
void set_construct_name (int name)
int get_construct_name (void)
static LOGICAL check_doconcurrent_ast (int ast, int *doif)
Check a DO CONCURRENT loop ast for constraint violations.
void check_doconcurrent (int doif)
Check a DO CONCURRENT loop for constraint violations.
int has_poly_mbr (int sptr, int flag)
Return TRUE if derived type has a polymorphic member.
void push_tbp_arg (ITEM *item)
ITEM * pop_tbp_arg (void)
void err307 (const char *msg, int diname, int namedc)
static SST * gen_fcn_sst (const char *nm, int dtype)
static SST * rewrite_cmplxpart_rhs (const char *i_cmplxnm, SST *realpart, SST *imagpart, int dtype)
static SST * gen_cmplxpart_intr (const char *i_partnm, SST *part, int dtype)
static LOGICAL rhs_expr_idx_dependent (int ast, int *id_dep)
static int new_member_expr (int new_parent, int mem)
void gen_init_unl_poly_desc (int dest_sdsc_ast, int src_sdsc_ast, int std)
Generate a call to init_unl_poly_desc which initializes a descriptor for an unlimited polymorphic object with another descriptor.
static LOGICAL is_associatable_variable_ast (int ast)
static LOGICAL is_associatable_variable_sst (SST *rhs)
Variables
static LOGICAL alloc_error = FALSE
static int alloc_source
static int orig_alloc_source
static int typed_alloc
static int do_label
static int construct_name
static int last_std
Detailed Description
This file contains part 3 of the compiler's semantic actions (also known as the semant3 phase).
Definition in file semant3.c.
Macro Definition Documentation
IN_OPENMP_ATOMIC
#define IN_OPENMP_ATOMIC (sem.mpaccatomic.ast && !(sem.mpaccatomic.is_acc))
Definition at line 65 of file semant3.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DC_HEADER
DC_MASK
DC_BODY
Definition at line 5730 of file semant3.c.
Function Documentation
check_do_term()
static void check_do_term () static
Definition at line 5705 of file semant3.c.
References ast, SCN::currlab, DI_DO, DI_DO_LABEL, DI_DOCONCURRENT, DI_DOWHILE, DI_ID, SEM::doif_depth, errsev(), errwarn(), flg, scn, sem, FLG::standard, std, STD_AST, and STD_PREV.
Referenced by semant3().
check_doconcurrent()
void check_doconcurrent (int doif)
Check a DO CONCURRENT loop for constraint violations.
Parameters
doif DO CONCURRENT doif stack slot index
Definition at line 5993 of file semant3.c.
References add_symitem(), ast_traverse(), ast_unvisit(), ast_visit(), check_doconcurrent_ast(), SCN::currlab, DC_BODY, DC_HEADER, DC_MASK, DI_CONC_BODY_STD, DI_CONC_COUNT, DI_CONC_KIND, DI_CONC_LABEL_SYMS, DI_CONC_MASK_STD, DI_CYCLE_LABEL, DI_DOINFO, DI_LINENO, gbl, i, DOINFO::init_expr, DOINFO::limit_expr, NULL, scn, std, STD_AST, STD_LABEL, STD_LINENO, STD_NEXT, and DOINFO::step_expr.
Referenced by do_end().
check_doconcurrent_ast()
static LOGICAL check_doconcurrent_ast (int ast, int * doif) static
Check a DO CONCURRENT loop ast for constraint violations.
Parameters
ast ast to examine
doif address of DO CONCURRENT doif stack slot index
Definition at line 5737 of file semant3.c.
References A_ARGCNTG, A_TKNG, add_symitem(), argt, ARGT_ARG, ast, ast_is_sym(), ASTLI_AST, ASTLI_NEXT, CNULL, DC_BODY, DC_HEADER, DC_MASK, DI_CONC_COUNT, DI_CONC_ERROR_SYMS, DI_CONC_KIND, DI_CONC_LABEL_SYMS, DI_CONC_NO_DEFAULT, DI_CONC_SYMAVL, DI_CONC_SYMS, ERR_Severe, error(), FLANG_FALLTHROUGH, gbl, has_impure_finalizer(), i, is_impure(), memsym_of_ast(), mkRteRtnNm(), name, NOSYM, NULL, RTE_finalize, s, sptr, SPTR_NULL, strlen(), sym_in_sym_list(), sym_of_ast(), SYMI_NEXT, and SYMNAME.
Referenced by check_doconcurrent().
chk_and_rewrite_cmplxpart_assn()
static void chk_and_rewrite_cmplxpart_assn (SST * rhs, SST * lhs) static
Definition at line 6230 of file semant3.c.
References ast, DT_ISCMPLX, DTY, gen_cmplxpart_intr(), interr(), lhs, rewrite_cmplxpart_rhs(), S_EXPR, S_LVALUE, sptr, SST_ASTG, SST_ASTP, SST_DTYPEP, SST_IDP, SST_PARENP, SYMNAME, TY_DBLE, TY_QUAD, and TY_REAL.
Referenced by semant3().
construct_association()
static int construct_association (int lhs_sptr, SST * rhs, int stmt_dtype, LOGICAL is_class) static
Definition at line 6657 of file semant3.c.
References A_TKNP, ADD_DEFER, ADD_NOBOUNDS, add_ptr_assign(), add_shapely_subscripts(), add_stmt(), array_element_dtype(), assert, astb, ASTB::bnd, change_assumed_char_to_deferred(), STB::curr_scope, DDTG, DT_INT, DTY, ASTB::dtype, dtype_to_arg(), FALSE, find_descriptor_ast(), gen_init_unl_poly_desc(), get_all_descriptors(), get_array_dtype(), get_ast_rank(), get_ast_sptr(), get_kind(), get_static_descriptor(), get_value_length_ast(), has_tbp(), insert_sym_first(), is_array_dtype(), is_associatable_variable_sst(), is_dtype_runtime_length_char(), is_unl_poly(), mk_assn_stmt(), mk_cval1(), mk_id(), mk_stmt(), mkexpr(), NOSYM, SEM::parallel, rank, sem, set_descriptor_rank(), SST_ASTG, stb, sym_of_ast(), symbol_descriptor_length_ast(), SEM::target, SEM::task, and TRUE.
Referenced by semant3().
convert_to_block_forall()
static int convert_to_block_forall (int old_forall_ast) static
Definition at line 6409 of file semant3.c.
References A_TKNG, add_stmt(), ast, astb, delete_stmt(), DI_FORALL_LASTSTD, SEM::doif_depth, gen_alloc_dealloc(), getitem(), i, ITEM_END, itemp, mk_id(), mk_stmt(), xyyz::next, SEM::p_dealloc, sem, STD_AST, STD_NEXT, and sym_of_ast().
Referenced by semant3().
dealloc_tmp()
static int dealloc_tmp (int sptr) static
Definition at line 6072 of file semant3.c.
References ast, gen_alloc_dealloc(), mk_id(), and sptr.
Referenced by semant3().
end_association()
static void end_association (int sptr) static
Definition at line 6875 of file semant3.c.
References A_TKNP, add_stmt(), ast, mk_id(), mk_stmt(), pop_sym(), and sptr.
Referenced by semant3().
err307()
void err307 (const char * msg, int diname, int namedc)
Definition at line 6162 of file semant3.c.
References error(), gbl, msg(), STB::n_base, and stb.
Referenced by semant1(), and semant3().
find_non_tbp()
static int find_non_tbp (char * symname) static
Definition at line 6116 of file semant3.c.
References HASH_ID, STB::hashtb, len, stb, strlen(), and SYMNAME.
Referenced by semant3().
gen_cmplxpart_intr()
static SST * gen_cmplxpart_intr (const char * i_partnm, SST * part, int dtype) static
Definition at line 6212 of file semant3.c.
References arg, BZERO, gen_fcn_sst(), getitem(), ITEM_END, and mkvarref().
Referenced by chk_and_rewrite_cmplxpart_assn().
gen_derived_arr_init()
static int gen_derived_arr_init (int arr_dtype, int strt_std, int end_std) static
Definition at line 6356 of file semant3.c.
References AD_DPTR, AD_NUMDIM, add_stmt_before(), assert, DDTG, delete_stmt(), DI_IDXLIST, SEM::doif_depth, FALSE, get_arr_temp(), i, MAXRANK, mk_id(), mk_subscr(), ndim, new_member_expr(), sem, sptr, std, STD_AST, STD_NEXT, subscr, SYMI_NEXT, and SYMI_SPTR.
Referenced by semant3().
gen_fcn_sst()
static SST * gen_fcn_sst (const char * nm, int dtype) static
Definition at line 6173 of file semant3.c.
References BZERO, getitem(), getsymbol(), IS_INTRINSIC, S_IDENT, setimplicit(), sptr, SST_DTYPEP, SST_IDP, and SST_SYMP.
Referenced by gen_cmplxpart_intr(), and rewrite_cmplxpart_rhs().
gen_init_unl_poly_desc()
void gen_init_unl_poly_desc (int dest_sdsc_ast, int src_sdsc_ast, int std)
Generate a call to init_unl_poly_desc which initializes a descriptor for an unlimited polymorphic object with another descriptor.
Parameters
dest_sdsc_ast is the AST of the destination's descriptor.
src_sdsc_ast is the AST of the source descriptor.
std is the statement descriptor to insert the call, or 0 to use the default statement descriptor.
Definition at line 6478 of file semant3.c.
References add_stmt(), add_stmt_after(), argt, ARGT_ARG, ast, DT_INT, mk_argt(), mk_cval1(), mk_func_node(), mk_id(), mk_unop(), mkRteRtnNm(), OP_VAL, RTE_init_unl_poly_desc, std, sym_mkfunc_nodesc(), and val.
Referenced by construct_association(), rewrite_allocatable_assignment(), and semant3().
gen_logical_if_expr()
static int gen_logical_if_expr (SST * stkp) static
Definition at line 6056 of file semant3.c.
References ast, check_etmp(), chk_scalartyp(), DT_LOG, FALSE, mkexpr1(), SST_DTYPEG, and void().
Referenced by semant3().
get_construct_name()
int get_construct_name (void)
Definition at line 5688 of file semant3.c.
References construct_name.
Referenced by semant1().
get_derived_type()
static int get_derived_type (SST * sst, LOGICAL abstract_type_not_allowed) static
Definition at line 6914 of file semant3.c.
References DTY, error(), gbl, NOSYM, NULL, refsym(), scn, sptr, SST_SYMG, SCN::stmtyp, and SYMNAME.
Referenced by semant3().
get_sst_named_whole_variable()
static int get_sst_named_whole_variable (SST * rhs) static
Definition at line 6892 of file semant3.c.
References ast, NOSYM, S_EXPR, S_IDENT, S_LVALUE, sptr, SST_ASTG, SST_IDG, SST_SYMG, and test_scope().
Referenced by semant3().
has_poly_mbr()
int has_poly_mbr (int sptr, int flag)
Return TRUE if derived type has a polymorphic member.
If flag is set, then it also returns TRUE if it has a pointer or allocatable derived type member with a type descriptor embedded in the type itself.
Definition at line 6087 of file semant3.c.
References DTY, has_poly_mbr(), is_tbp_or_final(), mem(), NOSYM, and sptr.
Referenced by has_poly_mbr(), rewrite_calls(), and semant3().
init_exprs_idx_dependent()
static LOGICAL init_exprs_idx_dependent (int strt_std, int end_std) static
Definition at line 6317 of file semant3.c.
References ast, ast_traverse(), ast_unvisit(), ast_visit(), FALSE, i, NULL, rhs_expr_idx_dependent(), STD_AST, and STD_NEXT.
Referenced by semant3().
is_associatable_variable_ast()
static LOGICAL is_associatable_variable_ast (int ast) static
Definition at line 6610 of file semant3.c.
References ast, has_vector_subscript_ast(), is_data_ast(), and is_variable_ast().
Referenced by is_associatable_variable_sst().
is_associatable_variable_sst()
static LOGICAL is_associatable_variable_sst (SST * rhs) static
Definition at line 6617 of file semant3.c.
References FALSE, is_associatable_variable_ast(), is_procedure_ptr(), S_EXPR, S_IDENT, S_LVALUE, SST_ASTG, SST_IDG, and SST_SYMG.
Referenced by construct_association().
new_member_expr()
static int new_member_expr (int new_parent, int mem) static
Definition at line 6338 of file semant3.c.
References ast, mem(), mk_member(), and new_member_expr().
Referenced by gen_derived_arr_init(), and new_member_expr().
pop_tbp_arg()
ITEM * pop_tbp_arg (void)
Definition at line 6145 of file semant3.c.
References sem, SEM::tbp_arg, and SEM::tbp_arg_cnt.
Referenced by semant2(), and semant3().
push_tbp_arg()
void push_tbp_arg (ITEM * item)
Definition at line 6131 of file semant3.c.
References getitem(), i, sem, SEM::tbp_arg, and SEM::tbp_arg_cnt.
Referenced by semant2(), and semant3().
rewrite_cmplxpart_rhs()
static SST * rewrite_cmplxpart_rhs (const char * i_cmplxnm, SST * realpart, SST * imagpart, int dtype) static
Definition at line 6192 of file semant3.c.
References BZERO, gen_fcn_sst(), getitem(), ITEM_END, mkvarref(), xyyz::next, xyyz::stkp, and xyyz::t.
Referenced by chk_and_rewrite_cmplxpart_assn().
rhs_expr_idx_dependent()
static LOGICAL rhs_expr_idx_dependent (int ast, int * id_dep) static
Definition at line 6305 of file semant3.c.
References ast, DI_IDXLIST, SEM::doif_depth, FALSE, sem, sym_in_sym_list(), and TRUE.
Referenced by init_exprs_idx_dependent().
semant3()
void semant3 (int rednum, SST * top)
semantic actions - part 3.
Parameters
rednum reduction number
top top of stack after reduction
Definition at line 72 of file semant3.c.
References _char_cmp(), _i4_cmp(), _i8_cmp(), _nchar_cmp(), A_ISLVAL, A_OPTYPEG, A_OPTYPEP, SEM::accassignc, FLG::accmp, SEM::action_type, AD_DEFER, AD_DPTR, AD_NUMDIM, add_arg(), add_astli(), add_bounds_subscripts(), add_case_range(), add_no_scope_sptr(), add_nullify_ast(), ADD_NUMDIM, add_ptr_assign(), add_stmt(), add_stmt_after(), add_stmt_before(), add_symitem(), ADD_UPAST, ADD_UPBD, alloc_error, alloc_source, SEM::allocs, SEM::apply, arg, argt, ARGT_ARG, SEM::arrdim, SEM::arrfn, assert, assign(), assign_pointer(), assn(), ast, astb, ASTLI_AST, ASTLI_HEAD, ASTLI_SPTR, ASTLI_TRIPLE, SEM::atomic, ATOMIC_CAPTURE, base, BCOPY, begin_call(), SEM::blksymnum, block_local_sym(), ASTB::bnd, SEM::bounds, BZERO, check_alloc_clauses(), check_and_add_auto_dealloc_from_ast(), check_dealloc_clauses(), check_do_term(), check_etmp(), check_member(), check_no_scope_sptr(), chk_and_rewrite_cmplxpart_assn(), chk_pointer_intent(), chk_scalar_inttyp(), chk_scalartyp(), chkcon(), chkstruct(), chktyp(), SWEL::clabel, clear_no_scope_sptr(), cmp_len_parms(), cmpat_dtype(), cngtyp(), CNULL, DOINFO::collapse, SEM::collapse, collapse_add(), collapse_begin(), SEM::collapse_depth, SEM::collapsed_acc_do, construct_association(), construct_name, SEM::construct_sptr, CONVAL2G, convert_to_block_forall(), count, create_parameterized_dt(), cuda_enabled(), SCN::currlab, d, dast(), DCLCHK, DDTG, dealloc_tmp(), declref(), declsym(), define_stfunc(), dest, DI_ACTIVE_SPTR, DI_ALLO_CHTMP, DI_ASSOC, DI_ASSOCIATIONS, DI_BEG_DEFAULT, DI_BTARGET, DI_CASE, DI_CASE_EXPR, DI_CLASS_DEFAULT_LABEL, DI_CONC_BLOCK_SYM, DI_CONC_BODY_STD, DI_CONC_COUNT, DI_CONC_ERROR_SYMS, DI_CONC_KIND, DI_CONC_LAST_SYM, DI_CONC_MASK_STD, DI_CONC_NO_DEFAULT, DI_CONC_SYMAVL, DI_CONC_SYMS, DI_CYCLE_LABEL, DI_DEFAULT_COMPLETE, DI_DEFAULT_SEEN, DI_DISTPARDO, DI_DISTRIBUTE, DI_DO, DI_DO_AST, DI_DO_LABEL, DI_DO_POPINDEX, DI_DOCONCURRENT, DI_DOINFO, DI_DOWHILE, DI_DTYPE, DI_ELSEWHERE, DI_END_DEFAULT, DI_END_SELECT_LABEL, DI_EXIT_LABEL, DI_FORALL, DI_FORALL_AST, DI_FORALL_DTYPE, DI_FORALL_LASTSTD, DI_FORALL_SYMAVL, DI_ID, DI_IDXLIST, DI_IF, DI_IFELSE, DI_IN_NEST, DI_IS_WHOLE, DI_LINENO, DI_MASKED, DI_NAME, DI_NOSCOPE_FORALL, DI_PARDO, DI_PDO, DI_PENDING, DI_SELECT_TYPE, DI_SELECT_TYPE_LIST, DI_SELECTOR, DI_SHAPEDIM, DI_SIMD, DI_SWEL_HD, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TASKLOOP, DI_TEAMSDIST, DI_TEAMSDISTPARDO, DI_TOP_LABEL, DI_TYPE_BEG, DI_WHERE, direct_loop_end(), direct_loop_enter(), DOINFO::distloop, do_begin(), do_distbegin(), do_end(), do_label, do_lastval(), do_openmp_atomics(), do_parbegin(), SEM::doconcurrent_dtype, SEM::doconcurrent_symavl, SEM::doif_base, SEM::doif_depth, dt, DT_INT, DT_ISINT, DT_ISLOG, DT_ISREAL, DT_ISWORD, STB::dt_log, DT_LOG, DT_PTR, SEM::dtemps, DTY, DTYG, type_list::dtype, ASTB::dtype, dtype_to_arg(), dup_array_dtype(), end_association(), eq_dtype(), eq_dtype2(), err307(), err_protected(), ERR_Severe, ERR_Warning, error(), errsev(), errwarn(), SEM::expect_acc_do, SEM::expect_cuf_do, SEM::expect_dist_do, SEM::expect_do, SEM::expect_simd_do, FALSE, find_non_tbp(), find_pointer_variable(), SEM::flabels, FLANG_FALLTHROUGH, flg, FREE, func, FUNCLINEP, gbl, SEM::gcvlen, SEM::gdtype, gen_alloc_dealloc(), gen_dealloc_etmps(), gen_deallocate_arrays(), gen_defer_shape(), gen_derived_arr_init(), gen_derived_type_alloc_init(), gen_finalization_for_sym(), gen_init_unl_poly_desc(), gen_logical_if_expr(), gen_type_initialize_for_sym(), generic_tbp_has_pass_and_nopass(), get_all_descriptors(), get_ast_bounds(), get_byte_len(), get_derived_type(), get_desc_gsize(), get_desc_lsize(), get_desc_rank(), get_desc_tag(), get_doinfo(), get_generic_member2(), get_generic_tbp_pass_or_nopass(), get_implementation(), get_int_cval(), get_kind(), get_member_descriptor(), get_parm_by_name(), get_parm_by_number(), get_specific_member(), get_sst_named_whole_variable(), get_static_descriptor(), get_static_type_descriptor(), get_tbp_argno(), get_type_descr_arg(), get_type_descr_arg2(), get_unl_poly_sym(), getccsym(), getcctmp_sc(), getitem(), getlab(), getstring(), getsymbol(), getsymf(), has_finalized_component(), has_poly_mbr(), has_type_parameter(), i, ASTB::i0, ASTB::i1, SCN::id, IN_OPENMP_ATOMIC, SEM::in_stfunc, SEM::index_sym_to_pop, DOINFO::index_var, init_derived_w_acl(), DOINFO::init_expr, init_exprs_idx_dependent(), insert_dup_sym(), insert_sym(), intast_sym, INTENT_IN, INTENTG, INTENTP, interr(), SEM::is_acc, is_array_dtype(), type_list::is_class, is_dovar_sptr(), IS_INTRINSIC, is_intrinsic_opr(), is_iso_cloc(), is_iso_cptr(), is_procedure_ptr(), is_protected(), IS_TBP, is_unl_poly(), is_varref(), ITEM_END, itemp, j, ASTB::k0, ASTB::k1, label, type_list::label, SEM::last_std, last_std, legal_labelvar(), LHS, lhs, DOINFO::limit_expr, LP_DISTPARDO, LP_PARDO_OTHER, MAXIDLEN, MAXRANK, mem(), memsym_of_ast(), mk_argt(), mk_assign_sptr(), mk_assn_stmt(), mk_binop(), mk_cnst(), mk_cval(), mk_cval1(), mk_func_node(), mk_id(), mk_label(), mk_set_type_call(), mk_stmt(), mk_triple(), mk_unop(), mkarg(), mkexpr(), mkexpr1(), mkident(), mklabelvar(), mklvalue(), mkmember(), mkRteRtnNm(), mkvarref(), SEM::mpaccatomic, msg(), STB::n_base, SCN::name, name, NEED, NEED_DOIF, needs_descriptor(), NEW, SEM::new_param_dt, newsym(), type_list::next, xyyz::next, SWEL::next, SEM::nodes, NOSYM, not_in_forall(), NULL, offset, ASTB::one, OP_EQ, OP_GE, OP_LAND, OP_LE, OP_LEQV, OP_LOC, OP_LOR, OP_REF, OP_ST, OP_VAL, orig_alloc_source, SEM::orph, SEM::p_dealloc, SEM::parallel, PARAMVALG, parent, pass_sym_of_ast(), SEM::pending, SEM::pgphase, PHASE_EXEC, PHASE_SPEC, pop_sym(), pop_tbp_arg(), pos, PR_ACCLOOPPRIVATE, PR_CUFLOOPPRIVATE, PR_NOSCOPE, prev, proc_arginfo(), SEM::psfunc, ASTB::ptr0c, ptrsubr_call(), push_sym(), push_tbp_arg(), put_length_type_param(), rank, rank_of_sym(), ref_based_object(), ref_entry(), refsym(), resolve_sym_aliases(), rewrite_ast_with_new_dtype(), RFCNTI, RHS, RTE_errorstop08a_char, RTE_errorstop08a_int, RTE_extends_type_of, RTE_f90io_end, RTE_init_from_desc, RTE_loc, RTE_pausea, RTE_poly_asn, RTE_poly_asn_src_intrin, RTE_same_intrin_type_as, RTE_same_type_as, RTE_stop08a, RTE_stopa, RU_FUNC, RU_SUBR, s, S_CONST, S_DERIVED, S_EXPR, S_IDENT, S_KEYWORD, S_LABEL, S_LVALUE, S_NULL, S_SCONST, S_STFUNC, S_TRIPLE, SEM::sc, SCFTN_TRUE, scn, SEM::seen, SEM::select_type_seen, sem, sem_check_scope(), sem_err105(), sem_set_storage_class(), sem_tempify(), set_assn(), set_descriptor_rank(), setimplicit(), SHD_NDIM, size_ast_of(), FLG::smp, sptr, xyyz::sptr, SPTR_NULL, src, sst, SST_ACLG, SST_ASTG, SST_ASTP, SST_BEGG, SST_BEGP, SST_COUNTG, SST_COUNTP, SST_CVALG, SST_CVALP, SST_DBEGG, SST_DBEGP, SST_DENDP, SST_DTYPEG, SST_DTYPEP, SST_E1G, SST_E1P, SST_E2G, SST_E2P, SST_E3G, SST_E3P, SST_ENDG, SST_ENDP, SST_ERRSYMG, SST_FIRSTG, SST_FIRSTP, SST_IDG, SST_IDP, SST_ISNONDECC, SST_LASTG, SST_LASTP, SST_LSYMG, SST_LSYMP, SST_MNOFFP, SST_PARENP, SST_SHAPEP, SST_SYMG, SST_SYMP, SST_TMPG, SST_TMPP, FLG::standard, start_astli(), SEM::stats, stb, std, STD_AST, STD_BLKSYM, STD_LABEL, STD_LAST, STD_NEXT, STD_PREV, DOINFO::step_expr, SEM::stfunc_error, xyyz::stkp, SCN::stmtyp, string_expr_length(), string_length(), subr_call(), subr_call2(), subscr, SEM::switch_avl, switch_base, SEM::switch_size, sym_in_sym_list(), sym_is_refd(), sym_mkfunc(), sym_mkfunc_nodesc(), sym_of_ast(), SYMI_NEXT, SYMI_SPTR, SYMNAME, t, xyyz::t, SEM::target, target_name(), SEM::task, SEM::tbp_arg, SEM::teams, test_private_dtype(), tmp, TRUE, SEM::try, TY_CHAR, TY_INT, TY_INT8, TY_ISINT, TY_ISLOG, TY_ISREAL, TY_LOG, TY_NCHAR, ty_to_lib, typed_alloc, SEM::use_etmps, use_opt_atomic(), STB::user, val, SWEL::val, validate_omp_atomic(), void(), XBIT, FLG::xref, xrefput(), and zero.
set_construct_name()
void set_construct_name (int name)
Definition at line 5682 of file semant3.c.
References construct_name, and name.
Referenced by semant1().
Variable Documentation
alloc_error
LOGICAL alloc_error = FALSE static
Definition at line 35 of file semant3.c.
Referenced by semant3().
alloc_source
int alloc_source static
Definition at line 36 of file semant3.c.
Referenced by rewrite_calls(), and semant3().
construct_name
int construct_name static
Definition at line 40 of file semant3.c.
Referenced by do_distbegin(), get_construct_name(), semant1(), semant3(), and set_construct_name().
do_label
int do_label static
Definition at line 39 of file semant3.c.
Referenced by do_distbegin(), and semant3().
last_std
int last_std static
Definition at line 41 of file semant3.c.
Referenced by bblock(), and semant3().
orig_alloc_source
int orig_alloc_source static
Definition at line 37 of file semant3.c.
Referenced by semant3().
typed_alloc
int typed_alloc static
Definition at line 38 of file semant3.c.
Referenced by semant3().