flang: semant2.c File Reference
semant2.c File Reference
This file contains part 2 of the compiler's semantic actions (also known as the semant2 phase).
#include "gbldefs.h"
#include "error.h"
#include "gramsm.h"
#include "gramtk.h"
#include "global.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "semant.h"
#include "scan.h"
#include "semstk.h"
#include "ast.h"
#include "dinit.h"
#include "rtlRtns.h"
Functions
static void common_rel (SST *top, int opc, int tkn_alias)
static void log_negation (SST *top, int tkn_alias)
static void var_ref_list (SST *top, int rhstop)
static void ssa_list (SST *top, int rhstop)
static void ast_cnst (SST *top)
static void ast_conval (SST *top)
static void string_with_kind (SST *top)
static void rewrite_cmplxpart_rval (SST *e)
static int combine_fdiv (int, int, int)
static int has_private (int)
static void form_cmplx_const (SST *, SST *, SST *)
static int reassoc_add (int, int, int)
static int get_mem_sptr_by_name (char *name, int dtype)
static ITEM * mkitem (SST *stkp)
static STD_RANGE * mk_ido_std_range (int prev, int mid, int end)
Return std range to mark the stds generated by loop body or loop control in an implied-do loop.
void semant2 (int rednum, SST *top)
semantic actions - part 2.
int test_private_dtype (int dtype)
Check whether the dtype is inside a valid scope.
static int _assoc_term (int op)
Detailed Description
This file contains part 2 of the compiler's semantic actions (also known as the semant2 phase).
Definition in file semant2.c.
Function Documentation
_assoc_term()
static int _assoc_term (int op) static
Definition at line 2917 of file semant2.c.
References A_ISLVAL, and XBIT.
Referenced by reassoc_add().
ast_cnst()
static void ast_cnst (SST * top) static
Definition at line 2697 of file semant2.c.
References LHS, mk_cnst(), SST_ASTP, SST_CVALG, and SST_SHAPEP.
Referenced by semant2(), and string_with_kind().
ast_conval()
static void ast_conval (SST * top) static
Definition at line 2704 of file semant2.c.
References LHS, mk_cval1(), SST_ACLP, SST_ASTP, SST_CVALG, SST_DTYPEG, and SST_SHAPEP.
Referenced by semant2().
combine_fdiv()
static int combine_fdiv (int l_ast, int r_ast, int dt) static
Definition at line 2721 of file semant2.c.
References A_OPTYPEG, dt, flg, mk_binop(), OP_DIV, OP_MUL, FLG::opt, r, and XBIT.
Referenced by semant2().
common_rel()
static void common_rel (SST * top, int opc, int tkn_alias) static
Definition at line 2569 of file semant2.c.
References ast, binop(), chklog(), is_intrinsic_opr(), LHS, mk_binop(), mk_cval1(), OP_LAND, OP_LOG, OP_LOR, RHS, S_CONST, SST_ASTG, SST_ASTP, SST_CVALG, SST_DTYPEG, SST_IDG, SST_OPCP, SST_OPTYPEP, SST_PARENP, and SST_SHAPEP.
Referenced by semant2().
form_cmplx_const()
static void form_cmplx_const (SST * res, SST * rp, SST * ip) static
Definition at line 2871 of file semant2.c.
References ast, cngtyp(), DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_REAL, errsev(), getcon(), i, mk_cnst(), r, res, S_CONST, SST_ASTP, SST_CVALG, SST_CVALP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_SHAPEP, and val.
Referenced by semant2().
get_mem_sptr_by_name()
static int get_mem_sptr_by_name (char * name, int dtype) static
Definition at line 2953 of file semant2.c.
References DTY, get_mem_sptr_by_name(), mem(), name, NOSYM, sptr, and SYMNAME.
Referenced by get_mem_sptr_by_name(), and semant2().
has_private()
static int has_private (int in_dtype) static
Definition at line 2737 of file semant2.c.
References DTY, DTYG, has_private(), is_iso_cptr(), is_tbp_or_final(), NOSYM, and test_private_dtype().
Referenced by has_private(), and semant2().
log_negation()
static void log_negation (SST * top, int tkn_alias) static
Definition at line 2603 of file semant2.c.
References ast, chklog(), cngtyp(), CONVAL2G, DT_LOG, gbl, getcon(), is_intrinsic_opr(), LHS, mk_cval1(), mk_unop(), NULL, OP_LNOT, RHS, S_CONST, S_EXPR, SCFTN_NEGATE, sptr, SST_ACLP, SST_ASTG, SST_ASTP, SST_CVALG, SST_CVALP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_ISNONDECC, SST_PARENP, SST_SHAPEP, and val.
Referenced by semant2().
mk_ido_std_range()
static STD_RANGE * mk_ido_std_range (int prev, int mid, int end) static
Return std range to mark the stds generated by loop body or loop control in an implied-do loop.
Parameters
prev the STD_LAST when the semantic analysis of an implied-do loop is started.
mid the STD_LAST when meeting the <idc eq>.
end the STD_LAST when the semantic analysis of an implied-do loop is finished.
Definition at line 2992 of file semant2.c.
References end, _std_range::end, getitem(), _std_range::mid, NULL, prev, _std_range::start, and STD_NEXT.
Referenced by semant2().
mkitem()
static ITEM * mkitem (SST * stkp) static
Definition at line 2975 of file semant2.c.
References getitem(), ITEM_END, xyyz::next, xyyz::stkp, and xyyz::t.
Referenced by rewrite_cmplxpart_rval(), semant2(), ssa_list(), and var_ref_list().
reassoc_add()
static int reassoc_add (int lop, int rop, int dtype) static
Definition at line 2925 of file semant2.c.
References _assoc_term(), A_OPTYPEG, ast, DDTG, DT_ISREAL, mk_binop(), OP_ADD, and XBIT.
Referenced by semant2().
rewrite_cmplxpart_rval()
static void rewrite_cmplxpart_rval (SST * e) static
Definition at line 2812 of file semant2.c.
References arg, ast, BZERO, DT_ISCMPLX, DTY, e, getitem(), getsymbol(), interr(), IS_INTRINSIC, list, mkitem(), mkvarref(), S_EXPR, S_IDENT, setimplicit(), sptr, SST_ASTG, SST_ASTP, SST_DTYPEG, SST_DTYPEP, SST_IDP, SST_PARENP, SST_SYMP, SYMNAME, TY_DBLE, TY_QUAD, and TY_REAL.
Referenced by semant2().
semant2()
void semant2 (int rednum, SST * top)
semantic actions - part 2.
Parameters
rednum reduction number
top top of stack after reduction
Definition at line 51 of file semant2.c.
References a, AC_ACONST, AC_AST, AC_EXPR, AC_IDO, AC_SCONST, SEM::ac_std_range, ACL_SAVE_AREA, ALIGNG, all_default_init(), arg, SEM::array_const_level, assert, ast, xyyz::ast, ast_cnst(), ast_conval(), ast_is_sym(), astb, binop(), block_local_sym(), SEM::block_scope, ch_substring(), check_and_add_auto_dealloc(), check_derived_type_array_section(), check_etmp(), chk_constructor(), chk_scalartyp(), chk_struct_constructor(), cngtyp(), CNULL, combine_fdiv(), common_rel(), CONVAL2G, DOINFO::count, d, DDTG, declsym(), defer_pt_decl(), defined_operator(), DISTG, SEM::doif_depth, STB::dt_int, DT_INT, DT_ISBASIC, DT_ISCMPLX, DT_ISINT, DT_ISREAL, STB::dt_log, DT_LOG, DT_PTR, DTY, DTYG, dup_struct_init(), SEM::elp_stack, ERR_Severe, error(), errsev(), errwarn(), SEM::etmp_list, FALSE, find_outer_sym(), findByNameStypeScope(), fix_term(), FLANG_FALLTHROUGH, flg, form_cmplx_const(), gbl, GBL_CURRFUNC, SEM::generic_tbp, generic_tbp_has_pass_and_nopass(), GET_ACL, get_doinfo(), get_generic_member2(), get_generic_tbp_pass_or_nopass(), get_implementation(), get_int_cval(), get_kind_parm_by_name(), get_mem_sptr_by_name(), get_next_sym(), get_parameterized_dt(), get_specific_member(), get_tbp_argno(), get_temp(), get_type(), getcon(), getitem(), getsymbol(), has_private(), has_type_parameter(), i, STB::i0, ASTB::i0, ASTB::i1, SCN::id, _acl::id, SEM::in_stfunc, SEM::in_struct_constr, DOINFO::index_var, DOINFO::init_expr, init_named_array_constant(), insert_sym(), interr(), is_dovar_sptr(), is_empty_typedef(), SCN::is_hpf, IS_INTRINSIC, is_intrinsic_opr(), is_parameter_context(), is_procedure_ptr(), IS_TBP, ITEM_END, itemp, kanji_len(), lboundMask, LHS, DOINFO::limit_expr, log_negation(), mem(), memsym_of_ast(), _std_range::mid, mk_alias(), mk_binop(), mk_convert(), mk_cval(), mk_cval1(), mk_id(), mk_ido_std_range(), mk_member(), mk_paren(), mk_unop(), mkarg(), mkexpr(), mkident(), mkitem(), mklvalue(), mkmember(), mkRteRtnNm(), mkvarref(), SEM::mod_cnt, STB::n_base, SCN::name, name, negate_const(), SEM::new_param_dt, _std_range::next, _std_record::next, xyyz::next, _acl::next, no_data_components(), NOSYM, NULL, offset, OP_ADD, OP_CAT, OP_CMP, OP_DIV, OP_EQ, OP_GE, OP_GT, OP_LAND, OP_LE, OP_LOC, OP_LOR, OP_LT, OP_MUL, OP_NE, OP_REF, OP_SUB, OP_VAL, OP_XTOI, SEM::param_struct_constr, SEM::parsing_operator, pass_sym_of_ast(), SEM::pgphase, PHASE_EXEC, pop_tbp_arg(), pp, prev, proc_arginfo(), SEM::psfunc, push_tbp_arg(), put_kind_type_param(), queue_type_param(), reassoc_add(), refsym(), refsym_inscope(), _acl::repeatc, rewrite_cmplxpart_rval(), RHS, RTE_loc, RUNTIMEG, S_ACONST, S_CONST, S_DERIVED, S_EXPR, S_IDENT, S_KEYWORD, S_LABEL, S_LVALUE, S_NULL, S_REF, S_SCONST, S_STFUNC, S_TRIPLE, S_VAL, SEM::save_aconst, sc_local_passbyvalue(), SCFTN_FALSE, scn, sem, sem_set_storage_class(), sem_strcmp(), setimplicit(), _acl::size, FLG::smp, sptr, SEM::ssa_area, ssa_list(), SST_ACLG, SST_ACLP, SST_ASTG, SST_ASTP, SST_BEGG, SST_BEGP, SST_CVALG, SST_CVALP, SST_DBEGP, SST_DIMFLAGP, SST_DTYPEG, SST_DTYPEP, SST_E1G, SST_E1P, SST_E2G, SST_E2P, SST_E3G, SST_E3P, SST_ENDG, SST_ENDP, SST_ERRSYMP, SST_IDG, SST_IDP, SST_ISNONDECC, SST_LSYMG, SST_LSYMP, SST_MNOFFP, SST_OPCP, SST_OPTYPEG, SST_OPTYPEP, SST_PARENG, SST_PARENP, SST_SHAPEP, SST_SYMG, SST_SYMP, SST_TMPG, SST_TMPP, FLG::standard, _std_range::start, stb, _std_record::std, STD_LAST, STD_PREV, DOINFO::step_expr, SEM::stfunc_error, _std_record::stkp, xyyz::stkp, _acl::stkp, strideMask, string_length(), string_with_kind(), _acl::subc, sym_mkfunc_nodesc(), sym_of_ast(), sym_skip_construct(), SYMNAME, xyyz::t, SEM::tbp_arg, test_private_dtype(), TK_EQUALS, SEM::tkntyp, top, TRUE, TY_CMPLX, TY_INT8, TY_LOG8, TY_NCHAR, SEM::type_mode, _acl::u1, uboundMask, uf, unop(), SEM::use_etmps, STB::user, val, var_ref_list(), void(), and XBIT.
Referenced by _parser(), and parser().
ssa_list()
static void ssa_list (SST * top, int rhstop) static
Definition at line 2663 of file semant2.c.
References AC_EXPR, GET_ACL, _acl::id, SEM::in_struct_constr, itemp, LHS, mkitem(), _acl::next, NULL, _acl::repeatc, RHS, S_ACONST, S_SCONST, sem, _acl::size, SST_ACLG, SST_BEGP, SST_E1G, SST_ENDG, SST_ENDP, SST_IDG, _acl::stkp, _acl::subc, and _acl::u1.
Referenced by semant2().
string_with_kind()
static void string_with_kind (SST * top) static
Definition at line 2712 of file semant2.c.
References ast_cnst(), LHS, RHS, SST_CVALP, SST_DTYPEP, SST_SYMG, and top.
Referenced by semant2().
test_private_dtype()
int test_private_dtype (int dtype)
Check whether the dtype is inside a valid scope.
Definition at line 2783 of file semant2.c.
References STB::curr_scope, DTY, NOSYM, scope, and stb.
Referenced by add_iolptrs(), has_private(), semant2(), and semant3().
var_ref_list()
static void var_ref_list (SST * top, int rhstop) static
Definition at line 2649 of file semant2.c.
References getitem(), itemp, LHS, mkitem(), RHS, SST_BEGP, SST_ENDG, and SST_ENDP.
Referenced by semant2().