flang: semfin.c File Reference
semfin.c File Reference
Fortran routines called at the end of semantic processing.
#include "gbldefs.h"
#include "global.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "semant.h"
#include "error.h"
#include "semstk.h"
#include "soc.h"
#include "dinit.h"
#include "machar.h"
#include "state.h"
#include "ast.h"
#include "rte.h"
#include "rtlRtns.h"
Classes
struct PSECT
Macros
#define NO_PTR XBIT(49, 0x8000)
#define NO_CHARPTR XBIT(58, 0x1)
#define NO_DERIVEDPTR XBIT(58, 0x40000)
#define USER_GNRIC_OR_OPR(sptr)
#define EVARERR(n, m)
#define PUT(n) (_put((INT)(n)))
#define PUTA(n) (dinit_put(DINIT_LABEL, (INT)(n)))
Functions
static void do_common_blocks (void)
static LOGICAL is_in_currsub (int sptr)
static void expand_common_pointers (int)
static void reorder_common_pointers (int)
static void fix_args (int)
static void check_derived_type_in_comm (int common)
static void do_access (void)
static LOGICAL chk_evar (int)
static void equivalence (int, int)
static void add_socs (int, ISZ_T, ISZ_T)
static void do_nml (void)
static void do_save (void)
static void do_sequence (void)
static void nml_equiv (int socp)
set NML of all symbols which are equivalenced (closure of socs)
static void dinit_name (int sptr)
static void put_name (int sptr)
static void misc_checks (void)
static void vol_equiv (int socp)
set VOL of all symbols which are equivalenced (closure of socs)
static void incr_invobj_for_retval_add (int impl_sptr, LOGICAL addit)
Increment a type bound procedure's (tbp's) pass object argument position (its INVOBJ field) if we are adding a result variable as the function's first argument.
static void merge_generics (void)
static void inject_arg (int func_sptr, int arg_sptr, int position)
static LOGICAL have_class_args_been_fixed_already (int func_sptr)
static LOGICAL add_class_arg_descr_arg (int func_sptr, int arg_sptr, int new_arg_position)
static void prepend_func_result_as_first_arg (int func_sptr)
void semfin (void)
Finalize semantic processing.
void semfin_free_memory (void)
Deallocate data structures for semantic analysis.
void fix_class_args (int func_sptr)
Add type descriptor arguments to a specified function if they have not already been added.
void llvm_fix_args (int sptr)
static int gen_accl_alias (int sptr, ACCL *accessp)
void do_equiv (void)
static void _put (INT)
static void nml_traverse (int, void(*p)(int))
static void nml_check_item (int)
static void nml_emit_desc (int)
static void nml_sym_is_refd (int sptr)
static void do_nml_sym_is_refd (void)
static int gen_vlist (void)
static ITEM * gen_dtio_arglist (int sptr, int vlist_ast)
static LOGICAL in_local_scope (int sym, int local_scope)
static LOGICAL _available (int ast)
static LOGICAL _available_size (int ast)
void CheckDecl (int sptr)
Check that sptr is declared if IMPLICIT NONE is set.
static LOGICAL search_for_auto (int ast, int *auto_found)
static LOGICAL bnd_contains_auto (int ast)
static LOGICAL bounds_contain_automatics (int sptr)
static void append_to_adjarr_list (int sptr)
static void append_to_adjstr_list (int sptr)
static void presence_test (LOGICAL *tested_presence, int *after_std, SPTR sptr)
void init_derived_type (SPTR sptr, int parent_ast, int wherestd)
void rw_semant_state (RW_ROUTINE, RW_FILE)
Variables
static PSECT * psect_base
static int psect_num
static int psect_size
static LOGICAL in_module
static int nml
static LOGICAL nml_err
static int nml_size
static LOGICAL new_nml
static int static_cnt = 0
static LOGICAL available_internal
static SPTR array_construct_scope
Detailed Description
Fortran routines called at the end of semantic processing.
Definition in file semfin.c.
Macro Definition Documentation
EVARERR
#define EVARERR (n, m)
Value:
  {                                            \
    error(n, 3, gbl.lineno, SYMNAME(sptr), m); \
    return FALSE;                              \
  }
NO_CHARPTR
#define NO_CHARPTR XBIT(58, 0x1)
Definition at line 63 of file semfin.c.
NO_DERIVEDPTR
#define NO_DERIVEDPTR XBIT(58, 0x40000)
Definition at line 64 of file semfin.c.
NO_PTR
#define NO_PTR XBIT(49, 0x8000)
Definition at line 62 of file semfin.c.
PUT
#define PUT (n) (_put((INT)(n)))
Definition at line 1988 of file semfin.c.
PUTA
#define PUTA (n) (dinit_put(DINIT_LABEL, (INT)(n)))
Definition at line 1989 of file semfin.c.
USER_GNRIC_OR_OPR
#define USER_GNRIC_OR_OPR (sptr)
Value:
  (sptr > stb.firstusym &&      \
   (STYPEG(sptr) == ST_USERGENERIC || STYPEG(sptr) == ST_OPERATOR))
Definition at line 127 of file semfin.c.
Function Documentation
_available()
static LOGICAL _available (int ast) static
Definition at line 2958 of file semfin.c.
References _available(), _available_size(), A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, ast, astb, available_internal, FALSE, FLANG_FALLTHROUGH, gbl, i, ndim, ASTB::ptr0, ASTB::ptr0c, ASTB::ptr1, sptr, ss, and TRUE.
Referenced by _available(), and _available_size().
_available_size()
static LOGICAL _available_size (int ast) static
Definition at line 2849 of file semfin.c.
References _available(), _available_size(), A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, ast, astb, available_internal, FALSE, FLANG_FALLTHROUGH, i, ndim, ASTB::ptr0, ASTB::ptr0c, ASTB::ptr1, sptr, ss, and TRUE.
Referenced by _available(), and _available_size().
_put()
static void _put (INT n) static
Definition at line 2111 of file semfin.c.
References cngcon(), dinit_put(), DT_PTR, n, and size_of().
add_class_arg_descr_arg()
static LOGICAL add_class_arg_descr_arg (int func_sptr, int arg_sptr, int new_arg_position) static
Definition at line 252 of file semfin.c.
References ADD_LWAST, ADD_LWBD, ADD_NUMELM, ADD_UPAST, ADD_UPBD, astb, ASTB::bnd, ASTB::dtype, FALSE, get_array_dtype(), get_descriptor_len(), getccsym_sc(), inject_arg(), mk_isz_cval(), needs_descriptor(), ASTB::one, set_parref_flag2(), sym_get_arg_sec(), tmp, and TRUE.
Referenced by fix_class_args(), and prepend_func_result_as_first_arg().
add_socs()
static void add_socs (int sptr, ISZ_T addr, ISZ_T size) static
Definition at line 1903 of file semfin.c.
References addr, assert, SOC::avail, SOC::base, DBGBIT, gbl, ISZ_T, NEED, NOSYM, size, SOC::size, size_of(), soc, SOC_NEXT, SOC_SPTR, sptr, and SYMNAME.
Referenced by do_equiv().
append_to_adjarr_list()
static void append_to_adjarr_list (int sptr) static
Definition at line 3172 of file semfin.c.
References gbl, i, NOSYM, and sptr.
Referenced by misc_checks().
append_to_adjstr_list()
static void append_to_adjstr_list (int sptr) static
Definition at line 3187 of file semfin.c.
References gbl, i, NOSYM, and sptr.
Referenced by misc_checks().
bnd_contains_auto()
static LOGICAL bnd_contains_auto (int ast) static
Definition at line 3144 of file semfin.c.
References ast, ast_traverse(), ast_unvisit(), ast_visit(), FALSE, NULL, and search_for_auto().
Referenced by bounds_contain_automatics().
bounds_contain_automatics()
static LOGICAL bounds_contain_automatics (int sptr) static
Definition at line 3154 of file semfin.c.
References AD_DPTR, AD_LWBD, AD_NUMDIM, AD_UPBD, array_construct_scope, bnd_contains_auto(), FALSE, i, ndim, sptr, and TRUE.
Referenced by misc_checks().
check_derived_type_in_comm()
static void check_derived_type_in_comm (int common) static
Definition at line 642 of file semfin.c.
References allocatable_member(), common, DDTG, DTY, ERR_Severe, error(), get_struct_tag_sptr(), has_init_value(), NOSYM, and SYMNAME.
Referenced by do_common_blocks().
CheckDecl()
void CheckDecl (int sptr)
Check that sptr is declared if IMPLICIT NONE is set.
Be careful about the situation where IMPLICIT NONE is in the host, but there are IMPLICIT statements in the contained subprogram.
Definition at line 3074 of file semfin.c.
References CNULL, error(), gbl, IN_MODULE, SEM::mod_cnt, SEM::none_implicit, sem, sptr, SYMNAME, was_implicit(), SEM::which_pass, and XBIT.
chk_evar()
static LOGICAL chk_evar (int evp) static
Definition at line 1609 of file semfin.c.
References AD_LWAST, AD_MLPYR, AD_NUMDIM, AD_PTR, AD_UPAST, assert, PSECT::cmblk, CNULL, CONVAL2G, DBGBIT, DDTG, dim, DTY, DTYG, EQV, EQV_NUMSS, EQV_SS, error(), EVARERR, FALSE, flg, gbl, get_int_cval(), ISZ_PF, ISZ_T, j, lineno, PSECT::memlist, NEED, NOSYM, offset, psect_base, psect_num, psect_size, SC_ISCMBLK, size_of(), sptr, ss, FLG::standard, sym_of_ast(), SYMNAME, TRUE, TY_CHAR, TY_NCHAR, and val.
Referenced by do_equiv().
dinit_name()
static void dinit_name (int sptr) static
Definition at line 2638 of file semfin.c.
References DINIT_END, DINIT_LOC, dinit_put(), DINIT_STR, getcctmp(), getstring(), local_sname(), name, sptr, strlen(), sym_is_refd(), and SYMNAME.
Referenced by do_nml().
do_access()
static void do_access (void) static
Definition at line 1196 of file semfin.c.
References SEM::accl, STB::curr_scope, DTY, error(), findByNameStypeScope(), STB::firstosym, STB::firstusym, gbl, gen_accl_alias(), GSAMEG, IN_MODULE, in_module, insert_sym(), is_procedure_ptr(), SEM::mod_public_flag, _accl::next, SEM::none_implicit, NOSYM, NULL, _accl::oper, refsym(), sem, sptr, _accl::sptr, stb, sym_in_scope(), SYMNAME, and _accl::type.
Referenced by semfin().
do_common_blocks()
static void do_common_blocks (void) static
Definition at line 682 of file semfin.c.
References ADD_DEFER, addr, ALIGN, alignment_of_var(), check_derived_type_in_comm(), CNULL, DTY, DTYG, ERR_Informational, ERR_Severe, ERR_Warning, error(), expand_common_pointers(), first_hash(), STB::firstusym, flg, gbl, is_in_currsub(), ISZ_T, msz, NOSYM, pad_cmn_mem(), reorder_common_pointers(), SEM::savall, sem, size, size_of_var(), SOC_NEXT, SOC_SPTR, sptr, FLG::standard, stb, SYMNAME, TY_CHAR, TY_NCHAR, SEM::which_pass, and XBIT.
Referenced by semfin().
do_equiv()
void do_equiv (void)
Definition at line 1438 of file semfin.c.
References a, add_socs(), addr, ALIGN, alignment(), assert, SOC::base, chk_evar(), PSECT::cmblk, CMEMLG, CMEMLP, CNULL, DBGBIT, equivalence(), EQV, SEM::eqvlist, error(), FALSE, fix_equiv_locals(), fix_equiv_statics(), flg, FREE, gbl, in_module, ISZ_T, PSECT::memlist, NEW, next, nml_equiv(), NOSYM, psect_base, psect_num, psect_size, FLG::recursive, SEM::savall, sem, size, SOC::size, size_of(), soc, sptr, SYMNAME, and vol_equiv().
Referenced by semfin().
do_nml()
static void do_nml (void) static
Definition at line 1996 of file semfin.c.
References cnt, DINIT_END, dinit_name(), DINIT_NML, dinit_put(), FALSE, gbl, in_module, mkRteRtnNm(), new_nml, SEM::nml, nml, nml_check_item(), nml_emit_desc(), nml_err, NML_LINENO, NML_NEXT, nml_size, NML_SPTR, nml_traverse(), NOSYM, plist(), PUT, put_name(), RTE_loc, sem, sptr, sym_is_refd(), sym_mkfunc_nodesc(), TRUE, void(), and XBIT.
Referenced by semfin().
do_nml_sym_is_refd()
static void do_nml_sym_is_refd (void) static
Definition at line 2098 of file semfin.c.
References SEM::nml, nml, NML_NEXT, NML_SPTR, nml_sym_is_refd(), nml_traverse(), NOSYM, sem, and sptr.
Referenced by misc_checks().
do_save()
static void do_save (void) static
Definition at line 2692 of file semfin.c.
References CNULL, STB::curr_scope, DDTG, DTY, error(), STB::firstusym, gbl, in_local_scope(), in_save_scope(), RUNTIMEG, sptr, ST_ISVAR, stb, sym_is_refd(), SYMNAME, TY_CHAR, and TY_NCHAR.
Referenced by semfin().
do_sequence()
static void do_sequence (void) static
Definition at line 2744 of file semfin.c.
References error(), STB::firstusym, flg, gbl, _seql::next, NOSYM, NULL, sem, SEM::seql, FLG::sequence, sptr, _seql::sptr, ST_ISVAR, stb, SYMNAME, and _seql::type.
Referenced by semfin().
equivalence()
static void equivalence (int evp, int evp2) static
Definition at line 1801 of file semfin.c.
References assert, PSECT::cmblk, DBGBIT, DTYG, EQV, error(), flg, gbl, in_module, ISZ_PF, ISZ_T, PSECT::memlist, NOSYM, offset, psect_base, sptr, FLG::standard, SYMNAME, TY_CHAR, and TY_NCHAR.
Referenced by do_equiv().
expand_common_pointers()
static void expand_common_pointers (int sptr) static
Definition at line 837 of file semfin.c.
References CMEMLP, DTYG, get_all_descriptors(), get_static_descriptor(), NO_CHARPTR, NO_DERIVEDPTR, NO_PTR, NOSYM, off, sptr, TY_CHAR, and TY_NCHAR.
Referenced by do_common_blocks().
fix_args()
static void fix_args (int sptr) static
Definition at line 1081 of file semfin.c.
References arg, assert, aux, CNULL, AUX::dpdsc_base, error(), errsev(), gbl, gen_conditional_dealloc_for_sym(), get_all_descriptors(), get_static_descriptor(), i, INTENT_DFLT, INTENT_IN, INTENT_OUT, INTENTG, INTENTP, sptr, and SYMNAME.
Referenced by llvm_fix_args(), and semfin().
fix_class_args()
void fix_class_args (int func_sptr)
Add type descriptor arguments to a specified function if they have not already been added.
Parameters
sptr is the symbol table pointer of the specified function.
Definition at line 1065 of file semfin.c.
References add_class_arg_descr_arg(), aux, AUX::dpdsc_base, have_class_args_been_fixed_already(), and j.
Referenced by _stb_fixup_ifacearg(), do_end_subprogram(), gen_poly_element_arg(), get_type_descr_dummy(), llvm_check_retval_inargs(), semant1(), semfin(), and transform_call().
gen_accl_alias()
static int gen_accl_alias (int sptr, ACCL * accessp) static
Definition at line 1179 of file semfin.c.
References STB::curr_scope, insert_sym(), sptr, _accl::sptr, and stb.
Referenced by do_access().
gen_dtio_arglist()
static ITEM * gen_dtio_arglist (int sptr, int vlist_ast) static
Definition at line 2294 of file semfin.c.
References ast_type, astb, CONVAL2G, DDTG, DT_INT, SEM::dtemps, DTY, getcctmp_sc(), getitem(), getstring(), ASTB::i0, ITEM_END, mk_cnst(), mk_convert(), mk_id(), NULL, p, S_CONST, S_IDENT, sem, sptr, SST_ASTP, SST_CVALP, SST_DTYPEP, SST_IDP, SST_LSYMP, SST_PARENP, SST_SHAPEP, SST_SYMP, strlen(), and XBIT.
Referenced by nml_emit_desc().
gen_vlist()
static int gen_vlist (void) static
Definition at line 2262 of file semfin.c.
References AD_DPTR, AD_LWAST, AD_LWBD, AD_MLPYR, AD_UPAST, AD_UPBD, astb, DT_INT, SEM::dtemps, get_all_descriptors(), get_array_dtype(), get_static_descriptor(), getcctmp_sc(), ASTB::i0, ASTB::i1, mk_id(), sem, sptr, and XBIT.
Referenced by nml_emit_desc().
have_class_args_been_fixed_already()
static LOGICAL have_class_args_been_fixed_already (int func_sptr) static
Definition at line 237 of file semfin.c.
References aux, count, AUX::dpdsc_base, FALSE, j, and TRUE.
Referenced by fix_class_args(), and prepend_func_result_as_first_arg().
in_local_scope()
static LOGICAL in_local_scope (int sym, int local_scope) static
Definition at line 2683 of file semfin.c.
Referenced by do_save().
incr_invobj_for_retval_add()
static void incr_invobj_for_retval_add (int impl_sptr, LOGICAL addit) static
Increment a type bound procedure's (tbp's) pass object argument position (its INVOBJ field) if we are adding a result variable as the function's first argument.
The pass object's argument position of a tbp is stored in the INVOBJ field. We need to increment it when we are about to add the result variable as the first argument in the function (e.g., pointer and allocatable results). This function is passed a symbol table pointer (sptr) to a function. We check to see if there are any tbps that use the function as an implementation (i.e., the RHS of the => in a tbp declaration). If so, we check whether the first argument is already a result variable. If it is not, we increment the pass object argument position (INVOBJ field). If there is already a result variable, we skip it. If a derived type inherits from a type defined in a use associated module, it can have function tbps that already have had their argument lists set-up. That's why we can't just arbitrarily increment the INVOBJ field of a tbp.
If the addit field is set, then this function is being called by ipa_semfin(). It handles a special case for IPA in which the result argument may already have been set in the semfin() function during the first compilation, but the INVOBJ has not yet been set.
If a tbp has an explicit pass(arg) attribute defined, then we can just update the INVOBJ field by searching the argument list for the specified pass argument.
Parameters
sptr is the function symbol to search.
addit is true when this is a special case for IPA (see the verbose description of this function).
Definition at line 100 of file semfin.c.
References aux, AUX::dpdsc_base, find_dummy_position(), NOSYM, stb, and TRUE.
Referenced by prepend_func_result_as_first_arg().
init_derived_type()
void init_derived_type (SPTR sptr, int parent_ast, int wherestd)
Definition at line 3548 of file semfin.c.
References add_stmt_after(), allocatable_member(), argt, ARGT_ARG, array_element_dtype(), BLOCK_ENTRY_STD, FALSE, find_descriptor_ast(), gbl, gen_dealloc_for_sym(), get_dtype_init_template(), get_static_type_descriptor(), get_struct_tag_sptr(), is_array_dtype(), mk_argt(), mk_assn_stmt(), mk_cval(), mk_func_node(), mk_id(), mk_stmt(), mk_unop(), mkRteRtnNm(), new_ast(), NOSYM, OP_VAL, presence_test(), rank_of_sym(), RTE_init_from_desc, sptr, std, and sym_mkfunc_nodesc().
Referenced by func_call2(), gen_finalized_result(), misc_checks(), and ptrfunc_call().
inject_arg()
static void inject_arg (int func_sptr, int arg_sptr, int position) static
Definition at line 218 of file semfin.c.
References aux, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, and NEED.
Referenced by add_class_arg_descr_arg(), and prepend_func_result_as_first_arg().
is_in_currsub()
static LOGICAL is_in_currsub (int sptr) static
Definition at line 827 of file semfin.c.
References gbl, scope, and sptr.
Referenced by do_common_blocks().
llvm_fix_args()
void llvm_fix_args (int sptr)
Definition at line 1173 of file semfin.c.
References fix_args(), and sptr.
Referenced by llvm_check_retval_inargs().
merge_generics()
static void merge_generics (void) static
Definition at line 132 of file semfin.c.
References copy_specifics(), STB::curr_scope, declsym_newscope(), first_hash(), STB::firstusym, NOSYM, SEM::pgphase, PHASE_CONTAIN, sem, sptr, stb, test_scope(), SEM::use_seen, and USER_GNRIC_OR_OPR.
Referenced by semfin().
misc_checks()
static void misc_checks (void) static
Definition at line 3202 of file semfin.c.
References add_auto_dealloc(), add_nullify_ast(), add_stmt_after(), append_to_adjarr_list(), append_to_adjstr_list(), ast, bounds_contain_automatics(), build_typedef_init_tree(), CNULL, DCLCHK, DDTG, do_nml_sym_is_refd(), DT_INT, DTY, ERR_Severe, error(), STB::firstusym, FLANG_FALLTHROUGH, gbl, get_all_descriptors(), get_static_descriptor(), get_struct_initialization_tree(), has_finalized_component(), IGNORE_C, ignore_tkr_all(), in_module, in_save_scope(), init_derived_type(), SEM::intent_list, INTENT_OUT, INTENTG, itemp, mk_id(), nml_err, SEM::none_implicit, NULL, RU_FUNC, RU_PROG, RUNTIMEG, sem, sem_set_storage_class(), sptr, stb, SYMNAME, trans_mkdescr(), void(), SEM::which_pass, WINNT_CALL, WINNT_CREF, WINNT_NOMIXEDSTRLEN, and XBIT.
Referenced by semfin().
nml_check_item()
static void nml_check_item (int sptr) static
assumed-size char not allowed
assumed-size arrays not allowed
Definition at line 2183 of file semfin.c.
References ADD_NUMDIM, DDTG, DT_IO_FREAD, DT_IO_FWRITE, DTY, dtype_has_defined_io(), error(), FLANG_FALLTHROUGH, gbl, i, ndims, nml, nml_err, nml_size, sptr, SYMNAME, TRUE, and TY_CHAR.
Referenced by do_nml().
nml_emit_desc()
static void nml_emit_desc (int sptr) static
Definition at line 2410 of file semfin.c.
References AD_LWAST, AD_NUMDIM, AD_PTR, AD_UPAST, ADD_LWBD, add_stmt_after(), ADD_UPBD, ast, cnt, DDTG, dest, dt, DT_INT, DT_IO_FREAD, DT_IO_FWRITE, DT_PTR, DTY, dtype_has_defined_io(), dtype_to_arg(), FALSE, gen_dtio_arglist(), gen_vlist(), get_all_descriptors(), get_implementation(), get_int_cval(), get_static_descriptor(), i, MAXRANK, mk_assn_stmt(), mk_cval(), mk_id(), mk_subscr(), mk_unop(), ndims, new_nml, nml, OP_LOC, PUT, put_name(), PUTA, resolve_defined_io(), sptr, static_cnt, xyyz::stkp, string_length(), sym_of_ast(), xyyz::t, trans_mkdescr(), TRUE, TY_CHAR, and TY_NCHAR.
Referenced by do_nml().
nml_equiv()
static void nml_equiv (int socp) static
set NML of all symbols which are equivalenced (closure of socs)
Definition at line 1962 of file semfin.c.
References nml_equiv(), p, SOC_NEXT, SOC_SPTR, and sptr.
Referenced by do_equiv(), and nml_equiv().
nml_sym_is_refd()
static void nml_sym_is_refd (int sptr) static
Definition at line 2086 of file semfin.c.
References sptr, and sym_is_refd().
Referenced by do_nml_sym_is_refd().
nml_traverse()
static void nml_traverse (int sptr, void(*)(int) p) static
Definition at line 2143 of file semfin.c.
References DDTG, DT_IO_FREAD, DT_IO_FWRITE, DTY, dtype_has_defined_io(), i, m, nml_traverse(), NOSYM, parent, and sptr.
Referenced by do_nml(), do_nml_sym_is_refd(), and nml_traverse().
prepend_func_result_as_first_arg()
static void prepend_func_result_as_first_arg (int func_sptr) static
Definition at line 283 of file semfin.c.
References add_class_arg_descr_arg(), aux, AUX::dpdsc_base, FALSE, have_class_args_been_fixed_already(), incr_invobj_for_retval_add(), inject_arg(), and NOSYM.
Referenced by semfin().
presence_test()
static void presence_test (LOGICAL * tested_presence, int * after_std, SPTR sptr) static
Definition at line 3530 of file semfin.c.
References add_stmt_after(), ast_intr(), STB::dt_log, mk_id(), mk_stmt(), mkRteRtnNm(), present, RTE_present, sptr, stb, sym_mkfunc_nodesc(), TRUE, STB::user, and void().
Referenced by init_derived_type().
put_name()
static void put_name (int sptr) static
Definition at line 2663 of file semfin.c.
References DINIT_LABEL, dinit_put(), getcctmp(), getstring(), local_sname(), name, PUT, sptr, strlen(), sym_is_refd(), SYMNAME, and XBIT.
Referenced by do_nml(), and nml_emit_desc().
reorder_common_pointers()
static void reorder_common_pointers (int sptr) static
Definition at line 931 of file semfin.c.
References CMEMLP, DTYG, get_all_descriptors(), get_static_descriptor(), NO_CHARPTR, NO_DERIVEDPTR, NO_PTR, NOSYM, off, sptr, TY_CHAR, and TY_NCHAR.
Referenced by do_common_blocks().
rw_semant_state()
void rw_semant_state (RW_ROUTINE , RW_FILE)
Definition at line 3607 of file semfin.c.
References STB::curr_scope, SEM::eqv_avail, SEM::eqv_base, SEM::eqv_size, SEM::eqv_ss_avail, SEM::eqv_ss_base, SEM::eqv_ss_size, SEM::eqvlist, fd, ISREAD, NEED, SEM::none_implicit, SYMUTL::none_implicit, RW_FD, RW_SCALAR, SEM::scope_level, SEM::scope_size, SEM::scope_stack, sem, stb, and symutl.
Referenced by rw_host_state().
search_for_auto()
static LOGICAL search_for_auto (int ast, int * auto_found) static
Definition at line 3117 of file semfin.c.
References A_ARGCNTG, argt, ARGT_ARG, array_construct_scope, ast, ast_visit(), DT_ISINT, gbl, i, sptr, and TRUE.
Referenced by bnd_contains_auto().
semfin()
void semfin (void)
Finalize semantic processing.
Definition at line 319 of file semfin.c.
References FLG::accmp, allocatable_member(), arg, assert, aux, CNULL, conformable(), DBGBIT, df_dinit_end(), do_access(), do_common_blocks(), do_dinit(), do_equiv(), do_nml(), do_save(), do_sequence(), AUX::dpdsc_avl, AUX::dpdsc_base, DTY, DTYG, ENDLINEP, SEM::eqvlist, errlabel(), error(), FALSE, STB::firstosym, fix_args(), fix_class_args(), fixup_reqgs_ident(), SEM::flabels, flg, FUNCLINEG, gbl, FLG::hpf, i, IN_MODULE, in_module, AUX::list, merge_generics(), misc_checks(), mkRteRtnNm(), NOSYM, pop_scope_level(), prepend_func_result_as_first_arg(), push_scope_level(), queue_tbp(), FLG::recursive, ref_entry(), RTE_loc, RU_BDATA, RU_FUNC, RU_PROG, RU_SUBR, SEM::savall, SEM::savloc, SCOPE_NORMAL, sem, FLG::sequence, FLG::smp, sptr, stb, sym_mkfunc_nodesc(), SYMNAME, TBP_COMPLETE_FIN, TRUE, TY_CHAR, TY_DCMPLX, TY_NCHAR, SEM::typroc_avail, SEM::typroc_base, void(), SEM::which_pass, and XBIT.
Referenced by fix_module_common(), and semant1().
semfin_free_memory()
void semfin_free_memory (void)
Deallocate data structures for semantic analysis.
Definition at line 1032 of file semfin.c.
References SEM::doif_base, FREE, freearea(), SEM::iface_base, SEM::interf_base, NULL, SEM::scope_stack, sem, SEM::stsk_base, switch_base, and SEM::typroc_base.
Referenced by semant1().
vol_equiv()
static void vol_equiv (int socp) static
set VOL of all symbols which are equivalenced (closure of socs)
Definition at line 1940 of file semfin.c.
References p, SOC_NEXT, SOC_SPTR, sptr, and vol_equiv().
Referenced by do_equiv(), and vol_equiv().
Variable Documentation
array_construct_scope
SPTR array_construct_scope static
Definition at line 3114 of file semfin.c.
Referenced by bounds_contain_automatics(), and search_for_auto().
available_internal
LOGICAL available_internal static
Definition at line 2845 of file semfin.c.
Referenced by _available(), and _available_size().
in_module
LOGICAL in_module static
Definition at line 59 of file semfin.c.
Referenced by do_access(), do_equiv(), do_nml(), equivalence(), misc_checks(), and semfin().
new_nml
LOGICAL new_nml static
Definition at line 1985 of file semfin.c.
Referenced by do_nml(), and nml_emit_desc().
nml
int nml static
Definition at line 1982 of file semfin.c.
Referenced by do_nml(), do_nml_sym_is_refd(), export_symbol(), fill_links_symbol(), fix_symbol(), get_nml_array(), import(), nml_check_item(), nml_emit_desc(), and read_symbol().
nml_err
LOGICAL nml_err static
Definition at line 1983 of file semfin.c.
Referenced by do_nml(), misc_checks(), and nml_check_item().
nml_size
int nml_size static
Definition at line 1984 of file semfin.c.
Referenced by do_nml(), and nml_check_item().
psect_base
PSECT* psect_base static
Definition at line 56 of file semfin.c.
Referenced by chk_evar(), do_equiv(), and equivalence().
psect_num
int psect_num static
Definition at line 57 of file semfin.c.
Referenced by chk_evar(), and do_equiv().
psect_size
int psect_size static
Definition at line 58 of file semfin.c.
Referenced by chk_evar(), and do_equiv().
static_cnt
int static_cnt = 0 static
Definition at line 2404 of file semfin.c.
Referenced by nml_emit_desc().