flang: semfunc.c File Reference
semfunc.c File Reference
Fortran front-end utility routines used by Semantic Analyzer to process functions, subroutines, predeclareds, etc.
#include "gbldefs.h"
#include "global.h"
#include "gramtk.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "semant.h"
#include "scan.h"
#include "ilmtp.h"
#include "semstk.h"
#include "pd.h"
#include "machar.h"
#include "ast.h"
#include "rte.h"
#include "rtlRtns.h"
#include "version.h"
#include "atomic_common.h"
Macros
#define MAX_ARGS_NUMBER 3
#define ARGS_NUMBER 3
#define MIN_ARGS_NUMBER 0
#define E74_CNT(s, c, l, u) (_e74_sym = s, _e74_cnt = c, _e74_l = l, _e74_u = u)
#define E74_ARG(s, p, k) (_e74_sym = s, _e74_pos = p, _e74_kwd = k)
#define ERR170(s) error(170, 2, gbl.lineno, s, CNULL)
#define HL_UF(s) error(0, 3, gbl.lineno, "HPF Library procedure not implemented", SYMNAME(s))
#define GET_CVAL_ARG(i) get_sst_cval(ARG_STK(i))
#define GET_DBLE(x, y)
#define GET_QUAD(x, y)
#define PASS_BYVAL 1
#define PASS_BYREF 2
#define PASS_BYREF_NO_LEN 3
#define PASS_BYDEFAULT 0
#define TYPELESS(dt)
#define C90_EPSILON "0.1421085471520200e-13"
#define C90_TINY "0.73344154702194e-2465" /* 0200044000000000000000 */
Functions
static void add_typroc (int)
static void count_actuals (ITEM *)
static void count_formals (int)
static void count_formal_args (int, int)
static void check_dim_error (int, int)
static int mk_array_type (int, int)
static int gen_pointer_result (int, int, int, LOGICAL, int)
static int gen_allocatable_result (int, int, int, LOGICAL, int)
static int gen_array_result (int, int, int, LOGICAL, int)
static int gen_char_result (int, int, int)
static void precompute_arg_intrin (int, int)
static void precompute_args (int, int)
static void replace_arguments (int, int)
static void rewrite_triples (int, int, int)
static void rewrite_subscr (int, int, int)
static void replace_formal_triples (int, int, int)
static int getMergeSym (int, int)
static void ref_pd_subr (SST *, ITEM *)
static void ref_intrin_subr (SST *, ITEM *)
static int set_kind_result (SST *, int, int)
static int set_shape_result (int, int)
static int _adjustl (int)
static int _adjustr (int)
static int _index (int, int, int)
static int _len_trim (int)
static int _repeat (int, int)
static int _scan (int, int, int)
static int _trim (int)
static int _verify (int, int, int)
static int find_byval_ref (int, int, int)
static int cmp_mod_scope (SPTR)
static void gen_init_intrin_call (SST *, int, int, int, int)
static int get_type_descr_dummy (int sptr, int arg)
static int get_tbp (int sptr)
static void fix_proc_pointer_call (SST *, ITEM **)
static int find_by_name_stype_arg (char *, int, int, int, int, int)
static void e74_cnt (int, int, int, int)
static void e74_arg (int, int, char *)
static int byvalue_ref_arg (SST *, int *, int, int)
static int gen_finalized_result (int fval, int func_sptr)
If applicable, generate finalization code for function result.
int get_static_type_descriptor (int sptr)
Return the "static type descriptor" for object sptr. The static type descriptor holds the "declared type" of an object.
int get_type_descr_arg (int func_sptr, int arg)
Return the type descriptor associated with arg (and func_sptr when arg is a dummy argument of routine func_sptr).
int get_type_descr_arg2 (int func_sptr, int arg)
Same as get_type_descr_arg(), but do not perform error check.
static int pass_char_no_len (int func_sptr, int param_sptr)
int sc_local_passbyvalue (int sptr, int func_sptr)
Return true if sptr is an SC_LOCAL and a pass by value parameter of func_sptr.
static int set_char_ref_val (int func, int param)
static void init_byval ()
static int inc_dummy_param (int func_sptr)
int get_byval (int func_sptr, int param_sptr)
Return true if param is pass by value.
static int rewrite_cptr_references (int ast)
LOGICAL allocatable_member (int sptr)
Return TRUE if sptr is a derived type with an allocatable member.
LOGICAL in_kernel_region ()
static int get_sym_from_sst_if_available (SST *sst_actual)
static LOGICAL is_ptr_arg (SST *sst_actual)
static int gen_and_assoc_tmp_ptr (SST *sst_actual, int std)
static LOGICAL need_tmp_retval (int func_sptr, int param_dummy)
int func_call2 (SST *stktop, ITEM *list, int flag)
Write ILMs to call a function.
static void resolve_fwd_ref (int ref)
Resolve forward references in function func_call().
int func_call (SST *stktop, ITEM *list)
int ptrfunc_call (SST *stktop, ITEM *list)
static int fix_character_length (int dtype, int func_sptr)
static int small_enough (ADSC *ad, int numdim)
int get_tbp_argno (int sptr, int dty)
int get_generic_member (int dtype, int sptr)
int get_generic_member2 (int dtype, int sptr, int argcnt, int *argno)
int generic_tbp_has_pass_and_nopass (int dtype, int sptr)
int get_generic_tbp_pass_or_nopass (int dtype, int sptr, int flag)
int get_specific_member (int dtype, int sptr)
int get_implementation (int dtype, int orig_sptr, int flag, int *memout)
For type bound procedures, find the implementation for the type bound procedure binding name in dtype.
void subr_call2 (SST *stktop, ITEM *list, int flag)
Write ILMs to call a subroutine.
void subr_call (SST *stktop, ITEM *list)
void ptrsubr_call (SST *stktop, ITEM *list)
static int gen_newer_intrin (int sptrgenr, int dtype)
int ref_intrin (SST *stktop, ITEM *list)
Handle Generic and Intrinsic function calls.
static int gen_call_class_obj_size (int sptr)
int ref_pd (SST *stktop, ITEM *list)
Handle calls to Predeclared functions.
int _selected_char_kind (int con)
Check charset.
Variables
struct {
int nent
int nargt
} carg
static int _e74_sym
static int _e74_cnt
static int _e74_l
static int _e74_u
static int _e74_pos
static char * _e74_kwd
static int byval_func_ptr = 0
static int byval_dscptr = 0
static int byval_paramct = 0
int dont_issue_assumedsize_error = 0
Detailed Description
Fortran front-end utility routines used by Semantic Analyzer to process functions, subroutines, predeclareds, etc.
Definition in file semfunc.c.
Macro Definition Documentation
ARGS_NUMBER
#define ARGS_NUMBER 3
Definition at line 33 of file semfunc.c.
C90_EPSILON
#define C90_EPSILON "0.1421085471520200e-13"
C90_TINY
#define C90_TINY "0.73344154702194e-2465" /* 0200044000000000000000 */
E74_ARG
#define E74_ARG (s, p, k) (_e74_sym = s, _e74_pos = p, _e74_kwd = k)
Definition at line 94 of file semfunc.c.
E74_CNT
#define E74_CNT (s, c, l, u) (_e74_sym = s, _e74_cnt = c, _e74_l = l, _e74_u = u)
Definition at line 93 of file semfunc.c.
ERR170
#define ERR170 (s) error(170, 2, gbl.lineno, s, CNULL)
Definition at line 96 of file semfunc.c.
GET_CVAL_ARG
#define GET_CVAL_ARG (i) get_sst_cval(ARG_STK(i))
Definition at line 100 of file semfunc.c.
GET_DBLE
#define GET_DBLE (x, y)
Value:
  x[0] = CONVAL1G(y);  \
  x[1] = CONVAL2G(y)
Definition at line 101 of file semfunc.c.
GET_QUAD
#define GET_QUAD (x, y)
Value:
  x[0] = CONVAL1G(y);  \
  x[1] = CONVAL2G(y);  \
  x[2] = CONVAL3G(y);  \
  x[3] = CONVAL4G(y);
Definition at line 104 of file semfunc.c.
HL_UF
#define HL_UF (s) error(0, 3, gbl.lineno, "HPF Library procedure not implemented", SYMNAME(s))
Definition at line 97 of file semfunc.c.
MAX_ARGS_NUMBER
#define MAX_ARGS_NUMBER 3
Definition at line 32 of file semfunc.c.
MIN_ARGS_NUMBER
#define MIN_ARGS_NUMBER 0
Definition at line 34 of file semfunc.c.
PASS_BYDEFAULT
#define PASS_BYDEFAULT 0
Definition at line 117 of file semfunc.c.
PASS_BYREF
#define PASS_BYREF 2
Definition at line 115 of file semfunc.c.
PASS_BYREF_NO_LEN
#define PASS_BYREF_NO_LEN 3
Definition at line 116 of file semfunc.c.
PASS_BYVAL
#define PASS_BYVAL 1
Definition at line 114 of file semfunc.c.
TYPELESS
#define TYPELESS (dt)
Value:
  (DT_ISINT(dt) || DTY(dt) == TY_HOLL || \
   (!XBIT(51, 0x20) && (DTY(dt) == TY_REAL || DTY(dt) == TY_DBLE)))
Function Documentation
_adjustl()
static int _adjustl (int string) static
Definition at line 12232 of file semfunc.c.
References cp, DTY, getcon(), getitem(), getstring(), i, STB::n_base, p, result, stb, str, string_length(), TY_NCHAR, and val.
Referenced by ref_pd().
_adjustr()
static int _adjustr (int string) static
Definition at line 12274 of file semfunc.c.
References cp, DTY, getcon(), getitem(), getstring(), i, STB::n_base, p, result, stb, str, string_length(), TY_NCHAR, and val.
Referenced by ref_pd().
_index()
static int _index (int string, int substring, int back) static
Definition at line 12317 of file semfunc.c.
References get_int_cval(), i, n, STB::n_base, stb, string_length(), and substring.
Referenced by ref_pd().
_len_trim()
static int _len_trim (int string) static
Definition at line 12351 of file semfunc.c.
References DTY, i, STB::n_base, p, result, stb, string_length(), and TY_NCHAR.
Referenced by ref_pd().
_repeat()
static int _repeat (int string, int ncopies) static
Definition at line 12376 of file semfunc.c.
References cp, DTY, get_int_cval(), get_type(), getcon(), getitem(), getstring(), i, j, mk_cval(), STB::n_base, p, result, stb, str, string_length(), strlen(), TY_NCHAR, and val.
Referenced by ref_pd().
_scan()
static int _scan (int string, int set, int back) static
Definition at line 12423 of file semfunc.c.
References get_int_cval(), i, j, STB::n_base, set, stb, and string_length().
Referenced by ref_pd().
_selected_char_kind()
int _selected_char_kind (int con)
Check charset.
Make sure this routine is consistent with
f90: dinit.c:_selected_char_kind()
runtime/f90: miscsup_com.c:_selected_char_kind()
Definition at line 12538 of file semfunc.c.
References sem_eq_str().
Referenced by ref_pd().
_trim()
static int _trim (int string) static
Definition at line 12448 of file semfunc.c.
References cp, DTY, get_type(), getcon(), getitem(), getstring(), i, kanji_len(), STB::n_base, p, result, stb, str, string_length(), strlen(), TY_NCHAR, and val.
Referenced by ref_pd().
_verify()
static int _verify (int string, int set, int back) static
Definition at line 12501 of file semfunc.c.
References get_int_cval(), i, j, STB::n_base, set, stb, and string_length().
Referenced by ref_pd().
add_typroc()
static void add_typroc (int dt) static
Definition at line 2016 of file semfunc.c.
References dt, i, NEED, sem, SEM::typroc_avail, SEM::typroc_base, and SEM::typroc_size.
Referenced by ptrfunc_call().
allocatable_member()
LOGICAL allocatable_member (int sptr)
Return TRUE if sptr is a derived type with an allocatable member.
Definition at line 567 of file semfunc.c.
References allocatable_member(), DDTG, DTY, DTYG, FALSE, is_tbp_or_final(), NOSYM, sptr, and TRUE.
Referenced by add_alloc_mem_initialize(), allocatable_member(), ast_has_allocatable_member(), check_derived_type_in_comm(), decl_private_sym(), func_call2(), gen_alloc_mem_initialize_for_sym2(), gen_dealloc_mbr(), handle_allocatable_members(), init_derived_type(), need_tmp_retval(), nullify_member_after(), ptrfunc_call(), rewrite_allocatable_assignment(), rewrite_calls(), rewrite_deallocate(), and semfin().
byvalue_ref_arg()
static int byvalue_ref_arg (SST * e1, int * dtype, int op, int func_sptr) static
Definition at line 505 of file semfunc.c.
References assert, cngtyp(), DDTG, DT_INT, DT_ISBASIC, DT_PTR, DTY, errsev(), is_iso_cptr(), mk_unop(), mkarg(), mkexpr(), new_ast(), OP_BYVAL, OP_REF, OP_VAL, rewrite_cptr_references(), S_EXPR, S_REF, S_VAL, SST_ASTG, SST_ASTP, SST_DTYPEG, SST_DTYPEP, SST_IDP, and SST_ISNONDECC.
Referenced by func_call2(), ptrfunc_call(), ptrsubr_call(), and subr_call2().
check_dim_error()
static void check_dim_error (int shape, int astdim) static
Definition at line 12549 of file semfunc.c.
References dim, error(), gbl, get_int_cval(), ndim, NULL, and SHD_NDIM.
Referenced by ref_pd().
cmp_mod_scope()
static int cmp_mod_scope (SPTR sptr) static
Definition at line 4143 of file semfunc.c.
References STB::curr_scope, IS_PROC, sptr, and stb.
Referenced by ref_intrin().
count_actuals()
static void count_actuals (ITEM * list) static
Definition at line 2031 of file semfunc.c.
References carg, ITEM_END, itemp, list, mkarg(), S_KEYWORD, S_SCONST, SST_E3G, and SST_IDG.
Referenced by func_call2(), ptrfunc_call(), ptrsubr_call(), and subr_call2().
count_formal_args()
static void count_formal_args (int paramct, int dpdsc) static
Definition at line 2060 of file semfunc.c.
References arg, aux, carg, AUX::dpdsc_base, DTY, and i.
Referenced by count_formals(), ptrfunc_call(), and ptrsubr_call().
count_formals()
static void count_formals (int sptr) static
Definition at line 2054 of file semfunc.c.
References count_formal_args(), and sptr.
Referenced by func_call2(), and subr_call2().
e74_arg()
static void e74_arg (int sym, int pos, char * kwd) static
Definition at line 5574 of file semfunc.c.
References buf, error(), gbl, i, KWDARGSTR, NULL, p, pos, q, sem, strlen(), SYMNAME, TRUE, and SEM::which_pass.
Referenced by ref_intrin_subr(), ref_pd(), and ref_pd_subr().
e74_cnt()
static void e74_cnt (int sym, int cnt, int l, int u) static
Definition at line 5559 of file semfunc.c.
References buf, cnt, error(), gbl, and SYMNAME.
Referenced by ref_intrin_subr(), ref_pd(), and ref_pd_subr().
find_by_name_stype_arg()
static int find_by_name_stype_arg (char * symname, int stype, int scope, int dtype, int inv, int exact) static
Definition at line 3065 of file semfunc.c.
References arg, aux, AUX::dpdsc_base, eq_dtype2(), HASH_ID, STB::hashtb, len, scope, stb, strlen(), and SYMNAME.
Referenced by get_implementation().
find_byval_ref()
static int find_byval_ref (int func_sptr, int param_sptr, int any_type) static
Definition at line 354 of file semfunc.c.
References DTY, is_iso_cptr(), NULL, PASS_BYDEFAULT, PASS_BYREF, PASS_BYVAL, proc_arginfo(), set_char_ref_val(), TY_CHAR, and TY_NCHAR.
Referenced by func_call2(), get_byval(), pass_char_no_len(), and ptrfunc_call().
fix_character_length()
static int fix_character_length (int dtype, int func_sptr) static
Definition at line 2083 of file semfunc.c.
References ast_rewrite(), ast_unvisit(), ast_visit(), DTY, get_type(), replace_arguments(), TY_CHAR, and TY_NCHAR.
Referenced by gen_allocatable_result(), and gen_pointer_result().
fix_proc_pointer_call()
static void fix_proc_pointer_call (SST * stktop, ITEM ** list) static
Definition at line 3752 of file semfunc.c.
References ast, check_member(), DTY, find_dummy_position(), findByNameStypeScope(), func, getitem(), i, is_procedure_ptr(), ITEM_END, itemp, list, memsym_of_ast(), mk_id(), xyyz::next, NULL, pass_sym_of_ast(), proc_arginfo(), S_EXPR, SST_ASTG, SST_ASTP, SST_IDP, SST_SYMP, xyyz::stkp, stktop, SYMNAME, and xyyz::t.
Referenced by ptrfunc_call(), and ptrsubr_call().
func_call()
int func_call (SST * stktop, ITEM * list)
Definition at line 1481 of file semfunc.c.
References ast, func_call2(), generic_func(), IS_TBP, list, memsym_of_ast(), NOSYM, resolve_fwd_ref(), sptr, SST_ASTG, SST_SYMG, and stktop.
Referenced by mkexpr1(), and mkvarref().
func_call2()
int func_call2 (SST * stktop, ITEM * list, int flag)
Write ILMs to call a function.
Parameters
stktop function to call
list arguments to pass to function
flag set if called from a generic resolution routine
Definition at line 791 of file semfunc.c.
References A_TKNP, add_auto_dealloc(), add_p_dealloc_item(), add_stmt(), add_stmt_before(), SEM::alloc_std, allocatable_member(), ARG_AST, ARG_STK, argt, ARGT_ARG, SEM::arrfn, assn(), ast, astb, aux, byvalue_ref_arg(), SEM::call_std, carg, check_arguments(), chkarg(), CNULL, count, count_actuals(), count_formals(), dt, STB::dt_cmplx, STB::dt_int, STB::dt_log, STB::dt_real, SEM::dtemps, DTY, DTYG, dtype_with_shape(), error(), errwarn(), FALSE, find_byval_ref(), FREE, FUNCLINEG, gbl, gen_allocatable_result(), gen_and_assoc_tmp_ptr(), gen_array_result(), gen_char_result(), gen_finalized_result(), gen_pointer_result(), generic_tbp_func(), get_all_descriptors(), get_arr_temp(), get_byval(), get_implementation(), get_len_of_deferchar_ast(), get_next_sym(), get_specific_member(), get_static_descriptor(), get_sym_from_sst_if_available(), get_tbp_argno(), getcctmp_sc(), getitem(), i, ASTB::i0, SCN::id, inc_dummy_param(), init_byval(), init_derived_type(), INTENT_IN, INTENTG, is_iso_cloc(), is_iso_cptr(), is_ptr_arg(), IS_TBP, ITEM_END, itemp, SEM::last_std, list, AUX::list, make_kwd_str(), mem(), memsym_of_ast(), mk_argt(), mk_assn_stmt(), mk_convert(), mk_func_node(), mk_id(), mk_member(), mk_stmt(), mkarg(), mkshape(), SCN::name, name, need_tmp_retval(), new_ast(), NULL, OP_BYVAL, OP_REF, OP_VAL, PASS_BYVAL, pass_char_no_len(), pass_sym_of_ast(), SEM::proc_initializer, ASTB::ptr0, ref_entry(), replace_memsym_of_ast(), SEM::return_value, S_DERIVED, S_EXPR, S_IDENT, S_KEYWORD, S_LABEL, S_LVALUE, S_SCONST, S_TRIPLE, SEM::sc, scn, sem, sem_tempify(), set_descriptor_sc(), set_pass_objects(), SEM::sptr, SST_ASTG, SST_ASTP, SST_CVALG, SST_CVLENP, SST_DTYPEP, SST_ERRSYMP, SST_IDG, SST_IDP, SST_LSYMG, SST_SHAPEP, SST_SYMG, SST_SYMP, stb, STD_PREV, stktop, strlen(), sym_of_ast(), SYMNAME, tempify(), TY_CHAR, TY_CMPLX, TY_INT, TY_LOG, TY_REAL, STB::user, void(), and XBIT.
Referenced by defined_operator(), func_call(), generic_func(), and is_intrinsic_opr().
gen_allocatable_result()
static int gen_allocatable_result (int array_value, int dscptr, int nactuals, LOGICAL is_derived, int func_sptr) static
Definition at line 2173 of file semfunc.c.
References STB::curr_scope, dt, DTY, dup_array_dtype(), dup_sym(), fix_character_length(), gbl, get_all_descriptors(), get_next_sym(), get_static_descriptor(), mk_id(), NULL, ref_based_object_sc(), SEM::sc, sem, set_descriptor_sc(), stb, sym_get_ptr(), and SYMNAME.
Referenced by func_call2(), and ptrfunc_call().
gen_and_assoc_tmp_ptr()
static int gen_and_assoc_tmp_ptr (SST * sst_actual, int std) static
Definition at line 664 of file semfunc.c.
References add_ptr_assign(), add_stmt(), assert, ast, SEM::dtemps, DTY, dup_array_dtype(), get_all_descriptors(), get_static_descriptor(), get_sym_from_sst_if_available(), getcctmp_sc(), mk_id(), S_EXPR, sem, sem_tempify(), SST_ASTG, SST_IDG, std, sym_of_ast(), and void().
Referenced by func_call2(), and subr_call2().
gen_array_result()
static int gen_array_result (int array_value, int dscptr, int nactuals, LOGICAL is_derived, int callee) static
Definition at line 2275 of file semfunc.c.
References AD_ADJARR, AD_DPTR, AD_LWBD, AD_NUMDIM, AD_UPBD, SEM::arrdim, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), astb, aux, ASTB::bnd, SEM::bounds, STB::curr_scope, AUX::dpdsc_base, dt, DTY, dup_sym(), first_hash(), gbl, gen_allocate_array(), get_next_sym(), get_symtype(), host, i, mk_arrdsc(), mk_id(), SEM::modhost_entry, SEM::modhost_proc, NULL, ASTB::one, precompute_arg_intrin(), precompute_args(), ref_based_object_sc(), replace_arguments(), replace_formal_triples(), S_NULL, SEM::sc, sem, small_enough(), stb, and SYMNAME.
Referenced by func_call2(), and ptrfunc_call().
gen_call_class_obj_size()
static int gen_call_class_obj_size (int sptr) static
Definition at line 5619 of file semfunc.c.
References arg, argt, ARGT_ARG, ast, gbl, get_static_type_descriptor(), get_type_descr_arg(), mk_argt(), mk_func_node(), mk_id(), mkRteRtnNm(), RTE_class_obj_size, sptr, and sym_mkfunc_nodesc().
Referenced by ref_pd().
gen_char_result()
static int gen_char_result (int fval, int dscptr, int nactuals) static
Definition at line 2451 of file semfunc.c.
References A_OPTYPEG, ARGT_ARG, ast_intr(), ast_rewrite(), ast_unvisit(), ast_visit(), astb, ASTB::bnd, dt, DTY, ASTB::dtype, dup_array_dtype(), get_ch_temp(), get_type(), len, mk_id(), replace_arguments(), and TY_CHAR.
Referenced by func_call2(), and ptrfunc_call().
gen_finalized_result()
static int gen_finalized_result (int fval, int func_sptr) static
If applicable, generate finalization code for function result.
Parameters
fval is the result symbol.
func_sptr is the function symbol table pointer
Returns
the result symbol; either fval or a new result symbol.
Definition at line 752 of file semfunc.c.
References add_stmt(), declsym(), gen_finalization_for_sym(), get_next_sym(), getsymbol(), has_finalized_component(), init_derived_type(), insert_sym(), mk_stmt(), NULL, std, SYMNAME, and TRUE.
Referenced by func_call2(), and ptrfunc_call().
gen_init_intrin_call()
static void gen_init_intrin_call (SST * stkp, int pdsym, int argt_count, int dtype, int elemental) static
Definition at line 4035 of file semfunc.c.
References A_OPTYPEP, ARG_AST, ARG_STK, argt, ARGT_ARG, ast, astb, DTY, i, ASTB::i0, mk_argt(), mk_array_type(), mk_func_node(), mk_id(), mkarg(), s, S_ACONST, S_EXPR, S_IDENT, SST_ASTP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_SHAPEG, void(), and XFR_ARGAST.
Referenced by ref_intrin(), and ref_pd().
gen_newer_intrin()
static int gen_newer_intrin (int sptrgenr, int dtype) static
Definition at line 4089 of file semfunc.c.
References DT_ISCMPLX, DTY, getsymbol(), GREALG, ILMG, ILMP, interr(), NEW_INTRIN, sptr, STANDARD_MAXIDLEN, SYMNAME, TY_CMPLX, and TY_DCMPLX.
Referenced by ref_intrin().
gen_pointer_result()
static int gen_pointer_result (int array_value, int dscptr, int nactuals, LOGICAL is_derived, int func_sptr) static
Definition at line 2107 of file semfunc.c.
References add_auto_len(), STB::curr_scope, ddt(), DDTG, dt, DTY, dup_array_dtype(), dup_sym(), fix_character_length(), gbl, get_all_descriptors(), get_next_sym(), get_static_descriptor(), mk_id(), NULL, ref_based_object(), stb, SYMNAME, TY_CHAR, and TY_NCHAR.
Referenced by func_call2(), and ptrfunc_call().
generic_tbp_has_pass_and_nopass()
int generic_tbp_has_pass_and_nopass (int dtype, int sptr)
Definition at line 2963 of file semfunc.c.
References DTY, generic_tbp_has_pass_and_nopass(), mem(), NOSYM, sptr, and SYMNAME.
Referenced by check_defined_io2(), find_best_generic(), generic_tbp_has_pass_and_nopass(), get_generic_tbp_pass_or_nopass(), semant2(), and semant3().
get_byval()
int get_byval (int func_sptr, int param_sptr)
Return true if param is pass by value.
Definition at line 457 of file semfunc.c.
References find_byval_ref(), and PASS_BYVAL.
Referenced by func_call2(), handle_arguments(), ptrfunc_call(), and subr_call2().
get_generic_member()
int get_generic_member (int dtype, int sptr)
Definition at line 2857 of file semfunc.c.
References DTY, get_generic_member(), mem(), NOSYM, sptr, and SYMNAME.
Referenced by check_defined_io2(), chk_arguments(), find_best_generic(), find_operator(), and get_generic_member().
get_generic_member2()
int get_generic_member2 (int dtype, int sptr, int argcnt, int * argno)
Definition at line 2888 of file semfunc.c.
References aux, AUX::dpdsc_base, DTY, eq_dtype2(), func, get_generic_member2(), get_implementation(), i, mem(), NOSYM, NULL, pass_arg, proc_arginfo(), sptr, and SYMNAME.
Referenced by get_generic_member2(), semant2(), and semant3().
get_generic_tbp_pass_or_nopass()
int get_generic_tbp_pass_or_nopass (int dtype, int sptr, int flag)
Definition at line 2998 of file semfunc.c.
References DTY, generic_tbp_has_pass_and_nopass(), mem(), NOSYM, sptr, and SYMNAME.
Referenced by semant2(), and semant3().
get_implementation()
int get_implementation (int dtype, int orig_sptr, int flag, int * memout)
For type bound procedures, find the implementation for the type bound procedure binding name in dtype.
If flag is set, then we check to see if we're accessing a PRIVATE type bound procedure. If so, we issue an error message.
Parameters
dtype is the derived type record that we are searching.
orig_sptr is the symbol table pointer of the binding name of the type bound procedure to look up.
flag is set to check for accessing a PRIVATE type bound procedure.
memout if set, the function will store the type bound procedure symbol table pointer in this pointer argument.
Returns
a symbol table pointer to the type bound procedure implementation; otherwise 0 (if not found).
Definition at line 3106 of file semfunc.c.
References DTY, error(), find_by_name_stype_arg(), gbl, get_implementation(), get_tbp(), mem(), NOSYM, queue_tbp(), scope, sem, sptr, strlen(), suffix, SYMNAME, TBP_FORCE_RESOLVE, and SEM::which_pass.
Referenced by check_defined_io2(), completeTbp(), find_best_generic(), find_operator(), func_call2(), get_defined_io_call(), get_generic_member2(), get_implementation(), get_tbp_argno(), is_intrinsic_opr(), lower_function(), nml_emit_desc(), proc_arginfo(), resolveGeneric(), resolveImp(), semant2(), semant3(), semCheckTbp(), and subr_call2().
get_specific_member()
int get_specific_member (int dtype, int sptr)
Definition at line 3033 of file semfunc.c.
References DTY, get_specific_member(), mem(), NOSYM, sptr, and SYMNAME.
Referenced by check_defined_io2(), find_best_generic(), find_operator(), func_call2(), get_specific_member(), lower_function(), lower_symbol(), proc_arginfo(), resolveGeneric(), semant2(), semant3(), and semCheckTbp().
get_static_type_descriptor()
int get_static_type_descriptor (int sptr)
Return the "static type descriptor" for object sptr. The static type descriptor holds the "declared type" of an object.
Definition at line 123 of file semfunc.c.
References dt, DTY, FALSE, FLANG_FALLTHROUGH, get_dtype_init_template(), get_static_descriptor(), get_struct_initialization_tree(), get_struct_members(), get_struct_tag_sptr(), NOSYM, set_descriptor_class(), sptr, sym_is_refd(), and TRUE.
Referenced by _constructf90(), check_alloc_ptr_type(), check_pointer_type(), gen_call_class_obj_size(), gen_finalization_for_sym(), genPolyAsn(), get_sdsc_ast(), get_type_descr_arg(), get_type_descr_arg2(), get_unl_poly_sym(), init_derived_type(), lower_function(), lower_stmt(), ref_pd(), resolveTbps(), semant1(), semant3(), set_type_in_descriptor(), and transform_call().
get_sym_from_sst_if_available()
static int get_sym_from_sst_if_available (SST * sst_actual) static
Definition at line 619 of file semfunc.c.
References mkarg(), S_DERIVED, S_IDENT, S_LVALUE, S_SCONST, sptr, SST_IDG, SST_LSYMG, SST_SYMG, and void().
Referenced by func_call2(), gen_and_assoc_tmp_ptr(), is_ptr_arg(), and subr_call2().
get_tbp()
static int get_tbp (int sptr) static
Definition at line 2774 of file semfunc.c.
References getsymf(), len, name, sptr, strlen(), and SYMNAME.
Referenced by get_implementation().
get_tbp_argno()
int get_tbp_argno (int sptr, int dty)
Definition at line 2801 of file semfunc.c.
References assert, error(), find_dummy_position(), first, gbl, get_implementation(), get_next_hash_link(), getitem(), len, mem(), name, NOSYM, proc_arginfo(), sptr, strlen(), SYMNAME, and test_scope().
Referenced by func_call2(), handle_arguments(), is_intrinsic_opr(), lower_function(), semant2(), semant3(), and subr_call2().
get_type_descr_arg()
int get_type_descr_arg (int func_sptr, int arg)
Return the type descriptor associated with arg (and func_sptr when arg is a dummy argument of routine func_sptr).
Definition at line 223 of file semfunc.c.
References arg, assert, DTY, gbl, get_static_descriptor(), get_static_type_descriptor(), get_type_descr_dummy(), needs_descriptor(), NOSYM, and sptr.
Referenced by check_pointer_type(), gen_call_class_obj_size(), gen_finalization_for_sym(), gen_poly_element_arg(), get_descr_arg(), get_sdsc_ast(), handle_arguments(), lower_data_stmts(), lower_function(), lower_stmt(), ref_pd(), semant3(), set_type_in_descriptor(), and transform_call().
get_type_descr_arg2()
int get_type_descr_arg2 (int func_sptr, int arg)
Same as get_type_descr_arg(), but do not perform error check.
Definition at line 262 of file semfunc.c.
References arg, get_descriptor_sc(), get_static_descriptor(), get_static_type_descriptor(), get_type_descr_dummy(), needs_descriptor(), set_descriptor_sc(), and sptr.
Referenced by semant3(), and transform_call().
get_type_descr_dummy()
static int get_type_descr_dummy (int sptr, int arg) static
Definition at line 187 of file semfunc.c.
References arg, aux, count, AUX::dpdsc_base, FALSE, fix_class_args(), i, needs_descriptor(), sptr, SYMNAME, and TRUE.
Referenced by get_type_descr_arg(), and get_type_descr_arg2().
getMergeSym()
static int getMergeSym (int dt, int ikind) static
Definition at line 11251 of file semfunc.c.
References dt, DTY, interr(), mkRteRtnNm(), RTE_mergec, RTE_mergecha, RTE_merged, RTE_mergedc, RTE_mergedt, RTE_mergei, RTE_mergei1, RTE_mergei2, RTE_mergei8, RTE_mergel, RTE_mergel1, RTE_mergel2, RTE_mergel8, RTE_mergeq, RTE_merger, sym_mkfunc_nodesc(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, and TY_SLOG.
Referenced by ref_pd().
in_kernel_region()
LOGICAL in_kernel_region (void)
Definition at line 594 of file semfunc.c.
References df, DI_ACCDO, DI_ACCKERNELSDO, DI_ACCKERNELSLOOP, DI_ACCLOOP, DI_ACCPARALLELDO, DI_ACCPARALLELLOOP, DI_ACCREGDO, DI_ACCREGLOOP, DI_ACCSERIALLOOP, DI_CUFKERNEL, DI_ID, SEM::doif_depth, FALSE, sem, and TRUE.
inc_dummy_param()
static int inc_dummy_param (int func_sptr) static
Definition at line 437 of file semfunc.c.
References aux, byval_dscptr, byval_func_ptr, byval_paramct, and AUX::dpdsc_base.
Referenced by func_call2(), ptrfunc_call(), ptrsubr_call(), and subr_call2().
init_byval()
static void init_byval () static
Definition at line 426 of file semfunc.c.
References byval_dscptr, byval_func_ptr, and byval_paramct.
Referenced by func_call2(), ptrfunc_call(), ptrsubr_call(), and subr_call2().
is_ptr_arg()
static LOGICAL is_ptr_arg (SST * sst_actual) static
Definition at line 636 of file semfunc.c.
References A_OPTYPEG, ast, get_sym_from_sst_if_available(), memsym_of_ast(), NOSYM, S_EXPR, sptr, SST_ASTG, SST_IDG, and TRUE.
Referenced by func_call2(), and subr_call2().
mk_array_type()
static int mk_array_type (int arr_spec_dt, int base_dtype) static
Definition at line 12195 of file semfunc.c.
References AD_DPTR, AD_LWAST, AD_NUMDIM, AD_UPAST, SEM::arrdim, SEM::bounds, SEM::dinit_error, DTY, error(), gbl, get_int_cval(), i, mk_arrdsc(), NULL, rank, S_CONST, sem, and TRUE.
Referenced by gen_init_intrin_call().
need_tmp_retval()
static LOGICAL need_tmp_retval (int func_sptr, int param_dummy) static
Definition at line 710 of file semfunc.c.
References allocatable_member(), ARG_STK, DTY, FALSE, SST_ASTG, and TRUE.
Referenced by func_call2(), and ptrfunc_call().
pass_char_no_len()
static int pass_char_no_len (int func_sptr, int param_sptr) static
Definition at line 293 of file semfunc.c.
References find_byval_ref(), and PASS_BYREF_NO_LEN.
Referenced by func_call2(), ptrfunc_call(), ptrsubr_call(), and subr_call2().
precompute_arg_intrin()
static void precompute_arg_intrin (int dscptr, int nactuals) static
Definition at line 2486 of file semfunc.c.
References AD_ADJARR, AD_DEFER, AD_DPTR, AD_NOBOUNDS, ADD_NUMDIM, add_stmt(), arg, ARG_AST, ARG_STK, assn(), DTY, FALSE, get_arr_temp(), get_shape_arr_temp(), get_temp(), get_temp_dtype(), mk_assn_stmt(), mk_id(), SHD_NDIM, SST_ASTP, tmp, TRUE, and void().
Referenced by gen_array_result().
precompute_args()
static void precompute_args (int dscptr, int nactuals) static
Definition at line 2527 of file semfunc.c.
References add_stmt(), arg, ARG_AST, ARG_STK, assn(), DT_ISSCALAR, DTY, sem_tempify(), SST_ASTP, and void().
Referenced by gen_array_result().
ptrfunc_call()
int ptrfunc_call (SST * stktop, ITEM * list)
Definition at line 1529 of file semfunc.c.
References add_p_dealloc_item(), add_stmt(), add_typroc(), SEM::alloc_std, allocatable_member(), ARG_AST, ARG_STK, argt, ARGT_ARG, SEM::arrfn, assert, assn(), ast, astb, byvalue_ref_arg(), SEM::call_std, carg, chk_arguments(), chkarg(), CNULL, count, count_actuals(), count_formal_args(), dt, DTY, DTYG, dtype_with_shape(), error(), errwarn(), FALSE, find_byval_ref(), fix_proc_pointer_call(), FREE, gbl, gen_allocatable_result(), gen_array_result(), gen_char_result(), gen_finalized_result(), gen_pointer_result(), get_all_descriptors(), get_arr_temp(), get_byval(), get_next_sym(), get_static_descriptor(), i, ASTB::i0, SCN::id, inc_dummy_param(), init_byval(), init_derived_type(), is_array_dtype(), is_iso_cloc(), is_iso_cptr(), is_procedure_ptr(), ITEM_END, itemp, list, make_keyword_str(), memsym_of_ast(), mk_argt(), mk_func_node(), mk_id(), mk_member(), mkarg(), mkshape(), SCN::name, need_tmp_retval(), new_ast(), NULL, OP_BYVAL, OP_REF, OP_VAL, PASS_BYVAL, pass_char_no_len(), proc_arginfo(), ASTB::ptr0, ref_entry(), SEM::return_value, S_DERIVED, S_EXPR, S_IDENT, S_KEYWORD, S_LABEL, S_LVALUE, S_SCONST, S_TRIPLE, SEM::sc, scn, sem, sem_tempify(), set_descriptor_sc(), SEM::sptr, SST_ASTG, SST_ASTP, SST_CVALG, SST_CVLENP, SST_DTYPEP, SST_ERRSYMP, SST_IDG, SST_IDP, SST_LSYMG, SST_SHAPEP, SST_SYMG, STD_PREV, stktop, SYMNAME, void(), and XBIT.
Referenced by mkvarref().
ptrsubr_call()
void ptrsubr_call (SST * stktop, ITEM * list)
Definition at line 3844 of file semfunc.c.
References ARG_AST, ARG_STK, argt, ARGT_ARG, assert, ast, astb, aux, byvalue_ref_arg(), carg, chk_arguments(), chkarg(), CNULL, count, count_actuals(), count_formal_args(), DTY, error(), fix_proc_pointer_call(), flg, FREE, gbl, i, ASTB::i0, SCN::id, inc_dummy_param(), init_byval(), is_iso_cloc(), is_iso_cptr(), is_procedure_ptr(), ITEM_END, itemp, list, AUX::list, make_keyword_str(), mk_argt(), mk_func_node(), mk_id(), mkarg(), SCN::name, NULL, OP_REF, pass_char_no_len(), proc_arginfo(), ASTB::ptr0, rewrite_cptr_references(), S_DERIVED, S_IDENT, S_KEYWORD, S_LVALUE, S_SCONST, scn, sptr, SST_ASTG, SST_ASTP, SST_CVALG, SST_IDG, SST_LSYMG, SST_SYMG, stktop, SYMNAME, void(), FLG::xref, and xrefput().
Referenced by semant3().
ref_intrin()
int ref_intrin (SST * stktop, ITEM * list)
Handle Generic and Intrinsic function calls.
Definition at line 4158 of file semfunc.c.
References A_OPTYPEP, AD_ADJARR, AD_DEFER, AD_DPTR, AD_NOBOUNDS, ADD_NUMDIM, add_stmt(), and64(), AOP_AND, AOP_MAX, AOP_MIN, AOP_OR, AOP_XOR, ARG_AST, ARG_STK, argt, ARGT_ARG, assert, ast, bits_in(), chktyp(), cmp64(), cmp_mod_scope(), cngcon(), cngtyp(), CNULL, const_fold(), CONVAL2G, count, STB::dbl0, STB::dblhalf, STB::dblm0, ddt(), DDTG, SEM::dinit_data, div64(), DT_CMPLX, DT_DBLE, DT_DCMPLX, STB::dt_int, DT_INT, STB::dt_log, DT_LOG, DT_PTR, STB::dt_real, DTY, DTYG, dup_array_dtype(), error(), FALSE, findByNameStypeScope(), STB::firstusym, fix_term(), FLANG_FALLTHROUGH, STB::flt0, STB::flthalf, STB::fltm0, gbl, GBL_CURRFUNC, gen_init_intrin_call(), gen_newer_intrin(), generic_func(), get_arr_temp(), GET_CVAL_ARG, GET_DBLE, get_iso_ptrtype(), get_kwd_args(), GET_QUAD, get_shape_arr_temp(), get_temp(), get_temp_dtype(), getcon(), getstring(), GREALG, i, STB::i0, ILMG, IN_MODULE, intast_sym, interr(), is_sst_const(), ITEM_END, STB::k0, kanji_char(), KWDARGSTR, list, mk_argt(), mk_cval(), mk_cval1(), mk_func_node(), mk_id(), mkarg(), mkexpr(), mkident(), mklvalue(), mkRteRtnNm(), mkvarref(), SEM::mpaccatomic, mul64(), STB::n_base, neg64(), newsym(), xyyz::next, NOSYM, not64(), NULL, OP_ADD, OP_CMP, OP_SUB, or64(), STB::quad0, rank_of_ast(), res, SEM::rmw_op, RTE_amodulov, RTE_dmodulov, RTE_i8modulov, RTE_imodulov, RTE_max, RTE_min, RTE_modulov, RTE_qmodulov, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_TRIPLE, sc_local_passbyvalue(), SCFTN_FALSE, SCFTN_TRUE, sem, set_kind_result(), SHD_NDIM, size_of(), sptr, SST_ASTG, SST_ASTP, SST_CVALP, SST_CVLENP, SST_DTYPEG, SST_DTYPEP, SST_ERRSYMP, SST_IDG, SST_IDP, SST_ISNONDECC, SST_SHAPEG, SST_SHAPEP, SST_SYMG, SST_SYMP, stb, xyyz::stkp, stktop, string_length(), sub64(), sym_mkfunc_nodesc(), SYMNAME, xyyz::t, tempify(), tmp, TRUE, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, STB::user, void(), XBIT, xdabsv(), xdble(), xdcmp(), xdmul(), xdneg(), xfabsv(), xfadd(), xfcmp(), xfneg(), XFR_ARGAST, xfsub(), xor64(), and xqabsv().
Referenced by gen_reduction(), generic_func(), and mkvarref().
ref_intrin_subr()
static void ref_intrin_subr (SST * stktop, ITEM * list) static
Definition at line 12003 of file semfunc.c.
References _e74_cnt, _e74_kwd, _e74_l, _e74_pos, _e74_sym, _e74_u, A_ARGCNTP, A_OPTYPEP, ARG_AST, ARG_STK, argt, ARGT_ARG, ast, CNULL, count, DT_ISINT, DTY, e74_arg(), E74_ARG, e74_cnt(), E74_CNT, error(), find_pointer_variable(), gbl, get_kwd_args(), i, is_iso_c_funloc(), is_iso_c_funptr(), is_iso_c_loc(), is_iso_c_ptr(), is_procedure_ptr(), is_varref(), ITEM_END, KWDARGSTR, list, mk_argt(), mk_id(), mk_stmt(), mkarg(), newsym(), xyyz::next, NULL, sptr, SST_ASTP, SST_DTYPEG, SST_SYMG, SST_SYMP, stktop, subr_call(), SYMNAME, void(), and XFR_ARGAST.
Referenced by subr_call2().
ref_pd()
int ref_pd (SST * stktop, ITEM * list)
Handle calls to Predeclared functions.
Parameters
stktop function to call
list arguments to pass to function
Definition at line 5653 of file semfunc.c.
References _adjustl(), _adjustr(), _e74_cnt, _e74_kwd, _e74_l, _e74_pos, _e74_sym, _e74_u, _index(), _len_trim(), _repeat(), _scan(), _selected_char_kind(), _trim(), _verify(), A_OPTYPEG, A_OPTYPEP, AC_ACONST, AD_DEFER, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_NUMDIM, AD_NUMELM, AD_UPAST, AD_UPBD, add64(), add_arg(), ADD_LWAST, ADD_NUMDIM, ADD_NUMELM, add_shape_rank(), add_shape_spec(), add_stmt(), ALIGN, alignment(), any_pointer_source(), ARG_AST, ARG_STK, SEM::argpos, ARGS_NUMBER, argt, ARGT_ARG, SEM::arrdim, ASD_NDIM, ASD_SUBS, assumshp, ast, _acl::ast, ast_intr(), ast_is_sym(), astb, atoxd(), aux, baseptr, begin_call(), bits_in(), BITS_PER_BYTE, ASTB::bnd, SEM::bounds, C90_EPSILON, C90_TINY, casttyp(), check_dim_error(), check_member(), chkshape(), chktyp(), FLG::cmdline, cmp64(), cngcon(), cngtyp(), CNULL, conform_shape(), const_fold(), construct_acl_from_ast(), CONVAL2G, convert_int(), count, STB::dbl0, STB::dblhalf, DDTG, dim, SEM::dinit_data, SEM::dinit_error, dont_issue_assumedsize_error, STB::dt_cmplx, DT_CMPLX, DT_DBLE, DT_FLOAT, AUX::dt_iarray, STB::dt_int, DT_INT, DT_ISCMPLX_ARR, DT_ISINT, DT_ISINT_ARR, DT_ISLOG, DT_ISLOG_ARR, DT_ISNUMERIC, DT_ISNUMERIC_ARR, DT_ISREAL, DT_ISREAL_ARR, STB::dt_log, DT_LOG, DT_PTR, STB::dt_real, DT_REAL, SEM::dtemps, DTY, DTYG, ASTB::dtype, dtype_with_shape(), dup_array_dtype(), e, e74_arg(), E74_ARG, e74_cnt(), E74_CNT, elem_size_of_ast(), EPSILON_BIT96_127, eq_dtype(), eq_dtype2(), ERR170, error(), errsev(), eval_init_expr(), evl_kwd_args(), extent_of_shape(), FALSE, find_pointer_target(), find_pointer_variable(), fix_term(), FLANG_FALLTHROUGH, flg, STB::flt0, STB::flthalf, gbl, gen_call_class_obj_size(), gen_init_intrin_call(), gen_set_type(), GET_ACL, get_arr_temp(), get_array_dtype(), get_ch_temp(), get_int_cval(), get_isz_cval(), get_kwd_args(), get_len_parm_by_number(), get_member_descriptor(), get_sst_cval(), get_static_descriptor(), get_static_type_descriptor(), get_temp(), get_type(), get_type_descr_arg(), get_version_string(), getccsym(), getcctmp_sc(), getcon(), getMergeSym(), getstring(), getsymbol(), i, STB::i0, ASTB::i0, ASTB::i1, _acl::id, if(), increase_shape(), INSIDE_STRUCT, intast_sym, SEM::interface, interr(), _acl::is_const, is_iso_c_funptr(), is_iso_cptr(), is_procedure_ptr(), is_sst_const(), is_varref(), ISZ_T, ITEM_END, kind_of(), KWDARGSTR, lbound_of_shape(), len, list, MAX_ARGS_NUMBER, MAX_EXP_OF_QMANTISSA, memsym_of_ast(), MIN_ARGS_NUMBER, MIN_QUAD_VALUE_BIT96_127, mk_argt(), mk_arrdsc(), mk_assn_stmt(), mk_binop(), mk_bnd_int(), mk_cnst(), mk_coercion_func(), mk_convert(), mk_cval(), mk_cval1(), mk_extent(), mk_func_node(), mk_id(), mk_isz_cval(), mk_member(), mk_shape(), mk_stmt(), mk_subscr(), mk_substr(), mk_unop(), mkarg(), mkexpr(), mkRteRtnNm(), mkshape(), mkvarref(), MMAX_MANTI_BIT0_31, MMAX_MANTI_BIT32_63, MMAX_MANTI_BIT64_95, MMAX_MANTI_BIT96_127, STB::n_base, name, need_alloc_ch_temp(), neg64(), newsym(), xyyz::next, _acl::next, nsubs, NULL, ASTB::one, OP_ADD, OP_CMP, OP_DIV, OP_GE, OP_MUL, OP_SUB, OP_VAL, pdtype, ASTB::ptr0, STB::quad0, STB::quadhalf, QVM4_SIZE, rank, rank_of_ast(), reduc_shape(), refsym(), res, RTE_cmd_arg_cnt, RTE_expon, RTE_expond, RTE_exponq, RTE_extends_type_of, RTE_frac, RTE_fracd, RTE_fracq, RTE_hypot, RTE_hypotd, RTE_hypotq, RTE_ilen, RTE_indexa, RTE_is_iostat_end, RTE_is_iostat_eor, RTE_lb, RTE_lb1, RTE_lb2, RTE_lb4, RTE_lb8, RTE_lba, RTE_lba1, RTE_lba2, RTE_lba4, RTE_lba8, RTE_lbaz, RTE_lbaz1, RTE_lbaz2, RTE_lbaz4, RTE_lbaz8, RTE_lbound1Dsc, RTE_lbound2Dsc, RTE_lbound4Dsc, RTE_lbound8Dsc, RTE_lbounda1Dsc, RTE_lbounda2Dsc, RTE_lbounda4Dsc, RTE_lbounda8Dsc, RTE_lboundaDsc, RTE_lboundaz1Dsc, RTE_lboundaz2Dsc, RTE_lboundaz4Dsc, RTE_lboundaz8Dsc, RTE_lboundazDsc, RTE_lboundDsc, RTE_lena, RTE_nearest, RTE_nearestd, RTE_nearestq, RTE_nrepeat, RTE_nscan, RTE_number_of_processors, RTE_nverify, RTE_present, RTE_present_ptr, RTE_presentc, RTE_processors_rank, RTE_repeata, RTE_rrspacing, RTE_rrspacingd, RTE_rrspacingq, RTE_same_type_as, RTE_scale, RTE_scaled, RTE_scaleq, RTE_scana, RTE_sel_char_kinda, RTE_sel_int_kind, RTE_sel_real_kind, RTE_setexp, RTE_setexpd, RTE_setexpq, RTE_shape, RTE_shape1, RTE_shape2, RTE_shape4, RTE_shape8, RTE_shapeDsc, RTE_size, RTE_sizeDsc, RTE_spacing, RTE_spacingd, RTE_spacingq, RTE_ub, RTE_ub1, RTE_ub2, RTE_ub4, RTE_ub8, RTE_uba, RTE_uba1, RTE_uba2, RTE_uba4, RTE_uba8, RTE_ubaz, RTE_ubaz1, RTE_ubaz2, RTE_ubaz4, RTE_ubaz8, RTE_ubound1Dsc, RTE_ubound2Dsc, RTE_ubound4Dsc, RTE_ubound8Dsc, RTE_ubounda1Dsc, RTE_ubounda2Dsc, RTE_ubounda4Dsc, RTE_ubounda8Dsc, RTE_uboundaDsc, RTE_uboundaz1Dsc, RTE_uboundaz2Dsc, RTE_uboundaz4Dsc, RTE_uboundaz8Dsc, RTE_uboundazDsc, RTE_uboundDsc, RTE_verifya, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_TRIPLE, SEM::sc, SCFTN_FALSE, select_kind(), sem, set_kind_result(), set_shape_result(), SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, shf64(), size, size_ast(), size_ast_of(), size_of(), size_of_ast(), sptr, src, SST_ACLG, SST_ASTG, SST_ASTP, SST_CVALG, SST_CVALP, SST_CVLENP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_ISNONDECC, SST_SHAPEG, SST_SHAPEP, SST_SYMG, SST_SYMP, FLG::standard, stb, std, STD_PREV, xyyz::stkp, stktop, string_length(), strlen(), _acl::subc, sym_mkfunc(), sym_mkfunc_nodesc(), sym_mkfunc_nodesc_expst(), sym_mknproc(), sym_of_ast(), SYMNAME, xyyz::t, t1, t2, target_kind(), tmp, TRUE, TY_BINT, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TYPELESS, _acl::u1, ubound_of_shape(), STB::user, ushf64(), val, void(), SEM::which_pass, XBIT, xfadd(), xfcmp(), XFR_ARGAST, xfsub(), xor64(), zero, and ASTB::zero.
Referenced by generic_func(), mkexpr1(), and mkvarref().
ref_pd_subr()
static void ref_pd_subr (SST * stktop, ITEM * list) static
Definition at line 11315 of file semfunc.c.
References _e74_cnt, _e74_kwd, _e74_l, _e74_pos, _e74_sym, _e74_u, A_ARGCNTP, A_OPTYPEP, add_arg(), ARG_AST, ARG_STK, argt, ARGT_ARG, ast, astb, begin_call(), CNULL, conform_shape(), count, DDTG, STB::dt_int, DT_INT, DT_ISINT, DT_ISINT_ARR, DT_ISREAL, STB::dt_log, DT_REAL, DTY, e74_arg(), E74_ARG, e74_cnt(), E74_CNT, eq_dtype2(), error(), evl_kwd_args(), gbl, get_kwd_args(), i, ASTB::i0, is_varref(), ITEM_END, KWDARGSTR, list, memsym_of_ast(), mk_argt(), mk_convert(), mk_id(), mk_stmt(), mkarg(), mkexpr(), mkRteRtnNm(), newsym(), xyyz::next, NULL, ASTB::ptr0c, rank_of(), rank_of_ast(), RTE_exit, sptr, SST_ASTG, SST_ASTP, SST_DTYPEG, SST_SHAPEG, SST_SYMG, SST_SYMP, stb, stktop, subr_call(), sym_mkfunc_nodesc(), sym_of_ast(), SYMNAME, TY_CHAR, TY_NCHAR, STB::user, void(), and XFR_ARGAST.
Referenced by subr_call2().
replace_arguments()
static void replace_arguments (int dscptr, int nactuals) static
Definition at line 2736 of file semfunc.c.
References arg, ARG_AST, ARG_STK, ast_replace(), aux, check_member(), AUX::dpdsc_base, get_all_descriptors(), get_static_descriptor(), and mk_id().
Referenced by fix_character_length(), gen_array_result(), and gen_char_result().
replace_formal_triples()
static void replace_formal_triples (int ast, int dscptr, int nactuals) static
Definition at line 2695 of file semfunc.c.
References A_ARGCNTG, argt, ARGT_ARG, ast, ast_visit(), cnt, i, replace_formal_triples(), rewrite_subscr(), and rewrite_triples().
Referenced by gen_array_result(), and replace_formal_triples().
resolve_fwd_ref()
static void resolve_fwd_ref (int ref) static
Resolve forward references in function func_call().
Used by func_call() to resolve any forward refs we may encounter since resolve_fwd_refs() in semutil.c gets called after we finish processing this function. We also want to check to see if this reference resolves to a generic procedure.
Definition at line 1437 of file semfunc.c.
References first_hash(), and stb.
Referenced by func_call().
rewrite_cptr_references()
static int rewrite_cptr_references (int ast) static
Definition at line 466 of file semfunc.c.
References ast, DTY, is_iso_cptr(), mk_id(), mk_member(), and new_ast().
Referenced by byvalue_ref_arg(), ptrsubr_call(), and subr_call2().
rewrite_subscr()
static void rewrite_subscr (int ast_subscr, int dscptr, int nactuals) static
Definition at line 2606 of file semfunc.c.
References ASD_NDIM, ASD_SUBS, ast, ast_replace(), aux, AUX::dpdsc_base, flg, i, mk_subscr(), sptr, and subscr.
Referenced by replace_formal_triples().
rewrite_triples()
static void rewrite_triples (int ast_subscr, int dscptr, int nactuals) static
Definition at line 2549 of file semfunc.c.
References AD_DPTR, AD_EXTNTAST, AD_LWBD, AD_UPBD, arg, ARG_AST, ARG_STK, ASD_NDIM, ASD_SUBS, ast_replace(), aux, AUX::dpdsc_base, i, j, mk_triple(), ndim, and sub.
Referenced by replace_formal_triples().
sc_local_passbyvalue()
int sc_local_passbyvalue (int sptr, int func_sptr)
Return true if sptr is an SC_LOCAL and a pass by value parameter of func_sptr.
Definition at line 303 of file semfunc.c.
References aux, AUX::dpdsc_base, i, sptr, and SYMNAME.
Referenced by ref_intrin(), and semant2().
set_char_ref_val()
static int set_char_ref_val (int func, int param) static
Definition at line 329 of file semfunc.c.
References func, PASS_BYREF, PASS_BYREF_NO_LEN, and PASS_BYVAL.
Referenced by find_byval_ref().
set_kind_result()
static int set_kind_result (SST * stkp, int dt, int ty) static
Definition at line 12170 of file semfunc.c.
References ast, cngcon(), dt, DT_ISINT, get_int_cval(), get_sst_cval(), is_sst_const(), kind, S_EXPR, select_kind(), SST_ASTG, SST_DTYPEG, and SST_IDG.
Referenced by ref_intrin(), and ref_pd().
set_shape_result()
static int set_shape_result (int shape1, int shape2) static
Definition at line 12154 of file semfunc.c.
References conform_shape().
Referenced by ref_pd().
small_enough()
static int small_enough (ADSC * ad, int numdim) static
Definition at line 2242 of file semfunc.c.
References AD_LWBD, AD_UPBD, assert, get_isz_cval(), i, ISZ_T, lv, and size.
Referenced by gen_array_result().
subr_call()
void subr_call (SST * stktop, ITEM * list)
Definition at line 3746 of file semfunc.c.
References list, stktop, and subr_call2().
Referenced by ref_intrin_subr(), ref_pd_subr(), and semant3().
subr_call2()
void subr_call2 (SST * stktop, ITEM * list, int flag)
Write ILMs to call a subroutine.
Parameters
stktop function to call
list arguments to pass to function
flag set if called from a generic resolution routine
Definition at line 3256 of file semfunc.c.
References add_stmt(), ARG_AST, ARG_STK, argt, ARGT_ARG, assn(), ast, astb, aux, byvalue_ref_arg(), carg, check_arguments(), check_generic(), chkarg(), CNULL, count, count_actuals(), count_formals(), DTY, eq_dtype2(), error(), FALSE, findByNameStypeScope(), flg, FREE, gbl, gen_and_assoc_tmp_ptr(), generic_call(), generic_tbp_call(), get_byval(), get_implementation(), get_next_hash_link(), get_sym_from_sst_if_available(), get_tbp_argno(), getitem(), GSAMEG, i, ASTB::i0, SCN::id, inc_dummy_param(), init_byval(), INTENT_IN, INTENTG, IS_INTRINSIC, is_iso_cloc(), is_iso_cptr(), is_ptr_arg(), ITEM_END, itemp, SEM::last_std, list, AUX::list, make_kwd_str(), mem(), memsym_of_ast(), mk_argt(), mk_func_node(), mk_id(), mkarg(), SCN::name, name, newsym(), NOSYM, NULL, OP_REF, pass_char_no_len(), pass_sym_of_ast(), ASTB::ptr0, FLG::recursive, ref_intrin_subr(), ref_pd_subr(), replace_memsym_of_ast(), rewrite_cptr_references(), RU_SUBR, S_DERIVED, S_EXPR, S_IDENT, S_KEYWORD, S_LVALUE, S_SCONST, scn, sem, sem_tempify(), set_pass_objects(), sptr, SST_ASTG, SST_ASTP, SST_CVALG, SST_DTYPEG, SST_IDG, SST_LSYMG, SST_SYMG, SST_SYMP, stktop, strlen(), sym_of_ast(), SYMNAME, test_scope(), tk_match_arg(), void(), FLG::xref, and xrefput().
Referenced by generic_call(), is_intrinsic_opr(), semant3(), and subr_call().
Variable Documentation
_e74_cnt
int _e74_cnt static
Definition at line 83 of file semfunc.c.
Referenced by ref_intrin_subr(), ref_pd(), and ref_pd_subr().
_e74_kwd
char* _e74_kwd static
Definition at line 87 of file semfunc.c.
Referenced by ref_intrin_subr(), ref_pd(), and ref_pd_subr().
_e74_l
int _e74_l static
Definition at line 84 of file semfunc.c.
Referenced by ref_intrin_subr(), ref_pd(), and ref_pd_subr().
_e74_pos
int _e74_pos static
Definition at line 86 of file semfunc.c.
Referenced by ref_intrin_subr(), ref_pd(), and ref_pd_subr().
_e74_sym
int _e74_sym static
Definition at line 82 of file semfunc.c.
Referenced by ref_intrin_subr(), ref_pd(), and ref_pd_subr().
_e74_u
int _e74_u static
Definition at line 85 of file semfunc.c.
Referenced by ref_intrin_subr(), ref_pd(), and ref_pd_subr().
byval_dscptr
int byval_dscptr = 0 static
Definition at line 111 of file semfunc.c.
Referenced by inc_dummy_param(), and init_byval().
byval_func_ptr
int byval_func_ptr = 0 static
Definition at line 110 of file semfunc.c.
Referenced by inc_dummy_param(), and init_byval().
byval_paramct
int byval_paramct = 0 static
Definition at line 112 of file semfunc.c.
Referenced by inc_dummy_param(), and init_byval().
struct { ... } carg
Referenced by CMPLXFUNC_C(), count_actuals(), count_formal_args(), func_call2(), ptrfunc_call(), ptrsubr_call(), and subr_call2().
dont_issue_assumedsize_error
int dont_issue_assumedsize_error = 0
Definition at line 5646 of file semfunc.c.
Referenced by mkexpr1(), and ref_pd().
nargt
int nargt
Definition at line 38 of file semfunc.c.
nent
int nent
Definition at line 37 of file semfunc.c.