flang: semfunc2.c File Reference
semfunc2.c File Reference
Utility routines used by semantic analyzer.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "semant.h"
#include "scan.h"
#include "semstk.h"
#include "pd.h"
#include "machar.h"
#include "ast.h"
#include "rte.h"
#include "rtlRtns.h"
Classes
struct _arginfo
Information about statement function arguments.
struct _sfuse
Statement function used in the right-hand side.
struct _sfdsc
Statement function descriptor.
Typedefs
typedef struct _arginfo ARGINFO
Information about statement function arguments.
typedef struct _sfuse SFUSE
Statement function used in the right-hand side.
typedef struct _sfdsc SFDSC
Statement function descriptor.
Functions
static LOGICAL get_keyword_args (ITEM *list, int cnt, const char *kwdarg, int pod, int pass_pos)
Similar to get_kwd_args but can also specify a pass-object dummy argument.
static int get_fval_array (int)
static LOGICAL cmpat_arr_arg (int d1, int shape2)
Check conformance of two arrays, where the first array is described with a dtype record, and the second is described with a shape descriptor.
static void dump_stfunc (int sptr)
Write out statement function descriptor to debug file.
static void asn_sfuse (SFUSE *)
static void _non_private (int ast, int *dummy)
AST visitor function.
void set_pass_objects (int pos, int pod)
Set position of type-bound procedure passed object location.
int define_stfunc (int sptr, ITEM *argl, SST *estk)
Perform error checking and create statement function descriptor for statement function definition.
int ref_stfunc (SST *stktop, ITEM *args)
int mkarg (SST *stkptr, int *dtype)
Check and write ILMs for a subprogram argument.
int intrinsic_as_arg (int intr)
int chkarg (SST *stkptr, int *dtype)
Performing checking on an argument to determine if it needs to be "protected".
int tempify (SST *stkptr)
Allocate a temporary, assign it the value, and return the temp's base.
int ref_entry (int ent)
int select_gsame (int gnr)
Given a generic intrinsic, select the corresponding specific of the same name.
char * make_kwd_str (int ext)
Make a keyword string for a ST_PROC.
char * make_keyword_str (int paramct, int dpdsc)
Make a keyword string from the DPDSC auxiliary structure.
static int nz_digit_str (char *)
LOGICAL get_kwd_args (ITEM *list, int cnt, const char *kwdarg)
Extract the arguments from the semantic list into sem.argpos[] in positional order.
LOGICAL evl_kwd_args (ITEM *list, int cnt, const char *kwdarg)
Call get_kwd_args and evaluate each argument.
LOGICAL sum_scatter_args (ITEM *list, int cnt)
void defer_arg_chk (SPTR formal, SPTR actual, SPTR subprog, cmp_interface_flags flags, int lineno, bool performChk)
Process information for deferred interface argument checking in in the compat_arg_lists() function below.
static LOGICAL compat_arg_lists (int formal, int actual)
For arguments that are subprograms, check that their argument lists are compatible.
LOGICAL check_arguments (int ext, int count, ITEM *list, char *kwd_str)
Check arguments passed to a user subprogram which has an interface block. Its keyword string is available and is located by kwd_str.
LOGICAL chk_arguments (int ext, int count, ITEM *list, char *kwd_str, int paramct, int dpdsc, int callee, int *p_pass_pos)
Check arguments passed to a user subprogram which has an interface block. Its keyword string is available and is located by kwd_str.
LOGICAL ignore_tkr (int arg, int tkr)
LOGICAL ignore_tkr_all (int arg)
static int iface_arg (int, int, int)
int iface_intrinsic (int sptr)
Variables
static SFUSE * l_sfuse = NULL
List of statement functions used in a definition.
static SFUSE * end_sfuse = NULL
static ITEM * stfunc_argl
static int pass_position = 0
static int pass_object_dummy = 0
static LOGICAL user_subr = FALSE
Detailed Description
Utility routines used by semantic analyzer.
Fortran front-end utility routines used by Semantic Analyzer to process functions, subroutines, predeclareds, statement functions, etc.
Definition in file semfunc2.c.
Typedef Documentation
ARGINFO
typedef struct _arginfo ARGINFO
Information about statement function arguments.
SFDSC
typedef struct _sfdsc SFDSC
Statement function descriptor.
SFUSE
typedef struct _sfuse SFUSE
Statement function used in the right-hand side.
Function Documentation
_non_private()
static void _non_private (int ast, int * dummy) static
AST visitor function.
This is passed to ast_traverse() to add variables with add_non_private.
Definition at line 212 of file semfunc2.c.
References add_non_private(), arg, ast, flg, ITEM_END, itemp, FLG::smp, sptr, SST_SYMG, ST_ISVAR, and stfunc_argl.
Referenced by define_stfunc().
asn_sfuse()
static void asn_sfuse (SFUSE * l_use) static
Definition at line 466 of file semfunc2.c.
References _arginfo::actual, add_stmt(), asn_sfuse(), ast, ast_clear_repl(), ast_replace(), ast_rewrite(), dbg_print_ast(), DBGBIT, _arginfo::dtype, dump_ast_tree(), _arginfo::formal, gbl, get_temp(), mk_assn_stmt(), mk_id(), _arginfo::next, _sfuse::next, _sfuse::node, NULL, _arginfo::refd, _arginfo::save, SYMNAME, tmp, and void().
Referenced by asn_sfuse(), and ref_stfunc().
check_arguments()
LOGICAL check_arguments (int ext, int count, ITEM * list, char * kwd_str)
Check arguments passed to a user subprogram which has an interface block. Its keyword string is available and is located by kwd_str.
Definition at line 2125 of file semfunc2.c.
References chk_arguments(), count, list, and NULL.
Referenced by func_call2(), and subr_call2().
chk_arguments()
LOGICAL chk_arguments (int ext, int count, ITEM * list, char * kwd_str, int paramct, int dpdsc, int callee, int * p_pass_pos)
Check arguments passed to a user subprogram which has an interface block. Its keyword string is available and is located by kwd_str.
NOTE: if callee is non-zero, the call is via some procedure pointer, and callee is the ast of pointer and ext will be the sptr of the pointer variable or member. Otherwise, callee is 0 and ext is the sptr of the subroutine/function.
Definition at line 2142 of file semfunc2.c.
References A_ARGCNTG, A_ISLVAL, A_OPTYPEG, ADD_NUMDIM, arg, ARG_AST, ARG_STK, aux, buf, chk_pointer_intent(), chkarg(), cmpat_arr_arg(), cngtyp(), CNULL, compat_arg_lists(), count, DDTG, different_type_same_kind(), AUX::dpdsc_base, DT_ISDWORD, DT_ISNUMERIC, DT_ISWORD, DTY, DTYG, eq_dtype(), eq_dtype2(), err_protected(), error(), FALSE, find_pointer_variable(), FLANG_FALLTHROUGH, flg, gbl, get_generic_member(), get_keyword_args(), get_kwd_args(), i, IGNORE_K, IGNORE_R, IGNORE_T, ignore_tkr(), INTENT_IN, INTENT_INOUT, INTENT_OUT, INTENTG, IS_CHAR_TYPE, is_iso_cloc(), is_protected(), list, mem(), memsym_of_ast(), mk_convert(), NULL, proc_arginfo(), s, same_type_different_kind(), SHD_NDIM, SHD_UPB, simply_contiguous(), sptr, ss, FLG::standard, sym_of_ast(), SYMNAME, tk_match_arg(), tmp, TRUE, TY_CHAR, TY_DWORD, TY_NCHAR, TY_WORD, user_subr, void(), and XFR_ARGAST.
Referenced by check_arguments(), ptrfunc_call(), and ptrsubr_call().
chkarg()
int chkarg (SST * stkptr, int * dtype)
Performing checking on an argument to determine if it needs to be "protected".
Parameters
stkptr a stack entry representing a subprogram argument
dtype used to pass out data type of argument
Returns
sptr for alternate return label
When an argument needs to be protected, its value may be have to be stored in a temp and then the temp's address becomes the actual argument. This occurs when a parenthesized expression is an actual argument. NOTE that the logic in chkarg relies on an argument being <expression>; a flag (SST_PARENG/P) in the semantic stack is used and is only defined for <expression>; the flag is cleared when <expression> ::= ... occurs and is set when <primary> ::= (<expression>) occurs.
Definition at line 1138 of file semfunc2.c.
References A_ISLVAL, ast, DT_INT, DT_ISSCALAR, DTY, FLANG_FALLTHROUGH, gbl, GSAMEG, mk_paren(), mkarg(), mkexpr(), newsym(), ref_entry(), RU_FUNC, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_LVALUE, select_gsame(), sem_set_storage_class(), sptr, SST_ASTG, SST_ASTP, SST_DTYPEG, SST_IDG, SST_PARENG, SST_SYMG, TY_CHAR, TY_NCHAR, and void().
Referenced by args_match(), chk_arguments(), func_call2(), ptrfunc_call(), ptrsubr_call(), and subr_call2().
cmpat_arr_arg()
static LOGICAL cmpat_arr_arg (int d1, int shape2) static
Check conformance of two arrays, where the first array is described with a dtype record, and the second is described with a shape descriptor.
Return true if the data types for two shapes are conformable (have the same shape). Shape is defined to be the rank and the extents of each dimension.
Definition at line 2654 of file semfunc2.c.
References AD_DPTR, AD_LWAST, AD_NUMDIM, AD_UPAST, FALSE, get_int_cval(), i, ndim, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, and TRUE.
Referenced by chk_arguments().
compat_arg_lists()
static LOGICAL compat_arg_lists (int formal, int actual) static
For arguments that are subprograms, check that their argument lists are compatible.
Definition at line 2058 of file semfunc2.c.
References aux, cmpat_dtype_with_size(), compat_arg_lists(), compatible_characteristics(), defer_arg_chk(), DEFER_IFACE_CHK, AUX::dpdsc_base, FALSE, flags, gbl, i, IGNORE_ARG_NAMES, RELAX_POINTER_CHK, RELAX_PURE_CHK_2, RELAX_STYPE_CHK, resolve_sym_aliases(), and TRUE.
Referenced by chk_arguments(), and compat_arg_lists().
defer_arg_chk()
void defer_arg_chk (SPTR formal, SPTR actual, SPTR subprog, cmp_interface_flags flags, int lineno, bool performChk)
Process information for deferred interface argument checking in in the compat_arg_lists() function below.
If the performChk argument is false, then we save the information (defer the check). If performChk argument is true, then we perform the argument checking. Note: If performChk is true, then the other arguments are ignored.
Parameters
formal is the symbol table pointer of the dummy/formal argument.
actual is the symbol table pointer of the actual argument.
flags are comparison flags that enable/disable certain checks
lineno is the source line number for the deferred check
performChk is false to defer checks and true to perform the checks.
Definition at line 1991 of file semfunc2.c.
References compatible_characteristics(), error(), flags, FREE, gbl, getsym(), lineno, list, NEW, next, NULL, prev, sem, strlen(), SYMNAME, and SEM::which_pass.
Referenced by compat_arg_lists(), and semant1().
define_stfunc()
int define_stfunc (int sptr, ITEM * argl, SST * estk)
Perform error checking and create statement function descriptor for statement function definition.
Definition at line 99 of file semfunc2.c.
References _non_private(), arg, ARGINFOG, ARGINFOP, _sfuse::args, SFDSC::args, ast, ast_replace(), ast_rewrite(), ast_traverse(), ast_unvisit(), ast_visit(), CNULL, DBGBIT, arginfo::dtype, dump_stfunc(), end_sfuse, error(), gbl, getitem(), ITEM_END, itemp, l_sfuse, mkexpr(), new_node(), _arginfo::next, _sfuse::next, arginfo::next, NOSYM, NULL, put_getitem_p(), SFDSCP, sptr, SST_ASTG, SST_SYMG, stfunc_argl, and SYMNAME.
Referenced by semant3().
dump_stfunc()
static void dump_stfunc (int sptr) static
Write out statement function descriptor to debug file.
Definition at line 242 of file semfunc2.c.
References _sfuse::args, SFDSC::args, _sfuse::dsc, arginfo::dtype, dump_ast_tree(), dump_one_ast(), gbl, get_getitem_p(), _sfuse::next, arginfo::next, SFDSCG, sptr, and SYMNAME.
Referenced by define_stfunc().
get_fval_array()
static int get_fval_array (int ent) static
Definition at line 1409 of file semfunc2.c.
References AD_ADJARR, AD_ASSUMSZ, AD_DEFER, AD_DPTR, STB::curr_scope, get_all_descriptors(), get_static_descriptor(), insert_sym(), INTENT_OUT, INTENTP, pop_sym(), sptr, stb, and XBIT.
Referenced by ref_entry().
iface_arg()
static int iface_arg (int arg, int dt, int iface) static
Definition at line 3147 of file semfunc2.c.
References arg, dt, insert_sym(), and pop_sym().
Referenced by iface_intrinsic().
iface_intrinsic()
int iface_intrinsic (int sptr)
Definition at line 2708 of file semfunc2.c.
References arg, assert, aux, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, DT_CMPLX, DT_DBLE, DT_INT, DT_REAL, getsym(), getsymf(), iface_arg(), intast_sym, INTENT_IN, INTENTP, KWDARGSTR, NEED, sptr, ss, SYMNAME, and TRUE.
Referenced by _do_iface().
ignore_tkr()
LOGICAL ignore_tkr (int arg, int tkr)
Definition at line 2618 of file semfunc2.c.
References arg, FALSE, IGNORE_C, ignore_tkr_all(), and TRUE.
Referenced by chk_arguments(), copy_arg_to_seq_tmp(), handle_seq_section(), and tkr_match().
ignore_tkr_all()
LOGICAL ignore_tkr_all (int arg)
Definition at line 2638 of file semfunc2.c.
References arg, FALSE, IGNORE_TKR_ALL, IGNORE_TKR_ALL0, and TRUE.
Referenced by ignore_tkr(), and misc_checks().
intrinsic_as_arg()
int intrinsic_as_arg (int intr)
Definition at line 851 of file semfunc2.c.
References cp, dt, FLANG_FALLTHROUGH, intast_sym, mkRteRtnNm(), STB::n_base, RTE_indexDsc, RTE_indexx_cr_nma, RTE_indexx_cra, RTE_indexxa, RTE_lenDsc, RTE_lenx_cr_nma, RTE_lenx_cra, RTE_lenxa, select_gsame(), stb, sym_mkfunc(), SYMNAME, WINNT_CALL, WINNT_CREF, WINNT_NOMIXEDSTRLEN, and XBIT.
Referenced by assign_pointer(), and mkarg().
make_keyword_str()
char * make_keyword_str (int paramct, int dpdsc)
Make a keyword string from the DPDSC auxiliary structure.
Definition at line 1476 of file semfunc2.c.
References arg, aux, avl, cnt, AUX::dpdsc_base, i, len, name, NEED, NEW, size, strlen(), SYMNAME, and td.
Referenced by make_kwd_str(), ptrfunc_call(), and ptrsubr_call().
make_kwd_str()
char * make_kwd_str (int ext)
Make a keyword string for a ST_PROC.
Definition at line 1467 of file semfunc2.c.
References make_keyword_str().
Referenced by args_match(), func_call2(), and subr_call2().
mkarg()
int mkarg (SST * stkptr, int * dtype)
Check and write ILMs for a subprogram argument.
Parameters
stkptr a stack entry representing a subprogram argument
dtype used to pass out data type of argument
Returns
sptr for alternate return label
Definition at line 558 of file semfunc2.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_UPAST, ADD_UPBD, ast, astb, ASTB::bnd, CNULL, DDTG, dt, DT_INT, SEM::dtemps, DTY, FLG::endian, error(), find_pointer_variable(), FLANG_FALLTHROUGH, flg, gbl, get_all_descriptors(), get_static_descriptor(), getcctmp_sc(), GSAMEG, ASTB::i0, init_derived_w_acl(), init_sptr_w_acl(), interr(), intrinsic_as_arg(), mk_extent(), mk_id(), mkarg(), mkexpr(), mkident(), mkvarref(), newsym(), ASTB::one, FLG::recursive, ref_entry(), ref_object(), RU_FUNC, RU_SUBR, S_ACONST, S_CONST, S_DERIVED, S_EXPR, S_IDENT, S_KEYWORD, S_LABEL, S_LOGEXPR, S_LVALUE, S_REF, S_SCONST, S_STAR, S_STFUNC, S_TRIPLE, S_VAL, SEM::sc, select_gsame(), sem, sem_set_storage_class(), size_ast(), sptr, SST_ACLG, SST_ASTG, SST_ASTP, SST_CVLENP, SST_DBEGG, SST_DTYPEG, SST_DTYPEP, SST_E3G, SST_ENDG, SST_IDG, SST_IDP, SST_LSYMG, SST_SHAPEP, SST_SYMG, SST_SYMP, sym_get_array(), SYMNAME, tempify(), TY_BINT, TY_BLOG, TY_CHAR, TY_NCHAR, TY_SINT, TY_SLOG, void(), and ASTB::zero.
Referenced by byvalue_ref_arg(), chk_expr(), chk_fmtid(), chk_unitid(), chk_var(), chkarg(), count_actuals(), evl_kwd_args(), func_call2(), gen_init_intrin_call(), gen_spec_item_tmp(), get_sym_from_sst_if_available(), mkarg(), ptrfunc_call(), ptrsubr_call(), ref_intrin(), ref_intrin_subr(), ref_pd(), ref_pd_subr(), semant2(), semant3(), semantio(), and subr_call2().
ref_entry()
int ref_entry (int ent)
Definition at line 1306 of file semfunc2.c.
References DT_INT, DTY, gbl, get_all_descriptors(), get_fval_array(), get_static_descriptor(), getsymbol(), insert_sym(), INTENT_OUT, INTENTP, name, SEM::orph, SEM::parallel, pop_sym(), sem, sem_check_scope(), SYMNAME, SEM::target, SEM::task, and SEM::teams.
Referenced by chkarg(), chksubstr(), find_outer_sym(), func_call2(), mkarg(), mkexpr1(), mklvalue(), mkvarref(), ptrfunc_call(), ref_array(), ref_storage(), ref_storage_inscope(), refsym(), semant3(), and semfin().
ref_stfunc()
int ref_stfunc (SST * stktop, ITEM * args)
Definition at line 276 of file semfunc2.c.
References _arginfo::actual, add_stmt(), _sfuse::args, args, SFDSC::args, asn_sfuse(), ast, ast_replace(), ast_rewrite(), ast_traverse(), ast_unvisit(), ast_visit(), chktyp(), CNULL, dbg_print_ast(), DBGBIT, _sfuse::dsc, _arginfo::dtype, arginfo::dtype, dump_ast_tree(), end_sfuse, error(), _arginfo::formal, gbl, get_getitem_p(), get_temp(), getitem(), SCN::id, SEM::in_stfunc, ITEM_END, itemp, l_sfuse, mk_assn_stmt(), mk_id(), mkexpr(), SCN::name, new_node(), _arginfo::next, _sfuse::next, arginfo::next, _sfuse::node, NULL, _arginfo::refd, S_EXPR, S_KEYWORD, S_STAR, S_TRIPLE, scn, sem, set_internref_stfunc(), SFDSCG, sptr, SST_ASTG, SST_ASTP, SST_CVALG, SST_DTYPEP, SST_E3G, SST_IDG, SST_IDP, SST_SHAPEP, SST_SYMG, stktop, SYMNAME, tmp, TRUE, and void().
Referenced by mkvarref().
select_gsame()
int select_gsame (int gnr)
Given a generic intrinsic, select the corresponding specific of the same name.
Normally, the selection is performed by just accessing the GSAME field of the generic. When an option to override the meaning of INTEGER (-noi4) is selected, some analysis must be done to select the specific intrinsic whose argument type matches the type implied by the option.
Definition at line 1386 of file semfunc2.c.
References DT_CMPLX, DT_INT, DT_REAL, flg, GSAMEG, FLG::i4, spec, and XBIT.
Referenced by assign_pointer(), chkarg(), intrinsic_as_arg(), mkarg(), and semant1().
set_pass_objects()
void set_pass_objects (int pos, int pod)
Set position of type-bound procedure passed object location.
Definition at line 89 of file semfunc2.c.
References pass_object_dummy, pass_position, and pos.
Referenced by func_call2(), and subr_call2().
tempify()
int tempify (SST * stkptr)
Allocate a temporary, assign it the value, and return the temp's base.
Definition at line 1279 of file semfunc2.c.
References add_stmt(), assign(), get_temp(), mkexpr(), mkident(), SST_DTYPEG, SST_DTYPEP, SST_LSYMP, SST_SHAPEP, SST_SYMP, and void().
Referenced by func_call2(), mkarg(), and ref_intrin().
Variable Documentation
end_sfuse
SFUSE* end_sfuse = NULL static
End of list – always add here
Definition at line 77 of file semfunc2.c.
Referenced by define_stfunc(), and ref_stfunc().
l_sfuse
SFUSE* l_sfuse = NULL static
List of statement functions used in a definition.
Keep track of the statement functions used in a definition and the arguments to those statement functions which need to be evaluated and saved in a temporary. The order of the list is in 'evaluation' order.
Definition at line 76 of file semfunc2.c.
Referenced by define_stfunc(), and ref_stfunc().
pass_object_dummy
int pass_object_dummy = 0 static
Definition at line 85 of file semfunc2.c.
Referenced by get_keyword_args(), and set_pass_objects().
pass_position
int pass_position = 0 static
Definition at line 84 of file semfunc2.c.
Referenced by get_keyword_args(), and set_pass_objects().
stfunc_argl
ITEM* stfunc_argl static
Definition at line 82 of file semfunc2.c.
Referenced by _non_private(), and define_stfunc().