flang: semgnr.c File Reference
semgnr.c File Reference
Fortran utility routines used by Semantic Analyzer to process user-defined generics including overloaded operators.
#include "gbldefs.h"
#include "global.h"
#include "gramtk.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "semant.h"
#include "scan.h"
#include "semstk.h"
#include "pd.h"
#include "machar.h"
#include "ast.h"
#include "state.h"
Classes
struct optabstruct
Macros
#define E155(s1, s2)
#define UNIT_SZ 3
#define NBR_DISTANCE_ELM_BITS ((sizeof(long) * 8 - 1) / UNIT_SZ)
#define DISTANCE_BIT(i) (i % NBR_DISTANCE_ELM_BITS)
#define DISTANCE_ELM(distance, i) (distance[i / NBR_DISTANCE_ELM_BITS])
#define INF_DISTANCE ((long)-1)
#define MIN_DISTANCE 0
#define EXACT_MATCH 0
#define EXTND_MATCH 4
#define MAN_MAN_MATCH 0
#define MAN_DEV_MATCH 1
#define MAN_HOST_MATCH 2
#define OPTABSIZE 29
Functions
static int resolve_generic (int, SST *, ITEM *)
static long * args_match (int, int, int, ITEM *, LOGICAL, LOGICAL)
static LOGICAL tkr_match (int, SST *, int, LOGICAL)
static LOGICAL kwd_match (ITEM *, int, char *)
static void get_type_rank (SST *, int *, int *)
static ITEM * make_list (SST *, SST *)
static int resolve_operator (int, SST *, SST *)
static int find_operator (int, SST *, SST *, LOGICAL)
static bool queue_generic_tbp_once (SPTR gnr)
Determines if we should (re)generate generic type bound procedure (tbp) bindings based on scope. This should only be done once per scope.
static bool is_conflicted_generic (SPTR func_sptrgen, SPTR found_sptrgen)
Determines if two generic procedures from different modules are conflicted or not.
void check_generic (int gnr)
int generic_tbp_call (int gnr, SST *stktop, ITEM *list, ITEM *chevlist)
void generic_call (int gnr, SST *stktop, ITEM *list, ITEM *chevlist)
int generic_tbp_func (int gnr, SST *stktop, ITEM *list)
int generic_func (int gnr, SST *stktop, ITEM *list)
static long * set_distance_to (long value, long *distance, int sz)
static int cmp_arg_score (long *distance1, long *distance2, int sz)
static int find_best_generic (int gnr, ITEM *list, int arg_cnt, int try_device, LOGICAL chk_elementals)
int defined_operator (int opr, SST *stktop, SST *lop, SST *rop)
void init_intrinsic_opr (void)
void bind_intrinsic_opr (int val, int opr)
static int tkn_alias_sym (int tkn_alias)
int get_intrinsic_oprsym (int val, int tkn_alias)
int get_intrinsic_opr (int val, int tkn_alias)
LOGICAL is_intrinsic_opr (int val, SST *stktop, SST *lop, SST *rop, int tkn_alias)
void rw_gnr_state (RW_ROUTINE, RW_FILE)
static void defined_io_error (const char *proc, int is_unformatted, const char *msg, int func)
static void check_defined_io2 (const char *proc, int silentmode, int chk_dtype)
int dtype_has_defined_io (int dtype)
Return a bit mask indicating which I/O routines are defined for a derived type.
void check_defined_io (void)
int resolve_defined_io (int read_or_write, SST *stktop, ITEM *list)
void add_overload (int gnr, int func)
void copy_specifics (int fromsptr, int tosptr)
Variables
static int silent_error_mode = 0
static int resolved_to_self = 0
static struct optabstruct optab []
Detailed Description
Fortran utility routines used by Semantic Analyzer to process user-defined generics including overloaded operators.
Definition in file semgnr.c.
Macro Definition Documentation
DISTANCE_BIT
#define DISTANCE_BIT (i) (i % NBR_DISTANCE_ELM_BITS)
Definition at line 48 of file semgnr.c.
DISTANCE_ELM
#define DISTANCE_ELM (distance, i) (distance[i / NBR_DISTANCE_ELM_BITS])
Definition at line 49 of file semgnr.c.
E155
#define E155 (s1, s2)
Value:
  if (!silent_error_mode) \
  error(155, 3, gbl.lineno, s1, s2)
Definition at line 30 of file semgnr.c.
EXACT_MATCH
#define EXACT_MATCH 0
Definition at line 55 of file semgnr.c.
EXTND_MATCH
#define EXTND_MATCH 4
Definition at line 56 of file semgnr.c.
INF_DISTANCE
#define INF_DISTANCE ((long)-1)
Definition at line 52 of file semgnr.c.
MAN_DEV_MATCH
#define MAN_DEV_MATCH 1
Definition at line 61 of file semgnr.c.
MAN_HOST_MATCH
#define MAN_HOST_MATCH 2
Definition at line 62 of file semgnr.c.
MAN_MAN_MATCH
#define MAN_MAN_MATCH 0
Definition at line 60 of file semgnr.c.
MIN_DISTANCE
#define MIN_DISTANCE 0
Definition at line 53 of file semgnr.c.
NBR_DISTANCE_ELM_BITS
#define NBR_DISTANCE_ELM_BITS ((sizeof(long) * 8 - 1) / UNIT_SZ)
Definition at line 47 of file semgnr.c.
OPTABSIZE
#define OPTABSIZE 29
Definition at line 104 of file semgnr.c.
UNIT_SZ
#define UNIT_SZ 3
bits necessary to hold the max *_MATCH value
Definition at line 46 of file semgnr.c.
Function Documentation
add_overload()
void add_overload (int gnr, int func)
Definition at line 1863 of file semgnr.c.
References add_symitem(), DBGBIT, SEM::defined_io_type, func, gbl, sem, and SYMNAME.
Referenced by copy_specifics(), resolveGeneric(), and semant1().
args_match()
static long * args_match (int ext, int count, int distance_sz, ITEM * list, LOGICAL elemental, LOGICAL usedevcopy) static
Definition at line 578 of file semgnr.c.
References arg, ARG_AST, ARG_STK, aux, chkarg(), count, DISTANCE_ELM, AUX::dpdsc_base, FREE, i, INF_DISTANCE, kwd_match(), list, make_kwd_str(), MIN_DISTANCE, NEW, set_distance_to(), tkr_match(), UNIT_SZ, void(), and XFR_ARGAST.
Referenced by find_best_generic().
bind_intrinsic_opr()
void bind_intrinsic_opr (int val, int opr)
Definition at line 1033 of file semgnr.c.
References optabstruct::opr, optab, and val.
Referenced by fill_links_symbol(), and get_intrinsic_opr().
check_defined_io()
void check_defined_io (void)
Definition at line 1818 of file semgnr.c.
References check_defined_io2().
Referenced by do_end_subprogram(), and semant1().
check_defined_io2()
static void check_defined_io2 (const char * proc, int silentmode, int chk_dtype) static
Definition at line 1338 of file semgnr.c.
References all_len_parms_assumed(), aux, STB::curr_scope, defined_io_error(), AUX::dpdsc_base, DT_INT, DT_IO_FREAD, DT_IO_FWRITE, DT_IO_NONE, DT_IO_UREAD, DT_IO_UWRITE, DT_ISINT, DTY, eq_dtype2(), error(), FALSE, first_hash(), func, gbl, generic_tbp_has_pass_and_nopass(), get_generic_member(), get_implementation(), get_specific_member(), getsymbol(), INTENT_IN, INTENT_INOUT, INTENT_OUT, INTENTG, IS_TBP, mem(), NOSYM, proc_arginfo(), queue_generic_tbp_once(), queue_tbp(), rank_of_sym(), sptr, stb, SYMI_NEXT, SYMI_SPTR, SYMNAME, TBP_COMPLETE_GENERIC, test_scope(), TRUE, and XBIT.
Referenced by check_defined_io(), and dtype_has_defined_io().
check_generic()
void check_generic (int gnr)
Definition at line 142 of file semgnr.c.
References assert.
Referenced by semant1(), and subr_call2().
cmp_arg_score()
static int cmp_arg_score (long * distance1, long * distance2, int sz) static
Definition at line 276 of file semgnr.c.
References i, INF_DISTANCE, and sz.
Referenced by find_best_generic().
copy_specifics()
void copy_specifics (int fromsptr, int tosptr)
Definition at line 1880 of file semgnr.c.
References add_overload(), assert, src, sym_in_sym_list(), SYMI_NEXT, and SYMI_SPTR.
Referenced by apply_use(), merge_generics(), and semant1().
defined_io_error()
static void defined_io_error (const char * proc, int is_unformatted, const char * msg, int func) static
Definition at line 1323 of file semgnr.c.
References buf, error(), func, gbl, getitem(), msg(), strlen(), and SYMNAME.
Referenced by check_defined_io2().
defined_operator()
int defined_operator (int opr, SST * stktop, SST * lop, SST * rop)
Definition at line 861 of file semgnr.c.
References STB::curr_scope, DBGBIT, DT_INT, findByNameStypeScope(), func_call2(), gbl, i, list, make_list(), mk_id(), mkident(), queue_generic_tbp_once(), queue_tbp(), resolve_operator(), S_CONST, sptr, SST_ASTP, SST_DTYPEP, SST_IDP, SST_SYMP, stb, stktop, SYMNAME, and TBP_COMPLETE_GENERIC.
Referenced by semant2().
dtype_has_defined_io()
int dtype_has_defined_io (int dtype)
Return a bit mask indicating which I/O routines are defined for a derived type.
Definition at line 1799 of file semgnr.c.
References check_defined_io2(), and DTY.
Referenced by nml_check_item(), nml_emit_desc(), nml_traverse(), and semantio().
find_best_generic()
static int find_best_generic (int gnr, ITEM * list, int arg_cnt, int try_device, LOGICAL chk_elementals) static
Definition at line 297 of file semgnr.c.
References args_match(), cmp_arg_score(), STB::curr_scope, E155, FALSE, first_hash(), FREE, func, gbl, generic_tbp_has_pass_and_nopass(), get_generic_member(), get_implementation(), get_specific_member(), getitem(), INF_DISTANCE, is_conflicted_generic(), IS_TBP, len, list, mem(), name, NBR_DISTANCE_ELM_BITS, NEW, NOSYM, queue_generic_tbp_once(), queue_tbp(), set_distance_to(), sptr, stb, strlen(), SYMI_NEXT, SYMI_SPTR, SYMNAME, TBP_COMPLETE_GENERIC, test_scope(), TRUE, and void().
Referenced by resolve_generic().
find_operator()
static int find_operator (int opr, SST * lop, SST * rop, LOGICAL elemental) static
Definition at line 931 of file semgnr.c.
References arg, aux, STB::curr_scope, AUX::dpdsc_base, first_hash(), func, get_generic_member(), get_implementation(), get_specific_member(), INF_DISTANCE, IS_TBP, mem(), NULL, sptr, stb, SYMI_NEXT, SYMI_SPTR, test_scope(), and tkr_match().
Referenced by resolve_operator().
generic_call()
void generic_call (int gnr, SST * stktop, ITEM * list, ITEM * chevlist)
Definition at line 174 of file semgnr.c.
References DBGBIT, gbl, ITEM_END, list, NULL, resolve_generic(), sptr, SST_ASTP, SST_SYMP, stktop, subr_call2(), and SYMNAME.
Referenced by subr_call2().
generic_func()
int generic_func (int gnr, SST * stktop, ITEM * list)
Definition at line 220 of file semgnr.c.
References DBGBIT, DT_INT, STB::firstosym, func_call2(), gbl, ITEM_END, list, mk_id(), mkident(), NULL, ref_intrin(), ref_pd(), resolve_generic(), S_CONST, sptr, SST_ASTP, SST_DTYPEP, SST_IDP, SST_SYMP, stb, stktop, and SYMNAME.
Referenced by func_call(), mkvarref(), and ref_intrin().
generic_tbp_call()
int generic_tbp_call (int gnr, SST * stktop, ITEM * list, ITEM * chevlist)
Definition at line 155 of file semgnr.c.
References DBGBIT, gbl, ITEM_END, list, NULL, queue_generic_tbp_once(), queue_tbp(), resolve_generic(), sptr, stktop, SYMNAME, and TBP_COMPLETE_GENERIC.
Referenced by subr_call2().
generic_tbp_func()
int generic_tbp_func (int gnr, SST * stktop, ITEM * list)
Definition at line 200 of file semgnr.c.
References DBGBIT, gbl, ITEM_END, list, NULL, queue_generic_tbp_once(), queue_tbp(), resolve_generic(), sptr, stktop, SYMNAME, and TBP_COMPLETE_GENERIC.
Referenced by func_call2().
get_intrinsic_opr()
int get_intrinsic_opr (int val, int tkn_alias)
Definition at line 1076 of file semgnr.c.
References bind_intrinsic_opr(), declsym(), FALSE, get_intrinsic_oprsym(), and val.
Referenced by semant1().
get_intrinsic_oprsym()
int get_intrinsic_oprsym (int val, int tkn_alias)
Definition at line 1065 of file semgnr.c.
References getsymbol(), name, optab, tkn_alias_sym(), and val.
Referenced by get_intrinsic_opr(), and semant1().
get_type_rank()
static void get_type_rank (SST * stkptr, int * dt_p, int * rank_p) static
Definition at line 1224 of file semgnr.c.
References AD_DPTR, AD_NUMDIM, DTY, newsym(), S_ACONST, S_CONST, S_DERIVED, S_EXPR, S_IDENT, S_LOGEXPR, S_LVALUE, S_SCONST, S_STFUNC, sem_set_storage_class(), SHD_NDIM, sptr, SST_DTYPEG, SST_IDG, SST_SHAPEG, SST_SYMG, and SST_SYMP.
Referenced by is_intrinsic_opr(), and tkr_match().
init_intrinsic_opr()
void init_intrinsic_opr (void)
Definition at line 1024 of file semgnr.c.
References i, OP_VAL, and optab.
Referenced by semant_init().
is_conflicted_generic()
static bool is_conflicted_generic (SPTR func_sptrgen, SPTR found_sptrgen) static
Determines if two generic procedures from different modules are conflicted or not.
Parameters
found_sptrgen is the first generic procedure sptr.
func_sptrgen is the second generic procedure sptr.
Returns
true if the func_sptrgen and found_sptrgen are not conflicted, else false.
Definition at line 135 of file semgnr.c.
Referenced by find_best_generic().
is_intrinsic_opr()
LOGICAL is_intrinsic_opr (int val, SST * stktop, SST * lop, SST * rop, int tkn_alias)
Definition at line 1087 of file semgnr.c.
References ast, buf, CNULL, DBGBIT, SEM::dtemps, DTYG, E155, error(), FALSE, func, func_call2(), gbl, get_implementation(), get_tbp_argno(), get_type_rank(), getccsym_sc(), IS_TBP, list, make_list(), mem(), mk_id(), mkexpr(), mkident(), mkmember(), SEM::mod_cnt, name, NULL, OP_ST, optabstruct::opr, optab, queue_generic_tbp_once(), queue_tbp(), rank, resolve_operator(), S_SCONST, sem, SST_ASTG, SST_ASTP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_SYMP, stktop, subr_call2(), SYMNAME, TBP_COMPLETE_GENERIC, tmp, TRUE, val, and SEM::which_pass.
Referenced by common_rel(), log_negation(), semant2(), and semant3().
kwd_match()
static LOGICAL kwd_match (ITEM * list, int cnt, char * kwdarg) static
Definition at line 756 of file semgnr.c.
References ARG_AST, ARG_STK, SEM::argpos, assert, cnt, FALSE, getitem(), i, SCN::id, ITEM_END, list, SCN::name, NULL, pos, S_KEYWORD, scn, sem, SST_ASTG, SST_CVALG, SST_E3G, SST_IDG, strlen(), and TRUE.
Referenced by args_match().
make_list()
static ITEM * make_list (SST * lop, SST * rop) static
Definition at line 1295 of file semgnr.c.
References getitem(), ITEM_END, list, NULL, and tmp.
Referenced by defined_operator(), and is_intrinsic_opr().
queue_generic_tbp_once()
static bool queue_generic_tbp_once (SPTR gnr) static
Determines if we should (re)generate generic type bound procedure (tbp) bindings based on scope. This should only be done once per scope.
Parameters
gnr is the SPTR of the symbol to check or 0 if N/A.
Returns
true if we should (re)generate generic tbp bindings, else false.
Definition at line 114 of file semgnr.c.
References STB::curr_scope, gbl, and stb.
Referenced by check_defined_io2(), defined_operator(), find_best_generic(), generic_tbp_call(), generic_tbp_func(), and is_intrinsic_opr().
resolve_defined_io()
int resolve_defined_io (int read_or_write, SST * stktop, ITEM * list)
Parameters
read_or_write 0 specifies read, 1 specifies write
stktop SST we're processing.
list argument list for read/write
Returns
= -1 : error (resolves to struct constructor -- should never happen)
= 0  : error or no I/O subroutine
> 0  : sptr of the 'specific' defined I/O subroutine
Definition at line 1837 of file semgnr.c.
References error(), gbl, getsymbol(), i, list, NOSYM, resolve_generic(), resolved_to_self, silent_error_mode, stktop, and SYMNAME.
Referenced by nml_emit_desc(), and semantio().
resolve_generic()
static int resolve_generic (int gnr, SST * stktop, ITEM * list) static
Definition at line 459 of file semgnr.c.
References AC_EXPR, AC_SCONST, chk_struct_constructor(), CNULL, DBGBIT, _acl::dtype, E155, error(), FALSE, find_best_generic(), STB::firstosym, gbl, GET_ACL, getitem(), _acl::id, IS_INTRINSIC, ITEM_END, itemp, list, mkexpr(), name, _acl::next, NULL, _acl::repeatc, S_ACONST, S_SCONST, S_TRIPLE, _acl::size, sptr, SST_ACLG, SST_ACLP, SST_DTYPEP, SST_IDG, SST_IDP, SST_SYMP, stb, _acl::stkp, stktop, strlen(), _acl::subc, SYMNAME, TRUE, and _acl::u1.
Referenced by generic_call(), generic_func(), generic_tbp_call(), generic_tbp_func(), and resolve_defined_io().
resolve_operator()
static int resolve_operator (int opr, SST * lop, SST * rop) static
Definition at line 899 of file semgnr.c.
References DBGBIT, E155, FALSE, find_operator(), func, gbl, NULL, SYMNAME, and TRUE.
Referenced by defined_operator(), and is_intrinsic_opr().
rw_gnr_state()
void rw_gnr_state (RW_ROUTINE , RW_FILE)
Definition at line 1316 of file semgnr.c.
References optab, OPTABSIZE, and RW_FD.
Referenced by rw_host_state().
set_distance_to()
static long * set_distance_to (long value, long * distance, int sz) static
Definition at line 260 of file semgnr.c.
References i, sz, and value().
Referenced by args_match(), and find_best_generic().
tkn_alias_sym()
static int tkn_alias_sym (int tkn_alias) static
Definition at line 1041 of file semgnr.c.
References getsymbol(), and interr().
Referenced by get_intrinsic_oprsym().
tkr_match()
static int tkr_match (int formal, SST * opnd, int actual, LOGICAL elemental) static
Definition at line 644 of file semgnr.c.
References AD_ASSUMSZ, AD_DPTR, AD_NUMDIM, ast_is_sym(), DDTG, different_type_same_kind(), DTY, EXACT_MATCH, EXTND_MATCH, FALSE, get_type_rank(), IGNORE_K, IGNORE_M, IGNORE_R, IGNORE_T, ignore_tkr(), INF_DISTANCE, IS_INTRINSIC, memsym_of_ast(), rank, same_type_different_kind(), setimplicit(), sptr, tk_match_arg(), and TRUE.
Referenced by args_match(), and find_operator().
Variable Documentation
optab
struct optabstruct optab[] static
Referenced by bind_intrinsic_opr(), get_intrinsic_oprsym(), init_intrinsic_opr(), is_intrinsic_opr(), and rw_gnr_state().
resolved_to_self
int resolved_to_self = 0 static
Definition at line 64 of file semgnr.c.
Referenced by resolve_defined_io().
silent_error_mode
int silent_error_mode = 0 static
Definition at line 28 of file semgnr.c.
Referenced by resolve_defined_io().