flang: semsym.c File Reference
semsym.c File Reference
Fortran Semantic action routines to resolve symbol references as to overloading class.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "gramtk.h"
#include "semant.h"
#include "ast.h"
#include "rte.h"
#include "interf.h"
Functions
static int find_in_host (int)
static void internref_bnd (int)
static int add_private_allocatable (int, int)
static void check_parref (int, int, int)
static LOGICAL isGenericOrProcOrModproc (SPTR sptr)
static LOGICAL isSameNameGenericOrProcOrModproc (SPTR sptr1, SPTR sptr2)
static int getEnclFunc (SPTR sptr)
static LOGICAL isLocalPrivate (SPTR sptr)
int sym_in_scope (int first, OVCLASS overloadclass, int *paliassym, int *plevel, int multiple_use_error)
Look for a symbol with same name as first and in an active scope.
void sem_import_sym (int s)
IMPORT symbol from host scope – not to be confused with interf import stuff.
int test_scope (int sptr)
int declref (int first, SYMTYPE stype, int def)
Look up symbol having a specific symbol type.
static int replace_variable (int sptr, SYMTYPE stype)
static void set_internref_flag (int sptr)
void set_internref_stfunc (int ast)
int declsym (int first, SYMTYPE stype, LOGICAL errflg)
Declare a new symbol.
int refsym (int first, OVCLASS oclass)
Look up a symbol having the given overloading class.
int refsym_inscope (int first, OVCLASS oclass)
Similar to refsym() except that the current scope is taken into consideration.
void enforce_denorm (void)
int getocsym (int first, OVCLASS oclass, LOGICAL alias)
Look up symbol matching overloading class of given symbol type.
int declobject (int sptr, SYMTYPE stype)
int newsym (int sptr)
Reset fields of intrinsic or generic symbol, sptr, to zero in preparation for changing its symbol type by the Semantic Analyzer.
int ref_ident (int sptr)
Reference a symbol when it's known the context requires an identifier.
int ref_ident_inscope (int sptr)
int ref_storage (int sptr)
Reference a symbol when it's known the context requires storage, e.g., a variable or the result of a function.
int ref_storage_inscope (int sptr)
int ref_int_scalar (int sptr)
Reference a symbol when it's known the context requires an integer scalar variable.
static void mark_static (int astx)
Mark a compiler-created temp as static.
int ref_based_object (int sptr)
Reference a based object.
int ref_based_object_sc (int sptr, SC_KIND sc)
int refocsym (int first, OVCLASS oclass)
Reference the first symbol of the given overloading class in the current scope. If not found, zero is returned.
int sym_skip_construct (int first)
SPTR block_local_sym (SPTR sptr)
Return a symbol local to the current BLOCK if applicable.
int declsym_newscope (int sptr, SYMTYPE stype, int dtype)
Declare a symbol in the most current scope; if one already exists return it.
static void nullify_member_after (int ast, int std, int sptr)
int decl_private_sym (int sptr)
Declare a private symbol which may be based on the attributes of an existing symbol.
static void check_adjustable_array (int sptr)
int sem_check_scope (int sym, int orig)
Check the current parallel scope of a variable.
Variables
static LOGICAL checking_scope = FALSE
Detailed Description
Fortran Semantic action routines to resolve symbol references as to overloading class.
This module hides the walking of hash chains and overloading class checks.
Definition in file semsym.c.
Function Documentation
add_private_allocatable()
static int add_private_allocatable (int old, int new) static
Definition at line 1828 of file semsym.c.
References ADD_LWAST, ADD_NOBOUNDS, add_nullify_ast(), ADD_NUMDIM, add_stmt(), add_stmt_after(), ADD_UPAST, ast, ast_intr(), astb, BLK_SYM, BLK_UPLEVEL_SPTR, ASTB::bnd, checking_scope, DI_ALLOCATED, SEM::doif_depth, dt, DT_INT, DT_PTR, ASTB::dtype, SCOPESTACK::end_prologue, flg, gen_conditional_alloc(), getccsym(), getitem(), i, interr(), itemp, lb, MAXRANK, mk_assn_stmt(), mk_id(), mk_subscr(), mk_triple(), ASTB::one, ref_based_object(), RUNTIMEG, SEM::sc, SEM::scope_level, SEM::scope_stack, sem, set_parref_flag(), FLG::smp, SCOPESTACK::sptr, STD_PREV, sym_get_scalar(), SYMNAME, ub, and void().
Referenced by decl_private_sym().
block_local_sym()
SPTR block_local_sym (SPTR sptr)
Return a symbol local to the current BLOCK if applicable.
Parameters
sptr symbol (index), possibly declared in an enclosing scope.
Returns
symbol in the current BLOCK if in a BLOCK (which may be the original \sptr); otherwise return original \sptr.
This function should be called when a symbol might be declared in an ancestor subprogram or block, but should be redeclared as a symbol in the current BLOCK.
Definition at line 1538 of file semsym.c.
References SEM::block_scope, SEM::construct_sptr, insert_sym(), INSIDE_STRUCT, SEM::scope_stack, sem, sptr, and SCOPESTACK::symavl.
Referenced by getcctmp(), semant1(), semant2(), and semant3().
check_adjustable_array()
static void check_adjustable_array (int sptr) static
Definition at line 1812 of file semsym.c.
References sptr, and sym_get_ptr().
Referenced by check_parref().
check_parref()
static void check_parref (int sym, int new, int orig) static
Definition at line 1973 of file semsym.c.
References BLK_UPLEVEL_SPTR, check_adjustable_array(), is_sptr_in_shared_list(), SCOPESTACK::par_scope, PAR_SCOPE_SHARED, SEM::parallel, SEM::scope_level, SEM::scope_stack, sem, set_parref_flag(), SEM::target, SEM::task, and SEM::teams.
Referenced by ref_based_object_sc(), and sem_check_scope().
decl_private_sym()
int decl_private_sym (int sptr)
Declare a private symbol which may be based on the attributes of an existing symbol.
If the symbol doesn't exist (its stype is ST_UNKNOWN), it's assumed that the private variable will be a scalar variable.
Definition at line 1608 of file semsym.c.
References AD_DPTR, AD_LWBD, AD_NUMDIM, AD_UPBD, add_private_allocatable(), allocatable_member(), SEM::arrdim, BLK_SCOPE_SPTR, BLK_SYM, SEM::bounds, checking_scope, decl_private_sym(), DI_ID, DI_PAR, DI_PARDO, DI_PARSECTS, DI_TASK, DI_TASKLOOP, SEM::doif_depth, dt, DT_INT, DTY, dup_array_dtype(), SCOPESTACK::end_prologue, error(), flg, gbl, get_all_descriptors(), get_isz_cval(), get_static_descriptor(), getsymbol(), i, insert_sym(), SCOPESTACK::kind, lb, mk_arrdsc(), mk_id(), name, ndim, nullify_member_after(), STB::ovclass, refsym(), SCOPESTACK::rgn_scope, RUNTIMEG, S_CONST, S_EXPR, SEM::sc, SEM::scope_level, SCOPE_PAR, SEM::scope_stack, sem, set_descriptor_sc(), set_private_encl(), set_private_taskflag(), FLG::smp, sptr, SCOPESTACK::sptr, stb, STD_PREV, sym_get_scalar(), SYMNAME, and SEM::task.
Referenced by decl_private_sym(), do_distbegin(), do_lastprivate(), do_private(), do_reduction(), mk_firstprivate(), mklvalue(), and sem_check_scope().
declobject()
int declobject (int sptr, SYMTYPE stype)
Definition at line 1159 of file semsym.c.
References AD_ASSUMSZ, AD_DEFER, AD_DPTR, CNULL, declsym(), error(), flg, gbl, refsym(), sptr, SYMNAME, TRUE, FLG::xref, and xrefput().
declref()
int declref (int first, SYMTYPE stype, int def)
Look up symbol having a specific symbol type.
If a symbol is found in the same overloading class and has the same symbol type, it is returned to the caller. If a symbol is found in the same overloading class, the action of declref depends on the stype of the existing symbol and value of the argument def:
if symbol is an unfrozen intrinsic and def is 'd' (define), its intrinsic property is removed and a new symbol is declared,
if def is 'd', a multiple declaration error occurs, or
if def is not 'd', an 'illegal use' error occurs
If an error occurs or a matching symbol is not found, one is created and its symbol type is initialized.
Definition at line 491 of file semsym.c.
References CNULL, STB::curr_scope, def, error(), first, flg, gbl, insert_sym(), SEM::interface, IS_INTRINSIC, newsym(), NULL, STB::ovclass, sem, sptr, st, stb, sym_in_scope(), SYMNAME, FLG::xref, and xrefput().
Referenced by _read_token(), chk_fmtid(), dummy_program(), ff_get_label(), get_stmt(), read_symbol(), semant1(), and semant3().
declsym()
int declsym (int first, SYMTYPE stype, LOGICAL errflg)
Declare a new symbol.
An error can occur if the symbol is already in the symbol table.
If the symbol types match: treat as in error if errflg is true; otherwise return the symbol.
If they don't match: if symbol is an intrinsic attempt to remove symbol's intrinsic property; otherwise it is an error.
Definition at line 644 of file semsym.c.
References CNULL, STB::curr_scope, error(), export_append_sym(), first, first_hash(), STB::firstusym, flg, gbl, get_scope(), get_scope_level(), GSAMEG, GSAMEP, IN_MODULE, IN_MODULE_SPEC, insert_sym(), SEM::interface, internal_proc_has_ident(), IS_INTRINSIC, kind, level(), SEM::mod_sym, newsym(), next_scope_kind(), NOSYM, STB::ovclass, pop_sym(), push_sym(), replace_variable(), SCOPE_MODULE, SCOPE_NORMAL, SCOPE_OUTER, SCOPE_USE, sem, set_internref_flag(), sptr, st, stb, sym_in_scope(), SYMI_NEXT, SYMI_SPTR, SYMNAME, SEM::which_pass, FLG::xref, and xrefput().
Referenced by add_predefined_ieeearith_module(), add_predefined_iso_fortran_env_module(), add_predefined_isoc_module(), begin_module(), create_func_entry(), create_func_entry_result(), decl_procedure_sym(), declobject(), fixup_param_vars(), gen_finalized_result(), get_intrinsic_opr(), get_parameterized_dt(), get_unl_poly_sym(), resolveBind(), resolveImp(), semant1(), semant2(), and semant3().
declsym_newscope()
int declsym_newscope (int sptr, SYMTYPE stype, int dtype)
Declare a symbol in the most current scope; if one already exists return it.
Definition at line 1557 of file semsym.c.
References STB::curr_scope, FALSE, gbl, getocsym(), insert_sym(), STB::ovclass, sptr, and stb.
Referenced by ast_ioret(), get_fmt_array(), merge_generics(), and resolveImp().
enforce_denorm()
void enforce_denorm (void)
Definition at line 1100 of file semsym.c.
References first, gbl, SEM::ieee_features, lookupsymbol(), NULL, sem, sptr, sym_in_scope(), SYMNAME, and TRUE.
Referenced by check_end_subprogram(), and semant1().
find_in_host()
static int find_in_host (int s) static
Definition at line 366 of file semsym.c.
References FALSE, first_hash(), get_scope(), get_scope_level(), SEM::interface, is_except_in_scope(), SCOPESTACK::kind, next_scope(), next_scope_kind(), STB::ovclass, s, scope, SCOPE_INTERFACE, SEM::scope_level, SCOPE_NORMAL, SCOPE_SUBPROGRAM, sem, sptr, stb, sym_in_sym_list(), SYMI_NEXT, SYMI_SPTR, and TRUE.
Referenced by sem_import_sym().
getEnclFunc()
static int getEnclFunc (SPTR sptr) static
Definition at line 59 of file semsym.c.
References sptr.
Referenced by isLocalPrivate().
getocsym()
int getocsym (int first, OVCLASS oclass, LOGICAL alias)
Look up symbol matching overloading class of given symbol type.
Parameters
first the symbol to match by name
oclass the overloading class to match
alias if true and the symbol is an ST_ALIAS, return the dereferenced symbol
Returns
The symbol whose overloading class matches the overloading class of the symbol type given. If no symbol is found in the given overloading class one is created.
Definition at line 1127 of file semsym.c.
References first, flg, insert_sym(), SEM::interface, NULL, STB::ovclass, sem, sptr, st, stb, sym_in_scope(), FLG::xref, and xrefput().
Referenced by chk_intrinsic(), declsym_newscope(), import_symbol(), newsym(), and semant1().
internref_bnd()
static void internref_bnd (int ast) static
Definition at line 615 of file semsym.c.
References ast, and sptr.
Referenced by set_internref_flag().
isGenericOrProcOrModproc()
static LOGICAL isGenericOrProcOrModproc (SPTR sptr) static
Definition at line 35 of file semsym.c.
References FALSE, sptr, and TRUE.
Referenced by isSameNameGenericOrProcOrModproc().
isLocalPrivate()
static LOGICAL isLocalPrivate (SPTR sptr) static
Definition at line 75 of file semsym.c.
References FALSE, gbl, getEnclFunc(), scope, sptr, and TRUE.
Referenced by sym_in_scope().
isSameNameGenericOrProcOrModproc()
static LOGICAL isSameNameGenericOrProcOrModproc (SPTR sptr1, SPTR sptr2) static
Definition at line 49 of file semsym.c.
References FALSE, GSAMEG, and isGenericOrProcOrModproc().
Referenced by sym_in_scope().
mark_static()
static void mark_static (int astx) static
Mark a compiler-created temp as static.
Definition at line 1367 of file semsym.c.
References sptr, and sym_of_ast().
Referenced by ref_based_object_sc().
newsym()
int newsym (int sptr)
Reset fields of intrinsic or generic symbol, sptr, to zero in preparation for changing its symbol type by the Semantic Analyzer.
If the symbol type of the symbol has been 'frozen', issue an error message and notify the caller by returning a zero symbol pointer.
Definition at line 1183 of file semsym.c.
References CNULL, error(), FALSE, gbl, getocsym(), getsym(), insert_sym(), LOCAL_SYMNAME, sptr, strlen(), and SYMNAME.
Referenced by chkarg(), convert_intrinsics_to_idents(), declref(), declsym(), export_fix_host_append_list(), find_outer_sym(), gen_dinit(), get_type_rank(), matmul(), mkarg(), mkexpr1(), mklvalue(), mkvarref(), mmul(), ref_ident(), ref_ident_inscope(), ref_int_scalar(), ref_intrin(), ref_intrin_subr(), ref_pd(), ref_pd_subr(), ref_storage_inscope(), reshape(), rewrite_func_ast(), semant1(), semant3(), and subr_call2().
nullify_member_after()
static void nullify_member_after (int ast, int std, int sptr) static
Definition at line 1575 of file semsym.c.
References add_nullify_ast(), add_stmt_after(), allocatable_member(), ast, DDTG, DTY, is_tbp_or_final(), mk_id(), mk_member(), NOSYM, nullify_member_after(), sptr, and std.
Referenced by decl_private_sym(), and nullify_member_after().
ref_based_object()
int ref_based_object (int sptr)
Reference a based object.
Since it's possible to have more than one level of 'based' storage, need to scan through the MIDNUM fields until the "pointer" variable is found. Along the way, it may be necessary to fix the stypes of the based variables and to create xref 'r' records. Also, the storage class of the 'pointer' variable is fixed if necessary. The symbol table index of the 'pointer' variable is returned.
Definition at line 1390 of file semsym.c.
References ref_based_object_sc(), and sptr.
Referenced by add_private_allocatable(), find_outer_sym(), gen_pointer_result(), ref_object(), and semant3().
ref_based_object_sc()
int ref_based_object_sc (int sptr, SC_KIND sc)
Definition at line 1398 of file semsym.c.
References AD_EXTNTAST, AD_LWAST, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_PTR, AD_UPAST, AD_ZBASE, assert, check_parref(), DT_PTR, DTY, F77OUTPUT, fixup_reqgs_ident(), flg, gbl, get_all_descriptors(), get_static_descriptor(), getccsym(), i, in_save_scope(), mark_static(), NOSYM, set_internref_flag(), FLG::smp, sptr, sym_get_ptr(), TRUE, FLG::xref, and xrefput().
Referenced by gen_allocatable_result(), gen_array_result(), and ref_based_object().
ref_ident()
int ref_ident (int sptr)
Reference a symbol when it's known the context requires an identifier.
If an error occurs (e.g., symbol which is frozen as an intrinsic), a new symbol is created so that processing can continue. If the symbol found is ST_UNKNOWN, its stype is changed to ST_IDENT.
Definition at line 1235 of file semsym.c.
References insert_sym(), IS_INTRINSIC, newsym(), refsym(), and sptr.
Referenced by ref_storage(), semant1(), and semsmp().
ref_ident_inscope()
int ref_ident_inscope (int sptr)
Definition at line 1252 of file semsym.c.
References insert_sym(), IS_INTRINSIC, newsym(), refsym_inscope(), and sptr.
Referenced by semant1().
ref_int_scalar()
int ref_int_scalar (int sptr)
Reference a symbol when it's known the context requires an integer scalar variable.
If an error occurs (e.g., symbol which is frozen as an intrinsic), a new symbol is created so that processing can continue. If the symbol found is ST_UNKNOWN, its stype is changed to ST_IDENT.
Definition at line 1345 of file semsym.c.
References DT_ISINT, error(), gbl, insert_sym(), IS_INTRINSIC, newsym(), refsym(), sptr, and SYMNAME.
ref_storage()
int ref_storage (int sptr)
Reference a symbol when it's known the context requires storage, e.g., a variable or the result of a function.
If an error occurs (e.g., symbol which is frozen as an intrinsic), a new symbol is created so that processing can continue. If the symbol found is ST_UNKNOWN, its stype is changed to ST_IDENT.
Definition at line 1279 of file semsym.c.
References DTY, gbl, ref_entry(), ref_ident(), RU_FUNC, and sptr.
ref_storage_inscope()
int ref_storage_inscope (int sptr)
Definition at line 1304 of file semsym.c.
References DTY, gbl, insert_sym(), IS_INTRINSIC, newsym(), ref_entry(), refsym_inscope(), RU_FUNC, and sptr.
refocsym()
int refocsym (int first, OVCLASS oclass)
Reference the first symbol of the given overloading class in the current scope. If not found, zero is returned.
Definition at line 1495 of file semsym.c.
References first, NULL, STB::ovclass, sptr, st, stb, and sym_in_scope().
Referenced by do_dot(), and resolveImp().
refsym()
int refsym (int first, OVCLASS oclass)
Look up a symbol having the given overloading class.
If the symbol with the overloading class is found its sptr is returned. If no symbol with the given overloading class is found, a new sptr is returned.
Definition at line 946 of file semsym.c.
References BLK_UPLEVEL_SPTR, first, flg, gbl, insert_sym(), SEM::interface, NULL, STB::ovclass, SEM::parallel, ref_entry(), RU_FUNC, SEM::scope_level, sem, set_internref_flag(), set_parref_flag(), sptr, st, stb, sym_in_scope(), SEM::target, SEM::task, SEM::teams, FLG::xref, and xrefput().
Referenced by _do_iface(), chk_func_entry_result(), decl_private_sym(), declobject(), do_access(), do_copyin(), do_copyprivate(), find_outer_sym(), get_derived_type(), ref_ident(), ref_int_scalar(), ref_pd(), sem_check_scope(), semant1(), semant2(), semant3(), semantio(), and semsmp().
refsym_inscope()
int refsym_inscope (int first, OVCLASS oclass)
Similar to refsym() except that the current scope is taken into consideration.
If the symbol with the overloading class is found its sptr is returned. If no symbol with the given overloading class is found, a new sptr is returned.
Definition at line 1009 of file semsym.c.
References STB::curr_scope, error(), first, STB::firstusym, flg, gbl, insert_sym(), SEM::interface, IS_INTRINSIC, SCOPESTACK::kind, level(), SEM::mod_sym, NULL, STB::ovclass, SEM::scope_level, SCOPE_NORMAL, SEM::scope_stack, sem, set_internref_flag(), sptr, st, stb, sym_in_scope(), SYMNAME, FLG::xref, and xrefput().
Referenced by _do_iface(), create_var(), get_csect_sym(), ref_ident_inscope(), ref_storage_inscope(), semant1(), and semant2().
replace_variable()
static int replace_variable (int sptr, SYMTYPE stype) static
Definition at line 541 of file semsym.c.
References SEM::accl, getitem(), insert_sym(), module_must_hide_this_symbol(), _accl::next, _accl::oper, sem, sptr, _accl::sptr, and _accl::type.
Referenced by declsym().
sem_check_scope()
int sem_check_scope (int sym, int orig)
Check the current parallel scope of a variable.
Parameters
sym Represents the variable which actually references storage.
orig Identifier to which the sym refers; for entries, orig will be the ST_ENTRY and sym will be its FVAL.
If the current scope is default private, need to ensure that any variables which have not been declared in this scope are declared as private variables. If the current scope is 'none', then need to ensure that the variables were actually declared in this scope.
Note that at this time, ST_UNKNOWN and ST_IDENT symbols should be have been resolved.
Definition at line 2013 of file semsym.c.
References add_assign_firstprivate(), add_no_scope_sptr(), check_parref(), checking_scope, decl_private_sym(), FALSE, gbl, SEM::ignore_default_none, SEM::orph, SCOPESTACK::par_scope, PAR_SCOPE_FIRSTPRIVATE, PAR_SCOPE_NONE, PAR_SCOPE_SHARED, PAR_SCOPE_TASKNODEFAULT, SEM::parallel, refsym(), SCOPESTACK::rgn_scope, s, SEM::scope_level, SEM::scope_stack, sem, sem_check_scope(), SCOPESTACK::sptr, ss, SEM::target, SEM::task, SEM::teams, and TRUE.
Referenced by mklvalue(), ref_entry(), ref_object(), sem_check_scope(), and semant3().
sem_import_sym()
void sem_import_sym (int s)
IMPORT symbol from host scope – not to be confused with interf import stuff.
Definition at line 325 of file semsym.c.
References add_symitem(), error(), find_in_host(), gbl, next_scope_kind(), NOSYM, s, scope, SCOPE_NORMAL, sptr, and SYMNAME.
Referenced by semant1().
set_internref_flag()
static void set_internref_flag (int sptr) static
Definition at line 565 of file semsym.c.
References AD_ADJARR, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_UPAST, AD_ZBASE, DTY, i, internref_bnd(), ndim, parent, set_internref_flag(), and sptr.
Referenced by declsym(), ref_based_object_sc(), refsym(), refsym_inscope(), set_internref_flag(), and set_internref_stfunc().
set_internref_stfunc()
void set_internref_stfunc (int ast)
Definition at line 625 of file semsym.c.
References ast, gbl, set_internref_flag(), and sptr.
Referenced by ref_stfunc().
sym_in_scope()
int sym_in_scope (int first, OVCLASS overloadclass, int * paliassym, int * plevel, int multiple_use_error)
Look for a symbol with same name as first and in an active scope.
Parameters
first the symbol to match by name
overloadclass 0 or the value of stb.ovclass to match
paliassym return the symbol the result is an alias of
plevel return the scope nest at which symbol was found
multiple_use_error if true, report error if name is USE-associated from two different modules
Returns
symbol (or alias) if found, else 0
Definition at line 96 of file semsym.c.
References SEM::doif_depth, error(), find_explicit_interface(), first, first_hash(), gbl, get_scope_level(), is_except_in_scope(), IS_TBP, is_used_by_submod(), isLocalPrivate(), isSameNameGenericOrProcOrModproc(), msg(), next_scope(), next_scope_kind_sptr(), NULL, STB::ovclass, scope, SCOPE_BLOCK, SCOPE_INTERFACE, SCOPE_NORMAL, SEM::scope_stack, SCOPE_USE, sem, sptr, stb, sym_in_sym_list(), SYMNAME, TRUE, and SEM::which_pass.
Referenced by declref(), declsym(), do_access(), enforce_denorm(), getocsym(), refocsym(), refsym(), refsym_inscope(), resolveBind(), and semant1().
sym_skip_construct()
int sym_skip_construct (int first)
Definition at line 1516 of file semsym.c.
References first, NOSYM, and sptr.
Referenced by mkvarref(), and semant2().
test_scope()
int test_scope (int sptr)
Definition at line 440 of file semsym.c.
References gbl, get_scope(), is_except_in_scope(), scope, SEM::scope_level, SCOPE_USE, sem, sptr, sym_in_sym_list(), SYMI_NEXT, and SYMI_SPTR.
Referenced by _do_iface(), check_defined_io2(), cmp_interfaces(), find_best_generic(), find_operator(), fix_proc_ptr_dummy_args(), get_sst_named_whole_variable(), get_tbp_argno(), merge_generics(), mkexpr1(), semant1(), and subr_call2().
Variable Documentation
checking_scope
LOGICAL checking_scope = FALSE static
Definition at line 32 of file semsym.c.
Referenced by add_private_allocatable(), decl_private_sym(), and sem_check_scope().