flang: semsym.cpp File Reference
semsym.cpp File Reference
FTN Semantic action routines to resolve symbol references as to overloading class. This module hides the walking of hash chains and overloading class checks.
#include "semsym.h"
#include "error.h"
#include "global.h"
#include "semant.h"
#include "xref.h"
Functions
SPTR declref (SPTR sptr, SYMTYPE stype, int def)
Look up symbol having a specific symbol type.
SPTR declsym (SPTR sptr, SYMTYPE stype, bool errflg)
Declare a new symbol.
SPTR refsym (SPTR sptr, int oclass)
Look up a symbol having the given overloading class.
SPTR getocsym (SPTR sptr, int oclass)
Look up symbol matching overloading class of given symbol type.
SPTR newsym (SPTR sptr)
Reset fields of intrinsic or generic symbol, sptr, to zero in preparation for changing its symbol type by the Semantic Analyzer. If the symbol type of the symbol has been 'frozen', issue an error message and notify the caller by returning a zero symbol pointer.
SPTR ref_ident (SPTR sptr)
Reference a symbol when it's known the context requires an identifier. If an error occurs (e.g., symbol which is frozen as an intrinsic), a new symbol is created so that processing can continue. If the symbol found is ST_UNKNOWN, its stype is changed to ST_IDENT.
Detailed Description
FTN Semantic action routines to resolve symbol references as to overloading class. This module hides the walking of hash chains and overloading class checks.
Definition in file semsym.cpp.
Function Documentation
declref()
SPTR declref (SPTR sptr, SYMTYPE stype, int def)
Look up symbol having a specific symbol type.
If a symbol is found in the same overloading class and has the same symbol type, it is returned to the caller. If a symbol is found in the same overloading class, the action of declref depends on the stype of the existing symbol and value of the argument def:
if symbol is an unfrozen intrinsic and def is 'd' (define), its intrinsic property is removed and a new symbol is declared,
if def is 'd', a multiple declaration error occurs, or
if def is not 'd', an 'illegal use' error occurs.
If an error occurs or a matching symbol is not found, one is created and its symbol type is initialized.
Definition at line 22 of file semsym.cpp.
References CNULL, def, ERR_Severe, error(), first, flg, gbl, insert_sym(), IS_INTRINSIC, newsym(), STB::ovclass, sptr, SPTR_NULL, st, stb, SYMNAME, FLG::xref, and xrefput().
declsym()
SPTR declsym (SPTR sptr, SYMTYPE stype, bool errflg)
Declare a new symbol.
An error can occur if the symbol is already in the symbol table:
if the symbol types match treat as an error if 'errflg' is true otherwise its okay and return symbol to caller
else if symbol is an intrinsic attempt to remove symbol's intrinsic property otherwise it is an error
Definition at line 68 of file semsym.cpp.
References CNULL, ERR_Severe, error(), first, flg, gbl, insert_sym(), IS_INTRINSIC, newsym(), STB::ovclass, sptr, st, stb, SYMNAME, FLG::xref, and xrefput().
getocsym()
SPTR getocsym (SPTR sptr, int oclass)
Look up symbol matching overloading class of given symbol type.
The sptr is returned for the symbol whose overloading class matches the overloading class of the symbol type given. If no symbol is found in the given overloading class one is created. (If scoping becomes a Fortran feature, this routine will not use it)
Definition at line 141 of file semsym.cpp.
References first, flg, insert_sym(), STB::ovclass, sptr, st, stb, FLG::xref, and xrefput().
Referenced by newsym().
newsym()
SPTR newsym (SPTR sptr)
Reset fields of intrinsic or generic symbol, sptr, to zero in preparation for changing its symbol type by the Semantic Analyzer. If the symbol type of the symbol has been 'frozen', issue an error message and notify the caller by returning a zero symbol pointer.
Definition at line 166 of file semsym.cpp.
References CNULL, ERR_Informational, ERR_Severe, error(), gbl, getocsym(), getsym(), insert_sym(), LOCAL_SYMNAME, sptr, SPTR_NULL, strlen(), and SYMNAME.
Referenced by declref(), declsym(), and ref_ident().
ref_ident()
SPTR ref_ident (SPTR sptr)
Reference a symbol when it's known the context requires an identifier. If an error occurs (e.g., symbol which is frozen as an intrinsic), a new symbol is created so that processing can continue. If the symbol found is ST_UNKNOWN, its stype is changed to ST_IDENT.
Definition at line 208 of file semsym.cpp.
References insert_sym(), IS_INTRINSIC, newsym(), refsym(), and sptr.
refsym()
SPTR refsym (SPTR sptr, int oclass)
Look up a symbol having the given overloading class.
If the symbol with the overloading class is found its sptr is returned. If no symbol with the given overloading class is found, a new sptr is returned. (If scoping becomes a Fortran feature, this routine will implement it)
Definition at line 116 of file semsym.cpp.
References first, flg, insert_sym(), STB::ovclass, sptr, st, stb, FLG::xref, and xrefput().
Referenced by ref_ident().