flang: semsmp.c File Reference
semsmp.c File Reference
semantic analyzer routines which process SMP statements.
#include "gbldefs.h"
#include "global.h"
#include "gramsm.h"
#include "gramtk.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "semant.h"
#include "scan.h"
#include "semstk.h"
#include "ast.h"
#include "fdirect.h"
#include "pragma.h"
#include "mach.h"
#include "rte.h"
#include "llmputil.h"
#include "mp.h"
#include "atomic_common.h"
Classes
struct cl_tag
struct savcl_tag
Macros
#define CL_DEFAULT 0
#define CL_PRIVATE 1
#define CL_SHARED 2
#define CL_FIRSTPRIVATE 3
#define CL_LASTPRIVATE 4
#define CL_SCHEDULE 5
#define CL_ORDERED 6
#define CL_REDUCTION 7
#define CL_IF 8
#define CL_COPYIN 9
#define CL_COPYPRIVATE 10
#define CL_MP_SCHEDTYPE 11
#define CL_CHUNK 12
#define CL_NOWAIT 13
#define CL_NUM_THREADS 14
#define CL_COLLAPSE 15
#define CL_UNTIED 16
#define CL_COPYOUT 17
#define CL_LOCAL 18
#define CL_CACHE 19
#define CL_SHORTLOOP 20
#define CL_VECTOR 21
#define CL_PARALLEL 22
#define CL_SEQ 23
#define CL_HOST 24
#define CL_UNROLL 25
#define CL_KERNEL 26
#define CL_COPY 27
#define CL_MIRROR 28
#define CL_REFLECTED 29
#define CL_UPDATEHOST 30
#define CL_UPDATESELF 31
#define CL_UPDATEDEV 32
#define CL_INDEPENDENT 33
#define CL_WAIT 34
#define CL_CUFTILE 35
#define CL_KERNEL_GRID 36
#define CL_KERNEL_BLOCK 37
#define CL_SEQUNROLL 38
#define CL_PARUNROLL 39
#define CL_VECUNROLL 40
#define CL_CREATE 41
#define CL_ACCPRESENT 42
#define CL_ACCPCOPY 43
#define CL_ACCPCOPYIN 44
#define CL_ACCPCOPYOUT 45
#define CL_ACCPCREATE 46
#define CL_ACCPNOT 47
#define CL_ASYNC 48
#define CL_STREAM 49
#define CL_DEVICE 50
#define CL_WORKER 51
#define CL_GANG 52
#define CL_NUM_WORKERS 53
#define CL_NUM_GANGS 54
#define CL_VECTOR_LENGTH 55
#define CL_USE_DEVICE 56
#define CL_DEVICEPTR 57
#define CL_DEVICE_RESIDENT 58
#define CL_FINAL 59
#define CL_MERGEABLE 60
#define CL_DEVICEID 61
#define CL_ACCDELETE 62
#define CL_ACCPDELETE 63
#define CL_ACCLINK 64
#define CL_DEVICE_TYPE 65
#define CL_AUTO 66
#define CL_TILE 67
#define CL_GANGCHUNK 68
#define CL_DEFNONE 69
#define CL_NUM_GANGS2 70
#define CL_NUM_GANGS3 71
#define CL_GANGDIM 72
#define CL_DEFPRESENT 73
#define CL_FORCECOLLAPSE 74
#define CL_FINALIZE 75
#define CL_IFPRESENT 76
#define CL_SAFELEN 77
#define CL_SIMDLEN 78
#define CL_LINEAR 79
#define CL_ALIGNED 80
#define CL_USE_DEVICE_PTR 81
#define CL_DEPEND 82
#define CL_INBRANCH 83
#define CL_NOTINBRANCH 84
#define CL_UNIFORM 85
#define CL_GRAINSIZE 86
#define CL_NUM_TASKS 87
#define CL_NOGROUP 88
#define CL_OMPDEVICE 89
#define CL_MAP 90
#define CL_DEFAULTMAP 91
#define CL_TO 92
#define CL_LINK 93
#define CL_FROM 94
#define CL_NUM_TEAMS 95
#define CL_THREAD_LIMIT 96
#define CL_DIST_SCHEDULE 97
#define CL_PRIORITY 98
#define CL_IS_DEVICE_PTR 99
#define CL_SIMD 100
#define CL_THREADS 101
#define CL_DEVICE_NUM 102
#define CL_DEFAULT_ASYNC 103
#define CL_ACCDECL 104
#define CL_PROC_BIND 105
#define CL_ACCNO_CREATE 106
#define CL_ACCATTACH 107
#define CL_ACCDETACH 108
#define CL_ACCCOMPARE 109
#define CL_PGICOMPARE 110
#define CL_MAXV 111 /* This must be the last clause */
#define BT_PAR 0x001
#define BT_SINGLE 0x002
#define BT_PDO 0x004
#define BT_PARDO 0x008
#define BT_DOACROSS 0x010
#define BT_SECTS 0x020
#define BT_PARSECTS 0x040
#define BT_PARWORKS 0x080
#define BT_TASK 0x100
#define BT_ACCREG 0x200
#define BT_ACCKERNELS 0x400
#define BT_ACCPARALLEL 0x800
#define BT_ACCKDO 0x1000
#define BT_ACCPDO 0x2000
#define BT_ACCKLOOP 0x4000
#define BT_ACCPLOOP 0x8000
#define BT_ACCDATAREG 0x10000
#define BT_ACCDECL 0x20000
#define BT_ACCUPDATE 0x40000
#define BT_ACCENDREG 0x80000
#define BT_ACCSCALARREG 0x100000
#define BT_CUFKERNEL 0x200000
#define BT_ACCHOSTDATA 0x400000
#define BT_ACCENTERDATA 0x800000
#define BT_ACCEXITDATA 0x1000000
#define BT_SIMD 0x2000000
#define BT_TASKGROUP 0x4000000
#define BT_TASKLOOP 0x8000000
#define BT_TARGET 0x10000000
#define BT_DISTRIBUTE 0x20000000
#define BT_TEAMS 0x400000000
#define BT_DECLTARGET 0x800000000
#define BT_DECLSIMD 0x1000000000
#define BT_ACCINITSHUTDOWN 0x2000000000
#define BT_ACCSET 0x4000000000
#define BT_ACCSERIAL 0x8000000000
#define BT_ACCSLOOP 0x10000000000
#define CL_PRESENT(d) cl[d].present
#define CL_VAL(d) cl[d].val
#define CL_NAME(d) cl[d].name
#define CL_STMT(d) cl[d].stmt
#define CL_FIRST(d) cl[d].first
#define CL_LAST(d) cl[d].last
#define SAVCL_PRESENT(d) sav_cl[d].present
#define SAVCL_VAL(d) sav_cl[d].val /* sptr in some cases */
#define SAVCL_FIRST(d) sav_cl[d].first
#define SAVCL_LAST(d) sav_cl[d].last
#define OMP_DEFAULT 0x0
#define OMP_TARGET 0x1
#define OMP_TARGETDATA 0x2
#define OMP_TARGETENTERDATA 0x4
#define OMP_TARGETEXITDATA 0x8
#define OMP_TARGETUPDATE 0x10
#define OMP_PARALLEL 0x20
#define OMP_TASK 0x40
#define OMP_TASKLOOP 0x80
#define OPT_OMP_ATOMIC !XBIT(69,0x1000)
#define IN_WRKSHR 0
#define IN_PARALLEL 1
#define CSECT_PFX "__cs_"
Functions
static void add_clause (int, LOGICAL)
static bool clause_errchk (BIGINT64, const char *)
static void accel_pragmagen (int, int, int)
static int sched_type (char *)
static void set_iftype (int, char *, char *, char *)
static int cancel_type (char *)
static int emit_bpar (void)
static int emit_btarget (int)
static void do_schedule (int)
static void do_private (void)
static void do_firstprivate (int)
static void do_lastprivate (void)
static void do_reduction (void)
static void do_copyin (void)
static void do_copyprivate (void)
static int size_of_allocatable (int)
static void do_default_clause (int)
static void begin_parallel_clause (int)
static void end_reduction (REDUC *, int)
static void end_lastprivate (int)
static void end_workshare (int s_std, int e_std)
static void deallocate_privates (int)
static void add_assignment (int, SST *)
static void add_assignment_before (int, SST *, int)
static void add_ptr_assignment (int, SST *)
static void assign_cval (int, int, int)
static int enter_dir (int, LOGICAL, LOGICAL, BITMASK64)
static int leave_dir (int, LOGICAL, LOGICAL)
static const char * name_of_dir (int)
static int find_reduc_intrinsic (int)
static int get_csect_sym (const char *)
static int get_csect_pfxlen (void)
static void check_barrier (void)
static void check_crit (char *)
static int check_cancel (int)
static void check_targetdata (int, const char *)
static void check_valid_data_sharing (int)
static void cray_pointer_check (ITEM *, int)
static void other_firstlast_check (ITEM *, int)
static void non_private_check (int, const char *)
static void private_check ()
static void deallocate_no_scope_sptr ()
static int get_stblk_uplevel_sptr ()
static int add_firstprivate_assn (int, int, int)
static void begin_combine_constructs (BIGINT64)
static void end_targteams ()
static LOGICAL is_last_private (int)
static void mp_add_shared_var (int, int)
static void mk_reduction_list (void)
static void mk_shared_list (void)
static void mk_lastprivate_list (void)
static void save_private_list (void)
static void save_firstprivate_list (void)
static void save_shared_list (void)
static void restore_clauses (void)
static void do_bdistribute (int, LOGICAL)
static void do_bteams (int)
static int get_mp_bind_type (char *)
static LOGICAL is_valid_atomic_read (int, int)
static LOGICAL is_valid_atomic_write (int, int)
static LOGICAL is_valid_atomic_capture (int, int)
static LOGICAL is_valid_atomic_update (int, int)
static int mk_atomic_update_binop (int, int)
static int mk_atomic_update_intr (int, int)
static void do_map ()
static LOGICAL use_atomic_for_reduction (int d)
Decide whether to use llvm atomic for reduction or not. Atomic is used only for teams reduction.
static void add_pragma (int pragmatype, int pragmascope, int pragmaarg)
void semsmp (int rednum, SST *top)
Semantic analysis for SMP statements.
void parstuff_init (void)
static int get_iftype (int argcnt, char *nm1, char *nm2, char *nm3)
int emit_etarget ()
int emit_epar (void)
int emit_bcs_ecs (int opc)
static void do_dist_schedule (int doif, LOGICAL chk_collapse)
int do_distbegin (DOINFO *doinfo, int do_label, int construct_name)
static void mk_firstprivate (int sptr1, int taskdupstd)
static LOGICAL validate_atomic_expr (int lop, int rop, int read)
static int mk_atomic_read (int lop, int src)
static int mk_atomic_write (int lop, int rop)
static void _is_atomic_update_binop (int rop, int *arg)
static LOGICAL is_atomic_update_binop (int lop, int rop)
static LOGICAL is_atomic_update_intr (int lop, int rop)
static int mk_atomic_capture (int lop, int rop)
int do_openmp_atomics (SST *l_stktop, SST *r_stktop)
LOGICAL validate_omp_atomic (SST *l_stktop, SST *r_stktop)
int is_sptr_in_shared_list (int sptr)
void end_parallel_clause (int doif)
static ATOMIC_RMW_OP get_atomic_rmw_op (int op)
static void gen_reduction (REDUC *reducp, REDUC_SYM *reduc_symp, LOGICAL rmme, LOGICAL in_parallel)
static void do_btarget (int doif)
static void save_clauses ()
void end_teams ()
void end_target ()
int find_outer_sym (int sym)
int mk_storage (int sptr, SST *stkp)
void add_assign_firstprivate (int dstsym, int srcsym)
Add an assignment to the parallel prologue.
void add_non_private (int sptr)
void add_no_scope_sptr (int oldsptr, int newsptr, int lineno)
void clear_no_scope_sptr ()
void check_no_scope_sptr ()
void is_dovar_sptr (int sptr)
void par_add_stblk_shvar ()
static LLUplevel * findUplevelForSharedVar (int sptr, int stblk)
static bool needCharLen (int sptr)
static void parref_bnd (int ast, int stblk)
void set_parref_flag (int sptr, int psptr, int stblk)
void set_parref_flag2 (int sptr, int psptr, int std)
set_parref_flag set PARREF flag after semant phase
static void set_private_bnd_encl (int ast, int scope, int encl)
void set_private_encl (int old, int new)
void set_private_taskflag (int sptr)
static LOGICAL is_in_list (int clause, int sptr)
LOGICAL use_opt_atomic (int d)
Decide to use optimized atomic usage.
Variables
static struct cl_tag cl [CL_MAXV]
static struct savcl_tag sav_cl [CL_MAXV]
static int recent_loop_clause = 0
static int chunk
static int distchunk
static int mp_iftype
static ISZ_T kernel_do_nest
static LOGICAL has_team = FALSE
static LOGICAL any_pflsr_private = FALSE
static int kernel_argnum
struct {
int chunk
int distchunk
int mp_iftype
} sav_chk
Detailed Description
semantic analyzer routines which process SMP statements.
Definition in file semsmp.c.
Macro Definition Documentation
BT_ACCDATAREG
#define BT_ACCDATAREG 0x10000
Definition at line 264 of file semsmp.c.
BT_ACCDECL
#define BT_ACCDECL 0x20000
Definition at line 265 of file semsmp.c.
BT_ACCENDREG
#define BT_ACCENDREG 0x80000
Definition at line 267 of file semsmp.c.
BT_ACCENTERDATA
#define BT_ACCENTERDATA 0x800000
Definition at line 271 of file semsmp.c.
BT_ACCEXITDATA
#define BT_ACCEXITDATA 0x1000000
Definition at line 272 of file semsmp.c.
BT_ACCHOSTDATA
#define BT_ACCHOSTDATA 0x400000
Definition at line 270 of file semsmp.c.
BT_ACCINITSHUTDOWN
#define BT_ACCINITSHUTDOWN 0x2000000000
Definition at line 281 of file semsmp.c.
BT_ACCKDO
#define BT_ACCKDO 0x1000
Definition at line 260 of file semsmp.c.
BT_ACCKERNELS
#define BT_ACCKERNELS 0x400
Definition at line 258 of file semsmp.c.
BT_ACCKLOOP
#define BT_ACCKLOOP 0x4000
Definition at line 262 of file semsmp.c.
BT_ACCPARALLEL
#define BT_ACCPARALLEL 0x800
Definition at line 259 of file semsmp.c.
BT_ACCPDO
#define BT_ACCPDO 0x2000
Definition at line 261 of file semsmp.c.
BT_ACCPLOOP
#define BT_ACCPLOOP 0x8000
Definition at line 263 of file semsmp.c.
BT_ACCREG
#define BT_ACCREG 0x200
Definition at line 257 of file semsmp.c.
BT_ACCSCALARREG
#define BT_ACCSCALARREG 0x100000
Definition at line 268 of file semsmp.c.
BT_ACCSERIAL
#define BT_ACCSERIAL 0x8000000000
Definition at line 283 of file semsmp.c.
BT_ACCSET
#define BT_ACCSET 0x4000000000
Definition at line 282 of file semsmp.c.
BT_ACCSLOOP
#define BT_ACCSLOOP 0x10000000000
Definition at line 284 of file semsmp.c.
BT_ACCUPDATE
#define BT_ACCUPDATE 0x40000
Definition at line 266 of file semsmp.c.
BT_CUFKERNEL
#define BT_CUFKERNEL 0x200000
Definition at line 269 of file semsmp.c.
BT_DECLSIMD
#define BT_DECLSIMD 0x1000000000
Definition at line 280 of file semsmp.c.
BT_DECLTARGET
#define BT_DECLTARGET 0x800000000
Definition at line 279 of file semsmp.c.
BT_DISTRIBUTE
#define BT_DISTRIBUTE 0x20000000
Definition at line 277 of file semsmp.c.
BT_DOACROSS
#define BT_DOACROSS 0x010
Definition at line 252 of file semsmp.c.
BT_PAR
#define BT_PAR 0x001
Definition at line 248 of file semsmp.c.
BT_PARDO
#define BT_PARDO 0x008
Definition at line 251 of file semsmp.c.
BT_PARSECTS
#define BT_PARSECTS 0x040
Definition at line 254 of file semsmp.c.
BT_PARWORKS
#define BT_PARWORKS 0x080
Definition at line 255 of file semsmp.c.
BT_PDO
#define BT_PDO 0x004
Definition at line 250 of file semsmp.c.
BT_SECTS
#define BT_SECTS 0x020
Definition at line 253 of file semsmp.c.
BT_SIMD
#define BT_SIMD 0x2000000
Definition at line 273 of file semsmp.c.
BT_SINGLE
#define BT_SINGLE 0x002
Definition at line 249 of file semsmp.c.
BT_TARGET
#define BT_TARGET 0x10000000
Definition at line 276 of file semsmp.c.
BT_TASK
#define BT_TASK 0x100
Definition at line 256 of file semsmp.c.
BT_TASKGROUP
#define BT_TASKGROUP 0x4000000
Definition at line 274 of file semsmp.c.
BT_TASKLOOP
#define BT_TASKLOOP 0x8000000
Definition at line 275 of file semsmp.c.
BT_TEAMS
#define BT_TEAMS 0x400000000
Definition at line 278 of file semsmp.c.
CL_ACCATTACH
#define CL_ACCATTACH 107
Definition at line 239 of file semsmp.c.
CL_ACCCOMPARE
#define CL_ACCCOMPARE 109
Definition at line 241 of file semsmp.c.
CL_ACCDECL
#define CL_ACCDECL 104
Definition at line 236 of file semsmp.c.
CL_ACCDELETE
#define CL_ACCDELETE 62
Definition at line 194 of file semsmp.c.
CL_ACCDETACH
#define CL_ACCDETACH 108
Definition at line 240 of file semsmp.c.
CL_ACCLINK
#define CL_ACCLINK 64
Definition at line 196 of file semsmp.c.
CL_ACCNO_CREATE
#define CL_ACCNO_CREATE 106
Definition at line 238 of file semsmp.c.
CL_ACCPCOPY
#define CL_ACCPCOPY 43
Definition at line 175 of file semsmp.c.
CL_ACCPCOPYIN
#define CL_ACCPCOPYIN 44
Definition at line 176 of file semsmp.c.
CL_ACCPCOPYOUT
#define CL_ACCPCOPYOUT 45
Definition at line 177 of file semsmp.c.
CL_ACCPCREATE
#define CL_ACCPCREATE 46
Definition at line 178 of file semsmp.c.
CL_ACCPDELETE
#define CL_ACCPDELETE 63
Definition at line 195 of file semsmp.c.
CL_ACCPNOT
#define CL_ACCPNOT 47
Definition at line 179 of file semsmp.c.
CL_ACCPRESENT
#define CL_ACCPRESENT 42
Definition at line 174 of file semsmp.c.
CL_ALIGNED
#define CL_ALIGNED 80
Definition at line 212 of file semsmp.c.
CL_ASYNC
#define CL_ASYNC 48
Definition at line 180 of file semsmp.c.
CL_AUTO
#define CL_AUTO 66
Definition at line 198 of file semsmp.c.
CL_CACHE
#define CL_CACHE 19
Definition at line 151 of file semsmp.c.
CL_CHUNK
#define CL_CHUNK 12
Definition at line 144 of file semsmp.c.
CL_COLLAPSE
#define CL_COLLAPSE 15
Definition at line 147 of file semsmp.c.
CL_COPY
#define CL_COPY 27
Definition at line 159 of file semsmp.c.
CL_COPYIN
#define CL_COPYIN 9
Definition at line 141 of file semsmp.c.
CL_COPYOUT
#define CL_COPYOUT 17
Definition at line 149 of file semsmp.c.
CL_COPYPRIVATE
#define CL_COPYPRIVATE 10
Definition at line 142 of file semsmp.c.
CL_CREATE
#define CL_CREATE 41
Definition at line 173 of file semsmp.c.
CL_CUFTILE
#define CL_CUFTILE 35
Definition at line 167 of file semsmp.c.
CL_DEFAULT
#define CL_DEFAULT 0
Definition at line 132 of file semsmp.c.
CL_DEFAULT_ASYNC
#define CL_DEFAULT_ASYNC 103
Definition at line 235 of file semsmp.c.
CL_DEFAULTMAP
#define CL_DEFAULTMAP 91
Definition at line 223 of file semsmp.c.
CL_DEFNONE
#define CL_DEFNONE 69
Definition at line 201 of file semsmp.c.
CL_DEFPRESENT
#define CL_DEFPRESENT 73
Definition at line 205 of file semsmp.c.
CL_DEPEND
#define CL_DEPEND 82
Definition at line 214 of file semsmp.c.
CL_DEVICE
#define CL_DEVICE 50
Definition at line 182 of file semsmp.c.
CL_DEVICE_NUM
#define CL_DEVICE_NUM 102
Definition at line 234 of file semsmp.c.
CL_DEVICE_RESIDENT
#define CL_DEVICE_RESIDENT 58
Definition at line 190 of file semsmp.c.
CL_DEVICE_TYPE
#define CL_DEVICE_TYPE 65
Definition at line 197 of file semsmp.c.
CL_DEVICEID
#define CL_DEVICEID 61
Definition at line 193 of file semsmp.c.
CL_DEVICEPTR
#define CL_DEVICEPTR 57
Definition at line 189 of file semsmp.c.
CL_DIST_SCHEDULE
#define CL_DIST_SCHEDULE 97
Definition at line 229 of file semsmp.c.
CL_FINAL
#define CL_FINAL 59
Definition at line 191 of file semsmp.c.
CL_FINALIZE
#define CL_FINALIZE 75
Definition at line 207 of file semsmp.c.
CL_FIRST
#define CL_FIRST (d) cl[d].first
Definition at line 505 of file semsmp.c.
CL_FIRSTPRIVATE
#define CL_FIRSTPRIVATE 3
Definition at line 135 of file semsmp.c.
CL_FORCECOLLAPSE
#define CL_FORCECOLLAPSE 74
Definition at line 206 of file semsmp.c.
CL_FROM
#define CL_FROM 94
Definition at line 226 of file semsmp.c.
CL_GANG
#define CL_GANG 52
Definition at line 184 of file semsmp.c.
CL_GANGCHUNK
#define CL_GANGCHUNK 68
Definition at line 200 of file semsmp.c.
CL_GANGDIM
#define CL_GANGDIM 72
Definition at line 204 of file semsmp.c.
CL_GRAINSIZE
#define CL_GRAINSIZE 86
Definition at line 218 of file semsmp.c.
CL_HOST
#define CL_HOST 24
Definition at line 156 of file semsmp.c.
CL_IF
#define CL_IF 8
Definition at line 140 of file semsmp.c.
CL_IFPRESENT
#define CL_IFPRESENT 76
Definition at line 208 of file semsmp.c.
CL_INBRANCH
#define CL_INBRANCH 83
Definition at line 215 of file semsmp.c.
CL_INDEPENDENT
#define CL_INDEPENDENT 33
Definition at line 165 of file semsmp.c.
CL_IS_DEVICE_PTR
#define CL_IS_DEVICE_PTR 99
Definition at line 231 of file semsmp.c.
CL_KERNEL
#define CL_KERNEL 26
Definition at line 158 of file semsmp.c.
CL_KERNEL_BLOCK
#define CL_KERNEL_BLOCK 37
Definition at line 169 of file semsmp.c.
CL_KERNEL_GRID
#define CL_KERNEL_GRID 36
Definition at line 168 of file semsmp.c.
CL_LAST
#define CL_LAST (d) cl[d].last
Definition at line 506 of file semsmp.c.
CL_LASTPRIVATE
#define CL_LASTPRIVATE 4
Definition at line 136 of file semsmp.c.
CL_LINEAR
#define CL_LINEAR 79
Definition at line 211 of file semsmp.c.
CL_LINK
#define CL_LINK 93
Definition at line 225 of file semsmp.c.
CL_LOCAL
#define CL_LOCAL 18
Definition at line 150 of file semsmp.c.
CL_MAP
#define CL_MAP 90
Definition at line 222 of file semsmp.c.
CL_MAXV
#define CL_MAXV 111 /* This must be the last clause */
Definition at line 243 of file semsmp.c.
CL_MERGEABLE
#define CL_MERGEABLE 60
Definition at line 192 of file semsmp.c.
CL_MIRROR
#define CL_MIRROR 28
Definition at line 160 of file semsmp.c.
CL_MP_SCHEDTYPE
#define CL_MP_SCHEDTYPE 11
Definition at line 143 of file semsmp.c.
CL_NAME
#define CL_NAME (d) cl[d].name
Definition at line 503 of file semsmp.c.
CL_NOGROUP
#define CL_NOGROUP 88
Definition at line 220 of file semsmp.c.
CL_NOTINBRANCH
#define CL_NOTINBRANCH 84
Definition at line 216 of file semsmp.c.
CL_NOWAIT
#define CL_NOWAIT 13
Definition at line 145 of file semsmp.c.
CL_NUM_GANGS
#define CL_NUM_GANGS 54
Definition at line 186 of file semsmp.c.
CL_NUM_GANGS2
#define CL_NUM_GANGS2 70
Definition at line 202 of file semsmp.c.
CL_NUM_GANGS3
#define CL_NUM_GANGS3 71
Definition at line 203 of file semsmp.c.
CL_NUM_TASKS
#define CL_NUM_TASKS 87
Definition at line 219 of file semsmp.c.
CL_NUM_TEAMS
#define CL_NUM_TEAMS 95
Definition at line 227 of file semsmp.c.
CL_NUM_THREADS
#define CL_NUM_THREADS 14
Definition at line 146 of file semsmp.c.
CL_NUM_WORKERS
#define CL_NUM_WORKERS 53
Definition at line 185 of file semsmp.c.
CL_OMPDEVICE
#define CL_OMPDEVICE 89
Definition at line 221 of file semsmp.c.
CL_ORDERED
#define CL_ORDERED 6
Definition at line 138 of file semsmp.c.
CL_PARALLEL
#define CL_PARALLEL 22
Definition at line 154 of file semsmp.c.
CL_PARUNROLL
#define CL_PARUNROLL 39
Definition at line 171 of file semsmp.c.
CL_PGICOMPARE
#define CL_PGICOMPARE 110
Definition at line 242 of file semsmp.c.
CL_PRESENT
#define CL_PRESENT (d) cl[d].present
Definition at line 501 of file semsmp.c.
CL_PRIORITY
#define CL_PRIORITY 98
Definition at line 230 of file semsmp.c.
CL_PRIVATE
#define CL_PRIVATE 1
Definition at line 133 of file semsmp.c.
CL_PROC_BIND
#define CL_PROC_BIND 105
Definition at line 237 of file semsmp.c.
CL_REDUCTION
#define CL_REDUCTION 7
Definition at line 139 of file semsmp.c.
CL_REFLECTED
#define CL_REFLECTED 29
Definition at line 161 of file semsmp.c.
CL_SAFELEN
#define CL_SAFELEN 77
Definition at line 209 of file semsmp.c.
CL_SCHEDULE
#define CL_SCHEDULE 5
Definition at line 137 of file semsmp.c.
CL_SEQ
#define CL_SEQ 23
Definition at line 155 of file semsmp.c.
CL_SEQUNROLL
#define CL_SEQUNROLL 38
Definition at line 170 of file semsmp.c.
CL_SHARED
#define CL_SHARED 2
Definition at line 134 of file semsmp.c.
CL_SHORTLOOP
#define CL_SHORTLOOP 20
Definition at line 152 of file semsmp.c.
CL_SIMD
#define CL_SIMD 100
Definition at line 232 of file semsmp.c.
CL_SIMDLEN
#define CL_SIMDLEN 78
Definition at line 210 of file semsmp.c.
CL_STMT
#define CL_STMT (d) cl[d].stmt
Definition at line 504 of file semsmp.c.
CL_STREAM
#define CL_STREAM 49
Definition at line 181 of file semsmp.c.
CL_THREAD_LIMIT
#define CL_THREAD_LIMIT 96
Definition at line 228 of file semsmp.c.
CL_THREADS
#define CL_THREADS 101
Definition at line 233 of file semsmp.c.
CL_TILE
#define CL_TILE 67
Definition at line 199 of file semsmp.c.
CL_TO
#define CL_TO 92
Definition at line 224 of file semsmp.c.
CL_UNIFORM
#define CL_UNIFORM 85
Definition at line 217 of file semsmp.c.
CL_UNROLL
#define CL_UNROLL 25
Definition at line 157 of file semsmp.c.
CL_UNTIED
#define CL_UNTIED 16
Definition at line 148 of file semsmp.c.
CL_UPDATEDEV
#define CL_UPDATEDEV 32
Definition at line 164 of file semsmp.c.
CL_UPDATEHOST
#define CL_UPDATEHOST 30
Definition at line 162 of file semsmp.c.
CL_UPDATESELF
#define CL_UPDATESELF 31
Definition at line 163 of file semsmp.c.
CL_USE_DEVICE
#define CL_USE_DEVICE 56
Definition at line 188 of file semsmp.c.
CL_USE_DEVICE_PTR
#define CL_USE_DEVICE_PTR 81
Definition at line 213 of file semsmp.c.
CL_VAL
#define CL_VAL (d) cl[d].val
Definition at line 502 of file semsmp.c.
CL_VECTOR
#define CL_VECTOR 21
Definition at line 153 of file semsmp.c.
CL_VECTOR_LENGTH
#define CL_VECTOR_LENGTH 55
Definition at line 187 of file semsmp.c.
CL_VECUNROLL
#define CL_VECUNROLL 40
Definition at line 172 of file semsmp.c.
CL_WAIT
#define CL_WAIT 34
Definition at line 166 of file semsmp.c.
CL_WORKER
#define CL_WORKER 51
Definition at line 183 of file semsmp.c.
CSECT_PFX
#define CSECT_PFX "__cs_"
IN_PARALLEL
#define IN_PARALLEL 1
Definition at line 8342 of file semsmp.c.
IN_WRKSHR
#define IN_WRKSHR 0
Definition at line 8341 of file semsmp.c.
OMP_DEFAULT
#define OMP_DEFAULT 0x0
Definition at line 527 of file semsmp.c.
OMP_PARALLEL
#define OMP_PARALLEL 0x20
Definition at line 533 of file semsmp.c.
OMP_TARGET
#define OMP_TARGET 0x1
Definition at line 528 of file semsmp.c.
OMP_TARGETDATA
#define OMP_TARGETDATA 0x2
Definition at line 529 of file semsmp.c.
OMP_TARGETENTERDATA
#define OMP_TARGETENTERDATA 0x4
Definition at line 530 of file semsmp.c.
OMP_TARGETEXITDATA
#define OMP_TARGETEXITDATA 0x8
Definition at line 531 of file semsmp.c.
OMP_TARGETUPDATE
#define OMP_TARGETUPDATE 0x10
Definition at line 532 of file semsmp.c.
OMP_TASK
#define OMP_TASK 0x40
Definition at line 534 of file semsmp.c.
OMP_TASKLOOP
#define OMP_TASKLOOP 0x80
Definition at line 535 of file semsmp.c.
OPT_OMP_ATOMIC
#define OPT_OMP_ATOMIC !XBIT(69,0x1000)
Definition at line 553 of file semsmp.c.
SAVCL_FIRST
#define SAVCL_FIRST (d) sav_cl[d].first
Definition at line 523 of file semsmp.c.
SAVCL_LAST
#define SAVCL_LAST (d) sav_cl[d].last
Definition at line 524 of file semsmp.c.
SAVCL_PRESENT
#define SAVCL_PRESENT (d) sav_cl[d].present
Definition at line 521 of file semsmp.c.
SAVCL_VAL
#define SAVCL_VAL (d) sav_cl[d].val /* sptr in some cases */
Definition at line 522 of file semsmp.c.
Function Documentation
_is_atomic_update_binop()
static void _is_atomic_update_binop (int rop, int * arg) static
Definition at line 6846 of file semsmp.c.
References A_OPTYPEG, AOP_ADD, AOP_DIV, AOP_EQV, AOP_MUL, AOP_NEQV, AOP_OR, AOP_SUB, AOP_UNDEF, arg, cnt, lhs, SEM::mpaccatomic, OP_ADD, OP_DIV, OP_LAND, OP_LEQV, OP_LNEQV, OP_LOR, OP_MUL, OP_SUB, SEM::rmw_op, and sem.
Referenced by is_atomic_update_binop().
accel_pragmagen()
static void accel_pragmagen (int pragma, int pragma1, int pragma2) static
Definition at line 5978 of file semsmp.c.
Referenced by semsmp().
add_assign_firstprivate()
void add_assign_firstprivate (int dstsym, int srcsym)
Add an assignment to the parallel prologue.
Parameters
dstsym The symbol assigned to.
srcsym The symbol assigned from.
Definition at line 8922 of file semsmp.c.
References add_stmt_after(), assign(), assign_pointer(), ast, BLK_UPLEVEL_SPTR, SCOPESTACK::end_prologue, interr(), mk_id(), mk_stmt(), mk_storage(), SEM::parallel, S_IDENT, SEM::scope_level, SEM::scope_stack, sem, set_parref_flag(), SST_ASTP, SST_DTYPEP, SST_IDP, SST_SYMG, SST_SYMP, SEM::target, SEM::task, and void().
Referenced by sem_check_scope().
add_assignment()
static void add_assignment (int x, SST * y_stkp) static
Definition at line 8893 of file semsmp.c.
References add_stmt(), assign(), S_IDENT, SST_ASTP, SST_DTYPEP, SST_IDP, SST_SYMP, void(), and x.
Referenced by assign_cval(), end_lastprivate(), and mk_firstprivate().
add_assignment_before()
static void add_assignment_before (int x, SST * y_stkp, int std) static
Definition at line 8880 of file semsmp.c.
References add_stmt_before(), assign(), S_IDENT, SST_ASTP, SST_DTYPEP, SST_IDP, SST_SYMP, std, void(), and x.
Referenced by mk_firstprivate().
add_clause()
static void add_clause (int clause, LOGICAL one_only) static
Definition at line 5786 of file semsmp.c.
References CL_NAME, CL_PRESENT, error(), and gbl.
Referenced by begin_combine_constructs(), and semsmp().
add_firstprivate_assn()
static int add_firstprivate_assn (int sptr, int sptr1, int std) static
Definition at line 10009 of file semsmp.c.
References add(), add_stmt_after(), ast, astb, ASTB::i0, mk_id(), mk_stmt(), sem, sptr, std, STD_PREV, and SEM::task.
Referenced by mk_firstprivate().
add_no_scope_sptr()
void add_no_scope_sptr (int oldsptr, int newsptr, int lineno)
Definition at line 9579 of file semsmp.c.
References BZERO, DI_NOSCOPE_AVL, DI_NOSCOPE_BASE, DI_NOSCOPE_SIZE, SEM::doif_depth, gbl, i, lineno, NEED, and sem.
Referenced by sem_check_scope(), and semant3().
add_non_private()
void add_non_private (int sptr)
Definition at line 9554 of file semsmp.c.
References i, NEED, SEM::non_private_avail, SEM::non_private_base, SEM::non_private_size, sem, and sptr.
Referenced by _non_private().
add_pragma()
static void add_pragma (int pragmatype, int pragmascope, int pragmaarg) static
Definition at line 5811 of file semsmp.c.
References add_stmt(), ast, mk_stmt(), and void().
Referenced by semsmp().
add_ptr_assignment()
static void add_ptr_assignment (int x, SST * y_stkp) static
Definition at line 8906 of file semsmp.c.
References add_stmt(), assign_pointer(), mk_id(), S_IDENT, SST_ASTP, SST_DTYPEP, SST_IDP, SST_SYMG, SST_SYMP, void(), and x.
Referenced by end_lastprivate(), and mk_firstprivate().
assign_cval()
static void assign_cval (int sptr, int v, int d) static
Definition at line 8977 of file semsmp.c.
References add_assignment(), ast, d, mk_cval1(), S_CONST, sptr, SST_ASTP, SST_CVALP, SST_DTYPEP, and SST_IDP.
Referenced by semsmp().
begin_combine_constructs()
static void begin_combine_constructs (BIGINT64 construct) static
Definition at line 8619 of file semsmp.c.
References add_clause(), apply_nodepchk(), ast, begin_parallel_clause(), BT_DISTRIBUTE, BT_PAR, BT_PARDO, BT_SIMD, BT_TARGET, BT_TEAMS, chunk, CL_PRESENT, CL_SCHEDULE, CL_VAL, DI_ATOMIC_CAPTURE, DI_B, DI_BPAR, DI_BTARGET, DI_DISTPARDO, DI_DISTRIBUTE, DI_PAR, DI_PARDO, DI_SCH_STATIC, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TEAMS, DI_TEAMSDIST, DI_TEAMSDISTPARDO, do_bdistribute(), do_btarget(), do_bteams(), do_schedule(), SEM::doif_depth, emit_bpar(), enter_dir(), ERR_Severe, error(), errwarn(), SEM::expect_dist_do, SEM::expect_do, FALSE, flg, gbl, has_team, mode_target_parallel_for, mode_target_parallel_for_simd, mode_target_teams, mode_target_teams_distribute, mode_target_teams_distribute_parallel_for, mode_target_teams_distribute_parallel_for_simd, mp_create_bscope(), FLG::omptarget, par_push_scope(), parstuff_init(), restore_clauses(), save_clauses(), sem, and TRUE.
Referenced by semsmp().
begin_parallel_clause()
static void begin_parallel_clause (int doif) static
Definition at line 7776 of file semsmp.c.
References add_stmt(), ast, DI_DISTPARDO, DI_DISTRIBUTE, DI_DOACROSS, DI_ID, DI_PAR, DI_PARDO, DI_PARSECTS, DI_PARWORKS, DI_PDO, DI_SECTS, DI_SIMD, DI_SINGLE, DI_TARGET, DI_TARGPARDO, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TASK, DI_TASKLOOP, DI_TEAMS, DI_TEAMSDIST, DI_TEAMSDISTPARDO, do_copyin(), do_default_clause(), do_firstprivate(), do_lastprivate(), do_map(), do_private(), do_reduction(), FLANG_FALLTHROUGH, mk_stmt(), private_check(), and void().
Referenced by begin_combine_constructs(), do_bdistribute(), do_btarget(), do_bteams(), do_distbegin(), and semsmp().
cancel_type()
static int cancel_type (char * nm) static
Definition at line 6013 of file semsmp.c.
References error(), gbl, NULL, and sem_strcmp().
Referenced by check_cancel(), and semsmp().
check_barrier()
static void check_barrier (void) static
Definition at line 9300 of file semsmp.c.
References DI_CRITICAL, DI_ID, DI_MASTER, DI_ORDERED, DI_PAR, DI_PARDO, DI_PARSECTS, DI_PDO, DI_SECTS, DI_SINGLE, DI_TARGPARDO, DI_TASK, DI_TASKLOOP, SEM::doif_depth, error(), gbl, NULL, prev, and sem.
Referenced by semsmp().
check_cancel()
static int check_cancel (int cancel_type) static
Definition at line 9401 of file semsmp.c.
References A_ORDEREDG, cancel_type(), DI_BEGINP, DI_BPAR, DI_DO, DI_DO_AST, DI_ID, DI_PAR, DI_PARSECTS, DI_PDO, DI_SECTS, DI_TASK, SEM::doif_depth, error(), gbl, NULL, prev, res, and sem.
Referenced by semsmp().
check_crit()
static void check_crit (char * nm) static
Definition at line 9329 of file semsmp.c.
References DI_CRITICAL, DI_CRITSYM, DI_ID, SEM::doif_depth, error(), gbl, get_csect_pfxlen(), NULL, prev, sem, sptr, and SYMNAME.
Referenced by semsmp().
check_no_scope_sptr()
void check_no_scope_sptr (void)
Definition at line 9627 of file semsmp.c.
References clear_no_scope_sptr(), DI_NOSCOPE_AVL, DI_NOSCOPE_BASE, DI_NOSCOPE_FORALL, SEM::doif_depth, error(), gbl, i, sem, and SYMNAME.
Referenced by semant1(), and semant3().
check_targetdata()
static void check_targetdata (int type, const char * nm) static
Definition at line 9354 of file semsmp.c.
References BT_TARGET, CL_DEPEND, CL_FROM, CL_IF, CL_MAP, CL_MAXV, CL_NAME, CL_NOWAIT, CL_OMPDEVICE, CL_PRESENT, CL_TO, CL_USE_DEVICE_PTR, clause_errchk(), error(), gbl, i, OMP_TARGET, OMP_TARGETDATA, OMP_TARGETENTERDATA, OMP_TARGETEXITDATA, OMP_TARGETUPDATE, and type.
Referenced by semsmp().
check_valid_data_sharing()
static void check_valid_data_sharing (int sptr) static
Definition at line 10216 of file semsmp.c.
References CL_FIRSTPRIVATE, CL_PRIVATE, CL_SHARED, count, ERR_Severe, error(), gbl, is_in_list(), is_last_private(), sptr, and SYMNAME.
Referenced by semsmp().
clause_errchk()
static bool clause_errchk (BIGINT64 bt, const char * dirname) static
Definition at line 5796 of file semsmp.c.
References CL_MAXV, CL_NAME, CL_PRESENT, CL_STMT, dirname, error(), gbl, and i.
Referenced by check_targetdata(), and semsmp().
clear_no_scope_sptr()
void clear_no_scope_sptr (void)
Definition at line 9610 of file semsmp.c.
References DI_NOSCOPE_AVL, DI_NOSCOPE_BASE, SEM::doif_depth, i, pop_sym(), and sem.
Referenced by check_no_scope_sptr(), and semant3().
cray_pointer_check()
static void cray_pointer_check (ITEM * itp, int clause) static
Definition at line 9501 of file semsmp.c.
References CL_NAME, error(), gbl, ITEM_END, itemp, sptr, and SYMNAME.
Referenced by semsmp().
deallocate_no_scope_sptr()
static void deallocate_no_scope_sptr () static
Definition at line 9599 of file semsmp.c.
References DI_NOSCOPE_AVL, DI_NOSCOPE_BASE, DI_NOSCOPE_SIZE, SEM::doif_depth, FREE, NULL, and sem.
Referenced by leave_dir().
deallocate_privates()
static void deallocate_privates (int doif) static
Definition at line 8781 of file semsmp.c.
References DI_ALLOCATED, gen_conditional_dealloc(), itemp, mk_id(), NULL, and STD_PREV.
Referenced by end_parallel_clause().
do_bdistribute()
static void do_bdistribute (int doif, LOGICAL chk_collapse) static
Definition at line 8439 of file semsmp.c.
References add_stmt(), ast, begin_parallel_clause(), DI_BDISTRIBUTE, do_dist_schedule(), get_stblk_uplevel_sptr(), mk_stmt(), par_push_scope(), and TRUE.
Referenced by begin_combine_constructs(), and semsmp().
do_btarget()
static void do_btarget (int doif) static
Definition at line 8404 of file semsmp.c.
References begin_parallel_clause(), DI_BTARGET, emit_btarget(), mp_create_bscope(), par_push_scope(), and TRUE.
Referenced by begin_combine_constructs().
do_bteams()
static void do_bteams (int doif) static
Definition at line 8413 of file semsmp.c.
References add_stmt(), ast, begin_parallel_clause(), CL_NUM_TEAMS, CL_PRESENT, CL_THREAD_LIMIT, CL_VAL, DI_BTEAMS, FALSE, mk_stmt(), mp_create_bscope(), par_push_scope(), sem, and SEM::teams.
Referenced by begin_combine_constructs(), and semsmp().
do_copyin()
static void do_copyin (void) static
Definition at line 7520 of file semsmp.c.
References add_stmt(), ast, astb, BLK_UPLEVEL_SPTR, CL_COPYIN, CL_FIRST, CL_PRESENT, error(), gbl, get_stblk_uplevel_sptr(), ASTB::i0, ITEM_END, itemp, mk_stmt(), mp_add_shared_var(), SEM::parallel, refsym(), SEM::scope_level, sem, size_of_allocatable(), sptr, SYMNAME, SEM::target, SEM::task, SEM::teams, and void().
Referenced by begin_parallel_clause().
do_copyprivate()
static void do_copyprivate (void) static
Definition at line 7573 of file semsmp.c.
References add_stmt(), ast, astb, CL_COPYPRIVATE, CL_FIRST, CL_PRESENT, error(), gbl, ASTB::i0, ITEM_END, itemp, mk_stmt(), refsym(), size_of_allocatable(), sptr, SYMNAME, and void().
Referenced by semsmp().
do_default_clause()
static void do_default_clause (int doif) static
Definition at line 7677 of file semsmp.c.
References CL_DEFAULT, CL_FIRST, CL_PRESENT, CL_SHARED, CL_VAL, DI_ID, DI_TASK, SCOPESTACK::end_prologue, getitem(), ITEM_END, itemp, scope_sym_tag::next, NULL, SCOPESTACK::par_scope, PAR_SCOPE_SHARED, PAR_SCOPE_TASKNODEFAULT, scope_sym_tag::scope, SEM::scope_level, SEM::scope_stack, sem, SCOPESTACK::shared_list, sptr, scope_sym_tag::sptr, SCOPESTACK::sptr, and STD_PREV.
Referenced by begin_parallel_clause().
do_dist_schedule()
static void do_dist_schedule (int doif, LOGICAL chk_collapse) static
Definition at line 6370 of file semsmp.c.
References add_stmt(), ast, BLK_SYM, BLK_UPLEVEL_SPTR, CL_COLLAPSE, CL_DIST_SCHEDULE, CL_ORDERED, CL_PRESENT, CL_VAL, SEM::collapse, DI_CHUNK, DI_DISTCHUNK, DI_IS_ORDERED, DI_ISSIMD, DI_SCH_DIST_STATIC, DI_SCHED_TYPE, distchunk, DT_INT, get_itemp(), mk_assn_stmt(), mk_id(), SEM::scope_level, sem, set_parref_flag(), sptr, and void().
Referenced by do_bdistribute().
do_distbegin()
int do_distbegin (DOINFO * doinfo, int do_label, int construct_name)
Definition at line 6411 of file semsmp.c.
References A_ORDEREDP, A_SCHED_TYPEP, add_stmt(), begin_parallel_clause(), BLK_UPLEVEL_SPTR, CL_COLLAPSE, CL_PRESENT, CL_VAL, DOINFO::collapse, SEM::collapse, collapse_begin(), SEM::collapse_depth, construct_name, dast(), decl_private_sym(), DI_ALLOCATED, DI_BPAR, DI_DISTCHUNK, DI_DO, DI_DO_AST, DI_DO_LABEL, DI_DOINFO, DI_IS_ORDERED, DI_LASTPRIVATE, DI_NAME, DI_PARDO, DI_REDUC, DI_REGIONVARS, DI_SCHED_TYPE, DI_SECT_VAR, direct_loop_enter(), DOINFO::distloop, do_begin(), do_label, do_lastval(), do_parbegin(), do_schedule(), DOCHK, SEM::doif_depth, DT_ISINT, emit_bpar(), ERR_Severe, error(), SEM::expect_dist_do, SEM::expect_do, FALSE, gbl, get_doinfo(), getccssym_sc(), has_team, DOINFO::index_var, DOINFO::init_expr, SEM::itemps, DOINFO::lastval_var, DOINFO::limit_expr, LP_DISTPARDO, LP_PARDO_OTHER, mk_assn_stmt(), mk_id(), mk_lastprivate_list(), mk_reduction_list(), mk_shared_list(), mk_stmt(), mp_create_bscope(), NEED_DOIF, NULL, par_push_scope(), past(), prev, DOINFO::prev_dovar, ref_object(), restore_clauses(), SEM::scope_level, sem, set_parref_flag(), sptr, DOINFO::step_expr, SYMNAME, SEM::teams, TRUE, and void().
Referenced by semant3().
do_firstprivate()
static void do_firstprivate (int istask) static
Definition at line 6647 of file semsmp.c.
References add_stmt(), ast, CL_FIRST, CL_FIRSTPRIVATE, CL_PRESENT, FALSE, FREE, get_stblk_uplevel_sptr(), i, ITEM_END, itemp, llmp_has_uplevel(), mk_firstprivate(), mk_stmt(), NEED, NEW, NULL, SEM::parallel, LLUplevel::parent, sem, sptr, SPTR_NULL, TRUE, LLUplevel::vals, and LLUplevel::vals_count.
Referenced by begin_parallel_clause().
do_lastprivate()
static void do_lastprivate (void) static
Definition at line 6711 of file semsmp.c.
References BLK_UPLEVEL_SPTR, CL_FIRST, CL_LASTPRIVATE, CL_PRESENT, curr_scope(), decl_private_sym(), DI_ID, DI_LASTPRIVATE, DI_PAR, DI_PARDO, DI_PARSECTS, DI_PARWORKS, DI_PDO, DI_SECTS, DI_SINGLE, SEM::doif_depth, ERR_Severe, error(), gbl, is_last_private(), reduc_sym::next, next_scope(), non_private_check(), reduc_sym::Private, scope, SEM::scope_level, sem, set_parref_flag(), reduc_sym::shared, sptr, and SYMNAME.
Referenced by begin_parallel_clause().
do_map()
static void do_map () static
Definition at line 7613 of file semsmp.c.
References add_stmt(), ast, xyyz::ast, CL_FIRST, CL_MAP, CL_PRESENT, xyyz::cltype, flg, ITEM_END, mk_stmt(), xyyz::next, FLG::omptarget, xyyz::t, and void().
Referenced by begin_parallel_clause(), and semsmp().
do_openmp_atomics()
int do_openmp_atomics (SST * l_stktop, SST * r_stktop)
Definition at line 7019 of file semsmp.c.
References SEM::action_type, add_stmt(), AOP_UNDEF, SEM::apply, ast, ATOMIC_CAPTURE, ATOMIC_READ, ATOMIC_UPDATE, ATOMIC_WRITE, CNULL, DTY, DTYG, error(), FALSE, gbl, SEM::mem_order, mk_atomic_capture(), mk_atomic_read(), mk_atomic_update_binop(), mk_atomic_update_intr(), mk_atomic_write(), mkexpr1(), mklvalue(), MO_UNDEF, SEM::mpaccatomic, SEM::rmw_op, SEM::seen, sem, SST_ASTG, SST_ASTP, SST_DTYPEG, SST_SHAPEG, TRUE, validate_atomic_expr(), and void().
Referenced by semant3().
do_private()
static void do_private (void) static
Definition at line 6578 of file semsmp.c.
References CL_FIRST, CL_PRESENT, CL_PRIVATE, decl_private_sym(), ITEM_END, itemp, non_private_check(), and void().
Referenced by begin_parallel_clause().
do_reduction()
static void do_reduction (void) static
Definition at line 7245 of file semsmp.c.
References add_stmt(), assign(), ast, BLK_UPLEVEL_SPTR, CL_FIRST, CL_PRESENT, CL_REDUCTION, DDTG, decl_private_sym(), DI_REDUC, SEM::doif_depth, DT_DBLE, DT_INT, DT_ISINT, DT_LOG, DT_REAL, getcon(), interr(), reduc_tag::intrin, lhs, reduc_tag::list, mk_cval1(), mk_storage(), reduc_sym::next, reduc_tag::next, OP_ADD, OP_LAND, OP_LEQV, OP_LNEQV, OP_LOG, OP_LOR, OP_MUL, OP_SUB, reduc_tag::opr, reduc_sym::Private, S_CONST, SCFTN_FALSE, SCFTN_TRUE, SEM::scope_level, sem, set_parref_flag(), reduc_sym::shared, size_of(), SST_ASTP, SST_CVALP, SST_DTYPEP, SST_IDP, SYMNAME, val, and void().
Referenced by begin_parallel_clause().
do_schedule()
static void do_schedule (int doif) static
Definition at line 6321 of file semsmp.c.
References add_stmt(), ast, BLK_SYM, BLK_UPLEVEL_SPTR, chunk, CL_COLLAPSE, CL_MP_SCHEDTYPE, CL_ORDERED, CL_PRESENT, CL_SCHEDULE, CL_VAL, SEM::collapse, DI_CHUNK, DI_DISTCHUNK, DI_IS_ORDERED, DI_ISSIMD, DI_SCH_AUTO, DI_SCH_DYNAMIC, DI_SCH_GUIDED, DI_SCH_RUNTIME, DI_SCH_STATIC, DI_SCHED_TYPE, DT_INT, error(), gbl, get_itemp(), mk_assn_stmt(), mk_id(), NULL, SEM::scope_level, sem, set_parref_flag(), sptr, void(), and XBIT.
Referenced by begin_combine_constructs(), do_distbegin(), and semsmp().
emit_bcs_ecs()
int emit_bcs_ecs (int opc)
Definition at line 6304 of file semsmp.c.
References add_stmt(), assert, ast, DI_CRITICAL, DI_IN_NEST, SEM::doif_depth, mk_stmt(), sem, and void().
Referenced by end_reduction(), gen_reduction(), semant1(), and semsmp().
emit_bpar()
static int emit_bpar (void) static
Definition at line 6248 of file semsmp.c.
References add_stmt(), ast, CL_IF, CL_NUM_THREADS, CL_PRESENT, CL_PROC_BIND, CL_VAL, error(), gbl, mk_stmt(), mp_iftype, NULL, OMP_DEFAULT, OMP_PARALLEL, SEM::parallel, sem, and void().
Referenced by begin_combine_constructs(), do_distbegin(), and semsmp().
emit_btarget()
static int emit_btarget (int atype) static
Definition at line 6212 of file semsmp.c.
References add_stmt(), ast, CL_DEPEND, CL_IF, CL_NOWAIT, CL_PRESENT, CL_VAL, error(), gbl, mk_stmt(), mp_iftype, NULL, OMP_DEFAULT, OMP_TARGET, sem, SEM::target, and void().
Referenced by do_btarget(), and semsmp().
emit_epar()
int emit_epar (void)
Definition at line 6284 of file semsmp.c.
References add_stmt(), ast, mk_stmt(), SEM::parallel, sem, and void().
Referenced by do_end(), and semsmp().
emit_etarget()
int emit_etarget (void)
Definition at line 6236 of file semsmp.c.
References add_stmt(), ast, mk_stmt(), sem, SEM::target, and void().
Referenced by do_end(), end_target(), and semsmp().
end_lastprivate()
static void end_lastprivate (int doif) static
Definition at line 8248 of file semsmp.c.
References add_assignment(), add_ptr_assignment(), add_stmt(), astb, DI_DISTPARDO, DI_DISTRIBUTE, DI_DOACROSS, DI_DOINFO, DI_ID, DI_LASTPRIVATE, DI_PARDO, DI_PARSECTS, DI_PDO, DI_SECT_CNT, DI_SECT_VAR, DI_SECTS, DI_SIMD, DI_TARGPARDO, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TASKLOOP, DI_TEAMSDIST, DI_TEAMSDISTPARDO, FALSE, SEM::ignore_default_none, ASTB::k0, mk_binop(), mk_cval1(), mk_id(), mk_stmt(), mk_storage(), reduc_sym::next, NULL, OP_EQ, OP_NE, SEM::parallel, reduc_sym::Private, sem, reduc_sym::shared, sptr, SEM::target, SEM::teams, TRUE, and void().
Referenced by end_parallel_clause().
end_parallel_clause()
void end_parallel_clause (int doif)
Definition at line 7912 of file semsmp.c.
References add_stmt(), ast, deallocate_privates(), DI_DISTPARDO, DI_DISTRIBUTE, DI_DOACROSS, DI_ID, DI_PAR, DI_PARDO, DI_PARSECTS, DI_PARWORKS, DI_PDO, DI_REDUC, DI_SECTS, DI_SIMD, DI_SINGLE, DI_TARGET, DI_TARGPARDO, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TASK, DI_TASKLOOP, DI_TEAMS, DI_TEAMSDIST, DI_TEAMSDISTPARDO, end_lastprivate(), end_reduction(), FLANG_FALLTHROUGH, mk_stmt(), and void().
Referenced by do_end(), end_target(), end_teams(), and semsmp().
end_reduction()
static void end_reduction (REDUC * red, int doif) static
Definition at line 8161 of file semsmp.c.
References add_stmt(), DI_ID, DI_SIMD, SEM::doif_depth, emit_bcs_ecs(), FALSE, gen_reduction(), SEM::ignore_default_none, reduc_tag::list, mk_stmt(), reduc_sym::next, reduc_tag::next, NULL, SEM::parallel, sem, reduc_sym::shared, SEM::target, SEM::teams, TRUE, use_atomic_for_reduction(), and void().
Referenced by end_parallel_clause(), and gen_reduction().
end_target()
void end_target ()
Definition at line 8758 of file semsmp.c.
References ast, DI_BTARGET, DI_TARGET, SEM::doif_depth, emit_etarget(), end_parallel_clause(), leave_dir(), mp_create_escope(), par_pop_scope(), sem, SEM::target, TRUE, and void().
Referenced by end_targteams(), and semant1().
end_targteams()
void end_targteams () static
Definition at line 8774 of file semsmp.c.
References end_target(), and end_teams().
Referenced by semsmp().
end_teams()
void end_teams ()
Definition at line 8741 of file semsmp.c.
References add_stmt(), ast, DI_BTEAMS, DI_TEAMS, SEM::doif_depth, end_parallel_clause(), leave_dir(), mk_stmt(), mp_create_escope(), par_pop_scope(), sem, SEM::teams, TRUE, and void().
Referenced by end_targteams(), semant1(), and semsmp().
end_workshare()
static void end_workshare (int s_std, int e_std) static
Definition at line 8344 of file semsmp.c.
References ast, error(), IN_PARALLEL, IN_WRKSHR, NULL, std, STD_AST, STD_LINENO, and STD_NEXT.
Referenced by semsmp().
enter_dir()
static int enter_dir (int typ, LOGICAL ignore_nested, LOGICAL ignore_sev, BITMASK64 illegal_region) static
Definition at line 8991 of file semsmp.c.
References DI_ALLOCATED, DI_B, DI_ID, DI_LASTPRIVATE, DI_NEST, DI_PAR, DI_PDO, DI_REDUC, DI_REGIONVARS, DI_SECT_VAR, DI_SECTS, DI_SINGLE, SEM::doif_depth, error(), FALSE, gbl, name_of_dir(), NEED_DOIF, NULL, prev, sem, and TRUE.
Referenced by begin_combine_constructs(), and semsmp().
find_outer_sym()
int find_outer_sym (int sym)
This function includes the actions performed by the production <var ref> ::= <ident> in the context of starting a parallel region or in the context of a parallel region. In either case, the symbol returned is the 'outer' symbol upon which the private symbol is based. In addition:
if the symbol is a function entry, refer to its local variable,
if the symbol is based, its associated pointer variable is created.
if the symbol is not yet a variable, it will be classified as if it was declared in the outer/nonparallel region.
Definition at line 8805 of file semsmp.c.
References STB::curr_scope, DCLCHK, gbl, insert_sym(), IS_INTRINSIC, newsym(), ref_based_object(), ref_entry(), refsym(), RU_FUNC, sem_set_storage_class(), setimplicit(), sptr, stb, and void().
Referenced by semant2(), and semsmp().
find_reduc_intrinsic()
static int find_reduc_intrinsic (int ident) static
Definition at line 9203 of file semsmp.c.
References error(), gbl, interr(), sptr, and SYMNAME.
Referenced by semsmp().
findUplevelForSharedVar()
static LLUplevel * findUplevelForSharedVar (int sptr, int stblk) static
Definition at line 9671 of file semsmp.c.
References assert, llmp_get_parent_sptr(), llmp_get_uplevel(), llmp_outermost_uplevel(), llmp_parent_uplevel(), NULL, and sptr.
Referenced by mp_add_shared_var().
gen_reduction()
static void gen_reduction (REDUC * reducp, REDUC_SYM * reduc_symp, LOGICAL rmme, LOGICAL in_parallel) static
Definition at line 8024 of file semsmp.c.
References add_stmt(), AOP_UNDEF, assign(), ast, binop(), BLK_SYM, SEM::doif_depth, emit_bcs_ecs(), end_reduction(), FALSE, FLANG_FALLTHROUGH, get_atomic_rmw_op(), getitem(), interr(), reduc_tag::intrin, ITEM_END, lhs, SEM::mem_order, mk_atomic_update_binop(), mk_atomic_update_intr(), mk_binop(), mk_cval1(), mk_stmt(), mk_storage(), mklvalue(), MO_SEQ_CST, SEM::mpaccatomic, xyyz::next, OP_ADD, OP_LOG, OP_MUL, OP_SUB, reduc_tag::opr, reduc_sym::Private, ref_intrin(), SEM::rmw_op, S_CONST, S_IDENT, scope, SEM::scope_level, sem, reduc_sym::shared, sptr, SST_ASTG, SST_ASTP, SST_CVALG, SST_DTYPEG, SST_IDG, SST_IDP, SST_OPCP, SST_OPTYPEP, SST_SHAPEP, SST_SYMP, xyyz::stkp, xyyz::t, TRUE, use_atomic_for_reduction(), and void().
Referenced by end_reduction().
get_atomic_rmw_op()
static ATOMIC_RMW_OP get_atomic_rmw_op (int op) static
Definition at line 7999 of file semsmp.c.
References AOP_ADD, AOP_AND, AOP_DIV, AOP_EQV, AOP_MUL, AOP_NEQV, AOP_OR, AOP_SUB, AOP_UNDEF, OP_ADD, OP_DIV, OP_LAND, OP_LEQV, OP_LNEQV, OP_LOR, OP_MUL, and OP_SUB.
Referenced by gen_reduction().
get_csect_pfxlen()
static int get_csect_pfxlen (void) static
Definition at line 9294 of file semsmp.c.
References CSECT_PFX, and strlen().
Referenced by check_crit(), and semsmp().
get_csect_sym()
static int get_csect_sym (const char * nm) static
Definition at line 9228 of file semsmp.c.
References AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_UPAST, AD_UPBD, astb, ASTB::bnd, CMEMLP, CSECT_PFX, ASTB::dtype, gbl, get_array_dtype(), get_next_sym(), getsymf(), mk_isz_cval(), NOSYM, refsym_inscope(), sptr, SYMNAME, and XBIT.
Referenced by semsmp().
get_iftype()
static int get_iftype (int argcnt, char * nm1, char * nm2, char * nm3) static
Definition at line 6030 of file semsmp.c.
References ERR_Severe, error(), gbl, IF_PARALLEL, IF_TARGET, IF_TARGETDATA, IF_TARGETENTERDATA, IF_TARGETEXITDATA, IF_TARGETUPDATE, IF_TASK, and IF_TASKLOOP.
Referenced by set_iftype().
get_mp_bind_type()
static int get_mp_bind_type (char * nm) static
Definition at line 9475 of file semsmp.c.
References CNULL, DT_INT, error(), gbl, getcon(), mk_cnst(), and val.
Referenced by semsmp().
get_stblk_uplevel_sptr()
static int get_stblk_uplevel_sptr () static
Definition at line 6178 of file semsmp.c.
References BLK_SCOPE_SPTR, BLK_UPLEVEL_SPTR, SEM::blksymnum, getccsym(), i, llmp_create_uplevel(), scope, SEM::scope_level, sem, and sptr.
Referenced by do_bdistribute(), do_copyin(), do_firstprivate(), semsmp(), and set_parref_flag().
is_atomic_update_binop()
static LOGICAL is_atomic_update_binop (int lop, int rop) static
Definition at line 6897 of file semsmp.c.
References _is_atomic_update_binop(), AOP_UNDEF, arg, ast_traverse(), ast_unvisit(), ast_visit(), FALSE, SEM::mpaccatomic, NULL, SEM::rmw_op, sem, and TRUE.
Referenced by is_valid_atomic_capture(), is_valid_atomic_update(), and mk_atomic_update_binop().
is_atomic_update_intr()
static LOGICAL is_atomic_update_intr (int lop, int rop) static
Definition at line 6916 of file semsmp.c.
References A_ARGCNTG, AOP_AND, AOP_EQV, AOP_MAX, AOP_MIN, AOP_NEQV, AOP_OR, AOP_UNDEF, AOP_XOR, argt, ARGT_ARG, cnt, CNULL, ERR_Severe, error(), FALSE, gbl, i, SEM::mpaccatomic, SEM::rmw_op, sem, and TRUE.
Referenced by is_valid_atomic_capture(), is_valid_atomic_update(), and mk_atomic_update_intr().
is_dovar_sptr()
void is_dovar_sptr (int sptr)
Definition at line 9652 of file semsmp.c.
References DI_NOSCOPE_AVL, DI_NOSCOPE_BASE, SEM::doif_depth, i, sem, and sptr.
Referenced by semant2(), semant3(), and semantio().
is_in_list()
static LOGICAL is_in_list (int clause, int sptr) static
Definition at line 10070 of file semsmp.c.
References CL_FIRST, FALSE, ITEM_END, xyyz::next, sptr, xyyz::sptr, xyyz::t, and TRUE.
Referenced by check_valid_data_sharing().
is_last_private()
static LOGICAL is_last_private (int sptr) static
Definition at line 10057 of file semsmp.c.
References CL_FIRST, CL_LASTPRIVATE, FALSE, reduc_sym::next, reduc_sym::Private, reduc_sym::shared, sptr, and TRUE.
Referenced by check_valid_data_sharing(), and do_lastprivate().
is_sptr_in_shared_list()
int is_sptr_in_shared_list (int sptr)
Definition at line 7747 of file semsmp.c.
References SCOPESTACK::kind, list, SCOPESTACK::rgn_scope, SEM::scope_level, SCOPE_PAR, SEM::scope_stack, sem, SCOPESTACK::shared_list, and sptr.
is_valid_atomic_capture()
static LOGICAL is_valid_atomic_capture (int lop, int rop) static
Definition at line 7172 of file semsmp.c.
References AOP_UNDEF, CNULL, contains_ast(), ERR_Severe, error(), FALSE, gbl, is_atomic_update_binop(), is_atomic_update_intr(), SEM::mpaccatomic, SEM::rmw_op, sem, TRUE, and validate_atomic_expr().
Referenced by mk_atomic_capture(), and validate_omp_atomic().
is_valid_atomic_read()
static LOGICAL is_valid_atomic_read (int lop, int rop) static
Definition at line 7142 of file semsmp.c.
References FALSE, TRUE, and validate_atomic_expr().
Referenced by mk_atomic_read(), and validate_omp_atomic().
is_valid_atomic_update()
static LOGICAL is_valid_atomic_update (int lop, int rop) static
Definition at line 7104 of file semsmp.c.
References AOP_UNDEF, CNULL, error(), FALSE, gbl, is_atomic_update_binop(), is_atomic_update_intr(), SEM::mpaccatomic, SEM::rmw_op, sem, TRUE, and validate_atomic_expr().
Referenced by validate_omp_atomic().
is_valid_atomic_write()
static LOGICAL is_valid_atomic_write (int lop, int rop) static
Definition at line 7157 of file semsmp.c.
References FALSE, TRUE, and validate_atomic_expr().
Referenced by mk_atomic_write(), and validate_omp_atomic().
leave_dir()
static int leave_dir (int typ, LOGICAL ignore_nested, LOGICAL ignore_sev) static
Definition at line 9077 of file semsmp.c.
References deallocate_no_scope_sptr(), DI_B, DI_ID, DI_ISSIMD, DI_NEST, DI_PARDO, DI_PDO, DI_SIMD, SEM::doif_depth, error(), gbl, name_of_dir(), NULL, prev, and sem.
Referenced by end_target(), end_teams(), and semsmp().
mk_atomic_capture()
static int mk_atomic_capture (int lop, int rop) static
Definition at line 7000 of file semsmp.c.
References A_MEM_ORDERP, A_OPTYPEP, ast, is_valid_atomic_capture(), SEM::mem_order, mk_stmt(), SEM::mpaccatomic, SEM::rmw_op, and sem.
Referenced by do_openmp_atomics().
mk_atomic_read()
static int mk_atomic_read (int lop, int src) static
Definition at line 6821 of file semsmp.c.
References A_MEM_ORDERP, ast, is_valid_atomic_read(), SEM::mem_order, mk_atomic(), SEM::mpaccatomic, sem, and src.
Referenced by do_openmp_atomics().
mk_atomic_update_binop()
static int mk_atomic_update_binop (int lop, int rop) static
Definition at line 6954 of file semsmp.c.
References A_MEM_ORDERP, A_OPTYPEP, AOP_UNDEF, ast, CNULL, ERR_Severe, error(), gbl, is_atomic_update_binop(), SEM::mem_order, mk_stmt(), SEM::mpaccatomic, SEM::rmw_op, and sem.
Referenced by do_openmp_atomics(), and gen_reduction().
mk_atomic_update_intr()
static int mk_atomic_update_intr (int lop, int rop) static
Definition at line 6975 of file semsmp.c.
References A_MEM_ORDERP, A_OPTYPEP, AOP_UNDEF, ast, CNULL, ERR_Severe, error(), gbl, is_atomic_update_intr(), SEM::mem_order, mk_stmt(), SEM::mpaccatomic, SEM::rmw_op, and sem.
Referenced by do_openmp_atomics(), and gen_reduction().
mk_atomic_write()
static int mk_atomic_write (int lop, int rop) static
Definition at line 6832 of file semsmp.c.
References A_MEM_ORDERP, ast, is_valid_atomic_write(), SEM::mem_order, mk_stmt(), SEM::mpaccatomic, and sem.
Referenced by do_openmp_atomics().
mk_firstprivate()
static void mk_firstprivate (int sptr1, int taskdupstd) static
Definition at line 6591 of file semsmp.c.
References add_assignment(), add_assignment_before(), add_firstprivate_assn(), add_ptr_assignment(), add_stmt_after(), ast, BLK_UPLEVEL_SPTR, decl_private_sym(), SCOPESTACK::end_prologue, mk_id(), mk_stmt(), mk_storage(), non_private_check(), SEM::parallel, SEM::scope_level, SEM::scope_stack, sem, set_parref_flag(), sptr, SPTR_NULL, std, STD_PREV, SEM::target, SEM::task, SEM::teams, void(), and XBIT.
Referenced by do_firstprivate().
mk_lastprivate_list()
static void mk_lastprivate_list (void) static
Definition at line 6749 of file semsmp.c.
References CL_FIRST, CL_LAST, CL_LASTPRIVATE, CL_PRESENT, first, getitem(), last, reduc_sym::next, NULL, reduc_sym::Private, and tmp.
Referenced by do_distbegin().
mk_reduction_list()
static void mk_reduction_list (void) static
Definition at line 7478 of file semsmp.c.
References CL_FIRST, CL_LAST, CL_PRESENT, CL_REDUCTION, first, getitem(), reduc_tag::intrin, last, reduc_tag::list, reduc_sym::next, reduc_tag::next, NULL, reduc_tag::opr, reduc_sym::Private, and reduc_sym::shared.
Referenced by do_distbegin().
mk_shared_list()
static void mk_shared_list (void) static
Definition at line 7456 of file semsmp.c.
References CL_FIRST, CL_LAST, CL_PRESENT, CL_SHARED, first, getitem(), getsymbol(), ITEM_END, itemp, last, NULL, and SYMNAME.
Referenced by do_distbegin().
mk_storage()
int mk_storage (int sptr, SST * stkp)
Definition at line 8856 of file semsmp.c.
References interr(), S_IDENT, sptr, SST_CVLENP, SST_DTYPEP, SST_IDP, SST_SHAPEP, SST_SYMG, and SST_SYMP.
Referenced by add_assign_firstprivate(), do_reduction(), end_lastprivate(), gen_reduction(), and mk_firstprivate().
mp_add_shared_var()
static void mp_add_shared_var (int sptr, int stblk) static
Definition at line 9728 of file semsmp.c.
References DT_INT, DTY, findUplevelForSharedVar(), llmp_add_shared_var(), llmp_add_shared_var_charlen(), needCharLen(), sptr, sym_get_scalar(), SYMNAME, and TY_CHAR.
Referenced by do_copyin(), parref_bnd(), set_parref_flag(), and set_parref_flag2().
name_of_dir()
static const char * name_of_dir (int typ) static
Definition at line 9117 of file semsmp.c.
References DI_ACCDATAREG, DI_ACCDO, DI_ACCHOSTDATA, DI_ACCKERNELS, DI_ACCKERNELSDO, DI_ACCKERNELSLOOP, DI_ACCLOOP, DI_ACCPARALLEL, DI_ACCPARALLELDO, DI_ACCPARALLELLOOP, DI_ACCREG, DI_ACCREGDO, DI_ACCREGLOOP, DI_ACCSERIAL, DI_ACCSERIALLOOP, DI_ATOMIC_CAPTURE, DI_CRITICAL, DI_DISTPARDO, DI_DISTRIBUTE, DI_DOACROSS, DI_MASTER, DI_ORDERED, DI_PAR, DI_PARDO, DI_PARSECTS, DI_PARWORKS, DI_PDO, DI_SECTS, DI_SIMD, DI_SINGLE, DI_TARGET, DI_TARGPARDO, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TASK, DI_TASKLOOP, DI_TEAMS, DI_TEAMSDIST, and DI_TEAMSDISTPARDO.
Referenced by enter_dir(), and leave_dir().
needCharLen()
static bool needCharLen (int sptr) static
Definition at line 9706 of file semsmp.c.
References DTYG, FLANG_FALLTHROUGH, sptr, TY_CHAR, and TY_NCHAR.
Referenced by mp_add_shared_var().
non_private_check()
static void non_private_check (int sptr, const char * cl) static
Definition at line 9565 of file semsmp.c.
References cl, error(), gbl, i, SEM::non_private_avail, SEM::non_private_base, sem, sptr, and SYMNAME.
Referenced by do_lastprivate(), do_private(), and mk_firstprivate().
other_firstlast_check()
static void other_firstlast_check (ITEM * itp, int clause) static
Definition at line 9518 of file semsmp.c.
References ITEM_END, itemp, and sptr.
Referenced by semsmp().
par_add_stblk_shvar()
void par_add_stblk_shvar (void)
Definition at line 9666 of file semsmp.c.
parref_bnd()
static void parref_bnd (int ast, int stblk) static
Definition at line 9766 of file semsmp.c.
References ast, mp_add_shared_var(), and sptr.
Referenced by set_parref_flag().
parstuff_init()
void parstuff_init (void)
Definition at line 5768 of file semsmp.c.
References any_pflsr_private, chunk, CL_FIRST, CL_LAST, CL_MAXV, CL_PRESENT, CL_VAL, distchunk, FALSE, i, IF_DEFAULT, mp_iftype, NULL, and recent_loop_clause.
Referenced by begin_combine_constructs(), semant1(), and semsmp().
private_check()
static void private_check () static
Definition at line 9530 of file semsmp.c.
References CL_FIRST, CL_FIRSTPRIVATE, CL_PRESENT, error(), gbl, ITEM_END, itemp, SCOPESTACK::par_scope, SEM::scope_level, SEM::scope_stack, sem, SCOPESTACK::sptr, and SYMNAME.
Referenced by begin_parallel_clause().
restore_clauses()
static void restore_clauses (void) static
Definition at line 8530 of file semsmp.c.
References BLK_UPLEVEL_SPTR, chunk, CL_DIST_SCHEDULE, CL_FIRST, CL_IF, CL_LAST, CL_MAXV, CL_NUM_TEAMS, CL_NUM_THREADS, CL_PRESENT, CL_SCHEDULE, CL_THREAD_LIMIT, CL_VAL, DI_DISTPARDO, DI_DISTRIBUTE, DI_ID, DI_PAR, DI_PARDO, DI_TARGET, DI_TARGPARDO, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TEAMS, DI_TEAMSDIST, DI_TEAMSDISTPARDO, distchunk, SEM::doif_depth, i, IF_DEFAULT, IF_PARALLEL, IF_TARGET, mk_id(), mp_iftype, sav_chk, SAVCL_FIRST, SAVCL_LAST, SAVCL_PRESENT, SAVCL_VAL, SEM::scope_level, sem, set_parref_flag(), and sptr.
Referenced by begin_combine_constructs(), and do_distbegin().
save_clauses()
static void save_clauses () static
Definition at line 8461 of file semsmp.c.
References add_stmt(), ast, chunk, CL_DIST_SCHEDULE, CL_FIRST, CL_IF, CL_LAST, CL_MAXV, CL_NUM_TEAMS, CL_NUM_THREADS, CL_PRESENT, CL_SCHEDULE, CL_THREAD_LIMIT, CL_VAL, distchunk, DT_INT, get_itemp(), i, mk_assn_stmt(), mk_id(), mp_iftype, sav_chk, SAVCL_FIRST, SAVCL_LAST, SAVCL_PRESENT, SAVCL_VAL, save_firstprivate_list(), save_private_list(), save_shared_list(), sptr, and void().
Referenced by begin_combine_constructs().
save_firstprivate_list()
static void save_firstprivate_list (void) static
Definition at line 7407 of file semsmp.c.
References CL_FIRST, CL_FIRSTPRIVATE, CL_PRESENT, first, getitem(), ITEM_END, itemp, last, NULL, SAVCL_FIRST, SAVCL_LAST, and tmp.
Referenced by save_clauses().
save_private_list()
static void save_private_list (void) static
Definition at line 7383 of file semsmp.c.
References CL_FIRST, CL_PRESENT, CL_PRIVATE, first, getitem(), ITEM_END, itemp, last, NULL, SAVCL_FIRST, SAVCL_LAST, and tmp.
Referenced by save_clauses().
save_shared_list()
static void save_shared_list (void) static
Definition at line 7432 of file semsmp.c.
References CL_FIRST, CL_PRESENT, CL_SHARED, first, getitem(), ITEM_END, itemp, last, NULL, SAVCL_FIRST, SAVCL_LAST, and tmp.
Referenced by save_clauses().
sched_type()
static int sched_type (char * nm) static
Definition at line 5983 of file semsmp.c.
References CNULL, DI_SCH_AUTO, DI_SCH_DYNAMIC, DI_SCH_GUIDED, DI_SCH_RUNTIME, DI_SCH_STATIC, error(), gbl, and sem_strcmp().
Referenced by semsmp().
semsmp()
void semsmp (int rednum, SST * top)
Semantic analysis for SMP statements.
Parameters
rednum reduction number
top top of stack after reduction
Definition at line 563 of file semsmp.c.
References A_CANCELKINDP, A_STDG, SEM::accassignc, accel_pragmagen(), ACCSTRICT, ACCVERYSTRICT, SEM::action_type, add_clause(), add_pragma(), add_stmt(), any_pflsr_private, SEM::apply, apply_nodepchk(), arg, assign_cval(), ast, SEM::ast, ATOMIC_CAPTURE, ATOMIC_READ, ATOMIC_UNDEF, ATOMIC_UPDATE, ATOMIC_WRITE, begin_combine_constructs(), begin_parallel_clause(), BLK_SYM, BT_ACCDATAREG, BT_ACCENDREG, BT_ACCHOSTDATA, BT_ACCKDO, BT_ACCKERNELS, BT_ACCKLOOP, BT_ACCPARALLEL, BT_ACCPDO, BT_ACCPLOOP, BT_ACCREG, BT_ACCSCALARREG, BT_ACCSERIAL, BT_ACCSLOOP, BT_DISTRIBUTE, BT_DOACROSS, BT_PAR, BT_PARDO, BT_PARSECTS, BT_PARWORKS, BT_PDO, BT_SECTS, BT_SIMD, BT_SINGLE, BT_TARGET, BT_TASK, BT_TASKLOOP, BT_TEAMS, cancel_type(), check_barrier(), check_cancel(), check_crit(), check_targetdata(), check_valid_data_sharing(), chk_scalartyp(), chkcon_to_isz(), chktyp(), chunk, CL_ACCCOMPARE, CL_ALIGNED, CL_CHUNK, CL_COLLAPSE, CL_COPYIN, CL_COPYPRIVATE, CL_DEFAULT, CL_DEPEND, CL_DEVICE, CL_DEVICE_TYPE, CL_DIST_SCHEDULE, CL_FINAL, CL_FIRST, CL_FIRSTPRIVATE, CL_GANG, CL_GRAINSIZE, CL_HOST, CL_IF, CL_KERNEL_BLOCK, CL_KERNEL_GRID, CL_LAST, CL_LASTPRIVATE, CL_LINEAR, CL_MAP, CL_MERGEABLE, CL_MP_SCHEDTYPE, CL_NOGROUP, CL_NOWAIT, CL_NUM_TASKS, CL_NUM_TEAMS, CL_NUM_THREADS, CL_ORDERED, CL_PARALLEL, CL_PARUNROLL, CL_PGICOMPARE, CL_PRESENT, CL_PRIORITY, CL_PRIVATE, CL_PROC_BIND, CL_REDUCTION, CL_SAFELEN, CL_SCHEDULE, CL_SEQ, CL_SEQUNROLL, CL_SHARED, CL_STREAM, CL_THREAD_LIMIT, CL_UNROLL, CL_UNTIED, CL_UPDATEDEV, CL_UPDATEHOST, CL_UPDATESELF, CL_VAL, CL_VECTOR, CL_VECUNROLL, CL_WORKER, clause_errchk(), CMEMLG, CNULL, SEM::collapse, CONVAL2G, cray_pointer_check(), d, DDTG, DI_ACCDATAREG, DI_ACCDO, DI_ACCHOSTDATA, DI_ACCKERNELS, DI_ACCKERNELSDO, DI_ACCKERNELSLOOP, DI_ACCLOOP, DI_ACCPARALLEL, DI_ACCPARALLELDO, DI_ACCPARALLELLOOP, DI_ACCREG, DI_ACCREGDO, DI_ACCREGLOOP, DI_ACCSERIAL, DI_ACCSERIALLOOP, DI_ATOMIC_CAPTURE, DI_B, DI_BEGINP, DI_BPAR, DI_BTARGET, DI_BTEAMS, DI_CRITICAL, DI_CRITSYM, DI_DISTPARDO, DI_DISTRIBUTE, DI_DOACROSS, DI_DOINFO, DI_ID, DI_IN_NEST, DI_IS_ORDERED, DI_ISSIMD, DI_LASTPRIVATE, DI_LINENO, DI_MASTER, DI_ORDERED, DI_PAR, DI_PARDO, DI_PARSECTS, DI_PARWORKS, DI_PDO, DI_SCH_STATIC, DI_SECT_CNT, DI_SECT_VAR, DI_SECTS, DI_SIMD, DI_SINGLE, DI_TARGET, DI_TARGETDATA, DI_TARGETENTERDATA, DI_TARGETEXITDATA, DI_TARGETUPDATE, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TASK, DI_TASKLOOP, DI_TEAMS, DI_TEAMSDIST, DI_TEAMSDISTPARDO, DI_WORKSHARE, dirname, distchunk, do_bdistribute(), do_bteams(), do_copyprivate(), do_map(), do_schedule(), SEM::doif_depth, DT_INT, DT_ISBASIC, DT_ISINT, emit_bcs_ecs(), emit_bpar(), emit_btarget(), emit_epar(), emit_etarget(), end_parallel_clause(), end_targteams(), end_teams(), end_workshare(), enter_dir(), ERR_Severe, ERR_Warning, error(), errwarn(), SEM::expect_do, SEM::expect_simd_do, FALSE, find_outer_sym(), find_reduc_intrinsic(), flg, gbl, get_csect_pfxlen(), get_csect_sym(), get_itemp(), get_mp_bind_type(), get_stblk_uplevel_sptr(), getitem(), getlab(), SCN::id, IF_DEFAULT, IF_TARGETEXITDATA, IF_TARGETUPDATE, IF_TASK, interr(), reduc_tag::intrin, SEM::is_acc, ITEM_END, itemp, kernel_argnum, kernel_do_nest, leave_dir(), LHS, reduc_tag::list, SEM::mem_order, mk_cval(), mk_id(), mk_label(), mk_stmt(), mkvarref(), MO_SEQ_CST, MO_UNDEF, mp_create_bscope(), mp_create_escope(), mp_iftype, SEM::mpaccatomic, SCN::name, new_node(), next, xyyz::next, reduc_sym::next, reduc_tag::next, NOSYM, NULL, OMP_DEFAULT, OMP_TARGETDATA, OMP_TARGETENTERDATA, OMP_TARGETEXITDATA, OMP_TARGETUPDATE, FLG::omptarget, OP_ADD, OP_LAND, OP_LEQV, OP_LNEQV, OP_LOG, OP_LOR, OP_MUL, reduc_tag::opr, other_firstlast_check(), par_pop_scope(), par_push_scope(), PAR_SCOPE_FIRSTPRIVATE, PAR_SCOPE_NONE, PAR_SCOPE_PRIVATE, PAR_SCOPE_SHARED, SEM::parallel, parstuff_init(), SEM::pending, PR_ACCBEGINDIR, PR_ACCDATAREG, PR_ACCEL, PR_ACCELLP, PR_ACCENDDATAREG, PR_ACCENDHOSTDATA, PR_ACCENDKERNELS, PR_ACCENDPARCONSTRUCT, PR_ACCENDSERIAL, PR_ACCHOSTDATA, PR_ACCKERNELS, PR_ACCKLOOP, PR_ACCPARCONSTRUCT, PR_ACCPLOOP, PR_ACCSCALARREG, PR_ACCSERIAL, PR_ACCSLOOP, PR_ACCTKLOOP, PR_ACCTPLOOP, PR_ACCTSLOOP, PR_ENDACCEL, PR_NOSCOPE, PR_PCASTCOMPARE, reduc_sym::Private, recent_loop_clause, ref_ident(), refsym(), RHS, rsp, S_CONST, S_DERIVED, S_IDENT, S_NULL, S_TRIPLE, sched_type(), scn, SEM::scope_level, SEM::seen, sem, set_iftype(), reduc_sym::shared, size_of(), sptr, SEM::ssa_area, SST_ASTG, SST_ASTP, SST_BEGG, SST_BEGP, SST_CVALG, SST_CVALP, SST_DEVICEG, SST_DTYPEP, SST_E1G, SST_E1P, SST_E2G, SST_E2P, SST_E3G, SST_E3P, SST_ENDG, SST_ENDP, SST_IDG, SST_IDP, SST_LSYMG, SST_OPCG, SST_OPCP, SST_OPTYPEG, SST_OPTYPEP, SST_PARENP, SST_SYMG, SST_SYMP, std, strlen(), SYMNAME, SEM::target, SEM::task, SEM::teams, top, TRUE, use_opt_atomic(), void(), and XBIT.
set_iftype()
static void set_iftype (int argcnt, char * nm, char * nm2, char * nm3) static
Definition at line 6083 of file semsmp.c.
References CL_IF, CL_PRESENT, SEM::doif_depth, ERR_Severe, error(), gbl, get_iftype(), IF_DEFAULT, mp_iftype, NULL, prev, sem, and type.
Referenced by semsmp().
set_parref_flag()
void set_parref_flag (int sptr, int psptr, int stblk)
Definition at line 9776 of file semsmp.c.
References AD_ADJARR, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_UPAST, AD_ZBASE, DTY, flg, get_static_descriptor(), get_stblk_uplevel_sptr(), i, mp_add_shared_var(), ndim, FLG::omptarget, parref_bnd(), sptr, and ST_ISVAR.
Referenced by add_assign_firstprivate(), add_private_allocatable(), check_parref(), do_dist_schedule(), do_distbegin(), do_lastprivate(), do_reduction(), do_schedule(), get_fmt_array(), mk_firstprivate(), refsym(), restore_clauses(), and set_parref_flag2().
set_parref_flag2()
void set_parref_flag2 (int sptr, int psptr, int std)
set_parref_flag set PARREF flag after semant phase
Parameters
sptr shared symbol - set PARREF field and put in uplevel structure
psptr shared symbol - use it as key to search for uplevel
std statement where the reference of sptr occurs
Definition at line 9851 of file semsmp.c.
References ast, STB::firstusym, i, llmp_get_uplevel(), mp_add_shared_var(), set_parref_flag(), sptr, ST_ISVAR, stb, std, STD_AST, STD_PREV, LLUplevel::vals, and LLUplevel::vals_count.
Referenced by add_class_arg_descr_arg(), change_mk_id(), make_simple_template_from_ast(), prepare_for_astout(), rewrite_all_shape(), transform_call(), and transform_wrapup().
set_private_bnd_encl()
static void set_private_bnd_encl (int ast, int scope, int encl) static
Definition at line 9925 of file semsmp.c.
References ast, scope, and sptr.
Referenced by set_private_encl().
set_private_encl()
void set_private_encl (int old, int new)
Definition at line 9936 of file semsmp.c.
References AD_ADJARR, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_UPAST, AD_ZBASE, DTY, i, ndim, scope, and set_private_bnd_encl().
Referenced by decl_private_sym().
set_private_taskflag()
void set_private_taskflag (int sptr)
Definition at line 9982 of file semsmp.c.
References RUNTIMEG, sem, sptr, and SEM::task.
Referenced by decl_private_sym().
size_of_allocatable()
static int size_of_allocatable (int sptr) static
Definition at line 7634 of file semsmp.c.
References A_OPTYPEP, argt, ARGT_ARG, ast, ast_intr(), astb, DT_PTR, DTY, intast_sym, mk_argt(), mk_binop(), mk_func_node(), mk_id(), OP_MUL, ASTB::ptr0, size_ast_of(), size_of(), and sptr.
Referenced by do_copyin(), and do_copyprivate().
use_atomic_for_reduction()
static LOGICAL use_atomic_for_reduction (int d) static
Decide whether to use llvm atomic for reduction or not. Atomic is used only for teams reduction.
Definition at line 10320 of file semsmp.c.
References d, DI_IN_NEST, DI_PARDO, DI_TARGET, DI_TARGTEAMSDISTPARDO, flg, FLG::omptarget, OPT_OMP_ATOMIC, and TRUE.
Referenced by end_reduction(), and gen_reduction().
use_opt_atomic()
LOGICAL use_opt_atomic (int d)
Decide to use optimized atomic usage.
Definition at line 10308 of file semsmp.c.
References d, and OPT_OMP_ATOMIC.
Referenced by semant1(), semant3(), and semsmp().
validate_atomic_expr()
static LOGICAL validate_atomic_expr (int lop, int rop, int read) static
Definition at line 6773 of file semsmp.c.
References SEM::accassignc, SEM::action_type, ATOMIC_CAPTURE, CNULL, DT_ISSCALAR, DTY, ERR_Severe, error(), FALSE, gbl, memsym_of_ast(), SEM::mpaccatomic, sem, sptr, and TRUE.
Referenced by do_openmp_atomics(), is_valid_atomic_capture(), is_valid_atomic_read(), is_valid_atomic_update(), and is_valid_atomic_write().
validate_omp_atomic()
LOGICAL validate_omp_atomic (SST * l_stktop, SST * r_stktop)
Definition at line 7215 of file semsmp.c.
References SEM::action_type, ATOMIC_CAPTURE, ATOMIC_READ, ATOMIC_UPDATE, ATOMIC_WRITE, CNULL, error(), FALSE, gbl, is_valid_atomic_capture(), is_valid_atomic_read(), is_valid_atomic_update(), is_valid_atomic_write(), mkexpr1(), mklvalue(), SEM::mpaccatomic, sem, and SST_ASTG.
Referenced by semant3().
Variable Documentation
any_pflsr_private
LOGICAL any_pflsr_private = FALSE static
Definition at line 546 of file semsmp.c.
Referenced by parstuff_init(), and semsmp().
chunk
int chunk static
Definition at line 539 of file semsmp.c.
Referenced by ast_rewrite(), begin_combine_constructs(), do_schedule(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), parstuff_init(), restore_clauses(), save_clauses(), and semsmp().
cl
struct cl_tag cl[CL_MAXV] static
Referenced by __fort_cyclic_loop(), add_headerfile(), copy_loop(), cyclic_setup(), ENT3F(), ENTFTN(), fill_cyclic_k(), fills_loop(), jsr2qjsr(), line_directive(), local_copy(), non_private_check(), olap_loop(), olap_recv(), olap_send(), outvalue_hcycliclp(), print_loop(), prng_loop_d_lf(), prng_loop_d_npb(), prng_loop_r_lf(), prng_loop_r_npb(), and put_length_type_param().
distchunk
int distchunk static
Definition at line 540 of file semsmp.c.
Referenced by do_dist_schedule(), parstuff_init(), restore_clauses(), save_clauses(), and semsmp().
has_team
LOGICAL has_team = FALSE static
Definition at line 543 of file semsmp.c.
Referenced by begin_combine_constructs(), and do_distbegin().
kernel_argnum
int kernel_argnum static
Definition at line 555 of file semsmp.c.
Referenced by semsmp().
kernel_do_nest
ISZ_T kernel_do_nest static
Definition at line 542 of file semsmp.c.
Referenced by semsmp().
mp_iftype
int mp_iftype static
Definition at line 541 of file semsmp.c.
Referenced by emit_bpar(), emit_btarget(), parstuff_init(), restore_clauses(), save_clauses(), semsmp(), and set_iftype().
recent_loop_clause
int recent_loop_clause = 0 static
Definition at line 537 of file semsmp.c.
Referenced by parstuff_init(), and semsmp().
struct { ... } sav_chk
Referenced by restore_clauses(), and save_clauses().
sav_cl
struct savcl_tag sav_cl[CL_MAXV] static
Definition at line 515 of file semsmp.c.