flang: semstk.h File Reference
semstk.h File Reference
Classes
struct sst
Macros
#define LHS top
#define RHS(i) (top + ((i)-1))
#define SST_SIZE 200
#define SST_INT(m) INT m
#define SST_IDG(p) ((p)->id)
#define SST_IDP(p, v) ((p)->id = ((int)(v)))
#define SST_FLAGG(p) ((p)->flag)
#define SST_FLAGP(p, v) ((p)->flag = ((int)(v)))
#define SST_PARENG(p) ((p)->f1)
#define SST_PARENP(p, v) ((p)->f1 = ((int)(v)))
#define SST_ALIASG(p) ((p)->f2)
#define SST_ALIASP(p, v) ((p)->f2 = (v))
#define SST_ASTG(p) ((p)->ast)
#define SST_ASTP(p, v) ((p)->ast = (v))
#define SST_MNOFFG(p) ((p)->mnoff)
#define SST_MNOFFP(p, v) ((p)->mnoff = (v))
#define SST_DIMFLAGG(p) ((p)->mnoff)
#define SST_DIMFLAGP(p, v) ((p)->mnoff = (v))
#define SST_TMPG(p) ((p)->sr)
#define SST_TMPP(p, v) ((p)->sr = (v))
#define SST_LINENOG(p) ((p)->lineno)
#define SST_LINENOP(p, v) ((p)->lineno = (v))
#define SST_COLUMNG(p) ((p)->col)
#define SST_COLUMNP(p, v) ((p)->col = (v))
#define SST_OPTYPEG(p) ((p)->value.wval.w1)
#define SST_SYMG(p) ((p)->value.wval.w1)
#define SST_CVALG(p) ((p)->value.wval.w1)
#define SST_GDTYPEG(p) ((p)->value.wval.w2)
#define SST_DTYPEG(p) ((p)->value.wval.w2)
#define SST_GTYG(p) ((p)->value.wval.w3)
#define SST_LSYMG(p) ((p)->value.wval.w3)
#define SST_LENG(p) ((p)->value.wval.w3)
#define SST_ERRSYMG(p) ((p)->value.wval.w3)
#define SST_SHAPEG(p) ((p)->value.wval.w4)
#define SST_OPCG(p) ((p)->value.wval.w4)
#define SST_UNITG(p) ((p)->value.wval.w4)
#define SST_FIRSTG(p) ((p)->value.wval.w4)
#define SST_LASTG(p) ((p)->value.wval.w5)
#define SST_CVLENG(p) ((p)->value.wval.w5)
#define SST_CPLXPARTG ((p)->value.wval.w5)
#define SST_ACLG(p) ((p)->value.cnval.acl)
#define SST_SUBSCRIPTG(p) ((p)->value.eqvval.subscript)
#define SST_SUBSTRINGG(p) ((p)->value.eqvval.substring)
#define SST_OFFSETG(p) ((p)->value.eqvval.offset)
#define SST_NMLBEGG(p) ((p)->value.wval.w1)
#define SST_NMLENDG(p) ((p)->value.wval.w2)
#define SST_BEGG(p) ((p)->value.ilval.beg)
#define SST_ENDG(p) ((p)->value.ilval.end)
#define SST_COUNTG(p) ((p)->value.ilval.count)
#define SST_CLBEGG(p) ((p)->value.clval.beg)
#define SST_CLENDG(p) ((p)->value.clval.end)
#define SST_DBEGG(p) ((p)->value.dtval.beg)
#define SST_DENDG(p) ((p)->value.dtval.end)
#define SST_VLBEGG(p) ((p)->value.vlval.beg)
#define SST_VLENDG(p) ((p)->value.vlval.end)
#define SST_RNG1G(p) ((p)->value.wval.w1)
#define SST_RNG2G(p) ((p)->value.wval.w2)
#define SST_E1G(p) ((p)->value.tlval.e1)
#define SST_E2G(p) ((p)->value.tlval.e2)
#define SST_E3G(p) ((p)->value.tlval.e3)
#define SST_ROUTG(p) ((p)->value.wval.w3)
#define SST_DEVTYPEG(p) ((p)->value.wval.w2)
#define SST_DEVICEG(p) ((p)->value.wval.w2)
#define SST_OPTYPEP(p, v) ((p)->value.wval.w1 = (v))
#define SST_SYMP(p, v) ((p)->value.wval.w1 = (v))
#define SST_CVALP(p, v) ((p)->value.wval.w1 = (v))
#define SST_GDTYPEP(p, v) ((p)->value.wval.w2 = (v))
#define SST_DTYPEP(p, v) ((p)->value.wval.w2 = (v))
#define SST_GTYP(p, v) ((p)->value.wval.w3 = (v))
#define SST_LSYMP(p, v) ((p)->value.wval.w3 = (v))
#define SST_LENP(p, v) ((p)->value.wval.w3 = (v))
#define SST_ERRSYMP(p, v) ((p)->value.wval.w3 = (v))
#define SST_SHAPEP(p, v) ((p)->value.wval.w4 = (v))
#define SST_OPCP(p, v) ((p)->value.wval.w4 = (v))
#define SST_UNITP(p, v) ((p)->value.wval.w4 = (v))
#define SST_FIRSTP(p, v) ((p)->value.wval.w4 = (v))
#define SST_LASTP(p, v) ((p)->value.wval.w5 = (v))
#define SST_CVLENP(p, v) ((p)->value.wval.w5 = (v))
#define SST_CPLXPARTP(p, v) ((p)->value.wval.w5 = (v))
#define SST_ACLP(p, v) ((p)->value.cnval.acl = (v))
#define SST_SUBSCRIPTP(p, v) ((p)->value.eqvval.subscript = (v))
#define SST_SUBSTRINGP(p, v) ((p)->value.eqvval.substring = (v))
#define SST_OFFSETP(p, v) ((p)->value.eqvval.offset = (v))
#define SST_NMLBEGP(p, v) ((p)->value.wval.w1 = (v))
#define SST_NMLENDP(p, v) ((p)->value.wval.w2 = (v))
#define SST_BEGP(p, v) ((p)->value.ilval.beg = (v))
#define SST_ENDP(p, v) ((p)->value.ilval.end = (v))
#define SST_COUNTP(p, v) ((p)->value.ilval.count = (v))
#define SST_CLBEGP(p, v) ((p)->value.clval.beg = (v))
#define SST_CLENDP(p, v) ((p)->value.clval.end = (v))
#define SST_DBEGP(p, v) ((p)->value.dtval.beg = (v))
#define SST_DENDP(p, v) ((p)->value.dtval.end = (v))
#define SST_VLBEGP(p, v) ((p)->value.vlval.beg = (v))
#define SST_VLENDP(p, v) ((p)->value.vlval.end = (v))
#define SST_RNG1P(p, v) ((p)->value.wval.w1 = (v))
#define SST_RNG2P(p, v) ((p)->value.wval.w2 = (v))
#define SST_E1P(p, v) ((p)->value.tlval.e1 = (v))
#define SST_E2P(p, v) ((p)->value.tlval.e2 = (v))
#define SST_E3P(p, v) ((p)->value.tlval.e3 = (v))
#define SST_ROUTP(p, v) ((p)->value.wval.w3 = (v))
#define SST_DEVTYPEP(p, v) ((p)->value.wval.w2 = (v))
#define SST_DEVICEP(p, v) ((p)->value.wval.w2 = (v))
#define SST_ISNONDECC(p)
Typedefs
typedef struct sst SST
Functions
void semant1 (int rednum, SST *top)
Semantic actions - part 1.
void semant2 (int rednum, SST *top)
semantic actions - part 2.
void semant3 (int rednum, SST *top)
semantic actions - part 3.
void psemant1 (int rednum, SST *top)
Semantic actions - part 1.
void psemant2 (int rednum, SST *top)
Semantic actions - part 2.
void psemant3 (int rednum, SST *top)
Semantic actions - part 3.
void psemantio (int rednum, SST *top)
void psemsmp (int rednum, SST *top)
void semantio (int rednum, SST *top)
Semantic analysis of IO statements.
int func_call2 (SST *stktop, ITEM *list, int flag)
Write ILMs to call a function.
int func_call (SST *stktop, ITEM *list)
int ptrfunc_call (SST *stktop, ITEM *list)
void subr_call2 (SST *stktop, ITEM *list, int flag)
Write ILMs to call a subroutine.
void subr_call (SST *stktop, ITEM *list)
void ptrsubr_call (SST *stktop, ITEM *list)
void cuda_call (SST *stktop, ITEM *list, ITEM *chevlist)
int ref_intrin (SST *stktop, ITEM *list)
Handle Generic and Intrinsic function calls.
int ref_pd (SST *stktop, ITEM *list)
Handle calls to Predeclared functions.
int define_stfunc (int sptr, ITEM *argl, SST *estk)
Perform error checking and create statement function descriptor for statement function definition.
int ref_stfunc (SST *stktop, ITEM *args)
int mkarg (SST *stkptr, int *dtype)
Check and write ILMs for a subprogram argument.
int chkarg (SST *stkptr, int *dtype)
Performing checking on an argument to determine if it needs to be "protected".
int tempify (SST *stkptr)
Allocate a temporary, assign it the value, and return the temp's base.
void constant_lvalue (SST *)
If stkptr is an LVALUE that has a constant value, replace it with the constant value.
INT chkcon (SST *, int, LOGICAL)
Check that the indicated semantic stack entry is a constant of the specified type and convert constant to new type if possible.
ISZ_T chkcon_to_isz (SST *, LOGICAL)
Check that the indicated semantic stack entry is a constant of any integer type.
INT chktyp (SST *, int, LOGICAL)
Convert expression pointed to by stkptr from its current data type to data type dtype.
INT chk_scalartyp (SST *, int, LOGICAL)
Same as chktyp() with the restriction that the expression must be a scalar (i.e., not an array/vector form).
INT chk_scalar_inttyp (SST *, int, const char *)
Same as chktyp() with the restriction that the expression must be a scalar (i.e., not an array/vector form) and integer (i.e., not logical).
INT chk_arr_extent (SST *, const char *)
Restrict the expression to be suitable for an array extent.
INT chksubscr (SST *, int)
Convert expression pointed to by stkptr from its current data type to a data type consistent with subscripting.
int casttyp (SST *, int)
Cast a given semantic entry into a desired type. No type conversion is done.
void cngtyp (SST *, DTYPE)
Convert expression pointed-to by old to the data type newtyp.
void cngshape (SST *, SST *)
LOGICAL chkshape (SST *, SST *, LOGICAL)
Semantically check an operand (old) for array conformance with operand new. If the operand is a scalar, change the shape of the operand to conform with the expected shape. If the operand is an array, check for conformance.
int chklog (SST *)
void mkident (SST *)
int mkexpr (SST *)
int mkexpr1 (SST *)
Given a semantic stack entry, write ILM's for the expression represented by the stack entry if they have not already been written.
int mkexpr2 (SST *)
Same as mkexpr1(), but the expression is the target of a pointer assignment. Must handle ST_PROCs as identifiers; otherwise, just call mkexpr1().
void mklogint4 (SST *)
Convert all sizes of logicals and integers to 4 byte versions.
int mklvalue (SST *, int)
Check for legal variable to be assigned to.
int mkvarref (SST *, ITEM *)
Make a var ref of the form: <var primary> ([<ssa list>])
LOGICAL is_sst_const (SST *)
Check if a stack entry represents a constant or an expression evaluated to a constant.
INT get_sst_cval (SST *)
Get the SST_CVAL-like value for a semantic stack entry already determined to be a constant (i.e., is_sst_const() is true).
LOGICAL is_varref (SST *)
Check if a stack entry is a legal variable reference.
int chksubstr (SST *, ITEM *)
Check that substring specifier is correct, write SUBS (substring) ILM and return pointer to it.
void ch_substring (SST *, SST *, SST *)
Substring of a character constant.
int fix_term (SST *, int)
Repair a bad term in an expression.
int assign (SST *, SST *)
Assign stktop to newtop.
int assign_pointer (SST *, SST *)
void chkopnds (SST *, SST *, SST *)
Make two operands conform in a binary operation. The sequence of events is crucial to correct interpretation of expression.
void unop (SST *, SST *, SST *)
Perform a unary operation on logical rhs.
void binop (SST *, SST *, SST *, SST *)
Perform a binary operation on rhs1 and rhs2. They both conform in data type and shape.
const char * prtsst (SST *)
Return the printable representation of a semantic stack entry.
int mklabelvar (SST *)
Given an ast which computes the address of the label variable or loads the label variable, create the variable of indicated dtype.
void construct_acl_for_sst (SST *, DTYPE)
void dinit_struct_param (SPTR, ACL *, DTYPE)
VAR * dinit_varref (SST *)
Create an initialization node for a variable reference in a data statement.
int sem_tempify (SST *)
Allocate a temporary, assign it the value, and return the assignment ast.
int check_etmp (SST *)
If temps were allocated while processing the expression, the expression needs to be assigned to a temp, the allocatable temps need to be deallocated, and the use of the expression is replaced by the temp.
void semsmp (int rednum, SST *top)
Semantic analysis for SMP statements.
int mk_storage (int sptr, SST *stkp)
LOGICAL validate_omp_atomic (SST *, SST *)
int do_openmp_atomics (SST *, SST *)
int generic_tbp_call (int gnr, SST *stktop, ITEM *list, ITEM *chevlist)
void generic_call (int gnr, SST *stktop, ITEM *list, ITEM *chevlist)
int generic_tbp_func (int gnr, SST *stktop, ITEM *list)
int generic_func (int gnr, SST *stktop, ITEM *list)
int defined_operator (int opr, SST *stktop, SST *lop, SST *rop)
LOGICAL is_intrinsic_opr (int val, SST *stktop, SST *lop, SST *rop, int tkn_alias)
int resolve_defined_io (int read_or_write, SST *stktop, ITEM *list)
Variables
SST * sst
Detailed Description
Shared by Parser and Semantic Analyzer modules. This file contains semantic stack definitions and prototypes of functions that operate on the semantic stack.
Definition in file semstk.h.
Macro Definition Documentation
LHS
#define LHS top
Definition at line 19 of file semstk.h.
RHS
#define RHS (i) (top + ((i)-1))
Definition at line 20 of file semstk.h.
SST_ACLG
#define SST_ACLG (p) ((p)->value.cnval.acl)
Definition at line 146 of file semstk.h.
SST_ACLP
#define SST_ACLP (p, v) ((p)->value.cnval.acl = (v))
Definition at line 187 of file semstk.h.
SST_ALIASG
#define SST_ALIASG (p) ((p)->f2)
Definition at line 106 of file semstk.h.
SST_ALIASP
#define SST_ALIASP (p, v) ((p)->f2 = (v))
Definition at line 107 of file semstk.h.
SST_ASTG
#define SST_ASTG (p) ((p)->ast)
Definition at line 110 of file semstk.h.
SST_ASTP
#define SST_ASTP (p, v) ((p)->ast = (v))
Definition at line 111 of file semstk.h.
SST_BEGG
#define SST_BEGG (p) ((p)->value.ilval.beg)
Definition at line 152 of file semstk.h.
SST_BEGP
#define SST_BEGP (p, v) ((p)->value.ilval.beg = (v))
Definition at line 193 of file semstk.h.
SST_CLBEGG
#define SST_CLBEGG (p) ((p)->value.clval.beg)
Definition at line 155 of file semstk.h.
SST_CLBEGP
#define SST_CLBEGP (p, v) ((p)->value.clval.beg = (v))
Definition at line 196 of file semstk.h.
SST_CLENDG
#define SST_CLENDG (p) ((p)->value.clval.end)
Definition at line 156 of file semstk.h.
SST_CLENDP
#define SST_CLENDP (p, v) ((p)->value.clval.end = (v))
Definition at line 197 of file semstk.h.
SST_COLUMNG
#define SST_COLUMNG (p) ((p)->col)
Definition at line 125 of file semstk.h.
SST_COLUMNP
#define SST_COLUMNP (p, v) ((p)->col = (v))
Definition at line 126 of file semstk.h.
SST_COUNTG
#define SST_COUNTG (p) ((p)->value.ilval.count)
Definition at line 154 of file semstk.h.
SST_COUNTP
#define SST_COUNTP (p, v) ((p)->value.ilval.count = (v))
Definition at line 195 of file semstk.h.
SST_CPLXPARTG
#define SST_CPLXPARTG ((p)->value.wval.w5)
Definition at line 145 of file semstk.h.
SST_CPLXPARTP
#define SST_CPLXPARTP (p, v) ((p)->value.wval.w5 = (v))
Definition at line 186 of file semstk.h.
SST_CVALG
#define SST_CVALG (p) ((p)->value.wval.w1)
Definition at line 132 of file semstk.h.
SST_CVALP
#define SST_CVALP (p, v) ((p)->value.wval.w1 = (v))
Definition at line 173 of file semstk.h.
SST_CVLENG
#define SST_CVLENG (p) ((p)->value.wval.w5)
Definition at line 144 of file semstk.h.
SST_CVLENP
#define SST_CVLENP (p, v) ((p)->value.wval.w5 = (v))
Definition at line 185 of file semstk.h.
SST_DBEGG
#define SST_DBEGG (p) ((p)->value.dtval.beg)
Definition at line 157 of file semstk.h.
SST_DBEGP
#define SST_DBEGP (p, v) ((p)->value.dtval.beg = (v))
Definition at line 198 of file semstk.h.
SST_DENDG
#define SST_DENDG (p) ((p)->value.dtval.end)
Definition at line 158 of file semstk.h.
SST_DENDP
#define SST_DENDP (p, v) ((p)->value.dtval.end = (v))
Definition at line 199 of file semstk.h.
SST_DEVICEG
#define SST_DEVICEG (p) ((p)->value.wval.w2)
Definition at line 169 of file semstk.h.
SST_DEVICEP
#define SST_DEVICEP (p, v) ((p)->value.wval.w2 = (v))
Definition at line 210 of file semstk.h.
SST_DEVTYPEG
#define SST_DEVTYPEG (p) ((p)->value.wval.w2)
Definition at line 168 of file semstk.h.
SST_DEVTYPEP
#define SST_DEVTYPEP (p, v) ((p)->value.wval.w2 = (v))
Definition at line 209 of file semstk.h.
SST_DIMFLAGG
#define SST_DIMFLAGG (p) ((p)->mnoff)
Definition at line 116 of file semstk.h.
SST_DIMFLAGP
#define SST_DIMFLAGP (p, v) ((p)->mnoff = (v))
Definition at line 117 of file semstk.h.
SST_DTYPEG
#define SST_DTYPEG (p) ((p)->value.wval.w2)
Definition at line 134 of file semstk.h.
SST_DTYPEP
#define SST_DTYPEP (p, v) ((p)->value.wval.w2 = (v))
Definition at line 175 of file semstk.h.
SST_E1G
#define SST_E1G (p) ((p)->value.tlval.e1)
Definition at line 163 of file semstk.h.
SST_E1P
#define SST_E1P (p, v) ((p)->value.tlval.e1 = (v))
Definition at line 204 of file semstk.h.
SST_E2G
#define SST_E2G (p) ((p)->value.tlval.e2)
Definition at line 164 of file semstk.h.
SST_E2P
#define SST_E2P (p, v) ((p)->value.tlval.e2 = (v))
Definition at line 205 of file semstk.h.
SST_E3G
#define SST_E3G (p) ((p)->value.tlval.e3)
Definition at line 165 of file semstk.h.
SST_E3P
#define SST_E3P (p, v) ((p)->value.tlval.e3 = (v))
Definition at line 206 of file semstk.h.
SST_ENDG
#define SST_ENDG (p) ((p)->value.ilval.end)
Definition at line 153 of file semstk.h.
SST_ENDP
#define SST_ENDP (p, v) ((p)->value.ilval.end = (v))
Definition at line 194 of file semstk.h.
SST_ERRSYMG
#define SST_ERRSYMG (p) ((p)->value.wval.w3)
Definition at line 138 of file semstk.h.
SST_ERRSYMP
#define SST_ERRSYMP (p, v) ((p)->value.wval.w3 = (v))
Definition at line 179 of file semstk.h.
SST_FIRSTG
#define SST_FIRSTG (p) ((p)->value.wval.w4)
Definition at line 142 of file semstk.h.
SST_FIRSTP
#define SST_FIRSTP (p, v) ((p)->value.wval.w4 = (v))
Definition at line 183 of file semstk.h.
SST_FLAGG
#define SST_FLAGG (p) ((p)->flag)
Definition at line 100 of file semstk.h.
SST_FLAGP
#define SST_FLAGP (p, v) ((p)->flag = ((int)(v)))
Definition at line 101 of file semstk.h.
SST_GDTYPEG
#define SST_GDTYPEG (p) ((p)->value.wval.w2)
Definition at line 133 of file semstk.h.
SST_GDTYPEP
#define SST_GDTYPEP (p, v) ((p)->value.wval.w2 = (v))
Definition at line 174 of file semstk.h.
SST_GTYG
#define SST_GTYG (p) ((p)->value.wval.w3)
Definition at line 135 of file semstk.h.
SST_GTYP
#define SST_GTYP (p, v) ((p)->value.wval.w3 = (v))
Definition at line 176 of file semstk.h.
SST_IDG
#define SST_IDG (p) ((p)->id)
Definition at line 97 of file semstk.h.
SST_IDP
#define SST_IDP (p, v) ((p)->id = ((int)(v)))
Definition at line 98 of file semstk.h.
SST_INT
#define SST_INT (m) INT m
Definition at line 30 of file semstk.h.
SST_ISNONDECC
#define SST_ISNONDECC (p)
Value:
  (SST_IDG(p) == S_CONST && \
   (SST_DTYPEG(p) == DT_WORD || SST_DTYPEG(p) == DT_HOLL))
Definition at line 212 of file semstk.h.
SST_LASTG
#define SST_LASTG (p) ((p)->value.wval.w5)
Definition at line 143 of file semstk.h.
SST_LASTP
#define SST_LASTP (p, v) ((p)->value.wval.w5 = (v))
Definition at line 184 of file semstk.h.
SST_LENG
#define SST_LENG (p) ((p)->value.wval.w3)
Definition at line 137 of file semstk.h.
SST_LENP
#define SST_LENP (p, v) ((p)->value.wval.w3 = (v))
Definition at line 178 of file semstk.h.
SST_LINENOG
#define SST_LINENOG (p) ((p)->lineno)
Definition at line 122 of file semstk.h.
SST_LINENOP
#define SST_LINENOP (p, v) ((p)->lineno = (v))
Definition at line 123 of file semstk.h.
SST_LSYMG
#define SST_LSYMG (p) ((p)->value.wval.w3)
Definition at line 136 of file semstk.h.
SST_LSYMP
#define SST_LSYMP (p, v) ((p)->value.wval.w3 = (v))
Definition at line 177 of file semstk.h.
SST_MNOFFG
#define SST_MNOFFG (p) ((p)->mnoff)
Definition at line 113 of file semstk.h.
SST_MNOFFP
#define SST_MNOFFP (p, v) ((p)->mnoff = (v))
Definition at line 114 of file semstk.h.
SST_NMLBEGG
#define SST_NMLBEGG (p) ((p)->value.wval.w1)
Definition at line 150 of file semstk.h.
SST_NMLBEGP
#define SST_NMLBEGP (p, v) ((p)->value.wval.w1 = (v))
Definition at line 191 of file semstk.h.
SST_NMLENDG
#define SST_NMLENDG (p) ((p)->value.wval.w2)
Definition at line 151 of file semstk.h.
SST_NMLENDP
#define SST_NMLENDP (p, v) ((p)->value.wval.w2 = (v))
Definition at line 192 of file semstk.h.
SST_OFFSETG
#define SST_OFFSETG (p) ((p)->value.eqvval.offset)
Definition at line 149 of file semstk.h.
SST_OFFSETP
#define SST_OFFSETP (p, v) ((p)->value.eqvval.offset = (v))
Definition at line 190 of file semstk.h.
SST_OPCG
#define SST_OPCG (p) ((p)->value.wval.w4)
Definition at line 140 of file semstk.h.
SST_OPCP
#define SST_OPCP (p, v) ((p)->value.wval.w4 = (v))
Definition at line 181 of file semstk.h.
SST_OPTYPEG
#define SST_OPTYPEG (p) ((p)->value.wval.w1)
Definition at line 130 of file semstk.h.
SST_OPTYPEP
#define SST_OPTYPEP (p, v) ((p)->value.wval.w1 = (v))
Definition at line 171 of file semstk.h.
SST_PARENG
#define SST_PARENG (p) ((p)->f1)
Definition at line 103 of file semstk.h.
SST_PARENP
#define SST_PARENP (p, v) ((p)->f1 = ((int)(v)))
Definition at line 104 of file semstk.h.
SST_RNG1G
#define SST_RNG1G (p) ((p)->value.wval.w1)
Definition at line 161 of file semstk.h.
SST_RNG1P
#define SST_RNG1P (p, v) ((p)->value.wval.w1 = (v))
Definition at line 202 of file semstk.h.
SST_RNG2G
#define SST_RNG2G (p) ((p)->value.wval.w2)
Definition at line 162 of file semstk.h.
SST_RNG2P
#define SST_RNG2P (p, v) ((p)->value.wval.w2 = (v))
Definition at line 203 of file semstk.h.
SST_ROUTG
#define SST_ROUTG (p) ((p)->value.wval.w3)
Definition at line 167 of file semstk.h.
SST_ROUTP
#define SST_ROUTP (p, v) ((p)->value.wval.w3 = (v))
Definition at line 208 of file semstk.h.
SST_SHAPEG
#define SST_SHAPEG (p) ((p)->value.wval.w4)
Definition at line 139 of file semstk.h.
SST_SHAPEP
#define SST_SHAPEP (p, v) ((p)->value.wval.w4 = (v))
Definition at line 180 of file semstk.h.
SST_SIZE
#define SST_SIZE 200
Definition at line 23 of file semstk.h.
SST_SUBSCRIPTG
#define SST_SUBSCRIPTG (p) ((p)->value.eqvval.subscript)
Definition at line 147 of file semstk.h.
SST_SUBSCRIPTP
#define SST_SUBSCRIPTP (p, v) ((p)->value.eqvval.subscript = (v))
Definition at line 188 of file semstk.h.
SST_SUBSTRINGG
#define SST_SUBSTRINGG (p) ((p)->value.eqvval.substring)
Definition at line 148 of file semstk.h.
SST_SUBSTRINGP
#define SST_SUBSTRINGP (p, v) ((p)->value.eqvval.substring = (v))
Definition at line 189 of file semstk.h.
SST_SYMG
#define SST_SYMG (p) ((p)->value.wval.w1)
Definition at line 131 of file semstk.h.
SST_SYMP
#define SST_SYMP (p, v) ((p)->value.wval.w1 = (v))
Definition at line 172 of file semstk.h.
SST_TMPG
#define SST_TMPG (p) ((p)->sr)
Definition at line 119 of file semstk.h.
SST_TMPP
#define SST_TMPP (p, v) ((p)->sr = (v))
Definition at line 120 of file semstk.h.
SST_UNITG
#define SST_UNITG (p) ((p)->value.wval.w4)
Definition at line 141 of file semstk.h.
SST_UNITP
#define SST_UNITP (p, v) ((p)->value.wval.w4 = (v))
Definition at line 182 of file semstk.h.
SST_VLBEGG
#define SST_VLBEGG (p) ((p)->value.vlval.beg)
Definition at line 159 of file semstk.h.
SST_VLBEGP
#define SST_VLBEGP (p, v) ((p)->value.vlval.beg = (v))
Definition at line 200 of file semstk.h.
SST_VLENDG
#define SST_VLENDG (p) ((p)->value.vlval.end)
Definition at line 160 of file semstk.h.
SST_VLENDP
#define SST_VLENDP (p, v) ((p)->value.vlval.end = (v))
Definition at line 201 of file semstk.h.
Typedef Documentation
SST
typedef struct sst SST
Function Documentation
assign()
int assign (SST * newtop, SST * stktop)
Assign stktop to newtop.
Definition at line 3443 of file semutil.c.
References SEM::alloc_std, argt, ARGT_ARG, SEM::arrfn, ast, ast_to_comment(), SEM::call_std, check_derived_type_array_section(), chktyp(), cngshape(), cngtyp(), cngtyp2(), delete_stmt(), direct_loop_end(), direct_loop_enter(), DT_ISVEC, DTY, DTYG, dtype, error83(), errsev(), FALSE, gbl, is_iso_cptr(), lhs, mk_assn_stmt(), mkexpr1(), mklvalue(), NULL, p, SEM::p_dealloc, SEM::p_dealloc_delete, SEM::return_value, S_EXPR, S_LVALUE, S_STFUNC, sem, sptr, SST_ASTG, SST_DTYPEG, SST_IDG, SST_LSYMG, SST_SHAPEG, SST_SYMG, STD_AST, stktop, subst_lhs_arrfn(), t, and SEM::try.
assign_pointer()
int assign_pointer (SST * newtop, SST * stktop)
Definition at line 3914 of file semutil.c.
References add_ptr_assign(), argt, ARGT_ARG, SEM::arrfn, assign_intrinsic_to_pointer(), ast, SEM::call_std, chk_pointer_intent(), chk_pointer_target(), CNULL, dest, dtype, err_protected(), ERR_Severe, error(), find_pointer_variable_assign(), FLANG_FALLTHROUGH, gbl, intrinsic_as_arg(), IS_INTRINSIC, is_procedure_ptr(), is_protected(), mk_id(), mkexpr2(), mklvalue(), NULL, proc_arginfo(), SEM::return_value, S_EXPR, S_IDENT, select_gsame(), sem, set_assn(), sptr, SST_ASTG, SST_ASTP, SST_DIMFLAGG, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_SHAPEG, SST_SHAPEP, SST_SYMG, STD_AST, stktop, subst_lhs_pointer(), sym_of_ast(), SYMNAME, SEM::try, and valid_assign_pointer_types().
Referenced by add_assign_firstprivate(), add_ptr_assignment(), and semant3().
binop()
void binop (SST * rslt, SST * lop, SST * operator, SST * rop)
Perform a binary operation on rhs1 and rhs2. They both conform in data type and shape.
Definition at line 5126 of file semutil.c.
References _xtok(), AD_DPTR, AD_NUMDIM, and64(), assert, BCOPY, chklog(), chkopnds(), clog_to_log(), cmp64(), cngcon(), const_fold(), const_xtoi(), constant_lvalue(), CONVAL2G, count, DT_INT, DT_ISINT, STB::dt_log, DT_LOG, DTY, errsev(), FALSE, get_array_dtype(), get_type(), getcon(), getitem(), getstring(), interr(), kanji_len(), mk_binop(), mk_cval(), mkexpr(), mkexpr1(), mklogint4(), STB::n_base, OP_ADD, OP_AND, OP_CAT, OP_CMP, OP_DIV, OP_EQ, OP_EQV, OP_GE, OP_GT, OP_LAND, OP_LE, OP_LEQV, OP_LNEQV, OP_LOG, OP_LOR, OP_LT, OP_MUL, OP_NE, OP_OR, OP_SUB, OP_XOR, OP_XTOI, OP_XTOX, or64(), res, S_CONST, S_EXPR, S_STFUNC, SCFTN_FALSE, SCFTN_TRUE, SST_ASTP, SST_CVALG, SST_CVALP, SST_CVLENG, SST_CVLENP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_OPCG, SST_OPTYPEG, SST_SYMG, SST_SYMP, stb, string_length(), TRUE, TY_CHAR, TY_DWORD, TY_ISCMPLX, TY_ISLOG, TY_LOG8, TY_NCHAR, TY_OF, TY_WORD, TYPE_OF, STB::user, val, and xor64().
Referenced by common_rel(), gen_reduction(), and semant2().
casttyp()
int casttyp (SST * old, int newcast)
Cast a given semantic entry into a desired type. No type conversion is done.
Returns
1 if no error, -1 if error
The following casts are ok:
Cast any of the data types to TY_WORD or TY_DWORD (necessary for the bitwise intrinsics and relational comparisons)
Cast a TY_WORD or TY_DWORD to any of the data types (necessary for casting the bitwise intrinsics back to a data type)
Since this is used primarily for the bitwise intrinsics, there is no need to support TY_DBLE, TY_CHAR, TY_CMPX, or TY_DCMPX since these types are illegal for these intrinsics. However, cast of TY_DWORD and TY_WORD to TY_CMPX and TY_DCMPLX is needed for relational comparisons. Comparisons between vector typed and typeless operands require typed vectors to be casted to typeless vectors.
Definition at line 306 of file semutil.c.
References cast_types, cngtyp(), STB::dt_int, DT_INT, DTY, DTYG, _acl::dtype, errsev(), FALSE, get_type(), im, mkexpr1(), S_ACONST, size_of(), SST_ACLG, SST_DTYPEG, SST_DTYPEP, SST_IDG, stb, TRUE, TY_INT8, and STB::user.
Referenced by cast_to_typeless(), chkopnds(), cngtyp2(), and ref_pd().
ch_substring()
void ch_substring (SST * stktop, SST * lb_sp, SST * ub_sp)
Substring of a character constant.
Definition at line 3189 of file semutil.c.
References ast, BCOPY, chk_scalartyp(), chktyp(), CONVAL2G, cp, DINIT_END, DINIT_LOC, dinit_put(), DINIT_STR, DT_INT, DT_ISINT, DTY, dtype, errsev(), FALSE, get_type(), getcctmp(), getcon(), getitem(), getstring(), kanji_len(), mk_cnst(), mk_cval(), mk_id(), mk_substr(), STB::n_base, p, S_CONST, S_EXPR, S_NULL, SST_ASTG, SST_ASTP, SST_CVALG, SST_CVALP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, stb, stktop, str, string_length(), strlen(), sym_is_refd(), TRUE, TY_CHAR, TY_NCHAR, val, and void().
Referenced by mkvarref(), semant1(), and semant2().
check_etmp()
int check_etmp (SST * stkp)
If temps were allocated while processing the expression, the expression needs to be assigned to a temp, the allocatable temps need to be deallocated, and the use of the expression is replaced by the temp.
Definition at line 12232 of file semutil2.c.
References add_stmt(), ast, SEM::etmp_list, FALSE, gen_dealloc_etmps(), NULL, sem, sem_tempify(), SST_ASTG, SEM::use_etmps, and void().
Referenced by gen_logical_if_expr(), semant2(), and semant3().
chk_arr_extent()
INT chk_arr_extent (SST * stkptr, const char * msg)
Restrict the expression to be suitable for an array extent.
Definition at line 259 of file semutil.c.
References astb, ASTB::bnd, chk_scalar_inttyp(), chk_scalartyp(), ASTB::dtype, FALSE, flg, msg(), and FLG::standard.
Referenced by semant1().
chk_scalar_inttyp()
INT chk_scalar_inttyp (SST * stkptr, int dtype, const char * msg)
Same as chktyp() with the restriction that the expression must be a scalar (i.e., not an array/vector form) and integer (i.e., not logical).
Definition at line 242 of file semutil.c.
References chktyp(), DT_ISINT, DT_ISLOG, DT_ISNUMERIC, DTY, error(), errsev(), FALSE, flg, gbl, msg(), SST_DTYPEG, and FLG::standard.
Referenced by chk_arr_extent(), and semant3().
chk_scalartyp()
INT chk_scalartyp (SST * stkptr, int dtype, LOGICAL warnflg)
Same as chktyp() with the restriction that the expression must be a scalar (i.e., not an array/vector form).
Definition at line 227 of file semutil.c.
References chktyp(), DTY, errsev(), and SST_DTYPEG.
Referenced by ch_substring(), chk_arr_extent(), chksubstr(), gen_logical_if_expr(), semant1(), semant2(), semant3(), semantio(), and semsmp().
chkarg()
int chkarg (SST * stkptr, int * dtype)
Performing checking on an argument to determine if it needs to be "protected".
Parameters
stkptr a stack entry representing a subprogram argument
dtype used to pass out data type of argument
Returns
sptr for alternate return label
When an argument needs to be protected, its value may be have to be stored in a temp and then the temp's address becomes the actual argument. This occurs when a parenthesized expression is an actual argument. NOTE that the logic in chkarg relies on an argument being <expression>; a flag (SST_PARENG/P) in the semantic stack is used and is only defined for <expression>; the flag is cleared when <expression> ::= ... occurs and is set when <primary> ::= (<expression>) occurs.
Definition at line 1138 of file semfunc2.c.
References A_ISLVAL, ast, DT_INT, DT_ISSCALAR, DTY, FLANG_FALLTHROUGH, gbl, GSAMEG, mk_paren(), mkarg(), mkexpr(), newsym(), ref_entry(), RU_FUNC, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_LVALUE, select_gsame(), sem_set_storage_class(), sptr, SST_ASTG, SST_ASTP, SST_DTYPEG, SST_IDG, SST_PARENG, SST_SYMG, TY_CHAR, TY_NCHAR, and void().
Referenced by args_match(), chk_arguments(), func_call2(), ptrfunc_call(), ptrsubr_call(), and subr_call2().
chkcon()
INT chkcon (SST * stkptr, int dtype, LOGICAL warnflg)
Check that the indicated semantic stack entry is a constant of the specified type and convert constant to new type if possible.
Returns
32-bit constant value or symbol table pointer.
Definition at line 98 of file semutil.c.
References cngcon(), constant_lvalue(), DT_ISINT, DT_ISREAL, DT_LOG, DTY, errsev(), errwarn(), flg, getstring(), S_CONST, S_EXPR, SCFTN_TRUE, SST_ASTG, SST_DTYPEG, SST_IDG, SST_SYMG, FLG::standard, TY_CHAR, TY_ISINT, TY_ISLOG, and TY_NCHAR.
Referenced by chkcon_to_isz(), get_param_alias_const(), semant1(), and semant3().
chkcon_to_isz()
ISZ_T chkcon_to_isz (SST * stkptr, LOGICAL warnflg)
Check that the indicated semantic stack entry is a constant of any integer type.
Returns
the integer value as type ISZ_T.
Issue an error message if stkptr is not a constant of the correct type.
Definition at line 165 of file semutil.c.
References chkcon(), CONVAL2G, DT_INT, DT_ISINT, dtype, errsev(), INT64_2_ISZ, ISZ_T, num, S_CONST, size_of(), SST_CVALG, SST_DTYPEG, SST_IDG, and XBIT.
Referenced by semant1(), and semsmp().
chklog()
int chklog (SST * stkptr)
Definition at line 1042 of file semutil.c.
References cngtyp(), DT_LOG, DTYG, errsev(), flg, mkexpr1(), S_CONST, SST_CVALP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_ISNONDECC, FLG::standard, TY_CHAR, TY_DWORD, TY_ISINT, and TY_ISLOG.
Referenced by binop(), chkopnds(), common_rel(), and log_negation().
chkopnds()
void chkopnds (SST * lop, SST * operator, SST * rop)
Make two operands conform in a binary operation. The sequence of events is crucial to correct interpretation of expression.
Definition at line 4739 of file semutil.c.
References ARITH, cast_to_typeless(), casttyp(), chklog(), chkshape(), cngshape(), cngtyp(), CONVAL2G, DDTG, DT_INT, DT_LOG, DTY, error83(), errsev(), errwarn(), flg, FLG::ieee, is_dbl0(), is_quad0(), mk_cval1(), mkexpr1(), num, OK_LTYP, OP_AND, OP_CAT, OP_CMP, OP_EQV, OP_LAND, OP_LEQV, OP_LOG, OP_LOR, OP_OR, OP_XOR, OP_XTOI, POW1, POW2, PT_OF, S_CONST, SST_ASTP, SST_CVALG, SST_CVALP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_ISNONDECC, SST_OPCG, SST_OPCP, SST_OPTYPEG, FLG::standard, TRUE, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT8, TY_ISCMPLX, TY_ISINT, TY_ISLOG, TY_ISNUMERIC, TY_ISVEC, TY_NCHAR, TY_OF, TY_QUAD, TY_REAL, TY_WORD, TYPE_OF, void(), XBIT, xdisint(), xfisint(), and xqisint().
Referenced by binop().
chkshape()
LOGICAL chkshape (SST * old, SST * new, LOGICAL promote)
Semantically check an operand (old) for array conformance with operand new. If the operand is a scalar, change the shape of the operand to conform with the expected shape. If the operand is an array, check for conformance.
Parameters
old operand to check
new operand to conform with
promote if true, promote scalar to vector
Returns
TRUE if shapes are conformant; false, otherwise.
Definition at line 1017 of file semutil.c.
References ast, conform_shape(), DTY, dup_array_dtype(), mk_promote_scalar(), SST_ASTG, SST_ASTP, SST_DTYPEG, SST_DTYPEP, SST_SHAPEG, SST_SHAPEP, and TRUE.
Referenced by chkopnds(), and ref_pd().
chksubscr()
INT chksubscr (SST * stkptr, int sptr)
Convert expression pointed to by stkptr from its current data type to a data type consistent with subscripting.
Returns
the ILM pointer
Definition at line 272 of file semutil.c.
References astb, ASTB::bnd, cngtyp(), CNULL, DTY, DTYG, ASTB::dtype, error(), errsev(), gbl, mkexpr1(), rank_of_ast(), sptr, SST_ASTG, SST_DTYPEG, SST_ISNONDECC, SYMNAME, TY_INT8, and TY_ISINT.
Referenced by ref_array().
chksubstr()
int chksubstr (SST * stktop, ITEM * item)
Check that substring specifier is correct, write SUBS (substring) ILM and return pointer to it.
Definition at line 3029 of file semutil.c.
References ast, ast_intr(), astb, ASTB::bnd, chk_scalartyp(), chktyp(), cngcon(), CNULL, CONVAL2G, DDTG, STB::dt_int, DT_ISINT, DTY, dtype, ASTB::dtype, error(), FALSE, gbl, get_type(), ASTB::i1, interr(), ITEM_END, mk_binop(), mk_convert(), mk_cval(), mk_substr(), xyyz::next, OP_ADD, OP_SUB, ref_entry(), ref_object(), S_CONST, S_DERIVED, S_LVALUE, S_NULL, S_TRIPLE, size_ast(), sptr, SST_ASTG, SST_ASTP, SST_CVALG, SST_CVALP, SST_CVLENP, SST_DTYPEG, SST_DTYPEP, SST_E1G, SST_E2G, SST_E3G, SST_IDG, SST_IDP, SST_LSYMG, SST_LSYMP, SST_SHAPEP, SST_SYMG, stb, xyyz::stkp, stktop, string_length(), SYMNAME, t, xyyz::t, TRUE, TY_CHAR, TY_INT8, TY_NCHAR, and STB::user.
Referenced by mkvarref().
chktyp()
INT chktyp (SST * stkptr, int dtype, LOGICAL warnflg)
Convert expression pointed to by stkptr from its current data type to data type dtype.
Returns
ILM pointer
Definition at line 199 of file semutil.c.
References cngtyp(), DT_INT, DTY, DTYG, errwarn(), mkexpr1(), S_CONST, SST_DTYPEG, SST_IDG, SST_ISNONDECC, TY_ISINT, and TY_ISLOG.
Referenced by assign(), ch_substring(), chk_expr(), chk_scalar_inttyp(), chk_scalartyp(), chk_unitid(), chksubstr(), collapse_add(), collapse_begin(), collapse_index(), ref_intrin(), ref_pd(), ref_stfunc(), semant1(), semant3(), and semsmp().
cngshape()
void cngshape (SST * old, SST * new)
Definition at line 942 of file semutil.c.
References assert, ast, CNULL, conform_shape(), DT_INT, DTY, DTYG, dup_array_dtype(), error(), error83(), errsev(), FALSE, gbl, interr(), is_iso_c_loc(), mk_promote_scalar(), mkexpr1(), S_EXPR, SST_ASTG, SST_ASTP, SST_DTYPEG, SST_DTYPEP, SST_IDP, SST_SHAPEG, SST_SHAPEP, TRUE, TY_CHAR, TY_ISVEC, UFCHAR, and void().
Referenced by assign(), chkopnds(), and unop().
cngtyp()
void cngtyp (SST * old, DTYPE newtyp)
Convert expression pointed-to by old to the data type newtyp.
Main entry point for cngtyp2() that assumes no polymorphic expressions.
Parameters
old points to the semantic stack entry with the old data type.
newtyp is the new dtype for the old semantic stack entry.
Definition at line 936 of file semutil.c.
References cngtyp2().
Referenced by assign(), byvalue_ref_arg(), casttyp(), chk_arguments(), chklog(), chkopnds(), chksubscr(), chktyp(), cngtyp2(), compute_size_expr(), form_cmplx_const(), log_negation(), ref_intrin(), ref_pd(), semant2(), semant3(), and unop().
constant_lvalue()
void constant_lvalue (SST * stkptr)
If stkptr is an LVALUE that has a constant value, replace it with the constant value.
Definition at line 70 of file semutil.c.
References ast, astb, CONVAL2G, DT_ISWORD, dtype, S_CONST, S_LVALUE, sptr, SST_ASTG, SST_ASTP, SST_DTYPEP, SST_IDG, SST_IDP, and SST_SYMP.
Referenced by binop(), chkcon(), ref_array(), semant1(), and unop().
construct_acl_for_sst()
void construct_acl_for_sst (SST * istkp, DTYPE dtype)
Definition at line 5045 of file semutil2.c.
References AC_IEXPR, AC_INTR_CALL, ADD_NUMELM, _acl::ast, construct_acl_from_ast(), CONVAL2G, DDTG, SEM::dinit_error, DTY, _acl::dtype, errsev(), _acl::expr, get_getitem_p(), has_type_parameter(), _acl::id, init_types_compatable(), interr(), no_data_components(), AEXPR::op, SEM::param_struct_constr, _acl::repeatc, rewrite_acl(), S_ACONST, S_CONST, S_EXPR, S_IDENT, S_LVALUE, S_SCONST, sem, sptr, SST_ACLG, SST_ACLP, SST_ASTG, SST_DTYPEG, SST_IDG, SST_SYMG, TRUE, and _acl::u1.
Referenced by convert_ctmp_array_to_param(), fixup_param_vars(), get_param_alias_const(), and semant1().
cuda_call()
void cuda_call (SST * stktop, ITEM * list, ITEM * chevlist)
define_stfunc()
int define_stfunc (int sptr, ITEM * argl, SST * estk)
Perform error checking and create statement function descriptor for statement function definition.
Definition at line 99 of file semfunc2.c.
References _non_private(), arg, ARGINFOG, ARGINFOP, _sfuse::args, SFDSC::args, ast, ast_replace(), ast_rewrite(), ast_traverse(), ast_unvisit(), ast_visit(), CNULL, DBGBIT, arginfo::dtype, dump_stfunc(), end_sfuse, error(), gbl, getitem(), ITEM_END, itemp, l_sfuse, mkexpr(), new_node(), _arginfo::next, _sfuse::next, arginfo::next, NOSYM, NULL, put_getitem_p(), SFDSCP, sptr, SST_ASTG, SST_SYMG, stfunc_argl, and SYMNAME.
Referenced by semant3().
defined_operator()
int defined_operator (int opr, SST * stktop, SST * lop, SST * rop)
Definition at line 861 of file semgnr.c.
References STB::curr_scope, DBGBIT, DT_INT, findByNameStypeScope(), func_call2(), gbl, i, list, make_list(), mk_id(), mkident(), queue_generic_tbp_once(), queue_tbp(), resolve_operator(), S_CONST, sptr, SST_ASTP, SST_DTYPEP, SST_IDP, SST_SYMP, stb, stktop, SYMNAME, and TBP_COMPLETE_GENERIC.
Referenced by semant2().
dinit_struct_param()
void dinit_struct_param (SPTR sptr, ACL * sconst, DTYPE dtype)
Definition at line 7590 of file semutil2.c.
Referenced by convert_ctmp_array_to_param(), and fixup_param_vars().
dinit_varref()
VAR * dinit_varref (SST * stkp)
Create an initialization node for a variable reference in a data statement.
If the variable reference is an array section (tpr1652) an implied do is generated for each subscript which is a triple. For example, the array section:
     A(i1, L2:U2, L3:U3, i4)
is transformed into:
     ( ( A(i1, j2, j3, i4) j2 = L2, U2 ), j3 = L3, U3 )
Each triple subscript is replaced by an implied do index variable, and the expressions in the triplet becomes the bounds of the implied do. Sections are to be initialized in array element order (i.e., column major). An implied do nest is produced by a left to right scan of the subscripts (the leftmost triple represents the innermost implied do).
If the variable reference is a member of a whole array, turn the whole array reference into a subscripted reference where each subscript is a triple. Then, the subscripted referenced is handled as described above.
For other variable references, a single initialization node is created.
Definition at line 7709 of file semutil2.c.
Referenced by gen_dinit(), gen_varref_var(), init_sptr_w_acl(), and semant1().
do_openmp_atomics()
int do_openmp_atomics (SST * l_stktop, SST * r_stktop)
Definition at line 7019 of file semsmp.c.
References SEM::action_type, add_stmt(), AOP_UNDEF, SEM::apply, ast, ATOMIC_CAPTURE, ATOMIC_READ, ATOMIC_UPDATE, ATOMIC_WRITE, CNULL, DTY, DTYG, error(), FALSE, gbl, SEM::mem_order, mk_atomic_capture(), mk_atomic_read(), mk_atomic_update_binop(), mk_atomic_update_intr(), mk_atomic_write(), mkexpr1(), mklvalue(), MO_UNDEF, SEM::mpaccatomic, SEM::rmw_op, SEM::seen, sem, SST_ASTG, SST_ASTP, SST_DTYPEG, SST_SHAPEG, TRUE, validate_atomic_expr(), and void().
Referenced by semant3().
fix_term()
int fix_term (SST * stktop, int sptr)
Repair a bad term in an expression.
Done by using the constant (sptr) passed to this routine. An xCON ILM is generated referencing this constant.
Definition at line 3312 of file semutil.c.
References DTY, interr(), S_EXPR, sptr, SST_DTYPEP, SST_IDP, stktop, TY_DBLE, TY_INT, TY_INT8, and TY_REAL.
Referenced by ref_intrin(), ref_pd(), and semant2().
func_call()
int func_call (SST * stktop, ITEM * list)
Definition at line 1481 of file semfunc.c.
References ast, func_call2(), generic_func(), IS_TBP, list, memsym_of_ast(), NOSYM, resolve_fwd_ref(), sptr, SST_ASTG, SST_SYMG, and stktop.
Referenced by mkexpr1(), and mkvarref().
func_call2()
int func_call2 (SST * stktop, ITEM * list, int flag)
Write ILMs to call a function.
Parameters
stktop function to call
list arguments to pass to function
flag set if called from a generic resolution routine
Definition at line 791 of file semfunc.c.
References A_TKNP, add_auto_dealloc(), add_p_dealloc_item(), add_stmt(), add_stmt_before(), SEM::alloc_std, allocatable_member(), ARG_AST, ARG_STK, argt, ARGT_ARG, SEM::arrfn, assn(), ast, astb, aux, byvalue_ref_arg(), SEM::call_std, carg, check_arguments(), chkarg(), CNULL, count, count_actuals(), count_formals(), dt, STB::dt_cmplx, STB::dt_int, STB::dt_log, STB::dt_real, SEM::dtemps, DTY, DTYG, dtype_with_shape(), error(), errwarn(), FALSE, find_byval_ref(), FREE, FUNCLINEG, gbl, gen_allocatable_result(), gen_and_assoc_tmp_ptr(), gen_array_result(), gen_char_result(), gen_finalized_result(), gen_pointer_result(), generic_tbp_func(), get_all_descriptors(), get_arr_temp(), get_byval(), get_implementation(), get_len_of_deferchar_ast(), get_next_sym(), get_specific_member(), get_static_descriptor(), get_sym_from_sst_if_available(), get_tbp_argno(), getcctmp_sc(), getitem(), i, ASTB::i0, SCN::id, inc_dummy_param(), init_byval(), init_derived_type(), INTENT_IN, INTENTG, is_iso_cloc(), is_iso_cptr(), is_ptr_arg(), IS_TBP, ITEM_END, itemp, SEM::last_std, list, AUX::list, make_kwd_str(), mem(), memsym_of_ast(), mk_argt(), mk_assn_stmt(), mk_convert(), mk_func_node(), mk_id(), mk_member(), mk_stmt(), mkarg(), mkshape(), SCN::name, name, need_tmp_retval(), new_ast(), NULL, OP_BYVAL, OP_REF, OP_VAL, PASS_BYVAL, pass_char_no_len(), pass_sym_of_ast(), SEM::proc_initializer, ASTB::ptr0, ref_entry(), replace_memsym_of_ast(), SEM::return_value, S_DERIVED, S_EXPR, S_IDENT, S_KEYWORD, S_LABEL, S_LVALUE, S_SCONST, S_TRIPLE, SEM::sc, scn, sem, sem_tempify(), set_descriptor_sc(), set_pass_objects(), SEM::sptr, SST_ASTG, SST_ASTP, SST_CVALG, SST_CVLENP, SST_DTYPEP, SST_ERRSYMP, SST_IDG, SST_IDP, SST_LSYMG, SST_SHAPEP, SST_SYMG, SST_SYMP, stb, STD_PREV, stktop, strlen(), sym_of_ast(), SYMNAME, tempify(), TY_CHAR, TY_CMPLX, TY_INT, TY_LOG, TY_REAL, STB::user, void(), and XBIT.
Referenced by defined_operator(), func_call(), generic_func(), and is_intrinsic_opr().
generic_call()
void generic_call (int gnr, SST * stktop, ITEM * list, ITEM * chevlist)
Definition at line 174 of file semgnr.c.
References DBGBIT, gbl, ITEM_END, list, NULL, resolve_generic(), sptr, SST_ASTP, SST_SYMP, stktop, subr_call2(), and SYMNAME.
Referenced by subr_call2().
generic_func()
int generic_func (int gnr, SST * stktop, ITEM * list)
Definition at line 220 of file semgnr.c.
References DBGBIT, DT_INT, STB::firstosym, func_call2(), gbl, ITEM_END, list, mk_id(), mkident(), NULL, ref_intrin(), ref_pd(), resolve_generic(), S_CONST, sptr, SST_ASTP, SST_DTYPEP, SST_IDP, SST_SYMP, stb, stktop, and SYMNAME.
Referenced by func_call(), mkvarref(), and ref_intrin().
generic_tbp_call()
int generic_tbp_call (int gnr, SST * stktop, ITEM * list, ITEM * chevlist)
Definition at line 155 of file semgnr.c.
References DBGBIT, gbl, ITEM_END, list, NULL, queue_generic_tbp_once(), queue_tbp(), resolve_generic(), sptr, stktop, SYMNAME, and TBP_COMPLETE_GENERIC.
Referenced by subr_call2().
generic_tbp_func()
int generic_tbp_func (int gnr, SST * stktop, ITEM * list)
Definition at line 200 of file semgnr.c.
References DBGBIT, gbl, ITEM_END, list, NULL, queue_generic_tbp_once(), queue_tbp(), resolve_generic(), sptr, stktop, SYMNAME, and TBP_COMPLETE_GENERIC.
Referenced by func_call2().
get_sst_cval()
INT get_sst_cval (SST * stkp)
Get the SST_CVAL-like value for a semantic stack entry already determined to be a constant (i.e., is_sst_const() is true).
SST_CVAL-like means just the the sst's CVAL field. If the stack has been evaluated (is an S_EXPR), need to get CVAL from the ast.
Definition at line 2547 of file semutil.c.
References assert, ast, CONVAL2G, DTY, S_CONST, S_EXPR, sptr, SST_ASTG, SST_CVALG, SST_IDG, TY_BINT, TY_BLOG, TY_INT, TY_LOG, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by ref_pd(), and set_kind_result().
is_intrinsic_opr()
LOGICAL is_intrinsic_opr (int val, SST * stktop, SST * lop, SST * rop, int tkn_alias)
Definition at line 1087 of file semgnr.c.
References ast, buf, CNULL, DBGBIT, SEM::dtemps, DTYG, E155, error(), FALSE, func, func_call2(), gbl, get_implementation(), get_tbp_argno(), get_type_rank(), getccsym_sc(), IS_TBP, list, make_list(), mem(), mk_id(), mkexpr(), mkident(), mkmember(), SEM::mod_cnt, name, NULL, OP_ST, optabstruct::opr, optab, queue_generic_tbp_once(), queue_tbp(), rank, resolve_operator(), S_SCONST, sem, SST_ASTG, SST_ASTP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_SYMP, stktop, subr_call2(), SYMNAME, TBP_COMPLETE_GENERIC, tmp, TRUE, val, and SEM::which_pass.
Referenced by common_rel(), log_negation(), semant2(), and semant3().
is_sst_const()
LOGICAL is_sst_const (SST * stk)
Check if a stack entry represents a constant or an expression evaluated to a constant.
Definition at line 2524 of file semutil.c.
References FALSE, S_CONST, S_EXPR, SST_ASTG, SST_IDG, stk, and TRUE.
Referenced by ref_intrin(), ref_pd(), and set_kind_result().
is_varref()
LOGICAL is_varref (SST * stk)
Check if a stack entry is a legal variable reference.
This routine is used when it's known that a variable reference is required and a check is necessary before calling routines like like mkvarref and mklvalue.
Definition at line 2585 of file semutil.c.
References FALSE, S_IDENT, S_LVALUE, SST_IDG, stk, and TRUE.
Referenced by chk_expr(), chk_var(), ref_intrin_subr(), ref_pd(), ref_pd_subr(), semant3(), and semantio().
mk_storage()
int mk_storage (int sptr, SST * stkp)
Definition at line 8856 of file semsmp.c.
References interr(), S_IDENT, sptr, SST_CVLENP, SST_DTYPEP, SST_IDP, SST_SHAPEP, SST_SYMG, and SST_SYMP.
Referenced by add_assign_firstprivate(), do_reduction(), end_lastprivate(), gen_reduction(), and mk_firstprivate().
mkarg()
int mkarg (SST * stkptr, int * dtype)
Check and write ILMs for a subprogram argument.
Parameters
stkptr a stack entry representing a subprogram argument
dtype used to pass out data type of argument
Returns
sptr for alternate return label
Definition at line 558 of file semfunc2.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_UPAST, ADD_UPBD, ast, astb, ASTB::bnd, CNULL, DDTG, dt, DT_INT, SEM::dtemps, DTY, FLG::endian, error(), find_pointer_variable(), FLANG_FALLTHROUGH, flg, gbl, get_all_descriptors(), get_static_descriptor(), getcctmp_sc(), GSAMEG, ASTB::i0, init_derived_w_acl(), init_sptr_w_acl(), interr(), intrinsic_as_arg(), mk_extent(), mk_id(), mkarg(), mkexpr(), mkident(), mkvarref(), newsym(), ASTB::one, FLG::recursive, ref_entry(), ref_object(), RU_FUNC, RU_SUBR, S_ACONST, S_CONST, S_DERIVED, S_EXPR, S_IDENT, S_KEYWORD, S_LABEL, S_LOGEXPR, S_LVALUE, S_REF, S_SCONST, S_STAR, S_STFUNC, S_TRIPLE, S_VAL, SEM::sc, select_gsame(), sem, sem_set_storage_class(), size_ast(), sptr, SST_ACLG, SST_ASTG, SST_ASTP, SST_CVLENP, SST_DBEGG, SST_DTYPEG, SST_DTYPEP, SST_E3G, SST_ENDG, SST_IDG, SST_IDP, SST_LSYMG, SST_SHAPEP, SST_SYMG, SST_SYMP, sym_get_array(), SYMNAME, tempify(), TY_BINT, TY_BLOG, TY_CHAR, TY_NCHAR, TY_SINT, TY_SLOG, void(), and ASTB::zero.
Referenced by byvalue_ref_arg(), chk_expr(), chk_fmtid(), chk_unitid(), chk_var(), chkarg(), count_actuals(), evl_kwd_args(), func_call2(), gen_init_intrin_call(), gen_spec_item_tmp(), get_sym_from_sst_if_available(), mkarg(), ptrfunc_call(), ptrsubr_call(), ref_intrin(), ref_intrin_subr(), ref_pd(), ref_pd_subr(), semant2(), semant3(), semantio(), and subr_call2().
mkexpr()
int mkexpr (SST * stkptr)
Definition at line 1093 of file semutil.c.
References mkexpr1(), and mklogint4().
Referenced by _constructf90(), binop(), byvalue_ref_arg(), chk_expr(), chkarg(), compute_size_expr(), construct_association(), define_stfunc(), evl_kwd_args(), gen_dtio_args(), is_intrinsic_opr(), mkarg(), mkexpr_assign_temp(), mklabelvar(), ref_intrin(), ref_pd(), ref_pd_subr(), ref_stfunc(), resolve_generic(), rewrite_acl(), semant1(), semant2(), semant3(), semantio(), sum_scatter_args(), and tempify().
mkexpr1()
int mkexpr1 (SST * stkptr)
Given a semantic stack entry, write ILM's for the expression represented by the stack entry if they have not already been written.
Returns
pointer to ILM
Definition at line 1107 of file semutil.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_UPAST, ADD_UPBD, astb, ASTB::bnd, CNULL, DDTG, SEM::dinit_data, dont_issue_assumedsize_error, DT_INT, DT_ISBASIC, DTY, dtype, error(), error83(), errsev(), FLANG_FALLTHROUGH, func_call(), gbl, get_all_descriptors(), get_next_hash_link(), get_static_descriptor(), getcon(), init_sptr_w_acl(), intast_sym, interr(), ITEM_END, mk_cnst(), mk_extent(), mk_id(), mkident(), mkvarref(), newsym(), NOSYM, NULL, num, ASTB::one, ref_entry(), ref_object(), ref_pd(), RU_FUNC, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_LOGEXPR, S_LVALUE, S_REF, S_STAR, S_STFUNC, S_VAL, sem, sem_set_storage_class(), size_ast(), sptr, SST_ACLG, SST_ASTG, SST_ASTP, SST_CVLENP, SST_DTYPEG, SST_DTYPEP, SST_ENDG, SST_IDG, SST_IDP, SST_LSYMG, SST_LSYMP, SST_SHAPEP, SST_SYMG, SST_SYMP, sym_get_array(), SYMNAME, test_scope(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, void(), and ASTB::zero.
Referenced by assign(), binop(), casttyp(), chklog(), chkopnds(), chksubscr(), chktyp(), cngshape(), cngtyp2(), collapse_add(), collapse_begin(), collapse_index(), do_openmp_atomics(), gen_logical_if_expr(), mkexpr(), mkexpr2(), semant3(), unop(), and validate_omp_atomic().
mkexpr2()
int mkexpr2 (SST * stkptr)
Same as mkexpr1(), but the expression is the target of a pointer assignment. Must handle ST_PROCs as identifiers; otherwise, just call mkexpr1().
Definition at line 1389 of file semutil.c.
References DDTG, dt, DTY, mk_id(), mkexpr1(), ref_object(), S_IDENT, size_ast(), sptr, SST_ASTG, SST_ASTP, SST_CVLENP, SST_DTYPEP, SST_IDG, SST_SHAPEP, SST_SYMG, TY_CHAR, and TY_NCHAR.
Referenced by _constructf90(), and assign_pointer().
mkident()
void mkident (SST * stkptr)
Definition at line 1084 of file semutil.c.
References S_IDENT, SST_ALIASP, SST_CVLENP, SST_IDP, and SST_SHAPEP.
Referenced by defined_operator(), gen_dinit(), gen_dtio_args(), generic_func(), is_intrinsic_opr(), mkarg(), mkexpr1(), mkvarref(), ref_intrin(), semant1(), semant2(), semant3(), and tempify().
mklabelvar()
int mklabelvar (SST * stkptr)
Given an ast which computes the address of the label variable or loads the label variable, create the variable of indicated dtype.
Definition at line 6716 of file semutil.c.
References ast, dtype, getcctmp_sc(), interr(), mk_id(), mkexpr(), SEM::sc, sem, sptr, SST_ASTG, SST_ASTP, SST_DTYPEP, and XBIT.
Referenced by chk_fmtid(), and semant3().
mklogint4()
void mklogint4 (SST * stkptr)
Convert all sizes of logicals and integers to 4 byte versions.
Definition at line 1418 of file semutil.c.
Referenced by binop(), and mkexpr().
mklvalue()
int mklvalue (SST * stkptr, int stmt_type)
Check for legal variable to be assigned to.
Parameters
stkptr the variable to check
stmt_type type of statement we are processing, from the table below
Returns
The sptr of the variable if stmt_type indicates an index variable.
Otherwise the ILM pointer to address expression for the destination.
Zero is returned for cases where we want to avoid assignment code generation.
Possible values for stmt_type:
     0 - Do index var
     1 - Assignment statement
     2 - Data statement
     3 - LOC reference
     4 - Implied do index var
     5 - Forall index var
Definition at line 1442 of file semutil.c.
References AD_DPTR, AD_LWAST, AD_LWBD, AD_NUMDIM, ASD_NDIM, ASD_SUBS, ast, check_member(), CNULL, STB::curr_scope, DCLCHK, DDTG, decl_private_sym(), DI_ATOMIC_CAPTURE, DI_DISTPARDO, DI_DISTRIBUTE, DI_FORALL_DTYPE, DI_FORALL_SYMAVL, DI_ID, DI_PARDO, DI_PDO, DI_SIMD, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TASK, DI_TASKLOOP, DI_TEAMSDIST, DI_TEAMSDISTPARDO, SEM::dinit_error, DOCHK, SEM::doconcurrent_dtype, SEM::doconcurrent_symavl, SEM::doif_depth, DT_INT, DTY, DTYG, dtype, error(), errsev(), SEM::expect_cuf_do, FALSE, FLANG_FALLTHROUGH, flg, gbl, get_all_descriptors(), get_static_descriptor(), getbase(), getccsym(), GSAMEG, i, SEM::ignore_default_none, SEM::index_sym_to_pop, insert_sym(), INTENTG, interr(), MAXDIMS, memsym_of_ast(), mk_id(), mk_subscr(), mkshape(), newsym(), SEM::orph, SEM::parallel, prtsst(), ref_entry(), ref_object(), RU_FUNC, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_LVALUE, sem, sem_check_scope(), sem_set_storage_class(), set_assn(), setimplicit(), size_ast(), FLG::smp, sptr, SST_ASTG, SST_ASTP, SST_CVLENP, SST_DTYPEG, SST_DTYPEP, SST_ERRSYMG, SST_IDG, SST_LSYMG, SST_SHAPEG, SST_SHAPEP, SST_SYMG, FLG::standard, stb, sym_of_ast(), SYMNAME, SEM::target, SEM::task, SEM::teams, TRUE, TY_CHAR, TY_NCHAR, and XBIT.
Referenced by assign(), assign_pointer(), do_openmp_atomics(), gen_reduction(), ref_intrin(), semant1(), semant2(), semant3(), and validate_omp_atomic().
mkvarref()
int mkvarref (SST * stktop, ITEM * list)
Make a var ref of the form: <var primary> ([<ssa list>])
Determine if a function call, array reference, or substring reference, and generate appropriate ILMs, shapes, data types. stktop is input and output.
Definition at line 2063 of file semutil.c.
References add_base(), ASD_NDIM, ASD_SUBS, ast, ch_substring(), chksubstr(), CNULL, ddtype(), dinit(), SEM::dinit_error, DT_INT, DTY, DTYG, dtype, error(), FALSE, FLANG_FALLTHROUGH, flg, func_call(), gbl, generic_func(), getbase(), getcon(), getstring(), GSAMEG, i, init_sptr_w_acl(), interr(), IS_CHAR_TYPE, is_procedure_ptr(), ITEM_END, list, memsym_of_ast(), mk_cnst(), mk_id(), mkident(), ndim, newsym(), next, NOSYM, NULL, ptrfunc_call(), FLG::recursive, ref_array(), ref_entry(), ref_intrin(), ref_object(), ref_pd(), ref_stfunc(), RU_FUNC, RU_PROG, RU_SUBR, S_ACONST, S_CONST, S_DERIVED, S_EXPR, S_IDENT, S_LVALUE, S_NULL, S_TRIPLE, sem, sem_set_storage_class(), sptr, ss, SST_ACLG, SST_ALIASG, SST_ASTG, SST_ASTP, SST_CLBEGG, SST_CVALG, SST_CVALP, SST_DTYPEG, SST_DTYPEP, SST_E1G, SST_E2G, SST_E3G, SST_ERRSYMG, SST_IDG, SST_IDP, SST_LSYMG, SST_LSYMP, SST_SHAPEP, SST_SYMG, SST_SYMP, FLG::standard, stktop, sym_skip_construct(), SYMNAME, test_really_an_entry(), TY_CHAR, TY_NCHAR, and val.
Referenced by gen_cmplxpart_intr(), mkarg(), mkexpr1(), ref_intrin(), ref_pd(), rewrite_cmplxpart_rhs(), rewrite_cmplxpart_rval(), semant1(), semant2(), semant3(), and semsmp().
prtsst()
const char * prtsst (SST * stkptr)
Return the printable representation of a semantic stack entry.
Definition at line 5710 of file semutil.c.
References DT_ISCMPLX, DT_ISLOG, DT_ISREAL, DTYG, dtype, getprint(), STB::n_base, S_CONST, SCFTN_TRUE, SST_DTYPEG, SST_IDG, SST_SYMG, stb, TY_CHAR, and val.
Referenced by mklvalue().
psemant1()
void psemant1 (int rednum, SST * top)
Semantic actions - part 1.
Parameters
rednum reduction number
top top of stack after reduction
Definition at line 31 of file psemant.c.
References LHS, and SST_ASTP.
psemant2()
void psemant2 (int rednum, SST * top)
Semantic actions - part 2.
Parameters
rednum reduction number
top top of stack after reduction
Definition at line 29 of file psemant2.c.
References LHS, and SST_ASTP.
Referenced by _parser().
psemant3()
void psemant3 (int rednum, SST * top)
Semantic actions - part 3.
Parameters
rednum reduction number
top top of stack after reduction
Definition at line 29 of file psemant3.c.
References LHS, and SST_ASTP.
psemantio()
void psemantio (int rednum, SST * top)
Parameters
rednum reduction number
top top of stack after reduction
Definition at line 29 of file psemantio.c.
References LHS, and SST_ASTP.
psemsmp()
void psemsmp (int rednum, SST * top)
Parameters
rednum reduction number
top top of stack after reduction
Definition at line 28 of file psemsmp.c.
References LHS, and SST_ASTP.
ptrfunc_call()
int ptrfunc_call (SST * stktop, ITEM * list)
Definition at line 1529 of file semfunc.c.
References add_p_dealloc_item(), add_stmt(), add_typroc(), SEM::alloc_std, allocatable_member(), ARG_AST, ARG_STK, argt, ARGT_ARG, SEM::arrfn, assert, assn(), ast, astb, byvalue_ref_arg(), SEM::call_std, carg, chk_arguments(), chkarg(), CNULL, count, count_actuals(), count_formal_args(), dt, DTY, DTYG, dtype_with_shape(), error(), errwarn(), FALSE, find_byval_ref(), fix_proc_pointer_call(), FREE, gbl, gen_allocatable_result(), gen_array_result(), gen_char_result(), gen_finalized_result(), gen_pointer_result(), get_all_descriptors(), get_arr_temp(), get_byval(), get_next_sym(), get_static_descriptor(), i, ASTB::i0, SCN::id, inc_dummy_param(), init_byval(), init_derived_type(), is_array_dtype(), is_iso_cloc(), is_iso_cptr(), is_procedure_ptr(), ITEM_END, itemp, list, make_keyword_str(), memsym_of_ast(), mk_argt(), mk_func_node(), mk_id(), mk_member(), mkarg(), mkshape(), SCN::name, need_tmp_retval(), new_ast(), NULL, OP_BYVAL, OP_REF, OP_VAL, PASS_BYVAL, pass_char_no_len(), proc_arginfo(), ASTB::ptr0, ref_entry(), SEM::return_value, S_DERIVED, S_EXPR, S_IDENT, S_KEYWORD, S_LABEL, S_LVALUE, S_SCONST, S_TRIPLE, SEM::sc, scn, sem, sem_tempify(), set_descriptor_sc(), SEM::sptr, SST_ASTG, SST_ASTP, SST_CVALG, SST_CVLENP, SST_DTYPEP, SST_ERRSYMP, SST_IDG, SST_IDP, SST_LSYMG, SST_SHAPEP, SST_SYMG, STD_PREV, stktop, SYMNAME, void(), and XBIT.
Referenced by mkvarref().
ptrsubr_call()
void ptrsubr_call (SST * stktop, ITEM * list)
Definition at line 3844 of file semfunc.c.
References ARG_AST, ARG_STK, argt, ARGT_ARG, assert, ast, astb, aux, byvalue_ref_arg(), carg, chk_arguments(), chkarg(), CNULL, count, count_actuals(), count_formal_args(), DTY, error(), fix_proc_pointer_call(), flg, FREE, gbl, i, ASTB::i0, SCN::id, inc_dummy_param(), init_byval(), is_iso_cloc(), is_iso_cptr(), is_procedure_ptr(), ITEM_END, itemp, list, AUX::list, make_keyword_str(), mk_argt(), mk_func_node(), mk_id(), mkarg(), SCN::name, NULL, OP_REF, pass_char_no_len(), proc_arginfo(), ASTB::ptr0, rewrite_cptr_references(), S_DERIVED, S_IDENT, S_KEYWORD, S_LVALUE, S_SCONST, scn, sptr, SST_ASTG, SST_ASTP, SST_CVALG, SST_IDG, SST_LSYMG, SST_SYMG, stktop, SYMNAME, void(), FLG::xref, and xrefput().
Referenced by semant3().
ref_intrin()
int ref_intrin (SST * stktop, ITEM * list)
Handle Generic and Intrinsic function calls.
Definition at line 4158 of file semfunc.c.
References A_OPTYPEP, AD_ADJARR, AD_DEFER, AD_DPTR, AD_NOBOUNDS, ADD_NUMDIM, add_stmt(), and64(), AOP_AND, AOP_MAX, AOP_MIN, AOP_OR, AOP_XOR, ARG_AST, ARG_STK, argt, ARGT_ARG, assert, ast, bits_in(), chktyp(), cmp64(), cmp_mod_scope(), cngcon(), cngtyp(), CNULL, const_fold(), CONVAL2G, count, STB::dbl0, STB::dblhalf, STB::dblm0, ddt(), DDTG, SEM::dinit_data, div64(), DT_CMPLX, DT_DBLE, DT_DCMPLX, STB::dt_int, DT_INT, STB::dt_log, DT_LOG, DT_PTR, STB::dt_real, DTY, DTYG, dup_array_dtype(), error(), FALSE, findByNameStypeScope(), STB::firstusym, fix_term(), FLANG_FALLTHROUGH, STB::flt0, STB::flthalf, STB::fltm0, gbl, GBL_CURRFUNC, gen_init_intrin_call(), gen_newer_intrin(), generic_func(), get_arr_temp(), GET_CVAL_ARG, GET_DBLE, get_iso_ptrtype(), get_kwd_args(), GET_QUAD, get_shape_arr_temp(), get_temp(), get_temp_dtype(), getcon(), getstring(), GREALG, i, STB::i0, ILMG, IN_MODULE, intast_sym, interr(), is_sst_const(), ITEM_END, STB::k0, kanji_char(), KWDARGSTR, list, mk_argt(), mk_cval(), mk_cval1(), mk_func_node(), mk_id(), mkarg(), mkexpr(), mkident(), mklvalue(), mkRteRtnNm(), mkvarref(), SEM::mpaccatomic, mul64(), STB::n_base, neg64(), newsym(), xyyz::next, NOSYM, not64(), NULL, OP_ADD, OP_CMP, OP_SUB, or64(), STB::quad0, rank_of_ast(), res, SEM::rmw_op, RTE_amodulov, RTE_dmodulov, RTE_i8modulov, RTE_imodulov, RTE_max, RTE_min, RTE_modulov, RTE_qmodulov, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_TRIPLE, sc_local_passbyvalue(), SCFTN_FALSE, SCFTN_TRUE, sem, set_kind_result(), SHD_NDIM, size_of(), sptr, SST_ASTG, SST_ASTP, SST_CVALP, SST_CVLENP, SST_DTYPEG, SST_DTYPEP, SST_ERRSYMP, SST_IDG, SST_IDP, SST_ISNONDECC, SST_SHAPEG, SST_SHAPEP, SST_SYMG, SST_SYMP, stb, xyyz::stkp, stktop, string_length(), sub64(), sym_mkfunc_nodesc(), SYMNAME, xyyz::t, tempify(), tmp, TRUE, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, STB::user, void(), XBIT, xdabsv(), xdble(), xdcmp(), xdmul(), xdneg(), xfabsv(), xfadd(), xfcmp(), xfneg(), XFR_ARGAST, xfsub(), xor64(), and xqabsv().
Referenced by gen_reduction(), generic_func(), and mkvarref().
ref_pd()
int ref_pd (SST * stktop, ITEM * list)
Handle calls to Predeclared functions.
Parameters
stktop function to call
list arguments to pass to function
Definition at line 5653 of file semfunc.c.
References _adjustl(), _adjustr(), _e74_cnt, _e74_kwd, _e74_l, _e74_pos, _e74_sym, _e74_u, _index(), _len_trim(), _repeat(), _scan(), _selected_char_kind(), _trim(), _verify(), A_OPTYPEG, A_OPTYPEP, AC_ACONST, AD_DEFER, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_NUMDIM, AD_NUMELM, AD_UPAST, AD_UPBD, add64(), add_arg(), ADD_LWAST, ADD_NUMDIM, ADD_NUMELM, add_shape_rank(), add_shape_spec(), add_stmt(), ALIGN, alignment(), any_pointer_source(), ARG_AST, ARG_STK, SEM::argpos, ARGS_NUMBER, argt, ARGT_ARG, SEM::arrdim, ASD_NDIM, ASD_SUBS, assumshp, ast, _acl::ast, ast_intr(), ast_is_sym(), astb, atoxd(), aux, baseptr, begin_call(), bits_in(), BITS_PER_BYTE, ASTB::bnd, SEM::bounds, C90_EPSILON, C90_TINY, casttyp(), check_dim_error(), check_member(), chkshape(), chktyp(), FLG::cmdline, cmp64(), cngcon(), cngtyp(), CNULL, conform_shape(), const_fold(), construct_acl_from_ast(), CONVAL2G, convert_int(), count, STB::dbl0, STB::dblhalf, DDTG, dim, SEM::dinit_data, SEM::dinit_error, dont_issue_assumedsize_error, STB::dt_cmplx, DT_CMPLX, DT_DBLE, DT_FLOAT, AUX::dt_iarray, STB::dt_int, DT_INT, DT_ISCMPLX_ARR, DT_ISINT, DT_ISINT_ARR, DT_ISLOG, DT_ISLOG_ARR, DT_ISNUMERIC, DT_ISNUMERIC_ARR, DT_ISREAL, DT_ISREAL_ARR, STB::dt_log, DT_LOG, DT_PTR, STB::dt_real, DT_REAL, SEM::dtemps, DTY, DTYG, ASTB::dtype, dtype_with_shape(), dup_array_dtype(), e, e74_arg(), E74_ARG, e74_cnt(), E74_CNT, elem_size_of_ast(), EPSILON_BIT96_127, eq_dtype(), eq_dtype2(), ERR170, error(), errsev(), eval_init_expr(), evl_kwd_args(), extent_of_shape(), FALSE, find_pointer_target(), find_pointer_variable(), fix_term(), FLANG_FALLTHROUGH, flg, STB::flt0, STB::flthalf, gbl, gen_call_class_obj_size(), gen_init_intrin_call(), gen_set_type(), GET_ACL, get_arr_temp(), get_array_dtype(), get_ch_temp(), get_int_cval(), get_isz_cval(), get_kwd_args(), get_len_parm_by_number(), get_member_descriptor(), get_sst_cval(), get_static_descriptor(), get_static_type_descriptor(), get_temp(), get_type(), get_type_descr_arg(), get_version_string(), getccsym(), getcctmp_sc(), getcon(), getMergeSym(), getstring(), getsymbol(), i, STB::i0, ASTB::i0, ASTB::i1, _acl::id, if(), increase_shape(), INSIDE_STRUCT, intast_sym, SEM::interface, interr(), _acl::is_const, is_iso_c_funptr(), is_iso_cptr(), is_procedure_ptr(), is_sst_const(), is_varref(), ISZ_T, ITEM_END, kind_of(), KWDARGSTR, lbound_of_shape(), len, list, MAX_ARGS_NUMBER, MAX_EXP_OF_QMANTISSA, memsym_of_ast(), MIN_ARGS_NUMBER, MIN_QUAD_VALUE_BIT96_127, mk_argt(), mk_arrdsc(), mk_assn_stmt(), mk_binop(), mk_bnd_int(), mk_cnst(), mk_coercion_func(), mk_convert(), mk_cval(), mk_cval1(), mk_extent(), mk_func_node(), mk_id(), mk_isz_cval(), mk_member(), mk_shape(), mk_stmt(), mk_subscr(), mk_substr(), mk_unop(), mkarg(), mkexpr(), mkRteRtnNm(), mkshape(), mkvarref(), MMAX_MANTI_BIT0_31, MMAX_MANTI_BIT32_63, MMAX_MANTI_BIT64_95, MMAX_MANTI_BIT96_127, STB::n_base, name, need_alloc_ch_temp(), neg64(), newsym(), xyyz::next, _acl::next, nsubs, NULL, ASTB::one, OP_ADD, OP_CMP, OP_DIV, OP_GE, OP_MUL, OP_SUB, OP_VAL, pdtype, ASTB::ptr0, STB::quad0, STB::quadhalf, QVM4_SIZE, rank, rank_of_ast(), reduc_shape(), refsym(), res, RTE_cmd_arg_cnt, RTE_expon, RTE_expond, RTE_exponq, RTE_extends_type_of, RTE_frac, RTE_fracd, RTE_fracq, RTE_hypot, RTE_hypotd, RTE_hypotq, RTE_ilen, RTE_indexa, RTE_is_iostat_end, RTE_is_iostat_eor, RTE_lb, RTE_lb1, RTE_lb2, RTE_lb4, RTE_lb8, RTE_lba, RTE_lba1, RTE_lba2, RTE_lba4, RTE_lba8, RTE_lbaz, RTE_lbaz1, RTE_lbaz2, RTE_lbaz4, RTE_lbaz8, RTE_lbound1Dsc, RTE_lbound2Dsc, RTE_lbound4Dsc, RTE_lbound8Dsc, RTE_lbounda1Dsc, RTE_lbounda2Dsc, RTE_lbounda4Dsc, RTE_lbounda8Dsc, RTE_lboundaDsc, RTE_lboundaz1Dsc, RTE_lboundaz2Dsc, RTE_lboundaz4Dsc, RTE_lboundaz8Dsc, RTE_lboundazDsc, RTE_lboundDsc, RTE_lena, RTE_nearest, RTE_nearestd, RTE_nearestq, RTE_nrepeat, RTE_nscan, RTE_number_of_processors, RTE_nverify, RTE_present, RTE_present_ptr, RTE_presentc, RTE_processors_rank, RTE_repeata, RTE_rrspacing, RTE_rrspacingd, RTE_rrspacingq, RTE_same_type_as, RTE_scale, RTE_scaled, RTE_scaleq, RTE_scana, RTE_sel_char_kinda, RTE_sel_int_kind, RTE_sel_real_kind, RTE_setexp, RTE_setexpd, RTE_setexpq, RTE_shape, RTE_shape1, RTE_shape2, RTE_shape4, RTE_shape8, RTE_shapeDsc, RTE_size, RTE_sizeDsc, RTE_spacing, RTE_spacingd, RTE_spacingq, RTE_ub, RTE_ub1, RTE_ub2, RTE_ub4, RTE_ub8, RTE_uba, RTE_uba1, RTE_uba2, RTE_uba4, RTE_uba8, RTE_ubaz, RTE_ubaz1, RTE_ubaz2, RTE_ubaz4, RTE_ubaz8, RTE_ubound1Dsc, RTE_ubound2Dsc, RTE_ubound4Dsc, RTE_ubound8Dsc, RTE_ubounda1Dsc, RTE_ubounda2Dsc, RTE_ubounda4Dsc, RTE_ubounda8Dsc, RTE_uboundaDsc, RTE_uboundaz1Dsc, RTE_uboundaz2Dsc, RTE_uboundaz4Dsc, RTE_uboundaz8Dsc, RTE_uboundazDsc, RTE_uboundDsc, RTE_verifya, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_TRIPLE, SEM::sc, SCFTN_FALSE, select_kind(), sem, set_kind_result(), set_shape_result(), SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, shf64(), size, size_ast(), size_ast_of(), size_of(), size_of_ast(), sptr, src, SST_ACLG, SST_ASTG, SST_ASTP, SST_CVALG, SST_CVALP, SST_CVLENP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_ISNONDECC, SST_SHAPEG, SST_SHAPEP, SST_SYMG, SST_SYMP, FLG::standard, stb, std, STD_PREV, xyyz::stkp, stktop, string_length(), strlen(), _acl::subc, sym_mkfunc(), sym_mkfunc_nodesc(), sym_mkfunc_nodesc_expst(), sym_mknproc(), sym_of_ast(), SYMNAME, xyyz::t, t1, t2, target_kind(), tmp, TRUE, TY_BINT, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TYPELESS, _acl::u1, ubound_of_shape(), STB::user, ushf64(), val, void(), SEM::which_pass, XBIT, xfadd(), xfcmp(), XFR_ARGAST, xfsub(), xor64(), zero, and ASTB::zero.
Referenced by generic_func(), mkexpr1(), and mkvarref().
ref_stfunc()
int ref_stfunc (SST * stktop, ITEM * args)
Definition at line 276 of file semfunc2.c.
References _arginfo::actual, add_stmt(), _sfuse::args, args, SFDSC::args, asn_sfuse(), ast, ast_replace(), ast_rewrite(), ast_traverse(), ast_unvisit(), ast_visit(), chktyp(), CNULL, dbg_print_ast(), DBGBIT, _sfuse::dsc, _arginfo::dtype, arginfo::dtype, dump_ast_tree(), end_sfuse, error(), _arginfo::formal, gbl, get_getitem_p(), get_temp(), getitem(), SCN::id, SEM::in_stfunc, ITEM_END, itemp, l_sfuse, mk_assn_stmt(), mk_id(), mkexpr(), SCN::name, new_node(), _arginfo::next, _sfuse::next, arginfo::next, _sfuse::node, NULL, _arginfo::refd, S_EXPR, S_KEYWORD, S_STAR, S_TRIPLE, scn, sem, set_internref_stfunc(), SFDSCG, sptr, SST_ASTG, SST_ASTP, SST_CVALG, SST_DTYPEP, SST_E3G, SST_IDG, SST_IDP, SST_SHAPEP, SST_SYMG, stktop, SYMNAME, tmp, TRUE, and void().
Referenced by mkvarref().
resolve_defined_io()
int resolve_defined_io (int read_or_write, SST * stktop, ITEM * list)
Parameters
read_or_write 0 specifies read, 1 specifies write
stktop SST we're processing.
list argument list for read/write
Returns
= -1 : error (resolves to struct constructor -- should never happen)
= 0  : error or no I/O subroutine
> 0  : sptr of the 'specific' defined I/O subroutine
Definition at line 1837 of file semgnr.c.
References error(), gbl, getsymbol(), i, list, NOSYM, resolve_generic(), resolved_to_self, silent_error_mode, stktop, and SYMNAME.
Referenced by nml_emit_desc(), and semantio().
sem_tempify()
int sem_tempify (SST * stkptr)
Allocate a temporary, assign it the value, and return the assignment ast.
Definition at line 8244 of file semutil2.c.
Referenced by check_etmp(), func_call2(), gen_and_assoc_tmp_ptr(), precompute_args(), ptrfunc_call(), semant3(), semantio(), and subr_call2().
semant1()
void semant1 (int rednum, SST * top)
Semantic actions - part 1.
Parameters
rednum reduction number
top top of stack after reduction
IN_MODULE
IN_MODULE
Definition at line 782 of file semant.c.
References _INF_CLEN, INTERF::abstract, AC_AST, AC_SCONST, SEM::ac_std_range, AC_VMSSTRUCT, AC_VMSUNION, SEM::accl, SEM::action_type, AD_ADJARR, AD_ASSUMSHP, AD_ASSUMSZ, AD_DEFER, AD_DPTR, AD_LWAST, AD_LWBD, AD_NUMDIM, AD_NUMELM, AD_PTR, AD_UPAST, AD_UPBD, ad_val_of(), add_auto_finalize(), ADD_DEFER, ADD_NOBOUNDS, add_overload(), add_param(), add_stmt(), add_submodule_use(), add_symitem(), add_type_param_initialize(), add_use_rename(), add_use_stmt(), SEM::alloc_std, dec_attr_t::altname, SEM::apply, apply_use_stmts(), SEM::array_const_level, SEM::arrdim, assert, ast, xyyz::ast, _acl::ast, SEM::ast, ast_implicit(), ast_isparam(), ast_to_comment(), astb, SEM::atomic, ATOMIC_CAPTURE, ASTB::atypes, SEM::autoloc, aux, BCOPY, begin_contains(), begin_module(), begin_submodule(), bind_attr, bindingNameRequiresOverloading(), SEM::blksymnum, block_local_sym(), SEM::block_scope, ASTB::bnd, SEM::bounds, buf, build_typedef_init_tree(), ch_substring(), check_defined_io(), check_duplicate(), check_end_subprogram(), check_generic(), check_module_prefix(), check_no_scope_sptr(), chk_adjarr(), chk_arr_extent(), chk_initialization_with_kind_parm(), chk_intrinsic(), chk_kind_parm(), chk_kind_parm_expr(), chk_len_parm_expr(), chk_new_param_dt(), chk_scalartyp(), chk_struct_constructor(), chkcon(), chkcon_to_isz(), chkstruct(), chktyp(), SEM::class, clear_ident_list(), clear_subp_prefix_settings(), close_module(), SEM::close_pdo, SCOPESTACK::closed, CMEMLG, CMEMLP, CMP_IFACE_NAMES, cmp_interfaces_strict(), CMP_SUBMOD_IFACE, cngcon(), CNULL, SEM::collapse, SEM::collapse_depth, SEM::collapsed_acc_do, constant_lvalue(), construct_acl_for_sst(), construct_acl_from_ast(), construct_name, SEM::construct_sptr, SEM::contiguous, _acl::conval, CONVAL2G, CONVAL2P, convert_intrinsics_to_idents(), copy_specifics(), copy_sym_flags(), copy_type_to_entry(), count, create_func_entry(), create_func_entry_result(), create_parameterized_dt(), create_var(), cref, cuda_enabled(), CUDA_HOST, CUDAG, STB::curr_scope, SCN::currlab, d, da, DA_ALIAS, DA_B, DA_C, DA_DECORATE, DA_DLLEXPORT, DA_DLLIMPORT, DA_NOMIXEDSLA, DA_REFERENCE, DA_STDCALL, DA_VALUE, DDTG, FLG::debug, dec_attr, decl_procedure_sym(), declref(), declsym(), decr_ident_use(), def, defer_arg_chk(), defer_ident_list(), defer_pt_decl(), defer_put_kind_type_param(), SEM::deferred_dertype, SEM::deferred_func_kind, SEM::deferred_func_len, SEM::deferred_kind_len_lineno, SEM::defined_io_type, DI_ACCDO, DI_ACCKERNELSDO, DI_ACCKERNELSLOOP, DI_ACCLOOP, DI_ACCPARALLELDO, DI_ACCPARALLELLOOP, DI_ACCREGDO, DI_ACCREGLOOP, DI_ACCSERIALLOOP, DI_B, DI_BLOCK, DI_CUFKERNEL, DI_DISTPARDO, DI_DISTRIBUTE, DI_DO, DI_DO_LABEL, DI_DOACROSS, DI_DOCONCURRENT, DI_DOINFO, DI_DOWHILE, DI_ENCL_BLOCK_SCOPE, DI_EXIT_LABEL, DI_FIRST_DIRECTIVE, DI_ID, DI_ISSIMD, DI_LINENO, DI_NAME, DI_NEST, DI_PARDO, DI_PDO, DI_SELECT_TYPE, DI_SIMD, DI_TARGETSIMD, DI_TARGPARDO, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TASKLOOP, DI_TEAMS, DI_TEAMSDIST, DI_TEAMSDISTPARDO, dim, dinit(), SEM::dinit_count, SEM::dinit_data, SEM::dinit_error, dinit_struct_vals(), dinit_varref(), direct_loop_end(), SCN::directive, DLL_EXPORT, DLL_IMPORT, DLLP, do_end(), do_end_subprogram(), do_fixup_param_vars_for_derived_arrays(), do_iface(), do_iface_module(), Doend, VAR::doend, SEM::doif_base, SEM::doif_depth, Dostart, VAR::dostart, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, STB::dt_cmplx, DT_CMPLX, DT_DBLE, DT_DCMPLX, STB::dt_int, DT_INT, DT_ISINT, DT_ISWORD, STB::dt_log, DT_LOG, DT_PTR, STB::dt_real, DT_REAL, DTY, DTYG, _acl::dtype, STSK::dtype, ASTB::dtype, dummy_program(), subp_prefix_t::elemental, SEM::elp_stack, emit_bcs_ecs(), end, SEM::end_host_labno, end_module(), end_of_host, end_param(), end_subprogram_checks(), end_target(), end_teams(), ENDLINEP, enforce_denorm(), entity_attr, entry_seen, eq_dtype2(), SEM::equal_initializer, EQV, SEM::eqv_avail, SEM::eqv_base, EQV_NUMSS, SEM::eqv_size, EQV_SS, SEM::eqv_ss_avail, SEM::eqv_ss_base, SEM::eqv_ss_size, SEM::eqvlist, err307(), ERR310, ERR_Severe, errlabel(), error(), errsev(), errwarn(), et, ET_ACCESS, ET_ALLOCATABLE, ET_ASYNCHRONOUS, ET_AUTOMATIC, ET_B, ET_BIND, ET_CONSTANT, ET_CONTIGUOUS, ET_DEVICE, ET_DIMENSION, ET_EXTERNAL, ET_INTENT, ET_INTRINSIC, ET_KIND, ET_LEN, ET_MANAGED, ET_NOPASS, ET_OPTIONAL, ET_PARAMETER, ET_PASS, ET_PINNED, ET_POINTER, ET_PROTECTED, ET_SAVE, ET_SHARED, ET_STATIC, ET_TARGET, ET_TEXTURE, ET_VALUE, ET_VOLATILE, eval_init_expr(), dec_attr_t::exist, SEM::expect_acc_do, SEM::expect_cuf_do, SEM::expect_dist_do, SEM::expect_do, SEM::expect_simd_do, SEM::extends, FALSE, fe_save_state(), find_explicit_interface(), findByNameStypeScope(), first_hash(), STB::firstusym, fix_class_args(), fix_iface(), fix_iface0(), fix_proc_ptr_dummy_args(), fix_type_param_members(), fixup_function_return_type(), fixup_param_vars(), FLANG_FALLTHROUGH, flg, freearea(), FUNCLINEG, FUNCLINEP, gbl, SEM::gcvlen, SEM::gdtype, gen_deallocate_arrays(), gen_dinit(), gen_unique_func_ast(), INTERF::generic, SEM::generic_tbp, GET_ACL, get_all_descriptors(), get_construct_name(), get_descriptor_sc(), get_getitem_p(), get_highest_param_offset(), get_int_cval(), get_intrinsic_opr(), get_intrinsic_oprsym(), get_isz_cval(), get_named_stmtyp(), get_next_hash_link(), get_next_sym(), get_nml_array(), get_retval_derived_type(), get_retval_KIND_value(), get_retval_LEN_value(), get_seen_contains(), get_static_descriptor(), get_static_type_descriptor(), get_struct_members(), get_type(), get_unl_poly_sym(), get_vtoff(), getccsym(), getcon(), getitem(), getlab(), getocsym(), getstring(), getsym(), getsymbol(), getsymf(), INTERF::gnr_rutype, SEM::gty, has_finalized_component(), has_kind_parm_expr(), has_tbp_or_final(), has_type_parameter(), have_module_state(), host_present, host_state, INTERF::hpfdcl, SEM::hpfdcl, i, STB::i0, ASTB::i1, STSK::ict_beg, STSK::ict_end, SCN::id, _acl::id, VAR::id, ident_host_sub, idx, IGNORE_C, ignore_common_decl(), IGNORE_D, IGNORE_K, IGNORE_M, IGNORE_R, SEM::ignore_stmt, IGNORE_T, IGNORE_TKR_ALL, subp_prefix_t::impure, SEM::in_dim, in_entity_typdcl, SEM::in_enum, IN_MODULE, IN_MODULE_SPEC, in_save_scope(), SEM::in_struct_constr, VAR::indvar, init_allocatable_typedef_components(), init_implicit(), init_use_stmts(), inited, insert_sym(), INSIDE_STRUCT, instantiate_interface(), INTENT_DFLT, INTENT_IN, INTENT_INOUT, SEM::intent_list, INTENT_OUT, INTENTP, SEM::interf_base, SEM::interf_size, SEM::interface, internal_proc_has_ident(), interr(), SEM::is_acc, is_empty_typedef(), is_entry, is_exe_stmt, is_executable(), SCN::is_hpf, SEM::is_hpf, is_impure(), IS_INTRINSIC, is_procedure_dtype(), is_procedure_ptr(), is_procedure_ptr_dtype(), IS_TBP, is_tbp(), ISZ_T, ITEM_END, itemp, j, kind, SCOPESTACK::kind, SEM::kind_candidate, SEM::kind_type_param, STSK::last, SEM::last_std, lb, len, SEM::len_candidate, SEM::len_type_param, lenspec, LHS, link_members(), link_parents(), LOCAL_SYMNAME, VAR::lowbd, MAXDIMS, STSK::mem_access, mk_alias(), mk_arrdsc(), mk_assumed_shape(), mk_bnd_int(), mk_cnst(), mk_comstr(), mk_cval(), mk_cval1(), mk_defer_shape(), mk_id(), mk_isz_cval(), mk_set_type_call(), mk_stmt(), mk_unop(), mkexpr(), mkident(), mklvalue(), mkvarref(), mod_add_subprogram(), SEM::mod_cnt, SEM::mod_dllexport, mod_end_subprogram(), mod_end_subprogram_two(), mod_implicit(), SEM::mod_sym, mod_type(), subp_prefix_t::module, SEM::module_procedure, SEM::mpaccatomic, mscall, STB::n_base, SCN::name, name, name_of_rutype(), ndim, NEED, NEED_DOIF, negate_const(), SEM::new_param_dt, newimplicit(), newimplicitnone(), newsym(), next, xyyz::next, _acl::next, _accl::next, VAR::next, next_enum, SEM::next_unnamed_scope, SEM::nml, AUX::nml_avl, AUX::nml_base, NML_LINENO, NML_NEXT, AUX::nml_size, NML_SPTR, nomixedstrlen, SEM::none_implicit, SYMUTL::none_implicit, NOSYM, NULL, offset, SEM::ogdtype, FLG::omptarget, OP_CAT, OP_LAND, OP_LEQV, OP_LNEQV, OP_LNOT, OP_LOR, OP_ST, OP_SUB, OP_XTOI, open_module(), _accl::oper, INTERF::operator, FLG::opt, INTERF::opval, STB::ovclass, p, SEM::p_dealloc_delete, par_pop_scope(), SEM::param_assume_sz, SEM::param_defer_len, SEM::param_offset, SEM::param_struct_constr, parent, SEM::parsing_operator, parstuff_init(), SEM::pending, SEM::pgphase, PHASE_CONTAIN, PHASE_END, PHASE_END_MODULE, PHASE_EXEC, PHASE_HEADER, PHASE_IMPLICIT, PHASE_IMPORT, PHASE_INIT, PHASE_SPEC, PHASE_USE, pop_scope_level(), pop_subprogram(), pop_sym(), proc_arginfo(), SEM::proc_initializer, process_bind(), subp_prefix_t::pure, push_scope_level(), put_default_kind_type_param(), put_getitem_p(), put_length_type_param(), queue_tbp(), queue_type_param(), record_func_result(), subp_prefix_t::recursive, ref_ident(), ref_ident_inscope(), refsym(), refsym_inscope(), reinit_sym(), reloc_byvalue_parameters(), _acl::repeatc, resolve_sym_aliases(), restore_host(), restore_host_state(), restore_internal_subprograms(), restored, rewrite_acl(), RFCNTI, RHS, RU_BDATA, RU_FUNC, RU_PROG, RU_SUBR, RUNTIMEG, INTERF::rutype, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_KEYWORD, S_LVALUE, S_NULL, S_SCONST, S_STAR, S_TRIPLE, SEM::savall, save_acl(), SEM::save_aconst, save_host(), save_host_state(), save_struct_init(), save_typedef_init(), SEM::savloc, scan_include(), scan_options(), SCFTN_FALSE, SCFTN_TRUE, scn, SCOPE_BLOCK, SCOPE_INTERFACE, SEM::scope_level, SCOPE_MODULE, SCOPE_NORMAL, SEM::scope_stack, SCOPE_SUBPROGRAM, SEM::seen, SEM::seen_end_module, seen_implicit, SEM::seen_import, seen_options, seen_parameter, select_gsame(), select_kind(), SEM::select_type_seen, sem, sem_import_sym(), sem_strcmp(), semfin(), semfin_free_memory(), SEM::seq_acc_do, set_aclen(), set_char_attributes(), set_construct_name(), set_descriptor_rank(), set_descriptor_sc(), set_len_attributes(), set_preserve_descriptor(), set_proc_ptr_param_count_dtype(), set_proc_ptr_result_dtype(), set_proc_result_dtype(), setfile(), setimplicit(), setup_procedure_sym(), size_of(), size_of_array(), FLG::smp, sptr, xyyz::sptr, _acl::sptr, STSK::sptr, _accl::sptr, SCOPESTACK::sptr, SPTR_NULL, ss, SEM::ssa_area, SST_ACLG, SST_ACLP, SST_ALIASP, SST_ASTG, SST_ASTP, SST_BEGG, SST_BEGP, SST_CLBEGG, SST_CLBEGP, SST_CLENDG, SST_CLENDP, SST_COLUMNG, SST_CVALG, SST_CVALP, SST_DTYPEG, SST_DTYPEP, SST_E1G, SST_E1P, SST_E2G, SST_E2P, SST_E3G, SST_E3P, SST_ENDG, SST_ENDP, SST_ERRSYMP, SST_FIRSTG, SST_FIRSTP, SST_FLAGG, SST_FLAGP, SST_GDTYPEG, SST_GDTYPEP, SST_GTYG, SST_GTYP, SST_IDG, SST_IDP, SST_LINENOG, SST_LSYMG, SST_LSYMP, SST_NMLBEGG, SST_NMLBEGP, SST_NMLENDG, SST_NMLENDP, SST_OFFSETG, SST_OFFSETP, SST_OPTYPEG, SST_OPTYPEP, SST_PARENP, SST_RNG1G, SST_RNG2G, SST_RNG2P, SST_SHAPEP, SST_SUBSCRIPTG, SST_SUBSCRIPTP, SST_SUBSTRINGG, SST_SUBSTRINGP, SST_SYMG, SST_SYMP, SST_TMPG, SST_TMPP, SST_VLBEGG, SST_VLBEGP, SST_VLENDG, SST_VLENDP, ST_ISVAR, SEM::stag_dtype, FLG::standard, stb, std, STD_AST, STD_LABEL, STD_PREV, VAR::step, xyyz::stkp, SCN::stmtyp, string_length(), strlen(), stsk, SEM::stsk_base, SEM::stsk_depth, STSK_ENT, SEM::stsk_size, _acl::subc, SEM::submod_sym, subp_prefix, sym_in_scope(), sym_is_refd(), sym_of_ast(), symatterr(), SCOPESTACK::symavl, SYMI_NEXT, SYMI_SPTR, SYMNAME, symutl, xyyz::t, SEM::tbp_access_stmt, TBP_ADD_FINAL, TBP_ADD_IMPL, TBP_ADD_INTERFACE, TBP_ADD_SIMPLE, TBP_ADD_TO_DTYPE, SEM::tbp_arg, SEM::tbp_arg_cnt, TBP_CHECK_CHILD, TBP_CHECK_PRIVATE, TBP_CHECK_PUBLIC, TBP_CLEAR, TBP_COMPLETE_END, TBP_COMPLETE_ENDMODULE, TBP_COMPLETE_ENDTYPE, TBP_DEFERRED, TBP_IFACE, TBP_INHERIT, SEM::tbp_interface, TBP_NONOVERRIDABLE, TBP_NOPASS, TBP_PASS, TBP_PRIVATE, TBP_PUBLIC, TBP_STATUS, SEM::temps_reset, test_scope(), SEM::tkntyp, top, TRUE, TY_BINT, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, type, STSK::type, _accl::type, SEM::type_mode, SEM::type_param_candidate, SEM::type_param_sptr, VAR::u, _acl::u1, ub, uf, VAR::upbd, use_opt_atomic(), SEM::use_seen, STB::user, val, VAR::varref, void(), SEM::which_pass, XBIT, FLG::xref, and xrefput().
Referenced by _parser(), and parser().
semant2()
void semant2 (int rednum, SST * top)
semantic actions - part 2.
Parameters
rednum reduction number
top top of stack after reduction
Definition at line 51 of file semant2.c.
References a, AC_ACONST, AC_AST, AC_EXPR, AC_IDO, AC_SCONST, SEM::ac_std_range, ACL_SAVE_AREA, ALIGNG, all_default_init(), arg, SEM::array_const_level, assert, ast, xyyz::ast, ast_cnst(), ast_conval(), ast_is_sym(), astb, binop(), block_local_sym(), SEM::block_scope, ch_substring(), check_and_add_auto_dealloc(), check_derived_type_array_section(), check_etmp(), chk_constructor(), chk_scalartyp(), chk_struct_constructor(), cngtyp(), CNULL, combine_fdiv(), common_rel(), CONVAL2G, DOINFO::count, d, DDTG, declsym(), defer_pt_decl(), defined_operator(), DISTG, SEM::doif_depth, STB::dt_int, DT_INT, DT_ISBASIC, DT_ISCMPLX, DT_ISINT, DT_ISREAL, STB::dt_log, DT_LOG, DT_PTR, DTY, DTYG, dup_struct_init(), SEM::elp_stack, ERR_Severe, error(), errsev(), errwarn(), SEM::etmp_list, FALSE, find_outer_sym(), findByNameStypeScope(), fix_term(), FLANG_FALLTHROUGH, flg, form_cmplx_const(), gbl, GBL_CURRFUNC, SEM::generic_tbp, generic_tbp_has_pass_and_nopass(), GET_ACL, get_doinfo(), get_generic_member2(), get_generic_tbp_pass_or_nopass(), get_implementation(), get_int_cval(), get_kind_parm_by_name(), get_mem_sptr_by_name(), get_next_sym(), get_parameterized_dt(), get_specific_member(), get_tbp_argno(), get_temp(), get_type(), getcon(), getitem(), getsymbol(), has_private(), has_type_parameter(), i, STB::i0, ASTB::i0, ASTB::i1, SCN::id, _acl::id, SEM::in_stfunc, SEM::in_struct_constr, DOINFO::index_var, DOINFO::init_expr, init_named_array_constant(), insert_sym(), interr(), is_dovar_sptr(), is_empty_typedef(), SCN::is_hpf, IS_INTRINSIC, is_intrinsic_opr(), is_parameter_context(), is_procedure_ptr(), IS_TBP, ITEM_END, itemp, kanji_len(), lboundMask, LHS, DOINFO::limit_expr, log_negation(), mem(), memsym_of_ast(), _std_range::mid, mk_alias(), mk_binop(), mk_convert(), mk_cval(), mk_cval1(), mk_id(), mk_ido_std_range(), mk_member(), mk_paren(), mk_unop(), mkarg(), mkexpr(), mkident(), mkitem(), mklvalue(), mkmember(), mkRteRtnNm(), mkvarref(), SEM::mod_cnt, STB::n_base, SCN::name, name, negate_const(), SEM::new_param_dt, _std_range::next, _std_record::next, xyyz::next, _acl::next, no_data_components(), NOSYM, NULL, offset, OP_ADD, OP_CAT, OP_CMP, OP_DIV, OP_EQ, OP_GE, OP_GT, OP_LAND, OP_LE, OP_LOC, OP_LOR, OP_LT, OP_MUL, OP_NE, OP_REF, OP_SUB, OP_VAL, OP_XTOI, SEM::param_struct_constr, SEM::parsing_operator, pass_sym_of_ast(), SEM::pgphase, PHASE_EXEC, pop_tbp_arg(), pp, prev, proc_arginfo(), SEM::psfunc, push_tbp_arg(), put_kind_type_param(), queue_type_param(), reassoc_add(), refsym(), refsym_inscope(), _acl::repeatc, rewrite_cmplxpart_rval(), RHS, RTE_loc, RUNTIMEG, S_ACONST, S_CONST, S_DERIVED, S_EXPR, S_IDENT, S_KEYWORD, S_LABEL, S_LVALUE, S_NULL, S_REF, S_SCONST, S_STFUNC, S_TRIPLE, S_VAL, SEM::save_aconst, sc_local_passbyvalue(), SCFTN_FALSE, scn, sem, sem_set_storage_class(), sem_strcmp(), setimplicit(), _acl::size, FLG::smp, sptr, SEM::ssa_area, ssa_list(), SST_ACLG, SST_ACLP, SST_ASTG, SST_ASTP, SST_BEGG, SST_BEGP, SST_CVALG, SST_CVALP, SST_DBEGP, SST_DIMFLAGP, SST_DTYPEG, SST_DTYPEP, SST_E1G, SST_E1P, SST_E2G, SST_E2P, SST_E3G, SST_E3P, SST_ENDG, SST_ENDP, SST_ERRSYMP, SST_IDG, SST_IDP, SST_ISNONDECC, SST_LSYMG, SST_LSYMP, SST_MNOFFP, SST_OPCP, SST_OPTYPEG, SST_OPTYPEP, SST_PARENG, SST_PARENP, SST_SHAPEP, SST_SYMG, SST_SYMP, SST_TMPG, SST_TMPP, FLG::standard, _std_range::start, stb, _std_record::std, STD_LAST, STD_PREV, DOINFO::step_expr, SEM::stfunc_error, _std_record::stkp, xyyz::stkp, _acl::stkp, strideMask, string_length(), string_with_kind(), _acl::subc, sym_mkfunc_nodesc(), sym_of_ast(), sym_skip_construct(), SYMNAME, xyyz::t, SEM::tbp_arg, test_private_dtype(), TK_EQUALS, SEM::tkntyp, top, TRUE, TY_CMPLX, TY_INT8, TY_LOG8, TY_NCHAR, SEM::type_mode, _acl::u1, uboundMask, uf, unop(), SEM::use_etmps, STB::user, val, var_ref_list(), void(), and XBIT.
Referenced by _parser(), and parser().
semant3()
void semant3 (int rednum, SST * top)
semantic actions - part 3.
Parameters
rednum reduction number
top top of stack after reduction
Definition at line 72 of file semant3.c.
References _char_cmp(), _i4_cmp(), _i8_cmp(), _nchar_cmp(), A_ISLVAL, A_OPTYPEG, A_OPTYPEP, SEM::accassignc, FLG::accmp, SEM::action_type, AD_DEFER, AD_DPTR, AD_NUMDIM, add_arg(), add_astli(), add_bounds_subscripts(), add_case_range(), add_no_scope_sptr(), add_nullify_ast(), ADD_NUMDIM, add_ptr_assign(), add_stmt(), add_stmt_after(), add_stmt_before(), add_symitem(), ADD_UPAST, ADD_UPBD, alloc_error, alloc_source, SEM::allocs, SEM::apply, arg, argt, ARGT_ARG, SEM::arrdim, SEM::arrfn, assert, assign(), assign_pointer(), assn(), ast, astb, ASTLI_AST, ASTLI_HEAD, ASTLI_SPTR, ASTLI_TRIPLE, SEM::atomic, ATOMIC_CAPTURE, base, BCOPY, begin_call(), SEM::blksymnum, block_local_sym(), ASTB::bnd, SEM::bounds, BZERO, check_alloc_clauses(), check_and_add_auto_dealloc_from_ast(), check_dealloc_clauses(), check_do_term(), check_etmp(), check_member(), check_no_scope_sptr(), chk_and_rewrite_cmplxpart_assn(), chk_pointer_intent(), chk_scalar_inttyp(), chk_scalartyp(), chkcon(), chkstruct(), chktyp(), SWEL::clabel, clear_no_scope_sptr(), cmp_len_parms(), cmpat_dtype(), cngtyp(), CNULL, DOINFO::collapse, SEM::collapse, collapse_add(), collapse_begin(), SEM::collapse_depth, SEM::collapsed_acc_do, construct_association(), construct_name, SEM::construct_sptr, CONVAL2G, convert_to_block_forall(), count, create_parameterized_dt(), cuda_enabled(), SCN::currlab, d, dast(), DCLCHK, DDTG, dealloc_tmp(), declref(), declsym(), define_stfunc(), dest, DI_ACTIVE_SPTR, DI_ALLO_CHTMP, DI_ASSOC, DI_ASSOCIATIONS, DI_BEG_DEFAULT, DI_BTARGET, DI_CASE, DI_CASE_EXPR, DI_CLASS_DEFAULT_LABEL, DI_CONC_BLOCK_SYM, DI_CONC_BODY_STD, DI_CONC_COUNT, DI_CONC_ERROR_SYMS, DI_CONC_KIND, DI_CONC_LAST_SYM, DI_CONC_MASK_STD, DI_CONC_NO_DEFAULT, DI_CONC_SYMAVL, DI_CONC_SYMS, DI_CYCLE_LABEL, DI_DEFAULT_COMPLETE, DI_DEFAULT_SEEN, DI_DISTPARDO, DI_DISTRIBUTE, DI_DO, DI_DO_AST, DI_DO_LABEL, DI_DO_POPINDEX, DI_DOCONCURRENT, DI_DOINFO, DI_DOWHILE, DI_DTYPE, DI_ELSEWHERE, DI_END_DEFAULT, DI_END_SELECT_LABEL, DI_EXIT_LABEL, DI_FORALL, DI_FORALL_AST, DI_FORALL_DTYPE, DI_FORALL_LASTSTD, DI_FORALL_SYMAVL, DI_ID, DI_IDXLIST, DI_IF, DI_IFELSE, DI_IN_NEST, DI_IS_WHOLE, DI_LINENO, DI_MASKED, DI_NAME, DI_NOSCOPE_FORALL, DI_PARDO, DI_PDO, DI_PENDING, DI_SELECT_TYPE, DI_SELECT_TYPE_LIST, DI_SELECTOR, DI_SHAPEDIM, DI_SIMD, DI_SWEL_HD, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TASKLOOP, DI_TEAMSDIST, DI_TEAMSDISTPARDO, DI_TOP_LABEL, DI_TYPE_BEG, DI_WHERE, direct_loop_end(), direct_loop_enter(), DOINFO::distloop, do_begin(), do_distbegin(), do_end(), do_label, do_lastval(), do_openmp_atomics(), do_parbegin(), SEM::doconcurrent_dtype, SEM::doconcurrent_symavl, SEM::doif_base, SEM::doif_depth, dt, DT_INT, DT_ISINT, DT_ISLOG, DT_ISREAL, DT_ISWORD, STB::dt_log, DT_LOG, DT_PTR, SEM::dtemps, DTY, DTYG, type_list::dtype, ASTB::dtype, dtype_to_arg(), dup_array_dtype(), end_association(), eq_dtype(), eq_dtype2(), err307(), err_protected(), ERR_Severe, ERR_Warning, error(), errsev(), errwarn(), SEM::expect_acc_do, SEM::expect_cuf_do, SEM::expect_dist_do, SEM::expect_do, SEM::expect_simd_do, FALSE, find_non_tbp(), find_pointer_variable(), SEM::flabels, FLANG_FALLTHROUGH, flg, FREE, func, FUNCLINEP, gbl, SEM::gcvlen, SEM::gdtype, gen_alloc_dealloc(), gen_dealloc_etmps(), gen_deallocate_arrays(), gen_defer_shape(), gen_derived_arr_init(), gen_derived_type_alloc_init(), gen_finalization_for_sym(), gen_init_unl_poly_desc(), gen_logical_if_expr(), gen_type_initialize_for_sym(), generic_tbp_has_pass_and_nopass(), get_all_descriptors(), get_ast_bounds(), get_byte_len(), get_derived_type(), get_desc_gsize(), get_desc_lsize(), get_desc_rank(), get_desc_tag(), get_doinfo(), get_generic_member2(), get_generic_tbp_pass_or_nopass(), get_implementation(), get_int_cval(), get_kind(), get_member_descriptor(), get_parm_by_name(), get_parm_by_number(), get_specific_member(), get_sst_named_whole_variable(), get_static_descriptor(), get_static_type_descriptor(), get_tbp_argno(), get_type_descr_arg(), get_type_descr_arg2(), get_unl_poly_sym(), getccsym(), getcctmp_sc(), getitem(), getlab(), getstring(), getsymbol(), getsymf(), has_finalized_component(), has_poly_mbr(), has_type_parameter(), i, ASTB::i0, ASTB::i1, SCN::id, IN_OPENMP_ATOMIC, SEM::in_stfunc, SEM::index_sym_to_pop, DOINFO::index_var, init_derived_w_acl(), DOINFO::init_expr, init_exprs_idx_dependent(), insert_dup_sym(), insert_sym(), intast_sym, INTENT_IN, INTENTG, INTENTP, interr(), SEM::is_acc, is_array_dtype(), type_list::is_class, is_dovar_sptr(), IS_INTRINSIC, is_intrinsic_opr(), is_iso_cloc(), is_iso_cptr(), is_procedure_ptr(), is_protected(), IS_TBP, is_unl_poly(), is_varref(), ITEM_END, itemp, j, ASTB::k0, ASTB::k1, label, type_list::label, SEM::last_std, last_std, legal_labelvar(), LHS, lhs, DOINFO::limit_expr, LP_DISTPARDO, LP_PARDO_OTHER, MAXIDLEN, MAXRANK, mem(), memsym_of_ast(), mk_argt(), mk_assign_sptr(), mk_assn_stmt(), mk_binop(), mk_cnst(), mk_cval(), mk_cval1(), mk_func_node(), mk_id(), mk_label(), mk_set_type_call(), mk_stmt(), mk_triple(), mk_unop(), mkarg(), mkexpr(), mkexpr1(), mkident(), mklabelvar(), mklvalue(), mkmember(), mkRteRtnNm(), mkvarref(), SEM::mpaccatomic, msg(), STB::n_base, SCN::name, name, NEED, NEED_DOIF, needs_descriptor(), NEW, SEM::new_param_dt, newsym(), type_list::next, xyyz::next, SWEL::next, SEM::nodes, NOSYM, not_in_forall(), NULL, offset, ASTB::one, OP_EQ, OP_GE, OP_LAND, OP_LE, OP_LEQV, OP_LOC, OP_LOR, OP_REF, OP_ST, OP_VAL, orig_alloc_source, SEM::orph, SEM::p_dealloc, SEM::parallel, PARAMVALG, parent, pass_sym_of_ast(), SEM::pending, SEM::pgphase, PHASE_EXEC, PHASE_SPEC, pop_sym(), pop_tbp_arg(), pos, PR_ACCLOOPPRIVATE, PR_CUFLOOPPRIVATE, PR_NOSCOPE, prev, proc_arginfo(), SEM::psfunc, ASTB::ptr0c, ptrsubr_call(), push_sym(), push_tbp_arg(), put_length_type_param(), rank, rank_of_sym(), ref_based_object(), ref_entry(), refsym(), resolve_sym_aliases(), rewrite_ast_with_new_dtype(), RFCNTI, RHS, RTE_errorstop08a_char, RTE_errorstop08a_int, RTE_extends_type_of, RTE_f90io_end, RTE_init_from_desc, RTE_loc, RTE_pausea, RTE_poly_asn, RTE_poly_asn_src_intrin, RTE_same_intrin_type_as, RTE_same_type_as, RTE_stop08a, RTE_stopa, RU_FUNC, RU_SUBR, s, S_CONST, S_DERIVED, S_EXPR, S_IDENT, S_KEYWORD, S_LABEL, S_LVALUE, S_NULL, S_SCONST, S_STFUNC, S_TRIPLE, SEM::sc, SCFTN_TRUE, scn, SEM::seen, SEM::select_type_seen, sem, sem_check_scope(), sem_err105(), sem_set_storage_class(), sem_tempify(), set_assn(), set_descriptor_rank(), setimplicit(), SHD_NDIM, size_ast_of(), FLG::smp, sptr, xyyz::sptr, SPTR_NULL, src, sst, SST_ACLG, SST_ASTG, SST_ASTP, SST_BEGG, SST_BEGP, SST_COUNTG, SST_COUNTP, SST_CVALG, SST_CVALP, SST_DBEGG, SST_DBEGP, SST_DENDP, SST_DTYPEG, SST_DTYPEP, SST_E1G, SST_E1P, SST_E2G, SST_E2P, SST_E3G, SST_E3P, SST_ENDG, SST_ENDP, SST_ERRSYMG, SST_FIRSTG, SST_FIRSTP, SST_IDG, SST_IDP, SST_ISNONDECC, SST_LASTG, SST_LASTP, SST_LSYMG, SST_LSYMP, SST_MNOFFP, SST_PARENP, SST_SHAPEP, SST_SYMG, SST_SYMP, SST_TMPG, SST_TMPP, FLG::standard, start_astli(), SEM::stats, stb, std, STD_AST, STD_BLKSYM, STD_LABEL, STD_LAST, STD_NEXT, STD_PREV, DOINFO::step_expr, SEM::stfunc_error, xyyz::stkp, SCN::stmtyp, string_expr_length(), string_length(), subr_call(), subr_call2(), subscr, SEM::switch_avl, switch_base, SEM::switch_size, sym_in_sym_list(), sym_is_refd(), sym_mkfunc(), sym_mkfunc_nodesc(), sym_of_ast(), SYMI_NEXT, SYMI_SPTR, SYMNAME, t, xyyz::t, SEM::target, target_name(), SEM::task, SEM::tbp_arg, SEM::teams, test_private_dtype(), tmp, TRUE, SEM::try, TY_CHAR, TY_INT, TY_INT8, TY_ISINT, TY_ISLOG, TY_ISREAL, TY_LOG, TY_NCHAR, ty_to_lib, typed_alloc, SEM::use_etmps, use_opt_atomic(), STB::user, val, SWEL::val, validate_omp_atomic(), void(), XBIT, FLG::xref, xrefput(), and zero.
semantio()
void semantio (int rednum, SST * top)
Semantic analysis of IO statements.
Parameters
rednum reduction number
top top of stack after reduction
Definition at line 473 of file semantio.c.
References FLG::accmp, AD_ASSUMSZ, AD_DPTR, AD_NUMELM, AD_PTR, add_arg(), add_astli(), add_cgoto(), add_io_arg(), add_stmt(), add_stmt_after(), ASD_NDIM, ASD_SUBS, assert, xyyz::ast, ast, ast_ioret(), astb, ASTLI_HEAD, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, begin_call(), begin_io_call(), bitv, BITV_ADVANCE, BITV_END, BITV_EOR, BITV_ERR, BITV_IOMSG, BITV_IOSTAT, BITV_SIZE, ASTB::bnd, BT_ACCEPT, BT_BKSPACE, BT_CLOSE, BT_DECODE, BT_ENCODE, BT_ENDFILE, BT_FLUSH, BT_INQUIRE, BT_OPEN, BT_PRINT, BT_READ, BT_REWIND, BT_WAIT, BT_WRITE, BYTE_SWAPPED_IO, BYTE_SWAPPED_IO_IDX, call_dtsfmt(), check_member(), chk_expr(), chk_fmtid(), chk_iospec(), chk_scalartyp(), chk_unitid(), chk_var(), CNULL, copy_back_to_replic_sect(), copy_replic_sect_to_tmp(), count, DOINFO::count, SCN::currlab, DBGBIT, DDTG, SEM::defined_io_seen, DI_DO, DI_DOCONCURRENT, DI_IN_NEST, dim, DINIT_END, DINIT_FMT, DINIT_LOC, dinit_put(), DINIT_STR, do_begin(), do_end(), DOCHK, SEM::doif_depth, iol::doinfo, DT_INT, DT_IO_FREAD, DT_IO_FWRITE, DT_IO_UREAD, DT_IO_UWRITE, DT_ISBASIC, DT_ISINT, DT_LOG, DT_PTR, SEM::dtemps, DTY, DTYG, ASTB::dtype, dtype_has_defined_io(), dtype_to_arg(), edit_state, iol::element, UnformattedRtns::end, end_io_call(), ERR170, ERR_Severe, ERR_Warning, error(), external_io, FALSE, fasize, FED_A, FED_Aw, FED_BN, FED_Bw_m, FED_BZ, FED_COLON, FED_D, FED_DC, FED_DOLLAR, FED_DP, FED_DT, FED_Dw_d, FED_E, FED_Ee, FED_END, FED_ENw_d, FED_ESw_d, FED_Ew_d, FED_F, FED_Fw_d, FED_G, FED_G0, FED_G0_d, FED_Gw_d, FED_I, FED_Iw_m, FED_KANJI_STRING, FED_L, FED_LPAREN, FED_Lw, FED_N, FED_Nw, FED_O, FED_Ow_m, FED_P, FED_Q, FED_RC, FED_RD, FED_RN, FED_RP, FED_RPAREN, FED_RU, FED_RZ, FED_S, FED_SLASH, FED_SP, FED_SS, FED_STR, FED_T, FED_TL, FED_TR, FED_X, FED_Z, FED_Zw_m, filename_type, fix_iostat(), flg, fmt_init, fmt_inite, fmt_is_var, fmt_length, fmttyp, FT_CHARACTER, FT_ENCODED, FT_FMTSTR, FT_LIST_DIRECTED, FT_NML, FT_UNFORMATTED, functype, gbl, gen_derived_io(), gen_dtio_args(), gen_dtsfmt_args(), gen_lastval(), gen_spec_item_tmp(), get_defined_io_call(), get_derived_iolptrs(), get_doinfo(), get_fmt_array(), get_nml_array(), get_temp(), getAggrRWRtn(), getArrayRWRtn(), getBasicScalarRWRtn(), getcctmp_sc(), getitem(), getprint(), getstring(), getWriteByDtypeRtn(), i, ASTB::i0, ASTB::i1, iol::id, IE_DOBEGIN, IE_DOEND, IE_EXPR, IE_OPTDO, DOINFO::index_var, index_var, init(), init_derived_w_acl(), DOINFO::init_expr, INTENT_IN, intern, intern_array, intern_tmp, interr(), io_call, io_sc, SEM::io_stmt, IOERR, IOERR2, iolist, iomsg_check(), is_dovar_sptr(), is_iso_cptr(), is_read, is_varref(), ITEM_END, itemp, ASTB::k1, kwd_errchk(), iol::l_std, LARGE_ARRAY_IDX, last_edit, lastrpt, lb, len, LHS, DOINFO::limit_expr, list, malloc(), misc_io_checks(), mk_assn_stmt(), mk_binop(), mk_cnst(), mk_convert(), mk_cval(), mk_fake_iostat(), mk_func_node(), mk_hpfiofunc(), mk_id(), mk_iofunc(), mk_isz_cval(), mk_stmt(), mk_subscr(), mk_substr(), mk_triple(), mk_unop(), mkarg(), mkexpr(), mkRteRtnNm(), n, STB::n_base, ndim, need_descriptor_ast(), NEED_DOIF, newunit_check(), next, xyyz::next, iol::next, nml_group, NML_NEXT, NML_SPTR, no_data_components(), no_rw, nondevice_io, noparens, NULL, OP_ADD, OP_DIV, OP_LOC, OP_MUL, OP_SUB, OP_VAL, open03, print_star, PT_ACCESS, PT_ACTION, PT_ADVANCE, PT_ASYNCHRONOUS, PT_BLANK, PT_CHECK, PT_CONVERT, PT_DECIMAL, PT_DELIM, PT_DIRECT, PT_DISPOSE, PT_ENCODING, PT_END, PT_EOR, PT_ERR, PT_EXIST, PT_FILE, PT_FMT, PT_FORM, PT_FORMATTED, PT_ID, PT_IOLENGTH, PT_IOMSG, PT_IOSTAT, PT_LAST_INQUIRE_VAL, PT_LAST_INQUIRE_VALf95, PT_MAXV, PT_NAME, PT_NAMED, PT_NEWUNIT, PT_NEXTREC, PT_NML, PT_NUMBER, PT_OPENED, PT_PAD, PT_PENDING, PT_POS, PT_POSITION, PT_READ, PT_READWRITE, PT_REC, PT_RECL, PT_ROUND, PT_SEQUENTIAL, PT_SET, PT_SHARED, PT_SIGN, PT_SIZE, PT_STATUS, PT_STREAM, PT_TMPUSED, PT_UNFORMATTED, PT_UNIT, PT_VARREF, PT_WRITE, PTARG, PTNAME, ASTB::ptr0, ASTB::ptr0c, PTS, PTV, PTVARREF, PUT, put_edit(), put_ffield(), put_vlist(), refsym(), rescan, resolve_defined_io(), RHS, RTE_f90io_aux_init, RTE_f90io_backspace, RTE_f90io_begin, RTE_f90io_closea, RTE_f90io_dts_stat, RTE_f90io_encode_fmta, RTE_f90io_encode_fmtv, RTE_f90io_endfile, RTE_f90io_flush, RTE_f90io_fmtr_end, RTE_f90io_fmtr_init03a, RTE_f90io_fmtw_end, RTE_f90io_fmtw_init03a, RTE_f90io_get_newunit, RTE_f90io_inquire03_2a, RTE_f90io_inquire2003a, RTE_f90io_ldr_end, RTE_f90io_ldr_init, RTE_f90io_ldr_init03a, RTE_f90io_ldr_intern_inita, RTE_f90io_ldr_intern_inite, RTE_f90io_ldw_end, RTE_f90io_ldw_init, RTE_f90io_ldw_init03a, RTE_f90io_ldw_intern_inita, RTE_f90io_ldw_intern_inite, RTE_f90io_nmlr, RTE_f90io_nmlr_end, RTE_f90io_nmlr_init, RTE_f90io_nmlr_init03a, RTE_f90io_nmlr_intern_inita, RTE_f90io_nmlw, RTE_f90io_nmlw_end, RTE_f90io_nmlw_init, RTE_f90io_nmlw_init03a, RTE_f90io_nmlw_intern_inita, RTE_f90io_open03a, RTE_f90io_open2003a, RTE_f90io_open_asynca, RTE_f90io_open_cvta, RTE_f90io_open_sharea, RTE_f90io_print_init, RTE_f90io_rewind, RTE_f90io_src_info03a, RTE_f90io_swbackspace, RTE_f90io_unf_asynca, RTE_f90io_wait, RTE_lena, RTE_loc, RTE_nlena, rw03, rw_array(), s, S_ACONST, S_CONST, S_DERIVED, S_EXPR, S_IDENT, S_LVALUE, S_SCONST, scn, sem, sem_set_storage_class(), sem_tempify(), set_assn(), set_io_sc(), SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, size_of(), size_of_ast(), FLG::smp, sptr, ss, SST_ACLG, SST_ALIASP, SST_ASTG, SST_ASTP, SST_BEGG, SST_BEGP, SST_CVALG, SST_CVALP, SST_CVLENG, SST_CVLENP, SST_DTYPEG, SST_DTYPEP, SST_ENDG, SST_ENDP, SST_IDG, SST_IDP, SST_LENG, SST_LENP, SST_LSYMG, SST_OPTYPEG, SST_RNG1G, SST_RNG1P, SST_RNG2G, SST_RNG2P, SST_SHAPEG, SST_SHAPEP, SST_SYMG, SST_SYMP, SST_UNITG, SST_UNITP, st, FLG::standard, start_astli(), stb, std, STD_LABEL, STD_LINENO, STD_NEXT, STD_PREV, DOINFO::step_expr, xyyz::stkp, SCN::stmtyp, str, string_expr_length(), string_length(), strlen(), sym_get_scalar(), sym_is_refd(), sym_mkfunc(), sym_mkfunc_nodesc(), sym_of_ast(), SYMNAME, t, xyyz::t, TRUE, TY_CHAR, TY_INT8, TY_NCHAR, ty_to_lib, ub, unf_nm, UNIT_CHECK, unit_star, void(), and XBIT.
semsmp()
void semsmp (int rednum, SST * top)
Semantic analysis for SMP statements.
Parameters
rednum reduction number
top top of stack after reduction
Definition at line 563 of file semsmp.c.
References A_CANCELKINDP, A_STDG, SEM::accassignc, accel_pragmagen(), ACCSTRICT, ACCVERYSTRICT, SEM::action_type, add_clause(), add_pragma(), add_stmt(), any_pflsr_private, SEM::apply, apply_nodepchk(), arg, assign_cval(), ast, SEM::ast, ATOMIC_CAPTURE, ATOMIC_READ, ATOMIC_UNDEF, ATOMIC_UPDATE, ATOMIC_WRITE, begin_combine_constructs(), begin_parallel_clause(), BLK_SYM, BT_ACCDATAREG, BT_ACCENDREG, BT_ACCHOSTDATA, BT_ACCKDO, BT_ACCKERNELS, BT_ACCKLOOP, BT_ACCPARALLEL, BT_ACCPDO, BT_ACCPLOOP, BT_ACCREG, BT_ACCSCALARREG, BT_ACCSERIAL, BT_ACCSLOOP, BT_DISTRIBUTE, BT_DOACROSS, BT_PAR, BT_PARDO, BT_PARSECTS, BT_PARWORKS, BT_PDO, BT_SECTS, BT_SIMD, BT_SINGLE, BT_TARGET, BT_TASK, BT_TASKLOOP, BT_TEAMS, cancel_type(), check_barrier(), check_cancel(), check_crit(), check_targetdata(), check_valid_data_sharing(), chk_scalartyp(), chkcon_to_isz(), chktyp(), chunk, CL_ACCCOMPARE, CL_ALIGNED, CL_CHUNK, CL_COLLAPSE, CL_COPYIN, CL_COPYPRIVATE, CL_DEFAULT, CL_DEPEND, CL_DEVICE, CL_DEVICE_TYPE, CL_DIST_SCHEDULE, CL_FINAL, CL_FIRST, CL_FIRSTPRIVATE, CL_GANG, CL_GRAINSIZE, CL_HOST, CL_IF, CL_KERNEL_BLOCK, CL_KERNEL_GRID, CL_LAST, CL_LASTPRIVATE, CL_LINEAR, CL_MAP, CL_MERGEABLE, CL_MP_SCHEDTYPE, CL_NOGROUP, CL_NOWAIT, CL_NUM_TASKS, CL_NUM_TEAMS, CL_NUM_THREADS, CL_ORDERED, CL_PARALLEL, CL_PARUNROLL, CL_PGICOMPARE, CL_PRESENT, CL_PRIORITY, CL_PRIVATE, CL_PROC_BIND, CL_REDUCTION, CL_SAFELEN, CL_SCHEDULE, CL_SEQ, CL_SEQUNROLL, CL_SHARED, CL_STREAM, CL_THREAD_LIMIT, CL_UNROLL, CL_UNTIED, CL_UPDATEDEV, CL_UPDATEHOST, CL_UPDATESELF, CL_VAL, CL_VECTOR, CL_VECUNROLL, CL_WORKER, clause_errchk(), CMEMLG, CNULL, SEM::collapse, CONVAL2G, cray_pointer_check(), d, DDTG, DI_ACCDATAREG, DI_ACCDO, DI_ACCHOSTDATA, DI_ACCKERNELS, DI_ACCKERNELSDO, DI_ACCKERNELSLOOP, DI_ACCLOOP, DI_ACCPARALLEL, DI_ACCPARALLELDO, DI_ACCPARALLELLOOP, DI_ACCREG, DI_ACCREGDO, DI_ACCREGLOOP, DI_ACCSERIAL, DI_ACCSERIALLOOP, DI_ATOMIC_CAPTURE, DI_B, DI_BEGINP, DI_BPAR, DI_BTARGET, DI_BTEAMS, DI_CRITICAL, DI_CRITSYM, DI_DISTPARDO, DI_DISTRIBUTE, DI_DOACROSS, DI_DOINFO, DI_ID, DI_IN_NEST, DI_IS_ORDERED, DI_ISSIMD, DI_LASTPRIVATE, DI_LINENO, DI_MASTER, DI_ORDERED, DI_PAR, DI_PARDO, DI_PARSECTS, DI_PARWORKS, DI_PDO, DI_SCH_STATIC, DI_SECT_CNT, DI_SECT_VAR, DI_SECTS, DI_SIMD, DI_SINGLE, DI_TARGET, DI_TARGETDATA, DI_TARGETENTERDATA, DI_TARGETEXITDATA, DI_TARGETUPDATE, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TASK, DI_TASKLOOP, DI_TEAMS, DI_TEAMSDIST, DI_TEAMSDISTPARDO, DI_WORKSHARE, dirname, distchunk, do_bdistribute(), do_bteams(), do_copyprivate(), do_map(), do_schedule(), SEM::doif_depth, DT_INT, DT_ISBASIC, DT_ISINT, emit_bcs_ecs(), emit_bpar(), emit_btarget(), emit_epar(), emit_etarget(), end_parallel_clause(), end_targteams(), end_teams(), end_workshare(), enter_dir(), ERR_Severe, ERR_Warning, error(), errwarn(), SEM::expect_do, SEM::expect_simd_do, FALSE, find_outer_sym(), find_reduc_intrinsic(), flg, gbl, get_csect_pfxlen(), get_csect_sym(), get_itemp(), get_mp_bind_type(), get_stblk_uplevel_sptr(), getitem(), getlab(), SCN::id, IF_DEFAULT, IF_TARGETEXITDATA, IF_TARGETUPDATE, IF_TASK, interr(), reduc_tag::intrin, SEM::is_acc, ITEM_END, itemp, kernel_argnum, kernel_do_nest, leave_dir(), LHS, reduc_tag::list, SEM::mem_order, mk_cval(), mk_id(), mk_label(), mk_stmt(), mkvarref(), MO_SEQ_CST, MO_UNDEF, mp_create_bscope(), mp_create_escope(), mp_iftype, SEM::mpaccatomic, SCN::name, new_node(), next, xyyz::next, reduc_sym::next, reduc_tag::next, NOSYM, NULL, OMP_DEFAULT, OMP_TARGETDATA, OMP_TARGETENTERDATA, OMP_TARGETEXITDATA, OMP_TARGETUPDATE, FLG::omptarget, OP_ADD, OP_LAND, OP_LEQV, OP_LNEQV, OP_LOG, OP_LOR, OP_MUL, reduc_tag::opr, other_firstlast_check(), par_pop_scope(), par_push_scope(), PAR_SCOPE_FIRSTPRIVATE, PAR_SCOPE_NONE, PAR_SCOPE_PRIVATE, PAR_SCOPE_SHARED, SEM::parallel, parstuff_init(), SEM::pending, PR_ACCBEGINDIR, PR_ACCDATAREG, PR_ACCEL, PR_ACCELLP, PR_ACCENDDATAREG, PR_ACCENDHOSTDATA, PR_ACCENDKERNELS, PR_ACCENDPARCONSTRUCT, PR_ACCENDSERIAL, PR_ACCHOSTDATA, PR_ACCKERNELS, PR_ACCKLOOP, PR_ACCPARCONSTRUCT, PR_ACCPLOOP, PR_ACCSCALARREG, PR_ACCSERIAL, PR_ACCSLOOP, PR_ACCTKLOOP, PR_ACCTPLOOP, PR_ACCTSLOOP, PR_ENDACCEL, PR_NOSCOPE, PR_PCASTCOMPARE, reduc_sym::Private, recent_loop_clause, ref_ident(), refsym(), RHS, rsp, S_CONST, S_DERIVED, S_IDENT, S_NULL, S_TRIPLE, sched_type(), scn, SEM::scope_level, SEM::seen, sem, set_iftype(), reduc_sym::shared, size_of(), sptr, SEM::ssa_area, SST_ASTG, SST_ASTP, SST_BEGG, SST_BEGP, SST_CVALG, SST_CVALP, SST_DEVICEG, SST_DTYPEP, SST_E1G, SST_E1P, SST_E2G, SST_E2P, SST_E3G, SST_E3P, SST_ENDG, SST_ENDP, SST_IDG, SST_IDP, SST_LSYMG, SST_OPCG, SST_OPCP, SST_OPTYPEG, SST_OPTYPEP, SST_PARENP, SST_SYMG, SST_SYMP, std, strlen(), SYMNAME, SEM::target, SEM::task, SEM::teams, top, TRUE, use_opt_atomic(), void(), and XBIT.
subr_call()
void subr_call (SST * stktop, ITEM * list)
Definition at line 3746 of file semfunc.c.
References list, stktop, and subr_call2().
Referenced by ref_intrin_subr(), ref_pd_subr(), and semant3().
subr_call2()
void subr_call2 (SST * stktop, ITEM * list, int flag)
Write ILMs to call a subroutine.
Parameters
stktop function to call
list arguments to pass to function
flag set if called from a generic resolution routine
Definition at line 3256 of file semfunc.c.
References add_stmt(), ARG_AST, ARG_STK, argt, ARGT_ARG, assn(), ast, astb, aux, byvalue_ref_arg(), carg, check_arguments(), check_generic(), chkarg(), CNULL, count, count_actuals(), count_formals(), DTY, eq_dtype2(), error(), FALSE, findByNameStypeScope(), flg, FREE, gbl, gen_and_assoc_tmp_ptr(), generic_call(), generic_tbp_call(), get_byval(), get_implementation(), get_next_hash_link(), get_sym_from_sst_if_available(), get_tbp_argno(), getitem(), GSAMEG, i, ASTB::i0, SCN::id, inc_dummy_param(), init_byval(), INTENT_IN, INTENTG, IS_INTRINSIC, is_iso_cloc(), is_iso_cptr(), is_ptr_arg(), ITEM_END, itemp, SEM::last_std, list, AUX::list, make_kwd_str(), mem(), memsym_of_ast(), mk_argt(), mk_func_node(), mk_id(), mkarg(), SCN::name, name, newsym(), NOSYM, NULL, OP_REF, pass_char_no_len(), pass_sym_of_ast(), ASTB::ptr0, FLG::recursive, ref_intrin_subr(), ref_pd_subr(), replace_memsym_of_ast(), rewrite_cptr_references(), RU_SUBR, S_DERIVED, S_EXPR, S_IDENT, S_KEYWORD, S_LVALUE, S_SCONST, scn, sem, sem_tempify(), set_pass_objects(), sptr, SST_ASTG, SST_ASTP, SST_CVALG, SST_DTYPEG, SST_IDG, SST_LSYMG, SST_SYMG, SST_SYMP, stktop, strlen(), sym_of_ast(), SYMNAME, test_scope(), tk_match_arg(), void(), FLG::xref, and xrefput().
Referenced by generic_call(), is_intrinsic_opr(), semant3(), and subr_call().
tempify()
int tempify (SST * stkptr)
Allocate a temporary, assign it the value, and return the temp's base.
Definition at line 1279 of file semfunc2.c.
References add_stmt(), assign(), get_temp(), mkexpr(), mkident(), SST_DTYPEG, SST_DTYPEP, SST_LSYMP, SST_SHAPEP, SST_SYMP, and void().
Referenced by func_call2(), mkarg(), and ref_intrin().
unop()
void unop (SST * rslt, SST * operator, SST * rop)
Perform a unary operation on logical rhs.
Definition at line 5088 of file semutil.c.
References cngshape(), cngtyp(), constant_lvalue(), DDTG, DT_INT, DT_LOG, mkexpr1(), OP_ADD, OP_SUB, S_CONST, S_EXPR, S_STFUNC, SST_DTYPEP, SST_IDG, SST_IDP, SST_OPTYPEG, TY_ISLOG, TY_OF, and TYPE_OF.
Referenced by semant2().
validate_omp_atomic()
LOGICAL validate_omp_atomic (SST * l_stktop, SST * r_stktop)
Definition at line 7215 of file semsmp.c.
References SEM::action_type, ATOMIC_CAPTURE, ATOMIC_READ, ATOMIC_UPDATE, ATOMIC_WRITE, CNULL, error(), FALSE, gbl, is_valid_atomic_capture(), is_valid_atomic_read(), is_valid_atomic_update(), is_valid_atomic_write(), mkexpr1(), mklvalue(), SEM::mpaccatomic, sem, and SST_ASTG.
Referenced by semant3().
Variable Documentation
sst
SST* sst extern
Definition at line 25 of file fenddf.c.
Referenced by _parser(), acl_rewrite_asts(), and semant3().