flang: semtbp.c File Reference
semtbp.c File Reference
This file contains semantic processing routines for type bound procedures (tbps), generic tbps, derived type I/O generic tbps, and final subroutines.
#include "gbldefs.h"
#include "gramsm.h"
#include "gramtk.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "semant.h"
#include "scan.h"
#include "semstk.h"
#include "ast.h"
#include "pragma.h"
#include "rte.h"
#include "pd.h"
#include "interf.h"
#include "fdirect.h"
#include "fih.h"
Classes
struct tbp
Internal type bound procedure ADT.
Macros
#define IS_CLEAR_STALE_RECORDS_TASK(task) (task == TBP_CLEAR_STALE_RECORDS)
Macro for clearing/zeroing out stale dtypes and sptrs in tbp_queue.
#define IS_CLEAR_TBP_TASK(task) (task == TBP_CLEAR || task == TBP_CLEAR_ERROR)
Macro for tasks that clear the tbp queue.
#define IS_ADD_TBP_TASK(task)
Macro for tasks that add tbp to tbo queue.
#define IS_ADD_TBP_TO_DTYPE_TASK(task) (task == TBP_ADD_TO_DTYPE)
Macro for tasks that add tbps to their associated derived types.
#define IS_INHERIT_TBP_TASK(task) (task == TBP_INHERIT)
Macro for task that copy inherited tbps from parent type to child type.
#define IS_RESOLVE_TBP_TASK(task)
Macro for tasks that resolve tbp binding and implementation names.
#define IS_ADD_TBP_INTERFACE_TASK(task) (task == TBP_ADD_INTERFACE)
Macro for task that adds user specified interface to tbp.
#define IS_ADD_TBP_PASS_ARG_TASK(task) (task == TBP_PASS)
Macro for tasks that adds pass attribute to tbp.
#define IS_ADD_TBP_NOPASS_ARG_TASK(task) (task == TBP_NOPASS)
Macro for task that adds nopass attribute to tbp.
#define IS_ADD_NON_OVERRIDABLE_TBP_TASK(task) (task == TBP_NONOVERRIDABLE)
Macro for task that adds non_overridable attribute to tbp.
#define IS_ADD_PRIVATE_TBP_TASK(task) (task == TBP_PRIVATE)
Macro for task that adds private attribute to tbp.
#define IS_ADD_PUBLIC_TBP_TASK(task) (task == TBP_PUBLIC)
Macro for task that adds public attribute to tbp.
#define IS_TBP_STATUS_TASK(task) (task == TBP_STATUS)
Macro for task that checks for tbps in a particular derived type.
#define IS_ADD_DEFERRED_TBP_TASK(task) (task == TBP_DEFERRED)
Macro for task that adds deferred attribute to tbp.
#define IS_ADD_EXPLICIT_IFACE_TBP_TASK(task) (task == TBP_IFACE)
Macro for task that adds explicit external interface for tbp's implementation.
#define IS_ADD_FINAL_SUB_TASK(task) (task == TBP_ADD_FINAL)
Macro for task that adds a final subroutine to tbp queue.
Typedefs
typedef struct tbp TBP
typedef enum tbpAccessTypes tbpAccess
Enum used to hold private or public accessibility of tbp.
Enumerations
enum tbpAccessTypes { DEFAULT_ACCESS_TBP = 0 , PRIVATE_ACCESS_TBP , PUBLIC_ACCESS_TBP }
Enum used to hold private or public accessibility of tbp.
Functions
static int initTbp (tbpTask task)
Initialize/clear entries in type bound procedure (tbp) queue, tbpQueue.
static int clearStaleRecs (tbpTask task)
Clear records in type bound procedure (tbp) queue that have a stale dtype field. Zero out any other stale dtype/sptr fields.
static int enqueueTbp (int sptr, int bind, int offset, int dtype, tbpTask task)
Add type bound procedure (tbp) to tbp queue, tbpQueue.
static int addToDtype (int dtype, tbpTask task)
Add type bound procedures (tbps) to derived type.
static int inheritTbps (int dtype, tbpTask task)
"Copy" inherited type bound procedures (tbps) from parent type to child type.
static int resolveTbps (int dtype, tbpTask task)
Resolve the implementation and binding name symbols associated with each type bound procedure (tbp) in a derived type. Also the bulk of the semantic checking on the tbps is performed here.
static int semCheckTbp (tbpTask task, TBP *curr, char *impName)
Called by resolveTbps(). This function will check the validity of the type bound procedure (tbp), curr, including its arguments and interface.
static int initFinalSub (tbpTask task, TBP *curr)
Called by resolveTbps(). This function initializes a final subroutine.
static int resolveImp (int dtype, tbpTask task, TBP *curr, char *impName)
Called by resolveTbps(). This function resolves the field curr->impName to the "in scope" implementation symbol table pointer.
static int resolveBind (tbpTask task, TBP *curr, char *impName)
Called by resolveTbps(). This function resolves the field curr->bindName to the "in scope" binding name symbol table pointer.
static int addTbpInterface (int sptr, int dtype, tbpTask task)
Add interface-name if user specified it with the type bound procedure (tbp) definition.
static int addPassArg (int sptr, int bind, int dtype, tbpTask task)
Add pass argument for type bound procedure (tbp) binding name, bind, if it has not already been added.
static int addNoPassArg (int bind, int dtype, tbpTask task)
Set nopass attribute on type bound procedure (tbp).
static int addNonOverridableTbp (int bind, int dtype, tbpTask task)
Set non_overridable attribute on type bound procedure (tbp).
static int addPrivateAttribute (int bind, int dtype, tbpTask task)
Add specified private attribute to type bound procedure (tbp) definition.
static int addPublicAttribute (int bind, int dtype, tbpTask task)
Add specified public attribute to type bound procedure (tbp) definition.
static int dtypeHasTbp (int dtype, tbpTask task)
Returns true if there exists a type bound procedure (tbp) for a specified derived type, dtype.
static int addDeferredTbp (int bind, int dtype, tbpTask task)
Add deferred attribute to type bound procedure (tbp).
static int addExplicitIface (int sptr, tbpTask task)
Called when type bound procedure (tbp) definition uses an explicit interface of an external routine for its implementation.
static int addFinalSubroutine (SPTR sptr, DTYPE dtype, tbpTask task)
Add final subroutine to type bound procedure queue, tbpQueue.
static void fixupImp (int next_sptr, TBP *curr)
Set curr->impSptr field to correct implementation symbol.
static int resolvePass (tbpTask task, TBP *curr, char *impName)
Resolve the PASS object/argument of a type bound procedure (tbp).
static int resolveGeneric (tbpTask task, TBP *curr)
Resolve generic symbols for generic type bound procedures.
static void completeTbp (TBP *curr)
Called by resolveTbps() to perform some final processing of the type bound procedure (tbp).
static int requiresOverloading (int sym, TBP *curr, tbpTask task)
Called by resolveImp() to determine if the implementation symbol is overloading another symbol that may be in scope through module use association.
static void checkForStaleTbpEntries (void)
issues an internal compiler warning if it finds any stale dtype/sptr entries in the type bound procedure (tbp) queue.
int queue_tbp (int sptr, int bind, int offset, int dtype, tbpTask task)
Main function for processing type bound procedures (tbps), generic type bound procedures, derived type I/O generic type bound procedures, and final subroutines.
Variables
static TBP * tbpQueue = NULL
The internal tbp queue.
Detailed Description
This file contains semantic processing routines for type bound procedures (tbps), generic tbps, derived type I/O generic tbps, and final subroutines.
Definition in file semtbp.c.
Macro Definition Documentation
IS_ADD_DEFERRED_TBP_TASK
#define IS_ADD_DEFERRED_TBP_TASK (task) (task == TBP_DEFERRED)
Macro for task that adds deferred attribute to tbp.
Definition at line 81 of file semtbp.c.
IS_ADD_EXPLICIT_IFACE_TBP_TASK
#define IS_ADD_EXPLICIT_IFACE_TBP_TASK (task) (task == TBP_IFACE)
Macro for task that adds explicit external interface for tbp's implementation.
Definition at line 85 of file semtbp.c.
IS_ADD_FINAL_SUB_TASK
#define IS_ADD_FINAL_SUB_TASK (task) (task == TBP_ADD_FINAL)
Macro for task that adds a final subroutine to tbp queue.
Definition at line 88 of file semtbp.c.
IS_ADD_NON_OVERRIDABLE_TBP_TASK
#define IS_ADD_NON_OVERRIDABLE_TBP_TASK (task) (task == TBP_NONOVERRIDABLE)
Macro for task that adds non_overridable attribute to tbp.
Definition at line 69 of file semtbp.c.
IS_ADD_PRIVATE_TBP_TASK
#define IS_ADD_PRIVATE_TBP_TASK (task) (task == TBP_PRIVATE)
Macro for task that adds private attribute to tbp.
Definition at line 72 of file semtbp.c.
IS_ADD_PUBLIC_TBP_TASK
#define IS_ADD_PUBLIC_TBP_TASK (task) (task == TBP_PUBLIC)
Macro for task that adds public attribute to tbp.
Definition at line 75 of file semtbp.c.
IS_ADD_TBP_INTERFACE_TASK
#define IS_ADD_TBP_INTERFACE_TASK (task) (task == TBP_ADD_INTERFACE)
Macro for task that adds user specified interface to tbp.
Definition at line 60 of file semtbp.c.
IS_ADD_TBP_NOPASS_ARG_TASK
#define IS_ADD_TBP_NOPASS_ARG_TASK (task) (task == TBP_NOPASS)
Macro for task that adds nopass attribute to tbp.
Definition at line 66 of file semtbp.c.
IS_ADD_TBP_PASS_ARG_TASK
#define IS_ADD_TBP_PASS_ARG_TASK (task) (task == TBP_PASS)
Macro for tasks that adds pass attribute to tbp.
Definition at line 63 of file semtbp.c.
IS_ADD_TBP_TASK
#define IS_ADD_TBP_TASK (task)
Value:
  (task == TBP_ADD_SIMPLE || task == TBP_ADD_IMPL ||       \
   task == TBP_CHECK_CHILD || task == TBP_CHECK_PRIVATE || \
   task == TBP_CHECK_PUBLIC)
Macro for tasks that add tbp to tbo queue.
Definition at line 41 of file semtbp.c.
IS_ADD_TBP_TO_DTYPE_TASK
#define IS_ADD_TBP_TO_DTYPE_TASK (task) (task == TBP_ADD_TO_DTYPE)
Macro for tasks that add tbps to their associated derived types.
Definition at line 47 of file semtbp.c.
IS_CLEAR_STALE_RECORDS_TASK
#define IS_CLEAR_STALE_RECORDS_TASK (task) (task == TBP_CLEAR_STALE_RECORDS)
Macro for clearing/zeroing out stale dtypes and sptrs in tbp_queue.
Definition at line 35 of file semtbp.c.
IS_CLEAR_TBP_TASK
#define IS_CLEAR_TBP_TASK (task) (task == TBP_CLEAR || task == TBP_CLEAR_ERROR)
Macro for tasks that clear the tbp queue.
Definition at line 38 of file semtbp.c.
IS_INHERIT_TBP_TASK
#define IS_INHERIT_TBP_TASK (task) (task == TBP_INHERIT)
Macro for task that copy inherited tbps from parent type to child type.
Definition at line 51 of file semtbp.c.
IS_RESOLVE_TBP_TASK
#define IS_RESOLVE_TBP_TASK (task)
Value:
  (task == TBP_COMPLETE_ENDMODULE || task == TBP_COMPLETE_FIN || \
   task == TBP_COMPLETE_END || task == TBP_COMPLETE_ENDTYPE ||   \
   task == TBP_COMPLETE_GENERIC || task == TBP_FORCE_RESOLVE)
Macro for tasks that resolve tbp binding and implementation names.
Definition at line 54 of file semtbp.c.
IS_TBP_STATUS_TASK
#define IS_TBP_STATUS_TASK (task) (task == TBP_STATUS)
Macro for task that checks for tbps in a particular derived type.
Definition at line 78 of file semtbp.c.
Typedef Documentation
TBP
typedef struct tbp TBP
Definition at line 92 of file semtbp.c.
tbpAccess
typedef enum tbpAccessTypes tbpAccess
Enum used to hold private or public accessibility of tbp.
Enumeration Type Documentation
tbpAccessTypes
enum tbpAccessTypes
Enum used to hold private or public accessibility of tbp.
Enumerator
DEFAULT_ACCESS_TBP
no access attribute specified
PRIVATE_ACCESS_TBP
private access attribute specified
PUBLIC_ACCESS_TBP
public access attribute specified
Definition at line 95 of file semtbp.c.
Function Documentation
addDeferredTbp()
static int addDeferredTbp (int bind, int dtype, tbpTask task) static
Add deferred attribute to type bound procedure (tbp).
Parameters
bind is the symbol table pointer of a binding name
dtype is the derived type record that we're currently processing
task is the task that invoked this function
Returns
integer > 0 if successful, else 0
Definition at line 2389 of file semtbp.c.
References tbp::bindName, tbp::dtype, IS_ADD_DEFERRED_TBP_TASK, tbp::isDeferred, tbp::next, strlen(), SYMNAME, task, and tbpQueue.
Referenced by queue_tbp().
addExplicitIface()
static int addExplicitIface (int sptr, tbpTask task) static
Called when type bound procedure (tbp) definition uses an explicit interface of an external routine for its implementation.
Parameters
sptr is the symbol table pointer of the implementation name
task is the task that invoked this function
Returns
integer > 0 if successful, else 0
Definition at line 2421 of file semtbp.c.
References tbp::impName, IS_ADD_EXPLICIT_IFACE_TBP_TASK, tbp::isExtern, tbp::next, sptr, SYMNAME, task, and tbpQueue.
Referenced by queue_tbp().
addFinalSubroutine()
static int addFinalSubroutine (SPTR sptr, DTYPE dtype, tbpTask task) static
Add final subroutine to type bound procedure queue, tbpQueue.
Parameters
sptr is the symbol table pointer of the implementation name
dtype is the derived type record that we're currently processing
task is the task that invoked this function
Returns
integer > 0 if successful, else 0.
Definition at line 2446 of file semtbp.c.
References tbp::bindName, BZERO, tbp::dtype, error(), gbl, get_struct_tag_sptr(), tbp::impName, IS_ADD_FINAL_SUB_TASK, tbp::isFinal, tbp::isIface, len, tbp::lineno, name, NEW, tbp::next, sptr, strlen(), SYMNAME, task, and tbpQueue.
Referenced by queue_tbp().
addNonOverridableTbp()
static int addNonOverridableTbp (int bind, int dtype, tbpTask task) static
Set non_overridable attribute on type bound procedure (tbp).
Parameters
bind is the symbol table pointer of the binding name
dtype is the derived type record that we're currently processing
task is the task that invoked this function
Returns
integer > 0 if successful, else 0
Definition at line 2502 of file semtbp.c.
References tbp::bindName, tbp::dtype, IS_ADD_NON_OVERRIDABLE_TBP_TASK, tbp::isNonOver, tbp::next, strlen(), SYMNAME, task, and tbpQueue.
Referenced by queue_tbp().
addNoPassArg()
static int addNoPassArg (int bind, int dtype, tbpTask task) static
Set nopass attribute on type bound procedure (tbp).
Parameters
bind is the symbol table pointer of the binding name
dtype is the derived type record that we're currently processing
task is the task that invoked this function
Returns
integer > 0 if successful, else 0
Definition at line 2534 of file semtbp.c.
References tbp::bindName, tbp::dtype, tbp::hasNopass, IS_ADD_TBP_NOPASS_ARG_TASK, tbp::next, strlen(), SYMNAME, task, and tbpQueue.
Referenced by queue_tbp().
addPassArg()
static int addPassArg (int sptr, int bind, int dtype, tbpTask task) static
Add pass argument for type bound procedure (tbp) binding name, bind, if it has not already been added.
Parameters
sptr is the symbol table pointer for the implementation name
bind is the symbol table pointer for the binding name
dtype is the derived type record that we're currently processing
task is the task that invokved this function
Returns
integer > 0 if successful, else 0
Definition at line 2271 of file semtbp.c.
References tbp::bindName, tbp::dtype, IS_ADD_TBP_PASS_ARG_TASK, tbp::next, tbp::pass, sptr, strlen(), SYMNAME, task, and tbpQueue.
Referenced by queue_tbp().
addPrivateAttribute()
static int addPrivateAttribute (int bind, int dtype, tbpTask task) static
Add specified private attribute to type bound procedure (tbp) definition.
Parameters
bind is the symbol table pointer of the binding name
dtype is the derived type record that we're currently processing
task is the task that invoked this function
Returns
integer > 0 if successful, else 0
Definition at line 2304 of file semtbp.c.
References tbp::access, tbp::bindName, tbp::dtype, IS_ADD_PRIVATE_TBP_TASK, tbp::next, PRIVATE_ACCESS_TBP, strlen(), SYMNAME, task, and tbpQueue.
Referenced by queue_tbp().
addPublicAttribute()
static int addPublicAttribute (int bind, int dtype, tbpTask task) static
Add specified public attribute to type bound procedure (tbp) definition.
Parameters
bind is the symbol table pointer of the binding name
dtype is the derived type record that we're currently processing
task is the task that invoked this function
Returns
integer > 0 if successful, else 0
Definition at line 2336 of file semtbp.c.
References tbp::access, tbp::bindName, tbp::dtype, IS_ADD_PUBLIC_TBP_TASK, tbp::next, PUBLIC_ACCESS_TBP, strlen(), SYMNAME, task, and tbpQueue.
Referenced by queue_tbp().
addTbpInterface()
static int addTbpInterface (int sptr, int dtype, tbpTask task) static
Add interface-name if user specified it with the type bound procedure (tbp) definition.
For example,
procedure (interface-name), deferred :: binding-name
Parameters
sptr is the symbol table pointer of implementation name
dtype is the derived type record that we're currently processing
task is the task that invoked this function
Returns
integer > 0 if successful, else 0
Definition at line 2571 of file semtbp.c.
References BZERO, tbp::dtype, gbl, tbp::impName, IS_ADD_TBP_INTERFACE_TASK, tbp::isIface, len, tbp::lineno, name, NEW, tbp::next, sptr, strlen(), SYMNAME, task, and tbpQueue.
Referenced by queue_tbp().
addToDtype()
static int addToDtype (int dtype, tbpTask task) static
Add type bound procedures (tbps) to derived type.
Note that what gets added to the derived type here is a stub. The symbol table pointers for the binding name, implementation name, interface, etc. are resolved later in the function resolveTbps().
Parameters
dtype is the derived type record that we're currently processing
task is the task that invoked this function.
Returns
integer > 0 if successful, else 0
Definition at line 1868 of file semtbp.c.
References tbp::access, tbp::bindName, BZERO, STB::curr_scope, DTY, tbp::dtype, gbl, tbp::genericType, getsymf(), tbp::impSptr, IS_ADD_TBP_TO_DTYPE_TASK, tbp::isFinal, tbp::isIface, tbp::isInherited, tbp::lineno, mem(), tbp::memSptr, NEW, tbp::next, NOSYM, PRIVATE_ACCESS_TBP, PUBLIC_ACCESS_TBP, sem, stb, SYMNAME, task, SEM::tbp_access_stmt, tbpQueue, tmp, and SEM::which_pass.
Referenced by queue_tbp().
checkForStaleTbpEntries()
static void checkForStaleTbpEntries (void) static
issues an internal compiler warning if it finds any stale dtype/sptr entries in the type bound procedure (tbp) queue.
Definition at line 2607 of file semtbp.c.
References assert, tbp::bindSptr, STB::dt, tbp::dtPass, tbp::dtype, ERR_Warning, FALSE, tbp::impSptr, tbp::memSptr, tbp::next, stb, and tbpQueue.
Referenced by clearStaleRecs().
clearStaleRecs()
static int clearStaleRecs (tbpTask task) static
Clear records in type bound procedure (tbp) queue that have a stale dtype field. Zero out any other stale dtype/sptr fields.
Parameters
task is the task that invoked this function
Returns
number of records/fields cleared
Definition at line 2211 of file semtbp.c.
References tbp::bindSptr, checkForStaleTbpEntries(), STB::dt, tbp::dtPass, tbp::dtype, FREE, tbp::impSptr, IS_CLEAR_STALE_RECORDS_TASK, tbp::memSptr, tbp::next, prev, stb, task, and tbpQueue.
Referenced by queue_tbp().
completeTbp()
static void completeTbp (TBP * curr) static
Called by resolveTbps() to perform some final processing of the type bound procedure (tbp).
Parameters
curr is a pointer to the current tbp record.
Definition at line 1518 of file semtbp.c.
References tbp::bindSptr, tbp::dtPass, tbp::dtype, get_implementation(), get_struct_tag_sptr(), tbp::isInherited, tbp::isOverloaded, mem(), and tbp::memSptr.
Referenced by resolveTbps().
dtypeHasTbp()
static int dtypeHasTbp (int dtype, tbpTask task) static
Returns true if there exists a type bound procedure (tbp) for a specified derived type, dtype.
Parameters
dtype is the derived type record that we're currently processing
task is the task that invokved this function
Returns
integer > 0 if successful, else 0
Definition at line 2367 of file semtbp.c.
References tbp::dtype, IS_TBP_STATUS_TASK, tbp::next, task, and tbpQueue.
Referenced by queue_tbp().
enqueueTbp()
static int enqueueTbp (int sptr, int bind, int offset, int dtype, tbpTask task) static
Add type bound procedure (tbp) to tbp queue, tbpQueue.
If task is TBP_ADD_SIMPLE, then we are adding a tbp that was declared as "procedure tbp".
If task is TBP_ADD_IMPL, then we are adding a tbp that was declared as "bind => implementation".
If task is TBP_CHECK_CHILD, then we are also checking the validity of a child tbp.
If task is TBP_CHECK_PUBLIC, then we are also checking the validity of a public declared tbp.
If task is TBP_CHECK_PRIVATE, then we are also checking the validity of a private declared tbp.
Parameters
sptr is the symbol table pointer of the implementation name
bind is the symbol table pointer of the binding name
offset is tbp's offset in dtype's "virtual function table"
dtype is the derived type record that we're currently processing
task is the task that invoked this function
Returns
integer > 0 if successful, else 0
Definition at line 2002 of file semtbp.c.
References tbp::access, tbp::bindName, BZERO, SEM::defined_io_type, tbp::dtPass, tbp::dtype, error(), gbl, SEM::generic_tbp, tbp::genericType, getitem(), tbp::impName, IS_ADD_TBP_TASK, tbp::isDefinedIO, tbp::isIface, len, tbp::lineno, name, NEW, tbp::next, offset, tbp::offset, prev, PRIVATE_ACCESS_TBP, PUBLIC_ACCESS_TBP, sem, sptr, strlen(), SYMNAME, task, TBP_ADD_IMPL, TBP_CHECK_CHILD, TBP_CHECK_PRIVATE, TBP_CHECK_PUBLIC, and tbpQueue.
Referenced by queue_tbp().
fixupImp()
static void fixupImp (int next_sptr, TBP * curr) static
Set curr->impSptr field to correct implementation symbol.
This function is called by resolvePass() when we determine that we have the wrong implementation symbol for the curr->impSptr field. This can happen when curr->impSptr was initially set to a forward reference, ST_ENTRY, instead of a ST_PROC.
Parameters
next_sptr is the correct symbol table pointer for the implementation
curr is the current type bound procedure record that we're processing.
Definition at line 868 of file semtbp.c.
References getCref(), getMscall(), tbp::impSptr, IN_MODULE, tbp::isExtern, tbp::isIface, and tbp::memSptr.
Referenced by resolvePass().
inheritTbps()
static int inheritTbps (int dtype, tbpTask task) static
"Copy" inherited type bound procedures (tbps) from parent type to child type.
Parameters
dtype is the derived type record that we're currently processing
task is the task that invokved this function
Returns
integer > 0 if successful, else 0
Definition at line 1643 of file semtbp.c.
References tbp::access, tbp::bindName, tbp::bindSptr, buf, BZERO, CNULL, DEFAULT_ACCESS_TBP, tbp::dtPass, DTY, tbp::dtype, error(), findByNameStypeScope(), gbl, tbp::genericType, get_struct_tag_sptr(), getitem(), tbp::hasNopass, tbp::impName, tbp::impSptr, IS_INHERIT_TBP_TASK, tbp::isDeferred, tbp::isFinal, tbp::isIface, tbp::isInherited, tbp::isNonOver, tbp::isOverloaded, len, tbp::lineno, name, NEW, tbp::next, NOSYM, tbp::offset, parent, tbp::pass, PRIVATE_ACCESS_TBP, PUBLIC_ACCESS_TBP, sem, strlen(), SYMNAME, task, SEM::tbp_access_stmt, and tbpQueue.
Referenced by queue_tbp().
initFinalSub()
static int initFinalSub (tbpTask task, TBP * curr) static
Called by resolveTbps(). This function initializes a final subroutine.
We also perform some intial semantic checking.
Parameters
task is the task that invoked this function
curr is tbp that we're currently processing
Returns
integer -1 if we processed a final subroutine, otherwise 0.
Definition at line 288 of file semtbp.c.
References array_element_dtype(), aux, STB::curr_scope, AUX::dpdsc_base, SEM::dtemps, DTY, tbp::dtype, ERR_Fatal, error(), gbl, get_static_descriptor(), get_struct_tag_sptr(), getccsym_sc(), getsymbol(), tbp::impName, tbp::impSptr, INTENT_OUT, INTENTG, is_array_dtype(), tbp::isFinal, tbp::lineno, mem(), tbp::memSptr, SEM::mod_cnt, NOSYM, proc_arginfo(), rank, rank_of_sym(), sem, set_descriptor_class(), set_final_descriptor(), stb, SYMNAME, task, TBP_COMPLETE_ENDMODULE, TBP_COMPLETE_FIN, and SEM::which_pass.
Referenced by resolveTbps().
initTbp()
static int initTbp (tbpTask task) static
Initialize/clear entries in type bound procedure (tbp) queue, tbpQueue.
Parameters
task is the task that invoked this function
Returns
an integer > 0 if successful, else 0
Definition at line 2173 of file semtbp.c.
References tbp::bindName, FREE, tbp::genericType, tbp::impName, IS_CLEAR_TBP_TASK, tbp::isFinal, tbp::next, NULL, sem, task, TBP_CLEAR, tbpQueue, and SEM::which_pass.
Referenced by queue_tbp().
queue_tbp()
int queue_tbp (int sptr, int bind, int offset, int dtype, tbpTask task)
Main function for processing type bound procedures (tbps), generic type bound procedures, derived type I/O generic type bound procedures, and final subroutines.
Parameters
sptr is the symbol table pointer of the implementation name of tbp
bind symbol table pointer to the binding name of tbp
offset is the integer offset of tbp in its "virtual function table"
dtype is the enclosing dtype of the type bound procedure
task is the type of processing to be performed (see tbpTask definition in semant.h)
Definition at line 173 of file semtbp.c.
References addDeferredTbp(), addExplicitIface(), addFinalSubroutine(), addNonOverridableTbp(), addNoPassArg(), addPassArg(), addPrivateAttribute(), addPublicAttribute(), addTbpInterface(), addToDtype(), clearStaleRecs(), dtypeHasTbp(), enqueueTbp(), inheritTbps(), initTbp(), IS_ADD_DEFERRED_TBP_TASK, IS_ADD_EXPLICIT_IFACE_TBP_TASK, IS_ADD_FINAL_SUB_TASK, IS_ADD_NON_OVERRIDABLE_TBP_TASK, IS_ADD_PRIVATE_TBP_TASK, IS_ADD_PUBLIC_TBP_TASK, IS_ADD_TBP_INTERFACE_TASK, IS_ADD_TBP_NOPASS_ARG_TASK, IS_ADD_TBP_PASS_ARG_TASK, IS_ADD_TBP_TASK, IS_ADD_TBP_TO_DTYPE_TASK, IS_CLEAR_STALE_RECORDS_TASK, IS_CLEAR_TBP_TASK, IS_INHERIT_TBP_TASK, IS_RESOLVE_TBP_TASK, IS_TBP_STATUS_TASK, offset, resolveTbps(), sptr, and task.
Referenced by check_defined_io2(), defined_operator(), do_end_subprogram(), find_best_generic(), generic_tbp_call(), generic_tbp_func(), get_implementation(), is_intrinsic_opr(), reinit(), resolveGeneric(), resolveTbps(), semant1(), and semfin().
requiresOverloading()
static int requiresOverloading (int sym, TBP * curr, tbpTask task) static
Called by resolveImp() to determine if the implementation symbol is overloading another symbol that may be in scope through module use association.
Special case for overloading symbol. Execute when we hit a "contains" in a module and symbol is overloadeded or its stype is not set to a ST_PROC, ST_ENTRY, or ST_MODPROC and therefore, needs to be overloaded.
Parameters
sym is symbol table pointer of the implementation name that we are checking.
curr is a pointer to the type bound procedure (tbp) record that we are checking.
task is the TBP task that called this function.
Returns
integer > 0 if sym requires overloading, else 0.
Definition at line 1260 of file semtbp.c.
References IN_MODULE, tbp::isDeferred, tbp::isOverloaded, task, and TBP_COMPLETE_FIN.
Referenced by resolveImp().
resolveBind()
static int resolveBind (tbpTask task, TBP * curr, char * impName) static
Called by resolveTbps(). This function resolves the field curr->bindName to the "in scope" binding name symbol table pointer.
In a type bound procedure (tbp) expression, we have the following:
procedure :: foo => bar
In this case, foo is the binding name and bar is the implementation name.
Parameters
task is the task that invoked this function
curr is the tbp record that we're currently processing
impName is a C string holding the tbp's implementation name that is suitable for printing in an error message
Returns
integer 0 upon success, > 0 if an error occurred, and < 0 if we ignore this tbp.
Definition at line 1167 of file semtbp.c.
References tbp::access, tbp::bindName, tbp::bindSptr, STB::curr_scope, declsym(), tbp::dtype, dup_sym(), eq_dtype2(), FALSE, tbp::genericType, getsymbol(), insert_sym(), tbp::isInherited, tbp::isNonOver, tbp::memSptr, NULL, tbp::offset, PRIVATE_ACCESS_TBP, PUBLIC_ACCESS_TBP, same_ancestor(), stb, sym_in_scope(), task, and TBP_COMPLETE_GENERIC.
Referenced by resolveTbps().
resolveGeneric()
static int resolveGeneric (tbpTask task, TBP * curr) static
Resolve generic symbols for generic type bound procedures.
We also add specific type bound procedures to generic sets in this function.
Parameters
task is the task that called this function.
curr is the current tbp record.
Returns
0 if successful, > 0 if an error occurred.
Definition at line 1036 of file semtbp.c.
References add_overload(), tbp::bindName, tbp::bindSptr, buf, CNULL, SEM::defined_io_type, tbp::dtype, error(), gbl, tbp::genericType, get_implementation(), get_specific_member(), get_struct_tag_sptr(), getitem(), tbp::hasNopass, tbp::impSptr, tbp::isDefinedIO, tbp::isInherited, len, mem(), tbp::memSptr, name, tbp::next, NULL, queue_tbp(), sem, strlen(), SYMNAME, task, TBP_COMPLETE_END, TBP_COMPLETE_ENDMODULE, TBP_COMPLETE_GENERIC, TBP_FORCE_RESOLVE, tbpQueue, and SEM::which_pass.
Referenced by resolveTbps().
resolveImp()
static int resolveImp (int dtype, tbpTask task, TBP * curr, char * impName) static
Called by resolveTbps(). This function resolves the field curr->impName to the "in scope" implementation symbol table pointer.
That is, we are resolving the implementation name to the symbol table pointer of the implementation procedure.
In a tbp expression, we have the following:
procedure :: foo => bar
In this case, foo is the binding name and bar is the implementation name.
Parameters
dtype is the derived type record that we're currently processing
task is the task that invoked this routine
curr is the tbp record that we're currently processing
impName is a C string holding the tbp's implementation name that's suitable for printing in an error message
Returns
integer 0 upon success or > 0 if an error occurred.
Definition at line 1301 of file semtbp.c.
References tbp::access, SEM::accl, aux, tbp::bindSptr, STB::curr_scope, declsym(), declsym_newscope(), DEFAULT_ACCESS_TBP, AUX::dpdsc_base, tbp::dtPass, tbp::dtype, error(), FALSE, findByNameStypeScope(), gbl, tbp::genericType, get_implementation(), getCref(), getMscall(), getsymbol(), tbp::hasNopass, i, tbp::impName, tbp::impSptr, IN_MODULE, insert_sym(), IS_PROC, tbp::isDeferred, tbp::isExtern, tbp::isFwdRef, tbp::isIface, tbp::isInherited, tbp::memSptr, _accl::next, NOSYM, NULL, STB::ovclass, tbp::pass, proc_arginfo(), refocsym(), requiresOverloading(), scope, sem, _accl::sptr, stb, SYMNAME, task, TBP_COMPLETE_FIN, TBP_COMPLETE_GENERIC, _accl::type, and SEM::which_pass.
Referenced by resolveTbps().
resolvePass()
static int resolvePass (tbpTask task, TBP * curr, char * impName) static
Resolve the PASS object/argument of a type bound procedure (tbp).
This includes the default and explicit pass objects. We also set NOPASS on tbp derived type component of nopass was specified.
Parameters
task is the task that called this function.
curr is the current tbp record.
impName is a C string that represents the implementation-name that we are processing.
Returns
0 if successful, > 0 if an error occurred.
Definition at line 911 of file semtbp.c.
References arg, aux, buf, AUX::dpdsc_base, DTY, tbp::dtype, eq_dtype(), error(), fixupImp(), gbl, tbp::genericType, get_next_hash_link(), get_struct_tag_sptr(), getitem(), tbp::hasNopass, tbp::impName, tbp::impSptr, IN_MODULE, tbp::isInherited, len, tbp::memSptr, NULL, tbp::pass, proc_arginfo(), strlen(), SYMNAME, task, TBP_COMPLETE_END, and TBP_COMPLETE_ENDMODULE.
Referenced by resolveTbps().
resolveTbps()
static int resolveTbps (int dtype, tbpTask task) static
Resolve the implementation and binding name symbols associated with each type bound procedure (tbp) in a derived type. Also the bulk of the semantic checking on the tbps is performed here.
In a tbp expression, we have the following:
procedure :: foo => bar
In this case, foo is the binding name and bar is the implementation name.
Parameters
dtype is the derived type record that we're currently processing
task is the task that invoked this function
Returns
integer > 0 if successful, else 0.
Definition at line 1560 of file semtbp.c.
References completeTbp(), STB::curr_scope, tbp::dtype, get_static_type_descriptor(), get_struct_tag_sptr(), getitem(), i, tbp::impName, IN_MODULE, initFinalSub(), IS_RESOLVE_TBP_TASK, name, tbp::next, queue_tbp(), resolveBind(), resolveGeneric(), resolveImp(), resolvePass(), semCheckTbp(), stb, strlen(), task, TBP_CLEAR_ERROR, TBP_COMPLETE_ENDMODULE, TBP_COMPLETE_ENDTYPE, TBP_COMPLETE_GENERIC, TBP_FORCE_RESOLVE, tbpQueue, and XBIT.
Referenced by queue_tbp().
semCheckTbp()
static int semCheckTbp (tbpTask task, TBP * curr, char * impName) static
Called by resolveTbps(). This function will check the validity of the type bound procedure (tbp), curr, including its arguments and interface.
Parameters
task is the task that invoked this function
curr is tbp that we're currently processing
impName is a C string that contains the implementation name suitable for printing in an error message
Returns
integer 0 if no errors found, > 0 if error found, -1 if this function chose to not check the tbp for various reasons (see comments in function code).
Definition at line 406 of file semtbp.c.
References aux, tbp::bindSptr, buf, cmp_interfaces_strict(), AUX::dpdsc_base, DTY, tbp::dtype, eq_dtype2(), error(), find_dummy_position(), findByNameStypeScope(), gbl, tbp::genericType, get_implementation(), get_next_hash_link(), get_specific_member(), get_struct_tag_sptr(), getitem(), tbp::hasNopass, i, IGNORE_IFACE_NAMES, tbp::impName, tbp::impSptr, IN_MODULE, INTENT_IN, INTENT_INOUT, INTENT_OUT, INTENTG, tbp::isInherited, len, mem(), tbp::memSptr, NULL, parent, tbp::pass, proc_arginfo(), sem, strlen(), SYMNAME, task, TBP_COMPLETE_END, TBP_COMPLETE_ENDMODULE, TBP_COMPLETE_ENDTYPE, TBP_FORCE_RESOLVE, TY_CHAR, and SEM::which_pass.
Referenced by resolveTbps().
Variable Documentation
tbpQueue
TBP* tbpQueue = NULL static
The internal tbp queue.
Definition at line 159 of file semtbp.c.
Referenced by addDeferredTbp(), addExplicitIface(), addFinalSubroutine(), addNonOverridableTbp(), addNoPassArg(), addPassArg(), addPrivateAttribute(), addPublicAttribute(), addTbpInterface(), addToDtype(), checkForStaleTbpEntries(), clearStaleRecs(), dtypeHasTbp(), enqueueTbp(), inheritTbps(), initTbp(), resolveGeneric(), and resolveTbps().