flang: semutil0.h File Reference
semutil0.h File Reference
#include "gbldefs.h"
#include "symtab.h"
Macros
#define AREA_SIZE 16
Functions
bool sem_eq_str (int con, const char *pattern)
...
INT cngcon (INT oldval, DTYPE oldtyp, DTYPE newtyp)
...
int getrval (int ilmptr)
...
void semant_init (void)
...
void semant_reinit (void)
...
Macro Definition Documentation
AREA_SIZE
#define AREA_SIZE 16
Definition at line 14 of file semutil0.h.
Function Documentation
cngcon()
INT cngcon (INT oldval, DTYPE oldtyp, DTYPE newtyp)
...
...
Issue error messages only for impossible conversions. Return constant value for 32-bit constants, or symbol table pointer. Can only be used for scalar constants.
Remember: Non-decimal constants are octal, hexadecimal, or hollerith constants which are represented by DT_WORD, DT_DWORD and DT_HOLL. Non-decimal constants 'assume' data types rather than go thru a conversion. Hollerith constants have a data type of DT_HOLL in the semantic stack, however, the symbol table entry they point to has a data type of DT_CHAR.
Hollerith constants are always treated as scalars while octal or hexadecimal constants can be promoted to vectors.
Definition at line 379 of file semutil0.cpp.
References AREA_SIZE, BCOPY, CONVAL2G, cp, STB::dbl0, DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_INT, DTY, FLG::endian, ERR170, errinfo(), errsev(), errwarn(), FLANG_FALLTHROUGH, flg, get_acon(), get_type(), getcon(), getitem(), getstring(), hex2char(), hex2nchar(), holtonum(), INT64_2_ISZ, is_empty_typedef(), ISZ_T, kanji_len(), kanji_prefix(), local_sname(), STB::n_base, num, STB::quad0, result, SERROR, sptr, SPTR_NULL, FLG::standard, stb, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_ISINT, TY_ISSCALAR, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, uf, xdble(), xdfix(), xdfix64(), xdfloat(), xdflt64(), xdtoq(), xffloat(), xfix(), xfix64(), xflt64(), xftoq(), xqfix(), xqfix64(), xqfloat(), xqflt64(), xqtod(), xqtof(), and xsngl().
getrval()
int getrval (int ilmptr)
...
...
Definition at line 94 of file semutil0.cpp.
References getrval(), and ILMA.
Referenced by getrval(), and getstr().
sem_eq_str()
bool sem_eq_str (int con, const char * pattern)
...
...
...
Returns
true if fortran character constant is equal to pattern (pattern is always uppercase)
Definition at line 8210 of file semutil2.c.
References len, STB::n_base, size_of(), and stb.
semant_init()
void semant_init (void)
...
...
Definition at line 82 of file semutil0.cpp.
semant_reinit()
void semant_reinit (void)
...
...
Definition at line 39 of file semutil0.cpp.
Referenced by semant_init().