flang: semutil.c File Reference
semutil.c File Reference
Utility routines used by Semantic Analyzer.
#include "gbldefs.h"
#include "global.h"
#include "gramtk.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "semant.h"
#include "scan.h"
#include "dinit.h"
#include "semstk.h"
#include "machar.h"
#include "ast.h"
#include "rte.h"
#include "pd.h"
#include "fdirect.h"
#include "go.h"
#include "rtlRtns.h"
Macros
#define RTE_C
#define ERR170(s1, s2) error(170, 2, gbl.lineno, s1, s2)
#define UFCHAR error(0, 3, gbl.lineno, "character array expressions not supported", CNULL)
#define TYPE_OF(s) (SST_DTYPEG(s))
#define TY_OF(s) (DTYG(TYPE_OF(s)))
#define PT_OF(s) (DDTG(TYPE_OF(s))) /* pointer to data type */
#define ERRMSG_BUFFSIZE 200
#define ARITH(o) (o == OP_ADD || o == OP_SUB || o == OP_MUL || o == OP_DIV || o == OP_XTOI)
#define OK_LTYP(t)
#define OP_OR -1
#define OP_AND -2
#define OP_EQV -3
#define OP_XOR -4
Functions
static int ref_array (SST *, ITEM *)
static INT clog_to_log (INT)
static int mkunion (int, int, int)
static INT const_xtoi (INT, int, int)
static INT _xtok (INT, BIGINT64, int)
static void error83 (int)
static LOGICAL subst_lhs_arrfn (int, int, int)
static LOGICAL subst_lhs_pointer (int, int, int)
static LOGICAL not_in_arrfn (int, int)
static int find_pointer_variable_assign (int, int)
static int inline_contig_check (int src, SPTR src_sptr, SPTR sdsc, int std)
Generate contiguity check test inline (experimental)
static bool is_selector (SPTR sptr)
Checks whether a symbol is used in a select type or associate construct as a selector.
void constant_lvalue (SST *stkptr)
If stkptr is an LVALUE that has a constant value, replace it with the constant value.
INT chkcon (SST *stkptr, int dtype, LOGICAL warnflg)
Check that the indicated semantic stack entry is a constant of the specified type and convert constant to new type if possible.
ISZ_T chkcon_to_isz (SST *stkptr, LOGICAL warnflg)
Check that the indicated semantic stack entry is a constant of any integer type.
INT chktyp (SST *stkptr, int dtype, LOGICAL warnflg)
Convert expression pointed to by stkptr from its current data type to data type dtype.
INT chk_scalartyp (SST *stkptr, int dtype, LOGICAL warnflg)
Same as chktyp() with the restriction that the expression must be a scalar (i.e., not an array/vector form).
INT chk_scalar_inttyp (SST *stkptr, int dtype, const char *msg)
Same as chktyp() with the restriction that the expression must be a scalar (i.e., not an array/vector form) and integer (i.e., not logical).
INT chk_arr_extent (SST *stkptr, const char *msg)
Restrict the expression to be suitable for an array extent.
INT chksubscr (SST *stkptr, int sptr)
Convert expression pointed to by stkptr from its current data type to a data type consistent with subscripting.
int casttyp (SST *old, int newcast)
Cast a given semantic entry into a desired type. No type conversion is done.
static void cngtyp2 (SST *old, DTYPE newtyp, bool allowPolyExpr)
Convert expression pointed-to by old to the data type newtyp.
void cngtyp (SST *old, DTYPE newtyp)
Convert expression pointed-to by old to the data type newtyp.
void cngshape (SST *old, SST *new)
LOGICAL chkshape (SST *old, SST *new, LOGICAL promote)
Semantically check an operand (old) for array conformance with operand new. If the operand is a scalar, change the shape of the operand to conform with the expected shape. If the operand is an array, check for conformance.
int chklog (SST *stkptr)
void mkident (SST *stkptr)
int mkexpr (SST *stkptr)
int mkexpr1 (SST *stkptr)
Given a semantic stack entry, write ILM's for the expression represented by the stack entry if they have not already been written.
int mkexpr2 (SST *stkptr)
Same as mkexpr1(), but the expression is the target of a pointer assignment. Must handle ST_PROCs as identifiers; otherwise, just call mkexpr1().
void mklogint4 (SST *stkptr)
Convert all sizes of logicals and integers to 4 byte versions.
int mklvalue (SST *stkptr, int stmt_type)
Check for legal variable to be assigned to.
void link_parents (STSK *stsk, int sptr)
Link parents for type extension by adding parent as a member to the type.
int check_parent (int sptr1, int sptr2)
Check parents of type extension for duplicate symbols.
void link_members (STSK *stsk, int sptr)
Link together members of a structure.
static int test_really_an_entry (int sptr)
int mkvarref (SST *stktop, ITEM *list)
Make a var ref of the form: <var primary> ([<ssa list>])
void resolve_fwd_refs ()
Resolve forward references: try to find the declaration symbol and replace the reference symbol with it.
bool in_save_scope (SPTR sptr)
LOGICAL is_sst_const (SST *stk)
Check if a stack entry represents a constant or an expression evaluated to a constant.
INT get_sst_cval (SST *stkp)
Get the SST_CVAL-like value for a semantic stack entry already determined to be a constant (i.e., is_sst_const() is true).
LOGICAL is_varref (SST *stk)
Check if a stack entry is a legal variable reference.
int ref_object (int sptr)
Access the address of the object (sym).
LOGICAL ast_isparam (int ast)
int chksubstr (SST *stktop, ITEM *item)
Check that substring specifier is correct, write SUBS (substring) ILM and return pointer to it.
void ch_substring (SST *stktop, SST *lb_sp, SST *ub_sp)
Substring of a character constant.
int fix_term (SST *stktop, int sptr)
Repair a bad term in an expression.
int assign_array_w_forall (int dest_ast, int src_ast, int dtype, int ndim)
Called when array of derived type = scalar derived type, but the scalar derived type has an array component.
void check_derived_type_array_section (int ast)
Give error message for reference like a(:)b(:)
int assign (SST *newtop, SST *stktop)
Assign stktop to newtop.
static void update_proc_ptr_dtype_from_interface (int func_sptr)
static LOGICAL valid_assign_pointer_types (SST *newtop, SST *stktop)
static int assign_intrinsic_to_pointer (SST *newtop, SST *stktop)
int assign_pointer (SST *newtop, SST *stktop)
int gen_poly_element_arg (int ast, SPTR sptr, int std)
Generates a call to a poly_element_addr runtime routine that computes the address of a polymorphic array element.
int add_ptr_assign (int dest, int src, int std)
void gen_contig_check (int dest, int src, SPTR sdsc, int srcLine, bool cs, int std)
Generate a contiguous pointer check on a pointer assignment when applicable.
int mk_component_ast (int leaf, int parent, int src_ast)
int chk_pointer_intent (int pvar, int refast)
int any_pointer_source (int ast)
int chk_pointer_target (int pvar, int source)
LOGICAL is_protected (int sptr)
void err_protected (int sptr, const char *context)
void set_assn (int sptr)
...
static void cast_to_typeless (SST *op, int typ)
void chkopnds (SST *lop, SST *operator, SST *rop)
Make two operands conform in a binary operation. The sequence of events is crucial to correct interpretation of expression.
void unop (SST *rslt, SST *operator, SST *rop)
Perform a unary operation on logical rhs.
void binop (SST *rslt, SST *lop, SST *operator, SST *rop)
Perform a binary operation on rhs1 and rhs2. They both conform in data type and shape.
int mod_type (int dtype, int ty, int kind, int len, int propagated, int sptr)
Return a new data type based on the rules of applying a length specifier to an existing base data type (i.e. LOGICAL*1) passed in as a TY_ value.
const char * prtsst (SST *stkptr)
Return the printable representation of a semantic stack entry.
int getbase (int ast)
Dereference an ast to determine the base, i.e. its symbol pointer.
int do_index_addr (int sptr)
Generate ILMs which computes the address of the index variable. Need to do it this way since the ILMs which were originally computed during the parse are not saved across the blocks.
int do_begin (DOINFO *doinfo)
Write out block DO AST from doinfo record. This function assumes that they init, limit, and step expressions have already been cast to the type of the do index variable.
static int tempify_ast (int)
void do_lastval (DOINFO *doinfo)
static void add_taskloopreg (DOINFO *doinfo)
int do_parbegin (DOINFO *doinfo)
void save_distloop_info (int lower, int upper, int stride)
void restore_distloop_info ()
int do_simdbegin (DOINFO *doinfo)
static int get_collapse_temp (int, const char *)
static int collapse_expr (int, int, const char *)
static void collapse_index (DOINFO *)
int collapse_begin (DOINFO *doinfo)
Begin processing loop collapse.
int collapse_add (DOINFO *doinfo)
Process an ensuing loop which is being collapsed.
void do_end (DOINFO *doinfo)
DOINFO * get_doinfo (int area)
int mkmember (int structd, int base, int nmx)
int mklabelvar (SST *stkptr)
Given an ast which computes the address of the label variable or loads the label variable, create the variable of indicated dtype.
LOGICAL legal_labelvar (int dtype)
Variables
struct {
int itemp
int doif_depth
int dtype
int index_var
int lp_cnt
int quo_var
int rem_var
int tmp_var
} coll_st
Detailed Description
Utility routines used by Semantic Analyzer.
Definition in file semutil.c.
Macro Definition Documentation
ARITH
#define ARITH (o) (o == OP_ADD || o == OP_SUB || o == OP_MUL || o == OP_DIV || o == OP_XTOI)
ERR170
#define ERR170 (s1, s2) error(170, 2, gbl.lineno, s1, s2)
Definition at line 32 of file semutil.c.
ERRMSG_BUFFSIZE
#define ERRMSG_BUFFSIZE 200
Definition at line 46 of file semutil.c.
OK_LTYP
#define OK_LTYP (t)
Value:
  ((t) == TY_WORD || (t) == TY_DWORD || (t) == TY_BINT || (t) == TY_SINT || \
   (t) == TY_INT || (t) == TY_CHAR || (t) == TY_NCHAR)
OP_AND
#define OP_AND -2
OP_EQV
#define OP_EQV -3
OP_OR
#define OP_OR -1
OP_XOR
#define OP_XOR -4
PT_OF
#define PT_OF (s) (DDTG(TYPE_OF(s))) /* pointer to data type */
Definition at line 44 of file semutil.c.
RTE_C
#define RTE_C
Definition at line 25 of file semutil.c.
TY_OF
#define TY_OF (s) (DTYG(TYPE_OF(s)))
Definition at line 43 of file semutil.c.
TYPE_OF
#define TYPE_OF (s) (SST_DTYPEG(s))
Definition at line 42 of file semutil.c.
UFCHAR
#define UFCHAR error(0, 3, gbl.lineno, "character array expressions not supported", CNULL)
Definition at line 34 of file semutil.c.
Function Documentation
_xtok()
static INT _xtok (INT conval1, BIGINT64 count, int dtype) static
Definition at line 6756 of file semutil.c.
References cngcon(), CNULL, const_fold(), CONVAL2G, count, STB::dbl1, DTY, error(), errsev(), STB::flt1, gbl, getcon(), STB::k1, mul64(), one, OP_DIV, STB::quad1, sem, sg, stb, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, SEM::which_pass, xdadd(), xdmul(), xdsub(), xfadd(), xfmul(), xfsub(), xqadd(), xqmul(), and xqsub().
Referenced by binop(), and const_xtoi().
add_ptr_assign()
int add_ptr_assign (int dest, int src, int std)
Definition at line 4144 of file semutil.c.
References A_OPTYPEG, A_OPTYPEP, add_arg(), add_stmt(), add_stmt_after(), add_stmt_before(), ARGT_ARG, ast, ast_is_sym(), astb, begin_call(), ASTB::bnd, check_member(), cmp_interfaces_strict(), CNULL, create_parameterized_dt(), dest, DTY, dtype, ASTB::dtype, dup_array_dtype(), ERR_Severe, error(), func, gbl, gen_contig_check(), get_len_of_deferchar_ast(), get_member_descriptor(), get_static_descriptor(), has_type_parameter(), IGNORE_ARG_NAMES, intast_sym, is_dtype_unlimited_polymorphic(), memsym_of_ast(), mk_argt(), mk_assn_stmt(), mk_cval(), mk_func_node(), mk_id(), mk_stmt(), mkRteRtnNm(), NOSYM, NULL, proc_arginfo(), RELAX_STYPE_CHK, RTE_asn_closure, src, std, string_expr_length(), sym_mkfunc_nodesc(), SYMNAME, TY_CHAR, and XBIT.
Referenced by _constructf90(), assign_intrinsic_to_pointer(), assign_pointer(), construct_association(), gen_and_assoc_tmp_ptr(), gen_poly_element_arg(), handle_allocatable_members(), rewrite_allocatable_assignment(), semant3(), and transform_call().
add_taskloopreg()
static void add_taskloopreg (DOINFO * doinfo) static
Definition at line 5885 of file semutil.c.
References add_stmt(), ast, DOINFO::init_expr, DOINFO::limit_expr, mk_stmt(), DOINFO::step_expr, and void().
Referenced by do_parbegin().
any_pointer_source()
int any_pointer_source (int ast)
Definition at line 4624 of file semutil.c.
References ast.
Referenced by chk_pointer_target(), and ref_pd().
assign()
int assign (SST * newtop, SST * stktop)
Assign stktop to newtop.
Definition at line 3443 of file semutil.c.
References SEM::alloc_std, argt, ARGT_ARG, SEM::arrfn, ast, ast_to_comment(), SEM::call_std, check_derived_type_array_section(), chktyp(), cngshape(), cngtyp(), cngtyp2(), delete_stmt(), direct_loop_end(), direct_loop_enter(), DT_ISVEC, DTY, DTYG, dtype, error83(), errsev(), FALSE, gbl, is_iso_cptr(), lhs, mk_assn_stmt(), mkexpr1(), mklvalue(), NULL, p, SEM::p_dealloc, SEM::p_dealloc_delete, SEM::return_value, S_EXPR, S_LVALUE, S_STFUNC, sem, sptr, SST_ASTG, SST_DTYPEG, SST_IDG, SST_LSYMG, SST_SHAPEG, SST_SYMG, STD_AST, stktop, subst_lhs_arrfn(), t, and SEM::try.
assign_array_w_forall()
int assign_array_w_forall (int dest_ast, int src_ast, int dtype, int ndim)
Called when array of derived type = scalar derived type, but the scalar derived type has an array component.
Definition at line 3337 of file semutil.c.
References AD_DPTR, AD_NUMDIM, add_astli(), ASD_SUBS, ast, astb, ASTLI_HEAD, ASTLI_SPTR, ASTLI_TRIPLE, ASTB::bnd, DTY, ASTB::dtype, get_temp(), i, interr(), list, MAXDIMS, mk_assn_stmt(), mk_id(), mk_stmt(), mk_subscr(), ndim, sptr, and start_astli().
assign_intrinsic_to_pointer()
static int assign_intrinsic_to_pointer (SST * newtop, SST * stktop) static
Definition at line 3871 of file semutil.c.
References add_ptr_assign(), CNULL, dest, SEM::dinit_error, DTY, error(), find_pointer_variable_assign(), gbl, INSIDE_STRUCT, sem, set_assn(), SST_ASTG, SST_DIMFLAGG, stktop, sym_of_ast(), SYMNAME, TRUE, TY_WORD, and valid_assign_pointer_types().
Referenced by assign_pointer().
assign_pointer()
int assign_pointer (SST * newtop, SST * stktop)
Definition at line 3914 of file semutil.c.
References add_ptr_assign(), argt, ARGT_ARG, SEM::arrfn, assign_intrinsic_to_pointer(), ast, SEM::call_std, chk_pointer_intent(), chk_pointer_target(), CNULL, dest, dtype, err_protected(), ERR_Severe, error(), find_pointer_variable_assign(), FLANG_FALLTHROUGH, gbl, intrinsic_as_arg(), IS_INTRINSIC, is_procedure_ptr(), is_protected(), mk_id(), mkexpr2(), mklvalue(), NULL, proc_arginfo(), SEM::return_value, S_EXPR, S_IDENT, select_gsame(), sem, set_assn(), sptr, SST_ASTG, SST_ASTP, SST_DIMFLAGG, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_SHAPEG, SST_SHAPEP, SST_SYMG, STD_AST, stktop, subst_lhs_pointer(), sym_of_ast(), SYMNAME, SEM::try, and valid_assign_pointer_types().
Referenced by add_assign_firstprivate(), add_ptr_assignment(), and semant3().
ast_isparam()
LOGICAL ast_isparam (int ast)
Definition at line 2614 of file semutil.c.
References A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, ast, ast_isparam(), FALSE, i, ndim, ss, TRUE, and val.
Referenced by ast_isparam(), ref_array(), and semant1().
binop()
void binop (SST * rslt, SST * lop, SST * operator, SST * rop)
Perform a binary operation on rhs1 and rhs2. They both conform in data type and shape.
Definition at line 5126 of file semutil.c.
References _xtok(), AD_DPTR, AD_NUMDIM, and64(), assert, BCOPY, chklog(), chkopnds(), clog_to_log(), cmp64(), cngcon(), const_fold(), const_xtoi(), constant_lvalue(), CONVAL2G, count, DT_INT, DT_ISINT, STB::dt_log, DT_LOG, DTY, errsev(), FALSE, get_array_dtype(), get_type(), getcon(), getitem(), getstring(), interr(), kanji_len(), mk_binop(), mk_cval(), mkexpr(), mkexpr1(), mklogint4(), STB::n_base, OP_ADD, OP_AND, OP_CAT, OP_CMP, OP_DIV, OP_EQ, OP_EQV, OP_GE, OP_GT, OP_LAND, OP_LE, OP_LEQV, OP_LNEQV, OP_LOG, OP_LOR, OP_LT, OP_MUL, OP_NE, OP_OR, OP_SUB, OP_XOR, OP_XTOI, OP_XTOX, or64(), res, S_CONST, S_EXPR, S_STFUNC, SCFTN_FALSE, SCFTN_TRUE, SST_ASTP, SST_CVALG, SST_CVALP, SST_CVLENG, SST_CVLENP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_OPCG, SST_OPTYPEG, SST_SYMG, SST_SYMP, stb, string_length(), TRUE, TY_CHAR, TY_DWORD, TY_ISCMPLX, TY_ISLOG, TY_LOG8, TY_NCHAR, TY_OF, TY_WORD, TYPE_OF, STB::user, val, and xor64().
Referenced by common_rel(), gen_reduction(), and semant2().
cast_to_typeless()
static void cast_to_typeless (SST * op, int typ) static
Definition at line 4718 of file semutil.c.
References casttyp(), mk_convert(), SST_ASTG, SST_ASTP, TY_DWORD, TY_WORD, and void().
Referenced by chkopnds().
casttyp()
int casttyp (SST * old, int newcast)
Cast a given semantic entry into a desired type. No type conversion is done.
Returns
1 if no error, -1 if error
The following casts are ok:
Cast any of the data types to TY_WORD or TY_DWORD (necessary for the bitwise intrinsics and relational comparisons)
Cast a TY_WORD or TY_DWORD to any of the data types (necessary for casting the bitwise intrinsics back to a data type)
Since this is used primarily for the bitwise intrinsics, there is no need to support TY_DBLE, TY_CHAR, TY_CMPX, or TY_DCMPX since these types are illegal for these intrinsics. However, cast of TY_DWORD and TY_WORD to TY_CMPX and TY_DCMPLX is needed for relational comparisons. Comparisons between vector typed and typeless operands require typed vectors to be casted to typeless vectors.
Definition at line 306 of file semutil.c.
References cast_types, cngtyp(), STB::dt_int, DT_INT, DTY, DTYG, _acl::dtype, errsev(), FALSE, get_type(), im, mkexpr1(), S_ACONST, size_of(), SST_ACLG, SST_DTYPEG, SST_DTYPEP, SST_IDG, stb, TRUE, TY_INT8, and STB::user.
Referenced by cast_to_typeless(), chkopnds(), cngtyp2(), and ref_pd().
ch_substring()
void ch_substring (SST * stktop, SST * lb_sp, SST * ub_sp)
Substring of a character constant.
Definition at line 3189 of file semutil.c.
References ast, BCOPY, chk_scalartyp(), chktyp(), CONVAL2G, cp, DINIT_END, DINIT_LOC, dinit_put(), DINIT_STR, DT_INT, DT_ISINT, DTY, dtype, errsev(), FALSE, get_type(), getcctmp(), getcon(), getitem(), getstring(), kanji_len(), mk_cnst(), mk_cval(), mk_id(), mk_substr(), STB::n_base, p, S_CONST, S_EXPR, S_NULL, SST_ASTG, SST_ASTP, SST_CVALG, SST_CVALP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, stb, stktop, str, string_length(), strlen(), sym_is_refd(), TRUE, TY_CHAR, TY_NCHAR, val, and void().
Referenced by mkvarref(), semant1(), and semant2().
check_derived_type_array_section()
void check_derived_type_array_section (int ast)
Give error message for reference like a(:)b(:)
Definition at line 3395 of file semutil.c.
References ASD_NDIM, ASD_SUBS, ast, DTY, error(), FLANG_FALLTHROUGH, gbl, i, mem(), memsym_of_ast(), ndim, parent, sptr, ss, subscr, and SYMNAME.
Referenced by assign(), and semant2().
check_parent()
int check_parent (int sptr1, int sptr2)
Check parents of type extension for duplicate symbols.
To Do: Take into account attributes such as access (private/public) and overridable.
Definition at line 1946 of file semutil.c.
References check_parent(), DTY, and NOSYM.
Referenced by check_parent(), and link_members().
chk_arr_extent()
INT chk_arr_extent (SST * stkptr, const char * msg)
Restrict the expression to be suitable for an array extent.
Definition at line 259 of file semutil.c.
References astb, ASTB::bnd, chk_scalar_inttyp(), chk_scalartyp(), ASTB::dtype, FALSE, flg, msg(), and FLG::standard.
Referenced by semant1().
chk_pointer_intent()
int chk_pointer_intent (int pvar, int refast)
Definition at line 4602 of file semutil.c.
References error(), gbl, getbase(), INTENT_IN, INTENTG, ss, and SYMNAME.
Referenced by assign_pointer(), chk_arguments(), and semant3().
chk_pointer_target()
int chk_pointer_target (int pvar, int source)
Definition at line 4649 of file semutil.c.
References any_pointer_source(), CNULL, DDTG, DT_ISCMPLX, err_protected(), error(), F77OUTPUT, find_pointer_target(), gbl, is_procedure_ptr(), is_protected(), SYMNAME, and XBIT.
Referenced by _constructf90(), and assign_pointer().
chk_scalar_inttyp()
INT chk_scalar_inttyp (SST * stkptr, int dtype, const char * msg)
Same as chktyp() with the restriction that the expression must be a scalar (i.e., not an array/vector form) and integer (i.e., not logical).
Definition at line 242 of file semutil.c.
References chktyp(), DT_ISINT, DT_ISLOG, DT_ISNUMERIC, DTY, error(), errsev(), FALSE, flg, gbl, msg(), SST_DTYPEG, and FLG::standard.
Referenced by chk_arr_extent(), and semant3().
chk_scalartyp()
INT chk_scalartyp (SST * stkptr, int dtype, LOGICAL warnflg)
Same as chktyp() with the restriction that the expression must be a scalar (i.e., not an array/vector form).
Definition at line 227 of file semutil.c.
References chktyp(), DTY, errsev(), and SST_DTYPEG.
Referenced by ch_substring(), chk_arr_extent(), chksubstr(), gen_logical_if_expr(), semant1(), semant2(), semant3(), semantio(), and semsmp().
chkcon()
INT chkcon (SST * stkptr, int dtype, LOGICAL warnflg)
Check that the indicated semantic stack entry is a constant of the specified type and convert constant to new type if possible.
Returns
32-bit constant value or symbol table pointer.
Definition at line 98 of file semutil.c.
References cngcon(), constant_lvalue(), DT_ISINT, DT_ISREAL, DT_LOG, DTY, errsev(), errwarn(), flg, getstring(), S_CONST, S_EXPR, SCFTN_TRUE, SST_ASTG, SST_DTYPEG, SST_IDG, SST_SYMG, FLG::standard, TY_CHAR, TY_ISINT, TY_ISLOG, and TY_NCHAR.
Referenced by chkcon_to_isz(), get_param_alias_const(), semant1(), and semant3().
chkcon_to_isz()
ISZ_T chkcon_to_isz (SST * stkptr, LOGICAL warnflg)
Check that the indicated semantic stack entry is a constant of any integer type.
Returns
the integer value as type ISZ_T.
Issue an error message if stkptr is not a constant of the correct type.
Definition at line 165 of file semutil.c.
References chkcon(), CONVAL2G, DT_INT, DT_ISINT, dtype, errsev(), INT64_2_ISZ, ISZ_T, num, S_CONST, size_of(), SST_CVALG, SST_DTYPEG, SST_IDG, and XBIT.
Referenced by semant1(), and semsmp().
chklog()
int chklog (SST * stkptr)
Definition at line 1042 of file semutil.c.
References cngtyp(), DT_LOG, DTYG, errsev(), flg, mkexpr1(), S_CONST, SST_CVALP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_ISNONDECC, FLG::standard, TY_CHAR, TY_DWORD, TY_ISINT, and TY_ISLOG.
Referenced by binop(), chkopnds(), common_rel(), and log_negation().
chkopnds()
void chkopnds (SST * lop, SST * operator, SST * rop)
Make two operands conform in a binary operation. The sequence of events is crucial to correct interpretation of expression.
Definition at line 4739 of file semutil.c.
References ARITH, cast_to_typeless(), casttyp(), chklog(), chkshape(), cngshape(), cngtyp(), CONVAL2G, DDTG, DT_INT, DT_LOG, DTY, error83(), errsev(), errwarn(), flg, FLG::ieee, is_dbl0(), is_quad0(), mk_cval1(), mkexpr1(), num, OK_LTYP, OP_AND, OP_CAT, OP_CMP, OP_EQV, OP_LAND, OP_LEQV, OP_LOG, OP_LOR, OP_OR, OP_XOR, OP_XTOI, POW1, POW2, PT_OF, S_CONST, SST_ASTP, SST_CVALG, SST_CVALP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_ISNONDECC, SST_OPCG, SST_OPCP, SST_OPTYPEG, FLG::standard, TRUE, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT8, TY_ISCMPLX, TY_ISINT, TY_ISLOG, TY_ISNUMERIC, TY_ISVEC, TY_NCHAR, TY_OF, TY_QUAD, TY_REAL, TY_WORD, TYPE_OF, void(), XBIT, xdisint(), xfisint(), and xqisint().
Referenced by binop().
chkshape()
LOGICAL chkshape (SST * old, SST * new, LOGICAL promote)
Semantically check an operand (old) for array conformance with operand new. If the operand is a scalar, change the shape of the operand to conform with the expected shape. If the operand is an array, check for conformance.
Parameters
old operand to check
new operand to conform with
promote if true, promote scalar to vector
Returns
TRUE if shapes are conformant; false, otherwise.
Definition at line 1017 of file semutil.c.
References ast, conform_shape(), DTY, dup_array_dtype(), mk_promote_scalar(), SST_ASTG, SST_ASTP, SST_DTYPEG, SST_DTYPEP, SST_SHAPEG, SST_SHAPEP, and TRUE.
Referenced by chkopnds(), and ref_pd().
chksubscr()
INT chksubscr (SST * stkptr, int sptr)
Convert expression pointed to by stkptr from its current data type to a data type consistent with subscripting.
Returns
the ILM pointer
Definition at line 272 of file semutil.c.
References astb, ASTB::bnd, cngtyp(), CNULL, DTY, DTYG, ASTB::dtype, error(), errsev(), gbl, mkexpr1(), rank_of_ast(), sptr, SST_ASTG, SST_DTYPEG, SST_ISNONDECC, SYMNAME, TY_INT8, and TY_ISINT.
Referenced by ref_array().
chksubstr()
int chksubstr (SST * stktop, ITEM * item)
Check that substring specifier is correct, write SUBS (substring) ILM and return pointer to it.
Definition at line 3029 of file semutil.c.
References ast, ast_intr(), astb, ASTB::bnd, chk_scalartyp(), chktyp(), cngcon(), CNULL, CONVAL2G, DDTG, STB::dt_int, DT_ISINT, DTY, dtype, ASTB::dtype, error(), FALSE, gbl, get_type(), ASTB::i1, interr(), ITEM_END, mk_binop(), mk_convert(), mk_cval(), mk_substr(), xyyz::next, OP_ADD, OP_SUB, ref_entry(), ref_object(), S_CONST, S_DERIVED, S_LVALUE, S_NULL, S_TRIPLE, size_ast(), sptr, SST_ASTG, SST_ASTP, SST_CVALG, SST_CVALP, SST_CVLENP, SST_DTYPEG, SST_DTYPEP, SST_E1G, SST_E2G, SST_E3G, SST_IDG, SST_IDP, SST_LSYMG, SST_LSYMP, SST_SHAPEP, SST_SYMG, stb, xyyz::stkp, stktop, string_length(), SYMNAME, t, xyyz::t, TRUE, TY_CHAR, TY_INT8, TY_NCHAR, and STB::user.
Referenced by mkvarref().
chktyp()
INT chktyp (SST * stkptr, int dtype, LOGICAL warnflg)
Convert expression pointed to by stkptr from its current data type to data type dtype.
Returns
ILM pointer
Definition at line 199 of file semutil.c.
References cngtyp(), DT_INT, DTY, DTYG, errwarn(), mkexpr1(), S_CONST, SST_DTYPEG, SST_IDG, SST_ISNONDECC, TY_ISINT, and TY_ISLOG.
Referenced by assign(), ch_substring(), chk_expr(), chk_scalar_inttyp(), chk_scalartyp(), chk_unitid(), chksubstr(), collapse_add(), collapse_begin(), collapse_index(), ref_intrin(), ref_pd(), ref_stfunc(), semant1(), semant3(), and semsmp().
clog_to_log()
static INT clog_to_log (INT clog) static
Definition at line 5538 of file semutil.c.
References SCFTN_FALSE, and SCFTN_TRUE.
Referenced by binop().
cngshape()
void cngshape (SST * old, SST * new)
Definition at line 942 of file semutil.c.
References assert, ast, CNULL, conform_shape(), DT_INT, DTY, DTYG, dup_array_dtype(), error(), error83(), errsev(), FALSE, gbl, interr(), is_iso_c_loc(), mk_promote_scalar(), mkexpr1(), S_EXPR, SST_ASTG, SST_ASTP, SST_DTYPEG, SST_DTYPEP, SST_IDP, SST_SHAPEG, SST_SHAPEP, TRUE, TY_CHAR, TY_ISVEC, UFCHAR, and void().
Referenced by assign(), chkopnds(), and unop().
cngtyp()
void cngtyp (SST * old, DTYPE newtyp)
Convert expression pointed-to by old to the data type newtyp.
Main entry point for cngtyp2() that assumes no polymorphic expressions.
Parameters
old points to the semantic stack entry with the old data type.
newtyp is the new dtype for the old semantic stack entry.
Definition at line 936 of file semutil.c.
References cngtyp2().
Referenced by assign(), byvalue_ref_arg(), casttyp(), chk_arguments(), chklog(), chkopnds(), chksubscr(), chktyp(), cngtyp2(), compute_size_expr(), form_cmplx_const(), log_negation(), ref_intrin(), ref_pd(), semant2(), semant3(), and unop().
cngtyp2()
static void cngtyp2 (SST * old, DTYPE newtyp, bool allowPolyExpr) static
Convert expression pointed-to by old to the data type newtyp.
If newtyp points to a TY_ARRAY entry or newshape is true then old is converted to an array.
Parameters
old points to the semantic stack entry with the old data type.
newtyp is the new dtype for the old semantic stack entry.
allowPolyExpr is true when we want to allow type extension in our type comparison.
Definition at line 379 of file semutil.c.
References ADD_NUMDIM, ast, casttyp(), cngcon(), cngtyp(), CNULL, DDTG, DT_INT, DT_LOG, DT_REAL, DTY, DTYG, eq_dtype2(), error(), errsev(), F77OUTPUT, FALSE, FLANG_FALLTHROUGH, flg, gbl, get_type(), is_dtype_unlimited_polymorphic(), is_iso_c_funptr(), is_iso_c_ptr(), is_iso_cptr(), mk_alias(), mk_convert(), mk_cval1(), mkexpr1(), S_CONST, S_EXPR, same_dtype(), SST_ASTG, SST_ASTP, SST_CVALG, SST_CVALP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_SHAPEP, FLG::standard, TRUE, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_ISLOG, TY_ISNUMERIC, TY_ISSCALAR, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, and void().
Referenced by assign(), and cngtyp().
collapse_add()
int collapse_add (DOINFO * doinfo)
Process an ensuing loop which is being collapsed.
Definition at line 6174 of file semutil.c.
References add_stmt(), ast, astb, BLK_SYM, chktyp(), coll_st, DOINFO::collapse, SEM::collapse, SEM::collapse_depth, collapse_expr(), collapse_index(), DOINFO::count, DI_CONC_BLOCK_SYM, DI_DOCONCURRENT, DI_DOINFO, DI_ID, DI_SIMD, do_lastval(), do_parbegin(), do_simdbegin(), SEM::doif_depth, DT_INT, DT_ISINT, dtype, FALSE, get_collapse_temp(), get_doinfo(), i, ASTB::i1, DOINFO::index_var, DOINFO::init_expr, ASTB::k1, DOINFO::limit_expr, mk_assn_stmt(), mk_binop(), mk_id(), mkexpr1(), OP_ADD, OP_DIV, OP_MUL, OP_SUB, DOINFO::prev_dovar, S_EXPR, S_IDENT, SEM::scope_level, sem, SST_ASTG, SST_ASTP, SST_DTYPEP, SST_IDP, SST_SYMP, std, STD_BLKSYM, DOINFO::step_expr, TRUE, and void().
Referenced by semant3().
collapse_begin()
int collapse_begin (DOINFO * doinfo)
Begin processing loop collapse.
Example: the use of the collapse is for 3 loops.
!$omp ... collapse(3)
    do i1 = in1, l1, s1
      do i2 = in2, l2, s2
        do i3 = in3, l3, s3
        ... SS ...
The 3 loops are collapsed into a single loop with a new index variable and loop count. The new loop defines the iteration space for which the other omp clauses are applied; the new loop will appear as:
    n1 = (l1 - in1 + s1)/s1
    n2 = (l2 - in2 + s2)/s2
    n3 = (l3 - in3 + s3)/s3
    nn = n1*n2*n3  !! the product of the loop counts
!$omp ...
    do ii = 1, nn
        t  = ii-1
        q  = t / n3
        r  = t - q*n3
        i3 = in3 + r*s3
        t  = q
        q  = t / n2
        r  = t - q*n2
        i2 = in2 + r*s2
        t  = q
        q  = t / n1
        r  = t - q*n1
        i2 = in1 + r*s1
        ... SS ...
Basically, the original index variables are no longer iterated; their values are computed as a function of the new index variable and the corresponding loops' init, stride, and loop count.
Prefix of temps created for each loop:
    .Xa - lower bound
    .Xb - stride
    .Xc - loop count
Collapsed loop:
    .Xd - loop count
    .id - index variable
    .Xe - quotient  of id/loopcnt
    .Xf - remainder of id/loopcnt
    .Xg = temp var
Definition at line 6093 of file semutil.c.
References add_stmt(), ast, BLK_SYM, chktyp(), coll_st, DOINFO::collapse, SEM::collapse, SEM::collapse_depth, collapse_expr(), DOINFO::count, DI_DOINFO, do_begin(), SEM::doif_depth, DT_INT, DT_ISINT, dtype, error(), FALSE, gbl, get_collapse_temp(), DOINFO::index_var, DOINFO::init_expr, DOINFO::limit_expr, mk_assn_stmt(), mk_binop(), mk_id(), mkexpr1(), OP_ADD, OP_DIV, OP_SUB, S_EXPR, S_IDENT, SEM::scope_level, sem, SST_ASTG, SST_ASTP, SST_DTYPEP, SST_IDP, SST_SYMP, DOINFO::step_expr, SYMNAME, and void().
Referenced by do_distbegin(), and semant3().
collapse_expr()
static int collapse_expr (int ast, int dtype, const char * pfx) static
Definition at line 6296 of file semutil.c.
References add_stmt(), ast, coll_st, getccssym_sc(), mk_assn_stmt(), mk_id(), SEM::sc, sem, sptr, and void().
Referenced by collapse_add(), and collapse_begin().
collapse_index()
static void collapse_index (DOINFO * dd) static
Definition at line 6315 of file semutil.c.
References add_stmt(), astb, chktyp(), cnt, coll_st, DOINFO::collapse, SEM::collapse, DOINFO::count, FALSE, ASTB::i1, DOINFO::index_var, DOINFO::init_expr, ASTB::k1, mk_assn_stmt(), mk_binop(), mk_id(), mkexpr1(), OP_ADD, OP_DIV, OP_MUL, OP_SUB, q, r, S_IDENT, sem, SST_ASTG, SST_DTYPEP, SST_IDP, SST_SYMP, DOINFO::step_expr, tmp, and void().
Referenced by collapse_add().
const_xtoi()
static INT const_xtoi (INT conval1, int cnt, int dtype) static
Definition at line 1890 of file semutil.c.
References _xtok(), cnt, and CONVAL2G.
Referenced by binop().
constant_lvalue()
void constant_lvalue (SST * stkptr)
If stkptr is an LVALUE that has a constant value, replace it with the constant value.
Definition at line 70 of file semutil.c.
References ast, astb, CONVAL2G, DT_ISWORD, dtype, S_CONST, S_LVALUE, sptr, SST_ASTG, SST_ASTP, SST_DTYPEP, SST_IDG, SST_IDP, and SST_SYMP.
Referenced by binop(), chkcon(), ref_array(), semant1(), and unop().
do_begin()
int do_begin (DOINFO * doinfo)
Write out block DO AST from doinfo record. This function assumes that they init, limit, and step expressions have already been cast to the type of the do index variable.
Definition at line 5781 of file semutil.c.
References ast, DOCHK, DOINFO::index_var, DOINFO::init_expr, DOINFO::limit_expr, mk_id(), mk_stmt(), DOINFO::prev_dovar, and DOINFO::step_expr.
Referenced by _constructf90(), collapse_begin(), compute_size_ido(), do_distbegin(), do_parbegin(), do_simdbegin(), semant3(), and semantio().
do_end()
void do_end (DOINFO * doinfo)
Definition at line 6385 of file semutil.c.
References add_stmt(), add_stmt_after(), ast, check_doconcurrent(), SEM::close_pdo, DOINFO::collapse, SEM::collapse, SEM::construct_sptr, SCN::currlab, DCLCHK, DI_ACCDO, DI_ACCKERNELSDO, DI_ACCKERNELSLOOP, DI_ACCLOOP, DI_ACCPARALLELDO, DI_ACCPARALLELLOOP, DI_ACCREGDO, DI_ACCREGLOOP, DI_ACCSERIALLOOP, DI_BDISTRIBUTE, DI_BEGINP, DI_BPAR, DI_BTARGET, DI_CONC_COUNT, DI_CONC_MASK_STD, DI_CONC_SYMS, DI_CUFKERNEL, DI_CYCLE_LABEL, DI_DISTPARDO, DI_DISTRIBUTE, DI_DO, DI_DO_POPINDEX, DI_DOACROSS, DI_DOCONCURRENT, DI_DOINFO, DI_DOWHILE, DI_EXIT_LABEL, DI_ID, DI_PARDO, DI_PDO, DI_SIMD, DI_TARGPARDO, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TASKLOOP, DI_TEAMSDIST, DI_TEAMSDISTPARDO, DI_TOP_LABEL, SEM::doif_depth, emit_epar(), emit_etarget(), end_parallel_clause(), ENDLINEP, flg, gbl, getlab(), i, DOINFO::index_var, mk_label(), mk_stmt(), mp_create_escope(), par_pop_scope(), SEM::parallel, pop_sym(), DOINFO::prev_dovar, RFCNTI, scn, sem, FLG::smp, sptr, SPTR_NULL, stb, std, STD_BLKSYM, STD_LABEL, STD_LAST, STD_LINENO, SCN::stmtyp, SYMI_NEXT, SYMI_SPTR, SEM::target, SEM::task, TRUE, and void().
Referenced by _constructf90(), compute_size_ido(), semant1(), semant3(), and semantio().
do_index_addr()
int do_index_addr (int sptr)
Generate ILMs which computes the address of the index variable. Need to do it this way since the ILMs which were originally computed during the parse are not saved across the blocks.
Definition at line 5771 of file semutil.c.
References ref_object(), and sptr.
do_lastval()
void do_lastval (DOINFO * doinfo)
Definition at line 5807 of file semutil.c.
References add_stmt(), ast, astb, DT_INT, dtype, SEM::expect_simd_do, get_itemp(), ASTB::i0, DOINFO::index_var, DOINFO::init_expr, DOINFO::lastval_var, DOINFO::limit_expr, mk_assn_stmt(), mk_binop(), mk_id(), OP_ADD, OP_DIV, OP_MUL, OP_SUB, sem, sptr, DOINFO::step_expr, tempify_ast(), and void().
Referenced by collapse_add(), do_distbegin(), and semant3().
do_parbegin()
int do_parbegin (DOINFO * doinfo)
Definition at line 5897 of file semutil.c.
References A_ORDEREDP, A_SCHED_TYPEP, add_taskloopreg(), ast, DI_BTARGET, DI_CHUNK, DI_DISTCHUNK, DI_ID, DI_IS_ORDERED, DI_PARDO, DI_SCHED_TYPE, DI_TARGET, DI_TASKLOOP, do_begin(), DOCHK, SEM::doif_depth, DT_ISINT, error(), gbl, DOINFO::index_var, DOINFO::init_expr, DOINFO::lastval_var, DOINFO::limit_expr, mk_id(), mk_stmt(), DOINFO::prev_dovar, sem, DOINFO::step_expr, and SYMNAME.
Referenced by collapse_add(), do_distbegin(), and semant3().
do_simdbegin()
int do_simdbegin (DOINFO * doinfo)
Definition at line 5978 of file semutil.c.
References A_ORDEREDP, A_SCHED_TYPEP, ast, do_begin(), DOCHK, DT_ISINT, error(), gbl, DOINFO::index_var, DOINFO::init_expr, DOINFO::lastval_var, DOINFO::limit_expr, mk_id(), mk_stmt(), DOINFO::prev_dovar, DOINFO::step_expr, and SYMNAME.
Referenced by collapse_add().
err_protected()
void err_protected (int sptr, const char * context)
Definition at line 4697 of file semutil.c.
References ERRMSG_BUFFSIZE, error(), gbl, sptr, and SYMNAME.
Referenced by assign_pointer(), chk_arguments(), chk_pointer_target(), semant3(), and set_assn().
error83()
static void error83 (int ty) static
Definition at line 6972 of file semutil.c.
References errsev(), TY_CHAR, and UFCHAR.
Referenced by assign(), chkopnds(), cngshape(), mkexpr1(), ref_array(), and valid_assign_pointer_types().
find_pointer_variable_assign()
static int find_pointer_variable_assign (int ast, int dimFlag) static
Definition at line 4527 of file semutil.c.
References ASD_SUBS, ast, error(), find_pointer_variable(), gbl, i, SHD_NDIM, and sub.
Referenced by assign_intrinsic_to_pointer(), and assign_pointer().
fix_term()
int fix_term (SST * stktop, int sptr)
Repair a bad term in an expression.
Done by using the constant (sptr) passed to this routine. An xCON ILM is generated referencing this constant.
Definition at line 3312 of file semutil.c.
References DTY, interr(), S_EXPR, sptr, SST_DTYPEP, SST_IDP, stktop, TY_DBLE, TY_INT, TY_INT8, and TY_REAL.
Referenced by ref_intrin(), ref_pd(), and semant2().
gen_contig_check()
void gen_contig_check (int dest, int src, SPTR sdsc, int srcLine, bool cs, int std)
Generate a contiguous pointer check on a pointer assignment when applicable.
Parameters
dest is the destination pointer.
src is the pointer target.
sdsc is an optional descriptor argument to pass to the check function (0 to use src's descriptor).
srcLine is the line number associated with the check.
cs is true when we are generating the check at a call-site.
std is the optional statement descriptor for adding the check (0 if not applicable).
Definition at line 4372 of file semutil.c.
References add_stmt(), add_stmt_after(), add_stmt_before(), ARGT_ARG, ast_is_sym(), check_member(), cs, dest, DT_INT, func, gbl, get_member_descriptor(), get_static_descriptor(), getstring(), inline_contig_check(), interr(), lineno, memsym_of_ast(), mk_argt(), mk_cval1(), mk_func_node(), mk_id(), mk_stmt(), mk_unop(), mkRteRtnNm(), NOSYM, OP_VAL, RTE_contigchk, RTE_contigerror, src, std, strlen(), sym_mkfunc_nodesc(), SYMNAME, and XBIT.
Referenced by add_ptr_assign(), newargs_for_entry(), and transform_call().
gen_poly_element_arg()
int gen_poly_element_arg (int ast, SPTR sptr, int std)
Generates a call to a poly_element_addr runtime routine that computes the address of a polymorphic array element.
This is required when our passed object argument of a type bound procedure call is an array element.
Parameters
ast is the ast of the passed object argument (an A_SUBSCR ast).
sptr is the symbol table pointer of the passed object argument.
std is the current statement descriptor.
Returns
an ast that represents the pointer that holds the address of the polymorphic array element.
Definition at line 4033 of file semutil.c.
References add_ptr_assign(), add_stmt_after(), add_stmt_before(), args, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, check_member(), DT_INT, SEM::dtemps, DTY, dtype, dtype_to_arg(), fix_class_args(), func, gbl, get_member_descriptor(), get_static_descriptor(), get_type_descr_arg(), getccsym_sc(), i, mk_argt(), mk_cval1(), mk_func_node(), mk_id(), mk_set_type_call(), mk_unop(), mkRteRtnNm(), needs_descriptor(), NOSYM, OP_VAL, RTE_poly_element_addr, RTE_poly_element_addr1, RTE_poly_element_addr2, RTE_poly_element_addr3, sem, set_descriptor_rank(), sptr, ss, std, sym_mkfunc_nodesc(), and tmp.
Referenced by ref_array(), transform_call(), and transform_section_arg().
get_collapse_temp()
static int get_collapse_temp (int dtype, const char * pfx) static
Definition at line 6287 of file semutil.c.
References coll_st, getccssym_sc(), SEM::sc, sem, and sptr.
Referenced by collapse_add(), and collapse_begin().
get_doinfo()
DOINFO * get_doinfo (int area)
Definition at line 6635 of file semutil.c.
References area, DOINFO::collapse, DOINFO::distloop, and getitem().
Referenced by acl_rewrite_asts(), collapse_add(), do_distbegin(), get_dobegin(), rewrite_acl(), save_acl(), semant2(), semant3(), and semantio().
get_sst_cval()
INT get_sst_cval (SST * stkp)
Get the SST_CVAL-like value for a semantic stack entry already determined to be a constant (i.e., is_sst_const() is true).
SST_CVAL-like means just the the sst's CVAL field. If the stack has been evaluated (is an S_EXPR), need to get CVAL from the ast.
Definition at line 2547 of file semutil.c.
References assert, ast, CONVAL2G, DTY, S_CONST, S_EXPR, sptr, SST_ASTG, SST_CVALG, SST_IDG, TY_BINT, TY_BLOG, TY_INT, TY_LOG, TY_REAL, TY_SINT, TY_SLOG, and TY_WORD.
Referenced by ref_pd(), and set_kind_result().
getbase()
int getbase (int ast)
Dereference an ast to determine the base, i.e. its symbol pointer.
Definition at line 5740 of file semutil.c.
References ast, and getbase().
Referenced by chk_pointer_intent(), getbase(), mklvalue(), and mkvarref().
in_save_scope()
bool in_save_scope (SPTR sptr)
Definition at line 2480 of file semutil.c.
References SEM::savall, sem, and sptr.
Referenced by do_save(), misc_checks(), ref_based_object_sc(), and semant1().
inline_contig_check()
static int inline_contig_check (int src, SPTR src_sptr, SPTR sdsc, int std) static
Generate contiguity check test inline (experimental)
Called by gen_contig_check() below to generate the contiguity check inline. This is an experimental test since it looks at the descriptor flags, data type, and src_sptr if src_sptr is an optional dummy argument. The endif asts are generated in gen_contig_check().
Parameters
src is the source/pointer target ast.
src_sptr is the source/pointer target sptr.
sdsc is the source/pointer target's descriptor
std is the optional statement descriptor for adding the check (0 if not applicable).
Returns
the statement descriptor (std) of the generated code.
Definition at line 4312 of file semutil.c.
References __SEQUENTIAL_SECTION, add_stmt(), add_stmt_after(), add_stmt_before(), ast_intr(), astb, ASTB::bnd, cmp(), DDTG, DT_INT, STB::dt_log, ASTB::dtype, get_header_member_with_parent(), ASTB::i0, I_AND, mk_binop(), mk_isz_cval(), mk_stmt(), OP_EQ, present, size_ast(), src, stb, std, STB::user, and XBIT.
Referenced by gen_contig_check().
is_protected()
LOGICAL is_protected (int sptr)
Definition at line 4689 of file semutil.c.
References FALSE, SEM::mod_sym, sem, sptr, and TRUE.
Referenced by assign_pointer(), chk_arguments(), chk_pointer_target(), semant3(), and set_assn().
is_selector()
static bool is_selector (SPTR sptr) static
Checks whether a symbol is used in a select type or associate construct as a selector.
Parameters
sptr is the symbol we are checking.
Returns
true if symbol is a selector in an associate/select type construct; else false.
Definition at line 2712 of file semutil.c.
References DI_ASSOC, DI_ASSOCIATIONS, DI_ID, DI_SELECT_TYPE, DI_SELECTOR, SEM::doif_depth, i, itemp, NULL, sem, sptr, and SYMNAME.
Referenced by ref_array().
is_sst_const()
LOGICAL is_sst_const (SST * stk)
Check if a stack entry represents a constant or an expression evaluated to a constant.
Definition at line 2524 of file semutil.c.
References FALSE, S_CONST, S_EXPR, SST_ASTG, SST_IDG, stk, and TRUE.
Referenced by ref_intrin(), ref_pd(), and set_kind_result().
is_varref()
LOGICAL is_varref (SST * stk)
Check if a stack entry is a legal variable reference.
This routine is used when it's known that a variable reference is required and a check is necessary before calling routines like like mkvarref and mklvalue.
Definition at line 2585 of file semutil.c.
References FALSE, S_IDENT, S_LVALUE, SST_IDG, stk, and TRUE.
Referenced by chk_expr(), chk_var(), ref_intrin_subr(), ref_pd(), ref_pd_subr(), semant3(), and semantio().
legal_labelvar()
LOGICAL legal_labelvar (int dtype)
Definition at line 6746 of file semutil.c.
References STB::dt_int, FALSE, stb, TRUE, and STB::user.
Referenced by chk_fmtid(), and semant3().
link_members()
void link_members (STSK * stsk, int sptr)
Link together members of a structure.
Parameters
stsk the structure stack item representing the structure to which members are added
sptr points to a list of new members linked via symlk
The new member list is added to the end of the existing member list watching out for duplicate member names.
Definition at line 1970 of file semutil.c.
References assert, check_parent(), CNULL, count, DTY, STSK::dtype, dtype, error(), gbl, get_entity_access(), STSK::last, STSK::mem_access, NOSYM, sptr, stsk, and SYMNAME.
Referenced by link_parents(), semant1(), and setup_procedure_sym().
link_parents()
void link_parents (STSK * stsk, int sptr)
Link parents for type extension by adding parent as a member to the type.
Definition at line 1913 of file semutil.c.
References DTY, insert_sym(), link_members(), sptr, STSK::sptr, and stsk.
Referenced by semant1().
mk_component_ast()
int mk_component_ast (int leaf, int parent, int src_ast)
Definition at line 4469 of file semutil.c.
References AD_DPTR, AD_LWAST, AD_NUMDIM, AD_UPAST, add(), ASD_SUBS, DDTG, dt, DTY, i, interr(), MAXDIMS, mk_id(), mk_subscr(), mk_triple(), ndim, nsubs, and parent.
mkexpr()
int mkexpr (SST * stkptr)
Definition at line 1093 of file semutil.c.
References mkexpr1(), and mklogint4().
Referenced by _constructf90(), binop(), byvalue_ref_arg(), chk_expr(), chkarg(), compute_size_expr(), construct_association(), define_stfunc(), evl_kwd_args(), gen_dtio_args(), is_intrinsic_opr(), mkarg(), mkexpr_assign_temp(), mklabelvar(), ref_intrin(), ref_pd(), ref_pd_subr(), ref_stfunc(), resolve_generic(), rewrite_acl(), semant1(), semant2(), semant3(), semantio(), sum_scatter_args(), and tempify().
mkexpr1()
int mkexpr1 (SST * stkptr)
Given a semantic stack entry, write ILM's for the expression represented by the stack entry if they have not already been written.
Returns
pointer to ILM
Definition at line 1107 of file semutil.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_UPAST, ADD_UPBD, astb, ASTB::bnd, CNULL, DDTG, SEM::dinit_data, dont_issue_assumedsize_error, DT_INT, DT_ISBASIC, DTY, dtype, error(), error83(), errsev(), FLANG_FALLTHROUGH, func_call(), gbl, get_all_descriptors(), get_next_hash_link(), get_static_descriptor(), getcon(), init_sptr_w_acl(), intast_sym, interr(), ITEM_END, mk_cnst(), mk_extent(), mk_id(), mkident(), mkvarref(), newsym(), NOSYM, NULL, num, ASTB::one, ref_entry(), ref_object(), ref_pd(), RU_FUNC, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_LOGEXPR, S_LVALUE, S_REF, S_STAR, S_STFUNC, S_VAL, sem, sem_set_storage_class(), size_ast(), sptr, SST_ACLG, SST_ASTG, SST_ASTP, SST_CVLENP, SST_DTYPEG, SST_DTYPEP, SST_ENDG, SST_IDG, SST_IDP, SST_LSYMG, SST_LSYMP, SST_SHAPEP, SST_SYMG, SST_SYMP, sym_get_array(), SYMNAME, test_scope(), TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, void(), and ASTB::zero.
Referenced by assign(), binop(), casttyp(), chklog(), chkopnds(), chksubscr(), chktyp(), cngshape(), cngtyp2(), collapse_add(), collapse_begin(), collapse_index(), do_openmp_atomics(), gen_logical_if_expr(), mkexpr(), mkexpr2(), semant3(), unop(), and validate_omp_atomic().
mkexpr2()
int mkexpr2 (SST * stkptr)
Same as mkexpr1(), but the expression is the target of a pointer assignment. Must handle ST_PROCs as identifiers; otherwise, just call mkexpr1().
Definition at line 1389 of file semutil.c.
References DDTG, dt, DTY, mk_id(), mkexpr1(), ref_object(), S_IDENT, size_ast(), sptr, SST_ASTG, SST_ASTP, SST_CVLENP, SST_DTYPEP, SST_IDG, SST_SHAPEP, SST_SYMG, TY_CHAR, and TY_NCHAR.
Referenced by _constructf90(), and assign_pointer().
mkident()
void mkident (SST * stkptr)
Definition at line 1084 of file semutil.c.
References S_IDENT, SST_ALIASP, SST_CVLENP, SST_IDP, and SST_SHAPEP.
Referenced by defined_operator(), gen_dinit(), gen_dtio_args(), generic_func(), is_intrinsic_opr(), mkarg(), mkexpr1(), mkvarref(), ref_intrin(), semant1(), semant2(), semant3(), and tempify().
mklabelvar()
int mklabelvar (SST * stkptr)
Given an ast which computes the address of the label variable or loads the label variable, create the variable of indicated dtype.
Definition at line 6716 of file semutil.c.
References ast, dtype, getcctmp_sc(), interr(), mk_id(), mkexpr(), SEM::sc, sem, sptr, SST_ASTG, SST_ASTP, SST_DTYPEP, and XBIT.
Referenced by chk_fmtid(), and semant3().
mklogint4()
void mklogint4 (SST * stkptr)
Convert all sizes of logicals and integers to 4 byte versions.
Definition at line 1418 of file semutil.c.
Referenced by binop(), and mkexpr().
mklvalue()
int mklvalue (SST * stkptr, int stmt_type)
Check for legal variable to be assigned to.
Parameters
stkptr the variable to check
stmt_type type of statement we are processing, from the table below
Returns
The sptr of the variable if stmt_type indicates an index variable.
Otherwise the ILM pointer to address expression for the destination.
Zero is returned for cases where we want to avoid assignment code generation.
Possible values for stmt_type:
     0 - Do index var
     1 - Assignment statement
     2 - Data statement
     3 - LOC reference
     4 - Implied do index var
     5 - Forall index var
Definition at line 1442 of file semutil.c.
References AD_DPTR, AD_LWAST, AD_LWBD, AD_NUMDIM, ASD_NDIM, ASD_SUBS, ast, check_member(), CNULL, STB::curr_scope, DCLCHK, DDTG, decl_private_sym(), DI_ATOMIC_CAPTURE, DI_DISTPARDO, DI_DISTRIBUTE, DI_FORALL_DTYPE, DI_FORALL_SYMAVL, DI_ID, DI_PARDO, DI_PDO, DI_SIMD, DI_TARGTEAMSDIST, DI_TARGTEAMSDISTPARDO, DI_TASK, DI_TASKLOOP, DI_TEAMSDIST, DI_TEAMSDISTPARDO, SEM::dinit_error, DOCHK, SEM::doconcurrent_dtype, SEM::doconcurrent_symavl, SEM::doif_depth, DT_INT, DTY, DTYG, dtype, error(), errsev(), SEM::expect_cuf_do, FALSE, FLANG_FALLTHROUGH, flg, gbl, get_all_descriptors(), get_static_descriptor(), getbase(), getccsym(), GSAMEG, i, SEM::ignore_default_none, SEM::index_sym_to_pop, insert_sym(), INTENTG, interr(), MAXDIMS, memsym_of_ast(), mk_id(), mk_subscr(), mkshape(), newsym(), SEM::orph, SEM::parallel, prtsst(), ref_entry(), ref_object(), RU_FUNC, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_LVALUE, sem, sem_check_scope(), sem_set_storage_class(), set_assn(), setimplicit(), size_ast(), FLG::smp, sptr, SST_ASTG, SST_ASTP, SST_CVLENP, SST_DTYPEG, SST_DTYPEP, SST_ERRSYMG, SST_IDG, SST_LSYMG, SST_SHAPEG, SST_SHAPEP, SST_SYMG, FLG::standard, stb, sym_of_ast(), SYMNAME, SEM::target, SEM::task, SEM::teams, TRUE, TY_CHAR, TY_NCHAR, and XBIT.
Referenced by assign(), assign_pointer(), do_openmp_atomics(), gen_reduction(), ref_intrin(), semant1(), semant2(), semant3(), and validate_omp_atomic().
mkmember()
int mkmember (int structd, int base, int nmx)
Parameters
structd dtype record of parent structure
base ast ptr of parent structure
nmx index into "names" area of member
Returns
ast or 0 if not found
Definition at line 6651 of file semutil.c.
References ast, base, DTY, dtype, flg, mk_id(), mk_member(), mkmember(), mkunion(), NOSYM, sptr, FLG::xref, and xrefput().
Referenced by _constructf90(), add_iolptrs(), is_intrinsic_opr(), mkmember(), mkunion(), semant2(), and semant3().
mkunion()
static int mkunion (int uniond, int base, int nmx) static
Parameters
uniond dtype record of parent structure
base ast ptr of parent structure
nmx index into "names" area of member
Returns
ast or 0 if not found
Definition at line 6690 of file semutil.c.
References assert, ast, base, DTY, dtype, mkmember(), NOSYM, and sptr.
Referenced by mkmember().
mkvarref()
int mkvarref (SST * stktop, ITEM * list)
Make a var ref of the form: <var primary> ([<ssa list>])
Determine if a function call, array reference, or substring reference, and generate appropriate ILMs, shapes, data types. stktop is input and output.
Definition at line 2063 of file semutil.c.
References add_base(), ASD_NDIM, ASD_SUBS, ast, ch_substring(), chksubstr(), CNULL, ddtype(), dinit(), SEM::dinit_error, DT_INT, DTY, DTYG, dtype, error(), FALSE, FLANG_FALLTHROUGH, flg, func_call(), gbl, generic_func(), getbase(), getcon(), getstring(), GSAMEG, i, init_sptr_w_acl(), interr(), IS_CHAR_TYPE, is_procedure_ptr(), ITEM_END, list, memsym_of_ast(), mk_cnst(), mk_id(), mkident(), ndim, newsym(), next, NOSYM, NULL, ptrfunc_call(), FLG::recursive, ref_array(), ref_entry(), ref_intrin(), ref_object(), ref_pd(), ref_stfunc(), RU_FUNC, RU_PROG, RU_SUBR, S_ACONST, S_CONST, S_DERIVED, S_EXPR, S_IDENT, S_LVALUE, S_NULL, S_TRIPLE, sem, sem_set_storage_class(), sptr, ss, SST_ACLG, SST_ALIASG, SST_ASTG, SST_ASTP, SST_CLBEGG, SST_CVALG, SST_CVALP, SST_DTYPEG, SST_DTYPEP, SST_E1G, SST_E2G, SST_E3G, SST_ERRSYMG, SST_IDG, SST_IDP, SST_LSYMG, SST_LSYMP, SST_SHAPEP, SST_SYMG, SST_SYMP, FLG::standard, stktop, sym_skip_construct(), SYMNAME, test_really_an_entry(), TY_CHAR, TY_NCHAR, and val.
Referenced by gen_cmplxpart_intr(), mkarg(), mkexpr1(), ref_intrin(), ref_pd(), rewrite_cmplxpart_rhs(), rewrite_cmplxpart_rval(), semant1(), semant2(), semant3(), and semsmp().
mod_type()
int mod_type (int dtype, int ty, int kind, int len, int propagated, int sptr)
Return a new data type based on the rules of applying a length specifier to an existing base data type (i.e. LOGICAL*1) passed in as a TY_ value.
sptr points to the symbol table entry whose data type is being modified. This is for error messages. If no sptr then message is for type declaration verb.
Special case:
‍ When sptr is 0, the data type adjustment is occurring at the time when the length immediately follows a data type (i.e. when <data type> is being processed). When sptr is non-zero, this means that the length follows the name of the symbol (<data type> has already been processed) (i.e. CHARACTER FOO*1); and a length of -1 implies that no length was specified.
So, when sptr is nonzero and len is -1, we do not attempt to adjust the data type; if so, we will incorrectly adjust
      REAL*4  rv
when the "r8" option has been selected (-x 124 8).
Definition at line 5568 of file semutil.c.
References astb, CNULL, DT_INT, DT_LOG, DTY, dtype, error(), FLANG_FALLTHROUGH, flg, gbl, get_type(), ASTB::i0, ASTB::i1, FLG::i4, interr(), kind, len, mk_cval(), SEM::ogdtype, propagated, sem, sptr, SYMNAME, TY_BINT, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_REAL, and XBIT.
Referenced by get_retval_LEN_value(), and semant1().
not_in_arrfn()
static LOGICAL not_in_arrfn (int memref, int call) static
Definition at line 3726 of file semutil.c.
References A_ARGCNTG, arg, argt, ARGT_ARG, contains_ast(), FALSE, i, nargs, and TRUE.
Referenced by subst_lhs_arrfn(), and subst_lhs_pointer().
prtsst()
const char * prtsst (SST * stkptr)
Return the printable representation of a semantic stack entry.
Definition at line 5710 of file semutil.c.
References DT_ISCMPLX, DT_ISLOG, DT_ISREAL, DTYG, dtype, getprint(), STB::n_base, S_CONST, SCFTN_TRUE, SST_DTYPEG, SST_IDG, SST_SYMG, stb, TY_CHAR, and val.
Referenced by mklvalue().
ref_array()
static int ref_array (SST * stktop, ITEM * list) static
Definition at line 2736 of file semutil.c.
References AD_DPTR, AD_LWAST, AD_NUMDIM, AD_UPAST, AD_UPBD, add_stmt(), ALIGNG, SEM::array_const_level, ast, ast_isparam(), astb, ASTB::bnd, check_member(), chksubscr(), cngcon(), CNULL, constant_lvalue(), construct_acl_from_ast(), _acl::conval, CONVAL2G, count, SEM::dinit_data, SEM::dinit_error, DISTG, DT_ISINT, DT_ISVEC, DT_ISWORD, DTY, DTYG, _acl::dtype, dtype, ERR170, error(), error83(), errsev(), eval_init_expr(), FALSE, flg, gbl, gen_poly_element_arg(), i, SEM::in_dim, INSIDE_STRUCT, interr(), is_selector(), is_unl_poly(), ITEM_END, j, lbound_of(), list, MAXDIMS, mk_cval1(), mk_id(), mk_stmt(), mk_subscr(), mk_triple(), xyyz::next, ASTB::one, ref_entry(), ref_object(), S_CONST, S_DERIVED, S_KEYWORD, S_LABEL, S_LVALUE, S_NULL, S_TRIPLE, sem, sptr, SST_ACLP, SST_ASTG, SST_ASTP, SST_DIMFLAGG, SST_DTYPEG, SST_DTYPEP, SST_E1G, SST_E2G, SST_E3G, SST_IDG, SST_IDP, SST_LSYMG, SST_LSYMP, SST_SHAPEP, SST_SYMG, SST_SYMP, FLG::standard, std, xyyz::stkp, stktop, SYMNAME, xyyz::t, tmp, TRUE, TY_ISVEC, and ASTB::zero.
Referenced by mkvarref().
ref_object()
int ref_object (int sptr)
Access the address of the object (sym).
Definition at line 2600 of file semutil.c.
References SEM::orph, SEM::parallel, ref_based_object(), sem, sem_check_scope(), sptr, SEM::target, SEM::task, and SEM::teams.
Referenced by chksubstr(), do_distbegin(), do_index_addr(), mkarg(), mkexpr1(), mkexpr2(), mklvalue(), mkvarref(), and ref_array().
resolve_fwd_refs()
void resolve_fwd_refs (void)
Resolve forward references: try to find the declaration symbol and replace the reference symbol with it.
F95 allows forward references to pure functions from within specification expressions. A symbol will be created at the reference which must be fixed later after the function declaration has been seen. Possible forward references are marked FWDREF in mkvarref() above.
Definition at line 2447 of file semutil.c.
References first_hash(), STB::firstusym, and stb.
Referenced by parser().
restore_distloop_info()
void restore_distloop_info ()
Definition at line 5973 of file semutil.c.
save_distloop_info()
void save_distloop_info (int lower, int upper, int stride)
Definition at line 5968 of file semutil.c.
set_assn()
void set_assn (int sptr)
...
Definition at line 4707 of file semutil.c.
Referenced by assign_intrinsic_to_pointer(), assign_pointer(), and mklvalue().
subst_lhs_arrfn()
static LOGICAL subst_lhs_arrfn (int lhs, int rhs, int call) static
Definition at line 3575 of file semutil.c.
References AD_DPTR, AD_LWAST, AD_NUMDIM, AD_UPAST, SEM::arrfn, ASD_SUBS, astb, ASTB::bnd, DDTG, DI_IN_NEST, DI_WHERE, SEM::doif_depth, DTY, dtype, eldt, FALSE, gbl, lhs, memsym_of_ast(), not_in_arrfn(), ASTB::one, sem, SHD_NDIM, SEM::sptr, sub, sym_of_ast(), TY_CHAR, TY_NCHAR, and XBIT.
Referenced by assign().
subst_lhs_pointer()
static LOGICAL subst_lhs_pointer (int lhs, int rhs, int call) static
Definition at line 3690 of file semutil.c.
References DDTG, DTY, FALSE, lhs, memsym_of_ast(), not_in_arrfn(), tmp, TY_CHAR, TY_NCHAR, and XBIT.
Referenced by assign_pointer().
tempify_ast()
static int tempify_ast (int src) static
Definition at line 5870 of file semutil.c.
References add_stmt(), ast, get_temp(), mk_assn_stmt(), mk_id(), src, and void().
Referenced by do_lastval().
test_really_an_entry()
static int test_really_an_entry (int sptr) static
Definition at line 2038 of file semutil.c.
References gbl, interr(), NOSYM, and sptr.
Referenced by mkvarref().
unop()
void unop (SST * rslt, SST * operator, SST * rop)
Perform a unary operation on logical rhs.
Definition at line 5088 of file semutil.c.
References cngshape(), cngtyp(), constant_lvalue(), DDTG, DT_INT, DT_LOG, mkexpr1(), OP_ADD, OP_SUB, S_CONST, S_EXPR, S_STFUNC, SST_DTYPEP, SST_IDG, SST_IDP, SST_OPTYPEG, TY_ISLOG, TY_OF, and TYPE_OF.
Referenced by semant2().
update_proc_ptr_dtype_from_interface()
static void update_proc_ptr_dtype_from_interface (int func_sptr) static
Definition at line 3744 of file semutil.c.
References CHECK, DTY, findByNameStypeScope(), is_procedure_ptr(), NOSYM, NULL, proc_arginfo(), and SYMNAME.
Referenced by valid_assign_pointer_types().
valid_assign_pointer_types()
static LOGICAL valid_assign_pointer_types (SST * newtop, SST * stktop) static
Definition at line 3774 of file semutil.c.
References array_element_dtype(), bnds_remap_list(), DDTG, dest, DT_ISVEC, DTY, DTYG, dtype, eq_dtype2(), error(), error83(), FALSE, gbl, get_ast_sptr(), is_procedure_ptr_dtype(), NOSYM, NULL, proc_arginfo(), proc_ptr_result_dtype(), rank_of_ast(), simply_contiguous(), SST_ASTG, SST_DTYPEG, stktop, TRUE, TY_CHAR, TY_NCHAR, and update_proc_ptr_dtype_from_interface().
Referenced by assign_intrinsic_to_pointer(), and assign_pointer().
Variable Documentation
struct { ... } coll_st
Referenced by collapse_add(), collapse_begin(), collapse_expr(), collapse_index(), and get_collapse_temp().
doif_depth
int doif_depth
Definition at line 6021 of file semutil.c.
dtype
int dtype
Definition at line 6022 of file semutil.c.
Referenced by add_ptr_assign(), assign(), assign_pointer(), ch_substring(), chkcon_to_isz(), chksubstr(), collapse_add(), collapse_begin(), constant_lvalue(), do_lastval(), gen_poly_element_arg(), link_members(), mkexpr1(), mklabelvar(), mklvalue(), mkmember(), mkunion(), mkvarref(), mod_type(), prtsst(), ref_array(), subst_lhs_arrfn(), and valid_assign_pointer_types().
index_var
int index_var
Definition at line 6023 of file semutil.c.
Referenced by conv_forall(), inline_reduction_f90(), semantio(), sequentialize(), transform_elemental(), transform_merge(), and transform_mvbits().
itemp
int itemp
Definition at line 6020 of file semutil.c.
Referenced by _constructf90(), _non_private(), add_alloc_mem_initialize(), add_auto_dealloc(), add_auto_finalize(), add_p_dealloc_item(), add_private_allocatable(), add_type_param_initialize(), add_wheresym(), bblock(), check_alloc_clauses(), check_dealloc_clauses(), CONCAT(), convert_to_block_forall(), count_actuals(), cray_pointer_check(), deallocate_privates(), define_stfunc(), do_copyin(), do_copyprivate(), do_default_clause(), do_firstprivate(), do_private(), fix_proc_pointer_call(), func_call2(), gen_alloc_dealloc(), gen_defer_shape(), gen_derived_type_alloc_init(), gentab(), hashof(), hepify(), in_wheresymlist(), is_selector(), misc_checks(), mk_shared_list(), other_firstlast_check(), pntset(), private_check(), ptrfunc_call(), ptrsubr_call(), ref_stfunc(), reloc_byvalue_parameters(), resolve_generic(), save_firstprivate_list(), save_private_list(), save_shared_list(), semant1(), semant2(), semant3(), semantio(), semsmp(), sortcg(), sortgm(), ssa_list(), subr_call2(), and var_ref_list().
lp_cnt
int lp_cnt
Definition at line 6024 of file semutil.c.
quo_var
int quo_var
Definition at line 6025 of file semutil.c.
rem_var
int rem_var
Definition at line 6026 of file semutil.c.
tmp_var
int tmp_var
Definition at line 6027 of file semutil.c.