flang: semutil2.c File Reference
semutil2.c File Reference
Utility routines used by Fortran Semantic Analyzer.
#include "gbldefs.h"
#include "global.h"
#include "gramtk.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "semant.h"
#include "semstk.h"
#include "machar.h"
#include "ast.h"
#include "dinit.h"
#include "interf.h"
#include "tokdf.h"
#include "scan.h"
#include "pd.h"
#include "rte.h"
#include "state.h"
#include "ccffinfo.h"
#include "rtlRtns.h"
#include "llmputil.h"
Classes
struct _ido_info
struct _ACS
struct struct_init
struct ASTLIST
struct INDEX
Macros
#define TEMPS_CTR(n) (temps_ctr[n]++)
#define TEMPS_STK(n) ((sem.doif_depth << 10) + temps_ctr[n]++)
#define DEFAULT_DIM_SIZE 127
#define THRESHHOLD 20
#define DTC_DEFAULT_HEAD dt_init.default_acl
#define DTC_ACL_HEAD dt_init.dt_acl
#define DTC_DEFAULT(i) dt_init.default_acl[i]
#define DTC_ACL(i) dt_init.dt_acl[i]
#define DTC_DEFAULT_CNT dt_init.default_count
#define DTC_DT_CNT dt_init.dt_count
#define KANJI_BLANK 0xA1A1
#define INTINTRIN2(iname, ent, op)
#define GET_DBLE(x, y)
#define GET_QUAD(x, y)
#define GETVALI64(x, b)
#define FPINTRIN1(iname, ent, fscutil, dscutil, qscutil)
#define FPINTRIN2(iname, ent, fscutil, dscutil, qscutil)
#define TRACE_EVAL_SB 0
Typedefs
typedef struct _ido_info IDO_INFO
typedef struct struct_init struct_init
Functions
static void to_assumed_shape (int)
static int compute_width_dtype (DTYPE in_dtype)
static void compute_size (bool add_flag, ACL *aclp, DTYPE dtype)
static void compute_size_ast (bool add_flag, ACL *aclp, DTYPE dtype)
static DTYPE compute_size_expr (bool add_flag, ACL *aclp, DTYPE dtype)
static void compute_size_ido (bool add_flag, ACL *aclp, DTYPE dtype)
static void compute_size_sconst (bool add_flag, ACL *aclp, DTYPE dtype)
static void add_etmp (int sptr)
static void add_auto_array (int)
static void add_auto_char (int)
static void add_autobj (int)
static void put_prefix (char *, int, FILE *)
static void _dmp_acl (ACL *, int, FILE *)
static ACL * clone_init_const (ACL *original, int temp)
static ACL * clone_init_const_list (ACL *original, int temp)
static ACL * eval_init_expr_item (ACL *cur_e)
static ACL * eval_do (ACL *ido)
static INT get_default_int_val (INT)
static int ast_rewrite_indices (int ast)
static INT get_const_from_ast (int ast)
static ACL * eval_array_constructor (ACL *)
static ISZ_T get_ival (DTYPE, INT)
static ACL * get_exttype_struct_constructor (ACL *, DTYPE, ACL **)
static ACL * get_struct_default_init (int sptr)
static void add_alloc_mem_initialize (int)
static int genPolyAsn (int dest, int src, int std, int parent)
static void save_dim_specs (SEM_DIM_SPECS *aa)
static void restore_dim_specs (SEM_DIM_SPECS *aa)
static void dinit_constructor (SPTR, ACL *)
static AC_INTRINSIC map_I_to_AC (int intrin)
static AC_INTRINSIC map_PD_to_AC (int pdnum)
static bool is_illegal_expr_in_init (SPTR, int ast, DTYPE)
static int init_intrin_type_desc (int ast, SPTR sptr, int std)
This function initializes the type in a descriptor for an object with an intrinsic type.
void chk_adjarr (void)
int runtime_array (int ast)
Return TRUE if the expression at 'ast' is composed of constants and the special symbol 'hpf_np$'. In this case, even though the bound is not a literal constant, it is a runtime constant.
static int valid_kind_parm_expr (int ast)
static DTYPE _mk_arrdsc (int start_of_base)
DTYPE mk_arrdsc (void)
int gen_defer_shape (int sptr, int astparent, int savedelete)
Process an explicit shape list has been parsed and all bounds information has been deposited into a few semant global data structures.
void add_p_dealloc_item (int sptr)
void gen_deallocate_arrays ()
Generate deallocates for the temporary arrays in the sem.p_delloc list.
void mk_defer_shape (SPTR sptr)
static int tempvar (int astx)
void mk_assumed_shape (SPTR sptr)
SPTR get_arr_const (DTYPE dtype)
Get a compiler array temporary of type dtype which is used to represent array constants.
DTYPE select_kind (DTYPE dtype, int ty, INT kind_val)
static LOGICAL _can_fold (int)
static void constructf90 (int, ACL *)
static void _dinit_acl (ACL *, LOGICAL)
static const char * iexpr_op (int op)
void gen_allocate_array (int arr)
Given an allocatable array and an explicit shape list which has been deposited in the semant 'bounds' structure, generate assignments to the arrays bounds temporaries, and allocate the array. Save the id ast of the array for an ensuing deallocate of the array.
static void _printacl (int in_array, ACL *aclp, FILE *f)
void printacl (const char *s, ACL *aclp, FILE *f)
static void _dumpacl (int nest, ACL *aclp, FILE *f)
void dumpacl (const char *s, ACL *aclp, FILE *f)
static void _compute_width (int in_array, ACL *aclp)
ISZ_T size_of_array (DTYPE dtype)
Check if array has zero size.
static int compute_width (ACL *aclp)
DTYPE chk_constructor (ACL *aclp, DTYPE dtype)
Check the array constructor and decide the dtype.
void init_named_array_constant (int arr, int host)
Initialize a named array constant (array PARAMETER), ensuring that it's only being done within the context of its host subprogram.
SPTR get_param_alias_var (SPTR param_sptr, DTYPE dtype)
static int convert_ctmp_array_to_param (int cctmpsptr, ACL *aclp)
int init_sptr_w_acl (int in_sptr, ACL *aclp)
Assign aclp values to in_sptr.
static void check_dependence_ido (ACL *aclp)
static void handle_dependence_ido (ACL *aclp)
static void init_constructf90 ()
static int add_subscript (int base_id, int indexast, DTYPE dtype)
static int apply_shape_subscripts (int base_id, int shp, DTYPE dtype)
static void push_subscript ()
static void pop_subscript ()
static void clear_element_cnt ()
static void incr_element_cnt ()
static INT get_element_cnt ()
static int get_subscripting_tmp (int indexast)
static void incr_tmp (int tmpid)
static int size_of_shape_dim (int shape, int i)
static int get_shape_arraydtype (int shape, int eltype)
static void mkexpr_assign_temp (SST *stkptr)
static int add_dt_subscr (int ast, int *subs, int numdim)
static void ast_replace_index (int old, int new)
static ACL * acl_rewrite_asts (ACL *aclp)
static int gen_null_intrin ()
static int _constructf90 (int base_id, int in_indexast, bool in_array, ACL *aclp)
ACL * mk_init_intrinsic (AC_INTRINSIC init_intr)
static ACL * mk_ulbound_intrin (AC_INTRINSIC intrin, int ast)
static ACL * mk_transpose_intrin (int ast)
static ACL * mk_reshape_intrin (int ast)
static ACL * mk_shape_intrin (int ast)
static ACL * mk_size_intrin (int ast)
static ACL * mk_transfer_intrin (int ast)
static ACL * construct_arg_list (int ast)
static ACL * mk_nonelem_init_intrinsic (AC_INTRINSIC init_intr, int ast, DTYPE dtype)
static ACL * mk_elem_init_intrinsic (AC_INTRINSIC init_intr, int ast, DTYPE dtype, int parent_acltype)
static AC_INTRINSIC get_ac_intrinsic (int ast)
static ACL * construct_intrinsic_acl (int ast, DTYPE dtype, int parent_acltype)
static int get_ast_op (int op)
static int get_ac_op (int ast)
static ACL * eval_do_idx (int ast)
ACL * construct_acl_from_ast (int ast, DTYPE dtype, int parent_acltype)
static int next_member (int member)
ACL * rewrite_acl (ACL *aclp, DTYPE dtype, int parent_acltype)
static int init_types_compatable (SST *istkp, DTYPE dtype, int sptr)
void construct_acl_for_sst (SST *istkp, DTYPE dtype)
ACL * get_acl (int area)
ACL * save_acl (ACL *oldp)
static void put_a_init_tree (int ast, int dinit_array)
static char * make_structkwd_str (DTYPE dtype, int *num_of_member, int *is_extend)
void clean_struct_default_init (int sptr)
int has_init_value (SPTR sptr)
static ACL * rewrite_typeinit_to_sconst (ACL *ict)
void dup_struct_init (int new_sptr, int old_sptr)
Duplicate a derived type component's default initializations.
void save_struct_init (ACL *ict)
ACL * all_default_init (DTYPE dtype)
Check whether derived type has components with default initializations.
static ACL * get_exttype_list (int cnt)
static int set_exttype_list (ACL *aclp)
static int get_exttype_default (DTYPE dtype, int pos)
static LOGICAL get_keyword_components (ACL *in_aclp, int cnt, char *kwdarg, DTYPE dtype, int is_extend)
void chk_struct_constructor (ACL *in_aclp)
int init_derived_w_acl (int in_sptr, ACL *sconst)
static void append_init_list (ASTLIST *target, ASTLIST *src)
static void add_init (ASTLIST *list, int left, DTYPE dtype, int sptr)
static INT const_eval (int ast)
static int dinit_getval (int ast, DTYPE dtype)
static int dinit_getval1 (int ast, DTYPE dtype)
static int unop_init_list (int llist, int optype)
static int binop_init_list (int llist, int rlist, int lop, int rop, int optype)
static void add_subscript_list (ASTLIST *list, int ast, int arraylist, int ssval[], int ndim)
static void build_subscript_list (ASTLIST *list, int ast, int arraylist, int ssval[], int sslist[], int dim, int ndim)
static void build_array_list (ASTLIST *list, int ast, DTYPE dtype, int sptr)
static void add_array_init (ASTLIST *list, int ast, DTYPE dtype, int sptr)
static ACL * dinit_fill_struct (ASTLIST *list, ACL *aclp, int sdtype, int sptr, int memberlist, int init_single)
void dinit_struct_param (SPTR sptr, ACL *sconst, DTYPE dtype)
ACL * dinit_struct_vals (ACL *sconst, DTYPE dtype, SPTR component_sptr)
In DATA statement, do the stuff in dinit_struct_const in two steps.
VAR * dinit_varref (SST *stkp)
Create an initialization node for a variable reference in a data statement.
SPTR get_temp (DTYPE dtype)
Get a compiler temporary of any scalar dtype.
DTYPE get_temp_dtype (DTYPE dtype, int expr)
SPTR get_itemp (DTYPE dtype)
static void allocate_temp (SPTR sptr)
SPTR get_arr_temp (DTYPE dtype, LOGICAL nodesc, LOGICAL alloc_deferred, LOGICAL constructor)
Get a compiler array temporary of type dtype.
SPTR get_adjlr_arr_temp (DTYPE dtype)
Get a compiler-created allocatable array temp to represent the result of run-time function computing the adjustl/adjustr intrinsic.
SPTR get_shape_arr_temp (int arg)
Get a compiler array temporary of from a shape of an ast.
SPTR get_ch_temp (DTYPE dtype)
Get a character compiler temporary of type dtype.
int need_alloc_ch_temp (DTYPE dtype)
int sem_strcmp (const char *str, const char *pattern)
Compare str and pattern like strcmp() but ignoring the case of str. pattern is all lower case.
LOGICAL sem_eq_str (int con, const char *pattern)
Return TRUE if fortran character constant is equal to pattern (pattern is always uppercase).
int sem_tempify (SST *stkptr)
Allocate a temporary, assign it the value, and return the assignment ast.
void add_case_range (int doif, int lc, int uc)
Update the SWEL list for a SELECTCASE construct represented by the doif structure.
int _i4_cmp (int l, int r)
Compare functions whose arguments are pointers to ST_CONST symbol table entries.
int _i8_cmp (int l, int r)
int _char_cmp (int l, int r)
int _nchar_cmp (int l, int r)
LOGICAL not_in_forall (const char *stmttype)
Check if we are currently in a block FORALL scope; if so, issue an error message.
LOGICAL cuda_enabled (const char *at_or_near)
If we are accepting cuda syntax return TRUE. Otherwise issue an error message and return FALSE.
LOGICAL in_device_code (int sptr)
static void add_to_list (ACL *val, ACL **root)
static INT get_int_from_init_conval (ACL *aclp)
static ACL * eval_ishft (ACL *arg, DTYPE dtype)
static ACL * eval_ichar (ACL *arg, DTYPE dtype)
static ACL * eval_char (ACL *arg, DTYPE dtype)
static ACL * eval_int (ACL *arg, DTYPE dtype)
static ACL * eval_fltconvert (ACL *arg, DTYPE dtype)
static ACL * eval_abs (ACL *arg, DTYPE dtype)
static ACL * eval_scale (ACL *arg, DTYPE dtype)
static ACL * eval_merge (ACL *arg, DTYPE dtype)
static bool cmp_acl (DTYPE dtype, ACL *x, ACL *y, bool want_max, bool back)
static bool incr_index (INDEX *index)
static unsigned get_offset_without_dim (INDEX *index, unsigned dim)
static DTYPE mk_dtype_without_dim (INDEX *index, unsigned dim, DTYPE elem_dtype)
static ACL * get_minmax_val (DTYPE dtype, bool want_max)
static ACL * convert_acl_dtype (ACL *head, int oldtype, int newtype)
static ACL * do_eval_minval_or_maxval (INDEX *index, DTYPE elem_dt, DTYPE loc_dt, ACL *elems, unsigned dim, ACL *mask, bool back, AC_INTRINSIC intrin)
static ACL * eval_minval_or_maxval (ACL *arg, DTYPE dtype, AC_INTRINSIC intrin)
static ACL * eval_min_or_max (ACL *arg, DTYPE dtype, LOGICAL want_max)
static ACL * eval_nint (ACL *arg, DTYPE dtype)
static ACL * eval_floor (ACL *arg, DTYPE dtype)
static ACL * eval_ceiling (ACL *arg, DTYPE dtype)
static ACL * eval_mod (ACL *arg, DTYPE dtype)
static ACL * eval_repeat (ACL *arg, DTYPE dtype)
static void transfer_store (INT conval, DTYPE dtype, char *destination)
static INT transfer_load (DTYPE dtype, char *source)
static ACL * eval_transfer (ACL *arg, DTYPE dtype)
static ACL * eval_len_trim (ACL *arg)
static ACL * eval_selected_real_kind (ACL *arg)
static ACL * eval_selected_int_kind (ACL *arg)
static ACL * eval_selected_char_kind (ACL *arg)
static ACL * eval_scan (ACL *arg)
static ACL * eval_verify (ACL *arg)
static ACL * eval_index (ACL *arg)
static ACL * eval_trim (ACL *arg, DTYPE dtype)
static ACL * eval_adjustl (ACL *arg)
static ACL * eval_adjustr (ACL *arg)
static ACL * eval_shape (ACL *arg, DTYPE dtype)
static ACL * eval_size (ACL *arg)
static ACL * eval_ul_bound (ACL *arg)
static int copy_initconst_to_array (ACL **arr, ACL *c, int count)
static ACL * eval_reshape (ACL *arg, DTYPE dtype, LOGICAL transpose)
static ACL * eval_null (int sptr)
static ACL * eval_sqrt (ACL *arg, DTYPE dtype)
static ISZ_T eval_sub_index (int dim)
static int eval_sb (int d)
static ACL * eval_const_array_section (ACL *lop, int ldtype)
static ACL * eval_const_array_triple_section (ACL *curr_e)
static void mk_cmp (ACL *c, int op, INT l_conval, INT r_conval, int rdtype, int dt)
static ACL * eval_init_op (int op, ACL *lop, DTYPE ldtype, ACL *rop, DTYPE rdtype, SPTR sptr, DTYPE dtype)
ACL * eval_init_expr (ACL *e)
VAR * gen_varref_var (int ast, DTYPE dtype)
SPTR get_dtype_init_template (DTYPE dtype)
Process an AC_TYPEINIT.
void gen_derived_type_alloc_init (ITEM *itemp)
void check_dealloc_clauses (ITEM *list, ITEM *spec)
void check_alloc_clauses (ITEM *list, ITEM *spec, int *srcast, int *mold_or_src)
int gen_alloc_dealloc (int stmtyp, int object, ITEM *spec)
int check_etmp (SST *stkp)
If temps were allocated while processing the expression, the expression needs to be assigned to a temp, the allocatable temps need to be deallocated, and the use of the expression is replaced by the temp.
void gen_dealloc_etmps (void)
void check_and_add_auto_dealloc_from_ast (int ast)
void check_and_add_auto_dealloc (int sptr)
void add_auto_dealloc (int sptr)
void add_type_param_initialize (int sptr)
void add_auto_finalize (int sptr)
int gen_finalization_for_sym (int sptr, int std, int memAst)
static int get_parm_ast (int parent, SPTR sptr, DTYPE dtype)
static int remove_parent_from_ast (int ast)
int add_parent_to_bounds (int parent, int ast)
int fix_mem_bounds (int parent, int mem)
int fix_mem_bounds2 (int parent, int mem)
static int insert_assign (int lhs, int rhs, int std)
static int get_header_member (int sdsc_ast, int info)
static int size_of_dtype (DTYPE dtype, SPTR sptr, int memberast)
int init_sdsc (int sptr, DTYPE dtype, int before_std, int parent_sptr)
int init_sdsc_bounds (SPTR sptr, DTYPE dtype, int before_std, SPTR parent_sptr, int subscr, int td_ast)
Similar to init_sdsc() above, but it's also used to initialize a descriptor's bounds from a subscript expression.
static int gen_kind_parm_assignments (SPTR sptr, DTYPE dtype, int std, int flag)
void fix_type_param_members (SPTR sptr, DTYPE dtype)
void gen_type_initialize_for_sym (SPTR sptr, int std, int flag, DTYPE dtype2)
static void gen_alloc_mem_initialize_for_sym2 (int sptr, int std, int ast, int visit_flag)
void gen_alloc_mem_initialize_for_sym (int sptr, int std)
static void __gen_conditional_dealloc (int do_cond, int dealloc_item, int after, int test_presence)
void gen_conditional_dealloc (int do_cond, int dealloc_item, int after)
int gen_conditional_alloc (int cond, int alloc_item, int after)
void gen_conditional_dealloc_for_sym (int sptr, int std)
int gen_dealloc_for_sym (int sptr, int std)
void gen_automatic_reallocation (int lhs, int rhs, int std)
Generate (re)allocation code for deferred length character objects and traditional character objects that are allocatable scalars.
void dummy_program ()
Check whether there is a subprogram statement; if not, create a dummy program symbol, and use that as the program.
static void rw_host_state (int wherefrom, int(*p_rw)(), FILE *fd)
void save_host_state (int wherefrom)
Called from semant.c to save the semant, sym, dtype, ast, and other 'state' information from a host routine for internal subprograms, for 'pass 1'. Also, for 'pass 2', save_host_state is called to overwrite the semant state information.
static void fix_symtab ()
void restore_host_state (int whichpass)
Called at the end of an internal subprogram.
void restore_internal_subprograms (void)
Called at the beginning of a subprogram in pass 2.
void reset_internal_subprograms ()
void save_module_state1 ()
Called at a CONTAINS clause.
void save_module_state2 ()
void save_imported_modules_state ()
void restore_imported_modules_state ()
void module_must_hide_this_symbol (int sptr)
void restore_module_state ()
Called at start of module-contained subprogram, restores state. If this is the first 'restore' since the last 'reset', the 'module append' file is full and needs to be imported.
void reset_module_state ()
Called at the end of a module-contained subprogram; rearranges the data structures for the module.
int have_module_state ()
void sem_fini (void)
Compilation is finished - deallocate storage, close files, etc.
void sem_set_storage_class (int sptr)
void dmp_var (VAR *var, int indent, FILE *f)
void dvar (VAR *var)
void dmp_acl (ACL *acl, int indent)
int mp_create_bscope (int reuse)
int mp_create_escope ()
int enter_lexical_block (int gen_debug)
void exit_lexical_block (int gen_debug)
void sem_err104 (int df, int lineno, const char *str)
void sem_err105 (int df)
void _dmp_doif (int df, FILE *f)
void dmp_doif (FILE *f)
LOGICAL is_alloc_ast (int ast)
LOGICAL is_dealloc_ast (int ast)
LOGICAL is_alloc_std (int std)
LOGICAL is_dealloc_std (int std)
int mk_set_type_call (int arg0, int arg1, LOGICAL intrin_type)
Creates an ast that represents a call to a set type runtime routine.
int gen_set_type (int dest_ast, int src_ast, int std, LOGICAL insert_before, LOGICAL intrin_type)
Generates calls to RTE_set_type() or RTE_set_intrin_type() which set the type descriptor field of an object's descriptor.
Variables
static int temps_ctr [3]
static _ACS acs
static int acl_array_num = 0
static const char * _iexpr_op []
static int cw_array_num = 0
static int max_cw_array_num = 0
static int ALLOCATE_ARRAYS = TRUE
static int sub_i = 7
static int tmpids [MAXDIMS]
static int oldindex [MAXDIMS]
static int newindex [MAXDIMS]
static int numindex
static int dinit_array = 0
static struct_init dt_init = {0, 0, NULL, NULL}
static LOGICAL out_of_elements_message
struct {
ACL * root
ACL * roottail
ACL * arrbase
int ndims
struct {
DTYPE dtype
ISZ_T idx
ACL * subscr_base
ISZ_T lowb
ISZ_T upb
ISZ_T stride
} sub [MAXDIMS]
struct {
ISZ_T lowb
ISZ_T upb
ISZ_T mplyr
} dim [MAXDIMS]
} sb
static int firstalloc
static FILE * state_file = NULL
static FILE * state_append_file = NULL
static int saved_symavl = 0
static int saved_astavl = 0
static int saved_dtyavl = 0
static LOGICAL state_still_pass_one = FALSE
static LOGICAL state_append_file_full = FALSE
static long state_file_position = 0
static int state_last_routine = 0
static char * saved_labels = NULL
static int saved_labels_size = 0
static int saved_labels_avail = 0
static int saved_labels_pos = 0
static FILE * modstate_file = NULL
static FILE * modstate_append_file = NULL
static int modsaved_symavl
static int modsaved_astavl
static int modsaved_dtyavl
static int modstate_append_file_full = 0
static int mod_clear_init = 0
static LOGICAL modsave_ieee_features
static FILE * modsave_file = NULL
static int module_must_hide_this_symbol_sptr = 0
static const char * di_name []
Detailed Description
Utility routines used by Fortran Semantic Analyzer.
Definition in file semutil2.c.
Macro Definition Documentation
DEFAULT_DIM_SIZE
#define DEFAULT_DIM_SIZE 127
DTC_ACL
#define DTC_ACL (i) dt_init.dt_acl[i]
Definition at line 5421 of file semutil2.c.
DTC_ACL_HEAD
#define DTC_ACL_HEAD dt_init.dt_acl
Definition at line 5419 of file semutil2.c.
DTC_DEFAULT
#define DTC_DEFAULT (i) dt_init.default_acl[i]
Definition at line 5420 of file semutil2.c.
DTC_DEFAULT_CNT
#define DTC_DEFAULT_CNT dt_init.default_count
Definition at line 5422 of file semutil2.c.
DTC_DEFAULT_HEAD
#define DTC_DEFAULT_HEAD dt_init.default_acl
Definition at line 5418 of file semutil2.c.
DTC_DT_CNT
#define DTC_DT_CNT dt_init.dt_count
Definition at line 5423 of file semutil2.c.
FPINTRIN1
#define FPINTRIN1 (iname, ent, fscutil, dscutil, qscutil)
Definition at line 10759 of file semutil2.c.
FPINTRIN2
#define FPINTRIN2 (iname, ent, fscutil, dscutil, qscutil)
Definition at line 10883 of file semutil2.c.
GET_DBLE
#define GET_DBLE (x, y)
Value:
  x[0] = CONVAL1G(y);  \
  x[1] = CONVAL2G(y)
Definition at line 8785 of file semutil2.c.
GET_QUAD
#define GET_QUAD (x, y)
Value:
  x[0] = CONVAL1G(y);  \
  x[1] = CONVAL2G(y);  \
  x[2] = CONVAL3G(y);  \
  x[3] = CONVAL4G(y);
Definition at line 8788 of file semutil2.c.
GETVALI64
#define GETVALI64 (x, b)
Value:
  x[0] = CONVAL1G(b);   \
  x[1] = CONVAL2G(b);
Definition at line 8793 of file semutil2.c.
INTINTRIN2
#define INTINTRIN2 (iname, ent, op)
Value:
  static ACL *ent(ACL *arg, DTYPE dtype)                         \
  {                                                              \
    ACL *arg1 = eval_init_expr_item(arg);                        \
    ACL *arg2 = eval_init_expr_item(arg->next);                  \
    ACL *rslt = clone_init_const(arg1, TRUE);                    \
    arg1 = rslt->id == AC_ACONST ? rslt->subc : rslt;            \
    arg2 = arg2->id == AC_ACONST ? arg2->subc : arg2;            \
    for (; arg1; arg1 = arg1->next, arg2 = arg2->next) {         \
      int con1 = arg1->conval;                                   \
      int con2 = arg2->conval;                                   \
      int num1[2], num2[2], res[2], conval;                      \
      if (DT_ISWORD(arg1->dtype)) {                              \
        num1[0] = 0, num1[1] = con1;                             \
      } else {                                                   \
        num1[0] = CONVAL1G(con1), num1[1] = CONVAL2G(con1);      \
      }                                                          \
      if (DT_ISWORD(arg2->dtype)) {                              \
        num2[0] = 0, num2[1] = con2;                             \
      } else {                                                   \
        num2[0] = CONVAL1G(con2), num2[1] = CONVAL2G(con2);      \
      }                                                          \
      res[0] = num1[0] op num2[0];                               \
      res[1] = num1[1] op num2[1];                               \
      conval = DT_ISWORD(dtype) ? res[1] : getcon(res, DT_INT8); \
      arg1->conval = conval;                                     \
      arg1->dtype = dtype;                                       \
    }                                                            \
    return rslt;                                                 \
  }
Definition at line 8655 of file semutil2.c.
KANJI_BLANK
#define KANJI_BLANK 0xA1A1
TEMPS_CTR
#define TEMPS_CTR (n) (temps_ctr[n]++)
Definition at line 84 of file semutil2.c.
TEMPS_STK
#define TEMPS_STK (n) ((sem.doif_depth << 10) + temps_ctr[n]++)
Definition at line 85 of file semutil2.c.
THRESHHOLD
#define THRESHHOLD 20
Definition at line 2580 of file semutil2.c.
TRACE_EVAL_SB
#define TRACE_EVAL_SB 0
Typedef Documentation
IDO_INFO
typedef struct _ido_info IDO_INFO
struct_init
typedef struct struct_init struct_init
Function Documentation
__gen_conditional_dealloc()
static void __gen_conditional_dealloc (int do_cond, int dealloc_item, int after, int test_presence) static
Definition at line 13241 of file semutil2.c.
References A_OPTYPEP, A_TKNP, add_stmt_after(), after, argt, ARGT_ARG, ast, ast_intr(), STB::dt_log, getsymbol(), mk_argt(), mk_func_node(), mk_id(), mk_stmt(), present, stb, std, and STB::user.
Referenced by gen_conditional_dealloc(), and gen_conditional_dealloc_for_sym().
_can_fold()
static LOGICAL _can_fold (int ast) static
Definition at line 2393 of file semutil2.c.
References _can_fold(), A_OPTYPEG, ASD_NDIM, ASD_SUBS, ast, b, DT_ISINT, FALSE, i, ndim, OP_ADD, OP_DIV, OP_MUL, OP_SUB, PARAMVALG, sptr, ss, and TRUE.
Referenced by _can_fold(), compute_size_expr(), construct_acl_from_ast(), mk_size_intrin(), and mk_ulbound_intrin().
_char_cmp()
int _char_cmp (int l, int r)
Definition at line 8401 of file semutil2.c.
Referenced by semant3().
_compute_width()
static void _compute_width (int in_array, ACL * aclp) static
Definition at line 1335 of file semutil2.c.
References _compute_width(), AC_ACONST, AC_AST, AC_CONST, AC_EXPR, AC_IDO, AC_IEXPR, AC_REPEAT, AC_SCONST, _acl::array_i, _acl::ast, compute_width_dtype(), cw_array_num, _acl::dtype, dtype, _acl::id, interr(), max_cw_array_num, _acl::next, NULL, SST_DTYPEG, _acl::stkp, _acl::subc, _acl::u1, and _acl::u2.
Referenced by _compute_width(), and compute_width().
_constructf90()
static int _constructf90 (int base_id, int in_indexast, bool in_array, ACL * aclp) static
Definition at line 2897 of file semutil2.c.
References _constructf90(), A_OPTYPEG, AC_ACONST, AC_AST, AC_EXPR, AC_IDO, AC_IEXPR, AC_SCONST, acl_rewrite_asts(), acs, ADD_DEFER, add_dt_subscr(), add_nullify_ast(), add_ptr_assign(), add_shape_rank(), add_shape_spec(), add_stmt(), add_stmt_before(), add_subscript(), SEM::alloc_std, apply_shape_subscripts(), argt, ARGT_ARG, SEM::arrfn, ast, _acl::ast, sst::ast, ast_is_sym(), ast_replace(), ast_replace_index(), ast_rewrite(), ast_rewrite_indices(), ast_unvisit(), ast_visit(), astb, ASTB::bnd, chk_pointer_target(), clear_element_cnt(), clone_init_const(), cnt, DBGBIT, DDTG, dest, DI_DO, do_begin(), do_end(), _acl::doinfo, DT_INT, DT_PTR, SEM::dtemps, DTY, _acl::dtype, dtype, ASTB::dtype, error(), extent_of_shape(), FALSE, _ACS::func_in_do, gbl, gen_alloc_dealloc(), gen_null_intrin(), GET_ACL, get_element_cnt(), get_static_descriptor(), get_static_type_descriptor(), get_struct_default_init(), get_subscripting_tmp(), get_temp(), getccsym(), getcctmp_sc(), has_layout_desc(), i, ASTB::i0, ASTB::i1, _acl::id, incr_element_cnt(), incr_tmp(), DOINFO::index_var, init_derived_w_acl(), init_sptr_w_acl(), interr(), _ACS::is_const, is_iso_cptr(), is_unl_poly(), itemp, _ACS::level, DOINFO::limit_expr, MAXDIMS, memsym_of_ast(), _std_range::mid, mk_argt(), mk_assn_stmt(), mk_binop(), mk_cval1(), mk_func_node(), mk_id(), mk_isz_cval(), mk_member(), mk_shape(), mk_stmt(), mk_unop(), mkexpr(), mkexpr2(), mkexpr_assign_temp(), mkmember(), mkRteRtnNm(), move_range_after(), ndim, NEED_DOIF, xyyz::next, _acl::next, no_data_components(), NOSYM, NULL, numindex, ASTB::one, OP_ADD, OP_SUB, OP_VAL, SEM::p_dealloc, pop_subscript(), printacl(), push_subscript(), SEM::return_value, RTE_poly_asn, RTE_realloc_arr_in_impiled_do, S_IDENT, S_LVALUE, sem, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, SEM::sptr, src, SST_ASTG, SST_DTYPEG, SST_IDG, SST_LSYMG, SST_SYMG, _std_range::start, std, STD_AST, STD_LAST, STD_NEXT, _acl::std_range, _acl::stkp, stmt, _acl::subc, sym_mkfunc(), sym_mkfunc_nodesc(), SYMNAME, tmp, TRUE, _acl::u1, _acl::u2, void(), and XBIT.
Referenced by _constructf90(), and constructf90().
_dinit_acl()
static void _dinit_acl (ACL * aclp, LOGICAL optimpldo) static
Definition at line 5269 of file semutil2.c.
References _dinit_acl(), AC_ACONST, AC_AST, AC_EXPR, AC_IDO, AC_REPEAT, AC_SCONST, sst::acl, ast, _acl::ast, astb, ASTB::bnd, sst::cnval, CONVAL2G, count, DOINFO::count, _acl::count, DOSTACK::currval, dinit_array, DINIT_ENDARY, DINIT_ENDTYPE, dinit_eval(), dinit_put(), DINIT_REPEAT, DINIT_STARTARY, DINIT_STR, DINIT_TYPEDEF, _acl::doinfo, SEM::dostack, DT_ISWORD, DTY, _acl::dtype, dtype, ASTB::dtype, errsev(), FALSE, getcon(), _acl::id, DOINFO::index_var, DOINFO::init_expr, interr(), last, MAX_DOSTACK, _acl::next, NULL, PARAMVALG, put_a_init_tree(), _acl::repeatc, S_IDENT, sem, _acl::size, sptr, DOSTACK::sptr, SST_IDG, DOINFO::step_expr, _acl::stkp, _acl::subc, SEM::top, TY_BINT, TY_BLOG, TY_CHAR, TY_INT, TY_INT8, TY_LOG, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, _acl::u1, and sst::value.
Referenced by _dinit_acl(), and put_a_init_tree().
_dmp_acl()
static void _dmp_acl (ACL * acl, int indent, FILE * f) static
Definition at line 14294 of file semutil2.c.
References _dmp_acl(), AC_ACONST, AC_AST, AC_CONST, AC_EXPR, AC_ICONST, AC_IDENT, AC_IDO, AC_IEXPR, AC_LIST, AC_REPEAT, AC_SCONST, AC_TYPEINIT, _acl::ast, _acl::doinfo, _acl::dtype, _acl::expr, f, _acl::i, _acl::id, iexpr_op(), indent, DOINFO::index_var, DOINFO::init_expr, _acl::is_const, DOINFO::limit_expr, AEXPR::lop, _acl::next, NULL, AEXPR::op, put_prefix(), _acl::repeatc, AEXPR::rop, _acl::size, _acl::sptr, SST_IDG, DOINFO::step_expr, _acl::stkp, _acl::subc, and _acl::u1.
Referenced by _dmp_acl(), and dmp_acl().
_dmp_doif()
void _dmp_doif (int df, FILE * f)
Definition at line 14621 of file semutil2.c.
References collapse, df, DI_B, DI_DO, DI_DOINFO, DI_ID, DI_LINENO, DI_MAXID, DI_NAME, di_name, DI_NEST, f, i, and NULL.
Referenced by dmp_doif().
_dumpacl()
static void _dumpacl (int nest, ACL * aclp, FILE * f) static
Definition at line 1162 of file semutil2.c.
References _dumpacl(), AC_ACONST, AC_AST, AC_CONST, AC_CONVAL, AC_EXPR, AC_IDO, AC_IEXPR, AC_REPEAT, AC_SCONST, ast, _acl::ast, _acl::conval, DOINFO::count, _acl::count, _acl::doinfo, DTY, _acl::dtype, dtype, _acl::expr, f, _acl::id, iexpr_op(), DOINFO::index_var, DOINFO::init_expr, DOINFO::limit_expr, _acl::next, NULL, AEXPR::op, printast(), S_ACONST, S_CONST, S_EXPR, S_IDENT, S_SCONST, sptr, SST_ASTG, SST_DTYPEG, SST_IDG, SST_SYMG, stb, DOINFO::step_expr, _acl::stkp, _acl::subc, SYMNAME, and _acl::u1.
Referenced by _dumpacl(), and dumpacl().
_i4_cmp()
int _i4_cmp (int l, int r)
Compare functions whose arguments are pointers to ST_CONST symbol table entries.
Returns
a number less than, equal to, or greater than 0, depending on the comparison
Definition at line 8375 of file semutil2.c.
Referenced by llvm_omp_sched(), and semant3().
_i8_cmp()
int _i8_cmp (int l, int r)
Definition at line 8389 of file semutil2.c.
Referenced by llvm_omp_sched(), and semant3().
_mk_arrdsc()
static DTYPE _mk_arrdsc (int start_of_base) static
Definition at line 294 of file semutil2.c.
References AD_ADJARR, AD_ASSUMSHP, AD_ASSUMSZ, AD_DEFER, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_MLPYR, AD_NOBOUNDS, AD_NUMELM, AD_UPAST, AD_UPBD, AD_ZBASE, SEM::arrdim, ast, astb, ASTB::bnd, SEM::bounds, chk_kind_parm_expr(), chk_len_parm_expr(), CNULL, INTERF::currsub, dtype, ASTB::dtype, error(), errsev(), FALSE, gbl, get_array_dtype(), i, IN_MODULE, IN_MODULE_SPEC, SEM::interf_base, SEM::interface, is_parameter_context(), ISZ_T, mk_bnd_ast(), mk_bnd_int(), mk_isz_cval(), mk_mlpyr_expr(), mk_shared_bnd_ast(), mk_shared_extent(), mk_zbase_expr(), ASTB::one, runtime_array(), S_CONST, S_EXPR, sem, SEM::stag_dtype, TRUE, valid_kind_parm_expr(), and zbase.
Referenced by mk_arrdsc().
_nchar_cmp()
int _nchar_cmp (int l, int r)
Definition at line 8411 of file semutil2.c.
Referenced by semant3().
_printacl()
static void _printacl (int in_array, ACL * aclp, FILE * f) static
Definition at line 1059 of file semutil2.c.
References _printacl(), AC_ACONST, AC_AST, AC_EXPR, AC_IDO, AC_IEXPR, AC_REPEAT, AC_SCONST, acl_array_num, _acl::ast, compute_width_dtype(), _acl::count, DTY, _acl::dtype, dtype, _acl::expr, f, _acl::id, iexpr_op(), interr(), _acl::next, NULL, AEXPR::op, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_SCONST, sptr, SST_DTYPEG, SST_IDG, _acl::stkp, _acl::subc, SYMNAME, and _acl::u1.
Referenced by _printacl(), and printacl().
acl_rewrite_asts()
static ACL * acl_rewrite_asts (ACL * aclp) static
Definition at line 2775 of file semutil2.c.
References AC_ACONST, AC_AST, AC_EXPR, AC_IDO, AC_REPEAT, AC_SCONST, acl_rewrite_asts(), ast, _acl::ast, ast_rewrite(), CNULL, DOINFO::count, _acl::doinfo, error(), GET_ACL, get_doinfo(), _acl::id, DOINFO::init_expr, interr(), DOINFO::limit_expr, NEW, next, _acl::next, NULL, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_LVALUE, S_SCONST, sst, SST_ASTG, SST_ASTP, SST_IDG, SST_SIZE, DOINFO::step_expr, _acl::stkp, _acl::subc, and _acl::u1.
Referenced by _constructf90(), and acl_rewrite_asts().
add_alloc_mem_initialize()
static void add_alloc_mem_initialize (int sptr) static
Definition at line 12314 of file semutil2.c.
References SEM::alloc_mem_initialize, allocatable_member(), DTY, getitem(), itemp, sem, and sptr.
Referenced by init_derived_w_acl().
add_array_init()
static void add_array_init (ASTLIST * list, int ast, DTYPE dtype, int sptr) static
Definition at line 7320 of file semutil2.c.
add_auto_array()
static void add_auto_array (int sptr) static
Definition at line 14200 of file semutil2.c.
References AD_DPTR, AD_NOBOUNDS, add_autobj(), and sptr.
Referenced by sem_set_storage_class().
add_auto_char()
static void add_auto_char (int sptr) static
Definition at line 14211 of file semutil2.c.
References add_autobj(), and sptr.
Referenced by sem_set_storage_class().
add_auto_dealloc()
void add_auto_dealloc (int sptr)
Definition at line 12299 of file semutil2.c.
References SEM::auto_dealloc, getitem(), itemp, sem, and sptr.
Referenced by check_and_add_auto_dealloc(), func_call2(), misc_checks(), and sem_set_storage_class().
add_auto_finalize()
void add_auto_finalize (int sptr)
Definition at line 12354 of file semutil2.c.
References SEM::auto_finalize, getitem(), itemp, sem, and sptr.
Referenced by semant1().
add_autobj()
static void add_autobj (int sptr) static
Definition at line 14218 of file semutil2.c.
References gbl, next, NOSYM, and sptr.
Referenced by add_auto_array(), and add_auto_char().
add_case_range()
void add_case_range (int doif, int lc, int uc)
Update the SWEL list for a SELECTCASE construct represented by the doif structure.
A new SWEL item is created for a case value or a range of case values denoted by the arguments lc and uc. The order of the items in the list will correspond to the case values in ascending order.
Kind of case lc uc
case (:c) c -1
case (c) c 0 (c is a sym pointer)
case (c:) c 1
case (c:d) c d (c and d are sym pointers)
Definition at line 8279 of file semutil2.c.
Referenced by semant3().
add_dt_subscr()
static int add_dt_subscr (int ast, int * subs, int numdim) static
Definition at line 2688 of file semutil2.c.
References add_dt_subscr(), ADD_NUMDIM, ASD_NDIM, ASD_SUBS, assert, ast, DTY, dtype, i, interr(), MAXDIMS, mem(), mk_member(), mk_subscr(), ndim, and parent.
Referenced by _constructf90(), and add_dt_subscr().
add_etmp()
static void add_etmp (int sptr) static
Definition at line 792 of file semutil2.c.
References SEM::etmp_list, getitem(), sem, sptr, and x.
Referenced by add_p_dealloc_item().
add_init()
static void add_init (ASTLIST * list, int left, DTYPE dtype, int sptr) static
Definition at line 6552 of file semutil2.c.
References ast, list, mk_init(), and sptr.
Referenced by add_subscript_list(), and build_array_list().
add_p_dealloc_item()
void add_p_dealloc_item (int sptr)
Definition at line 718 of file semutil2.c.
References add_etmp(), DI_FORALL, DI_ID, SEM::doif_depth, getitem(), itemp, mk_id(), SEM::p_dealloc, sem, sptr, and SEM::use_etmps.
Referenced by func_call2(), gen_allocate_array(), and ptrfunc_call().
add_parent_to_bounds()
int add_parent_to_bounds (int parent, int ast)
Definition at line 12507 of file semutil2.c.
References A_OPTYPEG, add_parent_to_bounds(), ARGT_ARG, ast, get_parm_ast(), i, interr(), parent, and sym_of_ast().
Referenced by add_parent_to_bounds(), copy_surrogate_to_bnds_vars(), fix_mem_bounds(), fix_mem_bounds2(), fix_type_param_members(), and gen_kind_parm_assignments().
add_subscript()
static int add_subscript (int base_id, int indexast, DTYPE dtype) static
Definition at line 2499 of file semutil2.c.
References acs, dest, mk_subscr(), sub_i, and _ACS::subs.
Referenced by _constructf90().
add_subscript_list()
static void add_subscript_list (ASTLIST * list, int ast, int arraylist, int ssval[], int ndim) static
Definition at line 7053 of file semutil2.c.
References a, add_init(), assert, ast, CONVAL2G, DDTG, i, lb, list, ndim, offset, SHD_LWB, SHD_NDIM, SHD_UPB, ss, and ub.
Referenced by build_subscript_list().
add_to_list()
static void add_to_list (ACL * val, ACL ** root) static
Definition at line 8478 of file semutil2.c.
Referenced by eval_array_constructor(), eval_do(), eval_init_expr(), eval_init_op(), and eval_sb().
add_type_param_initialize()
void add_type_param_initialize (int sptr)
Definition at line 12334 of file semutil2.c.
References DTY, getitem(), has_type_parameter(), itemp, sem, sptr, and SEM::type_initialize.
Referenced by semant1().
all_default_init()
ACL * all_default_init (DTYPE dtype)
Check whether derived type has components with default initializations.
Parameters
dtype is the derived type we want to check.
Returns
pointer to first default initializer, else NULL.
Definition at line 5653 of file semutil2.c.
References all_default_init(), clone_init_const(), DTC_DEFAULT, DTC_DEFAULT_CNT, DTY, is_tbp_or_final(), mem(), NOSYM, and NULL.
Referenced by all_default_init(), lower_symbol(), and semant2().
allocate_temp()
static void allocate_temp (SPTR sptr) static
Definition at line 7894 of file semutil2.c.
append_init_list()
static void append_init_list (ASTLIST * target, ASTLIST * src) static
Definition at line 6541 of file semutil2.c.
References ASTLIST::head, src, and ASTLIST::tail.
apply_shape_subscripts()
static int apply_shape_subscripts (int base_id, int shp, DTYPE dtype) static
Definition at line 2510 of file semutil2.c.
References ast, dest, i, MAXDIMS, mk_subscr(), mk_triple(), ndim, SHD_LWB, SHD_NDIM, SHD_STRIDE, and SHD_UPB.
Referenced by _constructf90().
ast_replace_index()
static void ast_replace_index (int old, int new) static
Definition at line 2754 of file semutil2.c.
References newindex, numindex, and oldindex.
Referenced by _constructf90().
ast_rewrite_indices()
static int ast_rewrite_indices (int ast) static
Definition at line 2762 of file semutil2.c.
References ast, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), i, newindex, numindex, and oldindex.
Referenced by _constructf90(), and mkexpr_assign_temp().
binop_init_list()
static int binop_init_list (int llist, int rlist, int lop, int rop, int optype) static
Definition at line 6963 of file semutil2.c.
References binop_init_list(), interr(), last, list, mk_binop(), mk_init(), optype(), and re.
Referenced by binop_init_list().
build_array_list()
static void build_array_list (ASTLIST * list, int ast, DTYPE dtype, int sptr) static
Definition at line 7124 of file semutil2.c.
References a, add_init(), ASD_NDIM, assert, ast, build_array_list(), d, DDTG, SEM::dinit_error, dtype, errsev(), i, interr(), list, lower(), MAXDIMS, ndim, PARAMVALG, past(), sem, sptr, stride, TRUE, and upper().
Referenced by build_array_list().
build_subscript_list()
static void build_subscript_list (ASTLIST * list, int ast, int arraylist, int ssval[], int sslist[], int dim, int ndim) static
Definition at line 7098 of file semutil2.c.
References add_subscript_list(), ast, build_subscript_list(), dim, list, and ndim.
Referenced by build_subscript_list().
check_alloc_clauses()
void check_alloc_clauses (ITEM * list, ITEM * spec, int * srcast, int * mold_or_src)
Definition at line 12106 of file semutil2.c.
References CNULL, error(), firstalloc, gbl, ITEM_END, itemp, list, spec, and stat.
Referenced by semant3().
check_and_add_auto_dealloc()
void check_and_add_auto_dealloc (int sptr)
Definition at line 12274 of file semutil2.c.
References add_auto_dealloc(), gbl, RU_FUNC, RU_SUBR, SEM::savall, SEM::scope_level, SEM::scope_stack, sem, sptr, and SCOPESTACK::sptr.
Referenced by check_and_add_auto_dealloc_from_ast(), and semant2().
check_and_add_auto_dealloc_from_ast()
void check_and_add_auto_dealloc_from_ast (int ast)
Definition at line 12266 of file semutil2.c.
References ast, check_and_add_auto_dealloc(), sptr, and sym_of_ast().
Referenced by gen_automatic_reallocation(), mk_ptr_subscr(), and semant3().
check_dealloc_clauses()
void check_dealloc_clauses (ITEM * list, ITEM * spec)
Definition at line 12075 of file semutil2.c.
References CNULL, error(), firstalloc, gbl, ITEM_END, itemp, list, spec, and stat.
Referenced by semant3().
check_dependence_ido()
static void check_dependence_ido (ACL * aclp) static
Definition at line 2046 of file semutil2.c.
References acs, _ACS::aggr_cnt, contains_ast(), _acl::doinfo, _ACS::doinfo, _std_range::end, FALSE, _ACS::ido_level, _ACS::ido_list, DOINFO::init_expr, level(), _ACS::level, DOINFO::limit_expr, _ACS::loop_stmts, _std_range::mid, mk_id(), _ido_info::next, NULL, std, STD_AST, STD_NEXT, _acl::std_range, DOINFO::step_expr, TRUE, _acl::u1, and _acl::u2.
Referenced by compute_size_ido().
check_etmp()
int check_etmp (SST * stkp)
If temps were allocated while processing the expression, the expression needs to be assigned to a temp, the allocatable temps need to be deallocated, and the use of the expression is replaced by the temp.
Definition at line 12232 of file semutil2.c.
References add_stmt(), ast, SEM::etmp_list, FALSE, gen_dealloc_etmps(), NULL, sem, sem_tempify(), SST_ASTG, SEM::use_etmps, and void().
Referenced by gen_logical_if_expr(), semant2(), and semant3().
chk_adjarr()
void chk_adjarr (void)
Definition at line 88 of file semutil2.c.
References arg, aux, cnt, AUX::dpdsc_base, FALSE, gbl, NOSYM, RU_FUNC, RU_PROG, RU_SUBR, RUNTIMEG, to_assumed_shape(), and TRUE.
Referenced by semant1().
chk_constructor()
DTYPE chk_constructor (ACL * aclp, DTYPE dtype)
Check the array constructor and decide the dtype.
It is called when we first recognize an array constructor.
Definition at line 1464 of file semutil2.c.
References AC_ACONST, acs, _ACS::aggr_cnt, SEM::arrdim, _ACS::arrtype, assert, astb, ASTB::bnd, SEM::bounds, BZERO, compute_size(), DBGBIT, SEM::dostack, DTY, _acl::dtype, dtype, ASTB::dtype, _ACS::eltype, FALSE, gbl, SEM::gcvlen, get_type(), ASTB::i1, _acl::id, _acl::is_const, _ACS::is_const, is_deferlenchar_dtype(), mk_arrdsc(), mk_binop(), mk_isz_cval(), OP_ADD, printacl(), restore_dim_specs(), S_CONST, S_EXPR, save_dim_specs(), _ACS::scalar_cnt, sem, _acl::size, _acl::subc, SEM::top, TRUE, TY_CHAR, TY_NCHAR, ASTB::zero, and _ACS::zln.
Referenced by semant2().
chk_struct_constructor()
void chk_struct_constructor (ACL * in_aclp)
Definition at line 6226 of file semutil2.c.
References A_OPTYPEG, AC_ACONST, AC_AST, AC_EXPR, AC_SCONST, ACL_AREA, assert, ast, _acl::ast, check_member(), cmpat_dtype_with_size(), cnt, CNULL, DBGBIT, DDTG, DT_PTR, DTC_ACL, DTY, _acl::dtype, dtype, error(), FREE, gbl, GET_ACL, get_all_descriptors(), get_keyword_components(), get_static_descriptor(), get_struct_default_init(), getitem(), STB::i0, _acl::id, is_illegal_expr_in_init(), is_tbp_or_final(), keyword(), make_structkwd_str(), mk_id(), _acl::next, no_data_components(), NOSYM, NULL, printacl(), _acl::ptrdtype, rank_of(), _acl::repeatc, S_CONST, S_EXPR, S_IDENT, S_LVALUE, set_exttype_list(), SHD_NDIM, _acl::size, sptr, SST_ASTG, SST_ASTP, SST_DTYPEG, SST_DTYPEP, SST_IDG, SST_IDP, SST_LSYMG, SST_LSYMP, SST_SHAPEP, SST_SYMG, SST_SYMP, stb, _acl::stkp, _acl::subc, SYMNAME, and _acl::u1.
Referenced by resolve_generic(), semant1(), and semant2().
clean_struct_default_init()
void clean_struct_default_init (int sptr)
Definition at line 5520 of file semutil2.c.
References DTC_ACL_HEAD, DTC_DEFAULT, DTC_DEFAULT_CNT, DTC_DEFAULT_HEAD, DTC_DT_CNT, FREE, i, NULL, and sptr.
Referenced by semant_init().
clear_element_cnt()
static void clear_element_cnt () static
Definition at line 2539 of file semutil2.c.
References acs, _ACS::element_cnt, and sub_i.
Referenced by _constructf90().
clone_init_const()
static ACL * clone_init_const (ACL * original, int temp) static
Definition at line 8491 of file semutil2.c.
Referenced by _constructf90(), all_default_init(), eval_init_expr(), eval_init_expr_item(), eval_init_op(), eval_sb(), and get_struct_default_init().
clone_init_const_list()
static ACL * clone_init_const_list (ACL * original, int temp) static
Definition at line 8515 of file semutil2.c.
cmp_acl()
static bool cmp_acl (DTYPE dtype, ACL * x, ACL * y, bool want_max, bool back) static
Definition at line 8984 of file semutil2.c.
compute_size()
static void compute_size (bool add_flag, ACL * aclp, DTYPE dtype) static
Definition at line 1801 of file semutil2.c.
References AC_ACONST, AC_AST, AC_EXPR, AC_IDO, AC_SCONST, acs, compute_size(), compute_size_ast(), compute_size_expr(), compute_size_ido(), compute_size_sconst(), SEM::dinit_error, _acl::doinfo, _ido_info::doinfo, _ACS::doinfo, _ACS::end, FALSE, getitem(), _acl::id, _ACS::ido_level, _ACS::ido_list, interr(), _ACS::level, _ACS::loop_stmts, move_range_before(), _acl::next, _ido_info::next, NULL, sem, _ACS::start, _acl::subc, TRUE, and _acl::u1.
Referenced by chk_constructor(), compute_size(), compute_size_ido(), and compute_size_sconst().
compute_size_ast()
static void compute_size_ast (bool add_flag, ACL * aclp, DTYPE dtype) static
Definition at line 1878 of file semutil2.c.
References acs, _acl::ast, DDTG, DTY, dtype, _ACS::eltype, fix_dtype(), get_isz_cval(), _ACS::scalar_cnt, TY_CHAR, TY_NCHAR, _acl::u1, and _ACS::zln.
Referenced by compute_size().
compute_size_expr()
static DTYPE compute_size_expr (bool add_flag, ACL * aclp, DTYPE dtype) static
Definition at line 1905 of file semutil2.c.
References _can_fold(), acs, AD_DPTR, AD_NUMELM, ad_val_of(), adjust_ch_length(), _ACS::aggr_cnt, ast, astb, ASTB::bnd, cngtyp(), CONVAL2G, DDTG, dt, DTY, dtype, ASTB::dtype, _ACS::eltype, eq_dtype(), errsev(), FALSE, fix_dtype(), get_isz_cval(), interr(), _ACS::is_const, is_dtype_runtime_length_char(), _ACS::level, mk_binop(), mkexpr(), OP_ADD, PARAMVALG, S_ACONST, S_CONST, S_EXPR, S_IDENT, S_LVALUE, _ACS::scalar_cnt, size_of_ast(), sptr, SST_ASTG, SST_DTYPEG, SST_IDG, SST_SYMG, _acl::stkp, sym_of_ast(), sz, TY_CHAR, TY_NCHAR, _acl::u1, and _ACS::zln.
Referenced by compute_size().
compute_size_ido()
static void compute_size_ido (bool add_flag, ACL * aclp, DTYPE dtype) static
Definition at line 2181 of file semutil2.c.
References acs, add_stmt(), _ACS::aggr_cnt, ast, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), astb, ASTB::bnd, check_dependence_ido(), compute_size(), contains_ast(), CONVAL2G, DOINFO::count, DOSTACK::currval, DDTG, DI_DO, SEM::dinit_data, SEM::dinit_error, dinit_eval(), do_begin(), do_end(), _acl::doinfo, _ACS::doinfo, ASTB::dtype, FALSE, get_temp(), handle_dependence_ido(), i, DOINFO::index_var, DOINFO::init_expr, _ACS::is_const, _ACS::level, DOINFO::limit_expr, _ACS::loop_stmts, mk_assn_stmt(), mk_binop(), mk_cval(), mk_id(), mk_isz_cval(), NEED_DOIF, NULL, OP_ADD, OP_MUL, _ACS::scalar_cnt, sem, DOSTACK::sptr, DOSTACK::step, DOINFO::step_expr, _acl::subc, sum(), SEM::top, _acl::u1, DOSTACK::upbd, and ASTB::zero.
Referenced by compute_size().
compute_size_sconst()
static void compute_size_sconst (bool add_flag, ACL * aclp, DTYPE dtype) static
Definition at line 2378 of file semutil2.c.
References acs, compute_size(), DTY, _acl::dtype, dtype, _ACS::eltype, FALSE, _ACS::is_const, _ACS::scalar_cnt, and _acl::subc.
Referenced by compute_size().
compute_width()
static int compute_width (ACL * aclp) static
Definition at line 1451 of file semutil2.c.
References _compute_width(), cw_array_num, and max_cw_array_num.
Referenced by constructf90().
compute_width_dtype()
static int compute_width_dtype (DTYPE in_dtype) static
Definition at line 1299 of file semutil2.c.
References compute_width_dtype(), DDTG, DTY, DTYG, NOSYM, sptr, and sum().
Referenced by _compute_width(), _printacl(), and compute_width_dtype().
const_eval()
static INT const_eval (int ast) static
Definition at line 6573 of file semutil2.c.
References A_ARGCNTG, A_OPTYPEG, ADD_LWAST, ADD_NUMELM, ADD_UPAST, ARGT_ARG, ast, cngcon(), CNULL, const_eval(), const_fold(), CONVAL2G, count, SEM::dinit_error, SEM::dostack, DT_INT, DT_ISINT, DT_ISWORD, DTY, error(), errsev(), FLANG_FALLTHROUGH, gbl, get_const_from_ast(), get_int_cval(), i, STB::k1, kanji_char(), lv, lwb, max, min, STB::n_base, negate_const(), OP_ADD, OP_CMP, OP_DIV, OP_EQ, OP_GE, OP_GT, OP_LAND, OP_LE, OP_LEQV, OP_LNEQV, OP_LNOT, OP_LOR, OP_LT, OP_MUL, OP_NE, OP_SUB, OP_XTOI, p, SCFTN_FALSE, SCFTN_TRUE, sem, sign, size_of(), sptr, stb, SYMNAME, sz, term(), tmp, SEM::top, TRUE, upb, val, and XBIT.
Referenced by const_eval(), dinit_getval1(), and get_const_from_ast().
construct_acl_for_sst()
void construct_acl_for_sst (SST * istkp, DTYPE dtype)
Definition at line 5045 of file semutil2.c.
References AC_IEXPR, AC_INTR_CALL, ADD_NUMELM, _acl::ast, construct_acl_from_ast(), CONVAL2G, DDTG, SEM::dinit_error, DTY, _acl::dtype, errsev(), _acl::expr, get_getitem_p(), has_type_parameter(), _acl::id, init_types_compatable(), interr(), no_data_components(), AEXPR::op, SEM::param_struct_constr, _acl::repeatc, rewrite_acl(), S_ACONST, S_CONST, S_EXPR, S_IDENT, S_LVALUE, S_SCONST, sem, sptr, SST_ACLG, SST_ACLP, SST_ASTG, SST_DTYPEG, SST_IDG, SST_SYMG, TRUE, and _acl::u1.
Referenced by convert_ctmp_array_to_param(), fixup_param_vars(), get_param_alias_const(), and semant1().
construct_acl_from_ast()
ACL * construct_acl_from_ast (int ast, DTYPE dtype, int parent_acltype)
Definition at line 4540 of file semutil2.c.
References _can_fold(), AC_ACONST, AC_ARRAYREF, AC_AST, AC_CONV, AC_IDENT, AC_IEXPR, AC_LNOT, AC_MEMBR_SEL, AC_NEG, AC_SCONST, AC_TRIPLE, ADD_NUMELM, ASD_NDIM, ASD_SUBS, ast, _acl::ast, astb, ASTB::bnd, construct_acl_from_ast(), construct_intrinsic_acl(), DDTG, SEM::dinit_error, DTY, _acl::dtype, dtype, ASTB::dtype, SEM::equal_initializer, errsev(), eval_do_idx(), _acl::expr, FLANG_FALLTHROUGH, get_ac_op(), GET_ACL, getitem(), i, _acl::id, interr(), _acl::is_const, AEXPR::lop, mk_cval(), ndim, _acl::next, NOSYM, NULL, ASTB::one, AEXPR::op, prev, _acl::repeatc, AEXPR::rop, s, sem, SHD_LWB, SHD_UPB, sptr, _acl::subc, TRUE, and _acl::u1.
Referenced by construct_acl_for_sst(), construct_acl_from_ast(), construct_arg_list(), export_data_consts(), fixup_param_vars(), get_param_alias_const(), mk_reshape_intrin(), mk_size_intrin(), mk_transfer_intrin(), mk_transpose_intrin(), mk_ulbound_intrin(), ref_array(), ref_pd(), rewrite_acl(), and semant1().
construct_arg_list()
static ACL * construct_arg_list (int ast) static
Definition at line 3950 of file semutil2.c.
References A_ARGCNTG, argt, ARGT_ARG, ast, construct_acl_from_ast(), i, _acl::next, and NULL.
Referenced by mk_elem_init_intrinsic(), and mk_nonelem_init_intrinsic().
construct_intrinsic_acl()
static ACL * construct_intrinsic_acl (int ast, DTYPE dtype, int parent_acltype) static
Definition at line 4270 of file semutil2.c.
References AC_I_abs, AC_I_acos, AC_I_adjustl, AC_I_adjustr, AC_I_asin, AC_I_atan, AC_I_atan2, AC_I_ceiling, AC_I_char, AC_I_cos, AC_I_exp, AC_I_floor, AC_I_fltconvert, AC_I_iand, AC_I_ichar, AC_I_ieor, AC_I_index, AC_I_int, AC_I_ior, AC_I_ishft, AC_I_ishftc, AC_I_lbound, AC_I_len, AC_I_len_trim, AC_I_log, AC_I_log10, AC_I_lshift, AC_I_max, AC_I_maxloc, AC_I_maxval, AC_I_merge, AC_I_min, AC_I_minloc, AC_I_minval, AC_I_mod, AC_I_nint, AC_I_null, AC_I_repeat, AC_I_reshape, AC_I_rshift, AC_I_scale, AC_I_scan, AC_I_selected_char_kind, AC_I_selected_int_kind, AC_I_selected_real_kind, AC_I_shape, AC_I_sin, AC_I_size, AC_I_sqrt, AC_I_tan, AC_I_transfer, AC_I_transpose, AC_I_trim, AC_I_ubound, AC_I_verify, argt, ARGT_ARG, ast, ast_intr(), SEM::dinit_error, ERR_Severe, error(), gbl, get_ac_intrinsic(), mk_elem_init_intrinsic(), mk_nonelem_init_intrinsic(), mk_reshape_intrin(), mk_shape_intrin(), mk_size_intrin(), mk_transfer_intrin(), mk_transpose_intrin(), mk_ulbound_intrin(), mk_unop(), new_ast(), OP_SUB, sem, shift, SYMNAME, TRUE, and val.
Referenced by construct_acl_from_ast().
constructf90()
static void constructf90 (int arr, ACL * aclp) static
Definition at line 3469 of file semutil2.c.
References _constructf90(), acs, ADD_LWAST, astb, ASTB::bnd, compute_width(), DTY, dtype, init_constructf90(), interr(), _ACS::level, lower(), mk_id(), numindex, ASTB::one, pop_subscript(), push_subscript(), sub_i, _ACS::tmpid, and _ACS::width.
Referenced by init_derived_w_acl(), and init_sptr_w_acl().
convert_acl_dtype()
static ACL * convert_acl_dtype (ACL * head, int oldtype, int newtype) static
Definition at line 9100 of file semutil2.c.
Referenced by eval_init_expr(), and eval_init_expr_item().
convert_ctmp_array_to_param()
static int convert_ctmp_array_to_param (int cctmpsptr, ACL * aclp) static
Definition at line 1565 of file semutil2.c.
References BZERO, construct_acl_for_sst(), CONVAL2P, STB::curr_scope, dinit_struct_param(), _acl::dtype, get_param_alias_var(), init(), SEM::interface, put_getitem_p(), S_ACONST, S_IDENT, sem, SST_ACLP, SST_DTYPEP, SST_IDP, SST_SYMP, and stb.
Referenced by init_sptr_w_acl().
copy_initconst_to_array()
static int copy_initconst_to_array (ACL ** arr, ACL * c, int count) static
Definition at line 10361 of file semutil2.c.
cuda_enabled()
LOGICAL cuda_enabled (const char * at_or_near)
If we are accepting cuda syntax return TRUE. Otherwise issue an error message and return FALSE.
Definition at line 8465 of file semutil2.c.
Referenced by semant1(), and semant3().
dinit_constructor()
static void dinit_constructor (SPTR arr, ACL * aclp) static
Definition at line 5209 of file semutil2.c.
References ast, dinit(), VAR::dtype, getitem(), VAR::id, mk_id(), VAR::next, NULL, VAR::ptr, S_IDENT, VAR::shape, sym_is_refd(), VAR::u, Varref, and VAR::varref.
Referenced by init_sptr_w_acl().
dinit_fill_struct()
static ACL * dinit_fill_struct (ASTLIST * list, ACL * aclp, int sdtype, int sptr, int memberlist, int init_single) static
Definition at line 7339 of file semutil2.c.
dinit_getval()
static int dinit_getval (int ast, DTYPE dtype) static
Definition at line 6870 of file semutil2.c.
References ast, cngcon(), CONVAL2G, dinit_eval(), DT_INT, DT_ISSCALAR, DT_ISWORD, mk_cval(), mk_cval1(), and val.
dinit_getval1()
static int dinit_getval1 (int ast, DTYPE dtype) static
Definition at line 6904 of file semutil2.c.
References ast, cngcon(), const_eval(), CONVAL2G, DT_ISSCALAR, DT_ISWORD, mk_cval(), mk_cval1(), and val.
dinit_struct_param()
void dinit_struct_param (SPTR sptr, ACL * sconst, DTYPE dtype)
Definition at line 7590 of file semutil2.c.
Referenced by convert_ctmp_array_to_param(), and fixup_param_vars().
dinit_struct_vals()
ACL * dinit_struct_vals (ACL * sconst, DTYPE dtype, SPTR component_sptr)
In DATA statement, do the stuff in dinit_struct_const in two steps.
Definition at line 7606 of file semutil2.c.
Referenced by semant1().
dinit_varref()
VAR * dinit_varref (SST * stkp)
Create an initialization node for a variable reference in a data statement.
If the variable reference is an array section (tpr1652) an implied do is generated for each subscript which is a triple. For example, the array section:
     A(i1, L2:U2, L3:U3, i4)
is transformed into:
     ( ( A(i1, j2, j3, i4) j2 = L2, U2 ), j3 = L3, U3 )
Each triple subscript is replaced by an implied do index variable, and the expressions in the triplet becomes the bounds of the implied do. Sections are to be initialized in array element order (i.e., column major). An implied do nest is produced by a left to right scan of the subscripts (the leftmost triple represents the innermost implied do).
If the variable reference is a member of a whole array, turn the whole array reference into a subscripted reference where each subscript is a triple. Then, the subscripted referenced is handled as described above.
For other variable references, a single initialization node is created.
Definition at line 7709 of file semutil2.c.
Referenced by gen_dinit(), gen_varref_var(), init_sptr_w_acl(), and semant1().
dmp_acl()
void dmp_acl (ACL * acl, int indent)
Definition at line 14288 of file semutil2.c.
References _dmp_acl(), indent, and NULL.
dmp_doif()
void dmp_doif (FILE * f)
Definition at line 14649 of file semutil2.c.
References _dmp_doif(), df, SEM::doif_depth, f, NULL, and sem.
dmp_var()
void dmp_var (VAR * var, int indent, FILE * f)
Definition at line 14242 of file semutil2.c.
References dmp_var(), Doend, VAR::doend, Dostart, VAR::dostart, VAR::dtype, ERR_Severe, f, FILE, gbl, getdtype(), i, VAR::id, indent, VAR::indvar, interr(), VAR::lowbd, VAR::next, NULL, printast(), VAR::ptr, VAR::shape, VAR::step, VAR::u, VAR::upbd, Varref, and VAR::varref.
Referenced by dmp_var(), and dvar().
do_eval_minval_or_maxval()
static ACL * do_eval_minval_or_maxval (INDEX * index, DTYPE elem_dt, DTYPE loc_dt, ACL * elems, unsigned dim, ACL * mask, bool back, AC_INTRINSIC intrin) static
Definition at line 9130 of file semutil2.c.
dummy_program()
void dummy_program (void)
Check whether there is a subprogram statement; if not, create a dummy program symbol, and use that as the program.
Definition at line 13548 of file semutil2.c.
References SCN::currlab, declref(), FUNCLINEP, gbl, getsymbol(), NOSYM, push_scope_level(), scn, SEM::scope_level, SCOPE_NORMAL, SCOPE_SUBPROGRAM, sem, sptr, and tname.
Referenced by do_end_subprogram(), restore_internal_subprograms(), and semant1().
dumpacl()
void dumpacl (const char * s, ACL * aclp, FILE * f)
Definition at line 1287 of file semutil2.c.
References _dumpacl(), acl_array_num, f, NULL, and s.
dup_struct_init()
void dup_struct_init (int new_sptr, int old_sptr)
Duplicate a derived type component's default initializations.
Parameters
new_sptr is the component that receives the initialization copy.
old_sptr has the default initialization that we want to duplicate.
We need to duplicate the initialization of a derived type component when we create new instances of the derived type with different kind/len type parameters.
Definition at line 5578 of file semutil2.c.
References BZERO, DTC_DEFAULT, DTC_DEFAULT_CNT, DTC_DEFAULT_HEAD, has_init_value(), and NEED.
Referenced by semant2().
dvar()
void dvar (VAR * var)
Definition at line 14282 of file semutil2.c.
References dmp_var().
enter_lexical_block()
int enter_lexical_block (int gen_debug)
Definition at line 14474 of file semutil2.c.
References add_stmt_after(), ast, BLK_SCOPE_SPTR, BLK_SYM, SEM::blksymnum, gbl, getccssym(), getlab(), mk_stmt(), RFCNTI, SEM::scope_level, sem, sptr, std, STD_LABEL, and STD_PREV.
Referenced by par_push_scope().
eval_abs()
static ACL * eval_abs (ACL * arg, DTYPE dtype) static
Definition at line 8798 of file semutil2.c.
Referenced by eval_init_op().
eval_adjustl()
static ACL * eval_adjustl (ACL * arg) static
Definition at line 10209 of file semutil2.c.
Referenced by eval_init_op().
eval_adjustr()
static ACL * eval_adjustr (ACL * arg) static
Definition at line 10247 of file semutil2.c.
Referenced by eval_init_op().
eval_array_constructor()
static ACL * eval_array_constructor (ACL * e) static
Definition at line 11732 of file semutil2.c.
References AC_ACONST, add_to_list(), e, eval_array_constructor(), eval_init_expr_item(), _acl::id, _acl::next, NULL, and root.
Referenced by eval_array_constructor(), eval_const_array_section(), eval_const_array_triple_section(), eval_init_expr(), and eval_init_expr_item().
eval_ceiling()
static ACL * eval_ceiling (ACL * arg, DTYPE dtype) static
Definition at line 9541 of file semutil2.c.
Referenced by eval_init_op().
eval_char()
static ACL * eval_char (ACL * arg, DTYPE dtype) static
Definition at line 8735 of file semutil2.c.
Referenced by eval_init_op().
eval_const_array_section()
static ACL * eval_const_array_section (ACL * lop, int ldtype) static
Definition at line 11110 of file semutil2.c.
References AC_ACONST, AD_DPTR, AD_LWAST, AD_MLPYR, AD_NUMDIM, AD_UPAST, ad_val_of(), eval_array_constructor(), eval_sb(), i, _acl::id, interr(), ndims, NULL, sb, and sym_of_ast().
Referenced by eval_init_op().
eval_const_array_triple_section()
static ACL * eval_const_array_triple_section (ACL * curr_e) static
Definition at line 11155 of file semutil2.c.
References AC_ACONST, c, _acl::conval, _acl::dtype, eval_array_constructor(), eval_init_expr(), get_ival(), _acl::id, interr(), _acl::is_const, ndims, _acl::next, NULL, and sb.
Referenced by eval_init_expr_item().
eval_do()
static ACL * eval_do (ACL * ido) static
Definition at line 11874 of file semutil2.c.
References add_to_list(), _acl::ast, _acl::conval, SEM::dinit_error, dinit_eval(), _acl::doinfo, DTY, _acl::dtype, eval_init_expr(), getcon(), i, DOINFO::index_var, DOINFO::init_expr, interr(), ISZ_2_INT64, DOINFO::limit_expr, mk_cval1(), NULL, num, root, sem, DOINFO::step_expr, _acl::subc, TY_INT8, TY_LOG8, and _acl::u1.
Referenced by eval_init_expr_item().
eval_do_idx()
static ACL * eval_do_idx (int ast) static
Definition at line 4512 of file semutil2.c.
References AC_CONST, ast, _acl::ast, SEM::dostack, DT_ISWORD, _acl::dtype, GET_ACL, _acl::id, _acl::is_const, mk_cnst(), mk_cval1(), NULL, p, sem, sptr, SEM::top, and _acl::u1.
Referenced by construct_acl_from_ast().
eval_floor()
static ACL * eval_floor (ACL * arg, DTYPE dtype) static
Definition at line 9480 of file semutil2.c.
Referenced by eval_init_op().
eval_fltconvert()
static ACL * eval_fltconvert (ACL * arg, DTYPE dtype) static
Definition at line 8770 of file semutil2.c.
Referenced by eval_init_op().
eval_ichar()
static ACL * eval_ichar (ACL * arg, DTYPE dtype) static
Definition at line 8691 of file semutil2.c.
Referenced by eval_init_op().
eval_index()
static ACL * eval_index (ACL * arg) static
Definition at line 10113 of file semutil2.c.
Referenced by eval_init_op().
eval_init_expr()
ACL * eval_init_expr (ACL * e)
Definition at line 11835 of file semutil2.c.
References AC_ACONST, AC_SCONST, add_to_list(), clone_init_const(), convert_acl_dtype(), DDTG, _acl::dtype, e, eval_array_constructor(), eval_init_expr(), eval_init_expr_item(), _acl::id, _acl::next, NULL, root, _acl::subc, and TRUE.
Referenced by eval_const_array_triple_section(), eval_do(), eval_init_expr(), eval_init_expr_item(), eval_init_op(), get_param_alias_const(), ref_array(), ref_pd(), and semant1().
eval_init_expr_item()
static ACL * eval_init_expr_item (ACL * cur_e) static
Definition at line 11757 of file semutil2.c.
References AC_ACONST, AC_ARRAYREF, AC_AST, AC_CONST, AC_CONVAL, AC_ICONST, AC_IDO, AC_IEXPR, AC_INTR_CALL, AC_SCONST, AC_TRIPLE, _acl::ast, clone_init_const(), _acl::conval, CONVAL2G, convert_acl_dtype(), DDTG, DTY, _acl::dtype, CONST::dtype, eval_array_constructor(), eval_const_array_triple_section(), eval_do(), eval_init_expr(), eval_init_op(), _acl::expr, FLANG_FALLTHROUGH, get_const_from_ast(), get_getitem_p(), _acl::id, AEXPR::lop, NULL, AEXPR::op, AEXPR::rop, sptr, _acl::sptr, _acl::subc, TRUE, and _acl::u1.
Referenced by eval_array_constructor(), eval_init_expr(), eval_sb(), mk_size_intrin(), and mk_ulbound_intrin().
eval_init_op()
static ACL * eval_init_op (int op, ACL * lop, DTYPE ldtype, ACL * rop, DTYPE rdtype, SPTR sptr, DTYPE dtype) static
Definition at line 11276 of file semutil2.c.
References AC_ACONST, AC_ARRAYREF, AC_CAT, AC_CONST, AC_CONV, AC_I_abs, AC_I_acos, AC_I_adjustl, AC_I_adjustr, AC_I_asin, AC_I_atan, AC_I_atan2, AC_I_ceiling, AC_I_char, AC_I_cos, AC_I_exp, AC_I_floor, AC_I_fltconvert, AC_I_iand, AC_I_ichar, AC_I_ieor, AC_I_index, AC_I_int, AC_I_ior, AC_I_ishft, AC_I_lbound, AC_I_len_trim, AC_I_log, AC_I_log10, AC_I_max, AC_I_maxloc, AC_I_maxval, AC_I_merge, AC_I_min, AC_I_minloc, AC_I_minval, AC_I_mod, AC_I_nint, AC_I_null, AC_I_repeat, AC_I_reshape, AC_I_scale, AC_I_scan, AC_I_selected_char_kind, AC_I_selected_int_kind, AC_I_selected_real_kind, AC_I_shape, AC_I_sin, AC_I_size, AC_I_sqrt, AC_I_tan, AC_I_transfer, AC_I_transpose, AC_I_trim, AC_I_ubound, AC_I_verify, AC_INTR_CALL, AC_LNOT, AC_MEMBR_SEL, AC_NEG, AC_SCONST, add_to_list(), _acl::ast, astb, BCOPY, c, clone_init_const(), cngcon(), const_fold(), _acl::conval, CONVAL2G, count, DDTG, dt, DT_INT, DT_LOG, DTY, _acl::dtype, dtype, ERR_Severe, error(), eval_abs(), eval_adjustl(), eval_adjustr(), eval_ceiling(), eval_char(), eval_const_array_section(), eval_floor(), eval_fltconvert(), eval_ichar(), eval_index(), eval_init_expr(), eval_int(), eval_ishft(), eval_len_trim(), eval_merge(), eval_min_or_max(), eval_minval_or_maxval(), eval_mod(), eval_nint(), eval_null(), eval_repeat(), eval_reshape(), eval_scale(), eval_scan(), eval_selected_char_kind(), eval_selected_int_kind(), eval_selected_real_kind(), eval_shape(), eval_size(), eval_sqrt(), eval_transfer(), eval_trim(), eval_ul_bound(), eval_verify(), FALSE, gbl, GET_ACL, get_ast_op(), get_getitem_p(), get_int_cval(), get_type(), getitem(), getstring(), _acl::i, ASTB::i1, _acl::id, interr(), mk_cmp(), mk_cnst(), mk_cval(), STB::n_base, negate_const(), _acl::next, NULL, OP_CMP, OP_EQ, OP_GE, OP_GT, OP_LAND, OP_LE, OP_LEQV, OP_LNEQV, OP_LOR, OP_LT, OP_NE, _acl::repeatc, root, s, SCFTN_FALSE, SCFTN_TRUE, sptr, stb, string_length(), _acl::subc, TRUE, and _acl::u1.
Referenced by eval_init_expr_item().
eval_int()
static ACL * eval_int (ACL * arg, DTYPE dtype) static
Definition at line 8755 of file semutil2.c.
Referenced by eval_init_op().
eval_ishft()
static ACL * eval_ishft (ACL * arg, DTYPE dtype) static
Definition at line 8543 of file semutil2.c.
Referenced by eval_init_op().
eval_len_trim()
static ACL * eval_len_trim (ACL * arg) static
Definition at line 9867 of file semutil2.c.
Referenced by eval_init_op().
eval_merge()
static ACL * eval_merge (ACL * arg, DTYPE dtype) static
Definition at line 8955 of file semutil2.c.
Referenced by eval_init_op().
eval_min_or_max()
static ACL * eval_min_or_max (ACL * arg, DTYPE dtype, LOGICAL want_max) static
Definition at line 9277 of file semutil2.c.
Referenced by eval_init_op().
eval_minval_or_maxval()
static ACL * eval_minval_or_maxval (ACL * arg, DTYPE dtype, AC_INTRINSIC intrin) static
Definition at line 9223 of file semutil2.c.
Referenced by eval_init_op().
eval_mod()
static ACL * eval_mod (ACL * arg, DTYPE dtype) static
Definition at line 9602 of file semutil2.c.
Referenced by eval_init_op().
eval_nint()
static ACL * eval_nint (ACL * arg, DTYPE dtype) static
Definition at line 9395 of file semutil2.c.
Referenced by eval_init_op().
eval_null()
static ACL * eval_null (int sptr) static
Definition at line 10598 of file semutil2.c.
Referenced by eval_init_op().
eval_repeat()
static ACL * eval_repeat (ACL * arg, DTYPE dtype) static
Definition at line 9630 of file semutil2.c.
Referenced by eval_init_op().
eval_reshape()
static ACL * eval_reshape (ACL * arg, DTYPE dtype, LOGICAL transpose) static
Definition at line 10400 of file semutil2.c.
Referenced by eval_init_op().
eval_sb()
static int eval_sb (int d) static
Definition at line 11014 of file semutil2.c.
References add_to_list(), assert, astb, c, clone_init_const(), d, eval_init_expr_item(), eval_sb(), eval_sub_index(), get_int_cval(), i, ASTB::i1, interr(), ISZ_T, _acl::next, NULL, _acl::repeatc, sb, tmp, TRACE_EVAL_SB, and TRUE.
Referenced by eval_const_array_section(), and eval_sb().
eval_scale()
static ACL * eval_scale (ACL * arg, DTYPE dtype) static
Definition at line 8873 of file semutil2.c.
Referenced by eval_init_op().
eval_scan()
static ACL * eval_scan (ACL * arg) static
Definition at line 10000 of file semutil2.c.
Referenced by eval_init_op().
eval_selected_char_kind()
static ACL * eval_selected_char_kind (ACL * arg) static
Definition at line 9984 of file semutil2.c.
Referenced by eval_init_op().
eval_selected_int_kind()
static ACL * eval_selected_int_kind (ACL * arg) static
Definition at line 9957 of file semutil2.c.
Referenced by eval_init_op().
eval_selected_real_kind()
static ACL * eval_selected_real_kind (ACL * arg) static
Definition at line 9893 of file semutil2.c.
Referenced by eval_init_op().
eval_shape()
static ACL * eval_shape (ACL * arg, DTYPE dtype) static
Definition at line 10287 of file semutil2.c.
Referenced by eval_init_op().
eval_size()
static ACL * eval_size (ACL * arg) static
Definition at line 10297 of file semutil2.c.
Referenced by eval_init_op().
eval_sqrt()
static ACL * eval_sqrt (ACL * arg, DTYPE dtype) static
Definition at line 10633 of file semutil2.c.
References x, and y.
Referenced by eval_init_op().
eval_sub_index()
static ISZ_T eval_sub_index (int dim) static
Definition at line 10985 of file semutil2.c.
References AD_DPTR, AD_LWAST, ad_val_of(), _acl::conval, dim, _acl::dtype, get_int_cval(), get_ival(), ISZ_T, _acl::next, _acl::repeatc, sb, subscr_base, and sym_of_ast().
Referenced by eval_sb().
eval_transfer()
static ACL * eval_transfer (ACL * arg, DTYPE dtype) static
Definition at line 9772 of file semutil2.c.
Referenced by eval_init_op().
eval_trim()
static ACL * eval_trim (ACL * arg, DTYPE dtype) static
Definition at line 10169 of file semutil2.c.
Referenced by eval_init_op().
eval_ul_bound()
static ACL * eval_ul_bound (ACL * arg) static
Definition at line 10327 of file semutil2.c.
Referenced by eval_init_op().
eval_verify()
static ACL * eval_verify (ACL * arg) static
Definition at line 10054 of file semutil2.c.
Referenced by eval_init_op().
exit_lexical_block()
void exit_lexical_block (int gen_debug)
Definition at line 14505 of file semutil2.c.
References add_stmt_after(), ast, BLK_SYM, ENDLINEP, gbl, getlab(), mk_stmt(), RFCNTI, SEM::scope_level, sem, std, STD_LABEL, and STD_PREV.
Referenced by par_pop_scope().
fix_mem_bounds()
int fix_mem_bounds (int parent, int mem)
Definition at line 12566 of file semutil2.c.
References AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_NUMDIM, AD_UPAST, AD_ZBASE, add_parent_to_bounds(), i, mem(), parent, and zbase.
Referenced by fix_type_param_members().
fix_mem_bounds2()
int fix_mem_bounds2 (int parent, int mem)
Definition at line 12603 of file semutil2.c.
References AD_DEFER, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_UPAST, AD_UPBD, AD_ZBASE, ADD_EXTNTAST, ADD_LWAST, ADD_NUMDIM, add_parent_to_bounds(), ADD_UPAST, ADD_ZBASE, dup_array_dtype(), get_aux_arrdsc(), i, mem(), new_dtype(), parent, remove_parent_from_ast(), and zbase.
Referenced by gen_kind_parm_assignments().
fix_symtab()
static void fix_symtab () static
Definition at line 13688 of file semutil2.c.
References assert, aux, AUX::dpdsc_base, DTY, i, AUX::list, NOSYM, sem, sptr, TRUE, SEM::typroc_avail, and SEM::typroc_base.
Referenced by restore_host_state().
fix_type_param_members()
void fix_type_param_members (SPTR sptr, DTYPE dtype)
Definition at line 13145 of file semutil2.c.
References add_parent_to_bounds(), ast, DTY, fix_mem_bounds(), i, mem(), mk_id(), NOSYM, sptr, and TY_CHAR.
Referenced by semant1().
gen_alloc_dealloc()
int gen_alloc_dealloc (int stmtyp, int object, ITEM * spec)
Definition at line 12148 of file semutil2.c.
References A_TKNP, add_stmt(), add_stmt_after(), add_stmt_before(), SEM::alloc_std, assert, ast, DT_INT, DTYG, dtype, error(), firstalloc, flg, gbl, SEM::gcvlen, get_len_of_deferchar_ast(), get_temp(), is_deferlenchar_ast(), ITEM_END, itemp, mk_assn_stmt(), mk_id(), mk_stmt(), sem, spec, sptr, FLG::standard, stmt, sym_of_ast(), SYMNAME, tmp, TY_INT8, and XBIT.
Referenced by _constructf90(), convert_to_block_forall(), dealloc_tmp(), gen_allocate_array(), gen_dealloc_etmps(), gen_deallocate_arrays(), mk_ptr_subscr(), and semant3().
gen_alloc_mem_initialize_for_sym()
void gen_alloc_mem_initialize_for_sym (int sptr, int std)
Definition at line 13235 of file semutil2.c.
References gen_alloc_mem_initialize_for_sym2(), sptr, and std.
Referenced by bblock().
gen_alloc_mem_initialize_for_sym2()
static void gen_alloc_mem_initialize_for_sym2 (int sptr, int std, int ast, int visit_flag) static
Definition at line 13180 of file semutil2.c.
References add_nullify_ast(), add_stmt_after(), allocatable_member(), ast, DDTG, DTY, dtype, FREE, gen_alloc_mem_initialize_for_sym2(), memsym_of_ast(), mk_id(), mk_member(), NEW, next, visit_list::next, NOSYM, prev, sptr, std, and visit_list.
Referenced by gen_alloc_mem_initialize_for_sym(), and gen_alloc_mem_initialize_for_sym2().
gen_allocate_array()
void gen_allocate_array (int arr)
Given an allocatable array and an explicit shape list which has been deposited in the semant 'bounds' structure, generate assignments to the arrays bounds temporaries, and allocate the array. Save the id ast of the array for an ensuing deallocate of the array.
Definition at line 1046 of file semutil2.c.
References acs, add_p_dealloc_item(), _ACS::arrtype, gen_alloc_dealloc(), gen_defer_shape(), get_all_descriptors(), get_static_descriptor(), and is_deferlenchar_dtype().
Referenced by gen_array_result(), init_sptr_w_acl(), and mkexpr_assign_temp().
gen_automatic_reallocation()
void gen_automatic_reallocation (int lhs, int rhs, int std)
Generate (re)allocation code for deferred length character objects and traditional character objects that are allocatable scalars.
This is typically used in generating (re)allocation code in an assignment to an allocatable/deferred length character object.
Reallocation code is generated for deferred length character objects.
For traditional character allocatable scalars, we allocate the object if it has not already been allocated; we do not generate reallocation code since the amount of space allocated is fixed with traditional character allocatable objects.
We update the character length descriptor information for both deferred length and traditional character objects. This is needed for proper I/O such as namelist processing.
Parameters
lhs is the ast of the object getting (re)allocated.
rhs is the ast of the object that supplies the character length.
std is the statement descriptor where we insert the (re)allocation and/or length assignment code.
Definition at line 13439 of file semutil2.c.
References A_OPTYPEP, A_TKNP, add_stmt_after(), add_stmt_before(), argt, ARGT_ARG, ast, check_and_add_auto_dealloc_from_ast(), DDTG, DT_INT, STB::dt_log, DT_LOG, get_len_of_deferchar_ast(), getsymbol(), init_intrin_type_desc(), lhs, memsym_of_ast(), mk_argt(), mk_assn_stmt(), mk_binop(), mk_func_node(), mk_id(), mk_stmt(), NULL, OP_NE, proc_arginfo(), procsym_of_ast(), size_ast_of(), stb, std, string_expr_length(), and STB::user.
Referenced by rewrite_allocatable_assignment().
gen_conditional_alloc()
int gen_conditional_alloc (int cond, int alloc_item, int after)
Definition at line 13296 of file semutil2.c.
References A_OPTYPEP, A_TKNP, add_stmt_after(), after, argt, ARGT_ARG, ast, STB::dt_log, getsymbol(), mk_argt(), mk_func_node(), mk_id(), mk_stmt(), stb, and STB::user.
Referenced by add_private_allocatable().
gen_conditional_dealloc()
void gen_conditional_dealloc (int do_cond, int dealloc_item, int after)
Definition at line 13290 of file semutil2.c.
References __gen_conditional_dealloc(), and after.
Referenced by deallocate_privates().
gen_conditional_dealloc_for_sym()
void gen_conditional_dealloc_for_sym (int sptr, int std)
Definition at line 13334 of file semutil2.c.
References __gen_conditional_dealloc(), A_TKNP, add_stmt_after(), ast, flg, gbl, mk_id(), mk_stmt(), scope, FLG::smp, sptr, std, and void().
Referenced by bblock(), and fix_args().
gen_dealloc_etmps()
void gen_dealloc_etmps (void)
Definition at line 12251 of file semutil2.c.
References SEM::etmp_list, FALSE, gen_alloc_dealloc(), mk_id(), xyyz::next, sem, sptr, xyyz::sptr, xyyz::t, and SEM::use_etmps.
Referenced by check_etmp(), and semant3().
gen_dealloc_for_sym()
int gen_dealloc_for_sym (int sptr, int std)
Definition at line 13361 of file semutil2.c.
References A_TKNP, add_stmt_after(), ast, mk_id(), mk_stmt(), sptr, ss, and std.
Referenced by init_derived_type().
gen_deallocate_arrays()
void gen_deallocate_arrays (void)
Generate deallocates for the temporary arrays in the sem.p_delloc list.
Definition at line 752 of file semutil2.c.
References DI_FORALL, DI_ID, SEM::doif_depth, gen_alloc_dealloc(), NULL, p, SEM::p_dealloc, sem, t, and void().
Referenced by rewrite_allocatable_assignment(), semant1(), and semant3().
gen_defer_shape()
int gen_defer_shape (int sptr, int astparent, int savedelete)
Process an explicit shape list has been parsed and all bounds information has been deposited into a few semant global data structures.
Parameters
sptr sptr of the deferred array
astparent ast of the parent pointer
savedelete ?
From this collection of information:
Generate assignments which define the lower and upper bounds for the deferred array; where the bounds are stored (asts) are located in the array descriptor.
Create a subscript AST which is used to represent the explicit shape; the bounds for the explicit shape use the bounds asts which are the destinations of the generated assignments; note that each subscript is represented as a triple.
Definition at line 613 of file semutil2.c.
References ADD_DEFER, ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_NUMDIM, add_stmt(), ADD_UPAST, ADD_UPBD, SEM::arrdim, ast, astb, ASTB::bnd, SEM::bounds, check_member(), dt, ASTB::dtype, extent(), getitem(), i, itemp, lb, MAXDIMS, mk_assn_stmt(), mk_extent_expr(), mk_id(), mk_subscr(), mk_triple(), ASTB::one, SEM::p_dealloc_delete, sem, sptr, src, std, sym_of_ast(), and ub.
Referenced by gen_allocate_array(), and semant3().
gen_derived_type_alloc_init()
void gen_derived_type_alloc_init (ITEM * itemp)
Definition at line 12049 of file semutil2.c.
References add_stmt(), ast, _acl::dtype, get_dtype_init_template(), get_getitem_p(), get_struct_initialization_tree(), has_type_parameter(), itemp, mk_assn_stmt(), mk_id(), and NOSYM.
Referenced by semant3().
gen_finalization_for_sym()
int gen_finalization_for_sym (int sptr, int std, int memAst)
Definition at line 12369 of file semutil2.c.
References add_stmt_after(), argt, ARGT_ARG, ast, check_member(), DTY, dtype, FALSE, gbl, gen_set_type(), get_static_descriptor(), get_static_type_descriptor(), get_type_descr_arg(), has_finalized_component(), init_sdsc(), mk_argt(), mk_func_node(), mk_id(), mk_stmt(), mkRteRtnNm(), RTE_finalize, SEM::savall, sem, sptr, std, and sym_mkfunc_nodesc().
Referenced by bblock(), gen_finalized_result(), rewrite_allocatable_assignment(), and semant3().
gen_kind_parm_assignments()
static int gen_kind_parm_assignments (SPTR sptr, DTYPE dtype, int std, int flag) static
Definition at line 12939 of file semutil2.c.
References A_TKNP, add_parent_to_bounds(), add_stmt_after(), add_stmt_before(), ast, BLOCK_EXIT_STD, buf, chk_kind_parm_expr(), chk_kind_parm_set_expr(), CNULL, DT_INT, SEM::dtemps, DTY, dtype, error(), fix_mem_bounds2(), gbl, gen_kind_parm_assignments(), genPolyAsn(), get_byte_len_indx(), get_header_member(), getccsym_sc(), getitem(), has_type_parameter(), i, init_sdsc(), insert_assign(), j, len, mem(), mk_assn_stmt(), mk_cval1(), mk_id(), mk_member(), mk_stmt(), NOSYM, RU_PROG, sem, sptr, std, STD_PREV, strlen(), SYMNAME, tmp, TY_CHAR, and val.
Referenced by gen_kind_parm_assignments(), and gen_type_initialize_for_sym().
gen_null_intrin()
static int gen_null_intrin () static
Definition at line 2885 of file semutil2.c.
References A_OPTYPEP, ast, intast_sym, mk_func_node(), and mk_id().
Referenced by _constructf90().
gen_set_type()
int gen_set_type (int dest_ast, int src_ast, int std, LOGICAL insert_before, LOGICAL intrin_type)
Generates calls to RTE_set_type() or RTE_set_intrin_type() which set the type descriptor field of an object's descriptor.
Parameters
dest_ast is the descriptor expression that's getting its type descriptor set. Note: dest_ast may be a descriptor expression or an expression that has a descriptor.
src_ast is the expression that has the type descriptor that we are copying to dest_ast. Note: src_ast may be a descriptor expression or an expession that has a descriptor.
std is the std where we will insert the call.
insert_before is true when you want to insert the call before std, otherwise we insert it after std.
intrin_type is true when you want to use the RTE_set_intrin_type() routine instead of the RTE_set_type() routine.
Returns
the new std after inserting the call.
Definition at line 14753 of file semutil2.c.
References add_stmt_after(), add_stmt_before(), check_member(), get_member_descriptor(), is_tbp(), memsym_of_ast(), mk_id(), mk_set_type_call(), sptr, and std.
Referenced by check_alloc_ptr_type(), check_pointer_type(), gen_finalization_for_sym(), genPolyAsn(), ref_pd(), and transform_call().
gen_type_initialize_for_sym()
void gen_type_initialize_for_sym (SPTR sptr, int std, int flag, DTYPE dtype2)
Definition at line 13163 of file semutil2.c.
References add_stmt(), array_element_dtype(), ast, DTY, gen_kind_parm_assignments(), is_array_dtype(), mk_stmt(), sptr, and std.
Referenced by bblock(), and semant3().
gen_varref_var()
VAR * gen_varref_var (int ast, DTYPE dtype)
Definition at line 11978 of file semutil2.c.
References ast, dinit_varref(), S_IDENT, SST_ASTP, SST_DTYPEP, SST_IDP, and SST_SHAPEP.
genPolyAsn()
static int genPolyAsn (int dest, int src, int std, int parent) static
Definition at line 12881 of file semutil2.c.
References add_stmt_after(), argt, ARGT_ARG, ast, check_member(), dest, DT_INT, DTY, FALSE, gen_set_type(), get_member_descriptor(), get_static_descriptor(), get_static_type_descriptor(), init_sdsc(), mk_argt(), mk_cval1(), mk_func_node(), mk_id(), mk_stmt(), mk_unop(), mkRteRtnNm(), NOSYM, OP_VAL, RTE_poly_asn, src, std, sym_mkfunc_nodesc(), and sym_of_ast().
Referenced by gen_kind_parm_assignments().
get_ac_intrinsic()
static AC_INTRINSIC get_ac_intrinsic (int ast) static
Definition at line 4019 of file semutil2.c.
References A_OPTYPEG, AC_I_NONE, ast, map_I_to_AC(), map_PD_to_AC(), and sptr.
Referenced by construct_intrinsic_acl().
get_ac_op()
static int get_ac_op (int ast) static
Definition at line 4428 of file semutil2.c.
References A_OPTYPEG, AC_ADD, AC_CAT, AC_DIV, AC_EQ, AC_EXP, AC_EXPK, AC_EXPX, AC_GE, AC_GT, AC_LAND, AC_LE, AC_LEQV, AC_LNEQV, AC_LNOT, AC_LOR, AC_LT, AC_MUL, AC_NE, AC_NEG, AC_SUB, ast, DDTG, interr(), OP_ADD, OP_CAT, OP_DIV, OP_EQ, OP_GE, OP_GT, OP_LAND, OP_LE, OP_LEQV, OP_LNEQV, OP_LNOT, OP_LOR, OP_LT, OP_MUL, OP_NE, OP_NEG, OP_SUB, and OP_XTOI.
Referenced by construct_acl_from_ast().
get_acl()
ACL * get_acl (int area)
Definition at line 5136 of file semutil2.c.
References a, area, BZERO, and getitem().
get_adjlr_arr_temp()
SPTR get_adjlr_arr_temp (DTYPE dtype)
Get a compiler-created allocatable array temp to represent the result of run-time function computing the adjustl/adjustr intrinsic.
The result of the run-time is the length (which we don't actually use), but it's needed to effect array/forall processing in the compiler. Eventually, in outconv.c, the temp is discarded, as well as the return value of the runtime routine.
Definition at line 8030 of file semutil2.c.
Referenced by init_sptr_w_acl(), and rewrite_func_ast().
get_arr_const()
SPTR get_arr_const (DTYPE dtype)
Get a compiler array temporary of type dtype which is used to represent array constants.
Definition at line 864 of file semutil2.c.
References getcctmp(), and sptr.
Referenced by init_sptr_w_acl().
get_arr_temp()
SPTR get_arr_temp (DTYPE dtype, LOGICAL nodesc, LOGICAL alloc_deferred, LOGICAL constructor)
Get a compiler array temporary of type dtype.
Definition at line 7932 of file semutil2.c.
Referenced by func_call2(), gen_derived_arr_init(), init_sptr_w_acl(), inline_small_matmul(), mkexpr_assign_temp(), precompute_arg_intrin(), ptrfunc_call(), ref_intrin(), ref_pd(), and rewrite_allocatable_assignment().
get_ast_op()
static int get_ast_op (int op) static
Definition at line 4358 of file semutil2.c.
References AC_ADD, AC_CAT, AC_DIV, AC_EQ, AC_EXP, AC_EXPK, AC_EXPX, AC_GE, AC_GT, AC_LAND, AC_LE, AC_LEQV, AC_LNEQV, AC_LNOT, AC_LOR, AC_LT, AC_MUL, AC_NE, AC_NEG, AC_SUB, interr(), OP_ADD, OP_CAT, OP_DIV, OP_EQ, OP_GE, OP_GT, OP_LAND, OP_LE, OP_LEQV, OP_LNEQV, OP_LNOT, OP_LOR, OP_LT, OP_MUL, OP_NE, OP_NEG, OP_SUB, OP_XTOI, and OP_XTOX.
Referenced by eval_init_op(), and mk_cmp().
get_ch_temp()
SPTR get_ch_temp (DTYPE dtype)
Get a character compiler temporary of type dtype.
Definition at line 8055 of file semutil2.c.
Referenced by gen_char_result(), ref_pd(), and rewrite_allocatable_assignment().
get_const_from_ast()
static INT get_const_from_ast (int ast) static
Definition at line 10936 of file semutil2.c.
References ast, c, const_eval(), CONVAL2G, DT_ISWORD, DTY, interr(), TY_CHAR, and TY_NCHAR.
Referenced by const_eval(), and eval_init_expr_item().
get_default_int_val()
static INT get_default_int_val (INT r) static
Definition at line 11963 of file semutil2.c.
References STB::dt_int, DTY, getcon(), r, stb, tmp, TY_INT8, and STB::user.
get_dtype_init_template()
SPTR get_dtype_init_template (DTYPE dtype)
Process an AC_TYPEINIT.
Look for an initialization template for this type. If one already exists then return it. Otherwise build one (and return it).
Definition at line 11998 of file semutil2.c.
References array_element_dtype(), assert, DDTG, dinit(), DTY, _acl::dtype, dtype, eq_dtype(), ERR_Fatal, GET_ACL, get_getitem_p(), get_struct_initialization_tree(), get_struct_tag_sptr(), getccssym_sc(), is_array_dtype(), is_unresolved_parameterized_dtype(), NOSYM, NULL, prefix, sptr, _acl::sptr, and TRUE.
Referenced by component_init_allocd_auto(), gen_derived_type_alloc_init(), get_static_type_descriptor(), init_derived_type(), and sym_get_sdescr().
get_element_cnt()
static INT get_element_cnt () static
Definition at line 2551 of file semutil2.c.
References acs, _ACS::element_cnt, and sub_i.
Referenced by _constructf90().
get_exttype_default()
static int get_exttype_default (DTYPE dtype, int pos) static
Definition at line 5739 of file semutil2.c.
References DTC_ACL, DTC_DT_CNT, DTY, get_exttype_default(), get_struct_default_init(), no_data_components(), NOSYM, NULL, and pos.
Referenced by get_exttype_default(), and get_keyword_components().
get_exttype_list()
static ACL * get_exttype_list (int cnt) static
Definition at line 5702 of file semutil2.c.
References cnt, DTC_ACL, first, i, NULL, and prev.
Referenced by get_keyword_components().
get_exttype_struct_constructor()
static ACL * get_exttype_struct_constructor (ACL * in_aclp, DTYPE dtype, ACL ** prev_aclp) static
Definition at line 6090 of file semutil2.c.
References AC_ACONST, AC_AST, AC_EXPR, AC_SCONST, ast, _acl::ast, cmpat_dtype_with_size(), DBGBIT, DDTG, DTY, _acl::dtype, error(), gbl, GET_ACL, get_exttype_struct_constructor(), _acl::id, is_tbp_or_final(), _acl::next, no_data_components(), NOSYM, NULL, printacl(), S_EXPR, S_IDENT, S_LVALUE, sptr, SST_ASTG, SST_DTYPEG, SST_IDG, SST_LSYMG, SST_SYMG, _acl::stkp, _acl::subc, SYMNAME, and _acl::u1.
Referenced by get_exttype_struct_constructor(), and get_keyword_components().
get_header_member()
static int get_header_member (int sdsc_ast, int info) static
Definition at line 12704 of file semutil2.c.
References ast, astb, ASTB::bnd, ASTB::dtype, info, mk_isz_cval(), and mk_subscr().
Referenced by gen_kind_parm_assignments().
get_int_from_init_conval()
static INT get_int_from_init_conval (ACL * aclp) static
Definition at line 8527 of file semutil2.c.
get_itemp()
SPTR get_itemp (DTYPE dtype)
Definition at line 7886 of file semutil2.c.
Referenced by do_dist_schedule(), do_lastval(), do_schedule(), save_clauses(), and semsmp().
get_ival()
static ISZ_T get_ival (DTYPE dtype, INT conval) static
Definition at line 11143 of file semutil2.c.
References DTY, get_isz_cval(), TY_INT8, and TY_LOG8.
Referenced by eval_const_array_triple_section(), and eval_sub_index().
get_keyword_components()
static LOGICAL get_keyword_components (ACL * in_aclp, int cnt, char * kwdarg, DTYPE dtype, int is_extend) static
Definition at line 5797 of file semutil2.c.
References AC_EXPR, AC_SCONST, ACL_SAVE_AREA, buf, cmpat_dtype_with_size(), cnt, CNULL, DT_INT, DTC_ACL, DTY, _acl::dtype, error(), errsev(), FALSE, gbl, GET_ACL, get_exttype_default(), get_exttype_list(), get_exttype_struct_constructor(), get_kind_parm_by_name(), get_len_set_parm_by_name(), getitem(), i, SCN::id, _acl::id, j, mk_cval1(), SCN::name, SEM::new_param_dt, _acl::next, no_data_components(), NULL, pos, put_default_kind_type_param(), put_length_type_param(), _acl::repeatc, S_CONST, S_EXPR, S_KEYWORD, S_SCONST, scn, sem, _acl::size, SST_ACLG, SST_ASTP, SST_CVALG, SST_CVALP, SST_DTYPEP, SST_E3G, SST_IDG, SST_IDP, SST_SHAPEP, _acl::stkp, strlen(), _acl::subc, TRUE, _acl::u1, and val.
Referenced by chk_struct_constructor().
get_minmax_val()
static ACL * get_minmax_val (DTYPE dtype, bool want_max) static
Definition at line 9093 of file semutil2.c.
get_offset_without_dim()
static unsigned get_offset_without_dim (INDEX * index, unsigned dim) static
Definition at line 9050 of file semutil2.c.
get_param_alias_var()
SPTR get_param_alias_var (SPTR param_sptr, DTYPE dtype)
Definition at line 1543 of file semutil2.c.
References STB::curr_scope, getsymbol(), mangle_name(), PARAMVALG, PARAMVALP, stb, sym_is_refd(), and SYMNAME.
Referenced by convert_ctmp_array_to_param(), and fixup_param_vars().
get_parm_ast()
static int get_parm_ast (int parent, SPTR sptr, DTYPE dtype) static
Definition at line 12417 of file semutil2.c.
References ast, DTY, get_parm_ast(), mem(), mk_id(), mk_member(), NOSYM, parent, sptr, and SYMNAME.
Referenced by add_parent_to_bounds(), and get_parm_ast().
get_shape_arr_temp()
SPTR get_shape_arr_temp (int arg)
Get a compiler array temporary of from a shape of an ast.
Definition at line 8042 of file semutil2.c.
Referenced by precompute_arg_intrin(), and ref_intrin().
get_shape_arraydtype()
static int get_shape_arraydtype (int shape, int eltype) static
Definition at line 2599 of file semutil2.c.
References acs, ad_val_of(), SEM::arrdim, _ACS::arrtype, SEM::bounds, DTY, FALSE, i, is_deferlenchar_dtype(), mk_arrdsc(), n, S_CONST, S_EXPR, sem, SHD_NDIM, size_of_shape_dim(), sz, THRESHHOLD, and TRUE.
Referenced by mkexpr_assign_temp().
get_struct_default_init()
static ACL * get_struct_default_init (int sptr) static
Definition at line 5632 of file semutil2.c.
References clone_init_const(), DTC_DEFAULT, DTC_DEFAULT_CNT, NULL, and sptr.
Referenced by _constructf90(), chk_struct_constructor(), and get_exttype_default().
get_subscripting_tmp()
static int get_subscripting_tmp (int indexast) static
Definition at line 2557 of file semutil2.c.
References add_stmt(), ast, astb, ASTB::bnd, ASTB::dtype, get_temp(), mk_assn_stmt(), mk_id(), sub_i, and tmpids.
Referenced by _constructf90().
get_temp()
SPTR get_temp (DTYPE dtype)
Get a compiler temporary of any scalar dtype.
Definition at line 7845 of file semutil2.c.
Referenced by _constructf90(), asn_sfuse(), assign_array_w_forall(), component_init_allocd_auto(), compute_size_ido(), conv_forall(), gen_alloc_dealloc(), gen_dos_over_shape(), get_dobegin(), get_subscripting_tmp(), handle_dependence_ido(), mk_fake_iostat(), precompute_arg_intrin(), ref_intrin(), ref_pd(), ref_stfunc(), rewrite_func_ast(), semant2(), semantio(), tempify(), tempify_ast(), and transform_c_f_pointer().
get_temp_dtype()
DTYPE get_temp_dtype (DTYPE dtype, int expr)
Definition at line 7870 of file semutil2.c.
Referenced by precompute_arg_intrin(), and ref_intrin().
handle_dependence_ido()
static void handle_dependence_ido (ACL * aclp) static
Definition at line 2087 of file semutil2.c.
References acs, add_stmt(), _ACS::aggr_cnt, ast, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), astb, ASTB::bnd, _acl::doinfo, _ACS::doinfo, ASTB::dtype, _std_range::end, _ACS::end, get_temp(), _ACS::ido_level, DOINFO::index_var, DOINFO::init_expr, _ACS::level, DOINFO::limit_expr, _ACS::loop_stmts, _std_range::mid, mk_assn_stmt(), mk_binop(), mk_id(), mk_stmt(), move_range_after(), NULL, ASTB::one, OP_ADD, OP_DIV, OP_MUL, OP_SUB, st, _ACS::start, std, STD_AST, STD_LAST, STD_NEXT, STD_PREV, _acl::std_range, DOINFO::step_expr, _ACS::sumid, _acl::u1, _acl::u2, void(), and ASTB::zero.
Referenced by compute_size_ido().
has_init_value()
int has_init_value (SPTR sptr)
Definition at line 5544 of file semutil2.c.
References DTC_DEFAULT, DTC_DEFAULT_CNT, and sptr.
Referenced by check_derived_type_in_comm(), and dup_struct_init().
have_module_state()
int have_module_state (void)
Definition at line 14116 of file semutil2.c.
References modstate_file, and NULL.
Referenced by semant1().
iexpr_op()
static const char * iexpr_op (int op) static
Definition at line 1032 of file semutil2.c.
References _iexpr_op.
Referenced by _dmp_acl(), _dumpacl(), and _printacl().
in_device_code()
LOGICAL in_device_code (int sptr)
Definition at line 8472 of file semutil2.c.
Referenced by _simple_replacements().
incr_element_cnt()
static void incr_element_cnt () static
Definition at line 2545 of file semutil2.c.
References acs, _ACS::element_cnt, and sub_i.
Referenced by _constructf90().
incr_index()
static bool incr_index (INDEX * index) static
Definition at line 9036 of file semutil2.c.
incr_tmp()
static void incr_tmp (int tmpid) static
Definition at line 2571 of file semutil2.c.
References add_stmt(), ast, astb, ASTB::bnd, ASTB::dtype, mk_assn_stmt(), mk_binop(), ASTB::one, and OP_ADD.
Referenced by _constructf90().
init_constructf90()
static void init_constructf90 () static
Definition at line 2484 of file semutil2.c.
References acs, astb, ASTB::bnd, _ACS::element_cnt, i, _ACS::indx, _ACS::indx_tmpid, ASTB::one, sub_i, _ACS::subs, and tmpids.
Referenced by constructf90().
init_derived_w_acl()
int init_derived_w_acl (int in_sptr, ACL * sconst)
Definition at line 6506 of file semutil2.c.
References add_alloc_mem_initialize(), constructf90(), DTY, _acl::dtype, dtype, get_next_sym(), SEM::sc, sem, sptr, and SYMNAME.
Referenced by _constructf90(), mkarg(), semant3(), and semantio().
init_intrin_type_desc()
static int init_intrin_type_desc (int ast, SPTR sptr, int std) static
This function initializes the type in a descriptor for an object with an intrinsic type.
This function generates a call to set_intrin_type() before the statement descriptor,
Parameters
std.
ast is the ast of the object that has a descriptor that needs to be initialized.
sptr is the symbol table pointer of the object that has a descriptor that needs to be initialized.
std is the statement descriptor that indicates where to add the call to set_intrin_type().
Returns
the std after the set_intrin_type() call.
Definition at line 13391 of file semutil2.c.
References add_stmt_after(), assert, ast, astb, ASTB::bnd, check_member(), DDTG, DT_ISBASIC, ASTB::dtype, dtype_to_arg(), get_member_descriptor(), mk_cval(), mk_id(), mk_set_type_call(), mk_unop(), OP_VAL, sptr, std, and TRUE.
Referenced by gen_automatic_reallocation().
init_named_array_constant()
void init_named_array_constant (int arr, int host)
Initialize a named array constant (array PARAMETER), ensuring that it's only being done within the context of its host subprogram.
Definition at line 1533 of file semutil2.c.
References CONVAL2G, get_getitem_p(), host, and init_sptr_w_acl().
Referenced by fix_module_common(), fixup_param_vars(), and semant2().
init_sdsc()
int init_sdsc (int sptr, DTYPE dtype, int before_std, int parent_sptr)
Definition at line 12741 of file semutil2.c.
References AD_DPTR, AD_LWAST, AD_NUMDIM, AD_UPAST, add_stmt_after(), add_stmt_before(), argt, ARGT_ARG, assert, ast, astb, ASTB::bnd, DDTG, DT_INT, ASTB::dtype, dtype_to_arg(), ERR_Fatal, i, mk_argt(), mk_func_node(), mk_id(), mk_isz_cval(), mk_member(), mkRteRtnNm(), nargs, ndims, NOSYM, RTE_instance, RTE_template, size_of_dtype(), sptr, std, sym_mkfunc(), and TRUE.
Referenced by gen_finalization_for_sym(), gen_kind_parm_assignments(), genPolyAsn(), init_sdsc_bounds(), and init_sdsc_from_dtype().
init_sdsc_bounds()
int init_sdsc_bounds (SPTR sptr, DTYPE dtype, int before_std, SPTR parent_sptr, int subscr, int td_ast)
Similar to init_sdsc() above, but it's also used to initialize a descriptor's bounds from a subscript expression.
Parameters
sptr is the symbol table pointer of the symbol with the descriptor to initialize.
dtype is the dtype used for initializing the descriptor.
before_std is the statement descriptor where we want to insert the initialization code (inserted before this std).
parent_sptr is the symbol table pointer of the enclosing object if sptr is an ST_MEMBER. Otherwise, it can be 0.
subscr is an AST representing the subscript expression that contains the array bounds. If it's not an A_SUBSCR, then init_sdsc() is called instead.
td_ast is an AST representing the descriptor that we are creating an instance of.
Returns
a statement descriptor of the generated statements.
Definition at line 12813 of file semutil2.c.
References AD_DPTR, AD_NUMDIM, ad_val_of(), add_stmt_after(), add_stmt_before(), argt, ARGT_ARG, ASD_SUBS, assert, ast, astb, ASTB::bnd, DDTG, DT_INT, ASTB::dtype, dtype_to_arg(), ERR_Fatal, i, init_sdsc(), mk_argt(), mk_bnd_int(), mk_func_node(), mk_id(), mk_isz_cval(), mk_member(), mkRteRtnNm(), nargs, ndims, NOSYM, RTE_instance, RTE_template, size_of_dtype(), sptr, std, stride, subscr, sym_mkfunc(), and TRUE.
Referenced by rewrite_allocatable_assignment().
init_sptr_w_acl()
int init_sptr_w_acl (int in_sptr, ACL * aclp)
Assign aclp values to in_sptr.
If in_sptr is 0, it assigns values to temporaries. init_sptr_w_acl() is called at the point we are trying to use (a possibly array/struct nested) constructor; eg. in mkexpr1(). If acl is constant, dinit_constructor() uses data initialization to assign the values; otherwise, _construct is called to generate runtime code to assign values. (is_const means: is constant, we can do it, and we're in the right context to do it.)
Definition at line 1620 of file semutil2.c.
References AC_ACONST, AC_IDO, acs, AD_DEFER, AD_DPTR, ADD_DEFER, ADD_EXTNTAST, ADD_LWBD, ADD_NUMDIM, add_stmt_before(), ADD_UPBD, ALLOCATE_ARRAYS, SEM::arrdim, SEM::arrfn, _ACS::arrtype, assert, ast, astb, ASTB::bnd, SEM::bounds, BZERO, constructf90(), convert_ctmp_array_to_param(), DBGBIT, dinit(), dinit_constructor(), SEM::dinit_data, dinit_varref(), _acl::dtype, dtype, ASTB::dtype, ERR_Fatal, FALSE, _ACS::func_in_do, gbl, gen_allocate_array(), get_adjlr_arr_temp(), get_all_descriptors(), get_arr_const(), get_arr_temp(), get_static_descriptor(), i, _acl::id, interr(), _acl::is_const, _ACS::is_const, lb, lbound_of(), memsym_of_ast(), mk_assn_stmt(), mk_id(), ndim, NOSYM, ASTB::one, printacl(), restore_dim_specs(), SEM::return_value, rewrite_acl(), S_IDENT, save_dim_specs(), sem, _acl::size, sptr, SEM::sptr, SST_ASTP, SST_DTYPEP, SST_IDP, SST_SHAPEP, std, STD_NEXT, STD_PREV, _acl::subc, _ACS::tmp, ub, void(), and ASTB::zero.
Referenced by _constructf90(), init_named_array_constant(), mkarg(), mkexpr1(), and mkvarref().
init_types_compatable()
static int init_types_compatable (SST * istkp, DTYPE dtype, int sptr) static
Definition at line 5026 of file semutil2.c.
References cmpat_dtype_with_size(), DDTG, DTY, FALSE, sptr, SST_DTYPEG, and TRUE.
Referenced by construct_acl_for_sst().
insert_assign()
static int insert_assign (int lhs, int rhs, int std) static
Definition at line 12693 of file semutil2.c.
References add_stmt_after(), lhs, mk_assn_stmt(), and std.
Referenced by gen_kind_parm_assignments().
is_alloc_ast()
LOGICAL is_alloc_ast (int ast)
Definition at line 14662 of file semutil2.c.
References A_TKNG, ast, and FALSE.
Referenced by compute_invariant(), invar_motion(), and is_std_hoistable().
is_alloc_std()
LOGICAL is_alloc_std (int std)
Definition at line 14680 of file semutil2.c.
References A_TKNG, ast, FALSE, std, and STD_AST.
Referenced by alldefs_allocsafe().
is_dealloc_ast()
LOGICAL is_dealloc_ast (int ast)
Definition at line 14671 of file semutil2.c.
References A_TKNG, ast, and FALSE.
Referenced by compute_invariant(), invar_motion(), and is_std_hoistable().
is_dealloc_std()
LOGICAL is_dealloc_std (int std)
Definition at line 14692 of file semutil2.c.
References A_TKNG, ast, FALSE, std, and STD_AST.
Referenced by hoist_stmt().
is_illegal_expr_in_init()
static bool is_illegal_expr_in_init (SPTR member_sptr, int ast, DTYPE acl_dtype) static
Definition at line 6489 of file semutil2.c.
References A_OPTYPEG, ast, astb, SEM::dinit_data, DT_PTR, DTY, ASTB::i0, and sem.
Referenced by chk_struct_constructor().
make_structkwd_str()
static char * make_structkwd_str (DTYPE dtype, int * num_of_member, int * is_extend) static
Definition at line 5426 of file semutil2.c.
References avl, BZERO, DTC_ACL_HEAD, DTC_DEFAULT, DTC_DEFAULT_CNT, DTC_DT_CNT, DTY, FREE, i, is_tbp_or_final(), len, make_structkwd_str(), name, NEED, NEW, NOSYM, NULL, num, size, strlen(), and SYMNAME.
Referenced by chk_struct_constructor(), and make_structkwd_str().
map_I_to_AC()
static AC_INTRINSIC map_I_to_AC (int intrin) static
Definition at line 4041 of file semutil2.c.
References AC_I_abs, AC_I_acos, AC_I_asin, AC_I_atan, AC_I_atan2, AC_I_cos, AC_I_exp, AC_I_fltconvert, AC_I_iand, AC_I_ichar, AC_I_ieor, AC_I_ior, AC_I_ishft, AC_I_log, AC_I_log10, AC_I_lshift, AC_I_max, AC_I_maxloc, AC_I_maxval, AC_I_merge, AC_I_min, AC_I_minloc, AC_I_minval, AC_I_mod, AC_I_NONE, AC_I_rshift, AC_I_scale, AC_I_sin, AC_I_sqrt, and AC_I_tan.
Referenced by get_ac_intrinsic().
map_PD_to_AC()
static AC_INTRINSIC map_PD_to_AC (int pdnum) static
Definition at line 4194 of file semutil2.c.
References AC_I_adjustl, AC_I_adjustr, AC_I_ceiling, AC_I_char, AC_I_floor, AC_I_fltconvert, AC_I_ichar, AC_I_index, AC_I_int, AC_I_lbound, AC_I_len_trim, AC_I_maxloc, AC_I_maxval, AC_I_minloc, AC_I_minval, AC_I_nint, AC_I_NONE, AC_I_null, AC_I_repeat, AC_I_reshape, AC_I_scale, AC_I_scan, AC_I_selected_char_kind, AC_I_selected_int_kind, AC_I_selected_real_kind, AC_I_shape, AC_I_size, AC_I_transfer, AC_I_transpose, AC_I_trim, AC_I_ubound, and AC_I_verify.
Referenced by get_ac_intrinsic().
mk_arrdsc()
DTYPE mk_arrdsc (void)
Definition at line 573 of file semutil2.c.
References _mk_arrdsc().
Referenced by chk_constructor(), decl_private_sym(), gen_array_result(), get_shape_arraydtype(), instantiate_interface(), mk_array_type(), mk_size_intrin(), mk_ulbound_intrin(), ref_pd(), and semant1().
mk_assumed_shape()
void mk_assumed_shape (SPTR sptr)
Definition at line 840 of file semutil2.c.
References AD_ASSUMRANK, AD_ASSUMSHP, AD_DPTR, AD_LWAST, AD_LWBD, AD_NUMDIM, SEM::arrdim, astb, ASTB::bnd, dt, i, ASTB::one, sem, sptr, tempvar(), and XBIT.
Referenced by semant1().
mk_cmp()
static void mk_cmp (ACL * c, int op, INT l_conval, INT r_conval, int rdtype, int dt) static
Definition at line 11223 of file semutil2.c.
References const_fold(), dt, get_ast_op(), OP_CMP, OP_EQ, OP_GE, OP_GT, OP_LAND, OP_LE, OP_LEQV, OP_LNEQV, OP_LOR, OP_LT, OP_NE, SCFTN_FALSE, and SCFTN_TRUE.
Referenced by eval_init_op().
mk_defer_shape()
void mk_defer_shape (SPTR sptr)
Definition at line 803 of file semutil2.c.
References AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_NUMDIM, AD_UPAST, dt, i, IN_MODULE_SPEC, mk_bnd_ast(), and sptr.
Referenced by semant1().
mk_dtype_without_dim()
static DTYPE mk_dtype_without_dim (INDEX * index, unsigned dim, DTYPE elem_dtype) static
Definition at line 9069 of file semutil2.c.
mk_elem_init_intrinsic()
static ACL * mk_elem_init_intrinsic (AC_INTRINSIC init_intr, int ast, DTYPE dtype, int parent_acltype) static
Definition at line 3986 of file semutil2.c.
References a, AC_ACONST, ADD_NUMELM, ast, construct_arg_list(), DDTG, SEM::dinit_error, DTY, _acl::dtype, dtype, _acl::expr, GET_ACL, mk_init_intrinsic(), _acl::repeatc, AEXPR::rop, sem, TRUE, and _acl::u1.
Referenced by construct_intrinsic_acl().
mk_init_intrinsic()
ACL * mk_init_intrinsic (AC_INTRINSIC init_intr)
Definition at line 3505 of file semutil2.c.
References AC_ICONST, AC_IEXPR, AC_INTR_CALL, BZERO, _acl::expr, GET_ACL, getitem(), _acl::id, CONST::id, AEXPR::lop, AEXPR::op, _acl::u1, and CONST::u1.
Referenced by init_allocatable_typedef_components(), mk_elem_init_intrinsic(), mk_nonelem_init_intrinsic(), mk_reshape_intrin(), mk_shape_intrin(), mk_size_intrin(), mk_transfer_intrin(), mk_transpose_intrin(), and mk_ulbound_intrin().
mk_nonelem_init_intrinsic()
static ACL * mk_nonelem_init_intrinsic (AC_INTRINSIC init_intr, int ast, DTYPE dtype) static
Definition at line 3972 of file semutil2.c.
References ast, construct_arg_list(), SEM::dinit_error, _acl::dtype, dtype, _acl::expr, mk_init_intrinsic(), AEXPR::rop, sem, and _acl::u1.
Referenced by construct_intrinsic_acl().
mk_reshape_intrin()
static ACL * mk_reshape_intrin (int ast) static
Definition at line 3648 of file semutil2.c.
References a, A_ARGCNTG, AC_AST, AC_I_reshape, ADD_NUMELM, arg_count, argt, ARGT_ARG, ast, astb, construct_acl_from_ast(), SEM::dinit_error, STB::dt_int, _acl::dtype, error(), _acl::expr, gbl, GET_ACL, get_int_cval(), ASTB::i0, mk_init_intrinsic(), CONST::next, NULL, AEXPR::rop, sem, stb, sym_of_ast(), TRUE, _acl::u1, and STB::user.
Referenced by construct_intrinsic_acl().
mk_set_type_call()
int mk_set_type_call (int arg0, int arg1, LOGICAL intrin_type)
Creates an ast that represents a call to a set type runtime routine.
Parameters
arg0 is the ast of the descriptor that receives the type from arg1.
arg1 is the ast of the source descriptor. The type of arg1 is copied into the arg0 descriptor.
intrin_type is true when you want to use the RTE_set_intrin_type() routine instead of the RTE_set_type() routine.
Returns
the call ast
Definition at line 14716 of file semutil2.c.
References ARGT_ARG, func, mk_argt(), mk_func_node(), mk_id(), mkRteRtnNm(), RTE_set_intrin_type, RTE_set_type, and sym_mkfunc_nodesc().
Referenced by check_pointer_type(), gen_poly_element_arg(), gen_set_type(), init_intrin_type_desc(), rewrite_allocatable_assignment(), semant1(), and semant3().
mk_shape_intrin()
static ACL * mk_shape_intrin (int ast) static
Definition at line 3728 of file semutil2.c.
References AC_ACONST, AC_AST, AC_I_shape, argt, ARGT_ARG, ast, astb, STB::dt_int, _acl::dtype, _acl::expr, extent_of_shape(), GET_ACL, i, ASTB::i0, ASTB::i1, _acl::id, lbound_of_shape(), MAXDIMS, mk_init_intrinsic(), r, rank, AEXPR::rop, SHD_NDIM, stb, _acl::subc, TRUE, _acl::u1, ubound_of_shape(), and STB::user.
Referenced by construct_intrinsic_acl().
mk_size_intrin()
static ACL * mk_size_intrin (int ast) static
Definition at line 3784 of file semutil2.c.
References _can_fold(), A_ARGCNTG, AC_ACONST, AC_AST, AC_I_size, arg_count, argt, ARGT_ARG, SEM::arrdim, ast, _acl::ast, astb, SEM::bounds, construct_acl_from_ast(), _acl::conval, SEM::dinit_error, STB::dt_int, DTY, _acl::dtype, dtype, error(), eval_init_expr_item(), _acl::expr, extent_of_shape(), gbl, GET_ACL, i, ASTB::i0, _acl::id, mk_arrdsc(), mk_convert(), mk_cval(), mk_init_intrinsic(), _acl::next, CONST::next, NULL, rank, AEXPR::rop, S_CONST, sem, SHD_LWB, SHD_NDIM, SHD_UPB, size_of_ast(), stb, _acl::subc, TRUE, _acl::u1, and STB::user.
Referenced by construct_intrinsic_acl().
mk_transfer_intrin()
static ACL * mk_transfer_intrin (int ast) static
Definition at line 3903 of file semutil2.c.
References AC_AST, AC_I_transfer, argt, ARGT_ARG, ast, construct_acl_from_ast(), DDTG, SEM::dinit_error, _acl::dtype, _acl::expr, GET_ACL, mk_cval(), mk_init_intrinsic(), _acl::next, AEXPR::rop, sem, TRUE, and _acl::u1.
Referenced by construct_intrinsic_acl().
mk_transpose_intrin()
static ACL * mk_transpose_intrin (int ast) static
Definition at line 3629 of file semutil2.c.
References AC_I_transpose, argt, ARGT_ARG, ast, construct_acl_from_ast(), _acl::dtype, _acl::expr, mk_init_intrinsic(), AEXPR::rop, and _acl::u1.
Referenced by construct_intrinsic_acl().
mk_ulbound_intrin()
static ACL * mk_ulbound_intrin (AC_INTRINSIC intrin, int ast) static
Definition at line 3522 of file semutil2.c.
References _can_fold(), A_ARGCNTG, AC_ACONST, AC_AST, AC_I_lbound, AC_I_ubound, arg_count, argt, ARGT_ARG, SEM::arrdim, ast, astb, SEM::bounds, construct_acl_from_ast(), _acl::conval, SEM::dinit_error, STB::dt_int, DTY, _acl::dtype, error(), eval_init_expr_item(), _acl::expr, extent_of_shape(), FALSE, gbl, GET_ACL, get_int_cval(), i, ASTB::i1, _acl::id, lbound_of_shape(), MAXDIMS, mk_arrdsc(), mk_convert(), mk_cval(), mk_init_intrinsic(), CONST::next, NULL, r, rank, AEXPR::rop, S_CONST, sem, SHD_NDIM, stb, _acl::subc, TRUE, _acl::u1, ubound_of_shape(), and STB::user.
Referenced by construct_intrinsic_acl().
mkexpr_assign_temp()
static void mkexpr_assign_temp (SST * stkptr) static
Definition at line 2638 of file semutil2.c.
References a, acs, add_stmt(), SEM::arrdim, _ACS::arrtype, ast, ast_rewrite_indices(), dest, DTY, dtype, FALSE, gen_allocate_array(), get_arr_temp(), get_shape_arraydtype(), is_deferlenchar_ast(), mk_assn_stmt(), mk_id(), mkexpr(), sem, SST_ASTG, SST_ASTP, and SST_DTYPEG.
Referenced by _constructf90().
module_must_hide_this_symbol()
void module_must_hide_this_symbol (int sptr)
Definition at line 14037 of file semutil2.c.
References module_must_hide_this_symbol_sptr, and sptr.
Referenced by replace_variable().
mp_create_bscope()
int mp_create_bscope (int reuse)
Definition at line 14408 of file semutil2.c.
References add_stmt(), ast, BLK_SCOPE_SPTR, BLK_UPLEVEL_SPTR, SEM::blksymnum, getccssym(), i, llmp_create_uplevel(), llmp_uplevel_set_parent(), mk_id(), mk_stmt(), SEM::scope_level, sem, and void().
Referenced by begin_combine_constructs(), do_btarget(), do_bteams(), do_distbegin(), and semsmp().
mp_create_escope()
int mp_create_escope (void)
Definition at line 14462 of file semutil2.c.
References add_stmt(), ast, BLK_UPLEVEL_SPTR, mk_stmt(), SEM::scope_level, sem, and void().
Referenced by do_end(), end_target(), end_teams(), and semsmp().
need_alloc_ch_temp()
int need_alloc_ch_temp (DTYPE dtype)
Definition at line 8164 of file semutil2.c.
Referenced by ref_pd().
next_member()
static int next_member (int member) static
Definition at line 4868 of file semutil2.c.
References NOSYM.
Referenced by rewrite_acl().
not_in_forall()
LOGICAL not_in_forall (const char * stmttype)
Check if we are currently in a block FORALL scope; if so, issue an error message.
Definition at line 8452 of file semutil2.c.
Referenced by misc_io_checks(), and semant3().
pop_subscript()
static void pop_subscript () static
Definition at line 2533 of file semutil2.c.
References sub_i.
Referenced by _constructf90(), and constructf90().
printacl()
void printacl (const char * s, ACL * aclp, FILE * f)
Definition at line 1151 of file semutil2.c.
References _printacl(), acl_array_num, f, gbl, NULL, and s.
Referenced by _constructf90(), chk_constructor(), chk_struct_constructor(), get_exttype_struct_constructor(), and init_sptr_w_acl().
push_subscript()
static void push_subscript () static
Definition at line 2527 of file semutil2.c.
References sub_i.
Referenced by _constructf90(), and constructf90().
put_a_init_tree()
static void put_a_init_tree (int ast, int dinit_array) static
Definition at line 5237 of file semutil2.c.
References _dinit_acl(), AC_AST, _acl::array_i, ast, _acl::ast, dinit_array, DINIT_ENDTYPE, dinit_put(), DINIT_TYPEDEF, DTY, _acl::dtype, FALSE, _acl::id, interr(), _acl::next, NULL, put_a_init_tree(), _acl::subc, _acl::u1, and _acl::u2.
Referenced by _dinit_acl(), and put_a_init_tree().
put_prefix()
static void put_prefix (char * str, int cnt, FILE * f) static
Definition at line 14398 of file semutil2.c.
References cnt, f, i, and str.
Referenced by _dmp_acl().
remove_parent_from_ast()
static int remove_parent_from_ast (int ast) static
Definition at line 12448 of file semutil2.c.
References A_ARGCNTG, A_ARGCNTP, A_OPTYPEG, A_OPTYPEP, ARGT_ARG, ast, i, interr(), memsym_of_ast(), mk_argt(), mk_binop(), mk_convert(), mk_id(), mk_stmt(), mk_subscr_copy(), mk_unop(), nargs, and remove_parent_from_ast().
Referenced by fix_mem_bounds2(), and remove_parent_from_ast().
reset_internal_subprograms()
void reset_internal_subprograms (void)
Definition at line 13953 of file semutil2.c.
References FALSE, state_append_file_full, state_file_position, and state_still_pass_one.
Referenced by parser().
reset_module_state()
void reset_module_state (void)
Called at the end of a module-contained subprogram; rearranges the data structures for the module.
Definition at line 14093 of file semutil2.c.
References errfatal(), export_module_subprogram(), gbl, interr(), modsaved_astavl, modsaved_dtyavl, modsaved_symavl, modstate_append_file, modstate_append_file_full, modstate_file, NULL, rw_host_state(), sem, tmpfile(), and SEM::which_pass.
Referenced by mod_end_subprogram_two().
restore_dim_specs()
static void restore_dim_specs (SEM_DIM_SPECS * aa) static
Definition at line 588 of file semutil2.c.
References SEM_DIM_SPECS::arrdim, SEM::arrdim, BCOPY, SEM::bounds, SEM::in_dim, MAXDIMS, and sem.
Referenced by chk_constructor(), and init_sptr_w_acl().
restore_host_state()
void restore_host_state (int whichpass)
Called at the end of an internal subprogram.
In pass 1:
Save the internal subprogram information, kind of like interface blocks. If there is more than 1 internal subprogram, the information is exported collectively, that is, all subprograms are exported each time.
Save any labels for internal subprograms. These labels are restored by restore_internal_subprograms() below.
Restores the host information for the next subprogram.
Reimport any internal subprograms as contained subprograms. This information will be reimported in pass 2 by restore_internal_subprograms() below.
In pass 2:
Restore the host information for the next subprogram, as this will have been saved by the save_host_state call for the host subprogram and will include all the contained subprograms information as imported in restore_internal_subprograms() for the host routine.
Definition at line 13759 of file semutil2.c.
References errfatal(), export_append_host_sym(), export_host_subprogram(), fflush(), STB::firstusym, fix_symtab(), SEM::flabels, gbl, import_host_subprogram(), interr(), len, SEM::mod_sym, NEED, NEW, NOSYM, NULL, rw_host_state(), saved_astavl, saved_dtyavl, saved_labels, saved_labels_avail, saved_labels_pos, saved_labels_size, saved_symavl, SEM::scope_level, SEM::scope_stack, sem, SCOPESTACK::sptr, state_append_file, state_append_file_full, state_file, state_file_position, state_last_routine, state_still_pass_one, stb, strlen(), SYMNAME, tmpfile(), and TRUE.
Referenced by semant1(), and semant_init().
restore_imported_modules_state()
void restore_imported_modules_state ()
Definition at line 14015 of file semutil2.c.
References modsave_file, and rw_host_state().
restore_internal_subprograms()
void restore_internal_subprograms (void)
Called at the beginning of a subprogram in pass 2.
Checks whether there is information available for subprograms contained in this one, as saved by restore_host_state().
If so, restores that more or less like an interface block.
If the current routine is an internal subprogram, its labels are restored. This is so FORMAT labels that appear in both the inner and outer subprogram are properly resolved.
Definition at line 13882 of file semutil2.c.
References cp, STB::curr_scope, dummy_program(), exterf_init_host(), gbl, getsymbol(), import_host(), insert_sym(), interr(), SEM::mod_sym, NOSYM, saved_astavl, saved_dtyavl, saved_labels, saved_labels_pos, saved_symavl, SEM::scope_level, SEM::scope_stack, sem, sptr, SCOPESTACK::sptr, state_append_file, state_append_file_full, state_file_position, state_still_pass_one, stb, strlen(), and SYMNAME.
Referenced by semant1().
restore_module_state()
void restore_module_state (void)
Called at start of module-contained subprogram, restores state. If this is the first 'restore' since the last 'reset', the 'module append' file is full and needs to be imported.
Definition at line 14047 of file semutil2.c.
References astb, STB::dt, errfatal(), gbl, SEM::ieee_features, import_host(), mod_clear_init, modsave_ieee_features, modsaved_astavl, modsaved_dtyavl, modsaved_symavl, modstate_append_file, modstate_append_file_full, modstate_file, module_must_hide_this_symbol_sptr, NOSYM, NULL, rw_host_state(), sem, sptr, and stb.
Referenced by mod_init().
rewrite_acl()
ACL * rewrite_acl (ACL * aclp, DTYPE dtype, int parent_acltype)
Definition at line 4880 of file semutil2.c.
References AC_ACONST, AC_AST, AC_EXPR, AC_IDO, AC_IEXPR, AC_REPEAT, AC_SCONST, AC_TYPEINIT, ADD_NUMELM, ast, _acl::ast, construct_acl_from_ast(), DDTG, SEM::dinit_error, _acl::doinfo, DTY, _acl::dtype, dtype, errsev(), GET_ACL, get_doinfo(), _acl::id, DOINFO::index_var, interr(), _acl::is_const, is_zero_size_typedef(), mk_id(), mkexpr(), _acl::next, next_member(), no_data_components(), NULL, _acl::repeatc, rewrite_acl(), S_ACONST, S_CONST, S_EXPR, S_IDENT, sem, sptr, _acl::sptr, SST_ACLG, SST_ASTG, SST_IDG, SST_SYMG, _acl::stkp, _acl::subc, TRUE, and _acl::u1.
Referenced by construct_acl_for_sst(), init_sptr_w_acl(), rewrite_acl(), and semant1().
rewrite_typeinit_to_sconst()
static ACL * rewrite_typeinit_to_sconst (ACL * ict) static
Definition at line 5554 of file semutil2.c.
References AC_SCONST, AC_TYPEINIT, _acl::dtype, GET_ACL, _acl::id, _acl::next, _acl::repeatc, rewrite_typeinit_to_sconst(), and _acl::subc.
Referenced by rewrite_typeinit_to_sconst(), and save_struct_init().
runtime_array()
int runtime_array (int ast)
Return TRUE if the expression at 'ast' is composed of constants and the special symbol 'hpf_np$'. In this case, even though the bound is not a literal constant, it is a runtime constant.
Definition at line 171 of file semutil2.c.
References ast, DBGBIT, FALSE, gbl, runtime_array(), and TRUE.
Referenced by _mk_arrdsc(), and runtime_array().
rw_host_state()
static void rw_host_state (int wherefrom, int(*)() p_rw, FILE * fd) static
Definition at line 13572 of file semutil2.c.
References fd, rw_ast_state(), rw_dinit_state(), rw_dpmout_state(), rw_dtype_state(), rw_gnr_state(), rw_import_state(), rw_mod_state(), rw_semant_state(), and rw_sym_state().
Referenced by reset_module_state(), restore_host_state(), restore_imported_modules_state(), restore_module_state(), save_host_state(), save_imported_modules_state(), save_module_state1(), and save_module_state2().
save_acl()
ACL * save_acl (ACL * oldp)
Definition at line 5145 of file semutil2.c.
References AC_ACONST, AC_AST, AC_CONST, AC_EXPR, AC_ICONST, AC_IDO, AC_IEXPR, AC_REPEAT, AC_SCONST, ACL_SAVE_AREA, _acl::ast, _acl::doinfo, _acl::expr, GET_ACL, get_doinfo(), _acl::id, interr(), AEXPR::lop, _acl::next, NULL, _acl::repeatc, AEXPR::rop, S_ACONST, save_acl(), _acl::size, SST_ACLG, SST_ASTG, SST_IDG, _acl::stkp, _acl::subc, TRUE, and _acl::u1.
Referenced by save_acl(), and semant1().
save_dim_specs()
static void save_dim_specs (SEM_DIM_SPECS * aa) static
Definition at line 579 of file semutil2.c.
References SEM_DIM_SPECS::arrdim, SEM::arrdim, BCOPY, SEM::bounds, SEM::in_dim, MAXDIMS, and sem.
Referenced by chk_constructor(), and init_sptr_w_acl().
save_host_state()
void save_host_state (int wherefrom)
Called from semant.c to save the semant, sym, dtype, ast, and other 'state' information from a host routine for internal subprograms, for 'pass 1'. Also, for 'pass 2', save_host_state is called to overwrite the semant state information.
Definition at line 13635 of file semutil2.c.
References astb, STB::dt, errfatal(), STB::firstusym, NULL, rw_host_state(), saved_astavl, saved_dtyavl, saved_symavl, sptr, state_file, stb, and tmpfile().
Referenced by semant1().
save_imported_modules_state()
void save_imported_modules_state ()
Definition at line 14002 of file semutil2.c.
References errfatal(), modsave_file, NULL, rw_host_state(), and tmpfile().
save_module_state1()
void save_module_state1 (void)
Called at a CONTAINS clause.
Writes the module information out quickly. It is split into two pieces: the first only writes out the semant information, before semfin() deallocates it, and the second appends everything else, including the module.c tables.
Definition at line 13975 of file semutil2.c.
References errfatal(), modstate_file, NULL, rw_host_state(), and tmpfile().
Referenced by begin_contains().
save_module_state2()
void save_module_state2 (void)
Definition at line 13988 of file semutil2.c.
References astb, STB::dt, SEM::ieee_features, mod_clear_init, modsave_ieee_features, modsaved_astavl, modsaved_dtyavl, modsaved_symavl, modstate_append_file_full, modstate_file, rw_host_state(), sem, and stb.
Referenced by begin_contains().
save_struct_init()
void save_struct_init (ACL * ict)
Definition at line 5597 of file semutil2.c.
References AC_TYPEINIT, BZERO, DTC_DEFAULT, DTC_DEFAULT_CNT, DTC_DEFAULT_HEAD, _acl::id, NEED, rewrite_typeinit_to_sconst(), sptr, and _acl::sptr.
Referenced by build_typedef_init_tree(), getict(), and semant1().
select_kind()
DTYPE select_kind (DTYPE dtype, int ty, INT kind_val)
Definition at line 875 of file semutil2.c.
References CNULL, dtype, error(), gbl, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_REAL, and XBIT.
Referenced by do_dot(), get_number(), get_retval_KIND_value(), put_kind_type_param(), ref_pd(), semant1(), and set_kind_result().
sem_eq_str()
LOGICAL sem_eq_str (int con, const char * pattern)
Return TRUE if fortran character constant is equal to pattern (pattern is always uppercase).
...
Definition at line 8210 of file semutil2.c.
sem_err104()
void sem_err104 (int df, int lineno, const char * str)
Definition at line 14590 of file semutil2.c.
References buff, CNULL, df, DI_ID, di_name, error(), interr(), lineno, and str.
Referenced by end_subprogram_checks(), and sem_err105().
sem_err105()
void sem_err105 (int df)
Definition at line 14606 of file semutil2.c.
References df, DI_ID, di_name, errsev(), gbl, and sem_err104().
Referenced by semant3().
sem_fini()
void sem_fini (void)
Compilation is finished - deallocate storage, close files, etc.
Definition at line 14126 of file semutil2.c.
References SEM::eqv_base, SEM::eqv_ss_base, fclose(), FREE, import_fini(), SEM::non_private_base, NULL, saved_labels, saved_labels_avail, saved_labels_pos, saved_labels_size, sem, state_append_file, and state_file.
Referenced by finish().
sem_set_storage_class()
void sem_set_storage_class (int sptr)
Definition at line 14157 of file semutil2.c.
References add_auto_array(), add_auto_char(), add_auto_dealloc(), CNULL, error(), gbl, has_allocattr(), IS_INTRINSIC, RUNTIMEG, sptr, and SYMNAME.
Referenced by chkarg(), find_outer_sym(), get_type_rank(), misc_checks(), mkarg(), mkexpr1(), mklvalue(), mkvarref(), semant2(), semant3(), and semantio().
sem_strcmp()
int sem_strcmp (const char * str, const char * pattern)
Compare str and pattern like strcmp() but ignoring the case of str. pattern is all lower case.
Definition at line 8186 of file semutil2.c.
Referenced by _do_iface(), cancel_type(), clear_iface(), sched_type(), semant1(), and semant2().
sem_tempify()
int sem_tempify (SST * stkptr)
Allocate a temporary, assign it the value, and return the assignment ast.
Definition at line 8244 of file semutil2.c.
Referenced by check_etmp(), func_call2(), gen_and_assoc_tmp_ptr(), precompute_args(), ptrfunc_call(), semant3(), semantio(), and subr_call2().
set_exttype_list()
static int set_exttype_list (ACL * aclp) static
Definition at line 5724 of file semutil2.c.
References DTC_ACL, DTC_DT_CNT, first, i, and NULL.
Referenced by chk_struct_constructor().
size_of_array()
ISZ_T size_of_array (DTYPE dtype)
Check if array has zero size.
It expects lowerbound and upper bound to be constant asts. Don't use NUM_ELEM because it could return 1 as number of element, If dtype is zero, it loosely check aggregate size which must be done after chk_constructor/(2).
Definition at line 1399 of file semutil2.c.
References acs, AD_DPTR, AD_LWAST, AD_NUMDIM, AD_UPAST, ad_val_of(), _ACS::aggr_cnt, assert, astb, ASTB::bnd, d, DEFAULT_DIM_SIZE, DTY, i, interr(), ISZ_T, _ACS::scalar_cnt, size, sym_of_ast(), and ASTB::zero.
Referenced by dinit_data(), and semant1().
size_of_dtype()
static int size_of_dtype (DTYPE dtype, SPTR sptr, int memberast) static
Definition at line 12715 of file semutil2.c.
References add_arg(), astb, begin_call(), ASTB::bnd, check_member(), DTY, ASTB::dtype, mk_bnd_int(), mk_id(), mk_isz_cval(), mkRteRtnNm(), RTE_lena, size_of(), sptr, sym_mkfunc_nodesc(), and TY_CHAR.
Referenced by init_sdsc(), and init_sdsc_bounds().
size_of_shape_dim()
static int size_of_shape_dim (int shape, int i) static
Definition at line 2583 of file semutil2.c.
References astb, ASTB::bnd, ASTB::dtype, i, mk_binop(), ASTB::one, OP_ADD, OP_DIV, OP_SUB, SHD_LWB, SHD_STRIDE, SHD_UPB, and sz.
Referenced by get_shape_arraydtype().
tempvar()
static int tempvar (int astx) static
Definition at line 831 of file semutil2.c.
Referenced by mk_assumed_shape().
to_assumed_shape()
static void to_assumed_shape (int arg) static
Definition at line 145 of file semutil2.c.
References AD_ASSUMSHP, AD_DPTR, AD_LWAST, AD_LWBD, AD_NUMDIM, arg, astb, ASTB::bnd, i, ndim, ASTB::one, and XBIT.
Referenced by chk_adjarr().
transfer_load()
static INT transfer_load (DTYPE dtype, char * source) static
Definition at line 9721 of file semutil2.c.
transfer_store()
static void transfer_store (INT conval, DTYPE dtype, char * destination) static
Definition at line 9668 of file semutil2.c.
unop_init_list()
static int unop_init_list (int llist, int optype) static
Definition at line 6933 of file semutil2.c.
References interr(), last, list, mk_init(), mk_unop(), optype(), and unop_init_list().
Referenced by unop_init_list().
valid_kind_parm_expr()
static int valid_kind_parm_expr (int ast) static
Definition at line 216 of file semutil2.c.
References A_OPTYPEG, ARGT_ARG, ast, i, memsym_of_ast(), sptr, and valid_kind_parm_expr().
Referenced by _mk_arrdsc(), and valid_kind_parm_expr().
Variable Documentation
_iexpr_op
const char* _iexpr_op[] static
Initial value:
= {
    "?0?",       "ADD",      "SUB",       "MUL",  "DIV",    "EXP",  "NEG",
    "INTR_CALL", "ARRAYREF", "MEMBR_SEL", "CONV", "CAT",    "EXPK", "LEQV",
    "LNEQV",     "LOR",      "LAND",      "EQ",   "GE",     "GT",   "LE",
    "LT",        "NE",       "LNOT",      "EXPX", "TRIPLE",
}
Definition at line 1024 of file semutil2.c.
Referenced by iexpr_op().
acl_array_num
int acl_array_num = 0 static
Definition at line 1022 of file semutil2.c.
Referenced by _printacl(), dumpacl(), and printacl().
acs
_ACS acs static
Definition at line 1017 of file semutil2.c.
Referenced by _constructf90(), add_subscript(), check_dependence_ido(), chk_constructor(), clear_element_cnt(), compute_size(), compute_size_ast(), compute_size_expr(), compute_size_ido(), compute_size_sconst(), constructf90(), gen_allocate_array(), get_element_cnt(), get_shape_arraydtype(), handle_dependence_ido(), incr_element_cnt(), init_constructf90(), init_sptr_w_acl(), mkexpr_assign_temp(), and size_of_array().
ALLOCATE_ARRAYS
int ALLOCATE_ARRAYS = TRUE static
Definition at line 1540 of file semutil2.c.
Referenced by init_sptr_w_acl().
arrbase
ACL* arrbase
Definition at line 10967 of file semutil2.c.
cw_array_num
int cw_array_num = 0 static
Definition at line 1331 of file semutil2.c.
Referenced by _compute_width(), and compute_width().
di_name
const char* di_name[] static
Definition at line 14525 of file semutil2.c.
Referenced by _dmp_doif(), sem_err104(), and sem_err105().
struct { ... } dim[MAXDIMS]
Referenced by build_subscript_list(), and eval_sub_index().
dinit_array
int dinit_array = 0 static
Definition at line 5207 of file semutil2.c.
Referenced by _dinit_acl(), and put_a_init_tree().
dt_init
struct_init dt_init = {0, 0, NULL, NULL} static
Definition at line 5416 of file semutil2.c.
dtype
DTYPE dtype
Definition at line 10970 of file semutil2.c.
Referenced by _compute_width(), _constructf90(), _dinit_acl(), _dumpacl(), _mk_arrdsc(), _printacl(), add_dt_subscr(), build_array_list(), chk_constructor(), chk_struct_constructor(), compute_size_ast(), compute_size_expr(), compute_size_sconst(), construct_acl_from_ast(), constructf90(), eval_init_op(), gen_alloc_dealloc(), gen_alloc_mem_initialize_for_sym2(), gen_finalization_for_sym(), gen_kind_parm_assignments(), get_dtype_init_template(), init_derived_w_acl(), init_sptr_w_acl(), mk_elem_init_intrinsic(), mk_nonelem_init_intrinsic(), mk_size_intrin(), mkexpr_assign_temp(), rewrite_acl(), and select_kind().
firstalloc
int firstalloc static
Definition at line 12072 of file semutil2.c.
Referenced by check_alloc_clauses(), check_dealloc_clauses(), and gen_alloc_dealloc().
idx
ISZ_T idx
Definition at line 10971 of file semutil2.c.
lowb
ISZ_T lowb
Definition at line 10973 of file semutil2.c.
Referenced by arrayref_size().
max_cw_array_num
int max_cw_array_num = 0 static
Definition at line 1332 of file semutil2.c.
Referenced by _compute_width(), and compute_width().
mod_clear_init
int mod_clear_init = 0 static
Definition at line 13964 of file semutil2.c.
Referenced by restore_module_state(), and save_module_state2().
modsave_file
FILE* modsave_file = NULL static
Definition at line 13999 of file semutil2.c.
Referenced by restore_imported_modules_state(), and save_imported_modules_state().
modsave_ieee_features
LOGICAL modsave_ieee_features static
Definition at line 13965 of file semutil2.c.
Referenced by restore_module_state(), and save_module_state2().
modsaved_astavl
int modsaved_astavl static
Definition at line 13962 of file semutil2.c.
Referenced by reset_module_state(), restore_module_state(), and save_module_state2().
modsaved_dtyavl
int modsaved_dtyavl static
Definition at line 13962 of file semutil2.c.
Referenced by reset_module_state(), restore_module_state(), and save_module_state2().
modsaved_symavl
int modsaved_symavl static
Definition at line 13962 of file semutil2.c.
Referenced by reset_module_state(), restore_module_state(), and save_module_state2().
modstate_append_file
FILE* modstate_append_file = NULL static
Definition at line 13961 of file semutil2.c.
Referenced by reset_module_state(), and restore_module_state().
modstate_append_file_full
int modstate_append_file_full = 0 static
Definition at line 13963 of file semutil2.c.
Referenced by reset_module_state(), restore_module_state(), and save_module_state2().
modstate_file
FILE* modstate_file = NULL static
Definition at line 13960 of file semutil2.c.
Referenced by have_module_state(), reset_module_state(), restore_module_state(), save_module_state1(), and save_module_state2().
module_must_hide_this_symbol_sptr
int module_must_hide_this_symbol_sptr = 0 static
Definition at line 14034 of file semutil2.c.
Referenced by module_must_hide_this_symbol(), and restore_module_state().
mplyr
ISZ_T mplyr
Definition at line 10980 of file semutil2.c.
Referenced by complex_alias(), create_array_subscr(), and inlarr().
ndims
int ndims
Definition at line 10968 of file semutil2.c.
Referenced by _makezero(), allocate_array(), bnds_remap_list(), charintr_arg_forall_depnd(), contiguous_array_section(), contiguous_section(), contiguous_section_array(), continuous_section(), copy_inargs(), eval_const_array_section(), eval_const_array_triple_section(), export_dt(), gen_early_array_bnds(), gen_early_bnd_dependencies(), get_forall_subscr(), has_invar_subs(), import(), init_sdsc(), init_sdsc_bounds(), mk_forall_sptr(), mmul_array(), nml_check_item(), nml_emit_desc(), replace_parms(), rewrite_allocatable_assignment(), rewrite_func_ast(), rewrite_inlined_args(), and stride_1_section().
newindex
int newindex[MAXDIMS] static
Definition at line 2751 of file semutil2.c.
Referenced by ast_replace_index(), and ast_rewrite_indices().
numindex
int numindex static
Definition at line 2751 of file semutil2.c.
Referenced by _constructf90(), ast_replace_index(), ast_rewrite_indices(), and constructf90().
oldindex
int oldindex[MAXDIMS] static
Definition at line 2751 of file semutil2.c.
Referenced by ast_replace_index(), and ast_rewrite_indices().
out_of_elements_message
LOGICAL out_of_elements_message static
Definition at line 6565 of file semutil2.c.
root
ACL* root
Definition at line 10965 of file semutil2.c.
Referenced by addarth(), eval_array_constructor(), eval_do(), eval_init_expr(), eval_init_op(), fast_math(), frte_func(), gnr_math(), markrootss(), relaxed_math(), rewrite_func_ast(), and vect_math().
roottail
ACL* roottail
Definition at line 10966 of file semutil2.c.
saved_astavl
int saved_astavl = 0 static
Definition at line 13605 of file semutil2.c.
Referenced by restore_host_state(), restore_internal_subprograms(), and save_host_state().
saved_dtyavl
int saved_dtyavl = 0 static
Definition at line 13606 of file semutil2.c.
Referenced by restore_host_state(), restore_internal_subprograms(), and save_host_state().
saved_labels
char* saved_labels = NULL static
Definition at line 13625 of file semutil2.c.
Referenced by restore_host_state(), restore_internal_subprograms(), and sem_fini().
saved_labels_avail
int saved_labels_avail = 0 static
Definition at line 13626 of file semutil2.c.
Referenced by restore_host_state(), and sem_fini().
saved_labels_pos
int saved_labels_pos = 0 static
Definition at line 13626 of file semutil2.c.
Referenced by restore_host_state(), restore_internal_subprograms(), and sem_fini().
saved_labels_size
int saved_labels_size = 0 static
Definition at line 13626 of file semutil2.c.
Referenced by restore_host_state(), and sem_fini().
saved_symavl
int saved_symavl = 0 static
Definition at line 13604 of file semutil2.c.
Referenced by restore_host_state(), restore_internal_subprograms(), and save_host_state().
struct { ... } sb
Referenced by eval_const_array_section(), eval_const_array_triple_section(), eval_sb(), and eval_sub_index().
state_append_file
FILE* state_append_file = NULL static
Definition at line 13603 of file semutil2.c.
Referenced by restore_host_state(), restore_internal_subprograms(), and sem_fini().
state_append_file_full
LOGICAL state_append_file_full = FALSE static
Definition at line 13608 of file semutil2.c.
Referenced by reset_internal_subprograms(), restore_host_state(), and restore_internal_subprograms().
state_file
FILE* state_file = NULL static
Definition at line 13602 of file semutil2.c.
Referenced by restore_host_state(), save_host_state(), and sem_fini().
state_file_position
long state_file_position = 0 static
Definition at line 13609 of file semutil2.c.
Referenced by reset_internal_subprograms(), restore_host_state(), and restore_internal_subprograms().
state_last_routine
int state_last_routine = 0 static
Definition at line 13610 of file semutil2.c.
Referenced by restore_host_state().
state_still_pass_one
LOGICAL state_still_pass_one = FALSE static
Definition at line 13607 of file semutil2.c.
Referenced by reset_internal_subprograms(), restore_host_state(), and restore_internal_subprograms().
stride
ISZ_T stride
Definition at line 10975 of file semutil2.c.
Referenced by build_array_list(), and init_sdsc_bounds().
struct { ... } sub[MAXDIMS]
Referenced by _makezero(), add_arrnme(), ast_rewrite(), build_sym_nme(), dd_array_conflict(), do_subscript(), dumpsubinfo(), eliminate_alloc(), eliminate_copy(), eliminate_gather(), eliminate_sect(), eliminate_shift(), eliminate_start(), ENTF90(), fill_subscripts(), find_pointer_variable_assign(), gen_bnd_assn(), gen_dos_over_shape(), has_invar_subs(), inline_ast(), is_nonscalar_array_in_expr(), is_same_array_bounds(), is_vector_indirection_in_it(), is_whole_dim(), left_nonscalar_subscript_ast(), lookupnme(), makezero(), mk_asd(), mk_offset(), mk_subscr_copy(), mkSub(), opt_allocate(), process_sub(), promote_assumsz_arg(), reciprocal_mod(), reciprocal_mod_64(), remove_from_scalar_subscript(), remove_function_common_from_scalar_subscript(), rewrite_triples(), subscript_allocmem(), subst_lhs_arrfn(), transform_ptr(), and visit_nme_subscript().
sub_i
int sub_i = 7 static
Definition at line 2480 of file semutil2.c.
Referenced by add_subscript(), clear_element_cnt(), constructf90(), get_element_cnt(), get_subscripting_tmp(), incr_element_cnt(), init_constructf90(), pop_subscript(), and push_subscript().
subscr_base
ACL* subscr_base
Definition at line 10972 of file semutil2.c.
Referenced by eval_sub_index().
temps_ctr
int temps_ctr[3] static
Definition at line 83 of file semutil2.c.
tmpids
int tmpids[MAXDIMS] static
Definition at line 2481 of file semutil2.c.
Referenced by get_subscripting_tmp(), and init_constructf90().
upb
ISZ_T upb
Definition at line 10974 of file semutil2.c.
Referenced by const_eval().