flang: semutil0.cpp File Reference
semutil0.cpp File Reference
SCFTN semantic analyzer module element.
#include "semutil0.h"
#include "gbldefs.h"
#include "error.h"
#include "global.h"
#include "semant.h"
#include "symtab.h"
#include "ilm.h"
#include "ilmtp.h"
#include "machar.h"
#include "outliner.h"
#include "dtypeutl.h"
#include "expand.h"
Macros
#define SERROR(e, f, c)
#define ERR170(s) error((error_code_t)170, ERR_Warning, gbl.lineno, s, CNULL)
Functions
void semant_reinit (void)
Initialize semantic analyzer for new user subprogram unit.
void semant_init (void)
Initialize semantic analyzer.
int getrval (int ilmptr)
Dereference an ilm pointer to determine the rvalue i.e. its symbol pointer.
static void holtonum (char *cp, INT num[4], int bc)
Convert a hollerith constant to a numeric value. The destination can be any one of the 5 available sizes 1 byte, 2 bytes, 4 bytes, 8 bytes, or 16 bytes.
static int hex2char (INT hexval[2])
Convert doubleword hex/octal value to a character.
static int hex2nchar (INT hexval[2])
Convert doubleword hex/octal value to an ncharacter.
INT cngcon (INT oldval, DTYPE oldtyp, DTYPE newtyp)
Convert constant from oldtyp to newtyp.
bool sem_eq_str (int con, const char *pattern)
Return TRUE if fortran character constant is equal to pattern (pattern is always uppercase).
Detailed Description
SCFTN semantic analyzer module element.
Definition in file semutil0.cpp.
Macro Definition Documentation
ERR170
#define ERR170 (s) error((error_code_t)170, ERR_Warning, gbl.lineno, s, CNULL)
Definition at line 33 of file semutil0.cpp.
SERROR
#define SERROR (e, f, c)
Value:
  {                                     \
    char bf[20];                        \
    sprintf(bf, f, c);                  \
    error((error_code_t)e, ERR_Warning, gbl.lineno, bf, CNULL); \
  }
Definition at line 26 of file semutil0.cpp.
Function Documentation
cngcon()
INT cngcon (INT oldval, DTYPE oldtyp, DTYPE newtyp)
Convert constant from oldtyp to newtyp.
...
Issue error messages only for impossible conversions. Return constant value for 32-bit constants, or symbol table pointer. Can only be used for scalar constants.
Remember: Non-decimal constants are octal, hexadecimal, or hollerith constants which are represented by DT_WORD, DT_DWORD and DT_HOLL. Non-decimal constants 'assume' data types rather than go thru a conversion. Hollerith constants have a data type of DT_HOLL in the semantic stack, however, the symbol table entry they point to has a data type of DT_CHAR.
Hollerith constants are always treated as scalars while octal or hexadecimal constants can be promoted to vectors.
Definition at line 379 of file semutil0.cpp.
References AREA_SIZE, BCOPY, CONVAL2G, cp, STB::dbl0, DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_INT, DTY, FLG::endian, ERR170, errinfo(), errsev(), errwarn(), FLANG_FALLTHROUGH, flg, get_acon(), get_type(), getcon(), getitem(), getstring(), hex2char(), hex2nchar(), holtonum(), INT64_2_ISZ, is_empty_typedef(), ISZ_T, kanji_len(), kanji_prefix(), local_sname(), STB::n_base, num, STB::quad0, result, SERROR, sptr, SPTR_NULL, FLG::standard, stb, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_ISINT, TY_ISSCALAR, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, uf, xdble(), xdfix(), xdfix64(), xdfloat(), xdflt64(), xdtoq(), xffloat(), xfix(), xfix64(), xflt64(), xftoq(), xqfix(), xqfix64(), xqfloat(), xqflt64(), xqtod(), xqtof(), and xsngl().
getrval()
int getrval (int ilmptr)
Dereference an ilm pointer to determine the rvalue i.e. its symbol pointer.
...
Definition at line 94 of file semutil0.cpp.
References getrval(), and ILMA.
Referenced by getrval(), and getstr().
hex2char()
static int hex2char (INT hexval[2]) static
Convert doubleword hex/octal value to a character.
Function return value is the symbol table entry of the character constant. The conversion is performed by copying an 8-bit value (2 hex digits) to a character position which is endian-dependent. The endian-dependency is handled as if the hex value is "equivalenced" with a character value of the same length. The length of the character constant returned is determined by the magnitude of the hex values (leading 0's are not converted). Note that this conversion returns the same character value in context of an assignment or data initialization. We may be incompatible with other implementations with respect to data initialization:
if the value is smaller than the char item being initialized, the conversion process results in appending blanks; other systems may pad with 'nulls'
if the value is larger, truncation of the least significant characters ("rightmost") occurs; other systems truncate the most significant characters ("leftmost").
hexval[0] is msw, hexval[1] is lsw.
Definition at line 252 of file semutil0.cpp.
References buf, FLG::endian, flg, getstring(), i, len, p, and val.
Referenced by cngcon().
hex2nchar()
static int hex2nchar (INT hexval[2]) static
Convert doubleword hex/octal value to an ncharacter.
Function return value is the symbol table entry of the character constant. The conversion is performed by copying an 8-bit value (2 hex digits) to a character position which is endian-dependent. The endian-dependency is handled as if the hex value is "equivalenced" with a ncharacter value of the same length. The length of the ncharacter constant returned is determined by the magnitude of the hex values (leading 0's are not converted). Note that this conversion returns the same ncharacter value in context of an assignment or data initialization. We may be incompatible with other implementations with respect to data initialization:
if the value is smaller than the nchar item being initialized, the conversion process results in appending blanks; other systems may pad with 'nulls'
if the value is larger, truncation of the least significant characters ("rightmost") occurs; other systems truncate the most significant characters ("leftmost").
hexval[0] is msw, hexval[1] is lsw.
Definition at line 319 of file semutil0.cpp.
References buf, FLG::endian, flg, getstring(), i, len, p, and val.
Referenced by cngcon().
holtonum()
static void holtonum (char * cp, INT num[4], int bc) static
Convert a hollerith constant to a numeric value. The destination can be any one of the 5 available sizes 1 byte, 2 bytes, 4 bytes, 8 bytes, or 16 bytes.
Parameters
cp is a character pointer to hollerith character string.
num is the result of conversion of hollerith to numeric.
bc is the byte count of destination area i.e. *1, *2, *4, *8 or *16
Definition at line 177 of file semutil0.cpp.
References buf, cp, FLG::endian, errwarn(), flg, i, num, and p.
Referenced by cngcon().
sem_eq_str()
bool sem_eq_str (int con, const char * pattern)
Return TRUE if fortran character constant is equal to pattern (pattern is always uppercase).
...
Returns
true if fortran character constant is equal to pattern (pattern is always uppercase)
Definition at line 1145 of file semutil0.cpp.
References len, STB::n_base, size_of(), and stb.
Referenced by _selected_char_kind(), and eval_selected_char_kind().
semant_init()
void semant_init (void)
Initialize semantic analyzer.
...
Definition at line 82 of file semutil0.cpp.
References ILMB::ilm_size, ilmb, and semant_reinit().
semant_reinit()
void semant_reinit (void)
Initialize semantic analyzer for new user subprogram unit.
...
Definition at line 39 of file semutil0.cpp.
References SEM::atemps, SEM::atomic, BOS_SIZE, SEM::close_pdo, FLG::code, SEM::ctemps, FLG::dclchk, SEM::dinit_data, SEM::dinit_error, SEM::eqvlist, EQVV_END, SEM::expect_do, SEM::flabels, flg, gbl, SEM::gdtype, SEM::ignore_stmt, ILMB::ilm_base, ILMB::ilm_size, ILMB::ilmavl, ilmb, SEM::in_stfunc, SEM::labels, llvm_ilms_rewrite_mode(), NEW, SEM::nml, SEM::none_implicit, NOSYM, FLG::object, SEM::p_adjarr, SEM::parallel, SEM::pgphase, SEM::psfunc, SEM::ptemps, SEM::savall, FLG::save, SEM::savloc, SEM::sc, SEM::scope, sem, FLG::smp, SEM::switch_avl, SEM::temps, SEM::temps_reset, SEM::vf_expr, void(), and SEM::wrilms.
Referenced by semant_init().