flang: sharedefs.h File Reference
shared/utils/sharedefs.h File Reference
Macros
#define STG_MEMBERS(dt)
#define STG_INIT NULL, 0, 0, 0, 0, 0, 0, 0, NULL, NULL
#define STG_DECLARE(name, dt)
#define STG_ALLOC(name, size) stg_alloc((STG *)&name.stg_base, sizeof(name.stg_base[0]), size, #name)
#define STG_CLEAR(name, r) stg_clear((STG *)&name.stg_base, r, 1)
#define STG_CLEAR_N(name, r, n) stg_clear((STG *)&name.stg_base, r, n)
#define STG_CLEAR_ALL(name) stg_clear_all((STG *)&name.stg_base);
#define STG_DELETE(name) stg_delete((STG *)&name.stg_base);
#define STG_NEXT(name) stg_next((STG *)&name.stg_base, 1)
#define STG_NEXT_SIZE(name, size) stg_next((STG *)&name.stg_base, size)
#define STG_NEED(name) stg_need((STG *)&name.stg_base)
#define STG_SET_FREELINK(name, dt, field) stg_set_freelink((STG *)&name.stg_base, offsetof(dt, field))
#define STG_NEXT_FREELIST(name) stg_next_freelist((STG *)&name.stg_base)
#define STG_ADD_FREELIST(name, index) stg_add_freelist((STG *)&name.stg_base, index)
#define STG_ALLOC_SIDECAR(basename, name)
#define STG_DELETE_SIDECAR(basename, name) stg_delete_sidecar((STG *)&basename.stg_base, (STG *)&name.stg_base);
#define STG_SETFLAG(name, flag) name.stg_flags |= (1 << (flag))
#define STG_CHECKFLAG(name, flag) (name.stg_flags & (1 << (flag)))
#define STG_FLAG_NOCLEAR 0
Functions
typedef STG_DECLARE (STG, void)
void stg_alloc (STG *stg, int dtsize, int size, char *name)
void stg_clear (STG *stg, int r, int n)
...
void stg_clear_all (STG *stg)
...
void stg_delete (STG *stg)
...
int stg_next (STG *stg, int n)
...
void stg_need (STG *stg)
...
void stg_set_freelink (STG *stg, int offset)
...
int stg_next_freelist (STG *stg)
...
void stg_add_freelist (STG *stg, int r)
...
void stg_alloc_sidecar (STG *basestg, STG *stg, int dtsize, char *name)
void stg_delete_sidecar (STG *basestg, STG *stg)
...
Macro Definition Documentation
STG_ADD_FREELIST
#define STG_ADD_FREELIST (name, index) stg_add_freelist((STG *)&name.stg_base, index)
Definition at line 111 of file shared/utils/sharedefs.h.
STG_ALLOC
#define STG_ALLOC (name, size) stg_alloc((STG *)&name.stg_base, sizeof(name.stg_base[0]), size, #name)
Definition at line 71 of file shared/utils/sharedefs.h.
STG_ALLOC_SIDECAR
#define STG_ALLOC_SIDECAR (basename, name)
Value:
  stg_alloc_sidecar((STG *)&basename.stg_base, (STG *)&name.stg_base, \
                    sizeof(name.stg_base[0]), #name)
Definition at line 116 of file shared/utils/sharedefs.h.
STG_CHECKFLAG
#define STG_CHECKFLAG (name, flag) (name.stg_flags & (1 << (flag)))
Definition at line 129 of file shared/utils/sharedefs.h.
STG_CLEAR
#define STG_CLEAR (name, r) stg_clear((STG *)&name.stg_base, r, 1)
Definition at line 76 of file shared/utils/sharedefs.h.
STG_CLEAR_ALL
#define STG_CLEAR_ALL (name) stg_clear_all((STG *)&name.stg_base);
Definition at line 83 of file shared/utils/sharedefs.h.
STG_CLEAR_N
#define STG_CLEAR_N (name, r, n) stg_clear((STG *)&name.stg_base, r, n)
Definition at line 79 of file shared/utils/sharedefs.h.
STG_DECLARE
#define STG_DECLARE (name, dt)
Value:
  struct {                    \
    STG_MEMBERS(dt);          \
  } name
Definition at line 58 of file shared/utils/sharedefs.h.
STG_DELETE
#define STG_DELETE (name) stg_delete((STG *)&name.stg_base);
Definition at line 87 of file shared/utils/sharedefs.h.
STG_DELETE_SIDECAR
#define STG_DELETE_SIDECAR (basename, name) stg_delete_sidecar((STG *)&basename.stg_base, (STG *)&name.stg_base);
Definition at line 122 of file shared/utils/sharedefs.h.
STG_FLAG_NOCLEAR
#define STG_FLAG_NOCLEAR 0
Definition at line 132 of file shared/utils/sharedefs.h.
STG_INIT
#define STG_INIT NULL, 0, 0, 0, 0, 0, 0, 0, NULL, NULL
Definition at line 55 of file shared/utils/sharedefs.h.
STG_MEMBERS
#define STG_MEMBERS (dt)
Value:
  dt *stg_base;                                                        \
  unsigned int stg_size, stg_avail, stg_free, stg_cleared, stg_dtsize, \
      stg_freelink_offset, stg_flags;                                  \
  char *stg_name;                                                      \
  void *stg_sidecar
Definition at line 47 of file shared/utils/sharedefs.h.
STG_NEED
#define STG_NEED (name) stg_need((STG *)&name.stg_base)
Definition at line 98 of file shared/utils/sharedefs.h.
STG_NEXT
#define STG_NEXT (name) stg_next((STG *)&name.stg_base, 1)
Definition at line 91 of file shared/utils/sharedefs.h.
STG_NEXT_FREELIST
#define STG_NEXT_FREELIST (name) stg_next_freelist((STG *)&name.stg_base)
Definition at line 107 of file shared/utils/sharedefs.h.
STG_NEXT_SIZE
#define STG_NEXT_SIZE (name, size) stg_next((STG *)&name.stg_base, size)
Definition at line 94 of file shared/utils/sharedefs.h.
STG_SET_FREELINK
#define STG_SET_FREELINK (name, dt, field) stg_set_freelink((STG *)&name.stg_base, offsetof(dt, field))
Definition at line 102 of file shared/utils/sharedefs.h.
STG_SETFLAG
#define STG_SETFLAG (name, flag) name.stg_flags |= (1 << (flag))
Definition at line 126 of file shared/utils/sharedefs.h.
Function Documentation
stg_add_freelist()
void stg_add_freelist (STG * stg, int r)
...
Definition at line 438 of file miscutil.c.
stg_alloc()
void stg_alloc (STG * stg, int dtsize, int size, char * name)
stg_alloc_sidecar()
void stg_alloc_sidecar (STG * basestg, STG * stg, int dtsize, char * name)
stg_clear()
void stg_clear (STG * stg, int r, int n)
...
Definition at line 179 of file miscutil.c.
Referenced by stg_add_freelist(), stg_clear_all(), stg_next(), and stg_next_freelist().
stg_clear_all()
void stg_clear_all (STG * stg)
...
Definition at line 189 of file miscutil.c.
STG_DECLARE()
typedef STG_DECLARE (STG , void)
stg_delete()
void stg_delete (STG * stg)
...
Definition at line 208 of file miscutil.c.
Referenced by stg_delete_sidecar().
stg_delete_sidecar()
void stg_delete_sidecar (STG * basestg, STG * stg)
...
Definition at line 307 of file miscutil.c.
stg_need()
void stg_need (STG * stg)
...
Definition at line 240 of file miscutil.c.
Referenced by stg_next().
stg_next()
int stg_next (STG * stg, int n)
...
Definition at line 337 of file miscutil.c.
Referenced by stg_next_freelist().
stg_next_freelist()
int stg_next_freelist (STG * stg)
...
Definition at line 395 of file miscutil.c.
stg_set_freelink()
void stg_set_freelink (STG * stg, int offset)
...
Definition at line 456 of file miscutil.c.