flang: sincosp.c File Reference
sincosp.c File Reference
#include "libm_amd.h"
#include "libm_util_amd.h"
#include "libm_inlines_amd.h"
Macros
#define USE_REMAINDER_PIBY2F_INLINE
#define USE_VALF_WITH_FLAGS
#define USE_NANF_WITH_FLAGS
#define USE_HANDLE_ERRORF
Functions
static double sinf_piby4 (double x)
static double cosf_piby4 (double x)
void FN_PROTOTYPE() mth_sincos (float x, float *s, float *c)
float FN_PROTOTYPE() mth_i_sin (float x)
float FN_PROTOTYPE() mth_i_cos (float x)
Macro Definition Documentation
USE_HANDLE_ERRORF
#define USE_HANDLE_ERRORF
Definition at line 49 of file sincosp.c.
USE_NANF_WITH_FLAGS
#define USE_NANF_WITH_FLAGS
Definition at line 48 of file sincosp.c.
USE_REMAINDER_PIBY2F_INLINE
#define USE_REMAINDER_PIBY2F_INLINE
Definition at line 46 of file sincosp.c.
USE_VALF_WITH_FLAGS
#define USE_VALF_WITH_FLAGS
Definition at line 47 of file sincosp.c.
Function Documentation
cosf_piby4()
static double cosf_piby4 (double x) inline static
Definition at line 79 of file sincosp.c.
References x, and x2.
Referenced by mth_i_cos(), mth_i_sin(), and mth_sincos().
mth_i_cos()
float FN_PROTOTYPE() mth_i_cos (float x)
Definition at line 379 of file sincosp.c.
References AMD_F_INEXACT, AMD_F_INVALID, cosf_piby4(), EXPBITS_DP64, EXPSHIFTBITS_DP64, GET_BITS_DP64, MANTBITS_DP64, r, sinf_piby4(), t, x, and xneg.
mth_i_sin()
float FN_PROTOTYPE() mth_i_sin (float x)
Definition at line 249 of file sincosp.c.
References AMD_F_INEXACT, AMD_F_INVALID, cosf_piby4(), EXPBITS_DP64, EXPSHIFTBITS_DP64, GET_BITS_DP64, MANTBITS_DP64, r, sinf_piby4(), t, x, and xneg.
mth_sincos()
void FN_PROTOTYPE() mth_sincos (float x, float * s, float * c)
Definition at line 97 of file sincosp.c.
References AMD_F_INEXACT, AMD_F_INVALID, cosf_piby4(), EXPBITS_DP64, EXPSHIFTBITS_DP64, GET_BITS_DP64, MANTBITS_DP64, r, s, sinf_piby4(), t, x, and xneg.
sinf_piby4()
static double sinf_piby4 (double x) inline static
Definition at line 58 of file sincosp.c.
References x, and x2.
Referenced by mth_i_cos(), mth_i_sin(), and mth_sincos().