flang: sincos.h File Reference
sincos.h File Reference
#include <stdint.h>
Macros
#define FMA __builtin_fma
#define _1_OVER_PI 3.1830988618379069e-01
#define PI_HI 3.1415926535897931e+00
#define PI_MI 1.2246467991473515e-16
#define PI_LO 1.6956855320737797e-31
#define THRESHOLD 2.1474836480000000e+09
#define A_D 2.7216757170572905e-15
#define B_D -7.6430432645975321e-13
#define C_D 1.6058941896620540e-10
#define D_D -2.5052106921502716e-08
#define E_D 2.7557319211743492e-06
#define F_D -1.9841269841213368e-04
#define G_D 8.3333333333332083e-03
#define H_D -1.6666666666666666e-01
Functions
static int64_t double_as_ll (double f)
static double ll_as_double (int64_t i)
static void reduction_slowpath (double const a, S(double *rs, uint64_t *hs) SINCOS_COMMA C(double *rc, uint64_t *hc))
Variables
static uint64_t i1opi_f []
Macro Definition Documentation
_1_OVER_PI
#define _1_OVER_PI 3.1830988618379069e-01
Definition at line 18 of file sincos.h.
A_D
#define A_D 2.7216757170572905e-15
Definition at line 25 of file sincos.h.
B_D
#define B_D -7.6430432645975321e-13
Definition at line 26 of file sincos.h.
C_D
#define C_D 1.6058941896620540e-10
Definition at line 27 of file sincos.h.
D_D
#define D_D -2.5052106921502716e-08
Definition at line 28 of file sincos.h.
E_D
#define E_D 2.7557319211743492e-06
Definition at line 29 of file sincos.h.
F_D
#define F_D -1.9841269841213368e-04
Definition at line 30 of file sincos.h.
FMA
#define FMA __builtin_fma
Definition at line 15 of file sincos.h.
G_D
#define G_D 8.3333333333332083e-03
Definition at line 31 of file sincos.h.
H_D
#define H_D -1.6666666666666666e-01
Definition at line 32 of file sincos.h.
PI_HI
#define PI_HI 3.1415926535897931e+00
Definition at line 19 of file sincos.h.
PI_LO
#define PI_LO 1.6956855320737797e-31
Definition at line 21 of file sincos.h.
PI_MI
#define PI_MI 1.2246467991473515e-16
Definition at line 20 of file sincos.h.
THRESHOLD
#define THRESHOLD 2.1474836480000000e+09
Definition at line 22 of file sincos.h.
Function Documentation
double_as_ll()
static int64_t double_as_ll (double f) static
Definition at line 59 of file sincos.h.
References f.
Referenced by reduction_slowpath().
ll_as_double()
static double ll_as_double (int64_t i) static
Definition at line 66 of file sincos.h.
References i.
Referenced by reduction_slowpath().
reduction_slowpath()
static void reduction_slowpath (double const a, S(double *rs, uint64_t *hs) SINCOS_COMMA C(double *rc, uint64_t *hc)) static
Definition at line 73 of file sincos.h.
References a, C, double_as_ll(), e, hc, i1opi_f, ia, idx, ll_as_double(), lz(), p, pc, q, rc, result, S(), and s.
Referenced by __attribute__(), and __reduction_slowpath().
Variable Documentation
i1opi_f
uint64_t i1opi_f[] static
Initial value:
= {
    0x35fdafd88fc6ae84ULL,
    0x9e839cfbc5294975ULL,
    0xba93dd63f5f2f8bdULL,
    0xa7a31fb34f2ff516ULL,
    0xb69b3f6793e584dbULL,
    0xf79788c5ad05368fULL,
    0x8ffc4bffef02cc07ULL,
    0x4e422fc5defc941dULL,
    0x9cc8eb1cc1a99cfaULL,
    0x74ce38135a2fbf20ULL,
    0x74411afa975da242ULL,
    0x7f0ef58e5894d39fULL,
    0x0324977504e8c90eULL,
    0xdb92371d2126e970ULL,
    0xff28b1d5ef5de2b0ULL,
    0x6db14acc9e21c820ULL,
    0xfe13abe8fa9a6ee0ULL,
    0x517cc1b727220a94ULL,
    0ULL,
}
Definition at line 35 of file sincos.h.
Referenced by reduction_slowpath().