flang: single1.h File Reference
single1.h File Reference
Functions
for (imask=0 ;imask< 2 ;imask++)
if (nfails !=0)
if (nfailsm !=0)
if ((nfails !=0)||(nfailsm !=0))
Variables
VRS_T rarg1 = vrs_set_arg(FMIN, FCONST1)
VRS_T rout = CONCAT7(__,FRP,PREC,_,FUNC,_,VLS)(rarg1)
int nfails = 0
int nfailsm = 0
char * fname = STRINGIFY(CONCAT7(__,FRP,PREC,_,FUNC,_,VLS))
VRS_T routm
int imask
int im
char * fnamem = STRINGIFY(CONCAT8(__,FRP,PREC,_,FUNC,_,VLS,m))
else
Function Documentation
for()
for ()
Definition at line 30 of file single1.h.
References build_masks(), checkfltol(), CONCAT8, FRP, FUNC, im, imask, m, nfailsm, PREC, rarg1, routm, and TOL.
if() [1/3]
if ((nfails !=0)||(nfailsm !=0))
Definition at line 54 of file single1.h.
if() [2/3]
if (nfails ! = 0)
Definition at line 40 of file single1.h.
References fname.
if() [3/3]
if (nfailsm ! = 0)
Definition at line 47 of file single1.h.
References fnamem.
Variable Documentation
else
else
Initial value:
{
      printf("%s Test Passed\n",fname)
Definition at line 42 of file single1.h.
fname
fname = STRINGIFY(CONCAT7(__,FRP,PREC,_,FUNC,_,VLS))
Definition at line 13 of file single1.h.
Referenced by _doincl(), _nextline(), _simple_replacements(), accpp(), ad1mathfunc_cmplx(), ad2mathfunc_cmplx(), add_headerfile(), addarth(), doline(), ENT3F(), gen_call_llvm_fm_intrinsic(), gen_call_llvm_intrinsic(), gen_call_llvm_intrinsic_impl(), gen_call_llvm_non_fm_math_intrinsic(), gen_call_pgocl_intrinsic(), gen_call_to_builtin(), gen_sincos(), getccsym_copy(), if(), import_module_print(), insert_llvm_prefetch(), makeCall(), ptok(), and subst().
fnamem
fnamem = STRINGIFY(CONCAT8(__,FRP,PREC,_,FUNC,_,VLS,m))
Definition at line 18 of file single1.h.
Referenced by if().
im
int im
Definition at line 17 of file single1.h.
Referenced by __rvs_log_fma3(), __rvs_log_fma3_256(), casttyp(), dump_one_scope(), and for().
imask
int imask
Definition at line 17 of file single1.h.
Referenced by for().
nfails
nfails = 0
Definition at line 11 of file single1.h.
nfailsm
int nfailsm = 0
Definition at line 12 of file single1.h.
Referenced by for().
rarg1
rarg1 = vrs_set_arg(FMIN, FCONST1)
Definition at line 9 of file single1.h.
Referenced by for().
rout
rout = CONCAT7(__,FRP,PREC,_,FUNC,_,VLS)(rarg1)
Definition at line 10 of file single1.h.
routm
VRS_T routm
Definition at line 16 of file single1.h.
Referenced by for().