flang: sleef_common.h File Reference
sleef_common.h File Reference
Macros
#define CONFIG 1
#define vF2I vreinterpret_vi2_vf
#define vI2F vreinterpret_vf_vi2
#define vD2I vreinterpret_vi2_vd
#define vD2L vD2I
#define vL2D vreinterpret_vd_vi2
#define vD2F(x) vI2F(vD2I(x))
#define vSETi vcast_vi2_i
#define vSETf vcast_vf_f
#define vSETd vcast_vd_d
#define vSETLLi(x, y) vD2I(vSETd(L2D(II2L(x, y))))
#define vSETll(x) vD2L(vSETd(L2D(x)))
#define vSETLLL(x, y) vD2L(vset_vd_d_d(L2D(x), L2D(y)))
Functions
static void INLINE vfast2sum (vfloat x, vfloat y, vfloat *rhi, vfloat *rlo)
static void INLINE vfast2mul (vfloat x, vfloat y, vfloat *r1, vfloat *r2)
static void INLINE vfast2sum_dp (vdouble x, vdouble y, vdouble *rhi, vdouble *rlo)
static void INLINE vfast2mul_dp (vdouble x, vdouble y, vdouble *r1, vdouble *r2)
Macro Definition Documentation
CONFIG
#define CONFIG 1
Definition at line 13 of file sleef_common.h.
vD2F
#define vD2F (x) vI2F(vD2I(x))
Definition at line 33 of file sleef_common.h.
vD2I
#define vD2I vreinterpret_vi2_vd
Definition at line 30 of file sleef_common.h.
vD2L
#define vD2L vD2I
Definition at line 31 of file sleef_common.h.
vF2I
#define vF2I vreinterpret_vi2_vf
Definition at line 28 of file sleef_common.h.
vI2F
#define vI2F vreinterpret_vf_vi2
Definition at line 29 of file sleef_common.h.
vL2D
#define vL2D vreinterpret_vd_vi2
Definition at line 32 of file sleef_common.h.
vSETd
#define vSETd vcast_vd_d
Definition at line 36 of file sleef_common.h.
vSETf
#define vSETf vcast_vf_f
Definition at line 35 of file sleef_common.h.
vSETi
#define vSETi vcast_vi2_i
Definition at line 34 of file sleef_common.h.
vSETll
#define vSETll (x) vD2L(vSETd(L2D(x)))
Definition at line 38 of file sleef_common.h.
vSETLLi
#define vSETLLi (x, y) vD2I(vSETd(L2D(II2L(x, y))))
Definition at line 37 of file sleef_common.h.
vSETLLL
#define vSETLLL (x, y) vD2L(vset_vd_d_d(L2D(x), L2D(y)))
Definition at line 39 of file sleef_common.h.
Function Documentation
vfast2mul()
static void INLINE vfast2mul (vfloat x, vfloat y, vfloat * r1, vfloat * r2) static
Definition at line 54 of file sleef_common.h.
References vfmapn_vf_vf_vf_vf(), vmul_vf_vf_vf(), x, and y.
Referenced by __vcis_kernel().
vfast2mul_dp()
static void INLINE vfast2mul_dp (vdouble x, vdouble y, vdouble * r1, vdouble * r2) static
Definition at line 75 of file sleef_common.h.
References vfmapn_vd_vd_vd_vd(), vmul_vd_vd_vd(), x, and y.
Referenced by __vcis_d_kernel().
vfast2sum()
static void INLINE vfast2sum (vfloat x, vfloat y, vfloat * rhi, vfloat * rlo) static
Definition at line 42 of file sleef_common.h.
References hi, lo, tmp, vadd_vf_vf_vf(), vsub_vf_vf_vf(), x, and y.
Referenced by __vcis_kernel().
vfast2sum_dp()
static void INLINE vfast2sum_dp (vdouble x, vdouble y, vdouble * rhi, vdouble * rlo) static
Definition at line 63 of file sleef_common.h.
References hi, lo, tmp, vadd_vd_vd_vd(), vsub_vd_vd_vd(), x, and y.
Referenced by __vcis_d_kernel().