flang: spread.c File Reference
spread.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
Functions
void ENTFTN (SPREAD, spread)
void ENTFTN (SPREADSA, spreadsa)
void ENTFTN (SPREADS, spreads)
void ENTFTN (SPREADCA, spreadca)
void ENTFTN (SPREADC, spreadc)
void ENTFTN (SPREADCSA, spreadcsa)
void ENTFTN (SPREADCS, spreadcs)
void ENTFTN (SPREAD_DESCRIPTOR, spread_descriptor)
Function Documentation
ENTFTN() [1/8]
void ENTFTN (SPREAD , spread)
Definition at line 16 of file spread.c.
References __DIST_INIT_SECTION, __fort_copy(), __fort_doit(), __fort_fetch_int(), __fort_finish_section(), __fort_frechn(), __fort_set_section(), __fort_set_single(), __SCALAR, c, DECL_DIM_PTRS, DECL_HDR_VARS, dim, DIST_CACHED_P, DIST_DIM_OLB_G, DIST_DIM_OLB_P, DIST_DIM_OUB_G, DIST_DIM_OUB_P, DIST_PBASE_G, DIST_PBASE_P, DIST_REPLICATED_G, DIST_REPLICATED_P, DIST_SCOFF_G, DIST_SCOFF_P, DPTR_UBOUND_G, F90_DPTR_LBOUND_G, F90_FLAGS_G, F90_FLAGS_P, F90_LBASE_G, F90_LBASE_P, F90_LEN_G, F90_RANK_G, flags, i, I8, k, lbase, MAXDIMS, NULL, rank, rb, sb, SET_DIM_PTRS, and td.
Referenced by ENTFTN().
ENTFTN() [2/8]
void ENTFTN (SPREAD_DESCRIPTOR , spread_descriptor)
Definition at line 209 of file spread.c.
References __DESC, __DIST_INIT_DESCRIPTOR, __DIST_SET_ALLOCATION, __fort_abort(), __fort_finish_descriptor(), __fort_set_alignment(), __fort_set_single(), __SINGLE, DECL_DIM_PTRS, DECL_HDR_PTRS, dim, DIST_ALIGN_TARGET_G, DIST_DIM_GEN_BLOCK_G, DIST_DPTR_TAXIS_G, DIST_DPTR_TOFFSET_G, DIST_DPTR_TSTRIDE_G, DIST_INFO_G, DIST_SINGLE_G, extent(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_FLAGS_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, I8, m, offset, SET_DIM_PTRS, and td.
ENTFTN() [3/8]
void ENTFTN (SPREADC , spreadc)
Definition at line 147 of file spread.c.
References __CLEN_T, CADR, CLEN, ENTFTN(), rb, and sb.
ENTFTN() [4/8]
void ENTFTN (SPREADCA , spreadca)
Definition at line 132 of file spread.c.
References CADR, ENTFTN(), rb, and sb.
ENTFTN() [5/8]
void ENTFTN (SPREADCS , spreadcs)
Definition at line 184 of file spread.c.
References __CLEN_T, CADR, CLEN, ENTFTN(), rb, and sb.
ENTFTN() [6/8]
void ENTFTN (SPREADCSA , spreadcsa)
Definition at line 164 of file spread.c.
References __CLEN_T, CADR, CLEN, ENTFTN(), rb, sb, and size.
ENTFTN() [7/8]
void ENTFTN (SPREADS , spreads)
Definition at line 117 of file spread.c.
References __CLEN_T, ENTFTN(), rb, and sb.
ENTFTN() [8/8]
void ENTFTN (SPREADSA , spreadsa)
Definition at line 91 of file spread.c.
References __CLEN_T, __fort_bcopy(), __fort_fetch_int(), I8, rb, sb, and size.