flang: ssacos.cpp File Reference
ssacos.cpp File Reference
#include <immintrin.h>
#include <math.h>
#include "acos_defs.h"
Functions
float __fss_acos_fma3 (float)
static int __float_as_int (float const a)
static float __int_as_float (int const a)
Function Documentation
__float_as_int()
static int __float_as_int (float const a) static
Definition at line 22 of file ssacos.cpp.
References a.
Referenced by __fss_acos_fma3().
__fss_acos_fma3()
float __fss_acos_fma3 (float a)
Definition at line 30 of file ssacos.cpp.
References __float_as_int(), __int_as_float(), _c, a, A0_F, A1_F, ABS_MASK_I, B0_F, B1_F, C, C0_F, C1_F, D0_F, D1_F, E, E0_F, E1_F, F0_F, F1_F, p, PI, PI_F, res, SGN_MASK_I, sign, sqrtf(), THRESHOLD_F, x, and ZERO.
__int_as_float()
static float __int_as_float (int const a) static
Definition at line 26 of file ssacos.cpp.
References a.
Referenced by __fss_acos_fma3().