flang: ssexp.cpp File Reference
ssexp.cpp File Reference
#include <math.h>
#include <stdint.h>
#include "exp_defs.h"
Macros
#define FMAF __builtin_fmaf
Functions
float __fss_exp_fma3 (float)
float itf (int a)
int fti (float a)
Macro Definition Documentation
FMAF
#define FMAF __builtin_fmaf
Definition at line 12 of file ssexp.cpp.
Function Documentation
__fss_exp_fma3()
float __fss_exp_fma3 (float a)
Definition at line 26 of file ssexp.cpp.
References a, DNRM_SHFT, DNRM_THR, exp, EXP_C0, EXP_C1, EXP_C2, EXP_C3, EXP_C4, EXP_C5, EXP_C6, EXP_C7, EXP_DN, EXP_HI, EXP_LO, FLT2INT_CVT, FMAF, fti(), INF, itf(), L2E, LN2_0, LN2_1, res, t, and z.
fti()
int fti (float a) inline
Definition at line 21 of file ssexp.cpp.
References a.
Referenced by __fss_exp_fma3().
itf()
float itf (int a) inline
Definition at line 16 of file ssexp.cpp.
References a.
Referenced by __fss_exp_fma3().