flang: sspow.cpp File Reference
sspow.cpp File Reference
#include <immintrin.h>
#include "pow_defs.h"
Functions
float __fss_pow_fma3 (float const, float const)
float __attribute__ ((noinline)) __pgm_pow_scalar_dp_special_cases(__m128 res_exp
if (a_is_neg_flag &&(!b_is_integer_flag))
if (a_is_any_zero_flag &&b_is_lt_zero_flag)
return _mm_cvtss_f32 (res_exp)
Variables
float float const a_scalar
float float const float const b_scalar
const __m128 b = _mm_set1_ps(b_scalar)
__m128i abs_mask = _mm_set1_epi32(D_ABS_MASK)
__m128i pos_inf = _mm_set1_epi32(D_POS_INF)
__m128i sign_mask = _mm_set1_epi32(D_SIGN_MASK)
__m128i neg_inf = _mm_set1_epi32(D_NEG_INF)
__m128i nan = _mm_set1_epi32(D_NAN)
__m128i neg_nan = _mm_set1_epi32(D_NEG_NAN)
__m128 MINUS_ONE_F_VEC = _mm_set1_ps(D_MINUS_ONE_F)
__m128 MINUS_ZERO_F_VEC = _mm_set1_ps(D_MINUS_ZERO_F)
__m128 const ONE_F_VEC = _mm_set1_ps(D_ONE_F)
__m128 const ZERO_F_VEC = _mm_setzero_ps()
__m128i b_is_nan = (__m128i)_mm_cmp_ps(b, b, _CMP_NEQ_UQ)
__m128i a_is_nan = (__m128i)_mm_cmp_ps(a,a, _CMP_NEQ_UQ)
__m128i a_is_neg = (__m128i)_mm_cmp_ps(a, ZERO_F_VEC, _CMP_LT_OS)
int a_is_neg_flag = _mm_movemask_epi8((__m128i)a_is_neg)
__m128i b_is_integer = (__m128i)_mm_cmp_ps(b, _mm_floor_ps(b), _CMP_EQ_OQ)
int b_is_integer_flag = _mm_movemask_epi8((__m128i)b_is_integer)
__m128i b_is_odd_integer
__m128i b_is_even_integer
__m128i b_is_lt_zero = (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_LT_OS)
int b_is_lt_zero_flag = _mm_movemask_epi8((__m128i)b_is_lt_zero)
__m128i b_is_gt_zero = (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_GT_OS)
__m128i b_is_odd_integer_lt_zero
__m128i b_is_odd_integer_gt_zero
__m128i change_sign_mask = _mm_and_si128(a_is_neg, b_is_odd_integer)
__m128 changed_sign = _mm_xor_ps(res_exp, (__m128)sign_mask)
res_exp = _mm_or_ps(_mm_and_ps((__m128)change_sign_mask, (__m128)changed_sign), _mm_andnot_ps((__m128)change_sign_mask, res_exp))
__m128i return_neg_nan_mask = _mm_andnot_si128(b_is_integer, a_is_neg)
__m128i return_nan_mask = _mm_or_si128(b_is_nan, a_is_nan)
__m128 b_as_nan
__m128 a_as_nan
__m128 nan_to_return = _mm_and_ps((__m128)b_is_nan, b_as_nan)
__m128i b_is_neg_inf = _mm_cmpeq_epi32((__m128i)b, neg_inf)
__m128i b_is_pos_inf = _mm_cmpeq_epi32((__m128i)b, pos_inf)
__m128i b_is_any_inf = _mm_or_si128(b_is_pos_inf, b_is_neg_inf)
__m128i a_is_neg_inf = _mm_cmpeq_epi32((__m128i)a, neg_inf)
__m128i a_is_pos_inf = _mm_cmpeq_epi32((__m128i)a, pos_inf)
__m128i a_is_any_inf = _mm_or_si128(a_is_pos_inf, a_is_neg_inf)
__m128i a_is_pos_zero = _mm_cmpeq_epi32((__m128i)a, (__m128i)ZERO_F_VEC)
__m128i a_is_neg_zero = _mm_cmpeq_epi32((__m128i)a, (__m128i)MINUS_ZERO_F_VEC)
__m128i a_is_any_zero = _mm_or_si128(a_is_pos_zero, a_is_neg_zero)
int a_is_any_zero_flag = _mm_movemask_epi8((__m128i)a_is_any_zero)
__m128i abs_a = _mm_and_si128((__m128i)a, abs_mask)
__m128 abs_a_lt_one = _mm_cmp_ps((__m128)abs_a, ONE_F_VEC, _CMP_LT_OS)
__m128 abs_a_gt_one = _mm_cmp_ps((__m128)abs_a, ONE_F_VEC, _CMP_GT_OS)
__m128i a_is_one_mask = _mm_cmpeq_epi32((__m128i)a, (__m128i)ONE_F_VEC)
__m128i a_is_minus_one_mask = _mm_cmpeq_epi32((__m128i)a, (__m128i)MINUS_ONE_F_VEC)
__m128i return_1_mask = _mm_or_si128(a_is_one_mask, (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_EQ_OQ))
__m128i return_minus_1_mask = _mm_and_si128(a_is_minus_one_mask, b_is_odd_integer)
__m128i return_neg_zero_mask
__m128i return_pos_zero_mask = _mm_and_si128((__m128i)abs_a_gt_one, b_is_neg_inf)
__m128i return_neg_inf_mask = _mm_and_si128(a_is_neg_inf, _mm_and_si128(b_is_odd_integer, b_is_gt_zero))
__m128i return_pos_inf_mask = _mm_and_si128((__m128i)abs_a_lt_one, b_is_neg_inf)
Function Documentation
__attribute__()
float __attribute__ ((noinline))
References a, and a_scalar.
__fss_pow_fma3()
float __fss_pow_fma3 (float const a_scalar, float const b_scalar)
Definition at line 180 of file sspow.cpp.
References _mm_cvtss_f32(), a, a_scalar, ALL_ONES_EXPONENT, b, b_scalar, D_ALL_ONES_EXPONENT, D_BIT_MASK2, D_EXP_OFFSET, D_OFFSET, D_ONE_F, D_SIGN_MASK2, D_TWO_TO_24_F, D_U24, DBL2INT_CVT, detect_inf_nan, e, EXP_C0, EXP_C1, EXP_C2, EXP_C3, EXP_C4, EXP_C5, EXP_C6, EXP_HI, EXP_LO, LOG_C0, LOG_C1, LOG_C10, LOG_C2, LOG_C3, LOG_C4, LOG_C5, LOG_C6, LOG_C7, LOG_C8, LOG_C9, m, m2, m4, offset, ONE_F_VEC, res, res_exp, t, and ZERO_F_VEC.
_mm_cvtss_f32()
return _mm_cvtss_f32 (res_exp)
Referenced by __attribute__(), __fss_atan_fma3(), __fss_pow_fma3(), __ldexpf_scalar_kernel(), and my_fmaf().
if() [1/2]
if (a_is_any_zero_flag && b_is_lt_zero_flag)
Definition at line 172 of file sspow.cpp.
References ONE_F_VEC, and ZERO_F_VEC.
if() [2/2]
if (a_is_neg_flag && !b_is_integer_flag)
Definition at line 168 of file sspow.cpp.
References a.
Variable Documentation
a_as_nan
__m128 a_as_nan
Initial value:
= _mm_or_ps(_mm_and_ps(
                                                     (__m128)a_is_nan, _mm_or_ps(a, (__m128)_mm_set1_epi32(0x00400000))),
                                                     _mm_andnot_ps((__m128)a_is_nan, res_exp))
Definition at line 79 of file sspow.cpp.
a_is_any_inf
__m128i a_is_any_inf = _mm_or_si128(a_is_pos_inf, a_is_neg_inf)
Definition at line 96 of file sspow.cpp.
a_is_any_zero
__m128i a_is_any_zero = _mm_or_si128(a_is_pos_zero, a_is_neg_zero)
Definition at line 100 of file sspow.cpp.
a_is_any_zero_flag
int a_is_any_zero_flag = _mm_movemask_epi8((__m128i)a_is_any_zero)
Definition at line 101 of file sspow.cpp.
a_is_minus_one_mask
__m128i a_is_minus_one_mask = _mm_cmpeq_epi32((__m128i)a, (__m128i)MINUS_ONE_F_VEC)
Definition at line 108 of file sspow.cpp.
a_is_nan
__m128i a_is_nan = (__m128i)_mm_cmp_ps(a,a, _CMP_NEQ_UQ)
Definition at line 38 of file sspow.cpp.
a_is_neg
__m128i a_is_neg = (__m128i)_mm_cmp_ps(a, ZERO_F_VEC, _CMP_LT_OS)
Definition at line 39 of file sspow.cpp.
a_is_neg_flag
int a_is_neg_flag = _mm_movemask_epi8((__m128i)a_is_neg)
Definition at line 40 of file sspow.cpp.
a_is_neg_inf
__m128i a_is_neg_inf = _mm_cmpeq_epi32((__m128i)a, neg_inf)
Definition at line 94 of file sspow.cpp.
a_is_neg_zero
__m128i a_is_neg_zero = _mm_cmpeq_epi32((__m128i)a, (__m128i)MINUS_ZERO_F_VEC)
Definition at line 99 of file sspow.cpp.
a_is_one_mask
__m128i a_is_one_mask = _mm_cmpeq_epi32((__m128i)a, (__m128i)ONE_F_VEC)
Definition at line 107 of file sspow.cpp.
a_is_pos_inf
__m128i a_is_pos_inf = _mm_cmpeq_epi32((__m128i)a, pos_inf)
Definition at line 95 of file sspow.cpp.
a_is_pos_zero
__m128i a_is_pos_zero = _mm_cmpeq_epi32((__m128i)a, (__m128i)ZERO_F_VEC)
Definition at line 98 of file sspow.cpp.
a_scalar
float float const a_scalar
Definition at line 21 of file sspow.cpp.
Referenced by __attribute__(), and __fss_pow_fma3().
abs_a
__m128i abs_a = _mm_and_si128((__m128i)a, abs_mask)
Definition at line 103 of file sspow.cpp.
abs_a_gt_one
__m128 abs_a_gt_one = _mm_cmp_ps((__m128)abs_a, ONE_F_VEC, _CMP_GT_OS)
Definition at line 105 of file sspow.cpp.
abs_a_lt_one
__m128 abs_a_lt_one = _mm_cmp_ps((__m128)abs_a, ONE_F_VEC, _CMP_LT_OS)
Definition at line 104 of file sspow.cpp.
abs_mask
__m128i abs_mask = _mm_set1_epi32(D_ABS_MASK)
Definition at line 25 of file sspow.cpp.
Referenced by __attribute__().
b
const __m128 b = _mm_set1_ps(b_scalar)
Definition at line 24 of file sspow.cpp.
Referenced by __fss_pow_fma3().
b_as_nan
__m128 b_as_nan
Initial value:
= _mm_or_ps(_mm_and_ps(
                                                     (__m128)b_is_nan, _mm_or_ps(b, (__m128)_mm_set1_epi32(0x00400000))),
                                                     _mm_andnot_ps((__m128)b_is_nan, res_exp))
Definition at line 75 of file sspow.cpp.
b_is_any_inf
__m128i b_is_any_inf = _mm_or_si128(b_is_pos_inf, b_is_neg_inf)
Definition at line 92 of file sspow.cpp.
b_is_even_integer
__m128i b_is_even_integer
Initial value:
= _mm_and_si128(b_is_integer,
                                                  _mm_cmpeq_epi32(
                                                                     _mm_and_si128(_mm_cvtps_epi32(b), _mm_set1_epi32(0x1)),
                                                                     _mm_set1_epi32(0x0)))
Definition at line 50 of file sspow.cpp.
b_is_gt_zero
__m128i b_is_gt_zero = (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_GT_OS)
Definition at line 58 of file sspow.cpp.
b_is_integer
__m128i b_is_integer = (__m128i)_mm_cmp_ps(b, _mm_floor_ps(b), _CMP_EQ_OQ)
Definition at line 42 of file sspow.cpp.
b_is_integer_flag
int b_is_integer_flag = _mm_movemask_epi8((__m128i)b_is_integer)
Definition at line 43 of file sspow.cpp.
b_is_lt_zero
__m128i b_is_lt_zero = (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_LT_OS)
Definition at line 55 of file sspow.cpp.
b_is_lt_zero_flag
int b_is_lt_zero_flag = _mm_movemask_epi8((__m128i)b_is_lt_zero)
Definition at line 56 of file sspow.cpp.
b_is_nan
__m128i b_is_nan = (__m128i)_mm_cmp_ps(b, b, _CMP_NEQ_UQ)
Definition at line 37 of file sspow.cpp.
b_is_neg_inf
__m128i b_is_neg_inf = _mm_cmpeq_epi32((__m128i)b, neg_inf)
Definition at line 90 of file sspow.cpp.
b_is_odd_integer
__m128i b_is_odd_integer
Initial value:
= _mm_and_si128(b_is_integer,
                                                  _mm_cmpeq_epi32(
                                                                     _mm_and_si128(_mm_cvtps_epi32(b), _mm_set1_epi32(0x1)),
                                                                     _mm_set1_epi32(0x1)))
Definition at line 45 of file sspow.cpp.
b_is_odd_integer_gt_zero
__m128i b_is_odd_integer_gt_zero
Initial value:
= _mm_and_si128(b_is_integer,
                                                           (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_GT_OS))
Definition at line 63 of file sspow.cpp.
b_is_odd_integer_lt_zero
__m128i b_is_odd_integer_lt_zero
Initial value:
= _mm_and_si128(b_is_integer,
                                                           (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_LT_OS))
Definition at line 60 of file sspow.cpp.
b_is_pos_inf
__m128i b_is_pos_inf = _mm_cmpeq_epi32((__m128i)b, pos_inf)
Definition at line 91 of file sspow.cpp.
b_scalar
float float const float const b_scalar
Initial value:
{
   __m128 a = _mm_set1_ps(a_scalar)
Definition at line 21 of file sspow.cpp.
Referenced by __fss_pow_fma3().
change_sign_mask
__m128i change_sign_mask = _mm_and_si128(a_is_neg, b_is_odd_integer)
Definition at line 66 of file sspow.cpp.
changed_sign
__m128 changed_sign = _mm_xor_ps(res_exp, (__m128)sign_mask)
Definition at line 67 of file sspow.cpp.
MINUS_ONE_F_VEC
__m128 MINUS_ONE_F_VEC = _mm_set1_ps(D_MINUS_ONE_F)
Definition at line 31 of file sspow.cpp.
MINUS_ZERO_F_VEC
__m128 MINUS_ZERO_F_VEC = _mm_set1_ps(D_MINUS_ZERO_F)
Definition at line 32 of file sspow.cpp.
nan
__m128i nan = _mm_set1_epi32(D_NAN)
Definition at line 29 of file sspow.cpp.
Referenced by enan().
nan_to_return
nan_to_return = _mm_and_ps((__m128)b_is_nan, b_as_nan)
Definition at line 83 of file sspow.cpp.
neg_inf
__m128i neg_inf = _mm_set1_epi32(D_NEG_INF)
Definition at line 28 of file sspow.cpp.
neg_nan
__m128i neg_nan = _mm_set1_epi32(D_NEG_NAN)
Definition at line 30 of file sspow.cpp.
ONE_F_VEC
__m128 const ONE_F_VEC = _mm_set1_ps(D_ONE_F)
Definition at line 33 of file sspow.cpp.
Referenced by __fss_pow_fma3(), and if().
pos_inf
__m128i pos_inf = _mm_set1_epi32(D_POS_INF)
Definition at line 26 of file sspow.cpp.
res_exp
return res_exp = _mm_or_ps(_mm_and_ps((__m128)change_sign_mask, (__m128)changed_sign), _mm_andnot_ps((__m128)change_sign_mask, res_exp))
Definition at line 68 of file sspow.cpp.
Referenced by __fss_pow_fma3().
return_1_mask
return_1_mask = _mm_or_si128(a_is_one_mask, (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_EQ_OQ))
Definition at line 110 of file sspow.cpp.
return_minus_1_mask
__m128i return_minus_1_mask = _mm_and_si128(a_is_minus_one_mask, b_is_odd_integer)
Definition at line 118 of file sspow.cpp.
return_nan_mask
__m128i return_nan_mask = _mm_or_si128(b_is_nan, a_is_nan)
Definition at line 73 of file sspow.cpp.
return_neg_inf_mask
return_neg_inf_mask = _mm_and_si128(a_is_neg_inf, _mm_and_si128(b_is_odd_integer, b_is_gt_zero))
Definition at line 141 of file sspow.cpp.
return_neg_nan_mask
__m128i return_neg_nan_mask = _mm_andnot_si128(b_is_integer, a_is_neg)
Definition at line 70 of file sspow.cpp.
return_neg_zero_mask
return_neg_zero_mask
Initial value:
= _mm_and_si128(a_is_neg_inf,
                                                      b_is_odd_integer_lt_zero)
Definition at line 123 of file sspow.cpp.
return_pos_inf_mask
return_pos_inf_mask = _mm_and_si128((__m128i)abs_a_lt_one, b_is_neg_inf)
Definition at line 147 of file sspow.cpp.
return_pos_zero_mask
return_pos_zero_mask = _mm_and_si128((__m128i)abs_a_gt_one, b_is_neg_inf)
Definition at line 131 of file sspow.cpp.
sign_mask
__m128i sign_mask = _mm_set1_epi32(D_SIGN_MASK)
Definition at line 27 of file sspow.cpp.
ZERO_F_VEC
__m128 const ZERO_F_VEC = _mm_setzero_ps()
Definition at line 34 of file sspow.cpp.
Referenced by __fss_pow_fma3(), and if().