flang: stat.c File Reference
stat.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "timeBlk.h"
#include <string.h>
#include <memory.h>
Functions
void __fort_gettb (struct tb *)
void ENTFTN (TIMES, times)
int __fort_stat_init (void)
Begin stats.
static const char * scale_bytes (double d, double *ds)
static const char * scale_kbytes (double d, double *ds)
static void cpu (struct tb *tbp)
static void mem (struct tb *tbp)
static void msg (struct tb *tbp)
void __fort_stat_term (void)
Print stats (called by all cpus)
void __fort_stat_recv (int cpu, long len)
void __fort_stat_recv_done (int cpu)
Update done receive message stats.
void __fort_stat_send (int cpu, long len)
Update start send message stats.
void __fort_stat_send_done (int cpu)
Update done send message stats.
void __fort_stat_copy (long len)
Update start bcopy message stats.
void __fort_stat_copy_done (void)
Update done bcopy message stats.
void __fort_stat_arecv (int cpu, long len, int reqn)
Update start asynch receive message stats.
void __fort_stat_arecv_done (int cpu)
void __fort_stat_asend (int cpu, long len, int reqn)
void __fort_stat_asend_done (int cpu)
void __fort_stat_await (int reqn)
void __fort_stat_await_done (int reqn)
void ENTFTN (MSGSTATS, msgstats)
void __fort_stat_function_entry (int line, int lines, int cline, char *func, char *file, int funcl, int filel)
Function entry
void __fort_stat_line_entry (int line)
Line entry
void __fort_stat_function_exit (void)
Function exit
Variables
static struct tb tb0
static struct tb tb1
Function Documentation
__fort_gettb()
void __fort_gettb (struct tb * t)
Definition at line 48 of file stat_linux.c.
References __fort_sbrk(), GET_DIST_HEAPZ, nodename(), sbrk(), t, timezone, and ieee::v.
Referenced by __fort_stat_init(), __fort_stat_term(), and ENTFTN().
__fort_stat_arecv()
void __fort_stat_arecv (int cpu, long len, int reqn)
Update start asynch receive message stats.
Definition at line 393 of file stat.c.
References tb::byter, tb::datar, len, and tb1.
Referenced by __fort_entry_arecv().
__fort_stat_arecv_done()
void __fort_stat_arecv_done (int cpu)
Definition at line 402 of file stat.c.
Referenced by __fort_entry_arecv_done().
__fort_stat_asend()
void __fort_stat_asend (int cpu, long len, int reqn)
Definition at line 409 of file stat.c.
References tb::bytes, tb::datas, len, and tb1.
Referenced by __fort_entry_asend().
__fort_stat_asend_done()
void __fort_stat_asend_done (int cpu)
Definition at line 418 of file stat.c.
Referenced by __fort_entry_asend_done().
__fort_stat_await()
void __fort_stat_await (int reqn)
Definition at line 425 of file stat.c.
Referenced by __fort_entry_await().
__fort_stat_await_done()
void __fort_stat_await_done (int reqn)
Definition at line 432 of file stat.c.
Referenced by __fort_entry_await_done().
__fort_stat_copy()
void __fort_stat_copy (long len)
Update start bcopy message stats.
Parameters
len total length in bytes
Definition at line 379 of file stat.c.
References tb::bytec, tb::datac, len, and tb1.
Referenced by __fort_entry_copy().
__fort_stat_copy_done()
void __fort_stat_copy_done (void)
Update done bcopy message stats.
Definition at line 387 of file stat.c.
Referenced by __fort_entry_copy_done().
__fort_stat_function_entry()
void __fort_stat_function_entry (int line, int lines, int cline, char * func, char * file, int funcl, int filel)
Function entry
Definition at line 449 of file stat.c.
Referenced by ENTFTN().
__fort_stat_function_exit()
void __fort_stat_function_exit (void)
Function exit
Definition at line 464 of file stat.c.
Referenced by ENTFTN().
__fort_stat_init()
int __fort_stat_init (void)
Begin stats.
Definition at line 54 of file stat.c.
References __fort_gettb(), and tb0.
Referenced by __fort_entry_init().
__fort_stat_line_entry()
void __fort_stat_line_entry (int line)
Line entry
Definition at line 457 of file stat.c.
Referenced by ENTFTN().
__fort_stat_recv()
void __fort_stat_recv (int cpu, long len)
Definition at line 342 of file stat.c.
References tb::byter, tb::datar, len, and tb1.
Referenced by __fort_entry_recv().
__fort_stat_recv_done()
void __fort_stat_recv_done (int cpu)
Update done receive message stats.
Definition at line 352 of file stat.c.
Referenced by __fort_entry_recv_done().
__fort_stat_send()
void __fort_stat_send (int cpu, long len)
Update start send message stats.
Parameters
cpu receiving cpu
len total length in bytes
Definition at line 361 of file stat.c.
References tb::bytes, tb::datas, len, and tb1.
Referenced by __fort_entry_send().
__fort_stat_send_done()
void __fort_stat_send_done (int cpu)
Update done send message stats.
Parameters
cpu - receiving cpu
Definition at line 371 of file stat.c.
Referenced by __fort_entry_send_done().
__fort_stat_term()
void __fort_stat_term (void)
Print stats (called by all cpus)
Definition at line 295 of file stat.c.
References __fort_gettb(), __fort_gfree(), __fort_gmalloc(), __fort_is_ioproc(), __fort_rrecv(), __fort_rsend(), __UCHAR, cpu(), GET_DIST_IOPROC, GET_DIST_QUIET, GET_DIST_TCPUS, tb::gsbrk, i, mem(), msg(), Q_CPU, Q_CPUS, Q_MEM, Q_MEMS, Q_MSG, Q_MSGS, tb::r, tb::s, tb::sbrk, tb0, tb1, and tb::u.
Referenced by __fort_entry_term().
cpu()
static void cpu (struct tb * tbp) static
Definition at line 115 of file stat.c.
References __io_stderr(), a, buf, d, e, GET_DIST_IOPROC, GET_DIST_QUIET, GET_DIST_TCPUS, host, i, n, Q_CPUS, r, s, strlen(), write, and x.
Referenced by __fort_chn_1to1(), __fort_comm_merge(), __fort_crecv(), __fort_csend(), __fort_entry_arecv(), __fort_entry_arecv_done(), __fort_entry_asend(), __fort_entry_asend_done(), __fort_entry_recv(), __fort_entry_recv_done(), __fort_entry_send(), __fort_entry_send_done(), __fort_exchange_counts(), __fort_findndx(), __fort_gathscat(), __fort_genlist(), __fort_global_reduce(), __fort_localize(), __fort_passarg(), __fort_passargs(), __fort_reduce_section(), __fort_rrecv(), __fort_rrecvl(), __fort_rsend(), __fort_rsendl(), __fort_stat_term(), broadcast(), ENTFTN(), gathscat_element(), and gathscat_start().
ENTFTN() [1/2]
void ENTFTN (MSGSTATS , msgstats)
Definition at line 438 of file stat.c.
References tb::byter, tb::bytes, tb::datar, tb::datas, and tb0.
ENTFTN() [2/2]
void ENTFTN (TIMES , times)
Definition at line 42 of file stat.c.
References __fort_gettb(), t, and times().
mem()
static void mem (struct tb * tbp) static
Definition at line 175 of file stat.c.
References __io_stderr(), buf, GET_DIST_IOPROC, GET_DIST_QUIET, GET_DIST_TCPUS, tb::gsbrk, i, tb::majflt, tb::maxrss, tb::minflt, tb::nivcsw, tb::nvcsw, Q_MEMS, sbrk(), scale_kbytes(), strlen(), and write.
Referenced by __fort_stat_term().
msg()
static void msg (struct tb * tbp) static
Definition at line 232 of file stat.c.
References __io_stderr(), ast, buf, tb::bytec, tb::byter, tb::bytes, d, tb::datac, tb::datar, tb::datas, dc, ds(), GET_DIST_IOPROC, GET_DIST_QUIET, GET_DIST_TCPUS, i, Q_MSGS, scale_bytes(), ss, strlen(), and write.
Referenced by __abort(), __abort_err(), __alloc04(), __auto_alloc(), __fort_alloc(), __fort_dealloc(), __fort_dealloc03(), __fort_kalloc(), __fort_print_vector(), __fort_red_abort(), __fort_stat_term(), __fort_status_bcst(), __fort_tracecall(), __fortio_stat_bcst(), chk_arr_extent(), chk_scalar_inttyp(), compose_and_throw(), copy_in_abort(), defined_io_error(), dmp_all_anno(), ENTCRF90IO(), ENTF90IO(), ENTFTN(), err307(), error(), ftn_msgcpy(), gathscat_abort(), global_reduce_abort(), proc_setup(), semant3(), and sym_in_scope().
scale_bytes()
static const char * scale_bytes (double d, double * ds) static
Definition at line 63 of file stat.c.
References d, ds(), and s.
Referenced by msg().
scale_kbytes()
static const char * scale_kbytes (double d, double * ds) static
Definition at line 91 of file stat.c.
References d, ds(), and s.
Referenced by mem().
Variable Documentation
tb0
struct tb tb0 static
Initial value:
= {
                        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ""}
Definition at line 24 of file stat.c.
Referenced by __fort_stat_init(), __fort_stat_term(), and ENTFTN().
tb1
struct tb tb1 static
Initial value:
= {
                        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ""}
Definition at line 28 of file stat.c.
Referenced by __fort_stat_arecv(), __fort_stat_asend(), __fort_stat_copy(), __fort_stat_recv(), __fort_stat_send(), and __fort_stat_term().