flang: state.h File Reference
state.h File Reference
macros to read/write the 'state' file
Macros
#define RW_FD(b, s, n)
#define RW_SCALAR(b) RW_FD(&b, b, 1)
#define RW_ROUTINE int (*p_rw)(void *, size_t, size_t, FILE *)
#define RW_FILE FILE *fd
#define RW_ROUTINE_TYPE int (*)(void *, size_t, size_t, FILE *)
#define ISREAD() (p_rw == (RW_ROUTINE_TYPE)fread)
#define ISWRITE() (p_rw == (RW_ROUTINE_TYPE)fwrite)
Functions
void rw_dpmout_state (RW_ROUTINE, RW_FILE)
void rw_semant_state (RW_ROUTINE, RW_FILE)
void rw_gnr_state (RW_ROUTINE, RW_FILE)
void rw_sym_state (RW_ROUTINE, RW_FILE)
void rw_dtype_state (int(*p_rw)(void *, size_t, size_t, FILE *), FILE *fd)
void rw_ast_state (RW_ROUTINE, RW_FILE)
void rw_dinit_state (RW_ROUTINE, RW_FILE)
void rw_import_state (RW_ROUTINE, RW_FILE)
void rw_mod_state (RW_ROUTINE, RW_FILE)
Detailed Description
macros to read/write the 'state' file
Definition in file state.h.
Macro Definition Documentation
ISREAD
#define ISREAD () (p_rw == (RW_ROUTINE_TYPE)fread)
Definition at line 43 of file state.h.
ISWRITE
#define ISWRITE () (p_rw == (RW_ROUTINE_TYPE)fwrite)
Definition at line 44 of file state.h.
RW_FD
#define RW_FD (b, s, n)
Value:
  {                                              \
    nw = (*p_rw)((char *)(b), sizeof(s), n, fd); \
    if (nw != (n))                               \
      error(10, 40, 0, "(state file)", CNULL);   \
  }
Definition at line 16 of file state.h.
RW_FILE
#define RW_FILE FILE *fd
Definition at line 36 of file state.h.
RW_ROUTINE
#define RW_ROUTINE int (*p_rw)(void *, size_t, size_t, FILE *)
Definition at line 35 of file state.h.
RW_ROUTINE_TYPE
#define RW_ROUTINE_TYPE int (*)(void *, size_t, size_t, FILE *)
Definition at line 37 of file state.h.
RW_SCALAR
#define RW_SCALAR (b) RW_FD(&b, b, 1)
Definition at line 27 of file state.h.
Function Documentation
rw_ast_state()
void rw_ast_state (RW_ROUTINE , RW_FILE)
Definition at line 7583 of file ast.c.
References ASTB::asd, astb, ASTB::hash, ASTB::hshtb, RW_FD, RW_SCALAR, and ASTB::shd.
Referenced by rw_host_state().
rw_dinit_state()
void rw_dinit_state (RW_ROUTINE , RW_FILE)
Definition at line 1647 of file dinit.c.
References assert, astb, ASTB::df, SEM::dinit_nbr_inits, errfatal(), fd, FILE, file_pos, i, VAR::id, interr(), ISREAD, lineno, NULL, VAR::ptr, RW_SCALAR, S_IDENT, sem, tmpfile(), VAR::u, VAR::varref, and void().
Referenced by rw_host_state().
rw_dpmout_state()
void rw_dpmout_state (RW_ROUTINE , RW_FILE)
Definition at line 5230 of file dpm_out.c.
References DTB::avl, DTB::base, dtb, and RW_FD.
Referenced by rw_host_state().
rw_dtype_state()
void rw_dtype_state (int(*)(void *, size_t, size_t, FILE *) p_rw, FILE * fd)
Definition at line 3675 of file dtypeutl.c.
References chartabavail, chartabbase, STB::dt, ISZ_T, RW_FD, and stb.
Referenced by rw_host_state().
rw_gnr_state()
void rw_gnr_state (RW_ROUTINE , RW_FILE)
Definition at line 1316 of file semgnr.c.
References optab, OPTABSIZE, and RW_FD.
Referenced by rw_host_state().
rw_import_state()
void rw_import_state (RW_ROUTINE , RW_FILE)
Definition at line 6451 of file interf.c.
References add_to_use_tree(), imported_modules_struct::avail, i, imported_modules, init_use_tree(), ISREAD, imported_modules_struct::list, uses_list::next, NULL, RW_FD, RW_SCALAR, uses_list::use_module, and use_tree.
Referenced by rw_host_state().
rw_mod_state()
void rw_mod_state (RW_ROUTINE , RW_FILE)
Definition at line 2502 of file module.c.
References BZERO, ISREAD, NEED, NEW, RW_FD, RW_SCALAR, and usedb.
Referenced by rw_host_state().
rw_semant_state()
void rw_semant_state (RW_ROUTINE , RW_FILE)
Definition at line 3607 of file semfin.c.
References STB::curr_scope, SEM::eqv_avail, SEM::eqv_base, SEM::eqv_size, SEM::eqv_ss_avail, SEM::eqv_ss_base, SEM::eqv_ss_size, SEM::eqvlist, fd, ISREAD, NEED, SEM::none_implicit, SYMUTL::none_implicit, RW_FD, RW_SCALAR, SEM::scope_level, SEM::scope_size, SEM::scope_stack, sem, stb, and symutl.
Referenced by rw_host_state().
rw_sym_state()
void rw_sym_state (RW_ROUTINE , RW_FILE)
Definition at line 3222 of file symtab.c.
References AUX::arrdsc_avl, AUX::arrdsc_base, aux, SOC::avail, SOC::base, AUX::dpdsc_avl, AUX::dpdsc_base, STB::firstusym, gbl, STB::hashtb, ISREAD, STB::lbavail, AUX::list, STB::n_base, STB::namavl, NEED, NEW, AUX::nml_avl, AUX::nml_base, RW_FD, RW_SCALAR, SOC::size, soc, stb, AUX::symi_avl, and AUX::symi_base.
Referenced by rw_host_state().