flang: stdioInterf.h File Reference
stdioInterf.h File Reference
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
Macros
#define __io_fclose(fp) fclose(fp)
#define __io_fflush(fp) fflush(fp)
#define __io_fgetc(fp) fgetc(fp)
#define __io_fgets(ptr, n, fp) fgets(ptr, n, fp)
#define __io_fopen(file, typ) fopen(file, typ)
#define __io_fprintf fprintf
#define __io_fputs(ptr, fp) fputs(ptr, fp)
#define __io_fread(ptr, size, nitems, fp) fread(ptr, size, nitems, fp)
#define __io_freopen(file, typ, fp) freopen(file, typ, fp)
#define __io_fscanf fscanf
#define __io_fputc(c, fp) fputc(c, fp)
#define __io_fseek(fp, off, wh) fseek(fp, off, wh)
#define __io_ftell(fp) ftell(fp)
#define __io_fseek64(fp, off, wh) fseek(fp, (long)off, wh)
#define __io_ftell64(fp) (long long) ftell(fp)
#define __io_fseekx(fp, off, wh) fseek(fp, off, wh)
#define __io_ftellx(fp) ftell(fp)
#define __io_gets(ptr) gets(ptr)
#define __io_perror(ptr) perror(ptr)
#define __io_printf printf
#define __io_puts(ptr) puts(ptr)
#define __io_remove(ptr) remove(ptr)
#define __io_rename(ptr1, ptr2) rename(ptr1, ptr2)
#define __io_rewind(fp) rewind(fp)
#define __io_scanf scanf
#define __io_setbuf(fp, ptr) setbuf(fp, ptr)
#define __io_setvbuf(fp, ptr, typ, size) setvbuf(fp, ptr, typ, size)
#define __io_sprintf sprintf
#define __io_sscanf sscanf
#define __io_tmpfile() tmpfile()
#define __io_tmpnam(ptr) tmpnam(ptr)
#define __io_ungetc(c, fp) ungetc(c, fp)
#define __io_strtod(p, ep) __fortio_strtod(p, ep)
#define __io_ecvt(v, w, n, d, s, r, q) __fortio_ecvt(v, w, n, d, s, r, q)
#define __io_fcvt(v, w, n, sf, d, s, r, q) __fortio_fcvt(v, w, n, sf, d, s, r, q)
#define __io_strtold(p, ep) __fortio_strtold(p, ep)
#define __fort_getfd(fp) __io_getfd(fp)
#define __fort_isatty(fd) __io_isatty(fd)
#define __fort_truncate(name, len) truncate(name, len)
#define __fort_ftruncate(fd, len) ftruncate(fd, len)
#define __fort_access(path, mode) access(path, mode)
#define __fort_unlink(path) unlink(path)
#define __fort_getenv(name) getenv(name)
#define __io_abort() exit(1)
#define __fortio_ispipe(fp) __io_ispipe(fp)
#define WIN_CDECL
#define WIN_MSVCRT_IMP extern
Typedefs
typedef long seekoff_t
typedef long long seekoff64_t
typedef long seekoffx_t
Functions
int __io_errno (void)
void __io_set_errno (int)
FILE * __io_stdin (void)
FILE * __io_stdout (void)
FILE * __io_stderr (void)
int __io_getc (FILE *)
int __io_putc (int x, FILE *)
int __io_getchar (void)
int __io_putchar (int x)
void __io_clearerr (FILE *)
int __io_getfd (FILE *)
int __io_isatty (int fd)
int __io_binary_mode (FILE *)
int __io_setmode_binary (FILE *)
int __io_ispipe (FILE *)
int __io_feof (FILE *)
int __io_ferror (FILE *)
size_t __io_fwrite (const void *, size_t, size_t, FILE *)
int __io_timezone (void *)
int fclose (FILE *)
int fflush (FILE *)
int __io_fputc (int, FILE *)
FILE * tmpfile (void)
char * tmpnam (char *)
char * __io_tempnam (const char *, const char *)
void * __aligned_malloc (size_t, size_t)
void __aligned_free (void *)
int __fenv_fegetzerodenorm (void)
Unimplemented: Get (flush to zero) underflow mode.
void __abort (int sv, const char *msg)
void __abort_trace (int skip)
void __abort_sig_init (void)
Macro Definition Documentation
__fort_access
#define __fort_access (path, mode) access(path, mode)
Definition at line 75 of file stdioInterf.h.
__fort_ftruncate
#define __fort_ftruncate (fd, len) ftruncate(fd, len)
Definition at line 74 of file stdioInterf.h.
__fort_getenv
#define __fort_getenv (name) getenv(name)
Definition at line 77 of file stdioInterf.h.
__fort_getfd
#define __fort_getfd (fp) __io_getfd(fp)
Definition at line 70 of file stdioInterf.h.
__fort_isatty
#define __fort_isatty (fd) __io_isatty(fd)
Definition at line 71 of file stdioInterf.h.
__fort_truncate
#define __fort_truncate (name, len) truncate(name, len)
Definition at line 73 of file stdioInterf.h.
__fort_unlink
#define __fort_unlink (path) unlink(path)
Definition at line 76 of file stdioInterf.h.
__fortio_ispipe
#define __fortio_ispipe (fp) __io_ispipe(fp)
Definition at line 79 of file stdioInterf.h.
__io_abort
#define __io_abort () exit(1)
Definition at line 78 of file stdioInterf.h.
__io_ecvt
#define __io_ecvt (v, w, n, d, s, r, q) __fortio_ecvt(v, w, n, d, s, r, q)
Definition at line 63 of file stdioInterf.h.
__io_fclose
#define __io_fclose (fp) fclose(fp)
Definition at line 19 of file stdioInterf.h.
__io_fcvt
#define __io_fcvt (v, w, n, sf, d, s, r, q) __fortio_fcvt(v, w, n, sf, d, s, r, q)
Definition at line 64 of file stdioInterf.h.
__io_fflush
#define __io_fflush (fp) fflush(fp)
Definition at line 20 of file stdioInterf.h.
__io_fgetc
#define __io_fgetc (fp) fgetc(fp)
Definition at line 21 of file stdioInterf.h.
__io_fgets
#define __io_fgets (ptr, n, fp) fgets(ptr, n, fp)
Definition at line 22 of file stdioInterf.h.
__io_fopen
#define __io_fopen (file, typ) fopen(file, typ)
Definition at line 24 of file stdioInterf.h.
__io_fprintf
#define __io_fprintf fprintf
Definition at line 26 of file stdioInterf.h.
__io_fputc
#define __io_fputc (c, fp) fputc(c, fp)
Definition at line 32 of file stdioInterf.h.
__io_fputs
#define __io_fputs (ptr, fp) fputs(ptr, fp)
Definition at line 27 of file stdioInterf.h.
__io_fread
#define __io_fread (ptr, size, nitems, fp) fread(ptr, size, nitems, fp)
Definition at line 28 of file stdioInterf.h.
__io_freopen
#define __io_freopen (file, typ, fp) freopen(file, typ, fp)
Definition at line 29 of file stdioInterf.h.
__io_fscanf
#define __io_fscanf fscanf
Definition at line 30 of file stdioInterf.h.
__io_fseek
#define __io_fseek (fp, off, wh) fseek(fp, off, wh)
Definition at line 35 of file stdioInterf.h.
__io_fseek64
#define __io_fseek64 (fp, off, wh) fseek(fp, (long)off, wh)
Definition at line 38 of file stdioInterf.h.
__io_fseekx
#define __io_fseekx (fp, off, wh) fseek(fp, off, wh)
Definition at line 41 of file stdioInterf.h.
__io_ftell
#define __io_ftell (fp) ftell(fp)
Definition at line 36 of file stdioInterf.h.
__io_ftell64
#define __io_ftell64 (fp) (long long) ftell(fp)
Definition at line 39 of file stdioInterf.h.
__io_ftellx
#define __io_ftellx (fp) ftell(fp)
Definition at line 42 of file stdioInterf.h.
__io_gets
#define __io_gets (ptr) gets(ptr)
Definition at line 44 of file stdioInterf.h.
__io_perror
#define __io_perror (ptr) perror(ptr)
Definition at line 45 of file stdioInterf.h.
__io_printf
#define __io_printf printf
Definition at line 46 of file stdioInterf.h.
__io_puts
#define __io_puts (ptr) puts(ptr)
Definition at line 47 of file stdioInterf.h.
__io_remove
#define __io_remove (ptr) remove(ptr)
Definition at line 48 of file stdioInterf.h.
__io_rename
#define __io_rename (ptr1, ptr2) rename(ptr1, ptr2)
Definition at line 49 of file stdioInterf.h.
__io_rewind
#define __io_rewind (fp) rewind(fp)
Definition at line 50 of file stdioInterf.h.
__io_scanf
#define __io_scanf scanf
Definition at line 51 of file stdioInterf.h.
__io_setbuf
#define __io_setbuf (fp, ptr) setbuf(fp, ptr)
Definition at line 52 of file stdioInterf.h.
__io_setvbuf
#define __io_setvbuf (fp, ptr, typ, size) setvbuf(fp, ptr, typ, size)
Definition at line 53 of file stdioInterf.h.
__io_sprintf
#define __io_sprintf sprintf
Definition at line 54 of file stdioInterf.h.
__io_sscanf
#define __io_sscanf sscanf
Definition at line 55 of file stdioInterf.h.
__io_strtod
#define __io_strtod (p, ep) __fortio_strtod(p, ep)
Definition at line 62 of file stdioInterf.h.
__io_strtold
#define __io_strtold (p, ep) __fortio_strtold(p, ep)
Definition at line 67 of file stdioInterf.h.
__io_tmpfile
#define __io_tmpfile () tmpfile()
Definition at line 56 of file stdioInterf.h.
__io_tmpnam
#define __io_tmpnam (ptr) tmpnam(ptr)
Definition at line 57 of file stdioInterf.h.
__io_ungetc
#define __io_ungetc (c, fp) ungetc(c, fp)
Definition at line 58 of file stdioInterf.h.
WIN_CDECL
#define WIN_CDECL
Definition at line 121 of file stdioInterf.h.
WIN_MSVCRT_IMP
#define WIN_MSVCRT_IMP extern
Definition at line 122 of file stdioInterf.h.
Typedef Documentation
seekoff64_t
typedef long long seekoff64_t
Definition at line 37 of file stdioInterf.h.
seekoff_t
typedef long seekoff_t
Definition at line 34 of file stdioInterf.h.
seekoffx_t
typedef long seekoffx_t
Definition at line 40 of file stdioInterf.h.
Function Documentation
__abort()
void __abort (int sv, const char * msg)
Definition at line 66 of file flangrti/trace.c.
References __abort_trace(), __io_stderr(), dbg_stop_before_exit(), fflush(), getenv(), msg(), n, NULL, p, T_ABORT, T_DEBUG, T_TEST, T_TRACE, and tracopt.
Referenced by __abort_err(), __abort_sig_hand(), __fort_abortx(), __fort_check_map(), __fort_getmap(), and __getfile3f().
__abort_sig_init()
void __abort_sig_init (void)
Definition at line 258 of file trace_lin.c.
References __abort_sig_hand(), n, new, and void().
Referenced by __abort_init().
__abort_trace()
void __abort_trace (int skip)
Definition at line 174 of file trace_lin.c.
References __io_stderr(), dumpregs(), FLANGRTI_GREGSET_T, i, MAXTRACE, print_back_trace_line(), regs, size, and skip.
Referenced by __abort().
__aligned_free()
void __aligned_free (void * p)
Definition at line 52 of file memalign.c.
References p.
__aligned_malloc()
void * __aligned_malloc (size_t sz, size_t aln)
Definition at line 17 of file memalign.c.
References MINALN, NULL, q, s, and sz.
__fenv_fegetzerodenorm()
int __fenv_fegetzerodenorm (void)
Unimplemented: Get (flush to zero) underflow mode.
Returns
1 if flush to zero is set, 0 otherwise
Definition at line 682 of file fltfenv.c.
__io_binary_mode()
int __io_binary_mode (FILE *)
__io_clearerr()
void __io_clearerr (FILE *)
__io_errno()
int __io_errno (void)
Definition at line 51 of file iostdinit.c.
Referenced by __f90io_unf_read(), __f90io_unf_write(), __f90io_usw_read(), __f90io_usw_write(), __fortio_close(), __fortio_open(), __fortio_rwinit(), __fortio_trunc(), __fortio_zeropad(), __INT_T(), __unf_end(), __unf_init(), __usw_end(), _f90io_backspace(), _f90io_fmtr_end(), _f90io_ldw_end(), _f90io_rewind(), asy_wait(), ENT3F(), ENTF90IO(), fr_read_record(), fw_write_record(), inquire(), read_record(), skip_record(), skip_to_nextrec(), write_item(), and write_record().
__io_feof()
int __io_feof (FILE *)
__io_ferror()
int __io_ferror (FILE *)
__io_fputc()
int __io_fputc (int , FILE *)
Referenced by __fortio_close(), _f90io_backspace(), _f90io_rewind(), and fw_write_record().
__io_fwrite()
size_t __io_fwrite (const void * , size_t , size_t , FILE *)
__io_getc()
int __io_getc (FILE *)
__io_getchar()
int __io_getchar (void)
Definition at line 122 of file iostdinit.c.
__io_getfd()
int __io_getfd (FILE *)
__io_isatty()
int __io_isatty (int fd)
Definition at line 162 of file iostdinit.c.
References fd.
Referenced by __isatty3f().
__io_ispipe()
int __io_ispipe (FILE *)
__io_putc()
int __io_putc (int x, FILE *)
__io_putchar()
int __io_putchar (int x)
Definition at line 128 of file iostdinit.c.
References x.
Referenced by __fort_get_scalar().
__io_set_errno()
void __io_set_errno (int value)
Definition at line 59 of file iostdinit.c.
References value().
Referenced by asy_wait(), ENT3F(), Fio_asy_open(), and ufptod().
__io_setmode_binary()
int __io_setmode_binary (FILE *)
__io_stderr()
FILE * __io_stderr (void)
Definition at line 79 of file iostdinit.c.
Referenced by __abort(), __abort_err(), __abort_init(), __abort_trace(), __fort_abortp(), __fort_begpar(), __fort_check_map(), __fort_describe(), __fort_dump_type(), __fort_getmap(), __fort_print_local(), __fort_print_scalar(), __fort_print_vector(), __fort_print_version(), __fort_show_flags(), __fort_show_index(), __fort_show_scalar(), __fort_show_section(), __fortio_eoferr(), __fortio_eorerr(), __fortio_error(), __fortio_init(), __getfile3f(), __llcrit_atfork(), _f90io_f2003_stop_with_ieee_warnings(), _f90io_pause(), _f90io_stop(), _mp_bcs_nest(), _mp_bcs_nest_red(), cpu(), ENT3F(), ENTF90(), ENTF90COMN(), ENTFTN(), Ftn_str_malloc(), Ftn_str_malloc_klen(), ioerrinfo(), MAIN__(), mem(), msg(), print_back_trace_line(), print_loop(), print_row(), and sighand().
__io_stdin()
FILE * __io_stdin (void)
Definition at line 67 of file iostdinit.c.
Referenced by __fortio_init(), __getfile3f(), and _f90io_pause().
__io_stdout()
FILE * __io_stdout (void)
Definition at line 73 of file iostdinit.c.
Referenced by __fortio_init(), and __getfile3f().
__io_tempnam()
char * __io_tempnam (const char * dir, const char * pfx)
Definition at line 129 of file tempnam.c.
References access, gentmp(), and p.
Referenced by __fortio_scratch_name().
__io_timezone()
int __io_timezone (void * tm)
Definition at line 263 of file iostdinit.c.
References timezone.
Referenced by ENTFTN().
fclose()
int fclose (FILE *)
Referenced by __pg_make_lock_file(), _nextline(), _readln(), apply_use(), ccff_close(), datastructure_reinit(), df_dinit_end(), dinit_end(), do_dinit(), do_nested_uses(), end_module(), export_inline(), extractor_end(), finish(), flushsym(), import_inline(), load_inline_file(), load_TOC(), lower_end_contains(), lower_ilm_finish(), main(), mod_fini(), par_xref(), print_back_trace_line(), process_stb_file(), scan_fini(), sem_fini(), write_comm(), xref(), and zprntk().
fflush()
int fflush (FILE *)
Referenced by __abort(), __fortio_rwinit(), __math_dispatch_error(), __math_epilog_do_stats(), dmp_all_anno(), dmp_anno(), dump_cand(), dump_ind(), ENT3F(), export(), export_host_subprogram(), export_module_subprogram(), fw_write_record(), ll_write_instruction(), lzfinifile(), and restore_host_state().
tmpfile()
FILE * tmpfile (void)
Referenced by accpp(), apply_use(), dinit(), dinit_put(), end_module(), fpp(), init(), lower(), lower_ilm_header(), lower_put_datatype_stb(), lower_symbol_stb(), push_include(), put_data_statement(), reset_module_state(), restore_host_state(), rw_dinit_state(), save_host_state(), save_imported_modules_state(), save_module_state1(), scan_include(), scan_init(), stb_lower_sym_header(), write_comm(), and xrefinit().
tmpnam()
char * tmpnam (char *)
Referenced by inquire().