flang: symacc.cpp File Reference
symacc.cpp File Reference
Generic access module. Used by all compilers and initialization utility.
#include "symacc.h"
#include "error.h"
#include <stdarg.h>
Functions
void sym_init_first (void)
void realloc_sym_storage ()
Expand symbol storage area when NEWSYM runs out of area.
SPTR lookupsym (const char *name, int olength)
Look up symbol with indicated name.
static void report_too_long_identifier (const char *name, int olength, int max_idlen)
Issue diagnostic for identifer that is too long.
SPTR lookupsymbol (const char *name)
Get the symbol table index for a NUL-terminated name.
SPTR lookupsymf (const char *fmt,...)
Construct a name via printf-style formatting and then look it up in the symbol table via lookupsymbol().
SPTR installsym_ex (const char *name, int olength, IS_MODE mode)
Enter symbol with indicated name into symbol table, initialize the new entry, and return pointer to it. If there is already such a symbol, just return pointer to the existing symbol table entry.
int putsname (const char *name, int length)
Put a string of characters into the symbol names storage area and return pointer to the string (relative to stb.n_base). This routine is used to enter both symbol names and character string constants.
char * local_sname (char *name)
Create a local copy of a name known to be stored in the 'stb.n_base' area.
void add_fp_constants (void)
bool is_flt0 (SPTR sptr)
bool is_dbl0 (SPTR sptr)
bool is_quad0 (SPTR sptr)
bool is_cmplx_flt0 (SPTR sptr)
bool is_creal_flt0 (SPTR sptr)
bool is_cimag_flt0 (SPTR sptr)
bool is_cmplx_dbl0 (SPTR sptr)
bool is_cmplx_quad0 (SPTR sptr)
void symini_errfatal (int n)
void symini_error (int n, int s, int l, const char *c1, const char *c2)
void symini_interr (const char *txt, int val, int sev)
Variables
STB stb
GBL gbl
Detailed Description
Generic access module. Used by all compilers and initialization utility.
Definition in file symacc.cpp.
Function Documentation
add_fp_constants()
void add_fp_constants (void)
Definition at line 335 of file symacc.cpp.
References atoxd(), atoxf(), atoxq(), CONVAL2G, STB::dbl0, STB::dbl1, STB::dbl2, STB::dblhalf, STB::dblm0, DT_DBLE, DT_REAL, STB::flt0, STB::flt1, STB::flt2, STB::flthalf, STB::fltm0, getcon(), STB::quad0, STB::quad1, STB::quad2, STB::quadhalf, STB::quadm0, res, stb, tmp, xdneg(), xfneg(), and xqneg().
installsym_ex()
SPTR installsym_ex (const char * name, int olength, IS_MODE mode)
Enter symbol with indicated name into symbol table, initialize the new entry, and return pointer to it. If there is already such a symbol, just return pointer to the existing symbol table entry.
Parameters
name is the symbol name.
olength is the number of characters in the symbol name.
Definition at line 196 of file symacc.cpp.
References flg, gbl, HASH_ID, STB::hashtb, IS_QUICK, length(), GBL::lineno, LINKSYM, MAXIDLEN, mode, STB::n_base, STB::namavl, name, NEWSYM, NOSYM, putsname(), report_too_long_identifier(), sptr, FLG::standard, and stb.
is_cimag_flt0()
bool is_cimag_flt0 (SPTR sptr)
Definition at line 457 of file symacc.cpp.
References CONVAL2G, STB::flt0, STB::fltm0, sptr, and stb.
is_cmplx_dbl0()
bool is_cmplx_dbl0 (SPTR sptr)
Definition at line 466 of file symacc.cpp.
References is_dbl0(), sptr, SymConval1, and SymConval2.
is_cmplx_flt0()
bool is_cmplx_flt0 (SPTR sptr)
Definition at line 435 of file symacc.cpp.
References CONVAL2G, STB::flt0, STB::fltm0, sptr, and stb.
is_cmplx_quad0()
bool is_cmplx_quad0 (SPTR sptr)
Definition at line 472 of file symacc.cpp.
References is_quad0(), sptr, SymConval1, and SymConval2.
is_creal_flt0()
bool is_creal_flt0 (SPTR sptr)
Definition at line 448 of file symacc.cpp.
References CONVAL2G, STB::flt0, STB::fltm0, sptr, and stb.
is_dbl0()
bool is_dbl0 (SPTR sptr)
Definition at line 411 of file symacc.cpp.
References STB::dbl0, STB::dblm0, sptr, and stb.
Referenced by is_cmplx_dbl0().
is_flt0()
bool is_flt0 (SPTR sptr)
Definition at line 403 of file symacc.cpp.
References STB::flt0, STB::fltm0, sptr, and stb.
is_quad0()
bool is_quad0 (SPTR sptr)
Definition at line 419 of file symacc.cpp.
References STB::quad0, STB::quadm0, sptr, and stb.
Referenced by is_cmplx_quad0().
local_sname()
char * local_sname (char * name)
Create a local copy of a name known to be stored in the 'stb.n_base' area.
Used when a symbol needs to be created from a name stored in the area; a purify umr error could occur if the area is realloc'd. The char pointer to the copy is returned.
Definition at line 312 of file symacc.cpp.
References length(), name, NEED, NEW, and strlen().
lookupsym()
SPTR lookupsym (const char * name, int olength)
Look up symbol with indicated name.
Returns
If there is already such a symbol, the pointer to the existing symbol table entry; or 0 if a symbol doesn't exist.
Parameters
name is a symbol name.
olength is the number of characters in the symbol name.
Definition at line 102 of file symacc.cpp.
References HASH_ID, STB::hashtb, length(), MAXIDLEN, name, sptr, SPTR_NULL, stb, and SYMNAME.
Referenced by lookupsymbol().
lookupsymbol()
SPTR lookupsymbol (const char * name)
Get the symbol table index for a NUL-terminated name.
Definition at line 165 of file symacc.cpp.
References lookupsym(), name, and strlen().
Referenced by lookupsymf().
lookupsymf()
SPTR lookupsymf (const char * fmt, ...)
Construct a name via printf-style formatting and then look it up in the symbol table via lookupsymbol().
Definition at line 175 of file symacc.cpp.
References lookupsymbol(), and MAXIDLEN.
putsname()
int putsname (const char * name, int length)
Put a string of characters into the symbol names storage area and return pointer to the string (relative to stb.n_base). This routine is used to enter both symbol names and character string constants.
Parameters
name are the characters to be entered.
length is the number of characters to be entered.
Definition at line 275 of file symacc.cpp.
References i, length(), MAX_NMPTR, n, STB::n_base, STB::n_size, STB::namavl, name, NEED, stb, and symini_errfatal().
Referenced by installsym_ex().
realloc_sym_storage()
void realloc_sym_storage ()
Expand symbol storage area when NEWSYM runs out of area.
It is assumed that stb.stg_avail is 1 more than the index of the current symbol being created.
Definition at line 80 of file symacc.cpp.
References DEBUG_ASSERT, NULL, SPTR_MAX, stb, STG_NEED, and symini_errfatal().
report_too_long_identifier()
static void report_too_long_identifier (const char * name, int olength, int max_idlen) static
Issue diagnostic for identifer that is too long.
Parameters
name - identifier (without terminating njull)
olength - length of identifier
max_idlen - maximum allowed length
Though this routine has only one lexical call site, it is factored out to not clutter the common path in installsym_ex.
Definition at line 140 of file symacc.cpp.
References gbl, GBL::lineno, name, NEED, NEW, strlen(), and symini_error().
Referenced by installsym_ex().
sym_init_first()
void sym_init_first (void)
Definition at line 37 of file symacc.cpp.
References assert, STB::dt, ERR_Fatal, HASHSIZE, STB::hashtb, i, STB::n_base, STB::n_size, STB::namavl, NEW, NULL, SPTR_NULL, stb, STB_NSIZE, STG_ALLOC, STB::w_base, STB::w_size, and STB::wrdavl.
symini_errfatal()
void symini_errfatal (int n)
Definition at line 478 of file symacc.cpp.
References errfatal(), and n.
Referenced by putsname(), and realloc_sym_storage().
symini_error()
void symini_error (int n, int s, int l, const char * c1, const char * c2)
Definition at line 484 of file symacc.cpp.
References error(), n, and s.
Referenced by report_too_long_identifier(), and symini_interr().
symini_interr()
void symini_interr (const char * txt, int val, int sev)
Definition at line 490 of file symacc.cpp.
References buff, gbl, GBL::lineno, symini_error(), and val.
Variable Documentation
gbl
GBL gbl extern
Definition at line 21 of file fenddf.c.
Referenced by installsym_ex(), report_too_long_identifier(), and symini_interr().
stb
STB stb extern
Referenced by add_fp_constants(), installsym_ex(), is_cimag_flt0(), is_cmplx_flt0(), is_creal_flt0(), is_dbl0(), is_flt0(), is_quad0(), lookupsym(), putsname(), realloc_sym_storage(), and sym_init_first().