flang: symtab.c File Reference
symtab.c File Reference
Fortran - symbol table access module.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "machar.h"
#include "symtab.h"
#include "symtabdf.h"
#include "symutl.h"
#include "syminidf.h"
#include "dtypeutl.h"
#include "soc.h"
#include "state.h"
#include "ast.h"
#include "semant.h"
#include "llmputil.h"
#include "rtlRtns.h"
#include "rte.h"
#include <stdarg.h>
Classes
struct DTIMPL
struct DEC_DEF_MAP
Macros
#define IPA_RECOMPILATION_SUFFIX (XBIT(89, 0x40) ? "i" : "")
#define NXTRA 2
#define _PFG(cond, str)
Functions
static void cng_inttyp (int, int)
static void generate_type_mismatch_errors (SPTR s1, SPTR s2)
Emit variable type mismatch errors for either subprogram argument variables or function return type based on separate module subprogram's definition vs. its declaration.
static void update_arrdsc (SPTR s, DEC_DEF_MAP *smap, int num_dummies)
Update array bound AST SPTRs (old_sptr) using newly created SPTRs (new_sptr) by referring to DEC_DEF_MAP. The DEC_DEF_MAP is a struct which contains mapping info from the old_sptr to new_sptr.
void sym_init (void)
...
void init_implicit (void)
void implicit_int (int default_int)
void save_implicit (LOGICAL reset)
void restore_implicit (void)
void hpf_library_stat (int *firstp, int *lastp, int stype)
void iso_c_lib_stat (int *firstp, int *lastp, int stype)
int get_ieee_arith_intrin (const char *nm)
int getsymbol (const char *name)
...
int getsym (const char *name, int olength)
Enter symbol with indicated name into symbol table, initialize the new entry.
int getsymf (const char *fmt,...)
SPTR getcon (INT *value, DTYPE dtype)
Enter constant of given dtype and value into the symbol table and return pointer to it.
int hashcon (INT *value, int dtype, int sptr)
SPTR get_acon (SPTR sym, ISZ_T off)
...
SPTR get_acon3 (SPTR sym, ISZ_T off, DTYPE dtype)
...
ISZ_T get_isz_cval (int con)
...
INT get_int_cval (int con)
INT sign_extend (INT val, int width)
...
int getstring (const char *value, int length)
Enter character constant into symbol table and return pointer to it.
int gethollerith (int strcon, int kind)
void newimplicit (int firstc, int lastc, int dtype)
Change the current settings for implicit variable types and character lengths.
void newimplicitnone (void)
void setimplicit (int sptr)
...
LOGICAL was_implicit (int sptr)
Return FALSE if this symbol could not have been properly implicitly typed.
const char * parmprint (int sptr)
Return ptr to printable representation of the indicated PARAMETER.
static const char * __log_print (INT val)
const char * getprint (int sptr)
...
void symdentry (FILE *file, int sptr)
...
void symdmp (FILE *dfil, LOGICAL full)
void dmp_socs (int sptr, FILE *file)
...
int getccsym (int letter, int n, SYMTYPE stype)
int getnewccsym (int letter, int n, int stype)
static int getnewccsym2 (char *name, int n, int stype)
int getnewccsymf (int stype, const char *fmt,...)
int getccsym_sc (int letter, int n, int stype, int sc)
int getccssym (const char *pfx, int n, int stype)
int getccssym_sc (const char *pfx, int n, int stype, int sc)
int getcctmp_sc (int letter, int n, int stype, int dtype, int sc)
int getcctmp (int letter, int n, int stype, int dtype)
int insert_sym (int first)
int insert_sym_first (int first)
int getlab (void)
...
LOGICAL sym_in_sym_list (int sptr, int list)
Return TRUE if sptr is in symi list represented by list.
LOGICAL same_sym_list (int list1, int list2)
Return TRUE if these two symi lists have the same sptrs in the same order.
void pop_sym (int sptr)
remove a symbol from its hash list
void push_sym (int sptr)
push a symbol onto a hash list
SPTR mkfunc (const char *nmptr)
...
const char * mk_coercion_func_name (int dtype)
create a coercion function based on the data type.
int mk_coercion_func (int dtype)
Create a coercion function based on the data type.
int mk_external_var (char *name, int dtype)
LOGICAL is_arg_in_entry (int ent, int arg)
determine if an argument is an argument to a given entry
LOGICAL is_argp_in_entry (int ent, int arg)
determine if an argument $p is an $p of argument to a given entry
int resolve_sym_aliases (int sptr)
LOGICAL is_procedure_ptr (int sptr)
void proc_arginfo (int sptr, int *paramct, int *dpdsc, int *iface)
bool cmp_interfaces (int sym1, int sym2, int flag)
Compares two symbols by returning true if they both have equivalent interfaces. Otherwise, return false.
bool compatible_characteristics (int psptr, int psptr2, cmp_interface_flags flag)
Tests the characteristics between two interfaces.
bool cmp_interfaces_strict (SPTR sym1, SPTR sym2, cmp_interface_flags flag)
Same as cmp_interfaces() except we also compare the characteristics as defined in "12.2 Characteristics of procedures" in F2003 Spec.
void copy_sym_flags (SPTR dest, SPTR src)
Copy flags from one symbol to another symbol.
void dup_sym (int new, SYM *content)
int insert_dup_sym (int sptr)
SPTR get_ancestor_module (SPTR mod)
SPTR find_explicit_interface (SPTR s)
SPTR instantiate_interface (SPTR iface)
Instantiate a copy of a separate module subprogram's declared interface as part of the MODULE PROCEDURE's definition (i.e., implement what would have taken place had the subprogram been defined with a MODULE SUBROUTINE or MODULE FUNCTION with a compatible interface).
void reinit_sym (int sptr)
char * sym_strsave (const char *s)
char * mangle_name (const char *basename, const char *purpose)
char * mangle_name_dt (const char *basename, const char *purpose, int encldtype)
void save_uname (int newsptr, INT oldnmptr)
int add_symitem (int sptr, int nxt)
...
void change_predefineds (int stype, LOGICAL remove)
void dbg_symdentry (int sptr)
...
void rw_sym_state (RW_ROUTINE, RW_FILE)
void symtab_fini (void)
void symtab_standard (void)
void symtab_nostandard (void)
int can_map_initsym (int old_firstosym)
Adding intrinsics, predeclareds, etc. to symini_ftn has the effect of rendering existng .mod files incompatible because the values of stb.firstosym will be different.
int map_initsym (int oldsym, int old_firstosym)
Determine if oldsym, read from a .mod file, is a predefined (intrinsic, predeclared, constant, etc.).
void convert_2dollar_signs_to_hyphen (char *name)
Convert two dollar signs to a hyphen. Especially used for the submodule *.mod file renaming: ancestor$$submod.mod -> ancestor-submod.mod.
bool is_used_by_submod (SPTR sym1, SPTR sym2)
Used for check whether sym2 used inside the scope of sym1 is defined in parent modules (SCOPEG(sym2)) and used by inherited submodules ENCLFUNCG(sym1).
Variables
static DTIMPL dtimplicit
static int dtimplicitsize = 0
static DTIMPL * save_dtimplicit = NULL
static int dtimplicitstack = 0
static ENTRY onlyentry
static int manglecount = 0
Detailed Description
Fortran - symbol table access module.
This module contains the routines used to initialize, update, access, and dump the symbol table. Note that in addition to being used by PGHPF, this module is used by the utility program, symini, which processes intrinsic and generic definitions in order to set up the initial symbol table for PGHPF.
Definition in file symtab.c.
Macro Definition Documentation
_PFG
#define _PFG (cond, str)
Value:
  if (cond)             \
  fprintf(dfil, "  %s", str)
Definition at line 1084 of file symtab.c.
IPA_RECOMPILATION_SUFFIX
#define IPA_RECOMPILATION_SUFFIX (XBIT(89, 0x40) ? "i" : "")
Definition at line 41 of file symtab.c.
NXTRA
#define NXTRA 2
Function Documentation
__log_print()
static const char * __log_print (INT val) static
Return ptr to printable representation of the indicated symbol. For symbols which are not constants, the name of the symbol is used. Constants are converted into the appropriate character representation.
Definition at line 933 of file symtab.c.
References val.
Referenced by getprint().
add_symitem()
int add_symitem (int sptr, int nxt)
...
Definition at line 3181 of file symtab.c.
References aux, i, NEED, sptr, AUX::symi_avl, AUX::symi_base, SYMI_NEXT, AUX::symi_size, and SYMI_SPTR.
Referenced by add_only(), add_overload(), apply_use(), check_doconcurrent(), check_doconcurrent_ast(), import(), import_use_stmts(), sem_import_sym(), semant1(), and semant3().
can_map_initsym()
int can_map_initsym (int old_firstosym)
Adding intrinsics, predeclareds, etc. to symini_ftn has the effect of rendering existng .mod files incompatible because the values of stb.firstosym will be different.
stb.firstosym is computed from:
the number of intrinsics, predeclareds defined by symini_ftn, and
the number of predeclared constants/symbols created in symtab.c:sym_init() (e.g., 1.0, 0, 2, etc.)
It should be possible to map the 'firstosym' symbols from the previous symini to the current symini by just subscripting a table using the old symbol as the index. The purpose of oldsyms0() is to generate the table, map_init0[], based on the old (6.1) version of symini and the current symini which defines the mapping. The 6.1 information, represented by init_sym0[] and init_names0[], are manually extracted from the 6.1-generated syminidf.h; these tables are just renamed versions of init_sym[] & init_names[]. oldsyms0() just scans these 'symbols' and looks for the symbols with the same names in the current symini. In addition to generating the table, map_init0[], the size of the table, init_syms0_size, is generated. If new intrinsics are added after today's symini is released, a new table & size, presumably named init_sym1 and init_syms1_size, will be generated from inputs init_sym1 & init_names1. This process should be able to be repreated to create map_init2, ...
Determine if a firstosym value read from a .mod file matches the current initial symtab or a previous initial symtab for which we have mapping information.
Definition at line 3368 of file symtab.c.
References STB::firstosym, NXTRA, and stb.
Referenced by import_header_only().
change_predefineds()
void change_predefineds (int stype, LOGICAL remove)
switch from ST_CRAFT/ST_CRAY to ST_PD or vice versa
Definition at line 3195 of file symtab.c.
References BCOPY, first, hpf_library_stat(), last, s, and stb.
Referenced by semant_init().
cmp_interfaces()
bool cmp_interfaces (int sym1, int sym2, int flag)
Compares two symbols by returning true if they both have equivalent interfaces. Otherwise, return false.
If flag is set, then we also make sure that sym1 and sym2 have the same symbol name.
Definition at line 2449 of file symtab.c.
References aux, cmp_interfaces(), AUX::dpdsc_base, eq_dtype2(), HASH_ID, STB::hashtb, i, len, NOSYM, proc_arginfo(), scope, stb, strlen(), SYMNAME, and test_scope().
Referenced by cmp_interfaces(), eq_dtype2(), fix_proc_ptr_dummy_args(), and tk_match_arg().
cmp_interfaces_strict()
bool cmp_interfaces_strict (SPTR sym1, SPTR sym2, cmp_interface_flags flag)
Same as cmp_interfaces() except we also compare the characteristics as defined in "12.2 Characteristics of procedures" in F2003 Spec.
Definition at line 2655 of file symtab.c.
References aux, CMP_IFACE_NAMES, CMP_SUBMOD_IFACE, compatible_characteristics(), AUX::dpdsc_base, ERR_Severe, error(), gbl, i, j, NULL, proc_arginfo(), RELAX_PURE_CHK_1, RELAX_PURE_CHK_2, and SYMNAME.
Referenced by add_ptr_assign(), compatible_characteristics(), semant1(), semCheckTbp(), and transform_call().
cng_inttyp()
static void cng_inttyp (int ss, int dt) static
Definition at line 308 of file symtab.c.
References assert, dt, and ss.
Referenced by sym_init().
compatible_characteristics()
bool compatible_characteristics (int psptr, int psptr2, cmp_interface_flags flag)
Tests the characteristics between two interfaces.
Parameters
psptr is the first interface.
pstr2 is the second interface.
flag is a bit mask that enforces/relaxes certain checks (see cmp_interface_flags enum in symtab.c).
Returns
true if the two characteristics are compatible, else false.
Definition at line 2551 of file symtab.c.
References AD_DPTR, AD_EXTNTAST, AD_NUMDIM, ast, cmp_interfaces_strict(), CMP_OPTARG, CMP_SUBMOD_IFACE, CONVAL2G, DDTG, DEFER_IFACE_CHK, DTY, DTYG, eq_dtype2(), ERR_Severe, error(), FALSE, gbl, generate_type_mismatch_errors(), i, IGNORE_ARG_NAMES, INTENTG, RELAX_INTENT_CHK, RELAX_POINTER_CHK, RELAX_STYPE_CHK, SYMNAME, TY_CHAR, and TY_NCHAR.
Referenced by cmp_interfaces_strict(), compat_arg_lists(), and defer_arg_chk().
convert_2dollar_signs_to_hyphen()
void convert_2dollar_signs_to_hyphen (char * name)
Convert two dollar signs to a hyphen. Especially used for the submodule *.mod file renaming: ancestor$$submod.mod -> ancestor-submod.mod.
Definition at line 3461 of file symtab.c.
References name, p, and q.
Referenced by add_to_be_used_list(), export_all(), and open_module().
copy_sym_flags()
void copy_sym_flags (SPTR dest, SPTR src)
Copy flags from one symbol to another symbol.
This routine is the same as dup_sym() except it preserves the symbol's name, hash link, scope, and name pointer. In other words, it copies all but 4 flags from one symbol to another. The 4 flags that are not copied are the hashlk, symlk, scope, and nmptr.
Parameters
dest is the receiving symbol table pointer of the flags.
src is the source symbol table pointer of the flags.
Definition at line 2791 of file symtab.c.
References dest, SYM::hashlk, SYM::nmptr, scope, SYM::scope, src, stb, and SYM::symlk.
Referenced by semant1().
dbg_symdentry()
void dbg_symdentry (int sptr)
...
Definition at line 3216 of file symtab.c.
References sptr, and symdentry().
dmp_socs()
void dmp_socs (int sptr, FILE * file)
...
Definition at line 1695 of file symtab.c.
References SOC::base, p, q, soc, SOC_NEXT, SOC_SPTR, sptr, and SYMNAME.
Referenced by symdentry().
dup_sym()
void dup_sym (int new, SYM * content)
replace contents of a symbol with values defining every field while ensuring values necessary for the hashing function are saved and restored.
Definition at line 2820 of file symtab.c.
References scope, and stb.
Referenced by gen_allocatable_result(), gen_array_result(), gen_pointer_result(), insert_dup_sym(), instantiate_interface(), reloc_byvalue_parameters(), and resolveBind().
find_explicit_interface()
SPTR find_explicit_interface (SPTR s)
return the symbol of the explicit interface of the ST_PROC
Definition at line 2861 of file symtab.c.
References s, and sptr.
Referenced by instantiate_interface(), semant1(), and sym_in_scope().
generate_type_mismatch_errors()
static void generate_type_mismatch_errors (SPTR s1, SPTR s2) static
Emit variable type mismatch errors for either subprogram argument variables or function return type based on separate module subprogram's definition vs. its declaration.
Definition at line 3498 of file symtab.c.
References ERR_Severe, error(), gbl, NULL, and SYMNAME.
Referenced by compatible_characteristics().
get_acon()
SPTR get_acon (SPTR sym, ISZ_T off)
...
Definition at line 601 of file symtab.c.
References DT_CPTR, get_acon3(), and off.
Referenced by ad_acon(), ad_aconi(), ad_aconk(), addarth(), cngcon(), exp_ac(), exp_type_bound_proc_call(), getstrconst(), ll_make_kmpc_fork_call(), and ll_make_kmpc_fork_teams().
get_acon3()
SPTR get_acon3 (SPTR sym, ISZ_T off, DTYPE dtype)
...
Definition at line 611 of file symtab.c.
References ACONOFFG, ACONOFFP, ADDSYM, bgitoi64(), HASH_CON, STB::hashtb, off, sptr, stb, and value().
Referenced by get_acon(), redundantLdLdElim(), widenProcessDirectLoad(), and widenProcessIndirectLoad().
get_ancestor_module()
SPTR get_ancestor_module (SPTR mod)
If mod is a submodule, return the module it is a submodule of. If it's a module, return mod. Otherwise 0.
Definition at line 2846 of file symtab.c.
References parent.
get_ieee_arith_intrin()
int get_ieee_arith_intrin (const char * nm)
Definition at line 428 of file symtab.c.
References i, and SYMNAME.
Referenced by add_predefined_ieeearith_module(), and export_ieee_arith_libraries().
get_int_cval()
INT get_int_cval (int con)
Retrieve the value of an integer constant symbol table entry and return as an 'INT'. Coerce TY_INT8 values if necessary.
Definition at line 674 of file symtab.c.
References assert, CONVAL2G, DT_ISINT, DT_ISLOG, DTY, res, TY_INT8, and TY_LOG8.
Referenced by _index(), _PDbound(), _PDsize(), _pghpf_bound(), _pghpf_size(), _repeat(), _reshape(), _RTE_ba(), _RTE_bound(), _RTE_size(), _RTE_xb(), _scan(), _verify(), check_dim_error(), check_subscript(), check_value(), chk_evar(), cmpat_arr_arg(), cmpat_dtype_with_size(), conformable(), const_eval(), conv_forall(), convert_template_instance(), dinit_data(), dinit_eval(), dump_ind(), eliminate_shift(), eval_init_op(), eval_sb(), eval_sub_index(), fill_cyclic_1(), fill_cyclic_k(), find_base(), generate_hcycliclp(), generate_hlocalizebnds(), get_isz_cval(), import(), increase_shape(), inline_reduction_f90(), inline_shifts(), inline_spread_shifts(), is_same_descr_for_bnds(), is_same_mask(), leave_arg(), lower_stmt(), mk_array_type(), mk_reshape_intrin(), mk_size(), mk_ulbound_intrin(), nml_emit_desc(), reduc_shape(), ref_pd(), rewrite_func_ast(), same_dtype(), semant1(), semant2(), semant3(), set_kind_result(), and string_expr_length().
get_isz_cval()
ISZ_T get_isz_cval (int con)
...
Definition at line 650 of file symtab.c.
References assert, CONVAL2G, DT_ISINT, DT_ISLOG, get_int_cval(), INT64_2_ISZ, ISZ_T, num, size_of(), and XBIT.
Referenced by ad_val_of(), arrayref_size(), ast_cval(), compute_sdsc_subscr(), compute_size_ast(), compute_size_expr(), conform_shape(), create_array_subscr(), DBGcnst(), decl_private_sym(), dinit_data(), eval(), exp_fstring(), exp_smp(), get_ival(), init_fold_const(), inlarr(), lbound_of_shape(), ref_pd(), semant1(), set_assumed_bounds(), small_enough(), and ubound_of_shape().
getccssym()
int getccssym (const char * pfx, int n, int stype)
create (or possibly reuse) a compiler created symbol whose name is of the form . "pfx" dddd where dddd is the decimal representation of n and "pfx" is the prefix specified in the pfx argument.
Definition at line 1852 of file symtab.c.
References STB::curr_scope, getsymbol(), i, IPA_RECOMPILATION_SUFFIX, n, name, sptr, stb, strlen(), and suffix.
Referenced by createUplevelSptr(), enter_lexical_block(), getccssym_sc(), and mp_create_bscope().
getccssym_sc()
int getccssym_sc (const char * pfx, int n, int stype, int sc)
similar to getccssym, but storage class is an argument. Calls getccssym if the storage class is not private; if private, a 'p' is appended to the name.
Definition at line 1883 of file symtab.c.
References STB::curr_scope, getccssym(), getsymf(), i, IPA_RECOMPILATION_SUFFIX, n, sptr, and stb.
Referenced by collapse_expr(), do_distbegin(), dotemp(), get_collapse_temp(), get_dtype_init_template(), lower_do_stmt(), and mkrtemp_arg1_sc().
getccsym()
int getccsym (int letter, int n, SYMTYPE stype)
create (or possibly reuse) a compiler created symbol whose name is of the form . 'letter' dddd where dddd is the decimal representation of n and 'letter' is the character specified in the letter argument.
Definition at line 1726 of file symtab.c.
References STB::curr_scope, getsymbol(), i, IPA_RECOMPILATION_SUFFIX, n, name, sptr, stb, and suffix.
Referenced by _constructf90(), add_private_allocatable(), allochartmp(), begin_entry(), check_alloc_ptr_type(), check_pointer_type(), create_display_temp_arg(), create_llvm_display_temp(), create_ref(), exp_header(), exp_misc(), fill_midnum(), get_atmp(), get_stblk_uplevel_sptr(), getccsym_sc(), getchartmp(), getdumlen(), gethost_dumlen(), getNewWideSym(), increase_shape(), llvmAddConcurEntryBlk(), mk_argasym(), mk_swlist(), mk_swtab(), mk_swtab_ll(), mkarglist(), mklvalue(), pp_entries(), pp_entries_mixedstrlen(), reduc_shape(), ref_based_object_sc(), ref_pd(), semant1(), and semant3().
getccsym_sc()
int getccsym_sc (int letter, int n, int stype, int sc)
similar to getccsym, but storage class is an argument. Calls getccsym if the storage class is not private; if private, a 'p' is appended to the name.
Definition at line 1812 of file symtab.c.
References STB::curr_scope, getccsym(), getsymbol(), i, IPA_RECOMPILATION_SUFFIX, n, name, sptr, stb, and suffix.
Referenced by add_class_arg_descr_arg(), exp_type_bound_proc_call(), gen_kind_parm_assignments(), gen_poly_element_arg(), get_unl_poly_sym(), initFinalSub(), is_intrinsic_opr(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), lower_scalar_temp(), mkrtemp_cpx_sc(), mkrtemp_sc(), and transform_call().
getcctmp()
int getcctmp (int letter, int n, int stype, int dtype)
Create a local compiler-created symbol - calls getcctmp_sc with the storage class SC_LOCAL.
Definition at line 1964 of file symtab.c.
References block_local_sym(), SEM::block_scope, getcctmp_sc(), n, sem, and sptr.
Referenced by ch_substring(), dinit_name(), get_arr_const(), mk_bnd_ast(), mk_shared_bnd_ast(), and put_name().
getcctmp_sc()
int getcctmp_sc (int letter, int n, int stype, int dtype, int sc)
create (or possibly reuse) a compiler created symbol whose name is of the form z_'letter'_'d' where 'd' is the decimal representation of n. If the storage class is private, 'p' is appended to the name.
Definition at line 1917 of file symtab.c.
References assert, CUDA_DEVICE, CUDA_GLOBAL, CUDAG, STB::curr_scope, DTY, gbl, getsymf(), i, IPA_RECOMPILATION_SUFFIX, n, sptr, and stb.
Referenced by _constructf90(), addssassignments(), chk_var(), func_call2(), gen_and_assoc_tmp_ptr(), gen_dtio_arglist(), gen_dtio_args(), gen_dtsfmt_args(), gen_spec_item_tmp(), gen_vlist(), get_invoking_proc_desc(), getcctmp(), mkarg(), mklabelvar(), ref_pd(), rewrite_allocatable_assignment(), semant3(), semantio(), temp_type_descriptor(), and transform_call().
getcon()
SPTR getcon (INT * value, DTYPE dtype)
Enter constant of given dtype and value into the symbol table and return pointer to it.
...
If an entry for the constant already exists, return pointer to the existing entry instead.
Definition at line 524 of file symtab.c.
References ADDSYM, CONVAL2G, CONVAL2P, DTY, HASH_CON, STB::hashtb, sptr, stb, TY_QUAD, and value().
Referenced by _adjustl(), _adjustr(), _dinit_acl(), _huge(), _make_mp_get_threadprivate(), _makezero(), _rd_token(), _repeat(), _trim(), _xtok(), ad_icon(), ad_kcon(), ad_kconi(), add_fp_constants(), addarth(), addili(), addother(), binop(), call_dtsfmt(), ch_substring(), check_ccon(), cngcon(), const_fold(), conv_int8_ilm(), convert_cnst(), copyLastItr(), create_threadprivate_dtype(), dinit_val(), do_dot(), do_reduction(), eval_abs(), eval_ceiling(), eval_do(), eval_floor(), eval_ishft(), eval_mod(), eval_scale(), eval_sqrt(), exp_ac(), exp_fstring(), exp_mac(), form_cmplx_const(), gen_abs_expr(), gen_binary_expr(), gen_dtio_args(), gen_extract_insert(), gen_llvm_expr(), gen_null_arg(), genNullArg(), get_bnd_con(), get_default_int_val(), get_kind_id(), get_len_parm_by_number(), get_mp_bind_type(), get_nondec(), get_number(), get_prefixed_int(), gethollerith(), ICON(), import_constant(), import_ptr_constant(), import_symbol(), init_fold_const(), init_negate_const(), log_negation(), lower_data_stmts(), lower_getintcon(), lower_getiszcon(), lower_getlogcon(), lower_getnull(), lower_getrealcon(), makeCopyprivArray(), mk_cval(), mk_cval1(), mk_isz_cval(), mk_smallest_val(), mkexpr1(), mkvarref(), mmul(), negate_const(), negate_const_be(), put_data(), read_symbol(), red_kadd(), ref_intrin(), ref_pd(), replace_by_zero(), replace_parms(), semant1(), semant2(), storechartmp(), sym_init(), transfer_load(), transform_ptr(), and write_operand().
gethollerith()
int gethollerith (int strcon, int kind)
Create a 'kinded' hollerith constant from a string constant and return the pointer to it. If the constant is already in the table, return pointer to the existing entry. Possible kind values are: 'h' - left justifed, blank filled. 'l' - left justfied, zero filled. 'r' - right justfied, zero filled.
Definition at line 789 of file symtab.c.
References getcon(), kind, sptr, and val.
Referenced by _rd_token(), and crunch().
getlab()
int getlab (void)
...
return a compiler-created label – user labels begin with '.', compiler- created labels begin with ''. Compiler-created labels will be mapped to fortran 77 labels by astout.
Definition at line 2048 of file symtab.c.
References assert, getsymf(), STB::lbavail, stb, and TRUE.
Referenced by _exp_mp_atomic_update(), add_loop_preheader(), add_single_loop_exit(), addCopyinInplace(), bblock(), do_end(), end_or_err(), enter_lexical_block(), exit_lexical_block(), exp_agoto(), exp_end(), exp_smp(), gen_call_expr(), genswitch(), import_symbol(), insert_begin_scope_label(), insert_end_scope_label(), insert_jump_entry_instr(), lower_lab(), make_stmt(), makeCopyprivArray_tls(), mkbranch(), remove_returns(), semant1(), semant3(), and semsmp().
getnewccsym()
int getnewccsym (int letter, int n, int stype)
create (never reuse) a compiler created symbol whose name is of the form . 'letter' dddd where dddd is the decimal representation of n and 'letter' is the character specified in the letter argument.
Definition at line 1757 of file symtab.c.
References gbl, n, name, NEWSYM, putsname(), sptr, and strlen().
Referenced by _sect(), exp_smp(), getPrivateTemp(), ll_create_task_sptr(), ll_set_new_threadprivate(), makeCopyprivArray(), and mkatomictemp().
getnewccsym2()
static int getnewccsym2 (char * name, int n, int stype) static
create (never reuse) a compiler created symbol whose name is of the form .
Definition at line 1778 of file symtab.c.
References gbl, name, NEWSYM, putsname(), sptr, and strlen().
Referenced by getnewccsymf().
getnewccsymf()
int getnewccsymf (int stype, const char * fmt, ...)
Definition at line 1793 of file symtab.c.
References getnewccsym2(), and MAXIDLEN.
Referenced by _sect(), and symvalue().
getprint()
const char * getprint (int sptr)
...
Parameters
sptr symbol table pointer
Definition at line 944 of file symtab.c.
References __log_print(), b, c, CONVAL2G, cprintf(), DTY, end, FLANG_FALLTHROUGH, interr(), len, STB::n_base, NEW, NULL, num, sptr, stb, string_length(), SYMNAME, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, and ui64toax().
Referenced by __print_nme(), _dump_one_ast(), _dumpilmtree(), _dumponeilm(), assn_static_off(), assn_stkoff(), bld_lhs(), bld_use(), can_copy_def(), const_prop(), def_ok(), delete_stores(), dsym(), dump_buff(), dump_cand(), dump_flowgraph(), dump_global(), dump_ind(), dump_loops(), dump_one_block(), dump_vinduc(), DumpnameHelper(), dumpsingleilm(), find_bivs(), findloop(), flow(), flowgraph(), function_init(), gen_address_operand(), get_loop_count(), getast(), getdtype(), ind_loop_init(), lower_end_contains(), lower_symbol(), lower_symbols(), malformed(), new_ivs(), only_one_ud(), parmprint(), plower(), prettytoken(), process_sptr_offset(), prsym(), prtsst(), putnme(), putpair(), putsym(), reg_assign1(), removest(), semantio(), single_ud(), sym_is_refd(), and symdentry().
getstring()
int getstring (const char * value, int length)
Enter character constant into symbol table and return pointer to it.
Enter character constant into symbol table.
Parameters
value character string value
length length of character string
If the constant is already in the table, return pointer to the existing entry instead.
Definition at line 724 of file symtab.c.
References ADDSYM, CONVAL2G, DTY, get_type(), HASH_STR, STB::hashtb, i, length(), mk_cval(), STB::n_base, p, putsname(), sptr, stb, TY_CHAR, and value().
Referenced by _adjustl(), _adjustr(), _get_token(), _makezero(), _rd_token(), _repeat(), _trim(), binop(), ch_substring(), chkcon(), cngcon(), crunch(), dinit_name(), dinit_val(), eval_adjustl(), eval_adjustr(), eval_init_op(), eval_repeat(), eval_trim(), fill_name(), gen_contig_check(), gen_dtio_arglist(), get_cstring(), get_fmtstr(), getstrconst(), hex2char(), hex2nchar(), import_constant(), lower_add_pghpf_commons(), lower_check_subscript(), mkvarref(), mod_add_subprogram(), process_bind(), put_name(), read_init(), read_symbol(), ref_intrin(), ref_pd(), semant1(), semant3(), semantio(), and transfer_load().
getsym()
int getsym (const char * name, int olength)
Enter symbol with indicated name into symbol table, initialize the new entry.
...
Parameters
name symbol name
olength number of characters in the symbol name
Returns
pointer to new symbol
If there is already such a symbol, just return pointer to the existing symbol table entry.
Definition at line 460 of file symtab.c.
References STB::curr_scope, gbl, insert_sym(), installsym, name, setimplicit(), sptr, and stb.
Referenced by _rd_token(), defer_arg_chk(), exp_misc(), get_kind_id(), getsymbol(), iface_intrinsic(), label_name(), make_new_funcsptr(), newsym(), read_symbol(), and semant1().
getsymbol()
int getsymbol (const char * name)
...
Definition at line 445 of file symtab.c.
References getsym(), name, and strlen().
Referenced by __gen_conditional_dealloc(), _do_iface(), assn_sclrtemp(), ast_ioret(), at_local_mode(), bblock(), check_defined_io2(), decl_private_sym(), declare_type(), dummy_program(), enter_local_mode(), exit_local_mode(), fixup_nme(), gen_allocated_check(), gen_automatic_reallocation(), gen_conditional_alloc(), gen_fcn_sst(), gen_finalized_result(), gen_newer_intrin(), get_byval_local(), get_fmt_array(), get_intrinsic_oprsym(), get_iso_ptrtype(), get_next_sym(), get_next_sym_dt(), get_param_alias_var(), get_private_size(), get_stack_size(), getccssym(), getccsym(), getccsym_sc(), getsymf(), import(), import_mk_newsym(), import_symbol(), initFinalSub(), is_overlap_cmblk_var(), ll_make_ftn_outlined_params(), ll_make_kmpc_proto(), ll_make_kmpc_struct_type(), lldbg_create_deferred_len_string_type_mdnode(), llGetSym(), llMakeFtnOutlinedSignature(), makeOutlinedFunc(), mk_external_var(), mk_impsym(), mk_shared_list(), mk_struct_for_llvm_init(), mkfunc(), process_blockaddr_sptr(), ref_entry(), ref_pd(), resolve_defined_io(), resolveBind(), resolveImp(), restore_internal_subprograms(), rewrite_cmplxpart_rval(), semant1(), semant2(), semant3(), sym_init(), sym_mkfunc(), and tkn_alias_sym().
getsymf()
int getsymf (const char * fmt, ...)
Definition at line 500 of file symtab.c.
References getsymbol(), and MAXIDLEN.
Referenced by _read_token(), addToDtype(), chk_fmtid(), ff_get_label(), get_csect_sym(), get_stmt(), get_submod_sym(), get_tbp(), get_unl_poly_sym(), getccssym_sc(), getcctmp_sc(), getlab(), hlv_getvsym(), iface_intrinsic(), reloc_byvalue_parameters(), semant1(), semant3(), sym_get_sdescr(), and sym_init().
hashcon()
int hashcon (INT * value, int dtype, int sptr)
Definition at line 573 of file symtab.c.
References HASH_CON, STB::hashtb, sptr, stb, and value().
hpf_library_stat()
void hpf_library_stat (int * firstp, int * lastp, int stype)
Return the first & last sym pointers for the HPF_LIBRARY procedures. Initially, the stype of the HPF library procedures is ST_HL; when the USE statement is seen, the stype of these symbols is changed to ST_PD.
Definition at line 393 of file symtab.c.
References interr().
Referenced by change_predefineds().
implicit_int()
void implicit_int (int default_int)
simple routine to reset the default integer type for implicitly typing integer variables. Needed for compile-type processing of -i4/-noi4 options in OPTIONS statement.
Definition at line 347 of file symtab.c.
References dtimplicit, DTIMPL::dtype, FALSE, i, and DTIMPL::typ8.
Referenced by init_implicit(), and scan_options().
init_implicit()
void init_implicit (void)
Set up initial implicit types. All are real except for the letters i thru n:
Definition at line 321 of file symtab.c.
References DTIMPL::anyset, STB::dt_int, STB::dt_real, dtimplicit, DTIMPL::dtype, FALSE, flg, i, FLG::i4, implicit_int(), DTIMPL::set, stb, TRUE, DTIMPL::typ8, STB::user, and XBIT.
Referenced by semant1(), and sym_init().
insert_dup_sym()
int insert_dup_sym (int sptr)
\Brief Create a duplicate of this sym and return it
Definition at line 2835 of file symtab.c.
References dup_sym(), insert_sym(), sptr, and stb.
Referenced by create_parameterized_dt(), get_parameterized_dt(), instantiate_interface(), mod_add_subprogram(), and semant3().
insert_sym()
int insert_sym (int first)
create new symbol table entry and insert it in the hash list immediately in front of 'first':
Definition at line 1985 of file symtab.c.
References assert, STB::curr_scope, first, gbl, HASH_ID, STB::hashtb, i, j, NEWSYM, NOSYM, setimplicit(), sptr, stb, strlen(), and SYMNAME.
Referenced by apply_use(), begin_submodule(), block_local_sym(), chk_intrinsic(), create_func_entry(), create_var(), decl_private_sym(), decl_procedure_sym(), declare_type(), declref(), declsym(), declsym_newscope(), do_access(), find_outer_sym(), gen_accl_alias(), gen_finalized_result(), get_fmt_array(), get_fval_array(), getocsym(), getsym(), iface_arg(), import_mk_newsym(), import_symbol(), insert_dup_sym(), link_parents(), lower_prepare_symbols(), mklvalue(), newsym(), open_module(), record_func_result(), ref_entry(), ref_ident(), ref_ident_inscope(), ref_int_scalar(), ref_storage_inscope(), refsym(), refsym_inscope(), replace_variable(), resolveBind(), resolveImp(), restore_internal_subprograms(), semant1(), semant2(), and semant3().
insert_sym_first()
int insert_sym_first (int first)
create new symbol table entry and insert it in the hash list in front of the head of the list containing 'first':
Definition at line 2020 of file symtab.c.
References STB::curr_scope, first, gbl, HASH_ID, STB::hashtb, i, NEWSYM, NOSYM, setimplicit(), sptr, stb, strlen(), and SYMNAME.
Referenced by add_member_for_llvm(), construct_association(), and instantiate_interface().
instantiate_interface()
SPTR instantiate_interface (SPTR iface)
Instantiate a copy of a separate module subprogram's declared interface as part of the MODULE PROCEDURE's definition (i.e., implement what would have taken place had the subprogram been defined with a MODULE SUBROUTINE or MODULE FUNCTION with a compatible interface).
Definition at line 2884 of file symtab.c.
References AD_DPTR, arg, array_element_dtype(), aux, DEC_DEF_MAP::dec_sptr, DEC_DEF_MAP::def_sptr, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, DTY, dup_sym(), find_explicit_interface(), FREE, gbl, get_all_descriptors(), get_static_descriptor(), insert_dup_sym(), insert_sym_first(), j, mk_arrdsc(), NEED, NEW, NOSYM, stb, trans_mkdescr(), TRUE, and update_arrdsc().
Referenced by semant1().
is_arg_in_entry()
LOGICAL is_arg_in_entry (int ent, int arg)
determine if an argument is an argument to a given entry
Parameters
ent entry sptr
arg argument sptr
Definition at line 2294 of file symtab.c.
References arg, assert, aux, AUX::dpdsc_base, FALSE, i, and TRUE.
Referenced by handle_arguments(), and lower_data_stmts().
is_argp_in_entry()
LOGICAL is_argp_in_entry (int ent, int arg)
determine if an argument $p is an $p of argument to a given entry
Parameters
ent entry sptr
arg argument sptr
Definition at line 2317 of file symtab.c.
References arg, assert, aux, AUX::dpdsc_base, FALSE, i, sptr, and TRUE.
Referenced by lower_data_stmts().
is_procedure_ptr()
LOGICAL is_procedure_ptr (int sptr)
Definition at line 2350 of file symtab.c.
References FALSE, is_procedure_ptr_dtype(), NOSYM, resolve_sym_aliases(), and sptr.
Referenced by assign_pointer(), chk_pointer_target(), dinit_val(), do_access(), fix_proc_pointer_call(), fix_proc_ptr_dummy_args(), get_invoking_proc_desc(), get_static_descriptor(), handle_arguments(), handle_seq_section(), is_associatable_variable_sst(), is_data_ast(), is_desc_needed(), is_variable_ast(), lower_data_stmts(), lower_function(), lower_make_all_descriptors(), lower_stmt(), lower_symbols(), mkvarref(), needDebugInfoFilt(), newargs_for_entry(), proc_arginfo(), ptrfunc_call(), ptrsubr_call(), ref_intrin_subr(), ref_pd(), semant1(), semant2(), semant3(), sym_is_dinitd(), transform_call(), and update_proc_ptr_dtype_from_interface().
is_used_by_submod()
bool is_used_by_submod (SPTR sym1, SPTR sym2)
Used for check whether sym2 used inside the scope of sym1 is defined in parent modules (SCOPEG(sym2)) and used by inherited submodules ENCLFUNCG(sym1).
Definition at line 3479 of file symtab.c.
Referenced by set_assn(), and sym_in_scope().
iso_c_lib_stat()
void iso_c_lib_stat (int * firstp, int * lastp, int stype)
Return the first & last sym pointers for the ISO_C intrinsic procedures. Initially, the stype of the ISO_C library procedures is ST_ISOC when the USE statement is seen, the stype of these symbols is changed to ST_INTRIN
Definition at line 413 of file symtab.c.
References interr().
Referenced by add_isoc_intrinsics(), export_iso_c_libraries(), and open_module().
mangle_name()
char * mangle_name (const char * basename, const char * purpose)
create a distinct mangled name
Definition at line 3045 of file symtab.c.
References assert, STB::curr_scope, flg, HASH_ID, STB::hashtb, i, j, length(), manglecount, MAXIDLEN, name, sptr, FLG::standard, STANDARD_MAXIDLEN, stb, strlen(), and SYMNAME.
Referenced by get_next_sym(), and get_param_alias_var().
mangle_name_dt()
char * mangle_name_dt (const char * basename, const char * purpose, int encldtype)
same as mangle_name, except only clash for members of the same derived type
Definition at line 3108 of file symtab.c.
References assert, flg, HASH_ID, STB::hashtb, i, j, length(), MAXIDLEN, name, sptr, FLG::standard, STANDARD_MAXIDLEN, stb, strlen(), and SYMNAME.
Referenced by get_next_sym_dt().
map_initsym()
int map_initsym (int oldsym, int old_firstosym)
Determine if oldsym, read from a .mod file, is a predefined (intrinsic, predeclared, constant, etc.).
If it is, attempt to map the oldsym to the current set of predefineds; note that oldsym could also be from the current set. The value of old_firstosym indicates to which set, current or older, oldsym belongs.
Definition at line 3402 of file symtab.c.
References STB::firstosym, interr(), NXTRA, and stb.
Referenced by new_symbol(), new_symbol_and_link(), and new_symbol_if_module().
mk_coercion_func()
int mk_coercion_func (int dtype)
Create a coercion function based on the data type.
Definition at line 2231 of file symtab.c.
References mk_coercion_func_name(), sptr, and sym_mkfunc_nodesc().
Referenced by ref_pd().
mk_coercion_func_name()
const char * mk_coercion_func_name (int dtype)
create a coercion function based on the data type.
Definition at line 2173 of file symtab.c.
References DTY, interr(), mkRteRtnNm(), RTE_cmplx16, RTE_cmplx32, RTE_cmplx8, RTE_int1, RTE_int2, RTE_int4, RTE_int8, RTE_log1, RTE_log2, RTE_log4, RTE_log8, RTE_no_rtn, RTE_real16, RTE_real4, RTE_real8, TY_BINT, TY_BLOG, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_QUAD, TY_REAL, TY_SINT, and TY_SLOG.
Referenced by lower_intrinsic(), and mk_coercion_func().
mk_external_var()
int mk_external_var (char * name, int dtype)
create an external variable given a name and its data type. A common block of the same name is created and its member is the variable. If the variable already exists, just return it.
Definition at line 2245 of file symtab.c.
References assert, CMEMLP, DTY, gbl, getsymbol(), name, NOSYM, pop_sym(), and sptr.
mkfunc()
SPTR mkfunc (const char * nmptr)
...
create a function ST item given a name
Definition at line 2157 of file symtab.c.
References DT_INT, getsymbol(), and sptr.
Referenced by allochartmp(), begin_entry(), cr_block(), efunc(), exp_ac(), exp_alloca(), exp_end(), exp_qjsr(), exp_restore_mxcsr(), exp_smp(), exp_strcpy(), exp_strx(), exp_szero(), exp_zqjsr(), ll_make_atomic_compare_xchg(), ll_make_atomic_load(), ll_make_atomic_store(), makeCall(), mkfunc_cncall(), mkfunc_sflags(), and mkMemcpy().
newimplicit()
void newimplicit (int firstc, int lastc, int dtype)
Change the current settings for implicit variable types and character lengths.
Parameters
firstc characters delimiting range
lastc new value assigned to range
dtype data type
Definition at line 810 of file symtab.c.
References DTIMPL::anyset, assert, CNULL, dtimplicit, DTIMPL::dtype, error(), FALSE, gbl, i, IMPL_INDEX, j, DTIMPL::set, set, TRUE, and DTIMPL::typ8.
Referenced by semant1().
newimplicitnone()
void newimplicitnone (void)
Definition at line 839 of file symtab.c.
References DTIMPL::anyset, dtimplicit, FALSE, and i.
Referenced by semant1().
parmprint()
const char * parmprint (int sptr)
Return ptr to printable representation of the indicated PARAMETER.
...
Parameters
sptr symbol table pointer
Definition at line 892 of file symtab.c.
References buf, CONVAL2G, CONVAL2P, DT_INT, DT_LOG, DTY, getprint(), sptr, TY_BINT, TY_HOLL, TY_ISWORD, TY_SINT, and TY_WORD.
Referenced by putentry(), and symdentry().
pop_sym()
void pop_sym (int sptr)
remove a symbol from its hash list
...
Definition at line 2101 of file symtab.c.
References DBGBIT, gbl, HASH_ID, STB::hashtb, j, name, s, sptr, stb, strlen(), and SYMNAME.
Referenced by add_predefined_ieeearith_module(), add_predefined_iso_fortran_env_module(), add_predefined_isoc_module(), clear_no_scope_sptr(), create_func_entry(), decl_procedure_sym(), declsym(), do_end(), end_association(), fill_links_symbol(), get_fval_array(), get_retval_derived_type(), gethost_dumlen(), iface_arg(), mk_external_var(), pop_scope_level(), pop_subprogram(), record_func_result(), ref_entry(), semant1(), and semant3().
proc_arginfo()
void proc_arginfo (int sptr, int * paramct, int * dpdsc, int * iface)
Definition at line 2367 of file symtab.c.
References assert, DTY, get_implementation(), get_specific_member(), is_procedure_ptr(), IS_TBP, mem(), and sptr.
Referenced by _rewrite_scalar_fuctions(), add_ptr_assign(), assign_pointer(), bld_ud(), check_defined_io2(), chk_arguments(), cmp_interfaces(), cmp_interfaces_strict(), elemental_func_call(), extract_shape_from_args(), find_byval_ref(), fix_proc_pointer_call(), fix_proc_ptr_dummy_args(), gen_automatic_reallocation(), get_generic_member2(), get_tbp_argno(), handle_seq_section(), initFinalSub(), is_desc_needed(), is_ptrast_arg(), is_seq_dummy(), needs_type_in_descr(), ptrfunc_call(), ptrsubr_call(), pure_func_call(), put_call(), resolveImp(), resolvePass(), rewrite_sub_args(), semant1(), semant2(), semant3(), semCheckTbp(), string_expr_length(), transform_call(), update_proc_ptr_dtype_from_interface(), and valid_assign_pointer_types().
push_sym()
void push_sym (int sptr)
push a symbol onto a hash list
Definition at line 2137 of file symtab.c.
References DBGBIT, gbl, HASH_ID, STB::hashtb, name, sptr, stb, strlen(), and SYMNAME.
Referenced by declsym(), and semant3().
reinit_sym()
void reinit_sym (int sptr)
reinitialize a symbol
Definition at line 3015 of file symtab.c.
References BZERO, scope, sptr, and stb.
Referenced by semant1().
resolve_sym_aliases()
int resolve_sym_aliases (int sptr)
Definition at line 2341 of file symtab.c.
References NOSYM, and sptr.
Referenced by compat_arg_lists(), is_procedure_ptr(), semant1(), and semant3().
restore_implicit()
void restore_implicit (void)
Definition at line 378 of file symtab.c.
References BCOPY, dtimplicit, dtimplicitstack, interr(), and save_dtimplicit.
Referenced by restore_host(), and semant_init().
rw_sym_state()
void rw_sym_state (RW_ROUTINE , RW_FILE)
Definition at line 3222 of file symtab.c.
References AUX::arrdsc_avl, AUX::arrdsc_base, aux, SOC::avail, SOC::base, AUX::dpdsc_avl, AUX::dpdsc_base, STB::firstusym, gbl, STB::hashtb, ISREAD, STB::lbavail, AUX::list, STB::n_base, STB::namavl, NEED, NEW, AUX::nml_avl, AUX::nml_base, RW_FD, RW_SCALAR, SOC::size, soc, stb, AUX::symi_avl, and AUX::symi_base.
Referenced by rw_host_state().
same_sym_list()
LOGICAL same_sym_list (int list1, int list2)
Return TRUE if these two symi lists have the same sptrs in the same order.
Definition at line 2083 of file symtab.c.
References FALSE, SYMI_NEXT, and SYMI_SPTR.
Referenced by already_to_be_used(), export_public_module(), and find_use_node_in_list().
save_implicit()
void save_implicit (LOGICAL reset)
Definition at line 357 of file symtab.c.
References BCOPY, BZERO, dtimplicit, dtimplicitsize, dtimplicitstack, FALSE, i, NEED, NEW, NULL, reset, save_dtimplicit, and DTIMPL::set.
Referenced by begin_contains(), restore_host(), save_host(), and semant_init().
save_uname()
void save_uname (int newsptr, INT oldnmptr)
can be called after name mangling if the original name needs to be saved in the symbol table, (for instance, for debug symbols.)
Definition at line 3162 of file symtab.c.
References assert, interr(), STB::namavl, and stb.
setimplicit()
void setimplicit (int sptr)
...
assign to the indicated symbol table entry, the current implicit dtype.
Definition at line 853 of file symtab.c.
References dtimplicit, i, IMPL_INDEX, sptr, and SYMNAME.
Referenced by find_outer_sym(), gen_fcn_sst(), getsym(), insert_sym(), insert_sym_first(), mklvalue(), mod_add_subprogram(), rewrite_cmplxpart_rval(), semant1(), semant2(), semant3(), and tkr_match().
sign_extend()
INT sign_extend (INT val, int width)
...
Sign extend an integer value of an indicated width (8, 16, 32); value returned is sign extended with respect to the host's int type.
Definition at line 702 of file symtab.c.
References val, and w.
Referenced by cngcon(), and convert_cnst().
sym_in_sym_list()
LOGICAL sym_in_sym_list (int sptr, int list)
Return TRUE if sptr is in symi list represented by list.
Definition at line 2069 of file symtab.c.
References FALSE, list, sptr, SYMI_NEXT, SYMI_SPTR, and TRUE.
Referenced by check_doconcurrent_ast(), copy_specifics(), find_in_host(), is_except_in_scope(), is_private_in_scope(), rhs_expr_idx_dependent(), semant3(), sym_in_scope(), and test_scope().
sym_init()
void sym_init (void)
...
Initialize symbol table for new user program unit.
Definition at line 72 of file symtab.c.
References add_fp_constants(), AUX::arrdsc_avl, AUX::arrdsc_base, AUX::arrdsc_size, assert, aux, SOC::avail, BCOPY, cng_inttyp(), CONVAL2G, AUX::curr_entry, STB::dbl0, STB::dblm0, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, STB::dt, STB::dt_cmplx, DT_CMPLX, DT_DBLE, DT_DCMPLX, STB::dt_int, DT_INT, STB::dt_log, DT_LOG, DT_PTR, STB::dt_real, DT_REAL, dtimplicitstack, DTY, AUX::dvl_avl, AUX::dvl_base, AUX::dvl_size, STB::firstosym, STB::firstusym, flg, STB::flt0, STB::fltm0, gbl, getcon(), getsymbol(), getsymf(), HASHSIZE, STB::hashtb, i, STB::i0, STB::i1, if(), init_chartab(), init_implicit(), INT, intast_sym, FLG::ipa, STB::k0, STB::k1, STB::lbavail, NMLDSC::lineno, AUX::list, llmp_reset_uplevel(), STB::n_base, STB::n_size, STB::namavl, NEW, NMLDSC::next, SYMI::next, AUX::nml_avl, AUX::nml_base, AUX::nml_size, NOSYM, onlyentry, res, SYMUTL::sc, soc, sptr, NMLDSC::sptr, SYMI::sptr, stb, STG_NEXT_SIZE, STG_RESET, sym_init_first(), AUX::symi_avl, AUX::symi_base, AUX::symi_size, symutl, tmp, STB::user, XBIT, xdneg(), and xfneg().
Referenced by datastructure_reinit(), init(), and reinit().
sym_strsave()
char * sym_strsave (const char * s)
Definition at line 3028 of file symtab.c.
References i, NEW, p, s, and strlen().
Referenced by sym_get_arg_sec(), sym_get_sec(), and trans_mkdescr().
symdentry()
void symdentry (FILE * file, int sptr)
...
Parameters
file the file
sptr symbol currently being dumped
Definition at line 1093 of file symtab.c.
References _PFG, AD_DPTR, AD_LWBD, AD_NUMDIM, AD_UPBD, aux, buff, CMEMLG, CONVAL2G, DBGBIT, DEFLABG, DLL_EXPORT, DLL_IMPORT, DLLG, dmp_socs(), AUX::dpdsc_base, DTY, ENDLINEG, FILE, FUNCLINEG, getast(), getdtype(), getprint(), GREALG, GSAMEG, i, IGNORE_C, IGNORE_D, IGNORE_K, IGNORE_M, IGNORE_R, IGNORE_T, ILMG, INTENT_IN, INTENT_OUT, INTENTG, interr(), ISZ_PF, line, STB::n_base, NML_NEXT, NML_SPTR, p, PARAMVALG, parmprint(), PDALN_IS_DEFAULT, PDALNG, STB::scnames, SFDSCG, sptr, stb, strlen(), STB::stypes, SYMI_NEXT, SYMI_SPTR, SYMNAME, and TY_ISWORD.
Referenced by dbg_symdentry(), lower_symbol(), putsclass(), putstype(), and symdmp().
symdmp()
void symdmp (FILE * dfil, LOGICAL full)
dump symbol table for debugging purposes. If full == TRUE, dump entire symbol table, otherwise dump symtab beginning with user symbols.
Definition at line 1686 of file symtab.c.
References STB::firstusym, full, sptr, stb, and symdentry().
Referenced by dbg_dump(), dump_old_symbols(), export(), import(), import_inline(), lower(), process_input(), and upper().
symtab_fini()
void symtab_fini (void)
Compilation is finished - deallocate storage, close files, etc.
Definition at line 3271 of file symtab.c.
References AUX::arrdsc_avl, AUX::arrdsc_base, AUX::arrdsc_size, aux, SOC::avail, SOC::base, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, STB::dt, dtimplicitsize, dtimplicitstack, AUX::dvl_avl, AUX::dvl_base, AUX::dvl_size, fini_chartab(), FREE, STB::n_base, STB::n_size, AUX::nml_avl, AUX::nml_base, AUX::nml_size, save_dtimplicit, SOC::size, soc, stb, STG_DELETE, AUX::symi_avl, AUX::symi_base, AUX::symi_size, STB::w_base, and STB::w_size.
Referenced by finish().
symtab_nostandard()
void symtab_nostandard (void)
call this when -nostandard is set; undo what symtab_standard does
Definition at line 3328 of file symtab.c.
References dttypes, TY_BLOG, TY_LOG, TY_LOG8, and TY_SLOG.
Referenced by scan_options().
symtab_standard()
void symtab_standard (void)
call this when -standard is set
Definition at line 3315 of file symtab.c.
References dttypes, TY_BLOG, TY_LOG, TY_LOG8, and TY_SLOG.
Referenced by scan_options().
update_arrdsc()
static void update_arrdsc (SPTR s, DEC_DEF_MAP * smap, int num_dummies) static
Update array bound AST SPTRs (old_sptr) using newly created SPTRs (new_sptr) by referring to DEC_DEF_MAP. The DEC_DEF_MAP is a struct which contains mapping info from the old_sptr to new_sptr.
Definition at line 2987 of file symtab.c.
References AD_DEFER, AD_DPTR, AD_LWAST, AD_LWBD, AD_NUMDIM, AD_UPAST, AD_UPBD, SEM::arrdim, SEM::bounds, i, j, mk_id(), s, and sem.
Referenced by instantiate_interface().
was_implicit()
LOGICAL was_implicit (int sptr)
Return FALSE if this symbol could not have been properly implicitly typed.
Definition at line 878 of file symtab.c.
References DTIMPL::anyset, dtimplicit, FALSE, i, IMPL_INDEX, SYMUTL::none_implicit, sptr, SYMNAME, symutl, and TRUE.
Referenced by CheckDecl().
Variable Documentation
dtimplicit
DTIMPL dtimplicit static
Definition at line 55 of file symtab.c.
Referenced by implicit_int(), init_implicit(), newimplicit(), newimplicitnone(), restore_implicit(), save_implicit(), setimplicit(), and was_implicit().
dtimplicitsize
int dtimplicitsize = 0 static
Definition at line 56 of file symtab.c.
Referenced by save_implicit(), and symtab_fini().
dtimplicitstack
int dtimplicitstack = 0 static
Definition at line 58 of file symtab.c.
Referenced by restore_implicit(), save_implicit(), sym_init(), and symtab_fini().
manglecount
int manglecount = 0 static
Definition at line 3039 of file symtab.c.
Referenced by mangle_name().
onlyentry
ENTRY onlyentry static
Definition at line 64 of file symtab.c.
Referenced by sym_init().
save_dtimplicit
DTIMPL* save_dtimplicit = NULL static
Definition at line 57 of file symtab.c.
Referenced by restore_implicit(), save_implicit(), and symtab_fini().