flang: symtab.cpp File Reference
symtab.cpp File Reference
Fortran symbol table access module.
#include "gbldefs.h"
#include "error.h"
#include "symtab.h"
#include "machar.h"
#include "symtabdf.h"
#include "syminidf.h"
#include "soc.h"
#include "llmputil.h"
#include "llutil.h"
#include "llassem.h"
#include "dtypeutl.h"
#include "symfun.h"
Macros
#define IMPL_INDEX(uc)
#define COPYFIELD(f) stb.stg_base[os].f = stb.stg_base[ns].f
#define COPYFIELD(f) stb.stg_base[os].f = stb.stg_base[ns].f
#define _PFG(cond, str)
Typedefs
typedef enum LLVMCallBack_t LLVMCallBack_t
Enumerations
enum LLVMCallBack_t { NO_LLVM_CALLBACK , LLVM_CALLBACK }
Functions
static void cng_generic (const char *, const char *)
static void cng_specific (const char *, const char *)
static void cng_inttyp (const char *, int)
static void clear_vc (void)
void sym_init (void)
Initialize symbol table for new user program unit.
void implicit_int (DTYPE default_int)
Simple routine to reset the default integer type for implicitly typing integer variables. Needed for compile-type processing of -i4/-noi4 options in OPTIONS statement.
SPTR getsymbol (const char *name)
Enter symbol with indicated name into symbol table, initialize the new entry, and return pointer to it. If there is already such a symbol, just return pointer to the existing symbol table entry.
SPTR getsym (const char *name, int olength)
Like getsymbol, but accepts a string that is not null-terminated.
SPTR getcon (INT *value, DTYPE dtype)
Enter constant of given dtype and value into the symbol table and return pointer to it. If an entry for the constant already exists, return pointer to the existing entry instead.
SPTR get_acon (SPTR sym, ISZ_T off)
...
SPTR get_acon3 (SPTR sym, ISZ_T off, DTYPE dtype)
...
SPTR get_vcon (INT *value, DTYPE dtype)
...
int get_vcon0 (DTYPE dtype)
Get a vector constant of a zero which suits the element type.
int get_vcon1 (DTYPE dtype)
...
int get_vconm0 (DTYPE dtype)
get a vector constant of a zero which suits the element type
SPTR get_vcon_scalar (INT sclr, DTYPE dtype)
...
ISZ_T get_isz_cval (int con)
...
INT sign_extend (INT val, int width)
Sign extend an integer value of an indicated width (8, 16, 32); value returned is sign extended with respect to the host's int type.
SPTR getstring (const char *value, int length)
Enter character constant into symbol table and return pointer to it.
SPTR getntstring (const char *value)
Similar to getstring except the character string is null terminated.
SPTR getstringaddr (SPTR sptr)
void newimplicit (int firstc, int lastc, DTYPE dtype)
Change settings for implicit variable types, character lengths.
void setimplicit (int sptr)
Assign to the indicated symbol table entry, the current implicit dtype.
void reapply_implicit (void)
Scan backwards in the symbol table to reapply the current implicit state to variables which have not been typed. Invoked when an implicit statement follows specification statements (usually a severe error) and the option -x 125 0x80 is specified.
const char * parmprint (int sptr)
Return ptr to printable representation of the indicated PARAMETER.
char * getprint (int sptr)
Return ptr to printable representation of the indicated symbol.
static void putaltname (FILE *, int, const char *)
static void putcuda (FILE *, int)
void symdentry (FILE *file, int sptr)
...
void symdmp (FILE *dfil, bool full)
Dump symbol table for debugging purposes. If full == true, dump entire symbol table, otherwise dump symtab beginning with user symbols.
void dmp_socs (int sptr, FILE *file)
...
static void set_ccflags (int sptr, SYMTYPE stype)
SPTR getccsym (char letter, int n, SYMTYPE stype)
create (or possibly reuse) a compiler created symbol whose name is of the form . <letter> dddd where dddd is the decimal representation of n.
SPTR getnewccsym (char letter, int n, SYMTYPE stype)
Create (never reuse) a compiler created symbol whose name is of the form . <letter> dddd where dddd is the decimal representation of n.
SPTR getccsym_sc (char letter, int n, SYMTYPE stype, SC_KIND sc)
Similar to getccsym, but storage class is an argument. Calls getccsym if the storage class is not private; if private, a 'p' is appended to the name.
SPTR getcctemp_sc (const char *name, SYMTYPE stype, SC_KIND sc)
Create (or possibly reuse) a compiler created temporary where the caller constructs the name and passes the storage class as an argument.
SPTR getccssym (const char *pfx, int n, SYMTYPE stype)
Create (or possibly reuse) a compiler created symbol whose name is of the form . <pfx> dddd where dddd is the decimal representation of n.
SPTR getccssym_sc (const char *pfx, int n, SYMTYPE stype, SC_KIND sc)
Similar to getccssym, but storage class is an argument. Calls getccssym if the storage class is not private; if private, a 'p' is appended to the name.
SPTR getccsym_copy (SPTR oldsptr)
...
SPTR insert_sym (SPTR first)
Create new symbol table entry and insert it in the hash list immediately in front of 'first':
SPTR insert_sym_first (SPTR first)
Create new symbol table entry and insert it in the hash list immediately in front of 'first':
SPTR getlab (void)
...
int get_entry_item (void)
...
void pop_scope (void)
Scan all hash lists and remove symbols whose scope is greater than or equal to the current scope:
void pop_sym (int sptr)
Scan all hash lists and remove specified symbol from scope.
SPTR mkfunc (const char *nmptr)
Create a function ST item given a name.
static SPTR vmk_prototype (LLVMCallBack_t llCallBack, const char *name, const char *attr, DTYPE resdt, int nargs, va_list vargs)
SPTR mk_prototype (const char *name, const char *attr, DTYPE resdt, int nargs,...)
Make a prototype but do not register it.
SPTR mk_prototype_llvm (const char *name, const char *attr, DTYPE resdt, int nargs,...)
Make a prototype and register it with LLVM.
int add_symitem (int sptr, int nxt)
...
int dbg_symdentry (int sptr)
...
SPTR get_semaphore (void)
...
int tr_conval2g (char *fn, int ln, int s)
...
int tr_conval2p (char *fn, int ln, int s, int v)
...
SPTR addnewsym (const char *name)
Add a new symbol with given name.
SPTR adddupsym (SPTR oldsptr)
Add a new symbol with same name as an existing symbol.
Variables
struct {
DTYPE dtype
bool set
} dtimplicit [26+26+2]
static ENTRY onlyentry
static int vc0 [TY_MAX+1][TY_VECT_MAXLEN]
static int vc1 [TY_MAX+1][TY_VECT_MAXLEN]
static int vcm0 [TY_MAX+1][TY_VECT_MAXLEN]
static int fltm0
static int dblm0
Detailed Description
Fortran symbol table access module.
FTN - symbol table access module. This module contains the routines used to initialize, update, access, and dump the symbol table. Note that in addition to being used by FTN, this module is used by the utility program, symini, which processes intrinsic and generic definitions in order to set up the initial symbol table for FTN.
Definition in file symtab.cpp.
Macro Definition Documentation
_PFG
#define _PFG (cond, str)
Value:
  if (cond)             \
  fprintf(dfil, "  %s", str)
Definition at line 1027 of file symtab.cpp.
COPYFIELD [1/2]
#define COPYFIELD (f) stb.stg_base[os].f = stb.stg_base[ns].f
COPYFIELD [2/2]
#define COPYFIELD (f) stb.stg_base[os].f = stb.stg_base[ns].f
IMPL_INDEX
#define IMPL_INDEX (uc)
Value:
  (islower(uc) ? uc - 'a'                       \
               : (isupper(uc) ? 26 + (uc - 'A') \
                              : (uc == '$' ? 52 : (uc == '_' ? 53 : -1))))
Definition at line 48 of file symtab.cpp.
Typedef Documentation
LLVMCallBack_t
typedef enum LLVMCallBack_t LLVMCallBack_t
Enumeration Type Documentation
LLVMCallBack_t
enum LLVMCallBack_t
Enumerator
NO_LLVM_CALLBACK
LLVM_CALLBACK
Definition at line 1945 of file symtab.cpp.
Function Documentation
add_symitem()
int add_symitem (int sptr, int nxt)
...
Definition at line 2027 of file symtab.cpp.
References aux, i, NEED, sptr, AUX::symi_avl, AUX::symi_base, SYMI_NEXT, AUX::symi_size, and SYMI_SPTR.
adddupsym()
SPTR adddupsym (SPTR oldsptr)
Add a new symbol with same name as an existing symbol.
Parameters
oldsptr symbol to duplicate
Definition at line 2116 of file symtab.cpp.
References NEWSYM, and sptr.
addnewsym()
SPTR addnewsym (const char * name)
Add a new symbol with given name.
Parameters
name the symbol's name
Definition at line 2107 of file symtab.cpp.
References name, NEWSYM, putsname(), sptr, and strlen().
Referenced by create_static_base(), get_entries_argnum(), and ll_make_kmpc_struct_type().
clear_vc()
static void clear_vc (void) static
Definition at line 496 of file symtab.cpp.
References BZERO, TY_VECT_MAXLEN, vc0, vc1, and vcm0.
Referenced by sym_init().
cng_generic()
static void cng_generic (const char * old, const char * New) static
Definition at line 219 of file symtab.cpp.
References assert, COPYFIELD, ERR_Severe, getsym(), and strlen().
Referenced by sym_init().
cng_inttyp()
static void cng_inttyp (const char * old, int dt) static
Definition at line 265 of file symtab.cpp.
References assert, dt, ERR_Severe, getsym(), ss, and strlen().
Referenced by sym_init().
cng_specific()
static void cng_specific (const char * old, const char * New) static
Definition at line 243 of file symtab.cpp.
References assert, COPYFIELD, ERR_Severe, getsym(), and strlen().
Referenced by sym_init().
dbg_symdentry()
int dbg_symdentry (int sptr)
...
Definition at line 2039 of file symtab.cpp.
References sptr, and symdentry().
dmp_socs()
void dmp_socs (int sptr, FILE * file)
...
Definition at line 1571 of file symtab.cpp.
References p, q, SOC_NEXT, SOC_SPTR, sptr, and SYMNAME.
Referenced by symdentry().
get_acon()
SPTR get_acon (SPTR sym, ISZ_T off)
...
Definition at line 390 of file symtab.cpp.
References DT_CPTR, get_acon3(), and off.
get_acon3()
SPTR get_acon3 (SPTR sym, ISZ_T off, DTYPE dtype)
...
Definition at line 399 of file symtab.cpp.
References ACONOFFG, ACONOFFP, ADDSYM, bgitoi64(), HASH_CON, STB::hashtb, off, sptr, stb, and value().
Referenced by get_acon().
get_entry_item()
int get_entry_item (void)
...
Definition at line 1835 of file symtab.cpp.
References aux, AUX::entry_avail, AUX::entry_base, AUX::entry_size, NEED, and NEW.
get_isz_cval()
ISZ_T get_isz_cval (int con)
...
Definition at line 644 of file symtab.cpp.
References assert, CONVAL2G, DT_ISINT, ERR_unused, INT64_2_ISZ, ISZ_T, num, and size_of().
get_semaphore()
SPTR get_semaphore (void)
...
Definition at line 2047 of file symtab.cpp.
References AD_DPTR, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_SCHECK, AD_UPBD, AD_ZBASE, dt, DT_INT, get_array_dtype(), getcon(), getsym(), STB::i1, name, and stb.
get_vcon()
SPTR get_vcon (INT * value, DTYPE dtype)
...
Definition at line 437 of file symtab.cpp.
References ADDSYM, aux, STB::dt, DTyVecLength, HASH_CON, STB::hashtb, i, n, NEED, sptr, stb, value(), AUX::vcon_avl, AUX::vcon_base, VCON_CONVAL, and AUX::vcon_size.
Referenced by gen_resized_vect(), get_vcon0(), get_vcon0_n(), get_vcon1(), get_vcon_scalar(), get_vconi(), and get_vconm0().
get_vcon0()
int get_vcon0 (DTYPE dtype)
Get a vector constant of a zero which suits the element type.
...
Definition at line 507 of file symtab.cpp.
References assert, CONVAL2G, STB::dbl0, DTY, DTySeqTyElement, DTyVecLength, ERR_Severe, STB::flt0, get_vcon(), i, STB::k0, n, stb, TY_DBLE, TY_FLOAT, TY_INT8, TY_LOG8, TY_VECT_MAXLEN, vc0, and zero.
Referenced by gen_scalar_to_vector_helper(), and get_vconm0().
get_vcon1()
int get_vcon1 (DTYPE dtype)
...
Definition at line 546 of file symtab.cpp.
References assert, CONVAL2G, STB::dbl1, DTY, DTySeqTyElement, DTyVecLength, ERR_Severe, STB::flt1, get_vcon(), i, STB::k1, n, one, stb, TY_DBLE, TY_FLOAT, TY_INT8, TY_LOG8, TY_VECT_MAXLEN, and vc1.
get_vcon_scalar()
SPTR get_vcon_scalar (INT sclr, DTYPE dtype)
...
Definition at line 628 of file symtab.cpp.
References assert, DTyVecLength, ERR_Severe, get_vcon(), i, n, and TY_VECT_MAXLEN.
Referenced by addarth(), gen_binary_expr(), and gen_llvm_expr().
get_vconm0()
int get_vconm0 (DTYPE dtype)
get a vector constant of a zero which suits the element type
Definition at line 581 of file symtab.cpp.
References assert, CONVAL2G, STB::dbl0, dblm0, DT_DBLE, DT_FLOAT, DTY, DTySeqTyElement, DTyVecLength, ERR_Severe, STB::flt0, fltm0, get_vcon(), get_vcon0(), getcon(), i, n, stb, TY_DBLE, TY_FLOAT, TY_VECT_MAXLEN, val, vcm0, and zero.
Referenced by gen_binary_expr().
getccssym()
SPTR getccssym (const char * pfx, int n, SYMTYPE stype)
Create (or possibly reuse) a compiler created symbol whose name is of the form . <pfx> dddd where dddd is the decimal representation of n.
Definition at line 1659 of file symtab.cpp.
References STB::curr_scope, getsym(), i, n, name, sptr, stb, and strlen().
Referenced by getccssym_sc().
getccssym_sc()
SPTR getccssym_sc (const char * pfx, int n, SYMTYPE stype, SC_KIND sc)
Similar to getccssym, but storage class is an argument. Calls getccssym if the storage class is not private; if private, a 'p' is appended to the name.
Definition at line 1684 of file symtab.cpp.
References STB::curr_scope, getccssym(), getsym(), i, n, name, sptr, stb, and strlen().
getccsym()
SPTR getccsym (char letter, int n, SYMTYPE stype)
create (or possibly reuse) a compiler created symbol whose name is of the form . <letter> dddd where dddd is the decimal representation of n.
Definition at line 1604 of file symtab.cpp.
References getsym(), n, name, set_ccflags(), sptr, and strlen().
Referenced by getccsym_sc(), and getlab().
getccsym_copy()
SPTR getccsym_copy (SPTR oldsptr)
...
Definition at line 1722 of file symtab.cpp.
References STB::curr_scope, DT_ISINT, fname, getsym(), i, len, malloc(), name, sptr, stb, strlen(), and SYMNAME.
Referenced by exp_smp().
getccsym_sc()
SPTR getccsym_sc (char letter, int n, SYMTYPE stype, SC_KIND sc)
Similar to getccsym, but storage class is an argument. Calls getccsym if the storage class is not private; if private, a 'p' is appended to the name.
Definition at line 1629 of file symtab.cpp.
References getccsym(), getcctemp_sc(), n, name, and sptr.
getcctemp_sc()
SPTR getcctemp_sc (const char * name, SYMTYPE stype, SC_KIND sc)
Create (or possibly reuse) a compiler created temporary where the caller constructs the name and passes the storage class as an argument.
Definition at line 1648 of file symtab.cpp.
References getsym(), name, set_ccflags(), and strlen().
Referenced by getccsym_sc(), lcpu_temp(), and ncpus_temp().
getcon()
SPTR getcon (INT * value, DTYPE dtype)
Enter constant of given dtype and value into the symbol table and return pointer to it. If an entry for the constant already exists, return pointer to the existing entry instead.
...
Enter constant of given dtype and value into the symbol table and return pointer to it.
Parameters
value is the constant value (value[1] if 1 word).
dtype - tbw.
Definition at line 334 of file symtab.cpp.
References ADDSYM, CONVAL2G, CONVAL2P, DTY, HASH_CON, STB::hashtb, sptr, stb, TY_QUAD, and value().
Referenced by get_semaphore(), get_vconm0(), and sym_init().
getlab()
SPTR getlab (void)
...
return a compiler-created label – user labels begin with '.', compiler- created labels begin with ''. Compiler-created labels will be mapped to fortran 77 labels by astout.
Definition at line 1829 of file symtab.cpp.
References getccsym(), STB::lbavail, and stb.
getnewccsym()
SPTR getnewccsym (char letter, int n, SYMTYPE stype)
Create (never reuse) a compiler created symbol whose name is of the form . <letter> dddd where dddd is the decimal representation of n.
Definition at line 1616 of file symtab.cpp.
References n, name, NEWSYM, putsname(), set_ccflags(), sptr, and strlen().
getntstring()
SPTR getntstring (const char * value)
Similar to getstring except the character string is null terminated.
Definition at line 729 of file symtab.cpp.
References getstring(), strlen(), and value().
getprint()
char * getprint (int sptr)
Return ptr to printable representation of the indicated symbol.
...
For symbols which are not constants, the name of the symbol is used. Constants are converted into the appropriate character representation.
Parameters
sptr - symbol table pointer
Definition at line 898 of file symtab.cpp.
References b, c, CONVAL2G, cprintf(), DTY, DTyCharLength, dtype, end, ERR_Informational, FLANG_FALLTHROUGH, interr(), len, STB::n_base, NEW, NULL, num, sptr, stb, SYMNAME, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_REAL, TY_WORD, and ui64toax().
Referenced by parmprint(), and symdentry().
getstring()
SPTR getstring (const char * value, int length)
Enter character constant into symbol table and return pointer to it.
Enter character constant into symbol table.
Parameters
value character string value
length length of character string
If the constant is already in the table, return pointer to the existing entry instead.
Definition at line 682 of file symtab.cpp.
References ADDSYM, DTY, DTyCharLength, get_type(), HASH_STR, STB::hashtb, i, length(), STB::n_base, p, putsname(), sptr, SPTR_NULL, stb, TY_CHAR, and value().
Referenced by getntstring().
getstringaddr()
SPTR getstringaddr (SPTR sptr)
Definition at line 740 of file symtab.cpp.
References STB::firstusym, NEWSYM, sptr, and stb.
getsym()
SPTR getsym (const char * name, int olength)
Like getsymbol, but accepts a string that is not null-terminated.
...
Enter symbol with indicated name into symbol table, initialize the new entry.
Parameters
name is the symbol name.
olength is the number of characters in the symbol name.
Definition at line 312 of file symtab.cpp.
References installsym, name, setimplicit(), and sptr.
Referenced by cng_generic(), cng_inttyp(), cng_specific(), get_semaphore(), getccssym(), getccssym_sc(), getccsym(), getccsym_copy(), getcctemp_sc(), getsymbol(), mkfunc(), and vmk_prototype().
getsymbol()
SPTR getsymbol (const char * name)
Enter symbol with indicated name into symbol table, initialize the new entry, and return pointer to it. If there is already such a symbol, just return pointer to the existing symbol table entry.
...
Parameters
name is the symbol name.
Definition at line 299 of file symtab.cpp.
References getsym(), name, and strlen().
implicit_int()
void implicit_int (DTYPE default_int)
Simple routine to reset the default integer type for implicitly typing integer variables. Needed for compile-type processing of -i4/-noi4 options in OPTIONS statement.
...
Definition at line 281 of file symtab.cpp.
References dtimplicit, and i.
Referenced by sym_init().
insert_sym()
SPTR insert_sym (SPTR first)
Create new symbol table entry and insert it in the hash list immediately in front of 'first':
...
Definition at line 1776 of file symtab.cpp.
References assert, ERR_Fatal, first, HASH_ID, STB::hashtb, i, j, NEWSYM, NOSYM, setimplicit(), sptr, stb, strlen(), and SYMNAME.
insert_sym_first()
SPTR insert_sym_first (SPTR first)
Create new symbol table entry and insert it in the hash list immediately in front of 'first':
...
Definition at line 1809 of file symtab.cpp.
References first, HASH_ID, STB::hashtb, i, NEWSYM, setimplicit(), sptr, stb, strlen(), and SYMNAME.
mk_prototype()
SPTR mk_prototype (const char * name, const char * attr, DTYPE resdt, int nargs, ...)
Make a prototype but do not register it.
...
Use when not using the LLVM backend or when the signature given is known to cause regressions in testing.
Definition at line 2001 of file symtab.cpp.
References name, nargs, NO_LLVM_CALLBACK, and vmk_prototype().
mk_prototype_llvm()
SPTR mk_prototype_llvm (const char * name, const char * attr, DTYPE resdt, int nargs, ...)
Make a prototype and register it with LLVM.
...
Definition at line 2015 of file symtab.cpp.
References LLVM_CALLBACK, name, nargs, and vmk_prototype().
mkfunc()
SPTR mkfunc (const char * nmptr)
Create a function ST item given a name.
...
create a function ST item given a name
Definition at line 1916 of file symtab.cpp.
References DT_INT, gbl, getsym(), sptr, strlen(), and sym_is_refd().
Referenced by vmk_prototype().
newimplicit()
void newimplicit (int firstc, int lastc, DTYPE dtype)
Change settings for implicit variable types, character lengths.
Parameters
firstc characters delimiting range
lastc characters delimiting range
dtype new value assigned to range
Definition at line 760 of file symtab.cpp.
References assert, CNULL, dtimplicit, dtype, ERR_Fatal, ERR_Severe, ERR_Warning, error(), gbl, i, IMPL_INDEX, j, and set.
parmprint()
const char * parmprint (int sptr)
Return ptr to printable representation of the indicated PARAMETER.
...
Parameters
sptr - symbol table pointer
Definition at line 857 of file symtab.cpp.
References buf, CONVAL2P, DT_INT, DT_LOG, DTY, dtype, getprint(), sptr, TY_BINT, TY_HOLL, TY_ISWORD, TY_SINT, and TY_WORD.
Referenced by symdentry().
pop_scope()
void pop_scope (void)
Scan all hash lists and remove symbols whose scope is greater than or equal to the current scope:
...
Definition at line 1853 of file symtab.cpp.
References STB::curr_scope, DBGBIT, gbl, HASHSIZE, STB::hashtb, i, j, sptr, stb, and SYMNAME.
pop_sym()
void pop_sym (int sptr)
Scan all hash lists and remove specified symbol from scope.
...
remove a symbol from its hash list
Definition at line 1881 of file symtab.cpp.
References DBGBIT, gbl, HASH_ID, STB::hashtb, j, name, s, sptr, SPTR_NULL, stb, strlen(), and SYMNAME.
putaltname()
static void putaltname (FILE * dfil, int sptr, const char * pref) static
Definition at line 1474 of file symtab.cpp.
References DTyCharLength, len, STB::n_base, sptr, ss, and stb.
Referenced by symdentry().
putcuda()
static void putcuda (FILE * dfil, int sptr) static
Definition at line 1497 of file symtab.cpp.
References CUDA_BUILTIN, CUDA_DEVICE, CUDA_GLOBAL, CUDA_GRID, CUDA_HOST, CUDAG, and sptr.
Referenced by dsym(), printblocks(), and symdentry().
reapply_implicit()
void reapply_implicit (void)
Scan backwards in the symbol table to reapply the current implicit state to variables which have not been typed. Invoked when an implicit statement follows specification statements (usually a severe error) and the option -x 125 0x80 is specified.
...
Definition at line 816 of file symtab.cpp.
References dtimplicit, DTySetFst, STB::firstusym, i, IMPL_INDEX, sptr, stb, and SYMNAME.
set_ccflags()
static void set_ccflags (int sptr, SYMTYPE stype) static
Definition at line 1592 of file symtab.cpp.
References sptr.
Referenced by getccsym(), getcctemp_sc(), and getnewccsym().
setimplicit()
void setimplicit (int sptr)
Assign to the indicated symbol table entry, the current implicit dtype.
...
assign to the indicated symbol table entry, the current implicit dtype.
Definition at line 789 of file symtab.cpp.
References dtimplicit, i, IMPL_INDEX, sptr, and SYMNAME.
Referenced by getsym(), insert_sym(), and insert_sym_first().
sign_extend()
INT sign_extend (INT val, int width)
Sign extend an integer value of an indicated width (8, 16, 32); value returned is sign extended with respect to the host's int type.
...
Sign extend an integer value of an indicated width (8, 16, 32); value returned is sign extended with respect to the host's int type.
Definition at line 670 of file symtab.cpp.
References val, and w.
sym_init()
void sym_init (void)
Initialize symbol table for new user program unit.
...
Initialize symbol table for new user program unit.
Definition at line 58 of file symtab.cpp.
References add_fp_constants(), AUX::arrdsc_avl, AUX::arrdsc_base, AUX::arrdsc_size, aux, BCOPY, BZERO, chkstruct(), clear_vc(), cng_generic(), cng_inttyp(), cng_specific(), AUX::curr_entry, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, STB::dt, DT_DBLE, DT_INT, DT_REAL, dtimplicit, DTySet, AUX::dvl_avl, AUX::dvl_base, AUX::dvl_size, STB::firstusym, flg, getcon(), HASHSIZE, STB::hashtb, i, STB::i0, STB::i1, FLG::i4, implicit_int(), init_chartab(), STB::k0, STB::k1, STB::lbavail, NMLDSC::lineno, llmp_reset_uplevel(), STB::n_base, STB::namavl, NEW, NMLDSC::next, SYMI::next, AUX::nml_avl, AUX::nml_base, AUX::nml_size, onlyentry, NMLDSC::sptr, SYMI::sptr, stb, STG_NEXT_SIZE, STG_RESET, sym_init_first(), AUX::symi_avl, AUX::symi_base, AUX::symi_size, tmp, AUX::vtypes, and XBIT.
symdentry()
void symdentry (FILE * file, int sptr)
...
Parameters
file the file.
sptr symbol currently being dumped.
Definition at line 1037 of file symtab.cpp.
References _PFG, aux, buff, CMEMLG, CONVAL2G, DEFLABG, DLL_EXPORT, DLL_IMPORT, DLLG, dmp_socs(), AUX::dpdsc_base, STB::dt, DT_DBLE, DT_FLOAT, DTY, DTyCharLength, dtype, DTySeqTyElement, DTyVecLength, ENDLINEG, ERR_Informational, f2, FILE, STB::firstusym, FUNCLINEG, getdtype(), getprint(), GREALG, GSAMEG, i, ILMG, interr(), ISZ_PF, n, NML_NEXT, NML_SPTR, ORIGDUMMYG, parmprint(), PDALNG, putaltname(), putcuda(), STB::scnames, SFDSCG, sptr, stb, STB::stypes, SYMI_NEXT, SYMI_SPTR, SYMNAME, TY_ISWORD, VCON_CONVAL, and WINNT_CALL.
Referenced by dbg_symdentry(), and symdmp().
symdmp()
void symdmp (FILE * dfil, bool full)
Dump symbol table for debugging purposes. If full == true, dump entire symbol table, otherwise dump symtab beginning with user symbols.
...
Definition at line 1559 of file symtab.cpp.
References STB::firstusym, full, sptr, stb, and symdentry().
tr_conval2g()
int tr_conval2g (char * fn, int ln, int s)
...
Definition at line 2087 of file symtab.cpp.
References DTY, fn, s, and stb.
tr_conval2p()
int tr_conval2p (char * fn, int ln, int s, int v)
...
Definition at line 2096 of file symtab.cpp.
References DTY, fn, s, and stb.
vmk_prototype()
static SPTR vmk_prototype (LLVMCallBack_t llCallBack, const char * name, const char * attr, DTYPE resdt, int nargs, va_list vargs) static
Definition at line 1948 of file symtab.cpp.
References args, ERR_Severe, FAST_MATH_FLAG, flags, getsym(), i, interr(), ll_add_func_proto(), LLVM_CALLBACK, mkfunc(), name, nargs, sptr, and strlen().
Referenced by mk_prototype(), and mk_prototype_llvm().
Variable Documentation
dblm0
int dblm0 static
Definition at line 492 of file symtab.cpp.
Referenced by get_vconm0().
struct { ... } dtimplicit[26 + 26 + 2]
Referenced by implicit_int(), newimplicit(), reapply_implicit(), setimplicit(), and sym_init().
dtype
DTYPE dtype
Definition at line 33 of file symtab.cpp.
Referenced by getprint(), newimplicit(), parmprint(), and symdentry().
fltm0
int fltm0 static
Definition at line 491 of file symtab.cpp.
Referenced by get_vconm0().
onlyentry
ENTRY onlyentry static
Definition at line 43 of file symtab.cpp.
Referenced by sym_init().
set
bool set
Definition at line 34 of file symtab.cpp.
Referenced by __INT8_T(), __INT_T(), _scan(), _verify(), fastset_add(), fastset_check(), fastset_contains(), fastset_dbgprintf(), fastset_free(), fastset_get(), fastset_init(), fastset_internal_drop_at(), fastset_is_empty(), fastset_limit(), fastset_member_index(), fastset_members(), fastset_pop(), fastset_reinit(), fastset_remove(), fastset_resize(), fastset_vacate(), idcache(), newimplicit(), resetMppBih(), and resetTaskBih().
vc0
int vc0[TY_MAX+1][TY_VECT_MAXLEN] static
Definition at line 488 of file symtab.cpp.
Referenced by clear_vc(), and get_vcon0().
vc1
int vc1[TY_MAX+1][TY_VECT_MAXLEN] static
Definition at line 489 of file symtab.cpp.
Referenced by clear_vc(), and get_vcon1().
vcm0
int vcm0[TY_MAX+1][TY_VECT_MAXLEN] static
Definition at line 490 of file symtab.cpp.
Referenced by clear_vc(), and get_vconm0().