flang: symutl.c File Reference
symutl.c File Reference
Fortran symbol utilities.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "symfun.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "soc.h"
#include "ast.h"
#include "gramtk.h"
#include "comm.h"
#include "extern.h"
#include "hpfutl.h"
#include "rte.h"
#include "semant.h"
Classes
struct BOUND
Macros
#define CONTIGUOUS_ARR(sptr) (ALLOCG(sptr) || CONTIGATTRG(sptr))
Functions
static int find_alloc_size (int ast, int foralllist, int *allocss, int *allocdtype, int *allocdim)
static int do_check_member_id (int astmem, int astid)
void set_symutl_sc (int sc)
int get_next_sym (const char *basename, const char *purpose)
int get_next_sym_dt (const char *basename, const char *purpose, int encldtype)
int get_len_of_deferchar_ast (int ast)
SPTR get_symtype (SYMTYPE stype, SPTR first)
Get the sptr of a specific name & SYMTYPE in the hash list.
int sym_get_scalar (const char *basename, const char *purpose, int dtype)
int sym_get_ptr (int base)
int sym_get_ptr_name (char *basename)
int sym_get_offset (int base)
int sym_get_array (const char *basename, const char *purpose, int dtype, int ndim)
Make a temporary array, not deferred shape. Bounds need to be filled in later.
int sym_mkfunc (const char *nmptr, int dtype)
Create a function ST item given a name.
int sym_mkfunc_nodesc (const char *nmptr, int dtype)
Create a function ST item given a name; set its NODESC flag.
int sym_mkfunc_nodesc_expst (const char *nmptr, int dtype)
Create a function ST item given a name; set its NODESC and EXPST flag.
int sym_mkfunc_nodesc_nocomm (const char *nmptr, int dtype)
Create a function ST item given a name; set its NODESC and NOCOMM flag.
int sym_mknproc (void)
void trans_mkdescr (int sptr)
int sym_get_sec (const char *basename, int is_dummy)
Create a section descriptor.
int sym_get_cp (void)
Create a channel pointer (cp)
int sym_get_xfer (void)
Create a channel pointer (xfer)
int sym_get_arg_sec (int sptr)
Create a section descriptor for a dummy argument.
int sym_get_formal (int basevar)
Get a symbol for the base address of the formal argument.
int constant_stride (int a, int *value)
Return TRUE if the ast (triplet or shape stride) has a constant value, and return its constant value.
int mk_forall_sptr (int forall_ast, int subscr_ast, int *subscr, int elem_dty)
int get_forall_subscr (int forall_ast, int subscr_ast, int *subscr, int elem_dty)
int get_temp_forall (int forall_ast, int subscr_ast, int alloc_stmt, int dealloc_stmt, int dty, int ast_dty)
Allocate a temporary to hold an array. Create the symbol pointer, add the allocate and deallocate statements, and return the array.
int get_temp_copy_section (int forall_ast, int lhs, int rhs, int alloc_stmt, int dealloc_stmt, int ast_dty)
This is almost identical to get_temp_forall() except that it has one more parameter, rhs.
int get_temp_pure (int forall_ast, int lhs, int rhs, int alloc_stmt, int dealloc_stmt, int ast_dty)
int get_temp_pure_replicated (int sptr, int alloc_stmt, int dealloc_stmt, int astmem)
Get a temp sptr1 which will be as big as sptr it will be replicated and allocated.
int get_temp_remapping (int arr_ast, int alloc_stmt, int dealloc_stmt, int dty)
static LOGICAL chk_temp_bnds (int lhs, int arr_sptr, int *subscr, int ndim)
int mk_assign_sptr (int arr_ast, const char *purpose, int *subscr, int elem_dty, int *retval)
int find_dummy (int entry, int pos)
int find_array (int ast, int *returnast)
static LOGICAL found_forall_var (int ast)
static void fixup_allocd_tmp_bounds (int *subscr, int *newsubscr, int ndim)
void fixup_srcalloc_bounds (int *subscr, int *newsubscr, int ndim)
int chk_assign_sptr (int arr_ast, const char *purpose, int *subscr, int elem_dty, int lhs, int *retval)
int mk_shape_sptr (int shape, int *subscr, int elem_dty)
void check_small_allocatable (int sptr)
static int handle_non_cnst_dim (int arr_ast, const char *purpose, int *subscr, int elem_dty, int dim, int lhs, int *retval, int ndim)
int chk_reduc_sptr (int arr_ast, const char *purpose, int *subscr, int elem_dty, int dim, int lhs, int *retval)
static void mk_temp_based (int sptr)
int mk_spread_sptr (int arr_ast, const char *purpose, int *subscr, int elem_dty, int dim, int ncopies, int lhs, int *retval)
int mk_matmul_sptr (int arg1, int arg2, const char *purpose, int *subscr, int elem_dty, int *retval)
int mk_transpose_sptr (int arr_ast, const char *purpose, int *subscr, int elem_dty, int *retval)
int mk_pack_sptr (int shape, int elem_dty)
int mk_maxloc_sptr (int shape, int elem_dty)
int search_forall_var (int ast, int list)
int other_forall_var (int ast, int list, int fnd)
int mk_forall_sptr_copy_section (int forall_ast, int lhs, int rhs, int *subscr, int elem_dty)
int mk_forall_sptr_gatherx (int forall_ast, int lhs, int rhs, int *subscr, int elem_dty)
int mk_forall_sptr_pure (int forall_ast, int lhs, int rhs, int *subscr, int elem_dty)
int first_element (int ast)
int mk_mem_allocate (int in_ast, int *subscr, int alloc_stmt, int ast_len_from)
int mk_mem_deallocate (int in_ast, int dealloc_stmt)
void init_bnd (void)
int getbnd (const char *basename, const char *purpose, int n, int dtype)
int trans_getbound (int sym, int type)
int check_member (int astmem, int astid)
int first_hash (int sptr)
LOGICAL has_allocattr (int sptr)
int get_next_hash_link (int sptr, int task)
utility function for visiting symbols of a specified name.
int findByNameStypeScope (char *symname, int stype, int scope)
utility function for finding a symbol in the symbol table that has a specified name.
LOGICAL is_array_sptr (int sptr)
LOGICAL is_unl_poly (int sptr)
bool is_impure (int sptr)
LOGICAL needs_descriptor (int sptr)
bool proc_arg_needs_proc_desc (SPTR symfunc)
SPTR get_member_descriptor (int sptr)
int find_member_descriptor (int sptr)
int find_descriptor_ast (int sptr, int ast)
int find_dummy_position (int proc_sptr, int arg_sptr)
int max_binding_invobj (int impl_sptr, int invobj)
static LOGICAL test_tbp_or_final (int sptr)
LOGICAL is_tbp (int sptr)
LOGICAL is_final_procedure (int sptr)
LOGICAL is_tbp_or_final (int sptr)
int get_tmp_descr (DTYPE dtype)
create a temporary variable that holds a temporary descriptor.
SPTR get_proc_ptr (SPTR sptr)
get a temporary procedure pointer to a specified procedure.
int get_descriptor_length_ast (int descriptor_ast)
int symbol_descriptor_length_ast (SPTR sptr, int ast)
int get_value_length_ast (DTYPE value_dtype, int value_ast, SPTR sptr, DTYPE sptr_dtype, int value_descr_ast)
void add_auto_len (int sym, int Lbegin)
Variables
SYMUTL symutl
static int symutl_sc = SC_LOCAL
static BOUND bound
Detailed Description
Fortran symbol utilities.
Definition in file symutl.c.
Macro Definition Documentation
CONTIGUOUS_ARR
#define CONTIGUOUS_ARR (sptr) (ALLOCG(sptr) || CONTIGATTRG(sptr))
Definition at line 28 of file symutl.c.
Function Documentation
add_auto_len()
void add_auto_len (int sym, int Lbegin)
Definition at line 3972 of file symutl.c.
Referenced by allocate_one_auto(), gen_pointer_result(), interface_for_entry(), interface_for_llvmiface(), transform_wrapup(), and wrap_symbol().
check_member()
int check_member (int astmem, int astid)
Definition at line 3403 of file symutl.c.
Referenced by _cr_nme(), _linearize(), _linearize_func(), _PDsize(), _ptrassign(), add_lbnd(), add_ptr_assign(), add_reduce_descriptor(), add_spread_descriptor(), bld_lhs(), bld_ud(), bld_use(), check_alloc_ptr_type(), check_pointer_type(), chk_struct_constructor(), collapse_assignment(), conv_allocate(), conv_deallocate(), convert_subscript(), copy_arg_to_seq_tmp(), copy_desc_to_bnds_vars(), cyclic_section(), emit_alnd(), emit_get_scalar(), emit_kopy_in(), emit_overlap(), emit_permute_section(), emit_secd(), emit_sum_scatterx(), fill_argt_with_alnd(), fix_mem_ast(), fix_proc_pointer_call(), forall_2_sec(), gen_contig_check(), gen_defer_shape(), gen_finalization_for_sym(), gen_islocal_index(), gen_localize_index(), gen_poly_element_arg(), gen_set_len_ast(), gen_set_type(), generate_copy(), generate_gather(), generate_get_scalar(), generate_hcycliclp(), generate_hlocalizebnds(), genPolyAsn(), get_allobnds(), get_descr_arg(), get_forall_subscr(), get_header_member_with_parent(), get_invoking_proc_desc(), get_sdsc_ast(), handle_seq_section(), init_intrin_type_desc(), inline_hlocalizebnds(), inline_reduction_f90(), inline_RTE_set_type(), is_whole_dim(), lower_ast(), lower_intrinsic(), lower_numelm(), lower_stmt(), make_forall(), make_sec_ast(), make_sec_from_ast_chk(), make_temp_descriptor(), mk_allocate_scalar(), mk_deallocate_scalar(), mk_forall_sptr(), mklvalue(), move_alloc_arg(), normalize_forall_array(), print_ast(), print_refsym(), redimension(), ref_array(), ref_pd(), reference_for_temp(), replace_arguments(), rewrite_inlined_args(), semant3(), semantio(), set_assumed_bounds(), set_descr_tag(), size_of_ast(), size_of_dtype(), sub_lbnd(), temp_type_descriptor(), transform_associated(), transform_c_f_pointer(), transform_c_f_procpointer(), transform_call(), transform_ptr(), transform_section_arg(), and wrap_symbol().
check_small_allocatable()
void check_small_allocatable (int sptr)
Definition at line 1681 of file symutl.c.
Referenced by inline_reduction_f90().
chk_assign_sptr()
int chk_assign_sptr (int arr_ast, const char * purpose, int * subscr, int elem_dty, int lhs, int * retval)
Definition at line 1460 of file symutl.c.
Referenced by mk_result_sptr().
chk_reduc_sptr()
int chk_reduc_sptr (int arr_ast, const char * purpose, int * subscr, int elem_dty, int dim, int lhs, int * retval)
Definition at line 1780 of file symutl.c.
Referenced by mk_result_sptr().
chk_temp_bnds()
static LOGICAL chk_temp_bnds (int lhs, int arr_sptr, int * subscr, int ndim) static
Definition at line 1201 of file symutl.c.
constant_stride()
int constant_stride (int a, int * value)
Return TRUE if the ast (triplet or shape stride) has a constant value, and return its constant value.
Definition at line 514 of file symutl.c.
References a, CONVAL2G, DT_ISINT, FALSE, sptr, TRUE, and value().
Referenced by get_forall_subscr(), mk_forall_sptr(), and reference_for_temp().
do_check_member_id()
static int do_check_member_id (int astmem, int astid) static
Definition at line 3473 of file symutl.c.
find_alloc_size()
static int find_alloc_size (int ast, int foralllist, int * allocss, int * allocdtype, int * allocdim) static
Definition at line 2606 of file symutl.c.
Referenced by mk_forall_sptr().
find_array()
int find_array (int ast, int * returnast)
Definition at line 1256 of file symutl.c.
Referenced by _reshape(), collapse_assignment(), fix_array_fields(), lower_intrinsic(), matmul_use_lhs(), mk_result_sptr(), and mmul_arg().
find_descriptor_ast()
int find_descriptor_ast (int sptr, int ast)
Definition at line 3746 of file symutl.c.
Referenced by build_poly_func_node(), construct_association(), get_sdsc_ast(), init_derived_type(), rewrite_allocatable_assignment(), set_type_in_descriptor(), and transform_move_alloc().
find_dummy()
int find_dummy (int entry, int pos)
Definition at line 1240 of file symutl.c.
Referenced by copy_arg_to_seq_tmp(), handle_seq_section(), is_optional_char_dummy(), need_copyout(), stride_1_dummy(), and stride_1_section().
find_dummy_position()
int find_dummy_position (int proc_sptr, int arg_sptr)
Definition at line 3784 of file symutl.c.
Referenced by fix_iface(), fix_proc_pointer_call(), get_tbp_argno(), handle_arguments(), incr_invobj_for_retval_add(), lower_function(), semCheckTbp(), and transform_call().
find_member_descriptor()
int find_member_descriptor (int sptr)
Definition at line 3730 of file symutl.c.
findByNameStypeScope()
int findByNameStypeScope (char * symname, int stype, int scope)
utility function for finding a symbol in the symbol table that has a specified name.
Note: The first symbol that meets the criteria specified in the arguments is returned. If you need to make multiple queries of the symbol table, consider using the function get_next_hash_link() instead.
Parameters
symname is a C string that specifies the name of the symbol to find
stype specifies a particular symbol type to find or 0 will locate any symbol type.
scope specifies the scope symbol table pointer to search for the symbol. If scope is 0 then the symbol can appear in any scope. If scope is -1, then the first symbol that's in scope is returned.
Returns
symbol table pointer of the first symbol found that meets the criteria mentioned above; else 0.
Definition at line 3619 of file symutl.c.
Referenced by defined_operator(), do_access(), fix_iface0(), fix_proc_pointer_call(), fixup_KIND_expr(), get_retval_KIND_value(), import(), inheritTbps(), ref_intrin(), resolveImp(), semant1(), semant2(), semCheckTbp(), subr_call2(), and update_proc_ptr_dtype_from_interface().
first_element()
int first_element (int ast)
Definition at line 3032 of file symutl.c.
Referenced by _reshape(), collapse_assignment(), get_len_of_deferchar_ast(), handle_seq_section(), lower_stmt(), and transform_ptr().
first_hash()
int first_hash (int sptr)
Definition at line 3509 of file symutl.c.
Referenced by apply_use(), check_defined_io2(), create_func_entry(), declsym(), do_common_blocks(), dumphashlk(), find_best_generic(), find_def_in_most_recent_scope(), find_in_host(), find_operator(), gen_array_result(), get_iso_ptrtype(), get_retval_derived_type(), import_symbol(), merge_generics(), resolve_fwd_ref(), resolve_fwd_refs(), semant1(), and sym_in_scope().
fixup_allocd_tmp_bounds()
static void fixup_allocd_tmp_bounds (int * subscr, int * newsubscr, int ndim) static
Definition at line 1360 of file symutl.c.
fixup_srcalloc_bounds()
void fixup_srcalloc_bounds (int * subscr, int * newsubscr, int ndim)
Definition at line 1417 of file symutl.c.
found_forall_var()
static LOGICAL found_forall_var (int ast) static
Definition at line 1305 of file symutl.c.
get_descriptor_length_ast()
int get_descriptor_length_ast (int descriptor_ast)
Definition at line 3911 of file symutl.c.
get_forall_subscr()
int get_forall_subscr (int forall_ast, int subscr_ast, int * subscr, int elem_dty)
Definition at line 797 of file symutl.c.
References ADD_LWAST, ADD_UPAST, ASD_NDIM, ASD_SUBS, assert, ast, astb, ASTLI_TRIPLE, ASTB::bnd, c, check_member(), constant_stride(), STB::dt_int, ASTB::dtype, flg, get_forall_subscr(), i, ASTB::i1, interr(), k, MAXDIMS, MAXSUBS, mk_binop(), mk_triple(), n, ndims, ASTB::one, OP_ADD, OP_DIV, OP_SUB, FLG::opt, other_forall_var(), search_forall_var(), SHD_LWB, SHD_STRIDE, SHD_UPB, sptr, stb, stride, subscr, STB::user, and XBIT.
Referenced by get_forall_subscr(), and get_temp_forall2().
get_len_of_deferchar_ast()
int get_len_of_deferchar_ast (int ast)
Definition at line 78 of file symutl.c.
References assert, ast, astb, ASTB::bnd, ASTB::dtype, first, first_element(), get_byte_len(), get_byte_len_indx(), get_member_descriptor(), mk_id(), mk_isz_cval(), mk_member(), mk_subscr(), and sptr.
Referenced by add_ptr_assign(), func_call2(), gen_alloc_dealloc(), gen_automatic_reallocation(), gen_bounds_assignments(), rewrite_allocatable_assignment(), and rewrite_func_ast().
get_member_descriptor()
SPTR get_member_descriptor (int sptr)
Definition at line 3717 of file symutl.c.
Referenced by add_ptr_assign(), check_alloc_ptr_type(), check_pointer_type(), gen_contig_check(), gen_poly_element_arg(), gen_set_type(), genPolyAsn(), get_descr_arg(), get_invoking_proc_desc(), get_len_of_deferchar_ast(), get_parameterized_dt(), init_intrin_type_desc(), ref_pd(), semant3(), and transform_call().
get_next_hash_link()
int get_next_hash_link (int sptr, int task)
utility function for visiting symbols of a specified name.
This function is used to visit symbols of a specified name. The user of this function should first initialize the search by calling the function with task == 0.
After initializing the search, the user can call this function with the same sptr and a task == 1 or task == 2. The function will return the sptr of the next unvisited symbol based on the criteria specified in the task argument. Below summarizes the values for task:
If task == 0, then this function will unset the VISIT flag for all symbols with the same name as sptr.
If task == 1, then return symbol must have the same symbol table type as the sptr argument.
If task == 2, then the returned symbol can have any symbol table type.
Caveat: Do not use this function when another phase is using the the VISIT field. For example, during the lower phase.
Parameters
sptr is the symbol table pointer of the name you wish to find.
task is the task the function will perform (see comments above).
Returns
symbol table pointer of next unvisited symbol or 0 if no more symbols have been found.
Definition at line 3564 of file symutl.c.
Referenced by get_tbp_argno(), mkexpr1(), resolvePass(), semant1(), semCheckTbp(), and subr_call2().
get_next_sym()
int get_next_sym (const char * basename, const char * purpose)
Definition at line 45 of file symutl.c.
References STB::curr_scope, gbl, getsymbol(), mangle_name(), p, sptr, and stb.
Referenced by add_equivalence(), add_padding(), alloc_char_temp(), func_call2(), gen_allocatable_result(), gen_array_result(), gen_dtsfmt_args(), gen_finalized_result(), gen_pointer_result(), gen_unique_func_ast(), get_charintrin_temp(), get_csect_sym(), get_nml_array(), get_parameterized_dt(), init_derived_w_acl(), make_module_common(), makezero(), new_seq_temp_array(), ptrfunc_call(), rewrite_func_ast(), semant1(), semant2(), sym_get_arg_sec(), sym_get_array(), sym_get_formal(), sym_get_offset(), sym_get_ptr(), sym_get_ptr_name(), sym_get_scalar(), sym_get_sdescr(), sym_get_sec(), and trans_mkdescr().
get_next_sym_dt()
int get_next_sym_dt (const char * basename, const char * purpose, int encldtype)
Definition at line 61 of file symutl.c.
References STB::curr_scope, gbl, getsymbol(), mangle_name_dt(), p, sptr, and stb.
Referenced by sym_get_offset(), sym_get_ptr(), and sym_get_sdescr().
get_proc_ptr()
SPTR get_proc_ptr (SPTR sptr)
get a temporary procedure pointer to a specified procedure.
Parameters
sptr is the ST_PROC pointer target.
Returns
the procedure pointer.
Definition at line 3877 of file symutl.c.
Referenced by transform_call().
get_symtype()
SPTR get_symtype (SYMTYPE stype, SPTR first)
Get the sptr of a specific name & SYMTYPE in the hash list.
Parameters
stype the SYMTYPE
first where to start the search (also establishes the name)
Definition at line 116 of file symutl.c.
References first, NOSYM, and sptr.
Referenced by gen_array_result().
get_temp_copy_section()
int get_temp_copy_section (int forall_ast, int lhs, int rhs, int alloc_stmt, int dealloc_stmt, int ast_dty)
This is almost identical to get_temp_forall() except that it has one more parameter, rhs.
Parameters
forall_ast ast for forall
lhs ast for LHS
rhs ast for RHS
alloc_stmt statement before which to allocate temp
dealloc_stmt statement after which to deallocate temp
ast_dty ast with data type of element required
Returns
symbol table pointer for array
For copy_section, we would like to decide the rank of temp according to rhs and distribution will be according to lhs. This case arise since we let copy_section to do also multicasting For example a(i,j) = b(2*i,3) kind of cases. tmp will be 1 dimensional and that will be distribute according to the fist dim of a.
Definition at line 1115 of file symutl.c.
Referenced by emit_permute_section().
get_temp_forall()
int get_temp_forall (int forall_ast, int subscr_ast, int alloc_stmt, int dealloc_stmt, int dty, int ast_dty)
Allocate a temporary to hold an array. Create the symbol pointer, add the allocate and deallocate statements, and return the array.
Parameters
forall_ast ast for forall
subscr_ast ast for subscript expression
alloc_stmt statement before which to allocate temp
dealloc_stmt statement after which to deallocate temp
dty datatype, or zero
ast_dty ast with data type of element required
Returns
symbol table pointer for array
The dimensions and mapping for the array are determined from the subscr_ast and the forall_ast. The subscr_ast has dimensions which are indexed by forall variables, and dimensions that are not. Those that are not are excluded from the temp. The caller can use the same index expressions to index this temp, as are used in the subscr_ast.
The dimensions included in the temp are taken from the array referenced by the subscr ast. Alignments for those dimensions are also taken from this array.
The allocate for the temporary is placed before alloc_stmt, and the deallocate is placed after dealloc_stmt. The name of the temporary is derived from the name of the array in the subscr_ast.
Definition at line 1049 of file symutl.c.
Referenced by emit_sum_scatterx(), forall_dependency(), forall_dependency_scalarize(), forall_lhs_indirection(), and forall_with_mask().
get_temp_pure()
int get_temp_pure (int forall_ast, int lhs, int rhs, int alloc_stmt, int dealloc_stmt, int ast_dty)
Parameters
forall_ast ast for forall
lhs ast for LHS
rhs ast for RHS
alloc_stmt statement before which to allocate temp
dealloc_stmt statement after which to deallocate temp
ast_dty ast with data type of element required
Definition at line 1135 of file symutl.c.
get_temp_pure_replicated()
int get_temp_pure_replicated (int sptr, int alloc_stmt, int dealloc_stmt, int astmem)
Get a temp sptr1 which will be as big as sptr it will be replicated and allocated.
Parameters
sptr sptr to replicate
alloc_stmt statement before which to allocate temp
dealloc_stmt statement after which to deallocate temp
astmem - tbw.
Definition at line 1154 of file symutl.c.
get_temp_remapping()
int get_temp_remapping (int arr_ast, int alloc_stmt, int dealloc_stmt, int dty)
Parameters
arr_ast ast for arr_ast
alloc_stmt statement before which to allocate temp
dealloc_stmt statement after which to deallocate temp
dty ast with data type of element required
Definition at line 1189 of file symutl.c.
get_tmp_descr()
int get_tmp_descr (DTYPE dtype)
create a temporary variable that holds a temporary descriptor.
Parameters
dtype is the data type of the temporary variable.
Returns
the temporary variable.
Definition at line 3857 of file symutl.c.
Referenced by transform_call().
get_value_length_ast()
int get_value_length_ast (DTYPE value_dtype, int value_ast, SPTR sptr, DTYPE sptr_dtype, int value_descr_ast)
Definition at line 3943 of file symutl.c.
Referenced by construct_association(), and transform_call().
getbnd()
int getbnd (const char * basename, const char * purpose, int n, int dtype)
Definition at line 3301 of file symutl.c.
handle_non_cnst_dim()
static int handle_non_cnst_dim (int arr_ast, const char * purpose, int * subscr, int elem_dty, int dim, int lhs, int * retval, int ndim) static
Definition at line 1733 of file symutl.c.
has_allocattr()
LOGICAL has_allocattr (int sptr)
Definition at line 3522 of file symutl.c.
Referenced by dealloc_dt_auto(), nop_dealloc(), and sem_set_storage_class().
init_bnd()
void init_bnd (void)
Definition at line 3281 of file symutl.c.
Referenced by forall_init().
is_array_sptr()
LOGICAL is_array_sptr (int sptr)
Definition at line 3637 of file symutl.c.
Referenced by is_array_ast().
is_final_procedure()
LOGICAL is_final_procedure (int sptr)
Definition at line 3839 of file symutl.c.
is_impure()
bool is_impure (int sptr)
Definition at line 3661 of file symutl.c.
Referenced by check_doconcurrent_ast(), check_pure_interface(), is_impure_finalizer(), is_pcalls(), and semant1().
is_tbp()
LOGICAL is_tbp (int sptr)
Definition at line 3833 of file symutl.c.
Referenced by gen_set_type(), get_vtoff(), is_tbp_component(), lower_function(), and semant1().
is_tbp_or_final()
LOGICAL is_tbp_or_final (int sptr)
Definition at line 3845 of file symutl.c.
Referenced by add_iolptrs(), all_default_init(), allocatable_member(), allocate_aligned(), chk_struct_constructor(), chkstruct(), dinit_data(), get_exttype_struct_constructor(), handle_allocatable_members(), has_poly_mbr(), has_private(), is_poly(), is_tbp_or_final_component(), make_structkwd_str(), nullify_member(), nullify_member_after(), rewrite_allocatable_assignment(), rewrite_deallocate(), size_of_var(), and wrap_symbol().
is_unl_poly()
LOGICAL is_unl_poly (int sptr)
Definition at line 3653 of file symutl.c.
Referenced by _constructf90(), construct_association(), ENTF90(), gen_alloc_mbr(), handle_arguments(), lower_function(), ref_array(), rewrite_allocatable_assignment(), semant3(), set_type_in_descriptor(), and transform_call().
max_binding_invobj()
int max_binding_invobj (int impl_sptr, int invobj)
Definition at line 3806 of file symutl.c.
Referenced by handle_arguments(), lower_function(), and transform_call().
mk_assign_sptr()
int mk_assign_sptr (int arr_ast, const char * purpose, int * subscr, int elem_dty, int * retval)
Definition at line 1230 of file symutl.c.
Referenced by mk_ptr_subscr(), rewrite_block_where(), rewrite_sub_args(), and semant3().
mk_forall_sptr()
int mk_forall_sptr (int forall_ast, int subscr_ast, int * subscr, int elem_dty)
Definition at line 538 of file symutl.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_UPAST, ADD_UPBD, ASD_NDIM, ASD_SUBS, assert, ast, astb, ASTLI_TRIPLE, ASTB::bnd, c, check_member(), constant_stride(), STB::dt_int, ASTB::dtype, find_alloc_size(), flg, i, ASTB::i1, interr(), k, MAXDIMS, MAXSUBS, mk_binop(), mk_extent(), mk_triple(), n, ndims, ASTB::one, OP_ADD, OP_DIV, OP_SUB, FLG::opt, other_forall_var(), search_forall_var(), SHD_LWB, SHD_STRIDE, SHD_UPB, sptr, stb, stride, subscr, sym_get_array(), SYMNAME, trans_mkdescr(), STB::user, and XBIT.
Referenced by get_temp_forall2().
mk_forall_sptr_copy_section()
int mk_forall_sptr_copy_section (int forall_ast, int lhs, int rhs, int * subscr, int elem_dty)
Definition at line 2684 of file symutl.c.
Referenced by temp_copy_section().
mk_forall_sptr_gatherx()
int mk_forall_sptr_gatherx (int forall_ast, int lhs, int rhs, int * subscr, int elem_dty)
Definition at line 2811 of file symutl.c.
Referenced by temp_gatherx().
mk_forall_sptr_pure()
int mk_forall_sptr_pure (int forall_ast, int lhs, int rhs, int * subscr, int elem_dty)
Definition at line 2945 of file symutl.c.
mk_matmul_sptr()
int mk_matmul_sptr (int arg1, int arg2, const char * purpose, int * subscr, int elem_dty, int * retval)
Definition at line 2123 of file symutl.c.
Referenced by mk_result_sptr().
mk_maxloc_sptr()
int mk_maxloc_sptr (int shape, int elem_dty)
Definition at line 2455 of file symutl.c.
Referenced by rewrite_func_ast().
mk_mem_allocate()
int mk_mem_allocate (int in_ast, int * subscr, int alloc_stmt, int ast_len_from)
Definition at line 3089 of file symutl.c.
Referenced by allocate_one_auto(), copy_arg_to_seq_tmp(), copy_replic_sect_to_tmp(), generate_hallobnds(), get_charintrin_temp(), get_temp_forall2(), matmul(), mmul(), reshape(), rewrite_block_where(), rewrite_func_ast(), rewrite_intr_allocatable(), rewrite_sub_args(), and wrap_symbol().
mk_mem_deallocate()
int mk_mem_deallocate (int in_ast, int dealloc_stmt)
Definition at line 3238 of file symutl.c.
Referenced by allocate_one_auto(), copy_arg_to_seq_tmp(), copy_back_to_replic_sect(), dealloc_dt_auto(), generate_hallobnds(), get_charintrin_temp(), get_temp_forall2(), matmul(), mmul(), reshape(), rewrite_block_where(), rewrite_func_ast(), rewrite_intr_allocatable(), rewrite_sub_args(), and wrap_symbol().
mk_pack_sptr()
int mk_pack_sptr (int shape, int elem_dty)
Definition at line 2435 of file symutl.c.
Referenced by mk_result_sptr().
mk_shape_sptr()
int mk_shape_sptr (int shape, int * subscr, int elem_dty)
Definition at line 1625 of file symutl.c.
Referenced by copy_replic_sect_to_tmp(), get_charintrin_temp(), mk_descr_from_section(), and mk_result_sptr().
mk_spread_sptr()
int mk_spread_sptr (int arr_ast, const char * purpose, int * subscr, int elem_dty, int dim, int ncopies, int lhs, int * retval)
Definition at line 1910 of file symutl.c.
Referenced by mk_result_sptr().
mk_temp_based()
static void mk_temp_based (int sptr) static
Definition at line 1889 of file symutl.c.
mk_transpose_sptr()
int mk_transpose_sptr (int arr_ast, const char * purpose, int * subscr, int elem_dty, int * retval)
Definition at line 2337 of file symutl.c.
Referenced by mk_result_sptr().
needs_descriptor()
LOGICAL needs_descriptor (int sptr)
Definition at line 3670 of file symutl.c.
Referenced by add_class_arg_descr_arg(), bld_ud(), gen_poly_element_arg(), get_descr_or_placeholder_arg(), get_type_descr_arg(), get_type_descr_arg2(), get_type_descr_dummy(), lower_symbol(), semant3(), and transform_call().
other_forall_var()
int other_forall_var (int ast, int list, int fnd)
Definition at line 2541 of file symutl.c.
Referenced by get_forall_subscr(), mk_forall_sptr(), and reference_for_temp().
proc_arg_needs_proc_desc()
bool proc_arg_needs_proc_desc (SPTR symfunc)
Definition at line 3706 of file symutl.c.
Referenced by handle_arguments(), and lower_function().
search_forall_var()
int search_forall_var (int ast, int list)
Definition at line 2483 of file symutl.c.
Referenced by get_forall_subscr(), is_same_number_of_idx(), mk_forall_sptr(), reference_for_temp(), and simple_reference_for_temp().
set_symutl_sc()
void set_symutl_sc (int sc)
Definition at line 38 of file symutl.c.
References SYMUTL::sc, symutl, and symutl_sc.
Referenced by set_descriptor_sc().
sym_get_arg_sec()
int sym_get_arg_sec (int sptr)
Create a section descriptor for a dummy argument.
Definition at line 409 of file symutl.c.
References AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_UPAST, AD_UPBD, astb, aux, ASTB::bnd, DDTG, AUX::dt_iarray_int, DT_INT, DTY, ASTB::dtype, FREE, get_next_sym(), mk_isz_cval(), p, scope, sptr, sym_get_sdescr(), sym_strsave(), SYMNAME, TY_CHAR, TY_NCHAR, and XBIT.
Referenced by add_class_arg_descr_arg(), init_newargs(), and newargs_for_entry().
sym_get_array()
int sym_get_array (const char * basename, const char * purpose, int dtype, int ndim)
Make a temporary array, not deferred shape. Bounds need to be filled in later.
Definition at line 208 of file symutl.c.
References AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_NOBOUNDS, AD_UPAST, AD_UPBD, get_array_dtype(), get_next_sym(), i, ndim, sptr, and symutl_sc.
Referenced by _reshape(), copy_inargs(), inline_reduction_f90(), mk_forall_sptr(), mkarg(), mkexpr1(), new_seq_temp_array(), put_data(), rewrite_func_ast(), and transform_call().
sym_get_cp()
int sym_get_cp (void)
Create a channel pointer (cp)
Definition at line 378 of file symutl.c.
References trans_getbound().
Referenced by emit_copy_section(), emit_overlap(), and emit_scatterx_gatherx().
sym_get_formal()
int sym_get_formal (int basevar)
Get a symbol for the base address of the formal argument.
Definition at line 474 of file symutl.c.
References ADD_EXTNTAST, ADD_LWAST, ADD_LWBD, ADD_NUMELM, ADD_UPAST, ADD_UPBD, astb, ASTB::bnd, DDTG, DTY, ASTB::dtype, get_array_dtype(), get_next_sym(), INTENTG, INTENTP, mk_isz_cval(), and SYMNAME.
Referenced by init_newargs(), and newargs_for_entry().
sym_get_offset()
int sym_get_offset (int base)
Definition at line 182 of file symutl.c.
References base, DT_PTR, get_next_sym(), get_next_sym_dt(), sptr, SYMNAME, and symutl_sc.
Referenced by get_all_descriptors(), and lower_make_all_descriptors().
sym_get_ptr()
int sym_get_ptr (int base)
Definition at line 144 of file symutl.c.
References base, DT_PTR, get_next_sym(), get_next_sym_dt(), sptr, SYMNAME, and symutl_sc.
Referenced by _reshape(), check_adjustable_array(), deferred_to_pointer(), gen_allocatable_result(), get_all_descriptors(), get_array_pointer(), lower_make_all_descriptors(), ref_based_object_sc(), rewrite_inlined_args(), and transform_wrapup().
sym_get_ptr_name()
int sym_get_ptr_name (char * basename)
Definition at line 168 of file symutl.c.
References DT_PTR, get_next_sym(), sptr, and symutl_sc.
sym_get_scalar()
int sym_get_scalar (const char * basename, const char * purpose, int dtype)
Definition at line 129 of file symutl.c.
References STB::curr_scope, get_next_sym(), SYMUTL::sc, sptr, stb, and symutl.
Referenced by _rewrite_scalar_fuctions(), add_private_allocatable(), allocate_array(), assign_scalar(), collapse_arrays(), copy_inargs(), copy_scalar_intent_in(), copy_to_scalar(), decl_private_sym(), emit_get_scalar(), emit_get_scalar_sub(), fix_dtype(), gen_early_bnd_dependencies(), gen_early_str_len(), gen_ptr_in(), get_init_idx(), hlv_getsym(), inline_reduction_f90(), inline_shifts(), mp_add_shared_var(), normalize_forall_triplet(), put_length_type_param(), rename_forall_list(), rewrite_func_ast(), semantio(), size_ast(), size_ast_of(), sym_get_place_holder(), tmp_assign(), and transform_all_call().
sym_get_sec()
int sym_get_sec (const char * basename, int is_dummy)
Create a section descriptor.
Definition at line 337 of file symutl.c.
References AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_UPAST, AD_UPBD, astb, aux, ASTB::bnd, AUX::dt_iarray_int, DT_PTR, ASTB::dtype, FREE, get_next_sym(), mk_isz_cval(), p, sym_strsave(), and symutl_sc.
Referenced by newargs_for_entry().
sym_get_xfer()
int sym_get_xfer (void)
Create a channel pointer (xfer)
Definition at line 395 of file symutl.c.
References trans_getbound().
Referenced by emit_copy_section(), emit_overlap(), and emit_scatterx_gatherx().
sym_mkfunc()
int sym_mkfunc (const char * nmptr, int dtype)
Create a function ST item given a name.
Definition at line 233 of file symutl.c.
References getsymbol(), sptr, and XBIT.
Referenced by _constructf90(), _sect(), build_conformable_func_node(), build_poly_func_node(), conv_deallocate(), convert_template_instance(), copy_arg_to_seq_tmp(), emit_alnd(), emit_fl(), emit_get_scalar_sub(), emit_permute_section(), emit_scatterx_gatherx(), emit_secd(), emit_sum_scatterx(), fill_cyclic_k(), gen_islocal_index(), gen_localize_index(), generate_copy(), generate_gather(), generate_get_scalar(), generate_hcycliclp(), generate_hlocalizebnds(), init_sdsc(), init_sdsc_bounds(), intrinsic_as_arg(), make_sec_from_ast_chk(), make_simple_template_from_ast(), make_temp_descriptor(), matmul(), mk_hpfiofunc(), mk_iofunc(), ref_pd(), reshape(), rewrite_func_ast(), semant3(), semantio(), sym_mkfunc_nodesc(), sym_mkfunc_nodesc_nocomm(), trans_mkproc(), and transform_associated().
sym_mkfunc_nodesc()
int sym_mkfunc_nodesc (const char * nmptr, int dtype)
Create a function ST item given a name; set its NODESC flag.
Definition at line 255 of file symutl.c.
References sptr, and sym_mkfunc().
Referenced by _constructf90(), add_ptr_assign(), add_reduce_descriptor(), add_spread_descriptor(), ast_intr(), check_pointer_type(), collapse_assignment(), conv_allocate(), do_nml(), elem_size_of_ast(), emit_alnd_secd(), emit_kopy_in(), emit_redim(), emit_scalar_kopy_in(), extent(), fill_ast(), fio_end_err(), gen_call_class_obj_size(), gen_contig_check(), gen_finalization_for_sym(), gen_init_unl_poly_desc(), gen_poly_element_arg(), genPolyAsn(), get_invoking_proc_desc(), getMergeSym(), init_derived_type(), mk_coercion_func(), mk_merge(), mk_set_type_call(), mmul(), presence_test(), ref_intrin(), ref_pd(), ref_pd_subr(), rewrite_allocatable_assignment(), rewrite_func_ast(), semant2(), semant3(), semantio(), semfin(), set_assumed_bounds(), set_assumsz_bound(), set_type_in_descriptor(), size_of_dtype(), sym_mkfunc_nodesc_expst(), and transform_call().
sym_mkfunc_nodesc_expst()
int sym_mkfunc_nodesc_expst (const char * nmptr, int dtype)
Create a function ST item given a name; set its NODESC and EXPST flag.
Could replace EXPST with a new flag. If the flag is set we still need transform_call() to fix arguments which are array sections.
Definition at line 273 of file symutl.c.
References sptr, and sym_mkfunc_nodesc().
Referenced by elem_size_of_ast(), ref_pd(), transform_c_f_pointer(), transform_c_f_procpointer(), and transform_move_alloc().
sym_mkfunc_nodesc_nocomm()
int sym_mkfunc_nodesc_nocomm (const char * nmptr, int dtype)
Create a function ST item given a name; set its NODESC and NOCOMM flag.
Definition at line 285 of file symutl.c.
References sptr, and sym_mkfunc().
sym_mknproc()
int sym_mknproc (void)
Definition at line 297 of file symutl.c.
References gbl.
Referenced by ref_pd(), and rewrite_func_ast().
symbol_descriptor_length_ast()
int symbol_descriptor_length_ast (SPTR sptr, int ast)
Definition at line 3924 of file symutl.c.
Referenced by construct_association(), and transform_call().
test_tbp_or_final()
static LOGICAL test_tbp_or_final (int sptr) static
Definition at line 3821 of file symutl.c.
trans_getbound()
int trans_getbound (int sym, int type)
Definition at line 3333 of file symutl.c.
Referenced by fill_cyclic_k(), outvalue_hcycliclp(), outvalue_hlocalizebnds(), sym_get_cp(), and sym_get_xfer().
trans_mkdescr()
void trans_mkdescr (int sptr)
Definition at line 307 of file symutl.c.
References FREE, get_next_sym(), NEWDSCG, p, sptr, sym_strsave(), SYMNAME, symutl_sc, and XBIT.
Referenced by get_all_descriptors(), inline_reduction_f90(), inline_small_matmul(), instantiate_interface(), make_alnd(), misc_checks(), mk_forall_sptr(), new_seq_temp_array(), nml_emit_desc(), and trans_get_descrs().
Variable Documentation
bound
BOUND bound static
Definition at line 3278 of file symutl.c.
Referenced by _PDbound(), propagate_bound(), and rqueue_ast().
symutl
SYMUTL symutl
FIXME: what is this?
Definition at line 33 of file symutl.c.
Referenced by alloc_char_temp(), get_charintrin_temp(), get_init_idx(), get_temp_forall2(), make_seq_temp_array(), new_seq_temp_array(), pop_subprogram(), restore_host(), rewrite_func_ast(), rw_semant_state(), save_host(), semant1(), semant_init(), set_symutl_sc(), sym_get_scalar(), sym_init(), and was_implicit().
symutl_sc
int symutl_sc = SC_LOCAL static
Definition at line 35 of file symutl.c.
Referenced by set_symutl_sc(), sym_get_array(), sym_get_offset(), sym_get_ptr(), sym_get_ptr_name(), sym_get_sec(), and trans_mkdescr().