flang: tan_f_vec.h File Reference
tan_f_vec.h File Reference
#include <math.h>
#include <common_tanf.h>
Functions
static vfloat INLINE __reduction_slowpath (vfloat const a, vmask *h)
static vfloat INLINE __tan_kernel (vfloat const a, vint2 const h)
static vfloat INLINE __tan_f_vec (vfloat const x)
Function Documentation
__reduction_slowpath()
static vfloat INLINE __reduction_slowpath (vfloat const a, vmask * h) static
Definition at line 23 of file tan_f_vec.h.
References a, d, e, float_as_int(), h, hi, i, i2opi_f, ia, idx, if(), lo, m, p, PI_2_M64, prev, q, r, s, t, ull, vadd64_vi2_vi2_vi2(), vadd_vi2_vi2_vi2(), vand_vi2_vi2_vi2(), vcast_vi2_i(), vcast_vm_i_i(), veq_vo_vi2_vi2(), vmulu_vi2_vi2_vi2(), vor_vi2_vi2_vi2(), vsel_vi2_vo_vi2_vi2(), vsll64_vi2_vi2_i(), vsll_vi2_vi2_i(), vsrl64_vi2_vi2_i(), vsrl_vi2_vi2_i(), vstore_v_p_vf(), vsub_vi2_vi2_vi2(), and vxor_vi2_vi2_vi2().
Referenced by __tan_f_vec().
__tan_f_vec()
static vfloat INLINE __tan_f_vec (vfloat const x) static
Definition at line 151 of file tan_f_vec.h.
References _2_OVER_PI_F, __reduction_slowpath(), __tan_kernel(), a, h, half, k, m, p, PI_2_HI_F, PI_2_LO_F, PI_2_MI_F, r, res, THRESHOLD_F, vand_vi2_vi2_vi2(), vcast_vf_f(), vcast_vi2_i(), vfma_vf_vf_vf_vf(), vgt_vo_vi2_vi2(), vmul_vf_vf_vf(), vsel_vf_vo_vf_vf(), vsll_vi2_vi2_i(), vsub_vf_vf_vf(), vtestz_i_vo(), and x.
Referenced by __attribute__().
__tan_kernel()
static vfloat INLINE __tan_kernel (vfloat const a, vint2 const h) static
Definition at line 128 of file tan_f_vec.h.
References a, A_F, B_F, C_F, cmp(), D_F, E_F, F_F, h, r, s, t, vcast_vf_f(), vcast_vi2_i(), vdiv_vf_vf_vf(), veq_vo_vi2_vi2(), vfma_vf_vf_vf_vf(), vmul_vf_vf_vf(), and vsel_vf_vo_vf_vf().
Referenced by __tan_f_vec().