flang: tempnam.c File Reference
tempnam.c File Reference
#include <errno.h>
#include <stdio.h>
Macros
#define P_tmpdir "/tmp"
Functions
unsigned long strlen (const char *)
void * malloc (unsigned long)
char * getenv (const char *)
static char * add (char *p, const char *q, int n)
static char * addn (char *p, int val, int n)
static char * gentmp (char *dir, char *pfx)
char * __io_tempnam (const char *dir, const char *pfx)
Variables
static int rand
static char chars []
Macro Definition Documentation
P_tmpdir
#define P_tmpdir "/tmp"
Definition at line 14 of file tempnam.c.
Function Documentation
__io_tempnam()
char * __io_tempnam (const char * dir, const char * pfx)
Definition at line 129 of file tempnam.c.
References access, gentmp(), and p.
Referenced by __fortio_scratch_name().
add()
static char * add (char * p, const char * q, int n) static
Definition at line 31 of file tempnam.c.
References n, p, and q.
Referenced by addn(), and gentmp().
addn()
static char * addn (char * p, int val, int n) static
Definition at line 43 of file tempnam.c.
References add(), chars, d, i, n, p, and val.
Referenced by gentmp().
gentmp()
static char * gentmp (char * dir, char * pfx) static
Definition at line 65 of file tempnam.c.
References add(), addn(), buf, chars, getenv(), malloc(), n, NULL, p, P_tmpdir, q, rand, strlen(), time(), and tmp.
Referenced by __io_tempnam().
getenv()
char * getenv (const char *)
Referenced by gentmp().
malloc()
void * malloc (unsigned long)
Referenced by __f90io_ldw(), __f90io_usw_write(), __fort_calloc_without_abort(), __fort_malloc_without_abort(), __fort_realloc(), __fortio_alloc_fcb(), __fortio_default_convert(), __fortio_getnum(), __fortio_open(), __pg_get_lock(), __pg_make_lock_file(), __pg_release_lock(), _f90io_ldr_init(), _f90io_nml_read(), _makezero(), _mp_malloc(), add_action(), add_generic_argument(), add_prototype(), addcombination(), alloc_flexible_mdnode(), alloc_fpbuf(), alloc_mdnode(), alloc_rbuf(), allocate_new_fmtgbl(), allocate_new_gbl(), allocate_refsymbol(), build_name_buffer(), call_format_double(), ccff_open(), compose_and_throw(), copy_action(), create_action_map(), create_arg_parser(), ef_alloc(), ENTF90(), fastset_resize(), fixup_nme(), fixup_x86_abi_return(), fr_OZconv_init(), fw_init(), fw_OZconv_init(), fw_write_record(), gentmp(), get_arch(), get_currentdir(), get_junk(), get_qstr(), get_struct_from_dsrt2(), getccsym_copy(), grow(), hashmap_sort(), init(), init_upper(), inquire(), layout_struct_body(), ll_add_func_proto(), ll_get_const_addrspacecast(), ll_get_const_bitcast(), ll_get_const_gep(), ll_get_function_pointer(), ll_get_global_pointer(), ll_get_gtid_addr_ili(), ll_get_gtid_val_ili(), ll_get_outlined_funcname(), ll_manage_malloc(), ll_manage_mem(), llvm_add_to_init_list(), lzinitfile(), malloc_obuff(), mth_i_override(), newprintfs(), put_buf(), read_line(), register_action_map_arg(), register_boolean_arg(), register_combined_bool_string_arg(), restore_gbl(), save_gbl(), save_samefcb(), sccalloc(), semantio(), set_modusename(), sptrListAdd(), stackcheck(), ulzinit(), and write_comm().
strlen()
unsigned long strlen (const char *)
Referenced by gentmp().
Variable Documentation
chars
char chars[] static
Initial value:
= {
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789XW"}
Definition at line 25 of file tempnam.c.
Referenced by addn(), and gentmp().
rand
int rand static
Definition at line 21 of file tempnam.c.
Referenced by gentmp().