flang: comm.c File Reference
tools/flang1/flang1exe/comm.c File Reference
Fortran communications module.
#include "comm.h"
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "soc.h"
#include "semant.h"
#include "ast.h"
#include "gramtk.h"
#include "extern.h"
#include "hpfutl.h"
#include "commopt.h"
#include "ccffinfo.h"
#include "dinit.h"
#include "fdirect.h"
#include "rte.h"
#include "rtlRtns.h"
#include "ilidir.h"
Classes
struct cs_table
Functions
static void comm_init (void)
Initialize the communication analyzer phase.
static void transform_ptr (int std, int ast)
static int normalize_forall_triplet (int std, int forall)
static void emit_overlap (int a)
static int emit_permute_section (int a, int std)
static int eliminate_extra_idx (int lhs, int a, int forall)
static int emit_copy_section (int a, int std)
static int canonical_conversion (int ast)
static void forall_dependency_scalarize (int std, int *std1, int *std2)
static LOGICAL is_use_lhs (int a, LOGICAL, LOGICAL, int)
static int emit_gatherx (int a, int std, LOGICAL opt)
static void fix_guard_forall (int std)
static void emit_sum_scatterx (int)
static void emit_scatterx (int)
static void emit_scatterx_gatherx (int std, int result, int array, int mask, int allocstd, int tempast0, int lhssec, int comm_type)
static void compute_permute (int lhs, int rhs, int list, int order[7])
static int put_data (int permute[7], int no)
static LOGICAL is_permuted (int array, int per[7], int per1[7], int *nper1)
static int scalar_communication (int ast, int std)
static int tag_call_comm (int std, int forall)
static void call_comm (int cstd, int fstd, int forall)
static void insert_call_comm (int std, int forall)
static void put_call_comm (int cstd, int fstd, int forall)
static void shape_communication (int std, int forall)
static void shape_comm (int cstd, int fstd, int forall)
static int sequentialize_mask_call (int forall, int stdnext)
static int sequentialize_stmt_call (int forall, int stdnext)
static int sequentialize_call (int cstd, int stdnext, int forall)
static void init_pertbl (void)
static void free_pertbl (void)
static int get_pertbl (void)
static int copy_section_temp_before (int sptr, int rhs, int forall)
static CTYPE * getcyclic (void)
static void init_opt_tables (void)
static LOGICAL is_scatter (int std)
static void opt_overlap (void)
static int insert_forall_comm (int ast)
static int forall_2_sec (int a, int forall)
This routine takes an array in a forall statement with its subinfo and replaces all forall indexes.
static int make_sec_ast (int arr, int std, int allocstd, int sectflag)
static int temp_copy_section (int std, int forall, int lhs, int rhs, int dty, int *allocast)
static int temp_gatherx (int std, int forall, int lhs, int rhs, int dty, int *allocast)
static int gatherx_temp_before (int sptr, int rhs, int forall)
Just like copy_section_temp_before() except it does not eliminate scalar dimension.
static int simple_reference_for_temp (int sptr, int a, int forall)
Like reference_for_temp(), this routine finds the dimension of sptr.
void comm_fini (void)
Finalize the phase and free allocated memory.
void comm_analyze (void)
Communication analyzer entry point.
void init_region (void)
Keep track of STD of endcritical or endmaster statement.
void check_region (int std)
Check a region is valid.
int insert_mask (int ast, int stdstart)
Create mask statements for conditional expression ast and insert them after stdstart. Return the STD of the last statement added.
int insert_endmask (int ast, int stdstart)
Create ENDIF statements corresponding to conditional statements emitted for mask expression ast. Insert the ENDIFs after stdstart. Return the STD of the last statement added.
void report_comm (int std, int cause)
Dump compiler internal information for the communication analyzer.
int add_lbnd (int dtyp, int dim, int ast, int astmember)
Construct an AST to add the lower bound of dimension dim for array datatype dtyp to ast, and return the new AST.
int sub_lbnd (int dtyp, int dim, int ast, int astmember)
Construct an AST to subtract the lower bound of dimension dim for array datatype dtyp to ast, and return the new AST.
LOGICAL normalize_bounds (int sptr)
Return TRUE if the bounds of array sptr should be 1-based with respect to the runtime.
LOGICAL is_same_number_of_idx (int dest, int src, int list)
int reference_for_temp (int sptr, int a, int forall)
This routine finds the dimension of sptr.
int record_barrier (LOGICAL bBefore, int astStmt, int std)
This routine a barrier statement in the barrier table.
int emit_get_scalar (int a, int std)
This routine is to read distributed array element at forall by using get scalar primitive.
void forall_opt1 (int ast)
void transform_forall (int std, int ast)
void scalarize (int std, int forall, LOGICAL after_transformer)
The forall should be treated like a serial statement.
void un_fuse (int forall)
This is necessary, if forall sequentialized.
void sequentialize (int std, int forall, LOGICAL after_transformer)
static void remove_section (int ast, int *pnewast, int *psectast, int *psptr, int *panydist, int *pnontrivial)
static LOGICAL is_bogus_forall (int forall)
static void permute_axis (int result, int array, int list, int permute[7])
static int shape_comm_in_expr (int expr, int forall, int std, int nomask)
static int fix_mem_ast (int astmem, int ast)
Variables
static struct cs_table cs_table
Detailed Description
Fortran communications module.
Definition in file tools/flang1/flang1exe/comm.c.
Function Documentation
add_lbnd()
int add_lbnd (int dtyp, int dim, int ast, int astmember)
Construct an AST to add the lower bound of dimension dim for array datatype dtyp to ast, and return the new AST.
Definition at line 332 of file tools/flang1/flang1exe/comm.c.
References ADD_LWAST, ast, astb, ASTB::bnd, check_member(), dim, ASTB::dtype, mk_binop(), ASTB::one, OP_ADD, and OP_SUB.
Referenced by conv_forall(), gen_islocal_index(), gen_localize_index(), generate_hcycliclp(), generate_hlocalizebnds(), and get_allobnds().
call_comm()
static void call_comm (int cstd, int fstd, int forall) static
Definition at line 3662 of file tools/flang1/flang1exe/comm.c.
References assert, ast, call_comm(), comminfo::forall, FT_CALL_CALL, FT_CALL_NCALL, glist(), i, STD_AST, and tag_forall_comm().
Referenced by call_comm(), and tag_call_comm().
canonical_conversion()
static int canonical_conversion (int ast) static
Definition at line 3984 of file tools/flang1/flang1exe/comm.c.
References A_STDP, ALIGNG, ASD_NDIM, ASD_SUBS, comminfo::asn, ast, ast_replace(), ast_rewrite(), ast_unvisit(), ast_visit(), astb, ASTLI_SPTR, ASTLI_TRIPLE, base, ASTB::bnd, ASTB::dtype, fix_mem_ast(), FT_NPCALL, FT_PCALL, i, interr(), is_dist_array_in_expr(), is_name_in_expr(), k, left_array_symbol(), left_subscript_ast(), lhs, list, mk_id(), mk_subscr(), mk_triple(), ndim, ASTB::one, OP_ADD, OP_DIV, OP_MUL, OP_SUB, opt_binop(), past(), plist(), replace_ast_subtree(), s, search_idx(), sptr, ss, STD_AST, stride, XBIT, zero, and ASTB::zero.
Referenced by transform_forall().
check_region()
void check_region (int std)
Check a region is valid.
Definition at line 197 of file tools/flang1/flang1exe/comm.c.
References A_STDG, ast, pure_gbl::end_critical_region, pure_gbl::end_master_region, std, and STD_AST.
Referenced by call_analyze(), comm_analyze(), and convert_forall().
comm_analyze()
void comm_analyze (void)
Communication analyzer entry point.
Definition at line 118 of file tools/flang1/flang1exe/comm.c.
References A_OPTYPEG, ast, check_region(), comm_init(), pure_gbl::end_master_region, gbl, init_region(), pure_gbl::local_mode, set_descriptor_sc(), std, STD_AST, STD_LINENO, STD_LOCAL, STD_NEXT, STD_PURE, transform_ast(), transform_forall(), transform_ptr(), and type.
comm_fini()
void comm_fini (void)
Finalize the phase and free allocated memory.
Definition at line 101 of file tools/flang1/flang1exe/comm.c.
References TRANSFORM::arrb, FINFO_TBL::base, finfot, FREE, free_pertbl(), NULL, TRANSFORM::stg_base, TRANSFORM::subb, TRANSFORM::tdescb, trans, and TRANS_FREE.
Referenced by convert_output().
comm_init()
static void comm_init (void) static
Initialize the communication analyzer phase.
Definition at line 950 of file tools/flang1/flang1exe/comm.c.
References TRANSFORM::arrb, init_brtbl(), init_pertbl(), TRANSFORM::subb, TRANSFORM::tdescb, trans, and TRANS_ALLOC.
Referenced by comm_analyze().
compute_permute()
static void compute_permute (int lhs, int rhs, int list, int order[7]) static
Definition at line 2222 of file tools/flang1/flang1exe/comm.c.
References ASD_NDIM, ASD_SUBS, assert, ASTLI_SPTR, count, FALSE, i, is_duplicate(), j, lhs, list, ndim, order, search_forall_idx(), and TRUE.
Referenced by permute_axis().
copy_section_temp_before()
static int copy_section_temp_before (int sptr, int rhs, int forall) static
Definition at line 1996 of file tools/flang1/flang1exe/comm.c.
References ASD_NDIM, ASD_SUBS, assert, ASTLI_SPTR, DTY, j, k, list, mk_id(), mk_subscr(), ndim, rank_of_sym(), search_forall_idx(), and sptr.
Referenced by emit_copy_section(), and emit_permute_section().
eliminate_extra_idx()
static int eliminate_extra_idx (int lhs, int a, int forall) static
Definition at line 2031 of file tools/flang1/flang1exe/comm.c.
References a, ASD_NDIM, ASD_SUBS, astb, ASTLI_SPTR, DTY, FALSE, i, ASTB::i1, is_name_in_expr(), k, lhs, list, mk_id(), mk_subscr(), ndim, search_forall_idx(), sptr, sptr_of_subscript(), and TRUE.
Referenced by emit_permute_section().
emit_copy_section()
static int emit_copy_section (int a, int std) static
Definition at line 1742 of file tools/flang1/flang1exe/comm.c.
References a, A_STDP, add_stmt_before(), ast, astb, ASTB::bnd, BOGUSFLAG, close_pragma(), copy_section_temp_before(), cp, dest, DTY, ASTB::dtype, emit_permute_section(), flg, forall_2_sec(), FT_CCOPY_ALLOC, FT_CCOPY_FREE, FT_CCOPY_LHS, FT_CCOPY_LHSSEC, FT_CCOPY_NOTLHS, FT_CCOPY_OUT, FT_CCOPY_REUSE, FT_CCOPY_RHS, FT_CCOPY_SAME, FT_CCOPY_SECTL, FT_CCOPY_SECTR, FT_CCOPY_TSPTR, FT_CCOPY_USELHS, FT_CSTART_ALLOC, FT_CSTART_COMM, FT_CSTART_FREE, FT_CSTART_INVMVD, FT_CSTART_OUT, FT_CSTART_REF, FT_CSTART_REUSE, FT_CSTART_RHS, FT_CSTART_SAME, FT_CSTART_SECTL, FT_CSTART_SECTR, FT_CSTART_TYPE, FT_CSTART_USEDSTD, FT_CSTART_USELHS, FT_FORALL, FT_HEADER, FT_NRT, FT_RTL, FT_SECTL, FT_STD, header(), is_bogus_forall(), is_ordered(), is_use_lhs(), lhs, list, make_sec_ast(), MAXDIMS, mk_ftb(), mk_id(), mk_stmt(), new_node(), no, plist(), sectflag, sptr, sptr_of_subscript(), std, STD_AST, STD_LINENO, comminfo::sub, sym_get_cp(), sym_get_xfer(), temp_copy_section(), TRUE, comminfo::usedstd, FLG::x, and xfer().
Referenced by insert_forall_comm().
emit_gatherx()
static int emit_gatherx (int a, int std, LOGICAL opt) static
Definition at line 2889 of file tools/flang1/flang1exe/comm.c.
References a, A_STDP, add_stmt_before(), ASD_NDIM, close_pragma(), DTY, emit_scatterx_gatherx(), FALSE, flg, comminfo::forall, forall_2_sec(), FT_HEADER, FT_NRT, FT_RTL, FT_SECTL, gatherx_temp_before(), header(), is_use_lhs(), lhs, list, make_sec_ast(), memsym_of_ast(), NOREINDEX, plist(), sectflag, sptr, std, STD_AST, STD_LINENO, comminfo::sub, temp_gatherx(), and FLG::x.
Referenced by insert_forall_comm().
emit_get_scalar()
int emit_get_scalar (int a, int std)
This routine is to read distributed array element at forall by using get scalar primitive.
Definition at line 614 of file tools/flang1/flang1exe/comm.c.
References a, A_STDP, add_stmt_before(), ALIGNG, ASD_NDIM, ast, check_member(), dist_ast(), DISTG, DTY, ld, memsym_of_ast(), mk_id(), ndim, new_node(), replace_ast_subtree(), std, STD_LOCAL, sym_get_scalar(), and SYMNAME.
Referenced by get_scalar_in_expr().
emit_overlap()
static void emit_overlap (int a) static
Definition at line 3014 of file tools/flang1/flang1exe/comm.c.
References a, A_STDP, add_stmt_before(), ALIGNG, ARREF_SUB, ASD_NDIM, comminfo::asn, ast, astb, ASTB::bnd, check_member(), cp, dest, ASTB::dtype, comminfo::forall, FT_CSTART_ALLOC, FT_CSTART_COMM, FT_CSTART_FREE, FT_CSTART_INVMVD, FT_CSTART_OUT, FT_CSTART_REF, FT_CSTART_REUSE, FT_CSTART_RHS, FT_CSTART_SAME, FT_CSTART_SECTL, FT_CSTART_SECTR, FT_CSTART_TYPE, FT_CSTART_USEDSTD, FT_CSTART_USELHS, FT_FORALL, FT_HEADER, FT_NRT, FT_RTL, FT_SHIFT_BOUNDARY, FT_SHIFT_FREE, FT_SHIFT_OUT, FT_SHIFT_REUSE, FT_SHIFT_RHS, FT_SHIFT_SAME, FT_SHIFT_TYPE, FT_STD, header(), i, memsym_of_ast(), mk_ftb(), mk_id(), mk_isz_cval(), mk_stmt(), mk_subscr(), mk_triple(), ndim, new_node(), plist(), sptr, comminfo::std, std, STD_AST, SUBI_NOP, SUBI_POP, comminfo::subinfo, sym_get_cp(), sym_get_xfer(), comminfo::usedstd, and xfer().
Referenced by insert_forall_comm().
emit_permute_section()
static int emit_permute_section (int a, int std) static
Definition at line 1900 of file tools/flang1/flang1exe/comm.c.
References a, A_ARGCNTP, add_stmt_before(), argt, ARGT_ARG, ASD_NDIM, assert, astb, ASTB::bnd, BOGUSFLAG, check_member(), copy_section_temp_before(), dest, ASTB::dtype, eliminate_extra_idx(), FALSE, forall_2_sec(), FT_HEADER, func, get_temp_copy_section(), header(), i, is_bogus_forall(), is_ordered(), is_use_lhs_final(), cs_table::is_used_lhs, lhs, list, make_sec_from_ast(), MAXDIMS, mk_argt(), mk_id(), mk_isz_cval(), mk_stmt(), mkRteRtnNm(), nargs, ndim, no, process_rhs_sub(), RTE_permute_section, sectflag, sptr, sptr_of_subscript(), src, std, STD_AST, comminfo::sub, sym_mkfunc(), and TRUE.
Referenced by emit_copy_section().
emit_scatterx()
static void emit_scatterx (int std) static
Definition at line 2551 of file tools/flang1/flang1exe/comm.c.
References SCATTER_TYPE::array, base, SCATTER_TYPE::base, emit_scatterx_gatherx(), SCATTER_TYPE::mask, result, SCATTER_TYPE::result, comminfo::scat, std, and STD_DELETE.
Referenced by is_scatter().
emit_scatterx_gatherx()
static void emit_scatterx_gatherx (int std, int result, int array, int mask, int allocstd, int tempast0, int lhssec, int comm_type) static
Definition at line 2572 of file tools/flang1/flang1exe/comm.c.
References A_ARGCNTP, A_STDP, AD_DPTR, AD_LWAST, AD_UPAST, add_stmt_before(), argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, comminfo::asn, assert, ast, astb, ASTB::bnd, close_pragma(), cp, dest, direct, DT_LOG, ASTB::dtype, FALSE, comminfo::forall, forall_2_sec(), FT_CGATHER_ALLOC, FT_CGATHER_FREE, FT_CGATHER_INDEXREUSE, FT_CGATHER_LHS, FT_CGATHER_LHSSEC, FT_CGATHER_MASK, FT_CGATHER_NOTLHS, FT_CGATHER_NPER, FT_CGATHER_NVEC, FT_CGATHER_NVSUB, FT_CGATHER_OUT, FT_CGATHER_PDIM, FT_CGATHER_PERMUTE, FT_CGATHER_PFLAG, FT_CGATHER_REUSE, FT_CGATHER_RHS, FT_CGATHER_SAME, FT_CGATHER_SECTM, FT_CGATHER_SECTNVSUB, FT_CGATHER_SECTV, FT_CGATHER_SECTVSUB, FT_CGATHER_TYPE, FT_CGATHER_USELHS, FT_CGATHER_V, FT_CGATHER_VDIM, FT_CGATHER_VFLAG, FT_CGATHER_VSUB, FT_CSTART_ALLOC, FT_CSTART_COMM, FT_CSTART_FREE, FT_CSTART_INVMVD, FT_CSTART_OUT, FT_CSTART_REF, FT_CSTART_REUSE, FT_CSTART_RHS, FT_CSTART_SAME, FT_CSTART_SECTL, FT_CSTART_SECTR, FT_CSTART_TYPE, FT_CSTART_USEDSTD, FT_CSTART_USELHS, FT_FORALL, FT_HEADER, FT_NRT, FT_RTL, FT_STD, func, getbit(), header(), i, ASTB::i0, ASTB::i1, is_scalar(), is_vector_subscript(), j, lhs, list, make_sec_ast(), comminfo::mask_phase, memsym_of_ast(), mk_argt(), mk_binop(), mk_convert(), mk_ftb(), mk_id(), mk_isz_cval(), mk_stmt(), mk_subscr(), mk_triple(), mk_unop(), mkRteRtnNm(), new_node(), NOREINDEX, OP_EQ, OP_LNOT, OP_LOR, OP_NE, permute_axis(), pflag, plist(), predicate(), result, RTE_comm_free, RTE_comm_gatherx, RTE_comm_scatterx, sectflag, sptr, std, STD_AST, STD_LINENO, sym_get_cp(), sym_get_xfer(), sym_mkfunc(), TRUE, comminfo::usedstd, and xfer().
Referenced by emit_gatherx(), and emit_scatterx().
emit_sum_scatterx()
static void emit_sum_scatterx (int std) static
Definition at line 2317 of file tools/flang1/flang1exe/comm.c.
References A_ARGCNTP, AD_DPTR, AD_LWAST, AD_UPAST, add_stmt_before(), argt, ARGT_ARG, SCATTER_TYPE::array, SCATTER_TYPE::array_simple, ASD_NDIM, ASD_SUBS, comminfo::asn, assert, astb, base, SCATTER_TYPE::base, ASTB::bnd, check_member(), comminfo, DT_INT, DT_LOG, ASTB::dtype, dtype_to_arg(), comminfo::forall, forall_2_sec(), func, SCATTER_TYPE::function, get_temp_forall(), getbit(), i, is_scalar(), is_vector_subscript(), j, list, make_sec_from_ast(), SCATTER_TYPE::mask, memsym_of_ast(), mk_argt(), mk_cval(), mk_id(), mk_isz_cval(), mk_stmt(), mk_subscr(), mk_triple(), mkRteRtnNm(), name, nargs, NOTSECTFLAG, OP_ADD, OP_LAND, OP_LNEQV, OP_LOR, OP_MUL, SCATTER_TYPE::operator, permute_axis(), pflag, process_forall(), result, SCATTER_TYPE::result, RTE_all_scatterx, RTE_any_scatterx, RTE_iall_scatterx, RTE_iany_scatterx, RTE_iparity_scatterx, RTE_maxval_scatterx, RTE_minval_scatterx, RTE_parity_scatterx, RTE_product_scatterx, RTE_sum_scatterx, comminfo::scat, sectflag, simple_reference_for_temp(), sptr, sptr_of_subscript(), std, STD_AST, STD_DELETE, sym_mkfunc(), and transform_forall().
Referenced by is_scatter().
fix_guard_forall()
static void fix_guard_forall (int std) static
Definition at line 3839 of file tools/flang1/flang1exe/comm.c.
References ASD_NDIM, comminfo::asn, ast, CTYPE::c_dstt, CTYPE::c_dupl, CTYPE::c_idx, FT_CYCLIC, i, left_subscript_ast(), lhs, ndim, std, STD_AST, SUBI_DSTT, SUBI_DUPL, SUBI_IDX, and comminfo::subinfo.
Referenced by transform_forall().
fix_mem_ast()
static int fix_mem_ast (int astmem, int ast) static
Definition at line 3935 of file tools/flang1/flang1exe/comm.c.
References ast, check_member(), and fix_mem_ast().
Referenced by canonical_conversion(), and fix_mem_ast().
forall_2_sec()
static int forall_2_sec (int a, int forall) static
This routine takes an array in a forall statement with its subinfo and replaces all forall indexes.
E.g., forall(i=1:10:2) a(i+1) will become a(2:11:2).
Note that this assumes each forall index appears in array subscripts. If not, something is wrong in the communication detection algorithm.
Definition at line 1207 of file tools/flang1/flang1exe/comm.c.
References a, ASD_NDIM, ASD_SUBS, assert, astb, ASTLI_SPTR, ASTLI_TRIPLE, base, ASTB::bnd, check_member(), ASTB::dtype, FINFO_SHAPE, get_finfo(), i, j, list, mk_subscr(), mk_triple(), ndim, ASTB::one, OP_MUL, opt_binop(), replace_expr(), s, search_forall_idx(), search_idx(), SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, sptr, sptr_of_subscript(), stride, t1, t2, and t3.
Referenced by emit_copy_section(), emit_gatherx(), emit_permute_section(), emit_scatterx_gatherx(), and emit_sum_scatterx().
forall_dependency_scalarize()
static void forall_dependency_scalarize (int std, int * std1, int * std2) static
Definition at line 3876 of file tools/flang1/flang1exe/comm.c.
References add_stmt_after(), add_stmt_before(), comminfo::asn, ast, close_pragma(), DT_LOG, get_temp_forall(), is_dependent(), lhs, lineno, mk_stmt(), open_pragma(), reference_for_temp(), sptr, std, STD_AST, STD_LINENO, and XBIT.
Referenced by scalarize().
forall_opt1()
void forall_opt1 (int ast)
Algorithm:
  gather information about lhs array.
  tag communications for rhs array.
  optimize overlap_shift if there is same array shift.
  optimize copy_section
  convert to forall into block forall since owner computes rule distribution
  for cyclic require complicated statement insertion.
  forall_gbl.s0....
  forall_gbl.s1 forall(i=.
  forall_gbl.s2   A(i)=
  forall_gbl.s3 endforall
  forall_gbl.s4, forall_gbl.s5 ...
These variables are globals.
  forall_gbl.s1 moves up.
  forall_gbl.s4 moves down.
Definition at line 671 of file tools/flang1/flang1exe/comm.c.
References A_STDG, ast, clist(), FT_BARR1, FT_BARR2, FT_CYCLIC, FT_FG, FT_FUSED, FT_FUSELP, FT_HEADER, FT_IGNORE, FT_MCALL, FT_MGET, FT_NFUSE, FT_NMCALL, FT_NMGET, FT_NPCALL, FT_NRT, FT_NSCALL, FT_NSGET, FT_PCALL, FT_RTL, FT_SCALL, FT_SECTL, FT_SGET, getcyclic(), i, j, MAXFUSE, mk_ftb(), and std.
Referenced by copy_arg_to_seq_tmp(), forall_init(), and transform_forall().
free_pertbl()
static void free_pertbl (void) static
Definition at line 2138 of file tools/flang1/flang1exe/comm.c.
References tbl::base, FREE, NULL, and pertbl.
Referenced by comm_fini().
gatherx_temp_before()
static int gatherx_temp_before (int sptr, int rhs, int forall) static
Just like copy_section_temp_before() except it does not eliminate scalar dimension.
This means that it makes a new array with sptr by using subscript of rhs.
Definition at line 1100 of file tools/flang1/flang1exe/comm.c.
References ASD_NDIM, ASD_SUBS, assert, ASTLI_SPTR, DTY, j, k, list, mk_id(), mk_subscr(), ndim, rank_of_sym(), search_forall_idx(), and sptr.
Referenced by emit_gatherx().
get_pertbl()
static int get_pertbl (void) static
Definition at line 2145 of file tools/flang1/flang1exe/comm.c.
References tbl::avl, tbl::base, errfatal(), NEED, NULL, pertbl, tbl::size, and SPTR_MAX.
Referenced by put_data().
getcyclic()
static CTYPE * getcyclic (void) static
Definition at line 3122 of file tools/flang1/flang1exe/comm.c.
References CTYPE::c_dupl, CTYPE::c_inc, CTYPE::c_init, CTYPE::c_lof, CTYPE::cb_block, CTYPE::cb_do, CTYPE::cb_enddo, CTYPE::cb_inc, CTYPE::cb_init, clist(), CTYPE::endifast, FORALL_AREA, getitem(), i, CTYPE::idx, CTYPE::ifast, CTYPE::inner_cyclic, and CTYPE::lhs.
Referenced by forall_opt1().
init_opt_tables()
static void init_opt_tables (void) static
Definition at line 1690 of file tools/flang1/flang1exe/comm.c.
References FALSE, and cs_table::is_used_lhs.
Referenced by transform_forall().
init_pertbl()
static void init_pertbl (void) static
Definition at line 2130 of file tools/flang1/flang1exe/comm.c.
References tbl::avl, tbl::base, NEW, pertbl, and tbl::size.
Referenced by comm_init().
init_region()
void init_region (void)
Keep track of STD of endcritical or endmaster statement.
Definition at line 187 of file tools/flang1/flang1exe/comm.c.
References pure_gbl::end_critical_region, and pure_gbl::end_master_region.
Referenced by call_analyze(), comm_analyze(), convert_forall(), and transform_init().
insert_call_comm()
static void insert_call_comm (int std, int forall) static
Definition at line 3594 of file tools/flang1/flang1exe/comm.c.
References comminfo::forall, FT_MCALL, FT_NMCALL, FT_NSCALL, FT_SCALL, glist(), i, comminfo::mask_phase, put_call_comm(), and std.
Referenced by transform_forall().
insert_endmask()
int insert_endmask (int ast, int stdstart)
Create ENDIF statements corresponding to conditional statements emitted for mask expression ast. Insert the ENDIFs after stdstart. Return the STD of the last statement added.
Definition at line 248 of file tools/flang1/flang1exe/comm.c.
References A_OPTYPEG, add_stmt_after(), ast, insert_endmask(), mk_stmt(), OP_SCAND, and std.
Referenced by conv_forall(), conv_fused_forall(), insert_endmask(), and sequentialize().
insert_forall_comm()
static int insert_forall_comm (int ast) static
Definition at line 1548 of file tools/flang1/flang1exe/comm.c.
References a, A_ARGCNTG, A_OPTYPEG, ALIGNG, argt, ARGT_ARG, ARREF_CLASS, ASD_NDIM, ASD_SUBS, assert, ast, cnt, COPY_SECTION, d, emit_copy_section(), emit_gatherx(), emit_overlap(), FALSE, comminfo::forall, FT_HEADER, FT_NRT, FT_RTL, FT_SHIFT_BOUNDARY, FT_SHIFT_TYPE, GATHER, glist(), header(), i, insert_comm_before(), insert_forall_comm(), interr(), IRREGULAR, is_array_element_in_forall(), lhs, mk_binop(), mk_convert(), mk_member(), mk_paren(), mk_subscr(), mk_unop(), nargs, ndim, NO_COMM, OVERLAP, parent, r, sptr, sptr_of_subscript(), src, comminfo::std, std, and STD_AST.
Referenced by insert_forall_comm(), put_call_comm(), and transform_forall().
insert_mask()
int insert_mask (int ast, int stdstart)
Create mask statements for conditional expression ast and insert them after stdstart. Return the STD of the last statement added.
Definition at line 225 of file tools/flang1/flang1exe/comm.c.
References A_OPTYPEG, add_stmt_after(), ast, insert_mask(), mk_stmt(), OP_SCAND, and std.
Referenced by conv_forall(), conv_fused_forall(), insert_mask(), and sequentialize().
is_bogus_forall()
static LOGICAL is_bogus_forall (int forall) static
Definition at line 1729 of file tools/flang1/flang1exe/comm.c.
References FALSE, and TRUE.
Referenced by emit_copy_section(), and emit_permute_section().
is_permuted()
static LOGICAL is_permuted (int array, int per[7], int per1[7], int * nper1) static
Definition at line 2285 of file tools/flang1/flang1exe/comm.c.
References ASD_NDIM, assert, count, FALSE, i, ndim, and TRUE.
Referenced by permute_axis().
is_same_number_of_idx()
LOGICAL is_same_number_of_idx (int dest, int src, int list)
Definition at line 376 of file tools/flang1/flang1exe/comm.c.
References ASD_NDIM, ASD_SUBS, count, dest, FALSE, j, list, ndim, search_forall_var(), src, and TRUE.
Referenced by is_use_lhs(), and is_use_lhs_final().
is_scatter()
static LOGICAL is_scatter (int std) static
Definition at line 960 of file tools/flang1/flang1exe/comm.c.
References SCATTER_TYPE::array_simple, SCATTER_TYPE::base, emit_scatterx(), emit_sum_scatterx(), FALSE, comminfo::scat, scatter_class(), std, and TRUE.
Referenced by transform_forall().
is_use_lhs()
static LOGICAL is_use_lhs (int a, LOGICAL sameidx, LOGICAL independent, int std) static
Definition at line 1698 of file tools/flang1/flang1exe/comm.c.
References a, DTY, expr_dependent(), FALSE, comminfo::forall, is_same_number_of_idx(), cs_table::is_used_lhs, lhs, list, src, std, comminfo::sub, and TRUE.
Referenced by emit_copy_section(), and emit_gatherx().
make_sec_ast()
static int make_sec_ast (int arr, int std, int allocstd, int sectflag) static
Definition at line 1138 of file tools/flang1/flang1exe/comm.c.
References A_STDP, add_stmt_before(), assert, ast, astb, ASTB::bnd, check_member(), ASTB::dtype, FT_FORALL, FT_HEADER, FT_NRT, FT_RTL, FT_SECT_ALLOC, FT_SECT_ARR, FT_SECT_FLAG, FT_SECT_FREE, FT_SECT_OUT, FT_SECT_REUSE, FT_SECT_SAME, FT_SECT_SPTR, FT_STD, getbit(), header(), is_whole_array(), mk_ftb(), mk_id(), mk_stmt(), new_node(), plist(), rank, sectflag, SHD_NDIM, sptr, sptr_of_subscript(), std, STD_AST, and sym_get_sdescr().
Referenced by emit_copy_section(), emit_gatherx(), and emit_scatterx_gatherx().
normalize_bounds()
LOGICAL normalize_bounds (int sptr)
Return TRUE if the bounds of array sptr should be 1-based with respect to the runtime.
Definition at line 368 of file tools/flang1/flang1exe/comm.c.
References FALSE, sptr, and XBIT.
Referenced by conv_forall(), emit_alnd(), emit_get_scalar_sub(), emit_kopy_in(), emit_secd(), fill_argt_with_alnd(), gen_islocal_index(), gen_localize_index(), generate_get_scalar(), generate_hcycliclp(), generate_hlocalizebnds(), get_allobnds(), inline_hlocalizebnds(), interface_for_entry(), interface_for_llvmiface(), lower_ast(), newargs_for_entry(), and rewrite_func_ast().
normalize_forall_triplet()
static int normalize_forall_triplet (int std, int forall) static
Definition at line 3747 of file tools/flang1/flang1exe/comm.c.
References add_astli(), add_stmt_before(), assert, ast, astb, ASTLI_HEAD, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, ASTB::bnd, dest, DT_ISINT, ASTB::dtype, FALSE, comminfo::forall, insert_comm_before(), is_multiple_idx_in_list(), lb, list, mk_id(), mk_stmt(), mk_triple(), st, start_astli(), std, sym_get_scalar(), and ub.
Referenced by transform_forall().
opt_overlap()
static void opt_overlap (void) static
Definition at line 2954 of file tools/flang1/flang1exe/comm.c.
References ALIGNG, ARREF_ARRSYM, ARREF_CLASS, ARREF_FLAG, ARREF_NDIM, ARREF_NEXT, ARREF_SUB, COMMT_SHIFTC, flg, i, FLG::ipa, ndim, OVERLAP, TRANSFORM::rhsbase, sptr, SUBI_COMMT, SUBI_COMMV, SUBI_NOP, SUBI_POP, comminfo::subinfo, and trans.
Referenced by transform_forall().
permute_axis()
static void permute_axis (int result, int array, int list, int permute[7]) static
Definition at line 2089 of file tools/flang1/flang1exe/comm.c.
References ASD_NDIM, ASD_SUBS, astb, ASTB::bnd, compute_permute(), ASTB::dtype, i, is_permuted(), is_vector_subscript(), list, mk_isz_cval(), mk_subscr(), ndim, put_data(), and result.
Referenced by emit_scatterx_gatherx(), and emit_sum_scatterx().
put_call_comm()
static void put_call_comm (int cstd, int fstd, int forall) static
Definition at line 3614 of file tools/flang1/flang1exe/comm.c.
References A_ARGCNTG, argt, ARGT_ARG, assert, ast, comminfo::forall, FT_CALL_CALL, FT_CALL_NCALL, glist(), i, insert_forall_comm(), nargs, put_call_comm(), STD_AST, and comminfo::usedstd.
Referenced by insert_call_comm(), and put_call_comm().
put_data()
static int put_data (int permute[7], int no) static
Definition at line 2157 of file tools/flang1/flang1exe/comm.c.
References AD_DEFER, AD_DPTR, AD_EXTNTAST, AD_LWAST, AD_LWBD, AD_NOBOUNDS, AD_NUMELM, AD_UPAST, AD_UPBD, assert, astb, tbl::avl, tbl::base, ASTB::bnd, DDTG, DINIT_END, DINIT_LOC, dinit_put(), DT_INT, DTY, ASTB::dtype, TABLE::f1, TABLE::f2, TABLE::f4, FALSE, get_pertbl(), getcon(), i, j, mk_id(), mk_isz_cval(), no, pertbl, sym_get_array(), sym_is_refd(), TRUE, TY_INT8, and val.
Referenced by permute_axis().
record_barrier()
int record_barrier (LOGICAL bBefore, int astStmt, int std)
This routine a barrier statement in the barrier table.
Definition at line 582 of file tools/flang1/flang1exe/comm.c.
References tbl::base, brtbl, clist(), TABLE::f1, TABLE::f2, TABLE::f3, get_brtbl(), i, itemlist::item, sptr, std, and sym_of_ast().
reference_for_temp()
int reference_for_temp (int sptr, int a, int forall)
This routine finds the dimension of sptr.
It takes subscript a(f(i),5,f(j)). It eliminates scalar dimension. It makes an ast for reference sptr: a(f(i),5,f(j)) --> sptr(f(i),f(j))
NOTE: This is always called after get_temp_forall(), which calls mk_forall_sptr(). The subscripts are not always as simple as sptr(f(i),f(j)), especially if the stride is not known. if the stride is not +1 or -1, the subscript will be normalized.
Definition at line 457 of file tools/flang1/flang1exe/comm.c.
References a, ASD_NDIM, ASD_SUBS, assert, ast, astb, ASTLI_SPTR, ASTLI_TRIPLE, c, check_member(), constant_stride(), STB::dt_int, DTY, flg, i, ASTB::i1, interr(), k, list, mk_binop(), mk_id(), mk_subscr(), mk_triple(), ndim, OP_ADD, OP_DIV, OP_SUB, FLG::opt, other_forall_var(), rank_of_sym(), search_forall_var(), sptr, stb, stride, STB::user, value(), and XBIT.
Referenced by forall_dependency(), and forall_dependency_scalarize().
remove_section()
static void remove_section (int ast, int * pnewast, int * psectast, int * psptr, int * panydist, int * pnontrivial) static
Definition at line 1291 of file tools/flang1/flang1exe/comm.c.
References ALIGNG, ast, mk_member(), mk_subscr_copy(), mk_substr(), remove_section(), and sptr.
Referenced by remove_section(), and transform_ptr().
report_comm()
void report_comm (int std, int cause)
Dump compiler internal information for the communication analyzer.
Definition at line 267 of file tools/flang1/flang1exe/comm.c.
References assert, CANONICAL_CAUSE, ccff_info(), COPYSCALAR_CAUSE, COPYSECTION_CAUSE, DEPENDENCY_CAUSE, GETSCALAR_CAUSE, INTRINSIC_CAUSE, MANYRUNTIME_CAUSE, MSGFTN, NULL, PURECOMM_CAUSE, std, STD_AST, STD_LINENO, STD_MINFO, UGLYCOMM_CAUSE, UGLYMASK_CAUSE, UGLYPURE_CAUSE, and XBIT.
Referenced by emit_get_scalar_sub(), forall_dependency(), generate_get_scalar(), and transform_forall().
scalar_communication()
static int scalar_communication (int ast, int std) static
Definition at line 4147 of file tools/flang1/flang1exe/comm.c.
References a, A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, ast, d, FALSE, comminfo::forall, FT_HEADER, header(), i, insert_comm_before(), interr(), is_array_element_in_forall(), mk_binop(), mk_convert(), mk_member(), mk_paren(), mk_subscr(), mk_triple(), mk_unop(), nargs, ndim, r, scalar_communication(), std, and STD_AST.
Referenced by scalar_communication(), and transform_forall().
scalarize()
void scalarize (int std, int forall, LOGICAL after_transformer)
The forall should be treated like a serial statement.
Turn it into a block-forall so the IF stuff works OK.
Definition at line 810 of file tools/flang1/flang1exe/comm.c.
References forall_dependency_scalarize(), sequentialize(), std, STD_AST, and transform_forall().
Referenced by copy_arg_to_seq_tmp(), forall_semantic(), and transform_forall().
sequentialize()
void sequentialize (int std, int forall, LOGICAL after_transformer)
Definition at line 860 of file tools/flang1/flang1exe/comm.c.
References A_STDG, add_stmt_before(), ast_to_comment(), ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, delete_stmt(), i, index_var, insert_endmask(), insert_mask(), lineno, mk_id(), mk_stmt(), n, sequentialize_mask_call(), sequentialize_stmt_call(), std, STD_AST, STD_LINENO, STD_NEXT, STD_PREV, transform_ast(), and un_fuse().
Referenced by process_forall(), and scalarize().
sequentialize_call()
static int sequentialize_call (int cstd, int stdnext, int forall) static
Definition at line 3714 of file tools/flang1/flang1exe/comm.c.
References add_stmt_before(), assert, ast, delete_stmt(), comminfo::forall, FT_CALL_CALL, FT_CALL_NCALL, glist(), i, lineno, sequentialize_call(), STD_AST, STD_LINENO, STD_NEXT, and transform_ast().
Referenced by sequentialize_call(), sequentialize_mask_call(), and sequentialize_stmt_call().
sequentialize_mask_call()
static int sequentialize_mask_call (int forall, int stdnext) static
Definition at line 3684 of file tools/flang1/flang1exe/comm.c.
References comminfo::forall, FT_MCALL, FT_NMCALL, glist(), i, and sequentialize_call().
Referenced by sequentialize().
sequentialize_stmt_call()
static int sequentialize_stmt_call (int forall, int stdnext) static
Definition at line 3699 of file tools/flang1/flang1exe/comm.c.
References comminfo::forall, FT_NSCALL, FT_SCALL, glist(), i, and sequentialize_call().
Referenced by sequentialize().
shape_comm()
static void shape_comm (int cstd, int fstd, int forall) static
Definition at line 3260 of file tools/flang1/flang1exe/comm.c.
References A_ARGCNTG, arg, argt, ARGT_ARG, assert, ast, convert_subscript(), comminfo::forall, FT_CALL_CALL, FT_CALL_NCALL, glist(), i, lhs, nargs, shape_comm(), and STD_AST.
Referenced by shape_comm(), and shape_communication().
shape_comm_in_expr()
static int shape_comm_in_expr (int expr, int forall, int std, int nomask) static
Definition at line 3147 of file tools/flang1/flang1exe/comm.c.
References A_ARGCNTG, A_OPTYPEG, argt, ARGT_ARG, convert_subscript(), d, comminfo::forall, i, interr(), lhs, mk_binop(), mk_convert(), mk_member(), mk_paren(), mk_unop(), nargs, r, shape_comm_in_expr(), sptr, and std.
Referenced by shape_comm_in_expr(), and shape_communication().
shape_communication()
static void shape_communication (int std, int forall) static
Definition at line 3228 of file tools/flang1/flang1exe/comm.c.
References comminfo::asn, comminfo::forall, FT_MCALL, FT_NMCALL, FT_NSCALL, FT_SCALL, glist(), i, shape_comm(), shape_comm_in_expr(), and std.
Referenced by transform_forall().
simple_reference_for_temp()
static int simple_reference_for_temp (int sptr, int a, int forall) static
Like reference_for_temp(), this routine finds the dimension of sptr.
It takes subscript a(f(i),5,f(j)). It eliminates scalar dimensions. It makes an ast to reference sptr: a(f(i),5,f(j)) --> sptr(i,j)
Definition at line 978 of file tools/flang1/flang1exe/comm.c.
References a, ASD_NDIM, ASD_SUBS, assert, ast, ASTLI_SPTR, DTY, i, interr(), k, list, mk_id(), mk_subscr(), ndim, rank_of_sym(), search_forall_var(), sptr, and XBIT.
Referenced by emit_sum_scatterx().
sub_lbnd()
int sub_lbnd (int dtyp, int dim, int ast, int astmember)
Construct an AST to subtract the lower bound of dimension dim for array datatype dtyp to ast, and return the new AST.
Definition at line 350 of file tools/flang1/flang1exe/comm.c.
References ADD_LWAST, ast, astb, ASTB::bnd, check_member(), dim, ASTB::dtype, mk_binop(), ASTB::one, OP_ADD, and OP_SUB.
Referenced by conv_forall(), emit_get_scalar_sub(), gen_islocal_index(), gen_localize_index(), generate_get_scalar(), generate_hcycliclp(), and generate_hlocalizebnds().
tag_call_comm()
static int tag_call_comm (int std, int forall) static
Definition at line 3641 of file tools/flang1/flang1exe/comm.c.
References call_comm(), comminfo::forall, FT_MCALL, FT_NMCALL, FT_NSCALL, FT_SCALL, glist(), i, comminfo::mask_phase, and std.
Referenced by transform_forall().
temp_copy_section()
static int temp_copy_section (int std, int forall, int lhs, int rhs, int dty, int * allocast) static
Definition at line 1062 of file tools/flang1/flang1exe/comm.c.
References ast, DTY, FT_ALLOC_FREE, FT_ALLOC_OUT, FT_ALLOC_REUSE, FT_ALLOC_SAME, FT_ALLOC_SPTR, FT_ALLOC_USED, FT_FORALL, FT_HEADER, FT_STD, header(), lhs, mk_forall_sptr_copy_section(), mk_ftb(), mk_id(), mk_subscr(), new_node(), rank_of_sym(), sptr, std, and subscr.
Referenced by emit_copy_section().
temp_gatherx()
static int temp_gatherx (int std, int forall, int lhs, int rhs, int dty, int * allocast) static
Definition at line 1030 of file tools/flang1/flang1exe/comm.c.
References ast, DTY, FT_ALLOC_FREE, FT_ALLOC_OUT, FT_ALLOC_REUSE, FT_ALLOC_SAME, FT_ALLOC_SPTR, FT_ALLOC_USED, FT_FORALL, FT_HEADER, FT_STD, header(), lhs, mk_forall_sptr_gatherx(), mk_ftb(), mk_id(), mk_subscr(), new_node(), rank_of_sym(), sptr, std, and subscr.
Referenced by emit_gatherx().
transform_forall()
void transform_forall (int std, int ast)
Definition at line 710 of file tools/flang1/flang1exe/comm.c.
References ast, CANONICAL_CAUSE, canonical_conversion(), dest, pure_gbl::end_critical_region, fix_guard_forall(), comminfo::forall, forall_opt1(), FT_NRT, init_opt_tables(), insert_call_comm(), insert_forall_comm(), is_scatter(), MANYRUNTIME_CAUSE, comminfo::mask_phase, normalize_forall_triplet(), opt_overlap(), process_lhs_sub(), report_comm(), TRANSFORM::rhsbase, scalar_communication(), scalarize(), shape_communication(), src, comminfo::std, std, STD_AST, tag_call_comm(), tag_forall_comm(), trans, TRUE, comminfo::ugly_mask, UGLYCOMM_CAUSE, UGLYMASK_CAUSE, comminfo::unstruct, and comminfo::usedstd.
Referenced by comm_analyze(), copy_arg_to_seq_tmp(), emit_sum_scatterx(), and scalarize().
transform_ptr()
static void transform_ptr (int std, int ast) static
Definition at line 1370 of file tools/flang1/flang1exe/comm.c.
References A_ARGCNTG, A_ARGCNTP, A_OPTYPEG, argt, ARGT_ARG, ASD_SUBS, assert, ast, astb, ASTB::bnd, bnds_remap_list(), check_member(), d, DDTG, dest, DTY, DTYG, ASTB::dtype, dtype_to_arg(), emit_alnd_secd(), error(), find_pointer_variable(), first_element(), getcon(), i, make_sec_from_ast(), mk_argt(), mk_cnst(), mk_id(), mk_isz_cval(), nargs, ASTB::one, remove_section(), SHD_NDIM, simply_contiguous(), size_of(), src, std, STD_LINENO, sub, SYMNAME, tmp, TRUE, ty_to_lib, val, and ASTB::zero.
Referenced by comm_analyze().
un_fuse()
void un_fuse (int forall)
This is necessary, if forall sequentialized.
Definition at line 837 of file tools/flang1/flang1exe/comm.c.
References A_STDG, assert, FT_FUSEDSTD, FT_HEADER, FT_NFUSE, i, and STD_AST.
Referenced by forall_dependency(), and sequentialize().
Variable Documentation
cs_table
struct cs_table cs_table static
Definition at line 38 of file tools/flang1/flang1exe/comm.c.