flang: hash.c File Reference
tools/flang1/flang1exe/hash.c File Reference
Open addressing, quadratically probed hash tables.
#include "flang/ADT/hash.h"
#include "flang/Error/pgerror.h"
#include <stdlib.h>
#include <string.h>
Classes
struct hashset_
struct hashmap_
A hashmap adds a table of data pointers after the hashset table.
struct sortmap_t
Macros
#define ERASED (hash_key_t) ~0UL
#define LONG long
#define ISKEY(k) ((k) != NULL && (k) != ERASED)
#define DTABLE(h) (((h)->table + 1) + (h)->mask)
#define NEED_REHASH(h) ((h)->entries + (h)->erased >= (h)->mask - (h)->mask / 8)
#define MINSIZE 16
Functions
static unsigned search (hashset_t h, hash_key_t key)
Search for key, return index that terminated the search.
static unsigned insertion_point (hashset_t h, hash_key_t key)
Find insertion point for key.
static unsigned mask_for_entries (unsigned n)
static void alloc_tables (hashset_t h, int with_dtable)
static void rehash (hashset_t h, int with_dtable)
hashset_t hashset_alloc (hash_functions_t f)
Allocate a hashset which uses the provided functions to interpret keys.
hashmap_t hashmap_alloc (hash_functions_t f)
Allocate a hashmap.
void hashset_free (hashset_t h)
Free all memory used by a hashset.
void hashmap_free (hashmap_t h)
Free all memory used by a hashmap.
void hashset_clear (hashset_t h)
Erase all keys in the set.
void hashmap_clear (hashmap_t h)
Erase all (key, data) entries in the map.
unsigned hashset_size (hashset_t h)
Get the number of keys in the set.
unsigned hashmap_size (hashmap_t h)
Return the number of (key, data) pairs in the map.
hash_key_t hashset_lookup (hashset_t h, hash_key_t key)
Look up a key and return the equivalent stored key, or NULL.
hash_key_t hashmap_lookup (hashmap_t h, hash_key_t key, hash_data_t *data)
Look up a key and return the equivalent stored key, or NULL.
void hashset_insert (hashset_t h, hash_key_t key)
Insert a new key.
void hashmap_insert (hashmap_t h, hash_key_t key, hash_data_t data)
Insert a new (key, data) pair.
hash_key_t hashset_replace (hashset_t h, hash_key_t key)
Insert a new key or replace an existing key.
hash_key_t hashmap_replace (hashmap_t h, hash_key_t key, hash_data_t *data)
Insert or replace a (key, data) pair.
hash_key_t hashset_erase (hashset_t h, hash_key_t key)
Erase a key from the set and return it.
hash_key_t hashmap_erase (hashmap_t h, hash_key_t key, hash_data_t *data)
Erase a key from the map and return it.
void hashset_iterate (hashset_t h, void(*f)(hash_key_t, void *context), void *context)
Call f with every key in the hash set.
static int string_cmp (sortmap_t *a, sortmap_t *b)
void hashmap_sort (hashmap_t h, void(*f)(hash_key_t, hash_data_t, void *context), void *context)
void hashmap_iterate (hashmap_t h, void(*f)(hash_key_t, hash_data_t, void *context), void *context)
Call f with every (key, data) pair in the hash map.
static hash_value_t string_hash (hash_key_t key)
static int string_equals (hash_key_t a, hash_key_t b)
static hash_value_t direct_hash (hash_key_t key)
Variables
const hash_functions_t hash_functions_strings = {string_hash, string_equals}
Predefined hash functions for strings.
const hash_functions_t hash_functions_direct = {direct_hash, NULL}
Predefined hash functions for directly hashed keys.
Detailed Description
Open addressing, quadratically probed hash tables.
All keys are kept in a single array with 2^n entries. A key is first looked up at index hash(k) mod 2^k, then following a quadratic sequence of offsets. The quadratic probing has decent locality of reference for the first few probes.
The search terminates when the key is found or a NULL is encountered. A special ERASED marker is used to avoid severing probe sequences when erasing keys.
Definition in file tools/flang1/flang1exe/hash.c.
Macro Definition Documentation
DTABLE
#define DTABLE (h) (((h)->table + 1) + (h)->mask)
Definition at line 61 of file tools/flang1/flang1exe/hash.c.
ERASED
#define ERASED (hash_key_t) ~0UL
Definition at line 37 of file tools/flang1/flang1exe/hash.c.
ISKEY
#define ISKEY (k) ((k) != NULL && (k) != ERASED)
Definition at line 40 of file tools/flang1/flang1exe/hash.c.
LONG
#define LONG long
Definition at line 38 of file tools/flang1/flang1exe/hash.c.
MINSIZE
#define MINSIZE 16
Definition at line 151 of file tools/flang1/flang1exe/hash.c.
NEED_REHASH
#define NEED_REHASH (h) ((h)->entries + (h)->erased >= (h)->mask - (h)->mask / 8)
Definition at line 150 of file tools/flang1/flang1exe/hash.c.
Function Documentation
alloc_tables()
static void alloc_tables (hashset_t h, int with_dtable) static
Definition at line 173 of file tools/flang1/flang1exe/hash.c.
References h, and mask_for_entries().
Referenced by hashmap_alloc(), hashmap_clear(), hashset_alloc(), hashset_clear(), and rehash().
direct_hash()
static hash_value_t direct_hash (hash_key_t key) static
Definition at line 498 of file tools/flang1/flang1exe/hash.c.
References HASH_ACCU_ADD, HASH_ACCU_FINISH, HASH_ACCU_INIT, HASH_ACCU_VALUE, k, and LONG.
hashmap_alloc()
hashmap_t hashmap_alloc (hash_functions_t f)
Allocate a hashmap.
The returned handle must be freed with hashmap_free().
Definition at line 227 of file tools/flang1/flang1exe/hash.c.
References alloc_tables(), f, and h.
Referenced by add_sincos_map(), build_kmpc_api_name(), cg_llvm_init(), create_action_map(), create_arg_parser(), gen_llvm_sincos_call(), gen_llvm_vsincos_call(), ll_create_module(), ll_proto_init(), lldbg_emit_subprogram(), redundantLdLdElim(), use_hash_alloc(), and widenAddressArith().
hashmap_clear()
void hashmap_clear (hashmap_t h)
Erase all (key, data) entries in the map.
Definition at line 260 of file tools/flang1/flang1exe/hash.c.
References alloc_tables(), and h.
Referenced by ll_reset_module_types(), lldbg_cleanup_missing_bounds(), process_global_lifetime_debug(), redundantLdLdElim(), schedule(), sincos_clear_all_args(), and use_hash_free().
hashmap_erase()
hash_key_t hashmap_erase (hashmap_t h, hash_key_t key, hash_data_t * data)
Erase a key from the map and return it.
If a (key, data) pair was erased and data is not NULL, update *data with the erased data value.
If no key was erased, return NULL and leave *data unchanged.
Definition at line 385 of file tools/flang1/flang1exe/hash.c.
References DTABLE, ERASED, h, i, NULL, and search().
Referenced by ll_remove_struct_type(), lldbg_create_aggregate_members_type(), lldbg_create_ftn_subrange_via_sdsc(), lldbg_emit_global_variable(), lldbg_emit_local_variable(), and sincos_clear_arg_helper().
hashmap_free()
void hashmap_free (hashmap_t h)
Free all memory used by a hashmap.
Note that any memory referenced by keys and data pointers in the map is not freed.
Definition at line 244 of file tools/flang1/flang1exe/hash.c.
References h.
Referenced by destroy_action_map(), destroy_arg_parser(), ll_destroy_module(), redundantLdLdElim(), remove_dead_sincos_calls(), use_hash_free(), and widenAddressArith().
hashmap_insert()
void hashmap_insert (hashmap_t h, hash_key_t key, hash_data_t data)
Insert a new (key, data) pair.
This function assumes that no equivalent key is present in the map, i.e. hashmap_lookup() would return NULL.
Use hashmap_replace() if an equivalent key may exist in the map already.
Definition at line 315 of file tools/flang1/flang1exe/hash.c.
References assert, DTABLE, ERASED, ERR_Fatal, h, hashmap_lookup(), i, insertion_point(), NEED_REHASH, NULL, and rehash().
Referenced by add_action(), add_generic_argument(), build_kmpc_api_name(), copy_action(), get_intrinsic(), hashmap_replace(), intern_constant(), ll_add_global_debug(), ll_add_module_debug(), ll_get_md_node(), ll_proto_add(), lldbg_fwd_local_variable(), process_formal_arguments(), and redundantLdLdElim().
hashmap_iterate()
void hashmap_iterate (hashmap_t h, void(*)(hash_key_t, hash_data_t, void *context) f, void * context)
Call f with every (key, data) pair in the hash map.
The function f must not modify the hash table.
Definition at line 463 of file tools/flang1/flang1exe/hash.c.
References f, h, ISKEY, n, and size.
Referenced by destroy_arg_parser(), lldbg_cleanup_missing_bounds(), redundantLdLdElim(), sincos_clear_specific_arg(), use_hash_dump(), and widenAddressArith().
hashmap_lookup()
hash_key_t hashmap_lookup (hashmap_t h, hash_key_t key, hash_data_t * data)
Look up a key and return the equivalent stored key, or NULL.
If if a key was found and data is not NULL, *data will be set to the corresponding data value, otherwise it is not changed.
Definition at line 286 of file tools/flang1/flang1exe/hash.c.
References DTABLE, h, i, k, and search().
Referenced by add_action(), add_generic_argument(), add_sincos_map(), build_kmpc_api_name(), cleanup_unneeded_sincos_calls(), copy_action(), execute_actions_for_keyword(), get_intrinsic(), get_last_sincos(), hashmap_insert(), insert_jump_entry_instr(), intern_constant(), ll_add_global_debug(), ll_add_module_debug(), ll_get_global_debug(), ll_get_md_node(), ll_get_module_debug(), ll_get_struct_type(), ll_named_struct_type_exists(), ll_proto_add(), ll_proto_get_abi(), ll_proto_has_defined_body(), ll_proto_is_weak(), ll_proto_set_abi(), ll_proto_set_defined_body(), ll_proto_set_intrinsic(), ll_proto_set_weak(), lldbg_create_aggregate_members_type(), lldbg_emit_global_variable(), lldbg_emit_local_variable(), lldbg_emit_subprogram(), lldbg_fwd_local_variable(), parse_arguments(), print_function_signature(), process_auto_sptr(), process_sptr_offset(), redundantLdLdElim(), remove_dead_sincos_calls(), rlleReplace(), sincos_argument_valid(), use_hash_lookup(), widenApplyCse(), widenApplyFree(), widenApplyStore(), and widenApplyVarMap().
hashmap_replace()
hash_key_t hashmap_replace (hashmap_t h, hash_key_t key, hash_data_t * data)
Insert or replace a (key, data) pair.
If an equivalent key already exists, replace it with the new key and *data, and return the old key. On return, *data is set to the old data.
If no equivalent key is present, insert the new key and *data and return NULL. The *data value is not updated.
Definition at line 350 of file tools/flang1/flang1exe/hash.c.
References DTABLE, h, hashmap_insert(), i, ISKEY, NULL, and search().
Referenced by add_sincos_imap(), add_sincos_imap_loads(), add_sincos_map(), gatherLocals(), ll_create_named_struct_type(), ll_finish_variable(), lldbg_emit_subprogram(), redundantLdLdElim(), rlleFindLL(), use_hash_insert(), widenProcessDirectLoad(), and widenProcessIndirectLoad().
hashmap_size()
unsigned hashmap_size (hashmap_t h)
Return the number of (key, data) pairs in the map.
Definition at line 274 of file tools/flang1/flang1exe/hash.c.
References h.
Referenced by lldbg_cleanup_missing_bounds(), and redundantLdLdElim().
hashmap_sort()
void hashmap_sort (hashmap_t h, void(*)(hash_key_t, hash_data_t, void *context) f, void * context)
Definition at line 427 of file tools/flang1/flang1exe/hash.c.
References count, sortmap_t::dtable, f, h, i, ISKEY, malloc(), n, size, string_cmp(), table, and sortmap_t::table.
hashset_alloc()
hashset_t hashset_alloc (hash_functions_t f)
Allocate a hashset which uses the provided functions to interpret keys.
The returned hashset_t handle should be passed to hashset_free() to deallocate memory.
Definition at line 218 of file tools/flang1/flang1exe/hash.c.
References alloc_tables(), f, and h.
Referenced by add_debug_cmnblk_variables(), create_arg_parser(), dinits(), ll_create_local_name(), ll_create_local_object(), ll_create_module(), lldbg_emit_imported_entity(), print_entry_subroutine(), redundantLdLdElim(), verify_all_blocks(), widenAddressArith(), and widenPruneAcon().
hashset_clear()
void hashset_clear (hashset_t h)
Erase all keys in the set.
Definition at line 252 of file tools/flang1/flang1exe/hash.c.
References alloc_tables(), and h.
Referenced by dinits(), parse_arguments(), print_entry_subroutine(), and verify_all_blocks().
hashset_erase()
hash_key_t hashset_erase (hashset_t h, hash_key_t key)
Erase a key from the set and return it.
Return NULL if no equivalent key was found.
Definition at line 370 of file tools/flang1/flang1exe/hash.c.
References ERASED, h, i, NULL, and search().
Referenced by widenElimAddrTaken().
hashset_free()
void hashset_free (hashset_t h)
Free all memory used by a hashset.
Note that any memory referenced by keys in the set is not freed.
Definition at line 236 of file tools/flang1/flang1exe/hash.c.
References h.
Referenced by ll_destroy_function(), ll_destroy_module(), print_entry_subroutine(), redundantLdLdElim(), verify_all_blocks(), widenAddressArith(), and widenPruneAcon().
hashset_insert()
void hashset_insert (hashset_t h, hash_key_t key)
Insert a new key.
Note that this function assumes that no equivalent key is present in the set, i.e. hashset_lookup() would return false.
Use hashset_replace() if an equivalent key may be in the set already.
The key cannot be NULL or (hash_key_t)~0UL.
Definition at line 296 of file tools/flang1/flang1exe/hash.c.
References assert, ERASED, ERR_Fatal, h, hashset_lookup(), i, insertion_point(), NEED_REHASH, NULL, and rehash().
Referenced by add_debug_cmnblk_variables(), hashset_replace(), lldbg_emit_imported_entity(), print_entry_subroutine(), rlleMakeSet(), unique_name(), and unique_type().
hashset_iterate()
void hashset_iterate (hashset_t h, void(*)(hash_key_t, void *context) f, void * context)
Call f with every key in the hash set.
Note that the iteration order is a function of both the hash function and the sequence of hashset_* calls leading up to this one. If pointers are directly hashed, address space layout randomization can cause different iteration orders in otherwise identical executions.
The function f must not modify the hash table.
Definition at line 402 of file tools/flang1/flang1exe/hash.c.
References f, for(), h, ISKEY, n, and size.
Referenced by dump_all_dinits(), ll_destroy_function(), verify_all_blocks(), widenAddressArith(), and widenPruneAcon().
hashset_lookup()
hash_key_t hashset_lookup (hashset_t h, hash_key_t key)
Look up a key and return the equivalent stored key, or NULL.
Definition at line 280 of file tools/flang1/flang1exe/hash.c.
References h, and search().
Referenced by add_debug_cmnblk_variables(), hashset_insert(), ll_named_struct_type_exists(), lldbg_emit_imported_entity(), print_entry_subroutine(), pruneAcon(), rlleFindLL(), unique_name(), unique_type(), was_value_set(), and widenElimAddrTaken().
hashset_replace()
hash_key_t hashset_replace (hashset_t h, hash_key_t key)
Insert a new key or replace an existing key.
If an equivalent key already exists, replace it with the new key and return the old one. If no equivalent key is in the set, insert the new key and return NULL.
Definition at line 335 of file tools/flang1/flang1exe/hash.c.
References h, hashset_insert(), i, ISKEY, NULL, and search().
Referenced by add_generic_argument(), collect_referenced_locals(), dinits(), parse_arguments(), pruneAcon(), widenAddNarrowVars(), and widenGatherAcon().
hashset_size()
unsigned hashset_size (hashset_t h)
Get the number of keys in the set.
Definition at line 268 of file tools/flang1/flang1exe/hash.c.
References h.
Referenced by unique_name(), and widenAddressArith().
insertion_point()
static unsigned insertion_point (hashset_t h, hash_key_t key) static
Find insertion point for key.
Definition at line 128 of file tools/flang1/flang1exe/hash.c.
References assert, ERR_Fatal, h, HKEY2INT, ISKEY, p, and s.
Referenced by hashmap_insert(), hashset_insert(), and rehash().
mask_for_entries()
static unsigned mask_for_entries (unsigned n) static
Definition at line 154 of file tools/flang1/flang1exe/hash.c.
References assert, ERR_Fatal, m, MINSIZE, and n.
Referenced by alloc_tables().
rehash()
static void rehash (hashset_t h, int with_dtable) static
Definition at line 191 of file tools/flang1/flang1exe/hash.c.
References alloc_tables(), DTABLE, h, i, insertion_point(), ISKEY, n, and NULL.
Referenced by hashmap_insert(), and hashset_insert().
search()
static unsigned search (hashset_t h, hash_key_t key) static
Search for key, return index that terminated the search.
Definition at line 98 of file tools/flang1/flang1exe/hash.c.
References assert, ERASED, ERR_Fatal, h, HKEY2INT, ISKEY, p, and s.
Referenced by hashmap_erase(), hashmap_lookup(), hashmap_replace(), hashset_erase(), hashset_lookup(), and hashset_replace().
string_cmp()
static int string_cmp (sortmap_t * a, sortmap_t * b) static
Definition at line 421 of file tools/flang1/flang1exe/hash.c.
References a, and b.
Referenced by hashmap_sort().
string_equals()
static int string_equals (hash_key_t a, hash_key_t b) static
Definition at line 489 of file tools/flang1/flang1exe/hash.c.
References a, and b.
string_hash()
static hash_value_t string_hash (hash_key_t key) static
Definition at line 478 of file tools/flang1/flang1exe/hash.c.
References HASH_ACCU_ADD, HASH_ACCU_FINISH, HASH_ACCU_INIT, HASH_ACCU_VALUE, and p.
Variable Documentation
hash_functions_direct
const hash_functions_t hash_functions_direct = {direct_hash, NULL}
Predefined hash functions for directly hashed keys.
The pointers are compared by value with no indirection. These hash functions can also be used for integer keys. Just cast the integers to hash_key_t.
Definition at line 512 of file tools/flang1/flang1exe/hash.c.
Referenced by add_sincos_map(), cg_llvm_init(), create_arg_parser(), dinits(), gen_llvm_sincos_call(), gen_llvm_vsincos_call(), ll_create_module(), lldbg_emit_subprogram(), print_entry_subroutine(), redundantLdLdElim(), use_hash_alloc(), verify_all_blocks(), widenAddressArith(), and widenPruneAcon().
hash_functions_strings
const hash_functions_t hash_functions_strings = {string_hash, string_equals}
Predefined hash functions for strings.
The hash keys are interpreted as pointers to NUL-terminated strings.
Definition at line 494 of file tools/flang1/flang1exe/hash.c.
Referenced by add_debug_cmnblk_variables(), build_kmpc_api_name(), cg_llvm_init(), create_action_map(), create_arg_parser(), ll_create_local_name(), ll_create_local_object(), ll_create_module(), ll_proto_init(), and lldbg_emit_imported_entity().