flang: error.c File Reference
tools/shared/error.c File Reference
Error handling and reporting module.
#include "error.h"
#include "global.h"
#include "version.h"
#include "main.h"
#include "symtab.h"
#include <stdarg.h>
#include "errmsgdf.h"
Macros
#define ERRMSG_GET_ERRTXT_TABLE 1
Functions
static char * errfill (const char *intxt, const char *op1, const char *op2)
Expand error message template: replace '$' with text of the other two operands.
static void display_error (error_code_t ecode, enum error_severity sev, int eline, const char *op1, const char *op2, int col, const char *srcFile)
void errini (void)
Initialize error counts for new user subprogram.
void errversion (void)
Print version info.
void error (error_code_t ecode, enum error_severity sev, int eline, const char *op1, const char *op2)
Construct and issue an error message.
void errlabel (error_code_t ecode, enum error_severity sev, int eline, char *nm, const char *op2)
Massage label name if necesseary.
void interrf (enum error_severity sev, const char *fmt,...)
Issue internal compiler error using printf-style formatting.
void interr (const char *txt, int val, enum error_severity sev)
Assert that cond is true, and emit an internal compiler error otherwise.
char * errnum (int num)
Convert an integer to a string, for printing numbers in error messages.
void errinfo (error_code_t ecode)
Issue an informational message for gbl.lineno.
void errwarn (error_code_t ecode)
Issue a warning for gbl.lineno.
void errsev (error_code_t ecode)
Issue a severe error message for gbl.lineno.
void errfatal (error_code_t ecode)
Issue a fatal error for gbl.lineno.
int summary (bool final, int ipafollows)
void erremit (int x)
Set the emit error flag(s)
void fperror (int errcode)
Floating point error.
enum error_severity error_max_severity (void)
...
Variables
static int ndiags [ERR_SEVERITY_SIZE]
static enum error_severity maxfilsev
static int totaldiags = 0
static int emit_errmsg = 1
Detailed Description
Error handling and reporting module.
Definition in file tools/shared/error.c.
Macro Definition Documentation
ERRMSG_GET_ERRTXT_TABLE
#define ERRMSG_GET_ERRTXT_TABLE 1
Definition at line 24 of file tools/shared/error.c.
Function Documentation
display_error()
static void display_error (error_code_t ecode, enum error_severity sev, int eline, const char * op1, const char * op2, int col, const char * srcFile) static
Definition at line 108 of file tools/shared/error.c.
References buff, FLG::code, col, FLG::dbg, DBGBIT, dump_stg_stat(), emit_errmsg, ERR_Fatal, ERR_Informational, ERR_Severe, ERR_Warning, errfatal(), errfill(), FLG::errorlimit, errtxt, finish(), flg, gbl, FLG::inform, FLG::list, list_line(), maxfilsev, ndiags, NULL, totaldiags, version, XBIT, and FLG::xref.
Referenced by error().
erremit()
void erremit (int x)
Set the emit error flag(s)
Definition at line 353 of file tools/shared/error.c.
References emit_errmsg, and x.
Referenced by apply_use(), and open_module().
errfatal()
void errfatal (error_code_t ecode)
Issue a fatal error for gbl.lineno.
Definition at line 320 of file tools/shared/error.c.
References CNULL, ERR_Fatal, error(), and gbl.
Referenced by accpp(), add_astli(), apply_use(), dinit(), dinit_put(), display_error(), end_module(), finish(), fpp(), get_brtbl(), get_gstbl(), get_pertbl(), get_tbl(), init(), ll_open_parfiles(), mk_argt(), mk_dtb(), mk_finfo(), mk_ftb(), mk_std(), new_node(), push_include(), put_data_statement(), reset_module_state(), restore_host_state(), restore_module_state(), rw_dinit_state(), save_host_state(), save_imported_modules_state(), save_module_state1(), scan_include(), scan_init(), sccalloc(), sccrelal(), symini_errfatal(), write_comm(), and xrefinit().
errfill()
static char * errfill (const char * intxt, const char * op1, const char * op2) static
Expand error message template: replace '$' with text of the other two operands.
Parameters
intxt error message template
op1 first operand for substitution
op2 second operand for substitution
Returns
pointer to result
Definition at line 43 of file tools/shared/error.c.
References NULL, p, and strlen().
Referenced by display_error().
errinfo()
void errinfo (error_code_t ecode)
Issue an informational message for gbl.lineno.
Definition at line 302 of file tools/shared/error.c.
References CNULL, ERR_Informational, error(), and gbl.
Referenced by cngcon().
errini()
void errini (void)
Initialize error counts for new user subprogram.
Definition at line 209 of file tools/shared/error.c.
References gbl, ndiags, and totaldiags.
Referenced by init(), parser(), and reinit().
errlabel()
void errlabel (error_code_t ecode, enum error_severity sev, int eline, char * nm, const char * op2)
Massage label name if necesseary.
Parameters
ecode error number
sev error severity in range 1 ... 4
eline source file line number
nm label name
op2 extra string
Definition at line 230 of file tools/shared/error.c.
References error().
Referenced by _read_token(), exp_label(), ff_get_label(), get_stmt(), semant1(), and semfin().
errnum()
char * errnum (int num)
Convert an integer to a string, for printing numbers in error messages.
This returns a pointer to static data, so only use it once.
Definition at line 294 of file tools/shared/error.c.
References n, and num.
error()
void error (error_code_t ecode, enum error_severity sev, int eline, const char * op1, const char * op2)
Construct and issue an error message.
Parameters
ecode error number
sev error severity (a value in the err_severity enum)
eline source file line number
op1 string to be expanded into error message * or 0
op2 string to be expanded into error message * or 0
Construct error message and issue it to user terminal and to listing file if appropriate.
Definition at line 223 of file tools/shared/error.c.
References display_error(), and NULL.
Referenced by errfatal(), errinfo(), errlabel(), errsev(), errwarn(), and interrf().
error_max_severity()
enum error_severity error_max_severity (void)
...
Definition at line 398 of file tools/shared/error.c.
References maxfilsev.
Referenced by verify_failure().
errsev()
void errsev (error_code_t ecode)
Issue a severe error message for gbl.lineno.
Definition at line 314 of file tools/shared/error.c.
References CNULL, ERR_Severe, error(), and gbl.
Referenced by _dinit_acl(), _mk_arrdsc(), _parser(), _size_of(), _xtok(), assign(), begin_contains(), binop(), build_array_list(), byvalue_ref_arg(), casttyp(), ch_substring(), check_do_term(), chk_doindex(), chk_scalar_inttyp(), chk_scalartyp(), chkcon(), chkcon_to_isz(), chklog(), chkopnds(), chksubscr(), cngcon(), cngshape(), cngtyp2(), compute_size_expr(), const_eval(), const_fold(), construct_acl_for_sst(), construct_acl_from_ast(), dinit_acl_val2(), dinit_data(), dinit_eval(), dinit_intr_call(), dinit_val(), dinit_varref(), error83(), eval(), extractor(), ff_get_stmt(), fix_args(), form_cmplx_const(), gen_dinit(), get_cstring(), get_keyword_components(), get_number(), get_retval_KIND_value(), get_stmt(), init_fold_const(), mkexpr1(), mklvalue(), ref_array(), ref_pd(), rewrite_acl(), sem_err105(), semant1(), semant2(), semant3(), size_ast_of(), and size_of().
errversion()
void errversion (void)
Print version info.
Definition at line 215 of file tools/shared/error.c.
References version.
errwarn()
void errwarn (error_code_t ecode)
Issue a warning for gbl.lineno.
Definition at line 308 of file tools/shared/error.c.
References CNULL, ERR_Warning, error(), and gbl.
Referenced by begin_combine_constructs(), check_do_term(), chkcon(), chkopnds(), chktyp(), cngcon(), crunch(), fperror(), func_call2(), get_retval_KIND_value(), holtonum(), main(), process_stb_file(), ptrfunc_call(), semant1(), semant2(), semant3(), semsmp(), and summary().
fperror()
void fperror (int errcode)
Floating point error.
Definition at line 359 of file tools/shared/error.c.
References ERR_Severe, errwarn(), FP_ILLEGAL_INPUT_OR_NAN, FP_NOERR, FP_OVERFLOW_ERROR, FP_UNDERFLOW_ERROR, FPE_FPOVF, FPE_FPUNF, FPE_INVOP, FPE_NOERR, gbl, interr(), lineno, and x.
Referenced by check().
interr()
void interr (const char * txt, int val, enum error_severity sev)
Assert that cond is true, and emit an internal compiler error otherwise.
Issue internal compiler error.
Note that unlike the C standard <assert.h> assert() macro, this version is active in both debug and release builds, and expands to a statement, not an expression.
Definition at line 266 of file tools/shared/error.c.
References interrf(), and val.
Referenced by __print_nme(), _assn_rtemp(), _avail(), _ccff_info(), _compute_width(), _constructf90(), _dinit_acl(), _dmp_dent(), _makezero(), _olap_conflict(), _parser(), _printacl(), _rdfo(), _size_of(), _transform_func(), acl_rewrite_asts(), ad1ili(), ad2func_cmplx(), ad2func_cmplx_abi(), ad2ili(), ad_cse(), ad_free(), ad_func(), add_arg(), add_arg_ili(), add_assign_firstprivate(), add_dt_subscr(), add_iolptrs(), add_parent_to_bounds(), add_private_allocatable(), addarth(), addili(), align_struct_tmp(), alignment(), alpha(), annomod_asm(), annomod_initx(), apply_gep_index(), arrayref_size(), assign_array_w_forall(), ast_clear_repl(), ast_replace(), ast_rewrite(), ast_trav_recurse(), ast_unvisit(), ast_unvisit_norepl(), ast_visit(), begin_call(), binop(), binop_init_list(), bits_in(), bld_lhs(), bld_use(), build_array_list(), build_dlist(), build_do_init(), build_rdfo(), canonical_conversion(), check_ccon(), check_ilm(), check_pte(), chk_and_rewrite_cmplxpart_assn(), chksubstr(), cmp_acl(), cmp_to_log(), cngshape(), compose_and_throw(), compute_size(), compute_size_expr(), Conflict_(), const_fold(), construct_acl_for_sst(), construct_acl_from_ast(), constructf90(), contains_alloc(), contiguous_array_section(), conv_allocate(), conv_deallocate(), convert_dtype(), convert_subscript_in_expr(), copy_initconst_to_array(), count_allocatable_members(), cp_memarg(), create_atomic_capture_seq(), create_atomic_seq(), create_atomic_write_seq(), crunch(), dd_array_conflict(), dd_edge(), decompose_expression(), dinit_acl_val2(), dinit_subs(), dinit_varref(), dist_ast(), dmp_var(), do_reduction(), do_subscript(), dtype_from_return_type(), dump_one_scope(), DumpnameHelper(), effective_rhs(), efunc(), emit_init(), endrcand(), eval_const_array_section(), eval_const_array_triple_section(), eval_do(), eval_fvec(), eval_ilm(), eval_init_op(), eval_sb(), exp_ac(), exp_add_copy(), exp_call(), exp_fstring(), exp_load(), exp_mac(), exp_misc(), exp_qjsr(), exp_smp(), exp_store(), exp_zqjsr(), export_dt(), export_host_subprogram(), export_ict(), export_module_subprogram(), export_symbol(), expr_dependent_check(), extent_of(), ff_get_stmt(), fill_ast(), fill_links_symbol(), fill_subscripts(), fillin_succ(), find_funcptr_name(), find_presence(), find_reduc_intrinsic(), first_element_from_section(), fix_dtype(), fix_term(), flow(), flow_end(), flow_init(), forall_semantic(), fperror(), gen_abs_expr(), gen_arg_operand(), gen_bindC_retval(), gen_call_expr(), gen_const_expr(), gen_contig_check(), gen_derived_io(), gen_funcret(), gen_llvm_expr(), gen_minmax_expr(), gen_mulh_expr(), gen_newer_intrin(), gen_reduction(), gen_switch(), get_ac_op(), get_ag(), get_ag_lltype(), get_ast_op(), get_atomic_function(), get_atomic_memory_order_name(), get_atomic_update_opcode(), get_atomicrmw_opname(), get_const_from_ast(), get_dtype_from_ilm(), get_forall_subscr(), get_header_member(), get_header_member_with_parent(), get_keyword_args(), get_kind_value(), get_llvm_name(), get_metadata_name(), get_msize(), get_next_arg(), get_number(), get_prefixed_int(), get_scalar_in_expr(), get_scope(), get_sdsc_element(), get_src_line(), get_stmt(), get_subscr(), get_type(), getdtype(), getitem(), getMergeSym(), getprint(), getsname(), handle_seq_section(), has_adjustable_expr(), has_allocatable_expr(), has_assumshp_expr(), has_invar_subs(), has_pointer_expr(), hostsym_is_refd(), hpf_library_stat(), ILI_OPC(), ILI_OPND(), ilm_return_slot_index(), import(), import_constant(), imprecise_match(), init_fold_const(), init_negate_const(), init_sptr_w_acl(), inlarr(), inline_shifts(), insert_comm_before(), insert_forall_comm(), install_dtype(), interpret(), is_array_in_expr(), is_dist_array_in_expr(), is_duplicate(), is_indirection_in_it(), is_legal_lhs(), is_legal_lhs_for_mask(), is_lonely_idx(), is_name_in_expr(), is_nonscalar_array_in_expr(), is_nonscalar_indirection_in_it(), is_one_idx_for_dim(), is_parentof_ast(), is_ptrast_arg(), is_same_array_bounds(), is_same_mask(), is_source_global(), is_source_nonlocal(), is_vector_indirection_in_it(), is_whole_array(), iso_c_lib_stat(), left_array_symbol(), left_nonscalar_subscript_ast(), left_subscript_ast(), ll_abi_from_call_site(), ll_ad_outlined_func2(), ll_convert_array_dtype(), ll_convert_basic_dtype_with_addrspace(), ll_create_int_type_with_addrspace(), ll_get_atomic_memorder(), ll_get_calling_conv_str(), ll_proto_add(), ll_proto_has_defined_body(), ll_proto_init(), ll_proto_is_weak(), ll_proto_set_defined_body(), ll_proto_set_intrinsic(), ll_proto_set_weak(), ll_type_bytes(), ll_write_global_objects(), localflow(), lower(), lower_check_stack(), lower_stmt(), mac_push(), make_equiv_ss(), make_forall(), make_sec_from_ast_chk(), map_initsym(), mark(), mark_apte_targets(), memsym_of_ast(), might_target(), mk_binop(), mk_coercion_func_name(), mk_component_ast(), mk_cval1(), mk_descr_id(), mk_forall_sptr(), mk_id_noshape(), mk_mem_ptr_shape(), mk_offset(), mk_result_sptr(), mk_storage(), mk_swtab(), mk_swtab_ll(), mk_unop(), mkarg(), mkexpr1(), mkfunc_sflags(), mklabelvar(), mklvalue(), mkrtemp_arg1_sc(), mkrtemp_cpx_sc(), mkshape(), mkvarref(), mod_type(), modify_inlined_stds(), move_labels(), name_dependent_check(), negate_const(), negate_const_be(), new_ast(), new_astli(), new_dtype(), new_installed_dtype(), new_symbol(), new_symbol_and_link(), normalize_forall(), normalize_forall_array(), par_xref(), par_xref_put(), parse_arguments(), pass_sym_of_ast(), pointer_squeezer(), points_to(), pop_indent(), pop_pragma(), pop_scope_level(), print_arg_attributes(), priority(), process_input(), procsym_of_ast(), push_elsewhere(), push_pragma(), push_scope_level(), put_a_init_tree(), put_arg_ili(), put_ffield(), put_length_type_param(), put_memsym_of_ast(), put_vlist(), queue_symbol(), rank_of(), read_symbol(), redimension(), ref_array(), ref_intrin(), ref_pd(), reference_for_temp(), remove_inlined_symbols(), remove_parent_from_ast(), remove_stmt(), reorder_dfn_loops(), reorderloops(), replace_ast_subtree(), replace_by_one(), replace_by_zero(), replace_memsym_of_ast(), replace_parms(), replace_vector_subscript(), reset_module_state(), restore_host_state(), restore_implicit(), restore_internal_subprograms(), restore_scope_level(), rewrite_acl(), rewrite_allocatable_assignment(), rewrite_ast_with_new_dtype(), rewrite_block_forall(), rewrite_block_where(), rewrite_calls(), rewrite_cmplxpart_rval(), rewrite_into_forall(), rewrite_sub_ast(), rw_dinit_state(), save_acl(), save_init(), save_scope_level(), save_uname(), scalar_communication(), scale_of(), Scale_Of(), search_basearr(), select_rtemp(), sem_err104(), semant1(), semant2(), semant3(), semantio(), semsmp(), set_ilmpos(), set_tp(), shape_comm_in_expr(), simple_reference_for_temp(), size_ast(), size_ast_of(), size_of(), size_of_array(), string_expr_length(), string_length(), subscr_dependent_check(), subscript_allocmem(), subst(), sym_is_refd(), sym_of_ast(), symdentry(), tag_forall_comm(), target_kind(), target_name(), test_really_an_entry(), tkn_alias_sym(), transfer_load(), transfer_store(), transform(), transform_all_call(), transform_c_f_pointer(), transform_c_f_procpointer(), transform_call(), transform_pure_function(), trav_struct(), ubound_of(), unop_init_list(), upper(), vect_math(), verify_failure(), vmk_prototype(), write_def_values(), write_mdfield(), write_mdref(), xref(), and xrefput().
interrf()
void interrf (enum error_severity sev, const char * fmt, ...)
Issue internal compiler error using printf-style formatting.
Parameters
sev error severity.
fmt printf-style format string
... args for format string
Definition at line 244 of file tools/shared/error.c.
References ERR_Informational, error(), FREE, gbl, NEW, NULL, and size.
Referenced by import(), init_ktable(), interr(), invalid_size(), sidecar_not_found(), stg_alloc_sidecar(), stg_next(), and too_small_for_freelist().
summary()
int summary (bool final, int ipafollows)
Write either error summary message for current subprogram unit, or final execution summary line to user's terminal. Return the maximum error severity seen for the entire file.
Definition at line 326 of file tools/shared/error.c.
References errwarn(), flg, gbl, maxfilsev, ndiags, SYMNAME, t, FLG::terse, and version.
Referenced by finish(), parser(), and process_input().
Variable Documentation
emit_errmsg
int emit_errmsg = 1 static
Definition at line 32 of file tools/shared/error.c.
Referenced by display_error(), and erremit().
maxfilsev
enum error_severity maxfilsev static
Definition at line 29 of file tools/shared/error.c.
Referenced by display_error(), error_max_severity(), finish(), and summary().
ndiags
int ndiags[ERR_SEVERITY_SIZE] static
Definition at line 28 of file tools/shared/error.c.
Referenced by display_error(), errini(), and summary().
totaldiags
int totaldiags = 0 static
Definition at line 30 of file tools/shared/error.c.
Referenced by display_error(), and errini().