flang: error.h File Reference
tools/shared/error.h File Reference
Compiler Error handling and reporting.
#include "gbldefs.h"
#include "errmsgdf.h"
#include "flang/Error/pgerror.h"
Functions
char * errnum (int num)
Convert an integer to a string, for printing numbers in error messages.
enum error_severity error_max_severity (void)
...
int summary (bool final, int ipafollows)
void asrt_failed (const char *filename, int line)
void dassert_err (const char *filename, int line, const char *expr, const char *txt)
void erremit (int x)
Set the emit error flag(s)
void errfatal (error_code_t ecode)
Issue a fatal error for gbl.lineno.
void errinfo (error_code_t ecode)
Issue an informational message for gbl.lineno.
void errini (void)
Initialize error counts for new user subprogram.
void errlabel (error_code_t ecode, enum error_severity sev, int eline, char *nm, const char *op2)
Massage label name if necesseary.
void error (error_code_t ecode, enum error_severity sev, int eline, const char *op1, const char *op2)
Construct and issue an error message.
void errsev (error_code_t ecode)
Issue a severe error message for gbl.lineno.
void errversion (void)
Print version info.
void errwarn (error_code_t ecode)
Issue a warning for gbl.lineno.
void fperror (int errcode)
Floating point error.
void interr (const char *txt, int val, enum error_severity sev)
Issue internal compiler error.
void interrf (enum error_severity sev, const char *fmt,...)
Issue internal compiler error using printf-style formatting.
Detailed Description
Compiler Error handling and reporting.
Definition in file tools/shared/error.h.
Function Documentation
asrt_failed()
void asrt_failed (const char * filename, int line)
Prints information on behalf of failed asrt.
Parameters
file filename: name of file where assertion failed.
line line number where assertion failed
dassert_err()
void dassert_err (const char * filename, int line, const char * expr, const char * txt)
Prints information on behalf of failed DEBUG_ASSERT.
Parameters
filename name of file where assertion failed.
line line number where assertion failed.
expr string representation of assertion that failed.
txt optional text to print via interr. Use NULL if no text
erremit()
void erremit (int x)
Set the emit error flag(s)
Definition at line 353 of file tools/shared/error.c.
References emit_errmsg, and x.
Referenced by apply_use(), and open_module().
errfatal()
void errfatal (error_code_t ecode)
Issue a fatal error for gbl.lineno.
Definition at line 320 of file tools/shared/error.c.
References CNULL, ERR_Fatal, error(), and gbl.
Referenced by accpp(), add_astli(), apply_use(), dinit(), dinit_put(), display_error(), end_module(), finish(), fpp(), get_brtbl(), get_gstbl(), get_pertbl(), get_tbl(), init(), ll_open_parfiles(), mk_argt(), mk_dtb(), mk_finfo(), mk_ftb(), mk_std(), new_node(), push_include(), put_data_statement(), reset_module_state(), restore_host_state(), restore_module_state(), rw_dinit_state(), save_host_state(), save_imported_modules_state(), save_module_state1(), scan_include(), scan_init(), sccalloc(), sccrelal(), symini_errfatal(), write_comm(), and xrefinit().
errinfo()
void errinfo (error_code_t ecode)
Issue an informational message for gbl.lineno.
Definition at line 302 of file tools/shared/error.c.
References CNULL, ERR_Informational, error(), and gbl.
Referenced by cngcon().
errini()
void errini (void)
Initialize error counts for new user subprogram.
Definition at line 209 of file tools/shared/error.c.
References gbl, ndiags, and totaldiags.
Referenced by init(), parser(), and reinit().
errlabel()
void errlabel (error_code_t ecode, enum error_severity sev, int eline, char * nm, const char * op2)
Massage label name if necesseary.
Parameters
ecode error number
sev error severity in range 1 ... 4
eline source file line number
nm label name
op2 extra string
Definition at line 230 of file tools/shared/error.c.
References error().
Referenced by _read_token(), exp_label(), ff_get_label(), get_stmt(), semant1(), and semfin().
errnum()
char * errnum (int num)
Convert an integer to a string, for printing numbers in error messages.
This returns a pointer to static data, so only use it once.
Definition at line 294 of file tools/shared/error.c.
References n, and num.
error()
void error (error_code_t ecode, enum error_severity sev, int eline, const char * op1, const char * op2)
Construct and issue an error message.
Parameters
ecode error number
sev error severity (a value in the err_severity enum)
eline source file line number
op1 string to be expanded into error message * or 0
op2 string to be expanded into error message * or 0
Construct error message and issue it to user terminal and to listing file if appropriate.
Definition at line 223 of file tools/shared/error.c.
References display_error(), and NULL.
Referenced by errfatal(), errinfo(), errlabel(), errsev(), errwarn(), and interrf().
error_max_severity()
enum error_severity error_max_severity (void)
...
Definition at line 398 of file tools/shared/error.c.
References maxfilsev.
Referenced by verify_failure().
errsev()
void errsev (error_code_t ecode)
Issue a severe error message for gbl.lineno.
Definition at line 314 of file tools/shared/error.c.
References CNULL, ERR_Severe, error(), and gbl.
Referenced by _dinit_acl(), _mk_arrdsc(), _parser(), _size_of(), _xtok(), assign(), begin_contains(), binop(), build_array_list(), byvalue_ref_arg(), casttyp(), ch_substring(), check_do_term(), chk_doindex(), chk_scalar_inttyp(), chk_scalartyp(), chkcon(), chkcon_to_isz(), chklog(), chkopnds(), chksubscr(), cngcon(), cngshape(), cngtyp2(), compute_size_expr(), const_eval(), const_fold(), construct_acl_for_sst(), construct_acl_from_ast(), dinit_acl_val2(), dinit_data(), dinit_eval(), dinit_intr_call(), dinit_val(), dinit_varref(), error83(), eval(), extractor(), ff_get_stmt(), fix_args(), form_cmplx_const(), gen_dinit(), get_cstring(), get_keyword_components(), get_number(), get_retval_KIND_value(), get_stmt(), init_fold_const(), mkexpr1(), mklvalue(), ref_array(), ref_pd(), rewrite_acl(), sem_err105(), semant1(), semant2(), semant3(), size_ast_of(), and size_of().
errversion()
void errversion (void)
Print version info.
Definition at line 215 of file tools/shared/error.c.
References version.
errwarn()
void errwarn (error_code_t ecode)
Issue a warning for gbl.lineno.
Definition at line 308 of file tools/shared/error.c.
References CNULL, ERR_Warning, error(), and gbl.
Referenced by begin_combine_constructs(), check_do_term(), chkcon(), chkopnds(), chktyp(), cngcon(), crunch(), fperror(), func_call2(), get_retval_KIND_value(), holtonum(), main(), process_stb_file(), ptrfunc_call(), semant1(), semant2(), semant3(), semsmp(), and summary().
fperror()
void fperror (int errcode)
Floating point error.
Definition at line 19 of file default-fperror.c.
References ERR_Severe, errwarn(), FPE_FPOVF, FPE_FPUNF, FPE_INVOP, FPE_NOERR, gbl, interr(), and lineno.
interr()
void interr (const char * txt, int val, enum error_severity sev)
Issue internal compiler error.
Parameters
txt null terminated text string identifying
val integer value to be written with message
sev error severity
Issue internal compiler error.
Note that unlike the C standard <assert.h> assert() macro, this version is active in both debug and release builds, and expands to a statement, not an expression.
Definition at line 266 of file tools/shared/error.c.
Referenced by fperror().
interrf()
void interrf (enum error_severity sev, const char * fmt, ...)
Issue internal compiler error using printf-style formatting.
Parameters
sev error severity.
fmt printf-style format string
... args for format string
Definition at line 244 of file tools/shared/error.c.
References ERR_Informational, error(), FREE, gbl, NEW, NULL, and size.
Referenced by import(), init_ktable(), interr(), invalid_size(), sidecar_not_found(), stg_alloc_sidecar(), stg_next(), and too_small_for_freelist().
summary()
int summary (bool final, int ipafollows)
Write either error summary message for current subprogram unit, or final execution summary line to user's terminal. Return the maximum error severity seen for the entire file.
Definition at line 326 of file tools/shared/error.c.
References errwarn(), flg, gbl, maxfilsev, ndiags, SYMNAME, t, FLG::terse, and version.
Referenced by finish(), parser(), and process_input().