flang: hash.h File Reference
tools/flang1/flang1exe/hash.h File Reference
General-Purpose Hash Tables.
Classes
struct hash_functions_
struct hash_accu_
Macros
#define INT2HKEY(i) (hash_key_t)(long)(i)
#define HKEY2INT(k) (int)(long)(k)
#define HASH_ACCU_INIT
#define HASH_ACCU_ADD(accu, data)
#define HASH_ACCU_FINISH(accu)
#define HASH_ACCU_VALUE(accu) ((accu).a + 0)
Typedefs
typedef unsigned hash_value_t
typedef const void * hash_key_t
typedef hash_value_t(* hash_function_t) (hash_key_t)
typedef int(* hash_equality_t) (hash_key_t, hash_key_t)
typedef struct hash_functions_ hash_functions_t
typedef struct hashset_ * hashset_t
Hash Set.
typedef void(* hashset_iterator_func_t) (hash_key_t, void *)
typedef struct hashmap_ * hashmap_t
Hash Map.
typedef const void * hash_data_t
typedef void(* hashmap_iterator_func_t) (hash_key_t, hash_data_t, void *)
typedef struct hash_accu_ hash_accu_t
Functions
hashset_t hashset_alloc (hash_functions_t f)
Allocate a hashset which uses the provided functions to interpret keys.
void hashset_free (hashset_t h)
Free all memory used by a hashset.
void hashset_clear (hashset_t h)
Erase all keys in the set.
unsigned hashset_size (hashset_t h)
Get the number of keys in the set.
hash_key_t hashset_lookup (hashset_t h, hash_key_t key)
Look up a key and return the equivalent stored key, or NULL.
void hashset_insert (hashset_t h, hash_key_t key)
Insert a new key.
hash_key_t hashset_replace (hashset_t h, hash_key_t key)
Insert a new key or replace an existing key.
hash_key_t hashset_erase (hashset_t h, hash_key_t key)
Erase a key from the set and return it.
void hashset_iterate (hashset_t h, void(*f)(hash_key_t k, void *context), void *context)
Call f with every key in the hash set.
hashmap_t hashmap_alloc (hash_functions_t f)
Allocate a hashmap.
void hashmap_free (hashmap_t h)
Free all memory used by a hashmap.
void hashmap_clear (hashmap_t h)
Erase all (key, data) entries in the map.
unsigned hashmap_size (hashmap_t h)
Return the number of (key, data) pairs in the map.
hash_key_t hashmap_lookup (hashmap_t h, hash_key_t key, hash_data_t *data)
Look up a key and return the equivalent stored key, or NULL.
void hashmap_insert (hashmap_t h, hash_key_t key, hash_data_t data)
Insert a new (key, data) pair.
hash_key_t hashmap_replace (hashmap_t h, hash_key_t key, hash_data_t *data)
Insert or replace a (key, data) pair.
hash_key_t hashmap_erase (hashmap_t h, hash_key_t key, hash_data_t *data)
Erase a key from the map and return it.
void hashmap_iterate (hashmap_t h, void(*f)(hash_key_t k, hash_data_t v, void *context), void *context)
Call f with every (key, data) pair in the hash map.
void hashmap_sort (hashmap_t h, void(*f)(hash_key_t k, hash_data_t v, void *context), void *context)
...
Variables
const hash_functions_t hash_functions_strings
Predefined hash functions for strings.
const hash_functions_t hash_functions_direct
Predefined hash functions for directly hashed keys.
Detailed Description
General-Purpose Hash Tables.
These two hash table implementations store void pointers as keys, using user-provided functions for hashing and equality testing. The void pointers are not interpreted by the hash table implementation, except:
The void pointers are passed to the provided hash() and equals() functions.
The sentinel values NULL and (void*)~0UL have special meanings and cannot be used as keys.
The equality function should return non-zero for equal hash keys. At a minimum, the provided functions must satisfy:
equals(a, b) ==> hash(a) = hash(b)
The hash() function should avoid clustering in the low bits of the hash value.
A NULL equals() function is equivalent to a function returning a == b, but faster.
Definition in file tools/flang1/flang1exe/hash.h.
Macro Definition Documentation
HASH_ACCU_ADD
#define HASH_ACCU_ADD (accu, data)
Value:
  do {                                \
    (accu).a += (hash_value_t)(data); \
    (accu).a += (accu).a << 10;       \
    (accu).a ^= (accu).a >> 6;        \
  } while (0)
Definition at line 246 of file tools/flang1/flang1exe/hash.h.
HASH_ACCU_FINISH
#define HASH_ACCU_FINISH (accu)
Value:
  do {                          \
    (accu).a += (accu).a << 3;  \
    (accu).a ^= (accu).a >> 11; \
    (accu).a += (accu).a << 15; \
  } while (0)
Definition at line 253 of file tools/flang1/flang1exe/hash.h.
HASH_ACCU_INIT
#define HASH_ACCU_INIT
Value:
  {                    \
    0                  \
  }
Definition at line 241 of file tools/flang1/flang1exe/hash.h.
HASH_ACCU_VALUE
#define HASH_ACCU_VALUE (accu) ((accu).a + 0)
Definition at line 260 of file tools/flang1/flang1exe/hash.h.
HKEY2INT
#define HKEY2INT (k) (int)(long)(k)
Definition at line 64 of file tools/flang1/flang1exe/hash.h.
INT2HKEY
#define INT2HKEY (i) (hash_key_t)(long)(i)
Definition at line 63 of file tools/flang1/flang1exe/hash.h.
Typedef Documentation
hash_accu_t
typedef struct hash_accu_ hash_accu_t
hash_data_t
typedef const void* hash_data_t
Definition at line 151 of file tools/flang1/flang1exe/hash.h.
hash_equality_t
typedef int(* hash_equality_t) (hash_key_t, hash_key_t)
Definition at line 39 of file tools/flang1/flang1exe/hash.h.
hash_function_t
typedef hash_value_t(* hash_function_t) (hash_key_t)
Definition at line 38 of file tools/flang1/flang1exe/hash.h.
hash_functions_t
typedef struct hash_functions_ hash_functions_t
hash_key_t
typedef const void* hash_key_t
Definition at line 36 of file tools/flang1/flang1exe/hash.h.
hash_value_t
typedef unsigned hash_value_t
Definition at line 35 of file tools/flang1/flang1exe/hash.h.
hashmap_iterator_func_t
typedef void(* hashmap_iterator_func_t) (hash_key_t, hash_data_t, void *)
Definition at line 209 of file tools/flang1/flang1exe/hash.h.
hashmap_t
typedef struct hashmap_* hashmap_t
Hash Map.
A hashmap_t is a hash table that maps a set of keys to data pointers.
The keys are treated exactly the same as for a hashset_t, and have the same restrictions (i.e., no NULL and ~0UL keys allowed). The data pointers can have any value.
Definition at line 150 of file tools/flang1/flang1exe/hash.h.
hashset_iterator_func_t
typedef void(* hashset_iterator_func_t) (hash_key_t, void *)
Definition at line 128 of file tools/flang1/flang1exe/hash.h.
hashset_t
typedef struct hashset_* hashset_t
Hash Set.
A hashset_t is a hash table that stores a set of keys with no associated information.
Definition at line 72 of file tools/flang1/flang1exe/hash.h.
Function Documentation
hashmap_alloc()
hashmap_t hashmap_alloc (hash_functions_t f)
Allocate a hashmap.
The returned handle must be freed with hashmap_free().
Definition at line 222 of file lib/ADT/hash.c.
References alloc_tables(), f, and h.
hashmap_clear()
void hashmap_clear (hashmap_t h)
Erase all (key, data) entries in the map.
Definition at line 255 of file lib/ADT/hash.c.
References alloc_tables(), and h.
hashmap_erase()
hash_key_t hashmap_erase (hashmap_t h, hash_key_t key, hash_data_t * data)
Erase a key from the map and return it.
If a (key, data) pair was erased and data is not NULL, update *data with the erased data value.
If no key was erased, return NULL and leave *data unchanged.
Definition at line 380 of file lib/ADT/hash.c.
References DTABLE, ERASED, h, i, NULL, and search().
hashmap_free()
void hashmap_free (hashmap_t h)
Free all memory used by a hashmap.
Note that any memory referenced by keys and data pointers in the map is not freed.
Definition at line 239 of file lib/ADT/hash.c.
References h.
hashmap_insert()
void hashmap_insert (hashmap_t h, hash_key_t key, hash_data_t data)
Insert a new (key, data) pair.
This function assumes that no equivalent key is present in the map, i.e. hashmap_lookup() would return NULL.
Use hashmap_replace() if an equivalent key may exist in the map already.
Definition at line 310 of file lib/ADT/hash.c.
References assert, DTABLE, ERASED, ERR_Fatal, h, hashmap_lookup(), i, insertion_point(), NEED_REHASH, NULL, and rehash().
Referenced by hashmap_replace().
hashmap_iterate()
void hashmap_iterate (hashmap_t h, void(*)(hash_key_t k, hash_data_t v, void *context) f, void * context)
Call f with every (key, data) pair in the hash map.
The function f must not modify the hash table.
hashmap_lookup()
hash_key_t hashmap_lookup (hashmap_t h, hash_key_t key, hash_data_t * data)
Look up a key and return the equivalent stored key, or NULL.
If if a key was found and data is not NULL, *data will be set to the corresponding data value, otherwise it is not changed.
Definition at line 281 of file lib/ADT/hash.c.
References DTABLE, h, i, k, and search().
Referenced by hashmap_insert().
hashmap_replace()
hash_key_t hashmap_replace (hashmap_t h, hash_key_t key, hash_data_t * data)
Insert or replace a (key, data) pair.
If an equivalent key already exists, replace it with the new key and *data, and return the old key. On return, *data is set to the old data.
If no equivalent key is present, insert the new key and *data and return NULL. The *data value is not updated.
Definition at line 345 of file lib/ADT/hash.c.
References DTABLE, h, hashmap_insert(), i, ISKEY, NULL, and search().
hashmap_size()
unsigned hashmap_size (hashmap_t h)
Return the number of (key, data) pairs in the map.
Definition at line 269 of file lib/ADT/hash.c.
References h.
hashmap_sort()
void hashmap_sort (hashmap_t h, void(*)(hash_key_t k, hash_data_t v, void *context) f, void * context)
...
hashset_alloc()
hashset_t hashset_alloc (hash_functions_t f)
Allocate a hashset which uses the provided functions to interpret keys.
The returned hashset_t handle should be passed to hashset_free() to deallocate memory.
Definition at line 213 of file lib/ADT/hash.c.
References alloc_tables(), f, and h.
hashset_clear()
void hashset_clear (hashset_t h)
Erase all keys in the set.
Definition at line 247 of file lib/ADT/hash.c.
References alloc_tables(), and h.
hashset_erase()
hash_key_t hashset_erase (hashset_t h, hash_key_t key)
Erase a key from the set and return it.
Return NULL if no equivalent key was found.
Definition at line 365 of file lib/ADT/hash.c.
References ERASED, h, i, NULL, and search().
hashset_free()
void hashset_free (hashset_t h)
Free all memory used by a hashset.
Note that any memory referenced by keys in the set is not freed.
Definition at line 231 of file lib/ADT/hash.c.
References h.
hashset_insert()
void hashset_insert (hashset_t h, hash_key_t key)
Insert a new key.
Note that this function assumes that no equivalent key is present in the set, i.e. hashset_lookup() would return false.
Use hashset_replace() if an equivalent key may be in the set already.
The key cannot be NULL or (hash_key_t)~0UL.
Definition at line 291 of file lib/ADT/hash.c.
References assert, ERASED, ERR_Fatal, h, hashset_lookup(), i, insertion_point(), NEED_REHASH, NULL, and rehash().
Referenced by hashset_replace().
hashset_iterate()
void hashset_iterate (hashset_t h, void(*)(hash_key_t k, void *context) f, void * context)
Call f with every key in the hash set.
Note that the iteration order is a function of both the hash function and the sequence of hashset_* calls leading up to this one. If pointers are directly hashed, address space layout randomization can cause different iteration orders in otherwise identical executions.
The function f must not modify the hash table.
hashset_lookup()
hash_key_t hashset_lookup (hashset_t h, hash_key_t key)
Look up a key and return the equivalent stored key, or NULL.
Definition at line 275 of file lib/ADT/hash.c.
References h, and search().
Referenced by hashset_insert().
hashset_replace()
hash_key_t hashset_replace (hashset_t h, hash_key_t key)
Insert a new key or replace an existing key.
If an equivalent key already exists, replace it with the new key and return the old one. If no equivalent key is in the set, insert the new key and return NULL.
Definition at line 330 of file lib/ADT/hash.c.
References h, hashset_insert(), i, ISKEY, NULL, and search().
hashset_size()
unsigned hashset_size (hashset_t h)
Get the number of keys in the set.
Definition at line 263 of file lib/ADT/hash.c.
References h.
Variable Documentation
hash_functions_direct
const hash_functions_t hash_functions_direct extern
Predefined hash functions for directly hashed keys.
The pointers are compared by value with no indirection. These hash functions can also be used for integer keys. Just cast the integers to hash_key_t.
Definition at line 459 of file lib/ADT/hash.c.
hash_functions_strings
const hash_functions_t hash_functions_strings extern
Predefined hash functions for strings.
The hash keys are interpreted as pointers to NUL-terminated strings.
Definition at line 441 of file lib/ADT/hash.c.