flang: trace2.c File Reference
trace2.c File Reference
Functions
void __fort_trac_arecv (int cpu, long len, int reqn)
void __fort_trac_arecv_done (int cpu)
void __fort_trac_asend (int cpu, long len, int reqn)
void __fort_trac_asend_done (int cpu)
void __fort_trac_await (int reqn)
void __fort_trac_await_done (int reqn)
Function Documentation
__fort_trac_arecv()
void __fort_trac_arecv (int cpu, long len, int reqn)
Definition at line 11 of file trace2.c.
Referenced by __fort_entry_arecv().
__fort_trac_arecv_done()
void __fort_trac_arecv_done (int cpu)
Definition at line 18 of file trace2.c.
__fort_trac_asend()
void __fort_trac_asend (int cpu, long len, int reqn)
Definition at line 25 of file trace2.c.
Referenced by __fort_entry_asend().
__fort_trac_asend_done()
void __fort_trac_asend_done (int cpu)
Definition at line 32 of file trace2.c.
Referenced by __fort_entry_asend_done().
__fort_trac_await()
void __fort_trac_await (int reqn)
Definition at line 39 of file trace2.c.
Referenced by __fort_entry_await().
__fort_trac_await_done()
void __fort_trac_await_done (int reqn)
Definition at line 46 of file trace2.c.
Referenced by __fort_entry_await_done().