flang: trace_lin.c File Reference
trace_lin.c File Reference
#include "flangrti_config.h"
#include <stdint.h>
#include <signal.h>
#include <execinfo.h>
#include <unistd.h>
#include <limits.h>
#include <sys/types.h>
#include <stdioInterf.h>
#include "dumpregs.h"
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
Classes
struct cods
struct sigs
Macros
#define CODNULL ((struct cods *)0)
#define MAXTRACE (32 * 1024)
Functions
char ** __io_get_argv ()
void print_back_trace_line (char *bt_str, void const *const addr)
void __abort_trace (int skip)
static void __abort_sig_hand (int sig, siginfo_t *in, FLANGRTI_UCONTEXT_T *u)
void __abort_sig_init (void)
Variables
static struct cods codill []
static struct cods codfpe []
static struct cods codsegv []
static struct cods codbus []
static struct sigs sigs []
static FLANGRTI_GREGSET_T * regs
static char ** saved_argv = NULL
Macro Definition Documentation
CODNULL
#define CODNULL ((struct cods *)0)
Definition at line 32 of file trace_lin.c.
MAXTRACE
#define MAXTRACE (32 * 1024)
Definition at line 97 of file trace_lin.c.
Function Documentation
__abort_sig_hand()
static void __abort_sig_hand (int sig, siginfo_t * in, FLANGRTI_UCONTEXT_T * u) static
Definition at line 210 of file trace_lin.c.
References __abort(), b, CODNULL, getRegs(), m, n, new, p, regs, sigs::str, str, and void().
Referenced by __abort_sig_init().
__abort_sig_init()
void __abort_sig_init (void)
Definition at line 258 of file trace_lin.c.
References __abort_sig_hand(), n, new, and void().
Referenced by __abort_init().
__abort_trace()
void __abort_trace (int skip)
Definition at line 174 of file trace_lin.c.
References __io_stderr(), dumpregs(), FLANGRTI_GREGSET_T, i, MAXTRACE, print_back_trace_line(), regs, size, and skip.
Referenced by __abort().
__io_get_argv()
char ** __io_get_argv ()
Definition at line 14 of file ioargs.c.
Referenced by print_back_trace_line().
print_back_trace_line()
void print_back_trace_line (char * bt_str, void const *const addr)
Definition at line 100 of file trace_lin.c.
References __io_get_argv(), __io_stderr(), addr, f, fclose(), FILE, fp, NULL, saved_argv, and strlen().
Referenced by __abort_trace().
Variable Documentation
codbus
struct cods codbus[] static
Initial value:
= {{BUS_ADRALN, "invalid address alignment"},
                               {BUS_ADRERR, "non-existent physical address"},
                               {BUS_OBJERR, "object specific hardware error"},
                               {0, NULL}}
Definition at line 60 of file trace_lin.c.
codfpe
struct cods codfpe[] static
Initial value:
= {{FPE_INTDIV, "integer divide by zero"},
                               {FPE_INTOVF, "integer overflow"},
                               {FPE_FLTDIV, "floating point divide by zero"},
                               {FPE_FLTOVF, "floating point overflow"},
                               {FPE_FLTUND, "floating point underflow"},
                               {FPE_FLTRES, "floating point inexact result"},
                               {FPE_FLTINV, "floating point invalid operation"},
                               {FPE_FLTSUB, "subscript out of range"},
                               {0, NULL}}
Definition at line 45 of file trace_lin.c.
codill
struct cods codill[] static
Initial value:
= {{ILL_ILLOPC, "illegal opcode"},
                               {ILL_ILLOPN, "illegal operand"},
                               {ILL_ILLADR, "illegal addressing mode"},
                               {ILL_ILLTRP, "illegal trap"},
                               {ILL_PRVOPC, "privileged opcode"},
                               {ILL_PRVREG, "privileged register"},
                               {ILL_COPROC, "coprocessor error"},
                               {ILL_BADSTK, "internal stack error"},
                               {0, NULL}}
Definition at line 35 of file trace_lin.c.
codsegv
struct cods codsegv[] static
Initial value:
= {
    {SEGV_MAPERR, "address not mapped to object"},
    {SEGV_ACCERR, "invalid permissions for mapped object"},
    {0, NULL}}
Definition at line 55 of file trace_lin.c.
regs
FLANGRTI_GREGSET_T* regs static
Definition at line 90 of file trace_lin.c.
Referenced by __abort_sig_hand(), and __abort_trace().
saved_argv
char** saved_argv = NULL static
Definition at line 93 of file trace_lin.c.
Referenced by print_back_trace_line().
sigs
struct sigs sigs[] static
Initial value:
= {
    {SIGINT, CODNULL, "interrupt"},
    {SIGILL, codill, "illegal instruction"},
    {SIGABRT, CODNULL, "abort"},
    {SIGFPE, codfpe, "floating point exception"},
    {SIGSEGV, codsegv, "segmentation violation"},
    {SIGTERM, CODNULL, "software termination"},
    {SIGPIPE, CODNULL, "write on a pipe with no one to read it"},
    {SIGSYS, CODNULL, "bad argument to system call"},
    {SIGHUP, CODNULL, "hangup"},
    {SIGBUS, codbus, "bus error"},
    {SIGQUIT, CODNULL, "quit"},
    {SIGTRAP, CODNULL, "trace trap"},
    {SIGIOT, CODNULL, "IOT instruction"},
    {0, CODNULL, NULL}
}
Definition at line 73 of file trace_lin.c.