flang: transfer.c File Reference
transfer.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
#include "type.h"
Functions
static int I8() next_index (__INT_T *index, F90_Desc *s)
void ENTFTN (TRANSFER, transfer)
Function Documentation
ENTFTN()
void ENTFTN (TRANSFER , transfer)
Definition at line 28 of file transfer.c.
References __DESC, __fort_bcopy(), __fort_free(), __fort_get_scalar(), __fort_malloc(), __POLY, dest, extent(), F90_DIM_EXTENT_G, F90_DIM_LBOUND_G, F90_RANK_G, F90_TAG_G, i, I8, k, next_index(), NULL, rb, result, sb, sindex, size, and src.
next_index()
static int I8() next_index (__INT_T * index, F90_Desc * s) static
Definition at line 15 of file transfer.c.
References DIM_UBOUND_G, F90_DIM_LBOUND_G, F90_RANK_G, i, index, and s.
Referenced by ENTFTN().