flang: transfrm.c File Reference
transfrm.c File Reference
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "comm.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "soc.h"
#include "semant.h"
#include "ast.h"
#include "transfrm.h"
#include "gramtk.h"
#include "extern.h"
#include "hpfutl.h"
#include "dinit.h"
#include "ccffinfo.h"
#include "optimize.h"
#include "rte.h"
#include "rtlRtns.h"
Classes
struct wherestackentry
struct wherestack
struct idxlist
Macros
#define TRANS_AREA 10
Typedefs
typedef struct wherestackentry wherestackentry
Functions
static void rewrite_into_forall (void)
Fortran transformation module.
static void rewrite_block_where (void)
static void rewrite_block_forall (void)
static void find_allocatable_assignment (void)
static void rewrite_allocatable_assignment (int, int, bool, bool)
static void handle_allocatable_members (int, int, int, bool)
static void trans_get_descrs (void)
static void trans_clridx (void)
static void trans_freeidx (void)
static int collapse_assignment (int, int)
static int build_sdsc_node (int)
static int inline_spread_shifts (int, int, int)
static int copy_forall (int)
static void clear_dist_align (void)
static void transform_init (void)
static void init_finfo (void)
static void set_initial_s1 (void)
static void gen_allocated_check (int ast, int std, int atype, bool negate, bool is_assign_lhs, bool is_assign_lhs2)
Generate an IF to see if ast is allocated and insert before std. Caller is responsible for generating ENDIF.
static int subscript_allocmem (int aref, int asd)
static int normalize_subscripts (int oldasd, int oldshape, int newshape)
static int gen_dos_over_shape (int shape, int std)
static void gen_do_ends (int docnt, int std)
static int mk_bounds_shape (int shape)
void dbg_print_stmts (FILE *)
static bool chk_assumed_subscr (int a)
Checks whether the user specified an empty array subscript such as (:), (:,:), (:,:,:), etc.
static int mk_ptr_subscr (int subAst, int std)
Create a non-subscripted "alias" or "replacement" ast to a subscripted expression.
static int get_sdsc_ast (SPTR sptrsrc, int astsrc)
Computes the descriptor on the right hand side of an allocatable polymorphic assignment.
static int build_poly_func_node (int dest, int src, int intrin_type)
Generate a call to poly_conform_types() that is used in polymorphic allocatable assignment.
static int mk_poly_test (int dest, int src, int optype, int intrin_type)
Same as mk_conformable_test() above, except it generates a test between two polymorphic scalar objects.
static int count_allocatable_members (int ast)
This function counts the number of allocatable members/components in a derived type member expression (e.g., ab, abc, abcd, etc.).
void transform (void)
void reset_init_idx (void)
int get_init_idx (int i, int dtype)
static int mk_finfo (void)
int get_finfo (int forall, int a)
static void nice_mask (int ast, LOGICAL *nice)
static LOGICAL nice_where_mask (int ast)
static void srch_sym (int ast, LOGICAL *has_sym)
static LOGICAL mask_on_lhs (int mask, int lhs)
static void rewrite_where_expr (int where_std, int endwhere_std)
static void init_where (void)
static void push_where (int where_std)
static void push_elsewhere (int elsewhere_std)
static void pop_where (int *where, int *elsewhere)
static void push_forall (int forall_std)
static void pop_forall (int *forall_std)
static void add_wheresym (ITEM **wheresymlist, int wheresym)
static LOGICAL in_wheresymlist (ITEM *list, int sptr)
static LOGICAL _contains_forall_index (int ast, LOGICAL *flag)
static LOGICAL contains_forall_index (int ast, int forall_list)
static void check_subprogram (int std, int ast, int callast)
static LOGICAL find_const_bound_rhs (int expr, int *rhs, int *shape)
static LOGICAL constant_shape (int shape)
static int search_arr (int ast)
static int normalize_subscript (int ast, int oldlb, int oldstride, int newlb, int newstride)
LOGICAL vector_member (int memast)
Return TRUE if memast is an A_MEM for an array, or memast is an A_SUBSCR whose parent is an A_MEM and which has triplet subscripts.
static int normalize_forall_array (int forall_ast, int arr_ast, int inlist)
static int normalize_id (int forall_ast, int asgn_ast, int inlist)
int normalize_forall (int forall_ast, int asgn_ast, int inlist)
static LOGICAL is_reshape (int ast)
int make_forall (int shape, int astmem, int mask_ast, int lc)
void init_tbl (void)
void free_tbl (void)
int get_tbl (void)
void trans_process_align (void)
LOGICAL is_bad_dtype (int dtype)
LOGICAL is_array_type (int sptr)
static int mk_descr_id (SPTR sptr)
static int build_conformable_func_node (int astdest, int astsrc)
int mk_conformable_test (int dest, int src, int optype)
int mk_allocate (int ast)
int mk_deallocate (int ast)
void rewrite_deallocate (int ast, bool is_assign_lhs, int std)
static void gen_bounds_assignments (int astdestparent, int astdestmem, int astsrcparent, int astsrcmem, int std)
static int build_allocation_item (int astdestparent, int astdestmem)
static void gen_alloc_mbr (int ast, int std)
static void gen_dealloc_mbr (int ast, int std)
static void nullify_member (int ast, int std, int sptr)
static LOGICAL _contains_sptr (int astSrc, LOGICAL *pflag)
static LOGICAL contains_sptr (int astSrc, int sptrDst, int astparent)
void gen_dealloc_if_allocated (int ast, int std)
Variables
FINFO_TBL finfot
static int init_idx [MAXSUBS+MAXSUBS]
static int num_init_idx
struct pure_gbl pure_gbl
int pghpf_type_sptr
int pghpf_local_mode_sptr = 0
struct {
int sptr
} wherestuff
struct wherestack wherestack = {(wherestackentry *)0, 0, 0, 0}
static int ForallList
int * badpointer1 = (int *)0
long * badpointer2 = (long *)1
long badnumerator = 99
long baddenominator = 0
static struct idxlist * idxlist
static int sptrMatch
static int parentMatch
Macro Definition Documentation
TRANS_AREA
#define TRANS_AREA 10
Definition at line 350 of file transfrm.c.
Typedef Documentation
wherestackentry
typedef struct wherestackentry wherestackentry
Function Documentation
_contains_forall_index()
static LOGICAL _contains_forall_index (int ast, LOGICAL * flag) static
Definition at line 943 of file transfrm.c.
References ast, ASTLI_NEXT, ASTLI_SPTR, FALSE, ForallList, list, and TRUE.
Referenced by contains_forall_index().
_contains_sptr()
static LOGICAL _contains_sptr (int astSrc, LOGICAL * pflag) static
Definition at line 3859 of file transfrm.c.
References FALSE, parentMatch, pflag, sptrMatch, and TRUE.
Referenced by contains_sptr().
add_wheresym()
static void add_wheresym (ITEM ** wheresymlist, int wheresym) static
Definition at line 561 of file transfrm.c.
References getitem(), itemp, and TRANS_AREA.
Referenced by rewrite_block_where().
build_allocation_item()
static int build_allocation_item (int astdestparent, int astdestmem) static
Definition at line 3631 of file transfrm.c.
References ADD_LWBD, ADD_NUMDIM, ADD_UPBD, astb, ASTB::bnd, DTY, DTYG, ASTB::dtype, get_global_lower_index(), get_global_upper_index(), i, ASTB::i1, MAXSUBS, memsym_of_ast(), mk_cval(), mk_descr_id(), mk_member(), mk_subscr(), mk_triple(), ndim, and subscr.
Referenced by rewrite_allocatable_assignment().
build_conformable_func_node()
static int build_conformable_func_node (int astdest, int astsrc) static
Definition at line 3081 of file transfrm.c.
References A_OPTYPEP, ADD_LWAST, ADD_NUMDIM, ADD_UPAST, argt, ARGT_ARG, ast, astb, ASTB::bnd, build_sdsc_node(), DT_INT, ASTB::dtype, i, memsym_of_ast(), mk_argt(), mk_cval(), mk_extent_expr(), mk_func_node(), mk_id(), mk_unop(), mkRteRtnNm(), nargs, ndim, NEWDSCG, OP_VAL, RTE_conformable_11v, RTE_conformable_1dv, RTE_conformable_22v, RTE_conformable_2dv, RTE_conformable_33v, RTE_conformable_3dv, RTE_conformable_d1v, RTE_conformable_d2v, RTE_conformable_d3v, RTE_conformable_dd, RTE_conformable_dnv, RTE_conformable_ndv, RTE_conformable_nnv, SHD_LWB, SHD_NDIM, SHD_UPB, and sym_mkfunc().
Referenced by mk_conformable_test().
build_poly_func_node()
static int build_poly_func_node (int dest, int src, int intrin_type) static
Generate a call to poly_conform_types() that is used in polymorphic allocatable assignment.
Parameters
dest is the ast representing the LHS of a polymorphic assignment.
src is the ast representing the RHS of a polymorphic assignment.
intrin_type is an ast that represents a descriptor for an intrinsic scalar object when src represents an intrinsic scalar object. It's zero if src is not a non-zero intrinsic object.
Returns
the ast representing the function call to poly_conform_types().
Definition at line 3319 of file transfrm.c.
References A_OPTYPEP, argt, ARGT_ARG, ast, dest, DT_INT, find_descriptor_ast(), get_sdsc_ast(), memsym_of_ast(), mk_argt(), mk_cval1(), mk_func_node(), mk_id(), mk_unop(), mkRteRtnNm(), OP_VAL, RTE_poly_conform_types, src, and sym_mkfunc().
Referenced by mk_poly_test().
build_sdsc_node()
static int build_sdsc_node (int ast) static
Definition at line 3063 of file transfrm.c.
References ast, memsym_of_ast(), mk_descr_id(), mk_id(), mk_member(), sptr, and sym_of_ast().
Referenced by build_conformable_func_node().
check_subprogram()
static void check_subprogram (int std, int ast, int callast) static
Definition at line 1082 of file transfrm.c.
References A_ARGCNTG, A_STDP, arg, argt, ARGT_ARG, ast, cnt, i, make_forall(), memsym_of_ast(), normalize_forall(), sptr, std, and STD_AST.
Referenced by rewrite_into_forall().
chk_assumed_subscr()
static bool chk_assumed_subscr (int a) static
Checks whether the user specified an empty array subscript such as (:), (:,:), (:,:,:), etc.
Parameters
a is the array subscript ast (A_SUBSCR) to check.
Returns
true if a is an empty subscript; else false.
Definition at line 3898 of file transfrm.c.
References a, ASD_NDIM, ASD_SUBS, assert, ERR_Fatal, i, lboundMask, MAXDIMS, ndim, strideMask, t, and uboundMask.
Referenced by mk_ptr_subscr().
clear_dist_align()
static void clear_dist_align (void) static
Definition at line 353 of file transfrm.c.
References STB::firstusym, sptr, and stb.
Referenced by trans_process_align().
collapse_assignment()
static int collapse_assignment (int asn, int std) static
Definition at line 1772 of file transfrm.c.
References add_arg(), ADD_NUMELM, ast, astb, begin_call(), ccff_info(), check_member(), CNULL, contiguous_section(), CONVAL2G, convert_int(), STB::dbl0, DDTG, dest, DT_INT, DT_ISCMPLX, DT_ISLOG, DT_ISNUMERIC, DTY, error(), find_array(), first_element(), flg, STB::flt0, func, gbl, i, STB::i0, is_reshape(), is_zero(), STB::k0, ASTB::k1, lhs, lwb, mk_binop(), mk_unop(), mkRteRtnNm(), MSGOPT, ndim, NULL, one, OP_ADD, OP_MUL, OP_SUB, OP_VAL, FLG::opt, STB::quad0, RTE_mcopy1, RTE_mcopy16, RTE_mcopy2, RTE_mcopy4, RTE_mcopy8, RTE_mcopyz16, RTE_mcopyz32, RTE_mcopyz8, RTE_mset1, RTE_mset16, RTE_mset2, RTE_mset4, RTE_mset8, RTE_msetz16, RTE_msetz32, RTE_msetz8, RTE_mzero1, RTE_mzero16, RTE_mzero2, RTE_mzero4, RTE_mzero8, RTE_mzeroz16, RTE_mzeroz32, RTE_mzeroz8, SHD_LWB, SHD_NDIM, SHD_UPB, size_of(), src, stb, sym_mkfunc_nodesc(), sz, upb, and XBIT.
Referenced by rewrite_into_forall().
constant_shape()
static LOGICAL constant_shape (int shape) static
Definition at line 1250 of file transfrm.c.
References FALSE, lb, SHD_LWB, SHD_NDIM, SHD_UPB, TRUE, and ub.
Referenced by rewrite_into_forall().
contains_forall_index()
static LOGICAL contains_forall_index (int ast, int forall_list) static
Definition at line 960 of file transfrm.c.
References _contains_forall_index(), ast, ast_traverse(), ast_unvisit(), ast_visit(), FALSE, forall_list, ForallList, NULL, and result.
Referenced by rewrite_block_forall().
contains_sptr()
static LOGICAL contains_sptr (int astSrc, int sptrDst, int astparent) static
Definition at line 3875 of file transfrm.c.
References _contains_sptr(), ast_traverse(), ast_unvisit(), ast_visit(), FALSE, NULL, parentMatch, result, and sptrMatch.
Referenced by rewrite_allocatable_assignment().
copy_forall()
static int copy_forall (int forall) static
Definition at line 2362 of file transfrm.c.
References assert, and mk_stmt().
Referenced by inline_spread_shifts().
count_allocatable_members()
static int count_allocatable_members (int ast) static
This function counts the number of allocatable members/components in a derived type member expression (e.g., ab, abc, abcd, etc.).
Parameters
ast is the AST of the expression that we are testing.
Returns
an integer representing the number of allocatable members.
Definition at line 4021 of file transfrm.c.
References ast, and interr().
Referenced by rewrite_allocatable_assignment().
dbg_print_stmts()
void dbg_print_stmts (FILE * f)
Definition at line 4503 of file astout.c.
References ast, dbg_print_ast(), f, NULL, std, STD_AST, and STD_NEXT.
Referenced by transform().
find_allocatable_assignment()
static void find_allocatable_assignment (void) static
Definition at line 4763 of file transfrm.c.
References ast, DTYG, match(), rewrite_allocatable_assignment(), SEM::sc, sem, std, STD_AST, and STD_NEXT.
Referenced by transform().
find_const_bound_rhs()
static LOGICAL find_const_bound_rhs (int expr, int * rhs, int * shape) static
Definition at line 1125 of file transfrm.c.
References ASD_NDIM, ASD_SUBS, astb, ASTB::bnd, DTY, FALSE, find_const_bound_rhs(), i, lwb, n, ASTB::one, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, sptr, ss, st, TRUE, upb, and vector_member().
Referenced by find_const_bound_rhs(), and rewrite_into_forall().
free_tbl()
void free_tbl (void)
Definition at line 2469 of file transfrm.c.
References tbl::base, and FREE.
Referenced by convert_statements().
gen_alloc_mbr()
static void gen_alloc_mbr (int ast, int std) static
Definition at line 3690 of file transfrm.c.
References add_stmt_before(), ast, check_alloc_ptr_type(), is_unl_poly(), memsym_of_ast(), mk_allocate(), sptr, and std.
Referenced by rewrite_allocatable_assignment().
gen_allocated_check()
static void gen_allocated_check (int ast, int std, int atype, bool negate, bool is_assign_lhs, bool is_assign_lhs2) static
Generate an IF to see if ast is allocated and insert before std. Caller is responsible for generating ENDIF.
Parameters
atype Type of AST to generate, A_IFTHEN or A_ELSEIF.
negate Check for not allocated instead of allocated.
is_assign_lhs True if this check is for the LHS of an assignment
Definition at line 3465 of file transfrm.c.
References A_OPTYPEP, add_stmt_before(), argt, ARGT_ARG, assert, ast, DT_LOG, ERR_Fatal, getsymbol(), mk_argt(), mk_func_node(), mk_id(), mk_stmt(), mk_unop(), OP_LNOT, std, and STD_RESCOPE.
Referenced by gen_dealloc_if_allocated(), rewrite_allocatable_assignment(), and rewrite_deallocate().
gen_bounds_assignments()
static void gen_bounds_assignments (int astdestparent, int astdestmem, int astsrcparent, int astsrcmem, int std) static
Definition at line 3522 of file transfrm.c.
References ADD_EXTNTAST, ADD_LWBD, ADD_NUMDIM, add_stmt_before(), ADD_UPBD, assert, ast, astb, ASTB::bnd, DDTG, DT_INT, ASTB::dtype, ERR_Fatal, extent_of_shape(), get_global_extent_index(), get_global_lower_index(), get_global_upper_index(), get_len_of_deferchar_ast(), i, is_array_dtype(), is_deferlenchar_ast(), memsym_of_ast(), mk_assn_stmt(), mk_bounds_shape(), mk_cval(), mk_descr_id(), mk_mem_ptr_shape(), mk_member(), mk_subscr(), ndim, SHD_LWB, SHD_NDIM, SHD_UPB, std, STD_AST, string_expr_length(), and subscr.
Referenced by rewrite_allocatable_assignment().
gen_dealloc_if_allocated()
void gen_dealloc_if_allocated (int ast, int std)
Definition at line 4754 of file transfrm.c.
References add_stmt_before(), ast, gen_allocated_check(), mk_deallocate(), mk_stmt(), and std.
Referenced by allocate_lhs_if_needed(), and rewrite_allocatable_assignment().
gen_dealloc_mbr()
static void gen_dealloc_mbr (int ast, int std) static
Definition at line 3703 of file transfrm.c.
References add_stmt_before(), allocatable_member(), ast, memsym_of_ast(), mk_deallocate(), rewrite_deallocate(), and std.
Referenced by rewrite_allocatable_assignment().
gen_do_ends()
static void gen_do_ends (int docnt, int std) static
Definition at line 3510 of file transfrm.c.
References add_stmt_before(), i, mk_stmt(), and std.
Referenced by handle_allocatable_members(), rewrite_allocatable_assignment(), and rewrite_deallocate().
gen_dos_over_shape()
static int gen_dos_over_shape (int shape, int std) static
Definition at line 3490 of file transfrm.c.
References add_stmt_before(), astb, ASTB::bnd, ASTB::dtype, get_temp(), i, MAXSUBS, mk_asd(), mk_id(), mk_stmt(), ndim, SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, std, and sub.
Referenced by handle_allocatable_members(), rewrite_allocatable_assignment(), and rewrite_deallocate().
get_finfo()
int get_finfo (int forall, int a)
Definition at line 339 of file transfrm.c.
References a, A_NCOUNTG, FINFO_AST, and i.
Referenced by forall_2_sec().
get_init_idx()
int get_init_idx (int i, int dtype)
Definition at line 298 of file transfrm.c.
References i, init_idx, num_init_idx, SYMUTL::sc, sym_get_scalar(), and symutl.
Referenced by forall_make_same_idx(), and make_forall().
get_sdsc_ast()
static int get_sdsc_ast (SPTR sptrsrc, int astsrc) static
Computes the descriptor on the right hand side of an allocatable polymorphic assignment.
Parameters
sptrsrc is the symbol table pointer of the object associated with the right hand side of a polymorphic assignment.
astsrc is the AST representing the right hand side of a polymorphic assignment.
Returns
an AST representing the descriptor for the right hand side of the polymorphic assignment.
Definition at line 3985 of file transfrm.c.
References check_member(), DTY, FALSE, find_descriptor_ast(), gbl, get_static_descriptor(), get_static_type_descriptor(), get_type_descr_arg(), mk_id(), and TRUE.
Referenced by build_poly_func_node(), and rewrite_allocatable_assignment().
get_tbl()
int get_tbl (void)
Definition at line 2475 of file transfrm.c.
References tbl::avl, tbl::base, errfatal(), NEED, NULL, tbl::size, and SPTR_MAX.
Referenced by conv_allocate().
handle_allocatable_members()
static void handle_allocatable_members (int astdest, int astsrc, int std, bool non_conformable) static
Definition at line 3734 of file transfrm.c.
References add_nullify_ast(), add_ptr_assign(), add_stmt_after(), add_stmt_before(), allocatable_member(), ASD_NDIM, ASD_SUBS, assn(), DDTG, DTY, FALSE, gbl, gen_do_ends(), gen_dos_over_shape(), i, is_tbp_or_final(), mem(), memsym_of_ast(), mk_assn_stmt(), mk_id(), mk_mem_ptr_shape(), mk_member(), ndim, normalize_subscripts(), NOSYM, offset, ptr_assign(), rewrite_allocatable_assignment(), std, and subscript_allocmem().
Referenced by rewrite_allocatable_assignment().
in_wheresymlist()
static LOGICAL in_wheresymlist (ITEM * list, int sptr) static
Definition at line 570 of file transfrm.c.
References FALSE, ITEM_END, itemp, list, sptr, and TRUE.
Referenced by rewrite_block_where().
init_finfo()
static void init_finfo (void) static
Definition at line 318 of file transfrm.c.
References FINFO_TBL::avl, FINFO_TBL::base, finfot, NEW, and FINFO_TBL::size.
Referenced by transform_init().
init_tbl()
void init_tbl (void)
Definition at line 2461 of file transfrm.c.
References tbl::avl, tbl::base, NEW, and tbl::size.
Referenced by convert_statements().
init_where()
static void init_where (void) static
Definition at line 486 of file transfrm.c.
References wherestack::base, wherestackentry::elsewhere, wherestackentry::forall, NEW, wherestack::size, top, wherestack::topforall, wherestack::topwhere, and wherestackentry::where.
Referenced by rewrite_block_where().
inline_spread_shifts()
static int inline_spread_shifts (int asgn_ast, int forall_ast, int inlist) static
Definition at line 2146 of file transfrm.c.
References A_ARGCNTG, A_OPTYPEG, A_OPTYPEP, add_astli(), argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, astb, ASTLI_HEAD, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, ASTB::bnd, boundary, cdim, copy_forall(), count, DDTG, delete_astli(), dim, DT_INT, ASTB::dtype, get_int_cval(), i, ASTB::i1, inlist(), list, MAXSUBS, mk_binop(), mk_cval(), mk_func_node(), mk_stmt(), mk_subscr(), mk_triple(), nargs, ndim, normalize_forall(), OP_ADD, OP_SUB, ASTB::ptr0, search_forall_idx(), SHD_LWB, SHD_STRIDE, SHD_UPB, shift, and start_astli().
Referenced by normalize_forall().
is_array_type()
LOGICAL is_array_type (int sptr)
Definition at line 2595 of file transfrm.c.
References DTY, FALSE, result, sptr, and TRUE.
Referenced by convert_subscript(), declare_array_dummys(), desc_need_arrays(), emit_kopy_in(), first_element_from_section(), handle_seq_section(), inline_hlocalizebnds(), is_legal_lhs(), needs_redim(), newargs_for_entry(), set_assumed_bounds(), and trans_get_descrs().
is_bad_dtype()
LOGICAL is_bad_dtype (int dtype)
Definition at line 2587 of file transfrm.c.
References DTYG, FALSE, and TRUE.
Referenced by declare_array_dummys(), emit_alnd(), emit_kopy_in(), emit_secd(), gen_ptr_in(), gen_ptr_out(), init_newargs(), make_alnd(), make_secd(), needs_redim(), newargs_for_entry(), share_alnd(), share_secd(), trans_get_descrs(), and transform_call().
is_reshape()
static LOGICAL is_reshape (int ast) static
Definition at line 1756 of file transfrm.c.
References ast, FALSE, SYMNAME, and TRUE.
Referenced by collapse_assignment().
make_forall()
int make_forall (int shape, int astmem, int mask_ast, int lc)
Definition at line 2375 of file transfrm.c.
References add_astli(), ast, astb, ASTLI_HEAD, ASTLI_SPTR, ASTLI_TRIPLE, ASTB::bnd, check_member(), ASTB::dtype, flg, get_init_idx(), i, interr(), list, lwb, MAXSUBS, mk_stmt(), mk_triple(), normalize_forall(), SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, FLG::smp, start_astli(), stride, sym_of_ast(), trans_clridx(), and upb.
Referenced by check_subprogram(), copy_arg_to_seq_tmp(), inline_reduction_f90(), rewrite_into_forall(), transform_elemental(), transform_merge(), and transform_mvbits().
mask_on_lhs()
static LOGICAL mask_on_lhs (int mask, int lhs) static
Definition at line 414 of file transfrm.c.
References assert, ast_traverse(), ast_unvisit(), ast_visit(), FALSE, lhs, NULL, sptr, srch_sym(), TRUE, and wherestuff.
Referenced by rewrite_block_where().
mk_allocate()
int mk_allocate (int ast)
Definition at line 3386 of file transfrm.c.
References A_TKNP, ast, and mk_stmt().
Referenced by allocate_lhs_if_needed(), gen_alloc_mbr(), and rewrite_allocatable_assignment().
mk_bounds_shape()
static int mk_bounds_shape (int shape) static
Definition at line 3617 of file transfrm.c.
References add_shape_rank(), add_shape_spec(), astb, ASTB::bnd, extent_of_shape(), i, lb, mk_shape(), ndim, ASTB::one, SHD_NDIM, and ub.
Referenced by gen_bounds_assignments().
mk_conformable_test()
int mk_conformable_test (int dest, int src, int optype)
Definition at line 3298 of file transfrm.c.
References astb, build_conformable_func_node(), cmp(), dest, DT_INT, func, ASTB::i0, mk_binop(), mk_stmt(), optype(), and src.
Referenced by allocate_lhs_if_needed(), and rewrite_allocatable_assignment().
mk_deallocate()
int mk_deallocate (int ast)
Definition at line 3395 of file transfrm.c.
References A_TKNP, ast, and mk_stmt().
Referenced by gen_dealloc_if_allocated(), gen_dealloc_mbr(), rewrite_allocatable_assignment(), and rewrite_deallocate().
mk_descr_id()
static int mk_descr_id (SPTR sptr) static
Definition at line 3050 of file transfrm.c.
References ERR_Fatal, interr(), mk_id(), and sptr.
Referenced by build_allocation_item(), build_sdsc_node(), and gen_bounds_assignments().
mk_finfo()
static int mk_finfo (void) static
Definition at line 326 of file transfrm.c.
References FINFO_TBL::avl, FINFO_TBL::base, errfatal(), finfot, NEED, NULL, and FINFO_TBL::size.
Referenced by normalize_id().
mk_poly_test()
static int mk_poly_test (int dest, int src, int optype, int intrin_type) static
Same as mk_conformable_test() above, except it generates a test between two polymorphic scalar objects.
Parameters
dest is the ast representing the LHS of a polymorphic assignment.
src is the ast representing the RHS of a polymorphic assignment.
optype is the type of check (see mk_conformable_test() above).
intrin_type is an ast that represents a descriptor for an intrinsic scalar object when src represents an intrinsic scalar object. It's zero if src is not a non-zero intrinsic object.
Returns
an ast representing the "if statement" for the polymorphic test.
Definition at line 3376 of file transfrm.c.
References astb, build_poly_func_node(), cmp(), dest, DT_INT, func, ASTB::i0, mk_binop(), mk_stmt(), optype(), and src.
Referenced by rewrite_allocatable_assignment().
mk_ptr_subscr()
static int mk_ptr_subscr (int subAst, int std) static
Create a non-subscripted "alias" or "replacement" ast to a subscripted expression.
This is used in a poly_asn() call where the source argument cannot directly handle an A_SUBSCR which could be an array slice. This function either returns the array object if it has an empty subscript expression or a pointer to a contiguous shallow copy of the array slice.
Parameters
subAst is the subscripted expression that we are processing.
std is the std for adding statements.
Returns
the replacement ast.
Definition at line 3934 of file transfrm.c.
References add_stmt_after(), add_stmt_before(), ast, check_and_add_auto_dealloc_from_ast(), chk_assumed_subscr(), DDTG, gen_alloc_dealloc(), MAXRANK, mk_assign_sptr(), mk_assn_stmt(), mk_id(), mk_stmt(), std, and subscr.
Referenced by rewrite_allocatable_assignment().
nice_mask()
static void nice_mask (int ast, LOGICAL * nice) static
Definition at line 372 of file transfrm.c.
References A_OPTYPEG, ast, FALSE, and OP_XTOX.
Referenced by nice_where_mask().
nice_where_mask()
static LOGICAL nice_where_mask (int ast) static
Definition at line 395 of file transfrm.c.
References ast, ast_traverse(), ast_unvisit(), ast_visit(), nice_mask(), NULL, and TRUE.
Referenced by rewrite_block_where().
normalize_forall()
int normalize_forall (int forall_ast, int asgn_ast, int inlist)
Definition at line 1628 of file transfrm.c.
References A_ARGCNTG, A_MEM_ORDERG, A_MEM_ORDERP, A_OPTYPEG, A_OPTYPEP, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, ast, DT_PTR, DTY, elemental_func_call(), i, inline_spread_shifts(), inlist(), interr(), is_iso_cptr(), MAXSUBS, mk_binop(), mk_convert(), mk_member(), mk_paren(), mk_stmt(), mk_subscr(), mk_substr(), mk_unop(), n, nargs, normalize_forall(), normalize_id(), and vector_member().
Referenced by check_subprogram(), copy_arg_to_seq_tmp(), inline_reduction_f90(), inline_spread_shifts(), make_forall(), normalize_forall(), normalize_forall_array(), rewrite_into_forall(), transform_elemental(), transform_merge(), and transform_mvbits().
normalize_forall_array()
static int normalize_forall_array (int forall_ast, int arr_ast, int inlist) static
Definition at line 1495 of file transfrm.c.
References ASD_NDIM, ASD_SUBS, assert, ast, ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, check_member(), DDTG, FALSE, i, inlist(), interr(), j, list, lwb, MAXSUBS, mk_id(), mk_member(), mk_subscr(), n1, normalize_forall(), normalize_subscript(), search_arr(), SHD_LWB, SHD_NDIM, SHD_STRIDE, sptr, stride, subs1, TRUE, and vector_member().
Referenced by normalize_id().
normalize_id()
static int normalize_id (int forall_ast, int asgn_ast, int inlist) static
Definition at line 1610 of file transfrm.c.
References A_NCOUNTG, A_NCOUNTP, FINFO_AST, FINFO_SHAPE, FINFO_TYPE, inlist(), mk_finfo(), nc, and normalize_forall_array().
Referenced by normalize_forall().
normalize_subscript()
static int normalize_subscript (int ast, int oldlb, int oldstride, int newlb, int newstride) static
Definition at line 1443 of file transfrm.c.
References ast, astb, ASTB::bnd, ASTB::dtype, mk_binop(), mk_isz_cval(), ASTB::one, OP_ADD, OP_DIV, OP_MUL, and OP_SUB.
Referenced by normalize_forall_array(), and normalize_subscripts().
normalize_subscripts()
static int normalize_subscripts (int oldasd, int oldshape, int newshape) static
Definition at line 4814 of file transfrm.c.
References ASD_NDIM, ASD_SUBS, assert, ERR_Fatal, i, MAXSUBS, mk_asd(), ndim, normalize_subscript(), SHD_LWB, SHD_NDIM, and SHD_STRIDE.
Referenced by handle_allocatable_members(), and rewrite_allocatable_assignment().
nullify_member()
static void nullify_member (int ast, int std, int sptr) static
Definition at line 3714 of file transfrm.c.
References add_nullify_ast(), add_stmt_before(), ast, DDTG, DTY, is_tbp_or_final(), mk_id(), mk_member(), NOSYM, sptr, and std.
Referenced by rewrite_allocatable_assignment().
pop_forall()
static void pop_forall (int * forall_std) static
Definition at line 548 of file transfrm.c.
References wherestack::base, wherestackentry::forall, top, and wherestack::topforall.
Referenced by rewrite_block_where().
pop_where()
static void pop_where (int * where, int * elsewhere) static
Definition at line 522 of file transfrm.c.
References wherestack::base, wherestackentry::elsewhere, top, wherestack::topwhere, and wherestackentry::where.
Referenced by rewrite_block_where().
push_elsewhere()
static void push_elsewhere (int elsewhere_std) static
Definition at line 510 of file transfrm.c.
References wherestack::base, wherestackentry::elsewhere, interr(), top, and wherestack::topwhere.
Referenced by rewrite_block_where().
push_forall()
static void push_forall (int forall_std) static
Definition at line 537 of file transfrm.c.
References wherestack::base, wherestackentry::forall, NEED, wherestack::size, top, and wherestack::topforall.
Referenced by rewrite_block_where().
push_where()
static void push_where (int where_std) static
Definition at line 498 of file transfrm.c.
References wherestack::base, wherestackentry::elsewhere, NEED, wherestack::size, top, wherestack::topwhere, and wherestackentry::where.
Referenced by rewrite_block_where().
reset_init_idx()
void reset_init_idx (void)
Definition at line 185 of file transfrm.c.
References i, init_idx, and MAXSUBS.
Referenced by inline_reduction_f90().
rewrite_allocatable_assignment()
static void rewrite_allocatable_assignment (int astasgn, int std, bool non_conformable, bool handle_alloc_members) static
Definition at line 4074 of file transfrm.c.
References A_OPTYPEG, A_OPTYPEP, AD_DPTR, AD_NUMDIM, add_arg(), add_ptr_assign(), add_shapely_subscripts(), add_stmt_after(), add_stmt_before(), allocatable_member(), argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, assert, ast, ast_intr(), ast_is_sym(), ast_to_comment(), astb, begin_call(), ASTB::bnd, build_allocation_item(), check_pointer_type(), contains_sptr(), count_allocatable_members(), DDTG, DT_INT, DT_ISBASIC, DT_LOG, SEM::dtemps, DTY, DTYG, ASTB::dtype, dtype_to_arg(), dtype_with_shape(), dup_array_dtype(), ERR_Fatal, ERR_Warning, FALSE, find_descriptor_ast(), gen_alloc_mbr(), gen_allocated_check(), gen_automatic_reallocation(), gen_bounds_assignments(), gen_dealloc_if_allocated(), gen_dealloc_mbr(), gen_deallocate_arrays(), gen_do_ends(), gen_dos_over_shape(), gen_finalization_for_sym(), gen_init_unl_poly_desc(), gen_set_len_ast(), get_arr_temp(), get_ch_temp(), get_len_of_deferchar_ast(), get_sdsc_ast(), get_static_descriptor(), get_type(), getcctmp_sc(), handle_allocatable_members(), has_finalized_component(), has_vector_subscript_ast(), i, ASTB::i1, init_sdsc_bounds(), intast_sym, interr(), is_deferlenchar_ast(), is_tbp_or_final(), is_unl_poly(), lboundMask, len, MAXDIMS, memsym_of_ast(), mk_allocate(), mk_argt(), mk_assn_stmt(), mk_binop(), mk_conformable_test(), mk_cval(), mk_cval1(), mk_deallocate(), mk_func_node(), mk_id(), mk_mem_ptr_shape(), mk_member(), mk_poly_test(), mk_ptr_subscr(), mk_set_type_call(), mk_stmt(), mk_subscr(), mk_triple(), mk_unop(), mkRteRtnNm(), move_stmts_after(), move_stmts_before(), ndim, ndims, normalize_subscripts(), NOSYM, nullify_member(), OP_GT, OP_LE, OP_LOR, OP_LT, OP_NE, OP_VAL, rewrite_allocatable_assignment(), RTE_poly_asn, SEM::sc, sem, size_ast_of(), sptr, std, STD_LAST, STD_NEXT, STD_RESCOPE, strideMask, string_expr_length(), subscript_allocmem(), sym_mkfunc_nodesc(), sym_of_ast(), TRUE, TY_CHAR, TY_NCHAR, uboundMask, and XBIT.
Referenced by find_allocatable_assignment(), handle_allocatable_members(), and rewrite_allocatable_assignment().
rewrite_block_forall()
static void rewrite_block_forall (void) static
Definition at line 975 of file transfrm.c.
References add_stmt_before(), assert, ast, ast_to_comment(), concatenate_list(), contains_forall_index(), DT_LOG, gbl, interr(), list, MAXSUBS, mk_binop(), mk_stmt(), OP_LAND, stack, std, STD_AST, STD_LINENO, STD_NEXT, stmt, and top.
Referenced by transform().
rewrite_block_where()
static void rewrite_block_where (void) static
Definition at line 585 of file transfrm.c.
References A_STDP, add_stmt_after(), add_stmt_before(), add_wheresym(), assert, ast, ast_to_comment(), astb, ASTLI_NEXT, ASTLI_SPTR, wherestack::base, CNULL, conform_shape(), DT_LOG, error(), FALSE, FORALLNDXG, FORALLNDXP, FREE, gbl, ASTB::i0, in_wheresymlist(), init_where(), interr(), ITEM_END, lhs, mask_on_lhs(), MAXSUBS, memsym_of_ast(), mk_assign_sptr(), mk_assn_stmt(), mk_binop(), mk_id(), mk_mem_allocate(), mk_mem_deallocate(), mk_stmt(), mk_unop(), nice_where_mask(), OP_LNOT, OP_SCAND, pop_forall(), pop_where(), push_elsewhere(), push_forall(), push_where(), rewrite_where_expr(), search_conform_array(), set_descriptor_sc(), sptr, std, STD_AST, STD_LINENO, STD_NEXT, subscr, wherestack::topwhere, and TRUE.
Referenced by transform().
rewrite_deallocate()
void rewrite_deallocate (int ast, bool is_assign_lhs, int std)
Definition at line 3405 of file transfrm.c.
References add_stmt_before(), allocatable_member(), ASD_NDIM, assert, ast, DDTG, DTY, ERR_Fatal, FALSE, gen_allocated_check(), gen_do_ends(), gen_dos_over_shape(), is_tbp_or_final(), memsym_of_ast(), mk_deallocate(), mk_id(), mk_member(), mk_stmt(), mk_subscr_copy(), NOSYM, rewrite_deallocate(), std, subscript_allocmem(), and TRUE.
Referenced by gen_dealloc_mbr(), rewrite_calls(), and rewrite_deallocate().
rewrite_into_forall()
static void rewrite_into_forall (void) static
Fortran transformation module.
Definition at line 1270 of file transfrm.c.
References A_STDP, add_stmt_after(), ast, ast_to_comment(), check_subprogram(), CNULL, collapse_assignment(), conform_shape(), constant_shape(), error(), find_const_bound_rhs(), flg, gbl, interr(), lhs, make_forall(), normalize_forall(), FLG::opt, set_descriptor_sc(), std, STD_AST, STD_LINENO, STD_NEXT, STD_ZTRIP, and XBIT.
Referenced by transform().
rewrite_where_expr()
static void rewrite_where_expr (int where_std, int endwhere_std) static
Definition at line 436 of file transfrm.c.
References add_stmt_before(), ast, mk_stmt(), arg_gbl::std, STD_AST, STD_NEXT, and STD_PREV.
Referenced by rewrite_block_where().
search_arr()
static int search_arr (int ast) static
Definition at line 1429 of file transfrm.c.
References assert, ast, and DTY.
Referenced by normalize_forall_array().
set_initial_s1()
static void set_initial_s1 (void) static
Definition at line 219 of file transfrm.c.
References DDTG, DTY, STB::firstusym, NEWDSCG, size_of(), sptr, stb, and XBIT.
Referenced by transform().
srch_sym()
static void srch_sym (int ast, LOGICAL * has_sym) static
Definition at line 407 of file transfrm.c.
References ast, TRUE, and wherestuff.
Referenced by mask_on_lhs().
subscript_allocmem()
static int subscript_allocmem (int aref, int asd) static
Definition at line 4838 of file transfrm.c.
References ASD_NDIM, ASD_SUBS, assert, ast, DTY, ERR_Fatal, i, interr(), MAXSUBS, mk_asd(), mk_member(), mk_subscr(), mk_subscr_copy(), n, sub, subscript_allocmem(), tmp, and vector_member().
Referenced by handle_allocatable_members(), rewrite_allocatable_assignment(), rewrite_deallocate(), and subscript_allocmem().
trans_clridx()
static void trans_clridx (void) static
Definition at line 2571 of file transfrm.c.
References p.
Referenced by make_forall().
trans_freeidx()
static void trans_freeidx (void) static
Definition at line 2580 of file transfrm.c.
References freearea(), and TRANS_AREA.
Referenced by transform().
trans_get_descrs()
static void trans_get_descrs (void) static
Definition at line 2523 of file transfrm.c.
References STB::firstusym, is_array_type(), is_bad_dtype(), sptr, stb, and trans_mkdescr().
Referenced by transform().
trans_process_align()
void trans_process_align (void)
Definition at line 2494 of file transfrm.c.
References baddenominator, badnumerator, badpointer1, clear_dist_align(), gbl, and XBIT.
transform()
void transform (void)
Definition at line 79 of file transfrm.c.
References dbg_print_stmts(), DBGBIT, dstda(), dstdpa(), ERR_Severe, f90_fini_pointsto(), find_allocatable_assignment(), flg, gbl, interr(), FLG::opt, SEM::p_dealloc, pghpf_local_mode_sptr, pghpf_type_sptr, points_to(), rewrite_block_forall(), rewrite_block_where(), rewrite_calls(), rewrite_forall(), rewrite_forall_pure(), rewrite_into_forall(), RU_BDATA, sem, set_initial_s1(), trans_freeidx(), trans_get_descrs(), transform_init(), and XBIT.
Referenced by tan_piby4().
transform_init()
static void transform_init (void) static
Definition at line 194 of file transfrm.c.
References gbl, i, init_finfo(), init_idx, init_region(), pure_gbl::local_mode, MAXSUBS, num_init_idx, pghpf_local_mode_sptr, pghpf_type_sptr, and RU_BDATA.
Referenced by transform().
vector_member()
LOGICAL vector_member (int memast)
Return TRUE if memast is an A_MEM for an array, or memast is an A_SUBSCR whose parent is an A_MEM and which has triplet subscripts.
Definition at line 1471 of file transfrm.c.
References ASD_NDIM, ASD_SUBS, DTY, FALSE, i, n, sptr, ss, and TRUE.
Referenced by build_array_ref(), find_const_bound_rhs(), normalize_forall(), normalize_forall_array(), and subscript_allocmem().
Variable Documentation
baddenominator
long baddenominator = 0
Definition at line 2490 of file transfrm.c.
Referenced by trans_process_align().
badnumerator
long badnumerator = 99
Definition at line 2489 of file transfrm.c.
Referenced by trans_process_align().
badpointer1
int* badpointer1 = (int *)0
Definition at line 2487 of file transfrm.c.
Referenced by trans_process_align().
badpointer2
long* badpointer2 = (long *)1
Definition at line 2488 of file transfrm.c.
finfot
FINFO_TBL finfot
Definition at line 70 of file transfrm.c.
Referenced by comm_fini(), init_finfo(), and mk_finfo().
ForallList
int ForallList static
Definition at line 939 of file transfrm.c.
Referenced by _contains_forall_index(), and contains_forall_index().
idxlist
struct idxlist * idxlist static
init_idx
int init_idx[MAXSUBS+MAXSUBS] static
Definition at line 71 of file transfrm.c.
Referenced by get_init_idx(), reset_init_idx(), and transform_init().
num_init_idx
int num_init_idx static
Definition at line 72 of file transfrm.c.
Referenced by get_init_idx(), and transform_init().
parentMatch
int parentMatch static
Definition at line 3855 of file transfrm.c.
Referenced by _contains_sptr(), and contains_sptr().
pghpf_local_mode_sptr
int pghpf_local_mode_sptr = 0
Definition at line 76 of file transfrm.c.
Referenced by lower_init_sym(), transform(), and transform_init().
pghpf_type_sptr
int pghpf_type_sptr extern
Definition at line 577 of file rest.c.
Referenced by declare_type(), pghpf_type(), transform(), and transform_init().
pure_gbl
struct pure_gbl pure_gbl
Definition at line 73 of file transfrm.c.
sptr
int sptr
Definition at line 368 of file transfrm.c.
Referenced by build_sdsc_node(), check_subprogram(), clear_dist_align(), find_const_bound_rhs(), gen_alloc_mbr(), in_wheresymlist(), is_array_type(), mask_on_lhs(), mk_descr_id(), normalize_forall_array(), nullify_member(), rewrite_allocatable_assignment(), rewrite_block_where(), set_initial_s1(), trans_get_descrs(), and vector_member().
sptrMatch
int sptrMatch static
Definition at line 3854 of file transfrm.c.
Referenced by _contains_sptr(), and contains_sptr().
wherestack
struct wherestack wherestack = {(wherestackentry *)0, 0, 0, 0}
struct { ... } wherestuff
Referenced by mask_on_lhs(), and srch_sym().