flang: transfrm.h File Reference
transfrm.h File Reference
macros, definitons, and prototypes for Fortran transformation module
#include "universal.h"
Classes
struct tlist
Typedefs
typedef struct tlist TLIST
Functions
void transform (void)
void reset_init_idx (void)
int get_init_idx (int i, int dtype)
int get_finfo (int forall, int a)
LOGICAL vector_member (int memast)
Return TRUE if memast is an A_MEM for an array, or memast is an A_SUBSCR whose parent is an A_MEM and which has triplet subscripts.
int normalize_forall (int forall_ast, int asgn_ast, int inlist)
int make_forall (int shape, int astmem, int mask_ast, int lc)
void init_tbl (void)
void free_tbl (void)
int get_tbl (void)
void trans_process_align (void)
LOGICAL is_bad_dtype (int dtype)
LOGICAL is_array_type (int sptr)
int mk_conformable_test (int dest, int src, int optype)
int mk_allocate (int ast)
int mk_deallocate (int ast)
void rewrite_deallocate (int ast, bool is_assign_lhs, int std)
void gen_dealloc_if_allocated (int ast, int std)
Detailed Description
macros, definitons, and prototypes for Fortran transformation module
Definition in file transfrm.h.
Typedef Documentation
TLIST
typedef struct tlist TLIST
Function Documentation
free_tbl()
void free_tbl (void)
Definition at line 2469 of file transfrm.c.
References tbl::base, and FREE.
Referenced by convert_statements().
gen_dealloc_if_allocated()
void gen_dealloc_if_allocated (int ast, int std)
Definition at line 4754 of file transfrm.c.
References add_stmt_before(), ast, gen_allocated_check(), mk_deallocate(), mk_stmt(), and std.
Referenced by allocate_lhs_if_needed(), and rewrite_allocatable_assignment().
get_finfo()
int get_finfo (int forall, int a)
Definition at line 339 of file transfrm.c.
References a, A_NCOUNTG, FINFO_AST, and i.
Referenced by forall_2_sec().
get_init_idx()
int get_init_idx (int i, int dtype)
Definition at line 298 of file transfrm.c.
References i, init_idx, num_init_idx, SYMUTL::sc, sym_get_scalar(), and symutl.
Referenced by forall_make_same_idx(), and make_forall().
get_tbl()
int get_tbl (void)
Definition at line 2475 of file transfrm.c.
References tbl::avl, tbl::base, errfatal(), NEED, NULL, tbl::size, and SPTR_MAX.
Referenced by conv_allocate().
init_tbl()
void init_tbl (void)
Definition at line 2461 of file transfrm.c.
References tbl::avl, tbl::base, NEW, and tbl::size.
Referenced by convert_statements().
is_array_type()
LOGICAL is_array_type (int sptr)
Definition at line 2595 of file transfrm.c.
Referenced by trans_get_descrs().
is_bad_dtype()
LOGICAL is_bad_dtype (int dtype)
Definition at line 2587 of file transfrm.c.
References DTYG, FALSE, and TRUE.
Referenced by declare_array_dummys(), emit_alnd(), emit_kopy_in(), emit_secd(), gen_ptr_in(), gen_ptr_out(), init_newargs(), make_alnd(), make_secd(), needs_redim(), newargs_for_entry(), share_alnd(), share_secd(), trans_get_descrs(), and transform_call().
make_forall()
int make_forall (int shape, int astmem, int mask_ast, int lc)
Definition at line 2375 of file transfrm.c.
References add_astli(), ast, astb, ASTLI_HEAD, ASTLI_SPTR, ASTLI_TRIPLE, ASTB::bnd, check_member(), ASTB::dtype, flg, get_init_idx(), i, interr(), list, lwb, MAXSUBS, mk_stmt(), mk_triple(), normalize_forall(), SHD_LWB, SHD_NDIM, SHD_STRIDE, SHD_UPB, FLG::smp, start_astli(), stride, sym_of_ast(), trans_clridx(), and upb.
Referenced by check_subprogram(), copy_arg_to_seq_tmp(), inline_reduction_f90(), rewrite_into_forall(), transform_elemental(), transform_merge(), and transform_mvbits().
mk_allocate()
int mk_allocate (int ast)
Definition at line 3386 of file transfrm.c.
References A_TKNP, ast, and mk_stmt().
Referenced by allocate_lhs_if_needed(), gen_alloc_mbr(), and rewrite_allocatable_assignment().
mk_conformable_test()
int mk_conformable_test (int dest, int src, int optype)
Definition at line 3298 of file transfrm.c.
References astb, build_conformable_func_node(), cmp(), dest, DT_INT, func, ASTB::i0, mk_binop(), mk_stmt(), optype(), and src.
Referenced by allocate_lhs_if_needed(), and rewrite_allocatable_assignment().
mk_deallocate()
int mk_deallocate (int ast)
Definition at line 3395 of file transfrm.c.
References A_TKNP, ast, and mk_stmt().
Referenced by gen_dealloc_if_allocated(), gen_dealloc_mbr(), rewrite_allocatable_assignment(), and rewrite_deallocate().
normalize_forall()
int normalize_forall (int forall_ast, int asgn_ast, int inlist)
Definition at line 1628 of file transfrm.c.
References A_ARGCNTG, A_MEM_ORDERG, A_MEM_ORDERP, A_OPTYPEG, A_OPTYPEP, argt, ARGT_ARG, ASD_NDIM, ASD_SUBS, ast, DT_PTR, DTY, elemental_func_call(), i, inline_spread_shifts(), inlist(), interr(), is_iso_cptr(), MAXSUBS, mk_binop(), mk_convert(), mk_member(), mk_paren(), mk_stmt(), mk_subscr(), mk_substr(), mk_unop(), n, nargs, normalize_forall(), normalize_id(), and vector_member().
Referenced by check_subprogram(), copy_arg_to_seq_tmp(), inline_reduction_f90(), inline_spread_shifts(), make_forall(), normalize_forall(), normalize_forall_array(), rewrite_into_forall(), transform_elemental(), transform_merge(), and transform_mvbits().
reset_init_idx()
void reset_init_idx (void)
Definition at line 185 of file transfrm.c.
rewrite_deallocate()
void rewrite_deallocate (int ast, bool is_assign_lhs, int std)
Definition at line 3405 of file transfrm.c.
References add_stmt_before(), allocatable_member(), ASD_NDIM, assert, ast, DDTG, DTY, ERR_Fatal, FALSE, gen_allocated_check(), gen_do_ends(), gen_dos_over_shape(), is_tbp_or_final(), memsym_of_ast(), mk_deallocate(), mk_id(), mk_member(), mk_stmt(), mk_subscr_copy(), NOSYM, rewrite_deallocate(), std, subscript_allocmem(), and TRUE.
Referenced by gen_dealloc_mbr(), rewrite_calls(), and rewrite_deallocate().
trans_process_align()
void trans_process_align (void)
Definition at line 2494 of file transfrm.c.
References baddenominator, badnumerator, badpointer1, clear_dist_align(), gbl, and XBIT.
transform()
void transform (void)
Definition at line 79 of file transfrm.c.
References dbg_print_stmts(), DBGBIT, dstda(), dstdpa(), ERR_Severe, f90_fini_pointsto(), find_allocatable_assignment(), flg, gbl, interr(), FLG::opt, SEM::p_dealloc, pghpf_local_mode_sptr, pghpf_type_sptr, points_to(), rewrite_block_forall(), rewrite_block_where(), rewrite_calls(), rewrite_forall(), rewrite_forall_pure(), rewrite_into_forall(), RU_BDATA, sem, set_initial_s1(), trans_freeidx(), trans_get_descrs(), transform_init(), and XBIT.
Referenced by tan_piby4().
vector_member()
LOGICAL vector_member (int memast)
Return TRUE if memast is an A_MEM for an array, or memast is an A_SUBSCR whose parent is an A_MEM and which has triplet subscripts.
Definition at line 1471 of file transfrm.c.
References ASD_NDIM, ASD_SUBS, DTY, FALSE, i, n, sptr, ss, and TRUE.
Referenced by build_array_ref(), find_const_bound_rhs(), normalize_forall(), normalize_forall_array(), and subscript_allocmem().