flang: type.h File Reference
type.h File Reference
F2003 polymorphic/OOP support.
#include "fioMacros.h"
Classes
struct layout_desc
Layout descriptor.
struct object_desc
The object_desc structure describes an `‘OOP’' F2003 object.
struct type_desc
The type_desc structure describes the type of an `‘OOP’' F2003 object.
struct proc_desc
Procedure Pointer/Argument Descriptor.
Macros
#define FUNC(x) void (*x)()
pointer to a procedure macro.
#define VTABLE(x) void (**x)()
pointer to type bound procedure table macro.
#define FINAL_TABLE(x) void (**x)(char *, char *)
pointer to final procedures table macro.
#define MAX_TYPE_NAME 32
Typedefs
typedef struct object_desc OBJECT_DESC
typedef struct layout_desc LAYOUT_DESC
typedef struct proc_desc PROC_DESC
Functions
void I8() __fort_dump_type (TYPE_DESC *d)
__INT_T ENTF90 (GET_OBJECT_SIZE, get_object_size)(F90_Desc *d)
__INT8_T ENTF90 (KGET_OBJECT_SIZE, kget_object_size)(F90_Desc *d)
void ENTF90 (SET_TYPE, set_type)(F90_Desc *dd
Variables
void OBJECT_DESC * td
Detailed Description
F2003 polymorphic/OOP support.
Definition in file type.h.
Macro Definition Documentation
FINAL_TABLE
#define FINAL_TABLE (x) void (**x)(char *, char *)
pointer to final procedures table macro.
Definition at line 43 of file type.h.
FUNC
#define FUNC (x) void (*x)()
pointer to a procedure macro.
Definition at line 22 of file type.h.
MAX_TYPE_NAME
#define MAX_TYPE_NAME 32
Definition at line 46 of file type.h.
VTABLE
#define VTABLE (x) void (**x)()
pointer to type bound procedure table macro.
This is a pointer to a NULL terminated array of function pointers.
Definition at line 28 of file type.h.
Typedef Documentation
LAYOUT_DESC
typedef struct layout_desc LAYOUT_DESC
Definition at line 49 of file type.h.
OBJECT_DESC
typedef struct object_desc OBJECT_DESC
Definition at line 48 of file type.h.
PROC_DESC
typedef struct proc_desc PROC_DESC
Definition at line 50 of file type.h.
Function Documentation
__fort_dump_type()
void I8() __fort_dump_type (TYPE_DESC * d)
Definition at line 1182 of file type.c.
References __CHAR, __CINT, __CPLX16, __CPLX32, __CPLX8, __DERIVED, __DESC, __DOUBLE, __INT1, __INT16, __INT2, __INT4, __INT8, __io_stderr(), __LOG1, __LOG16, __LOG2, __LOG4, __LOG8, __LONG, __LONGDOUBLE, __LONGLONG, __M128, __M256, __NCHAR, __NONE, __POLY, __PROC, __PROCPTR, __QCPLX32, __QREAL16, __REAL16, __REAL4, __REAL8, __SHORT, __SKED, __STR, __UCHAR, __UINT, __ULONG, __ULONGLONG, __USHORT, __WORD16, __WORD4, __WORD8, d, get_parent_pointer(), ld, level(), and parent.
Referenced by ENTF90COMN().
ENTF90() [1/3]
__INT_T ENTF90 (GET_OBJECT_SIZE , get_object_size)
Definition at line 342 of file type.c.
References __STR, d, I8(), object_desc::size, and td.
ENTF90() [2/3]
__INT8_T ENTF90 (KGET_OBJECT_SIZE , kget_object_size)
Definition at line 355 of file type.c.
References __STR, d, I8(), object_desc::size, and td.
ENTF90() [3/3]
void ENTF90 (SET_TYPE , set_type)
Variable Documentation
td
void OBJECT_DESC* td
Definition at line 147 of file type.h.