flang: type.c File Reference
type.c File Reference
F2003 polymorphic/OOP runtime support.
#include "type.h"
#include "f90alloc.h"
#include "stdioInterf.h"
Macros
#define ARG1_PTR 0x1
#define ARG1_ALLOC 0x2
#define ARG2_PTR 0x4
#define ARG2_ALLOC 0x8
#define ARG2_INTRIN 0x10
Functions
static struct type_desc * I8 (__f03_ty_to_id)[]
void ENTF90 (SET_INTRIN_TYPE, set_intrin_type)
__LOG_T ENTF90 (EXTENDS_TYPE_OF, extends_type_of)
__LOG8_T ENTF90 (KSAME_TYPE_AS, ksame_type_as)
__LOG8_T ENTF90 (KEXTENDS_TYPE_OF, kextends_type_of)
void ENTF90 (SET_TYPE, set_type)
int ENTF90 (POLY_CONFORM_TYPES, poly_conform_types)
Check whether two polymorphic types are conformable.
void ENTF90 (TEST_AND_SET_TYPE, test_and_set_type)
__INT_T ENTF90 (GET_OBJECT_SIZE, get_object_size)
__INT8_T ENTF90 (KGET_OBJECT_SIZE, kget_object_size)
void ENTF90 (POLY_ELEMENT_ADDR, poly_element_addr)
Compute address of an element in a polymorphic array.
void ENTF90 (KPOLY_ELEMENT_ADDR, kpoly_element_addr)
Compute address of an element in a polymorphic array (-i8 version)
void ENTF90 (POLY_ELEMENT_ADDR1, poly_element_addr1)
Compute address of an element in a 1-dimensional polymorphic array.
void ENTF90 (POLY_ELEMENT_ADDR2, poly_element_addr2)
Compute address of an element in a 2-dimensional polymorphic array.
void ENTF90 (POLY_ELEMENT_ADDR3, poly_element_addr3)
Compute address of an element in a 3-dimensional polymorphic array.
void ENTF90 (KPOLY_ELEMENT_ADDR1, kpoly_element_addr1)
Compute address of an element in a 1-dimensional polymorphic array. (-i8 version)
void ENTF90 (KPOLY_ELEMENT_ADDR2, kpoly_element_addr2)
Compute address of an element in a 2-dimensional polymorphic array. (-i8 version)
void ENTF90 (KPOLY_ELEMENT_ADDR3, kpoly_element_addr3)
Compute address of an element in a 3-dimensional polymorphic array. (-i8 version)
static TYPE_DESC * get_parent_pointer (TYPE_DESC *src_td, __INT_T level)
Returns a type descriptor pointer of a specified ancestor of a type descriptor.
static void process_final_procedures (char *area, F90_Desc *sd)
void ENTF90 (FINALIZE, finalize)
void ENTF90 (DEALLOC_POLY_MBR03A, dealloc_poly_mbr03a)
void ENTF90 (DEALLOC_POLY_MBR03, dealloc_poly_mbr03)
void ENTF90 (DEALLOC_POLY03A, dealloc_poly03a)
void ENTF90 (DEALLOC_POLY03, dealloc_poly03)
static void sourced_alloc_and_assign (char *ab, char *bb, TYPE_DESC *td)
static void sourced_alloc_and_assign_array (int extent, char *ab, char *bb, TYPE_DESC *td)
Perform sourced allocation and assign on each element of an array.
static void sourced_alloc_and_assign_array_from_scalar (int extent, char *ab, char *bb, TYPE_DESC *td)
Same as sourced_alloc_and_assign_array() except the source argument is a scalar; not an array.
static void get_source_and_dest_sizes (F90_Desc *ad, F90_Desc *bd, int *dest_sz, int *src_sz, int *dest_is_array, int *src_is_array, TYPE_DESC **tad, TYPE_DESC **tbd, __INT_T flag)
Computes destination/first object and source/second object sizes and other variables used by the poly_asn() and poly_conform_types() routines.
void ENTF90 (POLY_ASN, poly_asn)
void I8() __fort_dump_type (TYPE_DESC *d)
static struct type_desc I8 (__f03_short_td)
static struct type_desc I8 (__f03_ushort_td)
static struct type_desc I8 (__f03_cint_td)
static struct type_desc I8 (__f03_uint_td)
static struct type_desc I8 (__f03_long_td)
static struct type_desc I8 (__f03_ulong_td)
static struct type_desc I8 (__f03_float_td)
static struct type_desc I8 (__f03_double_td)
static struct type_desc I8 (__f03_cplx8_td)
static struct type_desc I8 (__f03_cplx16_td)
static struct type_desc I8 (__f03_char_td)
static struct type_desc I8 (__f03_uchar_td)
static struct type_desc I8 (__f03_longdouble_td)
static struct type_desc I8 (__f03_str_td)
static struct type_desc I8 (__f03_longlong_td)
static struct type_desc I8 (__f03_ulonglong_td)
static struct type_desc I8 (__f03_log1_td)
static struct type_desc I8 (__f03_log2_td)
static struct type_desc I8 (__f03_log4_td)
static struct type_desc I8 (__f03_log8_td)
static struct type_desc I8 (__f03_word4_td)
static struct type_desc I8 (__f03_word8_td)
static struct type_desc I8 (__f03_nchar_td)
static struct type_desc I8 (__f03_int2_td)
static struct type_desc I8 (__f03_int4_td)
static struct type_desc I8 (__f03_int8_td)
static struct type_desc I8 (__f03_real4_td)
static struct type_desc I8 (__f03_real8_td)
static struct type_desc I8 (__f03_real16_td)
static struct type_desc I8 (__f03_cplx32_td)
static struct type_desc I8 (__f03_word16_td)
static struct type_desc I8 (__f03_int1_td)
__LOG_T ENTF90 (SAME_INTRIN_TYPE_AS, same_intrin_type_as)
__LOG8_T ENTF90 (KSAME_INTRIN_TYPE_AS, ksame_intrin_type_as)
void ENTF90 (POLY_ASN_SRC_INTRIN, poly_asn_src_intrin)
void ENTF90 (POLY_ASN_DEST_INTRIN, poly_asn_dest_intrin)
static int has_intrin_type (F90_Desc *dd)
This routine checks whether a descriptor is associated with an intrinsic type.
void ENTF90 (INIT_UNL_POLY_DESC, init_unl_poly_desc)
void ENTF90 (INIT_FROM_DESC, init_from_desc)
void ENTF90 (ASN_CLOSURE, asn_closure)
void ENTF90 (COPY_PROC_DESC, copy_proc_desc)
Detailed Description
F2003 polymorphic/OOP runtime support.
Definition in file type.c.
Macro Definition Documentation
ARG1_ALLOC
#define ARG1_ALLOC 0x2
ARG1_PTR
#define ARG1_PTR 0x1
ARG2_ALLOC
#define ARG2_ALLOC 0x8
ARG2_INTRIN
#define ARG2_INTRIN 0x10
ARG2_PTR
#define ARG2_PTR 0x4
Function Documentation
__fort_dump_type()
void I8() __fort_dump_type (TYPE_DESC * d)
Definition at line 1182 of file type.c.
References __CHAR, __CINT, __CPLX16, __CPLX32, __CPLX8, __DERIVED, __DESC, __DOUBLE, __INT1, __INT16, __INT2, __INT4, __INT8, __io_stderr(), __LOG1, __LOG16, __LOG2, __LOG4, __LOG8, __LONG, __LONGDOUBLE, __LONGLONG, __M128, __M256, __NCHAR, __NONE, __POLY, __PROC, __PROCPTR, __QCPLX32, __QREAL16, __REAL16, __REAL4, __REAL8, __SHORT, __SKED, __STR, __UCHAR, __UINT, __ULONG, __ULONGLONG, __USHORT, __WORD16, __WORD4, __WORD8, d, get_parent_pointer(), ld, level(), and parent.
Referenced by ENTF90COMN().
ENTF90() [1/31]
void ENTF90 (ASN_CLOSURE , asn_closure)
Definition at line 1929 of file type.c.
References __PROCPTR, and proc_desc::tag.
ENTF90() [2/31]
void ENTF90 (COPY_PROC_DESC , copy_proc_desc)
Definition at line 1936 of file type.c.
References __PROCPTR, and F90_Desc::tag.
ENTF90() [3/31]
void ENTF90 (DEALLOC_POLY03 , dealloc_poly03)
Definition at line 902 of file type.c.
References __CLEN_T, area, CADR, CLEN, ENTF90(), firsttime, and stat.
ENTF90() [4/31]
void ENTF90 (DEALLOC_POLY03A , dealloc_poly03a)
Definition at line 840 of file type.c.
References __DESC, __fort_allocated(), __fort_bcopy(), __POLY, area, CADR, CLEN, ENTF90(), ENTFTN, fd, firsttime, I8(), ld, type_desc::obj, process_final_procedures(), src, stat, and object_desc::tag.
ENTF90() [5/31]
void ENTF90 (DEALLOC_POLY_MBR03 , dealloc_poly_mbr03)
Definition at line 831 of file type.c.
References __CLEN_T, area, CADR, CLEN, ENTF90(), firsttime, and stat.
ENTF90() [6/31]
void ENTF90 (DEALLOC_POLY_MBR03A , dealloc_poly_mbr03a)
Definition at line 770 of file type.c.
References __fort_allocated(), __fort_bcopy(), area, CADR, CLEN, ENTF90(), ENTFTN, fd, firsttime, I8(), ld, process_final_procedures(), src, and stat.
ENTF90() [7/31]
__LOG_T ENTF90 (EXTENDS_TYPE_OF , extends_type_of)
Definition at line 85 of file type.c.
References __fort_allocated(), __POLY, ARG1_ALLOC, ARG1_PTR, ARG2_ALLOC, ARG2_PTR, ENTFTN, GET_DIST_TRUE_LOG, get_parent_pointer(), I8(), object_desc::level, type_desc::obj, parent, t1, t2, and va.
ENTF90() [8/31]
void ENTF90 (FINALIZE , finalize)
Definition at line 760 of file type.c.
References area, and process_final_procedures().
ENTF90() [9/31]
__INT_T ENTF90 (GET_OBJECT_SIZE , get_object_size)
Definition at line 342 of file type.c.
References __STR, d, I8(), object_desc::size, and td.
ENTF90() [10/31]
void ENTF90 (INIT_FROM_DESC , init_from_desc)
Definition at line 1876 of file type.c.
References __DESC, index, j, MAXDIMS, NULL, type_desc::obj, offset, F90_Desc::rank, rank, and object_desc::size.
ENTF90() [11/31]
void ENTF90 (INIT_UNL_POLY_DESC , init_unl_poly_desc)
Definition at line 1850 of file type.c.
References __DESC, __fort_bcopy(), __POLY, DIST_ALIGN_TARGET_G, DIST_ALIGN_TARGET_P, ENTF90(), F90_RANK_G, F90_TAG_G, F90_Desc::gsize, has_intrin_type(), kind, F90_Desc::kind, F90_Desc::len, F90_Desc::lsize, F90_Desc::rank, SET_F90_DIST_DESC_PTR, SIZE_OF_RANK_n_ARRAY_DESC, and F90_Desc::tag.
ENTF90() [12/31]
__LOG8_T ENTF90 (KEXTENDS_TYPE_OF , kextends_type_of)
Definition at line 194 of file type.c.
References __fort_allocated(), __POLY, ARG1_ALLOC, ARG1_PTR, ARG2_ALLOC, ARG2_PTR, ENTFTN, GET_DIST_TRUE_LOG, get_parent_pointer(), I8(), object_desc::level, type_desc::obj, parent, t1, t2, and va.
ENTF90() [13/31]
__INT8_T ENTF90 (KGET_OBJECT_SIZE , kget_object_size)
Definition at line 355 of file type.c.
References __STR, d, I8(), object_desc::size, and td.
ENTF90() [14/31]
void ENTF90 (KPOLY_ELEMENT_ADDR , kpoly_element_addr)
Compute address of an element in a polymorphic array (-i8 version)
This routine is intended for arrays with 4 or more dimensions. For 1, 2, or 3 dimensional arrays, use the specialized routines below. Those routines do not incur the overhead of variable arguments.
Parameters
ab is the base address of the array.
ad is the array's descriptor.
result is the address of the pointer that will hold the result.
variable arguments include an __INT_T* for each index of the array element that we are computing.
Definition at line 425 of file type.c.
References add(), DECL_DIM_PTRS, ENTF90(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_RANK_G, i, index, MAXDIMS, offset, result, SET_DIM_PTRS, sz, and va.
ENTF90() [15/31]
void ENTF90 (KPOLY_ELEMENT_ADDR1 , kpoly_element_addr1)
Compute address of an element in a 1-dimensional polymorphic array. (-i8 version)
Parameters
ab is the base address of the array.
ad is the array's descriptor.
result is the address of the pointer that will hold the result.
ele1 is the first dimension index of the array element.
Definition at line 538 of file type.c.
References add(), DECL_DIM_PTRS, ENTF90(), F90_DPTR_LBOUND_G, result, SET_DIM_PTRS, and sz.
ENTF90() [16/31]
void ENTF90 (KPOLY_ELEMENT_ADDR2 , kpoly_element_addr2)
Compute address of an element in a 2-dimensional polymorphic array. (-i8 version)
Parameters
ab is the base address of the array.
ad is the array's descriptor.
result is the address of the pointer that will hold the result.
ele1 is the first dimension index of the array element.
ele2 is the second dimension index of the array element.
Definition at line 559 of file type.c.
References add(), DECL_DIM_PTRS, ENTF90(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, offset, result, SET_DIM_PTRS, and sz.
ENTF90() [17/31]
void ENTF90 (KPOLY_ELEMENT_ADDR3 , kpoly_element_addr3)
Compute address of an element in a 3-dimensional polymorphic array. (-i8 version)
Parameters
ab is the base address of the array.
ad is the array's descriptor.
result is the address of the pointer that will hold the result.
ele1 is the first dimension index of the array element.
ele2 is the second dimension index of the array element.
ele3 is the third dimension index of the array element.
Definition at line 586 of file type.c.
References add(), DECL_DIM_PTRS, ENTF90(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, offset, result, SET_DIM_PTRS, and sz.
ENTF90() [18/31]
__LOG8_T ENTF90 (KSAME_INTRIN_TYPE_AS , ksame_intrin_type_as)
Definition at line 1739 of file type.c.
References __fort_allocated(), ARG1_ALLOC, ARG1_PTR, ENTF90(), ENTFTN, I8(), type_desc::obj, t1, t2, and va.
ENTF90() [19/31]
__LOG8_T ENTF90 (KSAME_TYPE_AS , ksame_type_as)
Definition at line 151 of file type.c.
References __fort_allocated(), __POLY, ARG1_ALLOC, ARG1_PTR, ARG2_ALLOC, ARG2_PTR, ENTFTN, GET_DIST_TRUE_LOG, I8(), is_unl_poly(), t1, t2, and va.
ENTF90() [20/31]
void ENTF90 (POLY_ASN , poly_asn)
Definition at line 1113 of file type.c.
References __DESC, __fort_bcopy(), __NTYPES, __POLY, DIST_ALIGN_TARGET_G, DIST_ALIGN_TARGET_P, ENTF90(), F90_RANK_G, F90_TAG_G, get_source_and_dest_sizes(), i, ISSCALAR, type_desc::obj, SET_F90_DIST_DESC_PTR, object_desc::size, SIZE_OF_RANK_n_ARRAY_DESC, sourced_alloc_and_assign(), sourced_alloc_and_assign_array(), sourced_alloc_and_assign_array_from_scalar(), src, sz, F90_Desc::tag, and object_desc::tag.
ENTF90() [21/31]
void ENTF90 (POLY_ASN_DEST_INTRIN , poly_asn_dest_intrin)
Definition at line 1805 of file type.c.
References __fort_abort(), ENTF90(), I8(), and td.
ENTF90() [22/31]
void ENTF90 (POLY_ASN_SRC_INTRIN , poly_asn_src_intrin)
Definition at line 1786 of file type.c.
References __fort_abort(), ENTF90(), I8(), and td.
ENTF90() [23/31]
int ENTF90 (POLY_CONFORM_TYPES , poly_conform_types)
Check whether two polymorphic types are conformable.
This routine is similar to the conformable routines in rdst.c, but it is for two polymorphic scalar objects instead of arrays.
This is needed in polymorphic allocatable assignment. If two types are conformable or the type of the left hand side expression is large enough to hold the value(s) on the right hand side, then we do not have to reallocate the left hand side if it's already allocated.
Parameters
ab is the address of the first object.
ab is the first object's descriptor.
bd is the second object's descriptor.
flag can be 0, 1, 2. See flag's description for poly_asn().
Returns
1 if types are conformable; 0 if types are not conformable but
Parameters
ab is big enough to hold
bd; -1 if
ab is not conformable, not big enough, or not allocated.
Definition at line 294 of file type.c.
References __fort_allocated(), get_source_and_dest_sizes(), and I8().
ENTF90() [24/31]
void ENTF90 (POLY_ELEMENT_ADDR , poly_element_addr)
Compute address of an element in a polymorphic array.
This routine is intended for arrays with 4 or more dimensions. For 1, 2, or 3 dimensional arrays, use the specialized routines below. Those routines do not incur the overhead of variable arguments.
Parameters
ab is the base address of the array.
ad is the array's descriptor.
result is the address of the pointer that will hold the result.
variable arguments include an __INT_T* for each index of the array element that we are computing.
Definition at line 381 of file type.c.
References add(), DECL_DIM_PTRS, ENTF90(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, F90_RANK_G, i, index, MAXDIMS, offset, result, SET_DIM_PTRS, sz, and va.
ENTF90() [25/31]
void ENTF90 (POLY_ELEMENT_ADDR1 , poly_element_addr1)
Compute address of an element in a 1-dimensional polymorphic array.
Parameters
ab is the base address of the array.
ad is the array's descriptor.
result is the address of the pointer that will hold the result.
ele1 is the first dimension index of the array element.
Definition at line 464 of file type.c.
References add(), DECL_DIM_PTRS, ENTF90(), F90_DPTR_LBOUND_G, result, SET_DIM_PTRS, and sz.
ENTF90() [26/31]
void ENTF90 (POLY_ELEMENT_ADDR2 , poly_element_addr2)
Compute address of an element in a 2-dimensional polymorphic array.
Parameters
ab is the base address of the array.
ad is the array's descriptor.
result is the address of the pointer that will hold the result.
ele1 is the first dimension index of the array element.
ele2 is the second dimension index of the array element.
Definition at line 485 of file type.c.
References add(), DECL_DIM_PTRS, ENTF90(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, offset, result, SET_DIM_PTRS, and sz.
ENTF90() [27/31]
void ENTF90 (POLY_ELEMENT_ADDR3 , poly_element_addr3)
Compute address of an element in a 3-dimensional polymorphic array.
Parameters
ab is the base address of the array.
ad is the array's descriptor.
result is the address of the pointer that will hold the result.
ele1 is the first dimension index of the array element.
ele2 is the second dimension index of the array element.
ele3 is the third dimension index of the array element.
Definition at line 511 of file type.c.
References add(), DECL_DIM_PTRS, ENTF90(), F90_DPTR_EXTENT_G, F90_DPTR_LBOUND_G, offset, result, SET_DIM_PTRS, and sz.
ENTF90() [28/31]
__LOG_T ENTF90 (SAME_INTRIN_TYPE_AS , same_intrin_type_as)
Definition at line 1694 of file type.c.
References __fort_allocated(), ARG1_ALLOC, ARG1_PTR, ENTF90(), ENTFTN, I8(), type_desc::obj, t1, t2, and va.
ENTF90() [29/31]
void ENTF90 (SET_INTRIN_TYPE , set_intrin_type)
Definition at line 20 of file type.c.
Referenced by ENTF90(), and sourced_alloc_and_assign().
ENTF90() [30/31]
void ENTF90 (SET_TYPE , set_type)
Definition at line 259 of file type.c.
References __STR, I8(), object_desc::size, td, and type.
ENTF90() [31/31]
void ENTF90 (TEST_AND_SET_TYPE , test_and_set_type)
Definition at line 326 of file type.c.
References __NTYPES, __STR, I8(), object_desc::size, F90_Desc::tag, td, and type.
get_parent_pointer()
static TYPE_DESC * get_parent_pointer (TYPE_DESC * src_td, __INT_T level) static
Returns a type descriptor pointer of a specified ancestor of a type descriptor.
Parameters
src_td is the type descriptor used to locate the ancestor type type descriptor.
level specifies the heirarchical position in the inheritance graph of the desired ancestor type descriptor. To find its immediate parent, specify a level equal to src_td's level.
Returns
a type descriptor representing the ancestor or NULL if there is no ancestor.
Definition at line 617 of file type.c.
References level(), object_desc::level, NULL, type_desc::obj, offset, and parent.
Referenced by __fort_dump_type(), ENTF90(), and process_final_procedures().
get_source_and_dest_sizes()
static void get_source_and_dest_sizes (F90_Desc * ad, F90_Desc * bd, int * dest_sz, int * src_sz, int * dest_is_array, int * src_is_array, TYPE_DESC ** tad, TYPE_DESC ** tbd, __INT_T flag) static
Computes destination/first object and source/second object sizes and other variables used by the poly_asn() and poly_conform_types() routines.
Parameters
ad is the destination/first descriptor in a polymorphic assignment or polymorphic type conformance test.
bd is the source/second descriptor in a polymorphic assignment or polymorphic type conformance test.
dest_sz is used to return the destination/first object's size.
src_sz is used to return the source/second object's size.
dest_is_array stores whether the destination/first object is an array.
src_is_array stores whether the source/second object is an array.
tad is used to return the destination/first object's type descriptor.
tbd is used to return the source/second object's type descriptor.
flag can be 0, 1, 2. See flag's description for poly_asn().
Definition at line 1043 of file type.c.
References __DESC, __fort_size_of, __NTYPES, __POLY, __STR, object_desc::baseTag, dest, F90_Desc::gsize, I8(), ISSCALAR, F90_Desc::kind, F90_Desc::len, F90_Desc::lsize, type_desc::obj, F90_Desc::rank, object_desc::size, src, F90_Desc::tag, and object_desc::tag.
Referenced by ENTF90().
has_intrin_type()
static int has_intrin_type (F90_Desc * dd) static
This routine checks whether a descriptor is associated with an intrinsic type.
Parameters
dd is the descriptor we are testing.
Returns
1 if
Parameters
dd is associated with an intinsinc type, else 0.
Definition at line 1832 of file type.c.
References __NTYPES, i, I8(), NULL, and td.
Referenced by ENTF90().
I8() [1/33]
static struct type_desc I8 (__f03_char_td) static
References __CHAR, __POLY, and I8().
I8() [2/33]
static struct type_desc I8 (__f03_cint_td) static
References __CINT, __POLY, and I8().
I8() [3/33]
static struct type_desc I8 (__f03_cplx16_td) static
References __CPLX16, __POLY, and I8().
I8() [4/33]
static struct type_desc I8 (__f03_cplx32_td) static
References __CPLX32, __POLY, and I8().
I8() [5/33]
static struct type_desc I8 (__f03_cplx8_td) static
References __CPLX8, __POLY, and I8().
I8() [6/33]
static struct type_desc I8 (__f03_double_td) static
References __DOUBLE, __POLY, and I8().
I8() [7/33]
static struct type_desc I8 (__f03_float_td) static
References __FLOAT, __POLY, and I8().
I8() [8/33]
static struct type_desc I8 (__f03_int1_td) static
References __INT1, __POLY, and I8().
I8() [9/33]
static struct type_desc I8 (__f03_int2_td) static
References __INT2, __POLY, and I8().
I8() [10/33]
static struct type_desc I8 (__f03_int4_td) static
References __INT4, __POLY, and I8().
I8() [11/33]
static struct type_desc I8 (__f03_int8_td) static
References __INT8, __POLY, and I8().
I8() [12/33]
static struct type_desc I8 (__f03_log1_td) static
References __LOG1, __POLY, and I8().
I8() [13/33]
static struct type_desc I8 (__f03_log2_td) static
References __LOG2, __POLY, and I8().
I8() [14/33]
static struct type_desc I8 (__f03_log4_td) static
References __LOG4, __POLY, and I8().
I8() [15/33]
static struct type_desc I8 (__f03_log8_td) static
References __LOG8, __POLY, and I8().
I8() [16/33]
static struct type_desc I8 (__f03_long_td) static
References __LONG, __POLY, and I8().
I8() [17/33]
static struct type_desc I8 (__f03_longdouble_td) static
References __LONGDOUBLE, __POLY, and I8().
I8() [18/33]
static struct type_desc I8 (__f03_longlong_td) static
References __LONGLONG, __POLY, and I8().
I8() [19/33]
static struct type_desc I8 (__f03_nchar_td) static
References __NCHAR, __POLY, and I8().
I8() [20/33]
static struct type_desc I8 (__f03_real16_td) static
References __POLY, __REAL16, and I8().
I8() [21/33]
static struct type_desc I8 (__f03_real4_td) static
References __POLY, __REAL4, and I8().
I8() [22/33]
static struct type_desc I8 (__f03_real8_td) static
References __POLY, __REAL8, and I8().
I8() [23/33]
static struct type_desc I8 (__f03_short_td) static
References __POLY, __SHORT, and I8().
I8() [24/33]
static struct type_desc I8 (__f03_str_td) static
References __POLY, __STR, and I8().
I8() [25/33]
static struct type_desc * I8 (__f03_ty_to_id) static
Definition at line 1624 of file type.c.
References I8().
Referenced by ENTF90(), get_source_and_dest_sizes(), has_intrin_type(), I8(), process_final_procedures(), and sourced_alloc_and_assign().
I8() [26/33]
static struct type_desc I8 (__f03_uchar_td) static
References __POLY, __UCHAR, and I8().
I8() [27/33]
static struct type_desc I8 (__f03_uint_td) static
References __POLY, __UINT, and I8().
I8() [28/33]
static struct type_desc I8 (__f03_ulong_td) static
References __POLY, __ULONG, and I8().
I8() [29/33]
static struct type_desc I8 (__f03_ulonglong_td) static
References __POLY, __ULONGLONG, and I8().
I8() [30/33]
static struct type_desc I8 (__f03_ushort_td) static
References __POLY, __USHORT, and I8().
I8() [31/33]
static struct type_desc I8 (__f03_word16_td) static
References __POLY, __WORD16, and I8().
I8() [32/33]
static struct type_desc I8 (__f03_word4_td) static
References __POLY, __WORD4, and I8().
I8() [33/33]
static struct type_desc I8 (__f03_word8_td) static
References __POLY, __WORD8, and I8().
process_final_procedures()
static void process_final_procedures (char * area, F90_Desc * sd) static
Definition at line 648 of file type.c.
References __DERIVED, __DESC, __fort_allocated(), __fort_bcopy(), __NTYPES, __POLY, area, ENTFTN, F90_RANK_G, fd, FINAL_TABLE, for(), get_parent_pointer(), i, I8(), ld, object_desc::level, F90_Desc::lsize, MAXDIMS, type_desc::obj, parent, process_final_procedures(), rank, object_desc::size, src, F90_Desc::tag, and object_desc::tag.
Referenced by ENTF90(), and process_final_procedures().
sourced_alloc_and_assign()
static void sourced_alloc_and_assign (char * ab, char * bb, TYPE_DESC * td) static
Definition at line 915 of file type.c.
References __DESC, __fort_allocated(), __fort_bcopy(), __NONE, db(), ENTCOMN, ENTF90(), ENTFTN, fd, I8(), kind, ld, len, NULL, one, sourced_alloc_and_assign(), sourced_alloc_and_assign_array(), strlen(), td, and zero.
Referenced by ENTF90(), sourced_alloc_and_assign(), sourced_alloc_and_assign_array(), and sourced_alloc_and_assign_array_from_scalar().
sourced_alloc_and_assign_array()
static void sourced_alloc_and_assign_array (int extent, char * ab, char * bb, TYPE_DESC * td) static
Perform sourced allocation and assign on each element of an array.
Parameters
extent is the number of elements to allocate and assign.
ab is a pointer to the destination array.
bb is a pointer to the source array.
td is the destination array's type descriptor.
Definition at line 991 of file type.c.
References extent(), sourced_alloc_and_assign(), and td.
Referenced by ENTF90(), and sourced_alloc_and_assign().
sourced_alloc_and_assign_array_from_scalar()
static void sourced_alloc_and_assign_array_from_scalar (int extent, char * ab, char * bb, TYPE_DESC * td) static
Same as sourced_alloc_and_assign_array() except the source argument is a scalar; not an array.
Parameters
extent is the number of elements to allocate and assign.
ab is a pointer to the destination array.
bb is a pointer to the source array.
td is the destination array's type descriptor.
Definition at line 1012 of file type.c.
References extent(), sourced_alloc_and_assign(), and td.
Referenced by ENTF90().