flang: unf.c File Reference
unf.c File Reference
Fortran unformatted I/O routines.
#include <string.h>
#include "global.h"
#include "fioMacros.h"
#include "async.h"
Classes
struct unf_rec_struct
struct G
Macros
#define DBGBIT(v) (LOCAL_DEBUG && (dbgflag & v))
#define IOBUFSIZE 4096
#define MAX_REC_SIZE (0x7fffffff - 8) /* -8 to allow for two length words */
#define CONT_FLAG 0x80000000 /* sign bit is continuation flag */
#define CONT_FLAG_SW 0x00000080 /* byte-swapped continuation flag */
#define TO_BE_CONTINUED TRUE
#define RCWSZ sizeof(int)
#define UNF_ERR(e) return __fortio_error(e)
#define GBL_SIZE 5
#define WRITE_UNF_LEN (unf_fwrite((char *)&unf_rec.u.s.bytecnt, RCWSZ, 1, Fcb) != TRUE)
#define WRITE_UNF_REC (unf_fwrite((char *)&unf_rec.u.s.bytecnt, rw_size + RCWSZ, 1, Fcb) != TRUE)
#define WRITE_UNF_BUF write_unf_buf()
Functions
static int __unf_init (bool read, bool byte_swap)
Initialize global flags to prepare for unformatted I/O;.
static int __unf_end (bool)
static int __usw_end (bool)
int __f90io_usw_read (int type, long count, int stride, char *item, __CLEN_T item_length)
Read/copy data from an unformatted record file.
int __f90io_usw_write (int, long, int, char *, __CLEN_T)
Write data to an unformatted file with byte swapping.
int __f90io_usw_end (void)
Finish up unformatted, byte swapped read or write. If current I/O is a read, write the current buffer to the file. Whether a read or a write, free the buffer.
static int skip_to_nextrec (void)
static bool unf_fwrite (char *, size_t, size_t, FIO_FCB *)
static int adjust_fpos (FIO_FCB *cur_file, long offset, int whence)
static void save_gbl ()
static void restore_gbl ()
static void allocate_new_gbl ()
static void free_gbl ()
static bool write_unf_buf ()
Write the contents of unf_rec.buf; return TRUE if an error occurred.
int ENTF90IO (UNF_ASYNCA, unf_asynca)
int ENTF90IO (UNF_ASYNC, unf_async)
int __f90io_unf_init (__INT_T *read, __INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat)
Initialize global flags to prepare for unformatted I/O, and if the file isn't opened, open it (if possible).
__INT_T (__INT_T *read, __INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat)
int __f90io_unf_read (int type, long length, int stride, char *item, __CLEN_T item_length)
Read/copy data from an unformatted record file.
__INT_T (__INT_T *type, __INT_T *count, __INT_T *stride, DCHAR(item) DCLEN64(item))
same as unf_read, but item may be array - for unf_read, the compiler scalarizes.
__INT_T (__INT_T *type, __INT_T *count, __INT_T *stride, DCHAR(item) DCLEN(item))
__INT_T (__INT_T *type, __INT8_T *count, __INT_T *stride, DCHAR(item) DCLEN64(item))
same as usw_write, but item may be array - for usw_write, the compiler scalarizes.
__INT_T (__INT_T *type, __INT8_T *count, __INT_T *stride, DCHAR(item) DCLEN(item))
__INT_T (__INT_T *count, __INT_T *stride, char *item, __CLEN_T *item_length)
Write bytes to an unformatted record file; used when the item is an aggregate.
__INT_T (__INT_T *count, __INT_T *stride, char *item, __INT_T *item_length)
__INT_T (__INT8_T *count, __INT_T *stride, char *item, __CLEN_T *item_length)
__INT_T (__INT8_T *count, __INT_T *stride, char *item, __INT_T *item_length)
int __f90io_unf_write (int type, long count, int stride, char *item, __CLEN_T item_length)
Write data to an unformatted file.
int __f90io_unf_end (void)
Finish up unformatted read or write.
__INT_T ENTF90IO (UNF_END, unf_end)()
int __f90io_usw_init (__INT_T *read, __INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat)
Initialize global flags to prepare for unformatted I/O, and if the file isn't opened, open it (if possible).
__INT_T ENTF90IO (USW_END, usw_end)()
Variables
static int dbgflag
static FIO_FCB * Fcb
static char * buf_ptr
static size_t rw_size
static int rec_len
static bool rec_in_buf
static bool read_flag
static bool io_transfer
static bool continued
static bool async
static bool actual_init
static int has_same_fcb
static unf_rec_struct unf_rec
static G static_gbl [GBL_SIZE]
static G * gbl = &static_gbl[0]
static G * gbl_head = &static_gbl[0]
static int gbl_avl = 0
static int gbl_size = GBL_SIZE
Detailed Description
Fortran unformatted I/O routines.
Definition in file unf.c.
Macro Definition Documentation
CONT_FLAG
#define CONT_FLAG 0x80000000 /* sign bit is continuation flag */
Definition at line 36 of file unf.c.
CONT_FLAG_SW
#define CONT_FLAG_SW 0x00000080 /* byte-swapped continuation flag */
Definition at line 37 of file unf.c.
DBGBIT
#define DBGBIT (v) (LOCAL_DEBUG && (dbgflag & v))
Definition at line 31 of file unf.c.
GBL_SIZE
#define GBL_SIZE 5
Definition at line 121 of file unf.c.
IOBUFSIZE
#define IOBUFSIZE 4096
Definition at line 33 of file unf.c.
MAX_REC_SIZE
#define MAX_REC_SIZE (0x7fffffff - 8) /* -8 to allow for two length words */
Definition at line 35 of file unf.c.
RCWSZ
#define RCWSZ sizeof(int)
Definition at line 41 of file unf.c.
TO_BE_CONTINUED
#define TO_BE_CONTINUED TRUE
Definition at line 38 of file unf.c.
UNF_ERR
#define UNF_ERR (e) return __fortio_error(e)
Definition at line 43 of file unf.c.
WRITE_UNF_BUF
#define WRITE_UNF_BUF write_unf_buf()
Definition at line 133 of file unf.c.
WRITE_UNF_LEN
#define WRITE_UNF_LEN (unf_fwrite((char *)&unf_rec.u.s.bytecnt, RCWSZ, 1, Fcb) != TRUE)
Definition at line 129 of file unf.c.
WRITE_UNF_REC
#define WRITE_UNF_REC (unf_fwrite((char *)&unf_rec.u.s.bytecnt, rw_size + RCWSZ, 1, Fcb) != TRUE)
Definition at line 131 of file unf.c.
Function Documentation
__f90io_unf_end()
int __f90io_unf_end (void)
Finish up unformatted read or write.
Finish up unformatted read or write. If current I/O is a read, write the current buffer to the file. Whether a read or a write, free the buffer.
If current I/O is a read, * write the current buffer to the file. Whether a read or a write, free the buffer.
Definition at line 1139 of file unf.c.
References __f90io_usw_end(), __unf_end(), fcb::byte_swap, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FIO_TBL::error, Fcb, fioFcbTbls, has_same_fcb, and TO_BE_CONTINUED.
Referenced by __f90io_usw_end(), and ENTF90IO().
__f90io_unf_init()
int __f90io_unf_init (__INT_T * read, __INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat)
Initialize global flags to prepare for unformatted I/O, and if the file isn't opened, open it (if possible).
Initialize global flags to prepare for unformatted I/O, and if the file isn't opened, open it (if possible).
Definition at line 276 of file unf.c.
References __fortio_errinit03(), __fortio_rwinit(), __unf_init(), actual_init, allocate_new_gbl(), bitv, fcb::byte_swap, continued, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FALSE, Fcb, G::Fcb, FIO_UNFORMATTED, fioFcbTbls, gbl, NULL, read, s, save_gbl(), and TRUE.
Referenced by __INT_T().
__f90io_unf_read()
int __f90io_unf_read (int type, long length, int stride, char * item, __CLEN_T item_length)
Read/copy data from an unformatted record file.
Parameters
type Type of data long length number of items of specified type to read. May be <= 0
length number of items of specified type to read. May be <= 0
stride distance in bytes between items
item where to xfer data
item_length
Definition at line 435 of file unf.c.
References __CLEN_T, __f90io_usw_read(), __fortio_errend03(), __fortio_error(), __io_errno(), __io_feof(), __io_fread, __unf_end(), __unf_init(), assert, fcb::asy_rw, fcb::asyptr, fcb::binary, fcb::byte_swap, unf_rec_struct::bytecnt, continued, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FIO_TBL::error, Fcb, Fio_asy_read(), FIO_EDREAD, FIO_EEOF, FIO_ETOOBIG, fioFcbTbls, fcb::fp, free_gbl(), io_transfer, length(), NULL, offset, fcb::partial, read_flag, rec_len, restore_gbl(), unf_rec_struct::s, skip_to_nextrec(), stride, TO_BE_CONTINUED, TRUE, type, unf_rec_struct::u, unf_rec, and void().
Referenced by __f90io_usw_read(), and __INT_T().
__f90io_unf_write()
int __f90io_unf_write (int type, long count, int stride, char * item, __CLEN_T item_length)
Write data to an unformatted file.
Parameters
type data type of data (see above).
count number of items of specified type to write. May be <= 0
stride distance in bytes between items.
item where to get data from
item_length
Definition at line 768 of file unf.c.
References __CLEN_T, __f90io_usw_write(), __fortio_errend03(), __fortio_error(), __io_errno(), __io_printf, __unf_end(), __unf_init(), fcb::acc, assert, fcb::asy_rw, fcb::asyptr, unf_rec_struct::bcnt, fcb::binary, unf_rec_struct::buf, buf_ptr, fcb::byte_swap, unf_rec_struct::bytecnt, count, DBGBIT, FIO_TBL::eof, ERR_FLAG, FIO_TBL::error, FALSE, Fcb, Fio_asy_disable(), FIO_DIRECT, FIO_ETOOBIG, fioFcbTbls, free_gbl(), GBL_SIZE_T_FORMAT, i, io_transfer, IOBUFSIZE, j, MAX_REC_SIZE, NULL, read_flag, rec_in_buf, rec_len, restore_gbl(), rw_size, unf_rec_struct::s, stride, TO_BE_CONTINUED, TRUE, type, unf_rec_struct::u, unf_fwrite(), unf_rec, void(), WRITE_UNF_BUF, and WRITE_UNF_REC.
Referenced by __f90io_usw_write().
__f90io_usw_end()
int __f90io_usw_end (void)
Finish up unformatted, byte swapped read or write. If current I/O is a read, write the current buffer to the file. Whether a read or a write, free the buffer.
\ brief Finish up unformatted read or write. If current I/O is a read, write the current buffer to the file. Whether a read or a write, free the buffer.
Definition at line 1987 of file unf.c.
References __f90io_unf_end(), __usw_end(), FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FIO_TBL::error, Fcb, fioFcbTbls, has_same_fcb, fcb::native, and TO_BE_CONTINUED.
Referenced by __f90io_unf_end(), and ENTF90IO().
__f90io_usw_init()
int __f90io_usw_init (__INT_T * read, __INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat)
Initialize global flags to prepare for unformatted I/O, and if the file isn't opened, open it (if possible).
Initialize global flags to prepare for byte swapped unformatted I/O, and if the file isn't opened, open it (if possible).
Definition at line 1372 of file unf.c.
References __fortio_errinit(), __fortio_rwinit(), __unf_init(), actual_init, allocate_new_gbl(), bitv, continued, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FALSE, Fcb, FIO_UNFORMATTED, fioFcbTbls, fcb::native, NULL, read, s, save_gbl(), and TRUE.
__f90io_usw_read()
int __f90io_usw_read (int type, long count, int stride, char * item, __CLEN_T item_length)
Read/copy data from an unformatted record file.
Read/copy data from an unformatted record file with byte swapping.
Definition at line 1426 of file unf.c.
References __CLEN_T, __f90io_unf_read(), __fortio_errend03(), __fortio_error(), __fortio_swap_bytes(), __io_errno(), __io_feof(), __io_fread, __unf_init(), __usw_end(), assert, fcb::asy_rw, fcb::asyptr, fcb::binary, unf_rec_struct::bytecnt, continued, count, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FIO_TBL::error, Fcb, Fio_asy_disable(), FIO_EEOF, FIO_ETOOBIG, fioFcbTbls, fcb::fp, free_gbl(), io_transfer, fcb::native, NULL, offset, read_flag, rec_len, restore_gbl(), unf_rec_struct::s, skip_to_nextrec(), stride, TO_BE_CONTINUED, TRUE, type, unf_rec_struct::u, unf_rec, and void().
Referenced by __f90io_unf_read().
__f90io_usw_write()
int __f90io_usw_write (int type, long count, int stride, char * item, __CLEN_T item_length)
Write data to an unformatted file with byte swapping.
Parameters
type data type of data (see above).
count number of items of specified type to write. May be <= 0
stride distance in bytes between items.
item where to get data from
item_length
Definition at line 1686 of file unf.c.
References __CLEN_T, __f90io_unf_write(), __fortio_errend03(), __fortio_error(), __fortio_swap_bytes(), __INT, __io_errno(), __io_printf, __STR, __unf_init(), __usw_end(), fcb::acc, assert, unf_rec_struct::bcnt, fcb::binary, unf_rec_struct::buf, buf_ptr, fcb::byte_swap, unf_rec_struct::bytecnt, count, DBGBIT, FIO_TBL::eof, ERR_FLAG, FIO_TBL::error, FALSE, Fcb, FIO_DIRECT, FIO_ENOMEM, FIO_ETOOBIG, fioFcbTbls, fcb::fp, free_gbl(), FWRITE, GBL_SIZE_T_FORMAT, i, io_transfer, IOBUFSIZE, j, malloc(), MAX_REC_SIZE, fcb::native, NULL, pp, RCWSZ, read_flag, rec_in_buf, rec_len, restore_gbl(), rw_size, unf_rec_struct::s, stride, TO_BE_CONTINUED, TRUE, type, unf_rec_struct::u, unf_fwrite(), unf_rec, void(), and WRITE_UNF_BUF.
Referenced by __f90io_unf_write().
__INT_T() [1/9]
__INT_T (__INT8_T * count, __INT_T * stride, char * item, __CLEN_T * item_length)
Definition at line 730 of file unf.c.
References __f90io_unf_read(), __STR, count, DIST_RBCSTL, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, s, and stride.
__INT_T() [2/9]
__INT_T (__INT8_T * count, __INT_T * stride, char * item, __INT_T * item_length)
Definition at line 753 of file unf.c.
References __CLEN_T, count, ENTF90IO(), and stride.
__INT_T() [3/9]
__INT_T (__INT_T * count, __INT_T * stride, char * item, __CLEN_T * item_length)
Write bytes to an unformatted record file; used when the item is an aggregate.
Definition at line 699 of file unf.c.
References __f90io_unf_read(), __STR, count, DIST_RBCSTL, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, s, and stride.
__INT_T() [4/9]
__INT_T (__INT_T * count, __INT_T * stride, char * item, __INT_T * item_length)
Definition at line 718 of file unf.c.
References __CLEN_T, count, ENTF90IO(), and stride.
__INT_T() [5/9]
__INT_T (__INT_T * read, __INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat)
Definition at line 410 of file unf.c.
References __f90io_unf_init(), __fort_status_init(), __fortio_errend03(), bitv, DIST_STATUS_BCST, free_gbl(), GET_DIST_IOPROC, GET_DIST_LCPU, LOCAL_MODE, read, restore_gbl(), and s.
__INT_T() [6/9]
__INT_T (__INT_T * type, __INT8_T * count, __INT_T * stride, DCHAR(item) DCLEN(item))
Definition at line 683 of file unf.c.
References __CLEN_T, CADR, CLEN, count, ENTF90IO(), stride, and type.
__INT_T() [7/9]
__INT_T (__INT_T * type, __INT8_T * count, __INT_T * stride, DCHAR(item) DCLEN64(item))
same as usw_write, but item may be array - for usw_write, the compiler scalarizes.
Definition at line 657 of file unf.c.
References __CLEN_T, __f90io_unf_read(), __STR, CADR, CLEN, count, DIST_RBCSTL, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, GET_DIST_SIZE_OF, len, LOCAL_MODE, s, stride, and type.
__INT_T() [8/9]
__INT_T (__INT_T * type, __INT_T * count, __INT_T * stride, DCHAR(item) DCLEN(item))
Definition at line 602 of file unf.c.
References __CLEN_T, CADR, CLEN, count, ENTF90IO(), stride, and type.
__INT_T() [9/9]
__INT_T (__INT_T * type, __INT_T * count, __INT_T * stride, DCHAR(item) DCLEN64(item))
same as unf_read, but item may be array - for unf_read, the compiler scalarizes.
same as usw_write, but item may be array - for usw_write, the compiler scalarizes.
same as unf_write, but item may be array - for unf_write, the compiler scalarizes.
Definition at line 576 of file unf.c.
References __CLEN_T, __f90io_unf_read(), __STR, CADR, CLEN, count, DIST_RBCSTL, DIST_STATUS_BCST, GET_DIST_IOPROC, GET_DIST_LCPU, GET_DIST_SIZE_OF, len, LOCAL_MODE, s, stride, and type.
__unf_end()
static int __unf_end (bool to_be_continued) static
Definition at line 1155 of file unf.c.
References __fortio_zeropad(), __io_errno(), __io_fread, __io_fseek, fcb::acc, adjust_fpos(), unf_rec_struct::bcnt, fcb::binary, unf_rec_struct::buf, buf_ptr, unf_rec_struct::bytecnt, fcb::coherent, CONT_FLAG, continued, f90_old_huge_rec_fmt(), Fcb, FIO_DIRECT, fcb::fp, has_same_fcb, io_transfer, RCWSZ, read_flag, rec_in_buf, rec_len, fcb::reclen, rw_size, unf_rec_struct::s, skip_to_nextrec(), unf_rec_struct::u, UNF_ERR, unf_rec, WRITE_UNF_BUF, WRITE_UNF_LEN, and WRITE_UNF_REC.
Referenced by __f90io_unf_end(), __f90io_unf_read(), and __f90io_unf_write().
__unf_init()
static int __unf_init (bool read, bool byte_swap) static
Initialize global flags to prepare for unformatted I/O;.
Parameters
read - TRUE indicates READ statement.
byte_swap - TRUE if byteswap I/O
shared by __f90io_unf_init() & __f90io_usw_init().
Definition at line 316 of file unf.c.
References __fortio_swap_bytes(), __INT, __io_errno(), __io_feof(), __io_fread, a, fcb::acc, actual_init, fcb::asy_rw, async, fcb::asyptr, fcb::binary, unf_rec_struct::buf, buf_ptr, G::buf_ptr, unf_rec_struct::bytecnt, CONT_FLAG, continued, G::continued, f90_old_huge_rec_fmt(), FALSE, Fcb, Fio_asy_disable(), Fio_asy_enable(), FIO_DIRECT, FIO_EASYNC, FIO_EEOF, fcb::fp, gbl_avl, gbl_head, has_same_fcb, i, io_transfer, G::io_transfer, fcb::nextrec, NULL, RCWSZ, read, read_flag, rec_in_buf, G::rec_in_buf, G::rec_len, rec_len, fcb::reclen, rw_size, G::rw_size, unf_rec_struct::s, TRUE, unf_rec_struct::u, UNF_ERR, unf_rec, and G::unf_rec.
Referenced by __f90io_unf_init(), __f90io_unf_read(), __f90io_unf_write(), __f90io_usw_init(), __f90io_usw_read(), and __f90io_usw_write().
__usw_end()
static int __usw_end (bool to_be_continued) static
Definition at line 2003 of file unf.c.
References __fortio_swap_bytes(), __fortio_zeropad(), __INT, __io_errno(), __io_fread, __io_fseek, fcb::acc, unf_rec_struct::bcnt, fcb::binary, unf_rec_struct::buf, buf_ptr, unf_rec_struct::bytecnt, fcb::coherent, CONT_FLAG, CONT_FLAG_SW, continued, f90_old_huge_rec_fmt(), Fcb, FIO_DIRECT, fcb::fp, FWRITE, io_transfer, RCWSZ, read_flag, rec_in_buf, rec_len, fcb::reclen, rw_size, unf_rec_struct::s, skip_to_nextrec(), unf_rec_struct::u, UNF_ERR, unf_rec, and WRITE_UNF_BUF.
Referenced by __f90io_usw_end(), __f90io_usw_read(), and __f90io_usw_write().
adjust_fpos()
static int adjust_fpos (FIO_FCB * cur_file, long offset, int whence) static
Definition at line 136 of file unf.c.
References __io_fseek, fcb::asy_rw, fcb::asyptr, Fio_asy_fseek(), fcb::fp, and offset.
Referenced by __unf_end(), and skip_to_nextrec().
allocate_new_gbl()
static void allocate_new_gbl () static
Definition at line 189 of file unf.c.
References gbl, gbl_avl, gbl_head, GBL_SIZE, gbl_size, and malloc().
Referenced by __f90io_unf_init(), and __f90io_usw_init().
ENTF90IO() [1/4]
int ENTF90IO (UNF_ASYNC , unf_async)
Definition at line 266 of file unf.c.
References __CLEN_T, CADR, CLEN, and ENTF90IO().
ENTF90IO() [2/4]
int ENTF90IO (UNF_ASYNCA , unf_asynca)
Definition at line 248 of file unf.c.
References __fortio_eq_str(), async, CADR, CLEN, FIO_ESPEC, ISPRESENTC, NULL, and UNF_ERR.
Referenced by __INT_T(), and ENTF90IO().
ENTF90IO() [3/4]
__INT_T ENTF90IO (UNF_END , unf_end)
Definition at line 1326 of file unf.c.
References __f90io_unf_end(), __fortio_errend03(), unf_rec_struct::buf, buf_ptr, G::buf_ptr, continued, G::continued, DIST_STATUS_BCST, Fcb, free_gbl(), gbl_avl, gbl_head, GET_DIST_IOPROC, GET_DIST_LCPU, i, io_transfer, G::io_transfer, LOCAL_MODE, NULL, rec_in_buf, G::rec_in_buf, G::rec_len, rec_len, restore_gbl(), rw_size, G::rw_size, s, unf_rec, and G::unf_rec.
ENTF90IO() [4/4]
__INT_T ENTF90IO (USW_END , usw_end)
Definition at line 2142 of file unf.c.
References __f90io_usw_end(), __fortio_errend03(), unf_rec_struct::buf, buf_ptr, G::buf_ptr, continued, G::continued, DIST_STATUS_BCST, Fcb, free_gbl(), gbl_avl, gbl_head, GET_DIST_IOPROC, GET_DIST_LCPU, i, io_transfer, G::io_transfer, LOCAL_MODE, NULL, rec_in_buf, G::rec_in_buf, G::rec_len, rec_len, restore_gbl(), rw_size, G::rw_size, s, unf_rec, and G::unf_rec.
free_gbl()
static void free_gbl () static
Definition at line 209 of file unf.c.
References gbl, gbl_avl, and gbl_head.
Referenced by __f90io_unf_read(), __f90io_unf_write(), __f90io_usw_read(), __f90io_usw_write(), __INT_T(), and ENTF90IO().
restore_gbl()
static void restore_gbl () static
Definition at line 169 of file unf.c.
References async, G::async, unf_rec_struct::buf, buf_ptr, G::buf_ptr, continued, G::continued, Fcb, G::Fcb, gbl, gbl_avl, has_same_fcb, G::has_same_fcb, io_transfer, G::io_transfer, read_flag, G::read_flag, rec_in_buf, G::rec_in_buf, G::rec_len, rec_len, rw_size, G::rw_size, unf_rec, and G::unf_rec.
Referenced by __f90io_unf_read(), __f90io_unf_write(), __f90io_usw_read(), __f90io_usw_write(), __INT_T(), and ENTF90IO().
save_gbl()
static void save_gbl () static
Definition at line 149 of file unf.c.
References async, G::async, unf_rec_struct::buf, buf_ptr, G::buf_ptr, continued, G::continued, Fcb, G::Fcb, gbl, gbl_avl, has_same_fcb, G::has_same_fcb, io_transfer, G::io_transfer, read_flag, G::read_flag, rec_in_buf, G::rec_in_buf, G::rec_len, rec_len, rw_size, G::rw_size, unf_rec, and G::unf_rec.
Referenced by __f90io_unf_init(), and __f90io_usw_init().
skip_to_nextrec()
static int skip_to_nextrec (void) static
Definition at line 1301 of file unf.c.
References __io_errno(), __io_fseek, fcb::acc, adjust_fpos(), unf_rec_struct::bytecnt, fcb::coherent, Fcb, FIO_DIRECT, fcb::fp, RCWSZ, rec_len, unf_rec_struct::s, unf_rec_struct::u, UNF_ERR, and unf_rec.
Referenced by __f90io_unf_read(), __f90io_usw_read(), __unf_end(), and __usw_end().
unf_fwrite()
static bool unf_fwrite (char * buf, size_t size, size_t num, FIO_FCB * fcb) static
Definition at line 233 of file unf.c.
References fcb::asy_rw, fcb::asyptr, buf, FALSE, Fio_asy_write(), fcb::fp, FWRITE, num, and size.
Referenced by __f90io_unf_write(), __f90io_usw_write(), and write_unf_buf().
write_unf_buf()
static bool write_unf_buf () static
Write the contents of unf_rec.buf; return TRUE if an error occurred.
Definition at line 225 of file unf.c.
References unf_rec_struct::buf, FALSE, Fcb, rw_size, TRUE, unf_fwrite(), and unf_rec.
Variable Documentation
actual_init
bool actual_init static
Definition at line 61 of file unf.c.
Referenced by __f90io_unf_init(), __f90io_usw_init(), and __unf_init().
async
bool async static
Definition at line 60 of file unf.c.
Referenced by __unf_init(), ENTF90IO(), restore_gbl(), and save_gbl().
buf_ptr
char* buf_ptr static
Definition at line 51 of file unf.c.
Referenced by __f90io_unf_write(), __f90io_usw_write(), __unf_end(), __unf_init(), __usw_end(), ENTF90IO(), restore_gbl(), and save_gbl().
continued
bool continued static
Definition at line 59 of file unf.c.
Referenced by __f90io_unf_init(), __f90io_unf_read(), __f90io_usw_init(), __f90io_usw_read(), __unf_end(), __unf_init(), __usw_end(), ENTF90IO(), restore_gbl(), and save_gbl().
dbgflag
int dbgflag static
Definition at line 29 of file unf.c.
Fcb
FIO_FCB* Fcb static
Definition at line 50 of file unf.c.
Referenced by __f90io_unf_end(), __f90io_unf_init(), __f90io_unf_read(), __f90io_unf_write(), __f90io_usw_end(), __f90io_usw_init(), __f90io_usw_read(), __f90io_usw_write(), __unf_end(), __unf_init(), __usw_end(), ENTF90IO(), restore_gbl(), save_gbl(), skip_to_nextrec(), and write_unf_buf().
gbl
G* gbl = &static_gbl[0] static
Definition at line 124 of file unf.c.
Referenced by __f90io_unf_init(), allocate_new_gbl(), free_gbl(), restore_gbl(), and save_gbl().
gbl_avl
int gbl_avl = 0 static
Definition at line 126 of file unf.c.
Referenced by __unf_init(), allocate_new_gbl(), ENTF90IO(), free_gbl(), restore_gbl(), and save_gbl().
gbl_head
G* gbl_head = &static_gbl[0] static
Definition at line 125 of file unf.c.
Referenced by __unf_init(), allocate_new_gbl(), ENTF90IO(), and free_gbl().
gbl_size
int gbl_size = GBL_SIZE static
Definition at line 127 of file unf.c.
Referenced by allocate_new_gbl().
has_same_fcb
int has_same_fcb static
Definition at line 62 of file unf.c.
Referenced by __f90io_unf_end(), __f90io_usw_end(), __unf_end(), __unf_init(), restore_gbl(), and save_gbl().
io_transfer
bool io_transfer static
Definition at line 57 of file unf.c.
Referenced by __f90io_unf_read(), __f90io_unf_write(), __f90io_usw_read(), __f90io_usw_write(), __unf_end(), __unf_init(), __usw_end(), ENTF90IO(), restore_gbl(), and save_gbl().
read_flag
bool read_flag static
Definition at line 56 of file unf.c.
Referenced by __f90io_unf_read(), __f90io_unf_write(), __f90io_usw_read(), __f90io_usw_write(), __unf_end(), __unf_init(), __usw_end(), restore_gbl(), and save_gbl().
rec_in_buf
bool rec_in_buf static
Definition at line 54 of file unf.c.
Referenced by __f90io_unf_write(), __f90io_usw_write(), __unf_end(), __unf_init(), __usw_end(), ENTF90IO(), restore_gbl(), and save_gbl().
rec_len
int rec_len static
Definition at line 53 of file unf.c.
Referenced by __f90io_unf_read(), __f90io_unf_write(), __f90io_usw_read(), __f90io_usw_write(), __unf_end(), __unf_init(), __usw_end(), ENTF90IO(), restore_gbl(), save_gbl(), and skip_to_nextrec().
rw_size
size_t rw_size static
Definition at line 52 of file unf.c.
Referenced by __f90io_unf_write(), __f90io_usw_write(), __unf_end(), __unf_init(), __usw_end(), ENTF90IO(), restore_gbl(), save_gbl(), and write_unf_buf().
static_gbl
G static_gbl[GBL_SIZE] static
Definition at line 123 of file unf.c.
unf_rec
unf_rec_struct unf_rec static
Definition at line 105 of file unf.c.
Referenced by __f90io_unf_read(), __f90io_unf_write(), __f90io_usw_read(), __f90io_usw_write(), __unf_end(), __unf_init(), __usw_end(), ENTF90IO(), restore_gbl(), save_gbl(), skip_to_nextrec(), and write_unf_buf().