flang: unf.h File Reference
unf.h File Reference
Fortran unformatted I/O utility routines defined in unf.c and visible to the rest of the runtime.
Functions
int __f90io_unf_init (__INT_T *read, __INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat)
Initialize global flags to prepare for unformatted I/O, and if the file isn't opened, open it (if possible).
int __f90io_unf_read (int type, long length, int stride, char *item, __CLEN_T item_length)
Read/copy data from an unformatted record file.
int __f90io_unf_write (int type, long count, int stride, char *item, __CLEN_T item_length)
Write data to an unformatted file.
int __f90io_unf_end (void)
Finish up unformatted read or write. If current I/O is a read, write the current buffer to the file. Whether a read or a write, free the buffer.
int __f90io_usw_init (__INT_T *read, __INT_T *unit, __INT_T *rec, __INT_T *bitv, __INT_T *iostat)
Initialize global flags to prepare for byte swapped unformatted I/O, and if the file isn't opened, open it (if possible).
int __f90io_usw_read (int type, long count, int stride, char *item, __CLEN_T item_length)
Read/copy data from an unformatted record file with byte swapping.
int __f90io_usw_write (int type, long count, int stride, char *item, __CLEN_T item_length)
Write data to an unformatted file with byte swapping.
int __f90io_usw_end (void)
Finish up unformatted, byte swapped read or write. If current I/O is a read, write the current buffer to the file. Whether a read or a write, free the buffer.
Detailed Description
Fortran unformatted I/O utility routines defined in unf.c and visible to the rest of the runtime.
The calling sequence for these routines is always __f90io_unf_init(), __f90io_unf_read/write()... __f90io_unf_end(). __f90io_unf_init() initializes globals. __f90io_unf_read() reads one record into a buffer the first time it is called and then processes that record in subsequent calls. __f90io_unf_write() collects data in a buffer which is reallocated as needed in subsequent calls. __f90io_unf_end() either writes the buffer to the file in the case of a write, or seeks to the next record (if a variable length file) in the case of a read. If __fortio_error is called any time during or after an init, and is allowed to return (as opposed to exiting) by iostat, a global variable will be set and all subsequent calls to __f90io_unf_read() or __f90io_unf_write() and __f90io_unf_end() will return with an error. The next call to __f90io_unf_init() resets these flags.
Definition in file unf.h.
Function Documentation
__f90io_unf_end()
int __f90io_unf_end (void)
Finish up unformatted read or write. If current I/O is a read, write the current buffer to the file. Whether a read or a write, free the buffer.
Finish up unformatted read or write. If current I/O is a read, write the current buffer to the file. Whether a read or a write, free the buffer.
If current I/O is a read, * write the current buffer to the file. Whether a read or a write, free the buffer.
Definition at line 1139 of file unf.c.
References __f90io_usw_end(), __unf_end(), fcb::byte_swap, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FIO_TBL::error, Fcb, fioFcbTbls, has_same_fcb, and TO_BE_CONTINUED.
Referenced by __f90io_usw_end(), and ENTF90IO().
__f90io_unf_init()
int __f90io_unf_init (__INT_T * read, __INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat)
Initialize global flags to prepare for unformatted I/O, and if the file isn't opened, open it (if possible).
Parameters
read TRUE indicates READ statement
unit unit number
rec record number for direct access
bitv same as for ENTF90IO(open_)
iostat same as for ENTF90IO(open_)
Initialize global flags to prepare for unformatted I/O, and if the file isn't opened, open it (if possible).
Definition at line 276 of file unf.c.
References __fortio_errinit03(), __fortio_rwinit(), __unf_init(), actual_init, allocate_new_gbl(), bitv, fcb::byte_swap, continued, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FALSE, Fcb, G::Fcb, FIO_UNFORMATTED, fioFcbTbls, gbl, NULL, read, s, save_gbl(), and TRUE.
Referenced by __INT_T().
__f90io_unf_read()
int __f90io_unf_read (int type, long length, int stride, char * item, __CLEN_T item_length)
Read/copy data from an unformatted record file.
Parameters
type Type of data long length number of items of specified type to read. May be <= 0
length number of items of specified type to read. May be <= 0
stride distance in bytes between items
item where to xfer data
item_length
Definition at line 435 of file unf.c.
References __CLEN_T, __f90io_usw_read(), __fortio_errend03(), __fortio_error(), __io_errno(), __io_feof(), __io_fread, __unf_end(), __unf_init(), assert, fcb::asy_rw, fcb::asyptr, fcb::binary, fcb::byte_swap, unf_rec_struct::bytecnt, continued, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FIO_TBL::error, Fcb, Fio_asy_read(), FIO_EDREAD, FIO_EEOF, FIO_ETOOBIG, fioFcbTbls, fcb::fp, free_gbl(), io_transfer, length(), NULL, offset, fcb::partial, read_flag, rec_len, restore_gbl(), unf_rec_struct::s, skip_to_nextrec(), stride, TO_BE_CONTINUED, TRUE, type, unf_rec_struct::u, unf_rec, and void().
Referenced by __f90io_usw_read(), and __INT_T().
__f90io_unf_write()
int __f90io_unf_write (int type, long count, int stride, char * item, __CLEN_T item_length)
Write data to an unformatted file.
Parameters
type data type of data (see above).
count number of items of specified type to write. May be <= 0
stride distance in bytes between items.
item where to get data from
item_length
Definition at line 768 of file unf.c.
References __CLEN_T, __f90io_usw_write(), __fortio_errend03(), __fortio_error(), __io_errno(), __io_printf, __unf_end(), __unf_init(), fcb::acc, assert, fcb::asy_rw, fcb::asyptr, unf_rec_struct::bcnt, fcb::binary, unf_rec_struct::buf, buf_ptr, fcb::byte_swap, unf_rec_struct::bytecnt, count, DBGBIT, FIO_TBL::eof, ERR_FLAG, FIO_TBL::error, FALSE, Fcb, Fio_asy_disable(), FIO_DIRECT, FIO_ETOOBIG, fioFcbTbls, free_gbl(), GBL_SIZE_T_FORMAT, i, io_transfer, IOBUFSIZE, j, MAX_REC_SIZE, NULL, read_flag, rec_in_buf, rec_len, restore_gbl(), rw_size, unf_rec_struct::s, stride, TO_BE_CONTINUED, TRUE, type, unf_rec_struct::u, unf_fwrite(), unf_rec, void(), WRITE_UNF_BUF, and WRITE_UNF_REC.
Referenced by __f90io_usw_write().
__f90io_usw_end()
int __f90io_usw_end (void)
Finish up unformatted, byte swapped read or write. If current I/O is a read, write the current buffer to the file. Whether a read or a write, free the buffer.
\ brief Finish up unformatted read or write. If current I/O is a read, write the current buffer to the file. Whether a read or a write, free the buffer.
Definition at line 1987 of file unf.c.
References __f90io_unf_end(), __usw_end(), FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FIO_TBL::error, Fcb, fioFcbTbls, has_same_fcb, fcb::native, and TO_BE_CONTINUED.
Referenced by __f90io_unf_end(), and ENTF90IO().
__f90io_usw_init()
int __f90io_usw_init (__INT_T * read, __INT_T * unit, __INT_T * rec, __INT_T * bitv, __INT_T * iostat)
Initialize global flags to prepare for byte swapped unformatted I/O, and if the file isn't opened, open it (if possible).
Parameters
read TRUE indicates READ statement.
unit unit number.
rec record number for direct access
bitv same as for ENTF90IO(open_).
iostat same as for ENTF90IO(open_).
Initialize global flags to prepare for byte swapped unformatted I/O, and if the file isn't opened, open it (if possible).
Definition at line 1372 of file unf.c.
References __fortio_errinit(), __fortio_rwinit(), __unf_init(), actual_init, allocate_new_gbl(), bitv, continued, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FALSE, Fcb, FIO_UNFORMATTED, fioFcbTbls, fcb::native, NULL, read, s, save_gbl(), and TRUE.
__f90io_usw_read()
int __f90io_usw_read (int type, long count, int stride, char * item, __CLEN_T item_length)
Read/copy data from an unformatted record file with byte swapping.
Parameters
type Type of data
count number of items of specified type to read. May be <= 0
stride distance in bytes between items
item where to xfer data
item_length
Read/copy data from an unformatted record file with byte swapping.
Definition at line 1426 of file unf.c.
References __CLEN_T, __f90io_unf_read(), __fortio_errend03(), __fortio_error(), __fortio_swap_bytes(), __io_errno(), __io_feof(), __io_fread, __unf_init(), __usw_end(), assert, fcb::asy_rw, fcb::asyptr, fcb::binary, unf_rec_struct::bytecnt, continued, count, FIO_TBL::eof, EOF_FLAG, ERR_FLAG, FIO_TBL::error, Fcb, Fio_asy_disable(), FIO_EEOF, FIO_ETOOBIG, fioFcbTbls, fcb::fp, free_gbl(), io_transfer, fcb::native, NULL, offset, read_flag, rec_len, restore_gbl(), unf_rec_struct::s, skip_to_nextrec(), stride, TO_BE_CONTINUED, TRUE, type, unf_rec_struct::u, unf_rec, and void().
Referenced by __f90io_unf_read().
__f90io_usw_write()
int __f90io_usw_write (int type, long count, int stride, char * item, __CLEN_T item_length)
Write data to an unformatted file with byte swapping.
Parameters
type data type of data (see above).
count number of items of specified type to write. May be <= 0
stride distance in bytes between items.
item where to get data from
item_length
Definition at line 1686 of file unf.c.
References __CLEN_T, __f90io_unf_write(), __fortio_errend03(), __fortio_error(), __fortio_swap_bytes(), __INT, __io_errno(), __io_printf, __STR, __unf_init(), __usw_end(), fcb::acc, assert, unf_rec_struct::bcnt, fcb::binary, unf_rec_struct::buf, buf_ptr, fcb::byte_swap, unf_rec_struct::bytecnt, count, DBGBIT, FIO_TBL::eof, ERR_FLAG, FIO_TBL::error, FALSE, Fcb, FIO_DIRECT, FIO_ENOMEM, FIO_ETOOBIG, fioFcbTbls, fcb::fp, free_gbl(), FWRITE, GBL_SIZE_T_FORMAT, i, io_transfer, IOBUFSIZE, j, malloc(), MAX_REC_SIZE, fcb::native, NULL, pp, RCWSZ, read_flag, rec_in_buf, rec_len, restore_gbl(), rw_size, unf_rec_struct::s, stride, TO_BE_CONTINUED, TRUE, type, unf_rec_struct::u, unf_fwrite(), unf_rec, void(), and WRITE_UNF_BUF.
Referenced by __f90io_unf_write().