flang: upper.h File Reference
upper.h File Reference
Header file for upper - import the lowered F90/HPF code.
#include "gbldefs.h"
#include "semant.h"
Macros
#define VersionMajor 1
#define VersionMinor 55
Functions
char * getexnamestring (char *string, int sptr, int stype, int scg, int extraunderscore)
...
int F90_nme_conflict (int nme1, int nme2)
...
int F90_struct_mbr_nme_conflict (int nme1, int nme2)
Detect Fortran 90 structure member name conflicts. Return 0 if they point to different addresses; Return 1 otherwise.
int getswel (int sz)
...
int IPA_allcall_safe (int sptr)
...
int IPA_call_safe (int funcsptr, int sptr)
...
int IPA_func_almostpure (int sptr)
...
int IPA_func_pure (int sptr)
...
int IPA_nme_conflict (int nme1, int nme2)
...
int IPA_noaddr (int sptr)
...
int IPA_NoFree (void)
...
int IPA_pointer_safe (int nme)
...
int IPA_range (int sptr, int *plo, int *phi)
...
int IPA_safe (int sptr)
...
SPTR llvm_get_uplevel_newsptr (int oldsptr)
...
long IPA_pstride (int sptr)
...
long IPA_sstride (int sptr)
...
void cuda_emu_end (void)
...
void cuda_emu_start (void)
...
void dmp_const (CONST *acl, int indent)
...
void stb_upper_init (void)
...
void upper_assign_addresses (void)
...
void upper_init (void)
...
void upper (int stb_processing)
...
void upper_save_syminfo (void)
...
const char * lookup_modvar_alias (SPTR sptr)
Search for Module variable alias name saved by upper()
SPTR get_symbol_start (void)
return start symbol SPTR
Detailed Description
Header file for upper - import the lowered F90/HPF code.
Definition in file upper.h.
Macro Definition Documentation
VersionMajor
#define VersionMajor 1
Definition at line 144 of file upper.h.
VersionMinor
#define VersionMinor 55
Definition at line 145 of file upper.h.
Function Documentation
cuda_emu_end()
void cuda_emu_end (void)
...
Definition at line 6380 of file upper.cpp.
References cudaemu, cusv, flg, gbl, FLG::profile, FLG::recursive, FLG::smp, and FLG::x.
Referenced by process_input().
cuda_emu_start()
void cuda_emu_start (void)
...
Definition at line 6358 of file upper.cpp.
References cudaemu, cusv, FLG::debug, flg, gbl, FLG::profile, FLG::recursive, FLG::smp, and FLG::x.
Referenced by process_input().
dmp_const()
void dmp_const (CONST * acl, int indent)
...
Definition at line 5383 of file upper.cpp.
Referenced by dmp_const().
F90_nme_conflict()
int F90_nme_conflict (int nme1, int nme2)
...
...
return -1 if nme1/nme2 point to the same address; return 0 if they point to different addresses; return 1 if they may point to the same address
Definition at line 5840 of file upper.cpp.
References count, F90_struct_mbr_nme_conflict(), findindex(), FLANG_FALLTHROUGH, INFO_FGDYNTARGET, INFO_FLDYNTARGET, INFO_FOSTARGET, INFO_FOTARGET, INFO_FSTARGET, INFO_FUNKTARGET, IPNDX_INFO, IPNFO_NEXT, IPNFO_TARGET, IPNFO_TYPE, j1(), n1, n2, NME_NM, NME_SYM, NME_TYPE, NT_IND, NT_VAR, and t2.
Referenced by conflict().
F90_struct_mbr_nme_conflict()
int F90_struct_mbr_nme_conflict (int nme1, int nme2)
Detect Fortran 90 structure member name conflicts. Return 0 if they point to different addresses; Return 1 otherwise.
Detect Fortran 90 structure member name conflicts. Return 0 if they point to different addresses; Return 1 otherwise.
return 0 if they point to different addresses; return 1 otherwise
Definition at line 6003 of file upper.cpp.
References NME_NM, NME_SYM, NME_TYPE, NT_IND, NT_MEM, and NT_VAR.
Referenced by F90_nme_conflict().
get_symbol_start()
SPTR get_symbol_start (void)
return start symbol SPTR
Definition at line 6497 of file upper.cpp.
References oldsymbolcount.
Referenced by process_params().
getexnamestring()
char * getexnamestring (char * string, int sptr, int stype, int scg, int extraunderscore)
...
Definition at line 5458 of file upper.cpp.
getswel()
int getswel (int sz)
...
Definition at line 4426 of file upper.cpp.
References NEED, NEW, sem, SEM::switch_avl, switch_base, SEM::switch_size, and sz.
Referenced by exp_build_agoto(), and read_label().
IPA_allcall_safe()
int IPA_allcall_safe (int sptr)
...
Definition at line 6331 of file upper.cpp.
References findindex(), i, INFO_ALLCALLSAFE, INFO_SAFE, IPA_Safe_Globals_Confirmed, IPNDX_INFO, IPNFO_NEXT, IPNFO_TYPE, n, sptr, and XBIT.
IPA_call_safe()
int IPA_call_safe (int funcsptr, int sptr)
...
Definition at line 6305 of file upper.cpp.
References findindex(), i, INFO_ALLCALLSAFE, INFO_CALLSAFE, INFO_SAFE, IPA_Safe_Globals_Confirmed, IPNDX_INFO, IPNFO_NEXT, IPNFO_TYPE, IPNFO_VAL, n, sptr, and XBIT.
IPA_func_almostpure()
int IPA_func_almostpure (int sptr)
...
...
Returns
1 if function sptr is known to be 'almost pure' that means it does not read or modify globals that are visible in the current file, and does not modify its arguments.
Definition at line 6202 of file upper.cpp.
References findindex(), FINFO_READGLOB, FINFO_READSTATIC, FINFO_WRITEARG, FINFO_WRITEGLOB, FINFO_WRITESTATIC, FUNCLINEG, i, INFO_FUNC, IPA_Func_Propagated, IPNDX_INFO, IPNFO_FUNCINFO, IPNFO_NEXT, IPNFO_TYPE, n, sptr, and XBIT.
IPA_func_pure()
int IPA_func_pure (int sptr)
...
...
Returns
1 if function sptr is known to be 'pure' that means it does not read or modify globals or arguments or file statics.
Definition at line 6176 of file upper.cpp.
References findindex(), i, INFO_FUNC, IPA_Func_Propagated, IPNDX_INFO, IPNFO_FUNCINFO, IPNFO_NEXT, IPNFO_TYPE, n, sptr, and XBIT.
IPA_nme_conflict()
int IPA_nme_conflict (int nme1, int nme2)
...
return -1 if nme1/nme2 point to the same address; return 0 if they point to different addresses; return 1 if they may point to the same address
Definition at line 5698 of file upper.cpp.
References count, findindex(), FLANG_FALLTHROUGH, INFO_GTARGET, INFO_LTARGET, INFO_OGTARGET, INFO_OTARGET, IPA_Pointer_Targets_Disambiguated, IPNDX_INFO, IPNFO_IMPRECISE, IPNFO_INDIRECT, IPNFO_NEXT, IPNFO_TARGET, IPNFO_TYPE, j1(), n1, n2, NME_NM, NME_SYM, NME_TYPE, NT_IND, NT_VAR, t2, and XBIT.
Referenced by IPA_pointer_safe().
IPA_noaddr()
int IPA_noaddr (int sptr)
...
Definition at line 6152 of file upper.cpp.
References findindex(), i, INFO_NOADDR, IPA_Safe_Globals_Confirmed, IPNDX_INFO, IPNFO_NEXT, IPNFO_TYPE, n, sptr, and XBIT.
IPA_NoFree()
int IPA_NoFree (void)
...
Definition at line 6272 of file upper.cpp.
IPA_pointer_safe()
int IPA_pointer_safe (int nme)
...
Returns
1 if sptr is a pointer which has its pointer targets identified, and its pointer targets do not conflict with any other pointers in the program, and do not conflict which any array used in the program. return 0 otherwise
Definition at line 6077 of file upper.cpp.
References findindex(), IPA_nme_conflict(), n, NME_NM, NME_SYM, NME_TYPE, nmeb, NT_IND, NT_VAR, and XBIT.
IPA_pstride()
long IPA_pstride (int sptr)
...
Definition at line 6230 of file upper.cpp.
IPA_range()
int IPA_range (int sptr, int * plo, int * phi)
...
Returns
1 if sptr is known to be within a limited integer range at the start of the function. return 0 otherwise
Definition at line 6128 of file upper.cpp.
References findindex(), i, INFO_RANGE, IPA_Range_Propagated, IPNDX_INFO, IPNFO_HIGH, IPNFO_LOW, IPNFO_NEXT, IPNFO_TYPE, n, sptr, and XBIT.
IPA_safe()
int IPA_safe (int sptr)
...
Definition at line 6282 of file upper.cpp.
IPA_sstride()
long IPA_sstride (int sptr)
...
Definition at line 6251 of file upper.cpp.
llvm_get_uplevel_newsptr()
SPTR llvm_get_uplevel_newsptr (int oldsptr)
...
Definition at line 6465 of file upper.cpp.
References sptr, and symbolxref.
Referenced by _fixup_llvm_uplevel_symbol().
lookup_modvar_alias()
const char * lookup_modvar_alias (SPTR sptr)
Search for Module variable alias name saved by upper()
Parameters
sptr The sptr of a Module variable
Definition at line 6485 of file upper.cpp.
References alias_syminfo::alias, modvar_alias_list, alias_syminfo::next, NULL, sptr, and alias_syminfo::sptr.
Referenced by add_debug_cmnblk_variables(), lldbg_create_imported_entity(), and save_modvar_alias().
stb_upper_init()
void stb_upper_init (void)
...
Definition at line 6432 of file upper.cpp.
References base, end, filename, getlval(), getnamelen(), getval(), level(), line, name, offset, pos, read_line(), and size.
Referenced by main().
upper()
void upper (int stb_processing)
...
...
Size of private array allocated by frontend - the frontend will allocate space for a descriptor and its pointer & offset variables since there is an assumed sequence of allocation.
Definition at line 428 of file upper.cpp.
References agotosz, aux, Begindata(), build_agoto(), BZERO, checkname(), checkversion(), create_static_base(), data_pop_const(), dataConstant(), dataDo(), dataEnddo(), dataReference(), dataStructure(), datatypecount, datatypexref, dataVariable(), DBGBIT, DDTG, direct_import(), dmp_dtype(), do_dinit(), AUX::dpdsc_base, STB::dt, e, endilmfile, ERR_Fatal, errors, first, STB::firstusym, fix_datatype(), fix_symbol(), fixup_llvm_uplevel_symbol(), FREE, freearea(), gbl, getdumlen(), getSptrVal, getval(), i, ilmlinenum, ilmxref, ilmxrefsize, init_upper(), interr(), ISZ_T, line, llvm_stb_processing, NEW, NOSYM, NULL, olddatatypecount, oldsymbolcount, origilmavl, read_CCFF(), read_contained(), read_datatype(), read_Entry(), read_fileentries(), read_global(), read_ilm(), read_init(), read_ipainfo(), read_label(), read_line(), read_overlap(), read_program(), read_symbol(), restore_saved_syminfo(), saved_symbolcount, saved_symbolxref, saved_syminfo, saved_syminfocount, saved_tpcount, saved_tpinfo, set_private_size(), size, SPTR_NULL, stack, stb, STB_UPPER, symbolcount, symbolxref, symdmp(), ts, Writedata(), and XBIT.
Referenced by build_array_list(), check_loop_bound(), ENTF90(), ENTFTN(), exp_smp(), fix_datatype(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), lower_check_subscript(), process_input(), process_stb_file(), and read_datatype().
upper_assign_addresses()
void upper_assign_addresses (void)
...
...
Definition at line 797 of file upper.cpp.
References STB::firstusym, gbl, hostsym_is_refd(), sptr, and stb.
Referenced by process_input(), and process_stb_file().
upper_init()
void upper_init (void)
...
Definition at line 1145 of file upper.cpp.
References base, end, filename, getlval(), getnamelen(), getval(), level(), line, name, offset, pos, read_line(), and size.
Referenced by main().
upper_save_syminfo()
void upper_save_syminfo (void)
...
...
Definition at line 1033 of file upper.cpp.
References upper_syminfo::address, BZERO, upper_syminfo::clen_address, upper_syminfo::clen_memarg, cnt, DDTG, gbl, upper_syminfo::memarg, NEW, NOSYM, upper_syminfo::ref, s, upper_syminfo::save, saved_symbolcount, saved_symbolxref, saved_syminfo, saved_syminfocount, saved_tpcount, saved_tpinfo, upper_syminfo::sc, sptr, and tpcount.
Referenced by process_input(), and process_stb_file().