flang: upperl.l File Reference
upperl.l File Reference
#include <stdio.h>
#include <stdlib.h>
Macros
#define pilm 1
#define psym 2
#define pline 3
#define pdtype 4
#define pnum 5
#define pilms 6
#define psyms 7
#define pargs 8
#define pnums 9
#define chilm 'i'
#define chsym 's'
#define chline 'l'
#define chdtype 't'
#define chargs 'a'
#define chnum 'n'
#define MAXCOMBO 100
#define MAXSTRING 100
Functions
void putdecls ()
void addcombination ()
int yylex (void)
int main (int argc, char *argv[])
...
Variables
FILE * outfile
FILE * mytmpfile
char operation [MAXSTRING]
char ilmname [MAXSTRING]
int linenum
int numoperands
int numoperations = 0
const char * operand [10]
int j
int combinations = 0
int combolen [MAXCOMBO]
char * combo [MAXCOMBO]
Macro Definition Documentation
chargs
#define chargs 'a'
Definition at line 35 of file upperl.l.
chdtype
#define chdtype 't'
Definition at line 34 of file upperl.l.
chilm
#define chilm 'i'
Definition at line 31 of file upperl.l.
chline
#define chline 'l'
Definition at line 33 of file upperl.l.
chnum
#define chnum 'n'
Definition at line 36 of file upperl.l.
chsym
#define chsym 's'
Definition at line 32 of file upperl.l.
MAXCOMBO
#define MAXCOMBO 100
Definition at line 70 of file upperl.l.
MAXSTRING
#define MAXSTRING 100
Definition at line 71 of file upperl.l.
pargs
#define pargs 8
Definition at line 28 of file upperl.l.
pdtype
#define pdtype 4
Definition at line 24 of file upperl.l.
pilm
#define pilm 1
Definition at line 21 of file upperl.l.
pilms
#define pilms 6
Definition at line 26 of file upperl.l.
pline
#define pline 3
Definition at line 23 of file upperl.l.
pnum
#define pnum 5
Definition at line 25 of file upperl.l.
pnums
#define pnums 9
Definition at line 29 of file upperl.l.
psym
#define psym 2
Definition at line 22 of file upperl.l.
psyms
#define psyms 7
Definition at line 27 of file upperl.l.
Function Documentation
addcombination()
void addcombination ()
Definition at line 86 of file upperl.l.
References combinations, combo, combolen, i, linenum, malloc(), MAXCOMBO, MAXSTRING, numoperands, operand, outfile, and strlen().
main()
int main (int argc, char * argv[])
...
...
Parameters
argc number of command-line arguments \pram argv array of command-line argument strings
...
Definition at line 251 of file upperl.l.
References fclose(), linenum, mytmpfile, NULL, numoperations, operation, outfile, putdecls(), yyin, and yylex().
putdecls()
void putdecls ()
Definition at line 39 of file upperl.l.
References chargs, chdtype, chilm, chline, chnum, chsym, outfile, pargs, pdtype, pilm, pilms, pline, pnum, pnums, psym, and psyms.
Referenced by main().
yylex()
int yylex (void)
Definition at line 137 of file upperl.l.
Referenced by main().
Variable Documentation
combinations
int combinations = 0
Definition at line 81 of file upperl.l.
Referenced by addcombination().
combo
char* combo[MAXCOMBO]
Definition at line 83 of file upperl.l.
Referenced by addcombination().
combolen
int combolen[MAXCOMBO]
Definition at line 82 of file upperl.l.
Referenced by addcombination().
ilmname
char ilmname[MAXSTRING]
Definition at line 74 of file upperl.l.
j
int j
Definition at line 79 of file upperl.l.
linenum
int linenum
Definition at line 75 of file upperl.l.
Referenced by addcombination(), and main().
mytmpfile
FILE* mytmpfile
Definition at line 19 of file upperl.l.
Referenced by main().
numoperands
int numoperands
Definition at line 76 of file upperl.l.
Referenced by addcombination().
numoperations
int numoperations = 0
Definition at line 77 of file upperl.l.
Referenced by main().
operand
const char* operand[10]
Definition at line 78 of file upperl.l.
Referenced by addcombination().
operation
char operation[MAXSTRING]
Definition at line 73 of file upperl.l.
Referenced by main().
outfile
FILE* outfile
Definition at line 18 of file upperl.l.
Referenced by addcombination(), main(), and putdecls().