flang: upper.cpp File Reference
upper.cpp File Reference
upper - import the lowered F90/HPF code
#include "upper.h"
#include "error.h"
#include "ilm.h"
#include "ilmtp.h"
#include "semant.h"
#include "semutil0.h"
#include "main.h"
#include "soc.h"
#include "dinit.h"
#include "dinitutl.h"
#include "nme.h"
#include "fih.h"
#include "pragma.h"
#include "ccffinfo.h"
#include "llmputil.h"
#include "llassem.h"
#include "cgraph.h"
#include "semsym.h"
#include "dtypeutl.h"
#include "exp_rte.h"
#include "symfun.h"
#include <stdarg.h>
#include "fdirect.h"
#include "upperilm.h"
Classes
struct CGR_LIST
struct namelist
struct IPAinfo
struct IPAindex
struct SYMinfo
struct repltype
struct repltemptype
struct typelisttype
struct IPAB
struct alias_syminfo
struct typestack
struct upper_syminfo
Macros
#define STB_UPPER() (gbl.stbfil != NULL)
#define DESC_ELM_DT (XBIT(68, 1) ? DT_INT8 : DT_INT)
#define INFO_GTARGET 1
#define INFO_OGTARGET 2
#define INFO_LTARGET 3
#define INFO_OTARGET 4
#define INFO_FLDYNTARGET 5
#define INFO_FGDYNTARGET 6
#define INFO_FUNKTARGET 7
#define INFO_FOTARGET 8
#define INFO_FSTARGET 9
#define INFO_FOSTARGET 10
#define INFO_RANGE 11
#define INFO_SAFE 12
#define INFO_FUNC 13
#define INFO_NEWSYM 14
#define INFO_NOCONFLICT 15
#define INFO_NOADDR 16
#define INFO_PSTRIDE 17
#define INFO_SSTRIDE 18
#define INFO_ALLCALLSAFE 19
#define INFO_CALLSAFE 20
#define FINFO_WRITEARG 0x01
#define FINFO_READGLOB 0x02
#define FINFO_WRITEGLOB 0x04
#define FINFO_READSTATIC 0x08
#define FINFO_WRITESTATIC 0x10
#define Trace(a) TraceOutput a
#define getSptrVal getval
#define getDtypeVal getval
#define getSptrOperand getoperand
#define getDtypeOperand getoperand
#define getTYKind() getkeyword("datatype", Datatypes)
#define getSymType() getkeyword("type", Symboltypes)
#define getSCKind() getkeyword("class", Symbolclasses)
#define getRUType() getkeyword("procedure", Subprogramtypes)
#define getIPAType() getkeyword("type", IPAtypes)
#define IPNDX_SPTR(i) ipab.index[i].sptr
#define IPNDX_INFO(i) ipab.index[i].info
#define IPNFO_TYPE(i) ipab.info[i].type
#define IPNFO_NEXT(i) ipab.info[i].next
#define IPNFO_INDIRECT(i) (ipab.info[i].t.target.indirect >> 1)
#define IPNFO_IMPRECISE(i) (ipab.info[i].t.target.indirect & 0x01)
#define IPNFO_SET(i, indirect, imprecise) (ipab.info[i].t.target.indirect = indirect << 1 + (imprecise ? 1 : 0))
#define IPNFO_SET_IMPRECISE(i) (ipab.info[i].t.target.indirect |= 1)
#define IPNFO_TARGET(i) ipab.info[i].t.target.target
#define IPNFO_LOW(i) ipab.info[i].t.range.low
#define IPNFO_HIGH(i) ipab.info[i].t.range.high
#define IPNFO_FUNCINFO(i) ipab.info[i].t.funcinfo.info
#define IPNFO_PSTRIDE(i) ipab.info[i].t.pstride
#define IPNFO_SSTRIDE(i) ipab.info[i].t.pstride
#define IPNFO_VAL(i) ipab.info[i].t.val.val1
#define IPNFO_VAL2(i) ipab.info[i].t.val.val2
Typedefs
typedef struct CGR_LIST CGR_LIST
typedef struct alias_syminfo alias_syminfo
typedef struct typestack typestack
typedef struct upper_syminfo upper_syminfo
Functions
static int read_line (void)
static void checkversion (const char *text)
static int checkname (const char *text)
static ISZ_T getval (const char *valname)
static long getlval (const char *valname)
static int getbit (const char *bitname)
static void build_agoto (void)
static void free_modvar_alias_list ()
Release the memory space ocupied by the linked list of alias_symifo nodes.
static void save_modvar_alias (SPTR sptr, char *alias_name)
Given a alias name of a mod var sptr, create a new alias_syminfo node and add it to the linked list for later lookup.
static void init_upper (void)
static void read_fileentries (void)
static void read_datatype (void)
static void read_symbol (void)
static void read_overlap (void)
static void read_Entry (void)
static void read_program (void)
static void read_ipainfo (void)
static int newindex (int)
static int newinfo (void)
static void fix_datatype (void)
static void fix_symbol (void)
static int create_thread_private_vector (int, int)
static DTYPE create_threadprivate_dtype (void)
static int getnamelen (void)
static char * getname (void)
static int getoperand (const char *optype, char letter)
static void read_ilm (void)
static void read_label (void)
static void Begindata (void)
static void Writedata (void)
static void dataDo (void)
static void dataEnddo (void)
static void dataConstant (void)
static void dataReference (void)
static void dataStructure (void)
static void dataVariable (void)
static void read_init (void)
static void data_pop_const (void)
static void data_push_const (void)
static void read_global (void)
static int read_CCFF (void)
static void read_contained (void)
static void TraceOutput (const char *fmt,...)
static void restore_saved_syminfo (int)
static int getkeyword (const char *keyname, const namelist NL[])
void upper (int stb_processing)
Entry point for reading in ILM file.
void upper_assign_addresses (void)
For outer routines that contain inner routines, make sure all variables get an address, even if never used in this routine, in case they are used by the contained routines.
void upper_save_syminfo (void)
Save information about symbols for this outer routine to restore inside other inner routines.
void upper_init (void)
...
static void skipwhitespace (void)
static int checkbitname (const char *name)
static void getpair (SPTR *first, SPTR *second)
static int getnum (void)
static int gethex (void)
static int match (const char *K)
static SPTR newsymbol (void)
static int newintrinsic (int wantstype)
static char gethexchar (FILE *file)
static SPTR get_or_create_symbol (SPTR sptr)
static void addpstride (int sptr, long stride)
static void addsstride (int sptr, long stride)
static void addf90target (int sptr, int targettype, int targetid)
static void addsafe (int sptr, int safetype, int val)
static int getilm (void)
static int getoperation (void)
static int getlabelnum (void)
int getswel (int sz)
...
static void data_add_ivl (VAR *ivl)
static void data_add_const (CONST *ict)
static void push (int *value)
static int * pop (void)
static void push_typestack (void)
static void put_prefix (FILE *dfile, char *str, int cnt)
void dmp_const (CONST *acl, int indent)
...
char * getexnamestring (char *string, int sptr, int stype, int scg, int extraunderscore)
...
static int findindex (int sptr)
int IPA_nme_conflict (int nme1, int nme2)
...
int F90_nme_conflict (int nme1, int nme2)
Detect Fortran 90 name conflicts.
int F90_struct_mbr_nme_conflict (int nme1, int nme2)
Detect Fortran 90 structure member name conflicts.
int IPA_pointer_safe (int nme)
...
int IPA_range (int sptr, int *plo, int *phi)
...
int IPA_noaddr (int sptr)
...
int IPA_func_pure (int sptr)
detect pure function from IPA standpoint
int IPA_func_almostpure (int sptr)
detect "almost pure" function for IPA
long IPA_pstride (int sptr)
...
long IPA_sstride (int sptr)
...
int IPA_NoFree (void)
...
int IPA_safe (int sptr)
...
int IPA_call_safe (int funcsptr, int sptr)
...
int IPA_allcall_safe (int sptr)
...
void cuda_emu_start (void)
...
void cuda_emu_end (void)
...
void stb_upper_init (void)
...
SPTR llvm_get_uplevel_newsptr (int oldsptr)
...
const char * lookup_modvar_alias (SPTR sptr)
Search for Module variable alias name saved by upper()
SPTR get_symbol_start (void)
return start symbol SPTR
Variables
static int endilmfile
static int ilmlinenum = 0
static char * line = NULL
static int linelen = 0
static int pos
static int do_level = 0
static int in_array_ctor = 0
static int oprnd_cnt = 0
static int passbyflags = 1
static int cfuncflags = 1
static int cudaflags = 1
static int cudaemu = 0
int init_list_count
static int llvm_stb_processing = 0
static const namelist IPAtypes []
static const namelist Datatypes []
static const namelist Symboltypes []
static const namelist Symbolclasses []
static const namelist Subprogramtypes []
static int symbolcount = 0
static int datatypecount = 0
static int oldsymbolcount = 0
static int olddatatypecount = 0
static SPTR * symbolxref
static DTYPE * datatypexref
static int * agototab
static int agotosz = 0
static int agotomax
int IPA_Pointer_Targets_Disambiguated = 0
int IPA_Safe_Globals_Confirmed = 0
int IPA_Range_Propagated = 0
int IPA_Func_Propagated = 0
int IPA_Pointer_Strides_Propagated = 0
static alias_syminfo * modvar_alias_list
static IPAB ipab
static int errors
static int stack_top
static int stack_size
static int ** stack
static typestack * ts
static int tsl = -1
static int tssize = 0
static SPTR * saved_symbolxref
static int saved_symbolcount = 0
static upper_syminfo * saved_syminfo
static int saved_syminfocount = 0
static upper_syminfo * saved_tpinfo
static int saved_tpcount = 0
static int tpcount
static DTYPE threadprivate_dtype
static int * ilmxref
static int ilmxrefsize
static int origilmavl
static VAR * dataivl
static VAR * lastivl
static CONST * dataict
static CONST * lastict
static CONST * outerict
struct {
bool smp
bool recursive
int profile
int x5
int x121
int x123
} cusv
Detailed Description
upper - import the lowered F90/HPF code
Definition in file upper.cpp.
Macro Definition Documentation
DESC_ELM_DT
#define DESC_ELM_DT (XBIT(68, 1) ? DT_INT8 : DT_INT)
Definition at line 112 of file upper.cpp.
FINFO_READGLOB
#define FINFO_READGLOB 0x02
Definition at line 264 of file upper.cpp.
FINFO_READSTATIC
#define FINFO_READSTATIC 0x08
Definition at line 266 of file upper.cpp.
FINFO_WRITEARG
#define FINFO_WRITEARG 0x01
Definition at line 263 of file upper.cpp.
FINFO_WRITEGLOB
#define FINFO_WRITEGLOB 0x04
Definition at line 265 of file upper.cpp.
FINFO_WRITESTATIC
#define FINFO_WRITESTATIC 0x10
Definition at line 267 of file upper.cpp.
getDtypeOperand
#define getDtypeOperand getoperand
Definition at line 394 of file upper.cpp.
getDtypeVal
#define getDtypeVal getval
Definition at line 392 of file upper.cpp.
getIPAType
#define getIPAType () getkeyword("type", IPAtypes)
Definition at line 399 of file upper.cpp.
getRUType
#define getRUType () getkeyword("procedure", Subprogramtypes)
Definition at line 398 of file upper.cpp.
getSCKind
#define getSCKind () getkeyword("class", Symbolclasses)
Definition at line 397 of file upper.cpp.
getSptrOperand
#define getSptrOperand getoperand
Definition at line 393 of file upper.cpp.
getSptrVal
#define getSptrVal getval
Definition at line 391 of file upper.cpp.
getSymType
#define getSymType () getkeyword("type", Symboltypes)
Definition at line 396 of file upper.cpp.
getTYKind
#define getTYKind () getkeyword("datatype", Datatypes)
Definition at line 395 of file upper.cpp.
INFO_ALLCALLSAFE
#define INFO_ALLCALLSAFE 19
Definition at line 229 of file upper.cpp.
INFO_CALLSAFE
#define INFO_CALLSAFE 20
Definition at line 230 of file upper.cpp.
INFO_FGDYNTARGET
#define INFO_FGDYNTARGET 6
Definition at line 216 of file upper.cpp.
INFO_FLDYNTARGET
#define INFO_FLDYNTARGET 5
Definition at line 215 of file upper.cpp.
INFO_FOSTARGET
#define INFO_FOSTARGET 10
Definition at line 220 of file upper.cpp.
INFO_FOTARGET
#define INFO_FOTARGET 8
Definition at line 218 of file upper.cpp.
INFO_FSTARGET
#define INFO_FSTARGET 9
Definition at line 219 of file upper.cpp.
INFO_FUNC
#define INFO_FUNC 13
Definition at line 223 of file upper.cpp.
INFO_FUNKTARGET
#define INFO_FUNKTARGET 7
Definition at line 217 of file upper.cpp.
INFO_GTARGET
#define INFO_GTARGET 1
Definition at line 211 of file upper.cpp.
INFO_LTARGET
#define INFO_LTARGET 3
Definition at line 213 of file upper.cpp.
INFO_NEWSYM
#define INFO_NEWSYM 14
Definition at line 224 of file upper.cpp.
INFO_NOADDR
#define INFO_NOADDR 16
Definition at line 226 of file upper.cpp.
INFO_NOCONFLICT
#define INFO_NOCONFLICT 15
Definition at line 225 of file upper.cpp.
INFO_OGTARGET
#define INFO_OGTARGET 2
Definition at line 212 of file upper.cpp.
INFO_OTARGET
#define INFO_OTARGET 4
Definition at line 214 of file upper.cpp.
INFO_PSTRIDE
#define INFO_PSTRIDE 17
Definition at line 227 of file upper.cpp.
INFO_RANGE
#define INFO_RANGE 11
Definition at line 221 of file upper.cpp.
INFO_SAFE
#define INFO_SAFE 12
Definition at line 222 of file upper.cpp.
INFO_SSTRIDE
#define INFO_SSTRIDE 18
Definition at line 228 of file upper.cpp.
IPNDX_INFO
#define IPNDX_INFO (i) ipab.index[i].info
Definition at line 403 of file upper.cpp.
IPNDX_SPTR
#define IPNDX_SPTR (i) ipab.index[i].sptr
Definition at line 402 of file upper.cpp.
IPNFO_FUNCINFO
#define IPNFO_FUNCINFO (i) ipab.info[i].t.funcinfo.info
Definition at line 414 of file upper.cpp.
IPNFO_HIGH
#define IPNFO_HIGH (i) ipab.info[i].t.range.high
Definition at line 413 of file upper.cpp.
IPNFO_IMPRECISE
#define IPNFO_IMPRECISE (i) (ipab.info[i].t.target.indirect & 0x01)
Definition at line 407 of file upper.cpp.
IPNFO_INDIRECT
#define IPNFO_INDIRECT (i) (ipab.info[i].t.target.indirect >> 1)
Definition at line 406 of file upper.cpp.
IPNFO_LOW
#define IPNFO_LOW (i) ipab.info[i].t.range.low
Definition at line 412 of file upper.cpp.
IPNFO_NEXT
#define IPNFO_NEXT (i) ipab.info[i].next
Definition at line 405 of file upper.cpp.
IPNFO_PSTRIDE
#define IPNFO_PSTRIDE (i) ipab.info[i].t.pstride
Definition at line 415 of file upper.cpp.
IPNFO_SET
#define IPNFO_SET (i, indirect, imprecise) (ipab.info[i].t.target.indirect = indirect << 1 + (imprecise ? 1 : 0))
Definition at line 408 of file upper.cpp.
IPNFO_SET_IMPRECISE
#define IPNFO_SET_IMPRECISE (i) (ipab.info[i].t.target.indirect |= 1)
Definition at line 410 of file upper.cpp.
IPNFO_SSTRIDE
#define IPNFO_SSTRIDE (i) ipab.info[i].t.pstride
Definition at line 416 of file upper.cpp.
IPNFO_TARGET
#define IPNFO_TARGET (i) ipab.info[i].t.target.target
Definition at line 411 of file upper.cpp.
IPNFO_TYPE
#define IPNFO_TYPE (i) ipab.info[i].type
Definition at line 404 of file upper.cpp.
IPNFO_VAL
#define IPNFO_VAL (i) ipab.info[i].t.val.val1
Definition at line 417 of file upper.cpp.
IPNFO_VAL2
#define IPNFO_VAL2 (i) ipab.info[i].t.val.val2
Definition at line 418 of file upper.cpp.
STB_UPPER
#define STB_UPPER () (gbl.stbfil != NULL)
Definition at line 61 of file upper.cpp.
Trace
#define Trace (a) TraceOutput a
Definition at line 278 of file upper.cpp.
Typedef Documentation
alias_syminfo
typedef struct alias_syminfo alias_syminfo
CGR_LIST
typedef struct CGR_LIST CGR_LIST
typestack
typedef struct typestack typestack
upper_syminfo
typedef struct upper_syminfo upper_syminfo
Function Documentation
addf90target()
static void addf90target (int sptr, int targettype, int targetid) static
Definition at line 3388 of file upper.cpp.
References i, IPNDX_INFO, IPNFO_NEXT, IPNFO_TARGET, IPNFO_TYPE, j, newindex(), newinfo(), sptr, targettype, and Trace.
Referenced by read_ipainfo().
addpstride()
static void addpstride (int sptr, long stride) static
Definition at line 3357 of file upper.cpp.
References i, INFO_PSTRIDE, IPNDX_INFO, IPNFO_NEXT, IPNFO_PSTRIDE, IPNFO_TYPE, j, newindex(), newinfo(), sptr, stride, SYMNAME, Trace, and XBIT.
Referenced by read_ipainfo().
addsafe()
static void addsafe (int sptr, int safetype, int val) static
Definition at line 3401 of file upper.cpp.
References i, IPNDX_INFO, IPNFO_NEXT, IPNFO_TYPE, IPNFO_VAL, j, newindex(), newinfo(), sptr, Trace, and val.
Referenced by read_ipainfo().
addsstride()
static void addsstride (int sptr, long stride) static
Definition at line 3373 of file upper.cpp.
References i, INFO_SSTRIDE, IPNDX_INFO, IPNFO_NEXT, IPNFO_SSTRIDE, IPNFO_TYPE, j, newindex(), newinfo(), sptr, stride, SYMNAME, Trace, and XBIT.
Referenced by read_ipainfo().
Begindata()
static void Begindata (void) static
Definition at line 4878 of file upper.cpp.
References BOS_SIZE, dataict, dataivl, ILMB::ilmavl, ilmb, lastict, lastivl, NULL, and outerict.
Referenced by upper().
build_agoto()
static void build_agoto (void) static
Definition at line 6474 of file upper.cpp.
References agotomax, agotosz, agototab, exp_build_agoto(), and FREE.
Referenced by upper().
checkbitname()
static int checkbitname (const char * name) static
Definition at line 1297 of file upper.cpp.
References i, line, name, and pos.
Referenced by getbit().
checkname()
static int checkname (const char * text) static
Definition at line 1272 of file upper.cpp.
References i, line, name, and pos.
Referenced by dataConstant(), dataDo(), dataEnddo(), dataReference(), dataStructure(), dataVariable(), getlval(), getval(), read_CCFF(), read_contained(), read_init(), read_program(), and upper().
checkversion()
static void checkversion (const char * text) static
Definition at line 1212 of file upper.cpp.
References cfuncflags, check(), cudaflags, line, passbyflags, VersionMajor, and VersionMinor.
Referenced by upper().
create_thread_private_vector()
static int create_thread_private_vector (int sptr, int host_tpsym) static
Definition at line 4009 of file upper.cpp.
References ADDSYM, create_threadprivate_dtype(), gbl, HASH_ID, len, MAXIDLEN, putsname(), s, saved_tpcount, saved_tpinfo, sptr, strlen(), SYMNAME, threadprivate_dtype, and tpcount.
Referenced by fix_symbol(), and restore_saved_syminfo().
create_threadprivate_dtype()
static DTYPE create_threadprivate_dtype (void) static
Definition at line 4068 of file upper.cpp.
References AD_DPTR, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_SCHECK, AD_UPBD, AD_ZBASE, DESC_ELM_DT, dt, get_array_dtype(), getcon(), MAXCPUS, one, val, and zero.
Referenced by create_thread_private_vector().
cuda_emu_end()
void cuda_emu_end (void)
...
Definition at line 6380 of file upper.cpp.
References cudaemu, cusv, flg, gbl, FLG::profile, FLG::recursive, FLG::smp, and FLG::x.
Referenced by process_input().
cuda_emu_start()
void cuda_emu_start (void)
...
Definition at line 6358 of file upper.cpp.
References cudaemu, cusv, FLG::debug, flg, gbl, FLG::profile, FLG::recursive, FLG::smp, and FLG::x.
Referenced by process_input().
data_add_const()
static void data_add_const (CONST * ict) static
Definition at line 4513 of file upper.cpp.
References dataict, lastict, CONST::next, and NULL.
Referenced by dataConstant(), and dataStructure().
data_add_ivl()
static void data_add_ivl (VAR * ivl) static
Definition at line 4478 of file upper.cpp.
References dataivl, lastivl, VAR::next, and NULL.
Referenced by dataDo(), dataEnddo(), dataReference(), and dataVariable().
data_pop_const()
static void data_pop_const (void) static
Definition at line 4500 of file upper.cpp.
References dataict, lastict, CONST::next, outerict, and CONST::subc.
Referenced by dataConstant(), and upper().
data_push_const()
static void data_push_const (void) static
Definition at line 4490 of file upper.cpp.
References dataict, lastict, NULL, outerict, and CONST::subc.
Referenced by dataConstant(), and dataStructure().
dataConstant()
static void dataConstant (void) static
Definition at line 4972 of file upper.cpp.
References AC_ACONST, AC_CONST, AC_IDENT, AC_IDO, AC_IEXPR, AC_UNARY_OP, BZERO, chdtype, checkname(), chnum, chsym, CONST::conval, data_add_const(), data_pop_const(), data_push_const(), do_level, DT_INT, DTY, CONST::dtype, errors, CONST::expr, getDtypeOperand, getitem(), getoperand(), getSptrOperand, getval(), CONST::id, CONST::ido, ilmlinenum, in_array_ctor, IDOINFO::index_var, init_list_count, IDOINFO::initval, lastict, IDOINFO::limitval, line, AEXPR::lop, CONST::mbr, AEXPR::op, oprnd_cnt, pos, CONST::repeatc, AEXPR::rop, skipwhitespace(), CONST::sptr, IDOINFO::stepval, CONST::subc, SymConval1, and CONST::u1.
Referenced by upper().
dataDo()
static void dataDo (void) static
Definition at line 4893 of file upper.cpp.
References BZERO, checkname(), chilm, data_add_ivl(), Dostart, VAR::dostart, errors, getitem(), getoperand(), VAR::id, ilmlinenum, VAR::indvar, line, VAR::lowbd, push(), VAR::step, VAR::u, and VAR::upbd.
Referenced by upper().
dataEnddo()
static void dataEnddo (void) static
Definition at line 4914 of file upper.cpp.
References BZERO, checkname(), data_add_ivl(), Doend, VAR::doend, VAR::dostart, errors, getitem(), VAR::id, ilmlinenum, line, pop(), and VAR::u.
Referenced by upper().
dataReference()
static void dataReference (void) static
Definition at line 4931 of file upper.cpp.
References BZERO, chdtype, checkname(), chilm, data_add_ivl(), VAR::dtype, errors, getDtypeOperand, getitem(), getoperand(), VAR::id, ilmlinenum, line, VAR::ptr, S_LVALUE, VAR::shape, VAR::u, Varref, and VAR::varref.
Referenced by upper().
dataStructure()
static void dataStructure (void) static
Definition at line 5157 of file upper.cpp.
References AC_SCONST, BZERO, chdtype, checkname(), chnum, chsym, data_add_const(), data_push_const(), CONST::dtype, errors, getDtypeOperand, getitem(), getoperand(), getSptrOperand, CONST::id, ilmlinenum, line, CONST::no_dinitp, CONST::repeatc, and CONST::sptr.
Referenced by upper().
dataVariable()
static void dataVariable (void) static
Definition at line 4952 of file upper.cpp.
References BZERO, chdtype, checkname(), chilm, data_add_ivl(), VAR::dtype, errors, getDtypeOperand, getitem(), getoperand(), VAR::id, ilmlinenum, line, VAR::ptr, S_IDENT, VAR::shape, VAR::u, Varref, and VAR::varref.
Referenced by upper().
dmp_const()
void dmp_const (CONST * acl, int indent)
...
Definition at line 5383 of file upper.cpp.
References AC_ACONST, AC_CONST, AC_IDENT, AC_IDO, AC_IEXPR, AC_SCONST, CONST::conval, dfile, dmp_const(), CONST::expr, FILE, gbl, CONST::id, CONST::ido, indent, IDOINFO::index_var, IDOINFO::initval, IDOINFO::limitval, AEXPR::lop, CONST::next, AEXPR::op, put_prefix(), CONST::repeatc, AEXPR::rop, CONST::sptr, IDOINFO::stepval, CONST::subc, SYMNAME, and CONST::u1.
Referenced by dmp_const().
F90_nme_conflict()
int F90_nme_conflict (int nme1, int nme2)
Detect Fortran 90 name conflicts.
...
return -1 if nme1/nme2 point to the same address; return 0 if they point to different addresses; return 1 if they may point to the same address
Definition at line 5840 of file upper.cpp.
References count, F90_struct_mbr_nme_conflict(), findindex(), FLANG_FALLTHROUGH, INFO_FGDYNTARGET, INFO_FLDYNTARGET, INFO_FOSTARGET, INFO_FOTARGET, INFO_FSTARGET, INFO_FUNKTARGET, IPNDX_INFO, IPNFO_NEXT, IPNFO_TARGET, IPNFO_TYPE, j1(), n1, n2, NME_NM, NME_SYM, NME_TYPE, NT_IND, NT_VAR, and t2.
Referenced by conflict().
F90_struct_mbr_nme_conflict()
int F90_struct_mbr_nme_conflict (int nme1, int nme2)
Detect Fortran 90 structure member name conflicts.
Detect Fortran 90 structure member name conflicts. Return 0 if they point to different addresses; Return 1 otherwise.
return 0 if they point to different addresses; return 1 otherwise
Definition at line 6003 of file upper.cpp.
References NME_NM, NME_SYM, NME_TYPE, NT_IND, NT_MEM, and NT_VAR.
Referenced by F90_nme_conflict().
findindex()
static int findindex (int sptr) static
Definition at line 5671 of file upper.cpp.
References h, i, IPAB::indexavl, ipab, IPNDX_SPTR, and sptr.
Referenced by F90_nme_conflict(), IPA_allcall_safe(), IPA_call_safe(), IPA_func_almostpure(), IPA_func_pure(), IPA_nme_conflict(), IPA_noaddr(), IPA_pointer_safe(), IPA_pstride(), IPA_range(), IPA_safe(), and IPA_sstride().
fix_datatype()
static void fix_datatype (void) static
Definition at line 1780 of file upper.cpp.
References AD_DPTR, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_UPBD, AD_ZBASE, d, datatypecount, datatypexref, DTY, DTyAlgTyMember, DTyAlgTyTag, DTyFuncVal, DTyInterface, DTyParamDesc, DTyReturnType, DTySeqTyElement, DTySetAlgTyTag, DTySetFst, DTySetFuncVal, DTySetInterface, DTySetParamDesc, errors, i, lower(), ndim, olddatatypecount, oldsymbolcount, pdtype, symbolxref, upper(), and zbase.
Referenced by upper().
fix_symbol()
static void fix_symbol (void) static
Definition at line 3498 of file upper.cpp.
References AD_DPTR, AD_SDSC, assert, aux, CMEMLP, common, CONVAL2G, CONVAL2P, create_thread_private_vector(), DLL_EXPORT, DLL_IMPORT, DLLG, DLLP, AUX::dpdsc_base, DTY, ERR_Fatal, FLANG_FALLTHROUGH, gbl, i, IS_THREAD_TP, llmp_create_uplevel_bykey(), llmp_get_next_key(), llmp_get_uplevel(), llmp_has_uplevel(), nml, NML_NEXT, NML_SPTR, NOSYM, oldsymbolcount, ORIGDUMMYG, ORIGDUMMYP, LLUplevel::parent, plist(), scope, smax, spec, sptr, stb, sym_is_refd(), symbolxref, SYMI_NEXT, SYMI_SPTR, threadprivate_dtype, tpcount, TY_DCMPLX, TY_HOLL, TY_ISWORD, val, LLUplevel::vals, LLUplevel::vals_count, and XBIT.
Referenced by upper().
free_modvar_alias_list()
static void free_modvar_alias_list (void) static
Release the memory space ocupied by the linked list of alias_symifo nodes.
Definition at line 6520 of file upper.cpp.
References alias_syminfo::alias, FREE, modvar_alias_list, and alias_syminfo::next.
Referenced by init_upper().
get_or_create_symbol()
static SPTR get_or_create_symbol (SPTR sptr) static
Definition at line 1991 of file upper.cpp.
References newsymbol(), sptr, and symbolxref.
Referenced by read_symbol().
get_symbol_start()
SPTR get_symbol_start (void)
return start symbol SPTR
Definition at line 6497 of file upper.cpp.
References oldsymbolcount.
Referenced by process_params().
getbit()
static int getbit (const char * bitname) static
Definition at line 1394 of file upper.cpp.
References checkbitname(), endilmfile, errors, ilmlinenum, line, pos, skipwhitespace(), and Trace.
Referenced by read_label(), and read_symbol().
getexnamestring()
char * getexnamestring (char * string, int sptr, int stype, int scg, int extraunderscore)
...
Definition at line 5458 of file upper.cpp.
References FLG::dollar, flg, gbl, m, NEED, NEW, NULL, s, sptr, ss, strlen(), SYMNAME, upcase_name(), and XBIT.
Referenced by ccff_open_unit().
gethex()
static int gethex (void) static
Definition at line 1504 of file upper.cpp.
References endilmfile, errors, line, pos, skipwhitespace(), Trace, and val.
Referenced by read_symbol().
gethexchar()
static char gethexchar (FILE * file) static
Definition at line 1947 of file upper.cpp.
References val.
Referenced by read_symbol().
getilm()
static int getilm (void) static
Definition at line 4100 of file upper.cpp.
References endilmfile, errors, ilmlinenum, line, pos, and val.
Referenced by read_ilm().
getkeyword()
static int getkeyword (const char * keyname, const namelist NL[]) static
Definition at line 1552 of file upper.cpp.
References endilmfile, errors, i, ilmlinenum, namelist::keyvalue, keyword(), namelist::keyword, line, match(), pos, skipwhitespace(), and Trace.
getlabelnum()
static int getlabelnum (void) static
Definition at line 4398 of file upper.cpp.
References endilmfile, errors, ilmlinenum, line, pos, and val.
Referenced by read_label().
getlval()
static long getlval (const char * valname) static
Definition at line 1356 of file upper.cpp.
References checkname(), endilmfile, errors, ilmlinenum, line, neg(), pos, skipwhitespace(), Trace, and val.
Referenced by read_fileentries(), read_ipainfo(), stb_upper_init(), and upper_init().
getname()
static char * getname (void) static
Definition at line 1607 of file upper.cpp.
References getnamelen(), len, line, name, and pos.
Referenced by read_CCFF().
getnamelen()
static int getnamelen (void) static
Definition at line 1584 of file upper.cpp.
References endilmfile, errors, line, pos, skipwhitespace(), Trace, and val.
Referenced by getname(), newintrinsic(), newsymbol(), read_contained(), read_fileentries(), read_symbol(), stb_upper_init(), and upper_init().
getnum()
static int getnum (void) static
Definition at line 1482 of file upper.cpp.
References endilmfile, errors, line, pos, skipwhitespace(), Trace, and val.
Referenced by read_overlap(), and read_symbol().
getoperand()
static int getoperand (const char * optype, char letter) static
Definition at line 4129 of file upper.cpp.
References chdtype, chilm, chline, chnum, chsym, datatypexref, endilmfile, errors, ilmlinenum, ilmxref, line, neg(), optype(), origilmavl, pos, skipwhitespace(), symbolxref, and val.
Referenced by dataConstant(), dataDo(), dataReference(), dataStructure(), dataVariable(), and read_ilm().
getoperation()
static int getoperation (void) static
Definition at line 4205 of file upper.cpp.
References endilmfile, errors, hi, ilmlinenum, info, len, line, lo, name, p, pos, and skipwhitespace().
Referenced by read_ilm().
getpair()
static void getpair (SPTR * first, SPTR * second) static
Definition at line 1433 of file upper.cpp.
References endilmfile, errors, first, ilmlinenum, line, neg(), pos, skipwhitespace(), SPTR_NULL, and val.
Referenced by read_datatype().
getswel()
int getswel (int sz)
...
Definition at line 4426 of file upper.cpp.
References NEED, NEW, sem, SEM::switch_avl, switch_base, SEM::switch_size, and sz.
Referenced by exp_build_agoto(), and read_label().
getval()
static ISZ_T getval (const char * valname) static
Definition at line 1318 of file upper.cpp.
References checkname(), endilmfile, errors, ilmlinenum, ISZ_T, line, neg(), pos, skipwhitespace(), Trace, and val.
Referenced by dataConstant(), read_CCFF(), read_datatype(), read_fileentries(), read_global(), read_init(), read_ipainfo(), read_label(), read_overlap(), read_symbol(), stb_upper_init(), upper(), and upper_init().
init_upper()
static void init_upper (void) static
Definition at line 1107 of file upper.cpp.
References SOC::avail, errors, free_modvar_alias_list(), gbl, IPAB::index, IPAB::indexavl, IPAB::indexsize, IPAB::info, IPAB::infoavl, IPAB::infosize, ipab, line, linelen, malloc(), modvar_alias_list, NEW, NOSYM, NULL, soc, stack, stack_size, stack_top, ts, tsl, and tssize.
Referenced by upper().
IPA_allcall_safe()
int IPA_allcall_safe (int sptr)
...
Definition at line 6331 of file upper.cpp.
References findindex(), i, INFO_ALLCALLSAFE, INFO_SAFE, IPA_Safe_Globals_Confirmed, IPNDX_INFO, IPNFO_NEXT, IPNFO_TYPE, n, sptr, and XBIT.
IPA_call_safe()
int IPA_call_safe (int funcsptr, int sptr)
...
Definition at line 6305 of file upper.cpp.
References findindex(), i, INFO_ALLCALLSAFE, INFO_CALLSAFE, INFO_SAFE, IPA_Safe_Globals_Confirmed, IPNDX_INFO, IPNFO_NEXT, IPNFO_TYPE, IPNFO_VAL, n, sptr, and XBIT.
IPA_func_almostpure()
int IPA_func_almostpure (int sptr)
detect "almost pure" function for IPA
...
Returns
1 if function sptr is known to be 'almost pure' that means it does not read or modify globals that are visible in the current file, and does not modify its arguments.
Definition at line 6202 of file upper.cpp.
References findindex(), FINFO_READGLOB, FINFO_READSTATIC, FINFO_WRITEARG, FINFO_WRITEGLOB, FINFO_WRITESTATIC, FUNCLINEG, i, INFO_FUNC, IPA_Func_Propagated, IPNDX_INFO, IPNFO_FUNCINFO, IPNFO_NEXT, IPNFO_TYPE, n, sptr, and XBIT.
IPA_func_pure()
int IPA_func_pure (int sptr)
detect pure function from IPA standpoint
...
Returns
1 if function sptr is known to be 'pure' that means it does not read or modify globals or arguments or file statics.
Definition at line 6176 of file upper.cpp.
References findindex(), i, INFO_FUNC, IPA_Func_Propagated, IPNDX_INFO, IPNFO_FUNCINFO, IPNFO_NEXT, IPNFO_TYPE, n, sptr, and XBIT.
IPA_nme_conflict()
int IPA_nme_conflict (int nme1, int nme2)
...
return -1 if nme1/nme2 point to the same address; return 0 if they point to different addresses; return 1 if they may point to the same address
Definition at line 5698 of file upper.cpp.
References count, findindex(), FLANG_FALLTHROUGH, INFO_GTARGET, INFO_LTARGET, INFO_OGTARGET, INFO_OTARGET, IPA_Pointer_Targets_Disambiguated, IPNDX_INFO, IPNFO_IMPRECISE, IPNFO_INDIRECT, IPNFO_NEXT, IPNFO_TARGET, IPNFO_TYPE, j1(), n1, n2, NME_NM, NME_SYM, NME_TYPE, NT_IND, NT_VAR, t2, and XBIT.
Referenced by IPA_pointer_safe().
IPA_noaddr()
int IPA_noaddr (int sptr)
...
Definition at line 6152 of file upper.cpp.
References findindex(), i, INFO_NOADDR, IPA_Safe_Globals_Confirmed, IPNDX_INFO, IPNFO_NEXT, IPNFO_TYPE, n, sptr, and XBIT.
IPA_NoFree()
int IPA_NoFree (void)
...
Definition at line 6272 of file upper.cpp.
IPA_pointer_safe()
int IPA_pointer_safe (int nme)
...
Returns
1 if sptr is a pointer which has its pointer targets identified, and its pointer targets do not conflict with any other pointers in the program, and do not conflict which any array used in the program. return 0 otherwise
Definition at line 6077 of file upper.cpp.
References findindex(), IPA_nme_conflict(), n, NME_NM, NME_SYM, NME_TYPE, nmeb, NT_IND, NT_VAR, and XBIT.
IPA_pstride()
long IPA_pstride (int sptr)
...
Definition at line 6230 of file upper.cpp.
References findindex(), i, INFO_PSTRIDE, IPA_Pointer_Strides_Propagated, IPNDX_INFO, IPNFO_NEXT, IPNFO_PSTRIDE, IPNFO_TYPE, n, sptr, and XBIT.
IPA_range()
int IPA_range (int sptr, int * plo, int * phi)
...
Returns
1 if sptr is known to be within a limited integer range at the start of the function. return 0 otherwise
Definition at line 6128 of file upper.cpp.
References findindex(), i, INFO_RANGE, IPA_Range_Propagated, IPNDX_INFO, IPNFO_HIGH, IPNFO_LOW, IPNFO_NEXT, IPNFO_TYPE, n, sptr, and XBIT.
IPA_safe()
int IPA_safe (int sptr)
...
Definition at line 6282 of file upper.cpp.
References findindex(), i, INFO_SAFE, IPA_Safe_Globals_Confirmed, IPNDX_INFO, IPNFO_NEXT, IPNFO_TYPE, n, sptr, and XBIT.
IPA_sstride()
long IPA_sstride (int sptr)
...
Definition at line 6251 of file upper.cpp.
References findindex(), i, INFO_SSTRIDE, IPA_Pointer_Strides_Propagated, IPNDX_INFO, IPNFO_NEXT, IPNFO_SSTRIDE, IPNFO_TYPE, n, sptr, and XBIT.
llvm_get_uplevel_newsptr()
SPTR llvm_get_uplevel_newsptr (int oldsptr)
...
Definition at line 6465 of file upper.cpp.
References sptr, and symbolxref.
Referenced by _fixup_llvm_uplevel_symbol().
lookup_modvar_alias()
const char * lookup_modvar_alias (SPTR sptr)
Search for Module variable alias name saved by upper()
Parameters
sptr The sptr of a Module variable
Definition at line 6485 of file upper.cpp.
References alias_syminfo::alias, modvar_alias_list, alias_syminfo::next, NULL, sptr, and alias_syminfo::sptr.
Referenced by add_debug_cmnblk_variables(), lldbg_create_imported_entity(), and save_modvar_alias().
match()
static int match (const char * K) static
Definition at line 1536 of file upper.cpp.
References j, line, and pos.
Referenced by _addtpte(), collectIncludePaths(), ENT3F(), find(), find_allocatable_assignment(), find_lpprg(), Ftn_nstr_index(), Ftn_nstr_index_klen(), Ftn_str_index_klen(), ftn_str_kindex(), ftn_str_kindex_klen(), getkeyword(), open_pragma(), pop_pragma(), and push_pragma().
newindex()
static int newindex (int sptr) static
Definition at line 5622 of file upper.cpp.
References h, i, IPAB::index, IPAB::indexavl, IPAB::indexsize, ipab, IPNDX_INFO, IPNDX_SPTR, j, NEED, sptr, SYMNAME, and Trace.
Referenced by addf90target(), addpstride(), addsafe(), and addsstride().
newinfo()
static int newinfo (void) static
Definition at line 5659 of file upper.cpp.
References i, IPAB::info, IPAB::infoavl, IPAB::infosize, ipab, and NEED.
Referenced by addf90target(), addpstride(), addsafe(), and addsstride().
newintrinsic()
static int newintrinsic (int wantstype) static
Definition at line 1920 of file upper.cpp.
References errors, first, getnamelen(), HASH_ID, STB::hashtb, line, name, pos, sptr, stb, and SYMNAME.
Referenced by read_symbol().
newsymbol()
static SPTR newsymbol (void) static
Definition at line 1906 of file upper.cpp.
References ADDSYM, getnamelen(), HASH_ID, line, NOSYM, pos, putsname(), and sptr.
Referenced by get_or_create_symbol(), and read_symbol().
pop()
static int * pop (void) static
Definition at line 4541 of file upper.cpp.
References ilmlinenum, stack, and stack_top.
Referenced by dataEnddo(), and dumpsubinfo().
push()
static void push (int * value) static
Definition at line 4525 of file upper.cpp.
References NEED, NEW, stack, stack_size, stack_top, and value().
Referenced by dataDo().
push_typestack()
static void push_typestack (void) static
Definition at line 4553 of file upper.cpp.
References NEED, NEW, ts, tsl, and tssize.
Referenced by read_init().
put_prefix()
static void put_prefix (FILE * dfile, char * str, int cnt) static
Definition at line 5373 of file upper.cpp.
References cnt, dfile, i, and str.
Referenced by dmp_const().
read_CCFF()
static int read_CCFF (void) static
Definition at line 5245 of file upper.cpp.
References checkname(), endilmfile, errors, getname(), getval(), ilmlinenum, line, lineno, pos, read_line(), save_ccff_arg(), save_ccff_msg(), and save_ccff_text().
Referenced by upper().
read_contained()
static void read_contained (void) static
Definition at line 5335 of file upper.cpp.
References checkname(), errors, gbl, getnamelen(), HASH_ID, STB::hashtb, ilmlinenum, line, NOSYM, pos, sptr, stb, and SYMNAME.
Referenced by upper().
read_datatype()
static void read_datatype (void) static
Definition at line 1619 of file upper.cpp.
References AD_DPTR, AD_LWBD, AD_MLPYR, AD_NUMDIM, AD_NUMELM, AD_SCHECK, AD_UPBD, AD_ZBASE, datatypexref, dt, DT_CMPLX, DT_DBLE, DT_DCMPLX, DT_INT, DT_LOG, DT_REAL, DTySetAlgTy, DTySetProcTy, get_array_dtype(), get_type(), getDtypeVal, getpair(), getSptrVal, getTYKind, getval(), i, ISZ_T, lower(), ndim, NOSYM, size, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, and upper().
Referenced by upper().
read_Entry()
static void read_Entry (void) static
Definition at line 5315 of file upper.cpp.
References gbl, getSptrVal, NOSYM, sptr, and symbolxref.
Referenced by upper().
read_fileentries()
static void read_fileentries (void) static
Definition at line 5182 of file upper.cpp.
References addfile(), dirname, FIH_PARENT, filename, flags, getlval(), getnamelen(), getval(), level(), line, lineno, next, NULL, parent, and pos.
Referenced by upper().
read_global()
static void read_global (void) static
Definition at line 5231 of file upper.cpp.
References getval(), NOSYM, sptr, and symbolxref.
Referenced by upper().
read_ilm()
static void read_ilm (void) static
Definition at line 4268 of file upper.cpp.
References ad1ilm(), chdtype, chilm, chline, chnum, chsym, errors, gbl, getilm(), getoperand(), getoperation(), i, ILMB::ilmavl, ilmb, ilmlinenum, ilmxref, ilmxrefsize, info, line, name, NEED, NME_NULL, numoperands, operand, origilmavl, pargs, pdtype, pilm, pilms, pline, pnum, pnums, pos, psym, psyms, skipwhitespace(), Trace, and wrilms().
Referenced by upper().
read_init()
static void read_init (void) static
Definition at line 4568 of file upper.cpp.
References a, alignment(), aux, buf, checkname(), cngcon(), datatypexref, DDTG, DINIT_FUNCCOUNT, DINIT_LABEL, DINIT_LOC, dinit_put(), DINIT_REPEAT, dt, DT_ISINT, DT_ISLOG, DTY, DTyAlgTyMember, DTYG, typestack::dtype, DTySeqTyElement, AUX::dvl_avl, AUX::dvl_base, DVL_CONVAL, AUX::dvl_size, DVL_SPTR, errors, flg, gbl, getDtypeVal, getstring(), getval(), ilmlinenum, line, typestack::member, NEED, offset, FLG::opt, pos, push_typestack(), size_of(), skipwhitespace(), sptr, SPTR_NULL, sym_is_refd(), symbolxref, ts, tsl, TY_CHAR, TY_HOLL, TY_NCHAR, and val.
Referenced by upper().
read_ipainfo()
static void read_ipainfo (void) static
Definition at line 3414 of file upper.cpp.
References addf90target(), addpstride(), addsafe(), addsstride(), func, getIPAType, getlval(), getval(), INFO_ALLCALLSAFE, INFO_CALLSAFE, INFO_FGDYNTARGET, INFO_FLDYNTARGET, INFO_FOSTARGET, INFO_FOTARGET, INFO_FSTARGET, INFO_FUNKTARGET, INFO_GTARGET, INFO_LTARGET, INFO_OGTARGET, INFO_OTARGET, INFO_SAFE, sptr, stride, symbolxref, and targettype.
Referenced by upper().
read_label()
static void read_label (void) static
Definition at line 4445 of file upper.cpp.
References SWEL::clabel, errors, first, getbit(), getlabelnum(), getSptrVal, getswel(), getval(), ilmlinenum, label, SWEL::next, switch_base, symbolxref, SWEL::val, and value().
Referenced by upper().
read_line()
static int read_line (void) static
Definition at line 1178 of file upper.cpp.
References gbl, i, ilmlinenum, line, linelen, malloc(), pos, and STB_UPPER.
Referenced by read_CCFF(), stb_upper_init(), upper(), and upper_init().
read_overlap()
static void read_overlap (void) static
Definition at line 3308 of file upper.cpp.
References SOC::avail, SOC::base, count, getnum(), getval(), i, n, NEED, NEW, SOC::size, soc, SOC_NEXT, SOC_SPTR, sptr, and symbolxref.
Referenced by upper().
read_program()
static void read_program (void) static
Definition at line 3336 of file upper.cpp.
References checkname(), errors, flg, gbl, getRUType, ilmlinenum, line, pos, FLG::recursive, RU_PROG, and FLG::smp.
Referenced by upper().
read_symbol()
static void read_symbol (void) static
Definition at line 2002 of file upper.cpp.
References ACONOFFP, AD_DPTR, AD_NUMDIM, AD_SDSC, add_llvm_uplevel_symbol(), agotomax, agotosz, agototab, aux, c, cfuncflags, CMEMLP, common, CONVAL2P, count, cref, cudaemu, cudaflags, CUDAP, datatypecount, datatypexref, FLG::debug, declref(), DLLP, AUX::dpdsc_avl, AUX::dpdsc_base, AUX::dpdsc_size, dt, DT_CMPLX, DT_INT, DT_LOG, DT_REAL, DTY, DTySetFst, end, ENDLINEP, ERR_Fatal, errors, fix_private_sym(), flg, func, FUNCLINEP, gbl, get_array_dtype(), get_or_create_symbol(), getbit(), getcon(), getDtypeVal, gethex(), gethexchar(), getnamelen(), getnum(), getSCKind, getSptrVal, getstring(), getsym(), getSymType, getval(), GSAMEG, GSAMEP, i, FLG::i4, ilmlinenum, init(), init_list_count, interr(), ISZ_T, line, linelen, linenum, llmp_add_shared_var(), llmp_create_uplevel_bykey(), llmp_get_next_key(), local_sname(), m, mscall, STB::n_base, name, NEED, NEW, newintrinsic(), newsymbol(), SEM::nml, nml, AUX::nml_avl, AUX::nml_base, NML_LINENO, NML_NEXT, AUX::nml_size, NML_SPTR, nomixedstrlen, NOSYM, ORIGDUMMYP, parent, LLUplevel::parent, passbyflags, PDALN_EXPLICIT_0, PDALNP, plist(), pointer, pos, FLG::recursive, recursive, RU_BDATA, s, save_modvar_alias(), sem, size, sptr, SPTR_NULL, startline, stb, STB_UPPER, strlen(), symbolcount, symbolxref, AUX::symi_avl, AUX::symi_base, SYMI_NEXT, AUX::symi_size, SYMI_SPTR, SYMNAME, task, Trace, TY_BINT, TY_BLOG, TY_CHAR, TY_CMPLX, TY_DBLE, TY_DCMPLX, TY_DWORD, TY_HOLL, TY_INT, TY_INT8, TY_ISWORD, TY_LOG, TY_LOG8, TY_NCHAR, TY_QUAD, TY_REAL, TY_SINT, TY_SLOG, TY_WORD, val, WINNT_CALL, WINNT_CREF, WINNT_NOMIXEDSTRLEN, and XBIT.
Referenced by upper().
restore_saved_syminfo()
static void restore_saved_syminfo (int firstinternal) static
Definition at line 827 of file upper.cpp.
References upper_syminfo::address, create_thread_private_vector(), errors, gbl, gethost_dumlen(), IS_THREAD_TP, ISZ_PF, ISZ_T, NOSYM, upper_syminfo::ref, s, upper_syminfo::save, saved_symbolcount, saved_symbolxref, saved_syminfo, saved_syminfocount, upper_syminfo::sc, symbolcount, symbolxref, SYMNAME, Trace, and XBIT.
Referenced by upper().
save_modvar_alias()
static void save_modvar_alias (SPTR sptr, char * alias_name) static
Given a alias name of a mod var sptr, create a new alias_syminfo node and add it to the linked list for later lookup.
Definition at line 6504 of file upper.cpp.
References alias_syminfo::alias, lookup_modvar_alias(), modvar_alias_list, NEW, alias_syminfo::next, sptr, and alias_syminfo::sptr.
Referenced by read_symbol().
skipwhitespace()
static void skipwhitespace (void) static
Definition at line 1264 of file upper.cpp.
References line, and pos.
Referenced by dataConstant(), getbit(), gethex(), getkeyword(), getlval(), getnamelen(), getnum(), getoperand(), getoperation(), getpair(), getval(), read_ilm(), and read_init().
stb_upper_init()
void stb_upper_init (void)
...
Definition at line 6432 of file upper.cpp.
References base, end, filename, getlval(), getnamelen(), getval(), level(), line, name, offset, pos, read_line(), and size.
Referenced by main().
TraceOutput()
static void TraceOutput (const char * fmt, ...) static
Definition at line 281 of file upper.cpp.
References DBGBIT, and gbl.
upper()
void upper (int stb_processing)
Entry point for reading in ILM file.
...
Size of private array allocated by frontend - the frontend will allocate space for a descriptor and its pointer & offset variables since there is an assumed sequence of allocation.
Definition at line 428 of file upper.cpp.
References agotosz, aux, Begindata(), build_agoto(), BZERO, checkname(), checkversion(), create_static_base(), data_pop_const(), dataConstant(), dataDo(), dataEnddo(), dataReference(), dataStructure(), datatypecount, datatypexref, dataVariable(), DBGBIT, DDTG, direct_import(), dmp_dtype(), do_dinit(), AUX::dpdsc_base, STB::dt, e, endilmfile, ERR_Fatal, errors, first, STB::firstusym, fix_datatype(), fix_symbol(), fixup_llvm_uplevel_symbol(), FREE, freearea(), gbl, getdumlen(), getSptrVal, getval(), i, ilmlinenum, ilmxref, ilmxrefsize, init_upper(), interr(), ISZ_T, line, llvm_stb_processing, NEW, NOSYM, NULL, olddatatypecount, oldsymbolcount, origilmavl, read_CCFF(), read_contained(), read_datatype(), read_Entry(), read_fileentries(), read_global(), read_ilm(), read_init(), read_ipainfo(), read_label(), read_line(), read_overlap(), read_program(), read_symbol(), restore_saved_syminfo(), saved_symbolcount, saved_symbolxref, saved_syminfo, saved_syminfocount, saved_tpcount, saved_tpinfo, set_private_size(), size, SPTR_NULL, stack, stb, STB_UPPER, symbolcount, symbolxref, symdmp(), ts, Writedata(), and XBIT.
Referenced by build_array_list(), check_loop_bound(), ENTF90(), ENTFTN(), exp_smp(), fix_datatype(), ll_make_kmpc_dispatch_init(), ll_make_kmpc_dispatch_next(), ll_make_kmpc_dist_dispatch_init(), ll_make_kmpc_dist_for_static_init(), ll_make_kmpc_for_static_init(), lower_check_subscript(), process_input(), process_stb_file(), and read_datatype().
upper_assign_addresses()
void upper_assign_addresses (void)
For outer routines that contain inner routines, make sure all variables get an address, even if never used in this routine, in case they are used by the contained routines.
...
Definition at line 797 of file upper.cpp.
References STB::firstusym, gbl, hostsym_is_refd(), sptr, and stb.
Referenced by process_input(), and process_stb_file().
upper_init()
void upper_init (void)
...
Definition at line 1145 of file upper.cpp.
References base, end, filename, getlval(), getnamelen(), getval(), level(), line, name, offset, pos, read_line(), and size.
Referenced by main().
upper_save_syminfo()
void upper_save_syminfo (void)
Save information about symbols for this outer routine to restore inside other inner routines.
...
Definition at line 1033 of file upper.cpp.
References upper_syminfo::address, BZERO, upper_syminfo::clen_address, upper_syminfo::clen_memarg, cnt, DDTG, gbl, upper_syminfo::memarg, NEW, NOSYM, upper_syminfo::ref, s, upper_syminfo::save, saved_symbolcount, saved_symbolxref, saved_syminfo, saved_syminfocount, saved_tpcount, saved_tpinfo, upper_syminfo::sc, sptr, and tpcount.
Referenced by process_input(), and process_stb_file().
Writedata()
static void Writedata (void) static
Definition at line 4887 of file upper.cpp.
References dataict, dataivl, and dinit().
Referenced by upper().
Variable Documentation
agotomax
int agotomax static
Definition at line 186 of file upper.cpp.
Referenced by build_agoto(), and read_symbol().
agotosz
int agotosz = 0 static
Definition at line 185 of file upper.cpp.
Referenced by build_agoto(), read_symbol(), and upper().
agototab
int* agototab static
Definition at line 184 of file upper.cpp.
Referenced by build_agoto(), and read_symbol().
cfuncflags
int cfuncflags = 1 static
Definition at line 47 of file upper.cpp.
Referenced by checkversion(), and read_symbol().
cudaemu
int cudaemu = 0 static
Definition at line 49 of file upper.cpp.
Referenced by cuda_emu_end(), cuda_emu_start(), lower_symbol(), and read_symbol().
cudaflags
int cudaflags = 1 static
Definition at line 48 of file upper.cpp.
Referenced by checkversion(), and read_symbol().
struct { ... } cusv
Referenced by cuda_emu_end(), and cuda_emu_start().
dataict
CONST* dataict static
Definition at line 4473 of file upper.cpp.
Referenced by Begindata(), data_add_const(), data_pop_const(), data_push_const(), and Writedata().
dataivl
VAR* dataivl static
Definition at line 4471 of file upper.cpp.
Referenced by Begindata(), data_add_ivl(), and Writedata().
datatypecount
int datatypecount = 0 static
Definition at line 179 of file upper.cpp.
Referenced by fix_datatype(), read_symbol(), and upper().
Datatypes
const namelist Datatypes[] static
Initial value:
= {
  { "Array",     "A",   TY_ARRAY },  { "Complex8",   "C8", TY_CMPLX },
  { "Complex16", "C16", TY_DCMPLX },
  { "Complex32", "C32", TY_QCMPLX }, { "Derived",    "D",  TY_STRUCT },
  { "Hollerith", "H",   TY_HOLL },   { "Integer1",   "I1", TY_BINT },
  { "Integer2",  "I2",  TY_SINT },   { "Integer4",   "I4", TY_INT },
  { "Integer8",  "I8",  TY_INT8 },   { "Logical1",   "L1", TY_BLOG },
  { "Logical2",  "L2",  TY_SLOG },   { "Logical4",   "L4", TY_LOG },
  { "Logical8",  "L8",  TY_LOG8 },   { "Numeric",    "N",  TY_NUMERIC },
  { "Pointer",   "P",   TY_PTR },    { "proc",       "p",  TY_PROC },
  { "Real2",     "R2",  TY_HALF },
  { "Real4",     "R4",  TY_REAL },   { "Real8",      "R8", TY_DBLE },
  { "Real16",    "R16", TY_QUAD },   { "Struct",     "S",  TY_STRUCT },
  { "Word4",     "W4",  TY_WORD },   { "Word8",      "W8", TY_DWORD },
  { "Union",     "U",   TY_UNION },  { "any",        "a",  TY_ANY },
  { "character", "c",   TY_CHAR },   { "kcharacter", "k",  TY_NCHAR },
  { "none",      "n",   TY_NONE },   { NULL,         NULL, -1 },
}
Definition at line 128 of file upper.cpp.
datatypexref
DTYPE* datatypexref static
Definition at line 182 of file upper.cpp.
Referenced by fix_datatype(), getoperand(), read_datatype(), read_init(), read_symbol(), and upper().
do_level
int do_level = 0 static
Definition at line 43 of file upper.cpp.
Referenced by dataConstant().
endilmfile
int endilmfile static
Definition at line 36 of file upper.cpp.
Referenced by getbit(), gethex(), getilm(), getkeyword(), getlabelnum(), getlval(), getnamelen(), getnum(), getoperand(), getoperation(), getpair(), getval(), read_CCFF(), and upper().
errors
int errors static
Definition at line 333 of file upper.cpp.
Referenced by dataConstant(), dataDo(), dataEnddo(), dataReference(), dataStructure(), dataVariable(), fix_datatype(), getbit(), gethex(), getilm(), getkeyword(), getlabelnum(), getlval(), getnamelen(), getnum(), getoperand(), getoperation(), getpair(), getval(), init_upper(), newintrinsic(), read_CCFF(), read_contained(), read_ilm(), read_init(), read_label(), read_program(), read_symbol(), restore_saved_syminfo(), and upper().
ilmlinenum
int ilmlinenum = 0 static
Definition at line 37 of file upper.cpp.
Referenced by dataConstant(), dataDo(), dataEnddo(), dataReference(), dataStructure(), dataVariable(), getbit(), getilm(), getkeyword(), getlabelnum(), getlval(), getoperand(), getoperation(), getpair(), getval(), pop(), read_CCFF(), read_contained(), read_ilm(), read_init(), read_label(), read_line(), read_program(), read_symbol(), and upper().
ilmxref
int* ilmxref static
Definition at line 351 of file upper.cpp.
Referenced by getoperand(), read_ilm(), and upper().
ilmxrefsize
int ilmxrefsize static
Definition at line 352 of file upper.cpp.
Referenced by read_ilm(), and upper().
in_array_ctor
int in_array_ctor = 0 static
Definition at line 44 of file upper.cpp.
Referenced by dataConstant().
init_list_count
int init_list_count extern
Definition at line 62 of file dinit.cpp.
Referenced by dataConstant(), do_dinit(), read_symbol(), and save_init().
IPA_Func_Propagated
int IPA_Func_Propagated = 0
Definition at line 272 of file upper.cpp.
Referenced by IPA_func_almostpure(), and IPA_func_pure().
IPA_Pointer_Strides_Propagated
int IPA_Pointer_Strides_Propagated = 0
Definition at line 273 of file upper.cpp.
Referenced by IPA_pstride(), and IPA_sstride().
IPA_Pointer_Targets_Disambiguated
int IPA_Pointer_Targets_Disambiguated = 0
Definition at line 269 of file upper.cpp.
Referenced by IPA_nme_conflict().
IPA_Range_Propagated
int IPA_Range_Propagated = 0
Definition at line 271 of file upper.cpp.
Referenced by IPA_range().
IPA_Safe_Globals_Confirmed
int IPA_Safe_Globals_Confirmed = 0
Definition at line 270 of file upper.cpp.
Referenced by IPA_allcall_safe(), IPA_call_safe(), IPA_noaddr(), and IPA_safe().
ipab
IPAB ipab static
Definition at line 332 of file upper.cpp.
Referenced by findindex(), init_upper(), newindex(), and newinfo().
IPAtypes
const namelist IPAtypes[] static
Initial value:
= {
  { "pstride",  "p",  1 }, { "sstride",     "s",   2 }, { "Target", "T",  3 },
  { "target",   "t",  4 }, { "allcallsafe", "a",   5 }, { "safe",   "f",  6 },
  { "callsafe", "c",  7 }, { NULL,          NULL, -1 },
}
Definition at line 121 of file upper.cpp.
lastict
CONST* lastict static
Definition at line 4474 of file upper.cpp.
Referenced by Begindata(), data_add_const(), data_pop_const(), data_push_const(), and dataConstant().
lastivl
VAR* lastivl static
Definition at line 4472 of file upper.cpp.
Referenced by Begindata(), and data_add_ivl().
line
char* line = NULL static
Definition at line 39 of file upper.cpp.
Referenced by __fort_trac_function_entry(), checkbitname(), checkname(), checkversion(), collectIncludePaths(), condec(), contIndex(), dataConstant(), dataDo(), dataEnddo(), dataReference(), dataStructure(), dataVariable(), doline(), ENTFTN(), error(), find_lpprg(), fndnul(), gentab(), genthd(), get_src_line(), getbit(), gethex(), getilm(), getkeyword(), getlabelnum(), getlval(), getname(), getnamelen(), getnum(), getoperand(), getoperation(), getpair(), getval(), hlddmp(), init_upper(), ipa_restore_dtb(), lldbg_create_aggregate_type_mdnode(), lldbg_create_array_type_mdnode(), lldbg_create_basic_type_mdnode(), lldbg_create_block_mdnode(), lldbg_create_ftn_array_type_mdnode(), lldbg_create_global_variable_mdnode(), lldbg_create_local_variable_mdnode(), lldbg_create_location_mdnode(), lldbg_create_member_mdnode(), lldbg_create_pointer_type_mdnode(), lldbg_create_structure_type_mdnode(), lldbg_create_subprogram_mdnode(), lldbg_create_union_type_mdnode(), lz(), match(), movstr(), newintrinsic(), newsymbol(), numLeadingSpaces(), open_pragma(), output(), pntbas(), pntset(), pr_line(), prntgm(), push_pragma(), put_astfil(), put_err(), putsem(), read_CCFF(), read_contained(), read_fileentries(), read_ilm(), read_init(), read_line(), read_program(), read_symbol(), ILMTPApp::run(), N2Rst::run(), skipwhitespace(), stb_upper_init(), symdentry(), tablea(), tableu(), tokmac(), trimContIdx(), upper(), upper_init(), verify_failure(), xref(), and zprntk().
linelen
int linelen = 0 static
Definition at line 40 of file upper.cpp.
Referenced by init_upper(), read_line(), and read_symbol().
llvm_stb_processing
int llvm_stb_processing = 0 static
Definition at line 52 of file upper.cpp.
Referenced by upper().
modvar_alias_list
alias_syminfo* modvar_alias_list static
Definition at line 309 of file upper.cpp.
Referenced by free_modvar_alias_list(), init_upper(), lookup_modvar_alias(), and save_modvar_alias().
olddatatypecount
int olddatatypecount = 0 static
Definition at line 180 of file upper.cpp.
Referenced by fix_datatype(), and upper().
oldsymbolcount
int oldsymbolcount = 0 static
Definition at line 180 of file upper.cpp.
Referenced by fix_datatype(), fix_symbol(), get_symbol_start(), and upper().
oprnd_cnt
int oprnd_cnt = 0 static
Definition at line 45 of file upper.cpp.
Referenced by dataConstant().
origilmavl
int origilmavl static
Definition at line 352 of file upper.cpp.
Referenced by getoperand(), read_ilm(), and upper().
outerict
CONST* outerict static
Definition at line 4475 of file upper.cpp.
Referenced by Begindata(), data_pop_const(), and data_push_const().
passbyflags
int passbyflags = 1 static
Definition at line 46 of file upper.cpp.
Referenced by checkversion(), and read_symbol().
pos
int pos static
Definition at line 41 of file upper.cpp.
Referenced by checkbitname(), checkname(), dataConstant(), getbit(), gethex(), getilm(), getkeyword(), getlabelnum(), getlval(), getname(), getnamelen(), getnum(), getoperand(), getoperation(), getpair(), getval(), match(), newintrinsic(), newsymbol(), read_CCFF(), read_contained(), read_fileentries(), read_ilm(), read_init(), read_line(), read_program(), read_symbol(), skipwhitespace(), stb_upper_init(), and upper_init().
profile
int profile
Definition at line 6351 of file upper.cpp.
recursive
bool recursive
Definition at line 6350 of file upper.cpp.
Referenced by read_symbol().
saved_symbolcount
int saved_symbolcount = 0 static
Definition at line 344 of file upper.cpp.
Referenced by restore_saved_syminfo(), upper(), and upper_save_syminfo().
saved_symbolxref
SPTR* saved_symbolxref static
Definition at line 343 of file upper.cpp.
Referenced by restore_saved_syminfo(), upper(), and upper_save_syminfo().
saved_syminfo
upper_syminfo* saved_syminfo static
Definition at line 345 of file upper.cpp.
Referenced by restore_saved_syminfo(), upper(), and upper_save_syminfo().
saved_syminfocount
int saved_syminfocount = 0 static
Definition at line 346 of file upper.cpp.
Referenced by restore_saved_syminfo(), upper(), and upper_save_syminfo().
saved_tpcount
int saved_tpcount = 0 static
Definition at line 348 of file upper.cpp.
Referenced by create_thread_private_vector(), upper(), and upper_save_syminfo().
saved_tpinfo
upper_syminfo* saved_tpinfo static
Definition at line 347 of file upper.cpp.
Referenced by create_thread_private_vector(), upper(), and upper_save_syminfo().
smp
bool smp
Definition at line 6349 of file upper.cpp.
stack
int** stack static
Definition at line 337 of file upper.cpp.
Referenced by init_upper(), pop(), push(), and upper().
stack_size
int stack_size static
Definition at line 336 of file upper.cpp.
Referenced by init_upper(), and push().
stack_top
int stack_top static
Definition at line 336 of file upper.cpp.
Referenced by init_upper(), pop(), and push().
Subprogramtypes
const namelist Subprogramtypes[] static
Initial value:
= {
  { "Blockdata", "B",  RU_BDATA }, { "Function",   "F",  RU_FUNC },
  { "Program",   "P",  RU_PROG },  { "Subroutine", "S",  RU_SUBR },
  { NULL,        NULL, -1 },
}
Definition at line 172 of file upper.cpp.
Symbolclasses
const namelist Symbolclasses[] static
Initial value:
= {
  { "Based",  "B",  SC_BASED },  { "Common",  "C",  SC_CMBLK },
  { "Dummy",  "D",  SC_DUMMY },  { "Extern",  "E",  SC_EXTERN },
  { "Local",  "L",  SC_LOCAL },  { "Private", "P",  SC_PRIVATE },
  { "Static", "S",  SC_STATIC }, { "none",    "n",  SC_NONE },
  { NULL,     NULL, -1 },
}
Definition at line 163 of file upper.cpp.
symbolcount
int symbolcount = 0 static
Definition at line 179 of file upper.cpp.
Referenced by read_symbol(), restore_saved_syminfo(), and upper().
Symboltypes
const namelist Symboltypes[] static
Initial value:
= {
  { "Array",     "A",  ST_ARRAY },   { "Block",     "B",  ST_BLOCK },
  { "Common",    "C",  ST_CMBLK },   { "Derived",   "D",  ST_STRUCT },
  { "Entry",     "E",  ST_ENTRY },   { "Generic",   "G",  ST_GENERIC },
  { "Intrinsic", "I",  ST_INTRIN },  { "Known",     "K",  ST_PD },
  { "Label",     "L",  ST_LABEL },   { "Member",    "M",  ST_MEMBER },
  { "Namelist",  "N",  ST_NML },     { "Procedure", "P",  ST_PROC },
  { "Struct",    "S",  ST_STRUCT },  { "Tag",       "T",  ST_STAG },
  { "Union",     "U",  ST_UNION },   { "Variable",  "V",  ST_VAR },
  { "constant",  "c",  ST_CONST },   { "dpname",    "d",  ST_DPNAME },
  { "list",      "l",  ST_PLIST },
  { "module",    "m",  -99 },        { "parameter", "p",  ST_PARAM },
  { "typedef",   "t",  ST_TYPEDEF }, { NULL,        NULL, -1 },
}
Definition at line 148 of file upper.cpp.
symbolxref
SPTR* symbolxref static
Definition at line 181 of file upper.cpp.
Referenced by fix_datatype(), fix_symbol(), get_or_create_symbol(), getoperand(), llvm_get_uplevel_newsptr(), read_Entry(), read_global(), read_init(), read_ipainfo(), read_label(), read_overlap(), read_symbol(), restore_saved_syminfo(), and upper().
threadprivate_dtype
DTYPE threadprivate_dtype static
Definition at line 350 of file upper.cpp.
Referenced by create_thread_private_vector(), and fix_symbol().
tpcount
int tpcount static
Definition at line 349 of file upper.cpp.
Referenced by create_thread_private_vector(), fix_symbol(), and upper_save_syminfo().
ts
typestack* ts static
Definition at line 339 of file upper.cpp.
Referenced by __attribute__(), cyclic_setup(), gen_arg_operand(), GENERICNAME(), GENERICNAMEMASK(), if(), init_upper(), make_stmt(), push_typestack(), read_init(), and upper().
tsl
int tsl = -1 static
Definition at line 340 of file upper.cpp.
Referenced by init_upper(), push_typestack(), and read_init().
tssize
int tssize = 0 static
Definition at line 341 of file upper.cpp.
Referenced by init_upper(), and push_typestack().
x121
int x121
Definition at line 6353 of file upper.cpp.
x123
int x123
Definition at line 6354 of file upper.cpp.
x5
int x5
Definition at line 6352 of file upper.cpp.