flang: util.c File Reference
util.c File Reference
#include <stdioInterf.h>
#include "fioMacros.h"
Functions
int I8() __fort_varying_int (void *b, __INT_T *size)
int I8() __fort_varying_log (void *b, __INT_T *size)
int I8() __fort_fetch_int (void *b, F90_Desc *d)
void I8() __fort_store_int (void *b, F90_Desc *d, int val)
int I8() __fort_fetch_log (void *b, F90_Desc *d)
void I8() __fort_store_log (void *b, F90_Desc *d, int val)
int I8() __fort_fetch_int_element (void *b, F90_Desc *d, int i)
void I8() __fort_store_int_element (void *b, F90_Desc *d, int i, int val)
void I8() __fort_fetch_int_vector (void *b, F90_Desc *d, int *vec, int veclen)
void I8() __fort_store_int_vector (void *b, F90_Desc *d, int *vec, int veclen)
void __fort_ftnstrcpy (char *dst, int len, char *src)
Function Documentation
__fort_fetch_int()
int I8() __fort_fetch_int (void * b, F90_Desc * d)
Definition at line 54 of file util.c.
References __DESC, __fort_abort(), __INT1, __INT2, __INT4, __INT8, __OFF_TEMPLATE, Abs, b, d, DIST_SCOFF_G, F90_FLAGS_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, and kind.
Referenced by __fort_kred_arraylk(), __fort_red_array(), __fort_red_arraylk(), __INT8_T(), __INT_T(), and ENTFTN().
__fort_fetch_int_element()
int I8() __fort_fetch_int_element (void * b, F90_Desc * d, int i)
Definition at line 185 of file util.c.
References __fort_abort(), __fort_get_scalar(), __INT1, __INT2, __INT4, __INT8, b, d, F90_DIM_LBOUND_G, F90_KIND_G, F90_RANK_G, i, I8, idx, tmp, and val.
__fort_fetch_int_vector()
void I8() __fort_fetch_int_vector (void * b, F90_Desc * d, int * vec, int veclen)
Definition at line 249 of file util.c.
References __fort_abort(), __fort_get_scalar(), __INT1, __INT2, __INT4, __INT8, b, d, F90_DIM_LBOUND_G, F90_KIND_G, F90_RANK_G, i, I8, tmp, and vec.
Referenced by ENTFTN().
__fort_fetch_log()
int I8() __fort_fetch_log (void * b, F90_Desc * d)
Definition at line 120 of file util.c.
References __DESC, __fort_abort(), __LOG1, __LOG2, __LOG4, __LOG8, __OFF_TEMPLATE, Abs, b, d, DIST_SCOFF_G, F90_FLAGS_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_MASK_LOG1, GET_DIST_MASK_LOG2, GET_DIST_MASK_LOG4, GET_DIST_MASK_LOG8, and kind.
Referenced by __fort_gathscat(), __fort_kred_arraylk(), __fort_kred_scalarlk(), __fort_red_array(), __fort_red_arraylk(), __fort_red_scalar(), and __fort_red_scalarlk().
__fort_ftnstrcpy()
void __fort_ftnstrcpy (char * dst, int len, char * src)
Definition at line 314 of file util.c.
References end, len, and src.
__fort_store_int()
void I8() __fort_store_int (void * b, F90_Desc * d, int val)
Definition at line 85 of file util.c.
References __DESC, __fort_abort(), __INT1, __INT2, __INT4, __INT8, __OFF_TEMPLATE, Abs, b, d, DIST_SCOFF_G, F90_FLAGS_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, kind, and val.
__fort_store_int_element()
void I8() __fort_store_int_element (void * b, F90_Desc * d, int i, int val)
Definition at line 217 of file util.c.
References __fort_abort(), __fort_local_address(), __INT1, __INT2, __INT4, __INT8, b, d, F90_DIM_LBOUND_G, F90_KIND_G, F90_RANK_G, i, I8, idx, NULL, and val.
Referenced by ENTFTN().
__fort_store_int_vector()
void I8() __fort_store_int_vector (void * b, F90_Desc * d, int * vec, int veclen)
Definition at line 280 of file util.c.
References __fort_abort(), __fort_local_address(), __INT1, __INT2, __INT4, __INT8, b, d, F90_DIM_LBOUND_G, F90_KIND_G, F90_RANK_G, i, I8, NULL, and vec.
__fort_store_log()
void I8() __fort_store_log (void * b, F90_Desc * d, int val)
Definition at line 151 of file util.c.
References __DESC, __fort_abort(), __LOG1, __LOG2, __LOG4, __LOG8, __OFF_TEMPLATE, Abs, b, d, DIST_SCOFF_G, F90_FLAGS_G, F90_KIND_G, F90_LEN_G, F90_RANK_G, F90_TAG_G, GET_DIST_TRUE_LOG1, GET_DIST_TRUE_LOG2, GET_DIST_TRUE_LOG4, GET_DIST_TRUE_LOG8, kind, and val.
__fort_varying_int()
int I8() __fort_varying_int (void * b, __INT_T * size)
Definition at line 15 of file util.c.
References __fort_abort(), b, and size.
Referenced by __CLEN_T(), __INT8_T(), __INT_T(), ENTF90(), and ENTFTN().
__fort_varying_log()
int I8() __fort_varying_log (void * b, __INT_T * size)
Definition at line 34 of file util.c.
References __fort_abort(), b, GET_DIST_MASK_LOG1, GET_DIST_MASK_LOG2, GET_DIST_MASK_LOG4, GET_DIST_MASK_LOG8, and size.
Referenced by __INT1_T(), __INT2_T(), __INT4_T(), __INT8_T(), __INT_T(), __LOG1_T(), __LOG2_T(), __LOG4_T(), __LOG8_T(), __REAL16_T(), __REAL4_T(), __REAL8_T(), ENTF90(), and ENTFTN().