flang: utils.h File Reference
utils.h File Reference
Various definitions for the utility programs, ilmpt, machar, symutil, and symini.
#include "universal.h"
Classes
struct LT
Macros
#define MAXLINE 300
#define FUNCTION
#define SUBROUTINE void
#define LOOP while (1)
#define INT int
#define UINT unsigned int
#define UCHAR char
#define LT_EOF 0
#define LT_UNK -1
#define TRUE 1
#define FALSE 0
#define IN1 infile[0]
#define IN2 infile[1]
#define IN3 infile[2]
#define IN4 infile[3]
#define OUT1 outfile[0]
#define OUT2 outfile[1]
#define OUT3 outfile[2]
#define OUT4 outfile[3]
#define OUT5 outfile[4]
#define put_error put_err
Functions
void put_error (int sev, const char *txt)
void open_files (int argc, char **argv)
int get_line (FILE *funit, LT ltypes[])
void get_token (char out[], int *len)
Skip past blanks in lbuff beginning at currpos, and move into 'out' the token up to the next blank character.
int get_line1 (FILE *funit, LT ltypes[], FILE *outf)
Same as get_line except copies to outf.
void flush_line (FILE *outf)
void output_off (void)
Supress output going to output files.
void output_on (void)
Enable output going to output files.
void ili_op (void)
void init_ili (LT *elt)
int get_ili (char *ilin)
Variables
FILE * infile [10]
FILE * outfile [10]
Detailed Description
Various definitions for the utility programs, ilmpt, machar, symutil, and symini.
If compiled as C++ code this file provides a definition of the base class for various utility programs that generate documentation and header files for compilers in the build process.
Define the preprocessor symbol USE_OLD_C_UTILS before including this file if you need the old C interfaces.
The NroffInStream, NroffMap, and NroffTokenStream interfaces are always provided.
Definition in file utils.h.
Macro Definition Documentation
FALSE
#define FALSE 0
Definition at line 1470 of file utils.h.
FUNCTION
#define FUNCTION
Definition at line 1459 of file utils.h.
IN1
#define IN1 infile[0]
Definition at line 1480 of file utils.h.
IN2
#define IN2 infile[1]
Definition at line 1481 of file utils.h.
IN3
#define IN3 infile[2]
Definition at line 1482 of file utils.h.
IN4
#define IN4 infile[3]
Definition at line 1483 of file utils.h.
INT
#define INT int
Definition at line 1462 of file utils.h.
LOOP
#define LOOP while (1)
Definition at line 1461 of file utils.h.
LT_EOF
#define LT_EOF 0
Definition at line 1466 of file utils.h.
LT_UNK
#define LT_UNK -1
Definition at line 1467 of file utils.h.
MAXLINE
#define MAXLINE 300
Definition at line 1458 of file utils.h.
OUT1
#define OUT1 outfile[0]
Definition at line 1485 of file utils.h.
OUT2
#define OUT2 outfile[1]
Definition at line 1486 of file utils.h.
OUT3
#define OUT3 outfile[2]
Definition at line 1487 of file utils.h.
OUT4
#define OUT4 outfile[3]
Definition at line 1488 of file utils.h.
OUT5
#define OUT5 outfile[4]
Definition at line 1489 of file utils.h.
put_error
#define put_error put_err
Definition at line 1491 of file utils.h.
SUBROUTINE
#define SUBROUTINE void
Definition at line 1460 of file utils.h.
TRUE
#define TRUE 1
Definition at line 1469 of file utils.h.
UCHAR
#define UCHAR char
Definition at line 1464 of file utils.h.
UINT
#define UINT unsigned int
Definition at line 1463 of file utils.h.
Function Documentation
flush_line()
void flush_line (FILE * outf)
Definition at line 181 of file utils.cpp.
References lbuff.
Referenced by proc_sym().
get_ili()
int get_ili (char * ilin)
get_line()
int get_line (FILE * funit, LT ltypes[])
read input lines until one matching one of the line types in the 'ltypes' array is found. Return the corresponding integer line type id, or 0 for end of file. Set currpos to point immediately after first 3 chars of line.
Definition at line 193 of file utils.cpp.
References currfile, currpos, i, lbuff, lineno, LOOP, LT_EOF, ltypes, MAXLINE, NULL, and str.
Referenced by collectIncludePaths().
get_line1()
int get_line1 (FILE * funit, LT ltypes[], FILE * outf)
Same as get_line except copies to outf.
Definition at line 152 of file utils.cpp.
References currfile, currpos, i, lbuff, lineno, LOOP, LT_EOF, ltypes, MAXLINE, NULL, and str.
Referenced by proc_sym(), and write_ast().
get_token()
void get_token (char out[], int * len)
Skip past blanks in lbuff beginning at currpos, and move into 'out' the token up to the next blank character.
Currpos is left pointing to the first character (blank, NULL, or endline) following the token. One of the following values is returned in len:
len > 0 : number of characters in token.
len == 0 : no token remaining in lbuff.
len == -1: error occurred.
Definition at line 270 of file utils.cpp.
References c, currpos, i, lbuff, len, LOOP, and put_err().
Referenced by collectIncludePaths().
ili_op()
void ili_op (void)
init_ili()
void init_ili (LT * elt)
open_files()
void open_files (int argc, char ** argv)
output_off()
void output_off (void)
Supress output going to output files.
Definition at line 134 of file utils.cpp.
References i, null_file, outfile, and savefile.
output_on()
void output_on (void)
Enable output going to output files.
Definition at line 144 of file utils.cpp.
References i, outfile, and savefile.
put_error()
void put_error (int sev, const char * txt)
Referenced by addattr(), addfield(), findsym(), proc_sym(), and write_ast().
Variable Documentation
infile
FILE* infile[10] extern
Definition at line 29 of file utils.cpp.
Referenced by open_files().
outfile
FILE * outfile[10]
Definition at line 1478 of file utils.h.