flang: utils.c File Reference
utils.c File Reference
Utility functions for fortran i.o.
#include <errno.h>
#include "global.h"
#include "open_close.h"
#include "stdioInterf.h"
#include "fioMacros.h"
#include "async.h"
Macros
#define CHUNKSZ 100
#define ERR(code)
#define BFSZ 512L
#define SWAPB(p, b1, b2, tmp)
Functions
static int __fortio_trunc (FIO_FCB *, seekoffx_t)
void * __fortio_fiofcb_asyptr (FIO_FCB *f)
bool __fortio_fiofcb_asy_rw (FIO_FCB *f)
void __fortio_set_asy_rw (FIO_FCB *f, bool value)
bool __fortio_fiofcb_stdunit (FIO_FCB *f)
FILE * __fortio_fiofcb_fp (FIO_FCB *f)
short __fortio_fiofcb_form (FIO_FCB *f)
const char * __fortio_fiofcb_name (FIO_FCB *f)
void * __fortio_fiofcb_next (FIO_FCB *f)
FIO_FCB * __fortio_alloc_fcb (void)
void __fortio_free_fcb (FIO_FCB *p)
void __fortio_cleanup_fcb ()
FIO_FCB * __fortio_rwinit (int unit, int form, __INT_T *recptr, int optype)
FIO_FCB * __fortio_find_unit (int unit)
int __fortio_zeropad (FILE *fp, long len)
bool __fortio_eq_str (char *str, __CLEN_T len, const char *pattern)
void __fortio_swap_bytes (char *p, int type, long cnt)
Variables
static FIO_FCB * fcb_avail = NULL
static FIO_FCB * fcb_chunks
Detailed Description
Utility functions for fortran i.o.
Definition in file utils.c.
Macro Definition Documentation
BFSZ
#define BFSZ 512L
CHUNKSZ
#define CHUNKSZ 100
Definition at line 30 of file utils.c.
ERR
#define ERR (code)
Value:
  {                             \
    (void)__fortio_error(code); \
    return NULL;                \
  }
SWAPB
#define SWAPB (p, b1, b2, tmp)
Value:
  {                           \
    tmp = p[b1];              \
    p[b1] = p[b2];            \
    p[b2] = tmp;              \
  }
Definition at line 518 of file utils.c.
Function Documentation
__fortio_alloc_fcb()
FIO_FCB * __fortio_alloc_fcb (void)
Definition at line 89 of file utils.c.
References assert, CHUNKSZ, fcb_avail, fcb_chunks, FIO_TBL::fcbs, fioFcbTbls, i, malloc(), next, NULL, and p.
Referenced by __fortio_init(), and __fortio_open().
__fortio_cleanup_fcb()
void __fortio_cleanup_fcb (void)
Definition at line 146 of file utils.c.
References fcb_avail, fcb_chunks, NULL, and p.
Referenced by __fortio_cleanup().
__fortio_eq_str()
bool __fortio_eq_str (char * str, __CLEN_T len, const char * pattern)
Definition at line 474 of file utils.c.
References FALSE, len, NULL, str, and TRUE.
Referenced by __INT_T(), _f90io_close(), _selected_char_kind(), ENTCRF90IO(), ENTF90IO(), f90_open(), fr_init(), and fw_init().
__fortio_find_unit()
FIO_FCB * __fortio_find_unit (int unit)
Definition at line 434 of file utils.c.
References FIO_TBL::fcbs, fioFcbTbls, NULL, and p.
Referenced by __fortio_eoferr(), __fortio_eorerr(), __fortio_error(), __fortio_open(), __fortio_rwinit(), _f90io_backspace(), _f90io_close(), _f90io_rewind(), ENTF90IO(), and inquire().
__fortio_fiofcb_asy_rw()
bool __fortio_fiofcb_asy_rw (FIO_FCB * f)
Definition at line 47 of file utils.c.
References fcb::asy_rw, and f.
__fortio_fiofcb_asyptr()
void * __fortio_fiofcb_asyptr (FIO_FCB * f)
Definition at line 41 of file utils.c.
References fcb::asyptr, and f.
__fortio_fiofcb_form()
short __fortio_fiofcb_form (FIO_FCB * f)
Definition at line 71 of file utils.c.
References f, and fcb::form.
__fortio_fiofcb_fp()
FILE * __fortio_fiofcb_fp (FIO_FCB * f)
Definition at line 65 of file utils.c.
References f, and fcb::fp.
__fortio_fiofcb_name()
const char * __fortio_fiofcb_name (FIO_FCB * f)
Definition at line 77 of file utils.c.
References f, and fcb::name.
__fortio_fiofcb_next()
void * __fortio_fiofcb_next (FIO_FCB * f)
Definition at line 83 of file utils.c.
References f, and fcb::next.
__fortio_fiofcb_stdunit()
bool __fortio_fiofcb_stdunit (FIO_FCB * f)
Definition at line 59 of file utils.c.
References f, and fcb::stdunit.
__fortio_free_fcb()
void __fortio_free_fcb (FIO_FCB * p)
Definition at line 123 of file utils.c.
References assert, fcb_avail, FIO_TBL::fcbs, fioFcbTbls, NULL, p, and q.
Referenced by __fortio_close(), and __fortio_open().
__fortio_rwinit()
FIO_FCB * __fortio_rwinit (int unit, int form, __INT_T * recptr, int optype)
Definition at line 159 of file utils.c.
References __fortio_find_unit(), __fortio_open(), __fortio_trunc(), __fortio_zeropad(), __io_errno(), __io_fseek, __io_ftell, fcb::acc, fcb::action, assert, fcb::asy_rw, fcb::asyptr, fcb::binary, fcb::coherent, fcb::eof_flag, ERR, f, FALSE, fflush(), FIO_ASIS, Fio_asy_disable(), FIO_DIRECT, FIO_ECOMPAT, FIO_EDIRECT, FIO_EDREAD, FIO_EEOFERR, FIO_EFORM, FIO_EPOS, FIO_EPOSV, FIO_EREADONLY, FIO_EWRITEONLY, FIO_FORMATTED, FIO_KEEP, FIO_NONE, FIO_NULL, FIO_OLD, FIO_READ, FIO_READWRITE, FIO_SEQUENTIAL, FIO_STREAM, FIO_UNFORMATTED, FIO_UNKNOWN, FIO_WRITE, FIO_YES, fioFcbTbls, fcb::form, fcb::fp, if(), fcb::ispipe, ISPRESENT, len, fcb::maxrec, fcb::nextrec, NULL, optype(), fcb::partial, FIO_TBL::pos, pos, FIO_TBL::pos_present, fcb::reclen, fcb::skip, TRUE, fcb::truncflag, and void().
Referenced by __f90io_unf_init(), __f90io_usw_init(), _f90io_endfile(), _f90io_ldr_init(), _f90io_ldw_init(), _f90io_nmlr_init(), _f90io_nmlw_init(), fr_init(), and fw_init().
__fortio_set_asy_rw()
void __fortio_set_asy_rw (FIO_FCB * f, bool value)
Definition at line 53 of file utils.c.
References fcb::asy_rw, f, and value().
__fortio_swap_bytes()
void __fortio_swap_bytes (char * p, int type, long cnt)
Definition at line 525 of file utils.c.
References __CPLX16, __CPLX32, __CPLX8, __REAL16, __REAL4, __REAL8, __STR, assert, cnt, FIO_TYPE_SIZE, p, SWAPB, and type.
Referenced by __f90io_usw_read(), __f90io_usw_write(), __unf_init(), __usw_end(), and _f90io_backspace().
__fortio_trunc()
static int __fortio_trunc (FIO_FCB * p, seekoffx_t length) static
Definition at line 584 of file utils.c.
References __fort_getfd, __fortio_error(), __io_errno(), __io_fflush, FALSE, length(), and p.
Referenced by __fortio_rwinit().
__fortio_zeropad()
int __fortio_zeropad (FILE * fp, long len)
Definition at line 450 of file utils.c.
References __io_errno(), b, BFSZ, fp, FWRITE, and len.
Referenced by __fortio_rwinit(), __unf_end(), and __usw_end().
Variable Documentation
fcb_avail
FIO_FCB* fcb_avail = NULL static
Definition at line 33 of file utils.c.
Referenced by __fortio_alloc_fcb(), __fortio_cleanup_fcb(), and __fortio_free_fcb().
fcb_chunks
FIO_FCB* fcb_chunks static
Definition at line 36 of file utils.c.
Referenced by __fortio_alloc_fcb(), and __fortio_cleanup_fcb().