flang: utils3f.c File Reference
utils3f.c File Reference
#include "io3f.h"
#include <string.h>
#include "async.h"
#include "mpalloc.h"
Functions
char * __fstr2cstr (char *from, int from_len)
void __cstr_free (char *from)
void __fcp_cstr (char *to, int to_len, char *from)
bool __isatty3f (int unit)
FILE * __getfile3f (int unit)
Function Documentation
__cstr_free()
void __cstr_free (char * from)
Definition at line 33 of file utils3f.c.
References _mp_free().
Referenced by ENT3F(), and ENTF90().
__fcp_cstr()
void __fcp_cstr (char * to, int to_len, char * from)
Definition at line 39 of file utils3f.c.
Referenced by ctime_c(), and ENT3F().
__fstr2cstr()
char * __fstr2cstr (char * from, int from_len)
Definition at line 18 of file utils3f.c.
References _mp_malloc(), len, and str.
Referenced by ENT3F(), and ENTF90().
__getfile3f()
FILE * __getfile3f (int unit)
Definition at line 86 of file utils3f.c.
References __abort(), __fio_find_unit, __io_stderr(), __io_stdin(), __io_stdout(), Fio_asy_disable(), FIO_FCB_ASY_RW, FIO_FCB_ASYPTR, FIO_FCB_FP, FIO_FCB_SET_ASY_RW, NULL, and p.
Referenced by ENT3F().
__isatty3f()
bool __isatty3f (int unit)
Definition at line 59 of file utils3f.c.
References __fio_find_unit, __io_isatty(), FALSE, fd, FIO_FCB_STDUNIT, NULL, and p.
Referenced by ENT3F().