flang: utilsi64.c File Reference
utilsi64.c File Reference
#include "global.h"
Classes
union OVL8
Macros
#define NATIVEI8
#define ASCII_OFFSET 48
#define ASTERISK '*'
#define BLANK ' '
#define HEX_OFFSET 7
#define MINUS '-'
#define ZERO '0'
Typedefs
typedef long I8_T
typedef unsigned long UI8_T
Functions
static void neg64 (DBLINT64, DBLINT64)
static void uneg64 (DBLUINT64, DBLUINT64)
static int toi64 (char *, DBLINT64, char *, int)
static int ucmp64 (DBLUINT64, DBLUINT64)
void shf64 (DBLINT64, int, DBLINT64)
void ushf64 (DBLUINT64, int, DBLUINT64)
int __fort_atoxi32 (char *s, INT *i, int n, int base)
char string to 32-bit integer.
int __fort_atoxi64 (char *s, DBLINT64 ir, int n, int radix)
char string to 64-bit integer.
void __fort_i64toax (DBLINT64 from, char *to, int count, int sign, int radix)
Converts [un]signed 64 integer into a char string of the selected radix.
Variables
int __ftn_32in64_
Macro Definition Documentation
ASCII_OFFSET
#define ASCII_OFFSET 48
Definition at line 256 of file utilsi64.c.
ASTERISK
#define ASTERISK '*'
Definition at line 257 of file utilsi64.c.
BLANK
#define BLANK ' '
Definition at line 258 of file utilsi64.c.
HEX_OFFSET
#define HEX_OFFSET 7
Definition at line 259 of file utilsi64.c.
MINUS
#define MINUS '-'
Definition at line 260 of file utilsi64.c.
NATIVEI8
#define NATIVEI8
Definition at line 45 of file utilsi64.c.
ZERO
__m512d const ZERO '0'
Definition at line 261 of file utilsi64.c.
Referenced by __attribute__(), __fsd_exp_fma3(), __fsd_log_fma3(), __fss_acos_fma3(), __fvd_acos_fma3(), __fvd_acos_fma3_256(), __fvd_asin_fma3(), __fvd_asin_fma3_256(), __fvd_exp_fma3(), __fvd_exp_fma3_256(), __fvd_log_fma3(), __fvd_log_fma3_256(), __fvs_acos_fma3(), __fvs_acos_fma3_256(), __pgm_exp_d_slowpath(), __pgm_exp_d_vec128_slowpath(), __pgm_exp_d_vec256_slowpath(), __pgm_exp_d_vec512_slowpath(), __rvs_log_fma3(), and __rvs_log_fma3_256().
Typedef Documentation
I8_T
typedef long I8_T
Definition at line 30 of file utilsi64.c.
UI8_T
typedef unsigned long UI8_T
Definition at line 31 of file utilsi64.c.
Function Documentation
__fort_atoxi32()
int __fort_atoxi32 (char * s, INT * i, int n, int base)
char string to 32-bit integer.
Parameters
Input string containing number to be converted (string is NOT null terminated.)
Pointer to returned integer value
Number of chars from str to convert
Radix of conversion – 2, 8, 10, 16. If base is 16, then the digits\
a-f or A-F are allowed.
Returns
-1 str does not represent a valid number in radix base -2 overflow occurred on conversion 0 No error – *ival contains the converted number.
Definition at line 80 of file utilsi64.c.
References base, end, i, n, s, sign, and value().
Referenced by __fortio_getnum().
__fort_atoxi64()
int __fort_atoxi64 (char * s, DBLINT64 ir, int n, int radix)
char string to 64-bit integer.
Parameters
Input string containing number to be converted (string is NOT null terminated.)
DBLUINT64 output value
Number of chars from str to convert
Radix of conversion – 2, 8, 10, 16. If base is 16, then the digits a-f
Returns
-1 str does not represent a valid number in radix base -2 overflow occurred on conversion 0 No error – *ir contains the converted number.
Definition at line 230 of file utilsi64.c.
References end, n, s, and toi64().
Referenced by __fortio_getnum(), and fr_readnum().
__fort_i64toax()
void __fort_i64toax (DBLINT64 from, char * to, int count, int sign, int radix)
Converts [un]signed 64 integer into a char string of the selected radix.
Parameters
input integer value
output string
number of chars in to
0 = signed conversion; 1 = unsigned
conversion radix: 2, 8, 10, 16
Definition at line 264 of file utilsi64.c.
References ASCII_OFFSET, ASTERISK, count, HEX_OFFSET, I64_LSH, I64_MSH, OVL8::i8, idx, OVL8::lsw, MINUS, OVL8::msw, neg64(), OVL8::ovl8, shf64(), sign, and strlen().
Referenced by conv_int8().
neg64()
static void neg64 (DBLINT64 arg, DBLINT64 result) static
Definition at line 530 of file utilsi64.c.
Referenced by __fort_i64toax().
shf64()
void shf64 (DBLINT64 arg, int count, DBLINT64 result)
Definition at line 219 of file legacy-folding-api.c.
References arg, count, result, unwrap_l(), wrap_l(), and x.
Referenced by __fort_i64toax(), ftn_i_bktest(), and ftn_i_kibset().
toi64()
static int toi64 (char * s, DBLINT64 toi, char * end, int radix) static
Definition at line 409 of file utilsi64.c.
References base, end, I64_LSH, I64_MSH, OVL8::lsw, OVL8::msw, num, OVL8::ovl8, prev, s, OVL8::u8, ucmp64(), uneg64(), and ushf64().
Referenced by __fort_atoxi64().
ucmp64()
static int ucmp64 (DBLUINT64 arg1, DBLUINT64 arg2) static
Definition at line 554 of file utilsi64.c.
Referenced by toi64().
uneg64()
static void uneg64 (DBLUINT64 arg, DBLUINT64 result) static
Definition at line 541 of file utilsi64.c.
Referenced by toi64().
ushf64()
void ushf64 (DBLUINT64 arg, int count, DBLUINT64 result)
Definition at line 262 of file legacy-folding-api.c.
References arg, count, result, unwrap_u(), and wrap_u().
Referenced by ftn_i_kibclr(), ftn_i_kibits(), ftn_i_kishftc(), Ftn_kmvbits(), and toi64().
Variable Documentation
__ftn_32in64_
int __ftn_32in64_
Definition at line 17 of file utilsi64.c.
Referenced by __fortio_assign(), conv_int8(), fr_assign(), ftn_i_kishftc(), and Ftn_kmvbits().