flang: utils.cpp File Reference
utils.cpp File Reference
Utility routines used by nroff-to-C utility programs.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "utils.h"
Macros
#define USE_OLD_C_UTILS
#define NULL_FNAME "/dev/null"
Functions
bool isPathSeparator (char c)
void open_files (int argc, char *argv[])
void output_off ()
Supress output going to output files.
void output_on ()
Enable output going to output files.
int get_line1 (FILE *funit, LT ltypes[], FILE *outf)
Same as get_line except copies to outf.
void flush_line (FILE *outf)
int get_line (FILE *funit, LT ltypes[])
void put_err (int sev, const char *txt)
void get_token (char out[], int *len)
Skip past blanks in lbuff beginning at currpos, and move into 'out' the token up to the next blank character.
void interr (const char *txt, int val, int sev)
dummy version of interr to satisfy external refs.
bool getline (NroffInStream &f, std::string &s)
void collectIncludePaths (int argc, char *argv[])
Variables
static int lineno
static FILE * currfile = 0
static char lbuff [MAXLINE+1]
static int currpos
FILE * infile [10]
FILE * outfile [10]
FILE * savefile [10]
static FILE * null_file
std::list< std::string > includePaths
Detailed Description
Utility routines used by nroff-to-C utility programs.
Definition in file utils.cpp.
Macro Definition Documentation
NULL_FNAME
#define NULL_FNAME "/dev/null"
Definition at line 34 of file utils.cpp.
USE_OLD_C_UTILS
#define USE_OLD_C_UTILS
Definition at line 17 of file utils.cpp.
Function Documentation
collectIncludePaths()
void collectIncludePaths (int argc, char * argv[])
Definition at line 432 of file utils.cpp.
References assert, buf, cp, end, get_line(), get_token(), getline(), i, includePaths, isPathSeparator(), line, match(), pos, put_err(), result, strlen(), and tok.
Referenced by main().
flush_line()
void flush_line (FILE * outf)
Definition at line 181 of file utils.cpp.
References lbuff.
Referenced by proc_sym().
get_line()
int get_line (FILE * funit, LT ltypes[])
read input lines until one matching one of the line types in the 'ltypes' array is found. Return the corresponding integer line type id, or 0 for end of file. Set currpos to point immediately after first 3 chars of line.
Definition at line 193 of file utils.cpp.
References currfile, currpos, i, lbuff, lineno, LOOP, LT_EOF, ltypes, MAXLINE, NULL, and str.
Referenced by collectIncludePaths().
get_line1()
int get_line1 (FILE * funit, LT ltypes[], FILE * outf)
Same as get_line except copies to outf.
Definition at line 152 of file utils.cpp.
References currfile, currpos, i, lbuff, lineno, LOOP, LT_EOF, ltypes, MAXLINE, NULL, and str.
Referenced by proc_sym(), and write_ast().
get_token()
void get_token (char out[], int * len)
Skip past blanks in lbuff beginning at currpos, and move into 'out' the token up to the next blank character.
Currpos is left pointing to the first character (blank, NULL, or endline) following the token. One of the following values is returned in len:
len > 0 : number of characters in token.
len == 0 : no token remaining in lbuff.
len == -1: error occurred.
Definition at line 270 of file utils.cpp.
References c, currpos, i, lbuff, len, LOOP, and put_err().
Referenced by collectIncludePaths().
getline()
bool getline (NroffInStream & f, std::string & s)
Definition at line 379 of file utils.cpp.
References count, f, filename, getline(), includePaths, isPathSeparator(), k, s, strlen(), t, t1, and t2.
Referenced by collectIncludePaths(), get_input_line(), getline(), N2Rst::run(), and ulz().
interr()
void interr (const char * txt, int val, int sev)
dummy version of interr to satisfy external refs.
Definition at line 316 of file utils.cpp.
References put_err(), t, and val.
isPathSeparator()
bool isPathSeparator (char c) inline
Definition at line 40 of file utils.cpp.
Referenced by collectIncludePaths(), getline(), and open_files().
open_files()
void open_files (int argc, char * argv[])
Process command line and open input and output files. By default stdin and stdout are used. Files up to "-o" are considered input files and files following "-o" are output files (max of 10 each). "-" used for a file name indicates the default (stdin or stdout). -n preceeding a file name says that file is nroff output rather than C output.
Definition at line 57 of file utils.cpp.
References FILE, i, infile, isPathSeparator(), mode, NULL, null_file, NULL_FNAME, outfile, p, put_err(), savefile, and strlen().
Referenced by main().
output_off()
void output_off (void)
Supress output going to output files.
Definition at line 134 of file utils.cpp.
References i, null_file, outfile, and savefile.
output_on()
void output_on (void)
Enable output going to output files.
Definition at line 144 of file utils.cpp.
References i, outfile, and savefile.
put_err()
void put_err (int sev, const char * txt)
write error message to stderr with line number if non-zero (using global variable lineno) and severity level given by sev. Abort if sev == 4 (fatal error).
Parameters
sev error severity
txt error text to be written
Definition at line 235 of file utils.cpp.
References line, lineno, and tmp.
Referenced by addfieldtosym(), chk_overlap(), collectIncludePaths(), flushsym(), get_token(), interr(), open_files(), proc_sym(), and write_ast().
Variable Documentation
currfile
FILE* currfile = 0 static
Definition at line 25 of file utils.cpp.
Referenced by get_line(), and get_line1().
currpos
int currpos static
Definition at line 27 of file utils.cpp.
Referenced by __INT_T(), get_line(), get_line1(), get_token(), and inquire().
includePaths
std::list<std::string> includePaths
Definition at line 37 of file utils.cpp.
Referenced by collectIncludePaths(), and getline().
infile
FILE* infile[10]
Definition at line 29 of file utils.cpp.
Referenced by open_files().
lbuff
char lbuff[MAXLINE+1] static
Definition at line 26 of file utils.cpp.
Referenced by flush_line(), get_line(), get_line1(), and get_token().
lineno
int lineno static
Definition at line 24 of file utils.cpp.
Referenced by get_line(), get_line1(), and put_err().
null_file
FILE* null_file static
Definition at line 30 of file utils.cpp.
Referenced by open_files(), and output_off().
outfile
FILE * outfile[10]
Definition at line 29 of file utils.cpp.
Referenced by open_files(), output_off(), and output_on().
savefile
FILE * savefile[10]
Definition at line 29 of file utils.cpp.
Referenced by open_files(), output_off(), and output_on().