flang: vdexp8.cpp File Reference
vdexp8.cpp File Reference
#include <immintrin.h>
#include "mth_avx512helper.h"
#include "dexp_defs.h"
Functions
__m512d FCN_AVX512() __fvd_exp_fma3 (__m512d)
static __m512d __pgm_exp_d_vec512_slowpath (__m512d const a, __m512i const i, __m512d const t, __m512d const z)
Function Documentation
__fvd_exp_fma3()
__m512d FCN_AVX512() __fvd_exp_fma3 (__m512d a)
Definition at line 65 of file vdexp8.cpp.
References __pgm_exp_d_vec512_slowpath(), a, abs_a, DBL2INT_CVT, DBL2INT_CVT_D, EXP_POLY_0, EXP_POLY_0_D, EXP_POLY_1, EXP_POLY_10, EXP_POLY_10_D, EXP_POLY_11, EXP_POLY_11_D, EXP_POLY_1_D, EXP_POLY_2, EXP_POLY_2_D, EXP_POLY_3, EXP_POLY_3_D, EXP_POLY_4, EXP_POLY_4_D, EXP_POLY_5, EXP_POLY_5_D, EXP_POLY_6, EXP_POLY_6_D, EXP_POLY_7, EXP_POLY_7_D, EXP_POLY_8, EXP_POLY_8_D, EXP_POLY_9, EXP_POLY_9_D, HI_ABS_MASK, HI_ABS_MASK_D, i, INF, INF_D, L2E, L2E_D, m, m2, m4, MULT_CONST, MULT_CONST_D, NEG_LN2_HI_D, NEG_LN2_LO_D, SCALE_D, t, UPPERBOUND_1_D, UPPERBOUND_2, UPPERBOUND_2_D, z, ZERO, and ZERO_D.
__pgm_exp_d_vec512_slowpath()
static __m512d __pgm_exp_d_vec512_slowpath (__m512d const a, __m512i const i, __m512d const t, __m512d const z) static
Definition at line 30 of file vdexp8.cpp.
References _MM512_BLENDV_PD, _MM512_CMP_PD, a, a_plus_inf, abs_lt, accurate_scale_mask, HI_ABS_MASK, HI_ABS_MASK_D, i, i_scale_acc, i_scale_acc_2, INF, INF_D, k, lt_zero_mask, MULT_CONST, MULT_CONST_D, multiplier, res, SCALE_D, slowpath_blend, slowpath_mask, t, UPPERBOUND_1_D, UPPERBOUND_2, UPPERBOUND_2_D, z, ZERO, ZERO_D, and zero_inf_blend.
Referenced by __fvd_exp_fma3(), and __fvd_pow_fma3().