flang: vdpow8.cpp File Reference
vdpow8.cpp File Reference
#include <stdint.h>
#include <immintrin.h>
#include "mth_avx512helper.h"
#include "dpow_defs.h"
Classes
struct __m512d_2
Functions
__m512d FCN_AVX512() __fvd_pow_fma3 (__m512d, __m512d)
__m512d neg (__m512d a)
__m512d_2 __internal_ddfma (__m512d_2 x, __m512d_2 y, __m512d_2 z)
__m512d_2 __internal_ddadd_yisdouble (__m512d_2 x, __m512d_2 y)
__m512d __internal_fast_int2dbl (__m512i a)
static __m512d __attribute__ ((noinline)) __pgm_exp_d_vec512_slowpath(__m512i const i
if (a_is_neg_flag &&(!b_is_integer_flag))
if (a_is_any_zero_flag &&b_is_lt_zero_flag)
Variables
static __m512d __m512d const t
static __m512d __m512d const __m512d const bloga
static __m512d __m512d const __m512d const __m512d z = _MM512_BLENDV_PD(slowpath_blend, z, slowpath_mask)
static __m512d __m512d const __m512d const __m512d __m512d prodx
__m512d const UPPERBOUND_2 = (__m512d)_mm512_set1_epi64(UPPERBOUND_2_D)
__m512d const ZERO = _mm512_set1_pd(ZERO_D)
__m512d const INF = (__m512d)_mm512_set1_epi64(INF_D)
__m512i const HI_ABS_MASK = _mm512_set1_epi64(HI_ABS_MASK_D)
__m512i const ABS_MASK = _mm512_set1_epi64(ABS_MASK_D)
__m512i const MULT_CONST = _mm512_set1_epi64(MULT_CONST_D)
__m512i abs_bloga = _mm512_and_si512((__m512i)bloga, ABS_MASK)
__m512d abs_lt = (__m512d)_mm512_and_si512((__m512i)abs_bloga, HI_ABS_MASK)
__m512d lt_zero_mask = _MM512_CMP_PD(bloga, ZERO, _CMP_LT_OS)
__m512d slowpath_mask = _MM512_CMP_PD(abs_lt, UPPERBOUND_1, _CMP_LT_OS)
__m512d a_plus_inf = _mm512_add_pd(bloga, INF)
__m512d zero_inf_blend = _MM512_BLENDV_PD(a_plus_inf, ZERO, lt_zero_mask)
__m512d accurate_scale_mask = (__m512d)_MM512_CMP_PD(abs_lt, UPPERBOUND_2, 1)
__m512i k = _mm512_srli_epi64(i, 1)
__m512i i_scale_acc = _mm512_slli_epi64(k, D52_D)
__m512i i_scale_acc_2 = _mm512_slli_epi64(k, D52_D)
__m512d multiplier = (__m512d)_mm512_add_epi64(i_scale_acc_2, MULT_CONST)
__m512d res = (__m512d)_mm512_add_epi32(i_scale_acc, (__m512i)t)
__m512d slowpath_blend = _MM512_BLENDV_PD(zero_inf_blend, res, accurate_scale_mask)
__m512i isinf_mask = _MM512_CMPEQ_EPI64((__m512i)INF, (__m512i)z)
__m512d z_fixed = _mm512_fmadd_pd(z, prodx, z)
static __m512d __m512d const b
__m512d const SGN_EXP_MASK = (__m512d)_mm512_set1_epi64(SGN_EXP_MASK_D)
__m512d const NEG_ONE = _mm512_set1_pd(NEG_ONE_D)
__m512d const ONE = _mm512_set1_pd(ONE_D)
__m512d const HALF = _mm512_set1_pd(HALF_D)
__m512d const SGN_MASK = (__m512d)_mm512_set1_epi64(SGN_MASK_D)
__m512i const INF_FAKE = _mm512_set1_epi64(INF_FAKE_D)
__m512d const NAN_MASK = (__m512d)_mm512_set1_epi64(NAN_MASK_D)
__m512d const NEG_ONE_CONST = (__m512d)_mm512_set1_epi64(NEG_ONE_CONST_D)
__m512i const TEN_23 = _mm512_set1_epi64(TEN_23_D)
__m512i const ELEVEN = _mm512_set1_epi64(ELEVEN_D)
__m512i a_sign = (__m512i)_MM512_AND_PD(a, SGN_MASK)
__m512i b_sign = (__m512i)_MM512_AND_PD(b, SGN_MASK)
__m512i bIsOddInteger = _mm512_sllv_epi64((__m512i)b, shiftb)
__m512d abs_a = _MM512_AND_PD(a, (__m512d)ABS_MASK)
__m512d abs_b = _MM512_AND_PD(b, (__m512d)ABS_MASK)
__m512i shiftb = (__m512i)_MM512_AND_PD (b, SGN_EXP_MASK)
__m512i b_is_half = _MM512_CMPEQ_EPI64((__m512i)abs_b, (__m512i)HALF)
__m512d ahi_lt_0 = (__m512d)_MM512_CMPEQ_EPI64(a_sign, (__m512i)ZERO)
__m512d ahilt0_and_boddint_mask = _MM512_ANDNOT_PD(ahi_lt_0, (__m512d)bIsOddInteger)
__m512d b_ne_trunc = _MM512_CMP_PD(b, _MM512_ROUND_PD(b, _MM_FROUND_TO_ZERO), _CMP_NEQ_UQ)
__m512d nan_mask = _MM512_ANDNOT_PD(ahi_lt_0, b_ne_trunc)
__m512d a_is_0_mask = (__m512d)_MM512_CMPEQ_EPI64((__m512i)abs_a, (__m512i)ZERO)
__m512d thi_when_ais0 = ZERO
__m512d bhi_lt_0 = (__m512d)_MM512_CMPEQ_EPI64(b_sign, (__m512i)ZERO)
__m512d thi_or_INF = _MM512_OR_PD(thi_when_ais0, INF)
__m512d t_when_ais0 = _MM512_AND_PD(thi_when_ais0, (__m512d)HI_MASK)
__m512d a_inf_mask = (__m512d)_MM512_CMPEQ_EPI64((__m512i)abs_a, (__m512i)INF)
__m512d thi_when_aisinf = _MM512_BLENDV_PD(thi_when_aisinf, INF, bhi_lt_0)
__m512d thi_xor_sgn = _MM512_XOR_PD(thi_when_aisinf, SGN_MASK)
__m512d b_inf_mask = (__m512d)_MM512_CMPEQ_EPI64((__m512i)abs_b, (__m512i)INF)
__m512d thi_when_bisinf = ZERO
__m512d absa_gt_one = _MM512_CMP_PD(abs_a, ONE, _CMP_GT_OS)
__m512d thi_xor_inf = _MM512_XOR_PD(thi_when_bisinf, INF)
__m512d a_is_negone = (__m512d)_MM512_CMPEQ_EPI64((__m512i)a, (__m512i)NEG_ONE)
__m512i a_nan_mask = _MM512_CMPEQ_EPI64(_mm512_max_epu32((__m512i)abs_a, INF_FAKE), INF_FAKE)
__m512i b_nan_mask = _MM512_CMPEQ_EPI64(_mm512_max_epu32((__m512i)abs_b, INF_FAKE), INF_FAKE)
__m512i aorb_nan_mask = _mm512_and_si512(a_nan_mask, b_nan_mask)
__m512d a_is_one_mask = (__m512d)_MM512_CMPEQ_EPI64((__m512i)a, (__m512i)ONE)
__m512d b_is_zero_mask = (__m512d)_MM512_CMPEQ_EPI64((__m512i)abs_b, (__m512i)ZERO)
__m512d ans_equals_one_mask = _MM512_OR_PD(a_is_one_mask, b_is_zero_mask)
__m512i a_is_neg = (__m512i)_MM512_CMP_PD(a, ZERO, _CMP_LT_OS)
int a_is_neg_flag = _MM512_MOVEMASK_PD(_mm512_castsi512_pd(a_is_neg))
__m512i b_is_integer = (__m512i)_MM512_CMP_PD(b, _mm512_floor_pd(b), _CMP_EQ_OQ)
int b_is_integer_flag = _MM512_MOVEMASK_PD(_mm512_castsi512_pd(b_is_integer))
__m512i b_is_lt_zero = (__m512i)_MM512_CMP_PD(b, ZERO, _CMP_LT_OS)
int b_is_lt_zero_flag = _MM512_MOVEMASK_PD(_mm512_castsi512_pd(b_is_lt_zero))
__m512d const MINUS_ZERO = _mm512_set1_pd((double)-0.0)
__m512i a_is_pos_zero = (__m512i) _MM512_CMPEQ_PD(a, ZERO)
__m512i a_is_neg_zero = (__m512i) _MM512_CMPEQ_PD(a, MINUS_ZERO)
__m512i a_is_any_zero = _mm512_or_si512(a_is_pos_zero, a_is_neg_zero)
int a_is_any_zero_flag = _MM512_MOVEMASK_PD(_mm512_castsi512_pd(a_is_any_zero))
Function Documentation
__attribute__()
static __m512d __attribute__ ((noinline)) const static
References UPPERBOUND_1_D.
__fvd_pow_fma3()
__m512d FCN_AVX512() __fvd_pow_fma3 (__m512d a, __m512d b)
Definition at line 278 of file vdpow8.cpp.
References __internal_ddadd_yisdouble(), __internal_ddfma(), __internal_fast_int2dbl(), __pgm_exp_d_vec512_slowpath(), _MM512_AND_PD, _MM512_BLENDV_PD, _MM512_CMP_PD, _MM512_CMPEQ_EPI64, _MM512_MOVEMASK_PD, _MM512_OR_PD, a, abs_a, abs_bloga, ABS_MASK, ABS_MASK_D, ALL_ONES_EXPONENT, ALL_ONES_EXPONENT_D, b, bloga, CC_CONST_X_D, CC_CONST_Y_D, D52_D, DBL2INT_CVT, DBL2INT_CVT_D, detect_inf_nan, e, EXP_POLY_0, EXP_POLY_0_D, EXP_POLY_1, EXP_POLY_1_D, EXP_POLY_2, EXP_POLY_2_D, EXP_POLY_3, EXP_POLY_3_D, EXP_POLY_4, EXP_POLY_4_D, EXP_POLY_5, EXP_POLY_5_D, EXP_POLY_6, EXP_POLY_6_D, EXP_POLY_7, EXP_POLY_7_D, EXP_POLY_8, EXP_POLY_8_D, EXP_POLY_9, EXP_POLY_9_D, EXP_POLY_A_D, EXP_POLY_B_D, EXPO_MASK_D, f, HALFIFIER_D, HI_ABS_MASK, HI_ABS_MASK_D, HI_CONST_1_D, HI_CONST_2_D, HI_MASK_D, HI_THRESH_D, i, L2E, L2E_D, LN2_HI, LN2_HI_D, LN2_LO, LN2_LO_D, LOG_POLY_0_D, LOG_POLY_1_D, LOG_POLY_2_D, LOG_POLY_3_D, LOG_POLY_4_D, LOG_POLY_5_D, LOG_POLY_6_D, m, neg(), NEG_LN2_HI_D, NEG_LN2_LO_D, ONE, ONE_D, ONE_F, ONE_F_D, prodx, q, qq, SGN_EXP_MASK, SGN_EXP_MASK_D, t, t4, t6, t8, TEN_23, TEN_23_D, tmp, TWO_D, UPPERBOUND_1_D, __m512d_2::x, __m512d_2::y, z, ZERO, and ZERO_D.
__internal_ddadd_yisdouble()
__m512d_2 __internal_ddadd_yisdouble (__m512d_2 x, __m512d_2 y) inline
Definition at line 56 of file vdpow8.cpp.
References e, x, y, and z.
Referenced by __fvd_pow_fma3().
__internal_ddfma()
__m512d_2 __internal_ddfma (__m512d_2 x, __m512d_2 y, __m512d_2 z) inline
Definition at line 38 of file vdpow8.cpp.
References e, m, t, x, y, and z.
Referenced by __fvd_pow_fma3().
__internal_fast_int2dbl()
__m512d __internal_fast_int2dbl (__m512i a) inline
Definition at line 69 of file vdpow8.cpp.
References _MM512_BLEND_EPI32, a, INT2DBL_D, INT2DBL_HI_D, INT2DBL_LO_D, and t.
Referenced by __fvd_pow_fma3().
if() [1/2]
if (a_is_any_zero_flag && b_is_lt_zero_flag)
Definition at line 260 of file vdpow8.cpp.
References ONE, and ZERO.
if() [2/2]
if (a_is_neg_flag && !b_is_integer_flag)
Definition at line 256 of file vdpow8.cpp.
References a.
neg()
__m512d neg (__m512d a) inline
Definition at line 30 of file vdpow8.cpp.
References _MM512_XOR_PD, a, SGN_MASK, and SGN_MASK_D.
Referenced by __fvd_pow_fma3().
Variable Documentation
a_inf_mask
__m512d a_inf_mask = (__m512d)_MM512_CMPEQ_EPI64((__m512i)abs_a, (__m512i)INF)
Definition at line 191 of file vdpow8.cpp.
a_is_0_mask
__m512d a_is_0_mask = (__m512d)_MM512_CMPEQ_EPI64((__m512i)abs_a, (__m512i)ZERO)
Definition at line 176 of file vdpow8.cpp.
a_is_any_zero
__m512i a_is_any_zero = _mm512_or_si512(a_is_pos_zero, a_is_neg_zero)
Definition at line 241 of file vdpow8.cpp.
a_is_any_zero_flag
int a_is_any_zero_flag = _MM512_MOVEMASK_PD(_mm512_castsi512_pd(a_is_any_zero))
Definition at line 242 of file vdpow8.cpp.
a_is_neg
__m512i a_is_neg = (__m512i)_MM512_CMP_PD(a, ZERO, _CMP_LT_OS)
Definition at line 229 of file vdpow8.cpp.
a_is_neg_flag
int a_is_neg_flag = _MM512_MOVEMASK_PD(_mm512_castsi512_pd(a_is_neg))
Definition at line 230 of file vdpow8.cpp.
a_is_neg_zero
__m512i a_is_neg_zero = (__m512i) _MM512_CMPEQ_PD(a, MINUS_ZERO)
Definition at line 240 of file vdpow8.cpp.
a_is_negone
__m512d a_is_negone = (__m512d)_MM512_CMPEQ_EPI64((__m512i)a, (__m512i)NEG_ONE)
Definition at line 210 of file vdpow8.cpp.
a_is_one_mask
__m512d a_is_one_mask = (__m512d)_MM512_CMPEQ_EPI64((__m512i)a, (__m512i)ONE)
Definition at line 222 of file vdpow8.cpp.
a_is_pos_zero
__m512i a_is_pos_zero = (__m512i) _MM512_CMPEQ_PD(a, ZERO)
Definition at line 239 of file vdpow8.cpp.
a_nan_mask
__m512i a_nan_mask = _MM512_CMPEQ_EPI64(_mm512_max_epu32((__m512i)abs_a, INF_FAKE), INF_FAKE)
Definition at line 216 of file vdpow8.cpp.
a_plus_inf
__m512d a_plus_inf = _mm512_add_pd(bloga, INF)
Definition at line 96 of file vdpow8.cpp.
a_sign
a_sign = (__m512i)_MM512_AND_PD(a, SGN_MASK)
Definition at line 142 of file vdpow8.cpp.
abs_a
abs_a = _MM512_AND_PD(a, (__m512d)ABS_MASK)
Definition at line 143 of file vdpow8.cpp.
Referenced by __fvd_pow_fma3().
abs_b
abs_b = _MM512_AND_PD(b, (__m512d)ABS_MASK)
Definition at line 143 of file vdpow8.cpp.
abs_bloga
__m512i abs_bloga = _mm512_and_si512((__m512i)bloga, ABS_MASK)
Definition at line 91 of file vdpow8.cpp.
Referenced by __fvd_pow_fma3().
abs_lt
__m512d abs_lt = (__m512d)_mm512_and_si512((__m512i)abs_bloga, HI_ABS_MASK)
Definition at line 92 of file vdpow8.cpp.
ABS_MASK
__m512i const ABS_MASK = _mm512_set1_epi64(ABS_MASK_D)
Definition at line 88 of file vdpow8.cpp.
Referenced by __fvd_pow_fma3().
absa_gt_one
__m512d absa_gt_one = _MM512_CMP_PD(abs_a, ONE, _CMP_GT_OS)
Definition at line 204 of file vdpow8.cpp.
accurate_scale_mask
__m512d accurate_scale_mask = (__m512d)_MM512_CMP_PD(abs_lt, UPPERBOUND_2, 1)
Definition at line 99 of file vdpow8.cpp.
ahi_lt_0
__m512d ahi_lt_0 = (__m512d)_MM512_CMPEQ_EPI64(a_sign, (__m512i)ZERO)
Definition at line 165 of file vdpow8.cpp.
ahilt0_and_boddint_mask
__m512d ahilt0_and_boddint_mask = _MM512_ANDNOT_PD(ahi_lt_0, (__m512d)bIsOddInteger)
Definition at line 166 of file vdpow8.cpp.
ans_equals_one_mask
__m512d ans_equals_one_mask = _MM512_OR_PD(a_is_one_mask, b_is_zero_mask)
Definition at line 224 of file vdpow8.cpp.
aorb_nan_mask
__m512i aorb_nan_mask = _mm512_and_si512(a_nan_mask, b_nan_mask)
Definition at line 218 of file vdpow8.cpp.
b
__m512d __m512d const b
Definition at line 124 of file vdpow8.cpp.
Referenced by __fvd_pow_fma3().
b_inf_mask
__m512d b_inf_mask = (__m512d)_MM512_CMPEQ_EPI64((__m512i)abs_b, (__m512i)INF)
Definition at line 202 of file vdpow8.cpp.
b_is_half
__m512i b_is_half = _MM512_CMPEQ_EPI64((__m512i)abs_b, (__m512i)HALF)
Definition at line 157 of file vdpow8.cpp.
b_is_integer
__m512i b_is_integer = (__m512i)_MM512_CMP_PD(b, _mm512_floor_pd(b), _CMP_EQ_OQ)
Definition at line 232 of file vdpow8.cpp.
b_is_integer_flag
int b_is_integer_flag = _MM512_MOVEMASK_PD(_mm512_castsi512_pd(b_is_integer))
Definition at line 233 of file vdpow8.cpp.
b_is_lt_zero
__m512i b_is_lt_zero = (__m512i)_MM512_CMP_PD(b, ZERO, _CMP_LT_OS)
Definition at line 235 of file vdpow8.cpp.
b_is_lt_zero_flag
int b_is_lt_zero_flag = _MM512_MOVEMASK_PD(_mm512_castsi512_pd(b_is_lt_zero))
Definition at line 236 of file vdpow8.cpp.
b_is_zero_mask
__m512d b_is_zero_mask = (__m512d)_MM512_CMPEQ_EPI64((__m512i)abs_b, (__m512i)ZERO)
Definition at line 223 of file vdpow8.cpp.
b_nan_mask
__m512i b_nan_mask = _MM512_CMPEQ_EPI64(_mm512_max_epu32((__m512i)abs_b, INF_FAKE), INF_FAKE)
Definition at line 217 of file vdpow8.cpp.
b_ne_trunc
__m512d b_ne_trunc = _MM512_CMP_PD(b, _MM512_ROUND_PD(b, _MM_FROUND_TO_ZERO), _CMP_NEQ_UQ)
Definition at line 171 of file vdpow8.cpp.
b_sign
b_sign = (__m512i)_MM512_AND_PD(b, SGN_MASK)
Definition at line 142 of file vdpow8.cpp.
bhi_lt_0
__m512d bhi_lt_0 = (__m512d)_MM512_CMPEQ_EPI64(b_sign, (__m512i)ZERO)
Definition at line 183 of file vdpow8.cpp.
bIsOddInteger
bIsOddInteger = _mm512_sllv_epi64((__m512i)b, shiftb)
Definition at line 142 of file vdpow8.cpp.
bloga
__m512d __m512d const __m512d const bloga
Definition at line 81 of file vdpow8.cpp.
Referenced by __fvd_pow_fma3().
ELEVEN
__m512i const ELEVEN = _mm512_set1_epi64(ELEVEN_D)
Definition at line 140 of file vdpow8.cpp.
HALF
__m512d const HALF = _mm512_set1_pd(HALF_D)
Definition at line 132 of file vdpow8.cpp.
HI_ABS_MASK
__m512i const HI_ABS_MASK = _mm512_set1_epi64(HI_ABS_MASK_D)
Definition at line 87 of file vdpow8.cpp.
Referenced by __fvd_pow_fma3().
i_scale_acc
__m512i i_scale_acc = _mm512_slli_epi64(k, D52_D)
Definition at line 103 of file vdpow8.cpp.
i_scale_acc_2
__m512i i_scale_acc_2 = _mm512_slli_epi64(k, D52_D)
Definition at line 105 of file vdpow8.cpp.
INF
__m512d const INF = (__m512d)_mm512_set1_epi64(INF_D)
Definition at line 86 of file vdpow8.cpp.
INF_FAKE
__m512i const INF_FAKE = _mm512_set1_epi64(INF_FAKE_D)
Definition at line 135 of file vdpow8.cpp.
isinf_mask
__m512i isinf_mask = _MM512_CMPEQ_EPI64((__m512i)INF, (__m512i)z)
Definition at line 115 of file vdpow8.cpp.
k
k = _mm512_srli_epi64(i, 1)
Definition at line 102 of file vdpow8.cpp.
lt_zero_mask
__m512d lt_zero_mask = _MM512_CMP_PD(bloga, ZERO, _CMP_LT_OS)
Definition at line 93 of file vdpow8.cpp.
MINUS_ZERO
__m512d const MINUS_ZERO = _mm512_set1_pd((double)-0.0)
Definition at line 238 of file vdpow8.cpp.
MULT_CONST
__m512i const MULT_CONST = _mm512_set1_epi64(MULT_CONST_D)
Definition at line 89 of file vdpow8.cpp.
multiplier
multiplier = (__m512d)_mm512_add_epi64(i_scale_acc_2, MULT_CONST)
Definition at line 106 of file vdpow8.cpp.
NAN_MASK
__m512d const NAN_MASK = (__m512d)_mm512_set1_epi64(NAN_MASK_D)
Definition at line 136 of file vdpow8.cpp.
nan_mask
__m512d nan_mask = _MM512_ANDNOT_PD(ahi_lt_0, b_ne_trunc)
Definition at line 172 of file vdpow8.cpp.
NEG_ONE
__m512d const NEG_ONE = _mm512_set1_pd(NEG_ONE_D)
Definition at line 129 of file vdpow8.cpp.
NEG_ONE_CONST
__m512d const NEG_ONE_CONST = (__m512d)_mm512_set1_epi64(NEG_ONE_CONST_D)
Definition at line 137 of file vdpow8.cpp.
ONE
__m512d const ONE = _mm512_set1_pd(ONE_D)
Definition at line 131 of file vdpow8.cpp.
Referenced by __fvd_pow_fma3(), and if().
prodx
__m512d __m512d const __m512d const __m512d __m512d prodx
Initial value:
{
    __m512d const UPPERBOUND_1 = (__m512d)_mm512_set1_epi64(UPPERBOUND_1_D)
Definition at line 81 of file vdpow8.cpp.
Referenced by __fvd_pow_fma3().
res
res = (__m512d)_mm512_add_epi32(i_scale_acc, (__m512i)t)
Definition at line 109 of file vdpow8.cpp.
SGN_EXP_MASK
__m512d const SGN_EXP_MASK = (__m512d)_mm512_set1_epi64(SGN_EXP_MASK_D)
Definition at line 127 of file vdpow8.cpp.
Referenced by __fvd_pow_fma3().
SGN_MASK
__m512d const SGN_MASK = (__m512d)_mm512_set1_epi64(SGN_MASK_D)
Definition at line 133 of file vdpow8.cpp.
Referenced by neg().
shiftb
shiftb = (__m512i)_MM512_AND_PD (b, SGN_EXP_MASK)
Definition at line 144 of file vdpow8.cpp.
slowpath_blend
__m512d slowpath_blend = _MM512_BLENDV_PD(zero_inf_blend, res, accurate_scale_mask)
Definition at line 112 of file vdpow8.cpp.
slowpath_mask
__m512d slowpath_mask = _MM512_CMP_PD(abs_lt, UPPERBOUND_1, _CMP_LT_OS)
Definition at line 94 of file vdpow8.cpp.
t
return t
Initial value:
{
   __m512i const HI_MASK       = _mm512_set1_epi64(HI_MASK_D)
Definition at line 81 of file vdpow8.cpp.
Referenced by __fvd_pow_fma3(), __internal_ddfma(), and __internal_fast_int2dbl().
t_when_ais0
__m512d t_when_ais0 = _MM512_AND_PD(thi_when_ais0, (__m512d)HI_MASK)
Definition at line 186 of file vdpow8.cpp.
TEN_23
__m512i const TEN_23 = _mm512_set1_epi64(TEN_23_D)
Definition at line 139 of file vdpow8.cpp.
Referenced by __fvd_pow_fma3().
thi_or_INF
__m512d thi_or_INF = _MM512_OR_PD(thi_when_ais0, INF)
Definition at line 184 of file vdpow8.cpp.
thi_when_ais0
thi_when_ais0 = ZERO
Definition at line 177 of file vdpow8.cpp.
thi_when_aisinf
thi_when_aisinf = _MM512_BLENDV_PD(thi_when_aisinf, INF, bhi_lt_0)
Definition at line 193 of file vdpow8.cpp.
thi_when_bisinf
thi_when_bisinf = ZERO
Definition at line 203 of file vdpow8.cpp.
thi_xor_inf
__m512d thi_xor_inf = _MM512_XOR_PD(thi_when_bisinf, INF)
Definition at line 207 of file vdpow8.cpp.
thi_xor_sgn
__m512d thi_xor_sgn = _MM512_XOR_PD(thi_when_aisinf, SGN_MASK)
Definition at line 196 of file vdpow8.cpp.
UPPERBOUND_2
__m512d const UPPERBOUND_2 = (__m512d)_mm512_set1_epi64(UPPERBOUND_2_D)
Definition at line 84 of file vdpow8.cpp.
z
return z = _MM512_BLENDV_PD(slowpath_blend, z, slowpath_mask)
Definition at line 81 of file vdpow8.cpp.
Referenced by __fvd_pow_fma3(), __internal_ddadd_yisdouble(), and __internal_ddfma().
z_fixed
__m512d z_fixed = _mm512_fmadd_pd(z, prodx, z)
Definition at line 116 of file vdpow8.cpp.
ZERO
__m512d const ZERO = _mm512_set1_pd(ZERO_D)
Definition at line 85 of file vdpow8.cpp.
Referenced by __fvd_pow_fma3(), and if().
zero_inf_blend
__m512d zero_inf_blend = _MM512_BLENDV_PD(a_plus_inf, ZERO, lt_zero_mask)
Definition at line 97 of file vdpow8.cpp.