flang: vdpow4.cpp File Reference
vdpow4.cpp File Reference
#include <immintrin.h>
#include "dpow_defs.h"
Classes
struct __m256d_2
Functions
__m256d __fvd_pow_fma3_256 (__m256d, __m256d)
__m256d neg (__m256d a)
__m256d_2 __internal_ddfma (__m256d_2 x, __m256d_2 y, __m256d_2 z)
__m256d_2 __internal_ddadd_yisdouble (__m256d_2 x, __m256d_2 y)
__m256d __internal_fast_int2dbl (__m256i a)
__m256d __attribute__ ((noinline)) __pgm_exp_d_vec256_slowpath(__m256i const i
if (a_is_neg_flag &&(!b_is_integer_flag))
if (a_is_any_zero_flag &&b_is_lt_zero_flag)
Variables
__m256d __m256d const t
__m256d __m256d const __m256d const bloga
__m256d __m256d const __m256d const __m256d z = _mm256_blendv_pd(slowpath_blend, z, slowpath_mask)
__m256d __m256d const __m256d const __m256d __m256d prodx
__m256d const UPPERBOUND_2 = (__m256d)_mm256_set1_epi64x(UPPERBOUND_2_D)
__m256d const ZERO = _mm256_set1_pd(ZERO_D)
__m256d const INF = (__m256d)_mm256_set1_epi64x(INF_D)
__m256i const HI_ABS_MASK = _mm256_set1_epi64x(HI_ABS_MASK_D)
__m256i const ABS_MASK = _mm256_set1_epi64x(ABS_MASK_D)
__m256i const MULT_CONST = _mm256_set1_epi64x(MULT_CONST_D)
__m256i abs_bloga = _mm256_and_si256((__m256i)bloga, ABS_MASK)
__m256d abs_lt = (__m256d)_mm256_and_si256((__m256i)abs_bloga, HI_ABS_MASK)
__m256d lt_zero_mask = _mm256_cmp_pd(bloga, ZERO, _CMP_LT_OS)
__m256d slowpath_mask = _mm256_cmp_pd(abs_lt, UPPERBOUND_1, _CMP_LT_OS)
__m256d a_plus_inf = _mm256_add_pd(bloga, INF)
__m256d zero_inf_blend = _mm256_blendv_pd(a_plus_inf, ZERO, lt_zero_mask)
__m256d accurate_scale_mask = (__m256d)_mm256_cmp_pd(abs_lt, UPPERBOUND_2, 1)
__m256i k = _mm256_srli_epi64(i, 1)
__m256i i_scale_acc = _mm256_slli_epi64(k, D52_D)
__m256i i_scale_acc_2 = _mm256_slli_epi64(k, D52_D)
__m256d multiplier = (__m256d)_mm256_add_epi64(i_scale_acc_2, MULT_CONST)
__m256d res = (__m256d)_mm256_add_epi32(i_scale_acc, (__m256i)t)
__m256d slowpath_blend = _mm256_blendv_pd(zero_inf_blend, res, accurate_scale_mask)
__m256i isinf_mask = _mm256_cmpeq_epi64((__m256i)INF, (__m256i)z)
__m256d z_fixed = _mm256_fmadd_pd(z, prodx, z)
__m256d __m256d const b
__m256d const SGN_EXP_MASK = (__m256d)_mm256_set1_epi64x(SGN_EXP_MASK_D)
__m256d const NEG_ONE = _mm256_set1_pd(NEG_ONE_D)
__m256d const ONE = _mm256_set1_pd(ONE_D)
__m256d const HALF = _mm256_set1_pd(HALF_D)
__m256d const SGN_MASK = (__m256d)_mm256_set1_epi64x(SGN_MASK_D)
__m256i const INF_FAKE = _mm256_set1_epi64x(INF_FAKE_D)
__m256d const NAN_MASK = (__m256d)_mm256_set1_epi64x(NAN_MASK_D)
__m256d const NEG_ONE_CONST = (__m256d)_mm256_set1_epi64x(NEG_ONE_CONST_D)
__m256i const TEN_23 = _mm256_set1_epi64x(TEN_23_D)
__m256i const ELEVEN = _mm256_set1_epi64x(ELEVEN_D)
__m256i a_sign = (__m256i)_mm256_and_pd(a, SGN_MASK)
__m256i b_sign = (__m256i)_mm256_and_pd(b, SGN_MASK)
__m256i bIsOddInteger = _mm256_sllv_epi64((__m256i)b, shiftb)
__m256d abs_a = _mm256_and_pd(a, (__m256d)ABS_MASK)
__m256d abs_b = _mm256_and_pd(b, (__m256d)ABS_MASK)
__m256i shiftb = (__m256i)_mm256_and_pd (b, SGN_EXP_MASK)
__m256i b_is_half = _mm256_cmpeq_epi64((__m256i)abs_b, (__m256i)HALF)
__m256d ahi_lt_0 = (__m256d)_mm256_cmpeq_epi64(a_sign, (__m256i)ZERO)
__m256d ahilt0_and_boddint_mask = _mm256_andnot_pd(ahi_lt_0, (__m256d)bIsOddInteger)
__m256d b_ne_trunc = _mm256_cmp_pd(b, _mm256_round_pd(b, _MM_FROUND_TO_ZERO), _CMP_NEQ_UQ)
__m256d nan_mask = _mm256_andnot_pd(ahi_lt_0, b_ne_trunc)
__m256d a_is_0_mask = (__m256d)_mm256_cmpeq_epi64((__m256i)abs_a, (__m256i)ZERO)
__m256d thi_when_ais0 = ZERO
__m256d bhi_lt_0 = (__m256d)_mm256_cmpeq_epi64(b_sign, (__m256i)ZERO)
__m256d thi_or_INF = _mm256_or_pd(thi_when_ais0, INF)
__m256d t_when_ais0 = _mm256_and_pd(thi_when_ais0, (__m256d)HI_MASK)
__m256d a_inf_mask = (__m256d)_mm256_cmpeq_epi64((__m256i)abs_a, (__m256i)INF)
__m256d thi_when_aisinf = _mm256_blendv_pd(thi_when_aisinf, INF, bhi_lt_0)
__m256d thi_xor_sgn = _mm256_xor_pd(thi_when_aisinf, SGN_MASK)
__m256d b_inf_mask = (__m256d)_mm256_cmpeq_epi64((__m256i)abs_b, (__m256i)INF)
__m256d thi_when_bisinf = ZERO
__m256d absa_gt_one = _mm256_cmp_pd(abs_a, ONE, _CMP_GT_OS)
__m256d thi_xor_inf = _mm256_xor_pd(thi_when_bisinf, INF)
__m256d a_is_negone = (__m256d)_mm256_cmpeq_epi64((__m256i)a, (__m256i)NEG_ONE)
__m256i a_nan_mask = _mm256_cmpeq_epi64(_mm256_max_epu32((__m256i)abs_a, INF_FAKE), INF_FAKE)
__m256i b_nan_mask = _mm256_cmpeq_epi64(_mm256_max_epu32((__m256i)abs_b, INF_FAKE), INF_FAKE)
__m256i aorb_nan_mask = _mm256_and_si256(a_nan_mask, b_nan_mask)
__m256d a_is_one_mask = (__m256d)_mm256_cmpeq_epi64((__m256i)a, (__m256i)ONE)
__m256d b_is_zero_mask = (__m256d)_mm256_cmpeq_epi64((__m256i)abs_b, (__m256i)ZERO)
__m256d ans_equals_one_mask = _mm256_or_pd(a_is_one_mask, b_is_zero_mask)
__m256i a_is_neg = (__m256i)_mm256_cmp_pd(a, ZERO, _CMP_LT_OS)
int a_is_neg_flag = _mm256_movemask_epi8((__m256i)a_is_neg)
__m256i b_is_integer = (__m256i)_mm256_cmp_pd(b, _mm256_floor_pd(b), _CMP_EQ_OQ)
int b_is_integer_flag = _mm256_movemask_epi8((__m256i)b_is_integer)
__m256i b_is_lt_zero = (__m256i)_mm256_cmp_pd(b, ZERO, _CMP_LT_OS)
int b_is_lt_zero_flag = _mm256_movemask_epi8((__m256i)b_is_lt_zero)
__m256d const MINUS_ZERO = _mm256_set1_pd((double)-0.0)
__m256i a_is_pos_zero = _mm256_cmpeq_epi64((__m256i)a, (__m256i)ZERO)
__m256i a_is_neg_zero = _mm256_cmpeq_epi64((__m256i)a, (__m256i)MINUS_ZERO)
__m256i a_is_any_zero = _mm256_or_si256(a_is_pos_zero, a_is_neg_zero)
int a_is_any_zero_flag = _mm256_movemask_epi8((__m256i)a_is_any_zero)
Function Documentation
__attribute__()
__m256d __attribute__ ((noinline)) const
References UPPERBOUND_1_D.
__fvd_pow_fma3_256()
__m256d __fvd_pow_fma3_256 (__m256d a, __m256d b)
Definition at line 276 of file vdpow4.cpp.
References __internal_ddadd_yisdouble(), __internal_ddfma(), __internal_fast_int2dbl(), __pgm_exp_d_vec256_slowpath(), a, abs_a, abs_bloga, ABS_MASK, ABS_MASK_D, ALL_ONES_EXPONENT, ALL_ONES_EXPONENT_D, b, bloga, CC_CONST_X_D, CC_CONST_Y_D, D52_D, DBL2INT_CVT, DBL2INT_CVT_D, detect_inf_nan, e, EXP_POLY_0, EXP_POLY_0_D, EXP_POLY_1, EXP_POLY_1_D, EXP_POLY_2, EXP_POLY_2_D, EXP_POLY_3, EXP_POLY_3_D, EXP_POLY_4, EXP_POLY_4_D, EXP_POLY_5, EXP_POLY_5_D, EXP_POLY_6, EXP_POLY_6_D, EXP_POLY_7, EXP_POLY_7_D, EXP_POLY_8, EXP_POLY_8_D, EXP_POLY_9, EXP_POLY_9_D, EXP_POLY_A_D, EXP_POLY_B_D, EXPO_MASK_D, f, HALFIFIER_D, HI_ABS_MASK, HI_ABS_MASK_D, HI_CONST_1_D, HI_CONST_2_D, HI_MASK_D, HI_THRESH_D, i, L2E, L2E_D, LN2_HI, LN2_HI_D, LN2_LO, LN2_LO_D, LOG_POLY_0_D, LOG_POLY_1_D, LOG_POLY_2_D, LOG_POLY_3_D, LOG_POLY_4_D, LOG_POLY_5_D, LOG_POLY_6_D, m, neg(), NEG_LN2_HI_D, NEG_LN2_LO_D, ONE, ONE_D, ONE_F, ONE_F_D, prodx, q, qq, SGN_EXP_MASK, SGN_EXP_MASK_D, t, t4, t6, t8, TEN_23, TEN_23_D, tmp, TWO_D, UPPERBOUND_1_D, __m256d_2::x, __m256d_2::y, z, ZERO, and ZERO_D.
__internal_ddadd_yisdouble()
__m256d_2 __internal_ddadd_yisdouble (__m256d_2 x, __m256d_2 y) inline
Definition at line 54 of file vdpow4.cpp.
References e, x, y, and z.
Referenced by __fvd_pow_fma3_256().
__internal_ddfma()
__m256d_2 __internal_ddfma (__m256d_2 x, __m256d_2 y, __m256d_2 z) inline
Definition at line 36 of file vdpow4.cpp.
References e, m, t, x, y, and z.
Referenced by __fvd_pow_fma3_256().
__internal_fast_int2dbl()
__m256d __internal_fast_int2dbl (__m256i a) inline
Definition at line 67 of file vdpow4.cpp.
References a, INT2DBL_D, INT2DBL_HI_D, INT2DBL_LO_D, and t.
Referenced by __fvd_pow_fma3_256().
if() [1/2]
if (a_is_any_zero_flag && b_is_lt_zero_flag)
Definition at line 258 of file vdpow4.cpp.
References ONE, and ZERO.
if() [2/2]
if (a_is_neg_flag && !b_is_integer_flag)
Definition at line 254 of file vdpow4.cpp.
References a.
neg()
__m256d neg (__m256d a) inline
Definition at line 28 of file vdpow4.cpp.
References a, SGN_MASK, and SGN_MASK_D.
Referenced by __fvd_pow_fma3_256().
Variable Documentation
a_inf_mask
__m256d a_inf_mask = (__m256d)_mm256_cmpeq_epi64((__m256i)abs_a, (__m256i)INF)
Definition at line 189 of file vdpow4.cpp.
a_is_0_mask
__m256d a_is_0_mask = (__m256d)_mm256_cmpeq_epi64((__m256i)abs_a, (__m256i)ZERO)
Definition at line 174 of file vdpow4.cpp.
a_is_any_zero
__m256i a_is_any_zero = _mm256_or_si256(a_is_pos_zero, a_is_neg_zero)
Definition at line 239 of file vdpow4.cpp.
a_is_any_zero_flag
int a_is_any_zero_flag = _mm256_movemask_epi8((__m256i)a_is_any_zero)
Definition at line 240 of file vdpow4.cpp.
a_is_neg
__m256i a_is_neg = (__m256i)_mm256_cmp_pd(a, ZERO, _CMP_LT_OS)
Definition at line 227 of file vdpow4.cpp.
a_is_neg_flag
int a_is_neg_flag = _mm256_movemask_epi8((__m256i)a_is_neg)
Definition at line 228 of file vdpow4.cpp.
a_is_neg_zero
__m256i a_is_neg_zero = _mm256_cmpeq_epi64((__m256i)a, (__m256i)MINUS_ZERO)
Definition at line 238 of file vdpow4.cpp.
a_is_negone
__m256d a_is_negone = (__m256d)_mm256_cmpeq_epi64((__m256i)a, (__m256i)NEG_ONE)
Definition at line 208 of file vdpow4.cpp.
a_is_one_mask
__m256d a_is_one_mask = (__m256d)_mm256_cmpeq_epi64((__m256i)a, (__m256i)ONE)
Definition at line 220 of file vdpow4.cpp.
a_is_pos_zero
__m256i a_is_pos_zero = _mm256_cmpeq_epi64((__m256i)a, (__m256i)ZERO)
Definition at line 237 of file vdpow4.cpp.
a_nan_mask
__m256i a_nan_mask = _mm256_cmpeq_epi64(_mm256_max_epu32((__m256i)abs_a, INF_FAKE), INF_FAKE)
Definition at line 214 of file vdpow4.cpp.
a_plus_inf
__m256d a_plus_inf = _mm256_add_pd(bloga, INF)
Definition at line 94 of file vdpow4.cpp.
a_sign
a_sign = (__m256i)_mm256_and_pd(a, SGN_MASK)
Definition at line 140 of file vdpow4.cpp.
abs_a
abs_a = _mm256_and_pd(a, (__m256d)ABS_MASK)
Definition at line 141 of file vdpow4.cpp.
Referenced by __fvd_pow_fma3_256().
abs_b
abs_b = _mm256_and_pd(b, (__m256d)ABS_MASK)
Definition at line 141 of file vdpow4.cpp.
abs_bloga
__m256i abs_bloga = _mm256_and_si256((__m256i)bloga, ABS_MASK)
Definition at line 89 of file vdpow4.cpp.
Referenced by __fvd_pow_fma3_256().
abs_lt
__m256d abs_lt = (__m256d)_mm256_and_si256((__m256i)abs_bloga, HI_ABS_MASK)
Definition at line 90 of file vdpow4.cpp.
ABS_MASK
__m256i const ABS_MASK = _mm256_set1_epi64x(ABS_MASK_D)
Definition at line 86 of file vdpow4.cpp.
Referenced by __fvd_pow_fma3_256().
absa_gt_one
__m256d absa_gt_one = _mm256_cmp_pd(abs_a, ONE, _CMP_GT_OS)
Definition at line 202 of file vdpow4.cpp.
accurate_scale_mask
__m256d accurate_scale_mask = (__m256d)_mm256_cmp_pd(abs_lt, UPPERBOUND_2, 1)
Definition at line 97 of file vdpow4.cpp.
ahi_lt_0
__m256d ahi_lt_0 = (__m256d)_mm256_cmpeq_epi64(a_sign, (__m256i)ZERO)
Definition at line 163 of file vdpow4.cpp.
ahilt0_and_boddint_mask
__m256d ahilt0_and_boddint_mask = _mm256_andnot_pd(ahi_lt_0, (__m256d)bIsOddInteger)
Definition at line 164 of file vdpow4.cpp.
ans_equals_one_mask
__m256d ans_equals_one_mask = _mm256_or_pd(a_is_one_mask, b_is_zero_mask)
Definition at line 222 of file vdpow4.cpp.
aorb_nan_mask
__m256i aorb_nan_mask = _mm256_and_si256(a_nan_mask, b_nan_mask)
Definition at line 216 of file vdpow4.cpp.
b
__m256d __m256d const b
Definition at line 122 of file vdpow4.cpp.
Referenced by __fvd_pow_fma3_256().
b_inf_mask
__m256d b_inf_mask = (__m256d)_mm256_cmpeq_epi64((__m256i)abs_b, (__m256i)INF)
Definition at line 200 of file vdpow4.cpp.
b_is_half
__m256i b_is_half = _mm256_cmpeq_epi64((__m256i)abs_b, (__m256i)HALF)
Definition at line 155 of file vdpow4.cpp.
b_is_integer
__m256i b_is_integer = (__m256i)_mm256_cmp_pd(b, _mm256_floor_pd(b), _CMP_EQ_OQ)
Definition at line 230 of file vdpow4.cpp.
b_is_integer_flag
int b_is_integer_flag = _mm256_movemask_epi8((__m256i)b_is_integer)
Definition at line 231 of file vdpow4.cpp.
b_is_lt_zero
__m256i b_is_lt_zero = (__m256i)_mm256_cmp_pd(b, ZERO, _CMP_LT_OS)
Definition at line 233 of file vdpow4.cpp.
b_is_lt_zero_flag
int b_is_lt_zero_flag = _mm256_movemask_epi8((__m256i)b_is_lt_zero)
Definition at line 234 of file vdpow4.cpp.
b_is_zero_mask
__m256d b_is_zero_mask = (__m256d)_mm256_cmpeq_epi64((__m256i)abs_b, (__m256i)ZERO)
Definition at line 221 of file vdpow4.cpp.
b_nan_mask
__m256i b_nan_mask = _mm256_cmpeq_epi64(_mm256_max_epu32((__m256i)abs_b, INF_FAKE), INF_FAKE)
Definition at line 215 of file vdpow4.cpp.
b_ne_trunc
__m256d b_ne_trunc = _mm256_cmp_pd(b, _mm256_round_pd(b, _MM_FROUND_TO_ZERO), _CMP_NEQ_UQ)
Definition at line 169 of file vdpow4.cpp.
b_sign
b_sign = (__m256i)_mm256_and_pd(b, SGN_MASK)
Definition at line 140 of file vdpow4.cpp.
bhi_lt_0
__m256d bhi_lt_0 = (__m256d)_mm256_cmpeq_epi64(b_sign, (__m256i)ZERO)
Definition at line 181 of file vdpow4.cpp.
bIsOddInteger
bIsOddInteger = _mm256_sllv_epi64((__m256i)b, shiftb)
Definition at line 140 of file vdpow4.cpp.
bloga
__m256d __m256d const __m256d const bloga
Definition at line 79 of file vdpow4.cpp.
Referenced by __fvd_pow_fma3_256().
ELEVEN
__m256i const ELEVEN = _mm256_set1_epi64x(ELEVEN_D)
Definition at line 138 of file vdpow4.cpp.
HALF
__m256d const HALF = _mm256_set1_pd(HALF_D)
Definition at line 130 of file vdpow4.cpp.
HI_ABS_MASK
__m256i const HI_ABS_MASK = _mm256_set1_epi64x(HI_ABS_MASK_D)
Definition at line 85 of file vdpow4.cpp.
Referenced by __fvd_pow_fma3_256().
i_scale_acc
__m256i i_scale_acc = _mm256_slli_epi64(k, D52_D)
Definition at line 101 of file vdpow4.cpp.
i_scale_acc_2
__m256i i_scale_acc_2 = _mm256_slli_epi64(k, D52_D)
Definition at line 103 of file vdpow4.cpp.
INF
__m256d const INF = (__m256d)_mm256_set1_epi64x(INF_D)
Definition at line 84 of file vdpow4.cpp.
INF_FAKE
__m256i const INF_FAKE = _mm256_set1_epi64x(INF_FAKE_D)
Definition at line 133 of file vdpow4.cpp.
isinf_mask
__m256i isinf_mask = _mm256_cmpeq_epi64((__m256i)INF, (__m256i)z)
Definition at line 113 of file vdpow4.cpp.
k
k = _mm256_srli_epi64(i, 1)
Definition at line 100 of file vdpow4.cpp.
lt_zero_mask
__m256d lt_zero_mask = _mm256_cmp_pd(bloga, ZERO, _CMP_LT_OS)
Definition at line 91 of file vdpow4.cpp.
MINUS_ZERO
__m256d const MINUS_ZERO = _mm256_set1_pd((double)-0.0)
Definition at line 236 of file vdpow4.cpp.
MULT_CONST
__m256i const MULT_CONST = _mm256_set1_epi64x(MULT_CONST_D)
Definition at line 87 of file vdpow4.cpp.
multiplier
multiplier = (__m256d)_mm256_add_epi64(i_scale_acc_2, MULT_CONST)
Definition at line 104 of file vdpow4.cpp.
NAN_MASK
__m256d const NAN_MASK = (__m256d)_mm256_set1_epi64x(NAN_MASK_D)
Definition at line 134 of file vdpow4.cpp.
nan_mask
__m256d nan_mask = _mm256_andnot_pd(ahi_lt_0, b_ne_trunc)
Definition at line 170 of file vdpow4.cpp.
NEG_ONE
__m256d const NEG_ONE = _mm256_set1_pd(NEG_ONE_D)
Definition at line 127 of file vdpow4.cpp.
NEG_ONE_CONST
__m256d const NEG_ONE_CONST = (__m256d)_mm256_set1_epi64x(NEG_ONE_CONST_D)
Definition at line 135 of file vdpow4.cpp.
ONE
__m256d const ONE = _mm256_set1_pd(ONE_D)
Definition at line 129 of file vdpow4.cpp.
Referenced by __fvd_pow_fma3_256(), and if().
prodx
__m256d __m256d const __m256d const __m256d __m256d prodx
Initial value:
{
    __m256d const UPPERBOUND_1 = (__m256d)_mm256_set1_epi64x(UPPERBOUND_1_D)
Definition at line 79 of file vdpow4.cpp.
Referenced by __fvd_pow_fma3_256().
res
res = (__m256d)_mm256_add_epi32(i_scale_acc, (__m256i)t)
Definition at line 107 of file vdpow4.cpp.
SGN_EXP_MASK
__m256d const SGN_EXP_MASK = (__m256d)_mm256_set1_epi64x(SGN_EXP_MASK_D)
Definition at line 125 of file vdpow4.cpp.
Referenced by __fvd_pow_fma3_256().
SGN_MASK
__m256d const SGN_MASK = (__m256d)_mm256_set1_epi64x(SGN_MASK_D)
Definition at line 131 of file vdpow4.cpp.
Referenced by neg().
shiftb
shiftb = (__m256i)_mm256_and_pd (b, SGN_EXP_MASK)
Definition at line 142 of file vdpow4.cpp.
slowpath_blend
__m256d slowpath_blend = _mm256_blendv_pd(zero_inf_blend, res, accurate_scale_mask)
Definition at line 110 of file vdpow4.cpp.
slowpath_mask
__m256d slowpath_mask = _mm256_cmp_pd(abs_lt, UPPERBOUND_1, _CMP_LT_OS)
Definition at line 92 of file vdpow4.cpp.
t
return t
Initial value:
{
   __m256i const HI_MASK       = _mm256_set1_epi64x(HI_MASK_D)
Definition at line 79 of file vdpow4.cpp.
Referenced by __fvd_pow_fma3_256(), __internal_ddfma(), and __internal_fast_int2dbl().
t_when_ais0
__m256d t_when_ais0 = _mm256_and_pd(thi_when_ais0, (__m256d)HI_MASK)
Definition at line 184 of file vdpow4.cpp.
TEN_23
__m256i const TEN_23 = _mm256_set1_epi64x(TEN_23_D)
Definition at line 137 of file vdpow4.cpp.
Referenced by __fvd_pow_fma3_256().
thi_or_INF
__m256d thi_or_INF = _mm256_or_pd(thi_when_ais0, INF)
Definition at line 182 of file vdpow4.cpp.
thi_when_ais0
thi_when_ais0 = ZERO
Definition at line 175 of file vdpow4.cpp.
thi_when_aisinf
thi_when_aisinf = _mm256_blendv_pd(thi_when_aisinf, INF, bhi_lt_0)
Definition at line 191 of file vdpow4.cpp.
thi_when_bisinf
thi_when_bisinf = ZERO
Definition at line 201 of file vdpow4.cpp.
thi_xor_inf
__m256d thi_xor_inf = _mm256_xor_pd(thi_when_bisinf, INF)
Definition at line 205 of file vdpow4.cpp.
thi_xor_sgn
__m256d thi_xor_sgn = _mm256_xor_pd(thi_when_aisinf, SGN_MASK)
Definition at line 194 of file vdpow4.cpp.
UPPERBOUND_2
__m256d const UPPERBOUND_2 = (__m256d)_mm256_set1_epi64x(UPPERBOUND_2_D)
Definition at line 82 of file vdpow4.cpp.
z
return z = _mm256_blendv_pd(slowpath_blend, z, slowpath_mask)
Definition at line 79 of file vdpow4.cpp.
Referenced by __fvd_pow_fma3_256(), __internal_ddadd_yisdouble(), and __internal_ddfma().
z_fixed
__m256d z_fixed = _mm256_fmadd_pd(z, prodx, z)
Definition at line 114 of file vdpow4.cpp.
ZERO
__m256d const ZERO = _mm256_set1_pd(ZERO_D)
Definition at line 83 of file vdpow4.cpp.
Referenced by __fvd_pow_fma3_256(), and if().
zero_inf_blend
__m256d zero_inf_blend = _mm256_blendv_pd(a_plus_inf, ZERO, lt_zero_mask)
Definition at line 95 of file vdpow4.cpp.