flang: verify.cpp File Reference
verify.cpp File Reference
#include "gbldefs.h"
#include "error.h"
#include "global.h"
#include "symtab.h"
#include "verify.h"
#include "ili.h"
#include "iliutil.h"
Classes
struct visit_info
Macros
#define VERIFY(cond, message) ((cond)?(void)0 : verify_failure(__LINE__, #cond, message))
Typedefs
typedef unsigned char epoch_t
Functions
static void verify_failure (int line, const char *cond, const char *message)
static void begin_walk (VERIFY_LEVEL level)
static void end_walk (VERIFY_LEVEL level)
static void ili_mark_first_visit (int ilix)
static visit_info * ili_visit_info (int ilix)
static bool is_known_bug (ILI_OP opc, int j, ILI_OP j_opc)
static void verify_compatible (ILI_OP opc, int j, ILI_OP j_opc)
static void verify_ili_ad_hoc (int ilix)
Ad-hoc operand checks.
static void verify_ili_aux (int ilix, ILIO_KIND context, VERIFY_LEVEL level)
void verify_ili (int ilix, VERIFY_LEVEL level)
void verify_ilt (int iltx, VERIFY_LEVEL level)
void verify_block (int bihx, VERIFY_LEVEL level)
void verify_function_ili (VERIFY_LEVEL level)
Variables
static visit_info * visited_ili
static int visited_size
static epoch_t current_epoch
static int walk_depth
Macro Definition Documentation
VERIFY
#define VERIFY (cond, message) ((cond)?(void)0 : verify_failure(__LINE__, #cond, message))
Definition at line 18 of file verify.cpp.
Typedef Documentation
epoch_t
typedef unsigned char epoch_t
Definition at line 29 of file verify.cpp.
Function Documentation
begin_walk()
static void begin_walk (VERIFY_LEVEL level) static
Definition at line 46 of file verify.cpp.
References current_epoch, i, level(), VERIFY_ILI_DEEP, visited_ili, visited_size, and walk_depth.
Referenced by verify_block(), verify_function_ili(), verify_ili(), and verify_ilt().
end_walk()
static void end_walk (VERIFY_LEVEL level) static
Definition at line 66 of file verify.cpp.
References level(), VERIFY, VERIFY_ILI_DEEP, and walk_depth.
Referenced by verify_block(), verify_function_ili(), verify_ili(), and verify_ilt().
ili_mark_first_visit()
static void ili_mark_first_visit (int ilix) static
Definition at line 75 of file verify.cpp.
References current_epoch, DEBUG_ASSERT, visit_info::epoch, i, NEED, VERIFY, visited_ili, visited_size, and walk_depth.
Referenced by verify_ili_aux().
ili_visit_info()
static visit_info * ili_visit_info (int ilix) static
NULL if ilix has not been visited yet.
Definition at line 99 of file verify.cpp.
References current_epoch, DEBUG_ASSERT, NULL, visited_ili, visited_size, and walk_depth.
Referenced by verify_ili_aux().
is_known_bug()
static bool is_known_bug (ILI_OP opc, int j, ILI_OP j_opc) static
Return true if jth operand of opc is allowed to have operation j_opc contrary to expectations of IL_OPRFLAG(opc, j). This routine is called infrequently so consider readability over speed when adding another case.
Definition at line 114 of file verify.cpp.
References IL_AADD, IL_IADD, IL_IDIV, IL_IMUL, IL_OPRFLAG, IL_RES, ILIA_AR, ILIA_CS, ILIA_IR, ILIA_KR, ILIO_ARLNK, ILIO_DPLNK, ILIO_IRLNK, ILIO_KRLNK, j, and r.
Referenced by verify_compatible().
verify_block()
void verify_block (int bihx, VERIFY_LEVEL level)
Definition at line 419 of file verify.cpp.
References begin_walk(), BIH_ILTFIRST, bihb, end_walk(), ILT_NEXT, level(), VERIFY, and verify_ilt().
Referenced by verify_function_ili().
verify_compatible()
static void verify_compatible (ILI_OP opc, int j, ILI_OP j_opc) static
Check that operation opc can have jth operand that has operation operand_opc.
Definition at line 184 of file verify.cpp.
References IL_OPRFLAG, IL_RES, ILIA_128, ILIA_256, ILIA_512, ILIA_AR, ILIA_CD, ILIA_CQ, ILIA_CS, ILIA_DOUBLEDOUBLE, ILIA_DP, ILIA_FLOAT128, ILIA_IR, ILIA_KR, ILIA_QP, ILIA_SP, ILIA_X87, ILIO_128LNK, ILIO_256LNK, ILIO_512LNK, ILIO_ARLNK, ILIO_CDLNK, ILIO_CQLNK, ILIO_CSLNK, ILIO_DOUBLEDOUBLELNK, ILIO_DPLNK, ILIO_FLOAT128LNK, ILIO_IRLNK, ILIO_KRLNK, ILIO_LNK, ILIO_QPLNK, ILIO_SPLNK, ILIO_X87LNK, is_known_bug(), j, r, and VERIFY.
Referenced by verify_ili_aux().
verify_failure()
static void verify_failure (int line, const char * cond, const char * message) static
Definition at line 22 of file verify.cpp.
References error_max_severity(), interr(), line, and XBIT.
verify_function_ili()
void verify_function_ili (VERIFY_LEVEL level)
Definition at line 432 of file verify.cpp.
References begin_walk(), BIH_NEXT, end_walk(), gbl, level(), and verify_block().
Referenced by expand().
verify_ili()
void verify_ili (int ilix, VERIFY_LEVEL level)
Definition at line 322 of file verify.cpp.
References begin_walk(), end_walk(), ILIO_LNK, level(), and verify_ili_aux().
Referenced by addili().
verify_ili_ad_hoc()
static void verify_ili_ad_hoc (int ilix) static
Ad-hoc operand checks.
This routine does ad-hoc checking of the operands that needs to be specific to an operation. This routine is called from verify_ili_aux after generic checks have been done.
Definition at line 254 of file verify.cpp.
References ILI_OPC, ILI_OPND, MSZ_F16, MSZ_F4, MSZ_F8, and VERIFY.
Referenced by verify_ili_aux().
verify_ili_aux()
static void verify_ili_aux (int ilix, ILIO_KIND context, VERIFY_LEVEL level) static
Recursive helper routine for verifying ILI. Because it is recursive, please try to keep it relatively uncluttered so that the control flow remains clear.
Definition at line 289 of file verify.cpp.
References IL_OPRFLAG, ili_mark_first_visit(), ILI_OPC, ILI_OPND, ili_visit_info(), ilib, ILIO_ISLINK, ilis, j, level(), operand, ILIINFO::oprs, VERIFY, verify_compatible(), verify_ili_ad_hoc(), verify_ili_aux(), VERIFY_ILI_DEEP, and VERIFY_ILI_SHALLOW.
Referenced by verify_ili(), verify_ili_aux(), and verify_ilt().
verify_ilt()
void verify_ilt (int iltx, VERIFY_LEVEL level)
Definition at line 359 of file verify.cpp.
References begin_walk(), end_walk(), flg, IL_TYPE, ILI_OPC, ili_throw_label(), ILIO_LNK, ILT_CAN_THROW, ILT_ILIP, ILT_NEXT, iltb, ILTY_PROC, ILTY_STORE, level(), FLG::opt, VERIFY, verify_ili_aux(), and VERIFY_ILT.
Referenced by verify_block().
Variable Documentation
current_epoch
epoch_t current_epoch static
Definition at line 39 of file verify.cpp.
Referenced by begin_walk(), ili_mark_first_visit(), and ili_visit_info().
visited_ili
visit_info* visited_ili static
Definition at line 37 of file verify.cpp.
Referenced by begin_walk(), ili_mark_first_visit(), and ili_visit_info().
visited_size
int visited_size static
Definition at line 38 of file verify.cpp.
Referenced by begin_walk(), ili_mark_first_visit(), and ili_visit_info().
walk_depth
int walk_depth static
Definition at line 40 of file verify.cpp.
Referenced by begin_walk(), end_walk(), ili_mark_first_visit(), and ili_visit_info().