flang: vspow8.cpp File Reference
vspow8.cpp File Reference
#include <immintrin.h>
#include "pow_defs.h"
Functions
__m256 __fvs_pow_fma3_256 (__m256 const, __m256 const)
__m256 __attribute__ ((noinline)) __pgm_pow_vec256_dp_special_cases(__m256 res_exp
if (a_is_neg_flag &&(!b_is_integer_flag))
if (a_is_any_zero_flag &&b_is_lt_zero_flag)
Variables
__m256 __m256 const a
__m256 __m256 const __m256 const b
__m256i pos_inf = _mm256_set1_epi32(D_POS_INF)
__m256i sign_mask = _mm256_set1_epi32(D_SIGN_MASK)
__m256i neg_inf = _mm256_set1_epi32(D_NEG_INF)
__m256i nan = _mm256_set1_epi32(D_NAN)
__m256i neg_nan = _mm256_set1_epi32(D_NEG_NAN)
__m256 MINUS_ONE_F_VEC = _mm256_set1_ps(D_MINUS_ONE_F)
__m256 MINUS_ZERO_F_VEC = _mm256_set1_ps(D_MINUS_ZERO_F)
__m256 const ONE_F_VEC = _mm256_set1_ps(D_ONE_F)
__m256 const ZERO_F_VEC = _mm256_setzero_ps()
__m256i b_is_nan = (__m256i)_mm256_cmp_ps(b, b, _CMP_NEQ_UQ)
__m256i a_is_nan = (__m256i)_mm256_cmp_ps(a,a, _CMP_NEQ_UQ)
__m256i a_is_neg = (__m256i)_mm256_cmp_ps(a, ZERO_F_VEC, _CMP_LT_OS)
int a_is_neg_flag = _mm256_movemask_epi8((__m256i)a_is_neg)
__m256i b_is_integer = (__m256i)_mm256_cmp_ps(b, _mm256_floor_ps(b), _CMP_EQ_OQ)
int b_is_integer_flag = _mm256_movemask_epi8((__m256i)b_is_integer)
__m256i b_is_odd_integer
__m256i b_is_even_integer
__m256i b_is_lt_zero = (__m256i)_mm256_cmp_ps(b, ZERO_F_VEC, _CMP_LT_OS)
int b_is_lt_zero_flag = _mm256_movemask_epi8((__m256i)b_is_lt_zero)
__m256i b_is_gt_zero = (__m256i)_mm256_cmp_ps(b, ZERO_F_VEC, _CMP_GT_OS)
__m256i b_is_odd_integer_lt_zero
__m256i b_is_odd_integer_gt_zero
__m256i change_sign_mask = _mm256_and_si256(a_is_neg, b_is_odd_integer)
__m256 changed_sign = _mm256_xor_ps(res_exp, (__m256)sign_mask)
res_exp = _mm256_or_ps(_mm256_and_ps((__m256)change_sign_mask, (__m256)changed_sign), _mm256_andnot_ps((__m256)change_sign_mask, res_exp))
__m256i return_neg_nan_mask = _mm256_andnot_si256(b_is_integer, a_is_neg)
__m256i return_nan_mask = _mm256_or_si256(b_is_nan, a_is_nan)
__m256 b_as_nan
__m256 a_as_nan
__m256 nan_to_return = _mm256_and_ps((__m256)b_is_nan, b_as_nan)
__m256i b_is_neg_inf = _mm256_cmpeq_epi32((__m256i)b, neg_inf)
__m256i b_is_pos_inf = _mm256_cmpeq_epi32((__m256i)b, pos_inf)
__m256i b_is_any_inf = _mm256_or_si256(b_is_pos_inf, b_is_neg_inf)
__m256i a_is_neg_inf = _mm256_cmpeq_epi32((__m256i)a, neg_inf)
__m256i a_is_pos_inf = _mm256_cmpeq_epi32((__m256i)a, pos_inf)
__m256i a_is_any_inf = _mm256_or_si256(a_is_pos_inf, a_is_neg_inf)
__m256i a_is_pos_zero = _mm256_cmpeq_epi32((__m256i)a, (__m256i)ZERO_F_VEC)
__m256i a_is_neg_zero = _mm256_cmpeq_epi32((__m256i)a, (__m256i)MINUS_ZERO_F_VEC)
__m256i a_is_any_zero = _mm256_or_si256(a_is_pos_zero, a_is_neg_zero)
int a_is_any_zero_flag = _mm256_movemask_epi8((__m256i)a_is_any_zero)
__m256i abs_a = _mm256_and_si256((__m256i)a, abs_mask)
__m256 abs_a_lt_one = _mm256_cmp_ps((__m256)abs_a, ONE_F_VEC, _CMP_LT_OS)
__m256 abs_a_gt_one = _mm256_cmp_ps((__m256)abs_a, ONE_F_VEC, _CMP_GT_OS)
__m256i a_is_one_mask = _mm256_cmpeq_epi32((__m256i)a, (__m256i)ONE_F_VEC)
__m256i a_is_minus_one_mask = _mm256_cmpeq_epi32((__m256i)a, (__m256i)MINUS_ONE_F_VEC)
__m256i return_1_mask = _mm256_or_si256(a_is_one_mask, (__m256i)_mm256_cmp_ps(b, ZERO_F_VEC, _CMP_EQ_OQ))
__m256i return_minus_1_mask = _mm256_and_si256(a_is_minus_one_mask, b_is_odd_integer)
__m256i return_neg_zero_mask
__m256i return_pos_zero_mask = _mm256_and_si256((__m256i)abs_a_gt_one, b_is_neg_inf)
__m256i return_neg_inf_mask = _mm256_and_si256(a_is_neg_inf, _mm256_and_si256(b_is_odd_integer, b_is_gt_zero))
__m256i return_pos_inf_mask = _mm256_and_si256((__m256i)abs_a_lt_one, b_is_neg_inf)
Function Documentation
__attribute__()
__m256 __attribute__ ((noinline))
References abs_mask, and D_SIGN_MASK2.
__fvs_pow_fma3_256()
__m256 __fvs_pow_fma3_256 (__m256 const a, __m256 const b)
Definition at line 176 of file vspow8.cpp.
References a, ALL_ONES_EXPONENT, b, D_ALL_ONES_EXPONENT, D_BIT_MASK2, D_EXP_OFFSET, D_OFFSET, D_ONE_F, D_SIGN_MASK2, D_TWO_TO_24_F, D_U24, DBL2INT_CVT, detect_inf_nan, EXP_C0, EXP_C1, EXP_C2, EXP_C3, EXP_C4, EXP_C5, EXP_C6, EXP_HI, EXP_LO, LOG_C0, LOG_C1, LOG_C10, LOG_C2, LOG_C3, LOG_C4, LOG_C5, LOG_C6, LOG_C7, LOG_C8, LOG_C9, m, offset, ONE_F_VEC, res, res_exp, and ZERO_F_VEC.
if() [1/2]
if (a_is_any_zero_flag && b_is_lt_zero_flag)
Definition at line 169 of file vspow8.cpp.
References ONE_F_VEC, and ZERO_F_VEC.
if() [2/2]
if (a_is_neg_flag && !b_is_integer_flag)
Definition at line 165 of file vspow8.cpp.
References a.
Variable Documentation
a
__m256 __m256 const a
Definition at line 20 of file vspow8.cpp.
Referenced by __fvs_pow_fma3_256(), and if().
a_as_nan
__m256 a_as_nan
Initial value:
= _mm256_or_ps(_mm256_and_ps(
                                                     (__m256)a_is_nan, _mm256_or_ps(a, (__m256)_mm256_set1_epi32(0x00400000))),
                                                     _mm256_andnot_ps((__m256)a_is_nan, res_exp))
Definition at line 76 of file vspow8.cpp.
a_is_any_inf
__m256i a_is_any_inf = _mm256_or_si256(a_is_pos_inf, a_is_neg_inf)
Definition at line 93 of file vspow8.cpp.
a_is_any_zero
__m256i a_is_any_zero = _mm256_or_si256(a_is_pos_zero, a_is_neg_zero)
Definition at line 97 of file vspow8.cpp.
a_is_any_zero_flag
int a_is_any_zero_flag = _mm256_movemask_epi8((__m256i)a_is_any_zero)
Definition at line 98 of file vspow8.cpp.
a_is_minus_one_mask
__m256i a_is_minus_one_mask = _mm256_cmpeq_epi32((__m256i)a, (__m256i)MINUS_ONE_F_VEC)
Definition at line 105 of file vspow8.cpp.
a_is_nan
__m256i a_is_nan = (__m256i)_mm256_cmp_ps(a,a, _CMP_NEQ_UQ)
Definition at line 35 of file vspow8.cpp.
a_is_neg
__m256i a_is_neg = (__m256i)_mm256_cmp_ps(a, ZERO_F_VEC, _CMP_LT_OS)
Definition at line 36 of file vspow8.cpp.
a_is_neg_flag
int a_is_neg_flag = _mm256_movemask_epi8((__m256i)a_is_neg)
Definition at line 37 of file vspow8.cpp.
a_is_neg_inf
__m256i a_is_neg_inf = _mm256_cmpeq_epi32((__m256i)a, neg_inf)
Definition at line 91 of file vspow8.cpp.
a_is_neg_zero
__m256i a_is_neg_zero = _mm256_cmpeq_epi32((__m256i)a, (__m256i)MINUS_ZERO_F_VEC)
Definition at line 96 of file vspow8.cpp.
a_is_one_mask
__m256i a_is_one_mask = _mm256_cmpeq_epi32((__m256i)a, (__m256i)ONE_F_VEC)
Definition at line 104 of file vspow8.cpp.
a_is_pos_inf
__m256i a_is_pos_inf = _mm256_cmpeq_epi32((__m256i)a, pos_inf)
Definition at line 92 of file vspow8.cpp.
a_is_pos_zero
__m256i a_is_pos_zero = _mm256_cmpeq_epi32((__m256i)a, (__m256i)ZERO_F_VEC)
Definition at line 95 of file vspow8.cpp.
abs_a
__m256i abs_a = _mm256_and_si256((__m256i)a, abs_mask)
Definition at line 100 of file vspow8.cpp.
abs_a_gt_one
__m256 abs_a_gt_one = _mm256_cmp_ps((__m256)abs_a, ONE_F_VEC, _CMP_GT_OS)
Definition at line 102 of file vspow8.cpp.
abs_a_lt_one
__m256 abs_a_lt_one = _mm256_cmp_ps((__m256)abs_a, ONE_F_VEC, _CMP_LT_OS)
Definition at line 101 of file vspow8.cpp.
b
__m256 __m256 const __m256 const b
Initial value:
{
      __m256i abs_mask = _mm256_set1_epi32(D_SIGN_MASK2)
Definition at line 20 of file vspow8.cpp.
Referenced by __fvs_pow_fma3_256().
b_as_nan
__m256 b_as_nan
Initial value:
= _mm256_or_ps(_mm256_and_ps(
                                                     (__m256)b_is_nan, _mm256_or_ps(b, (__m256)_mm256_set1_epi32(0x00400000))),
                                                     _mm256_andnot_ps((__m256)b_is_nan, res_exp))
Definition at line 72 of file vspow8.cpp.
b_is_any_inf
__m256i b_is_any_inf = _mm256_or_si256(b_is_pos_inf, b_is_neg_inf)
Definition at line 89 of file vspow8.cpp.
b_is_even_integer
__m256i b_is_even_integer
Initial value:
= _mm256_and_si256(b_is_integer,
                                                  _mm256_cmpeq_epi32(
                                                                     _mm256_and_si256(_mm256_cvtps_epi32(b), _mm256_set1_epi32(0x1)),
                                                                     _mm256_set1_epi32(0x0)))
Definition at line 47 of file vspow8.cpp.
b_is_gt_zero
__m256i b_is_gt_zero = (__m256i)_mm256_cmp_ps(b, ZERO_F_VEC, _CMP_GT_OS)
Definition at line 55 of file vspow8.cpp.
b_is_integer
__m256i b_is_integer = (__m256i)_mm256_cmp_ps(b, _mm256_floor_ps(b), _CMP_EQ_OQ)
Definition at line 39 of file vspow8.cpp.
b_is_integer_flag
int b_is_integer_flag = _mm256_movemask_epi8((__m256i)b_is_integer)
Definition at line 40 of file vspow8.cpp.
b_is_lt_zero
__m256i b_is_lt_zero = (__m256i)_mm256_cmp_ps(b, ZERO_F_VEC, _CMP_LT_OS)
Definition at line 52 of file vspow8.cpp.
b_is_lt_zero_flag
int b_is_lt_zero_flag = _mm256_movemask_epi8((__m256i)b_is_lt_zero)
Definition at line 53 of file vspow8.cpp.
b_is_nan
__m256i b_is_nan = (__m256i)_mm256_cmp_ps(b, b, _CMP_NEQ_UQ)
Definition at line 34 of file vspow8.cpp.
b_is_neg_inf
__m256i b_is_neg_inf = _mm256_cmpeq_epi32((__m256i)b, neg_inf)
Definition at line 87 of file vspow8.cpp.
b_is_odd_integer
__m256i b_is_odd_integer
Initial value:
= _mm256_and_si256(b_is_integer,
                                                  _mm256_cmpeq_epi32(
                                                                     _mm256_and_si256(_mm256_cvtps_epi32(b), _mm256_set1_epi32(0x1)),
                                                                     _mm256_set1_epi32(0x1)))
Definition at line 42 of file vspow8.cpp.
b_is_odd_integer_gt_zero
__m256i b_is_odd_integer_gt_zero
Initial value:
= _mm256_and_si256(b_is_integer,
                                                           (__m256i)_mm256_cmp_ps(b, ZERO_F_VEC, _CMP_GT_OS))
Definition at line 60 of file vspow8.cpp.
b_is_odd_integer_lt_zero
__m256i b_is_odd_integer_lt_zero
Initial value:
= _mm256_and_si256(b_is_integer,
                                                           (__m256i)_mm256_cmp_ps(b, ZERO_F_VEC, _CMP_LT_OS))
Definition at line 57 of file vspow8.cpp.
b_is_pos_inf
__m256i b_is_pos_inf = _mm256_cmpeq_epi32((__m256i)b, pos_inf)
Definition at line 88 of file vspow8.cpp.
change_sign_mask
__m256i change_sign_mask = _mm256_and_si256(a_is_neg, b_is_odd_integer)
Definition at line 63 of file vspow8.cpp.
changed_sign
__m256 changed_sign = _mm256_xor_ps(res_exp, (__m256)sign_mask)
Definition at line 64 of file vspow8.cpp.
MINUS_ONE_F_VEC
__m256 MINUS_ONE_F_VEC = _mm256_set1_ps(D_MINUS_ONE_F)
Definition at line 28 of file vspow8.cpp.
MINUS_ZERO_F_VEC
__m256 MINUS_ZERO_F_VEC = _mm256_set1_ps(D_MINUS_ZERO_F)
Definition at line 29 of file vspow8.cpp.
nan
__m256i nan = _mm256_set1_epi32(D_NAN)
Definition at line 26 of file vspow8.cpp.
nan_to_return
nan_to_return = _mm256_and_ps((__m256)b_is_nan, b_as_nan)
Definition at line 80 of file vspow8.cpp.
neg_inf
__m256i neg_inf = _mm256_set1_epi32(D_NEG_INF)
Definition at line 25 of file vspow8.cpp.
neg_nan
__m256i neg_nan = _mm256_set1_epi32(D_NEG_NAN)
Definition at line 27 of file vspow8.cpp.
ONE_F_VEC
__m256 const ONE_F_VEC = _mm256_set1_ps(D_ONE_F)
Definition at line 30 of file vspow8.cpp.
Referenced by __fvs_pow_fma3_256(), and if().
pos_inf
__m256i pos_inf = _mm256_set1_epi32(D_POS_INF)
Definition at line 23 of file vspow8.cpp.
res_exp
return res_exp = _mm256_or_ps(_mm256_and_ps((__m256)change_sign_mask, (__m256)changed_sign), _mm256_andnot_ps((__m256)change_sign_mask, res_exp))
Definition at line 65 of file vspow8.cpp.
Referenced by __fvs_pow_fma3_256().
return_1_mask
return_1_mask = _mm256_or_si256(a_is_one_mask, (__m256i)_mm256_cmp_ps(b, ZERO_F_VEC, _CMP_EQ_OQ))
Definition at line 107 of file vspow8.cpp.
return_minus_1_mask
__m256i return_minus_1_mask = _mm256_and_si256(a_is_minus_one_mask, b_is_odd_integer)
Definition at line 115 of file vspow8.cpp.
return_nan_mask
__m256i return_nan_mask = _mm256_or_si256(b_is_nan, a_is_nan)
Definition at line 70 of file vspow8.cpp.
return_neg_inf_mask
return_neg_inf_mask = _mm256_and_si256(a_is_neg_inf, _mm256_and_si256(b_is_odd_integer, b_is_gt_zero))
Definition at line 138 of file vspow8.cpp.
return_neg_nan_mask
__m256i return_neg_nan_mask = _mm256_andnot_si256(b_is_integer, a_is_neg)
Definition at line 67 of file vspow8.cpp.
return_neg_zero_mask
return_neg_zero_mask
Initial value:
= _mm256_and_si256(a_is_neg_inf,
                                                      b_is_odd_integer_lt_zero)
Definition at line 120 of file vspow8.cpp.
return_pos_inf_mask
return_pos_inf_mask = _mm256_and_si256((__m256i)abs_a_lt_one, b_is_neg_inf)
Definition at line 144 of file vspow8.cpp.
return_pos_zero_mask
return_pos_zero_mask = _mm256_and_si256((__m256i)abs_a_gt_one, b_is_neg_inf)
Definition at line 128 of file vspow8.cpp.
sign_mask
__m256i sign_mask = _mm256_set1_epi32(D_SIGN_MASK)
Definition at line 24 of file vspow8.cpp.
ZERO_F_VEC
__m256 const ZERO_F_VEC = _mm256_setzero_ps()
Definition at line 31 of file vspow8.cpp.
Referenced by __fvs_pow_fma3_256(), and if().