flang: vspow16.cpp File Reference
vspow16.cpp File Reference
#include <immintrin.h>
#include "mth_avx512helper.h"
#include "pow_defs.h"
Functions
__m512 FCN_AVX512() __fvs_pow_fma3 (__m512 const, __m512 const)
static __m512 __attribute__ ((noinline)) __pgm_pow_vec512_dp_special_cases(__m512 res_exp
if (a_is_neg_flag &&(!b_is_integer_flag))
if (a_is_any_zero_flag &&b_is_lt_zero_flag)
Variables
static __m512 __m512 const a
static __m512 __m512 const __m512 const b
__m512i pos_inf = _mm512_set1_epi32(D_POS_INF)
__m512i sign_mask = _mm512_set1_epi32(D_SIGN_MASK)
__m512i neg_inf = _mm512_set1_epi32(D_NEG_INF)
__m512i nan = _mm512_set1_epi32(D_NAN)
__m512i neg_nan = _mm512_set1_epi32(D_NEG_NAN)
__m512 MINUS_ONE_F_VEC = _mm512_set1_ps(D_MINUS_ONE_F)
__m512 MINUS_ZERO_F_VEC = _mm512_set1_ps(D_MINUS_ZERO_F)
__m512 const ONE_F_VEC = _mm512_set1_ps(D_ONE_F)
__m512 const ZERO_F_VEC = _mm512_setzero_ps()
__m512i b_is_nan = (__m512i)_MM512_CMP_PS(b, b, _CMP_NEQ_UQ)
__m512i a_is_nan = (__m512i)_MM512_CMP_PS(a,a, _CMP_NEQ_UQ)
__m512i a_is_neg = (__m512i)_MM512_CMP_PS(a, ZERO_F_VEC, _CMP_LT_OS)
int a_is_neg_flag = _MM512_MOVEMASK_PS(_mm512_castsi512_ps(a_is_neg))
__m512i b_is_integer = (__m512i)_MM512_CMP_PS(b, _mm512_floor_ps(b), _CMP_EQ_OQ)
int b_is_integer_flag = _MM512_MOVEMASK_PS(_mm512_castsi512_ps(b_is_integer))
__m512i b_is_odd_integer
__m512i b_is_even_integer
__m512i b_is_lt_zero = (__m512i)_MM512_CMP_PS(b, ZERO_F_VEC, _CMP_LT_OS)
int b_is_lt_zero_flag = _MM512_MOVEMASK_PS(_mm512_castsi512_ps(b_is_lt_zero))
__m512i b_is_gt_zero = (__m512i)_MM512_CMP_PS(b, ZERO_F_VEC, _CMP_GT_OS)
__m512i b_is_odd_integer_lt_zero
__m512i b_is_odd_integer_gt_zero
__m512i change_sign_mask = _mm512_and_si512(a_is_neg, b_is_odd_integer)
__m512 changed_sign = _MM512_XOR_PS(res_exp, (__m512)sign_mask)
res_exp = _MM512_OR_PS(_MM512_AND_PS((__m512)change_sign_mask, (__m512)changed_sign), _MM512_ANDNOT_PS((__m512)change_sign_mask, res_exp))
__m512i return_neg_nan_mask = _mm512_andnot_si512(b_is_integer, a_is_neg)
__m512i return_nan_mask = _mm512_or_si512(b_is_nan, a_is_nan)
__m512 b_as_nan
__m512 a_as_nan
__m512 nan_to_return = _MM512_AND_PS((__m512)b_is_nan, b_as_nan)
__m512i b_is_neg_inf = _MM512_CMPEQ_EPI32((__m512i)b, neg_inf)
__m512i b_is_pos_inf = _MM512_CMPEQ_EPI32((__m512i)b, pos_inf)
__m512i b_is_any_inf = _mm512_or_si512(b_is_pos_inf, b_is_neg_inf)
__m512i a_is_neg_inf = _MM512_CMPEQ_EPI32((__m512i)a, neg_inf)
__m512i a_is_pos_inf = _MM512_CMPEQ_EPI32((__m512i)a, pos_inf)
__m512i a_is_any_inf = _mm512_or_si512(a_is_pos_inf, a_is_neg_inf)
__m512i a_is_pos_zero = _MM512_CMPEQ_EPI32((__m512i)a, (__m512i)ZERO_F_VEC)
__m512i a_is_neg_zero = _MM512_CMPEQ_EPI32((__m512i)a, (__m512i)MINUS_ZERO_F_VEC)
__m512i a_is_any_zero = _mm512_or_si512(a_is_pos_zero, a_is_neg_zero)
int a_is_any_zero_flag = _MM512_MOVEMASK_PS(_mm512_castsi512_ps(a_is_any_zero))
__m512i abs_a = _mm512_and_si512((__m512i)a, abs_mask)
__m512 abs_a_lt_one = _MM512_CMP_PS((__m512)abs_a, ONE_F_VEC, _CMP_LT_OS)
__m512 abs_a_gt_one = _MM512_CMP_PS((__m512)abs_a, ONE_F_VEC, _CMP_GT_OS)
__m512i a_is_one_mask = _MM512_CMPEQ_EPI32((__m512i)a, (__m512i)ONE_F_VEC)
__m512i a_is_minus_one_mask = _MM512_CMPEQ_EPI32((__m512i)a, (__m512i)MINUS_ONE_F_VEC)
__m512i return_1_mask = _mm512_or_si512(a_is_one_mask, (__m512i)_MM512_CMP_PS(b, ZERO_F_VEC, _CMP_EQ_OQ))
__m512i return_minus_1_mask = _mm512_and_si512(a_is_minus_one_mask, b_is_odd_integer)
__m512i return_neg_zero_mask
__m512i return_pos_zero_mask = _mm512_and_si512((__m512i)abs_a_gt_one, b_is_neg_inf)
__m512i return_neg_inf_mask = _mm512_and_si512(a_is_neg_inf, _mm512_and_si512(b_is_odd_integer, b_is_gt_zero))
__m512i return_pos_inf_mask = _mm512_and_si512((__m512i)abs_a_lt_one, b_is_neg_inf)
Function Documentation
__attribute__()
static __m512 __attribute__ ((noinline)) static
References abs_mask, and D_SIGN_MASK2.
__fvs_pow_fma3()
__m512 FCN_AVX512() __fvs_pow_fma3 (__m512 const a, __m512 const b)
Definition at line 177 of file vspow16.cpp.
References _MM512_AND_PS, _MM512_ANDNOT_PS, _MM512_CMP_PS, _MM512_CMPEQ_EPI32, _MM512_EXTRACTF256_PS, _MM512_EXTRACTI256_SI512, _MM512_INSERTF256_PS, _MM512_MOVEMASK_PS, _MM512_OR_PS, a, ALL_ONES_EXPONENT, b, D_ALL_ONES_EXPONENT, D_BIT_MASK2, D_EXP_OFFSET, D_OFFSET, D_ONE_F, D_SIGN_MASK2, D_TWO_TO_24_F, D_U24, DBL2INT_CVT, detect_inf_nan, EXP_C0, EXP_C1, EXP_C2, EXP_C3, EXP_C4, EXP_C5, EXP_C6, EXP_HI, EXP_LO, LOG_C0, LOG_C1, LOG_C10, LOG_C2, LOG_C3, LOG_C4, LOG_C5, LOG_C6, LOG_C7, LOG_C8, LOG_C9, m, offset, ONE_F_VEC, res, res_exp, and ZERO_F_VEC.
if() [1/2]
if (a_is_any_zero_flag && b_is_lt_zero_flag)
Definition at line 170 of file vspow16.cpp.
References ONE_F_VEC, and ZERO_F_VEC.
if() [2/2]
if (a_is_neg_flag && !b_is_integer_flag)
Definition at line 166 of file vspow16.cpp.
References a.
Variable Documentation
a
__m512 __m512 const a
Definition at line 21 of file vspow16.cpp.
Referenced by __fvs_pow_fma3(), and if().
a_as_nan
__m512 a_as_nan
Initial value:
= _MM512_OR_PS(_MM512_AND_PS(
                                                     (__m512)a_is_nan, _MM512_OR_PS(a, (__m512)_mm512_set1_epi32(0x00400000))),
                                                     _MM512_ANDNOT_PS((__m512)a_is_nan, res_exp))
Definition at line 77 of file vspow16.cpp.
a_is_any_inf
__m512i a_is_any_inf = _mm512_or_si512(a_is_pos_inf, a_is_neg_inf)
Definition at line 94 of file vspow16.cpp.
a_is_any_zero
__m512i a_is_any_zero = _mm512_or_si512(a_is_pos_zero, a_is_neg_zero)
Definition at line 98 of file vspow16.cpp.
a_is_any_zero_flag
int a_is_any_zero_flag = _MM512_MOVEMASK_PS(_mm512_castsi512_ps(a_is_any_zero))
Definition at line 99 of file vspow16.cpp.
a_is_minus_one_mask
__m512i a_is_minus_one_mask = _MM512_CMPEQ_EPI32((__m512i)a, (__m512i)MINUS_ONE_F_VEC)
Definition at line 106 of file vspow16.cpp.
a_is_nan
__m512i a_is_nan = (__m512i)_MM512_CMP_PS(a,a, _CMP_NEQ_UQ)
Definition at line 36 of file vspow16.cpp.
a_is_neg
__m512i a_is_neg = (__m512i)_MM512_CMP_PS(a, ZERO_F_VEC, _CMP_LT_OS)
Definition at line 37 of file vspow16.cpp.
a_is_neg_flag
int a_is_neg_flag = _MM512_MOVEMASK_PS(_mm512_castsi512_ps(a_is_neg))
Definition at line 38 of file vspow16.cpp.
a_is_neg_inf
__m512i a_is_neg_inf = _MM512_CMPEQ_EPI32((__m512i)a, neg_inf)
Definition at line 92 of file vspow16.cpp.
a_is_neg_zero
__m512i a_is_neg_zero = _MM512_CMPEQ_EPI32((__m512i)a, (__m512i)MINUS_ZERO_F_VEC)
Definition at line 97 of file vspow16.cpp.
a_is_one_mask
__m512i a_is_one_mask = _MM512_CMPEQ_EPI32((__m512i)a, (__m512i)ONE_F_VEC)
Definition at line 105 of file vspow16.cpp.
a_is_pos_inf
__m512i a_is_pos_inf = _MM512_CMPEQ_EPI32((__m512i)a, pos_inf)
Definition at line 93 of file vspow16.cpp.
a_is_pos_zero
__m512i a_is_pos_zero = _MM512_CMPEQ_EPI32((__m512i)a, (__m512i)ZERO_F_VEC)
Definition at line 96 of file vspow16.cpp.
abs_a
__m512i abs_a = _mm512_and_si512((__m512i)a, abs_mask)
Definition at line 101 of file vspow16.cpp.
abs_a_gt_one
__m512 abs_a_gt_one = _MM512_CMP_PS((__m512)abs_a, ONE_F_VEC, _CMP_GT_OS)
Definition at line 103 of file vspow16.cpp.
abs_a_lt_one
__m512 abs_a_lt_one = _MM512_CMP_PS((__m512)abs_a, ONE_F_VEC, _CMP_LT_OS)
Definition at line 102 of file vspow16.cpp.
b
__m512 __m512 const __m512 const b
Initial value:
{
      __m512i abs_mask = _mm512_set1_epi32(D_SIGN_MASK2)
Definition at line 21 of file vspow16.cpp.
Referenced by __fvs_pow_fma3().
b_as_nan
__m512 b_as_nan
Initial value:
= _MM512_OR_PS(_MM512_AND_PS(
                                                     (__m512)b_is_nan, _MM512_OR_PS(b, (__m512)_mm512_set1_epi32(0x00400000))),
                                                     _MM512_ANDNOT_PS((__m512)b_is_nan, res_exp))
Definition at line 73 of file vspow16.cpp.
b_is_any_inf
__m512i b_is_any_inf = _mm512_or_si512(b_is_pos_inf, b_is_neg_inf)
Definition at line 90 of file vspow16.cpp.
b_is_even_integer
__m512i b_is_even_integer
Initial value:
= _mm512_and_si512(b_is_integer,
                                                  _MM512_CMPEQ_EPI32(
                                                                     _mm512_and_si512(_mm512_cvtps_epi32(b), _mm512_set1_epi32(0x1)),
                                                                     _mm512_set1_epi32(0x0)))
Definition at line 48 of file vspow16.cpp.
b_is_gt_zero
__m512i b_is_gt_zero = (__m512i)_MM512_CMP_PS(b, ZERO_F_VEC, _CMP_GT_OS)
Definition at line 56 of file vspow16.cpp.
b_is_integer
__m512i b_is_integer = (__m512i)_MM512_CMP_PS(b, _mm512_floor_ps(b), _CMP_EQ_OQ)
Definition at line 40 of file vspow16.cpp.
b_is_integer_flag
int b_is_integer_flag = _MM512_MOVEMASK_PS(_mm512_castsi512_ps(b_is_integer))
Definition at line 41 of file vspow16.cpp.
b_is_lt_zero
__m512i b_is_lt_zero = (__m512i)_MM512_CMP_PS(b, ZERO_F_VEC, _CMP_LT_OS)
Definition at line 53 of file vspow16.cpp.
b_is_lt_zero_flag
int b_is_lt_zero_flag = _MM512_MOVEMASK_PS(_mm512_castsi512_ps(b_is_lt_zero))
Definition at line 54 of file vspow16.cpp.
b_is_nan
__m512i b_is_nan = (__m512i)_MM512_CMP_PS(b, b, _CMP_NEQ_UQ)
Definition at line 35 of file vspow16.cpp.
b_is_neg_inf
__m512i b_is_neg_inf = _MM512_CMPEQ_EPI32((__m512i)b, neg_inf)
Definition at line 88 of file vspow16.cpp.
b_is_odd_integer
__m512i b_is_odd_integer
Initial value:
= _mm512_and_si512(b_is_integer,
                                                  _MM512_CMPEQ_EPI32(
                                                                     _mm512_and_si512(_mm512_cvtps_epi32(b), _mm512_set1_epi32(0x1)),
                                                                     _mm512_set1_epi32(0x1)))
Definition at line 43 of file vspow16.cpp.
b_is_odd_integer_gt_zero
__m512i b_is_odd_integer_gt_zero
Initial value:
= _mm512_and_si512(b_is_integer,
                                                           (__m512i)_MM512_CMP_PS(b, ZERO_F_VEC, _CMP_GT_OS))
Definition at line 61 of file vspow16.cpp.
b_is_odd_integer_lt_zero
__m512i b_is_odd_integer_lt_zero
Initial value:
= _mm512_and_si512(b_is_integer,
                                                           (__m512i)_MM512_CMP_PS(b, ZERO_F_VEC, _CMP_LT_OS))
Definition at line 58 of file vspow16.cpp.
b_is_pos_inf
__m512i b_is_pos_inf = _MM512_CMPEQ_EPI32((__m512i)b, pos_inf)
Definition at line 89 of file vspow16.cpp.
change_sign_mask
__m512i change_sign_mask = _mm512_and_si512(a_is_neg, b_is_odd_integer)
Definition at line 64 of file vspow16.cpp.
changed_sign
__m512 changed_sign = _MM512_XOR_PS(res_exp, (__m512)sign_mask)
Definition at line 65 of file vspow16.cpp.
MINUS_ONE_F_VEC
__m512 MINUS_ONE_F_VEC = _mm512_set1_ps(D_MINUS_ONE_F)
Definition at line 29 of file vspow16.cpp.
MINUS_ZERO_F_VEC
__m512 MINUS_ZERO_F_VEC = _mm512_set1_ps(D_MINUS_ZERO_F)
Definition at line 30 of file vspow16.cpp.
nan
__m512i nan = _mm512_set1_epi32(D_NAN)
Definition at line 27 of file vspow16.cpp.
nan_to_return
nan_to_return = _MM512_AND_PS((__m512)b_is_nan, b_as_nan)
Definition at line 81 of file vspow16.cpp.
neg_inf
__m512i neg_inf = _mm512_set1_epi32(D_NEG_INF)
Definition at line 26 of file vspow16.cpp.
neg_nan
__m512i neg_nan = _mm512_set1_epi32(D_NEG_NAN)
Definition at line 28 of file vspow16.cpp.
ONE_F_VEC
__m512 const ONE_F_VEC = _mm512_set1_ps(D_ONE_F)
Definition at line 31 of file vspow16.cpp.
Referenced by __fvs_pow_fma3(), and if().
pos_inf
__m512i pos_inf = _mm512_set1_epi32(D_POS_INF)
Definition at line 24 of file vspow16.cpp.
res_exp
return res_exp = _MM512_OR_PS(_MM512_AND_PS((__m512)change_sign_mask, (__m512)changed_sign), _MM512_ANDNOT_PS((__m512)change_sign_mask, res_exp))
Definition at line 66 of file vspow16.cpp.
Referenced by __fvs_pow_fma3().
return_1_mask
return_1_mask = _mm512_or_si512(a_is_one_mask, (__m512i)_MM512_CMP_PS(b, ZERO_F_VEC, _CMP_EQ_OQ))
Definition at line 108 of file vspow16.cpp.
return_minus_1_mask
__m512i return_minus_1_mask = _mm512_and_si512(a_is_minus_one_mask, b_is_odd_integer)
Definition at line 116 of file vspow16.cpp.
return_nan_mask
__m512i return_nan_mask = _mm512_or_si512(b_is_nan, a_is_nan)
Definition at line 71 of file vspow16.cpp.
return_neg_inf_mask
return_neg_inf_mask = _mm512_and_si512(a_is_neg_inf, _mm512_and_si512(b_is_odd_integer, b_is_gt_zero))
Definition at line 139 of file vspow16.cpp.
return_neg_nan_mask
__m512i return_neg_nan_mask = _mm512_andnot_si512(b_is_integer, a_is_neg)
Definition at line 68 of file vspow16.cpp.
return_neg_zero_mask
return_neg_zero_mask
Initial value:
= _mm512_and_si512(a_is_neg_inf,
                                                      b_is_odd_integer_lt_zero)
Definition at line 121 of file vspow16.cpp.
return_pos_inf_mask
return_pos_inf_mask = _mm512_and_si512((__m512i)abs_a_lt_one, b_is_neg_inf)
Definition at line 145 of file vspow16.cpp.
return_pos_zero_mask
return_pos_zero_mask = _mm512_and_si512((__m512i)abs_a_gt_one, b_is_neg_inf)
Definition at line 129 of file vspow16.cpp.
sign_mask
__m512i sign_mask = _mm512_set1_epi32(D_SIGN_MASK)
Definition at line 25 of file vspow16.cpp.
ZERO_F_VEC
__m512 const ZERO_F_VEC = _mm512_setzero_ps()
Definition at line 32 of file vspow16.cpp.
Referenced by __fvs_pow_fma3(), and if().