flang: vspow4.cpp File Reference
vspow4.cpp File Reference
#include <immintrin.h>
#include "pow_defs.h"
Functions
__m128 __fvs_pow_fma3 (__m128 const, __m128 const)
__m128 __attribute__ ((noinline)) __pgm_pow_vec128_dp_special_cases(__m128 res_exp
if (a_is_neg_flag &&(!b_is_integer_flag))
if (a_is_any_zero_flag &&b_is_lt_zero_flag)
Variables
__m128 __m128 const a
__m128 __m128 const __m128 const b
__m128i pos_inf = _mm_set1_epi32(D_POS_INF)
__m128i sign_mask = _mm_set1_epi32(D_SIGN_MASK)
__m128i neg_inf = _mm_set1_epi32(D_NEG_INF)
__m128i nan = _mm_set1_epi32(D_NAN)
__m128i neg_nan = _mm_set1_epi32(D_NEG_NAN)
__m128 MINUS_ONE_F_VEC = _mm_set1_ps(D_MINUS_ONE_F)
__m128 MINUS_ZERO_F_VEC = _mm_set1_ps(D_MINUS_ZERO_F)
__m128 const ONE_F_VEC = _mm_set1_ps(D_ONE_F)
__m128 const ZERO_F_VEC = _mm_setzero_ps()
__m128i b_is_nan = (__m128i)_mm_cmp_ps(b, b, _CMP_NEQ_UQ)
__m128i a_is_nan = (__m128i)_mm_cmp_ps(a,a, _CMP_NEQ_UQ)
__m128i a_is_neg = (__m128i)_mm_cmp_ps(a, ZERO_F_VEC, _CMP_LT_OS)
int a_is_neg_flag = _mm_movemask_epi8((__m128i)a_is_neg)
__m128i b_is_integer = (__m128i)_mm_cmp_ps(b, _mm_floor_ps(b), _CMP_EQ_OQ)
int b_is_integer_flag = _mm_movemask_epi8((__m128i)b_is_integer)
__m128i b_is_odd_integer
__m128i b_is_even_integer
__m128i b_is_lt_zero = (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_LT_OS)
int b_is_lt_zero_flag = _mm_movemask_epi8((__m128i)b_is_lt_zero)
__m128i b_is_gt_zero = (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_GT_OS)
__m128i b_is_odd_integer_lt_zero
__m128i b_is_odd_integer_gt_zero
__m128i change_sign_mask = _mm_and_si128(a_is_neg, b_is_odd_integer)
__m128 changed_sign = _mm_xor_ps(res_exp, (__m128)sign_mask)
res_exp = _mm_or_ps(_mm_and_ps((__m128)change_sign_mask, (__m128)changed_sign), _mm_andnot_ps((__m128)change_sign_mask, res_exp))
__m128i return_neg_nan_mask = _mm_andnot_si128(b_is_integer, a_is_neg)
__m128i return_nan_mask = _mm_or_si128(b_is_nan, a_is_nan)
__m128 b_as_nan
__m128 a_as_nan
__m128 nan_to_return = _mm_and_ps((__m128)b_is_nan, b_as_nan)
__m128i b_is_neg_inf = _mm_cmpeq_epi32((__m128i)b, neg_inf)
__m128i b_is_pos_inf = _mm_cmpeq_epi32((__m128i)b, pos_inf)
__m128i b_is_any_inf = _mm_or_si128(b_is_pos_inf, b_is_neg_inf)
__m128i a_is_neg_inf = _mm_cmpeq_epi32((__m128i)a, neg_inf)
__m128i a_is_pos_inf = _mm_cmpeq_epi32((__m128i)a, pos_inf)
__m128i a_is_any_inf = _mm_or_si128(a_is_pos_inf, a_is_neg_inf)
__m128i a_is_pos_zero = _mm_cmpeq_epi32((__m128i)a, (__m128i)ZERO_F_VEC)
__m128i a_is_neg_zero = _mm_cmpeq_epi32((__m128i)a, (__m128i)MINUS_ZERO_F_VEC)
__m128i a_is_any_zero = _mm_or_si128(a_is_pos_zero, a_is_neg_zero)
int a_is_any_zero_flag = _mm_movemask_epi8((__m128i)a_is_any_zero)
__m128i abs_a = _mm_and_si128((__m128i)a, abs_mask)
__m128 abs_a_lt_one = _mm_cmp_ps((__m128)abs_a, ONE_F_VEC, _CMP_LT_OS)
__m128 abs_a_gt_one = _mm_cmp_ps((__m128)abs_a, ONE_F_VEC, _CMP_GT_OS)
__m128i a_is_one_mask = _mm_cmpeq_epi32((__m128i)a, (__m128i)ONE_F_VEC)
__m128i a_is_minus_one_mask = _mm_cmpeq_epi32((__m128i)a, (__m128i)MINUS_ONE_F_VEC)
__m128i return_1_mask = _mm_or_si128(a_is_one_mask, (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_EQ_OQ))
__m128i return_minus_1_mask = _mm_and_si128(a_is_minus_one_mask, b_is_odd_integer)
__m128i return_neg_zero_mask
__m128i return_pos_zero_mask = _mm_and_si128((__m128i)abs_a_gt_one, b_is_neg_inf)
__m128i return_neg_inf_mask = _mm_and_si128(a_is_neg_inf, _mm_and_si128(b_is_odd_integer, b_is_gt_zero))
__m128i return_pos_inf_mask = _mm_and_si128((__m128i)abs_a_lt_one, b_is_neg_inf)
Function Documentation
__attribute__()
__m128 __attribute__ ((noinline))
References abs_mask, and D_ABS_MASK.
__fvs_pow_fma3()
__m128 __fvs_pow_fma3 (__m128 const a, __m128 const b)
Definition at line 225 of file vspow4.cpp.
References a, ALL_ONES_EXPONENT, b, D_ALL_ONES_EXPONENT, D_BIT_MASK2, D_EXP_OFFSET, D_OFFSET, D_ONE_F, D_SIGN_MASK2, D_TWO_TO_24_F, D_U24, DBL2INT_CVT, detect_inf_nan, e, EXP_C0, EXP_C1, EXP_C2, EXP_C3, EXP_C4, EXP_C5, EXP_C6, EXP_HI, EXP_LO, LOG_C0, LOG_C1, LOG_C10, LOG_C2, LOG_C3, LOG_C4, LOG_C5, LOG_C6, LOG_C7, LOG_C8, LOG_C9, m, m2, m4, offset, ONE_F_VEC, res, res_exp, t, and ZERO_F_VEC.
if() [1/2]
if (a_is_any_zero_flag && b_is_lt_zero_flag)
Definition at line 218 of file vspow4.cpp.
References ONE_F_VEC, and ZERO_F_VEC.
if() [2/2]
if (a_is_neg_flag && !b_is_integer_flag)
Definition at line 214 of file vspow4.cpp.
References a.
Variable Documentation
a
__m128 __m128 const a
Definition at line 69 of file vspow4.cpp.
Referenced by __fvs_pow_fma3(), and if().
a_as_nan
__m128 a_as_nan
Initial value:
= _mm_or_ps(_mm_and_ps(
                                           (__m128)a_is_nan, _mm_or_ps(a, (__m128)_mm_set1_epi32(0x00400000))),
                                _mm_andnot_ps((__m128)a_is_nan, res_exp))
Definition at line 125 of file vspow4.cpp.
a_is_any_inf
__m128i a_is_any_inf = _mm_or_si128(a_is_pos_inf, a_is_neg_inf)
Definition at line 142 of file vspow4.cpp.
a_is_any_zero
__m128i a_is_any_zero = _mm_or_si128(a_is_pos_zero, a_is_neg_zero)
Definition at line 146 of file vspow4.cpp.
a_is_any_zero_flag
int a_is_any_zero_flag = _mm_movemask_epi8((__m128i)a_is_any_zero)
Definition at line 147 of file vspow4.cpp.
a_is_minus_one_mask
__m128i a_is_minus_one_mask = _mm_cmpeq_epi32((__m128i)a, (__m128i)MINUS_ONE_F_VEC)
Definition at line 154 of file vspow4.cpp.
a_is_nan
__m128i a_is_nan = (__m128i)_mm_cmp_ps(a,a, _CMP_NEQ_UQ)
Definition at line 84 of file vspow4.cpp.
a_is_neg
__m128i a_is_neg = (__m128i)_mm_cmp_ps(a, ZERO_F_VEC, _CMP_LT_OS)
Definition at line 85 of file vspow4.cpp.
a_is_neg_flag
int a_is_neg_flag = _mm_movemask_epi8((__m128i)a_is_neg)
Definition at line 86 of file vspow4.cpp.
a_is_neg_inf
__m128i a_is_neg_inf = _mm_cmpeq_epi32((__m128i)a, neg_inf)
Definition at line 140 of file vspow4.cpp.
a_is_neg_zero
__m128i a_is_neg_zero = _mm_cmpeq_epi32((__m128i)a, (__m128i)MINUS_ZERO_F_VEC)
Definition at line 145 of file vspow4.cpp.
a_is_one_mask
__m128i a_is_one_mask = _mm_cmpeq_epi32((__m128i)a, (__m128i)ONE_F_VEC)
Definition at line 153 of file vspow4.cpp.
a_is_pos_inf
__m128i a_is_pos_inf = _mm_cmpeq_epi32((__m128i)a, pos_inf)
Definition at line 141 of file vspow4.cpp.
a_is_pos_zero
__m128i a_is_pos_zero = _mm_cmpeq_epi32((__m128i)a, (__m128i)ZERO_F_VEC)
Definition at line 144 of file vspow4.cpp.
abs_a
__m128i abs_a = _mm_and_si128((__m128i)a, abs_mask)
Definition at line 149 of file vspow4.cpp.
abs_a_gt_one
__m128 abs_a_gt_one = _mm_cmp_ps((__m128)abs_a, ONE_F_VEC, _CMP_GT_OS)
Definition at line 151 of file vspow4.cpp.
abs_a_lt_one
__m128 abs_a_lt_one = _mm_cmp_ps((__m128)abs_a, ONE_F_VEC, _CMP_LT_OS)
Definition at line 150 of file vspow4.cpp.
b
__m128 __m128 const __m128 const b
Initial value:
{
   __m128i abs_mask = _mm_set1_epi32(D_ABS_MASK)
Definition at line 69 of file vspow4.cpp.
Referenced by __fvs_pow_fma3().
b_as_nan
__m128 b_as_nan
Initial value:
= _mm_or_ps(_mm_and_ps(
                                           (__m128)b_is_nan, _mm_or_ps(b, (__m128)_mm_set1_epi32(0x00400000))),
                                _mm_andnot_ps((__m128)b_is_nan, res_exp))
Definition at line 121 of file vspow4.cpp.
b_is_any_inf
__m128i b_is_any_inf = _mm_or_si128(b_is_pos_inf, b_is_neg_inf)
Definition at line 138 of file vspow4.cpp.
b_is_even_integer
__m128i b_is_even_integer
Initial value:
= _mm_and_si128(b_is_integer,
                                             _mm_cmpeq_epi32(
                                                             _mm_and_si128(_mm_cvtps_epi32(b), _mm_set1_epi32(0x1)),
                                                             _mm_set1_epi32(0x0)))
Definition at line 96 of file vspow4.cpp.
b_is_gt_zero
__m128i b_is_gt_zero = (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_GT_OS)
Definition at line 104 of file vspow4.cpp.
b_is_integer
__m128i b_is_integer = (__m128i)_mm_cmp_ps(b, _mm_floor_ps(b), _CMP_EQ_OQ)
Definition at line 88 of file vspow4.cpp.
b_is_integer_flag
int b_is_integer_flag = _mm_movemask_epi8((__m128i)b_is_integer)
Definition at line 89 of file vspow4.cpp.
b_is_lt_zero
__m128i b_is_lt_zero = (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_LT_OS)
Definition at line 101 of file vspow4.cpp.
b_is_lt_zero_flag
int b_is_lt_zero_flag = _mm_movemask_epi8((__m128i)b_is_lt_zero)
Definition at line 102 of file vspow4.cpp.
b_is_nan
__m128i b_is_nan = (__m128i)_mm_cmp_ps(b, b, _CMP_NEQ_UQ)
Definition at line 83 of file vspow4.cpp.
b_is_neg_inf
__m128i b_is_neg_inf = _mm_cmpeq_epi32((__m128i)b, neg_inf)
Definition at line 136 of file vspow4.cpp.
b_is_odd_integer
__m128i b_is_odd_integer
Initial value:
= _mm_and_si128(b_is_integer,
                                            _mm_cmpeq_epi32(
                                                            _mm_and_si128(_mm_cvtps_epi32(b), _mm_set1_epi32(0x1)),
                                                            _mm_set1_epi32(0x1)))
Definition at line 91 of file vspow4.cpp.
b_is_odd_integer_gt_zero
__m128i b_is_odd_integer_gt_zero
Initial value:
= _mm_and_si128(b_is_integer,
                                                     (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_GT_OS))
Definition at line 109 of file vspow4.cpp.
b_is_odd_integer_lt_zero
__m128i b_is_odd_integer_lt_zero
Initial value:
= _mm_and_si128(b_is_integer,
                                                     (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_LT_OS))
Definition at line 106 of file vspow4.cpp.
b_is_pos_inf
__m128i b_is_pos_inf = _mm_cmpeq_epi32((__m128i)b, pos_inf)
Definition at line 137 of file vspow4.cpp.
change_sign_mask
__m128i change_sign_mask = _mm_and_si128(a_is_neg, b_is_odd_integer)
Definition at line 112 of file vspow4.cpp.
changed_sign
__m128 changed_sign = _mm_xor_ps(res_exp, (__m128)sign_mask)
Definition at line 113 of file vspow4.cpp.
MINUS_ONE_F_VEC
__m128 MINUS_ONE_F_VEC = _mm_set1_ps(D_MINUS_ONE_F)
Definition at line 77 of file vspow4.cpp.
MINUS_ZERO_F_VEC
__m128 MINUS_ZERO_F_VEC = _mm_set1_ps(D_MINUS_ZERO_F)
Definition at line 78 of file vspow4.cpp.
nan
__m128i nan = _mm_set1_epi32(D_NAN)
Definition at line 75 of file vspow4.cpp.
nan_to_return
nan_to_return = _mm_and_ps((__m128)b_is_nan, b_as_nan)
Definition at line 129 of file vspow4.cpp.
neg_inf
__m128i neg_inf = _mm_set1_epi32(D_NEG_INF)
Definition at line 74 of file vspow4.cpp.
neg_nan
__m128i neg_nan = _mm_set1_epi32(D_NEG_NAN)
Definition at line 76 of file vspow4.cpp.
ONE_F_VEC
__m128 const ONE_F_VEC = _mm_set1_ps(D_ONE_F)
Definition at line 79 of file vspow4.cpp.
Referenced by __fvs_pow_fma3(), and if().
pos_inf
__m128i pos_inf = _mm_set1_epi32(D_POS_INF)
Definition at line 72 of file vspow4.cpp.
res_exp
return res_exp = _mm_or_ps(_mm_and_ps((__m128)change_sign_mask, (__m128)changed_sign), _mm_andnot_ps((__m128)change_sign_mask, res_exp))
Definition at line 114 of file vspow4.cpp.
Referenced by __fvs_pow_fma3().
return_1_mask
return_1_mask = _mm_or_si128(a_is_one_mask, (__m128i)_mm_cmp_ps(b, ZERO_F_VEC, _CMP_EQ_OQ))
Definition at line 156 of file vspow4.cpp.
return_minus_1_mask
__m128i return_minus_1_mask = _mm_and_si128(a_is_minus_one_mask, b_is_odd_integer)
Definition at line 164 of file vspow4.cpp.
return_nan_mask
__m128i return_nan_mask = _mm_or_si128(b_is_nan, a_is_nan)
Definition at line 119 of file vspow4.cpp.
return_neg_inf_mask
return_neg_inf_mask = _mm_and_si128(a_is_neg_inf, _mm_and_si128(b_is_odd_integer, b_is_gt_zero))
Definition at line 187 of file vspow4.cpp.
return_neg_nan_mask
__m128i return_neg_nan_mask = _mm_andnot_si128(b_is_integer, a_is_neg)
Definition at line 116 of file vspow4.cpp.
return_neg_zero_mask
return_neg_zero_mask
Initial value:
= _mm_and_si128(a_is_neg_inf,
                                                b_is_odd_integer_lt_zero)
Definition at line 169 of file vspow4.cpp.
return_pos_inf_mask
return_pos_inf_mask = _mm_and_si128((__m128i)abs_a_lt_one, b_is_neg_inf)
Definition at line 193 of file vspow4.cpp.
return_pos_zero_mask
return_pos_zero_mask = _mm_and_si128((__m128i)abs_a_gt_one, b_is_neg_inf)
Definition at line 177 of file vspow4.cpp.
sign_mask
__m128i sign_mask = _mm_set1_epi32(D_SIGN_MASK)
Definition at line 73 of file vspow4.cpp.
ZERO_F_VEC
__m128 const ZERO_F_VEC = _mm_setzero_ps()
Definition at line 80 of file vspow4.cpp.
Referenced by __fvs_pow_fma3(), and if().