flang: vsub.c File Reference
vsub.c File Reference
Rewrite subscript vectors for lhs and rhs, etc.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "symutl.h"
#include "dtypeutl.h"
#include "soc.h"
#include "semant.h"
#include "ast.h"
#include "gramtk.h"
#include "comm.h"
#include "extern.h"
#include "hpfutl.h"
#include "commopt.h"
#include "rte.h"
Functions
static int reference_for_temp_lhs_indirection (int, int, int)
static int forall_semantic (int std)
static void forall_with_mask (int std)
static void forall_loop_interchange (int std)
static void forall_with_shape (int std)
static void forall_list_call (int std)
static void forall_bound_dependence (int std)
static void forall_bound_dependence_fix (int prevstd, int nextstd)
static LOGICAL is_mask_for_rhs (int std, int ast)
static LOGICAL is_legal_lhs_for_mask (int, int)
static void scalar_lhs_dependency (int std)
static void scatter_dependency (int std)
static void scatter_dependency_assumsz (int std)
static int take_out_assumsz_array (int expr, int std, int sptr)
static LOGICAL is_one_idx_for_dim (int, int)
static LOGICAL is_sequentialize_pure (int std)
static LOGICAL is_ugly_pure (int ast)
static LOGICAL find_scatter_rhs (int expr, int forall, int *rhs)
static LOGICAL is_all_idx_in_subscript (int list, int a)
static LOGICAL ptr_subs_olap (int, int)
static LOGICAL can_ptr_olap (int, int)
void rewrite_forall (void)
This routine rewrites foralls.
int process_forall (int std)
int assign_scalar (int std, int ast)
void forall_lhs_indirection (int std)
LOGICAL is_legal_lhs (int a, int forall)
LOGICAL is_multiple_idx_in_list (int list)
LOGICAL is_duplicate (int a, int list)
LOGICAL is_scalar (int a, int list)
LOGICAL is_idx (int a, int list)
static LOGICAL is_triplet (int a, int list)
LOGICAL is_vector_subscript (int a, int list)
LOGICAL is_ordered (int lhs, int rhs, int list, int order2[MAXDIMS], int *no)
void search_forall_idx (int ast, int list, int *astli, int *nidx)
LOGICAL is_legal_rhs (int lhs, int rhs, int forall)
int delete_astli (int list, int astli)
int concatenate_list (int list1, int list2)
void rewrite_forall_pure (void)
static LOGICAL _contains_call (int astx, LOGICAL *pflag)
LOGICAL contains_call (int astx)
static LOGICAL appears_in_expr (int sptr, int expr)
static int remove_scalar_lhs_dependency (int ast, int list, int sptr, int std)
static int copy_to_scalar (int ast, int std, int sym)
Variables
static int process_forall_recursion = 0
struct {
int first
int lhs
int n
int std
int pre_std
} intr_info
static int scatter_dependency_recursion = 0
static int save_list = 0
int rewrite_opfields
Detailed Description
Rewrite subscript vectors for lhs and rhs, etc.
Definition in file vsub.c.
Function Documentation
_contains_call()
static LOGICAL _contains_call (int astx, LOGICAL * pflag) static
Definition at line 1407 of file vsub.c.
appears_in_expr()
static LOGICAL appears_in_expr (int sptr, int expr) static
Definition at line 1433 of file vsub.c.
assign_scalar()
int assign_scalar (int std, int ast)
Definition at line 234 of file vsub.c.
References add_stmt_before(), ast, dest, mk_id(), mk_stmt(), sptr, std, and sym_get_scalar().
Referenced by forall_list_call(), and rewrite_calls().
can_ptr_olap()
static LOGICAL can_ptr_olap (int parr, int ast) static
Definition at line 2157 of file vsub.c.
concatenate_list()
int concatenate_list (int list1, int list2)
Definition at line 1125 of file vsub.c.
Referenced by rewrite_block_forall().
contains_call()
LOGICAL contains_call (int astx)
Definition at line 1419 of file vsub.c.
Referenced by forall_list_call(), and rewrite_calls().
copy_to_scalar()
static int copy_to_scalar (int ast, int std, int sym) static
Definition at line 2041 of file vsub.c.
delete_astli()
int delete_astli (int list, int astli)
Definition at line 1049 of file vsub.c.
Referenced by inline_spread_shifts().
find_scatter_rhs()
static LOGICAL find_scatter_rhs (int expr, int forall, int * rhs) static
Definition at line 1942 of file vsub.c.
Referenced by forall_lhs_indirection().
forall_bound_dependence()
static void forall_bound_dependence (int std) static
Definition at line 2059 of file vsub.c.
Referenced by process_forall().
forall_bound_dependence_fix()
static void forall_bound_dependence_fix (int prevstd, int nextstd) static
Definition at line 2110 of file vsub.c.
Referenced by process_forall().
forall_lhs_indirection()
void forall_lhs_indirection (int std)
Definition at line 403 of file vsub.c.
References add_stmt_before(), ALIGNG, find_scatter_rhs(), get_temp_forall(), is_duplicate(), is_legal_lhs(), is_multiple_idx_in_list(), is_one_idx_for_dim(), is_vector_indirection_in_it(), left_array_symbol(), left_subscript_ast(), lhs, list, mk_stmt(), optype(), process_forall(), reference_for_temp_lhs_indirection(), scalar_lhs_dependency(), scatter_class(), scatter_dependency(), sptr, src, std, and STD_AST.
Referenced by process_forall().
forall_list_call()
static void forall_list_call (int std) static
Definition at line 249 of file vsub.c.
References assign_scalar(), ASTLI_NEXT, ASTLI_TRIPLE, contains_call(), j, list, mk_triple(), s, std, and STD_AST.
forall_loop_interchange()
static void forall_loop_interchange (int std) static
Definition at line 994 of file vsub.c.
Referenced by process_forall().
forall_semantic()
static int forall_semantic (int std) static
Definition at line 172 of file vsub.c.
References ASD_NDIM, ASD_SUBS, assert, ASTLI_NEXT, ASTLI_SPTR, CNULL, error(), FALSE, i, interr(), is_name_in_expr(), j, lhs, list, ndim, scalarize(), std, STD_AST, STD_LINENO, SYMNAME, and TRUE.
Referenced by process_forall().
forall_with_mask()
static void forall_with_mask (int std) static
Definition at line 276 of file vsub.c.
References add_stmt_before(), ALIGNG, DT_LOG, get_temp_forall(), is_indirection_in_it(), is_legal_lhs_for_mask(), is_mask_for_rhs(), is_multiple_idx_in_list(), is_one_idx_for_dim(), left_array_symbol(), lhs, list, mk_stmt(), process_forall(), reference_for_temp_lhs_indirection(), sptr, src, std, and STD_AST.
Referenced by process_forall().
forall_with_shape()
static void forall_with_shape (int std) static
Definition at line 1078 of file vsub.c.
Referenced by process_forall().
is_all_idx_in_subscript()
static LOGICAL is_all_idx_in_subscript (int list, int a) static
Definition at line 2016 of file vsub.c.
is_duplicate()
LOGICAL is_duplicate (int a, int list)
Definition at line 609 of file vsub.c.
References a, ASD_NDIM, ASD_SUBS, ast, ASTLI_NEXT, ASTLI_SPTR, FALSE, i, interr(), is_name_in_expr(), list, ndim, sptr, and TRUE.
Referenced by compute_permute(), forall_lhs_indirection(), is_legal_lhs_for_mask(), and same_forall_bnds().
is_idx()
LOGICAL is_idx (int a, int list)
Definition at line 657 of file vsub.c.
References a, ASTLI_SPTR, FALSE, list, mk_id(), search_forall_idx(), and TRUE.
Referenced by is_legal_lhs(), is_legal_lhs_for_mask(), and is_vector_subscript().
is_legal_lhs()
LOGICAL is_legal_lhs (int a, int forall)
Definition at line 481 of file vsub.c.
References a, AD_DPTR, AD_LWBD, ASD_NDIM, ASD_SUBS, assert, astb, FALSE, i, ASTB::i1, interr(), is_array_type(), is_idx(), is_scalar(), is_vector_subscript(), lb, list, ndim, sptr, sptr_of_subscript(), and TRUE.
Referenced by forall_lhs_indirection().
is_legal_lhs_for_mask()
static LOGICAL is_legal_lhs_for_mask (int a, int forall) static
Definition at line 523 of file vsub.c.
References a, ASD_NDIM, ASD_SUBS, ast, FALSE, i, interr(), is_duplicate(), is_idx(), is_scalar(), is_vector_subscript(), list, ndim, and TRUE.
Referenced by forall_with_mask().
is_legal_rhs()
LOGICAL is_legal_rhs (int lhs, int rhs, int forall)
Definition at line 938 of file vsub.c.
Referenced by is_mask_for_rhs().
is_mask_for_rhs()
static LOGICAL is_mask_for_rhs (int std, int ast) static
Definition at line 333 of file vsub.c.
References ast, FALSE, i, is_indirection_in_it(), is_legal_rhs(), is_mask_for_rhs(), lhs, r, std, STD_AST, and TRUE.
Referenced by forall_with_mask(), and is_mask_for_rhs().
is_multiple_idx_in_list()
LOGICAL is_multiple_idx_in_list (int list)
Definition at line 556 of file vsub.c.
References ASTLI_NEXT, ASTLI_SPTR, ASTLI_TRIPLE, FALSE, is_name_in_expr(), list, and TRUE.
Referenced by forall_lhs_indirection(), forall_with_mask(), and normalize_forall_triplet().
is_one_idx_for_dim()
static LOGICAL is_one_idx_for_dim (int a, int list) static
Definition at line 581 of file vsub.c.
References a, ASD_NDIM, ASD_SUBS, FALSE, i, interr(), list, ndim, search_forall_idx(), and TRUE.
Referenced by forall_lhs_indirection(), and forall_with_mask().
is_ordered()
LOGICAL is_ordered (int lhs, int rhs, int list, int order2[MAXDIMS], int * no)
Definition at line 712 of file vsub.c.
References ASD_NDIM, ASD_SUBS, assert, count, i, is_ordered(), j, LHS, list, MAXDIMS, ndim, order, r, and search_forall_idx().
Referenced by emit_copy_section(), emit_permute_section(), is_ordered(), and same_forall_bnds().
is_scalar()
LOGICAL is_scalar (int a, int list)
Definition at line 643 of file vsub.c.
References a, FALSE, list, search_forall_idx(), and TRUE.
Referenced by emit_scatterx_gatherx(), emit_sum_scatterx(), is_legal_lhs(), is_legal_lhs_for_mask(), and is_vector_subscript().
is_sequentialize_pure()
static LOGICAL is_sequentialize_pure (int std) static
Definition at line 1204 of file vsub.c.
is_triplet()
static LOGICAL is_triplet (int a, int list) static
Definition at line 673 of file vsub.c.
References a, base, FALSE, list, search_idx(), stride, and TRUE.
is_ugly_pure()
static LOGICAL is_ugly_pure (int ast) static
Definition at line 1241 of file vsub.c.
is_vector_subscript()
LOGICAL is_vector_subscript (int a, int list)
Definition at line 687 of file vsub.c.
References a, ASD_NDIM, ASD_SUBS, count, FALSE, i, is_idx(), is_scalar(), list, ndim, and TRUE.
Referenced by emit_scatterx_gatherx(), emit_sum_scatterx(), is_legal_lhs(), is_legal_lhs_for_mask(), is_vector_indirection_in_it(), and permute_axis().
process_forall()
int process_forall (int std)
Definition at line 119 of file vsub.c.
References assert, FALSE, forall_bound_dependence(), forall_bound_dependence_fix(), forall_lhs_indirection(), forall_loop_interchange(), forall_semantic(), forall_with_mask(), forall_with_shape(), lhs, process_forall_recursion, sequentialize(), std, STD_AST, STD_NEXT, STD_PREV, and void().
Referenced by copy_arg_to_seq_tmp(), emit_sum_scatterx(), forall_lhs_indirection(), forall_with_mask(), and rewrite_forall().
ptr_subs_olap()
static LOGICAL ptr_subs_olap (int parr, int a) static
Definition at line 2133 of file vsub.c.
reference_for_temp_lhs_indirection()
static int reference_for_temp_lhs_indirection (int sptr, int a, int forall) static
Definition at line 814 of file vsub.c.
Referenced by forall_lhs_indirection(), and forall_with_mask().
remove_scalar_lhs_dependency()
static int remove_scalar_lhs_dependency (int ast, int list, int sptr, int std) static
Definition at line 1503 of file vsub.c.
rewrite_forall()
void rewrite_forall (void)
This routine rewrites foralls.
forall with shape sec as A(i,:)
forall with dependency,
forall with distributed indirection array at rhs.
Definition at line 65 of file vsub.c.
References ast, FALSE, gbl, arg_gbl::inforall, arg_gbl::lhs, process_forall(), set_descriptor_sc(), arg_gbl::std, std, STD_AST, STD_LINENO, STD_NEXT, and arg_gbl::used.
Referenced by transform().
rewrite_forall_pure()
void rewrite_forall_pure (void)
Definition at line 1159 of file vsub.c.
Referenced by transform().
scalar_lhs_dependency()
static void scalar_lhs_dependency (int std) static
Definition at line 1578 of file vsub.c.
Referenced by forall_lhs_indirection().
scatter_dependency()
static void scatter_dependency (int std) static
Definition at line 1619 of file vsub.c.
Referenced by forall_lhs_indirection().
scatter_dependency_assumsz()
static void scatter_dependency_assumsz (int std) static
Definition at line 1774 of file vsub.c.
search_forall_idx()
void search_forall_idx (int ast, int list, int * astli, int * nidx)
Definition at line 872 of file vsub.c.
Referenced by compute_permute(), copy_section_temp_before(), eliminate_extra_idx(), forall_2_sec(), gatherx_temp_before(), inline_spread_shifts(), is_idx(), is_one_idx_for_dim(), is_ordered(), is_scalar(), and search_idx().
take_out_assumsz_array()
static int take_out_assumsz_array (int expr, int std, int sptr) static
Definition at line 1830 of file vsub.c.
Variable Documentation
first
int first
Definition at line 1151 of file vsub.c.
struct { ... } intr_info
lhs
int lhs
Definition at line 1152 of file vsub.c.
Referenced by _find_lhs_on_rhs_conflict(), _find_rhs_def_conflict(), _ilis_are_matched(), _is_atomic_update_binop(), _parser(), _RTE_ba(), add_def(), add_psd(), addssassignments(), allocate_lhs_if_needed(), assign(), bld_lhs(), build_psd(), canonical_conversion(), chk_and_rewrite_cmplxpart_assn(), collapse_assignment(), complt(), compute_permute(), conv_forall(), convert_template_instance(), do_reduction(), eliminate_copy(), eliminate_extra_idx(), eliminate_redundant(), emit_copy_section(), emit_gatherx(), emit_permute_section(), emit_scatterx_gatherx(), exp_mp_atomic_capture(), find_lhs_on_rhs_conflict(), find_rhs_conflict(), fix_guard_forall(), forall_dependency(), forall_dependency_scalarize(), forall_lhs_indirection(), forall_semantic(), forall_with_mask(), gen_automatic_reallocation(), gen_mulh_expr(), gen_reduction(), generate_hcycliclp(), generate_hlocalizebnds(), get_complex_update_operand(), get_lhs_first_defs(), get_simple_update_operand(), inline_shifts(), inline_small_matmul(), insert_assign(), insert_forall_comm(), is_biv(), is_blockaddr_store(), is_call_dependent(), is_dependent(), is_fusable(), is_mask_call_dependent(), is_mask_for_rhs(), is_same_descr_for_bnds(), is_stmt_call_dependent(), is_use_lhs(), is_use_lhs_final(), lhs_dim(), lhs_needtmp(), ll_make_atomic_compare_xchg(), ll_make_atomic_load(), ll_make_atomic_store(), load_op_match_lhs(), mask_on_lhs(), matmul(), matmul_use_lhs(), mk_result_sptr(), mmul(), no_comm_class(), prntgm(), process_forall(), process_lhs_sub(), reshape(), rewrite_asn(), rewrite_block_where(), rewrite_calls(), rewrite_func_ast(), rewrite_into_forall(), rewrite_intr_allocatable(), search_pure_function(), semant3(), sfloat(), shape_comm(), shape_comm_in_expr(), strovlp(), subst_lhs_arrfn(), subst_lhs_pointer(), tag_comms(), temp_copy_section(), temp_gatherx(), and trnred().
n
int n
Definition at line 1153 of file vsub.c.
pre_std
int pre_std
Definition at line 1155 of file vsub.c.
process_forall_recursion
int process_forall_recursion = 0 static
Definition at line 116 of file vsub.c.
Referenced by process_forall().
rewrite_opfields
int rewrite_opfields extern
Definition at line 4358 of file ast.c.
Referenced by ast_rewrite(), ast_unvisit(), and ast_unvisit_norepl().
save_list
int save_list = 0 static
Definition at line 2057 of file vsub.c.
scatter_dependency_recursion
int scatter_dependency_recursion = 0 static
Definition at line 1616 of file vsub.c.
std
int std
Definition at line 1154 of file vsub.c.
Referenced by assign_scalar(), forall_lhs_indirection(), forall_list_call(), forall_semantic(), forall_with_mask(), is_mask_for_rhs(), process_forall(), and rewrite_forall().