flang: wintimes.h File Reference
wintimes.h File Reference
#include <Windows.h>
#include <time.h>
Classes
struct tms
Typedefs
typedef struct tms tms
Functions
clock_t convert_filetime (const FILETIME *ac_FileTime)
void times (tms *time_struct)
Typedef Documentation
tms
typedef struct tms tms
Function Documentation
convert_filetime()
clock_t convert_filetime (const FILETIME * ac_FileTime)
times()
void times (tms * time_struct)
Referenced by ENT3F(), ENTFTN(), and get_rutime().