flang: exp.c File Reference
x86_64/exp.c File Reference
#include "libm_amd.h"
#include "libm_util_amd.h"
#include "libm_inlines_amd.h"
#include "libm_errno_amd.h"
Macros
#define USE_SPLITEXPF
#define USE_SCALEFLOAT_1
#define USE_SCALEFLOAT_2
#define USE_ZEROF_WITH_FLAGS
#define USE_INFINITYF_WITH_FLAGS
#define USE_NANF_WITH_FLAGS
#define USE_HANDLE_ERRORF
Functions
static float retval_errno_erange_overflow (float x __attribute__((unused)))
static float retval_errno_erange_underflow (float x __attribute__((unused)))
float FN_PROTOTYPE() mth_i_exp (float x)
Macro Definition Documentation
USE_HANDLE_ERRORF
#define USE_HANDLE_ERRORF
Definition at line 51 of file x86_64/exp.c.
USE_INFINITYF_WITH_FLAGS
#define USE_INFINITYF_WITH_FLAGS
Definition at line 49 of file x86_64/exp.c.
USE_NANF_WITH_FLAGS
#define USE_NANF_WITH_FLAGS
Definition at line 50 of file x86_64/exp.c.
USE_SCALEFLOAT_1
#define USE_SCALEFLOAT_1
Definition at line 46 of file x86_64/exp.c.
USE_SCALEFLOAT_2
#define USE_SCALEFLOAT_2
Definition at line 47 of file x86_64/exp.c.
USE_SPLITEXPF
#define USE_SPLITEXPF
Definition at line 45 of file x86_64/exp.c.
USE_ZEROF_WITH_FLAGS
#define USE_ZEROF_WITH_FLAGS
Definition at line 48 of file x86_64/exp.c.
Function Documentation
mth_i_exp()
float FN_PROTOTYPE() mth_i_exp (float x)
Definition at line 76 of file x86_64/exp.c.
References EMAX_SP32, EMIN_SP32, GET_BITS_SP32, m, MANTBITS_SP32, retval_errno_erange_overflow(), retval_errno_erange_underflow(), SIGNBIT_SP32, x, and z.
retval_errno_erange_overflow()
static float retval_errno_erange_overflow (float x __attribute__(unused)) inline static
Definition at line 65 of file x86_64/exp.c.
References AMD_F_INEXACT, and AMD_F_OVERFLOW.
Referenced by mth_i_exp().
retval_errno_erange_underflow()
static float retval_errno_erange_underflow (float x __attribute__(unused)) inline static
Definition at line 71 of file x86_64/exp.c.
References AMD_F_INEXACT, and AMD_F_UNDERFLOW.
Referenced by mth_i_exp().