flang: dlog.c File Reference
x86_64/dlog.c File Reference
#include "libm_amd.h"
#include "libm_util_amd.h"
#include "libm_inlines_amd.h"
#include "libm_errno_amd.h"
Macros
#define USE_NAN_WITH_FLAGS
#define USE_INFINITY_WITH_FLAGS
#define USE_HANDLE_ERROR
#define _FUNCNAME "log"
Functions
static double retval_errno_erange_overflow (double x __attribute__((unused)))
static double retval_errno_edom (double x __attribute__((unused)))
double FN_PROTOTYPE() mth_i_dlog (double x)
Macro Definition Documentation
_FUNCNAME
#define _FUNCNAME "log"
Definition at line 77 of file x86_64/dlog.c.
USE_HANDLE_ERROR
#define USE_HANDLE_ERROR
Definition at line 47 of file x86_64/dlog.c.
USE_INFINITY_WITH_FLAGS
#define USE_INFINITY_WITH_FLAGS
Definition at line 46 of file x86_64/dlog.c.
USE_NAN_WITH_FLAGS
#define USE_NAN_WITH_FLAGS
Definition at line 45 of file x86_64/dlog.c.
Function Documentation
mth_i_dlog()
double FN_PROTOTYPE() mth_i_dlog (double x)
Definition at line 78 of file x86_64/dlog.c.
References EXPBIAS_DP64, EXPBITS_DP64, EXPSHIFTBITS_DP64, f, f2, GET_BITS_DP64, HALFEXPBITS_DP64, IMPBIT_DP64, index, MANTBITS_DP64, poly, PUT_BITS_DP64, q, r, retval_errno_edom(), retval_errno_erange_overflow(), SIGNBIT_DP64, and x.
retval_errno_edom()
static double retval_errno_edom (double x __attribute__(unused)) inline static
Definition at line 64 of file x86_64/dlog.c.
References AMD_F_INVALID.
Referenced by mth_i_dlog().
retval_errno_erange_overflow()
static double retval_errno_erange_overflow (double x __attribute__(unused)) inline static
Definition at line 57 of file x86_64/dlog.c.
References AMD_F_DIVBYZERO.
Referenced by mth_i_dlog().