flang: alog.c File Reference
x86_64/alog.c File Reference
#include "libm_amd.h"
#include "libm_util_amd.h"
#include "libm_inlines_amd.h"
#include "libm_errno_amd.h"
Macros
#define USE_NANF_WITH_FLAGS
#define USE_INFINITYF_WITH_FLAGS
#define USE_HANDLE_ERRORF
#define _FUNCNAME "logf"
Functions
static float retval_errno_erange_overflow (float x __attribute__((unused)))
static float retval_errno_edom (float x __attribute__((unused)))
float FN_PROTOTYPE() mth_i_alog (float fx)
Macro Definition Documentation
_FUNCNAME
#define _FUNCNAME "logf"
Definition at line 77 of file x86_64/alog.c.
USE_HANDLE_ERRORF
#define USE_HANDLE_ERRORF
Definition at line 47 of file x86_64/alog.c.
USE_INFINITYF_WITH_FLAGS
#define USE_INFINITYF_WITH_FLAGS
Definition at line 46 of file x86_64/alog.c.
USE_NANF_WITH_FLAGS
#define USE_NANF_WITH_FLAGS
Definition at line 45 of file x86_64/alog.c.
Function Documentation
mth_i_alog()
float FN_PROTOTYPE() mth_i_alog (float fx)
Definition at line 78 of file x86_64/alog.c.
References EXPBIAS_DP64, EXPBITS_DP64, EXPSHIFTBITS_DP64, f, f2, GET_BITS_DP64, HALFEXPBITS_DP64, index, MANTBITS_DP64, poly, PUT_BITS_DP64, q, r, retval_errno_edom(), retval_errno_erange_overflow(), SIGNBIT_DP64, and x.
retval_errno_edom()
static float retval_errno_edom (float x __attribute__(unused)) inline static
Definition at line 64 of file x86_64/alog.c.
References AMD_F_INVALID.
Referenced by mth_i_alog().
retval_errno_erange_overflow()
static float retval_errno_erange_overflow (float x __attribute__(unused)) inline static
Definition at line 57 of file x86_64/alog.c.
References AMD_F_DIVBYZERO.
Referenced by mth_i_alog().