flang: ll_abi.cpp File Reference
x86_64/ll_abi.cpp File Reference
#include "ll_abi.h"
#include "dtypeutl.h"
#include "error.h"
#include "symfun.h"
Macros
#define DT_VOIDNONE DT_NONE
#define GP_XM 0
#define XM_GP 1
#define XM_XM 2
Enumerations
enum amd64_class {
AMD64_NO_CLASS = 0 , AMD64_INTEGER , AMD64_SSE , AMD64_SSEUP ,
AMD64_X87 , AMD64_X87UP , AMD64_COMPLEX_X87 , AMD64_MEMORY
}
Functions
void ll_abi_compute_call_conv (LL_ABI_Info *abi, int func_sptr, int jsra_flags)
...
static enum amd64_class amd64_merge (enum amd64_class c1, enum amd64_class c2)
static int amd64_update_class (void *context, DTYPE dtype, unsigned address, int member_sptr)
static int amd64_classify (enum amd64_class ebc[2], DTYPE dtype)
static void amd64_coerce (LL_Module *module, LL_ABI_ArgInfo *arg, const enum amd64_class ebc[2], DTYPE dtype)
static enum LL_ABI_ArgKind classify_int (DTYPE dtype)
void ll_abi_classify_return_dtype (LL_ABI_Info *abi, DTYPE dtype)
...
void ll_abi_classify_arg_dtype (LL_ABI_Info *abi, LL_ABI_ArgInfo *arg, DTYPE dtype)
...
unsigned ll_abi_classify_va_arg_dtype (LL_Module *module, DTYPE dtype, unsigned *num_gp, unsigned *num_fp)
...
Macro Definition Documentation
DT_VOIDNONE
#define DT_VOIDNONE DT_NONE
Definition at line 15 of file x86_64/ll_abi.cpp.
GP_XM
#define GP_XM 0
Definition at line 379 of file x86_64/ll_abi.cpp.
XM_GP
#define XM_GP 1
Definition at line 380 of file x86_64/ll_abi.cpp.
XM_XM
#define XM_XM 2
Definition at line 381 of file x86_64/ll_abi.cpp.
Enumeration Type Documentation
amd64_class
enum amd64_class
Enumerator
AMD64_NO_CLASS
AMD64_INTEGER
AMD64_SSE
AMD64_SSEUP
AMD64_X87
AMD64_X87UP
AMD64_COMPLEX_X87
AMD64_MEMORY
Definition at line 29 of file x86_64/ll_abi.cpp.
Function Documentation
amd64_classify()
static int amd64_classify (enum amd64_class ebc[2], DTYPE dtype) static
Definition at line 181 of file x86_64/ll_abi.cpp.
References AMD64_MEMORY, AMD64_NO_CLASS, AMD64_SSE, AMD64_SSEUP, amd64_update_class(), AMD64_X87, AMD64_X87UP, i, visit_flattened_dtype(), and zsize_of().
Referenced by ll_abi_classify_arg_dtype(), ll_abi_classify_return_dtype(), and ll_abi_classify_va_arg_dtype().
amd64_coerce()
static void amd64_coerce (LL_Module * module, LL_ABI_ArgInfo * arg, const enum amd64_class ebc[2], DTYPE dtype) static
Definition at line 212 of file x86_64/ll_abi.cpp.
References AMD64_INTEGER, AMD64_NO_CLASS, AMD64_SSE, AMD64_SSEUP, AMD64_X87, AMD64_X87UP, arg, assert, DT_CMPLX, ERR_Fatal, i, ISZ_T, LL_AddrSp_Default, LL_ARG_COERCE, ll_create_anon_struct_type(), ll_create_basic_type(), ll_create_int_type(), LL_DOUBLE, LL_FLOAT, ll_get_vector_type(), LL_I64, LL_X86_FP80, NULL, size, and zsize_of().
Referenced by ll_abi_classify_arg_dtype(), and ll_abi_classify_return_dtype().
amd64_merge()
static enum amd64_class amd64_merge (enum amd64_class c1, enum amd64_class c2) static
Definition at line 43 of file x86_64/ll_abi.cpp.
References AMD64_COMPLEX_X87, AMD64_INTEGER, AMD64_MEMORY, AMD64_NO_CLASS, AMD64_SSE, AMD64_X87, and AMD64_X87UP.
Referenced by amd64_update_class().
amd64_update_class()
static int amd64_update_class (void * context, DTYPE dtype, unsigned address, int member_sptr) static
Definition at line 88 of file x86_64/ll_abi.cpp.
References alignment(), AMD64_INTEGER, AMD64_MEMORY, amd64_merge(), AMD64_SSE, AMD64_SSEUP, amd64_update_class(), ddtype(), DT_ISCMPLX, DT_ISINT, DT_ISREAL, DT_ISVECT, DTY, DTySeqTyElement, offset, size, TY_DCMPLX, and zsize_of().
Referenced by amd64_classify(), and amd64_update_class().
classify_int()
static enum LL_ABI_ArgKind classify_int (DTYPE dtype) static
Definition at line 286 of file x86_64/ll_abi.cpp.
References DT_ISUNSIGNED, LL_ARG_DIRECT, LL_ARG_SIGNEXT, LL_ARG_ZEROEXT, and size_of().
Referenced by ll_abi_classify_arg_dtype(), and ll_abi_classify_return_dtype().
ll_abi_classify_arg_dtype()
void ll_abi_classify_arg_dtype (LL_ABI_Info * abi, LL_ABI_ArgInfo * arg, DTYPE dtype)
...
Definition at line 331 of file x86_64/ll_abi.cpp.
References amd64_classify(), amd64_coerce(), AMD64_INTEGER, AMD64_SSE, arg, classify_int(), DT_ISCMPLX, DT_ISINT, DT_ISSCALAR, DT_ISVECT, LL_ARG_BYVAL, LL_ARG_DIRECT, LL_ABI_Info_::module, LL_ABI_Info_::used_fregs, and LL_ABI_Info_::used_iregs.
ll_abi_classify_return_dtype()
void ll_abi_classify_return_dtype (LL_ABI_Info * abi, DTYPE dtype)
...
Definition at line 296 of file x86_64/ll_abi.cpp.
References amd64_classify(), amd64_coerce(), LL_ABI_Info_::arg, classify_int(), DT_ISCMPLX, DT_ISINT, DT_ISSCALAR, DT_ISVECT, DT_VOIDNONE, LL_ABI_ArgInfo_::kind, LL_ARG_DIRECT, LL_ARG_INDIRECT, LL_ABI_Info_::module, and LL_ABI_Info_::used_iregs.
ll_abi_classify_va_arg_dtype()
unsigned ll_abi_classify_va_arg_dtype (LL_Module * module, DTYPE dtype, unsigned * num_gp, unsigned * num_fp)
...
Definition at line 384 of file x86_64/ll_abi.cpp.
References amd64_classify(), AMD64_INTEGER, AMD64_SSE, GP_XM, XM_GP, and XM_XM.
ll_abi_compute_call_conv()
void ll_abi_compute_call_conv (LL_ABI_Info * abi, int func_sptr, int jsra_flags)
...
Definition at line 18 of file x86_64/ll_abi.cpp.
References LL_ABI_Info_::call_as_varargs, and LL_ABI_Info_::missing_prototype.