flang: dtan.c File Reference
x86_64/dtan.c File Reference
#include "libm_amd.h"
#include "libm_util_amd.h"
#include "libm_inlines_amd.h"
Macros
#define USE_REMAINDER_PIBY2_INLINE
#define USE_NAN_WITH_FLAGS
#define USE_VAL_WITH_FLAGS
#define USE_HANDLE_ERROR
Functions
static double tan_piby4 (double x, double xx, int recip)
double FN_PROTOTYPE() mth_i_dtan (double x)
Macro Definition Documentation
USE_HANDLE_ERROR
#define USE_HANDLE_ERROR
Definition at line 49 of file x86_64/dtan.c.
USE_NAN_WITH_FLAGS
#define USE_NAN_WITH_FLAGS
Definition at line 47 of file x86_64/dtan.c.
USE_REMAINDER_PIBY2_INLINE
#define USE_REMAINDER_PIBY2_INLINE
Definition at line 46 of file x86_64/dtan.c.
USE_VAL_WITH_FLAGS
#define USE_VAL_WITH_FLAGS
Definition at line 48 of file x86_64/dtan.c.
Function Documentation
mth_i_dtan()
double FN_PROTOTYPE() mth_i_dtan (double x)
Definition at line 132 of file x86_64/dtan.c.
References AMD_F_INEXACT, AMD_F_INVALID, EXPBITS_DP64, EXPSHIFTBITS_DP64, GET_BITS_DP64, MANTBITS_DP64, r, t, tan_piby4(), x, and xneg.
tan_piby4()
static double tan_piby4 (double x, double xx, int recip) inline static
Definition at line 59 of file x86_64/dtan.c.
References GET_BITS_DP64, PUT_BITS_DP64, r, t, t1, t2, transform(), and x.
Referenced by mth_i_dtan().