flang: x86id.h File Reference
x86id.h File Reference
#include <stdint.h>
Macros
#define X86IDFN_(l, r) l##r
#define X86IDFN(n) X86IDFN_(__Cpuid_,n)
#define X86ID_IS_CACHED_UNDEF (-1)
#define HW_SSE 0x00000001
#define HW_SSE4 0x00000002
#define HW_AVX 0x00000004
#define HW_AVX2 0x00000008
#define HW_AVX512 0x00000010
#define HW_AVX512F 0x00000020
#define HW_AVX512VL 0x00000040
#define HW_FMA 0x00000080
#define HW_FMA4 0x00000100
#define HW_KNL 0x00000200
#define HW_F16C 0x00000400
#define HW_SSSE3 0x00000800
#define IS_CONCAT3_(l, m, r) l##m##r
#define IS_CONCAT3(l, m, r) IS_CONCAT3_(l,m,r)
#define IS_X86ID(f)
#define DECLEXTERN extern
Functions
DECLEXTERN uint32_t X86IDFN (hw_features)
DECLEXTERN int X86IDFN (is_intel_cached)
DECLEXTERN int X86IDFN (is_amd_cached)
DECLEXTERN int X86IDFN (is_ip6_cached)
DECLEXTERN int X86IDFN (is_sse_cached)
DECLEXTERN int X86IDFN (is_sse2_cached)
DECLEXTERN int X86IDFN (is_sse3_cached)
DECLEXTERN int X86IDFN (is_ssse3_cached)
DECLEXTERN int X86IDFN (is_sse4a_cached)
DECLEXTERN int X86IDFN (is_sse41_cached)
DECLEXTERN int X86IDFN (is_sse42_cached)
DECLEXTERN int X86IDFN (is_aes_cached)
DECLEXTERN int X86IDFN (is_avx_cached)
DECLEXTERN int X86IDFN (is_avx2_cached)
DECLEXTERN int X86IDFN (is_avx512_cached)
DECLEXTERN int X86IDFN (is_avx512f_cached)
DECLEXTERN int X86IDFN (is_avx512vl_cached)
DECLEXTERN int X86IDFN (is_fma_cached)
DECLEXTERN int X86IDFN (is_fma4_cached)
DECLEXTERN int X86IDFN (is_ht_cached)
DECLEXTERN int X86IDFN (is_athlon_cached)
DECLEXTERN int X86IDFN (is_hammer_cached)
DECLEXTERN int X86IDFN (is_gh_cached)
DECLEXTERN int X86IDFN (is_gh_a_cached)
DECLEXTERN int X86IDFN (is_gh_b_cached)
DECLEXTERN int X86IDFN (is_shanghai_cached)
DECLEXTERN int X86IDFN (is_istanbul_cached)
DECLEXTERN int X86IDFN (is_bulldozer_cached)
DECLEXTERN int X86IDFN (is_piledriver_cached)
DECLEXTERN int X86IDFN (is_k7_cached)
DECLEXTERN int X86IDFN (is_ia32e_cached)
DECLEXTERN int X86IDFN (is_p4_cached)
DECLEXTERN int X86IDFN (is_knl_cached)
DECLEXTERN int X86IDFN (is_x86_64_cached)
DECLEXTERN int X86IDFN (is_f16c_cached)
DECLEXTERN int X86IDFN() is_intel (void)
DECLEXTERN int X86IDFN() is_amd (void)
DECLEXTERN int X86IDFN() is_ip6 (void)
DECLEXTERN int X86IDFN() is_sse (void)
DECLEXTERN int X86IDFN() is_sse2 (void)
DECLEXTERN int X86IDFN() is_sse3 (void)
DECLEXTERN int X86IDFN() is_ssse3 (void)
DECLEXTERN int X86IDFN() is_sse4a (void)
DECLEXTERN int X86IDFN() is_sse41 (void)
DECLEXTERN int X86IDFN() is_sse42 (void)
DECLEXTERN int X86IDFN() is_aes (void)
DECLEXTERN int X86IDFN() is_avx (void)
DECLEXTERN int X86IDFN() is_avx2 (void)
DECLEXTERN int X86IDFN() is_avx512 (void)
DECLEXTERN int X86IDFN() is_avx512f (void)
DECLEXTERN int X86IDFN() is_avx512vl (void)
DECLEXTERN int X86IDFN() is_fma (void)
DECLEXTERN int X86IDFN() is_fma4 (void)
DECLEXTERN int X86IDFN() is_ht (void)
DECLEXTERN int X86IDFN() is_athlon (void)
DECLEXTERN int X86IDFN() is_hammer (void)
DECLEXTERN int X86IDFN() is_gh (void)
DECLEXTERN int X86IDFN() is_gh_a (void)
DECLEXTERN int X86IDFN() is_gh_b (void)
DECLEXTERN int X86IDFN() is_shanghai (void)
DECLEXTERN int X86IDFN() is_istanbul (void)
DECLEXTERN int X86IDFN() is_bulldozer (void)
DECLEXTERN int X86IDFN() is_piledriver (void)
DECLEXTERN int X86IDFN() is_k7 (void)
DECLEXTERN int X86IDFN() is_ia32e (void)
DECLEXTERN int X86IDFN() is_p4 (void)
DECLEXTERN int X86IDFN() is_knl (void)
DECLEXTERN int X86IDFN() is_x86_64 (void)
DECLEXTERN int X86IDFN() get_cachesize (void)
DECLEXTERN int X86IDFN() is_f16c (void)
DECLEXTERN char *X86IDFN() get_processor_name (void)
int X86IDFN() get_cores (void)
Macro Definition Documentation
DECLEXTERN
#define DECLEXTERN extern
Definition at line 100 of file x86id.h.
HW_AVX
#define HW_AVX 0x00000004
Definition at line 56 of file x86id.h.
HW_AVX2
#define HW_AVX2 0x00000008
Definition at line 57 of file x86id.h.
HW_AVX512
#define HW_AVX512 0x00000010
Definition at line 58 of file x86id.h.
HW_AVX512F
#define HW_AVX512F 0x00000020
Definition at line 59 of file x86id.h.
HW_AVX512VL
#define HW_AVX512VL 0x00000040
Definition at line 60 of file x86id.h.
HW_F16C
#define HW_F16C 0x00000400
Definition at line 64 of file x86id.h.
HW_FMA
#define HW_FMA 0x00000080
Definition at line 61 of file x86id.h.
HW_FMA4
#define HW_FMA4 0x00000100
Definition at line 62 of file x86id.h.
HW_KNL
#define HW_KNL 0x00000200
Definition at line 63 of file x86id.h.
HW_SSE
#define HW_SSE 0x00000001
Definition at line 54 of file x86id.h.
HW_SSE4
#define HW_SSE4 0x00000002
Definition at line 55 of file x86id.h.
HW_SSSE3
#define HW_SSSE3 0x00000800
Definition at line 65 of file x86id.h.
IS_CONCAT3
#define IS_CONCAT3 (l, m, r) IS_CONCAT3_(l,m,r)
Definition at line 72 of file x86id.h.
IS_CONCAT3_
#define IS_CONCAT3_ (l, m, r) l##m##r
Definition at line 71 of file x86id.h.
IS_X86ID
#define IS_X86ID (f)
Value:
    (X86IDFN(IS_CONCAT3(is_,f,_cached)) != X86ID_IS_CACHED_UNDEF) ?           \
        X86IDFN(IS_CONCAT3(is_,f,_cached)) : X86IDFN(IS_CONCAT3(is_,f,))()
Definition at line 74 of file x86id.h.
X86ID_IS_CACHED_UNDEF
#define X86ID_IS_CACHED_UNDEF (-1)
Definition at line 15 of file x86id.h.
X86IDFN
#define X86IDFN (n) X86IDFN_(__Cpuid_,n)
Definition at line 13 of file x86id.h.
X86IDFN_
#define X86IDFN_ (l, r) l##r
Definition at line 12 of file x86id.h.
Function Documentation
get_cachesize()
DECLEXTERN int X86IDFN() get_cachesize (void)
Definition at line 1180 of file x86id.c.
References amd_cachesize(), ia_cachesize(), is_amd(), is_intel(), and X86IDFN().
get_cores()
int X86IDFN() get_cores (void)
get_processor_name()
DECLEXTERN char *X86IDFN() get_processor_name (void)
Definition at line 1237 of file x86id.c.
References CPU80::b, DEBUG_PRINTF, i, CPU80::i, idcache(), CPU80::largest, processor_name, and X86IDFN().
is_aes()
DECLEXTERN int X86IDFN() is_aes (void)
Definition at line 394 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_amd(), is_intel(), ICPU1::u, and X86IDFN().
is_amd()
DECLEXTERN int X86IDFN() is_amd (void)
Definition at line 234 of file x86id.c.
is_athlon()
DECLEXTERN int X86IDFN() is_athlon (void)
Definition at line 587 of file x86id.c.
References DEBUG_PRINTF, ACPU1::eax, ACPU1::i, idcache(), is_amd(), ACPU1::u, and X86IDFN().
is_avx()
DECLEXTERN int X86IDFN() is_avx (void)
Definition at line 410 of file x86id.c.
is_avx2()
DECLEXTERN int X86IDFN() is_avx2 (void)
Definition at line 434 of file x86id.c.
is_avx512()
DECLEXTERN int X86IDFN() is_avx512 (void)
Definition at line 458 of file x86id.c.
is_avx512f()
DECLEXTERN int X86IDFN() is_avx512f (void)
Definition at line 473 of file x86id.c.
is_avx512vl()
DECLEXTERN int X86IDFN() is_avx512vl (void)
Definition at line 490 of file x86id.c.
is_bulldozer()
DECLEXTERN int X86IDFN() is_bulldozer (void)
Definition at line 756 of file x86id.c.
References DEBUG_PRINTF, ACPU1::eax, ACPU1::i, idcache(), is_amd(), ACPU1::u, and X86IDFN().
Referenced by is_piledriver().
is_f16c()
DECLEXTERN int X86IDFN() is_f16c (void)
Definition at line 507 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_amd(), is_avx(), is_intel(), ICPU1::u, and X86IDFN().
Referenced by init_hw_features().
is_fma()
DECLEXTERN int X86IDFN() is_fma (void)
Definition at line 530 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_amd(), is_intel(), ICPU1::u, and X86IDFN().
Referenced by init_hw_features(), and is_piledriver().
is_fma4()
DECLEXTERN int X86IDFN() is_fma4 (void)
Definition at line 546 of file x86id.c.
is_gh()
DECLEXTERN int X86IDFN() is_gh (void)
Definition at line 634 of file x86id.c.
References DEBUG_PRINTF, ACPU1::eax, ACPU1::i, idcache(), is_amd(), ACPU1::u, and X86IDFN().
Referenced by is_gh_a(), is_gh_b(), and is_shanghai().
is_gh_a()
DECLEXTERN int X86IDFN() is_gh_a (void)
Definition at line 652 of file x86id.c.
References DEBUG_PRINTF, ACPU1::eax, ACPU1::i, idcache(), is_gh(), ACPU1::u, and X86IDFN().
is_gh_b()
DECLEXTERN int X86IDFN() is_gh_b (void)
Definition at line 700 of file x86id.c.
References DEBUG_PRINTF, ACPU1::eax, ACPU1::i, idcache(), is_gh(), ACPU1::u, and X86IDFN().
is_hammer()
DECLEXTERN int X86IDFN() is_hammer (void)
Definition at line 616 of file x86id.c.
References DEBUG_PRINTF, ACPU1::eax, ACPU1::i, idcache(), is_amd(), ACPU1::u, and X86IDFN().
is_ht()
DECLEXTERN int X86IDFN() is_ht (void)
Definition at line 567 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ebx, ICPU1::edx, ICPU1::i, idcache(), is_intel(), ICPU1::u, and X86IDFN().
is_ia32e()
DECLEXTERN int X86IDFN() is_ia32e (void)
Definition at line 802 of file x86id.c.
References CPU80::b, DEBUG_PRINTF, ICPU1::eax, ICPU81::edx, CPU80::i, ICPU1::i, ICPU81::i, idcache(), is_intel(), CPU80::largest, ICPU1::u, ICPU81::u, and X86IDFN().
is_intel()
DECLEXTERN int X86IDFN() is_intel (void)
Definition at line 214 of file x86id.c.
is_ip6()
DECLEXTERN int X86IDFN() is_ip6 (void)
Definition at line 254 of file x86id.c.
References DEBUG_PRINTF, ICPU1::edx, ICPU1::i, idcache(), ICPU1::u, and X86IDFN().
is_istanbul()
DECLEXTERN int X86IDFN() is_istanbul (void)
Definition at line 739 of file x86id.c.
References ACPU1::eax, ACPU1::i, idcache(), is_shanghai(), ACPU1::u, and X86IDFN().
is_k7()
DECLEXTERN int X86IDFN() is_k7 (void)
Definition at line 784 of file x86id.c.
References DEBUG_PRINTF, ACPU1::eax, ACPU1::i, idcache(), is_amd(), ACPU1::u, and X86IDFN().
is_knl()
DECLEXTERN int X86IDFN() is_knl (void)
Definition at line 851 of file x86id.c.
References DEBUG_PRINTF, ICPU1::eax, ICPU1::i, idcache(), is_intel(), ICPU1::u, and X86IDFN().
Referenced by init_hw_features().
is_p4()
DECLEXTERN int X86IDFN() is_p4 (void)
Definition at line 833 of file x86id.c.
References DEBUG_PRINTF, ICPU1::eax, ICPU1::i, idcache(), is_intel(), ICPU1::u, and X86IDFN().
is_piledriver()
DECLEXTERN int X86IDFN() is_piledriver (void)
Definition at line 773 of file x86id.c.
References is_bulldozer(), is_fma(), and X86IDFN().
is_shanghai()
DECLEXTERN int X86IDFN() is_shanghai (void)
Definition at line 718 of file x86id.c.
References CPU80::b, CPU80::i, ACPU86::i, idcache(), is_gh(), ACPU86::l3cache, CPU80::largest, ACPU86::u, and X86IDFN().
Referenced by is_istanbul().
is_sse()
DECLEXTERN int X86IDFN() is_sse (void)
Definition at line 272 of file x86id.c.
References DEBUG_PRINTF, ICPU1::edx, ICPU1::i, idcache(), is_amd(), is_intel(), ICPU1::u, and X86IDFN().
is_sse2()
DECLEXTERN int X86IDFN() is_sse2 (void)
Definition at line 290 of file x86id.c.
References DEBUG_PRINTF, ICPU1::edx, ICPU1::i, idcache(), is_amd(), is_intel(), ICPU1::u, and X86IDFN().
is_sse3()
DECLEXTERN int X86IDFN() is_sse3 (void)
Definition at line 307 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_amd(), is_intel(), ICPU1::u, and X86IDFN().
Referenced by init_hw_features().
is_sse41()
DECLEXTERN int X86IDFN() is_sse41 (void)
Definition at line 362 of file x86id.c.
is_sse42()
DECLEXTERN int X86IDFN() is_sse42 (void)
Definition at line 378 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_amd(), is_intel(), ICPU1::u, and X86IDFN().
Referenced by init_hw_features().
is_sse4a()
DECLEXTERN int X86IDFN() is_sse4a (void)
Definition at line 342 of file x86id.c.
is_ssse3()
DECLEXTERN int X86IDFN() is_ssse3 (void)
Definition at line 325 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_amd(), is_intel(), ICPU1::u, and X86IDFN().
Referenced by init_hw_features().
is_x86_64()
DECLEXTERN int X86IDFN() is_x86_64 (void)
Definition at line 872 of file x86id.c.
References CPU80::b, DEBUG_PRINTF, ICPU81::edx, CPU80::i, ICPU81::i, idcache(), CPU80::largest, ICPU81::u, and X86IDFN().
X86IDFN() [1/35]
DECLEXTERN uint32_t X86IDFN (hw_features)
X86IDFN() [2/35]
DECLEXTERN int X86IDFN (is_aes_cached)
X86IDFN() [3/35]
DECLEXTERN int X86IDFN (is_amd_cached)
X86IDFN() [4/35]
DECLEXTERN int X86IDFN (is_athlon_cached)
X86IDFN() [5/35]
DECLEXTERN int X86IDFN (is_avx2_cached)
X86IDFN() [6/35]
DECLEXTERN int X86IDFN (is_avx512_cached)
X86IDFN() [7/35]
DECLEXTERN int X86IDFN (is_avx512f_cached)
X86IDFN() [8/35]
DECLEXTERN int X86IDFN (is_avx512vl_cached)
X86IDFN() [9/35]
DECLEXTERN int X86IDFN (is_avx_cached)
X86IDFN() [10/35]
DECLEXTERN int X86IDFN (is_bulldozer_cached)
X86IDFN() [11/35]
DECLEXTERN int X86IDFN (is_f16c_cached)
X86IDFN() [12/35]
DECLEXTERN int X86IDFN (is_fma4_cached)
X86IDFN() [13/35]
DECLEXTERN int X86IDFN (is_fma_cached)
X86IDFN() [14/35]
DECLEXTERN int X86IDFN (is_gh_a_cached)
X86IDFN() [15/35]
DECLEXTERN int X86IDFN (is_gh_b_cached)
X86IDFN() [16/35]
DECLEXTERN int X86IDFN (is_gh_cached)
X86IDFN() [17/35]
DECLEXTERN int X86IDFN (is_hammer_cached)
X86IDFN() [18/35]
DECLEXTERN int X86IDFN (is_ht_cached)
X86IDFN() [19/35]
DECLEXTERN int X86IDFN (is_ia32e_cached)
X86IDFN() [20/35]
DECLEXTERN int X86IDFN (is_intel_cached)
X86IDFN() [21/35]
DECLEXTERN int X86IDFN (is_ip6_cached)
X86IDFN() [22/35]
DECLEXTERN int X86IDFN (is_istanbul_cached)
X86IDFN() [23/35]
DECLEXTERN int X86IDFN (is_k7_cached)
X86IDFN() [24/35]
DECLEXTERN int X86IDFN (is_knl_cached)
X86IDFN() [25/35]
DECLEXTERN int X86IDFN (is_p4_cached)
X86IDFN() [26/35]
DECLEXTERN int X86IDFN (is_piledriver_cached)
X86IDFN() [27/35]
DECLEXTERN int X86IDFN (is_shanghai_cached)
X86IDFN() [28/35]
DECLEXTERN int X86IDFN (is_sse2_cached)
X86IDFN() [29/35]
DECLEXTERN int X86IDFN (is_sse3_cached)
X86IDFN() [30/35]
DECLEXTERN int X86IDFN (is_sse41_cached)
X86IDFN() [31/35]
DECLEXTERN int X86IDFN (is_sse42_cached)
X86IDFN() [32/35]
DECLEXTERN int X86IDFN (is_sse4a_cached)
X86IDFN() [33/35]
DECLEXTERN int X86IDFN (is_sse_cached)
X86IDFN() [34/35]
DECLEXTERN int X86IDFN (is_ssse3_cached)
X86IDFN() [35/35]
DECLEXTERN int X86IDFN (is_x86_64_cached)