flang: x86id.c File Reference
x86id.c File Reference
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include "pgcpuid.h"
#include "x86id.h"
Macros
#define xcr0_bit_XMM 0x00000002U
#define xcr0_bit_YMM 0x00000004U
#define xcr0_bit_ZMMK 0x00000020U
#define xcr0_bit_ZMMLO 0x00000040U
#define xcr0_bit_ZMMHI 0x00000080U
#define xcr0_mask_YMM (xcr0_bit_XMM | xcr0_bit_YMM)
#define xcr0_mask_ZMM (xcr0_bit_ZMMK | xcr0_bit_ZMMLO | xcr0_bit_ZMMHI)
#define signature_AMD_ebx 0x68747541
#define signature_AMD_ecx 0x444d4163
#define signature_AMD_edx 0x69746e65
#define signature_INTEL_ebx 0x756e6547
#define signature_INTEL_ecx 0x6c65746e
#define signature_INTEL_edx 0x49656e69
#define DEBUG_PRINTF(...)
Functions
static int ia_cachesize (void)
static int ia_unifiedcache (void)
static int amd_cachesize (void)
static int ia_cores (void)
static int amd_cores (void)
static int is_xcr_set (uint32_t, uint64_t)
static int is_amd_family (uint32_t, uint32_t *)
uint32_t X86IDFN (hw_features)=0
int X86IDFN (is_intel_cached)
int X86IDFN (is_amd_cached)
int X86IDFN (is_ip6_cached)
int X86IDFN (is_sse_cached)
int X86IDFN (is_sse2_cached)
int X86IDFN (is_sse3_cached)
int X86IDFN (is_ssse3_cached)
int X86IDFN (is_sse4a_cached)
int X86IDFN (is_sse41_cached)
int X86IDFN (is_sse42_cached)
int X86IDFN (is_aes_cached)
int X86IDFN (is_avx_cached)
int X86IDFN (is_avx2_cached)
int X86IDFN (is_avx512_cached)
int X86IDFN (is_avx512f_cached)
int X86IDFN (is_avx512vl_cached)
int X86IDFN (is_fma_cached)
int X86IDFN (is_fma4_cached)
int X86IDFN (is_ht_cached)
int X86IDFN (is_athlon_cached)
int X86IDFN (is_hammer_cached)
int X86IDFN (is_gh_cached)
int X86IDFN (is_gh_a_cached)
int X86IDFN (is_gh_b_cached)
int X86IDFN (is_shanghai_cached)
int X86IDFN (is_istanbul_cached)
int X86IDFN (is_bulldozer_cached)
int X86IDFN (is_piledriver_cached)
int X86IDFN (is_k7_cached)
int X86IDFN (is_ia32e_cached)
int X86IDFN (is_p4_cached)
int X86IDFN (is_knl_cached)
int X86IDFN (is_x86_64_cached)
int X86IDFN (is_f16c_cached)
int X86IDFN() idcache (uint32_t f, uint32_t *r)
int X86IDFN() is_intel (void)
int X86IDFN() is_amd (void)
int X86IDFN() is_ip6 (void)
int X86IDFN() is_sse (void)
int X86IDFN() is_sse2 (void)
int X86IDFN() is_sse3 (void)
int X86IDFN() is_ssse3 (void)
int X86IDFN() is_sse4a (void)
int X86IDFN() is_sse41 (void)
int X86IDFN() is_sse42 (void)
int X86IDFN() is_aes (void)
int X86IDFN() is_avx (void)
int X86IDFN() is_avx2 (void)
int X86IDFN() is_avx512 (void)
int X86IDFN() is_avx512f (void)
int X86IDFN() is_avx512vl (void)
int X86IDFN() is_f16c (void)
int X86IDFN() is_fma (void)
int X86IDFN() is_fma4 (void)
int X86IDFN() is_ht (void)
int X86IDFN() is_athlon (void)
int X86IDFN() is_hammer (void)
int X86IDFN() is_gh (void)
int X86IDFN() is_gh_a (void)
int X86IDFN() is_gh_b (void)
int X86IDFN() is_shanghai (void)
int X86IDFN() is_istanbul (void)
int X86IDFN() is_bulldozer (void)
int X86IDFN() is_piledriver (void)
int X86IDFN() is_k7 (void)
int X86IDFN() is_ia32e (void)
int X86IDFN() is_p4 (void)
int X86IDFN() is_knl (void)
int X86IDFN() is_x86_64 (void)
uint32_t X86IDFN() init_hw_features (uint32_t old_hw_features)
static int ia_cachecode (int code)
int X86IDFN() get_cachesize (void)
char *X86IDFN() get_processor_name (void)
Variables
static char processor_name [50]
Macro Definition Documentation
DEBUG_PRINTF
#define DEBUG_PRINTF (...)
Definition at line 59 of file x86id.c.
signature_AMD_ebx
#define signature_AMD_ebx 0x68747541
Definition at line 39 of file x86id.c.
signature_AMD_ecx
#define signature_AMD_ecx 0x444d4163
Definition at line 40 of file x86id.c.
signature_AMD_edx
#define signature_AMD_edx 0x69746e65
Definition at line 41 of file x86id.c.
signature_INTEL_ebx
#define signature_INTEL_ebx 0x756e6547
Definition at line 43 of file x86id.c.
signature_INTEL_ecx
#define signature_INTEL_ecx 0x6c65746e
Definition at line 44 of file x86id.c.
signature_INTEL_edx
#define signature_INTEL_edx 0x49656e69
Definition at line 45 of file x86id.c.
xcr0_bit_XMM
#define xcr0_bit_XMM 0x00000002U
Definition at line 29 of file x86id.c.
xcr0_bit_YMM
#define xcr0_bit_YMM 0x00000004U
Definition at line 30 of file x86id.c.
xcr0_bit_ZMMHI
#define xcr0_bit_ZMMHI 0x00000080U
Definition at line 33 of file x86id.c.
xcr0_bit_ZMMK
#define xcr0_bit_ZMMK 0x00000020U
Definition at line 31 of file x86id.c.
xcr0_bit_ZMMLO
#define xcr0_bit_ZMMLO 0x00000040U
Definition at line 32 of file x86id.c.
xcr0_mask_YMM
#define xcr0_mask_YMM (xcr0_bit_XMM | xcr0_bit_YMM)
Definition at line 35 of file x86id.c.
xcr0_mask_ZMM
#define xcr0_mask_ZMM (xcr0_bit_ZMMK | xcr0_bit_ZMMLO | xcr0_bit_ZMMHI)
Definition at line 36 of file x86id.c.
Function Documentation
amd_cachesize()
static int amd_cachesize (void) static
Definition at line 1157 of file x86id.c.
References CPU80::b, DEBUG_PRINTF, CPU80::i, ACPU86::i, idcache(), ACPU86::l2cache, ACPU86::l3cache, CPU80::largest, ACPU86::u, and X86IDFN().
Referenced by get_cachesize().
amd_cores()
static int amd_cores (void) static
Definition at line 1216 of file x86id.c.
References CPU80::b, DEBUG_PRINTF, ACPU88::ecx, CPU80::i, ACPU88::i, idcache(), CPU80::largest, ACPU88::u, and X86IDFN().
get_cachesize()
int X86IDFN() get_cachesize (void)
Definition at line 1180 of file x86id.c.
References amd_cachesize(), ia_cachesize(), is_amd(), is_intel(), and X86IDFN().
get_processor_name()
char *X86IDFN() get_processor_name (void)
Definition at line 1237 of file x86id.c.
References CPU80::b, DEBUG_PRINTF, i, CPU80::i, idcache(), CPU80::largest, processor_name, and X86IDFN().
ia_cachecode()
static int ia_cachecode (int code) static
Definition at line 986 of file x86id.c.
Referenced by ia_cachesize().
ia_cachesize()
static int ia_cachesize (void) static
Definition at line 1027 of file x86id.c.
References CPU0::b, CPU80::b, ICPU2::Int_Cache::c1, ICPU2::Int_Cache::c2, ICPU2::Int_Cache::c3, ICPU2::Int_Cache::c4, DEBUG_PRINTF, ICPU86::ecx, i, CPU0::i, CPU80::i, ICPU2::i, ICPU86::i, ia_cachecode(), ia_unifiedcache(), idcache(), ICPU2::Int_Cache::invalid, CPU0::largest, CPU80::largest, n, r, ICPU2::u, ICPU86::u, and X86IDFN().
Referenced by get_cachesize().
ia_cores()
static int ia_cores (void) static
Definition at line 1193 of file x86id.c.
References __pgi_cpuid_ecx(), CPU0::b, DEBUG_PRINTF, ICPU4::eax, i, CPU0::i, ICPU4::i, idcache(), CPU0::largest, n, r, ICPU4::u, and X86IDFN().
ia_unifiedcache()
static int ia_unifiedcache (void) static
Definition at line 1091 of file x86id.c.
References __pgi_cpuid_ecx(), DEBUG_PRINTF, ICPU4::eax, ICPU4::ebx, i, ICPU4::i, n, ICPU4::nsets, r, and ICPU4::u.
Referenced by ia_cachesize().
idcache()
int X86IDFN() idcache (uint32_t f, uint32_t * r)
Definition at line 148 of file x86id.c.
References __pgi_cpuid(), f, i, j, r, and set.
Referenced by amd_cachesize(), amd_cores(), get_processor_name(), ia_cachesize(), ia_cores(), is_aes(), is_amd(), is_amd_family(), is_athlon(), is_avx(), is_bulldozer(), is_f16c(), is_fma(), is_fma4(), is_gh(), is_gh_a(), is_gh_b(), is_hammer(), is_ht(), is_ia32e(), is_intel(), is_ip6(), is_istanbul(), is_k7(), is_knl(), is_p4(), is_shanghai(), is_sse(), is_sse2(), is_sse3(), is_sse41(), is_sse42(), is_sse4a(), is_ssse3(), and is_x86_64().
init_hw_features()
uint32_t X86IDFN() init_hw_features (uint32_t old_hw_features)
Definition at line 894 of file x86id.c.
References HW_AVX, HW_AVX2, HW_AVX512, HW_AVX512F, HW_AVX512VL, HW_F16C, HW_FMA, HW_FMA4, HW_KNL, HW_SSE, HW_SSE4, HW_SSSE3, is_avx(), is_avx2(), is_avx512(), is_avx512f(), is_avx512vl(), is_f16c(), is_fma(), is_fma4(), is_knl(), is_sse3(), is_sse42(), is_ssse3(), and X86IDFN().
is_aes()
int X86IDFN() is_aes (void)
Definition at line 394 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_amd(), is_intel(), ICPU1::u, and X86IDFN().
is_amd()
int X86IDFN() is_amd (void)
Definition at line 234 of file x86id.c.
References DEBUG_PRINTF, h, CPU0::i, idcache(), signature_AMD_ebx, signature_AMD_ecx, signature_AMD_edx, and X86IDFN().
Referenced by get_arch(), get_cachesize(), is_aes(), is_amd_family(), is_athlon(), is_avx(), is_avx2(), is_bulldozer(), is_f16c(), is_fma(), is_fma4(), is_gh(), is_hammer(), is_k7(), is_sse(), is_sse2(), is_sse3(), is_sse42(), is_sse4a(), and is_ssse3().
is_amd_family()
static int is_amd_family (uint32_t family, uint32_t * model) static
Definition at line 196 of file x86id.c.
References DEBUG_PRINTF, ACPU1::eax, ACPU1::i, idcache(), is_amd(), ACPU1::u, and X86IDFN().
is_athlon()
int X86IDFN() is_athlon (void)
Definition at line 587 of file x86id.c.
References DEBUG_PRINTF, ACPU1::eax, ACPU1::i, idcache(), is_amd(), ACPU1::u, and X86IDFN().
is_avx()
int X86IDFN() is_avx (void)
Definition at line 410 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_amd(), is_intel(), is_xcr_set(), ICPU1::u, X86IDFN(), and xcr0_mask_YMM.
Referenced by get_arch(), init_hw_features(), is_avx2(), is_avx512(), and is_f16c().
is_avx2()
int X86IDFN() is_avx2 (void)
Definition at line 434 of file x86id.c.
References __pgi_cpuid_ecx(), DEBUG_PRINTF, ICPU7::ebx, ICPU7::i, is_amd(), is_avx(), is_intel(), ICPU7::u, and X86IDFN().
Referenced by get_arch(), and init_hw_features().
is_avx512()
int X86IDFN() is_avx512 (void)
Definition at line 458 of file x86id.c.
References is_avx(), is_intel(), is_xcr_set(), X86IDFN(), and xcr0_mask_ZMM.
Referenced by init_hw_features(), and is_avx512f().
is_avx512f()
int X86IDFN() is_avx512f (void)
Definition at line 473 of file x86id.c.
References __pgi_cpuid_ecx(), DEBUG_PRINTF, ICPU7::ebx, ICPU7::i, is_avx512(), ICPU7::u, and X86IDFN().
Referenced by get_arch(), init_hw_features(), and is_avx512vl().
is_avx512vl()
int X86IDFN() is_avx512vl (void)
Definition at line 490 of file x86id.c.
References __pgi_cpuid_ecx(), DEBUG_PRINTF, ICPU7::ebx, ICPU7::i, is_avx512f(), ICPU7::u, and X86IDFN().
Referenced by get_arch(), and init_hw_features().
is_bulldozer()
int X86IDFN() is_bulldozer (void)
Definition at line 756 of file x86id.c.
References DEBUG_PRINTF, ACPU1::eax, ACPU1::i, idcache(), is_amd(), ACPU1::u, and X86IDFN().
Referenced by is_piledriver().
is_f16c()
int X86IDFN() is_f16c (void)
Definition at line 507 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_amd(), is_avx(), is_intel(), ICPU1::u, and X86IDFN().
Referenced by init_hw_features().
is_fma()
int X86IDFN() is_fma (void)
Definition at line 530 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_amd(), is_intel(), ICPU1::u, and X86IDFN().
Referenced by init_hw_features(), and is_piledriver().
is_fma4()
int X86IDFN() is_fma4 (void)
Definition at line 546 of file x86id.c.
References CPU80::b, ACPU81::ecx, CPU80::i, ACPU81::i, idcache(), is_amd(), CPU80::largest, ACPU81::u, and X86IDFN().
Referenced by get_arch(), and init_hw_features().
is_gh()
int X86IDFN() is_gh (void)
Definition at line 634 of file x86id.c.
References DEBUG_PRINTF, ACPU1::eax, ACPU1::i, idcache(), is_amd(), ACPU1::u, and X86IDFN().
Referenced by is_gh_a(), is_gh_b(), and is_shanghai().
is_gh_a()
int X86IDFN() is_gh_a (void)
Definition at line 652 of file x86id.c.
References DEBUG_PRINTF, ACPU1::eax, ACPU1::i, idcache(), is_gh(), ACPU1::u, and X86IDFN().
is_gh_b()
int X86IDFN() is_gh_b (void)
Definition at line 700 of file x86id.c.
References DEBUG_PRINTF, ACPU1::eax, ACPU1::i, idcache(), is_gh(), ACPU1::u, and X86IDFN().
is_hammer()
int X86IDFN() is_hammer (void)
Definition at line 616 of file x86id.c.
References DEBUG_PRINTF, ACPU1::eax, ACPU1::i, idcache(), is_amd(), ACPU1::u, and X86IDFN().
is_ht()
int X86IDFN() is_ht (void)
Definition at line 567 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ebx, ICPU1::edx, ICPU1::i, idcache(), is_intel(), ICPU1::u, and X86IDFN().
is_ia32e()
int X86IDFN() is_ia32e (void)
Definition at line 802 of file x86id.c.
References CPU80::b, DEBUG_PRINTF, ICPU1::eax, ICPU81::edx, CPU80::i, ICPU1::i, ICPU81::i, idcache(), is_intel(), CPU80::largest, ICPU1::u, ICPU81::u, and X86IDFN().
is_intel()
int X86IDFN() is_intel (void)
Definition at line 214 of file x86id.c.
References DEBUG_PRINTF, h, CPU0::i, idcache(), signature_INTEL_ebx, signature_INTEL_ecx, signature_INTEL_edx, and X86IDFN().
Referenced by get_arch(), get_cachesize(), is_aes(), is_avx(), is_avx2(), is_avx512(), is_f16c(), is_fma(), is_ht(), is_ia32e(), is_knl(), is_p4(), is_sse(), is_sse2(), is_sse3(), is_sse41(), is_sse42(), and is_ssse3().
is_ip6()
int X86IDFN() is_ip6 (void)
Definition at line 254 of file x86id.c.
References DEBUG_PRINTF, ICPU1::edx, ICPU1::i, idcache(), ICPU1::u, and X86IDFN().
is_istanbul()
int X86IDFN() is_istanbul (void)
Definition at line 739 of file x86id.c.
References ACPU1::eax, ACPU1::i, idcache(), is_shanghai(), ACPU1::u, and X86IDFN().
is_k7()
int X86IDFN() is_k7 (void)
Definition at line 784 of file x86id.c.
References DEBUG_PRINTF, ACPU1::eax, ACPU1::i, idcache(), is_amd(), ACPU1::u, and X86IDFN().
is_knl()
int X86IDFN() is_knl (void)
Definition at line 851 of file x86id.c.
References DEBUG_PRINTF, ICPU1::eax, ICPU1::i, idcache(), is_intel(), ICPU1::u, and X86IDFN().
Referenced by init_hw_features().
is_p4()
int X86IDFN() is_p4 (void)
Definition at line 833 of file x86id.c.
References DEBUG_PRINTF, ICPU1::eax, ICPU1::i, idcache(), is_intel(), ICPU1::u, and X86IDFN().
is_piledriver()
int X86IDFN() is_piledriver (void)
Definition at line 773 of file x86id.c.
References is_bulldozer(), is_fma(), and X86IDFN().
is_shanghai()
int X86IDFN() is_shanghai (void)
Definition at line 718 of file x86id.c.
References CPU80::b, CPU80::i, ACPU86::i, idcache(), is_gh(), ACPU86::l3cache, CPU80::largest, ACPU86::u, and X86IDFN().
Referenced by is_istanbul().
is_sse()
int X86IDFN() is_sse (void)
Definition at line 272 of file x86id.c.
References DEBUG_PRINTF, ICPU1::edx, ICPU1::i, idcache(), is_amd(), is_intel(), ICPU1::u, and X86IDFN().
is_sse2()
int X86IDFN() is_sse2 (void)
Definition at line 290 of file x86id.c.
References DEBUG_PRINTF, ICPU1::edx, ICPU1::i, idcache(), is_amd(), is_intel(), ICPU1::u, and X86IDFN().
is_sse3()
int X86IDFN() is_sse3 (void)
Definition at line 307 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_amd(), is_intel(), ICPU1::u, and X86IDFN().
Referenced by init_hw_features().
is_sse41()
int X86IDFN() is_sse41 (void)
Definition at line 362 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_intel(), ICPU1::u, and X86IDFN().
Referenced by get_arch().
is_sse42()
int X86IDFN() is_sse42 (void)
Definition at line 378 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_amd(), is_intel(), ICPU1::u, and X86IDFN().
Referenced by init_hw_features().
is_sse4a()
int X86IDFN() is_sse4a (void)
Definition at line 342 of file x86id.c.
References CPU80::b, ACPU81::ecx, CPU80::i, ACPU81::i, idcache(), is_amd(), CPU80::largest, ACPU81::u, and X86IDFN().
Referenced by get_arch().
is_ssse3()
int X86IDFN() is_ssse3 (void)
Definition at line 325 of file x86id.c.
References DEBUG_PRINTF, ICPU1::ecx, ICPU1::i, idcache(), is_amd(), is_intel(), ICPU1::u, and X86IDFN().
Referenced by init_hw_features().
is_x86_64()
int X86IDFN() is_x86_64 (void)
Definition at line 872 of file x86id.c.
References CPU80::b, DEBUG_PRINTF, ICPU81::edx, CPU80::i, ICPU81::i, idcache(), CPU80::largest, ICPU81::u, and X86IDFN().
is_xcr_set()
static int is_xcr_set (uint32_t xcr_indx, uint64_t xcr_mask) static
Definition at line 128 of file x86id.c.
References __pgi_getbv(), and DEBUG_PRINTF.
Referenced by is_avx(), and is_avx512().
X86IDFN() [1/35]
uint32_t X86IDFN (hw_features) pure virtual
Referenced by amd_cachesize(), amd_cores(), get_cachesize(), get_processor_name(), ia_cachesize(), ia_cores(), init_hw_features(), is_aes(), is_amd(), is_amd_family(), is_athlon(), is_avx(), is_avx2(), is_avx512(), is_avx512f(), is_avx512vl(), is_bulldozer(), is_f16c(), is_fma(), is_fma4(), is_gh(), is_gh_a(), is_gh_b(), is_hammer(), is_ht(), is_ia32e(), is_intel(), is_ip6(), is_istanbul(), is_k7(), is_knl(), is_p4(), is_piledriver(), is_shanghai(), is_sse(), is_sse2(), is_sse3(), is_sse41(), is_sse42(), is_sse4a(), is_ssse3(), and is_x86_64().
X86IDFN() [2/35]
int X86IDFN (is_aes_cached)
X86IDFN() [3/35]
int X86IDFN (is_amd_cached)
X86IDFN() [4/35]
int X86IDFN (is_athlon_cached)
X86IDFN() [5/35]
int X86IDFN (is_avx2_cached)
X86IDFN() [6/35]
int X86IDFN (is_avx512_cached)
X86IDFN() [7/35]
int X86IDFN (is_avx512f_cached)
X86IDFN() [8/35]
int X86IDFN (is_avx512vl_cached)
X86IDFN() [9/35]
int X86IDFN (is_avx_cached)
X86IDFN() [10/35]
int X86IDFN (is_bulldozer_cached)
X86IDFN() [11/35]
int X86IDFN (is_f16c_cached)
X86IDFN() [12/35]
int X86IDFN (is_fma4_cached)
X86IDFN() [13/35]
int X86IDFN (is_fma_cached)
X86IDFN() [14/35]
int X86IDFN (is_gh_a_cached)
X86IDFN() [15/35]
int X86IDFN (is_gh_b_cached)
X86IDFN() [16/35]
int X86IDFN (is_gh_cached)
X86IDFN() [17/35]
int X86IDFN (is_hammer_cached)
X86IDFN() [18/35]
int X86IDFN (is_ht_cached)
X86IDFN() [19/35]
int X86IDFN (is_ia32e_cached)
X86IDFN() [20/35]
int X86IDFN (is_intel_cached)
X86IDFN() [21/35]
int X86IDFN (is_ip6_cached)
X86IDFN() [22/35]
int X86IDFN (is_istanbul_cached)
X86IDFN() [23/35]
int X86IDFN (is_k7_cached)
X86IDFN() [24/35]
int X86IDFN (is_knl_cached)
X86IDFN() [25/35]
int X86IDFN (is_p4_cached)
X86IDFN() [26/35]
int X86IDFN (is_piledriver_cached)
X86IDFN() [27/35]
int X86IDFN (is_shanghai_cached)
X86IDFN() [28/35]
int X86IDFN (is_sse2_cached)
X86IDFN() [29/35]
int X86IDFN (is_sse3_cached)
X86IDFN() [30/35]
int X86IDFN (is_sse41_cached)
X86IDFN() [31/35]
int X86IDFN (is_sse42_cached)
X86IDFN() [32/35]
int X86IDFN (is_sse4a_cached)
X86IDFN() [33/35]
int X86IDFN (is_sse_cached)
X86IDFN() [34/35]
int X86IDFN (is_ssse3_cached)
X86IDFN() [35/35]
int X86IDFN (is_x86_64_cached)
Variable Documentation
processor_name
char processor_name[50] static
Definition at line 1235 of file x86id.c.
Referenced by get_processor_name().