flang: xfer.c File Reference
xfer.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
Macros
#define DEFENTS (512)
#define GBUFA 4096 /* global buffer size alignment */
#define MINSHIFT 1024 /* smaller send values may be send */
Functions
struct chdr * __fort_allchn (struct chdr *cp, int dents, int sents, int cpus)
void __fort_frechn (struct chdr *c)
void __fort_rstchn (struct chdr *c)
void __fort_sendl (struct chdr *c, int indx, void *adr, long cnt, long str, int typ, long ilen)
void __fort_recvl (struct chdr *c, int indx, void *adr, long cnt, long str, int typ, long ilen)
struct chdr * __fort_chain_em_up (struct chdr *list, struct chdr *c)
void __fort_adjbase (struct chdr *c, char *bases, char *baser, int typ, long ilen)
void __fort_setbase (chdr *c, char *bases, char *baser, int typ, long ilen)
char * __fort_getgbuf (long len)
void __fort_chn_prune (struct chdr *c)
Variables
static int gbufz
static char * gbuf
Macro Definition Documentation
DEFENTS
#define DEFENTS (512)
Definition at line 11 of file xfer.c.
GBUFA
#define GBUFA 4096 /* global buffer size alignment */
Definition at line 339 of file xfer.c.
MINSHIFT
#define MINSHIFT 1024 /* smaller send values may be send */
Definition at line 361 of file xfer.c.
Function Documentation
__fort_adjbase()
void __fort_adjbase (struct chdr * c, char * bases, char * baser, int typ, long ilen)
Definition at line 220 of file xfer.c.
References __fort_abort(), avl, CHDR_1DBL, CHDR_1INT, CHDR_BASE, ent::ilen, n, p, and ent::typ.
Referenced by comm_sked_start(), gathscat_start(), and olap_start().
__fort_allchn()
struct chdr * __fort_allchn (struct chdr * cp, int dents, int sents, int cpus)
Definition at line 16 of file xfer.c.
References __fort_calloc(), c, CHDR_1DBL, CHDR_1INT, cp, and chdr::next.
__fort_chain_em_up()
struct chdr * __fort_chain_em_up (struct chdr * list, struct chdr * c)
Definition at line 202 of file xfer.c.
References c, list, and chdr::next.
Referenced by __fort_copy(), cshift_loop(), and ENTFTN().
__fort_chn_prune()
void __fort_chn_prune (struct chdr * c)
Definition at line 364 of file xfer.c.
References m, and n.
Referenced by __fort_copy(), __fort_exchange_counts(), ENTFTN(), and olap_shift().
__fort_frechn()
void __fort_frechn (struct chdr * c)
Definition at line 53 of file xfer.c.
References __fort_free(), d, and n.
Referenced by comm_sked_free(), cshift_loop(), ENTFTN(), eoshift_scalar(), gathscat_free(), olap_free(), and recopy().
__fort_getgbuf()
char * __fort_getgbuf (long len)
Definition at line 345 of file xfer.c.
References __fort_gfree(), __fort_gmalloc(), gbuf, GBUFA, gbufz, and len.
Referenced by __fort_pull_them_in(), and __io_read().
__fort_recvl()
void __fort_recvl (struct chdr * c, int indx, void * adr, long cnt, long str, int typ, long ilen)
Definition at line 151 of file xfer.c.
References __fort_abort(), __fort_malloc(), __fort_realloc(), ent::adr, CHDR_1DBL, CHDR_1INT, cnt, DEFENTS, ent::ilen, n, r, str, and ent::typ.
Referenced by __fort_copy(), __fort_exchange_counts(), ENTFTN(), mget_recv(), olap_copy(), and olap_recv().
__fort_rstchn()
void __fort_rstchn (struct chdr * c)
Definition at line 83 of file xfer.c.
References n.
__fort_sendl()
void __fort_sendl (struct chdr * c, int indx, void * adr, long cnt, long str, int typ, long ilen)
Definition at line 100 of file xfer.c.
References __fort_abort(), __fort_malloc(), __fort_realloc(), ent::adr, CHDR_1DBL, CHDR_1INT, cnt, DEFENTS, ent::ilen, n, s, str, and ent::typ.
Referenced by __fort_copy(), __fort_exchange_counts(), copy_xfer(), ENTFTN(), mget_send(), olap_copy(), olap_recv(), and olap_send().
__fort_setbase()
void __fort_setbase (chdr * c, char * bases, char * baser, int typ, long ilen)
Definition at line 315 of file xfer.c.
References CHDR_BASE, ent::ilen, and ent::typ.
Referenced by __fort_comm_sked(), and olap_shift().
Variable Documentation
gbuf
char* gbuf static
Definition at line 342 of file xfer.c.
Referenced by __fort_getgbuf().
gbufz
int gbufz static
Definition at line 341 of file xfer.c.
Referenced by __fort_getgbuf().