flang: xfer_heap_dum.c File Reference
xfer_heap_dum.c File Reference
#include "fioMacros.h"
Functions
char * sbrk (int)
char * __fort_sbrk (int len)
void __fort_verghp (char *adr, int len, char *msg)
void __fort_hinit (void)
int __fort_hsend (int cpu, struct ents *e)
int __fort_hrecv (int cpu, struct ents *e)
Function Documentation
__fort_hinit()
void __fort_hinit (void)
Definition at line 34 of file xfer_heap_dum.c.
__fort_hrecv()
int __fort_hrecv (int cpu, struct ents * e)
Definition at line 49 of file xfer_heap_dum.c.
__fort_hsend()
int __fort_hsend (int cpu, struct ents * e)
Definition at line 41 of file xfer_heap_dum.c.
__fort_sbrk()
char * __fort_sbrk (int len)
Definition at line 17 of file xfer_heap_dum.c.
References len, and sbrk().
Referenced by __fort_gettb().
__fort_verghp()
void __fort_verghp (char * adr, int len, char * msg)
Definition at line 27 of file xfer_heap_dum.c.
sbrk()
char * sbrk (int)
Referenced by __fort_gettb(), __fort_sbrk(), and mem().