flang: xfer_rpm1.c File Reference
xfer_rpm1.c File Reference
#include "stdioInterf.h"
#include "fioMacros.h"
Functions
void __fort_erecv (int cpu, struct ents *e)
void __fort_esend (int cpu, struct ents *e)
void __fort_ebcopys (struct ents *ed, struct ents *es)
void __fort_doit (struct chdr *c)
Variables
int __fort_minxfer = 0
Function Documentation
__fort_doit()
void __fort_doit (struct chdr * c)
Definition at line 57 of file xfer_rpm1.c.
References __fort_abort(), __fort_ebcopys(), cp, CPU_COPY, and n.
Referenced by __fort_exchange_counts(), comm_sked_start(), cshift_loop(), ENTFTN(), eoshift_scalar(), gathscat_start(), olap_start(), and recopy().
__fort_ebcopys()
void __fort_ebcopys (struct ents * ed, struct ents * es)
Definition at line 29 of file xfer_rpm1.c.
References __DIST_ENTRY_COPY, __DIST_ENTRY_COPY_DONE, __fort_abort(), __fort_bcopysl(), ents::avl, avl, ents::beg, p, and q.
Referenced by __fort_doit().
__fort_erecv()
void __fort_erecv (int cpu, struct ents * e)
Definition at line 15 of file xfer_rpm1.c.
References __fort_abort().
Referenced by __fort_rbcstl(), and __fort_rrecvl().
__fort_esend()
void __fort_esend (int cpu, struct ents * e)
Definition at line 22 of file xfer_rpm1.c.
References __fort_abort().
Referenced by __fort_rbcstl(), and __fort_rsendl().
Variable Documentation
__fort_minxfer
int __fort_minxfer = 0
Definition at line 11 of file xfer_rpm1.c.