flang: xflag.h File Reference
xflag.h File Reference
Definitions for x-flags handling routines.
#include <stdbool.h>
Functions
bool is_xflag_bitvector (int index)
Query whether x flag index corresponds to a bit vector.
void set_xflag_value (int *xflags, int index, int value)
Set x flag value.
void unset_xflag_value (int *xflags, int index, int value)
Unset x flag value.
Detailed Description
Definitions for x-flags handling routines.
X-flags are an array of integers, some of which are bitvectors and some are just plain values that are used to control compiler's behavior. XBIT macros scattered around the source read those values.
Definition in file xflag.h.
Function Documentation
is_xflag_bitvector()
bool is_xflag_bitvector (int index)
Query whether x flag index corresponds to a bit vector.
Returns
true is it is, false if it corresponds to a plain value
Parameters
index index into x flag array
Does this index correspond to a bitvector (true) or plain value (false)
Definition at line 17 of file xflag.c.
References index.
Referenced by is_xflag_bit(), set_xflag_value(), and unset_xflag_value().
set_xflag_value()
void set_xflag_value (int * xflags, int index, int value)
Set x flag value.
XOR passed value if with existing one if the index corresponds to a bitvector, otherwise just assign it.
Parameters
xflags pointer to x flags array
index index of the element to modify
value mask to apply (or value to set)
Set a value for and x-flag
Definition at line 62 of file xflag.c.
References index, is_xflag_bitvector(), and value().
Referenced by parse_arguments(), and set_xflag().
unset_xflag_value()
void unset_xflag_value (int * xflags, int index, int value)
Unset x flag value.
Bitwise AND passed value if with existing one if the index corresponds to a bitvector, otherwise just set it to zero.
Parameters
xflags pointer to x flags array
index index of the element to modify
value mask to unset (if value is a bit vector)
Clear value for and x-flag
Definition at line 72 of file xflag.c.
References index, and is_xflag_bitvector().
Referenced by parse_arguments(), and set_yflag().