flang: xflag.c File Reference
xflag.c File Reference
X flag handling routines.
#include "flang/ArgParser/xflag.h"
#include <stdbool.h>
Functions
bool is_xflag_bitvector (int index)
Query whether x flag index corresponds to a bit vector.
void set_xflag_value (int *xflags, int index, int value)
Set x flag value.
void unset_xflag_value (int *xflags, int index, int value)
Unset x flag value.
Detailed Description
X flag handling routines.
Definition in file xflag.c.
Function Documentation
is_xflag_bitvector()
bool is_xflag_bitvector (int index)
Query whether x flag index corresponds to a bit vector.
Does this index correspond to a bitvector (true) or plain value (false)
Definition at line 17 of file xflag.c.
References index.
Referenced by is_xflag_bit(), set_xflag_value(), and unset_xflag_value().
set_xflag_value()
void set_xflag_value (int * xflags, int index, int value)
Set x flag value.
Set a value for and x-flag
Definition at line 62 of file xflag.c.
References index, is_xflag_bitvector(), and value().
Referenced by parse_arguments(), and set_xflag().
unset_xflag_value()
void unset_xflag_value (int * xflags, int index, int value)
Unset x flag value.
Clear value for and x-flag
Definition at line 72 of file xflag.c.
References index, and is_xflag_bitvector().
Referenced by parse_arguments(), and set_yflag().