flang: xref.cpp File Reference
xref.cpp File Reference
Fortran module responsible for generating Cross Reference Listing.
#include "xref.h"
#include "gbldefs.h"
#include "error.h"
#include "global.h"
#include "listing.h"
#include "symtab.h"
#include "dtypeutl.h"
#include "symfun.h"
Classes
struct memitem
struct RGN
Macros
#define ENDOFLINE 80
#define SORTLIM 16
#define WIDTH 8
Functions
void xrefinit (void)
...
void xrefput (SPTR symptr, int usage)
write one reference record to Reference File.
static void putentry (int elem)
write two lines of info for symbol elem to listing.
static void printxref (SPTR liststart)
static SPTR insertsrt (int q, int r)
static SPTR merge (int q, int r)
static SPTR mergesrt (int low, int high)
void xref (void)
...
void par_xref_put (int lineno, SPTR sym, int sc)
...
static int find_rgn (int lineno)
static void add_to_list (int *list, int index)
static void par_body (const char *hdr, int *list)
static void print_par_xref (void)
void par_xref (void)
...
Variables
static FILE * fd
static int xrefcnt
static struct memitem * baseptr
static RGN * rgn_base
static int rgn_avl
static int rgn_size
static int rgn_cur
Detailed Description
Fortran module responsible for generating Cross Reference Listing.
Definition in file xref.cpp.
Macro Definition Documentation
ENDOFLINE
#define ENDOFLINE 80
SORTLIM
#define SORTLIM 16
WIDTH
#define WIDTH 8
Function Documentation
add_to_list()
static void add_to_list (int * list, int index) static
Definition at line 401 of file xref.cpp.
References baseptr, index, list, prev, s, and memitem::use.
Referenced by par_xref().
find_rgn()
static int find_rgn (int lineno) static
Definition at line 363 of file xref.cpp.
References i, lineno, RGN::lineno, NEED, RGN::next, RGN::prev, RGN::Private, rgn_avl, rgn_base, rgn_cur, rgn_size, and RGN::shared.
Referenced by par_xref().
insertsrt()
static SPTR insertsrt (int q, int r) static
Definition at line 202 of file xref.cpp.
References i, last, next, q, r, SPTR_NULL, SYMNAME, and XREFLKG.
Referenced by mergesrt().
merge()
static SPTR merge (int q, int r) static
Definition at line 230 of file xref.cpp.
References i, j, k, q, r, and SYMNAME.
Referenced by mergesrt().
mergesrt()
static SPTR mergesrt (int low, int high) static
Definition at line 255 of file xref.cpp.
References insertsrt(), merge(), mergesrt(), p, q, r, and SORTLIM.
Referenced by mergesrt(), and xref().
par_body()
static void par_body (const char * hdr, int * list) static
Definition at line 421 of file xref.cpp.
References baseptr, buf, cnt, list, list_line(), s, strlen(), SYMNAME, memitem::use, and WIDTH.
Referenced by print_par_xref().
par_xref()
void par_xref (void)
...
Definition at line 468 of file xref.cpp.
References add_to_list(), baseptr, ERR_Fatal, fclose(), fd, find_rgn(), flg, FREE, i, index, interr(), memitem::lineno, RGN::lineno, memitem::link, NEW, RGN::next, NULL, RGN::prev, print_par_xref(), RGN::Private, rgn_avl, rgn_base, rgn_cur, rgn_size, RGN::shared, sptr, memitem::type, memitem::use, FLG::xref, and xrefcnt.
par_xref_put()
void par_xref_put (int lineno, SPTR sym, int sc)
...
Definition at line 335 of file xref.cpp.
References ERR_Fatal, fd, interr(), lineno, memitem::lineno, memitem::link, memitem::type, memitem::use, and xrefcnt.
print_par_xref()
static void print_par_xref (void) static
Definition at line 451 of file xref.cpp.
References buf, i, lineno, list_line(), list_page(), next, RGN::next, par_body(), and rgn_base.
Referenced by par_xref().
printxref()
static void printxref (SPTR liststart) static
Definition at line 155 of file xref.cpp.
References assert, baseptr, buf, ENDOFLINE, ERR_Severe, i, lineno, memitem::link, list_line(), list_page(), putentry(), sptr, SPTR_NULL, use, and XREFLKG.
Referenced by xref().
putentry()
static void putentry (int elem) static
write two lines of info for symbol elem to listing.
Definition at line 72 of file xref.cpp.
References buf, getdtype(), ISZ_PF, list_line(), parmprint(), stb, strlen(), STB::stypes, and SYMNAME.
Referenced by printxref().
xref()
void xref (void)
...
Definition at line 276 of file xref.cpp.
References baseptr, ERR_Fatal, fclose(), fd, FREE, i, index, interr(), memitem::link, mergesrt(), NEW, NULL, printxref(), sptr, SPTR_NULL, stb, memitem::type, XBIT, xrefcnt, XREFLKG, and XREFLKP.
Referenced by main(), and process_input().
xrefinit()
void xrefinit (void)
...
Definition at line 36 of file xref.cpp.
References baseptr, errfatal(), fd, NULL, tmpfile(), and xrefcnt.
Referenced by reinit().
xrefput()
void xrefput (SPTR symptr, int usage)
write one reference record to Reference File.
...
Definition at line 52 of file xref.cpp.
References ERR_Fatal, fd, gbl, interr(), memitem::lineno, memitem::link, memitem::type, memitem::use, and xrefcnt.
Variable Documentation
baseptr
struct memitem* baseptr static
Definition at line 31 of file xref.cpp.
Referenced by add_to_list(), par_body(), par_xref(), printxref(), xref(), and xrefinit().
fd
FILE* fd static
Definition at line 29 of file xref.cpp.
Referenced by par_xref(), par_xref_put(), xref(), xrefinit(), and xrefput().
rgn_avl
int rgn_avl static
Definition at line 358 of file xref.cpp.
Referenced by find_rgn(), and par_xref().
rgn_base
RGN* rgn_base static
Definition at line 357 of file xref.cpp.
Referenced by find_rgn(), par_xref(), and print_par_xref().
rgn_cur
int rgn_cur static
Definition at line 360 of file xref.cpp.
Referenced by find_rgn(), and par_xref().
rgn_size
int rgn_size static
Definition at line 359 of file xref.cpp.
Referenced by find_rgn(), and par_xref().
xrefcnt
int xrefcnt static
Definition at line 30 of file xref.cpp.
Referenced by par_xref(), par_xref_put(), xref(), xrefinit(), and xrefput().