flang: xref.c File Reference
xref.c File Reference
Fortran module responsible for generating Cross Reference Listing.
#include "gbldefs.h"
#include "global.h"
#include "error.h"
#include "symtab.h"
#include "dtypeutl.h"
Classes
struct memitem
Macros
#define ENDOFLINE 80
#define SORTLIM 16
Typedefs
typedef short int LINENOTYPE
typedef short int USETYPE
Functions
void xrefinit (void)
...
void xrefput (int symptr, int usage)
Write one reference record to Reference File:
static void putentry (int elem)
static void printxref (int liststart)
static int insertsrt (int q, int r)
static int merge (int q, int r)
static int mergesrt (int low, int high)
void xref (void)
...
Variables
static FILE * fd
static int xrefcnt
static struct memitem * baseptr
Detailed Description
Fortran module responsible for generating Cross Reference Listing.
Definition in file xref.c.
Macro Definition Documentation
ENDOFLINE
#define ENDOFLINE 80
SORTLIM
#define SORTLIM 16
Typedef Documentation
LINENOTYPE
typedef short int LINENOTYPE
Definition at line 19 of file xref.c.
USETYPE
typedef short int USETYPE
Definition at line 20 of file xref.c.
Function Documentation
insertsrt()
static int insertsrt (int q, int r) static
Definition at line 203 of file xref.c.
References i, last, next, q, r, SYMNAME, and XREFLKG.
Referenced by mergesrt().
merge()
static int merge (int q, int r) static
Definition at line 230 of file xref.c.
References i, j, k, q, r, and SYMNAME.
Referenced by mergesrt().
mergesrt()
static int mergesrt (int low, int high) static
Definition at line 259 of file xref.c.
References insertsrt(), merge(), mergesrt(), p, q, r, and SORTLIM.
Referenced by mergesrt(), and xref().
printxref()
static void printxref (int liststart) static
Definition at line 156 of file xref.c.
References assert, baseptr, buf, ENDOFLINE, i, lineno, memitem::link, list_line(), list_page(), putentry(), sptr, use, and XREFLKG.
Referenced by xref().
putentry()
static void putentry (int elem) static
Definition at line 66 of file xref.c.
References buf, getdtype(), ISZ_PF, list_line(), parmprint(), stb, strlen(), STB::stypes, and SYMNAME.
Referenced by printxref().
xref()
void xref (void)
...
Definition at line 279 of file xref.c.
xrefinit()
void xrefinit (void)
...
Definition at line 35 of file xref.c.
xrefput()
void xrefput (int symptr, int usage)
Write one reference record to Reference File:
Definition at line 49 of file xref.c.
References fd, gbl, interr(), memitem::lineno, memitem::link, memitem::use, and xrefcnt.
Referenced by chk_fmtid(), declobject(), declref(), declsym(), fixup_param_vars(), gen_dinit(), getocsym(), mkmember(), ptrsubr_call(), ref_based_object_sc(), refsym(), refsym_inscope(), semant1(), semant3(), and subr_call2().
Variable Documentation
baseptr
struct memitem* baseptr static
Definition at line 30 of file xref.c.
Referenced by printxref(), ref_pd(), xref(), and xrefinit().
fd
FILE* fd static
Definition at line 28 of file xref.c.
Referenced by xref(), xrefinit(), and xrefput().
xrefcnt
int xrefcnt static
Definition at line 29 of file xref.c.
Referenced by xref(), xrefinit(), and xrefput().