flang: xref.h File Reference
xref.h File Reference
#include "gbldefs.h"
#include "global.h"
Functions
void par_xref_put (int lineno, SPTR sym, int sc)
...
void par_xref (void)
...
void xrefinit (void)
...
void xrefput (SPTR symptr, int usage)
...
void xref (void)
...
Function Documentation
par_xref()
void par_xref (void)
...
Definition at line 468 of file xref.cpp.
References add_to_list(), baseptr, ERR_Fatal, fclose(), fd, find_rgn(), flg, FREE, i, index, interr(), memitem::lineno, RGN::lineno, memitem::link, NEW, RGN::next, NULL, RGN::prev, print_par_xref(), RGN::Private, rgn_avl, rgn_base, rgn_cur, rgn_size, RGN::shared, sptr, memitem::type, memitem::use, FLG::xref, and xrefcnt.
par_xref_put()
void par_xref_put (int lineno, SPTR sym, int sc)
...
Definition at line 335 of file xref.cpp.
References ERR_Fatal, fd, interr(), lineno, memitem::lineno, memitem::link, memitem::type, memitem::use, and xrefcnt.
xref()
void xref (void)
...
Definition at line 279 of file xref.c.
References a4tos1(), baseptr, condec(), DECL_LINE, ERR_Fatal, fclose(), fd, files, FREE, g_1, i, index, interr(), s4_s::item, j, k, line, memitem::link, files_s::lstfil, lsthed, mergesrt(), movstr(), n, NEW, s4_s::nextt, NULL, g_1_s::numprd, g_1_s::nvoc, output(), g_1_s::prdind, printxref(), g_1_s::prodcn, rel(), switches_s::runosw, s4, sptr, SPTR_NULL, stb, switches, memitem::type, g_1_s::vocab, wtline(), wtpage(), XBIT, xrefcnt, XREFLKG, and XREFLKP.
xrefinit()
void xrefinit (void)
...
Definition at line 35 of file xref.c.
References baseptr, errfatal(), fd, NULL, tmpfile(), and xrefcnt.
xrefput()
void xrefput (SPTR symptr, int usage)
...
...
Definition at line 52 of file xref.cpp.
References ERR_Fatal, fd, gbl, interr(), memitem::lineno, memitem::link, memitem::type, memitem::use, and xrefcnt.